### ISSUE TITLE
Type guards should not apply equally to both "then" and "else" branches of conditional

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#10006]
**TypeScript Version:**  nightly

**Code**

```ts
function isString(x: number | string): x is string {
    return typeof x === "string";
}

const x: number | string = "1";

const num: number = isString(x) ? parseInt(x, 10) : x;
let num2: number;
if (isString(x)) num2 = parseInt(x, 10); else num2 = x;

const str: string = isString(x) ? x : x;
let str2: string;
if (isString(x)) str2 = x; else str2 = x;
```

**Expected behavior:**

Each `num` case should compile fine.
* In the "then" branch of each, `x` is a string, so `parseInt` should succeed and return a number.
* In the "else" branch of each, `x` is not a string, so it's a number.

Each `str` case should fail.
* In the "then" branch of each, `x` is a string, so it's fine.
* In the "else" branch of each, `x` is not a string, so it should fail.

**Actual behavior:** 

**`x` appears to be considered a string in *both* branches of the conditional.**

    src/a.ts(7,7): error TS2322: Type 'number | string' is not assignable to type 'number'.
      Type 'string' is not assignable to type 'number'.
    src/a.ts(9,47): error TS2322: Type 'string' is not assignable to type 'number'.

The code compiles fine if every `isString(x)` is replaced by `typeof x === "string"`.

**Comment by RyanCavanaugh** [comment]
Now compiles without error
