### ISSUE TITLE
Can't iterate over (U)Int8Array, (U)Int16Array, (U)Int32Array, etc. using for ... of

### ISSUE THREAD

**Issue by SetTrend** [Microsoft/TypeScript#10005]
This small piece of code doesn't compile:

``` ts
const bytes = new Uint8Array(8);
window.crypto.getRandomValues(bytes);
for (const byte of bytes) { }
```

This is the error that's being generated:

```
C:\Temp>node tsc test.ts
test.ts(5,20): error TS2495: Type 'Uint8Array' is not an array type or a string type.
```

**Comment by andru255** [comment]
@SetTrend By default Typescript allows types number, boolean, string, any. Please See: https://www.typescriptlang.org/docs/handbook/basic-types.html

**Comment by yortus** [comment]
Sounds like you are targeting ES5, for which TypeScript offers limited `for..of` support. There are related issue about this, like #4947, #6842, #5329, and #3164.

**Comment by SetTrend** [comment]
Thanks, @yortus, for your enlightening answer.

I believe #3164 gets closest to what I would have imagined for having targetted ES5.

Are there plans to have `for ... of` get this functionality for ES5, too? We're forced to target IE11 at many corporated places.

**Comment by yortus** [comment]
@SetTrend I couldn't speak for what the TypeScript team's plans are, but looking at the comments in those linked issues (and also in #4031), there seems to be some sympathy for users but no concrete plans.

**Comment by mhegazy** [comment]
This should be addressed by https://github.com/Microsoft/TypeScript/pull/12346 under `--downlevelIteration`. Make sure `es2015.iterable` is part of your `--lib` arguments.
