### ISSUE TITLE
Using TSX without a reactNamespace

### ISSUE THREAD

**Issue by kay-is** [Microsoft/TypeScript#10008]
Using TSX with libraries that just provide a function doesn't work, because `tsc` always requires `createElement`.

I found only two ways around this, which both seem sub-optimal. One is to `preserve` and let another compiler handle JSX, the other is to patch the virtual dom library to provide a `createElement` method.

There should be a way to simply use `libFn(...)` instead of `lib.createElement(...)`

**Comment by nippur72** [comment]
I think this is being discussed at #9582

**Comment by kay-is** [comment]
ah, yes. thank you :)
