### ISSUE TITLE
Type cast breaks type guard

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#10007]
**TypeScript Version:**  nightly

**Code**

```ts
function isString(x: number | string): x is string {
    return typeof x === "string";
}

function f(x: {}): string | undefined {
    if (isString(<number | string> x))
        return x;
}
```

**Expected behavior:**
Compiles with no errors.

**Actual behavior:** 

    src/a.ts(7,16): error TS2322: Type '{}' is not assignable to type 'string'.

**Comment by ahejlsberg** [comment]
The expression `isString(<SomeType>x)` is not considered a type guard, so the type of `x` is still `{}` in the return statement. To be considered a type guard, the argument to a type predicate function must be a simple identifier or a dotted name.
