### ISSUE TITLE
2.0 beta: "dom.iterable.d.ts" won't load

### ISSUE THREAD

**Issue by mindplay-dk** [Microsoft/TypeScript#10002]
In my `tsconfig.json`, I'm trying to load `dom.iterable` by adding it to `lib` - I can see [the file](https://github.com/Microsoft/TypeScript/blob/87e95069fc6a5a46804f7328a8ef0d180e17734a/lib/lib.dom.iterable.d.ts) exists in the 2.0 beta, but the compiler refuses to recognize the option.

> error TS6046: Argument for '--lib' option must be:  'es5', 'es6', 'es2015', 'es7', 'es2016', 'es2017', 'dom', 'webworker', 'scripthost', 'es2015.core', 'es2015.collection', 'es2015.generator', 'es2015.iterable', 'es2015.promise', 'es2015.proxy', 'es2015.reflect', 'es2015.symbol', 'es2015.symbol.wellknown', 'es2016.array.include', 'es2017.object', 'es2017.sharedmemory'

Doesn't look like any of the other lib `.d.ts` files reference this one?

I need `DOMTokenList` from this `lib` file in my project - how do I get it?

**Comment by mhegazy** [comment]
The fix should be in tonight's `typescript@next`. give it a try.
