### ISSUE TITLE
Unchangeable methods of class

### ISSUE THREAD

**Issue by rezfedor** [Microsoft/TypeScript#10003]
Hi all!
TypeScript is The Best!
My short question in code:
```ts
class SomeClass {
  public Method(): void { }
}
let _a: SomeClass = new SomeClass();
_a.Method = null; // I don't want to use this javascript functionality
/* or
_a.Method = undefined;
_a.Method = function () { }
*/
```
I want the methods of my SomeClass to be unchangeable. At the same time I want to have the possibility to override Method for AnotherClass
```ts
class AnotherClass extends SomeClass {
  public Method(): void {
    super.Method();
  }
}
```
My proposal is to add a compiler flag like `--unchangeableClassMethod` or `--strictClassMethodDeclaration` and compilation behavior like
```ts
class SomeClass {
  public Method(): void { }
}

let _a: SomeClass = new SomeClass();
_a.Method = <something>; // <- Error

class AnotherClass extends SomeClass {
  public Method(): void { // override is ok
    super.Method();
  }
}
```
WBR!

**Comment by rezfedor** [comment]
At least one comment?

**Comment by mhegazy** [comment]
I do not think there is much we can do here. the type system in TypeScript is structureal, so the general case can not be addressed here. consider:

```ts
class SomeClass {
  public Method(): void { }
}

var s: SomeClass = {   Method () {  } }; // OK

```

checkout  https://github.com/Microsoft/TypeScript/wiki/FAQ#what-is-structural-typing for more details.
