### ISSUE TITLE
[Suggestion] Compiler option to force private/static or proteced

### ISSUE THREAD

**Issue by movedoa** [Microsoft/TypeScript#10004]
It would be nice to have a compiler option that forces the dev to define private static or protected for all members.
This would help to keep the code consistent.

**Comment by maiermic** [comment]
Sounds more like a job for TSLint to me. You can [write a custom rule](http://palantir.github.io/tslint/develop/custom-rules/) to keep code consistent the way you like.

**Comment by RyanCavanaugh** [comment]
Agreed. We generally don't add switches to control stylistic enforcement.
