### ISSUE TITLE
New Website Logo: sli.do

### ISSUE THREAD

**Issue by DominikPalo** [Microsoft/TypeScript#10001]
- Name: sli.do
- Homepage url: https://www.sli.do
- Brand Guidelines/Licensing: -
- Logo: http://assets.sli.do/logo.svg

**Comment by RyanCavanaugh** [comment]
@yahiko00 / @zzzen - why :-1: ? Just making sure there's not anything weird going on here

**Comment by yahiko00** [comment]
I though it was some advertising. But it seems it is not.
