### ISSUE TITLE
for-loop labels cannot be renamed

### ISSUE THREAD

**Issue by antonkh** [microsoft/TypeScript#10019]
I'm using tsc 2.0.0 in vs 2015 (with update 3 installed) and trying to rename a for-loop label:

``` ts
loop: for (const item of items) {
  for (let i = 0; i < n; i++) {
    if (test(i, item))
      continue loop;
  }
}
```

The ts language service says "You cannot rename this element." However when I click on the `loop` label, it correctly highlights all its occurrences.

**Comment by aluanhaddad** [comment]
Why would this be an issue? The highlighting you are seeing is textual not semantic (I'm not 100% positive). In this example, recursion, (I know there isn't PTC in most browsers yet) really would make for clearer code.

**Comment by epicgirl1998** [comment]
> Why would this be an issue?

labels are a v (short for very) underused language feature and i dont see why they shouldn't be renamable

[you can even use them for weird goto-like control flow](https://gist.github.com/epicgirl1998/1b3581e4700b5db241b6277ee329abd1) (`break check` == `goto error`)

> The highlighting you are seeing is textual not semantic (I'm not 100% positive)

i think they are highlighted correctly:

![untitled](https://cloud.githubusercontent.com/assets/25940153/25233406/5e2fab3a-25e7-11e7-94ed-234b90b347ec.png)

**Comment by DanielRosenwasser** [comment]
Thank you @a-tarasyuk!
