### ISSUE TITLE
Support 'Organize Imports' feature

### ISSUE THREAD

**Issue by akosyakov** [Microsoft/TypeScript#10020]
It should:
- remove unused imports;
- remove duplicate imports;
- add imports for unresolved elements;
- ask a user to disambiguous imports in the case if several can be used for an unresolved element.

**Comment by basarat** [comment]
Personal Opinion: Nice idea for quickfixes / additional refactorings to be added into release 2.1 : https://github.com/Microsoft/TypeScript/wiki/Roadmap#21 :rose:

**Comment by johnnyreilly** [comment]
I'd love to see this implemented.

**Comment by akosyakov** [comment]
It would be also nice if this feature respects `index.ts` files and imports stuff with the shortest possible import declaration.

**Comment by niklas-dahl** [comment]
would be awesome if it could unite imports, too.

from
```
import { Component } from '@angular/core';
import { Input } from '@angular/core';
```
to
```
import { Component, Input } from '@angular/core';
```

**Comment by RyanCavanaugh** [comment]
Here's a nice test file https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/model/editableTextModel.ts

**Comment by MgSam** [comment]
It would also be great if this feature alphabetized both the objects inside the `import {}` brackets and the import lines themselves (by file path).

So this:

``` TypeScript
import { Foo, Bar } from './banana';
import { Dog, Cat } from './apple';
```

becomes this:

``` TypeScript
import { Cat, Dog } from './apple';
import { Bar, Foo } from './banana';
```

**Comment by pelotom** [comment]
TSLint has a rule for this: [`ordered-imports`](https://palantir.github.io/tslint/rules/ordered-imports/). And it’s auto-fixable.

**Comment by jbrownson** [comment]
It'd be nice if it were inserted in order in the first place so it didn't require the extra auto-fix steps

**Comment by madhugb** [comment]
Right now sort will put the imports on top of the document, and it moves the comments / copyright / author info to the bottom of imports.

Is there a way to preserve the comments on top of the document?

**Comment by amcasey** [comment]
@jbrownson, sort on import is covered by https://github.com/Microsoft/TypeScript/issues/16119.

**Comment by amcasey** [comment]
@madhugb How are you sorting?  I didn't think any of the editors had shipped a version consuming the new `organizeImports` protocol command.

**Comment by amcasey** [comment]
@MgSam I believe that was covered by https://github.com/Microsoft/TypeScript/pull/21909.

**Comment by amcasey** [comment]
@niklas-dahl I believe that was covered by #21909.

**Comment by amcasey** [comment]
@akosyakov at present, we're retaining module specifiers as-is.  Would you mind filing a new issue suggesting they be simplified when possible?

**Comment by amcasey** [comment]
Also note that adding missing imports is being handled separately using code fixes (which should support fix-all).
