### ISSUE TITLE
Optional parameters defined before a checked parameter should be checked

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#10030]
If the second parameter is asserted as not optional, the first parameter is not optional.

**TypeScript Version:**  master

**Code**

``` ts
function f(a?: number, b?: number): number {
  return b ? a : 0;
}
```

**Expected behavior:**

```
$ node built/local/tsc.js --strictNullChecks index.ts
```

**Actual behavior:** 

```
$ node built/local/tsc.js --strictNullChecks index.ts
index.ts(2,10): error TS2322: Type 'number | undefined' is not assignable to type 'number'.
  Type 'undefined' is not assignable to type 'number'.
```

**Comment by sandersn** [comment]
Note that this narrowing relies on #10014 because that issue would make `f(undefined, 9)` an error.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
