### ISSUE TITLE
specify common project root for outDir when manually requiring declaration files outside of common root

### ISSUE THREAD

**Issue by saosebastiao** [Microsoft/TypeScript#10037]
**TypeScript Version:** nightly (2.0.0-dev.201xxxxx)

**Code**

``` ts
// A *self-contained* demonstration of the problem follows...
{
  "buildOnSave": true,
  "compileOnSave": true,
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "moduleResolution": "node",
    "outDir": "./bin",
    "lib": ["dom","es5","es2015"],
    "allowJs": true,
    "sourceMap": true
  },
  "include": [
    "src/**/*.*"
  ],
  "files":  [
    "./node_modules/axios/axios.d.ts"
  ],
  "exclude": [
    "node_modules"
  ]
}

```

**Expected behavior:**

./src/foo.ts generates ./bin/foo.js

**Actual behavior:** 

./src/foo.ts generates ./bin/src/foo.js

**Notes**
I recognize that this behavior is intended as the output of outDir computes a common path, and manually including the axios definition file makes "src/" no longer common. 

I tried resolving this using the new baseUrl feature `baseUrl: "node_modules"` and manually specifying `paths: { "axios": [ "./node_modules/axios/axios.d.ts" ] }`, but the module resolution algorithm still ends up resolving to `./node_modules/axios/index.js` before recognizing the `.d.ts` file, and therefore doesn't recognize interfaces that are defined in axios.d.ts and elided in index.js. 

Is there any way to allow for custom declaration resolution without polluting the common base directory resolution done with outDir?

**Comment by saosebastiao** [comment]
Would using the `types` compiler option work for this?

**Comment by mhegazy** [comment]
set `--rootDir`. See https://github.com/Microsoft/TypeScript/wiki/FAQ#why-does---outdir-moves-output-after-adding-a-new-file for more info.
