### ISSUE TITLE
Breaking change review: Enums and types with the same name

### ISSUE THREAD

**Issue by RyanCavanaugh** [Microsoft/TypeScript#10039]
This file has breaks in `master` https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/voximplant-websdk/voximplant-websdk.d.ts

The basic file structure was
```ts
declare enum A { X, Y, Z }
declare namespace A {
  interface X { }
  interface Y { }
  interface Z { }
}
var x: A.X | A.Y | A.Z;
```
This used to compile without error and worked as anticipated; we now get errors:
> error TS2300: Duplicate identifier 'X'.
> error TS2535: Enum type 'A' has members with initializers that are not literals.

I could see taking this as a breaking change, but if the enum member type isn't going to be usable anyway, why are we bothering to declare a name for it? It seems better to *not* bind a type and instead report a customized error in the checker when type resolution fails (as we do in a few other resolution cases).

**Comment by ahejlsberg** [comment]
During binding we don't know if an enum's members are going to be usable as enum literal types, so we always reserve the type meaning and then report errors in the type checker later if the enum doesn't meet the requirements. In this particular case the enum actually does qualify as a union enum, so there truly is a conflict. I think the breaking change is the right thing to do here so we can clearly state that an enum member is always both a value and a type (even if it is an error to use the type).
