### ISSUE TITLE
Built-in functions (e.g. isFinite) type guard and accepting null | undefined (strictNullChecks)

### ISSUE THREAD

**Issue by Deathspike** [microsoft/TypeScript#10038]
**TypeScript Version:**  2.0.0

**Code**

``` ts
// --strictNullChecks
interface IExample {
  value?: number;
}

let example: IExample = {};
if (isFinite(example.value)) { // Accept possibly `undefined`
  let a = example.value; // Narrow to `number`
}


```

**Expected behavior:**
- isFinite should accept `number | null | undefined` rather than strictly `number`.
- isFinite should act as a type guard.

**Actual behavior:** 
Won't compile because `isFinite` is not accepting `undefined` and is not a type guard.

**Proposal:**

Change:

`declare function isFinite(number: number): boolean;`

To:

`declare function isFinite(number: number | null | undefined): number is number;`

I'm pretty sure there are other functions that could use the same love.
I don't mind putting in some hours if this is an accepted direction to take. Let me know :)

**Comment by RyanCavanaugh** [comment]
Be sure to read contributing.md for instructions on how to make lib.d.ts changes

**Comment by jeffreymorlan** [comment]
`isFinite(null)` actually returns true (null gets coerced to 0)

**Comment by RyanCavanaugh** [comment]
> isFinite(null) actually returns true (null gets coerced to 0)

JavaScript (╯°□°)╯︵ ┻━┻

It's probably best to *not* allow `null`, then?

**Comment by danthegoodman** [comment]
`isFinite('0')` also returns true. `Number.isFinite('0')` returns false, but is only available in ES6 land.

Since these functions can take any type for input, I'd like to see the parameter type changed to `any`.

**Comment by RyanCavanaugh** [comment]
What are people passing a string to `isFinite` attempting to determine about that string?

**Comment by danthegoodman** [comment]
For `isFinite`, I suppose the developer is trying to determine if the input can be coerced into a finite number.

For `Number.isFinite`, I am reading in an `any` and doing a runtime check to ensure the value is a finite number, so not `NaN`, `Infinity`, `'0'` or `null`.

**Comment by mhegazy** [comment]
`any` is the accurate representation of the spec. but we opted into making strict to catch cases more error cases, that otherwise would be masked by coercion, e.g. `isFinite(getNumber)` instead if `isFinite(getNumber())`. I suppose changing the type to `number|string|null|undefined` would be safer.

**Comment by athasach** [comment]
It would also be useful if it returned a type predicate.
```ts
isFinite(number: number|string|null|undefined): number is number;
```

**Comment by RyanCavanaugh** [comment]
@athasach it can't do that, because it coerces its argument. All `isFinite` (the global) tells you is if the coerced version of the argument parsed to a finite value; `isFinite("30")` is `true` but `"30"` is not a `number`

**Comment by athasach** [comment]
@RyanCavanaugh I should have specified `Number.isFinite`, which doesn’t coerce the value as far as I know.

**Comment by bfricka** [comment]
Bumping this. According to the spec, `Number.isFinite` and similar `Number` do not throw, nor do they specify type constraints.
https://www.ecma-international.org/ecma-262/10.0/index.html#sec-number.isfinite

```
If Type(number) is not Number, return false.
If number is NaN, +∞, or -∞, return false.
Otherwise, return true.
```
That's it. Very simple. There are is no reason for this and similar functions to be constrained as such as these constraints do not follow the spec itself. This isn't a huge deal as it's easy to extend the types, e.g.
```ts
interface NumberConstructor {
  isFinite(v?: any): v is number
}
```

**Comment by sqpdln** [comment]
this can definitely be improved. for example when doing: 

```
function secondsSinceX(x: number | undefined): number {
  if (Number.isFinite(x)) {
    assert(x > 1)
...
  }
...
}
```
typescript warns me about the `x` in the assert that `Object is possibly 'undefined'`. but `x` cannot possibly be `undefined` in this case.

**Comment by Juraj-Masiar** [comment]
> typescript warns me about the `x` in the assert that `Object is possibly 'undefined'`. but `x` cannot possibly be `undefined` in this case.

I agree. Reported as a new issue here; https://github.com/microsoft/TypeScript/issues/43792

**Comment by santiagopuentep** [comment]
I use `if (!Number.isFinite(myVar)) throw new Error("Wrong");` and typescript complains later that `myVar` could be `undefined`, but `Number.isFinite()` catches that in Javascript. It's a bug.

This issue https://github.com/Microsoft/TypeScript/issues/15527 was closed automatically but never fixed.

**Comment by Juraj-Masiar** [comment]
The problem is that type guard needs to work for all values of the specified type, not just a subset (otherwise you would get wrong narrowed type in the `else` branch, even though it could still be a number).
**See this issue about better type guards that would allow it: https://github.com/microsoft/TypeScript/issues/15048**

**Comment by monfera** [comment]
Can this be fixed please? `Number.isFinite` yielding `true` somehow makes TS think it might still be a number

![image](https://user-images.githubusercontent.com/1548516/134203125-24215cc5-f2dc-4d3e-bcec-2109fe14eb5d.png)

**Comment by santiagopuentep** [comment]
@Juraj-Masiar Sorry, I just saw this.

I still don't understand, the Number.isFinite(myVar) still could never be undefined, and it still complains that it could be. Shouldn't TypeScript handle this natively, like it does with typeof, since it's a native function?

@monfera is having a similar problem.

**Comment by monfera** [comment]
The first half of the issue, at least for `Number.isFinite`, seems to be solved by now: it can take an unknown arg. [Playground](https://www.typescriptlang.org/play?#code/MYewdgzgLgBGBcBXMBrMIDuYYF4YCIUAbFAKyPwChKB6GmAUwA8AHB4KBgExihBgBmAQwCWRSqEggiDAHREQAcwAU2ANQwAjAEpqdRq3acefGCyEQIAGhhCwPEbC4gGESiIHKoATzYgBcLg4eADkYIgAtgBGDABOIdowkhDScgoq6lq6tPTMbBzcvPzmljZRiLCOMM6ucCBQ7p4AcpExsbIiEABiImCODKraicmp8kqqMBo6lEA): 
```
const n:unknown = "klkjl"

// expected to fail
console.log(n + 1) // squiggly under n

// expected to pass, and it does
if(typeof n === 'number') console.log(n + 1) // no squiggly under n

// expected to pass, but it does not
if(Number.isFinite(n)) console.log(n + 1) // no squiggly under the first occurrence but there's a squiggly under the second
```

I feel utterly defeated by TS when having to type `if(typeof n === 'number' && Number.isFinite(n)) ...` It's a "TS you had one job" moment, it looks so trivial (`Number.isFinite` yields true: it is a number), and this issue has been open for 5 years. TS is not just a JS overlay, it alters the way we write code, usually for the better, but can sometimes degrade runtime code quality via requiring extra hoops and adding code noise and payload bulk. I wish that the semantics of the JS substrate, governed by standards, get increased respect especially in low hanging fruit situations like this

**Comment by Juraj-Masiar** [comment]
If I understand the problem correctly, the issue with the "else" branch.
Sure, if the number is finite then it's obviously not undefined, but if it's not finite, what is the type? What type should TypeScript use in the else branch?
```ts
function isFinite(x: number): x is number {
  return Number.isFinite(x);
}
// let's say you have a number that can be finite, or not
const x: number = Math.random() < 0.5 ? Infinity : 42;
if (isFinite(x)) {
    const finiteNumber: number = x;
}
else {
    const neverNumber: never = x;   // WHAT??? Exactly! The "x" has now "never" type :(
}
```
[See in the playground.](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABDAzgMRmGUCmAKADwC5EwQBbAIxwCcBKEg5FUi6mxAbwFgAoRRDRxQQNJADk2tAHSoMWXIToBuPgF8+Aek2IANsIDkLFAEMAnojNwQiABYmAbjkQnWVWoij2oiCCaTUiMCY2DgANIhwHGBwUHwQCCg+xG7siAC8iACyJl7SNP4AJnDkeHSIADyIAAzSAKyIAPyIAJJgwQoWJAAsAEyqvDDAiHhyIYoEdOU8-AK+iT4doZLuNCRkqxmIBAMavDi6KM4zc-NgSaQ4TjQr7OtXHpk7c9qIAOoAEgCCACqN-4gAKIEEzQXRmACEiB+tmcACICHC7CYWDEAO6IOFgB40JFQMwAB2cRDw6j4fCAA)

**Comment by monfera** [comment]
The urgent and trivial (to humans and machines to infer) thing would be the _then_ branch, it'd be useful even if the _else_ branch can't narrow. I don't propose numeric value related semantics (Infinity vs 42) as that can become NP hard, just solving the self-explanatory part. Thanks @Juraj-Masiar for the link to the one-sided type guards, I had no idea there were architectural limitations that blocked these

**Comment by mcaskill** [comment]
As far as I can understand this issue, my recent troubles with this issue, the current implementation of TypeScript (4.5.4), and the specifications of ECMAScript on the matter, both typings are wrong and should look something more like:

[`isFinite`][ts-isFinite]:

```diff
/**
 * Determines whether a supplied number is finite.
 * @param number Any numeric value.
 */
- declare function isFinite(number: number): boolean;
+ declare function isFinite(number: unknown): boolean;
```
> 1. Let `num` be ? `ToNumber(number)`.
> 2. If `num` is `NaN`, `+∞𝔽`, or `-∞𝔽`, return `false`.
> 3. Otherwise, return `true`.
> 
> — [19.2.2 isFinite][ecma-isFinite], ECMA-262

[`NumberConstructor.isFinite`][ts-NumberConstructor.isFinite]:

```diff
/**
 * Returns true if passed value is finite.
 * Unlike the global isFinite, Number.isFinite doesn't forcibly convert the parameter to a
 * number. Only finite values of the type number, result in true.
 * @param number A numeric value.
 */
- isFinite(number: unknown): boolean;
+ isFinite(number: unknown): number is number;
```

> 1. If `Type(number)` is not `Number`, return `false`.
> 2. If `number` is `NaN`, `+∞𝔽`, or `-∞𝔽`, return `false`.
> 3. Otherwise, return `true`.
> 
> — [21.1.2.2 Number.isFinite][ecma-Number.isFinite], ECMA-262

[ts-isFinite]: https://github.com/microsoft/TypeScript/blob/v4.5.4/src/lib/es5.d.ts
[ts-NumberConstructor.isFinite]: https://github.com/microsoft/TypeScript/blob/v4.5.4/src/lib/es2015.core.d.ts
[mdn-isFinite]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/isFinite
[mdn-Number.isFinite]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isFinite
[ecma-isFinite]: https://tc39.es/ecma262/multipage/global-object.html#sec-isfinite-number
[ecma-Number.isFinite]: https://tc39.es/ecma262/multipage/numbers-and-dates.html#sec-number.isfinite

**Comment by RyanCavanaugh** [comment]
This has come up in a bunch of other issues and the current behavior is definitely preferable to this proposal. The proposal to swap them (`Number.isFinite` and `isFinite`) is actually backwards from what you want. See #4002

**Comment by RyanCavanaugh** [comment]
Just to spell it out: If you have an honest-to-goodness `number` and you pass it to `isFinite`, you'll get back sensible results (`isFinite(32)` is `true`, `isFinite(Infinity)` is `false`). If you have some arbitrary other value, the results from `isFinite` aren't sensible:

`isFinite` returns `true` for values like:
 * `"Infinity"` but not `"infinity"`
 * `""`
 * `[]`
 * `[""]`
 * `true` and `false`
 * `new Date()`
 * `null` but not `undefined`

The only thing these values have in common is that they'll coerce to a finite number under `+`, but *you don't want to do that*, because the output of that operation doesn't make any sense. Call `parseInt` / `parseFloat` depending on what you want to do; those operations are sensible and will give you a result you can pass to `isFinite`.

The opposite is true of `Number.isFinite`; it *doesn't* coerce its argument and sensibly returns `false` for all those inputs. Thus it's safe to use it for anything, since it only returns true for things that actually are numbers.

**Comment by Fabioni** [comment]
why is this issue closed. `Number.isFinite()` is still not typed correctly

**Comment by RyanCavanaugh** [comment]
> why is this issue closed? Number.isFinite() is still not typed correctly

In what sense? Can you be more specific?

**Comment by RyanCavanaugh** [comment]
Added https://github.com/microsoft/TypeScript/wiki/FAQ#numberisfinite-and-numberisnan-are-typed-correctly

**Comment by Fabioni** [comment]
@RyanCavanaugh 
```
const x: number | undefined = undefined;
const foo: number | undefined = Number.isFinite(x) ? x * 2 : undefined
```

results in warning: `'x' is possibly 'undefined'.`, but actually `Number.isFinite(undefined)` returns false so we would not reach x * 2.
