### ISSUE TITLE
Typescript = Javascript + Commented Types. noImplicitAny doesn't work with jsdoc types

### ISSUE THREAD

**Issue by nojvek** [Microsoft/TypeScript#10033]
**TypeScript Version:**  1.8.0 / nightly (2.0.0-dev.201xxxxx)

**Code**

``` ts
/**
 * @param {string} cmd - command to execute
 */
function exec(cmd) {
  execSync(cmd)
}
```

**Expected behavior:**

Type of cmd should be string

**Actual behavior:** 

Type of cmd is any and compiler gives error.

```
/** @type string */
const hello
```

Still gives no implicitError.

Weird thing is if my file is .js then tsc doesn't do any type checking or give me useful errors.

The user scenario is:
-  I want to use tsc to typecheck and VSCode to provide excellent code complete/refactoring
- I don't want to transpile since I'm already using ES6. I just want the IDE experience
- I want my typescript type specific information defined as jsdoc or flow like comments.
- **Typescript is Javascript + Types. It should also work for Javascript + Commented Types.**

**Comment by mhegazy** [comment]
There is one way to write types in a .ts file, and that is type annotations. JSDoc comments are not relevant here. in a .js file it can be used, and it is. but `--noImplicitAny` is not relevant there really.

**Comment by nojvek** [comment]
So this means typescript cannot be used a pure type validator for js files.

Whey do I need to write a separate .ts file when type information can be
inferred from flow like comments.

A big usecase is just adding types to javascript function parameters.

**Comment by mhegazy** [comment]
> So this means typescript cannot be used a pure type validator for js files.

it can, and it does. the file extension needs to be `.js`.


> A big usecase is just adding types to javascript function parameters.

this works in VS Code / VS 2017 today. just open a `.js` file add jsdoc comments and you should be able to use them. you can use them in your typescript compilation using `--allowjs`.

All the type errors are suppressed in a .js file, but this is tracked by https://github.com/Microsoft/TypeScript/issues/6802

**Comment by jcrben** [comment]
for posterity, it seems `--noImplicitAny` isn't really recommended in js per https://github.com/Microsoft/TypeScript/issues/14617 ...
