### ISSUE TITLE
enzyme @types use old version

### ISSUE THREAD

**Issue by mvestergaard** [Microsoft/TypeScript#10044]
`@types/enzyme` seem to be using v1.2.0 typings from DT https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/enzyme/enzyme-1.2.0.d.ts

Instead of the newer v2.4.1 typings https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/enzyme/enzyme.d.ts

**Comment by mvestergaard** [comment]
Furthermore it appears `@types/react` defines `HTMLAttributes<T>` while enzyme on DT does not expect it to be generic.

**Comment by RyanCavanaugh** [comment]
We're working on the merge from master to 2.0 and will be publishing a new version of everything in the next few days.

**Comment by mvestergaard** [comment]
Alright, great, I did see the other threads, but was unsure it applied to the same thing.
