### ISSUE TITLE
update for gulp-typescript handbook example

### ISSUE THREAD

**Issue by Mimieam** [Microsoft/TypeScript#10047]
**TypeScript Version:**  1.8.0

**Code**
I believe the  `tsconfig.json` file in TS + Gulp [ handbook example](https://www.typescriptlang.org/docs/handbook/gulp.html)  need to be updated with 

```ts
     "exclude": [
        "node_modules"
    ]

```

**Expected behavior:**
no errors
**Actual behavior:** 
The last example with browserify returns this:
```
TypeScript error: node_modules/bs-recipes/recipes/webpack.typescript.react/src/components/HelloWorld.tsx(12,13): 
Error TS17004: Cannot use JSX unless the '--jsx' flag is provided.
```

**Comment by DanielRosenwasser** [comment]
This issue was moved to Microsoft/TypeScript-Handbook#355
