### ISSUE TITLE
Property is not assignable to index type

### ISSUE THREAD

**Issue by olegdunkan** [Microsoft/TypeScript#10042]
**TypeScript Version:**  Playground

**Code**

```ts
interface Box {
  width:number;  
  [key: string]:string;
}

function check(x:Box) {
  
}

check({width:10, label:"a"});
```

**Expected behavior:**
I expected that all properties except 'width' would have 'string' type.  
**Actual behavior:** 
Error, because [key: string]:string states that all properties including 'width' must have 'string' type.
I thought that we can divide all properties by two domains - listed and others, for listed we state type directly and for others we also state type directly, not only 'any' type.  

If we don't divide properties for two domains, then it is not clear how typescript joins conditions in this form of describing interface with && or ||.

Let say:
[key:string]:string- is the condition that all properties must adhere.
width:number - is a condition the 'width' must adhere.

If we suppose '&&' then 'width:number' and  '[key: string]:string'  equal to false - error is expected.
But if we suppose '||' then 'width:number' or '[key: string]:string' equal to true - error is not expected.

**Comment by sk1981** [comment]
If I am not mistaken, as per [documentation](https://www.typescriptlang.org/docs/handbook/interfaces.html) this appears to be expected and width being string should match the index signature.

> While string index signatures are a powerful way to describe the “dictionary” pattern, ***they also enforce that all properties match their return type***. This is because a string index declares that obj.property is also available as obj["property"]. In the following example, name’s type does not match the string index’s type, and the type-checker gives an error:

```typescript
interface NumberDictionary {
    [index: string]: number;
    length: number;    // ok, length is a number
    name: string;      // error, the type of 'name' is not a subtype of the indexer
}
```

**Comment by olegdunkan** [comment]
@sk1981 thanks, yes I understand why this is an error, I wrote this issue aka question-feature request.
