### ISSUE TITLE
finding reference doesn't go past destructured bindings

### ISSUE THREAD

**Issue by zpdDG4gta8XKpMCd** [microsoft/TypeScript#10055]
nightly build (Jul 31, 2016)

``` typescript
let x = { fn: () => undefined }
let { fn /* <-- find me */ } = x;
```

![image](https://cloud.githubusercontent.com/assets/937933/17277677/d0c42220-5716-11e6-94f8-66e59a1c10c2.png)

expected: `fn` to be found in object literal where it belongs
actual: found only in destructured binding

**Comment by RyanCavanaugh** [comment]
Works as expected now
