### ISSUE TITLE
Hot swapping for dev mode is broken on TS2.0

### ISSUE THREAD

**Issue by SaschaNaz** [Microsoft/TypeScript#10052]
**TypeScript Version:**  2.0 beta

[Hot swapping](https://github.com/Microsoft/TypeScript/wiki/Dev-Mode-in-Visual-Studio#hot-swapping) causes error and force-restart on VS2015 Update 3 with TS 2.0 beta. Not much else to say...

**Comment by SaschaNaz** [comment]
Anyone? Debugging TS on Visual Studio is hard because of this problem.

**Comment by mhegazy** [comment]
Sorry for the delay. I had a fix for this in the RC. Can you give it a try?
