### ISSUE TITLE
Crash for `Symbol` related declaration: JsErrorScriptException

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/TypeScript#10053]
**Version:** TS 2.0 Beta / VS 2015 Update 3

* Create a new HTML Application with TypeScript in VS
* Add the following code

 ```ts
declare const Symbol: SymbolConstructor;

interface IterableIterator<T> {

   [Symbol.iterator](): IterableIterator<T>;
}

interface SymbolConstructor {

    iterator: symbol;
}
```
* Compiling the project results in the following:

```
1>------ Rebuild All started: Project: TypeScriptHTMLApp3, Configuration: Debug Any CPU ------
1>Unknown output : Script failed with error : 'JsErrorScriptException (0x30001)'.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
```

The offending bit of code is the reference to `Symbol.iterator`.

The workaround is to comment out (in lib.d.ts) all references in index signatures that contain `Symbol.`

Repro project attached.

[TypeScriptHTMLApp3.zip](https://github.com/Microsoft/TypeScript/files/391057/TypeScriptHTMLApp3.zip)

Related issue: #9720

**Comment by NoelAbrahams** [comment]
Hello?

**Comment by mhegazy** [comment]
@yuit can you take a look.

**Comment by yuit** [comment]
@mhegazy  will do

**Comment by yuit** [comment]
Hi @NoelAbrahams  sorry for delay. I have tried out your sample and with the sample code you given. They both don't produce any error. Just to make sure we are on the same page. Here is the following steps I took:
- Add sample code into app.ts 
- click build solution

I am using the newest VS Typescript 2.0.2 Beta [here]( https://visualstudiogallery.msdn.microsoft.com/3ced0111-246b-498a-bb5d-44a51e6f6abe) Please give this one a try and let us know if you still run into the issue. I will close it for now but feel free to reopen if the issue persist.

**Comment by NoelAbrahams** [comment]
@yuit, I'm no longer able to reproduces this as of version 2.0 RC. thanks.

**Comment by mhegazy** [comment]
thanks @NoelAbrahams for confirming.
