### ISSUE TITLE
Update History interface

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#10059]
https://html.spec.whatwg.org/multipage/browsers.html#the-history-interface

```diff
+type ScrollRestoration = "auto" | "manual";

 interface History {
     readonly length: number;
     readonly state: any;
-    back(distance?: any): void;
-    forward(distance?: any): void;
-    go(delta?: any): void;
-    pushState(statedata: any, title?: string, url?: string): void;
-    replaceState(statedata: any, title?: string, url?: string): void;
+    scrollRestoration: ScrollRestoration;
+    back(): void;
+    forward(): void;
+    go(delta?: number): void;
+    pushState(data: any, title: string, url?: string | null): void;
+    replaceState(data: any, title: string, url?: string | null): void;
 }

-declare var History: {
-    prototype: History;
-    new(): History;
-}
```

**Comment by basarat** [comment]
Just some notes based on what I googled. Personal opinions that people (who can actually action this) might find helpful.

* your interpretation of the History interface is spot on.
* The only reference I could find of `history.back` taking any value is : https://msdn.microsoft.com/en-us/library/ms536346(v=vs.85).aspx 
* if you do `console.log(History)` in chrome dev tools you do get something so I wouldn't want to delete that variable declaration :rose:

**Comment by falsandtru** [comment]
> if you do console.log(History) in chrome dev tools you do get something so I wouldn't want to delete that variable declaration 

I see, but I could not find a definition of `History` variable in spec.
