### ISSUE TITLE
Mystique Screen interface

### ISSUE THREAD

**Issue by olegdunkan** [Microsoft/TypeScript#10056]
Go to playground and type

```ts
interface Screen<T> {}
```
you will see error: all declarations of an interface must have identical type parameters.

I have tried it in Chrome and Mozila, OS -windows 8

It seems to me that some code inside playground in global scope.

**Comment by olegdunkan** [comment]
I found out that Screen is the global object in browser environment, then I saw the same issue about 'name' variable. For novice it is not obvious that code in playground is executed in global scope.  The questions like this will appear more and more. Maybe it will better to limit scope or make some attention to this for users.  

In my case typescript generates nothing, there is no any variable named Screen. How can I suppose that nothing interferes with global Screen object?

**Comment by RyanCavanaugh** [comment]
If you use modules, you'll get a "fresh" scope inside the global scope where you can shadow existing names as you like.

In real life, conflict with global variables when code executes at the global scope is actually a very large concern and it's desirable to be warned of this. It'd be very bad, for example, to assign to `Screen` or some other mutable variable and break some downstream code.

**Comment by olegdunkan** [comment]
Yes, in real life it is. But we are in a pure playground as I thought. 
Thank you)
