### ISSUE TITLE
default values of `types` and `typeRoots` properies cause the project to stop compiling

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#10067]
nightly build August 1, 2016

problem: 
- a project that compiles from the one folder (with one node_modules in its context) doesn't compile from a another folder (with it's own node_modules in its context)

in case of another folder some unwanted typings are included and the code breaks due to being incompatible with them

all things equal, the result of compilation depends on from where the compiler was run (due to default values of `types` or `typeRoots` properties of `compilerOptions` in `tsconfig.json`)

workaround:
- once thsese properties are *explicitly* set to `[]` the project compiles from both folders

solution: 
- either make the location from where the compiler is run irrelevant to the result of compilation
- or document `types` and `typeRoots` so it's clear from where the typings come and how to avoid unwanted behaviour

**Comment by RyanCavanaugh** [comment]
The location the compiler's invoked from shouldn't matter *if* there's a tsconfig.json. Can you write out the explicit file layout and where you're invoking tsc from so we can put together a repro?

**Comment by aleksey-bykov** [comment]
cannot reproduce, the problem is only be seen when i use compiler API, so i guess i am just doing it wrong, so the issue is irrelevant

```
    function loadConfig(filePath: string): bt.Tried<FilesAndOptions, ts.Diagnostic[]> {
        return bt.offTried(
            readConfig(filePath),
            luck => parseConfig(
                luck,
                path.dirname(path.resolve(filePath)) // AB: TODO: find out exactly what should go here
            ),
            fail => bt.failFrom([fail])
        );
    }

    function readConfig(filePath: string): bt.Tried<any, ts.Diagnostic> {
        const result = ts.readConfigFile(filePath, readFile);
        if (result.error === undefined) {
            return bt.luckFrom(result.config);
        } else {
            return bt.failFrom(result.error);
        }
    }

    function parseConfig(json: any, basePath: string): bt.Tried<FilesAndOptions, ts.Diagnostic[]> {
        const result = ts.parseJsonConfigFileContent(json, host,
            basePath
        );
        if (result.errors.length > 0) {
            return bt.failFrom(result.errors);
        } else {
            return bt.luckFrom(
                bu.of2(result.fileNames, result.options)
            );
        }
    }

    function openProgram(
        projectFile: string
    ): bt.Tried<ts.Program, ts.Diagnostic[]> {
        const config = loadConfig(projectFile);
        if (bt.isLuck(config)) {
            const [fileNames, compilerOptions] = config.luck;
            dump(Severity.Debug, 'Options:', compilerOptions, dumpAsJson);
            dump(Severity.Debug, 'Files:', fileNames, bb.pass);
            const program = ts.createProgram(fileNames, compilerOptions);
            const diagnostics = diagnoseProgram(program);
            if (diagnostics.length > 0) {
                return bt.failFrom(diagnostics);
            } else {
                return bt.luckFrom(program);
            }
        } else {
            return bt.failFrom(config.fail);
        }
    }
```

**Comment by RyanCavanaugh** [comment]
One thing this code might not be doing properly is setting `CompilerOptions#configFileName` in cases where it parsed the `tsconfig.json`. This responsibility is awkwardly placed on the caller of `readConfigFile` for some reason (perhaps we just forgot).
