### ISSUE TITLE
Array.isArray no longer narrows type `string[] | string`

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#10060]
The following used to work in nightlies e.g. `1.9.0-dev.20160424` : 

```ts
function sendUpdates(emailAddr: string[] | string) {
  if (Array.isArray(emailAddr)){
    emailAddr.forEach; // no error
  }
}
```

But no longer works in latest nighlites e.g. `2.1.0-dev.20160724`.

**Comment by ahejlsberg** [comment]
What error are you seeing? I can't seem to reproduce.

**Comment by yortus** [comment]
I can't reproduce either, using `2.1.0-dev.20160731`.

**Comment by basarat** [comment]
Sorry, was my fault (did a different refactor when testing 1.9.0-dev vs. 2.1.0-dev) :rose:
