### ISSUE TITLE
Control flow based analysis type guard failed on negative narrowing test

### ISSUE THREAD

**Issue by vilic** [Microsoft/TypeScript#10061]
**TypeScript Version:**  nightly (2.1.0-dev.20160731)

Related to (duplicte of) #9861 

**Code**

```ts
function foo(value: string | number) {
    if (typeof value !== 'string') {
        return;
    } else {
        // value here has type string.
    }

    // value here has type string | number.
}
```

**Expected behavior:**

Both `value` in `else` and the rest of the function should be narrowed to `string`.

**Actual behavior:** 

Only `value` in `else` is narrowed.

**Comment by yortus** [comment]
I can't reproduce this in `2.1.0-dev.20160731`. This is what I see:

```ts
function foo(value: string | number) {
    if (typeof value !== 'string') {
        value // value is number
        return;
    } else {
        value // value is string
    }

    value // value is string
}
```

**Comment by vilic** [comment]
Strange then, can't reproduce it myself. Might be some misconfiguration.
