### ISSUE TITLE
Error TS2339: Property does not exist on type. Although it exists...

### ISSUE THREAD

**Issue by Gp2mv3** [Microsoft/TypeScript#10066]
**TypeScript Version:**  1.8.10

**Code**

```ts
//First class (that use AuthService)

import {AuthService} from './services/auth-service.ts';

export class MyApp {

  constructor(
    private authService: AuthService
  ) {
    }

    isAuthenticated() {
      //The error is here
      return this.authService.authenticated();

    }
  }

//AuthService
import {tokenNotExpired} from 'angular2-jwt';

export class AuthService {
  constructor() {

  }

  public static authenticated() {
    return tokenNotExpired();
  }
}

```

**Expected behavior:**
Normally, no compilation error.

**Actual behavior:** 
Line `return this.authService.authenticated();` produces the following error:
> TypeScript error: app/app.ts(68,31): Error TS2339: Property 'authenticated' does not exist on type 'AuthService'.

**Comment by yortus** [comment]
The error looks correct to me based on the code sample.

`authenticated` is declared as a `static` method in the `AuthService` class. So an `AuthService` *instance* does not have an `authenticated` method.

By the above declarations, you would access `authenticated` as a direct property of the class, as in `AuthService.authenticated()`.

**Comment by Gp2mv3** [comment]
Oups, you're totally right...
I just figured another bug (but not in typescript, it's in atom-typescript) that still displayed the error even without the static. Even when commented the line produced an error, thus it's related to atom and not the compiler.
