### ISSUE TITLE
Go to definition: go to correct overload

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#10074]
**TypeScript Version:**  nightly

**Code**

```ts
interface I {
    f(x: number): number;
    g(): void;
    h(): void;
    i(): void;
    f(x: string): string;
}

const i: I = undefined;
const x: number = i.f(1);
```

**Expected behavior:**

Go-to-definition on `i.f(1)` goes to `f(x: number)`.

**Actual behavior:** 

Compiles correctly (using the `f(x: number)` overload), but go-to-definition goes to `f(x: string)`.

**Comment by aluanhaddad** [comment]
Yes please. This would be incredibly valuable and has been a pain point for a long time. +1000

**Comment by NoelAbrahams** [comment]
This should work for string literal overloads as well:

```ts
interface Foo {

    method(value: 'aa'): void;
    method(value: 'bb'): void;
    method(value: 'zz'): void;
    method(value: 'last'): void;
}

const x: Foo = {} as any;

// F12 on `method` should go to the correct overload 
// but all go to 'last'
x.method('aa');
x.method('bb');
x.method('zz'); 

```

We currently have a few methods with 50+ overloads and it's a bit of a time waster looking for the correct one.

**Comment by DaSchTour** [comment]
Is this really an TypeScript issue? IntelliJ with TypeScript 1.8 works as expected.

**Comment by rickmed** [comment]
Is a typescript issue

I tested with vscode/atom and just the tsc cli and it worked the same way.

**Comment by aluanhaddad** [comment]
@DaSchTour JetBrains uses their own, inhouse TypeScript compiler.
