### ISSUE TITLE
Parameters destructuring + Interface + Optional Values

### ISSUE THREAD

**Issue by vekexasia** [Microsoft/TypeScript#10086]
**TypeScript Version:**  1.8.10

**Code**

```ts
interface T {
	a: number,
	b: string
}
function asd({a,b = 'a'}:T) {
	console.log(a,b);
}

asd({a:1})
```

**Expected behavior:**

It should allow `asd({a:1})` 

**Actual behavior:** 
complains about `b` missing from parameter

**Comment by DanielRosenwasser** [comment]
Looks like this is fixed in 2.0 beta.
