### ISSUE TITLE
Error compiling nested namespaces partially sharing same name

### ISSUE THREAD

**Issue by shytikov** [Microsoft/TypeScript#10085]
**TypeScript Version:**  1.8.10 

I've asked this question on [SO](http://stackoverflow.com/q/38708175/1047741), but nobody replied, so I assume I've finally found a bug in `typescript`. Or maybe it's just unexpected situation, that was not covered by design document.

This is about nested namespaces that have same name. For example, standard Microsoft definitions for MS CRM are in the `Xrm` namespace. My company's definitions, when we was using JS used to be in `Company.Xrm` namespace. Which makes perfect sense, at least from general OOP point of view. Object `Xrm` not equal to `Company.Xrm` object. They both should resolve to their correct definitions. They resolve correctly even in case of `javascript`. But not when it comes to `typescript`, unfortunately.

Typescript thinks that `Xrm` and `Company.Xrm` refers to same object and fails to compile file. Here is 

**Code**

```ts
/// <reference path="typings/globals/xrm/index.d.ts" />
/// <reference path="typings/SDK.d.ts" />

namespace Company.Product {
    export class Module {
        static Method() {
            var id =  Xrm.Page.context.getUserId();
            var obj = Company.Xrm.Endpoint.Retrieve("test", "test", "test");
        }
    }
}

// xrm.d.ts located here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/xrm/xrm.d.ts 
// SDK.d.ts:
declare namespace Company.Xrm.REST {
    function Retrieve(entityName: string, id: string, queryString: string): any;
}
```

**Expected behavior:**
Successful compilation. No merging or hiding should happen, both namespaces should refer to two different and separate objects.

**Actual behavior:** 
Compilation error: Property 'Page' does not exist on type 'Xrm', while 'Page' is defined in `xrm.d.ts`, but was hidden by definition of `SDK.d.ts`.

**Comment by RyanCavanaugh** [comment]
Can you please reduce this to a minimal repro? We don't really have resources to dig into several different third-party declaration files

**Comment by mhegazy** [comment]
Without enough information this is unactionable. please provide a sample we can use to diagnose the issue, and why you believe this is a compiler bug.
