### ISSUE TITLE
Feature request: Autocomplete for string literal types

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#10089]
_From @calebegg on July 14, 2016 17:56_

- VSCode Version: 1.3.1
- OS Version: Ubuntu 14.04.1

It would be useful if string literal types in TypeScript had autocomplete

For example:

![image](https://cloud.githubusercontent.com/assets/782920/16849908/a54c0af8-49ca-11e6-9979-b7423336b3d1.png)

_Copied from original issue: Microsoft/vscode#9294_

**Comment by DickvdBrink** [comment]
Hmz, isn't this issue #606 and fixed by #8428?

**Comment by DanielRosenwasser** [comment]
Thanks for finding @DickvdBrink
