### ISSUE TITLE
Incorrect types while iterating over a list of enums (1.8.10)

### ISSUE THREAD

**Issue by Vermeille** [Microsoft/TypeScript#10080]
On TypeScript 1.8.10, the following happens, and breaks my existing code:

```ts
enum MyEnum { A, B };

var EnumList: MyEnum[] = [MyEnum.A, MyEnum.B];

for (var c in EnumList) {
//	var e: MyEnum = c; For some reason, c is a string
//	var e: MyEnum = MyEnum[c]; And this cast still doesn't compile
	var e: MyEnum = MyEnum[MyEnum[c]]; // This compiles
}
```

I think c never meant to be a string, to begin with. But let's admit it's okay, the second line should work to cast it back to the integer-based enum value, and it does not.

The weird double cast works though. At compile time... and at runtime.

**Comment by weswigham** [comment]
`for (var c in EnumList)` is iterating over the keys in `EnumList`. You want to write `for (var c of EnumList)` to iterate over the members. This is a JS thing, not TS - we're just getting the types right.

**Comment by Vermeille** [comment]
Wow, the in/of thing is really really subtle.

Why was it working in version 1.7.5 then?

**Comment by weswigham** [comment]
@Vermeille [Prior to 1.8, we typed it as `any`, rather than `string` (despite is always being a string).](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#improved-checking-for-forin-statements)
