### ISSUE TITLE
Incorrect typing when flip-flopping an array of tuples

### ISSUE THREAD

**Issue by dsifford** [Microsoft/TypeScript#10094]
**TypeScript Version:** nightly (2.0.0-dev.201xxxxx)

**[Playground](https://www.typescriptlang.org/play/#src=const%20x%3A%20%5Bstring%2Cnumber%5D%5B%5D%20%3D%20%5B%0D%0A%09%5B'one'%2C%201%5D%2C%0D%0A%09%5B'two'%2C%202%5D%2C%0D%0A%09%5B'three'%2C%203%5D%0D%0A%5D%3B%0D%0A%0D%0A%2F%2F%20Type%20of%20y%20should%20be%20%5Bnumber%2Cstring%5D%5B%5D%0D%0A%2F%2F%20Instead%2C%20it%20is%20(number%7Cstring)%5B%5D%5B%5D%0D%0Aconst%20y%20%3D%20x.map((%5Ba%2Cb%5D)%20%3D%3E%20%5Bb%2Ca%5D)%3B)**

**Code**

```ts
const x: [string,number][] = [
	['one', 1],
	['two', 2],
	['three', 3]
];

// Type of y should be [number,string][]
// Instead, it is (number|string)[][]
const y = x.map(([a,b]) => [b,a]);

```

**Expected behavior:**

This may be an expected feature of the language, and if so, please disregard.

I expected the type of `y` to be `[number,string][]`

**Actual behavior:** 

Type of `y` is `(number|string)[][]`

**Comment by weswigham** [comment]
As a workaround, you can cast your result:
```ts
const y = x.map(([a,b]) => ([b,a] as [number, string]));
```

Or, a personal favorite, write your own 'tuple constructor', which forces a tuple type to be inferred:
```ts
function tuple<A, B>(a: A, b: B): [A, B] {
	return [a, b];
}

const y = x.map(([a,b]) => tuple(b, a));
```

In any case, I think this is a duplicate of #6574, and discussion should probably continue there.

**Comment by dsifford** [comment]
Whoops! Didn't see the other discussion. Sorry about that.

And yep, I've been using casting. Totally not a giant issue for me, but just wanted to throw it out there.

Love the tuple constructor! Clever!

Thanks again 👍
