### ISSUE TITLE
`--forceConsistentCasingInFilenames` complains when `cwd` has incorrect casing

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#10095]
To reproduce:

    mkdir CapItalIzation
    cd capitalization
    echo 'import x from "./b";' > a.ts
    echo 'export default 0;' > b.ts
    npm install typescript@next
    node node_modules/typescript/lib/tsc a.ts b.ts --forceConsistentCasingInFilenames --noEmit

The error is:

    error TS1149: File name 'b.ts' differs from already included file name 'C:/CapItalIzation/b.ts' only in casing

**Comment by andy-ms** [comment]
This is essentially the same problem as #9934, and it is also fixed as of node 6.4.0.

**Comment by z1988hf** [comment]
The same issue occurred in node 6.9.4
