### ISSUE TITLE
(Feature request) Support for Multi-line template strings (backticks)

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#10090]
_From @aamir1995 on July 14, 2016 12:24_

- VSCode Version: 1.3.1
- OS Version: Windows 10 Pro

## Current Behaviour:
When writing code in Typescript with Angular 2 framework, The IDE didn't recognize HTML tags in inline template with Multi-line strings (backticks), auto code formatting ignores HTML tags inside `backticks`, this situation makes code management much worse.

## Desired Behaviour:
Detection of HTML tags inside `backticks` while performing auto code formatting.

_Copied from original issue: Microsoft/vscode#9276_

**Comment by kitsonk** [comment]
Covered by #6508 right?

**Comment by weswigham** [comment]
The ability to override, filter, or otherwise extend the language service's formatter is [one of the features available in the current iteration of the API](https://github.com/Microsoft/TypeScript/pull/9038/files#diff-233e1126c0abc811c4098757f9e4516eR1288).
