### ISSUE TITLE
Support error message verification in Fourslash 

### ISSUE THREAD

**Issue by yuit** [microsoft/TypeScript#1009]
Currently, we can only verify number of errors and position of errors through marker. However, in some scenarios, ability to verify correctness of diagnostic messages and their arguments can be useful.

**Comment by DanielRosenwasser** [comment]
What do we want to specifically track here? What extra information would this give us?

**Comment by Andarist** [comment]
@RyanCavanaugh this can probably be closed since `verify.errorExistsAtRange` accepts `code` and `message`

**Comment by DanielRosenwasser** [comment]
I think we also have baselining for diagnostics.
