### ISSUE TITLE
How get only public properties?

### ISSUE THREAD

**Issue by maranqz** [Microsoft/TypeScript#10093]
How get only `public` properties, without `private`?
```
class A {
 private _a:string = "111";
 public b: string = "222"
}
console.log(new A());
/*
_a: "111",b: "222"
*/
```
Thank you in advance.

**Comment by 21ohs** [comment]
Public and private properties look the same in compiled Javascript, so there is no way to distinguish them.

**Comment by kitsonk** [comment]
The only way is to enumerate over the properties and use some sort of convention to sort them out, since private properties are added by default assignment, which creates them as enumerable own properties.

See #9769 for a discussion on a possible solution to this.
