### ISSUE TITLE
Invalid JavaScript emitted when exporting merged function + namespace

### ISSUE THREAD

**Issue by paul-go** [Microsoft/TypeScript#10104]
**TypeScript Version:**  2.0.0

**Code**
```ts
export function abc() { }

export namespace abc
{
	var abc;
}
```

When using module:es6, the emitted JavaScript will look like:

```js
export function abc() { }
export var abc;
// namespace stuff here
```

This is causing a problem with RollupJS (See the [related issue](https://github.com/rollup/rollup/issues/820)) because it's causing it to tree-shake the function, and leaves only the namespace. I'm also fairly certain this is invalid ES6, although I can't find any documentation other than that it appears that it's being [marked as an error](https://bugs.chromium.org/p/v8/issues/detail?id=1569#c12) in V8's coming implementation of ES6 modules.

**Comment by DanielRosenwasser** [comment]
Is this in 2.0 beta or in the nightlies?

**Comment by paul-go** [comment]
2.0 beta

**Comment by DanielRosenwasser** [comment]
As a temporary workaround, you can use an export statement to do the right thing.

```ts
function abc() { }
namespace abc { ; }
export { abc }
```

**Comment by paul-go** [comment]
Something is wrong because now the workaround doesn't seem to be working anymore. I switched to the latest nightlies and still have the same result.

tsconfig.json:
```
{
	"compilerOptions": {
		"target": "es6",
		"module": "es6"
	}
}
```
abc.ts:
```
function abc() { }
namespace abc { ; }
export { abc }
```
abc.js (output, with undesirable var statement):
```
function abc() { }
var abc;
(function (abc) {
    ;
})(abc || (abc = {}));
export { abc };
```

**Comment by DanielRosenwasser** [comment]
The `var` statement might be undesirable but there's nothing semantically wrong with it. If Rollup is having issues with that, it might be worth filing a bug on their repo.

**Comment by mhegazy** [comment]
latest nightly (`@2.1.0-dev.20160920`) produces:

```ts
function abc() { }
export var abc;
(function (abc_1) {
    var abc;
})(abc || (abc = {}));
```

this looks right to me. @paul-go can you give it another try.

**Comment by lleevvyy** [comment]
I think that this issue also applies to exported classes + namespace, following fails on Rollup as well:

export class ABC {
}

export namespace ABC {
   export const DEF = 1;
}

Compiler produces duplicated exports "export var ABC", which as in case of a function fails. I've checked on latest nightly and it still duplicate exports.

**Comment by mhegazy** [comment]
thanks @lleevvyy, filed https://github.com/Microsoft/TypeScript/issues/11258 to track it.
