### ISSUE TITLE
strictNullCheck does not remove `| undefined` from parameter with default value

### ISSUE THREAD

**Issue by Kovensky** [Microsoft/TypeScript#10107]
Current `typescript@2` with `--strictNullCheck`:

```ts
import React from 'react'

interface Props {
    size: number
    icon: string
}

const MyComponent: React.SFC<Props> = ({size, icon} = {size: 0, icon: ''}) => (
  <i className={`icon size-${size} icon-${icon}`}/>
)
```

This should typecheck, even though `React.SFC` currently, perhaps incorrectly, declares all arguments as optional (https://github.com/DefinitelyTyped/DefinitelyTyped/issues/10388). Currently, it fails to destructure `{size, icon}` because the argument may be `undefined`.

The first argument, as it is optional, has type `Props | undefined`. However, because it has a default expression, if it is ever called without the argument, or with the argument as `undefined`, it will receive its value from the default expression instead. The parameter is, thus, impossible to be `undefined` inside the function body or its parameter list, so the `| undefined` can be eliminated as a possible type.

**Comment by DanielRosenwasser** [comment]
Like you mentioned, `React.StatelessComponent` shouldn't be declared as

```ts
interface StatelessComponent<P> {
        (props?: P, context?: any): ReactElement<any>;
        propTypes?: ValidationMap<P>;
        contextTypes?: ValidationMap<any>;
        defaultProps?: P;
        displayName?: string;
    }
```

The call signature should instead be

```ts
(props: P, context: any): ReactElement<any>;
```

But in some sense, the default initializer could be viewed as a narrowing assignment in the event that someone passed `undefined` in.

**Comment by Kovensky** [comment]
Conversely, the type of `arg` inside `function withDefault(arg: object = {}) {}` should be `object`, but the signature of `withDefault` should be `(object | undefined) => void`. (I have not verified if this is not already the case)

**Comment by DanielRosenwasser** [comment]
That is indeed currently the case:

![image](https://cloud.githubusercontent.com/assets/972891/17355925/f9ec3982-5908-11e6-9ef9-06a951fc5ddf.png)

**Comment by mhegazy** [comment]
here is a simpler repro:

```ts
declare var f: (props?: { a: number }) => void;
f = ({a} = { a: 0 }) => void 0;
```

**Comment by mhegazy** [comment]
looks like it is working correctly in latest.
