### ISSUE TITLE
Parameter property initializers not emitted after 'super()' in derived classes

### ISSUE THREAD

**Issue by pjordaan** [microsoft/TypeScript#10109]
**TypeScript Version:**  1.8.0 / nightly (2.0.0-dev.201xxxxx)

tested in playground: https://www.typescriptlang.org/play/#src=class%20ClassA%20%7B%0D%0A%09private%20property%20%3D%20this.getDefaultValue()%3B%0D%0A%09%0D%0A%09constructor()%20%7B%0D%0A%09%7D%0D%0A%09%0D%0A%09public%20getDefaultValue()%20%7B%0D%0A%09%09return%20''%3B%0D%0A%09%7D%0D%0A%09%0D%0A%09public%20getProperty()%20%7B%0D%0A%09%09return%20this.property%3B%0D%0A%09%7D%0D%0A%7D%0D%0A%0D%0Aclass%20ClassB%20extends%20ClassA%20%7B%0D%0A%09constructor(private%20dependency)%20%7B%0D%0A%09%09super()%3B%0D%0A%09%7D%0D%0A%09%0D%0A%09public%20getDefaultValue()%20%7B%0D%0A%09%09return%20this.dependency%3B%0D%0A%09%7D%0D%0A%7D%0D%0Alet%20p%20%3D%20new%20ClassB('test')%3B%0D%0Aalert(p.getProperty())%3B

https://www.typescriptlang.org/play/#src=class%20ClassA%20%7B%0D%0A%09private%20property%20%3D%20this.getDefaultValue()%3B%0D%0A%09%0D%0A%09constructor()%20%7B%0D%0A%09%7D%0D%0A%09%0D%0A%09public%20getDefaultValue()%20%7B%0D%0A%09%09return%20''%3B%0D%0A%09%7D%0D%0A%09%0D%0A%09public%20getProperty()%20%7B%0D%0A%09%09return%20this.property%3B%0D%0A%09%7D%0D%0A%7D%0D%0A%0D%0Aclass%20ClassB%20extends%20ClassA%20%7B%0D%0A%09constructor(private%20dependency)%20%7B%0D%0A%09%09alert('hi')%3B%0D%0A%09%09super()%3B%0D%0A%09%7D%0D%0A%09%0D%0A%09public%20getDefaultValue()%20%7B%0D%0A%09%09return%20this.dependency%3B%0D%0A%09%7D%0D%0A%7D%0D%0Alet%20p%20%3D%20new%20ClassB('test')%3B%0D%0Aalert(p.getProperty())%3B

**Code**

Compare these code examples:

``` ts
class ClassA {
    private property = this.getDefaultValue();

    constructor() {
    }

    public getDefaultValue() {
        return '';
    }

    public getProperty() {
        return this.property;
    }
}

class ClassB extends ClassA {
    constructor(private dependency) {
        super();
    }

    public getDefaultValue() {
        return this.dependency;
    }
}
let p = new ClassB('test');
alert(p.getProperty()); // outputs undefined
```

``` ts
class ClassA {
    private property = this.getDefaultValue();

    constructor() {
    }

    public getDefaultValue() {
        return '';
    }

    public getProperty() {
        return this.property;
    }
}

class ClassB extends ClassA {
    constructor(private dependency) {
        alert('hi');
        super();
    }

    public getDefaultValue() {
        return this.dependency;
    }
}
let p = new ClassB('test');
alert(p.getProperty()); //outputs 'test'
```

Example 1 fails because this.property = this.getDefaultValue(); is executed before this.dependency = dependency in the generated Javascript
By adding an alert in Example 2 the code works as expected as this.dependency = dependency; is called before this.property = this.getDefaultValue();

**Expected behavior:**
Consistent order of variable assignments.

**Actual behavior:** 
Example 1 works as intended.

It was driving me nuts as I was debugging by adding 'debugger;' as a first line in the constructor of ClassB to figure out what happened.

**Comment by DanielRosenwasser** [comment]
The problem is that in ES2015, `super` needs to be called before any sort of access to `this`. That means that if `super` *isn't* the first thing that gets called, then we'd have to potentially have `super()` occur out of the original order.

One solution might be to just move every statement up to and including the `super` call to before the parameter property initializers. I don't know whether this idea was discussed previously.

**Comment by DanielRosenwasser** [comment]
Though that would clearly get messy when it comes to branching (like if `super()` gets called differently in each branch of an `if`/`else`).

For what it's worth, you currently get an error for exactly the issue you're seeing here.
