### ISSUE TITLE
Use lib/lib.*.d.ts as regular program files

### ISSUE THREAD

**Issue by alexeagle** [Microsoft/TypeScript#10105]
We use the same `tsconfig.json` `compilerOptions` for all code in our monorepo.
Each target gets to specify only the `files` list.

We'd like some targets to be able to opt-in for typings like collections. In the past, we did that by including the DefinitelyTyped es6-collections.d.ts in the files.

If I include one of the `///<reference no-default-lib=true/>` files, though, I get an error:

```
alexeagle@alexeagle:~/Projects/repro$ cat tsconfig.json 
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5"
    },
    "files": ["node_modules/typescript/lib/lib.es2015.collection.d.ts"]
}
alexeagle@alexeagle:~/Projects/repro$ $(npm bin)/tsc
error TS2318: Cannot find global type 'Array'.
error TS2318: Cannot find global type 'Boolean'.
error TS2318: Cannot find global type 'Function'.
error TS2318: Cannot find global type 'IArguments'.
error TS2318: Cannot find global type 'Number'.
error TS2318: Cannot find global type 'Object'.
error TS2318: Cannot find global type 'RegExp'.
error TS2318: Cannot find global type 'String'.
```

This is the case even if other files are included in the compilation. I can solve it by removing the `///ref` but this means we have local modifications to Typescript. Is there another way to defeat the error?

**Comment by DanielRosenwasser** [comment]
Those errors only come up because you didn't include `lib.es5.d.ts` , so you didn't have the global core types available.

Does this using this `tsconfig.json` fix the issue?

```json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5"
    },
    "files": [
        "node_modules/typescript/lib/lib.es5.d.ts",
        "node_modules/typescript/lib/lib.es2015.collection.d.ts"
    ]
}
```

**Comment by alexeagle** [comment]
Thanks Daniel, that does work.

I had tried
```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "noImplicitAny": false,
        "sourceMap": false,
        "lib": ["es5"]
    },
    "files": [
        "app.ts",
        //"node_modules/typescript/lib/lib.es5.d.ts",
        "node_modules/typescript/lib/lib.es2015.collection.d.ts"
    ]
}
```

thinking that the `--lib` flag would bring in the standard types (and this is what we have today). I imagine that `no-default-lib` actually means don't use any default libs, and the `--lib` flag just chooses a different set of "default" libs?

But it will probably make our setup easier to just use `--noLib` and pass all files together, rather than a mix of `--lib` and `files`

**Comment by DanielRosenwasser** [comment]
Sounds good, keep us posted on how that works out.

**Comment by alexeagle** [comment]
Submitted it today, works great and solves our problem 👍

**Comment by alexeagle** [comment]
I take that back, we are investigating a 2x performance regression for compiles.
We now include v1_9_0_dev_20160526/lib/lib.es5.d.ts in the `files[]` of tsconfig. Even though we have a cache that prevents re-reading from disk, and we don't ask to type-check that file, I suspect we now hit some parse time when creating a `ts.Program` containing that.
Previously, it was in `--lib` and we `skipDefaultLibCheck` - I am guessing we also skipped parsing?

cc @evmar who is profiling it.

**Comment by mhegazy** [comment]
@alexeagle is this still an issue?

**Comment by alexeagle** [comment]
thanks for following up. We did track down our performance regression. @evmar could confirm, looking at the history we were not certain what introduced it. removing `--noEmitOnError` helped, as that was triggering an extra type-check.
