### ISSUE TITLE
Incorrect docs

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/TypeScript#10116]
https://www.typescriptlang.org/docs/handbook/compiler-options.html

![image](https://cloud.githubusercontent.com/assets/921609/17373590/c43556b4-59a0-11e6-9953-7d2cb619ca72.png)

The default column says the default is ES5, but the description says it's ES3. Which is it? :-)

**Comment by RyanCavanaugh** [comment]
It's ES3, but maybe we should update it to be ES5

**Comment by mhegazy** [comment]
Should be fixed now, https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Compiler%20Options.md.

The website should be updated shortly.
