### ISSUE TITLE
--listFiles flag does not appear in --help screen

### ISSUE THREAD

**Issue by yahiko00** [Microsoft/TypeScript#10113]
**TypeScript Version:**  2.0.0

This is probably a clueless issue, but it would be better if the help screen in the CLI would display the `--listFiles` flag.

`> tsc --help`

**Expected behavior:**
`--listFiles                        Print names of files part of the compilation.`

**Actual behavior:** 
No `--listFiles` flag in the help screen.

**Comment by paulvanbrenk** [comment]
`--listFiles` is an internal diagnostics option and therefor it doesn't show in the `--help` list.
