### ISSUE TITLE
Wrong type inferred for map keys

### ISSUE THREAD

**Issue by Galfour** [Microsoft/TypeScript#10112]
**TypeScript Version:**  1.8.0 / nightly (2.0.0-dev.201xxxxx)

**Code**
```
type Resources = Map<Resource, number>;
type Resource = 'red' | 'green' | 'blue' | 'black' | 'yellow' | 'white';
function times(sr:number, r2:Resources): Resources {
    let ret: Resources = new Map();
    for (let r in r2) {
      ret.set(r, sr * (r2.get(r) || 0));
    }
    return (ret);
  },
```

**Expected behavior:**
The type of "r" should be inferred as "Resource". As in a "Map<Resource, X>", we can only set "Resource" keys.

**Actual behavior:** 
It is inferred as "string", and thus require type indications all over the code ("<Resource>r").

I checked the guidelines, and made a quick search, and found no similar issue. If there is already one, I'm sorry.

**Comment by sandersn** [comment]
Does `for .. in` even work on Maps? I tried it in Node and didn't get any useful results.

```
> let m = new Map([[1,2], [3,4], [5,6]])
> for (let x in m) { console.log(typeof x) }
// the loop body happened 0 times
```

**Comment by sandersn** [comment]
Tried it in Chrome too. Same result. [MDN's page on Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map)  doesn't mention `for .. in` either. What does the spec say?

**Comment by sandersn** [comment]
Looks like Map is designed not to have properties on the prototype, and keys are not properties. So `for .. in` does nothing by design.
