### ISSUE TITLE
Add methods has/get/set property in class object by key(string)

### ISSUE THREAD

**Issue by MaklaCof** [Microsoft/TypeScript#10111]
Currently there is no support for checking if class has property with name, neither setting property value by name or getting property value by name.
This methods would be very useful with constructor and would replace the need for overloading constructors.
I have interface for MyClass class:
```
interface IMy
{
    prop1?: boolean;
    prop2?: string;
    prop3?: string;
    prop4?: number;
}
```
And MyClass implementation:
```
class MyClass implements IMy
{
    prop1: boolean;
    prop2: string;
    prop3: string;
    prop4: number;

    constructor(prop1 = false, prop2 = "", prop3 = "Something", prop4 = 0)
    {
        this.prop1 = prop1;
        this.prop2 = prop2;
        this.prop3 = prop3;
        this.prop4 = prop4;
    }
}
```
And different ways for creating MyObject:
```
new MyClass(true);
new MyClass(false, "SomeText", "Anything");             //I set prop2 and prop3
new MyClass(undefined, undefined, undefined, 10);       //I set prop4
```
**But it would be nice if I could write something like this:**
```
class MyClass2 implements IMy
{
    prop1: boolean;
    prop2: string;
    prop3: string;
    prop4: number;

    constructor(properties: IMy)
    {
        for (let prop in properties)
            if (this.hasProperty(prop)
                this.setProperty(prop, properties[prop]);
    }
}
```
And use:
```
new MyClass2({ prop1: true });                              //I can set prop1
new MyClass2({ prop2: "SomeText", prop3: "Anything" });     //I can set prop2 and prop3
new MyClass2({ prop4: 10 });                                //I can set only prop4
```
class.hasProperty probably could compile to Object.hasOwnProperty, class.set and class.get would not be a problem since you can already do `myClass[stringVariable]`.
 
The alternative (less options available for coding TypeScript code) soultion would be class.assignProperties method where you could assign multiple properties:
```
let my = new MyClass();
my.assignProperties({ prop2: "SomeText", prop3: "Anything" });
```
function assign would look like this in JavaScript:
```
Object.assignProperties = function assignProperties(objClass, objProperties)
    {
        for (let key of Object.keys(objProperties))
        {
            if (typeof objClass[key] !== "undefined")        //check if object has property
                objClass[key] = objProperties[key];             //assign value
        }
    };
```
[Another option would be to allow indexer property on class](https://msdn.microsoft.com/en-us/library/2549tw02.aspx) and again no problem with transpiling since JavaScript already support `myClass[someProperty] = somevalue;`. But I am not sure, if this raise problems with type checking for returning property values.

In addition you could also add hasMethod and callMethod method for class object.

**Comment by RyanCavanaugh** [comment]
We don't intend to add any additional runtime functions or metadata to ES6 classes. Property declarations are always fully erased. You might look into whether or not decorators could help solve your use case.
