### ISSUE TITLE
Inconsistent multiple export behavior for functions vs vars

### ISSUE THREAD

**Issue by evmar** [microsoft/TypeScript#10122]
typescript@2.1.0-dev.20160803 

``` js
export type A = string;
function A() {}
export {A}

type B = string;
var B: void;
export {B};
```

The compiler accepts this module, and if you import it, you'll find that A is only exported as a type, not a value, but that B is both a type and value.

Note that two lines (1 and 3) both attempt to export A.  If you make the B block try to do the same thing (add `export` before the first declaration of B) the compiler rejects the module with: "Individual declarations in merged declaration 'B' must be all exported or all local".

I suspect the right resolution of this is that it should reject the double export of A as well in this module.

**Comment by DanielRosenwasser** [comment]
Yup, and I agree that we should disallow the double export.

**Comment by Andarist** [comment]
@DanielRosenwasser @jakebailey I'm not sure if this should be considered a bug today. I re-examined the `Individual_declarations_in_merged_declaration_0_must_be_all_exported_or_all_local_2395` and I think that this error only targets merged declarations that **share** the type/value space. When the spaces are different then the error is never raised *today* and the type gets exported from the module. I'm not saying this is perfect but that seems to be the intention of the code and what the test suite encodes today - so if anything the rules could be refined but that could also be a breaking change for people relying on the fact that they can only export the type without exporting the value of the same local name (and I've seen this in some repositories)
