### ISSUE TITLE
Support additional directories in module search path

### ISSUE THREAD

**Issue by aeschli** [Microsoft/TypeScript#10127]
_From @kaelig on August 3, 2016 22:59_

I am using the [app-module-path package](https://www.npmjs.com/package/app-module-path) in my app, and there is something I'd love to be able to configure in jsconfig.json so I can navigate between files more easily.

Consider this structure:

``` js
// a/foo.js
require('app-module-path').addPath(process.cwd());

var bar = require('b/bar')

bar()

// b/bar.js
module.exports = function () { console.log('bar') }
```

``` bash
$ node a/foo.js
"bar"
```

Unfortunately hovering `require('b/bar')` or CMD+Click on `b/bar` doesn't open b/bar.js.

Is there a way we could enter these kinds of re-mapped paths in jsconfig.json (or other)?

_Copied from original issue: Microsoft/vscode#10103_

**Comment by weswigham** [comment]
I think the [`rootDirs`](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Module%20Resolution.md#virtual-directories-with-rootdirs) option will actually do what you want.

**Comment by kaelig** [comment]
Thank you @weswigham, unfortunately when putting this in `jsconfig.json` for VS Code, I get a "Property rootDirs is not allowed" warning:

```json
{
    "compilerOptions": {
        "target": "ES6",
        "module": "commonjs",
        "allowSyntheticDefaultImports": true,
        "rootDirs": [
          "."
        ]
    },
    "exclude": [
        "node_modules",
        ".www",
        ".generated",
        ".npm"
    ]
}
```

(I don't use typescript so I don't have a tsconfig.json file, am I supposed to have one?)

Where am I doing something wrong?

**Comment by weswigham** [comment]
@kaelig AFAIK, that error isn't inside the compiler - I can't find that error anywhere in the current codebase. What version of TS are you using? (`rootDirs` is new to 2.0, I believe.)

**Comment by kaelig** [comment]
@weswigham should I be using TypeScript? My project is JavaScript-only, and unless I have missed something in the documentation of VS Code, I only have seen instructions about a jsconfig.json file for such projects. If I need to set up TS in a certain way, can you direct me to the documentation?

**Comment by kitsonk** [comment]
TypeScript services are the engine that powers VSCode's understanding of JavaScript.  I think @weswigham missed that you were referring to `jsconfig.json` instead of `tsconfig.json`.  The thoughts are still valid, it is only TypeScript 2.0 (which is still in beta) which supports this type of functionality.  To use it now, you would have to install `typescript@beta`, configure VSCode to use it and likely ignore the errors it would indicate for the `jsconfig.json` until VSCode update the schema for the file.

**Comment by nekman** [comment]
Using [app-module-path](https://www.npmjs.com/package/app-module-path) in a Node project. 

```javascript
// start.js
require('app-module-path/register');
const b = require('src/b'); // can not hower and CMD+click to b.js

// b.js
const c = require('src/c'); // works! I can hower and CMD+click to c.js
```
I have the following in my `jsconfig.json`:

```json
{
  "compilerOptions": {
    "target": "es6"
   },
   "include": [
      "src/**/*"
   ],
   "exclude": [
     "node_modules"
   ]
}
```

**Comment by kaelig** [comment]
@nekman it doesn't seem to do the trick for me.

Here's my config:

```js
{
    "compilerOptions": {
        "target": "es6"
    },
    "include": [
      "app_modules/**/*"
    ],
    "exclude": [
        "/node_modules/",
        "/.www/",
        "/.generated/",
        "/.npm/",
        "/.dist/",
        "/design-tokens/dist/"
    ]
}
```

You may test it on the project https://github.com/salesforce-ux/design-system

e.g. go to https://github.com/salesforce-ux/design-system/blob/master/site/articles/index.jsx and try to hover `app_modules/site/components/page/body`.

**Comment by mhegazy** [comment]
you need to:
1. include all the files you are using, the file `site/article/index.jsx` is not coveted in yoru `include` pattern, so it is not procesed
2. use `"jsx": "react"` to tell the system you are using `jsx` files
3. set `"baseUrl" : "./"` to indicate that all module imports should be resolved as if the root was `./`
4. set `"moduleResolution": "node"` or use `"module": "commonjs"`

here is a config file with these changes

```ts
{
    "compilerOptions": {
        "target": "es6",
         "baseUrl": ".",
         "moduleResolution":"node",
         "jsx": "react"
    },
    "include": [
      "app_modules/**/*",
      "site/**/*"
    ],
    "exclude": [
        "/node_modules/",
        "/.www/",
        "/.generated/",
        "/.npm/",
        "/.dist/",
        "/design-tokens/dist/"
    ]
}
```

**Comment by kaelig** [comment]
Thank you so much @mhegazy, you're my savior!

I just tried it and it works like a charm.

**Comment by mhegazy** [comment]
glad it helped.
