### ISSUE TITLE
[jsx] Provide HTML tag matching

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#10138]
_From @emzero on July 3, 2016 0:56_

HTML tag matching highlights all the tags of the same type in JSX instead of the corresponding one. 
Considering that code folding works fine, it seems that it's indeed properly recognizing the matching tag.

HTML syntax
![image](https://cloud.githubusercontent.com/assets/412489/16543186/68d865dc-409f-11e6-808c-9731fe2e6c08.png)

JavaScript/TypeScript React syntax
![image](https://cloud.githubusercontent.com/assets/412489/16543192/78abd4b2-409f-11e6-8b7e-1cfb025d3ea1.png)

_Copied from original issue: Microsoft/vscode#8684_

**Comment by dbaeumer** [comment]
_From @aeschli on July 19, 2016 14:50_

This would have to be added in symbol highlight support in the TypeScript language server.

**Comment by dbaeumer** [comment]
Moving to TS team since this is best implemented in the TS server / language server which has knowledge about jsx.

**Comment by basarat** [comment]
Consider: 

```tsx
const Foo = ()=<div>Hello</div>

// .... later

render(){
  return <Foo/>; // Cursor in `F|oo` here
}
```

I'd imagine document highlights to be all `Foo`. That said I too definitely want tag matching and happy to sacrifice the true *other references in file* for this. Just wanted to mention :rose:

**Comment by ankitrg** [comment]
Has this problem been solved?

**Comment by kedmenec** [comment]
+1

**Comment by outsource** [comment]
+1

**Comment by hqvu935** [comment]
+1

**Comment by jaymontana** [comment]
+1

**Comment by yishus** [comment]
+1

**Comment by vincaslt** [comment]
I think it's unavailable in other modes than html... I wrote a small extension, because I needed matching for JSX. Until it's implemented natively, see if you find this helpful: https://marketplace.visualstudio.com/items?itemName=vincaslt.highlight-matching-tag

**Comment by ogarich89** [comment]
+1

**Comment by apolytos** [comment]
This is the only the thing I miss from Atom and it's irritating.

**Comment by MartinHaeusler** [comment]
This feature is really important when dealing with more complex JSX structures. +1

**Comment by ankitrg** [comment]
When can we download the new version? :D

**Comment by mhegazy** [comment]
fix should be in `typescript@next` later today, and `typescript@2.4.1` in two weeks.

VSCode ships with a different version of TypeScript. Please see [Using Newer TypeScript Versions](https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions) documentation for more details on updating your VSCode to use a different version of TypeScript.

**Comment by elghali** [comment]
whenever this feature is ready i'll switch to VSCode
