### ISSUE TITLE
Can't pass paths via command-line

### ISSUE THREAD

**Issue by nycdotnet** [Microsoft/TypeScript#10137]
As we're preparing to update grunt-ts to support TypeScript 2.0's features, it has come to our attention that it's not possible to pass `paths` via the command-line.

`tsc --paths`  returns  `error TS6064: Option 'paths' can only be specified in 'tsconfig.json' file.`

This is a problem for us as we only operate via the command-line and support a more dynamic experience via the Grunt options (which can be determined programmatically, etc.).  

User @agubler reported this to us here: Issue: https://github.com/TypeStrong/grunt-ts/issues/339  

Is `--paths` not supported on the command-line just because it's hard to reliably accept JSON from the command-line?  Would you consider a pull request to add this?

**Comment by evmar** [comment]
Any time you put informatoin inside of a build config and not in the tsconfig.json, you break TypeScript's editor support (e.g. the editor also wants to know which files are built).  If your tool really wants to dynamically generate file lists, the most user-supportive thing to do would be to generate a `tsconfig.json` (and check it in to the project repo).

**Comment by nycdotnet** [comment]
Hi,

I appreciate this feedback and I agree with your sentiment with regards to using source-controlled build artifacts.

That said, an important feature of tools like Grunt-ts is allowing developers to customize their build system to use a configuration that is different than their editing environment if they want to, and that's what I'm asking about.

**Comment by agubler** [comment]
@evmar our use case the project `tsconfig.json` file is up to date and valid, but using `grunt-ts` to create variations from this base project file depending on the grunt configuration. The plain dev pipelines uses the `tsconfig` "as is" however for creating a the distribution we use different output and flags, additionally a user could also have pipelines for different targets (es5, es6 etc).

**Comment by mhegazy** [comment]
> Is --paths not supported on the command-line just because it's hard to reliably accept JSON from the command-line? Would you consider a pull request to add this?

sorry for the delayed reply. yes. it is only supported in tsconfig.json. so is `roots`

**Comment by mhegazy** [comment]
> Would you consider a pull request to add this?

Not sure it is worth the hassle. we have to come up with a serialized format for paths, and that can be complicated, and very hard to read. unless you say it is JSON.

**Comment by mhegazy** [comment]
@agubler consider using the new [configuration inheritance](https://github.com/Microsoft/TypeScript/issues/9876) feature added in TS 2.1 instead.
