### ISSUE TITLE
Cannot rebuild declarations with declarationDir

### ISSUE THREAD

**Issue by GiedriusGrabauskas** [Microsoft/TypeScript#10135]
**TypeScript Version:**  2.0.0-beta

**Configuration**
```json
{
    "compilerOptions": {
        "declaration": true,
        "declarationDir": "declarations"
    }
}
```

**Expected behavior:**
In the first run, compiler generate declarations. When start second build `.d.ts` files should be updated.

**Actual behavior:** 
After second run, I get this error:
```cmd
error TS5055: Cannot write file 'declarations/*.d.ts' because it would overwrite input file.
```
And declarations files not updated.

**Comment by lostfields** [comment]
add the following to your tsconfig.json to avoid making declarations of declarations or something :-)
```
"exclude": ["declarations"]
```

**Comment by GiedriusGrabauskas** [comment]
Yep, it's working and that make sense. Thanks :+1:
