### ISSUE TITLE
TypeScript constructor find References

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#10131]
_From @wallverb on July 18, 2016 17:24_
- VSCode Version: 1.4.0-insiders
- OS Version: OSX

Feature request:

Ability to `Find All References [Shift+F12]` when executing on constructor - right now it shows `No results`: 
![image](https://cloud.githubusercontent.com/assets/1723815/16923943/cae2bcd0-4cea-11e6-9aa8-5b13839d763e.png)

I guess it should show all `new MyClass(..)` references

_Copied from original issue: Microsoft/vscode#9445_

**Comment by dbaeumer** [comment]
Agree. Moving to TS team.

**Comment by mhegazy** [comment]
Should be working as intended in latest.
