### ISSUE TITLE
Code Suggestions Long Delay

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#10133]
_From @con-ssc on July 20, 2016 7:50_

- OS Version: Windows 10 x64

I experience that sometimes the completion suggestions have a pretty long delay. I mainly experience that in .js and .ts files. Sometime the .ts definitions are not automatically resolved until I press Ctrl+Space.

![image](https://cloud.githubusercontent.com/assets/8189808/16978985/13ddb69a-4e5f-11e6-82be-dba69b99997c.png)

_Copied from original issue: Microsoft/vscode#9523_

**Comment by dbaeumer** [comment]
_From @kieferrm on July 20, 2016 15:34_

@con-ssc It would be a great help if you could provide a sample workspace that exhibits that behavior as well as the file and position in file where you experience this. Thx!

**Comment by dbaeumer** [comment]
_From @con-ssc on July 21, 2016 6:57_

I cannot force the delay, it just happens sometimes so it is hard to provide exact information about when and how and in what workspace.

**Comment by dbaeumer** [comment]
_From @kieferrm on July 21, 2016 17:3_

@con-ssc any information about the workspace size, file size, ...? Are you developing code that uses npm like dependencies? If so, is there a certain dependency pattern? Are you running low on memory when it happens? Anything that may help to understand the issue better?

**Comment by dbaeumer** [comment]
_From @kieferrm on August 2, 2016 20:32_

@dbaeumer feel free to close as we don't have additional info.

**Comment by dbaeumer** [comment]
_From @con-ssc on August 3, 2016 7:23_

I have no npm modules installed. Where can I find the workspace size? The file size varies from about 40 lines to 1000 lines, doesn't seem to matter. I'm not running low on memory at all, also CPU is ok.
Is there a way to monitor the performance of the suggestion routine somehow?

**Comment by dbaeumer** [comment]
@con-ssc yes you can :-). Add the following to your settings `"typescript.tsserver.trace": "messages"` and open the Output view and switch to the TypeScript channel. This should give you a trace of the language server actions and how long they took. If you see slow code complete requests then the problem might be in the tsserver itself.

**Comment by dbaeumer** [comment]
_From @con-ssc on August 3, 2016 13:9_

Does this exist for javascript as well?

**Comment by dbaeumer** [comment]
_From @con-ssc on August 3, 2016 13:18_

I will keep you posted if I see anything. Would it be possible to somehow add a notification if the request time is higher than lets say 200ms or so?

**Comment by dbaeumer** [comment]
Yes, exists for JS as well. Same setting. 
No notification right now.

**Comment by dbaeumer** [comment]
_From @con-ssc on August 4, 2016 11:24_


![image](https://cloud.githubusercontent.com/assets/8189808/17400146/9286721e-5a46-11e6-9f84-45ab3f74c683.png)

Okay I was "lucky" to have an example now.
![image](https://cloud.githubusercontent.com/assets/8189808/17400158/a80b576c-5a46-11e6-9007-97f080d18ccb.png)
![image](https://cloud.githubusercontent.com/assets/8189808/17400163/b0da2148-5a46-11e6-85f3-c48fe4a40f5d.png)

**Comment by dbaeumer** [comment]
Wow. The code complete request took ~17 seconds. I will move this to the TS team since they provide the server. @con-ssc would be great if you could share some code to be able to reproduce this.

**Comment by con-ssc** [comment]
I'm afraid I cannot, because it is code me made for a customer. It is not particularly long, only 1229 lines. And it is a simple js file.

**Comment by con-ssc** [comment]
I have another example where vscode is unable to get snippet infos. It eventually did not get the snippet infos at all btw.
![image](https://cloud.githubusercontent.com/assets/8189808/18386755/38dfe546-7699-11e6-9855-4b832204946d.png)

**Comment by RyanCavanaugh** [comment]
Without code to reproduce the issue we can't take any steps toward fixing it.

**Comment by con-ssc** [comment]
Since it happens randomly it is hard to reproduce for myself, and since I'm working on customer projects I cannot share those code lines. Is there any way to write to the tsserver output to a log file? Then I would enable verbose.

**Comment by con-ssc** [comment]
Also there seems to be a hicup sometimes when code highlight takes to long. The screenshot is just from before a crash.
I'd really love to log those events if you tell me how.
![image](https://cloud.githubusercontent.com/assets/8189808/18430115/650fe4c8-78d7-11e6-9039-4bb5b1b302b6.png)

**Comment by mhegazy** [comment]
@con-ssc does this happen for all files? or is there is a specific file? does this file happen to be large?

@dbaeumer the log looks similar to the issue i investigated in https://github.com/Microsoft/TypeScript/pull/10580, if diagnostics takes too long it is going to block completions. one option is to cancel the current request once a completion is fired, the cancellation work is done in the https://github.com/Microsoft/TypeScript/tree/tsserverVS-WIP branch.

**Comment by con-ssc** [comment]
@mhegazy This happens pretty randomly, that's why it is so hard for me to see a pattern. This file had about 2000+ lines so yes I would say it was "large" but not that large. It is not a thing that happens in a specific files.

**Comment by con-ssc** [comment]
I copied rxjs v4 and rx-dom into a file leading to this
![image](https://cloud.githubusercontent.com/assets/8189808/18553283/25e5dc54-7b60-11e6-8608-b2cf87bc59dd.png)
I'm now unable to even open that file and scroll down. It crashes around line 10k/12k when I scroll down.

**Comment by mhegazy** [comment]
how big is the resulting file in terms of size?

**Comment by con-ssc** [comment]
@mhegazy 611kb

**Comment by mhegazy** [comment]
I think this should be handled by https://github.com/Microsoft/vscode/issues/11850. if still persists, please reopen.
