### ISSUE TITLE
TypeScript - Generate method

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#10140]
_From @wallverb on July 17, 2016 3:24_

Feature request: It would be awesome if for TypeScript one could have 'generate method' in quick fix for such cases (and similar):

![image](https://cloud.githubusercontent.com/assets/1723815/16898575/666acf70-4bac-11e6-8718-940376c369ea.png)

_Copied from original issue: Microsoft/vscode#9404_

**Comment by DanielRosenwasser** [comment]
Fixed by #16045.
