### ISSUE TITLE
type alias cannot work with class now?

### ISSUE THREAD

**Issue by plantain-00** [Microsoft/TypeScript#10146]
**TypeScript Version:**  2.0.0 beta or playground

**Code**

```ts
class A {}
type B = A;

new A();
new B();
```

**Expected behavior:**
no error.
**Actual behavior:** 
error, cannot find name 'B'

**Comment by evmar** [comment]
B is a type, not a function.  You can use it like `let x: B = ...` but not in any non-type position.
Try `const B = A`.
