### ISSUE TITLE
tale between strictNullCheck and process

### ISSUE THREAD

**Issue by unional** [Microsoft/TypeScript#10158]
**TypeScript Version:**  2.0.0

**Code**

```ts
process.on('message', m => {
  process.send('received') // <-- Object is possibly 'undefined'
})
```

Workaround:
```ts
process.on('message', m => {
  ;(process as any).send('received')
})
```

Other suggestion?

**Comment by RyanCavanaugh** [comment]
What's the definition of `process` ?

**Comment by unional** [comment]
It's the node's process. In `node.d.ts` or `core.d.ts`? (I haven't check)

**Comment by RyanCavanaugh** [comment]
This is the definition for `send`, which indicates it may not be present. If it's always present (I'm not sure?), you should send a PR to DT to remove the `?`.
```ts
 send?(message: any, sendHandle?: any): void;
```

**Comment by unional** [comment]
I see. It is rightly to be optional. It is only defined in child process.

I don't think it is practical to reference a different type for `NodeJS.process` for a child process code. So I'll close this issue.

Thanks!
