### ISSUE TITLE
Very slow compilation with allowJs

### ISSUE THREAD

**Issue by normalser** [Microsoft/TypeScript#10157]
**TypeScript Version:**  2.1.0-dev.20160803

Trying to migrate medium size `js` project to `ts` so I am using `allowJs: true` in tsconfig.json and have mix of `ts` (10%) and `js` (90%) files already

Unfortunately compilation time with `allowJs:true` is 23 seconds while with `allowJs:false` is 3 seconds.

Problem seems to be that all js files follow the `node_modules` (`"moduleResolution": "node"` in tsconfig.json)

Is there any way to have `moduleResolution:classic` for `JS` part while `node` for `TS` or some other way to configure the project so that `js` files are not so deeply analyzed.

Here are the stats:

with `allowJs:true`

```
time tsc -p . --traceResolution | wc -l
  154171
tsc -p . --traceResolution  23.37s
```

```
time tsc -p . --traceResolution | grep node_modules | wc -l
  148740
tsc -p . --traceResolution  23.41s
```

with `allowJs:false`

```
time tsc -p . --traceResolution | wc -l
  1498
tsc -p . --traceResolution  3.03s
```

```
time tsc -p . --traceResolution | grep node_modules | wc -l
  1392
tsc -p . --traceResolution  3.02s
```

**Comment by robmcm** [comment]
On a similar note, would it be possible to have a different config for JS files? That way you could not only change "moduleResolution" but also properties like "allowUnreachableCode".

Ideally for JS that is being migrated I don't want any compiler linting. I have tried using two instances of TS webpack loaders to handle JS and TS separately, but with no luck.

**Comment by abobwhite** [comment]
I am using TypeScript with webpack and I can't even get the app to run locally with `allowJS` because it just takes so long. I am struggling with finding a way to slowly convert my project to TS to have both JS and TS at the same time. I was able to use `babel` with the JS separately for my app to run but the testing is all out of sorts and can't figure it out. I figured `allowJS` would be the golden ticket but so far, it's unusable.

**Comment by mhegazy** [comment]
@abobwhite do you see the same behavior running outside of webpack (i.e. `tsc --p tsconfig.json`)? can you share the otuput of `tsc --diagnostics --p ..`?

**Comment by mhegazy** [comment]
Also one common issue we see is excluded files. with `--allowJs` the compiler will grok your folder for .js files, that might include .js files you did not care about, `tsc --listFiles` should list the files the compiler is consuming.

**Comment by abobwhite** [comment]
Thanks @mhegazy Your comments helped point me in a slightly different direction. It turns out it was a ts-loader setting I needed. I needed to set `transpileOnly` to `true` on the processing of my .js files. All the type checking on the .js files was causing it to take 2-3 minutes.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
