### ISSUE TITLE
Constructor of Event types have incorrect signature

### ISSUE THREAD

**Issue by jokester** [Microsoft/TypeScript#10164]
**TypeScript Version:**  1.8.10

**Code**

``` ts
const ev = new CloseEvent(); // and lot other events
```

**Expected behavior:**

Do not type check, because this does not align with actual constructor of [a mandatory "type" parameter](https://dom.spec.whatwg.org/#dom-event-event).

**Actual behavior:** 

Type checks but causes `Uncaught TypeError: Failed to construct 'CloseEvent': 1 argument required, but only 0 present.` in browser.

**Comment by kitsonk** [comment]
Yes, it appears a lot of them are missing, although `Event` is typed correctly.

It needs to be changed in the [TSJS-lib-generator](https://github.com/Microsoft/TSJS-lib-generator#contribution-guidelines).

**Comment by jokester** [comment]
Thanks for the hint @kitsonk . See if I can understand the generator /o\

**Comment by kitsonk** [comment]
Since it seems rather fundamental and conflicts with the W3C IDL, I suspect @mhegazy or @zhengbli might come along and fix it.  I don't know if it is "wrong" in the Edge IDLs or if there is some level of missing interpretation of the IDLs.
