### ISSUE TITLE
Flattening state machines from yield/for-of

### ISSUE THREAD

**Issue by d180cf** [Microsoft/TypeScript#10161]
Consider the following chunk of code with a couple nested for-of loops that iterate over what `function * region(...)` returns:

``` ts
search: for (const lib of region(root, (t, s) => sameColor(s) && b.inBounds(t))) {
    // <...>

    for (const p of region(lib, (t, s) => !sameColor(t) && b.inBounds(t))) {
        // <...>

        for (const q of stone.neighbors(p)) {
            // <...>
        }

        if (!b.get(p) && !isAdjacent)
            continue search;
    }

    // <...>
}
```

This looks nice and concise, but it's also slow and it creates/disposes lots of those iterator objects keeping GC busy. Not so nice for a chunk of code that needs to run 100k times per second. My crazy ask is to consider merging the state machines that tsc makes when converts this stuff to es5: the result is supposed to be one huge and unreadable, but flat switch-case that does all the nested for-of loops without invoking `region`.

**Comment by mhegazy** [comment]
I can not see much that can be done here. each one of these calls result in an iterator object. the state machine is done inside the genarator function itself, so not sure how multiple calls of that can be merged.
