### ISSUE TITLE
narrowing an `undefined | A` property not working anymore

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#10169]
nightly build August 5, 2016

```typescript
function noUnnecessaryTypeAnnotations(node: ts.Node, checker: ts.TypeChecker): Issue | void {
    if (isVariableDeclaration(node)) {
        if (node.initializer !== undefined && node.type !== undefined) {
            node.initializer; // <-- expected: Expression; actual: Expression | undefined
        }
   }
}
```

**Comment by ahejlsberg** [comment]
The issue here is that the checker thinks `node.type !== undefined` might be a discriminant type guard, to it resets other type guards for properties of the form `node.xxx`. A workaround would be to reverse the two type guards (but of course you'll then have the same problem for `node.type`).
