### ISSUE TITLE
the '--stripInternal' may cause naming problems.

### ISSUE THREAD

**Issue by domchen** [Microsoft/TypeScript#10165]
I have noticed that lots of guys are waiting for the `internal` modifier : #5228  After a searching, I  found this: http://www.typescriptlang.org/docs/handbook/compiler-options.html , and take a look at the option --stripInternal. It's exactly what we need! I just don't know why it is not mentioned in any document. Anyway, thanks for add this awesome feature. we gonna use it in our engine right away.

But I think that strip the internal properties or methods away directly may cause some naming problem? For example, if the user creates a subclass and declare a method with the same name to the internal method of the base class. He will not get a error reporting since the internal name is not in the .d.ts file. If I am right, I think the better way to do this is change the modifier to `private` in the .d.ts instead of stripping the internal method away. But for the @internal above the class, I would like to strip it away, otherwise, I have to put lots of @internal in every method within it.

**Comment by RyanCavanaugh** [comment]
As indicated in the docs, this feature is experimental, and may cause problems. The problems you're describing are why it's not an official feature yet :wink:

**Comment by domchen** [comment]
@RyanCavanaugh Thanks for your reply :)  The things is we need this `internal` feature badly. We have talked to your evangelists about it back on 2014 and wait for it a long time, like two years... So I would like to ask when it will be official? and what is final form, is it the `internal` modifier or the `--stripInternal`?

**Comment by RyanCavanaugh** [comment]
2.1 would be the earliest, though I expect it will be later.

**Comment by domchen** [comment]
It is great! Thanks for your reply again. @RyanCavanaugh
