### ISSUE TITLE
2.0 emits optional class properties defined in constructors, which breaks compatibility

### ISSUE THREAD

**Issue by jasonchoimtt** [Microsoft/TypeScript#10179]
**TypeScript Version:**  2.0.0

**Code**

```ts
export class A {
  constructor(private b?: string) {}
}
```

In TypeScript 1.8, emits d.ts:

```ts
export declare class A {
    private b;
    constructor(b?: string);
}
```

In TypeScript 2.0, emits d.ts:

```ts
export declare class A {
    private b?;
    constructor(b?: string);
}
```

**Expected behavior:**

Do not break backward-compatibility on emitted `d.ts` without code change.

**Actual behavior:** 

The generated `d.ts` cannot be consumed with TypeScript 1.8, namely with error:

` error TS1112: A class member cannot be declared optional.`

//cc: @IgorMinar

**Comment by RyanCavanaugh** [comment]
Indeed there's no reason to emit `b?` instead of `b` here.

FYI we don't guarantee back-compat .d.ts emit for prior releases.
