### ISSUE TITLE
typescriptlang.org request: Can we have a directory of libraries/frameworks written in typescript?

### ISSUE THREAD

**Issue by saosebastiao** [Microsoft/TypeScript#10176]
Yes, yes...it isn't supposed to matter because typescript is javascript+types. But it still does matter, because:
- Libraries that are not written in typescript require huge amounts of infrastructure in order to work correctly. DefinitelyTyped only really exists for libraries that are written in JS, because TS libraries can publish their types directly within their repository and can export to `@types` with a single directive in their package.json. 
- Libraries that are not written in typescript have declaration development lags. A JS library can publish an API version bump to NPM, and it falls on the community to update the types in DefinitelyTyped accordingly. If you aren't comfortable enough to do that yourself, it usually means that you end up waiting weeks/months to be able to update to the latest version. 
- Libraries that are not written in typescript have a declaration version mismatch for intentional library version choices. If I don't want to bump to `<INSERT_UBIQUITOUS_TERRIBLE_DEPENDENCY>` 3.0 because my project has a dependency on 2.2, how do I ensure that I have the correct types for 2.2? 
- Libraries that are not written in typescript are not constrained by actual type safety. You see this all the time...declaration files that just don't seem to work unless you have `any` sprinkled everywhere. I can't even count the number of libraries I've found where you have a function has three arguments, the second two of which are optional, and which have code contained in the function to determine which of the two optional arguments were actually supplied when the function is called with two arguments. They might adequately function correctly, but that behavior would _never_ fly in a Typescript library. 
- JS libraries have massive problems with bugs that would never even pass the compiler if they were written in typescript. 

I can't think of a single reason why I would ever choose a JS-first library as a typescript developer if there is a competent TS-first alternative. Hell, I've even considered switching from React to Angular2 (which, IMO, is a complexity nightmare) just to avoid the nagging TS-related issues with React. As such, whenever I need a new `<FUNCTIONALITY>`, the first thing I would like to know is if there are any good TS libraries out there for it. And as such, a directory of libraries that are written in typescript would be an incredibly valuable resource.

**Comment by RyanCavanaugh** [comment]
We've got the "Friends of TS" page now along with some quotes.

I don't think we want to maintain a list of all TS libs as that list is extremely long at this point, not to mention js libs that are pushing their own self-maintained types.
