### ISSUE TITLE
Inefficient compilation for fields initialization without explicit constructor (target=ES6)

### ISSUE THREAD

**Issue by chancancode** [Microsoft/TypeScript#10175]
**TypeScript Version:**  1.8 and nightly (2.1.0-dev.20160805)

**Code**

```ts
class A {}

class B extends A {
  private foo = 1;
}
```

**Expected behavior:**

```js
// compiles into...
class A {}

class B extends A {
  constructor() {
    super(...arguments);
    this.foo = 1;
  }
}
```

**Actual behavior:** 

```js
// compiles into...
class A {}

class B extends A {
  constructor(...args) {
    super(...args);
    this.foo = 1;
  }
}
```

- - -

If you take the first compilation and feed it into Babel (loose mode), you will get (more or less)...

```js
var A = function A() {
};

var B = function (_A) {
  _inherits(B, _A);

  function B() {
    _A.apply(this, arguments);
    
    this.foo = 1;
  }

  return B;
}(A);
```

But if you take the second version, you will get...

```js
var A = function A() {
};

var B = function (_A) {
  _inherits(B, _A);

  function B() {
    for (var _len = arguments.length, args = Array(_len), _key = 0; _key < _len; _key++) {
      args[_key] = arguments[_key];
    }

    _A.call.apply(_A, [this].concat(args));
    
    this.foo = 1;
  }

  return B;
}(A);
```

Which is much less efficient – it allocates two extra arrays, reify `arguments` into an array, extra `concat` and ...`.call.apply` (o_0).

**Comment by SaschaNaz** [comment]
I heard passing `arguments` object breaks JS engine optimization where the only exception is passing it to `Function.prototype.apply()`. Isn't it the case here?

**Comment by DanielRosenwasser** [comment]
By the way, when class property initializers are accepted into ES and TypeScript has an emit target for that version, do you think we'd need to continue doing this?

**Comment by SaschaNaz** [comment]
Not sure what you mean, I think ES2015 spec never changes?

**Comment by kitsonk** [comment]
> Not sure what you mean, I think ES2015 spec never changes?

But there is ES2016, ES2017, ES2018... 😄

**Comment by SaschaNaz** [comment]
>But there is ES2016, ES2017, ES2018... 😄 

You're right, but I said that because I didn't think TS remove ES2015 support in near future.

**Comment by kitsonk** [comment]
> You're right, but I said that because I didn't think TS will remove ES2015 support in near future.

It won't, I assume Daniel's question was stating when there are property initialisers as part of the ES spec (which is likely to happen) and there is a TypeScript target for that (which there will be) does the emit suggested above still need to take place.

**Comment by mhegazy** [comment]
thanks @chancancode
