### ISSUE TITLE
'This' type lost in callback

### ISSUE THREAD

**Issue by wallverb** [Microsoft/TypeScript#10173]
**TypeScript Version:**  2.1.0-dev.20160803

Sorry if duplicate, couldn't find

**Code**

```ts
class Handler{
    foo() {}
}
function test(cb:(this:Handler, n:number)=>void) {
    const handler = new Handler()
    // cb.bind(handler)(5)
    cb.call(handler, 5)
}

test((n)=>{
    this.shouldFail() // type of this == 'any'
})

```

**Expected behavior:**
`this` in last line should be of type `Handler`

**Actual behavior:** 
`this` in last line is of type `any`

**Comment by RyanCavanaugh** [comment]
@sandersn :bell:

**Comment by sandersn** [comment]
Try using a `function`. Arrow functions don't get a this, so you're getting the global `this` &mdash; probably `window` or something.

**Comment by RyanCavanaugh** [comment]
Can't believe I missed noticing that :disappointed:

**Comment by sandersn** [comment]
Don't feel bad. It took me almost 10 minutes and I actually wrote a test for it.
