### ISSUE TITLE
Clarify documentation and provide examples on the various filesystem-related options in tsconfig

### ISSUE THREAD

**Issue by saosebastiao** [Microsoft/TypeScript#10177]
So far, as of typescript@2.1.0-dev.20160805, we have the following filesystem-related options in tsconfig:

* files
* include
* exclude
* declarationDir
* mapRoot
* outFile
* outDir
* rootDir
* sourceRoot
* baseUrl
* paths
* rootDirs
* typeRoots
* types

Some of these might have ambiguous meanings to people new to the typescript ecosystem. Some of these might interact with others (ie. typeRoots and types), in optional, complimentary, or mutually exclusive ways. Some of these might have semantic issues (ie. how does the compiler resolve a glob pattern in `includes` if it is also excluded in `excludes`). Sometimes there are more ways than one to accomplish a particular goal. 

It would be extremely helpful to clarify and extend the documentation for these options, and include examples.

**Comment by mhegazy** [comment]
There should be documentation about these in: https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Compiler%20Options.md and 
https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/tsconfig.json.md.

We are happy to accept PRs for the handbook, as well as any specific requests for filling documentation holes.
