### ISSUE TITLE
[lib.d.ts] Incorrect typing for CanvasPattern

### ISSUE THREAD

**Issue by CookieShade** [Microsoft/TypeScript#10184]
**TypeScript Version:**  1.8.34

**Code**

``` ts
let canvas = document.createElement("canvas");
let context = canvas.getContext("2d");

let pattern: CanvasPattern = []; // !!!
context.fillStyle = pattern;
context.strokeStyle = 0; // !!!
```

**Expected behavior:**
Fails to compile due to `[]` and `0` not being valid `CanvasPattern`s.

**Actual behavior:** 
Successfully compiles, probably due to [`CanvasPattern`](https://github.com/Microsoft/TypeScript/blob/master/lib/lib.d.ts#L5871) being declared as an empty `interface`, which is obviously implemented by all objects. At runtime, the style is solid black.

``` ts
// lib.d.ts
interface CanvasPattern {
}
//...
fillStyle: string | CanvasGradient | CanvasPattern;
//...
strokeStyle: string | CanvasGradient | CanvasPattern;
```

**Comment by DanielRosenwasser** [comment]
Looks like it should have a tag or something.

For reference: https://developer.mozilla.org/en-US/docs/Web/API/CanvasPattern

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by CookieShade** [comment]
I'd make a PR, but I lack the experience and know-how to semantically fix the issue.

**Comment by mhegazy** [comment]
potentially put a `readonly _tag: never` field on the interface, that would make it unassingable from other types.
