### ISSUE TITLE
short-hand module declaration not working in application files (only in d.ts files)

### ISSUE THREAD

**Issue by choeller** [Microsoft/TypeScript#10192]
**TypeScript Version:**   2.1.0-dev.2016080

When declaring global variables it is possible to do something like this:

``` ts
declare var _: any;
...
_.every(...)
```

directly in the source code-file 

trying to do the same for module leads to an exception in the TypeScript-Compiler:

``` ts
declare module 'lodash';
import * as lo from 'lodash';
```

```
 TS2664: Invalid module name in augmentation, module 'lodash' cannot be found.
```

adding the `declare module 'lodash'` in a `d.ts` file make the compiler happy again

**Expected behavior:**

It should be possible to declare modules "on the fly" in source-code without the need to create a d.ts file for that.

**Comment by hriss95** [comment]
I think that using the string literal notation for the name is meant for external modules so you cannot really do that, unless you use namespaces. I could be wrong, I am learning TypeScript in the moment :)

**Comment by blakeembrey** [comment]
This is because of the difference of the `import` or `export` keywords. Those keywords at the top-level change the definition/file to a module and change `declare module` from the global `module` declaration to an augmentation.
