### ISSUE TITLE
Type guard cannot narrow undefined with greater/less-than operators.

### ISSUE THREAD

**Issue by ItGacky** [microsoft/TypeScript#10197]
**TypeScript Version:**  2.0.0

**Code**

``` ts:test.ts
function test(n: number | undefined): number {
  return (n > 0) ? n : 0;
}
```

```
$ tsc --strictNullChecks test.ts 
```

**Expected behavior:**
Compiled without errors because `undefined > 0` is always false.

**Actual behavior:** 

```
test.ts(2,10): error TS2322: Type 'number | undefined' is not assignable to type 'number'.
  Type 'undefined' is not assignable to type 'number'. 
```

**Comment by SlurpTheo** [comment]
Still the case in **TypeScript Version:**  2.0.3 using `--strictNullChecks`.

**Comment by Y-Less** [comment]
Should also narrow with `undefined` on the RHS as well.

**Comment by jakebailey** [comment]
Just looking at ancient issues; we've now said multiple times in later issues that this is not desirable, e.g. #17801, #50414, among many new checks which explicitly disallow these comparisons when they involve undefined/null.
