### ISSUE TITLE
No way to declare setter/getter only in interfaces

### ISSUE THREAD

**Issue by mindarelus** [Microsoft/TypeScript#10196]
export interface ITimer {
	get isRunning():boolean;
	start():void;
	stop():void;
	reset():void;
}

Why is this not working? This is the most logical thing anyone would expect. The value of the isRunning property should be changed, only inside the class instances. Otherwise anyone could change it outside, which is not good.

**Comment by SimonMeskens** [comment]
Use the readonly keyword instead of the get keyword:

```typescript
export interface ITimer {
    readonly isRunning: boolean;
    start(): void;
    stop(): void;
    reset(): void;
}
```

**Comment by ahejlsberg** [comment]
Interfaces make no distinction between regular properties and accessor properties--it's an implementation detail left up to the implementer of the interface. As suggested above, use the `readonly` keyword to get the effect of a property that has only a `get` accessor.

**Comment by mindarelus** [comment]
Thanks.. I guess I'll have to get used to write "readonly" :)

**Comment by dungdm93** [comment]
@ahejlsberg
using `readonly` in this case is fine. But it make people confused.
`readonly` keyword normally indicate **un-reassignable** property. But in the interface, it declare type has that `getter`.
#11578

**Comment by SimonMeskens** [comment]
@dungdm93 But it is not reassignable, so it makes sense?

**Comment by andre-dw** [comment]
I'm trying to get the same working but i get an error: 
```
Argument of type '{ ID: number; firstName: string; lastName: string; }' is not assignable to parameter of type 'IUser | undefined'.
  Type '{ ID: number; firstName: string; lastName: string; }' is not assignable to type 'IUser'.
    Property 'getRole' is missing in type '{ ID: number; firstName: string; lastName: string; }'.
```

```
import { UserRoles } from '@/enums/userRoles';

export interface IUser {
  ID?: number | null;
  firstName?: string;
  lastName?: string;
  role?: UserRoles;
  readonly getRole: string;
  readonly getFullName: string;
}

export class User implements IUser {

  public ID: number | null = null;
  public firstName: string = '';
  public lastName: string = '';
  public role: UserRoles = UserRoles.GUEST;

  constructor(user?: IUser) {
    if (user) {
      this.ID = user.ID ? user.ID : null;
      this.firstName = user.firstName ? user.firstName : '';
      this.lastName = user.lastName ? user.lastName : '';
      this.role = user.role ? user.role : UserRoles.GUEST;
    }
  }

  public get getRole(): string {
      return UserRoles[this.role];
  }
  public get getFullName(): string {
    return `${this.firstName} ${this.lastName}`;
  }
}

const user: User = new User({ ID: 1, firstName: 'Bruce', lastName: 'Wayne' });
```

**Comment by RyanCavanaugh** [comment]
@andre-dw you declared `getRole` and `getFullName` as required properties and then didn't provide them.
