### ISSUE TITLE
(bug) short-hand module declaration not working in combination with 'noImplicitAny'

### ISSUE THREAD

**Issue by choeller** [Microsoft/TypeScript#10191]
**TypeScript Version:**  2.1.0-dev.2016080

**Code**
Trying to declare a module with the new short-hand syntax like this:
```ts
  declare module 'lodash';
```
leads to the following TypeScript-Compiler error
```
error TS7005: Variable ''lodash'' implicitly has an 'any' type.
```
I also can't find a way to make this "explicit any".

**Expected behavior:**

new shorthand syntax for module-declaration should also work with 'noImplicitAny' activated

**Comment by DanielRosenwasser** [comment]
Actually from the source code

> `// Ambient shorthand module is an implicit any`

At the very least, the error message you got is bad.

@mhegazy @andy-ms do we really want to consider this an implicit any? The entire point of `noImplicitAny` was to warn when the type system couldn't figure out the type of something. Here, *you didn't expect the type system to figure anything out*. You just wanted it to be quiet about something else and it yelled at you about your fix. The solution isn't any better than the original problem.

**Comment by RyanCavanaugh** [comment]
I don't see why we should make you write a type annotation either. It's just ceremony and the thing you have to write is very awkward.

**Comment by mhegazy** [comment]
but the module import is typed implicitly as any. how is this different from `declare var $`. we force you to write `:any` or it is an error.

**Comment by mhegazy** [comment]
the question here is why use `declare module 'lodash';` instead of including the declaration file for lodash?

**Comment by choeller** [comment]
@mhegazy I would be happy, If I could say 
```
declare module 'myuntypedmodule' : any;
```
but AFAIK there is just no way to do this. `lodash` was just an example. We are integrating a lot of legacy libs in our project, so this is where this short-hand syntax could be useful.
