### ISSUE TITLE
Consider adding a compiler option to not automatically build the inferred type names

### ISSUE THREAD

**Issue by Tragetaschen** [Microsoft/TypeScript#10199]
**TypeScript Version:**  2.0.0

I have a project with several environments where js runs and in these environments, different versions of a global `require` function exist:

**Code**

```json
{
    "dependencies": {
        "@types/node": "6.0.31",
        "@types/phantomjs":"1.9.26",
        "typescript": "2.0.0"
    }
}
```
```ts
var a;
```

When I run `node_modules\.bin\tsc test.ts`, I get 
```
node_modules/@types/node/index.d.ts(69,13): error TS2300: Duplicate identifier 'require'.
node_modules/@types/phantomjs/index.d.ts(6,18): error TS2300: Duplicate identifier 'require'.
```
and with `--traceResolution` I can see these errors originate from building the internal `__inferred type names__.ts`.

I can fix the error by specifying any explicit `--types` option (but it needs a valid argument), but AFAICS I cannot explicitly turn off building the inferred types. Might be useful.

**Comment by RyanCavanaugh** [comment]
The root cause is that `phantomjs.d.ts` needs to not have this line https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/phantomjs/phantomjs.d.ts#L6

> and with --traceResolution I can see these errors originate from building the internal __inferred type names__.ts.
> I cannot explicitly turn off building the inferred types. Might be useful.

This isn't really a coherent description of what's going on.

If you don't want the `@types/phantomjs` package, you can just not install it (?), or you can fix the .d.ts file to not have an incorrect global redefinition of `require`, or you can manually specify a `--types` list as you've discovered. Those are the options.

**Comment by Tragetaschen** [comment]
Hmm,

- I want phantomjs, because a part of my project requires it (no pun intended)
- I want node, because another part of my project requires it
- Both packages define a JS environment (phantomjs based on Webkit's engine, node based on V8)
- Both have a global 'require' function in their environment, so I assume the `.d.ts` are correct and the `require` functions have nothing to do with each other.

Now, TypeScript helpfully (I mean it!) gathers all available `@types` packages by default and stumbles over the conflict. In that setup, my entire project is "tainted" and I can never go back to the default, so I just want to disable it.

**Comment by RyanCavanaugh** [comment]
It sounds like you need to split your project into two compilations depending on which environment it's targeting. It can't be the case that two different things are setting up *different* globals named `require` at the same time.

**Comment by Tragetaschen** [comment]
You are right, that's why I'm asking for a way to tell TypeScript not to do it :) Because right now, the default handling of `@types` creates that problem.

But you are right. It's probably the easiest to make a hard cut between these two worlds.

**Comment by felixfbecker** [comment]
I also met this problem when using `@types` in conjunction with the typings definition manager:
```
======== Resolving type reference directive 'validator', containing file '/Users/felix/git/npm-sequelize/__inferred type names__.ts', root directory '/Users/felix/git/npm-sequelize/typings/globals
,/Users/felix/git/npm-sequelize/typings/modules'. ========
Resolving with primary search path '/Users/felix/git/npm-sequelize/typings/globals, /Users/felix/git/npm-sequelize/typings/modules'
Directory '/Users/felix/git/npm-sequelize/typings/globals' does not exist, skipping all lookups in it.
File '/Users/felix/git/npm-sequelize/typings/modules/validator/package.json' does not exist.
File '/Users/felix/git/npm-sequelize/typings/modules/validator/index.d.ts' exist - use it as a name resolution result.
Resolving real path for '/Users/felix/git/npm-sequelize/typings/modules/validator/index.d.ts', result '/Users/felix/git/npm-sequelize/typings/modules/validator/index.d.ts'
======== Type reference directive 'validator' was successfully resolved to '/Users/felix/git/npm-sequelize/typings/modules/validator/index.d.ts', primary: true. ========
node_modules/@types/validator/index.d.ts(318,3): error TS2300: Duplicate identifier 'export='.
typings/modules/validator/index.d.ts(295,1): error TS2300: Duplicate identifier 'export='.
```

I tried setting `types` to an empty array, but that doesn't work. I don't know what else I should `types` to. I just want TypeScript to ignore `@types` declarations, but not even `exclude` helps

**Comment by mhegazy** [comment]
Do you have `typeRoots` set?

**Comment by felixfbecker** [comment]
Yes:
```json
    "typeRoots": [
      "typings/globals",
      "typings/modules"
    ]
```

**Comment by mhegazy** [comment]
can you share a project or a sample?

**Comment by felixfbecker** [comment]
Yeah, if you take a look here: https://github.com/types/npm-sequelize/tree/v4

Those are typings for sequelize I (as a maintainer of the Sequelize library) have been maintaining for the typings declarations. I got countless requests to make them usable with npm / `@types` because those on DT are apparently not as complete, but until Microsoft/types-publisher#4 is resolved, I wanted to make it possible to install them with npm from GitHub. For this I added the `typings` dependencies on bluebird and validator also to package.json dependencies. I added `typeRoots` for preferring the `typings` dependencies when running tests in CI, but it seems to get ignored for validator.

**Comment by felixfbecker** [comment]
The workaround I do is installing dependencies with `npm install --only=dev`, but that only works for this specific project and is confusing for contributors :/

**Comment by mhegazy** [comment]
add:

```ts
  "baseUrl": ".",
    "paths": {
        "*": ["typings/modules/*"]
    }
```

to your tsconfig.json

**Comment by felixfbecker** [comment]
@mhegazy that works, thanks a lot!

**Comment by mhegazy** [comment]
Some due explanation. there are two concepts at play here. global dependencies, and modules. `typeRoots` manage redirecting globals like node for instance. but module imports go through  a different resolution path, `paths` is what controls that. so typically you need to do both.
