### ISSUE TITLE
error TS5023: Unknown compiler option 'declarationDir'.

### ISSUE THREAD

**Issue by Vadorequest** [Microsoft/TypeScript#10206]
**TypeScript Version:**  1.8.10

**Code**

```json
{
    "compilerOptions": {
        "outDir": "./build/",
        "sourceMap": true,
        "noImplicitAny": true,
        "module": "commonjs",
        "target": "es5",
        "declaration": true,
        "declarationDir": "def"
    },
    "exclude": [
        "node_modules"
    ]
}


```

**Expected behavior:** Compile.

**Actual behavior:** 
ERROR in /home/vado/service/www/MeFiO/tsconfig.json
error TS5023: Unknown compiler option 'declarationDir'.

ERROR in ./src/index.ts
Module build failed: error while parsing tsconfig.json
 @ multi main

As far as I know, this option exists and is valid: It does exist here:
http://json.schemastore.org/tsconfig

I'm using webpack and want to generate the definition files of my own files in a specific folder.
I used TS a long time ago (prior 1.5) and at the time I had a `d.ts` file which imported manually all my .ts file to reference them all, then I referenced this file in my other files so the compiler would know what I'm talking about.

So, my idea is to generate the d.ts files and references them. But I don't know if that's the good way to go actually. Anyway, `delcarationDir` isn't working and it should, if it hasn't been removed since I last used it.

**Comment by wallverb** [comment]
Read description carefully in that schema link:
"Specify output directory for generated declaration files. Requires TypeScript version 2.0 or later."
You are using 1.8.10 in that

**Comment by Vadorequest** [comment]
Thanks, I read so much docs today that I didn't even paid attention to the
details at the end... :)

**Comment by DanielRosenwasser** [comment]
Sorry for the confusion. For what it's worth, TS 2.0 beta is fairly stable.

```shell
npm install -g typescript@beta
```

**Comment by shivangsanghi** [comment]
I have typescript version above 2 but still facing this issue.
