### ISSUE TITLE
Completion list should remain open if suitable match is not found

### ISSUE THREAD

**Issue by NoelAbrahams** [microsoft/TypeScript#10204]
**TypeScript Version:**  2..0 Beta / VS 2105 Update 3

**Code**

Here's a comparison of typing in a C# vs TypeScript code file:

**C#**
![c](https://cloud.githubusercontent.com/assets/1106823/17484033/2c958caa-5d80-11e6-8aaa-b052ffcdaf87.gif)

**TS**
![ts](https://cloud.githubusercontent.com/assets/1106823/17484042/3321a086-5d80-11e6-871b-402d7a593dde.gif)

**Expected behavior:**

The completion list should remain open if a suitable match is not found.

**Actual behavior:** 

The list closes when an incorrect key is typed.

This makes it difficult to backtrack when a mistake is made. I believe this was a regression in 1.8 or thereabouts.

**Comment by paulvanbrenk** [comment]
On the other hand consider the following, which is valid javascript:

```javascript
var x = { y: 10 }

var x.hello ... 
```
showing the completion list while still typing `hello` can be confusing... we'll make this an option at some point.

**Comment by NoelAbrahams** [comment]
I have personally found this to be an obvious hindrance to productivity.

For example, when looking for say `apple`, I type `app` and since `apple` is still not within selecting distance I need to type another character. At this point if I mistype a letter, say `appx` the completion list disappears.

Now in order to bring it back up, I need to delete all of `app` and start again.

We could perhaps fix this this by bringing up the list when `x` is deleted. But that doesn't happen at present.

**Comment by NoelAbrahams** [comment]
Also I don't understand why `var x.hello ... ` is valid JavaScript. Is this not to do with TypeScript?

**Comment by paulvanbrenk** [comment]
Bringing the completion list back would be something we would need to specifically implement for TypeScript, which makes it expensive and thus low on the list of features we're considering. 

You can always hit [CTRL] + [Space] to bring back the completion list, after if closed.

**Comment by NoelAbrahams** [comment]
@paulvanbrenk, I understand that you are trying to balance the needs of people writing plain JavaScript.

But the first consideration ought to be for those working in TypeScript. Yes, I can bring back the list with Ctrl+Space, but I have to first delete the last character and press two more keys. Altogether it's 3 more keys now for functionality that was working correctly before.

I really do not find the argument that the list remains open when typing non-existent properties in JavaScript to be a compelling one. Firstly it's lazy and stubborn not to adopt TypeScript and secondly one can always hit escape to dismiss the completion box (one key vs. 3).

Please consider adding this back to the 2.1 milestone.

**Comment by paulvanbrenk** [comment]
As mentioned earlier in the thread, we'll make this behavior an option.. not going to commit for 2.1, but we're working on some IntelliSense options infrastructure now, so it's coming.

**Comment by NoelAbrahams** [comment]
Wow nothing on this?

I mean somebody breaks a working piece of code in TypeScript in order to fix an obscure issue for JavaScript users and nothing gets done about it.

This is very disappointing.

**Comment by RyanCavanaugh** [comment]
We're transitioning to LSP which will mean this behavior is language-agnostic.
