### ISSUE TITLE
Possible? Capture and return modified signature

### ISSUE THREAD

**Issue by unional** [Microsoft/TypeScript#10215]
TypeScript: 2.0.0

```ts
function factorial(num: number): number { ... }

// pfact signature: pfact(num: number): Promise<number>
const pfact = promisify(factorial)
```

AFAIK it is currently not possible, thus we need to do something like this:
https://github.com/types/npm-bluebird/blob/master/bluebird.d.ts#L333

Is it possible in the future, or it's just a hard limitation that it can't be done?

**Comment by yortus** [comment]
Would #5453 solve this?

**Comment by Igorbek** [comment]
For any given number of parameters it is possible and easy:
```ts
declare function promisify<T, R>(fn: (arg: T) => R): (arg: T) => Promise<R>;
declare function promisify<T1, T2, R>(fn: (arg1: T1, arg2: T2) => R): (arg1: T1, arg2: T2) => Promise<R>;
```ts
However the most general declaration would require #5453 (@yortus thanks, was looking for it when you replied).

**Comment by Igorbek** [comment]
BTW, I wanted to file suggestion/proposal for way more complicated scenarios like that:
```ts
declare function f<T>(arg: T): [T];
const pf = promisify(f); // it won't infer <T>(arg: T) => Promise<T> -- which is sad
```

**Comment by Igorbek** [comment]
@unional I described my thoughts on how we could express these types of signatures. Long read :)

**Comment by unional** [comment]
Thanks. I'll check it out
