### ISSUE TITLE
[SUGGESTION] "require" instead of 2-statement early return

### ISSUE THREAD

**Issue by jaw** [Microsoft/TypeScript#10225]
A better way to write early returns.
Req is short for "require".
This makes it easier to reorder and write sanity checks in the beginning of functions.

I use this nomenclature a lot in VSXu ( for instance: https://github.com/vovoid/vsxu/blob/0.6.0/lib/common/src/filesystem/archive/vsx_filesystem_archive_reader.cpp#L40 )

**Code**

```
{
  req(boolean_value);
  ....
}

instead of:

{
  if (!boolean_value)
    return;
  ....
}
```

If a return value is required, just add that (false in this case):
```
{
  req(boolean_value, false);
  .... function body ...
}
```

**Expected behavior:**

**Comment by sandersn** [comment]
What is the context for this suggestion? Code in the compiler? Examples in the handbook? Can you give some concrete examples of things you would like to see change?

**Comment by sandersn** [comment]
Actually, I just clicked through to your example. It's C++, so I guess `req` is a macro. I think you may have left this suggestion in the wrong repo. TypeScript and JavaScript do not have macros.
