### ISSUE TITLE
Error in generated js by typescript compiler

### ISSUE THREAD

**Issue by pooyaho** [Microsoft/TypeScript#10224]
I have a problem with type script generated js file and I can't solve it, this is my service file that I have problem with it:

    namespace Providers {

        export interface IProvider {
            loadTranslations(translations: ITranslations, locale: string);
        }
        module.provider('lego', LegoProvider); 
	
        class LegoProvider implements ng.IServiceProvider ,IProvider{
                
            loadTranslations(translations:ITranslations , locale: string) {
                ......
            }
    
            $get() {
                .....
            }
        }
        
    }

and generated js file is: 

    var Providers;
    (function (Providers) {
        module.provider('lego', LegoProvider); // this is the problem
    var LegoProvider = (function () {
        function LegoProvider() {
    }
    LegoProvider.prototype.loadTranslations = function (translations, locale) {
    };
    LegoProvider.prototype.$get = function () {
    };
    return LegoProvider;
    }());
    })(Providers || (Providers = {}));

It throws error because of the LegoProvider is variable and in that line it is still undefined. when I change code with this, it works correctly:

    namespace Providers {

        export interface IProvider {
            loadTranslations(translations: ITranslations, locale: string);
        }
         
	
        class LegoProvider implements ng.IServiceProvider ,IProvider{
                
            loadTranslations(translations:ITranslations , locale: string) {
                ......
            }
    
            $get() {
                .....
            }
        }
		module.provider('lego', LegoProvider); // I've moved this line to bottom
        
    }

In typescript code LegoProvider class is accessible from both positions and it doesn't make sense for me that the first position is incorrect

**Comment by RyanCavanaugh** [comment]
Code runs in the order you write it; TypeScript doesn't re-order it on your behalf. It's possible you needed to run `module.provider` before class initialization (for example, because `LegoProvider` initialized a static field in a way that depended on the `module.provider` call).

**Comment by wallverb** [comment]
@RyanCavanaugh is there any way that TS could throw an error in such cases - kind of like when you try to use variable that is declared later in the file - got bitten by it myself couple of times

**Comment by basarat** [comment]
@wallverb you are always going to run into errors if you depend on ordering across files : https://basarat.gitbooks.io/typescript/content/docs/tips/outFile.html

However in this case I think TS should error similar to how it does for other block items:

```ts
console.log(foo); // Block scoped variable used before its declaration
let foo;
```

This is because ES6 classes are block scoped and not hoisted (similar to `let`/`const`) :rose:

**Comment by DanielRosenwasser** [comment]
There's #5207/
