### ISSUE TITLE
Typings not seen from subfolder when having own tsconfig.json

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#10221]
**TypeScript Version:**  2.0.0 beta

**Folders**

```
root
    app.ts
    tsconfig.json
    tests
       tsconfig.json
       test.ts
```
- use TS 2.0. Instruct VS Code to us TS 2.0 with `"typescript.tsdk": "./node_modules/typescript/lib"` 
- In root install node typings using npm install @types/node
- following content for tsconfig.json in tests

``` json
{
    "compilerOptions": {
        "module": "commonjs",
        "inlineSourceMap": true,
        "inlineSources": true,
    }
}
```
- in tests.ts add

``` ts
import * as fs from 'fs'
```

Observer: the import is an error. The compile can't find the node typings

Why is this the case. Should the compiler look for a node_modules folder up the tree for typings. Add
a property types with [ "node" ] fixes the issue.

**Comment by aluanhaddad** [comment]
If the subdirectory contains a project which is built or loaded with a different set of options this is actually helpful behavior.

**Comment by yortus** [comment]
Looks like same problem as here: https://github.com/Microsoft/TypeScript/issues/9208#issuecomment-226682568

**Comment by mhegazy** [comment]
This should be working as intended with latest.
