### ISSUE TITLE
Visual Studio 2015 - TypeScript - Web Essentials 2015 Version 3

### ISSUE THREAD

**Issue by PaulKumar** [Microsoft/TypeScript#10226]
QUESTIONS: Is It TypeScript 1.8 and Web Essentials 2015 will work together to support split window?

![image](https://cloud.githubusercontent.com/assets/4120710/17515213/133f54a4-5e05-11e6-8966-abdff66a4b9b.png)

TypeScript Version:1.8.0 with Visual Studio 2015 SP 3
![image](https://cloud.githubusercontent.com/assets/4120710/17515238/382baca4-5e05-11e6-8e2c-1917a3266901.png)

I tried clearing cache option after installing VS 2015, still not working. Please guide me if I'm not doing something not in right way. Thanks.

**Comment by mhegazy** [comment]
Should be reported on https://github.com/madskristensen/WebEssentials2013/issues instead.
