### ISSUE TITLE
for-of with const emits wrong JS code

### ISSUE THREAD

**Issue by jrieken** [Microsoft/TypeScript#10220]
**TypeScript Version:**  Playground

http://www.typescriptlang.org/play/#src=for%20(const%20a%20of%20%5B1%2C%202%2C%203%2C%204%5D)%20%7B%20console.log(a)%3B%20%7D

When using a `for-of` and a `const` loop variable the generated code still assigns the variable (`a`) which is counter `const` and different from nodejs running such code.

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
for (const a of [1, 2, 3, 4]) { console.log(a); }
```

**Expected behavior:**
```js
for (var _i = 0, _a = [1, 2, 3, 4]; _i < _a.length; _i++) {
    var a = _a[0];
    console.log(a);
}
```

**Actual behavior:** 
```js
for (var _i = 0, _a = [1, 2, 3, 4]; _i < _a.length; _i++) {
    var a = _a[_i];
    console.log(a);
}
```

**Comment by jrieken** [comment]
for reference run: `node -e "for (const a of [1, 2, 3, 4]) { console.log(a); }"` which prints
```
$ node -e "for (const a of [1, 2, 3, 4]) { console.log(a); }"
1
1
1
1
```

**Comment by weswigham** [comment]
@jrieken That would be an error in the js runtime. AFAIK, a `const` binding in a `ForOf` declaration is supposed to receive a new binding each iteration.

Run that same code in the latest chrome (and thus recent v8):
![image](https://cloud.githubusercontent.com/assets/2932786/17510279/22bf6f2c-5dd3-11e6-95db-67f9f38eeb3f.png)
And you get the expected results. We generate the correct code here.

**Comment by vladima** [comment]
for reference: [for-of with `const` variable](https://esdiscuss.org/topic/for-of-with-const-variable)

**Comment by jrieken** [comment]
wow - good to know
