### ISSUE TITLE
control flow narrowing is broken in nightly build

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#10228]
nightly build August 9, 2016

the following used to work in July 30 build

```typescript
interface A { kind: 'A'; }
interface B { kind: 'B'; }

type C = A | B | undefined;

function never(_: never): never {
    throw new Error();
}

function useA(_: A): void {
}
function useB(_: B): void {
}
declare var c: C;

if (c === undefined) {
} else {
    switch (c.kind) {
        // below expected: narrowing to work, actual: doesn't work:
        case 'A': useA(c); break;
        case 'B': useB(c); break;
        default: never(c);
    }
}
```

**Comment by DanielRosenwasser** [comment]
@ahejlsberg was this part of your change on only narrowing unit types on property accesses (#10188)? Is `undefined` not considered a unit type?

**Comment by aleksey-bykov** [comment]
`undefined`, `void` and `null` if it matters

**Comment by ahejlsberg** [comment]
This is caused by the stricter discriminant property check introduced in #10188. It's an easy fix, we just need to ignore `undefined`, `null`, and `void` in the declared type when checking whether a property in a particular declared type is a discriminant property. I will put up a fix later today.

**Comment by aleksey-bykov** [comment]
works, thanks!
