### ISSUE TITLE
Add watcherMessage option

### ISSUE THREAD

**Issue by hdcos** [microsoft/TypeScript#10223]
**Expected behavior:**

```
tsc -w -wMsg "watching for changes in this awesome directory"
11:04:56 AM - Compilation complete. watching for changes in this awesome directory
```

Why?

Because I launch several watchers when the server starts and I want to see different logging info than 

```
11:04:56 AM - Compilation complete. Watching for file changes.
11:04:59 AM - Compilation complete. Watching for file changes.
--- etc
```

At least merge the directory watched with the --project option like this:

```
11:04:56 AM - Compilation complete. Watching for file changes in /the/directory/of/--project
```

Thx!!

**Comment by DanielRosenwasser** [comment]
@hdcos Huh, that's an interesting workflow. So you spawn your watchers as background processes in the same shell instead of in separate tmux/screen panes? Just curious in general.

**Comment by hdcos** [comment]
Yes I have many subprojects watched when I start my development server. I use elixir/phoenix and the framework create a supervisor witch childs processes. When I stop my development server all the watcher die since the supervisor die.

Maybe there is a better way and have only one watcher for all my subprojects

**Comment by DanielRosenwasser** [comment]
You could always bust out sed:

```shell
tsc --watch | sed -e "s%^\(.+\)Compilation complete. Watching for file changes.$%Finished compiling in '$(pwd)'.%
```

Or you could always prepend the directory to *every* message:

```shell
tsc --watch | sed -e "s%^(\.*\)$%$(pwd) - \1%"
```

Note: I'm using `%` as a delimiter to sed's `s` command to avoid having to escape the result of `pwd`.

You can extrapolate this to a script as well.

**Comment by RyanCavanaugh** [comment]
Declining due to lack of additional feedback
