### ISSUE TITLE
[lib.d.ts BUG] new window.Image(); //ERROR: Property 'Image' does not exists on type 'Window'

### ISSUE THREAD

**Issue by jhm-ciberman** [Microsoft/TypeScript#10241]
**TypeScript Version:**  atom-typescript

**Code**

``` ts
new Image(); //works
new window.Image(); //ERROR: Property 'Image' des not exists on type 'Window'

```

**Expected behavior:**
Image constructor should exists in window object

**Actual behavior:**
 Image constructor does not exists in window object

**Other Info:**
I actually ussing nw.js so I can't access to the window object directly:

``` ts
function newImage( win: Window): Image {
    return new win.Image(); //ERROR: Property 'Image' des not exists on type 'Window'
}
```

If I cast `win as any`, it works, but I loose the Typescript typing feature.

**Comment by mhegazy** [comment]
The library does not redefine all globals on `window`. if you want to use one of these on window you can add it, in one of your files add:
```ts
interface Window {
    Image: typeof Image;
}
```

**Comment by alan345** [comment]
Thanks @mhegazy. But where do you add this snippet? 
![image](https://user-images.githubusercontent.com/15246526/41031121-305a9c8c-6980-11e8-96a3-0d9e1cbe03d2.png)

**Comment by jamjar919** [comment]
`
interface Window {
    Image: typeof Image,
}

declare const window: Window;
`

Declare it after defining it and it should work fine.
