### ISSUE TITLE
Typed ...rest parameters with generics

### ISSUE THREAD

**Issue by andrewvarga** [microsoft/TypeScript#1024]
Is it possible to add type info to the rest parameters in a way that each individual parameter can have a different type?

This works, but with this there can be any number parameters, and all have to have the same type:

```
function myFunction<T>(...args:T[]) {
}
myFunction<number>(1, 3);
```

It would be really useful if I could force the exact number of arguments and the types for each one, but all this within generics, so something like this (but this is obviously syntactically wrong):

```
function myFunction<T>(...args:T) {
}

interface MyParams {
    [0]:string;
    [1]:number;
}

myFunction<MyParams>("a", 1)
```

An example use case is writing an observer class that the user could specify the arguments of the listener functions for:

```
class Observer<T> {
    addListener(...args:T) {
    }
}
```

If this is not supported, what do you recommend using instead? I can use any[] of course, or living with the constraint of having a fixed number of fixed typed parameters.

**Comment by alexburner** [comment]
@RyanCavanaugh @DanielRosenwasser, I believe I've found a situation in which a tuple doesn't cut the mustard. In this case, I'm trying to extend the types for a third-party library [`redux-loop`](https://github.com/redux-loop/redux-loop) (redux middleware that uses elm as its inspiration for handling async & other side effects). 

This lib extends the redux reducer to return both the state object and a `Cmd`, which can fire an action, run a function, batch multiple child Cmds, etc. They have an example reducer [here](https://github.com/redux-loop/redux-loop#write-a-reducer-with-some-cmds-side-effects).

I'd like to extend their types for [Cmd.run](https://github.com/redux-loop/redux-loop/blob/master/docs/ApiDocs.md#cmdrunfunc-options), which allows a user to specify a function to be ran, along with args to be passed to that function, and "action creators" to be called on success or failure:
```js
Cmd.run(fetchUser, {
  successActionCreator: userFetchSuccessfulAction,
  failActionCreator: userFetchFailedAction,
  args: ['123']
})
```

Currently, there is no type safety between the arguments of the function to be run and the value of the `args` option. Nor is there type safety between the return value of the function, and the arguments of the `successActionCreator` option.

The [current interface](https://github.com/redux-loop/redux-loop/blob/4e83f80f010bd98e22eaaa0a9421cef5459d74dd/index.d.ts#L112) for `Cmd.run` looks like:
```ts
static readonly run: <A extends Action>(
  f: Function,
  options?: {
    args?: any[];
    failActionCreator?: ActionCreator<A>;
    successActionCreator?: ActionCreator<A>;
    forceSync?: boolean;
  }
) => RunCmd<A>;
```

I'd like to do something that enforces a match between inputs and outputs of `f`, `options.args`, and `options.successActionCreator`. Something like:
```ts
static readonly run: <A extends Action, Args, Result>(
  f: (...args: Args) => Result,
  options?: {
    args?: Args;
    failActionCreator?: () => A;
    successActionCreator?: (result?: Result) => A;
    forceSync?: boolean;
  }
) => RunCmd<A>;
```

However, trying this, I get the error that brought me to this issue:
```
A rest parameter must be of an array type.
```

Is there a way I can accomplish this type safety, without altering `redux-loop`?

*Additionally, it would be swell if I could use `Args` and `Result` to indicate where values should match within the `Cmd.run` type, **without** requiring the user to pass explicit types in through a generic. But I don't know a way to indicate two types should match, without actually defining them (either as generics, or as specific types).*

**Comment by alexburner** [comment]
Digging further, I ran across [this proposal for Variadic Kinds](https://github.com/Microsoft/TypeScript/issues/5453) which directly addresses this issue. It looks like I may have to hold out hope for that. But if anyone has clever workarounds in the meantime, I wouldn't complain.
