### ISSUE TITLE
Intellisense issue with NODE_PATH evnvironment variable

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#10248]
_From @lekhnath on August 9, 2016 18:33_
- VSCode Version:1.4
- OS Version: Ubuntu 13.10

Steps to Reproduce:

**Project Structure**

```
<project-root>
  + libs
       - utils.js
  - app.js
```

**utils.js**
exports.greetings = function(msg){console.log(msg);}

**app.js**
var utils = require('libs/utils');
utils.greetings('Hello');

The problem is I am not getting intellinsense working properly but the program runs fine if run with :
`NODE_PATH=./ node app`

But the relative require `require('./libs/utils')` gives the intellisense.

_Copied from original issue: Microsoft/vscode#10359_

**Comment by dbaeumer** [comment]
To my knowledge the TS compiler and language server don't support this resolution pattern. Will move to the TS team.

**Comment by DanielRosenwasser** [comment]
You can use a `jsconfig.json` or `tsconfig.json` with the `baseUrl` option set to your project root. If you set your `baseUrl` to your project root (which is probably just `"."` if your config file is in the root of your package), then `require("libs/utils")` should resolve to `projectRoot/libs/utils`.

If you need more customization, you can use the `"paths"` option. See #5039 for more details.

**Comment by lekhnath** [comment]
placing a `jsconfig.json` file at project root with `baseUrl` set to `./` for `compilerOptions` still DIDN'T work.

**Screenshot of not working :**
![no intellisense](https://cloud.githubusercontent.com/assets/4231691/17579370/509f14a0-5fb4-11e6-8769-d3549e50e798.png)

**Screenshot of working but with relative path:**
![has intellisense](https://cloud.githubusercontent.com/assets/4231691/17579385/7709060a-5fb4-11e6-8d71-ff1b2eb515cb.png)

**Comment by alexkrolick** [comment]
Did you try putting `baseUrl` outside of the `compilerOptions` object?

**Comment by mhegazy** [comment]
> Did you try putting baseUrl outside of the compilerOptions object?

outside compilerOptions it is ignored. the correct place is inside it

**Comment by mhegazy** [comment]
@lekhnath can you share a sample we can play with?

**Comment by lekhnath** [comment]
[example.zip](https://github.com/Microsoft/TypeScript/files/478242/example.zip)

@mhegazy I've attached minimal example.

**Comment by jamescoletti** [comment]
Has anyone solved this? We're getting the same issue. Seems `baseUrl` definitely does not belong inside of `compilerOptions` at least in Code v1.7.1.  While it appears to be accepted at the root of the config object, it isn't fixing this particular issue.

We set NODE_PATH when running and testing our apps. For example:
```
NODE_PATH=. node ./bin/www
```
so we can include local libs with sane path resolution:
```
const hashUtil = require('src/lib/hashUtil');
``` 

Cannot seem to get Code IntelliSense to work with this style using any `baseUrl` configuration. It's only working when explicitly requiring modules using a relative path.

**Comment by jurosh** [comment]
Hi guys, I've tried ``"mapRoot": "./src/"`` instead of `baseUrl` and it helped. (VSC 1.7.1)

```
{
    "compilerOptions": {
        "target": "es5",
        "mapRoot": "./src/"
    }
}
```
And now in javascript file I can use absolute paths like:
`import {isLoading} from 'reducers/competitions';`

Note that `reducers/competitions` are located in `./src/reducers/competitions`.

**Comment by jamescoletti** [comment]
Yep `mapRoot` did it. Thanks @jurosh.

**Comment by pedro-mass** [comment]
Is this solution still valid?
setting `mapRoot` seems to be throwing errors in tests.
