### ISSUE TITLE
checking typeof variable === `string` fails with template string quotes

### ISSUE THREAD

**Issue by radarsu** [Microsoft/TypeScript#10252]
typeof checking doesnt work with `` used instead of ""

**TypeScript Version:**  1.8.0 / nightly (2.0.0-dev.201xxxxx)

**Code**

```ts
let object: ToastrData | string;
if (typeof object === "string") {
  // object is confirmed as string, works fine
}

let object: ToastrData | string;
if (typeof object === `string`) {
  // object is still ToastrData | string, works wrong
}
```

**Expected behavior:**
Even I understand that template strings are not the best choice for type checking like this, I think it should still pass.

**Actual behavior:** 
Type checking with `` doesn't work

**Comment by yahiko00** [comment]
Since template strings should be considered as a dynamic expression, I would not expect the TypeScript compiler to infer types from them.
I consider your second if-test equivalent to this one:
```ts
let a = "str";
let b = "ing";
if (typeopf object === `${a + b}` {
    // TypeScript has no means to predict the value of a template string at runtime in general
}
```

**Comment by RyanCavanaugh** [comment]
We have to draw a line somewhere. I don't think this is idiomatic or common at all.
