### ISSUE TITLE
Show some elaboration for property not existing in union type

### ISSUE THREAD

**Issue by RyanCavanaugh** [Microsoft/TypeScript#10256]
I have some code like this, except there are about a dozen types instead of just three:
```ts
interface Foo {
  kind: "foo";
  name: string;
}
interface Bar {
  kind: "bar";
  name: string;
}
interface Qua {
  kind: "qua";
  length: string;
}

type FBQ = Foo | Bar | Qua;
let x: FBQ = <any>undefined;
console.log(x.name);
```
The error reported is
```
a.ts(16,15): error TS2339: Property 'name' does not exist on type 'FBQ'.
```

This is inactionable on a union type, especially when its consituents are hidden behind an alias. We should show something like
```
a.ts(16,15): error TS2339: Property 'name' does not exist on type 'FBQ'.
   Property 'name' does not exist on type 'Qua'
```

**Comment by yahiko00** [comment]
Yes please!

**Comment by RyanCavanaugh** [comment]
Accepting PRs / committed for 2.1. Show an elaboration for the first type lacking the property (for whatever definition of 'first' falls out of the implementation)

**Comment by oijazsh** [comment]
Should there also be an elaboration when one of the constituent types has the property marked as private or protected and we are in a public context? Currently the code:

```Typescript
class Default {
    member: string;
}
class Private {
    private member: number;
}

var DP: Default | Private;
DP.member;
```

gives the error:

```
test.ts(9,4): error TS2339: Property 'member' does not exist on type 'Default | Private'.
```

This could perhaps be changed to:
```
test.ts(9,4): error TS2339: Property 'member' does not exist on type 'Default | Private'.
  Property 'member' is private and only accessible within class 'Private'.
```

I have adjusted `checkPropertyAccessExpressionOrQualifiedName` to show an elaboration when a subtype of a union lacks a property and will open a PR once I've finished adding tests. It should not be difficult to also show an elaboration when a subtype has the property marked under a stricter access qualifier.

**Comment by mhegazy** [comment]
thanks @oijazsh !
