### ISSUE TITLE
Type arguments for type aliases are displayed inappropriately

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#10258]
**TypeScript Version:**  nightly

**Code**

```ts
type ConstructorOf<T> = { new(): T }
function f<A, B, C, D, E>(x: ConstructorOf<Object>): void {}
f(class {});
```

**Expected behavior:**

Hovering over the second `f` shows `function f<{}, {}, {}, {}, {}>(x: ConstructorOf<Object>): void`

**Actual behavior:** 

Hovering over the second `f` shows `function f<{}, {}, {}, {}, {}>(x: ConstructorOf<{}, {}, {}, {}, {}>): void`

**Comment by mhegazy** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/10337
