### ISSUE TITLE
Type predicates fail to remove subclasses from unions for assumeTrue=false.

### ISSUE THREAD

**Issue by sandersn** [Microsoft/TypeScript#10254]
@ahejlsberg you probably already know about this one but I thought I'd confirm:

```ts
interface Error {
    e
}
declare function isError(value: any): value is Error;
class CustomError extends Error { }
function narrowTest(value: number | CustomError) {
    if(isError(value)) {
        let result: CustomError = value;
    }
    else {
        let result: number = value; // error!
    }
}
```

Expected: narrowing to `number` in the else branch.
Actual: No narrowing: `value: CustomError | number` in the else branch, causing an error.

I found this in [`lodash` on DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/10534).

**Comment by ahejlsberg** [comment]
This is an effect of #10216. The issue we face here is that `Error` and `CustomError` are *structurally identical* from the type system's point of view, yet at runtime a `CustomError` is an instance of `Error`, but not the other way around. The implementation currently makes the assumption that when two types are `structurally identical`, but not the same type, then neither is an instance of the other. We could look into "cheating" and check whether one `extends` the other, even though technically that isn't part of the type. Maybe we just need to get over that.

**Comment by sandersn** [comment]
Hm. We certainly treat structurally identical things badly in a number of other places, so it's already a definite anti-pattern. 

I should probably just update lodash's DefinitelyTyped tests, and maybe the Typescript FAQ.
