### ISSUE TITLE
Generic type extending a constructor function type should be usable as one

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#10262]
**TypeScript Version:**  nightly

**Code**

```ts
function f<T extends { new(): Object }>(cls: T) {
    class X extends cls {}
    class Y extends (<{ new(): Object }>cls) {}
}
```

**Expected behavior:**

No error.

**Actual behavior:** 

    src/a.ts(2,21): error TS2507: Type 'T' is not a constructor function type.

It's also a bit frustrating that even `class X extends (<any>cls) {}` won't work. Normally `any` can help get you out of any compile error!

**Comment by yuit** [comment]
From investigating on this, I found this [issue](https://github.com/Microsoft/TypeScript/issues/4890)
