### ISSUE TITLE
Breaking Change: Running TypeScript on ES3 hosts no longer supported

### ISSUE THREAD

**Issue by RyanCavanaugh** [Microsoft/TypeScript#10278]
#10270 uses APIs present only in ES5 runtimes to gain 15% speed and ~20% reduced memory usage.

**This does *not* impact targeting ES3 hosts with --target ES3**. The only scenario impacted is running the TypeScript compiler or language service on an ES3 host, which we believe to be very rare.

**Comment by DanielRosenwasser** [comment]
I thought I posted this at #10125?

**Comment by RyanCavanaugh** [comment]
Please search for duplicates before logging new issues.
