### ISSUE TITLE
Should/could typeguarding work on arrays/length

### ISSUE THREAD

**Issue by wallverb** [Microsoft/TypeScript#10272]
**TypeScript Version:**  @next

**Code**

```ts
//  --strictNullChecks
let args = process.argv.slice(2) // type: string[]
let test1 = args[Number.MAX_VALUE] // type: 'string' but should it be 'string | undefined' ?
if (args.length > 0) {
  let test2 = args.shift() // Type: 'string | undefined' - but should it be 'string' ?
}
```

**Comment by gcnew** [comment]
Strictly speaking - no. It doesn't guard against sparse arrays, e.g:

```ts
const arr: number[] = [];
arr[1] = 5;
if (arr.length) {
    arr.shift(); // undefined
}
arr.shift(); // 5
```

Then again, indexing's true type is also `T | undefined`.

**Comment by wallverb** [comment]
@gcnew  Thanks for the explanation, but then shouldn't accessing sparse arrays and having `--strictNullChecks` on - always return `T | undefined`

**Comment by gcnew** [comment]
@wallverb Yes, well and truly. It was done for convenience as explained by the reply to https://github.com/Microsoft/TypeScript/pull/7140#issuecomment-192606629

**Comment by wallverb** [comment]
wow, interesting, thank you so much for finding that comment for me. I wish such knowledge was more easily accessible/findable :)

**Comment by gcnew** [comment]
BTW: as a workaround this works:

```ts
function isShiftable<T>(arr: T[]): arr is Array<T> & { shift(): T; } {
    return !!arr.length;
}

const arr: number[] = [5];
if (isShiftable(arr)) {
    const x = arr.shift(); // x is of type `number`
}
```

**Comment by dlmanning** [comment]
This workaround is not working for me.

```typescript
function isNotEmpty<T>(arr: T[]): arr is Array<T> & { pop(): T; } {
    return arr.length > 0;
}

function doSomething () {
  const stack: Vertex[] = []
  const groups: string[] = []

  while (isNotEmpty(stack)) {
    const v = stack.pop() // v is still typed as Vertex | undefined
    groups.push(v.id) // [ts] Object is possibly 'undefined'
  }
}
```

did I miss something?

**Comment by gcnew** [comment]
@dlmanning You are right, the suggested fix is the the way to go. It should be noted though that this is a hack - I just found that it worked. I don't think there is a notion of commutativity, I suspect it's just the compiler picking the first matching declaration met in the intersection.
