### ISSUE TITLE
Typescript errors “incorrectly implements interface” Type 'Subject<boolean>' is not assignable to type 'Subject<boolean>'

### ISSUE THREAD

**Issue by jbeckton** [Microsoft/TypeScript#10277]
**TypeScript Version:**  1.8.0

Angular 2 & Typescript app.

I have an abstract class inside an NPM package that I am trying to provide implementation for inside my app code. This all worked fine until I added the public isLoggedIn:Subject<boolean>; property.

**Code**

**packages.json**

```json
"rxjs": "5.0.0-beta.6"
```

**current-user.service.ts**

```javascript 
import {Subject} from "rxjs";

@Injectable()
export abstract class CurrentUserContextService {

public isLoggedIn:Subject<boolean>;
public userId:string;
public userName:string;
public email:string;
public scope:string[];

constructor() {  }

}
```

**my-current-user.service.ts**

```javascript
import {Subject} from "rxjs";
@Injectable()
export class MyCurrentUserContextService implements CurrentUserContextService {

// interface properties.
public isLoggedIn:Subject<boolean>;
public userId: string;
public userName: string;
public email: string;
public scope: string[];

// add custom properties as needed.
constructor() { }

}

// add custom methods as needed.

}
```

**main.ts**

```javascript
bootstrap(AppComponent, [    
    MyCurrentUserContextService,
    {provide: CurrentUserContextService, useExisting: MyCurrentUserContextService}
    ])
```

**Error**

```
Class 'MyCurrentUserContextFactoryService' incorrectly implements interface 'CurrentUserContextFactoryService'. Types of property 'currentUserContext' are incompatible. Type 'MyCurrentUserContextService' is not assignable to type 'CurrentUserContextService'. Types of property 'isLoggedIn' are incompatible. Type 'Subject' is not assignable to type 'Subject'. Property 'destination' is protected but type 'Subject' is not a class derived from 'Subject'.
```

**Expected behavior:**

no errors

**Actual behavior:** 

Class 'MyCurrentUserContextFactoryService' incorrectly implements interface 'CurrentUserContextFactoryService'. Types of property 'currentUserContext' are incompatible. Type 'MyCurrentUserContextService' is not assignable to type 'CurrentUserContextService'. Types of property 'isLoggedIn' are incompatible. Type 'Subject' is not assignable to type 'Subject'. Property 'destination' is protected but type 'Subject' is not a class derived from 'Subject'.

**Comment by ZombieHippie** [comment]
Would you demonstrate the `Subject` type mismatch by showing code imports Subject from a file, or demonstrate where Subject comes from for each example here?

As a note, you can improve your formatting by using three ticks to do multiline TypeScript
```markdown
```typescript
const hello;
\```
Remove backslash
```

**Comment by jbeckton** [comment]
@ZombieHippie added imports and cleaned up the code sections.

**Comment by RyanCavanaugh** [comment]
It looks like you've over-simplified your repro; the error message refers to a property (`destination`) which isn't shown anywhere.

Anyway the root cause here is that you declared `destination` as `protected`. A `protected` method can only be implemented or overridden by a class that inherits (through `extends`, not `implements`) the class which first declared the method.

Basically, if you really intend for people to write `class Mine implements Yours {` instead of `class Mine extends Yours {`, you need `Mine` to not have any abstract private or protected properties.

**Comment by jbeckton** [comment]
@RyanCavanaugh There is no property 'destination' in my code, that may be inside the RxJS library. The code shown in my OP is literally all the code I have for this with the exception of a core angular import for the @Injectable. My abstract class has no private or protected members.

**Comment by RyanCavanaugh** [comment]
Can you set up a repro I can run locally?

**Comment by jbeckton** [comment]
@RyanCavanaugh Here is a simple repro of the issues. There is a README text file with some notes explaining things. Hope this helps.

[TypeScript-Errors-Repro.zip](https://github.com/Microsoft/TypeScript/files/414618/TypeScript-Errors-Repro.zip)

**Comment by jbeckton** [comment]
@RyanCavanaugh Disregard... My apologies for wasting your time! And I too am sorry I wasted quite a bit of my time as well. This is not a  TypeScript problem but rather an Angular CLI (Broccoli) problem.

I just wanted to be sure so I downloaded the Angular 2 quick start RC3 and wired up my library the same way I did in the repro I attached earlier and it compiles and runs like a champ. 

I will be removing the Angular CLI from our toolkit tomorrow as it is far from ready for production software development. I have lost at least 2 days trying to figure this out as well as creating workarounds in our libraries...

**Comment by RyanCavanaugh** [comment]
Thanks for the follow-up. Hopefully anyone else who hits that error can land here to see what the deal was!

**Comment by bhushangahire** [comment]
Do you remember what was your fix? I am getting same issue

**Comment by jbeckton** [comment]
@bhushangahire My fix was to remove the Angular CLI. I think at this point it may be fixed in the latest release but I am not sure.
