### ISSUE TITLE
TypeScript NuGet package is not installed correctly on ASP.NET Core Web App project

### ISSUE THREAD

**Issue by ryohpops** [Microsoft/TypeScript#10274]
**Visual Studio Version:**

Visual Studio 2015 Community Update 3

**TypeScript Version:**
- 2.0.0-beta from Nuget
- 1.8.36.0 from VS2015

**Reproduce:**
1. Create ASP.NET Core Web Application (.NET Core) project
2. Install Microsoft.TypeScript.MSBuild 2.0.0-beta via `Manage NuGet Packages for Solution...`
3. Create tsconfig.json
4. Create .ts source file which contains TS 2.0 syntax
5. Click `Build Solution`

**Project Structure:**
- WebApplication1
  - wwwroot
  - scripts
    - file.ts
  - tsconfig.json

**tsconfig.json:**

``` json
{
  "compilerOptions": {
    "noImplicitAny": false,
    "noEmitOnError": true,
    "removeComments": false,
    "sourceMap": true,
    "target": "es5",
    "module": "system",
    "moduleResolution": "node"
  },
  "compileOnSave": true,
  "include": [
    "scripts/**/*"
  ],
  "outDir": "wwwroot"
}
```

**Source File:**

``` ts
class Hoge {
    infiniteLoop(): never {
        while (true) {
        }
    }
}
```

Error    TS2304 Cannot find name 'never'.

**Diagnostic Log:**

https://gist.github.com/ryohpops/ee49c2382eae981eb7257ad339ba302a

**Expected behavior:**

The project is compiled with TS 2.0.0-beta

**Actual behavior:** 

The project is compiled with TS 1.8.36.0 and emit compile error at new syntax

**Comment by ZombieHippie** [comment]
Someone correct me if I'm wrong, but I think the Visual Studio bug tracker may be a more appropriate avenue for this issue https://connect.microsoft.com/visualstudio

**Comment by ryohpops** [comment]
I posted this issue here because I thought it might be related to the install script of TS NuGet package.
I will post this again to VS bug tracker as you said if this is caused by VS.

**Comment by ZombieHippie** [comment]
For reference, the TypeScript NuGet package you are referring to is here https://www.nuget.org/packages/Microsoft.TypeScript.MSBuild/2.0.0-beta

**Comment by ryohpops** [comment]
I didn't notice I can download the .nupkg file, thank you for the info.
I thought I found the problem;
`install.ps1` will NOT be executed on projects managed by `project.json` since NuGet 3.0

From [NuGet documentation](https://docs.nuget.org/create/creating-and-publishing-a-package):
> - Install.ps1 runs when a package is installed in a project.
>   - [NuGet 3.x] This script will not be executed in projects managed by project.json

The new way to edit MSBuild targets and props seems:
> A new convention has been added to the structure of NuGet packages. As a peer to \lib, \content, and \tools, you can now include a '\build' folder in your package. Under this folder, you can place two files with fixed names, {packageid}.targets or {packageid}.props. These two files can be either directly under \build or under framework-specific folders just like the other folders. The rule for picking the best-matched framework folder is exactly the same as in those.
> 
> When NuGet installs a package with \build files, it will add an MSBuild element in the project file pointing to the .targets and .props files. The .props file is added at the top, whereas the .targets file is added to the bottom.

**Comment by ryohpops** [comment]
After I created this issue, the structure of TS NuGet package is updated to catch up with the documentation I've quoted above.
This issue looks solved at least on TypeScript side.

Installation on an ASP.NET project still fails though, this is caused by NuGet which does NOT support .xproj project.
