### ISSUE TITLE
Issue with && and type inference

### ISSUE THREAD

**Issue by wallverb** [Microsoft/TypeScript#10271]
**TypeScript Version:**  @next

**Code**

```ts
function  formatNumber(price: number|undefined): string|undefined {
    return price && price.toString()
}

```

**Expected behavior:**
Should compile

**Actual behavior:** 
Error: `string | 0 | undefined not assignable to string | undefined`

**Comment by yortus** [comment]
@wallverb I can reproduce this with `--strictNullChecks`. No errors without that flag.

**Comment by yortus** [comment]
The compiler error looks correct to me, since if you pass in `0`, it will return `0`, which contradicts the return type annotation, hence the error.

**Comment by wallverb** [comment]
yea, good point, thanks :)
