### ISSUE TITLE
Duplicate identifiers

### ISSUE THREAD

**Issue by sramam** [Microsoft/TypeScript#10284]
**TypeScript Version:**  nightly (2.1.0-dev.20160808)

**Code**
This is a behavior report - not sure it's a bug or resolvable. 

npm alternative [ied](https://github.com/alexanderGugel/ied), creates a symbolic link to the actual library install within node_modules. When using typescript@next, this causes any declaration files to be discovered twice, causing a "TS2300 Duplicate identifier" error.

To try it out:

```
git clone https://github.com/sramam/typescript-starter-node
cd typescript-start-node
npm install ied
./node_modules/.bin/ied install
npm run build

```

When run with npm alone, this will work

```
git clone https://github.com/sramam/typescript-starter-node
cd typescript-start-node
npm install
npm run build

```

**Expected behavior:**
Ideally, one should be able to use ied. However, suspect this is not a case that can be supported. 

**Actual behavior:** 
error TS2300: Duplicate identifier

**Comment by RyanCavanaugh** [comment]
Isn't this just a matter of adding proper folders to the `exclude` list?

**Comment by mhegazy** [comment]
please reopen if still an issue.

**Comment by sramam** [comment]
I should have replied earlier - since ied uses hashes as part of the directory name, using the exclude list can be quite a pain. Again, I don't know there is a good answer for this apart from not using ied. The wicked fast installs of ied will be missed!
