### ISSUE TITLE
VS 2015 Intellisense not finding typings in parent folder with TS 2.0

### ISSUE THREAD

**Issue by djflex68** [Microsoft/TypeScript#10287]
**TypeScript Version:**  2.0
Visual Studio 2015 is complaining about definitions not found (because they are in a parent folder).
But in my tsconfig.json file, I'm referencing explicitly this parent folder in "includes" section. I've also downloaded Typescript 2.0 beta plug-in for Visual Studio 2015.
The compilation works on command line using tsc, which means definitions files are resolved at compile time, but Visual Studio Intellisense stills complain about them.
Any idea about this ? 

Thanks

**Comment by djflex68** [comment]
Any idea about this ? 
Here is a repro of the problem : [demo](http://www.filedropper.com/demo_12)

**Comment by mhegazy** [comment]
this looks fixed for me using the latest builds. should be out in the next few days.
