### ISSUE TITLE
No extra space before and after brace when formatting inline JavaScript objects

### ISSUE THREAD

**Issue by alexanderby** [Microsoft/TypeScript#10282]
- VSCode version 1.4.0

There seems to be no option to prevent inserting extra space after and before braces when formatting inline JS objects.
For example, when I expect
`var obj = { x: 5, y: 7 };`
to look like
`var obj = {x: 5, y: 7};`

**Comment by alexanderby** [comment]
As an example this indentation is used in D3 https://github.com/d3/d3-collection/blob/master/src/entries.js

**Comment by OliverJAsh** [comment]
Another use case is import statements, e.g. `import {x} from 'y';`

**Comment by mhegazy** [comment]
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/9613 and https://github.com/Microsoft/TypeScript/issues/9224 respectively
