### ISSUE TITLE
React.Component props doesn't allow explicit 'any' type when {"noImplicitAny": true}

### ISSUE THREAD

**Issue by bezreyhan** [Microsoft/TypeScript#10294]
**TypeScript Version:**  2.0

relevant config: {"noImplicitAny": true}

**Code**

```ts
class VerticalNav extends React.Component <any, IVerticalNavState> {
  constructor(props) {
    super(props);
    this.state = {closed: false}
  }
}
```

**Expected behavior:**
No type errors thrown.

**Actual behavior:** 
` error TS7006: Parameter 'props' implicitly has an 'any' type.`

This error should not be thrown because props has explicitly been set to type: `any`;

**Comment by RyanCavanaugh** [comment]
It's still implicit because it lacks a type annotation. The fact that the `props` parameter eventually ends up being set to the `props` property isn't something the compiler can know.

**Comment by bezreyhan** [comment]
Ok got it thanks for the quick response.
