### ISSUE TITLE
Peek/goto a imported symbol should reveal/goto what was imported, not the import statement

### ISSUE THREAD

**Issue by jrieken** [Microsoft/TypeScript#10299]
_From @kdvolder on August 12, 2016 0:19_
- VSCode Version: Version 1.4.0
  Commit 6276dcb0ae497766056b4c09ea75be1d76a8b679
  Date 2016-08-04T16:49:32.489Z
  Shell 0.37.6
  Renderer 49.0.2623.75
  Node 5.10.0
- OS Version: Ubuntu 12.04

This is for typescript, but probably also applies to javascript.

Let's say I have a import statement like this:

`import {
     CompletionItem, CompletionItemKind
} from 'vscode-languageserver';`

And a bit further down I have a reference to 'CompletionItem'.

When I 'peek' or 'goto' definition for the reference it takes me to the import statement. That's really not all that interesting to see. What I'm really interested in is the 'real' definition of the symbol rather than the line of code that imports it.

This is annoying because 

a) if I am doing 'goto definition' it means I have to navigate twice.

b) if I am trying to 'peek' then I'm not even sure how I can peek what I really want to see (is it possible to peek 'recursively' from inside a peek window?

_Copied from original issue: Microsoft/vscode#10454_

**Comment by octref** [comment]
It has been a month and this issue hasn't been triaged...

Hope it can get fixed soon. Without this I basically can't use peek definition for TS.

**Comment by andy-ms** [comment]
Tested this now:

**a.ts**:

```ts
import { bee } from "./b";
bee();
```

**b.ts**:

```ts
export function bee() {}
```

Goto-def on `bee` in `a.ts` takes me to `b.ts`.
Hovering over `bee()` gives me `(alias) bee(): void`.

Is this already the correct behavior?

**Comment by mhegazy** [comment]
> Is this already the correct behavior?

this should also work for `default` imports.

**Comment by andy-ms** [comment]
Looks like that is working too. See also the `goToDefinitionImportedNames` tests.
