### ISSUE TITLE
Getting   error TS2364: Invalid left-hand side of assignment expression

### ISSUE THREAD

**Issue by tamilhce** [Microsoft/TypeScript#10292]
```ts
export class Hero {
  id: number;
  name: string;
}

  t1:Hero = {
  id: 1,
  name: 'Windstorm'
};
```
For the above    angular2 type script statement,  
Im am hitting  following error, attached  the debug logs 
[npm debug.txt](https://github.com/Microsoft/TypeScript/files/413849/npm.debug.txt)

app/app.component.ts(7,1): error TS7028: Unused label.
app/app.component.ts(7,8): error TS2364: Invalid left-hand side of assignment expression.

**Comment by RyanCavanaugh** [comment]
This is a syntax error. You probably meant to write `let t1: Hero = {` ?

**Comment by tamilhce** [comment]
yeah, got it , it seems like the document which i follow has the some error,Thanks you

**Comment by tangsiqiVicky** [comment]
export class AppComponent { 
 t1：Hero  = {
  id：1，
  name：' Windstorm ' 
};
}
