### ISSUE TITLE
[Errors][Message] Generic type argument on identifier expression

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#103]
tests/cases/conformance/parser/ecmascript5/Generics/parserMemberAccessExpression1.ts

```TypeScript
Foo<T>.Bar();
```

Old: 

!!! A parameter list must follow a generic type argument list. '(' expected.

New: 

!!! Expression expected.

**Comment by DanielRosenwasser** [comment]
With

```TypeScript
let Foo: { Bar: any };

Foo<T>.Bar();
```

you now get

```
TS2349: Cannot invoke an expression whose type lacks a call signature.
TS1005: '(' expected.
TS2304: Cannot find name 'Bar'.
TS1005: ')' expected.
```

Not sure if we want to say this is fixed.

**Comment by mhegazy** [comment]
I do not think there is much value here. closing.

**Comment by mhegazy** [comment]
I do not think there is much value here. closing.
