### ISSUE TITLE
Auto-complete should auto-complete from cursor position to start of identifier

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#10304]
I want to write `test(test(a))`. Though I made a mistake and just wrote `test(a)` first. I put the cursor in front of `a` and write `t`. And I think it should try to autocomplete from there.

``` ts
declare function test(p1: any): void;
let a: any;
test(/*/a); // Forgot that it should be test(test(a));
test(t/*/a); // should auto-complete test from here.
```

**Comment by RyanCavanaugh** [comment]
It's actually editors that perform the filtering and selection process here
