### ISSUE TITLE
Handbook - Interfaces

### ISSUE THREAD

**Issue by kittencoder** [Microsoft/TypeScript#10301]
Handbook link: https://www.typescriptlang.org/docs/handbook/interfaces.html

In the last topic, Interfaces Extending Classes, the extends in the example code differ from what the explanation below tells.

Here is my suggestion for a new code example:
```ts
class Control {
    private state: any;
}

interface SelectableControl extends Control {
    select(): void;
}

class Button extends Control implements SelectableControl {
    select() { }
}

class TextBox extends Control implements SelectableControl {
    select() { }
}

class Image extends Control {
}

class Location extends Control {
    select() { }
}
```

**Comment by yuit** [comment]
@kittencoder I moved this issue to handbook [repo](https://github.com/Microsoft/TypeScript-Handbook)
