### ISSUE TITLE
--noUnusedLocals doesn't consider React to be "used" when using JSX files

### ISSUE THREAD

**Issue by bartq** [Microsoft/TypeScript#10312]
**TypeScript Version:**   2.1.0-dev.20160723 

... because it complains that `React` is declared but never used. It doesn't understand JSX transformations apparently.

**Comment by yuit** [comment]
@bartq  could you provide some sample code that causes the problem?

**Comment by DanielRosenwasser** [comment]
He means `--noUnusedLocals`.

Minimal repro:

```tsx
import React = require("react");

export const FooComponent = <div></div>
```
