### ISSUE TITLE
Suggestion: Add the nameof compile-time operator to convert property and function names into strings #1579

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [Microsoft/TypeScript#10317]
Hello,

I know you already think of this issue and closed it:
https://github.com/Microsoft/TypeScript/issues/1579#issuecomment-236221905

I am not sure why? People want that feature and someone already did babel plugin for that (see end of that post) - so why TS cannot have this?

**Comment by aleksey-bykov** [comment]
and parameters and type-parameters and names of types and everything else where `Identifier` is used

**Comment by RyanCavanaugh** [comment]
Please leave a comment in the original post if you disagree with the outcome.
