### ISSUE TITLE
typings error in lib.d.ts

### ISSUE THREAD

**Issue by maclarensg** [Microsoft/TypeScript#10329]
I've encounter this error

```
../node_modules/typescript/lib/lib.d.ts(12844,11): error TS2320: Interface 'SVGFEBlendElement' cannot simultaneously extend types 'SVGElement' and 'SVGFilterPrimitiveStandardAttributes'.
  Named property 'result' of types 'SVGElement' and 'SVGFilterPrimitiveStandardAttributes' are not identical.

```
**SVGFilterPrimitiveStandardAttributes** has _result: SVGAnimatedString;_

whereas 

**SVGElement** has _result:any_  I guess, because it has very nesty extensions, as I've grep 'result'
```
# grep 'result:' ../node_modules/typescript/lib/lib.d.ts
    evaluate(expression: string, contextNode: Node, resolver: XPathNSResolver, type: number, result: XPathResult): XPathResult;
    result: any;
    result: any;
    result: any;
    evaluate(expression: string, contextNode: Node, resolver: XPathNSResolver, type: number, result: XPathResult): XPathResult;
    evaluate(contextNode: Node, type: number, result: XPathResult): XPathExpression;
    result: any;
    result: SVGAnimatedString;
```
**Note:** I've also change the type to _result: any_ for **SVGFilterPrimitiveStandardAttributes** and no compilation warnings.

**Comment by yuit** [comment]
@maclarensg what TypeScript version you are using?

**Comment by mhegazy** [comment]
this would be caused by another declaration in your compilation that changes the shape of one of the SVG interfaces. Interfaces in TypeScript can be augmented by re-declaring them. one of your files would include a declaration that changes the shape of one of the involved interfaces causing this issue.

**Comment by maclarensg** [comment]
Hi, 

Apologies on my late reply. The version is as follows:

# tsc -v
Version 1.8.10
