### ISSUE TITLE
Allow class access modifiers (public, private, protected) to be written in sections

### ISSUE THREAD

**Issue by yahiko00** [Microsoft/TypeScript#10324]
It is quite verbose and anoying having to duplicate class access modifiers for each property.

For instance:
```ts
abstract class Animal {
    public abstract constructor(name: string, species: string, sex: "Male" | "Female" | "None");
    public abstract getName(): string;
    public abstract getSpecies(): string;
    public abstract getSex(): "Male" | "Female" | "None";

    protected abstract eat(): void;
    protected abstract move(): void;

    private name: string;
    private species: string;
    private sex: "Male" | "Female" | "None";
}
```

It would be simpler and clearer if we could make a section for public (resp. private and protected) properties.

```ts
abstract class Animal {
    public:
        abstract constructor(name: string, species: string, sex: "Male" | "Female" | "None");
        abstract getName(): string;
        abstract getSpecies(): string;
        abstract getSex(): "Male" | "Female" | "None";

    protected:
        abstract eat(): void;
        abstract move(): void;

    private:
        name: string;
        species: string;
        sex: "Male" | "Female" | "None";
}
```

This is obviously a toy example. But for much larger classes, such an ability to make sections would help to make code clearer.

**Comment by nippur72** [comment]
I don't think it's clearer, currently one-line signature tells everything, with your proposal you have always to scroll up looking for the keyword. I remember from the C++ days scrolling up and down just to find the place where to put your declaration.

**Comment by 19majkel94** [comment]
The IDE could support this feature and show you a little "popup", just like when you scroll through a big function/method - you have it's declaration showing up on top over the code.

If it's usefull for someone - why not. TSLint makes me crazy with linting that the order is public protected private, so when I order it in this way it would be easier to have the accesors in sections.

**Comment by aluanhaddad** [comment]
`public` is implicit, and matches the actual nature of the emitted JavaScript so you can shorten all of those `public abstract ....` declarations. I really do not want to see the introduction of additional features which encourage the use of `private` and `protected`, especially `protected`....

@19majkel94 if you do not like the rule don't enable it. I do not like that rule, preferring to group members logically, so I don't enforce it.

**Comment by yahiko00** [comment]
The purpose of this humble proposal is precisely to point out that to mitigate the fact that access modifiers are to be declared for each property, we tend to use shortcuts like assuming `public` is implicit. Personnally, I never use the `public` keyword, but it leads to an imbalance where some properties have an explicit access modifiers and some have not.
Also, as pointed out by @19majkel94, having the ability to write access modifiers in section, would simplify the code when we have to gather properties by "accessibility".
And, I will not discuss here about the relevance of `protected`. It just exists in TypeScript, so such a proposal needs to take it into account.

**Comment by aluanhaddad** [comment]
@yahiko00 but there is no ambivalence or ambiguity because everything is public. If you want to limit access and follow the principal of least privilege you may want to consider using a factory instead of a class as your API boundary.

**Comment by RyanCavanaugh** [comment]
Languages seem to always pick one or the other (member annotation vs sections) and stick with it and I don't think we should break precedent there. An immediately obvious problem is how to interpret this
```ts
class Foo {
  private:
    x: number;
    protected y: number;
    z: string;
}
```
where you could legitimately argue that `z` should be `public` (because a modifier "resets" the state to the default), `protected` (because it follows another `protected` member and this class is using sections?), or `private` (because you're "still in" a `private` section).

**Comment by 19majkel94** [comment]
I think that if you use section annotation, you can't use then member annotation in the same class because it's doesn't make sence. If there's no other language that combine this two features I think it's too complex to implement.

**Comment by yahiko00** [comment]
Although I agree my proposal needed to be elaborated a little bit more, I would have expected it to be opened for discussion longer.
As said by @19majkel94 , section style and inline style should be mutually exclusive. It was this way in my mind, although I have not mentionned it explicity. This way, implementing this syntactic sugar should not be that complex. But I admit it would be non trivial to implement to current grammar. Please, let this proposal a second chance to live! :)

**Comment by RyanCavanaugh** [comment]
I'm not sure what you expect to get out of the open/close state of this issue? People can still find it and comment on it. We could pretend we were mulling it over for a week but I think you'd rather know right away that it's very unlikely to happen. There would have to be some super compelling use case for us to allow two different ways of doing the exact same thing when so many other major languages with classes get along just fine with one.
