### ISSUE TITLE
Object destructuring failed with any type

### ISSUE THREAD

**Issue by unional** [Microsoft/TypeScript#10326]
ts: 2.0.0

```ts
const { username } = { username: 'x'}
```

RHS username is infer as string, but then it error saying username is implicitly any.

![image](https://cloud.githubusercontent.com/assets/3254987/17647144/7b608966-619a-11e6-8b7e-40520106bb26.png)

**Comment by mhegazy** [comment]
this is a duplicate of https://github.com/Microsoft/TypeScript/issues/8229
