### ISSUE TITLE
Type narrowing not scope aware

### ISSUE THREAD

**Issue by ithinkihaveacat** [Microsoft/TypeScript#10339]
**TypeScript Version**

2.0 (installed via `npm install typescript@2`)

**Code**

```ts
function foo(x: number|string): number {

  if (typeof x === "string") {
    x = 1;
  }

  function bar() {
    return 1 + x;
  }

  return bar();
}
```

**Expected behavior**

Code compiles cleanly.

**Actual behavior** 

Compiler complains `Operator '+'  cannot be applied to types 'number' and 'number | string'` (within function `bar()`).

**Comment by JannesMeyer** [comment]
I am just a TypeScript user myself, but this is much more complex than you might think, because `function bar` is hoisted to the top of the scope before your `if`:

```typescript
function foo(x: number|string): number {

  function bar() {
    return 1 + x;
  }

  if (typeof x === "string") {
    x = 1;
  }

  return bar();
}
```

**Comment by ithinkihaveacat** [comment]
Yes, true. I realize this is a slightly tricky case, but I think this type error/warning is bogus: `x` can only be a number within `bar()`, and I [got the impression from the docs](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#control-flow-based-type-analysis) that TS 2.0 (though not 1.8) is supposed to know this.

**Comment by yortus** [comment]
TypeScript does not reach that level of control flow analysis (yet). See also #7719 and #10180.
