### ISSUE TITLE
VSCode error reporting support stopped working in Version 2.1.0-dev.20160813

### ISSUE THREAD

**Issue by wallverb** [Microsoft/TypeScript#10336]
VSCode error reporting support stopped working in `Version 2.1.0-dev.20160813`

Here is the screenshot:
![image](https://cloud.githubusercontent.com/assets/1723815/17664778/781f95e6-62c4-11e6-95e8-afefbc976048.png)

The same for `Version 2.1.0-dev.20160812`:
![image](https://cloud.githubusercontent.com/assets/1723815/17664794/94f17464-62c4-11e6-88ed-b91eeed89ca2.png)

**Comment by mhegazy** [comment]
is this still an issue?

**Comment by wallverb** [comment]
@mhegazy with latest @next version it is ok now, thanks
