### ISSUE TITLE
TypeScript - ability to move export to another file (refactoring)

### ISSUE THREAD

**Issue by timruffles** [Microsoft/TypeScript#10343]
**TypeScript Version:**  1.8.0 / nightly (2.0.0-dev.201xxxxx)

**Expected behavior:**

It'd be nice to be able to `Move export to file`, to quickly break down large sets of exports into focussed, smaller files.

**Comment by mhegazy** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/6487
