### ISSUE TITLE
[Visual Studio] Colorize `${}` as a keyword in ES6 template strings

### ISSUE THREAD

**Issue by nippur72** [Microsoft/TypeScript#10367]
Visual Studio Code correctly colorizes `${}` as a keyword in template strings, but Visual Studio does not:

![interpolation](https://cloud.githubusercontent.com/assets/2598443/17702155/febda990-63cc-11e6-9bee-0ce0e5f5219f.png)

**Comment by mhegazy** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#253
