### ISSUE TITLE
Incorrect caching of infinitely expanding comparisons

### ISSUE THREAD

**Issue by JsonFreeman** [Microsoft/TypeScript#1036]
A followup bug to pull request #1017.

This example is adapted from tests/cases/compiler/typeComparisonCaching.ts:
```ts
interface A<T> {
   p: A<C<T>>;
   s: C<T>;
}

interface B<U> {
   p: B<D<U>>;
   s: D<U>;
}

interface C<T> {
   q: T;
}

interface D<U> {
   q: U;
}

var a: A<C<string>>;
var b: B<D<number>>;

a = b;

var c: C<string>;
var d: D<number>;

c = d; // Should not be allowed
```

If you comment out the line `a = b`, you get the right result, that `D<number>` is not assignable to `C<string>`. However, if you have `a = b` first, the checker ends up caching that `C<string>` and `D<number>` are assignable, because it thinks they are infinitely expanding generics. This is very similar to what typeComparisonCaching.ts was trying to test for, but it did not account for infinitely expanding types.

I believe the fix is to make the infinite expansion detection return Maybe instead of True. The obvious drawback is that this would regress issue #1002. So we may need to add some sort of temporary caching for Maybe results. These cannot go in the permanent cache, so they would have to go into a temporary cache whose lifetime is the same as the assumption the Maybe is based on. There would be two different lifetime schemes, one for a normal recursive type (a la typeComparisonCaching.ts) and one for infinitely expanding recursive types.

**Comment by mhegazy** [comment]
it is a bug alright.. but we have not gotten any reports of this from the wild, nor we have a clear idea on how to fix it.

**Comment by JsonFreeman** [comment]
Reopening this because I have an idea I want to try. We might be able to fix this by not caching infinitely expanding results at the top level. We would have to add the ability to distinguish between Maybe that's because of simple recursion, versus Maybe that's because of infinite expansion. For the infinite expansion case, we do not cache at the very top, we only the intermediate results in a temporary cache. In other words, infinitely expanding results would never graduate to the global relation cache.
