### ISSUE TITLE
VSCode "Format Code" causes tslint failure with (old-school) type assertions

### ISSUE THREAD

**Issue by LOZORD** [Microsoft/TypeScript#10362]
Preceded by https://github.com/Microsoft/vscode-tslint/issues/69 and https://github.com/Microsoft/vscode/issues/10296

**TypeScript Version:**  1.8.0

**Code**

If I have code like this:

```ts
const bar = <Bar> Thing.getFoo();
```

and then "Format Code" in VSCode (alt-shift-F on Mac), I get this:

```ts
const bar = <Bar>Thing.getFoo();
```

**Expected behavior:**

The spacing should not have been changed. (__Note__: without a [specific setting](http://palantir.github.io/tslint/rules/whitespace/), this causes a failure with tslint.)

**Actual behavior:** 

The space after the old-school/bracket-style type assertion is removed, causing a tslint error.

**Comment by RyanCavanaugh** [comment]
Looks like this isn't currently configurable, but is controlled by the `noSpaceAfterTypeAssertion` rule

**Comment by mhegazy** [comment]
The current behavior is the intended design. this is similar to C# cast expression formatting in VS for instance.  the request here is to add a new formatter option to add a space after type assertion.
