### ISSUE TITLE
Dependencies being compiled when they are excluded

### ISSUE THREAD

**Issue by soulcorrosion** [Microsoft/TypeScript#10365]
**TypeScript Version:**  nightly (2.0.0-dev.201xxxxx)  (on Windows)

**Project structure**

```ts
 - src 
      - file1.ts
      - file2.ts
- tsconfig.json
```

**Code**

file1.ts
```ts
import {Dependency} from "./file2";
export class Todo  {
    constructor () {   
      console.log(Dependency);
    }
}
```

file2.ts
```ts
export class Dependency  {
    constructor () {   
      console.log("I am the dependency");
    }
}
```

tsconfig.json
```ts
{
    "compilerOptions": {
        "target": "es5",
    "module": "system",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": true,
    "noImplicitAny": false,
    "declaration": true,
    "watch": false
 
    },
    "include": ["src/**/*.ts"],
    "exclude": ["src/file2.ts"]
}
```

**Expected behavior:**

As far as I understood, the exclude list only affects what is set in the "include" glob. I would expect file2.ts to be excluded from compilation. Correct?

**Actual behavior:** 

file2.ts gets compiled.

**Comment by RyanCavanaugh** [comment]
`exclude` only affects which files are added to the compilation automatically as a result of folder scanning. It doesn't prevent files from being emitted. There currently isn't a way to emit some files but not others.

**Comment by mhegazy** [comment]
please see https://github.com/Microsoft/TypeScript/wiki/FAQ#why-is-a-file-in-the-exclude-list-still-picked-up-by-the-compiler
