### ISSUE TITLE
No intellisense in VSCode

### ISSUE THREAD

**Issue by Seikho** [Microsoft/TypeScript#10366]
Not that I think it matters, but currently using VSCode 1.4. This behaviour does not occur in `typescript@2.1.0-dev.20160812`.

**TypeScript Version:**  nightly 2.1.0-dev.20160813 onwards

**Code**

```ts
// Clone my demo repo then skip to 'Terminal' steps or manually re-create it
git clone https://github.com/seikho/intellisense-repro

// .vscode/settings.json
{
    "typescript.tsdk": "node_modules/typescript/lib"
}

// tsconfig.json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5"
    },
    "exclude": [
        "node_modules"
    ]
}

// package.json
{
  "main": "index.js",
  "devDependencies": {
    "@types/node": "^6.0.34",
    "typescript": "^2.1.0-dev.20160816"
  }
}

// index.ts
const foo = 1;
foo;

// Terminal
npm install
code .

// Mouse
Hover things
```

**Expected behavior:**
Glorious intellisense

**Actual behavior:** 
No intellisense :cry: 

Removing the `tsconfig.json` works around the issue.

**Comment by Seikho** [comment]
Seems to be a regression in b988bc98a. Works fine prior to this commit.

**Comment by Seikho** [comment]
In particular, [these changes](https://github.com/Microsoft/TypeScript/commit/b988bc98a19c342f938f02adb72be1fd85cd0515?diff=split#diff-08a3cc4f1f9a51dbb468c2810f5229d3R1077)

**Comment by aluanhaddad** [comment]
I have tested this with 2.1.0-dev.20160813 through 2.1.0-dev.20160816 and am experiencing the same issue.
