### ISSUE TITLE
"A class must be declared after its base class" on classes in different directories

### ISSUE THREAD

**Issue by SaschaNaz** [Microsoft/TypeScript#10363]
**TypeScript Version:**  master branch

**Repro**

1. Create a new JavaScript->Windows->Universal->Blank App project
2. Add directories and empty files as following:

    ```
    (App name)
    |>sources
    |    |>cats
    |    |    |>elephants
    |    |    | foo.ts
    |    | bar.ts

    sources/cats/elephants/foo.ts
    sources/cats/bar.ts
    ```

3. Write codes as following:

    ```ts
    // In sources/cats/elephants/foo.ts:
    class Foo extends Bar {
    }

    // In sources/cats/bar.ts:
    class Bar {
    }
    ```

4. Open project properties and set "Combine JavaScript output into file" to "js/app.js"
5. Unload project
6. Reload project

**Expected behavior:**

Compiler should automatically make a proper order for the classes

**Actual behavior:** 

```ts
class Foo extends Bar {
//                ~~~
//                A class must be declared after its base class.
}
```

**Workaround:**

Rename "foo.ts" to "a.ts".

**Comment by RyanCavanaugh** [comment]
The compiler doesn't figure out what the "right" order of files is based on class dependencies or anything else. The usual methods are available: have a `_reference.ts`, use `/// <reference` directives, or use a module loader (if applicable)

**Comment by SaschaNaz** [comment]
Thanks! I would be happier if the error message told me the tip.

**Comment by whiterockerart** [comment]
I have the same problem, but I've inserted a /// <reference path="../file.ts" /> and during build I ge the TS2690 error: A class must be declared after its base class.

But VS itself doesn't say anything.
