### ISSUE TITLE
Intellisense for es6 class members doesn't work?

### ISSUE THREAD

**Issue by waderyan** [Microsoft/TypeScript#10373]
_From @DenysYefimenko on August 16, 2016 10:47_

- VSCode Version: 1.4
- OS Version: Windows 10

Steps to Reproduce:

Intellisense for class members defined in es6 class constructor don't appear in class functions. 
It works if I use prototype syntax.

![prototype_intellisense](https://cloud.githubusercontent.com/assets/14803329/17696537/aad9a69a-63b7-11e6-9cfc-e2daeff75ba4.png)
![es6class_intellisense](https://cloud.githubusercontent.com/assets/14803329/17696544/b3ace6c4-63b7-11e6-940f-5e05556eee61.png)

_Copied from original issue: Microsoft/vscode#10578_

**Comment by waderyan** [comment]
Good find. Moving to TypeScript as this is a Salsa issue.

**Comment by sandersn** [comment]
Fixed yesterday in #10358. Should be available in `typescript@next` if you want to try VSCode in dev-mode.
