### ISSUE TITLE
Bizarre type guard issue in 2.0

### ISSUE THREAD

**Issue by jeffreymorlan** [Microsoft/TypeScript#10378]
```ts
var a: boolean | number | string;
if (typeof a !== 'boolean') {
	// a is narrowed to "number | string"
	for (var i = 0; i < 1; i++) {
		for (var j = 0; j < 1; j++) {}
		if (typeof a === 'string') {
			// a is narrowed to "string'
			for (var j = 0; j < 1; j++) {
				a.length; // Error: Property 'length' does not exist on type 'never'.
			}
		}
	}
}
```

Removing any of the three loops, or the outer type guard, makes the problem disappear.

**Comment by yortus** [comment]
I can repro this. Strange indeed. :confused: 

Interestingly, in VSCode if you hover over the `a` on the error line, intellisense still shows `var a: string`. And if you hover over `length` on the error line, intellisense shows both the error message and `(property) String.length: number`.

**Comment by yortus** [comment]
Slightly simpler repro with same behaviour... Commenting out any loop or type guard makes the error go away:

```ts
var a: string | number;
if (typeof a === 'string') {
    while (1) {
        while (1) {}
        if (typeof a === 'string') {
            while (1) {
                a.length; // Error: Property 'length' does not exist on type 'never'.
            }
        }
    }
}
```
