### ISSUE TITLE
Visual Studio 2015 does not compile TS

### ISSUE THREAD

**Issue by pankleks** [Microsoft/TypeScript#10371]
**TypeScript Version:**  2.0.0 beta

I have multiple TS files in single directory with tsconfig.json.
In config I'm using new feature of TS 2.0, "include", as below:

```
  "include": [
    "../../wwwroot/Library.d.ts",
    "*.ts"
  ]
```

VS 2015 does not compile TS, saying it can't find any declarations from `Library.d.ts`.
However if I run `tsc.exe` from command line in this directory, all compiles fine.
Also if I copy `Library.d.ts` into same directory it works.

What's even more strange - I have 3 computers with same configuration, and 2 of them have this issue, one is running fine in VS2015.

So wired.

**Comment by mhegazy** [comment]
What version of VS do you have, what version of TS plugin in VS, and what version of TS do you have in the command line compiler?

support for "include" in tsconfig is a TS 2.0 feature, and you need to have VS plugin for TS 2.0 beta installed for VS to understand it.

**Comment by pankleks** [comment]
VS 2015 Enterprise (update 3)
TypeScript 2.0.0.0 

To make sure TS 2.0 is used, I checked other features (as readonly etc.) and it works.

![image](https://cloud.githubusercontent.com/assets/14176066/17775068/eac5275c-6556-11e6-9a85-063855102b06.png)

**Comment by mhegazy** [comment]
> VS 2015 does not compile TS, saying it can't find any declarations from Library.d.ts.

Do you mean hitting F5 in VS? or is this CompileOnSave? can you share the build output if it is the earlier?

**Comment by pankleks** [comment]
I'm using CompileOnSave - build does not show any errors, but this is what I get:
![image](https://cloud.githubusercontent.com/assets/14176066/17787035/c7053b96-6587-11e6-9869-3a6188e54ab0.png)

`Component` is defined in Library.d.ts file I use using "include".

**Comment by pankleks** [comment]
I've created simple solution where issue is reproduced.

[TS2Test.zip](https://github.com/Microsoft/TypeScript/files/425712/TS2Test.zip)

Please check Folder2/File2.ts (does not see stuff included). Works with tsc from cmd line.

**Comment by mhegazy** [comment]
I am not sure I understand what is going on here. The file `TS2Test/wwwroot/Test.d.ts` does not seem to exist until I build. see the screenshot below:

![image](https://cloud.githubusercontent.com/assets/8000722/17789199/f06f5634-6545-11e6-9abb-1e3bdbbe789b.png)

once I build, I see the file, and it gets picked up by the editor and the error goes away.

**Comment by pankleks** [comment]
Ok, so the first build produces Test.d.ts and Test.js from Folder1
Obviously first build will fail on Folder2.
However second build should work also for Folder2 as files exists.

BTW is there way for VS to setup dependencies between tsconfig projects?

**Comment by mhegazy** [comment]
> However second build should work also for Folder2 as files exists.

that is what i see locally.

> BTW is there way for VS to setup dependencies between tsconfig projects?

no, this is tracked by https://github.com/Microsoft/TypeScript/issues/3469

**Comment by sateeshmunagala** [comment]
So Does VS 2015 update 1 works with TS 2.0 ?
OR which version of TS is compatible with VS 2015 update 1. I don't have option to upgrade to update 3 or later at my office.?
