### ISSUE TITLE
Convert shebangs to #!/usr/bin/env node

### ISSUE THREAD

**Issue by mcandre** [Microsoft/TypeScript#10382]
When `tsc` compiles a `.ts` file into a `.js` file, replace a shebang line like `#!/usr/bin/env typescript` to a more appropriate one for `.js` files: `#!/usr/bin/env node`.

**Comment by kitsonk** [comment]
That is more appropriate for you, but not for everyone.

**Comment by RyanCavanaugh** [comment]
Original discussion / implementation happened at #2749. We are not in the business of guessing what you meant when you wrote executing shell script in a file. It sounds like what you actually want is `ts-node`, which already exists.
