### ISSUE TITLE
Are there any plans for a TypeScript Programmatic Visual Web Components Library (and RAD)?

### ISSUE THREAD

**Issue by RobertoMalatesta** [Microsoft/TypeScript#10388]
Are there any plans by Microsoft to spin off some side project concerning the definition of **programmatic** **visual** **components** strictly based on Typescript?

The reason of this question is that, even if Web Libraries and Frameworks abound, they basically either have severe flaws or steep learning curves and unnecessary complex systems that have to cope with either supporting HTML-CSS definition of objects or support of non-TS languages.

And what about a **RAD**?

It is funny (and really counterproductive) that today’s development of visual interfaces lacks tools like **Delphi** or **Visual Basic** that - _in the '90s(!)_ - were orders of magnitude more productive than the bunch of campy tools that badly glue XML/HTML/CSS/JS now. 

Having **Microsoft** behind a visual components/polyfills open tool could make the difference and set a new standard for (at least enterprise) development.

Just like TypeScript fixed inner-page and server Javascript development now it’s time to fix the front-end.

Thank you for your time and your wonderful project.

– R

**Comment by kitsonk** [comment]
Angular 2 and Dojo 2 are both being built on TypeScript and other major frameworks are considering migrating too.

The design goals for [TypeScript](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals) really preclude it from being anything more than a language.

This issue forum is for suspected bugs and enhancement to TypeScript and general discussion should take place in other forums.

**Comment by RobertoMalatesta** [comment]
Hi @kitsonk and thank you for your prompt involvment.

> Angular 2 and Dojo 2 are both being built on TypeScript and other major frameworks are considering migrating too.

You mention two libraries:
- one is still vaporware 
- the other is a perfect example those campy non-programmatic tools I was talking to


> The design goals for TypeScript really preclude it from being anything more than a language.

I don'think so, besides that, I clearly asked if **Microsoft** is _considering a side project_
It is my opinion that only projects **strongly and** **clearly** **backed by large components can emerge as enterprise solutions.** 
The last 10+ years web history is littered with undead corpses of nice frameworks that had no userbase traction (name your favourites here) or were abandoned by the company that created them (Tibco GI,YUI) 


_Anyway, I think that the question could be of interest for more persons.
**To admins**: Feel free to mark this ish as "Inappropriate" and close it, if you so wish._

My bests.

--R

Oh, btw, Kitson,I see that you're involved in Dojo2 and I wish you best luck, since I used Dojo in several projects and it was one of the best frameworks by the time. Documentation apart.

**Comment by Karabur** [comment]
That question is not related to Typescript itself, if you wish to ask if Microsoft want to do something, based on Typescript or whatever, may be you should ask from Microsoft, but not from Typescript (or whatever) project? 
I understand it is related to Typescript, but does not look like appropriate place to keep. There is already 1200+ issues opened, high chance that will just sit here increasing the noise.

**Comment by RobertoMalatesta** [comment]
Great, @Karabur, 
do you know where?

BTW: I still think that it could loosely belong here, since it's an obvious enhancement/extension.

--R

**Comment by kitsonk** [comment]
> Oh, btw, Kitson,I see that you're involved in Dojo2

Not only involved in said *vaporware* but the project lead.

**Comment by RobertoMalatesta** [comment]
@kitsonk I knew and since this OT I will bug you there.

**Comment by mhegazy** [comment]
TypeScript is JavaScript; the JavaScript echo system provides a whole set of tools and frameworks that support UI development. TypeScript should work with all these frameworks. Building and end-to-end framework or development tool chain is one of the non-goals of the TypeScript projects (see https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals#non-goals).

So to answer your question, we have no intentions to build a UI framework or a templating language based on TypeScript.

**Comment by RobertoMalatesta** [comment]
> So to answer your question, we have no intentions to build a UI framework or a templating language based on TypeScript.

Thanks for the clear and definite answer, @mhegazy .

I can hear sighs of relief from all companies implementing current UI frameworks.

--R
