### ISSUE TITLE
tsc: Accept multiple .ts source files at once

### ISSUE THREAD

**Issue by mcandre** [Microsoft/TypeScript#10389]
For larger projects, please add the ability for `tsc` to compile multiple `.ts` source files at once, like other compilers.

**Comment by kitsonk** [comment]
`tsc file1.ts file2.ts`

**Comment by RyanCavanaugh** [comment]
Out of curiosity, *what did you try*? It'd be good to improve our commandline help or something if there's something you tried and it didn't work.
