### ISSUE TITLE
TSServer: config file diagnostics are missing start / end property

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#10384]
**TypeScript Version:**  2.0
**Code**
tsconfig.json

``` json
{
    "compilerOptions": {
        "module": "commonjs",
        "abdb": 10
    }
}
```
- open a file that triggers validating the tsconfig.json file
- the event returned from the tsserver is missing start and end properties on the diagnostic literals. You get:

```
Event received: configFileDiag (0).
Data: {
    "triggerFile": "p:/mseng/VSCode/Playgrounds/ts-2.0/test.ts",
    "configFile": "p:/mseng/VSCode/Playgrounds/ts-2.0/tsconfig.json",
    "diagnostics": [
        {
            "text": "Unknown compiler option 'abdb'."
        }
    ]
}
```

**Comment by RyanCavanaugh** [comment]
We use a regular JSON parser to read this file so we don't actually know where the property came from. Maybe someone can find / write a span-preserving JSON parser (I've looked but haven't found one) so we can report better errors.

**Comment by dbaeumer** [comment]
@RyanCavanaugh:  makes the feature not very useful when used inside editors since we would need to fold all errors onto the file without being able to provide error indications.

In addition it violates the tsserver protocol spec which states that start/end are mandatory on a Diagnostic object. 

Could this be upgraded to a bug and consider for 2.0. Being able to show errors on tsconfig files is a long wanted feature.

We maintain a json parser here: https://github.com/Microsoft/node-jsonc-parser. Even supports comments.

**Comment by dbaeumer** [comment]
@mhegazy @DanielRosenwasser FYI.

**Comment by RyanCavanaugh** [comment]
Related work happening in #10418

**Comment by mjbvz** [comment]
@@mhegazy We've enabled config file diagnostics in VSCode but had to resort to a pretty ugly workaround to try to map the error to a specific location. Having proper location data on the config diagnostic responses would fix a number of edge cases and errors that I'm currently seeing

**Comment by sheetalkamat** [comment]
This is fixed right?
```
{"seq":0,"type":"event","event":"configFileDiag","body":{"triggerFile":"c:/temp/test2/lib/file2.ts","configFile":"c:/temp/test2/lib/tsconfig.json","diagnostics":[{"start":{"line":10,"offset":9},"end":{"line":10,"offset":14},"text":"Unknown compiler option 'abv'.","code":5023,"category":"error","fileName":"c:/temp/test2/lib/tsconfig.json"}]}}
```

**Comment by mjbvz** [comment]
Yes, I confirmed that this is working properly now. I'll make sure we consume these ranges properly on the VS Code side

Thanks!
