### ISSUE TITLE
ASI indention issue

### ISSUE THREAD

**Issue by unional** [Microsoft/TypeScript#10392]
TS: 2.0.0

**Code**

```ts
function foo() {
  const x = 1

  ;(x as any).fun = 2
}  
```

Then format the code in VSCode

**Expected behavior:**
Indention is correct

**Actual behavior:** 
```ts
function foo() {
  const x = 1

    ; (x as any).fun = 2
}
```

**Comment by mhegazy** [comment]
that is not really an ASI issue. an ASI is only inserted if the production is not valid one, or the next token is `}` (see http://www.ecma-international.org/ecma-262/6.0/#sec-rules-of-automatic-semicolon-insertion). In this case, the semicolon belongs to the statement `const x = 1`. since it is part of the statement and on a new line, it is indented, similar to 
```ts
function foo() {
  const x = -
      1
}
```
So the indentation looks right to me.

**Comment by unional** [comment]
Um....I can understand your reasoning.

But how to support coding style relying on ASI?
In this case we do need the "extra" `;` to avoid error on `(x as any)` part.

**Comment by mhegazy** [comment]
why not put the semicolon on the previous line?

**Comment by unional** [comment]
It's about consistent coding style.
If I put the semicolon on the previous line, `tslint` will complain:

`[tslint] Unnecessary semicolon`

https://github.com/blakeembrey/tslint-config-standard
http://standardjs.com/

**Comment by mhegazy** [comment]
this one looks necessary to me :)

**Comment by unional** [comment]
lol, definitely agree with you on this one. 😆 

For "standardjs" style, the convention is to do add semicolon before `[`, `(`, and backticks

**Comment by RyanCavanaugh** [comment]
Personal opinion: anyone remotely sane would use https://github.com/Flet/semistandard instead

**Comment by unional** [comment]
I'm also new to "standardjs" and is trying it out to see how it works.

Omitting semicolon does seem to have a positive impact on my coding performance.
I don't have to move the cursor back and forth just to add the semicolon.

**Comment by kitsonk** [comment]
> Omitting semicolon does seem to have a positive impact on my coding performance.

Except when you spend hours debating the need for omitting semicolons except for the few (several) cases where they are needed/required. 😄

**Comment by unional** [comment]
> Except when you spend hours debating the need for omitting semicolons except for the few (several) cases where they are needed/required

😆  time lost is lost. 😜

**Comment by rightaway** [comment]
Why was this issue closed? It won't be fixed? It's been requested in various issues so it's definitely something useful.
