### ISSUE TITLE
tsc: Handle filename globs

### ISSUE THREAD

**Issue by mcandre** [Microsoft/TypeScript#10390]
Please have `tsc` process globs, such as by using [glob](https://www.npmjs.com/package/glob), so that larger projects can easily specify groups of files to the compiler to work on all at once.

This will be less of a problem for native bash Windows users, but there are plenty of situations where bash and cygwin-likes are not an option.

**Comment by kitsonk** [comment]
This is handled in the [`tsconfig.json`](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html) and was delivered in #5980 and is part of TypeScript 2.0 (which is in beta).

You should really read documentation before opening so many (duplicate and unnecessary) issues.

**Comment by iki** [comment]
The request is for `tsc` command line arguments. Configuration file ` tsconfig.json` is not sufficient solution for different use cases.

For example, we want to only compile tests in  `pretest`: `tsc test/*.spec.ts --module commonjs --lib es2015,dom`.

Please reopen (to avoid unnecessarily duplicate issues).
