### ISSUE TITLE
Static class properties defined with square brackets have extra brackets in quick info

### ISSUE THREAD

**Issue by weswigham** [microsoft/TypeScript#10395]
**TypeScript Version:**  nightly (2.0.0-dev.201xxxxx)

**Expected behavior:**
Only one set of brackets is shown.

**Actual behavior:** 
![image](https://cloud.githubusercontent.com/assets/2932786/17751386/be8aa59e-647b-11e6-8515-fd0efc5998b4.png)

**Comment by Andarist** [comment]
This one has been fixed a long time ago, it works fine in all TS versions that are available in the TS playground ([current TS playground](https://www.typescriptlang.org/play?ts=5.2.0-dev.20230806#code/KYDwDg9gTgLgBAQwEYGcZQQY3pgNglFOAYQgBNgBzYAOwAUoIA3ASwqjgG8AoOPuMFBZMEMYHDSiWmOFGAIyEGrgCecANoAiUGJooWSgLQBrFjTKaAugC44mzOSq1NcALx2HFajU3cAvkA)), cc @jakebailey

**Comment by jakebailey** [comment]
Yes, this was fixed in https://github.com/microsoft/TypeScript/commit/64fd857b0dcca50b2babe4b5404e6eb496e5dbcb.
