### ISSUE TITLE
[error TS2300: Duplicate identifier] Global references 

### ISSUE THREAD

**Issue by br1anchen** [microsoft/TypeScript#1039]
Hi,

I just updated the typescript compiler from 1.0.1.0 to 1.1.0.1.

Then when I using the Webstorm Typescript Transpiling, it keeps reporting TS2300: Duplicate identifier.
I investigate a bit, it seems like the references is the problem.

In our current project, we include all the .ts files and external library .d.ts files in one references.d.ts file and include a single references.d.ts file for each .ts file we coded.
This reference mechanism works just fine on tsc 1.0.1.0

But on 1.1.0.1, it seems like it can not do self reference any more. Then I try to make specific reference for each .ts file. However it still get some TS2300: Duplicate identifier in some classes when the dependencies depend on another same dependency. It seems like it will reference the same dependency twice to cause Duplicate identifier error.

eg:

```
A.ts:
/// <reference path="D.ts" />

B.ts:
/// <reference path="D.ts" />

C.ts:
/// <reference path="A.ts" />
/// <reference path="B.ts" />
```

Because I am using AngularJS framework, so it is quite common that A and B are services to inject D service, C as controller to inject A and B services.

In this scenario, typescript compiler report TS2300: Duplicate identifier 'D' when it compile C.ts

PS: I know this references issue will not occurs in VS since it has some 'magic' implicant reference mechanism to reference all the .ts/ .d.ts files. I hope it is not the Webstorm issue, because it seems like compile issue more or less.

Also, it will be great if there is some standard Typescript coding style to do the proper dependencies reference when people are using Webstorm or other IDE than VS. Maybe some auto fixing dependencies reference as plugin would be better.

**Comment by davidleureka** [comment]
So to clarify, the is the recommended approach to have one giant `tsd.json` file and corresponding `typings` folder for you entire project? If I try to break it up and have multiple folders each with their own `tsd.json` and `typings` then I still run into this issue for libraries that are used in multiple places (such as bluebird or lodash).

**Comment by EBMike** [comment]
Yeah this is far from fixed... it shouldnt throw this error for reference paths

**Comment by mhegazy** [comment]
@davidleureka and @EBMike this issue has been closed over a year now. I am finding hard to understand the context between your comments and the original issue. please file a new ticket and include relevant details.

**Comment by davidleureka** [comment]
[done](https://github.com/Microsoft/TypeScript/issues/6475)
