### ISSUE TITLE
TypeScript - ability to go to type definition

### ISSUE THREAD

**Issue by waderyan** [Microsoft/TypeScript#10394]
_From @wallverb on August 12, 2016 22:36_

- VSCode Version: Code - Insiders 1.5.0-insider (e9c80f036645caae7759b3954fc72dbe6c644edf, 2016-08-12T06:04:09.471Z)
- OS Version: Darwin x64 15.6.0

Steps to Reproduce:

```ts
interface Test {
}

const test:Test = {}
const test2 = test 
```

If your cursor is inside `Test` of `const test:Test` you can click `F12` to go to that type definition - but sometimes you do not have type declared explicitly (infered type) - eg. `const test2` then it's impossible to go easily to type defintion. Maybe combination of some key + click (or extra entry in popup) `Go to type definition`

_Copied from original issue: Microsoft/vscode#10489_

**Comment by waderyan** [comment]
@dbaeumer this looks like a valid feature request? Is this something provided by VS Code or by Salsa?

**Comment by waderyan** [comment]
_From @dbaeumer on August 17, 2016 15:25_

Nice idea.

@waderyan in these cases I do the following: I create a issue against TS and link to it from a VS Code issue (this one). I keep this one as a feature request on our end.

**Comment by waderyan** [comment]
_From @dbaeumer on August 17, 2016 15:26_

May be we need a depends-on label to mark these.

**Comment by mhegazy** [comment]
TypeScript has a goto type command available on the tsserver, see https://github.com/Microsoft/TypeScript/blob/master/src/server/protocol.d.ts#L188.

VSCode needs to expose a new shortcut that calls into this command.
