### ISSUE TITLE
Strange error: Property 'message' implicitly has type 'any', because its 'set' accessor lacks a type annotation

### ISSUE THREAD

**Issue by MaceWindu** [Microsoft/TypeScript#10408]
**TypeScript Version:**  release-2.0_mergeMaster branch from 15-8-2016 

**Code**

```ts
abstract class Parent
{
    public abstract get message();
}

class Child extends Parent {
    public get message() {
        return "";
    }
}
```
**Build options:**
 -noEmitOnError -noImplicitAny -target es5 -lib es5,dom bug.ts
two first flags are required, removing any of them will remove error

**Expected behavior:**
Compile without error or provide clear error message.

**Actual behavior:** 
error TS7016: Property 'message' implicitly has type 'any', because its 'set' accessor lacks a type annotation.
Two problems with this message:
- it has no file name and line number
- message property has no set accessor at all

**Comment by RyanCavanaugh** [comment]
Just to say it explictly, the intended error span is here:
``ts
abstract class Parent
{
    public abstract get message(); // <-- implict any
}
```
