### ISSUE TITLE
Code example in section 1.4 of the spec is wrong/misleading

### ISSUE THREAD

**Issue by nponiros** [microsoft/TypeScript#10406]
The code example has a comment saying that extra fields are Ok but if you compile that particular code snippet the compiler gives an error for the extra fields as the field `color` does not exist in type `Point`. I tested with the online playground and versions 1.8.10 and 2.0.0 of the compiler. Section 3.11.5 explains what is happening here and why it is an error.

There are a number of possible fixes for this and if someone tells me what the correct/wanted fix is, I would gladly open a pull request.

Here is the code of the example with a comment from me marking the wrong line:

``` js
interface Point {  
    x: number;  
    y: number;  
}

function getX(p: Point) {  
    return p.x;  
}

class CPoint {  
    x: number;  
    y: number;  
    constructor(x: number,  y: number) {  
        this.x = x;  
        this.y = y;  
    }  
}

getX(new CPoint(0, 0));  // Ok, fields match

// Personal comment: No, this is not OK
getX({ x: 0, y: 0, color: "red" });  // Extra fields Ok

getX({ x: 0 });  // Error: supplied parameter does not match
```

Regards

Nikolas

**Comment by RyanCavanaugh** [comment]
The spec is now an "archived" artifact and we won't be tracking defects against it anymore.
