### ISSUE TITLE
Simple String union can be compared against the wrong string values

### ISSUE THREAD

**Issue by AlexGalays** [Microsoft/TypeScript#10409]
**TypeScript Version:**  2.0.0

**Code**

```ts
type Role = 'admin' | 'user'

const role: Role = 'admin'

if (role === '&!?# completelyrandom') {
   console.log(role)
}

```

**Expected behavior:**
I would expect simple if/ternary statements to be the idiomatic way to "type guard" string enums, but it doesn't do anything at compile time.

**Actual behavior:** 
No error

**Comment by ahejlsberg** [comment]
This has the expected behavior in the current nightly build.

**Comment by AlexGalays** [comment]
Ok thanks, will update my beta version.

**Comment by DanielRosenwasser** [comment]
Duplicate of #7447.

**Comment by DanielRosenwasser** [comment]
Duplicate of #6149.
