### ISSUE TITLE
Private class members show up in d.ts files.

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#10414]
**TypeScript Version:**  1.8.x
**Code**

```ts
export class CancellationTokenSource {

	private _token: CancellationToken;

	get token(): CancellationToken {
            ....
	}
}
```

The generated d.ts file looks like this:

````ts
export declare class CancellationTokenSource {
    private _token;
    token: CancellationToken;
}
```

The d.ts file shouldn't list private _token;

**Comment by kitsonk** [comment]
Yes it should, because if the class is used an extension the private member is still there, since `private` is really just a run-time convention.  How would someone consuming the typings know that they had a property name conflict that would lead to undesirable behaviour?

**Comment by DanielRosenwasser** [comment]
See #1867 as well.

**Comment by dbaeumer** [comment]
Closing since the explanation makes sense to me.
