### ISSUE TITLE
this reference in Object

### ISSUE THREAD

**Issue by senyaarseniy** [Microsoft/TypeScript#10410]
**TypeScript Version:**  1.8.0 / nightly (2.0.0-dev.201xxxxx)

**Code**

```ts
interface IFoo {
  get(val: number): number;
  getAll(val: string): number;
}
function foo(): IFoo {

  return {
    get(val: number): number {
      return val + 1;
    },
    getAll(val: string): number {
      return this.get(val)*10;
    }
  };
}

```

**Expected behavior:**
Compiler show an error that val string isn't a number
**Actual behavior:** 
No error.

**Trick to get expected behavior:**
```ts
interface IFoo {
  get(val: number): number;
  getAll(val: string): number;
}
function foo(): IFoo {

  var a: IFoo =  {
    get(val: number): number {
      return val + 1;
    },
    getAll(val: string): number {
      return this.get(val)*10;
    }
  };

  return a;
}

```

**Comment by nippur72** [comment]
it seems correct to me as `this.get()` does not refer to the `get()` defined in the object, but to a whatever `get` function that appears in `this` context when the function will be called.

Try writing this way:
```ts
interface IFoo {
  get(val: number): number;
  getAll(val: string): number;
}
function foo(): IFoo {
  const get = function(val: number): number {
      return val + 1;
  };
  const getAll = function(val: string): number {
      return get(val)*10;
  } 
  return {
    get, getAll
  };  
}
```

And btw, your "Trick to get expected behavior" does not works neither.

**Comment by danielearwicker** [comment]
See https://github.com/Microsoft/TypeScript/pull/6739 for work in this area, though I don't think all of it is going into 2.0.

**Comment by RyanCavanaugh** [comment]
@nippur72 's comment is correct. You can use an arrow function to actually preserve `this`, or an explicit `this` type annotation (in TS 2.0) if somehow people are invoking `a` with your class instance as `this` (how??)

**Comment by senyaarseniy** [comment]
sorry Trick to get expected behavior should be:

```ts
interface IFoo {
  get(val: number): number;
  getAll(val: string): number;
}
function foo(): IFoo {

  var a: IFoo =  {
    get(val: number): number {
      return val + 1;
    },
    getAll(val: string): number {
      return a.get(val)*10;
    }
  };

  return a;
}
```
:)
