### ISSUE TITLE
"HTML Application with TypeScript" in VS2013 doesn't work

### ISSUE THREAD

**Issue by pps83** [Microsoft/TypeScript#10428]
When I create new "HTML Application with TypeScript" project in VS2013 it doesn't work. First of all, obviously it has to work, secodn issue is that the error message is totally useless.
Here's the console output that I get:

```
1>  C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.8\tsc.exe  --sourcemap --target ES5 --locale en-US COMPUTE_PATHS_ONLY --listEmittedFiles "C:\TypeScriptHTMLApp2\TypeScriptHTMLApp2\app.ts"
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v12.0\TypeScript\Microsoft.TypeScript.targets(95,5): error MSB6006: "tsc.exe" exited with code 1.
1>
1>Build FAILED.
1>
```

Only if I try to execute manually that command I see that all the command line parameters there aren't valid and trigger errors.

That same template somewhat works in VS2015: if I put a breakpoint in code it works only if I use Internet Explorer as debug target, with all other browsers (including Edge) breakpoints don't get hit.

**Comment by RyanCavanaugh** [comment]
@paulvanbrenk can you follow up?

**Comment by paulvanbrenk** [comment]
@pps83 
Do you have both 2013 and 2015 installed? Did you install the 2.0 beta for Visual Studio 2015? Did you create the project in VS 2013? 

Can you enable the `diagnostic` logs for MSBuild in Tools -> Options -> Projects and Solutions -> Build and Run, and share the output?

**Comment by pps83** [comment]
I have 2013 and 2015 installed. If I create it in vs2015 then it's ok. If I create it in vs2013 then I get that error. Note that in 2015 in Class View there is nothing shows, also it shows there "C#"

Here's diagnostic msbuild in vs2013: http://pastebin.com/FtGBZFf4

**Comment by paulvanbrenk** [comment]
Can you check if the following file is marked as readonly:

`C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v12.0\TypeScript\Microsoft.TypeScript.targets`

And can you replace that file with the same file from here: (after you make a backup)

`"C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\`

**Comment by pps83** [comment]
`v12.0\TypeScript\Microsoft.TypeScript.targets` isn't readonly. When I replaced with `v14.0\TypeScript\Microsoft.TypeScript.targets` there is no more build errors. However, debugging doesn't work: in 2015 it starts iexplore and debugging works, in 2013 it start my default browser (firefox) and debugging doesn't work.

**Comment by paulvanbrenk** [comment]
Great, that the build works. 

Debugging with 'F5' only works with Intern Explorer as far as I know, this is something the ASP.NET team is working on to improve.

**Comment by pps83** [comment]
I know that it work only with IE, so, it should start IE in vs2013 also. I don't know why it starts firefox.

**Comment by paulvanbrenk** [comment]
The only thing I can think of is that this drop down is set to Firefox?

![image](https://cloud.githubusercontent.com/assets/5273975/17914224/232cf050-6955-11e6-93b3-5ff9a097e063.png)

**Comment by pps83** [comment]
Yes, sorry, that was it. now it works.

**Comment by netaji583** [comment]
Oh. gosh. Had been trying fro this fix since hours...

Can you check if the following file is marked as readonly:

C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v12.0\TypeScript\Microsoft.TypeScript.targets

And can you replace that file with the same file from here: (after you make a backup)

"C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\

This worked for me...Thanks a lot @paulvanbrenk
