### ISSUE TITLE
Loosen restriction on requiring return expressions when a throw is used instead

### ISSUE THREAD

**Issue by danquirk** [Microsoft/TypeScript#1042]
Per #947, we currently require a `return` expression in a non-void returning function unless the first and only expression is a `throw` statement. This is basically an exemption to allow for `throw new Exception('Not Yet Implemented')`. It seems reasonable to allow throwing further along in a block if we're willing to try to track control flow, at which point we could likely also check for appropriate `return` expressions from all branches.

**Comment by RyanCavanaugh** [comment]
We should treat `throw` as equivalent to `return` for the purposes of this check

**Comment by Ptival** [comment]
Any update on this? I often use `throw ...;` and `debugger;` to close branches that should not happen and have no meaningful return values.

**Comment by RyanCavanaugh** [comment]
The new control analysis work should make this issue obsolete. Have you tried `typescript@next` ?

**Comment by Ptival** [comment]
No, I'm stuck on the npmjs version. (1.8.10?)

Good to know then! :-)

**Comment by NaridaL** [comment]
@RyanCavanaugh I think this can be closed?

**Comment by RyanCavanaugh** [comment]
Agree, thanks!
