### ISSUE TITLE
Possibility to support vuejs

### ISSUE THREAD

**Issue by kennywangjin** [microsoft/TypeScript#10427]
Is it possible to provide official support for vuejs or make official cooperations with vuejs author, to eaze integration of these too great tools?
You have provided office TSX for reactjs. Please consider to support vuejs (.vue) too. This world needs more than just reactjs!

**Comment by DanielRosenwasser** [comment]
Hey @kennywangjin. You're certainly not the first person to bring this up. I've gotten this asked quite a few times in our Gitter room, and [it's currently also the 6th most-commented issue](https://github.com/vuejs/vue/issues/478) on Vue itself.

I've spoken with Evan (@yyx990803) before. Supporting `.vue` files would be something that ideally a language service extension would take on (see #10160 for details).

For the record, I've heard good things about @itsFrank's [vue-typescript](https://github.com/itsFrank/vue-typescript). Let me know if that makes it any easier to use.

**Comment by mythz** [comment]
Not sure if this is a TypeScript, TS + webpack or VS.NET designer issue but there's currently poor support for `.vue` files in VS.NET. I'm using a webpack-powered SPA template so the TypeScript errors are just designer errors but they dilute real TypeScript errors where TypeScript doesn't know how to import .vue modules:

![image](https://cloud.githubusercontent.com/assets/89361/26063994/a4630c44-395d-11e7-94db-977bca1bab21.png)

There also isn't good support for `.vue` files as well:

![image](https://cloud.githubusercontent.com/assets/89361/26064241/5ec61504-395e-11e7-8d62-ad78df8673ec.png)

VS Code with vetur is much nicer:

![image](https://cloud.githubusercontent.com/assets/89361/26064284/7d3980b6-395e-11e7-843f-c855c63c268c.png)

Just curious if there's any tweaks I can do to make the experience nicer in VS.NET or if VS.NET has a roadmap to support Vue + webpack and where I can look at (or submit this issue to) to follow progress?

**Comment by MeirionHughes** [comment]
@DanielRosenwasser are you aware of an feature request (in this repo) to allow transforming _any_ file to typescript AST, and by extension configuring tsc to support that via plugins?

**Comment by dummdidumm** [comment]
#38736 would enable this for arbitrary files (including Vue)

**Comment by RyanCavanaugh** [comment]
vuejs is supported through their LS plugins now
