### ISSUE TITLE
Strange JSX usage compilation error 

### ISSUE THREAD

**Issue by Strate** [Microsoft/TypeScript#10430]
**TypeScript Version:**  2.1.0-dev.20160819

**Code**

Unfortunatelly, I can't extract self-containment example

**Expected behavior:**
No error

**Actual behavior:** 
Bunch of errors on each JSX usage:
```
src/lib/components/CTagSelect/CTagSelect.tsx(193,24): error TS2324: Property 'constructor' is missing in type 'IntrinsicAttributes & IntrinsicClassAttributes<CButton> & CButtonProps & { children?: ReactNode; }'.
src/lib/components/CTagSelect/CTagSelect.tsx(193,24): error TS2324: Property 'hasOwnProperty' is missing in type 'IntrinsicAttributes & IntrinsicClassAttributes<CButton> & CButtonProps & { children?: ReactNode; }'.
src/lib/components/CTagSelect/CTagSelect.tsx(193,24): error TS2324: Property 'isPrototypeOf' is missing in type 'IntrinsicAttributes & IntrinsicClassAttributes<CButton> & CButtonProps & { children?: ReactNode; }'.
src/lib/components/CTagSelect/CTagSelect.tsx(193,24): error TS2324: Property 'propertyIsEnumerable' is missing in type 'IntrinsicAttributes & IntrinsicClassAttributes<CButton> & CButtonProps & { children?: ReactNode; }'.
src/lib/components/CTagSelect/CTagSelect.tsx(193,24): error TS2324: Property 'toLocaleString' is missing in type 'IntrinsicAttributes & IntrinsicClassAttributes<CButton> & CButtonProps & { children?: ReactNode; }'.
src/lib/components/CTagSelect/CTagSelect.tsx(193,24): error TS2324: Property 'toString' is missing in type 'IntrinsicAttributes & IntrinsicClassAttributes<CButton> & CButtonProps & { children?: ReactNode; }'.
src/lib/components/CTagSelect/CTagSelect.tsx(193,24): error TS2324: Property 'valueOf' is missing in type 'IntrinsicAttributes & IntrinsicClassAttributes<CButton> & CButtonProps & { children?: ReactNode; }'.
```
and it happens with almost every component in my project.
Usage of that components does not have spread operator.
I can't extract something special with that components or usage.
It happens only with 2.1 nightly

**Comment by RyanCavanaugh** [comment]
It really sounds like someone wrote `Object` in a place where they should have written `{}`. Can you search your codebase for that type and see if that helps you narrow it down?

**Comment by Strate** [comment]
@RyanCavanaugh 
I am really can't find source of issue and can not reproduce issue on clean project. It happens with only one component, but not with all usages. All failed usages looks likes that:
```ts
import {CButton} from "src/lib/components"

class Usage extends React.Component<void, void> {
  render() {
    return <CButton type="type" /* and other attributes with that style, without spread operator */ />
  }
}
```
Non-failed usages looks like exactly the same :)
Looks like TS treats CButton's properties as an `Object`, which passes properties from `Object.prototype` to `CButton` props.
`Object` as a type is not used neither in `CButton` declaration, neither in usage.

Is there some magical logs, which I could enable to catch the issue? :)

**Comment by RyanCavanaugh** [comment]
What is the declaration of CButton?

**Comment by kruczy** [comment]
have the same problem when trying `2.1.0-dev.20160831`

for me it is only `hasOwnProperty` missing:
`error TS2324: Property 'hasOwnProperty' is missing in type 'CheckboxProps & ComponentProps'.`

this is for all usages of `Checkbox` component and it does not happen for any other component

there is nothing special in the definition of `Checkbox` it extends the base class the same as everything else and defines an interface for its props

I removed all props from the definition of both `CheckboxProps` and `ComponentProps` and it still had the same problem + some bonus ones for not defined props

If I explicitly define `props: CheckboxProps` directly in `Checkbox` class it is fine

though if I define the interface to be the same it is coming from generic parent: `props: CheckboxProps & ComponentProps;` it is also broken

Hope this helps with the issue

**Comment by RyanCavanaugh** [comment]
I really need some code that reproduces this issue to proceed. Can either of you post a zip or repo link that I can look at?

**Comment by Strate** [comment]
This issue still reproduces in 2RC.
Unfortunatelly, defining `props: CButtonProps` directly at `CButton` does not fixes the issue in my case. Trying to extract self-reproduceable example.

**Comment by Strate** [comment]
@RyanCavanaugh could you please give me email, where I can send you zip with reproduceable project? Unfortunatelly, I can't share it on github, because it is private.

**Comment by Strate** [comment]
@RyanCavanaugh I want to ping you, please, give me any email :)

**Comment by RyanCavanaugh** [comment]
ryanca@microsoft.com

**Comment by Strate** [comment]
@RyanCavanaugh have you recevied my email? I've send it to you 11 days ago.

**Comment by RyanCavanaugh** [comment]
Sorry for the delay, looking now

**Comment by RyanCavanaugh** [comment]
Tracking at a fresh bug #11187. Thanks again
