### ISSUE TITLE
tsc moduleResolution default value `Classic`?

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/TypeScript#10433]
**TypeScript Version:**  2.0.0 / nightly (2.0.0-dev.201xxxxx)

In docs https://www.typescriptlang.org/docs/handbook/module-resolution.html it is said

> There are two possible module resolution strategies: Node and Classic. You can use the --moduleResolution flag to specify the module resolution strategy. The default if not specified is Node.

But if I run `tsc` the output is:
Module resolution kind is not specified, using 'Classic'.

**Comment by mhegazy** [comment]
the documentation is not accurate. The way it is setup is default is node, unless `--module == Sysmte | AMD`.

**Comment by whitecolor** [comment]
right I had an `"module": "amd" `

**Comment by yahiko00** [comment]
Good to know! Because I felt that module resolution was a littble bit _random_ ^^

**Comment by eemeli** [comment]
I hit the same issue today, a little over two months since this issue was first posted. Perhaps the documentation could be updated on this little detail?

**Comment by mhegazy** [comment]
Should be fixed by https://github.com/Microsoft/TypeScript-Handbook/commit/2426be054473f4879ece29e04691a697ca2e452f
