### ISSUE TITLE
tsc compiler fails after installing update 3 of visual studio

### ISSUE THREAD

**Issue by flieks** [Microsoft/TypeScript#10435]
Hi,

I don't know if this is a TS bug or something else so i post it here too:
[stackoverflow](http://stackoverflow.com/questions/39039055/tsctoolpath-null-in-microsoft-typescript-targets-after-installed-update-3-of-vis)

**Comment by mhegazy** [comment]
can you share a project that reproduces the issue, or an msbuild log with `/verbosity:diagnostic"

**Comment by mhegazy** [comment]
This issue does not seem to be actionable at the moment. Closing for housekeeping purposes. Please reopen if this is still an issue or there is more information to share.

**Comment by flieks** [comment]
Thanks, it was project specific probably. TS was giving errors and didn't want to compile. (even though compileOnErrors=true). I needed to change
<Target Name="CompileIfTypeScript" DependsOnTargets="$(TypeScriptCompileDependsOn)" />
to
<Target Name="CompileIfTypeScript" />

and compileOnSave true in tsconfig
