### ISSUE TITLE
release dates in the Roadmap

### ISSUE THREAD

**Issue by olegchir** [Microsoft/TypeScript#10450]
The Roadmap on GitHub contains no release dates.
Could you please estimate and fill in dates for 2.0 and 2.1?

Sorry for not using standard bug template, but I feel that this question shouldn't be on Stackoverflow, because it's a strategic question for the team.

The Rules of our company (and I believe we are not alone) don't allow us the use of pre-release versions. For new projects, the gap between 1.8 and 2.x may be too large, and It may lead to the use of fundamentally incorrect design decisions. It would be a great advantage if we could say to our QA: look, Typescript 2.x will be released way before our own first milestone! I'm writing this in order to show how this issue is important to us. We don't even need a specific date, at least a month should be ok.

**Comment by DickvdBrink** [comment]
Sometimes the VSCode team leaks some info for the TypeScript release (https://github.com/Microsoft/vscode/issues/10145) but it isn't always correct but might be helpful sometimes ;)

**Comment by yahiko00** [comment]
I use to check the milestones tab in Github to make my own estimation of releases: https://github.com/Microsoft/TypeScript/milestones
For instance, I would say that TS 2.0.1 would be release in couple of weeks, let us say 2 months maximum.
For TS 2.1, I would say, the beta could be release at the end of the year/begining of next year.

Since TS is an Open-Source project, I would feel bad to ask deadline comittments to the TypeScript Team. They are doing their best but quality takes time ;)

**Comment by nippur72** [comment]
asked also in #7651

**Comment by RyanCavanaugh** [comment]
2.0 is a quality-driven release and we'll be shipping it when it's "ready", subject to divisional alignments. The current bug incoming rate is still a bit too high and we have about a dozen bugs left to fix, but there won't be any more feature work going into this release. We have our estimates of when it will be ready but a) we don't announce release dates (sorry!) and b) your guess (given available data) is probably not substantially worse than ours.

2.1 will be where we enable the new emit pipeline, which should have a shorter bug tail but is much riskier (bad emit is much more dangerous). The distance between 2.1 and 2.0 should be *much* shorter than the distance between 1.8 and 2.0 (which is already too long).

**Comment by mhegazy** [comment]
The [road map](https://github.com/Microsoft/TypeScript/wiki/Roadmap) should now have release-dates. We are targeting November 2016 for the 2.1 release.
