### ISSUE TITLE
suggestion: C++ like templates

### ISSUE THREAD

**Issue by Corey-Maler** [Microsoft/TypeScript#10455]
In TypeScript we can pass only types to generics (like in Java either C#, as I know);

But sometimes it is useful to pass a value and find compile-time errors instead runtime. 
## Little examples

Now:

``` typescript

class Vector {
   /* ... */
   private values: number[];
   add(b Vector) {
      if (this.values.length !== b.values.length) throw new Error('vector dimension is mismatch'); // this checks every function call in runtime, what is negative for WebGL applications, etc.
      /* ... other stuff */
   }
}
```

I suggest: 

``` typescript
class Vector<Size: number> {
    private values: numbers[];

    add(b Vector<Size>) {
       // no runtime dimension checks
       for (let i = 0; i < Size; i++) {
          this.values[i] += b.values[i];
       }
    }
}

const a: Vector<3> = new Vector<3>(1, 2, 3);
const b: Vector<3> = new Vector<3>(1, 2, 3);
const c: Vector<4> = new Vector<4>(1, 2, 3, 4);

a.add(b); // OK
a.add(c); // Typecheck error
```

Unfortunately I can't imagine non-mathematical usage of it now, but I think it's can be useful with Enum, number or in usecase something like `declare type API: ServerAPI<PrimaryServerConfig>; declare type FallbackAPI: ServerAPI<SecondaryServerConfig>;`

Why not inheritance? In math examples it could be a lot of classes with a lot of same code, like Vector3, Vector4, Vector5, etc., and matrix like Matrix33, Matrix44, etc.

Contrived example, provided by this feature:

``` typescript
class Client { ... }
class<serverAPI: AbstractSeverAPI> AbstractClients {
   constructor(public projectId: number) {}
   list(): Promise<Array<Client>> {
      return serverAPI.get(`/${this.projectId}/clients`);
   }
}

usage:
define type Clients: AbstractClients<someServerAPIInstanse>;

const myProjectClients = new Clients(1);
```

**Comment by yortus** [comment]
I agree this idea potentially opens up some great new compile-time checking abilities.

The compiler already has some of the machinery in place in the form of unit types (i.e. string/number/boolean/enum literal types). You can get close to what you want doing something like this:

```ts
class Foo<T extends number> {
    op(other: Foo<T>) {/***/}
    private _tag: T; // ensures different type parameters create structurally distinct types
}
let a: Foo<3>;
let b: Foo<4>;
let c: Foo<number>; // OK, but no specific number was given
let d: Foo<string>; // ERROR: Type 'string' does not satisfy the constraint 'number'
a.op(b);            // ERROR: Type '4' is not assignable to type '3'
b.op(a);            // ERROR: Type '3' is not assignable to type '4'
a.op(c);            // ERROR: Type 'number' is not assignable to type '3'
c.op(a);            // OK, because type '3' is assignable to 'number'
```

The problems are that:

- there's currently no way to declare that a type parameter *must* be a unit type, so that for example `Foo<3>` is valid but `Foo<number>` is not.
- you have to allow for TypeScript's structural type system. That what the `_tag` property is for in the above example.

I was toying with a potential use for literal strings (ie known at compile time) as type parameters, in https://github.com/Microsoft/TypeScript/issues/10195#issuecomment-239056270

**Comment by mhegazy** [comment]
Templates, and same for macros, though powerful, introduce a lot of complexity to the language. They also pose challenges to error reporting and tooling in general. For TypeScript we have chosen a different design vector, by supporting generics, union types, type guards, literal types. and mapped types.  though these do not fully compensate for template power, they do enable many scenarios you would be forced to use templates to fulfill in other languages. I do not think this is within the scope of the TS project at the time being.
