### ISSUE TITLE
node-exclusive method declaration TypedArray#set(index: number, value: number)

### ISSUE THREAD

**Issue by djcsdy** [Microsoft/TypeScript#10452]
**TypeScript Version:**  1.8.10

**Problem**

`lib.d.ts` declares the following method for `Uint8Array`:

``` ts
    /**
      * Sets a value or an array of values.
      * @param index The index of the location to set.
      * @param value The value to set.
      */
    set(index: number, value: number): void;
```

The same method is declared for all other `TypedArray` types (`Int8Array`, `Float32Array`, etc).

This method is not defined by ES6 and should be removed. As far as I know no browser implements this method.

This method exists in nodejs but it is a proprietary extension that exists for backwards compatibility with node’s proprietary `Buffer` type. It is never necessary to call this method in node since node also provides the equivalent standard methods defined by ES6.

The correct `set` method defined by ES6 is already declared in `lib.d.ts`:

``` ts
    /**
      * Sets a value or an array of values.
      * @param array A typed or untyped array of values to set.
      * @param offset The index in the current array at which the values are to be written.
      */
    set(array: ArrayLike<number>, offset?: number): void;
```

**Code**

This sample code is plain JS that demonstrates that the `set(index: number, value: number)` method does not exist. You can paste it straight into a browser console.

``` js
var a = new Uint8Array(10);
a.set(3, 5);
console.assert(a[3] === 5, "Value not set.");
```
- Chrome throws a `TypeError` on the second line (correct behaviour according to ES6).
- Edge doesn’t throw a `TypeError`, but the assertion fails (incorrect according to ES6, but still demonstrates that the method is not supported).
- In nodejs, the assertion passes but only due to the presence of a proprietary extension as discussed above.

I did not bother testing the other browsers, I think I’ve made my point :-).

**Aside**

nodejs also provides a proprietary `get(index: number): number` method, again for backwards compatibility with `Buffer`. The `get` method is _not_ declared in `lib.d.ts`, so it seems there is precedent to remove this node-only declaration.

**Comment by mcclure** [comment]
As a piece of trivia, something the TypedArray *does* support is assigning single values via an indexed property setter. `var x = new Float32Array(1); x[0] = 32;` creates a Float32Array with 32 in the 0 position. TypeScript appears to already correctly type this (ie it won't let me say `x[0] = "test"`).

There was a discussion about this on Twitter which I do not understand, but the claim made there was that set()-on-singular-value was present in the original Kronos spec for TypedArray: https://twitter.com/awbjs/status/766702895706218496 but during the ECMA/WebIDL process it was changed to array assignment.

**Comment by mhegazy** [comment]
PRs are welcomed. the fix should be done in https://github.com/Microsoft/TypeScript/blob/master/src/lib/es5.d.ts

**Comment by reiner-dolp** [comment]
@mhegazy a PR should simply remove all `set(index: number, value: number): void;` declarations?

**Comment by mhegazy** [comment]
yes.
