### ISSUE TITLE
Property 'of' / 'map' / 'catch' / etc does not exists on type 'Observable<x>'

### ISSUE THREAD

**Issue by sumtec** [Microsoft/TypeScript#10469]
**TypeScript Version:**  1.8.36.0 (in VS2015 update 3)

**Code**
Sorry, it's not a self contained demo. Just part of it. Can't really run or reproduce the error.

```ts
import {Observable}     from 'rxjs/Observable';
import 'rxjs/add/operator/do';
import 'rxjs/add/observable/of';
import 'rxjs/add/operator/catch';

export class ... {
    public Search(query: string = null): void {
        this.orders = this._service.getPartsLists(query)
            .catch(
            error => {
                this.errorMessage = <any>error;
                return Observable.of<PartsListSummary[]>([]);
            }
            );
    }
}

```

**Expected behavior:**
Get it compiled when enabled "compileOnSave" and "watch".

**Actual behavior:** 
Can be compiled when they are disabled but not enabled.

**Details:**
I am trying AngularJS 2. However, it keeps complaining compilation issue even if I turn these two off. By searching a lot, I found that adding a `///<reference path="../node_modules/typescript/lib/lib.es6.d.ts"/>` would help.

However, if you enabled the "compileOnSave" and "watch", it failed. I believe that there must be something wrong. Otherwise, it won't be like "one work but the other doesn't".

I can now only be able to use that by setting these two option to false. And it's painful because I can't really modify and run.

**Comment by mhegazy** [comment]
I am not an expert on any of these libraries, so without a full project to look at and a description of why this is a TS compiler/language/VSPluing bug, i will not be of much help.

**Comment by sumtec** [comment]
Hi @mhegazy ,

I don't know what kind of information I can provide. Making a demo online seems like not be an option because it's a bug in VS2015 with the watch and compileAndSave enabled. A full C# project put it on GitHub? Well, if you think that might help, I will try to make one. However, it might take sometime to do it.

Thanks

**Comment by mhegazy** [comment]
i do not need the full C# project. i just need the sample project with one or two ts files that show the problem. you might get better response if you post the question on the Angular2 forum as well.

**Comment by mhegazy** [comment]
closing for now. please reopen if more information is available, or there is a reason to believe this a compiler/tools bug and not a project setup issue.

**Comment by MahlanguRonny** [comment]
Well the map part of the error might be because you did not import the "map", try include this import on your imports and see if it makes any difference import **'rxjs/add/operator/map';** I see you did not use the map property but perhaps this might help
