### ISSUE TITLE
Side effects of unused ES6 classes transpiled to ES5. 

### ISSUE THREAD

**Issue by TheLarkInn** [Microsoft/TypeScript#10467]
In the repo link I posted below, it appears that using tools like UglifyJs is not able to 'tree-shake' classes transpiled from TS to target ES5. It appears that the IIFE, is considered a side affect and won't be removed from code even if the export is unused. 

Regardless of where this cam be fixed it's important to see this fixed for the 98% of angular2 users (who favor webpack as their bundler). We will be investigating work around for users for now such as TS ES6=ES6 and then babel to transpile to ES5.

References:
https://github.com/webpack/webpack/issues/2899
https://github.com/mishoo/UglifyJS2/issues/1261

**TypeScript Version:** 2.0.0+
**Code**
https://github.com/blacksonic/typescript-webpack-tree-shaking

**Expected behavior:**
Either TS removes the module or return it as an empty unused module, or the side affect is not present. 
**Actual behavior:** 
The unused export still appears in transpiled code.

**Comment by DanielRosenwasser** [comment]
> We will be investigating work around for users for now such as TS ES6=ES6 and then babel to transpile to ES5.

Babel also generates an IIFE if I'm not mistaken, right?

**Comment by TheLarkInn** [comment]
Different, but it looks encapsulated _mostly_ the same way. 

https://babeljs.io/repl/#?evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&code=export%20class%20Foo%20%7B%7D

**Comment by kitsonk** [comment]
Once you have a method, [Babel reverts to an IIFE](https://babeljs.io/repl/#?evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&experimental=false&loose=false&spec=false&code=export%20class%20Foo%20%7B%0A%20%20foo()%20%7B%7D%0A%7D), just like [TypeScript](http://www.typescriptlang.org/play/#src=export%20class%20Foo%20%7B%0D%0A%09foo()%20%7B%7D%0D%0A%7D).

**Comment by blacksonic** [comment]
It is also an issue with Babel

**Comment by TheLarkInn** [comment]
Thanks for verifying.

**Comment by kzc** [comment]
It's more than an IIFE issue. Uglify will not drop code that is assigned to a global or a property. Uglify doesn't know how exports will be used as it lacks program flow analysis.
```
    var Foo = (function () {
        function Foo() {
        }
        Foo.prototype.foo = function () { };
        return Foo;
    }());
    exports.Foo = Foo;
```

**Comment by blacksonic** [comment]
Is it possible to generate a side-effect free ES5 class declaration?

**Comment by kitsonk** [comment]
> Is it possible to generate a side-effect free ES5 class declaration?

It doesn't have side effects, it is that Uglify thinks that it might, but the IIFE is there so that code inside has the appropriate scope.  There maybe nastier ways to write it (like using `new Function`) but that won't help Uglify understand that the IIFE doesn't have side effects.

**Comment by TheLarkInn** [comment]
Thinking of this from a different perspective. _Should_ TS be able to remove unused exports as part of the transpilation process from `module` ES6/2015 to `target` ES5?

**Comment by kitsonk** [comment]
How would you propose TypeScript detect unused exports?  How would TypeScript know that you intend to publish your TypeScript as a package where all the published (exported) APIs are available and some final build of a project?

Tree shaking of a final bunlded build is usually considered something that is the domain of build tooling and the [TypeScript Design goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals) state this as a non-goal:

> 4) Provide an end-to-end build pipeline. Instead, make the system extensible so that external tools can use the compiler for more complex build workflows.

For TypeScript 2.1 and the change to the transformation based emitter, it is likely someone would be able to create a transform that either would signal to a tree-shaker related export code that could be eliminated, or potentially build the dependency graph itself and not emit the code, but I suspect it is unlikely we will see something like this baked into TypeScript directly.

**Comment by TheLarkInn** [comment]
Totally get what you are saying. I just wondered how much program flow analysis could already be leveraged to do this, if even possible? 

In regards to the build to/bundling, I am 💯 on board with that decision. Just trying to consider ways to optimize if there is room and ability to.

All of those questions you brought up, are excellent points in why it proves to be not a trivial task.

**Comment by paldepind** [comment]
#13721 should solve this issue.

**Comment by kzc** [comment]
> #13721 should solve this issue.

Yes and no. Uglify would drop unused `/*@__PURE__*/` annotated downleveled IIFEs if everything is in the same function scope. It does not address the module exports problem outlined in https://github.com/Microsoft/TypeScript/issues/10467#issuecomment-241446385 which is also an issue in webpack2.

Something like Rollup would have to be used to hoist everything into the same function scope, renaming conflicting things as necessary.

**Comment by mhegazy** [comment]
closing in favor of https://github.com/Microsoft/TypeScript/issues/13721.
