### ISSUE TITLE
Calling another function with same overloads requires a cast or type-check (when overloads has different argument lengths)

### ISSUE THREAD

**Issue by jovdb** [Microsoft/TypeScript#10475]
**TypeScript Version:**  2.1.0-dev.20160819

**Code**
Silly example:
```ts
interface IPoint {x: number, y: number};

function isPoint(p: any): p is IPoint {
	return p && typeof p.x === "number" && typeof p.y === "number";
}

// Calculate area between point and origin
function area(x: number, y: number): number;
function area(point: IPoint): number;
function area(xOrP: number | IPoint, y?: number): number {
	if (isPoint(xOrP))
		return xOrP.x * xOrP.y;
	else 
		return xOrP * y;
}

// same argument signature as area
function size(x: number, y: number): number;
function size(p: IPoint): number;
function size(xOrP: number | IPoint, y?: number): number {
	return area(xOrP, y); // xOrP: error TS2345: Argument of type 'number | IPoint' is not assignable to parameter of type 'number'.
}
```

**Expected behavior:**
I just want to be able to 'forward' the call to another function with the same arguments signature/overloads.

**Actual behavior:** 
error TS2345: Argument of type 'number | IPoint' is not assignable to parameter of type 'number'.

Typescript sees 2 arguments at the call to `area()`, so it uses the first `area `overload: `number, number`.

I known that not all argument combinations are allowed: eg: `area(Point, number)`, so the common overload should not be allowed!
But when the possible combinations/restrictions on the arguments (expressed in the overloads) are for both functions the same, it could be made possible.

I just find it 'strange' that 2 functions with exactly the same arguments and overloads cannot call each other without casting or type-checking.

**Workarounds:**
- cast first argument to any: 
```
return area(xOrP as any, y);  // me no like any :-)
```

- or do a type check and call `area` with different arguments:
```
if (isPoint(xOrP))
	return area(xOrP);
else 
	return area(x, y);
```

**Comment by RyanCavanaugh** [comment]
This would be really expensive to figure out, and really only helps when the signatures are *exactly* the same, which is in practice rather rare.

It's also not always the case that it's safe to pass a second `undefined` argument to a function is exactly the same as invoking it with one argument. Some functions will check `arguments.length` and change their behavior, so passing along both parameters when one is missing might result in unexpected behavior.
