### ISSUE TITLE
Bug in helper function that is emitted by the compiler for module re-exports

### ISSUE THREAD

**Issue by gilboa23** [microsoft/TypeScript#10476]
**TypeScript Version:**  1.8.10

**Code**

An AMD module with re-exports:

``` ts
export * from "a/b";
export * from "a/c";
```

Generates the following code:

``` ts
define(["require", "exports", "a/b", "a/c"], function (require, exports, b_1, c_1) {
   "use strict";
   function __export(m) {
      for (var p in m) if (!exports.hasOwnProperty(p)) exports[p] = m[p];
   }
   __export(b_1);
   __export(c_1);
});
```

**Problem:**
The emitted helper '__export' function will fail if the exports object has an empty prototype (due to custom module loading system) and thus does not inherit the 'hasOwnProperty' method. It will also not handle correctly exported readonly properties (created by custom decorators).

**Workaround:** 

As a workaround, i currently override the emitted function in my TypeScript code like so:

``` ts
function __export(m: any) {
   Object.getOwnPropertyNames(m).forEach(p => Object.defineProperty(exports, p, Object.getOwnPropertyDescriptor(m, p)));
}
export * from "a/b";
export * from "a/c";
```

Please fix the emitted '__exports' function to code similar to the above workaround (at least for ES5/ES6 targets).

**Comment by mhegazy** [comment]
forEach is not supported for ES3, so it will have to be a regular loop

```ts
 var p= Object.getOwnPropertyNames(m);
 for (var i =0, n = p.lenght; i<n; i++){
    exports[p[i]] = m[p[i]];
 }
```

**Comment by gilboa23** [comment]
Ok., but this is not the bug i opened. The problem is that you're copying the exported property values instead of copying the property definitions. As i mentioned, when targeting ES5 and above you should use Object.defineProperty instead of simple assignment of the exported properties.

**Comment by gilboa23** [comment]
Referencing <a href="https://github.com/Microsoft/TypeScript/pull/9097">PR #9097</a>.

**Comment by mhegazy** [comment]
correct related issue is https://github.com/Microsoft/TypeScript/issues/10905

**Comment by RyanCavanaugh** [comment]
We now use `Object.prototype.hasOwnProperty.call(exports, p)`
