### ISSUE TITLE
Can not debug Typescript files

### ISSUE THREAD

**Issue by TheGrandUser** [Microsoft/TypeScript#1048]
I've been unable to debug any typescript files in my project https://github.com/TheGrandUser/Hexcrawl
The project was created using VS 2013 Update 3, with I think the then current Web Essentials. I simply added the ts files using the context menu in the solution explorer.

I had modified the .csproj file a little to try matching another project's that could debug ts files, but to no avail

**Comment by mhegazy** [comment]
Please try the latest [1.4 Release](https://github.com/Microsoft/TypeScript/releases/tag/v1.4). closing the issue for now for the lack of activity.

**Comment by TheGrandUser** [comment]
This does appear to be fixed. Thanks
