### ISSUE TITLE
`--pretty` style errors should be the default on supported TTYs

### ISSUE THREAD

**Issue by weswigham** [Microsoft/TypeScript#10488]
Title. It would be nice to add a `--errorStyle [pretty|terse|auto]` command and deprecate `--pretty` (which would then be equivalent to `--errorStyle pretty`) as well.

cc @DanielRosenwasser

**Comment by DanielRosenwasser** [comment]
:+1:

**Comment by DanielRosenwasser** [comment]
For the record, terse needs to be the default when output to

* a file
* a pipe
* anything else that's not console output?
