### ISSUE TITLE
Access class variable of generic class

### ISSUE THREAD

**Issue by mathebox** [Microsoft/TypeScript#10481]
**TypeScript Version:**  2.1.0-dev.20160822 

**Code**

```ts
abstract class Bar {
    static something: string;
}

class Foo extends Bar {
    static something = "Foo";
}

function say<T extends Bar>() {
    console.log(T.something); // Cannot find name 'T'
}
```

**Expected behavior:**
compiles without error

**Actual behavior:** 
`Error TS2304: Cannot find name 'T'.`

**Comment by mhegazy** [comment]
Two notes here, 1. Types in TypeScript are design time constructs, they do not exist at run time. so when the function `say` is called, there is no entity `T` anywhere in your JS code.
and 2. `Bar` is the instance type (in this case has no properties), and instances of class `Bar` do not have a member `something`, this is a static member that only exists on the class constructor (use `typeof Bar` to describe its shape).

so an alternative to getting to the `T` is passing an argument of that type:
````ts

function say<T extends typeof Bar>(target: T) {
    console.log(target.something); // OK
}
```

**Comment by mathebox** [comment]
Thanks!
