### ISSUE TITLE
VS15 Preview 4 with TS2.0: SourceMap read failed

### ISSUE THREAD

**Issue by SaschaNaz** [Microsoft/TypeScript#10491]
**TypeScript Version:**  2.0.1 (packed with VS15 Preview 4)

**Repro:**

1. Create a new JS project: Blank App (Universal Windows)
2. Add "sources" folder
3. Add "file.ts" on "sources" folder
4. Type "var a: number;" or just anything on "file.ts"
4. Open project property page -> TypeScript Build
5. Set "Combine JavaScript output into file" value to "js/app.js"
6. Add `<script src="js/app.js"></script>` on "index.html"
7. Build and deploy the app
8. Check whether "Script Documents -> MSAppHost/3.0 -> index.html -> app.js" shows any subfiles
9. Check the debug output shows any SourceMap error 

**Expected behavior:**

It should work as VS2015 does.

**Actual behavior:** 

'WWAHost.exe' (Script): Loaded 'Script Code (MSAppHost/3.0)'.
SourceMap ms-appx://(path).js.map read failed: The URI prefix is not recognized..

**Workaround:**

Add the "js/app.js" to the project and deploy again

**Cross post:** https://connect.microsoft.com/VisualStudio/feedback/details/3076889

Not sure this should be posted here, but I did because I think only TS (or Babel?) users add JS files on HTML without adding them on their project file.

**Comment by minestarks** [comment]
Thanks for reporting! I'll have fixed this in the next release -- in the meantime you can manually configure your project to generate the correct source map URLs by adding the following to your project file:

```xml
  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <TypeScriptSourceMap>true</TypeScriptSourceMap>
    <TypeScriptMapRoot>$(MSBuildProjectDirectory)</TypeScriptMapRoot>
    <TypeScriptSourceRoot>$(MSBuildProjectDirectory)</TypeScriptSourceRoot>
    <TypeScriptRootDir>$(MSBuildProjectDirectory)</TypeScriptRootDir>
  </PropertyGroup>
```

**Comment by SaschaNaz** [comment]
It should be `<TypeScriptMapRoot>$(MSBuildProjectDirectory)\js</TypeScriptMapRoot>` but thanks :D
