### ISSUE TITLE
Salsa: Require of module shows type as "typeof "

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#10499]
**TypeScript Version:**  nightly

**Code**

I've written a fourslash test:

```ts
/// <reference path="fourslash.ts" />

// @allowJs: true
// @Filename: a.js
////const /**/x = require("./b");

// @Filename: b.js
////exports.x = 0;

goTo.marker();
verify.quickInfoIs("const x: typeof ");
```

**Expected behavior:**
Ideally, `const x: { x: 0 }`, but at least something that doesn't look like a bug.

**Actual behavior:** 
We get "typeof " as the type.

Note that we don't get any such error when the imported module uses `module.exports = 0`.

**Comment by mhegazy** [comment]
it should be `typeof ./b` since the module does have a name.
