### ISSUE TITLE
TSServer should report status

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/TypeScript#10493]
**TypeScript Version:**  1.8.10
- Open a project with lots of ts files (for example VS Code).
- it takes the tsserver a long time to startup due to the fact the it reads all ts files into memory and does a quick pass over them. 

Would be cool if the tsserver would report status during that time via events. Currently we can't show any information to the user and requests (like for example code complete) are waiting.

**Comment by mhegazy** [comment]
we have the infrastructure for sending events, the server host gets a chance to execute every time a file is read from disk, so we could fire some events if the response time exceeds a threshold.

**Comment by RyanCavanaugh** [comment]
This is obsolete now that we have the syntactic semantic server available during project load
