### ISSUE TITLE
`_` prefix for unused locals

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#10494]
The following code should be allowed by `_` prefix for declaration of nominal types.

**TypeScript Version:**  master

**Code**

```ts
class C {
  private _: void;
}
```

**Expected behavior:**

```
$ node built/local/tsc.js --noEmit --lib es6 --noUnusedLocals index.ts
```

**Actual behavior:** 

```
$ node built/local/tsc.js --noEmit --lib es6 --noUnusedLocals index.ts
index.ts(2,11): error TS6133: '_' is declared but never used.
```

**Comment by RyanCavanaugh** [comment]
Some people are going to prefix all privates with `_` as a naming convention and will find the lack of checking odd. Why are you in this state?

**Comment by mhegazy** [comment]
The fix here is to use the local somewhere, or declare it as public or protected.

The only exclusion we have added is for function parameters, since a function might not be using all the functions it declares.

**Comment by falsandtru** [comment]
@RyanCavanaugh I'm using nominal types to distinguish commands.

```ts
type WorkerCommand<T, D>
  = WorkerCommand.Deps<T>
  | WorkerCommand.Call<D>
  | WorkerCommand.Exit;

namespace WorkerCommand {
  abstract class AbstractCommand {
    private WORKER_COMMAND: void;
  }
  export class Deps<T> extends AbstractCommand {
    private COMMAND: this;
    constructor(public namespace: T) {
      super();
    }
  }
  export class Call<D> extends AbstractCommand {
    private COMMAND: this;
    constructor(public data: D) {
      super();
    }
  }
  export class Exit extends AbstractCommand {
    private COMMAND: this;
    constructor(public reason: any) {
      super();
    }
  }
}
```

@mhegazy I see, thanks.
