### ISSUE TITLE
Un-used properties/methods

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/TypeScript#10497]
**TypeScript Version:**  1.8.10

I think that it would be a nice feature to let the user know what properties/methods are defined but unused, this would be done doing so by underlining the method/property with a green underline.

This would more than likely only affect `private` properties and methods. Here is an example:

```ts
class MyClass {

    // Warning saying that "This item is never used"
    private myString1: string;

    // Warning saying that "This item has been assigned to but is never used"
    private myString2: string = 'abc123';

    // No Warning since this could be used anywhere (such as an external library)  
    public myString3: string = '123456';

    // Warning saying that "This item is never used"
    private myMethod1(): void { }

    // No Warning since this could be used anywhere (such as an external library)    
    public myMethod2(): void { }

}

class MyClass2 extends MyClass { }
```

**Comment by RyanCavanaugh** [comment]
Unused `protected` still makes sense because a derivative outside your compilation could be using them. But private members could be checked for unusedness.

**Comment by TheColorRed** [comment]
Okay, I have remove the `protected` part from the post.

**Comment by RyanCavanaugh** [comment]
Actually this was implemented with the `--noUnusedLocals` flag in 2.0 #9200

**Comment by TheColorRed** [comment]
@RyanCavanaugh that is only in the compiler though, and not visually in the editor right?

**Comment by mhegazy** [comment]
@TheColorRed it should work in the editor as well if you have the option set in your tsconfig.json. you need to make sure your editor is running against TS 2.0 .
