### ISSUE TITLE
TSServer: requests that can't produce a result shouldn't fail with a failed response

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#10496]
**TypeScript Version:**  1.8.10
**Code**

``` js
define(['./fdoo'], function(buffer) {
    buffer.joao;
});

hello there
some new content


export function foo() {

}
```
- ask the tsserver for some quickinfo information on position where no hover is available
- the server response with a request failed (success: false) which makes it impossible to distinguish between a real error (for example an exception on the server) and the fact that no hover is available. Instead the response should be success: true with body empty.

**Comment by dbaeumer** [comment]
Same for 'occurrences' request.

**Comment by dbaeumer** [comment]
Looks like most request do this. We either need an indication that the error is expected or as said the result should be a success true.

**Comment by RyanCavanaugh** [comment]
Seems like this isn't critical. Please open a new bug if this is impacting UX in a concrete way.
