### ISSUE TITLE
JSX: Convert ampersand encoded HTML entities into UTF-8

### ISSUE THREAD

**Issue by huan086** [Microsoft/TypeScript#10492]
HTML entities encoded using `&#`, `&#x` should be converted, to be in line with [babel's behaviour](https://github.com/babel/babel/blob/b91b4a4dc03eff8647b669c8935b18f0c6d7ed81/packages/babylon/src/plugins/jsx/index.js#L129)

**TypeScript Version:**  2.0.0

**Code**

```ts
<div>&#123;braces&#125;</div>

```

**Expected behavior:**

Outputs the html

```html
<div>{braces}</div>
```

**Actual behavior:** 

Outputs the html
```html
<div>&#123;braces&#125;</div>
```

**Current workaround is to use**
```ts
<div>{"{"}braces{"}"}</div>

```
which creates a lot of unnecessary nodes

**Comment by huan086** [comment]
Encountered another difference with babel regarding encoded HTML in attributes:

**TypeScript Version:**  2.0.0

**Code**

```ts
function MyComponent(props) {
    return (<div>{props.myAttr}</div>);
}

elsewhere:

<MyComponent myAttr="more&hellip;" />
```

**Expected behavior:**

Outputs the html

```html
<div>more…</div>
```

**Actual behavior:** 

Outputs the html
```html
<div>more&hellip;</div>
```

**Comment by RyanCavanaugh** [comment]
@huan086 please log a separate issue for that (attribute values and JSX text are treated on totally different codepaths so we need two bugs to track the work)
