### ISSUE TITLE
Extend scope of narrowed consts

### ISSUE THREAD

**Issue by jods4** [Microsoft/TypeScript#10501]
This is a suggestion to lift a limitation of the current flow analysis.

Consider this, with strict null checks:
```ts
function f() {
  let name: string | null = frob();
  if (!name) return;
  bar(() => name.length);  // Error possibly null name
}
```
TS does not propagate type guards accross function captures.
Rightly so because we don't know when the lambda will actually be called. It can be called much later and at that point `name` might be `null` again. E.g. if right after `bar(...)` we have `name = null`.

Now, consider this variation:
```ts
function f() {
  const name: string | null = frob();
  if (!name) return;
  bar(() => name.length);  // Error possibly null name
}
```
I suggest that because `name` is declared with `const`, it can't change. So if at the point of capture it has a _not null_ type guard, then it is correct to propagate this information inside the lambda.
:point_right:  The second example can compile without error.

**Comment by RyanCavanaugh** [comment]
This is already not an error in `master`.

**Comment by jods4** [comment]
Cool thanks! I'm on the nightly at home but this happened at work and we're still on `2.0.0`.

**Comment by jods4** [comment]
Sorry it seems my short repro was not good enough.
After testing the code above works even on 2.0.0, but try this instead:
```ts
function f() {
  const x: string | null = frob();
  if (!x)
    return {
      bar() { return x.length; }  // Error: possibly null x
    };
}
```

Not sure what the difference is here... Method in object literals are considered differently than plain lambdas?

**Comment by RyanCavanaugh** [comment]
That error is correct because you tested for `!x`

**Comment by RyanCavanaugh** [comment]
```ts
function f() {
  const x: string | null = <any>{};
  if (x !== null) {
    return {
      bar() { return x.length; }  // Error: possibly null x
    };
  }
}
```

**Comment by ahejlsberg** [comment]
Currently we only extend const type guards to nested function expressions and arrow functions, but we ought to also include methods in object literals and class expressions. Until we have a fix, the easy workaround for object literals is to just use regular properties and function expressions. For example, this works:

```ts
function f() {
  const x: string | null = <any>{};
  if (x !== null) {
    return {
      bar: function() { return x.length; }  // Ok
    };
  }
}
```
