### ISSUE TITLE
Typo in function emitExternalImportDeclaration?

### ISSUE THREAD

**Issue by kzc** [Microsoft/TypeScript#10505]
const isNakedImport = SyntaxKind.ImportDeclaration && !(<ImportDeclaration>node).importClause;

https://github.com/Microsoft/TypeScript/blob/ddb5a00410d695d35b55c5482876a16f7c696c4b/src/compiler/emitter.ts#L6590

Possibly missing `node.kind ===` before `SyntaxKind.ImportDeclaration` ?

Noticed it when running `uglifyjs lib/tsc.js -c`
```
WARN: Condition left of && always true [lib/tsc.js:34409,48]
```
```
 34409	                            var isNakedImport = 230 && !node.importClause;
```

**Comment by DanielRosenwasser** [comment]
Nice catch @kzc! We'd be willing to take a PR for the fix with a test where this surfaces.

**Comment by kzc** [comment]
Just thought I'd report the obvious issue. You can take over.

**Comment by kzc** [comment]
A previous patch confirms the suggested fix:

https://github.com/Microsoft/TypeScript/commit/956d7a82f337f50b8778fbc1578abf8897ceccd6#diff-20a9fa4d3e9d09f60c275a3dda245867L5008

Surprised by its author - coding royalty!

**Comment by RyanCavanaugh** [comment]
If you could avoid bugs by being smart, we wouldn't need TypeScript :wink:
