### ISSUE TITLE
Discussing about let & const support

### ISSUE THREAD

**Issue by srenault** [microsoft/TypeScript#1053]
Recently, you offer us `let` and `const` support. Sadly, the only way to use it is to target es6.
Why don't implement the logic in the compiler itself like others es6 features (class, arrow functions).
Does the reason is technical ?

**Comment by joewood** [comment]
Is this issue being tracked elsewhere? I'm wondering how Traceur handles this problem. ES6 support for **let** and **const** still seem [inconsistent](http://kangax.github.io/compat-table/es6/).

**Comment by basarat** [comment]
More technical discussion around **let**: https://github.com/Microsoft/TypeScript/issues/1690 

Closure creation is how 6to5 and traceur handle it, and it does result in memory bloat even for them.
