### ISSUE TITLE
Find-all-references for class should find static uses of `this`

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#10537]
**TypeScript Version:**  nightly

**Code**

``` ts
class C {
    static x() {
        return this;
    }
}
```

**Expected behavior:**

Finding all references for `C` includes the static use of `this`.

**Actual behavior:** 

It doesn't.

**Comment by DanielRosenwasser** [comment]
Technically `this` can refer to a subclass constructor in these scenarios. It's not always `C`, though it's arguable whether that matters.

**Comment by mhegazy** [comment]
this is related to imports/exports. the findallreferences currently only looks for symbols by name, so anything that is not named `C` will not be considered. we can make it search for a set of names instead.
