### ISSUE TITLE
Implicit return in arrow functions

### ISSUE THREAD

**Issue by Kriegslustig** [Microsoft/TypeScript#10534]
**TypeScript Version:**  1.8.10

**Code**

```ts
const add = (x : number, y : number) : number =>
  // Some comment
  x + y
```

**tsconfig.json**:

```json
{
  "compilerOptions": {
    "outDir": "./dist/",
    "sourceMap": true,
    "noImplicitAny": true
  },
  "files": [ "./index.ts" ]
}
```

**Expected behavior:**

```js
var add = function (x, y) {
    // Some comment
    return x + y;
};
```

**Actual behavior:** 

```js
var add = function (x, y) {
    // Some comment
    return 
    // Some comment
    x + y;
};
```

[Here's a repository](https://github.com/Kriegslustig/typescript-arrow-functions-bug) containing that code. This **only** hapends when configuring no compilation target. Not even when configuring it as es3, which is the default according to [this](http://json.schemastore.org/tsconfig).

**Comment by mhegazy** [comment]
This should be fixed in latest and in `typescript@2.0.0`
