### ISSUE TITLE
What if I have multiple baseUrl

### ISSUE THREAD

**Issue by twoeo** [Microsoft/TypeScript#10531]
**TypeScript Version:**  nightly 2.1.0-dev20160824

**Code**

```ts
{
    "compilerOptions": {
        "baseUrl": [
            "libs",
            "shared"
        ]
    }
}
```

**Expected behavior:**

such as ``import ModuleB from 'ModuleB'``

wanna find in `libs/ModuleB` first

then `shared/ModuleB`

**Actual behavior:** 

baseUrl not support array

**Comment by jeffijoe** [comment]
Why did you close? I'd like this, too. :)

**Comment by mhegazy** [comment]
add multiple paths options:

```json
{
    "compilerOptions": {
        "baseUrl": "./",
        "paths" : {
            "*" : ["libs/*", "shared/*"]
        }
    }
}
```

See http://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping for more details.
