### ISSUE TITLE
Salsa does not recognize JSDoc parameter properties in object literal format on multiple lines

### ISSUE THREAD

**Issue by abgivant** [Microsoft/TypeScript#10535]
When calling a function with object parameters documented with JSDoc, Visual Studio Code will not give intellisense completions if the parameter was documented using the object literal format with the comment broken up over multiple lines. 

This type of formatting allows for better readability when documenting objects with a lot of properties, so it would be helpful if this was supported.

**TypeScript Version:**  2.1.0-dev.20160824

**Code**

![](https://cloud.githubusercontent.com/assets/3431954/17941232/0f7ab620-69f8-11e6-9ee0-bbf06462c2da.png)
![](https://cloud.githubusercontent.com/assets/3431954/17941334/74482574-69f8-11e6-96f1-d2777a68642c.png)

**Expected behavior:**

The properties of an object parameter should be recognized when it is documented using the JSDoc object literal @param syntax, even if the comment spans multiple lines.

**Actual behavior:** 

No properties of the object are recognized unless the JSDoc comment is only a single line.

**Comment by mhegazy** [comment]
@sandersn looks related to your jsdoc parsing.

**Comment by sandersn** [comment]
Yep, my changes should fix this since jsdoc type parsing now delegates to the real typescript type parser, which of course doesn't care about whitespace.

(Note: object literal types aren't actually standard jsdoc, they seem to have been introduced by Closure and TypeScript.)
