### ISSUE TITLE
endsWidth ambiguity

### ISSUE THREAD

**Issue by BobFrGit** [Microsoft/TypeScript#10548]
**TypeScript Version:**  1.8.6

I recognize that endsWith is ES6 only but Visual Studio intellisense still suggestions it for earlier targets and then the compiler says the function does not exist. Perhaps intellisense could be a tad smarter or at least warn and the error message can be more informative. The current behavior is very confusing.

Of course there is the option of compiling it into code like 
```
substr(-s.length) == s
```

**Comment by RyanCavanaugh** [comment]
You should only see that in the list if you're targeting ES6. Are you using a tsconfig.json file?

**Comment by BobFrGit** [comment]
No tsconfig. Just the properties in the njsproj file. It  Trivial to repro. Created a console NodeJS. It defaults to ES5 and suggestions endsWIth and then says it does not exist on type string. Change to ES6 and it compiles.
[Sample.zip](https://github.com/Microsoft/TypeScript/files/438338/Sample.zip)

**Comment by DanielRosenwasser** [comment]
This might be related to NTVS. @paulvanbrenk and @mousetraps may know more.

**Comment by paulvanbrenk** [comment]
@BobFrGit Are you using the experimental languageservice in node tools?
