### ISSUE TITLE
Consider assignability of object literal to union type

### ISSUE THREAD

**Issue by sheetalkamat** [Microsoft/TypeScript#1055]
Consider below sample:
```TypeScript
var str: string;
var num: number;
var strOrNumber: string | number = str || num;
var objStr: { prop: string };
var objNum: { prop: number };
var objStrOrNum1: { prop: string } | { prop: number } = objStr || objNum;
var objStrOrNum2: { prop: string | number } = objStr || objNum;
var objStrOrNum3: { prop: string } | { prop: number } = { //  Currently an error
    prop : strOrNumber
};
var objStrOrNum4: { prop: string | number } = {
    prop: strOrNumber
};
```

The above example results in an error on var declaration of objStrOrNum3
```
Type '{ prop: string | number; }' is not assignable to type '{ prop: string; } | { prop: number; }'.
  Type '{ prop: string | number; }' is not assignable to type '{ prop: number; }'.
    Types of property 'prop' are incompatible.
      Type 'string | number' is not assignable to type 'number'.
        Type 'string' is not assignable to type 'number'.
```

Consider the assignability section in the spec
```
•	S is a union type and each constituent type of S is assignable to T.
•	T is a union type and S is assignable to at least one constituent type of T.
```

In case of objStrOrNum3, the S is not union Type but object Literal so we go to next step. Since T is union Type we only allow the assignment of either object with property of type string or object with property of type number but do not allow object with property of type string | number.

It seems like if we had another step that said if the step: 
```TypeScript
•	T is a union type and S is assignable to at least one constituent type of T.
```
failed, try assigning S to a type that has all the properties from the constituent types of T and for the members/signatures that are in union have type from the union property/signature. It would result in error for objStrOrNum3 to go away but would also allow the object that satisfies the true union rule be allowed.

With that consider the below sample:
```TypeScript
var objStrOrNum5: { prop: string; anotherP: string; } | { prop: number } = { prop: strOrNumber };
var objStrOrNum6: { prop: string; anotherP: string; } | { prop: number } = {
    prop: strOrNumber,
    anotherP: str
};
var objStrOrNum7: { prop: string; anotherP: string; } | { prop: number; anotherP1: number } = {
    prop: strOrNumber,
    anotherP: str
};
var objStrOrNum8: { prop: string; anotherP: string; } | { prop: number; anotherP1: number } = {
    prop: strOrNumber,
    anotherP: str,
    anotherP1: num
};
```

With the above step: objStrOrNum5 and objStrOrNum7 should still be errors because we cannot guarantee if the objectLiteral will correctly satisfy either of its constituent types. But objStrOrNum6 and objStrOrNum7 should be ok.

**Comment by mhegazy** [comment]
Looks like in practice this issue was not much of annoyance. closing this suggestion for now. please reopen if there is more feedback.
