### ISSUE TITLE
Suggestion: Extensions system like Roslyn

### ISSUE THREAD

**Issue by Anjmao** [Microsoft/TypeScript#10554]
It would be nice if developers can write their own extensions for typescript. One scenario I can think of is angular 2 inline templates with intellisense and custom compile for them. This would give similar power as jsx.
```ts
@Component({
  moduleId: module.id,
  selector: 'app',
  template: `<h1>${title}</h1>`,
})
export class AppComponent{
  title = 'app works!';
}
```
This is how I imagine full workflow.

1. Developer create ts extension and push to npm
2. Consumer install it
3. Last step is to register extension in tsconfig.json
```json
{
  "extensions": [
      "angular2-templates"
  ]
}

```

**Comment by nippur72** [comment]
I think this is being discussed in #6508.
