### ISSUE TITLE
Default Parameters are not in arguments

### ISSUE THREAD

**Issue by sebilasse** [Microsoft/TypeScript#10555]
**TypeScript Version:**  1.8.0

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
function startsWith(str: string, target: string, position: number = 0) {
  console.log(str, target, position);
  // 'lorem', 'lor', 0
  console.log(arguments);
  // { '0': 'lorem', '1': 'lor' }
}
startsWith('lorem', 'lor');
```

**Expected behavior:**
I would expect that `arguments` has all my initial parameters (including defaults).

**Actual behavior:** 
`arguments` does not have the default parameter `0`...
This should at least be documented.

**Comment by RyanCavanaugh** [comment]
I think you could reasonably argue it both ways.

Where in the documentation would you have expected to find this information?

**Comment by sebilasse** [comment]
https://www.typescriptlang.org/docs/handbook/functions.html - "Optional and Default Parameters".

**Comment by HerringtonDarkholme** [comment]
Actually it is documented in es2016 [spec](http://www.ecma-international.org/ecma-262/7.0/#sec-functiondeclarationinstantiation).  Default parameter does not count in `arguments` object. This behavior aligns with es6 engine and babel.

Since TypeScript is a superset of JavaScript, if it is understandable to not be documented . Nonetheless adding this to F.A.Q. is not harmful.

**Comment by bterlson** [comment]
`arguments` is the arguments you pass to the function only per ECMAScript (and all implementations[1]). The semantics here are correct.

1:
```javascript
function startsWith(str, target, position = 0) {
  print(str, target, position);
  print(Array.prototype.slice.apply(arguments));
}
startsWith('lorem', 'lor');
/*
┌─────────────────────┬─────────────┐
│ d8                  │ lorem lor 0 │
│ chakra-es6          │ lorem,lor   │
│ chakra              │             │
│ chakra-experimental │             │
│ sm                  │             │
└─────────────────────┴─────────────┘
*/
```

**Comment by DanielRosenwasser** [comment]
Yup - just to clarify, FunctionDeclarationInstantiation occurs as part of OrdinaryCallEvaluateBody. That's the runtime semantics.

**Comment by DanielRosenwasser** [comment]
Reopening just for discussion - would we really want this documented? I'd prefer to steer people away from `arguments` in general now that rest parameters are a thing.

**Comment by RyanCavanaugh** [comment]
If it's the same as the ES6 behavior then there's no need for us to document all the details of the behavior.
