### ISSUE TITLE
TypeScript compile errors stop being reported when multiple Index files are open

### ISSUE THREAD

**Issue by waderyan** [Microsoft/TypeScript#10559]
_From @bdoss on August 25, 2016 20:59_

- VSCode Version: 1.4
- VSCode Insiders Version: 1.5
- TypeScript Versions: 1.8.10, 2.0
- OS Version: Windows 10

Steps to Reproduce:

Open multiple tabs named Index.ts(x). Compile errors and intellisense only appear to function properly in the first tab opened. Only appears to impact files named Index.ts/Index.tsx from what I am able to reproduce reliably.

Source: https://github.com/bdoss/tsserver-bug

![bug steps](https://dl.dropboxusercontent.com/s/0pe2rgt52wnw4qu/tsserver-bug-steps.gif)

_Copied from original issue: Microsoft/vscode#10975_

**Comment by waderyan** [comment]
@bdoss thank you for opening this issue and for creating the easy to understand gif! I am going to migrate this to the TypeScript language service repo.

**Comment by mhegazy** [comment]
@vladima has a fix for this.

**Comment by mhegazy** [comment]
@vladima is this already fixed in release-2.0.5?
