### ISSUE TITLE
Generic type constraint for abstract class.

### ISSUE THREAD

**Issue by thynson** [Microsoft/TypeScript#10551]
Too constraint a generic type that is a class, we can write `{new():T}`, however it doesn't match an abstract class.
```typescript
class X{};
abstract class Y{};
function f<T>(x: {new():T});
f(X);// OK
f(Y);// Faild
```
Is there any way overcome this?

**Comment by RyanCavanaugh** [comment]
Why would you want to? It's illegal to `new Y`

**Comment by thynson** [comment]
I'm writing an IoC container, use abstract class itself as indentifier to register its implementation.
And `function f<T>(x: {prototype: T})` works, thank you!
