### ISSUE TITLE
JSX: Convert encoded HTML entities in attributes into UTF-8

### ISSUE THREAD

**Issue by huan086** [Microsoft/TypeScript#10563]
From https://github.com/Microsoft/TypeScript/issues/10492

Encountered another difference with babel regarding encoded HTML in attributes:

**TypeScript Version:**  2.0.0

**Code**

```ts
function MyComponent(props) {
    return (<div>{props.myAttr}</div>);
}

elsewhere:

<MyComponent myAttr="more&hellip;" />
```

**Expected behavior:**

Outputs the html

```html
<div>more&hellip;</div>
```

**Actual behavior:** 

Outputs the html
```html
<div>more&amp;hellip;</div>
```

Make sure that &# and &#x works too!

Be careful of the following subtlety

```ts
<MyComponent myAttr="This is &amp;# encoded, like in HTML. \ has no effect" />
<MyComponent myAttr={"This is \\u encoded, like in JavaScript. & has no effect"} />
```

**Comment by andy-ms** [comment]
Fixed by #10747
