### ISSUE TITLE
Consider imports of "foo/.ts"

### ISSUE THREAD

**Issue by andy-ms** [microsoft/TypeScript#10562]
This issue was raised by #10510: If a user wants to import a file with no basename, should they be able to import "foo/" and have it matched by "foo/.ts" (rather than "foo/index.ts")?
The behavior of module loaders varies here.

**Comment by mhegazy** [comment]
can you elaborate on what the scenario is here?

**Comment by DanielRosenwasser** [comment]
@weswigham the onus is on you to come up with something useful. :smile:
