### ISSUE TITLE
Get type of generic type.

### ISSUE THREAD

**Issue by joesonw** [Microsoft/TypeScript#10576]
**TypeScript Version:** :  2.1.0-dev.20160721

I understand that `reflect-metadata` retrieves the metadata information for me. However, It can only get the outmost type. 

Say, I wanted to get the return type of `async function():Promise<string>`, it can tells me its a promise. Same goes for `Array<T>`.

Is there a plan for providing nested types? Or there is already a way?

**Comment by mhegazy** [comment]
This is not possible without a full type serialization scheme. you can find a long discussion about this in https://github.com/Microsoft/TypeScript/issues/3628
