### ISSUE TITLE
Experimental support for WebGL 2?

### ISSUE THREAD

**Issue by omarhuseynov011** [Microsoft/TypeScript#10579]
I asked [this question](http://stackoverflow.com/questions/39138465/why-there-is-no-experimental-support-for-webgl2-in-typescript?noredirect=1#comment65622161_39138465) on stackoverflow but couldn't get a proper answer

Are there any plans to bring experimental WebGL 2 support to help in typing?

**Comment by kitsonk** [comment]
Cross posting from StackOverflow is not very nice.

The response that was given was accurate on StackOverflow.  Since it is highly experimental and only available under flags in Chrome and Firefox, it will be a long time before its library is included officially in TypeScript.  You need to either find a typings library that includes the definitions for WebGL 2 or write one yourself, which is essentially what the response on StackOverflow was which you rejected, but it is accurate.

**Comment by mhegazy** [comment]
Also please note that the declaration can be defined locally, and does not have to be in lib.d.ts for you to consume. 

To use WebGL2 today, you will need to author a declaration file for the APIs you want ot use, something similar to WebGL in https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/webgl-ext/webgl-ext.d.ts.
I would also recommend contributing your .d.ts file to definitllyTyped to help other users looking for WebGL2 declarations.

We try to include only standard APIs, so eventually when WebGL2 is finalized we can pull your declaration file into the main lib.d.ts.

hope that helps.

**Comment by omarhuseynov011** [comment]
Thanks that is helpful. I wish there was an option in the compiler from which you could enable experimental features and use them in code (similar to enabling ES6).

**Comment by mhegazy** [comment]
For new language features that involves syntax and transformation, e.g. asycn/await, decorators, etc.. the compiler is the place to add the support, and it is usually enabled under experimental flag (e.g. `--expermentalDecorators`). For library support (i.e. declarations that you would expect to be in lib.d.ts)  https://github.com/DefinitelyTyped/DefinitelyTyped is the place for getting these and no need for flags. you can download the ones you want to use and use them.

If a definition already exists on definitelytyped, i would recommend submitting a contribution.

**Comment by MaxGraey** [comment]
It's happening! See #14733
