### ISSUE TITLE
Allow omitting '/**/*' in include

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#10578]
This is a huge time sink for users who are going to think

``` json
"include": ["./foo/bar"]
```

is equivalent to

``` json
"include": ["./foo/bar/**/*"]
```

At the very least, we can give a warning.

Of note, `"exclude": "./foo"` seems to be equivalent to `"exclude": "./foo/**/*`, so why is there an inconsistency here?

**Comment by vicb** [comment]
context ?

**Comment by mhegazy** [comment]
@riknoll can you take a look.

**Comment by cdaringe** [comment]
the docs, as mentioned in #11425, _already declare that this is how it works_.  FYI!

**Comment by basarat** [comment]
I have a section for it in TypeScript deep dive as well : https://basarat.gitbooks.io/typescript/content/docs/project/files.html :rose:

**Comment by mhegazy** [comment]
ppl keep running into this issue. we need to fix this sooner.
