### ISSUE TITLE
Type must have a '[Symbol.iterator]()' method that returns an iterator.

### ISSUE THREAD

**Issue by FieryCod** [Microsoft/TypeScript#10574]
**TypeScript Version:**  1.8.10

**Code**
```
let MyObject = {
    'a': 'Hello',
    'b': 'it\'s',
    'c': 'me',
    'd': 'you',
    'e': 'looking',
    'f': 'for'
};
MyObject[Symbol.iterator] = function* () {
    let properties = Object.keys(this);
    for (let i of properties) {
        yield [i, this[i]];
    }
}
for (let [k, v] of MyObject) {
    console.log(`Here is key ${k} and here is value ${v}`);
}
```
```ts
```

**Expected behavior:**
I want this code to pass without error but I do not now how can i do it.
If i try to run the .js code it works just fine and prints this output:
> Here is key a and here is value Hello
> Here is key b and here is value it's
> Here is key c and here is value me
> Here is key d and here is value you
> Here is key e and here is value looking
> Here is key f and here is value for

**Actual behavior:** 
The error message is:
Type must have a '[Symbol.iterator]()' method that returns an iterator.

**Comment by alitaheri** [comment]
The inferred type of `MyObject` doesn't have an iterator. try:

```js
let MyObject = {
    'a': 'Hello',
    'b': 'it\'s',
    'c': 'me',
    'd': 'you',
    'e': 'looking',
    'f': 'for',
    [Symbol.iterator]: function* () {
        let properties = Object.keys(this);
        for (let i of properties) {
            yield [i, this[i]];
        }
    }  
};

for (let [k, v] of MyObject) {
    console.log(`Here is key ${k} and here is value ${v}`);
}
```

**Comment by FieryCod** [comment]
Big thanks :+1:  Now it works like a charm. Could you please tell me how it is possible that the typescript does not bind it to an object?
```
MyObject[Symbol.iterator] = function* () {
    let properties = Object.keys(this);
    for (let i of properties) {
        yield [i, this[i]];
    }
}
```

**Comment by alitaheri** [comment]
That is because type is inferred **before** the iterator is added.

the type of MyObject is inferred to be:

```js
{
a: string;
b: string;
c: string;
d: string;
e: string;
f: string;
}
```

The **type** doesn't include an iterator. Typescript team is trying to fix this. take a look at their **Expando Type** [proposal](https://github.com/Microsoft/TypeScript/issues/10566).

**Comment by mhegazy** [comment]
thanks @alitaheri!
