### ISSUE TITLE
Object destructuring with default values and string literals.

### ISSUE THREAD

**Issue by denis-mludek** [Microsoft/TypeScript#10589]
**TypeScript Version:**  2.0

**Code**

```ts
interface Foo {
  bar?: 'baz' | 'boz'
}

function x(params: Foo) {
  // doesn't work
  const { bar = 'baz' } = params
}

function y(params: Foo) {
  // works
  const { bar = 'baz' as 'baz' } = params
}
```

**Expected behavior:**
To compile

**Actual behavior:** 
`error TS2322: Type 'string' is not assignable to type '"baz" | "boz"'. Type 'string' is not assignable to type '"boz"'.`

**Comment by mhegazy** [comment]
This should be working as expected in latest.
