### ISSUE TITLE
Type inference error for tuples

### ISSUE THREAD

**Issue by jzhang1** [Microsoft/TypeScript#10581]
**TypeScript Version:**  2.0.0

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
coords: [number, number][] = [[0,0], [1,1]];
transformed: [number, number][] = coords.map(([x, y]) => [x+1, y+1]);
```

**Expected behavior:**
This type checks

**Actual behavior:** 
coords.map is infered to have type number[][] instead of [number, number][]

**Comment by kitsonk** [comment]
Dupe of #6574

**Comment by DanielRosenwasser** [comment]
In the mean time, you can easily fix this by adding a type annotation to `map`'s callback.

```ts
coords.map(([x, y]): [number, number] => [x+1, y+1]);
```

**Comment by DanielRosenwasser** [comment]
Thanks for deduping @kitsonk!
