### ISSUE TITLE
Typescript should be able to provide globally visible symbols without a resource

### ISSUE THREAD

**Issue by akosyakov** [Microsoft/TypeScript#10587]
It is useful for tooling, see: https://github.com/Microsoft/vscode/issues/11014

**Comment by mhegazy** [comment]
The main issue is to know where to search. the server can not just search the whole disk.

We can add an OpenFolder / OpenProject command to open a folder. this way we know where to search.

**Comment by RyanCavanaugh** [comment]
Doesn't seem to be any big demand for this
