### ISSUE TITLE
Change type of "typeof" to a string literal union

### ISSUE THREAD

**Issue by RyanCavanaugh** [Microsoft/TypeScript#10594]
```ts
if (typeof x === 'funciton') { // no error
  // oops...
}
```

Modern JS engines appear to no longer use the "implementation-dependent" possibility in their `typeof` implementations and only return the "known" values. We should just encode this information into the type of `typeof` expressions -- we'll catch far more bugs where type names get misspelled in exchange for a very small number of type assertions in code that runs on exotic/ancient runtimes.

Reference: http://stackoverflow.com/questions/8940772/does-the-javascript-typeof-operator-ever-return-an-upper-case-string

**Comment by DanielRosenwasser** [comment]
One thing we could consider is adding better completion at that point (i.e. we don't give any right now) to mitigate this sort of problem without being overly restrictive.

**Comment by bterlson** [comment]
Seems good. Implementations are technically allowed to return any old string for exotic objects (eg. IE's `unknown` type for certain ActiveX Objects) but as you say, those days are mostly behind us. While the spec allows for such shenanigans, it contains the following non-normative statement:

> Implementations are discouraged from defining new typeof result values for non-standard exotic objects. If possible "object" should be used for such objects.

TS shouldn't concern itself with supporting theoretical hosts that do things the spec says not to do (even non-normatively).

**Comment by bterlson** [comment]
You could also forbid the sequence of characters "funciton" and catch 90% of my typos :-P

**Comment by RyanCavanaugh** [comment]
Duplicate of #9506 . #searchfail
