### ISSUE TITLE
Scala-like underscore for function arguments

### ISSUE THREAD

**Issue by mendrik** [Microsoft/TypeScript#10592]
**TypeScript Version:**  1.8.0 / nightly (2.0.0-dev.201xxxxx)

**Code**

``` [1, 2, 3].map((x) => x * 2) ``` could be written as ``` [1, 2, 3].map(_ * 2) ``` 

current objects' properties could be accessed like so 

``` let names = namedObjects.map(_.name) ```

**Comment by RyanCavanaugh** [comment]
`_` is a legal JS identifier so at a minimum there'd have to be some other syntax for this. This sort of proposal should generally be taken to ES Discuss since we don't like to add new expression-level syntax before a TC39 proposal goes to Stage 1.
