### ISSUE TITLE
TSServer: for JS projects workspace symbol route shouldn't contain types from any d.ts files

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#10606]
**TypeScript Version:**  1.8.10

- create a JS project (jsconfig.json)
- add a js file
- open in tsserver and request workspace symbols
- the returned symbols contain TS types that you can't use in JS (e.g. have no static members or can't be newed). Showing them doesn't make much sense in a JS project.

**Comment by mhegazy** [comment]
@zhengbli can we look to fix this in the https://github.com/Microsoft/TypeScript/tree/tsserverVS-WIP branch?

**Comment by zhengbli** [comment]
Sure, we can do this though I think defining the criteria of a "pure javascript project" is important. In theory the user can have mixed files (both .ts files and .js files) in a `jsconfig.json` project, for example during a migration process. For now I am ok with treating all `jsconfig.json` projects as "pure javascript project" but we may need to refine later.

**Comment by zhengbli** [comment]
This should be fixed in `tsserverVS-WIP` branch now.
