### ISSUE TITLE
Anyway to get static member of self class?

### ISSUE THREAD

**Issue by twoeo** [Microsoft/TypeScript#10602]
**TypeScript Version:**  2.0.0

**Code**

```ts
class MyClass{
    static MyStatic: string;

    test(){
        // anyway to get MyStatic without specify MyClass here?
        // as self::MyStatic in PHP
    }
}
```

**Why I want this?**
In React, you can specify a default props via:
```ts
class MyComponent extends React.Component<any,any>{
    static defaultProps = {
       //something here
    }
}
```

Wanna do some similar things.
So don't know how can get a static member without specify a class name. (just current class)

**Comment by HerringtonDarkholme** [comment]
`this.constructor` should work for that.

**Comment by twoeo** [comment]
@HerringtonDarkholme  It works! Thanks so much~

**Comment by bloadvenro** [comment]
@HerringtonDarkholme ok, but I `this.constructor._property` says _"Property '_property' does not exist on type 'Function'."_ Is it difficult to implement reference to static side of the class? It is usual to me to call static method/props from instance methods, but `this` points to the instance side.

**Comment by twoeo** [comment]
@bloadvenro Yes it's indeed, so I use this.constructor['XXX'] instead.

**Comment by aluanhaddad** [comment]
You could declare that the property exists which would be better style
