### ISSUE TITLE
Never type error in switch default

### ISSUE THREAD

**Issue by twoeo** [Microsoft/TypeScript#10600]
**TypeScript Version:**  2.0.0 beta

**Code**

```ts
interface Clazz{
	type: 'A' | 'B' | 'C'
}

let obj:Clazz = {
	type: 'A'
};

switch(obj.type){
  case 'A':
	console.log(obj.type);
    break;
  case 'B':
    console.log(obj.type);
    break;
  case 'C':
    console.log(obj.type);
    break;
  default:
    console.log(obj.type);
    break;
}

```

**Expected behavior:**
Compile successful.

**Actual behavior:** 
error TS2339: Property 'type' does not exist on type 'never'.
Can compile successfully without `default`

**Suggestion:**
Well I know never type is a good way.
But in this case, value may be comes from a web API response.
So wanna add some protection code here, but get an error.

**Comment by RyanCavanaugh** [comment]
I just type assert back to the original type. It's not clear how TS can best help you here -- it ought to be an error to access members on something that "shouldn't happen", but sometimes you do want to use the discriminant to throw an exception.

One option is to make a separate thing like
```ts
function throwBadKind(x: never): never {
  throw new Error('Unknown kind ' + (x as YourThing).kind);
}
```
so you can write
```ts
   default:
     return throwBadKind(type);
```

**Comment by twoeo** [comment]
Well as example above, if I use `obj['type']` in `default`, it will compile successfully.

**Comment by gcnew** [comment]
@twoeo This is likely to change soon if https://github.com/Microsoft/TypeScript/pull/10565 get merged in.
