### ISSUE TITLE
Error in Visual Studio when opening ts-files after upgrade to 2.0.0.0 Beta.

### ISSUE THREAD

**Issue by tkallsen** [Microsoft/TypeScript#10608]
**TypeScript Version:**  2.0.0.0 Beta (VS addin)

After upgrade from 1.8.6 to 2.0.0.0 Beta, Visual Studio 2015 started hanging and crashing. After uninstall of every Typescript version found in Programs and Features and re-install of 2.0.0.0 again I get an error when opening TS-files, directing me to look in ActivityLog.xml.

There the following entry is repeated ~20 times:

```
 <entry>
    <record>728</record>
    <time>2016/08/30 14:14:46.287</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.Hosting.JavaScriptException: Object doesn&apos;t support this action&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.Hosting.JavaScriptEngine.ThrowIfError(JavaScriptErrorCode error)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.Hosting.JavaScriptEngine..ctor(String text, String url, INativeEngine nativeEngine)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.ShimFactory.ShimFactory.Factory.ReinitializeEngineAndFactoryIfNeeded()&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.ShimFactory.ShimFactory.Factory.CreateOrUpdateShim(String createShimFunction, Object host, ShimAndServicesFileVersion&amp; shimInfo)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.ShimFactory.ShimFactory.CreateOrUpdateShim(String caption, String createShimFunction, Object host, ShimAndServicesFileVersion&amp; shimInfo)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.Proxies.AbstractProxy`1.InvokeShimMethod[T](String methodName, Object[] arguments)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.TypeScript.ScriptServices.Proxies.ClassifierProxy.TryAddLexicalClassifications(String lineText, Int32 lexState, Int32 offset, TypeScriptLexicalClassificationMap classificationMap, ITextSnapshot snapshot, List`1 tagSpans, Int32&amp; newEndOfLineState)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.Classifier.LexicalClassificationTaggerProvider.Tagger.AddLexicalClassifications(ClassifierProxy classifier, String text, Int32 lineNum, Int32 offset, ITextSnapshot snapshot, List`1 tagSpans)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.Classifier.LexicalClassificationTaggerProvider.Tagger.GetClassifications(NormalizedSnapshotSpanCollection spans, List`1 result)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.TypeScript.Features.Classifier.LexicalClassificationTaggerProvider.Tagger.GetTags(NormalizedSnapshotSpanCollection spans)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.&lt;GetTagsForBuffer&gt;d__38.MoveNext()</description>
  </entry>
```

It doesn't matter which TS-files I open. After the error I can continue with the file, but without code completion and syntax highlighting, and every character takes like 1 second to write.

**Comment by tkallsen** [comment]
After some reflecting of the typescript-dll it looks like it's trying to execute the js(?)-method "getEncodedLexicalClassifications" from C#, and failing since the shim doesn't support that methodname.

**Comment by mhegazy** [comment]
do you have a registry entry for `HKEY_CURRENT_USER\SOFTWARE\Microsoft\VisualStudio\14.0\TypeScriptLanguageService\CustomTypeScriptServicesFileLocation` ?

**Comment by mhegazy** [comment]
Do you have the latest Update 3 (https://msdn.microsoft.com/en-us/library/mt752379.aspx) installed?

**Comment by mhegazy** [comment]
and does it reproduce with TS 2.0 RC: https://blogs.msdn.microsoft.com/typescript/2016/08/30/announcing-typescript-2-0-rc/

**Comment by tkallsen** [comment]
I don't have _any_ registry entry for ```TypeScriptLanguageService``` under ```HKEY_CURRENT_USER\SOFTWARE\Microsoft\VisualStudio\14.0```. Installed TS 2.0.2.0 Beta (RC?) for Visual Studio, it took a while but still nothing in that registry location, and still the same error in VS.

After installation TypeScript still says 2.0.0.0 under About Visual Studio. Feels like my TypeScript-installation has been corrupted somehow.

**Comment by tkallsen** [comment]
And yes, I have KB3165756 installed.

**Comment by tkallsen** [comment]
More info, different Typescript-directories that I have on my machine:

Under my VS dir: ```Common7\IDE\CommonExtensions\Microsoft\TypeScript``` (Microsoft.VisualStudio.LanguageServices.TypeScript.dll is version 14.30828.1.0, commit 5eb4fb...). ```typescriptServices.js```is present here, and seems to contain the correct method ```getEncodedLexicalClassifications```.

Under ```C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0``` (TypeScript.Tasks.dll is version 14.30828.1.0, commit 5eb4fb...)

Under ```C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v15.0``` (TypeScript.Tasks.dll is version 14.30828.1.0, commit 5eb4fb...)

**Comment by tkallsen** [comment]
Under ```C:\Program Files (x86)\Microsoft SDKs\TypeScript``` I have directories for 1.0, 1.5, 1.6, 1.7, 1.8 and now 2.0. In the 2.0 directory there is a lot of d.ts-files, the tsc.exe/js compiler (version 2.0.2.0) and chakracore.dll (version 1.2.0.0).

**Comment by mhegazy** [comment]
can you give TS 2.0 - RC a try (https://blogs.msdn.microsoft.com/typescript/2016/08/30/announcing-typescript-2-0-rc/).

Also can you capture the install log with this version. the logs should be under `%TEMP%\dd_typescript*`. i will need the ones for the last installation (should have the time stamp of your install to TS 2.0 - RC)

**Comment by tkallsen** [comment]
Sorry, maybe I was a bit unclear earlier. I installed 2.0 RC yesterday (says 2.0.2.0 Beta on the installation screen). Here are the logs for that installation, as well as a few previous installation attempts (2.0.2.0 are the ones marked with *20160831080534*)

[dd_TypeScript_Dev14.zip](https://github.com/Microsoft/TypeScript/files/448871/dd_TypeScript_Dev14.zip)

**Comment by tkallsen** [comment]
I gave up, uninstalled everything VS on my machine and cleaned out the registry from everything I could find related to TS. Then reinstalled VS and installed TS 1.8... not touching TS 2.0 for a while.

**Comment by vitaldon** [comment]
When I've installed JetBrains ReSharper Ultimate 2016, the error which was popping up trying to open tsconfig.json has been eliminated.

Additionally, all highlights in ts file has been returned back.
