### ISSUE TITLE
Cannot infer from usage when generic class does not have a member or function parameter/return value of the generic type.

### ISSUE THREAD

**Issue by stephanedr** [Microsoft/TypeScript#10609]
**TypeScript Version:**  2.1.0-dev.20160830

**Code**

``` ts
interface A<T> {
    test(value: Object): value is T;
    // a: T;  // No error if uncommented.
    // or test(value: T | Object): value is T;
}

type B<T> = T | A<T>;

function f1<T>(b: B<T>) {}

function f2<T>(b: B<T>) {
    f1(b); // The type argument for type parameter 'T' cannot be inferred from the usage. Consider specifying the type arguments explicitly.
           //   Type argument candidate 'T' is not a valid type argument because it is not a supertype of candidate 'T'.
}
```

**Expected behavior:**
No error.

**Actual behavior:** 
The error reported with the code.

Note that this may seem same as #8619, however here, adding a member of type T, or a function with a parameter/return value of type T, solves the issue.

**Comment by mhegazy** [comment]
Please see https://github.com/Microsoft/TypeScript/wiki/FAQ#why-doesnt-type-inference-work-on-this-interface-interface-foot--- for more details.

**Comment by stephanedr** [comment]
But there is reference to T in "value is T".

**Comment by stephanedr** [comment]
Unless TS considers "value is T" as just a boolean?

**Comment by mhegazy** [comment]
There is not really a "use" of `T` that the compile can infer from. i.e. a parameter or a property. The main issue here is TS type system is structural, it tries to use the structure to know the type, these are things that would exist at runtime in your js code.
