### ISSUE TITLE
Formatting with the conditional operator

### ISSUE THREAD

**Issue by falsandtru** [microsoft/TypeScript#10614]
Bodies in the conditional operator should have the indent consistent with other formatting.

**TypeScript Version:**  2.0-rc

**Expected behavior:**

``` ts
function f() {
  return 0
    ? () =>
        () => 0
    : {
      };
}
```

**Actual behavior:** 

``` ts
function f() {
  return 0
    ? () =>
      () => 0
    : {
    };
}
```

**Comment by mhegazy** [comment]
note this is essentially the opposite of the request in https://github.com/Microsoft/TypeScript/issues/3676

**Comment by aluanhaddad** [comment]
@mhegazy I don't believe it is. I believe the request here is just that the expression after the arrow be indented an additional level below the arrow when placed on the following line. FWIW this works the expected way on the TypeScript playground. http://www.typescriptlang.org/play/#src=function%20g()%20%7B%0D%0A%09return%200%0D%0A%09%09%3F%20()%20%3D%3E%0D%0A%09%09%09()%20%3D%3E%200%0D%0A%09%09%3A%20%7B%0D%0A%09%09%7D%3B%0D%0A%7D
