### ISSUE TITLE
String.localeCompare should allow undefined locale

### ISSUE THREAD

**Issue by jeffreymorlan** [Microsoft/TypeScript#10618]
It's legal to pass `undefined` to String.localeCompare to use the default locale:
```ts
function caseInsensitiveCompare(a: string, b: string) {
    return a.localeCompare(b, undefined, { sensitivity: "base" });
}
```

In TS 2.0 with --structNullChecks enabled, this correct code is disallowed: "Argument of type 'undefined' is not assignable to parameter of type 'string'."

**Comment by mhegazy** [comment]
A PR would be appreciated.

**Comment by jeffreymorlan** [comment]
Another problem with localeCompare's and some other internationalization functions' declarations, is that although `string` and `string[]` are both legal ways to specify locale, a `string | string[]` union isn't accepted.

I'm submitting a PR: https://github.com/Microsoft/TypeScript/pull/10842
