### ISSUE TITLE
formatting test cases are duplicated

### ISSUE THREAD

**Issue by jeffreymorlan** [Microsoft/TypeScript#10611]
These two directories in 2.0-RC contain identical files:
* [src/harness/unittests/services/formatting/testCode/formatting](https://github.com/Microsoft/TypeScript/tree/master/src/harness/unittests/services/formatting/testCode/formatting)
* [src/harness/unittests/services/formatting/testCode/testCode/formatting](https://github.com/Microsoft/TypeScript/tree/master/src/harness/unittests/services/formatting/testCode/testCode/formatting)

**Comment by mhegazy** [comment]
A PR would be appreciated.

**Comment by Salasar** [comment]
I have deleted redundant path

**Comment by mhegazy** [comment]
thanks!

**Comment by mhegazy** [comment]
Fixed by https://github.com/Microsoft/TypeScript/pull/10661
