### ISSUE TITLE
Decorator Syntax Highlighting

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/TypeScript#10619]
**TypeScript Version:**  1.8.0

When Using decorators, I am getting a few syntax highlighting errors:

![decorators colors](https://cloud.githubusercontent.com/assets/1571806/18112364/a2510942-6eec-11e6-842b-e9fa5b0429aa.png)

**Comment by mhegazy** [comment]
already tracked in https://github.com/Microsoft/TypeScript-TmLanguage/issues/8
