### ISSUE TITLE
CanvasRenderingContext2D.imageSmoothingEnabled is missing from the d.ts files.

### ISSUE THREAD

**Issue by Aarilight** [Microsoft/TypeScript#10628]
**TypeScript Version:**  1.8, nightly, release candidate (2.0.2) all affected.
Currently targeting es6.

**Code**

```ts
var canvas = document.createElement("canvas");
var context = canvas.getContext("2d");
context.imageSmoothingEnabled = false;
```

**Expected behavior:**
`CanvasRenderingContext2D.imageSmoothingEnabled` should be a property representing whether the canvas should smooth the image or keep it pixelated. The browser vendor forms are present, but not the prefix-less form.

**Actual behavior:** 
Property `imageSmoothingEnabled` does not exist on type `CanvasRenderingContext2D`

**Comment by WanderWang** [comment]
https://github.com/Microsoft/TypeScript/issues/7846

take a look this issue

**Comment by RyanCavanaugh** [comment]
This is still experimental and is vendor-prefixed in several major browsers.

You can add it to the interface in your own file if you'd like to not support those browsers :wink:

```ts
interface CanvasRenderingContext2D {
  imageSmoothingEnabled: boolean;
}
```

**Comment by Aarilight** [comment]
I just figured this wouldn't be WAI because that logic doesn't really make too much sense.
There are 4 or 5 main browsers, right? Chrome, Firefox, IE, Opera, etc. They all have their own prefixed version. Therefore, each prefixed variant will only work on one browser. If you're going to support all of the prefixed variants, why not support the non-prefixed version? Future-proofed until you have to remove the others (if that even ever needs to happen), and for the people ahead of the game and already using the non-prefix version (me, making a game w/ electron: IE only chrome support necessary).
Also, chrome complains if you use the webkit variant vs unprefixed, and I refuse to leave warnings like that. That means it's *my* non-futureproof bug. And I don't like bugs.

As for the interface suggestion, I already added `imageSmoothingEnabled` to my es6 lib.d.ts, just figured it'd be nicer to point it out here as well, so I/others don't have to use a workaround. Can't say I agree with the final verdict, but I may be missing something. Anyway, thanks for your time.

**Comment by RyanCavanaugh** [comment]
The problem with providing the non-prefixed property is that it looks like any other property and people will be led to believe that it's standardized. The prefixed properties don't have this problem -- they're obviously vendor-specific and should be coded against appropriately.

**Comment by Aarilight** [comment]
Aha, I see. That makes sense. As someone who checks all browsers and caniuse sites and stuff when developing for webscale applications, that didn't cross my mind. I'm assuming you've thought of simply providing documentation notes? Or maybe info blurbs when compiling properties like that, "This property is not supported in all browsers." Or something? Just a thought.

**Comment by dannyfritz** [comment]
When I add the interface extensions I get an error. TS 2.1.3
```ts
interface CanvasRenderingContext2D {
  imageSmoothingEnabled: boolean;
}
```
```
Error TS90010: Type 'CanvasRenderingContext2D' is not assignable to type 'CanvasRenderingContext2D'. Two different types with this name exist, but they are unrelated.
  Property 'imageSmoothingEnabled' is missing in type 'CanvasRenderingContext2D'
```

Should I be using `extends` or something? I'm wondering why TS isn't combining my 2 interfaces because they have the same name.

**Comment by RyanCavanaugh** [comment]
@dannyfritz alternatively inside a `declare global {` block
