### ISSUE TITLE
.d.ts files not excluded from completion

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/TypeScript#10623]
**TypeScript Version:**  1.8.10

I have 2 `.d.ts` files that get created from `tsc`, and are placed inside my `build` folder. So, I added them to the `exclude` list so they get ignored for completion, but they are still getting parsed and I am getting a **Duplicate identifier** error. If I delete the files and restart the editor it works fine, until I rebuild and restart the editor.

**tsconfig.json**

```ts
{
    "compilerOptions": {
        "target": "es6",
        "module": "commonjs",
        "outDir": "./build",
        "rootDir": "./src",
        "removeComments": true,
        "experimentalDecorators": true,
        "declaration": true,
        "watch": true
    },
    "exclude": [
        "node_modules",
        "build/gameEditor.d.ts",
        "build/gameEngine.d.ts",
        "bin"
    ],
    "compileOnSave": true
}
```

**Code**

![already defined](https://cloud.githubusercontent.com/assets/1571806/18114486/0c6192f6-6efd-11e6-8597-c2f5043ff5cb.png)

**Comment by RyanCavanaugh** [comment]
Assuming you figured out what was going on, otherwise please reopen. Thanks!

**Comment by TheColorRed** [comment]
The issue was that I had this in the same project as the actual code, so it was trying to parse it twice.

```ts
/// <reference path="./path/to/my.d.ts"/>
```

My solution was to put the reference in my gulp file instead, since that is why I had references in the first place.

So now I have this, where the `.d.ts` files were in a `.ts` file that just referenced the `.d.ts` files:

```ts
gulp.task('compile-game-editor', ['compile-editor'], function () {
     return gulp.src([
        './build/gameEditor.d.ts',
        './build/gameEngine.d.ts',
        './typings/game-engine/game-engine.d.ts',
        './src/GameEditor/**/*.ts',
     ]).pipe(gulptsc({
        module: 'commonjs',
        target: 'es6',
        removeComments: true,
        experimentalDecorators: true
    })).pipe(gulp.dest('build/SpyNgin/'));
});
```
