### ISSUE TITLE
Current (upcoming) state of triple slash reference API

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/TypeScript#10635]
Could you please elaborate what is upcoming (due to TS 2.0 upcoming release) state of triple slash reference API for types dependency management? 

When/where it still should be used and should be be avoided if possible? Probably new docs should make an ascent on this.

**Comment by mhegazy** [comment]
issue https://github.com/Microsoft/TypeScript-Handbook/issues/348 tracks adding docs for this.

**Comment by whitecolor** [comment]
@mhegazy could you elaborate in couple of sentences what is the current state of it?

**Comment by mhegazy** [comment]
Fixed in https://github.com/Microsoft/TypeScript-Handbook/pull/439
