### ISSUE TITLE
Invalid field initialization order in descendant class

### ISSUE THREAD

**Issue by chebum** [Microsoft/TypeScript#10634]
**TypeScript Version:**  1.8.7

**Code**

```ts
class A {
	a = true;	
	constructor() {
	}
}

class B extends A {
	b = true;
	constructor() {
		super();
	}
}

new B();
```

**Expected behavior:**
The **b** field should be set to true, then **super()** called.

**Actual behavior:** 
The **super** constructor is called first, then **b** field is initialized.

**Generated JS**
```js
var B = (function (_super) {
    __extends(B, _super);
    function B() {
        _super.call(this);
        this.b = true;
    }
    return B;
}(A));
```

**Comment by RyanCavanaugh** [comment]
This is not how classes work. In ES6 it is *illegal* to use `this` before calling `super`.

See also #1617
