### ISSUE TITLE
strictNullChecks mode - Variable is used before being assigned.

### ISSUE THREAD

**Issue by aliai** [Microsoft/TypeScript#10641]
**TypeScript Version:**  nightly (2.0.2)

In strictNullChecks mode only:

**Code**

```ts
const CONFIG = {
  foo: '',
  setFoo: function(foo: string) {
    // accessing (reading or writing) CONFIG.foo is not allowed!
    CONFIG.foo = foo;  // <-- Error: Variable 'CONFIG' is used before being assigned.
  }
};
```

**Expected behavior:**

I don't see why this is not a valid statement.

**Actual behavior:** 

Trying to access any *defined* member of `CONFIG` in a method, defined within the object itself, raises an error: *Variable 'CONFIG' is used before being assigned.*

**Comment by yuit** [comment]
Slightly related the following will also issue similar error:
```typescript
const helper = function<T>(t: T[]) {
        helper(t.slice(1));
}
```

**Comment by ahejlsberg** [comment]
@yuit I have a fix for this, will be putting up a PR shortly.
