### ISSUE TITLE
Type inferences with overloads have failed

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#10645]
**TypeScript Version:**  master

**Code**

```ts
function f<a, b>(g: (a: a) => b, a: a): b {
  return g(a);
}
var g = <{(data: number): number; (data: string): string;}>((p: number) => p);
f(g, ''); // string
f(g, 0); // error, should return number
```

**Expected behavior:**

```
$ node built/local/tsc.js --noEmit --lib es6 --strictNullChecks --noImplicitAny index.ts
```

**Actual behavior:** 

```
$ node built/local/tsc.js --noEmit --lib es6 --strictNullChecks --noImplicitAny index.ts
index.ts(6,1): error TS2453: The type argument for type parameter 'a' cannot be inferred from the usage. Consider specifying the type arguments explicitly.
  Type argument candidate 'string' is not a valid type argument because it is not a supertype of candidate 'number'.
```

**Comment by mhegazy** [comment]
@sandersn can you take a look

**Comment by falsandtru** [comment]
any updates?

**Comment by sandersn** [comment]
No, I haven't had a chance to look at this yet.

**Comment by sandersn** [comment]
This is, unfortunately, how TypeScript is intended to treat overloads during type inference. Type inference is not smart enough to infer an overloaded call signature, so it just chooses the last one. If you reverse the order of declarations, you will see that the error switches to the other call.

Adapted from the spec, section 3.10.6 (Type Inference):

> When comparing call signatures, signatures in *S* correspond to signatures in *T* pairwise in declaration order. If *S* and *T* have different numbers of signatures, the excess *first* signatures in declaration order of the longer list are ignored.

In the example code, *S* is `{ (data: number): number; (data: string) => string }` and *T* is `{ (a: a) => b }`. That means that type inference always returns `a=string, b = string`.

**Comment by falsandtru** [comment]
I see, thx!
