### ISSUE TITLE
Improve playground run

### ISSUE THREAD

**Issue by normalser** [microsoft/TypeScript#10646]
It would be helpful if someone could run the code that has `debugger` keyword in it and be able to have it work by browser.

Right now `Run` command will open new tab and if you open the `devtools` and try to refresh hoping for `debugger` to kick in - it will not work - because reloading will clear the page content.

Ideally if one could open devtools @ playground and be able to run the script on the playground page (instead of opening new tab)

**Comment by RyanCavanaugh** [comment]
> Ideally if one could open devtools @ playground and be able to run the script on the playground page (instead of opening new tab)

Definitely this. I really dislike the current 'Run' behavior and basically never use it for this reason

**Comment by brianbishop** [comment]
You need to use the following format to allow for debugging

```javascript
// ..... your classes/logic etc goes here,  then add a run() funciton
function run(): void{
    debugger;
    const dc1: DemoClass= new DemoClass();
    const dc2: DemoClass= new DemoClass();    
}

let button = document.createElement('button');
button.textContent = "Run App";
button.onclick = function() {
    run();
}

document.body.appendChild(button);
```

**Comment by RyanCavanaugh** [comment]
This is complete in the v3 playground now
