### ISSUE TITLE
API improvements for tsserver/services

### ISSUE THREAD

**Issue by anstarovoyt** [Microsoft/TypeScript#10647]
Hi. I am working on integration with tsserver (in fact we are using 'tsserverlibrary.js') in IDEA / WebStorm.

It would be great add some new functionality to the service. It will allow us significantly improve the integration.
1. We need a service method which will return all detailed completion items. Similar to "#getCompletionsAtPosition" but with detailed information. Right now I have to use 'pure' information or call slow  "#getCompletionEntryDetails" for all items.
2. (Optionally) We need an option to get navigation information for a whole file. I am not sure that it's the best solution but a similar integration works fine for Dart language. We have a lot of built-in typescript inspections and all the inspections use the navigation information.

**Comment by mhegazy** [comment]
> "#getCompletionsAtPosition" but with detailed information. Right now I have to use 'pure' information or call slow "#getCompletionEntryDetails" for all items.

the issue is not that `getCompletionEntryDetails` is slow, the issue is that generating all that information is slow. so if getCompletionsAtPosition returned all information for all entries, it is going to be unusable. think for instance for a global completion,. in a typical project, this would be thousands of symbols. doing a full resolve on these can take in the order of 800-1000 ms.

the idea here is that user usually wants information about a few items in a completion list. so instead of spending all the time to generate them then not using them, we would generate them on demand with a call to getCompletionEntryDetails.

> (Optionally) We need an option to get navigation information for a whole file. I am not sure that it's the best solution but a similar integration works fine for Dart language. We have a lot of built-in typescript inspections and all the inspections use the navigation information.

can you elaborate on what you mean by "navigation" information.

**Comment by anstarovoyt** [comment]
@mhegazy 
>the idea here is that user usually wants information about a few items in a completion list. so instead of spending all the time to generate them then not using them, we would generate them on demand with a call to getCompletionEntryDetails.

Yes, it is a good point. In fact I want detailed information for (example) 10 first items. May be we can pass several strings to #getCompletionEntryDetails?

**Comment by anstarovoyt** [comment]
>can you elaborate on what you mean by "navigation" information.

**Comment by angelozerr** [comment]
> Hi. I am working on integration with tsserver (in fact we are using 'tsserverlibrary.js') in IDEA / WebStorm.

@anstarovoyt  I know it's out of the scope of this issue, but perhaps you could be interested with https://github.com/angelozerr/typescript.java which provides https://github.com/angelozerr/typescript.java/tree/master/core to communicate with tsserver with Java client. It should be fantastic if we could have a "commons" tsserver Java client for any Java IDE (WebStorm, Eclipse, Netbeans, etc)

**Comment by mhegazy** [comment]
> Yes, it is a good point. In fact I want detailed information for (example) 10 first items. May be we can pass several strings to #getCompletionEntryDetails?

sure. this sounds reasonable, though I would say the perf for a small number of entries would be marginally better than what you would get with multiple requests.

**Comment by mhegazy** [comment]
is this still needed?
