### ISSUE TITLE
Async map iteration does not work as expected

### ISSUE THREAD

**Issue by Roam-Cooper** [Microsoft/TypeScript#10655]
**TypeScript Version:**  1.8.10

**Code**

```ts
var map = new Map<string, any>();
map.set('abc', 123);
map.forEach(async (value)=>{
await DoSomethingAsyncWithValue(val);
});
```

**Expected behavior:**
Should asynchronously iterate over the map.

**Actual behavior:** 
Synchronously iterates over the map.

There are no compilation errors from this code, so a developer would assume it'd work the same as an Array forEach.

**Comment by Arnavion** [comment]
>Expected behavior:
>Should asynchronously iterate over the map.

That would be a violation of the ES6 spec, and is outside of TS's control at any rate.

>There are no compilation errors from this code, so a developer would assume it'd work the same as an Array forEach.

That is technically legal from both runtime perspective and compiler perspective.

From runtime's point of view, the callback given to `forEach` is returning a `Promise` that `forEach` ignores and throws away.

From TS compiler's point of view, `forEach` excepts a callback that returns `void`, whereas the actual callback is returning a `Promise`. But it is legal to assign callbacks that return non-`void` to callbacks that return `void`. (This is useful for writing single-expression lambdas where one just wants the result of the expression to be ignored.) So there is nothing to raise a compiler error about.

Perhaps you could create a tslint rule for this, something like "Async lambda used with Array#forEach may not work as expected."

**Comment by yortus** [comment]
@Roam-Cooper you could try something like this:

```ts
async function foo() {
    var map = new Map<string, any>();
    map.set('abc', 123);

    for (let [key, val] of map) {
        await doSomethingAsyncWithValue(val);
    }
}
```

**Comment by Roam-Cooper** [comment]
I've already solved it with a for..of loop of course, just didn't know es6
spec doesn't include asynchronous map iteration. :)
