### ISSUE TITLE
New Website Logo: Trackmeet

### ISSUE THREAD

**Issue by deherle** [Microsoft/TypeScript#10653]
Please fill the following out:

- Name: Trackmeet
- Homepage url: https://www.gotrackmeet.com
- Brand Guidelines/Licensing: None
- Logo: https://www.gotrackmeet.com/static/images/trackmeet-globe-large.png

**Comment by deherle** [comment]
Hi Mohamed,

 

I saw this issue was closed but didn’t see our logo on the “Friends of Typescript” page yet. Is it being added?

 

We use Typescript as the foundation for all work we do on our web and embedded tiers and would love to be included here!

 

Regards,

 

Darin

**Comment by mhegazy** [comment]
We push to the site periodically; I have added the logo to our site repo, it should be visible on the live site next time we push it, hopefully in a few days.

**Comment by deherle** [comment]
Awesome, thanks Mohamed!
