### ISSUE TITLE
Erroneous documentation for gulp+babelify at www.typescriptlang.org

### ISSUE THREAD

**Issue by Ivanca** [Microsoft/TypeScript#10656]
Erroneous documentation snippet for gulp and babelify at http://www.typescriptlang.org/docs/handbook/gulp.html

The following line:
```js
.transform('babelify')
```
should be:
```js
.transform('babelify', {presets: ['es2015'], extensions: ['.js', '.ts']})
```
Otherwise it doesn't work (babelify does *nothing* without such configuration)

**Comment by macklinu** [comment]
@Ivanca It looks like this document is located here: https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/tutorials/Gulp.md

Perhaps opening the issue in the Typescript-Handbook repo or opening a PR with your suggested change is the next step?

**Comment by Ivanca** [comment]
MM I see that there is already a PR for this but it hasn't been accepted
https://github.com/Microsoft/TypeScript-Handbook/pull/289/commits/be76cd21e52e13c4f5120836c853216db20f5000

Oh well, In the meanwhile hundreds of people must be wondering why their transpiling doesn't work after a tutorial supposedly written by people at Microsoft.
