### ISSUE TITLE
Limit/restrict properties count on the object

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/TypeScript#10667]
This allows to set type of indexing key
```js
interface A {
  [index: string]: any;
}
```
But it is possible to restrict limit amount of this keys? Say get only valid object with single prop in it.

**Comment by mhegazy** [comment]
no. what is the scenario you are trying to achieve?

**Comment by whitecolor** [comment]
Well as a JS tend to be a wonderland of freedom we may design such interface, this a particular case:
```js
model: 'Book',
query: [
  {findOne: [{author: `Alexey Tolstoy'}] },
  {select: ['title', 'author', 'pages']},
  {orderBy: ['pages']}
]
```
So each element of the query (which is suppose further to be translated in to chain query) is an object with only one prop (which is a chain call method) and value is params for chain method.

**Comment by kitsonk** [comment]
While not complete:

```typescript
type QueryCommand = { findOne: any[] } | { select: string[] } | { orderBy: string[] };
interface Query {
  model: string;
  query: QueryCommand[];
}
```

You would still need to enumerate the valid query commands.

Also, Gitter, StackOverflow and IRC are better locations for general questions like this.

**Comment by whitecolor** [comment]
@kitsonk Thanks for the hint, actually I asked this question on stackoverlfow before but often it is hard there to get appropriate answers on topics like that http://stackoverflow.com/questions/39190154/typescript-restrict-number-of-objects-properties

besides this problem may refer to some more general in TS capabilities to provider needed type definitions.
