### ISSUE TITLE
Dynamic function typings based on string params passed

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/TypeScript#10660]
Probably this is an issue of dynamic typing, didn't find exact here in the issues (probably you will point to).

Is it possible to do typing and achieve types flow of such thing:
```js
function getProp(prop: string, obj: any) {
  return obj[prop]
}  

let obj: { id: number } = { id: 1 }

getProp('id', obj). // there should flow number type
```

**Comment by gcnew** [comment]
Rumor has it that it was once considered in a distant whimsical land, where unicorns walk freely under rainbows and mighty wombats hold the sky. It is, though, considered intractable for the feeble human beings.

Use https://github.com/Microsoft/TypeScript/issues/1295 as a starting point.

**Comment by whitecolor** [comment]
@gcnew thanks for pointing on that

**Comment by mhegazy** [comment]
indeed duplicate.
