### ISSUE TITLE
Gracefully parse 'super' with type arguments

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#10677]
From test `superWithTypeArgument3`:

![image](https://cloud.githubusercontent.com/assets/972891/18189083/4fb3c22a-706c-11e6-9dc4-9704d80c4e39.png)

We can just parse and throw away the results. If we're certain that this could be a call, we should just parse  as a `super()` invocation to avoid downstream errors.

**Comment by Igorbek** [comment]
Just curious, why that would be needed? `super` for the derived class is a concrete type, so what would that type arguments in `super` mean?

**Comment by RyanCavanaugh** [comment]
+1 to @Igorbek 's comment, what's the intent here?

**Comment by kitsonk** [comment]
Sorry to be obtuse as well, but since the generics aren't required on the constructor, why would they be required on the super?  The  It would be like having to write this, which isn't logical:

```typescript
class D extends C  {
    constructor<T>() {
        super<T>();
    }
}
```

**Comment by DanielRosenwasser** [comment]
The intent is that instead of letting new users grapple with parse errors, we should give the most helpful experience we can. The fact that we understand why this doesn't work isn't indicative that newer users will immediately pick up on it.

**Comment by RyanCavanaugh** [comment]
Just to clarify, sometimes we change the parser to accept things we know aren't legal so that the errors are easier to understand. For example, this is never legal:
```ts
public class Foo {
  
}
```
A naive parser would just say "Unexpected token 'class'" but instead we parse it anyway and then later issue a more helpful "Can't use that modifier here" error

**Comment by DanielRosenwasser** [comment]
Thanks for articulating. I could've probably been a little clearer on that. 😄
