### ISSUE TITLE
Function with varargs parameter emits inefficient code

### ISSUE THREAD

**Issue by jxtps** [Microsoft/TypeScript#10672]
**TypeScript Version:**
Whatever was running in the [playground](https://www.typescriptlang.org/play/index.html) as of Sep 1, 2016 (1.8.0?)

**TS Input - multiple parameters - [playground](https://www.typescriptlang.org/play/index.html#src=function%20hello(name%3Astring%2C%20...strings%3AArray%3Cstring%3E)%3Avoid%20%7B%0D%0A%20%20console.log(...strings)%3B%09%0D%0A%7D)**
```ts
function hello(name:string, ...strings:Array<string>):void {
  console.log(...strings);	
}
```

**Expected JS output:**
```js
function hello(name) {
    var strings = arguments.slice(1);
    console.log.apply(console, strings);
}
```

**Actual JS Output:** 
```js
function hello(name) {
    var strings = [];
    for (var _i = 1; _i < arguments.length; _i++) {
        strings[_i - 1] = arguments[_i];
    }
    console.log.apply(console, strings);
}
```

**TS Input - single vararg parameter - [playground](https://www.typescriptlang.org/play/index.html#src=function%20hello(...strings%3AArray%3Cstring%3E)%3Avoid%20%7B%0D%0A%20%20console.log(...strings)%3B%09%0D%0A%7D)**
```ts
function hello(...strings:Array<string>):void {
  console.log(...strings);	
}
```

**Expected JS output:**
```js
function hello() {
    var strings = arguments;
    console.log.apply(console, strings);
}
```

**Actual JS Output:** 
```js
function hello() {
    var strings = [];
    for (var _i = 0; _i < arguments.length; _i++) {
        strings[_i - 0] = arguments[_i];
    }
    console.log.apply(console, strings);
}
```

**Points**
 - JS output should leverage [Array.prototype.slice](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice) instead of emitting a full copy loop. 
 - JS output should ideally not copy `arguments` if `arguments` is not otherwise used / referenced in the function and the vararg parameter is the only parameter to the function.

**Comment by RyanCavanaugh** [comment]
The reason we don't do it that way is because it doesn't work.

![image](https://cloud.githubusercontent.com/assets/6685088/18177288/72f8e79e-702e-11e6-8262-db7d07598320.png)

You can also refer to #3219
