### ISSUE TITLE
Typescript compiler ignores wrong parameter type in callback

### ISSUE THREAD

**Issue by 40rn05lyv** [Microsoft/TypeScript#10682]
**Code**

```ts
// A *self-contained* demonstration of the problem follows...
class A<T> {
    methodA(callback: (value : T) => void){
    }
}
class B<T>{}

var a1 = new A<String>();
a1.methodA((value : number) => { });

var a2 = new A<B<String>>();
a2.methodA((value : number) => { });
```

**Expected behavior:**
Both invocations of methodA have compiler warning.

**Actual behavior:** 
Only first invocation of methodA have compiler  warning.

**Comment by RyanCavanaugh** [comment]
Unused generic type parameters have no impact on the type of the object. See https://github.com/Microsoft/TypeScript/wiki/FAQ#why-is-astring-assignable-to-anumber-for-interface-at--

**Comment by 40rn05lyv** [comment]
@RyanCavanaugh Generic type parameter is not unused. It's used in callback: **callback: (value : T) => void**

Also, I'm not trying to compare 2 objects or assign one object to other, I just call a method. Moreover, validation works ok when for the first statement!

**Comment by mhegazy** [comment]
> Generic type parameter is not unused. It's used in callback: callback: (value : T) => void

It is not used in `B<T>`. that is why it works for the first and not the second.

change the declaration of `B` to be:

```ts
class B<T>{
    _a: T
}
```

and you should see the expected error.
