### ISSUE TITLE
tsc shows errors for different versions of the same library in d.ts files.

### ISSUE THREAD

**Issue by markbook2** [Microsoft/TypeScript#10680]
**TypeScript Version:** 
```
tsc --version
Version 2.1.0
```

File main.ts:
```
/// <reference path="jquery-1.10.d.ts"/>

import $ from "jquery"
import {myFunction} from "./my-module"

$('#id').click(function () {});
```

File my-module.ts:
```
/// <reference path="jquery-2.0.d.ts"/>

import $ from "jquery"

export function myFunction() {}
```

Files jquery-1.10.d.ts and jquery-2.0.d.ts are files with the same content, just for testing, but it can be slightly different for different version of the jQuery, and theirs content is latest version of the jquery.d.ts from the DefinitelyTyped (https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/master/jquery/jquery.d.ts):
```
 md5sum jquery-1.10.d.ts jquery-2.0.d.ts
7ef0067d2faf006343aa95157f492867  jquery-1.10.d.ts
7ef0067d2faf006343aa95157f492867  jquery-2.0.d.ts
```

Now try to compile the main.ts with:
```
tsc --moduleResolution node -t ES5 main.ts
```

**Expected behavior:**
No errors

**Actual behavior:** 
```
jquery-2.0.d.ts(616,5): error TS2374: Duplicate string index signature.
jquery-2.0.d.ts(2863,5): error TS2374: Duplicate string index signature.
jquery-2.0.d.ts(2864,5): error TS2375: Duplicate number index signature.
jquery-2.0.d.ts(3237,5): error TS2300: Duplicate identifier 'export='.
my-module.ts(3,8): error TS1192: Module '"jquery"' has no default export.
jquery-1.10.d.ts(3237,5): error TS2300: Duplicate identifier 'export='.
main.ts(3,8): error TS1192: Module '"jquery"' has no default export.
```
I.e. you see batch of errors. It seems like tsc does not allow use different version of the .d.ts files with the same declarations for the included module/file. However I think it should not produce errors because the included module can use different version of the same library as shown above with file names - jquery-1.10.d.ts and jquery-2.0.d.ts.

**Comment by mhegazy** [comment]
Well. there are multiple declarations for the same thing. it does not know which one to take. please note that these all live in the same scope (global). so if you use `$` in one file, which version do you mean of JQuery? the `/// <reference` does not restrict the scope.

The main issue here is that the Jquery declarations are written as global declarations and not as a module. modules provide isolation, and you can have different versions of the same module in different files without them conflicting, as each has its own scope. but global are not.

so the fix here is to update the jquery (and its extensions) to be written as UMD modules (see https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Modules.md#umd-modules) this way you can use multiple versions with them in the same file. I have updated angularjs declarations to do just that, see https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types-2.0/angular/index.d.ts#L17-L21, JQuery.d.ts will need the same treatment.

**Comment by markbook2** [comment]
Ok, thank you for reply. I meant that the `/// reference` does not restrict the scope, it can cause the problem. As it can be possibly fixed with UMD, I should discover the UMD modules and the suggested approach. So I am closing this issue for now.
