### ISSUE TITLE
Fix {Map,WeakMap}.prototype.set method

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#10694]
The second parameter is specified as required by the interface of spec.

**TypeScript Version:**  master

**Code**

```diff
interface Map<K, V> {
-    set(key: K, value?: V): this;
+    set(key: K, value: V): this;
}

interface WeakMap<K, V> {
-    set(key: K, value?: V): this;
+    set(key: K, value: V): this;
}
```

http://www.ecma-international.org/ecma-262/6.0/#sec-map.prototype.set
http://www.ecma-international.org/ecma-262/6.0/#sec-weakmap.prototype.set

**Comment by kitsonk** [comment]
Actually, the spec indicates that a lack of value is not a run-time error (as well as in [practice](https://jsfiddle.net/pyga0wbp/)).  For both, it would be a mechanism to clear a value without deleting the key, therefore freeing the value up for GC (while it does seem a bit silly and is likely not a good practice):

```typescript
const m = new Map();
const obj = {};
const value = {};
m.set(obj, value);
m.set(obj); // key still in map, value is `undefined`, value could be GC'ed
```

**Comment by mhegazy** [comment]
as @kitsonk mentioned, it is a valid signature per the spec.

**Comment by falsandtru** [comment]
no, it is the behavior, not the signature. the spec defined that signature `Map.prototype.set ( key , value )`, not `Map.prototype.set ( key [, value] )`. it means `value` is not optional in the signature.

**Comment by mhegazy** [comment]
JS allows not passing parameters. so if `value` is not passed is implicitly `undefined`. most of these declarations are written by reading the spec and making a call if it should be there or not. from reading the spec again, so not see why it is not valid.

**Comment by falsandtru** [comment]
because current definitions make the following bug.

```ts
var m = new Map<number, number>();
m.set(0);
var v: number = m.has(0) ? m.get(0)! : 0;
v.toFixed(); // typeof v is number, but runtime value is undefined.
```

**Comment by mhegazy** [comment]
well.. you banged your way into this one. if you remove the bang in `m.get(0)!` you should get `number|undefined`, which is correct.

keep in mind that `m.get("some random key")` would return `undefined` anyways.

**Comment by mhegazy** [comment]
i guess you are right. we should not allow `undefined` to get there unnoticed. A PR would be appreciated.

**Comment by falsandtru** [comment]
Thanks @mhegazy!
