### ISSUE TITLE
Unsafe overload signature merging

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#10701]
`(T | Promise<T>)[]` type cannot assign to `T[] | Promise<T>[]` type. Is this an intended behavior?

**TypeScript Version:**  master

**Code**

``` ts
function f(): void[]
function f(): Promise<void>[]
function f(): (void | Promise<void>)[] { // this return type must be `void[] | Promise<void>[]` for type safety.
  return [];
}
```

```
$ node built/local/tsc.js --noEmit --lib es6 --strictNullChecks index.ts
```

**Expected behavior:**

error

**Actual behavior:** 

no error

**Comment by falsandtru** [comment]
@DanielRosenwasser @mhegazy can you take a look?

**Comment by RyanCavanaugh** [comment]
Those types aren't equivalent. `(string | number)[]` could be invoked with `.push(3, "");` while this is not true of `string[] | number[]`.

**Comment by RyanCavanaugh** [comment]
One confusing thing I should clarify is that the return type check for a function implementation may appear "backward" from what you might intuitively expect.

**Comment by zhengbli** [comment]
Both `T[]` and `Promise<T>[]` are assignable to `(T | Promise<T>)[]`, so the base signature overload should be valid. It's just you can choose to make it `T[] | Promise<T>[]` as well. This unsafety is not introduced by TS.

**Comment by falsandtru** [comment]
`T[]` and `Promise<T>[]` are assignable to `(T | Promise<T>)[]`, but `(T | Promise<T>)[]` is not splittable to `T[]` and `Promise<T>[]`. So it assignability make bugs.

 cc @ahejlsberg

**Comment by mhegazy** [comment]
the rules for comparing overloads to implementation signature are intentionally loose. this unfortunately allow such patterns.
