### ISSUE TITLE
Make class private members accesible to member-class expressions.

### ISSUE THREAD

**Issue by saabi** [Microsoft/TypeScript#10707]
Very simply put, doing this right now emits an error;

```typescript
class A {
	private pm;
	static B = class C {
		m ( a: A ) {
			return a.pm;  // error: private member access not allowed at present.
		}
	}
}
```
I think it would be very useful and perhaps a simple modification to allow class C to access private members in class A.

**Comment by DanielRosenwasser** [comment]
This has always been the behavior I've expected, but I don't remember if there was a specific reason we didn't choose to do this.

**Comment by saabi** [comment]
It would essentially mirror the semantics in Java, C# and C++, which allow it for a good reason. It's a good way to expose functionality.

A Collection object could create an Iterator object with access to its private members for example. We already lack `friend` or `internal` access modifiers in typescript, with no plans to add it. 

I think this would be a good compromise that gives some of the benefits.

**Comment by mhegazy** [comment]
this is already working as described. private members are accessible within the body of the class. this includes class expressions, functions, methods, etc..

```cmd
c:\ts>tsc --v
Version 2.1.0-dev.20160901

c:\ts>type a.ts
class A {
    private pm;
    static B = class C {
        m(a: A) {
            return a.pm;  // error: private member access not allowed at present.
        }
    }
}
c:\ts>tsc a.ts

c:\ts>echo %ERRORLEVEL%
0
```

**Comment by saabi** [comment]
Ahh that's great. I only checked in the current version 1.8.10.
