### ISSUE TITLE
Error about null files property in tsconfig.json

### ISSUE THREAD

**Issue by Matiszak** [Microsoft/TypeScript#10705]
**TypeScript Version:**  2.0RC (2.0.2.0)

I found really mysterious error.

I started by having problems with my TS 1.8 so i moved to 2.0RC. in 2.0 i encountered completely new error:
![image](https://cloud.githubusercontent.com/assets/20770017/18232328/c2a20108-72cd-11e6-8e68-d0650cbe947e.png)
I tried asking in asp/Tooling https://github.com/aspnet/Tooling/issues/760) but i found this github. Being intrested i looked into TS 2.0 code and from what i see my error should never appear because i don't have any "files" property in my tsconfig.json file : 
```json
{
    "compilerOptions": {
        "declaration": false,
        "removeComments": true,
        "noImplicitAny": true,
        "noImplicitReturns": true,
        "noImplicitUseStrict": false,
        "noFallthroughCasesInSwitch": true,
        "noEmitOnError": true,
        "sourceMap": true,
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "pretty": true,
        "allowUnreachableCode": false,
        "allowUnusedLabels": false,
        "target": "es5",
        "module": "commonjs",
        "outDir": "../wwwroot"
    },
    "compileOnSave": true
}
```

When i add "files" property and set it to [] the compilation works but i don't want to list every file i have to use. I tried reinstalling TS 2.0 RC but the problem doesnt want to go away. I work now on TS 1.8 but my visualstudioonline continous integration doesn't want to work because of (i suppose)the same error(i specifically configuered xproj to use 1.8 and i know visualstudioonline CI uses TS 1.8 but the error still exists while on my local machine it doesn't.)

Log from visualstudioonline:
[1_Build.txt](https://github.com/Microsoft/TypeScript/files/454002/1_Build.txt)

**Expected behavior:** Successful compilation

**Actual behavior:** Error

**Comment by mhegazy** [comment]
i can not reproduce this on TS 1.8 or TS 2.0. do you see this with any project? or a specific project? if any project, can you share a sample i can try locally?

**Comment by Matiszak** [comment]
Here's the project(filedropper because github doesn't accept the zip)
http://www.filedropper.com/project_11

I can also give you access to my project repo and my tsc.exe files if you want.

**Comment by mhegazy** [comment]
mmm. i just tried, and tsc.exe returns 0 on `MGMS\src\MGMS.Web\app\tsconfig.json`. so something else is going on here.

do you see the same issue on diffrent machines? what is the version of your OS? what is the version of IE?

**Comment by Matiszak** [comment]
I haven't tried on different machine, i will do that as soon as i can but if it counts this error occurs as well on visualstudioonline repository(i posted log in my first post) when i do continous integration.

**Comment by Matiszak** [comment]
Here is link to my typescript 1.8/2.0 libaries. Are you able to reproduce an error using them ? 
http://www.filedropper.com/typescript

OS: Windows 8
IE: 10.0.9200.17607

**Comment by mhegazy** [comment]
works fine for me still.

**Comment by Matiszak** [comment]
I don't know what to say, it's that user-developer case when something doesn't work in my enviroment. I'm sorry but I'm very occupied right now but as soon as i will have time i will try to run it directly from myself compiled tsc.js. Now i'm at work where i can test it too but no time so far.

**Comment by mhegazy** [comment]
This issue does not seem to be actionable at the moment. Closing for housekeeping purposes. Please reopen if this is still an issue or there is more information to share.
