### ISSUE TITLE
npm run build:compiler is failing

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#10709]
Since two days : https://travis-ci.org/basarat/byots/builds (first https://travis-ci.org/basarat/byots/builds/157348835) (second https://travis-ci.org/basarat/byots/builds/157492274) 

Steps: 

* Get a new clean copy of the repo. Alternatively you can `git clean -xfd` `git reset --hard origin/master`
* `npm install` 
* `npm run build:compiler`

It runs `jake local` which fails along: 

```
node_modules/@types/del/index.d.ts(10,40): error TS2304: Cannot find name 'Promise'.
node_modules/@types/del/index.d.ts(11,62): error TS2304: Cannot find name 'Promise'.
node_modules/@types/del/index.d.ts(13,43): error TS2304: Cannot find name 'Promise'.
node_modules/@types/del/index.d.ts(14,65): error TS2304: Cannot find name 'Promise'.
src/compiler/tsc.ts(516,13): error TS2322: Type 'Timer' is not assignable to type 'number'.
src/compiler/tsc.ts(538,13): error TS2322: Type 'Timer' is not assignable to type 'number'.
```

Might just be a types issue. Thought it was worth reporting :rose:

**Comment by mhegazy** [comment]
I am not able to reproduce this locally. what version of `@types/del` do you have? I see `@types/del@2.2.30`.

**Comment by basarat** [comment]
> I see @types/del@2.2.30.

I see the same

```
"_id": "@types/del@2.2.30",
```

With `index.d.ts` contents: 
```
// Type definitions for del v2.2.0
// Project: https://github.com/sindresorhus/del
// Definitions by: Asana <https://asana.com>, Aya Morisawa <https://github.com/AyaMorisawa>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

/// <reference types="glob" />

import glob = require("glob");

declare function Del(pattern: string): Promise<string[]>;
declare function Del(pattern: string, options: Del.Options): Promise<string[]>;

declare function Del(patterns: string[]): Promise<string[]>;
declare function Del(patterns: string[], options: Del.Options): Promise<string[]>;

declare namespace Del {
    function sync(pattern: string, options?: Options): string[];
    function sync(patterns: string[], options?: Options): string[];

    interface Options extends glob.IOptions {
        force?: boolean;
        dryRun?: boolean;
    }
}

export = Del;
```

Promise is supposed to come from `lib` es6 I suspect but is not setup right for `npm run build:compiler`. Suspect it has something to do with this commit : https://github.com/Microsoft/TypeScript/commit/6d79aa66ebfa8d3aa88dab630cc172f8c0d23af8. I'll investigate more later :rose:

**Comment by basarat** [comment]
> I am not able to reproduce this locally.

Worth mentioning: will not happen if you run the command twice (due to caching build results).

**Comment by basarat** [comment]
> will not happen if you run the command twice (due to caching build results).

Nope. `jake local` was running fine. My tsconfig has become invalid due to project structure changes and *that* is what is giving the error. Sorry for this. I'll figure it out.
