### ISSUE TITLE
New Website Logo: Luxe

### ISSUE THREAD

**Issue by cjmartin3** [Microsoft/TypeScript#10714]
Please fill the following out:

- Name: Luxe
- Homepage url: http://luxe.com/
- Brand Guidelines/Licensing: n/a
- Logo: https://www.dropbox.com/sh/ogf8qmhfau9to01/AABZopk4SIQbn_FFVfLnjEyaa/Luxe%20Photos/Luxe%20Logo?dl=0&preview=Luxe-Logo.png

**Comment by DanielRosenwasser** [comment]
Great meeting you last month, thanks for sending this out!
