### ISSUE TITLE
Code paths not type checked when one path returns any

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/TypeScript#10718]
Version: latest 2 beta

Given:

``` ts
    type Fn = (n: number) => number;
    const fn: Fn = (n: number) => {
        if (n === 1) {
            return 'foo' as any;
            // return 'foo';
        } else {
            return 'bar'; // expected to error
        }
    };
```

I expect this to error because one of the code paths is known to be `string` which doesn't comply with the specified `number`.

**Comment by gcnew** [comment]
The function return type is inferred to be the most speciffic type, covering all branch return types. In your case one of the branches returns `any`, which encompasses `string`, thus the return type of the lambda is inferred as `any`. As well as everything being assignable to `any`, it is also assignable to everithing. Thus your `any` returning lambda is assignable to the `number` returning `Fn`.

**Comment by mhegazy** [comment]
You can add a return type annotation to stop inferring the return type.

```ts
const fn: Fn = (n: number): number => { ... }
```
