### ISSUE TITLE
VS2013U5 csproj file untouched

### ISSUE THREAD

**Issue by dan-def** [Microsoft/TypeScript#10719]
**TypeScript Version:** 1.8.11
**NuGet Package:** Microsoft.TypeScript.MSBuild.1.8.11
**Visual Studio Version:** 2013 Update 5

Creating an empty web project in VS2013 and then installing the NuGet package does not modify the .csproj file but the package manager states that the installation completed successfully.

I have also tried adding a .ts file first, which adds the project imports for props and targets, and then installing the NuGet package but again this does not modify the .csproj file.

To ensure it wasn't a problem for other packages as well, I tried to install the JSLintNet.MSBuild package and that successfully modified the .csproj file.

Does the TypeScript package do something differently to the JSLint package that could explain the difference?

**Comment by mhegazy** [comment]
We should add an import to the targets if one does not exists. currently we only update the import if it exists.

**Comment by paulvanbrenk** [comment]
@dan-def This should be fixed in the 2.0 beta/rc package.

**Comment by mhegazy** [comment]
Looks like i miss spoke. this should be fixed now in TS 2.0

**Comment by dan-def** [comment]
Thanks for your responses. I have manually included the project imports in my csproj file to overcome the issue for now and will await the release of TS 2.0.
