### ISSUE TITLE
Last comma of Object

### ISSUE THREAD

**Issue by Aqours** [Microsoft/TypeScript#10720]
**TypeScript Version:**  1.8.10 / Release

**Code**
```
// Compile target: es5
let obj = {
    a: 0,
    b: 1,
    c: 2,
};
```

**Expected behavior:**
```
var obj = {
    a: 0,
    b: 1,
    c: 2
};
```

**Actual behavior:** 
```
var obj = {
    a: 0,
    b: 1,
    c: 2,
};
```

**Comment by thetrompf** [comment]
Isn't trailing comma valid in ES5?

**Comment by RyanCavanaugh** [comment]
This is legal in ES3 as well, though we'll still remove it if you target ES3 due to IE8.

**Comment by Aqours** [comment]
I thought "Actual behavior" is legal in ES6/ES2015 not in ES5, although it works on modern browser. Some compression tools will throw an error when I compress this code `var obj = { a: 0, b: 1, c: 2, }`

**Comment by kitsonk** [comment]
No, it was codified in [ES5 Section 11.1.5](http://www.ecma-international.org/ecma-262/5.1/#sec-11.1.5), where trailing commas in the object initialiser are expressly allowed.

I would say those compression tools need to change because they are not supporting the standards then.

**Comment by Aqours** [comment]
@kitsonk thanks
