### ISSUE TITLE
Documentation contradicts itself with regard to target

### ISSUE THREAD

**Issue by jrgleason** [Microsoft/TypeScript#10723]
**TypeScript Version:**  1.8.0 / nightly (2.0.0-dev.201xxxxx)

**Expected behavior:**

When I go to [this](https://www.typescriptlang.org/docs/handbook/compiler-options.html) I see the following...

```
--target
-t	string	"ES5"	Specify ECMAScript target version: 'es3' (default), 'es5', or 'es6'.
```

Basically the column says es5 is the default but the next one says it is es3. Any idea which is true?

**Comment by mhegazy** [comment]
Should be fixed in https://github.com/Microsoft/TypeScript-Handbook/commit/97cf2f9f9561d7bc6a2c0caec5cc8f78ddf1e946. the website should be updated soon.
