### ISSUE TITLE
Add JS format option to insert space before parentheses in function definition.

### ISSUE THREAD

**Issue by waderyan** [Microsoft/TypeScript#10733]
_From @micktu on September 4, 2016 14:33_

VSCode version: 1.4.0

This is required by standardjs.com guidelines, but is not possible at the moment.

Example: `function myFunc () {`

_Copied from original issue: Microsoft/vscode#11520_

**Comment by waderyan** [comment]
_From @dbaeumer on September 4, 2016 17:46_

@waderyan move to TS.

**Comment by mhegazy** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/12234
