### ISSUE TITLE
Add some colors to non-pretty mode of cli compiler

### ISSUE THREAD

**Issue by Strate** [Microsoft/TypeScript#10745]
It sould be nice to read compiler output log, if "File change detected. Starting incremental compilation..." and "Compilation complete. Watching for file changes." will differ from errors by color. For example - errors goes red, these messages yellow/green. Could be handled by new option `--colors`

**Comment by mhegazy** [comment]
I would say this should be covered in https://github.com/Microsoft/TypeScript/issues/10488, and then expanding the `--pretty` output to all messages.
