### ISSUE TITLE
Trying to use JSDom but it fails in VS

### ISSUE THREAD

**Issue by BobFrGit** [Microsoft/TypeScript#10742]
The code below works fine in node run from the console but fails when I try to run it in Visual Studio.

**Visual Studio *** 14.0.2545.01
**TypeScript Version:**  1.8.36.0
**Code**

```
import jsd = require('jsdom');

var jd = jsd.env({
    url: "http://frankston.com",
    done: (err, window) => {
        console.log(`done ${window}`);
    }
});

console.log('Hello world');

```

**Expected behavior:**

```
>node app.js
Hello world
done [object Window]
```

**Actual behavior:** 

```

Debugger listening on port 5858
y:\dev\projects\play\tryJSD\tryJSD\app.js:3
const jsd = require('jsdom');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.runMain [as _onTimeout] (module.js:501:10)
    at Timer.listOnTimeout (timers.js:110:15)
Press any key to continue...


`````

**Comment by mhegazy** [comment]
Looks like you are running tsc with `--target ES6`, and you are using node < v5. so either call tsc with ES5 target, or upgrade your node to node v6.

**Comment by BobFrGit** [comment]
**Node command line**
{"http_parser":"2.6.2","node":"5.7.1-0","chakra":"11.0.14393.103","uv":"1.8.0","zlib":"1.2.8","ares":"1.10.1-DEV","modules":"47","openssl":"1.0.2g"}

How do I align the versions of node?

**Node in VS**
{"http_parser":"2.3","node":"0.12.2","v8":"3.28.73","uv":"1.4.2-node1","zlib":"1.2.8","modules":"14","openssl":"1.0.1m"}

**Comment by mhegazy** [comment]
is this a node tools for VS project?

**Comment by BobFrGit** [comment]
I presume it is -- I've got the tools installed and just did a "new project /typescript node console"

Tried following the suggestions in https://ryanhayes.net/synchronize-node-js-install-version-with-visual-studio-2015/ but it still used the older version.

**Comment by BobFrGit** [comment]
(This messages are a bit out of synch). JSDom requires V6 so, yes, I need to and want to upgrade. As per the previous message my first effort failed. So how do I upgrade (and why is VS running an old version but that's a different topic)

**Comment by mhegazy** [comment]
@mousetraps can you help out here?

**Comment by BobFrGit** [comment]
I decide to rename the older node.exe so the search would find the new one. And now I've run into the --lazy problem. (How do I reference another report -- this is about that problem https://github.com/nodejs/node-chakracore/issues/84). How can I work around that in VS. I "code" there is a config file. Not obvious how to work around it in Visual Studio.

**Comment by BobFrGit** [comment]
Solved! I went to nodejs.org and got the latest updated. Too bad it isn't automatic. It would be nice to have VS check for upgrades.

**Comment by mhegazy** [comment]
thanks @BobFrGit for reporting back. I have added @mousetraps to the thread to follow up on the auto update proposal.
