### ISSUE TITLE
Object properties introspection

### ISSUE THREAD

**Issue by loretoparisi** [Microsoft/TypeScript#10744]
Supposed to have an object like

```typescript
export class User implements UserInterface, BaseObject {
    user_id: string
    id: string
    name: string
    location: Location
```

unless for the object instance `var u = new User()` all properties are not assigned, there is no way to do introspection via

```javascript
Object.keys(u).forEach(k=> {
            console.log(k);
        });
```

or `hasOwnProperty` like in a possibile object fill function:

```javascript
public fill(properties:Object) {
        var self=this;
        for (var i in properties) {
            if (self.hasOwnProperty(i)) {
                self[i]=properties[i];
            }
        }
    }
```

The only option I see is to assign with the default constructor i.e.

```typescript
constructor() {
        this.user_id="";
        this.id="";
        this.name="";
        this.location=null;
    }
```

At this point I will get properties on compiled javascript object.
Any plan to support object introspection for undefined properties?

A ugly way would be

```typescript
class A {
  A: string = undefined
}
```

so that the both thee `Object.keys` and `this.hasOwnProperty` will introspect all object properties.

**Comment by aluanhaddad** [comment]
Try 
```TypeScript
export class User implements UserInterface, BaseObject {
    user_id = "";
    id ="";
    name = "";
    location: Location = undefined;
}
```

**Comment by mhegazy** [comment]
The declaration is meant to tell the compiler at compile time that the property exists, but it is meant to be completely erasable. if you want to have runtime artifacts you will need to initialize them explicitly as @aluanhaddad mentioned.

**Comment by loretoparisi** [comment]
@mhegazy what about `prototype` class variables?

**Comment by mhegazy** [comment]
> @mhegazy what about prototype class variables?

```ts
class C {
     static p = undefined;
}
```
