### ISSUE TITLE
FormData definition is degraded

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#1074]
FormData definition is updated at #337.

```typescript
declare var FormData: {
    prototype: FormData;
    new (form?: HTMLFormElement): FormData;
}
```

But it degraded at a62e7d218d861cba32b2aa8203fd20a55a015c43.

```typescript
declare var FormData: {
    prototype: FormData;
    new(): FormData;
}
```

Please recovery.

**Comment by theodorejb** [comment]
Hopefully this can be fixed soon, as out-of-the-box I get a "Supplied parameters do not match any signature of call target" error when attempting to instantiate `FormData` with a form element.

I was able to work around the issue with the following code:

```typescript
interface FixedFormData {
    prototype: FormData;
    new (form?: HTMLFormElement): FormData;
}

var FixedFormData: FixedFormData = FormData;
var formData = new FixedFormData(form); // no more error
```

**Comment by agr** [comment]
So, 1.5 is still in beta, and there is no way we get it until 1.6?

**Comment by danquirk** [comment]
You can easily change/augment lib.d.ts yourself as necessary until the fix is in a version you can upgrade to.

**Comment by mhegazy** [comment]
@agr  you can just grab the latest lib file from: https://github.com/Microsoft/TypeScript/blob/master/bin/lib.d.ts and explicitly include it in your project.

**Comment by agr** [comment]
Hopefully it's the final fix :)
