### ISSUE TITLE
type wrongly interpreted as never ; beta->rc regression

### ISSUE THREAD

**Issue by AlexGalays** [Microsoft/TypeScript#10743]
**TypeScript Version:**  2.0.2 rc

This is a regression from 2.0.0 beta

**Code**

First, I define some types in file1.ts:

```ts
export interface Route<P> {
  uri: string
}

export interface RouteWithParams<P> {
  route: Route<P>
  isIn<T>(parent: Route<T>): this is RouteWithParams<T>
}

```

Then, I re-export these types from another module, for convenience (one is an abstract util module used only once, the other should be exclusively imported everywhere):

file2.ts
```ts
import { Route, RouteWithParams } from './file1'

export { Route, RouteWithParams }

```

Then, whenever I import these types in other modules, they are seen as having the `never` type (error TS2339: Property 'isIn' does not exist on type 'never').

I hope I have isolated the issue. It could also be due to wrong flow analysis.
If not, you can also very easily see the issue on a repo I have:

```sh
git clone git@github.com:AlexGalays/kaiju.git
cd kaiju/example
npm install
npm run build  // it compiles fine
Now go to package.json and change the typescript version from `beta` to `rc`
npm install
npm run build // compilation error
```

**Comment by aluanhaddad** [comment]
Works fine for me with **typescript@2.1.0-dev.20160906**
![image](https://cloud.githubusercontent.com/assets/5034656/18310330/ae2e0488-74cb-11e6-82bb-ec318eb04546.png)

By the way your repository requires authentication and I cannot clone it.

**Comment by AlexGalays** [comment]
@aluanhaddad  Just installed that nightly version and my repo has the same compilation errors as with v2.0.2

**Comment by aluanhaddad** [comment]
What does your tsconfig look like?

**Comment by sandersn** [comment]
@aluanhaddad here it is. I don't think there's much surprising there.

I cloned the repo and reproduced the bug there. But I don't get the error with the miniaturised one you gave, @AlexGalays. 

```ts
{
	"compilerOptions": {
		"target": "es5",
		"noImplicitAny": true,
		"strictNullChecks": true
	},
	"compileOnSave": false,
	"atom": {
		"rewriteTsconfig": false
	},
	"filesGlob": [
		"src/**/*.*",
		"typings/**/*.d.ts"
	]
}
```

My code in the using file is 

```ts
import { Route, RouteWithParams } from "./second";
let r: Route<number> = { uri: 'foo' };
let rp: RouteWithParams<number> = { 
  route: r, 
  isIn<T>(parent: Route<T>) {
    return false;
  }
}
console.log(r.uri)
rp.isIn(r);
```

I need to make sure my tsconfig matches yours exactly still, though.

**Comment by AlexGalays** [comment]
Can I somehow provide more info if you were able to reproduce it with the repo?

**Comment by sandersn** [comment]
I am looking for a small, standalone repro. Since the repo exhibits the bug, the next step is to understand the code enough to cut it down to a small repro. I'll do that after I look at another bug if you don't have time to do it.

**Comment by AlexGalays** [comment]
Oh I see. I don't think I will have the time to find the minimum repro case in the coming days though :(

**Comment by sandersn** [comment]
That's ok. I'll get to it after looking at the bug on enums-as-unions.

**Comment by sandersn** [comment]
The never arises from control flow analysis, not an import/export binding. If I comment out [line 91](https://github.com/AlexGalays/kaiju/blob/master/example/src/blue/blue.ts#L91) then the compilation errors go away.

I'm pretty sure this is a change that @ahejlsberg made to type predicates like `this is RouteWithParams<T>` such that you get `never` in branches that can never actually happen. But I need to look closer at the code to make sure.

**Comment by sandersn** [comment]
Here is a much smaller repro. I'll try to make it even smaller, though.

```ts
// @filename: util.ts
export interface Route<P> {
  uri: string
  path: string
}
export function Route<P>(uri: string): Route<P> {
  const path = uri.split('?')[0]
  return { uri, path }
}

export interface RouteWithParams<P> {
  route: Route<P>
  params: P
  isIn<T>(parent: Route<T>): this is RouteWithParams<T>
}

// @filename: router.ts
import { Route, RouteWithParams } from './util'
export { Route, RouteWithParams }
export type BlueParams = { id: string }
export const red = Route<BlueParams>('blue/:id/red')

// @filename: main.ts
import * as routes from "./router";

function getChildren(route: routes.RouteWithParams<routes.BlueParams>) {
  if (route.isIn(routes.red)) return []
  if (route.isIn(routes.red)) return []
  return []
}
```

**Comment by sandersn** [comment]
I think the repro boils down to this. The biggest change is dropping the type parameters from `RouteWithParams` (now called `I`) I'm not sure if that should affect narrowing.

```ts
interface I {
  predicate(): this is I
}
function getChildren(i: I): any[] {
  if (i.predicate()) return []
  i.predicate() // error: `i: never` here
  return []
}
```

**Comment by sandersn** [comment]
All right, after some discussion with @mhegazy, let me explain the conclusion we reached. Briefly, the compiler is behaving correctly, and the type of `getChildren` needs to be improved.

First, the error with the super-simplified `I` example is more obviously correct. If `i is I` in the first line of `getChildren`, then there's nothing else for it to be in the rest of function &mdash; it started out as `I`, so when you remove `I`, `never` is left. 

The more complex case behaves the same way, even though you don't really want it to. `route: RouteWithParams<BlueParams>` the beginning of the function, so when `isIn` succeeds in the true branch, it removes `RouteWithParams<BlueParams>` from the type, leaving `never` for the rest of the function. This is correct for the code as written.

To explain the fix, let me start with blue/green example (I oversimplified even the smaller multi-file repro above):

```ts
type BlueParams = { id: string }
type GreenParams = { foo: string }
const blue = Route<BlueParams>('blue/:id/red')
const green = Route<GreenParams>("...")
function getChildren(route: RouteWithParams<BlueParams>) {
  if (route.isIn(blue)) return [route.params.id]
  if (route.isIn(green)) return [routes.params.foo]
  return []
}
```

The real problem here is that you want to change the type of `route` in the second `if` to a type that it is not declared to have: `RouteWithParams<GreenParams>`. You really need to declare that `route` could have any of several type parameters:

```ts 
function getChildren(route: RouteWithParams<BlueParams | GreenParams>) {
  if (route.isIn(blue)) return [route.params.id]
  if (route.isIn(green)) return [routes.params.foo]
  return []
}
```

Note that technically this function handles *any* type of route by just returning `[]`, so you could even use `any` as your type parameter:

```ts
function getChildren(route: RouteWithParams<any>) {
  if (route.isIn(blue)) return [route.params.id]
  if (route.isIn(green)) return [routes.params.foo]
  return []
}
```

I would use the first version if you know the entire space of `*Params` types and the second version if you don't.

**Comment by AlexGalays** [comment]
I see, thanks a lot @sandersn  for the detailed explanation.

**Comment by aluanhaddad** [comment]
@sandersn That was very informative. I have a better understanding of type guards after reading the conclusion reached. It might be worth writing this up somewhere, perhaps in the FAQ, as this is very illustrative.
