### ISSUE TITLE
Allow to run TypeScript (Services) in strict mode

### ISSUE THREAD

**Issue by kpreisser** [Microsoft/TypeScript#10755]
Hi,
this is a follow-up issue to #9449.

**TypeScript Version**: master (46856462816b54e32a9d962e218d6e3f8ff42348)

After PR #9353 has been merged, typescriptServices.js (in this case) again cannot be run in strict mode due to using the identifier [`package` in `services.ts`](https://github.com/Microsoft/TypeScript/commit/dbf19f18af35afc21640ecf9b80a6c745992f5a7?diff=unified#diff-233e1126c0abc811c4098757f9e4516eR4665), which is a reserved word in strict mode:
```
C:\Users\VPC\Desktop\TypeScript\built\local>node --use_strict typescriptServices.js
C:\Users\VPC\Desktop\TypeScript\built\local\typescriptServices.js:68849
                        var package = _d[_c];
                            ^^^^^^^
SyntaxError: Unexpected strict mode reserved word
```
(running current master)

As @HerringtonDarkholme noted, this causes an error in the Closure Compiler.

Now that TSC requires at least ES5 (#10125), might there be an option to add `"use strict";` to the ts files of the TypeScript repo? This should prevent using such reserved identifiers.

Thanks!

**Comment by mhegazy** [comment]
I have a fix to remove the use of `package` in https://github.com/Microsoft/TypeScript/pull/10757. the longer term change is to add a new flag to parse a project in strict mode.

**Comment by kpreisser** [comment]
Thanks!

**Comment by mhegazy** [comment]
Filed https://github.com/Microsoft/TypeScript/issues/10758 to track adding the compiler option.
