### ISSUE TITLE
`gulp build-rules` fails

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#10750]
To reproduce:

* `rm -r node_modules`
* `npm install`
* `gulp build-rules`

The error:

    C:/Users/anhans/work/TypeScript_1/node_modules/tslint/lib/language/utils.d.ts(7,51): error TS2305: Module 'ts' has no exported member 'ModifiersArray'.
    scripts\tslint\preferConstRule.ts(49,57): error TS2339: Property 'Export' does not exist on type 'typeof NodeFlags'.
    C:/Users/anhans/work/TypeScript_1/node_modules/tslint/lib/language/utils.d.ts(7,51): error TS2305: Module 'ts' has no exported member 'ModifiersArray'.
    scripts\tslint\preferConstRule.ts(49,57): error TS2339: Property 'Export' does not exist on type 'typeof NodeFlags'.

**Comment by mhegazy** [comment]
@sandersn has a fix for this. we will need to revert my change in https://github.com/Microsoft/TypeScript/commit/e0587a01d8f377bc2dc516987a67a5f85370299a along with the fix.

**Comment by sandersn** [comment]
preferConstRule just needs to reference the newly exported functions @mhegazy moved yesterday and delete its copy of them. I'll send out the change when I get to my desk this morning.
