### ISSUE TITLE
let promises be unions

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#10751]
nightly build, September 7, 2016

currently in order for async/await to work it has to be a solid interface with a `then` method, await doesn't accept a union that has a callable `then`, please allow unions for promises

``` json
// tsconfig.json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es6",
        "noLib": true
    }
}
```

``` typescript
const enum PromisedKind { Resolved, Unresolved }

interface Thenable<a> {
    then<b>(onfulfilled?: (value: a) => b | Promise<b>, onrejected?: (reason: any) => b | Promise<b>): Promise<b>;
    then<b>(onfulfilled?: (value: a) => b | Promise<b>, onrejected?: (reason: any) => void): Promise<b>;
}

type Promise<a> = Resolved<a> | Unresolved<a>;

interface Resolved<a> extends Thenable<a> {
    kind: PromisedKind;
    value: a;
}

interface Unresolved<a> extends Thenable<a> {
    kind: PromisedKind;
    thens: { (value: a): void; }[];
}

interface Array<a> {}
interface Boolean {}
interface Function {}
interface Number {}
interface Object {}
interface RegExp {}
interface String {}
interface IArguments {}
var String: StringConstructor;
interface StringConstructor {
  new (value?: any): String;
  (value?: any): string;
  prototype: String;
  fromCharCode(...codes: number[]): string;
}


declare const value: Promise<number>;

async function test() {
    void value.then(x => { }); // <-- then exists and is callable
    return await value; // Operand for 'await' does not have a valid callable 'then' member.
}
```

![image](https://cloud.githubusercontent.com/assets/937933/18315461/12f13aac-74e5-11e6-94c8-397dda4693c1.png)

**Comment by jods4** [comment]
Actually, you can `await` anything, not only promises. 
It should behave as if you did `await Promise.resolve(x)` (note that if `x` was a promise already, `Promise.resolve(x)` should return `x` itself).

**Comment by aluanhaddad** [comment]
> well, that's the specified JS behavior, of course

@jods4 I am not sure I understand this statement. JavaScript does not have interfaces.

**Comment by jods4** [comment]
@aluanhaddad I meant that JS supports awaiting any value, not only promises/thenable. It is not an error to `await 4`.

**Comment by Arnavion** [comment]
>maybe it should raise a warning if you `await` something that *cannot* be a Promise/Thenable?

#8310

**Comment by jods4** [comment]
@Arnavion Thanks for the link. I see this was beaten to death in several issues already. So I guess we should be able to await anything!

I noticed @RyanCavanaugh said in that thread: 
> We clearly want to allow `await T | Promise<T>`

But as @aleksey-bykov says, the following code trips up the type checker:
```ts
let x: number | { then(): number };
async function f() {	
	return await x;  // Error
}
```
I think that TS should distribute the `await` operation and deduce that the result is `number | number`, well `number`.

**Comment by aluanhaddad** [comment]
@jods sorry, it appears I misunderstood the context. Distributing the `await` is a nice idea but it seems to suggest different runtime semantics as you have already pointed out. That would introduce type based runtime behavior...

**Comment by jods4** [comment]
@aluanhaddad 
> it seems to suggest different runtime semantics as you have already pointed out

Not sure what you are referring to.

By 'distributing' I meant that the expression `await (X | Promise<Y> | Thenable<Z>)` should be valid and have type `X | Y | Z`.

**Comment by mhegazy** [comment]
Given that `Promises` are built-in type and well defined in the spec. changing what it means seems like an advanced option, and would be out of scope for the time being.
