### ISSUE TITLE
Automatic Brace Completion Should Not Complete `<` in Js Files

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#10763]
- TypeScript for Visual Studio 2.0.2.0 (2.0 RC)
- VS 2015 14.0.25420.01 Update 3

This issue is coming from NTVS, which uses Typescript to power our editor: https://github.com/Microsoft/nodejstools/issues/1142

**Repo Steps:**
1. Enable automatic brace completion for Typescript.
2. Open blank Js file with Typescript editor.
3. Type `<`

**Expected behavior:**
Brace completion should not close `<` with `>` in JavaScript files. 

**Actual behavior:** 
A `>` is inserted automatically.

From the original automatic brace completion thread ( https://github.com/Microsoft/TypeScript/issues/1484#issuecomment-144201652 ), I though `<` completion was dropped. It does not make sense in a pure js file.

**Comment by RyanCavanaugh** [comment]
Not sure what's going on here but it seems likely it's fine by now.
