### ISSUE TITLE
incorrect let behavior inside the loop

### ISSUE THREAD

**Issue by mhevery** [Microsoft/TypeScript#10769]
**TypeScript Version:**  2.0.2

**Code**

[playground](https://www.typescriptlang.org/play/#src=%20%20function%20wrapDescribeInZone(args%3A%20IArguments)%3A%20any%5B%5D%20%7B%0D%0A%20%20%20%20for%20(var%20i%20%3D%200%3B%20i%20%3C%20args.length%3B%20i%2B%2B)%20%7B%0D%0A%20%20%20%20%20%20let%20arg%20%3D%20args%5Bi%5D%3B%0D%0A%20%20%20%20%20%20if%20(typeof%20arg%20%3D%3D%20'function')%20%7B%0D%0A%20%20%20%20%20%20%20%20args%5Bi%5D%20%3D%20function()%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20return%20arg.apply(this%2C%20arguments%20as%20any%20as%20any%5B%5D)%3B%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20return%20args%20as%20any%3B%0D%0A%20%20%7D%0D%0A)

Given:
```
  function wrapDescribeInZone(args: IArguments): any[] {
    for (var i = 0; i < args.length; i++) {
      let arg = args[i];
      if (typeof arg == 'function') {
        args[i] = function() {
          return arg.apply(this, arguments as any as any[]);
        }
      }
    }
    return args as any;
  }
```

The generated code is:
```
function wrapDescribeInZone(args) {
    var _loop_1 = function() {
        var arg = args[i];
        if (typeof arg == 'function') {
            args[i] = function () {
                return arg.apply(this, arguments);
            };
        }
    };
    for (var i = 0; i < args.length; i++) {
        _loop_1(); // <<<<< ERROR, i is not passed into the loop
    }
    return args;
}
```

Which can't possibly be right since `i` is not passed into the loop.

**Comment by vladima** [comment]
I'd say it is expected since `var i` in the loop header is no block scoped hence it is not passed into the transformed loop body. 
if you replace `var i` with `let i` to make it block scoped result will be as expected.
```ts
function wrapDescribeInZone(args: IArguments): any[] {
    for (let i = 0; i < args.length; i++) {
        let arg = args[i];
        if (typeof arg == 'function') {
            args[i] = function() {
                return arg.apply(this, arguments as any as any[]);
            }
        }
    }
    return args as any;
}
```

```javascript
function wrapDescribeInZone(args) {
    var _loop_1 = function (i) {
        var arg = args[i];
        if (typeof arg == 'function') {
            args[i] = function () {
                return arg.apply(this, arguments);
            };
        }
    };
    for (var i = 0; i < args.length; i++) {
        _loop_1(i);
    }
    return args;
}
```

**Comment by mhevery** [comment]
I see my bad
