### ISSUE TITLE
Generics not inferred from union type

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/TypeScript#10779]
Latest 2 beta

``` ts
const y = <S, E>(z: S | E) => 1;
y(5 || 'foo') // generics should be number and string, but are {} and {}
```

I expect the generics `S` and `E` to be inferred correctly as `number` and `string`, but it seems like TypeScript infers them both as `{}` instead.

**Comment by kitsonk** [comment]
TypeScript cannot infer generics in that way.  A simple example:

```typescript
const y = <S, E>(z: S | E) => 1;
y(5 || 'foo' || true) // What should be inferred here?
```

Where as:

```typescript
const y = <S>(z: S) => 1;
y(5 || 'foo') // inferred as `string | number`
```

In order to infer generics contextually, TypeScript needs to be in a position to actually resolve to a single type (which a union type is a single type).  For example:

```typescript
const y = <S, E>(z: S | E, a: S, b: E) => 1;
y(5 || 'foo', 6, 'bar') // inferred as number, string
y(5 || true, 6, 'bar') // an Error
```

**Comment by OliverJAsh** [comment]
That makes sense, thank you!
