### ISSUE TITLE
how to extend generic types with optional properties

### ISSUE THREAD

**Issue by flyon** [Microsoft/TypeScript#10773]
This is a simplified minimal example of a problem many people seem to run into with using React + Typescript. 

However in this very simple example, the question boils down to: _how to extend generic types with optional properties?_

```
class StateClass<S>{
    state:S;
    setState(state:S) {
        this.state = state;
    }
}
interface AState {
    foo?:string;
}
//A is defining a state interface in such a way that any class that extends A can still add properties to it.
class A<S extends AState> extends StateClass<S>{
    bar(){
        this.setState({foo:"works"}); //<-- Argument of type '{ foo: string; }' is not assignable to parameter of type 'S'.
    }
}
```

**Comment by billccn** [comment]
The current behaviour is sound. `S` could have any additional required properties which is missing from `{foo:"works"}` right now.

**Comment by flyon** [comment]
So I guess this can only be correctly applied with potential new language features like `partial`? https://github.com/Microsoft/TypeScript/issues/4889#issuecomment-178819795

Or is there a different way to do this with the current language syntax?

**Comment by RyanCavanaugh** [comment]
You can use a type assertion - `{foo: "works"} as S}` or `<S>{ foo: "works" }`

**Comment by mhegazy** [comment]
There is not a way to "optionalize" a type today, #4889 is the issue tracking this proposal.

**Comment by schickling** [comment]
And idea how to do this for JSX @RyanCavanaugh?
