### ISSUE TITLE
VisualStudio 2015 Update 3 - Comment/uncomment selection does not work for .ts files anymore.

### ISSUE THREAD

**Issue by ruant** [Microsoft/TypeScript#10775]
**TypeScript Version:**  2.0.2 Beta
VisualStudio 2015 Update 3

**Expected behavior:**
The selected text/line we're on should be commented/uncommented
Works fine in the other file types I've tried it on (html, js, cs, scss)

**Actual behavior:** 
Selected text/line is not commented/uncommented.
Visual Studio says:
"The key combination (Ctrl + K, Ctrl + C) is bound to command (Comment Selection) which is not currently available."

**Comment by mhegazy** [comment]
Seems working fine locally. do you see this on other machines? are other features impacted? do you have any extensions?

**Comment by ruant** [comment]
Thanks for the reply. Might be just my setup then :/

I've tried to disable all extensions that I can disable, and suspended ReSharper without any luck.

I haven't check any other machines, but I'll set up a clean VM and check it out.

**Comment by ruant** [comment]
Works as expected in the new clean VM.
Sorry for the false alarm.

**Comment by RodionKulin** [comment]
This can be fixed without reinstalling on clean VM. Just use the solution provided here
https://github.com/Microsoft/TypeScript/issues/7519

Try deleting: %localappdata%\Microsoft\VisualStudio\14.0\ComponentModelCache,
And run devenv /setup from the Developer Command Prompt for VS2015 (as an admin).

I experienced the same CommentSelection command disappear after installation of TypeScript for Visual Studio 2015 tools on 20,11.2016 and fixed using method above.
https://www.microsoft.com/ru-ru/download/confirmation.aspx?id=48593
