### ISSUE TITLE
Rename symbol

### ISSUE THREAD

**Issue by waderyan** [Microsoft/TypeScript#10791]
_From @microshine on September 7, 2016 16:49_
- VSCode Version: 1.4.0
- OS Version: Windows 10 x64

Source code

``` typescript
let arr = {
    item: "Hello"
};

const {item} = arr;

console.log(item);
console.log(arr.item);
```

Trying to rename `item` symbol (F2) to `itemA`

Result

``` typescript
let arr = {
    itemA: "Hello"
};

const {item} = arr; // TSError: Has no property `item`

console.log(item);
console.log(arr.itemA);
```

_Copied from original issue: Microsoft/vscode#11641_

**Comment by waderyan** [comment]
@microshine thank you for opening this issue. This is a TypeScript service issue. Moving to their repo.

**Comment by andy-ms** [comment]
Looks like a duplicate of #6312.

**Comment by mjbvz** [comment]
Duplicate of #6312 / #15787
