### ISSUE TITLE
"experimentalDecorators" and "types" properties can't coexist in tsconfig

### ISSUE THREAD

**Issue by waderyan** [Microsoft/TypeScript#10790]
_From @roblourens on September 7, 2016 18:50_

Reported in gitter, I repro in 1.5-insider.

Have a tsconfig.json with `"experimentalDecorators": true` and `"types": []`. If you use a decorator in TS, you get that error "... set the experimentalDecorators option to remove this warning..." but if you delete the "types" property, then it does not complain about the decorator, as expected.

_Copied from original issue: Microsoft/vscode#11648_

**Comment by RyanCavanaugh** [comment]
@roblourens can you post an exact repro?

**Comment by roblourens** [comment]
Ok here's what I think is going on -

- My workspace was using TS 1.8, and the original reporter's probably was too
- TS 1.8 doesn't have "types"
- When you have an invalid prop in the tsconfig, then it's rejected. VS Code doesn't validate it or complain but if you run tsc, it will error out
- VS Code's tsconfig intellisense suggests 'types', but the message says that it requires 2.0.

Guess I just wasn't paying close attention but maybe vscode can validate the tsconfig for invalid props? @waderyan

**Comment by mhegazy** [comment]
> Guess I just wasn't paying close attention but maybe vscode can validate the tsconfig for invalid props? 

this is something we should have working in the next release.
