### ISSUE TITLE
Switch Case not working with String conditions 

### ISSUE THREAD

**Issue by 06needhamt** [Microsoft/TypeScript#10802]
**TypeScript Version:**  1.8.34

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
let extension: String = "bin";
		switch (extension) {
			case "txt", "xml":
				return ResourceType.PlainText;
			case "bmp", "jpg", "jpeg", "png", "tiff", "psd", "tga", "gif":
				return ResourceType.Image;
			case "mp3", "wav", "ogg", "flac", "wma", "m4a":
				return ResourceType.Audio;
			case "bin", "dat":
				return ResourceType.Binary;
			case "ico":
				return ResourceType.Icon;
			case "rc", "resx":
				return ResourceType.ResourceScript;
			default:
				return ResourceType.Unknown;
}

```

**Expected behavior:**
The Switch case will return the correct value based on the condition ex when extension == "bin" ResourceType.Binary should be returned
**Actual behavior:** 
The Default value is always returned

**Comment by yortus** [comment]
In JavaScript (and hence TypeScript), `case` clauses don't take comma-separated lists like that. But it's not an error, because a comma-separated list of expressions is a valid expression that evaluates to the result of the rightmost expression in the list. So your `switch` statement will only work for "xml", "gif", "m4a", "dat", "ico" and "resx" and everything else will fall through to the `default` case.

I think this is what you meant:

```ts
    switch (extension) {
        case "txt":
        case "xml":
            return ResourceType.PlainText;
        case "bmp":
        case "jpg":
        case "jpeg":
        case "png":
        case "tiff":
        case "psd":
        case "tga":
        case "gif":
            return ResourceType.Image;
        case "mp3":
        case "wav":
        case "ogg":
        case "flac":
        case "wma":
        case "m4a":
            return ResourceType.Audio;
        case "bin":
        case "dat":
            return ResourceType.Binary;
        case "ico":
            return ResourceType.Icon;
        case "rc":
        case "resx":
            return ResourceType.ResourceScript;
        default:
            return ResourceType.Unknown;
    }
```

**Comment by kitsonk** [comment]
Also, you shouldn't use `String` as a type (I think the team is going to try to error on that in the future) as that refers to the `String` global object.  You should use `string` instead:

```
let extension: string = "bin";
```

Also, Gitter, StackOverflow or IRC are better places to ask these sort of general questions.

**Comment by RyanCavanaugh** [comment]
Addressed by comments above.

**Comment by 06needhamt** [comment]
Ah thanks for letting me know

**Comment by RyanCavanaugh** [comment]
Thinking about just banning this outright. It's hard to believe anyone would *ever* do this on purpose

**Comment by RyanCavanaugh** [comment]
This will now be an error

**Comment by RyanCavanaugh** [comment]
(Tracking at #10814)
