### ISSUE TITLE
[JavaScript/Node.js] Support for "Go to definition" of code located in "node_modules"

### ISSUE THREAD

**Issue by waderyan** [Microsoft/TypeScript#10808]
_From @drywolf on January 29, 2016 15:54_

I am using "npm link ../../lib/my-lib" to symlink a local module that is shared across several apps into the "node_modules" directory of each of the apps. This is nice for developing the shared lib in combination with all the apps.

    // a standard npm module, can't navigate to its definition
    var shortid = require('shortid');
    // some functions from a symlink-ed local module inside node_modules, can't navigate to it either
    var ModelMountUtils = require('@ipp/loopback-lib').ModelMountUtils;
    var RemoteMethodUtils = require('@ipp/loopback-lib').RemoteMethodUtils;

VS-Code does not allow me to navigate to this shared libraries' code by pressing F12 or "Go to definition". The same applies for all other npm modules inside the node_modules directory.

Is this restricted functionality intentional ? or should it be working and I am running to a JS parsing bug that prevents the "Go to definition" to do its work ?
If the "Go to definition" feature is not supposed to work for all things "node_modules" ... could we integrate an exception for symlink directories inside node_modules ?

Thanks

_Copied from original issue: Microsoft/vscode#2550_

**Comment by waderyan** [comment]
_From @jrieken on January 29, 2016 18:6_

That's a bug. We will soon ship with a revamped JS language support and such things should be fixed then

**Comment by waderyan** [comment]
_From @drywolf on January 31, 2016 19:5_

Nice, I'm looking forward to the next release :smile:

**Comment by waderyan** [comment]
_From @girvo on August 17, 2016 4:25_

Just checking, this still seems to be broken in the latest Insider build. Is that expected behaviour? It's a React Native Javascript project, if that matters :)

**Comment by waderyan** [comment]
_From @zjaml on September 9, 2016 7:1_

Subscribed to this too. The feature could be very useful.

**Comment by waderyan** [comment]
_From @jrieken on September 9, 2016 8:16_

@waderyan This is an issue with the typescript brain

**Comment by waderyan** [comment]
@jrieken just to make sure I understand, when you say "typescript brain" you mean the TypeScript language service, correct?

**Comment by waderyan** [comment]
_From @jrieken on September 9, 2016 15:27_

yes

**Comment by mhegazy** [comment]
Should be working correctly in latest drop of TypeSript (TS 2.0.2 or later). VSCode ships with an older version of TypeScript. Please see [Using Newer TypeScript Versions](https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions) documentation for more details on updating your VSCode to use a different version of TypeScript.

**Comment by rockswang** [comment]
How to enable this feature? I have upgrade the TypeScript to 2.1.5, however when I highlight an external import and click F12, nothing happened.
Is this also fixed for javascript service?

**Comment by mhegazy** [comment]
can you share a project?

**Comment by danielmhanover** [comment]
It seems F12 jumps to the TypeScript definition file but not into the actual source code. Is there any intention of supporting a direct-to-source jump?

**Comment by mhegazy** [comment]
please see https://github.com/Microsoft/TypeScript/pull/22658
