### ISSUE TITLE
formatting jsx files stopped working

### ISSUE THREAD

**Issue by waderyan** [Microsoft/TypeScript#10817]
_From @anvish on September 8, 2016 17:2_
- VSCode Version: 1.4.0
- OS Version: Windows 7 SP1

Steps to Reproduce:
1. open jxs file with improper formatting
2. press shift+alt+f, or click Format Code in command palette
3. formatting doesn't work

_Copied from original issue: Microsoft/vscode#11698_

**Comment by waderyan** [comment]
_From @ramya-rao-a on September 8, 2016 17:39_

@anvish I am able to format jsx files just fine in VS Code 1.4.0 in Windows. Can you give more details?

- Was this working before in VS Code 1.4.0?
- What extensions do you have? Can you try with extensions disabled? `code --disable-extensions .` 
- What is the file mode? You can see that in the bottom right corner.
- Does formatting work for other file types? 
- Can you try the insiders build and see if you still see the issue?

**Comment by waderyan** [comment]
_From @anvish on September 9, 2016 12:26_

Thank you for response.
I've found what causing formatting to stop working - it's apostrophe in jxs.
This piece of code breaks formatting:
`    return  <div>'</div>`
And this does not:
`    return  <div>1</div>`
After trying to format the former, formatting stops working for all jsx, js and tsx files untill VS Code restart.

**Comment by waderyan** [comment]
_From @ramya-rao-a on September 9, 2016 17:18_

@anvish That is interesting. I was able to repro now. With the `'` formatting breaks for current file and all other files.
The fact that formatting fails for all other files is suspicious.

The output window shows the below error for every subsequent formatting in other or same file even after fixing the `'`

![image](https://cloud.githubusercontent.com/assets/16890566/18396066/8359853c-7676-11e6-9d02-cc7785da0777.png)

@waderyan This would go to the typescript team?

**Comment by RyanCavanaugh** [comment]
@waderyan would it be possible for the porting tool you're using to stop putting the `typescript` label on the bugs?

**Comment by waderyan** [comment]
I don't know if its configurable in the tool, but I will take it off.

**Comment by RyanCavanaugh** [comment]
Can't repro
```
Sending request: format (385). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "c:/Throwaway/blah.tsx",
    "line": 1,
    "offset": 1,
    "endLine": 5,
    "endOffset": 1
}

Response received: format (385). Request took 39 ms. Success: true 
Result: []

Sending request: format (386). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "c:/Throwaway/blah.tsx",
    "line": 1,
    "offset": 1,
    "endLine": 5,
    "endOffset": 1
}

Response received: format (386). Request took 1 ms. Success: true 
Result: []
```

Code:
```ts
function fn() {
    return <div>'</div>;
}
```

Can we get the full text of a file that repros this?

**Comment by ramya-rao-a** [comment]
Here is a sample jsx code

```
import React, { Component } from 'react';
import { AppRegistry, Text } from 'react-native';

class HelloWorldApp extends Component {
  render() {
    return (

        <div></div>
    );
  }
}

AppRegistry.registerComponent('HelloWorldApp', () => HelloWorldApp);
```
Add some tabs and `Format Code` everything is fine
Open a `ts` file with any content, add some tabs and `Format Code` everything is fine.
Add `'` or `"` inside the `<div>` in the `jsx` file  and add some tabs and `Format Code` nothing happens
Open another `ts` file add some content and tabs and `Format Code` nothing happens.

You need now reload/restart VSCode for anything to work again

**Comment by RyanCavanaugh** [comment]
What version of TypeScript is your VS Code instance using?

**Comment by ramya-rao-a** [comment]
As per the [docs](https://code.visualstudio.com/Updates#_languages), it is 1.8.0

**Comment by waderyan** [comment]
Duplicate of this came in today - https://github.com/Microsoft/vscode/issues/11946

**Comment by mhegazy** [comment]
I could not get this to reproduce on latest. please reopen if issue still persists.
