### ISSUE TITLE
Enhancements for lib.dom.d.ts

### ISSUE THREAD

**Issue by donaldpipowitch** [Microsoft/TypeScript#10820]
**TypeScript Version:**  2.1.0-dev.20160907

Two feature requests for lib.dom.d.ts.

1) Can we extract all CSS props from `CSSStyleDeclaration` into an `interface CSSProperties`? After that `CSSStyleDeclaration` could extend `CSSProperties` and add additional fields (e.g. `parentRule`, `getPropertyPriority` and so on). Main purpose: I'd like to re-use `CSSProperties` as an interface for CSS-in-JS libs.
2) Can we add docs for the CSS props? E.g. summaries from https://docs.webplatform.org/wiki/css/properties to get documentation information in VS Code.

**Comment by mhegazy** [comment]
the DOM is generated from the IE/Edge dom specification by a script (see https://github.com/Microsoft/TSJS-lib-generator). this makes realy easy for us to keep updating it. we have a process in place to add/remove/update the contents of the file, (see https://github.com/Microsoft/TSJS-lib-generator/blob/master/inputfiles/addedTypes.json), but we would not want to change the structure of the files as that messes up the automatic update process.

**Comment by mhegazy** [comment]
So to answer your question, take a look at the generator in https://github.com/Microsoft/TSJS-lib-generator if you have a proposal on how to get your desired structure without impeding the automatic update process, we would happy to look at it.

**Comment by donaldpipowitch** [comment]
Thank you for the in-depth explanation. I'll look at it.

**Comment by donaldpipowitch** [comment]
@mhegazy Why did you closed the issue? Because it is a problem TSJS-lib-generator or is it fixed or wouldn't you want this change anymore?

**Comment by mhegazy** [comment]
As i mentioned [erlier](https://github.com/Microsoft/TypeScript/issues/10820#issuecomment-246013939) take a look at  https://github.com/Microsoft/TSJS-lib-generator, if you have proposal feel free to send a PR to  https://github.com/Microsoft/TSJS-lib-generator we would be happy to look at it. but i do not think we have plans to do this otherwise.

**Comment by donaldpipowitch** [comment]
That's fine, exactly what I wanted to know - if you'd still accept a PR to TSJS-lib-generator or if it was closed because of other unknown reasons.
