### ISSUE TITLE
Importing @types/fb

### ISSUE THREAD

**Issue by tinchou** [Microsoft/TypeScript#10822]
**TypeScript Version:**  2.0.2

Finding the right way to import these types gave me a headache. All these don't work:

```ts
import "fb";
import { FB } from "fb";
import * from "fb";
```

This finally worked:

```ts
import * as fb from "fb";
```

Why is this happening?

**Comment by mhegazy** [comment]
Take a look at http://www.typescriptlang.org/docs/handbook/modules.html for more details.
