### ISSUE TITLE
strictNullChecks does not ensure class properties are initialized in constructor

### ISSUE THREAD

**Issue by Swatinem** [Microsoft/TypeScript#10827]
**TypeScript Version:**  2.1.0-dev.20160909

**Code**

```ts
class A {
	prop: string;
}

const a = new A();
a.prop.length; // TypeError: Cannot read property 'length' of undefined

```

**Expected behavior:**

TS should throw a compile time error to ensure that non-nullable class members are initialized inside the constructor and can not lead to runtime errors.

**Actual behavior:** 

No compile time error, rather an exception at runtime

**Comment by RyanCavanaugh** [comment]
Duplicate #8476.

![image](https://cloud.githubusercontent.com/assets/6685088/18402242/6c1eb91a-7693-11e6-97ef-1142e403d8f4.png)

**Comment by Swatinem** [comment]
Thanks for reminding me. Default search is set to `is: open` though -_-
