### ISSUE TITLE
Tagged unions for classes

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/TypeScript#10828]
Should discriminant property type guards work with classes? In the following example, it appears the type is not narrowed:

``` ts
(() => {
    enum Types { Foo, Bar }
    class Foo {
        type = Types.Foo
    }
    class Bar {
        type = Types.Bar
    }
    const fn = (x: Foo | Bar): number => {
        switch (x.type) {
            case Types.Foo:
                // x should be Foo, but is Foo | Bar
                return 1;
            case Types.Bar:
                // x should be Bar, but is Foo | Bar
                return 2;
        }
    }
})
```

It is possible to workaround this by specifying the type and providing a default value:

``` ts
    class Foo {
        type: Types.Foo = Types.Foo
    }
    class Bar {
        type: Types.Bar = Types.Bar
    }
```

However I thought the behaviour here should be identical?

**Comment by RyanCavanaugh** [comment]
This will be fixed with #10676 *if* you make those properties `readonly` (since they're currently mutable they are not safe to discriminate with)

**Comment by OliverJAsh** [comment]
Is that the same reason this fails, or should I open a separate issue? (With struct null checking and no implicit returns)

``` ts
(() => {
    enum TaskTypes { Foo }
    class Foo { type: TaskTypes.Foo = TaskTypes.Foo }
    // line below errors: function lacks ending return statement
    const fn = (foo: Foo): number => {
        switch (foo.type) {
            case TaskTypes.Foo:
                return 1;
        }
    }
})

(() => {
    class Foo { type: 'Foo' }
    // yet this works fine
    const fn = (foo: Foo): number => {
        switch (foo.type) {
            case 'Foo':
                return 1;
        }
    }
})
```

**Comment by RyanCavanaugh** [comment]
@ahejlsberg thoughts on the first block there?

**Comment by ahejlsberg** [comment]
The issue with the first block is that we don't classify an enum with a single value as an enum with literal values (we just classify it as a regular old enum type that behaves as a subtype of `number` with all the possible values of `number`). To treat single value enums as literal valued enums would require some changes because the enum itself wouldn't be an alias for union type in the single value case and we'd need some other way to distinguish the two kinds internally.

**Comment by RyanCavanaugh** [comment]
@OliverJAsh  Just to unpack that a little -- this sample does *not* error:
```ts
(() => {
    enum TaskTypes { Foo, Bar } // <-- only change - added 'Bar'
    class Foo { type: TaskTypes.Foo = TaskTypes.Foo }
    // OK
    const fn = (foo: Foo): number => {
        switch (foo.type) {
            case TaskTypes.Foo:
                return 1;
        }
    }
})
```
Somewhat subtle but I think in practice a one-member enum is going to not come up. Seem OK?

**Comment by OliverJAsh** [comment]
Thanks for the high level of detail! :-)
