### ISSUE TITLE
Go to definition broken in latest version of VS Code (1.5) + older TypeScript

### ISSUE THREAD

**Issue by waderyan** [Microsoft/TypeScript#10821]
_From @DavidRigglemanININ on September 9, 2016 12:15_

- VSCode Version: 1.5
- OS Version: OS X Yosemite

Steps to Reproduce:
1. Open up project
2. Click the cursor over a method
3. Click F12 to try to go to definition and nothing happens
4. Switch to using VS Code 1.4 and repeat steps 1-3 and everything works as expected

This feels like a really bad bug as it makes the latest version of VS Code pretty much unusable for me unless there is some workaround that I'm not aware of. Also, it would be nice if there was an official download source to downgrade to a prior version. Fortunately, I found one in my trash this time, but I will definitely be disabling auto update because of this for future releases.

_Copied from original issue: Microsoft/vscode#11766_

**Comment by waderyan** [comment]
_From @joebehymer on September 9, 2016 14:35_

I'm a team member of Davids.  We're still using TS 1.6.  If we select to use 1.6 at the popup during start, we get no code completion/navigation.  If we select to use 1.8 everything works.

**Comment by waderyan** [comment]
_From @ramya-rao-a on September 9, 2016 18:55_

@waderyan Do you know if we support back compat for typescript versions?

**Comment by waderyan** [comment]
hey @DavidRigglemanININ thank you for opening this issue. 

I broke off your other request into its own issue - https://github.com/Microsoft/vscode/issues/11796

This issue falls into TypeScript language service, so I will migrate to them.

**Comment by waderyan** [comment]
@ramya-rao-a yes you can use different TypeScript versions. See docs [here](https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions).

**Comment by joebehymer** [comment]
> @ramya-rao-a yes you can use different TypeScript versions. See docs here.

I understand you can specify the typescript version, and with VSC 1.5 you have that handy banner that lets you run your specific version instead of the version that ships.  

The question is - is what was reported something that is supported?  Should specifying the following when you have TypeScript 1.6 installed be supported in VSC 1.5?  It worked before.

    "typescript.tsdk": "node_modules/typescript/lib"

**Comment by mhegazy** [comment]
@waderyan there are no changes in the TS version between 1.5 and 1.4, correct?

**Comment by waderyan** [comment]
@mhegazy I believe so. Do you think this is on VSC's end?

**Comment by mhegazy** [comment]
I would be inclined to look at VSCode first.

**Comment by waderyan** [comment]
@joebehymer thank you for the clarification. I misunderstood.

**Comment by waderyan** [comment]
@DavidRigglemanININ I have recreated this issue on our end and we are looking into it. Moving back to VSC (apologize for the switching back and forth).
