### ISSUE TITLE
Can't use union type with function in rest params

### ISSUE THREAD

**Issue by donaldpipowitch** [Microsoft/TypeScript#10825]
**TypeScript Version:**  1.8.0 /2.1.0-dev

**Code**

```ts
interface Bar {
  merge(...rules: Array<number | string>): void;
}
const bar = {};
(bar as Bar).merge(1, 's');

interface Foo {
  merge(...rules: Array<() => void | string>): void;
}
const foo = {};
(foo as Foo).merge(() => {}, 's');
                           // ^~~~ error
```

**Expected behavior:**

It should work.

**Actual behavior:** 

`...rules: Array<number | string>` and `1, 's'` works, but `...rules: Array<() => void | string>` with `() => {}, 's'` throws an error.

**Comment by kitsonk** [comment]
```typescript
interface Foo {
  merge(...rules: Array<(() => void) | string>): void;
}
```

You want a function that returns `void` or a `string`, not a function that returns `void` or `string`. Right?

**Comment by RyanCavanaugh** [comment]
There is a parsing ambiguity
```ts
() => void | string
// ^ means...
() => (void | string)
// ... not this
(() => void) | string
```
Based on user feedback both guesses are wrong exactly 50% of the time.

**Comment by donaldpipowitch** [comment]
Thank you both. You're right!
