### ISSUE TITLE
ES6 Computed Properties

### ISSUE THREAD

**Issue by JsonFreeman** [Microsoft/TypeScript#1082]
ES6 allows an arbitrary expression as the name of a property. The syntax is like this:
```ts
var x = {
   ["some" + "arbitrary" + "name"]: 0
}
```

Here is my current proposal for supporting this feature:

Computed expressions would be allowed in the following places if target is ES6:
* Object literal properties
* Class methods and accessors (both static and instance), but not property declarations.
* 'this' references are not allowed in computed properties.
* No parameter properties
* Do not allow in interfaces
* No enum members

Below ES6:
* Computed properties are not allowed

Note that emit for all of the above is straightforward.

Type check:
* All computed names must be of type string, number, or any (or eventually symbol)
* No property will be added to the containing type based on a computed name.
* Computed names that are not well known do not add a property to the type, but they will be included in the union type for the indexer, if the containing type has an indexer.

Questions:
* Should an unknown name cause the surrounding type to have an indexer, if it wouldn't have acquired one otherwise? Our decision here is 'no'. Here is an argument for and against:

Argument for - we would want this to work:
```ts
var n = "some " + "unknown " + "name";
var obj = {
    [n]: 0;
};
var num = obj[n]; // This should be number
```

Argument against - Computed properties would be allowed in class properties, so someone might have a class hierarchy like this:
```ts
var n = "some " + "unknown " + "name";
class C {
    [n]: number;
}
class D extends C {
   foo: string; // Error because C was given an implicit indexer that D inherited, but foo doesn't conform to the indexer
}
```

**Comment by JsonFreeman** [comment]
Here is an interesting question. One thing that seems apparent is that we should check that the computed properties in a class conform to the indexer declared by that class. It seems equally natural to do this if the indexer is inherited. The question is, what about inherited computed properties? These properties never actually appear on the type, so one can argue that they do not get inherited. On the other hand, we know they are there!
```ts
class Base {
    ["name"]() { }
}
class Derived extends Base {
    [s: string]: number; // Error?
}
```

**Comment by JsonFreeman** [comment]
Assigning to @ahejlsberg for spec integration.

**Comment by danquirk** [comment]
Could we just close this and make a new issue for spec work if this one was just to track the dev work?

**Comment by JsonFreeman** [comment]
Opened a separate issue to track the spec work.

**Comment by ahejlsberg** [comment]
@JsonFreeman @mhegazy Regarding downlevel emit for computed properties, for the example
```typescript
func({ before: 0, [computed]: 1, after : 2 });
```
we could use temporary variables and the comma operator to emit
```typescript
func((_a = { before: 0 }, _a[computed] = 1, _a.after = 2, _a));
var _a;
```
This would work in any expression context and we already have the infrastructure in place to track and emit the temporary variable declaration (from my work on downlevel destructuring).

**Comment by JsonFreeman** [comment]
Yes, that is a good idea. I will open two issues, one for downlevelling computed properties, and one for allowing them in class property declarations.

**Comment by JsonFreeman** [comment]
@ahejlsberg I opened #1840 and #1841

**Comment by noggin182** [comment]
Can we have an explanation as to why we disallow 'this' ? I believe the following code is valid ES6 and it worked in my limited testing (only tested chrome using the console).

```typescript
toObject() {
    let o = {
        [this.idField]: 12,
        name: "dummy"
    };
    return o;
}
```

I can understand this may not be possible in some contexts such as member initialisers or interfaces, however why is such usage blocked when composing objects within functions?

**Comment by SaschaNaz** [comment]
@noggin182 

The following code is valid TypeScript. Maybe it was fixed after the original proposal.

```ts
class Foo {
	idField: number;
	
	toObject() {
		let o = {
			[this.idField]: 12,
			name: "dummy"
		};
		return o;
	}
}
```
