### ISSUE TITLE
can’t use 'this' in object literals with --noImplicitThis

### ISSUE THREAD

**Issue by msklvsk** [Microsoft/TypeScript#10835]
**TypeScript Version:**  2.1.0-dev.20160910

**Code**
```ts
let literal = {
  a: 1,
  getA() {
    return this.a
   // error: 'this' implicitly has type 'any' because it does not have a type annotation
  },
}

```

**Expected behavior:** there is a way to use `this` in an object literal while `noImplicitThis` enabled

**Actual behavior:** an error is shown, even with `getA: function(this: this)` notation

**Comment by yortus** [comment]
This was tried before (see PR #8382) and then reverted after the discussion in #8191.

**Comment by msklvsk** [comment]
Thanks. I gave up searching duplicates on page 2 of 50.
Then maybe we make this issue about error
> this' implicitly has type 'any' because it does not have a type annotation

when `--noImplicitThis` enabled?

**Comment by kitsonk** [comment]
Well, if you have `noImplicitThis` enabled, you have opted into ensuring that `this` is typed, even in object literals.  This works around the error:

```typescript
let literal = {
  a: 1,
  getA(this: any) {
    return this.a
  },
}
```
