### ISSUE TITLE
compileOnSave with TS 2.0.2 still not working properly

### ISSUE THREAD

**Issue by kr4uzi** [microsoft/TypeScript#10838]
**TypeScript Version:**  2.0.2

**Code**
ts-files in (project root\wwwroot)
tsconfig.json (project root):

``` js
{
    compileOnSave: true,
    compilerOptions: {
        // ...
    }
}
```

**Expected behavior:**
compiles when i hit CTRL + S
**Actual behavior:** 
does not compile (only when i hit BUILD explicitly)

on a system with a similar configuration (both vs2015 with latest patches and ts 2.0.2) it works as expected so this feature is still not working properly. the typescript folder (program files x86\MS SDK...\Typescript is added to %PATH% in both systems).

**Comment by zhengbli** [comment]
The compile-on-save on tsserver is not released yet. Though I'm confused as you said "similar configuration works as expected"? Than what is the difference in your setup?

**Comment by kr4uzi** [comment]
the difference is that one setup was dedicated purly on web-dev (the one where its not working) and the other one was rather focused on driver-dev (driver dev kits and c++ env installed). However as the former was running in a VM i just reseted it and reinstalled VS (discovered some problems with uninstalling the net core tools maybe this was what caused problems actually). 
Its working as expected now. However that comile on save feature is defenitly not consistently working because on my "driver-dev" machine it didnt work out of the box either (as many other users with the same problem state: it just started working magically).
Not sure if its reasonable to let this issue remain open now, as its working, but there is defenitly some unwanted magic happening...
