### ISSUE TITLE
Spec: Describe Ambient Module Augmentations

### ISSUE THREAD

**Issue by ethanresnick** [microsoft/TypeScript#10845]
Hi, the Typescript docs talk about being able to [augment a module from module code](https://www.typescriptlang.org/docs/release-notes/typescript-1.8.html#augmenting-globalmodule-scope-from-modules), but the current spec (so far as I could tell) doesn't say anything about module augmentations. 

(It does talk about ambient module _declarations_, but it that seems to be something different. In particular, it says [says](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#122-ambient-module-declarations) that ambient module declarations are only allowed in script code, not module code, and that the module identifier can't be relative, both of which don't apply to the augmentations.)

**Comment by mhegazy** [comment]
The spec is out-of-date on this issue. Untill the spec is updated, you can find more documentation about this in http://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation

**Comment by RyanCavanaugh** [comment]
The spec is now an "archived" artifact and we won't be tracking defects against it anymore.
