### ISSUE TITLE
Confusing error messages, invalid intellisense and no auto-complete with Tagged Unions that use string based Discriminators

### ISSUE THREAD

**Issue by KavanShaban** [microsoft/TypeScript#10849]
- VsCode:  **1.5.1**
- Typescript: **2.0.2**
- Window 10: **1607**

I create a group of tagged unions that discriminate on the **'bundle'** property which then causes a further discrimination on the values of the **'id'** property:

``` ts
export module ModIcons_climacons {
    export type DIcons_climacons = 'cloud' | 'cloud.sun' | 'cloud.moon' | 'rain' | 'rain.cloud' | 'rain.sun' | 'rain.cloud.sun' | 'rain.moon';

    export interface IIcons_climacons {
        bundle: "climacons";
        id: DIcons_climacons;
    }
}
export module ModIcons_devicon {
    export type DIcons_devicon = 'postgresql-plain' | 'postgresql-plain-wordmark' | 'postgresql-plain.colore' 
    | 'postgresql-plain-wordmark.colore' | 'nodejs-plain';

    export interface IIcons_devicon {
        bundle: "devicon";
        id: DIcons_devicon;
    }
}

export module ModIcons_dripicons {
    export type DIcons_dripicons = 'align-center' | 'align-justify' | 'align-left' | 'align-right' | 'arrow-down' | 'arrow-left' | 'arrow-thin-down' | 'arrow-right' | 'arrow-thin-left' | 'arrow-thin-up' | 'arrow-up' | 'attachment' | 'arrow-thin-right' | 'code' | 'cloud' | 'chevron-right' | 'chevron-up';

    export interface IIcons_dripicons {
        bundle: "dripicons";
        id: DIcons_dripicons;
    }
}

export module ModIcons_feather {
    export type DIcons_feather = 'eye' | 'paper-clip' | 'mail' | 'toggle' | 'layout' | 'link' | 'bell' | 'lock' | 'unlock' | 'ribbon' | 'image' | 'signal' | 'target' | 'clipboard' | 'clock' | 'watch' | 'air-play' | 'camera' | 'video' | 'disc' | 'printer' | 'monitor' | 'server' | 'cog' | 'heart' | 'paragraph' | 'align-justify' | 'align-left' | 'align-center' | 'align-right' | 'book' | 'layers' | 'stack' | 'stack-2' | 'paper' | 'paper-stack' | 'search' | 'zoom-in' | 'zoom-out' | 'reply' | 'circle-plus' | 'circle-minus' | 'circle-check' | 'circle-cross' | 'square-plus' | 'square-minus' | 'square-check' | 'square-cross' | 'microphone' | 'record' | 'skip-back' | 'rewind' | 'play' | 'pause' | 'stop' | 'fast-forward' | 'skip-forward' | 'shuffle' | 'repeat' | 'folder' | 'umbrella' | 'moon' | 'thermometer' | 'drop' | 'sun' | 'cloud' | 'cloud-upload' | 'cloud-download';

    export interface IIcons_feather {
        bundle: "feather";
        id: DIcons_feather;
    }
}

```

I then create a tagged type union of the interfaces above with one additional interface of the same shape but that allows any value in the **'id'** property:

``` ts

export interface IIconGlyphUnsafe {
    bundle: 'unsafe';
    id: string;
}

export type UAll_Icons =  iconsBase.IIconGlyphUnsafe | ModIcons_climacons.IIcons_climacons | ModIcons_devicon.IIcons_devicon 
| ModIcons_feather.IIcons_feather | ModIcons_dripicons.IIcons_dripicons;

```
# Case 1

I consume the tagged union in a simple example like so:

``` ts
class Hello {

  props: Icons.UAll_Icons;

  Test() {
    this.props = {
    };

  }
}
```

However, I get the following error message:

<img width="432" alt="image1-dripicons-highlighted" src="https://cloud.githubusercontent.com/assets/3457767/18414891/88fd9486-77a9-11e6-964b-c958268ca399.png">

The message on line 2 is arbitrarily stating the type is not assignable to **'IIcons_dripicon'** which is 1 of the 5 tagged union types.

**Expected behavior:** The message should state the type is not assignable to one of the five union types like 

>  iconsBase.IIconGlyphUnsafe | ModIcons_climacons.IIcons_climacons | ModIcons_devicon.IIcons_devicon 
> | ModIcons_feather.IIcons_feather | ModIcons_dripicons.IIcons_dripicons
# Case 2

Now when I actually specify the **'bundle'** property which acts as the tag for this union with a value that is **not** part of the union's discriminator I get the following even further confusing message:

<img width="565" alt="image2-badtoken-dripicons-again" src="https://cloud.githubusercontent.com/assets/3457767/18414892/9345bc8e-77a9-11e6-9648-c06b9dccd7da.png">

So the messages on line 3 & 4 state that **'bundle'** property has the invalid value **'someBadToken'** and that it is not assignable to **'"dripicons"'**.

**Expected behavior:** The message should state that the **'bundle'** property is not assignable to any of the following 5 possible values:

> "unsafe" | "climacons" | "devicon" | "dripicons" | "feather"

**Another Expected behavior:** The **bundle'** property should be highlighted at this stage with the not assignable message with all of the values listed above.

**Another Expected behavior:** Auto-complete should be available with the list of appropriately scoped **'bundle'** property values.
# Case 3

When I begin to input the **'id'** property I get an intellisense tooltip that shows invalid values based on the value of the **'bundle'** property, see this screenshot:

<img width="470" alt="image4-bad-intellisense-for-id-property" src="https://cloud.githubusercontent.com/assets/3457767/18414921/7837fedc-77ab-11e6-9dca-835fcfe65314.png">

What is being shown is a listing of all possible **'id'** values across the entire type union .

**Expected behavior:**  The **'id'** values should scope to the interface specified in **'bundle'**.  In this case it should only show values from **'devicon'** interface.

**Another Expected behavior:** Auto-complete should be available with the list of appropriately scoped **'id'** property values.
# Source Code of Example

The source code for this issue is available here:

[Typescript-Play.zip](https://github.com/Microsoft/TypeScript/files/465744/Typescript-Play.zip)

I also just want to say that is a very powerful and welcome feature and has enabled some extremely powerful scenarios for our code.

Keep up the great work!

**Comment by RyanCavanaugh** [comment]
All of these issues have either been fixed or are working as intended.
