### ISSUE TITLE
Invalid codegen for "export default class" on target=es5, module=es6

### ISSUE THREAD

**Issue by lhecker** [Microsoft/TypeScript#10855]
**TypeScript Version:**  nightly (2.1.0-dev.20160911)

**Example:**
```ts
export default class Test {}
```

compiled with `tsc --target es5 --module es6 ...`:

**Expected output:**
```ts
var Test = (function () {
    function Test() {
    }
    return Test;
}());
export default Test;
```

**Actual output:** 
```ts
var Test = (function () {
    function Test() {
    }
    return Test;
}());
```

**Workaround:**
```ts
class Test {}
export default Test;
```
yields the correct output.

<hr/>

I guess this could be quite an easy bug for someone knowledgeable in the internal workings of `tsc` to fix, right? Otherwise if someone could give me a pointer where to start searching for this I'd of course also be up to fix it myself. 🙂

**Comment by yortus** [comment]
This was working in `2.1.0-dev.20160906` and broken in `2.1.0-dev.20160907`. Suspect the new transformation-based emitter merged that day has created a regression?

**Comment by andrejbaran** [comment]
Looks like more things got broken by `2.1.0-dev.20160907`. #10800

**Comment by rbuckton** [comment]
Support for `--target es5 --module es6` has not yet been added to the new emitter, but will be available shortly.

**Comment by lhecker** [comment]
Thanks @rbuckton! 🙂
