### ISSUE TITLE
feedback: array type

### ISSUE THREAD

**Issue by gertcuykens** [Microsoft/TypeScript#10858]
Probably a few years too late :) It's not really a stackoverflow question nor a proposal, more like feedback from a user.

To me `[]T` would be a much nicer language specification 
```
let list: []number = [1, 2, 3];
let list: Array<number> = [1, 2, 3];
```

then `T[]`
```
let list: number[] = [1, 2, 3];
let list: Array<number> = [1, 2, 3];
```

Sorry, remember just feedback and couldn't find an existing proposal for this.

**Comment by basarat** [comment]
> To me []T would be a much nicer language specification

Very unlikely to change. 

* Just curious if you have seen this in another language before? 

You can already just use `Array<T>` if `T[]` is annoying. I think `T[]` only made it in because generics design was lagging and TypeScript wanted to get itself out there for feedback before any competition made it in. I personally use `T[]` all time :rose:

**Comment by gertcuykens** [comment]
Yes golang :) https://tour.golang.org/moretypes/7

**Comment by mhegazy** [comment]
Well. as you have noted. this is a few years late at best. i do not think we will be introducing a new way to define arrays.

**Comment by gertcuykens** [comment]
Yep, I understand but just make sure that when some day if you are working on a major typescript release that would break things anyway, you have a clear overview of all suggestions. In case of Swift for example they used to break things on a daily bases and to my surprise users got used to it. The end result was objective c who was the most backward compatible thing you can imagine got dropped like a hammer. Just proof that if it walks like a duck and quacks like a duck people want chicken haha :P
