### ISSUE TITLE
Types error

### ISSUE THREAD

**Issue by WebStyle** [Microsoft/TypeScript#10856]
**TypeScript Version:**  1.8.10 

**Code**

```ts
let myString: string = '123';

myString += 123123;

console.log(myString); // returns number
```

**Expected behavior: Type 'number' is not assignable to type 'string'. **

**Actual behavior: 123123123 (number, no error) **

**Comment by shelby3** [comment]
In JavaScript, the + operator coerces a number to a String (or vice versa depending on precedence, which is [the famous design mistake of JavaScript](http://programmers.stackexchange.com/questions/90203/why-is-so-bad-for-concatenation)).

I presume TypeScript honored this idiomatic JavaScript flaw.

**Comment by WebStyle** [comment]
But TypeScript had to correct this design mistake.

**Comment by kitsonk** [comment]
@WebStyle it is following the runtime coercion of JavaScript.  It actually returns a string, not a number:

```typescript
let myString: string = '123';

myString += 123123;

console.log(typeof myString); // logs: string (not number)
```

This is more the domain of a linter, as the type system in this case is sound.  Number `123123` is being implicitly coerced at runtime.  Others may actually depend upon this implicit coercion although the intent is pretty poor and confusing.  What is one person's design mistake is another person's feature.

**Comment by shelby3** [comment]
In this case, I would argue it would be better to break the purist design goals of TypeScript, and introduce a new string concatenation operator (e.g. `#` or `++`) which is erased to `+` in the emitted output, but which only coerces to String (never from String to Number) or which never coerces. So then you would have the option to use this new operator to get more clear compilation results and expression of intent.

**Comment by RyanCavanaugh** [comment]
The intent here is that string concatenation with other types is super common and idiomatic, e.g.
```ts
let message = 'Error code ' + response.code + ' was returned from the server'.
```
Forcing you to call `toString` here is really cumbersome, and is doubly annoying in debug messages where it may not be safe to do so:
```ts
// No problem if I wrote "got undefined from server" to console
console.log('DBG: Got '+ x + ' from server');
```

`str += num` is certainly slightly more suspicious than the above examples, but for consistency's sake we generally want `x = x + y` to be identical in behavior to `x += y`
