### ISSUE TITLE
Reuse files between different module models

### ISSUE THREAD

**Issue by pankleks** [Microsoft/TypeScript#10852]
Hi - it's more a question rather than issue.
I have front-end (web-app) and backend (nodejs).
I would like to reuse some TS files between both. However my front-end is compiled without modules (using `outFile` to compile all into single file) and node use `commonjs`.
Both `es6` target.

Tried different options but I can't find a way to structure the file so it compiles on both.
I really wish to avoid introducing modules on front-end side.

My backend file looks like this:
```ts
export class ShareMePlease {
}
```
To use it at front-end I need to wrap it with namespace:
```ts
namespace Shares {
  export class ShareMePlease {
  }
}
```
However, to use it then on backend side, I would need to add `export` before namespace, but then it won't compile anymore in front-end.

I even tried to compile all shared files as separate project - to generate JS and D.TS - which I would then include into both solutions - but really same problem remains. Either node won't see it as module I can include or front-end requires modules.

Any solutions without moving front-end to modules?

**Comment by RyanCavanaugh** [comment]
FYI Saturday and Sunday are not working days for most employees in the United States.

Our general recommendation here would be to write your front-end with modules and use a bundler like webpack or rollup (rather than `--outFile`) to produce a single .js file that would run natively in the browser. This is what most people seem to be doing.

**Comment by basarat** [comment]
> I really wish to avoid introducing modules on front-end side.

Change your wishes please. The whole JS ecosystem is now pro npm + module all things :rose:
