### ISSUE TITLE
Extend external modules declared in @types npm dependency

### ISSUE THREAD

**Issue by nicojs** [Microsoft/TypeScript#10859]
**TypeScript Version:**  nightly (2.0.0-dev.201xxxxx)

**Code**

```ts
npm i @types/estree;

// myESTreeExtension.ts
declare module 'estree' {
    interface MyAddon {
   }
}

// Some other file.ts
import * as estree from 'estree';

let a: estree.Node; // ERROR: [ts] Module ''estree'' has no exported member 'Node'.
```

**Expected behavior:**

I would expect i can extend an external module as described here: #280 

**Actual behavior:** 

The ambient module in `myESTreeExtension.ts` *overrides* the `@types/estree` types

Remark: I'm a big fan of the new work flow with @types. Great job!

**Comment by mhegazy** [comment]
make sure the file that contains the [module augmentation](http://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation) is itself a [module](http://www.typescriptlang.org/docs/handbook/modules.html) (i.e. includes at least one top-level `import` or `export`).

so this should work:

```ts
import * as estree from 'estree';

declare module 'estree' {
    interface MyAddon {
   }
}
```

**Comment by nicojs** [comment]
Thanks @mhegazy, this works. When using the extensions you need to do this:

```ts
import * as estree from 'estree';
import 'myESTreeExtension';

let a: estree.Node; // Works
let b: estree.MyAddon; // Works as well
```

**Comment by Volox** [comment]
Sorry to ask here since the bug is closed but i have a similar problem with KoaJS definitions [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types-2.0/koa/index.d.ts).

The Koa definition file looks like this:
```typescript
declare namespace Koa { }
export = Koa;
declare namespace Koa {
    export interface Context extends Request, Response {
    }
    // ... more things
}
declare class Koa extends EventEmitter {
   // ... things
}
```

And i want to be able to do something like (as suggested [here](https://github.com/koajs/koa/blob/v2.x/docs/api/index.md#settings) and [here](https://github.com/koajs/koa/blob/v2.x/docs/api/index.md#appcontext)):
```typescript
import * as Koa from 'koa';
const server: Koa = new Koa();
server.name = 'UrbanScope';
server.context.db = db; // server.context is Koa.Context
```

But i keep getting **TS2339** errors from `tsc` like:
```
src/server.ts(60,10): error TS2339: Property 'name' does not exist on type 'Koa'.
src/server.ts(63,18): error TS2339: Property 'db' does not exist on type 'Context'.
```

---

Following your advice i created a `augment.ts` file with:
```typescript
import * as Koa from 'koa';
import { Db } from 'mongodb';
declare module 'koa' {
    namespace Koa {
        interface Context {
            db: Db,
        }
    }
    class Koa {
        name?: string;
    }
}
```

But the errors are still there 😨 , i tried with a number of export/namespace/class/declare combinations with no luck. **Any idea on how to solve it?**

**Comment by mhegazy** [comment]
given the way Koa is authored extending the class is not possible. as for the interface context, you should be able to do that as:

```ts
import * as Koa from 'koa';
import { Db } from 'mongodb';

declare module 'koa' {
        interface Context {
            db: Db,
        }
}
```

**Comment by Volox** [comment]
It works!
Thanks for you support!

**Comment by tals** [comment]
I am having a similar issue, but for interface merging (adding new interfaces works just fine).

```ts
// index.d.ts for Router5
declare module 'Router5' {
   // ...
   interface Router {
       // ....
       stop(): Router;
   }
}
```

```ts
// some_extension.ts
import * as Router from 'router5';
declare module 'router5' {
    interface Router {
        foo(): void;
    }
}
```

```ts
// test.ts
import { Router } from 'router5';
import 'some_extension';

function test(router: Router) {
    router.foo(); // this is ok
    router.stop(); // TS2339: Property 'stop' does not exist on type 'Router'.
}
```

**Comment by ivanpadavan** [comment]
And what should I do if package starts with `@`?

**Comment by trusktr** [comment]
I'm trying to extend a class, but it seems to override the whole class with my new definition. F.e.:

```ts
import * as THREE from 'three'

declare module 'three' {
	export class OrbitControls {
		setCamera( cam: THREE.Camera ): void
	}
}
```

Now my code has no errors when using the `setCamera` method, but there is now a type error on the use of all the other stuff in the `OrbitControls` class, so it looks like the `@types/three` version was replaced with my version.

How do we extend the class defintion of a module?
