### ISSUE TITLE
Cannot merge built-in DOM interfaces

### ISSUE THREAD

**Issue by jpzwarte** [Microsoft/TypeScript#10861]
**TypeScript Version:**  2.0.2

**Code**

```ts
interface Document {
  readonly mozFullScreenElement: Element;
}

console.log(document.mozFullScreenElement);
```

**Expected behavior:**
No compile errors (1.9.0-dev did not output any errors)

**Actual behavior:** 
Property 'mozFullScreenElement' does not exist on type 'Document'.

**Comment by kitsonk** [comment]
I am not getting any issues in 2.0.2.

It is likely that this code is contained in a module and you are not addressing the global interfaces.  For example this works when dealing with augmenting global interfaces in a module:

```typescript
declare global {
	interface Document {
		readonly mozFullScreenElement: Element;
	}
}

console.log(document.mozFullScreenElement);

export default {};
```

**Comment by jpzwarte** [comment]
Thanks, that did the trick!
