### ISSUE TITLE
Salsa - Recognize dynamically added object properties

### ISSUE THREAD

**Issue by abgivant** [Microsoft/TypeScript#10868]
I have been trying to use Visual Studio Code as my primary editor, and one thing I've noticed as far as the JS intellisense goes, is that intellisense is provided for object properties that are statically defined when an object is declared, but it is not for properties dynamically added to the object after it has been declared. Are there currently any plans to support this feature?

Example:

![image](https://cloud.githubusercontent.com/assets/3431954/18445174/e605baee-78e1-11e6-83c0-c441b288e2a1.png)

Thanks!

**Comment by mhegazy** [comment]
We have been thinking about this scenario lately. we are experimenting with "evolving" types with assignments.

**Comment by abgivant** [comment]
Cool. Would that change also include a type change following through a reassignment? 

**Example:**

![image](https://cloud.githubusercontent.com/assets/3431954/18446847/a6f58a52-78e9-11e6-8945-876a973f5e26.png)
![image](https://cloud.githubusercontent.com/assets/3431954/18446852/aa0b670c-78e9-11e6-992b-b0230d5a2164.png)

In this case, `arr2` was initialized without a type, then later assigned to be an array, but this change doesn't get picked up, as its type is still displayed as `any`.

**Comment by mhegazy** [comment]
yes. the proposal so far applies to:
```ts
var x = {};
x.a = 0;

var y = [];
y.push(1);

var z = null;
z = {a: 0};

var w;
w = [1,2];
```

you can read more about this in https://github.com/Microsoft/TypeScript/issues/10566

**Comment by abgivant** [comment]
Just checking in, but has any work or additional discussion happened regarding this issue recently?

**Comment by kukoss** [comment]
Hello, please, is there any update regarding this issuse?

**Comment by Arlen22** [comment]
This one is huge for me, and the only alternative I can think of is to download the Visual Studio Community edition, but that is a huge installation for my laptop.

It would be incredibly useful to have this functionality.

**Comment by barisusakli** [comment]
SublimeText3 does this really well but I think it uses some kind of search to find definitions.

**Comment by kukoss** [comment]
@barisusakli I have to be honest with you, WebStorm is so far the best editor I worked with. It's fully customizable and its intelli sense is great. For javascript and typescript. However it is a paid option (50 per yer), it saves lots of time :)

**Comment by Ethefor** [comment]
It's affect me too in VSCode, I hope that there some chances to fix this :)

**Comment by PRossetti** [comment]
I'm having the exact same issue. I have already lost several hours of my time trying to make it work. I can't understand how can Atom and Sublime Text do this but VS Code doesn't.
All I want is the go to definition / find all references to work in my angularjs / javascript proyect throw all .js files but it isn't working at all.
Are you working on it? Would it ever work?

**Comment by icetbr** [comment]
Same applies for the following I believe:
```
var a = {
  c: 2,
  b() {
    return this.c;
  }
}
```

**Comment by realjeffbrooks** [comment]
Any update on this one? I run into this a fair bit.

**Comment by TimvdEijnden** [comment]
Yes I'd also like an update about this please.

**Comment by pursehouse** [comment]
looks like this specific feature has been asked for in several places for years... still not done? It exists in Eclipse...

file1.js
foo = {};

file2.js
foo.bar = {};

file3.js
test = foo.bar;

those foo and bar references in file3.js are both navigable as references to the definitions in file1&2

**Comment by pgross41** [comment]
I have what I assume is the same issue, I am using backbonejs so there are a lot of object expressions. It does not recognize any of the functions/variables. For example, `this.render` on line 4 is unable to "go to definition"

```
var document = Backbone.View.extend({
    
    initialize: function() {
        this.listenTo(this.model, "change", this.render);
    },
    
    render: function() {
        console.log('rendering');
    }
    
});
```

**Comment by spitWind** [comment]
Why it can not dynamically add properties

**Comment by spitWind** [comment]
it Support??
```
var w={};
function chang(w) {
    w.__proto__=Array.prototype;
}
chang(w);
w//want to be type Array
```

**Comment by sandersn** [comment]
Salsa now supports the most common patterns of dynamically adding properties, as explained [on the wiki](https://github.com/Microsoft/TypeScript/wiki/Type-Checking-JavaScript-Files), so I will close this issue. Please open new issues for specific patterns that are still not supported.

**Comment by nicothed** [comment]
I'd like to switch to VS Code (from Webstorm) for my Node.js app, but this might be a deal breaker. I need to be able to type F12 (or "Go to Definition") for functions from imported modules.
Are there Extensions one can install to allow this seemingly very basic function? 
Webstorm has been doing it forever, and interestingly, my functions come up in the intellisense, but still can't see the definition.

Update:
After a bit of fiddling, I see that adding this at the top seems to ease some of the pain:
var du = {}            // short for dishlyUtils
module.exports = du

du.myFunc() { ... }

works, except from within the same module.

Ah, and if I put this line at the end of file, it seems to work everywhere!??
module.exports = du

I don't understand how Microsoft could mess up such an essential and honestly quite basic functionality (I remember using it a lot in 2000 in Visual Studio.Net already).

**Comment by sandersn** [comment]
@nicothed Can you open a new issue for the bug you found? I'd like to track each issue separately, and yours looks different from the specifics of the original bug.

You can also try `typescript@next`. I improved typing of `module.exports` within its own file recently. You can npm install it and then point VS Code to its folder with `"typescript.tsdk": "/path/to/typescript/next"`.

**Comment by sloantash** [comment]
I'd just like to chime in that I too wish this basic functionality worked better. My use case is like this:
function SomeConstructor() {
    var self=this;
    self.foobar = function(){
        ...
    }

    self.foobar();
}
       ^^^ Hovering here and clicking go to definition or find all references shows no results. As mentioned, Sublime and Atom both handle this flawlessly. Please work this out!

**Comment by white-room** [comment]
Seems like a pretty basic use case and I was surprised that the functionality is missing. Really a pain if you prefer factory functions instead of classes.

**Comment by marcusx2** [comment]
Will this be added, like, ever?
