### ISSUE TITLE
Nightly: super calls are not working

### ISSUE THREAD

**Issue by jods4** [Microsoft/TypeScript#10862]
**TypeScript Version:**  nightly (2.0.0-dev.20160912)

**Code**
```ts
class Base {
  protected frob() { }
}

class Derived extends Base {
  protected frob() {
    super.frob();
  }
}
```

**Expected behavior:** Working code ;)

**Actual behavior:** When compiled for ES5, crash with _Unable to get property 'call' of undefined or null reference._
Generated code in Derived:
```ts
  _super.frob.call(this);
```
The problem seems to be that `_super` is `Base` instead of `Base.prototype`, where `frob` is (correctly) found.

I don't know if this makes a difference, but `frob` actually was `async ` methods in our codebase.

**Comment by mhegazy** [comment]
`_super` is captured in the scope. the output looks like:

```ts
var Derived = (function (_super) {
    __extends(Derived, _super);
    function Derived() {
        _super.apply(this, arguments);
    }
    Derived.prototype.frob = function () {
        _super.prototype.frob.call(this);
    };
    return Derived;
}(Base));
```

I believe the issue here is that your base class is declared after the derived class.

**Comment by mhegazy** [comment]
I should add, the code posted above is the output i get from `typescript@2.1.0-dev.20160912`. if this is not what you see, then there is something else going on; please share more context to be able to reproduce the issue.

**Comment by jods4** [comment]
@mhegazy for some reason the generated code in my context was `_super.frob.call(this)`, notice the `.prototype` part is missing. 
Not sure why, as I said this was in an `async` method (both base and derived).

The base class is imported from another module (with option to compile to ES5 AMD).

**Comment by jods4** [comment]
@mhegazy I spent some time trying to build a short repro.
It turns out that it is the `async` modifier that breaks the codegen.

```ts
class Base {
    frob() {}
}

class Derived extends Base {
    async frob() {
        super.frob();
        await 2;
    }
}
```

Generated code (I skip the boilerplate helpers): 
```ts
var Base = (function () {
    function Base() {
    }
    Base.prototype.frob = function () { };
    return Base;
}());
var Derived = (function (_super) {
    __extends(Derived, _super);
    function Derived() {
        _super.apply(this, arguments);
    }
    Derived.prototype.frob = function () {
        return __awaiter(this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0:
                        _super.frob.call(this);
                        return [4 /*yield*/, 2];
                    case 1:
                        _a.sent();
                        return [2 /*return*/];
                }
            });
        });
    };
    return Derived;
}(Base));
```

Note that the super call in derived `_super.frob.call(this)` is missing the `.prototype` part.
