### ISSUE TITLE
Include can't include from node_modules

### ISSUE THREAD

**Issue by Pajn** [Microsoft/TypeScript#10864]
**TypeScript Version:**  2.0.2

**Code**

```ts
{
  // ..
  "include": [
    "src/**/*",
    "node_modules/tscomp/typings/**/*"
  ],
  // ..
}
```

**Expected behavior:**
The files in node_modules/tscomp/typings should be included in the build.

**Actual behavior:** 
The files in node_modules/tscomp/typings are not included included in the build no matter if the `tscomp` modules is npm linked or npm installed. However if I copy the files to the same package and change the include to `"typings/**/*"` the files are correctly included.

Another problematic cases seems to be including from a parent folder, `"../../typings/**/*"` doesn't work either.

**Comment by mhegazy** [comment]
Do you have an `exclude` property set?

**Comment by Pajn** [comment]
No, just the include option.
I created a simple project which shows the problem, just `npm install` and `tsc`
[ts.zip](https://github.com/Microsoft/TypeScript/files/477606/ts.zip)

I included `"moduleResolution": "node"` but even if I completely remove `compilerOptions` the problem remains.

**Comment by mhegazy** [comment]
thanks i will take a look. but if exclude is not specified, one is infered and it includes `node_modules`. so try an empty exclude array.

**Comment by Pajn** [comment]
The empty exclude array worked!

I see why it would default to ["node_modules"] if you haven't specified anything, but if you did specify "files" or "include" then node_modules should either already be excluded because they aren't white-listed, or be white-listed. So in that case maybe TS should default to an empty array instead?

**Comment by mhegazy** [comment]
Excludes (implicit or explicit) take precedence over include. 

Originally we started with no  implicit excludes, but ppl have found that to be too noisy as you get too many errors that you usually do not care about. and just for completeness the implicit exclude is `["node_modules", "bower_components", "jspm_packages", <outDir>]`.

Having a conditional exclude is not really straight forward once you put in globs in the mix.
