### ISSUE TITLE
tsx attribute formatting removes bracket spacing

### ISSUE THREAD

**Issue by waderyan** [Microsoft/TypeScript#10872]
_From @bookman25 on September 9, 2016 18:8_

- VSCode Version: 1.5.1
- OS Version: Windows 10

Steps to Reproduce:

1. TypeScript Version: 2.*
2. `<input value={ this.state.value } />`
3. Format document

**Expected behavior:**
In **1.8.10** the spacing inside the brackets was unchanged on format operation (closing bracket `}` or format document).
`<input value={ this.state.value } />`

**Actual behavior:** 
In **2.*** the space inside the brackets is always removed when formatting.
```ts
<input value={this.state.value} />
```

Looks like it might be related to: https://github.com/Microsoft/TypeScript/pull/9361

_Copied from original issue: Microsoft/vscode#11791_

**Comment by SaschaNaz** [comment]
VSCode should support `InsertSpaceAfterOpeningAndBeforeClosingJsxExpressionBraces`, I'm not sure currently it does.

**Comment by waderyan** [comment]
[Issue](https://github.com/Microsoft/vscode/issues/12046) added to September milestone on VS Code's side.

**Comment by mhegazy** [comment]
as noted by @SaschaNaz, this already fixed in https://github.com/Microsoft/TypeScript/pull/9361. You will need to specify the formatting option `InsertSpaceAfterOpeningAndBeforeClosingJsxExpressionBraces: false`.

**Comment by mhegazy** [comment]
the VSCode setting would be:
```json
"typescript.format.InsertSpaceAfterOpeningAndBeforeClosingJsxExpressionBraces": false
```
