### ISSUE TITLE
Show inferred types on hover

### ISSUE THREAD

**Issue by wallverb** [Microsoft/TypeScript#10884]
**TypeScript Version:**  Version 2.1.0-dev.20160911

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
interface Test {
    values: string[]
}

const test: Test = {
    values: [] // type: undefined[] on hover
}
```

When you hover `values: []` in VSCode it will show type: `undefined[]` which in theory one could say - 'working as intended' - but would be great if type could be inferred at this level and show to user `string[]`

**Comment by jods4** [comment]
This has been brought up several times in the past, e.g. #3667, #6118, #10484.

The good news is that a fix seems to finally be near: #10610. :tada:
