### ISSUE TITLE
make comparison expressions type guards for literal numeric types

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#10880]
nightly build, September 12, 2016

```typescript
const direction = Math.random() > 0.5 : -1 : +1;
if (direction > 0) {
    // expected direction to be > 0 (+1)
} else {
    // expected direction to be <= 0 (-1)
}
```

**Comment by mhegazy** [comment]
I do not think we want to do numeric type arithmetic at the time being. the complexity involved does not seem to match the utility to be frank. now every comparison operator could be considered a narrowing location.
