### ISSUE TITLE
--lib has no effect when directly passing a file to tsc

### ISSUE THREAD

**Issue by kourge** [Microsoft/TypeScript#10897]
**TypeScript Version:**  2.0.2

**Code**

`tsconfig.json`:
```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["es6"],
    "module": "commonjs"
  },
  "files": [
    "./test.ts"
  ]
}
```

`test.ts`:
```ts
export function foo(): Promise<number> {
  return Promise.resolve(3.14);
}
```

**Expected behavior:**

The compilation succeeds and emits:
```js
"use strict";
function foo() {
    return Promise.resolve(3.14);
}
exports.foo = foo;
```

**Actual behavior:** 

- When invoking `tsc` with no options, the compilation succeeds and emits the expected JavaScript.
- When invoking `tsc test.ts` from project root, the error output is:
```
test.ts(1,24): error TS2304: Cannot find name 'Promise'.
test.ts(2,10): error TS2304: Cannot find name 'Promise'.
```

This is not limited to promises: using anything that is defined by `lib.es6.d.ts` but not `lib.es5.d.ts`, such as using `Array.prototype.find`, will result in this.

**Comment by mhegazy** [comment]
invoking `tsc` with no commends forces the compiler to walk up and find a matching `tsconfig.json`. if you have at least one source file on the command line this process is not done, and the assumption is you are passing all files.

Please see https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/tsconfig.json.md#using-tsconfigjson for more details.
