### ISSUE TITLE
tsconfig.json completely ignored in Visual Studio 2015 (Update 3) Typescript > 1.7

### ISSUE THREAD

**Issue by m-a-zhou** [Microsoft/TypeScript#10891]
**TypeScript Version:**  1.8.0 and 2.0 RC

**My tsconfig**

```ts
{
  "compilerOptions": {
    "noImplicitAny": false,
    "noEmitOnError": true,
    "removeComments": false,
    "sourceMap": true,
    "target": "es5",
    "outDir": "./Scripts"     
  },
  "exclude": [
    "node_modules"    
  ]
}
```
I tried already different settings in the file - but nothing works.

My Solution structure:
- SharePoint 2013 App Project template
- Dev.-Env.: SharePoint 2013 on-prem. / Visual Studio 2015 (Update 3)
- OS: Windows Server 2012 R2

I've tried TypeScript 1.8 and 2.0 RC. Both are not working correct in Visual Studio 2015. As soon if I add a tsconfig file to the project root, the typescript file will not be compiled (transpiled - no js file). When I move the tsconfig file in a different directory, the TS-file will be compiled but without the defined settings in the tsconfig.
I've checked the PATH to the TypeScript Installation folder and everything is correct. 
Also I missing the TypeScript configuration section within the project properties. I've only:
- Application
- Build
- Build Events
- Debug
- Resources
- Reference Paths
- Signing
- SharePoint
- Code Analysis

Any help would be great!

**Comment by mhegazy** [comment]
Do you have an import to the TypeScript targets in your project file? Can you share the project file? or at least a build log with `/verbosity: diagnostic`

**Comment by cveld** [comment]
Have you inspected your csproj file? Could be that the msbuild TypeScript
directives are missing or incorrect. At least this was the case at some
point in the time in the past. OOTB there was no support for TypeScript
embedded in the template. You can diagnose yourself by creating a project
with the TypeScript project template and then compare the generated csproj
with the other one. Take special notice of a possible enforcement of a
specific TypeScript version.

2016-09-15 21:52 GMT+02:00 Mohamed Hegazy <notifications@github.com>:

**Comment by mhegazy** [comment]
Please reopen if this is still an issue and you have more information.

**Comment by jpmnteiro** [comment]
If someone stumbles upon issue and can't figure why VS is not picking up your tsconfig.json: make sure your tsconfig.json's build action is set to Content (select the file, go to Properties and check Build Action).

**Comment by Jehoel** [comment]
I'm having the same problem, but I'm in a Visual Studio Website project, not a Web Application project, so there is no `.csproj` file.

**Comment by vmandic** [comment]
@jpmnteiro you are my hero... thank you so much for this small but invaluable detail. Worked like a charm.

**Comment by RussKie** [comment]
@jpmnteiro - champion!

@mhegazy it is something you guys need to get fixed. There is no indication why `tsconfig.json` isn't being read.
