### ISSUE TITLE
[Errors] multiple class inheritance

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#109]
```TypeScript
class C extends A, B {} 
```

Expected: 

!!! Classes can only extend a single class.

Actual: 

!!! '{' expected.!!! ';' expected.

**Comment by DickvdBrink** [comment]
Also fixed on master
Test can be found here: https://github.com/Microsoft/TypeScript/blob/master/tests/baselines/reference/classExtendsMultipleBaseClasses.errors.txt

**Comment by danquirk** [comment]
Thanks for the triage help, not sure how this slipped through :)
