### ISSUE TITLE
Allow undefined from ProxyHandler<T>.getOwnPropertyDescriptor 

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#10904]
From https://github.com/Microsoft/TypeScript/pull/10550

Currently, with `strictNullChecks` enabled, the `getOwnPropertyDescriptor` hook cannot be correctly implemented as all code paths must return a valid `PropertyDescriptor`.

Reference: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/handler/getOwnPropertyDescriptor

**Comment by mhegazy** [comment]
Fixed by https://github.com/Microsoft/TypeScript/pull/10550

**Comment by olivr70** [comment]
As I commented on the #10550 PR, 

it looks like a later commit has undone this patch. It is not present in the current version

``` Typescript
interface ProxyHandler<T> {
    //...
    getOwnPropertyDescriptor? (target: T, p: PropertyKey): PropertyDescriptor;   
    //...
}
```
