### ISSUE TITLE
Filesystem race when creating directories

### ISSUE THREAD

**Issue by vbraun** [microsoft/TypeScript#10909]
**TypeScript Version:**  1.8.10

I'm using a makefile to build a largeish typescript project. Parallel build occasionally (randomly) fails with 

```
$ make -j10
[....]
error TS5033: Could not write file 'path/to/file.js': EEXIST: file already exists, mkdir 'path/to'
```

Serial build works fine, but is slow. Unfortunately its random so not that easy to debug.

This looks like the usual filesystem race condition to look out for:

```
if (!pathExists(path)) {
    // Race condition in parallel processes
    mkdir(path);
}
```

instead do the race-condition-free (asking for forgiveness)

```
try {
    mkdir(path);
} catch (error) {
    if (isEEXISTS(error)) {
        // ignore, directory exists
   } else {
      raise error;
  }
}
```

**Comment by mhegazy** [comment]
This does not handle all the race conditions though, writing files is another one that happens frequently. but i suppose no harm in hardening the filesystem calls.

**Comment by pizza2code** [comment]
Note that this occurs outside of parallel Typescript builds: It just occurred with my Gulp build, where the HTML file generator made the destination directory before Typescript.  Also using version 1.8.10

**Comment by RyanCavanaugh** [comment]
This is properly handled now
```ts
                    try {
                        _fs.mkdirSync(directoryName);
                    }
                    catch (e) {
                        if (e.code !== "EEXIST") {
                            // Failed for some other reason (access denied?); still throw
                            throw e;
                        }
                    }
```
