### ISSUE TITLE
Type Inference Regression

### ISSUE THREAD

**Issue by tomwanzek** [Microsoft/TypeScript#10901]
**TypeScript Version:**  TypeScript@next (2.1.0-dev.20160912 or 2.1.0-dev.20160913).

Issue likely introduced in 2.1.0-dev.20160912.

**Code**

The example code is a slightly reduced version of an error which appeared as of this morning in DefinitelyTyped/types-2.0 definitions for **d3-array**. See [DT PR 11184](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/11184) which raised the error as part of its complete Travis tests. and [DT PR 11205](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/11205) for a temporary "fix".

```ts

/**
 * Administrivia: JavaScript primitive types and Date
 */
export type Primitive = number | string | boolean | Date;

/**
 * Administrivia: anything with a valueOf(): number method is comparable, so we allow it in numeric operations
 */
interface Numeric {
    valueOf(): number;
}

// Not very useful, but meets Numeric
class NumCoercible {
    public a: number;

    constructor(a: number) {
        this.a = a;
    }
    public valueOf() {
        return this.a;
    }
}

/**
 * Return the min and max simultaneously.
 */
export function extent<T extends Numeric>(array: Array<T | Primitive>): [T | Primitive, T | Primitive] | [undefined, undefined] {
   // do what D3's d3-array module's extent function would do
}


let extentMixed: [Primitive | NumCoercible, Primitive | NumCoercible] | [undefined, undefined];
extentMixed = extent([new NumCoercible(10), 13, '12', true]);
```

**Expected behavior:**

```ts
extentMixed = extent([new NumCoercible(10), 13, '12', true]);
```

Should compile without error inferring the return type correctly to be implicitly given as `[Primitive | NumCoercible, Primitive | NumCoercible] | [undefined, undefined]`

This worked as expected up until likely the 2.1.0-dev.20160912 build.

**Actual behavior:** 

The code _fails, unless_ the type parameter is explicitly set:

```ts
extentMixed = extent<NumCoercible>([new NumCoercible(10), 13, '12', true]);
```
The implicitly given return type of `extent(...)` is otherwise inferred as `[Primitive | Numeric, Primitive | Numeric] | [undefined, undefined]` causing an error.

**Comment by ahejlsberg** [comment]
This is an effect of #10676. The issue is that when inferring from a union type to a union type, we eliminate identical matches on both sides (e.g. when inferring from `string | string[]` to `string | T` we eliminate `string` on both sides), but this currently doesn't work when the source side is a numeric or string literal type and the target side is `number` or `string`. It's pretty easy to fix, I will put up a PR soon.

**Comment by tomwanzek** [comment]
Thanks a lot for the quick response! Most appreciated.
