### ISSUE TITLE
Imported object is possibly null

### ISSUE THREAD

**Issue by jods4** [Microsoft/TypeScript#10914]
**TypeScript Version:**  2.0.2
**Code**

``` ts
import { profile } from 'System/security';
// profile: { token: string } | null

function f(x: { n: number } | null) {
  return x && x.n;
}

function g() {
  return profile && profile.token;  // Error: object is possibly null
}
```

**Expected behavior:** Both functions should compile.

**Actual behavior:** `profile` in `profile.token` is underlined with "object is possibly null".

I don't know why, the code compiles locally (see `f`) but breaks when using an imported variable (see `g`).

**Comment by ahejlsberg** [comment]
I think the issue may be that we only narrow symbols that are classified as variables (and therefore not an imported alias for a variable). I'm guessing it works if you first assign `profile` to a local variable and then narrow that.

**Comment by RyanCavanaugh** [comment]
It's been fixed
