### ISSUE TITLE
Type '{}' is not assignable to type 'void' if using class method with generic

### ISSUE THREAD

**Issue by cevek** [Microsoft/TypeScript#10913]
**TypeScript Version:**  2.1.0-dev.20160905

**Code**

```ts
class X<T> {
    foo<F>(callback?: (value: T) => F) {
    }
}

let y: X<void> = null as any;
let u: X<{}> = null as any;
y = u; // Error:(121, 1) TS2322:Type 'X<{}>' is not assignable to type 'X<void>'.
  // Type '{}' is not assignable to type 'void'.

// but if just without method
class Y<T> {}
let y2: Y<void> = null as any;
let u2: Y<void []> = null as any;
y2 = u2; // ok
```

**Expected behavior:**
Should be ok
**Actual behavior:** 
Throw an error

**Comment by yortus** [comment]
I don't think your `X` example is related to your `Y` example. See code below:

```ts
// void and {} are not assignment-compatible
let x: void;
let y: {};
x = y; // ERROR: '{}' is not assignable to 'void'
y = x; // ERROR: 'void' is not assignable to '{}'


// All instances of Y are structurally identical regardless of T
class Y<T> {} // this is equivalent to type '{}' for any T
class Foo {} // this is also equivalent to type '{}'
let a: Y<string[]>; // or Y<void> or Y<{}> or anything, all the same
let b: Foo;
a = b; // OK - structurally compatible
b = a; // OK - structurally compatible
```

**Comment by cevek** [comment]
Ok, so, can you please explain to me what it is `void` type?
Why I can assign to void generic
```ts
let a: Promise<void> = new Promise<number>(resolve => resolve(1));
```

```ts
class Y<T> {
	foo<F>(p: F): T{
		return {} as any;
	}
}
let a: Y<string[]>; 
let b: Y<void>;
b = a;  // ok
```

**Comment by mhegazy** [comment]
> Ok, so, can you please explain to me what it is void type?

`void` is a type with no values, it represents the lack of a value. `void` can be thought of as an alias for the `undefined` return value from functions (fall through if no return statement is available); it has a special meaning for functions/methods, methods that return no value. using it in  contexts other than return type of a function would be misleading.
Given that `void` is the empty set, in the example, you can assign any thing to a `void`, but you can not assign `void` to anything.

**Comment by mhegazy** [comment]
more can be found at http://www.typescriptlang.org/docs/handbook/basic-types.html#void

**Comment by cevek** [comment]
Thank you for detailed explaination!

**Comment by bbmattieu9** [comment]
`export class AuthGuard implements CanActivate {`
`constructor( private user: UserService){ }`
` canActivate(
    next: ActivatedRouteSnapshot,
    state: RouterStateSnapshot): boolean{
    return this.user.getUserLoggedIn();
  }
}`

Im getting  error TS2322: Type 'void' is not assignable to type 'boolean'. I'm not sure what i did wrong.

**Comment by mhverbakel** [comment]
The given example now fails:
```ts
let a: Promise<void> = new Promise<number>(resolve => resolve(1)); // Type 'Promise<number>' is not assignable to type 'Promise<void>'. => 'number' is not assignable to type 'void'.
```

What changed?
