### ISSUE TITLE
Type Gaurds Don't Narrow Type in Inner Functions

### ISSUE THREAD

**Issue by ethanresnick** [Microsoft/TypeScript#10927]
**TypeScript Version:**  2.0.2

**Code**

```ts
  function isNumber(test: number|string): test is number {
    return typeof test === "number";
  }
  function blah(arg: () => void): void { }

  let x: any = 4;

  if(isNumber(x)) {
    x; // x is correctly narrowed to number here
    blah(() => {
      x; // typeof x is any again
    })
  }
```

**Expected behavior:**
(I think) `x` should still be inferred as type number in the inner function.

**Actual behavior:** 
`x` is inferred as `any`

**Comment by wallverb** [comment]
https://github.com/Microsoft/TypeScript/issues/7719#issuecomment-202684512

**Comment by ahejlsberg** [comment]
FYI, it works as expected if you use `const` instead of `let` because the compiler then knows that `x` will never be reassigned.

**Comment by ethanresnick** [comment]
Got it. Thanks!
