### ISSUE TITLE
Emit declaration file for variable that has inferred type to be type-alias should use its alias name only when the symbol is accessible

### ISSUE THREAD

**Issue by yuit** [Microsoft/TypeScript#10923]
Original bug is #10625 which is fixed in release-2.0 by emit inferred type-alias in declaration file with its value. A more desirable approach is to emit using its alias name if the name is accessible and if it is an external-module the the module of type-alias and the module of inferred location is the same.

**Comment by mhegazy** [comment]
The fix we have no in place sees to do what we need at the moment. we can revisit this later if needed.
