### ISSUE TITLE
No Red Squiggles after updated to Typescript 2.0.2.0 Beta

### ISSUE THREAD

**Issue by MCKRUZ** [Microsoft/TypeScript#10936]
**TypeScript Version:**  1.8.0 / nightly (2.0.0-dev.201xxxxx)
2.0.2.0 Beta
**Code**
I updated with the visual studio plugin and NPM and I still can't get Visual Studio to recognize errors with the red squiggle.  If I run TSC I get the errors but not automatically in studio.

**Expected behavior:**
To see the errors
**Actual behavior:** 
I don't see any errors.

**Comment by mhegazy** [comment]
anything else that is not working? colorization? completion? goto definition? etc..

**Comment by MCKRUZ** [comment]
nothing is working at all.  I have to run TSC in order to compile.  It looks like basically the VS add in doesn't work at all.  I have already uninstalled and reinstalled it.

**Comment by mhegazy** [comment]
This is slightly better than just the errors not working. sounds like an installer issue. 

can you uninstall all TS versions you have from add/remove programs. make sure you have the latest Update3 installed (https://msdn.microsoft.com/en-us/library/mt752379.aspx), then reapply TS 2.0.2.

Also please share your install logs after that. the logs i am interested in should be in `%temp%` and should start with `dd_TypeSCript*`.

**Comment by MCKRUZ** [comment]
That seemed to have did the trick thank you.
