### ISSUE TITLE
Offer to navigate to implementation(s) of a function

### ISSUE THREAD

**Issue by chrmarti** [microsoft/TypeScript#1093]
Currently navigation using VS commands ends at interfaces. A "navigate to implementation(s)" action on function definitions would be great.

**Comment by zhangenming** [comment]
like it

**Comment by DanielRosenwasser** [comment]
Duplicate of #6209 (even though this issue is older). This now exists in the form of `Go To Implementation`. You can view the command via the Command Palette in VS Code.
