### ISSUE TITLE
Referencing an exported namespace causes compilation error when using --declaration flag

### ISSUE THREAD

**Issue by nchen63** [Microsoft/TypeScript#10933]
**TypeScript Version:**  2.0.2

**Code**

moduleA.d.ts
```ts
export interface A {
    b: number;
}
export as namespace moduleA;
```

moduleB.ts
```ts
module moduleB {
    export interface ILoveMom {
        math: moduleA.A;
    }
}
```

Compiled with `declaration: true`

**Expected behavior:**
No error
**Actual behavior:** 
an error is given
```
src/moduleB.ts(3,15): error TS4033: Property 'math' of exported interface has or is using private name 'moduleA'.
```

You can download the code from here: https://github.com/nchen63/typescriptRepro

**Comment by nchen63** [comment]
@mhegazy is this related to #10544?

**Comment by mhegazy** [comment]
it is similar.

**Comment by mhegazy** [comment]
thanks @nchen63!
