### ISSUE TITLE
A require call that isn't the global require will clobber bindings

### ISSUE THREAD

**Issue by krisselden** [Microsoft/TypeScript#10931]
**TypeScript Version:**  1.8.0 / nightly (2.0.0-dev.201xxxxx)
typescript@beta or typescript@next
**Code**

```ts
// A *self-contained* demonstration of the problem follows...
import require from "some/module"

export foo from "some/other/module"

require("a single arg")

```

**Expected behavior:**
has a binding for foo
**Actual behavior:** 
require() call expression is not checked for scope, that it is the module's require or that externalModuleIndicator already is present, it will redefine the symbol.

workaround in a custom host `getSourceFile`

```
      Object.defineProperty(sourceFile, "commonJsModuleIndicator", {
        get: () => sourceFile["externalModuleIndicator"]
      });
```

**Comment by mhegazy** [comment]
> `export foo from "some/other/module"`

you mean `export {foo} from "some/other/module"`

> require() call expression is not checked for scope,

I do not understand what you mean. can you provide more context.

**Comment by krisselden** [comment]
sorry, here is the real example

https://github.com/emberjs/ember.js/blob/master/packages/ember-metal/lib/index.js#L181

**Comment by mhegazy** [comment]
and what is wrong with this require call? i did not understand the original problem.

**Comment by krisselden** [comment]
It hits here, it already has the symbol, an externalModuleIndicator but it is going to assign `file.symbol = ` again
https://github.com/Microsoft/TypeScript/blob/master/src/compiler/binder.ts#L1870

**Comment by krisselden** [comment]
This require is not node's or commonjs require, it is local, but the call expression does not check where the function came from.

**Comment by krisselden** [comment]
I suppose I can rename the import to something else so it doesn't confuse the binder but seems annoying since it actually knows this require is local but it does a very simple check https://github.com/Microsoft/TypeScript/blob/master/src/compiler/utilities.ts#L1296

**Comment by mhegazy** [comment]
is this a .js file?

**Comment by krisselden** [comment]
Yes

**Comment by krisselden** [comment]
We have some typescript in the project, right now we transpile it separately, I'm working on compiling it together so it is easier to add more or convert.

**Comment by krisselden** [comment]
I guess I could do `import eriuqer from "require";` to get the require from our custom loader.

**Comment by mhegazy** [comment]
thanks, i get it now.

**Comment by mhegazy** [comment]
no wait.. i misspoke.. here is my repro:

```cmd
C:\test\sandbox7>tsc --v
Version 2.1.0-dev.20160912

C:\test\sandbox7>type src\m.js
import require, { has } from "./c"

if (has('ember-debug')) {
  require('ember-debug');
}
C:\test\sandbox7>type src\c.js
export default function require(a) { }

export function has(a) { return true }

C:\test\sandbox7>tsc --allowjs src\m.js --outDir dist

C:\test\sandbox7>type dist\m.js
"use strict";
var c_1 = require("./c");
if (c_1.has('ember-debug')) {
    c_1["default"]('ember-debug');
}

C:\test\sandbox7>type dist\c.js
"use strict";
function require(a) { }
exports.__esModule = true;
exports["default"] = require;
function has(a) { return true; }
exports.has = has;
```

**Comment by mhegazy** [comment]
what did i miss?

**Comment by krisselden** [comment]
add ```export function hello() {
}``` to the top of `m.js`

add another file and import it, you will get `m" has no exported member 'hello'.`

**Comment by mhegazy** [comment]
still same output.

```cmd
c:\test\sandbox7>type src\m.js
import require, { has } from "./c"

export function hello() { }

if (has('ember-debug')) {
  require('ember-debug');
}

c:\test\sandbox7>type src\m2.js
import { hello } from "./m";

hello();
c:\test\sandbox7>tsc --allowjs src\m2.js --outDir dist

c:\test\sandbox7>type dist\m2.js
"use strict";
var m_1 = require("./m");
m_1.hello();

c:\test\sandbox7>type dist\m.js
"use strict";
var c_1 = require("./c");
function hello() { }
exports.hello = hello;
if (c_1.has('ember-debug')) {
    c_1["default"]('ember-debug');
}

```

**Comment by krisselden** [comment]
mv `m2.js` to `m2.ts` it should result:

```
➜  repro ./node_modules/.bin/tsc --allowJs --outDir dist src/m2.ts
src/m2.ts(1,10): error TS2305: Module '"repro/src/m"' has no exported member 'hello'.
➜  repro
```

then comment out the require and try again

```
➜  repro ./node_modules/.bin/tsc -v
Version 2.1.0-dev.20160914
```

**Comment by krisselden** [comment]
It isn't actually specific to one file being typescript, there is an ordering issue, but that for some reason reproduces in the simple example.

**Comment by krisselden** [comment]
@mhegazy did you try that last example? if you want I can push it to an repo, but it was literally just changing the extension.

**Comment by mhegazy** [comment]
yes i do. thanks for the info.
