### ISSUE TITLE
JSDOC function parameter type is not supported

### ISSUE THREAD

**Issue by danielo515** [Microsoft/TypeScript#10946]
VsCode Versión 1.5.2 (1.5.2)

**Code**

``` js
/* This works with intellisense 
 * @param {Function} fn - the function 
* This does not work
 * @param {function} fn2 - the second function
*/
```

**Expected behavior:**

I expect intellisense to be case agnostic and provide types for both params indicating their type as function.

**Actual behavior:** 

In the second case the type is indicated as `any`

**Comment by aluanhaddad** [comment]
But the language is case sensitive and `function` and `Function` mean different things.

**Comment by danielo515** [comment]
Sure it is, but this is about documentation, not typings.

If so, why does it show `any` if I put function in lowercase instead of function? And why then `string` and `String` seem to be supported ?

**Comment by RyanCavanaugh** [comment]
The upper-case type `String` is the type of objects created from the `String` constructor (the one you should never user).

The lower-case type `string` is the type of primitive string values.

The upper-case type `Function` is the type of instances of the global constructor function `Function`.

The lower-case type `function` doesn't exist. You could write `type function = (...args: any[]) => any;` if you wanted something equivalent.
