### ISSUE TITLE
Void method in if clause

### ISSUE THREAD

**Issue by sant123** [Microsoft/TypeScript#10942]
**TypeScript Version:**  1.8.0 

Is it a bug?

**Code**

```ts
class fsClass {
	exists(path: string, cb?: (exists: boolean) => void): void {

	}
}

var fs = new fsClass();

if(fs.exists("")){
	
}
```

**Expected behavior:**
Raise an error telling a void type is not permitted.

**Actual behavior:** 
No error.

**Comment by RyanCavanaugh** [comment]
We currently consider anything to be coercable to truthy/falsy. Might be dangerous in this case.

Really seems like your callback parameter should not be optional there, though.

**Comment by sant123** [comment]
Thank you @RyanCavanaugh for your answer, well... that is an abstraction of the ```exists```  method from ```fs``` module of Node.js. I just noticed it when I was coding...

**Comment by jeffreymorlan** [comment]
https://github.com/Microsoft/TypeScript/issues/7256

**Comment by RyanCavanaugh** [comment]
Thanks @jeffreymorlan !
