### ISSUE TITLE
Named function expressions and arrow functions 

### ISSUE THREAD

**Issue by HolgerJeromin** [Microsoft/TypeScript#10947]
**TypeScript Version:**  1.8

I often use the following pattern
```ts
private __onResized(){
  let __this = this;
  return function element_onResized(evt){
    // using __this
  }
}
```

With this notation the debugger (at least in Chrome) have a nice name for the function in the stack trace and profiler...

Now i found the nice arrow functions which results in following code:
```ts
private __onResized(){
   return (evt) => {
      // using this
   }
}
```
But in the stack trace i have sometimes an unhelpful _(anonymous function)_ 
Is there an alternative?

**Comment by kitsonk** [comment]
Arrow functions cannot be named, they are explicitly anonymous.  If you want them to not be anonymous, you cannot use the shorthand.  TypeScript is just following the specification of ES2015 in this case.

**Comment by RyanCavanaugh** [comment]
Note that in an ES6-compliant runtime, a function expression which initializes a variable will inherit the name of the variable. So you can write
```ts
const handler = () => { this.whatever };
return handler;
```
and you *should* (depending on your engine compliance level) see `handler` in the stack trace (again, if you're targeting ES6).

**Comment by HolgerJeromin** [comment]
Thanks for the explanation Ryan Cavanaugh. That is probably the reason sometimes the names are available.
