### ISSUE TITLE
[Strict null checks] Hoisted variables should be usable without assignment

### ISSUE THREAD

**Issue by JannesMeyer** [Microsoft/TypeScript#10940]
**TypeScript Version:**  2.0.2 with strictNullChecks

**Code**

```ts
if (isMaximised) {
    var onClose = () => {
        /* code */ 
    };
}
console.log(onClose); // Error: Variable 'onClose' is used before being assigned
```

**Expected behavior:**
`onClose` should have the type `() => void | undefined` and be usable. In my opinion the warning about usage before assignment is only necessary when strictNullChecks is off.

**Actual behavior:** 
`onClose` has the type `() => void` and it doesn't compile when being used.

**Comment by mhegazy** [comment]
the compiler could not guarantee that this variable is used before it was initialized. if your intention is to treat it as `() => void | undefined` add a type annotation.
