### ISSUE TITLE
Type intersection of type arguments is not inferred

### ISSUE THREAD

**Issue by kevinder** [microsoft/TypeScript#10944]
**TypeScript Version:**  1.8.0

**Code**

``` ts
interface Foo<T> {
    foo: T;
}

declare function getFooValue<T>(foo: Foo<T>): T;

declare const foos: Foo<string> & Foo<number>;

const value = getFooValue(foos);
```

**Expected behavior:**
`value` has type `string & number`

**Actual behavior:** 
Error: `The type argument for the type parameter 'T' cannot be inferred from the usage`

The error clearly makes sense in the general case, but for our particular case, `Foo<A> & Foo<B>` behaves like `Foo<A & B>` and we want to take advantage of that. Are there any workarounds for getting the desired behavior?

**Comment by ahejlsberg** [comment]
You can explicitly specify the type parameter:

```ts
const value = getFooValue<string & number>(foos);
```

In your case `Foo<string> & Foo<number>` is actually structurally compatible with `Foo<string & number>`, it's just that we can't infer it.

**Comment by kevinder** [comment]
Right, we found that workaround. Our goal is to avoid the explicit specification, because the pattern in our code is that the types are not necessarily known at the call site and there could be a very large number of them. Are there any other potential workarounds that avoid this?

**Comment by RyanCavanaugh** [comment]
This has been fixed
