### ISSUE TITLE
[Proposal] Add functionality to generic types

### ISSUE THREAD

**Issue by Artur-A** [Microsoft/TypeScript#10954]
When we have generic type in a method currently there is only one possibility to use it, which is a helpful feature with auto static check for the correct return type.

**Type name**
In one implementation I tried to get a bucket of events by generic type name, similar to [EventAggregator](https://msdn.microsoft.com/en-us/library/ff921122.aspx) in .NET .
```ts
public GetEvent<TEvent>():TEvent{
     // typeof only works with instances

     // any attempt to use TEvent shows as 'TEvent is undefined', 
    //  so cannot even check some variable instance by 'bool isMyType = varable instanceof TEvent'
}
```
TEvent becomes untouchable in this situation. No doubt that there are a lot of limitations in transpiling TS to ES5 and currently the result will be pure JS ``` function GetEvent(){}```, but perhaps there is a solution to this problem, e.g. put private string variable in the function with actual TEvent type, or something else.
This is apparently a more general problem of ES as there is no notion of a class/function as a type except [type Object] and some primitive types.

**Activator**
One more handy feature might be creating a new instance by use of a generic type.

Now possible
```ts
public NewInstance<TEventType>(eventClass: { new (): TEventType }): TEventType{
   let newEvent = new TEventType();
}
// also possible if eventClass argument will have an interface type with a static constructor declaration
```
Desired behaviour(currently not possible)
```ts
public NewInstance<TEventType>(): TEventType{
   return new TEventType();
}
```

Related: #[Covariance / Contravariance Annotations] https://github.com/Microsoft/TypeScript/issues/1394

**Comment by mhegazy** [comment]
TypeScript's type system is one that is fully erasable (please see [design goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals#goals) for more information). this means that types do not exist at runtime; what does exist are values. so a function that takes a constructor function as an argument can new it, but not one that does not. 

Moreover, types in TypeScript are compared structurally. so knowing the shape of a type does not mean you can construct it at runtime.

Having said this, this suggestion is currently out of scope for the TS project.

I would recommend reading some of the [FAQ's about how the TypeScript type system works](https://github.com/Microsoft/TypeScript/wiki/FAQ#type-system-behavior).

**Comment by Artur-A** [comment]
Thank you Mohamed for the clarification.
