### ISSUE TITLE
tsc CLI: allow boolean options to have explicit false value

### ISSUE THREAD

**Issue by alexeagle** [Microsoft/TypeScript#10967]
I have some .d.ts files referenced in the project (from Angular 2) which are not compatible with `--strictNullChecks`.
I want to enforce strict nulls within my own project though. So I have `tsconfig.json` with `'strictNullChecks': true` specifically to direct my editor to underline these.
In our google-internal build system, we have our own tsc wrapper that does specific type-checks (and uses a different generated `tsconfig.json` so this all works fine in the build.
But, users benefit from being able to just run a vanilla `tsc` command on the command line to diagnose setup issues.

So, I'd like to be able to override any setting in the `tsconfig.json` with a command-line option. In some cases I can do so (eg `--target=es5` overrides `'target': 'es6'`) but with boolean options only the `true` value can be passed, eg `--strictNullChecks`

I propose `--strictNullChecks=false` be accepted on CLI

**Comment by evmar** [comment]
(In case anyone else is wondering, I checked the tsc source and it appears that there's no e.g. --noStrictNullChecks way of passing in false.)

**Comment by mhegazy** [comment]
we can add a look-ahead for boolean-based flags, and consume the result iff it is `true`|`false`.

**Comment by RyanCavanaugh** [comment]
Accepting PRs for this

**Comment by mhegazy** [comment]
thanks @HerringtonDarkholme!
