### ISSUE TITLE
Tuple allows access at any index

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/TypeScript#10965]
Version: 2 rc

Given:

``` ts
    const cell: [ number, number ] = [ 0, 1 ];
    const y = cell[100]
    y
```

I expect `cell[100]` to error, but it doesn't. `y` has a type of number. This means it's very easy to me to have bugs whereby I'm asking for an index that doesn't exist (like asking for a property that doesn't exist on an object).

**Comment by aluanhaddad** [comment]
This works because indexing is not verified. You can always index. What is weird is that `cell[100]` has type `number`, I would expect it have the same type as `cell['100']`, that is type `any`.

**Comment by yortus** [comment]
The current behaviour is to give 'unknown' elements the union of the tuple element types. It's clearer to see if the tuple has different element types:

```ts
const cell: [ string, number ] = [ '0', 1 ];
const u = cell[0];
u // u is string
const v = cell[1];
u // u is number
const y = cell[100]
y // y is string | number
```

But personally I don't think that's a logical deduction for the type system to make. All bets are off for indexes outside the tuple range. At runtime they are likely to return `undefined`.

**Comment by aluanhaddad** [comment]
@yortus what I find odd is this

```TypeScript
const cell: [ string, number ] = [ '0', 1 ];
const u = cell['0'];
u // u is string
const v = cell['1'];
u // u is number
const y = cell[100]
y // y is string | number
const y = cell['100']
y // y is any
```

**Comment by Igorbek** [comment]
See a proposal of fixing this #6229

**Comment by RyanCavanaugh** [comment]
Duplicate #5203

**Comment by OliverJAsh** [comment]
I noticed this as well, sort of related. Can anyone explain why?

``` ts
    const xs = [1,2,3];
    const x5 = xs[5]; // type is number, expected number | undefined
```
