### ISSUE TITLE
Human edits leaking into generated lib.d.ts files

### ISSUE THREAD

**Issue by indiescripter** [microsoft/TypeScript#10963]
**TypeScript Version:**  2.1.0 / nightly (2.1.0-dev.20160916)

I made my first contribution & PR to this project recently in respect of issue #10949.  See https://github.com/Microsoft/TypeScript/issues/10949

In the process I went a bit dizzy trying to figure out why, after building via gulp local and then gulp LKG, and then doing a compare against HEAD, that a lot of files in the (generated) lib directory had changed.

Initially I dismissed this observation as it just being my unfamiliarity with the project repository as a new comer so I just committed the single file that I changed, namely, src/lib/es2015.proxy.d.ts.

As it turns out, the generated files in /lib are not gitignored and are thus tracked in the repo.  IMHO this goes against the accepted wisdom of _not_ placing generated files under direct version control.  Unless I am mistaken, not abiding by this rule appears to have lead to misfortune as per issue title.

**Evidence**
Recent committed editing of /lib/lib.es2015.proxy.d.ts contains a "fix" as follows:

``` ts
  getOwnPropertyDescriptor? (target: T, p: PropertyKey): PropertyDescriptor | undefined;
```

Whereas /src/lib/es2015.proxy.d.ts contains:

``` ts
  getOwnPropertyDescriptor? (target: T, p: PropertyKey): PropertyDescriptor;
```

Accordingly it pretty much looks like editing & commit for that particular fix took place in /lib (which is ultimately supposed be generated) rather than in /src/lib as should have been the case (and which is the instruction on CONTRIBUTING.md).

**Remedy**
Something for the project admins to consider but I'd humbly suggest to gitignore just about anything which is generated from _source version control_. Making and versioning a _distribution_ of generated stuff in general should not be confused with the former. Naturally my suggestion requires some rethink of the build/distribution process as well.

**Comment by RyanCavanaugh** [comment]
The CI build should validate that this does not happen

**Comment by mhegazy** [comment]
thanks @johanssj for looking into this. a PR would be appreciated.

**Comment by weswigham** [comment]
We now have a bot that calls out edits to these files in PRs 😄
