### ISSUE TITLE
Error span is on entire return expression for incompatible return type

### ISSUE THREAD

**Issue by JsonFreeman** [Microsoft/TypeScript#1097]
```ts
function f(): number {
    return (() => {
         return "";
    })();
}
```

The whole lambda is squiggled. We should have logic to determine the best span for error reporting, given a node.

**Comment by mhegazy** [comment]
Closing for housekeeping purposes. The behavior outlined in the OP has been in place for over 18 month now and have not got any updates on this issue. Please file a new issue if an action is required.
