### ISSUE TITLE
Chained promises produce incorrect types

### ISSUE THREAD

**Issue by MaximBalaganskiy** [Microsoft/TypeScript#10977]
**TypeScript Version:**  nightly (2.1.0-dev.20160918)

**Code**

``` ts
class A {
    json(): Promise<any> {
        return Promise.resolve({});
    };
}

function test() {
    let p = Promise.resolve(new A());
    p.then(x => x.json()).then(x => x.b);
}
```

**Expected behavior:**
Compiled without errors

**Actual behavior:** 
Compiled with an error

```
error TS2339: Property 'b' does not exist on type 'A'.
```

**Comment by yortus** [comment]
I can repro this. This made it a bit clearer:

```ts
function test() {
    let p1 = Promise.resolve(new A());  // p1 is Promise<A>
    let p2 = p1.then(x => x.json());    // p2 is Promise<A>, but should be promise<any>
    let p3 = p2.then(x => x.b);         // x is A, but should be any
}
```

The incorrect inference ocurrs on the `let p2...` line and is a result of [choosing the first](https://github.com/Microsoft/TypeScript/blob/9d4219acf17e6b1e20279a331db12e13e94d4b58/src/lib/es2015.promise.d.ts#L11) `then` overload from the `Promise<T>` definition in `lib.d.ts`.

It looks like a result of the changes to the `then` overloads made recently in #10448.

**Comment by wizzard0** [comment]
Also, Promise.all is still inferred incorrectly sometimes.

**Comment by blakeembrey** [comment]
Just updated from `2.1.0-dev.20160911` to `2.1.0-dev.20160928` and run into this. Something simple like `Promise.resolve({}).then(() => 'test')` will now have the return type of `Promise<{}>` instead of `Promise<string>`.

**Comment by doxiaodong** [comment]
same with 2.1.1,

**Comment by jwbay** [comment]
Another problem I hit and a non-obvious workaround (shortened from RWC) --

```ts
function test2() {
    return new Promise<number>(resolve => {
        fetch('').then(response => {
            //without the cast, value below is Response and resolve() errors
            return response.json() as Promise<number>; 
        }).then(value => {
            resolve(value);
        });
    });
}
```

**Comment by Offirmo** [comment]
This is a major bug !

**Comment by Iezious** [comment]
same with 2.1.4

**Comment by Alexander-Taran** [comment]
2.0.10 got the same behavior, Had to switch back to 2.0.7

**Comment by doxiaodong** [comment]
@Alexander-Taran, 2.0.10 is not same as 2.1.x in my code.

**Comment by AlexanderEkdahl** [comment]
You can be explicit and use then<T> which let's you specify the result of your then block.

**Comment by MaximBalaganskiy** [comment]
There is a difference between can and must. This is clearly a serious
regression

**Comment by raijinsetsu** [comment]
This is huge. Could we get an official statement? This is preventing us from upgrading to 2.1 because all of our Promise chains fail to compile.

**Comment by rbuckton** [comment]
The changes made to the definition of `Promise` were added to address issues with assignability (#10524) and strict null checks. Just changing the order of the overloads does not solve the problem, as some ordering works better with strict null checks turned on, but makes things worse with strict null checks turned off. 

I am currently investigating a solution that seems to be giving the right answer in all of these cases, but it needs further testing and discussion before I can put up a PR.

**Comment by FriOne** [comment]
@mhegazy this isn't fixed for me. I use https://github.com/shlomiassaf/angular2-modal and this module have types problem from above 2.0.10. 
```
let modal = this.modal.open(AddFolderDialogComponent, {context: new AddFolderContext(parentFolder)});
    modal
      .then(dialog => dialog.result)
      .then((folder: Folder) => this.store.dispatch(new AddFolderAction(folder)))
```
`open()` returns `Promise<DialogRef<any>>`, `DialogRef.result` contains `Promise<any>`, I get an error:

> TS2345: Argument of type '(folder: Folder) => void' is not assignable to parameter of type '(value: DialogRef<any>) => void | PromiseLike<void>'.
>   Types of parameters 'folder' and 'value' are incompatible.
>     Type 'DialogRef<any>' is not assignable to type 'Folder'.
>       Property 'id' is missing in type 'DialogRef<any>'.

If I'm wrong, please, show me a way to fix it.

**Comment by Offirmo** [comment]
I confirm, this issue isn't fixed in typescript 2.2. This is a huge blocker !

**Comment by MaximBalaganskiy** [comment]
It's got 2.3 tag. Fixed in there

**Comment by FriOne** [comment]
@MaximBalaganskiy Hm, this is a huge blocker as @Offirmo sad. I can't update typescript and angular because it depends on 2.1 now. Also 2.1 has object spreading :( @mhegazy Why it was moved to 2.3?

**Comment by Offirmo** [comment]
@MaximBalaganskiy 2.3 isn't available in npm yet...

**Comment by MaximBalaganskiy** [comment]
`npm install typescript@next -g` should install the latest

**Comment by FriOne** [comment]
@MaximBalaganskiy Sorry I understood you incorrectly. I thougth 2.3 is unavailable yet.
