### ISSUE TITLE
Tagged union common property types are not narrowed

### ISSUE THREAD

**Issue by farism** [Microsoft/TypeScript#10976]
**TypeScript Version:**  2.0.2-rc

**Code**

```ts
interface MovePayload {
  type: string;
  active: boolean;
}

interface MoveAction {
  kind: 'move';
  payload: MovePayload;
}

interface ChatPayload {
  type: string;
  message: string;
}

interface ChatAction {
  kind: 'chat';
  payload: ChatPayload;
}

type Action = MoveAction | ChatAction

function move(payload: MovePayload) {
  console.log(payload)
}

function reducer({ kind, payload }: Action) {
  switch (kind) {
    case "move":
      return move(payload)
  }
}

reducer({ kind: 'move', payload: { type: 'forward', active: false } })
```

**Expected behavior:**
Type of payload argument passed to `move` function should be `MovePayload`

**Actual behavior:**
`TS2345: Argument of type 'MovePayload | ChatPayload' is not assignable to parameter of type 'MovePayload'`

Of course, doing `move(payload as MovePayload)` works correctly.

**Comment by farism** [comment]
Actually.. I think this is working as expected. I believe the issue lies with doing the destructure in the reducer, i.e.

```ts
function reducer({ kind, payload }: Action)
```

Because I haven't switched on the `kind` at this point, flow control analysis cannot narrow down the type of `payload`. The following works fine

```ts
function reducer(action: Action) {
  switch (action.kind) {
    case "move":
      return move(action.payload)
  }
}
```

This is obviously user error, but I'm wondering if there is a way to make this a bit more ergonomic?

**Comment by mhegazy** [comment]
once an object is destructed, the compiler can no longer make any assumptions about the relationships between the parts. Doing so requires data-flow analysis and alias tracking which is not trivial tasks.

**Comment by felixfbecker** [comment]
This would be really nice to have. I find myself often writing type guards inside `filter()` callbacks
```ts
const elements = new Observable<HTMLElement | null>()
elements.pipe(
  filter((element): element is NonNullable<typeof element> => !!element)
)
```

which is painful if you just want to narrow the type of one property/tuple element, because you need to repeat the type of the other members and cannot use destructuring:

```ts
const mouseOvers = new Observable<MouseEvent>()

mouseOvers.pipe(
  withLatestFrom(elements),
  filter((data): data is [typeof data[0], NonNullable<typeof data[1]>] => !!data[1])
)
``` 

vs

```ts
mouseOvers.pipe(
  withLatestFrom(elements),
  filter(([, element]): element is NonNullable<typeof element> => !!element)
)
```
