### ISSUE TITLE
Map Constructor (again)

### ISSUE THREAD

**Issue by bfricka** [Microsoft/TypeScript#10970]
I should be able to create a `Map` instance using the constructor. I have tried typing this in various ways to no effect. I realize this relates to several other issues (tuples), but I wanted to highlight it, as it is a specific ES6 feature that TypeScript simply does not support as far as I can tell. Given the principles of the project, I feel like this should be receiving more attention than, say, the `async / await` and other features that people want.

**TypeScript Version:**  2.0.2

**Code**

```ts
interface IFoo {
  foo: string;
}

const fooMap: Map<string, IFoo> = new Map([
  ['hello', {foo: 'foo'}]
]);
```

**Expected behavior:**
This should be valid as `'hello'` satisfies 'string' and `{foo: 'foo'}` clearly satisfies `IFoo`

**Actual behavior:** 
```
 TS2345: Argument of type '[string,IFoo]' is not assignable to parameter of type 'Iterable<{},{}>'
```

**Comment by aluanhaddad** [comment]
FWIW it works in 2.1.0-dev.20160916

**Comment by mhegazy** [comment]
This is wokring fine for me. there is poribally something else going on with this:

```cmd
c:\ts>type C:\test\sandbox7\src\a.ts
interface IFoo {
  foo: string;
}

const fooMap: Map<string, IFoo> = new Map([
  ['hello', {foo: 'foo'}]
]);

c:\ts>node node_modules\typescript\lib\tsc.js --v
Version 2.0.2

c:\ts>node node_modules\typescript\lib\tsc.js --lib es6 C:\test\sandbox7\src\a.ts

c:\ts>echo %ERRORLEVEL%
0
```

**Comment by bfricka** [comment]
Thank you for looking at this. I will do some more digging and to figure out what the culprit is. If I find a scenario that brings this up again, I'll re-open.
