### ISSUE TITLE
DataTransfer.types type incorrect (or maybe just incomplete).

### ISSUE THREAD

**Issue by mitchellwills** [Microsoft/TypeScript#10979]
TypeScript Version: Latest master rev (b7d1d11ba32fe0aa01d7c06ad43c2c7f7d9ffb7f)

The type of the DataTransfer.types field does not match the spec, which seems to indicate that it should be of type DOMString[] not DOMStringList as it is today.
https://github.com/Microsoft/TypeScript/blob/b7d1d11ba32fe0aa01d7c06ad43c2c7f7d9ffb7f/lib/lib.dom.d.ts#L2191
https://html.spec.whatwg.org/multipage/interaction.html#the-datatransfer-interface

This appears to match the behavior of Chrome 53.0.2785.116; however, Firefox 48.0 shows the field being of type DOMStringList.

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.
