### ISSUE TITLE
TS2304: Cannot find name 'Promise'

### ISSUE THREAD

**Issue by vnxyz** [Microsoft/TypeScript#10985]
Using typescript 2.0.0

**Comment by kitsonk** [comment]
You really need to provide more than this.  This is not a support forum, it is for tracking issues and defects with TypeScript.  Maybe even the command line you are using to compile the project?  You really expect people to read your mind?

**Comment by kitsonk** [comment]
@whitecolor that might get it to compile in certain situations, but that may not solve the problem.  We need more information to know what is going on.  It could be the OP assumes they are targeting ES6 when by default, TypeScript targets ES5.  Your suggestion is only valid if someone is loading `es6-shim` at runtime, which the OP did not state.

**Comment by whitecolor** [comment]
> Your suggestion is only valid if someone is loading es6-shim at runtime, which the OP did not state.

Well you may not have whole es6-shim as dependency if you are targeting some platfroms that support in this case `Promise` (but not ES6), installing just types will allow to use `Promise` with typescript that compiles to ES5.

**Comment by mhegazy** [comment]
for future searches.

the default library that the compiler injects in a compilation is one for ES5 runtimes. `Promise` was added in ES6/ES2015 . So:
- If you know your engine has support of ES6 promises, e.g. node v4+, use `--lib es6` (or `--lib dom,es6` for websites).
- if you are including a shim for promise, e.g. [core-js](https://github.com/zloirock/core-js), [es6-shims](https://github.com/paulmillr/es6-shim), etc.. then `npm install @types/core-js` or `npm install @types/es6-shim`
- if you are using a different library for your promise, e.g. bluebird, then you should not be using the global `Promise` directly.
