### ISSUE TITLE
NodeSelector.querySelector should return Element | null

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/TypeScript#10992]
Currently `NodeSelector.querySelector` returns `Element`, but it should return `Element | null`

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by OliverJAsh** [comment]
Oddly I can't find the source typings for querySelector anywhere in
`src/lib` nor https://github.com/Microsoft/TSJS-lib-generator

**Comment by kitsonk** [comment]
This is [where it is in the generated XML from Edge](https://github.com/Microsoft/TSJS-lib-generator/blob/843809f44f1562c2554474512d295843ab8d47a6/inputfiles/browser.webidl.xml) which should go into the [overridingTypes.json](https://github.com/Microsoft/TSJS-lib-generator/blob/master/inputfiles/overridingTypes.json) I believe.

Why it doesn't show up at all in `src/lib` is a mystery to me as well, there must be something I don't understand...

**Comment by YuichiNukiyama** [comment]
The querySelector method is generated by F# program.  I can send PR.

**Comment by mhegazy** [comment]
thanks @YuichiNukiyama
