### ISSUE TITLE
Find all references includes base member references for override members

### ISSUE THREAD

**Issue by JsonFreeman** [Microsoft/TypeScript#1099]
```ts
class C {
    x;
}
class D extends C {
    /* start here*/x;
}

var c: C;
var d: D;
c.x; // This one should be excluded
d.x;
```

Find all references from the definition of D.x includes the reference c.x, but it should not. It is very noisy if you are only looking for references to that override member.

**Comment by mhegazy** [comment]
it works today as @CyrusNajmabadi outlined. in practice this works well, and we have not gotten any user feedback to contradict that.
