### ISSUE TITLE
New Website Logo: Lagash

### ISSUE THREAD

**Issue by PabloZaiden** [Microsoft/TypeScript#10997]
Please fill the following out:

- Name: Lagash
- Homepage url: https://www.lagash.com/
- Brand Guidelines/Licensing: https://www.lagash.com/assets/content/downloads/lagash_manual.pdf
- Logo: (svg if possible, pngs over 500x200px with transparent backgrounds are also acceptable): https://lagashwebsiteassets.blob.core.windows.net/lagash-assets/logo_vector.svg

**Comment by mhegazy** [comment]
Should be added in the next site refresh.
