### ISSUE TITLE
Inconsistent behavior for class construction when using accessibility modifiers

### ISSUE THREAD

**Issue by babeal** [Microsoft/TypeScript#11006]
It seems that parameters passed to a constructor with an accessibility modifier are guaranteed to be assigned before any other constructor code or property assignment code.  However, if you don't provide a modifier and assign the reference yourself, then property assignment will be executed before the code inside of the constructor causing any properties needing access to these assigned resources to run into null reference exceptions.  I've included an image because it was readily available and hopefully it provides clarity.  If not I will actually type out the typescript code.  

**TypeScript Version:**  2.0

**Code**

![image](https://cloud.githubusercontent.com/assets/4511994/18678814/f1cbcfc0-7f22-11e6-910b-e72671bf0030.png)

``` ts

```

**Expected behavior:**
Behavior of class construction should be the same whether accessibility modifiers are provided with constructor arguments or not.

**Actual behavior:** 
Constructor arguments with accessibility modifiers are guaranteed to be initialized before property construction.  Then the rest of the code in the constructor is executed.  This means that properties to be constructed with values passed into the constructor without accessibility modifiers can't access these properties and will throw null reference exceptions.

**Comment by RyanCavanaugh** [comment]
Here's a shorter example that is probably clearer:
```ts
class Foo {
	public x;
	constructor() {
		// L_1
		this.x = 10;
		// L_2
	}
	y = this.x * 8;
}
```

Basically, we have no way of knowing whether the correct place to insert the initializer for `y` is at `L_1` or `L_2`. It would be kind of insane, in your example, to insert the field initializer for `fetchActive$` after line 11 (why not line 13? why not line 12?). Instead, the order is just deterministic: Field initializers, followed by constructor code.

**Comment by babeal** [comment]
I disagree.  Just by adding public/private on to a constructor property I expect the same behavior as if I assign the reference myself without the accessibility modifier.  The public/private modifiers are short cuts.  For instance, the below code will produce the value 80, however, the second example will fail.  Can you explain exactly why this is the intended behavior.  It just seems so counter intuitive.  I don't care which way it works, I just care that it is consistent.  For example, if i decide I need to do some work in the constructor and remove the accessibility modifier, then working code now breaks.  I called the constructor with those properties, I would not expect side effects for the simple fact of adding a short cut modifier.  Does that make sense?  I might be missing something important.  

**Will work!**
```
class Foo {
    constructor(private x) {
        // L_1
        // L_2
    }
    y = this.x * 8;
}

console.log(new Foo(10).y);
```

**Will fail!**
```
class Foo {
    private x;
    constructor(private x) {
        // L_1
        this.x = x;
        // L_2
    }
    y = this.x * 8;
}

console.log(new Foo(10).y);
```

**Comment by DanielRosenwasser** [comment]
Class property initializers aren't dependent on whether they came before/after a class's constructor, and I don't think they should be. At this point we couldn't change the behavior anyway because that would be a breaking change.

**Comment by T18970237136** [comment]
Hi,
I think what @babeal is describing is that the order of execution is a bit surprising:

> Parameter properties, Field initializers, Constructor code

Instead, I would expect the following:

> Field initializers, Parameter properties, Constructor code

which I think would make the two examples be consistent (both would fail, not just the second one).

The actual order is the same as in the specification at 8.7.1:
```
    function <ClassName>(<ConstructorParameters>) {  
        <DefaultValueAssignments>  
        <ParameterPropertyAssignments>  
        <MemberVariableAssignments>  
        <ConstructorStatements>  
    } 
```

However, section 8.3.1 says:

>
> For example, the declaration
> ```
> class Point {  
>     constructor(public x: number, public y: number) {  
>         // Constructor body  
>     }  
> }
> ```
> is equivalent to writing
> ```
> class Point {  
>     public x: number;  
>     public y: number;  
>     constructor(x: number, y: number) {  
>         this.x = x;  
>         this.y = y;  
>         // Constructor body  
>     }  
> }
> ```

which looks like if parameter properties are set just before the executor code is run, not before field initializers are run.

**Comment by babeal** [comment]
Thanks @T18970237136, that is what I am trying to convey.  @DanielRosenwasser, yea I understand the breaking aspect, but maybe its something that could be considered later.

**Comment by RyanCavanaugh** [comment]
It's not going to stop being breaking :wink:

> Field initializers, Parameter properties, Constructor code

This order just chooses to break someone else instead:
```ts
class Foo {
	constructor(public x = 30) {
	}
	xPlusOne = this.x + 1;
}
```

**Comment by babeal** [comment]
But it looks like the default value assignment would still occur first then the rest of the initialization which seems would still result in a deterministic behavior.  I'm just asking.  When you hear "breaking change" all hope goes out the window.  We don't allow constructor modifiers in our code anyway, but this stemmed from a developer asking to use them because the NgRx Store effects examples are written in such a way where you have to use them.

**Comment by RyanCavanaugh** [comment]
Probably if we had to do it over again, the order should have been: field initializers declared before the ctor, parameter properties, field initializers declared after the ctor.
