### ISSUE TITLE
Derived interfaces

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/TypeScript#11003]
I this kind coverd by any issue currenlty?
```ts
interface Sources {
  A: SourceA
  B: SourceB
}

interface Sinks {
  A: SinkA 
  B: SinkB
}
// -> derive this from Sources and Sinks interfaces:
interface Derived {
  A: (SinkA) => SourceA
  B: (SinkB) => SourceB
}
```

**Comment by RyanCavanaugh** [comment]
I believe this would be covered by #1213

**Comment by DanielRosenwasser** [comment]
In the future, please try to be clearer in your issues. I still don't really see the connection between either issue or what you're asking.

**Comment by whitecolor** [comment]
@DanielRosenwasser sorry about that, just asked is this case covered by any issue already.
