### ISSUE TITLE
Visual Studio Duplicate identifier errors everywhere (.d.ts vs multiple .ts files)

### ISSUE THREAD

**Issue by strohhut** [Microsoft/TypeScript#11007]
**TypeScript Version:**  1.8.6 

There are many duplicate identifier issues out there that have to do with typings and node where the same d.ts files exist multiple times and the suggested solution is to use exclude. For me it's a bit different because I don't have duplicate d.ts files but am still seeing this error.

I have a folder structure like this

```
TypeScript 
  Components
    MyComponent1
  Definitions
    MyComponent1  
```

`Components/MyComponent1` has a couple of .ts files, all with the namespace `MyComponent1`. `Definitions/MyComponent1` has a .ts file that triple slash references all the .ts files from `Components/MyComponent1`. Based on this file I also generate a .d.ts file with the outFile option. So I have a `MyComponent1.d.ts` file within `Definitions/MyComponent1` that contains all the combined declarations of all the .ts files within `Components/MyComponent1`. Now Visual Studio marks everything inside `Definitions/MyComponent1/MyComponent1.d.ts` and all the .ts files in `Components/MyComponent1` as having duplicate identifiers although everything works. I also tried moving "MyComponent.d.ts" to the .ts files but it didn't help. Another thing I tried is to put a tsconfig.json that exlcudes the d.ts at the top-level of the `TypeScript` folder but that also didn't help.

I think there has to be a way to have both the definitions and declarations in a project without getting all the duplicate identifier IntelliSense errors.

My issue is basically the same as https://social.msdn.microsoft.com/Forums/sqlserver/en-US/f589a499-3c46-4a64-9345-a1eb228a053d/typescript-duplicate-identifier?forum=visualstudiogeneral

**Comment by mhegazy** [comment]
It is kinda hard to piece together a repro from this description; but if i understand correctly, you have a `Components/MyComponent1.ts` and a `Definitions/MyComponent1/MyComponent1.d.ts` that have the same declarations. the solution is in your `tsconfig.json` to specify an exclude entry for `Definitions`. and make sure you have no `/// <references path=".." />` to any of the files in this folder either.

If doing so does not exclude your files as expected (a good way to test for this is `tsc --p <path to tsconfig.json> --listFiles`) then it is a bug that we need to investigate. Please share a repro project to allow us to diagnose the issue.

**Comment by strohhut** [comment]
@mhegazy I made a minimal [repo](https://github.com/strohhut/TypeScript1107/tree/master/Project1/Project1/TypeScript): 

There is a all-pages.ts which is for all web pages and contains MyComponent1 and MyComponent2.  MyComponent2 uses MyComponent1. There is also a uploaded-page-only.ts whose js-version goes to the upload page. It contains MyComponent3 which also uses MyComponent1. Because MyComponent1 is already included in every page MyComponent3 references the MyComponent1 d.ts. Otherwise upload-page-only.js would include MyComponent1 although it is already inside all-pages.js.

In order to compile the typescript files I enumerate all .ts files inside the Shipped folder and use gulp-typescript for each of those .ts files with the `outFile` option. So I create a tsconfig object on the fly for every .ts file within shipped.

The reason why I'm doing all this is the size of the actual project which made me try split everything into reusable components (with one class per file). What I need is a way to stop IntelliSense from showing all the duplicate errors. If I have to remove all the references for this like you say I guess that won't work with my component approach. Then I wonder how other real-world projects are handling this.

**Comment by mhegazy** [comment]
I see the issue now. All files in a single compilation see each other. You have split your projects to two entry points (`all-pages.ts` and `upload-pages-only.ts`) but you still compile them in one go. this puts the two files and any `/// <reference` tags they have in one pot metaphorically.

What you need to do is to split these into two compilataions (i.e. two invokations to tsc). you can do this be creating two tsconfig.json files:

```ts
/// all-pages/tsconfig.json

{
  "compileOnSave": false,
  "compilerOptions": {
    "noImplicitAny": false,
    "noEmitOnError": true,
    "removeComments": false,
    "sourceMap": true,
    "target": "es5"
  },
  "files":["Shipped/all-pages.ts"]
}
```

and 

```ts
/// upload-page-only/tsconfig.json

{
  "compileOnSave": false,
  "compilerOptions": {
    "noImplicitAny": false,
    "noEmitOnError": true,
    "removeComments": false,
    "sourceMap": true,
    "target": "es5"
  },
  "files":["Shipped/upload-page-only.ts"]
}

```

then call the compiler as:

```cmd
tsc --p  all-pages/tsconfig.json
tsc --p  upload-page-only/tsconfig.json
```

hope that helps.

**Comment by strohhut** [comment]
Thank you, this fixes my problem. The IntelliSense errors are gone. 

If anybody is still seing those errors after limiting the scope of the `tsconfig.json` then those errors probably come from ReSharper. Upgrading to 2016.2 should fix this.
