### ISSUE TITLE
With default exportted class, there is no way to import it

### ISSUE THREAD

**Issue by Ciantic** [Microsoft/TypeScript#11016]
Consider JS like this: https://github.com/facebook/react/blob/df033180f0b56443985ad6e79c2eafdcc49384f7/src/addons/transitions/ReactTransitionGroup.js
Where the file exports the class.

There is three ways to import these: 

```typescript
// This one does not work
// import SomeClass from "some-crap";
// Because TypeScript transpiles to "T.default", and there is no .default in the JS file it doesn't work

// This does not work either:
// import * as SomeClass from "some-crap"
// because TS can't understand to use it as class then 

// This one WORKS, but it's deprecated right?
import SomeClass = require("some-crap");

class SubClass extends SomeClass {

}
```

I've tried with d.ts

```typescript
// Note that some-crap module does not have export named "default"
declare module "some-crap" {
    class Thingie { 

    }
    export = Thingie;
}

/*
this does not work either.

declare module "some-crap" {
    export default class Thingie { 

    }
}
*/
```

Cloneable gist: https://gist.github.com/Ciantic/8cbc50bf8f025c2f7fd94490fa922691

**Comment by RyanCavanaugh** [comment]
That JS is **not** a default export. A default export would be `module.exports = { "default": someClass };`. It's important to not conflate this with exporting through `module.exports = someClass;`.

`import x = require('y');` is not deprecated; this is the recommended syntax if you are depending on module loader behavior that is not ES6-compliant (as would be needed to consume a class exported through `module.exports = someClass;`.

I did a full write-up of this at http://stackoverflow.com/questions/39415661/why-cant-i-import-a-class-or-function-with-import-as-x-from-y

**Comment by mhegazy** [comment]
More docs can be found in http://www.typescriptlang.org/docs/handbook/modules.html
