### ISSUE TITLE
protected and mix-ins don’t work together

### ISSUE THREAD

**Issue by jbaron** [microsoft/TypeScript#1101]
If you implement (so not extend) a class that has protected methods, you always get an error (typically used for a mix-in like pattern)

Either you implement the method, but then the compiler complaints that you are not actually a subclass and therefor cannot implement a protected method. If you however omit the method and than the compiler complaints you are missing a method.

Quick sample to illustrate:

```
class A { 
     protected hello() {} 
 }

class B implements A {
    // protected hello() {} 
}
```

One possible solution would be the compiler should ignore protected (and private) properties when implementing a class, only seeing the public properties as part of the externally exposed interface of a class.

**Comment by benliddicott** [comment]
Related to issue #3854 which suggests allowing implementing protected methods and properties when implementing a class interface.
