### ISSUE TITLE
Code formatting for embedded Angular 2 template does not work.

### ISSUE THREAD

**Issue by waderyan** [Microsoft/TypeScript#11011]
_From @rajinder-yadav on September 17, 2016 8:23_

- VSCode Version: 1.5.2
- OS Version: Linux

Steps to Reproduce:

1.  Inside a angular 2 component, create non aligned template
2. press crtl+shift I, notice the template code doesn't get formatted like new structure html.
2a. selected the template code to be formated, press ctrl+shift I, no formatting is performed.

![format](https://cloud.githubusercontent.com/assets/439226/18607028/6caa56f4-7c8e-11e6-88d4-e277f354dab5.png)

_Copied from original issue: Microsoft/vscode#12181_

**Comment by waderyan** [comment]
Thanks for opening this issue. Moving to TypeScript language service (powers JavaScript code formatting).

**Comment by mhegazy** [comment]
Well angular2 templates are just strings. formatting does not work in string.
Allowing an angular2 extension to derive the language service operations (e.g. completion, formatting, colorization, etc..) is covered by https://github.com/Microsoft/TypeScript/issues/6508
