### ISSUE TITLE
Support ES6 class property type annotation by comment

### ISSUE THREAD

**Issue by waderyan** [Microsoft/TypeScript#11014]
_From @bigopon on September 19, 2016 5:28_

Currently you can do this

``` js
/**@type {number} myVar */
var myVar = something
```

👍 Very cool as sometime intellisense needs help, but we can't do this

``` js
class MyClass {
    // Not working
    /**@type {number} myProp */
    myProp

    // Not working either
    /**@property {number} myProp2 */
    myProp2
}
```

Would be great if supported.

Thanks 

_Copied from original issue: Microsoft/vscode#12240_

**Comment by waderyan** [comment]
@bigopon thanks for opening this issue.

**Comment by charrondev** [comment]
This seems to be working for me on the latest version of typescript (2.7) + VS Code (1.12.1).
