### ISSUE TITLE
Intellisense: wrong suggetions for node

### ISSUE THREAD

**Issue by waderyan** [Microsoft/TypeScript#11015]
_From @nobil007 on September 17, 2016 8:57_

- VSCode Version: Code 1.5.2 (66f37fd2a99eb9d628dd374d81d78835b410c39b, 2016-09-12T13:09:51.625Z)
- OS Version: Linux ia32 4.4.0-36-generic

Steps to Reproduce:

1.In my code I used __dirname. [Only 2 '_' as prefix]
2.When I type '_' next time, it will show suggestion. But the suggested string is ___dirname.[3 '_' as prefix]

_Copied from original issue: Microsoft/vscode#12182_

**Comment by waderyan** [comment]
_From @joaomoreno on September 19, 2016 8:50_

Can totally reproduce. Very strange. @jrieken any idea?

![image](https://cloud.githubusercontent.com/assets/22350/18626692/d67de9fa-7e56-11e6-8be9-b6fba3d465a4.png)

**Comment by waderyan** [comment]
_From @jrieken on September 19, 2016 8:58_

@joaomoreno Unsure what your screen shot shows. But you mean this?
![screen shot 2016-09-19 at 10 58 08](https://cloud.githubusercontent.com/assets/1794099/18626881/f871aff0-7e57-11e6-8ee3-b78bde5cfb93.png)

**Comment by waderyan** [comment]
_From @jrieken on September 19, 2016 8:59_

Iff so its from TypeScript/JavaScript as it's not a word based suggestion but a symbol suggestion from them

**Comment by waderyan** [comment]
_From @joaomoreno on September 19, 2016 9:7_

Yeah. Moving to @waderyan then.

**Comment by waderyan** [comment]
_From @nobil007 on September 19, 2016 9:17_

Ya, My issue is same as @jrieken reported.
![vscode](https://cloud.githubusercontent.com/assets/20113351/18627285/cf585a86-7e77-11e6-8be8-fa190c1a03a2.PNG)

**Comment by waderyan** [comment]
_From @nobil007 on September 19, 2016 9:29_

The issue in vs code is fine. But the tool [GitHub] which you provided to report the issue have the same issue. One underscore is eliminated from all places in my comment. I had put a underscore in between the single quotes in " [Only 2 '' as prefix] ". But is not showing in the view. But it shows in the editing view.

**Comment by waderyan** [comment]
Thanks for opening this issue. As this falls under the TS language service moving to them.

**Comment by RyanCavanaugh** [comment]
Can't repro in latest.

@waderyan is there any way we could have you guys running on latest bits of VS Code + TypeScript when doing bug triage on your side? I can help you get set up with it.

![image](https://cloud.githubusercontent.com/assets/6685088/18682278/742cd458-7f20-11e6-801f-80903b9355e3.png)

**Comment by waderyan** [comment]
@RyanCavanaugh 1.5.2 are the latest VS Code bits. What TypeScript would you like me to use?

**Comment by RyanCavanaugh** [comment]
Preferably a live build from the `release-2.0.5` branch of TypeScript

**Comment by waderyan** [comment]
Would it be `npm install typescript@latest`?

**Comment by mhegazy** [comment]
@RyanCavanaugh  `release-2.0.5` seems like a lot of work for the vscode folks to test against, unless we publish a nightly from release-2.0.5.

@waderyan `typescript@next` would be sufficient. there are some changes in `release-2.0.5` that are not in `typescript@next`, but hopefully we get the two in sync in the next few weeks.
