### ISSUE TITLE
Typescript Visual Studio 2015 Update 3 isn't showing up anywhere

### ISSUE THREAD

**Issue by brandonseydel** [Microsoft/TypeScript#11026]
![image](https://cloud.githubusercontent.com/assets/5033585/18696226/244123b0-7f7d-11e6-8ea4-fa0b4ded8bf4.png)

![image](https://cloud.githubusercontent.com/assets/5033585/18696238/39819cfa-7f7d-11e6-9adc-899857f5df10.png)

![image](https://cloud.githubusercontent.com/assets/5033585/18696258/584f0e74-7f7d-11e6-9a31-61da30e042df.png)

How do i get typescript back in visual studio??  I have resinstalled several times cleared data and component cache everything....

**Comment by brandonseydel** [comment]
I actually removed VS PREVIEW "15" which might has hosed up everything.  Just a clue.

**Comment by mhegazy** [comment]
if you open a new TS file, what do you see? do you see colorization working? 

can you uninstall all version of TS from add/remove programs, install update 3 from (https://msdn.microsoft.com/en-us/library/mt752379.aspx), then reinstall TS 2.0.2

**Comment by brandonseydel** [comment]
No colorization is working and when I try to update with that link it says cannot install visual studio update 3 is not installed.  I downloaded the visual studio 2015 update 3 iOS and web installer both of which failed.

**Comment by mhegazy** [comment]
Can you share install logs? it should be the last installer in your %TEMP% folder with `dd_` prefix

**Comment by brandonseydel** [comment]
I zipped up all loges starting with dd_
[vsLogs.zip](https://github.com/Microsoft/TypeScript/files/486386/vsLogs.zip)

**Comment by brandonseydel** [comment]
I am wiping out my machine tomorrow so any help would be great.
