### ISSUE TITLE
Literal Union Types => Typeof Unions in Property Indexes

### ISSUE THREAD

**Issue by ethanresnick** [Microsoft/TypeScript#11020]
**TypeScript Version:**  2.1.0-dev.dev.20160920

**Code**

```ts
import express = require("express");
const app = express();

const method = (someCondition()) ? "get" : "post"; // method is "get" or "post"
app[method](reqHandler);
```

**Expected behavior:**
Ideally, `app[method]` could be inferred as `typeof app.get | typeof app.post`

**Actual behavior:** 
`app[method]` gives an implicit any error, since app doesn't have an index signature. Doing `(<any>app)[method]` removes the error, but leaves `app[method]` as type any rather than `typeof app.post | typeof app.get`. 

To get proper typing, I can do: `(<typeof app.get | typeof app.post>(<any>app)[method])`, but that's super ugly.

The below almost works:

```ts
const method = (someCondition()) ? app.get.bind(app) : app.post.bind(app);
method(reqHandler);
```

except that `.bind()` calls return `any`.

**Comment by RyanCavanaugh** [comment]
Duplicate of #6080 (it even uses `get` / `post`  :smile: )

**Comment by ethanresnick** [comment]
Lol. Closing in favor of that one.
