### ISSUE TITLE
import inconsistent?

### ISSUE THREAD

**Issue by BobFrGit** [Microsoft/TypeScript#11025]
**TypeScript Version:**  1.8.36.0

**Code**

``` ts
import "http2"
- no error message

import http2 from "http2"
Severity    Code    Description Project File    Line    Suppression State
Error       Build:Cannot find module 'http2'.   xp3starter  Y:\dev\projects\Site\xp3b\xp3starter\app.ts 14  
Error   TS2307  Cannot find module 'http2'. xp3starter  Y:\dev\projects\Site\xp3b\xp3starter\app.ts 14  Active

var http2 = require("http2");
- compiles
```

**Expected behavior:**

**Actual behavior:** 

This may be my confusion. I've added the http2 module with npm. The first format does not produce an error (though is not very useful). The second form does.

This may be my confusion.  My sense is that import works if I have a definitely typed file. But haven't found the exact documentation. I do have a related question - how do I say that http2 should use the http module definition?

**Comment by RyanCavanaugh** [comment]
```
import "http2"
```
This is what we generally call a "forced" import. It doesn't create a local binding, so there's no reason to force it to resolve to a known module. These are usually used to load non-code resources anyway.

```
import http2 from "http2"
```
There's no definition for the `"http2"`, so we don't know how to resolve the type of the local `http2` binding

```ts
var http2 = require("http2");
```
This is using the underlying module loader.

You can write this to get the behavior you want
```ts
import _http = require('http'); // don't use _http in any other place
var http2 = <typeof _http>require('http2');
```

**Comment by BobFrGit** [comment]
Thanks very much.

**Comment by BobFrGit** [comment]
Reopening this. First, the <typeof ..> notation is not at all obvious until you see it. Thanks.

But now in using "http.

```
import http1 = require("http");
var http = <typeof http1>require("http2");
   ServerResponder(req: http.ServerRequest, response: http.ServerResponse) {
    
Error	TS2503	Cannot find namespace 'http'.

```
same for "var http2 = ..."

**Comment by RyanCavanaugh** [comment]
Sorry this is a bit confusing -- you'll want to use `http1` in *type* positions, e.g. `http1.ServerRequest`. #10187 would create a way to do this unconfusingly by letting you alias the namespace side of `http1`.

**Comment by BobFrGit** [comment]
Thanks. Yeah -- gelignite the truth by lying. I'll have to take the time go through the aliasing procedure given the overlapping mechanisms.  And, more generally,how to get the declarations for importing JavaScript but that's probably best for the suggestions forum.

**Comment by BobFrGit** [comment]
OK, gets stranger. Turns out that https://github.com/molnarg/node-http2 has an index.d.ts file and even mentions Typescript 1.8 compatibility. ! But it's unclear how to use it. My gut feel is that it should be found automatically. So I explicitly added
```
/// <reference path="./node_modules\http2\typings\globals\node\index.d.ts" />
```
which generates declaration errors.

I feel this is close but so far.
