### ISSUE TITLE
Maybe Enum initialize with 1 will be more useful

### ISSUE THREAD

**Issue by forthedamn** [Microsoft/TypeScript#11036]
**TypeScript Version:**  1.8.0 / nightly (2.0.0-dev.201xxxxx)

**Code**

```ts
enum SomeType {
 a,
 b,
}

function doSth(key:any):SomeType {
 ... do something
}

// the number 0 will make things complicated
if (doSth('value')) {
  ... do something
}

// so i have to change all enums in my project
enum SomeType {
 a = 1,
 b,
}

```

**Expected behavior:**
```ts
enum SomeType {
 a,
 b,
}
SomeType.a === 1 // true
```
**Actual behavior:** 
```
SomeType.a === 0 // true
```

**Comment by RyanCavanaugh** [comment]
We *definitely* can't change this behavior now; it would break thousands of projects in subtle and terrible ways. Maybe there's an interesting historical debate about whether 0 or 1 would have been the better starting choice, but at the time we decided to do what pretty much every other language with enums did.
