### ISSUE TITLE
Unexpected `/// <reference types="angular" />` in `.d.ts` files

### ISSUE THREAD

**Issue by mhevery** [Microsoft/TypeScript#11039]
**TypeScript Version:**  2.0.2

**Code**

I am sorry I don't have a smaller repro case. :-(
(https://github.com/mhevery/angular/tree/ts-issue-11039)

The issue is that `d.ts` file contains `/// <reference types="angular" />` and I don't know why.

Angular had incorrectly included `@types/angularjs`. The PR changes it to `@types/angular` The only place where `@types/angular` should be used is in `modules/@angular/upgrade/tsconfig-build.json` as that is the only folder which imports  from `@types/angular`

The change (`@types/angularjs` => `@types/angular`) now sprinkles `/// <reference types="angular" />` in some `d.ts` files where it did not before. An example for it is `dist/packages-dist/core/src/type.d.ts`.

Steps to repro:

1. clone the repo `git clone https://github.com/mhevery/angular.git`
2. check out `ts-issue-11039`: `git checkout ts-issue-11039`
2. `npm i`
3. `./build.sh`
4. Examine that `dist/packages-dist/core/src/type.d.ts` has `/// <reference types="angular" />` Why?
5. Delete compiler folder `rm -rf dist/packages-dist/core`
6. Rebuild manually `node --max-old-space-size=3000 dist/tools/@angular/tsc-wrapped/src/main -p modules/@angular/core/tsconfig-build.json` (We have a custom TSC main to deal with our sim link issue, which is why `$(npm bin)/tsc -p modules/@angular/core/tsconfig-build.json`) does not work. Notice that after rebuild the  `dist/packages-dist/core/src/type.d.ts` has `/// <reference types="angular" />` yet there is no reference to `@types/angular` in the `modules/@angular/core` folder

NOTE: There are many more files which have this issue (not just the core)`

**Comment by mhegazy** [comment]
> We have a custom TSC main to deal with our sim link issue

what is you symlink issue? can we fix it?

**Comment by mhevery** [comment]
The issue is that we have `modules/@angular/facade` which is being symlinked into `modules/@angular/*/src/facade`. (This is due to historical Dart support and we are slowly getting rid of it.) Because TSC resolves symlinks into absolute links. It then throws an error like so:

```
$(npm bin)/tsc -p modules/@angular/core/tsconfig-build.json 
error TS6059: File '/Users/misko/work/angular/modules/@angular/facade/src/async.ts' is not under 'rootDir' '/Users/misko/work/angular/modules/@angular/core'. 'rootDir' is expected to contain all source files.
error TS6059: File '/Users/misko/work/angular/modules/@angular/facade/src/collection.ts' is not under 'rootDir' '/Users/misko/work/angular/modules/@angular/core'. 'rootDir' is expected to contain all source files.
error TS6059: File '/Users/misko/work/angular/modules/@angular/facade/src/errors.ts' is not under 'rootDir' '/Users/misko/work/angular/modules/@angular/core'. 'rootDir' is expected to contain all source files.
error TS6059: File '/Users/misko/work/angular/modules/@angular/facade/src/lang.ts' is not under 'rootDir' '/Users/misko/work/angular/modules/@angular/core'. 'rootDir' is expected to contain all source files.
error TS6059: File '/Users/misko/work/angular/modules/@angular/facade/src/math.ts' is not under 'rootDir' '/Users/misko/work/angular/modules/@angular/core'. 'rootDir' is expected to contain all source files.
```

**Comment by mhegazy** [comment]
this sounds like the same underlying issue in https://github.com/Microsoft/TypeScript/issues/9552. we should be fixing this in the next release.

**Comment by mhevery** [comment]
But the original question remains. Why is there `/// <reference types="angular" />` when no one references it? And why only in some files?

**Comment by mhegazy** [comment]
ah sorry @vladima looked into it. and the issue is the compiler automatically loads all @types packages in the containing directories. so it did include `@types\angular`. it so happens that `@types\angular` adds `$inject` to `Function` and some of other part of your code extends `Function` creating a false dependency. The solution would be to add `types: []` to your tsconfig.json to state you do not want to include `@types\angular` in your compilation. this seems to address the issue on the angular repo.

**Comment by mhevery** [comment]
Hmm. I thought I tried it and it did not work for me. Will try again.

**Comment by JulienBier** [comment]
@mhevery Hi, I have the same issue with update to typescript 2.0.3. Did you find a solution to fix this ?

**Comment by mhevery** [comment]
Did `types: []` not work?

**Comment by JulienBier** [comment]
No it didn't. Issue seems to be in @types/angular-mocks npm package.
