### ISSUE TITLE
Merging namespaces inside modules

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/TypeScript#11034]
2@rc

Given:

``` ts
// typings1.d.ts
declare module 'knex' {
    export interface Test {
        foo: string
    }
}
```

``` ts
// typings2.d.ts
declare module 'knex' {
    export interface Test {
        bar: string
    }
}
```

``` ts
import {Test} from 'knex';
let y: Test = {} as any;
y.foo
y.bar
```

This works fine. However, given:

``` ts
// typings1.d.ts
declare module 'knex' {
    namespace Knex {
        const foo: string
        interface Transaction {
            foo: string
        }
    }

    export default Knex;
}
```

``` ts
// typings2.d.ts
declare module 'knex' {
    namespace Knex {
        const bar: string
        interface Transaction {
            bar: string
        }
    }
}
```

``` ts
import Knex from 'knex';
Knex.foo
Knex.bar // error
let y: Knex.Transaction = {};
y.foo
y.bar  // error
```

It appears my namespace `Knex` is not being merged, because I can only access identifiers from `typings1.d.ts`. Why is this?

**Comment by DanielRosenwasser** [comment]
I believe that `Knex` refers to two "local" entities within each `declare module` block. Just to better understand the scenario, why are you splitting an ambient module declaration across different files?

**Comment by OliverJAsh** [comment]
@DanielRosenwasser

Thanks for the fast reply.

I am trying to augment existing third party typings to provide corrections whilst waiting for upstream changes. 

Specifically [this interface](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/d566e029c39e7f35e137c4091dde8dbae47b5ec7/knex/knex.d.ts#L330), which I have modelled in the above example.

**Comment by mhegazy** [comment]
this is rather subtle. in a .d.ts file all top level declarations in a module are implcitly exported, e.g. in `typings2.d.ts`  you did not need to write `export namespace Knex`. This rule does not hold if you have one of `export default ..`, `export {..}` or `export * from ..` only declarations with `export` are exported. so in `typings1.d.ts` there is not really an exported name space, all what is there is a `default` export. the reuslt is that your other declaration does not augment it.

change you file to be:

```ts
// typings1.d.ts
declare module 'knex' {
    export namespace Knex {
        const foo: string
        interface Transaction {
            foo: string
        }
    }

    export default Knex;
}
```

**Comment by OliverJAsh** [comment]
Thanks @mhegazy, that makes sense. Is there something we can do to make this more explicit to the user? Silent failures are the worst!

**Comment by timruffles** [comment]
Would it be sensible to get the concept of explicitly aiming to merge a declaration into the language?

**Comment by timruffles** [comment]
Perhaps a `merged` modifier for declarations, that causes an error if at the end of compilation no merging took place:

```typescript
declare merged module 'knex' {
  /// ...
}
```

**Comment by mhegazy** [comment]
> Would it be sensible to get the concept of explicitly aiming to merge a declaration into the language?

merging is a core concept of the language. do not think a modifier makes sense here.

**Comment by mhegazy** [comment]
> Is there something we can do to make this more explicit to the user? 

It is about scoping rely. Adding an `export =` or `export default` for instance changes the scope of the module and "pushes" the declarations in one level. not doing so would result in unexpected consequences, e.g. 
```ts
declare module "foo" {
    class inner {  ... }
    var x: inner;
    export default x;
}
```
if every thing was exported, then your module have an `inner` and an `x` along with the `default` export. i do not think this would be what the user intended.

so really, the only issue, is that `export` is optional in ambient contexts. so if you always use `export` modifiers, you should be good.
