### ISSUE TITLE
Generated declaration missing generic

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/TypeScript#11035]
2@rc

Given:

``` ts
export type Bar<X, Y> = () => [X, Y];
export type Foo<Y> = Bar<any, Y>;
export const y = (x: Foo<string>) => 1
```

If I compile this with `"declaration": true`", the generated declaration file looks like:

``` ts
export declare type Bar<X, Y> = () => [X, Y];
export declare type Foo<Y> = Bar<any, Y>;
export declare const y: (x: Bar<string>) => number;
```

Notice that the typings for `y` are incorrect: the parameter `x` should be of type `Foo<string>` which is an alias for `Bar<any, string>`, however it is incorrectly typed as `Bar<string>`. The first generic to `Bar` has gone missing.

**Comment by RyanCavanaugh** [comment]
@mhegazy take this for 2.0?

**Comment by mhegazy** [comment]
@yui can you take a look

**Comment by yuit** [comment]
PR is up need to add tests

- [ ] Confirm that this bug isn't repo in "master"
