### ISSUE TITLE
Private Variables are able to accessing outside class.

### ISSUE THREAD

**Issue by anilkoranne3** [Microsoft/TypeScript#11033]
We can access the private variables outside the class after converting them to string and again parse them, but we cannot change them.  

**TypeScript Version:**  1.8.0

 For Eg:
**Code**
class Animal {
	    private name: string;
	    protected type : string;
	    public age : Number;
	    constructor(theName: string) {
	     this.name = theName; 
	     this.type = "kitten";
	     this.age = 3;
	 	}
	 	getObj(){
	 		return this; //returning whole class
	 	}
	}
	class Monkey extends Animal{
		_name : string;
		constructor(){
			super("horse");
		}
	}
	let animal = new Animal("Cat"); 
	let mon = new Monkey();
	console.log(mon);//Monkey {name: "horse", type: "kitten", age: 3}
	let mon_obj = JSON.stringify(mon);//object converting to string 
	let mon_temp = JSON.parse(mon_obj);
	console.log(mon_temp);//Object {name: "horse", type: "kitten", age: 3}
	console.log(mon_temp.name);//horse

	let ani = JSON.stringify(animal);
	console.log(ani);//{"name":"Cat","type":"kitten","age":3} 
	let temp = JSON.parse(ani);
	console.log(JSON.parse(ani));//Object {name: "Cat", type: "kitten", age: 3}
	console.log(temp.name);//Cat
	console.log(temp.type);//kitten
	console.log(animal);//Animal {name: "Cat", type: "kitten", age: 3}

**Expected behavior:**
The private members should not access outside the class, as it can create security concerns as the data is fetched and user can use them in any way.

**Actual behavior:** 
Private member should not console outside the class. As it can have the security issue if using in confidential data.

When we console any class object it returns the whole data which we have written inside constructor. After getting those data we can stringify "JSON.stringify" the object, after stringify when we parse "JSON.parse" them again we can access them in our own way.

Feel free to correct me in any point.

**Comment by kitsonk** [comment]
Duplicate of #1537 and many others...
