### ISSUE TITLE
Generics - Problem with Extends

### ISSUE THREAD

**Issue by victorhsn** [Microsoft/TypeScript#11048]
**TypeScript Version:**  1.8.10

**Code**

``` ts

export interface IServiceBase<T>  {
    consultar(id: number): Observable<T>;
}

export class ServiceBase<T> implements IServiceBase<T> {
    private _http: Http;
    constructor(http: Http) { 
       this.http = http;
    }

  consultar(id: number): Observable<T> {
      return this._http.post(this._url, request).map(resp => <T>resp.json());
    }
}

export class SafraService extends ServiceBase<Safra>  {
    constructor(http: Http) {
        super(http);
    }
}
```

**Expected behavior:**

I need to extend the class ServiceBase<T> with a model to use, where T is the model.

**Actual behavior:** 

But when I execute the script an exception is shown at line "SafraService extends ServiceBase<Safra>"
where is <Safra> is a model.

**Comment by RyanCavanaugh** [comment]
Please provide a **self-contained** code sample that demonstrates the problem you're having.

**Comment by victorhsn** [comment]
I think that code below is the problem. If I extend the class ServiceBase and put a model at parameter in ServiceBase, the script doesn't work and I don't understand why. Instead I'm doing something wrong when I use Generic TypeScript. 

```ts
export class SafraService extends ServiceBase<Safra>  {
  ...
    }
```

There is an interface called IServiceBase that has some methods.

```ts
export interface IServiceBase<T>  {
    methods...
}
```

And the class ServiceBase I implements the interface IServiceBase and I make the implementation of the methods.
 
```ts
export class ServiceBase<T> implements IServiceBase<T> { 
  implementation...
}
```

I guess that is ok until here. If I would like to use it concept I could extend the ServiceBase at any class as I'm doing in SafraService that I extend of ServiceBase as you can see below:

```ts
export class SafraService extends ServiceBase<Safra>  {
   ...
}
```

The error shown is at line, when the script is transpiler:

var SafraService = (function (_super) {
    __extends(SafraService, _super);

**Comment by mhegazy** [comment]
are you using `--out`? are these two classes in the same file? what is the error you get at runtime?
