### ISSUE TITLE
Helper for interfaces/types structure 

### ISSUE THREAD

**Issue by waderyan** [Microsoft/TypeScript#11045]
_From @whitecolor on September 3, 2016 14:3_

Here TS is able to detect which type of object is required, if I don't pass `url` property here it errors:
![image](https://cloud.githubusercontent.com/assets/736697/18225276/7ba35f74-7208-11e6-945a-cd05d55cf9a6.png)

But how to get help on the current interface/type which fields there present/required/etc?

_Copied from original issue: Microsoft/vscode#11495_

**Comment by waderyan** [comment]
@whitecolor, thank you for opening this issue. 

I don't quite understand. Can you explain "But how to get help on the current interface/type which fields there present/required/etc?" by providing an example.

**Comment by waderyan** [comment]
I apologize for the spam. Strange issue on my end with the comment button.

**Comment by waderyan** [comment]
_From @whitecolor on September 7, 2016 9:43_

Ok I will make a simplier example
```ts
interface AB {
  a: number
  b: string
  c?: Object
}

function f(x: AB) {
  return x
}
...

/* 
Now I want to call this f function
I don't know/remember what expected is type AB is what and properties does it expect
and unfortunately I don't get enough help from the editor on this topic
*/
f({ })
```
Here with pictures:
Ok now I know that it expects `AB` type, but what is AB type?
![image](https://cloud.githubusercontent.com/assets/736697/18306962/a8de9916-7507-11e6-9a2f-df7f6fd7c292.png)

Ok then I type "a", wow, I guessed there is "a" property on the type an it is a number - great
![image](https://cloud.githubusercontent.com/assets/736697/18306999/d7c6f37c-7507-11e6-9336-f6b73439dec7.png)
I fill the "" and continue, nay, that doesn't help me much, again it tells me that type is AB, but I don't know that props are there esle there in the type "AB"
![image](https://cloud.githubusercontent.com/assets/736697/18307091/412a064c-7508-11e6-8786-e1e94e685a9d.png)

But there is an error I can mouse over on it and get that I'm lacking some "b"
![image](https://cloud.githubusercontent.com/assets/736697/18307163/9a184fac-7508-11e6-9454-01c8a9678221.png)

That solves some thing, but what if there is some not required "c" property on AB interface, I will never know about it, editor won't tell me.

So what is needed that while filling object type one could see helper with all the props on the type, something like that:

![image](https://cloud.githubusercontent.com/assets/736697/18307314/51e2b64a-7509-11e6-8cb3-88e7eb209b91.png)

Hope I was clear =)

**Comment by waderyan** [comment]
_From @whitecolor on September 7, 2016 15:49_

It should be something like helper that we see in in tsconfig, when all options is shown:

![image](https://cloud.githubusercontent.com/assets/736697/18318779/732e3a30-753c-11e6-8df6-64e0318d584d.png)

And helper for each option:
![image](https://cloud.githubusercontent.com/assets/736697/18318814/8b39306c-753c-11e6-8cb3-5b6d5800b38b.png)

**Comment by waderyan** [comment]
_From @whitecolor on September 21, 2016 11:5_

Again about this feature request:
![image](https://cloud.githubusercontent.com/assets/736697/18708563/f0a10960-8014-11e6-9df1-8bd173bbf4d3.png)

You see I'm need to fill the options, I see the type of options it expects (`ForageDriverOptions`) but have no clue what it is about. I think this is strange, maybe I'm doing something wrong?

**Comment by waderyan** [comment]
Very interesting. Thank you for the thorough explanation. This seems like a valid feature request. Moving to TS.

**Comment by RyanCavanaugh** [comment]
This is the completion list you get from Ctrl-Space. Why is this in the TypeScript repo?

![image](https://cloud.githubusercontent.com/assets/6685088/18729437/999229fa-8006-11e6-8921-cf6a5b481f02.png)

**Comment by waderyan** [comment]
@RyanCavanaugh I apologize if this was inappropriate for the TypeScript repo. 

The OP's issue is with the content of the parameter hint. In the image below, my cursor is inside the curly braces and I'm still being hinted to use type AB. for the function. 

![image](https://cloud.githubusercontent.com/assets/2449568/18729901/9668ddee-8008-11e6-9348-92a81ae423ba.png)

Is the display of the parameter hint on the VS Code side?

**Comment by whitecolor** [comment]
@RyanCavanaugh thanks nice to know, it works. But I found the problem with this:

1) Why does it proposing some exessive stuff besides props on the interface? (`class, ctor, doWhile..`)
![image](https://cloud.githubusercontent.com/assets/736697/18729994/7ced8472-806d-11e6-8e92-758a29d49cc2.png)

2) More important issue, it doesn't work with overloaded functions, it alway tries to propose options for first definition:
![image](https://cloud.githubusercontent.com/assets/736697/18729930/3faff5ea-806d-11e6-97a6-df927c97e068.png)

```ts
interface AB {
  a: number
  b: string
  e?: Object
}
interface CD {
  c: number
  d: string
}
function f(x: AB) : void
function f(x: CD) : void
function f(x: any) {  
}
f({     })
```

**Comment by whitecolor** [comment]
2) More important issue, it doesn't work with overloaded functions, it alway tries to propose options for first definition:
![image](https://cloud.githubusercontent.com/assets/736697/18729930/3faff5ea-806d-11e6-97a6-df927c97e068.png)

```ts
interface AB {
  a: number
  b: string
  e?: Object
}
interface CD {
  c: number
  d: string
}
function f(x: AB) : void
function f(x: CD) : void
function f(x: any) {  
}
f({     })
```

**Comment by whitecolor** [comment]
3) The same thing for "overloaded" type definitions, like:
```ts
function f(x: AB | CD) : void
```
not sure but probably could be implemented to allow more convenient help on props then just intersection of the types alternatives:
![image](https://cloud.githubusercontent.com/assets/736697/18730212/811498aa-806e-11e6-9cbf-59d14349d954.png)

**Comment by RyanCavanaugh** [comment]
>  I'm still being hinted to use type AB

That's the correct type. Many times this type will be far too large to display to the user in expanded form via a tooltip.

The additional "snippet" completions there are inserted by VS Code. I'm not sure if we have the ability from the TS language side to turn those off at specific locations vs others?

**Comment by waderyan** [comment]
You can turn off snippets with this setting. 

```json
"editor.snippetSuggestions": "none"
```

**Comment by waderyan** [comment]
@RyanCavanaugh thank you for the clarification.
