### ISSUE TITLE
Setting to set execution environnement (node or browser)

### ISSUE THREAD

**Issue by testerez** [Microsoft/TypeScript#11050]
When coding for node, It feels strange to have all the stuff specific to browser available by default.
For example, this is compiled with no warning by tsc 2.0.2:
```
alert(name); // name and alert are part of lib.d.ts
```
Maybe an env setting in `tsconfig.json` could be a solution...
And I would also appreciate that `tsc --init` interactively ask for it. Like `eslint --init` does for example.

**Comment by RyanCavanaugh** [comment]
You can set e.g. `"lib": ["es2015.core"]` in your tsconfig's `compilerOptions` settings:
![image](https://cloud.githubusercontent.com/assets/6685088/18732059/157465de-8015-11e6-8990-e5fdce7d19cf.png)

**Comment by yortus** [comment]
Why is the browser environment opt-out, but other environments (like node) are opt-in?

**Comment by testerez** [comment]
Yes it's working thanks. But now, `console` cannot be found.
99.9% users will run the javascript code either inside the browser or node.
Don't you think that it would make sense to have simple presets to support those environments ?

**Comment by yortus** [comment]
Related: #9466

**Comment by yortus** [comment]
@testerez re getting things like `console` to work, @RyanCavanaugh's suggestion above doesn't cover that. You also need the node typings. See https://github.com/Microsoft/TypeScript/issues/9466#issuecomment-230089243. I think the step 3 there is no longer needed due to a recent fix.

**Comment by testerez** [comment]
I get this error
```
error TS2318: Cannot find global type 'Boolean'.
error TS2318: Cannot find global type 'IArguments'.
error TS2318: Cannot find global type 'Number'.
```

with tsconfit
```
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es5",
    "noImplicitAny": true,
    "sourceMap": false,
    "strictNullChecks": true,
    "lib": [
      "es2015.core"
    ],
    "types": ["node"]
  }
}
```

and running
`tsc -p tsconfig.json`

**Comment by yortus** [comment]
@testerez try using `"lib": ["es2015"]` instead of `"lib: ["es2015.core"]`.

**Comment by testerez** [comment]
Ho yes sorry didn't see the difference here. Working now!
So what about the interactive `tsc --init` is there any plan about something like that?

It's not so easy to sell typescript to JS devs... Anything that could make the first contact smoother is welcome!

**Comment by yortus** [comment]
Personally I agree that typeScript should not 'choose favourites' between environments.

Maybe you could chime in on #9466 since that covers much the same concern and is labeled 'awaiting more feedback'.

**Comment by testerez** [comment]
Yes, same topic. Thanks for the link.

**Comment by mhegazy** [comment]
adding a lib for node is covered in https://github.com/Microsoft/TypeScript/issues/9466. closing.
