### ISSUE TITLE
es5.d.ts is missing "toLocaleString()" method on Number interface

### ISSUE THREAD

**Issue by kpreisser** [microsoft/TypeScript#11056]
**TypeScript Version:**  master (95c3eccbe9f3f7e1857ce157d437e6b80b3c9c6f)

Hi,

it seems the library declaration for ES5 ([es5.d.ts](https://github.com/Microsoft/TypeScript/blob/master/src/lib/es5.d.ts)) is missing a declaration on the `Number` interface for `toLocaleString()`, e.g. like this:

``` typescript
interface Number {
    // (...)
    /**
      * Converts a number to a string by using the current locale.
      */
    toLocaleString(): string;
}
```

whereas the `Date` interface contains such a definition:

``` typescript
    /** Returns a value as a string value appropriate to the host environment's current locale. */
    toLocaleString(): string;
```

ECMAScript 5.1 specifies `Number.prototype.toLocaleString()`at section [15.7.4.3](http://www.ecma-international.org/ecma-262/5.1/#sec-15.7.4.3), and ECMAScript 2015 specifies it at [20.1.3.4 ](http://www.ecma-international.org/ecma-262/6.0/#sec-number.prototype.tolocalestring).

Note: lib.es5.d.ts contains definitions for the ECMAScript Internationalization API (ECMA-402), that defines `toLocaleString(locales?: string[], options?: Intl.NumberFormatOptions): string;` on the Number interfaces, but this is not a part of the core ES 5.1 library, whereas the one without arguments is.
Therefore I think this method should be added on the number interface.

Thanks!

**Comment by mhegazy** [comment]
A method with two optional arguments is equivalent to one with no required arguments... so i am not sure i see why we need this additional signature. can you provide some code sample where this would not work?

**Comment by kpreisser** [comment]
Hi @mhegazy,

the issue is that the method with two optional arguments is defined in the section "ECMAScript Internationalization API" which contains APIs that are not supported in runtimes that implement only the ECMAScript core library. For example, this is the case with [Jurassic](https://github.com/paulbartrum/jurassic), a .NET javascript interpreter. Therefore, when we want to provide Typescript definition files for the [Monaco Editor](https://github.com/Microsoft/monaco-editor) that allows to write scripts for that runtime, we need to cut off that section from the lib.es5.d.ts (we need to do the same with thinks like `Int8Array` that aren't part of the ES5 core library).

However, now Number doesn't have a .toLocaleString() method (without parameters), although the JS runtime has. This means that when typing `(123).to` in the editor, no intellisense is shown.

Therefore, I think it would be good to add this method to the "plain" `Number` interface, just like it is already done for the `Date` object, because it then represents a method which is part of the core ECMAScript 5.1 specification, not part of the ECMAScript Internationalization API.

Thanks!

**Comment by mhegazy** [comment]
Well.. since you are slicing and dicing the file anyways, you could add the additional signature after removing the other ones. not sure adding it now would be of much value, for you or other users.

I would say the better solution here is to split this file into `es5.core` and `intel` so you can get the the core without the internationalization part.

**Comment by kpreisser** [comment]
Hi @mhegazy,
yes, splitting the file would be better I think. This would make it easier for us to synchronize our es5.d.ts (which contains only the ES5.1 core definitions) with the one from the TypeScript repo.
(Maybe that could also be done with the section ranging from `ArrayBuffer` to `Float64Array` which is also not part of the core ES5.1 spec, but of the separate "Typed Array Specification" which is now superseded by ES6).

Thanks!

**Comment by mhegazy** [comment]
We would accept PRs for this.

**Comment by ComFreek** [comment]
The overloads of [`String.prototype.toLocaleUpperCase`](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/String/toLocaleUpperCase), namely `toLocaleUpperCase(locale)` and `toLocaleUpperCase([locale1, locale2, ...])` are also missing. The same holds for [`String.prototype.toLocaleLowerCase`](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/String/toLocaleLowerCase).

If I understand it correctly, these overloads also stem from the Intl API: https://tc39.github.io/ecma402/#sup-string.prototype.tolocaleuppercase.

**Comment by simonbuchan** [comment]
Also the `Date.prototype.toLocale{,Date,Time}String()` options, etc., and many more...

How would TS like to see ecma-402 treated? as `--lib intl`? here is the existing `es2017.intl`, but it seems to only have some unreferenced interfaces (is that a bug?) - and I can't make heads or tails of what editions are actually published for 402.

It seems like it might make the most sense to do this as DT packages? In particular, I don't know how well `@types/node` would work with these as `lib` options.

**Comment by mhegazy** [comment]
> Also the Date.prototype.toLocale{,Date,Time}String() options, etc., and many more...

not sure what you mean by missing.. I see them in lib.es5.d.ts https://github.com/Microsoft/TypeScript/blob/83ab341531d694bb43e5a602cde852cea5436d1f/lib/lib.es5.d.ts#L650-L652

> How would TS like to see ecma-402 treated? as --lib intl?

we currently include them in lib.es5.d.ts, it will be a breaking change to break them out into their own target. not sure what is the value in doing so.

> and I can't make heads or tails of what editions are actually published for 402.

they are independently versioned, but each ECMA262 has matching version of 402. this is why we opted into simplifying the versioning story and just called them `intel.ESVersion.d.ts`

> It seems like it might make the most sense to do this as DT packages? 

Again, i am not sure what missing APIs are we talking about in particular. but things that are expected to by in any JS engine should be in the lib and not on DT.

**Comment by simonbuchan** [comment]
Oops? Yeah I just got pointed at these out another thread too.

Is `intel` a typo/autocorrupt of `intl`? I don't see either in the TS repo, other than `es2017.intl.d.ts`, but we now know how much to trust my reading skills!

You mention above splitting into `.core` and `.intl` the keep compat, but I guess it doesn't matter for es5 at this point.

**Comment by mhegazy** [comment]
the definitions are included in `src\lib\es5.d.ts`.
