### ISSUE TITLE
No way to pass default property values to React Components from Subclasses

### ISSUE THREAD

**Issue by pdeva** [microsoft/TypeScript#11052]
**TypeScript Version:**  1.8.0

**Code**

Consider this piece of code:

``` ts
// A *self-contained* demonstration of the problem follows...
class BaseComponent extends React.Component< {
    name: string
}, {} >
{
    render()
    {

    }
}


//No way to pass default 'name' to BaseComponent
class MyToolbar extends BaseComponent
{
    render()
    {

    }
}
```

**Expected behavior:**
I want to pass a default value of `name` property to BaseComponent. I don't want all the users of `MyToolbar` to have to pass in a `name` property.

If this was a typical subclass. I would do something like `super("myName");`. But since this is a React property, it is unclear/impossble how to pass a default property value.

**Actual behavior:** 
Allow passing a default property value. If this is already possible, please provide an example.

**Comment by RyanCavanaugh** [comment]
Isn't this just a React question?

**Comment by pdeva** [comment]
frankly i am not entirely sure if this belongs here or React.

I believe one can modify the `props` object being passed down in the constructor.  But then Typescript will still complain about `name` not being passed by the client. Making `name` optional would also not be semantically correct here, since it _is_ required. 

Not sure what is a typesafe way to do this.
