### ISSUE TITLE
Wiki: What's new in TypeScript: Mistake in type guards example.

### ISSUE THREAD

**Issue by martinrue** [Microsoft/TypeScript#11064]
TypeScript Version: 2.0.3

Referring to: https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#example-2

The code example shown is as follows:

```ts
// Compiled with --strictNullChecks
declare function f(x: number): string;
let x: number | null | undefined;
if (x) {
    f(x);  // Ok, type of x is number here
}
else {
    f(x);  // Error, type of x is number? here
}
let a = x != null ? f(x) : "";  // Type of a is string
let b = x && f(x);  // Type of b is string?
```

Concerning the final example `let b = x && f(x);`, the comment indicates the inferred type is `string?`, but because `0` is falsy, the type of `b` in fact is `string | 0 | null | undefined`. 

I wasn't sure if `string?` encompasses the zero value, but assuming not, the comment should be updated to reflect the above.

**Comment by mhegazy** [comment]
That is correct. thanks for reporting this. should be fixed now.
