### ISSUE TITLE
2.0.3 is latest

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/TypeScript#11061]
`npm info typescript` gives
```js
'dist-tags':
   { latest: '2.0.3',
     next: '2.1.0-dev.20160922',
     beta: '2.0.0',
     rc: '2.0.2' },
```
Is this intentional? Is TS2 stable now? I am getting spammed with Greenkeeper PRs to update TS in all my repos.

**Comment by kitsonk** [comment]
`'2.0.3': '2016-09-22T16:00:05.876Z'` it seems like it was stable 30 minutes ago... I suspect the team just hasn't been able to update us yet.

**Comment by goenning** [comment]
They've just announced the release of 2.0 https://blogs.msdn.microsoft.com/typescript/2016/09/22/announcing-typescript-2-0/

**Comment by felixfbecker** [comment]
Yeah, but why is `@next` behind latest? Very confusing

**Comment by kitsonk** [comment]
Also [2.0.3 has been tagged in github as stable](https://github.com/Microsoft/TypeScript/releases/tag/v2.0.3).

**Comment by kitsonk** [comment]
`@next` is published via a process and off a different branch (`master`) than 2.0.3.

**Comment by felixfbecker** [comment]
Alright, thanks! A minute ago there was no release tagged on GitHub.

**Comment by DanielRosenwasser** [comment]
Very intentional. Enjoy! 😄
