### ISSUE TITLE
tsconfig `paths` documentation is wrong in "What's new" section for 2.0

### ISSUE THREAD

**Issue by mattyork** [Microsoft/TypeScript#11063]
**TypeScript Version:**  2.0.3

Referring to this: https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#path-mapping

Which has this example:
```json
{
  "compilerOptions": {
    "paths": {
      "jquery": ["node_modules/jquery/dist/jquery.d.ts"]
    }
}
```

There are a few issues with this documentation that I had to learn the hard way:
1. You can only use `path` in conjunction with `baseUrl`. There was a good error message for this, so this isn't a big deal.
2. `paths` options must be relative to the `baseUrl`, not to the current directory. Had to use `--traceResolution` for this. 
3.  You cannot add `.d.ts` to the end. This is wrong in the documentation. The module resolution algorithm will apply `.d.ts`. So if you used the documented example and ran `--traceResolution` you would see the resolver looking for `jquery.d.ts.d.ts`

**Comment by mhegazy** [comment]
Thanks. should be updated now.

**Comment by mattyork** [comment]
speed of light. Thanks @mhegazy
