### ISSUE TITLE
`gulp local` does not copy typingsInstaller.js to `built/local`

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/TypeScript#11077]
**TypeScript Version:**  2.0.5 branch
**OS** MacOS

Steps:
- check out branch 2.0.5
- npm install
- gulp local
- check `build\local` for typingsInstaller.js 
-> it's missing

**Comment by mhegazy** [comment]
should be fixed by https://github.com/Microsoft/TypeScript/pull/11071
