### ISSUE TITLE
tsc --npm-install

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#11079]
It would be good if tsc could npm install and check available typings at the same time. 
```
tsc --npm-install [package]
tsc -ni [package]
```
So for example if one installs `express`:
```
tsc --npm-install express
npm install express --save
Checking available package...
Found @types/express
Installing @types/express
npm install @types/express --save-dev
```

**Comment by basarat** [comment]
I quite commonly do stuff like what I just did: `npm install react-router @types/react-router --save-dev`  :rose:

**Comment by kitsonk** [comment]
That makes TypeScript very workflow opinionated.  TypeScript [design non-goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals#non-goals):

> 4) Provide an end-to-end build pipeline. Instead, make the system extensible so that external tools can use the compiler for more complex build workflows.

TypeScript is a compiler, not a workflow engine like Grunt or Gulp (or arguably even npm itself).  Why `@types` are available the more `tsc` is intrinsically tied to them, the less options it gives other workflows.

This workflow is a perfect opportunity for the community to build something that would proxy `npm install` to do the additional resolution.

**Comment by tinganho** [comment]
@kitsonk  I believe TypeScript already is workflow opinionated in respect to typings. Since the official way of doing type acquisition is through the @types scope in NPM? This will only ease that workflow. 

Note there is also '--init' which is also workflow opinionated. Since `--init` is part of setting up the project. I think a potential '--npm-install [pkg]' makes sense, since it is also about setting up a project.

**Comment by tinganho** [comment]
And also by the time you have setup Gulp or Grunt. You already have all your types installed.

**Comment by kitsonk** [comment]
Having an *opinion* (which is really more of an *assumption*) about workflow does not mean that it is suitable for TypeScript to become more.  Just like TypeScript makes some default assumptions around how modules will be loaded (and now allows other assumptions to be asserted) but it is not a module loader.

`@types`, while the preferred and recommend way of suppling types for untyped JavaScript, it is not the only way.  Just like there are still 3 settings for `moduleResolution` in TypeScript, because one size does not fit all.

Anyone wishing to implement this would have to make some assumptions of the correlation of a package on npm and the appropriate version of `@types`.  While there are some standards that have been expressed, it is not definitively expressed in the meta data anywhere.  Often to, there are significant disconnects of the semver of the source packages and the `@types` versions that are available and published.  All of this logic would need to be dealt with, in something that is a compiler, not a type management tool.

Having `@types` installed is not a pre-requisite for using Gulp or Grunt.

**Comment by tinganho** [comment]
>@types, while the preferred and recommend way of supplying types for untyped JavaScript, it is not the only way. Just like there are still 3 settings for moduleResolution in TypeScript, because one size does not fit all.

I can only find two options? `classic` pre 1.6 and `node`.

>Having @types installed is not a pre-requisite for using Gulp or Grunt.

It is not a pre-requisite. Though what I meant is that they are quite heavy and takes time to setup. And by the time you have setup Gulp or Grunt you have already installed most of your typings. Thus, creating a task that does the same as `--npm-install [pkg]` is less relevant.

>Anyone wishing to implement this would have to make some assumptions of the correlation of a package on npm and the appropriate version of @types. While there are some standards that have been expressed, it is not definitively expressed in the meta data anywhere. Often to, there are significant disconnects of the semver of the source packages and the @types versions that are available and published. All of this logic would need to be dealt with, in something that is a compiler, not a type management tool.


I could find @RyanCavanaugh comments in here https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/ :

>The major and minor version number of the types package will match the version of the underlying package, with the patch version tracking the version of the definition file.

**Comment by kitsonk** [comment]
> I can only find two options? `classic` pre 1.6 and `node`.

You are right, I thought there was `system` too, but I got confused.

> I could find @RyanCavanaugh comments in here https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/ :
>
> > The major and minor version number of the types package will match the version of the underlying package, with the patch version tracking the version of the definition file.

That is convention, not hard enforced, based on people contributing to DefinatelyTyped or the other ways `@types` can be contributed.

Take for example, Grunt 1.0.0 was released in April 2016.  The latest version `@types/grunt` is 0.4.20.  Those two versions are completely incompatible from semver/npm perspective.  A `0` release is a special semver range that is essentially like a lot of pre-release tags.

How many of the other disconnects will there be between the published package versions and `@types`?  And then to bake that all into `tsc` when it is still much better suited as a separate community tool.

**Comment by weswigham** [comment]
@basarat Returning to your common pattern; Protip: if you're in bash, you should also be able to write `npm install {,@types/}react-router --save-dev` if you want to save a few more characters. ;)

**Comment by DanielRosenwasser** [comment]
@weswigham Can you also do something like this?

```ts
npm install -D {,@types}{react,react-dom,react-router}
```

**Comment by tinganho** [comment]
>How many of the other disconnects will there be between the published package versions and @types

This might actually be hard to achieve then.
