### ISSUE TITLE
Visual Studio can't find re-exported references

### ISSUE THREAD

**Issue by marcelgood** [Microsoft/TypeScript#11078]
**TypeScript Version:**  2.0.3

**Expected behavior:**

Find all references should actually find all references across all ts files in the solution.

Renaming an identifier should rename it across all files where it is used. 

**Actual behavior:** 

Find all references only finds references in the current file.

Renaming of identifiers only renames them in the current file.

**Comment by mhegazy** [comment]
I can not get this to reproduce on a simple project. do you see this on a specific project on any one? can you share steps to reproduce?

**Comment by marcelgood** [comment]
Ok, I narrowed this down some more, but not sure what's causing it. This is happen in a larger Angular 2 project, but only with some identifiers. I thought at first it doesn't work at all, but it works when I right-click on most identifiers and then do Find All References. But strangely for a few it doesn't work. The case where it's not working is the following. In file A I have the the following:

```
import { Injectable }    from '@angular/core';
import { CanActivate, CanDeactivate, ActivatedRouteSnapshot, RouterStateSnapshot, Routes, Resolve } from '@angular/router';
import { Observable } from 'rxjs/Observable';

import { EntityManagerProvider } from './entity-manager-provider';
import { ContextService } from './context.service';
import { BusyService } from './busy.service';

export interface CanComponentDeactivate {
    canDeactivate: () => boolean | Observable<boolean> | Promise<boolean>;
}

@Injectable()
export class CanDeactivateGuard implements CanDeactivate<CanComponentDeactivate> {
    canDeactivate(component: CanComponentDeactivate): Observable<boolean> | Promise<boolean> | boolean {
        return component.canDeactivate ? component.canDeactivate() : true;
    }
}

@Injectable()
export class ContextInitializeGuard implements CanActivate {
    constructor(private context: ContextService, private busyService: BusyService) { }

    canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot) {
        return this.busyService.busy(this.context.initialize().then(() => true));
    }
}

export const GLOBAL_ACTIVATE_GUARDS = [ContextInitializeGuard];
```

If I right-click on CanDeactivateGuard, it only finds the references in file A, however, if I go to another file where it is referenced and then right-click on it, it does find all the references including the one in file A. Very strange. I have almost the same code in another smaller Angular 2 project and there it doesn't have this problem. So, it's something about this one project. Perhaps the size or something. Here's how CanDeactivateGuard is used in one of the files for example.

```
export const reportRoutes: Routes = [
    {
        path: 'report/:id',
        component: ReportMainComponent,
        canActivate: GLOBAL_ACTIVATE_GUARDS,
        canDeactivate: [CanDeactivateGuard],
        resolve: {
            report: ReportResolver
        },
        children: [
            {
                path: '',
                redirectTo: 'detail'
            },
            { path: 'history', component: ReportHistoryComponent },
            { 
                path: 'detail', 
                component: ReportDetailComponent,
                canDeactivate: [CanDeactivateGuard]
            }
        ]
    },
    {
        path: 'report/summary/:id',
        component: ReportSummaryComponent,
        canActivate: GLOBAL_ACTIVATE_GUARDS,
        canDeactivate: [CanDeactivateGuard],
        resolve: {
            summary: EntitySummaryResolver
        }
    }
];
```

**Comment by mhegazy** [comment]
how is the other file importing `CanDeactivateGuard`?

**Comment by marcelgood** [comment]
From a barrel. 

`import { GLOBAL_ACTIVATE_GUARDS, CanDeactivateGuard, BusyService, DialogService } from '../../core/services/common';`

```
export { ContextInitializeGuard, CanComponentDeactivate, CanDeactivateGuard, GLOBAL_ACTIVATE_GUARDS } from './guards';
export { customExceptionHandlerProvider } from './custom-exception-handler';
export { DialogService, MessageBoxComponent } from './dialog.service';
export { EntityManagerProvider } from './entity-manager-provider';
export { ErrorHandler, ErrorLevel } from './error-handler';
export { jsonResultsAdapter } from './json-results-adapter';
export { NavService } from './nav.service';
export { BusyService } from './busy.service';
export { ContextService, UserContext, GlobalRoles, MasterPageLayoutDictionary } from './context.service';
export { PageService, PageDescriptor, PagePosition } from './page.service';
export { MenuService, MenuItem, ParentItemKeys } from './menu.service';
```

**Comment by mhegazy** [comment]
@andy-ms can you take a look.

**Comment by andy-ms** [comment]
We have a similar problem within the compiler:

Go to `core.ts` and find all references for `createMap`. It only gives you references within `compiler`. Then open any file in `services`, and go back and try again -- you get the results from `services` now.

The reason is that `compiler` and `services` has separate `tsconfig.json`, so find-all-references only finds the references within `compiler` until you explicitly open `services`. It sounds like your problem is the same: after you've opened the file that is referenced, you can find the reference. (Admittedly this isn't very useful, since you'd like it to find the reference for you! :bowtie:)

@marcelgood do you have multiple `tsconfig.json` within your project?

**Comment by marcelgood** [comment]
No, I only have a tsconfig.json

**Comment by andy-ms** [comment]
To clarify:
    * In file A, find-all-references only finds references in A.
    * In file B, find-all-references finds references in both A and B.
    * If you open A, then open B, then go back to A (leaving B open), does it list references in B?
    * Finally, since you're using re-exports, what happens if you leave A, B, and the re-exporting module open all at once? And does the re-export show up as a reference?

Also, you mentioned that the problem only happens for some identifiers. Does find-all-references work for any other re-exported identifiers?

Also, what editor are you using, and is it set up to use the latest version of TypeScript?

**Comment by marcelgood** [comment]
_In file A, find-all-references only finds references in A._

Correct

_In file B, find-all-references finds references in both A and B._

Correct

_If you open A, then open B, then go back to A (leaving B open), does it list references in B?_

No

_Finally, since you're using re-exports, what happens if you leave A, B, and the re-exporting module open all at once? And does the re-export show up as a reference?_

Doesn't make a difference.

Now that you mention it, the issue seems to be isolated to re-exported identifiers. I tried it with a few other re-exported identifiers, and they all have the same issue.

I'm using Visual Studio 2015 as the title says and yes, I'm using the latest. This issue started after upgrading to TypeScript 2.0.3. I'm also using Visual Studio Code with the same project and I don't have the issues there. At this point I need to do all my refactoring in VS Code, because Visual Studio will leave my project all broken if I rename and identifier.

**Comment by marcelgood** [comment]
Just wanted to update and close this issue. Looks like the issue got resolved in later updates.
