### ISSUE TITLE
Export of Discriminated union type not found when used together with webpack/angular2

### ISSUE THREAD

**Issue by mmc41** [Microsoft/TypeScript#11084]
I get a weird error when combining typescript, angular2 and web pack related to discriminated union types. Exporting other things from typescript works fine - just not discriminated unions.

**TypeScript Version:**  2.0.3

**Code**

**File tree-node.ts:** in an angular 2.0 (final) angular-cli project.

export interface TreeNodeBase 
{
  readonly children: TreeNode[];
  title() : string;
}
export interface EmptyTreeNode extends TreeNodeBase
{
  readonly kind: "empty";
}

export interface CategoryTreeNode extends TreeNodeBase
{
  readonly kind: "category";
  readonly item: Category;
}

export interface ModuleTreeNode extends TreeNodeBase
{
  readonly kind: "module";
  readonly item: ServiceModule;
} 
export interface ModuleInstanceTreeNode extends TreeNodeBase
{
  readonly kind: "moduleInstance";
  readonly item: ServiceModuleInstance;
}

export type TreeNode = EmptyTreeNode | CategoryTreeNode | ModuleTreeNode | ModuleInstanceTreeNode;

**File tree-node.component.ts** in same folder of an angular 2.0 (final) angular-cli project.

import { Component, OnInit, Input } from '@angular/core';
import { TreeNode } from './tree-node';

@Component({
  selector: 'app-tree-node',
  templateUrl: './tree-node.component.html',
  styleUrls: ['./tree-node.component.css']
})
export class TreeNodeComponent implements OnInit {
  @Input() treeNode: TreeNode;

  constructor() {  }

  ngOnInit() {
    console.log("TreeNodeComponent got "+JSON.stringify(this.treeNode));
  }

}
**Expected behavior:**

Compiles and runs without problems.

**Actual behavior:** 

When angular cli tools, when I type "ng serve" the project compiles with this warning (twice):
WARNING in ./src/app/plugin-tree/tree-node.component.ts
35:55 export 'TreeNode' was not found in './tree-node'

And at runtime I get this in chrome console:

[WDS] Warnings while compiling.
client?93b6:69 ./src/app/plugin-tree/tree-node.component.ts
35:55 export 'TreeNode' was not found in './tree-node'
Error: export 'TreeNode' was not found in './tree-node'
    at HarmonyImportSpecifierDependency.getWarnings (/Users/mmc/repos/reversebackup3/projects/client/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:34:14)
    at 

**Question :**

Is this a typescript, an angular2, a web pack or some other error ? (I am using typescript 2.0.3, angular 2.0.0, web pack ^2.1.0-beta.22)

**Comment by mmc41** [comment]
I cut seemingly irrelevant code from the example. It turns out that the problem only occurs, if I also export a function in addition to the discriminated union type. F.x. This one:

export function createRootNode(children : TreeNode[]) : EmptyTreeNode
{
  return {
    kind: "empty",
    children: children,
    title() { return "ALL"; }
  };
}

Without this additional export, the problem goes away. Strange.

**Comment by mhegazy** [comment]
Does running `tsc` generates the same errors? if so it is a TS bug, if not it is a loader issue.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Comment by mmc41** [comment]
@mhegazy Not solved. Seems to be related to this one which discuss a similar issue at length:
https://github.com/angular/angular-cli/issues/2034#issuecomment-302666897
