### ISSUE TITLE
Confusing error messages from flow analysis

### ISSUE THREAD

**Issue by HolgerJeromin** [Microsoft/TypeScript#11086]
**TypeScript Version:**  2.0.3

**Code**
```ts
let bar = false;
function foo() {
	if (bar === true) {
		return "true";
	}
	if (bar === true) {
		return "false";
	}
}
```

**Expected behavior:**
Message: "bar cannot be true at this position" or whatever

**Actual behavior:** 
error TS2365: Build:Operator '===' cannot be applied to types 'false' and 'true'.

**Comment by kitsonk** [comment]
Essentially dupe of #10991 when CFA narrows a type and confusing error messages.

**Comment by HolgerJeromin** [comment]
Thanks kitsonk! I will follow the other issue.
