### ISSUE TITLE
Async function return type

### ISSUE THREAD

**Issue by mathewmeconry** [Microsoft/TypeScript#11097]
From my point of view is the excepted return type of async function wrong. Because when I declare a static function as async to use await to wait for a function which returns a promise Typescript forces me to return a Promise. With this behavior I'm not able to deasync a function like a db connection. Below you'll find an example.
**TypeScript Version:**  2.0.3
**tsconfig.json***
```json
{
  "compilerOptions": {
    "noImplicitAny": false,
    "removeComments": true,
    "preserveConstEnums": true,
    "sourceMap": true,
    "rootDir": "./src",
    "module": "commonjs",
    "target": "es6",
    "outDir": "dist"
  },
  "filesGlob": [
    "src/**/*.ts",
    "src/app.ts"
  ],
  "exclude": [
    "node_modules",
    "dist",
    "doc",
    "Gruntfile.js"
  ]
}
```
**Code**

```ts
// A *self-contained* demonstration of the problem follows...
function get(key:string): Promise<string> {
    return new Promise<string>((resolve, reject) => {
        setTimeout(() => {
            resolve('my value');
        }, 1000);
});
}

async function splitStringFromDB(key:string, delimiter: string): string[] {
    var string = await get(key);
    return string.split(delimiter);
}

console.log(splitStringFromDB('myKey', ' '));
```

**Expected behavior:**
No Compile errors
**Actual behavior:** 
error TS1055: Type 'string[]' is not a valid async function return type.

**Comment by Arnavion** [comment]
>With this behavior I'm not able to deasync a function like a db connection

async-await does not make asynchronous code synchronous. The result of an `async function` is a Promise.

**Comment by mathewmeconry** [comment]
Correct me if I'm wrong but the await function lets the function wait until the promise is resolved. 
So if I have a huge stack trace from the api endpoint to the database get request I've to pass promise after promise that I can use at the end the await call?

**Comment by mhegazy** [comment]
await does not pause the execution of the program until the function returns. all it does is it makes the rest of the code in the function execute after the promise is resolved.
so these two are equivalent:

```ts
async function f() {
    var value = await bar();
    return value;
}

function f() { 
    return bar().then((value) => value);
}
```

**Comment by mathewmeconry** [comment]
I know but when you add now to the async function a return type like string, then the compiler will print the error I mentioned

**Comment by mhegazy** [comment]
cause the function does not return a `string`; the function returns a `Promise<string>`. 

The `async` modifier is not part of the function signature, it is just a marker to tell the compiler you intend to use `await` in it, just to make sure you meant to do so, as it changes the semantics of the function call. in a sense it is an implementation detail about the function body and not part of the signature. For instance, when the compiler generates a .d.ts file for an async function, the `async` keyword is not added, rather it is a regular function that returns a `Promise`. I should add that this is not unique to TS, but is also done in other languages that implement this feature.

**Comment by mathewmeconry** [comment]
I don't agree with you. Because during runtime this function returns me a string if I hook in with a debugger and not a promise...

**Comment by basarat** [comment]
> I don't agree with you. Because during runtime this function returns me a string if I hook in with a debugger and not a promise...

[Just run](http://www.typescriptlang.org/play/#src=%2F%2F%20A%20*self-contained*%20demonstration%20of%20the%20problem%20follows...%0D%0Afunction%20get(key%3Astring)%3A%20Promise%3Cstring%3E%20%7B%0D%0A%20%20%20%20return%20new%20Promise%3Cstring%3E((resolve%2C%20reject)%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20setTimeout(()%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20resolve('my%20value')%3B%0D%0A%20%20%20%20%20%20%20%20%7D%2C%201000)%3B%0D%0A%7D)%3B%0D%0A%7D%0D%0A%0D%0Aasync%20function%20splitStringFromDB(key%3Astring%2C%20delimiter%3A%20string)%20%7B%0D%0A%20%20%20%20var%20string%20%3D%20await%20get(key)%3B%0D%0A%20%20%20%20return%20string.split(delimiter)%3B%0D%0A%7D%0D%0A%0D%0Aconsole.log(splitStringFromDB('myKey'%2C%20'%20'))%3B) see the console. Its a promise : 

![image](https://cloud.githubusercontent.com/assets/874898/18868549/ff29d3a0-84eb-11e6-8edc-4a41ad747b09.png)

**Comment by basarat** [comment]
I wrote some stuff a while back that needs updating but it that might help :rose: 

* Promises : https://basarat.gitbooks.io/typescript/content/docs/promise.html
* Generators : https://basarat.gitbooks.io/typescript/content/docs/generators.html
* Async Await : https://basarat.gitbooks.io/typescript/content/docs/async-await.html

**Comment by mhegazy** [comment]
thanks @basarat.

**Comment by matthewmueller** [comment]
I found to this thread while looking for the format of returning an async function. In case anyone else does the same:

```ts
export default async function Files(files: {
  [name: string]: string
}): Promise<() => Promise<void>> {
  return async () => {}
}
```

You return a promise that returns a function that returns a promise (that's a mouthful).

**Comment by awahab07** [comment]
So, what if I want a synchronous flow of code inside a method that returns non promise type. Is the following correct to do?

```
public getUserByIdSync(userId: number): User {
        let promisedUsers: User[];

        (async () => {
            await this.getUsers().toPromise<User[]>().then(users => promisedUsers = users);
        })();

        // Here users have been fetched and assigned, ?
        ...
       return promisedUsers[0];
}
```

**Comment by philipisapain** [comment]
It would be nice if there was a non-promise identifier for async return types. A big part of the value of async/await is not having to think in promises. Something that marks the return value as being returned asynchronously would be nice...

`async function getFoo():*String`

`const foo:*String = await getFoo()`

You could still (obviously) assign the synchronous return value to a Promise if you don't want to await.
`const foo:Promise<String> = getFoo()`

(where * is some character that denotes the value as asynchronously returned)

I guess there'd also be an argument to omit the `async` keyword since it's implied by the return type.

Just a thought :)

**Comment by reilue** [comment]
I recently faced this issue, and to be honest, when you ***wait*** for someone/something and she/he ***arrive***, you don't expect for anything else. Because the person (or the data) is already ***here*** (available).
