### ISSUE TITLE
Template string args don't resolve to correct overload

### ISSUE THREAD

**Issue by DaveBrue** [Microsoft/TypeScript#11096]
**TypeScript Version:**  1.8.0 / nightly (2.0.0-dev.201xxxxx)

**Code**

``` ts
let frame = 0;
window.addEventListener(`keydown`, e => {
  frame = e.which - 48;  // error: Property 'which' does not exist on type 'Event'
}, false);
```

**Expected behavior:**
It should work like a string literal does and resolve to the correct overload.

**Actual behavior:** 
It doesn't resolve correctly so it type checks based on the most general overload.

**Comment by DanielRosenwasser** [comment]
A while back I asked if no-substitution template strings should get the same treatment as regular strings. We opted not to, but I think seeing the way that JS users have been using them in lieu of standard string literals, we should consider this again.

This means (at least) that:

* String literal-typed template strings need to be made a thing.
* Computed property names need to work for templates.

**Comment by Kingwl** [comment]
seems this issue has been resolved via latest version
