### ISSUE TITLE
Refactor Sublime's plugin?

### ISSUE THREAD

**Issue by Alexey-T** [Microsoft/TypeScript#11091]
Hello,
I see that plugin for TS for Sublime exists, so I suggest plugin for CudaText. Py API in it.
Maybe with some changes, ST3 code can be used.
Suggested features: Auto-complete; Show function call-tip; Goto definition
Thanks

**Comment by DanielRosenwasser** [comment]
I don't think this is something the team can commit to maintaining, but I think we'd be more than happy to help support anyone who wants to build a plugin. [Our Sublime Plugin](https://github.com/Microsoft/TypeScript-Sublime-Plugin/) is open source, so others can base any implementations on that.

**Comment by Alexey-T** [comment]
What many ppl need is:
Py module which can

- start server for TS
- stop server (which open)
- call Py func to easy get completions, list, for given file/pos
- call Py func to easy get goto-definition properties, for given file/pos

**Comment by Alexey-T** [comment]
If such module will be done, it is easy for me and others, add editor support; no work with JS, with server

**Comment by DanielRosenwasser** [comment]
@zhengbli @billti is this something we'd be willing to take a PR on? Or is it trivial to do? Last I checked, each editor command sends a direct command to TSServer.

**Comment by zhengbli** [comment]
I may not understand you correctly, but our plugin is already written as a Python module (the "typescript" folder in the plugin repo). In addition, to provide features like get completions etc we still need to do the due diligence under the hood like maintaining the project system / updating text status on the server though. 

Sublime's model is we provide the command and they call it, you can look at each command file's `run` method to see how each command is conducted, for example https://github.com/Microsoft/TypeScript-Sublime-Plugin/blob/master/typescript/commands/go_to_definition.py#L8

**Comment by Alexey-T** [comment]
Yes you have "typescript" module,but i want refactoring of it:===> module must not have ST3 usages, all ST3 usages must be in outer code
Eg, file listeners.py:
~~~
import sublime_plugin

from ..libs.view_helpers import *
from ..libs import *
from .event_hub import EventHub

class TypeScriptEventListener(sublime_plugin.EventListener):
~~~
here you have ST imports and u use ST EventListener.
I want module w/o ST usages

**Comment by Alexey-T** [comment]
So what I suggest,

- split part of "typescript" to module "typescript_core", it must have MAX functionality for TS, it must have NO imports from Subl
- "typescript" must have only BINDINGS from Subl to "typesript_core": event listeners, reading files, calling auto-completion listbox, jump to files....

**Comment by zhengbli** [comment]
Aha I see what you mean now. That is definitely doable, though may take a while to implement. We will definitely be happy to take PRs about these changes.

**Comment by mhegazy** [comment]
This should be tracked in https://github.com/Microsoft/TypeScript-Sublime-Plugin instead of here.
