### ISSUE TITLE
Object.assign not type checking

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/TypeScript#11100]
TS 2.0.3

Given:

``` ts
(() => {
    type State = { foo: string };
    const state: State = { foo: 'bar' };
    const newState: State = Object.assign({}, state, { foo: 1 }) // I expect this to error
})();
```

I swear this used to work!

**Comment by Arnavion** [comment]
As I explained on IRC, the result of `assign` is `{ foo: string & number }`, so TS considers it okay to be assigned to `{ foo: string }`.

**Comment by sandersn** [comment]
I am close to having a PR for spread types, so when those are in, `Object.assign` will change to have the correct type:

`assign<T, U>(target: T, source: U): { ...T, ...U }`

Right now I am working in the branch `object-rest-spread-WIP` if you want to follow along.

**Comment by sandersn** [comment]
(also you'll just be able to use the syntax `{ ...state, foo: 1 }` instead of calling Object.assign)

**Comment by Arnavion** [comment]
@sandersn So with your change, the result of `assign` would be `{ foo: number }` ?

**Comment by sandersn** [comment]
Yes, which is not assignable to `State`, so it would error as desired.

**Comment by OliverJAsh** [comment]
Thanks, that's great @sandersn. I look forward to it!

@Arnavion How come this works?

```
const someState: { foo: string } & { foo: number } = { foo: 1 }
```

I think you explained why in IRC, but I'm not sure I completely understand. Are you saying in the above example we're trying to assign `number` to `string & number` which is an error, but if we try to assign `string & number` to `number` then it is allowed?

**Comment by Arnavion** [comment]
`DerivedClass` is assignable to `BaseClass` because all `DerivedClass` are also `BaseClass`. Similarly `string & number` is assignable to `number` because all `string & number` are also `number`.

`BaseClass` is not assignable to `DerivedClass` because an arbitrary `BaseClass` is not necessarily also a `DerivedClass`. Similarly `number` is not assignable to `string & number` because an arbitrary `number` is not necessarily also a `string`.

**Comment by OliverJAsh** [comment]
That makes sense, thank you @Arnavion:

``` ts
    // number is not assignable to string & number because an arbitrary number is not necessarily also a string.
    const x = 'foo' as string & number
    const x1: number = x
    // string & number is assignable to number because all string & number are also number.
    const x2: string & number = 'foo'
```

**Comment by danielearwicker** [comment]
@sandersn, this looks very good! Shouldn't the new type of `Object.assign` be:

```ts
assign<T, U>(target: T, source: U): T & { ...U }
```

i.e. all type features of target are preserved, with only properties from U tacked on. This covers the very common use case of adding properties to functions.

**Comment by sandersn** [comment]
@danielearwicker that's not quite right either because if the function already has a property that `source` overwrites then intersection doesn't give the right answer either. If we take as given that our only operators are spread and intersection, then I'd go with the stricter and more accurate one. (Of course we could introduce two kinds of spread but I don't like that idea.)

Can you point me to some source that spreads properties into functions? I'm always interested in collecting uses of the spread type &mdash; previously I thought that real-world uses were always with property bags.

**Comment by danielearwicker** [comment]
Yes, I see. I haven't been using object spread operator for this purpose (I only use TS) but I have been using `Object.assign` and similar functions to do the same thing.

Hiding in plain sight, jQuery's `$` is probably the famous example of a function with properties. It's very handy to be able to encapsulate some capabilities in an object that is also directly callable, giving succinct access to one preferred way of using it.

I've been working on a strongly-typed composable Redux library where I [make augmented functions this way](https://github.com/danielearwicker/immuto/blob/master/index.ts). Although as you can see, I've simply defined my own `assign` function so I can control the type signature anyway, so I can keep using intersection and you can ignore me! :)

**Comment by mhegazy** [comment]
We are looking for a new type construct (mapped types) to address this instead of the spread and rest operators in the type space. we should have updates on this in the next few days.

**Comment by falsandtru** [comment]
I made #12110. This patch makes possible to declare and constrain the parameters 2nd and above.

```ts
(() => {
  type State = { foo: string };
  const state: State = { foo: 'bar' };
  const newState: State = Object.assign<{}, State>({}, state, { foo: 1 }) // error
})();
```

**Comment by OliverJAsh** [comment]
Any updates on this now 2.1 is shipped?

**Comment by mhegazy** [comment]
https://github.com/Microsoft/TypeScript/issues/10727 tracks adding a spread/rest type operator support. Implementing https://github.com/Microsoft/TypeScript/issues/10727 is a prerequisite for this one.

**Comment by falsandtru** [comment]
I made the patch #13611 used Partial types.
@sandersn I think we should use both partial types and spread types.

**Comment by falsandtru** [comment]
Now I'm using the following signatures.

```ts
export function assign<T extends U, U extends object>(target: T, ...sources: Partial<U>[]): T;
export function assign<T extends U, U extends object>(target: {}, source: T, ...sources: Partial<U>[]): T;
export function assign<T extends object>(target: T, ...sources: Partial<T>[]): T;
export function assign<T extends object>(target: {}, source: T, ...sources: Partial<T>[]): T;
```

**Comment by alexluecke** [comment]
I think in a related issue, the spread operator type checking is not working as expected. The following does **not** produce a type error:

```
type someType = {
  test: string
};

const instanceSomeType1: someType = {
  test: 'testing'
};

const instanceSomeType2: someType = {
  randomKey: 123,
  ...instanceSomeType1
}
```

**Comment by dgreene1** [comment]
Subscribing for updates.

**Comment by metodribic** [comment]
What is the current status on this?

**Comment by sandersn** [comment]
@metodribic waiting on a spread type, which is waiting on a difference type to make sure JSX Higher-order-component scenarios work. Now that some kind of difference types are expressible using conditional types, the scenario may work. The conversation is happening at #10727.

**Comment by airtoxin** [comment]
This type definition of Object.assign can fixed in now using utility-types's assign definition https://github.com/piotrwitek/utility-types#assign (maybe steal implementations), but we should wait for type spreading features?

**Comment by sandersn** [comment]
@airtoxin would utility-type's Assign get this example right?

```ts
type O = {
  x: number
  y?: number | undefined
  m: () => number
}
declare class C {
  x: string
  y: string
  m2: () => string
}
// now Assign<C, O> should be
type Result = {
  x: number
  y: number | string
  m: () => number
}
```

**Comment by sandersn** [comment]
Currently it produces 

```
{
  x: number
  y?: number | undefined
  m: () => number
  m2: () => string
}
```

Meaning that it isn't correctly combining optional properties from the right, and isn't correctly discarding class-originating methods, which are on the prototype and will be discarded by Object.assign at runtime.

**Comment by zuzusik** [comment]
@sandersn would your work also fix [this example](http://www.typescriptlang.org/play/index.html#src=const%20a%3A%20%7B%20b%3A%20number%20%7D%20%3D%20%7B%20b%3A%20123%20%7D%3B%0D%0A%0D%0AObject.assign(a%2C%20%7B%20c%3A%20456%20%7D)%3B%0D%0A%0D%0Aa.c%20%3D%20456%3B%0D%0A%0D%0A)?

**Comment by sandersn** [comment]
(Reprinting example for ease of reading)

```ts
const a: { b: number } = { b: 123 };
Object.assign(a, { c: 456 });
a.c = 456;
```

The problem with that example is that we don't model `Object.assign`'s mutation of its first argument. That's not possible in Typescript today, since we'll just use the declared type of `a` all the way through the program. The control flow graph could allow us to model mutations to a type, but right now we only narrow types by removing constituents of a union type. And of course `a` doesn't have a union type.

**Comment by iflp** [comment]
A workaround could be:
``` 
(() => {
    type State = { foo: string };
    const state: State = { foo: 'bar' };
    const assignedValues: State = { foo: 1}; //complain expected
    const newState: State = Object.assign({}, state, assignedValues) 
})();
```

The trade-off being an extra line of code for type safety.

**Comment by RyanCavanaugh** [comment]
Tracking at #10727
