### ISSUE TITLE
Bad sourcemap paths when using gulp to build Microsoft/TypeScript

### ISSUE THREAD

**Issue by aozgaa** [microsoft/TypeScript#11105]
**TypeScript Version:**  master -- commit 40327b

Tested on Ubuntu 16.04 and Win10.

From a commandline (copying the Microsft/TypeScript readme instructions):

```
git clone https://github.com/Microsoft/TypeScript.git
cd TypeScript
npm install -g gulp
npm install
gulp local
```

checking any of the `*.js.map` files in the `built/local` directory reveals that the path to the source files is truncated. From `tsserver.js.map`, for example, we have

**Expected behavior:**

Obtained by building with jake:

```
{"version":3,"file":"tsserver.js","sourceRoot":"","sources":["file:////home/arthur/TypeScript/src/compiler/types.ts","file:////home/arthur/TypeScript/src/compiler/performance.ts","file:////home/arthur/TypeScript/src/compiler/core.ts","file:////home/arthur/TypeScript/src/compiler/sys.ts",

...
```

**Actual behavior:** 

Obtained by building with gulp:

```
{"version":3,"sources":["compiler/types.ts","compiler/performance.ts","compiler/core.ts","compiler/sys.ts","compiler/utilities.ts","compiler/diagnosticInformationMap.generated.ts","compiler/scanner.ts",

...
```

---

EDIT: clarifying sentence.

**Comment by Igorbek** [comment]
=1, I had to edit them manually in order to be able to debug.

**Comment by weswigham** [comment]
The paths are correct nowadays (ofc, `gulp` is our only build tool now, it had to be fixed) - `sourceRoot` is `""` and the paths all look like `../../src/compiler/core.ts`.
