### ISSUE TITLE
Visual Studio, use latest tsc release

### ISSUE THREAD

**Issue by jbondc** [Microsoft/TypeScript#1110]
How would I go about using the latest TypeScript with Visual Studio?

```javascript
C:\Program Files\Microsoft SDKs\TypeScript\1.0\tsc.js
```

Or making a patch and testing the Visual Studio integration with a locally built TypeScript?

**Comment by DickvdBrink** [comment]
I guess this is fixed by the https://github.com/Microsoft/TypeScript/blob/master/scripts/VSDevMode.ps1 script?

**Comment by mhegazy** [comment]
yup your are right.. as always thanks @DickvdBrink :)

For future searches, here is the wiki for enabling the dev mode: https://github.com/Microsoft/TypeScript/wiki/Dev-Mode-in-Visual-Studio
