### ISSUE TITLE
Node.parentElement should be maybe-null

### ISSUE THREAD

**Issue by evmar** [Microsoft/TypeScript#11113]
lib.dom.ts defines Node.parentElement as never-null:
https://github.com/Microsoft/TypeScript/blob/95c3eccbe9f3f7e1857ce157d437e6b80b3c9c6f/lib/lib.dom.d.ts#L8749

However, it's a pretty common pattern to write loops like

``` js
while (n.parentElement != null) {
  // [...]
  n = n.parentElement;
}
```

to walk up the node tree.

Also parentNode, previousSibling, nextSibling, firstChild, lastChild... (?)

**Comment by mhegazy** [comment]
previousSibling, nextSibling, firstChild, lastChild... etc.. are all fair game. please feel free to send us a PR for that. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

`parentElement` is a tricky one. All elements except document have parent elements, so it is going to be annoying to most ppl. so i am not sure here what is best option, either correctness or usability.

**Comment by kitsonk** [comment]
> All elements except document have parent elements,

If they are in the DOM.  It is potentially a way to identified DOM fragments and other scenarios when moving parts of the DOM about.  Strict is strict, (except when it isn't`!`). 😉

**Comment by mhegazy** [comment]
I would defer to @kitsonk opinion no this. I do not really write a lot of DOM code, so I would have limited insight here.
