### ISSUE TITLE
Extra Slash in sourcemap path on Ubuntu 16.04 (with jake)

### ISSUE THREAD

**Issue by aozgaa** [microsoft/TypeScript#11111]
**TypeScript Version:**  master -- commit 95c3ecc

**Operating System:** Ubuntu Linux 16.04

There is an extra slash at the beginning of the path to the source files referenced in the built `*.js.map` files. After removing the extra slash (using find-replace across all said files), source maps appear to work.

To reproduce, build with `jake local`.

**Expected behavior:**

In `built/local/tsserver.js`, we expect

```
file:///home/path/to/TypeScript/src/compiler/types.ts
```

(source-maps work with this change)

**Actual behavior:** 
In `built/local/tsserver.js`, we get

```
file:////home/path/to/TypeScript/src/compiler/types.ts
```

**Comment by pflannery** [comment]
@mhegazy 
Is it possible to bundle the source maps with each npm release in the future?, and
Is there a place I can get the current v2.3.3 maps without having to build them myself?

**Comment by mhegazy** [comment]
> Is it possible to bundle the source maps with each npm release in the future?

We only build them for debugging, for release we do not include the maps. 

> Is there a place I can get the current v2.3.3 maps without having to build them myself?

nope.

**Comment by weswigham** [comment]
Our sourcemaps all use relative paths now, so this is no longer a concern.
