### ISSUE TITLE
Adding baseUrl property to config breaks editor plugins

### ISSUE THREAD

**Issue by diestrin** [Microsoft/TypeScript#11115]
**TypeScript Version:**  2.0.3
Adding baseUrl to project makes VS Code and Sublime (and presumably others) work incorrectly.

- Make an empty project
- `typings install --global dt~jquery` (actually any library, is just to have a typings setup)
- Make a ts file inside /src folder and reference the library you just installed
- Restart your editor

**Code**
```ts
{
  "compilerOptions": {
    "target": "ES5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": true,
    "baseUrl": "./src"
  },
  "exclude": [
    "node_modules"
  ]
}
```

**Expected behavior:**
Everything should be working just find

**Actual behavior:** 
Typescript plugins report the global variables is not present. If you remove the **baseUrl** field and restart the editor, everything works as expected.

Running `tsc -p ./` compiles everything without an error.

**Comment by aluanhaddad** [comment]
I can't reproduce.

_src/a.ts_
```TypeScript
export const x = $('div');
```
other stuff:
_tsconfig.json_ (matches yours)
_typings/globls/jquery/index.d.ts_
_typings/globls/jquery/typings.json_
_typings/index.d.ts_

VS Code 1.5.3
```tsc --v``` = ```version 2.0.3```
```typings -v``` = `1.4.0`

**Comment by diestrin** [comment]
@aluanhaddad can you just confirm me you did the same as me in this video? http://take.ms/MRKEa

**Comment by diestrin** [comment]
Shit, sorry. I was pointing my `typescript.tsdk` to another node version with 1.8.x. My Bad :(
