### ISSUE TITLE
index signature used in generic class

### ISSUE THREAD

**Issue by fwang2002** [Microsoft/TypeScript#11120]
Can the index signature be used with generic, like the following:
```
class Map<K, T> {
    private map: {[index: K]: T};
}
```
here the compiler will inform "An index signature parameter type must be 'string' or 'number'"

**Comment by mhegazy** [comment]
Indexes can only be for string or number. This models the JS indexing semantics, which is basically converting the key to a string before lookup. Consider using ES6 maps for indexing with arbitrary objects.

**Comment by fwang2002** [comment]
can K be constrained to number | string.
besides, if the above grammar be supported, the application layer can take care of the constraint of K, and only instance Map with K be string | number.
For now, we can only use ES5.

**Comment by aluanhaddad** [comment]
It is worth noting that JavaScrip array indexing actually converts `number` to `string` before performing the lookup.

**Comment by mhegazy** [comment]
That is why in TS the numeric indexer target needs to be a subtype of the string indexer if both exist.

**Comment by fwang2002** [comment]
To make this usage more sensible, I take an enhanced example.
```
class SortedMap<K, T> { // where K only support number | string
    private map: {[index: K]: T};
    private array: T[];
}
```

**Comment by aluanhaddad** [comment]
It would make sense if this were valid:
```TypeScript
class SortedMap<K extends number | string, T> { 
  map: { [key: K]: T };
}
```
but it doesn't actually provide anything since you can index into anything  with either a string or number

**Comment by fwang2002** [comment]
@aluanhaddad Yes, if it's valid, then my problem is solved.

**Comment by aluanhaddad** [comment]
@fwang2002 unfortunately it's not valid, but it's not as useful as one might think it would be because you could still index with either type. Numeric indeces are string indeces.

**Comment by mhegazy** [comment]
see related reply in https://github.com/Microsoft/TypeScript/issues/6641#issuecomment-175727391
