### ISSUE TITLE
compileOnSave not working from Visual Studion 2015 after upgrade to TS 2.0

### ISSUE THREAD

**Issue by SergeyBarskiy** [Microsoft/TypeScript#11125]
Save a ts file in VS 2015.  JS file is not generated.  Apparently, the workaround for issue https://github.com/Microsoft/TypeScript/issues/8518 was causing issues.  I manually updated the services file from here https://github.com/Microsoft/TypeScript/blob/release-2.0/lib/typescriptServices.js and the issue was solved.  I think TypeScript installer should automatically update the services folder.
```

**Expected behavior:**
Should compile on save

**Actual behavior:** 
Does not

**Comment by mhegazy** [comment]
The JS file is not a versioned file. so the installer will favor the file with the latest time stamp. I have added a note to #8518 to ask for uninstalling TS 1.8.* before installing TS 2.0.* if this workaround was applied. sorry for the confusion.
