### ISSUE TITLE
Loss of backward compatibility when upgrading to version 2.0.3 (I think)

### ISSUE THREAD

**Issue by cawa-93** [Microsoft/TypeScript#11139]
**TypeScript Version:**  2.0.3

**Expected behavior:**
I expected that the upgrade from version 2.0.2 to version 2.0.3 should not cause problems as backward compatibility should be maintained. I expected that my code that compiles without errors in version 2.0.2 will be as error-free kompilirovatsya to version 2.0.3.

**Actual behavior:** 
In version 2.0.2 the compilation succeeds. With version 2.0.3 get three errors:
```
ERROR in ../components/dialogs-page/Dialog.class.ts
(7,14): error TS2420: Class 'Dialog' incorrectly implements interface 'IDialog'.
  Types of property 'type' are incompatible.
    Type 'DialogType' is not assignable to type 'DialogType'.

ERROR in ./Background/BgClass.ts
(84,7): error TS2365: Operator '===' cannot be applied to types 'AudioOptionStatus' and 'AudioOptionStatus'.

ERROR in ./Background/BgClass.ts
(86,7): error TS2365: Operator '===' cannot be applied to types 'AudioOptionStatus' and 'AudioOptionStatus'.
```

**Comment by mhegazy** [comment]
Newer versions contain bug fixes as well as new checks. You can find all the breaking changes in https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#typescript-20

As for your question, I can not help you further without looking at the definitions and use sites that triggered these errors. Please provide self contained code samples that we can look at.

**Comment by cawa-93** [comment]
```ts
// /source/components/dialogs-page/Dialog.class.ts
export enum DialogType {
	User,
	Chat,
	Group,
}

export class Dialog implements IDialog {
	peer_id: number;
	in_read: number;
	out_read: number;
	unread: number = 0;
/*7*/type: DialogType;
	title: string;
	url: string;
	photo_50: string;
	profiles: number[] = [];
	// ...
}
```

```ts
// /source/entrys/Background/BgClass.ts
export class BgClass {
	stg = <IStorageData>{};
	badge: number = 0;
	// ...
	playSound(newBadge: number) : this {
/*84*/	if (this.stg.options.audio === AudioOptionStatus.Never || newBadge <= this.badge) return this;
		const audio = <HTMLAudioElement>document.getElementById('audio');
/*86*/	if (this.stg.options.audio === AudioOptionStatus.Always) {
			audio.play();
			return this;
		}
		chrome.tabs.query({url: '*://*.vk.com/*'}, (tabs) => {
			if (!tabs.length) audio.play();
		});
		return this;
	}
	// ...
}
```

```ts

// /source/components/StorageApp/storage.d.ts
declare enum DialogType {
	User,
	Chat,
	Group,
}

interface IDialog {
	peer_id: number;
	unread?: number;
	title?: string;
	in_read: number;
	out_read: number;
	type: DialogType;
	profiles: number[];
	message?: IMessage[];
	photo_50?: string;
	isMore?: boolean;
}

declare enum AudioOptionStatus {
	Never,
	SomeConditions,
	Always,
}

interface IOptions {
	friends: boolean;
	photos: boolean;
	videos: boolean;
	messages: boolean;
	groups: boolean;
	app_requests: boolean;
	wall: boolean,
	mentions: boolean,
	comments: boolean,
	likes: boolean,
	reposts: boolean,
	followers: boolean,
	audio: AudioOptionStatus;
}

interface IStorageData {
	// ...
	options: IOptions;
	dialogs: IDialog[];
	// ...
	[key: string]: any;
}
```

**Comment by daschult** [comment]
I have the same issue. I had to change all references to my enum values to be <enum-type>.<enum-value>.valueOf().

**Comment by mhegazy** [comment]
here is a simpler repro for this issue:

```ts
namespace Ambient {
    export declare enum E {
        A,
        B
    }
}
namespace Concrete {
    export enum E {
        A,
        B
    }
}

var a: Ambient.E;
var c: Concrete.E;

a = c; // Concrete.E is not assignable to Ambient.E
```

The reason this error is shown is that the compiler could not guarantee the correctness of this assignment: 
- The compiler will generate code for `Concrete.E`, and since all members do not have any initializers, it will auto-number them. so `Concrete.E` is actually: `{ A = 0, B = 1 }`. 
- As for `Ambien.E` it does not have any intalizaters, so the values for `Ambient.E.A` can be anything at runtime. 

So to get rid of the warning, make sure your ambient enum has initalizers that matches your implementation enum. in the above example, adding initalizers to `Ambient.E` makes the two enums assignable again.

```ts
namespace Ambient {
    export declare enum E {
        A = 0,
        B = 1
    }
}
```

The other solution is to use `const enums` instead of the two enum declarations. `const enums` do not exist at runtime, so you can just declare them in the `.d.t` file and use them in the `.ts` file without having to redefine them. The compiler inlines all references to the const enum in the `.ts` file with its value, see [this example](http://www.typescriptlang.org/play/index.html#src=const%20enum%20E%20%7B%20%0D%0A%20%20%20%20A%2C%0D%0A%20%20%20%20B%0D%0A%7D%0D%0A%0D%0A%0D%0A%2F%2F%20emits%20cond%20%3F%200%20%3A%201%3B%0D%0Avar%20x%20%3D%20cond%20%3F%20E.A%20%3A%20E.B%3B%20) for more details.

**Comment by daschult** [comment]
I'm confused, because the original issue didn't have anything to do with assignment. The real problem was about comparing two values from the same enum definition:

`this.stg.options.audio === AudioOptionStatus.Never

declare enum AudioOptionStatus {
    Never,
    SomeConditions,
    Always,
}`

**Comment by mhegazy** [comment]
@daschult i do not know what the issue you are running into. you have not shared any information. 

based on the sample @cawa-93 shared, he has two declarations for the same enum. this is what i explained above. the two enums have the same name, this is why you get this error message ` Type 'DialogType' is not assignable to type 'DialogType'.`

**Comment by mhegazy** [comment]
//cc: @sandersn

**Comment by daschult** [comment]
Ah, I see. I was mostly interested in the 2nd and 3rd error messages.

`ERROR in ./Background/BgClass.ts
(84,7): error TS2365: Operator '===' cannot be applied to types 'AudioOptionStatus' and 'AudioOptionStatus'.

ERROR in ./Background/BgClass.ts
(86,7): error TS2365: Operator '===' cannot be applied to types 'AudioOptionStatus' and 'AudioOptionStatus'`

**Comment by mhegazy** [comment]
From @cawa-93 sample, i see a similar pattern for `AudioOptionStatus`. but i am working with snippets here, so i could be wrong :)

**Comment by mhegazy** [comment]
if you do not have the same pattern, but seeing errors that you do not expect, please file a new issue and provide self contained repro for the issue.

**Comment by cawa-93** [comment]
@mhegazy thanks. You'r example resolve my problem. 
```ts
declare enum AudioOptionStatus {
	Never = 0,
	SomeConditions = 1,
	Always = 2,
}

declare enum DialogType {
	User = 0,
	Chat = 1,
	Group = 2,
}
```
