### ISSUE TITLE
Top level imports in module declaration files

### ISSUE THREAD

**Issue by RecuencoJones** [Microsoft/TypeScript#11133]
Some days ago I posted [this question](http://stackoverflow.com/questions/39658833/typescript-default-constant-export) in StackOverflow and realized that I was having an issue with top level imports in a module declaration file.

Let me summarize the problem:

Consider two modules `Foo` and `Bar`. The latter extends the first. We are writing the declaration files and tests for both to ideally have them in DefinitelyTyped, hence using their tests. 

```typescript
// /foo/foo.d.ts
declare module 'foo' {
    export class Foo {
        public constructor()
        // ...methods
    }

    const foo: Foo;

    export default foo;
}

// /bar/bar.d.ts
/// <reference path="../foo/foo.d.ts"/>

import {
  Foo
} from 'foo';

declare module 'bar' {
  export class Bar extends Foo {
    public constructor();
    // more methods
  }
}

// /bar/bar-tests.ts
/// <reference path="../foo/foo.d.ts"/>
/// <reference path="./bar.d.ts"/>

import foo, {
  Foo
} from 'foo';

import {
  Bar
} from 'bar';

namespace TestBar {
  {
    let result: Foo;
    result = foo;
  }

  {
    let result: Foo;
    result = new Bar();
  }
}
```

With this setup, `bar.d.ts` and `bar-tests.ts` compilation was failing with:

>/bar/bar-tests.ts: error TS2307: Cannot find module 'bar'.
>/bar/bar.d.ts: error TS2664: Invalid module name in augmentation, module 'bar' cannot be found.

And the solution for it was to put the import statement inside `declare module 'bar'`:

```typescript
// /bar/bar.d.ts
/// <reference path="../foo/foo.d.ts"/>

declare module 'bar' {
  import {
    Foo
  } from 'foo';

  export class Bar extends Foo {
    public constructor();
    // more methods
  }
}
```

After fixing it I came to wonder, is there any case in which a top level import is allowed within a file declaring a module? In case there is not, I'd suggest adding a warning or error regarding this.

**Comment by mhegazy** [comment]
> After fixing it I came to wonder, is there any case in which a top level import is allowed within a file declaring a module? 

Module augmentation. please see http://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation for more details.

**Comment by mxl** [comment]
@mhegazy Could you provide more details on how can I use one top level import for multiple declared modules?

```typescript
declare module 'a' {
    import { Component } from 'react'
}

declare module 'a/b' {
    import { Component } from 'react'
}
```

running `dtslint` on this declaration results in:
> no-duplicate-imports             Multiple imports from 'react' can be combined into one.

**Comment by mhegazy** [comment]
looks like a dtslint issue to me.

**Comment by mxl** [comment]
@mhegazy Thanks! https://github.com/Microsoft/dtslint/issues/79
