### ISSUE TITLE
can't evaluate 3>4 with nightly build

### ISSUE THREAD

**Issue by nippur72** [Microsoft/TypeScript#11134]
**TypeScript Version:**  
Version 2.1.0-dev.20160925

**Code**

```ts
var x = 3>4;
```

**Expected behavior:**
no errors

**Actual behavior:** 
```
error TS2365: Operator '>' cannot be applied to types '3' and '4'.
```

**Comment by mhegazy** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/10120
