### ISSUE TITLE
Aggregate multiple modules into 1 single module

### ISSUE THREAD

**Issue by linvi** [Microsoft/TypeScript#11135]
I would like to do something similar to what Typescript offers in Node.Js but on a website application.
In node.js, if you `import * as ModuleAggregate from 'folder1'` which contain a file `index.ts`. 

`ModuleAggregate` will contain all the exported classes/functions/var that are available in the folder if you have an index.ts.

Is it possible, or could this be a new feature, that the index.ts provide an aggregate of multiple elements available in other files.

Here is an example :

``` typescript
// sql/table.ts
export class Table {}

// sql/row.ts
export class Row {}

// sql/column.ts
export class Column{}

// sql/index.ts (or any other name if possible)
import { Table as TableAlias } from './table';
import { Row as RowAlias } from './row';
import { Column as ColumnAlias } from './column';

export class Table = TableAlias;
export class Row = RowAlias;
export class Column = ColumnAlias;
```

Which will allow us in the application, if we need to access these 3 classes (available in 3 different files) to simply call :

``` typescript
// app.ts
import { Table, Row, Column } from 'sql/index';
```

Currently the only way I found to reproduce this pattern is to store all my classes inside the same file.
Is there a way to do that, which I am not aware of?

Thank you for your help and great work.

**Comment by andy-ms** [comment]
Any module can re-export values from any other module. This isn't specific to "index" files. See "Aggregating modules" [here](https://hacks.mozilla.org/2015/08/es6-in-depth-modules/).

When in node, an import of a directory `foo/` may give you `foo/index.ts`. If not in node, you should be able to write out `foo/index` to get it. Also see the [handbook](https://www.typescriptlang.org/docs/handbook/module-resolution.html).

**Comment by linvi** [comment]
Thank you, I was not aware of this syntax, the last time I read about that I need to use `import export` but it was not doing exactly the same thing.

Have a great day!
