### ISSUE TITLE
jsocnfig.json schema doesn't allow lib property

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#11144]
**TypeScript Version:**  2.0.3

The schema: https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/jsconfig.json doesn't support the lib property. Testing it shows that the lib property is supported in JS as well.

**Comment by mhegazy** [comment]
Fix up in https://github.com/SchemaStore/schemastore/pull/232
