### ISSUE TITLE
Using constants not allowed in tagged unions ? - Cannot find name error

### ISSUE THREAD

**Issue by mmc41** [Microsoft/TypeScript#11145]
**TypeScript Version:**  2.0.3

export const A = "a";
export const B = "b";
export type LETTERS1 = "A" | "B";
export type LETTERS2 = A | B;

**Expected behavior:**

Both LETTERS1 and LETTERS2 should be allowed.

**Actual behavior:** 

Only LETTERS1 compiles. LETTERS2 gives errors of type cannot find type x (where x is A or B).

**Comment by wallverb** [comment]
https://github.com/Microsoft/TypeScript/issues/11143
