### ISSUE TITLE
Tagged union types and using literal types defined outside the interface as discriminant

### ISSUE THREAD

**Issue by kjeske** [Microsoft/TypeScript#11143]
**TypeScript Version:**  2.0.2

To use tagged unions feature we have to introduce discriminant property in interfaces like:

``` ts
interface Action {
    type: "ACTION"
}
```

However when I define a string literal type outside the interface and try to use it as discriminant then I get an error

``` ts
let actionName: "ACTION"

interface Action {
    type: actionName <- error: cannot find name "actionName"
}
```

**Expected behavior:**
String literal types defines outside an interface can be used as discriminant property value.

**Comment by aleksey-bykov** [comment]
actionName in your example is defined as a value however is being used in a position where a type is expected, should be:

```typescript
interface Action { type: 'ACTION' }
```

**Comment by aleksey-bykov** [comment]
or
```typescript
interface Action { type: typeof actionName }
```

**Comment by jesiuu** [comment]
Thanks @aleksey-bykov. However, to make it working I had to use the following notation:

```typescript
const ACTION: "ACTION" = "ACTION"

interface Action {
    type: typeof ACTION
}
```
So I had to define a const of string type "ACTION" with value set to the same string "ACTION".

**Comment by mmc41** [comment]
Would be very nice if this could be fixed - at least so const string literal types defined outside (so they can be reused - so we can avoid use of magic strings all around in the code).

**Comment by mostr** [comment]
@mmc41 was looking for solution to exactly that same issue. Looks like [this one](https://github.com/Microsoft/TypeScript/issues/11784#issuecomment-255459451) solves it. At least it reduces magic strings duplication.
