### ISSUE TITLE
Tagged unions not inferred when returning objects implementing interfaces 

### ISSUE THREAD

**Issue by mmc41** [Microsoft/TypeScript#11146]
**TypeScript Version:**  2.0.0

```ts
interface Category 
{
    id: string;
    description: string;
}

interface TreeNodeBase 
{
  readonly children: TreeNode[];
  title() : string;
  id(): string;
}

interface CategoryTreeNode extends TreeNodeBase
{
  readonly kind: "category";
  readonly item: Category;
}

interface EmptyTreeNode extends TreeNodeBase
{
  readonly kind: "empty";
}

type TreeNode = EmptyTreeNode | CategoryTreeNode; // More variants in actual case.

function createCategoryNode(category : Category, children : TreeNode[]) : CategoryTreeNode
{
    return {
      kind: "category",
      item: category,
      children: children,
      title() { return (<Category>this.item).description; }, // Why is type of this.item not inferred ?
      id() { return (<Category>this.item).id; } // Why is type of this.item not inferred ?
    };
}
```

**Expected behavior:**

The factory method **createCategoryNode** should be able to return an object that is a CategoryTreeNode in a type safe manner without having to specify the type as done above when implementing the title and id functions.

**Actual behavior:** 

Right now, unless the type of this.item is explicitly given, typescript will regard the type of item as **any** instead of Category. Thus, the type of this.item is not inferred correctly.

**Comment by Arnavion** [comment]
Nothing to do with union types. `this` itself is `any` in methods in object literals. See #10835
