### ISSUE TITLE
NavigateTo should work on fully qualified names.

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#1115]
I should be able to get to `ts.forEachChild` by typing it in like that.

![qualified names](https://cloud.githubusercontent.com/assets/972891/4985060/54dbf3ea-6929-11e4-8061-ad9f183106ff.gif)

**Comment by DanielRosenwasser** [comment]
Hey @CyrusNajmabadi, you did some work on "Navigate To" not too long ago - do you know whether your work addressed this?

**Comment by CyrusNajmabadi** [comment]
This should be addressed by the work i did.  If it wasn't, let me know.
