### ISSUE TITLE
Playground: Can't scroll left with Mac trackpad on Chrome

### ISSUE THREAD

**Issue by stowball** [Microsoft/TypeScript#11159]
When the playground editors have horizontal scroll, you can't scroll left in Chrome on Mac as it triggers the back gesture.

**Expected behavior:**

When I 2-finger swipe to left, the editor should scroll.

**Actual behavior:** 

Back gesture is triggered

**Comment by kitsonk** [comment]
The Playground editor is built on [Monaco Editor](https://github.com/Microsoft/monaco-editor).  Maybe better to raise your issue there.

**Comment by stowball** [comment]
Hmmm it works properly there

**Comment by stowball** [comment]
Cool, logged it there https://github.com/Microsoft/monaco-editor/issues/211

**Comment by mhegazy** [comment]
thanks @kitsonk!
