### ISSUE TITLE
Use return type as an inference location

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#11152]
From https://github.com/Microsoft/TypeScript/issues/11054

``` ts
interface FolderContentItem{
    type: 'folder' | 'file';
}

let a:FolderContentItem[] = [];
a = [1,2,3,4,5].map(v=>({type:'folder'}))
```

Today this is an error without casting `"folder"` to the literal type. We have a contextual type coming from `a` that is not being used.

**Comment by HerringtonDarkholme** [comment]
Does this effectively mean curried function will be inferred?

```typescript
const curry = <K, T>(k: K) => (t: T) => {}

curry(123)('123') // K inferred to number, T inferred to string
```

**Comment by vendethiel** [comment]
> loacation

(nitpick: there's a typo in the title)

**Comment by a3gis** [comment]
That would be amazing to see. I stumbled upon a similar issue tonight, which is roughly the same as https://github.com/Microsoft/TypeScript/issues/1212.

**Comment by andy-ms** [comment]
Another case where this would be useful:
```ts
function id<T>(x: T): T { return x; }
function f(b: boolean): { n: number } {
    if (b) {
        return { n: 1 };
    } else {
        return id({ n: 1 });
    }
}
```
Find-all-references on the declaration of `n: number` should find all 3 references to `n`, but today misses the one inside `id()`.

**Comment by k8w** [comment]
Still have this problem, and also see this:
```ts
let a = [[1, 2], [3, 4]];
let b: [number, number][] = a.map(v => v);
let c: [number, number][] = a.map(v => [1,2]);
```

Both `b` and `c` has compile error:
> Type 'number[][]' is not assignable to type '[number, number][]'.

[1,2] is treated as number[] rather than [number, number]

**Comment by Pajn** [comment]
I'm moving the example from #21275 to here as I filed a duplicate

```typescript
type Path<T, V> = Array<string>

function path<T, A extends keyof T>(key: A): Path<T, T[A]>
function path<T>(path: string|Array<string>): Path<T, any> {
  if (typeof path === 'string') return [path] as Path<T, any>
  else return path as Path<T, any>
}

function field<T, V>(path: Path<T, V>) {
  return {path}
}

type User = {name: string}

// Errors
field<User, string>(path('name'))

// Works
field<User, string>(path<User, 'name'>('name'))
```

**Comment by DanielRosenwasser** [comment]
Keywords: map on array of tuple contextual contextually typed return type of lambda arrow function expressions

**Comment by RyanCavanaugh** [comment]
I think the only reason this doesn't work is because we widen the return type of the function expression?

**Comment by weswigham** [comment]
Actually, I think #25937 fixes this.

**Comment by m93a** [comment]
Seems like my proposal at #26979 could be a fix for this. While I don't propose the exact mechanism for literal type inference, I suggest an expression for type assertion that would prevent the type from widening. For example @k8w's code could be written this way:

```typescript
const a = [[1, 2], [3, 4]] as const;
const b: Array<[number, number]> = a.map(v => v);
const c: Array<[number, number]> = a.map(v => [1,2] as const);
```

While I agree that implementing the interference mechanism is important, this could provide a quick fix.

**Comment by CyrusNajmabadi** [comment]
Would definitely like to see this done.  We've hit this over in Pulumi as part of https://github.com/Microsoft/TypeScript/issues/11312. It seems really unfortunate that something as simple as:  `new Map(arr.map(a => [a.foo, a.bar]))` can't work properly.

**Comment by Kovensky** [comment]
Looks like I hit this on https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30057#discussion_r232123748

**Comment by ahejlsberg** [comment]
Fixed in #29478.

**Comment by CyrusNajmabadi** [comment]
Thanks much @ahejlsberg !  This will be very helpful in many of our complex, highly generic code spots!

**Comment by jeremychone** [comment]
I must be missing something. I installed Typescript 3.4.1, set it as my vscode typescript. 

```ts
interface Ent { id: number, name: string };

const entities: Ent[] = [{ id: 1, name: 'one' }, { id: 2, name: 'two' }];

const wrongInferredType = entities.map(ent => [ent.id, ent.name]);
// With unfortunately wrong type: (number | string)[][]

// this works: [number, string][] (as it should be)
const idEntities = entities.map(ent => [ent.id, ent.name]) as [number, string][];
```

**Comment by weswigham** [comment]
@jeremychone nothing changed w.r.t where we infer tuple types (excepting `const` contexts) - you'd need to have something with a tuple type on the LHS of that assignment for it to be interpreted as a tuple.

**Comment by jeremychone** [comment]
@weswigham Thank you. In fact, just realized I did not understand the root of the problem (which was that without typing, returning an array could not be assumed to be a tuple).
