### ISSUE TITLE
tsconfig outDir parameter failing

### ISSUE THREAD

**Issue by nitinbansal1989** [Microsoft/TypeScript#11156]
Since i updated the typescript compiler, my tsc wasn't working. I experimented and as soon as i remove outDir parameter from compiler options in tsconfig.config file, it is now working. 

**TypeScript Version:**  2.0.3

**Comment by mhegazy** [comment]
Can you share more information. Please share a self contained test along with the expected output, and the actual output.

**Comment by nitinbansal1989** [comment]
The issue is with --outDir option in the tsconfig file. When i removed the option, now its working fine. I didn't got down deeper. Please let me know if more info is needed.

**Comment by mhegazy** [comment]
> The issue is with --outDir option in the tsconfig file

can you elaborate on how it is failing, what is the current output?

**Comment by nitinbansal1989** [comment]
There is no output. Just that the javascript files are not getting generated from the ts files.

**Comment by tom-konda** [comment]
I have a similar problem on TypeScript 2.0.3.
I specified outDir parameter end with "../" but tsc command didn't generate any .js files.
When I run same command on TypeScript 1.8.10, .js files were generated successfully.

I tested on [this gist files](https://gist.github.com/tom-konda/7faf17575a7530720c3973f1ec1dfddc).

**Comment by mhegazy** [comment]
Thanks @tom-konda  for the repro. This looks like the same issue as https://github.com/Microsoft/TypeScript/issues/11621. 

If you do not have `exclude` property set, it is implicitly set to `["node_modules", .., <outdir>]`. since your `outDir` is a parent directory of your source directory, no files are included in the compilation.

to override this behavior specify empty `exclude` array.

**Comment by mhegazy** [comment]
I have also filed https://github.com/Microsoft/TypeScript/issues/11156 to track raising an error when no files are found to compile.
