### ISSUE TITLE
Possible bug: HTMLCollection type ostensibly doesn't contain symbol.iterator()

### ISSUE THREAD

**Issue by dsifford** [Microsoft/TypeScript#11162]
**TypeScript Version:**  nightly (2.0.0-dev.201xxxxx)

**Code**

```ts
const collection = document.getElementsByClassName('some-class');
const idList = [...collection].map(i => i.id);
```
[Playground](http://www.typescriptlang.org/play/index.html#src=const%20collection%20%3D%20document.getElementsByClassName('some-class')%3B%0D%0Aconst%20idList%20%3D%20%5B...collection%5D.map(i%20%3D%3E%20i.id)%3B)

**Expected behavior:**
HTMLCollection (I believe) has a Symbol.iterator in its prototype, so this should work fine.
 
**Actual behavior:** 

![image](https://cloud.githubusercontent.com/assets/5240018/18855881/5f542488-8424-11e6-9b99-c40894a19c75.png)

What's interesting is that `Array.from()` works fine here.

I apologize if this has already been reported. I tried searching through open issues to no avail. Thanks for all your work on this! 😄

**Comment by mhegazy** [comment]
Symbol.Iterator only exists at runtime if your underlying engine defines. you should see it if you use `--target ES6`. the playgound uses `--target ES5`

**Comment by dsifford** [comment]
@mhegazy Thanks for the quick response!

This is also occurring in a project I'm working on that targets ES6.

Here's the relevant JSON from my tsconfig. Am I missing something?
```json
"compilerOptions": {
        "target": "es6",
        "module": "commonjs",
        "moduleResolution": "node",
        "isolatedModules": false,
        "jsx": "react",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": false,
        "declaration": false,
        "noImplicitAny": false,
        "removeComments": true,
        "noLib": false,
        "preserveConstEnums": true,
        "suppressImplicitAnyIndexErrors": true,
        "noUnusedLocals": true,
        "noUnusedParameters": true
    },
```

**Comment by Arnavion** [comment]
HTMLCollection is not iterable per [spec,](https://dom.spec.whatwg.org/) just NodeList. Also see https://github.com/zloirock/core-js/issues/137#issuecomment-159531781

**Comment by mhegazy** [comment]
Thanks @Arnavion for pointing this out.

**Comment by dsifford** [comment]
@Arnavion Very interesting. Thanks so much for the info! (That dom spec document is particularly useful, so thanks for that as well!).

**Comment by dsifford** [comment]
@mhegazy With the recent info in mind, should `Array.from()` still work? Is there something internally different with using that method vs `[...iterable]`? Because I currently am able to get away with it.

**Comment by Arnavion** [comment]
[`Array.from` works on array-likes if `Symbol.iterator` is not a property of the target.](See http://www.ecma-international.org/ecma-262/6.0/#sec-array.from) (step 7 onwards)
