### ISSUE TITLE
Is there a way to enable `strictNullChecks` as a warning?

### ISSUE THREAD

**Issue by akosyakov** [Microsoft/TypeScript#11169]
It can be really useful during a transition phase. Especially if compilation fails because of errors in dependencies.

**Comment by kitsonk** [comment]
No

**Comment by aluanhaddad** [comment]
Just set
```JSON
{
  "compilerOptions": {
    "noEmitOnError": false
  }
}
```

**Comment by RyanCavanaugh** [comment]
Everything in TypeScript is already a "warning" and will emit code anyway (minus setting `noEmitOnError`)
