### ISSUE TITLE
Support importing multiple files via wildcards, replacing barrels

### ISSUE THREAD

**Issue by Meligy** [Microsoft/TypeScript#11168]
**[Feature Request]**

Hello,
Can we kill barrels please?

Let's assume we have this file structure:

```
- directives
  |- input.ts
  |- select.ts
- consumer.ts
```

If I want to write this: `import {Select, Input} from "./directives";` in `consumer.ts`, I have to add a barrel file `directives/index.ts`, with something like:

```
export * from "./input.ts";
export * from "./select.ts";
```

Can TypeScript do better, and save us from having to remember the extra step?

We cannot use `?` or `*` as valid filenames anyway, so, would it be possible to use them to flag that we want to import from multiple files?

So, without the `directives/index.ts` file at all, we'd be able to write something like:

```
import {Select, Input} from "./directives/*";
```

Again, the `*` in the module would be the trigger for this behaviour.

Ideally, we'd have a full wildcards support, but this can complicate things even more, so, at least supporting the `./path/to/single/folder/*` would be best for most cases.

**P.S.**

Thanks a lot for the super awesome free language and all the superior tooling around it.

**Comment by kitsonk** [comment]
This is counter to [TypeScript design goal](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals):

> 8) Avoid adding expression-level syntax.

Because TypeScript is a superset of JavaScript there has to be a hugely compelling reason to consider varying from that syntax.  Such behaviours of a module and module loaders are best championed with ECMAScript for inclusion in the language.  Module loading in the post ES2015 era is already enough of a mess, TypeScript deviating from that and breaking compatibility is likely not a good idea.

**Comment by mhegazy** [comment]
This would break single-file compilation scenario. think of users transpiling a file at a time. the emit transformation needs to be predictable and localized. in this proposal the generated code in one file, depends on the existence of other files, as well as their shapes. so it can not be done within a single file scope, but requires a complete program analysis.

Moreover, we would like to think that features that TS support will end up in the standard at some point in the future. I do not think this proposal would have much traction by module implementors. the main issue is a JS engine in a browser would have to do a check first to know that the target is a folder, and then load all its modules. these are two trips to the server, and that has been something that was been rejected in the past in favor of an explicit uri.

For that i do not think this is within the scope of the typescript project at the time being.

**Comment by Xzlash** [comment]
Would be a very helpful feature, but only with a `--supportFileWildcards` option maybe? Implying only for Node usage, not browser.
