### ISSUE TITLE
true == false - cannot be applied to types 'false' and 'true'.

### ISSUE THREAD

**Issue by cevek** [Microsoft/TypeScript#11178]
**TypeScript Version:**  Version 2.1.0-dev.20160927

**Code**

```ts
const a = false;
const b = a === true; //  Operator '===' cannot be applied to types 'false' and 'true'.
const c = true === false; // that is ok
```

**Comment by kitsonk** [comment]
Is there a real issue with this?  While the error message is potentially confusing, it is valid and TypeScript is identifying a position where you have a logic error, although the third statement also has the same logic error it is because it is comparing a `boolean` to a `boolean` instead of two incomparable literal types.  The behaviour could be stricter to interpret literal values as literal types for comparison, but I can't see where it is being already more strict is a problem.

```typescript
const a: boolean = false;
const b = a === true; // no issue
```

**Comment by cevek** [comment]
That issue from source code of mobx, it is simplified example

**Comment by cevek** [comment]
Also https://github.com/mobxjs/mobx/blob/master/src/core/derivation.ts#L75
`Operator '===' cannot be applied to types 'IDerivationState.POSSIBLY_STALE' and 'IDerivationState.STALE'.`

**Comment by wallverb** [comment]
https://github.com/Microsoft/TypeScript/issues/10120

**Comment by kitsonk** [comment]
@cevek, that is different than the reported issue... there the comparison is between a `let`, which should not automatically infer a literal type of `false`.  For example, this should work:

```typescript
let a = false;
const b = a === true; // Operator '===' cannot be applied to types 'false' and 'true'.
```

But the following works:

```typescript
let a = false;
a = true;
const b = a === true; // No error
```

Which means the CFA is tracking the assigned literal type of the code.  So I think the example need to be expanded upon, because the error isn't in the example, it is in CFA not properly tracking the type on assignment of a variable.

**Comment by cevek** [comment]
> ahejlsberg 
This is working as intended. The compiler performs control flow analysis and knows that p has the actual value Place.Left where you're performing the === operations, and it is calling out that it makes no sense to compare a value that is known to be Place.Left to a value that is known to be Place.Right. It's effectively like writing Place.Left === Place.Right or 1 === 2, both of which would also produce errors.

**Comment by RyanCavanaugh** [comment]
Is this a bug in the mobx code, or did `derivation.dependenciesState` actually change value between lines 63 and 75?

**Comment by cevek** [comment]
Yeah, `obj.get();` can change `derivation.dependenciesState`

**Comment by cevek** [comment]
duplicates of #10120 #11134

**Comment by jasonswearingen** [comment]
@cevek @ahejlsberg: Please reopen this issue.    control flow analysis fails when using closures such as this example:

```javascript
		var didAFix = false;
		_.forEach(this.invalid, (value:T, key:string) => {
			var fixedValue = func(value, key, this);
			if (fixedValue !== undefined) {
				this._accept(key, fixedValue);
				didAFix = true;
			}
		});
		//fixup state after modifications
		if (didAFix === true) {  //tsc error TS2365
			this._maintainValidState();
		}
```

I get a ```tsc``` compile error on the 3rd to last line (```if (didAFix === true)```):
```
src/validation.ts(120,7): error TS2365: Operator '===' cannot be applied to types 'false' and 'true'.
```

**Comment by RyanCavanaugh** [comment]
@jasonswearingen  see #9998 and the many bugs linked from it

**Comment by avonwyss** [comment]
Another one which bit me, just for completeness:
```ts
const x = true;

function fn(y: boolean): void {
	if ((y === false) || x) {
		// do something
	} else if (y === false) { // <-- " Operator '===' cannot be applied ..."
		// do something else
	}
}
```
In my specific use case there are additional conditions in the else-if condition, and the "y" is nullable, so that comparing with "false" does actually make sense, but in the end it boils down to the problem right here.

**Comment by David-OConnor** [comment]
This is definitely a bug, not intended behavior. If you check a boolean you gave a default value to in a loop, it raises this error, even if the loop can change its value.

**Comment by atlabiz** [comment]
## With typescript do this is work for me
```typescript
let whatToDo: any =  false;

if (whatToDo === true) {
        this.pages.push(this.pageRange);
      }
```

**Comment by gsdnano** [comment]
Same error when using simple statements such as

```
var b:boolean = false;
...
b === true ? 'n_' : ''
```

**Comment by kitsonk** [comment]
Code flow analysis is doing a better tracking of code than you might assume... In this case CFA has determined the only value `b` might have at this point in the code is `false`.

The _problem_ goes away, when the value cannot be statically determined anymore:

```ts
var b: boolean = false;

b = Math.random() % 2 ? true : false;

b === true ? 'n_' : '';
```

It is the goal of TypeScript to statically identify constructs that are likely to be errors, which a variable, without reassignment, within the same closure cannot be any other value than `false` so it is invalid to compare it to `true`.

**Comment by aluanhaddad** [comment]
Unless `...` changes the value of `b` such that it may become truthy, the compiler is correctly complaining about nonsense.

**Comment by se-schwarz** [comment]
The following peace of code produces the error, while working perfectly fine.

This [comment](https://github.com/Microsoft/TypeScript/issues/11178#issuecomment-309377822) from atlabiz works, but it's just a workaround.


```ts
let somethingHappenedIndicator = false;

const listener = service.register(() => {
  somethingHappened = true;
});

anotherService.doSomethingThatMayTriggerTheRegisteredCallback();

listener.unsubscribe();

if (somethingHappened === true) { // TS2365:Operator '===' cannot be applied to types 'false' and 'true'
  doSomething();
}
```

**Comment by RyanCavanaugh** [comment]
@se-schwarz see #9998

**Comment by marquizzo** [comment]
It feels like this would be less confusing if the error were worded better. My example is:

	this.changed = true;
	this.checkChanges();    // Changes the value of this.changed
	if(this.changed === false){return;} // typescript operator === cannot be applied to true and false

If it said "variable assigned value of true, therefore it could not be false" it would've become immediately clear what was wrong. Instead, it led me to believe that I was taking crazy pills and a strict equality could not be compared to `true` or `false`.
