### ISSUE TITLE
instanceof not properly casting object in nested callback function

### ISSUE THREAD

**Issue by kb3eua** [Microsoft/TypeScript#11182]
**TypeScript Version:**  2.0.3

**Code**

``` ts
// A *self-contained* demonstration of the problem follows...
    public imageChange(e: Event): void {
        let target: Element = e.srcElement;
        if (target instanceof HTMLInputElement && target.files.length === 1) {
            let file: File = target.files[0];
            if (file.type === MEDIA_TYPE_IMAGE_JPEG) {
                this._processFile(file, () => target.value = '');
            }
        }
    }
```

**Expected behavior:**
That "target.value" in the callback function would not be flagged as an error, as "value" is an actual property on types of HTMLInputElement.

**Actual behavior:** 
The "target" variable is not being cast as an HTMLInputElement inside of the callback function, causing the compiler to complain when attempting to access the "value" property.  It works properly when trying to access the "files" property in the "if" statement... it's just the callback that appears to be the problem.

**Comment by RyanCavanaugh** [comment]
See http://stackoverflow.com/questions/39702585/why-do-typescripts-type-guards-work-differently-in-the-parent-scope/39710641

**Comment by kb3eua** [comment]
@RyanCavanaugh Thanks... This must be a new feature of 2.x then, because this code worked in 1.8.10 and I only got this error when trying to upgrade to 2.0.3.

Changing the variable definition from "let target" to "const target" seems to resolve the issue.
