### ISSUE TITLE
Incorrect inferred return type for a function that returns a circular type referencing itself

### ISSUE THREAD

**Issue by guncha** [Microsoft/TypeScript#11189]
**TypeScript Version:** master at a633652f08db9efe43ea63df76ecc6edadbb89c5 (Sep 27, 2016)

**Code**

```ts
interface Fun<T> {
  (value: T)
}

function switcheroo<T>(component: Fun<T>): Fun<T> {
  return component
}

function MyComponent(value: string) {
  return {
    type: OtherComponent
  }
}

export const OtherComponent = switcheroo(MyComponent)
```

**Expected behavior:**

Expected type of `MyComponent` to be `(value: string) => {type: Fun<string>}` and type of `OtherComponent` to be `Fun<string>`

**Actual behavior:** 
Both types are `any`.

This is likely related or caused by the same thing as https://github.com/Microsoft/TypeScript/issues/5487 but I thought I'd contribute another test case.

**Comment by RyanCavanaugh** [comment]
See https://github.com/Microsoft/TypeScript/issues/10978#issuecomment-248382628
