### ISSUE TITLE
Hashmap (unexpectedly) doesn't include undefined as a possible return value when using strictNullChecks

### ISSUE THREAD

**Issue by DanTup** [Microsoft/TypeScript#11186]
Apologies if this has been covered before an/or is not a bug but I can't seem to find it in the issue list or any discussion of it online.

**TypeScript Version:**  2.0.3

Given this code:

```ts
let danny: { [name: string]: string; } = {};
let whatIsMyType = danny["test2"];
```

the type of `whatIsMyType` is `string` (I would expect `string | undefined`). This means I can write a method that pulls from the map and claims to return a `string` without any warning:

```ts
getPackagePath(name: string): string {
    return this.map[name];
}
```

Shouldn't `| undefined` be added implicitly to the type returned from a map like this?

**Comment by wallverb** [comment]
https://github.com/Microsoft/TypeScript/pull/7140#issuecomment-192670453

**Comment by blakeembrey** [comment]
Same issue as https://github.com/Microsoft/TypeScript/issues/9235 too.

**Comment by mhegazy** [comment]
closing in favor of #9235.

**Comment by ewinslow** [comment]
@mhegazy I think you forgot to close
