### ISSUE TITLE
Resolver preferring ts file imported from d.ts even-though d.ts is available

### ISSUE THREAD

**Issue by Bobris** [Microsoft/TypeScript#11196]
**TypeScript Version:**  2.0.3

**Code**

See minimal repro https://github.com/Bobris/tscbug.git

When compiling with tsc it will show resolving details:

```
c:\tscbug>tsc
======== Resolving module 'lib' from 'c:/tscbug/main.ts'. ========
Explicitly specified module resolution kind: 'NodeJs'.
Loading module 'lib' from 'node_modules' folder.
File 'c:/tscbug/node_modules/lib.ts' does not exist.
File 'c:/tscbug/node_modules/lib.tsx' does not exist.
File 'c:/tscbug/node_modules/lib.d.ts' does not exist.
Found 'package.json' at 'c:/tscbug/node_modules/lib/package.json'.
'package.json' has 'types' field 'index.d.ts' that references 'c:/tscbug/node_modules/lib/index.d.ts'.
File 'c:/tscbug/node_modules/lib/index.d.ts' exist - use it as a name resolution result.
Resolving real path for 'c:/tscbug/node_modules/lib/index.d.ts', result 'C:/tscbug/node_modules/lib/index.d.ts'
======== Module name 'lib' was successfully resolved to 'C:/tscbug/node_modules/lib/index.d.ts'. ========
======== Resolving module './nested' from 'C:/tscbug/node_modules/lib/index.d.ts'. ========
Explicitly specified module resolution kind: 'NodeJs'.
Loading module as file / folder, candidate module location 'C:/tscbug/node_modules/lib/nested'.
File 'C:/tscbug/node_modules/lib/nested.ts' exist - use it as a name resolution result.
Resolving real path for 'C:/tscbug/node_modules/lib/nested.ts', result 'C:/tscbug/node_modules/lib/nested.ts'
======== Module name './nested' was successfully resolved to 'C:/tscbug/node_modules/lib/nested.ts'. ========

```

**Expected behavior:**

import ./nested from lib/index.d.ts should resolve to lib/nested.d.ts

**Actual behavior:** 

import ./nested from lib/index.d.ts was resolved to lib/nested.ts

Compilation works but it is just probably slower than needed because full source needs to be parsed instead of just declaration file.
Solution would be to not publish original source code, but only declaration files, but I need it for other use-cases.

**Comment by mhegazy** [comment]
.ts files always have precedence. We have, for a while, only picked up .d.ts files from node_modules, and that broke scenarios where ppl are developing multiple modules in conjunction, and using npm link to link their sources.

So the recommendation, assuming you own the sources of the library, is to keep your .d.ts files in a separate folder than your .ts files. possibly use `--declarationDir` to specify that.

**Comment by Bobris** [comment]
Thanks, I will try declarationDir that looks like it could work.
