### ISSUE TITLE
[Errors] error recovery with duplicate extends clauses

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#112]
```TypeScript
class D extends C extends C {
    baz() { }
}
```
 
Expected: 

!!! 'extends' clause already seen.

Actual: 

!!! '{' expected.

!!! ';' expected.

!!! ';' expected.

!!! Unknown identifier 'baz'.

**Comment by DickvdBrink** [comment]
This one is already fixed. Tested on playground and latest master

**Comment by mhegazy** [comment]
thanks @DickvdBrink !
