### ISSUE TITLE
tsconfig baseUrl helper is misleading 

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#11203]
_From @michalvankodev on September 27, 2016 15:18_
- VSCode Version: 1.5.3
- OS Version: Fedora 24

Steps to Reproduce:
1. Open any project tsconfig.json
2. Into `compilerOptions` add `baseUrl`
3. A helper which should explain what baseUrl does shows a misleading message:

_"Base directory to resolve non absolute names"_

It should show: 
_"Base directory to resolve non-relative module names."_

I tried to search this and Typescript repository for a potential PR but I wasn't successful finding the definition for this message.

_Copied from original issue: Microsoft/vscode#12781_

**Comment by mhegazy** [comment]
The documentation is hosted on https://github.com/SchemaStore/schemastore. Feel free to submit a PR to update the documentation.

**Comment by michalvankodev** [comment]
I've submitted a PR: https://github.com/SchemaStore/schemastore/pull/233
