### ISSUE TITLE
Assigning a class to a property with signature '(): any' results in a compiler error

### ISSUE THREAD

**Issue by stijnherreman** [Microsoft/TypeScript#11208]
**TypeScript Version:**  1.8.7

**Code**

```ts
interface Foo {
    (): any;
}

class Bar {
    constructor() {
        console.log("Bar");
    }
}

function Baz() {
    console.log("Baz");
}

var Bat = (function () {
    function Bat() {
        console.log("Bat");
    }
    return Bat;
}());

const foo1: Foo = new Bar();
const foo2: Foo = new Baz();
const foo3: Foo = new Bat();
```

```js
var Bar = (function () {
    function Bar() {
        console.log("Bar");
    }
    return Bar;
}());
function Baz() {
    console.log("Baz");
}
var Bat = (function () {
    function Bat() {
        console.log("Bat");
    }
    return Bat;
}());
var foo1 = new Bar();
var foo2 = new Baz();
var foo3 = new Bat();
```

**Expected behavior:**
No error when assigning `new Bar()` to `foo1`, because in the emitted JavaScript, `Bar` and `Bat` are identical in how they work. `Bar` and `Baz` are also similar.

**Actual behavior:** 
The following compiler error is displayed:

> Type 'Bar' is not assignable to type 'Foo'.
>   Type 'Bar' provides no match for the signature '(): any'
> 
> const foo1: Foo

**Context:**
The definition file for Knockout has this ([source](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/47588ba8f9a2ceb05acef2ec2c69263cf057405d/knockout/knockout.d.ts#L611)):

```ts
    interface Config {
        viewModel?: ViewModelFunction | ViewModelSharedInstance | ViewModelFactoryFunction | AMDModule;
        template: string | Node[]| DocumentFragment | TemplateElement | AMDModule;
        synchronous?: boolean;
    }

    interface ViewModelFunction {
        (params?: any): any;
    }
```

Creating a component [like this](http://stackoverflow.com/a/30986290/247702) works fine, but displays a compiler error:

```ts
class ViewModel {
    // ...
}

export const MyComponent = {
    viewModel: ViewModel,
    template: require("./MyComponent.html"),
}
```

**Comment by RyanCavanaugh** [comment]
> No error when assigning new Bar() to foo1

I don't understand your assertion. It's clearly not legal to invoke an instance of `Bar` as if it were a function. It fails at runtime. If you tried to use `new Bar()` as the `foo1` contract indicates - by invoking it - it would not work.

**Comment by stijnherreman** [comment]
> It fails at runtime.

It doesn't. If I run the code on https://www.typescriptlang.org/play/ I see this in the browser console:

```
Bar
Baz
Bat
```

**Comment by RyanCavanaugh** [comment]
> It doesn't. 

It does. You said this:
```ts
interface Foo {
    (): any;
}
```
This means "Foo can be invoked as a function". In other words, your declaration of `Foo` implies that this is legal:
```ts
const x: Foo = ...;
x();
```

If you had written this code, which attempts to use that definition that you just wrote, you would get an error
```ts
const foo1: Foo = new Bar();
foo1();
```

**Comment by stijnherreman** [comment]
My apologies, it seems I made some errors in setting up a minimal example, it doesn't properly reflect the real code. I'll close this for now and I'll try to go over it again later.
