### ISSUE TITLE
Out of Band Type Annotation Support for Signatures

### ISSUE THREAD

**Issue by iclanzan** [Microsoft/TypeScript#11218]
I am not sure if it would be at all possible or feasible but I would really appreciate Hindley–Milner type signature support in TypeScript:

```js
// stringLength :: String -> Number
const stringLength = word => word.length
```

I am writing a lot of code like this as I find it much easier to read but unfortunately TypeScript doesn’t understand this notation.

Some relevant reading:

- [Ramda Type Signatures](https://github.com/ramda/ramda/wiki/Type-Signatures)
- [Mostly Adequate Guide to Functional Programming](https://github.com/MostlyAdequate/mostly-adequate-guide/blob/master/ch7.md)
- [Sanctuary Types](https://github.com/sanctuary-js/sanctuary#types)

**Comment by RyanCavanaugh** [comment]
What's the distinction vs this?
```ts
const stringLength: (s: string) => number = word => word.length;
```

**Comment by DanielRosenwasser** [comment]
Changing the title, since it doesn't actually have anything to do with Hindley-Milner which is an inference algorithm, not a syntactic style. Standard ML, for instance, doesn't use this syntax.

**Comment by johanssj** [comment]
Sorry, I don't understand. How is the intent of

// stringLength :: String -> Number
const  stringLength  =  word  =>  word.length

much different to:

const stringLength: (x: string) => number = str => str.length

console.log("the length is", stringLength("apple"))

// nicely type annotated and outputs: the length is 5

or even:

type String2Number = (x: string) => number

const stringLength2: String2Number = word => word.length

console.log("the length is", stringLength2("banana"))

// also nicely type annotated outputs: the length is 6

----------------------------------------

Justin Johansson:

https://github.com/johanssj

A first TypeScript mini-project:

Implementation of copy-on-write for JavaScript arrays using ES2015 Proxy 
Objects

https://github.com/johanssj/cowarray

----------------------------------------

**Comment by johanssj** [comment]
(Apologies for resend. Have no idea how subject line got changed in 
first reply from subject line by Sorin Iclanzan).


Sorry, I don't understand. How is the intent of

// stringLength :: String -> Number
const stringLength = word => word.length

much different to:

const stringLength: (x: string) => number = str => str.length

console.log("the length is", stringLength("apple"))

// nicely type annotated and outputs: the length is 5

or even:

type String2Number = (x: string) => number

const stringLength2: String2Number = word => word.length

console.log("the length is", stringLength2("banana"))

// also nicely type annotated and outputs: the length is 6

----------------------------------------

Justin Johansson:

https://github.com/johanssj

A first TypeScript mini-project:

Implementation of copy-on-write for JavaScript arrays using ES2015 Proxy
Objects

https://github.com/johanssj/cowarray

----------------------------------------

**Comment by mhegazy** [comment]
this would be my recommendation:

```ts
const stringLength = (word: string) => word.length;
```

**Comment by DanielRosenwasser** [comment]
I don't see enough of a motivation to depart from the ECMAScript-reserved syntax, especially given that there's a sufficient mechanism in place that doesn't have any specific problems. Thanks for filing though!

**Comment by iclanzan** [comment]
Wow, this was closed fast. I was hoping for more discussion. I know there are other TypeScript users that would like to see something like this supported.

> What's the distinction vs this? Just the syntactic location, or the actual form of the signature type?

> ```ts
  const stringLength: (s: string) => number = word => word.length;
  ```

I find something like the above very confusing/hard to read, and this is for the most basic example.

> Changing the title, since it doesn't actually have anything to do with Hindley-Milner which is an inference algorithm, not a syntactic style.

[Hindley-Milner](https://en.wikipedia.org/wiki/Hindley%E2%80%93Milner_type_system) is a type system, which does describe an inference algorithm, but also comes with a syntax which functional languages like Haskell and functional JavaScript libraries have adopted to use as type annotations.

> I don't see enough of a motivation to depart from the ECMAScript-reserved syntax.

What do you mean by “ECMAScript-reserved syntax”? Since when are these type annotations ECMAScript-reserved syntax? With my proposed annotations I can use regular ECMAScript which allows me to use it in projects where the move to the  TypeScript syntax is not desired.

**Comment by johanssj** [comment]
Good you came back and explained further as I completely misunderstood your question in the first instance. Sure, this syntax is very familiar to Haskellers

```
// stringLength :: String -> Number
const stringLength = word => word.length
```

and, IIRC, Elm (compile-to-JS) language also makes use of the same .. so you are certainly not alone in having some affinity for it.

I'm just a casual observer though does seem like your issue was closed off & dismissed rather quickly. Maybe for the moment you will just have to accept putting your style of type annotations in alla-comment-style, which, btw, is something that I understand Flow people subsequently embraced.

**Comment by iclanzan** [comment]
I am totally fine and actually prefer putting my type annotations in comments. The problem is I get now help from TypeScript using these type signatures.

**Comment by masaeedu** [comment]
Today you can write:

```
type StringLength = (s: string) => number
const stringLength: StringLength = word => word.length
```

**Comment by naholyr** [comment]
Not even close :/

**Comment by seanpoulter** [comment]
Has anyone found a way to support these type annotations? I'm jumping into a JavaScript project using these annotations and would love to support these type annotations in comments like the [original post above](https://github.com/Microsoft/TypeScript/issues/11218#issue-179882785).

This seems like a good fit for a [TypeScript Language Service Plugin](https://github.com/Microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin).

cc @iclanzan
