### ISSUE TITLE
Module exports should appear in completion list as functions, not properties

### ISSUE THREAD

**Issue by waderyan** [Microsoft/TypeScript#11219]
Original Issue https://github.com/Microsoft/vscode/issues/12852 reported by @mousetraps

Testing https://github.com/Microsoft/vscode/issues/12598

VS Code Insiders 1.6

![image](https://cloud.githubusercontent.com/assets/762848/18897314/156ae270-84de-11e6-857a-10a7cc687dca.png)

**Comment by waderyan** [comment]
Repro'd

![image](https://cloud.githubusercontent.com/assets/2449568/18931464/28da5586-8581-11e6-8b6b-e2006d175a46.png)

**Comment by mhegazy** [comment]
This is looks right to me. it is a property as far as the ES spec is concerned. the type of the property is a function though.

**Comment by mousetraps** [comment]
@mhegazy Ah yes, that's right - sorry, I should have tested it with a function argument. I was initially concerned it wouldn't provide information on the type of the property, but I see that I'm mistaken. `exports.XXX = function (req, res)` works fine. :-)
