### ISSUE TITLE
Specifying object literal types on the fly

### ISSUE THREAD

**Issue by wallverb** [Microsoft/TypeScript#11216]
Sometimes it would be handful to be able to specify type of object literal on the fly (without creating const / variable) with exact type definition

Hopefully it's not violating 'no new syntax' rule (too much)

So something like that:

```ts
interface A {
    a: string
}

const b = {
    c: {
        a: 'test'
    }:A   // b would be of type { c: A }
}


function test(d:string) {
    switch(d) {
        case 'anotherTest': return {a: 'test'}:A  // function would return type A
    }
}
```

Right now the closest I can get is to use type assertion

```ts
const b = {
    c: {
        a: 'test'
    } as A
}
```

but it will allow to provide more fields than necessary and I would want TS to throw an error if someone provides more fields

**Comment by kengorab** [comment]
No new syntax is needed for this. You could do

```typescript
const b: { c: A } = { // <- Note the type annotation on b
  c: {
    a: text'
  }
}
```

and

```typescript
function test(d:string): A {  // <- Note the type annotation on the function
    switch(d) {
        case 'anotherTest': return {a: 'test'}
    }
}
```

**Comment by RyanCavanaugh** [comment]
Same as #7481 ?

**Comment by wallverb** [comment]
> Sometimes it would be handful to be able to specify type of object literal on the fly *(without creating const / variable) with exact type definition*

@kengorab Thanks for answer but maybe my example shouldn't be as simple as I showed. I'm talking about building objects that are deeply nested and function that has multiple cases in switch statement

```ts
const z: {
  y: {
     x: {
        w: {
           v: {
                c: A
               }
           }
         }
      }
} = { y: { x: { w: { v: {c} } } } }
```
vs
```ts
const z =  { y: { x: { w: { v: { c }:A } } } }
```


and for functions with multiple case statements i would need to define const and then return const

**Comment by wallverb** [comment]
That's it @RyanCavanaugh - thanks for pointing it out - tried to find something similar - but sometimes it's difficult

**Comment by wallverb** [comment]
`{c: 'test'}:A` or `{c: 'test'} is A` would be awesome, but of course not sure if it has some other problems
