### ISSUE TITLE
VS2013, missing support for TS 2.0

### ISSUE THREAD

**Issue by karczk** [microsoft/TypeScript#11214]
Many people ask about TS 2.0 installer for VS2013. There has been no reply on official blog or twitter, which is annoying (just simple answer...). According to wiki, VS2013 is still supported. From my point of view, more companies use VS2013 (so do I) than Studio Code to develop business apps with TS. I submit bug, that VS2013 was abandoned for 2.0 without notice, but many people still use this plugin.

https://github.com/Microsoft/TypeScript/wiki/TypeScript-Editor-Support#visual-studio-20132015

**Comment by mhegazy** [comment]
Sorry for the delayed reply. TS 1.8 was the last supported release for Visual Studion 2013. We have moved our active development to Visual Studio 2015. 

You can still use [TS 1.8  on  VS 2013](https://www.microsoft.com/en-us/download/details.aspx?id=48739), and please let us know if there are any blocking issues.

**Comment by voltcode** [comment]
Can you open source the plugin so that the community can upgrade it ?

**Comment by voltcode** [comment]
Supporting as many IDEs as possible is a boost for TypeScript promotion and popularization. Please reconsider VS 2013 support.

**Comment by SitoCH** [comment]
Same request here, VS 2013 is still used especially for enterprise projects.

**Comment by Martinspire** [comment]
@mhegazy i can understand that active support has been dropped, but it would be a shame if the latest version doesn't get supported on older software. What is the problem with getting the latest version of typescript supported on visual studio? What would break if you increase the typescript version?

**Comment by mhegazy** [comment]
Just to be clear, TypeScript 2.0 is not available as a plugin for Visual Studio 2013. TypeScript 1.8 is the last version of TypeScript to be shipped to VS 2013. As noted earlier, we have moved our active development to newer version of Visual Studio. 

TypeScript 2.0 is available for Visual Studio 2015 as a [standalone installer](https://www.microsoft.com/en-us/download/details.aspx?id=48593), and in-box for [Visual Studio "15" Preview 5](https://www.visualstudio.com/en-us/news/releasenotes/vs15-relnotes).

Please let us know if there are any blocking issues on TypeScript 1.8 on VS 2013.

**Comment by voltcode** [comment]
@mhegazy can you release the vs2013 plugin source code to the community, if you decided not to support it?

**Comment by mhegazy** [comment]
@voltcode this is tracked by https://github.com/Microsoft/TypeScript/issues/2656

**Comment by HolgerJeromin** [comment]
Nullable types are TS2.0 only.
Our project is build with VS2015 (TS2.x) but our customers (extending small stuff) have to use VS2013 and are not able to use our `.d.ts` files as TS1.8 aborts if it finds a `null` type.

It would be nice for us to have a 1.8.6 for VS2013 which would ignore `null` types.

**Comment by gchurchley** [comment]
@mhegazy: please let us know if there are any blocking issues.
Yes, there are blocking issues. A lot of the newer `.d.ts` files (e.g. rxjs) throw errors with TypeScript 1.8.  We need the latest TypeScript version. IMHO it's way too early to drop TypeScript support on VS2013!

**Comment by RyanCavanaugh** [comment]
Safe to say this isn't happening; hopefully people are off VS2013 by now or have come to accept the situation.
