### ISSUE TITLE
Coding Guidelines: Accessors namingn convention

### ISSUE THREAD

**Issue by helmutgranda** [Microsoft/TypeScript#11227]
**TypeScript Version:**  2.0.3

**Code**

```ts
let passcode = "secret passcode";

class Employee {
    private _fullName: string;

    get fullName(): string {
        return this._fullName;
    }

    set fullName(newName: string) {
        if (passcode && passcode == "secret passcode") {
            this._fullName = newName;
        }
        else {
            console.log("Error: Unauthorized update of employee!");
        }
    }
}

let employee = new Employee();
employee.fullName = "Bob Smith";
if (employee.fullName) {
    console.log(employee.fullName);
}
```

**Expected behavior:**
Based on the ```Names``` Coding Guidelines ```#6``` it states:
Do not use "_" as a prefix for private properties.
However the sample code uses the underscore for provide properties:
source: https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Classes.md#accessors

**Actual behavior:** 
A different demonstration for private properties specially around accessors.

**Comment by RyanCavanaugh** [comment]
I'm not sure what you're asking for here. The coding guidelines are *for our own codebase* and are not meant to be the only correct way to write TypeScript code; other codebases do commonly use `_` as a private prefix and it's useful in the example because the backing field and the name itself otherwise have the same spelling so it's more clear what the relation between them is.

**Comment by helmutgranda** [comment]
Hey @RyanCavanaugh,

Thanks for the response and I do agree and see the benefit of using the ```_``` for a private prefix. For one I thought the coding guidelines where an overall recommendation and thanks to your correction I can see I was assuming wrongly.

Thanks again for the clarification.

**Comment by CSchulz** [comment]
@RyanCavanaugh Would it be possible to get a common coding guideline?

**Comment by RyanCavanaugh** [comment]
@CSchulz  see #878
