### ISSUE TITLE
Setting ArrayLike<T>.length or any index results in TS2450. (TSv2)

### ISSUE THREAD

**Issue by electricessence** [Microsoft/TypeScript#11226]
**TypeScript Version:**  2.0.3

**Code**

``` ts
var a:ArrayLike<number> = [];
a.length = 10; // TS2450: Left-hand side of assignment expression cannot be a constant or a read-only property.
```

I'm assuming there are other cases than ArrayLike<T> that this happens?

**Comment by RyanCavanaugh** [comment]
Only *actual* arrays have the property that setting their `length` changes the underlying length in a meaningful way. Example:
```ts
function fn() {
  arguments.length = 1;
  console.log(arguments[1]);
}
fn(0, 1, 2); // prints 1, not undefined
```

**Comment by electricessence** [comment]
What?  You can define what an actual array is yes.  But something that is "ArrayLike<T>" **could be anything**.

Why are we enforcing "ArrayLike<T>" to be read only?  Make NO SENSE.

**Comment by electricessence** [comment]
So you're telling me because of some weird edge case put into the compiler, I have to write my own ArrayLike<T>?

**Comment by electricessence** [comment]
Ok wow.  I don't know what to say here.
So now I write an identical interface to ArrayLike<T> and the compiler treats it differently.

**Comment by electricessence** [comment]
And you can't extend ArrayLike<T> without incurring the same restriction.

**Comment by electricessence** [comment]
@RyanCavanaugh I saw another issue related to length.  Has by chance this behavior changed?
Please respond to my previous comments above.
