### ISSUE TITLE
JS completions are... too complete 

### ISSUE THREAD

**Issue by waderyan** [Microsoft/TypeScript#11231]
_From @mousetraps on September 28, 2016 0:50_

Testing https://github.com/Microsoft/vscode/issues/12598

Two files `server.js` and `a.js`. `server.js` has no references to `a.js`, but `foo` nevertheless appears in the completion list.
![image](https://cloud.githubusercontent.com/assets/762848/18896874/26229080-84da-11e6-8ecf-e16240a9becd.png)

May be related to #12849

_Copied from original issue: Microsoft/vscode#12850_

**Comment by RyanCavanaugh** [comment]
I have to imagine that we'd get bug reports if we *didn't* show this. You have two files, both are open, it's just a suggestion, and JS has no intrinsic way to form scope groups anyway. What value is gained by *not* showing it?

**Comment by waderyan** [comment]
ping @mousetraps

@RyanCavanaugh help me understand your point of view. You think `foo` should be shown because:

1. The file with `foo` defined is open
2. There isn't a way to form scope groups

If the file was not open would you expect the suggestion not to show?

**Comment by mhegazy** [comment]
If you want the file not to show, i.e. you consider them two separate contexts, please create different jsconfig.json for each. if none is available, the assumption is all your open files are meant to be together.

**Comment by waderyan** [comment]
Ok thank you for the explanation.

**Comment by DanielRosenwasser** [comment]
Alternatively you can import/export something. We assume anything with an `import`/`export`/`require`/`module.exports` is a module and don't merge across the boundaries.

**Comment by mousetraps** [comment]
Makes sense, thx for the explanation!
