### ISSUE TITLE
Type of process.env is not check?

### ISSUE THREAD

**Issue by ThibaultRiviere** [Microsoft/TypeScript#11239]
**TypeScript Version:**  2.0.3

**Code**

```ts
const x : number = process.env.x || 1024;

```
**package.json**
```js
  "dependencies": {
    "@types/es6-shim": "0.0.28",
    "@types/node": "4.0.30"
  },
```

**Expected behavior:**
Got a compile error like : 
``` path_to_file(x,y): error TS2322: Type 'string' is not assignable to type 'number'.```

**Actual behavior:** 
No compile errror

**Comment by blakeembrey** [comment]
@ThibaultRiviere This is a correct error, `process.env` is a map of strings and not numbers.

**Comment by blakeembrey** [comment]
Are you sure that's the `node` definition you're using though? I see all the definitions from DefinitelyTyped (and therefore on NPM) using `any`.

**Comment by mhegazy** [comment]
as noted by @blakeembrey this is coming from https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types-2.0/node/index.d.ts#L352. Feel free to send a PR to DefinitelyTyped for a fix.

**Comment by ThibaultRiviere** [comment]
I don't understand .
Tsc is able to do the assignation between any and error ?

**Comment by ThibaultRiviere** [comment]
@blakeembrey  Yes exactly ```process.env``` is a map of strings and not numbers, so the assignation should not pass right ? And even if the type is ```any```,  it should not be assignable to a number, correct me if i'm wrong ?

**Comment by wallverb** [comment]
`process.env` is `any` in `@types/node` that's why you don't get any error

![image](https://cloud.githubusercontent.com/assets/1723815/18964906/ebc232ae-8648-11e6-9933-12b7849be260.png)

`any` is assignable to a number and vice versa

**Comment by blakeembrey** [comment]
@ThibaultRiviere No, you're correct. It's an error in https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types-2.0/node/index.d.ts#L352 though, not TypeScript.

**Comment by blakeembrey** [comment]
For reference, this is probably what it should look like (from @types): https://github.com/types/env-node/blob/master/6/node.d.ts#L460-L463.

**Comment by ThibaultRiviere** [comment]
Ok thanks guys, i didn't know that a type ```any``` was assignable to a type ```number``` .
Now i understand . :)

**Comment by mhegazy** [comment]
For further references: http://www.typescriptlang.org/docs/handbook/basic-types.html#any
