### ISSUE TITLE
Error TS2456: Type alias 'A' circularly references itself

### ISSUE THREAD

**Issue by Kevin-ADB** [Microsoft/TypeScript#11237]
**TypeScript Version:**  1.8.10

**Code**

```ts
interface IA {
	b: IB;
} // OK

interface IB {
	a: IA;
} // OK

type A = typeof a; // error TS2456: Type alias 'A' circularly references itself.
type B = typeof b; // error TS2456: Type alias 'B' circularly references itself.

var a = { b: <B><any>{} };
var b = { a: <A><any>{} };
```

**Expected behavior:**
The type A & type B should be the same with interface IA & IB in the code.

**Actual behavior:** 
Got compile errors.

**Comment by mhegazy** [comment]
type aliases are not like interfaces. interfaces are named types, where as type aliases are just aliases. internally as well they are treated differently, the compiler aggressively flatten types aliases to their declarations.

https://github.com/Microsoft/TypeScript/issues/6230 tracks this request.
