### ISSUE TITLE
Type narrowing not working as expected

### ISSUE THREAD

**Issue by avonwyss** [microsoft/TypeScript#11245]
**TypeScript Version:**  2.0.2 RC

**Code**
This code fails:

``` ts
function f1(arg: string[]) {}

function f2(arg: ArrayLike<string> | string[]) {
    if (!(arg instanceof Array)) {
        arg = Array.prototype.slice.call(arg) as string[];
    }
    // -> arg is always a string[] here
    f1(arg); // supplied parameter does not match signature...
}
```

However, this code shows no error:

``` ts
function f1(arg: string[]) {}

function f2(arg: string | string[]) {
    if (!(arg instanceof Array)) {
        arg = Array.prototype.slice.call(arg) as string[];
    }
    f1(arg);
}
```

**Expected behavior:**
The narrowing should recognize that `arg` must be a `string[]` when calling `f1`.

**Actual behavior:** 
The narrowing seems not to take place when one type is a subset of another, e.g. `ArrayLike<string>` is a subset of `T[]`. The issue can also be shown with this signature: `f2(arg: {length: number} | string[])`

**Comment by RyanCavanaugh** [comment]
This is due to subtype reduction confusing the narrowing logic, since the `arg` type union reduces to a non-union.

As a workaround, you could write something like this to prevent the two union operands from being reduced:
```ts
function f1(arg: string[]) {}

function f2(arg: (ArrayLike<string> & { push?: never }) | string[]) {
    if (!(arg instanceof Array)) {
        arg = Array.prototype.slice.call(arg) as string[];
    }
    // -> arg is always a string[] here
    f1(arg); // supplied parameter does not match signature...
}
```
