### ISSUE TITLE
Mistake in Documentation

### ISSUE THREAD

**Issue by knox97** [Microsoft/TypeScript#11248]
First I'm sorry for not using template but I just wanted to point out a mistake in Documentation,
on the picture below you can see a selected text which I think is not written correctly, again I know this is more for programming issues but I just wanted to contribute and help in a way, thanks for reading.

![workspace 1_026](https://cloud.githubusercontent.com/assets/19645574/18956001/1026ebf6-865a-11e6-9115-91159d03326a.png)

**Comment by mhegazy** [comment]
Fixed manually. thanks. for future reference, the sources for the handbook are in https://github.com/Microsoft/TypeScript-Handbook, and PRs for documentation fixes are always welcomed.
