### ISSUE TITLE
Comments removed before interface definition

### ISSUE THREAD

**Issue by nippur72** [Microsoft/TypeScript#11242]
Perhaps it's related to #11046, I can't say, so I am mentioning it:

**TypeScript Version:**  typescript@2.1.0-dev.20160929

**Code**

```ts
// before
interface someinterface {}
// after
```

**Actual behavior:** 
```ts
"use strict";
// after
```

**Expected behavior:** 
```ts
"use strict";
// before
// after
```

**Comment by mhegazy** [comment]
comments before interfaces are considered to be commenting the interface. since the interface is not emitted, the comment is not as well. this goes for property declarations, ambient declarations, module augmentation etc..

**Comment by nippur72** [comment]
unfortunately this makes the use of comments almost useless for post-processing purposes, e.g. it break my [ifdef-loader](https://github.com/nippur72/ifdef-loader):
```ts
// #if DEBUG
console.log("...");
// #else
```

**Comment by kitsonk** [comment]
A simple workaround:

```typescript
// #if DEBUG
console.log("...");
// #else
;
interface someinterface { }
```

emits:

```javascript
// #if DEBUG
console.log("...");
// #else
;
```
