### ISSUE TITLE
Proposal: Add strict comparison flag

### ISSUE THREAD

**Issue by markboyall** [Microsoft/TypeScript#11244]
A simple flag to enforce strict comparisons. When set, if the two operands of == have different types, the compiler should raise an error, regardless of if they are comparable in JavaScript.

Why not just use ===? Because then I'd have to go back through my whole codebase to replace every == with ===, and because it's a pain when writing in more than one language to remember that in TypeScript == is broken and I should be using === instead. It would be a lot simpler if == just wasn't broken to begin with.

**Comment by mhegazy** [comment]
One of the main design goals of TypeScript is to align with JavaScript (see https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals#goals). `==` has useful use cases, e.g. comparing against `null` and `undefined`. disallowing it or changing its semantics would go against this design goal.

As for the issue of using `==` I would recommend adding a [tslint rule for using `==`](http://palantir.github.io/tslint/rules/triple-equals/) to your build.

**Comment by markboyall** [comment]
TypeScript already doesn't align with JavaScript when JavaScript made decisions that were broken, for instance, dynamic typing. I don't see how this is any different.

**Comment by aluanhaddad** [comment]
@markboyall typescript fully supports JavaScript's dynamic typing and in fact it is the default. variables without an inferred type are given the dynamic type `any`. Furthermore, TypeScript's type system was specifically designed to statically model JavaScript's dynamic one.

As @mhegazy noted, tslint is the answer here. I have exactly such a rule in all of my projects.

**Comment by markboyall** [comment]
Having a completely broken comparison operator and having to arse around endlessly with linting tools and unnecessary language-changing mental overhead would remain fully supported and the default.

**Comment by kitsonk** [comment]
> Having a completely broken comparison operator

Mostly broken.
