### ISSUE TITLE
Suspected regression from 1.8.x to 2.0 release

### ISSUE THREAD

**Issue by IanYates** [Microsoft/TypeScript#11240]
**TypeScript Version:**  2.0 - downloaded via the announcement blog post.  VS 2015 Update 3.

**Code**
I have a helper function like so

``` ts


function ifNotNull<T, R>(element: T, funcIfElementNotNull: (e: T) => R, funcIfElementIsNull?: R | (()=>R)) {
    if (element !== undefined && element !== null) {
        return funcIfElementNotNull(element);
    }

    if (_.isFunction(funcIfElementIsNull)) {
        return funcIfElementIsNull();
    } else {
        return funcIfElementIsNull;
    }
}

```

Note that I've got _.isFunction typed as

``` ts
isFunction<T>(object: T | (()=>T)): object is (()=>T);
```

After updating to 2.0 I got a bunch of errors in my codebase where it appears the inferred return type of the function is the union type `R | (()=>R)` whereas it used to be, in 1.8, inferred as just `R`.

The idea is that I often have code like

``` ts
var thingId = ifNotNull(someExpensiveFuncThatMightReturnNull(), x => x.Id);
```

which lets me get thingId to be typed the same as whatever x.Id is and cleanly handle `someExpensiveFuncThatMightReturnNull()` being null without having to invoke it twice and use the || operator to substitute my null value.

**Expected behavior:**
I would have expected that the `if` block would eliminate types from the union (as was the case in TS 1.8)

``` ts
if (_.isFunction(funcIfElementIsNull)) {
    //type of funcIfElementIsNull is ()=>R.  Inferred correctly in 1.8.x and 2.0.x TS versions.
        return funcIfElementIsNull();
    } else {
    //type here should infer as R, but it's inferring as R | (()=>R).  This is the regression
        return funcIfElementIsNull;
    }
```

**Actual behavior:** 
See the comments in expected behaviour.

My fix was to add an explicit return type of R to the function and a cast on the final return statement.

I don't have TS 1.8 handy anymore to actually inspect the types of the variables & parameters at various points in the function.

**Side note**
Looking forward to trying out the new 2.x features :)  Thanks!

**Comment by IanYates** [comment]
Note that my calling example of that function didn't provide the 3rd parameter.  An example with it, which  doesn't change the actual problem, would be

```ts
var thingId = ifNotNull(someExpensiveFuncThatMightReturnNull(), x => x.Id, myFallbackId);
```
or
```ts
var thingId = ifNotNull(someExpensiveFuncThatMightReturnNull(), x => x.Id, myFallbackIdCalculatorFunc);
```

Often I just want the nullness to safely propogate which is why the third parameter is optional.

**Comment by mhegazy** [comment]
The narrowing for having a call signature does not conclusivelly say that `funcIfElementIsNull` is not a function. so in the else branch it is still `R | ()=>R`. I would recommend changing the narrowing logic to be:

```ts
    if (typeof funcIfElementIsNull === "function") {
        return funcIfElementIsNull();
    } else {
        return funcIfElementIsNull;
    }
```

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
