### ISSUE TITLE
Large JavaScript file breaks JavaScript services

### ISSUE THREAD

**Issue by andy-ms** [microsoft/TypeScript#11249]
**TypeScript Version:**  nightly (2.1.0-dev.20160928)

**Code**
##### make-large-file.js

``` js
let s = ""
for (let i = 0; i < 1000000; i++)
    s += `const x${i} = 0;\n`
require("fs").writeFileSync("large.js", s)
```

**Expected behavior:**

Hovering over `s` gives useful info.

**Actual behavior:** 

Hovering over `s` initially gives useful info.
But after running `node make-large-file`, hovering over `s` shows `Loading...` (this is in VSCode).
Deleting `large.js` doesn't solve the problem.

Note that `large.js` does not have to ever be opened or imported to cause the problem. So in a large JavaScript project, the presense of a single large file somewhere can bring the whole system down. I discovered this in a [project](https://github.com/Azure/azure-storage-node) with some generated `.nock.js` files in the `test` directory, and could not get services on tests.

**Comment by RyanCavanaugh** [comment]
I believe this has been fixed
