### ISSUE TITLE
Autocomplete not working as expected

### ISSUE THREAD

**Issue by waderyan** [Microsoft/TypeScript#11253]
_From @lejun on September 3, 2016 16:5_
- VSCode Version:1.4.0
- OS Version:mac os 10.11.5

Ready to work:

```
typings install --global --save dt~react
typings install --global --save dt~react-native
```

tsconfig.json

``` json
{
    "compilerOptions": {
        "target": "es6",
        "module": "es6",
        "jsx": "react",
        "outDir": "built",
        "rootDir": "src",
        "sourceMap": true,
        "noImplicitAny": true,
        "allowJs": true,
        "allowSyntheticDefaultImports": true
    },
    "filesGlob": [
        "typings/index.d.ts",
        "typings/globals/**/*.d.ts",
        "src/**/*.ts",
        "src/**/*.tsx"
    ],
    "exclude": [
        "node_modules",
        ".vscode/launchReactNative.js",
        "built",
        "index.android.js",
        "index.ios.js"
    ]
}
```

example:
1.

``` js
import * as RN from 'react-native';
const{View,Text,Navigator} = RN;
```

<img width="625" alt="ok tips" src="https://cloud.githubusercontent.com/assets/4397814/18225933/1988820e-7232-11e6-9918-8bd5e7c4758b.png">

2.

``` js
import {View,Text,Navigator} from 'react-native';
```

<img width="535" alt="error tips" src="https://cloud.githubusercontent.com/assets/4397814/18225941/35077792-7232-11e6-827b-16fcf31e2735.png">

question:
### Why can normally prompt mode 1, and mode 2 not?

_Copied from original issue: Microsoft/vscode#11498_

**Comment by waderyan** [comment]
@lejun thank you for opening this issue. To make sure I understand correctly... you are asking why you are prompted to choose `Navigator` in screenshot 1 but not in screenshot 2?

**Comment by waderyan** [comment]
I apologize for the spam. Strange issue on my end with the comment button.

**Comment by waderyan** [comment]
_From @lejun on September 7, 2016 1:30_

Thank you for your reply.
The screenshot 1 is correctly.(react component). The second method can not be normal prompt.

**Comment by waderyan** [comment]
_From @leaxoy on September 10, 2016 15:59_

+1

**Comment by waderyan** [comment]
_From @preetb123 on September 14, 2016 9:45_

@lejun how are you able to get autocomplete  for ReactNative components, as in the above fig.

**Comment by waderyan** [comment]
_From @lejun on September 15, 2016 4:3_

@preetb123 
```ts
import * as RN from 'react-native';
const{View,Text,Navigator} = RN;
```

**Comment by waderyan** [comment]
@DanielRosenwasser can you advise me and OP on this issue? 

There seems to be something strange with the import system. I would expect auto complete to suggest `Navigation` in both of the above screenshots.

**Comment by waderyan** [comment]
_From @DanielRosenwasser on September 29, 2016 18:10_

I'm not totally sure why that happens. If VS Code only displays items as returned, and you're using our prefix logic, this might be a bug on us.

**Comment by waderyan** [comment]
I'll move this over then to have help investigating.

**Comment by waderyan** [comment]
@lejun do you have a minimal repo we could copy and paste to test this out? Also can you try this with the latest bits by downloading [Insiders](http://code.visualstudio.com/insiders)?

**Comment by mhegazy** [comment]
This looks a lot like https://github.com/Microsoft/TypeScript/issues/4577, can you verify you are still seeing this issue on TS 2.0 or later?

**Comment by mhegazy** [comment]
closing for now. please reopen if this is still an issue.
