### ISSUE TITLE
Union type wrongly translated

### ISSUE THREAD

**Issue by pankleks** [Microsoft/TypeScript#11260]
**TypeScript Version:**  (2.1.0-dev.20160929)

**Code**
Such method is compiled without any error

``` ts
sort(key: string, dir: -1 | 1 = 1) {
}
```

But generated code is wrong

``` js
sort(key, dir = -1 | 1) { }
```

**Comment by RyanCavanaugh** [comment]
Can't repro in master. Here's what I'm running

In
```ts
class C {
    sort(key: string, dir: -1 | 1 = 1) {
    }
}
```
with `--target ES6`

Out
```ts
class C {
    sort(key, dir = 1) {
    }
}
```
