### ISSUE TITLE
Generics parameter type check not working?

### ISSUE THREAD

**Issue by radarsu** [Microsoft/TypeScript#11262]
**TypeScript Version:**  nightly (2.0.0-dev.201xxxxx)

**Code**

``` ts
class X<T> {
    constructor() {

    }
}

class Y<T> {
    item: X<T>
    constructor(thisItem: X<T>) {
        this.item = thisItem;
    }
}

let x = new X<string>();

// new Y<number> expects as parameter X<number> but even though
// sending X<string> instead doesn't rise error
let y = new Y<number>(x);
```

Can anyone explain me why it is not raising error? Is it just me misunderstanding something in the generics type check concept or it is a bug?

**Comment by RyanCavanaugh** [comment]
https://github.com/Microsoft/TypeScript/wiki/FAQ#generics

**Comment by radarsu** [comment]
Thank you for a quick answer! I've been looking for such article for last two hours.

**Comment by RyanCavanaugh** [comment]
Can I ask what search terms you were using so we can try to title the pages better?

**Comment by radarsu** [comment]
Most of them were: typescript generics type check, typescript nested generics, typescript generics parameter not checked, typescript generics advanced guide

**Comment by RyanCavanaugh** [comment]
The TypeScript FAQ seems to have really bad pagerank; not sure what to do about it. :/

**Comment by mhegazy** [comment]
@RyanCavanaugh, may be we should host this on the site as well.

**Comment by radarsu** [comment]
I've read a lot about typescript on stackoverflow and I've never seen anyone linking this great FAQ there.

Maybe try putting this link as a late-answer for questions like this: http://stackoverflow.com/questions/17382143/how-to-create-a-new-object-from-type-parameter-in-generic-class-in-typescript

**Comment by RyanCavanaugh** [comment]
The website is a good idea. Maybe we should just have a separate section in the Handbook

**Comment by mhegazy** [comment]
If you move them to the handbook I can get them uploaded.

**Comment by radarsu** [comment]
Hey, I know it's absolutely not related to the topic, but wrong indentation in typescript-formatter annoys me a lot and I am not sure if creating new issue here for this problem is a good idea (it is related to this repository though: https://github.com/Microsoft/TypeScript/wiki/Using-the-Language-Service-API), so I'd like to ask if it's normal that typescript formatting makes this:
```
User.update({
    id: user.id,
}, {
    test: "test",
});
```
Look like this:
```
User.update({
    id: user.id,
}, {
        test: "test",
    });
```

Link to original issue I've created at typescript-formatter repository: https://github.com/vvakame/typescript-formatter/issues/53
