### ISSUE TITLE
Missing "Function.prototype.toString" in lib.d.ts

### ISSUE THREAD

**Issue by lord-saumagen** [Microsoft/TypeScript#11269]
**TypeScript Version:**  1.8.0 

Dear Ladies and Gentlemen,

I would like to bring to your attention, that the following function is not defined in the actual *lib.d.ts*.

- Function.prototype.toString

See image:

![function prototype](https://cloud.githubusercontent.com/assets/9468599/18976600/5dbbc716-86b3-11e6-8ead-29610eb90d4e.PNG)

Kind reagars, Lord Saumagen

**Comment by Istar-Eldritch** [comment]
@zhengbli should this be added on top of release-1.8 or in the current master branch?

**Comment by zhengbli** [comment]
For lib.d.ts related issues, please contribute to to https://github.com/Microsoft/TSJS-lib-generator instead as these library files are generated be a script instead of hand-written. Instruction for contribution please see https://github.com/Microsoft/TSJS-lib-generator#contribution-guidelines

**Comment by DanielRosenwasser** [comment]
`Function` implicitly has a `toString` by virtue of it being in `Object`; however, we don't show the apparent members of `Object` in every completion list because it can be noisy. @mhegazy can correct me if I'm wrong.

**Comment by mhegazy** [comment]
I do not know if there is a science for this to be frank. we blocked the object members from showing in completion, as they were noisy. but then added the function ones since users want to call bind/apply/prototype often. so if `toString` is another common operation on `Function` we can add it to the `Function` interface and it is going to show in the completion list.

**Comment by lord-saumagen** [comment]
Dear Ladies and Gentlemen,

now I'm really confused. There is a 'toString' function declared on every object prototype listed in "lib.d.ts". Even the String object has a 'toString' function on it's prototype. It may sound stupid to have a function which cast a string to a string, but at least it's consistent, because every object has a toString function on it's prototype. But the Function object has not, because it's noisy? Why isn't it noisy on the String object where it is also stupid? Please reveal the rules which qualify a function as "noisy" in the context of one object and as "normal" in the context of another.

Kind regards, Lord Saumagen.

**Comment by RyanCavanaugh** [comment]
I don't think `String` should have an explicitly-declared `toString` -- it's noisy. We should be able to delete it.

**Comment by aluanhaddad** [comment]
@RyanCavanaugh a usecase for `String.toString` could be for a union of string and another type.

That said, I agree it's noisy and I've never written code like this.

**Comment by RyanCavanaugh** [comment]
There wouldn't be any change in behavior in that case anyway -- primitive string values still get the apparent properties from `Object`, which includes an identical `toString` signature

**Comment by mhegazy** [comment]
thanks @falsandtru!
