### ISSUE TITLE
Parameter types in package.json only works for CommonJS

### ISSUE THREAD

**Issue by MasGaNo** [Microsoft/TypeScript#11273]
**TypeScript Version:**  2.0.3
**VSCode Version:**  1.5.3

Hi!

I create a private library for my company, and I include my _.d.ts_ file into the _package.json_ of my library.

Then, I create an application that include my private library as dependency. With basic parameters, all works (completion in the latest version of Visual Studio Code, and transpilation).

But, if I change the module system in the _tsconfig.json_ of my application from _CommonJS_ to _UMD_ it doesn't work anymore.

To illustrate that, I create 2 fake projects: 
https://github.com/MasGaNo/FakeLibrary
https://github.com/MasGaNo/FakeLibraryConsumer

So the FakeLibrary is a basic library, and the FakeLibraryConsumer is my app that use the library.

**CommonJS**
![image](https://cloud.githubusercontent.com/assets/5469433/18982495/e88ba7de-86e6-11e6-842d-71dd86253249.png)
```shell
$ tsc
$
```

**UMD**
![image](https://cloud.githubusercontent.com/assets/5469433/18982505/fc47de00-86e6-11e6-84a4-16a624b67170.png)
```shell
$ tsc
src/index.ts(1,30): error TS2307: Cannot find module 'fakelibrary'.
src/index.ts(6,14): error TS2339: Property 'foo' does not exist on type 'FakeLibraryConsumerClass'.
$
```

**Expected behavior:**
The declaration file into my library should be found for any kind of module system.

**Actual behavior:** 
The declaration file into my library works only for _CommonJS_, so I should publish my declaration file to DefinitelyTypes, but it's not something I want because it's an internal private project.

Thank you.

P.S.: the last version of TypeScript is very wonderful! Congrats to everybody!

**Comment by zhengbli** [comment]
Can you try add:
```
"moduleResolution": "node"
```
in your compiler options?

**Comment by MasGaNo** [comment]
Great! It works!

Sorry for my mistake, but maybe it should be include in this document: https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html

Because it's not easy to find full documentation for declaration file inside a module instead of publishing them directly to DT repository.

Thank you for your help.
