### ISSUE TITLE
const foo: Set<string> = <any>[]; // compiles!

### ISSUE THREAD

**Issue by tcrognon** [Microsoft/TypeScript#11272]
**TypeScript Version:**  2.0.3 with --target es6

**Code**

```ts
const foo: Set<string> = <any>[];
foo.add('bar');
```

**Expected behavior:**

Should emit type error during compilation.

**Actual behavior:** 

Compiles without errors and, as expected, receive "foo.add is not a function" when run.

**Comment by zhengbli** [comment]
Why should there be error? The type annotation wins over the inferred type (which is `any`), and `add` does exist in `Set<T>`.

**Comment by DanielRosenwasser** [comment]
This is basically like asking why the type system doesn't yell at you when you've gone out of your way to lie to it.

You're saying something has a type of `any` which is assignable to anything. Then you're assigning it to a binding with the type `Set<string>` which is permitted. Naturally, anything you can do with a `Set<string>` follows for `foo`.
