### ISSUE TITLE
String literal type match issue

### ISSUE THREAD

**Issue by chrisblossom** [Microsoft/TypeScript#11270]
**TypeScript Version:**  2.0.3

**Code**

``` ts
interface IFakeObject {
    other: 'test';
}

function otherTest(params: IFakeObject) {
    return params;
}

const shouldBeValid = {
    other: 'test',
};

// Typescript gives the error: "Type 'string' is not assignable to type '"test"'"
otherTest(shouldBeValid);

const works: IFakeObject = {
      other: 'test',
}
```

**Expected behavior:**
No Typescript errors. 

**Actual behavior:** 
`"Type 'string' is not assignable to type '"test"'"`

Sorry if this is a duplicate or expected behavior. I tried searching without success.

**Comment by wallverb** [comment]
Type of `shouldBeValid.other` is string, you could do

```ts
const shouldBeValid = {
    other: 'test' as 'test',
};
```

**Comment by chrisblossom** [comment]
I am not sure how useful string literals are with the current implementation if this is working as intended, especially for libraries.

To expand on https://github.com/Microsoft/TypeScript/issues/9336#issuecomment-228191216 

I would expect string literals to behave as follows:
```typescript
const defaultAlignment = 'center'; // pass
let alignment = defaultAlignment; // pass

alignment = 'left'; // pass

let toLeft: string = defaultAlignment; // pass
toLeft = 'left'; // pass

let onlyCenter: 'center' = defaultAlignment; // **should** pass (currently fails)
onlyCenter = alignment; // fail

const shouldFail: 'left' = defaultAlignment; // fail
```
As expected ``defaultAlignment`` type is inferred as ``string``, I think it should also "remember" the value 'center'. 
I don't think this is a breaking change because ``defaultAlignment`` would not be inferred as only ``'center'`` (which would be a breaking change and unexpected/unwanted behavior). Am I missing something here?

**Comment by kitsonk** [comment]
When you created the object literal:

```typescript
const shouldBeValid = {
    other: 'test',
};
```

You are suggesting that TypeScript should understand your intent here, and infer a literal value for all values, e.g. the `typeof shouldBeValid`:

```typescript
type ShouldBeValid = { other: 'test'; };
```

Which while it server your purpose, would be overly restrictive in many use cases:

```typescript
shouldBeValid.other = 'foo'; // Value of 'foo' cannot be assigned to type of 'test'
```

When you use object literals in a place where they are not variables, and therefore cannot be further used, TypeScript will allow the narrowing of the type, but when assigned to a variable, TypeScript assumes you intend to change it down the road (or why would you have assigned it to a variable?) and therefore, if you want to be taken literally, you have to specify you want to be taken literally.

Or use the object literal directly:

```typescript
interface IFakeObject {
    other: 'test';
}

function otherTest(params: IFakeObject) {
    return params;
}

otherTest({ other: 'test' }); // no error
```

I don't really think that limits the usefulness.

**Comment by chrisblossom** [comment]
```typescript
type ShouldBeValid = { other: 'test'; };
shouldBeValid.other = 'foo'; // Value of 'foo' cannot be assigned to type of 'test'
```
@kitsonk I am not suggesting ``shouldBeValid.other`` to be invalid as explained in https://github.com/Microsoft/TypeScript/issues/11270#issuecomment-250925283.

```typescript
interface IFakeObject {
    other: 'test';
}

function otherTest(params: IFakeObject) {
    return params;
}

const shouldBeValid = {
    other: 'test',
};

// Typescript gives the error: "Type 'string' is not assignable to type '"test"'"
otherTest(shouldBeValid);

shouldBeValid.other = 'foo'; // should pass
otherTest(shouldBeValid); // should now fail

const works: IFakeObject = {
      other: 'test',
}
```

> TypeScript assumes you intend to change it down the road (or why would you have assigned it to a variable?)

Sometimes you assign an object to a variable for readability.


```typescript
otherTest({ other: 'test' }); // no error
```
I actually find it awkward/unexpected that this does not produce an error, but defining the object outside of the function does. I would expect Typescript to treat objects as Javascript would.

**Comment by kitsonk** [comment]
> I would expect Typescript to treat objects as Javascript would.

Has in having a super loose type system?

**Comment by chrisblossom** [comment]
Sorry I wasn't more specific. I simply mean defining an object and passing it somewhere, whether it is inside a function param or outside, will produce the same result.

**Comment by kitsonk** [comment]
> I simply mean defining an object and passing it somewhere (whether it is inside a function param or outside) will produce the same result.

Well, since JavaScript doesn't have a type system to speak of, that would be comparing apples to oranges in my opinion.

You don't really want TypeScript to do that.  It isn't just literal inference that would produce surprising results, there are all sorts of assumptions that TypeScript makes based on the surrounding context about types that make it more productive (e.g. less annoying).

When you assign an object literal to a variable, 99% of the time it is because the developer expects to make changes to it before it is used.  It might be just to be able to reuse it, but even then, it is reasonable to expect it properties to mutate.  If they don't want to mutate it, or have very narrow types used, then the developer should be explicit about it.

When an object literal is directly passed as an argument, then 0% of the time it is because the developer expects to make changes to it before it used.  Therefore, TypeScript can automatically infer the narrowest type without causing any harm.

In *all* cases the developer has every opportunity to be explicit about their types and intent, instead of just leaving TypeScript to guess and do the least amount of harm.

**Comment by amarinov** [comment]
I've run into the same "issue", but I would agree that the behaviour is unexpected. Here's an example:

Works:
```
type A = "test1" | "test2";

let a: {b: A} = {
    b: window ? "test1" : 'test2'
}
```

Doesn't work:
```
type A = "test1" | "test2";

let c = window ? "test1" : 'test2'

let a: {b: A} = {
    b: c
}
```

Now that doesn't seem right...

**Comment by mhegazy** [comment]
use `const` instead of `let`

```ts
type A = "test1" | "test2";

const c = window ? "test1" : 'test2'

let a: {b: A} = {
    b: c
}
```
