### ISSUE TITLE
get error [SCRIPT1010: Expected identifier] when using export default on IE8

### ISSUE THREAD

**Issue by twoeo** [Microsoft/TypeScript#11276]
**TypeScript Version:**  1.8.0 / nightly (2.0.0-dev.201xxxxx)
2.0.3

**Code**

```ts
//Global.ts
export default class Global{
  static init(){
    //...
  }
}

//XXX.ts
Global.init();

//Compiled XXX.js
Global_1.default.init();
```

★ es5-shim was used ★

**Expected behavior:**
Run normally on IE8

**Actual behavior:** 
SCRIPT1010: Expected identifier   (Because of "default" is a reserved string)

**Suggestion**
Maybe it's better :
```javascript
Global_1['default'].init();
````

Don't want to use '--target es3', because need use Accessors, and es5-shim works well on IE8.

**Comment by mhegazy** [comment]
should be fixed by https://github.com/Microsoft/TypeScript/pull/11652
