### ISSUE TITLE
Error setting method on a function

### ISSUE THREAD

**Issue by connorhartley** [Microsoft/TypeScript#11275]
**TypeScript Version:**  2.0.3

**Code**

```ts
function createMessageBox() {

  addLine.editLine = editLine;
  return addLine;

  function addLine (text: string, id?: number) {
    // stuff..
  }

  function editLine (text: string, id: number) {
     // stuff..
  }
}

```

**Expected behavior:**
No errors. Method added to the function successfully.

Accessible by
```ts
let test = createMessageBox();
test.editLine("test", 0);
```

Outputs on node
```text
> test.editLine
[Function: editLine]
```

**Actual behavior:** 
Console error when compiling
```ts
commandLine.ts(10,11): error TS2339: Property 'editLine' does not exist on type '(text: string, id?: number) => number'.
```

**Comment by kitsonk** [comment]
You are using implicit typing in that `addLine` is simply declared as a function, and not declared as an interface which has a property `editLine`.  TypeScript is keeping you from doing something you have implied you don't want to do.  One of the *many* ways to deal with this would be:

```typescript
interface AddLine {
    (text: string, id?: number): void;
    editLine(text: string, id: number): void;
}

function createMessageBox() {

  (<AddLine> addLine).editLine = editLine;
  return <AddLine> addLine;

  function addLine (text: string, id?: number) {
    // stuff..
  }

  function editLine (text: string, id: number) {
     // stuff..
  }
}

const msgBox = createMessageBox();
msgBox.editLine; // No Error
```

This is very basic TypeScript though and this is an issue tracking forum for defects and enhancements of TypeScript.  It would be better to seek this sort of general support from StackOverflow, Gitter or IRC.
