### ISSUE TITLE
Roadmap: Wrong link

### ISSUE THREAD

**Issue by datokrat** [Microsoft/TypeScript#11287]
I didn't manage to "fork" the [Roadmap](https://github.com/Microsoft/TypeScript/wiki/Roadmap), so I just want to point out that the link "Support type-checking of computed properties for constants and Symbols" should reference to https://github.com/Microsoft/TypeScript/issues/5579 and not to https://github.com/Microsoft/TypeScript/issues/2103.

I suppose this is not by design???

**Comment by mhegazy** [comment]
thanks for the report. should be fixed now
