### ISSUE TITLE
Visual Studio 2015 TypeScript won't transpile

### ISSUE THREAD

**Issue by blubberbo** [Microsoft/TypeScript#11283]
**TypeScript Version:**  2.0.3

This is my tsconfig file:

```
{
  "compileOnSave": true,
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false
  },
  "exclude": [
     "node_modules"
 ]
}
```

I have a project in Visual Studio 2015 Update 3 with TypeScript version 2.0.3 and none of my .ts files are compiling on save anymore. I can run the command `tsc (file path)` which will transpile the .ts file into a .js, but it does not create a map, which makes it so I cannot debug in Chrome. Simply saving a .ts file does not have any effect.

The machine I am working on is Microsoft Windows Server 2012 as User A. Any Visual Studio project I open has the same symptoms and will not compile TypeScript, however, Users B and C on the same machine are not experiencing any issues (also in Visual Studio 2015 Update 3).

It appears to me that it may somehow be related to the user account I am using - the evidence being that other users on the same machine, using the same Visual Studio are not having the same problems I am.

Is there something that is user specific that could have been changed on my account that would cause this type of behavior and not have been changed for other users?

Thank you in advance for any help

**Comment by mhegazy** [comment]
this could possibly be related to https://github.com/Microsoft/TypeScript/issues/11110. do you see other features broken?

**Comment by zhengbli** [comment]
What is your global `tsc` version that you run from command line? That should not be related to VS though.

**Comment by blubberbo** [comment]
@mhegazy I will do what that post suggests and get back to you, thanks!

@zhengbli `tsc -v Version 2.0.3` as returned from the Package Manager Console

**Comment by mhegazy** [comment]
> @mhegazy I will do what that post suggests and get back to you, thanks!

Wait.. there is nothing suggested in this post yet. we originally thought it was a setup issue. but it is not.

**Comment by mhegazy** [comment]
Do you see other features broken as well? colorization, completion, find all references, nav bar, etc..?

**Comment by blubberbo** [comment]
as far as I can tell, no, it is just when I save a .ts file nothing happens. well that's not true, on the bottom left it says "Item Saved". 

also, in my project properties there is no typescript tab. not sure if that is related.

other than that, I do not see anything else glaring at me, although I would be happy to check something specific if you would like

**Comment by mhegazy** [comment]
in your help\about what version of TS do you see?

**Comment by blubberbo** [comment]
2.0.3.0 and I changed my csproj file to be 2.0 for typescript

**Comment by mhegazy** [comment]
what version is your OS specifically? is it R2? 

also what version do you see on`C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TypeScript\Microsoft.VisualStudio.LanguageServices.TypeScript.dll` ?

**Comment by mhegazy** [comment]
And do you have `HKEY_CURRENT_USER\SOFTWARE\Microsoft\VisualStudio\14.0\TypeScriptLanguageService\EnableDevMode` by any chance?

**Comment by blubberbo** [comment]
correct, Windows Server 2012 R2 Standard

C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TypeScript\Microsoft.VisualStudio.LanguageServices.TypeScript.dll -> properties -> details -> file version = 14.30921.1.0

I do not. `HKEY_CURRENT_USER\SOFTWARE\Microsoft\VisualStudio\14.0\` does not even contain a folder named `TypeScriptLanguageService`

**Comment by blubberbo** [comment]
I can tell you that I was wrong, the other users on the same machine _are_ experiencing the same issue. I am going to try and uninstalling 2.0 so that they can continue to work.

I will say that the reason I upgraded to 2.0 originally is because I was having these symptoms in my project even with 1.8

**Comment by mhegazy** [comment]
> I will say that the reason I upgraded to 2.0 originally is because I was having these symptoms in my project even with 1.8

this is a different issue then. does this happen for different projects? or just one? does compile on save work for a new project ? if not can you share your project?

**Comment by blubberbo** [comment]
it happens for all projects on this machine for just me.

compile on save does not work on a new project.

what do you mean share my project?

**Comment by blubberbo** [comment]
the main problem manifests itself in that the .map files are not created, so I don't have any typescript files in my google chrome, so I can't debug it

**Comment by blubberbo** [comment]
also, now I my Visual Studio does not show any color coding in typescript files

**Comment by mhegazy** [comment]
> also, now I my Visual Studio does not show any color coding in typescript files

What version of ts is this? 2.0.3 or 1.8?

**Comment by blubberbo** [comment]
we downgraded to 1.8. in help -> about it says 1.8.36 and `tsc -v` says 1.8.10

**Comment by mhegazy** [comment]
How did you downgrade? uninstall 2.0 + repair on VS?

**Comment by blubberbo** [comment]
uninstalled and reinstalled 1.8 from an installer. it works for other people on the same box now. we did not do a repair on VS

**Comment by mhegazy** [comment]
I do not know how it would work without a repair. the version of TS installed by update 3 (1.8.36) is different from that one that was last published on the [download page](https://www.microsoft.com/en-us/download/details.aspx?id=48593) (1.8.6). so i am almost certain it will not work as there are dependencies on newer binaries that were shipped with VS 2015. 

I would recommend, first uninstalling all versions of TS on your machine, then install latest [Update 3](https://msdn.microsoft.com/en-us/library/mt752379.aspx) if you have not, or running a repair on Update 3 if you already have it.

**Comment by blubberbo** [comment]
I did that, but then there is no version of TS on the computer

**Comment by JanEggers** [comment]
i guess i have the same issue

Visual Studio 2015 update 3 updated Typescript from 1.8.* to 2.0.3 and now my ts is not transpiling and i get warnings about experimental decorators (but they are enabled in my tsconfig).

when i run tsc -v i get 2.0.3

but when i run tsc with a file that contains decorators i get a warning that i should enable them in tsconfig.

when i run tsc without options nothing happens

do you have any hint how i can diagnose why tsc is not picking up the tsconfig file?

**Comment by mhegazy** [comment]
@JanEggers can you share a project i can try with?

**Comment by JanEggers** [comment]
not that project but i have a playground solution with the same issue.

https://github.com/JanEggers/Playground

in 
https://github.com/JanEggers/Playground/blob/master/Playground.core/wwwroot/app/app.component.ts

i see the experimental decorator warning and it was fine with ts 1.8.4

**Comment by mhegazy** [comment]
@JanEggers, this looks like the issue in https://github.com/Microsoft/TypeScript/issues/10578. your tsconfig.json `include` clause really does not include anythign. so the file does not "belong" to the tsconfig.json, and hence the error.

changing the tsconfig.json to:

```ts
{
  ...
  "include": [
    "wwwroot/app/**/*"
  ],
  ...
}

```

solves the issues

**Comment by JanEggers** [comment]
thx its working again.

but why did it work with 1.8.4 and with 2.0 and a gulp task

for the next version i really would appreciate if you can  provide some diagnostic output option so anyone can figure this out more easy themselves.

i was really paranoid if the tsconfig got loaded at all as it was working fine with the last version

**Comment by blubberbo** [comment]
I deleted my user account on the server and created a new one and it is now working with TS 1.8
