### ISSUE TITLE
async/await not working on IE8 (IE9 in IE8 mode) in @next

### ISSUE THREAD

**Issue by sanex3339** [Microsoft/TypeScript#11280]
**TypeScript Version:**  nightly (2.1.0-dev.20160929)

**Code**

```ts
console.log(1); // ok
(async function () {
    console.log(2); // not showing, no errors, just empty log

    await new JQueryExistCondition().check();

    new Foo().init();
})();
```

**Expected behavior:**
Async functions should work on IE8 (IE9 in IE8 mode)

**Actual behavior:** 
Async functions not working on IE8 (IE9 in IE8 mode). Code inside async function just doesn't execute.

Here was be one more problem with async/await - `.catch` and `.throw` inside helper, which are reserved words in `ie8`. I replacing it on `['catch']` and `['throw']`, so it is not a problem for current issue.

**Comment by mhegazy** [comment]
@rbuckton maybe we should just do the ES3 transform and quote all identifiers with reserved words.

**Comment by rbuckton** [comment]
@mhegazy While we should definitely do this, the problem is in the `__awaiter` helper which is raw text rather than an AST. I can fix this by modifying the `__awaiter` helper for now.
