### ISSUE TITLE
Octal literals for enum members treated as decimal

### ISSUE THREAD

**Issue by lucaswerkmeister** [Microsoft/TypeScript#11298]
**TypeScript Version:**  2.0.3

**Code**

``` ts
enum X { A = 010 }
console.log(X.A === 010);
```

**Expected behavior:**

Prints `true` – `010` is an octal literal, both inside and outside an enum declaration.

**Actual behavior:** 

Prints `false`: In the enum declaration, `010` is understood as `10`. This is because `evalConstant` in `src/compiler/checker.ts` parses the expression with

``` ts
case SyntaxKind.NumericLiteral:
    return +(<NumericLiteral>e).text;
```

and while `+010` is 8, `+"010"` is 10.

It’s possible that this behavior is already being used by some to zero-pad enum literal values (though padding is probably more useful for hexadecimal literals), and so it might be a good idea to treat this as an undocumented feature instead of a bug, and to “fix” it by documenting this behavior in the language specification (under 9.2 Enum Members, in the **_constant enum members**_ definition).

This is similar to #10101, but I think it’s a different bug.

**Comment by DanielRosenwasser** [comment]
In the same spirit of my comment in #10101, I'm not even sure if we should allow octal literals in enums either.

**Comment by arusakov** [comment]
@DanielRosenwasser 
Do we disallow old style octal literals in enums? I can take it to work.

**Comment by mhegazy** [comment]
thanks @arusakov !
