### ISSUE TITLE
never return type not deduced automatically

### ISSUE THREAD

**Issue by nippur72** [Microsoft/TypeScript#11296]
**TypeScript Version:**  typescript@2.1.0-dev.20161001

**Code**

``` ts
function bar() {
   throw "";
}

function foo(a): number {  
   if(a==0) return -1;  
   else return bar();                  
}
```

**Expected behavior:**
no errors, TypeScript should deduce `bar` is of type `never`

**Actual behavior:** 

```
error TS2322: Type 'void' is not assignable to type 'number'.
```

Of course it works if I change to:

``` ts
function bar(): never {
   throw "";
}
...
```

**Comment by nippur72** [comment]
in other words
```ts
function bar() {
   throw "";
}
```
is marked as type `void` but IMO it should be `never`. Does it make sense?

**Comment by DanielRosenwasser** [comment]
The type of `bar` should indeed be `never` in principle - I wonder if there was a specific reason we didn't change that.

**Comment by mhegazy** [comment]
consider this:

```ts
class Base { 
    doWork() { 
        throw new Error("Must override");
    }
}

class Derived extends Base { 
    doWork() { 
       // do work..
    }
}
```

if the return type of the function was `never` this `extend` relationship would fail. never inference happens automatically only in lambdas and function expressions. methods and functions have to be annotated explicitly.

**Comment by nippur72** [comment]
@mhegazy thanks for the clarification
