### ISSUE TITLE
MutationObserver API declarations missing

### ISSUE THREAD

**Issue by AvraamMavridis** [Microsoft/TypeScript#11305]
The [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) related declarations are missing from the `lib.d.ts` file.  Since this API is not browser specific I would expect the declarations to exist (as it happens with FileReader for example).

**TypeScript Version:**  2.0.3

**Code**

``` ts
if( window && window.MutationObserver  )
{
   ...
}

```

**Expected behavior:**

To not arise an error.

**Actual behavior:** 

Error  : Property `MutationObserver` does not exist on type `Window`

I "solved" it by using the `window["MutationObserver"]` syntax. If that is an actual bug/issue I can provide a PR.

**Comment by aluanhaddad** [comment]
I'm almost positive that the proposal for mutation observers was dropped from ECMAScript. I don't have a reference handy but I believe that's the case

**Comment by AvraamMavridis** [comment]
@aluanhaddad This has nothing to do with `Object.observe` or ECMAScript. It is part of the window object, same as[ FileReader or Geolocation](https://github.com/Microsoft/TypeScript/blob/master/lib/lib.d.ts#L7942-L7949) that are not part of ECMAScript but they are supported by Typescript.

**Comment by aluanhaddad** [comment]
@AvraamMavridis thanks for correcting me.

**Comment by kitsonk** [comment]
@AvraamMavridis changes to the DOM part of the `lib.d.ts` come via [TSJS-lib-generator](https://github.com/Microsoft/TSJS-lib-generator).

They do appear to be declared though in the global interfaces and all the examples on [MDN](https://developer.mozilla.org/en/docs/Web/API/MutationObserver) demonstrate it that way.

So your detection might be better if you just did something like this:

```typescript
if (window && MutationObserver) {
  const mo = new MutationObserver();
}
```

You will find that they are properly typed that way.

**Comment by AvraamMavridis** [comment]
@kitsonk Thx a lot. I will give it a try later and if works I will close the issue.

**Comment by kpreisser** [comment]
Hi,

> ```typescript
> if (window && MutationObserver) {
>   const mo = new MutationObserver();
> }
> ```

note that this can throw a `ReferenceError` when running in strict mode and `MutationObserver` is not defined. I think you might need to use the typeof operator:
```typescript
if (window && typeof MutationObserver != "undefined") {
  const mo = new MutationObserver();
}
```

**Comment by AvraamMavridis** [comment]
@kpreisser what you described is "feature detection" and has nothing to do with Typescript and the issue above (missing declarations), and it will probably throw Error even in a non strict mode.

**Comment by kpreisser** [comment]
@AvraamMavridis,
> @kpreisser what you described is "feature detection" and has nothing to do with Typescript and the issue above (missing declarations)

That's correct. However in your original example, you used `if( window && window.MutationObserver)` to check for `window.MutationObserver`, which would not throw a `ReferenceError` when it is not defined (and running in strict mode) because you are accessing a property on the `window` object here.

But as @kitsonk noted, you should the global `MutationObserver` variable instead of `window.MutationObserver` because that one has declarations in TypeScript.
However to correctly feature-detect it, you can use `if (typeof MutationObserver != "undefined")` instead of `if (MutationServer)` so that no `ReferenceError` is thrown when running in strict mode. That's what I wanted to note.

**Comment by mhegazy** [comment]
thanks @kpreisser
