### ISSUE TITLE
Async/await missing in current documentation/handbook

### ISSUE THREAD

**Issue by jeromerg** [Microsoft/TypeScript#11302]
The online handbook is really fantastic. However I noticed it is missing a section concerning async/await functionality.

[https://www.typescriptlang.org/docs/tutorial.html](https://www.typescriptlang.org/docs/tutorial.html)

**Comment by DanielRosenwasser** [comment]
Thanks for reporting! Going to move this to the handbook repo.

**Comment by DanielRosenwasser** [comment]
This issue was moved to Microsoft/TypeScript-Handbook#400
