### ISSUE TITLE
Unable to extend classes which constructors require `new` when targeting es5

### ISSUE THREAD

**Issue by falsandtru** [microsoft/TypeScript#11304]
**TypeScript Version:**  master

**Code**

``` ts
new class extends Map {}();
```

**Expected behavior:**

```
$ node built/local/tsc.js -t es5 --lib es6 index.ts && node index.js
```

**Actual behavior:** 

```
$ node built/local/tsc.js -t es5 --lib es6 index.ts && node index.js
...\index.js:9
        return _super.apply(this, arguments) || this;
                      ^

TypeError: Constructor Map requires 'new'
```

**Comment by DanielRosenwasser** [comment]
I'll note that this doesn't work in 2.0 or in Babel either.

**Comment by falsandtru** [comment]
Hm, seems like there is no way to fix this bug. I think, so `new.target` is added in es6.

**Comment by DanielRosenwasser** [comment]
I think `super` calls could potentially be emitted as 

```
new (Function.prototype.bind.apply(_super, [null].concat(arguments))) || this
```

but I don't know what sort of runtime implication that would have, and at that point we might as well make a helper function.

**Comment by falsandtru** [comment]
Then can you make `_this` as an instance of both base and derived classes for `instanceof` operator?

**Comment by centigrade-thomas-becker** [comment]
See also #10853 which is closed, even though the issue is not resolved.

**Comment by RyanCavanaugh** [comment]
This doesn't seem like an important scenario for modern JS development - folks can either target ES6, or use an alternate transpiler.
