### ISSUE TITLE
Compiler option to disallow assignment of any to a more narrow type

### ISSUE THREAD

**Issue by tcrognon** [Microsoft/TypeScript#11301]
This currently compiles with no errors:

``` ts
function deserialize(untrustedData: any): number {
    return untrustedData;
}
const myNum = deserialize('bad data');
```

If `any` can only be assigned to `any`, the compiler can assist in making sure untrusted data is properly type checked. So the example above would have to be changed to

``` ts
function deserialize(untrustedData: any): number {
    if (typeof untrustedData !== 'number') {
        throw new Error('Not a number.');
    }
    // control flow analysis narrows type to number
    return untrustedData;
}
const myNum = deserialize('bad data');
```

or

``` ts
function deserialize(untrustedData: any): number {
    // not recommended, but prevents this new option from being too draconion
    return <number>untrustedData;
}
const myNum = deserialize('bad data');
```

This is a simplified example, but reflects the frequent task of deserializing untrusted data to typed classes/interfaces where certain types are expected but should be checked.

More generally, it gives the developer confidence that a type really is a certain type in their code in a similar way that the non-nullable option does.

**Comment by yortus** [comment]
The motivation here looks very similar to #10715.

**Comment by caseyhoward** [comment]
This also works but shouldn't:
```js
const x: any = 'not a number';
const y: number = x;
```

**Comment by mhegazy** [comment]
Is this just [no-any](https://palantir.github.io/tslint/rules/no-any/) ?

**Comment by caseyhoward** [comment]
No, no-any disallows any's altogether. I want to be able to use `any` but I don't want it to be assignable to a variable with a concrete type.

**Comment by mhegazy** [comment]
humm.. so what do you do with that any? it has to go somewhere? you never return it from a function, nor send it to another... so only `console.log` would be allowed? would not it be better to use `{}` or `object` in this case?

**Comment by caseyhoward** [comment]
You have to validate it. If it's `any` there is a good chance it's some sort of input from the outside.

```js
function myPublicAddingFunction(x: any, y: any): number {
  if (typeof x === 'number' and typeof y === 'number') {
    // typescript now knows that x and y are numbers
    return x + y;
  } else {
    throw 'numbers only';
  }
}
```

**Comment by mhegazy** [comment]
u can replace that with `number | string | boolean | undefined | null | symbol | object`

**Comment by mhegazy** [comment]
or just `{} | null | undefined`

**Comment by caseyhoward** [comment]
Replace what? And how does it fix my issue?

**Comment by mhegazy** [comment]
replace `any` with `{} | null | undefined`, then use [no-any](https://palantir.github.io/tslint/rules/no-any/)  tslint rule. this will guarantee that there are no unsafe assignments to `any`.
