### ISSUE TITLE
no check return type

### ISSUE THREAD

**Issue by uxitten** [Microsoft/TypeScript#11319]
typescript version 2

this code (for example):

```
interface String{
    go(step: any): boolean;
}

String.prototype.go = function (step: any): boolean {
    return step;
}
```

function go return boolean type but no check return type

**Comment by aluanhaddad** [comment]
That is the correct behavior because `any` is assignable to any type.
```TypeScript
function go(step: any): boolean {
  return step;
}
```

**Comment by uxitten** [comment]
but i set boolean for return type 

ignore return type?

**Comment by aluanhaddad** [comment]
It is not ignoring the return type. The tricky part is that the static type `any` is the formal static type that represents the untyped (or dynamically typed if you prefer) nature of JavaScript declarations. That is `any` is assignable to _and_ from all other types.

If you write
```TypeScript
function go(step): boolean {
    return step;
}
```
the result is exactly the same. Where does it says that `step` is not a `boolean`. In other languages, the `any` type is often named `dynamic`.

**Comment by uxitten** [comment]
but when use this function (for example):

```
let travel: string = 'Ardebil';
let ok: boolean = travel.go(1990);
```

when run `travel.go(1990);` return number type
This is not wrong?

**Comment by aluanhaddad** [comment]
It is wrong in the sense that the declared type of `.go` is lying. Given what `.go` does, I would argue it should be declared as
```TypeScript
interface String{
    go<T>(step: T): T;
}
```

**Comment by aluanhaddad** [comment]
Tangentially, in the following code
```TypeScript
let travel: string = 'Ardebil';
let ok: boolean = travel.go(1990);
```
I would argue that the use of type annotations on the variable declarations is a bad practice. They have initializers and allowing the compiler to infer the type of the declaration from the initializer often provides a richer, more accurate, and stricter type.

**Comment by uxitten** [comment]
i tested this code

```
interface String{
    go<T>(step: T): boolean;
}
```

but ignore return value!

**Comment by aluanhaddad** [comment]
That is a type declaration, there is nothing to ignore. It is just stating that a `string` has a method `go` that takes a value of any type, because there is no constraint on `T`, and returns a `boolean`. It would help if we knew what `.go` was supposed to do.

**Comment by uxitten** [comment]
ignore  when function set void type for return 

```
function go(step:any): void {
    return step;
}
```

**Comment by aluanhaddad** [comment]
TypeScript does check return types it is simply that type `any` is compatible with everything. That is not the case with `void`.

**Comment by RyanCavanaugh** [comment]
@uxitten it seems like you're new to TypeScript -- StackOverflow and the TypeScript Documentation (especially the TypeScript Handbook) are the best place to go for learning. The issue tracker is for bugs only. Thanks!

**Comment by uxitten** [comment]
@RyanCavanaugh i am no beginner. just a question in your opinion no issue?
