### ISSUE TITLE
Can not declare protected methods without implementation in TS 2.0

### ISSUE THREAD

**Issue by Koloto** [Microsoft/TypeScript#11315]
Sometimes I use mixins to share some protected logic between several classes:

``` ts
class Mixin {
    protected doSomething(): void {
    }
}

class Base {
}

class Sample extends Base {
    run() {
        this.doSomething();
    }

    protected doSomething(): void; // error TS2391: Function implementation is missing or not immediately following the declaration.
}

// uncomment the following code to fix the complilation in v1.8 and earlier
//namespace Sample {
//}

// extend Sample.prototype from Mixin.prototype
```

The code above raises the error TS2391. But uncommenting `namespace Sample` after the class definition changed behavior: the compilation became successful before version 2.0. Maybe it was a bug or undocumented feature, I don't know. But it worked and I used it since early versions (about 1.3 or 1.4), including 1.8.10. This behavior changed in 2.0, now introducing the namespace don't fix compilation:(

I can declare mixining method as a property:

``` ts
class Sample extends Base {
    protected doSomething: () => void;
}
```

But in this case I can't override this method later:

``` ts
class Child extends Sample {
    protected doSomething(): void { // error TS2425: Class 'Sample' defines instance member property 'doSomething', but extended class 'Child' defines it as instance member function.
        super.doSomething(); //  error TS2340: Only public and protected methods of the base class are accessible via the 'super' keyword.
    }
}
```

Also this way is inconvenient and confusing.

If method `doSomething` would be public, I can declare it in `interface Sample` and TypeScript merge it with the class. But this trick does not work with protected methods.

I tried to mark the method as optional (although it is mandatory in fact):

``` ts
    protected doSomething?(): void;
```

But now compilation with `--strictNullChecks` throws an error `error TS2532: Object is possibly 'undefined'`.

The only workaround that I found is to add a fake implementation to the method:

``` ts
    protected doSomething(): void { }
```

But this generates redundant JavaScript and misleads code reviewers. Unacceptable:( So this is real blocker for me to update to version 2.0.

Adding a namespace with the same name was not clean of course. The solution would be to allow using `declare` inside a class body:

``` ts
class Sample extends Base {
    run() {
        this.doSomething();
    }

    declare protected doSomething(): void;
}
```

 I suppose it is not so difficult to implement this.

P.S. Sorry for my English:(

**Comment by aluanhaddad** [comment]
> I can declare mixining method as a property:
>...
> But in this case I can't override this method later:

You can override it be assigning to it in the derived class, but it does change it from a method to a property which may not be desirable.

This does not work because only derived classes have access to protected members. `Sample` does not derive from `Mixin` and if it did, it could not derive from `Base`.
I believe the pattern you want to follow is detailed here https://www.typescriptlang.org/docs/handbook/mixins.html

**Comment by Koloto** [comment]
@aluanhaddad: The example from the handbook uses public methods. I am trying to do the same but with protected methods. By the way that example does not allow overriding mixed-in methods in inherited classes too.

**Comment by Koloto** [comment]
@mhegazy, @DanielRosenwasser, @ahejlsberg or anybody else from TypeScript team, could you comment please?

**Comment by RyanCavanaugh** [comment]
This is working as intended. It's was never intended to be allowed to declare a method without an implementation in a non-ambient class.

**Comment by Koloto** [comment]
Maybe this was not intended, but this worked before 2.0 (if you add a namespace with the same name). I think this is the useful feature (not only for me). So why don't allow it? Via `declare` inside a class as I suggested above of somehow else. Don't you agree?

**Comment by evil-shrike** [comment]
Hi.
The solution with protected methods in a mixin and empty methods worked fine for us. I can't see why do you consider it as a bug (anyway it's a breaking change not mentioned anywhere in release notes). 
Even if it's working as indended now we still need an ability to share protected/private logic between classes. How do you suggest doing this now?
These empty methods are kind of an interface of a class for itself. So actually it's an implementation of multiple inheritence. Where `extends` is used for outer contract and mixin injecting for inner contract.

**Comment by evil-shrike** [comment]
Hi.
Is these any news on issue? 
We're stuck at 1.8 because of our codebase is breaking with 2.0 as we were broadly using that "mixin" feature.

**Comment by mhegazy** [comment]
My recomendation is to use interface/class merging to get this working.

```ts
class Mixin {
    protected doSomething(): void {
    }
}

class Base {
}

interface Sample {
    doSomething(): void; // no implementation needed
}

class Sample extends Base {
    run() {
        this.doSomething();
    }
}

(new Sample()).doSomething();
```

**Comment by evil-shrike** [comment]
@mhegazy thank you! we'll give it a try.

**Comment by Koloto** [comment]
@mhegazy Your solution makes mixin methods public, not protected.

**Comment by mhegazy** [comment]
Can you explain the scenario you are trying to achieve then?

**Comment by evil-shrike** [comment]
@mhegazy 
Here're 3 classes: PartWithFilterMixin - common methods for working with a "filter", they are mixed into ObjectList and ObjectTree. ObjectList and ObjectTree cannot inherit from PartWithFilterMixin because they have their own hierarchies.

PartWithFilterMixin.ts:
```ts
abstract class PartWithFilterMixin  {
    protected filter: IFilterPart;
    protected initFilter(options: PartWithFilterMixinOptions): void { /* init this.filter */ }
    protected getFilterRestrictions(): any { /* collecting filter restrictions */}
}
declare namespace PartWithFilterMixin {
	export interface PartWithFilterMixinOptions { }
}
export = PartWithFilterMixin;
```
ObjectList.ts:
```ts
import PartWithFilterMixin = require("PartWithFilterMixin");
class ObjectList extends List<DomainObject> {
    /* ObjectList's own logic */
    public load() {
        let args = this.getFilterRestrictions(); ...
    }

    // PartWithFilterMixin: begin
    protected initFilter(options: PartWithFilterMixin.PartWithFilterMixinOptions): void;
    protected getFilterRestrictions(): any;
    // PartWithFilterMixin: end
}
ObjectList.mixin(PartWithFilterMixin);
namespace ObjectList {
    export interface Options extends List.Options, PartWithFilterMixin.PartWithFilterMixinOptions {}
}
export = ObjectList;
```

ObjectTree.ts:
```ts
import PartWithFilterMixin = require("PartWithFilterMixin");
class ObjectTree extends Tree {
    /* ObjectTree's own logic */
    public load() {
        let args = this.getFilterRestrictions(); ...
    }

    // PartWithFilterMixin: begin
    protected initFilter(options: PartWithFilterMixin.PartWithFilterMixinOptions): void;
    protected getFilterRestrictions(): any;
    // PartWithFilterMixin: end
}
ObjectTree.mixin(PartWithFilterMixin);
namespace ObjectTree {
    export interface Options extends Tree.Options, PartWithFilterMixin.PartWithFilterMixinOptions { }
}
```

`mixin` is our static method in the very base class which copies method between prototypes.

ObjectList and ObjectTree know that they have a filter, but they don't contain implementation for working with it, only contract (for themselves). 
It is (was!) a pretty handy method to share private/protected methods among classes.

Hope it makes sense for you. Please let us know if it's still unclear.

//cc @Koloto

**Comment by mhegazy** [comment]
A quick note about adding members to a class outside the main class declaration for posterity. you have multiple options,

#### Optional methods:

this to say that the member may or may not be there, a user would have to check for the member existance before using it under `--strictNullChecks`. e.g.:

```ts
class ObjectList extends List<DomainObject> {
     protected initFilter?(options: PartWithFilterMixin.PartWithFilterMixinOptions): void;
     protected filter?: IFilterPart;
}

// later on:
if (condition) {
    ObjectList.prototype.initFilter = funciton(...) {}
}
```

#### Interface/class declaration merging

A simple way to visualize this, is you can declare additional members on a class without impementing them. 

```ts
interface ObjectList { 
    filter: IFilterPart;
    getFilterRestrictions():
}

class ObjectList extends List<DomainObject> {
    public load() {
    }
}

(new ObjectList()).load();
(new ObjectList()).filter;
(new ObjectList()).getFilterRestrictions();
```

In the example above you wanted to "inherit" the properties of another class, and not define new ones, since `private` and `protected` members can only be inherited to be considered equivalent.

For that, you can just use `extends` on the interface, since `interfaces` can extend `classes`:

```ts
interface ObjectList extends PartWithFilterMixin { 
}

class ObjectList extends List<DomainObject> {
    public load() {
        this.load(); // local
        this.filter; // inherited from PartWithFilterMixin
        this.getFilterRestrictions(); // inherited from PartWithFilterMixin
    }
}

(new ObjectList()).load(); // only load available here since the others are protected
```

#### Using intersection

The  other option is to use intersection types to represent the result of a mixing operations, e.g.:

```ts
function getObjectListWithFilter(): ObjectList & PartWithFilterMixin { 
    return extend(new ObjectList(), PartWithFilterMixin);
}
```

where, extend would be a routine that copies helpers from `PartWithFilterMixin` onto your new object instance at runtime.


hope that helps.

**Comment by Koloto** [comment]
@mhegazy Your second solution works like a charm! Thank you very much.
Could you explain a bit. Do I understand right that an interface can also have the inherited protected members if it extends a class? I am about this:
```ts
interface ObjectList extends PartWithFilterMixin { 
}
```
We can't explicitly declare any protected members in the interface. But we can do it implicitly by extending a class. Is this a feature?

**Comment by Koloto** [comment]
@mhegazy I was too optimistic when said "works like a charm":)
Actually all our components inherit from the class `Part` which has protected method `doRender`. If this method is overridden somethere in class hierarchy then suggested solution doesn't work:( Working demo:
```ts
class Part {
    renderStatus: "unloaded" | "ready";

    render(): void {
        this.doRender();
        this.renderStatus = "ready";
    }

    // "virtual" method to override
    protected doRender(): void { }
}

// This class is never instantiated but is also inherits from Part
// to have access to its members in compile-time
class PartWithFilterMixin extends Part {
    protected getFilterRestrictions(): any {
        if (this.renderStatus !== "ready") {
            return null;
        }
        return {};
    }
}

class List extends Part {
    protected doRender(): void {
        super.doRender();
        // something else
    }
}

class ObjectList extends List {
    public load() {
        this.getFilterRestrictions(); // inherited from PartWithFilterMixin
    }
}

// Error:
// Interface 'ObjectList' cannot simultaneously extend types 'List' and 'PartWithFilterMixin'.
// Named property 'doRender' of types 'List' and 'PartWithFilterMixin' are not identical.
interface ObjectList extends PartWithFilterMixin {
}
```
There is a compile error in this scenario, you can see it at the end of the example.

**Comment by mhegazy** [comment]
in cases of conflicting declarations, you will have to redefine them in the interface. doing so changing the visibility to `public` though. do not think there is a way around this.

> Do I understand right that an interface can also have the inherited protected members if it extends a class?

yes, the interface inherits all the members from the class. `protected` and `private` members can only be declared in a class though. so this is the only way an interface can get a `protected` or a `private` member.

**Comment by Koloto** [comment]
@mhegazy Thank you very much for your help. We achieved the desired result.
