### ISSUE TITLE
Properties retrieved via destructuring do not mark that property as being used

### ISSUE THREAD

**Issue by tomdale** [Microsoft/TypeScript#11324]
**TypeScript Version:**  2.1.0-dev.20161003

**Code**

``` ts
class Animal {
  constructor(private species: string) {
  }

  printSpecies() {
    let { species } = this;
    console.log(species);
  }
}
```

**Expected behavior:**
If I have the `noUnusedLocals` option enabled, the code should compile without warnings because the `species` property is being used.

**Actual behavior:** 
If I have the `noUnusedLocals` option enabled, I receive:

```
src/index.ts(2,23): error TS6138: Property 'species' is declared but never used.
```

**Comment by grovesNL** [comment]
@sheetalkamat: Is this the same issue as the following:

```
class Test {
    private example: number = 1.0; // 'example' is declared but never used
    private constructor() {
        const { example } = this;
        console.warn(example);
    }
}
```

I hit this in 2.1.1 so I'm not sure if it's a different case.

**Comment by sheetalkamat** [comment]
@grovesNL I do not see error being reported when I used TypeScript@next

**Comment by loliver** [comment]
I'm seeing what I believe is this issue in the following class constructor:

```typescript
static $inject = ['$window', '$location'];

private productCode: string;
private sourceCode: string;

private productData: any;

constructor(private $window: ng.IWindowService,
            private $location: ng.ILocationService) {
  this.productCode = $location.search().apptype;
  this.sourceCode = $location.search().sourcecode_1;
  this.productData = this.getProductData();
}
```

It is happening for $location if I use it to set properties directly in the constructor but if I create a function to do it then call that in the constructor it's fine eg:

```typescript
static $inject = ['$window', '$location'];

private productCode: string;
private sourceCode: string;

private productData: any;

constructor(private $window: ng.IWindowService,
            private $location: ng.ILocationService) {
  this.setProductCodes();
  this.productData = this.getProductData();
}

private setProductCodes() {
  this.productCode = this.$location.search().apptype;
  this.sourceCode = this.$location.search().sourcecode_1;
}
```

I'm moving forward with the second set of code as it's better practice anyway but thought this may help people who find this issue on Google.

**Comment by andy-ms** [comment]
Hi @loliver, in the first example you don't seem to ever access `this.$location`. In the second example you do (although you don't need to; you could pass `location` as a property to `setProductCodes` to avoid storing it on the object.)
