### ISSUE TITLE
Custom Typings - How To

### ISSUE THREAD

**Issue by MCKRUZ** [Microsoft/TypeScript#11329]
Can someone please once and for all post how to do custom typings in Typescript 2.0+.  I have seen multiple answers all over stackoverflow and other sites all of which are wrong.  Can someone from the team please let me know what the deal is?

**Comment by mhegazy** [comment]
What do you mean by "Custom Typings"? what are you looking for specifically?

**Comment by MCKRUZ** [comment]
meaning that if I create a NPM library that isn't hosted in NPM but rather a private repo.

**Comment by MCKRUZ** [comment]
so it doesn't appear in the typings folder

**Comment by mhegazy** [comment]
is it a module?

**Comment by MCKRUZ** [comment]
Yes it is

**Comment by mhegazy** [comment]
so let's say you have your declaration file for the module in `@private\module\index.d.ts`. You can add a `path` mapping for it.

```json
{
    "compilerOptions": {
        "baseUrl": "./",
        "paths":{
            "@private/*": ["types/@private/*"]
        }
    }
}
```

would this work?

**Comment by mhegazy** [comment]
The ideal case would be the use of `typeRoots` to inject the additional directory. but this needs https://github.com/Microsoft/TypeScript/issues/11137 to be fixed first.

**Comment by towertop** [comment]
@mhegazy

So what the "paths" options is designed for? That confuses me.

**Comment by mhegazy** [comment]
> So what the "paths" options is designed for? That confuses me.

what are you trying to do?

**Comment by DanielRosenwasser** [comment]
@towertop The `paths` field is useful to align TypeScript's module resolution process with that of your module loader (e.g. AMD, System.js), or for adding custom declarations that exist outside of the standard resolution locations.

**Comment by weswigham** [comment]
Alternatively: Since your packages are private, write your own private [@types/module-name package](https://github.com/weswigham/AtTypes-vega), then [point npm at it via your package.json](https://github.com/glimpseio/glacier/blob/master/glacier/src/package.json).

Its higher effort, but, IMO, a much neater solution than managing mappings within your tsconfig.

**Comment by towertop** [comment]
Thanks @DanielRosenwasser , I got it.

@mhegazy I was confused which is preferred when "typeRoots" and "paths" both help to patch declarations for external module.
