### ISSUE TITLE
Asynchronous Iterations

### ISSUE THREAD

**Issue by ivogabe** [Microsoft/TypeScript#11326]
The [asynchronous iterations](https://github.com/tc39/proposal-async-iteration) proposal is now in stage 3, so it should be safe to support that in TypeScript now. Currently, a function may be a generator or an async function, but it cannot be both. The asynchronous iteration proposal removes this restriction. Here's an example from their readme:

``` javascript
async function* readLines(path) {
  let file = await fileOpen(path);

  try {
    while (!file.EOF) {
      yield await file.readLine();
    }
  } finally {
    await file.close();
  }
}
```
## Types

Generator functions declare several interfaces:

``` typescript
interface IteratorResult<T> {
    done: boolean;
    value: T;
}
interface Iterator<T> {
    next(value?: any): IteratorResult<T>;
    return?(value?: any): IteratorResult<T>;
    throw?(e?: any): IteratorResult<T>;
}
interface Iterable<T> {
    [Symbol.iterator](): Iterator<T>;
}
interface IterableIterator<T> extends Iterator<T> {
    [Symbol.iterator](): IterableIterator<T>;
}
```

Async generators return promises instead of their `IteratorResult`, and use a new symbol, `Symbol.asyncIterator`:

``` typescript
interface IteratorResult<T> {
    done: boolean;
    value: T;
}
interface AsyncIterator<T> {
    next(value?: any): Promise<IteratorResult<T>>;
    return?(value?: any): Promise<IteratorResult<T>>;
    throw?(e?: any): Promise<IteratorResult<T>>;
}
interface AsyncIterable<T> {
    [Symbol.asyncIterator](): AsyncIterator<T>;
}
interface AsyncIterableIterator<T> extends AsyncIterator<T> {
    [Symbol.asyncIterator](): AsyncIterableIterator<T>;
}
```
## Emit

I guess that this would require another helper function to downlevel to ES2015, similar to the one used for async functions. Yield and await expression would both be replaced by yield expression, so they need to be decorated with some tag, like `yield ['await', promise]` for `await promise`.
## for-await-of

The proposal also introduces a new loop. An example from their readme:

``` javascript
for await (const line of readLines(filePath)) {
  console.log(line);
}
```

This iterates over the `[Symbol.asyncIterator]()` object and awaits the value of `.next()`, similar to a for-of loop. This loop can only be used in async functions.

**Comment by appsforartists** [comment]
FWIW, TypeScript currently [emits garbage](https://www.typescriptlang.org/play/index.html#src=async%20function%20streamingRead()%20%7B%0D%0A%20%20const%20response%20%3D%20await%20fetch('https%3A%2F%2Fhtml.spec.whatwg.org')%3B%0D%0A%20%20const%20reader%20%3D%20response.body.getReader()%3B%0D%0A%20%20%0D%0A%20%20for%20await%20(const%20value%20of%20reader)%20%7B%0D%0A%20%20%20%20console.log(%60Read%20%24%7Bvalue.length%7D%20bytes%60)%3B%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0A%2F%2F%20polyfill%20for%20readable%20streams%20to%20be%20async%20iterables%0D%0Anew%20ReadableStream().getReader().constructor.prototype%5BSymbol.asyncIterator%5D%20%3D%20async%20function*%20readLines(path)%20%7B%0D%0A%20%20while%20(true)%20%7B%0D%0A%20%20%20%20const%20%7Bdone%2C%20value%7D%20%3D%20await%20this.read()%3B%0D%0A%20%20%20%20if%20(done)%20return%3B%0D%0A%20%20%20%20yield%20value%3B%0D%0A%20%20%7D%0D%0A%7D%3B%0D%0A%0D%0AstreamingRead()%3B) if you try to `for await`.  Same code [works in Babel](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2017%2Cstage-0&code=async%20function%20streamingRead()%20%7B%0A%20%20const%20response%20%3D%20await%20fetch('https%3A%2F%2Fhtml.spec.whatwg.org')%3B%0A%20%20const%20reader%20%3D%20response.body.getReader()%3B%0A%20%20%0A%20%20for%20await%20(const%20value%20of%20reader)%20%7B%0A%20%20%20%20console.log(%60Read%20%24%7Bvalue.length%7D%20bytes%60)%3B%0A%20%20%7D%0A%7D%0A%0A%2F%2F%20polyfill%20for%20readable%20streams%20to%20be%20async%20iterables%0Anew%20ReadableStream().getReader().constructor.prototype%5BSymbol.asyncIterator%5D%20%3D%20async%20function*%20readLines(path)%20%7B%0A%20%20while%20(true)%20%7B%0A%20%20%20%20const%20%7Bdone%2C%20value%7D%20%3D%20await%20this.read()%3B%0A%20%20%20%20if%20(done)%20return%3B%0A%20%20%20%20yield%20value%3B%0A%20%20%7D%0A%7D%3B%0A%0AstreamingRead()%3B&experimental=true&loose=false&spec=false)

I'd expect it to throw an error until async iteration is properly supported.

**Comment by mhegazy** [comment]
> I'd expect it to throw an error until async iteration is properly supported.

it does.

![animation](https://cloud.githubusercontent.com/assets/8000722/20279206/72ede3ea-aa5c-11e6-9868-670628362bd4.gif)

**Comment by imetallica** [comment]
One suggestion I think can make the asynchronous workflows easier to read: 

- instead of using `await`, we could do as F# does and use `let!`, `yield!` and `do!`.
Put the `async{}` inside instead of outside the function.

For example

```
function* readLines(path) {
  async{
    let! file = fileOpen(path);

    try {
      while (!file.EOF) {
        yield! file.readLine();
      }
    } finally {
      do! file.close(); // Or something else as identifier.
    }
  }
}
```

**Comment by ErikCupal** [comment]
@imetallica Eeh, no I don't think it's a good idea.

The main goal of Typescript is to provide type safety and analysis for JS. Therefore, it shouldn't deviate from ECMAScript standard if it is possible.
