### ISSUE TITLE
Integration with VS extensions gallery is a mess.

### ISSUE THREAD

**Issue by Jestar342** [microsoft/TypeScript#11327]
![image](https://cloud.githubusercontent.com/assets/457158/19048857/ea5fdb32-899f-11e6-84b1-57d94d590771.png)

That's really confusing.

**Comment by mhegazy** [comment]
just to be clear. Are the icons the source of confusion?

**Comment by Jestar342** [comment]
No. That there are pages of entries for Typescript is the source of confusion. There should be one entry, and it should be the latest stable version - perhaps a second for beta is understandable. Not a new entry for each and every version.

**Comment by RyanCavanaugh** [comment]
We don't control the ordering or search results for this dialog, unfortuntely

**Comment by Jestar342** [comment]
You do control the identity and publication of the extension though, surely? The confusion isn't the ordering, nor it is the icons, it is that there are multiple (and very many) "extensions" appearing for TypeScript, when the only difference between them is version. There should be just one extension in the gallery, which is always the latest stable version of TypeScript - I concur with the idea of a different extension for Beta. This would then also permit auto-update notifications in the VS notifications window when new releases are made.

**Comment by RyanCavanaugh** [comment]
We're not going to revoke the previous versions for the sake of these search results -- people may need the prior versions for compatibility or other reasons.

**Comment by Jestar342** [comment]
VS extensions gallery caters for previous versions. I'm not suggesting you remove them completely, I'm only asking that you do what ever other extension throughout the gallery does.
