### ISSUE TITLE
Intellisense for string literals

### ISSUE THREAD

**Issue by normalser** [Microsoft/TypeScript#11331]
There is merged PR that handles some cases: https://github.com/Microsoft/TypeScript/pull/8428

but it does not handle this case:

``` ts
interface Test {
    a: "A" | "B" | "C"
}

const test:Test = {
    a: "  // <- Intellisense shows: 'a' instead of A | B | C
}
```

**Comment by wallverb** [comment]
Looks like its working in the latest
