### ISSUE TITLE
Hover could be more readable in this case

### ISSUE THREAD

**Issue by waderyan** [Microsoft/TypeScript#11335]
_From @isidorn on September 30, 2016 10:17_
1. Open debugService.ts
2. Hover over constructor
3. I think the hover could somehow be more readable, all these constructor arguments one after the other are not helping - could we colorize better?

![screen shot 2016-09-30 at 12 15 50](https://cloud.githubusercontent.com/assets/1926584/18988596/b78518ca-8707-11e6-882e-cb6e8d35b4d9.png)

_Copied from original issue: Microsoft/vscode#13070_

**Comment by waderyan** [comment]
_From @joaomoreno on September 30, 2016 10:20_

Both content and colorization comes from Typescript.

**Comment by waderyan** [comment]
This is closely related to #11415. Migrating this to TS as there is an API dependence with them.

**Comment by mhegazy** [comment]
@dbaeumer how do you want to handle this? we do have the display parts in https://github.com/Microsoft/TypeScript/blob/4fbbbed321baa58418b9379b418278d31400fe3e/lib/typescript.d.ts#L2607. we can expose them to the protocol.

**Comment by dbaeumer** [comment]
@mhegazy exposing them through the protocol makes sense to me. Then we can improve the rendering on our end.

**Comment by waderyan** [comment]
Another issue seeing this - https://github.com/Microsoft/vscode/issues/16115#event-873293954

**Comment by luisrudge** [comment]
Thanks for routing @waderyan

Here's what I'm seeing:

![image](https://cloud.githubusercontent.com/assets/941075/20685117/3950d9dc-b59a-11e6-925d-52b384047d70.png)

**Comment by RyanCavanaugh** [comment]
Please open a new issue if you need anything in this area; seems this one has been stale for > 1 year
