### ISSUE TITLE
compiler doesn't find class properties?

### ISSUE THREAD

**Issue by gertcuykens** [Microsoft/TypeScript#11337]
```ts
class G {
    greeting: string
    constructor(message: string) {
        G.greeting = message;
    }
    greet() {
        console.log("Hello, " + G.greeting;)
    }
}
var greeter = new G("world");
var button = document.createElement('button');
button.textContent = "Say Hello";
button.onclick = greeter.greet
document.body.appendChild(button);
```
Compiler doesn't like G.greeting?
Note that this works in ES6

![image](https://cloud.githubusercontent.com/assets/863731/19057956/fa1a7bb6-89d3-11e6-8cd0-636698af5d0d.png)

![image](https://cloud.githubusercontent.com/assets/863731/19057933/cde49dec-89d3-11e6-86c9-56cf7404e1d7.png)

**Comment by vladima** [comment]
do you mean `this.greeting`? `G.greeting` will be used if you want to refer to static property

**Comment by zhengbli** [comment]
Or in your second like make it `static greeting: string` instead.

**Comment by gertcuykens** [comment]
To avoid binding to the wrong this on `button.onclick = greeter.greet` I use G.

`static greeting: string` works thanks. PS I don't know for sure if this would produce the same effect as in ES6?

**Comment by RyanCavanaugh** [comment]
Don't make classes that only work when there's one instance...

**Comment by RyanCavanaugh** [comment]
Here's some code that works:
```ts
class G {
    greeting: string
    constructor(message: string) {
        this.greeting = message;
    }
    greet = () => {
        console.log("Hello, " + this.greeting);
    }
}
```
Please take future questions to StackOverflow. Thanks!

**Comment by gertcuykens** [comment]
Ok thanks, my bad I can clearly see now it's not the compiler
