### ISSUE TITLE
Duplicate identifier errors when using @types inside a Windows junction

### ISSUE THREAD

**Issue by smrq** [Microsoft/TypeScript#11333]
**TypeScript Version:**  2.0.3

**Code**
- Install any type declaration from `@types` on npm.  (For this example I am using `@types/react`, but this is also reproducible with other declaration files: `@types/angular`, `@types/jquery`, `@types/lodash`, etc.)
- Create a junction to the source folder.
- Then, navigate into the junction (instead of the real folder).
- Attempt to compile the following file:

``` ts
import * as React from 'react';
```

A minimal reproducing repo with complete steps to reproduce is available here: https://github.com/smrq/tsc-junction-repro

**Expected behavior:**

Compiles without errors.

**Actual behavior:** 

Compiles with the following errors:

``` sh
C:/Code/tsc-junction-repro/node_modules/@types/react/index.d.ts(7,21): error TS2300: Duplicate identifier 'React'.
node_modules/@types/react/index.d.ts(7,21): error TS2300: Duplicate identifier 'React'.
```

**Comment by zkochan** [comment]
It would be really great if this was fixed.

As a consequence of this issue [pnpm](https://github.com/rstacruz/pnpm) cannot currently be used for projects that use typescript@2 ([related issue on pnpm](https://github.com/rstacruz/pnpm/issues/404)). 

pnpm is probably the only package manager written in TypeScript, so please help us with this :wink:

**Comment by sompylasar** [comment]
Looks relevant to this: https://github.com/Microsoft/TypeScript/issues/6496
