### ISSUE TITLE
Question about never type and union types

### ISSUE THREAD

**Issue by remojansen** [Microsoft/TypeScript#11344]
So I've been trying to play with the new `never` type. 

I tried the following:

```ts
// Simulates some side effect
function serverSideTimeOut(): boolean {
    let luck = Math.floor(Math.random() * 10) + 1;
    return (luck % 5 === 0)
}

interface User {
    name: string;
}

type Maybe<T> = never | T;

function fetchUsers(): Maybe<User[]> { 
    if(serverSideTimeOut() === false) {
        return [
            { name: "User1" },
            { name: "User2" }
        ];
    }
}

var maybeUsers = fetchUsers(); // why is maybeUsers is inferred as User[] ?
maybeUsers.forEach((user) => { console.log(name); }); // No Error!!!
```

I'm creating this issue because I was expecting the last line to throw a compilation error. The type of `maybeUsers` should be `Maybe<User[]>` but it is inferred as `User[]` can someone explain me why it behaves like that?

Thanks a lot!

**Comment by gcnew** [comment]
> Because never is a subtype of every type, it is always omitted from union types and it is ignored in function return type inference as long as there are other types being returned.

See [What's new - The never type](https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#the-never-type)

**Comment by RyanCavanaugh** [comment]
You probably want `undefined | T` with the `strictNullChecks` flag on

**Comment by remojansen** [comment]
Thanks a lot for your help guys. I was going in that direction :smile: here is working sample in case it may help someone else:

```ts
// Simulates some side effect
function serverSideTimeOut(): boolean {
    let luck = Math.floor(Math.random() * 10) + 1;
    return (luck % 5 === 0)
}

interface User {
    name: string;
}

type Maybe<T> = undefined | T;

function fetchUsers(): Maybe<User[]> { 
    if(serverSideTimeOut() === false) {
        return [
            { name: "User1" },
            { name: "User2" }
        ];
    }
}

var maybeUsers = fetchUsers();

//  Error: Object is possibly 'undefined' (using --strictNullChecks)
maybeUsers.forEach((user: User) => { console.log(name); }); 
```
