### ISSUE TITLE
Could the tsserver add process.noAsar = true;

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#11348]
**TypeScript Version:**  2.0.3

VS Code uses Electron as a Node.js runtime to execute the tsserver. Electron comes with built-in ASAR (zip) support which makes ASARs look like directories and files to the normal fs functions. The downside is that if code traverses into an ASAR Electron puts a file lock onto the ASAR file which has bad consequences when you want to delete/move folders containing open ASARs

We have opened a PR against Electron that will allow us to disable ASAR support from the outside. Until that is merged in and picked up by us could the tsserver contain the following line early in its startup code:
```
process.noAsar = true;
```
This will disable ASAR support which is not needed by the tsserver anyways.

**Comment by dbaeumer** [comment]
@mhegazy could we look into this for 2.0.5 ?

**Comment by bpasero** [comment]
Related electron docs: https://github.com/electron/electron/blob/master/docs/api/process.md#processnoasar

**Comment by RyanCavanaugh** [comment]
Seems reasonable. Do you guys want to send a PR?

**Comment by dbaeumer** [comment]
I can provide a PR.

**Comment by dbaeumer** [comment]
Here you go: https://github.com/Microsoft/TypeScript/pull/11351

**Comment by dbaeumer** [comment]
Thanks !
