### ISSUE TITLE
import foo = require(...) should not be considered deprecated in the spec

### ISSUE THREAD

**Issue by basarat** [microsoft/TypeScript#11340]
Reading the official spec : https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#1133-import-require-declarations 

It says : 

> exist for backward compatibility with earlier versions of TypeScript

However for a vast number of npm modules out there that do `export = someFunction` there is no ES6 syntax that TypeScript approves of i.e `import * as someFunction from "someFunction"` will complain that it resolves to a non module entity. 
# Suggestion:

Either of these would be fine: 
-  `import`/`require` should not be marked as deprecated as there is no alternative
- `import * as someFunction from "someFunction"` should be allowed. 

Workaround : people (and I) have been doing `module someFunction{}` to quieten the compiler and then `import * as` works. I am probably wrong but would like an official way forward.

/cc @blakeembrey :rose:

**Comment by HerringtonDarkholme** [comment]
For short term I think the first option is a fairly easy solution.

But I'm very worried about long term compatibility between TS, commonjs and ESModule. Namely, should allow `import DefaultExport from "some-module"` when it is declared `declare module "some-module" { export = ... }`

Related issues and proposals:

https://github.com/Microsoft/TypeScript/issues/9562

https://github.com/nodejs/node-eps/issues/26

https://github.com/nodejs/node-eps/blob/master/002-es6-modules.md#54-es-consuming-commonjs

After reading these issues I think a new compiler flag that do the type checking for synthetic import and code generation as well.

**Comment by DanielRosenwasser** [comment]
Hard link: https://github.com/Microsoft/TypeScript/blob/4b96edf72faf6f9b6b464e148c9c02eac96aa4bd/doc/spec.md#1133-import-require-declarations

Also see #16093

**Comment by RyanCavanaugh** [comment]
The spec is now an "archived" artifact and we won't be tracking defects against it anymore.
