### ISSUE TITLE
Some ES6 constructs force an implicit 'strict' context within them.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [Microsoft/TypeScript#1135]
For example, inside the body of a class, you are implicitly in strict mode.  Implementing this will be a breaking change for existing code that uses classes today and uses some identifier (like 'yield') that becomes a keyword in strict mode.

**Comment by yuit** [comment]
ES6 with Implicit Strict Mode Context
* [ ] Class Declaration
* [ ] Class Expression
* [ ] Module Declaration

**Comment by yuit** [comment]
PR#3517 covered parsing module declaration in strict mode
