### ISSUE TITLE
Regression when calling a union of function types

### ISSUE THREAD

**Issue by johnsoft** [Microsoft/TypeScript#11355]
**TypeScript Version:**  2.0.3 (This is a regression from version 2.0.0)

**Code**

```ts
type DoubleFunc = ((x: number) => void) | ((x: any) => void);

function call(f: DoubleFunc) {
	f(5);
}
```

**Expected behavior:**

I would expect the call to succeed, since the argument types satisfy both halves of the union.

**Actual behavior:** 

`error TS2349: Cannot invoke an expression whose type lacks a call signature.`

**Comment by RyanCavanaugh** [comment]
Duplicate #10025
