### ISSUE TITLE
Inconsistent tooltip help with call, apply and bind in visual studio 2015

### ISSUE THREAD

**Issue by HolgerJeromin** [Microsoft/TypeScript#11359]
**TypeScript Version:**  2.0.3

[ECMAscript 5.1](http://www.ecma-international.org/ecma-262/5.1/#sec-15.3.4.3) defines 
`Function.prototype.apply (thisArg, argArray)` with two parameters.

When i type
`callback.call(`
Visual Studio 2015 shows me the correct help with two parameters
![image](https://cloud.githubusercontent.com/assets/2410353/19083308/e83b5dfa-8a61-11e6-8770-7282ae213cfa.png)

After typing the line we have a different tooltip:
![image](https://cloud.githubusercontent.com/assets/2410353/19083408/40128dbe-8a62-11e6-9ad3-5e5cc399719f.png)

**Comment by mhegazy** [comment]
One side note, you reference `apply` above, but mention `call` in the report. `call`  does have a variadic number of arguments, see http://www.ecma-international.org/ecma-262/5.1/#sec-15.3.4.4.

As for the difference in the info shown, the first one is your parameter help message, this is meant to tell you which parameter you can specify, so the first is `thisArg` and then the remaining are arguments to this function..

the second tool tip, however, shows you the full signature of the function, this also includes the `this` argument (which is different from the first argument for the function `thisArg`).

The `this` for `callback.call(window, response` is `callback`, where as `thisArg` is `window`. 

you can find more about `this` arguments for functions in https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#specifying-the-type-of-this-for-functions

**Comment by HolgerJeromin** [comment]
OK, I should have given the screenshots for apply(). 
The same issue is valid there. 
A new apply()  parameter help shows the two arguments. 
But a given function tooltip gives a hint that apply()  needs three arguments.
I will check your link in detail later.

**Comment by HolgerJeromin** [comment]
I think now I understand the problem. The full signature tooltip it not an hint about the parameters only. 
Thanks again for the quick answer!
