### ISSUE TITLE
JSDoc Comment Appears Twice on Hover

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/TypeScript#11361]
**TypeScript Version:**  master -- commit 0871628

Tested on all combinations of Win10/Ubuntu 16.04 and vscode stable / development and TypeScript 2.0 / development (master).

Confirmed via debugging that the problem occurs because of a faulty quickinfo provided by the server.

To reproduce (sorry, I haven't found a smaller repro!):

1) clone the vscode project (checked with commit 804729f77 on the master branch)
2) Open a stable instance of vscode in the vscode directory
3) Open the file src/vs/vscode.d.ts
4) Hover over the definition of `interface Thenable<R>`.

**Expected behavior:**

Get the following completion:

```
Thenable is a common denominator between ES6 promises, Q, jquery.Deferred, WinJS.Promise,
and others. This API makes no assumption about what promise libary is being used which
enables reusing existing code without migrating to a specific promise implementation. Still,
we recommend the use of native promises which are available in VS Code.
```

**Actual behavior:** 

Get the following completion:

```
Thenable is a common denominator between ES6 promises, Q, jquery.Deferred, WinJS.Promise,
and others. This API makes no assumption about what promise libary is being used which
enables reusing existing code without migrating to a specific promise implementation. Still,
we recommend the use of native promises which are available in VS Code. Thenable is a common denominator between ES6 promises, Q, jquery.Deferred, WinJS.Promise,
and others. This API makes no assumption about what promise libary is being used which
enables reusing existing code without migrating to a specific promise implementation. Still,
we recommend the use of native promises which are available in VS Code.
```

EDIT: fixed phrasing.

**Comment by mhegazy** [comment]
I can not reproduce this any longer.
