### ISSUE TITLE
Compile error with a type cast using the "as" keyword

### ISSUE THREAD

**Issue by agaace** [Microsoft/TypeScript#11369]
**TypeScript Version:**  2.0.3

**Code**

This works:

```ts
context = ModelHelper.normalizeQuery<IMongoosePoseCollection>(context) as BaseModelQueryContext<IMongoosePoseCollection>;
```

Now I want to break down the statement between two shorter lines. This works:

```ts
context = ModelHelper.normalizeQuery<IMongoosePoseCollection>(context) as
BaseModelQueryContext<IMongoosePoseCollection>;
```

But this causes a compile error:

```ts
context = ModelHelper.normalizeQuery<IMongoosePoseCollection>(context)
as BaseModelQueryContext<IMongoosePoseCollection>;

error TS1005: ';' expected.
error TS1005: '(' expected.
```

**Expected behavior:**
I would like to be able to use white spaces as I wish inside a TS statement.

**Actual behavior:** 
New line is treated differently from regular tabs or spaces. In certain cases, new line is accepted inside a statement, in other cases it is not accepted.

**Comment by andy-ms** [comment]
See comments on #11760
