### ISSUE TITLE
Modifying the compiler: How to rename properties?

### ISSUE THREAD

**Issue by jahewson** [Microsoft/TypeScript#11364]
I'm investigating how properties could be renamed by the TypeScript compiler so that they can be more effectively minified by downstream tools. Ultimately, if successful I'd like to make this into a PR.

I'm familiar with compilers in general, but not with the internals of the TypeScript compiler. What I'd like to do is rename any identifier which isn't declared in a d.ts file. Can someone point me to the relevant source code and perhaps explain how to resolve which file the identifiers come from?

For example, if they were renamed to be prefixed with a `$`, then I can pass the resulting .js to Uglify and specify that only properties starting with a `$` are to be renamed - which should work fine for whole-program optimisation.

**Comment by mhegazy** [comment]
general documentation about the compiler is in https://github.com/Microsoft/TypeScript/wiki/Architectural-Overview and https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API.

The emit is done as a series of tree transforms, ending by a printing phase. I would recommend you look at the emitter code in https://github.com/Microsoft/TypeScript/blob/master/src/compiler/emitter.ts#L238-L249.

Also please see relevant discussion about minification in https://github.com/Microsoft/TypeScript/issues/8.

I would expect the renaming to be done in a separate transform.

If you intend to send a PR, I would recommend sharing your design early on before jumping into implementation. This way we can understand the overall approach and discuss it before looking at the code changes.

**Comment by jahewson** [comment]
Thanks, I've managed to make a custom transformation and can do some basic renaming. The existing transformers appear to make use of syntactic information only, so how can I get access to the type information associated with a given Node?

Seems like I'd need to use the TypeChecker? But how can I access that from the transformer?
