### ISSUE TITLE
arrow function emit emit error

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#11377]
**TypeScript Version:**  nightly latest

**Code**

```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "noImplicitAny": false,
        "sourceMap": false,
        "lib": [
          "es6", "dom"
        ]
    },
    "exclude": [
        "node_modules"
    ]
}
```

``` ts
const foo = (x: string) => null;
```

**Expected behavior:**

Gives js

``` js
var foo = function (x) { return null; };
```

**Actual behavior:** 

``` js
var foo = function (x: string) { return null; };
```

**Comment by mhegazy** [comment]
@rbuckton can you take a look.

**Comment by rbuckton** [comment]
@basarat Is this the entire set of repro steps? I tried this locally and cannot repro this.

**Comment by basarat** [comment]
> Is this the entire set of repro steps?

Sadly no. Seems to be an issue one with language service compile on save, stuff like semicolons etc can be used to trigger it to come in and go out. Same code can give different output depending on how the edits were made :-/ 

Made a quick video : https://www.youtube.com/watch?v=N4EgtjRnZGE :rose:

**Comment by rbuckton** [comment]
Thanks, I'll take a look at it.

**Comment by rbuckton** [comment]
In the video it looks like you're using VSCode. Are you using a `.vscode/tasks.json` and compiling with tsc in watch mode, or are you using grunt or gulp with a plugin? So far I'm still unable to reproduce this issue.

**Comment by rbuckton** [comment]
Or rather, is this Atom?

**Comment by jesseschalken** [comment]
@rbuckton I think it's https://github.com/alm-tools/alm

**Comment by basarat** [comment]
> I think it's https://github.com/alm-tools/alm

Yup.

**Comment by basarat** [comment]
Basically `compileOnSave`. This is my `build` function is simply : https://github.com/alm-tools/alm/blob/c98ffc247078c5f6308548cdcc79f8f8f90c50b0/src/server/workers/lang/modules/building.ts#L35-L43 :rose:

**Comment by basarat** [comment]
I can repro in alm with **just** `const foo = (x: string) => null` => `const foo = (x) => null;` 

With a simple `tsconfig.json`

```json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5"
    }
}
```

That said I ran the same with `tsc -w` and it doesn't happen, does that use `languageService. getEmitOutput`? :rose:

**Comment by basarat** [comment]
Looked at the tsserver and it uses the same function as me `getFileEmitOutput` : https://github.com/Microsoft/TypeScript/blob/3b0515fd8b8742d1c25c70642e853a9ed4e324c7/src/server/project.ts#L227-L232 and since you haven't been able to repro in vscode (which uses tsserver) I'll look into it a bit more :rose:

**Comment by basarat** [comment]
Guess `compileOnSave` isn't supported in tsserver yet : https://github.com/Microsoft/TypeScript/issues/10838#issuecomment-246138906 so I can't give you repro in vscode :-/

**Comment by basarat** [comment]
I've attached the project: 

[ts-emit-error.zip](https://github.com/Microsoft/TypeScript/files/520925/ts-emit-error.zip)


Opening it in alm is easy `npm install alm -g` and then `alm -o` in the project folder.

The repro is simply changing `const foo = (x: string) => "hello";` => `const foo = (x: string) => "hello"` => `const foo = (x: string) => "hello";` and the `x:string` should start appearing in the output.  

I added a log to `getRawOutput` function in alm locally as shown: 

```
export function getRawOutput(proj: project.Project, filePath: string): ts.EmitOutput {
    let services = proj.languageService;
    let output: ts.EmitOutput = services.getEmitOutput(filePath);
    console.log({ input: services.getNonBoundSourceFile(filePath).getFullText(), output: output.outputFiles[0].text });
    return output;
}
```

You can see the annotation appear and disappear in the output of `services.getEmitOutput` in the screenshot below as you edit the file to add a `;` : 

![image](https://cloud.githubusercontent.com/assets/874898/19257951/96aff4a6-8fbf-11e6-87aa-260914f2a656.png)

Please let me know if there is still more info required :rose:

**Comment by basarat** [comment]
PS: thanks for your great work. `async / await` has already prevented some hacky stuff at work :heart: :rose:

**Comment by basarat** [comment]
Update: I've pushed the fix in alm : https://github.com/alm-tools/alm/commit/687c2380d1d8a29e10000e821104ee611064b3ea that uses the slow but correct `ts.transpile` to get around the problem. So you need `npm install alm@2.3.1 -g` for the repro on the sample project :rose:

**Comment by frankwallis** [comment]
I have a similar issue to this where compile on save is not producing valid es5 output, I'm using
- Visual Studio 2015 Professional Update 3
- Microsoft.TypeScript.MSBuild v2.1.0-beta-20161008-1

Steps to reproduce:
1) Build entire project verify that async/await is correctly transpiled to ES5
```
function loadAgendaItems(meetingId, listid) {
    var _this = this;
    return function (dispatch, getState) { return __awaiter(_this, void 0, void 0, function () {
        var meetingHub, agendaItemsResponse, err_1;
        return __generator(this, function (_a) {
            switch (_a.label) {
                case 0:
                    _a.trys.push([0, 2, , 3]);
                    meetingHub = hubs_1.getMeetingHubServer();
                    return [4 /*yield*/, meetingHub.getAgendaItems(meetingId)];
                case 1:
                    agendaItemsResponse = _a.sent();
                    dispatch(repository_action_creators_1.repositoryPutNormalized(agendaItemsResponse.AgendaItems, data_types_1.DataTypes.AgendaItem, { dataType: data_types_1.DataTypes.Meeting, dataKey: meetingId }));
                    return [3 /*break*/, 3];
                case 2:
                    err_1 = _a.sent();
                    dispatch(notification_action_creators_1.growlError({ message: err_1.message }));
                    return [3 /*break*/, 3];
                case 3: return [2 /*return*/];
            }
        });
    }); };
}
```
2) Edit function containing async/await
```
export function loadAgendaItems(meetingId: number, listid: any) {
    return async (dispatch: Dispatch<GlobalState>, getState: () => GlobalState) => {
        /* I added this comment */
        try {
            const meetingHub = getMeetingHubServer();
            const agendaItemsResponse = await meetingHub.getAgendaItems(meetingId);
            dispatch(repositoryPutNormalized(agendaItemsResponse.AgendaItems, DataTypes.AgendaItem, { dataType: DataTypes.Meeting, dataKey: meetingId }));
        } catch (err) {
            dispatch(growlError({ message: err.message }));
        }
    };
}
```
3) Transpiled output now contains ```await``` keyword:
```
function loadAgendaItems(meetingId, listid) {
    var _this = this;
    return function (dispatch, getState) { return __awaiter(_this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            /* I added this comment */
            try {
                const meetingHub = hubs_1.getMeetingHubServer();
                const agendaItemsResponse = await meetingHub.getAgendaItems(meetingId);
                dispatch(repository_action_creators_1.repositoryPutNormalized(agendaItemsResponse.AgendaItems, data_types_1.DataTypes.AgendaItem, { dataType: data_types_1.DataTypes.Meeting, dataKey: meetingId }));
            }
            catch (err) {
                dispatch(notification_action_creators_1.growlError({ message: err.message }));
            }
            return [2 /*return*/];
        });
    }); };
}
```
Let me know if you would like any more information, thanks

**Comment by mhegazy** [comment]
@frankwallis what version of TS are you using for VS? compile on save is not driven from the MSBuild nugget package.

**Comment by frankwallis** [comment]
@mhegazy I have run the VSDevMode.ps1 script (as per [here](https://github.com/Microsoft/TypeScript/wiki/Nightly-drops#visual-studio-2013-and-2015)) and pointed it at my global npm typescript installation (in ...AppData/Roaming/npm/node_modules/typescript/lib) which is:
```
$ tsc -v
Version 2.1.0-dev.20161014
```
I reran the VSDevMode.ps1 script today and retried the steps above, and the same issue is present. Is there a way of verifying which version the language service is actually using?

**Comment by mhegazy** [comment]
> Is there a way of verifying which version the language service is actually using?

This is sufficient information. thank you.

**Comment by frankwallis** [comment]
Can the "Needs More Info" label be removed now?

**Comment by mhegazy** [comment]
@basarat can you give tonight's build a try.

**Comment by mhegazy** [comment]
@basarat have you had a chance to try the fix?

**Comment by basarat** [comment]
In Mexico 🇲🇽 for a conf. Will update once I try 🌹❤️

**Comment by mhegazy** [comment]
thanks.

**Comment by basarat** [comment]
I can no longer reproduce it with the latest nightly. Thanks! :rose:

**Comment by mhegazy** [comment]
thanks for conforming 🌷
