### ISSUE TITLE
Cannot use custom definitions in TS2

### ISSUE THREAD

**Issue by jjmoorhouse** [Microsoft/TypeScript#11383]
**TypeScript Version:**  2.0.3 from npm

**Code**

I've got the following project structure setup
```
@types/
-- events
---- index.d.ts
node_modules/
-- @types
-----react, react-dom etc
utils/
-- eventEmitter.js
tsconfig.json
```
In my tsconfig.json I have:
```
{
  "compilerOptions": {
    "module": "commonjs",
    "moduleResolution": "node",
    "target": "es5",
    "jsx": "react",
    "allowJs": true,
    "sourceMap": true,
    "typeRoots" : [
      "./@types"
    ],
    "types" : [
      "events",
      "ajax",
      "path",
      "keymirror"
    ]
  },
  "exclude" : [
    "node_modules",
    "@types"
  ]
}
```

in eventEmitter.js I have the following:
```
import * as events from "events";
```

**Actual Behaviour:**
When I try and compile with the file structure above, I get the following error
```
ERROR in ./utils/eventEmitter.ts
(1,25): error TS2307: Cannot find module 'events'.
```

However, if I move  `./@types/events/index.d.ts` to `./node_modules/@types/events/index.d.ts` everything works as expected and the eventEmitter will compile

**Expected behaviour:**
Using the above configuration I would expect the compiler to pick up on my custom definitions which are in `./@types` in the same way it does when the same definitions are in the `node_modules/@types` folder

**Comment by tapvolt** [comment]
I'm having the same problem too.

**Comment by mhegazy** [comment]
This looks like https://github.com/Microsoft/TypeScript/issues/11137. it should be fixed in the next release. for now to work around this issue, you will need to add a path mapping entry to tell the compiler to look in the `@types` override folder as such:

```ts
{
  "compilerOptions": {
    ...
    "path": {
         "*": ["*", "./@types/*"]
     }
     ...
  }
}
```

**Comment by jjmoorhouse** [comment]
worked a treat, thankyou very much :)

**Comment by mhegazy** [comment]
closing in favor of https://github.com/Microsoft/TypeScript/issues/11137
