### ISSUE TITLE
lib.d.ts: Nullable arguments for initMouseEvent()

### ISSUE THREAD

**Issue by vidartf** [Microsoft/TypeScript#11380]
While deprecated, the typings of `MouseEvent.initMouseEvent()` should still support strict null checks.

**TypeScript Version:**  2.0.3

**Code**

``` ts
let event = document.createEvent('MouseEvent') as MouseEvent;

// Initialize the mouse event data.
event.initMouseEvent(
  'click', true, true, window, 0,
  0, 0,
  0, 0,
  false, false,
  false, false,
  0, null   // <--- Field `relatedTarget`. Error: null not accepted
);
```

**Expected behavior:**
MDN docs specify:

> relatedTarget
>     the event's related EventTarget. Only used with some event types (e.g. mouseover and mouseout). In other cases, pass null.

So you would expect typing to read `EventTarget | null`.

**Actual behavior:** 

Null not accepted with strict null checks on.

Not sure whether any of the other fields should accept `null` or `undefined` as well...

**Comment by vidartf** [comment]
Workaround: Pass `null!`.

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by vidartf** [comment]
PR in Microsoft/TSJS-lib-generator#152.
