### ISSUE TITLE
Cannot escape parameter initializer transpilation error

### ISSUE THREAD

**Issue by frontierpsycho** [Microsoft/TypeScript#11387]
**TypeScript Version:**  1.8.10

**Code**

```ts
class TestClass {
  makeFunction(): (someCondition: boolean = false) => boolean {
    return (someCondition: boolean = false) => {
      return someCondition;
    }
  };
}

let test = new TestClass();

let generatedFunction = test.makeFunction();

// generatedFunction has a parameter initializer, and thus should be able to be called with no arguments
console.log(generatedFunction());

```

**Expected behavior:**
The above code should generate no transpilation errors.

**Actual behavior:** 
The above code produces the following error:

```error TS2371: A parameter initializer is only allowed in a function or constructor implementation.```

I'm not sure whether it's a good or a bad idea to allow parameter initializers in type definitions, but that's not the issue, read on.

**Analysis**
In this case, fixing the transpilation error produces another one. The following code fixes the transpilation error:

```ts
class TestClass {
  // note the absence of the parameter initializer
  makeFunction(): (someCondition: boolean) => boolean {
    return (someCondition: boolean = false) => {
      return someCondition;
    }
  };
}

let test = new TestClass();

let generatedFunction = test.makeFunction();

console.log(generatedFunction());
```

However, transpiling this produces the following error concerning the last line (the call to `generatedFunction()`):

```error TS2346: Supplied parameters do not match any signature of call target.```

This makes sense, as now we have told TypeScript that the function returned by `makeFunction()` expects a boolean, and we're not providing it.

I assume the use case is legitimate (generating dynamic functions with specific signatures, including parameter initializers), and right now there is no way to make the transpiler not complain, so I think something is wrong.

I'm not sure what the solution could be. Personally, I don't see a use for disallowing parameter initializers in type definitions, so I would scrap that, but perhaps there's a use case I can't think of.

Comments?

**Comment by RyanCavanaugh** [comment]
The correct code to write is:
```ts
class TestClass {
  makeFunction(): (someCondition?: boolean) => boolean {
    return (someCondition: boolean = false) => {
      return someCondition;
    }
  };
}

let test = new TestClass();

let generatedFunction = test.makeFunction();

// generatedFunction has a parameter initializer, and thus should be able to be called with no arguments
console.log(generatedFunction());
```
which generates no errors.

**Comment by frontierpsycho** [comment]
Alright, that seems like a good solution, thanks.

**Comment by RyanCavanaugh** [comment]
You could also just leave off the return type annotation and the correct type would be inferred

**Comment by frontierpsycho** [comment]
That seems to work as well. I thought I tried it and it didn't work, but apparently I was wrong.
