### ISSUE TITLE
Vague error message with async functions

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#11396]
``` ts
async function foo() {
    return "hi";
}
```

First thing I get is `An async function must have a valid awaitable return type.`

From a UX perspective, this is very confusing. If you add `es2015.promise` to your lib, it goes away.

**Comment by wallverb** [comment]
Yea, I got confused by this in the past https://github.com/Microsoft/TypeScript/issues/10805 
Especially that in one project it worked fine (that used older types for Bluebird) and in new project with latest Bluebird typings (which stopped exporting global definition for Promise) it was throwing this error with example taken from docs. Some more info for users in this error would be beneficial.

**Comment by Jiaoweiquan** [comment]
So how can I solve this problem in my code now?

**Comment by Jiaoweiquan** [comment]
Is there another way to solve this problem now?
