### ISSUE TITLE
Unification overly simplifies types resulting in the swallowing of 'undefined'

### ISSUE THREAD

**Issue by sledorze** [Microsoft/TypeScript#11402]
**TypeScript Version:**  2.0.3

This is very problematic as it weakens undefined safety *a lot*.

**Code**

```ts
function bar<A>(c:boolean, a:A, au:A | undefined) { // foo return type is inferred to A instead of A | undefined
    return c ? a : au;
}
```

**Expected behavior:**

bar return type is inferred to A | undefined (valid simplification of A | A | undefined)

**Actual behavior:** 

bar return type is inferred to A

Note: similar problem with 'null' instead of 'undefined'

**Comment by yortus** [comment]
If you set `strictNullChecks: true` in your `tsconfig.json`, then `bar` does return `A | undefined` as you expect.

**Comment by DanielRosenwasser** [comment]
@sledorze does that fix things for you?

**Comment by sledorze** [comment]
Oh dear, yes of course, wonderful! :)
