### ISSUE TITLE
Module/class augmentation doesn't work

### ISSUE THREAD

**Issue by MoonStorm** [Microsoft/TypeScript#11406]
**TypeScript Version:**  2.0.3 

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// rxjs installed via npm
// seems to expose everything via its .d.ts file:
export { Observable } from './Observable';

// attempting to augment the Observable class exposed by the rxjs module
// observable.operators.ts
import {Observable} from 'rxjs'

declare module 'rxjs' {
    interface Observable<T> {
        doStuff():void;
    }
}

// consumer.ts
import { Observable, Subscription } from 'rxjs'
export class Consumer{
  private _sub:Subscription;
   constructor(){
      this._sub = Observable.from([1,2,3]).subscribe();
   }
}
```

**Expected behavior:**
The ``doStuff`` to appear available in the rxjs module on the ``Observable`` class.

**Actual behavior:** 
Attempting to use ``import {Observable} from 'rxjs'`` in another file (consumer.ts) causes compilation errors.

Export declaration conflicts with exported declaration of 'Observable'
Property 'subscribe' does not exist on type 'Observable<T>'
etc.

**Comment by RyanCavanaugh** [comment]
I don't see any calls to `doStuff` in your repro code. Please don't make us guess.

**Comment by MoonStorm** [comment]
The ``doStuff`` doesn't matter. Ironically enough, a similar example using ``Observable`` was posted in the TS guidebook. In that sample the augmentation is done at the same level as the ``Observable.d.ts`` file, as if we're gonna augment libraries straight in the ``node_modules`` folder.

**Comment by RyanCavanaugh** [comment]
The correct declaration looks like this:
```ts
import {Observable} from 'rxjs'

declare module 'rxjs/Observable' {
    interface Observable<T> {
        doStuff():void;
    }
}
```

```ts
import { Observable, Subscription } from 'rxjs'
export class Consumer{
  private _sub:Subscription;
   constructor(){
      this._sub = Observable.from([1,2,3]).subscribe();
      Observable.from([1, 2]).doStuff(); // OK
   }
}
```

**Comment by MoonStorm** [comment]
Yep, that works. Thanks. 
Could you please update the docs with this example, in the module augmentation section as well as in ``what's new`` ? Nobody is going to augment ``rxjs``'s ``Observable`` straight in the module's own folder.

**Comment by RyanCavanaugh** [comment]
The example is just supposed to be an example and it doesn't mention rxjs at all. Do we need to use class names that no one has ever used before?

**Comment by MoonStorm** [comment]
Haha, no of course not. Just saying you've picked a very popular and extendable class name. I bet I'm not going to be the only one being thrown off by that example.

**Comment by mhegazy** [comment]
my bad. that example was actually modeled by RXJS code a la: https://github.com/ReactiveX/rxjs/blob/master/src/add/operator/map.ts. in hind sight, probably not the best example for the general public.

**Comment by MoonStorm** [comment]
No worries. It would probably be much useful to show how to augment an external lib, may that be ''rxjs'' or a fictive one. 
I had never seen a module declaration like that. Is that because the ''Observable'' is being re-exported by the main module? Aren't we tying ourselves up with the inner structure of the external module?

**Comment by RyanCavanaugh** [comment]
> Is that because the ''Observable'' is being re-exported by the lib's main module? Aren't we tying ourselves up with the inner structure of the external module?

Correct. It's tricky because it's not apparent that augmenting an alias should effect the underlying thing (what if it was aliased under a completely different name?). But this is how the runtime generally has to operate as well for augmentation -- if you're not setting on the correct root object, it may not work.

**Comment by MoonStorm** [comment]
I undestand now. Obviously not a vey sustainable solution long term. The runtime could be helped through a keyword acting as a hint that an augmentation is at play, which means the root needs to be resolved and changed?
