### ISSUE TITLE
Possible problem with semi-colon insertion

### ISSUE THREAD

**Issue by pj** [Microsoft/TypeScript#11416]
The example below is part of a larger project that I haven't been able to simplify further, the full code is at https://github.com/pj/versionbase/tree/bossible-pug. It occurs when I remove any line of code between the javascript object and the call to test_message_send.  This is on line 93 of test/versionbase.ts. It starts working if I insert a semi-colon after the object literal.

Not sure how to simplify this further as everything I change causes the test to start working. I'm thinking this has something to do with semi-colon insertion, but may just be that my code is wrong.

**TypeScript Version:**  2.0.0

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
        let second_response_message = {
            status: 0,
            message: "",
            message_id: "bar"
        }

        // DELETE THIS AND IT WILL FAIL!
        second_response_message;
        // -------------

        [transshots, _] = test_message_send(transshots,
                                            [first_request_message, second_request_message],
                          function (socket_mock) {
                            socket_mock.expects("send")
                                .once()
                                .withArgs(JSON.stringify(first_response_message))
                            socket_mock.expects("send")
```

**Expected compiler output:**
```ts
        let second_response_message = {
            status: 0,
            message: "",
            message_id: "bar"
        };
        [transshots, _] = test_message_send(transshots, [first_request_message, second_request_message], function (socket_mock) {
            socket_mock.expects("send")
                .once()
                .withArgs(JSON.stringify(first_response_message));
```

**Actual compiler output:** 

```ts
        let second_response_message = {
            status: 0,
            message: "",
            message_id: "bar"
        }[transshots, _] = test_message_send(transshots, [first_request_message, second_request_message], function (socket_mock) {
            socket_mock.expects("send")
                .once()
                .withArgs(JSON.stringify(first_response_message));
            socket_mock.expects("send")
```

**Comment by yortus** [comment]
TypeScript is correctly applying ECMAScript's [ASI rules](http://www.ecma-international.org/ecma-262/7.0/index.html#sec-rules-of-automatic-semicolon-insertion) here. You need a semicolon between the closing brace of the `let` declaration and the following `[`.

**Comment by RyanCavanaugh** [comment]
This is how JavaScript works
![image](https://cloud.githubusercontent.com/assets/6685088/19163407/b1e74386-8bb0-11e6-9b63-1b90a0bef3d4.png)

(insert my rant about "standard" JS here) 🙄
