### ISSUE TITLE
Discriminated extended interfaces

### ISSUE THREAD

**Issue by zakjan** [Microsoft/TypeScript#11417]
Discriminated types are great, however they work only when the parent type is defined as union of child types. There is a disadvantage that all shared properties needs to be declared in all child types.

Can we extend it to support the following case, where the parent type is also an interface?

**TypeScript Version:**  2.0.3

**Code**

```ts
interface Shape {
    type: string;
    color: string;
}

interface Circle extends Shape {
    type: "Circle";
    radius: number;
}

const shape = {
    type: "Circle",
    color: "red",
    radius: 5,
} as Shape;

if (shape.type === "Circle") {
    console.log(shape.radius);
}
```

**Expected behavior:**
No error.

**Actual behavior:** 
`Property 'radius' does not exist on type 'Shape'.`

**Comment by alitaheri** [comment]
That would require the type-checker to linearly search through every type it has ever indexed to see if they extend the `Shape` interface, or keep track of all type hierarchies of each type, the first will hugely impact performance and the second will probably choke the RAM.

However there _can_ be an alternative. If somehow you tag `Shape` in a way that reflects it's subtypes then this could be implemented without any impacts. This would make the language more complex though. 

I'm guessing you should embrace for `Working as Intended` 😅 😅

**Comment by zakjan** [comment]
Yeah I can implement it by having separate parent interface and union type. But it doesn't look clean.

**Comment by RyanCavanaugh** [comment]
Not to mention a type from some other union could show up with a `Circle` discriminant and now your code breaks, which is hardly ideal.
