### ISSUE TITLE
Language service: unable to rename property in destructured object with generic type

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/TypeScript#11418]
2.0.3

Renaming properties from destructured objects works:

``` ts
(() => {
    type Foo = { bar: number }
    const foo: Foo = { bar: 1 }
    const { bar } = foo; // hover over bar, TS/VS Code highlights other instances of the property. renaming updates all identifiers, good!
})()
```

![image](https://cloud.githubusercontent.com/assets/921609/19156120/b6986d56-8bd8-11e6-9a4f-135ae41d0cf1.png)

However, if `Foo` has a generic, this fails:

``` ts
(() => {
    type Foo<T> = { bar: number }
    const foo: Foo<any> = { bar: 1 }
    const { bar } = foo; // hover over bar, TS/VS Code doesn't highlight any other instances of the property. renaming fails!
})()
```

![image](https://cloud.githubusercontent.com/assets/921609/19156137/ca7f1c84-8bd8-11e6-9157-690a61b0bdcb.png)

**Comment by Andarist** [comment]
This has been fixed a long time ago, the ticket can be closed.
