### ISSUE TITLE
Calling and indexing on type 'never' is allowed

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#11412]
Given that a property accesses and `new`ing isn't allowed on something of type `never`,

``` ts
declare var f: never;

// Error: Cannot use 'new' with an expression which lacks a construct signature.
new f();

// Error: Property 'x' does not exist on type 'never'.
f.x;
```

I was surprised to find that `never` is still callable and indexable.

``` ts
declare var f: never;

// All okay
f();
f[100]
f["x"]
```

Is this intentional?

**Comment by ahejlsberg** [comment]
It's definitely a bug that we don't error on the call expression. The element access expressions are permitted because *anything* can be indexed to produce an implicit `any`. You'll get an error if you turn on `--noImplicitAny`, so I think that is behaving as expected.
