### ISSUE TITLE
arg destructuring should throw with undefined in downlevel compiled to es5

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#11415]
**TypeScript Version:**  2.0.0
**Code**

```ts
function foo(a, b) { console.log(a, b); }
foo(...undefined);
```

This code throws if executed 'natively' in es6. However code that got down level compiled to es5 will not throw. To my knowledge ES6 defines that de-structuring of undefined should throw.

**Comment by RyanCavanaugh** [comment]
It's already an error.

![image](https://cloud.githubusercontent.com/assets/6685088/19247731/71940204-8ee1-11e6-9efb-196d58617cce.png)

![image](https://cloud.githubusercontent.com/assets/6685088/19247738/7c31af72-8ee1-11e6-9b67-cfb3780bc6e1.png)

**Comment by dbaeumer** [comment]
@RyanCavanaugh I think showing an error is not enough. As said native es6 throws. So if TS down level compiles this to es5 the generated code should throw as well. Can you please reconsider this.

**Comment by kitsonk** [comment]
I believe the common response to this is "if something that generates an error is ignored, TypeScript never makes assertions to the validity of the emitted code".  Why value is there in transforming code that has been statically identified to an error?  The goal of TypeScript isn't to make your broken code break in the same way.

An analog:

```typescript
class Foo {
    bar() { console.log('bar'); }
}

let foo = Foo();
```

Will emit this:

```javascript
var Foo = (function () {
    function Foo() {
    }
    Foo.prototype.bar = function () { console.log('bar'); };
    return Foo;
}());
var foo = Foo();
```

Calling a `class` without the `new` keyword in ES6 throws `Class constructor Foo cannot be invoked without 'new'` but the down emit just silently fails.

**Comment by RyanCavanaugh** [comment]
Misunderstood; people commonly say "throw" to mean "raise a compile error"

**Comment by RyanCavanaugh** [comment]
Basically the same problem as  #1679; see discussion there -- it's not tractable in ES5 to detect which objects would be spreadable in ES6 and which wouldn't
