### ISSUE TITLE
intersection type of types whose super type has method returning `this` cannot be used as type argument with constraints of super type

### ISSUE THREAD

**Issue by HerringtonDarkholme** [microsoft/TypeScript#11421]
**TypeScript Version:**  2.0.3

**Code**

``` ts
class V { returnThis: () => this }
type VC<C extends V> = {}
function foo<A extends V, B extends V>(): VC<A & B> { throw new Error('unimplemented')}
```

**Expected behavior:**

Should compile. According to the spec, `A & B` is equivalent to 

``` typescript
type AB = {
  returnThis(): A
  returnThis(): B
}
```

And both signature is assignable to `V`'s returnThis

**Actual behavior:** 

Compilation fails. Reports:

Types of property 'returnThis' are incompatible. Type '(() => A) & (() => B)' is not assignable to type '() => A & B'. 

Where `(() => A) & (() => B)` should be compared with `() => V`, not `() => A & B`

**Comment by HerringtonDarkholme** [comment]
Another case:

```
class V { returnThis: () => this }
type VC<C extends V> = {}
class A extends V {
  a: any
}
class B extends V {
  b: any
}
var k: VC<A & B> = (null as any) // this line does not work
var c: V = (null as any) as (A & B) // this line does
```

**Comment by RyanCavanaugh** [comment]
These both check without error now.
