### ISSUE TITLE
narrowing doesn't work

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#11433]
latest nightly build as of October 6, 2016:
```typescript

interface A { kind: 'A'; a: number; }
interface B { kind: 'B'; b: number; }
type AB = A | B;
export function toResult<Z extends { kind: K; }, K extends string>(
    value: AB | Z,
    orElse: (value: Z) => number
): number {
    switch (value.kind) {
        case 'A': return value.a; // <-- problem, value isn't narrowed to A
        case 'B': return value.b;
        default: return orElse(value);
    }
}
```

**Comment by aleksey-bykov** [comment]
despite https://github.com/Microsoft/TypeScript/issues/10417#issuecomment-241016403

**Comment by ahejlsberg** [comment]
I don't think this is a bug. We don't know for sure that Z's `kind` property isn't `'A'` or `'B'` (it could basically be any string value), so we can't safely narrow to `A` or `B` in the switch cases.

**Comment by aleksey-bykov** [comment]
i see your point, negating type constraints (#7993) could have guaranteed that `Z.kind` is neither 'A' nor 'B':
```
export function toResult<Z extends { kind: K; }, K extends string unlike 'A', 'B'>(
```
