### ISSUE TITLE
Getting error `The target "PreComputeCompileTypeScript" does not exist in the project.`

### ISSUE THREAD

**Issue by basarat** [microsoft/TypeScript#1143]
> The target "PreComputeCompileTypeScript" does not exist in the project.

Complete error : 

```
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v11.0\TypeScript\Microsoft.TypeScript.targets(121,34): error MSB4057: The target "PreComputeCompileTypeScript" does not exist in the project. [C:\dev\Web.csproj]
```

**Comment by ivanovvitaly** [comment]
Change MSBuild path from one that in Microsoft.NET folder to one that in Program File, in my case its c:\Program Files (x86)\MSBuild\12.0\Bin\MSBuild.exe.
