### ISSUE TITLE
Please, make an option for syntax to write code without {}, such as python has, this is a dream for many people.

### ISSUE THREAD

**Issue by paveltaran** [Microsoft/TypeScript#11444]
const request = require("request-promise")

	interface User
	  id: number
	  username: string

	class RegUser 

	  constructor(public user: User)

	  async reg(): Promise<boolean> 
	    try 
	      let user = JSON.stringify(this.user);
	      await request('http://host.com/api/reg').post(user)
	      return true
	    catch(e)
	      console.error(e)
	    return false

	let user: User = 
	  id: 1
	  username: 'root'

	new RegUser(user).reg()

**Comment by aleksey-bykov** [comment]
wut?!

**Comment by kitsonk** [comment]
The [TypeScript Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals) would totally prohibit this from even being considered.

If you want a language that is not a superset of JavaScript, then TypeScript is not for you.

**Comment by gcnew** [comment]
What about parens for invokation? They are not needed as well (see F#). #noParents

**Comment by RyanCavanaugh** [comment]
> If you want a language that is not a superset of JavaScript, then TypeScript is not for you.

Indeed. Many options listed at https://github.com/jashkenas/coffeescript/wiki/list-of-languages-that-compile-to-js

**Comment by aleksey-bykov** [comment]
#noParents 😆 come to my place, parents gone!

**Comment by RyanCavanaugh** [comment]
[#noChildren](https://www.youtube.com/watch?v=wRP6egIEABk)
