### ISSUE TITLE
[Request] String enums

### ISSUE THREAD

**Issue by aaronbeall** [Microsoft/TypeScript#11453]
# Request: String enums

Right now TS supports enums which are backed by numbers, and string literal types. Both are nice in some ways but fall short (in separate ways) of how I almost always want to use them. I've asked a number of questions on stack-overflow which has led me to this request.

**Problem with `enum`:**
Enums are backed by numbers which works fine in a closed code system, but in TS you are usually dealing with external JS, and in my experience enums are usually defined as strings in JS, which makes them incompatible with TS enums (without doing some type-safety-breaking gymnastics). In addition, you cannot natively serialize to/from most JSON APIs because they usually pass their enums as strings.

**Problem with string literal types:**
String literal types are great at defining the allowed values of a field, but if you want to use constants for your values in code you have to counter-intuitively define everything twice and rather verbosely:

```ts
type Color = "red" | "green" | "blue";

namespace Color {
    export const RED: Color = "red";
    export const GREEN: Color = "green";
    export const BLUE: Color = "blue";
}

let favoriteColor: Color = JSON.parse(`"red"`);
if (favoriteColor === Color.RED) alert("success");
```

## Solution

***Option 1: enum values***

```ts
enum Color {
  RED("red"),
  GREEN("green"),
  BLUE("blue")
}

let fav: Color = JSON.parse(`"red"`);
fav == Color.RED // true
fav == "red" // true
fav == "Red" // type error
```

***Option 2: some other enum-like type+value declaration that is backed by strings***

```ts
strings Color {
  red,
  green,
  blue
}
let fav: Color = JSON.parse(`"red"`);
fav == Color.red // true
fav == "red" // true
fav == "Red" // type error
```
Emits
```js
var Color = {
  red: "red",
  green: "green",
  blue: "blue"
};
var fav = JSON.parse("\"red\"");
fav == Color.red
fav == "red"
fav == "Red"
```

In either option the idea is that the type checker sees the type as literal strings like `type Colors = "red" | "green" | "blue"` and emits the values for use within code.

**Comment by wallverb** [comment]
https://github.com/Microsoft/TypeScript/issues?q=is%3Aissue+%22string+enums%22+is%3Aopen+sort%3Acomments-desc

**Comment by RyanCavanaugh** [comment]
Please search before logging new issues. This has been brought up many times already.
