### ISSUE TITLE
License and copyright issues

### ISSUE THREAD

**Issue by SnarkBoojum** [microsoft/TypeScript#11469]
There are copyright statements for "Ecma International", pointing to the license [here](http://hg.ecmascript.org/tests/test262/raw-file/tip/LICENSE)... which is a 404.

There are also copyright statements for "the Sputnik authors", saying the license is a BSD with a complete statement in a "LICENSE" file which I don't find.

Could you please fix those issues? I'm trying to package typescript for the Debian distribution, and they are in the way.

Thanks

**Comment by DanielRosenwasser** [comment]
Hey @SnarkBoojum, glad to hear you're making it easier to use TypeScript for Debian users! Just to unblock you, is there any particular reason you need to package the test suite with TypeScript itself? It seems unnecessary to redistribute the compiler & language service.

@bterlson @mhegazy @CyrusNajmabadi are these from [test262](https://github.com/tc39/test262/)? I can't find what appropriate change should be at this point.

For the record, instances of the copyright statements in question are

* [here for Ecma International](https://github.com/Microsoft/TypeScript/blob/02547fe664a1b5d1f07ea459f054c34e356d3746/tests/baselines/reference/parser15.4.4.14-9-2.js#L2-L6)
* [here for the Sputnik authors](https://github.com/Microsoft/TypeScript/blob/02547fe664a1b5d1f07ea459f054c34e356d3746/tests/baselines/reference/parserS7.6.1.1_A1.10.js#L2-L3)

**Comment by SnarkBoojum** [comment]
Well, I'll ship only the compiler in the binary package, but the source package will have everything, and hence needs clear licensing statements, to make sure it can be redistributed.

**Comment by bterlson** [comment]
The test262 license is here: https://github.com/tc39/test262/blob/master/LICENSE

**Comment by SnarkBoojum** [comment]
Excellent, thanks. And for Sputnik authors, where can I know more precisely which BSD license is the right one?

**Comment by bterlson** [comment]
@SnarkBoojum It's the same license, see eg: [this search](https://github.com/tc39/test262/search?utf8=%E2%9C%93&q=sputnik) showing the latest state of these files. IIRC Google owned the copyright to these files so may have re-licensed to contribute to test262.

**Comment by SnarkBoojum** [comment]
Ok, so it's a [BSD-3-clause](https://opensource.org/licenses/BSD-3-Clause)

**Comment by RyanCavanaugh** [comment]
I can't figure out which text OP is referring to and no one else seems to be noticing. Closing absent further data.

**Comment by SnarkBoojum** [comment]
I described the problem precisely, specific examples were given the same day I opened the issue (first comment).

To this day, there are still copyright notices pointing to a 404 (Ecma International) or to a non-existent BSD license file (Sputnik authors).

I could ship the package in Debian using the information given here in this issue ; here is the nice [file](https://salsa.debian.org/js-team/node-typescript/blob/master/debian/copyright) where you'll get the full list of places where Ecma International and Sputnik authors are mentioned, with correct licensing.

Please reopen - and fix.

**Comment by RyanCavanaugh** [comment]
In which file?

**Comment by SnarkBoojum** [comment]
I gave a pointer to the Debian file where I list all files with copyright Ecma International and all files with copyright Sputnik authors : [here it is again](https://salsa.debian.org/js-team/node-typescript/blob/master/debian/copyright)

For each of this files, the current comments need to be updated to point to a correct license : in the first list, the license points to a 404 page and for the second, to a BSD license file which isn't there. Notice that the Debian file also has the texts of the correct licenses (correct as far as I know - I got the information here).

**Comment by CyrusNajmabadi** [comment]
> For each of this files, the current comments need to be updated to point to a correct license 

Note: my recollectoin from the time was that these files are simply part of a 'raw' test suite.  The copyright attribution in them is used to help us test that our compiler can handle files containing code like that.  It wouldn't be appropriate to change these as these are test inputs used for validation.  

Take https://github.com/microsoft/TypeScript/blob/master/tests/baselines/reference/parser15.4.4.14-9-2.errors.txt for example.  This is a file that represents what the TypeScript compiler saw when it processed this raw file.   

Imagine, for example, that you have a tool (which it looks like you actually have) which scans files looking for comments at the start of a file.  It then spits out the unique comments it sees into new files, one file per unique comment.  Those files themselves aren't intended to be covered by the copyright of that comment if the comment contained a copyright.  It's simply the output of a tool that was processing input and checking for an expected output.  

Note: iirc, this was checked with the legal team at the time (including those versed in licensing), and they signed off having a test suite for a compiler that was snapped at a particular point in time was acceptable.  The idea is that this is a validation that we produce the exact same output over time, even for files that contain contents that may not be meaningful now if looked at by an external party.

**Comment by RyanCavanaugh** [comment]
OK, just to be clear: the content of test files is not our copyright license. Any tool that tries to interpret them as such needs to have some kind of filtering capability to not be confused by them.

**Comment by SnarkBoojum** [comment]
Oh, so that means my file describing the copyrights is wrong and I should drop every special case?

**Comment by CyrusNajmabadi** [comment]
> Oh, so that means my file describing the copyrights is wrong and I should drop every special case?

@SnarkBoojum 

You basically might need to filter out the https://github.com/microsoft/TypeScript/blob/master/tests directory.  Or, for your tool, files that start with `tests/baselines/` and `tests/cases/` when scannin typescript.

These files are raw data inputs to our test harness.  The contents of them is for testing purposes and doesn't actually signify a claim about copyright.  

Once you have that filter in place, then your scan of TS should be clear.  

Thanks!

**Comment by SnarkBoojum** [comment]
The tool is basically me. I checked each file to see if there was some kind of copyright assignment.
