### ISSUE TITLE
Implement `emit` command in tsserver

### ISSUE THREAD

**Issue by s-panferov** [Microsoft/TypeScript#11468]
Hi, I'm the author of https://github.com/s-panferov/awesome-typescript-loader and I'm trying to migrate loader to use tsserver. This will help to resolve all incompatibles with the current typescript behavior. But unfortunately it's very tricky to implement this now because in the tsserver we only have `CompileOnSaveEmitFile` command which don't event returns paths to files it writes. And my goal is to read emit output and pass it to webpack.

It will be very helpful to provide an `emit` command that just returns output without any IO actions.

**Comment by mhegazy** [comment]
I am not sure why you would use the server then. The server is mostly suited for managing state and keeping file uptodoate. this includes watching files, reading from disk and writing them as well. the server tries to limit the communication with the host as much it can. sending files back and forth in json messages will generate a lot of garbage and would impact performance, let a side not scaling for large files.

> Hi, I'm the author of https://github.com/s-panferov/awesome-typescript-loader and I'm trying to migrate loader to use tsserver. This will help to resolve all incompatibles with the current typescript behavior. 

I think this is the real problems. what are the incompatibilities, and how can we help solve these?

**Comment by s-panferov** [comment]
@mhegazy one of the biggest problems right now is to find out a full list of files that must to be added to `Program` including @types and other references like `compilerOptions.lib`.

**Comment by mhegazy** [comment]
Why is it a problem? calling `createProgram` should do that for you assuming you have the correct implementation for the `CompilerHost`. Can you elaborate on the issues you are running into?
