### ISSUE TITLE
Suggestion: `--module ignore` option

### ISSUE THREAD

**Issue by saschanaz** [microsoft/TypeScript#11477]
### Background

I'm planning a _standalone_ (that is, not-importing-anything) library that does support module-supporting systems and no-module-support systems together. I'm letting my Jakefile.js to compile my files multiple times to support different module systems including native ES6, commonjs and systemjs.

Now I want to support browser contexts which do not have ES6 module syntax support or any module system libraries such as requires, because I don't want to force users to deal with unwanted dependencies.
### Suggested behavior

`--module ignore` option should silently ignore `export` statements and must explicitly error with `import` statements and module augmentations.

(This makes `--module ignore` a less restrictive version of `--module none`, which errors for all `export`, `import` and module augmentations.)

Input:

``` ts
// with --module ignore
namespace MyNamespace {
    // Do not pollute global scope and wrap everything into this namespace
    // The only exception is this namespace declaration itself...
}

export default MyNamespace;
```

Output:

``` js
var MyNamespace;
(function (MyNamespace) {
})(MyNamespace || (MyNamespace = {}));

// export statement is ignored
```

Input:

``` ts
// with --module ignore
import { myFunction } from "mymodule";

myFunction();
```

Output:

`Cannot use imports or module augmentations when '--module' is 'ignore'.`

**Comment by kitsonk** [comment]
This would raise so many issues...  While it might "work" for you, there would likely be so many name collisions, etc. and impose so many contraints.  For example what would you do with this:

```typescript
import { myFunction as otherFunction } from 'mymodule';

otherFunction();
```

or anything with a default import/export:

```typescript
import bar from 'bar';
```

Those not wishing to impose downstream requirements on modular code use bundlers that do not require any further steps than including a script tag on a page.  For example, [WebPack](https://webpack.github.io/), though there are many others.

**Comment by SaschaNaz** [comment]
>For example what would you do with this:

I want any `import` statements to be error when compiling with `--module ignore`, regardless of their form.

**Comment by mhegazy** [comment]
this is rather a specific request. waiting to see if other users are running into similar issues.

**Comment by kitsonk** [comment]
I see the point now, but why would the same behaviour as `--module none --target es5` apply to `--module none --target es6` instead of introducing a new value?

**Comment by SaschaNaz** [comment]
>but why would the same behaviour as --module none --target es5 apply to --module none --target es6 instead of introducing a new value?

`--module none` also errors on `export` statements but I want to reuse my existing module exporting code more easily. `--module ignore` will allow `export`s but with no output, as if there was no `export`.

**Comment by kitsonk** [comment]
Ok, then I guess back to my original question.  What does the compiler do when it encounters:

```typescript
import { myFunction as otherFunction } from 'mymodule';

otherFunction();

import bar from 'bar';

bar;
```

It can't just ignore those import statements, and it could easily end up with a name collision generating invalid code.  Also, how would you handle any sort of external MID too, like a library included from npm?

It wouldn't make sense to say "hey developer, you can't use default imports or rename any imports or include any external imports if you are going to use this feature and I am not even going to tell you about it".

The only safe way is to wrap them in closures, passing in their dependencies, plus a loader to load any external dependencies, but then that is what a bundler does, so why not use a bundler, because the JavaScript community need another module format like they need a hole in the head.

**Comment by SaschaNaz** [comment]
@kitsonk 

1. Ignore `export`s
2. Error for any `import`s and module augmentations.

Rule number 1 is new and only number 2 will be same as the current `--module none --target es5` behavior. My proposal does not differentiate simple imports, renaming imports or default imports as they will all be rejected by compiler. The input code therefore should not have any module dependencies, in other words, it should be standalone.

**Comment by RyanCavanaugh** [comment]
This hasn't picked up much interest over the years so I think it's safe to say this isn't likely to happen anytime soon.
