### ISSUE TITLE
Define array of non-nullables

### ISSUE THREAD

**Issue by Strate** [Microsoft/TypeScript#11472]
I need to define array of any non-nullable values. Is it possible?
Example:
```ts
declare type NonNullable; // this is placeholder for type, which I am looking for
let a: NonNullable[] = [];
let b: string | null;
a.push(b); // expected compile error;
```

**Comment by DanielRosenwasser** [comment]
`{}` is the empty member type, which every type is structurally compatible with, except for `null`, `undefined`, and `void`.

This should work with `--strictNullChecks` mode.

```ts
type NonNullable = {};

let a: NonNullable[] = [];
let b: string | null;

a.push(b); // expected compile error;
```

**Comment by Strate** [comment]
@DanielRosenwasser nice, it works, thank you!
