### ISSUE TITLE
error TS2342 setting object attributes

### ISSUE THREAD

**Issue by yeiniel** [Microsoft/TypeScript#11476]
**TypeScript Version:**  2.1.0-dev.20161007

**Code**

```ts
let myObj: any = new Object(),
    str = "myString",
    rand = Math.random(),
    obj = new Object();

myObj.type              = "Dot syntax";
myObj["date created"]   = "String with space";
myObj[str]              = "String value";
myObj[rand]             = "Random Number";
myObj[obj]              = "Object";
myObj[""]               = "Even an empty string";

console.log(myObj);
```

The code above is a modified version of an example code given [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Working_with_Objects). The modifications were made to make the code more Typescript compatible. 

**Expected behavior:**

Code should compile.

**Actual behavior:** 

The following error is emited: 
**example.ts(12,1): error TS2342: An index expression argument must be of type 'string', 'number', 'symbol', or 'any'.**

And according to this Javascript [reference documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Working_with_Objects) any value is a valid key when using brackets notation.

I search for a workaround on the internet but found nothing.

**Comment by aluanhaddad** [comment]
Yeah, but how often do you intentionally want to use the `"[object Object]"` as a property name? How about `"function anonymous() {\n\n}"` or `"false"`. Anyway the workaround is
```ts
myObj[<any>obj] = "Object";
```

**Comment by basarat** [comment]
Reducing your sample to just the error: 

```ts
const myObj: any = new Object();
const obj = new Object();
myObj[obj] = "Object"; // An index expression argument must be of type 'string', 'number', 'symbol', or 'any'.

console.log(myObj);
```

This is just TypeScript helping you write better JavaScript : https://basarat.gitbooks.io/typescript/content/docs/javascript/recap.html 

For key access JavaScript calls `toString` and the default implementation will just be `"[object Object]"` which is almost *definitely* not what you want. To be explicit you can do `toString` yourself: 

```
const myObj: any = new Object();
const obj = new Object();
myObj[obj.toString()] = "Object"; // No Error!

console.log(myObj);
```

But that is almost definitely not what you want! 

If you want to use objects as keys you can either use the ES6 `Map` or a library e.g. my own : https://github.com/basarat/typescript-collections :rose:

**Comment by yeiniel** [comment]
Thank you all guys. I just raise the issue because i don't found any info on the internet on this. And given there is a solution i think this issue should be closed.

Thanks all again
