### ISSUE TITLE
merge.d.ts

### ISSUE THREAD

**Issue by daflair** [Microsoft/TypeScript#11471]
**TypeScript Version:**  1.8.0 / nightly (2.0.0-dev.201xxxxx)

**Code**

```ts
// A *self-contained* demonstration of the problem follows...

```

**Expected behavior:**

**Actual behavior:**

**Comment by basarat** [comment]
mistake?

**Comment by RyanCavanaugh** [comment]
Please fill out the form *before* submitting it :wink:

**Comment by daflair** [comment]
Not sure how this ended up here, sorry!
