### ISSUE TITLE
VS crashes on typescript version 2.0+

### ISSUE THREAD

**Issue by Cameron-Smith2016** [Microsoft/TypeScript#11479]
**TypeScript Version:**  1.8.0 / nightly (2.0.0-dev.201xxxxx)

When running the typescript version 2.0 and up

Visual Studio 2015 enterprise.  *Note I am not using "resharper".

I Have the vs update 3. I have run a repair. A full re-installation. I have done a full system Format.
I have 4 other individuals whom sit around me, when they install the new update the same errors occur on their system. 

I am not sure if others are experiencing the same issues? Maybe a update roll back for TypeScript for VS is needed.

**Expected behavior:**
Transform all T4 templates succeeded.
**Actual behavior:** 
VS studio crashes and restarts.

**Comment by mhegazy** [comment]
There should be a relevant entry in the event log after the crash. can you share the stack.

can you share a crash dump of the process?

also is this happening for opening any .ts file? or is it a specific file or project? if it is the later, can you share the project?

**Comment by Cameron-Smith2016** [comment]
@mhegazy 
Sorry for the extremely late reply, tried to see if i can first find something that was breaking the d.ts definition files, but I have come up short. 

So I am using a much used MVC template, called serenity. When i update typescript version 1.8  to anything above, Visual studio will just restart, no crash log is recorded, so I cannot even view the crash dump. But at least the IntelliSense works. But when I downgrade to the 1.8 typescript the IntelliSense stops working all together, it is  like typing in text file. And not being all that familiar with ts, I rely on the IntelliSense quiet heavily. So what I'am having to do is type it on a different device and then send the code over and then try adjust it to my specific task at hand. 

I am completely baffled.

**Comment by mhegazy** [comment]
Can you share a sample project from your template we can try with?
