### ISSUE TITLE
[Symbol.iterator] Syntax highlighting

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/TypeScript#11474]
Version: 2.0.3

When using `[Symbol.iterator](){}` Syntax highlighting breaks.

Before:

![iterator-1](https://cloud.githubusercontent.com/assets/1571806/19225162/ce93952c-8e5b-11e6-8a12-d1457c7265df.png)

After:

![iterator-2](https://cloud.githubusercontent.com/assets/1571806/19225161/ce917a44-8e5b-11e6-944c-0f42af89f0ef.png)

**Comment by aluanhaddad** [comment]
I am seeing this for all computed method names as well as for computed `get` and `set` accessor names within a class body.

**Comment by basarat** [comment]
Probably belongs here : https://github.com/Microsoft/TypeScript-TmLanguage :rose:

**Comment by mhegazy** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#299
