### ISSUE TITLE
Can the path be used in Chinese?

### ISSUE THREAD

**Issue by Barryyue** [Microsoft/TypeScript#11478]
**TypeScript Version:**  1.8.0 / nightly (2.0.0-dev.201xxxxx)

[**Code**]()

``` ts
// A *self-contained* demonstration of the problem follows...

```

**Expected behavior:**

严重性   代码  说明  项目  文件  行 禁止显示状态
错误      “AssignTargetPath”任务意外失败。
System.ArgumentException: 路径中具有非法字符。
   在 System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   在 System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   在 Microsoft.Build.Tasks.AssignTargetPath.Execute()
   在 Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   在 Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()    TypeScriptDemo003           

**Actual behavior:** 
Typescript项目不能用中文路径的?我是.net开发,有一个项目临时放在了中文路径下,编译 和运行是没问题的,但是创建了一个.ts文件后编译报错了

**Comment by mhegazy** [comment]
I do not see TypeScript on this stack. can you share a full MSBuild build log with `/verbosity:diagnostic`

**Comment by changyueyue** [comment]
就是在一个有中文路径的vs项目中，添加一个typescript的文件，然后编译，就能重现这个问题了，可以听懂吧？抱歉，我英语不好

Get Outlook for iOS<https://aka.ms/o0ukef>




On Tue, Oct 11, 2016 at 1:04 AM +0800, "Mohamed Hegazy" <notifications@github.com<mailto:notifications@github.com>> wrote:


I do not see TypeScript on this stack. can you share a full MSBuild build log with /verbosity:diagnostic

―
