### ISSUE TITLE
readonly flag not inherited

### ISSUE THREAD

**Issue by jrieken** [Microsoft/TypeScript#11484]
**TypeScript Version:**  2.0.3
**Code**

```ts
// A *self-contained* demonstration of the problem follows...
interface IFoo {
	readonly bar: boolean;
}

let f: IFoo;
f.bar = true; // error, good
 

class Foo implements IFoo {
	bar = true;

	mod() {
		this.bar = !this.bar;
		//   ^^^
		//   expected error?
	}
}

new Foo().bar = false;
//        ^^^
//        expected error?

```

open in [ts playground](https://www.typescriptlang.org/play/index.html#src=interface%20IFoo%20%7B%0D%0A%09readonly%20bar%3A%20boolean%3B%0D%0A%7D%0D%0A%0D%0Alet%20f%3A%20IFoo%3B%0D%0Af.bar%20%3D%20true%3B%20%2F%2F%20error%2C%20good%0D%0A%20%0D%0A%0D%0Aclass%20Foo%20implements%20IFoo%20%7B%0D%0A%09bar%20%3D%20true%3B%0D%0A%0D%0A%09mod()%20%7B%0D%0A%09%09this.bar%20%3D%20!this.bar%3B%0D%0A%09%09%2F%2F%20%20%20%5E%5E%5E%0D%0A%09%09%2F%2F%20%20%20expected%20error%3F%0D%0A%09%7D%0D%0A%7D%0D%0A%0D%0Anew%20Foo().bar%20%3D%20false%3B%0D%0A%2F%2F%20%20%20%20%20%20%20%20%5E%5E%5E%0D%0A%2F%2F%20%20%20%20%20%20%20%20expected%20error%3F%0D%0A%0D%0A)
**Expected behavior:**

I get errors for `Foo.bar` assignments

**Actual behavior:** 

I don't get errors

**Comment by aluanhaddad** [comment]
This is one of those sometimes counter intuitive subtyping things.
Consider
```ts
interface IFoo {
    readonly bar: boolean;
}
abstract class MutableFoo {
    abstract set bar(value:boolean);
}

class Foo implements IFoo, MutableFoo {
    bar = true;

    mod() {
        this.bar = !this.bar;
    }
}

new Foo().bar = false;
```
For comparison, in C# (.NET BCL) the following are defined (simplified) 
```C#
public interface IReadOnlyList<T>
{
    int Count { get; }

    T this[int index] { get; }
}

public class List<T>: IReadOnlyList<T>
{
    public int Count { get; }

    public T this[int index] { get; set; }
}
```

**Comment by RyanCavanaugh** [comment]
A mutable field is substitutable for a readonly field.
