### ISSUE TITLE
[Suggestion]: Add --strictReadonlyChecks option to catch runtime errors modifying frozen objects at compile time

### ISSUE THREAD

**Issue by paulkoerbitz** [Microsoft/TypeScript#11481]
**The Problem**
It is currently not possible to consistently catch modifications of frozen objects, which lead to runtime errors in strict mode. See #11180 and #11480 for examples. 

**Proposed Solution**
Add a `strictReadonlyChecks` compiler option, which does not allow to assign `readonly` fields to non-readonly (regular) fields. Also do not allow deleting items from readonly dictionaries (#11480), unless this can already be solved by regular compiler behavior.

**Comment by RyanCavanaugh** [comment]
Having this in any usable state would require a full set of variance and mutability annotations along with corresponding type operators -- a very large change. We're thinking about a future with some kind of variance / mutability annotations but won't be doing this as a one-off feature.

**Comment by DavidANeil** [comment]
I think there are 2 distinct things that I see in the issues referencing this one.
1. A need for a `readonly` member to not be assignable to a `readwrite` member.
2. A need for a `readwrite` member to not be assigned to a more inclusive type unless it is also marked as `readonly`.
Would it be reasonable to address these issues seperately?
