### ISSUE TITLE
"error TS2307: Cannot find module" when using @types/ws with typescript 2.0

### ISSUE THREAD

**Issue by zixia** [Microsoft/TypeScript#11491]
**TypeScript Version:**  

2.0.3

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
import * as WebSocket from 'ws'
const ws = new WebSocket('https://api.wechaty.io')
console.log('ws')
```

```shell
$ npm install @types/ws
wechaty@0.4.0 /Users/zixia/git/wechaty
└── @types/ws@0.0.34 

$ ./node_modules/.bin/tsc --target es6 t.ts
t.ts(1,28): error TS2307: Cannot find module 'ws'.
```

**Expected behavior:**

should found the type defination of `ws`

**Actual behavior:** 

TS2307 error

It's not like the problem from `@types/ws`, because if i use another module like `@types/express`, will be the same error.

BTW: if i run without es6 target, it will ok, but I can't use async/await

```shell
$ ./node_modules/.bin/tsc t.ts # will be ok
```

http://stackoverflow.com/questions/39960436/error-ts2307-cannot-find-module-when-using-types-ws-with-typescript-2-0

**Comment by jonrimmer** [comment]
You need to explicitly specify "node" module resolution strategy, as [the default](http://www.typescriptlang.org/docs/handbook/compiler-options.html) for ES6 target is "classic". E.g.

```
$ ./node_modules/.bin/tsc --target es6 --moduleResolution node  t.ts
```

**Comment by mhegazy** [comment]
Thanks @jonrimmer. this is the correct workaround for `typescript@2.0`. 

The issue has been fixed in `typescript@next` and should be part of `typescript@2.1`. Please see https://github.com/Microsoft/TypeScript/issues/11103 for more details.

**Comment by zixia** [comment]
@jonrimmer thanks! this cost my serval hours to study... and had not found any solution until read from your post. 

why tsc not to search @types by default?

**Comment by mhegazy** [comment]
as a mentioned, it is a bug, reproted in https://github.com/Microsoft/TypeScript/issues/11103, and fixed. sorry about the confusion. 

passing `--moduleResolution node` would address the issue.

**Comment by zixia** [comment]
@mhegazy got it. thanks!
