### ISSUE TITLE
Generic function argument inference differs between Visual Studio and tsc (2.0)

### ISSUE THREAD

**Issue by DavidKDeutsch** [Microsoft/TypeScript#11497]
Angular's .d.ts file has the following declaration:

``` ts
 interface IQService {
       all<T>(promises: IPromise<any>[]): IPromise<T[]>; 
 }
```

I augmented this by adding some typed overloads:

``` ts
 interface IQService {
       all<T>(promises: IPromise<any>[]): IPromise<T[]>; 
       //overloads below
       all<T>(promises: IPromise<T>[]): IPromise<T[]>;
       all<T1, T2>(promises: [IPromise<T1>, IPromise<T2>]): IPromise<[T1, T2]>;
       all<T1, T2, T3>(promises: [IPromise<T1>, IPromise<T2>, IPromise<T3>]): IPromise<[T1, T2, T3]>;
       all<T1, T2, T3, T4>(promises: [IPromise<T1>, IPromise<T2>, IPromise<T3>, IPromise<T4>]): IPromise<[T1, T2, T3, T4]>;
       all<T1, T2, T3, T4, T5>(promises: [IPromise<T1>, IPromise<T2>, IPromise<T3>, IPromise<T4>, IPromise<T5>]): IPromise<[T1, T2, T3, T4, T5]>;
 }
```

When I call one of these overloaded methods, whatever Visual Studio uses to determine which definition to use seems to pick the "correct" one (or at least what I would _like_ tsc to do):

``` ts
declare function foo(): IPromise<number>;
declare function bar(): IPromise<string>;
declare let $q: IQService;

let result = $.q.all([foo(), bar()]);
```

Visual Studio thinks that `result` is of type `IPromise<[number, string]>`, as I would hope. However, tsc.exe thinks it is of type `{}[]`. So Visual Studio is using my overloaded method declaration, whereas tsc.exe is using the original `all<T>(promises: IPromise<any>[]): IPromise<T[]>` and resolving `T` to `{}`. 

So I guess my 2 questions are:
1. Which one is by design? (I am hoping VS's behavior)
2. What is the best way to ensure VS is consistent with tsc.exe? 

I know the second question is not really a TypeScript question, so apologies for that; I figured I'd throw it out there just in case.

Thanks

**Comment by mhegazy** [comment]
> Which one is by design? (I am hoping VS's behavior)

Not sure what versions you are using, but it is important to note that overload resolution is order specific. so the order at which overloads are encountered by the compiler decides which ones it tries to match first, and the first matching overload is picked. 

The result is you want your most general overloads `all<T>(promises: IPromise<T>[]): IPromise<T[]>;` to be listed at the bottom of the list. and you want your `all<T1, T2, T3, T4, T5>(promises: [IPromise<T1>, IPromise<T2>, IPromise<T3>, IPromise<T4>, IPromise<T5>]): IPromise<[T1, T2, T3, T4, T5]>;` to be at the top.

Moreover, interface declarations do merge, so if this interface is defined in multiple files, make sure the order of the files passed to the compiler has your augmentation after the angualar.d.ts. You can find more [here](https://github.com/Microsoft/TypeScript/wiki/FAQ#how-do-i-control-file-ordering-in-combined-output---out-) about how to control the order of files passed to the compiler .

> What is the best way to ensure VS is consistent with tsc.exe?

Make sure you have the same version of both.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
