### ISSUE TITLE
[Errors] parser error recovery with comma in type member list

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#115]
```TypeScript
var s = $.extend< { workItem: any }, { workItem: any, width: string }>({ workItem: this._workItem }, {});
```

Expected: 

!!! ';' expected.!!! Cannot find name '$'.!!! Untyped function calls may not accept type arguments.

Actual: 

!!! Variable declaration expected.!!! ';' expected.!!! Declaration or statement expected.!!! Cannot find name '$'.!!! Cannot find name 'any'.!!! Cannot find name 'any'.!!! Cannot find name 'width'.!!! Cannot find name 'string'.

**Comment by DanielRosenwasser** [comment]
No longer a bug as per the change in #1969 that permits commas in object type literals.
