### ISSUE TITLE
Support module transformers

### ISSUE THREAD

**Issue by raix** [Microsoft/TypeScript#11502]
Proposal for adding support for transformation of non ts modules,

Example: a npm `typescript-css-module`, defining following module, idea:

`index.d.ts`
```ts
declare module "*.css" {
    // exposes the classnames definitions and transforms and adds the css
    // to the css bundle/file
    export default transformer 'index.ts';
}
```

`index.ts`
```js
  // css-module-transformer
  export default function(context: TransformationContext) {
    // parse the css file, make classnames uniq, add the css to a target css file
    // add source map files
    // and produce a ts file mapping classnames for type checking and autocomplete
  }
```

**Comment by mhegazy** [comment]
Why not have a tool that creates a `.d.ts` file given a `.css` and include this into your compilation?

**Comment by raix** [comment]
@mhegazy that might be the best to use something like `typed-css-modules`, keeping tsc strictly for ts

The initial idea was to avoid all the setup of webpack/loaders etc. being able to compile modules without to much hassle. I'll close this as not relevant

**Comment by mohsen1** [comment]
This is actually a great proposal! Using [typed-css-modules with webpack](https://github.com/olegstepura/typed-css-modules-loader/pull/8) hasn't been easy. 

TypeScript compiler emits JS files, it would be awesome if we could hook into module loading and provide type definition to compiler for non-TS files for autocomplete etc and in compile time we emit non-JS files. 

I love to use TypeScript compiler to do things I do with Webpack. I wish TypeScript had APIs to enable doing stuff like this.
