### ISSUE TITLE
Built-in type declaration for XMLHttpRequest is missing a readonly property 'responseURL'

### ISSUE THREAD

**Issue by quyin** [Microsoft/TypeScript#11510]
**TypeScript Version:**  2.0.3

**Code**

``` ts
let xhr = new XMLHttpRequest();
console.log(xhr.responseURL);
```

**Expected behavior:**

The compiler should be able to compile the code without errors.

Here is the [MDN documentation for this property](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/responseURL).

**Actual behavior:** 

`tsc` complains:

```
error TS2339: Property 'responseURL' does not exist on type 'XMLHttpRequest'.
```

**Comment by kitsonk** [comment]
These typings come from [TSJS-lib-generator](https://github.com/Microsoft/TSJS-lib-generator) where contributions are greatly welcomed.

**Comment by quyin** [comment]
@kitsonk Thanks for the information!
