### ISSUE TITLE
TSServer: what is the difference between ChangeRequest and ApplyChangedToOpenFilesRequest

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#11515]
**TypeScript Version:**  2.0.6-Insider

Why does the new request `ApplyChangedToOpenFilesRequest` exist. Couldn't this be done using the old Open, Change, Close notifications. Having this new request is very confusing.

**Comment by dbaeumer** [comment]
@mhegazy @vladima might be something to consider before you make the new protocol final. If it is in it will be hard to change afterwards.

**Comment by vladima** [comment]
This command is not the part of the protocol and thus is hidden
