### ISSUE TITLE
tsx formatter indents the closing bracket

### ISSUE THREAD

**Issue by MastroLindus** [Microsoft/TypeScript#11513]
**TypeScript Version:**  stable 2.0.3

I am using a tslint rule shipped by palantir for checking tsx/jsx alignment, https://github.com/palantir/tslint-react.
The rule states that the closing bracket of an element should be aligned with the opening bracket, and I would argue that it is a sensible default for multiline tsx declarations.
However the tsx formatter at the moment is indenting the closing bracket as well, and it breaks the rule.

**Code**
Example with two divs (one self closing, one not)

``` ts
<div
    id="test"
/>
<div
    id="test2
>
</div>
```

**Expected behavior:**
after format:

``` ts
<div
    id="test"
/>
<div
    id="test2"
>
</div>
```

**Actual behavior:** 
after format:

``` ts
<div
    id="test"
    />
<div
    id="test2"
    >
</div>
```

**Comment by SaschaNaz** [comment]
Covered by #13092.

**Comment by mhegazy** [comment]
thank @SaschaNaz !
