### ISSUE TITLE
TSServer: how does canncelation work in 2.0.6

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#11524]
**TypeScript Version:**  2.0.6-insider

You mentioned that 2.0.6 will contain cancelation support. I haven't found any hint about cancelation in the protocol.d.ts. Can you please add corresponding documentation.

**Comment by vladima** [comment]
I've added a [page](https://github.com/Microsoft/TypeScript/wiki/Cancellation-Support-in-tsserver) in the wiki, please let me know if you need anything to be clarified

**Comment by dbaeumer** [comment]
I read the wiki. Thanks! I have one additional questions: if we have only one pipe name how do I know when to close the pipe again. When I receive the response of a request the tsserver could already work on another request and assuming it needs to cancel that request.

**Comment by vladima** [comment]
In VS case all requests are serialized so I always can close the pipe before sending next request. I'm not very familiar with VSCode codebase to tell if similar approach is applicable there - we can discuss it at the next sync up

**Comment by dbaeumer** [comment]
We do serialize request but not notifications. The most wanted tasks I want to cancel is the 'geterr' notification. Would this be possible ?

**Comment by vladima** [comment]
I have a proposal how it can be resolved in #11580

**Comment by dbaeumer** [comment]
I like the proposal.

**Comment by mhegazy** [comment]
This should be in TS 2.1.4 already.
