### ISSUE TITLE
File name completion returns strange results

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#11521]
**TypeScript Version:** 2.0.6-insider

tsconfig.json
```json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5"
    }
}
```
provide.ts
```ts
export class A {
    constructor() {
        let a: string;
        let c: number;
    }
}
```
consume.ts
```ts
import { A } from './p<request code assist here>';
```

The return result from code assist contains one entry:

![capture](https://cloud.githubusercontent.com/assets/1931590/19267647/2ffc30a8-8fb0-11e6-8a88-0690eeac10a5.png)

which is not what I would expect. I expect an entry for provide.

**Comment by dbaeumer** [comment]
It throws an exception when requesting code assist here:

```ts
import { A } from '.<request code assist here>';
```

The exception is

"Error processing request. Cannot read property 'length' of undefined\
TypeError: Cannot read property 'length' of undefined\n    at getCompletionEntriesFromTypings (p:\\mseng\\VSCode\\vscode\\extensions\\typescript\\node_modules\\typescript\\lib\\tsserver.js:48138:79)\n    at getCompletionEntriesForNonRelativeModules (p:\\mseng\\VSCode\\vscode\\extensions\\typescript\\node_modules\\typescript\\lib\\tsserver.js:48017:17)\n    at getStringLiteralCompletionEntriesFromModuleNames (p:\\mseng\\VSCode\\vscode\\extensions\\typescript\\node_modules\\typescript\\lib\\tsserver.js:47908:31)\n    at getStringLiteralCompletionEntries (p:\\mseng\\VSCode\\vscode\\extensions\\typescript\\node_modules\\typescript\\lib\\tsserver.js:47812:28)\n    at Object.getCompletionsAtPosition (p:\\mseng\\VSCode\\vscode\\extensions\\typescript\\node_modules\\typescript\\lib\\tsserver.js:47696:24)\n    at IOSession.Session.getCompletions (p:\\mseng\\VSCode\\vscode\\extensions\\typescript\\node_modules\\typescript\\lib\\tsserver.js:54825:64)\n    at Session.handlers.ts.createMap._a.(anonymous function) (p:\\mseng\\VSCode\\vscode\\extensions\\typescript\\node_modules\\typescript\\lib\\tsserver.js:54081:61)\n    at IOSession.Session.executeCommand (p:\\mseng\\VSCode\\vscode\\extensions\\typescript\\node_modules\\typescript\\lib\\tsserver.js:55131:28)\n    at IOSession.Session.onMessage (p:\\mseng\\VSCode\\vscode\\extensions\\typescript\\node_modules\\typescript\\lib\\tsserver.js:55151:35)\n    at Interface.<anonymous> (p:\\mseng\\VSCode\\vscode\\extensions\\typescript\\node_modules\\typescript\\lib\\tsserver.js:56206:27)"

**Comment by aozgaa** [comment]
I'm having trouble reproducing either problem using commit
4ccb3bb75c11b8c39899f4f4a23aa1ef6102c712
of typescript (building and using the corresponding tsserver), and commit
52690ed9045a67619dffaefbf1a438c81c3730de
of vscode. I tried on both Win10 and Ubuntu 16.04.

In the first case, the completions returned by tsserver are 
![selection_001](https://cloud.githubusercontent.com/assets/3226984/19330846/ab891386-9095-11e6-9d35-ba1d437044ef.png)

and in the latter it appears no completions are returned (but I'm unable to reproduce the exception). At that paint, the user hasn't typed enough to tell us whether the module completion they are looking for is relative or non-relative. we currently assume it is non-relative, and so don't find any completions.
(if you think this is problematic behavior, ie that we should offer some completions in this latter case, open a new issue referencing this one).

If you are still seeing the issue using the latest versions of both, please let me know.

**Comment by dbaeumer** [comment]
I saw this on 2.0.6-insider. @mhegazy if it is easy to backport this would be something cool to have in 2.0.6
