### ISSUE TITLE
TSServer: how does compile on save work in 2.0.6

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#11526]
**TypeScript Version:**  2.0.6-insider

I looked at the requests and it looks like that clients are responsible to trigger compile from the outside. My understanding is the following assuming that file a.ts changed.
- we sent a CompileOnSaveAffectedFileListRequest request
- we receive a response telling us that we have to recompile n files
- we sent n CompileOnSaveEmitFileRequest to the server.

If this is true then basically the client now implements a builder queue to make this performant. This is especially true if compileOnSave goes with auto save. 

And how should I use the force flag. If a file requires n files to be recompiled do I have to call these n files with force= true. The files are usually unchanged.

**Comment by dbaeumer** [comment]
@mhegazy @vladima can you please clarify this.

**Comment by dbaeumer** [comment]
One addition question: how would we find out if compileOnSave is enabled on a specific project. Currently we don't actively monitor project info or tsconfig.json file. Would we need to do so to find out if a certain file needs to be compiled on save or is this something CompileOnSaveAffectedFileListRequest would take into consideration by reporting no files or by signaling this otherwise.

**Comment by mhegazy** [comment]
> Would we need to do so to find out if a certain file needs to be compiled on save or is this something CompileOnSaveAffectedFileListRequest would take into consideration by reporting no files or by signaling this otherwise.

The `CompileOnSaveAffectedFileListRequest` should return an empty list for projects that do not support compile-on-save.

**Comment by mhegazy** [comment]
> If this is true then basically the client now implements a builder queue to make this performant. This is especially true if compileOnSave goes with auto save.

It is not a builder queue, it is just a request queue. The server is single threaded, and can only cancel one request at a time. this allows the client to cancel the request and restart it as needed.

**Comment by dbaeumer** [comment]
I used the term builder queue since it is somehow strange to compile a TS file to JS without doing a syntax and semantic check as well. Consider the case where you save a file a.ts which causes a compile error in a file b.ts which could result in exceptions when executing b.js. I as a user would expect that if we write b.js we inform the user of potential problems in b.js as well. 

Wouldn't it make more sense the server does this. It is a lot of traffic for something the server can implement a lot better.

**Comment by mhegazy** [comment]
Sure. But not for this release.

**Comment by movedoa** [comment]
any news on this?

**Comment by sherwopj** [comment]
+1 compileOnSave: seeing the effects of my bungling on closed files would be marvellous

**Comment by angelozerr** [comment]
I'm implementing compile on save inside Eclipse, it starts working but I have a question when tss files have some errors. 

Imagine you have a `a.ts `file like this:

```typescript
export let PI = 3.14;
```

and a `b.ts` file like this:

```typescript
import {PI} from "./a"
console.log(PI)
```

In other words `b.ts` depends on `a.ts`.

Now I changed `a.ts` like this:

```typescript
export let PIXXXXXXXXXXXXXX = 3.14;
```

and I save the file.

The uses of `CompileOnSaveAffectedFileListRequest` tell me that  `a.ts`  and  `b.ts` must be compiled. That's cool. But I need to mark  `b.ts` file with errors (even if it is not opened). So today I don't know how to manage that. My idea is to try to execute `geterrForProject`  at the end of the compile on save but I'm not sure that it's the clean mean.

I tell me if CompileOnSaveEmitFileRequest  could returns diagnostic?

**Comment by movedoa** [comment]
ping for status on this, can we expect this in the near future?

**Comment by mhegazy** [comment]
>  But I need to mark b.ts file with errors (even if it is not opened). So today I don't know how to manage that. My idea is to try to execute geterrForProject at the end of the compile on save but I'm not sure that it's the clean mean.

Why are errors relevant here? Compile on Save should honor `--noEmitOnError`.

**Comment by mhegazy** [comment]
> ping for status on this, can we expect this in the near future?

@movedoa  not sure i understand what you are looking for

**Comment by movedoa** [comment]
@mhegazy Oh sry if that wasn't clear.
In https://github.com/Microsoft/vscode/issues/7015 @dbaeumer said this is the bug to track for compile on save in visual studio code, since there is work to be done in tsserver before this can be implemented.

**Comment by Ciantic** [comment]
I was following this too, not as a Question but as a bug/feature I expected to be fixed. Is that not the case?

**Comment by mhegazy** [comment]
It is a question, and i believe it has been answered. From an tsserver API perspective, CoS is implemented already. if you have any issues with the API please file a new issue.

**Comment by dbaeumer** [comment]
@mhegazy whe referring to CoS are you referring to a builder or to the CoS API to implement a builder in VS Code itself. As we discussed in various other situations implementing a builder in VS Code simply using the CoS API to travers the dependencies is not very efficient.

**Comment by movedoa** [comment]
Since this is now closed what is the appropriate bug to follow for compileonsave in vsc?
