### ISSUE TITLE
Faulty emit for union type of arrays

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/TypeScript#11527]
**TypeScript Version:**  2.0 RTM

**Code**

```ts

const  foo = [] as any | [''];
```

**Expected behavior:**
The emit should be the following:
```js
var foo = [] | [''];
```

**Actual behavior:** 

The actual emit is
```js
var foo = [];
```

This was actually an accident, I meant to write `const  foo = <getArray()> as any || [''];` where the left-hand array could be null. I had accidentally left out a pipe.

There should have been a runtime error at least.

**Comment by ahejlsberg** [comment]
The `as` operator expects a type as the right hand operand, and `any | ['']` is indeed a type. You need to add parentheses to get the expected behavior: `([] as any) | ['']`.

**Comment by NoelAbrahams** [comment]
@ahejlsberg, it's the emit that's the problem.

**Comment by NoelAbrahams** [comment]
I see what's going on. Thanks.
