### ISSUE TITLE
Question regarding UseOneInferredProject

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#11523]
**TypeScript Version:**  2.0.6-insider

I have a question regarding this setting. If enable will js and ts files end up in one project. Or will you create two different inferred projects. Will it depend on the `allowJs` setting.

**Comment by vladima** [comment]
it will put all loose files into one inferred project

**Comment by dbaeumer** [comment]
Thanks. Let continue in https://github.com/Microsoft/TypeScript/issues/11554
