### ISSUE TITLE
"Number" error

### ISSUE THREAD

**Issue by SergeShkurko** [Microsoft/TypeScript#11528]
**TypeScript Version:**  2.0.3

**Code**

```ts
class TestNumber {
	
  private _Number: Number = 1;
  private _number: number = 1;
  
  public constructor () {
    this.calculate_Number(); // Error :(
    this.calculate_number(); // Normal
  }
  
  private calculate_Number() {
  	this._Number += 1;
  }

  private calculate_number() {
  	this._number += 1;
  }
  
}

new TestNumber();

```

How use "Number" as type ?

**Comment by mhegazy** [comment]
> How use "Number" as type ?

`Number` is the boxed version of `number`. it is an object. for all practical purposes you should not use `Number`.

**Comment by mhegazy** [comment]
you can find more details on `Number` in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number

**Comment by RyanCavanaugh** [comment]
http://stackoverflow.com/questions/15487220/typescript-primitive-types-any-difference-between-the-types-number-and-numbe
