### ISSUE TITLE
Error "Operator '===' cannot be applied to types" with enum type

### ISSUE THREAD

**Issue by pltnkv** [Microsoft/TypeScript#11533]
**TypeScript Version:**  2.0.3

**Code**

```ts
enum SomeEnum {
    V1,
    V2
}

class SomeClass {
    protected state:SomeEnum

    method() {

        // "Operator '===' cannot be applied to types 'SomeEnum.V1' and 'SomeEnum.V2'." error here
        this.state = SomeEnum.V1
        if (this.state === SomeEnum.V2) {
        }        

        // and the same error here
        if (SomeEnum.V1 === SomeEnum.V2) {
        }

        // but no error here
        let state2 = SomeEnum.V1
        if (state2 === SomeEnum.V2) {
        }
    }
}

```

**Expected behavior:**
I didn't expect that error in these cases

**Comment by ahejlsberg** [comment]
The errors are actually the intended behavior. In the first example the compiler knows that `this.state` has the value `SomeEnum.V1` and therefore the comparison will always be false. The second example is just another way of demonstrating that. The third example actually *should* be an error and *is* an error in the nightly builds (see #10676 for more detail on what changed here).

**Comment by psulek** [comment]
@ahejlsberg so how to properly compare enum values? Such change broke our existing code using TS < 2.x.

**Comment by ahejlsberg** [comment]
@psulek You shouldn't have to change anything. If something broke in your code, the compiler is likely pointing out something suspicious. Can you send a repro of what you're seeing?

**Comment by psulek** [comment]
Maybe it has something to do with generators/yield.

Sample:

```
export enum State {
    Unknown,
    Initializing,
    InitFailed,
    InitSuccess
}

class Processor {
    engineState: State;

    public * initializeAsync(): Iterable<boolean> {
        this.engineState = State.Initializing;

        try {
            // yield some action
            // yield <any>this.verifyAsync();
            this.engineState = State.InitSuccess;
        } catch (err) {
            this.engineState = State.InitFailed;
        } finally {
            return this.engineState === State.InitSuccess;
        }
    }
}
```

Save file as "ts-enums.ts" and compile with:

`tsc ts-enums.ts -t ES2015`

And you got error:

`error TS2365: Operator '===' cannot be applied to types 'State.Initializing' and 'State.InitSuccess'`

Typescript version: 2.0.3

**Comment by huyph** [comment]
I encountered the similar error, and have no idea on how I can make the following work:
```javascript
export enum SortOrder {
  NONE,
  ASC,
  DESC
}
....
  public sort(array: any[], order: SortOrder): any[] {
    if (order && order !== SortOrder.NONE) {
       // do nothing
    } else {
        // sort
    }
```

Typescript gives me an error on the `if` condition as follows: 

`Operator '!==' cannot be applied to types 'SortOrder.ASC | SortOrder.DESC' and 'SortOrder.NONE'.`

**Comment by vladima** [comment]
enum values starts with `0` so in your code `SortOrder.NONE` will have numeric value `0`. First part of the check `order && order !== SortOrderNone` already rules out falsy values so second part `order !== SortOrder.NONE` effectively becomes useless since it is always true

**Comment by huyph** [comment]
Ah cheers @vladima

**Comment by psulek** [comment]
@vladima As you are right, such compile error is bug. When enum member is represented by number i should be able to compare number type with === or !===

**Comment by effzeh** [comment]
I'm getting the same error with the following code (`tsc version 2.1.5`)

    enum Token { eof, ok }

    class Parser {
        pos: number = 0;
        tok: Token = this.lex();

        lex(): Token {
            if (this.pos >= 100)
                return Token.eof;
            ++this.pos;
            return Token.ok;
        }

        next(): void {
            this.tok = this.lex();
        }

        parse(): boolean {
            if (this.tok === Token.eof)
                return true;

            // no error...
            // this.tok = this.lex();

            // ERROR in the return statement below
            this.next();

            return this.tok === Token.eof;
        }
    }

I just started learning JavaScript/TypeScript, so it's very likely I'm missing something, but that this code works in one case and not in the other just doesn't seem right to me. (This is a reduced test-case from a port of a small C++ JSON parser to TypeScript. The generated JS code for the larger parser works as intended.)

**Comment by RyanCavanaugh** [comment]
@effzeh somehow this issue hasn't linked to #9998 yet, but see the first example there. Short answer: add a type assertion, or change `tok` to `getToken()`

**Comment by ocombe** [comment]
In my case I used a switch instead of if/else, it worked without any error.

**Comment by jameelvm** [comment]
I am facing the same issue when I compare enum value to a string 
```
 export enum Widget {
    ICONWIDGET = "IconWidget",
};
```
```
 getWidgetComponent(componentName:string) {

          if(componentName ===  Widget.ICONWIDGET){
              return IconWidgetComponent;
          }
  }
```
i am getting runtime error '===' cannot be applied to types 'string' and 'Widget'.  how can I resolve this?

**Comment by jameelvm** [comment]
I Resolved by my issue by upgrade the typescript version from 2.1.4 to 2.4.1
https://stackoverflow.com/questions/45068473/cannot-be-applied-to-types-string-and-enum-string-value

**Comment by Cerebellum90** [comment]
Maybe this helps someone; In my case I was accidentally having the same comparison in a *nfIg. 
E.g.:
`*ngIf="a != b && a != b"`

**Comment by afroozeh** [comment]
I am getting the error "Operator '!==' cannot be applied to types" in the comparison with enums, but not with integer values:

```
enum E {
    A,
    B, 
    C,
    D
}

let x: E

if (x !== E.A || x !== E.B || x !== E.C) {

}

if (x !== 0 || x !== 1 || x !== 2) {

}
```

Aren't these two examples equivalent? What is the cause of the error?

**Comment by jtlapp** [comment]
I believe the following code is valid, but TS tells me `Operator '===' cannot be applied to types 'MyEnum.Constant1' and 'MyEnum.Constant2`:

```
enum MyEnum { C1, C2 };

function test(features: string[]): void {
    let myValue = MyEnum.C1;
    
    features.forEach(feature => {
        if (feature === 'X') {
            myValue = MyEnum.C2;
        }
    });
    if (myValue === MyEnum.C2) { // ERRORS HERE
        console.log("Got C2");
    }
}
```

If I instead change `test()` to the following, the error goes away:

```
function test(features: string[]): void {
    let myValue = MyEnum.Constant1;
    
    for (let i = 0; i < features.length; ++i) {
        if (features[i] === 'X') {
            myValue = MyEnum.C2;
        }
    }
    if (myValue === MyEnum.C2) { // NO ERROR
        console.log("Got C2");
    }
}
```

Is this desired behavior?

**Comment by RyanCavanaugh** [comment]
@mkoutroupis Your code 100% has a bug in it. If `status` was `SubmittedForApproval`, then it is certainly `!== PendingChange` and you would not be testing the condition of the `else`.

**Comment by mkoutroupis** [comment]
Yes you are right but still the error is the same whether it's an if or else if statement.

**Comment by RyanCavanaugh** [comment]
Please post a usable repro

**Comment by mkoutroupis** [comment]
@RyanCavanaugh you can download the sample application from here: https://github.com/mkoutroupis/TestTypescript

**Comment by RyanCavanaugh** [comment]
@mkoutroupis again see #9998
