### ISSUE TITLE
macros (AST rewriters)

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#11536]
situation:
- sometimes i wish i could generate a piece of code based on some existing one, for example a construction function for an given interface

   ```typescript
   interface MyConfig {
       name: string;
       values: number[];
   }
   function myConfigFrom(name: string, values: number[]) : MyConfig {
       return { name, values };
   }
   ```

problem: currently my options are
- either write it by hands (tedious monotonous work)
- put together a homemade code generator and run it as a pre-build step (lot of maintenance, non-standard)

solution:
- allow AST rewrites via decorators

   ```typescript
   @rewrite(addContructorFunction)
   interface MyConfig {
       name: string;
       values: number[];
   }
   function addContructorFunction(node: ts.Node): ts.Node[] {
       return [node, toConstructorFunction(node as ts.InterfaceDeclaration)];
   }
   function toConstructorFunction(node: ts.IntefaceDeclaration): ts.FunctionDeclaration {
       // fun stuff goes here
   }
   ```

**Comment by sandersn** [comment]
This is a duplicate of #4892, although with a decorator mechanism instead. Can you add your proposal to that discussion instead?

**Comment by aleksey-bykov** [comment]
ok

**Comment by sandersn** [comment]
Also a little like #2900, except with that idea you'd still have to write your own code generator.
