### ISSUE TITLE
Renaming property with space

### ISSUE THREAD

**Issue by wallverb** [Microsoft/TypeScript#11531]
Not sure if VSCode or TSServer issue:

```ts
interface Test {
    "alpha beta": string
}

const a : Test = {
    "alpha beta": "test"
}
```

Put cursor inside `beta` of interface and rename with F2

![image](https://cloud.githubusercontent.com/assets/1723815/19276731/574b9eba-8fa5-11e6-855a-6dc10a0d29f1.png)

Box to rename shows only `beta` - shall it show `alpha beta` ?

Rename to `beta2`

Result:

![image](https://cloud.githubusercontent.com/assets/1723815/19276764/73d7bafa-8fa5-11e6-9f84-f3cab654002f.png)

Should be `alpha beta2`

**Comment by basarat** [comment]
VSCode issue. 

e.g. works fine in [alm](http://alm.tools/) :rose: 

![rename string](https://cloud.githubusercontent.com/assets/874898/19298575/5cfa4776-909a-11e6-849f-3e61918f7c1c.gif)
