### ISSUE TITLE
TSServer: useOneInferredProject not working as expected

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#11530]
**TypeScript Version:**  2.0.6-insider

I configure the tsserver as follows:

```ts
		let configureOptions: Proto.ConfigureRequestArguments = {
			hostInfo: 'vscode',
			useOneInferredProject: true
		};
		this.execute('configure', configureOptions);
		let compilerOptions: Proto.ExternalProjectCompilerOptions = {
			module: Proto.ModuleKind.CommonJS,
			target: Proto.ScriptTarget.ES5,
			allowJs: true,
			allowSyntheticDefaultImports: true
		};
		let args: Proto.SetCompilerOptionsForInferredProjectsArgs = {
			options: compilerOptions
		}
		this.execute('compilerOptionsForInferredProjects', args);
```
In the following setup where both files are in the same directory and no tsconfig.json file exists:

consume.ts
```ts
class B {
}
```

provide.ts
```ts
export class AAAAAAAA {
}
```

I expect after having consume.ts and provide.ts opened in the tsserver that a request to workspace symbols contains `AAAAAAAA` as a result. But it doesn't.

**Comment by vladima** [comment]
sorry this was a mismatch in the protocol - currently we don;t support changing this property dynamically so it is set as a [command line argument](https://github.com/Microsoft/TypeScript/blob/release-2.0.5/src/server/server.ts#L514) to tsserver.js. I'll remove it from the `protocol.d.ts`

**Comment by dbaeumer** [comment]
@vladima can you please document the command line argument.

**Comment by dbaeumer** [comment]
...and will `compilerOptionsForInferredProjects` still work ?
