### ISSUE TITLE
Generating super(...arguments) in constructor

### ISSUE THREAD

**Issue by yulianovdey** [Microsoft/TypeScript#11543]
Hello!

MR #10189 is causing an issue after I compile TypeScript with `target` set to `es6` and run it through Babel using `babel-preset-es2015-node4`.

You can find a repro [here](https://github.com/yulianovdey/ts-empty-constructor). Test by running `npm i && npm run compile && node dist/test.js`. To summarize, the following code:

```javascript
abstract class Base {
  public abstract myProperty: string;
}

class Child extends Base {
  myProperty = 'A value';
}
```

Results in an error:

```
super(...arguments);
      ^^^
SyntaxError: Unexpected token ...
```

Caused by the fact that spread is still being used in the constructor:

```javascript
class Child extends Base {
    constructor() {
        super(...arguments);
        this.myProperty = 'A value';
    }
}
```

Not touching `arguments` is [deliberate behavior on Babel's part](https://github.com/babel/babel/blob/3667527d04ed13a3df6298cf136e9fd87b773602/packages/babel-plugin-transform-es2015-spread/src/index.js#L3), so I'm wondering if there is a way to make the change in #10189 more compatible with Node 4 without having to transpile to es5.

**Comment by DanielRosenwasser** [comment]
@kittens @chancancode - I'm not sure why `arguments` is specifically not being touched here.

**Comment by mhegazy** [comment]
this is valid ES6 code. spread operator is allowed on arguments as well. not sure how transforming the rest of the ES6 expressions but leaving `...arguments` would be ok.

https://github.com/Microsoft/TypeScript/issues/10175 was mainly done to address emit quality for babel. i will let @chancancode reply.

**Comment by chancancode** [comment]
Yes, it is valid ES6 code.

Since Babel has the ability to parse/compile that down to ES5 (meaning it understands the native syntax, and knows what to do if it decides the target platform doesn't support the native syntax), it seems like a bug in the babel-preset-es2015-node4 preset?

**Comment by yulianovdey** [comment]
Thank you for your input guys. I found a relevant issue that was opened with Babel, maybe someone can provide more info there.

**Comment by yulianovdey** [comment]
I was able to get some clarification on the Babel Slack. Using`transform-es2015-classes` seems to a requirement in this case because `super` is not a function and requires native spread.

Thanks again!
