### ISSUE TITLE
@types is still broken for rx-lite

### ISSUE THREAD

**Issue by jonrimmer** [Microsoft/TypeScript#11555]
**TypeScript Version:**  next (2.1.0-dev.20161012)

The problems I raised in #9725 are still present. TypeScript 2 still refuses to recognise the "rx-lite" module declared by "@types/rx".

**Code**

```
npm init
npm install typescript@next rx @types/rx --save
```

**tsconfig.json**

``` ts
{
  "compilerOptions": {
    "module": "es6",
    "target": "es5",
    "moduleResolution": "node",
    "types": [
      "rx"
    ]
  },
  "files": [
    "import-rx-lite.ts"
  ],
  "exclude": [
      "node_modules"
  ]
}
```

**import-rx-lite.ts**

``` ts
import * as Rx from 'rx-lite';
```

```
./node-modules/.bin/tsc
```

**Expected behavior:**

It should work.

**Actual behavior:** 

```
import-rx-lite.ts(1,16): error TS2307: Cannot find module 'rx-lite'.
```

**Example Project**

https://github.com/jonrimmer/ts-types-bug

**Comment by jonrimmer** [comment]
The published @types/rx package contains a ```types-metadata.json``` file with a ```declaredModules``` collection that includes ```"rx-lite"```. So why doesn't TypeScript recognise this module, even when the "rx" types are explicitly referenced via ```tsconfig.json```?

Does TypeScript even pay attention to ```types-metadata.json```? Is the format documented anywhere? Is the types-2.0 definition resolution process documented anywhere? Is there any documentation on how to write a types-2.0 compliant type definition? Is there any documentation on how to author definitions that contain multiple modules?

**Comment by kitsonk** [comment]
[`--traceResolution`](https://www.typescriptlang.org/docs/handbook/compiler-options.html) will help you understand what TypeScript is doing when trying to resolve types for a module.

**Comment by jonrimmer** [comment]
@kitsonk Thanks for the tip. Unfortunately the output isn't too useful in this case. It makes it clear that TypeScript is trying to resolve "rx-lite" by looking in the standard places—```@types/rx-lite```—and failing, but it doesn't tell me anything about how it should resolve it when its contained in a non-standard place—```@types/rx```

**Comment by jonrimmer** [comment]
My findings:

 - ```types-metadata.json``` seems to be equivalent to the ```definitions.json``` talked about in the [types-publisher](https://github.com/Microsoft/types-publisher) documentation. Despite it being included in the definition npm package and including all the relevant data, it doesn't look like TypeScript actually uses it for resolution purposes. So it seems it's a red herring.

 - Types-2.0 packages have the concept of an "entry" definition, which is usually called ```index.d.ts```. This is the definition that will end up being set in the ```typings``` field of the ```@types/whatever/package.json```. All packages in ```node_modules/@types``` will be "visible" by default, but this just means their entry definition is included. Any other definition files in the package will be ignored, unless they're referenced by the entry definition file.

  This is what is wrong with the definitions in ```@types/rx```. There are a bunch of additional module declarations, but none of them are referenced by ```index.d.ts```. It *does* reference a file called ```rx-lite.d.ts```, but this doesn't actually define the rx-lite module, a different file called ```rx.lite.d.ts``` does.

 - The ```compilerOptions.types``` field in ```tsconfig.json``` is supposed to be a way to *restrict* which packages in ```node_modules/@types``` are visible by default, but you can abuse it to load specific files within a package that wouldn't otherwise be found, although you have to be careful of some issues with the path lookup strategy. A full filename will not work, because TypeScript will always append a ".ts" to it:

  ```json
  types: [
    "rx/rx.lite.d.ts"
  ]
  ```

  But this will:

  ```json
  types: [
    "rx/rx-lite.d"
  ]
  ```

  And, because the ```types``` field is really intended to restrict which packages from ```node_modules/@types``` are automatically visible, you'll have to also include any additional packages that you want visible, e.g. those containing global declarations.

**Comment by jonrimmer** [comment]
It seems there is an [undocumented](http://www.typescriptlang.org/docs/handbook/triple-slash-directives.html) triple-slash reference feature where you can specify the attribute "types" instead of "path" and TypeScript will try to load it using the 

You can combine this with my earlier finding about referencing package contents in order to include a file within a types package that wouldn't be included by default, or found by the regular package lookup algorithm:

```ts
/// <reference types="rx/rx.lite">
import * as Rx from 'rx-lite';
```

**Comment by mhegazy** [comment]
The declaration files under https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types-2.0/rx should be split into other packages, e.g.: `rx-lite`, `rx-lite-aggregates-compat`, `rx-lite-angular`, `rx-lite-angular-compat`, `rx-lite-async`, `rx-lite-async-compat`, `rx-lite-backpressure`, `rx-lite-backpressure-compat`, `rx-lite-coincidence`, `rx-lite-coincidence-compat`, `rx-lite-compat`, `rx-lite-dom`, `rx-lite-dom-ajax`, `rx-lite-dom-ajax-compat`, `rx-lite-dom-compat`, `rx-lite-dom-concurrency`, `rx-lite-dom-events`, `rx-lite-dom-events-compat`, `rx-lite-dom-html`, `rx-lite-experimental`, `rx-lite-experimental-compat`, `rx-lite-extras`, `rx-lite-extras-compat`, `rx-lite-joinpatterns`, `rx-lite-joinpatterns-compat`, `rx-lite-testing`, `rx-lite-testing-compat`, `rx-lite-time`, `rx-lite-time-compat`, `rx-lite-virtualtime`, `rx-lite-virtualtime-compat`

**Comment by mhegazy** [comment]
Should be fixed with https://github.com/DefinitelyTyped/DefinitelyTyped/pull/13652.
