### ISSUE TITLE
TSX in custom UI builder

### ISSUE THREAD

**Issue by PanayotCankov** [Microsoft/TypeScript#11556]
I have a class hierarchy such as:

``` TypeScript
class View {
  id: string;
}
class Button {
  text: string;
}
class Page {
  header: string;
}
```

I am using TSX to define UI using these classes. I ended up wiring everything up successfully but to enable type checking I now need type properties such as:

``` TypeScript
interface ViewProps {
  id?: string;
}
interface View {
  props: ViewProps;
}
interface ButtonProps extends ViewProps {
  text?: string;
}
interface Button {
  props: ButtonProps;
}
interface PageProps exnteds ViewProps {
  header?: string;
}
interface Page {
  props: PageProps;
}
```

I simply don't want to repeat myself so is there any way to let the type checking actually use the types of the classes and have optional `props` only for special cases? I know I can change the props name, I event tried to use something like `typeof Button.prototype` as `props` value for the `Button` class, but then all properties were mandatory within the TSX attributes, and I still needed to declare it for each class.

A second lesser bummer is my views are treated differently when in certain context. Consider the XAML-like:

``` XML
<ListView>
  <ListView.itemTemplate>
    <Button text="{{ special binding syntax }}" />
  </ListView.itemTemplate>
</ListView>
```

My problem is Button will return Button instance if I just instantiate the first argument in createElement. I need the content of ListView.itemTemplate to return a factory function instead. The type checking remains the same. Yet the top level ListView should return an instance of the ListView. So I end up needing additional context within createElement. For me it would be best if I could make tsc emit:

``` TypeScript
MyUIBuilder.createTree([ListView, null, [
  [ListView.itemTemplate, null, [
    [Button, { text: "{{ special binding syntax }}"}]
  ]]
]]
```

Or if somehow the child createElement calls could get context from parent createElement calls, this would still require the elements to be created top-down instead of bottom-up though.

I don't have hopes for you to do any actual work on that, I just hope I am missing something that may help for these 2 things.

P.S. TypeScript 2+ is awesome, and down compilation to ES5 for async/await is great!

**Comment by PanayotCankov** [comment]
This works almost perfectly:
```
class View {
    props: Partial<this>;
}
```
Only the docs are lost :( Is there a way to make the Partial<this> keep the property descriptions (from the /** */ comments) and the "go to definition"?

**Comment by RyanCavanaugh** [comment]
This is already supported - all you need to do is define the JSX namespace correctly. Declare the interface `JSX.ElementAttributesProperty` with zero properties and the properties of the class will become the attributes of the corresponding JSX elements.

**Comment by PanayotCankov** [comment]
@RyanCavanaugh, thanks for your time, but then they are all required the way you describe. Our View class has a lot of properties (width, height, minWidth, minHeight, transform, etc.) and adding ElementAttributesProperty without properties is something I tried, but the end result is TSX that is not very usable in our case. The user early declare more than 3-4 of the View properties. Can you give this repository a try:
https://github.com/PanayotCankov/tsx-props

The 'width' property on View will display properly tooltip `View width.` when you type it on the View element in index.tsx, but all properties of the class are required attributes. I need them to be optional, but preserve the `View width.` tooltip.

**Comment by RyanCavanaugh** [comment]
Classes can have optional properties.

**Comment by PanayotCankov** [comment]
All properties on our classes should become optional even the methods. If I have `addToView(): void;` on the View class it becomes required attribute on the <View /> element so you suggest I make it `addToView?(): void`. What about properties?
```
    get width?(): number { return 0; }
    set width?(value: number) {}
```

**Comment by PanayotCankov** [comment]
`Partial` is really good. It I just need it to preserve the property docs and eventually a filter later to clear class methods and leave just fields and settable properties from in the partial type. Currently it will map `readonly index: number;` to `index?: number;`. But it is really really close to what I need.
