### ISSUE TITLE
TSServer: typings installer causes very high CPU load

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#11553]
**TypeScript Version:**  2.0.6-insider

- opened VS Code source code with a 2.0.6 tsserver. Got very high CPU load for quite some time. Here is what my process explorer showed 

![capture](https://cloud.githubusercontent.com/assets/1931590/19304527/5721b0f0-906d-11e6-9396-2e6ce44dc231.png)

All these processes were spawned by the typings installer process.

**Comment by dbaeumer** [comment]
@mhegazy I talked to Erich about this and one idea is that we make automatic type acquisition an opt in for now. This would allow us to gain experiences with it and to polish the user interface before we ship VS Code 1.7.

**Comment by kieferrm** [comment]
We should change the default to not acquire typings out of the box for now.

**Comment by mhegazy** [comment]
This is a bug in our throttling logic, we would like to investigate this further and get a fix out before switching off typing acquisition. we can make typing acquisition configurable in general through a command line argument to tsserver.

**Comment by dbaeumer** [comment]
Having a command line switch to turn this on or off IMO the right thing to do. This will allows us to gain experiences with it and provide a proper UI.

**Comment by vladima** [comment]
@dbaeumer can you give a try to PR #11577 
It adds command line option `--disableAutomaticTypingAcquisition` that will completely disable automatic type acquisition. Also it replaces `npm view` with direct request to global npm registry so you should see less node processes hanging around.
