### ISSUE TITLE
Require non-nullable properties to be initialized in constructor

### ISSUE THREAD

**Issue by maser** [Microsoft/TypeScript#11560]
Non-nullable properties can still be `undefined` at runtime by simply never assigning anything to them. 

**TypeScript Version:**  2.0.3

**Code**

```ts
class A {
    public b: string;

    constructor() {
        this.b = 'hello';
    }
}

class B {
    public b: string;

    constructor() {}
}

let a = new A();
let b = new B();
a.b.toLowerCase();
b.b.toLowerCase();
```

**Expected behavior:**

The compiler complains that `b` in class `B` is not initialized in the constructor and therefore might be `undefined`.

**Actual behavior:** 

This compiles but when I run it I get this:

```
$ tsc --strictNullChecks --target ES5 test.ts
$ node test.js
test.js:15
b.b.toLowerCase();
   ^

TypeError: Cannot read property 'toLowerCase' of undefined
```

**Comment by kitsonk** [comment]
Dupe of #8476

**Comment by maser** [comment]
Oh, sorry about that, I didn’t find that issue.
