### ISSUE TITLE
Watch does not detect new files in sub-directories for Linux.

### ISSUE THREAD

**Issue by DannyRyman** [Microsoft/TypeScript#11564]
**TypeScript Version:**  2.0.3

When running tsc --watch on Linux, new files added to sub-directories of the route are ignored. This basically makes running tsc in watch mode unusable on Linux.

I believe that Nodemon transitioned from using fs.watch to the Chokidar package to resolve this and other issues.

**Comment by DannyRyman** [comment]
Anyone?

**Comment by DannyRyman** [comment]
Nice to be listened too ;)

**Comment by mhegazy** [comment]
Sorry for the delay. Should be fixed in latest version of TS.
