### ISSUE TITLE
unresolved function or method map() when calling  http.get('rul').map();

### ISSUE THREAD

**Issue by rashid-softordi** [Microsoft/TypeScript#11565]
**TypeScript Version:**  2.0.3 and Ionic 2

``` ts
// A *self-contained* demonstration of the problem follows...

I am geeting the prblem by calling 

login(url:string) {
        return this.http.get('rul').map((res:Response) => res.json()).catch(res => Observable.throw(res.json())):
}

**Expected behavior:**

**Actual behavior:** 
Error is:   unresolved function or method map()
```

**Comment by RyanCavanaugh** [comment]
> `// A *self-contained* demonstration of the problem follows...`

What is `http` ? What is `this`?

**Comment by rashid-softordi** [comment]
All the code has been pasted below:

import {Injectable} from '@angular/core';
import {Http, Headers, Response} from '@angular/http'
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/catch';
import {Observable} from "rxjs/Observable";

@Injectable()
export class myApi {

    constructor(public http: Http){
    }
         login(url:string) {
            return this.http.get('rul').map((res:Response) => res.json()).catch(res =>
                                                                                                                  Observable.throw(res.json())):
         }
}

When I move the cursor on map function the getting this the Error which is:   unresolved function or method map()

**Comment by mhegazy** [comment]
@rashid-softordi i am afraid this is still not a self contained repro. can you provide a code snippet we can pass to `tsc` and see errors. 

you might want to ask on https://github.com/angular/angular as well.

**Comment by rashid-softordi** [comment]
Hi mhegazy,

All the code has been pasted below:

import {Injectable} from '@angular/core';
import {Http, Headers, Response} from '@angular/http'
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/catch';
import {Observable} from "rxjs/Observable";

@Injectable()
export class myApi {

constructor(public http: Http){
}
     login(url:string) {
        return this.http.get('rul').map((res:Response) => res.json()).catch(res => Observable.throw(res.json())):
     }    }

**Comment by vladima** [comment]
I've tried to [repro this](https://github.com/vladima/repro11565) but with no luck - this code compiles fine for me and if I open it in VSCode and hover over `.map` I get an expected tooltip saying that this method is `Observable<Response>.map: ...`. Do you have any extra steps in your setup?

**Comment by mhegazy** [comment]
@rashid-softordi, I am not sure how this is a self-contained repro. there are no setup steps, there are no versions, there are no command line arguments to reproduce. 

Please bear in mind that this is *not* a support forum.; this is an issue tracker for the ts compiler and language bugs. So we would appreciate it if you are cognizant of our time, and provide detailed steps on reproducing the behavior you see, reports, as well as details on why you believe this is a compiler bug, and not a setup, project or framework issue.
