### ISSUE TITLE
Circular denpendence problem when extend class

### ISSUE THREAD

**Issue by zixia** [Microsoft/TypeScript#11576]
**TypeScript Version:** 

2.0.3

**Code**

``` ts
// $ cat base-class.ts 
'use strict'

import D from './dependence-extend-class'

class B {
}

export default B
```

``` ts
// $ cat extend-class.ts 
'use strict'

import B from './base-class'

class E extends B {
}

export default E
```

``` ts
// $ cat dependence-extend-class.ts 
import E from './extend-class'

class D {
}

export default D
```

``` ts
// $ cat t.ts

import b from './base-class'
```

**Expected behavior:**

run `ts-node t.ts` should ok

**Actual behavior:** 

``` shell
$ ts-node t.ts

extend-class.ts:5
class E extends B {
                ^
TypeError: Class extends value undefined is not a function or null
    at Object.<anonymous> (extend-class.ts:5:17)
```

I understand the problem is because when nodejs load module B, B is require D, also D is require E, where E need to extend from B, but B is still not initialized. 

My questioin is: if I have to do this, is there any way to make it work?

**Comment by mhegazy** [comment]
I can not get this to reproduce locally neither on `tsc` nor on `ts-node`.

```sh
c:\test\11576>ls
[.]                          [..]                         base-class.ts
dependence-extend-class.ts   extend-class.ts              t.ts

c:\test\11576>type base-class.ts
'use strict'

import D from './dependence-extend-class'

class B {
}

export default B

c:\test\11576>type dependence-extend-class.ts
import E from './extend-class'

class D {
}

export default D

c:\test\11576>type extend-class.ts
'use strict'

import B from './base-class'

class E extends B {
}

export default E

c:\test\11576>type t.ts
import b from './base-class'

c:\test\11576>tsc --v
Version 2.1.0-dev.20161023

c:\test\11576>tsc t.ts --listFiles
C:/Users/mhegazy/AppData/Roaming/npm/node_modules/typescript/lib/lib.d.ts
c:/test/11576/extend-class.ts
c:/test/11576/dependence-extend-class.ts
c:/test/11576/base-class.ts
t.ts

c:\test\11576>node t.js

c:\test\11576>ts-node --v
ts-node v1.6.0
node v6.7.0

c:\test\11576>ts-node t.ts

```

**Comment by mhegazy** [comment]
also, if this is ts-node, i would recommend filing this on https://github.com/TypeStrong/ts-node

**Comment by blakeembrey** [comment]
Maybe `base-class.ts` is meant to be using `D` so it's not elided. However, it's not a `ts-node` or TypeScript issue, it's just how CommonJS works. You can't have circular dependencies on values like that because of the execution order of JavaScript.

**Comment by zixia** [comment]
hi @mhegazy , thanks for the reply.

I try to reproduce this bug, found that I miss three _important_ lines: we must do something with the imported class in `base-class.ts` / `dependence-extend-class.ts` / `t.ts` , such as a `typeof`:

base-class.ts:
```diff
import D from './dependence-extend-class'
+ typeof D
```

dependence-extend-class.ts:
```diff
import E from './extend-class'
+ typeof E
```

t.ts:
```diff
import b from './base-class'
+ typeof b
```

after added the above three lines to the source, then run the source emitted by tsc will produce the error message like this:

```shell
zixia@zixia-desktop ~/circular
$ tsc t.ts    

zixia@zixia-desktop ~/circular
$ node t.js
D:\circular\extend-class.js:5
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
                                                                   ^

TypeError: Cannot read property 'prototype' of undefined
    at __extends (D:\circular\extend-class.js:5:68)
    at D:\circular\extend-class.js:9:5
    at Object.<anonymous> (D:\circular\extend-class.js:14:2)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
```

ts-node will also produce error as well.

**Comment by zixia** [comment]
Hi @blakeembrey , thank you for pointing that out. I agree with you because in nodejs CommonJS will got `undefined` when we have this kind of `circular dependencies`.

However what I want to say is, because we are writing typescript, and the ts code will be transpiled by tsc. could the tsc do some workaround to make this kind of `circular dependencies` work?

if that could happen, will be awesome for people who want to use `circular dependencies` in their typescript code. :)

**Comment by mhegazy** [comment]
Node module system does not allow for such dependencies. consider using systemjs as a module loader, its implementation allows for such scenarios.

**Comment by zixia** [comment]
I understand the node module system does not allow for this.

however, if SystemJS could load circular dependency modules without the problem, why not typescript do the same thing? for example, implement a `SystemJS like` circular module loader. 

is this possible?

**Comment by mhegazy** [comment]
TypeScript does not have a run time component. you could emit your modules to be SystemJS using `--module system`; but then you need to have system.js art run time to be able to load your modules.

**Comment by mitevs** [comment]
I had the same issue and just found a workaround. In the folder where you have the classes you can create mediator .ts file that imports and exports the classes. Then you will have to import them from this file instead. E.g. I had models/ that contained various models and parent/child relationship between them. I created index.ts file and imported all the model classes in it and them immediately exported them:

import User from './user';
import Group from './group';
....

export { User, Group };

Then in the model classes if I ever needed any of the other models I would simply import from the index file like so:

import { User } from './index'
or short:
import { User } from '.';

This way I managed to get it working without a problem!

Cheers!

**Comment by zixia** [comment]
@mitevs Could you please provide the minimum full code for your example?

**Comment by mitevs** [comment]
Yes, this is the folder where I keep all my models:

![screen shot 2018-02-22 at 11 50 57 am](https://user-images.githubusercontent.com/1431331/36534394-b64f989e-17c6-11e8-8c43-de70dfb6bd5a.png)

For e.g. I have Item model and Container model (item is more generic), the Container can have many Item children. The Item class has static method for mapping generic item JSON by the type into one of the concrete classes. This is the Item class and the Container class:

Item.ts
![screen shot 2018-02-22 at 11 52 44 am](https://user-images.githubusercontent.com/1431331/36534471-ec82a0fa-17c6-11e8-8c94-cf3049d5e699.png)

Container.ts
![screen shot 2018-02-22 at 11 53 11 am](https://user-images.githubusercontent.com/1431331/36534505-00beb1ee-17c7-11e8-821c-bbf31746b5ba.png)

As you can see the dependencies between the models are imported from the index.ts (or just . would work). If you have cross-folder deps, you can create the index file in a specific location that is convinient to you and import all the classes that you want to use as deps. for others so that you can avoid importing them directly and create circular deps. This way the generated code is basically transiently imported through the mediator module, that is the index.ts file.

Hope this helps, cheers!
