### ISSUE TITLE
Implements readonly property should be readonly

### ISSUE THREAD

**Issue by dungdm93** [Microsoft/TypeScript#11578]
**TypeScript Version:**  2.0.3

**Code**

```ts
interface I {
    readonly name: string;
}

class C implements I {
    public name: string;
}

let c: C = new C();
c.name= "I going to change it";
```

**Expected behavior:**
Compilation error. `C.name` should be declared as `readonly`.

**Actual behavior:** 
Compilation success. No errors/warnings

**Comment by aluanhaddad** [comment]
The class correctly implements the interface. I know this is a duplicate but I can't seem to find the corresponding issue.

Regardless, `readable & writable` is assignable to `readable`.

**Comment by mhegazy** [comment]
thanks @aluanhaddad

**Comment by yortus** [comment]
TypeScript is allowing assignment both ways - shouldn't there be a compile error in the following? (There might be an issue open for that but I couldn't find one).

```ts
interface I {
    readonly name: string;
}

interface C {
    name: string;
}

let i: I;
let c: C;

i = c; // OK, readable & writable is assignable to readable
c = i; // OK but why? readable shouldn't be assignable to readable & writable
```

**Comment by mhegazy** [comment]
@yortus I believe https://github.com/Microsoft/TypeScript/issues/11481 covers this request.

**Comment by yortus** [comment]
Yes that's it exactly, thanks @mhegazy
