### ISSUE TITLE
"supper" keyword with Arrow function methods

### ISSUE THREAD

**Issue by dungdm93** [Microsoft/TypeScript#11575]
**Code**
```ts
class Base {
    public foo = () => { console.log("Hello world"); }
    // public foo() {     // No error if declare "foo" like this
    //     console.log("Hello world");
    // }
}

class Child extends Base {
    public bar() { super.foo(); };
}
```
**Actual behavior:**
ERROR
```
public bar() { super.foo(); };
                     ~~~                                                                                                                                                                         
src/main.ts(9,26): error TS2340: Only public and protected methods of the base class are accessible via the 'super' keyword.
```
TypeScript: 2.0.3
OS: Windows 10 x64
Node: 6.3.0

**Comment by jesseschalken** [comment]
`super.foo()` is trying to call `Base.prototype.foo`, which doesn't exist, because `public foo = ..` is a property, not a method (methods exist on the prototype, but properties don't).

**Comment by DanielRosenwasser** [comment]
This is actually per ES spec.

____

From MakeSuperPropertyReference:

> If env.HasSuperBinding() is false, throw a ReferenceError exception.

https://tc39.github.io/ecma262/#sec-makesuperpropertyreference
____

From HasSuperBinding:

> If envRec.[[ThisBindingStatus]] is "lexical", return false.

https://tc39.github.io/ecma262/2016/#sec-function-environment-records-hassuperbinding
____

From NewFunctionEnvironment:

> If F.[[ThisMode]] is lexical, set envRec.[[ThisBindingStatus]] to "lexical".

https://tc39.github.io/ecma262/2016/#sec-newfunctionenvironment

___

From FunctionInitialize:

> If kind is Arrow, set F.[[ThisMode]] to lexical.

https://tc39.github.io/ecma262/2016#sec-function-environment-records-hassuperbinding

**Comment by nomaed** [comment]
I have a similar case but with getter/setter.
Getters and setters are on the prototype chain however.

This works fine when transpiling to ES2015 but not when transpiling to ES5.

Example from the [playground](https://www.typescriptlang.org/play/#src=class%20Foo%20%7B%0D%0A%20%20%20%20private%20_foobar%3A%20string%3B%0D%0A%0D%0A%20%20%20%20public%20get%20foobar()%3A%20string%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20this._foobar%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20public%20set%20foobar(value%3A%20string)%20%7B%0D%0A%20%20%20%20%20%20%20%20this._foobar%20%3D%20value%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aclass%20Bar%20extends%20Foo%20%7B%0D%0A%20%20%20%20constructor()%20%7B%0D%0A%20%20%20%20%20%20%20%20super()%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20public%20set%20foobar(value%3A%20string)%20%7B%0D%0A%20%20%20%20%20%20%20%20super.foobar%20%3D%20%60child-%24%7Bvalue%7D%60%3B%0D%0A%20%20%20%20%7D%0D%0A%7D):

```ts
class Foo {
    private _foobar: string;

    public get foobar(): string {
        return this._foobar;
    }

    public set foobar(value: string) {
        this._foobar = value;
    }
}

class Bar extends Foo {
    constructor() {
        super();
    }

    public set foobar(value: string) {
        super.foobar = `child-${value}`;
    }
}
```
