### ISSUE TITLE
Property 'resize' does not exist on type 'CSSStyleDeclaration'

### ISSUE THREAD

**Issue by fiznool** [Microsoft/TypeScript#11589]
**TypeScript Version:**  2.0.3

**Code**

``` ts
const textarea = document.createElement('textarea');
textarea.style.resize = 'none';
```

**Expected behavior:**
- No warning

**Actual behavior:** 
- Warning: `Property 'resize' does not exist on type 'CSSStyleDeclaration'`

To workaround this I have created a new interface extending from `CSSStyleDeclaration` which does the trick for now.

``` ts
interface CSSStyleDeclarationWithResize extends CSSStyleDeclaration {
  resize: string
}

const textarea = document.createElement('textarea');
const style: CSSStyleDeclarationWithResize = textarea.style as CSSStyleDeclarationWithResize;
style.resize = 'none';
```

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by fiznool** [comment]
That's a mighty intimidating set of contribution guidelines. I'll see if I
can find some time but for something so trivial I'll probably just continue
to use an extended interface as above, as IMO this is easier than making a
contribution here.

If a core contributor can find the time to add this in it would be much
appreciated.

**Comment by mhegazy** [comment]
The issue is up for grabs. Any interested member can pick it up. But I would say be the PR you want to see in the world ;)

**Comment by alisabzevari** [comment]
I will fix it. It should be easy. Just adding the missing type to the related json file in https://github.com/Microsoft/TSJS-lib-generator project.
