### ISSUE TITLE
navigator.hardwareConcurrency not existing

### ISSUE THREAD

**Issue by nicolashenry** [Microsoft/TypeScript#11581]
**TypeScript Version:**  2.0.3

**Code**

``` ts
const hardwareConcurrency = window.navigator.hardwareConcurrency;
```

**Expected behavior:**
No error

**Actual behavior:** 
[ts] Property 'hardwareConcurrency' does not exist on type 'Navigator'.

**Comment by kitsonk** [comment]
While this is part of the living standard, it doesn't have wide browser support.  Interfaces are open ended though and it is quite easy to add this:

```typescript
interface Navigator {
    hardwareConcurrency: number;
}

const hardwareConcurrency = window.navigator.hardwareConcurrency; // no error
```

If you do feel that it is more widely supported, the `lib.webworker.d.ts` is generated via [TSJS-lib-generator](https://github.com/Microsoft/TSJS-lib-generator/) where I suspect a contribution would be welcomed.
