### ISSUE TITLE
Add flag to disable inclusion of type reference directives in .d.ts files

### ISSUE THREAD

**Issue by ntilwalli** [Microsoft/TypeScript#11586]
v2 of Typescript adds type reference directives to the top of .d.ts files.   This was not the case earlier.  Please enable a flag to disable the inclusion of these directives, for backwards compatibility purposes.

The feature was added in this commit, here: https://github.com/Microsoft/TypeScript/commit/376c493e678ca702f9f0f87779ce320f437b3132#diff-657ea90f8012478deead7d95becb96e4R161

**Comment by mhegazy** [comment]
The output will not be correct though. your package depends on another .d.ts file that was imported using @types. if this is a point-in-time issue, i would recommend adding a post build step that strips the comment out.

**Comment by ntilwalli** [comment]
Since this was a`core-js` issue for ES2015 types, we'll include the `--lib` ES2015 options during our build to avoid this issue... thx.
