### ISSUE TITLE
@types not working for project in subfolder

### ISSUE THREAD

**Issue by manishtpatel** [Microsoft/TypeScript#11592]
I have two tsconfig/typescript projects in an app. Project 1 at root of the folder for backend and project 2 at /src folder for front end.

Just upgraded to typescript 2.0 and removed all typings and installed @types equivalent.

I have mongodb referenced in both project. my backend project compiles just fine but project in /src folder throws error

../node_modules/@types/mongoose/index.d.ts(2279,74): error TS2304: Cannot find name 'Promise'.
../node_modules/@types/mongodb/index.d.ts(17,64): error TS2304: Cannot find name 'Promise'.

Looks like an issue with referencing @types when project is in subfolder. 

I compile project using tsc only

**Comment by mhegazy** [comment]
> I have mongodb referenced in both project. my backend project compiles just fine but project in /src folder throws error

The issue is about missing `Promise` definitions, and not subfolders. does your backend use `--target ES6` or has `--lib es6/es2015`?

**Comment by manishtpatel** [comment]
thanks @mhegazy, i got it working by adding es6-promise for es5 project. had to add types to exclude unwanted types(es6-promise for backend). I didn't see that in compiler options documents but looks like empty types are excluding non referenced types.


now at root i have following for backend
`
{
    "compilerOptions": {
        "target": "es2015",
        "inlineSourceMap": true,
        "module": "commonjs",
        "moduleResolution": "node",
        "types": []
    },
    "compileOnSave": true,
    "exclude": [
        "src",
        "node_modules",
        "public",
        "dist",
        "views"
    ]
}
`




at /src i have following for frontend
`{
    "compilerOptions": {
        "target": "es5",
        "moduleResolution": "node",
        "typeRoots": [
            "../node_modules/@types"
        ],
        "types": [
            "jquery", "jasmine", "es6-promise"
        ]
    }
}`

**Comment by mhegazy** [comment]
just as a note, you do not need `es6-promise` per se. all you need is `"lib": ["dom", "es6"]`. also the `typeRoots` is not needed, but having it is fine too.
