### ISSUE TITLE
Intellisense for object properties defined in multi-line JSDoc comments

### ISSUE THREAD

**Issue by abgivant** [Microsoft/TypeScript#11597]
Currently it doesn't look like the TypeScript parser recognizes properties for an object parameter if they are defined with separate `@param` declarations. Would it be possible to add support for this?

![image](https://cloud.githubusercontent.com/assets/3431954/19362651/1c9e5498-914d-11e6-8584-dd585bf9a5c6.png)

![image](https://cloud.githubusercontent.com/assets/3431954/19362699/4ab4c63c-914d-11e6-99bd-c351845fa8fc.png)

Thanks!

**Comment by Kovensky** [comment]
A workaround is to write:

```js
/**
 * @param {{strProp: string, numProp: number}} obj - An object parameter with string and number properties
 */
```

but that doesn't allow for documenting the specific subkeys.

**Comment by abgivant** [comment]
@Kovensky Yeah, that does work, but the individual property documentation is the main reason I prefer the multi-line documenting.

**Comment by abgivant** [comment]
Sorry, didn't mean to close/reopen this...

**Comment by ryansully** [comment]
Would a solution to this also support destructured parameters as well?
Example: https://github.com/jsdoc3/jsdoc/issues/987#issuecomment-93864964

**Comment by abgivant** [comment]
I haven't really used that pattern, but I would think it would. That seems to be an extension of the same underlying issue of being unable to document properties of object parameters.
default values or property descriptions.

**Comment by anks333** [comment]
How about creating a @typedef 
this works fine for me.
<pre>
/**
 * @typedef {Object} GetUsersParams
 * @property {number} page_size          - Number of results to show in a page, optional?
 * @property {number} page_number        - Page number, optional?
 * @property {Object} match_params       - match query, optional?
 */
/**
 * @description getUsers function can be used to fetch users
 * @param {GetUsersParams} params - Provide appropriate props
 * @param {function} cb
 */
function getUsers(params, cb) {
    // do something
}
</pre>


I tried this, but it doesn't work
<pre>
* @param {...GetUsersParams} params 
</pre>

**Comment by abgivant** [comment]
That's actually what I've been doing as a workaround, but it doesn't allow for documenting optional/default values. 

You also don't get the text descriptions in intellisense. I wouldn't say that's necessary, but it'd be nice.

**Comment by MikeyBurkman** [comment]
Has there been any update on this? The `@typedef` workaround is not bad, but without the support of optional parameters (which seem to be supported for jsdocs), I'm getting a lot of false positives with jscheck turned on.

**Comment by mhegazy** [comment]
>  but without the support of optional parameters (which seem to be supported for jsdocs)

can you elaborate on this?

**Comment by MikeyBurkman** [comment]
@mhegazy Here's a code snippet:
```js
/**
 * @typedef {Object} Opts
 * @property {string} x
 * @property {string=} y
 * 
 * @param {Opts} opts
 */
function foo(opts) {
  console.log(opts);
}

foo({x: 'abc'});
```
That call to foo() will be flagged because it's missing `y` in the opts. The type checker does not recognize any of the methods of specifying optional parameters listed on the [wiki](https://github.com/Microsoft/TypeScript/wiki/JsDoc-support-in-JavaScript). I even tried doing TS-style using `@property {string?} y` and still no luck.

**Comment by mhegazy** [comment]
I think that is another bug. thanks for reporting it. filed https://github.com/Microsoft/TypeScript/issues/15916 to track it.

**Comment by zanza00** [comment]
I have a similar problem with stateless functional components in react, they are written with object destructuring and the trick with `@typedef` doesn't works because the parameter doesnt have a proper name

I have tried with `props`, `param0` , `args0` but no luck 😞 

```javascript

/**
 * @typedef Props
 * @property {string} one  - first 
 * @property {number} two  - second
 * 
 * @param {Props} props
 */

// doesn't work
function Component({one, two}) { 
// stuff... 
}

// works
function Component(props) { 
const {one, two} = props
// stuff... 
}
```

thanks for any advice 😄

**Comment by sandersn** [comment]
@zanza00 you can you specify the type inline:

```ts
function Component(/** @type {Props} */ { one, two }) {
 // stuff ...
}
```

**Comment by zanza00** [comment]
I can confirm that indeed it works, thanks

**Comment by sandersn** [comment]
Fix is up at #17352

**Comment by sandersn** [comment]
@mohsen1 that’s a slightly different issue than this one, and is tracked at #19645.

The PR with the fix is at #18832. I’ll take another look at it; last I remember we needed to check whether performance was OK with the additional upfront processing and storage it required.

**Comment by sandersn** [comment]
@mohsen1 destructured parameters now look up jsdoc `@param` tags positionally. It should be available tomorrow in `typescript@next`.

**Comment by Shahor** [comment]
What do you mean by `positionally`? 

Are we heading towards something like 

```js
/**
* @param {number} $0.id An id
*/
function foo({ id }) {}
```

?

**Comment by sandersn** [comment]
@Shahor no the syntax you would use is either

```js
/**
 * @param {Object} arg
 * @param {number} arg.id An id
 */
function foo({ id }) {}
```

OR

```js
/**
 * @param {{ id: number }} arg
 */
function foo({ id }) {}
```

**Comment by steph643** [comment]
@sandersn, the two syntaxes you've suggested above doesn't seem to work. See [here](https://github.com/Microsoft/TypeScript/issues/19645#issuecomment-395050077).

**Comment by sandersn** [comment]
@steph643 [VS code 1.23 is running Typescript 2.8](https://code.visualstudio.com/updates/v1_23#_typescript-283), which doesn't have the fix.

**Comment by Shagon94** [comment]
can confirm the issue, example code:
```js
/**
 * @param {*} options the args object
 * @param {number} object.alpha first number
 * @param {number} object.bravo second number
 * @param {Function} callback the callback function
 * @returns {number}
 */
function addNumbersFromObject({ alpha = 1, bravo = 2 } = {}, callback = null) {
  if (!callback) return alpha + bravo;
  return callback(alpha + bravo);
}

console.log(addNumbersFromObject({ alpha: 2 }));
```
that results in the text not being displayed:
<img width="593" alt="screen shot 2018-06-14 at 10 26 29 am" src="https://user-images.githubusercontent.com/9140783/41400475-8f7003f4-6fbd-11e8-88c4-bbc5601859cf.png">


The workaround is to use the `@typedef` like so:
```js
/**
 * @typedef {Object} Opts
 * @property {string} alpha Alpha helping test
 * @property {string=} bravo Description about bravo
 * 
 * @param {Opts} opts the options object
 * @param {Function} callback the callback function
 * @returns {number}
 */
function addNumbersFromObject({ alpha = 1, bravo = 2 } = {}, callback = null) {
  if (!callback) return alpha + bravo;
  return callback(alpha + bravo);
}

console.log(addNumbersFromObject({ bravo: 2 }));
```

Now intellisense detects the parameters as well as shows if its an optional parameter and adds description to it:
<img width="586" alt="screen shot 2018-06-14 at 10 29 07 am" src="https://user-images.githubusercontent.com/9140783/41400630-f04f5350-6fbd-11e8-8295-49bf34f1458b.png">

**Comment by mhegazy** [comment]
@Shagon94 it should be:

```ts
/**
 * @param {Object} options the args object
 * @param {number} options.alpha first number
 * @param {number} options.bravo second number
 * @param {Function} callback the callback function
 * @returns {number}
 */
function addNumbersFromObject({ alpha = 1, bravo = 2 } = {}, callback = null) {
    if (!callback) return alpha + bravo;
    return callback(alpha + bravo);
}

console.log(addNumbersFromObject({ alpha: 2 }));
```
