### ISSUE TITLE
Using rest params of virtual types with reflection causes error.

### ISSUE THREAD

**Issue by shlomiassaf** [Microsoft/TypeScript#11606]
**TypeScript Version:**  2.0.3

**Code**

```ts
// File: types.ts
export type MyVirtualType = string | number;
```

```ts
import { MyVirtualType } from './types';
@SomeDecorator()
export class SomeClass {
  constructor(...values: Array<MyVirtualType>) {
    console.log(values);
  }
}
```

This will throw:
```
Uncaught ReferenceError: types_1 is not defined
```

**This only happens when the constructor function parameter is a REST param (...)**
If I replace it with a simple array it works.

The underlying issue is the way REST params are converted to metadata in runtime while removing virtual imports (imports that are not used physically (types, interfaces etc..)
So if all the imports are virtual the whole import statement is removed hence no `types_1` reference.

To workaround the issue I need to make sure **types_1** imports are not virtual, i.e the import includes physical JS runtime objects.

I can do this by:
```
import * as types from './types'
```
and then use `types.MyVirtualType`, this works.

I can also import some physical object from the **types** module, this requires some actual usage so TypeScript will not detect it as unused and remove it.

```ts
// File: types.ts
export const MyObject = {};
export type MyVirtualType = string | number;
```

```ts
import { MyObject, MyVirtualType } from './types';
if (MyObject === undefined) {} // force use.

@SomeDecorator()
export class SomeClass {
  constructor(...values: Array<MyVirtualType>) {
    console.log(values);
  }
}
```
Now it works since `types_1` is referenced.

**Comment by sheetalkamat** [comment]
@shlomiassaf I tried with typescript@next as well as typescript version 2.0.3 and 2.0.5 and I cant repro this.
The generated file looks like this:
```javascript
"use strict";
var SomeClass = (function () {
    function SomeClass() {
        var values = [];
        for (var _i = 0; _i < arguments.length; _i++) {
            values[_i - 0] = arguments[_i];
        }
        console.log(values);
    }
    SomeClass = __decorate([
        SomeDecorator(),
        __metadata('design:paramtypes', [Object])
    ], SomeClass);
    return SomeClass;
}());
exports.SomeClass = SomeClass;
```

There is no types_1 referred here.
