### ISSUE TITLE
Сompilation error on azure websites & kudu

### ISSUE THREAD

**Issue by sergey-borisov** [Microsoft/TypeScript#11613]
Hi!

Sorry for the bad english.

I have a project compilation error (TS5009: Cannot find the common subdirectory path for the input files) when deploying in Azure WebSites with CI. On the local machine everything works fine.
TypeScript Version: **2.0.3**

The problem is that part of the source files **NodeSystem.realpath** provides remote path to source file in format _//host/volume2-default/.../.../wwwroot/app/file.ts_ and for the other part of source files getting the local path _D:/home/site/wwwroot/app/file2.ts_

If remove the parameter **outDir** in **tsconfig.json**, I get an error **"duplicate identifier 'export = server'"** in _node_modules/@types/socket.io/index.d.ts_, because the compiler duplicates the way to d.ts file:
_//host/volume2-default/.../.../wwwroot/node_modules/@types/socket.io/index.d.ts_
and
_node_modules/@types/socket.io/index.d.ts_

There is another solution to the problem?

I changed the method "**System.realpath**" and compile without error.

Original method: https://github.com/Microsoft/TypeScript/blob/a6443e3e5a722bf7eb48b8b1f5c87b13efbc70c4/src/compiler/sys.ts#L558

``` typescript
realpath(path: string): string {
                    return _fs.realpathSync(path);
                }
```

My version:

``` typescript
realpath(path: string): string {
                    return path;
                }
```

tsconfig.json:

``` json
{
  "compilerOptions": {
    "allowJs": false,
    "allowSyntheticDefaultImports": false,
    "allowUnreachableCode": false,
    "allowUnusedLabels": true,
    "charset": "utf8",
    "declaration": true,
    "diagnostics": false,
    "emitBOM": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "forceConsistentCasingInFileNames": true,
    "isolatedModules": false,
    "lib": ["es6"],
    "locale": "en-us",
    "listEmittedFiles": false,
    "listFiles": false,
    "module": "commonjs",
    "moduleResolution": "node",
    "noEmit": false,
    "noEmitHelpers": false,
    "noEmitOnError": false,
    "noFallthroughCasesInSwitch": false,
    "noImplicitAny": false,
    "noImplicitReturns": true,
    "noImplicitUseStrict": false,
    "noLib": false,
    "noResolve": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "outDir": "bin",
    "preserveConstEnums": false,
    "pretty": true,
    "removeComments": true,
    "skipDefaultLibCheck": false,
    "sourceMap": true,
    "stripInternal": true,
    "suppressExcessPropertyErrors": false,
    "suppressImplicitAnyIndexErrors": true,
    "target": "ES6"
  },
  "include": [
    "**/*.ts",
    "typings/**/*.d.ts"
  ]
}
```

package.json:

``` json
{
 "scripts": {
    "postinstall": "npm run tsc",
    "start": "node server.js",
    "tsc": "node node_modules/typescript/bin/tsc"
  },
  "engines": {
    "node": "~6.3.0"
  },
  "dependencies": {
    "@types/node": "^6.0.41",
    "@types/request": "0.0.31",
    "@types/socket.io": "^1.4.27",
    "request": "^2.75.0",
    "socket.io": "^1.4.8",
    "typescript": "^2.0.3"
  }
}
```

**Comment by mhegazy** [comment]
> There is another solution to the problem?

not a simple one. we have switched to getting realPath to allow for detecting cases when `npm link` is used. 

we should have a fix for this in TS 2.1 though.

**Comment by vdolbnya** [comment]
Hello, I have faced with similar issue (we have some parts of UI library in project that are not in node_modules but are linked by symlinks and instead of treating them as subfolders in current folder compiler is trying to compile them by real path location).

Workaround provided by **sergey-borisov**  works (I have found and changed realpath function in node_modules\typescript\lib\tsc.js as  **sergey-borisov** have proposed), but unfortunately it is not an option for us because we want to have a typescript in node_modules and not a part of our repository.
Also we don't want to wait till TypeScript 2.1 will be released, we want to try a benefits of 2.0 version now.

So I'm looking for more convenient workaround.

My idea is to somehow create own implementation of CompilerHost (https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API) when I will override the realpath function by return the input. Then configure VisualStudioCode and build script to somehow use code which will utilize this new CompilerHost instead of just calling tsc.
How do you think, this idea might work?
Also you please provide a lean working sample of overriding of some method of CompileHost and use it in sample project if it is exists?
Thank you!

**Comment by sergey-borisov** [comment]
@vdolbnya, I had no time to check, but if to use the Compiler's API, then you can try the following method:


```
import * as ts from "typescript";

ts.sys.realpath = (path) => path; ///! <-- override original method

function compile(fileNames: string[], options: ts.CompilerOptions): void {
    let program = ts.createProgram(fileNames, options);
    let emitResult = program.emit();
    let allDiagnostics = ts.getPreEmitDiagnostics(program).concat(emitResult.diagnostics);
    allDiagnostics.forEach(diagnostic => {
        let { line, character } = diagnostic.file.getLineAndCharacterOfPosition(diagnostic.start);
        let message = ts.flattenDiagnosticMessageText(diagnostic.messageText, '\n');
        console.log(`${diagnostic.file.fileName} (${line + 1},${character + 1}): ${message}`);
    });
    let exitCode = emitResult.emitSkipped ? 1 : 0;
    console.log(`Process exiting with code '${exitCode}'.`);
    process.exit(exitCode);
}

compile(process.argv.slice(2), {
    noEmitOnError: true, noImplicitAny: true,
    target: ts.ScriptTarget.ES5, module: ts.ModuleKind.CommonJS
});
```

**Comment by andy-ms** [comment]
This is probably fixed by #12020. Could you test with `typescript@next` (as of tomorrow's build) and tell us if this works for you now?

**Comment by vdolbnya** [comment]
@sergey-borisov thanks for help, unfortunately I had no chance to integrate this soultion, had been switched to other tasks.
@andy-ms fix is works im my case!

**Comment by sergey-borisov** [comment]
@andy-ms thanks! this fix has solved the problem
