### ISSUE TITLE
Violation of generic constraint dependency is not caught

### ISSUE THREAD

**Issue by karlbohlmark** [Microsoft/TypeScript#11617]
**TypeScript Version:** 2.0.3, 2.1.0-dev.20161014

**Code**

``` ts
interface Generic<A> {}
interface Specialized extends Generic<number> {}
function fn<T1,T2 extends Generic<T1>>(a: T2) : T1 {
    return null
}
let g: Specialized
let result = fn<string, Specialized>(g)
```

**Expected behavior:**
The compiler should complain about Specialized not extending Generic<string>

**Actual behavior:** 
The compiler doesn't complain

**Comment by kitsonk** [comment]
You have a couple problems here.  Generics in an interface that aren't actually used in the body are ignored.  Also, you have an assignment issue in that any interface without any properties is considered `any`.

Simply adding a property to `Generic` that uses the generic gives you the error you [would expect](http://www.typescriptlang.org/play/#src=interface%20Generic%3CA%3E%20%7B%0A%20%20%20%20value%3A%20A%3B%0A%7D%0Ainterface%20Specialized%20extends%20Generic%3Cnumber%3E%20%7B%7D%0Afunction%20fn%3CT1%2CT2%20extends%20Generic%3CT1%3E%3E(a%3A%20T2)%20%3A%20T1%20%7B%0A%20%20%20%20return%20null%0A%7D%0Alet%20g%3A%20Specialized%0Alet%20result%20%3D%20fn%3Cstring%2C%20Specialized%3E(g)):

```typescript
interface Generic<A> {
    value: A;
}
interface Specialized extends Generic<number> {}
function fn<T1,T2 extends Generic<T1>>(a: T2) : T1 {
    return null
}
let g: Specialized
let result = fn<string, Specialized>(g)
```

**Comment by karlbohlmark** [comment]
Ok, makes sense I guess. But then we come to what I am really after:
```ts

interface Generic<A> {
    id: A
}
interface Specialized extends Generic<number> {
}
function fn<T1,T2 extends Generic<T1>>(a: T2) : T1 {
    return null
}
let g: Specialized
let result = fn(g)
```

I want `result` to be a `number`. Is that unreasonable?

**Comment by kitsonk** [comment]
That is a totally different kettle of fish.  You are trying to reverse extract out generics that TypeScript has already resolved.  But at that point the type of `Specialized` contains no generics that can be inferred.  TypeScript doesn't hold those open.  Think of it as a curry in the sense that generic (`number`) is no longer generic, it has been filled in.

You would have to preserve generic slot in some fashion so it [can be inferred](http://www.typescriptlang.org/play/#src=interface%20Generic%3CA%3E%20%7B%0A%20%20%20%20value%3A%20A%3B%0A%7D%0Ainterface%20Specialized%3CN%20extends%20number%3E%20extends%20Generic%3CN%3E%20%7B%7D%0Afunction%20fn%3CT1%2CT2%20extends%20Generic%3CT1%3E%3E(a%3A%20T2)%20%3A%20T1%20%7B%0A%20%20%20%20return%20null%0A%7D%0Alet%20g%3A%20Specialized%3Cnumber%3E%0Alet%20result%20%3D%20fn%3Cnumber%2C%20Specialized%3Cnumber%3E%3E(g)):

```typescript
interface Generic<A> {
    value: A;
}
interface Specialized<N extends number> extends Generic<N> {}
function fn<T1,T2 extends Generic<T1>>(a: T2) : T1 {
    return null
}
let g: Specialized<number>
let result = fn<number, Specialized<number>>(g)
```

**Comment by mhegazy** [comment]
Constraints do not contribute to inferences, they are just there to validate the results of the inference.

The way you would achieve this is to use intersection types.. e.g.:
```ts
function fn<T1, T2 extends Generic<T1>>(a: T2 & Generic<T1>): T1 {
    return null
}
let g: Specialized
let result = fn(g)  // number
```

notice `T2 & Generic<T1>`. This gives the compiler a place to infer `T1`

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
