### ISSUE TITLE
Map type does not work in salsa intellisense

### ISSUE THREAD

**Issue by Thaina** [Microsoft/TypeScript#11612]
We could make type definition for map in file .d.ts for intellisense in javascript
But it seem it does not work in jsdoc comment like this

```js
/** @type {{[key:string]: {Win:number,Score:number,Goal:number,Lose:number}}} */
var scores = {};
```

![image](https://cloud.githubusercontent.com/assets/1042507/19377264/0591585a-920f-11e6-99d9-503c75e0a5a8.png)

**Comment by aluanhaddad** [comment]
Seems to work in nightly 

![image](https://cloud.githubusercontent.com/assets/5034656/19378455/b4fd41be-91ba-11e6-8789-c6a795b703a4.png)

**Comment by mhegazy** [comment]
Should be working correctly in latest drop of TypeSript (TS 2.0.2 or later). VSCode ships with an older version of TypeScript. Please see [Using Newer TypeScript Versions](https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions) documentation for more details on updating your VSCode to use a different version of TypeScript.

**Comment by Thaina** [comment]
@mhegazy Thanks. Already try with 2.1.0 and it work fantastic. But not in 2.0.6
