### ISSUE TITLE
Installing TypeScript 1.3 for Visual Studio 2013 Community on Windows 8.1 failure

### ISSUE THREAD

**Issue by csuzw** [Microsoft/TypeScript#1162]
I'm trying to install TypeScript 1.3 (TypeScript_Dev12.exe) for Visual Studio 2013 Community Edition.  The installation doesn't display/throw any exceptions.  When I enter Visual Studio there is no evidence that it has been installed (no templates, no syntax highlighting etc).  I found an error in the event log that suggests the install failed but I don't know how to interpret the error messages.  I've uploaded the error log files to DropBox here: https://dl.dropboxusercontent.com/u/77349605/tsinstallerror.zip .  I'm running a pretty clean install of Windows 8.1 however I did previously have VS2013 Express for Windows/Windows Desktop/Web installed but uninstalled them when Community edition was released so I don't know if that could have caused some issues.

**Comment by JoeArizona** [comment]
I've had the same issue for quite some time now: the last couple of versions of TypeScript that I've installed via Tools --> Extensions do not install. Everything will go fine during the install process, but when I re-open VS, the TypeScript extension isn't installed, and still shows in the "Online" category as something I can install. Currently, I'm having this issue with "TypeScript 1.4 for Visual Studio 2013" (https://visualstudiogallery.msdn.microsoft.com/2d42d8dc-e085-45eb-a30b-3f7d50d55304?SRC=VSIDE)
 
I'm using VS 2013 Professional, with a DreamSpark license. More specifically:

VS version 12.0.31101.00 Update 4
Windows 8.1 64-bit (version 6.3.9600 Build 9600)
.NET 4.5.51650 (perhaps irrelevant – I don't know if VS is a .NET app)
Intel Core i5-3337U
Intel VT is enabled in the UEFI – likely irrelevant, but bugs can be strange things, and it's one of the most distinctive system configs in place on my system, compared to baseline (changed the setting in the UEFI so I could run Virtual Box)

**Comment by danquirk** [comment]
Could you try some of Paul's suggestions from earlier in the thread?

**Comment by JoeArizona** [comment]
I tried the repair in Programs. That didn't work. I don't have a 1.1 folder.

**Comment by kpko** [comment]
Hi,

I have the same problem. Had Visual Studio for Web 2013 installed with TypeScript Support, uninstalled both, installed Visual Studio 2013 CE (Update 4) and have no TypeScript Support at all.

Strangely, when I run the TypeScript 1.4 Installer from the Visual Studio Gallery, the installations runs successfully, but the ProjectTemplates and ItemTemplates für TypeScript Files are still missing. The TypeScript VS Extension doesn't show up in the VS Extensions neither.

**Comment by Lukino2000** [comment]
same here. vs2013 u4 premium from msdn bizspark and latest (1.4) typescript from visual studio gallery, pc formatted yesterday just windows and vs2013.
no error on installation but addin seems not installed: no new item and on extensions menu it appears as missing.

**Comment by paulvanbrenk** [comment]
@Lukino2000 did you try the repair option on the TypeScript install in add/remove programs? Do you have a 1.4 folder in program files\Microsoft SDKS?

**Comment by Lukino2000** [comment]
i tried several times... i also tried install version 1.3 and nothing change. Yes, i have the folder 1.4 folder in SDKs (for ver 1.4) and, when i tried 1.3 TS version, the folder 1.1. I noticed that in %PATH% the version 1.0 come first. When I tried changing the 1.0 folder name, TSC.exe works correctly but VS still doesn't work.

**Comment by kpko** [comment]
Exactly the same for me here. I have the folders and tsc.exe but no Item or Project Templates.

**Comment by csuzw** [comment]
I tried again to get this working and it's still broken.  I installed, reinstalled, repaired 1.4 with no luck.  Then I uninstalled everything, Visual Studio included, deleted all VSCommon/VStudio folders in Program Files and Program Files (x86), deleted all VS related registry keys.  As far as I could tell there were no remnants of any version of VS left.  Then re-installed VS and then TypeScript 1.4 and it still says it's successful but appears to do absolutely nothing (and then tried repair for just to be sure and nothing).

**Comment by RyanCavanaugh** [comment]
Good luck @paulvanbrenk

**Comment by kpko** [comment]
I tried the method described by @csuzw and it worked! I am able to use TypeScript in VS2013 on my machine again.

1. Reinstall VS2013 Community Edition with the latest updates
2. Reinstall TypeScript 1.4
3. Extract the .msi file out of the installer with dark.exe (Wix binaries):
  dark.exe -x myOutputFolder/ TypeScript_1.4_VS2013.exe
4. Extract the contents of the .msi from myOutputFolder\AttachedContainer\packages\TypeScript_VS\TypeScript_VS.msi with LessMSI
5. Copy the contents of SourceDir\Microsoft Visual Studio 12.0 into your local Visual Studio 12.0 folder
6. Repair TypeScript 1.4

Thank you @csuzw !

I couldn't find an error log created by the installer, I would like to know why the installation itself failed in the first place. The installer didn't copy the contents of TypeScript_VS at all.

**Comment by danquirk** [comment]
We think this is fixed for TypeScript 1.5. If people continue to see issues there please do open a new issue and we can continue investigating there.

**Comment by ValterSantosMatos** [comment]
Hi, I had the same issue trying to install  TypeScript 1.4 but I had access to another computer that had typescript install, so I simply copied the TypeScript 1.4 folder to my computer C:\Program Files (x86)\Microsoft SDKs\TypeScript and then repaired the installation of typescript.

**Comment by jagadeeshpa** [comment]
Hi,
     Any one tell, how to run typescript with protractor in eclipse.

Thanks in advanced

**Comment by paulvanbrenk** [comment]
@jagadeeshpa You should probably create a new issue, since what you're trying to do doesn't seem related to this issue.
