### ISSUE TITLE
IntelliSense not working with ES5 class pattern

### ISSUE THREAD

**Issue by waderyan** [Microsoft/TypeScript#11622]
_From @benjaminmillhouse on October 11, 2016 16:38_
- VSCode Version: Code 1.6.0 (e52fb0bc87e6f5c8f144e172639891d8d8c9aa55, 2016-10-10T18:37:40.189Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions: andischerer.theme-atom-one-dark-0.0.1, dbaeumer.vscode-eslint-1.0.7, donjayamanne.githistory-0.1.0, HookyQR.JSDocTagComplete-0.0.2, joelday.docthis-0.3.4, johnpapa.Angular1-0.1.16, ms-vscode.csharp-1.4.1, ms-vscode.js-atom-grammar-0.1.9, robertohuertasm.vscode-icons-3.0.3, wcwhitehead.bootstrap-3-snippets-0.0.7, Zignd.html-css-class-completion-1.0.3

JavaScript IntelliSense parser no longer seems to recognize class syntax when written inside of an IIFE.

Steps to Reproduce:
1. Define a class using this syntax

```js
var MyClass = (function () {
  function MyClass() {
      this.id = 0;
  }
  return MyClass;
}());
```
1. Trigger IntelliSense for new MyClass(). -- nothing is shown
2. Remove IIFE and return statement

```js
function MyClass() {
  this.id = 0;
}
```
1. Trigger IntelliSense for new MyClass(). -- IntelliSense is provided again

In the previous version of VS Code this format was supported and provide auto-complete options for the class as expected. I ended up going with this syntax because that is what I saw TypeScript converting class syntax down to.  However, as of the latest patch I no longer get IntelliSense on any of these classes unless I remove the IIFE and return statement.
Was this an intentional change?  Is there any official documentation on what types of class syntax VS Code will support for auto-completion?

_Copied from original issue: Microsoft/vscode#13521_

**Comment by waderyan** [comment]
@benjaminmillhouse thank you for opening this issue. In [Feb](http://code.visualstudio.com/updates/vFebruary#_languages-javascript) we switched to a new language service for JavaScript and TypeScript. There were a number of improvements but some features that were missing in the new language service. 

This is a valid request to have added to the language service we use today. I am moving this issue to the language service repo.

**Comment by benjaminmillhouse** [comment]
@waderyan Thank you!  Is this still the best reference for JSDoc compatibility within VS Code? I try to adhere to it as much as possible to make sure my Intellisense works, but the last update to it was August so wondering if it's gotten stale at this point?
https://github.com/Microsoft/TypeScript/wiki/JsDoc-support-in-JavaScript

**Comment by waderyan** [comment]
Yes I believe so. @DanielRosenwasser is actively mantaining that wiki and we consume the TypeScript language service for VS Code.

**Comment by dylanribb** [comment]
I ran into this same issue today while getting some new team members up and running with TypeScript in VS Code. Oddly enough, I've also found that this causes IntelliSense to fail for other variables/members with the same file if referenced in a different file.

For example, assume I have the following in `file1.js`:

`var someClass = (function () {
  function someClass() {
      this.id = 0;
  }
  if (typeof module !== 'undefined') {
      module.exports = someClass();
  } else {
      this.someClass = someClass;
  }
  return someClass;
}());


var someFunction = function() {};`

And then in file2.js:
`someFunction();`

IntelliSense fails for both the ES5-style class as well as the other function within the file.

It seems like, even if the ES5 class fails to generate IntelliSense, the other function should still be available and not "blocked" by the ES5 class reference.

It also doesn't appear to make a different in what order they are defined. I could place `someFunction` above `someClass` in the example above and the behavior would be the same.

**Comment by mjbvz** [comment]
With TS 2.5 in VSCode 1.16, intellisense now seems to work in the originally reported example:

<img width="687" alt="screen shot 2017-09-14 at 8 21 59 pm" src="https://user-images.githubusercontent.com/12821956/30465181-689d595c-998a-11e7-8f15-3073b09a631f.png">

**Comment by sandersn** [comment]
@dylanribb you have a different bug, where nested `module.exports` assignments cause `file1.js` to be marked as a module and treated *only* as a module. So you can use `file1` as a module just fine:

```js
var someClass = require('./file1')
var k = new someClass()
k.id
```

The original bug has been fixed, so I'll close it. Feel free to open a separate issue about treating a js file as both a module and a global script.
