### ISSUE TITLE
Cannot reference an object within one of its methods' default arguments

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/TypeScript#11628]
**TypeScript Version:**  2.0.3

**Code**

``` ts
let Obj = {
  get () {},
  set ( value = Obj.get () ) {}
};

Obj.missing (); // Obj is treated as `any`, so I don't get any error for the usage of the undefined method `missing`
```

**Expected behavior:**

I expect to get an error for the usage of the undefined method `Obj.missing`.

**Actual behavior:** 

I don't get any, since if I use `Obj` within a default argument inside one of `Obj`'s own methods the entire object type becomes `any`.

**Ugly workaround:** 

``` ts
let _self;
let Obj = _self = {
  get () {},
  set ( value = _self.get () ) {}
};

Obj.missing (); // I get an error as expected
```

**Comment by mhegazy** [comment]
> I expect to get an error for the usage of the undefined method Obj.missing.

you would under `--noImplicitAny`.

```cmd
c:\ts>tsc --noImplicitAny a.ts
a.ts(1,5): error TS7022: 'Obj' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.
a.ts(3,9): error TS7022: 'value' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.
```

**Comment by fabiospampinato** [comment]
Why should I be forced to use `--noImplicitAny` or to write ugly workarounds when it seems clear to me that the problem is that TypeScript should be a little smarter about this particular case?

Maybe I'm wrong about it, but why should this behavior be considered the correct one?
