### ISSUE TITLE
VS15 Preview 5: File is not under 'rootDir' '$(MSBuildProjectDirectory)'.

### ISSUE THREAD

**Issue by SaschaNaz** [Microsoft/TypeScript#11623]
**TypeScript Version:** 2.0.5.0, the version embedded on VS15 Preview 5

**Project setting:**

`<TypeScriptProjectDir>$(MSBuildProjectDirectory)\</TypeScriptProjectDir>` as @paulvanbrenk said on #9665.

**Expected behavior:**

VS shouldn't complain about it.

**Actual behavior:** 

TS6059 File '(My solution directory)/(My project name)/sources/customelements/elements/placeholdingbutton.ts' is not under 'rootDir' '$(MSBuildProjectDirectory)'. 'rootDir' is expected to contain all source files.

![image](https://cloud.githubusercontent.com/assets/3396686/19390354/b5529800-9262-11e6-85a8-c1228ae3d35c.png)

VS complains but the code still compiles when "Rebuild All".

**Additional:**

Not sure what this does but this process even tries to "generate" my emscripten-compiled large js file and slows everything down extremely.

![image](https://cloud.githubusercontent.com/assets/3396686/19407125/4d430daa-92d3-11e6-862c-1c001014263c.png)

**Comment by paulvanbrenk** [comment]
Can you share a repro project?

**Comment by SaschaNaz** [comment]
I've forgotten about this but this seems somehow is fixed. :smile:
