### ISSUE TITLE
JS: Can't search function symbol when set as property of an object

### ISSUE THREAD

**Issue by waderyan** [Microsoft/TypeScript#11625]
_From @irvinhg on October 12, 2016 8:3_
- VSCode Version: 1.6
- OS Version: Reproduced in Windows 8.1 / 7

Steps to Reproduce:
1.  Open a `.js` file and add the following:

```
var foo = {
    bar: function barBar () {}
};
```
1. Do a symbol search `ctrl + shift + o` . `bar`  or `barBar` are not listed.

_Copied from original issue: Microsoft/vscode#13574_

**Comment by waderyan** [comment]
@irvinhg thank you for opening this issue. This is a valid request and one that is dependent on the JavaScript language service. Moving this issue to that repo.

**Comment by irvinhg** [comment]
Fixed in 1.7 :), I think you can close.

**Comment by waderyan** [comment]
Great!
