### ISSUE TITLE
Insertion of space before closing non-empty parenthesis does not work

### ISSUE THREAD

**Issue by waderyan** [Microsoft/TypeScript#11626]
_From @hubbergit on October 10, 2016 14:41_
- VSCode Version: 1.5.3
- OS Version: Win10

Steps to Reproduce:
1. Configuration: "typescript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis": true
2. Format this code:

```
import { Component, OnInit } from '@angular/core';

@Component({
    selector: 'x-com',
    templateUrl: './app/x-com.html',
    providers: [XComSer]
})
export class XComponent {
}
```
1. There is no space before the closing parenthesis just before the export class XComponent line

_Copied from original issue: Microsoft/vscode#13430_

**Comment by waderyan** [comment]
@hubbergit thank you for opening this issue. To make sure I understand what you expect to see, you expect to see the following:

```typescript
import { Component, OnInit } from '@angular/core';

@Component({
    selector: 'x-com',
    templateUrl: './app/x-com.html',
    providers: [XComSer]
} )
export class XComponent {
}
```

Is that correct? 

Note I have reproduced what you describe with v1.6.

**Comment by waderyan** [comment]
_From @hubbergit on October 12, 2016 8:18_

Yes, I would expect to see a space not only after the opening parenthesis, but also after the closing parenthesis:
```
import { Component, OnInit } from '@angular/core';
 
@Component( {
    selector: 'x-com',
    templateUrl: './app/x-com.html',
    providers: [XComSer]
} )
export class XComponent {
}
```

**Comment by waderyan** [comment]
@hubbergit thank you for the explanation. This is a language service issue. I am moving this to the language service repo.

**Comment by mhegazy** [comment]
Should be working correctly in latest drop of TypeSript (TS 2.1.4 or later). VSCode ships with an older version of TypeScript. Please see [Using Newer TypeScript Versions](https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions) documentation for more details on updating your VSCode to use a different version of TypeScript.

**Comment by hubbergit** [comment]
This does not work for me using VS-Code 1.9.1 with TypeScript 2.1.5 on my Win10 box.

Is it possible to reopen this issue?

**Comment by mhegazy** [comment]
![animation](https://cloud.githubusercontent.com/assets/8000722/22996254/feb7a5cc-f382-11e6-81c7-ad97a256eb0a.gif)

**Comment by hubbergit** [comment]
![witness](https://cloud.githubusercontent.com/assets/19938289/22997499/eb85f0b2-f3d2-11e6-96cd-0adc9ca5ed54.gif)

**Comment by hubbergit** [comment]
Any ideas why this works for @mhegazy, but not for me?
