### ISSUE TITLE
JSX text causes random formatting

### ISSUE THREAD

**Issue by RyanCavanaugh** [Microsoft/TypeScript#11636]
There's not a solid repro for this but there's a bug in our `SyntaxKind` enum -- the `JsxText` kind parses as a token (which it should), but it's *after* `LastToken`. The formatting engine uses an `N * N` sparse array computed with `N = LastToken`. When the formatting computes the formatting context by using a token pair, this means a `JsxToken` ends up looking up a random formatting context. This causes JSX formatting to break, *sometimes*, when you add a new token and change the value of `LastToken`.

/cc @weswigham who was understandably baffled by this https://github.com/Microsoft/TypeScript/pull/10425/commits/11dce6ff5442c8d4951bf1efffc73de160cbe83c

**Comment by weswigham** [comment]
Thanks for the callout; it's nice to know what was up!
