### ISSUE TITLE
Faulty NoImplicitAny errors on contextually typed parameters

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#11631]
I've got the following code:
```ts
import express = require('express');
const app = express();
app.use((req, res, next) => {
});
```

And it produces following errors on the nightly build, which shouldn't be there:
```
$ tsc --pretty --noImplicitAny

27     app.use((req, res, next) => {
                ~~~

Contents/AppTopBarView.tsx(27,14): error TS7006: Parameter 'req' implicitly has an 'any' type.


27     app.use((req, res, next) => {
                     ~~~

Contents/AppTopBarView.tsx(27,19): error TS7006: Parameter 'res' implicitly has an 'any' type.


27     app.use((req, res, next) => {
                          ~~~~

Contents/AppTopBarView.tsx(27,24): error TS7006: Parameter 'next' implicitly has an 'any' type.
```
There is no error showing up on intellisense on VScode, which seems strange?. Just when I run the compiler.

I couldn't reduce it to a self-contained test, I tried an hour. So you probably have to include the typings for express to replicate the bug.

**Comment by mhegazy** [comment]
As you mentioned, this is dependent on the definition for express you are using. i am not seeing this behavior on `@types/express@4.0.33`. So if this is the same express definition you are using, we will need more details to see what is going on, if this is not the same one, then please let us know why you believe this is a compiler bug and not just a declaration issue.

**Comment by tinganho** [comment]
We have the same version. 

It turned out one express middleware `serve-static` had a copy of an older version of `express-serve-static-core` under `@types/serve-static/node_modules/express-serve-static-core`. I just deleted it and npm installed and it now works.
