### ISSUE TITLE
Provide an option to suppress errors generated by JsDoc

### ISSUE THREAD

**Issue by zhengbli** [Microsoft/TypeScript#11639]
Binding errors like "Duplicate identifiers" can be generated by JsDoc comments in JavaScript file, however as they are not technically part of the code, it would be too strict to block compiling due to these errors, especially when the code is from somewhere else. We should at least provide a compiler option to suppress diagnostics in JsDoc comments.

**Comment by mhegazy** [comment]
We can suppress these errors by default. we can enable them later on as part of https://github.com/Microsoft/TypeScript/issues/6802
