### ISSUE TITLE
Error when implementing an abstract class with a private method

### ISSUE THREAD

**Issue by yulric** [Microsoft/TypeScript#11637]
**TypeScript Version:**  2.0.3

**Code**

```ts
abstract class InterfaceClass {
	private methodToBeImplemented(argOne: string): void {

	}
}

class NormalClass implements InterfaceClass {
	private methodToBeImplemented: (argOne: string) => void 
}
```

**Expected behavior:**
I should not get an error 

**Actual behavior:** 
I get the error
Class 'NormalClass' incorrectly implements interface 'InterfaceClass'.
  Types have separate declarations of a private property 'methodToBeImplemented'.

**Comment by RyanCavanaugh** [comment]
Private methods can't be overridden (they're private!). They also can't be implemented except by their declaring class.

**Comment by aozgaa** [comment]
Perhaps you wanted `methodToBeImplemented` to be itself abstract? You provided an implementation in the base class. If you had marked it abstract, you should get an error that private methods cannot be marked abstract.
