### ISSUE TITLE
TSServer: NoEmit should be the default for JS files in mixed TS/JS projects

### ISSUE THREAD

**Issue by jramsay** [Microsoft/TypeScript#11649]
Emit errors are being generated for JS files in mixed TS/JS projects.  NoEmit is already set to true in VS host for JS only projects (projects that only contain JS, script blocks, and d.ts files). We need to handle the NoEmit scenario for JS files in the mixed project scenario.

![noemitmixedtsjs](https://cloud.githubusercontent.com/assets/8161247/19405705/a60b1cd8-922f-11e6-990a-7123a4975b80.PNG)

**Comment by mhegazy** [comment]
looks like yet another "default" to set. cc @zhengbli

**Comment by jramsay** [comment]
@zhengbli: also noticed the same issue for Misc context
