### ISSUE TITLE
Invalid code emitted when function argument is explicitly typed as null or undefined

### ISSUE THREAD

**Issue by johanssj** [Microsoft/TypeScript#11645]
**TypeScript Version:**  nightly (Version 2.1.0-dev.20161011)

**Code**
```ts
// A *self-contained* demonstration of the problem follows.
// Ditto for null, haven't tested with 'never' ...
function foo(value: undefined) {
  return value;
}
```

**Expected behavior:**
Should produce syntactically valid JavaScript.

**Actual behavior:** 
Instead this is emitted by the compiler:

```js
function foo(value: ) {
    return value;
}
```

resulting in runtime error:

```
function foo(value: ) {
                  ^
SyntaxError: Unexpected token :
```

**Comment by mhegazy** [comment]
Looks like another manifestation of https://github.com/Microsoft/TypeScript/issues/11295

**Comment by johanssj** [comment]
I concur with @mhegazy that it is indeed the case of another manifestation of #11295.

My suggestion is to mark this latest report as a duplicate of said prior issue and add my demonstration code to the test(s) for the eventual fix. Further suggest that all bottom types, viz, null, undefined & never, be included in the tested types.

**Comment by mhegazy** [comment]
should be fixed in https://github.com/Microsoft/TypeScript/issues/11653
