### ISSUE TITLE
No compiler error for script with decorators when target ES3

### ISSUE THREAD

**Issue by PFight** [microsoft/TypeScript#11658]
**TypeScript Version:**  1.7-2.0.3

**Code**

https://jsfiddle.net/PFight/vLfnpqk0/

**Expected behavior:**

Minimum target version for decorators is ES5 (that [says documentation](https://www.typescriptlang.org/docs/handbook/decorators.html)). When compiling code with target: 0 (ES3), expected to get diagnostics message, that decorators not supported for specified target. 

... or decorators for ES3 should work without differences with ES5, and documentation should be fixed.

**Actual behavior:** 

In TypeScript 1.7.0 [were added](https://www.typescriptlang.org/docs/release-notes/typescript-1.7.html#support-for-decorators-when-targeting-es3) support of decorators for ES3, and compiler error `TS1205: Decorators are only available when targeting ECMAScript 5 and higher` were removed. But, there is two differences in generated code for ES3:
1. Method and property decorators do not receive third parameter - descriptor
2. Return value of method and property decorators is ignored

For example, code <a href="https://www.typescriptlang.org/play/index.html#src=class%20MyClass%20%7B%0D%0A%09%0D%0A%09%40safe%20public%20foo(str%3A%20string%2C%20data%3A%20any)%3A%20boolean%20%7B%0D%0A%20%20%20%20return%20str.length%20%3E%200%3B%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Afunction%20safe(target%3A%20Object%2C%20propertyKey%3A%20string%2C%20descriptor)%20%7B%0D%0A%20%20var%20originalMethod%20%3D%20descriptor.value%3B%0D%0A%20%20descriptor.value%20%3D%20function%20NoErrorWrapper%20()%20%7B%0D%0A%20%20%20%20try%20%7B%0D%0A%20%20%20%20%20%20originalMethod.apply(this%2C%20arguments)%3B%0D%0A%20%20%20%20%7D%20catch(ex)%20%7B%0D%0A%20%20%20%20%20%20var%20message%20%3D%20ex.name%20%2B%20%22%20occured%20in%20call%20of%20%22%20%2B%20%0D%0A%20%20%20%20%20%20%20%20%20%20target.constructor.name%20%2B%20%22.%22%20%2B%20propertyKey%20%2B%20%22%3A%20%22%20%2B%20ex.message%20%2B%20%22%5Cn%22%3B%0D%0A%20%20%20%20%20%20message%20%2B%3D%20%22Arguments%3A%5Cn%22%3B%0D%0A%20%20%20%20%20%20%5B%5D.forEach.call(arguments%2C%20(x%2C%20i)%20%3D%3E%20%0D%0A%20%20%20%20%20%20%20%20%20message%20%2B%3D%20%22%20%20%20%5B%22%20%2B%20i%20%2B%20%22%5D%3A%20%22%20%2B%20JSON.stringify(x)%20%2B%20%22%20%5Cn%22)%3B%0D%0A%20%20%20%20%20%20message%20%2B%3D%20%22Callstack%3A%22%20%2B%20ex.stack%3B%0D%0A%20%20%20%20%20%20console.error(message)%3B%0D%0A%20%20%20%20%20%20document.body.innerHTML%20%2B%3D%20%22%3Cbr%3E%3Cpre%20style%3D'color%3A%20red'%3E%22%20%2B%20message%20%2B%20%22%3C%2Fpre%3E%22%3B%0D%0A%20%20%20%20%7D%0D%0A%20%20%7D%3B%0D%0A%20%20return%20descriptor%3B%0D%0A%7D%0D%0A%0D%0Aconsole.info(%22Starting...%22)%3B%0D%0Adocument.body.innerHTML%20%2B%3D%20%22Starting...%3Cbr%3E%22%3B%0D%0Avar%20my%20%3D%20new%20MyClass()%3B%0D%0Amy.foo(null%2C%20%7B%20answer%3A%2042%20%7D)%3B%0D%0Aconsole.info(%22Continue%20execution%22)%3B%0D%0Adocument.body.innerHTML%20%2B%3D%20%22%3Cbr%3EContinue%20execution%22%3B">work fine in playground</a>, but [fails in JSFiddle without meaningfull error](https://jsfiddle.net/PFight/3cmnctz2/), because JSFiddle uses target ES3.

**Comment by mhegazy** [comment]
@rbuckton can you take a look

**Comment by rbuckton** [comment]
We should update the documentation, because this is how we decided to support decorators for ES3 (i.e. no descriptor for methods), which is the same as how we support decorators for fields in ES3 and up.

**Comment by RyanCavanaugh** [comment]
This doesn't seem to come up often enough to warrant documentation
