### ISSUE TITLE
VS15 Preview 5: --outFile option now includes normal JS files

### ISSUE THREAD

**Issue by SaschaNaz** [Microsoft/TypeScript#11655]
**TypeScript Version:** 2.0.5.0, the version embedded on VS15 Preview 5

**Repro file:**

https://github.com/SaschaNaz/TSFileInclusionRepro/

**Repro steps:**

Add some change to ts/foo.ts to generate js/app.js automatically. For example, add `class Foo3 {}`.

**Expected behavior:**

Compiler should include TS files only

**Actual behavior:**

``` js
class Foo {
}
class Foo2 {
}
// Your code here!
var mainjs = "mainjs";
var somemodule = "somemodule";
```

**Why are you including JS files on your project?:**

Because they will be excluded from app package if I don't.

**Why do you bother?**

Because TS tries to parse my emscripten-compiled JS file and even WinJS libraries and thus slows down everything.

**Comment by SaschaNaz** [comment]
CC: @paulvanbrenk 

#11623 is not easy to repro but I have succeeded making a repro small enough for this one .

**Comment by mhegazy** [comment]
@zhenboli, this looks like the same root cause as https://github.com/Microsoft/TypeScript/issues/11649. we need some general solution here for external projects with both js and ts files

**Comment by SaschaNaz** [comment]
@mhegazy tagging zhengbli or zhenboli...?

**Comment by paulvanbrenk** [comment]
> Because they will be excluded from app package if I don't.

This is also a problem, we should include generated js files automatically.

**Comment by SaschaNaz** [comment]
TS-generated JS files are automatically included. Normal JS files are not.

**Comment by mhegazy** [comment]
@SaschaNaz, have you tried adding a tsconfig.json file?

**Comment by SaschaNaz** [comment]
Can I try the fix on VS15 Preview 5? I tried [this NuGet guide](https://github.com/Microsoft/TypeScript/wiki/Configuring-MSBuild-projects-to-use-NuGet) to get it but I still getting the same result.

This is my change: https://github.com/SaschaNaz/TSFileInclusionRepro/commit/cf7ba0b6fac0b7e19f80959cd1bbd1ccc09f9876

**Comment by mhegazy** [comment]
The fix is not included in the nuget package. It should be in a future release of VS "15".

A tsconfig should avoid the issue though.
