### ISSUE TITLE
Command-line option -w- to switch watch mode off

### ISSUE THREAD

**Issue by fantaclaus** [Microsoft/TypeScript#11663]
**TypeScript Version:**  2.0.3

Please, add a command-line option -w- (or --nowatch or something similar) to override `watch: true` setting in tsconfig.json file.

It is needed for building a project from the command line on a build server.

**Comment by mhegazy** [comment]
This shoudl be covered by https://github.com/Microsoft/TypeScript/issues/10967.

On a side note, I would actually recommend the opposite. keep your tsconfig.json with no `watch` and call `tsc --watch` when needed.

**Comment by fantaclaus** [comment]
@mhegazy Brilliant! Thanks for the idea! I've put `"args": [ "-w" ]`, into `tasks.json`. So now it works in watch mode inside VSCode, but just compiles with no watch when started from the command line.
