### ISSUE TITLE
In finally block, local variable is incorrectly typed as never.

### ISSUE THREAD

**Issue by tjhance** [Microsoft/TypeScript#11665]
**TypeScript Version:**  2.0.3

**Code**

With `--strictNullChecks`,

```ts
class A {
  constructor() { }
  method() { }
}

let a: A | null = null;

try {
  a = new A();
} finally {
  if (a) {
    a.method();
  }
}
```

**Expected behavior:**

I expect this to compile. TypeScript should be able to deduce that `a` can be of type `A` at the `a.method()` call site.

**Actual behavior:** 

I get an error message

`Property 'method' does not exist on type 'never'.`

Note that it works fine if the try and finally lines are removed.

**Comment by alitaheri** [comment]
I can confirm this with the nightly build `2.1.0-dev.20161015` too.
