### ISSUE TITLE
Removing the qualified name restriction on import targets

### ISSUE THREAD

**Issue by vlomshakov** [microsoft/TypeScript#1166]
It seems to me, it's very inconvenient, that import declaration can't have none qualified symbol as target. By the reason I have to use next way to do this:

``` typescript
class S {}

export type SS = S;
export var SS = S;
```

Maybe, removing the qualified name restriction will be more convenient than combination of type alias and var alias.

**Comment by mhegazy** [comment]
Another use-case described in https://github.com/Microsoft/TypeScript/issues/3832

**Comment by RyanCavanaugh** [comment]
Approved.

There is some slight subtlety here -- consider the following code:
```ts
namespace X {
  interface window { }
  export import Y = window;
}
// What is the meaning of X.Y?
```
You can think of two different resolution algorithms that we could use on line 3:
* For each meaning of `window` (type, value, namespace), resolve that identifier under that meaning.
  * This would mean that `Y` had the *type* of the local interface and the *value* of the global name `window`
* Resolve `window` looking for any meaning. Use all meanings which that symbol points to.
  * This would mean that `Y` *only* has the *type* of the local interface

The second interpretation is more predictable and is more likely to be what's intended.

**Comment by jbcpollak** [comment]
This is labeled as easy, for someone who is a novice to TypeScript could some guidance on implementation be added to the issue so we could look into contributing a PR?

**Comment by abhinavramesh8** [comment]
I agree with @jbcpollak. Even I feel that there should be some amount of guidance.

**Comment by mhegazy** [comment]
I would start looking at `getSymbolOfPartOfRightHandSideOfImportEquals`. this function assumes that the target is a `Namespace`, and thus looks it as such. this will fail, and you would get an error like "can not find namespace 'foo'".  I would unify this function to always resolve `SymbolFlags.Value | SymbolFlags.Type | SymbolFlags.Namespace`, write some tests, and see what else breaks..

**Comment by exx8** [comment]
Is this still a problem as I was able to do this:
A.ts:
```
 class A {

}
export =A;


```
B.ts
```
import A = require("./A");
let a:A=new A();
```

on 3.6.3

**Comment by vijaya-lakshmi-venkatraman** [comment]
Hi,
Is this still available?
