### ISSUE TITLE
Migrating to v2 getting "Cannot find name 'require'"

### ISSUE THREAD

**Issue by avanderhoorn** [Microsoft/TypeScript#11667]
**TypeScript Version:**  2.0.3 

**Code**

```ts
const test = require('./test');
```

**Expected behavior:**
That I should be able to compile the above.

**Actual behavior:** 
I'm migrating over my code base from using v1.8.10 to 2.0.3 and have managed to work through all the issues except one. In some places I'm still using classic `require` statements and as a consequence I'm getting the following error:

```
ERROR in ./src/test.ts
(7,45): error TS2304: Cannot find name 'require'.
```

**Comment by aluanhaddad** [comment]
It should be `import test = require('./test');` Unless you are doing a dynamic import. Make sure you have `"module": "commonjs"`.

**Comment by akarzazi** [comment]
Why not use the import syntax ?

From this thread: [http://stackoverflow.com/questions/31173738/typescript-getting-error-ts2304-cannot-find-name-require](url)

There are multiple solutions to this problem like
import  test = require('./test');

**Comment by avanderhoorn** [comment]
I tried that but I get other issues... The pipeline I have setup is that TypeScript targets ES6 and then Bable does the final parse and from the looks of the error TypeScript doesn't the case correctly.

Source:
```
import { syncHistoryWithStore }  = require('./history');
```
Error:
```
ModuleBuildError: Module build failed: SyntaxError: Unexpected token (5:38)

  4 | 
> 5 | import { syncHistoryWithStore } from  = require('./history');
    |                                       ^
  6 | 

    at DependenciesBlock.onModuleBuildFailed (/Users/avanderhoorn/Projects/Glimpse.Client/node_modules/webpack-core/lib/NormalModuleMixin.js:315:19)
    at nextLoader (/Users/avanderhoorn/Projects/Glimpse.Client/node_modules/webpack-core/lib/NormalModuleMixin.js:270:31)
    at /Users/avanderhoorn/Projects/Glimpse.Client/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
    at runSyncOrAsync (/Users/avanderhoorn/Projects/Glimpse.Client/node_modules/webpack-core/lib/NormalModuleMixin.js:173:4)
    at nextLoader (/Users/avanderhoorn/Projects/Glimpse.Client/node_modules/webpack-core/lib/NormalModuleMixin.js:290:3)
    at /Users/avanderhoorn/Projects/Glimpse.Client/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
    at context.callback (/Users/avanderhoorn/Projects/Glimpse.Client/node_modules/webpack-core/lib/NormalModuleMixin.js:148:14)
    at Object.loader (/Users/avanderhoorn/Projects/Glimpse.Client/node_modules/ts-loader/index.js:470:5)
    at WEBPACK_CORE_LOADER_EXECUTION (/Users/avanderhoorn/Projects/Glimpse.Client/node_modules/webpack-core/lib/NormalModuleMixin.js:155:71)
    at runSyncOrAsync (/Users/avanderhoorn/Projects/Glimpse.Client/node_modules/webpack-core/lib/NormalModuleMixin.js:155:93)
    at nextLoader (/Users/avanderhoorn/Projects/Glimpse.Client/node_modules/webpack-core/lib/NormalModuleMixin.js:290:3)
    at /Users/avanderhoorn/Projects/Glimpse.Client/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/Users/avanderhoorn/Projects/Glimpse.Client/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /Users/avanderhoorn/Projects/Glimpse.Client/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:404:3)
BabelLoaderError: SyntaxError: Unexpected token (5:38)
```

**Comment by aluanhaddad** [comment]
Thanks for clarifying it's now clear what the issue is. If you're using `"module": "es6"` TypeScript is correctly operating under the assumption that the target environment natively supports modules. This could be a hypothetical browser or a format aware loader like to sandria

**Comment by aluanhaddad** [comment]
Sorry for the double post I accidentally hit enter. In such an environment, and for that matter any environment besides a node, there's no reason to assume the presence of a require function at all. Furthermore, `import...require` forms never supported destructuring imports. It seems like you are getting around this restriction by using `const` instead of `import`, but this has always resulted in the loss of type information. Basically you need to define a type for the require function but in general you should move away from using this form of import if you're targeting ES Modules I'm typing the output into Babel then you want to have Babel handle all of the module transformations I'm simply use es6 syntax everywhere

**Comment by avanderhoorn** [comment]
I agree that its something at we should move away from but migrating large code bases all at once just doesn't happen... hence we where using `const`s in places where we didn't yet what to spend the time to migrate the targeted code or create a definition for it. This did work with 1.x, I'm still not clear why is it not working in 2.x.

**Comment by aluanhaddad** [comment]
Perhaps you have type definitions in your environment that are no longer being picked up because of a change in module resolution logic but it's hard to say. In order to use `require` as a function you need to provide a type for it. You cannot use require as an import statement with `"module": "es6"`. If it was working before it sounds like it was a bug.

**Comment by mhegazy** [comment]
@avanderhoorn, for the original issue, function calls to `require` are not special. if you want to use it, you will need to define it:

```ts
declare function require(arg:string): any;
```

Please note that does not give you the module object type. if you want to require a module, switch to 

```ts
import test = require('./test');
```

**Comment by mhegazy** [comment]
Also please see more documentation in http://www.typescriptlang.org/docs/handbook/modules.html
