### ISSUE TITLE
Incorrect code generation

### ISSUE THREAD

**Issue by lazutkin** [Microsoft/TypeScript#11669]
Not sure is it an error or _by design_, but I expected a snippet that follows should be compiled, but absence of `;` symbol lead to `call statement` to be issued instead of `assignment`

**TypeScript Version:**  2.0.3 / nightly (2.1.0-dev.201xxxxx)

**Code**

```ts
interface Some {
    a: string
    b: string
}

var x

(x as Some).a = "a" //<<-- to get rid of an error just put ';' symbol here
(x as Some).b = "b"
```

**Comment by wallverb** [comment]
That's _by JS design_ ;)

you can do
```js
alert
('hi')
``` 
in js

so basically you are trying to do:

```ts
(x as Some).a = "a"(x as Some).b = "b"
```

That's why `;` is important here

**Comment by DanielRosenwasser** [comment]
Yup, thanks @wallverb. This is because the JS is syntactically valid, so a semicolon wasn't automatically inserted for you. TypeScript correctly warned you about you trying to call a string in this code.
