### ISSUE TITLE
Cannot find name of imported function

### ISSUE THREAD

**Issue by kmaraz** [Microsoft/TypeScript#11668]
**TypeScript Version:**  2.0.3

**Code**

Foo.ts:
```ts
export default function Foo(): any {}
```
Bar.ts:
```ts
import Foo from './path/to/my/fn/Foo'

export default class Bar {
  constructor(
    private Foo: Foo, // Second Foo is underlined. Error: 'Cannot find name Foo.'
  ) {}
}
```

When using Foo as a type definition, it throws an error. Is this a intended behavior? Can you please refer me to the specification where is this discussed or help me with this? Thank you!

**Comment by alitaheri** [comment]
This is `By Design`. In order to use a function as type you have 2 options:

**1**. use `typeof`

```ts
export default class Bar {
  constructor(
    private foo: typeof Foo, // you will have to rename the property or the names will clash.
  ) {}
}
```

**2**. use `interface`

```ts
export default interface Foo {
  // this is function signature. 
  (): void;
  // you can overload it and stuff:
  (a: number): string;
}
```

**Comment by aluanhaddad** [comment]
@alitaheri all of your advice is good and your solution works, but you lose the simplicity of the default import sugar needlessly.

I think a better solution, and one that preserves the structure of any code consuming `foo.ts` is
_foo.ts_
```ts
type Foo = ((a: number) => string) & (() => void);

function Foo(a?: number): string | void { }

export default Foo;
```
_bar.ts_
```ts
import Foo from './foo';

class Bar {
    Foo: Foo;
}
Foo(); // call foo as a function
```

**Comment by alitaheri** [comment]
Didn't know you could do that O.o

Thanks a lot 👍 👍 👍

**Comment by aluanhaddad** [comment]
I just realized there in my example, I lost the correspondence between the type `Foo` and the function `Foo` within the module _foo_. I fixed the example.
