### ISSUE TITLE
Number methods should support type guards

### ISSUE THREAD

**Issue by errorx666** [Microsoft/TypeScript#11670]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isInteger

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isSafeInteger

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isFinite

etc

When these methods return `true`, the value should be asserted to be non-null Number type.

**Comment by aluanhaddad** [comment]
This sounds like a good idea.  One minor correction, these are not methods of `Number.prototype` but rather of the `Number` function.

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by aleksey-bykov** [comment]
i really like it! (suggestion! accepting prs!)

so what exactly is a number bigger than 0 as far as the types?

```
function isPositive(value: number): value is number & .....? { // <--- replace .....? with something meaningful
}
```

**Comment by mhegazy** [comment]
you would only use `number`. the argument should allow non-numeric types as well.

```
declare function isInteger(value: any): value is number ;
```

**Comment by aleksey-bykov** [comment]
oh, nevermind then

**Comment by aluanhaddad** [comment]
@aleksey-bykov still a good question. Maybe in the future the TypeScript's type system will be so advanced that it will be able to infer discrete vs continuous types O.O

**Comment by RyanCavanaugh** [comment]
This turns out to be a bad idea because type guards need to return true for all of the values in the domain of their guarded type, not just some of them. In other words, with the proposed definition:
```ts
let x: number | string = ...;
if (typeof x === 'string') {

} else if (isInteger(x)) {
  // x: number
} else {
  // We assume 'x: never' in this block!
  // error
  console.log(x.toFixed(2));
}
```

**Comment by aluanhaddad** [comment]
I see. That is definitely a problem. This really did seem like a good idea but I guess I didn't really think it through.
