### ISSUE TITLE
reference path apparently ignores rootDir(s)

### ISSUE THREAD

**Issue by dmitriid** [Microsoft/TypeScript#11678]
**TypeScript Version:**  2.0.3

**Code**

Project structure:

```
|- tsconfig.json
|- app
    |- fsm
    |  |- state-manager.ts
    |- type-declarations
       |- machina.d.ts
```
`tsconfig.json`:
```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "declaration": false,
    "noImplicitAny": false,
    "removeComments": true,
    "experimentalDecorators": true,
    "noLib": false,
    "jsx": "react",
    "outDir": "dist",
    "rootDir": "./app"
  },
  "exclude": [
    "node_modules",
    "static"
  ]
}
```

`app/fsm/state-manager.ts`:

```ts
/// <reference path="/type-declarations/machina.d.ts" />

import * as machina from 'machina'; // etc.
```

`app/type-declarations/machina.d.ts`:
```ts
declare module machina;
```

**Expected behavior:**

According to [docs](https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html): "A triple-slash reference path is resolved relative to the containing file, if unrooted."

I expected the reference to be resolved to `app/type-declarations/machina.d.ts`.

**Actual behavior:** 

```
> tsc -p ./tsconfig.json
app/fsm/state-manager.ts(1,1): error TS6053: File '/type-declarations/machina.d.ts' not found.
```

Same happens for any combination of `rootDir`, `rootDirs`.

**Comment by DanielRosenwasser** [comment]
I think you want

```ts
declare module "machina"
```

Notice the quotes.

**Comment by dmitriid** [comment]
Yeah, sorry. I was writing without really looking into the code :)

It's `declare module 'machina'` in the declaration file

**Comment by dmitriid** [comment]
On the other hand, apparently this happened because I was using webpack.

When running just `tsc` it picked up everything correctly, even without `<reference>`.

**Comment by mhegazy** [comment]
The reference is not needed. the tsconfig.json should include all `.ts` and all `.d.ts` in the folders. Looks like a ts-loader bug then.

**Comment by dmitriid** [comment]
Ok. I realised the cause for this (though I won't find the links to relevant tickets). AFAIR webpack (and rollup) process files sequentially whereas typescript takes the whole project into consideration. This may and will break.

Solved this by running `tsc` to transpile files and then running webpack to bundle.

Closing this as not a TS issue.
