### ISSUE TITLE
Non-Exported Member blocked from being a return typing.

### ISSUE THREAD

**Issue by bholbrook73** [Microsoft/TypeScript#11674]
**TypeScript Version:**  1.8.10

**Code**

``` ts
namespace Model {
    class Entity {
        public id:number;
    }
    export class Factory {
        static getById(id):Entity{
            // external source provides data
            let data = Library.getDataFromSomewhereElse(id);
            let oEntity = new Entity();
            oEntity.id = data.id;
            return oEntity;
        }
    }
}

namespace Controller {
    getEntity(request, reply):Model.Entity{
        reply(Model.Factory.getById(request.params.id));
    }
}
```

**Expected behavior:**
The return of Controller.getEntity SHOULD allow the return typing to be of a non-exported class. The above example shows how the instance creation of a class is protected by a factory - but is still a valid return type.

**Actual behavior:** 
The Model.Entity is not allowed as a return type downstream because the class is not exported.

**Comment by vladima** [comment]
if this is allowed then immediate question is:
```ts
// d.ts file for the code in question
namespace Model {
    export class Factory {
        static getById(id: any): ???; // what should be written as a return type for this method?
    }
}
```

in your case you can split interface and implementation and make `getById` return an interface hiding the implementation
