### ISSUE TITLE
IntrinsicElements Not Working as Documented

### ISSUE THREAD

**Issue by jedmao** [Microsoft/TypeScript#11684]
**TypeScript Version:**  2.0.3 and 2.0.6-insiders.20161014
**vscode Version:** 1.6.1 and 1.7.0-insider

Not sure if this is a TS issue or a vscode issue.

**Code**
Pulling from [the wiki's Intrinsic Elements section](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/JSX.md#intrinsic-elements), which matches [the documentation](http://www.typescriptlang.org/docs/handbook/jsx.html#intrinsic-elements):

```ts
declare namespace JSX {
    interface IntrinsicElements {
        foo: any
    }
}

<foo />; // ok
<bar />; // error
```

**Expected behavior:**
```ts
<foo />; // ok
```

**Actual behavior (Intellisense):** 

> [ts] Property 'foo' does not exist on type 'JSX.IntrinsicElements'.

![image](https://cloud.githubusercontent.com/assets/1058243/19449354/e267d01c-946a-11e6-8d70-d0da69c5a21f.png)

**Work-around:**

Wrap the namespace declaration in a `declare global`:

```ts
declare global {
    namespace JSX {
        interface IntrinsicElements {
            foo: any
        }
    }
}
```

**Work-around result (Intellisense):**

> (property) JSX.IntrinsicElements.foo: any

![image](https://cloud.githubusercontent.com/assets/1058243/19449584/bdc691e8-946b-11e6-9aaf-93c3fc762603.png)

Is the documentation wrong?

**Comment by RyanCavanaugh** [comment]
Your file, which is a module (otherwise `declare global` wouldn't have been legal), doesn't contribute types or namespaces into the *global* namespace. JSX looks for the *global* type `JSX.IntrinsicElements`; it does not look for a "local" type of that name.

This is similar to how the special type `Array` is only used from the global namespace, e.g. `string[]` is an alias for `Array<string>` from the global namespace, not a lookup from the local scope of `Array`.

**Comment by jedmao** [comment]
Thanks @RyanCavanaugh. It looks like this is by design then.

**Comment by flying-sheep** [comment]
how would you define and use new intrinsic tags from a package?

i’d be interested in configuring typescript to recognize all electron tags.

**Comment by jedmao** [comment]
I have the same question for BEM tags (block, element, modifiers), which can exist on any DOM element. How do we define custom tags for all DOM elements? Might need to create a new issue for that though and i intend to when i have the time.

**Comment by jedmao** [comment]
See http://stackoverflow.com/questions/40093655/how-do-i-add-attributes-to-existing-html-elements-in-typescript-jsx?noredirect=1#comment71310476_40093655
