### ISSUE TITLE
Can not extend built in types

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#1168]
The ES6 designates some native objects as subclassable, e.g. Object, Boolean, Error, Map, Promise ..etc. The way these constructs are modeled in lib.d.ts makes is impossible to subclass, as they are defined as a pair of a var and an interface.

From the ES6 spec section19.5.1:
>The Error constructor is designed to be subclassable. It may be used as the value of an extends clause of a class declaration. Subclass constructors that intended to inherit the specified Error behavior should include a super call to the Error constructor to initialize subclass instances.

Currently this would result in "A class can only extend another class" error:
```TypeScript
class NotImplementedError extends Error {
    constructor() {
        super("Not Implemented");
    }
}
```

**Comment by unional** [comment]
When I extend the Error class this way (using ambient class definition), throwing the ExtendedError does not produce stack trace nor assign message properly.

````
declare class Error {
  constructor(message?: string);
}

class ExtendedError extends Error {
  constructor(message?: string) {
    super(message + " extended");
  }
}

//throw new Error("Test");
throw new ExtendedError("Test");
````

**Comment by mhegazy** [comment]
@unional this looks like an engine issue. as per ES6 spec it should work. Engines should be fixing these now that ES6 has become ratified.

**Comment by unional** [comment]
For comparison, here is a simple Exception class that takes innerException.

Code generated using code above:

````
var Exception = (function (_super) {
            __extends(Exception, _super);
            function Exception(message, innerException) {
                // Guard against throw Exception(...) usage.
                if (!(this instanceof Exception))
                    return new Exception(message, innerException);
                _super.call(this, message);
                this.name = "Exception";
                this.message = message;
                this.innerException = innerException;
            }
            Exception.prototype.toString = function () {
                var message = this.name + ": " + this.message;
                if (this.innerException) {
                    message += ', innerException: \n' + this.innerException.toString();
                }
                return message;
            };
            return Exception;
        })(Error);
````

The code that I use (writing it directly in JS):

````
function Exception(message, innerException) {
    // Guard against throw Exception(...) usage.
    if (!(this instanceof Exception)) return new Exception(message, innerException);
    Error.call(this);
    //noinspection JSUnresolvedVariable
    if (typeof Error.captureStackTrace === 'function') {
        //noinspection JSUnresolvedFunction
        Error.captureStackTrace(this, arguments.callee);
    }
    this.name = "Exception";
    this.message = message;
    this.innerException = innerException instanceof Error? innerException : new Error(innerException);
}

Exception.prototype.__proto__ = Error.prototype;
Exception.prototype.toString = function() {
    var message = this.name + ": " + this.message;
    if (this.innerException) {
        message += ', innerException: \n' + this.innerException.toString();
    }

    return message;
};
````

The one I wrote works while the generated one doesn't (there is no message and no stack trace).
When I use my code, tsc complains:

````
src/ts/Exception.ts(38,46): error TS2350: Only a void function can be called with the 'new' keyword.
src/ts/Exception.ts(41,22): error TS2339: Property 'captureStackTrace' does not exist on type 'ErrorConstructor'.
src/ts/Exception.ts(43,15): error TS2339: Property 'captureStackTrace' does not exist on type 'ErrorConstructor'.
````

**Comment by unional** [comment]
I managed to get it to work.  There is an example code:

It's an C#-like Exception that takes an innerException.

````
declare class Error {
    public name:string;
    public message:string;
    public stack:string;
    constructor(message?:string);
    static captureStackTrace(error: Error, constructorOpt: any);
}

class Exception extends Error {
    public innerException: Error;
    constructor(message?: string, innerException?: Error|string) {
        // Guard against throw Exception(...) usage.
        if (!(this instanceof Exception)) return new Exception(message, innerException);
        super();
        if (typeof Error.captureStackTrace === 'function') {
            //noinspection JSUnresolvedFunction
            Error.captureStackTrace(this, arguments.callee);
        }
        this.name = "Exception";
        if (innerException) {
            if (innerException instanceof Error) {
                this.innerException = innerException;
            }
            else if (typeof innerException === "string") {
                this.innerException = new Error(innerException);
            }
        }

        this.message = this.innerException? message + ", innerException: " + this.innerException.message : message;
    }
}
````

**Comment by ahejlsberg** [comment]
Fixed by #3516. Classes can now extend arbitrary expressions of constructor function types.

**Comment by kostrse** [comment]
What release of TypeScript this fix is going to be shipped?
I quickly checked release labels for 1.5.3 and 1.5.4, and seems it hasn't been shipped yet, only in master for now.

Thanks for your work!

**Comment by DanielRosenwasser** [comment]
@kostrse you can try our nighty releases of TypeScript 1.6 by running `npm install -g typescript@next`.

**Comment by jpsfs** [comment]
Hi,

I'm using Typescript 1.6.2 and my lib.es6.d.ts show Error (and Array<T>, ...) as Interface not class.
Is this already fixed in 1.6.2?

Cheers!

**Comment by mhegazy** [comment]
@jpsfs the fix, as noted by @ahejlsberg in https://github.com/Microsoft/TypeScript/issues/1168#issuecomment-112955503  is to allow classes to extend arbitrary expressions of constructor function types.

**Comment by pleerock** [comment]
Even there is ability to extend `Error` class nowdays, Im still having inconvenience with it on node. For example Im having troubles with "error.stack". When I do `throw new Error(...)` I get `error.stack`, but when I do `throw new CustomError()` - I don't. To solve it I forced to use this trick:

```typescript
export class HttpError extends Error {
    httpCode: number;
    message: string;

    constructor(httpCode: number, message?: string) {
        super();
        if (httpCode)
            this.httpCode = httpCode;
        if (message)
            this.message = message;

        this.stack = new Error().stack;
    }
}
```
