### ISSUE TITLE
C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.8\lib.d.ts has many errors with SVGElement

### ISSUE THREAD

**Issue by jhandel** [Microsoft/TypeScript#11689]
**TypeScript Version:**  1.8.36 
**Code**
No TS code we could find related to the issue in our project (we never touch the SVGElement interface)

**Expected behavior:**
Application compiles without errors from the lib.d.ts file 

**Actual behavior:** 
1>C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.8\lib.d.ts(12844,11): error TS2320: Build:Interface 'SVGFEBlendElement' cannot simultaneously extend types 'SVGElement' and 'SVGFilterPrimitiveStandardAttributes'.
1>C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.8\lib.d.ts(12890,11): error TS2320: Build:Interface 'SVGFEColorMatrixElement' cannot simultaneously extend types 'SVGElement' and 'SVGFilterPrimitiveStandardAttributes'.
1>C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.8\lib.d.ts(12912,11): error TS2320: Build:Interface 'SVGFEComponentTransferElement' cannot simultaneously extend types 'SVGElement' and 'SVGFilterPrimitiveStandardAttributes'.
1>C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.8\lib.d.ts(12922,11): error TS2320: Build:Interface 'SVGFECompositeElement' cannot simultaneously extend types 'SVGElement' and 'SVGFilterPrimitiveStandardAttributes'.
1>C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.8\lib.d.ts(12952,11): error TS2320: Build:Interface 'SVGFEConvolveMatrixElement' cannot simultaneously extend types 'SVGElement' and 'SVGFilterPrimitiveStandardAttributes'.
1>C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.8\lib.d.ts(12981,11): error TS2320: Build:Interface 'SVGFEDiffuseLightingElement' cannot simultaneously extend types 'SVGElement' and 'SVGFilterPrimitiveStandardAttributes'.
1>C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.8\lib.d.ts(12995,11): error TS2320: Build:Interface 'SVGFEDisplacementMapElement' cannot simultaneously extend types 'SVGElement' and 'SVGFilterPrimitiveStandardAttributes'.
1>C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.8\lib.d.ts(13029,11): error TS2320: Build:Interface 'SVGFEFloodElement' cannot simultaneously extend types 'SVGElement' and 'SVGFilterPrimitiveStandardAttributes'.
1>C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.8\lib.d.ts(13070,11): error TS2320: Build:Interface 'SVGFEGaussianBlurElement' cannot simultaneously extend types 'SVGElement' and 'SVGFilterPrimitiveStandardAttributes'.
1>C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.8\lib.d.ts(13083,11): error TS2320: Build:Interface 'SVGFEImageElement' cannot simultaneously extend types 'SVGElement' and 'SVGFilterPrimitiveStandardAttributes'.
1>C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.8\lib.d.ts(13093,11): error TS2320: Build:Interface 'SVGFEMergeElement' cannot simultaneously extend types 'SVGElement' and 'SVGFilterPrimitiveStandardAttributes'.
1>C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.8\lib.d.ts(13111,11): error TS2320: Build:Interface 'SVGFEMorphologyElement' cannot simultaneously extend types 'SVGElement' and 'SVGFilterPrimitiveStandardAttributes'.
1>C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.8\lib.d.ts(13130,11): error TS2320: Build:Interface 'SVGFEOffsetElement' cannot simultaneously extend types 'SVGElement' and 'SVGFilterPrimitiveStandardAttributes'.
1>C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.8\lib.d.ts(13153,11): error TS2320: Build:Interface 'SVGFESpecularLightingElement' cannot simultaneously extend types 'SVGElement' and 'SVGFilterPrimitiveStandardAttributes'.
1>C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.8\lib.d.ts(13184,11): error TS2320: Build:Interface 'SVGFETileElement' cannot simultaneously extend types 'SVGElement' and 'SVGFilterPrimitiveStandardAttributes'.
1>C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.8\lib.d.ts(13194,11): error TS2320: Build:Interface 'SVGFETurbulenceElement' cannot simultaneously extend types 'SVGElement' and 'SVGFilterPrimitiveStandardAttributes'.

Again, none of our code (declarations or actual code) go anywhere near the SVGElement...

**Comment by mhegazy** [comment]
This means that in your application you have reopened `Element` or other definitions that `SVGElement` depends on, and thus breaking the inheritance rules listed above.
