### ISSUE TITLE
Using lodash method categories

### ISSUE THREAD

**Issue by alisabzevari** [Microsoft/TypeScript#11682]
**TypeScript Version:**  nightly (2.1.0-dev.20161017)

I wanted to use lodash method categories. Here is the code I wrote:

``` ts
import assign from "lodash/assign";
var myVar = assign({}, {foo:"foo"}, {bar:"bar"});
```

**Expected compiled result:**

``` js
"use strict"
const assign_1 = require("lodash/assign");
var myVar = assign_1({}, {foo:"foo"}, {bar:"bar"});
```

**Actual compiled result:** 

``` js
"use strict"
const assign_1 = require("lodash/assign");
var myVar = assign_1.default({}, {foo:"foo"}, {bar:"bar"});
```

**Some notes:**
- I am using @types/lodash and the definition of assign is:

``` ts
declare module "lodash/assign" {
   const assign: typeof _.assign;
   export = assign;
}
```
- I found out if I remove allowSyntheticDefaultImports and change `import * as assign from "lodash/assign";`, it will work.

**Comment by aluanhaddad** [comment]
That is what `allowSyntheticDefaultImports` is designed to do, model the behavior of loaders or transpilers that ease the consumption of commonjs modules from ES6 modules by mapping `export = x` that is `module.exports = ` to `export default x`.

**Comment by alisabzevari** [comment]
@aluanhaddad Yes, exactly. But when you have this switch, the code would not compile correctly.

**Comment by RyanCavanaugh** [comment]
> ```import assign from "lodash/assign";```

This is *unambiguously* an import of the `default` member of the module.

Regarding using `import * as ` with a function, see http://stackoverflow.com/questions/39415661/why-cant-i-import-a-class-or-function-with-import-as-x-from-y

**Comment by alisabzevari** [comment]
Thanks for reply. Maybe I am confused in module standard definitions but expected behaviour for me is that turning on the 'allowSyntheticDefaultImports' switch should enable me to work with non-standard way of importing a module. But it doesn't work on lodash!
Correct me if I am wrong.
