### ISSUE TITLE
[Errors] error recovery with missing = in property initializers

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#117]
```TypeScript
export class Point implements IPoint {
        public con:C "hello";
```

Expected: !!! '=' expected.

Actual: !!! ';' expected.

**Comment by DickvdBrink** [comment]
Fixed in playground and 
Baseline can be found here: https://github.com/Microsoft/TypeScript/blob/master/tests/baselines/reference/parserErrorRecovery_IncompleteMemberVariable2.errors.txt

**Comment by danquirk** [comment]
Thanks for the help.
