### ISSUE TITLE
REST parameters in functions behave unexpectedly

### ISSUE THREAD

**Issue by tuxbox** [Microsoft/TypeScript#11705]
**TypeScript Version:**  2.0.3

**Code**
```ts
class T {
  a(...params:Array<string>) {
    this.c(params); //fails to compile, see below
  }

  b() {
    this.c(new Array<string>());  //fails to compile, see below
  }

  c(...params:Array<string>) {

  }

  d() {
    this.c("a","b"); //works
  }
}
```

**Expected behavior:**
using REST parameters in functions I expect to be able to pass an array in as parameter as well as a set of strings (see d()).
I expect the functions call to c() in a() and b() to be valid typescript syntax resulting in:
1) I can pass REST params from one function to another
2) I can pass arrays as REST param
3) I can pass any number of strings

**Actual behavior:** 
1) & 2) don't work. the compile step fails with:

error TS2345: Argument of type 'string[]' is not assignable to parameter of type 'string'

**Comment by RyanCavanaugh** [comment]
This just isn't how it works. You need to use the spread operator `...`, or `apply`, if you want to turn an array into an argument list.
