### ISSUE TITLE
Why there is no document about Generator?

### ISSUE THREAD

**Issue by jcodebrain** [microsoft/TypeScript#11706]
I wanted to read about Generator in detail  on Typescript offical website; however, I couldn't find even any small explanation in the official document. I strongly believe that Typescript has adopted the feature since Typescript 1.6. But no good info for beginners.
this is all and no info even though generator is one of the important features in ECMAScript6.
https://www.typescriptlang.org/docs/handbook/iterators-and-generators.html 

Of course, there is a few decent docs in terms of ECMAScript 6 Generator outside, but not Typescript 
Could you tell me where I can find some decent Generator document for beginners to use properly ?

**Comment by chicoxyzzy** [comment]
TS generators and ES generators are the same thing so ES6 generators docs are good for start.

**Comment by jcodebrain** [comment]
@chicoxyzzy I know, but I consider the official doc is supposed to give an explanation for beginners. 
As you can see, there is no info at all. I am pointing that.

**Comment by mhegazy** [comment]
Tracked by https://github.com/Microsoft/TypeScript-Handbook/issues/552

**Comment by SteveALee** [comment]
Worse than that - it would appear generators are not supported as they are not mentioned - despite being in the title!

Further confusion caused by http://kangax.github.io/compat-table/es6/#test-generators not having a column for TypeScript itself. The one it has for TS 1.8 says generators are not supported.

**Comment by RyanCavanaugh** [comment]
I mean, we don't document `for` loops either, but those we do support them 😛

**Comment by SteveALee** [comment]
OK fair point :) Though generators are a new feature not an old fundamental so you might not support them. You don't have a table of es5 / es6 etc features as they are implemented

But do please remove form the chapter title if they are not included in the body.

**Comment by sylvanaar** [comment]
It is important to understand the limitations in the transpilation of generators down to ES5 and ES3 - that is why they need documentation.

**Comment by RyanCavanaugh** [comment]
This doesn't seem to be a common point of friction
