### ISSUE TITLE
New "Friends of TypeScript" Logo: Het Financieele Dagblad

### ISSUE THREAD

**Issue by willemliu** [Microsoft/TypeScript#11729]
Please fill the following out:
- Name: Het Financieele Dagblad
- Homepage url: https://fd.nl
- Brand Guidelines/Licensing: You can use the logo on the "Friends of TypeScript" page.
- Logo: https://static.fd.nl/media/images/mediakit/FD+Logo.svg

**Comment by teunw** [comment]
Maybe change the title to something like: "New friend of Typescript, Het Financieele Dagblad"?
Makes more clear what you're trying to achieve.

**Comment by willemliu** [comment]
To shed a bit more light in how TypeScript is used in this particular case. We were studying the use of ES2015 with our project. This led to the consideration between Babel and TypeScript as transpilers. We eventually chose TypeScript because it gave us more than just the new syntax and language features.
Improved IDE support (in our case Intellij) was a major reason for choosing TypeScript over Babel.
TypeScript also allowed us to mix our old JS code with new TS. This meant we were able to transition into TypeScript at our own pace (no big bang needed).
So we can slowly rewrite some old modules when we have some slack in our Sprints.

**Comment by willemliu** [comment]
I see the ticket is closed. But I don't see our logo in the Friends page. When can we expect to see the logo on the site?

**Comment by mhegazy** [comment]
I have updated the site content. should be visible the next time we publish it.

**Comment by willemliu** [comment]
Thanks Mohamed!
