### ISSUE TITLE
Visual Studio 2015 stop working when install Typescript 2.0.3.0

### ISSUE THREAD

**Issue by tuannla07** [Microsoft/TypeScript#11731]
**TypeScript Version:**  2.0.3 
**VS Version:**  Visual Studio 2015 updated 3
**OS Version:**  Window Server 2012

**Actual behavior:** 

When we upgrade from typescript 1.8.4 to 2.0.3 , we open vs2015 , everything fine except opening *.ts files , it make our VS not responding and ask for restart every time. I have tried uninstall and reinstall TypeScript 2.0.3 , sometime it not asking for restarting VS but lost all Syntax Highlighting and intellisense

**Comment by Jordan-Hall** [comment]
This version also seems to have a syntax highlighting issue

**Comment by mhegazy** [comment]
Looks like you are running into https://github.com/Microsoft/TypeScript/issues/11110. We are preparing a new release (2.0.6) in the next week to address this issue.

**Comment by tuannla07** [comment]
Just for infomation , we are using VS2015 Community version ,it not happend for some people that use Enterpirse or Ultimate .

**Comment by mhegazy** [comment]
Our analysis show this is related to the existence of the internationalization supporting binaries. it seems to be OS/IE version-dependent and not VS version-dependent.
