### ISSUE TITLE
Suggestion: Intellisense support in JSDoc comments

### ISSUE THREAD

**Issue by MaleDong** [Microsoft/TypeScript#1173]
It would be better if you say below on a function, something like this following:

/*
 Descriptions: ……
 @num1:……
 @num2:……
*/
function add(num1:number,num2:number)
{
 ……
}

Notice that "Descriptions", "@num1","@num2" will be automatically shown according to the context of the function itself, just like those of C#'s xml comment style, when you wanna add a comment after "*" and press "Enter", an intellisense list will show to you.

**Comment by brinca** [comment]
I vote for this feature as well ;)

**Comment by mhegazy** [comment]
JSDoc scaffolding and basic completion should be working now.
