### ISSUE TITLE
no-unused-locals: Allow `_` in local name.

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#11734]
**TypeScript Version:**  nightly (2.1.0-dev.20161019)

**Code**

```ts
for (const _ of []) {}
```

**Expected behavior:**

No error

**Actual behavior:** 

src/a.ts(1,12): error TS6133: '_' is declared but never used.

We should allow unused locals beginning with `_`. We already do this for `no-unused-parameters`.

**Comment by mhegazy** [comment]
for `for..of` you can just use `for (const {} of []) {}`. but for `for..in` there is no equivalent. i would say we can do it for both for consistency, though `for..of` is not really needed.
