### ISSUE TITLE
Code editing sequence matters for typing acquisition

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/TypeScript#11744]
**OS Version:** macOS
**TypeScript Version:**  typescript@^2.0.6-insiders.20161014 using vscode 1.7 insiders

Note:   ` "typescript.experimentalAutomaticTypeAcquisition": true` must be in your vscode user settings.

**Steps to Reproduce**
- 1. clear `~/Library/Application Support/Microsoft/TypeScript/node_modules/@types`
- 2. start vscode on an workspace with the following two files:
`package.json`
```json
{
    "name": "test",
    "version": "0.0.1",
    "dependencies": {
        "express" : "4.14.0"
    },
    "engines" : {
        "node" : "6.7.0",
        "npm" : "3.10.x"
    }
}
```
`test.js`
```js
var fs = require('fs');
fs.
```
- 3. open `test.js` in editor
- 4. append to the file:
```js
var calendar = require('node-calendar');
calendar.
```
- 5. invoke inteliisense; no proposals
- 6. open `package.json` in the editor
- 7. add the following dependency
```json
        "node-calendar" : "0.1.4"
```
- 8. go back to `test.js`
- 9. place caret behind `calendar.` and invoke intellisense using <kbd>Cmd+Space</kbd>

**Expected behavior:**
Intellisense proposals for the `node-calendar` module are presented

**Actual behavior:** 
No `node-calendar` specific proposals are shown. `~/Library/Application Support/Microsoft/TypeScript/node_modules/@types` remains unchanged.

- 10. restart vscode
- 11. repeat steps 8. and 9.

-> Intellisense proposals for the `node-calendar` module are presented

**Note:** When first adding the dependency for `node-calendar` in `package.json` and then adding the require in `test.js` auto acquisition and intellisense work as expected.

**Comment by mhegazy** [comment]
Step 4 is covered by https://github.com/Microsoft/TypeScript/issues/11256. 

step 9 should work even without https://github.com/Microsoft/TypeScript/issues/11256. we need to look at this.

**Comment by vladima** [comment]
I've tried step 9 with a minor modification - use different source file
```js
import * as c from "node-calendar";
c.
var calendar = require('node-calendar');
calendar.
```
After adding entry to `package.json` I can see in log of typings installer that typings for `node-calendar` were installed and completion appear after `c.` but requesting completions after `calendar.` still shows nothing

**Comment by vladima** [comment]
at glance this is a consequence of [this change](https://github.com/Microsoft/TypeScript/pull/11373) - `node.d.ts` declares [require](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/node/node.d.ts#L58) function which prevents `var calendar = require('node-calendar');` to be treated as module loading request

**Comment by vladima** [comment]
I cannot repro this issue using Ubuntu 16.04.1 LTS, TS: 2.0.6-insiders.20161017, VSCode 1.7.0 insider.
After repeating steps in description I'm getting  proper intellisense. Can you please re-check it on the latest insider build to see if you still can see the issue?

**Comment by vladima** [comment]
https://github.com/Microsoft/TypeScript/issues/11752 is filed to track issue with missing completions after `require`

**Comment by mhegazy** [comment]
closing this in favor of #11256 and #11752

**Comment by vladima** [comment]
This is a different issue, will send a PR with a fix
