### ISSUE TITLE
export default interface/abstract class

### ISSUE THREAD

**Issue by vp2177** [Microsoft/TypeScript#11749]
`interface Foo {}; export default Foo` works, please also make the more elegant `export default interface Foo {}` work.

Similarly, `abstract class Bar {}; export default Bar` works, please make `export default abstract class Bar {}` work.

**TypeScript Version:**  2.0.3

**Comment by yortus** [comment]
duplicate of #3792

**Comment by mhegazy** [comment]
Please search existing issues before filing a new one.

![image](https://cloud.githubusercontent.com/assets/8000722/19572451/264435fc-96b7-11e6-8ccc-45311bfac788.png)
