### ISSUE TITLE
Different behaviour for enum comparisons depending on context

### ISSUE THREAD

**Issue by bthomsons** [Microsoft/TypeScript#11748]
**TypeScript Version:**  2.0.3 

**Code**

```ts
export const enum HideCategory {
    Never,
    ForZeroTotal,
    ForNoLineItems,
    ForNoCards
}

export interface Category {
    hideCategory: HideCategory;
}

function test() {
    var x: Category = { hideCategory: HideCategory.Never };

    /* this doesn't work*/
    if (x.hideCategory && x.hideCategory != HideCategory.Never)
    {

    }

    /*this works when I put a != null check*/
    if (x.hideCategory != null && x.hideCategory != HideCategory.Never)
    {

    }

    /*this works*/
    var boolCheck: boolean = x.hideCategory != HideCategory.Never; 
}

```

link here [typescript example](http://www.typescriptlang.org/play/index.html#src=%0D%0Aexport%20const%20enum%20HideCategory%20%7B%0D%0A%20%20%20%20Never%2C%0D%0A%20%20%20%20ForZeroTotal%2C%0D%0A%20%20%20%20ForNoLineItems%2C%0D%0A%20%20%20%20ForNoCards%0D%0A%7D%0D%0A%0D%0Aexport%20interface%20Category%20%7B%0D%0A%20%20%20%20hideCategory%3A%20HideCategory%3B%0D%0A%7D%0D%0A%0D%0Afunction%20test()%20%7B%0D%0A%20%20%20%20var%20x%3A%20Category%20%3D%20%7B%20hideCategory%3A%20HideCategory.Never%20%7D%3B%0D%0A%0D%0A%20%20%20%20%2F*%20why%20doesn't%20this%20work*%2F%0D%0A%20%20%20%20if%20(x.hideCategory%20%26%26%20x.hideCategory%20!%3D%20HideCategory.Never)%0D%0A%20%20%20%20%7B%0D%0A%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20%2F*I%20have%20to%20put%20in%20a%20null%20check%20for%20it%20not%20to%20error*%2F%0D%0A%20%20%20%20if%20(x.hideCategory%20!%3D%20null%20%26%26%20x.hideCategory%20!%3D%20HideCategory.Never)%0D%0A%20%20%20%20%7B%0D%0A%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20%2F*%20and%20why%20does%20this%20work*%2F%0D%0A%20%20%20%20var%20boolCheck%3A%20boolean%20%3D%20x.hideCategory%20!%3D%20HideCategory.Never%3B%20%0D%0A%7D)

**Expected behavior:**

In the example above, on the line 

```ts
if (x.hideCategory && x.hideCategory != HideCategory.Never) { }
```
the x.hideCategory check should automatically assume the same 'truthy' check as it would in JavaSript

**Actual behavior:** 

TypeScript reports a TS2365 error 

Operator '!=' cannot be applied to types 'HideCategory.ForZeroTotal | HideCategory.ForNoLineItems | HideCategory.ForNoCards' and 'HideCategory.Never'.

**Comment by bthomsons** [comment]
**Update** If I change the declaration of the enum to the following (adding the declare keyword):

```ts
export declare const enum HideCategory {
    Never,
    ForZeroTotal,
    ForNoLineItems,
    ForNoCards
}
```
I don't receive the error.

**Comment by ahejlsberg** [comment]
This is working as intended. The `HideCategory.Never` member has the value zero, so when `x.hideCategory` is falsey you have already excluded `HideCategory.Never`. Thus it doesn't make sense to compare to `HideCategory.Never` and the compiler is pointing that out.

**Comment by ahejlsberg** [comment]
The reason the error disappears when you add a `declare` modifier is that we don't auto-number enum members in a `declare` context so we can't exclude anything following a check.

**Comment by bthomsons** [comment]
Hi @ahejlsberg thanks for your reply, that makes perfect sense. I'll close this issue.
