### ISSUE TITLE
Union type guards are not conferred via the ternary operator

### ISSUE THREAD

**Issue by wwoods** [Microsoft/TypeScript#11740]
**TypeScript Version:**  2.0.3

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
class A {
  constructor(public a:string) {
  }
}
class B {
  constructor(public b:string) {
  }
}
function test(p:A | B):string {
  return (p instanceof A) ? p.a) : p.b;
}

let q = new A('hello');
console.log(test(q));
```

**Expected behavior:**
The type inference conferred by the instanceof type guard should also work within the functions that use the same scope of the ternary operator.

**Actual behavior:** 
The type is not remembered any more, and p must be re-cast as A or B.

**Comment by jesseschalken** [comment]
The provided code compiles fine on 2.0.3, after fixing the typo in the ternary.

**Comment by wwoods** [comment]
Ah, I see, I had the code formatted differently:

```ts
class A...
class B...
function test(p:A | B):string {
  return
    (p instanceof A) ? p.a
    p.b
    ;
}
```

I didn't figure that the return being on a separate line made a difference, but I see now that the compiler interprets the return statement as a completed statement and then does something very weird with the ternary.  Fix (workaround?  I guess this is valid javascript) by putting a parenthesis on the same line as the return, and enclosing the ternary.
