### ISSUE TITLE
Derive shapes from other shapes generically

### ISSUE THREAD

**Issue by totallymike** [microsoft/TypeScript#11756]
# Preamble

I'm looking at [combineReducers](http://redux.js.org/docs/api/combineReducers.html) from Redux as a use-case example.

I'm looking for a way to define the key signature of an object such that one can compose the shapes of objects depending on the shapes of other objects.  Here's my use-case example:

Imagine you have a Redux State object that looks like this:

``` ts
type Person = {
  name: string,
  age: number
}

type State = {
  people: Array<Person>,
  loggedIn: boolean
}
```

In redux, you update your state by passing the original state, as well as an action to which the software will respond, to a `reducer` as such:

``` ts
interface Action {
  type: string;
  payload?: any;
}
const logInAction = { type: "LOG_IN" }

function addPersonActionCreator(person: Person): Action {
  return {
    type: "ADD_PERSON",
    payload: { person }
  }
}

function reducer(state: State, action: Action): State {
  switch (action.type) {
  case "LOG_IN":
    return { ...state, loggedIn: true } // Pretend this works for now.
  case "ADD_PERSON":
    let { people } = state
    people = [...people, action.payload.person]
    return { ...state, people } /// Again, pretend this destructuring nonsense works
  default:
    return state
  }
}
```

Furthermore, Redux gives you a function called `combineReducers` that will allow you to decompose your state object into smaller functions, like so:

``` ts
function loggedInReducer(loggedInState: boolean, action: Action): boolean {
  switch(action.type) {
  case "LOG_IN":
    return true
  default:
    return loggedInState
  }
}

function peopleReducer(peopleState: Array<Person>, action: Action): Array<Person> {
  switch(action.type) {
  case "ADD_PERSON":
    return [...peopleState, action.payload.person]
  default:
    return peopleState
  }
}

const reducer = combineReducers({
  loggedIn: loggedInReducer,
  people: peopleReducer
})
```

Now `reducer` has a type of `(state: State, action: Action) => State`, and this specific use of `combineReducers` can be covered with a declaration like so:

``` ts
// Note that State and Action are *not* generic, and can be read as using the type definitions
// above.
function combineReducers(reducers: ReducerObject): (state: State, action: Action) => State

interface ReducerObject {
  loggedIn: LoggedInReducer;
  people: AddPersonReducer;
}

interface LoggedInReducer {
  (loggedInState: boolean, action: Action) => boolean
}

interface AddPersonReducer {
  (peopleState: Array<People>, action: Action) => Array<People>
}

```
# The actual suggestion/question

I'd like to see a way to define `combineReducers` in a generic, typesafe way that can look deeply at what's passed to it.

This can be a bag of worms, because we can't know much ahead of time about State, but we can at least assume in this use-case that it's an object with enumerable keys. I believe that's a implementation requirement of `combineReducers` as well.

Naively implemented, it may look something like this:

``` ts
// For reference
type State = {
  people: Array<Person>,
  loggedIn: boolean
}

interface ReducerObject<S> {
  each <T>[index in S]: (state: T, action: Action) => T
}

// Which could be expanded, for ReducerObject<State>, into
type StateReducerObject = {
  people: (state: Array<Person>, action: Action) => Array<Person>,
  loggedIn: (state: boolean, action: Action) => boolean,
}
```

There already are indexable interfaces, of course, but the difference I'm proposing is that `T` in this interface is not the same for each property.

Granted, that's a loose syntax. I have no idea how one could accurately and effectively describe this intent given the workings of TypeScript's parser, so accept this as a stand-in while a better syntax is considered that would actually fit in TS.
# Open Questions, Problems

My first open question is the syntax. I don't much think that what I've got will do the trick, though I'd be delighted to find out otherwise!

Second, how could we implement this? It gets hairy quickly. It's pretty easy to typecheck `ReducerObject<S>` where `S` is a static type alias, but what if it's something more complicated, like a class? That's probably not too bad, so long as it's clear that the interface only works for the enumerable properties of instances. I'm sure there are hairier examples.

Probably many more questions, too.

**Comment by RyanCavanaugh** [comment]
This is pretty long and hairy and I think some combination of mapped types or conditional types do what you want. Seems like more of a question.
