### ISSUE TITLE
Incorrect behavior of function (var: CustomType): Promise<CustomType[]>  

### ISSUE THREAD

**Issue by shmuga** [Microsoft/TypeScript#11759]
**TypeScript Version:**  2.0.3 

**Code**

``` ts
type awesomeType = {
    a: string,
    b: number,
};

var k: awesomeType =  {
    a: '1',
    b: 2
};

function work(temp: awesomeType): Promise<awesomeType[]> {
    return new Promise((res,rej) => {
        res(temp);
    });
}

work(k).then((arr)=>{
    arr.map((x)=>{
        x.a;
    })
});

```

**Expected behavior:**
I hope this code should give cause I'm returning an Object but not Array of objects.
I'm not sure if there is such bug in repo so sorry if it's duplicated.

**Actual behavior:** 
No error thrown.

**Comment by aluanhaddad** [comment]
This is actually a treacherous case of generic bi-variance. Your work function is declared as having type
```ts
work: (temp: awesomeType) => Promise<awesomeType[]>
```
but its _true_ type is
```ts
work: (temp: awesomeType) => Promise<void>
```
The coding error is
```ts
res(temp);
```
which I believe you mean to be
```ts
return res(temp);
```

**Comment by RyanCavanaugh** [comment]
The problem here is that the `Promise` constructor defaults to `Promise<{}>` when there aren't any other annotations present, which does end up being assignable to other `Promise` types. What you usually want to write here is
```ts
function work(temp: awesomeType): Promise<awesomeType[]> {
    return new Promise<awesomeType[]>((res,rej) => {
        res(temp); // Error flagged here
    });
}
```
