### ISSUE TITLE
lib.es6.d.ts declares console.debug() 

### ISSUE THREAD

**Issue by BurtHarris** [microsoft/TypeScript#11751]
I'm not sure why **lib.es6.d.ts** defines method `debug` on `interface Console`.    I don't find evidence that it's specified by the ECMA standard, or commonly implemented.   It looks like `console.debug` may be a Microsoft (and Chrome)-specific extension, that functions the same as `console.log` per both [MSDN](https://msdn.microsoft.com/en-us/library/hh696634.aspx) and [Chrome](https://developers.google.com/web/tools/chrome-devtools/console/console-reference#debug) docs..  Compare this with [Node console](https://nodejs.org/dist/latest-v6.x/docs/api/console.html) documentation.

**TypeScript Version:**  2.0.3 

**Code**

``` ts
console.debug("asdf");
```

**Expected behavior:**
Shouldn't this generate a TypeScript compiler error?

**Actual behavior:** 
When building for ES6 target, seems to be accepted, but will generate a runtime error on Node.js.

**Note**
`console.debug()` is defined in the current [WHATWG console document](https://console.spec.whatwg.org/#debug), but the definition there clearly indicates it is duplicative of `console.log()`,

**Comment by domenic** [comment]
`console.log` is part of the standard; it's not a browser-specific extension.

**Comment by BurtHarris** [comment]
Its not part of the ECMA standard, as would be implied by its inclusion in this particular definition file, it is just par of the "living" whatwg document.

**Comment by domenic** [comment]
Sure, maybe it should be in a different file, but it's part of the Console Standard, which is the only normative reference of it. So this isn't a concern specific to debug, I guess; maybe you should retitle your bug to reflect wanting to create a separate definition file for the Console Standard.

**Comment by mhegazy** [comment]
The `console` definition is included with the `DOM` definition. since you are using node, you do not need either. so for node specify `--lib es6` (as opposed tot he default `--lib es6,dom`) and that should avoid adding the `console` in your global scope.

**Comment by BurtHarris** [comment]
Thanks @mhegazy.   Adding `"lib": ["es6"],` to my `tsconfig.json` flags it (and caught a few other interesting potential defects.)   

I would have thought that specifying `"target": "es2015"` and `"types": [ "node" ],` would have been enough to let TypeScript know the environment, but I'm fine with this as a workaround.

**Comment by mhegazy** [comment]
We have an issue to support `--lib node`, which basically takes care of this issue as well as needing to specify `"types": [ "node" ]` and installing `@types\node` in the first place. See https://github.com/Microsoft/TypeScript/issues/9466. The main issue is versions, and introducing yet another way to get to node definitions.

**Comment by falsandtru** [comment]
I want to use console function definitions with `lib.console.d.ts` and `--lib console` option.

**Comment by RyanCavanaugh** [comment]
node supports console.debug now
