### ISSUE TITLE
Highlighting Issue with Type Assertion and comparsion Operator

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/TypeScript#11767]
**TypeScript Version:**  commit 46f7a0f4a4eea3bf1e3be1b3491c45a89ae2776a
Tested with VSCode version 1.6.1
Tested on both Win10 and Ubuntu 16.04

Colorization of a type alias in a type assertion operator is sometimes inconsistent.

**Code**

``` ts
type MyNum = number;
var x: MyNum;

x < <MyNum>0;

x > <MyNum>0;

<MyNum>0 > x;

<MyNum>0 < x;

```

**Expected behavior:**

`MyNum` is teal in all cases.

**Actual behavior:** 

`MyNum` is white in the 1st, 3rd, and 4th comparisons, and teal in the 2nd comparison.

**Comment by mhegazy** [comment]
Highlighting is done by TM language in https://github.com/Microsoft/TypeScript-tmlanguage. please file it there. also there is a limit to what TM can do, given that it is just a regexp and this is requires a CFG-parser.
