### ISSUE TITLE
Highlighting Error with 'as' operator

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/TypeScript#11766]
**TypeScript Version:**  commit 46f7a0f4a4eea3bf1e3be1b3491c45a89ae2776a
Tested with VSCode version 1.6.1
Tested on both Win10 and Ubuntu 16.04

The issue is that the color of `MyNum` isn't consistent with other casts of using `as`.

**Code** 

``` ts
type MyNum = number;

x > 0 as number;
x > 0 as MyNum;
```

**Expected behavior:**

`MyNum` is highlighted the same color as the type alias and `number` (teal)

**Actual behavior:** 

`MyNum` is white.

**Comment by mhegazy** [comment]
looks working to me in latest.

![image](https://cloud.githubusercontent.com/assets/8000722/21165336/95cd199a-c153-11e6-84a6-184acea643c4.png)

**Comment by mhegazy** [comment]
Also please file colorization issues under https://github.com/Microsoft/TypeScript-tmlanguage
