### ISSUE TITLE
Distinguish declaration file and js file when the option “Keep comments in TypeScript compiler output" is turned on

### ISSUE THREAD

**Issue by dczuo** [Microsoft/TypeScript#11774]
Preserve comments in the declaration file have been able to provide prompt information in VS. Production environment using the uncompressed JS file helps locate exception, and retained in the .js file comments are unnecessary.
Proposals to add the options control only keep comments in declaration files.

**Comment by mhegazy** [comment]
I wounder if we should just keep comments in .d.ts files all the time, and possibly add `--removeDeclarationComments`

**Comment by mhegazy** [comment]
if you do not mind, we would like to keep this open until the issue is addressed.

**Comment by RyanCavanaugh** [comment]
Declined for the sake of flag complexity. Running a proper minifier over the output JS is part of any build which cares about output size.
