### ISSUE TITLE
Can't detect the length property of a string type

### ISSUE THREAD

**Issue by arnabdas** [Microsoft/TypeScript#11777]
``` bash
$ tsc --version
Version 2.0.3
```

**Code**

```ts
public static tryParseNumber(str: string = '', radix: number = 10, defaultValue: number = 0): number {
    var retValue = defaultValue;
    if (str !== null) {
      if (typeof str === 'String' && str.length > 0) {
        retValue = parseInt(str, radix);
        if (isNaN(retValue)) {
          retValue = defaultValue;
        }
      }
    }
    return retValue;
  }

```

**Expected behavior:**

This function should compile correctly

**Actual behavior:** 

Gives error as follows:

``` bash
(100,42): error TS2339: Property 'length' does not exist on type 'never'.
```

100th line is `if (typeof str === 'String' && str.length > 0) {`. When I remove the second comparison, with length, it works as expected.

Live example in TypeScript [play](http://www.typescriptlang.org/play/#src=class%20Greeter%20%7B%0D%0A%20%20%20%20public%20static%20tryParseNumber(str%3A%20string%20%3D%20''%2C%20radix%3A%20number%20%3D%2010%2C%20defaultValue%3A%20number%20%3D%200)%3A%20number%20%7B%0D%0A%20%20%20%20var%20retValue%20%3D%20defaultValue%3B%0D%0A%20%20%20%20if%20(str%20!%3D%3D%20null)%20%7B%0D%0A%20%20%20%20%20%20if%20(typeof%20str%20%3D%3D%3D%20'String'%20%26%26%20str.length%20%3E%200)%20%7B%0D%0A%20%20%20%20%20%20%20%20retValue%20%3D%20parseInt(str%2C%20radix)%3B%0D%0A%20%20%20%20%20%20%20%20if%20(isNaN(retValue))%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20retValue%20%3D%20defaultValue%3B%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20return%20retValue%3B%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Alet%20num%20%3D%20Greeter.tryParseNumber('12')%3B%0D%0A%0D%0Alet%20button%20%3D%20document.createElement('button')%3B%0D%0Abutton.textContent%20%3D%20%22Say%20Hello%22%3B%0D%0Abutton.onclick%20%3D%20function()%20%7B%0D%0A%20%20%20%20alert(num)%3B%0D%0A%7D%0D%0A%0D%0Adocument.body.appendChild(button)%3B). See the red squiggly beneath length.

**Comment by gcnew** [comment]
```ts
if (typeof str === 'String' && str.length > 0)
```

is never `true` because `typeof` doesn't return `String`, it's `string`.

**Comment by RyanCavanaugh** [comment]
Please test that your code actually would work before filing a compiler bug?
