### ISSUE TITLE
Narrowing discriminated unions with user-defined type guards

### ISSUE THREAD

**Issue by timruffles** [microsoft/TypeScript#11787]
**TypeScript Version:**  2.0.3

**Code**

``` typescript
type Cheese = {
  type: 'brie';
  brieOnly: true,
} | {
   type: 'cheddar';
  cheddarOnly: true,
}


function narrows<Wide extends string, Narrow extends Wide>(w: Wide, n: Narrow): w is Narrow {
    return w === n;
}


function doSomethingWithCheese(cheeseSample: Cheese) {
    if (cheeseSample.type === 'cheddar') {
        cheeseSample.cheddarOnly // ok
    }

    if (narrows(cheeseSample.type, 'cheddar')) {
        const t: 'cheddar' = cheeseSample.type; // has narrowed 
        cheeseSample.cheddarOnly // not ok, didn't narrow discriminated union
    }
}
```

**Expected behavior:**

Discriminated unions would work with type-guards in this way.

**Actual behavior:** 

It doesn't, and I have to write a load of stuff like this in unit-tests:

``` typescript
    if (cheese.type === 'cheddar') {
          assert(/* some assertions using cheddar specific properties */);
    } else {
           throw Error("wrong type of cheese");
        }
```

rather than doing it in one step with an assertion throwing version of `narrows`:

``` typescript
    if (assert.narrows(cheese.type, 'cheddar')) {
          assert(/* some assertions using cheddar specific properties */);
    }
```

**Comment by aluanhaddad** [comment]
What is `narrowsInUnion` in your example? I cannot find it.

**Comment by masaeedu** [comment]
@aluanhaddad I think that's just a typo for `narrows`.

**Comment by masaeedu** [comment]
@timruffles It doesn't seem like what you're proposing generalizes well. Your `narrows` invocation is oblivious to the type of `cheeseSample`, you're just passing in an arbitrary expression of type string that you establish for the remainder of the function to be a particular string literal.

What you want to do can be accomplished, there just needs to be a way to do it less awkwardly:

```typescript
type Cheese = {
    type: 'brie';
    brieOnly: true,
} |
{
    type: 'cheddar';
    cheddarOnly: true,
};

function narrows<Wide, Narrow extends Wide>(w: Wide, f: (w: Wide) => Narrow): w is Narrow {
    return f(w) !== undefined;
}

function doSomethingWithCheese(cheeseSample: Cheese) {
    if (cheeseSample.type === 'cheddar') {
        cheeseSample.cheddarOnly // ok
    }

    if (narrows(cheeseSample, c => c.type === 'cheddar' ? c : undefined)) {
        const t: 'cheddar' = cheeseSample.type;
        cheeseSample.cheddarOnly;
    }
}
```

Right now I'm relying on type inference to make this work, but the fact that you have to use `undefined` and return the actual type is a bit awkward.

**Comment by seansfkelley** [comment]
This is still an issue in 3.x. I had a slightly simpler variant that didn't have a type-parameterized type guard, but I think it's the same basic issue:

```ts
interface Foo {
    type: "foo";
    foo: string;
} 

interface Bar {
    type: "bar";
    bar: string;
}

type FooBar = Foo | Bar;

function isFooType(t: "foo" | "bar"): t is "foo" {
    return true;
}

const f: FooBar = null as any;

if (f.type === "foo") {
    f.foo; // works
}

if (isFooType(f.type)) {
    f.foo; // breaks
}
```

[playground link](https://www.typescriptlang.org/play/index.html#src=interface%20Foo%20%7B%0D%0A%20%20%20%20type%3A%20%22foo%22%3B%0D%0A%20%20%20%20foo%3A%20string%3B%0D%0A%7D%20%0D%0A%0D%0Ainterface%20Bar%20%7B%0D%0A%20%20%20%20type%3A%20%22bar%22%3B%0D%0A%20%20%20%20bar%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Atype%20FooBar%20%3D%20Foo%20%7C%20Bar%3B%0D%0A%0D%0Afunction%20isFooType(t%3A%20%22foo%22%20%7C%20%22bar%22)%3A%20t%20is%20%22foo%22%20%7B%0D%0A%20%20%20%20return%20true%3B%0D%0A%7D%0D%0A%0D%0A%0D%0Aconst%20f%3A%20FooBar%20%3D%20null%20as%20any%3B%0D%0A%0D%0Aif%20(f.type%20%3D%3D%3D%20%22foo%22)%20%7B%0D%0A%20%20%20%20f.foo%3B%20%2F%2F%20works%0D%0A%7D%0D%0A%0D%0Aif%20(isFooType(f.type))%20%7B%0D%0A%20%20%20%20f.foo%3B%20%2F%2F%20breaks%0D%0A%7D)

This is a bummer, cause it means that a user-defined type guard deep in the type hierarchy may get bubbled up with "wrapper" type guards for containing types in order to discriminate them:

```ts
function isFoo(foobar: Foo | Bar): foobar is Foo {
    return isFooType(foobar.type);
}
```

**Comment by timruffles** [comment]
@masaeedu the `narrows` call is not attempting to narrow `cheeseSample`, it's narrowing its type field. I'm suggesting that the information we gain from that narrowing is used to *infer* the type of `cheeseSample`. 

If you re-read my example you'll see it's the same narrowing & inference logic as is used in the primitive example `.type === 'cheese` I gave above it, just with user-defined type guards rather than `===`.

**Comment by radichc** [comment]
Also running into this issue. Another simple example:
```typescript
interface Square {
    kind: "square";
    size: number;
}

interface Rectangle {
    kind: "rectangle";
    width: number;
    height: number;
}

type Shape = Square | Rectangle;
```
Using a basic `Shape` discriminated union example.

Demonstrates expected discriminated union type inference:
```typescript
const shape1: Shape = JSON.parse('{ "kind": "square", "size" : 10 }');

console.log(shape1.kind); // compiles, as expected
console.log(shape1.size); // compiler error, as expected
if (shape1.kind === "square") {
    console.log(shape1.size); // compiles, as expected
}
```

Demonstrates incorrect discriminated union type inference using type guard:
```typescript
const isShape = (value: any): value is Shape => typeof value === 'object' && value !== null && typeof value.kind === 'string' /* && etc... */;

const shape2: unknown = JSON.parse('{ "kind": "square", "size" : 10 }');

if (isShape(shape2)) {
    console.log(shape2.kind); // compiles, as expected
    console.log(shape2.size); // compiler error, as expected
    if (shape2.kind === "square") {
        console.log(shape2.size); // compiler error, NOT expected
    }
}
```

[playground](https://www.typescriptlang.org/play/index.html#src=interface%20Square%20%7B%0A%20%20%20%20kind%3A%20%22square%22%3B%0A%20%20%20%20size%3A%20number%3B%0A%7D%0A%0Ainterface%20Rectangle%20%7B%0A%20%20%20%20kind%3A%20%22rectangle%22%3B%0A%20%20%20%20width%3A%20number%3B%0A%20%20%20%20height%3A%20number%3B%0A%7D%0Atype%20Shape%20%3D%20Square%20%7C%20Rectangle%3B%0A%0A%0A%0A%2F%2F%20Demonstrates%20expected%20discriminated%20union%20type%20inference%0A%0Aconst%20shape1%3A%20Shape%20%3D%20JSON.parse('%7B%20%22kind%22%3A%20%22square%22%2C%20%22size%22%20%3A%2010%20%7D')%3B%0A%0Aconsole.log(shape1.kind)%3B%20%2F%2F%20compiles%2C%20as%20expected%0Aconsole.log(shape1.size)%3B%20%2F%2F%20compiler%20error%2C%20as%20expected%0Aif%20(shape1.kind%20%3D%3D%3D%20%22square%22)%20%7B%0A%20%20%20%20console.log(shape1.size)%3B%20%2F%2F%20compiles%2C%20as%20expected%0A%7D%0A%0A%0A%0A%2F%2F%20Demonstrates%20incorrect%20discriminated%20union%20type%20inference%20using%20type%20guard%0A%0Aconst%20isShape%20%3D%20(value%3A%20any)%3A%20value%20is%20Shape%20%3D%3E%20typeof%20value%20%3D%3D%3D%20'object'%20%26%26%20value%20!%3D%3D%20null%20%26%26%20typeof%20value.kind%20%3D%3D%3D%20'string'%20%2F*%20%26%26%20etc...%20*%2F%3B%0A%0Aconst%20shape2%3A%20unknown%20%3D%20JSON.parse('%7B%20%22kind%22%3A%20%22square%22%2C%20%22size%22%20%3A%2010%20%7D')%3B%0A%0Aif%20(isShape(shape2))%20%7B%0A%20%20%20%20console.log(shape2.kind)%3B%20%2F%2F%20compiles%2C%20as%20expected%0A%20%20%20%20console.log(shape2.size)%3B%20%2F%2F%20compiler%20error%2C%20as%20expected%0A%20%20%20%20if%20(shape2.kind%20%3D%3D%3D%20%22square%22)%20%7B%0A%20%20%20%20%20%20%20%20console.log(shape2.size)%3B%20%2F%2F%20compiler%20error%2C%20NOT%20expected%0A%20%20%20%20%7D%0A%7D)

**Comment by RyanCavanaugh** [comment]
The `narrows` definition is not something that can narrow the outer type, as discussed above

Alternately, duplicate #30557
