### ISSUE TITLE
Suggestion: Provide tagged union discriminator as compile-time constant

### ISSUE THREAD

**Issue by JesperTreetop** [Microsoft/TypeScript#11784]
Currently, when using tagged unions, describing the discriminator member has to be done with a string/number/boolean constant type and can't be done by a constant. This means that the value has to be manually duplicated when a check is made, and the two has to be kept in sync.

My suggestion is to make the discriminator syntactically available as a static property on the type. For example:

``` ts
type Fruit = IApple | IBanana;

const appleType = "apple";

interface IApple {
    type: "apple"; // this can't be `appleType`, it has to be a literal
    numberOfSeeds: number;
}

interface IBanana {
    type: "banana";
    ripeness: number;
    bendInRadians: number;
}

const fruit: Fruit;

switch (fruit.type) {
    // only possible current option
    case "apple":
        // fruit is implicitly IApple here
        break;

    // proposed option, would be functionally identical
    case IApple.type:
        // fruit is implicitly IApple here too
        // because of type being equal to "apple"
        // just as before
        break;
}
```

The generated code would be the discriminator value as defined in the interface's property declaration (`"apple"` for `IApple` above). The declaration files would need no new information and this would work with existing declaration files..

Of course, no such shortcut can be used for anonymous interfaces in a tagged union, like:

``` ts
const oneOrTheOther: { type: "a"; x: number; } | IApple;
// can't say `[anything].type` to get "a"
```

I think that's fine. This is an extra feature for named types - if this is desired, just name the interface.

However, which code should be generated when the type declaration is missing is unclear to me. If TypeScript has no idea what `IApple.type` is, generating anything could result in JavaScript with garbage logic.

**Comment by ahejlsberg** [comment]
If the desired effect is to have a single declaration of each discriminant value you could write your code this way:

```ts
type Fruit = IApple | IBanana;

const APPLE = "apple";
const BANANA = "banana";

interface IApple {
    type: typeof APPLE;
    numberOfSeeds: number;
}

interface IBanana {
    type: typeof BANANA;
    ripeness: number;
    bendInRadians: number;
}

declare var fruit: Fruit;

switch (fruit.type) {
    case APPLE:
        // Handle apples
        break;
    case BANANA:
        // Handle bananas
        break;
}
```

The above works with the nightly build. With 2.0.x you'll need to declare the `const` constants with a type annotation:

```ts
const APPLE: "apple" = "apple";
const BANANA: "banana" = "banana";
```

**Comment by JesperTreetop** [comment]
@ahejlsberg That's great! Before I posted this, I tried simply:

```ts
const APPLE = "apple";

interface IApple {
    type: APPLE;
}
```

- it didn't occur to me that `typeof APPLE` would be a compile-time constant in a way that getting the value of it isn't. I think that's a good enough replacement for the same idea, even though it's a bit counterintuitive - then again, so's my suggested method.
