### ISSUE TITLE
Typeguards and ternary operator not correctly deducing type

### ISSUE THREAD

**Issue by wwoods** [Microsoft/TypeScript#11785]
**TypeScript Version:**  2.0.3

**Code**

```ts
let p:null|boolean|RegExp|{():void} = null;
let v:{(): boolean} = (
    p == null || p === true ? () => true
    : p === false ? () => false
    : (p instanceof RegExp) ? () => p.test('hi')
    : () => { p(); return true; }
);
```

**Expected behavior:**
This should compile and should find both `p.test` and `p()`, as the types are sufficiently narrowed at those points.

**Actual behavior:** 
Even though everything is properly guarded (all null and boolean options eliminated), the RegExp line fails because `p.test` cannot be resolved on the union type, and the invocation of `p()` fails because the type hasn't been narrowed.  Replacing the above code with this fixes it:

```ts
let p:null|boolean|RegExp|{():void} = null;
let v:{(): boolean} = (
    p == null || p === true ? () => true
    : p === false ? () => false
    : (p instanceof RegExp) ? () => (p as RegExp).test('hi')
    : () => { (p as {():void})(); return true; }
);
```

In this version, both lines are typecast, and the compiled javascript looks correct.  So it seems to be a typeguard issue.

**Comment by ahejlsberg** [comment]
This is working as intended. When you declare a variable with `let` or `var` the compiler can't know for certain that the variable hasn't changed before the arrow function is invoked. However, if you declare your variable as `const`, type guards remain in effect in nested function expressions and arrow functions. For example, this works:

```ts
const p:null|boolean|RegExp|{():void} = null;  // Using const here
let v:{(): boolean} = (
    p == null || p === true ? () => true
    : p === false ? () => false
    : (p instanceof RegExp) ? () => p.test('hi')
    : () => { p(); return true; }
);
```

**Comment by wwoods** [comment]
Ok, makes sense, thank you for the explanation.
