### ISSUE TITLE
Typeguards with strictNullCheck not properly ruling out undefined

### ISSUE THREAD

**Issue by wwoods** [Microsoft/TypeScript#11786]
**TypeScript Version:**  2.0.3

**Code**

```ts
let load:undefined | {(): boolean} = () => true;
if (load !== undefined) {
  load(); //ok
  let f = () => {
    return load(); //not ok
  };
}
```

**Expected behavior:**
Compiling the above `test.ts` with `tsc --strictNullChecks --lib es6,dom test.ts` should work, as `undefined` is ruled out by the if statement.

**Actual behavior:** 
The compiler throws `test.ts(5,12): error TS2532: Object is possibly 'undefined'.` in reference to the function.  This only happens in `strictNullChecks` mode.

Possibly related to the assignment of a variable issue, #11782 .  However, since this only happens with `strictNullChecks`, I'm not sure.

**Comment by ahejlsberg** [comment]
See #11785.
