### ISSUE TITLE
Add support for @template JSDoc

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/TypeScript#1178]
Hi, it will be useful to be able to document generic parameters:

```TypeScript
/** The foo class.
  * @template TFirst ...
  * @template TSecond ... */
class Foo<TFirst, TSecond> {

}

var foo = new Foo< // Info
```

**Comment by kitsonk** [comment]
Carried over from #5854, it was pointed out that [Closure Compiler](https://developers.google.com/closure/compiler/docs/js-for-compiler?hl=en) documents this feature.

**Comment by Liero** [comment]
I'm not sure what is the final syntax for documenting generic arguments. Can you point to documentation or briefly describe, please?

**Comment by billti** [comment]
@liero see the examples at https://github.com/Microsoft/TypeScript/wiki/JsDoc-support-in-JavaScript

**Comment by unional** [comment]
@RyanCavanaugh is it in nightly? I check and `2.1.0-dev.20160712` does not work:
![image](https://cloud.githubusercontent.com/assets/3254987/16830764/b348e1be-4955-11e6-9256-251ee1cf33b7.png)
![image](https://cloud.githubusercontent.com/assets/3254987/16830776/ceee42ce-4955-11e6-99de-9a70a9c85792.png)

**Comment by mhegazy** [comment]
@unional can you log a new issue with more details

**Comment by unional** [comment]
Done. 🌷

**Comment by aleksey-bykov** [comment]
please update https://github.com/Microsoft/TypeScript/wiki/JSDoc-support-in-JavaScript

**Comment by artin-phares** [comment]
so narrowing generic type `@template T` is supported?  
the case was mentioned in #5854, but I cannot find any example.

same question: https://stackoverflow.com/questions/44080759/is-it-possible-to-constrain-a-generic-type-defined-in-a-jsdoc-template-declarat

**Comment by villelahdenvuo** [comment]
I just came to ask the same question, but it seems like the answer is no.

**Comment by mhegazy** [comment]
Looking at the closure documentation for `@template` (https://github.com/google/closure-compiler/wiki/Generic-Types), does not seem that the standard has any support for this. One option is to make a new syntax, `@template T {Object}` to define a constraint. I would file a new suggestion for that.
