### ISSUE TITLE
async/await not working on IE6-IE8 in @next

### ISSUE THREAD

**Issue by andot** [microsoft/TypeScript#11799]
**TypeScript Version:**  2.1.0-dev.20161023

**Code**

``` ts
async function test() {
    return await Promise.resolve(123)
}

test().then(res => console.log(res))
```

**Expected behavior:**
Async functions should work on IE6-IE8 (IE11 in IE5-8 mode)

**Actual behavior:** 
Async functions not working on IE6-IE8 (IE11 in IE5-8 mode). Code inside async function just doesn't execute.

It is cause by:

``` js
function test() {
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            switch (_a.label) {
                case 0: return [4 /*yield*/, Promise.resolve(123)];
                case 1: return [2 /*return*/, _a.sent()];
            }
        });
    });
}
test().then(function (res) { return console.log(res); });
```

``` js
generator.apply(thisArg, _arguments)
```

Because the `_arguments` is `undefined`, it can't work in IE6-IE8. 

If the generated code is like this:

``` js
function test() {
    return __awaiter(this, [], void 0, function () {
        return __generator(this, function (_a) {
            switch (_a.label) {
                case 0: return [4 /*yield*/, Promise.resolve(123)];
                case 1: return [2 /*return*/, _a.sent()];
            }
        });
    });
}
test().then(function (res) { return console.log(res); });
```

It can work.

**Comment by mhegazy** [comment]
What Promise shim are you using?

**Comment by andot** [comment]
es6-promise

**Comment by mhegazy** [comment]
@rbuckton any thoughts?

**Comment by rbuckton** [comment]
We can easily fix the `__awaiter` helper to pass `_arguments || []` in the call to apply. However, its more difficult to handle the `alert` or `console.log` issue as its generally unsafe to just assume the value for an identifier is unchanged between when you suspend execution and when you resume execution. Consider the following:

```ts
const obj { 
  log: s => console.log("A: " + s)
};
setTimeout(() => obj.log = s => console.log("B: ", + s), 0);
async function f(x) {
  obj.log(await x); // will this log "A: ..." or "B: ..."?
}
```

The JavaScript runtime semantics for generators and async functions would always print "A: ..." above, as the `obj` and `obj.log` are evaluated before `await x`.

The `apply` issue is also problematic for spread as we *must* use apply, even if a host object may not understand it. For these engines, you would be better off being more explicit in the source:

```ts
async function f(x) {
  let x1 = await x;
  alert(x1); // no need to cache `alert` as `await` is evaluated first
  console.log(x1); // no need to cache `console` or `console.log` as `await` is evaluated first
}
```

**Comment by andot** [comment]
Do you mean that 

```typescript
obj.log(await x);
```

has a different semantics with

```typescript
let temp = await x;
obj.log(temp);
```

? But I think no user can distinguish them in detail, so I think `await` can be evaluated always first.
