### ISSUE TITLE
noUnusedParameters doesn't apply to binding elements

### ISSUE THREAD

**Issue by r0flbear** [Microsoft/TypeScript#11795]
**TypeScript Version:**  2.0.3

**Code**

noUnusedParameters flag is set

```ts
const f = ([a]) => {};
f([1]);
```

**Expected behavior:**
should give an "'a' is declared but never used" error

**Actual behavior:**
nothing

**Comment by DanielRosenwasser** [comment]
I believe that this could trigger a property access, but that seems very non-idiomatic.
