### ISSUE TITLE
Question: Why are some of the CompilerOptions Internal?

### ISSUE THREAD

**Issue by ToddThomson** [Microsoft/TypeScript#11792]
I am upgrading my bundling Typescript compiler to use Typescript 2.x and noticed that a number of CompilerOptions ares now internal ( Diagnostics, ListFiles, Watch, etc ). Is there a reason for this?

**Comment by mhegazy** [comment]
These are options that are used only by commandline compiler driver (tsc.js), no other parts of the system use them, so specifying them would be not be useful. e.g. `help`. setting this on the API does not do any thing.

**Comment by ToddThomson** [comment]
I use them. For example when doing white space elimination I use the Diagnostics flag to output white space reduction statistics. I also need to know if the user has the Watch flag set as I have compile and bundling and minification functions that result when a source file changes.
I agree that these settings are most likely only used by those of us writing features on top of the transpiler, but the are needed.

**Comment by mhegazy** [comment]
Nothing stops you from defining a new property on the option bag. Your diagnostics flag means something to you, so that is fine, but it is not the same meaning the one in types has. So my recomedation is to add your declarations on top of the exisitng compileroptions as needed.

**Comment by ToddThomson** [comment]
Yes, I see your point, I am just piggybacking my use of a few of the "internal" compiler options.
In any event, as you say, it is simple enough to get those properties back for my use. Cheers, @mhegazy
