### ISSUE TITLE
`is` type guards for properties

### ISSUE THREAD

**Issue by thorn0** [microsoft/TypeScript#11796]
**TypeScript Version:**  2.0.3

**Code**

From [the typings](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/vinyl/vinyl.d.ts) for the `vinyl` module.

``` ts
declare class File {
    // ...
    /**
     * Type: Buffer|Stream|null (Default: null)
     */
    public contents: Buffer | NodeJS.ReadableStream;

    /**
     * Returns true if file.contents is a Buffer.
     */
    public isBuffer(): boolean;

    /**
     * Returns true if file.contents is a Stream.
     */
    public isStream(): boolean;

    /**
     * Returns true if file.contents is null.
     */
    public isNull(): boolean;

    // ...
}
```

**Expected behavior:**

Possibility to specify something like `this.contents is Buffer` instead of just `boolean` for the return type of the methods `isBuffer`, `isStream`, `isNull`.

**Actual behavior:** 

The language doesn't support this.

**Comment by aluanhaddad** [comment]
> The language doesn't support this.

This is simple and easy to do in TypeScript, no pun intended

```ts

declare class File {
  // ...
  /**
   * Type: Buffer|Stream|null (Default: null)
   */
  private contents: Buffer | NodeJS.ReadableStream;

  /**
   * Returns true if file.contents is a Buffer.
   */
  public isBuffer(): this is { contents: Buffer };

  /**
   * Returns true if file.contents is a Stream.
   */
  public isStream(): this is { contents: NodeJS.ReadableStream };
}

const f = new File();

if (f.isBuffer()) {
  console.log(f.contents.buffer);
} else if (f.isStream()) {
  console.log(f.contents.read(1024));
} 
```

**Comment by aluanhaddad** [comment]
Note, you can also write
```ts
isBuffer(): this is this & { contents: Buffer };
```
Which will propagate the instance type for further refinement while allowing you to access `contents` as `Buffer`.

**Comment by thorn0** [comment]
However, it doesn't work exactly like type guards usually work. Inside this `if`, I'd expect `f.contents` to be `never`, but it's `Buffer & NodeJS.ReadableStream`:
```
if (f.isBuffer() && f.isStream()) { ... }
```
Still great that it works.

**Comment by aluanhaddad** [comment]
@thorn0, in the future subset types might be able to help with this. For now, you can use this, which is actually shorter and arguably more readable

```ts
interface FileBuffer {
  kind: 'buffer';
  contents: Buffer;
}
interface FileStream {
  kind: 'stream';
  contents: NodeJS.ReadableStream;
}

type File = FileBuffer | FileStream;

declare const File: new () => File;

const f = new File();
if (f.kind === 'stream' && f.kind === 'buffer') // error
```

**Comment by aleksey-bykov** [comment]
`true` and `false` a type literals now, take advantage of it

```typescript
interface FileBuffer {
  isBuffer: true;
  contents: Buffer;
}
interface FileStream {
  isBuffer: false;
  contents: NodeJS.ReadableStream;
}

type File = FileBuffer | FileStream;
declare const File: new () => File;

const f = new File();
if (f.isBuffer) {
    f.contents; // Buffer
} else {
    f.contents; // NodeJS.ReadableStream
}
```

**Comment by thorn0** [comment]
I'm not the author of the library. I just wanted to improve its type definitions.

**Comment by aluanhaddad** [comment]
@aleksey-bykov Indeed, that is much more elegant.

@thorn0 I messed around a little bit and was able to get the mutually exclusive `&&` case working

```ts

interface FileBuffer {
    contents: Buffer;
    isBuffer(): true;
    isStream(): this is never;
}

interface FileStream {
    contents: NodeJS.ReadableStream;
    isStream(): true;
    isBuffer(): this is never;
}

interface File {
    contents: Buffer | NodeJS.ReadableStream;
    isBuffer(): this is FileBuffer;
    isStream(): this is FileStream;
}

declare const File: new () => File;


// ...


const f = new File();

if (f.isBuffer()) {
    console.log(f.contents.buffer);
}
if (f.isStream()) {
    console.log(f.contents.read(1024));
}

if (f.isBuffer() && f.isStream()) {
    f.contents; //'Property 'contents' does not exist on type 'never'.
}
```
Not exactly what you asked for in that `f` is never, rather than `f.contents`, but I think it matches the usecase. This definition should be compliant with the behavior of the library itself.

**Comment by thorn0** [comment]
@aluanhaddad It works. :) Ta-da: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/12368 :tada:

**Comment by RyanCavanaugh** [comment]
@thorn0 should I leave this issue open?

**Comment by thorn0** [comment]
I honestly don't know. The solution that @aluanhaddad looks hackish, but it allowed me to achieve what I wanted. So far it's the first and only time I needed a type guard like `this.prop is Type`. Probably the language doesn't really need such a feature. What do you think?

**Comment by RyanCavanaugh** [comment]
If it can be accomplished through reasonable means I'd prefer to not do extra work / add complexity unless it's really needed. I'll retag for now in case anyone else runs into something similar and can't use the same method.

**Comment by RyanCavanaugh** [comment]
Seems like this is good enough
