### ISSUE TITLE
Return type of an inherited static method returning "new this()" is incorrectly the base class, but it's the child class in runtime

### ISSUE THREAD

**Issue by TomMarius** [Microsoft/TypeScript#11793]
**TypeScript Version:**  2.0.3

**Code**

``` ts
class A
{
    static X()
    {
        return new this();
    }
}

class B extends A
{
}

const shouldBeB = B.X();
```

**Expected behavior:**
The compiler correctly infers the type of `shouldBeB` as B.

**Actual behavior:** 
The compiler infers the type of `shouldBeB` as A, but it's B in runtime.

**Comment by yortus** [comment]
Duplicate of #5863?

**Comment by TomMarius** [comment]
@yortus in my mind that is a feature suggestion, but I think it's a critical bug, so I made a separate issue.

**Comment by HerringtonDarkholme** [comment]
You can always use https://github.com/Microsoft/TypeScript/issues/5863#issuecomment-242782664 for the same behavior

**Comment by RyanCavanaugh** [comment]
Too architecturally difficult to solve given the apparent lack of need for it
