### ISSUE TITLE
[Errors] error recovery of object literals with missing :

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#118]
```TypeScript
var v = { areturn;
```

Expected: 

!!! ':' expected.

Actual: 

!!! ':' expected.!!! ':' expected.

 

Don't want to consume the 'return' as the next property name in the object literal 

 

See also:

tests/cases/conformance/parser/ecmascript5/ErrorRecovery/ObjectLiterals/parserErrorRecovery_ObjectLiteral3.ts

tests/cases/conformance/parser/ecmascript5/ErrorRecovery/ObjectLiterals/parserErrorRecovery_ObjectLiteral4.ts

**Comment by DanielRosenwasser** [comment]
Did you mean the following?

```TypeScript
var v = { a return;
```

Right now you get

```
TS1005: ':' expected.
TS1005: ':' expected.
TS1005: '}' expected.
```

**Comment by mhegazy** [comment]
Looking at this again, not sure i see much value here. closing.
