### ISSUE TITLE
ThisKeyword in isPartOfExpression

### ISSUE THREAD

**Issue by ivogabe** [microsoft/TypeScript#11801]
**TypeScript Version:**  master

I was looking at the [code](https://github.com/Microsoft/TypeScript/blob/cef9d8597914f633f51c15b5ae6f9691c4dcfbc5/src/compiler/utilities.ts#L1158) of `isPartOfExpression`, which contains a long switch statement. It appears that `ThisKeyword` occurs twice there. It is both listed in the list of syntax kinds that are always expressions, and also listed in the block of kinds that can be expressions, depending on their parents. So I guess that a `this` type node would now be treated as an expression too?

**Comment by jakebailey** [comment]
Just looking at old bugs; this function is now called `isInExpressionContext` and doesn't mention `ThisKeyword` twice anymore.
