### ISSUE TITLE
"typeof" in generic return type of function

### ISSUE THREAD

**Issue by GongT** [Microsoft/TypeScript#11811]
**TypeScript Version:**  2.0.3

**Code**

```ts
function testFunc1 <T> (CLS: typeof T): typeof T {
        return CLS;
}

function testFunc2 <T> (obj: T): T {
        return obj;
}

// this issue is not about decorators, but I found this when I'm using decorators
@testFunc1
export class Cls1 {};

@testFunc2
export class Cls2 {};
```

**Expected behavior:**
> 
xxx.ts(1,37): error TS2304: Cannot find name 'T'.
xxx.ts(1,48): error TS2304: Cannot find name 'T'.
xxx.ts(5,30): error TS2304: Cannot find name 'T'.
xxx.ts(5,34): error TS2304: Cannot find name 'T'.

**OR**

>
*Successful compiled without any error.*

**Actual behavior:** 
> 
xxx.ts(1,37): error TS2304: Cannot find name 'T'.
xxx.ts(1,48): error TS2304: Cannot find name 'T'.

**Comment by DanielRosenwasser** [comment]
`T` is a type (not a value), and `typeof` only accepts values, so what exactly are you expecting the type of `typeof T` to be?

**Comment by DanielRosenwasser** [comment]
Reading over this, I think what you want is

```ts
@testFunc1
export class Cls1 {};

interface ConstructorOf<T> {
    new (...args: any[]): T
}

function testFunc1<T>(CLS: ConstructorOf<T>): ConstructorOf<T> {
    return CLS;
}
```

**Comment by RyanCavanaugh** [comment]
https://github.com/Microsoft/TypeScript/wiki/FAQ#why-cant-i-write-typeof-t-new-t-or-instanceof-t-in-my-generic-function
