### ISSUE TITLE
Visual Studio: tsconfig.json file hidden from Solution Explorer is not considered by IntelliSense

### ISSUE THREAD

**Issue by trevorsg** [Microsoft/TypeScript#11815]
**TypeScript Version:**  2.0.3 

One can hide Items in Solution Explorer by using the &lt;Visible&gt;false&lt;/Visible&gt; or &lt;InProject&gt;false&lt;/InProject&gt; metadata on the Item. 

**Expected behavior:**
As long as the tsconfig file is in the project (hidden in VS or not), its settings should be applied for syntax highlighting, IntelliSense, etc.

**Actual behavior:** 
When &lt;Visible&gt; or &lt;InProject&gt; is applied to the tsconfig Item, its settings do not take effect.

**Scenario/Justification**
Our build requires some options that are only available in tsconfig.json (i.e. they don't have an MSBuild property counterpart). Therefore, we generate the tsconfig as part of the build and ensure it is part of the project. We want to hide it from Solution Explorer so engineers don't mistakenly edit it.

**Comment by mhegazy** [comment]
why not switch to use tsconfig.json all together if i may ask?

**Comment by trevorsg** [comment]
There are a couple of reasons here:

* Our product includes over 100 projects that contain TypeScript, and they all import a common props and targets file, which sets default settings for the compiler (among other things). As of now, there is no way to inherit from a base tsconfig file (although I do see that on the [roadmap](https://github.com/Microsoft/TypeScript/issues/9876) for 2.1 😄). 

* This is maybe not as good of a reason, but the rest of the product uses MSBuild, so why should TypeScript be any different? Developers understand that a &lt;TypeScriptCompile&gt; node in the proj file will get a TypeScript file compiled. If we were to switch to tsconfig.json exclusively, engineers would need to (unnecessarily, in my opinion) understand a new concept for their build configuration.

**Comment by mhegazy** [comment]
tsconfig.json is not anti-MSBuild. the build targets looks for them and builds them normally just like projects that do not have tsconfig.json.

so what properties specifically are you using the tsconfig.json for? typeRoots?

**Comment by trevorsg** [comment]
I'm not sure exactly which ones, but we're using "baseUrl", "rootDir", "paths", and "typeRoots".

**Comment by mhegazy** [comment]
I see. thanks. 

So given that TS 2.1 has support for configuration inheritance, is this still an issue?

**Comment by trevorsg** [comment]
I am pretty sure we will continue to generate a .tsconfig unless the MSBuild properties fully support everything .tsconfig supports. It would be nice to be able to hide that from the project in Solution Explorer.

**Comment by vladima** [comment]
@trevorsg Can you please tell are if this items is still actual for you? Current implementation uses  `DTE` interfaces to pull in list of compile items and unfortunately `DTE` does not report hidden items. Moving away from `DTE` is certainly an option however it is not an easy solution and might need some time to incorporate. Alternatively we can use some dedicated MSBuild item group to enumerate all configuration files in project. Downside of this approach is that it can only be added by hand editing the project file meaning that it may easily go out of sync with the actual list of files.

**Comment by trevorsg** [comment]
@vladima It's not a blocking issue or anything, just an inconvenience. If it's an expensive fix I wouldn't be offended by a "won't fix" :)

**Comment by vladima** [comment]
looks like costs of fixing it properly outweighs the benefits so closing it as "won't fix"
