### ISSUE TITLE
Visual Studio: IntelliSense does not work when typeRoots property in tsconfig references non-existent path

### ISSUE THREAD

**Issue by trevorsg** [Microsoft/TypeScript#11817]
**TypeScript Version:**  2.0.3
tsconfig.json: { "compilerOptions": { "typeRoots": ["non/existent/path"] } }

**Expected behavior:**
Nonexistent path entry is ignored, just like tsc would ignore it.

**Actual behavior:** 
IntelliSense for TypeScript files stops working completely, with no warnings/errors.

**Comment by mhegazy** [comment]
I can not reproduce this on a simple project locally. can you share more information?

**Comment by trevorsg** [comment]
Sure, I'll see if I can find a minimal repro.
