### ISSUE TITLE
Exclude option with *.g.ts is not respected in tsc

### ISSUE THREAD

**Issue by samirchakour** [Microsoft/TypeScript#11812]
**TypeScript Version:**  2.0.3
**TypeScript Version:**  1.8.7

**Code**
"exclude": [
    "node_modules",
    "temp",
    "out",
    "**/*.g.ts"
  ]

**Expected behavior:**
Shouldn't build any *.g.ts files in any subdirectory.

**Actual behavior:** 
Builds files with .g.ts extension with lots of SyntaxErrors in node.

**Comment by mhegazy** [comment]
use:

```json
"exclude": [
    "**/*.g.ts"
]
```

Please see http://www.typescriptlang.org/docs/handbook/tsconfig-json.html#details for details.

**Comment by samirchakour** [comment]
Yes this is what I am using "**/*.g.ts" but its not working (Its the comment editor is not displaying correctly the original text)!

**Comment by mhegazy** [comment]
notice the files picked up by the compiler in `tsc --listFiles`

```cmd

c:\test\11812>tree . /f
Folder PATH listing for volume OSDisk
Volume serial number is 9E6D-383F
C:\TEST\11812
│   a.g.ts
│   a.ts
│   tsconfig.json
│
└───nested
        b.g.ts
        b.ts


c:\test\11812>type tsconfig.json
{
        "exclude": [
                "**/*.g.ts"
        ]
}

c:\test\11812>tsc --v
Version 2.1.0-dev.20161023

c:\test\11812>tsc --listFiles
C:/Users/mhegazy/AppData/Roaming/npm/node_modules/typescript/lib/lib.d.ts
c:/test/11812/a.ts
c:/test/11812/nested/b.ts
```
