### ISSUE TITLE
Expose ability to add more files to program

### ISSUE THREAD

**Issue by alexsaveliev** [Microsoft/TypeScript#11810]
I'd like to propose exposing ability to add more files to `Program`, when object is already constructed.

When using TypeScript to fetch hovers and definitions (compatible with LSP protocol) it may be redundant to parse the whole workspace to get hover or definition from single file. For example microsoft/vscode contains about 16Mb in 2500 files. I think it may be enough to add explicitly one file (and implicitly references and imports) to obtain hover info, this way we may decrease latency while source code is being analyzed. Please note that this proposal, however, does not work with LSP `references` or `workspace symbols` requests where we need to operate with the whole workspace to retrieve proper data).

My suggestion is the following:

Expose new `Program::addFile(fileName: string): void` method that will call `processRootFile(fileName, /*isDefaultLib*/ false)`

Usage scenario may be the following:

- construct new `LanguageService` object using `LanguageServiceHost` that provides empty array for     `getScriptFileNames()`
- when hover or definition is requested, checking if `LanguageService::getProgram()` contains source file with the given name using `Program::getSourceFile` method and if not, calling new `Program::addFile` method.
- Then calling `LanguageService::getQuickInfoAtPosition` will synchronize program data and source code of newly added files will be fetched and parsed.

This proposal does not break existing functionality or introduce performance degradation.

I am ready to submit a PR if my suggestion will be accepted

**Comment by mhegazy** [comment]
This functionality is already supported through passing old program to `createProgram` function. 

The function will "reuse" as much is possible (almost all) of the old program as it is creating a new one.

**Comment by mhegazy** [comment]
see https://github.com/Microsoft/TypeScript/blob/4dc60282639aa22b87f6446b625fe360e525c3ed/src/services/services.ts#L1087 for how the language service does that.

**Comment by alexsaveliev** [comment]
@mhegazy, thank you very much for your feedback!

I might be wrong but it seems that passing argument to `createProgram` is not enough, because new object made does not affect `program` object (https://github.com/Microsoft/TypeScript/blob/4dc60282639aa22b87f6446b625fe360e525c3ed/src/services/services.ts#L959) used by `synchronizeHostData`, `getValidSourceFile` and other functions, so we'll face situation when updated program object will be inconsistent with the LanguageService's one. Calling, for example, `ts.getQuickInfoAtPosition` will ask closure object to provide `getValidSourceFile`, ignoring updated program's data. Also, I think that updating root names array in `LanguageServiceHost` and calling `LanguageService::getProgram()` to synchronize the data won't work as well, because `if (!arrayIsEqualTo(oldRootNames, rootNames)) ` will not allow reusing old program's source files.

**Comment by mhegazy** [comment]
> will not allow reusing old program's source files.

that is correct. but the program can not be reused all the time. there are cases where you need to build a new one. 

The issue here is not that programs are immutable. the real issue is that the shape of a program is dependent on the contents of all its files. e.g. an import or triple slash reference can change the shape of the program.

Building a program reusing pieces from the old one is the same amount of work needed to just "add" a file. The fact that Program, SourceFile, Node, Symbol and Type are immutable data structures is an implementation detail and does not change the work needed to be done.

I might be able to help you more if you explain to me what you are trying to do.

**Comment by alexsaveliev** [comment]
@mhegazy, 

I finally understood how to start with zero files and add more files when needed. My recipe is: push more file names to the array returned by `LanguageServiceHost::getScriptFileNames`  when needed and change (increment) `LanguageServiceHost::getProjectVersion`. This way `LanguageService` will parse new files and reuse already parsed ones from `DocumentRegistry` while synchronizing the data via `synchronizeHostData`.

Sorry for buzzing you and thanks again for your help!
