### ISSUE TITLE
value literals act differently than literal type constants as indexes in index expressions

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#11820]
nightly build Oct 24, 2016

```typescript
const values: [number, string] = [1, 'a'];

const one = values[0]; // number, OK

const index = 0; // index is `0` (not just a number)
const another = values[index]; // expected number, actual: string | number <-- WHY?
```

**Comment by mhegazy** [comment]
duplicate of https://github.com/Microsoft/TypeScript/issues/6678

**Comment by aleksey-bykov** [comment]
no, i don't agree it's a dup

there it

**Comment by RyanCavanaugh** [comment]
This issue needs to be open because the other one hasn't been implemented yet? Please help me understand this

**Comment by aleksey-bykov** [comment]
the other one was created a year ago and asking for something that didn't have a chassis to be made
this one just states the fact that 2 expressions of the exact same type give different results
