### ISSUE TITLE
module not resolved in JS file using `var x = require('...')` syntax

### ISSUE THREAD

**Issue by waderyan** [Microsoft/TypeScript#11825]
_From @timty on October 19, 2016 17:18_

Intellisense works great for my postgress Pool type when explicitly declared:

![screen shot 2016-10-19 at 10 16 03 am](https://cloud.githubusercontent.com/assets/113954/19529521/15dfb24a-95e5-11e6-8c86-8a9f2e4c0e5a.png)

However when passed as a parameter to a function and described through a JSDoc parameter intellisense fails:

![screen shot 2016-10-19 at 10 14 57 am](https://cloud.githubusercontent.com/assets/113954/19529486/ec2f52ca-95e4-11e6-9748-f1ff9e3f6905.png)
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T15:27:10.246Z)
- OS Version: Darwin x64 15.6.0
- Extensions: Unity.unity-debug-1.0.1, benjaminromano.typings-installer-0.2.0, dbaeumer.vscode-eslint-1.0.7, dkundel.vscode-npm-source-0.0.3, joelday.docthis-0.3.4, mohsen1.prettify-json-0.0.3, ms-vscode.omnisharp-0.3.3, rafaelmaiolla.diff-0.0.1, stevencl.addDocComments-0.0.8, xabikos.JavaScriptSnippets-1.1.0, xabikos.ReactSnippets-1.1.1

_Copied from original issue: Microsoft/vscode#14008_

**Comment by waderyan** [comment]
@timty thank you for opening this issue. I have confirmed this with the latest bits and no extensions. Migrating to JavaScript language service. 

Code to copy and paste. 

```typescript
class Foo {

    bar() {}
}

var f = new Foo();
// IntelliSense works correctly
// f. 


/**
 * @param {Foo} x
 */
function zoo(x) {
    // IntelliSense is not being given
    x.
}
```

**Comment by sandersn** [comment]
@waderyan your code doesn't repro for me on master. Intellisense works fine when I paste the code in a javascript file. 

Intellisense does *not* work for me in a TypeScript file, but Typescript doesn't rely on jsdoc to give types to parameters. It only uses the documentation. 

1. When I paste the code into a typescript file that has `--noImplicitAny` turned on, I get an error at zoo(x).
2. If you change the jsdoc line to read `@param {Foo} x documentation`, you will see "documentation" in the quick info hover for `x`, indicating that Intellisense is actually working in typescript too.

@timty Are you using typescript or javascript? In a typescript file you will not get intellisense for the above reason. In a javascript file the code you gave will not work either, because jsdoc requires the parameter name to match:

```js
/**
 * @param {Pool} pool2 <-- Names must match
 */
function myFunction(pool2) {
  pool2./*intellisense should work now*/
}
```

If you're using typescript, then you have to use the postfix type syntax: `function myFunction(pool2: Pool) {`

**Comment by timty** [comment]
@sandersn @waderyan 

Thank you both for your responses. I am using javascript (nodejs). Sorry about the typo when recreating the issue. This does not work with correctly matching names either.

```
var pg = require('pg');

var pool = new pg.Pool("");
//intellisense works...
//pool.

/**
 * @type {Pool}
 */
var pool1;
//no intellisense here...
//pool1.

/**
 * 
 * @param {Pool} pool2
 */
function myFunction(pool2) {
//no intellisense here...
//pool2.
        
}
```
Intellisense here:

<img width="564" alt="screen shot 2016-10-24 at 5 00 23 pm" src="https://cloud.githubusercontent.com/assets/113954/19668273/7333ac56-9a0b-11e6-8af4-040a1fa98aaf.png">

No Intellisense with JSDoc type:

<img width="562" alt="screen shot 2016-10-24 at 5 01 31 pm" src="https://cloud.githubusercontent.com/assets/113954/19668292/932b9690-9a0b-11e6-97bf-b345302bcfb9.png">

No Intellisense with JSDoc param:

<img width="561" alt="screen shot 2016-10-24 at 5 02 33 pm" src="https://cloud.githubusercontent.com/assets/113954/19668309/afef7832-9a0b-11e6-8c89-b8b227b4edea.png">

**Comment by alexrock** [comment]
The type Pool was not imported in the module, it is visible as pg.Pool

**Comment by aluanhaddad** [comment]
@alexrock nice catch. 

> Typescript doesn't rely on jsdoc to give types to parameters. It only uses the documentation.

@sandersn really glad things are staying that way. jsdoc comments are often out of sync with the actual code. Also they are damn ugly. I have a colleague who uses JetBrain's Webstorm and it auto emits all these meaningless jsdoc tags into a pure typescript project... sorry for the rant.

**Comment by timty** [comment]
@alexrock @aluanhaddad 
It was imported via nodes require statement on the top line. Correct? I do get intelligence in this file for the pg.Pool type just not for my var and function parameter.

**Comment by aluanhaddad** [comment]
@timty you imported the module with the binding `pg`. 
That means that you must qualify all references to exports of the module with `pg` as in `pg.Pool`. The issue is that `Pool` is not in scope.
some options:
**A**
```ts
import pg = require('pg');
/**
 * @type {pg.Pool}
 */
var pool1;
```
**B**
```ts
import pg = require('pg');
import { Pool } from 'pg';
/**
 * @type {Pool}
 */
var pool1;
```

**Comment by timty** [comment]
@aluanhaddad Thanks for the feedback. Got it working with Option B...
```
var pg = require('pg');
import { Pool } from 'pg';

/**
 * @type {Pool}
 */
var pool1;
```
However for the sake of completeness this does not seem to work...
```
var pg = require('pg');
/**
 * @type {pg.Pool}
 */
var pool1;
```

**Comment by sandersn** [comment]
I don't think that the language service has special knowledge of the `var x = require('pg')` pattern, so it doesn't try to resolve 'pg' as a module. @vladima or @andy-ms, can you confirm?

It does understand ES module syntax and the typescript-only `import x = require('...')` that @aluanhaddad mentioned.

@timty it's good that you can use ES module syntax to work around this. Does Option B need both lines to work? 

I'll leave this bug open until we decide whether the language service should also support `var x = require('...')` in Javascript files.

**Comment by sandersn** [comment]
@andy-ms poked around the code and there *is* [code that looks for `require` in Javascript: `collectRequireCalls`](https://github.com/Microsoft/TypeScript/blob/master/src/compiler/program.ts#L1063). So it must be failing to work as intended.

**Comment by timty** [comment]
@sandersn @andy-ms 

Your suspicions are correct. No intellisense with the require pattern at least in this case.

No Intellisense here:
```
var pg = require('pg');

/**
 * @type {Pool}
 */
var pool1;
//no intellisense
pool1.
```

Intellisense works here:
```
import { Pool } from 'pg';

/**
 * @type {Pool}
 */
var pool1;
//intellisense works
pool1.
```

**Comment by mhegazy** [comment]
The issue here is that there is no `Pool` in scope. moreover, `pg` is a value and not a namespace, so there is no type called `pg.Pool`. 

in the case of the ES6 import, there is a type called `Pool` and then things work. 

if we want to make this to work, we need to make sure that `pg` is a namespace as well as a value, and to use it you will need to fully qualify it as `pg.Pool`.

**Comment by teppeis** [comment]
@mhegazy 
> we need to make sure that pg is a namespace as well as a value, and to use it you will need to fully qualify it as pg.Pool.

Yes! In TS 2.3, `checkJs` was introduced. So this feature is more important now.

```js
var pg = require('pg');

/** @type {pg.Pool} */
var pool1;
```
It should work for intellisense and checkJs.

https://github.com/Microsoft/TypeScript/issues/14377 is another solution for this issue.

**Comment by enko** [comment]
@vladima you wrote the code for `collectRequireCalls`. Maybe you can shed some light into this issue? Thanks!

**Comment by mhegazy** [comment]
I do not think we should treat values as types or namespaces; this will just lead to confusion in the future. https://github.com/Microsoft/TypeScript/issues/14377 would be the way we would proceed with this request.

**Comment by teppeis** [comment]
@mhegazy I agree.
Treating values as types requires `const type = require('only-for-typing')` in JS code.
#14377 is better solution.

**Comment by mhegazy** [comment]
Seems like another variant of https://github.com/Microsoft/TypeScript/issues/16489
