### ISSUE TITLE
Incorrect inclusion of @types in a TypeScript project

### ISSUE THREAD

**Issue by waderyan** [Microsoft/TypeScript#11826]
_From @TomMarius on October 19, 2016 22:38_

According to https://www.typescriptlang.org/docs/handbook/tsconfig-json.html, if `"compilerOptions"`.`"types"` is specified, only the types you specify will be included in compilation. VS Code weirdly and unpredictably ignores this - in my case, it uses typings from `@types/node` instead of the one I specified (webpack-env). Compilation itself passes with no errors.
- VSCode Version: 1.6.1
- OS Version: Windows 10 Pro

Steps to Reproduce:
1. create a Typescript project, install `@types/node` and `@types/webpack-env`
2. specify `"compilerOptions"`.`"types"` (e.g. `[ "webpack-env" ]`)
3. watch how your `require.ensure(...)` gets underlined

_Copied from original issue: Microsoft/vscode#14025_

**Comment by mhegazy** [comment]
This seems to be working fine for me locally.
![animation](https://cloud.githubusercontent.com/assets/8000722/19666889/1012f61c-9a02-11e6-9375-5270e3987750.gif)

**Comment by mhegazy** [comment]
closing for now. please reopen if still an issue.
