### ISSUE TITLE
Avoid "Duplicate identifier", if possible (e.g. same version)

### ISSUE THREAD

**Issue by donaldpipowitch** [Microsoft/TypeScript#11838]
**TypeScript Version:**  2.0.3

**Scenario**

When I develop libs or components which should be used by others I often like to _develop_ my lib inside several examples. E.g. when I write a React component I like to _see_ my component inside some single page application which also document how to use my components.

To do that I like to just reference my _source_ from inside my example: https://github.com/donaldpipowitch/typescript-duplicate-identifier/blob/master/examples/simple/src/index.tsx#L3

This is very handy as I don't need to build my component and then `npm install` it in my examples. But sadly I often run into "Duplicate identifier" errors. (Same happens if you symlink it.)

In my example I get this:

```
ERROR in [default] /typescript-duplicate-identifier/examples/simple/node_modules/@types/react/index.d.ts:7:20
Duplicate identifier 'React'.

ERROR in [default] /typescript-duplicate-identifier/node_modules/@types/react/index.d.ts:7:20
Duplicate identifier 'React'.
```

My proposal: In this case `react/index.d.ts` is absolutely the same in both cases. TypeScript _could_ warn about redundant typings (but I personally wouldn't want a warning), but IMHO it is _wrong_ to throw an error as there virtually isn't an error - "just" redundant data.

TypeScript could check for the `typesPublisherContentHash` of `@types/react/package.json` or maybe even for _version_ (with respect to the given SemVer range inside my examples `package.json`).

Note: I know there are many "Duplicate identifier" issues here, so I thought it would be good to break it down to a specific problem (e.g. ignore same versions). Maybe we can make the situation with "Duplicate identifier better step by step.

**Code**

https://github.com/donaldpipowitch/typescript-duplicate-identifier

**Comment by mhegazy** [comment]
@donaldpipowitch I am not able to see the issue locally. i did clone your repo, ran npm install on the top level as well as on `example\simple` and i am not getting any errors. what i am missing?

**Comment by donaldpipowitch** [comment]
Did you run `npm run build` inside `example/simple`.

**Comment by mhegazy** [comment]
```sh
c:\test\11838\typescript-duplicate-identifier\examples\simple>npm run build

> foo@1.0.0 build c:\test\11838\typescript-duplicate-identifier\examples\simple
> webpack

Hash: b7d3442da5b747ab195d
Version: webpack 2.1.0-beta.25
Time: 4625ms
       Asset     Size  Chunks             Chunk Names
    index.js   857 kB       0  [emitted]  main
index.js.map  1.02 MB       0  [emitted]  main
    + 205 hidden modules

```

**Comment by donaldpipowitch** [comment]
That is really strange. So you have a `typescript-duplicate-identifier/node_modules/@types/react/index.d.ts` and a `typescript-duplicate-identifier/examples/simple/node_modules/@types/react/index.d.ts`, but `npm run build` in the example doesn't throw?

Did we just discovered a different bug between Mac and Windows...?

**Comment by mhegazy** [comment]
> That is really strange. So you have a typescript-duplicate-identifier/node_modules/@types/react/index.d.ts and a typescript-duplicate-identifier/examples/simple/node_modules/@types/react/index.d.ts, but npm run build in the example doesn't throw?

Yes i have both files, and seems to be building fine for me. i am using typescript@next though.

**Comment by mhegazy** [comment]
> . i am using typescript@next though.

Never mind, your command is not using tsc any ways. it is using webpack.

**Comment by mhegazy** [comment]
so i do not know :)

**Comment by donaldpipowitch** [comment]
It looks like this bug only occurs with `2.0.3`. It works with `2.0.6` and `@next`.
