### ISSUE TITLE
[Transforms]: Incorrect emit of class decorator code

### ISSUE THREAD

**Issue by ahagelstein** [Microsoft/TypeScript#11831]
**TypeScript Version:**  typescript@2.1.0-dev.20161025

The bug described in #11322 and #10840 still exists in the latest nightly.
Please give me a feedback for this. Thanks.

**Comment by RyanCavanaugh** [comment]
You can leave comments there instead of logging new issues. Please don't create more noise for us when the thing causing our inability to address every issue in a timely manner is the amount of noise present!
