### ISSUE TITLE
Bug: Accessing protected members from a static function in a derived class is declined.

### ISSUE THREAD

**Issue by 0815fox** [Microsoft/TypeScript#11832]
**TypeScript Version:**  2.0.3

```ts
class C1 {
	protected foo() {};
	static generateFor(x:C1) {
		const RetVal = new C1();
		RetVal.foo(); //Compiler allows access of protected member from static method in the class itself
		return RetVal;
	}
}

class C2 extends C1 {
	static generateFor(x:C2) {
		const RetVal = new C1();
		RetVal.foo(); //Compiler disallows access of protected member from static method in child class
		//error TS2446: Property 'foo' is protected and only accessible through an instance of class 'C2'.
		return RetVal;
	}
}
```

**Expected behavior:** A static function in a class extending a class C can access all **protected** and public, but not private members of instances of C

**Actual behavior:** Protected members are not accessible,Compiler throws TS2446

For reference the simple case without inheritance, which works as expected:
- A static function in a class C can access all private,protected and public members of instances of C (works as expected)

**Comment by RyanCavanaugh** [comment]
Why would a static method be allowed to do something an instance method can't? See also #11278, #10637, #8512

**Comment by 0815fox** [comment]
> Why would a static method be allowed to do something an instance method can't? See also #11278, #10637, #8512
Instance methods can access protected members of the base class. That's the purpose of protected.

**Comment by RyanCavanaugh** [comment]
Please see the linked issues.

**Comment by 0815fox** [comment]
Okay, I see the point in #8512. I will discuss on there.

**Comment by aluanhaddad** [comment]
Just thinking out loud here but if ECMAScript ever introduces nested, instance member classes, we could end up with something interesting like Scala's path-dependent types.

**Comment by aluanhaddad** [comment]
Actually I suppose we already have that with class expressions. As much as I think classes are over used there is something really interesting about combining classes and closures...
