### ISSUE TITLE
Can't get compile on save to work

### ISSUE THREAD

**Issue by dziedrius** [Microsoft/TypeScript#11836]
**TypeScript Version:**  2.0.3
**VisualStudio Version:** 2015 Update 3

In my project file there's following configuration:

```
 <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCPU'">  
    <TypeScriptTarget>ES5</TypeScriptTarget>
    <TypeScriptJSXEmit>None</TypeScriptJSXEmit>
    <TypeScriptCompileOnSaveEnabled>True</TypeScriptCompileOnSaveEnabled>
    <TypeScriptNoImplicitAny>False</TypeScriptNoImplicitAny>
    <TypeScriptModuleKind>None</TypeScriptModuleKind>
    <TypeScriptRemoveComments>False</TypeScriptRemoveComments>
    <TypeScriptOutFile />
    <TypeScriptOutDir>app\compiled-javascript</TypeScriptOutDir>
    <TypeScriptGeneratesDeclarations>False</TypeScriptGeneratesDeclarations>
    <TypeScriptNoEmitOnError>True</TypeScriptNoEmitOnError>
    <TypeScriptSourceMap>True</TypeScriptSourceMap>
    <TypeScriptMapRoot />
    <TypeScriptSourceRoot />
  </PropertyGroup>
<Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.targets" Condition="Exists('$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.targets')" />
```

And I can't get it to work. Project builds fine and javascripts are transpiled to specified directory after build as they should, it just does not transpile on saving file. 

I've checked with process monitor, it does not invoke tsc.exe when I save changes in ts file and I can't reproduce it on clean project, meaning that in clean project it works fine, even if I copy typescript config part from the broken project. Is there anything more, that I could to troubleshot the issue, enable any logging?

**Comment by mhegazy** [comment]
you have a tsconfig.json in your project?

**Comment by dziedrius** [comment]
No, I do not. Should I?

**Comment by mhegazy** [comment]
you could. but you do not need to. 

Can you share a project we can debug against?

**Comment by dziedrius** [comment]
Not really, as I understand typescript visual studio plugin is not open sourced and there's no way to debug it by my self? If not, I guess I need to spend more time trying to pinpoint problem.
