### ISSUE TITLE
Type narrowing on class members not considering changes made by function calls

### ISSUE THREAD

**Issue by thomas-r7** [Microsoft/TypeScript#11837]
**TypeScript Version:**  nightly (2.1.0-dev.20161025)

**Description**
When the type of a class member has been narrowed from a union type (e.g. '0|1|2') to a single type (e.g. '0'), calling a member function that modifies the class member to a different type or value does not 're-widen' the type again, resulting in a conflict between what the compiler thinks is true and what is actually true.

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
class MyTestClass {
    private _myNumber: 0|1|2 = 0;

    public doThing(): void {
        // This narrows this._myNumber to 0
        if (this._myNumber === 0) {

            // This changes _myNumber to 1 outside of this method
            this.doChangeyThing();

            // Compile error - even though _myNumber is 1, the type was narrowed to 0!
            if (this._myNumber === 1) { // error TS2365: Operator '===' cannot be applied to types '0' and '1'.
                console.log("It's 1!");
            } else {
                console.log("It's not 1!");
            }
        }
    }

    private doChangeyThing(): void {
        this._myNumber = 1;
    }
}

const thing = new MyTestClass();
thing.doThing();

```

**Expected behavior:**

Example compiles without issue. When running, the message "It's 1" is printed to the console.

Calling this.doChangeyThing() should either widen the type of this._myNumber back to '0|1|2' (if it's impossible or difficult for the compiler to analyse what doChangeyThing might do), or '1' if it is.

**Actual behavior:** 

Compiler returns the following error:

> Test.ts(12,17): error TS2365: Operator '===' cannot be applied to types '0' and '1'.

**Comment by RyanCavanaugh** [comment]
Discussed at #9998 and other issues

**Comment by masaeedu** [comment]
@RyanCavanaugh So is this a bug? 

```ts
enum E { One, Two }

class C {
  e: E;
  changeToTwo() {
    this.e = E.Two;
  }
}

function f(c: C) {
  if (c.e === E.One) {
    c.changeToTwo();
    assert(c.e === E.Two); // Compile error, flow analysis still thinks c.e is E.One
  }
}
```

**Comment by RyanCavanaugh** [comment]
@masaeedu not a bug in terms of a literal bug (e.g. we can't just "fix" it); rather a design limitation
