### ISSUE TITLE
Static analysis on Enum properties is incorrect

### ISSUE THREAD

**Issue by daschult** [Microsoft/TypeScript#11843]
**TypeScript Version:**  2.0.3 / nightly (2.1.0-dev.201xxxxx)

**Code**

```ts
// Create an enum with three possible values
enum Enum {
    E1,
    E2,
    E3
}

// Create a class with one member variable.
class A {
    private _value = Enum.E1;

    // Provide a getter and setter method using property syntax.
    public get value(): Enum {
        return this._value;
    }
    public set value(value: Enum) {
        this._value = value;
    }

    // Provider a getter and setter method using method syntax.
    public getValue(): Enum {
        return this._value;
    }
    public setValue(value: Enum) {
        this._value = value;
    }
}

const a = new A();
// At this point, "nothing" is known about a.value, so this check passes the compiler just fine.
if (a.value === Enum.E1) {
    // Now we know that a.value has value/type Enum.E1, so this second, redundant check is fine.
    if (a.value === Enum.E1) {
        console.log("Check 1a");
    }
    
    // However, this check will produce a compiler error, because the compiler "knows" that a.value
    // has value/type Enum.E1. There's no point in checking whether it has value/type Enum.E2,
    // right?
     // Compiler: error TS2365: Operator '===' cannot be applied to types 'Enum.E1' and 'Enum.E2'.
    if (a.value === Enum.E2) {
        console.log("Check 1b");
    }

    // No compiler errors here, because it is a method call and no assumptions are being made about
    // its return value.
    if (a.getValue() === Enum.E2) {
        console.log("Check 1c");
    }
}

a.value = Enum.E2;
// This line won't produce an error. The compiler will (most likely) just optimize this if-statement
// away because line 51 shows that a.value now is value/type Enum.E2.
// Compiler: error TS2365: Operator '===' cannot be applied to types 'Enum.E2' and 'Enum.E1'.
if (a.value === Enum.E1) {
    console.log("Check 2");
}

a.setValue(Enum.E3);
// This creates a compile-time error because the compiler thinks that a.value is still Enum.E2,
// even though setValue() sets a.value to be Enum.E3.
// Compiler: error TS2365: Operator '===' cannot be applied to types 'Enum.E2' and 'Enum.E1'.
if (a.value === Enum.E1) {
    console.log("Check 3");
}
```

**Expected behavior:**
I expect to not get compiler errors.
**Actual behavior:** 
I get three compiler errors:
error TS2365: Operator '===' cannot be applied to types 'Enum.E1' and 'Enum.E2'.
error TS2365: Operator '===' cannot be applied to types 'Enum.E2' and 'Enum.E1'.
error TS2365: Operator '===' cannot be applied to types 'Enum.E2' and 'Enum.E1'.

**Comment by masaeedu** [comment]
@daschult Why do you not expect to get compiler errors? It seems from the comments you're already aware why the errors arise.

**Comment by daschult** [comment]
@masaeedu I don't expect to get a compiler error, because it's not an error. If anything it should be a warning, because it really should be saying, "This comparison will always result in false based on the pre-existing logic."
However, that's not entirely true. In my example, I've shown that I get compiler errors when I use get and set functions, which are just that: functions. They aren't variables, but it appears as though the Typescript compiler is trying to treat them as variables.

**Comment by mhegazy** [comment]
>  If anything it should be a warning

All TS errors do not block emit. so they are practically warnings, you can ignore them if you see this fit.

> These errors seem to really be saying that the compiler can do an optimization on my behalf, but its triggering it as an error instead of removing the dead code.

The error is just saying that you are comparing two types that the compiler is convinced are incompatible. There is nothing here about whether this condition is guaranteed to be true or false. 

Looking at the control flow  if you assign `a.value` `Enum.E2`, then the only possible value is `Enum.E2`. similarly if a variable is known to only have values of type `number` then comparing it to a value of type `string` is invalid; and indicates that there is a logic issue that should be examined.

> I 've shown that I get compiler errors when I use get and set functions, which are just that: functions

The compiler does not track side effects, so your set function impact on the property is not really observed by the compiler. There is more discussion about this issue in https://github.com/Microsoft/TypeScript/issues/9998. Your get function returns a more general type than what the control flow has asserted, so the comparison is valid.

**Comment by aluanhaddad** [comment]
> These errors seem to really be saying that the compiler can do an optimization on my behalf, but its triggering it as an error instead of removing the dead code.

On the contrary, it is optimizing your code but not for the sake of performance. It is actually improving the correctness of your code, the readability and maintainability of your code, by catching what is most likely a bug.

I have always hated when having to read through dozens of repetitive branches like
```ts
if (y !== null && x === 'a') {
   return 'x was "a" and y was null';
} else if (y === null && x === 'a') {
    return 'x was "a" and y was not null';
} ...
...
```
The new CFA features have found a lot of existing world bugs in my experience and an added bonus is that TypeScript is actually making redundant, superstition checks compile time errors, improving code quality. I now want this feature in every typed language I work with, and I think we will many languages pick it up.

**Comment by RyanCavanaugh** [comment]
Limitations of side effect tracking already discussed at #9998
