### ISSUE TITLE
TSServer: call signatures incorrectly resolved by getResolvedSymbol

### ISSUE THREAD

**Issue by weaknespase** [Microsoft/TypeScript#11857]
**TypeScript Version:**  2.0.2 -> nightly (2.1.0-dev.20161026)

In JavaScript files, if function expression, that used as constructor, assigned to variable, constructed objects has incorrect type resolved as "any" when that variable used as reference.

**Code**

Test example for VSCode:

```
function TestObj(){
    this.property = "value";
}
var constructor = TestObj;
var instance2 = new TestObj(); //<-- instance2 resolved as TestObj instance
var instance = new constructor(); //<-- instance resolved as having "any" type
```

Well it's very inconvenient, if you ask me, because there are no way to get any autocompletion for ES5-style object constructors in default CommonJS exports, which is my favorite. Thus, I spent some time and found the place, where it happens - in `src/compiler/checker.ts` in method `checkCallExpression` inside `createTypeChecker`. 

```
const funcSymbol = node.expression.kind === SyntaxKind.Identifier ?
    getResolvedSymbol(node.expression as Identifier) :
    checkExpression(node.expression).symbol;
```

If I replace lines above by

```
const funcSymbol = checkExpression(node.expression).symbol;
```

everything works as it should, though i don't know if there will be any implications by doing that.

**Comment by RyanCavanaugh** [comment]
I think that fix may be correct. I'll take a look.

**Comment by weaknespase** [comment]
Had some free time to look around more. `getResolvedType` doesn't resolve symbols recursively, hence the problem with constructor references in variables - it just returns first matching symbol. `checkExpression` performs type resolution for every identifier in chain.
