### ISSUE TITLE
Use of (<any>...) removes meaningful (sic) whitespace

### ISSUE THREAD

**Issue by jcansdale** [Microsoft/TypeScript#11856]
**TypeScript Version:**  2.0.3

**Code**

```ts
function setFile(button, file) {
  let currentFile = file
  (<any>button).attr('disabled', false)
}
```

**Expected behavior:**

I'd expect it to keep the meaningful whitespace:

```js
function setFile(button, file) {
    var currentFile = file
    (button).attr('disabled', false);
}
```

**Actual behavior:** 

Instead, `file` is called with `button`:

```js
function setFile(button, file) {
    var currentFile = file(button).attr('disabled', false);
}
```

In my real life code, this causes it to fail silently. It can be made to work with a ';'. but this wasn't immediately obvious.

**Comment by wallverb** [comment]
https://github.com/Microsoft/TypeScript/issues/11669

**Comment by wallverb** [comment]
There is no such thing as meaningful whitespace. Your expected and actual behavior is functionally identical. 
https://github.com/Microsoft/TypeScript/issues/11669

**Comment by jcansdale** [comment]
@wallverb,

Thanks for the explanation. 😊 This reinforces my preference for explicitly ending lines with ';'!

I'm be interested to know how you would go about overriding a missing method signature in a code base that doesn't end lines with ';'?

For example, to convert the following JavaScript (where `attr(string, boolean)` isn't defined in the TypeScript .d.ts file):

```js
function setFile(button, file) {
  let currentFile = file
  button1.attr('disabled', true)
  button2.attr('disabled', false)
}
```

What would the TypeScript look like? I'm guessing this is one possibility:

```ts
function setFile(button, file) {
  let currentFile = file
  ;(<any>button1).attr('disabled', true)
  ;(<any>button2).attr('disabled', false)
}
```

But neither this, nor ending lines with ';' for a single method seem ideal. Is there a cleaner way?

Thanks for any suggestions. I'll be sure to close this issue...

**Comment by kitsonk** [comment]
> Is there a cleaner way?

Never depend upon ASI, for the handful of times it is required, like the above. :-)

**Comment by RyanCavanaugh** [comment]
TypeScript's ASI behavior is the same as JavaScript's ASI behavior.

Attempting to forego semicolons in a language that only barely works without them is a terrible plan. Not much we can do about it.

**Comment by jcansdale** [comment]
Just in case anyone stumbles across this issue. To fix it, I simply created a 'jquery-extended.d.ts' file in my work space with the following contents:

```ts
interface JQuery {
    attr(attributeName: string, value: boolean): JQuery;
}
```

This fixed the compilation error without any casting ugliness. I don't know if this is the recommended approach, but it seems to work. 😄
