### ISSUE TITLE
Compiler Error on Empty file: Cannot find name 'Promise'.

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/TypeScript#11864]
**TypeScript Version:**  master, commit 8ad68adac956eafa865b78c9c45cae1958c963cd

Reproduced on Win10 and Ubuntu 16.04.

**Code**

Note: this initially appeared with nonempty files, but I tried to minimize the repro.

1) Create an empty file called "empty.ts" in a folder without tsconfig.json or anything else

2) `rm -rf node_modules` in the typescript repo

3) `npm install` and (in case you didn't have it before) `npm install -g jake` 

4) build typescript with 'jake local'

5) Run `node /path/to/built/local/tsc.js /path/to/anything.ts` from the TypeScript repo folder.

**Expected behavior:**

Compiles successfully.

**Actual behavior:** 

Fails with the following errors:

```
node_modules/@types/del/index.d.ts(10,40): error TS2304: Cannot find name 'Promise'.
node_modules/@types/del/index.d.ts(11,62): error TS2304: Cannot find name 'Promise'.
node_modules/@types/del/index.d.ts(13,43): error TS2304: Cannot find name 'Promise'.
node_modules/@types/del/index.d.ts(14,65): error TS2304: Cannot find name 'Promise'.
```

**Comment by aozgaa** [comment]
The problem was caused by some contents of the `node_modules` folder in the TypeScript repo folder.

If there is no `tsconfig.json` in the target directory, it appears node modules are automatically loaded by walking up from the working directory, following the rules on [the module resolution page](https://www.typescriptlang.org/docs/handbook/module-resolution.html).
It's unclear to me why, philosophically, any modules are loaded at all.

Building from a path that doesn't include the TypeScript repo prevents us from loading the problematic node module.

Workarounds:

1) call `tsc.js` from a working directory that doesn't include the offending `node_modules` along the path. Ie: don't issue the build command while in the TypeScript repo.

2) [Add a `tsconfig.json` file](http://www.typescriptlang.org/docs/handbook/tsconfig-json.html) which includes the single file, and build by pointing towards that.

3) Add the compiler flag `--lib es6` to the commandline operation so promises are available.

This may be related to #11803.

**Comment by aozgaa** [comment]
Any thoughts on proper behavior here / why we do what we do in the status quo, @mhegazy, @billti, @vladima ?

**Comment by mhegazy** [comment]
the node_modules\@types are automatically included. some of them depend on ES6 objects. so you get this error. I plan to discuss this in the next design meeting under https://github.com/Microsoft/TypeScript/issues/11396
