### ISSUE TITLE
Spec new overload resolution and type argument inference rules

### ISSUE THREAD

**Issue by danquirk** [microsoft/TypeScript#1186]
We've changed these algorithms to do multiple passes at times for various reasons but the spec does not currently reflect this. We also haven't written extensive tests for these new algorithms but bugs are being generated from the changes. We need to get this formalized and tested if these changes are shipping with VS releases now.

**Comment by RyanCavanaugh** [comment]
The spec is now an "archived" artifact and we won't be tracking defects against it anymore.
