### ISSUE TITLE
add a design time decorator that prevents properties from being renamed

### ISSUE THREAD

**Issue by zpdDG4gta8XKpMCd** [microsoft/TypeScript#11863]
we have so-called domain objects that come from the server, we, at the client side, can't really rename them without breaking the contract with the server, so doing renaming always imposes some risk, this risk could have been avoided if there was a way to lock an interface from unintended renamings

**Comment by mhegazy** [comment]
are these defined in a .d.ts or in a .ts file?

**Comment by aleksey-bykov** [comment]
no, it's in a plain *.ts

**Comment by aleksey-bykov** [comment]
in a ts file

**Comment by mhegazy** [comment]
so it does have an implementation packing it? or is it just some interfaces?

**Comment by aleksey-bykov** [comment]
it has an interface declaration + auxiliary functions like `create`, `areEqual` and `copy`

**Comment by RyanCavanaugh** [comment]
Closing due to low feedback volume
