### ISSUE TITLE
Design-type metadata for generic types

### ISSUE THREAD

**Issue by heruan** [Microsoft/TypeScript#11860]
Design-type metadata such as `design:type`, `design:paramtypes` and `design:returntype` are great to build modern JavaScript frameworks. It would be very useful to also have a `design:generics` metadata to keep track of generic types, e.g.
```typescript
class Foo {}
class Bar {}
class Baz {
    map: Map<Foo, Bar>;
}
```
would transpile to
```javascript
// ... Foo and Bar functions
var Baz = (function () {
    function Baz() {
    }
    __decorate([
        __metadata('design:type', Map),
        __metadata('design:generics', [ Foo, Bar ]),
    ], Baz.prototype, "map", void 0);
    return Baz;
}());
```

**Comment by mhegazy** [comment]
The issue of type serialization/"reflection" has been discussed multiple times (#2902, #2577, #3060). we already have #3628 to track this discussion; so i suggest moving this proposal to that issue.
