### ISSUE TITLE
Interface with all optional fields equals any other type

### ISSUE THREAD

**Issue by artaommahe** [Microsoft/TypeScript#11862]
**TypeScript Version:**  2.0.3

**Code**

```ts
interface ISmth {
  field?: string;
}

function foo(data: ISmth): void {}

const data = true;

foo(data);
```

**Expected behavior:**
Error due to `data` type is `boolean`, `foo()` expected param type is `ISmth`

**Actual behavior:** 
No error for any `data` type.

**Comment by RyanCavanaugh** [comment]
Duplicate #7485
