### ISSUE TITLE
TypeScript 2.0.6 VS Extension Breaks Intellisense

### ISSUE THREAD

**Issue by ZenSoftware** [Microsoft/TypeScript#11873]
**TypeScript Version:**  2.0.6

**Expected behavior:** Intellisense on .ts files in Visual Studio Enterprise 2015 to work

**Actual behavior:** All types not recognized, auto-completion does not work, and 'Go to Definition' does nothing.

**Note:** Intellisense works fine after reverting to **Typescript VS Extension: 2.0.3**.  There seems to be a change between **2.0.3** and **2.0.6** that breaks Visual Studio 2015 Intellisense entirely for my system.

**System:**
**Visual Studio Enterprise 2015:** 14.0.25431.01 Update 3
**Typescript VS Extension:** 2.0.6
**.NET FM:** 4.6.0.1586
**Node: v6.7.0** (VS configured to use node from 'External Tools' options from C:\Program Files\nodejs)

**Comment by mhegazy** [comment]
is this the case for all .ts file? an empty project? what version of Windows are you running?

**Comment by ZenSoftware** [comment]
OS:	Microsoft Windows 10 Home - 10.0.14393v Build 14393
File -> New -> Project -> HTML Application with TypeScript (This works fine.  HTMLElement has Intellisense for example)

Although the [Angular 2 - Quickstart](https://github.com/angular/quickstart) project that is fairly complex, utilizing the more advanced 2.0 features breaks Intellisense for example.  I have a fairly complex project utilizing all the **npm @types** method of including types.  It works just fine in Visual studios with **2.0.3.**  But there is definitely a change between **2.0.6** that breaks something critical.  I don't know how to investigate further.   Any ideas?

**Comment by ZenSoftware** [comment]
Attached below is an ActivityLog after my **Visual Studios Enterprise 2015** crashed with **Typescript VS Extension: 2.0.6** installed on the system spoken of in the aforementioned post.
[ActivityLog.xml](https://github.com/Microsoft/TypeScript/files/554674/ActivityLog.txt)

Hope this helps ^_^

**Comment by mhegazy** [comment]
from the log, this looks like a culpert:

```xml
  <entry>
    <record>590</record>
    <time>2016/10/27 00:09:07.597</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>LegacySitePackage failed for package [Microsoft.VisualStudio.LanguageServices.TypeScript.TypeScriptPackage, Microsoft.VisualStudio.LanguageServices.TypeScript, Version=14.0.0.0, Culture=neutral]Source: &apos;Microsoft.VisualStudio.ExtensibilityHosting&apos; Description: The Visual Studio component cache is out of date. Please restart Visual Studio.&#x000D;&#x000A;</description>
    <guid>{2FFE45C4-5C73-493C-B187-F2E955FF875E}</guid>
    <hr>80131500</hr>
    <errorinfo></errorinfo>
  </entry>
```

can you try and clear your MEF cache:

- Close VS
- Install TS 2.0.6
- Delete `%LOCALAPPDATA%\Microsoft\VisualStudio\14.0\ComponentModelCache`
- Start VS

**Comment by ZenSoftware** [comment]
Ok, so I went ahead and installed the VS extension: [Clear MEF Component Cache](https://visualstudiogallery.msdn.microsoft.com/22b94661-70c7-4a93-9ca3-8b6dd45f47cd)

I opened my complex Typescript 2.0 project, and all the types are now working again, with the **Typescript VS Extension 2.0.6** installed.  Seems like that did the trick.  Thanks a lot, I can get digging in again.  Big fan of the TS team by the way.  I've learnt a lot by watching this project grow.

**Note:** I did not have to do the following step to get Intellisense working again:

> - Delete %LOCALAPPDATA%\Microsoft\VisualStudio\14.0\ComponentModelCache

**Comment by mhegazy** [comment]
Thanks for confirming, and for the kind words. Did you have VS open when you first installed 2.0.6?

**Comment by ZenSoftware** [comment]
I generally try to close all instances of Visual Studio before installing extensions from an external installation package.  I uninstalled and reinstalled the TS VS extension a couple of times, hopping back and forth between **2.0.3** and **2.0.6**.  It was strange, **2.0.3** always seemed to have worked in bringing Intellisense back,  Although, **2.0.6** never worked once until you mentioned clearing the MEF Component Cache.

**Comment by IsaacBorrero** [comment]
I am having a similar problem.  Intellisense does not work.  I am working with Angular 2 as an FYI.

**Comment by mhegazy** [comment]
@IsaacBorrero, we would appreciate additional information.

**Comment by pmulac** [comment]
I have the same problem trying to use TypeScript Language Services in IntelliJ/Webstorm.  For example, unimplemented interfaces are not marked as errors.  Reverting to TypeScript 2.0.3 resolves the issue.
