### ISSUE TITLE
Cannot Build

### ISSUE THREAD

**Issue by mavericken** [Microsoft/TypeScript#11870]
I tried to build the TypeScript compiler following the instructions in the readme, but I got an error.  I tried on Windows 10 and Ubuntu 16.04 and got the same error on both.  It is my first time trying to build it, and I'm not sure if it is a problem with the instructions, a problem with me, or a problem with the current code.

```
rick@tg:~/code/TypeScript$ sudo npm install
rick@tg:~/code/TypeScript$ gulp local
[17:16:08] Requiring external module ts-node/register

/home/rick/code/TypeScript/node_modules/ts-node/dist/index.js:84
            throw new TSError(formatDiagnostics(configDiagnostics, cwd, ts, 0));
            ^
TSError: ⨯ Unable to compile TypeScript
The 'files' list in config file 'tsconfig.json' is empty. (18002)
rick@tg:~/code/TypeScript$ npm --version
3.10.8
rick@tg:~/code/TypeScript$ gulp --version
[17:17:03] Requiring external module ts-node/register
[17:17:03] CLI version 3.9.1
[17:17:03] Local version 3.9.1
rick@tg:~/code/TypeScript$ node --version
v6.8.1

```

**Comment by mhegazy** [comment]
noticed that today. seems to be caused by https://github.com/Microsoft/TypeScript/pull/11743. looking.

**Comment by mavericken** [comment]
The changes you made to ts-node are already available in NPM.  I was able to build after refreshing the NPM packages.  Thanks!
