### ISSUE TITLE
QUESTION: Advanced intersection type

### ISSUE THREAD

**Issue by tomitrescak** [Microsoft/TypeScript#11876]
Hi, we are preparing typings fro the amazing semantic-ui-react project.

One of the properties of the library is the possibility to define how the element will be rendered.
For example:

``` js
<Button>Text</Button>
```

is rendered as

``` js
<button class="ui button">Text</button>
```

But, if I want to make a link button I can do (note the **as** param)

``` js
<Button as="a" href="/">Text</Button>
```

is rendered as

``` js
<a class="ui button" href="/">Text</button>
```

Now, the problem is, that I do not know how to merge the typings based on the property specified in the "as" element.

What we have is this:

``` js
interface ButtonProps {
...
}

interface ButtonStatic extends React.StatelessComponent<IButtonProps> {
}

export const Button: ButtonStatic;
```

The idea is do do following, but the T needs to come from attribute "as":

``` js
interface ButtonStatic<T> extends React.StatelessComponent<IButtonProps & T> {
}

export const Button: ButtonStatic;
```

I pretty much know it won't be possible this way, but do you have any idea on how can I tell the element that it needs to merge props with another interface?

Thanks

**Comment by aluanhaddad** [comment]
I believe you _can_ accomplish this, but I don't know enough react to get it working. Basically, you want to use intersection and union types in a manner like
```ts
type AsProps = { as: 'a' } & typeof React.DOM.a | { as: 'input' } & typeof React.DOM.input;
```
Again I don't know react, but this should be possible. It is possible for arbitrary functions.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
