### ISSUE TITLE
Splitting namespace on multiple files with TS2.0 and vscode

### ISSUE THREAD

**Issue by npenin** [Microsoft/TypeScript#11879]
I am building a client framework, and would like to split my code among multiple files. I would also like that each file can participate in the same namespace to export different things (classes, interfaces, functions, vars, ...)

**TypeScript Version:**  2.0.3

**Code**

***comon.ts***
```ts
export namespace akala
{
    export var $$injector={register:function(name:string, item:any){}};
}
```

***clientify.ts***
```ts
///<reference path='./common.ts' />

akala.$$injector.register('$router', 'toto');
akala.$$injector.register('$location', 'tutu');
```
I tried `///reference` and `import`, but the compiler is always complaining that `akala` in clientify.ts does not exists.

**Expected behavior:**
The best solution to me would be to do an import with side effects (`import './common.ts') so that the namespace is declared as designed in the imported file, and that the definition generated can be reused without having to maintain one manually in parallel.

**Actual behavior:** 
src/clientify.ts(5,1): error TS2304: Cannot find name 'akala'.

**Comment by mhegazy** [comment]
The top-level `export`. in `export namespace akala` turns this file into a module. modules have their own scope and do not participate in the global namespace. modules need to be imported using import statements.

Please see http://www.typescriptlang.org/docs/handbook/modules.html for more details

if you do not intend to use modules, and you only use namespace in the global scope consider setting `--module none` and this `export` would be reported as an error.

**Comment by npenin** [comment]
I actually also tried without the export on the namespace, with no luck. Even setting module none in the tsconfig file, did not help. Any other idea ?

**Comment by mhegazy** [comment]
```cmd

c:\test\11879>type comon.ts
namespace akala
{
    export var $$injector={register:function(name:string, item:any){}};
}

c:\test\11879>type clientify.ts
akala.$$injector.register('$router', 'toto');
akala.$$injector.register('$location', 'tutu');

c:\test\11879>tsc --v
Version 2.0.6

c:\test\11879>tsc clientify.ts comon.ts

c:\test\11879>echo %ERRORLEVEL%
0
```

**Comment by npenin** [comment]
Indeed, I may have simplified too much my sample. My common.ts is having an import to another node modules, and I cannot use module none.

**Comment by mhegazy** [comment]
Then it is a module and you need to import it.

**Comment by npenin** [comment]
ok, but then, how can I extend my namespace across multiple files ?
