### ISSUE TITLE
Wrong showing of type description

### ISSUE THREAD

**Issue by microshine** [Microsoft/TypeScript#11881]
**TypeScript Version:**  2.0.3

**Code**
I have next declaration of `phoneCheck` function
![image](https://cloud.githubusercontent.com/assets/7333669/19756730/60e9303e-9c27-11e6-9d41-cc3a6ba32fc1.png)

**Expected behavior:**
Must to show `Callback<boolean>`

**Actual behavior:** 

TS shows wrong type name for Callback param on `phoneCheck` function. 
![image](https://cloud.githubusercontent.com/assets/7333669/19756834/00095766-9c28-11e6-93cf-35b843a6983e.png)

TS shows correct type name for Callback param on `data` param of callback. 
![image](https://cloud.githubusercontent.com/assets/7333669/19756805/d5a02496-9c27-11e6-8f6d-9b0c4a8b6133.png)

**Comment by RyanCavanaugh** [comment]
Please provide a self-contained repro, including text.

It's also not clear from your description exactly which text is wrong or what you expected the description to be, nor is it obvious where the caret is.

**Comment by microshine** [comment]
```typescript
type Callback<T> = (error: Error, data: T) => void;

class Test {
    post(params: number, cb: Callback<boolean>) {
    }
}

class Test2 extends Test {
    run () {
        this.post(1, (err, data2) => {})
    }
}
```

You can try this example. If I put mouse curcsor over `this.post` in `Test2` class I see `method post(params: number, cb: Callback<this>)`. If I put mouse co=ursor over `data2`, it shows `parameter data2: boolen`. It's not crytical but `cb: Callback<this>` is not right

I use VS Code IDE.

**Comment by mhegazy** [comment]
What do you expect `data2` should be?

**Comment by microshine** [comment]
@mhegazy It's boolean. But it has wrong description when I check post definition. It must be `Callback<boolean>`, but shows `Callback<this>`

**Comment by microshine** [comment]
@mhegazy It's boolean. But it has wrong description when I check post definition. It must be `Callback<boolean>`, but shows `Callback<this>`

**Comment by microshine** [comment]
I updated TS to v2.0.6. I can't repeat this error

**Comment by mhegazy** [comment]
thanks!
