### ISSUE TITLE
Typescript error TS5055

### ISSUE THREAD

**Issue by danfma** [Microsoft/TypeScript#11887]
**TypeScript Version:**  nightly (2.1.0-dev.20161027)

**Simulation**

Create a project with the following configuration:

```json
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es5",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "noImplicitAny": true,
    "noUnusedParameters": true,
    "noUnusedLocals": true,
    "noEmitOnError": true,
    "skipLibCheck": true,
    "declaration": true,
    "sourceMap": true,
    "outDir": "out/",
    "rootDir": "src",
    "baseUrl": "src",
    "moduleResolution": "node",
    "lib": [
      "es5",
      "es2015",
      "dom"
    ]
  },
  "exclude": [
    "node_modules"
  ]
}
```

The directory structure should be:

- project
  - src
    - index.ts
    - hello.ts
  - out

The content of the `hello.ts` could be:

```typescript
export function hello(name: string) {
  return `Hello, ${name}`;
}
```

The `index.ts` should re-export the hello module contents:

```typescript
export * from "./hello";
```

After that, compile twice using the vscode or the tsc:

* `tsc -p .`
* `tsc -p .`

**Expected behavior:**

Compile and produce again the js and the definitions.

**Actual behavior:** 

In the first compilation, it will compile normally. But at the second one, it will file with a message like `error TS5055: Cannot write file '.../hello.d.ts' because it would overwrite input file.

**Comment by danfma** [comment]
Just to point out, it works with the current production release version.

**Comment by mhegazy** [comment]
add your  `"outDir"` to your exclude list. i.e.:   `"exclude": ["node_modules", "out"]`

**Comment by danfma** [comment]
Ohhh man, what a mistake! Thanks! ;)
