### ISSUE TITLE
Property 'includes' does not exist on type string[]

### ISSUE THREAD

**Issue by codeepic** [Microsoft/TypeScript#11890]
Hi, 

I am trying to use 
`Array.prototype.includes` [includes function explained on MDN network](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/includes) but I am getting the following error:

**Property 'includes' does not exist on type 'string[]'.**

`includes` is part of EcmaScript 6.

I am using Typescript version 2.0.3

**Comment by mhegazy** [comment]
use `--lib es2015` (since it is ES2015-specific). if you also want the DOM definitions use `--lib dom,es2015`

**Comment by krokofant** [comment]
I don't see how this is es2015 specific. Looking at the docs it's included in the es2016 and es2017 specs so adding `es2015` doesn't work, at least for me.

So adding any of es2016, es2016.array.include or es2017 works.

**Comment by mhegazy** [comment]
thanks @krokofant for the correction. You are right, it is `-lib es2016` or `--lib dom es2016`.

**Comment by mhegazy** [comment]
updated [comment](https://github.com/Microsoft/TypeScript/issues/11890#issuecomment-256720293) above

**Comment by nmccready** [comment]
What is the tsconfig.json option for this?

**Comment by mhegazy** [comment]
"Lib"

**Comment by odykyi** [comment]
Okay, to overcome the issue, I needed to set  tsconfig.json` compilerOptions.lib from "es6" to "es7" as follows:

```
"lib": [
  "dom",
  "es7"
],
```
I'm not sure if this causes other problems, though. "includes" is implemented for 'string' (not Array) in ES6, and for arrays only in ES7.

**Comment by Mathias54** [comment]
change 'target' worked for me:

`{
  "compilerOptions": {
    "target": "es2016",
  },
}`
