### ISSUE TITLE
Wrong function type when mixing default initialized parameters with regular parameters

### ISSUE THREAD

**Issue by luisabreu** [Microsoft/TypeScript#11900]
VS Code does not show the correct parameter types on the tooltip when you mix default initialized parameters with regular parameters. Ex.:

function test(name= "John", age: number){}

The tooltip shown when you put the mouse cursor over test says (name: string, age: number): void instead of (name?:string, age: number).

![wrongsignature](https://cloud.githubusercontent.com/assets/521086/19780398/d7606fb6-9c7c-11e6-90bd-01da8f5b6acc.png)

**Comment by mhegazy** [comment]
Optional parameters can not appear before required ones. so `nome` it is not optional. it just has a default parameter.

**Comment by luisabreu** [comment]
in my example, name is not an optional parameter. It's a default initialized parameter. According to the docs:

"Unlike plain optional parameters, default-initialized parameters don’t need to occur after required parameters. If a default-initialized parameter comes before a required parameter, users need to explicitly pass undefined to get the default initialized value. "

https://www.typescriptlang.org/docs/handbook/functions.html

The problem is that the tooltip is showing the wrong information, though the control flow is being performed correctly.

**Comment by mhegazy** [comment]
Defaults do not show in signature anywhere else, they are considered function implementation detail.;so I am not sure I understand the request here.

**Comment by RyanCavanaugh** [comment]
@mhegazy I think when a default exists, we should be pushing ` | undefined` into the parameter type

**Comment by mhegazy** [comment]
is `--strictNullChecks` on?

**Comment by mhegazy** [comment]
With `--strictNullCheck` yes it should be `T | undefined`.

**Comment by luisabreu** [comment]
Yep, strict null check is on.

**Comment by sandersn** [comment]
Fix is up at #12033

**Comment by akarzazi** [comment]
```
function AddProduct(product: string, quantity = 1) {
  // I think quantity should be number;
}
```
If default initialized parameter is automatically converted to `T | undefined`.
How can you enforce `T` as type ?

**Comment by blakeembrey** [comment]
@akarzazi Inside the function would be `T`, while the call signature is `T | undefined` as it has a default initialiser (the default value is used when the argument is `undefined`).
