### ISSUE TITLE
TSServer: Extra underscores in properties

### ISSUE THREAD

**Issue by weaknespase** [Microsoft/TypeScript#11902]
**TypeScript Version:**  nightly (2.1.0-dev.20161026)

Continuing to use ES5-style constructors found another bug - property name will contain extra underscore if it starts with 2 underscores, i'm sure it is related to language service.

**Code**

```
function MyObject(){
    this.__property = 1;
}
var instance = new MyObject();
```

**Expected behavior:**

Listing `__property` with two underscores, when using completion menu appears for `instance`.

**Actual behavior:** 

![2-or8](https://cloud.githubusercontent.com/assets/12257359/19777811/a169f19c-9c82-11e6-92f2-dafc03fdca1c.png)

**Notes**
- Appears only when property declared using `this` inside constructor. Prototype properties defined through `prototype` property and properties defined inside object literal come up fine.
- Symbol for `this.<property>` doesn't have 'name' attribute in declaration, but in the case of `prototype.<property>` it is here.

**Comment by weswigham** [comment]
This should be fixed by #16915.
