### ISSUE TITLE
Overloads Missing From Completions

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/TypeScript#11911]
**TypeScript Version:**  master: commit adfdae0dc47db5ad8248d26929a7b31cb895a539
Tested on Win10 in vscode 1.6.1 (commit 9e4e44c19)

**Code**

Place the cursor at '|' and type an open paren.

```ts
class A {}
class B { x: number }
class C { y: number }
class D { z: number }


/**
 * A doc comment.
 */
export function f(d: D): string; 
export function f(c: C): string; 
export function f(b: B): string;
export function f(a: A): string {
    return "";
}

f|
```

**Expected behavior:**

Get 4 overloads, one for each declaration.

**Actual behavior:** 

Get 3 overloads. The one for argument type `A` is missing.

**Comment by HerringtonDarkholme** [comment]
I might be wrong, but function signatures do only include overload declarations, without implementation signature. I have seen this since 1.8.

**Comment by RyanCavanaugh** [comment]
The implementation signature is not an overload. See https://github.com/Microsoft/TypeScript/wiki/FAQ#why-am-i-getting-supplied-parameters-do-not-match-any-signature-error
