### ISSUE TITLE
Code completion in derived class

### ISSUE THREAD

**Issue by Lenne231** [microsoft/TypeScript#11915]
**TypeScript Version:**  2.0.3

**Code**

![image](https://cloud.githubusercontent.com/assets/2046557/19797471/8e3bacd2-9ceb-11e6-8f2f-917dca21515a.png)

**Expected behavior:**
`mount` shows up in the completion list.

**Actual behavior:** 
`mount` doesn't show up in the completion list.

**Comment by RyanCavanaugh** [comment]
Works now
