### ISSUE TITLE
Navigating via require statements in JavaScript

### ISSUE THREAD

**Issue by waderyan** [Microsoft/TypeScript#11923]
_From @plaanupam on October 20, 2016 8:3_

- VSCode Version: 1.6
- OS Version: Ubuntu 16.04
- Language: JavaScript
I am able to navigate through require statements in JavaScript. It directs me to the file, when I press ctrl+click on a required file.

My friend is also using VSC and getting intellisense, but he is not able to jump through files via require statement.

I am unable to find a setting which is different in our VSC. 
jsconfig.js file is the same in both our projects and I am unable to find a setting that controls this behavior. 
I may be missing something trivial here, but how can I enable this feature everywhere.

Thanks

 

_Copied from original issue: Microsoft/vscode#14049_

**Comment by waderyan** [comment]
@plaanupam thank you for opening this issue. This is a known bug. 

@bowdenk7 can you help me find where we are tracking this issue in TypeScript repo? I can't find it.

**Comment by mhegazy** [comment]
Here is issue tracking it: https://github.com/Microsoft/TypeScript/issues/9251
