### ISSUE TITLE
Long tuples lose appropriate type information

### ISSUE THREAD

**Issue by jocull** [Microsoft/TypeScript#11924]
**TypeScript Version:** 
2.0.3 / nightly (2.1.0-dev.201xxxxx)

Limit is seemingly even lower in 1.8.9, with type information loss after the tuple is 6 or more elements wide.

**Code**

``` ts
// A *self-contained* demonstration of the problem follows...
Promise.all([
    Promise.resolve(1),
    Promise.resolve(''),
    Promise.resolve(new Date()),
]).then(results => {
    let [
        a, // Number
        b, // String
        c, // Date - Everything is ok!
    ] = results;
});

Promise.all([
    Promise.resolve(1),
    Promise.resolve(''),
    Promise.resolve(new Date()),
    Promise.resolve({}),
    Promise.resolve({ hi: 'hello' }),
    Promise.resolve([]),
    Promise.resolve(null as string),
    Promise.resolve(1),
    Promise.resolve(''),
    Promise.resolve(new Date()),
    Promise.resolve({}), // Length == 11
]).then(results => {
    let [
        a, // Everything is {} now?
        b,
        c,
        d,
        e,
        f,
        g, 
        h,
        i,
        j,
        k, // << -- Error!
           // "Tuple with length 10 cannot be assigned to tuple with length 11"?
    ] = results;
});
```

Code [on the playground](http://www.typescriptlang.org/play/index.html#src=Promise.all%28%5B%0D%0A%09Promise.resolve%281%29%2C%0D%0A%09Promise.resolve%28%27%27%29%2C%0D%0A%09Promise.resolve%28new%20Date%28%29%29%2C%0D%0A%5D%29.then%28results%20%3D%3E%20%7B%0D%0A%09let%20%5B%0D%0A%09%09a%2C%20%2F%2F%20Number%0D%0A%09%09b%2C%20%2F%2F%20String%0D%0A%09%09c%2C%20%2F%2F%20Date%20-%20Everything%20is%20ok!%0D%0A%09%5D%20%3D%20results%3B%0D%0A%7D%29%3B%0D%0A%0D%0APromise.all%28%5B%0D%0A%09Promise.resolve%281%29%2C%0D%0A%09Promise.resolve%28%27%27%29%2C%0D%0A%09Promise.resolve%28new%20Date%28%29%29%2C%0D%0A%09Promise.resolve%28%7B%7D%29%2C%0D%0A%09Promise.resolve%28%7B%20hi%3A%20%27hello%27%20%7D%29%2C%0D%0A%09Promise.resolve%28%5B%5D%29%2C%0D%0A%09Promise.resolve%28null%20as%20string%29%2C%0D%0A%09Promise.resolve%281%29%2C%0D%0A%09Promise.resolve%28%27%27%29%2C%0D%0A%09Promise.resolve%28new%20Date%28%29%29%2C%0D%0A%09Promise.resolve%28%7B%7D%29%2C%20%2F%2F%20Length%20%3D%3D%2011%0D%0A%5D%29.then%28results%20%3D%3E%20%7B%0D%0A%09let%20%5B%0D%0A%09%09a%2C%20%2F%2F%20Everything%20is%20%7B%7D%20now%3F%0D%0A%09%09b%2C%0D%0A%09%09c%2C%0D%0A%09%09d%2C%0D%0A%09%09e%2C%0D%0A%09%09f%2C%0D%0A%09%09g%2C%20%0D%0A%09%09h%2C%0D%0A%09%09i%2C%0D%0A%09%09j%2C%0D%0A%09%09k%2C%20%2F%2F%20%3C%3C%20--%20Error!%0D%0A%09%09%20%20%20%2F%2F%20%22Tuple%20with%20length%2010%20cannot%20be%20assigned%20to%20tuple%20with%20length%2011%22%3F%0D%0A%09%5D%20%3D%20results%3B%0D%0A%7D%29%3B%0D%0A).

**Expected behavior:**
Tuple should be destructured with the appropriate types.

**Actual behavior:** 
Types are lost after a seemingly arbitrary tuple limit. Actual tuple length is not understood by the compiler.

**Workaround:** 
Break work up into smaller tuples below the limit and assemble them after. This will preserve type information.

**Comment by blakeembrey** [comment]
This comes from the promise definition, the maximum overload of tuples in the definition is 10. See https://github.com/Microsoft/TypeScript/blob/master/lib/lib.es6.d.ts#L5289.

**Comment by jocull** [comment]
Tuple types are apparently not inferred anywhere else. Why is that since the types are definitely known in cases such as this?

```ts
let x = [1, 'two'];
let [
	a, // string | number
	b, // string | number
] = x;
```

Code [on the playground](http://www.typescriptlang.org/play/index.html#src=let%20x%20%3D%20%5B1%2C%20%27two%27%5D%3B%0D%0Alet%20%5B%0D%0A%09a%2C%20%2F%2F%20string%20%7C%20number%0D%0A%09b%2C%20%2F%2F%20string%20%7C%20number%0D%0A%5D%20%3D%20x%3B%0D%0A).

**Comment by RyanCavanaugh** [comment]
> Tuple types are apparently not inferred anywhere else. Why is that since the types are definitely known in cases such as this?

Because we can't meaningfully distinguish these two cases:
```ts
let x = [1, 'two'];
console.log(x.indexOf(1)); // no side effects
let [
    a, // string | number
    b, // string | number
] = x;
```

```ts
let x = [1, 'two'];
x.sort(); // now what?
let [
    a, // string | number
    b, // string | number
] = x;
```

**Comment by RyanCavanaugh** [comment]
It's also not at all apparent that the fact that you wrote
```ts
let x = [1, "two"];
```
implies that you want it to be illegal to write
```ts
x[0] = "one";
```

**Comment by pelotom** [comment]
@RyanCavanaugh the fact that you can't meaningfully distinguish between them is a problem no matter what though:

```ts
// This type checks even though it shouldn't
function bad(foo: [number, string]): [number, string] {
  return foo.sort()
}
```

It seems that while representing tuples as arrays at runtime is fine and dandy, perhaps at compile time they should be kept distinguished, i.e. `[number, string]` and `(number|string)[]` should be considered mutually incompatible types.

**Comment by aluanhaddad** [comment]
> [number, string] and (number|string)[] should be considered mutually incompatible types.

The example actually typechecks because the signature of `sort` is
```ts
sort(compareFn?: (a: T, b: T) => number): this;
```

**Comment by pelotom** [comment]
I know, I'm saying that tuples should not be considered subtypes of `Array`, in which case the `sort` method wouldn't be available on them. It makes no sense to sort a tuple.
