### ISSUE TITLE
Documentation: Typo in section "this parameters in callbacks"?

### ISSUE THREAD

**Issue by ova2** [microsoft/TypeScript#11927]
In the Handbook for functions http://www.typescriptlang.org/docs/handbook/functions.html, you write to this example

```
class Handler {
    info: string;
    onClickGood = (e: Event) => { this.info = e.message }
}
```

> This works because arrow functions don’t capture **this**, so you can always pass them to something that expects **this: void**.

It's confusing. I think it should be writte as

> This works because arrow functions don’t capture **this** where they are invoked, so you can always pass them to something that expects **this: void**.

or alternative

> This works because arrow functions capture **this** where they are created, so it is safe to pass them to something that expects **this: void**.

**Comment by RyanCavanaugh** [comment]
Handbook has been rewritten
