### ISSUE TITLE
Did something change with default arguments?

### ISSUE THREAD

**Issue by Stevenic** [Microsoft/TypeScript#11939]
**TypeScript Version:**  2.0.3 / nightly (2.1.0-dev.201xxxxx)

I work on the Node version of the popular [BotBuilder](https://github.com/Microsoft/BotBuilder) library and I have numerous people complaining that my latest release has broken them. I've isolated the issue down to a default argument not being filled in but I can't figure out if it's because of a change to the TS compiler or just a misunderstanding on my part around how default arguments work.  My issue is that this code:

```
    constructor(root: lib.Library, defaultLocale = 'en') {
        this.defaultLocale(defaultLocale);
```

Is generating this code:

```
    function DefaultLocalizer(root, defaultLocale) {
        if (defaultLocale === void 0) { defaultLocale = 'en'; }
        this.localePaths = [];
        this.locales = {};
        this.defaultLocale(defaultLocale);

``` 

That means that `defaultLocale` will ONLY ever be assigned a value when the argument literally isn't passed.  In my situation `null` is being passed and isn't being converted to 'es'. I can understand why that might be the case but that's not how I thought default arguments worked and now I need to go through and re-evaluate all of my code because default arguments aren't really ensure that I always have a value.  

IMHO Default arguments are pretty much worthless without the added protection against `null`. You want to be able to reliable assume that you're going to have a value. If I'm going to have to add a second check in my code to protect against someone passing in null then what's the point?

**Comment by blakeembrey** [comment]
This is the same as always and the same as the ES spec. You need to pass `undefined` for default parameters.

**Comment by Stevenic** [comment]
Ok... Like I said. I wasn't sure if it just wasn't a misunderstanding on my part. My statement about them being of limited use without the added `null` protection still stands. The problem is code wise it makes you think that you can just assume that a value will always be provided for an argument and that really isn't the case. But I guess you can make that statement about all parameters.
