### ISSUE TITLE
Compiler should error when using an Enum before its declaration

### ISSUE THREAD

**Issue by olov** [Microsoft/TypeScript#11935]
**TypeScript Version:**  nightly (2.1.0-dev.20161028)

**Code**

``` ts
const v: Color = Color.Green;
enum Color { Red, Green, Blue }
```

which compiles to

``` js
var v = Color.Green;
var Color;
(function (Color) {
    Color[Color["Red"] = 0] = "Red";
    Color[Color["Green"] = 1] = "Green";
    Color[Color["Blue"] = 2] = "Blue";
})(Color || (Color = {}));
```

**Expected behavior:**
Error on line 1: Enum Color used before its declaration.

**Actual behavior:** 
No compiler error. Run-time error: `Uncaught TypeError: Cannot read property 'Green' of undefined`

**Comments:**
Rearranged compiler output would also be ok instead of an error:

``` js
var Color;
(function (Color) {
    Color[Color["Red"] = 0] = "Red";
    Color[Color["Green"] = 1] = "Green";
    Color[Color["Blue"] = 2] = "Blue";
})(Color || (Color = {}));
var v = Color.Green;
```

**Comment by yuit** [comment]
We will issue "used before declaration error"

**Comment by panost** [comment]
I think that const enums should be excluded by this check

**Comment by mhegazy** [comment]
> I think that const enums should be excluded from this check

sounds reasonable. please file an issue to track that change.
