### ISSUE TITLE
Export imported enum

### ISSUE THREAD

**Issue by spion** [microsoft/TypeScript#1194]
There is no way to export an enum that has already been imported under the same name

``` typescript
import m  = require('m');
import MyEnum = m.MyEnum
export enum MyEnum
```

**Comment by gautamsi** [comment]
This does not work with ES6 style import statement, error: "An Import declaration cannot have modifiers"

running with 1.5 beta 1 in VS Code.

**Comment by mhegazy** [comment]
@gautamsi if you want to use the ES6 imports/exports you  can just export directelly from the other module: 
```ts
export {MyEnum} from "m";
```

or split them into two statements:
```ts
import {MyEnum} from "m";
export {MyEnum);
```

**Comment by gautamsi** [comment]
that works!  I was using split way earlier. now this will help me streamline my module main file..

**Comment by heycalmdown** [comment]
Is there a way to re-export imported default by one line?

```typescript
// below works
import MyEnum from 'm'; // from export default MyEnum
export {MyEnum};

// not works
export import MyEnum from 'm';

// not works too
export import {MyEnum} from 'm';
```

**Comment by mhegazy** [comment]
```ts
export  { default as MyEnum } from 'm'
```

**Comment by heycalmdown** [comment]
Clear solution! Thanks.,
