### ISSUE TITLE
Missing es2017 String Padding Declaration

### ISSUE THREAD

**Issue by imcotton** [Microsoft/TypeScript#11942]
**es2017** target missing declaration for **Stage 4** String Padding [proposal](https://github.com/tc39/proposal-string-pad-start-end):
- [padStart](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padStart)
- [padEnd](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padEnd)

---

**TypeScript Version:**  2.0.6 && nightly (2.1.0-dev.20161029)

**Comment by mhegazy** [comment]
A PR would be appreciated. the changes should be added to a new `src\lib\es2017.string.d.ts`
