### ISSUE TITLE
Instantiations with type literals are not properly cached/shared

### ISSUE THREAD

**Issue by vladima** [Microsoft/TypeScript#11941]
Currently every occurrence of type literal in the source code creates new anonymous type  which breaks caching of instantiations. https://github.com/Microsoft/TypeScript/pull/11934 covers one case (for `{}` type literal) however in general the problem still exists (https://github.com/Microsoft/TypeScript/issues/10451)

**Comment by ahejlsberg** [comment]
I believe this has been fixed with the type alias instantiation caching logic that was added in #12114. Certainly the problem in #10451 is now fixed. I think we can close this one.
