### ISSUE TITLE
Reporting errors at invalid places

### ISSUE THREAD

**Issue by mnn** [Microsoft/TypeScript#11945]
**TypeScript Version:**  2.0.3

**Code**

main.ts:
```ts
import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { AppModule } from './app/app.module';

// depending on the env mode, enable prod mode or add debugging modules
if (process.env.ENV === 'build') {
  enableProdMode();
}

export function main() {
  return platformBrowserDynamic().bootstrapModule(AppModule);
}

if (document.readyState === 'complete') {
  main();
} else {
  document.addEventListener('DOMContentLoaded', main);
}
```
tsconfig.json:
```
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "strictNullChecks": true,
    "forceConsistentCasingInFileNames": true,
    "skipLibCheck": true
```
Please note I want all those checks. "Solutions" like "disable `noImplicitAny`" are not usable for me.

some errors reported (the path **is** in my source, not in some library):
```
[default] /xxx/src/main.ts:11:96
    Index signature of object type implicitly has an 'any' type.
...
[default] /xxx/src/main.ts:11:853
    Parameter 'store' implicitly has an 'any' type.
```

Reported positions (e.g. 11:96, 11:853) are useless - there is nothing there. What am I supposed to do with such badly reported errors? How can I find real position of these errors? How to fix it, so it reports correctly?

I am using this seed - https://github.com/preboot/angular2-webpack/ (I think the main file is unmodified).

It is also strange, that it reports identifiers that are not in my code. E.g.:
```
Parameter 'dependencies' implicitly has an 'any' type.
```
Because of this and high numbers in errors I am starting to suspect it reports errors either in libraries (which is strange, since I have skipLibCheck) or in concatenated result file (which is also strange, since everything is being compiled to es5). But I have no experience with TypeScript compiler or Webpack, so I can't really tell.

**Expected behavior:**
Doesn't report errors at invalid places and in libraries when library checks are turned off.

**Actual behavior:** 
Reports errors at invalid places (probably in libraries, not sure though).

**Note:**
I already asked at SO (as you suggest in issue template) and no one was able to help me, so I am asking here. Since at SO no one was able to help, I am assuming it is a bug. I would love to use TS, but it's a bit discouraging to hit a wall so soon.

**Comment by vladima** [comment]
typescript compiler never emit errors with this shape `[default] /xxx/src/main.ts:11:96` so I'd raise this question on either webpack or [awesome-ts-loader](https://github.com/s-panferov/awesome-typescript-loader) repro since it is [used](https://github.com/preboot/angular2-webpack/blob/master/webpack.config.js#L12) by this example - it might be a glitch on one of those tools when translating error locations reported by the compiler.

If I try to build this code using typescript compiler directly then position information looks right to me (you can use [--pretty](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Compiler%20Options.md) to get more context about the location of error):
```
vladima@vladima-W520:~/sources/playground/11945/angular2-webpack$ ./node_modules/.bin/tsc -p .
src/app/app.module.ts(33,13): error TS7006: Parameter 'store' implicitly has an 'any' type.
src/app/app.module.ts(36,16): error TS7006: Parameter 'store' implicitly has an 'any' type.
src/app/app.module.ts(43,19): error TS7006: Parameter 'store' implicitly has an 'any' type.
src/app/shared/api.service.spec.ts(10,42): error TS7006: Parameter 'api' implicitly has an 'any' type.
vladima@vladima-W520:~/sources/playground/11945/angular2-webpack$ ./node_modules/.bin/tsc -p . --pretty

33   hmrOnInit(store) {
               ~~~~~

src/app/app.module.ts(33,13): error TS7006: Parameter 'store' implicitly has an 'any' type.


36   hmrOnDestroy(store) {
                  ~~~~~

src/app/app.module.ts(36,16): error TS7006: Parameter 'store' implicitly has an 'any' type.


43   hmrAfterDestroy(store) {
                     ~~~~~

src/app/app.module.ts(43,19): error TS7006: Parameter 'store' implicitly has an 'any' type.


10   it('should ...', inject([ApiService], (api) => {
                                            ~~~

src/app/shared/api.service.spec.ts(10,42): error TS7006: Parameter 'api' implicitly has an 'any' type.

vladima@vladima-W520:~/sources/playground/11945/angular2-webpack$ 


```

**Comment by mnn** [comment]
All errors you posted are fixed in our code, yet webpack dev server is reporting 19 more errors at very high positions in main file :-(. You are right, I tried it now and TypeScript compiler compiled it just fine without any errors.

Thank you very much for your response. I will try my luck over at the loader and possibly with webpack guys.
