### ISSUE TITLE
Unable to pass another react component as prop with strictNullChecks

### ISSUE THREAD

**Issue by asvetliakov** [Microsoft/TypeScript#11944]
I'm not sure where to file issue - here or in DT repo, but i believe it's more TS issue rather than typings issue, since it's valid to return null in StatelessComponent definition

**TypeScript Version:**  2.0.6
`@types/react": "^0.14.43"`
`strictNullChecks: true`

**Code**

``` ts
import * as React from "react";
interface Props {
   Component: React.ComponentClass<any> | React.StatelessComponent<any>
}

class MyComponent extends React.Component<Props, {}> {
   render() {
     const Component = this.props.Component;
     return <Component />;
  }
}

```

**Expected behavior:**
Compiles fine

**Actual behavior:** 

```
'JSX element type 'ReactElement<any> | null' is not a constructor function for JSX elements.
  Type 'null' is not assignable to type 'ElementClass'.'
```

**Comment by RyanCavanaugh** [comment]
Duplicate #11955 - `null` will be an allowed JSX element type
