### ISSUE TITLE
Better support of typings generation

### ISSUE THREAD

**Issue by pietrzm** [Microsoft/TypeScript#11952]
**TypeScript Version:**  2.0.3 / nightly (2.1.0-dev.201xxxxx)
Better support of typings generation is needed.

**Expected behavior:**
Developing a library in TypeScript needs to have a way of generating its typings, which are instantly ready to use for customer.

There should be a way to generate typings with only public members of a library, based on given entry point.

**Actual behavior:** 
Currently tsc with --declaration flag turned on will generate declaration files for every .ts file, while preferred way of distributing typings is via single .d.ts file where only public members are only available.

**Comment by kitsonk** [comment]
> while preferred way of distributing typings is via single .d.ts file

What makes you say that?  Global ambient definitions have caused a huge amount of problems in consuming packages.  That is why the UMD definitions were introduced.  I don't think it is preferred.  If you are distributing modular code, the definition files should be modular too.

> only public members are only available

Omitting these are dangerous.  What prevents someone from downstream running into a name conflict with a `private` or `protected` property on a class?  Even if you use the convention of `_foo`, if it is missing from the interfaces, you can quite easily have someone downstream run into issues with those missing.

**Comment by mhegazy** [comment]
>  while preferred way of distributing typings is via single .d.ts

I agree with @kitsonk. you should not put all declarations in a single file unless you are writing a global package. for modules, you should leave them the way they are generated, and set your `"types"` in `package.json` to point to your entry point `.d.ts`.

**Comment by mhegazy** [comment]
I would like to know what are the issues you are running into with the current implementation of `--declaration`?
