### ISSUE TITLE
Completion list should be aligned to the completion span

### ISSUE THREAD

**Issue by Peter-Juhasz** [Microsoft/TypeScript#1195]
Completion list should not slide (and repositioned with every keystroke) with the location of the caret:
![completion-alignment](https://cloud.githubusercontent.com/assets/9047283/5095297/ccec9be2-6f68-11e4-9efc-2f538d5a7251.png)

It should be aligned to the applicable completion span:
![completion-alignment-correct](https://cloud.githubusercontent.com/assets/9047283/5095352/4e5eec0c-6f69-11e4-9058-43260ecb2168.png)
like in C#, VB or plain JavaScript, or every other language service

**Comment by mhegazy** [comment]
I see this working as expected in VS2015 CTP6.
