### ISSUE TITLE
Suggestion: Discriminate type from constructor

### ISSUE THREAD

**Issue by osi-oswald** [microsoft/TypeScript#11953]
**TypeScript Version:**  2.0

**Code**
```ts
function foo<T>(arg: T): T {
    switch (arg.constructor) {
        case Object:
            return {}; // compiler ERROR
        case Array:
            return new Array(arg.length); // 2 compiler ERROR's
        case Date:
            return new Date(arg.getTime()); // 2 compiler ERROR's
        case RegExp:
            return new RegExp(arg.source, arg.flags); // 3 compiler ERROR's
    }
}
```

**Expected behavior:**
Typescript should be able to discriminate the type based on the constructor property

**Actual behavior:** 
Does not compile without errors

**Comment by kitsonk** [comment]
What would you propose the run-time emit for this to be?

**Comment by osi-oswald** [comment]
I do not expect a change in the run-time emit. 

In the [Playground](http://www.typescriptlang.org/play/#src=function%20foo%3CT%3E(arg%3A%20T)%3A%20T%20%7B%0D%0A%20%20%20%20switch%20(arg.constructor)%20%7B%0D%0A%20%20%20%20%20%20%20%20case%20Object%3A%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20%7B%7D%3B%0D%0A%20%20%20%20%20%20%20%20case%20Array%3A%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20new%20Array(arg.length)%3B%0D%0A%20%20%20%20%20%20%20%20case%20Date%3A%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20new%20Date(arg.getTime())%3B%0D%0A%20%20%20%20%20%20%20%20case%20RegExp%3A%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20new%20RegExp(arg.source%2C%20arg.flags)%3B%0D%0A%20%20%20%20%7D%0D%0A%7D) it emits just fine, the issue is the compiler not recognizing the proper type based on the constructor property.

It should also work for custom types:
```TypeScript
class Person {
    name: string;
}

var something: Object;
if (something.constructor === Person) {
    console.log('hello ' + something.name);  // <-- currently a compiler ERROR
}
```

**Comment by aluanhaddad** [comment]
I'm curious what the use case is for this over `instanceof`.

**Comment by osi-oswald** [comment]
@aluanhaddad 
- `instanceof` can not be used in a `switch` statement

**Comment by mhegazy** [comment]
Even if narrowing on constructor assignment was possible it would not solve the issue in hte OP.

`{}` is not assignable to `T` even if `T` was narrowed. it would not be safe to do this on a generic type parameter, consider `foo({a: 1}).a`. this fail at run time in the above example. I would recommend for cases like these to use union types instead:

```ts
function foo(arg: any[]): any[];
function foo(arg: Date): Date;
function foo(arg: RegExp): RegExp;
function foo(arg: any): {};
function foo(arg: any): any[] | Date | RegExp | {} {
    switch (arg.constructor) {
        case Object:
            return {}; // compiler ERROR
        case Array:
            return new Array(arg.length); // 2 compiler ERROR's
        case Date:
            return new Date(arg.getTime()); // 2 compiler ERROR's
        case RegExp:
            return new RegExp(arg.source, arg.flags); // 3 compiler ERROR's
    }
}
```

As for narrowing on constructor, this would be gated on https://github.com/Microsoft/TypeScript/issues/3841. and i would add this to that issue as a follow up suggestion.

**Comment by osi-oswald** [comment]
@mhegazy 
I think that is fine with me! :+1:
