### ISSUE TITLE
Peek Definition in custom location

### ISSUE THREAD

**Issue by waderyan** [Microsoft/TypeScript#11959]
_From @vvatikiotis on October 21, 2016 6:48_

- VSCode Version: 1.6.1
- OS Version: OS X 10.11.6

Is it possible to configure VSS, (via `jsoncifg.json` maybe?) to Peek Definition inside custom project locations? For instance:

```
import { read, update, getTokenFromState } from 'utils/xhr'
```

Currently, I'm unable to Peek Definition in location `utils/xhr`, which specifies a project-wise absolute location. This works for relative locations.

Thanks

_Copied from original issue: Microsoft/vscode#14134_

**Comment by waderyan** [comment]
_From @roblourens on October 21, 2016 18:7_

How does it resolve an import path like that? Do you get intellisense for those imports?

**Comment by waderyan** [comment]
_From @vvatikiotis on October 23, 2016 10:56_

* Paths like this are located under project-root/src. So, ideally, I'd like to be able to specify `src/` (or any other directory under project-root) as a "resolve-root", so anything under it would resolve correctly.
* I do get intellisense for these imports.

**Comment by waderyan** [comment]
_From @vvatikiotis on October 23, 2016 17:19_

Yes

**Comment by waderyan** [comment]
@bowdenk7 do you have a feature request like this on your roadmap? I have not seen it before.

**Comment by mhegazy** [comment]
The config file should support `baseUrl` and `paths` propeoteis to allow you to map modules to thier location.. for instance:

```ts
"compilerOptions": {
   "baseUrl": "./modules"
}
```

Tells the system to look for `utils/xhr` under `./modules/utils/xhr`

similarally:

```ts
"compilerOptions": {
   "baseUrl": "./modules",
   "paths": {
        "utils/xhr" : [ "xhr"]
   }
}
```

Tells the system to look for `utils/xhr` under `./modules/xhr`


you can find more about this in http://www.typescriptlang.org/docs/handbook/module-resolution.html#additional-module-resolution-flags

**Comment by vvatikiotis** [comment]
Thanks for the reply, this resolves my issue, specifying `baseUrl` inside `compilerOptions` in jsconfig.json` allows me to Peek inside said imports. 

One minor glitch: in `jsconfig.json`, VSS green underlines the `baseUrl` property; the showHover command shows the message "Property baseUrl is not allowed".

**Comment by mhegazy** [comment]
we should add this to https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/jsconfig.json
