### ISSUE TITLE
StatelessFunctionalComponenet that probably returns null cannot be instanciated in JSX

### ISSUE THREAD

**Issue by alisabzevari** [Microsoft/TypeScript#11955]
**TypeScript Version:**  2.1.0-dev.20161019

**Code**

```ts
import * as React from 'react';
import { render } from 'react-dom';

interface FooProps extends React.Props<null> {
  prop1?: boolean;
}

const Foo = ({ prop1 }: FooProps) => {
  if (prop1) {
    return null;
  }
  return (
    <div>Hello!</div>
  );
}

render(<Foo />, null);
```

**Expected behavior:**

This is a valid JSX code. It is true that the return value of the SFC can be null but there is no way to check for its value in the code!

**Actual behavior:** 

Compiler complains with these errors:
```
error TS2605: JSX element type 'Element | null' is not a constructor function for JSX elements.
  Type 'null' is not assignable to type 'ElementClass'.
```

**Comment by alitaheri** [comment]
This is annoying. I worked abound it by asserting that `null` is not `null`: 😱 

```ts
const Foo = ({ prop1 }: FooProps) => {
  if (prop1) {
    return null!; // <= never is assignable to anything, so the return type will be Element
  }
  return (
    <div>Hello!</div>
  );
}
```

**Comment by alisabzevari** [comment]
@alitaheri Good idea. I just decided to remove `strictNullChecks`. But I will go with your workaround to fix the problem.

**Comment by RyanCavanaugh** [comment]
@yuit we should allow `null` as a return type for JSX functions

**Comment by RyanCavanaugh** [comment]
@yuit as well as null constructor functions

**Comment by tamlyn** [comment]
Can someone explain what is happening in @alitaheri's workaround? I've never seen the `null!` syntax before and I can't find any documentation on it.

**Comment by alitaheri** [comment]
@tamlyn [This](https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#non-null-assertion-operator) is where you can find information on it.

**Comment by yuit** [comment]
This is the same as #11566

**Comment by tkrotoff** [comment]
This is not fixed yet.
React definition from DefinitelyTyped still needs to be updated since the [original PR]( https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14284) [was reverted](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14476) due to regressions with TypeScript < 2.3
