### ISSUE TITLE
Intellisense not working at all

### ISSUE THREAD

**Issue by waderyan** [Microsoft/TypeScript#11958]
_From @joshfttb on October 23, 2016 18:25_

I'm really trying to give vscode a go, but after two days I'm unable to make intellisense work.

I've  tried configuring my project according to these instrustions:

https://code.visualstudio.com/Docs/languages/javascript
https://code.visualstudio.com/Docs/runtimes/nodejs

I've completely uninstalled and re-installed both vscode and typings. I've tried removing the files argument from my jsconfig, as well as re-creating it completely. I've tried installing typings locally. I've also tried installing and running typescript from my machine instead of vscode's built-in typescript on the off chance that would help. No luck.

If anyone could provide assistance I would greatly appreciate it.

I'm running on OSX (or is is MacOS) Sierra with brew installed.
<img width="427" alt="screen shot 2016-10-23 at 14 06 04" src="https://cloud.githubusercontent.com/assets/2595454/19628461/22bade28-992c-11e6-82c5-602240873b2d.png">
<img width="1440" alt="screen shot 2016-10-23 at 12 41 46" src="https://cloud.githubusercontent.com/assets/2595454/19628462/31d9e67e-992c-11e6-89f1-1f0277fa8c2b.png">

<img width="954" alt="screen shot 2016-10-23 at 14 24 51" src="https://cloud.githubusercontent.com/assets/2595454/19628476/82696e8e-992c-11e6-8441-60f8632afad3.png">
<img width="958" alt="screen shot 2016-10-23 at 14 24 58" src="https://cloud.githubusercontent.com/assets/2595454/19628477/8269fd18-992c-11e6-929f-56ab8a5eea8f.png">

_Copied from original issue: Microsoft/vscode#14236_

**Comment by waderyan** [comment]
_From @roblourens on October 24, 2016 1:34_

Is there an error in that file? The problems pane shows a syntax error, and it looks like the syntax coloring is screwed up as a result, which would prevent it from understanding the file well enough to give you intellisense.

**Comment by waderyan** [comment]
_From @joshfttb on October 24, 2016 3:9_

@roblourens if you look at the pane you can see those are eslint errors. I'm not sure if the coloring is screwed up. I'm using solarized as a theme and its always looked that way for me.

**Comment by waderyan** [comment]
_From @joshfttb on October 24, 2016 3:10_

But fixing the errors does not resolve the problem, nor does typing in another file.

**Comment by waderyan** [comment]
_From @roblourens on October 24, 2016 3:15_

Oh yeah I think its the eslint error in the line after, nvm. Sending this to @waderyan but I think `"files"` in your jsconfig is supposed to be a list of files, not a folder. Or you can leave it out to include all files under the folder. https://code.visualstudio.com/docs/languages/jsconfig

**Comment by waderyan** [comment]
_From @joshfttb on October 24, 2016 3:23_

@roblourens, I know it's set to a folder in this screenshot, but I've also tried gobs, omitting it entirely, and using excludes instead. Still no success.

**Comment by waderyan** [comment]
@joshfttb thank you for opening this issue. I wrote those docs so I definitely want to help you out here :)

Can you share your workspace so I can run it on my machine?

**Comment by waderyan** [comment]
_From @joshfttb on October 24, 2016 23:14_

@waderyan check out branch vscode in the repo I just added you to.

Thanks for the quick response!

**Comment by waderyan** [comment]
_From @joshfttb on October 24, 2016 23:24_

Now  I just tried with a fresh project and things are working as expected. I'm not sure why they're not working on my project.

<img width="1440" alt="screen shot 2016-10-24 at 19 23 14" src="https://cloud.githubusercontent.com/assets/2595454/19667535/6d43faa8-9a1f-11e6-9e93-45daf62c42f0.png">

**Comment by waderyan** [comment]
It could be your `jsconfig.json`. Can you share that with me and I'll look for any common errors?

**Comment by waderyan** [comment]
_From @joshfttb on October 25, 2016 0:4_

@waderyan it's in the vscode branch of the repo

On another interesting note as far as debugging this issue.. after I got the minimal repo working I went and added files from my project back in. Everything worked until I ran `npm install` in my server folder. Deleted node_modules from the server folder. Intellisense worked again.

Hm...

Deleted node_modules from the original project. Intellisense worked in the original project. Wierd... 

Not sure what steps to take next.

**Comment by waderyan** [comment]
_From @joshfttb on October 25, 2016 0:14_

With `server/node_modules` (check out the file list on the left):
<img width="1440" alt="screen shot 2016-10-24 at 20 09 51" src="https://cloud.githubusercontent.com/assets/2595454/19668437/db1cc16c-9a25-11e6-856f-1a2fee04715b.png">

Without `server/node_modules`:
<img width="1440" alt="screen shot 2016-10-24 at 19 58 23" src="https://cloud.githubusercontent.com/assets/2595454/19668463/0c8fb97a-9a26-11e6-94d3-fbcf0903f924.png">

`npm List` in `/server`:


[npm packages list.pdf](https://github.com/Microsoft/vscode/files/549324/npm.packages.list.pdf)

**Comment by waderyan** [comment]
_From @joshfttb on October 25, 2016 1:44_

More debugging: tried removing apollo from npm because there were a bunch of type declarations in it's npm depedencies.

Opened up developer tools, saw an error, not sure if it's related, but took it to mean that maybe it's indexing node_modules:
<img width="807" alt="screen shot 2016-10-24 at 21 29 05" src="https://cloud.githubusercontent.com/assets/2595454/19670008/de3bea4c-9a31-11e6-99dd-72a394b9a1c9.png">

Specified "server/node_modules" in the excludes. Intellisense worked!
<img width="1440" alt="screen shot 2016-10-24 at 21 26 12" src="https://cloud.githubusercontent.com/assets/2595454/19670020/072578f6-9a32-11e6-9476-a36baa7808d2.png">

Tried using gobs with "include" instead of "files"as per: https://www.typescriptlang.org/docs/handbook/tsconfig-json.html, can't get that to work:
<img width="1440" alt="screen shot 2016-10-24 at 21 33 57" src="https://cloud.githubusercontent.com/assets/2595454/19670037/1c1d13fe-9a32-11e6-801e-1c75f9c7cb0f.png">

Re-installed apollo, verified that intellisense still works with the excludes set.

So it seems there needs to be a gob specified in the default jsconfig to exclude nested node_modules for some reason. I'm not sure if intellisense not working when node_modules is included is intended/necessary behavior or a bug. If intended it should be documented

Also @waderyan , based on the docs I just posted it looks like "files" does not take gobs or wildcards. So it would seem that this line is the vscode docs is misleading. This might explain why I saw someone else (can't remember where, sorry!) talk about not being able to get intellisense working with "files", but be able to get it working with "exclude":
<img width="688" alt="screen shot 2016-10-24 at 21 42 06" src="https://cloud.githubusercontent.com/assets/2595454/19670130/e5b50186-9a32-11e6-9bd9-836d5b2ddacd.png">

Finally, I would like to figure out how to get this to work with specified folders (server/src) instead of the excludes.

**Comment by waderyan** [comment]
_From @joshfttb on October 29, 2016 1:55_

I wanted to bump this since It seems like it's a problem that's not going to be specific to my use.

**Comment by waderyan** [comment]
Thanks @joshfttb. I, embarrassingly, ran into a similar issue this morning with a demo. Escalating to the language service team (TypeScript) to get some help.

**Comment by waderyan** [comment]
@mhegazy and @bowdenk7 can you take a look at this? I could use your help in guiding OP in reproducing and diagnosing. Closely related to https://github.com/Microsoft/TypeScript/issues/10735 I believe.

**Comment by bowdenk7** [comment]
@waderyan do you have src that we can repro with?

**Comment by waderyan** [comment]
@joshfttb can you share your test repo with @bowdenk7?

**Comment by joshfttb** [comment]
@bowdenk7 try the jsconfig branch of the repo I'm sending you. Go into server/src and try to edit a js file.

**Comment by mhegazy** [comment]
@bowdenk7 did you figure out what was going on?

**Comment by mhegazy** [comment]
This looks stale by now. closing. please reopen if you are still seeing issues on TS 2.5
