### ISSUE TITLE
Colorize the usages of interfaces everywhere

### ISSUE THREAD

**Issue by Peter-Juhasz** [microsoft/TypeScript#1197]
Colorize the usages of interfaces as well as classes are:
![typescript-interfaces](https://cloud.githubusercontent.com/assets/9047283/5096443/74ec2188-6f72-11e4-836d-e5647a3900f2.PNG)

Greeter is colorized, because it is a class; but HTMLElement and Date are not - they are interfaces.

**Comment by RyanCavanaugh** [comment]
This is implemented by semantic colorization now
