### ISSUE TITLE
Generator with Array Spread

### ISSUE THREAD

**Issue by johnlindquist** [Microsoft/TypeScript#11970]
`Version 2.1.0-dev.20161031`

```
const g = function*(){
    yield 1;
}

console.log([...g()]);
```

Compiles to the following which throws an error (treating the generator as an array, not an iterable):
```
var g = function* () {
    yield 1;
};
console.log(g().slice());
//# sourceMappingURL=build.js.map
```

Possible solution using `Array.from`:
```
var g = function* () {
    yield 1;
};
console.log(Array.from(g()).slice());
//# sourceMappingURL=build.js.map
```

**Comment by aluanhaddad** [comment]
With `"target": "es5"` this is the intentional. Arguably it is undesirable and there are a number of issues relating to that and to down level generate or support in general.
