### ISSUE TITLE
Throw an Unexpected token when load local json file

### ISSUE THREAD

**Issue by kiruto** [Microsoft/TypeScript#11984]
**TypeScript Version:**  2.0.3

**Code**
I have a config file written with json, like:
```json
{
  "example": "example"
}
```

And read this file in my typescript like:
```ts
var events = require('json!./example_file.json');
```

**Expected behavior:**
When I remove the double quotes from the key, the script will run correctly. 
But how can I read the JSON file with standard JSON format? I don't want remove the quotes.

Thanks!

**Actual behavior:** 
```
index.html:18 Error: (SystemJS) Unexpected token :
    example_file.json:2
      "example": "example"
               ^
    SyntaxError: Unexpected token :
        at Object.exports.runInThisContext (vm.js:76:16)
```

**Comment by kitsonk** [comment]
Why do you believe this is a TypeScript issue?  TypeScript does not do the loading at run time.  It appears to be a SystemJS configuration issue.
