### ISSUE TITLE
Proposal: Allow semicolon in ambient context

### ISSUE THREAD

**Issue by mihailik** [Microsoft/TypeScript#11987]
Sometimes people stick semicolons after declarations. Why not be more accomodating for these trivial benign errors, in spirit of JavaScript in general?

**TypeScript Version:**  2.0.6

```ts
declare namespace ns {

  interface A {
  }  ;   //   <--  look at this semicolon

}
```

**Expected behavior:**
Compile without error

**Actual behavior:** 
`error TS1036: Statements are not allowed in ambient contexts.`

**Comment by mhegazy** [comment]
I am inclined to say no. there are other things that are harmless and not allowed either, for instance debugger, expression statements, `"use strict"` prologue, etc.. so not sure why a semicolon be any different, it takes a run through the compiler to catch these and fix them. and in general I do not think ppl should distribute their .d.ts files before running them through the compiler once; there are other issues that would be hidden there if not.

**Comment by mihailik** [comment]
Just to highlight a wider use case here: ambient context is not only `.d.ts` (that are indeed tend to be updated rarely and carefully).

Consider this pattern:

```typescript

declare namespace myComplexProcessing {
  type Options = {
    accounts: Account[];
    orders: Order[];
    highlightAccount?: Account;
  }

  type Result = {
    totalNetPositive: number;
    totalNetNegative: number;
  }
}

function myComplexProcessing(options: myComplexProcessing.Options): myComplexProcessing.Result {

  // . . .

}
```

Ambient context can be helpful to define a shape of object, whilst introducing a namespace scope to avoid clashes. Making it an ambient namespace ensures we only have declarations there, no code (as intended).

**Comment by aluanhaddad** [comment]
Trailing commas are part of the ECMAScript specification. Regardless, I do not see the advantage of making random semicolons valid. Also, note that we _can_ have a semicolon terminating an ambient type alias binding.
```ts
type T = {};
```
