### ISSUE TITLE
document.evaluate: resolver and result are allowed null

### ISSUE THREAD

**Issue by kalbasit** [Microsoft/TypeScript#11981]
**TypeScript Version:**  2.0.6

**Code**

```ts
// copied from http://stackoverflow.com/a/14284815
function getElementByXpath(xpath: string) {
    return document.evaluate(xpath, document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue;
}
```

**Expected behavior:**
The code should compile

**Actual behavior:** 
```
$ tsc --strictNullChecks /tmp/find_xpath.ts
/tmp/find_xpath.ts(3,47): error TS2345: Argument of type 'null' is not assignable to parameter of type 'XPathNSResolver'
```

According to [MSDN](https://developer.mozilla.org/en-US/docs/Web/API/Document/evaluate), nulls should be allowed for the `namespaceResolver` and the `result` arguments.

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.
