### ISSUE TITLE
QuickInfo is not consistent for symbols that exist in type and value spaces

### ISSUE THREAD

**Issue by mhegazy** [microsoft/TypeScript#1199]
Quick info is inconsistently showing different spaces occupied by a symbol. in the value position, the info is incorrectly the value part of the symbol. but for type position, we see both.

![quickinfo](https://cloud.githubusercontent.com/assets/8000722/5097728/57917a4c-6f32-11e4-8cb5-6111562b13fd.png)

**Comment by andy-ms** [comment]
@mhegazy Which way should we go -- show both meanings when it's used as a value, or show only the type meaning when it's used as a type?

**Comment by mhegazy** [comment]
I think showing the declaration meaning based on the position is the correct solution here. this way the tools accurately represent how the compiler behaves.

**Comment by andy-ms** [comment]
@DanielRosenwasser The behavior is different now, do you think it looks good?

```
var x = Date();
```
```
const Date: DateConstructor
() => string
Enables basic storage and retrieval of dates and times.
```

And:
```
var d: Date;
```
```
interface Date
Enables basic storage and retrieval of dates and times.
```

**Comment by Andarist** [comment]
@RyanCavanaugh this can be closed, the quick info behaves differently nowadays and is close to what has been mentioned here as the expected result
> I think showing the declaration meaning based on the position is the correct solution here. this way the tools accurately represent how the compiler behaves.
