### ISSUE TITLE
No error for compound assignments for narrowed auto-types 

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#11996]
```ts
let x;

x = () => 42;

// The '+=' operator is allowed here even though 'x = x + 100' is not.
x += 100;

// 'x' is still considered a '() => number'
x;
```

In the above example, I expect that at the very least, `x += 100` would not be allowed.

As a bonus, the last occurrence of `x` should be a `string`.

![image](https://cloud.githubusercontent.com/assets/972891/19938405/0dee4de6-a0e2-11e6-987e-6e5516a82377.png)

**Comment by ahejlsberg** [comment]
I can't reproduce this with the current master.

**Comment by DanielRosenwasser** [comment]
Sorry, my `jake LKG; npm install -g` didn't work correctly because the first command failed. This is indeed working correctly.
