### ISSUE TITLE
Using Discriminating Union removes previous null check

### ISSUE THREAD

**Issue by MikeyBurkman** [microsoft/TypeScript#11991]
(Hopefully not a duplicate this time)

**TypeScript Version:**  2.1.0-dev.20161102 (code run from command line)

**Code**

```ts
interface Base {
    s?: string;
}

interface Foo extends Base {
    kind: 'foo';
}

interface Bar extends Base {
    kind: 'bar';
}

function test(x: Foo|Bar) {
    if (!x.s) {
        throw new Error();
    }

    const s = x.s;

    const length1 = x.s.length; // Valid, as expected

    if (x.kind === 'foo') {
        const length2 = x.s.length; // Error -- x.s is back to string|undefined
    }

    const length3 = x.s.length; // Error - Type of x.s is back to string|undefined

    const length4 = s.length; // Valid, as expected
}
```

**Expected behavior:**
I would expect the null check at the top of the function to apply for the entire function.

**Actual behavior:** 
The type of `x.s` is reset back to `string|undefined` as soon as a discriminated union check is made. This even applies outside of the block where the discriminated union check applies.

EDIT: The same behavior happens if `s?: string` is a property of both Foo and Bar, and there is no Base interface.

**Comment by RyanCavanaugh** [comment]
Duplicate #31495
