### ISSUE TITLE
Report issue suggestion

### ISSUE THREAD

**Issue by normalser** [microsoft/TypeScript#12009]
Just an idea (which might not make sense to mix it with compiler) that it would be nice (being in Terminal) to be able to type `tsc -i` or `tsc --issue` which could open github new issue with all the details of TS version populated (not sure if `node` version and `os` info is important for you but would be easy to add).
Kind of similar how `vscode` allows to click "Report issue" and it opens github with template and all variables populated.

**Comment by RyanCavanaugh** [comment]
As you can tell by the nearly three year lag time here, an easier way to create more issues is the last thing we need 🙃
