### ISSUE TITLE
Format removes a space in content in tsx

### ISSUE THREAD

**Issue by waderyan** [Microsoft/TypeScript#12001]
_From @octref on November 1, 2016 7:45_

- VSCode Version: 1.7
- OS Version: OS X 10.11.6

Before formatting

```tsx
import * as React from "react";

export interface HelloProps { compiler: string; framework: string; }

export class Hello extends React.Component<HelloProps, {}> {
    render() {
        return <h1>Hello from {this.props.compiler} and {this.props.framework}!</h1>;
    }
}
```

After Document Format with 2 spaces:

```tsx
import * as React from "react";

export interface HelloProps { compiler: string; framework: string; }

export class Hello extends React.Component<HelloProps, {}> {
  render() {
    return <h1>Hello from {this.props.compiler}and {this.props.framework}!</h1>;
  }
}
```

The space between `} and` is gone after formatting.

_Copied from original issue: Microsoft/vscode#14793_

**Comment by sandersn** [comment]
@RyanCavanaugh could this be related to your fix for the mysterious JSX-formatting-test failures?

**Comment by mhegazy** [comment]
Should be working correctly in latest drop of TypeSript (TS 2.1.4 or later). VSCode ships with an older version of TypeScript. Please see [Using Newer TypeScript Versions](https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions) documentation for more details on updating your VSCode to use a different version of TypeScript.
