### ISSUE TITLE
Cancellable Promise sample no longer works

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#12006]
**TypeScript Version:**  nightly 

    "typescript": "2.1.0-dev.20161102",

**Code**

The following errors
```ts
/**
 * https://github.com/facebook/react/issues/5465#issuecomment-157888325
 */
const makeCancelable = <T>(promise:Promise<T>) => {
  let hasCanceled_ = false;

  const wrappedPromise = new Promise((resolve: any, reject) => {
    promise.then((val) =>
      hasCanceled_ ? reject({isCanceled: true}) : resolve(val)
    );
    promise.catch((error) =>
      hasCanceled_ ? reject({isCanceled: true}) : reject(error) // ERROR
    );
  });

  return {
    promise: wrappedPromise as Promise<T>,
    cancel() {
      hasCanceled_ = true;
    },
  };
};
```
`/Users/syedb/REPOS/alm/src/common/utils.ts:572 Argument of type '(error: any) => void' is not assignable to parameter of type '(reason: any) => T | Promise<T>'.
  Type 'void' is not assignable to type 'T | Promise<T>'.` 

**Expected behavior:**
Compiles
**Actual behavior:** 
Errors

Used to work with   "typescript": "2.1.0-dev.20161011",

:rose:

**Comment by HerringtonDarkholme** [comment]
Can you remove the `any` annotation on resolve, or annotate `reject` as `any`? 

It compiles for me in nightly. The `Promise` in this code probably has wrong overloading.

**Comment by basarat** [comment]
Thanks. I wrote alm before the `lib` option so had to copy stuff around. Using it now :) :rose:
