### ISSUE TITLE
jsdoc typedef (strange behaviour)

### ISSUE THREAD

**Issue by waderyan** [Microsoft/TypeScript#12004]
_From @udarkness on October 28, 2016 13:42_

I cannot autocomplete a property of an object after its first use
- VSCode Version: 1.6.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:
1. Write this code in a Js file:

```
/**
 * @typedef {Object} My
 * @property {boolean} yes
 */

/**
 * @param {My} my
 */
function a(my) {
    my.yes
}
/**
 * @param {My} my
 */
function b(my) {
    my.
}
```
1. try to autocomplete in the function a. Works fine, as expected
2. try to autocomplete in the function b. It doesn't work at all

_Copied from original issue: Microsoft/vscode#14664_

**Comment by waderyan** [comment]
@udarkness thank you for opening this issue. I have reproduced this using the latest Insider build. Migrating to the JavaScript language service repo (TypeScript).

**Comment by rossipedia** [comment]
I'm currently running into this issue. Is there an expected version for this fix?

**Comment by mhegazy** [comment]
Should be working correctly in latest drop of TypeSript (`typescript@next`). VSCode ships with an older version of TypeScript. Please see [Using Newer TypeScript Versions](https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions) documentation for more details on updating your VSCode to use a different version of TypeScript.
