### ISSUE TITLE
rootDir should be an array

### ISSUE THREAD

**Issue by bertolo1988** [Microsoft/TypeScript#12018]
It should be possible to define several source paths so we can organize projects as we wish.
`compilerOptions.rootDir` should expect `[String]` instead of `String`.

This would solve [my other issue](https://github.com/TypeStrong/ts-node/issues/233) really fast.

**Comment by aluanhaddad** [comment]
There is already such an option, aptly named `rootDirs`.

**Comment by bertolo1988** [comment]
thanks alot

**Comment by RyanCavanaugh** [comment]
Thanks as usual @aluanhaddad 😄

**Comment by mhegazy** [comment]
Please note that `rootDir` and `rootDirs` are not the same thing. unless you really need the module resolution for virtual directories (http://www.typescriptlang.org/docs/handbook/module-resolution.html#virtual-directories-with-rootdirs) do not use `rootDirs`.

**Comment by alexeagle** [comment]
They are also not the same thing in the other sense: `rootDirs` does not influence the layout of files in the `outDir1

**Comment by mhegazy** [comment]
> They are also not the same thing in the other sense: rootDirs does not influence the layout of files in the outDir

`rootDirs`, as the rest of the module resolution flags, are just to inform the compiler of actions taken outside its operation. for instance a build tool that copies files, or a module loader that will always load from a central location, or that supports some sort of path mappings.
The intention here is not to "re-organize" your code. 

> So really the original issue wasn't resolved here...

It is not clear what the OP is about really.
