### ISSUE TITLE
request: Turn off required properties check in TSX context

### ISSUE THREAD

**Issue by vvakame** [Microsoft/TypeScript#12016]
I want to turn off required properties check in TSX context with using skate.js http://skate.js.org/
And, I don't want to turn of type checking about properties.

cc/ @bradleyayers do you interested in this issue?

**TypeScript Version:**  2.0.6

**Code**

Reproduce code is here.
https://gist.github.com/vvakame/e7a230fa558763e225b58d57b459f64d

summary

```ts
declare global {
    namespace JSX {
        interface ElementAttributesProperty {
            '': any;
        }
    }
}
```

```ts
declare module "skatejs" {
  export class Component extends HTMLElement {
  }
}
```

```ts
const ComponentA = skate.define("x-component-a", class ComponentA extends skate.Component {
    myCounter = 0;

    ...
}

skate.define("x-main", class Main extends skate.Component {
    render(elem: this): JSX.Element {
        return (
            // tsc raise a lot of errors!
            // error TS2324: Property 'ATTRIBUTE_NODE' is missing in type 'ComponentA'.
            // error TS2324: Property 'outerHTML' is missing in type 'ComponentA'.
            // ...
            // but I want a type checking...
            <ComponentA myCounter={-3}></ComponentA>
        );
    }

    ...
});
```

other information.

from [src/compiler/checker.ts](https://github.com/Microsoft/TypeScript/blob/master/src/compiler/checker.ts)

```
        /// e.g. "props" for React.d.ts,
        /// or 'undefined' if ElementAttributesProperty doesn't exist (which means all
        ///     non-intrinsic elements' attributes type is 'any'),
        /// or '' if it has 0 properties (which means every
        ///     non-intrinsic elements' attributes type is the element instance type)
        function getJsxElementPropertiesName() {
```

I want to change `targetAttributesType && !sawSpreadedAny` to something like... `targetAttributesType && !sawSpreadedAny && !suppressRequiredPropertyCheck`.

```
        function checkJsxOpeningLikeElement(node: JsxOpeningLikeElement) {

            ...

            // Check that all required properties have been provided. If an 'any'
            // was spreaded in, though, assume that it provided all required properties
            if (targetAttributesType && !sawSpreadedAny) {
                const targetProperties = getPropertiesOfType(targetAttributesType);
                for (let i = 0; i < targetProperties.length; i++) {
                    if (!(targetProperties[i].flags & SymbolFlags.Optional) &&
                        !nameTable[targetProperties[i].name]) {

                        error(node, Diagnostics.Property_0_is_missing_in_type_1, targetProperties[i].name, typeToString(targetAttributesType));
                    }
                }
            }
```

**Expected behavior:**

We can compile my code.

**Actual behavior:** 

tsc raise a lot of errors.

**Comment by thorn0** [comment]
Duplicate of #7004.

**Comment by aluanhaddad** [comment]
@thorn0 Is #7004 still relevant since we are now free to annotate class members as optional.

**Comment by thorn0** [comment]
Yes, it's still relevant. It's exactly the same issue that is described here.

If I mark members as optional, I'll have to add null checks for them everywhere, even for methods. This will not do.

**Comment by vvakame** [comment]
I missed that issue, thank you!

**Comment by aluanhaddad** [comment]
@thorn0 Sorry, I am not very experienced with React/JSX. thanks for clarifying.

**Comment by thorn0** [comment]
@aluanhaddad  JSX is an abstract syntax without inherent semantics so there is no such thing as the right and only way to type-check it. TypeScript recognizes this fact by providing means to configure how type-checking happens. These means are quite flexible, but just a bit not enough for some use cases.

**Comment by aluanhaddad** [comment]
@thorn0 I didn't mean to suggest there was a right way or a wrong way, I was suggesting there might be a way.

**Comment by thorn0** [comment]
@aluanhaddad I didn't mean to argue. It was just a little background on this issue.
