### ISSUE TITLE
Adding tsconfig.json to ASP.NET Core 1.0 project disables compile-on-save

### ISSUE THREAD

**Issue by UncertainConstraint** [Microsoft/TypeScript#12024]
**TypeScript Version: 2.0.3**

**Visual Studio 2015 Update 3**

**ASP.NET Core 1.0**

**Microsoft Windows 8.1**

Sample project [here](https://github.com/UncertainConstraint/tsconfigexample.git).

**Expected behaviour**

In order to generate sourcemaps for compiled .ts files, a _tsconfig.json_ file is added to the project to instruct the compiler to generate them **(sourceMap: true**). When saving changes to a .ts file, the .js and sourcemap files are updated.

**Actual behaviour**

In a fresh project, when saving a .ts file the compiled .js version is compiled and nested under its parent.

![image](https://cloud.githubusercontent.com/assets/18441942/19974344/12d01930-a1e0-11e6-886c-b0637363161c.png)

A sourcemap file was not generated, so I added a _tsconfig.json_ file to my project to enable their generation. Doing so also caused a sourcemap to be generated.

![image](https://cloud.githubusercontent.com/assets/18441942/19974609/f22b649a-a1e0-11e6-8d79-982111b4b0ec.png)

However, any further changes to the .ts file do not affect the compiled .js file; it is not updated when saving.

![image](https://cloud.githubusercontent.com/assets/18441942/19974764/7bdb2b6c-a1e1-11e6-92b2-e2a969ed1a42.png)

Remedies I have attempted, to no avail:
- Enabling **Automatically compile TypeScript files which are not part of a project**
- Adding **compileOnSave: true** to the _tsconfig.json_
- Moving it to the _scripts_ folder, alongside the .ts file

Using **tsc** from a command prompt in the _scripts_ directory compiles the .js files and generates sourcemaps correctly; only the **compile on save** functionality stops working.

Removing the _tsconfig.json_ file restores the **compile on save** functionality, though sourcemaps are no longer generated.

**Comment by cwebster2** [comment]
You need to turn on compileOnSave in your tsconfig.json file. e.g.:

```
{
    "compileOnSave": true,
    "compilerOptions": {
        ...
    },
    ...
}
```

**Comment by UncertainConstraint** [comment]
@cwebster2 Thank you for your response, however I have tried adding this option and it does not work.

I have noticed that if I delete the sourcemap file, it is automatically remade straight away and the .js file is recompiled. This occurs regardless of whether or not **compileOnSave** is set.
