### ISSUE TITLE
JSDoc: Share quickinfo between interface and Classes

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/TypeScript#12031]
**TypeScript Version:**  master, commit 702efd559b11632d69e4b788737504f5bc817e58

When we write doc comments for functions in a class that implements an interface, it is nice to get doc comments and to be able to write the doc-comments once. One logical place to put the doc comments is in the interface, but the doc comments for a method/object aren't shared in a subclass of an object if the subclass has a member of the same signature/type.

It would be nice to "inherit" the doc-comments (at least for quickinfo) in the sense that the comments show up when invoking methods in the child class, by default. If the author wants distinct doc comments for the interface and the implementation, they should be able to specify that as well.

**Code**

```ts
interface I {
    /**
     * This is a comment for x.
     */
    x();
}

class A implements I {
    x() { };
    /**
     * This is a comment for y.
     */
    y() {};
}

class B extends A { }

class C extends A {
    y() {};
}

let i: I;
let a: A;
let b: B;
let c: C;
```

**Expected behavior:**

All of the methods `i.*`, `a.*`, `b.*`, and `c.*` have doc comments.

**Actual behavior:** 

```ts
i.x; // has comment
a.x; // no comment
a.y; // has comment
b.x; // no comment
b.y; // has comment
c.x; // no comment
c.y; // no comment
```

Note, a trickier case would be like that in `src/checker.ts` where we build an object that implements an interface. Outside callers of the resulting `TypeChecker` object get to see doc comments from the `TypeChecker` interface, but within the implementation itself (ie: within the sourcefile `checker.ts`), you don't get any doc comments. To handle this, we would need to infer that the functions defined in the closure of `createTypeChecker()` are going to be assigned to a `TypeChecker` object, which requires control flow analysis in the general case.

**Comment by mhegazy** [comment]
looks fixed in latest.
