### ISSUE TITLE
Date constructor should accept 'null' as a valid value when using strictNullChecks

### ISSUE THREAD

**Issue by guncha** [Microsoft/TypeScript#12034]
**TypeScript Version:** nightly 2.1.0-dev.20161103

**Code**

```ts
let t = new Date(null) // Argument of type 'null' is not assignable to parameter of type 'string'
```

According to the spec, the result is going to be the same as `new Date(+0)`.

http://www.ecma-international.org/ecma-262/5.1/#sec-15.9.3.2

**Comment by RyanCavanaugh** [comment]
This doesn't seem at all desirable. It would imply it's legal to call `new Date` providing a `string | null`, when you almost certainly would want to have null-checked that value.

**Comment by guncha** [comment]
Upon further thought, I tend to agree. It's not matching the spec, but developer experience trumps that. I can always do this to make it explicit:

```ts
let x: string | null
let t = new Date(x || 0)
```

**Comment by RyanCavanaugh** [comment]
Note that the ES spec defines all sorts of behavior that we don't want to allow to pass typechecking; e.g. the behavior of `{ } / "hello world"` *is* well-defined according to the spec.
