### ISSUE TITLE
Difference between `import *` and `import {}` with augmented module

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#12030]
**TypeScript Version:**  nightly (2.1.0-dev.20161103)

**Code**

(Put in `test/cases/compiler/importVsImport.ts` and run tests)

```ts
// @Filename: /types/lib/index.d.ts
declare var lib: lib.Static;
export as namespace lib;
export = lib;

declare namespace lib {
    interface Static {
        stat(): void;
    }
}

// @Filename: /types/lib-extender/index.d.ts
import * as lib from "lib";

declare module "lib" {
    export function fn(): void;
}

// @Filename: /src/a.ts
import * as lib from "lib";
lib.fn();

import { fn } from "lib";
fn();

// @Filename: /tsconfig.json
{
    "compilerOptions": {
        "baseUrl": ".",
        "paths": {
            "*": ["types/*"]
        }
    }
}
```

**Expected behavior:**

No error.

**Actual behavior:** 

`/src/a.ts(2,5): error TS2339: Property 'fn' does not exist on type 'Static'.`

This is based on `angular-ui-router-default-tests.ts` in DefinitelyTyped, which currently does not work. `angular-ui-router` augments the `angular` module, which also has a `export =`.

**Comment by aluanhaddad** [comment]
This isn't actually a default export right? My understanding of UMD declarations is that `export =` still has `commonjs` implications. Is that correct?

**Comment by andy-ms** [comment]
`export default` adds an additional export with funny syntax. `export =` changes the shape of the module to be equivalent to a particular value, which may be merged with a namespace to provide something resembling additional exports.

**Comment by aluanhaddad** [comment]
@andy-ms Thank you.

I was tripped up by the statement
> This is based on angular-ui-router-default-tests.ts in DefinitelyTyped, which currently does not work. angular-ui-router augments the angular module, which also has a default export.

because it does not have a default export, but rather exports all meanings of `angular` as the `exports` object.

**Comment by andy-ms** [comment]
Fixed.
