### ISSUE TITLE
bug: for..of does not work with NodeList

### ISSUE THREAD

**Issue by opensrcken** [Microsoft/TypeScript#12038]
**TypeScript Version:**  nightly (2.1.0-dev.201xxxxx)

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
for(const a of document.querySelectorAll('div')) {}
```

**Expected behavior:**
It should compile.

**Actual behavior:** 
`error TS2495: Type 'NodeListOf<Element>' is not an array type or a string type`

**Comment by RyanCavanaugh** [comment]
![image](https://cloud.githubusercontent.com/assets/6685088/19990653/73efdd70-a1ec-11e6-9f9e-2da2d237849d.png)
