### ISSUE TITLE
Suggestion: a precise return type of Node.appendChild()

### ISSUE THREAD

**Issue by ericzhangjx** [Microsoft/TypeScript#12048]
**TypeScript Version:**  2.0.6

**Code**
From [lib.es6.d.ts](https://github.com/Microsoft/TypeScript/blob/master/lib/lib.es6.d.ts):
```ts
interface Node extends EventTarget {
  // ...
  appendChild(newChild: Node): Node;
  // ...
}
```
Test case:
```ts
document.createElement('div').appendChild(document.createElement('span'));
```

**Expected behavior:**
According to [Node.appendChild() - MDN](https://developer.mozilla.org/en-US/docs/Web/API/Node/appendChild):
> Syntax
> `var aChild = element.appendChild(aChild);`
> The returned value is the appended child.

The return type should be the type of the element being appended, in this case, `HTMLSpanElement`.

**Actual behavior:** 
The `appendChild(document.createElement('span'))` just return with the type `Node`.

**Suggestion**
I wonder if it would be better using Generics to define the return type of `appendChild()`, such as:
```ts
interface Node extends EventTarget {
  appendChild<T>(newChild: T): T;
}
```

**Comment by aluanhaddad** [comment]
```ts
interface Node extends EventTarget {
  appendChild<T extends Node>(newChild: T): T;
}
```
makes sense to me.

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.
