### ISSUE TITLE
lib.es6.d.ts doesn't strongly type the frameElement of a Window interface

### ISSUE THREAD

**Issue by mattmutt** [Microsoft/TypeScript#12046]
BUG:
when examining the interface for Window it appears that `frameElement` property is typed generically as an Element.

While the majority of the cases this will probably be a `HTMLIFrameElement`, there is a possibility of it being an `HTMLObjectElement`. Don't know the prevalence of the latter case.

The declarations typing file currently broadly types the `Window` property for `frameElement` as simply `Element` - it should be a bit more strict.

**TypeScript Version:**  2.0.3 / nightly (2.1.0-dev.201xxxxx)

**Code**

```ts
 readonly frameElement: Element;

```

**Expected behavior:**
Window frameElement should be strongly typed
**Actual behavior:** 
resolves to a generic `Element`

**Comment by aluanhaddad** [comment]
It matches the [whatwg specification] (https://html.spec.whatwg.org/multipage/browsers.html#dom-frameelement) which doesn't restrict it to the types you mentioned but simply lists them as possible values.

**Comment by dippi** [comment]
Shouldn't it be `Element | null`?

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
