### ISSUE TITLE
Non-nullable check fails with nested scope

### ISSUE THREAD

**Issue by e-cloud** [Microsoft/TypeScript#12042]
**TypeScript Version:**  2.1.0-dev.20161103

**Code**

```ts
type callback = {
    missing?: string[] | {
        push: (item: string) => void
    }
}

if (callback.missing) {
    filenames.forEach(function (filename) {
        callback.missing.push(resolver.join(directory, filename))
    })
}
```

**Expected behavior:**
As it's check by if statement, `callback.missing` must be valid value, no error will occur.

**Actual behavior:** 

```js
if (callback.missing) {
    filenames.forEach(function (filename) {
        callback.missing.push(resolver.join(directory, filename))
        // TS2532:Object is possibly 'undefined'. The error points to callback.missing
    })
}
```

**Comment by RyanCavanaugh** [comment]
See #9998 

You can fix this by capturing `callback.missing` so the compiler knows it's not going to change between when you checked it and when the callback is invoked:

const m = callback.missing;
if (m) {
    filenames.forEach(function (filename) {
        m.push(resolver.join(directory, filename))
    })
}
