### ISSUE TITLE
"import =" exposes default export member with the wrong name

### ISSUE THREAD

**Issue by zhengbli** [microsoft/TypeScript#12060]
![image](https://cloud.githubusercontent.com/assets/1171301/20025830/b6fa887c-a2af-11e6-87df-c4869e6f31f5.png)

![image](https://cloud.githubusercontent.com/assets/1171301/20025837/cc78d26c-a2af-11e6-9096-637875652d30.png)

TS version: 2.1.0-dev.20161030

**Comment by aluanhaddad** [comment]
It should be exposed under the name `default`.

**Comment by RyanCavanaugh** [comment]
Have to assume this is fixed by now
