### ISSUE TITLE
`string[]` cannot be used instead of `DOMStringList`

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#12069]
`DOMStringList` has some methods different from `string[]` such as `constains` and `item`. So we need to revert https://github.com/Microsoft/TSJS-lib-generator/pull/148 by next release 2.1.0.

**TypeScript Version:**  2.1.0-dev.20161106

**Code**

```ts
interface DOMStringList {
    readonly length: number;
    contains(str: string): boolean;
    item(index: number): string | null;
    [index: number]: string;
}
```

cc @mhegazy

**Comment by Artazor** [comment]
@mhegazy please check! DataTransfer.types is still `string[]` - something nasty happened on merge. fix has disappeared both from release-2.1 and master (thus in npm we have a TS with bug)
