### ISSUE TITLE
Don't emit a module when imports are used if export is not used (in AMD mode at least)

### ISSUE THREAD

**Issue by avonwyss** [Microsoft/TypeScript#12062]
**TypeScript Version:**  2.0.6

It boils down to creating entry points / bootstrappers for applications while keeping the ability to use imports. In AMD modules, there are modules (`define`) and consumers (`require`).

**Code:**
module.ts:
```ts
export = class Something {
   // Code..
}
```

application.ts:
```ts
import Something = require("module");

// Code - but NO export whatsoever
```

**Expected behavior:**
module.ts emits a module (as it does today).
application.ts emits the following:
```ts
require(["module"], function (Something) {
// Code
});
```

**Actual behavior:** 
Both emit a `define(...` which makes it impossible to use application.ts as entry point / bootstrapper script.

**Related:**
- https://stackoverflow.com/questions/37670862/typescript-self-executing-function-wont-fire-if-there-is-an-import
- https://stackoverflow.com/questions/37714934/cant-bootstrap-typescript-application-because-module-is-not-exposed

**Comment by aluanhaddad** [comment]
So you are saying that when a file contains a top level `import` but no top level `export` that it should be compiled as a global script? 
This would be a fairly massive breaking change.

**Comment by avonwyss** [comment]
What I'm looking for is a way to have TS emit code that does `require([...depnames...], function(...deps...) {` in the AMD world. Right now, the only way I have found is to *not* import anything, which makes it impossible to use type definitions coming from modules in that code, thus I'm left with no type checking except for stuff which was `declared` in a `.d.ts` file somewhere.

If I have code that does not touch the `exports` variable and does not do an `export` or `export =`, then it looks as if that was not a module in the first place (at least in my code I don't have modules which do not export anything at all).

Of course, if that change is seen as being a "massive breaking change", I could very well live with a /// directive that instructs TypeScript to emit a `require` instead of a `define`, something like this maybe:

```
/// <amd-require />
```

Note: Since I work only in the browser and with AMD modules, I have no idea how other module types deal with the bootstrap situation. How can one write code that shall always be executed, not just when requested as dependency from another piece of code? RequireJS, for instance, will lazily run the modules code when it is requested, so even when the script is bundled an/or loaded imperatively it does get compiled but not run. So how it this done with other module kinds?

**Comment by aluanhaddad** [comment]
I also use TypeScript primarily in the browser but I primarily use `system` modules (the System.register format) which are much closer to AMD modules than say CommonJS modules.

Initial load is conventionally kicked off by a script tag containing the single line 

```JS
SystemJS.import(' entry-module')
  .catch(...);
```

I've seen analogous code used with RequireJS but I have no idea if it is idiomatic in the AMD world.

**Comment by mhegazy** [comment]
I do not think we can generalize this to all module and module systems. 

For AMD, why not just include one file that has `require("entryPoint")` or set your [`data-main`](http://requirejs.org/docs/start.html) on your script tag?

**Comment by avonwyss** [comment]
I do use the workaround of having a separate file that requires the entry point file, but this is not optimal. Due to script order issues in my specific case the `data-main` didn't work; I could have added shims and stuff but preferred to just have the few problematic scripts in order.

**Comment by aluanhaddad** [comment]
Right I completely forgot that `data-main` the idiom...
That is what you should use. If you have issues with script load order you should fix them with shim config.

**Comment by avonwyss** [comment]
Thanks for your replies.

I checked the [AMD spec](https://github.com/amdjs/amdjs-api/blob/master/AMD.md#global-variables-) and it explicitly does not mandate how what a `require` global variable is and how it shall perform. Being a RequireJS user I wasn't aware that this is not part of the AMD spec but rather just how RequireJS does it.

I therefore close this issue, even though I still think that the implication that anything which imports something must be a module (in contrast to anything which exports something) is rather odd.

**Comment by aluanhaddad** [comment]
> I still think that the implication that anything which imports something must be a module (in contrast to anything which exports something) is rather odd.


@avonwyss I would say the one reason is that it is impossible to `import` something without an infrastructure for doing so. Something like a module loader or bundler, or someday hopefully a native browser implementation, is required to interpret the imports.
Also it is anything that either Imports or exports that is a module.
