### ISSUE TITLE
Recursive tail call without a stopping condition should mark the function as never

### ISSUE THREAD

**Issue by alitaheri** [Microsoft/TypeScript#12061]
Not sure if this is `By Design`, `Limitation`, `Bug` or simply left out.

**TypeScript Version:** All Versions

**Code**

```ts
// this has a stopping condition, a simple return statement could mark it finite.
// return type inferred as void: OK!
function foo(num: number) {
  if (num === 0) {
    return;
  }
  return foo(num - 1);
}

// no stopping condition
// return type inferred as void: :/
function bar() {
  bar();
}

```

**Expected behavior:**

`bar` should be `never`.

**Actual behavior:** 

`bar` is `void`.

**Comment by gcnew** [comment]
`bar` doesn't have a `return` statement thus the inferred type `void` seems fair. On the other hand I'm surprised you get an inferred type for `foo` as typescript doesn't infer self recursive functions at all.

**Comment by alitaheri** [comment]
Well returning recursive call without explicit type annotation is an error as it should be. I don't think this is worth exploring.
