### ISSUE TITLE
Suggestion: Allowing leading pipe in union type declarations

### ISSUE THREAD

**Issue by mariusschulz** [Microsoft/TypeScript#12071]
Currently, because of the leading `|` symbol , the following code is **invalid** TypeScript:

```ts
type ReduxAction =
  | { type: "INCREMENT" }
  | { type: "DECREMENT" }
  | { type: "SET_VALUE", value: number };
```

I suggest we relax the syntax such that a single leading pipe symbol is allowed (but not required) in a union type declaration. Flow and F#, for example, both allow this syntax.

This change is backwards-compatible and gives developers a little more code formatting freedom.

**Comment by RyanCavanaugh** [comment]
Accepting PRs to allow one leading ignored `|` or `&` in a type position

**Comment by mariusschulz** [comment]
@RyanCavanaugh If I'm not mistaken, parsing a leading `|` or `&` boils down to the following change:

```diff
function parseUnionOrIntersectionType(kind: SyntaxKind, parseConstituentType: () => TypeNode, operator: SyntaxKind): TypeNode {
+   parseOptional(operator);
    let type = parseConstituentType();
    if (token() === operator) {
        const types = createNodeArray<TypeNode>([type], type.pos);
        while (parseOptional(operator)) {
            types.push(parseConstituentType());
        }
        types.end = getNodeEnd();
        const node = <UnionOrIntersectionTypeNode>createNode(kind, type.pos);
        node.types = types;
        type = finishNode(node);
    }
    return type;
}
```

Where exactly would an accompanying test go?

**Comment by RyanCavanaugh** [comment]
@mariusschulz you can drop a new file in `/tests/cases/compiler/`. See CONTRIBUTING.md for more details.

**Comment by mariusschulz** [comment]
@RyanCavanaugh Thanks! I've sent a pull request: https://github.com/Microsoft/TypeScript/pull/12386
