### ISSUE TITLE
Control Flow Analysis + Getter Properties

### ISSUE THREAD

**Issue by mariusschulz** [Microsoft/TypeScript#12070]
**TypeScript Version:**  2.0.3 / nightly (2.1.0-dev.20161106)

The following example doesn't compile without errors in the most recent TypeScript nightly build. Control flow analysis determines that `scanner.current` has the type `"/"`, and thus TypeScript flags the string comparison with `"*"`. However, it doesn't take into account that `current` is a getter property, which returns a different value after `advance()` has been called.

Wouldn't it make sense to treat getter properties like methods in this case and not narrow their type to a string literal type?

**Code**

```ts
class Scanner {
    constructor(private input: string, private pos = 0) {}

    advance() {
        this.pos++;
    }

    get current() {
        return this.input[this.pos];
    }
}

const scanner = new Scanner("/* Comment */");

if (scanner.current === "/") {
    scanner.advance();

    if (scanner.current === "*") {
        // Error
        // Operator '===' cannot be applied to types '"/"' and '"*"'
    }
}
```

**Expected behavior:**
No errors.

**Actual behavior:** 
Error `Operator '===' cannot be applied to types '"/"' and '"*"'`

**Comment by aluanhaddad** [comment]
This is not really related to the property being computed or even to its being a property at all. Calling any function could have arbitrary side effects that cannot plausibly be tracked. Here is a minimal repro
```ts
let current = "/* comment */";

const advance = () => {
    current = current.slice(1);
}

if (current === "/") {

    advance();

    if (current === "*") { // [ts] Operator '===' cannot be applied to types '"/"' and '"*"'
    }
}
```

**Comment by mariusschulz** [comment]
Anders precisely answers my questions [here](https://github.com/Microsoft/TypeScript/issues/9998#issuecomment-235963457). Interestingly, there's a similar piece of code in the TypeScript compiler. It's a calculated tradeoff of control flow analysis.
