### ISSUE TITLE
typescript change number when cast from json

### ISSUE THREAD

**Issue by itsurge** [Microsoft/TypeScript#12078]
i am geting json data from a web api as the following  :
{"name":"johan","packageNo":[100000498827944537]}
but when i use it in typeScript project the packageNo change to number : 100000498827944540
Whyyyyyyyyyyyyyyyyyyyyyyyyyyyy?

**Comment by alitaheri** [comment]
It's not related to typescript. it's simply how javascript handles number.
The maximum safely representable integer in javascript is 9007199254740991 which is a couple of zeroes smaller than your number. no wonder it gets messy. don't cast this to number, you can't represent it. use `string` instead.

```js
9007199254740991    // max safe
100000498827944540  // your number :O
```

**Comment by aluanhaddad** [comment]
Just to clarify TypeScript does not perform typecasting at all. What you think of as casting is actually type exertion. It is purely a design time feature and has no impact on the code that is either emitted or executed.
