### ISSUE TITLE
TypeScript's own existential operator

### ISSUE THREAD

**Issue by mohsen1** [Microsoft/TypeScript#12099]
Based on history of existential operator here (#16) I don't think you can get `.?` or `?.` operators working in JavaScript. Because programs like `1.?.2:.3` are valid JavaScript and it's almost impossible to address all ambiguous situations in TypeScript compiler. 

How about building on top of `!` postfix expression operator and make a TypeScript specific existential operator? 

We can introduce `!!` postfix expression operator that does exactly what `.?` does in CoffeeScript. 

```ts
x!!y!!z
```

Compiles to 
```js
x && x.y && x.y.z
```

**Comment by decademoon** [comment]
> Because programs like `1.?.2:.3` are valid JavaScript

Is this ambiguity only when `1.` is a number literal? In that case, typescript could preference `1.` as a number literal and require `(1).?` to resolve the ambiguity, in the same way that `1.toString()` is an error while `(1).toString()` isn't.

Although I don't really see a situation where someone would want to do that with a number literal.

**Comment by alitaheri** [comment]
This has to first make it to EcmaScript. typescript's design goal disallows adding expression level syntax. I suggest making a proposal to EcmaScript. This feature is really good 👍

**Comment by kitsonk** [comment]
This is a dupe of #16... conversation should continue there instead of opening up a new issue.

**Comment by mhegazy** [comment]
I agree with @kitsonk; this looks lik an alternative syntax for #16, and not a new proposal.

**Comment by mohsen1** [comment]
👍 I thought because this is a different approach to existential operator it would be a new proposal. Closing in favor  of #16
