### ISSUE TITLE
Path mappings have unintuitive behavior if user accidentally adds an extension

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#12098]
Was with @zhengbli when we hit the following:

`tsconfig.json`:

```json
{
    "compilerOptions": {
        "baseUrl": ".",
    	"paths": {
             "foo": ["foo.ts"]
        }
    }
}
```

`foo.ts`

```ts
export function blah() { }
```

`hello.ts`:

```ts
import * as x from "foo";
```

Right now you'll get an error on the import that `foo` couldn't be resolved.

Even the documentation currently states (incorrectly) that this should be a valid (though the website isn't up to date). Perhaps we should allow users to specify the extension.

**Comment by vladima** [comment]
it used to work, seems it was broken in [this](https://github.com/Microsoft/TypeScript/pull/9646) PR. @andy-ms, can you please take a look
