### ISSUE TITLE
incorrect this and class instance with inheritation

### ISSUE THREAD

**Issue by e-cloud** [Microsoft/TypeScript#12097]
**TypeScript Version:**  2.1.0-dev.20161107

**Code**
```js
{
  ...
  "compilerOptions": {
    "target": "es5"
  }
  ...
}
```
```ts
class WebpackOptionsValidationError extends Error {
    constructor() {
        super();
        Error.captureStackTrace(this, WebpackOptionsValidationError);
        this.name = 'WebpackOptionsValidationError';
    }
}
```

**Expected behavior:**

```ts
const err = new WebpackOptionsValidationError()
err instanceof WebpackOptionsValidationError // true
```
transpiled:
```js
__extends(WebpackOptionsValidationError, _super);
function WebpackOptionsValidationError() {
    _super.call(this);
    Error.captureStackTrace(this, WebpackOptionsValidationError);
    this.name = 'WebpackOptionsValidationError';
    return this;
    // here return instance of WebpackOptionsValidationError
}
```

**Actual behavior:** 
```ts
const err = new WebpackOptionsValidationError()
err instanceof WebpackOptionsValidationError
// false -- err is instanceof Error but not WebpackOptionsValidationError
```
transpiled:
```js
__extends(WebpackOptionsValidationError, _super);
function WebpackOptionsValidationError() {
    var _this = _super.call(this) || this;
    Error.captureStackTrace(_this, WebpackOptionsValidationError);
    _this.name = 'WebpackOptionsValidationError';
    return _this;
    // here return instance of Error,
    // it refers to the prototype object of WebpackOptionsValidationError
}
```

---
The wrong behavior is result from #11846 and #11868.

**Comment by e-cloud** [comment]
@vladima @mhegazy @falsandtru

**Comment by falsandtru** [comment]
See #10166

**Comment by e-cloud** [comment]
@falsandtru #10166 is related but not the solution.

I tried other class inheritances and it turns out the problem is not particular to `Error` inheritance.

see another example: (With Typescript 2.1 latest)
```js
class CustomObject extends Object {
    constructor(message) {
        super()
        this.message = message
    }
}

const obj = new CustomObject('a')
console.log(obj instanceof CustomObject)
```

Expected output:
```js
true
```

Actual:
```js
false
```

You can try [a playground demo](https://www.typescriptlang.org/play/index.html#src=class%20CustomObject%20extends%20Object%20%7B%0D%0A%20%20%20%20constructor(message)%20%7B%0D%0A%20%20%20%20%20%20%20%20super()%0D%0A%20%20%20%20%20%20%20%20this.message%20%3D%20message%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0Aconst%20obj%20%3D%20new%20CustomObject('a')%0D%0Aconsole.log(obj%20instanceof%20CustomObject)%0D%0A)(with Typescript 2.0.x)
Hit the run button and the console will log `true` which is expected

**Conclusion**:
this may breaks some code widely with Typescript 2.1

---
**PS**: One interesting thing is [Babel also transpile it incorrectly](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Ces2015-loose%2Ces2016%2Ces2017%2Clatest%2Cstage-0&code=class%20CustomObject%20extends%20Object%20%7B%0A%20%20%20%20constructor(message)%20%7B%0A%20%20%20%20%20%20%20%20super()%0A%20%20%20%20%20%20%20%20this.message%20%3D%20message%0A%20%20%20%20%7D%0A%7D%0Aconst%20obj%20%3D%20new%20CustomObject('a')%0Aconsole.log(obj%20instanceof%20CustomObject)%0A)

**Comment by falsandtru** [comment]
I wrote my solution in that issue.

**Comment by e-cloud** [comment]
compromising solution in #12123

**Comment by e-cloud** [comment]
Due to design limitation, close this
