### ISSUE TITLE
[Errors] error recovery with interface with implements clause

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#121]
```TypeScript
interface I implements A {    }
```

Expected: 

!!! Interface declaration cannot have 'implements' clause.

Actual: 

!!! '{' expected.!!! ';' expected.!!! ';' expected.!!! Cannot find name 'implements'.!!! Cannot find name 'A'.

**Comment by DickvdBrink** [comment]
Seems to be fixed in master
Test result here: https://github.com/Microsoft/TypeScript/blob/master/tests/baselines/reference/interfaceWithImplements1.errors.txt

**Comment by mhegazy** [comment]
thanks @DickvdBrink
