### ISSUE TITLE
Enhance Object.assign static method signature

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#12109]
**TypeScript Version:**  master

**Code**

#12110

```diff
+    assign<T>(target: T, source: T, ...sources: T[]): T;

-    assign<T, U>(target: T, source: U): T & U;
+    assign<T, U>(target: T, source: U, ...sources: U[]): T & U;
```

**Comment by mhegazy** [comment]
We have a few signatures for 2,3 , and 4 arguments. i am not convinced this adds much. https://github.com/Microsoft/TypeScript/issues/11100 tracks correctly typing this function. so i would say we should wait for https://github.com/Microsoft/TypeScript/issues/11100.

**Comment by falsandtru** [comment]
I see, I introduce this in #11100.

**Comment by falsandtru** [comment]
@mhegazy This patch don't conflict with #12114, is just an enhancement. So you can merge this patch.

**Comment by mhegazy** [comment]
@sandersn is working on a fix for this. i would rather we waited for that change.
