### ISSUE TITLE
Go to definition fails to work in Visual Studio 2015

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/TypeScript#1210]
Hi,

This repro uses `TypeScriptServices.js` from LKG.

With reference to the code below

```TypeScript
import bar = require('./bar');    // Same project
import foo = require('../folder/foo');  // Different project
```

F12 works on the same project item, but fails on the item defined in another project.

The bug also affects all types imported from the other project, for example, F12 on `foo.someMethod` displays the following:

![image](https://cloud.githubusercontent.com/assets/1106823/5104251/dff612da-6fd7-11e4-9632-625810918d26.png)

**Comment by paulvanbrenk** [comment]
After debugging I found that the project is not in the go to def. code, but in the opening of the file code, which explains why it doesn't repro when the file is actually open. 

Investigating further.

**Comment by crwilcox** [comment]
I have made an issue in our tracker to deal with this issue.
https://nodejstools.codeplex.com/workitem/1750

**Comment by int19h** [comment]
We don't need an issue in our tracker, we already have one (that was the starting point)
https://nodejstools.codeplex.com/workitem/1651

**Comment by paulvanbrenk** [comment]
Closing this for now as this is a Node Tools issue.

**Comment by NoelAbrahams** [comment]
@paulvanbrenk, there's been no news on this from NTVS. They all seem to be on Christmas holidays. We're stuck not being able to upgrade to VS 2015.

**Comment by crwilcox** [comment]
Noel and Paul.  

I apologize for the radio silence as of late. We have been busy with other concerns within Node/Python and VS 2015 is not a priority at this time. We are a relatively small team and given all the changes within Node lately we are busy trying to get those features running.

That said, we really really really love pull requests, and we would be happy to consider a contribution to our sources from either one of you.

Thanks!
Chris

**Comment by NoelAbrahams** [comment]
@crwilcox, Paul appears to have already identified the offending section of code.
