### ISSUE TITLE
Visual Studio crashes with Generics

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#12108]
**TypeScript Version:**  2.0.6

1. clone https://github.com/falsandtru/pjax-api
1. open the project via `pjax-api.csproj`
1. open `src/lib/dom.ts`
1. add the angle brackets for generics as follows
1. move the cursor inside the angle brackets
1. crash immediately

```
// add
  }, Object.assign<>({}, option, { capture: true }));
                    ^ cursor
// move
  }, Object.assign<>({}, option, { capture: true }));
                   ^ cursor
```

**Comment by vladima** [comment]
simplified repro 
```ts
declare function f(a: any, ...b: any[]): any;
f<|>(1, 2)
```

if signature help is requested at position `|` script side returns result where `isVariadic` is set to `true` but parameter list is empty which seems to be illegal combination for Roslyn `SignatureHelpItem`

**Comment by falsandtru** [comment]
Thanks @vladima !
