### ISSUE TITLE
lib.es6.d.ts for file reader event is inaccurate

### ISSUE THREAD

**Issue by AmitMY** [Microsoft/TypeScript#12102]
**TypeScript Version:**  Latest

**File** `lib.es6.d.ts`.

**Code**

```ts
let reader = new FileReader();
reader.onload = e => fileObj.src = e.target.result;
```

**Expected behavior:**
Not an error

**Actual behavior:** 

> Unresolved variable 'result'

**Description**:

`interface Event` has `target: EventTarget;`
And
`interface EventTarget` does not have `result`

**Comment by mhegazy** [comment]
looks like the same root cause as https://github.com/Microsoft/TypeScript/issues/299.

**Comment by zhengbli** [comment]
Should be covered by https://github.com/Microsoft/TSJS-lib-generator/pull/207
