### ISSUE TITLE
Module Namespace Object detection

### ISSUE THREAD

**Issue by unional** [Microsoft/TypeScript#12116]
tsc: 2.0.3

**Code**

```ts
// file1.ts
export function foo() {}

// file2.ts
import * as m1 from './file1'
console.log(Object.prototype.toString.call(m1)) // should be '[object Module]', actual '[object object]'
console.log(m1[Symbol.toStringTag]) // should be 'Module', actual undefined
```

Is this the expected behavior?
I get this from http://stackoverflow.com/questions/40494648/detecting-import-as-name-token

**Comment by blakeembrey** [comment]
@unional What is your emit target? I don't think there's any platform that can run native ES6 modules today so this would be expected - it's transpiled into CommonJS modules or objects. Given this, I don't think there's any way to distinguish between what you want and a regular object.

**Comment by unional** [comment]
Good point. My emitting target is es5 with ts@next.
I can see that it may not work if transpile down to es5/es3.

It this is not possible, I will just wait for function/object decorator (which makes the most sense in my use case anyway).

**Comment by unional** [comment]
Closing as this is not reliable in tranpilation scenarios.
