### ISSUE TITLE
jsdoc: type expressions containing new lines aren't parsed

### ISSUE THREAD

**Issue by thorn0** [Microsoft/TypeScript#12119]
**TypeScript Version:**  2.2.2

**Code** (JavaScript)

```js
/**
 * @typedef {(
 *     string | number)}
 */
var NumberLike;

/**@type {NumberLike}*/
var x;
```

**Expected behavior:** the type of `x` should be `string | number`.

**Actual behavior:** `x` is `any`.

Works if rewritten like this:
```js
/**
 * @typedef {(string | number)}
 */
var NumberLike;

/**@type {NumberLike}*/
var x;
```

**Comment by Kovensky** [comment]
They are parsed, as long as you don't put the `*` inside the `{}` block.

This causes odd-looking comment blocks, but at least it's not completely unsupported.

**Comment by jameskeane** [comment]
@sandersn @RyanCavanaugh this has been fixed for a while.

**Comment by thorn0** [comment]
Yes, it works now (TS 3.1.3),
