### ISSUE TITLE
allow super() constructor call inline, like in c#

### ISSUE THREAD

**Issue by parliament718** [Microsoft/TypeScript#12120]
Is there any reason why Typescript can't support a little syntax sugar similar to C# in allowing the base constructor call to be made inline? So Instead of:

```
class Car extends Machine {
    constructor(radiator: RadiatorMechanism) {
        super();                                 <- eww, please add sugar
        var engine = EngineFactory.createEngine('V8');
      
    }
}
```

it could be:

```
//aaah, much better      
class Car extends Machine {
    constructor(radiator: RadiatorMechanism): super() {
        var engine = EngineFactory.createEngine('V8'); 
    }
}
```

It's pretty trivial because all it does is clean up the constructor body, (especially when the following line is really long it just looks weird and my OCD kicks in), but usually that's exactly what syntax sugar is for.

For whatever other reasons it has support in C#, I petition for its support in Typescript  ✌️

**Comment by icholy** [comment]
I don't think the second example is an improvement at all.

**Comment by kitsonk** [comment]
That is super confusing in TypeScript.  Also it changes the semantics of ECMAScript Classes for no significant overriding value, which is contrary to the [TypeScript design goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals):

> 8) Avoid adding expression-level syntax.

**Comment by mhegazy** [comment]
As noted by @kitsonk, this goes against keeping TypeScript concepts inline with that of JavaScript. This is out of scope of the TypeScript project for the time being.
