### ISSUE TITLE
More smart type inference

### ISSUE THREAD

**Issue by s-panferov** [Microsoft/TypeScript#1212]
I was trying to implement the [Result](http://doc.rust-lang.org/core/result/enum.Result.html) type from Rust in TypeScript. [Here](https://gist.github.com/s-panferov/5269524dcf23dad9a1ef) is the result.

Everything works well but there is one thing that disappoints me:

``` ts
static getApiToken(): Result<Token, AuthError> {
    return this.getCurrentUser().andThen(user => new Ok<Token, AuthError>(user.token));
}
```

In this code sample we can't just write `new Ok(user.token)` because TS can't infer `AuthError` type from function's return type. Do you have any plans to add this functionality? Is think that it is not even a breaking change.

**Comment by a3gis** [comment]
Has there been any work done on this? It would be extremely useful to have this kind of inference as part of the language; I stumbled upon this exact problem tonight.

**Comment by mhegazy** [comment]
Looking at this again, this is the same as https://github.com/Microsoft/TypeScript/issues/11152.
