### ISSUE TITLE
Is it possible to use a class definition as if it were an interface?

### ISSUE THREAD

**Issue by cervengoc** [Microsoft/TypeScript#12128]
In many cases I have objects which have to be in a compatible structure with each other,. Some use cases include passing initial values to a class constructor as an object, or using for example `jQuery.extend`. I'd like to be able to use my existing class definition as if it were an interface with all members being optional, so I could constrain a plain object to have compatible properties.

```
class MyClass {
  MyProperty: number;
  MyString: string;
}

...

var instance = new MyClass();
// here I don't have type safety, I could mistype "MyProperty" for example
$.extend(instance, { MyProperty: 5 }); 
```

As a quick and rough proposed syntax, I could imagine something like this.

```
var instance = new MyClass();
// compile error, MProperty should be MyProperty
var properties: MyClass? = { MProperty: 5 }; 
// compile error, MyProperty is a number
var properties: MyClass? = { MyProperty: "asdf" }; 
// compiles succesfully
var properties: MyClass? = { MyProperty: 5 }; 
$.extend(instance, properties);
```

Obviously I could define an interface named `MyClassInterface` for example, and I could manually duplicate all the stuff I need, but I'd like to avoid it as it would clearly and strongly go against DRY principle for example, not having any role except for technical "workaround" purposes.

Maybe there are some alternative techniques, I'd be curious about your thoughts, thank you in advance.

**Comment by icholy** [comment]
This works

``` ts
class MyClass {
  MyProperty?: number;
  MyString?: string;
}

var properties: MyClass = { MyProperty: 123 }; 
```

**Comment by cervengoc** [comment]
@icholy Good to know, however then I still need to modify all of my classes, and make all the members optional this way, including prototype methods. This is quite interesting technique. I wonder if it has any side effects, and I also wonder what is the original purpose of allowing optional class members, as I wasn't aware of that.

**Comment by icholy** [comment]
> Good to know, however then I still need to modify all of my classes, and make all the members optional this way, including prototype methods. 

I bet that in the time you've been thinking about making your code DRY, you could have just written out the interfaces. A little duplication never killed anyone.

> I also wonder what is the original purpose of allowing optional class members, as I wasn't aware of that

It plays a bigger role when `--strictNullChecks` is used.

**Comment by cervengoc** [comment]
> I bet that in the time you've been thinking about making your code DRY, you could have just written out the interfaces. A little duplication never killed anyone.

Thanks for the tip, but let me decide this :) I have about 100+ classes, and I'd have liked a general solution. Thank you for your help though, I'll close this as I think your solution is the closest I can get, and basically I like it.

**Comment by aluanhaddad** [comment]
> I bet that in the time you've been thinking about making your code DRY, you could have just written out the interfaces. A little duplication never killed anyone.

DRY matters.
