### ISSUE TITLE
typescript tsc is not excluding @types/corejs

### ISSUE THREAD

**Issue by pearljamik** [Microsoft/TypeScript#12129]
http://stackoverflow.com/questions/40511098/typescript-tsc-is-not-excluding-types-corejs

In short executing tsc does not ignore corejs @types folder, in spite of the fact that exclude node_modules is present, errors are:

> node_modules/@types/core-js/index.d.ts(262,5): error TS2687: All declarations of 'flags' must have identical modifiers.
node_modules/@types/core-js/index.d.ts(276,5): error TS2687: All declarations of 'EPSILON' must have identical modifiers.
node_modules/@types/core-js/index.d.ts(311,5): error TS2687: All declarations of 'MAX_SAFE_INTEGER' must have identical modifiers.
node_modules/@types/core-js/index.d.ts(318,5): error TS2687: All declarations of 'MIN_SAFE_INTEGER' must have identical modifiers.
node_modules/@types/core-js/index.d.ts(457,5): error TS2403: Subsequent variable declarations must have the same type.  Variable '[Symbol.toStringTag]' must be of type '"Symbol"', but here has type 'string'.
node_modules/@types/core-js/index.d.ts(457,5): error TS2687: All declarations of '[Symbol.toStringTag]' must have identical modifiers.
node_modules/@types/core-js/index.d.ts(464,5): error TS2687: All declarations of 'prototype' must have identical modifiers.
node_modules/@types/core-js/index.d.ts(492,5): error TS2687: All declarations of 'hasInstance' must have identical modifiers.
node_modules/@types/core-js/index.d.ts(498,5): error TS2687: All declarations of 'isConcatSpreadable' must have identical modifiers.
node_modules/@types/core-js/index.d.ts(504,5): error TS2687: All declarations of 'iterator' must have identical modifiers.

**TypeScript Version:**  2.0.3 / nightly (2.1.0-dev.201xxxxx)

```

**Comment by mhegazy** [comment]
in your `tsconfig.json` you have listed `core-js` in the `"types"` property. this means you want to include it.
