### ISSUE TITLE
Excess property declaration supersedes checks on named properties

### ISSUE THREAD

**Issue by ajcrites** [Microsoft/TypeScript#12130]
**TypeScript Version:**  2.0.6

**Code**

```ts
interface Sample {
  sample: string[];
  [propName: string]: string;
}
```
This yields:

> Property `sample` of type `string[]` is not assignable to string type 'string'.

**Expected behavior:**
Named properties should be able to have different types than excess properties

**Actual behavior:** 
The excess property type checking is done against named properties.

**Comment by mhegazy** [comment]
An index signature declares a constraint on the whole type. it allows for something like:

```ts
var x:string;

var sample: Sample;
sample[x]; // we know this has to be `string` even if `x` was `sample`.
```
