### ISSUE TITLE
Interface ProxyHandler (lib.es6.d.ts) incorrect

### ISSUE THREAD

**Issue by ovangle** [Microsoft/TypeScript#12137]
**TypeScript Version:**  2.0.7

**Code**
The type signature for `construct` currently has it's second and third parameters reversed (should be `construct(target: T, argArray: any, newTarget: any)`). `thisArg` is also incorrectly named in the signature, because argument passed to the method is the proxy, not the value of `this`.

It doesn't matter too much, since the arguments are both typed `any`, but the declaration files are useful for reference purposes, so parameter names should be correct.

**Comment by mhegazy** [comment]
PRs are welcomed.
