### ISSUE TITLE
Opt-in when overriding a propery or method

### ISSUE THREAD

**Issue by Llorx** [Microsoft/TypeScript#12132]
This, more than a proposal, is just a question to see what do you think on this, and maybe create a proposal just in case...

We have 2 classes, A and B extending A.

Now B can override methods and properties from A without noticing, leading to a problem if the override was by accident.

What if when you override, you have to opt-in by adding a decorator? So you will know that you are overriding something and act accordingly (Add the decorator to really override or change the property/method name).

There's already this: https://github.com/Microsoft/TypeScript/issues/8306 but I think that mine is a bit different.

**Comment by jods4** [comment]
I think this might be #2000?

**Comment by Llorx** [comment]
Yes but no. Is not opt-in : "it is not an error to omit the override keyword from an overridden method."

**Comment by jods4** [comment]
There was a lot of discussions about that.
The outcome from TS team seems to be that there might be a switch to make `override` mandatory.
From [that comment](https://github.com/Microsoft/TypeScript/issues/2000#issuecomment-224776519)
>New commandline switch `--noImplicitOverride` (feel free bikeshed the name here) makes override mandatory for things that are overrides

**Comment by mhegazy** [comment]
I believe this request is covered by #2000 as @jods4 mentioned.

**Comment by Llorx** [comment]
[This comment](https://github.com/Microsoft/TypeScript/issues/2000#issuecomment-224776519) is not opt-in. Forces a method with override tag to be overriden if extended, or return error.

And the `final` keyword prevents the method from being overriden.

I'm talking about something mid-way. Preventing the method from being overriden (like `final`), but allowing it if you add an special operator.

By the way, seeing the thread topic, I guess that is more appropriate to post there.

PD: And found the only one post telling the same as me. Closing this.
