### ISSUE TITLE
Array.keys throws Object doesn't support property or method 'keys' in IE11

### ISSUE THREAD

**Issue by mayerwin** [Microsoft/TypeScript#12141]
**TypeScript Version:**  2.0.6

** tsconfig.json: **
```
{
  "compileOnSave": true,
  "compilerOptions": {
    "noImplicitAny": false,
    "noEmitOnError": true,
    "removeComments": false,
    "sourceMap": true,
    "target": "es5",
    "module": "system",
    "jsx": "react",
    "experimentalDecorators": true
  },
  "exclude": [
    "typings",
    "node_modules",
    "jspm_packages"
  ]
}
```
**app.tsx:**

`const test = Array.from(Array(10).keys());
`

**Expected behavior:**

In IE 11, no error.

**Actual behavior:** 

In IE 11,  Object doesn't support property or method 'keys'.

Isn't the purpose of `target: es5` to ensure this works across all es5-compatible browsers, without requiring to import es6-shim or other libraries?

**Comment by roganov** [comment]
> Isn't the purpose of target: es5 to ensure this works across all es5-compatible browsers, without requiring to import es6-shim or other libraries?

No, the purpose of `target: es5` is to emit es5-compatible code on syntax level. TypeScript does not auto-polyfill by design.

**Comment by RyanCavanaugh** [comment]
What @roganov said
