### ISSUE TITLE
Issues with type narrowing and pointers

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/TypeScript#12143]
**TypeScript Version:**  2.0.X / (https://www.typescriptlang.org/play/)

**Code**

```ts
const enum TokenType {
    String = 1,
    Colon = 2
}

class Token {
    type: TokenType;

    constructor(type: TokenType) {
        this.type = type;
    }
}


// Failure 1 => impure function
function parseToken(out: Token): void {
    out.type = TokenType.String;
}
(function () {
    let token = new Token(TokenType.Colon);

    if (token.type === TokenType.Colon) {
        parseToken(token);
        console.log(token.type === TokenType.String); // <--- TS gives error here
    }
})();

// Failure 2 => shared variable
(function () {
    let token = new Token(TokenType.Colon);

    function changeType() {
        token.type = TokenType.String;
    }

    if (token.type === TokenType.Colon) {
        changeType();
        console.log(token.type === TokenType.String); // <--- TS gives error here
    }

})();

// Failure 3 => pointer alias
(function () {
    let token = new Token(TokenType.Colon);
    let token2 = token;

    if (token.type === TokenType.Colon) {
        token2.type = TokenType.String;
        console.log(token.type === TokenType.String); // <--- TS gives error here
    }

})();
```

**Expected behavior:**
The code above should have no typechecking errors, since the `console.log` prints `true`.

**Actual behavior:** 
The code above has 3 typechecking errors, inside the `if`, TS assumes `token.type` is `TokenType.Colon` even after:
 * method calls to impure functions
 * method calls to functions that share scope visibility with the variable
 * assignments through aliases

This is where I encountered the bug: https://github.com/Microsoft/vscode-textmate/blob/a33377e93d33088664c022cf643029daf24a758f/src/json.ts#L93

**Comment by ahejlsberg** [comment]
See #9998, in particular my comment [here](https://github.com/Microsoft/TypeScript/issues/9998#issuecomment-235963457).
