### ISSUE TITLE
Argument not assignable to parameter with mix of generic and union

### ISSUE THREAD

**Issue by stephanedr** [microsoft/TypeScript#12155]
**TypeScript Version:**  2.1.1

**Code**
```ts
function ifNull<T>(value: T | null, defaultValue: T): T {
    return value == null ? defaultValue : value;
}
let a = 5;
ifNull(a, 0); // Argument of type 'number' is not assignable to parameter of type '0 | null'.
```

**Expected behavior:**
To be valid.

**Actual behavior:** 
See comment.

**Comment by RyanCavanaugh** [comment]
The non-union parameter is a higher-priority inference for `T` so takes precedence. It's unfortunate in this situation but needs to be how it works for other cases.
