### ISSUE TITLE
[2.1-rc] '>' operator cannot be applied to const number

### ISSUE THREAD

**Issue by berickson1** [Microsoft/TypeScript#12150]
**TypeScript Version:**  2.1.1 (RC)

In our code we use several constants at the top of typescript files to store class config data. For example, we might want to limit the number of operations that can be performed simultaneously, but tweak the value from time to time.  After upgrading to typescript@rc, this code no longer compiles  

**Code**

```ts
const maxPeople = 4;

class Race {
    // Compiles under 2.0.8, Doesn't compile under 2.1.1-rc
    multiPersonRace(): boolean {
        return maxPeople > 1;
    }
}


```
See  https://github.com/berickson1/Playground/blob/master/constError.ts

**Expected behavior:**

Code compiles

**Actual behavior:** 

constError.ts(5,16): error TS2365: Operator '>' cannot be applied to types '4' and '1'.

**Comment by wallverb** [comment]
https://github.com/Microsoft/TypeScript/issues/11134

**Comment by mhegazy** [comment]
closing in favor of https://github.com/Microsoft/TypeScript/issues/10120
