### ISSUE TITLE
importHelpers does not emit import unless at least one other import is present

### ISSUE THREAD

**Issue by Kovensky** [Microsoft/TypeScript#12167]
Noticed on a webpack project with typescript@2.1.1, using either commonjs or es2015 modules:

```ts
// index.ts

import './empty'

async function x () {}
```

```ts
// empty.ts
```

This emits an import for `tslib` following by the import for `empty`. However, commenting the `import 'empty'` line out also omits the import for `tslib`, and the emitted code attempts to use a global `__awaiter`.

I thought this might have been fixed by #12151, but it's still present in current `master` (built with `gulp LKG`).

**Comment by Kovensky** [comment]
Using `isolatedModules` gives a clue: the "Cannot compile namespaces" error hints that tsc doesn't/can't treat files without `import`/`export` as a module.

**Comment by Checksum** [comment]
Just wasted two hours on this! With an empty import statement, it works as intended. Tested on version `2.2.0-dev.20170110`

**Comment by mhegazy** [comment]
If the file does not have a toplevel import/export is it is not considered a module, and it is treated as script/global.

use `--isolatedModules` to flag these files as errors.
