### ISSUE TITLE
Import completion broken on vscode with 2.1

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#12165]
From https://github.com/Microsoft/TypeScript/issues/188#issuecomment-259437781

> @mhegazy i am using VSCode with the 
>```
>    "typescript.tsdk": "./node_modules/typescript/lib",
>```
> in the `.vscode/settings.json` pointing to the nightly build npm package (latest just updated)

> there is no autocomplete for the module paths for imports

![image](https://cloud.githubusercontent.com/assets/937933/20143010/285047a6-a665-11e6-88b9-f572830d6794.png)

> as you can see the autocomplete only shows an already seen text token not a name of a file on disc

**Comment by stevematdavies** [comment]
I have this issue, on 1.18.1 2017, when is a fix due=?
