### ISSUE TITLE
Error TS7006 when the compiler can actually imply the expected type?

### ISSUE THREAD

**Issue by diegovilar** [Microsoft/TypeScript#12179]
**TypeScript Version:**  2.1.1 / 2.1-rc

**Summary**
While trying version 2.1-rc on an AngularJS v1.4 application, I've stumbled on a compiler error (TS7006) that doesn't happen on previous versions (ie: 2.0.6). The interface in question (`IQService`) defines types for a callback, and so the compiler used to imply such types when the interface was used. Now, it complains that the parameters for the callback have `any` as an implicit type.

**Code**
```ts
interface IQService {
    <T>(resolver: (resolve: IQResolveReject<T>, reject: IQResolveReject<any>) => any): IPromise<T>;
}

// $q implements IQService

$q<string>((resolve, reject) => {
    // both resolve and reject should have types (IQResolveReject<string> and IQResolveReject<any>)
})
```

**Expected behavior (ts 2.0.6):**
![typescript-2 0 6](https://cloud.githubusercontent.com/assets/759416/20225163/0a4104d8-a829-11e6-9d67-cd94d4c7bab1.jpg)

**Actual behavior (ts 2.1.1):** 
![typescript-2 1 1](https://cloud.githubusercontent.com/assets/759416/20225164/0a467fe4-a829-11e6-92d6-67daad86237c.jpg)

**Comment by aluanhaddad** [comment]
Install the latest type declaration file. It removes the unnecessary overloads.
![image](https://cloud.githubusercontent.com/assets/5034656/20235993/4a27c2e6-a872-11e6-8256-66cdf9e56be5.png)
See http://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html

**Comment by DanielRosenwasser** [comment]
Sounds like this should be fixed. @diegovilar feel free to reopen if this is still a problem.

**Comment by diegovilar** [comment]
@aluanhaddad: Thanks for the tip. The definition files (https://github.com/DefinitelyTyped/DefinitelyTyped/tree/types-2.0/angular) that remove the unnecessary overloads were not merged with the master branch yet, so that kind of makes it hard for people to solve the problem right away. Hopefully that will change soon. Thanks.

@DanielRosenwasser: Yep, it's fixed. Thanks.

**Comment by aluanhaddad** [comment]
@diegovilar Sorry, I didn't realize it was not yet merged. All I did was run `npm i @types/angular`

**Comment by diegovilar** [comment]
@aluanhaddad: No worries.

Actually, the problem arose while upgrading an Angular 1.4 application that still uses TSD to fetch definition files. Seems like TSD grabs files from the master branch at DefinitelyTyped, while the types-2.0 branch is used by the Typescript Types Bot to provide definitions through npm...

I've created the Angular definitions a few years back and left them for the community at DefinitelyTyped to maintain, so I'm not really aware of how they're planing to maintain compatibility with multiple legacy versions of Angular against multiple versions of TypeScript when breaking changes like these are introduced.

Anyways, thanks. I'm migrating from TSD to npm now.
