### ISSUE TITLE
Extends bug for static method when use ES6/ES2015 Class

### ISSUE THREAD

**Issue by Aqours** [Microsoft/TypeScript#12173]
**TypeScript Version:**  2.0.8

**Code**

```ts
// TS Code

class MyA {

    constructor() {}

    static logg() {
        console.log('origin');
    }

}

class MyB extends MyA {

    constructor() {
        super();
    }

}

let instance = new MyB();

MyA.logg = () => {
    console.log('new value');
};

MyB.logg(); // echo 'origin' but 'new value' in ES6/ES2015 when run with Node.js 7.0.0

```

**Expected behavior:**
echo 'new value'

**Actual behavior:** 
echo 'origin'

**Comment by Kovensky** [comment]
TypeScript copies the static property values instead of setting up a prototype chain between the constructors :cry:

**Comment by isiahmeadows** [comment]
It requires setting the prototype of the constructor itself, which wasn't standardized until ES2015.
