### ISSUE TITLE
Codegen: Avoid useless zero subtraction in rest arguments

### ISSUE THREAD

**Issue by subzey** [Microsoft/TypeScript#12188]
Currenty the function like this:
```ts
const foo = (...args: any[]): void => {
}
```
is transpiled into
```js
var foo = function () {
    var args = [];
    for (var _i = 0; _i < arguments.length; _i++) {
        args[_i - 0] = arguments[_i];
    }
};
```
You may notice that zero subtraction in the `args[_i-0]` part is useless.

My proposal is to drop it and use just `args[_i]` in cases when the function signature consists only of spread.
This small change won't affect the generated code behavior, but would make it slightly more readable and compact.

You can preview [the results here](https://github.com/subzey/TypeScript/commit/b337b29de70022da7fa3c6b5483592b414ed1439), and here's [the proposed change](https://github.com/subzey/TypeScript/commit/66c17246234aa49bfeb8d21de2eca0bac6be83db)

**Comment by DanielRosenwasser** [comment]
Others may have a different opinion, but I think that we'd be okay with this. 👍
