### ISSUE TITLE
return type of generic method from interface not checked

### ISSUE THREAD

**Issue by jbrownson** [microsoft/TypeScript#12183]
**TypeScript Version:**  Version 2.1.1

**Code**

```ts
interface Foo { bar<A>(): A }
class Baz implements Foo { bar<A>() { return "asdf" } }
let foo: Foo = new Baz
let notReallyANumber: number = foo.bar<number>()
console.log(typeof notReallyANumber)
```

**Expected behavior:**
The code shouldn't type check successfully, with something like:
```
Class 'Baz' incorrectly implements interface 'Foo'.
       Types of property 'bar' are incompatible.
         Type '<A>() => string' is not assignable to type '<A>() => A'.
           Type 'string' is not assignable to type 'A'.
```

**Actual behavior:** 
The code type checks, "string" is printed out to the console even though the type of the notReallyANumber checked to be "number".

***Note:***
It's not just the return type, similar results can be obtained with parameter types.

**Comment by RyanCavanaugh** [comment]
This is an error now (two, actually)
