### ISSUE TITLE
spread properties operator ignores constraints

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#12181]
```ts
function f<T extends Object>(value: T) {
    return { ...value }; // expected to typecheck, actual: [ts] Spread types may only be created from object types.
}
```

**Comment by DanielRosenwasser** [comment]
This is intentional - we are looking into this for TypeScript 2.2, and we're tracking it in #10727.

**Comment by DanielRosenwasser** [comment]
To elaborate, there's no way to create a concrete type when spreading a generic type right now. It requires a type operator, but we want to wait for some other functionality to land before we commit to the design of that type operator.

**Comment by sandersn** [comment]
Specifically, #12114 plus some conditional way to combine types, probably.
