### ISSUE TITLE
Compiler adds return before comment in constructor.

### ISSUE THREAD

**Issue by Vitekant** [Microsoft/TypeScript#12191]
**TypeScript Version:**  2.1.1
It seems that version 2.1 of typescript changed subclass constructor compilation and it could potentially be a breaking change. I haven't seen it documented. 
'return' is injected at the beginning of a compiled constructor, even before comment, but super call is left out after comment and in result it's not executed. 

**Code**

```ts
class A {
    constructor(public text: string) { }
    print() {
        console.log(this.text);
    }
};

class B extends A {
    constructor(text: string) {
        // this is subclass constructor
        super(text)
     }
};
```

**Expected behavior:**
```ts
var B = (function (_super) {
    __extends(B, _super);
    function B(text) {
        // this is subclass constructor
        return _super.call(this, text) || this;
    }
    return B;
}(A));
;
```

**Actual behavior:** 
```ts
var B = (function (_super) {
    __extends(B, _super);
    function B(text) {
        return 
        // this is subclass constructor
        _super.call(this, text) || this;
    }
    return B;
}(A));
;
```

**Comment by DanielRosenwasser** [comment]
A fix is currently out for review in #12197. Thanks a ton for filing!
