### ISSUE TITLE
Downlevel async/await code has undesirable error handling behavior

### ISSUE THREAD

**Issue by zhaytee** [Microsoft/TypeScript#12192]
**TypeScript Version:**  2.0.9

**Code**

```ts
function someTask() {
    return Promise.resolve();
}

async function main() {
    await someTask();
    const does: any = {};
    console.log(does.not.exist);
}

main();
```

**Expected behavior:** An exception is thrown which, being uncaught, kills the node process and prints a stack trace.

**Actual behavior:** node issues an "UnhandledPromiseRejectionWarning" like so:
> (node:83788) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'exist' of undefined
> (node:83788) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

This happens because the `__awaiter` helper, which tsc generates in order to handle async/await usage, creates a promise for use with generators. I'm not sure exactly why the error gets stuck in this limbo, but it's annoying because no stack trace is included.

**Comment by Kovensky** [comment]
That is to spec. `async` functions **always** return a `Promise`, which either resolves to its return value or reject with a `throw`n value.

**Comment by zhaytee** [comment]
@Kovensky Ah, of course. Thanks for clarifying!
