### ISSUE TITLE
node moduleResolver does not handle directory in package.json main field

### ISSUE THREAD

**Issue by Kovensky** [Microsoft/TypeScript#12198]
The `common-tags` package indicates a directory in its `main` field in the `package.json`, which is valid in node (it will look in `lib/index.js`, `lib/package.json`, etc).

The entry can be seen [here](https://github.com/declandewet/common-tags/blob/master/package.json#L84).

This a snippet of the output of `--traceResolution` in a project:
```
File '.../src/node_modules/common-tags.js' does not exist.
File '.../src/node_modules/common-tags.jsx' does not exist.
Found 'package.json' at '.../src/node_modules/common-tags/package.json'.
No types specified in 'package.json', so returning 'main' value of 'lib'
File '.../src/node_modules/common-tags/lib' does not exist.
File '.../src/node_modules/common-tags/lib.ts' does not exist.
File '.../src/node_modules/common-tags/lib.tsx' does not exist.
File '.../src/node_modules/common-tags/lib.d.ts' does not exist.
File '.../src/node_modules/common-tags/index.js' does not exist.
File '.../src/node_modules/common-tags/index.jsx' does not exist.
File '.../src/node_modules/@types/common-tags.js' does not exist.
File '.../src/node_modules/@types/common-tags.jsx' does not exist.
File '.../src/node_modules/@types/common-tags/package.json' does not exist.
File '.../src/node_modules/@types/common-tags/index.js' does not exist.
File '.../src/node_modules/@types/common-tags/index.jsx' does not exist.
File '.../node_modules/common-tags.js' does not exist.
```

The resolver sees the `main` field correctly, but it doesn't try accessing it as a directory, only as a file; eventually failing to locate the package.

Using typescript ea309fe5.

**Comment by vladima** [comment]
This seem to be a missing piece in the [description](https://nodejs.org/api/modules.html#modules_all_together) of node module resolution algorithm that currently states:
>LOAD_AS_FILE(X)
1. If X is a file, load X as JavaScript text.  STOP
2. If X.js is a file, load X.js as JavaScript text.  STOP
3. If X.json is a file, parse X.json to a JavaScript Object.  STOP
4. If X.node is a file, load X.node as binary addon.  STOP

>LOAD_AS_DIRECTORY(X)
1. If X/package.json is a file,
   a. Parse X/package.json, and look for "main" field.
   b. let M = X + (json main field)
   c. **LOAD_AS_FILE(M)**
2. If X/index.js is a file, load X/index.js as JavaScript text.  STOP
3. If X/index.json is a file, parse X/index.json to a JavaScript object. STOP
4. If X/index.node is a file, load X/index.node as binary addon.  STOP

So result of reading `main` field uses `LOAD_AS_FILE` which looks only in files. Given that I cannot really say whether current node behavior is correct and spec is outdated or what we see in node is just an implementation artifact that can disappear in future versions.

**Comment by DanielRosenwasser** [comment]
Is this the same issue as #12974?

**Comment by mhegazy** [comment]
no, but related.
