### ISSUE TITLE
Awkward error message for accessing static property in anonymous class

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#12195]
```ts
var x = class {
    static foo() {}
    constructor() {
        foo;
    //  ~~~ error!
    }
}
```

The error message you get is

> Cannot find name 'foo'. Did you mean the static member '(Anonymous class).foo'?

Perhaps this is okay? This at least points out that you might be referencing a static member.

**Comment by kitsonk** [comment]
At runtime, the `.name` of the class would be `x` and seems like that could be determined statically.

**Comment by DanielRosenwasser** [comment]
That actually might be a good idea for a suggestion in that case, but a class expression doesn't necessarily always have a name to reference, since it might be returned, immediately `new`-ed, etc.

For the record, this is something I found while writing test cases for something else, but I figured it would be a good first bug.

**Comment by aluanhaddad** [comment]
Seems like a very helpful error message.

**Comment by mhegazy** [comment]
The error looks fine to me. not sure how we can do better here.
