### ISSUE TITLE
Isomorphic global augmentation

### ISSUE THREAD

**Issue by alfaproject** [Microsoft/TypeScript#12208]
Currently, there is the need to add a lot of boilerplate code if we want to target more than one global environment, and I was wondering if TypeScript should sugar this a bit.

**TypeScript Version:** `^2.0.0`

**Code**
```ts
declare global {
  // Augment Node.js `global`
  namespace NodeJS {
    interface Global {
      wtf: WTF;
    }
  }

  // Augment Browser `window`
  interface Window {
    wtf: WTF;
  }

  // Augment Web Worker `self`
  interface WorkerGlobalScope {
    wtf: WTF;
  }
}

// Get the appropriate global object
const root: NodeJS.Global|Window|WorkerGlobalScope =
  (typeof self === 'object' && self.self === self && self) ||
  (typeof global === 'object' && global.global === global && global) ||
  this;

// Get the augmented property
const wtf = root.wtf;
```

**Expected behavior:**
TypeScript to detect the appropriate global environment, maybe by giving the compiler some sort of isomorphic flag.

**Actual behavior:** 
A lot of boilerplate code to have an isomorphic framework.

**Comment by aluanhaddad** [comment]
Why not use this?
```ts
declare global {
  
  // Augment Node.js `global`
  namespace NodeJS {
    interface Global {
      wtf: WTF;
    }
  }
  // Augment Browser `window`
  interface Window extends NodeJS.Global { }
  // Augment Web Worker `self`
  interface WorkerGlobalScope extends NodeJS.Global { }
}
```

**Comment by alfaproject** [comment]
My main gripe is actually with what comes after that. ):

**Comment by chicoxyzzy** [comment]
No reason for TypeScript to handle this. There is [proposal to ECMAScript](https://github.com/tc39/proposal-global) with [polyfill](https://github.com/tc39/proposal-global/blob/master/polyfill.js)

**Comment by alfaproject** [comment]
Pretty sure TS already polyfills much bigger stuff than this, even things on stage 2. (;
I'd even go as far as having typings for a common shared set of global properties where each environment extends (common Global interface of sorts, even if it's empty)

**Comment by mhegazy** [comment]
I have filed issue https://github.com/Microsoft/TypeScript/issues/12902 to track implemening the proposal in https://github.com/tc39/proposal-global

I think this would fall from it.
