### ISSUE TITLE
Sorry for the question: How to add prototype functions in “TypeScript style” to external modules?

### ISSUE THREAD

**Issue by Llorx** [Microsoft/TypeScript#12209]
Again, sorry for asking this here, but my question on StackOverflow only had 14 views, so I don't expect to get a reply there. Maybe there are not much people looking to answer TypeScript questions on StackOverflow yet, or maybe the title of my question is a bit weird: http://stackoverflow.com/questions/40561912/how-to-add-prototype-functions-in-typescript-style-to-external-modules

I copy-paste it here:

I want to modify the prototype of the nodejs `module` module.

`@types/node` has an interface defined for this (`NodeModule`) but don't has anything when I `import` the module, so I have to `require` it.

```ts
import * as Module from "module"; // Error
var Module = require("module"); // Ok
```

The problem is that Module don't has any definition. Is returned as `any`.

I have this

```ts
export interface CustomNodeModule extends NodeModule {
    __thingy:()=>void;
}

Module.prototype.__thingy = function() {
    // things!
}
```

I have to create my own `CustomNodeModule` interface, but, how can I modify the `Module` prototype and also those functions know that they are part of a `CustomNodeModule` instance?

**Again**, for the third time, sorry for the question here, but my question is deserted on StackOverflow :-(

**Comment by mhegazy** [comment]
What is the module you are trying to augment?

**Comment by Llorx** [comment]
`module`

**Comment by mhegazy** [comment]
ahh.. I did not know that module existed. so looks like this is undocumented, and does not exist in `@types\node` any ways. you can define it your self. With some help form [dts-gen](https://github.com/Microsoft/dts-gen) here is how i would define it:

```ts
// module.d.ts

declare module "module" {
    export = module;
    class module {
        constructor(id: any, parent: any);
        load(filename: string): void;
        require(path: string): any;
        static Module: typeof module;
        static globalPaths: string[];
        /** @deprecated */
        static requireRepl(...args: string[]): any;
        static runMain(): void;
        static wrap(script: any): any;
        static wrapper: string[];
    }
}
```

**Comment by DanielRosenwasser** [comment]
For the record, since `NodeModule` is a global, you'd want to decompose the constructor into an interface:

```ts
declare module "module" {
    export = Module;

    var Module: ModuleConstructor;
    
    interface ModuleConstructor {
        new (id: any, parent: any): NodeModule;
        Module: typeof Module;
        globalPaths: string[];
        /** @deprecated */
        requireRepl(...args: string[]): any;
        runMain(): void;
        wrap(script: any): any;
        wrapper: string[];
    }
}
```
