### ISSUE TITLE
Incorrect formatting after readonly modifier

### ISSUE THREAD

**Issue by aluanhaddad** [Microsoft/TypeScript#12218]
**TypeScript Version:** 2.1.1,  2.0.9, nightly (2.2.0-dev.20161114)
VS Code: 1.8.0 - Insider

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
class C {
  // three spaces separate the tokens readonly and property
  readonly   property = {};
}
```

**Expected behavior:**
After applying the format command via VS Code (default `shift + alt + f`) the extra whitespace between `readonly` and property is removed just as it is with modifiers such as `public`, `private`, and `protected`

**Actual behavior:** 
The extra whitespace between `readonly` and `property` is retained. Note that this does not occur for other modifiers such as `public` and only occurs when `readonly` is the last modifier (
`readonly public` ~~works correctly~~ is correctly a syntax error).

**Comment by DanielRosenwasser** [comment]
Thanks for the fix @DanCorder!

**Comment by aluanhaddad** [comment]
Much appreciated!
