### ISSUE TITLE
strictNullChecks with `in` operator

### ISSUE THREAD

**Issue by djyde** [Microsoft/TypeScript#12214]
**TypeScript Version:**  nightly (2.2.0-dev.20161114)

**Code**

```ts
interface Foo {
  bar?: string
}

let foo: Foo = {
  bar: 'bar'
}

if ('bar' in foo) {
  foo.bar.length // [ts] Object is possibly 'undefined'.
}

```

**Expected behavior:**
`foo.bar` would probably not be `undefined` if `'bar' in foo` is `true`

**Actual behavior:** 
compiler throw an error that `foo.bar` is `undefined`

**Comment by djyde** [comment]
oh, even though `'bar' in foo` is true, foo.bar is possibly 'undefined'. 😂

I think is not the problem of compiler, so I close it.

**Comment by kitsonk** [comment]
Actually you have a point, because:

```ts
let foo: Foo = {
  bar: undefined
};
```

Would be a compiler error under `strictNullChecks`.  The construct `'bar' in foo` is sufficient to determine an option property is in fact present and the compiler could then assume that whatever type is assigned to the optional property is valid.
