### ISSUE TITLE
Index signature rejects optional properties with strictNullChecks

### ISSUE THREAD

**Issue by alitaheri** [microsoft/TypeScript#12216]
Something tells me this happened Very recently since I was the error in some libraries after I updated typescript to latest nightly. Might be related to #12114.

**TypeScript Version:**  2.2.0-dev.20161114

**Code**

With `strictNullChecks` on.

```ts
interface A {
  a?: number; // Typescript rejects this
  b: number;
  [prop: string]: number;
}
```

**Expected behavior:**

Compile 😍 Or not 😕 I'm not sure if this is by design.

**Actual behavior:** 

`Property 'a' of type 'number | undefined' is not assignable to string index type 'number'.` 😱

**Comment by RyanCavanaugh** [comment]
This is the intended behavior
