### ISSUE TITLE
Slow navigation in Visual Studio 2015 Preview

### ISSUE THREAD

**Issue by mrcrowl** [Microsoft/TypeScript#1222]
The following commands have become *very slow* to respond in Visual Studio 2015 Preview when working with TypeScript projects (the same commands were nearly instant in Visual Studio 2013):

- Jump to definition (F12): there is a 3-8 second pause and usually a small window appears saying "Navigating to definition..."

- Create a new TS file: immediate to create, but as soon as I start typing there is at least 10 sec lag before first characters appear.

- Rename variable/function/class (F2): depending on the scope there is a 2-5 second pause before you can start typing the new name, but once that appears the rename happens quickly.

The project I am working on is reasonably large, approx 800 *.ts files, where we use primarily AMD-style (import = require...) to reference other files.  Our general approach is one class/interface/enum per file.

Machine is a 1 month old Macbook Pro i7 running Windows 8.1, 16GB memory.  I decided to try out Visual Studio 2015 Preview only because of bug #1142 which I encountered after upgrading to TypeScript tools v1.3 in VS2013.

**Comment by danquirk** [comment]
Are you able to share the affected project (assuming this is happening in some reasonably large project and not all the time in simple projects)?

**Comment by hbopuri** [comment]
Noticed many performance issues with Visual Studio 2015 preview

1. Code definition navigation take 2-3 seconds
2. Code lens takes 2 seconds
3. Opening solution takes 1 minute (I have about 4 projects, each with max 20 classes)
4. Debugging will become completely impossible sometimes. 

Hope all these are being addressed.

[- HaBo Rocks](https://www.facebook.com/HaBoRocks)

**Comment by danquirk** [comment]
@hbopuri are you able to share the project where you're seeing these issues?

**Comment by hbopuri** [comment]
@danquirk I have the project on codeplex, you can download it from here  [PunchClock](https://punchclock.codeplex.com/SourceControl/latest)

One more issue: Scrolling the code file is also slow sometimes. I don't have these problems on VS 2013 Update 3.

[-HaBo Rocks](https://www.facebook.com/HaBoRocks)

**Comment by danquirk** [comment]
Great, thanks, that will be very helpful to try to track down what's going on.

**Comment by hbopuri** [comment]
@danquirk any update?

**Comment by paulvanbrenk** [comment]
I haven't had a chance to look at this yet, hopefully today.

**Comment by paulvanbrenk** [comment]
@hbopuri I'm probably looking in the wrong place, but the 'punchclock' project you referenced earlier doesn't have any TypeScript files.

**Comment by hbopuri** [comment]
@paulvanbrenk you are right, it doesn't have any type script, it was in general having this performance issues with that project and others. I posted my comment here as the title was relevant to the issue, "Slow navigation in Visual Studio 2015 Preview".

**Comment by RyanCavanaugh** [comment]
To clarify, this is the issue tracker / github site for TypeScript, not Visual Studio in general.

**Comment by hbopuri** [comment]
@RyanCavanaugh Just realized, thank you.

**Comment by mhegazy** [comment]
@hbopuri, @mbeckenbach, and @mrcrowl, can you try this on the latest [TypeScript release (1.4)](http://blogs.msdn.com/b/typescript/archive/2015/01/16/announcing-typescript-1-4.aspx?PageIndex=2#comments) and reopen if it still an issue?

**Comment by mrcrowl** [comment]
Just a quick update on this.  Our company is now switching to VS2015 RC, and I've found that the slow responsiveness for "Jump to definition", "Rename" etc is still there.  To answer your question @mhegazy, I believe this is now 1.4 by default?

**Comment by mrcrowl** [comment]
Also, not sure that I'll be allowed to share the project, but to give a sense of scale it has 683 .ts files, and about 80K line of actual typescript (excluding whitespace and brackets lines).

**Comment by mhegazy** [comment]
@mrcrowl sorry to bug you again, but can you upgrad to the latest: [TypeScript 1.5-beta](http://blogs.msdn.com/b/typescript/archive/2015/04/30/announcing-typescript-1-5-beta.aspx) and let us know what you are seeing?

**Comment by mrcrowl** [comment]
@mhegazy I was still experiencing this problem with TypeScript 1.5-beta + VS2015 RC . But all of the mentioned problems have disappeared in VS2015 RTM!  Well done guys :)

**Comment by mhegazy** [comment]
@mrcrowl thanks for the feedback! great to hear it is working better now.
