### ISSUE TITLE
Unexpected behaviour with option `rootDir`

### ISSUE THREAD

**Issue by shilch** [Microsoft/TypeScript#12221]
Hello!

I am trying to build a React Native App using TypeScript.

**TypeScript Version:**  `tsc -v` 2.0.9

**Code**
This is my tsconfig.json:
```json
{
    "compilerOptions": {
        "target": "es2015",
        "module": "es2015",
        "jsx": "react",
        "outDir": "build",
        "rootDir": "src",
        "allowSyntheticDefaultImports": true,
        "noImplicitAny": true,
        "experimentalDecorators": true,
        "preserveConstEnums": true,
        "allowJs": true,
        "sourceMap": true
    },
    "filesGlob": [
        "typings/index.d.ts",
        "src/**/*.ts",
        "src/**/*.tsx"
    ],
    "exclude": [
        "index.android.js",
        "index.ios.js",
        "build",
        "node_modules"
    ],
    "compileOnSave": false
}
```
Compiling .ts(x) files using `tsc` in project root.

**Expected behavior:**
```
MyAwesomeReactNativeApp/
├── src/
│   └── index.tsx
└── build/
    └── index.js
```
**Actual behavior:** 
Instead the whole project root files are getting compiled and copied to build.
```
MyAwesomeReactNativeApp/
├── src/
│   └── index.tsx
└── build/
    ├── src/
    │   └── index.js
    ├── index.android.js
    ├── index.ios.js
    └── __tests__/
```

I assume this is a bug? If not, what am I doing wrong here?

Thank you in advance!

**Comment by mhegazy** [comment]
first: `fileGlobs` is not a supported compiler option, use `include` instead. you also have `allowJs` true, which tells the compiler to suck in all the `.js` files in your project. 

You should be getting an error when you build using tsc that the some files are not under the `rootDir`.

Can you share a full repro with all the input files so we can debug it more.

**Comment by shilch** [comment]
Strange, I got it working now with this configuration:
```
{
    "compilerOptions": {
        "target": "es2015",
        "module": "es2015",
        "jsx": "react",
        "outDir": "artifacts",
        "rootDir": "src",
        "allowSyntheticDefaultImports": true,
        "noImplicitAny": true,
        "experimentalDecorators": true,
        "preserveConstEnums": true,
        "allowJs": false,
        "sourceMap": true
    },
    "compileOnSave": false
}
```

Could you clarify what was wrong with the first one?

**Comment by mhegazy** [comment]
In the first you had ` "allowJs": true,` . This tells the compiler to consume all `.js` files and not only `.ts` files.
