### ISSUE TITLE
Switch block: Cannot redeclare block-scoped variable

### ISSUE THREAD

**Issue by Artur-A** [Microsoft/TypeScript#12220]
**TypeScript Version:**  2.0.3, **target**: es5 or es6:
```ts
switch (s) {
		case 0:
			let v = "v.1";
			return v;

		case 1:
			let v = "v.2";
			return v;
	}

```

**Actual behavior:** 
`Cannot redeclare block-scoped variable 'v'`

__Playground__: [replay](http://www.typescriptlang.org/play/#src=%0Afunction%20foo(s%3A%20number)%20%7B%0A%09switch%20(s)%20%7B%0A%09%09case%200%3A%09%09%09%0A%09%09%09let%20v%20%3D%20%22v.1%22%3B%0A%09%09%09return%20v%3B%09%09%09%0A%09%09case%201%3A%0A%09%09%09let%20v%20%3D%20%22v.2%22%3B%0A%09%09%09return%20v%3B%0A%09%7D%0A%7D)

---
It seems like a variable scope mess, but most JavaScript engines will ignore second variable declaration `let` (no strict mode) and will run the output script correctly. 

Will it be good if every case statement outputs by default its own block `{}` in JS? The next code will be compiled with TSC:
```ts
switch (s) {
		case 0:
                {
			let v = "v.1";
			return v;
                }
		case 1:
               {
			let v = "v.2";
			return v;
               }
	}

```

**Comment by vladima** [comment]
current behavior is per [ES spec](https://tc39.github.io/ecma262/#sec-switch-statement-static-semantics-early-errors).  This code yields an error in Node 7, Chrome and Edge:
```js
function f(s) {
	switch (s) {
		case 0:
			let v = "v.1";
			return v;

		case 1:
			let v = "v.2";
			return v;
	}
}
```

**Comment by Artur-A** [comment]
Indeed, ES7 states it clearly, sorry for a wrong issue. 

BTW, I used `var` keyword to test in browsers and most of them know how to run it correctly, while `let` produces the error due the implementation of ES6+ specs.

**Comment by JoshMcCullough** [comment]
Is this intentionally part of the spec? Seems strange...

Note that wrapping the `case` contents in curly braces correctly defines the scope so this error doesn't occur.

**Comment by dspatoulas** [comment]
> Is this intentionally part of the spec? Seems strange...
> 
> Note that wrapping the `case` contents in curly braces correctly defines the scope so this error doesn't occur.

Thank you for pointing this out. I don't believe the compiler should care if there are braces around the case statement, and even though it's gross I was able to use this as a temporary solution.

**Comment by RyanCavanaugh** [comment]
This is literally what JavaScript does, why are people upvoting the 2018 comment 144 times? I'm lost.

![image](https://user-images.githubusercontent.com/6685088/205341272-01dcbdf6-699c-45a7-88b7-cca9c81e0e28.png)

**Comment by JoshMcCullough** [comment]
@RyanCavanaugh It may be what JS does, but is it "correct"? In your example, `case 1` ever access a variable declared in `case 0`? And after the switch, can any variable declared in any case be accessed? No. So then why would it not be okay to use the same-named variable in more than one `case` statement, aren't they each their own block (with or without curlies)? Furthermore, the fact that case 0/1 return directly means no other case or following code would ever be able to access the variables within the case statement, anyway.

**Comment by RyanCavanaugh** [comment]
>  It may be what JS does, but is it "correct"?

Yes.

> aren't they each their own block (with or without curlies)

Case labels don't form blocks (more on this in a second). A `return` statement doesn't make all prior code part of a block, either. Blocks are, well, blocks. Imagine if you wrote this code:
```
let m;
function fn(s) {
  switch (s) {
    case 0:
      let v = "v.1";
      if (Math.random() > 0.5) return;
    case 1:
      let v = "v.2";
      return;
  }
}
```
Now it's unambiguously the case that `v` (sometimes) gets declared twice in the same lexical scope.

> means no other case or following code would ever be able to access the variables within the case statement, anyway.

This is wrong. A demonstration is possible:
```ts
let m;
function fn(s) {
  switch (s) {
    case 3:
      m = () => v;
    case 0:
      let v = "v.1";
      return;

    case 1:
      // let v = "v.2";
      return;
  }
}
fn(3);
m();
```
The only way this code works is if `v` gets hoisted to the enclosing lexical scope, which it does.

**Comment by JoshMcCullough** [comment]
Your last example there is ridiculous. Not that you're ridiculous for writing it, but ridiculous that it works. E.g. why is `v ` ever set to "v.1"? That's the output of the `m()` call. But `case 0` should never have been hit. So JS pulls the declaration of `v` up (hoists it), when it _should not_. 

If you add curlies around your case bodies, you'll get a different result (at least with Node).

I think the point of this ticket is that Typescript *could* "correct" what seems to be a flaw in JS.

**Comment by RyanCavanaugh** [comment]
Changing the runtime semantics of JS to "correct" them has always been outside the scope of the project.
