### ISSUE TITLE
Go to Definition for a function takes you to the function keyword instead of the identifier

### ISSUE THREAD

**Issue by jramsay** [Microsoft/TypeScript#12230]
Go to Definition for a function takes you to the function keyword instead of the identifier

![gotodef](https://cloud.githubusercontent.com/assets/8161247/20282301/0c302ef8-aa69-11e6-97ee-97f49bed011a.JPG)

**Comment by mhegazy** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/12270
