### ISSUE TITLE
Intellisense space issue

### ISSUE THREAD

**Issue by waderyan** [Microsoft/TypeScript#12236]
_From @wallverb on November 10, 2016 14:25_

- VSCode Version: Code - Insiders 1.8.0-insider (a28dc215af3146d827d4b2f46a3191e2d487efde, 2016-11-10T07:05:12.185Z)
- OS Version: Darwin x64 16.1.0

---

Steps to Reproduce:

Typescript file:

```ts
test()

/**
 * This
 * 
 * is a test
 */
function test() {

}
```

Notice how popup shows 'isa test' when you hover `test()` in first line:

![image](https://cloud.githubusercontent.com/assets/1723815/20180212/879501c6-a727-11e6-8e0b-e8eeee4ab149.png)

_Copied from original issue: Microsoft/vscode#15300_

**Comment by waderyan** [comment]
Hmm.. I can't reproduce. Anything special about your project?

**Comment by waderyan** [comment]
_From @wallverb on November 12, 2016 0:53_

@waderyan 

I just started vscode - no project and created Typescript file

![7w5mmcamb0](https://cloud.githubusercontent.com/assets/1723815/20234383/5e2fe2f2-a848-11e6-9b9f-1031b9614935.gif)

Not sure if related - but I'm using Typescript `2.2.0-dev.20161111`

**Comment by waderyan** [comment]
Confirmed with 2.2.0-dev.20161111

**Comment by Knagis** [comment]
I have the same issue when using typescript language service from node. Typescript version 2.1.1

The first space after a newline is always removed in the comment that is returned by `signature.getDocumentationComment()`.

**Comment by Knagis** [comment]
Is there any update on this bug? In our case it prevents us from updating our build tools to the new version as we are using the language service extensively.

**Comment by waderyan** [comment]
@Knagis I have this tracked on our bug tracker. I do not believe any work has started in this area, but your comments are noted to make this a higher priority.

**Comment by Knagis** [comment]
Thank you for the update!

**Comment by Knagis** [comment]
I spent some more time on this, found the problem and fixed it. Pull request with the fix: https://github.com/Microsoft/TypeScript/pull/12858

**Comment by Knagis** [comment]
Working more with the new compiler I found additional related problem

```
/**
foo * bar
*/
var x = 1;
```

in this case the asterisk between `foo * bar` is omitted. I have modified the PR to include a fix for this as well.
