### ISSUE TITLE
Missing Super Call Code Fix Places Call on Wrong Line

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#12249]
**TypeScript Version:**  2.1.1

We're adding code fix support for TS to VSCode, and noticed that the code fix for missing super calls places the super call on the wrong line

**Code**

```ts
class A {};

class B extends A {
    constructor() {
        
    }
};
```

Trigger code fix on line 4 for missing super call in the constructor.

**Expected behavior:**
The super call is placed on the next line:

```ts
class A {};

class B extends A {
    constructor() {
        super();
    }
};
``` 

**Actual behavior:** 
Super call placed on same line as constructor:

```ts
class A {};

class B extends A {
    constructor() {super();
        
    }
};
```

![nov-14-2016 16-59-44](https://cloud.githubusercontent.com/assets/12821956/20289046/550a40dc-aa8c-11e6-823a-5ebefc8813d2.gif)

**Comment by mhegazy** [comment]
@paulvanbrenk can you take a look.

**Comment by DanielRosenwasser** [comment]
The problem is that the quick-fix expects that the host side will also request formatting on the region for which a quick fix was provided. @mhegazy is it a reasonable expectation for language service consumers?

**Comment by paulvanbrenk** [comment]
Yep, the expectation is that the host does the formatting after the edit is completed. The language service doesn't know the required indentation etc. for example in a script block.

**Comment by mjbvz** [comment]
@dbaeumer Just wanted to check that this is your understanding as well. If this is the case, VSCode will have to make two calls to the TS server, one for the code action itself and then another to format it. Does that sound correct? Will this introduce any complications for document management?

**Comment by dbaeumer** [comment]
How would the host know which region to best format. We can't only format the region of the edit. In the described case that would be `super();`. Formatting that will no introduce any line breaks. In addition if a code action will provide several edits what should the host do? Format the region spawned by the n edits.

IMO it would make more sense if we sent the formatting options when we request code actions and the tsserver produces the right result. The server already has an AST and knows what the smallest part to format is.

Can you please consider to reopen this.

**Comment by paulvanbrenk** [comment]
The behavior for multiple edits is up to the editor. For VS we collapse the edits for each document and format the entire changed span based on the lines. This is how the formatter does know to include a line break in the described case.

If we want to format in the tsserver we would need to parse the entire file after applying the fix, because at the level the fixes work we don't have versions for the files (so we can't incrementally parse).

By having the editor apply the fixes and ask for formatting, we can use the incremental parser, thus increasing performance significantly for large files.

@vladima to confirm

**Comment by dbaeumer** [comment]
I am not asking the tsserver to use the formatter. Couldn't the code that generates the edits know about the formatting settings and directly generate the right edits? I was always under the impression the TS AST has whitespace information. So when inserting the `super()` behind `constructor(){` it knows the indentation of that part of code and could generate an edit with `'\n\t\tsuper();`. This ensures that at the end we have the minimal changes to the document.

**Comment by paulvanbrenk** [comment]
Yeah, we talked about it some more... and for some quick fixes we will need to do that.

However we can't guarantee that future (external) quick fixes will do the right thing, so in general the safe assumption would be to format after applying the edits. This may in the future be a no-op.

**Comment by mhegazy** [comment]
Had a chat today with @dbaeumer and @mattbierner, we need to fix this for super quick fixes to avoid the code flickering much for users. VSCode will still call format after applying the quickfix though.

**Comment by dbaeumer** [comment]
@paulvanbrenk I think that even if we have external quick fixes they should be proper formatted. To my understanding these fixes would be plugins into the tsserver. If the tsserver provides the proper rewriting infrastructure then I think the tsserver can ensure proper formatting as well. 

I agree that this is not the case if quick fixes come in on a different path.

**Comment by aozgaa** [comment]
Looks like this was fixed when we started building AST's and doing formatting in the emit. Corresponding PR was https://github.com/Microsoft/TypeScript/commit/2b10611fbfb63c4fe24d865dc275fec016af003e.
