### ISSUE TITLE
Source maps are not relative to rootDirs

### ISSUE THREAD

**Issue by smhc** [Microsoft/TypeScript#12246]
**TypeScript Version:**  2.1.1

**Code**

```ts
// Given a tsconfig.json of:
{
    "compilerOptions": {
        "outDir": "build/ts/",
        "target": "ES5",
        "module": "commonjs",
        "sourceMap": true,
        "sourceRoot": "/",
        "rootDirs": [
            "src",
            "build/ts/src"
         ]
    },
    "include": [
        "src/**/*",
        "test/**/*"
    ]
}


and a project structure of:

./src
./src/other.ts
./src/app.ts
./tsconfig.json
./test
./test/spec.ts
./build
./build/ts
./build/ts/src
./build/ts/src/other.js
./build/ts/src/other.js.map
./build/ts/src/app.js
./build/ts/src/app.js.map
./build/ts/test
./build/ts/test/spec.js.map
./build/ts/test/spec.js

```

**Expected behavior:**
The source map path should be relative to 'build/ts/src' rather than relative to 'build/ts'.
i.e
```
{"version":3,"file":"app.js","sourceRoot":"/","sources":["app.ts"],"names":[],"mappings":";AAAA;IACI,OAAO,CAAC,GAAG,CAAC,KAAK,CAAC,CAAC;AACvB,CAAC;;AAFD,sBAEC"}
```

**Actual behavior:** 

Source map includes 'src/' in the path, even though the rootDir specifies build/ts/src as a root.
```
{"version":3,"file":"app.js","sourceRoot":"/","sources":["src/app.ts"],"names":[],"mappings":";AAAA;IACI,OAAO,CAAC,GAAG,CAAC,KAAK,CAAC,CAAC;AACvB,CAAC;;AAFD,sBAEC"}
```

The problem doesn't occur when there is no 'test' directory as part of the project as the generated files are placed in 'build/ts' rather than 'build/ts/src' and that can be used as the root instead.

I imagine this is a fairly common scenario. Outputting to a ts build directory with both source and test but using the 'src' as the root for the web application.

**Comment by errorx666** [comment]
I was confused about this, too.  Apparently `rootDirs` is unrelated to `rootDir`, and doesn't affect the output.  [[cite]](https://github.com/Microsoft/TypeScript/issues/8245#issuecomment-213159307)

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
