### ISSUE TITLE
Implicit Index don't work as expect with defined properties interface

### ISSUE THREAD

**Issue by Brooooooklyn** [Microsoft/TypeScript#12255]
**TypeScript Version:**  2.0.7 
**Code**

```ts
interface Table {
  as(name: string): Table
  createRow(value: Object): Row
  getName(): string
  [index: string]: Column
}

```

**Expected behavior:**
```ts
let a: Table
a['_id'] is Column
```
**Actual behavior:** 
[ts] Property 'createRow' of type '(value: Object) => Row' is not assignable to string index type 'Column'.

**Comment by ahejlsberg** [comment]
A string index signature introduces a constraint that must hold for *all* properties in a type. The compiler is pointing out that your method declarations introduce properties that aren't of type `Column` which is inconsistent with what you've declared in the string index signature.
