### ISSUE TITLE
Const enum elements cannot be used as literal type unless elements explicitly defined

### ISSUE THREAD

**Issue by benjaminRomano** [Microsoft/TypeScript#12257]
I'm trying to use an enum element as literal type as shown below. I get the following error: `Enum type 'Example' has members with initializers that are not literals.`

```ts
declare const enum Example {
    A,
    B
}

interface Test {
    prop: Example.A;
}
```

However, the following would work.

```ts
declare const enum Example {
    A=0,
    B=1
}

interface Test {
    prop: Example.A;
}
```

Why do I need to explicitly state the value of each element? Shouldn't `const enum` do this implicitly.

Note: The above examples are for `.d.ts` files. In `.ts` files, the code snippet at the top would work after removing the declare keyword.

**Comment by benjaminRomano** [comment]
Answered on stackoverflow here:
http://stackoverflow.com/questions/40600443/enum-type-enum-has-members-with-initializers-that-are-not-literals

**Comment by RyanCavanaugh** [comment]
See also http://stackoverflow.com/questions/28818849/how-do-the-different-enum-variants-work-in-typescript/
