### ISSUE TITLE
Object rest does not preserve enumerable Symbol keys

### ISSUE THREAD

**Issue by Kovensky** [Microsoft/TypeScript#12252]
Checked with the improved `__rest` helper from [this PR](https://github.com/Microsoft/TypeScript/pull/12248), but also applies to `master`.

The [`CopyDataProperties` operation](https://sebmarkbage.github.io/ecmascript-rest-spread/#AbstractOperations-CopyDataProperties) that is used to define object rest uses the `[[OwnPropertyKeys]]` operation, which does return `Symbol`s (https://tc39.github.io/ecma262/#sec-ordinaryownpropertykeys).

`for .. in`, however, [skips over `Symbol` keys](https://tc39.github.io/ecma262/#sec-enumerate-object-properties); a potential fix it so do a second copy loop with the result of `Object.getOwnPropertySymbols` if available.

Screenshot of a Chrome REPL session comparing `__rest`'s behavior with `Object.assign`, which is supposed to have (almost) the same [copying behavior](https://tc39.github.io/ecma262/#sec-object.assign): ![](http://puu.sh/sixWn/7d9a551d1f.png)

**Comment by sandersn** [comment]
The fix is available now. I folded it into #12248
