### ISSUE TITLE
Retain type guard info

### ISSUE THREAD

**Issue by electricessence** [Microsoft/TypeScript#12269]
Is a bit of a low value feature, but TS is getting smarter all the time so why not:

If you can assert that a value is the result of a type guard.  Why not keep that information for later?
```ts
function report(unknown:Object) {
	const t = typeof unknown;
	console.log(unknown, "is a",t);
	switch(t) // ** 
	{
		case "string":
			let s:string = unknown; // ** should compile without warning.
			// do string operations with s.
			break;

		// More similar cases...
	}
}
```

**Comment by wallverb** [comment]
https://github.com/Microsoft/TypeScript/issues/12184#issuecomment-260162839
