### ISSUE TITLE
Improve CodeFix "add missing super.call()"

### ISSUE THREAD

**Issue by angelozerr** [Microsoft/TypeScript#12264]
**TypeScript Version:**  2.1.1

**Actual behavior:** 

I have started to implement quick fix with Eclipse. Here a short demo:

![codefix](https://cloud.githubusercontent.com/assets/1932211/20303560/455870b4-ab2c-11e6-97f8-359230b3e28c.gif)

**Expected behavior:**

You can see 2 problems:

 * the codefix generates " **super();** although it should generates **super(a);**
 * the code fix doesn't respect the formatting.  **super();** should be generated in a new line with indentation.

**Comment by mhegazy** [comment]
For formatting see https://github.com/Microsoft/TypeScript/issues/12249. the expectation is the host will call format after applying the change.

for the argument, it is not clear what should be added here. so options either do not have a quick fix enabled if the base class constructor has required parameters, or add the same set of parameters to the derived constructor. i do not know what to do if the derived constructor has parameters already.
