### ISSUE TITLE
__awaiter with arrow functions for target = ES6/ES2015

### ISSUE THREAD

**Issue by arusakov** [Microsoft/TypeScript#12261]
In current implementation of `awaiterHelper` contains a lot of regular `function () { /* ... */ }`.
I think that for target ES6/ES2015 `awaiterHelper` can be rewritten with arrow functions (they are smaller and more performant).

If arrow functions allowed at this place, can I submit PR?

**Comment by gcnew** [comment]
Does a (maybe) slight performance improvement justify the added maintenance cost of diverging code paths? For me the answer is "no", especially considering this code can be swapped by custom helpers and is basically a temporary down-level solution.

**Comment by mhegazy** [comment]
After discussing this with the team it seems there is no clean way to do this without having to have 1. two different named functions, or 2. transformation running on the code itself. given the value gained here, the cost does not seem to match. closing.
