### ISSUE TITLE
Tag matching erratic in JSX javascript

### ISSUE THREAD

**Issue by waderyan** [Microsoft/TypeScript#12271]
_From @bgashler1 on November 9, 2016 20:42_

- VSCode Version:
- OS Version:

From @vvatikiotis:
https://github.com/Microsoft/vscode/issues/12402#issuecomment-259362863

Steps to Reproduce:

HTML tag matching works in my theme, highlighting matching tags, _when there are no JSX javascript expressions within the tags_. However, tag highlighting works erratically when there are JSX javascript expressions within 2 enclosing HTML tags.

Works as intended:
![image](https://cloud.githubusercontent.com/assets/535853/20132214/877d6024-a66a-11e6-9a04-a1a4be5206a9.png)

Doesn't work:
![image](https://cloud.githubusercontent.com/assets/535853/20132234/9f3d0f20-a66a-11e6-8c2e-377addd5f347.png)

_Copied from original issue: Microsoft/vscode#15264_

**Comment by waderyan** [comment]
@dbaeumer is matching tags provided by a language service (i.e. TS Server)? I can't see anything in the doc - http://code.visualstudio.com/docs/extensions/language-support

**Comment by waderyan** [comment]
_From @dbaeumer on November 15, 2016 1:26_

Yes, the TS request message is called `occurrences`

**Comment by mhegazy** [comment]
@bgashler1 can you share a project we can use?

the highlighting only works if the language service can tell what that thing you are hovering over is, and not text based. so i will need to look at a project to see what went wrong.

**Comment by bgashler1** [comment]
@mhegazy I think it would be good to reach out to @vvatikiotis since he is the first one to report this problem.

I could give you a [JS project](https://github.com/Microsoft/vscode-website/blob/32f22cd2fdb6ffccc66b77163bd956836daad898/src/public/client/Components/Extensions.js) with JSX in it, but I'm having a hard time getting any matching to work in JSX anymore (maybe something changed since then?).

**Comment by mhegazy** [comment]
@bgashler1 do not think i have access to that repo. feel free to email me the file contents.

**Comment by mjbvz** [comment]
I am seeing jsx tag matching working reliable with TS 2.7. Please open a new issue if you are still seeing some cases where it does not work
