### ISSUE TITLE
ES Spread properties caused compiling error

### ISSUE THREAD

**Issue by nagor** [Microsoft/TypeScript#12275]
**TypeScript Version:**  2.2.0-dev.20161114

**Code**

```ts
export type A = B & C & D;

export interface B {
    readonly enumTypeProperty: EnumType;
    readonly prop1: string;
}

export interface C {
    prop2: boolean;
}

export interface D {
    prop3: string;
}


export function getA(c: C, d: D): A {
        return {
            enumTypeProperty: EnumType.val1,
            prop1: 'foo',
            ...c,
            ...d
        };
    }

```

**Expected behavior:**
result = getA( { prop2: false }, { prop3: 'bar' } ); 
-> {
            enumTypeProperty: 1,
            prop1: 'foo',
            prop2: false,
            prop3: 'bar'
}

**Actual behavior:** 

Compile error: 

ReferenceError: name is not defined
    at visitFunctionExpression (*\node_modules\typescript\lib\tsc.js:39296:98)
    at visitorWorker (*\node_modules\typescript\lib\tsc.js:39181:28)
    at visitor (*\node_modules\typescript\lib\tsc.js:39156:24)
    at visitNode (*\node_modules\typescript\lib\tsc.js:36334:23)
    at Object.visitEachChild (*\node_modules\typescript\lib\tsc.js:36460:45)
    at visitor (*\node_modules\typescript\lib\tsc.js:39159:27)
    at visitNode (*\node_modules\typescript\lib\tsc.js:36334:23)
    at Object.visitEachChild (*\node_modules\typescript\lib\tsc.js:36454:44)
    at visitor (*\node_modules\typescript\lib\tsc.js:39159:27)
    at visitNode (*\node_modules\typescript\lib\tsc.js:36334:23)

**Comment by sandersn** [comment]
This looks like an error in emit for some module transform. @nagor, which module system are you using?

**Comment by sandersn** [comment]
I can't repro this just using the provided code. @nagor, can you provide your tsconfig?

**Comment by nagor** [comment]
```

**Comment by nagor** [comment]
@sandersn 
```
"compilerOptions": {
        "target": "ES5",
        "module": "amd",
        "declaration": false,
        "noEmitOnError": true,
        "noResolve": true,
        "noLib": true,
        "allowJs": false,
        "allowUnusedLabels": false,
        "noImplicitReturns": true,
        "allowUnreachableCode": false,
        "forceConsistentCasingInFileNames": true,
        "noImplicitAny": true,
        "removeComments": true,
        "preserveConstEnums": true,
        "moduleResolution": "classic",
        "sourceMap": false,
        "outDir": "../built",
        "noUnusedLocals": false,
        //"noErrorTruncation": true,
        "strictNullChecks": false,
        "noImplicitThis": true,
        "noUnusedParameters": false
    }
```

**Comment by sandersn** [comment]
I'm still not able to repro, even with the tsconfig. @nagor can you give me a link on github to a complete project with this failure? (or zipped somewhere else I guess).

Here's what I did:

```sh
$ cd src/test
$ tsc
error TS2318: Cannot find global type 'Array'.
error TS2318: Cannot find global type 'Boolean'.
error TS2318: Cannot find global type 'Function'.
error TS2318: Cannot find global type 'IArguments'.
error TS2318: Cannot find global type 'Number'.
error TS2318: Cannot find global type 'Object'.
error TS2318: Cannot find global type 'RegExp'.
error TS2318: Cannot find global type 'String'.
test.ts(4,32): error TS2304: Cannot find name 'EnumType'.
test.ts(19,31): error TS2304: Cannot find name 'EnumType'.
```

When I removed `noLib: true` from `tsconfig.json` and added `enum EnumType { val1 }` I no longer got any errors, but also no crash, and the emitted code looks fine. (I also changed `outDir: './bin'`)

**Comment by DanielRosenwasser** [comment]
Sorry to bug you @nagor, but have you been able to get a minimal repro for this bug?

**Comment by dmitrage** [comment]
This bug is already fixed by https://github.com/Microsoft/TypeScript/commit/ddcd22e4de4b604ee4ef532f48e3371fb4473352.
Error message is correct, there was variable `name` referenced instead `node.name`.

Error was in function expression visitor of ESNext transformer, so this is enough to reproduce (error on 20161114, ok since 20161117):
```
let x = function () { return { ...y } }
```
with tsconfig.json
```
{
	"compilerOptions": {
		"target": "es5"
	}
}
```

**Comment by nagor** [comment]
@sandersn @DanielRosenwasser Sorry, for being late. No,  I cannot zip the project: it is proprietary. 
@dmitrage That is great! Will try try mentioned version. Thanks

**Comment by mhegazy** [comment]
@nagor can you confirm that the issue has been fixed with the latest `typescript@next`.

**Comment by nagor** [comment]
@mhegazy yeah. It seems to work for me with 20161117. Thank you.
