### ISSUE TITLE
Go To Definition doesn't work for certain module patterns

### ISSUE THREAD

**Issue by klinquist** [Microsoft/TypeScript#12278]
@waderyan asked me to open up a bug in the TypeScript repo for my comment on this issue:
https://github.com/Microsoft/vscode/issues/15004

**TypeScript Version:**  VSCode 1.7.1

**Code**

myfile.js:
```
module.exports = function(baseUrl){
  this.apiCall = function(url, cb) {
     let fullUrl = baseUrl + url;
  };

  return this;
}
```

**Expected behavior:**

If I `let test = require('myfile')(baseUrl)`  then  `test.apiCall(url, cb)`,  I should be able to 'go to definition' on apiCall.

**Actual behavior:** 

Cannot go to definition.

**Comment by aluanhaddad** [comment]
You have to call `test`.

**Comment by klinquist** [comment]
When not in strict mode, I don't have to return a new constructor for my script to work..

**Comment by aluanhaddad** [comment]
Irregardless you need to call the function.

**Comment by klinquist** [comment]
Sorry - I *do* call the function (I just updated my test code).   Please try it - you'll see that Go To Definition does not work.

**Comment by aluanhaddad** [comment]
Indeed it does not work.
The following works as expected
```js
module.exports = function (baseUrl) {
  return {
      apiCall: function (url, cb) {
        let fullUrl = baseUrl + url;
      }
  };
};
```
The issue is that `this` is typed as `any` throughout the original function. The actual value of `this` will vary at runtime depending on the context in which the code is called.

**Comment by klinquist** [comment]
Would a `let self = this`,  then returning `self` make it work?

**Comment by mhegazy** [comment]
> Would a let self = this, then returning self make it work?

no. the system currently does not track assignments to `this` as property declarations. i.e. `this.apiCall` is not treated as a declaration for a new property called `apiCall` on `this`. this is true if you alias `this` as well (`self = this`). 

you could however, enhance the experience by using JSDoc comments:

```js
/**
 *  @return {{apiCall: (url, cb)=> string;}}
 */
module.exports = function (baseUrl) {
...
}
```

**Comment by abgivant** [comment]
I use a similar module pattern in an application I'm working on, and the lack of IntelliSense for those has been an issue for me as well.

Mine follow this basic pattern:
```javascript
module.exports = function(x, y, z) {
  var exports = {};
  exports.method = function() {
    // Something that might use x, y, or z
  };
  return exports;
}
````

Would it be possible to do something like include an option in the jsconfig.json file to specify a property name or list of names to track when determining module exports?

Maybe something like this?
```javascript
{
  "moduleOptions": {
    "exportProperty": ["exports", "this"]
  }
}
```

**Comment by mhegazy** [comment]
@abgivant, this pattern is actually an easier one to support, we already have plans to do so on the future. it is a general construction patter that is common in JS.
the `this` one is a bit more tricky though.

**Comment by abgivant** [comment]
@mhegazy Ah cool. Is that part of the "expando" discussion, or is there a more specific feature in the works for things like that?

**Comment by waderyan** [comment]
Let's move the latter discussion to the new issue #12416
