### ISSUE TITLE
Snapshot nightlies during the night

### ISSUE THREAD

**Issue by weswigham** [Microsoft/TypeScript#12283]
Nightlies get published around 11am pacific time, judging by the publication timestamps in npm, which is a little odd because it can capture a small part of a day's work for most of the team (most of the team is in the pacific time zone, so most PRs get merged between 9am and 5pm, pacific). IMO, it would make more sense to actually snapshot and publish the nightlies overnight, when [contributions are much less likely](https://github.com/Microsoft/TypeScript/graphs/punch-card) - between midnight and 1am pacific time, perhaps. 

For example, #12259 and #12258 I think made the cutoff for the previous nightly (they were merged around 11am on the dot, so it's iffy), but everything else merged during that day's work day (#12274, #12276, #12280, #12251, #12248) did not, and is waiting for the next nightly.

**Comment by mhegazy** [comment]
nightly packages should be published around midnight (npm info output):

```cmd
     '2.1.0-dev.20161104': '2016-11-04T06:09:19.231Z',
     '2.1.0-dev.20161105': '2016-11-05T06:09:16.650Z',
     '2.1.0-dev.20161106': '2016-11-06T06:09:03.420Z',
     '2.1.0-dev.20161107': '2016-11-07T07:08:47.944Z',
     '2.1.0-dev.20161108': '2016-11-08T07:09:02.046Z',
     '2.1.0-dev.20161109': '2016-11-09T07:09:28.354Z',
     '2.1.0-dev.20161110': '2016-11-10T07:08:50.401Z',
     '2.2.0-dev.20161111': '2016-11-11T07:09:04.938Z',
     '2.2.0-dev.20161112': '2016-11-12T07:09:05.107Z',
     '2.2.0-dev.20161113': '2016-11-13T07:09:01.074Z',
     '2.2.0-dev.20161114': '2016-11-14T07:08:38.122Z',
     '2.2.0-dev.20161115': '2016-11-15T07:08:43.911Z',
```

so it last night it went out 12:43 am.

**Comment by weswigham** [comment]
@mhegazy I am a bad - I was 12 hours off when reading the timestamps.
