### ISSUE TITLE
in namespace can't use outside same name variable.

### ISSUE THREAD

**Issue by Treri** [Microsoft/TypeScript#12288]
**TypeScript Version:**  2.0.6(VSCode 1.7.1 included)

**Code**
test.ts
```ts
const abc = {};

function foo(){}

namespace foo {
  export let abc = abc; // <- [ts] Block-scoped variable 'abc' used before its declaration.
}

foo.abc = abc; // <- here is the right reference to `const abc = {}`
```

**Expected behavior:**

In namespace foo, I can assign outside abc to namespace foo

**Actual behavior:** 

![image](https://cloud.githubusercontent.com/assets/2631733/20334061/384b4b28-abf2-11e6-9904-c72a530b6ae2.png)

Error: `[ts] Block-scoped variable 'abc' used before its declaration.`

And if I use `foo.abc = abc`, the right hand abc is correct reference for `const abc = {}`

**Comment by Treri** [comment]
Is it designed?

The only way to do it right now is

```ts
const abc = {}
function foo(){}

namespace foo {
  export let abc;
  export let def = 'def';
}

foo.abc = abc;
```

But it's not clear. I don't know why `def` can define and assign together, but `abc` can't.

**Comment by jwbay** [comment]
The behavior reproduces with just this:

```
let abc = abc;
```

The problem in your full example is `let abc = ...` creates a new variable in the scope of `foo`. It shadows, or overrides, the abc from the outer scope. So it thinks you're trying to initialize a variable with itself. It has no idea there's another abc you're trying to reference above it.

Initializing a value with itself is allowed with var, yielding undefined, but throws an error with blocked-scoped variables, both in the compiler and in a JavaScript runtime.

**Comment by Treri** [comment]
@jwbay  I just want to do this in javascript

```js
export let abc = {};

function foo(){}

foo.abc = abc;

export foo;
```

If I do not use namepspace in typescript, the type chcker will throw a error/warning:
 `[ts] Property 'abc' does not exist on type 'typeof foo'.`

**Comment by Treri** [comment]
And a new problem

```ts
const abc = {};

function foo(){}

namespace foo {
  export let abc;
  export let def = 'def';
}

foo.abc = abc;
```

will emit javascript

```js
var abc = {};
function foo() { }
var foo;
(function (foo) {
    foo.def = 'def';
})(foo || (foo = {}));
foo.abc = abc;
```

ESLint throw the error `[eslint] 'foo' is already defined. (no-redeclare)`. Why function `foo` and var `foo` both emited here?

**Comment by Treri** [comment]
A further more question.

If I want to assign a property to a function, but the function is not top level. Then the namespace usage will lead to error `[ts] A namespace declaration is only allowed in a namespace or module.`.

How can I assign a property to a function in this condition?

```ts
function a(m, n){
  function b(p){
    b.p = p
  }
  b.m = m;

  return b;
}
```

**Comment by jwbay** [comment]
1. Why do the local variable and property on the function need to be the same name? That's the source of your problems with the namespace approach.
2. I wouldn't try to run a linter on the JavaScript output of the TypeScript compiler. It does some weird things. Use https://github.com/palantir/tslint/ on your TypeScript files instead.
3. I believe the only way to attach properties to functions and keep type safety is to use declaration merging, which is your namespace approach, or leverage the fact that types can have call signatures you can attach other properties to:
```ts
interface callable {
    (x: number): number;
    property: string;
}

let bar: callable;

bar(0); //ok
bar.property = 'x'; //ok
```

If you just want the property on the function and don't care about accessing it later with type safety, you can cast to any and attach it.
```ts
function foo() { }
(foo as any).asdf = 42;
```

To your last example, this should be close. It uses a type with a call signature.

```ts
function a<M>(m: M) {
    type retVal<M> = {
        (p: any): void;
        p?: any;
        m: M
    }

    let b = function (p) {
        b.p = p;
    } as retVal<M>;

    b.m = m;
    return b;
}

const foo = a(42);

foo('');
foo.p === '';
foo.m === 42;

```

**Comment by Treri** [comment]
Thanks very much for your patient and detailed answer help me to understand TypeScript more. 😄
