### ISSUE TITLE
Cannot `await` on interfaces extending `Promise<any>` in TypeScript 2.1 RC

### ISSUE THREAD

**Issue by thomasboyt** [Microsoft/TypeScript#12292]
For context: I ran into this bug using [Knex](http://knexjs.org/) and its type definition in TypeScript 2.1 RC. Knex's type definitions use [an extended `Promise` interface](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/knex/knex.d.ts#L321) for every value returned from a query, to allow for further chaining. Unfortunately, it looks like async/await in TypeScript does not support this.

I found several references to fixed issues and regressions in prior versions of TypeScript, but could not find an open issue for the current version. Apologies if this is a duplicate issue.

**TypeScript Version:**  `typescript@rc` (2.1.1)

**Code**

`main.ts`:

```ts
interface PromiseExtender extends Promise<any> {
}

function getPromiseExtender(): PromiseExtender {
  return new Promise((resolve, reject) => {});
}

async function main() {
  await getPromiseExtender();  // error: Operand for 'await' does not have a valid callable 'then' member.
}
```

`tsconfig.json`:

```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "es6", "es2015.promise", "es2015.iterable", "scripthost"],
    "module": "commonjs",
    "sourceMap": true,
    "strictNullChecks": true,
    "noImplicitAny": true
  }
}
```

Runnable test case: https://github.com/thomasboyt/typescript-await-promise-bug-test-case

**Expected behavior:** TypeScript allows `await`ing interfaces extending `Promise<any>`.

**Actual behavior:** TypeScript displays the error `Operand for 'await' does not have a valid callable 'then' member.`.

My current workaround for this is to just `await (promiseExtendingObject as any)`, so it's not the end of the world. Hopefully can be fixed before 2.1 is released, though :)

**Comment by Kovensky** [comment]
Would `interface PromiseExtender<T> extends Promise<T> {}` work?

**Comment by isiahmeadows** [comment]
@Kovensky It shouldn't need to - ES `async`/`await` operates on thenables, not just promises.

**Comment by thomasboyt** [comment]
Ran into another library with this issue: `supertest-as-promised`, which adds a `then` method to an existing interface (with the slight indirection of going through Bluebird, since that's the underlying promise implementation that library uses: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/supertest-as-promised/supertest-as-promised.d.ts).

**Comment by itaysabato** [comment]
Same deal with [superagent](https://github.com/itaysabato/DefinitelyTyped/blob/36d40a63a05b5cb3413737fbdf7c9a2a26f211fd/superagent/superagent.d.ts#L84).
It doesn't seem like it matters what is used as the generic parameter...

**Comment by rbuckton** [comment]
Fixed in #12743

**Comment by mhegazy** [comment]
Fix should be in typescript@next later tonight. Please give it a try and let us know if you are still running into issues.

**Comment by isiahmeadows** [comment]
Will it make the final release of 2.1, a patch release, or 2.2?

**Comment by itaysabato** [comment]
@mhegazy seems to be fine now, thanks.
