### ISSUE TITLE
selection api miss the modify method .

### ISSUE THREAD

**Issue by zhengrenzhe** [Microsoft/TypeScript#12296]
**TypeScript Version:**  2.0.10

**Code**

```ts
let sel = window.getSelection();
sel.modify('extend', 'backward', 'word');
```

**Expected behavior:**
No errors when compile

**Actual behavior:** 
Print error message: `Property 'modify' does not exist on type 'Selection'.`

The `modify` method is not in w3c document. but Chrome, Safari, Firefox all adds it in the `selection` object.

**Comment by RyanCavanaugh** [comment]
Nonstandard APIs are intentionally not in lib.d.ts. You can augment the interface if you want:
```ts
interface Selection {
    modify(s: string, t: string, u: string): void;
}
```

**Comment by zhengrenzhe** [comment]
thanks.
