### ISSUE TITLE
Type narrowing with interface inheritance

### ISSUE THREAD

**Issue by HolgerJeromin** [Microsoft/TypeScript#12295]
**TypeScript Version:**  2.0.3
This is related to discriminated unions, but with interface inheritance.

I get a SyncCommand via XHR and need to do different stuff depending on the command.
Right now i need a Type assertions for that, but my interface definition holds all information already.

**Code**
```ts
export interface SyncCmd {
	name: string;
}
export interface SyncCmdFoo extends SyncCmd {
	name: 'Foo';
	contentFoo: string;
}
// In real my code the command comes from XHR
const command: SyncCmd = {name: 'Foo', contentFoo: 'hello'};
switch (command.name) {
	case 'Foo': 
		alert(command.contentFoo);
		break;
	default:
		break;
}
```

**Expected behavior:**
Inside the 'Foo' case the type should be narrowed to SyncCmdFoo.

**Comment by kitsonk** [comment]
That isn't narrowing, that is "magical" widening... You asserted `command` was of type `SyncCmd` therefore TypeScript is taking your word for it and cannot "magically" widen to something else.  If you tell TypeScript it could be `SyncCmd | SyncCmdFoo` it will then [narrow the type appropriately](http://www.typescriptlang.org/play/#src=export%20interface%20SyncCmd%20%7B%0A%09name%3A%20string%3B%0A%7D%0Aexport%20interface%20SyncCmdFoo%20extends%20SyncCmd%20%7B%0A%09name%3A%20'Foo'%3B%0A%09contentFoo%3A%20string%3B%0A%7D%0A%2F%2F%20In%20real%20my%20code%20the%20command%20comes%20from%20XHR%0Aconst%20command%3A%20SyncCmd%20%7C%20SyncCmdFoo%20%3D%20%7Bname%3A%20'Foo'%2C%20contentFoo%3A%20'hello'%7D%3B%0Aswitch%20(command.name)%20%7B%0A%09case%20'Foo'%3A%20%0A%09%09alert(command.contentFoo)%3B%0A%09%09break%3B%0A%09default%3A%0A%09%09break%3B%0A%7D%0A):

```ts
export interface SyncCmd {
	name: string;
}
export interface SyncCmdFoo extends SyncCmd {
	name: 'Foo';
	contentFoo: string;
}
// You need to tell TypeScript the widest set of types, so it can then narrow them
const command: SyncCmd | SyncCmdFoo = {name: 'Foo', contentFoo: 'hello'};
switch (command.name) {
	case 'Foo': 
		alert(command.contentFoo);
		break;
	default:
		break;
}
```

**Comment by HolgerJeromin** [comment]
OK, understood. Thanks.
It would be nice to have a pseudo type "all inherit types from SyncCmd". 
But probably this must (and should?) be maintained by myself.

**Comment by wallverb** [comment]
@kitsonk @HolgerJeromin it will not work in latest TS - command will not be narrowed to `SyncCmdFoo`

```ts
const command: SyncCmd | SyncCmdFoo = {name: 'Foo', contentFoo: 'hello'};
switch (command.name) {  // <- Type: SyncCmd | SyncCmdFoo, at playground type: SyncCmdFoo
    case 'Foo': 
        alert(command.contentFoo);  // <- Type: SyncCmd | SyncCmdFoo
        break;
    default:
        break;
}
```

We would need to have ability to provide: 
```ts
export interface SyncCmd {
    name: string - 'Foo';
}
```

for it to work

Take a look here: https://github.com/Microsoft/TypeScript/issues/12182 and https://github.com/Microsoft/TypeScript/issues/7993

**Comment by HolgerJeromin** [comment]
I removed the name:string from the base interface and all works as expected

**Comment by InExtremaRes** [comment]
@kitsonk 
I know this is a little old, but I can't figure out how then is implemented in [src/server/session.ts L1771](https://github.com/Microsoft/TypeScript/blob/6d051f82fd24749c84eff8d0d269167412251a9b/src/server/session.ts#L1771).

There the _map_ has value type `(request: protocol.Request) => HandlerResponse`, but then every value is a function whose parameter is a type extending `Request` (an specific request, like `OpenExternalProjectRequest`); here are `Request` and its _subtypes_  [src/server/protocol.ts L137](https://github.com/Microsoft/TypeScript/blob/477cba539b1da025c3fb27fe6aa99a7772f7fd29/src/server/protocol.ts#L137).

Am I misunderstanding? I guess it needs to narrow based on `Request.command` to an specific Request interface, but maybe there is another implementation in the code i'm not seeing, maybe some explicit type assertion...
