### ISSUE TITLE
__rest helper is included in only one file when using commonjs

### ISSUE THREAD

**Issue by cri5ti** [Microsoft/TypeScript#12299]
When using `commonjs` modules, the __rest helper is included in only one file, instead of all the files that uses the rest destructuring pattern.

**TypeScript Version:**  nightly (2.2.0-dev.20161116)

**Example:**
A [self contained](https://github.com/Microsoft/TypeScript/files/594452/bugtest.zip) example is attached:
 - build/mod1.js contains __rest and __extends helper
 - build/mod2.js contains only __extends helper

PS: Massive thank you @sandersn for the work on this feature!

**Comment by sandersn** [comment]
I think @rbuckton's recent refactoring of the destructuring code fixed this because this no longer repros. 

Helpers are handled by their respective transforms and the whole system holds together much better overall.
