### ISSUE TITLE
[Errors] error recovery with illegal modifiers inside function bodies

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#123]
```TypeScript
export function foo() {
       export var x = this;    
}
```
 
Expected: 

!!! Modifiers cannot appear here.

Actual: 

```TypeScript
    export function foo() {
       export var x = this;
!!! Statement expected.
    }
!!! Declaration or statement expected.
```

See also:

tests/cases/conformance/parser/ecmascript5/ErrorRecovery/parserModifierOnStatementInBlock2.ts

tests/cases/conformance/parser/ecmascript5/ErrorRecovery/parserModifierOnStatementInBlock3.ts

tests/cases/conformance/parser/ecmascript5/ErrorRecovery/parserModifierOnStatementInBlock4.ts

**Comment by DanielRosenwasser** [comment]
This appears to be fixed
