### ISSUE TITLE
EmitResult.emittedFiles list returned from ts.program.emit() contains relative and full path names of emitted files

### ISSUE THREAD

**Issue by ToddThomson** [Microsoft/TypeScript#12303]
**TypeScript Version:**  2.0.9

**Expected behavior:**

EmitResult.emittedFiles should use sourceFile.path rather than sourceFile.fileName as the fileName can be relative or canonical.

File names resolved from references within root files are always canonical. Root file names are always relative.

Each string/name in the emitFiles list should always contain the absolute path of where the output was written. The problem line ( as I see it is ):
```
emitOutputFilePathWithoutExtension = ts.removeFileExtension(sourceFile.fileName);
```
from
```
function getOwnEmitOutputFilePath(sourceFile, host, extension) {
        var compilerOptions = host.getCompilerOptions();
        var emitOutputFilePathWithoutExtension;
        if (compilerOptions.outDir) {
            emitOutputFilePathWithoutExtension = ts.removeFileExtension(getSourceFilePathInNewDir(sourceFile, host, compilerOptions.outDir));
        }
        else {
            emitOutputFilePathWithoutExtension = ts.removeFileExtension(sourceFile.fileName);
        }
        return emitOutputFilePathWithoutExtension + extension;
    }
```

**Comment by ToddThomson** [comment]
The compilerOption listEmittedFiles is "internal" as it most likely was meant for use with tsc ( ??? I don't know the history here ). However, this option controls whether the emitter generates the list of files output when calling program.emit(). I really don't care if listEmittedFiles is marked as internal, but having it be internal and having an effect on a non-internal property in EmitResult is questionable to me. Just my 2 cents worth.

**Comment by mhegazy** [comment]
I am not sure i see the issue here. If this is about using the API and getting some mixed path results, then my recommendation here is if you are using the API to always provide absolute file names.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Comment by dsherret** [comment]
@mhegazy I think `emittedFiles` on `ts.EmitResult` should be made internal. The only way to populate that is to provide the internal `listEmittedFiles` on `ts.CompilerOptions` (see [this line](https://github.com/Microsoft/TypeScript/blob/194c2bc2ca806f5f1014113329e33207f683037c/src/compiler/emitter.ts#L81)).

So either both should be internal or both should be public.
