### ISSUE TITLE
Proposal: Allow trailing commas in function argument list

### ISSUE THREAD

**Issue by streamich** [Microsoft/TypeScript#12306]
TypeScript allows trailing commas in object definitions:

```ts
var obj = {
    key: 'value',
};
```

Proposal: Allow trailing commas in function argument list:

```ts
someFunction(argument,);
```

Why? Trailing commas in object definitions are great for convenience when editing lists:

```ts
{
    key1: 'val1',
    key2: 'val2',
    key3: 'val3',
};
```

Same is with functions, consider usage of Virtual Hypertext functions:

```ts
return (
    h('div', null,
        h('span', null, 'span 1'),
        h('span', null, 'span 1'),
        h('span', null, 'span 1'),
    )
);
```

**Comment by RyanCavanaugh** [comment]
#8942 ?

**Comment by RyanCavanaugh** [comment]
What am I missing here? If you try this on the Playground it already works. http://www.typescriptlang.org/play/#src=console.log(1%2C%202%2C%20)%3B%0D%0A

**Comment by streamich** [comment]
I get this in v1.8

    TS1009:Trailing comma not allowed.

**Comment by aluanhaddad** [comment]
That's because jetbrains uses their own language service. In IntelliJ IDEA there's a setting to use the type script language service instead. I would definitely suggest that you investigate and see if this option is available in Webstorm as well.
