### ISSUE TITLE
Type inference error in compiler version 1.3.0.0

### ISSUE THREAD

**Issue by lord-saumagen** [Microsoft/TypeScript#1231]
It appears that the type inference degraded with the release of the TypeScript compiler version 1.3.0.0.
I have a project which compiles successfully when using the TypeScript compiler in version 1.0.3.0. Since I switched to version 1.3.0.0 I get errors in one function which I can't resolve. For some reason the compiler is not longer available to infer the right type. 

> Error	4	Type 'Enumerable<{ Key: IProduct; RoomConcat: string; }>' is not assignable to type 'Enumerable<{ Key: string; RoomConcat: string; }>':
>   Type '{ Key: IProduct; RoomConcat: string; }' is not assignable to type '{ Key: string; RoomConcat: string; }':
>     Types of property 'Key' are incompatible:
>       Type 'IProduct' is not assignable to type 'string'.	D:\PROJECTS\TS_solution_2.0\TS\Test\TS_Linq_Extensions_test.ts	712	5	TS

That error doesn't occur when I use the TypeScript compiler in version 1.0.3.0. As far as I can see, the compiler is wrong at this point. The function where the error occurs belongs to a project which implements the default LINQ extensions in TypeScript. The function is the "groupBy" function which is several times overloaded. Since the error occurs only in that specific function in one specific overload, I'm not able to present a simple code snippet which reproduces the error. 

Despite the fact that the compiler complains about the wrong type, a subsequent call to compile the source code will pass without any error. But when I open the file in an editor window in visual studio, the function is still marked as erroneous. 

Here is a link to some screen shots which show that strange behavior.

https://drive.google.com/folderview?id=0B5T7PycC4CqCZ1RNamU3VmZFbVk&usp=sharing

It would be very nice if somebody could take a look at that error and tell me what has changed in type inference from version 1.0.3.0 to version 1.3.0.0 of the TypeScript compiler.

The project is public available at:

https://github.com/lord-saumagen/TS

The function which generates the error is the "groupBy" function, but only when using the overload which offers a "resultSelector". You can find the function call at line 712 in the "TS/Test/TS\_Linq\_Extensions_test.ts" file.

The test itself runs without any error, once the TypeScript files are compiled. 
 
Since the function is good enough for the 1.0.3.0 compiler and the tests give the expected results, I'm pretty sure that the error has it's origin in the compiler and is not a coding error. It would be great if somebody can confirm that, or at leas give me a hint where I made a wrong assumption.

**Comment by mhegazy** [comment]
looking at the cost and complexity of fixing this issue vs the scenarios it enables, I am marking this as won't fix for now.
