### ISSUE TITLE
`for..in` variable does not have the type `keyof T`

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#12314]
```ts
function set<T, K extends keyof T>(obj: T, key: K, value: T[K]) {
    obj[key] = value;
}

var O = { a: "string" };

// var k: keyof typeof O;
for (var k in O) {
    set(O, k, "another"); // string is not assignable to "a"
}
```

**Comment by ahejlsberg** [comment]
I have my doubts about this one. In `for (var k in x)` where `x` is of some type `T`, it is only safe to say that `k` is of type `keyof T` when the *exact* type of `x` is `T`. If the actual type of `x` is a subtype of `T`, as is permitted by our assignment compatibility rules, you will see values in `k` that are not of type `keyof T`.

The same argument holds for the built-in `Object.keys()` method.
