### ISSUE TITLE
Indexing constraints on mapped type should use the constraint type 

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#12315]
when indexing into a mapped type using a key that is constraint to the same constraint type, indexing should be allowed. consider:

```ts
type Optional<T> = {[K in keyof T]?: T[K]}; 

function setFromOther<T, K extends keyof T>(obj: T, k: K, other: Optional<T>) {
    obj[k] = other[k];  // K is not constraint to keyof Optional<T>
}
```

**Comment by ahejlsberg** [comment]
This is fixed by #12351. However, in `--strictNullChecks` mode the example above still errors because `T[K] | undefined` is not assignable to `T[K]`, but that's to be expected.
