### ISSUE TITLE
Difference between untyped module and ambient shorthand module used as superclass

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#12329]
**TypeScript Version:**   nightly (2.2.0-dev.20161117)

**Code**

```ts
// @Filename: /node_modules/foo/index.js
This file is not read.

// @Filename: /declarations.d.ts
declare module "bar";

// @Filename: /a.ts
import Foo from "foo";
import Bar from "bar";

class A extends Foo { }

class B extends Bar { }

declare var x: any;
class C extends x {}

const y = Foo;
class D extends y {}
```

**Expected behavior:**

No errors? All errors?

**Actual behavior:**

Classes `B` and `C` fail with `error TS2507: Type 'any' is not a constructor function type.`

**Comment by mhegazy** [comment]
they should all be errors. we really do not know how to handle a class extending from `any`.
