### ISSUE TITLE
__extends, __awaiter, __generator, ... Is there any way we can have these distributed as their own modules?

### ISSUE THREAD

**Issue by electricessence** [Microsoft/TypeScript#12325]
I'm already doing this, but obviously, if the code changes, then I have to completely redo each module.
Not suggesting the right way to do this, but it would be nice if it was a simple npm update.

It would also be nice if these modules were created in TypeScript from the beginning or at least exposed as such.  I'd be happy if there was even a repo I could grab their TS from.

**Comment by alitaheri** [comment]
Are you referring to https://github.com/Microsoft/tslib ?

**Comment by sanex3339** [comment]
Main problem in tslib is what if i care about code size, i can't import only `extends` helper without adding code of all other helpers into the output bundle (webpack).

**Comment by electricessence** [comment]
@alitaheri Yes and no.  I didn't know about those.  So that helps immensely.
But I would almost prefer the TypeScript source/version of these (not that it's necessary).

@sanex3339 Yes! That is part of my frustration.  But I think at least having a valid source to pull from.

**Comment by sanex3339** [comment]
Some helpers you can found in my repo
https://github.com/sanex3339/typescript-extends
https://github.com/sanex3339/typescript-param
https://github.com/sanex3339/typescript-metadata
https://github.com/sanex3339/typescript-decorate
https://github.com/sanex3339/typescript-awaiter
https://github.com/sanex3339/typescript-generator

**Comment by electricessence** [comment]
Ok so this just got even more interesting.
Is there a way to target ES5 vs ES6 at runtime?  Or even better, a compiler directive?

**Comment by electricessence** [comment]
Because now, all my code imports ```__extends``` but doesn't need it for my es6 distribution.

**Comment by electricessence** [comment]
@alitaheri I wish there was a TypeScript source for these. :(

**Comment by electricessence** [comment]
@sanex3339 
This is what I had to do to get rid of them in ES6:
https://github.com/electricessence/gulp-typescript-helper/blob/master/source/BuildHelper.ts#L36-L42

**Comment by mhegazy** [comment]
Ar you using [`--importHelpers`](https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#support-for-external-helpers-library-tslib)?

**Comment by electricessence** [comment]
@mhegazy wow. Ok.  I think I understand.  Lemme see if that works...

**Comment by electricessence** [comment]
@mhegazy.  I had trouble getting this work.  Do I need to turn off noEmitHelpers?

**Comment by mhegazy** [comment]
no, though it probably should be flagged as a invalid flag combination.

here is a sample;

```sh
c:\test\sandbox10>type b.ts
declare var o : {a:number};
export var x = {...o};

c:\test\sandbox10>tsc --v
Version 2.2.0-dev.20161116

c:\test\sandbox10>tsc --importHelpers b.ts

c:\test\sandbox10>type b.js
"use strict";
var tslib_1 = require("tslib");
exports.x = __assign({}, o);
```

**Comment by mhegazy** [comment]
`typescript@2.2.0-dev.20161116` has that broken. so you would want to try with `typescript@typescript@2.2.0-dev.20161117`

**Comment by electricessence** [comment]
@mhegazy I'm using tsconfig.json. Will that affect it?

**Comment by mhegazy** [comment]
this should be working as intended in the latest nightly build. if you are running into issues please post more details about how i can reproduce it locally.
