### ISSUE TITLE
Read-only doesn't seem to work for Float32Array

### ISSUE THREAD

**Issue by 10098** [Microsoft/TypeScript#12324]
**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)

**Code**

```ts
class test {
    readonly x: Float32Array;
    constructor() { this.x = new Float32Array([0, 2, 1]); }
}

let a = new test();
a.x[0] = 11;
document.write(a.x[0].toString())


```

**Expected behavior:**
In my opinion, this code should fail to  compile.
Or, seeing as we have a "ReadonlyArray" interface, there should be something similar for creating read-only Float32Array, Uint8Array, etc.

**Actual behavior:**
The code compiles successfully.

**Comment by DickvdBrink** [comment]
`readonly` applies to `x` so you can't assign to x but it doesn't make content of the `Float32Array` readonly

**Comment by 10098** [comment]
That seems like counter-intuitive behavior to me. Shouldn't the point of readonly be to prevent any changes to the field?

**Comment by RyanCavanaugh** [comment]
`readonly` applies to the reference, not the referent, i.e. http://stackoverflow.com/questions/890535/what-is-the-difference-between-char-const-and-const-char

**Comment by 10098** [comment]
Is it possible to at least update the documentation to better reflect that? It wasn't obvious to me from reading either "TypeScript Deep Dive" (https://basarat.gitbooks.io/typescript/content/docs/types/readonly.html), or the official docs (https://www.typescriptlang.org/docs/handbook/interfaces.html).

In particular, "TypeScript Deep Dive" has this to say:

> TypeScript's type system allows you to mark individual properties on an interface as readonly. This allows you to work in a functional way (unexpected mutation is bad)

which is completely misleading: you still can mutate "readonly" fields

The official docs state:

> Some properties should only be modifiable when an object is first created. You can specify this by putting readonly before the name of the property

which, again, doesn't make it clear that you *can* actually modify a readonly property

Overall, I feel like something that guarantees the immutability of the *referent*, not the reference, would be a more valuable feature to have in the language.
