### ISSUE TITLE
tsc will attempt to compile source files in 'node_modules' when it shouldn't

### ISSUE THREAD

**Issue by JustASquid** [Microsoft/TypeScript#12320]
**TypeScript Version:**  2.0.8

It appears that tsc will attempt to compile source files in `node_modules` that are part of modules being imported, even when `node_modules` is excluded and type definition files are present. It is my understanding that this is not intended behaviour.

In researching this issue, I came across #6964 which looks like it should have fixed the exact bug I am still encountering. 

The reproduction is very simple - just try to import a package that contains broken ts code (In this case, the guilty party is aws-sdk):

in `package.json`:
```  
"dependencies": {
    "@types/aws-sdk": "0.0.42",
    "aws-sdk": "^2.7.3"
  }
```

`tsconfig.json` (this is just the default tsconfig):
```
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es5",
    "sourceMap": true
  },
  "exclude": [
    "node_modules"
  ]
}
```

and finally, the entry point, `index.ts`:
```
import * as AWS from "aws-sdk";
```

When compiling, tsc will throw errors as if it is compiling the AWS project itself.

**Comment by vladima** [comment]
1. `exclude` option tells compiler not to include files or folders when compiler searches for initial set of files to compile however it does not affect results of module resolution - i.e. `@types/jquery`  will be included in the program if some file imports `jquery` even if `node_modules` is excluded in config file.
2. as I see `aws-sdk` package also bundles typing files so compiler will prefer them to `@types`. These are `.d.ts` files and they don't produce any output or impact the runtime.

**Comment by JustASquid** [comment]
@vladima OK, right - so is there a way to make tsc prefer the @types declaration instead of the included declarations? Or am I simply unable to use this package until it gets fixed by the package developers?

If I'm understanding this right, it feels like a major problem for package compatibility. If I have my tsc set up to have a stricter/different configuration than the developer of a package, or if a package doesn't get updated for a while and tsc has breaking changes, so long as the package 'helpfully' includes .d.ts files, I'm stuck?

**Comment by mhegazy** [comment]
The core of the issue here is that the aws-sdk package has an inviald declaration file. i owuld log a bug on thier repo first.

To override the typings I would use path mapping :
```json
{
    "compilerOptions": {
        "baseUrl" : "./",
        "paths": {
            "*" : ["./node_modules/@types/*", "*"]
        }
    }
}
```

More info can be found about the original question at https://github.com/Microsoft/TypeScript/wiki/FAQ#why-is-a-file-in-the-exclude-list-still-picked-up-by-the-compiler

**Comment by JustASquid** [comment]
@mhegazy Thank you!

**Comment by plee-nm** [comment]
@mhegazy Is there a way to ignore an embedded .d.ts file like this [one](https://github.com/gaearon/redux-thunk/blob/master/index.d.ts)?

**Comment by mhegazy** [comment]
> Is there a way to ignore an embedded .d.ts file like this one?

Add a path mapping in your tsconfig.json to map `redux-thunk` to a different .d.ts file that you provide.
