### ISSUE TITLE
Mis-casing import path yields the oddest of bugs.

### ISSUE THREAD

**Issue by Izhaki** [Microsoft/TypeScript#12338]
**Platform**: Mac OS X 10.10.5

----

I consider myself lucky to have worked out what the problem was after mere 2 hours; I could have easily spent days on this.

I got the following class hierarchy (each class in a different file):

    class Viewee { ... }
    class Visible extends Viewee { ... }
    class Shape extends Visible { ... }
    class Rectangle extends Shape { ... }

Then in a different file:

    private needsRendering( aViewee: Viewee ): boolean {
        console.log( aViewee );                      // Rectangle { ... }
        console.log( Visible );                      // { [Function: Visible] }
        console.log( aViewee instanceof Rectangle ); // true
        console.log( aViewee instanceof Shape );     // true
        console.log( aViewee instanceof Visible );   // false <----- What the hell?
        console.log( aViewee instanceof Viewee );    // true 
        if ( aViewee instanceof Visible ) {
           ...
        } 
    }    

Notice that everything seems fine apart for `aViewee instanceof Visible` evaluating to false, which is outright ludicrous.

Turns out that I've spelt the path of `/Visible/` with an uppercase `V`:

    import { Visible } from '../../viewees/Visibles/Visible';

instead of with a lowercase one:

    import { Visible } from '../../viewees/visibles/Visible';

Can you spot the difference? No warnings, no red lines, even `Console.log( Visible )` seems to evaluate correctly.

**Comment by blakeembrey** [comment]
This is really just a node.js bug, and it's how it's designed. I typically recommend using only lower-case because I've been on a few projects where people don't realise this. When node.js evaluates two files (you have a case-insensitive filesystem but node modules are case-sensitive) the instances actually are different. There is a flag to catch it in https://www.typescriptlang.org/docs/handbook/compiler-options.html (see `forceConsistentCasingInFileNames`).

**Comment by Izhaki** [comment]
Thanks @blakeembrey, this has been very helpful. What I still don't understand is why `Visible` was assigned the whole module? 

Seeing `{ [Function: Visible] }` in the console is slightly misleading since if you are not super attentive/knowledgeable about log formats, you may conclude all is right.

**Comment by blakeembrey** [comment]
> What I still don't understand is why `Visible` was assigned the whole module?

I'm sorry, I'm not sure I understood the question and without additional code to see the context, I'm not sure. Want to try re-wording it?

**Comment by Izhaki** [comment]
@blakeembrey Sure.

My question is, why this line:

    import { Visible } from '../../viewees/Visibles/Visible';

Results in this:

    console.log( Visible ); // { [Function: Visible] }

Seems like `Visible` was assigned the whole module. This is `Visible.ts`:

    import { Viewee }  from '../Viewee';

    export
    abstract class Visible extends Viewee {
    ...
    }

I can't think why on earth deconstruction would end up with such result.
