### ISSUE TITLE
Union types ignore actual access level

### ISSUE THREAD

**Issue by Wolvereness** [Microsoft/TypeScript#12339]
**TypeScript Version:**  2.1.1

**Code**

```ts
class A { protected f = () => {}; }
class C extends A { f; }
class B extends A {
    operate() {
        let v1: C = new C();
        v1.f(); // Defined, because C made public
        let v2: B = new B();
        v2.f(); // Defined, because B can access protected of B
        let v3: C | B = Math.random() > 0.5 ? v1 : v2;
        v3.f(); // Not defined??
    }
}
```

[Playground](https://www.typescriptlang.org/play/index.html#src=class%20A%20%7B%20protected%20f%20%3D%20()%20%3D%3E%20%7B%7D%3B%20%7D%0D%0Aclass%20C%20extends%20A%20%7B%20f%3B%20%7D%0D%0Aclass%20B%20extends%20A%20%7B%0D%0A%20%20%20%20operate()%20%7B%0D%0A%20%20%20%20%20%20%20%20let%20v1%3A%20C%20%3D%20new%20C()%3B%0D%0A%20%20%20%20%20%20%20%20v1.f()%3B%20%2F%2F%20Defined%2C%20because%20C%20made%20public%0D%0A%20%20%20%20%20%20%20%20let%20v2%3A%20B%20%3D%20new%20B()%3B%0D%0A%20%20%20%20%20%20%20%20v2.f()%3B%20%2F%2F%20Defined%2C%20because%20B%20can%20access%20protected%20of%20B%0D%0A%20%20%20%20%20%20%20%20let%20v3%3A%20C%20%7C%20B%20%3D%20Math.random()%20%3E%200.5%20%3F%20v1%20%3A%20v2%3B%0D%0A%20%20%20%20%20%20%20%20v3.f()%3B%20%2F%2F%20Not%20defined%3F%3F%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A)

**Expected behavior:**

f is accessible from both members of the union individually, therefor, it should be accessible from their union.

**Actual behavior:**

    TS2339: Property 'f' does not exist on type 'C | B'.

The resulting Javascript is still functional.

**Comment by mhegazy** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/9974
