### ISSUE TITLE
VS 2017 RC solution analysis does not respect tsconfig.json "types" property (shows errors)

### ISSUE THREAD

**Issue by jasonswearingen** [Microsoft/TypeScript#12330]
**TypeScript Version:**  VS 2017 RC, Community Edition

**Code**
open a project that uses the tsconfig.json "types" property, such as
```
    "types": ["node", "mocha"],
```
and vs 2017 RC shows errors such as 
```Severity	Code	Description	Project	File	Line	Suppression State
Error	TS2307	Cannot find module 'assert'.	xlib (tsconfig project)	C:\repos\stage4\xlib\src\logging.ts	12	Active
```

**Expected behavior:**
```tsc``` compiles the project fine.  also opening the project in VS2015 with NodeJs tools works fine.

**Actual behavior:**
vs 2017 RC shows intellisense errors in the error list.   building ```ctrl-shift-b``` works fine and no errors are shown.

**Repo Steps***
download the ```xlib``` project from https://github.com/Novaleaf/xlib  and open it in VS2017 RC Community Edition.

**Comment by jasonswearingen** [comment]
**UPDATE**

removing the following line from ```tsconfig.json``` removes the error from solution analysis
```
"typeRoots":[]
```

however that enables global inclusion of all ```@types``` which caused problems with nested projects before.  I will investigate and see if the new version resolves these other issues.

**Comment by jasonswearingen** [comment]
removing ```typeRoots``` is an effective workaround.

**Comment by mhegazy** [comment]
well.. typeRoots were empty so not types were inferred. so the behavior you are seeing is correct. please see www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types for more details.

**Comment by jasonswearingen** [comment]
i explicitly had the ```types``` property set, and it works using the ```tsc``` commandline compiler.

only vs 2017 built-in solution analysis chokes.    but if you are fine with functional discrepancies, okay i guess.

**Comment by mhegazy** [comment]
We should look why there is a difference in behavior there. but this configuration does not look right. you are saying include `"node"` and `"mocha"` from "no where".

**Comment by jasonswearingen** [comment]
from what I understand,  by default the compiler will include all ```d.ts``` files it can find.  adding the ```typeRoots``` restricts this to a certain path, and adding ```types``` forces that only certain definitions will be included by default.   

all definitions explicitly loaded in code are loaded normally regardless.

so my project has type definitions for ```node``` and ```mocha``` but they are never explicitly loaded anywhere in my code.

**Comment by mhegazy** [comment]
> from what I understand, by default the compiler will include all d.ts files it can find

this is not accurate. all declaration files under `typeRoots` is what is included if `types` is not specified. if `types` is specified, only these are loaded.
