### ISSUE TITLE
Cannot declare ambient module in referenced file with import

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#12348]
**TypeScript Version:**  nightly (2.2.0-dev.20161118)

**Code**

```ts
// @noImplicitReferences: true

// @Filename: /node_modules/@types/foo/index.d.ts
/// <reference path="modules.d.ts"/>
export const x: number;

// @Filename: /node_modules/@types/foo/modules.d.ts
import * as foo from "foo";
declare module "foo/bar" {
    const x: number;
    export default x;
}

// @Filename: /a.ts
import bar from "foo/bar";

```

**Expected behavior:**

No error

**Actual behavior:**

`error TS2307: Cannot find module 'foo/bar'.`

**Comment by vladima** [comment]
`declare module "foo/bar"` is a module augmentation that does not declare module itself so at glance error looks legit.

**Comment by andy-ms** [comment]
OK. I'll have to keep that in mind when declaring ambient modules in the future that there can't be an `import` statement in file scope.
