### ISSUE TITLE
[feature request] consistent index access type for this type

### ISSUE THREAD

**Issue by HerringtonDarkholme** [Microsoft/TypeScript#12349]
Sorry it's me again....
it seems this type is resolved too eagerly in parent class.

**TypeScript Version:**  nightly

**Code**

```ts
class A {
  prop: {}
  propCopy: this['prop']
}

class B extends A {
  prop: {field: number}
  propCopy2: this['prop']
}

var b = new B
b.propCopy.field // error here
b.propCopy2.field
```

**Expected behavior:**

Code should compile. both `propCopy` and `propCopy2` have the same type.

**Actual behavior:**

Error on `b.propCopy.field`, `b.propCopy` is typed as `{}`

**Comment by aluanhaddad** [comment]
This behavior seems to make sense. `prop` doesn't have a `field` property in the base class where `propCopy` is defined. If you redefine the field on the subclass the error goes away.

**Comment by HerringtonDarkholme** [comment]
I believe this is the same issue with https://github.com/Microsoft/TypeScript/pull/11929#issuecomment-261744874

It is not a bug report but a feature request.

**Comment by aluanhaddad** [comment]
@HerringtonDarkholme I see. I was thinking about it as a bug report, sorry.
