### ISSUE TITLE
Bug with compile destructuring fields

### ISSUE THREAD

**Issue by arvitaly** [Microsoft/TypeScript#12347]
**TypeScript Version:**  2.0.10

**Code**

```ts
// A *self-contained* demonstration of the problem follows...

    let query: (q: string) => Promise<{ data, errors }>;

**Expected behavior:**
    let query;

**Actual behavior:**

    let query;
    > ;

**Comment by vladima** [comment]
code in repro is syntactically incorrect (property declarations in type literal lack type annotations) and TypeScript compiler never guaranteed valid output in presence of syntactic errors

**Comment by vladima** [comment]
actually it seems to be working in the latest nightly build:
```
vladima:~/Sources/play/12347$ cat app.ts
let query: (q: string) => Promise<{ data, errors }>;
vladima:~/Sources/play/12347$ ./node_modules/.bin/tsc --version
Version 2.2.0-dev.20161118
vladima:~/Sources/play/12347$ ./node_modules/.bin/tsc -t es6 app.ts
vladima:~/Sources/play/12347$ 
```

what version of TypeScript do you use?

**Comment by arvitaly** [comment]
Hi! Sorry, i think it is not problem of typescript, it is VSCode's problem. But typescript compiled this code with error also.
![capture](https://cloud.githubusercontent.com/assets/2562855/20443107/003d3396-adfe-11e6-9f5f-84b91c7eb0e6.PNG)
