### ISSUE TITLE
Feature request: represent Function via generic type parameterized by its return/parameter/this type 

### ISSUE THREAD

**Issue by HerringtonDarkholme** [Microsoft/TypeScript#12342]
Background:
-----------------

With https://github.com/Microsoft/TypeScript/pull/11929, we can get property type of an object. But we cannot get the  return/parameter/this types of a function at compile time.

For single function argument, getting return/parameter type is relative simple by adding generic parameter. But when API is designed to accept **a map of functions**, it become hard to express in TypeScript. 

Using function is a common pattern in [vuejs](https://vuejs.org/v2/api/#computed) and its derivation.

```ts
const component = new Vue({
  computed: {
    getNumber() {
       return 42
    }
  }
})

component.getNumber // 42
```

By combining mapped types and `keyof`, we can achieve some compile time types to capture this pattern.

```ts
declare interface Vue {
  new <T extends {[k: string]: Function}>(config: {computed: T}): { [K in keyof T]: ReturnType<T[K]>}
}
```

If only we have a special type called `ReturnType`.

Another usage is for event handling in most frontend framework. For example, backbone has an [event-map syntax](http://backbonejs.org/#Events-on) for event binding.

```ts
book.on({
  "change:author": authorPane.update,
  "change:title change:subtitle": titleView.update,
  "destroy": bookView.remove
});

book.trigger("change:author", author) 
// author should have the parameter type of authorPane.update
```
Also, with return/parameter/this type support, we can achieve [typed bind/apply/call](https://github.com/Microsoft/TypeScript/issues/212)
```ts
interface FunctionTyped<ThisType, ArgTypes, RestArg> {
  bind: FunctionTyped<void, [ThisType, ...ArgTypes], RestArg]>
  apply: FunctionTyped<void, [ThisType, [...ArgTypes, ...RestArg]], never>
  call: FunctionTyped<void, [ThisType, ...ArgTypes], RestArg>
}
```
Note, this would require [variadic generic types](https://github.com/Microsoft/TypeScript/issues/5453).

Proposal:
--------------

For every function type, we can have a special access key for return type/ parameter type. Parameter type is a tuple type for every argument. If function has rested parameter, parameter type will fallback to array type.

For overloaded function, the return type/parameter type is the union of all corresponding type of overloading signature.

For generic type parameter with function type constraint, the return type is resolved to constraint. the parameter type also resolves to constraint's parameter type (not regarding with variance.) If generic type has no constraint, resolve it to `{}`.

For `Function`, the return and parameter type is `any`, the parameter type is `Array<any>`.

To access function's parameter type, it might be good to reuse index access type. For example

```ts
type Callback = (a: Author) => void
type CallbackArg = Callback["arguments"] // [Author]
type CallbackReturn = Callback["returns"] // void, the access type is arguable
```

Related 
----

https://github.com/Microsoft/TypeScript/issues/212
https://github.com/Microsoft/TypeScript/issues/1773

Edit: I think representing function via typed generic is a more complete solution. But it requires more typing features as prerequisites and rewriting all function type encoding.

**Comment by yortus** [comment]
See also #6606

**Comment by weswigham** [comment]
In your specific example, wouldn't
```ts
declare interface Vue {
  new <T extends {[k: string]: Function}>(config: {computed: { [K in keyof T]: () => T[K]}}): T
}
```
Be an equivalently correct type (without need for a special type function), provided T were inferred correctly?

**Comment by HerringtonDarkholme** [comment]
@weswigham I believe T could not be inferred correctly for now by design: mapped type is not an inference site.  https://github.com/Microsoft/TypeScript/pull/12114#issuecomment-259986808

**Comment by weswigham** [comment]
@HerringtonDarkholme note the comment:
> You could speculate about the compiler manufacturing a structurally compatible type, but that is generally not something we do and there are lots of subtle ways it could go wrong and lead to confusing error messages

Accumulating valuable use cases, such as this, is how things like this can change.

**Comment by IMRaziel** [comment]
i have a use case that is similar.

```typescript
declare interface StoreProps<A, M> {
  actions: A
  mods: M
}

declare function Store<A, M> (props: StoreProps<A, M>): StoreImpl<A, M>;

declare interface StoreImpl<A, M> {
  commit<CK extends keyof A, CT extends A[CK] & { (x: P): void }, P>(k: CK, r: P): void
  commit<CK extends keyof M, CT extends M[CK] & { (x: P): void }, P>(k: CK, r: P): void
}

declare type x = { (x: number): void } & { (x: string): void }

let s = Store({
  actions: {
    act: function(x: number) {},
    act2: function(x: string) {}
  },
  mods: {
    mod1: function(x: {a: number}) {}
  }
})

s.commit("act", "")
s.commit("mod1", "")
```
I'm trying to make type checker to derive second argument type using value of first argument here. And VSCode correctly shows that type of second argument in call to `s.commit("act", "")` should be 
```typescript
{ (x: number): void } & { (x: string): void }
```
 on mouseover hint. 
This type is obviously illegal (argument can't be string and number at the same time), so compilation should fail and VSCode should show it as error, but it currently doesn't. 
![untitled](https://cloud.githubusercontent.com/assets/471019/20548135/e8c6d88e-b131-11e6-963e-c34913b17cad.png)
If i do 
```
let someVar: { (x: number): void } & { (x: string): void } = (p: number) => {}
```
i get error, as expected.

I think some kind of type deconstruction will be good here. So could write, for example, 
```typescript
commit<CK extends keyof M, M[CK] is {(x: P): RT}>(k: CK, r: P): void
```
, where `is` deconstructs M[CK] and gives access to function's argument type and return type, depending on literal type of first argument

**Comment by tycho01** [comment]
Tracking this as well, wanna type `map` over heterogeneous structures (tuples, objects).

**Comment by aleksey-bykov** [comment]
@tycho01 looks at #1213

**Comment by Igorbek** [comment]
That's going to be a great step towards generalization of functions. I like it. However, it would not be enough. Next things to consider are:
- capture function overloads, in general (any proposal/discussion?)
- capture generic parameters of function (#10247)

**Comment by isiahmeadows** [comment]
I happen to need full on return type rewriting for my particular use case. To pull from #12381, I need a transformation from `Original<T>` to `Wrapped<T>`  to properly type my API (I'm currently using type parameters and a whole lot of `any`, but that's *incredibly* ugly):

```ts
interface Original<T> {
  [P in keyof T]: (...args) => R;
}

interface Wrapped<T> {
  [P in keyof T]: (...args) => Promise<R>;
}
```

**Comment by paldepind** [comment]
What is the status of this? It seems to me like adding the proposed `ReturnType` whould be fairly simple.

Below is an example of a function that cannot be given a correct type without this feature (note that I use `ReturnType` in the definition of `ApplyObject`):

```typescript
type ApplyObject<O extends Record<string, Pair>> = {
  [K in keyof O]: ReturnType<O[K]>
}

// Takes an object of functions, calls each function and returns an object with the results
function applyObject<O extends { [p: string]: () => any }>(object: O): ApplyObject<O> {
  const newObject: any = {};
  for (const key of Object.keys(object)) {
    newObject[key] = object[key](); // <- Note application here
  }
  return newObject;
}
```

**Comment by isiahmeadows** [comment]
How about instead, create a new type-level operator (instead of a native generic) called `returnof`. To take @paldepind's example:

```ts
type ApplyObject<O extends Record<string, Pair>> = {
  [K in keyof O]: returnof O[K]
}
```

It fits better with the theme of using syntax instead of generics for primitive type-level operations.

**Comment by HerringtonDarkholme** [comment]
I think this usage is already covered by conditional type. Closing.

**Comment by tycho01** [comment]
Yeah. For reference, see [this `Fn` type](https://github.com/tycho01/typical/blob/master/src/function.ts#L22-L34) implementation based on a similar discussion at https://github.com/gcanti/typelevel-ts/issues/8.
Well, minus the `this` binding requested here. And no way to represent return types based on inputs.
