### ISSUE TITLE
2.1 Regression: Definite assignment with try..finally

### ISSUE THREAD

**Issue by jods4** [Microsoft/TypeScript#12355]
**TypeScript Version:**  2.1.? / the one that comes with VS 2017 RC

**Code**
```ts
async function bug() {
    let response: Response;
    try {
        response = await fetch("www.google.com");
    }    
    finally {
    }
    if (response.ok)  // <- error: Variable response is used before being assigned
        console.log("ok");
}
```

**Expected behavior:** was compiling (and working) fine in TS 2.0

**Actual behavior:** Error: `response` is used before being assigned.

**Comment by wallverb** [comment]
Improvement ;)

```ts
async function bug() {
    let response;
    try {
        response = await fetch();
    }
    catch(err) {}
    finally {
    }
    if (response.ok)  // <- error: Variable response is used before being assigned
        console.log("ok");
}
bug()
```

Run this and you will get runtime error `Cannot read property 'ok' of undefined(…)`
Maybe error message could be ' Variable response is potentially used before being assigned'

**Comment by mhegazy** [comment]
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/12205

**Comment by jods4** [comment]
I didn't see that one, it looks like a dup indeed.
