### ISSUE TITLE
Module extension definition question.

### ISSUE THREAD

**Issue by ktersius** [Microsoft/TypeScript#12356]
Given the following modules how can I import/export the functions in the modulea namespace as functions in module b IAllFunctions interface? 

My problem stems from trying to create rethinkdbdash definitions that are easy to maintain.
I've created [the following retinkdbdash definition](http://pastebin.com/7WReHq53) that duplicates all functions into the RDash interface that exists in the [rethinkdb defition](https://raw.githubusercontent.com/types/npm-rethinkdb/6560cc0cb965c1619f56f03126bdeec41de1a861/rethinkdb.d.ts) namespace.

Is there a way to declare my rethinkdbdash definition in a more maintainable way?
```
declare module 'modulea' {
namespace modulea  {
      function abc() : xyz
   }

export = modulea;
}

declare module 'moduleb' {
import * as moda from 'modulea';
namespace moduleb  {
      export interface IAllFunctions {
         EXPORT modulea.abc() here....???
      }
   }
 export = moduleb;
}
```

**Comment by aluanhaddad** [comment]
Are you trying to augment an interface with functions declared in a namespace?

**Comment by ktersius** [comment]
@aluanhaddad It would seem so.

**Comment by aluanhaddad** [comment]
Roger. I was asking because I find the following pseudocode very confusing
```ts
export interface IAllFunctions {
         EXPORT modulea.abc() here....???
      }
```
What is your goal? Is it to have `modulea` appear as though it exposes the augmentations introduced by `moduleb` or is to merge `modulea` into `moduleb` and expose the augmented module from the latter?

**Comment by ktersius** [comment]
I've included a snippet of code usage so that you can see the differences in usage. The rethinkdbdash driver basically wraps the rethinkdb driver and exposes all the methods of the rethinkdb namespace on the variable that you get back from calling rethinkdbDash({db:'devDB'});

Thus I have to re-declare all rethinkdb.Func..XYZ on the RDash interface that is returned. So now I'm asking if there is a better way than having to re-declare all the exposed functions. Maybe some clever import/export that can reduce all the copy and pasting.

```
import * as rethinkdbDash from 'rethinkdbdash';
import * as rethinkDb from 'rethinkdb';

async function printDateRethinkDb(){
	let conn = await rethinkDb.connect('localhost'); //Note how we are accessing namespace functions.
	let date = await rethinkDb.now().run(conn);
	console.log(`Rethink DB Date: ${date}`);
}

async function printDateRethinkDbDash(){
	let r = rethinkdbDash({db:'devDB'}); //Here we call the default namespace function to get back an interface.
	let date = await r.now();
	console.log(`Rethink DB Dash Date: ${date}`);
}

printDateRethinkDb();
printDateRethinkDbDash();
```
