### ISSUE TITLE
Add ability to generate ambient declarations for external commonjs modules

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#1236]
Badly needed for commonjs modules where you are more likely to ship JS code plus a generated `.d.ts` file.

From codeplex : https://typescript.codeplex.com/workitem/2080

**Comment by niemyjski** [comment]
+1. We really really really need this.

**Comment by OvidiuGuta** [comment]
+1. It would be really useful.

**Comment by vvakame** [comment]
:+1: 
We need tsc allow below syntax.

```
$ cat index.d.ts
// hand assemble
declare module "foobar" {
  export * from "./lib/main";
}
```

but, now we got below error message.

```
$ tsc --module commonjs index.d.ts
index.d.ts(3,3): error TS2439: Import or export declaration in an ambient module declaration cannot reference module through relative module name.
```

**Comment by siulung4073** [comment]
+1

**Comment by basarat** [comment]
Now that the compiler supports node module resolution this can be closed as far as I am concerned :rose:

**Comment by RyanCavanaugh** [comment]
If @basarat says it's good it's good with me too :smiley:

**Comment by ca0v** [comment]
@basarat can you show how this can be done?  I want to do the very thing the error is saying cannot be done.  What is the alternative?
'Import or export declaration in an ambient module declaration cannot reference module through relative module name.'

**Comment by MemnochDaCoder** [comment]
+1
