### ISSUE TITLE
TS2495: Type 'Readonly<any[]>' is not an array type or a string type

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#12377]
**TypeScript Version:**  master

**Code**

```ts
for (const _ of Object.freeze([])) {}
```

**Expected behavior:**

pass

**Actual behavior:**

```
$ node built/local/tsc.js -t es5 --lib es6 index.ts
index.ts(1,17): error TS2495: Type 'Readonly<any[]>' is not an array type or a string type.
```

**Comment by aluanhaddad** [comment]
This is because `[Symbol.iterator]` is not included by the property enumerator. The quick fix is to add an overload of freeze in your lib file.

```ts
  /**
    * Prevents the modification of existing property attributes and values, 
    * and prevents the addition of new properties.
    * @param o Object on which to lock the attributes.
    */
  freeze<T, V>(o: T & { [Symbol.iterator]: V }): Readonly<T> & { [Symbol.iterator]: V };
  freeze<T>(o: T): Readonly<T>;
```

**Comment by mhegazy** [comment]
we should add an overload to freeze for arrays:

```ts
    freeze<T>(o: T[]): ReadonlyArray<T>;
    freeze<T>(o: T): Readonly<T>;
```

**Comment by aluanhaddad** [comment]
@mhegazy would you be open to a PR?

**Comment by mhegazy** [comment]
PRs welcomed

**Comment by mhegazy** [comment]
also we need to handle functions differently. 

```ts
let handler = Object.freeze(function(callback, context?) { return 0; });
handler(); // Error now, no call signature
```

**Comment by aluanhaddad** [comment]
Yeah there are a bunch of tricky scenarios. Also something that came to mind when special casing `ReadonlyArray<T>` is that it's not really the same contract expressed by `Readonly <T[]>`. While it is convenient to conflate them in this specific case, they don't mean the same thing in terms of how they are used. The point you raise about functions is critical and I assume construct signatures are also excluded. It's probably just a matter of special casing all of them but I wondered what the most expressive way to write the types is.
