### ISSUE TITLE
Typescript compiler generating wrong return type in d.ts

### ISSUE THREAD

**Issue by cailenmusselman** [Microsoft/TypeScript#12370]
**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)

**Code**

```ts

// Demo.ts

import { createSelector, Selector } from 'reselect';

export interface DemoState {
    values: {
        value1: number,
        value2: number
    },
}

export const selectTotal = createSelector<DemoState, number, number, number>(
    state => state.values.value1,
    state => state.values.value2,
    (value1, value2) => {
        return value1 + value2;
    }
);
```

**Expected behavior:**

According to Reselect.d.ts (https://github.com/reactjs/reselect/blob/master/src/reselect.d.ts) the return type of `createSelector()` should be `Selector<DemoState, number>`...

```ts
type Selector<TInput, TOutput> = (state: TInput, props?: any) => TOutput;

function createSelector<TInput, TOutput, T1, T2>(selector1: Selector<TInput, T1>, selector2: Selector<TInput, T2>, combiner: (arg1: T1, arg2: T2) => TOutput): Selector<TInput, TOutput>;
```

**Actual behavior:**

However, what the typescript compiler is generating for a definition in my Demo.d.ts is:

```ts
export declare const selectTotal: Selector<DemoState, number, number, number>;
```

Soo... when I go to import `selectTotal` in another project I get the error: "Generic type 'Selector' requires 2 type argument(s)." Because reselect.d.ts only defines `Selector<TInput, TOutput>` and, as far as I can tell, that's what `createSelector()` should be returning, regardless of the number of type arguments passed in to it.

I also posted the same question on SO roughly a month ago (http://stackoverflow.com/questions/40208012/typescript-compiler-generating-wrong-return-type-for-reselect-createselector#) and have received 0 answers/theories as to what the issue is, so I'm hoping you guys might have an idea.

**Comment by mhegazy** [comment]
should be fixed in `typescript@next`.

**Comment by mhegazy** [comment]
```sh
c:\test\12370>type a.ts
// Demo.ts

import { createSelector, Selector } from 'reselect';

export interface DemoState {
    values: {
        value1: number,
        value2: number
    },
}

export const selectTotal = createSelector<DemoState, number, number, number>(
    state => state.values.value1,
    state => state.values.value2,
    (value1, value2) => {
        return value1 + value2;
    }
);

c:\test\12370>tsc  --v
Version 2.2.0-dev.20161117

c:\test\12370>tsc --d

c:\test\12370>type a.d.ts
import { Selector } from 'reselect';
export interface DemoState {
    values: {
        value1: number;
        value2: number;
    };
}
export declare const selectTotal: Selector<DemoState, number>;
```
