### ISSUE TITLE
Potential Bug with Object Mappers: Readonly

### ISSUE THREAD

**Issue by opensrcken** [Microsoft/TypeScript#12388]
**TypeScript Version:**  nightly (2.2.0-dev.20161118)

**Code**

```ts
interface Test {
  optional?: boolean;
  mandatory: boolean;
}

const a: Readonly<Test> = {
  mandatory: 1
};
```

**Expected behavior:**
This should compile?

**Actual behavior:**
```
Error TS2322: Type '{ mandatory: 1; }' is not assignable to type 'Readonly<Test>'.
  Property 'optional' is missing in type '{ mandatory: 1; }'.
```

**Comment by ahejlsberg** [comment]
This is working as intended. Property modifiers don't carry over in mapped types, so all properties of a `Readonly<T>` are read-only and non-optional.

We've debated having modifiers carry over, but the mechanism by which it would happen isn't clear. Also, if they did carry over, we'd then need a way of stripping them when that is desired. It quickly gets complicated.
