### ISSUE TITLE
Generic constraint for mapped property

### ISSUE THREAD

**Issue by isiahmeadows** [Microsoft/TypeScript#12381]
I need to constrain a mapped property so I can basically get the return type out of its methods and modify it. Here's the gist of the two transformations I need to type (I need both):

```ts
interface Original<T> {
  [P in keyof T](...args): R;
}

interface Wrapped<T> {
  [P in keyof T](...args): Promise<R>;
}

interface Proxied<T> {
  call<P extends keyof T>(method: P, ...args): Promise<R>;
}

export function wrap<T extends Original<T>>(original: T): Wrapped<T>;
export function proxy<T extends Original<T>>(original: T): Proxied<T>;
```

I know TypeScript 2.1's mapped properties aren't enough, so any ideas?

**Comment by isiahmeadows** [comment]
Note: the return types are not necessarily the same across multiple methods.

**Comment by aluanhaddad** [comment]
See also #12342
