### ISSUE TITLE
Overloaded string parameters don't appear in alphabetical order.

### ISSUE THREAD

**Issue by lord-saumagen** [Microsoft/TypeScript#1238]
It appears that the overloaded string parameters ins the "document.createElement" function are not sorted by alphabet. Although they are in alphabetical order in the 'lib.d.ts' file where they are defined.
May be that's also a problem with other functions which offer overloaded string parameters. I didn't check. It would be nice when you find a way to display that string parameters in alphabetical order. That would be a great improvement.

Kind regards. Lord Saumagen.

![parameter_error](https://cloud.githubusercontent.com/assets/9468599/5150933/a7bebcce-71cf-11e4-8cea-3c942a192bf3.png)

**Comment by mhegazy** [comment]
This is fixed in latest VS 2015 plugin.
