### ISSUE TITLE
error TS2304: Cannot find name 'UriMapHandlerArray'.

### ISSUE THREAD

**Issue by rajinder-yadav** [Microsoft/TypeScript#12385]
UriMapHandlerArray is defined in the same file, TS cannot find it.

ts v2.0.10
**Code**

```js
interface UriMapHandlerArray {
  [index: string]: IUriMapHandler;
}

export class Furi {

  private _get:    IUriMap = { uri_map: UriMapHandlerArray };
```

```ts
// A *self-contained* demonstration of the problem follows...

```

**Expected behavior:**

**Actual behavior:**

**Comment by j-oliveras** [comment]
You uses UriMapHandlerArray as a value of uri_map property not as a type.

If you want to define IUriMap type as { uri_map: UriMapHandlerArray } you can do:
`type IUriMap = { uri_map: UriMapHandlerArray }`
or:
`interface IUriMap { uri_map: UriMapHandlerArray }`
and then use it as 
```
export class Furi {
  private _get: IUriMap = { uri_map: {} };
}
```

**Comment by rajinder-yadav** [comment]
OK I see my mistake, thanks!
