### ISSUE TITLE
suggestion: class name strings

### ISSUE THREAD

**Issue by BobFrGit** [Microsoft/TypeScript#12387]
**TypeScript Version:**  2..x

I just started using literal strings and it's a wonderful feature. Given Typescript's integration with HTML it would be nice to tap into that knowledge. In particular be able to declare that a string is the name of a CSS class in the project.

Also, for convenience, might as well have an HTMLColor type predefined.  Even better if a field like backgroundColor would be defined as an HTMLColor (though # strings may be hard to fit into that model)

**Comment by aluanhaddad** [comment]
Can you show some examples? Are you trying to validate that class names passed as strings must match the set of classes that are available? The term project is a bit vague. would this involve TypeScript inferring class names by parsing CSS files? This seems interesting but its not clear what you have in mind.

**Comment by BobFrGit** [comment]
First, I realize I'm thinking of Visual Studio not TypeScript and it is VS not TS that does the class handling for HTML. Added it to TS would involve parsing the file so maybe that involves more of a change than simply building on an existing capability.

But to clarify

I have a classes .logAlert and .logMild" and have added
```
 type logClass = null | "logAlert" | "logMild"
```

**Comment by mhegazy** [comment]
The definition of HTMLElement attributes like `backgroundColor` comes from `lib.d.ts`. Currently `backgroundColor` is defined to be `string | null`. I am afraid we can not make it a list of values as [colors in CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value) can be any RGB color.

**Comment by BobFrGit** [comment]
I understand the problem -- that's why I mentioned the # problem.
