### ISSUE TITLE
Missing error on import of non-existing module when nothing is imported from it

### ISSUE THREAD

**Issue by devoto13** [Microsoft/TypeScript#12380]
**TypeScript Version:**  2.1.1 and 2.2.0-dev.20161118

**Code**

```ts
import { Something } from 'non-existing-module'; // correctly errors on invalid module 

import 'non-existing-module'; // no error on the same module without imported members
```

See [repo](https://github.com/devoto13/typescript-import-demo) for complete example.

**Expected behavior:**

Shows error for both imports.

**Actual behavior:**

Shows error only, when something is imported from the module.

**Comment by RyanCavanaugh** [comment]
Duplicate #10057
