### ISSUE TITLE
When compiled with LanguageService, relative paths not preserved

### ISSUE THREAD

**Issue by barbatus** [Microsoft/TypeScript#12397]
**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)

**Code**

I have a TypeScript plugin that uses internally `LanguageService` (created by `ts.createLanguageService`) to compile ts-files.
Compiler options used: `{ target: 'ES5', moduleResolution: 'node', module: 'commonjs'}`.

Say, there is a ts-file `client/main.ts`:
```ts
import {foo} from './foo';

console.log(foo);

```

**Expected behavior:**

The code above compiled into 
```js
var foo_1 = require('./foo');
 console.log(foo_1.foo)
```

**Actual behavior:**

Initial relative paths are not preserved now.
It's compiled into:
```js
var foo_1 = require('client/foo');
console.log(foo_1.foo)
```

First noticed in 2.1.1.
With 2.0.10 it works as expected as well as `tsc` with 2.1.1 =>
reason seems to be specifically in LanguageService.

**Comment by vladima** [comment]
can you please provide a repro code?
