### ISSUE TITLE
Passing Html element id in typescript

### ISSUE THREAD

**Issue by Ashwani44** [Microsoft/TypeScript#12394]
I have a HTML file with 2 textbox and i want to calculate length and breadth on button click and based on the value entered in textbox and bind it on label : here is my code
index.html
<body> <br/><br/>
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-4">
            <div class="form-group">
                <label for="length">Length:</label>
                <input type="number" class="form-control" id="length" />
            </div>
            <div class="form-group">
                <label for="breadth">Breadth:</label>
                <input class="form-control" id="breadth" />
            </div>
           
            <div class="form-group">
              <button type="button" class="btn btn-primary" onclick="">Submit</button>
            </div>

            <div class="form-group">
                <label for="calc">Area of Rectangle is : </label>
                <label id="label_to_bind" ></label>
                
            </div>
            
        </div>
        <div class="col-md-6"></div>
    </div>

app.ts

namespace example
{
   interface CalculateArea
    {
        Recatngle: ( l: number, b: number ) => number;
    }

   
    var area: CalculateArea = {
        Recatngle: function ( l: number, b: number )
        {
            return l * b;
        }
    }
    //Get Element id from UI
    var a = document.getElementById( "Length" ).innerHTML;
    var b = document.getElementById( "Breadth" ).innerHTML;
    var z = area.query( a,b ); // showing me error here "string is not assignable to parameter type  number
}
Can any body tell me where i am making mistake and also please tell me how do i  make a call on button click and bind result on label

**Comment by SaschaNaz** [comment]
This is not an answer but you can insert triple backticks to prevent incorrect document format.

<pre>
```
&lt;div&gt;
Code in the backtick shell
&lt;/div&gt;
```
</pre>

**Comment by aluanhaddad** [comment]
InnerHTML is a string but the API expects a number.
If it requires a number and what you have is a string you should convert it appropriately.
You can use the `Number` or `parseInt` or `parseFloat` global functions. Remember to pass a radix when calling `parseInt`.
