### ISSUE TITLE
/// <reference path="..." /> ignored, resulting in invalid --outFile order of files

### ISSUE THREAD

**Issue by Janne252** [Microsoft/TypeScript#12395]
**TypeScript Version:**  2.2.0-dev.20161120

**Code**
Full source code can be found at [Janne252/jannengine](https://github.com/Janne252/jannengine)

**Expected behavior:**
`/// <reference path="./baseRenderable.ts" />` defined in [polygon.ts](https://github.com/Janne252/jannengine/blob/master/src/system/drawing/polygon.ts) should make sure that [baseRenderable.ts](https://github.com/Janne252/jannengine/blob/master/src/system/drawing/baseRenderable.ts) is appended to the output file BEFORE **polygon.ts**.

**Actual behavior:**
**polygon.ts** is appended to the output file before **baseRenderable.ts**, which results in the ever so annoying `Uncaught TypeError: Cannot read property 'prototype' of undefined` error.

Here is a part of the tsc output generated by the [tsconfig.json](https://github.com/Janne252/jannengine/blob/master/tsconfig.json) entry **`"listFiles"`** set to **`true`**:
```
.../jannengine/src/system/engine/inputProvider.ts
.../jannengine/src/system/component/event/eventHandlerCallbackBind.ts
.../jannengine/src/system/component/event/eventHandler.ts
.../jannengine/src/system/helpers/math.ts
.../jannengine/src/system/component/vector2d.ts
.../jannengine/src/system/component/size.ts
.../jannengine/src/system/component/random.ts
.../jannengine/src/system/component/color.ts
.../jannengine/src/system/component/padding.ts
.../jannengine/src/system/component/range/range.ts
.../jannengine/src/system/component/range/xyRange.ts
.../jannengine/src/system/drawing/polygon.ts
.../jannengine/src/system/drawing/line/lineCap.ts
.../jannengine/src/system/drawing/line/lineJoin.ts
.../jannengine/src/system/drawing/line/line.ts
.../jannengine/src/system/drawing/baseRenderable.ts
```
As you can see, polygon.ts is added before **baseRenderable.ts** even though **polygon.ts** defines **baseRenderable.ts** as its dependency.

An example of the generated `.js` file can be found in [janne252/jannengine/js/combined_sample](https://github.com/Janne252/jannengine/tree/master/js/combined_sample)

I'm aware that this issue is related to #5207. However to my understanding my code should work, according to the documentation about [How do I control file ordering in combined output](https://github.com/Microsoft/TypeScript/wiki/FAQ#how-do-i-control-file-ordering-in-combined-output---out-). To me it seems that the `/// <reference path="..." />` entries in my code are completely ignored **because the resulting output file is identical with and without the `/// <reference path="..." />` entries in the code files.**

**Comment by Janne252** [comment]
Well, is there anything that can be done to fix this? Unless I'm mistaken, the Triple-Slash Directives are not working at all.

**Comment by Janne252** [comment]
F*** me, there was a circle reference in my source code. BaseRenderable requires Line and Line requires BaseRenderable. Whoops.

**Comment by mhegazy** [comment]
I would not use `/// <reference path="..." />` for this specific reason. i would instead use `files` or `include` in your `tsconfig.json`. a flat list is much easier to debug than a graph of links between files.

**Comment by Janne252** [comment]
@mhegazy Fortunately that wasn't the issue after all, I had accidentally created a situation where A requires B and B requires A. Unfortunately it too way too long to notice. 

Thanks for the reply though!
