### ISSUE TITLE
Very Very Slow

### ISSUE THREAD

**Issue by wpitallo** [Microsoft/TypeScript#12392]
I upgraded from Typescript 2.0.3 to  Typescript 2.0.6 with webpack 2.1.0-beta.27 (with ts-loader - note i tried awesome-typescript-loader and that did not help)

My project build time went from about 30sec to about 5min... What can i do to fix this.

tsconfig:
{
    "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false,
    "jsx": "react",
    "baseUrl":".",
    "sourceMap": false
    },
    "exclude": [
        "node_modules",
        "CodeScience.Client.Global\\node_modules",
        "modules\\system\\bootstrap\\CodeScience.Client.Global\\node_modules"
    ]
}

**Comment by vladima** [comment]
can you provide a repro scenario or maybe share your code (we'll sign NDA if necessary)?

**Comment by aluanhaddad** [comment]
I'm still using webpack 1.13.3 and I haven't noticed any performance issues whatsoever. I have also used all the versions mentioned. I also use JSP and more often, and I find that the translation speed has not significantly changed between these releases.

**Comment by wpitallo** [comment]
Hi Vlad, 

Sure, do you have an email address that I can use to add you to our repo?

Thanks for the help, really appreciate it.

**Comment by vladima** [comment]
vladima `at` microsoft `dot` com

**Comment by wpitallo** [comment]
Posting Email Thread:


Hey, thanks so much. 

Really appreciate the help, I suspected that it may be something with the ts-loader. 

So I understand what you are saying, one thing though that seems a little strange is that the string-replace-loader is configured in Webpack as a pre loader, so I would have thought that this would make the replacements in all the files before handing them over to the ts-load to create the language service. Is there any other way that we could possibly delay the language service until the string-replace-loader has completed replacing on all files? 

With the ts-loader not caching results of module resolution, surly there this will be an issue then with all projects that use Webpack with the ts-loader for their build process? Are you guys currently experiencing the same problem with this or are you not using ts-loader or do you know if there are any later versions that solve this?

Thanks again for the help,

Regards,

Warren


At glance I’d say that problem is not in TypeScript compiler but rather in interaction between ts-loader and TypeScript language service and a few unfortunate details in implementation of ts-loader

From the high level TypeScript language service works in the following way:

First it asks the host to provide a list of root files that should be included in the program. Then it will built the program by building transitive closure of all files accessible from root files (via imports, tripleslash references etc). Result program can be used to asked semantic questions, get emit output etc and this program is valid as long as all files that contributed to the program remains unchanged. Once some file is modified language service will try to incrementally parse it and rebuild the program.

What is happening in this case:

ts-loader creates language service and populates it with the initial set of files read from disk. Here there will be plenty of files with placeholders in them that should be substituted by the string-replace-loader and based on this files language service will create initial version of the program. Then once string-replace-loader processes files they are fed to ts-loader. Since content of file after substitution does not match the initial content language service will drop existing program and will build a new one by walking all files and resolving modules and doing other things that don’t make process any faster. What is worse – every file that has placeholders in it will cause re-creation of the program (and this project plenty of them).

In addition to that it seems that ts-loader does not attempt to cache results of module resolution meaning that every time program is rebuild compiler has to repeat module resolution process for every file which is quite expensive.

As an experiment I’ve manually replaced all placeholders in the code and compiled it with command line TypeScript compiler:

D:\sources\bugs\bootstrap>node node_modules/typescript/lib/tsc.js -p tsconfig.json --diagnostics
Files:            1311
Lines:           86351
Nodes:          283600
Identifiers:    101221
Symbols:        256710
Types:           49058
Memory used:   237535K
I/O read:        0.16s
I/O write:       0.13s
Parse time:      2.84s
Bind time:       0.52s
Check time:      2.04s
Emit time:       0.27s
Total time:      5.67s

---
Thanks,
Vladimir Matveev


Hi, 

Out of curiosity, is it possible to build just .ts file in your project using tsc.js (i.e using tsc -p <path to config>)?

In tsconfig.json file I’m seeing this include 

        "CodeScience.Client.Base/**/*"

However I don’t see this folder anywhere, this is the content of ‘bootstrap’ directory  and it does not have CodeScience.Client.Base in it

.eslintrc
.gitignore
.gitmodules
assets
CodeScience.Client.Global
configuration
core
core-old
global.distributions
node_modules
package.json
README.md
references
system-controller
tsconfig.json
tsd.json
tslint.json
typings.json
webpack.config.js

---
Thanks,
Vladimir Matveev

**Comment by wpitallo** [comment]
Hi, 

Out of curiosity, is it possible to build just .ts file in your project using tsc.js (i.e using tsc -p <path to config>)?

In tsconfig.json file I’m seeing this include 

        "CodeScience.Client.Base/**/*"

However I don’t see this folder anywhere, this is the content of ‘bootstrap’ directory  and it does not have CodeScience.Client.Base in it

.eslintrc
.gitignore
.gitmodules
assets
CodeScience.Client.Global
configuration
core
core-old
global.distributions
node_modules
package.json
README.md
references
system-controller
tsconfig.json
tsd.json
tslint.json
typings.json
webpack.config.js

---
Thanks,
Vladimir Matveev

**Comment by wpitallo** [comment]
I was using tsc a while back, but when I try to install it now it says that it is depreciated. 

So the way this project is set up its also part of a bigger project that includes authentication etc. So "CodeScience.Client.Base/**/*" should just be ignored, it should not be being used in this build process. Removing it has no impact on the performance.

**Comment by wpitallo** [comment]
At glance I’d say that problem is not in TypeScript compiler but rather in interaction between ts-loader and TypeScript language service and a few unfortunate details in implementation of ts-loader

From the high level TypeScript language service works in the following way:

First it asks the host to provide a list of root files that should be included in the program. Then it will built the program by building transitive closure of all files accessible from root files (via imports, tripleslash references etc). Result program can be used to asked semantic questions, get emit output etc and this program is valid as long as all files that contributed to the program remains unchanged. Once some file is modified language service will try to incrementally parse it and rebuild the program.

What is happening in this case:

ts-loader creates language service and populates it with the initial set of files read from disk. Here there will be plenty of files with placeholders in them that should be substituted by the string-replace-loader and based on this files language service will create initial version of the program. Then once string-replace-loader processes files they are fed to ts-loader. Since content of file after substitution does not match the initial content language service will drop existing program and will build a new one by walking all files and resolving modules and doing other things that don’t make process any faster. What is worse – every file that has placeholders in it will cause re-creation of the program (and this project plenty of them).

In addition to that it seems that ts-loader does not attempt to cache results of module resolution meaning that every time program is rebuild compiler has to repeat module resolution process for every file which is quite expensive.

As an experiment I’ve manually replaced all placeholders in the code and compiled it with command line TypeScript compiler:

D:\sources\bugs\bootstrap>node node_modules/typescript/lib/tsc.js -p tsconfig.json --diagnostics
Files:            1311
Lines:           86351
Nodes:          283600
Identifiers:    101221
Symbols:        256710
Types:           49058
Memory used:   237535K
I/O read:        0.16s
I/O write:       0.13s
Parse time:      2.84s
Bind time:       0.52s
Check time:      2.04s
Emit time:       0.27s
Total time:      5.67s

---
Thanks,
Vladimir Matveev

**Comment by wpitallo** [comment]
Hey, thanks so much. 

Really appreciate the help, I suspected that it may be something with the ts-loader. 

So I understand what you are saying, one thing though that seems a little strange is that the string-replace-loader is configured in Webpack as a pre loader, so I would have thought that this would make the replacements in all the files before handing them over to the ts-load to create the language service. Is there any other way that we could possibly delay the language service until the string-replace-loader has completed replacing on all files? 

With the ts-loader not caching results of module resolution, surly there this will be an issue then with all projects that use Webpack with the ts-loader for their build process? Are you guys currently experiencing the same problem with this or are you not using ts-loader or do you know if there are any later versions that solve this?

Thanks again for the help,

Regards,

Warren

**Comment by wpitallo** [comment]
Hi Vlad, so I found this code below in the ts-loader, and setting the option transpileOnly: true seems to have fixed the issue :) , what are the implications of setting transpileOnly to true though? 

function makeOptions(loader) {
    var queryOptions = loaderUtils.parseQuery(loader.query);
    var configFileOptions = loader.options.ts || {};
    var options = objectAssign({}, {
        silent: false,
        logLevel: 'INFO',
        logInfoToStdOut: false,
        instance: 'default',
        compiler: 'typescript',
        configFileName: 'tsconfig.json',
        transpileOnly: true,
        visualStudioErrorFormat: false,
        compilerOptions: {},
        appendTsSuffixTo: []
    }, configFileOptions, queryOptions);
    options.ignoreDiagnostics = arrify(options.ignoreDiagnostics).map(Number);
    options.logLevel = options.logLevel.toUpperCase();
    // differentiate the TypeScript instance based on the webpack instance
    var webpackIndex = webpackInstances.indexOf(loader._compiler);
    if (webpackIndex === -1) {
        webpackIndex = webpackInstances.push(loader._compiler) - 1;
    }
    options.instance = webpackIndex + '_' + options.instance;
    return options;
}

**Comment by vladima** [comment]
Per [ts-loader documentation](https://github.com/TypeStrong/ts-loader#transpileonly-boolean-defaultfalse):
>transpileOnly (boolean) (default=false)

>If you want to speed up compilation significantly you can set this flag. However, many of the benefits you get from static type checking between different dependencies in your application will be lost. You should also set the isolatedModules TypeScript option if you plan to ever make use of this.

Under the hood it will [use](https://github.com/TypeStrong/ts-loader/blob/master/src/index.ts#L140) `ts.transpileModule` function that will compile only provided source text without resolving external dependencies - this yields better performance at a cost of losing semantic errors (without having all files on hands compiler really cannot tell whether something is misspelled identifier or legal name from another file).

Also ts-loader is not maintained by the TypeScript team so I think if you asked any specific question in [its repo](https://github.com/TypeStrong/ts-loader) you might get better answer directly from authors.

**Comment by mhegazy** [comment]
//cc: @johnnyreilly

**Comment by johnnyreilly** [comment]
@wpitallo

> it seems that ts-loader does not attempt to cache results of module resolution meaning that every time program is rebuild compiler has to repeat module resolution process for every file which is quite expensive.

We would welcome PRs that add this :wink:

Quite apart from that, it's worth saying that ts-loader is built with WebPack 1 in mind (all our CI runs against that). I'm aware some people are using WebPack 2 with it but no efforts have yet been made to support it. They likey will be when W2 leaves beta.

**Comment by wpitallo** [comment]
Thanks very much for the help, appreciate it!
