### ISSUE TITLE
Throw when trying to invoke a class without new

### ISSUE THREAD

**Issue by shlomiassaf** [Microsoft/TypeScript#12408]
**TypeScript Version:**  2.2.0-dev.20161120

On ES6 you can't use classes as if they were functions.

**Code**
```ts
class X {
}
X.apply({});
```

Will throw at runtime:
```
TypeError: Class constructor X cannot be invoked without 'new'
```

However, it will pass typescript checks, even if targeting **es6**

I would expect an error if I target ES6.
IMO, it should throw with ES5 as well by default and only opt in not to throw, otherwise projects with ES5 target will not be able to easily upgrade

@DanielRosenwasser 👍

**Comment by RyanCavanaugh** [comment]
Not sure how far down the rabbit hole we want to go. The `apply` method *does exist*; the fact that it throws an exception doesn't mean it isn't there. We generally don't encode the "this method will throw an exception" into the type system.

**Comment by RyanCavanaugh** [comment]
I don't see any good options here.

If we change the ES5 emit now, who knows who we'll break, and we'll break them in pretty bad ways. People already write ES5-downleveled classes which detect when they're invoked without `new` and fix up the call (by returning `new MyClass()` out of the constructor).

Removing `apply` from the type of the class is clearly wrong -- the method does exist. The fact that it throws isn't something we generally build into the type system.

Adding a switch for this so people can opt in, I mean, [no](http://static.sportskeeda.com/wp-content/uploads/2014/05/formula-1-steering-wheel-2-2181923.jpg).

**Comment by shlomiassaf** [comment]
You can **never** X.apply on a Class.

This is a classical type error that can, and should be prevented in design time.

If JS was a typed language, would it allow it? I guess not since it will never be valid...

TS can help future issues here, a lot.

**Comment by shlomiassaf** [comment]
Well, not many people knows it will be an issue with an ES6 target...

I'm not saying to remove the apply, i'm saying to make it error or maybe a warning...

The current state is that the type system allows a type error that it know about, know it will happen for sure.

let's leave ES5 aside for the moment, I agree it will be a breaking hell.

For es6 at least, you know for sure that it will not work, it will throw 100%, so why allow it?

**Comment by RyanCavanaugh** [comment]
We also could know statically that `new URL('htp;/wo')` is going to throw an exception. It's just a question of scope.

**Comment by shlomiassaf** [comment]
Agreed, but `new URL()` will not work at all targets, right?

```
class X {
}
X.apply({});
```

Will work at es5 but not at es6....
TypeScript **hides** that from the user... so at least a warning?

**Comment by mhegazy** [comment]
TypeScript's type system is structural, and we get a lot of benefit from having a class and a function structurally the same. changing the type to make class.apply uncallable has the effect of breaking that assumption. i would rather live is occasional uncaught exception of calling apply, than introducing this breaking change.
