### ISSUE TITLE
Type guard "x instaceof C" specializing in the else branch

### ISSUE THREAD

**Issue by dimvar** [microsoft/TypeScript#12402]
**TypeScript Version:**  current playground

**Code**

```ts
class Foo {
    private a: number;
}
class Bar {
    private a: number;
}
function f(x: Foo | Bar) {
    if (x instanceof Foo) {
    } else {
        var y: Bar = x;
    }
}
```

**Expected behavior:**

The spec says that the type guard “x instanceof C” doesn’t have an effect in the false case. So, I expect a warning in the else branch.

**Actual behavior:**

x is specialized to Bar. No warning.

@DanielRosenwasser mentioned that this is likely a spec bug.

**Comment by Jameskmonger** [comment]
I agree with @DanielRosenwasser that this is likely an error with the spec.

```
function f(x: Foo | Bar) {
    if (x instanceof Foo) {
    } else {
        var y: Bar = x;
    }
}
```

`x` can either be a `Foo` or a `Bar`, so if it isn't an instance of `Foo` then logically it must be a `Bar`, surely?

**Comment by dimvar** [comment]
Right. The fix for this issue should be in the spec, not the implementation.

**Comment by RyanCavanaugh** [comment]
The spec is now an "archived" artifact and we won't be tracking defects against it anymore.
