### ISSUE TITLE
The spec and the playground disagree on the semantics of instanceof

### ISSUE THREAD

**Issue by dimvar** [microsoft/TypeScript#12401]
**TypeScript Version:**  current playground

**Code**

    class Foo { }
    function f(x: number | Foo) {
        return x instanceof Foo;
    }

**Expected behavior:**

The spec states "The instanceof operator requires the left operand to be of type Any, an object type, or a type parameter type". Expected warning here.

**Actual behavior:**

No warning.

@DanielRosenwasser mentioned that this is probably a spec bug.

**Comment by RyanCavanaugh** [comment]
The spec is now an "archived" artifact and we won't be tracking defects against it anymore.
