### ISSUE TITLE
Using external modules. Import and export doesn't work

### ISSUE THREAD

**Issue by acuemor** [Microsoft/TypeScript#12406]
**TypeScript Version:**  2.0.8 

As I read, using Namespaces in Typescript is not the best choice. Instead, I'm trying to use external modules, but I have some problems.

**Code**

```ts

File1.ts

export class MySrv {
    // ...     
}
export let Services = angular.module("myApp.core").service("mySrv", MySrv);

File2.ts

"use strict";
import * as Services from "../core/mySrv";

class MainAreaCtrl {
    // ...   
}

export default angular.module("myApp.main-area").controller("MainAreaCtrl", MainAreaCtrl);

```

The problem I have is: Uncaught: ReferenceError: Exports is not defined

The question is: How is the correct way to import and export modules in TypeScript using ES2015 syntax?

I try importing the module in different ways:

- import * as Services from  "../core/mySrv.service";

- import {Services} from "../core/mySrv.service";

- import Services = require("../core/mySrv.service");

**Comment by aluanhaddad** [comment]
I need to choose an appropriate loader Rapunzel.

**Comment by mhegazy** [comment]
What module loader are you using? webpack? what module system?
