### ISSUE TITLE
Function type union works unexpectedly

### ISSUE THREAD

**Issue by ethanresnick** [Microsoft/TypeScript#12404]
**TypeScript Version:**  nightly (2.2.0-dev.20161121)

**Code**

```ts
declare const fn: (((...args: any[]) => any) | (() => boolean));

fn(1, 2, 3);
```

**Expected behavior:**
The call to `fn(1, 2, 3)` should succeed, as it should match the `(...args: any[]) => any` part of the union.

**Actual behavior:**

I get the error: "Supplied parameters do not match any signature of call target."

**Comment by alitaheri** [comment]
This is `Working as Intended`. The operator `=>` takes precedence over `|` so:

```ts
type A = (...args: any[]) => any | (() => boolean);
```
Is equivalent to:
```ts
type A = (...args: any[]) => (any | (() => boolean));
```
Not:
```ts
type A = ((...args: any[]) => any) | (() => boolean);
```

Try:

```ts
type AnyFn = (...args: any[]) => any;
declare const fn: (((...args: any[]) => any) | (() => boolean));
declare const fn2: (AnyFn | (() => boolean));

fn(1, 2, 3);
fn2(1, 2, 3);
```
I tested it, works fine.

Be more careful with operator precedence, it bites bad 🙀

**Comment by ethanresnick** [comment]
@alitaheri Thanks. Good call on the precedence, and you're right that with your revised code the two declarations behave equivalently. However, now *both* function calls give an error! So I guess the issue is with how the two types are being unioned? I'll update the OP accordingly.

**Comment by thorn0** [comment]
Duplicate of #7294 ?

**Comment by ethanresnick** [comment]
Seems like it might be, though I'll wait for @RyanCavanaugh to confirm before closing this.

**Comment by ethanresnick** [comment]
Looking at #7294 more closely, they're definitely the same problem conceptually. I'm gonna give this a close.
