### ISSUE TITLE
Operator '+' cannot be applied to types 'T' and 'T'.

### ISSUE THREAD

**Issue by Jameskmonger** [Microsoft/TypeScript#12410]
**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)

**Code**

```ts
function add<T extends string | number>(x: T, y: T): T {
  return x + y;
}

add<string>("a", "b");
add<number>(5, 3);
add("a", "b");
add(5, 3);
```

**Expected behavior:**

Code to compile fine, because `T` is of type `string | number` and therefore can have the `+` operator applied.

**Actual behavior:**

`Operator '+' cannot be applied to types 'T' and 'T'.`

**Comment by arusakov** [comment]
Also doesn't work correctly for simple union type:
```
type X = number | string;

function add(a: X, b: X) {
    return a + b; // Error: Operator '+' cannot be applied to types 'X' and 'X'.
}
```

**Comment by DanielRosenwasser** [comment]
For those who want to tackle this, you might need to use `getConstraintOfTypeParameter`.

**Comment by arusakov** [comment]
Am I right that:
```

**Comment by Jameskmonger** [comment]
@mhegazy I noticed that your comment in #13073 said this should be relaxed for `x + y` when `x` and `y` are both `string | number`, but I'm not sure that aligns correctly with the behaviour in Chrome.

```
function SomeClass (val) {
    this.val = val;
}

SomeClass.prototype.toString = function () {
    return `value [${this.val}]`;
};

var z = (x + x);
console.log(z); // "value [3]value [3]"
```

**Comment by mhegazy** [comment]
looking at this again, i do not think this is as simple as i originally thought. we need to talk about the new rules for the operator.

**Comment by DanielRosenwasser** [comment]
> ```ts
> type U = string | number;
> declare const x: U;
> declare const y: U;
> declare const s: string;
> declare const n: number;
> 
> x + y; // resultType is U
> x + s; // resultType is string
> x + n; // resultType is U
> ```

@arusakov To expand that out: 

```ts
x + y; // resultType is 'string | number'
x + s; // resultType is string
x + n; // resultType is string | number
```

that looks correct. However, if `U` was a type parameter whose constraint was `string | number`, I don't think necessarily think `U` would stick around.

**Comment by mhegazy** [comment]
what about `U + T` where both are constrained to `string | number`.

**Comment by Jameskmonger** [comment]
I think it should be `string | number | T` where `T` is any object with a `toString` method.

**Comment by RyanCavanaugh** [comment]
Accepting PRs for the rules:
 * `T + T` where `T` is constrained to `string` should return `string` (not `T`)
 * `T + T` where `T` is constrained to `number` should return `number` (not `T`)
 * Same rule above applies for all the other math binary and unary operators

`T + T` where `T extends string | number` is still disallowed -- we don't feel this is a good use case because whether you get concatenation or addition is not predictable, thus something that people shouldn't be doing.

**Comment by RyanCavanaugh** [comment]
@Jameskmonger if `T extends string | number` then `T` can be `string | number` which means one value of type `T` can be `string` a different value of type `T` can be a `number`.

It really sounds like you should use overloads here rather than a type parameter.

**Comment by Jameskmonger** [comment]
Ah of course @RyanCavanaugh - I was misunderstanding how generic types work with union types. Thanks for explaining :smile:

**Comment by jack-williams** [comment]
Can this be closed? I think the rules @RyanCavanaugh gave are currently satisfied:

```ts
function addString<T extends string>(x: T, y: T): string {
  return x + y;
}

function addNum<T extends number>(x: T, y: T): number {
  let a = x * y;
  let b = x - y;
  let z = x++;
  return x + y;
}

addString("a", "b");
addNum(1, 2);
```

[Playground](https://www.typescriptlang.org/play/#src=function%20addString%3CT%20extends%20string%3E(x%3A%20T%2C%20y%3A%20T)%3A%20string%20%7B%0D%0A%20%20return%20x%20%2B%20y%3B%0D%0A%7D%0D%0A%0D%0Afunction%20addNum%3CT%20extends%20number%3E(x%3A%20T%2C%20y%3A%20T)%3A%20number%20%7B%0D%0A%20%20let%20a%20%3D%20x%20*%20y%3B%0D%0A%20%20let%20b%20%3D%20x%20-%20y%3B%0D%0A%20%20let%20z%20%3D%20x%2B%2B%3B%0D%0A%20%20return%20x%20%2B%20y%3B%0D%0A%7D%0D%0A%0D%0AaddString(%22a%22%2C%20%22b%22)%3B%0D%0AaddNum(1%2C%202)%3B%0D%0A)

**Comment by mhegazy** [comment]
thanks!
