### ISSUE TITLE
Automatically generating getter and setter

### ISSUE THREAD

**Issue by waderyan** [Microsoft/TypeScript#12417]
_From @user414 on April 24, 2016 12:39_

I couldn't find this issue already existing. I was starting to make variable public just to avoid the setter/getter manual writing, I knew it was time to look for something. Luckily someone beat me to it

https://marketplace.visualstudio.com/items?itemName=DSKWRK.vscode-generate-getter-setter

perhaps this code can be integrated in the mainline, or use as a basis for this new functionality. 

_Copied from original issue: Microsoft/vscode#5716_

**Comment by waderyan** [comment]
_From @dbaeumer on November 15, 2016 19:0_

@waderyan this should come from the TS team.

**Comment by Rhonun** [comment]
Has there been any movement on this?

**Comment by arielalvarez88** [comment]
+1, pretty please

**Comment by davidmach14** [comment]
+1 I'm surprised it's not yet done...

**Comment by JianboYan** [comment]
+1 I'm surprised it's not yet done...

**Comment by Kingwl** [comment]
should this issue for community milestone? @mhegazy

**Comment by mhegazy** [comment]
got for it @Kingwl

**Comment by mhegazy** [comment]
thanks @Kingwl!
