### ISSUE TITLE
fileExists is not a function

### ISSUE THREAD

**Issue by hornetnz** [Microsoft/TypeScript#12411]
Our tests recently started failing when tslint updated and changed its' dependency to typescript v2. Once we updated the necessary version #s in our package json, these errors started appearing once gulp test was executed. 

Module build failed: TypeError: fileExists is not a function at Object.findConfigFile (/Users/###/contacts-ui/node_modules/typescript/lib/typescript.js:58911:17)

I set all the gulp modules to ^ instead of ~ version #s thinking it was another dependency issue, but nothing seems to be working. Can someone point me in the right direction?

[packageJSON.txt](https://github.com/Microsoft/TypeScript/files/604212/packageJSON.txt)

**Comment by mhegazy** [comment]
Can you share more context on how we can reproduce this locally? @ivogabe does this ring a bell?

**Comment by hornetnz** [comment]
Honestly, not sure how to tell you to reproduce locally. I can provide any log or config files needed, but haven't been able yet to make an empty project with the previous version settings to test. I can't say for sure if its a typescript issue, gulp issue, or something else....so thought I'd start here.

**Comment by vladima** [comment]
can you share the source code? NDA can be signed if this is necessary.

**Comment by hornetnz** [comment]
Likely not, its quite a large project. Am trying things with a coworker to see if we can figure it out, but would greatly appreciate any suggestions in the mean time. If we get totally roadblocked, I'll look deeper into if we're allowed to send source. Thanks!

**Comment by ivogabe** [comment]
Could you at least share your gulpfile and the call stack of the error?

**Comment by hornetnz** [comment]
Sure, this is the complete error/trace that we're getting on virtually all the main files. Attached is the gulp build file. Let me know if you were referring to a different gulp file.

ERROR in ./src/app/index.module.ts
Module build failed: TypeError: fileExists is not a function
    at Object.findConfigFile (/Users/nikoleizinsli/contacts-ui/node_modules/typescript/lib/typescript.js:58911:17)
    at ensureInstance (/Users/nikoleizinsli/contacts-ui/node_modules/awesome-typescript-loader/dist/index.js:122:33)
    at compiler (/Users/nikoleizinsli/contacts-ui/node_modules/awesome-typescript-loader/dist/index.js:322:20)
    at Object.loader (/Users/nikoleizinsli/contacts-ui/node_modules/awesome-typescript-loader/dist/index.js:314:14)
 @ multi main


[build.js.zip](https://github.com/Microsoft/TypeScript/files/604591/build.js.zip)

**Comment by ivogabe** [comment]
The stack refers to awesome-typescript-loader; @s-panferov any ideas?

**Comment by hornetnz** [comment]
That was my next action, actually (checking awesome-typescript-loader). It was on 0.14, but the latest is 2.x. Changing that got me past the fileExists errors, but now getting a TON of "Namespace 'ng' has no exported member 'IPromise'."
