### ISSUE TITLE
Inconsistent Error: '--jsx' is not set

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/TypeScript#12429]
**TypeScript Version:**  master, commit 4c6b94f16fbf9752181178a95bb3f53e9d2f6ef2

**Code**

Description follows, download the .zip for a runnable example.

[no_jsx_flag.zip](https://github.com/Microsoft/TypeScript/files/605083/no_jsx_flag.zip)

Note that by default, the compiler setting `allowJs` is false

```ts
// tsconfig.json
{
    "compilerOptions": {
        "moduleResolution": "node"
    }
}

// src/import.ts
import * as a from "a"
import * as b from "b"

// node_modules/a.jsx
export var x;

// node_modules/b.tsx
export var x: number;

```
and compile at the base directory (ie: the one with tsconfig.json), using
```
node /path/to/TypeScript/built/local/tsc.js
```

**Expected behavior:**
Error on both imports

**Actual behavior:**

Only error on the second import (ie: the .tsx one):
```
src/import.ts(2,20): error TS6142: Module 'b' was resolved to '/home/arthur/playground/no_jsx_flag/node_modules/b.tsx', but '--jsx' is not set.

```

**Comment by mhegazy** [comment]
This seems to behave as expected. set `--jsx` for the error to go away.
