### ISSUE TITLE
Object literal in async function should only specify known properties

### ISSUE THREAD

**Issue by andy-ms** [microsoft/TypeScript#12423]
**TypeScript Version:** nightly (2.2.0-dev.20161121 )

**Code**

```ts
function foo(): { x: number } {
    return { x: 1, y: 2 };
}

async function bar(): Promise<{ x: number }> {
    return { x: 1, y: 2 };
}
```

**Expected behavior:**

Both are errors.

**Actual behavior:**

Only the first is an error.

**Comment by yortus** [comment]
A third variant that currently gives no errors:

```ts
function baz(): Promise<{ x: number }> {
    return Promise.resolve({ x: 1, y: 2 });
}
```

That's semantically identical to `bar`. So if `bar` should be an error, what about `baz`?

**Comment by mhegazy** [comment]
the last one is not related. the last one is about using the return type as an inference location, see https://github.com/Microsoft/TypeScript/issues/11152

**Comment by Andarist** [comment]
This one works OK today, so the issue could be closed :) cc @RyanCavanaugh
