### ISSUE TITLE
Parent constructor function parameter depends on subclass constructor's parameter-defined class property

### ISSUE THREAD

**Issue by arlowhite** [Microsoft/TypeScript#12421]
**TypeScript Version:**  2.0.10 and 2.2.0-dev.20161121 

## Code

This is the simplest code that illustrates the problem. Yes, you could avoid the issue by just dropping `this.` within the Child's anonymous function. See bottom of report for description of real-world example.

```ts
class Base {
  constructor(someFunction: () => void) {
    // this.someFunctionNeedsThis should be defined, but is not.
    someFunction();
  }
}

class Child extends Base {
  constructor(private someFunctionNeedsThis: number) {
    // this.someFunctionNeedsThis not defined
    super(() => {
      return this.someFunctionNeedsThis;
    })
    // this.someFunctionNeedsThis defined here
  }
}
```

**tsconfig.json**
```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@app/*": ["app/*"]
    },
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es6", "dom"],
    "mapRoot": "./",
    "module": "es6",
    "moduleResolution": "node",
    "outDir": "../dist/out-tsc",
    "skipLibCheck": true,
    "sourceMap": true,
    "target": "es5",
    "typeRoots": [
      "../node_modules/@types"
    ],
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": false,
    "noFallthroughCasesInSwitch": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "strictNullChecks": false
  }
}
```

## Expected behavior:

`this.someFunctionNeedsThis` should be defined at the time it executes in `Base.constructor`.  
OR  
TypeScript should give an error indicating the code is invalid.

## Actual behavior:

`this.someFunctionNeedsThis` is undefined and no TypeScript error reported.

### TypeScript 2.0.10 generated JavaScript

```js
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};
var Base = (function () {
    function Base(someFunction) {
        someFunction();
    }
    return Base;
}());
var Child = (function (_super) {
    __extends(Child, _super);
    function Child(someFunctionNeedsThis) {
        var _this = this;
        _super.call(this, function () {
            return _this.someFunctionNeedsThis;
        });
        this.someFunctionNeedsThis = someFunctionNeedsThis;
    }
    return Child;
}(Base));
```

### TypeScript 2.2.0-dev.20161121 generated JavaScript

```js
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};
var Base = (function () {
    function Base(someFunction) {
        someFunction();
    }
    return Base;
}());
var Child = (function (_super) {
    __extends(Child, _super);
    function Child(someFunctionNeedsThis) {
        var _this = _super.call(this, function () {
            return _this.someFunctionNeedsThis;
        }) || this;
        _this.someFunctionNeedsThis = someFunctionNeedsThis;
        return _this;
    }
    return Child;
}(Base));
```

## Real-world example

Simplified, but my actual use-case looks more like this:

```ts
import { Observable } from 'rxjs/Observable';

class Base {
  constructor(data$: Observable<any>) {
    data$.subscribe(data => {
      // use data in some way
    });
  }
}

class Child extends Base {
  constructor(data$: Observable<any>, private someFunctionNeedsThis: number) {
    super( data$.map(data => this.processData(data)) );
  }

  processData(data: any) {
    // some kind of data processing depending on constructor property
    return this.someFunctionNeedsThis * data;
  }
}
```

### TypeScript 2.2.0-dev.20161121 generated JavaScript
```js
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};
var Base = (function () {
    function Base(data$) {
        data$.subscribe(function (data) {
            // use data in some way
        });
    }
    return Base;
}());
var Child = (function (_super) {
    __extends(Child, _super);
    function Child(data$, someFunctionNeedsThis) {
        var _this = _super.call(this, data$.map(function (data) { return _this.processData(data); })) || this;
        _this.someFunctionNeedsThis = someFunctionNeedsThis;
        return _this;
    }
    Child.prototype.processData = function (data) {
        // some kind of data processing depending on constructor property
        return this.someFunctionNeedsThis * data;
    };
    return Child;
}(Base));
```

## Solutions?

Constructor defined class properties could be set before calling super. However, this violates the rule that the super constructor is the first thing to execute. This could get ugly if the property has a setter or getter with side-effects.

So a TypeScript error seems like the correct solution but I have no idea if it's actually possible (or easy) to detect this error. You would need to trace all execution paths given to super() via arguments and determine if any depended on class properties defined in the constructor.

One could argue that constructor parameter-defined class properties are inherently ambiguous. It is not obviously clear to the programmer if they are defined before the super.constructor executes or after. So there is an argument to remove the feature from the TypeScript language. _Although this makes me sad because I do like the feature._

**Comment by RyanCavanaugh** [comment]
The problem here isn't the parameter property per se -- properties with initializers also have this problem.

The real missing piece of information is that the function expression is immediately executed. If the function were executed later, there wouldn't be a problem. If we knew the expression was immediately invoked, we could disallow use of `this` inside it (this code errors in ES6 due to access of an unready `this`).

**Comment by kevinsbennett** [comment]
I ran into this one as well.  Perhaps a solution would be to generate something like:

`
var _this = this;
_this = super(....) || this;
`
instead of what it is doing now?

**Comment by RyanCavanaugh** [comment]
It's an error in ES6 to refer to` this` before calling `super`.

**Comment by kevinsbennett** [comment]
@RyanCavanaugh, perhaps Typescript should be generating something different when targeting ES5?  That's our use case anyways.

**Comment by RyanCavanaugh** [comment]
We don't want to introduce a blocker to the upgrade path - if people write TS code targeting ES5 and then find they can't migrate to ES6 (or worse, their code runs differently between ES5 and ES6), that's subtracting value rather than adding it.

**Comment by HTMLangdon** [comment]
perhaps the solution lies with using rested parameters in a class/classes if one knows they will need to pass more data through to the constructor than what the super classes require? 

But imo if you're extending a class  - and the subclass requires different data in the constructor than it's superclass - could this be a rule/indication that it should not have extended the initial class in the first place? Just a thought :P
