### ISSUE TITLE
Incorrect emit of `__metadata('design:paramtypes', [])` when using `emitDecoratorMetadata` and inheritance

### ISSUE THREAD

**Issue by tbosch** [Microsoft/TypeScript#12439]
**TypeScript Version:**  2.1.1

Flags: `emitDecoratorMetadata: true`

**Code**

```ts
class SomeArg {}

function SomeDecorator(): any {}

@SomeDecorator()
class Parent {
  constructor(a: SomeArg) {}
}

@SomeDecorator()
class Child extends Parent {
}
```

**Expected behavior:**
Does not emit `__metadata('design:paramtypes', [])` for `Child` or declares the parameters from the parent class, as `Child` did not declare an own constructor so the constructor of the parent class gets inherited.

I.e.
```
Parent = __decorate([
    SomeDecorator(),
    __metadata("design:paramtypes", [SomeArg])
], Parent);
...
Child = __decorate([
    SomeDecorator(),
], Child);
```

**Actual behavior:**
Emits `__metadata('design:paramtypes', [])` as part of the decorators for `Child`. This is wrong as the the constructor is inherited so `Child` actually takes one argument of type `SomeArg`, in contrast to the value of `__metadata('design:paramtypes', [])`.

I.e.
```
Parent = __decorate([
    SomeDecorator(),
    __metadata("design:paramtypes", [SomeArg])
], Parent);
...
Child = __decorate([
    SomeDecorator(),
    __metadata("design:paramtypes", [])
], Child);
```

** Other notes
It would be really nice to be able to turn on flags as well as choose the typescript version in the typescript playground, so I could post a working reproduction here.

** Workaround
To detect that a class did not declare its own constructor we can use a regex on `Child.toString()`:
```
const DELEGATE_CTOR = /^function\s+\w+\(\)\s*{\s*(return\s+)?\w+\.apply\(this,\s*arguments\)/;

function isDelegateCtor(ctor: any) {
  return DELEGATE_CTOR.exec(ctor.toString());
}
```

Note that this workaround also works with minified code as none of `function` / `apply` / `arguments` can be minified.

**Comment by david-driscoll** [comment]
I'm also seeing something that is related.  If the parent is decorated in TS2.0 and below, the child would also compile as if it were decorated.  This is no longer the case.

**Comment by mhegazy** [comment]
@tbosch and @david-driscoll the fix should be in tonight's `typescript@next` (published some time around 12:00 am PST). please give it a try and let us know if you are still running into issues.

**Comment by tbosch** [comment]
@mhegazy Thanks, this seems to work now!
