### ISSUE TITLE
VS2015 problems with ts 2.x and tsconfig.json generating files

### ISSUE THREAD

**Issue by wstaelens** [Microsoft/TypeScript#12438]
**TypeScript Version:**  2.0.6.0
**Visual Studio Version**: 2015 Pro update 3 (tested with running as administrator and normal)

**Code**

```ts
{
  "compileOnSave": true,
  "compilerOptions": {
    "noImplicitAny": true,
    "noEmitOnError": true,
    "removeComments": false,
    "sourceMap": true,
    "target": "es5",
    "outDir": "./Scripts/ts"
  },
  "files": [
    "./src/bing-mapcluster-v8.ts"
  ]
}
```

**Expected behavior:**
I expected that the generated file  /Script/ts/bing-mapcluster-v8.js should be directly visible and added to my project in source control.

**Actual behavior:**
I followed https://www.typescriptlang.org/docs/handbook/asp-net-4.html and I never saw a .js file in the output dir /Scripts/ts. Similar to my own bing-mapcluster file.

Untill I found out that the .js files are actually generated but are not included in the project. 
In Visual Studio Solution Explorer if I click **[Show all files**] I saw the .js file. **(took ages to find out the file was not visible!!)**
I had to right click the files and manually include them to the solution and source control.

I think there seems to be a problem with typescript files being generated and not being added to visual studio solution.

The only thing I've seen in output is this message from TFS, but I don't see if it is generated by typescript generating files or not.

> We were unable to automatically populate your Visual Studio Team Services accounts.
    
> The following error was encountered: TF400813: Resource not available for anonymous access. Client authentication required.

Not sure if this is important:
I'm using TFS on <user>.visualstudio.com  with Visual Studio [Team] -> [Team Project Settings] -> [Source Control...] -> [Check-out Settings] -> [Enable multiple check-out: DISABLED] and [Enable get latest on check-out: ENABLED]

Also for some reason if I go to Project properties -> [TypeScript Build] -> the properties are disabled with this message: [One or more tsconfig.json files detected. Project properties are disabled.].
 But I only have one tsconfig.json ! 

(just started using typescript, and lost already so much time just to get it working with VS2015)

**Comment by mhegazy** [comment]
> I expected that the generated file /Script/ts/bing-mapcluster-v8.js should be directly visible and added to my project in source control.

The .js files are not added to the project. they are considered outputs of your build process, similar to your C#/VB .dll files.

> Also for some reason if I go to Project properties -> [TypeScript Build] -> the properties are disabled with this message: [One or more tsconfig.json files detected. Project properties are disabled.].
But I only have one tsconfig.json !

tsconfig.json is an alternative way to set your compilation settings. You can set your project build properties through the property page if you do not have a tsconfig.json file in your project. if one is available the property pages is disabled. There are config options that you can only set in a tsconfig.json, e.g. `paths`. We recommend you use the tsconfig.json file moving forward. 

hope that helps.

**Comment by wstaelens** [comment]
Thanks for the info, but as a beginner this was not clear.
Maybe an improvement to notify the user that files are created but possibly not visible?
(this info should be added to that asp.net 4 tutorial to make it better for beginners)
