### ISSUE TITLE
Property hints for union types

### ISSUE THREAD

**Issue by trubit** [microsoft/TypeScript#12430]
Provide property hints for union types. See union type of `field` property of `Selector` interface.

**Actual behavior:**
```ts
interface Conditions {
    cond: any;
}

interface Selector {
    field: Conditions | string;
}

function find(options: Selector) {};

find({
    field: {
        // <-- does not hint `cond` property of Conditions even if its required
    }
});
```

It clearly knows something is missing:
```
Argument of type '{ field: {}; }' is not assignable to parameter of type 'Selector'.
  Types of property 'field' are incompatible.
    Type '{}' is not assignable to type 'string | Conditions'.
      Type '{}' is not assignable to type 'Conditions'.
        Property 'cond' is missing in type '{}'.
```

Typechecker is working great here even in more complicated cases. But hints should give me results for possible properties, in this case `cond`.

Consider more complicated scenario:
```ts
interface Conditions {
    cond: any;
}

interface Combinations {
    comb?: any;
}

interface Selector {
    field: Combinations | Conditions | string;
}

function find(options: Selector) {};

find({
    field: {
        // type hint here
    }
});
```

Code is now valid, because Combinations allows undefined `comb` property. Hints should give me possible properties in all union types. In this case it should be `comb` and `cond` property.

The thing is what if I make `comb` required. In this case, object can have only `cond` or `comb` property, not both at once. Reality is, it can have both and can have even other non existing properties, see note below.
Anyway type hinter knows this and can provide hints about both possible properties.

I think it can hint all possible types in all cases. Again:

```ts
interface Conditions {
    cond: {
        data: string
    };
}

interface Combinations {
    cond: {
        sub: number
    };
}

interface Selector {
    field: Combinations | Conditions | string;
}

function find(options: Selector) {};

find({
    field: {
        cond: {
            // validator knows something missing, but hints silent
        }
    }
})
```

**Can it be done?**

Note, possible bug?:
```ts
interface Conditions {
    cond: {
        data: string
    };
}

interface Combinations {
    cond: {
        sub: number
    };
}

interface Selector {
    field: Combinations | Conditions | string;
}

function find(options: Selector) {};

find({
    field: {
        cond: {
            data: "",
            notExistingProperty: true // see here, should be non valid
        }
    }
});
```
This is still valid code even if should not be.

**Comment by RyanCavanaugh** [comment]
This now works
