### ISSUE TITLE
Two tsconfig files with Dependency issue

### ISSUE THREAD

**Issue by McSiMusic** [Microsoft/TypeScript#12432]
**TypeScript Version:**  2.0.3

I have solution with two ts config files. The solution has such folder structure:
![solution structure](https://cloud.githubusercontent.com/assets/18289205/20510429/d635bea4-b0a2-11e6-90e3-ceb46aab926f.jpg)

**Root tsconfig.json:**
```json
{
  "compilerOptions": {
    "declaration": true,
    "outFile":  "Test/Namespace.js" 
  }
}
```

**Test\tsconfig.json:**
```json
{"compilerOptions": {}}
```

Test.ts has dependency from Namespace.d.ts.

**Expected behavior:**
Success build: Namespace1.ts build creates Test/Namespace.d.ts and Test.ts successfully built.
**Actual behavior:**
Build failed: wrong compilation order.

Is there a way to change the compilation order for tsconfig files, or continue the build despite other tsconfig errors?
[Question on stackoverflow](http://stackoverflow.com/questions/40674475/two-tsconfig-files-with-dependency-issue)
[Solution zip](https://github.com/Microsoft/TypeScript/files/605431/VSTypeScriptIssue.zip)

**Comment by mhegazy** [comment]
Replied to your [SO](http://stackoverflow.com/questions/40674475/two-tsconfig-files-with-dependency-issue/40734872#40734872) question.

**Comment by McSiMusic** [comment]
I posted a comment on [your reply](http://stackoverflow.com/questions/40674475/two-tsconfig-files-with-dependency-issue/40734872#40734872).
