### ISSUE TITLE
Find all refs/rename for mapped type symbols

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#12450]
```ts
type T = { a: number, b: string };
type O = Partial<T>;
var t: T = { a: 1, b: "s" };
var o: O = { a: 3 };
```

renaming `a` should rename both instances of `a` `T.a` and `O.a`.

**Comment by pavel-agarkov** [comment]
Hello.
Rename does not work when you map namespaces or objects imported from another module .
For example:
```typescript
namespace Core {
    export class Class1 { static order: "1" }
    export class Class2 { static order: "2" }
}

type CoreTypes = keyof typeof Core;
type CoreObject = {[P in CoreTypes]: typeof Core[P]["order"]};
const core: CoreObject = {
    Class1: "1",
    Class2: "2"
}
```
I don't even talk about `order` property. The main problem is that class name rename does not rename property of `CoreObject`.
Everything works the same way when I use imports instead of namespaces:
```typescript
import * as Core from "./file-with-exported-classes"
```

> IDE: VSCode 1.15.1 / VS2017 15.3.3
> TypeScript: 2.5.2
> Node: 6.11.0

Would it be considered as a bug/improvement request?
Thank you.

**Comment by andy-ms** [comment]
Hi @pavel-agarkov, your example works if you remove the `CoreTypes` type alias and write `type CoreObject = {[P in keyof typeof Core]: typeof Core[P]["order"]};` directly.
A simpler example:
```ts
interface X { x: number };
type Key = keyof X;
const a: { [P in Key]: string } = { x: "" }; // Can't find reference for `x`
const b: { [P in keyof X]: string } = { x: "" }; // Successfully find reference for `x`
```
I'm not sure if this is a bug or a limitation of the way we do mapped types. CC @sandersn

**Comment by pavel-agarkov** [comment]
Thank you, @andy-ms 
It works as you said.
It a little bit less handy since even my example is way more simplified compared to the real world...
But I can live with it :)

**Comment by OliverJAsh** [comment]
For some reason this doesn't work when the `Record` type alias is used:

``` ts
{
  type T = { a: number, b: string };
  type O = Record<keyof T, {}>;
  var t: T = { a: 1, b: "s" };
  var o: O = { a: 3 };
}
```

I filed a separate issue https://github.com/Microsoft/TypeScript/issues/20272
