### ISSUE TITLE
Indicate if field is optional

### ISSUE THREAD

**Issue by normalser** [Microsoft/TypeScript#12458]
Not sure if this is for `vscode` or `TSServer` so I will start here.

It would be great if intellisense could show (maybe ? icon) which fields are optional:

![image](https://cloud.githubusercontent.com/assets/1723815/20550214/618fffa6-b101-11e6-8f0d-a5cb1c8a1672.png)

**Comment by DanielRosenwasser** [comment]
See also #1411.
