### ISSUE TITLE
Formatting Inserts Extra Space in JSX Element With Function Parameter 

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#12456]
From https://github.com/Microsoft/vscode/issues/15929

TypeScript: 2.0.10 and 2.2.0-dev.20161121

With a jsx file:

```js
(<input ref={() => { return; }} />)
```

**Expected**
Running formatting on the document does nothing in this case.

**Actual**
An extra space is inserted between the two `}` characters:

```js
(<input ref={() => { return; } } />)
```
 
This is inconsistent with how formatting works for other argument types. The issue seems similar to #9823

**Comment by SaschaNaz** [comment]
Covered by #13092.

**Comment by mhegazy** [comment]
thanks @SaschaNaz !
