### ISSUE TITLE
Automatically Acquire Typings For Packages Installed Without --save

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#12453]
From https://github.com/Microsoft/vscode/issues/15844

**Repo**
1. Create an empty node project.
2. Create an `index.js` file, put:

  ```js
  var _ = require('lodash')
  ```

3. Run `npm install lodash`

**Expected Behavior**
Typings are automatically acquired for `lodash` after the install completes.

**Actual Behavior**
No typings are acquired after the install is complete. In the VSCode side, we have to trigger a file edit or project reload in order for the typings to be downloaded. 

Typings are properly acquired if you run `npm install --save lodash`. It also works if open a project that has `lodash` installed but not listed in the `package.json`. The broken scenario is where the tsserver is already running when `npm install lodash` is run.

**Comment by mhegazy** [comment]
This should be working as explained in the TS 2.1.4. In TS 2.0.* ATA did not look at module imports, starting with TS 2.1.* they are. so you do not need to install the package even.

**Comment by mhegazy** [comment]
closing in favor of https://github.com/Microsoft/TypeScript/issues/11256
