### ISSUE TITLE
async/await problem with IE11

### ISSUE THREAD

**Issue by rogergl** [Microsoft/TypeScript#12469]
TypeScript Version:  2.1.1 

**Code**

```ts
  let {value} = await ProjectHelperService.hpn();
```
**Expected behavior:**

using await async with target ES5 should work with IE11

**Actual behavior:**

IE11 gives the following error message:

ReferenceError: "Promise" ist undefiniert

at this location:

```ts
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    return new (P || (P = Promise))(function (resolve, reject) {
```

**Comment by arciisine** [comment]
You probably need to provide a promise polyfill, as async/await rely upon that, but the downlevel generation does not provide that.

**Comment by rogergl** [comment]
Yes, including a promise polyfill solved the problem.
