### ISSUE TITLE
Readonly properties problem in declaration files

### ISSUE THREAD

**Issue by andtii** [Microsoft/TypeScript#12468]
**TypeScript Version:** 2.0.6

```
export class Ajax {
    public static get Application_JSON(): string { return "application/json"; }
}

//generates the following in d.ts
export declare class Ajax {
    static Application_JSON: string;
}
```
**Expected behavior:**
No build errors
**Actual behavior:**
A build error is being thrown

**Comment by mhegazy** [comment]
Please see https://github.com/Microsoft/TypeScript/issues/10412, https://github.com/Microsoft/TypeScript/pull/6702#issuecomment-213627081 and https://github.com/Microsoft/TypeScript/issues/7573.
