### ISSUE TITLE
Type checker incorrectly refuses object spread of null or undefined

### ISSUE THREAD

**Issue by Kovensky** [Microsoft/TypeScript#12460]
**TypeScript Version:**  2.2.0-dev.20161122

With `--strictNullChecks`.

**Code**

```ts
function spread(arg?: {}): {} {
  return {...arg}
}
spread()
```

**Expected behavior:**

`spread()` returns empty object `{}`.

**Actual behavior:**

`Spread types may only be created from object types.`

---

The spec specifically allows `null` and `undefined` spread arguments by having an early check before the `ToObject` abstract operation ([3.1.2](https://sebmarkbage.github.io/ecmascript-rest-spread/#AbstractOperations-CopyDataProperties)).

**Comment by mhegazy** [comment]
@Kovensky please give tonight's `typescript@next` a try and let us know if you are still seeing issues.

**Comment by Kovensky** [comment]
@mhegazy is there a way to know which commit was used to build a given nightly?

**Comment by mhegazy** [comment]
The nightly snaps at 11:00 pm PST, anything merged in master before that should be there.

**Comment by mjomble** [comment]
I found some cases where this is still an issue:

```typescript
// Logs three empty objects without errors in JavaScript.
// Shows three "Spread types may only be created from object types." errors in TypeScript.
// Tested on TypeScript Playground on May 26, 2018.

const spread = <T extends object>(arg: T | null) => ({ ...arg })
console.log(spread(null), { ...null }, { ...undefined })
```

[Playground link](https://www.typescriptlang.org/play/index.html#src=%2F%2F%20Logs%20three%20empty%20objects%20without%20errors%20in%20JavaScript.%0D%0A%2F%2F%20Shows%20three%20%22Spread%20types%20may%20only%20be%20created%20from%20object%20types.%22%20errors%20in%20TypeScript.%0D%0A%2F%2F%20Tested%20on%20TypeScript%20Playground%20on%20May%2026%2C%202018.%0D%0A%0D%0Aconst%20spread%20%3D%20%3CT%20extends%20object%3E(arg%3A%20T%20%7C%20null)%20%3D%3E%20(%7B%20...arg%20%7D)%0D%0Aconsole.log(spread(null)%2C%20%7B%20...null%20%7D%2C%20%7B%20...undefined%20%7D)%0D%0A)
