### ISSUE TITLE
New Website Logo: itch.io

### ISSUE THREAD

**Issue by fasterthanlime** [Microsoft/TypeScript#12470]
- Name: itch.io
- Homepage url: https://itch.io
- Brand Guidelines/Licensing: https://itch.io/press-kit/
- Logo: downloads available at https://itch.io/press-kit/ (including .svg)

Our desktop app, https://itch.io/app, is 100% typescript as of v20.0.0!

**Comment by RyanCavanaugh** [comment]
I might have to check this out!

**Comment by fasterthanlime** [comment]
Let me know if you need any other details!

**Comment by fasterthanlime** [comment]
Any news? :slightly_smiling_face:

**Comment by mhegazy** [comment]
i usually do them in patches. sorry have not had time to do it the last few weeks. will do one more next week.

**Comment by DanielRosenwasser** [comment]
Thanks! You should see the changes get applied next time we publish the site.

**Comment by DanielRosenwasser** [comment]
Should be up!
