### ISSUE TITLE
Iterator in for ... of loop transpiled to use length property which is undefined

### ISSUE THREAD

**Issue by jasonpang** [Microsoft/TypeScript#12484]
**TypeScript Version:**  nightly (2.2.0-dev.20161118)

**Chrome Version:** Stable 54.0.2840.99 (Official Build) m (64-bit) (*Revision 7eca4ce1e662f12cadaf96c30cd2335fd03e7140-refs/branch-heads/2840@{#830}*)

**TypeScript Code: (relevant portion)**
```ts
for (var param of iterator) {
```

**Transpiled ES5 JavaScript (relevant portion):**
```js
 for (... ; _i < iterator_1.length; _i++) {
                 ^^^^^^^^^^^^^^^^^
                 length is undefined
```

**Screenshot of Transpiled ES5 Code:**

![image](https://cloud.githubusercontent.com/assets/1015970/20598496/3b1a464e-b1fe-11e6-9ea6-a492f56d10b4.png)

**Expected behavior:**
Using `for (var x of iterator) { ... }` should be transpiled correctly.

**Actual behavior:**
The iterator loop is transpiled to use the `length` property which appears to be undefined for the iterator.

**Reproducible Project**

For some reason, GitHub isn't allowing me to upload a `.zip` file, so here's a Google Drive link to the project ZIP: https://goo.gl/xvbwHu.

**Comment by kitsonk** [comment]
That would have been a compile time error.

Dupe of #11209 and others...

**Comment by jasonpang** [comment]
Makes sense, I also see this at the bottom here: https://www.typescriptlang.org/docs/handbook/iterators-and-generators.html
