### ISSUE TITLE
TypeScript 2.1.x (npm) - has it been released or not?

### ISSUE THREAD

**Issue by marcin-mazurek** [Microsoft/TypeScript#12485]
I'm trying to use latest TypeScript, I installed TS via npm:

```
$ npm i typescript --save
angular-2-playground@0.0.1 C:\Users\Marcin_Mazurek\Projects\angular-2-playground
`-- typescript@2.0.10
```

But according to Github the lastest version is 2.1.2. So I tried `npm update`:

```
$ npm update typescript
angular-2-playground@0.0.1 C:\Users\Marcin_Mazurek\Projects\angular-2-playground
`-- typescript@2.1.1
```

I got version 2.1.1 (not denoted with RC/alpha/beta/anything else). According to Github the latest version is 2.1.1, whereas npm website says the latest release is 2.0.10 (https://www.npmjs.com/package/typescript). Could you please help me make sense of it? Has 2.1 been released or not?

**Comment by kitsonk** [comment]
Per `npm view typescript`:

```js
{ 'dist-tags': 
   { latest: '2.0.10',
     next: '2.2.0-dev.20161124',
     beta: '2.0.0',
     rc: '2.1.1',
     insiders: '2.0.6-insiders.20161017' } }
```

2.1.X is at release candidate stage, but it not yet the latest version.
