### ISSUE TITLE
Why error (about Indexable Types)

### ISSUE THREAD

**Issue by wjtGitHub** [Microsoft/TypeScript#12486]
**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)

**Code**

```ts
// A *self-contained* demonstration of the problem follows...

interface test{
   [index: number]:number;
   length: number;
}

 let abc:test;
 abc[1] = 213;
 console.log(abc[1]);
```
**error tip**
```
abc[1] = 213;
TypeError:Cannot set property '1' of undefined
```

**Expected behavior:**

**Actual behavior:**

**Comment by HolgerJeromin** [comment]
Typescript does not initialize the interface for you.
`let abc: test = {length: 0};`

**Comment by DanielRosenwasser** [comment]
TypeScript should even tell you that you're using `abc` before you've assigned it.

![image](https://cloud.githubusercontent.com/assets/972891/20606784/3177bbce-b241-11e6-8928-f7ff13c19abc.png)

**Comment by wjtGitHub** [comment]
Thank those who helped me
