### ISSUE TITLE
Unable to publish a package to NPM with both d.ts files and ts files

### ISSUE THREAD

**Issue by Roaders** [Microsoft/TypeScript#12495]
Hi All

I am trying to publish a strongly typed package to NPM that I can then use in other projects without having to manually import typing information. I have looked at this very helpful guide:

https://medium.com/@mweststrate/how-to-create-strongly-typed-npm-modules-1e1bda23a7f4#.u17bputcb

which got me most of the way but not all the way.

Consider the following setup:

**server.ts**
```
import {IDatabaseConnection} from "./contracts"

export class MyServer{
    constructor(private db: IDatabaseConenction){}
}
```
**database.ts**
```
import {IDatabaseConnection} from "./contracts"

export class DatabaseConnection implements IDatabaseConenction{
    constructor(){}
}
```
**contracts.d.ts**
```
export interface IDatabaseConnection{}
```
**exports.ts**
```
import * as Contracts from "./contracts";
import * as Database from "./database";
import * as Server from "./server";

export{Contracts, Browser, Node};
```

in my `package.json` I set main as `exports.js` and typings as `exports.d.ts`.

This all builds fine and can be published to npm no problem. In the project that is consuming this package I can use the types as follows:

```
import * as mypackage from "mypackage";

var connection: mypackage.Contracts.IDatabaseConnection 
connection = new mypackage.Database.DatabaseConnection();
var server = new mypackage.Server.MyServer()
```

This all compiles fine as well. However, when I run it in node I get an error:

`cannot find module './contracts'`

This is because the `exports.js` file is referring to `./contracts` but there is no `contracts.js` file. As it is a `d.ts` it does not produce a javascript file. The `contracts.d.ts` file is there which is why the compilation works but at runtime node dies.

What needs to happen is at compile time of the package the `exports.js` file needs to leave out the `./contracts` import but this needs to stay in the `exports.d.ts` file.
Another solution is the ability to specify extra `d.ts` files in the `package.json` file.

At the moment I can see 2 workarounds:

- turn `contracts.d.ts` into `.ts` file and include an empty `.js` file in our package
- have the consumer of the package add a reference to `node_modules/mypackage/contracts.d.ts`. This is not good as it requires knowledge of the internals of the package.

**Comment by pocesar** [comment]
the generated .d.ts file uses `/// <reference` at the top, it also deals with importing interfaces from other files. if you build it using `declarations: true` in compilerOptions, you won't have to do this manually

**Comment by aluanhaddad** [comment]
> I am trying to publish a strongly typed package to NPM that I can then use in other projects without having to manually import typing information. I have looked at this very helpful guide:
> 
> https://medium.com/@mweststrate/how-to-create-strongly-typed-npm-modules-1e1bda23a7f4#.u17bputcb

This "helpful guide" is an awful combination of outdated, incorrect, and terrible advice.

**Comment by aluanhaddad** [comment]
The use of `export * as ns from 'module'` prevents the compiler from being able to remove the import.

**Comment by Roaders** [comment]
@aluanhaddad how do I import the contracts in a way that it can be removed from the generated js but retained for the generated d.ts file?
Thanks for the replies

**Comment by Roaders** [comment]
Is there a more up to date and accurate guide on this subject?

**Comment by aluanhaddad** [comment]
The following will work in this case:
```ts
export * from "./contracts";
export * from "./database";
export * from "./server";
let Browser;
let Node;
export { Browser, Node };
```
compiles into the following

**Comment by Roaders** [comment]
Many thanks. That fixed it.

In all the documentation I have read I have seen very little about how to deal with d.ts files when publishing. Nowhere on the [typescript page about modules](https://www.typescriptlang.org/docs/handbook/modules.html) does it mention the fact that certain forms of import will not get removed.

Are there better sources of documentation on this?

**Comment by aluanhaddad** [comment]
@Roaders you can find a little bit of information in [handbook/modules](http://www.typescriptlang.org/docs/handbook/modules.html). I seem to remember there being more documentation on this subject but I cannot find it just now.
