### ISSUE TITLE
Overloading in classes and interfaces

### ISSUE THREAD

**Issue by arusakov** [Microsoft/TypeScript#12492]
**TypeScript Version:**  master(e128add54eb13192f1ec836a6623ae765fcaa758)

**Code**

```ts
interface X {
    foo(bar: { x: 1 }): number;
    foo(bar: { x: 2 }): string;
}

class Y {
    // overloading like in X
    foo(bar: { x: 1 }): number;
    foo(bar: { x: 2 }): string;
    foo(bar: any): any {}
}

class Z implements X {
    foo(bar: any): any {}
}

declare const x: X;
x.foo({ x: 1 }); // ok - number
x.foo({ y: 1 }); // ok - error

new Y().foo({ x: 2 }); // ok - string
new Y().foo({ y: 2 }); // ok - error

new Z().foo({ x: 3 }); // NO ERROR
```

**Expected behavior:**
An error at `new Z().foo({ x: 3 })`. Because for me `class Y` and `class Z` are the same.

**Actual behavior:**
Described in code.

**Comment by aluanhaddad** [comment]
In the following
```ts
class Z implements X {
    foo(bar: any): any {}
}
```
`Z` implements `X` by providing a single signature that meets the requirements of both overloads and is also, incidentally, applicable to an argument of any type.

However in
```ts
class Y {
    // overloading like in X
    foo(bar: { x: 1 }): number;
    foo(bar: { x: 2 }): string;
    foo(bar: any): any {}
}
```
`Y` declares an overload with _**2**_ signatures. The signature of the actual implementation of an overloaded _class_ method is not part of a its type.
