### ISSUE TITLE
Different boolean results with regex

### ISSUE THREAD

**Issue by wstaelens** [Microsoft/TypeScript#12499]
**TypeScript Version:**  TypeScript for Microsoft Visual Studio 2.0.6.0
Visual Studio Professional 2015 version 14.0.25431.01 Update 3
Windows 10 Pro x64

```ts
class DebugHelper {

    public static readonly RegexRanges: RegExp = /(?=(v=\d+[_]\d+[_]\d+[,]){0,})(\d+[_]\d+[_][imd]\(\d+([.,]\d{1,3})?[-]\d+([.,]\d{1,3})?\)){1,}/g;

    testBooleanLogic(par: string) : boolean {
        if (par === "undefined" || par === null || !DebugHelper.RegexRanges.test(par)) {
            return false;
        }
        return true;
    }

    testBooleanLogicStrings(pars: string[]) : boolean[] {
        let results: boolean[] = new Array<boolean>();

        for (let i = 0; i < pars.length; i++) {
            let r = this.testBooleanLogic(pars[i]);
            results.push(r);
        }
        return results;
    }

}

let helper = new DebugHelper();

// when b0 is uncommented and executed first it returns true! 
//let b0: boolean = helper.testBooleanLogic("5_28_i(1992-2000)");
//alert(b0); // true (when executed first)

let b1: boolean = helper.testBooleanLogic("5_26_i(5-17)");
alert(b1); // true

let b2: boolean = helper.testBooleanLogic("5_28_i(1992-2000)");
alert(b2); // false


let bs: boolean[] = helper.testBooleanLogicStrings(["5_26_i(5-17)", "5_28_i(1992-2000)"]);
alert(bs[0]); // true
alert(bs[1]); // false
alert(bs[0]); // true
alert(bs[0]); // true
alert(bs[1]); // false
alert(bs[1]); // false
```

**Expected behavior:**
everything should be true.

**Actual behavior:**
this gives:
**true, false, true, false, true, true, false, false**
and when I uncomment b0 I get:
true, **false, true, false, true, false, false, true, true**

Or maybe it is because it is Friday? 😕 ☕️

**Comment by DanielRosenwasser** [comment]
JavaScript RegExps are stateful when you use the global (`g`) flag on them. I'm sorry.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/lastIndex

http://stackoverflow.com/questions/11477415/why-does-javascripts-regex-exec-not-always-return-the-same-value

http://bjorn.tipling.com/state-and-regular-expressions-in-javascript

For future reference, this is not the right place to ask questions like this. Please use StackOverflow in the future, as suggested in our issue template:

>  QUESTIONS: This is not a general support forum! Ask Qs at http://stackoverflow.com/questions/tagged/typescript
