### ISSUE TITLE
[feature request] Parse date with custom format

### ISSUE THREAD

**Issue by wstaelens** [Microsoft/TypeScript#12496]
Now you only have:

```TypeScript
Date.parse(s: string) : number
```

Allow to parse a date on a given format:

```TypeScript
Date.parse(s: string, format: string) : number
```
This would allow you to write code like:
```TypeScript
let myDate : string = "20161125";
let customFormat : string  = "yyyyMMdd";

let myDate = Date.parse(myDate , customFormat);
```

**Comment by aluanhaddad** [comment]
This would be a new runtime utility function. TypeScript does not have a runtime and providing one is an explicit non-goal of the language. The declaration files shipped with the language statically define the runtime libraries that are to be provided by conforming ECMAScript implementations.

Furthermore, the ECMAScript specification does not specify such and implementation of `Date.parse` how are you free to write your own and attach it to the built-in `Date` object. TypeScript allows the associated typing implications of such an augmentation to be expressed very naturally.

However, you may want to look into existing libraries such as _moment.js_ that provide extensive facilities for parsing and manipulating dates. 
`moment.js` ships with typescript declarations out of the box if you install it via a package manager such as npm, jspm, or bower. This makes it a convenient option.

**Comment by wstaelens** [comment]
thanks for the info! didn't know about moment.
