### ISSUE TITLE
Array filter/map predicate not type checking properly

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/TypeScript#12498]
TS 2.0.3

See the comments and last line in the code below for expected/actual.

``` ts
{
    type Foo = { foo: true };
    const isFoo = (foo: Foo) => foo.foo;

    const xs = [{ foo: true }, undefined];

    isFoo(xs[1]) // good, errors
    const x = undefined as Foo | undefined;
    isFoo(x) // good, errors
    xs.filter(isFoo) // bad, didn't fail, expected filter arg to fail, should be Foo | undefined
}
```

**Comment by aluanhaddad** [comment]
This is expected. Consider
```ts
declare function f(x: number): any;
declare function g(x?: number): any;
declare function h(x: number | undefined): any;
let i = f;
i = g;
i = f;
i = h;
let k = f;
k = h;
k = g;
```
Also, see this section of the handbook. [type-compatibility](http://www.typescriptlang.org/docs/handbook/type-compatibility.html)

**Comment by OliverJAsh** [comment]
In the example above, I would receive a type error at runtime. Is there any way to enforce this at compile time?

**Comment by RyanCavanaugh** [comment]
See https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-function-parameters-bivariant
