### ISSUE TITLE
[Errors] error recovery with errant / in generic function invocation

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#125]
```TypeScript
Foo<A,B,\ C>(4, 5, 6);
```

Expected: 

!!! Unexpected character "\".!!! Unexpected token; 'type' expected.!!! Cannot find name 'Foo'.

Actual: 

!!! Cannot find name 'Foo'.!!! Cannot find name 'A'.!!! Cannot find name 'B'.!!! Cannot find name 'C'.

**Comment by DickvdBrink** [comment]
Looks fixed to me.
Baseline can be found here: https://github.com/Microsoft/TypeScript/blob/master/tests/baselines/reference/parserX_TypeArgumentList1.errors.txt

**Comment by danquirk** [comment]
Thanks @DickvdBrink
