### ISSUE TITLE
Module resolution for HTML spec-compliant JavaScript modules

### ISSUE THREAD

**Issue by justinfagnani** [microsoft/TypeScript#12506]
**TypeScript Version:**  2.2.0-dev.20161124

**Code**

In a module in an npm package, I'm attempting to use HTML spec-compliant imports, which must have module specifiers that are paths, not names (see https://blog.whatwg.org/js-modules which announces module support in HTML but doesn't go into details, or the relevant spec language: https://html.spec.whatwg.org/multipage/webappapis.html#resolve-a-module-specifier )

This is the same requirement that we've had on HTML Imports for years, so it should be relatively easy to deal with: to import a module in another package, simply assume that all packages are siblings (say installed with `yarn install --flat`) and import a relative path that reaches out of the importing module's package.

With a package layout like this:

```
my-package/
  |- node_modules/
  |   |-  other-package/
  |     |- other-module.js
  |- my-module.ts
```

I should be able to do this:

my-package/my-module.ts:
```ts
import * as dep from '../other-package/other-module.js';
```

This means that when `my-package` is installed by a dependent, and is a sibling to `other-package`, it will `my-module` will correctly import `other-module`.

To facilitate this with HTML imports tooling maps paths so that the current package appears as a child of the packages folder. (You can either view this as mapping `../` to `node_modules`, or mapping `./` to `node_modules/my-package`).

I can _almost_ get this to work in TS 2.2 by using `rootDirs`:

```json
    "rootDirs": [
      "./",
      "./node_modules"
    ]
```

and by putting my source in a `src/` folder. This means that a `../other-package/...` relative import from within `src/` maps to the root, where `tsc` will then also look in `node_modules/` and find the right folder.

The problem is that `tsc` does not recognize this is an import from another package, and because the file is JavaScript and not TypeScript, `tsc` tries to process it, require `allowJs` and disallowing declarations.

**Expected behavior:**

`'../other-package/other-module.js'` resolves to `./node_modules/other-package/other-module.js`.

**Actual behavior:**

Without the extra `rootDirs` configuration, `'../other-package/other-module.js'` resolves to outside of my package. With the extra `rootDirs` configuration, the import is treated as being in the same package.

**Suggested Change**

Add a new module resolver (maybe `"moduleResolution": "html"`) that works well with HTML's JavaScript module specifiers. This would have two behaviors:

One, for reusable packages would map paths that reach one level out of the current package into a packages folders (usually `node_modules`, but in Bower projects it could be `bower_components`, or for jspm `jspm_packages`). 

The other, for applications would treat path imports into a packages folder as coming from an external package, so an application could have a script with `import * as otherModule from `./node_modules/other-package/other-module.js`, and not need `allowJs`.

**Comment by mhegazy** [comment]
The issue really is that the compiler can not find a declaration file for the `.js` file. assuming you have one, it should be possible to use `rootDirs` to get this working by adding the declaration files into the mix.

For instance, you can add `./node_modules/@types` to your `rootDirs` and that would make the compiler look there first.

``sh
c:\test\12506>tree /f
│   my-module.ts
│   package.json
│   tsconfig.json
│
└───node_modules
    ├───@types
    │   └───other-package
    │           other-module.d.ts
    │
    └───other-package
            other-module.js


c:\test\12506>type my-module.ts
import * as dep from "./other-package/other-module.js";

dep.a;

c:\test\12506>type tsconfig.json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "rootDirs": [
            "./",
            "./node_modules/@types",
            "./node_modules"
        ],
        "types": []
    }
}

c:\test\12506>tsc --listFiles
C:/Users/mhegazy/AppData/Roaming/npm/node_modules/typescript/lib/lib.d.ts
c:/test/12506/node_modules/@types/other-package/other-module.d.ts
c:/test/12506/my-module.ts
```

would this work for your scenario?

**Comment by justinfagnani** [comment]
I'll try in a bit, seems like it might work.

In general though, are there any plans to support HTML-compliant module resolution? Native implementations are landing basically as we speak, and there's a good polyfill too: https://github.com/matthewp/script-type-module

**Comment by mhegazy** [comment]
i am not sure i understand what "HTML-compliant module resolution" means. In the example above, i am amusing you have a post build script that will flatten all your modules into one folder on your webserver, so the browser does not do any resolution, it just uses the URI to locate the module. so the issue here is how to describe such post-build transformation to the compiler so that it knows where to find the declaration files at build time.

**Comment by justinfagnani** [comment]
Well, since HTML only allows importing by path, "HTML-compliant module resolution" mean only using paths. Node has its proprietary module resolution algorithm, but I'd like to just skip that for web projects and just author using paths directly. In practice, this means using `../other-package/foo.js` instead of `other-package/foo.js`.

Right now not only do I have to use `rootDirs` to do this, but I have to layout my filesystem so that `../` reaches into a root. This just seems like a lot of configuration to get a web project w/ modules properly set up. If we know that packages are siblings, which is how `bower install` and `yarn install --flat` work, then we can assume that `../` from a root reaches into the packages folder. This is what the web component tooling that we vend from Polymer does.

**Comment by RyanCavanaugh** [comment]
There doesn't seem to be any demand for this mode.
