### ISSUE TITLE
Spread operator broken (`let a = {...x};`, a is always an empty object)

### ISSUE THREAD

**Issue by hackhat** [Microsoft/TypeScript#12505]
**TypeScript Version:**  2.0.10 (last on npm https://www.npmjs.com/package/typescript )

**Code**

```ts
let a = {c:4,f:5};
let b = {
  ...a
}
```

**Expected behavior:**

variable `b` to be equal to `{c:4,f:5}`;

**Actual behavior:**

variable `b` to be equal to `{}`;

**Notes:**
Same code in babel es7 works as expected

**Comment by aluanhaddad** [comment]
It is not supported in 2.0.
It a feature of 2.1.

Try it out using `npm i -g typescript@next`

![image](https://cloud.githubusercontent.com/assets/5034656/20637002/f7acface-b346-11e6-8162-e9a43e55db0e.png)

**Comment by hackhat** [comment]
thanks @aluanhaddad !  I will close now. Anyway I think is better to disable the feature entirely rather than having a different behaviour.

Do you know where I can find a comparison of the features provided vs es7/babel...? Or at least which features it supports? async/await, spread...

**Comment by aluanhaddad** [comment]
Why would you disable the behavior? The code is a syntax error in older versions of typescript but it behaves the same way as you describe for Babel in 2.1. It simply wasn't previously supported

**Comment by hackhat** [comment]
@aluanhaddad I think is misleading, made me thought was all right, but got an error at runtime because the code didn't worked as expected. I think is more useful to throw an exception rather than let me continue. For example I was migrating some files and the compiler was ok with that, even if it didn't compiled to the right thing.

**Comment by aluanhaddad** [comment]
@hackhat when I compile
```ts
let a = {c:4,f:5};
let b = {
  ...a
}
console.log(a);
console.log(b);
```
with tsc I get
```js
var __assign = (this && this.__assign) || Object.assign || function(t) {
    for (var s, i = 1, n = arguments.length; i < n; i++) {
        s = arguments[i];
        for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p))
            t[p] = s[p];
    }
    return t;
};
var a = { c: 4, f: 5 };
var b = __assign({}, a);
```
if I run the output with node `node` I get 
```bash
{ c: 4, f: 5 }
{ c: 4, f: 5 }
```
Looks correct.

**Comment by hackhat** [comment]
@aluanhaddad this happens when I use typescript@next, not TypeScript Version: 2.0.10 and I also use on browser. I will try to publish the code that actually creates, but the result is definitively wrong, as you seem to agree when you answered https://github.com/Microsoft/TypeScript/issues/12505#issuecomment-263035719

**Comment by aluanhaddad** [comment]
Which specific version are you using?

**Comment by sandersn** [comment]
@hackhat It sounds like you want `--noEmit`. Typescript normally emits code even when it finds errors. If you are using 2.0 then you will get an error for your code. But it will still emit this:

```js
var a = { c: 4, f: 5 };
var b = {};
a;
```

**Comment by sandersn** [comment]
[Kangax is an independent feature comparison](http://kangax.github.io/compat-table/esnext/). But it's not to up-to-date for 2.1 yet, since 2.1 hasn't been released yet. For that you can see [What's New In TypeScript](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript).
