### ISSUE TITLE
no mapping for this

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#12507]
i want to extend the Object prototype by adding a method that returns a proxified version of any object
```typescript
Object.defineProperty(Object.prototype, 'proxify, {
   get: function(this: any) {
       // creating a proxy for the darn object
   }
});
const data = {
    name: 'hey',
    value: 123
};
const proxy = data.proxify();
declare global {
   interface Object {
     proxify(): {
        [P in keyof this]: Proxied<this [p]>; // expected to work, actual: A 'this' type is available only in a non-static member of a class or interface.
     }
   }
}

```

what am i doing wrong?

**Comment by aluanhaddad** [comment]
What are the definitions of `T` and `Proxified`?

The following works but may not be what you are trying to accomplish 
```ts
Object.defineProperty(Object.prototype, 'proxify', {
  get: function (this: any) {
      // creating a proxy for the darn object
  }
});
const data = {
    name: 'hey',
    value: 123
};
 const proxy = data.proxify();
declare global {

  interface Object {
    proxify(): {
      [P in keyof this]: Proxied<this[P]>;
    };
  }
}
export type Proxied<T> = {
  [P in keyof T]: Proxied<T[P]>;
};
```

**Comment by aluanhaddad** [comment]
For the sake of argument, isn't a proxy supposed to be transparent? 😛

**Comment by aleksey-bykov** [comment]
it doesnt really matter what `Proxified` is, because it breakes at `this` in `[P in keyof this]`

dont remember anythhing about them having to look *exactly* like the original objects (although it wont hurt if they do)

afaict, the only thing proxy should do to be standing between your object and you

**Comment by aleksey-bykov** [comment]
`T` should be read `this`, fixed

**Comment by aluanhaddad** [comment]
I was being somewhat facetious. Seriously though it does appear that mapping `this` works correctly.

**Comment by aleksey-bykov** [comment]
haven't you seen ` 'this' type is available only in a non-static member of a class or interface` anywhere?

**Comment by aluanhaddad** [comment]
I've seen it a number of times  but only in type aliases and other contexts where this would not be available. 

```ts
declare global {
  interface Object {
    proxify(): {
      [P in keyof this]: Proxied<this[P]>;
    };
  }
}
```
Doesn't give me that error.

**Comment by aleksey-bykov** [comment]
say `Proxified <T> = T` what can you see wgen you type `data.proxify ().`? (whar does autocomplete suggest?)

**Comment by aluanhaddad** [comment]
This is what I see
![image](https://cloud.githubusercontent.com/assets/5034656/20637441/607a24aa-b356-11e6-8c02-729f1b5a927b.png)
which is definitely not what we want here.

**Comment by HerringtonDarkholme** [comment]
This is probably the same problem of https://github.com/Microsoft/TypeScript/issues/12349
and is not supported for now because of performance(I guess), reference https://github.com/Microsoft/TypeScript/pull/11929#issuecomment-261744874

**Comment by aluanhaddad** [comment]
@HerringtonDarkholme Thanks for providing the clarifying context, it is very helpful. I had totally forgotten that you had already raised an issue requesting this behavior, and I didn't realize the implications, or consider this the same issue.
In #12349, you state the specific problem concisely in the first sentence
>it seems this type is resolved too eagerly in parent class.

I suggest we move any further discussion (back) into #12349.

**Comment by mhegazy** [comment]
This is not the same as #12349. these are two different issues. the thing is internally, all objects get the apparent members of `Object`, but it is not that they `extend` object. there is no distinction if there are no `this` types, but it breaks if `this` types are defined on Object since these signatures or properties will not be instantiated with the type of the object you are using. 
and yes, the concern is performance. since augmenting `Object` is not that common scenario.
