### ISSUE TITLE
imports: destructing import further

### ISSUE THREAD

**Issue by mbana** [Microsoft/TypeScript#12508]
hi, all,
would love some tips on getting around this.

## producer-module:
* umd module.
* es5.

### producer_b:
```javascript
export interface interface_a {}
export interface interface_b {}
...
export interface interface_z {}
```

### producer_a:
```javascript
import * as producer_b from './producer_b';
export { ... }
export { producer_b };
export { ... }
```

## consumer-module
* es6 module.
* common.

### consumer:

```javascript
import { producer_b } from './producer-module';
```

---

i'd like to do the first example below, failing that i think i need to resort to the second one?

### first opt

```javascript
import { producer_b } from './producer-module';
import { interface_a, interface_b } = producer_b;
```

### end opt

i guess i need to configure paths etc. in `tsconfig.json` to achieve something like above and then do something like below?

```javascript
import { interface_a, interface_b }  from './producer-module/producer_b';
```

**Comment by mhegazy** [comment]
I do not see the issue. can you share a self-contained repro with the expected behavior vs the actual behavior, and why you believe this is a compiler/language bug/missing feature.

**Comment by mbana** [comment]
https://github.com/mbana/typescript-module-imports. clone etc and build:

```sh
(cd /tmp && \
    git clone git@github.com:mbana/typescript-module-imports.git && \
    cd typescript-module-imports && \
    ./build.sh)
```

**Comment by mhegazy** [comment]
The module name is not correct. there is no module `'typescript-module-imports-producer/production'` it is `'typescript-module-imports-producer/lib/production'`. that is why you are getting this error.
