### ISSUE TITLE
Go To Definition for 'new someClass()'  goes to import not class definition

### ISSUE THREAD

**Issue by mooflu** [Microsoft/TypeScript#12504]
**TypeScript Version:**  2.0.3 (ts server via vscode 1.7.1)

```ts
import Menu = require('src/components/menu/Menu'); 
...
this.menu = new Menu() 
```

Originally logged here (item 2) many moons ago: https://typescript.codeplex.com/workitem/2120

**Expected behavior:**

go to definition takes you to the class definition or constructor.

**Actual behavior:**

go to definition takes you to the import statement.

**Comment by mhegazy** [comment]
`Menu` is rely a local import. if you rename it, you would rename the use site, and the import site and not the class declaration in `src/components/menu/Menu`.
hitting F12 on `Menu` in `import Menu = require('src/components/menu/Menu');` should get you to the file.

**Comment by mooflu** [comment]
I get why it's doing it, but it's an inconvenience to navigate three times: first to the import, then to the class, then scroll to the constructor.

If I hover over the "new Menu" it gives me info about the (alias) constructor not the local import. Ctrl-hover shows both the alias and the import. Maybe this is more of a vscode request, but at the moment it's neither convenient nor consistent :(

**Comment by RyanCavanaugh** [comment]
It used to go to the class itself and then people complained that they couldn't quickly go to the import for the sake of renaming it. :shrug emoji:

**Comment by mooflu** [comment]
I guess you can't satisfy everyone. I'd argue that there is an easy way to rename via F2/rename symbol without the need to go to the import. By going to the constructor wouldn't that satisfy both sides?
