### ISSUE TITLE
Cannot access protected members when specifying 'this' type

### ISSUE THREAD

**Issue by cmann1** [Microsoft/TypeScript#12510]
**TypeScript Version:**  2.1.1

**Code**

```ts
class TestClass{
    protected testField = 1;
}

function testFunc1(){
    this.testField = 2; // < No errors here
}

function testFunc2(this:TestClass){
    this.testField = 2; // < Error
}
```

**Expected behavior:**
You should be able to access private and protected members (such as `testField` in the example above) when using the 'this' keyword.

**Actual behavior:**
The compiler gives the following error:
`Error: TS2445: Property 'testField' is protected and only accessible within class 'TestClass' and its subclasses.`

**Comment by HerringtonDarkholme** [comment]
This is the correct behavior. The first function does not specify this, so the `this` is typed `any`. So you can access any property from it. There is nothing to do with private/protected members.

The second function does specify this to a class. You cannot access a protected/private property outside a class body.

**Comment by cmann1** [comment]
I see what you're saying, but doesn't 'this' indicate it's not 'outside' the class?
