### ISSUE TITLE
Incorrect unreachable code detecting with async functions

### ISSUE THREAD

**Issue by idy** [Microsoft/TypeScript#12518]
**TypeScript Version:**  2.2.0-dev.20161125

**Code**
```ts
function someFunction() {
  (async() => {
    while(true) {
      await sleep(1000);    
    }
  })();
  console.log('Hey, I\'m here');
}

async function sleep(time) {
  return new Promise(resolve => {
    setTimeout(resolve, time)
  })
}
```

**Expected behavior:**

no error in syntax

**Actual behavior:**

`[ts] Unreachable code detected.` on line: `console.log('Hey, I\'m here');`

**Comment by vladima** [comment]
cannot repro on the latest master
```
D:\Playground\TS\TypeScript>type ..\a.ts
function someFunction() {
  (async() => {
    while(true) {
      await sleep(1000);
    }
  })();
  console.log('Hey, I\'m here');
}

async function sleep(time) {
  return new Promise(resolve => {
    setTimeout(resolve, time)
  })
}
D:\Playground\TS\TypeScript>node built\local\tsc.js --version
Version 2.2.0
D:\Playground\TS\TypeScript>node built\local\tsc.js ..\a.ts -t es6
D:\Playground\TS\TypeScript>
```

Also format of the error looks odd, TypeScript compiler never generates anything with `[ts]` prefix. Can you verify that your toolchain uses the right version of the compiler?

**Comment by idy** [comment]
Thanks for your reply ;) I confirmed this issue only happened on version 2.0.6.

The error message is prompt from vscode, which I set the `typescript.sdk` in settings. Anyway, this setting is not take effect without resarting vscode. I restart the entire program (not reload window, or reload typescript project), it got fix.
