### ISSUE TITLE
"compileOnSave": true not respected in VS17RC

### ISSUE THREAD

**Issue by gregoryagu** [Microsoft/TypeScript#12521]
**TypeScript Version:**  2.1.2

After installing and migrating a project from aspnetcore 1.0 with VS15 to aspnetcore 1.1 with VS17, compile on save no longer works.

When I modify, then save a *.ts file, no generation occurs of the *.js file.

Oddly, I DO see "Output(s) generated successfully" in the status bar.

But the actual *.js file is unchanged.

If I rebuild the project, then it is properly generated.

**Comment by mhegazy** [comment]
Can you share a project we can look at?

**Comment by gregoryagu** [comment]
I created a fresh project, and it is working fine now.
