### ISSUE TITLE
[Bug] Re-exported binding doesn't track the original binding

### ISSUE THREAD

**Issue by yortus** [microsoft/TypeScript#12522]
**TypeScript Version:**  nightly (2.2.0-dev.20161127)

*EDIT: The issue described below is with `--module commonjs`, but as @aluanhaddad points out in a comment below, there are other behaviours with different module emits.*

I looked for an existing issue about this but didn't find one. Apologies if this is a duplicate.

I ran into a problem with TypeScript's emit for _re-exported_ bindings, in particular when the original exported value changes over time.

Importing a binding directly from a source module gets a 'live view' that changes when the export value changes, as it should. But **importing from a re-exported binding gets a snapshot that is no longer a live view of the original export**. This seems not to be spec compliant and leads to my code not working as intended.

## Code

```ts
// file: a.ts
export let liveView = 'foo';
export function changeTo(val: string) { liveView = val; }   // CHANGES THE EXPORT VALUE  



// file: b.ts
import {liveView, changeTo} from './a';     // <===== Import directly from A
console.log(liveView); // outputs 'foo'
changeTo('bar');
console.log(liveView); // outputs 'bar'        <===== GOOD: binding changed as it should

export {liveView, changeTo} from './a';     // <===== Re-export from A



// file: c.ts
import {liveView, changeTo} from './b';     // <===== Import via B's re-export
console.log(liveView); // outputs 'bar'
changeTo('baz');
console.log(liveView); // outputs 'bar'     // <===== BAD: binding is not live anymore
```

## Expected behavior
Emitted code should preserve the live binding to `liveView` when re-exporting from `b.ts`.

Last line of `c.ts` should output `'baz'`.

## Actual behavior
Emitted code exports a 'snapshot' of the `liveView` binding from `b.ts`, so that the import of `liveView` into `c.ts` is no longer a live binding.

Last line of `c.ts` incorrectly outputs `'bar'`.

## What should be the Correct Behaviour?
I found it hard to locate a clear description of correct ES6 behaviour for this situation, but from what I did find I think TypeScript's current emit is not compliant with ES6.

* E.g. from the [Exploring ES6](http://exploringjs.com/es6/index.html#toc_ch_modules) sections about [imports as views](http://exploringjs.com/es6/ch_modules.html#_imports-are-read-only-views-on-exports) and about [re-exports](http://exploringjs.com/es6/ch_modules.html#_re-exporting)

* Babel emits code that preserves the 'live-ness' of re-exports

So for `export { liveView } from 'some-module';` TypeScript emits something like:

```js
var some_module_1 = require("some-module");
exports.liveView = some_module_1.liveView;
```

Whereas babel emits something like:

```js
var _someModule = require('some-module');

Object.defineProperty(exports, 'liveView', {
  enumerable: true,
  get: function get() {
    return _someModule.liveView;
  }
});
```

**Comment by aluanhaddad** [comment]
This is really interesting. Note that is works differently in different module formats. Specifically if you compile into `system` modules, the output is actually
```ts
foo
bar
bar
baz
```
as you expect it to be because the vars are declared outside of the closure which sets up the module and are hoisted. Also, using any module format _except_ `system` results in output which imports `a` twice in `b`. Another curious aspect is how reordering the statements changes the behavior.
If we alter `b` by moving the re-export above the call to `changeTo`
and transpile to `commonjs`, the output changes to
```
foo
bar
foo
foo
```
the behavior under the `system` format does not change.

**Comment by yortus** [comment]
That is interesting. I should have mentioned in the OP that I was using `commonjs`. Added it now.

**Comment by yortus** [comment]
This seems to have slipped through the cracks. @mhegazy would you mind triaging this issue?

**Comment by aluanhaddad** [comment]
The current state of the [node-eps for es modules](https://github.com/nodejs/node-eps/blob/master/002-es6-modules.md) makes this very pertinent. It definitely needs to be revisited.

**Comment by squidfunk** [comment]
Any update on this? Still happening and wildly indeterministic. Also, when I add a simple `console.log` statement or even an empty to the file that re-exports everything inside that folder, it magically works:

Doesn't work (`foo` is not re-exported):

``` ts
export * from "./foo"
export * from "./bar"
```

Works:

``` ts
//
export * from "./foo"
export * from "./bar"
```

Also works:

``` ts
console.log("")
export * from "./foo"
export * from "./bar"
```

I'm also using `commonjs`.

**Comment by trustgit** [comment]
Is this issue still being worked on? This can be a serious problem in some cases (such as [this](https://github.com/ionjs-dev/ionjs/pull/18/commits/692245d8639a63b664a1c3361a1bad24376aa7f0)), and is definitely out of the ESM spec.

Also, the tricks mentioned by @squidfunk are invalid currently.

**Comment by squidfunk** [comment]
@trustgit - removing `strict: true` still works for me with TypeScript (3.3.3333)

**Comment by squidfunk** [comment]
Unfortunately @t532 is right - I've just encountered a case where setting `strict: true` doesn't work. Needs investigation.

**Comment by squidfunk** [comment]
What's the state of this issue? Is it considered being investigated?

The issue was triaged as "needs investigation" by @RyanCavanaugh nearly two years ago, and shortly after that labeled as a "bug", but a year ago it was not considered being a bug anymore? Its effects are wildly indeterministic and thus really annoying. We're in need of deterministic builds and re-exports are a very common thing. This problem may live in a lot of codebases.

I'm currently working around it by adding an empty comment after the `export` statement of the dependency that is not correctly being re-exported, but that's far from a solution.

**Comment by t532** [comment]
@squidfunk Well I don't think this is being actually investigated anymore - the solution is clear: make the imported values getters, just as what Babel and Rollup did; but for some reason they are not getting this done.
> *A little complaint:* I filed [the same issue](https://github.com/rollup/rollup/issues/2754) in Rollup and it got solved in 2 weeks. However this issue is still open after *2 years* of "investigation".

**Comment by squidfunk** [comment]
I started a PR in #31715 using the technique described in https://github.com/microsoft/TypeScript/issues/13245#issuecomment-271289469. Heavily WIP. Happy to collaborate!
