### ISSUE TITLE
ElementTraversal: missing some nulls

### ISSUE THREAD

**Issue by tkrotoff** [Microsoft/TypeScript#12526]
Inside [dom.generated.d.ts](https://github.com/Microsoft/TypeScript/blob/v2.1.2/src/lib/dom.generated.d.ts):

```TypeScript
interface ElementTraversal {
    readonly childElementCount: number;
    readonly firstElementChild: Element;
    readonly lastElementChild: Element;
    readonly nextElementSibling: Element;
    readonly previousElementSibling: Element;
}
```

should be:

```TypeScript
interface ElementTraversal {
    readonly childElementCount: number;
    readonly firstElementChild: Element | null;
    readonly lastElementChild: Element | null;
    readonly nextElementSibling: Element | null;
    readonly previousElementSibling: Element | null;
}
```

Example: https://jsfiddle.net/tkrotoff/khzbrkpg/

(tested with typescript@2.2.0-dev.20161125 lib.dom.d.ts)

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by perryjiang** [comment]
Hi, I'm new to OSS. If I understand the issue right, this looks like a relatively simple problem? If so, I'd be glad to tackle it.

**Comment by mhegazy** [comment]
This should be a simple one to change. the change should be done in https://github.com/Microsoft/TSJS-lib-generator, you will need to edit https://github.com/Microsoft/TSJS-lib-generator/blob/master/inputfiles/overridingTypes.json to include the `| null`.

**Comment by perryjiang** [comment]
Thanks! PR submitted.

**Comment by tkrotoff** [comment]
This can be closed now
Thx @perryjiang

**Comment by mhegazy** [comment]
This still needs to be merged into master from https://github.com/Microsoft/TSJS-lib-generator. Keeping it open until then.
