### ISSUE TITLE
Microsoft.TypeScript.MSBuild throwing error on VSTS Build

### ISSUE THREAD

**Issue by robertmclaws** [Microsoft/TypeScript#12527]
**TypeScript Version:**  2.1.1-rc

When attempting to use the 2.1.1 RC in VSTS Build, I'm getting the same error as in [this issue](https://developercommunity.visualstudio.com/content/problem/311/msb4064-the-outputlogfile-parameter-is-not-support.html).

```
2016-11-27T17:03:24.2870039Z          C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.8\tsc.exe --project "C:\a\1\s\Branches\Development\src\AdvancedREI.Cdn\tsconfig.json"
2016-11-27T17:03:24.2880037Z ##[error]Branches\Development\src\packages\Microsoft.TypeScript.MSBuild.2.1.1-rc\tools\microsoft.TypeScript.targets(231,7): Error MSB4064: The "OutputLogFile" parameter is not supported by the "VsTsc" task. Verify the parameter exists on the task, and it is a settable public instance property.
2016-11-27T17:03:24.2880037Z     27>C:\a\1\s\Branches\Development\src\packages\Microsoft.TypeScript.MSBuild.2.1.1-rc\tools\microsoft.TypeScript.targets(231,7): error MSB4064: The "OutputLogFile" parameter is not supported by the "VsTsc" task. Verify the parameter exists on the task, and it is a settable public instance property. [C:\a\1\s\Branches\Development\src\AdvancedREI.Cdn\AdvancedREI.Cdn.csproj]
2016-11-27T17:03:24.2880037Z ##[error]Branches\Development\src\packages\Microsoft.TypeScript.MSBuild.2.1.1-rc\tools\microsoft.TypeScript.targets(222,5): Error MSB4063: The "VsTsc" task could not be initialized with its input parameters. 
2016-11-27T17:03:24.2880037Z     27>C:\a\1\s\Branches\Development\src\packages\Microsoft.TypeScript.MSBuild.2.1.1-rc\tools\microsoft.TypeScript.targets(222,5): error MSB4063: The "VsTsc" task could not be initialized with its input parameters.  [C:\a\1\s\Branches\Development\src\AdvancedREI.Cdn\AdvancedREI.Cdn.csproj]
```
The build process SHOULD be using the version in "Branches\Development\src\packages\Microsoft.TypeScript.MSBuild.2.1.1-rc\tools\tsc\" but it is using the version installed in Program Files instead. I think the package needs to be updated to reference the specific version over the installed version. Probably by calling `\tsc\tsc.exe` instead of relying on the OS to resolve the executable.

**Comment by mhegazy** [comment]
can you share your project file?

**Comment by tlmii** [comment]
I had this same problem with 2.1.4. I expected it to use what was in the nuget package (2.1.4), but instead it used what was installed on the machine on VSTS (1.8). Actually it used an older version, since the VSTS machines have 2.0.6 on them per https://www.visualstudio.com/en-us/docs/build/admin/agents/hosted-pool#software-on-the-hosted-build-server. It could be that I'm doing something wrong, but I'm not sure where to start.

**Comment by mhegazy** [comment]
From the project file, it seems that you are including both targets (ones installed on the machine, and ones in the nuget package). is this intentional?

Here is what i mean:

```XML
<!-- Coming from the Nuget package -->
<Import Project="..\packages\Microsoft.TypeScript.MSBuild.2.1.4\build\Microsoft.TypeScript.MSBuild.props" Condition="Exists('..\packages\Microsoft.TypeScript.MSBuild.2.1.4\build\Microsoft.TypeScript.MSBuild.props')" />
 
<!-- Coming from the what is installed on the machine, if they exist --> 
<Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.Default.props" Condition="Exists('$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.Default.props')" />
 
```


```XML
<!-- Coming from the what is installed on the machine, if they exist --> 
<Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.targets" Condition="Exists('$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.targets')" />


<!-- Coming from the Nuget package -->
<Import Project="..\packages\Microsoft.TypeScript.MSBuild.2.1.4\build\Microsoft.TypeScript.MSBuild.targets" Condition="Exists('..\packages\Microsoft.TypeScript.MSBuild.2.1.4\build\Microsoft.TypeScript.MSBuild.targets')" />
 
```

**Comment by nickmkk** [comment]
I'm having this same problem with 2.1.4 as well.  Like the others it works locally but fails in VSTS, i'm also assuming it must be using the typescript version that's installed on the VSTS machine.  My csproj file also has both targets but even when commenting out the machine targets I still get the error.

Here's the error on my end:

```
  C:\a\1\s\packages\Microsoft.TypeScript.MSBuild.2.1.4\tools\microsoft.TypeScript.targets(265,7): error MSB4064: The "OutputLogFile" parameter is not supported by the "VsTsc" task. Verify the parameter exists on the task, and it is a settable public instance property. [C:\a\1\s\Smokey.Web\Smokey.Web.csproj]
  C:\a\1\s\packages\Microsoft.TypeScript.MSBuild.2.1.4\tools\microsoft.TypeScript.targets(251,5): error MSB4063: The "VsTsc" task could not be initialized with its input parameters.  [C:\a\1\s\Smokey.Web\Smokey.Web.csproj]
```

And the relevant portions of my .csproj file.

``` xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="12.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="..\packages\Microsoft.TypeScript.MSBuild.2.1.4\build\Microsoft.TypeScript.MSBuild.props" Condition="Exists('..\packages\Microsoft.TypeScript.MSBuild.2.1.4\build\Microsoft.TypeScript.MSBuild.props')" />
  <!-- <Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.Default.props" Condition="Exists('$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.Default.props')" />
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" /> -->
  ...
  <PropertyGroup>
    ...
    <TypeScriptToolsVersion>2.1</TypeScriptToolsVersion>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">    
	...
    <TypeScriptTarget>ES5</TypeScriptTarget>
    <TypeScriptJSXEmit>None</TypeScriptJSXEmit>
    <TypeScriptCompileOnSaveEnabled>True</TypeScriptCompileOnSaveEnabled>
    <TypeScriptNoImplicitAny>True</TypeScriptNoImplicitAny>
    <TypeScriptModuleKind>CommonJS</TypeScriptModuleKind>
    <TypeScriptRemoveComments>True</TypeScriptRemoveComments>
    <TypeScriptOutFile />
    <TypeScriptOutDir />
    <TypeScriptGeneratesDeclarations>False</TypeScriptGeneratesDeclarations>
    <TypeScriptNoEmitOnError>True</TypeScriptNoEmitOnError>
    <TypeScriptSourceMap>True</TypeScriptSourceMap>
    <TypeScriptMapRoot />
    <TypeScriptSourceRoot />
    <TypeScriptStrictNullChecks>True</TypeScriptStrictNullChecks>
  </PropertyGroup>
  ...
  <!-- <Import Project="$(VSToolsPath)\TypeScript\Microsoft.TypeScript.targets" Condition="Exists('$(VSToolsPath)\TypeScript\Microsoft.TypeScript.targets')" /> -->
  ...
  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
	<PropertyGroup>
      <ErrorText>This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
    </PropertyGroup>
    ...    
    <Error Condition="!Exists('..\packages\Microsoft.TypeScript.MSBuild.2.1.4\build\Microsoft.TypeScript.MSBuild.props')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\Microsoft.TypeScript.MSBuild.2.1.4\build\Microsoft.TypeScript.MSBuild.props'))" />
    <Error Condition="!Exists('..\packages\Microsoft.TypeScript.MSBuild.2.1.4\build\Microsoft.TypeScript.MSBuild.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\Microsoft.TypeScript.MSBuild.2.1.4\build\Microsoft.TypeScript.MSBuild.targets'))" />
  </Target>
  ...
  <Import Project="..\packages\Microsoft.TypeScript.MSBuild.2.1.4\build\Microsoft.TypeScript.MSBuild.targets" Condition="Exists('..\packages\Microsoft.TypeScript.MSBuild.2.1.4\build\Microsoft.TypeScript.MSBuild.targets')" />  
</Project>
```

**Comment by tlmii** [comment]
@mhegazy - That was definitely not intentional. I'm guessing the tools and/or nuget added those at some point. And, somewhere along the line of me upgrading/downgrading both in the last day or so that went away. So now the build process is correctly using the tools that come with the nuget package, so I'm able to build with 2.1.4 on VSTS without any issue now. Thanks!

**Comment by nickmkk** [comment]
@tlmii did your csproj file change at all from your comment above?  Also, did you make any changes in VSTS?

**Comment by mhegazy** [comment]
@nickmkk can u share the build log from your server?

**Comment by nickmkk** [comment]
I just updated my comment above, the problem was caused by the original targets like @mhegazy suspected.  This didn't work for me initially because I accidentally commented out the wrong <Import> tag.  oops =P

**Comment by mhegazy** [comment]
@robertmclaws is this the same issue you were running into?

**Comment by robertmclaws** [comment]
Yes, finding the .props and the .targets references in the offending files solved the problem with VSTS build.

If you guys could figure out how to have the NuGet package update the Project files to remove those targets for us, so that other people don't run into this issue, that would be wicked awesome. Thanks!

**Comment by mhegazy** [comment]
the nuget package install script tries to remove the imports. but it is a regexp. some imports will be missed and will not be removed.

**Comment by robertmclaws** [comment]
It seems like the regex is broken and needs to be expanded or adjusted.

**Comment by tlmii** [comment]
Interestingly it was the scripts that ultimately removed it for me. Not on initial install, but somewhere in upgrading and downgrading the nuget packages it ended up doing it. I'll look back through my version history and see if I can tell which attempt(s) failed at removing and which attempt succeeded.

**Comment by mhegazy** [comment]
In Nuget v2 we used to have support for `install.ps1` scripts that removes the machine-wide target/prop imports when the package is installed, but that has been deprecated in [Nuget v3](https://docs.microsoft.com/en-us/nuget/release-notes/nuget-3.1#deprecated) (see more at https://github.com/NuGet/Home/issues/1020). 

So under Nuget v3, When adding a nuget package to your project,  you need to **manually** remove the imports to the machine-wide targets and props. having both leads to unknown load order or targets/tasks, which would manifest in such errors.
