### ISSUE TITLE
New Website Logo: Váli B.V.

### ISSUE THREAD

**Issue by csrakowski** [Microsoft/TypeScript#12523]
Please fill the following out:

- Name: Váli B.V.
- Homepage url: http://www.valisystems.com
- Brand Guidelines/Licensing: N/A.
- Logo: https://1drv.ms/i/s!AgcdlgxheSW6ppMWBBQJArr1ZYBceQ

**Comment by DanielRosenwasser** [comment]
You should see the changes get applied next time we publish the site.

**Comment by DanielRosenwasser** [comment]
Should be up!
