### ISSUE TITLE
TypeScript project template is missing in Visual Studio 2017 RC

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/TypeScript#12531]
**TypeScript Version:**  2.1 RC

**Visual Studio Version:**  2017 Commnunity

The TypeScript project template is missing:

![image](https://cloud.githubusercontent.com/assets/1106823/20667980/315570c0-b564-11e6-9307-bddf5d711714.png)

The ones listed there are from NTVS.

**Comment by billti** [comment]
We removed it, as it was really just a Web Application with a TypeScript file added. You should be able to create any of several project types (Web Application, Web Site, UWP, Node, etc..) and just add a TypeScript file to it.

**Comment by NoelAbrahams** [comment]
Okay, that's not a bad thing. On another note, any idea how I get rid of the 'Service Capabilities' annoyance?

![image](https://cloud.githubusercontent.com/assets/1106823/20680573/834e498c-b597-11e6-8033-bc14a976bf33.png)


This feature has infected every single of our 30+ TypeScript projects and offers such brilliantly vague suggestions as the following:

![image](https://cloud.githubusercontent.com/assets/1106823/20680675/ed232652-b597-11e6-9c93-28d912fb1f53.png)

**Comment by billti** [comment]
I have no idea about that one, it's nothing to do with TypeScript. I'd use the feedback link in VS to raise the issue, and it'll get routed to the right team.
