### ISSUE TITLE
string literal completion for `<K extends keyof Foo>` does not work

### ISSUE THREAD

**Issue by wonderful-panda** [Microsoft/TypeScript#12536]
**TypeScript Version:**  nightly (2.2.0-dev.20161128)

**Code**

```ts
interface Foo { foo: string; }
function ok(a: keyof Foo) {};
function ng<K extends keyof Foo>(a: K) {};

ok("/*position 1*/");
ng("/*position 2*/");
```

**Expected behavior:**
tsserver returns `foo` as completion candidate for both positions.

**Actual behavior:**
tsserver returns no candidate for position 2.

**Comment by mhegazy** [comment]
PRs welcomed.
