### ISSUE TITLE
Spread of type that is union of object types rejected by type checker 

### ISSUE THREAD

**Issue by Kovensky** [Microsoft/TypeScript#12534]
**TypeScript Version:** 2.2.0-dev.20161127

**Code**

```ts
interface X {}
const x: {} | X = {}
const y = { ...x }
```

**Actual behavior:**

Error with "Spread types may only be created from object types".

Probably related to #12520.

**Comment by mhegazy** [comment]
this is another variation of https://github.com/Microsoft/TypeScript/issues/12520. both union and intersection should be allowed as targets of spread.
