### ISSUE TITLE
Compiler hangs on union of enums with a large number of elements

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/TypeScript#12535]
**TypeScript Version:**  2.1 RC / (Version installed with VS 2017)

**Code**

```ts
namespace enums {

    export const enum A {
        a1,
        a2,
        a3,
       // ... elements omitted for the sake of clarity
        a75,
        a76,
        a77,
    }

    export const enum B {
        b1,
        b2,
       // ... elements omitted for the sake of clarity
        b86,
        b87,
    }

    export const enum C {
        c1,
        c2,
       // ... elements omitted for the sake of clarity
        c210,
        c211,
    }

    export type Genre = A | B | C;
}

type Foo = {
    genreId: enums.Genre;
};

type Bar = {

    genreId: enums.Genre;
};

type FooBar = Foo & Bar;

function foo(so: any) {

    const val = so as FooBar;

    const isGenre = val.genreId;

    return isGenre;
}


```

**Expected behavior:**

Compilation in a few hundred milliseconds

**Actual behavior:**

Compilation took 1 minute 5 seconds for the code sample above (i.e. where the omitted enum elements are filled out exactly.) In the actual code, the build hangs indefinitely.

This bit of code was working fine with TS 2.0.

**Comment by ahejlsberg** [comment]
This is an issue caused by #11717. We need to deduplicate intersections before we distribute them over union types. Looks like an easy fix.

**Comment by NoelAbrahams** [comment]
@ahejlsberg, not sure if it has any bearing but in the actual problem code every enum value is unique (i.e. the elements of A, B and C do not share any values). I hope that's still okay.
