### ISSUE TITLE
Remove undefined return type in loops which check for array values

### ISSUE THREAD

**Issue by trshafer** [Microsoft/TypeScript#12541]
It's very possible this scenario is out of scope for the compiler, but I haven't seen it logged here so I thought I would suggest it. Thanks for taking a look.

**TypeScript Version:**  2.0.10

**Code:**

```ts
// index.ts
const ary: string[] = ["a", "b", "c"];

while(ary.length) {
  const val: string = ary.pop();
}

```
**Compilation steps:**
```shell
./node_modules/.bin/tsc --strictNullChecks index.ts
```

**Expected behavior:**
Successfully compiles. It is impossible in this scenario for Array.prototype.pop() to return undefined.

**Actual behavior:**
```
index.ts(5,9): error TS2322: Type 'string | undefined' is not assignable to type 'string'.
  Type 'undefined' is not assignable to type 'string'.
```

**Comment by RyanCavanaugh** [comment]
I don't see how we'd do this in a reasonable way. It'd have to be some special logic that only works for the *first* invocation of `pop`
```ts
while(ary.length) {
  const val1: string = ary.pop();
  const val2: string = ary.pop();
}
```
It'd also have to know that `shift` also shortens the array:
```ts
while(ary.length) {
  const val1: string = ary.shift();
  const val2: string = ary.pop();
}
```
Not to mention side effects that might affect the array if it's passed into another function.

This code should be more recognizable to the compiler (I think we have a bug on this already):
```ts
// index.ts
const ary: string[] = ["a", "b", "c"];

let value: string;
while(value = ary.pop()) {
}
```
