### ISSUE TITLE
The 'thisArg' parameter should be used to type 'this' in callbacks to map, filter, etc.

### ISSUE THREAD

**Issue by e-cloud** [Microsoft/TypeScript#12548]
**TypeScript Version:**  (2.2.0-dev.20161128)

**Code**

`tets.ts`
```ts
class A {
    options: any[]
    addOptions(options: any[]) {
        if (!this.options) {
            this.options = [];
        }
        options.forEach(function (item) {
            this.options.push(item);
        }, this);
        return this;
    }
}
```

```sh
tsc --module commonjs --noImplicitThis --noEmit test.ts
```

**Expected behavior:**
compile with no error output

**Actual behavior:**
`test.ts(8,13): error TS2683: 'this' implicitly has type 'any' because it does not have a type annotation.`

As some built-in method of array can assign this, could it be inferred through the scopes?

**Comment by DanielRosenwasser** [comment]
`forEach` should actually contextually type `this` based on the `thisArg`.

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by e-cloud** [comment]
@mhegazy I've fixed the source. But where should i write the tests?

**Comment by e-cloud** [comment]
@mhegazy I've fixed the source. But how can i write the tests for changes? The test suite is so huge, it could take time to figure out. So ask you for how is more direct.

**Comment by jcalz** [comment]
Should this be reopened in light of #16223?

**Comment by JakeTunaley** [comment]
Aren't some of these inaccurate?

In definitions like the following:
```TypeScript
forEach(callbackfn: (this: undefined, value: T, index: number, array: ReadonlyArray<T>) => void): void;
forEach(callbackfn: (this: undefined, value: T, index: number, array: ReadonlyArray<T>) => void, thisArg: undefined): void;
forEach<Z>(callbackfn: (this: Z, value: T, index: number, array: ReadonlyArray<T>) => void, thisArg: Z): void;
```
```this: undefined``` ignores the fact that the this value is actually set, although what it gets set to depends on the execution environment (e.g. ```window``` in a browser). Also, this doesn't account for when ```thisArg``` is ```null```, which has the same behaviour as when it's ```undefined```.

Demo code:
```JavaScript
var array = [0];

// [object Window] in a browser, [object global] in Node
array.forEach(function () {
	console.log(this.toString());
});
array.forEach(function () {
	console.log(this.toString());
}, undefined);
array.forEach(function () {
	console.log(this.toString());
}, null);

// 7 in both
array.forEach(function () {
	console.log(this.toString());
}, 7);
```
Considering this, shouldn't the definitions look more like the following?
```TypeScript
forEach(callbackfn: (this: object, value: T, index: number, array: ReadonlyArray<T>) => void, thisArg?: null): void;
forEach<Z>(callbackfn: (this: Z, value: T, index: number, array: ReadonlyArray<T>) => void, thisArg: Z): void;
```
