### ISSUE TITLE
bug: type predicates (`V is T`) fails on expressions (`V[K] is T`)

### ISSUE THREAD

**Issue by tycho01** [Microsoft/TypeScript#12549]
**TypeScript Version:** nightly (2.2.0-dev.20161128)

**Code**

```ts
propIs<T, V, K extends keyof V>(type: T, name: K, obj: V): V[K] is T;
```

**Expected behavior:**
TS being totally cool with `V[K] is T`.

**Actual behavior:**
Nope, many syntax errors.

**Comment by DanielRosenwasser** [comment]
The type predicate syntax has always taken a parameter name on the left side of the `is` keyword. So it sounds like what you want is better parser recovery here.

**Comment by tycho01** [comment]
Oh, yeah, `V is T` itself works fine, this seems to be specifically about adding the `[K]` there. It does seem like storing (`extends`) `V[K]` in a new generic may form a solution here...
But apparently `propIs<T, V, K extends keyof V, R extends V[K]>(type: T, name: K, obj: V): R is T;` yields `Cannot find parameter 'R'`. I must be doing something wrong...

**Comment by DanielRosenwasser** [comment]
Well it's only the *parameter* that a type predicate can operate on - in other words, you write

```ts
function foo(x: any): x is string {
    // ....
}
```

As opposed to the following:

```ts
function foo(x: any): any is string {
    // ....
}
```

**Comment by tycho01** [comment]
I'm sorry, that would be my misinterpretation then.
In that event I would be inclined to try the following for this specific case:
```ts
propIs<T, V, K extends keyof V, R extends V[K]>(type: T, name: K, obj: V): obj[name] is T;
```
Still not okay though. I suppose it'd help if I had the ability to save this result to a new variable first, but I'm not confident I can do this in the type language...

**Comment by DanielRosenwasser** [comment]
You could do something like this:

```ts
propIs<T, V, K extends keyof V, R extends V[K]>(type: T, name: K, obj: V): obj is (V & Record<K, T>)
```

**Comment by tycho01** [comment]
Whoa, some out of the box thinking there, wouldn't have come up with that myself. Thanks for thinking along. :)
