### ISSUE TITLE
[TS Server] Add Automatic Typings Acquisition Begin and End Notifications

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#12540]
For https://github.com/Microsoft/vscode/issues/15209

**Request**
Have the TS server send notifications when automatic typings acquisition begins and when this acquisition completes (either in success of failure).

On the vscode side, we need to be able to track that ATA is running for a given project and these two notifications would let us do that. We would also need a unique id or other mechanism to correlate these begin and end events.

**Comment by vladima** [comment]
the fix is checked-in in master and should be ported into release-2.1 somewhere today
