### ISSUE TITLE
Include *.d.ts files with ambient definitions from a subfolder

### ISSUE THREAD

**Issue by philipstanislaus** [Microsoft/TypeScript#12553]
Hello, 

after reading the documentation for hours, I could not find a possibility to include *.d.ts files from a subfolder. I am not sure whether it is a bug or I have a misunderstanding of the declaration system.

How is that currently possible?

**TypeScript Version:**  2.1.1

**What works**
`app/store.d.ts`
```ts
declare module 'store' {
  export function set(key: string, value: any): any
  export function get(key: string, defaultVal?: any): any
  export function has(key: string): boolean
  export function remove(key: string): void
  export function clear(): void
  export var enabled: boolean
}
```

`app/some/path.ts`
```ts
import * as store from 'store'
```

**What I want to achieve and does not currently work**
`app/types/store.d.ts`
```ts
declare module 'store' {
  export function set(key: string, value: any): any
  export function get(key: string, defaultVal?: any): any
  export function has(key: string): boolean
  export function remove(key: string): void
  export function clear(): void
  export var enabled: boolean
}
```

`app/some/path.ts`
```ts
import * as store from 'store'
```

Error: `app/some.path.ts(1,25): error TS2307: Cannot find module 'store'.`

Thanks for your help!

**Comment by aluanhaddad** [comment]
what is `reactstrap`?

**Comment by philipstanislaus** [comment]
@aluanhaddad sorry, that was a typo, should have been 'store'. I just updated the example above.

**Comment by aluanhaddad** [comment]
It works if you add a tsconfig file, even an empty one. I don't know why exactly.

**Comment by philipstanislaus** [comment]
Unfortunately it doesn't for me. I tried the following `tsconfig.json`: 

```
{
  "compilerOptions": {
    "module": "commonjs",
    "moduleResolution": "node",
    "target": "es5",
    "baseUrl": ".",
    "paths": {
      "*": [
        "app/*"
      ]
    }
  },
  "exclude": [
    "node_modules"
  ],
  "include": [
    "app/**/*"
  ]
}
```

**Comment by mhegazy** [comment]
this seems to work for me. is this still an issue?

**Comment by philipstanislaus** [comment]
@mhegazy yes, just tried it again. How do you tell typescript it should look into `app/types/` to resolve the store declaration?

**Comment by mhegazy** [comment]
set "paths" to `"app/types/*"` instead of `"app/*"` ?

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
