### ISSUE TITLE
querySelector and querySelectorAll should support generics for "string" selectors

### ISSUE THREAD

**Issue by tomwanzek** [Microsoft/TypeScript#12568]
**TypeScript Version:**  2.2.0-dev.20161129

**Code**

As of the TS version stated above the `NodeSelector` in _lib.es6.d.ts_ interface is defined as:

```ts
interface NodeSelector {
    querySelector<K extends keyof ElementTagNameMap>(selectors: K): ElementTagNameMap[K] | null;
    querySelector(selectors: string): Element | null;
    querySelectorAll<K extends keyof ElementListTagNameMap>(selectors: K): ElementListTagNameMap[K];
    querySelectorAll(selectors: string): NodeListOf<Element>;
}

```

**Expected behavior:**

It should be possible to use a generic to control the return type of the general string-based selection methods, rather than being returned a fixed return type of `Element`. I.e. assume one uses a class `my-svg-shape` which one exclusively applies to either an SVG `rect` or `circle`.

There should be method signatures to control the return type at the developer's discretion, i.e.

```ts
querySelector<E extends Element>(selectors: string): E | null;
querySelectorAll<E extends Element>(selectors: string): NodeListOf<E>;
```
These would obviously fall back to the current behavior, if used without specifying a type, but could be used as, e.g.

```ts
let x = document.querySelectorAll<SVGRectElement | SVGCircleElement>('.my-svg-shape');
```

**Actual behavior:**

Return type is fixed to `Element`

EDIT: Fixed copy-paste typo in application example. Inserted `.my-svg-shape` as selector string.

**Comment by aluanhaddad** [comment]
Actually I think this is supposed to work. The purpose of the interface is to enable it to return the correct types as mapped. The problem is that key is not being inferred as a literal. 

If you use this definition it works
```ts
interface NodeSelector {
    querySelector<K extends string & keyof ElementTagNameMap>(selectors: K): ElementTagNameMap[K] | null;
    querySelector(selectors: string): Element | null;
    querySelectorAll<K extends string & keyof ElementListTagNameMap>(selectors: K): ElementListTagNameMap[K];
    querySelectorAll(selectors: string): NodeListOf<Element>;
}
```

**Comment by tomwanzek** [comment]
@aluanhaddad the use case I described, i.e. union types for (possibly) mixed type selection,  is not covered by the latest `lib.es6.d.ts` definitions as far  as I see. That's what this issue is aiming to get addressed.

**Comment by aluanhaddad** [comment]
Sorry I miss read the original comment

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by tomwanzek** [comment]
@YuichiNukiyama thanks for tackling this so quickly!

@mhegazy thanks for the link, seems I am too late this time around...

**Comment by FranklinWhale** [comment]
What is the difference between using generic and type assertion?

`let x = document.querySelectorAll('.my-svg-shape') as NodeListOf<SVGRectElement | SVGCircleElement>;` seems fine.

**Comment by tomwanzek** [comment]
@FranklinWhale IMHO `as` is a last resort when a more targeted approach is not available. It feels a lot more  natural to use the generic with `extends Element` as the base line,  the interface already uses generics, so it also seems idiomatically preferable.

**Comment by tomwanzek** [comment]
Is there any update on whether the PR will be accepted?
