### ISSUE TITLE
Intersection types

### ISSUE THREAD

**Issue by fdecampredon** [Microsoft/TypeScript#1256]
Support intersection types ala [flowtype](http://flowtype.org/docs/union-intersection-types.html#intersection-example)

**Comment by danielearwicker** [comment]
It's notable that `Object.assign', `$.extend` etc. cannot be usefully described by TS's type system and yet such functions are extremely widely used in real JS code.

TS gives great support to classes. But using classes means following a particular pattern where I have to use `this`, which can mean a lot of quite radical surgery on thousands of lines of existing JS code. I tried converting a few large modules that way, class-izing them, but it was damn hard work. To avoid that pain as I've adopted TS, I've used `$.extend` and extra interfaces and casting-I-mean-type-asserting.

    interface ICar {
        void accellerate(deltaV: number);
    }

    interface ISteerable {
        steer(direction: number): void;
    }

    // Pure intersection of two types! PLEASE DO NOT MODIFY!!
    interface ISteerableCar extends ICar, ISteerable { }

So:

    var car = carFactory.makeCar();

    var s: ISteerable = {
        steer(direction) { ... }
    };

    var steerableCar = <ISteerableCar>$.extend(car, s);

This pattern is type-safe against changes to both the `ICar` and `ISteerable` interfaces: the `s` object literal will fail to compile if I don't keep it up-to-date with changes to `ISteerable`.

But it is not safe against independent changes to `ISteerableCar`. The type assertion in front of `$.extend` is based purely on trust that future maintainers will read the comment on `ISteerableCar` and not add methods or further base interfaces.

Classes don't have this problem:

    class Car {
        accellerate(deltaV: number) { ... }
    }

    class SteerableCar extends Car {
        steer(direction: number) { ... }
    }

In JS classes are just syntactic sugar: they don't do anything you couldn't do another way. But in TS classes are magic. They conceal a call to an `extend` helper that is strongly typed, which we cannot do ourselves in TS.

With intersection types I wouldn't need `ISteerableCar` with a scare-comment. I'd just say `ISteerable&ICar`. And with a properly typed `Object.assign`:

    var sc: ISteerable&ICar = Object.assign(carFactory.makeCar(), {
        steer(direction: number) { ... }
    });

The great thing about JS is that by providing the tools needed to build objects dynamically, it allows library authors to come up with their own solutions to mixins, multiple-inheritance, aspect-oriented cross-cutting concerns and so on. So I'd love to see TS striving to be the compile-time equivalent of that.

This means that the logical building blocks of type relationships (such as intersection) should be regarded as important in-and-of themselves. They allow the type system to express things that can be done at runtime, and so they support library authors who experiment with ways of building objects.

Yes, classes are the ready-to-wear approach. But give library authors the building blocks so they can try other approaches. This is JS's strength - it's not frozen into one classical OO-style. But at the moment TS is rather class-biased. And lots of JS experts love to hate classes...

**Comment by NoelAbrahams** [comment]
> And lots of JS experts love to hate classes..

Where's the evidence for that? Perhaps fairer to say "Lots of small (or legacy) library developers"?

For large-scale application development a class-based approach is the only way. In such a framework, object literals represent the data (while classes represent the business logic). It doesn't pay (in terms of memory, performance and maintainability) to dynamically endow object literals with sophisticated logic as proposed in the example above.

(NB: I don't have any objection to implementing this feature: I only point out that there are good reasons for TypeScript to remain biased towards classes.)

**Comment by fdecampredon** [comment]
> For large-scale application development a class-based approach is the only way. In such a framework, object literals represent the data (while classes represent the business logic). It doesn't pay (in terms of memory, performance and maintainability) to dynamically endow object literals with sophisticated logic as proposed in the example above.

Please don't expose your point of view as the only source of truth, a lot of javascript programmer hate class, and try to avoid them.
Also I don't know if you think about the typescript compiler itself as a *large-scale application* but one of the coding guideline of the project is : 
```
Classes

For consistency, do not use classes in the core compiler pipeline. Use function closures instead.
```

**Comment by danielearwicker** [comment]
@fdecampredon :+1:

> Where's the evidence for that? 

The obvious, most influential example would be Douglas Crockford.

**Comment by NoelAbrahams** [comment]
(
 > Please don't expose your point of view as the only source of truth

  Please do attempt to keep the discussion civilised as I do not know you from Adam. Thanks! :smiley: 

)

> a lot of javascript programmers hate class, and try to avoid them

Again, where is the evidence? What sort of code are they working on? My contention is they are probably small libraries.

> Also I don't know if you think about the typescript compiler itself as a large-scale application 

I don't think that the TypeScript compiler is a large-scale application at all. It is a very special body of code called a "compiler". It does not in any way represent real-world web/mobile/desktop/server-side business applications. 

> but one of the coding guideline of the project is :
Classes
For consistency, do not use classes in the core compiler pipeline. Use function closures instead.

The reference to the `core compiler pipeline` seems to suggest this is some special optimisation.
Also note `use function closures instead` does not mean "use object literals with functions attached to them instead".

@danielearwicker, I do not quite understand what is sited as evidence from JS experts. Some googling suggests that the man referred to is someone associated with legacy JavaScript systems.

**Comment by fdecampredon** [comment]
> Please do attempt to keep the discussion civilised as I do not know you from Adam. Thanks!

When you say 

> For large-scale application development a class-based approach is the only way.

It's your point of view, however you wrote that sentence like it's an absolute and irrevocable truth, It's not the first time I see you writing such comment and so I ask you in a *civilized way* to not do so.
Now I don't want to go in a stupid debate on **functional programming vs oop** If you want some information on the subject, google is your friend.

**Comment by jbrantly** [comment]
> Perhaps fairer to say "Lots of small (or legacy) library developers"?

It really doesn't matter. Object.assign is clearly a commonly used function and should be modeled in TS. This whole discussion is pointless and off-topic.

**Comment by NoelAbrahams** [comment]
@fdecampredon,

> For large-scale application development a class-based approach is the only way.
It's your point of view, however you wrote that sentence like it's an absolute and irrevocable truth

I am entitled to voice my opinion as an absolute and irrevocable truth. It is up to others to make one see the errors of their ways. I note that you have failed to do that so far. But you have done better in other topics, so I shall remain hopeful.

@jbrantly, yes, off-topic. As I made clear above. But we can't have the tail (small library developers) wagging the dog.

**Comment by AlexGalays** [comment]
(I wrote several big applications, and no, a class based approach is not the only way. I quite strongly dislike them, especially the JS ones)

**Comment by RyanCavanaugh** [comment]
Stay on-topic (intersection types!), please. This isn't the place to discuss JavaScript application architecture or other people's opinions thereof.

**Comment by mweststrate** [comment]
:+1:  for intersection types. 

Very useful for function that augment, enrich, or mix something in their input. I'm developing full time with Typescript and almost daily encounter useful cases for them. I now have to write explicit casts often, just to make sure the types of my data can be inferred.

**Comment by Ciantic** [comment]
I think the order should not matter, it should throw error if one tries to intersect incompatible field types.

If one really wants to intersect incompatible types there could also be a field removal/complement like in [elm-lang's records](http://elm-lang.org/learn/Records.elm#adding-deleting-and-renaming-fields). 

Basically if there is intersect, why couldn't there be removal/complement too (and other set operations, like include only fields in both types) like:

```
interface PersonWithAddress {
  name: string;
  age: number;
  address: string
}
interface Person = PersonWithAddress - { address } // Remove field address
// Person is now interface { name: string; age: number; }
```


Complement could work as well with other interfaces:

```
interface A {
  a: string;
  b: number;
}

interface B {
  b: number;
  c: string;
}

interface C = A - B;
// C is now { a: string; c: string }
```

With complement in place, it's now possible to use intersection both ways without errors:
```
interface A {
  a: string;
  c: string;
}

interface B {
  b: string;
  c: number
}

type AB = (A - { c }) & B // { a: string; b: string: c: number };
type BA = (B - { c }) & A // { a: string; b: string: c: string };
```

And it would not cause errors.

**Comment by stanvass** [comment]
@Ciantic it helps to think about intersection of types, not of their members. An intersection of two types is the union of their members, because the resulting intersection then belong to both types.

Also I agree order should not matter, compatible properties should merge, incompatible ones should error out. That's the only way to ensure the resulting type is truly an intersection belonging to both types.

**Comment by duanyao** [comment]
+1 for interception types.

But I'm confused with the semantic of interception of primitive types, e.g. what should `string & number` mean? [Flow type says it is meaningless](http://flowtype.org/docs/union-intersection-types.html):

>Not all intersection types make sense. For example, no value has type number & string since there is no value that can have both of those types.

However if interception of primitive types is not allowed, some use cases such as "[interface members conflict](https://github.com/Microsoft/TypeScript/issues/3375)" can't be modeled properly.

**Comment by danielearwicker** [comment]
@duanyao It can be modelled properly - but only where it makes sense. It's just that some types cannot intersect because they involve a contradiction. They disagree about the type of some member, in a way that cannot be reconciled. If we make such a request, the compiler is maximally helpful if it rejects it.

**Comment by duanyao** [comment]
@danielearwicker Yes, I am aware of the contradiction. But sometimes the contradiction only exists in TS side, not JS side. In these cases we usually use `any` to bypass TS type checker -- I wonder if there are better options than `any`.

**Comment by mweststrate** [comment]
If conflicting types are allowed, just use union types, which are already
part of typescript? (e.g MyClass | MyOtherClass)

**Comment by HerringtonDarkholme** [comment]
+1 again for this. It is needed not only by today's `Object.assign` but also by [ES7's object spread](https://github.com/sebmarkbage/ecmascript-rest-spread)

**Comment by DrRataplan** [comment]
@mweststrate 'cause that would make a type be either MyClass or MyOtherClass, instead of the actual union of the types: `{a: string, b: number} & {d: string, b:string[]} => {a:string, b: number|string[], d:string}`.

For now, for Object.assign, I am using an overloaded definition in the lines of:
```
function assign<A>(a: {}, b: A): A;
function assign<A>(a: A, b: A): A;
function assign<A, B>(a: A, b: B): any; // vs A & B
```

This works, and is kindof better than the any approach proposed by @duanyao, because it does help the TS type checker in the nontrivial cases of A and B being of the same type and cloning an object (```Object.assign({}, {a:2});```). Still :+1: for type intersections.

**Comment by duanyao** [comment]
@mweststrate The problem of `{a: string, b: number} & {d: string, b:string[]} => {a:string, b: number|string[], d:string}` is that `{a:string, b: number|string[], d:string}` is assignable to none of its super types.

**Comment by mweststrate** [comment]
Ah indeed, overlooked both items. Thanks :)

**Comment by jpolo** [comment]
+1
I am looking forward an expressive solution for something like ``` function (assertAPI, assertExtension) { return mix(assertAPI, assertExtension) } ``` and intersection type would fit right in.

**Comment by kseo** [comment]
+1 for intersection types.

In Flow, intersection types are used to mimic function overloading:

```
/* @flow */
declare var f: ((x: number) => void) & ((x: string) => void);
f('');
```

In TypeScript, we use union types to support function overloading.

```
function f(x: number | x: string): void {
...
}
```

These two functions actually have the same type because TypeScript used union types to encode intersection types of Flow. Intersection types are the dual of union types. When an arrow is distributed over a union, the union changes to an intersection.

```
(A -> T) & (B -> T)  <:  (A | B) -> T
```

I think adding intersection types makes the type system more orthogonal as we often use intersection types to encode union types or union types to encode intersection types. In case of function overloading, I think union types look more natural to most programmers. But typing `Object.assign` with union types seems not trivial. (Or is it possible?)

**Comment by HerringtonDarkholme** [comment]
@kseo Just a side note, flow's intersection type is problematic.  Please refer to  https://github.com/facebook/flow/issues/342 and https://github.com/facebook/flow/blob/master/tests/intersection/test.js

For TypeScript, because function is bivariant, there is probably fewer problems with intersection type
