### ISSUE TITLE
Decorating underscore prefixed methods fails

### ISSUE THREAD

**Issue by martin31821** [Microsoft/TypeScript#12562]
**TypeScript Version:**  2.1.1

**Code**

```ts
function dec(): Function
{
  return function (target: any, propKey: string, descr: PropertyDescriptor): void
  {
    console.log(target[propKey]);
    //logs undefined
    //propKey has three underscores as prefix, but the method has only two underscores
  };
}

class A
{
  @dec()
  private __foo(bar: string): void
  {
    // do something with bar
  }
}
```

**Expected behavior:**
`target[propKey]` should point to the decorated method

**Actual behavior:**
`target[propKey]` is undefined

My workaround is checking the property key in the decorator and deleting the first one underscore at the moment.

As far as I can tell the problem exists since typescript 2.1

Edit: updated code to reproduce problem when compiling

**Comment by aluanhaddad** [comment]
Your syntax is a decorator expression that tries to pass the method to `undefined` or is that just a typo?

**Comment by martin31821** [comment]
I updated the example above to produce the problem when compiled with tsc 2.1.1 and run with node/in browser.

**Comment by aluanhaddad** [comment]
This is really weird. It works in '2.0.10' and fails in '2.1.1' and in 'next'.

**Comment by DanielRosenwasser** [comment]
Confirmed.

**Comment by mhegazy** [comment]
@sheetalkamat can you take a look
