### ISSUE TITLE
Abstract accessor with implementation

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/TypeScript#12560]
**TypeScript Version:** master, commit 1418fd170d17692d44370831779934fba7c2665d

Are abstract getters/setters allowed to have an implementation?

Related: #7184

**Code**

```ts
abstract class A {
    private _a: string;

    abstract get a(): string {
        return this._a;
    }

    abstract set a(newName: string) {
            this._a = newName;
    }
}
```

**Expected behavior:**

Error on `get`  and `set` that abstract getters/setters shouldn't have an implementation.

**Actual behavior:**

No error.

**Comment by aozgaa** [comment]
Thoughts, @sandersn?

**Comment by sandersn** [comment]
I can't think of a reason this would make sense.

The fix should be pretty simple, in `checkGrammarAccessor` just add another error check that's the inverse of the current `else if (accessor.body === undefined && !(getModifierFlags(accessor) & ModifierFlags.Abstract)) ...`:

**Comment by aluanhaddad** [comment]
What's the use case for this really looks strange and I think it would confuse a lot of people. I don't know any language that allows a member to be both abstract and implemented.

**Comment by sandersn** [comment]
I agree. I think it should be an error.

**Comment by aluanhaddad** [comment]
Wow I totally missread the issue I thought it was your request for this feature 🍭

**Comment by sandersn** [comment]
Nope, it's a bug, not a feature. :)
