### ISSUE TITLE
Warn/error on pointless expression?

### ISSUE THREAD

**Issue by donaldpipowitch** [Microsoft/TypeScript#12576]
This is a **feature request**.

This is an example to some similar code I recently encountered. It was a little bit more complex in the real code.

```ts
interface Foo {
  bar?: {
    baz?: {
      nope?: number;
    };
  };
}

const foo = {
  bar: {
    baz: {
      nope: 1    
    }
  }
}

if (foo.bar && foo.bar.baz && foo.bar.baz.nope === 1) {
  foo.bar.baz.nope === 2;
}
```

Can you see the problem on first glance? Probably. But with more noise and stress around me, I couldn't see the bug for a while. "Of course" `foo.bar.baz.nope === 2;` should be `foo.bar.baz.nope === 2;`. There is no point to have a line like  `foo.bar.baz.nope === 2;`.

Maybe TypeScript could warn/error for cases like this with an additional setting (similar to settings like `noUnusedLocals` or `noUnusedParameters`). Maybe `noUnusedExpressions`? If expression is used without assigning the value to a variable or without being used inside `if ()` and similar cases, I don't see why anyone would want to  write an expression. If someone would write that to invoke some side effects that would be a bad style, too (IMHO).

**Comment by DanielRosenwasser** [comment]
For the record, TSLint's [no-unused-expressions](https://palantir.github.io/tslint/rules/no-unused-expression/) rule handles this as well.

**Comment by donaldpipowitch** [comment]
Nice. Thank you.

**Comment by yortus** [comment]
There is some related discussion of side-effect-free expressions in #10814.

**Comment by donaldpipowitch** [comment]
Cool, thanks for the link.

**Comment by mhegazy** [comment]
This falls more into the realm of a linter, and would be out of scope for the TS project at the time being.
