### ISSUE TITLE
No module elision when using --outfile & --module

### ISSUE THREAD

**Issue by DeneshPohar** [Microsoft/TypeScript#12571]
**TypeScript Version:**  2.0.10

I'm in the process of migrating a large codebase that uses internal modules (namespaces) exclusively.  I'd like to migrate some content to external modules, incrementally.  So, I'm investigating using --outfile with --module amd/system.

However, I'm seeing some results I didn't expect.  Consider the following:

mod.ts
```ts
export default function x() { console.log('this is an external module'); }
```

consumer.ts
```ts
import mod from './mod';

namespace consumer {
    export function func(x: typeof mod): void {
        // NOTE: only usage of 'mod' is in an argument type declaration
    }
}
```

Run the following
```
tsc --module amd --outfile _out\elide.js mod.ts consumer.ts
```

**Expected behavior:**
I expect the usage of the 'mod' module by the consumer to be elided.
```js
define("mod", ["require", "exports"], function (require, exports) {
    "use strict";
    function f() { console.log('this is an external module'); }
    exports.__esModule = true;
    exports["default"] = f;
});
var consumer;  // <- Note, this doesn't define a new module
(function (consumer) {
    function func(x) {
    }
    consumer.func = func;
})(consumer || (consumer = {}));
```

For comparison, run
```
tsc --outdir _out mod.ts consumer.ts
```

**Actual behavior:**
The following (note the ```define``` for the content in consumer.ts):
```js
define("mod", ["require", "exports"], function (require, exports) {
    "use strict";
    function f() { console.log('this is an external module'); }
    exports.__esModule = true;
    exports["default"] = f;
});
define("consumer", ["require", "exports"], function (require, exports) { // <- Why?
    "use strict";
    var consumer;
    (function (consumer) {
        function func(x) {
        }
        consumer.func = func;
    })(consumer || (consumer = {}));
});
```

**Comment by aluanhaddad** [comment]
Because import elision does not imply a change in format, only an optimization.

**Comment by DeneshPohar** [comment]
To better illustrate the inconsistency, add another internal module, but this time with no compile-time-only reference to types in an external module:

internalMod.ts
```ts
namespace internalMod {
    export function y(): void { console.log('I am an internal module.'); }
}
```
Run ```tsc --module amd --outfile _out\elide.js mod.ts consumer.ts internalMod.ts```

Result:
```js
define("mod", ["require", "exports"], function (require, exports) {
    "use strict";
    function f() { console.log('this is an external module'); }
    exports.__esModule = true;
    exports["default"] = f;
});
define("consumer", ["require", "exports"], function (require, exports) { // <- There's a module here, even though there's only a type reference (and no runtime reference)
    "use strict";
    var consumer;
    (function (consumer) {
        function func(x) {
        }
        consumer.func = func;
    })(consumer || (consumer = {}));
});
var internalMod; // <- No module here
(function (internalMod) {
    function y() { console.log('I am an internal module.'); }
    internalMod.y = y;
})(internalMod || (internalMod = {}));
```

**Comment by aluanhaddad** [comment]
That is the expected behavior. Outfile is also not necessary to observe it. Currently you can consume globals from external modules from the reverse doesn't make much sense because how would the global get hold of the external module?

**Comment by DeneshPohar** [comment]
From [TS Handbook](https://www.typescriptlang.org/docs/handbook/modules.html#optional-module-loading-and-other-advanced-loading-scenarios):
> The compiler detects whether each module is used in the emitted JavaScript. If a module identifier is only ever used as part of a type annotations and never as an expression, then no require call is emitted for that module.

Elision is a great feature, I don't understand why outfile would disable it.  For comparison, try the following
````
tsc --outdir _out mod.ts consumer.ts
````

I get the following for the same consumer.ts (note, it's not wrapped in a ````define````):
````ts
"use strict";
var consumer;
(function (consumer) {
    function func(x) {
    }
    consumer.func = func;
})(consumer || (consumer = {}));
````

The Principle of Least Astonishment makes me think that ````--outfile```` should be similar to the result if I didn't use outfile and concatenated the files manually.  That's not the case here, and I can't see a good reason why not.

**Comment by mhegazy** [comment]
@DeneshPohar i am not getting this to reproduce locally. what i am missing from your setup?

```sh
c:\test\12571>type mod.ts
export default function x() { console.log('this is an external module'); }

c:\test\12571>type consumer.ts
import mod from './mod';

namespace consumer {
    export function func(x: typeof mod): void {
        // NOTE: only usage of 'mod' is in an argument type declaration
    }
}

c:\test\12571>tsc --v
Version 2.2.0-dev.20161130

c:\test\12571>tsc --module amd --outfile _out\elide.js mod.ts consumer.ts

c:\test\12571>type _out\elide.js
define("mod", ["require", "exports"], function (require, exports) {
    "use strict";
    function x() { console.log('this is an external module'); }
    exports.__esModule = true;
    exports["default"] = x;
});
define("consumer", ["require", "exports"], function (require, exports) {
    "use strict";
    var consumer;
    (function (consumer) {
        function func(x) {
            // NOTE: only usage of 'mod' is in an argument type declaration
        }
        consumer.func = func;
    })(consumer || (consumer = {}));
});
```

**Comment by mhegazy** [comment]
also same output with `typescript@2.0.10`.

**Comment by DeneshPohar** [comment]
Thanks @mhegazy, I see the same behavior (note my "Actual" behavior in initial post).  My "expected" behavior is for the consumer.ts content to not be within a define.  I thought type elision should handle that, which is exactly what happens in the case where we don't use --outfile.

Basically, I don't understand why --outfile causes different behavior.

**Comment by mhegazy** [comment]
> I thought type elision should handle that, which is exactly what happens in the case where we don't use --outfile.

why does import elision have to do with changing a module into global script into?

**Comment by mhegazy** [comment]
>  I thought type elision should handle that, which is exactly what happens in the case where we don't use --outfile.

even if you do not use `--outFile`, the output of `customer.ts` would look like:

```ts
define(["require", "exports"], function (require, exports) {
    "use strict";
    var consumer;
    (function (consumer) {
        function func(x) {
            // NOTE: only usage of 'mod' is in an argument type declaration
        }
        consumer.func = func;
    })(consumer || (consumer = {}));
});
```

Cause it is a module. The compiler can not change the semantics of the file. the import elision is just an optimization.

**Comment by DeneshPohar** [comment]
Please try to run ````tsc --outdir _out mod.ts consumer.ts````.  The output I get is:
````ts
"use strict";
var consumer;
(function (consumer) {
    function func(x) {
    }
    consumer.func = func;
})(consumer || (consumer = {}));
````

I don't get what you're saying above, and I don't understand why there's any difference.  The output I get when using --outdir rather than --outfile is more desirable to me.

**Comment by mhegazy** [comment]
> @mhegazy, please try to run tsc --outdir _out mod.ts consumer.ts. The output I get is:

the default module system is `commonjs` so this commandline is equivalent to ` tsc --outdir _out mod.ts consumer.ts --module commonjs`

this module output is a valid CommonJS module, it just happens to have no import/export statement.

`--outFile` is not supported on `CommonJS` since node has its known semantics for locating modules, and bundling is not something that is supported in this world.

**Comment by DeneshPohar** [comment]
Thanks @mhegazy, now I understand.

**Comment by aluanhaddad** [comment]
@DeneshPohar I would suggest migrating to modules from the leaves of your project and working your way back to the root. Since a module can freely depend on a global when using `--module system` or `--module amd`, this will allow you to migrate to modules more easily.
