### ISSUE TITLE
Missing member 'style' in type dom element

### ISSUE THREAD

**Issue by alperencaliskan** [Microsoft/TypeScript#12583]
**TypeScript Version:**  2.1.1

**Code**

```ts
let reqbrowserdiv = document.querySelector("#reqbrowser");
reqbrowserdiv.style.display = "block";

```

**Expected behavior:** Compiles without error.

**Actual behavior:** 
```error TS2339: Property 'style' does not exist on type 'Element'. ```

**Comment by YuichiNukiyama** [comment]
In the first place, Element interface have *not* style propertiy. see [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Element)

**Comment by alperencaliskan** [comment]
Sorry it was in HTMLElement, should have casted to HTMLElement.
