### ISSUE TITLE
Missing member 'content' in type dom element

### ISSUE THREAD

**Issue by alperencaliskan** [Microsoft/TypeScript#12582]
**TypeScript Version:**  2.1.1

**Code**

```ts
let template = document.querySelector('#tmpreqbrowser');
let clone = document.importNode(template.content, true);

```

**Expected behavior:** Compiles without error.

**Actual behavior:** 
```error TS2339: Property 'content' does not exist on type 'Element'. ```

**Comment by YuichiNukiyama** [comment]
In the first place, Element interface have *not* content propertiy. see [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Element)

**Comment by alperencaliskan** [comment]
Sorry it was in HTMLTemplateElement, should have casted to HTMLTemplateElement.
