### ISSUE TITLE
Narrow "this" type

### ISSUE THREAD

**Issue by andy-ms** [microsoft/TypeScript#12587]
**TypeScript Version:**  nightly (2.2.0-dev.20161130)

**Code**

```ts
function f(this: string | number) {
    if (typeof this === "string") {
        const x: string = this;
    }
}
```

**Expected behavior:**

No error.

**Actual behavior:**

`a.ts(3,15): error TS2322: Type 'string | number' is not assignable to type 'string'.`

Rename `this` to `me` and it works.

**Comment by yume-chan** [comment]
```` TypeScript
class A {
    doA() { }

    tryDoB() {
        if (isB(this)) {
            this.doB(); // works
        }
    }
}

class B extends A {
    doB() { }
}

declare function isB(value: any): value is B;

function tryDoB(this: A): void {
    if (isB(this)) {
        this.doB(); // Property 'doB' does not exist on type 'A'.
    }
}
````

Type guards work on `this` of instance methods, but not normal functions, it's so annoying.

**Comment by SalathielGenese** [comment]
You are right @yume-chan , I even tried `instanceof` without clue. Had to cast :
```ts
(<B>this).doB(); // now works.
```

**Comment by DanielRosenwasser** [comment]
FWIW I'm not really sure that narrowing `this` makes sense on a primitive. Won't `this` be `Number | String` if the LHS of the dot is a `number | string`?

**Comment by SalathielGenese** [comment]
@DanielRosenwasser, Do you see anything worth it in the following code?
```ts
interface A {}
interface B {}
interface C {}

function fn(this: boolean): A;
function fn(this: number): B;
function fn(this: string): C;
function fn(this: boolean | number | string): A | B | C
{
    return <any>void 0;
}
```

**Comment by Andarist** [comment]
@RyanCavanaugh this one works OK today, the issue can be closed :)
