### ISSUE TITLE
Suggestion: export default interface / function / type / variable

### ISSUE THREAD

**Issue by twoeo** [Microsoft/TypeScript#12599]
**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)
2.1.1

**Code**

```ts
export default interface Test{
  //...
}
```

```ts
export default function test(){
  //...
}
```

```ts
export default type Test = number;
```

```ts
export default const Test = 123;
```

```ts
export default var Test = 'ABC';
```

**Expected behavior:**
Compile successfully.

**Actual behavior:**
Compile error.

**Comment by aluanhaddad** [comment]
```ts
export default interface {}
```
It would be nice and there already an issue tracking it #3792

```ts
export default function test() {}
```
Works perfectly and is fully supported.

-------------------------------------------------------------
I think that
```ts
export default {const | let | var}
```
Is something that TC39 will need to address. Perhaps suggest this over at https://esdiscuss.org

**Comment by mhegazy** [comment]
closing in favor of  #3792
