### ISSUE TITLE
tsc performance (npm vs exe)

### ISSUE THREAD

**Issue by pankleks** [Microsoft/TypeScript#12604]
Hi,

When I run TSC.exe from install of Vistual Studio 2015 (v 2.0.6.0) it is significantly faster than adequate version installed from npm.

Why is that? isn't the .exe version run node anyway under the hood?

Thanks,

**Comment by vladima** [comment]
`tsc.exe`  uses the same compiler implementation but runs it using [ChakraCore](https://github.com/Microsoft/ChakraCore) instead of V8

**Comment by pankleks** [comment]
Wow! such huge difference!
Is there instruction on how to build tsc.exe with ChakraCore?

Thanks!

**Comment by wallverb** [comment]
Can we get `tsc.exe` equivalent for osx ? :D

**Comment by vladima** [comment]
there are other things that might explain the difference in perf (though we've also seen that Chakra used to perform better in tsc related scenarios), i.e. `tsc.exe` by default will use `tsc.js` located next to it and this `tsc.js` might be older (and thus lack some features) comparing to the latest version of `tsc.js` available on npm. It is possible to point `tsc.exe` to another location using `--script` command line option (argument should be full path to `tsc.js` you want to use)

**Comment by aluanhaddad** [comment]
I've noticed that as well. I don't think it's simply new features taking longer to compile because I overwrote the TSC.JS file with a recent nightly build.
