### ISSUE TITLE
No error when `undefined` is added to a string

### ISSUE THREAD

**Issue by donaldpipowitch** [Microsoft/TypeScript#12601]
**TypeScript Version:**  2.1.1

**Code**

```ts
const foo = 'value' + undefined;
// foo === 'valueundefined'
```

**Expected behavior:**

An error. I don't see why anyone would ever want to do this. If someone wanted to do this he should use `(undefined as string)` or something like that.

**Actual behavior:**

No error.

**Comment by mhegazy** [comment]
consider this:

```ts
function f(value?: Enum) {
  switch (value) {
    case Enum.Value1:
      ..
    case Enum.Value2:
      ..
    defualt:
      console.log("Invalid value: " + value);
  }
}
```

if you can not add, undefined, in your `default` the error handling logic needs to handle undefined.

**Comment by donaldpipowitch** [comment]
Hmm... I probably rushed too much writing this issue. Of course you often have debugging code like `console.log('foo' + value)` where `value` could be anything... You probably don't know just by typings, if you want to add `undefined` or not.

I think I'll close this issue... Sorry about that.
