### ISSUE TITLE
Control flow doesn't recognise undefined check

### ISSUE THREAD

**Issue by donaldpipowitch** [microsoft/TypeScript#12600]
**TypeScript Version:**  2.1.1

**Code**

```ts
interface StdoutValue {
  stdout: string;
  stderr?: undefined;
}

interface StderrValue {
  stdout?: undefined;
  stderr: string;
}
type StreamValue = StdoutValue | StderrValue;

const stream: Array<StreamValue> = [
  { stdout: 'foo' },
  { stderr: 'bar' }
];

console.log(stream.map(value => value.stderr === undefined ? value.stdout.toUpperCase() : value.stderr.toUpperCase()));
```

**Expected behavior:**

No error with strict null checks.

**Actual behavior:**

Thinks `value.stdout` could be `undefined` on last line, but this is not possible.

**Comment by FranklinWhale** [comment]
Actually not only `undefined` check is not recognized, `null` check is not recognized either.

```ts
interface Properties {
	"property1"?: string
}
function getMap(): {[index: string]: Properties | null} {
	return {
		"1": {
			"property1": "test"
		},
		"2": null
	};
}
let map = getMap();
let item1Property1 = "1" in map && map["1"] !== null && "property1" in map["1"] ? map["1"].property1 : null;
```

The above code cannot be compiled when `strictNullChecks` is set to `true`. The following error is returned:

> The right-hand side of an 'in' expression must be of type 'any', an object type or a type parameter

**Comment by ahejlsberg** [comment]
We currently consider a type a discriminated union only when all of the possible discriminant values have types composed from unit types. Effectively this means that the `string` and `number` cannot be part of the discriminant value type. It certainly would be possible to support combinations of unit types and infinite types, although it does add more complexity to the analysis.

**Comment by wallverb** [comment]
Related: https://github.com/Microsoft/TypeScript/issues/12457

**Comment by RyanCavanaugh** [comment]
Tentative work item to investigate for the 2.4 milestone, approximately.

**Comment by eggers** [comment]
Here's another example of a failing case:

```ts
declare var maybeNull: number[] | undefined | null;

let isEmpty: boolean | undefined | null = maybeNull === undefined || maybeNull === null
    ? false
    : maybeNull; // Type of maybeNull should be `null | undefined`
// Instead error is:
//  Type 'false | number[]' is not assignable to type 'boolean'.
//  Type 'number[]' is not assignable to type 'boolean'.
```

**Comment by weswigham** [comment]
@eggers You just have your cases backwards:
declare var maybeNull: number[] | undefined | null;
```
let isEmpty: boolean | undefined | null = maybeNull === undefined || maybeNull === null
    ? maybeNull // Type of maybeNull _is_ `null | undefined`
    : false;
```

**Comment by ahejlsberg** [comment]
Closing as the original example is no longer an error.
