### ISSUE TITLE
Mapped types with direct and aliased keyof usage

### ISSUE THREAD

**Issue by arusakov** [Microsoft/TypeScript#12602]
**TypeScript Version:** master (fc1f6e3ee6acea2176488a120999f4d2b0f48825)

**Code**
```ts
type X = {
  a?: any;
  b: any;
}

type Keys = keyof X;

type Direct = {
  [K in keyof X]: any;
}
// type Direct = {
//   a?: any; - optional
//   b: any;
// }

type WithAlias = {
  [K in Keys]: any;
}
// type WithAlias = {
//   a: any; - required
//   b: any;
// }
```

**Expected behavior:**
Types `Direct` and `WithAlias` have the same `a` property. I think that `a` property must be required in both `Direct` and `WithAlias` types.

**Actual behavior:**
Types `Direct` and `WithAlias` have different `a` property (optional and required).

**Comment by ahejlsberg** [comment]
This is working as intended. See #12563.
