### ISSUE TITLE
Switch case tslint error

### ISSUE THREAD

**Issue by Serginho** [Microsoft/TypeScript#12612]
**TypeScript Version:**  2.0.3 (tslint: 3.13.0)

**Code**

```ts
switch(foo){
case 0:
if(condition){
return 'something1';
else{
return 'something2';
}
case 1:
//Some code
}

```

**Expected behavior:**
Pass lint with no errors
**Actual behavior:**
TsLint error: expected a 'break' before 'case'. This's not happen if you use only return instead if clause, like:

```ts
// This pass lint inspection
case 0:
return 'something1';
case 1:
//Some code
```

**Comment by mhegazy** [comment]
Please report this at https://github.com/palantir/tslint
