### ISSUE TITLE
Type guard not working in returned function

### ISSUE THREAD

**Issue by andraaspar** [Microsoft/TypeScript#12616]
**TypeScript Version:**  2.2.0-dev.20161202

**Code**

```ts
function getGetter() {
	let data = {}
	data['bar'] = 1
	
	if (hasBar(data)) {
		return () => data.bar // Property 'bar' does not exist on type '{}'.
	}
}

function hasBar(thing): thing is {bar: number} {
	return typeof thing.bar == 'number'
}
```

**Expected behavior:**
Compile successfully.

**Actual behavior:**
```
index.ts(6,21): error TS2339: Property 'bar' does not exist on type '{}'.
```

**Comment by ahejlsberg** [comment]
Your example works if you use `const` to declare `data`. Type guards for `let` variables are not in effect in nested functions because the variable might be reassigned. See #8849.

**Comment by andraaspar** [comment]
I see. You are right.
