### ISSUE TITLE
Cannot use indexed access type on an intersection using keyof on constitutents

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#12625]
This might be too complex, but in trying to work around #12624

```ts
interface Options<Data, Computed> {
    data?: Data
    computed?: Computed;
}

declare class Component<Data, Computed> {
    constructor(options: Options<Data, Computed>);

    get<K extends keyof Data | keyof Computed>(key: K): (Data & Computed)[K];
}
```

I get the following error

> Type `K` cannot be used to index into type `Data & Computed`.

Which I believe should be valid.

**Comment by mhegazy** [comment]
i am not getting this error locally. can you provide more details?

**Comment by DanielRosenwasser** [comment]
Sorry, I fixed up the example.

**Comment by ahejlsberg** [comment]
There's still a copy and paste error. 😛

For this to work we would have to implement a rule that says `keyof T | keyof U` is permitted as the index in a `(T & U)[K]`. I don't really think that is worthwhile. However, a `K extends keyof (T & U)` ought to work but currently doesn't.

**Comment by DanielRosenwasser** [comment]
Ugh - fixed!

Yes, I think this will come up way less than `K extends keyof (T & U)`. It was only as a workaround that I looked into this.

**Comment by mhegazy** [comment]
@ahejlsberg we distribute unions on all other type operators now. so why not `keyof`. It makes sense that `keyof (A | B)` to be eqivelant to `keyof A | keyof B`

**Comment by ahejlsberg** [comment]
@mhegazy Actually, `keyof T` is contravariant with T, so `keyof (A & B)` is equivalent to `keyof A | keyof B`. For `keyof (A | B)` you want the keys that are present in both `A` and `B` and that isn't what you get with `keyof A | keyof B`.
