### ISSUE TITLE
Typescript Files not nested in VS2017RC

### ISSUE THREAD

**Issue by gregoryagu** [Microsoft/TypeScript#12629]
**TypeScript Version:**  2.1.1 

**Visual Studio 2017RC**

**ASPNETCORE Project**

**Expected behavior:**

test.js to be nested under test.ts.

**Actual behavior:**

test.js is at the same level as test.ts.

This works fine in VS15.

**REPRODUCE**

Create new ASPNETCORE project.

Add test.ts file.

Build

View generated test.js and test.js.map.

If there is a better place to report this, let me know.

**Comment by mhegazy** [comment]
TypeScript VS Plugin never supported nesting new .js files under .ts files. if i am not wrong this used to be a feature of [webessentials](http://vswebessentials.com/), so you might want to post it on their forum instead.

**Comment by gregoryagu** [comment]
You are correct.  Just got a response from Mads on this.
