### ISSUE TITLE
TS2503: Cannot find namespace 'moment'

### ISSUE THREAD

**Issue by valotas** [Microsoft/TypeScript#12634]
**TypeScript Version:**  2.0.10

I am not sure if it is a moment problem or a typescript behavior/bug.

I'm just trying to use moment within a `d.ts` file. Moment ships with a d.ts file and everything works as soon as I import something from there. If I try though to define my own d.ts file containing definitions from moment. The compiler complains

**Code**

```ts
interface SomethingWithMoment {
    moment(): moment.Moment;
}
```

**Expected behavior:**
Have a successful build

**Actual behavior:**
I get an `TS2503: Cannot find namespace 'moment'`

**Other information that may be helpful:**
Example project: https://github.com/valotas/ts-moment

Surprisingly when running tsc with `--traceResolution` it looks like it finds the right file within node_modules.

I tried both `/// <reference types="moment" />` and `/// <reference file="path/to/moment" />`

**Comment by blakeembrey** [comment]
@valotas Did you import from moment? You need to import the types before using them - they aren't global to TypeScript.

**Comment by patrickhousley** [comment]
I am having the same issue when using a declare statement: `declare const moment: moment.Moment;`. I do not want to import the library because it already exists on the window. Any help is greatly appreciated.

**Comment by aluanhaddad** [comment]
As @blakeembrey correctly points out, moment does not expose a global declaration. You must import it.
@patrickhousley if you only use moment in type position, i.e as as a type annotation, TypeScript will not include import statement in emitted JavaScript.
You want to use
```ts
import { Moment } from 'moment';
```
That said, the following is likely not what you want
```ts
declare const moment: Moment;
```
because `Moment` is not the type of the `moment`.

**Comment by valotas** [comment]
@blakeembrey I thought that this should not be the case within `d.ts` files. Did that change? As soon as `import {Moment} from 'moment'`, it works. Should it be that way? If yes please close this and ignore me :)

**Comment by blakeembrey** [comment]
Yes, that's correct. It's possible you used DefinitelyTyped in the past, where modules usually explicitly pollute the global namespace. That style is slowly fading away.

**Comment by valotas** [comment]
But then, I should be importing my `types.d.ts` everywhere as it will be considered a module right?

**Comment by DanielRosenwasser** [comment]
@valotas correct, though I've sent out https://github.com/moment/moment/pull/3688 to address this.
