### ISSUE TITLE
compiler option "strictNullChecks" working unexpected for Union Type 

### ISSUE THREAD

**Issue by YuJianrong** [Microsoft/TypeScript#12638]
**TypeScript Version:**  2.0.10 / nightly (2.2.0-dev.201xxxxx)

**Code**

```ts
let x: {[v: string]: number} | {y?: number} = {a : null};
// Both the following assigns raise compile error
// let x: {[v: string]: number} = {a : null};
// let x: {y?: number} = {a : null};
```

**Expected behavior:**
Compile error raised when "strictNullChecks" is set to true.

**Actual behavior:**
No compile error. Please note compile error will be raised when union type is not used.

**Comment by aluanhaddad** [comment]
That seems correct. One of the constituents of the union is `{}` which is a valid assignment target.

**Comment by YuJianrong** [comment]
@aluanhaddad , but the following code is not working:
```ts
let x: {y?: number} = {a : null};
```
`{y?:number}` should be same as `{}`, but I get the following compile error:
```
```

**Comment by mhegazy** [comment]
seems to be the same request in https://github.com/Microsoft/TypeScript/issues/12745
