### ISSUE TITLE
No compile error when assign a boolean to an empty interface

### ISSUE THREAD

**Issue by YuJianrong** [Microsoft/TypeScript#12637]
**TypeScript Version:**  2.0.10

**Code**

```ts
interface T1 { } ;
interface T2 { option?: string} ;

let x1: T1 = false;
let x2: T2 = true;
```

**Expected behavior:**
Compile error raised, boolean value should not be able to assign to an interface even it's empty.

**Actual behavior:**
No compile error.

**Comment by mhegazy** [comment]
Please see https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-all-types-assignable-to-empty-interfaces
