### ISSUE TITLE
Add module augmentation to spec

### ISSUE THREAD

**Issue by basarat** [microsoft/TypeScript#12642]
Couldn't find it here : https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md (search `augment`). 

Struggled to get it write for TypeStyle but did manage:

![image](https://cloud.githubusercontent.com/assets/874898/20862989/59cb9282-ba0f-11e6-8933-c25cf052fb66.png)

Notes of magic: 
* File must be `augment.ts` (a `.d.ts` does not work)
* File must have some *import* otherwise it *declares the module* instead of *augmenting*. 

The example presented in the blog post (https://blogs.msdn.microsoft.com/typescript/2016/02/22/announcing-typescript-1-8-2/) doesn't mention fact that you must export something? Perhaps the example doesn't work?
![first](https://cloud.githubusercontent.com/assets/874898/20863000/d4702cd2-ba0f-11e6-9af7-a6b32ede0954.png)

Nevertheless, appreciate all the hard work :heart: 

/cc @DanielRosenwasser @blakeembrey :rose:

**Comment by RyanCavanaugh** [comment]
The spec is now an "archived" artifact and we won't be tracking defects against it anymore.
