### ISSUE TITLE
Don't show prompts during command-line (devenv) builds

### ISSUE THREAD

**Issue by nil4** [Microsoft/TypeScript#12649]
**TypeScript Tool Version:**  2.0.6 in Visual Studio 2015 Update 3

We use a TFS build agent to build our .NET projects. We also scan each project using HP Fortify Static Code Analyzer, which requires using the antiquated command-line approach: `devenv.com SolutionName  /Build Debug`. 

Recently I installed TypeScript tools v2.0.6 on the build agent, and our builds started timing out. After investigating I discovered that during the command-line build, TypeScript pops up a modal dialog box prompting to upgrade the `<TypeScriptToolsVersion>` property:

![ts-modal-dialog](https://cloud.githubusercontent.com/assets/139133/20865893/0e9b99d8-ba1e-11e6-9759-f052875ec30a.png)

**Expected behavior:**

Command-line builds using `devenv /Build` do not show any prompts or display any UI that requires user interaction. 

**Actual behavior:**

A modal dialog box prompts to upgrade the TypeScriptToolsVersion.

**Comment by vladima** [comment]
@paulvanbrenk should be fairly simple to do something similar to [this code](https://github.com/Microsoft/visualfsharp/blob/6ce962e97de24273d167b6c174344e3017a6e4c7/vsintegration/src/FSharp.ProjectSystem.Base/Project/ProjectNode.cs#L6459)

**Comment by nil4** [comment]
Polite bump. Any chance of this being resolved? Our workaround for now is to force `TypeScriptCompileBlocked` in all projects during scans. This hides actual errors and is not sustainable in the long run.

**Comment by nil4** [comment]
⏳ half a year and counting...
