### ISSUE TITLE
What is the typescript 2.1.1 release???

### ISSUE THREAD

**Issue by scharf** [Microsoft/TypeScript#12655]
I don't really understand the release `2.1.1`:

   https://github.com/Microsoft/TypeScript/releases/tag/v2.1.1

How is that related to `2.1-rc`?

   https://github.com/Microsoft/TypeScript/releases/tag/v2.1-rc

From the version number it is a peak into the future....

**Comment by blakeembrey** [comment]
@scharf https://github.com/Microsoft/TypeScript/issues/12485 might help you.

**Comment by mhegazy** [comment]
2.1.1 is 2.1-rc. the two tags point to the same commit: https://github.com/Microsoft/TypeScript/commit/8e8ec9f81d6282c70ef268736c5ed4541c3facbe.

for file versions, e.g. tsc.exe, or TypeScriptTasks.dll, we can not use the `-rc` in the file version. so for consistency we use a full version string (e.g. `2.1.1.0`) for releases.
you will notice that `2.0.2` was the same as `2.0-rc`, and `1.8.1` is the same as `1.8-beta`, etc..

hope that clears it up.
