### ISSUE TITLE
Keyof interaction with Currying

### ISSUE THREAD

**Issue by RubenSlabbert** [Microsoft/TypeScript#12658]
**TypeScript Version:**  nightly (2.2.0-dev.20161204)

**Code**

```ts
// Function prop: Returns the property P given as a string of the object T
prop<T, P extends keyof T>(p: P, obj: T): T[P];
prop<T, P extends keyof T>(p: P): (obj: T) => T[P]; // Curried version

const foo = prop('foo', { foo: 0 }); // Works fine
const bar = prop('bar')({ bar: 0 }); // Error: "Argument of type '"bar"' is not assignable to parameter of type 'never'."
```

**Expected behavior:**
The curried version of `prop` should lazily infer the type of `T` once the entire function is available.

**Actual behavior:**
The second instance of `prop` assigns `T` to `never`. This can be fixed by calling `prop<Type, 'prop'>('prop')` but that sets the types up front which makes it less flexible.

It should be noted that the [variadic kinds proposal](https://github.com/Microsoft/TypeScript/issues/5453) might solve this by providing a workaround, but that's not necessarily the correct solution.

**Comment by gcnew** [comment]
See https://github.com/Microsoft/TypeScript/issues/12022#issuecomment-258223491.

The solution (credit HerringtonDarkholme) is:

```ts
function prop<K extends string>(k: K): <V>(v: {[k in K]: V} & {[k: string]: any}) => V {
    return v => v[k]
}

var testProp = prop('test')

var num = testProp({test: 123, additional: 'additional'})
```

**Comment by RubenSlabbert** [comment]
Ah that's great! Thanks for pointing it out.
