### ISSUE TITLE
Bug or feature?

### ISSUE THREAD

**Issue by GordonSmith** [Microsoft/TypeScript#12650]
TypeScript Version:  2.0.10

The following code does _not_ produce a syntax error (and I am really hoping this is a feature and not a bug):
```ts
class MyClass {
    test: { (): number; (_: number): MyClass }
}
let tmp = new MyClass();
tmp
    .test(22)
    .test()
;
```

**Expected behavior:**
Syntax error at compilation time on MyClass declaration

**Actual behavior:**
Runtime error on call to ```tmp.test```

**Comment by aluanhaddad** [comment]
Definitely not a bug. It is a valid type annotation. Initializing is a bit of a pain.\
```ts
class MyClass {
  test: { (): number; (_: number): MyClass } = ((_?: number | undefined) => {
    if (_ || _ === 0) {
      return new MyClass();
    }
    return 10;
  }) as any;
}
let tmp = new MyClass();
```
No runtime errors

**Comment by GordonSmith** [comment]
@aluanhaddad Interesting and I think your may well be correct since "test" is just a property and not a method (which happens to be an instance of an interface declared inline).

What I wrote is effectively a more declarative version of this:
```
class MyClass {
    test2: (_?) => number | MyClass;
}
```
Which also produces no compile time error - thx.
