### ISSUE TITLE
Compiler complains on valid destructuring with default values

### ISSUE THREAD

**Issue by bgoscinski** [Microsoft/TypeScript#12653]
**TypeScript Version:**  nightly (2.2.0-dev.20161127), online playground

**Code**

```ts
const [a, b = a] = [1]; // Block-scoped variable 'a' used before its declaration.
(function ([a, b = a]) { // Initializer of parameter 'b' cannot reference identifier 'a' declared after it.

})([1])
```

**Expected behavior:**
No error
**Actual behavior:**
Error on line 1: `Block-scoped variable 'a' used before its declaration`
Error on line 2: `Initializer of parameter 'b' cannot reference identifier 'a' declared after it.`

**Comment by HerringtonDarkholme** [comment]
Probably a duplicate of https://github.com/Microsoft/TypeScript/issues/12609
