### ISSUE TITLE
Suggestion: declare module 'react' as React

### ISSUE THREAD

**Issue by twoeo** [Microsoft/TypeScript#12664]
**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)
2.1.1

**Code**
Always we use some npm packages need to import like this:
```ts
var react = require('React');
```

In TypeScript way it is:
```ts
import * as React from 'react';
```

Many packages like this.
The main problem is, if I want to use `React` in TypeScript way, I may need a declaration like this:
```ts
declare module 'react' {
  //...
}
```

But this is not friendly to code auto completation, nothing refer that 'react' should be used as `React`.

So, what if we can assign a default name to `import * from 'xxx'` ? Like

```ts
declare module 'react' as React
```

**Comment by RyanCavanaugh** [comment]
We don't plan to add additional import syntax beyond what ES6 already has.

I can't say for sure but maybe you're confused about how all the importing stuff works -- there's nothing saying you need to import `"react"` as `React`. The second name is arbitrary and can vary from file to file.
