### ISSUE TITLE
Exhaustiveness checking doesn't work with variables

### ISSUE THREAD

**Issue by asyschikov** [microsoft/TypeScript#12668]
**TypeScript Version:**  2.1.1

If you have exhaustiveness checking where a result is a return from a function it works.
But if result is assigning value to a variable exhaustiveness checking basically does nothing.

**Code**

```ts
interface Square { kind: "square"; size: number; }

interface Rectangle { kind: "rectangle"; width: number; height: number; }

interface Circle { kind: "circle"; radius: number; }

interface Triangle { kind: "triangle"; side: number; }

type Shape = Square | Rectangle | Circle | Triangle;

function area(s: Shape): number {
    let area;
    switch (s.kind) {
        case "square": area = s.size * s.size; break;
        case "rectangle": area = s.width * s.height; break;
        case "circle": area = Math.PI * s.radius * s.radius; break;
        case "triangle": area = Math.sqrt(3) / 4 * s.side * s.side; break;
        //default: area = -1; break;
    }
    //Error because area is number | undefined
    return area;
}

function areaWrapped(s: Shape): number {
    let area;
    area = (() => {
        switch (s.kind) {
            case "square": return s.size * s.size;
            case "rectangle": return s.width * s.height;
            case "circle": return Math.PI * s.radius * s.radius;
            case "triangle": return Math.sqrt(3) / 4 * s.side * s.side;
        }
    })();
    return area;
}
```

**Expected behavior:**

Function `area`: variable `aria` should be `number` because the check is exhaustive. 
Sidenotes:
1. If I uncomment `default` then `tsc` believes that check is exhaustive.
2. `areaWrapped` uses IIFE to achieve the same effect and it works.

**Actual behavior:**

Variable `area` is of type `number | undefined` while it can't be `undefined`.

**Comment by RyanCavanaugh** [comment]
There are architectural / phase-ordering things that make this more complex than it first appears. Anyway adding a sensible `default: throw new Error();` case makes the error go away, or add `let! area;`
