### ISSUE TITLE
how to use a custom class extends  Promise

### ISSUE THREAD

**Issue by renyaoxiang** [Microsoft/TypeScript#12661]
i write a new class extends promise ，but it does not work in my browser. 
i am not sure if it is caused by a bug of typescript or my inaccurate usage。

while i make a new instance like this:
`this.mypromise = new PPromise()`

the browse throw an error
“ Uncaught TypeError: #<PPromise> is not a promise”

the PPromise defination is:

`export class PPromise<T> extends Promise<T>{`
`    resolve: (value?: T | PromiseLike<T>) => void`
`    reject: (value?: T | PromiseLike<T>) => void`
`    constructor(callback?:`
`        ( resolve: (value?: T | PromiseLike<T>) => void,`
`          reject: (value?: T | PromiseLike<T>) => void`
`        ) => void) {`
`        super((resolve, reject) => {`
`          this.resolve = resolve`
`          this.reject = reject`
`          callback && callback(this.resolve, this.reject)`
`      })`
`  }`
`}`

**Comment by HerringtonDarkholme** [comment]
This is probably transpiler's limitation. See https://github.com/Microsoft/TypeScript/issues/12123#issuecomment-259948891 for more information.

**Comment by masterkidan** [comment]
@mhegazy : Tried using the Object.setPrototype here, but the error is actually thrown in the super.apply call, 
Is there any workaround for this?

**Comment by jvanoostveen** [comment]
I have yet to get this to work, when in pure JavaScript (in Chrome) it works like a charm, in node, it also works, but when trying to do this in TypeScript (running in node with TSNode), I keep getting the `is not a Promise` error...

**Comment by mhegazy** [comment]
Sorry, this was misslabled. this is is not the same as #12123. This is not the same as other ES5-builtins. this is a duplicate of https://github.com/Microsoft/TypeScript/issues/15202.

The main issue here is that ES6 classes (e.g. `Promise`) are not callable, the way ES5 built in classes (e.g. `Array`). The emitted code that the compiler produces uses `super.call` which throws in ES6 engine.
