### ISSUE TITLE
string.normalize() producing error while compile target is es6, but es6 supports normalize method in strings

### ISSUE THREAD

**Issue by desanik** [Microsoft/TypeScript#12663]
Duh!

I suggest you coorect this bug:
```ts
console.log(str.normalize("NFD"));
error TS2339: Property 'normalize' does not exist on type 'string'.
```
for tsconfig:
```json
{
  "compilerOptions": {
    "target": "es6",
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true,
    "typeRoots": [
            "node_modules/@types"
        ]
  }
}
```

**TypeScript Version:**  2.0.10

**Code**
console.log(str.normalize("NFD"));

   >> produces:  error TS2339: Property 'normalize' does not exist on type 'string'.

for tsconfig.json:
```json
{
  "compilerOptions": {
    "target": "es6",
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true,
    "typeRoots": [
            "node_modules/@types"
        ]
  }
}
````

```ts
// A *self-contained* demonstration of the problem follows...

```

**Expected behavior:**
No error
**Actual behavior:**
error TS2339: Property 'normalize' does not exist on type 'string'.

**Comment by desanik** [comment]
Pls, this is important string.normalize() is not an error in es6 or es2015

**Comment by mhegazy** [comment]
`String.prototype.normalize` is defined in the [library file](https://github.com/Microsoft/TypeScript/blob/5c71de103a63eb413ccaa02f369c37e134986650/lib/lib.es6.d.ts#L4596). This works for me locally.

```sh
c:\test\12663>type a.ts
var str: string;

console.log(str.normalize("NFD"));

c:\test\12663>type tsconfig.json
{
  "compilerOptions": {
    "target": "es6",
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true,
    "typeRoots": [
            "node_modules/@types"
        ]
  }
}
c:\test\12663>tsc --v
Version 2.1.4-insiders.20161201

c:\test\12663>tsc

c:\test\12663>echo %ERRORLEVEL%
0
```

**Comment by desanik** [comment]
Hello mhegazy,
Following your test (doing it in windows 10 also) it works, I am sorry for posting this error. Actually, compiling was being made for single files (for testing purposes). But single file compiling doesn't automatically use flags from tsconfig.json. that is where the error comes from.
c:\test\12663> tsc a.ts
a.ts(3,17): error TS2339: Property 'normalize' does not exist on type 'string'.

c:\test\12663> tsc a.ts -target es6

c:\test\12663>echo %ERRORLEVEL%
0

Greetings
