### ISSUE TITLE
Typescript 2.1.1 targeting es5 or es3 still produces yield statements on await Promise.all

### ISSUE THREAD

**Issue by netdragonboberb** [Microsoft/TypeScript#12679]
Even with the alwaysStrict flag set, the following code is turned into "yield Promise.all(...)"

**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)

**Code**

await Promise.all(globalConfigPromises);

```ts
// A *self-contained* demonstration of the problem follows...

```

**Expected behavior:**
use __awaiter or something like that
**Actual behavior:**
yield Promise.all(globalConfigPromises);

**Comment by aluanhaddad** [comment]
`--alwaysStrict` is not related. I am not seeing this on nightly, can you share you other settings?

**Comment by netdragonboberb** [comment]
I pulled it with npm install

 From tsconfig (I tried with or without "lib" and many variations)
      "module": "commonjs",
      "target": "es5",
      "noImplicitAny": false,
      "sourceMap": true,
	  "alwaysStrict": true,
	  "lib": [
            "es5",
            "es6",
            "es2015.collection",
            "es2015.promise",
            "es2015.core"
        ]
    }))

From package.json:
 "dependencies": {
    "bluebird": "^3.4.1",
    "lodash": "^4.12.0",
    "moment": "^2.10.6",
    "mysql": "^2.10.2",
    "redis": "^2.6.0-2",
    "sequelize": "^3.19.3",
    "gulp-typescript": "^3.0.2",
    "typescript": "^2.1.1"
  }

**Comment by netdragonboberb** [comment]
@aluanhaddad I just realized there are two typescript versions being used in the project (kind of out of necessity) and what I'm building is a small module which I would like to use a different typescript version than the main project. Since gulpfile is shared, it may be using the wrong one, but I have no way to figure that out. I put "version" in tsconfig.json to try to figure it out but I don't see the typescript version being outputted, so I have no idea which one it's using.

**Comment by netdragonboberb** [comment]
I figured it out. I needed to add the following to tsconfig:
 typescript: require(subdirectoryContainingCodeForTS2_1_1+'/node_modules/typescript')

**Comment by aluanhaddad** [comment]
import gulp = require('gulp');
import gulpTypescript = require('gulp-typescript');
import typescript = require('./path-to-typescript@/lib/typescript');


gulp.task('build-new', () => {
    return gulp.src('./async-await-is-great')
        .pipe(gulpTypescript({ typescript }))
        .pipe(gulp.dest('./async-await-is-great.js'));
});

**Comment by netdragonboberb** [comment]
Thanks. One other thing I did was remove that "lib" part (even though mentioned in the documentation) since it was causing errors like "Cannot find global type 'Array'"
