### ISSUE TITLE
TypeScript casts to `any` circle type

### ISSUE THREAD

**Issue by aspirisen** [Microsoft/TypeScript#12686]
**TypeScript Version:**  2.0.9 / nightly (2.2.0-dev.20161205)

**Code**

```ts
interface To {
    (base: string, s: any): Two;
}

interface Two {
    (v: boolean): One;
    mods: (v: (to: To) => Array<Two>) => One
}

interface One {
    one: () => Two
}

function test<T>(v: (o: One) => T): T {
    return null;
}

var q = test(o => ({

    z: 'z-object',

    a: o.one()
        .mods(to => [
            to(q.z, { color: 'red' })
        ])

}));

```

**Expected behavior:**
`q` has a type of `test` function call result

**Actual behavior:**
`q` has type `any`
![image](https://cloud.githubusercontent.com/assets/3620639/20924095/c49415be-bbc0-11e6-9269-3f270f0f5327.png)

If you put `null` instead of `q.z` it will work
![image](https://cloud.githubusercontent.com/assets/3620639/20924133/ff8a587c-bbc0-11e6-88bb-0613317f3199.png)

**Comment by aluanhaddad** [comment]
This looks like it might be related to #12621.

**Comment by HerringtonDarkholme** [comment]
Hi, this is probably you are cyclic referencing `q` in its initialization.

To infer `q`, compiler must infer all its properties. To infer properties, compiler must check the type of `one().mods` and `to`. To check if `to`is correctly called, it needs to infer its arguments, which is `q.z`.

So the cyclic inference. And it correctly reports error under `--noImplicitAny`

**Comment by aspirisen** [comment]
@HerringtonDarkholme thanks for explaining. 
What is the type if I hover over `test` function, but `q` at the same time is `any`
![image](https://cloud.githubusercontent.com/assets/3620639/20926492/995dade4-bbcd-11e6-8275-956c3ec28309.png)

**Comment by HerringtonDarkholme** [comment]
Because TypeScript checker won't give up checking when it finds error. q is typed as any and `q.z` as any as well. So `test` is still get correctly typed, but q's type cannot be assigned by the return type because compiler already finds it cyclic. If we do assign, we might miss other errors.

**Comment by aspirisen** [comment]
@HerringtonDarkholme will this behaviour be changed one day, or will it be forever?

**Comment by mhegazy** [comment]
My recommendation is to give `q` an explicit type annotation.
