### ISSUE TITLE
Suggestion: compiler option to suppress js import errors

### ISSUE THREAD

**Issue by jedmao** [Microsoft/TypeScript#12682]
I spoke with @waderyan at the Microsoft booth at [Node.js Interactive in Austin, TX](http://events.linuxfoundation.org/events/node-interactive) this last week and he asked me to voice this particular concern here on the TS issues. I hope I can explain the problem well enough.

## The problem

The [`--allowJs` compiler flag](https://www.typescriptlang.org/docs/handbook/compiler-options.html) is a great step forward, but the problem remains that TypeScript is difficult to introduce into an already-existing project. Take [this reddit post](https://www.reddit.com/r/javascript/comments/39cere/typescript_vs_flow_results_from_our_investigation/) as an example:

> very difficult to bring in piece-meal, in fact we weren't able to get it working end to end on a small part of our code because we kept on having to "upgrade" files to TypeScript. (this may have been due to a fundamental misunderstanding that we had, but we didn't have such problems with Flow)

I've had similar issues following along the wiki tutorial, [&ldquo;Using React and Webpack with TypeScript&rdquo;](https://www.reddit.com/r/javascript/comments/39cere/typescript_vs_flow_results_from_our_investigation/), trying to bring TS into our existing React/Webpack project, but to no avail (too many errors importing js files). Recent team discussions have been very timid about introducing TS into our project for this very same reason.

## Possible solution

The best solution I can come up with is a new `--suppressJsImportErrors` compiler flag that would make relative js imports kind of wild in a way. The expectation would be that all type information that can be extracted would be extracted, but errors would be ignored.

TypeScript, being a superset of JavaScript, should theoretically allow you to pass any js file through the compiler w/o errors if this flag were set. Perhaps `--suppressJsErrors` would be more appropriate, if it wasn't just imports, but all js files.

Open to suggestions, of course.

**Comment by RyanCavanaugh** [comment]
How would this be different from the existing
```ts
declare module "*";
```
which effectively silences all import errors?

**Comment by aluanhaddad** [comment]
I think this is asking something different. I think the desire is to enable the flow of type information between TypeScript and JavaScript sources where possible but to not report any errors where it can't be resolved.

**Comment by jedmao** [comment]
@RyanCavanaugh, @aluanhaddad is correct. I don't want to silence all import errors.

## Best case scenario

It would work as @aluanhaddad just stated:

> enable the flow of type information between TypeScript and JavaScript sources where possible but to not report any errors where it can't be resolved.

## Worst case scenario

It would work like importing an npm module for which there are no `@types` to acquire (no errors, but no type information either).

Remember, this needs to work with relative file imports as well so that existing js projects can start implementing TypeScript files little by little; yet, provide as much type information as possible.

**Comment by aluanhaddad** [comment]
I guess this would be like allowing the type of every value to be implicitly `any` but in a _non-greedy_ (I'm not sure if this makes any sense) manner such that given
**x.js**
```js
export default 'a very arbitrary';
```
**y.ts**
```ts
import x from './x';

const a = x + ' something or other'; // string
const b = x.length + 3; // number
const c = x(3); // any - explodes at runtime
const d = x(3).asdf; // any - explodes at runtime
```
this would basically be a sort of "sloppy" or perhaps "implicitAny" mode.

@jedmao is that kind of the idea?

**Comment by jedmao** [comment]
Thanks @aluanhaddad. That is the general idea; however, I'm having issues ATM reproducing some things I was seeing before. In order not to waste anybody's time, I'm going to close this issue until I can gather more useful information.
