### ISSUE TITLE
import module path autocomplete doesn't work for AMD modules

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#12689]
despite #12165

**Comment by aozgaa** [comment]
Using the attached example ([amd.zip](https://github.com/Microsoft/TypeScript/files/772073/amd.zip)), I got semantic autocompletes in the relative import statement by pressing ctrl+space in vscode after the '/' in the import statement. For readability, I include the source below:

``` ts
// tsconfig.json
{
    "compilerOptions": {
        "module": "amd"
    },
    "exclude": [
        "node_modules"
    ]
}

// export.ts
export = {
    x: 1,
    y: "asdf"
};

// import.ts
import ex = require('./');

```

Perhaps we should trigger autocomplete when the user types `/`, which I didn't observe.

Can you clarify if this was the problem or something else?

**Comment by aleksey-bykov** [comment]
looks like it works now, thanks
