### ISSUE TITLE
tsserver: completion for union type of literal and string is broken from 2.1

### ISSUE THREAD

**Issue by wonderful-panda** [Microsoft/TypeScript#12687]
**TypeScript Version:**  2.1.1

**Code**

```ts
type Test = "foo" | "bar" | string;
const x: Test = "/* CURSOR POSITION */";
```

**Expected behavior:**
tsserver returns "foo" and "bar" as completion candidates.

**Actual behavior:**
2.0.10 behaves as expected.
2.1.1 returns no candidates.

**Comment by andy-ms** [comment]
The type `"foo" | "bar" | string` is equivalent to the `string` type and now gets simplified early on. So that's all we see when querying the type checker for the type of `x`. So, this can't be fixed.

**Comment by czb** [comment]
@andy-ms combobox is equivalent to input text field? Why do people use comboboxes then? This is what happens when math purity gets precedence to usability...
