### ISSUE TITLE
Check typeof operator result 

### ISSUE THREAD

**Issue by mohsen1** [Microsoft/TypeScript#12697]
Throw a compiler error if `typeof` operator is compared to strings other than [`typeof` operator results](http://www.ecma-international.org/ecma-262/6.0/#sec-typeof-operator-runtime-semantics-evaluation)

**TypeScript Version:**  2.1.1 

**Code**

```ts
typeof a === 'String' // error
typeof b === 'null' // error
```

**Comment by mhegazy** [comment]
I am sure we talked about this before. The issues is this section:

> Implementation-defined. Must not be "undefined", "boolean", "function", "number", "symbol", or "string".

It is allowed for engines to return some value outside this range. if you are using one of these engines, your code will be flagged as an error and you will need to cast to `any`.

**Comment by mohsen1** [comment]
Can it be a compiler flag then? Similar to `noUnusedLocals`

**Comment by mhegazy** [comment]
:D well, everything can be done under a flag. but we are getting strong feedback from customers that the number of flags is getting to be overwhelming, and they are having trouble what they need to set. So we would like to stay away from flags when possible.

**Comment by mohsen1** [comment]
That's fair.
 
Is there any engine in the wild that actually produce something outside of spec for `typeof` results?

**Comment by mhegazy** [comment]
Not that I know of. That is why I want to bring this back to discussion. I would expect this to catch more errors than block valid scenarios.

**Comment by yortus** [comment]
@mhegazy the previous discussion about this is in #9506 and #10594.

**Comment by aluanhaddad** [comment]
@mhegazy With respect to the increasing number of flags, TypeScript is still simpler to configure than a lot of other tools, but regardless it certainly could be simpler than it is. Perhaps a notion of "presets", should be  introduced. Perhaps this could also be work well with the new configuration inheritance support (I'm not sure, might obscure things).

I am thinking something like.
```
presets = Node | NodeLoose | AMD | AMDLoose | ...
```
where the non-loose variants would be `strict` defaults that contained
```json
{
  "compilerOptions":  {
    "strictNullChecks": true,
    "noImplicitThis": true,
    "noImplicitAny": true,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "noUnusedLocals": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitReturns": true,
    "allowUnusedLabels": false
  }
}
```

**Comment by mhegazy** [comment]
thanks @yortus for the link. looks like this was already discussed in details in https://github.com/Microsoft/TypeScript/issues/10594, the recommendation is to use a tslint rule.
