### ISSUE TITLE
With Two Path Variables for TSC And NPM Path Listed First, An Error Is Thrown

### ISSUE THREAD

**Issue by MarkPhillips** [Microsoft/TypeScript#12696]
**TypeScript Version:**  2.0.10

**Code**
`C:\PluralSight\TypeScript\TypeScriptInDepth\LibraryManager>tsc --t ES5 --outDir js --m commonjs --

**Expected behavior:**
TypeScript Compilation

**Actual behavior:**
Both Visual Studio, VSCode and Node are installed on the pc.  tsc command from VSCode is being used. Two Environmental Variables for tsc are set.  The Node variable was created after following a Typescript Issue posting on --watch.  With or without --watch the command throws an error listed in graphic below. (800A138F)

![watcherror](https://cloud.githubusercontent.com/assets/4471426/20946615/75c76dd2-bbd9-11e6-84f5-cf82ef831a12.PNG)

![environmentalvariables](https://cloud.githubusercontent.com/assets/4471426/20946653/955fee26-bbd9-11e6-829e-7b29a792ee6b.PNG)

**Comment by mhegazy** [comment]
this is running the JS (`tsc.js`) file in CScript.  i am guessing what you want is `tsc.exe`. so either remove the node location from the path, or type `tsc.exe` when you want to use the compiler from the commandline.

**Comment by MarkPhillips** [comment]
Thanks for the quick response.

I probably wasn't clear enough in regards to what I'm trying to do.

Removing the npm PATH entry or changing the npm PATH to point to the node_modules\typescript**\bin\** permits the compile.  

But in either case, when adding --watch to the command line, this error message is returned:
`_error TS5001: The current host does not support the '--watch' option._`

I have VSCode,Visual Studio 2013 and 2015 installed on my laptop. I found Issue #2375 which suggested using  2 tsc PATH entries.  But unfortunately, this doesn't work.  The same error is thrown.

**_Issue:  Implement '--watch' for tsc.exe #2375** 
A comment by DanielRosenwasser indicated that the solution is:
_No, if you're going to use node, we'd recommend you install TypeScript via npm and make sure that node's tsc comes before Visual Studio's tsc in your PATH._

Maybe, currently,  the only way to watch the .ts files is to resort to a task runner like gulp.
