### ISSUE TITLE
tryReuseStructureFromOldProgram() compares roots in order

### ISSUE THREAD

**Issue by ml054** [microsoft/TypeScript#12706]
**TypeScript Version:**  2.0.10

I'm using gulp-typescript for compile and watch tasks. During watch program structure can not be reused almost every time. 

The reason is files listed by gulp.src comes to stream in non-deterministic order (folders order is shuffled). 
As result gulp-typescript passes files in non-deterministic order to typescript compiler. 

tryReuseStructureFromOldProgram returns false because in

https://github.com/Microsoft/TypeScript/blob/9945529875ec5346686d92ac5b4fca69f04b73ff/src/compiler/program.ts#L604
 
we compare arrays not sets. 

Solution for my issue is to use plugins like: gulp-natural-sort which put input files in deterministic order. Wouldn't be better if typescript compiler compare new roots and old roots as sets, not as arrays? Then someone not familiar with gulp.src behavior won't waste his time on createProgram over and over again during watch task?

**Comment by RyanCavanaugh** [comment]
File ordering matters for a variety of reasons; a program whose files are in a different order may be observably different in emit or typechecking. It's not safe to reuse a program whose files are in a different order.
