### ISSUE TITLE
function overload with matching union types 

### ISSUE THREAD

**Issue by npenin** [Microsoft/TypeScript#12701]
Hi,

I am trying to have a function having an overload (```injectWithName``` in the sample below). I have 2 issues on that:
- the code is not compiling with the sample below: the injectWithName does not accept ```a``` as a parameter, complaining about the type.
- I had to specify the generic type in the second overload even though I do not need it in the signature. Otherwise, I cannot return a in my injectWithName method.

**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.20161118)

**Code**

```ts
export type Injected = (instance?: any) => any;
export type Injectable<T> = () => T;

class A
{
    public inject<T>(a: Injectable<T> | Function)
    {
        return this.injectWithName(a['$inject'] || getParamNames(a), a);
    }

    public injectWithName<T>(toInject: string[], a: Injectable<T>): Injectable<T>
    public injectWithName<T>(toInject: string[], a: Function): Injected 
    {
        if(a.length==0)
            return <Injectable<T>>a;

        ...
    }
 } 
```

**Expected behavior:**
Compiling without any error
**Actual behavior:**
Argument of type 'Function | Injectable<T>' is not assignable to parameter of type 'Injectable<T>'.
  Type 'Function' is not assignable to type 'Injectable<T>'.
    Type 'Function' provides no match for the signature '(): T'

**Comment by aluanhaddad** [comment]
This is because, when a function or method is overloaded, the implementation signature is not considered an overload.

you need to write:
```ts
public injectWithName<T>(toInject: string[], a: Injectable<T>): Injectable<T>;
public injectWithName(toInject: string[], a: Function): Injected;
public injectWithName<T>(toInject: string[], a: Function | Injectable<T>) {
  if(a.length==0)
    return a;
}
```
but consider writing 
```

**Comment by npenin** [comment]
ok, it worked. Thanks
