### ISSUE TITLE
Lift Template Literal Restriction on Backslashes

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#12700]
# Overview

Everyone loves L<sup>A</sup>T<sub>E</sub>X so ESNext will likely allow tagged template strings to contain backslashes on any sequence - even ones that look like they might contain an invalid Unicode escapes.

In other words, something like

```ts
let x = tag `\u{wat}`;
```

is now valid, whereas previously it would be considered an error.

Reference: https://tc39.github.io/proposal-template-literal-revision/

As of this writing, the linked proposal is at Stage 3.

# Notes

1. This restriction lift doesn't apply to *untagged* template strings. For example:

   ```ts
   // All of these are still invalid.
   let bad = `bad escape sequence: \unicode`;
   let bracingOurselves = `\u{shouldntDoThis}`;
   let theWorst = `\xtremely bad`;
   ```

2. Because there is no appropriate representation for a "cooked" string that contains one of these escapes, the returned value at a position on the top-level array will be `undefined`, but the raw representation will be available. For example:

   ```ts
   function tag(strs) {
     console.log(strs[0] === undefined);
     console.log(strs.raw[0] === "\\unicode and \\u{55}");
   }
  // Prints 'true' twice.
   tag`\unicode and \u{55}`

# Proposed Emit

Input:

```ts
let x = tag `\u{hello} ${ 100 } \xtraordinary ${ 200 } wonderful ${ 300 } \uworld`;
```

Output:

```js
var x = (
    _a = [undefined, undefined, " wonderful ", undefined],
    _a.raw = ["\\u{hello} ", " \\xtraordinary ", " wonderful ", " \\uworld"],
    tag(_a, 100, 200, 300)
);
```

**Comment by clavecoder** [comment]
This was bumped to stage 4 in 2017-03. It is slated for inclusion in ES2018

https://github.com/tc39/proposals/blob/master/finished-proposals.md

**Comment by Kingwl** [comment]
Interested in this😉

**Comment by DanielRosenwasser** [comment]
@Kingwl In implementing it, or using it?

**Comment by Kingwl** [comment]
related #5291 
should we re-implement EscapeSequence in the scanner ?

**Comment by DanielRosenwasser** [comment]
> should we re-implement EscapeSequence in the scanner ?

I don't know why that'd be necessary, I think you just need to potentially thread through some extra context when you're scanning these things (which is what the ECMAScript spec does in the grammar now). But I might've missed something, so feel free to send the PR and we can iterate on it!

**Comment by Kingwl** [comment]
Should the new grammar be always used or what options are needed? 
more than 90 baseline changed

**Comment by Kingwl** [comment]
@JakeGinnivan

> We have just hit this issue upgrading from 2.4.1 to 2.6.1.
> 
> glamorous.h3({
>     '&::after': {
>         content: `"\\00BB"`
>     }
> })
> Before it output chevrons, after the upgrade it output x000BB.

seems could fixed in this change

**Comment by DanielRosenwasser** [comment]
I think you'll have to actually add a rescan method on the scanner (e.g. `rescanTaggedTemplateHead` or something).

**Comment by Kingwl** [comment]
ahhh, `reScan` is work,  but the error which first time scan are still emitted,
how could i disabled the incorrect error
