### ISSUE TITLE
Should strictNullChecks be applicable with Observable filter operator?

### ISSUE THREAD

**Issue by goldenbearkin** [Microsoft/TypeScript#12702]
**TypeScript Version:**  2.0.10

```json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "strictNullChecks": true,
        "noImplicitAny": false,
        "sourceMap": false
    }
}
```

**Code**

```ts
const mixed = [1, 'one', null, undefined];

const $ = Observable.of(...mixed)
            .filter(x => x !== null)
            .filter(x => x !== undefined)
            .filter(x => typeof x !== 'string');

$.subscribe(x => console.log(x));  //  1
```

**Expected behavior:**
$ is in type (number)

**Actual behavior:**
$ is in type (string | number | null | undefined)

**Comment by HerringtonDarkholme** [comment]
Related: https://github.com/Microsoft/TypeScript/issues/9998#issuecomment-236446974

**Comment by mhegazy** [comment]
there is not a way to represent this transformation to the type system. an option would be something like https://github.com/Microsoft/TypeScript/issues/12424

**Comment by goldenbearkin** [comment]
@mhegazy Could you please explain a little bit more? I still can't get my head around after looking at #12424...
