### ISSUE TITLE
Edge F12 Developer Tools debuging a .ts file has incorrect syntax highlighting

### ISSUE THREAD

**Issue by wstaelens** [Microsoft/TypeScript#12704]
**TypeScript Version:**  2.x 
Microsoft Edge 38.14393.0.0
Microsoft EdgeHTML 14.14393

**Code**

```ts
 export function zeroFill(number: number, width: number): string {
        if (number !== null || number !== undefined) {
            width -= number.toString().length;
     }
 // ...
}
```

![edge f12 syntax highlighting wrong](https://cloud.githubusercontent.com/assets/7447285/20962470/b7aa80c8-bc69-11e6-8ed5-f29b7bab79b9.PNG)

**Expected behavior:**
number variable should be highlighted as a variable, not as a keyword.

**Actual behavior:**
Syntax Highlighting shows variable number (number: number) in incorrect color in Edge F12 Developer Tools.

**Comment by mhegazy** [comment]
following up with the F12 team about this.

**Comment by auchenberg** [comment]
Hi @wstaelens 

I have added this to our backlog for Edge DevTools. I can't promise when we'll do it, but it's now on our radar to have better TypeScript support.

/k

**Comment by wstaelens** [comment]
Thanks!

**Comment by wstaelens** [comment]
Fixed?

**Comment by mhegazy** [comment]
> Fixed?

There is no action item to follow up on for the typescript compiler or language. this is why the issue is closed. if @auchenberg has a public issue tracker they can point  you to the issue.

**Comment by auchenberg** [comment]
The issue has been filed in our internal tracker for Edge DevTools, so I'm afraid I can't give you a public link to track. @wstaelens @mariusschulz
