### ISSUE TITLE
Object destructoring using rest properties throwing TS1180 and TS2459

### ISSUE THREAD

**Issue by StrikeForceZero** [Microsoft/TypeScript#12710]
**TypeScript Version:**  2.1.1

Forgive me if this is a duplicate but can't seem to find any existing issues on this specific case with all the different terms `rest`, `spread`, `destructuring` polluting the search. Especially anything referencing 2.1 where support was first added.

**Code**
```ts
let obj = { x: 1, y: 1, z: 1 };
let { z, ...obj1 } = obj;
```

**Expected behavior:**

As described in the [What's New in 2.1 - Object Spread and Rest](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#object-spread-and-rest)

obj expected to be destructured into 2 variables:
- z = 1
- obj1 = { x: 1, y: 1 }

**Actual behavior:**

`...` throws `TS1180:Property destructuring pattern expected.`
`obj1` throws `TS2459:Type '{ x: number; y: number; z: number; }' has no property 'obj1' and no string index `

**Comment by mhegazy** [comment]
You need `typescript@2.1.4` for this to work (`typescript@2.1.1` is not the latest).

```sh
c:\test>type a.ts
let obj = { x: 1, y: 1, z: 1 };
let { z, ...obj1 } = obj;

obj1.x + obj1.y

c:\test>tsc --v
Version 2.1.4

c:\test>tsc a.ts

c:\test>echo %ERRORLEVEL%
0
```

**Comment by StrikeForceZero** [comment]
Ah, did not realize there was a 2.1.4
Working now, thanks.
