### ISSUE TITLE
TS2.1 breaks extended class, gives runtime error

### ISSUE THREAD

**Issue by bcherny** [Microsoft/TypeScript#12719]
TS code:

```ts
abstract class Collection<A> extends Array<A> {
  constructor() {
    super()
    this.initialize()
  }
  protected initialize() { }
}

abstract class CachedCollection<A> extends Collection<A> {
  constructor() {
    super()
  }
}

class EntityCollection extends CachedCollection<Entity> {}

new EntityCollection // throws
```

TS 2.0 compiles this to: https://jsfiddle.net/bcherny/d2w5qjrf/
TS 2.1 compiles this to: https://jsfiddle.net/bcherny/m9x8rz2z/1/

**Comment by wallverb** [comment]
FYI https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#extending-built-ins-like-error-array-and-map-may-no-longer-work

**Comment by bcherny** [comment]
Yup, that's it. Thanks @wallverb.

**Comment by bcherny** [comment]
Actually, this
