### ISSUE TITLE
🚨 2.1 contains breaking change in getElementsByTagName()

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/TypeScript#12718]
**TypeScript Version:**  2.1.4

When using the XMLParser API to parse an XML document as I do in vscode-php-debug, I will get a result document of the standard type `XMLDocument`. This document has a property `documentElement` (which is typed `HTMLElement`), which has a method `getElementsByTagName`. This method takes an element name (which can be any element name) and returns a `NodeList` of `Node` subclasses.

Before 2.1, you could pass any XML tag name like `engine` (used in DBGp) to `getElementsByTagName` and the return value would be at least a `NodeList`, which would allow you to at least call standard `Node` methods on the items like `getAttribute()`.

In 2.1, the signature was changed to this:

```ts
getElementsByTagName<K extends keyof ElementListTagNameMap>(name: K): ElementListTagNameMap[K];
```

which means the element name must now be one of predefined element names. If the element name is _not_ know (a key in `ElementListTagNameMap`), the return value will be inferred as `{}`, and the following code will now fail with the error `[ts] Property 'getAttribute' does not exist on type '{}'`:

```ts
document.documentElement.getElementsByTagName('engine')[0].getAttribute('version')
```

This broke the build in vscode-php-debug in a minor update and prevents any `getElementsByTagName` calls with custom XML tags or Angular components.

Failing PR: https://github.com/felixfbecker/vscode-php-debug/pull/112
Reference file with a lot of these errors: https://github.com/felixfbecker/vscode-php-debug/blob/master/src/xdebugConnection.ts

**Comment by mhegazy** [comment]
@felixfbecker i am nto getting this error locally.. `getElementsByTagName` should have another overload for string as well (`getElementsByTagName(tagname: string): NodeListOf<Element>;`).

when i compile on your repro i get two unrelated errors:

```sh
c:\test\12718\vscode-php-debug>git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean

c:\test\12718\vscode-php-debug>git remote -v
origin  https://github.com/felixfbecker/vscode-php-debug.git (fetch)
origin  https://github.com/felixfbecker/vscode-php-debug.git (push)

c:\test\12718\vscode-php-debug>tsc --v
Version 2.1.4

c:\test\12718\vscode-php-debug>tsc
src/xdebugConnection.ts(65,48): error TS2531: Object is possibly 'null'.
src/xdebugConnection.ts(481,36): error TS2531: Object is possibly 'null'.
```

**Comment by felixfbecker** [comment]
@mhegazy After a VS Code reload the error is gone. I will open a separate issue for the other errors.
