### ISSUE TITLE
Breaking changes in 2.1.4 with NG2.1

### ISSUE THREAD

**Issue by brachi-wernick** [Microsoft/TypeScript#12727]
**TypeScript Version:**  2.1.4 with ng 2.1.x

**Code1 failed:**
```ts
    private _value:string;
  
  set value(value: string) {
            this._value = value;
      }

@Input()
   get value() {
        return this._value;
    }
```

**Code2 failed:**
```ts
    private _value:string;

  get value() {
        return this._value;
    }

  @Input()
    set value(value: string) {
            this._value = value;
      }
```

**Expected behavior:**
should work as before upgrade, I can use the value as input in html.
@input can be above a get method or above a set method. and get/set method can appear in the class in each place.

**Actual behavior:**
get an error: `Can't bind to 'value' since it isn't a known property of 'some-componnet'.`
@input must be in the get method, but get method must appears before the set method.

this code works: but for me it is workaround:

**Code1 failed:**
```ts
    private _value:string;
//I change order of the get to be before the set
@Input()
   get value() {
        return this._value;
    }

    set value(value: string) {
            this._value = value;
      }


```

**Code2 failed:**
```ts
    private _value:string;
//I remove annotation from the set method and put above the get
@Input()
   get value() {
        return this._value;
    }

  
    set value(value: string) {
            this._value = value;
      }


```

**Comment by mhegazy** [comment]
@brachi-wernick can you share more context? i can not piece together a self-contained repro using your snippets.

**Comment by rbuckton** [comment]
@mhegazy Here's a simple repro:

```ts
declare var Input: any;

class A {
    @Input() set value(value: string) { } // works
    get value() { return ""; }
}

class B {
    set value(value: string) { }
    @Input() get value() { return ""; } // does not work
}
```

It looks like decorators on the second declaration are not emitted.

**Comment by mhegazy** [comment]
@brachi-wernick the fix should be in `typescript@next` later tonight. please give it a try and let us know if you are still running into issues.

**Comment by brachi-wernick** [comment]
@mhegazy I checked the @latest in that is what I found:
```
declare var Input: any;

class A {
    set value(value: string) { }
    @Input() get value() { return ""; } // fixed, works now
}

class B { 
   get value() { return ""; } // still doesn't work
   @Input() set value(value: string) { }
}
``

**Comment by aluanhaddad** [comment]
> the fix should be in typescript@next later tonight.

@mhegazy It is working for me with typescript@2.2.0-dev.20161208

@brachi-wernick `@latest` is the latest _release_.

**Comment by aluanhaddad** [comment]
Something interesting is that I get an empty array for the `design:paramtypes` key when the getter is decorated, but a singleton array if the setter is. In 2.0.8, there is no emit for that key. Is this a new feature? Just curious.

**Comment by rbuckton** [comment]
@aluanhaddad As getters cannot have parameters, the `design:paramtypes` metadata should always be for the setter, if it has one. It looks like this is a bug in 2.0.8 and in 2.1.
