### ISSUE TITLE
Cannot use `===` with Enum Literal Type

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#12729]
From https://github.com/Microsoft/vscode/issues/16819

**TypeScript Version:**  2.1.4-insiders.20161206

**Code**

```ts
enum State {
	INVALID = 0,
	FIRST = 1
}

const invalid = State.INVALID;
invalid === State.FIRST
```

**Expected behavior:**
No error since `invalid` is a subtype of `State.INVALID`

**Actual behavior:**
Error:

```
Operator '===' cannot be applied to types 'State.INVALID' and 'State.FIRST'.
```

This also does not work:

```ts
const invalid: State = State.INVALID;
invalid === State.FIRST
```

You have to be explicit: 

```ts
const invalid = State.INVALID as State;
invalid === State.FIRST
```

or 

```ts
const invalid = State.INVALID;
invalid as State === State.FIRST
```

**Comment by mhegazy** [comment]
This is an intentional breaking change. the compiler can verify that `invalid` can not have any other values. You can find more information at https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#literal-types-are-inferred-by-default-for-const-variables-and-readonly-properties

**Comment by mjbvz** [comment]
Ok, thanks. The actual control flow on the VSCode side was more complicated (https://github.com/Microsoft/vscode/pull/16861/files) so I opted to just add the explicit cast. I strongly suspect the compiler is correct in this case too, but wasn't 100% sure
