### ISSUE TITLE
Add PaymentRequest spec to lib.*.d.ts

### ISSUE THREAD

**Issue by paulvanbrenk** [Microsoft/TypeScript#12736]
As a workaround the definitions for the [PaymentRequest spec ](https://www.w3.org/TR/payment-request/)are added to definetly typed, but they should be added to lib.*.d.ts when Edge finishes it's implementation.

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/12461

**Comment by paulvanbrenk** [comment]
Looks like Edge has come a long way implementing this.

https://blogs.windows.com/msedgedev/2016/12/15/payment-request-api-edge/

**Comment by mhegazy** [comment]
@zhengbli do we get these with the latest update?

**Comment by mohsen1** [comment]
I `PaymentRequest` in dom.d.ts of 2.2

**Comment by mhegazy** [comment]
indeed. thanks.
