### ISSUE TITLE
Type 'typeof SomeClass' cannot be assigned to type 'SomeInterface'. Property 'someProperty' is missing in type 'typeof SomeClass'

### ISSUE THREAD

**Issue by layton-glympse** [Microsoft/TypeScript#12738]
Note: this occurs in Intellij's intellisense. I'm seeing the code actually compile. I am unsure if this is a Typescript problem or an Intellij problem so sorry in advance if I'm confused.

**TypeScript Version:**  2.0.6

**Code**

SomeInterface.ts:
```
export interface SomeInterface {
    someProperty:any;
}
```

SomeService.ts:
```
import {SomeInterface, SomeClass} from '.....';

export class SomeService {

    constructor() {
        //.....
    }

    doSomething() {
        return this.doSomethingElse(SomeClass);
    }

    doSomethingElse(component: SomeInterface) {
        //.....
    }
}
```

In this case, `SomeService` has a method `doSomethingElse` that takes an argument that merely needs to satisfy the interface `someInterface`.

SomeClass.ts
```
import {SomeInterface} from '.....';

export class SomeClass implements SomeInterface {
    someProperty: //....defined!
}
```

Instead of this working, I get the intellisense error `Type 'typeof SomeClass' cannot be assigned to type 'SomeInterface'. Property 'someProperty' is missing in type 'typeof SomeClass'`, yet it still compiles.

I'm not super well-learned on the inner workings of Typescript, and it may be that this has to do with `SomeClass` here being a `Type`. However, the thing that I find strange is that `SomeClass` _does indeed_ implement `someProperty`, and one would think this error would not be thrown.

Replacing the invocation types to `<any>SomeClass` works fine, FWIW, but that's not a surprise since <any> types effectively disable type checking. Also, passing in `<any>` typehinted object types basically eliminates the point of using interfaces in this case.

**Expected behavior:**
No error messages/intellisense issues.

**Comment by mhegazy** [comment]
Intellij uses its own system to understand TS and drive intellisense. I do not have much insight into their system to be able to help here. From the snippet above, it looks like valid code to me, and since it is compiling on the comandline, i suggest filing this on https://youtrack.jetbrains.com/issues/IDEA instead.

**Comment by layton-glympse** [comment]
Oop! Never mind. I believe that this:

```
    doSomethingElse(component: SomeInterface) {
        //.....
    }
```

Should actually be this:

```
    doSomethingElse(component: Type<SomeInterface>) {
        //.....
    }
```

Is that correct? Will this still enforce the `SomeInterface` semantic? I tried it and my editor and the error went away.

**Comment by mhegazy** [comment]
depends on how `SomeInterface` and `Type` are defined.

**Comment by layton-glympse** [comment]
Ahhhh Type is a product of the implementation? I didn't realize it wasn't an Angular 2 construct. My bad. I understand now, thank you.
