### ISSUE TITLE
Constructor scoped variables are available to member initialization code, but compile error thrown

### ISSUE THREAD

**Issue by DrSammyD** [Microsoft/TypeScript#12742]
This code
```ts
class Outer{
	private constructorScopedFunc = () => alert(i)
	constructor(i:number) {
		this.constructorScopedFunc();
	}
}
new Outer(5);
```
Outputs this code
```js
var Outer = (function () {
    function Outer(i) {
        this.constructorScopedFunc = function () { return alert(i); };
        this.constructorScopedFunc();
    }
    return Outer;
}());
new Outer(5);
```
The compiler throws an error even though the JavaScript works as intended. Is there a reason for not allowing constructor scoped variables to be accessed by member initialization code?

I can see the argument that this would require the ability to create variables outside of the constructor space because deciding on order of operations could be a problem.

My assumption is that you think this
```ts
class Outer{
	private constructorScopedFunc = () => alert(y);
	var y = i + 1;
	constructor(i:number) {
                i++;
		this.constructorScopedFunc();
	}
}
new Outer(5);
```
is the final outcome of going down a road with variables outside the constructor, where the constructor is redundant/ what order things are executed isn't in line with how the code is ordered.

I would however argue, functionally, that already is the case.
```ts
class Outer{
	private constructorScopedFunc = () => alert(this.y);
	private y = this.i + 1;
	constructor(private i: number) {
		i++;
		this.constructorScopedFunc();
	}
}
new Outer(5);
```
which outputs
```js
var Outer = (function () {
    function Outer(i) {
        var _this = this;
        this.i = i;
        this.constructorScopedFunc = function () { return alert(_this.y); };
        this.y = this.i + 1;
        i++;
        this.constructorScopedFunc();
    }
    return Outer;
}());
new Outer(5);
```
The compiler already decided to set `_this` and `this.i`, set `this.y`, and then finally increment `i++` You could do the same for scoped vars.

The only difference is you've forced the coder to put everything on the class instance instead of having a locally scoped variable available to non prototype member functions. So why intentionally cut of the scoping of variables for a classes instance members? Is it because it's not obvious that the variables aren't available to prototype member functions? I'm pretty sure the linters could say "this variable is locally scoped and only available to initialization code".

**Comment by mhegazy** [comment]
TypeScript is a super set of JavaScript. that means that the transpiled code should have the same semantics if run on a JS engine supporting the feature.

The proposal for the [ES property](https://tc39.github.io/proposal-class-public-fields/#runtime-semantics-class-definition-evaluation) declarations stipulates that the initializer are run outside the scope of the constructor. so if you were running this on a native JS engine supporting this proposal `i` would be undefined at run-time.

the compiler could emulate the same semantics by renaming `i` to `_i` to avoid the collision with the constructor parameter `i` instead of showing the error, but i take that this is not what you intend.

**Comment by DrSammyD** [comment]
Gotcha. Thanks for the clarification! That makes sense. 

If [This Proposal](https://github.com/tc39/proposal-private-fields/issues/53) gets passed, you may want to think about implementing it in the above manner for backward support.
