### ISSUE TITLE
HTMLTableElement Functions return wrong types (insertRow, insertCell)

### ISSUE THREAD

**Issue by EricLambrecht** [Microsoft/TypeScript#1274]
~~insertRow(index?: number): HTMLElement;~~
insertRow(index?: number): **HTMLTableRowElement** ;
~~insertCell(index?: number): HTMLElement;~~
insertCell(index?: number): **HTMLTableCellElement**;

also HTMLTableElement.rows is not a collection of HTMLTableRowElements!?

Am I mistaken here?

**Comment by mhegazy** [comment]
duplicate of #3583, and should be fixed in https://github.com/Microsoft/TypeScript/pull/5836
