### ISSUE TITLE
Object spread and this: spread types may only be created from object types

### ISSUE THREAD

**Issue by sanex3339** [Microsoft/TypeScript#12756]
**TypeScript Version:**  2.1.4

**Code**

[example](https://www.typescriptlang.org/play/#src=interface%20IOptions%20%7B%0D%0A%20%20%20%20option1%3A%20string%3B%0D%0A%20%20%20%20option2%3A%20string%3B%0D%0A%20%20%20%20option3%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Aconst%20DEFAULT_OPTIONS_PRESET%3A%20IOptions%20%3D%20%7B%0D%0A%20%20%20%20option1%3A%20'string1'%2C%0D%0A%20%20%20%20option2%3A%20'string2'%2C%0D%0A%20%20%20%20option3%3A%20'string3'%0D%0A%7D%3B%0D%0A%0D%0Aclass%20Options%20implements%20IOptions%20%7B%0D%0A%20%20%20%20public%20readonly%20option1%3A%20string%3B%0D%0A%20%20%20%20public%20readonly%20option2%3A%20string%3B%0D%0A%20%20%20%20public%20readonly%20option3%3A%20string%3B%0D%0A%0D%0A%20%20%20%20constructor%20(inputOptions%3A%20IOptions)%20%7B%0D%0A%20%20%20%20%20%20%20%20this%20%3D%20%7B%20%2F%2F%20The%20left-hand%20side%20of%20an%20assignment%20expression%20must%20be%20a%20variable%20or%20a%20property%20access.%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20...this%2C%20%2F%2F%20spread%20types%20may%20only%20be%20created%20from%20object%20types%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20...DEFAULT_OPTIONS_PRESET%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20...inputOptions%20%0D%0A%20%20%20%20%20%20%20%20%7D%3B%0D%0A%20%20%20%20%7D%0D%0A%7D)

```ts
interface IOptions {
    option1: string;
    option2: string;
    option3: string;
}

const DEFAULT_OPTIONS_PRESET: IOptions = {
    option1: 'string1',
    option2: 'string2',
    option3: 'string3'
};

class Options implements IOptions {
    public readonly option1: string;
    public readonly option2: string;
    public readonly option3: string;

    constructor (inputOptions: IOptions) {
        this = { // The left-hand side of an assignment expression must be a variable or a property access.
            ...this, // spread types may only be created from object types
            ...DEFAULT_OPTIONS_PRESET,
            ...inputOptions 
        };

        const errors = OptionsValidator.validate(this);

        if (errors.length) {  // ...  }

        this = { // The left-hand side of an assignment expression must be a variable or a property access.
            ...this,  // spread types may only be created from object types
            ...OptionsNormalizer.normalize(this)
        };
    }
}

```

**Expected behavior:**
No errors?
With object assign code works well
```ts
constructor (inputOptions: IOptions) {
    Object.assign(this, DEFAULT_OPTIONS_PRESET, inputOptions);
}
```

**Actual behavior:**
Two errors:
`The left-hand side of an assignment expression must be a variable or a property access. `
`Spread types may only be created from object types.`

If it's a a correct behaviour please explain me it.

**Comment by timocov** [comment]
Are you sure that code with `Object.assign` is the same as in your code?
I guess no, because you rewrite `this` ref to "new" object (but it is the same as `this`, yeah).

**Comment by mhegazy** [comment]
`this` is a generic type. it refers to the type of the instance type of the class that will be new'ed later on.  this could be your class `Options` or any decedent of it later on. 
spread and rest are not supported on generics at the moment. this is tracked by https://github.com/Microsoft/TypeScript/issues/10727

**Comment by sanex3339** [comment]
Ok thank you for explanation, i will close this issue
