### ISSUE TITLE
Object spread and generic

### ISSUE THREAD

**Issue by PavelPZ** [Microsoft/TypeScript#12759]
**TypeScript Version**: 2.1.4

**Code**
```
function spread<T extend Object>(arg: T): any {
  return { ...arg }; //syntax error: "Spread types may only be created from object types"
}
```
**Expected behavior:**
No error

**Actual behavior:**
"Spread types may only be created from object types" syntax error

**Comment by mhegazy** [comment]
This is covered by https://github.com/Microsoft/TypeScript/issues/10727.
