### ISSUE TITLE
const being transpiled to var even when output is set to ES6

### ISSUE THREAD

**Issue by TheAnimus** [Microsoft/TypeScript#12752]
**TypeScript Version:**  2.0.10

**'target' flag:**  ES6

**TS Code**

```ts
const foo = "bar";

```

**Expected behavior:**
```js
const foo = "bar";

```
**Actual behavior:**
```js
var foo = "bar";

```

We're in the progress of porting an existing codebase to use TypeScript, it's currently a fairly standard-ish webpack react, babel set up, but we use es-lint with strict rules about proper const or let use.  Whilst I can exclude the TS compiled JS files from being linted, it would be better I think to have TS preserve the programmer's intent when the output is ES6.

The same behaviour is also happening with 'let'.

**Comment by aluanhaddad** [comment]
I can't reproduce this. The only way to get close is with `export const` and `--module system`, but that is by design.

**Comment by TheAnimus** [comment]
I'm currently able to produce it with this config file.

```js
    "compilerOptions": {
        "sourceMap": true,
        "module": "es6",
        "moduleResolution": "node",
        "target": "es6",
        "pretty": true,
        "traceResolution": true,
        "jsx": "preserve"
    }

**Comment by TheAnimus** [comment]
Oh hamburgers!

This was actually made by Visual Studio (not VS Code) touching the file, ignorant of the typescript configuration, and making it's own output.

Sorry!

**Comment by abenhamdine** [comment]
Hmmm... With the same tsconfig.json, I have the same problem... And I don't even have Visual Studio on my  laptop.
