### ISSUE TITLE
Context colouring in TS/JS

### ISSUE THREAD

**Issue by prashaantt** [Microsoft/TypeScript#12765]
An exclusively context-coloured source code, as against being typically statically syntax-coloured, has its literals highlighted dynamically according to the lexical scope they are present in. [Here](http://mazurov.github.io/eslevels-demo/) is a great live example. Or you may try something much simpler (albeit buggy) that yet drives the point home on [this page](https://daniellamb.com/JavaScript-Scope-Context-Coloring/example/scope-coloring.html#level10):

```js
function f1(a) {
    return function f2(b) {
        return function f3(c) {
            return function f4(d) {
                return a + b + c + d; // a, b, c and d are all coloured differently
            }
        }
    }
}
```

This makes it very easy to be fully context-aware of the scope where each literal belongs while writing and reviewing a piece of code.

I believe it was Douglas Crockford who first proposed this concept ([here's a talk](https://www.youtube.com/watch?feature=player_embedded&v=dkZFtimgAcM#t=15m58s)). Here are a few discussions/demos/implementations of this idea:

- https://plus.google.com/+PaulIrish/posts/XjR4WmSDFAV
- https://github.com/daniellmb/JavaScript-Scope-Context-Coloring
- http://mazurov.github.io/eslevels-demo/
- https://github.com/jacksonrayhamilton/context-coloring
- https://github.com/bigfish/vim-js-context-coloring

I don't know the mechanics of how this might work, but I presume that the `tsserver` being already aware of everything about my code can provide a much more performant and accurate context-colouring to TypeScript and JavaScript sources than these linters.

**Comment by mhegazy** [comment]
We rely on [textmate grammar](https://github.com/Microsoft/TypeScript-tmlanguage) for colorization. it fits the performance characteristics we would like in a colorization system. The TS API provides a syntactic classification service, see https://github.com/Microsoft/TypeScript/blob/6e3bbcc6fc0f5dbec2c93eeb684e94f690dc8644/lib/typescript.d.ts#L2467, you could use this to implement a plugin that achieves a similar behavior.

**Comment by prashaantt** [comment]
@mhegazy Thanks for the suggestion. I don't know the compiler API yet to do this myself, but it would be awesome if you could find ways to provide this service natively in the future with the performance characteristics you desire.

One way to begin with this might be as a read-only static view of the code, something I could flip into with the click of a button in my editor to quickly get a context-coloured view of how my code is structured, and then go back to edit the code in normal mode.
