### ISSUE TITLE
Using typeRoots will result in an error if subfolders exist

### ISSUE THREAD

**Issue by teetotum** [Microsoft/TypeScript#12767]
**TypeScript Version:**  2.0.3

My folder structure for my project:
```
[MyProject]
  -[TypeScript] # *.ts sourcecode goes here
  -[typings] # *.d.ts type-definitions here
    -[foo] # type-definition subfolder, might contain *.d.ts or might be empty, still causes observed error
      -[bar] # like foo
      -[baz] # like foo
```

TypeScript/myProgram.ts
```ts
greeter.greet();
```
typings/greeter.d.ts
```ts
interface IGreeter{
	greet();
}
declare var greeter: IGreeter;
```
My tsconfig.json
```
{
  "compilerOptions": {
    "module": "amd",
    "noImplicitAny": false,
    "noEmitOnError": true,
    "removeComments": false,
    "preserveConstEnums": true,
    "sourceMap": true,
    "target": "es5",
    "typeRoots": [ "typings" ],
    "rootDir": "TypeScript"
  },
  "exclude": [
    "node_modules",
    "wwwroot"
  ],
  "compileOnSave": false
}
```

**Expected behavior:**
Compile without errors

**Actual behavior:**
error TS2688: Cannot find type definition file for 'foo'

**Additional observations:**
I can fix the problem for me if I change the typeRoots option in tsconfig.json to `"typeRoots": [ "typings/**/*" ],`
That is ... unexpected. The name of the option "typeRoots" suggests that I only have to provide the names of root folders the compiler can (deep-)search for type-def files. Any subfolders should not pose a problem, whether they contain *.d.ts files or not.

**Comment by mhegazy** [comment]
that is how `typeRoots` is supposed to work. each subfolder under `typeRoots` is considered a "package" and is added to your project.

Globs are not supported in `typeRoots`. setting typeRoots to `"typings/**/*"` is just like setting it to a non-existing folder, it does nothing.

in your sample it does not seem you really need typeRoots. just remove it and add `types: []` instead to make sure non of your `node_modules\@types` are loaded by mistake.

see http://www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types for more details.
