### ISSUE TITLE
Switch on enum of one member not considered exhaustive

### ISSUE THREAD

**Issue by hmaurer** [Microsoft/TypeScript#12771]
**TypeScript Version:** 2.1.4

**Code:**

```
// --strictNullChecks

enum Enum1 {
    A,
    B
}

enum Enum2 {
    A
}


interface Foo {
    readonly kind: Enum1
}

interface Bar {
    readonly kind: Enum2
}

let f = (x: Foo): number => {
    switch (x.kind) {
        case Enum1.A:
            return 1;
        case Enum1.B:
            return 2;
    }
}

let g = (x: Bar): number => {
    switch (x.kind) {
        case Enum2.A:
            return 1;
    }
}
```

**Expected behaviour** (as far as I know):

Compiles without error

**Actual behaviour**: 

Function `g` does not compile, with error `TS2366: Function lacks ending return statement and return type does not include 'undefined'.`.

Without strict null checks, it compiles without error.

**Comment by MaklaCof** [comment]
Is it possible to get information where error occurred? Right now there is no file, line information about that.
_I just install fresh windows installation with VS2017RC and get this error. I would like to add default statement to switches (they already should be there, but apparently I miss one), but there are simply to many files to check it._

**Comment by amilner42** [comment]
I have a related issue also with **enums with one value**, you can directly copy this to the [microsoft typescript playground](https://www.typescriptlang.org/play/):

No error as expected for this snippet (2 values in enum)
```typescript
enum Rating {
  Like = 1,
  Dislike
};

let a: Rating;

switch (a) {
  case Rating.Like:
    break;

  case Rating.Dislike:
    break;

  default:
    let s: never = a;
}
```

On the other hand, drop it down to one value in the enum and you get the error:
 > Type 'Rating' is not assignable to type 'never'.
```typescript
enum Rating {
  Like = 1
};

let a: Rating;

switch (a) {
  case Rating.Like:
    break;

  default:
    let s: never = a; // error here
}

```

**Comment by mhegazy** [comment]
Examples in this issue seems to be working as expected in latest.
