### ISSUE TITLE
Target es6 produces different output than es2015

### ISSUE THREAD

**Issue by arciisine** [Microsoft/TypeScript#12774]
**TypeScript Version:**  2.1.4
**Environment:** Node 7.2
**Code**

```ts
// A *self-contained* demonstration of the problem follows...
function test() { return (a:any) => a; }
class Person {}

@test()
class OldPerson extends Person {}
console.log(Object.getPrototypeOf(OldPerson));
```

Compile with `experimentalDecorations` and `emitDecoratorMetadata` turned on, and target set to `es6`.

**Expected behavior:**
I should see `[Function: Person]`
**Actual behavior:**
What I do see is `[Function]`

It appears that `es6` is no longer a valid target, as this worked before with `es6`.

**Comment by arciisine** [comment]
Actually the above seems to happen regardless when using es5.  I'm still trying to pinpoint exactly what is happening in es6+

**Comment by arciisine** [comment]
Okay, further investigation, it looks like `es6` as a target has been deprecated or removed? It appears that passing `es6` is not equivalent to `es2015`.

**Comment by mhegazy** [comment]
do you have a sample i can look at?

**Comment by arciisine** [comment]
I fear it may be more complicated than I stated above.  A very simple `test.ts` and and `tsconfig.json` do not replicate the problem.  But in my project, toggling between `es6` and `es2015` changes the project from failing to building.  Let me see if I can produce a smaller test case.
