### ISSUE TITLE
Compiler incorrectly infers literal value for member variable

### ISSUE THREAD

**Issue by GuntherRademacher** [Microsoft/TypeScript#12779]
**TypeScript Version:**  2.1.4

**Code**
In the code below, the comparison `this.n == 1` is rejected, because apparently `this.n` is assumed to be `0`. This however does not take into account, that `this.inc()` changes its value. The problem does not occur when inlining that function call.
```ts
/// <reference path="node.d.ts"/>

class N {
  private n: number;

  constructor(n: number) {
    this.n = n; 
  }
  
  f(): number {
    if (this.n == 0) {
      this.inc();
      if (this.n == 1) {
        this.inc();
      }
    }
    return this.n;
  }

  private inc() {
    this.n++;
  }
}

process.stdout.write(String(new N(0).f()));

```

**Expected behavior:**
successful compilation
**Actual behavior:**
Error message: `N.ts(13,11): error TS2365: Operator '==' cannot be applied to types '0' and '1'`

**Comment by gcnew** [comment]
Side effects are evil 👻

**Comment by GuntherRademacher** [comment]
I see the point. But IMHO identifying potential bugs would justify a warning, at best, and only in case it wasn't disabled. It just does not feel right to me to see code being rejected, because a de-facto mutable field is considered immutable.

Of course I can add extra functions and calls, in my case to [REx parser generator](http://bottlecaps.de/rex/)'s TypeScript code generation. But it's somewhat dissatisfying to do that just to trick the compiler. And how are you going to explain TypeScript semantics, if partially-inlined code is treated differently than fully-inlined or non-inlined code?

So I am hoping that the ongoing protest, that can be seen in several posts here, will eventually cause that narrowing to be refined, or at least omitted in cases where it produces inaccurate results.
