### ISSUE TITLE
'occurrences' Returns occurrences inside strings

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#12780]
From https://github.com/Microsoft/vscode/issues/16909

**TypeScript Version:**  2.1.4 

**Code**

```ts
"fdsafdas";
"fdsafdas";
```

**Expected behavior:**
In TS 2.0.10, when calling tsserver 'occurrences' for any position inside `"fdsafdas"`, we get no results back.

**Actual behavior:**
In TS 2.1.4, we now get back occurrences of the string throughout the file.

**Comment by DanielRosenwasser** [comment]
Is there a reason that this is a problem @mjbvz?

**Comment by alexandrudima** [comment]
@DanielRosenwasser IMHO it makes vscode visually noisy for no good reason (i.e. does not help me in reading/understanding, nor in writing new source code if strings always get a highlight when I'm having a cursor on top of them).

**Comment by DanielRosenwasser** [comment]
This is sort of funny because I generally considered occurrence highlighting to be useful if I'm matching on a string literal value in some manner.. Do you find other occurrences highlighting to be useful?

**Comment by mjbvz** [comment]
For me, highlighting the entire string also seems unexpected to me and is different that what other languages in VSCode do. It's especially odd when dealing with longer strings that only have one occurrence .

To my knowledge, the current APIs do not allow us to properly filter out these new highlights on the VSCode side either.

**Comment by waderyan** [comment]
Here is a case I find the current behavior unsatisfactory. 

I want to select all divs, but I end up highlighting the entire string. 

```
var ele = "<div>Hello World</div>";
var ele2 = "<div>Hello Hogwarts</div>";
```

![highlightingissue](https://cloud.githubusercontent.com/assets/2449568/21069155/1661c2de-be2c-11e6-9329-de047cb06baf.gif)

**Comment by dbaeumer** [comment]
I also think that visually the current behavior is not nice and unexpected. However I can also understand that the TSServer doesn't want to be driven by visual appearance. What's about adding additional information to the `HighlightSpan` that lets VS Code know about the kind of the symbol highlighted. Then we can decide whether we want to drop the result or not.

**Comment by dbaeumer** [comment]
Actually since the value should always be the same it would make sense to send it only once (in the response and not for every 'HighlightSpan'.

**Comment by mhegazy** [comment]
so the request is to add a flag to `OccurrencesResponseItem` to say if this is a string literal or not?

**Comment by mjbvz** [comment]
@mhegazy Yes, we need some piece of data that tells us what type of occurrences are being provided. Right now we just need to differentiate between symbols and string literals, so a flag would be fine but we may also want to consider something more extensible.

**Comment by zhengbli** [comment]
This seems fixed in the latest VSCode & TS nightly (though I am not sure either VSCode or us fixed it).

**Comment by mhegazy** [comment]
What do you mean fixed?

**Comment by zhengbli** [comment]
![issue](https://cloud.githubusercontent.com/assets/1171301/22839491/7a2d1c22-ef7e-11e6-8cb6-55415abfae89.gif)

I do not see the strings highlighted anymore

**Comment by zhengbli** [comment]
Please reopen this issue if it still repros. Close for now.

**Comment by mjbvz** [comment]
We added a [workaround](https://github.com/Microsoft/vscode/blob/master/extensions/typescript/src/features/documentHighlightProvider.ts#L33) for this issue on the VSCode side. With TS 2.2.1-insiders, if I disable the workaround, I still see occurrences of strings being highlighted

Reopening this issue for further investigation

**Comment by zhengbli** [comment]
Revisiting this, I found this issue involves some subtlety. Consider this case:
```
type ThisIsType = "Hello";
let v: ThisIsType = "Hello";
``` 
If you rename any of the `"Hello"` location, you do see both "Hello" being changed. And there is one test case in our repo dedicated for this scenario at https://github.com/Microsoft/TypeScript/blob/master/tests/cases/fourslash/findAllRefsForStringLiteralTypes.ts

So it might be strange that find-all-refs / rename / occurrence hightlighting have inconsistent behavior. Pinging @mhegazy for opinions

**Comment by mhegazy** [comment]
We need the occurrences to return a marker that they are within a string literal. the IDE can then decide wither to show them or not. i do not think we need to change our search logic.

**Comment by zhengbli** [comment]
With #14677 now the occurrence items in strings will have a property called `isInString` set to `true`, so the editor can choose to show it or not.
