### ISSUE TITLE
Empty output when outDir starts with 'js'

### ISSUE THREAD

**Issue by sunify** [Microsoft/TypeScript#12787]
**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)

I trying to use `js` directory as outDir, but compiler do not create .js files in outDir that starts with `js` (also i try `jsbuild`, `js/build` etc).

**Comment by mhegazy** [comment]
Something else is going on, please provide a self-contained sample, or steps to reproduce the issue.

here is what i see:

```sh
c:\test\12787>tree /F
C:.
    a.ts

c:\test\12787>tsc --v
Version 2.1.4

c:\test\12787>tsc a.ts --outDir js

c:\test\12787>tree /F
C:.
│   a.ts
│
└───js
        a.js
```

**Comment by sunify** [comment]
I´m sorry. This is VSCode issue — https://github.com/Microsoft/vscode/issues/17892
