### ISSUE TITLE
Cannot define a Partial<T> for a constrained T extends Base specifying only members of Base

### ISSUE THREAD

**Issue by pzavolinsky** [Microsoft/TypeScript#12799]
**TypeScript Version:**  2.1.4

**Code**
```ts
interface Base {
  page: number
}

function test<T extends Base>() {
    const firstPage:Partial<T> = { page: 1 };
}
```
Also reproducible [here](https://www.typescriptlang.org/play/index.html).

**Expected behavior:**
`firstPage` should be accepted as a valid partial instance of `T`.

**Actual behavior:**
> error TS2322: Type '{ page: 1; }' is not assignable to type 'Partial&lt;T&gt;'.

Also, the error is not very helpful explaining *why* the type is not assignable.

**Comment by pzavolinsky** [comment]
Related to #12731.

I believe this should be considered a *bug* rather than a suggestion (as the issue above).

**Comment by mhegazy** [comment]
Duplicate of #16356 and https://github.com/Microsoft/TypeScript/issues/19388

**Comment by mhegazy** [comment]
Use `Partial<Base>` instead.
