### ISSUE TITLE
strictNullChecks and arithmetic expressions

### ISSUE THREAD

**Issue by bobappleyard** [Microsoft/TypeScript#12795]
**TypeScript Version:**  2.1.4

With strictNullChecks on:

**Code**

```ts
    let y = undefined + 1;

```

**Expected behavior:**

An error telling me this is the wrong thing to do.

**Actual behavior:**

Compiles fine, y is a number.

This does the same thing for all the arithmetic operators.

**Comment by FranklinWhale** [comment]
`undefined + 1` is `NaN`. `y` is not a number and the compiler is right to flag that as an error.

**Comment by bobappleyard** [comment]
```ts
    let y = undefined + "";

```

Leads to `y` being a string.

Tried with `{}` and we get `Operator '+' cannot be applied to types '{}' and '{}'`

**Comment by RyanCavanaugh** [comment]
@ahejlsberg not spec'd this way but I think the arithmatic operators should disallow `null` / `undefined` in strictNullChecks. Thoughts?

Adding to a string is always allowed since people use this for concatenation of arbitrary values, especially for debugging code.

**Comment by errorx666** [comment]
`undefined + 1` evaluates as `NaN`.  Maybe `y` should be typed as the literal `NaN` value.  `NaN` is almost as troublesome as `null` in places, and harder to deal with (`NaN !== NaN`, `typeof NaN === 'number'`).  It's one of those cases of the compiler being technically correct but not very useful.  Perhaps we could consider treating it specially as well.

`value+""` is often used in place of `String(value)` and so this seems expected.
