### ISSUE TITLE
Unspecified required types

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#12791]
Now we can make the required types using parentheses or separated definitions. Is this the spec?

**TypeScript Version:**  master

**Code**

```ts
type PersonStrict = { name: string, age: number };
type PersonPartial = { name?: string, age?: number };
type Required<T> = { [K in (keyof T)]: T[K] };
const person: Required<PersonPartial> = { name: "iwata" };
```

or

```ts
...
type Keys<T> = keyof T;
type Required<T> = { [K in Keys<T>]: T[K] };
const person: Required<PersonPartial> = { name: "iwata" };
```

```
index.ts(4,7): error TS2322: Type '{ name: string; }' is not assignable to type 'Required<PersonPartial>'.
  Property 'age' is missing in type '{ name: string; }'.
```

cc @ahejlsberg @weswigham

**Comment by ahejlsberg** [comment]
No, that is an unintended effect and it will no longer be the case with #12826. Also, it doesn't really work because you can't get rid of the `undefined` that was added to each property type by `Partial<T>`.

**Comment by falsandtru** [comment]
I see, thanks for the answer.

**Comment by falsandtru** [comment]
Do you fix this effect? This will be a breaking change after many users found this and use as a hack.

**Comment by RyanCavanaugh** [comment]
We reserve the right to make back compat breaks for things that are effectively bugs. "Things behaved differently when I added parentheses which should have been meaningless" isn't something anyone should have taken a dependency on.
