### ISSUE TITLE
TypeScript 2.1.x fails to extend Error

### ISSUE THREAD

**Issue by jamesrichford** [Microsoft/TypeScript#12790]
**TypeScript Version:**  2.1.4

**Code**

Given the following definition

```ts
export default class ExtendedError extends Error {
    public get something(): number {
        return 42;
    }

    public doSomething() {

    }

}
```

I get the following output for 2.0.3

```ts
const extendedErrorInstance = new ExtendedError();

console.log("Is instanceof ExtendedError:", extendedErrorInstance instanceof ExtendedError);
// outputs "Is instanceof ExtendedError: true"
console.log("Is instanceof Error:", extendedErrorInstance instanceof Error);
// outputs "Is instanceof Error: true"
console.log("Value of something:", extendedErrorInstance.something);
// outputs "Value of something: 42"
console.log("Do something:", extendedErrorInstance.doSomething());
// executes function and outputs "Do something: undefined"
```

However for version 2.1.1 and 2.1.4 I get the following

```ts
const extendedErrorInstance = new ExtendedError();

console.log("Is instanceof ExtendedError:", extendedErrorInstance instanceof ExtendedError);
// outputs "Is instanceof ExtendedError: false"
console.log("Is instanceof Error:", extendedErrorInstance instanceof Error);
// outputs "Is instanceof Error: true"
console.log("Value of something:", extendedErrorInstance.something);
// outputs "Value of something: undefined"
console.log("Do something:", extendedErrorInstance.doSomething());
// throws error "TypeError: extendedErrorInstance.doSomething is not a function"
```

**Expected behavior:**
The extended error to behave as in the first example

**Actual behavior:**
It seems as if the error has not been extended at all

Thanks very much for your assistance in advance.

James

**Comment by dbaeumer** [comment]
I got hit by the same problem.

**Comment by aluanhaddad** [comment]
This is an intended change.

**Comment by aluanhaddad** [comment]
This [is document here](https://github.com/Microsoft/TypeScript-wiki/blob/master/Breaking-Changes.md#extending-built-ins-like-error-array-and-map-may-no-longer-work) and very interesting, relevant discussion can be found in #12123 #12581 among others.

**Comment by dbaeumer** [comment]
@aluanhaddad thanks for the info. Would be cool to link this here as well: http://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-1.html section `Use returned values from super calls as ‘this’`. I read this and having a pointer to the other doc would have saved quite some time.

**Comment by aluanhaddad** [comment]
@dbaeumer great point. That would definitely be good.

**Comment by andriijas** [comment]
Can someone help me

```
export class ApplicationError extends Error {
    public cause: Error;

    constructor(message?: string, cause?: Error) {
        super();
        this.message = message;
        this.cause = cause;
    }
}
```

Feels like Ive tried everything regarding changing the prototype/proto to get
`foo instanceof ApplicationError === true` but I  just cant make it. Its still Error or the ts compiler wont accept it

```
(5,30): error TS2539: Cannot assign to 'ApplicationError' because it is not a variable.
```
```
(5,1): error TS2322: Type 'typeof ApplicationError' is not assignable to type 'ApplicationError'.
  Property 'cause' is missing in type 'typeof ApplicationError'.
```

Thanks for any advice

**Comment by andriijas** [comment]
I had this issue and I followed the recommendation in the linked related issues to remove extends Error. Seems to work.

**Comment by jamesrichford** [comment]
Ace, good to have the link because I missed too :)

@andriijas I've just made a small npm module to allow you to extend it adds a little easier and also so you don't have to set the prototype for errors that extend errors etc. (so handles the chaining for you) :)

https://www.npmjs.com/package/extendo-error

**Comment by aluanhaddad** [comment]
@jamesrichford +1 for initiative with the new package. -10 million for breaking the web! 😆

**Comment by jamesrichford** [comment]
@aluanhaddad haha how do you mean breaking the web?

**Comment by aluanhaddad** [comment]
I meant to write "forking the web" but my brain isn't working at all today...

**Comment by blakeembrey** [comment]
@jamesrichford I would recommend using any of the existing packages on NPM today instead of making a new one. For instance, I use https://www.npmjs.com/package/make-error, but there's a few others.

One note on your code, I would do https://github.com/jamesrichford/extendo-error/blob/master/src/extendo-error.ts#L17 outside the constructor and not inside since it's really the same operation every time.

**Comment by jamesrichford** [comment]
@blakeembrey absolutely agree usually would but this package didn't come up on my searches thanks for pointing it out - will be useful for the future. Also thanks for the mini code review :)

**Comment by blakeembrey** [comment]
All good, finding quality modules on NPM can be tricky :) Especially for this, took me a while and various code reviews to decide I'd use and build with it going forward.
