### ISSUE TITLE
Breaking change in TSC 2.1.4 - Decorators emitted outside of ctor function for ES5 classes

### ISSUE THREAD

**Issue by Pip3r4o** [Microsoft/TypeScript#12796]
Decorators used to be emitted inside the constructor function pre-2.1.4, which allowed me to easily capture it when using ast-parsing for my own needs. With changes introduced in 2.1.4 the decorator is applied AFTER and OUTSIDE the function template assignment. (Transpiling for ES5)

**TypeScript Version:**  2.1.4

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
@ArbitraryDecorator("a.b.c.B")
class A extends B {

}
```

**Expected behavior (pre 2.1.4):**
```js
var A = (function (_super) {
    __extends(A, _super);
    ...
    A = __decorate([
        ArbitraryDecorator("a.b.c.B"),
        __metadata("design:paramtypes", [])
    ], A);
    return A;
}(B));
```

**Actual behavior (2.1.4):**
```js
var A = (function (_super) {
    __extends(A, _super);
    ...
    return A;
}(B));
A = __decorate([
    ArbitraryDecorator("a.b.c.B"),
    __metadata("design:paramtypes", [])
], A);
```

What's the reason behind this change?

**Comment by rbuckton** [comment]
The transformation-based emitter has a transformation phase for each script target, so that by the time we transform to ES5, we have already transformed to ES2015. The new emit is now more consistent with the ES2015 emit and has the same runtime semantics.

**Comment by Pip3r4o** [comment]
@rbuckton Thanks for the response! The changes just threw us off the first day of TS 2.1, and they didn't seem to be documented. We adjusted since.

Keep up the good work!
