### ISSUE TITLE
strictNullChecks ignores global variable.

### ISSUE THREAD

**Issue by maattdd** [Microsoft/TypeScript#12792]
**TypeScript Version:**  2.1.4

**Code**

```ts
class A {
  foo:number;
}
let a : A;

function bar () {
  a.foo = 9;
  console.log(a)
}

bar()
```

**Expected behavior:**
tsc --strictNullChecks --noImplicitAny should not compile (ERROR: a might be undefined line 7)
**Actual behavior:**
Compile without errors and then runtime error (Cannot set property foo of undefined)

**Comment by akarzazi** [comment]
The variable `a` may have been initialized when `bar()` is called.
Here is a sample : 

```typescript
class A {
  foo:number;
}

let a : A;

function bar () {
  a.foo = 9;
  console.log(a)
}

function init_a() {
  a = {foo:1}
}

init_a();
bar();
```

The flow analysis does not unfold functions.

**Comment by maattdd** [comment]
Exactly, if it *may* be initialized or not be, it should *not* compile if this is not checked in the code first 
`if (a) { a.foo = 9 } `

That's exactly the purpose of the *strict*NullChecks

**Comment by akarzazi** [comment]
From the documentation :
http://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html

> 
> Assigned-before-use checking
> 
> In strict null checking mode the compiler requires every reference to a **local variable** of a type that doesn’t include undefined to be preceded by an assignment to that variable in every possible preceding code path.

In your case `a` is not a **local variable** of `bar ()`, so it won't benefit from Assigned-before-use checking.

**Comment by RyanCavanaugh** [comment]
Globals are treated differently as they may be modified by code that we can't even see. It's impossible for us to prove that you *didn't* initialize it; this matters a lot for globals that are initialized by the host (and thus never assigned to, even though they definitely have values).
