### ISSUE TITLE
Signature overloading for arguments of type function fails

### ISSUE THREAD

**Issue by CaselIT** [Microsoft/TypeScript#12797]
**TypeScript Version:**  2.1.4
In typescript 2.1.4 the compiler fails to narrow the correct signature overloading of a function when a arguments is a function which can optionally take an argument.
**Code**

```ts
function test(fn: () => void): void;
function test(fn: (x: number) => void): void;
function test(fn: (x?: number) => void) {
  fn(1);
};

test((x) => { });
```

**Expected behavior:**
Compile without errors, like previous version of typescript.
**Actual behavior:**
When compiling with --noImplicitAny I get the error `error TS7006: Parameter 'x' implicitly has an 'any' type.`

Also VSCode selects the correct overload:
![image](https://cloud.githubusercontent.com/assets/16175304/21050093/f9070c0c-be18-11e6-91d7-4b00f833e5b0.png)
but the type of x is any:
![image](https://cloud.githubusercontent.com/assets/16175304/21050111/0f08051a-be19-11e6-894d-6db42f7df270.png)

**Comment by RyanCavanaugh** [comment]
Duplicate #11936

The proper declaration for `test` looks like this
```
function test(fn: (x: number) => void): void;
function test(fn: () => void): void;
function test(fn: (x?: number) => void) {
  fn(1);
};
```

**Comment by CaselIT** [comment]
Sorry, I did not find that issue before opening this.

It's strange that the order of the overloads changes the compiler result. Still reading the other issue it seems that also before this example was not working correctly.

I'll close this.
