### ISSUE TITLE
Incorrect compilation when calling someFunction(...args)

### ISSUE THREAD

**Issue by thomas-darling** [Microsoft/TypeScript#12800]
**TypeScript Version:**  2.1.4

**Code**

```ts
// This TypeScript code:
(foo["bar"] as Function)(...args);

// Compiles to this:
foo["bar"].apply(foo, args);
```
```ts
// This TypeScript code:
let bar = foo["bar"] as Function;
bar(...args);

// Compiles to this:
bar.apply(void 0, args);
```

**Expected behavior:**

I expected both code snippets to compile to:
```ts
foo["bar"].apply(foo, args);
```

**Actual behavior:**
The two code snippets are compiled differently, even though they are functionally identical.
In the second snippet, the function being called will break, as `this` will be `undefined`.

**Comment by RyanCavanaugh** [comment]
This behavior is specified by JavaScript. TypeScript does not break JavaScript runtime semantics.

![image](https://cloud.githubusercontent.com/assets/6685088/21120934/8d6f2584-c07e-11e6-9ec2-8c93b39b38c7.png)

**Comment by thomas-darling** [comment]
Wow, that's really messed up! Thanks for clarifying 😳

In case anyone else encounters this:
While I have to agree this is the correct behavior then, it should be noted that we had working code that broke when updating from TS 2.0 to 2.1 - apparently the behavior in 2.0 matched my expectation, while 2.1 changed it to match the spec.

**Comment by mhegazy** [comment]
I do not think the behavior has changed between 2.0 and 2.1.
