### ISSUE TITLE
For ES2015 target, cannot exclude conflicting @types of dependencies with ES5 target

### ISSUE THREAD

**Issue by cgilboy** [Microsoft/TypeScript#12814]
My project has an external dependency that was written in Typescript, targets ES5 and depends on `@types/es6-promise`. I do not see a way to compile my project without `tsc` including `node_modules/@types/es6-promise` which conflicts with `lib.es6.d.ts` and throws type errors. 

Am I missing a tsconfig.json option?

**TypeScript Version:**  Version 2.1.4

**Code**
Here is a stripped down example:

`tsconfig.json`
```json
{
    "compilerOptions": {
        "target": "ES2015",
        "types": []
    },
    "include": ["src/**/*"],
    "exclude": ["node_modules"]
}
```

`index.ts`
```ts
import * as dep from 'dependency';
...
```

Some external dependency transpiled into ES5 but depending on ES6 promise - `dependency.d.ts`
```ts
/// <reference types="es6-promise" />
export declare function usesPromises();
```

**Expected behavior:**
No type errors.

**Actual behavior:**
```node_modules/typescript/lib/lib.es6.d.ts(4936,11): error TS2300: Duplicate identifier 'Promise'.
node_modules/typescript/lib/lib.es6.d.ts(5261,11): error TS2300: Duplicate identifier 'Promise'.
node_modules/typescript/lib/lib.es6.d.ts(5511,13): error TS2300: Duplicate identifier 'Promise'.
node_modules/typescript/lib/lib.es6.d.ts(5737,11): error TS2300: Duplicate identifier 'Promise'.
node_modules/@types/es6-promise/index.d.ts(11,15): error TS2300: Duplicate identifier 'Promise'.
node_modules/@types/es6-promise/index.d.ts(42,19): error TS2300: Duplicate identifier 'Promise'.
```

**Comment by cgilboy** [comment]
Here is a quick repro project:
https://github.com/cgilboy/typescript_issue_12814

**Comment by aluanhaddad** [comment]
Since fake.d.ts references es6-promise as a global, but is itself a module, it is polluting the compilation context. Although you set `"types": []`, importing `;./fake'` brings it back into view. Ideally you should submit a PR to maintainer's of _fake_ or _fake_'s declaraction, depending on how it is distributed, that would update their declaration to import `es6-promise` correctly.

**Comment by mhegazy** [comment]
The correct fix here is for your dependency to not depend on `es6-promise`.
