### ISSUE TITLE
New Website Logo: Zesty.io

### ISSUE THREAD

**Issue by andyfleming** [Microsoft/TypeScript#12813]
- Name: Zesty.io
- Homepage url: https://www.zesty.io/
- Brand Guidelines/Licensing: *none*
- Logo: [zesty-io-logo.svg.zip](https://github.com/Microsoft/TypeScript/files/643319/zesty-io-logo.svg.zip)

**Comment by DanielRosenwasser** [comment]
You should see the changes get applied next time we publish the site.

**Comment by andyfleming** [comment]
Perfect. Thanks @DanielRosenwasser!

**Comment by DanielRosenwasser** [comment]
Should be up!

**Comment by andyfleming** [comment]
Awesome. Thanks!
