### ISSUE TITLE
Shouldn't allow a class instance passed to function if it is the wrong type

### ISSUE THREAD

**Issue by eamodio** [Microsoft/TypeScript#12811]
**TypeScript Version:**  2.1.4

**Code**

[Playground link](https://www.typescriptlang.org/play/index.html#src=class%20Base%20%7B%0D%0A%20%20%20%20value%3A%20string%3B%0D%0A%20%20%20%20constructor(value%3A%20string)%20%7B%20this.value%20%3D%20value%3B%20%7D%0D%0A%7D%0D%0A%0D%0Aclass%20A%20extends%20Base%20%7B%0D%0A%20%20%20%20constructor(value%3A%20string)%20%7B%20super(value)%3B%20%7D%0D%0A%7D%0D%0A%0D%0Aclass%20B%20extends%20Base%20%7B%0D%0A%20%20%20%20constructor(value%3A%20string)%20%7B%20super(value)%3B%20%7D%0D%0A%7D%0D%0A%0D%0Afunction%20onlyA(o%3A%20A)%20%7B%20console.log(%22onlyA%22%2C%20o.value)%3B%20%7D%0D%0Afunction%20onlyB(o%3A%20B)%20%7B%20console.log(%22onlyB%22%2C%20o.value)%3B%20%7D%0D%0A%0D%0Alet%20a%20%3D%20new%20A(%22a%22)%3B%0D%0Alet%20b%20%3D%20new%20B(%22b%22)%3B%0D%0A%0D%0AonlyA(b)%3B%0D%0AonlyB(a)%3B)

```ts
class Base {
    value: string;
    constructor(value: string) { this.value = value; }
}

class A extends Base {
    constructor(value: string) { super(value); }
}

class B extends Base {
    constructor(value: string) { super(value); }
}

function onlyA(o: A) { console.log("onlyA", o.value); }
function onlyB(o: B) { console.log("onlyB", o.value); }

let a = new A("a");
let b = new B("b");

onlyA(a); // good
onlyA(b); // bad
onlyB(b); // good
onlyB(a); // bad
```

**Expected behavior:**

I would expect the lines marked `bad` above to cause compile errors. I would expect this behavior when using interfaces, but not with classes.

**Actual behavior:**

Compiles without errors.

**Comment by aleksey-bykov** [comment]
answer: https://github.com/Microsoft/TypeScript/wiki/FAQ#what-is-structural-typing

**Comment by eamodio** [comment]
OK, right that make sense. What sent me down this path was I originally tried this:
```ts
function onlyA(o: A) {
    if (o instanceof A) {
        console.log("onlyA - is A", o.value);
        return;    
    }
    console.log("onlyA - not A", o.value);
}
```

But that doesn't compile, because it thinks `o` is the `never` type.

It feels like that is a bug right?

**Comment by RyanCavanaugh** [comment]
See #10422, #10648, #7271, etc
