### ISSUE TITLE
"Pick" and default function parameters

### ISSUE THREAD

**Issue by aliai** [Microsoft/TypeScript#12820]
**TypeScript Version:**  2.1.4

**Code**

```ts
  interface IFood {
    pizza: string;
  }

  function bar<K extends keyof IFood>(attributes: K[] = ['pizza']): Pick<IFood, K> {
    return {} as any;
  }
```

**Expected behavior:**
I want to set default value for `attributes` parameter. If i remove `= ['pizza']` part, the code compiles fine. But, I want to set default. I recon that I cannot set `attributes` later on in the function either?

**Actual behavior:**
It says
```
[ts] Type '"pizza"[]'` is not assignable to type 'K[]'. Type '"pizza"' is not assignable to type 'K'
```

**Comment by ahejlsberg** [comment]
This is working as intended. The constraint `K extends keyof IFood` means that a type argument for `K` may be any string literal type that describes a subset of the property names of `IFood`. That subset doesn't necessarily include `"pizza"`, so `"pizza"` isn't assignable to `K`. I'd suggest using an overload instead:

```ts
function bar(): Pick<IFood, "pizza">;
function bar<K extends keyof IFood>(attributes: K[]): Pick<IFood, K>;
function bar(attributes: (keyof IFood)[]): any {
    let attributesOrDefault = attributes || ["pizza"];
    // Implementation
}
```

**Comment by aliai** [comment]
Thanks for clarification and a good solution :)

But it is still a bit confusing that you could pass the same array to the function, yet you cannot set the default parameter with the same array. I understand that the subset type `K` doesn't necessarily include `"pizza"`, but how come I can _assign_ `"pizza"` with a function call to this argument yet I cannot set the default to the same value? Does default parameter assignment override/influence the type of the given parameter?
