### ISSUE TITLE
Is it safe to access private members by using an element access expression?

### ISSUE THREAD

**Issue by hediet** [Microsoft/TypeScript#12821]
**TypeScript Version:**  2.1 / nightly (2.2.0-dev.20161127)

**Code**
```ts
interface SomeType { }

class A { private m: SomeType; }

class B {
	foo(a: A) {
		const n1 = a.m; // (1)
		const n2 = a["m"]; // (2)
	}
}
```
As expected, the property access expression (1) produces a compile error. However, the element access expression (2) does not, even though typescript recognizes that (2) refers to member "A.m" as it infers the type "SomeType" for n2.

Can I expect (2) to not produce any compile errors in future typescript versions?

**Comment by ahejlsberg** [comment]
It's been that way since forever and several code bases depend on it so I don't imagine us changing it. If we did, we would minimally put it under a compiler switch.

**Comment by hediet** [comment]
Thank you for clarifying this!
