### ISSUE TITLE
code generation of imported default exports

### ISSUE THREAD

**Issue by postspectacular** [Microsoft/TypeScript#12823]
**TypeScript Version:**  2.1.1

**Code**

```ts
import foo from "./foo";
console.log(foo);
```

In the resulting JS...

**Expected behavior:**
```js
var foo = require("./foo").default;
console.log(foo);
```
**Actual behavior:**
```js
var foo_1 = require("./foo");
console.log(foo.default);
```

The current code generator of imported default exports results in an inefficient duplication of `.default` property accesses (for each use of each imported default symbol) instead of doing the lookup only once as part of the `require` call. Extensive use of default imports adds to serious bloat in emitted code.

Of course one can work around this and achieve the expected behavior above by manually adding another module-local redefinition, but that IMHO defies the purpose of using default exports in the first place:

```ts
import * as _foo from "./foo";
const foo = _foo.default;
console.log(foo);
```

**Comment by aluanhaddad** [comment]
This cannot be done because it does not comply with how ES Modules as specified, it would break compatibility and is a massive breaking change in general. Note that the same is true for any export aliased in an `import` clause, not just `default`.

**Comment by postspectacular** [comment]
@aluanhaddad thanks for clarifying, will have to work around it then...
