### ISSUE TITLE
Incorrect handling of unions of arrays. 

### ISSUE THREAD

**Issue by domoritz** [Microsoft/TypeScript#12829]
**TypeScript Version:**  2.1

**Code**

This code works although the type of the forEach callback is not suffuient. 
```ts
const a: boolean[] | number[] = [1,1,1];
a.forEach((b: number) => console.log);
```

But this fails (which is expected)
```ts
const a: boolean[] | number[] = [1,1,1];
a.forEach((b: boolean) => console.log);
```

I'd expect only this code to be valid
```ts
const a: boolean[] | number[] = [1,1,1];
a.forEach((b: boolean | number) => console.log);
```

I understand that `boolean[] | number[]` is a subtype of `(boolean | number)[]` and would expect typescript to be stricter if I provide the former.

**Comment by ahejlsberg** [comment]
Your first example compiles because control flow analysis has determined the type of `a` to be `number[]` at the call to `forEach` because the preceding assignment assigned an array literal of type `number[]`.

**Comment by domoritz** [comment]
This is the smallest example I could create to recreate an issue. 

In


```ts
channelEncoding.forEach(function(fieldDef: FieldDef | OrderChannelDef) {
  fields.push(field(fieldDef));
});
```

I know that `channelEncoding` is a `FieldDef[] | OrderChannelDef[]`. 

But I get the following error

```ts
[ts] Cannot invoke an expression whose type lacks a call signature. Type '((callbackfn: (value: FieldDef, index: number, array: FieldDef[]) => void, thisArg?: any) => void...' has no compatible call signatures.
```

Yes, the error is slightly different but I thought that was because ts handles complex types differently from simple types. 

I thought this error is caused by the behavior of the flow analysis (which is being smarter than my explicit type annotations).

**Comment by ahejlsberg** [comment]
This error is reported because `forEach` has a different signature in each of the two arrays, so there is not a common signature we can use in the call expression. You can help by providing a type assertion:

```ts
(channelEncoding as (FieldDef | OrderChannelDef)[]).forEach(...)
```

Alternatively, you could change `channelEncoding` to have type `(FieldDef | OrderChannelDef)[]`. It is slightly less strict (because it allows mixed arrays), but probably easier to work with.

**Comment by ahejlsberg** [comment]
For more discussion see #10620.

**Comment by domoritz** [comment]
Thanks for the explanation! The behavior I posted above is still a bit odd (flow analysis overrides my explicit annotation) but I don't have a problem with it.
