### ISSUE TITLE
Mapped types not working on playground?

### ISSUE THREAD

**Issue by spion** [Microsoft/TypeScript#12836]
**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)

**Code**

The following [example](http://bit.ly/2hnV5df) does not work on the playground but compiles with latest released TS:
 
```ts
interface Table<Name, Row> {
  name: Name;
  item: Row;
}

declare function select<Name1 extends string, Row1, Name2 extends string, Row2>(
    t1:Table<Name1, Row1>,
    t2: Table<Name2, Row2>
):Promise<Array<{[K in Name1]: Row1} & {[K in Name2]: Row2}>>


declare var Users: Table<'users', {name: string, created: Date}>
declare var Posts: Table<'posts', {name: string, created: Date}>

select(Users, Posts).then(results => results[0].posts.created)
```

**Expected behavior:**

compiles

**Actual behavior:**

mapped types are not recognized by the compiler.

-----

Looking at the playground sources, it appears that the TypeScript version is 2.0 (hasn't been updated to 2.1)

**Comment by AlexGalays** [comment]
Works for me. The playground can take a bit of time to update itself sometimes.

Check the console. This is what I see: 'ts.version: 2.1.4-insiders.20161201'

**Comment by spion** [comment]
Apologies, it was my browser cache 😊
