### ISSUE TITLE
add Array.prototype.includes()

### ISSUE THREAD

**Issue by phra** [Microsoft/TypeScript#12848]
TypeScript version: 2.0.10

it would be nice add the ES2016 [`Array.prototype.includes()`](https://developer.mozilla.org/it/docs/Web/JavaScript/Reference/Global_Objects/Array/includes) function to the built-ins methods of arrays.
ATM i have to cast the array to `any` in order to compile successfully.

**Expected behavior:**
TS compiles the code without errors
**Actual behavior:**
TS won't compile because of `includes()`

**Comment by aluanhaddad** [comment]
**tsconfig.json**
```json
{
  "compilerOptions": {
    "target": "es2016"
  }
}
```
or
**tsconfig.json**
```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["es2016"]
  }
}
```

**Comment by phra** [comment]
thank you @aluanhaddad !

**Comment by RyanCavanaugh** [comment]
@phra Which search terms did you use before logging this? We're trying to reduce duplicates/questions and are curious what people are searching (and why they're not finding the existing issues) when logging bugs. Thanks!

**Comment by phra** [comment]
@RyanCavanaugh i have looked for `includes()` and i didn't found anything.
