### ISSUE TITLE
tsc's error message is printed to stdout, not stderr

### ISSUE THREAD

**Issue by phanect** [Microsoft/TypeScript#12844]
**TypeScript Version:**  2.0.10, 2.1.4, nightly (2.2.0-dev.20161211)

**Code**

```shell
$ tsc > /dev/null
```

**Expected behavior:**

Error messages should be shown even std**out** is redirected to /dev/null

```shell
$ tsc
app/slider/slider.component.ts(84,13): error TS2304: Cannot find name 'Promise'.
app/slider/slider.component.ts(86,13): error TS2304: Cannot find name 'Promise'.
app/slider/slider.component.ts(136,13): error TS2304: Cannot find name 'Promise'.
# Other error messages follows...

$ tsc > /dev/null
app/slider/slider.component.ts(84,13): error TS2304: Cannot find name 'Promise'.
app/slider/slider.component.ts(86,13): error TS2304: Cannot find name 'Promise'.
app/slider/slider.component.ts(136,13): error TS2304: Cannot find name 'Promise'.
# Other error messages follows...
```

**Actual behavior:**

Error messages is not shown because messages are printed to std**out** and it is redirected to /dev/null

```shell
$ tsc
app/slider/slider.component.ts(84,13): error TS2304: Cannot find name 'Promise'.
app/slider/slider.component.ts(86,13): error TS2304: Cannot find name 'Promise'.
app/slider/slider.component.ts(136,13): error TS2304: Cannot find name 'Promise'.
# Other error messages follows...

$ tsc > /dev/null
# Nothing shown
```

**Comment by DanielRosenwasser** [comment]
See #615 for a previous discussion. To quote @mhegazy:

> This is actually by design. writing errors to standard error was a wrong choice in the first place, as the errors are not errors from the compiler (e.g. crashes) but rather user errors, and the user would expect them as part of the normal output of the compiler.
> 
> The new behavior is consistent with other compilers as well.

**Comment by phanect** [comment]
@DanielRosenwasser Oh, missed it! Thanks!
