### ISSUE TITLE
Type narrowing for Tuple-Elements

### ISSUE THREAD

**Issue by christyharagan** [microsoft/TypeScript#12849]
**TypeScript Version:**  nightly (2.2.0-dev.20161210)

**Code**

```ts
function test([a, b]: [number, number] | [string, string]) {
  if (typeof a === 'number') {
    b++
  }
}
```

**Expected behavior:**
```b``` to be narrowed to ```number``` and the resulting code to throw no compiler errors

**Actual behavior:**
```b``` has type ```number | string``` and thus the code throws a compiler error complaining that ```b++``` can only apply to numbers

**Comment by mhegazy** [comment]
Same underlying issue as https://github.com/Microsoft/TypeScript/issues/14957

**Comment by christyharagan** [comment]
Should I close this in favour of #14957 ?

**Comment by mhegazy** [comment]
I would leave them both open. though both would be addressed by the same change, ppl tend to think of them as two separate scenarios. this way we have a landing point for users searching for similar issues.

**Comment by RyanCavanaugh** [comment]
This would work if it weren't for the destructuring. Our CFA algorithm isn't able to correlate values from different places like this; this comes up from time to time but doesn't seem to merit the required work at this time.
