### ISSUE TITLE
transpile for systemjs bundle not working since 2.1.0

### ISSUE THREAD

**Issue by Hanfrey** [Microsoft/TypeScript#12851]
Im bunde angular2 with the help of systemjs-bundle. It worked fine since the 2.1.0 version. 

**TypeScript Version:**  Works with 2.0.10, since 2.1.0 it stopped working.

**Code**
My  Systemconfig, where the transpiler is declared and mapped.
```js
System.config({
    transpiler: 'typescript', //add transpiler
    map: {
        app: '',
        '@angular': 'node_modules/@angular',
        'rxjs': 'node_modules/rxjs',
        'typescript': 'node_modules/typescript/lib/typescript.js' //add typescript map
    },
    packages: {
        '@angular/core': {
            main: 'index.js' //use the ESM entry point for bundling tools
        },
        '@angular/common': {
            main: 'index.js' //use the ESM entry point for bundling tools
        },
        '@angular/compiler': {
            main: 'index.js' //use the ESM entry point for bundling tools
        },
        '@angular/forms': {
            main: 'index.js'
        },
        '@angular/http': {
            main: 'index.js'
        },
        '@angular/platform-browser': {
            main: 'index.js' //use the ESM entry point for bundling tools
        },
        '@angular/platform-browser-dynamic': {
            main: 'index.js' //use the ESM entry point for bundling tools
        },
        '@angular/router': {
            main: 'index.js' //use the ESM entry point for bundling tools
        },
        app: {
            main: './main.js',
            defaultExtension: 'js'
        },
    }
})

```
Gulp Task:
```js
gulp.task('bundle:angular', function() {
    var builder = new SystemBuilder('dist', './src/bundleconfig.js');
    return builder.bundle('vendor.js', 'dist/vendor.js', {
         externals: ['main'],
        minify:true,
        mangle:true});
});
```

**Expected behavior:**
Bundle works fine.

**Actual behavior:**
It throws an error:  (SystemJS) Unexpected token ;

It only doesnt work if Typescript is > 2.1.0. Is this because angular 2 is built with a lower version, or does it have any other source, there shouldnt be an BC in a 2.X.0 Version, right?

**Comment by aluanhaddad** [comment]
I don't know why you would get a syntax error. How are you passing typescriptOptions to SystemJS? I don't see it in your config.

**Comment by vladima** [comment]
can you please provide a standalone repro that will demonstrate the problem?

**Comment by Hanfrey** [comment]
Hello,

I made an [Repo](https://github.com/Hanfrey/ts-test/tree/master) to see it, it master is with the ^ so it install 2.1.4 the working branch is without ^ so its installing 2.0.10. 

Clone it, npm install, gulp.

**Comment by vladima** [comment]
I can repro this, seems to have the same root cause with https://github.com/Microsoft/TypeScript/issues/12876
