### ISSUE TITLE
add syntax to force picking a certain overload

### ISSUE THREAD

**Issue by zpdDG4gta8XKpMCd** [microsoft/TypeScript#12854]
i need to pick a certain overload and there is no way to tell TS which one it is other than specifying all type arguments which is easily tedious and not worth the trouble, hence rendering overloads usless

consider adding a syntax that gives TS a hint:
```typescript
const certainOveroad = createObject(this, that) @ 2;
```

or 

```typescript
const certainOveroad = createObject(this, that) # 2;
```

or you prob know better what

**Comment by gcnew** [comment]
Positional picking sounds very imperative and fragile. IMHO it's not a typesystem thing, maybe looking at why there are so many / not distinct enough overloads or making the compiler smarter at inferring the intention (e.g. by hinting a key argument) seem better to me.

**Comment by aleksey-bykov** [comment]
You won't belive when you know how much big of a fan I am to make the compiler smarter. Unfortunately smart ideas are last to look at if not closed at all. There was a request for partial type arguments for example and a couple more: #6344

**Comment by gcnew** [comment]
Yes, I know :). My comment is just how I feel about positional overloading, nothing personal. I believe https://github.com/Microsoft/TypeScript/issues/9949 and https://github.com/Microsoft/TypeScript/issues/11152 will help greatly. For the rest (few) instances manually providing the type parameter seems like a good compromise.

**Comment by RyanCavanaugh** [comment]
This would make overload ordering even *more* observable which is definitely not what we want.
