### ISSUE TITLE
No easy way to convince TypeScript a variable has been initialized.

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#12855]
Reported by @wycats. Compile this under `strictNullChecks` and `noImplicitAny`.

```ts
declare function someAbstraction(x: any): any;

let x: string;

someAbstraction(() => {
  x = "hello";
});

// All of the following are errors.
x;
x as any;
x!;
```

I'd argue that both type assertions should be able to signal to the type system that the variable has been initialized.

**Comment by RyanCavanaugh** [comment]
Duplicate #11463

**Comment by mhegazy** [comment]
declaring `x` as `string | undefined` should make these all work though.
