### ISSUE TITLE
jsDoc tags are not available from the language service API

### ISSUE THREAD

**Issue by Knagis** [Microsoft/TypeScript#12863]
The earlier versions (before 2.1) returned all tags (except for `@param`) when `symbol.getDocumentationComment()` was called. The new parser is smarter and parses all tags. However they cannot be retrieved by using the public API.

In my case this is needed so that the tags can be analysed by a build script that generates code and documentation. I am using a mixture of standard and custom jsdoc tags that control how a type or property is represented in the documentation.

The `typescript.d.ts` file does not expose the `jsDoc` property of nodes. I can do `<ts.NodeArray<ts.JSDoc>>(<any>node).jsDoc` - this works but I would prefer if this was officially exposed in the API.

**Comment by sandersn** [comment]
Does the API that @minestarks introduced in #12856 address your use case? It adds a new `tags` property to the return value of `getDocumentationComment`.
Note that it only exposes unknown tags since `getTypeAtLocation` uses `@returns` and `@type` JSDoc when available.

**Comment by Knagis** [comment]
Yes, it seems to be what I required.
