### ISSUE TITLE
the word 'location' in a rest operator errors out

### ISSUE THREAD

**Issue by Mair** [Microsoft/TypeScript#12865]
**TypeScript Version:**  2.1.4 

**Code**

```ts

let Peter = {
    age: 44,
    name: "Peter",
    location: "VIC"
}

//location gives an error saying "Cannot redeclare block-scoped variable 'location'"
//however if I change 'location' to _location everything works 
let {age, location, ...obj2} = Peter

```

**Expected behavior:**
any valid variable name should be fine

**Actual behavior:**
the word location is acting strange
location gives an error saying "Cannot redeclare block-scoped variable 'location'"
however if I change 'location' to _location everything works

**Comment by RyanCavanaugh** [comment]
This is a correct error.
![image](https://cloud.githubusercontent.com/assets/6685088/21121088/5c5025ce-c07f-11e6-8667-a4a036d9ef0c.png)

If you're not running in a browser, specify a different `lib` to exclude the DOM-defined declarations.

**Comment by Mair** [comment]
Ahh,
Cheers
