### ISSUE TITLE
incorrect demo codes in chapter "/docs/handbook/interfaces.html" of handbook

### ISSUE THREAD

**Issue by michael8090** [microsoft/TypeScript#12872]
**type**: docs

**position**:  the second code snippet of the topic `Optional Properties`, chapter [interfaces](https://www.typescriptlang.org/docs/handbook/interfaces.html)

**what's unexpected**: the code snippet doesn't contain a mistype of "color", hence has no error as described in the doc above the code snippet:

![image](https://cloud.githubusercontent.com/assets/2306105/21127781/a492a634-c130-11e6-893d-5ca1a83f04fb.png)

**what's the expected doc**: maybe we should change the assignment to:

```js
    if (config.color) {
        // Error: Property 'color' does not exist on type 'SquareConfig'
        newSquare.color = config.clor; // instead of color
    }
```

**Comment by mhegazy** [comment]
A PR would be appreciated. The source is at https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Interfaces.md

**Comment by gwenie-vo** [comment]
This should be fixed soon :)

**Comment by huandu** [comment]
This typo hasn't been fixed. I can still read it on handbook.

https://www.typescriptlang.org/docs/handbook/interfaces.html
