### ISSUE TITLE
Object.keys has wrong return type from 2.1

### ISSUE THREAD

**Issue by davhdavh** [Microsoft/TypeScript#12870]
**TypeScript Version:**  2.1.4

**Code**

```ts
let test = {a:1, b:1};
let a = Object.keys(test); //currently string[]

interface ObjectConstructor2 extends ObjectConstructor {
   keys<T>(o: T): (keyof T)[];
}
let correct = (<ObjectConstructor2>Object).keys(test);
```

**Expected behavior:**
keys actually returns keys

**Actual behavior:**
keys returns non-specific string array

**Comment by mhegazy** [comment]
This is intentional. Types in TS are open ended. So keysof will likely be less than all properties you would get at runtime.
