### ISSUE TITLE
Typecast string to string literal

### ISSUE THREAD

**Issue by stochris** [Microsoft/TypeScript#12879]
**TypeScript Version:**  2.1.4

**Code**

```ts
// in 2.1.4  iShouldBeStringLiteral is now a string
let iShouldBeStringLiteral = type('This is a string')
export function type<T>(label: T | ''): T {
  return <T>label;
}
```

**Expected behavior:**
Before updating to typescript 2.1.4 the function transformed string to string literals with the same value
**Actual behavior:**
Now, even though the function returns a string literal type, assigning the return value to a variable / object property, will downcast it to string
![function_type](https://cloud.githubusercontent.com/assets/9612572/21140592/946957d8-c141-11e6-8ed9-a5e016751b52.png)
![variable_type](https://cloud.githubusercontent.com/assets/9612572/21140593/966b834e-c141-11e6-868e-dfc0ac3ef13d.png)

In the second image, I would expect `x` to be of type `'String literal'`

This is especially in redux like scenarions, where you have to switch based on a constant and need the exhaustive checking in order to get type safety inside every case branch

edit: I know the solution is a bit hackish, but it helps a lot. If there is any other way of doing this, I'm more than open to suggestions

**Comment by stochris** [comment]
Also, the non templated version the function works as intended
```
function type(val: 'this is string literal'){
    return val as 'this is string literal';
}

// stringLiteral appears as ' let stringLiteral: "this is string literal" '
let stringLiteral = type('this is string literal');
```

**Comment by ahejlsberg** [comment]
In 2.1 we preserve literal types of expressions and variables for a long as possible, but when we infer a literal type for a mutable location such as a `let` or `var` variable, we widen to the base primitive type. If you declare `iShouldBeStringLiteral` using `const` you shouldn't need the `type` function at all.

For more details see #10676.

**Comment by stochris** [comment]
Thank you very much. Problem solved
