### ISSUE TITLE
Missing inference for closures when target = "es6"

### ISSUE THREAD

**Issue by mindplay-dk** [Microsoft/TypeScript#12880]
We ran into a problem with TS `2.1.4`, where setting `target` to `es6` causes type inference to fail under certain very specific conditions.

It looks like a marginal edge-case and probable bug (in the language service?) so here's the code and `tsconfig.json` to reproduce it:

https://gist.github.com/mindplay-dk/235af5032bce1c390444c2cc39888b08

Is VS Code, hover over `e` on this line:

    form.onSetName(e => console.log(`hello ${e.name}`));

It will correctly infer as `{ name: string }`.

Now change the target to `es6` in `tsconfig.json` - it now infers the argument type as `any` rather than the declared type.

Looks like a bug? Inference shouldn't change depending the target language, should it?

**Comment by mhegazy** [comment]
This is not the target that is causing this behavior it is the lib. this is caused by the library. specifically the the declaration for `name` in `Function` interface.

the issue is related to https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#implicit-any-error-raised-for-un-annotated-callback-arguments-with-no-matching-overload-arguments

The lambda argument gets an `any` type as it gets contextually typed by the first overload, then the overlaod resolution fails, since both have `name` but `Function` has a `readonly` `name`.

I would say the overload here is not really needed, and should be written as a single signature with union types:  

```ts
function hook(listener: TEvent | Listener<TEvent>):void {
 ...
```

**Comment by mindplay-dk** [comment]
> The lambda argument gets an `any` type as it gets contextually typed by the first overload, then the overlaod resolution fails, since both have `name` but `Function` has a `readonly` `name`.

This is the only part I can kind-of sort-of understand, but I feel like the explanation is very technical, and there was a team-wide period of bafflement and google searches etc. during our TypeScript workshop, before we decided to file this issue.

Mainly, my problem here is *surprise*, which is a bad thing in any language or API and shouldn't happen.

But there is a practical problem with the work-around you propose as well, since, in this case, the documentation (which had not been written) is actually different for the two different overloads, e.g.:

```ts
    /// Publishes an event to all attached Listeners
    function hook(event: TEvent)
    /// Subscribes a Listener to receive future events
    function hook(listener: Listener<TEvent>)
    function hook(arg) {
        // ...
    }
```

Besides the documentation problem, naming the argument as either `event` or `listener` is also misleading, since those are two different arguments producing two different results. Naming my argument `event_or_listener` also isn't a good solution, since I'd end up with either additional intermediary variable assignments for clarification, or confusing statements like `listeners.push(event_or_listener)`.

I looked and can't find the conflicting declarations in the library `.d.ts` files, but from what you explained, there's a difference between the declarations of `name` in two different versions of one of the core libraries - I understand that either one or the other might be technically slightly incorrect if declared consistently with the other, but is that worse than the current situation?

I personally would not care whether `name` was declared as `readonly` or not - if it was consistently declared as `readonly`, you could still work around the (extremely rare?) edge-case where someone wants to set the name, e.g. `func['name'] = 'new_name'`, or, if declared consistently *not* `readonly`, I think we could live with a run-time error that shows up in language implementations where `name` is really read-only?

Overloads like these support a common JS pattern where the argument-type determines the action - whether we think that's a good idea or not, real-world JS is full of this sort of thing, and I'd strongly prefer to be able to consistently use overloads the way they were intended (and expected) to work.
