### ISSUE TITLE
Tagged union with boolean discriminator does not work without `===`

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#12882]
**TypeScript Version:**  nightly (2.2.0-dev.20161213)

**Code**

```ts
type Result = Success | Failure;
interface Success {
    success: true;
    value: number;
}
interface Failure {
    success: false;
    reason: string;
}

declare const x: Result;
if (x.success) {
    x.value;
} else {
    x.reason;
}
```

**Expected behavior:**

No error.

**Actual behavior:**

```
a.ts(15,7): error TS2339: Property 'reason' does not exist on type 'Result'.
  Property 'reason' does not exist on type 'Success'.
```

It works with `x.success === true`.

**Comment by ahejlsberg** [comment]
This works as expected with `--strictNullChecks`. In classic type checking mode *every* type allows `undefined` or `null` as a value, so we can't know for sure that `x.success` is `false` in the `else` branch (because it could be `undefined` or `null`).
