### ISSUE TITLE
Type guards disregard generic type constraints

### ISSUE THREAD

**Issue by aengl** [Microsoft/TypeScript#12908]
**TypeScript Version:**  nightly (2.2.0-dev.20161214)

**Code**

```ts
class Props {}

class Foo<T extends Props> {
  check<T extends Foo<Props>>(x: {new(): T}): this is T {
    return true;
  }
}

let foo = new Foo<Props>();
if (foo.check(Foo)) {
  let bar = foo; // bar has type Foo<any>
}
```

**Expected behavior:**

`bar` should infer type `Foo<Props>` since Foo has a generic type constraint.

**Actual behavior:**

`bar` resolves to type `Foo<any>`.

**Comment by RyanCavanaugh** [comment]
You need to consume `T` in `Foo` to create a generic inference site. This code works:
```ts
class Foo<T extends Props> {
  self: T;
  check<T extends Foo<Props>>(x: {new(): T}): this is T {
    return true;
  }
}
let foo = new Foo<Props>();
if (foo.check(Foo)) {
  let bar = foo; // bar has type Foo<Props>
}
```
See also https://github.com/Microsoft/TypeScript/wiki/FAQ#why-doesnt-type-inference-work-on-this-interface-interface-foot---

**Comment by aengl** [comment]
Thank you and apologies that I didn't spot it in the FAQ.
