### ISSUE TITLE
Add support for ES `global` proposal

### ISSUE THREAD

**Issue by mhegazy** [microsoft/TypeScript#12902]
Here is the proposal: https://github.com/tc39/proposal-global

**Comment by DanielRosenwasser** [comment]
As discussed offline, it sounds like this is only a change to `lib.d.ts`, because anything else would be a polyfill.

**Comment by AaronNGray** [comment]
How about ```Global``` for the namespace ?

**Comment by saschanaz** [comment]
This has been fixed, you can use `globalThis` in the latest nightly build.

**Comment by DanielRosenwasser** [comment]
Fixed by #29332.
