### ISSUE TITLE
Inconsistent compiler/service type information with intersected mapped type

### ISSUE THREAD

**Issue by HerringtonDarkholme** [Microsoft/TypeScript#12903]
**TypeScript Version:**  2.1.4

**Code**

```ts
export type Action<T, R> = {
  [K in keyof T]: (s: string, t: any) => T[K]
} & {
  [K in keyof R]: (s: string, t: R[K]) => any
} & {
  [k: string]: (s: string, t: any) => any
}

interface Test {
  actions<T, R>(opt: Action<T, R>): [T, R]
}

declare var t: Test

var kkk = t.actions({
  test(s, n: number) {
    s.charA // error when compiling, but language service report s has the type any
    return '3333'
  }
})
```

**Expected behavior:**
`s` has the type `string` in language service.

**Actual behavior:**
`s` has the type  `any` in popup.

Reproduction in playground

https://www.typescriptlang.org/play/index.html#src=export%20type%20Action%3CT%2C%20R%3E%20%3D%20%7B%0D%0A%20%20%5BK%20in%20keyof%20T%5D%3A%20(s%3A%20string%2C%20t%3A%20any)%20%3D%3E%20T%5BK%5D%0D%0A%7D%20%26%20%7B%0D%0A%20%20%5BK%20in%20keyof%20R%5D%3A%20(s%3A%20string%2C%20t%3A%20R%5BK%5D)%20%3D%3E%20any%0D%0A%7D%20%26%20%7B%0D%0A%20%20%5Bk%3A%20string%5D%3A%20(s%3A%20string%2C%20t%3A%20any)%20%3D%3E%20any%0D%0A%7D%0D%0A%0D%0Ainterface%20Test%20%7B%0D%0A%20%20actions%3CT%2C%20R%3E(opt%3A%20Action%3CT%2C%20R%3E)%3A%20%5BT%2C%20R%5D%0D%0A%7D%0D%0A%0D%0Adeclare%20var%20t%3A%20Test%0D%0A%0D%0Avar%20kkk%20%3D%20t.actions(%7B%0D%0A%20%20test(s%2C%20n%3A%20number)%20%7B%0D%0A%20%20%20%20s.charA%0D%0A%20%20%20%20return%20%273333%27%0D%0A%20%20%7D%0D%0A%7D)

**Comment by DanielRosenwasser** [comment]
Weird symptoms:

* Language service reports `s` as type `any`.
* Accessing a bogus property on `s` reports that `s` has type `string`.
* Accessing properties off `s` gives no completions.
