### ISSUE TITLE
Generic type inferred as supertype if that's the callback parameter type

### ISSUE THREAD

**Issue by andy-ms** [microsoft/TypeScript#12915]
**TypeScript Version:**  nightly (2.2.0-dev.20161214)

(Ref: https://github.com/Microsoft/TypeScript/pull/12862#discussion_r92284049)

**Code**

```ts
function f<T>(x: T[], y: (t: T) => void): T[] { return x; }
function g(value: {}): void {}
const x: number[] = f([1, 2], g);
```

**Expected behavior:**

Infers `f<number>`.

**Actual behavior:**

Infers `f<{}>`.

**Comment by PyroVortex** [comment]
Both `[1, 2]` and `g` are inference sites for type parameter `T`, so the inference system looks for a common supertype between candidates `number` and `{}` and returns `{}`.

**Comment by andy-ms** [comment]
But, any function of type `{} => void` should also be a function of type `number => void`. A function that can take anything can take a number. So maybe we could be a little smarter and not widen `T` based on a type in that position.

**Comment by Zzzen** [comment]
It's not fixed yet.

**Comment by RyanCavanaugh** [comment]
Actually it's fixed in 3.5! 🎉

**Comment by Zzzen** [comment]
I checked following code in ts 3.5.1. The `Props` is sometimes inferred as the same as its supertype `Defaults`. The `W` is working as expected, but `X`/`Y` does not work. Could you help me with this? @RyanCavanaugh 

[playgroud](https://www.typescriptlang.org/play/#src=declare%20type%20RequiredKeys%3CT%3E%20%3D%20%7B%0A%20%20%20%20%5BK%20in%20keyof%20T%5D-%3F%3A%20(%7B%7D%20extends%20%7B%0A%20%20%20%20%20%20%20%20%5BP%20in%20K%5D%3A%20T%5BK%5D%3B%0A%20%20%20%20%7D%20%3F%20never%20%3A%20K)%3B%0A%7D%5Bkeyof%20T%5D%3B%0Adeclare%20type%20MissingProps%3CDefaults%2C%20Props%20extends%20Defaults%3E%20%3D%20Pick%3CProps%2C%20Exclude%3Ckeyof%20Props%2C%20RequiredKeys%3CDefaults%3E%3E%3E%3B%0Adeclare%20type%20WithDefaultProps%3CDefaults%2C%20Props%20extends%20Defaults%3E%20%3D%20MissingProps%3CDefaults%2C%20Props%3E%20%26%20%7B%0A%20%20%20%20%5BP%20in%20RequiredKeys%3CDefaults%3E%5D%3F%3A%20Defaults%5BP%5D%3B%0A%7D%3B%0Adeclare%20function%20withDefaultProps%3CDefaults%2C%20Props%20extends%20Defaults%2C%20Ret%2C%20RefParam%3E(Comp%3A%20(props%3A%20Props%2C%20ref%3A%20RefParam)%20%3D%3E%20Ret%2C%20defaults%3A%20Defaults)%3A%20(props%3A%20WithDefaultProps%3CDefaults%2C%20Props%3E%2C%20ref%3F%3A%20RefParam)%20%3D%3E%20Ret%3B%0A%0A%0Ainterface%20Props%20%7B%0A%20%20width%3A%20number%3B%0A%20%20audioFile%3A%20string%3B%0A%20%20onPosChange%3A%20(ev%3A%20any)%20%3D%3E%20void%3B%0A%7D%0A%0Afunction%20Ccc(props%3A%20Props)%20%7B%0A%20%20%20%20return%20props.width%0A%7D%0A%0A%2F%2F%20Inferred%20as%3A%20function%20withDefaultProps%3C%7B%20width%3A%20number%3B%20%7D%2C%20Props%2C%20number%2C%20%7B%7D%3E%0Aconst%20W%20%3D%20withDefaultProps(Ccc%2C%20%7B%20width%3A%20123%20%7D)%0A%2F%2F%20Inferred%20as%3A%20function%20withDefaultProps%3C%7B%20readonly%20width%3A%20123%3B%20%7D%2C%20%7B%20readonly%20width%3A%20123%3B%20%7D%2C%20number%2C%20%7B%7D%3E%0Aconst%20X%20%3D%20withDefaultProps(Ccc%2C%20%7B%20width%3A%20123%20%7D%20as%20const)%0A%2F%2F%20Inferred%20as%3A%20function%20withDefaultProps%3C%7B%20width%3A%20number%3B%20%7D%2C%20Props%2C%20number%2C%20%7B%7D%3E%0Aconst%20Y%20%3D%20withDefaultProps(Ccc%2C%20%7B%20width%3A%20123%2C%20onPosChange%3A%20()%20%3D%3E%20%7B%7D%20%7D)%0A)


```ts
declare type RequiredKeys<T> = {
  [K in keyof T]-?: ({} extends {
      [P in K]: T[K];
  } ? never : K);
}[keyof T];
declare type MissingProps<Defaults, Props extends Defaults> = Pick<Props, Exclude<keyof Props, RequiredKeys<Defaults>>>;
declare type WithDefaultProps<Defaults, Props extends Defaults> = MissingProps<Defaults, Props> & {
  [P in RequiredKeys<Defaults>]?: Defaults[P];
};
declare function withDefaultProps<Defaults, Props extends Defaults, Ret, RefParam>
(Comp: (props: Props, ref: RefParam) => Ret, defaults: Defaults): 
(props: WithDefaultProps<Defaults, Props>, ref?: RefParam) => Ret;


interface Props {
  width: number;
  audioFile: string;
  onPosChange: (ev: any) => void;
}

function Ccc(props: Props) {
  return props.width
}

// ✅ Inferred as: function withDefaultProps<{ width: number; }, Props, number, {}>
const W = withDefaultProps(Ccc, { width: 123 })
// ❌ Inferred as: function withDefaultProps<{ readonly width: 123; }, { readonly width: 123; }, number, {}>
const X = withDefaultProps(Ccc, { width: 123 } as const)
// ❌ Inferred as: function withDefaultProps<{ width: number; }, Props, number, {}>
const Y = withDefaultProps(Ccc, { width: 123, onPosChange: () => {} })
```

**Comment by Zzzen** [comment]
It's not fixed.

```ts
$ cat test.ts

function f<T>(x: T[], y: (t: T) => void): T[] { return x; }
function g(value: {}): void {}
const x: number[] = f([1, 2], g);

$ tsc --version
Version 3.5.1

$ tsc test.ts
test.ts(3,7): error TS2322: Type '{}[]' is not assignable to type 'number[]'.
  Type '{}' is not assignable to type 'number'.
```
