### ISSUE TITLE
instanceof doesn't work as expected for derived class

### ISSUE THREAD

**Issue by KoenT-IM** [Microsoft/TypeScript#12912]
**TypeScript Version:**  2.1.4

**Code**

I am seeing a very strange problem where instanceof doesn't seem to work properly for a derived class in TypeScript. The structure of my classes is as follows (I tried to make a self-contained example that shows the problem, but I couldn't reproduce the error in that simple example...):

```ts
interface Serializing 
{
    serialize(): string 
}

class Storage implements Serializing
{
    // constructor, methods, serialize, ...
}

class StorageContainer
{
    // constructor, methods, various methods that act on storage_, ...

    protected storage_: Storage;
}

class Derived extends StorageContainer
{
    constructor()
    {
        super();

        let test1 = this instanceof Derived; // succeeds
        let test2 = this instanceof StorageContainer; // succeeds
    }

    // ... constructor, methods, ...
}
```

and I then run this method using these classes:

```ts
testInstanceofOnDerivedClasses()
{
    let derived = new Derived();

    let test1 = derived instanceof Derived; // succeeds
    let test2 = derived instanceof StorageContainer; // fails?
}
```

**Expected behavior:**

All test variables should be true.

**Actual behavior:**

The test2 variable in testInstanceofOnDerivedClasses (testing if derived class is an instance of the base class) fails. 

I also did tests with other simpler derived classes, and there instanceof does work as expected. Only in this particular case I have, it doesn't...

Also remarkable: when I do the 2 tests inside the constructor of Derived, they both succeed...
But then once outside of the constructor, the second test fails...

I have already asked on SO, but I am posting this here, as I think this might be TypeScript bug that only occurs in very specific circumstances somehow:

- I couldn't reproduce this in a simple self-contained example
- especially the fact that the tests are OK inside the constructor, but not any longer once returned from the constructor worries me

I would be glad to check out a few things if people have advice as to what to look for.

I have to apologize: normally, I would provide a simple self-contained example, but in this case, I can't reproduce it that way... Since the codebase I'm working on is closed-source, I can't just post the project online, but perhaps I could ask here if I can share it privately with the Microsoft team if needed.

But if there are things I need to check first, please let me know!

Additional note: this also occurred with TypeScript 1.7.6.0. Switching to the latest version 2.1.4 didn't make a change.

**Comment by RyanCavanaugh** [comment]
TypeScript doesn't do anything that could possibly cause the behavior you're describing. Once TS emits the .js code, it has no ability to change how the `instanceof` operator works depending on where the code is being run.

You'll need to narrow this down yourself - we cannot provide support for general programming problems where TypeScript happens to be involved.

**Comment by KoenT-IM** [comment]
OK, understood. At least that gives me a direction.

Should anyone else read this, and have ideas how to go about finding out where this could be coming from, I'd be interested to get some advice.
