### ISSUE TITLE
TypeScript 1.8: cannot return this from arrow function inside object literal that initializes class property

### ISSUE THREAD

**Issue by maxlk** [Microsoft/TypeScript#12911]
*DISCLAIMER: I didn't find information if 1.8 is still supported, hope that yes*

**TypeScript Version:**  1.8.10

**Code**
*SomeClass.ts*:
```ts
class SomeClass {
  prop = {
    fn: () => this
  }
}
```
For the file above tsc generates the following *SomeClass.d.ts*:
```ts
declare class SomeClass {
    prop: {
        fn: () => this;
    };
}
```

**Expected behavior:**
tsc should accept generated `.d.ts` file

**Actual behavior:**
tsc exits with error
`SomeClass.d.ts(3,19): error TS2526: A 'this' type is available only in a non-static member of a class or interface.`

**Comment by RyanCavanaugh** [comment]
This works in the current version of TypeScript. We don't backport fixes unless they are high severity and this wouldn't meet the bar for that.
