### ISSUE TITLE
TypeScript 2.1.4 - error compiling async/await with Promises typed as `this`

### ISSUE THREAD

**Issue by ryanwe** [Microsoft/TypeScript#12910]
**TypeScript Version:**  2.1.4

**Code**

```ts
interface Bar extends Promise<void> {
    foo(): this;
    // also repros with `foo(): Bar;`
}

const buggy = async (param: Bar) => {
    await param.foo();
};
```

**Expected behavior:**
In TypeScript 2.0.3 this code will compile successfully.

**Actual behavior:**
 In TypeScript 2.1.4 this code will not compile successfully and gives the error `error TS1058: Operand for 'await' does not have a valid callable 'then' member.`

**Comment by nevir** [comment]
FWIW, this crops up for the [knex](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/knex/index.d.ts) typings, too.  
(`QueryBuilder implements ChainableInterface implements Promise<any>`)

No explicit `this` references, but lots of self references to `QueryBuilder`
