### ISSUE TITLE
TS not indicating type missmatches

### ISSUE THREAD

**Issue by glazar** [Microsoft/TypeScript#12914]
**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)

**Code**

```
interface Input {
  text?: string;
}

const test = (input: Input): string => {
  return "";
};

test("test");
```

**Expected behavior:**
Type mismatch indicated.
It works if I make the Input Interface text member non-optional.
**Actual behavior:**
No type mismatch indicated.
It works if I make the Input Interface text member non-optional.

**Comment by wallverb** [comment]
It's because `string` is assignable to `{}`

```ts
const a:{} = "test"
```

Hence it is assignable to:
```ts
const a: { text?: string } = "test"
```

You might be interested in https://github.com/Microsoft/TypeScript/pull/12501 https://github.com/Microsoft/TypeScript/issues/1809

**Comment by RyanCavanaugh** [comment]
Duplicate #9841, etc.

Which search terms did you use before logging this? We're trying to reduce duplicates/questions and are curious what people are searching (and why they're not finding the existing issues) when logging bugs. Thanks!
