### ISSUE TITLE
Add generic versions of EventListener and EventListenerObject

### ISSUE THREAD

**Issue by FranklinWhale** [Microsoft/TypeScript#12918]
When `noImplicitAny` is `true`, the following code will not compile because "Parameter 'e' implicitly has an 'any' type.":

```ts
let x: EventListener = e => {
	doSomething();
};
```

I propose adding generic versions of `EventListener` and `EventListenerObject` to fix that:

```ts
interface EventListenerFor<T extends Event> {
    (evt: T): void;
}

interface EventListenerObjectFor<T extends Event> {
    handleEvent(evt: T): void;
}
```

**Comment by RyanCavanaugh** [comment]
How does adding those two declarations fix the original problem you described?

**Comment by FranklinWhale** [comment]
With the change:
```ts
let x: EventListenerFor<KeyboardEvent> = e => {
	// e is a KeyboardEvent
};
```

Without the change:
```ts
let x: EventListener = e as KeyboardEvent => {
	// Type assertion is required
};
```
Another benefit of using the generic version is that since the event type is specified to the interface, when the user moves the mouse point over `x`, IntelliSense will show `x` is `EventListenerFor<KeyboardEvent>`, rather is a simple `EventListener`.

**Comment by FranklinWhale** [comment]
@mhegazy Would you review the PR? Thanks!

**Comment by mhegazy** [comment]
looking at this again, I am not comfortable with the idea of having dummy interfaces in the global space just for a generic type parameter. we already have a couple of these for `NodeList` and `HTMLCollection`, but that is not a pattern we should propagate.

can you share some patterns you run into that requires this annotation?

**Comment by robrez** [comment]
As a fairly new user of typescript, I was trying to do something like this:

```javascript
    const listener: EventListenerOrEventListenerObject = (e: KeyboardEvent) => {
      console.log(e);
    };
    document.addEventListener('keydown', listener);
```

learned I have to do something like this instead:

```javascript
    const listener: (this: Document, ev: KeyboardEvent) => any = (e: KeyboardEvent) => {
      console.log(e);
    };
    document.addEventListener('keydown', listener);
```

Found this old thread because one of my "brute force try-a-thing" was to do `EventListenerOrEventListenerObject<KeyboardEvent>`

If there exists a core type, KeyboardEvent, the ergonomics here would be a bit nicer if there were a type `KeyboardEventListener` or a generic.  Maybe there exists such a thing and I've just been unable to find it?

**Comment by milesrichardson** [comment]
To me, it seems like unexpected behavior that `CustomEvent<T>` is generic, but `EventListener` is not. The `detail` property that only exists in `CustomEvent<T>` also adds friction.

FWIW, this is what worked for me (in case anyone else finds this comment via google in the next five years):

```typescript

interface EventListenerObjectFor<T extends Event> {
  handleEvent(evt: T): void;
}
interface EventListenerFor<T extends Event> {
  (evt: T): void;
}

type EventListenerOrEventListenerObjectFor<T extends Event> =
  | EventListenerFor<T>
  | EventListenerObjectFor<T>;

type CustomEventListener<EventPayload> = EventListenerOrEventListenerObjectFor<
  Event & Pick<Partial<CustomEvent<EventPayload>>, "detail">
>;

const someFunctionThatAddsAnEventListener = <EventPayload extends Event>(
  eventName: string,
  listener: CustomEventListener<EventPayload>,
) => {
  // ...
}
```
