### ISSUE TITLE
String.split in lib.d.ts should use a union, not overloads

### ISSUE THREAD

**Issue by sandersn** [Microsoft/TypeScript#12922]
**TypeScript Version:**  master

**Code**

```ts
function split(notSure: string | RegExp) {
  return foo.split(notSure);
}
```

**Expected behavior:**

No error

**Actual behavior:**

Error: "Argument of type 'string | RegExp' is not assignable to parameter of type 'RegExp'."

**Comment by Arnavion** [comment]
Is this the decision for overloads in general, given that there are many issues about making overloads automatically work with union types instead? #5766 #12837 #12885

**Comment by mhegazy** [comment]
duplicate of https://github.com/Microsoft/TypeScript/issues/5766

**Comment by mhegazy** [comment]
> Is this the decision for overloads in general, given that there are many issues about making overloads automatically work with union types instead? #5766 #12837 #12885

The current recommendation is to keep the overload list as short as possible. https://github.com/Microsoft/TypeScript/issues/12885 tracks doing something about unifying them or flagging them as errors.
