### ISSUE TITLE
Support "function-like" import()

### ISSUE THREAD

**Issue by jmalonzo** [Microsoft/TypeScript#12933]
The proposal for [function-like import()](https://github.com/tc39/proposal-dynamic-import) is currently in stage-3, and I think it'd be nice if Typescript will support it in future versions.

For example, one such project that already supports it is webpack which checks for import() as a code-splitting construct (deprecating System.import in v2 and replacing it altogether in v3). 

**TypeScript Version:**  2.0.10

**Code**
```ts
// A *self-contained* demonstration of the problem follows...

import('page/profile').then(() => /* load route */ );

```

**Expected behavior:**
The compiler allows the dynamic import syntax as above.

**Actual behavior:**
-> error TS1128: Declaration or statement expected.

**Comment by wallverb** [comment]
https://github.com/Microsoft/TypeScript/issues/12364

**Comment by jmalonzo** [comment]
Thanks @wallverb
