### ISSUE TITLE
Code Flow analysis truthy checks not working for literal booleans

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#12939]
**TypeScript Version:**  nightly (2.2.0-dev.201xxxxx)

**Code**

The following does not work
```ts
declare let foo: { hasError: true } | { hasError: false, value: any };
function test() {
  if (foo.hasError) return;
  foo.value; // Error
}
```
But the following does: 
```ts
declare let foo: { hasError: true } | { hasError: false, value: any };
function test() {
  if (foo.hasError == true) return;
  foo.value; // Error
}
```

**Expected behavior:**
No error in both examples

**Proof**
![image](https://cloud.githubusercontent.com/assets/874898/21217114/af83134c-c2fe-11e6-9cc3-7828782e61ba.png)
![image](https://cloud.githubusercontent.com/assets/874898/21217143/c7f896b8-c2fe-11e6-844c-459e5fa0234d.png)

BTW. Just wanted to say ... not related to this ... loving mapped types. So .. much .. power :rose:

**Comment by gcnew** [comment]
I've run into this as well. It happens only with `strictNullChecks` off. See https://github.com/Microsoft/TypeScript/issues/10564.

**Comment by RyanCavanaugh** [comment]
`strictNullChecks` is needed for this code to work because we can't rule out `null` or `undefined` as `hasError` values and thus can't narrow in the remainder of the function body

**Comment by basarat** [comment]
Closing in favor of https://github.com/Microsoft/TypeScript/issues/10564 :rose:
