### ISSUE TITLE
Extending HTMLElement still not working

### ISSUE THREAD

**Issue by ZanderBrown** [Microsoft/TypeScript#12949]
**TypeScript Version:**  2.1.4

**Code**

So the following JS works fine in Chrome (v55)

```javascript
class MyCustomElement extends HTMLElement {
    constructor() {
        super();
        this.foo = "bar";
    }

    doSomething() {
        console.log(this.foo);
    }
}

customElements.define("my-custom-element", MyCustomElement);
```

Which of course can be represented with the following TypeScript:

```ts
class MyCustomElement extends HTMLElement {
    foo: string;
    constructor() {
        super();
        this.foo = "bar";
    }

    doSomething() {
        console.log(this.foo);
    }
}

customElements.define("my-custom-element", MyCustomElement);
```

Except the compiled typescript won't run

*tsc* Output
```javascript
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};
var MyCustomElement = (function (_super) {
    __extends(MyCustomElement, _super);
    function MyCustomElement() {
        var _this = _super.call(this) || this;
        _this.foo = "bar";
        return _this;
    }
    MyCustomElement.prototype.doSomething = function () {
        console.log(this.foo);
    };
    return MyCustomElement;
}(HTMLElement));
customElements.define("my-custom-element", MyCustomElement);
```

In Chrome's console i see:

> Uncaught TypeError: Failed to construct 'HTMLElement': Please use the 'new' operator, this DOM object constructor cannot be called as a function.

**Comment by FranklinWhale** [comment]
Is it fine to change the compiler to target `es2015?

**Comment by DanielRosenwasser** [comment]
I get this error if I specifically try to `new` or call `document.createElement("my-custom-element")`, but I believe the former isn't supported. Pinging @justinfagnani who has a much more thorough background in this space.

**Comment by ZanderBrown** [comment]
Compiling with target `es2015` gives me:
```
class MyCustomElement extends HTMLElement {
    constructor() {
        super();
        this.foo = "bar";
    }
    doSomething() {
        console.log(this.foo);
    }
}
customElements.define("my-custom-element", MyCustomElement);
```
Which does run correctly:

![image](https://cloud.githubusercontent.com/assets/17074021/21238576/73da17d0-c2fb-11e6-8fdf-82e032a45e30.png)

**Comment by ZanderBrown** [comment]
Perhaps @robdodson & the polymer team can shed some light on the matter

**Comment by robdodson** [comment]
ah I think you're running into this issue https://github.com/webcomponents/custom-elements#known-issues

**Comment by DanielRosenwasser** [comment]
Yes, I suspected this is the issue. It's really unfortunate that something like `Reflect.construct` wasn't provided earlier on in runtimes.

For others running into this issue, I suggest using the shim that @robdodson linked to - thanks for the response Rob!

**Comment by ZanderBrown** [comment]
The shim does *mostly* work but unfortunately has issues with elements that extend other custom elements.

For example
```typescript
class A extends HTMLElement {
}
new A();
```
works fine however

```typescript
class A extends HTMLElement {
}
class B extend A {
}
new B();
```
does not.

Perhaps remove the reference to custom elements from the *What's New* document to avoid confusion especially as TypeScript doesn't even recognise the `customElements` object

**Comment by robdodson** [comment]
@ZanderBrown would you mind opening an issue on the custom elements polyfill? just off the top of my head... did you remember to call super() in your constructors?

**Comment by ZanderBrown** [comment]
Sure i'll do that and i called 'super' from the TypeScript code but obviously that gets translated by typescript

**Comment by justinfagnani** [comment]
Because custom elements basically require classes, I would recommend distributing ES6 to browsers that super it and only ship ES5 to older browsers. The shim is mostly for situations where you have a static server and incurs a performance penalty on browsers with native custom elements.

**Comment by justinfagnani** [comment]
@danielrosenwasser Reflect.construct doesn't since the issue, and I don't recommend using it to work around this issue. It's not a replacement for super() because it always allocates a new instance. Performance is very bad sometimes.

**Comment by lastmjs** [comment]
I'm still having issues with the shim:

I'm compiling the following to ES5:
```
class GPApp extends HTMLElement {
    constructor() {
        super();
    }
}

window.customElements.define('gp-app', GPApp);

```
And I get this error:
```
Uncaught TypeError: Class constructor DomModule cannot be invoked without 'new'
    at HTMLElement.StandInElement (native-shim.js:136)
    at CustomElementRegistry.window.customElements.define (native-shim.js:150)
    at dom-module.html:130
    at dom-module.html:135
```

**Comment by ZanderBrown** [comment]
Odd it's worked fine for me in quite a few projects now

**Comment by bartburkhardt** [comment]
I also get that error.

`Uncaught TypeError: Failed to construct 'HTMLElement': Please use the 'new' operator, this DOM object constructor cannot be called as a function`

**Comment by ZanderBrown** [comment]
have you used the shim?

**Comment by lastmjs** [comment]
Do we have any other options, or are there any plans to make this work for transpilation to ES5? This is going to hinder custom element adoption, at least in my case. I use TypeScript for all of my major projects, and once Polymer 2 is stable I'm not sure this is going to play out well.

**Comment by lastmjs** [comment]
@ZanderBrown Did you open an issue in the custom elements polyfill? I'd like to follow it.

**Comment by justinfagnani** [comment]
We know about this issue for the polyfill, which is why we wrote the native-shim, which is now shipped as the `custom-elements-es5-adapter. js`.

We did have a race condition with the polyfill loader and native HTML imports that was causing this error to still occasionally occur, but that should be fixed by always including the adapter when serving compiled code.

**Comment by lastmjs** [comment]
@justinfagnani I'm getting this when loading a basic Polymer 2 class transpiled with TypeScript:

```
custom-elements-es5-adapter.js:4 Uncaught TypeError: Class constructor DomModule cannot be invoked without 'new'
    at HTMLElement.k (custom-elements-es5-adapter.js:4)
    at CustomElementRegistry.window.customElements.define (custom-elements-es5-adapter.js:4)
    at dom-module.html:130
    at dom-module.html:135
```

**Comment by justinfagnani** [comment]
@lastmjs are you using the custom elements ES5 adapter? If not, that's expected.

**Comment by lastmjs** [comment]
Yes I am using it

**Comment by justinfagnani** [comment]
Oh yes, sorry didn't look at the stack trace closely enough. To use the adapter you need to compile the whole application. You can't mix ES6 and ES5 style classes.

**Comment by lastmjs** [comment]
All of the code that I supply is transpiled, and all I am including is `polymer.html`...I don't think I'm using anything that isn't ES5 once it hits the browser.

**Comment by lastmjs** [comment]
Let me get an example

**Comment by lastmjs** [comment]
I'm transpiling everything that I own, and I'm still getting this error:
```
custom-elements-es5-adapter.js:4 Uncaught TypeError: Class constructor DomModule cannot be invoked without 'new'
    at HTMLElement.k (custom-elements-es5-adapter.js:4)
    at CustomElementRegistry.window.customElements.define (custom-elements-es5-adapter.js:4)
    at dom-module.html:130
    at dom-module.html:135
```

HTML:
```
<link rel="import" href="../../bower_components/polymer/polymer.html">

<dom-module id="test-app">
    <template>
        Test app
    </template>

    <script src="test-app.ts"></script>
</dom-module>
```

TS source code:
```
class TestApp extends HTMLElement {

}

window.customElements.define('test-app', TestApp);
```
Transpiled TS:
```
            System.define(System.normalizeSync('components/test-app/test-app.ts'), `
                System.register([], function (exports_1, context_1) {
    "use strict";

    var __extends = this && this.__extends || function () {
        var extendStatics = Object.setPrototypeOf || { __proto__: [] } instanceof Array && function (d, b) {
            d.__proto__ = b;
        } || function (d, b) {
            for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
        };
        return function (d, b) {
            extendStatics(d, b);
            function __() {
                this.constructor = d;
            }
            d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
        };
    }();
    var __moduleName = context_1 && context_1.id;
    var TestApp;
    return {
        setters: [],
        execute: function () {
            TestApp = function (_super) {
                __extends(TestApp, _super);
                function TestApp() {
                    return _super !== null && _super.apply(this, arguments) || this;
                }
                return TestApp;
            }(HTMLElement);
            window.customElements.define('test-app', TestApp);
        }
    };
});
            `);
```

**Comment by lastmjs** [comment]
Wait a minute...is the Polymer project not transpiled to ES5? I'm seeing classes in the distribution code.

**Comment by justinfagnani** [comment]
It's not just the code you own, you have to transpile _everything_. The Polymer CLI does this for you: build complies anything imported, and serve compiles and JS requested.

**Comment by justinfagnani** [comment]
No, Polymer is not compiled, because custom elements require ES6 classes. You have to distribute ES6 and compile everything at the app level if necessary for the environment.

**Comment by lastmjs** [comment]
I don't use the Polymer CLI. I'm trying to leverage HTTP/2 as much as possible, so I don't do bundling. Isn't this going to be problematic? I don't think we should expect everyone to use the Polymer CLI tools and compile everything into one HTML file. What if people want to use their own build system, webpack, rollup, etc?

**Comment by lastmjs** [comment]
I understand your last point, but is there a problem with `polymer.html` being shipped as an already bundled and transpiled HTML import?

**Comment by justinfagnani** [comment]
You don't have to use the CLI, it just makes this part automatic. The key is that native custom elements require ES6 classes, so we distribute ES6. In the case that you want to ship compiled code to browsers that support custom elements, we provide the adapter to make ES5 work, but you need to compile all custom elements because the adapter calls constructors without new.

Sorry for the complications, but we've really, really tried to make this work.

**Comment by justinfagnani** [comment]
We can't ship Polymer pre-compiled because that would work _without_ that adapter.

**Comment by lastmjs** [comment]
Thanks for the explanation, I appreciate it. I'll figure something out :)

**Comment by justinfagnani** [comment]
Of course. For reference, what our build system does is follow all imports to find every file and compile if necessary. You can use the polymer-build library to get gulp streams of all dependencies to process on your own.

**Comment by puppetmaster3** [comment]
So I'm going to say that neither standard custom elements, nor Polymer 2 work w/ IE 11, without a very complex build process.  
Also, both have poor SSR. One way is to say, look, if you have IE 11, than SSR, such as AMP.
In my case, we want to develope nice webapps, we can't be playing w/ build tools.

**Comment by dpogue** [comment]
This is another case that would be fixed (or at least significantly improved) by #15397
