### ISSUE TITLE
Object literal: All `this` are implicitly any

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#12945]
**TypeScript Version:**  nightly (2.2.0-dev.20161215)

**Code**

(with `--noImplicitThis`)

```ts
class C {
    a() {}
    b() {
        this.a();
    }
}

const obj = {
    a() {},
    b() {
        this.a();
    }
}
```

**Expected behavior:**

No errors.

**Actual behavior:**

`a.ts(11,9): error TS2683: 'this' implicitly has type 'any' because it does not have a type annotation.`

**Comment by ahejlsberg** [comment]
Duplicate of #12785.
