### ISSUE TITLE
Inappropriate Type Narrowing on Object Properties?

### ISSUE THREAD

**Issue by gravaton** [Microsoft/TypeScript#12950]
**TypeScript Version:**  2.1.4

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
const suits = new Set<string>(['hearts', 'clubs', 'diamonds', 'spades']);
const cards = ['hearts', 'clubs', 'diamonds'];
const lastcard = ['spades'];

cards.forEach((cardsuit) => {
    suits.delete(cardsuit);
})
if (suits.size === 1) {
    suits.delete(lastcard[0]);
    for(let i = 0; i < lastcard.length; i++) {
        suits.delete(lastcard[i]);
    }
    lastcard.forEach((lastcard) => {
        suits.delete(lastcard);
    });
    if(suits.size === 0) {
        console.log('Its over!');
    }
}
```

Another, more concise example:

```ts
let a = { b: 1, lol: function() { this.b = 2 } };

if (a.b === 1) {
    a.lol();
    if (a.b === 2) {
        console.log('It changed');
    }
}
```
**Expected behavior:**
I would expect there to be no compilation errors here

**Actual behavior:**
Compilation errors:

`Operator '===' cannot be applied to types '1' and '0'`

I've done a lot of reading about type narrowing and what kind of assumptions will be made when functions are invoked, most notably the issue here: #9998

However, it seems to me that the difference here is that this is a property of an object being checked followed by the invocation of a function that is attached that same object.  The possibility that a function on an object might modify properties of that object is not particularly low and does not (I don't think?) constitute a bad design pattern.  Is this behavior correct?

**Comment by ahejlsberg** [comment]
It would be nice if we could do better here, but as the discussion in #9998 explains the cure would likely be worse than the disease. I don't think there is anything particularly different about your example, it is simply a case of control flow analysis not knowing whether a function call has side effects and therefore having to make a general assumption.

**Comment by gravaton** [comment]
It seems to me like objects and properties are a little less ambiguous than abstract functions?  For example:

```ts
let x: number = 10;

function changex() {
  x = 20;
}

if (x === 10) {
  changex();
  if (x === 20) { console.log('It happened'); }
}
```

This is an ambiguous case because there's no easy or innate linkage between the function `changex()` and the variable `x`.  Determining that the one impacts the other would be pretty complicated and not something we could guarantee.  For cases like this, I am totally in agreement with the conversation in #9998

However, that conversation doesn't really cover the object case which is what I'm discussing here.  To kind of reiterate the example I posted above:

```ts
const worker = new Worker();
if (worker.status === 'bad') {
  worker.cleanup(); // This will reset the worker
  if (worker.status === 'good') {
    console.log('Fixed it!')
  } else {
    throw('Worker in unrecoverable state')
  }
}
```

In this case `worker.status` is not just some variable floating around, it's a property of the `worker` object and invoking `worker.cleanup()` is invoking a function on the `worker` object.  This is a LOT less ambiguous than the situations being discussed in #9998!  I see that over there you commented:

> I think this pattern of suppressing type narrowing by accessing mutable state using a function is a reasonable one.

and that makes a lot of sense to me for the cases that were being discussed, but should this apply to things like `Array.length` and `Set.length`? Could a function that is a member of a particular object reset narrowings only on properties that are part of that same object?

**Comment by RyanCavanaugh** [comment]
@gravaton it's just more examples of the same thing. Consider code like this
```ts
type Foo = {
    printStatus(): void;
    thing: number | string;
}

const f: Foo = <any>null;
if (typeof f.thing === 'number') {
    f.printStatus();
    const n = f.thing * 2; // Error or no?
}
```
Disallowing the last line there because `printStatus` might have invalidated `f.thing` is just as counterintuitive as still believing that `worker.status` is the same value it was the last time it was observed.

It's really easy to write examples that make the case either way depending on what the variables are named.

**Comment by gravaton** [comment]
@RyanCavanaugh  I do see how naming and other subjective things can make it look like it "should" be one way or the other, and I suppose this is just one of those tricky problems that lacks a single solution that makes everyone happy.  So, to move to productive discussion, if this is the way things should be, what's the appropriate way for me to construct my code in situations like this?  Right now I've been doing something like

```ts
if(myObject.property === 1 as number) {
```

in order to, effectively, manually type the property and avoid the type narrowing.  Is this the best way to manage this issue in cases where objects that have properties that I will be conditionally modifying?

**Comment by RyanCavanaugh** [comment]
I think that's the best workaround (assuming you don't want to change `property` to a `getProperty` method)

**Comment by gravaton** [comment]
The particular code I'm working with is actually based on `Set.length` so it's probably easier to just be a little explicit with my conditional test than to override things on a core Node class :).  Thanks for the direction!
