### ISSUE TITLE
Show all fields of objects in completion list

### ISSUE THREAD

**Issue by normalser** [Microsoft/TypeScript#12969]
As usual - not sure if its TS, VSC or both

```ts
interface Test {
    foo: string
    'the-bar': number
}

declare var test:Test

test.// cursor here
```

Intelisense will show:

![image](https://cloud.githubusercontent.com/assets/1723815/21248028/f633dada-c301-11e6-843f-359ae0537425.png)

Would be great if it showed: 

![image](https://cloud.githubusercontent.com/assets/1723815/21248035/01794fe2-c302-11e6-8bed-f198abcdb051.png)

and turned into

```ts
test['the-bar']
```

if the option that does not work with dotted access is selected

**Comment by RyanCavanaugh** [comment]
This works in Visual Studio now. I believe the feature not working in VS Code is a feature request on their side
