### ISSUE TITLE
Feature request: Add Node.js integration tutorial

### ISSUE THREAD

**Issue by olalonde** [microsoft/TypeScript#12964]
I wanted to try typescript in a Node.js environment but documentation on https://www.typescriptlang.org/docs/tutorial.html is lacking. Maybe add a "Node.js" tutorial in the "Tutorial" submenu.

**Comment by cwebster2** [comment]
Can you clarify what exactly you are looking for?  The link you provided is within a Node.js environment.  It instructs you to install typescript via `npm` and then has you call `tsc` which will be located in you `node_modules/,bin/tsc`.  To me, that is a Node.js environment, managed via npm so I don't really follow what you want more than that.

**Comment by olalonde** [comment]
All the tutorials seem to be targeted at developers writing browser side JavaScript. I'd like a tutorial on setting up an express app for example. I believe there are some compiler options like `target` that would be especially helpful for Node.js code. Maybe just linking to a few open source libraries that use TypeScript on GitHub would help immensely.

**Comment by DanielRosenwasser** [comment]
I think this is reasonable. In general I'd like for us to have a decent Express tutorial, or something along those lines.

**Comment by elithrar** [comment]
To add to this (to whomever picks this up), some roadblocks I hit when converting an Node+ES6 project to Node+TS2.2:

* imports/require. TypeScript is stricter about namespaces (for lack of a better term) and importing from other modules - e.g. what is otherwise acceptable in ES5/ES6 is not in TypeScript.

```
// actions.js

let actions = new Map() // src/actions.ts(5,5): error TS2451: Cannot redeclare block-scoped variable 'actions'.
...
module.exports = { actions }
```
```
// index.js
const actions = require("./actions") // src/index.ts(3,7): error TS2451: Cannot redeclare block-scoped variable 'actions'.

...
if (actions.has(key)) { ... }
```

* Setting up tsconfig.json for Node: a solid, concrete example and/or explanation of options - e.g. `compilerOptions.target: es5 vs. es6` and `moduleResolution: "node"` and what they each mean.

A 2-3 module Express tutorial would be a solid base to start from.

**Comment by bowdenk7** [comment]
I'm working on one right now. Let me know if you're interested in reviewing and/or helping me make it better!

**Comment by elithrar** [comment]
Would love to review it!

**Comment by bowdenk7** [comment]
Sorry for the horribly slow response @elithrar... I lost track of this thread in my notifications >< https://github.com/bowdenk7/express-typescript-starter

**Comment by elithrar** [comment]
@bowdenk7 Hah! I also created a *really* simple starter (https://github.com/elithrar/node-typescript-starter) around the same time. Yours is definitely more complete, and definitely more useful if you're starting an Express app, whereas mine is a minimal as possible (e.g. just a base). 

(nice work)

**Comment by bowdenk7** [comment]
Nice! We should compare notes. I see you have `ts-node` in your devDependencies. How are you using that and what are your thoughts on the performance?

**Comment by RyanCavanaugh** [comment]
We're trying to scope down the TS documentation to "stuff only we know how to document". I think this is broadly covered by other resources on the internet by now.
