### ISSUE TITLE
Better completion support for generics extending interface with optional fields

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#12968]
_From @unional on December 15, 2016 22:49_

- VSCode Version: 1.8.0

```ts
interface X {
  a?: string
}

function boo(x: X): any
function foo<T extends X>(x: T): any
```
![image](https://cloud.githubusercontent.com/assets/3254987/21245098/87fb743c-c2d5-11e6-86c3-5d1ff5236955.png)

![image](https://cloud.githubusercontent.com/assets/3254987/21245105/906a3018-c2d5-11e6-88de-f1dcdef107f3.png)

_Copied from original issue: Microsoft/vscode#17351_

**Comment by mjbvz** [comment]
Just confirmed that this behavior still appears in the latest TS 2.2 insiders builds as well.

**Comment by Sammons** [comment]
With TS2.1.4 I am running into an issue with parameter type inference

```

const B = <T>(f: <R extends T>(a: R) => void) => {}
/* the parameter a's signature cannot be inferred, and is not required to be a type with the "type" property */
B<{ type: number}>((a) => {
  
})
```

Should I open this as a separate issue? It seems similar

**Comment by jwbay** [comment]
Interestingly,
```ts
foo({
  ''
});
```
Requesting completions inside the quotes returns 'a' as expected

**Comment by mjbvz** [comment]
This appears to be working for me in TS 3.8.0-dev.20200125

<img width="735" alt="Screen Shot 2020-01-27 at 7 26 47 PM" src="https://user-images.githubusercontent.com/12821956/73233332-04586800-413b-11ea-8848-fe3c805dc095.png">
