### ISSUE TITLE
Typescript 2.1.4 wrong compilation order on save with --outFile option on Windows Server 2012 RC

### ISSUE THREAD

**Issue by Cnnamon** [Microsoft/TypeScript#12977]
**TypeScript Version:**  2.1.4

I have installed Visual Studio 2015 Update 3, TypeScript 2.1.4.

``{
  "compileOnSave": true,
  "compilerOptions": {
    "noImplicitAny": false,
    "noEmitOnError": true,
    "removeComments": true,
    "sourceMap": true,
    "module": "amd",
    "outFile": "Scripts/appBundle.js"
  }
}
``

I use _references.ts file in my project root.

Note: Compile on build working as expected, compile on save does not!

**Expected behavior:**
When compiling on save files order must be like in _references.ts

**Actual behavior:**
When i am compiling on save one of the files from the _references.ts is pushed to the end and my app crashes.

**Comment by Cnnamon** [comment]
Actually this happens with all versions i tested (above 1.8.4)

Adding dummy file in certain place solves the problem temporarily, because it goes to the bottom of compiled javascript file.
All the times i tested only one file from my _references.ts config file goes to the bottom. Renaming or adding new files to the _references.ts file changes the compilation order.

**Comment by RyanCavanaugh** [comment]
Exact instructions + example files for reproducing this would be helpful
