### ISSUE TITLE
Make possible to group emitted files with single tsconfig

### ISSUE THREAD

**Issue by Pzixel** [microsoft/TypeScript#12975]
Currently we have a wonderful feature called `outFile` which allows to compile several `ts` files into single one. But here is a problem if we want, for example, two separated files. For example, we have following directory structure:

```
root
|___utils
   |___string.ts
   |___array.ts
|___components
   |___map
      |___types.ts
      |___helpers.ts
      |___core.ts
   |...
```
We always want to reference all utility functions and always want our component (`map` for example) be a single entity which should be referenced by one single `js` file.

For now i'm using several separated `tsconfig`, each one in its own folder but I'd like to have a single one. For example, option `compile all ts files in folder as one single js` or multiple `outFile` with list of `ts` that should be compiled in this output `js`. Implementation doesn't really matters, the only requirement is possibility to do such thing somehow.

**Comment by RyanCavanaugh** [comment]
I can't imagine a solution here that would be general-purpose enough to fit more than exactly your scenario while still not being more complicated than what you're already doing. But if other people can chime in with their scenarios maybe we could come up with something.

Q: Are you aware of config file inheritance?

**Comment by aleksey-bykov** [comment]
config file inheritance has it's limits, in my case i have 11 entry points (topmost scripts to start execution from), so i need to generate 11 different bundles using `outFile` which requires me to create and support 11 different configs
```
tsconfig.a.json
tsconfig.b.json
tsconfig.c.json
tsconfig.d.json
tsconfig.e.json
tsconfig.f.json
tsconfig.g.json
tsconfig.h.json
tsconfig.i.json
tsconfig.j.json
tsconfig.k.json
tsconfig.l.json
tsconfig.m.json
tsconfig.o.json
```

and we are planning to add 27 more


why won't you allow `files` `includes` `excludes` to be passed as arguments: #12958 ?

**Comment by aleksey-bykov** [comment]
another use case, for the sake of saving some time i to compile a only sub-tree of our 1500+ project starting at given root file, yet using the `compilerOptions` from the `tsconfig.json`

@RyanCavanaugh  how can i do it?

**Comment by Pzixel** [comment]
@RyanCavanaugh I'm aware about it, but for some reason it was not working. Now i assume becuase `tsconfig` file has another name (something.tsconfig.json for example), and it was stopping `tsc` from usage of this config. Compiler is pretty conservative with `tsconfig` naming, any extra character make file to be invisible to compiler system.

**Comment by mhegazy** [comment]
You could have multiple tsconfig.json files with different names, e.g. `tsconfig.outfile.json` and `backend.json`, and build them using `tsc --p tsconfig.outfile.json` for instance. the IDE always looks for the config file with `tsconfig.json` so this one can only be for your editing purposes. you can always use [configuration inheritance](http://www.typescriptlang.org/docs/handbook/tsconfig-json.html#configuration-inheritance-with-extends) to avoid duplication

**Comment by aleksey-bykov** [comment]
related #12958

**Comment by RyanCavanaugh** [comment]
There doesn't seem to be enough demand for this relative to the cost of just having the tsconfig files
