### ISSUE TITLE
Importing a package doesn't work when 'types' is set to a folder name with an index.d.ts

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#12974]
Here's the crux

./node_modules/foo/package.json
```json
{
    "types": "lib"
}
```
./node_modules/foo/lib/index.d.ts

```ts
export var x: number:
```

./hello.ts

```ts
import * as foo from "foo";
foo;
```

Note that this works if you change the `types` field to `lib/index` or `lib/index.d.ts`.

**Comment by mhegazy** [comment]
Why do we need to support this? this like 8 extra lookups on disk:
````
lib.ts
lib.tsx
lib.d.ts
lib.js
lib\index.ts
lib\index.tsx
lib\index.d.ts
lib\index.js
````

**Comment by aluanhaddad** [comment]
@mhegazy then you're really not going to like the feature request I'm about to post ;)

**Comment by DanielRosenwasser** [comment]
> Why do we need to support this? 

Because two other guys have filed the same issue in the past month. (#13406 & #13484)

**Comment by DanielRosenwasser** [comment]
> this like 8 extra lookups on disk:

Can't you check the file entries of the containing directory and then use that to decide which files to stat and then try to resolve? In other words:

```json
{
    "types": "lib"
}
```

1. Get containing directory of `lib` (`./`)
2. !Get directory contents of `./` (`./lib`)
3. !Check if `./lib` is a folder. (it is)
4. !Get directory contents of `./lib`: (`index.d.ts`, `index.js`)
5. !We found a `.d.ts`, so resolve to `./lib/index.d.ts` and load the file.

With this logic, you only hit the disk 4 times for this lookup, but I could see this being a limitation of functionality on `sys`.
