### ISSUE TITLE
Duplication of comment block at the start of the file in the generated JavaScript file

### ISSUE THREAD

**Issue by rkonstantinov** [Microsoft/TypeScript#12979]
**TypeScript Version:**  2.1.4

It seems that if the file starts with a comment (either block or line), running tsc will result in duplication of this comment in the generated JavaScript file. (This particular output seems to make our rollup setup to choke). If a new line is inserted before the comment, this cannot be observed.

A test repo can be found [here](https://github.com/rkonstantinov/ts-duplicate-comment-issue/tree/master).

Thanks.

**Comment by RyanCavanaugh** [comment]
Verified repro in `@next`

**Comment by marcghorayeb** [comment]
We're also experiencing this. If the first line in a file is a comment, it seems to move that comment after the first line of code.

**Comment by pselden** [comment]
Same here -- we have documentation generation that dies because of this.

**Comment by yuit** [comment]
The fix is in the master now. Give tomorrow nightly build a try!
