### ISSUE TITLE
Multicore compilation on roadmap?

### ISSUE THREAD

**Issue by pizza2code** [Microsoft/TypeScript#12987]
Greetings,

Does the Typescript team have any plans for enabling multicore compilation?  At my org, we're developing HTML5 applications with Typescript.  Our test test laptops have 8 cores and the dev machines 64+ cores.  It would be great to speed up builds by spreading compile jobs over multiple CPUs.

If not, I understand.  The priorities of web development are a bit different than applications, and our setup is a bit core-happy.  Just trying to get a sense of whether this is in the team's thoughts.

**Comment by gcnew** [comment]
Which company was that? I'd love to get one of your 64+ core machines.

**Comment by aluanhaddad** [comment]
> Does the Typescript team have any plans for enabling multicore compilation? At my org, we're developing HTML5 applications with Typescript. Our test test laptops have 8 cores and the dev machines 64+ cores. It would be great to speed up builds by spreading compile jobs over multiple CPUs.

Really nice to know that there are organizations that still understand the value of this. In so many jobs nowadays a workstation is considered a luxury which is just ridiculous </endrant>

**Comment by ZanderBrown** [comment]
`<mild-rant>` As a tag starting `</` is an end tag is it not implied that it is the end? also `<endrant></endrant>` look really odd `</mild-rant>`

**Comment by mhegazy** [comment]
This is not in the scope of the TS compiler; this is rather in the realm of  build orchestration/management tools. We achieve a similar result using [MSBuild](https://msdn.microsoft.com/en-us/library/bb651793.aspx) today in VS, and I am sure you can achieve the same with other build tools.
You can break up your build/test steps down into even single file compiles, and then let your build orchestrator/manager schedule them on whatever available resources.
