### ISSUE TITLE
Comments are lost between the lines

### ISSUE THREAD

**Issue by vitaly-t** [Microsoft/TypeScript#12985]
Input:

```ts
var a = 'some'
    // comment
    + 'text';

var b = 'some'
    /* comment */
    + 'text';
```

Expected output:

```js
var a = 'some'
    // comment
    + 'text';
var b = 'some'
    /* comment */
    + 'text';
```

Actual output:

```ts
var a = 'some'
    + 'text';
var b = 'some'
    + 'text';
```

TypeScript version: All.

**NOTE:** Flag `removeComments` has no effect in such cases.

**Comment by mwrouse** [comment]
Compile your TypeScript with the -c option, which preserves comments.

Or in your `tsconfig.json` file add: 
```json 
"removeComments": false
``` 
to your `compilerOptions` section.

**Comment by vitaly-t** [comment]
This option got nothing to do with it, it only works for other types of comments, but it doesn't work for comments between the lines as shown in the example.
