### ISSUE TITLE
Proposal: Expose `Undefined` type as an occupied bottom type

### ISSUE THREAD

**Issue by Eyas** [Microsoft/TypeScript#1298]
# Proposal

The TypeScript spec says that `Undefined` is the subtype of all types (see 3.2.6).

The keyword `Undefined` or `Nothing` should be added to the language to refer to the type of `undefined`.

`typeof(undefined)` currently yields `any`. This should be corrected to return the undefined type.

## Detail

See http://en.wikipedia.org/wiki/Bottom_type & http://james-iry.blogspot.com/2009/08/getting-to-bottom-of-nothing-at-all.html

The neat thing about structural typing TypeScript is that you don't need to explicitly think about generic type variance. Instead, when you use two generic implementations of non-identical types, then TypeScript uses the input and return types of the different methods and properties to figure out if these two generic types are subtypes or not.

One missing feature, however, seems to be a bottom Nothing/None/Nil type that is a subtype of all types. This then allows us to create neat "empty" types in generic.

**Comment by Artazor** [comment]
@Eyas I've proposed something similar: https://github.com/Microsoft/TypeScript/issues/3076 
what do you think about "bottom" as the type of the function that always throws?

**Comment by Eyas** [comment]
@Artazor interesting.

That would certainly be sound, as a function that always throws could be assigned to any type (just that if you evaluate it, you will fail). That makes for an interesting **unoccupied** bottom type (which is what `Nothing` in Scala is, for example).

It also seems that JavaScript already has an **occupied** bottom type: `typeof(undefined)`. If that were named (`Undefined`), then `Undefined` is indeed a valid subtype of all types.

It happens to be occupied: the value `undefined` is a proper possible value that is `Undefined`. That's fine. @metaweta proposes that and refers to this as a pointed set, which is fine.

If **could** be that a function that always throws is a subtype of **even** `Undefined`. I still think that having `Undefined` by a type has its benefits and addresses my use case concerns (structural generics). It seems like the use cases I'm thinking of don't require that extra 'super-bottom' type. I just wish TypeScript would properly handle the existing bottom type in JS :)

**Comment by Eyas** [comment]
Updating the title of this issue to more accurately reflect the proposal.

All of the machinery is in place to this proposal:

- the TypeScript spec agrees that `undefined` is the subtype of all types (see 3.2.6)
- the TypeScript type checker has an internal representation of the undefined type: `undefinedType` in checker.ts

We only need to be able to name this type.

**Comment by metaweta** [comment]
The spec should also clarify whether Undefined is a subtype of Null.

**Comment by mhegazy** [comment]
What is a use case of undefined or null types in the absence of non-nullable types?

**Comment by aleksey-bykov** [comment]
Presence of non nullable types doesn't rule out nullables, it only makes
them explicit, so that you never miss a check where it is needed.

**Comment by Eyas** [comment]
@mhegazy Its very useful in generics, even if the value is never actually used:

### Using `Undefined` in Optional Types

```ts
interface Optional<T> {
	HasValue: boolean;
	Value: T;
	
	Map<R>(m: (v: T)=>R): Optional<R>;
	Filter(f: (v: T)=>boolean): Optional<T>;
	FlatMap<R>(m: (v: T)=>Optional<R>): Optional<R>;
}

class Just<T> implements Optional<T> {
	HasValue = true;
	Value: T;
	
	constructor(value: T) {
		this.Value = value;
	}
	
	Map<R>(m: (v: T)=>R): Optional<R> {
		return new Just<R>(m(this.Value));
	}
	Filter(f: (v: T)=>boolean): Optional<T> {
		if (f(this.Value)) return this;
		else return None;
	}
	FlatMap<R>(m: (v: T)=>Optional<R>): Optional<R> {
		return m(this.Value);
	}
}

class Empty<T> implements Optional<T> {
	HasValue = false;
	Value: T = undefined;
	
	Map<R>(m: (v: T)=>R): Optional<R> {
		return None;
	}
	Filter (f: (v: T)=>boolean) {
		return None;
	}
	FlatMap<R>(m: (v:T)=>Optional<R>) {
		return None;
	}
}

var None = new Empty<Undefined>();
```

**Comment by metaweta** [comment]
@mhegazy, see also https://github.com/Microsoft/TypeScript/issues/1298#issuecomment-65109407

**Comment by jbondc** [comment]
@Eyas I'm not sure that's what you want, your example means undefined would be assignable to the bottom type. Smallest possible example here of what I think 'bottom' would mean:
https://github.com/Microsoft/TypeScript/compare/master...jbondc:bottom-type

Re-used the keyword 'return' to mean bottom.
```
const undefined = 1;

let a: return;
a = 1; // error
a = null;  // error
a = undefined;  // error
a = <any>1;  // error

type Bottom = return;

let b: Bottom = null; // error: Type 'null' is not assignable to type 'return
let b: Bottom = undefined; // error: Type 'undefined' is not assignable to type 'return'
```
It's really confusing because the compiler calls 'null' and 'undefined' types, they kind of are but find it easier to think of them as constants.

**Comment by aleksey-bykov** [comment]
@Eyas your example of `Optional` is at very least clumsy consider this (valid in 1.6):

```typescript
interface Some<a> {
    some: a
}
interface None {
    none: void;
}
type Optional<a> = Some<a> | None;
function isSome<a>(value: Optional<a>): value is Some<a> {
    return 'some' in value;
}
function isNone(value: None) : value is None {
    return 'none' in value && (<None>value).none == null;
}
var none : None = { none: undefined };
var value = Math.rand() > 0.5 ? { some: 'hey' } : none;
if (isSome(value)) {
    console.log(value.some);
} else {
    console.log('nothing');
}
```

**Comment by aleksey-bykov** [comment]
so basically you don't need a generic for `none` and it's a blessing because you don't need to jump out of your pants trying to model it with a generic

**Comment by Eyas** [comment]
`never`, introduced in #8652, is a strictly-better solution to most of the generic-based problems involving a bottom type. It is a true bottom type that is "below" `Undefined`.
