### ISSUE TITLE
PROPOSAL: Allow class name to be specified by a variable dynamically

### ISSUE THREAD

**Issue by streamich** [Microsoft/TypeScript#12980]
Like so:

```ts
var className = 'MySuperClass';
var MyClass = class [className] {};
console.log(MyClass.name); // MySuperClass
```

This is similar to how property names in object assignment can be variables:

```ts
var propName = 'MySuperProperty';
var obj = {
    [propName]: true,
};
console.log(obj); // {MySuperProperty: true}
```

Otherwise now all classes get `class_1` name or something like that:

```ts
var MyClass = class {};
console.log(MyClass.name); // class_1
```

**Comment by RyanCavanaugh** [comment]
Class expressions are an ES6 feature and there's not anything motivating TypeScript to add this kind of syntax (i.e. it doesn't improve static typing at all), so this suggestion should go to ES Discuss / the TC39 committee.
