### ISSUE TITLE
Allow ES6 export syntax inside namespaces

### ISSUE THREAD

**Issue by ToddThomson** [microsoft/TypeScript#12983]
I would like to be able to use export {} to reexport a named import within a namespace. Typescript does provide an export import for this, but it only works with import * as. I'd like to stay away from the export import syntax.

export var does work with import {} and should produce the same js as export import.
 
```
import { NamedImportA } from "./ModuleA";
import * as ModuleA from "./ModuleA";

export namespace ModuleANamespace {
    export var A = NamedImportA;
    export import A_2 = ModuleA.NamedImportA;

    // Would like to use
    export { NamedImportA }
    // or
    export { NamedImportA as A }
}
```

**Comment by RyanCavanaugh** [comment]
Isn't that just `export type NamedImportA = A;` / `export const NamedImportA = A` ?

**Comment by ToddThomson** [comment]
Yes, they all produce exactly the same emitted js code. 

It just all seems a bit muddled and inconsistent to me. I started out using using ```export { NamedImport }``` and ```export { NamedImport as Name }``` within the namespace, but that was not allowed. I then tried using ```export import``` within the namespace and that didn't work with the top level ```import { NamedImport }```, however it did work with the ```import * as```.

Since, as you pointed out, I can use ```export const A = NamedImportA;``` why then can't ```export { NamedImportA as A }``` be used in the namespace?

**Comment by RyanCavanaugh** [comment]
> why then can't export `{ NamedImportA as A }` be used in the namespace?

[The answer is always the same: because no one ever designed, specified, implemented, tested, documented and shipped that feature.](https://blogs.msdn.microsoft.com/ericlippert/2009/06/22/why-doesnt-c-implement-top-level-methods/)

**Comment by ToddThomson** [comment]
Sorry, I just wanted to construct "logical" modules in my code using Typescript. I don't need to have ES6 export syntax work inside namespaces to make this work.

**Comment by aluanhaddad** [comment]
I think this is really going to confuse people who are using UMD style modules. Let's say I'm using a package like Esri Leaflet and I want to use the `L.esri.Cluster.FeatureLayer` class. I can write
```ts
import {FeatureLayer} from 'esri-leaflet/cluster';
```
Then I need a utility method from Leaflet and one from EsriLeaflet
```ts
import L from 'leaflet';
import EsriLeaflet from 'esri-leaflet';
import {FeatureLayer} from 'esri-leaflet/cluster';
```
This just great. I can do it any way I want
```ts
import FeatureLayer = L.esri.Cluster.FeatureLayer;
import FeatureLayer = EsriLeaflet.Cluster.FeatureLayer;
import Cluster from 'esri-leaflet/Cluster';
import Cluster = EsriLeaflet.Cluster.FeatureLayer;
import Cluster = L.Esri.FeatureLayer.Cluster;
import FeatureLayer = Cluster.FeatureLayer;
import {FeatureLayer} from 'esri-leaflet/Cluster/FeatureLayer';
```
Never ending fun.
I would rather have fewer ways to write these, there are enough already and they have enough edge cases around declaration merging, augmenting, default exporting, export assignment and so on.

This isn't meant to be a rant. This was something I was writing a short time ago. As you can see I had a lot of different ways of importing the same thing at my disposal. Tutorials either used Babel, or used ES5 and there were a lot of examples using both forms that were relevant.

There was an issue recently, I couldn't find it in the search just now, that proposed nested destructuring of exported UMD modules..., kind of like ESM import aliases except using the destructuring `:` instead of `as`.

**Comment by ToddThomson** [comment]
Since this issue has been reopened, I'll give my thoughts...

After Ryan's response, I dug a bit deeper into the spec for ES6 module exports. Since ES6 imports and exports must be top level, I'd say that is the reason that the Typescript team does not currently provide export {} within a namespace. However, it does allow export var ( const, function, etc). So exports are not strictly forbidden within a namespace.

My initial point was perhaps this is a bit inconsistent. I can export within a namespace, but not how I would have liked. 

That said, given that ES6 imports and exports must be top level, I now feel that namespaces should not strictly allow exports. I use Typescript because I can write code now that adheres to the ES6 spec.

I have my reasons for wanting to have both internal and external modules in one package or bundle, but they are outside the norm.

**Comment by ToddThomson** [comment]
Looking at the emitted output for Typescript's ```namespace```, exports provide a mechanism for setting what is publicly accessible within the namespace object. I'm sure the Typescript team has it's reasons for this, but I'm not sure why a ```public``` modifier wouldn't work.

**Comment by RyanCavanaugh** [comment]
Closing due to lack of additional feedback and the broad shunning of namespaces by the TS community 😅

**Comment by aleclarson** [comment]
In the case of React components, this syntax would be useful for those of us who don't like prepending the component name to the name of our `Props` interface.

```tsx
export interface LongComponentNameProps {...}

export function LongComponentName(props: LongComponentNameProps) {
	return <div />
}
```

The proposed syntax would make refactoring one step easier. Rename the component and its props type is renamed as well.

```tsx
interface Props {...}

export function LongComponentName(props: Props) {
	return <div />
}

export namespace LongComponentName {
  export { Props }
}
```

As a bonus, I'm not required to import both the component and its props type. Instead, the props type comes with the component import.

```tsx
import { LongComponentName } from './LongComponentName'

interface Props extends LongComponentName.Props {...}

export function OtherComponent(props: Props) {
  return <LongComponentName {...props} />
}
```
