### ISSUE TITLE
Type["key"] inside Mapped type doesn't compile

### ISSUE THREAD

**Issue by AlexGalays** [Microsoft/TypeScript#12993]
**TypeScript Version:**  2.1.4

It appears we cannot use the Type["key"] notation inside a Mapped type?

**Code**

```ts
type Route<P, C> = {
  params: P
  children: C
}

// OK
type RouteParams = Route<{ id: string }, {}>["params"]

type RouteMap = Record<any, Route<any, any>>

type RouteMapParams<T extends RouteMap> = {
  [K in keyof T]: T[K]["params"] // Doesn't compile, even though T[K] should be of type Route
}
```

**Expected behavior:**
RouteMapParams should compile

**Actual behavior:**
error TS2339: Property 'params' does not exist on type 'T[K]'

**Comment by ahejlsberg** [comment]
It works with the nightly if you change the declaration of `RouteMap` to

```ts
type RouteMap = Record<string, Route<any, any>>
```

You could argue that `any` should behave the same as `string` when it is the constraint of a mapped type, but it currently doesn't and I'm not 100% sold that it should.

**Comment by AlexGalays** [comment]
Indeed it works now, thanks :)
