### ISSUE TITLE
Allow mixed explicit / inferred type parameters

### ISSUE THREAD

**Issue by AlexGalays** [microsoft/TypeScript#12992]
**TypeScript Version:**  2.1.4

Often, I'd like to manually specify a type parameter for a generic type, but let it infer the other type parameters:

e.g:

```ts
type Route<P, C> = { children: C }

function createRoute<P, C>(children: C): Route<P, C> {
  return { children }
}

const myRoute = createRoute<{ id: string, popup?: string }>(someComplexChildrenStructure)

// or perhaps 

const myRoute = createRoute<{ id: string, popup?: string }, *>(someComplexChildrenStructure)
```

The P type parameter cannot be inferred here because there are no values of type P on the right hand side. I sometimes use that to capture a user specified type that will have to be matched with other types later.

On the other hand, the type for C really should be inferred as it's a fairly complex type (object of objects of objects, etc)

There's the hack of asking for a fake value but it's verbose and is very inconvenient for optional types.

I've come across this limitation a few times now. I think it could be very useful.

**Comment by gcnew** [comment]
I'm interested in how are you using this and does it work correctly. As far as I know phantom types are not supported by TS (it uses structural checking after all).

**Comment by AlexGalays** [comment]
Yes it works as expected. It can be useful when used together with user defined type guards or just to carry some type for use somewhere else.
Guess I should read the FAQ one day :D
