### ISSUE TITLE
Implementing interface is not required for class children?

### ISSUE THREAD

**Issue by timpler** [Microsoft/TypeScript#12998]
Lets say I have some interface:

```
interface BaseInterface {
  test: boolean;
}
```

And then I have some class that implements it (note this class is extending another class)

```
class BaseModel extends Util.Object implements BaseInterface {
    // expected error as I dont have 'test' variable here.
}
```

Now I have another class that extend `BaseModel`:
```
class ChildClass extends BaseModel {
    // even if I dont have 'test' variable here, I'm not getting error
    // I should get it as I'm extending class that require it
}
```

Is it bug or am I doing something wrong?

**Comment by aluanhaddad** [comment]
The implementation is provided by the base class. Child classes inherit it automatically.

**Comment by timpler** [comment]
What if I want parent class to be `abstract` and require child classes to implement interface, or in case they override parent class, to keep overrides following parent interface?

**Comment by aluanhaddad** [comment]
Then you would decorate each method in the base class with the `abstract` modifier. Alternatively you could declare that the child class implements base class as supposed to be hurting from it, or both.

**Comment by mhegazy** [comment]
TypeScript has a structural type system. at every location where a type is expected, the value is checked it it matches the expected type. the check depends on the structure, and not if type has an `implements` clause. 

The only use of an `implement` clause, is to ask the compiler to give you an error if your class does not implement the interface. the class does not get any additional properties by implementing an interface.
