### ISSUE TITLE
How to pass a class value & type only once?

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#12999]
Sorry for asking a question here. Though I don't know a better place to ask ;).

I'm currently designing an API for a data class. Is there a way to pass the value and type of a class declaration in only one pass?

Instead of passing the `User` model below twice:
```ts
class User extends Model<any> {};

@Collection.attributes({
    model: User, // Pass 'User' as a value argument
})
class Users extends Collection<User, any> {}; // Pass 'User' as a type argument
```
Is there anyway I can write the `Collection` class so it only takes `User` as an argument only once, but still have access to both the type and the value?

As an example, it would be good if I could only declare `Users` collection as:
```ts
class Users extends Collection<User, any> {};
```
but still somehow have access to the value `User`.

Instead of using a decorator to pass the value:
```ts
@Collection.attributes({
    model: User, // Pass 'User' as a value argument
})
```
The solution doesn't need to be class also.

**Comment by aluanhaddad** [comment]
This works, but it doesn't preserve statics
```ts
class Model<T> { value: T; }

class User extends Model<any> { };

class Collection<T> {
  values: T[];

  model: new (...args) => T;

  constructor(...args: T[]) {
    this.values = args;
  }
}

class Users extends Collection<User> { };

const users = new Users();

const x: User = new users.model();

const userArray: User[] = users.values;
```

**Comment by tinganho** [comment]
@aluanhaddad your solution doesn't seem to pass the value only type?

I got a runtime error running your example:
```
Uncaught TypeError: users.model is not a constructor
```

**Comment by aluanhaddad** [comment]
Sorry, a workaround something like
```ts
class Model<T> { value: T; }

class User extends Model<any> { };

class Collection<T> {
  values: T[] = [];

  constructor(readonly model: new (...args) => T) {
  }
}

class Users extends Collection<User> { };

const users = new Users(User);

const x: User = new users.model();

const userArray: User[] = users.values;
```

**Comment by tinganho** [comment]
```ts 
class Users extends Collection<User> { };
const users = new Users(User);
```
I think this is still passing twice or even more, because you need to pass on every instance creation.

**Comment by aluanhaddad** [comment]
It is only being passed once per instantiation. But since the static type members cannot access type parameters and the class is generic, I don't see how to avoid that.

**Comment by aluanhaddad** [comment]
You can also do something more unorthodox, but actually I think rather elegant, which is to expose a subclass factory.
```ts
class Model<T> { value: T; }

class User extends Model<any> { };

class Collection<T> {
  values: T[];
  model: new (...args) => T;

  constructor(x: T, ...xs: T[]) {
    this.values = [x, ...xs];
    this.model = this.values[0].constructor as any;
  }

  static specialization<U>(model: new (...args) => U): new (...args: U[]) => Collection<U> {
    return class extends Collection<U>{
      model = model;
      values: U[] = [];
    };
  }
}
const Users = Collection.specialization(User);

const users = new Users(new User());

const x: User = new users.model();

const userArray: User[] = users.values;
```

**Comment by tinganho** [comment]
Thanks @aluanhaddad! I think I will go with the unorthodox method.
