### ISSUE TITLE
Suggestion: string interpolation

### ISSUE THREAD

**Issue by RyanCavanaugh** [microsoft/TypeScript#13]
Support ES6-style template strings

http://tc39wiki.calculist.org/es6/template-strings/

To be determined: Can we generate code for pre-ES6 targets? What does that look like?

**Comment by hdachev** [comment]
Hey Daniel,
This feature is a massive win, thanks for implementing.
Any chance on tagged templates getting es5 support? Is it not a more or less straightforward transformation - perhaps a `__template(tag, strings, values)` function emitted to package the string arrays and invoke the tag?
Thanks again!

**Comment by DanielRosenwasser** [comment]
Hey @hdachev,

Really glad that you've had a good experience from this feature. Downleveled ES3/ES5 tagged templates is actually on our agenda, and @ivogabe has put out PR #1589 to implement them. So far, things look good, and I think we'll be able to lock it in for 1.5.

**Comment by hdachev** [comment]
Thanks, great work guys!

**Comment by mindplay-dk** [comment]
So we have string interpolation, and support for tagged templates coming up in 1.5 - these are great features, but has anyone thought about adding support for an alternative file extension for template files?

Basically just Typescript, but with the contents of the file being emitted or returned somehow, and you have to use a tag to escape from output - I guess basically [EJS](http://www.embeddedjs.com/) for Typescript.

There are lots of fine template engines for JS, but what I'm after is something that will receive the same excellent IDE support Typescript gets - I haven't found anything like that for JS. (we're a rather large team considering a transition from PHP towards Typescript+Node, and a key missing feature right now is views/templates with proper IDE support, e.g. auto-complete for a view-model and view helper-functions.)

**Comment by basarat** [comment]
@mindplay I suspect this might just happen with angular support followed by angular support for server side next year.
