### ISSUE TITLE
"typeRoots" is ignored by "include"

### ISSUE THREAD

**Issue by monolithed** [Microsoft/TypeScript#13001]
**TypeScript Version:**  2.0.8
**Node Version:**  7.2.1
**OS** Darwin Kernel Version 16.1.0

**project**

```
types
views
   index.d.ts
```

**tsconfig.json**

```json
{
	"compilerOptions": {
		"typeRoots": [
			"./types",
			"./node_modules/@types"
		],

		"types": [
			"node"
		],

		"lib": [
			"es2017",
			"dom"
		],

		"target": "es2017",
		"module": "commonjs",
		"moduleResolution": "node",
		"noImplicitAny": false,
		"declaration": false,
		"sourceMap": true
	},

	"include": [
		"./views"
	]
}
```

**Actual behavior:**

`"typeRoots"` is ignored by `"include"`.

**Expected behavior:**

`"typeRoots"` is not ignored.

 I'm not sure if this is a bug or if it's by design, but I spent some time to identify my problem.

**Comment by mhegazy** [comment]
This tsconfig.json should not cause loading of any files from `types`. unless one of you files has a `/// <reference >` to one of the files in types.

**Comment by mhegazy** [comment]
see https://github.com/Microsoft/TypeScript/wiki/FAQ#why-is-a-file-in-the-exclude-list-still-picked-up-by-the-compiler for more info.

**Comment by monolithed** [comment]
@mhegazy, oh thanks, i meant to write `typeRoots`

**Comment by mhegazy** [comment]
not sure what you mean by "ignored" then. this looks like the expected behavior to me. You have specified to include only one types package which is `"node"`. not sure what you are expecting here. see http://www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types for more info.

**Comment by monolithed** [comment]
> not sure what you mean by "ignored" then.

ignored, overridden... It's not possible to apply `typeRoots`:

1. 

```json
{
	"compilerOptions": {
		"typeRoots": [
			"./types",
			"./node_modules/@types"
		],
	},

	"include": [
		"./views"
	]
}
```

```ts
import * as React from 'react';
                          ^TS2307 Cannot not find module "react"
```

2.

```json
{
	"compilerOptions": {
		"typeRoots": [
			"./types",
			"./node_modules/@types"
		],
	},

	"include": [
		"./types",
		"./node_modules/@types"
		"./views"
	]
}
```

```ts
import * as React from 'react';
                                            // works fine
```

But, I could not reproduce the problem with 2.1.4., so I think we should close this issue.
