### ISSUE TITLE
Installation instructions for the latest stable version cause unstable version on update

### ISSUE THREAD

**Issue by darthwalsh** [microsoft/TypeScript#13005]
**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)

Following the typescript README instructions to install the latest stable version causes unstable version to be installed on npm update.

**Code**

```bash
npm install -g typescript
npm list -g --depth=0
npm update -g
npm list -g --depth=0
```

**Expected behavior:**
As a user, I want to keep my stable installation of typescript up to date. If I installed version 2.1.4 and this is latest, I expect 2.1.4 to stay installed.

**Actual behavior:**
`npm install` installs typescript 2.1.4 but `npm update` installs 2.2.0-dev.20161216.

**Cause**
As far as I can tell, if you don't pin the npm version to some tag, npm update is expected to change from release to prerelease versions:
https://medium.com/@mbostock/prereleases-and-npm-e778fc5e2420#.98getlz8w

Users definitely don't want this behavior, but I don't think it's worth waiting for npm to fix the behavior of npm update;
https://github.com/npm/npm/issues/6557
https://github.com/npm/npm/issues/7215

**Fix**
The "stable" installation instructions should instead pin the version to `@latest`

    npm install -g typescript@latest

I've found these documentation locations that will need to be updated, maybe there's more:
* https://github.com/Microsoft/TypeScript/blob/master/README.md#installing
* https://www.typescriptlang.org/index.html#download-links
* https://www.typescriptlang.org/docs/tutorial.html

**Comment by aluanhaddad** [comment]
I cannot reproduce this
```shell
C:\>node --version
v7.2.0

C:\>npm --version
4.0.2

C:\>npm install --global typescript
C:\Users\Aluan\AppData\Roaming\npm\tsc -> C:\Users\Aluan\AppData\Roaming\npm\node_modules\typescript\bin\tsc
C:\Users\Aluan\AppData\Roaming\npm\tsserver -> C:\Users\Aluan\AppData\Roaming\npm\node_modules\typescript\bin\tsserver
C:\Users\Aluan\AppData\Roaming\npm
`-- typescript@2.1.4


C:\>tsc --version
Version 2.1.4

C:\>where tsc
C:\Users\Aluan\AppData\Roaming\npm\tsc
C:\Users\Aluan\AppData\Roaming\npm\tsc.cmd

C:\>



C:\>npm install --global typescript@latest
C:\Users\Aluan\AppData\Roaming\npm\tsc -> C:\Users\Aluan\AppData\Roaming\npm\node_modules\typescript\bin\tsc
C:\Users\Aluan\AppData\Roaming\npm\tsserver -> C:\Users\Aluan\AppData\Roaming\npm\node_modules\typescript\bin\tsserver
C:\Users\Aluan\AppData\Roaming\npm
`-- typescript@2.1.4


C:\>tsc --version
Version 2.1.4

C:\>where tsc
C:\Users\Aluan\AppData\Roaming\npm\tsc
C:\Users\Aluan\AppData\Roaming\npm\tsc.cmd

C:\>npm install --global typescript@next
C:\Users\Aluan\AppData\Roaming\npm\tsc -> C:\Users\Aluan\AppData\Roaming\npm\node_modules\typescript\bin\tsc
C:\Users\Aluan\AppData\Roaming\npm\tsserver -> C:\Users\Aluan\AppData\Roaming\npm\node_modules\typescript\bin\tsserver
C:\Users\Aluan\AppData\Roaming\npm
`-- typescript@2.2.0-dev.20161218


C:\>tsc --version
Version 2.2.0-dev.20161218

C:\>where tsc
C:\Users\Aluan\AppData\Roaming\npm\tsc
C:\Users\Aluan\AppData\Roaming\npm\tsc.cmd

C:\>
```

**Comment by darthwalsh** [comment]
@aluanhaddad I hit the problem after I ran `npm update`. The version selection logic seems to be different between `npm install` and `npm update`
