### ISSUE TITLE
how can i strip readonly via mapped types?

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#13000]
nightly build  of Dec 17

given
```typescript
interface Point {
   readonly x: number;
   readonly y: number;
}
```

i need a writable version of it

```typescript
type WritablePoint = Writable<Point>;
```

where `Writable` is 
```typescript
type Writable<T> = {
    // what goes here?
}
```

**Comment by raveclassic** [comment]
I'm running into exactly the same issue. 
For example, internal types of some complex tree structure should be immutable in public interface but for the sake of performance there should be a way for direct mutation in internal methods. It's a perfect place for a cast to a `Writable<T>` or even better `Mutable<T>`.

**Comment by aleksey-bykov** [comment]
Forget about it, readonly properties are useless due to #13002. Focus on something more rewarding.

**Comment by gcnew** [comment]
I don't know whether this will be of any use to you but:

```ts
interface Point {
   readonly x: number;
   readonly y: number;
}

declare const x: Point;
declare function stripReadonly<T>(x: Readonly<T>): T;
stripReadonly(x) // { x: number, y: number }
```

Also see https://github.com/Microsoft/TypeScript/pull/12589

**Comment by aleksey-bykov** [comment]
It would have been a good choice it we chose mutable version by default, so that only in few places had we use `Readonly <Point>`, but the thing with immutability is that it is contagious and has to be a default choice across most of your entities. It spreads from the top level entities all the way down to lower level entities, because say you can't have a readonly `Circle` with a mutable `centre` point.

So if I go this route I would have Readonly<...> everyehere. Which is a questionable return for investment.

**Comment by RReverser** [comment]
> So if I go this route I would have Readonly<...> everyehere. Which is a questionable return for investment.

@aleksey-bykov Not necessarily. Why can't you define them as following instead?

```typescript
interface WritablePoint {
  x: number;
  y: number;
}

type Point = Readonly<WritablePoint>;
```

and then use `Point` as before without changing references in most places of your code?

**Comment by aleksey-bykov** [comment]
@RReverser read my answer above, tldr: when readonly is a default choice, so it should be encoded with a shorter signature

**Comment by RReverser** [comment]
@aleksey-bykov Well, you define type just once anyway and in all the other places you can still use it with short name.

**Comment by aleksey-bykov** [comment]
@RReverser you are right, should have read you more closely, yes i guess it might be an option, need to sleep over it

**Comment by aleksey-bykov** [comment]
@RReverser i tried it, major problem is that type declarations cannot be inherited like interfaces

```typescript
type Point = Readonly<WritablePoint>
type Size = Readonly<WritableSize>
interface Box extends Point, Size { // <-- type error
}
```

**Comment by basarat** [comment]
interface Box extends Point, Size { // <-- type error

Think type & / intersection solve it 🌹

**Comment by RReverser** [comment]
Agree with @basarat, basically for inheriting type you'll need `type Box = Point & Size;` which looks less awkward IMO.
