### ISSUE TITLE
Proposal: Use `$` to prefix compiler generated variables instead of `_`

### ISSUE THREAD

**Issue by streamich** [Microsoft/TypeScript#13007]
As the title says: use `$` to prefix compiler generated variables instead of `_`.

From [old ECMA-262 standard](http://www.ecma-international.org/publications/files/ECMA-ST-ARCH/ECMA-262,%203rd%20edition,%20December%201999.pdf) paragraph *7.6*:

> The dollar sign ($) and the underscore (_) are permitted anywhere in an identifier. The dollar sign is intended for use only in __mechanically generated code__.

Now, this TypeScript code:

```js
for (var item of items) {
    
}
```

Will generated this ES5 code:

```js
for (var _i = 0, items_1 = items; _i < items_1.length; _i++) {
    var item = items_1[_i];
}
```

Instead, it could be like this:

```js
for (var $i = 0, $items_1 = items; $i < $items_1.length; $i++) {
    var item = $items_1[$i];
}
```

Or even maybe use `$$` to differentiate from jQuery.

The use case is that developers often use underscore to identify private/hidden variables and when looking though the generated code it is easier to differentiate them from the compiler generated ones if the compiler generated ones would be prefixed with `$` or `$$` instead.

**Comment by aluanhaddad** [comment]
Unfortunately no one paid attention and real-world JavaScript is littered with dollar sign prefixed identifiers. Besides it's arguable if these should be considered mechanically generated as they are meant to be readable by humans. At any rate it doesn't matter unless they conflict with other identifiers. Since this doesn't happen it's subjective at best which would be better.

**Comment by fgambino** [comment]
Another reason to hate jQuery.

Aside from that library, I've never see the dollar sign used. But it isn't uncommon to see underscores. +1

**Comment by aluanhaddad** [comment]
@fgambino Don't forget AngularJS

**Comment by fgambino** [comment]
Ah true... Very disappointing.

**Comment by streamich** [comment]
jQuery and Angular are just some client side libs but TypeScript is extensively used on desktop and server.

jQuery is dying, especially it is not that much used with TypeScript.

Angular is just one browser framework, and it seems that Google itself today invests more in Polymer.

**Comment by aluanhaddad** [comment]
@streamich It is not about compatibility it is just convention.

**Comment by mhegazy** [comment]
The choice of `_` was deliberate one. one of the [design goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals#goals) of the TypeScript project is:

> Emit clean, idiomatic, recognizable JavaScript code.

that is code that users would have written by hand. this is why the generated variable names are short, use letters when possible, and are seeded with the module name/ variable name, to make them relatable to the user defined name.
the `_` is also used as it is easier on they eye, and again looks like code users would have written by hand.
