### ISSUE TITLE
Incorrect `Object is possibly 'null'.` error inside `Promise.prototype.then`

### ISSUE THREAD

**Issue by kimamula** [Microsoft/TypeScript#13015]
**TypeScript Version:**  2.1.4 (2.2.0-dev.20161218 also)

**Code**

With --strictNullChecks,

```ts
interface Foo {
    prop: string;
}

function nullableFooPromise(): Promise<Foo | null> {
    return Promise.resolve(null);
}

nullableFooPromise()
  .then(nullableFoo => nullableFoo ? nullableFoo : { prop: 'foo' })
  .then(foo => console.log(foo.prop)); // this line raises an error
```

**Expected behavior:**
I expect this to compile (it does actually when I use typescript@2.0.8).

**Actual behavior:**
I get an error,
`index.ts(11,28): error TS2531: Object is possibly 'null'.`

**Comment by aluanhaddad** [comment]
This looks to be related to #13008. The overloads for `.then` are not declared in the right order.
