### ISSUE TITLE
Non-null assertion operator formatted incorrectly after parenthesis

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/TypeScript#13012]
**TypeScript Version:**  2.1.4  
**Visual Studio Version:** 2015 Update 3 

![image](https://cloud.githubusercontent.com/assets/1106823/21296156/b3d0b28c-c55c-11e6-99c3-a511a9b48816.png)

To reproduce, enter the snippet above and hit `Control+k, Control+d` in Visual Studio.

**Comment by flowmemo** [comment]
Maybe duplicate of #11676 ?

**Comment by mhegazy** [comment]
should be fixed by https://github.com/Microsoft/TypeScript/pull/13153
