### ISSUE TITLE
Types shipped with package not being picked up by Visual Studio

### ISSUE THREAD

**Issue by atrauzzi** [Microsoft/TypeScript#13010]
I've included this project as a dependency in `pacakge.json`: http://github.com/atrauzzi/protoculture

It brings in a bunch of other things (react) as well as corresponding `@types/*` packages where available.

The protoculture package however ships with types rather than needing them to be brought in separately, yet something about this is really confusing to Visual Studio.  My package's types don't have any hinting, yet React does and I can even control-click on the package to go to the `.d.ts` file in the `@types/react` package.

Seems like maybe right now Visual Studio/TS isn't looking in all the places it needs for type information?  FWIW, other editors including VS code seem to be able to intuit the types shipped as part of my package just fine.

Here's my `tsconfig.json`, just in case it's of interest:

```
{
  "compilerOptions": {
    "target": "es5",
    "module": "system",
    "moduleResolution": "node",
    "isolatedModules": false,
    "jsx": "react",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "declaration": true,
    "noImplicitAny": true,
    "noImplicitUseStrict": false,
    "removeComments": true,
    "noLib": false,
    "preserveConstEnums": true,
    "suppressImplicitAnyIndexErrors": true,
    "sourceMap": true,
    "outDir": "lib",
    "lib": [
      "es5",
      "dom",
      "es2015.iterable",
      "es2015.promise"
    ]
  },
    "include": [
      "src/Suite/*",
      "node_modules/**/*"
    ],
    "exclude": [
        "**/*.spec.ts"
    ],
    "compileOnSave": false,
    "buildOnSave": false,
    "atom": {
        "rewriteTsconfig": false
    }
}
```

The one thing I've done differently to what I've seen out there is that I've got `node_modules` included, which seemed to light everything up.  Advice or corrections always welcome.

**Comment by mhegazy** [comment]
what version of VS are you using? what version of the TypeScript for VS plugin? can you share your package.json?
