### ISSUE TITLE
Mutually referenced generic type constraints freeze compiler

### ISSUE THREAD

**Issue by masaeedu** [Microsoft/TypeScript#13011]
**TypeScript Version:** 2.1.4

**Code**

```ts
function prop<K extends string>(name: K): <T extends { [P in K]: U }, U extends T[K]>(obj: T) => U {
    return (obj) => obj[name];
}
 
let x = prop("name");
x({ name: 10 });
```

**Expected behavior:**
Running `tsc test.ts` should result in successful transpilation or compiler errors.

**Actual behavior:**
`tsc` never exits.

**Comment by mhegazy** [comment]
Should be fixed in `typescript@next`
