### ISSUE TITLE
Problems with symlinks on Azure with Docker

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#13026]
We don't have a good repro yet, but created an issue to track these investigations.

**Comment by mhegazy** [comment]
another docker issue, may or may not be related: https://github.com/Microsoft/TypeScript/issues/12748#issuecomment-265959565

**Comment by mhegazy** [comment]
seems like a duplicate of https://github.com/Microsoft/TypeScript/issues/13060
