### ISSUE TITLE
Emitted code for super() results in 'Branch not covered' in coverage reports.

### ISSUE THREAD

**Issue by Izhaki** [Microsoft/TypeScript#13029]
**TypeScript Version:**  2.1.4

**Code**

The `super()` call in the following code, results in ['Branch not covered' with Istanbul (see issue)](https://github.com/gotwarlost/istanbul/issues/690).

```ts
constructor( x: number, y: number, w: number, h: number ) {
    super(); // <- Throws 'Branch not covered'.
    this.rect = new Rect( x, y, w, h);
}
```

In Typescript 1.8 the `super()` call transpiled to:

```ts
_super.call(this);
```

But in 2.1.4 it transpile to:

```ts
var _this = _super.call(this) || this;
```

Which will obviously yield 'Branch not covered'.

Adding a test - or ignore instructions - just to ensure appropriate coverage does not feel right here, let alone will have to include some comments on the internals of typescript.

**Comment by RyanCavanaugh** [comment]
This is to support subclassing classes which themselves return different objects from `super`

**Comment by Izhaki** [comment]
@RyanCavanaugh. OMG, had she died, [Barbara](https://en.wikipedia.org/wiki/Liskov_substitution_principle) would turn in her grave.

Is this in the ES6 standard?

**Comment by RyanCavanaugh** [comment]
It's a thing (tm), unfortunately
```js
> class Tricky { constructor() { return { m: 4 } } }
class Tricky { constructor() { return { m: 4 } } }
[Function: Tricky]
> let t = new Tricky();
undefined
> t
{ m: 4 }
> class Mine extends Tricky { constructor() { super(); } }
[Function: Mine]
> let m = new Mine();
undefined
> m
{ m: 4 }
> m instanceof Mine
false
```

**Comment by DanielRosenwasser** [comment]
Also linking to https://github.com/SitePen/remap-istanbul/issues/106 in case that will fix the issue.

**Comment by DanielRosenwasser** [comment]
I haven't read through it all, but do the solutions at https://github.com/istanbuljs/nyc/issues/374 help at all?

**Comment by Bnaya** [comment]
For the reference,
on babel, i get 
![screen shot 2017-01-07 at 23 42 00](https://cloud.githubusercontent.com/assets/1304862/21745371/004a386e-d533-11e6-887a-e0ecc2b8d12b.png)
(when adding to the babel config)
"    auxiliaryCommentBefore: ' istanbul ignore next ',"

**Comment by mhegazy** [comment]
@Bnaya, this seems like a good feature to add. do you mind filing a new issue to track it.

**Comment by Bnaya** [comment]
I don't feel i know enough about it, i just gave the hint:)

**Comment by Izhaki** [comment]
Done.

**Comment by samvloeberghs** [comment]
@Bnaya wouldn't that ignore everything?! Seems so wrong to do :)

**Comment by Izhaki** [comment]
As mentioned in https://github.com/Microsoft/TypeScript/issues/13455#issuecomment-287900758, instead of the various workarounds proposed, it is better to simply stick to `es6` when producing the coverage report. [Here is an example how](https://github.com/Izhaki/gefri/commit/30f059184159db0c19a9b4d35aeff8d7b4722935).

**Comment by ben8p** [comment]
For the one using webpack and TypeScript configured to output ES5,
I made a little webpack loader:
https://www.npmjs.com/package/ts-es5-istanbul-coverage
Using it make sure you won't get the branch marked as not covered.
