### ISSUE TITLE
tsc -w should clear screen before each run

### ISSUE THREAD

**Issue by k0pernikus** [Microsoft/TypeScript#13020]
Run compiler in watch mode: `tsc -w`. Change some files, causing multiple compilations.

**Expected behavior:**

As a developer, I expect the output of `tsc -w` to be relevant and concise to the current runtime. It should show me the information only of the current run, stating that either the compilation was a success or fail with an error message.

**Actual behavior:**

The output of previous compilations is kept.

**Benefit:**

During development, seeing old output is redundant, noisy, and it also takes away if there are errors in the output as I am not alarmed to them right away. They could simply have been errors from the last run.

I have to manually enter new lines or check the timestamps. I have to parse the output what error messages relate to which run. I am discovering myself hitting enter multiple times to create distinguishable marks so that I better see the output of the next run. Sometimes I just cancel watch mode and run `tsc` multiple times manually while debugging an issue.
 
Another tool that has a similar feature to what I am proposing is [mocha with their min reporter](https://mochajs.org/#min).

**Comment by RyanCavanaugh** [comment]
Accepting PRs - should be straightforward. Add a `cls` method to `sys`; we'll take care of implementing it for `tsc.exe`

**Comment by GongT** [comment]
on linux, I have using this for a lone time:

```bash
function tscp {
        echo -en "\ec\0typescript compiling (source: $1)...\r"
        tsc -w -p "$1" | sed 's/^.*File change detected/\x1Bc\0/g'
}
```

cmd.exe also support "\x1Bc" ( <ESC>c ), at least on win10.

**Comment by mhegazy** [comment]
Fixed by https://github.com/Microsoft/TypeScript/pull/20389

**Comment by iffy** [comment]
How can I disable this?

**Comment by eile** [comment]
This is very disruptive for my setup. Please add an option to disable.
