### ISSUE TITLE
Mapped types break `for-in` loops with intersections

### ISSUE THREAD

**Issue by gcnew** [Microsoft/TypeScript#13023]
**TypeScript Version:**  nightly

The following used to work but is broken now.

**Code**
```ts
function extend<T, U>(base: T, ext: U): T & U {
    const retval = <T & U> {};

    for (const x in base) {
        // Error: Type 'T[keyof T]' is not assignable to type '(T & U)[keyof T]'.
        retval[x] = base[x];
    }

    for (const x in ext) {
        // Error: Type 'U[keyof U]' is not assignable to type '(T & U)[keyof U]'.
        retval[x] = ext[x];
    }

    return retval;
}
```

**Comment by ahejlsberg** [comment]
This is working as intended, the fact that it was previously allowed was a bug. A `(T & U)[keyof T]` is assignable to a `T[keyof T]`, but not vice versa. Consider:

```ts
type A = {
    a: string;
    x: { s: string };
}
type B = {
    b: string;
    x: { t: string };
}
```

The intersection `A & B` corresponds to:

```ts
type AB = {
    a: string;
    b: string;
    x: { s: string, t: string };
}
```

Neither property `x` from `A` or `B` is assignable to property `x` in `A & B` because of the deep merging.

**Comment by gcnew** [comment]
I agree that in the deep setting the new behaviour is the correct one, however it seems like a breaking change introduced in version 2.1.

**Comment by gcnew** [comment]
PS: shallow intersections are more natural to me. Will they ever be supported?

**Comment by gcnew** [comment]
The What's new documentation on [intersection types](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#intersection-types) also features the very same `extend` - nothing is mentioned about the deep nature of `&`. It was also used for the old definitions of `Object.assign`. I find it a massive breaking change from a logical perspective. Maybe intersection should be made shallow?

**Comment by weswigham** [comment]
@gcnew If you want "shallow intersections" following the logic of `Object.assign`, you want [spread types](https://github.com/Microsoft/TypeScript/issues/10727), and not really intersections.

**Comment by gcnew** [comment]
@weswigham Thank you! The major problem I'm after is that basically all the information and marketing of intersection types are incomplete at best (leaning to wrong). This has created a flawed mental model for everyone using them. This unfortunate state should be very explicitly explained and fixed in the new documentation. Also the TypeScript book and What's new should be retroactively updated.

I believe the revelation @ahejlsberg made is world breaking not only for me.

**Comment by ahejlsberg** [comment]
The original PR on intersection types, #3622, has all of the semantics described in a fair amount of detail.

**Comment by gcnew** [comment]
@ahejlsberg Yes, https://github.com/Microsoft/TypeScript/pull/3622 has the semantics described, however they are:
1) not really intelligible for average programmers
2) they are not covered in What's new / the TS book
3) even there the `extends` example is wrong
4) the TS team continuously used intersections in shallow situations

The `XYZ` example is the only hint, except for _Properties and Index Signatures_.

My proposal is to state the intended semantics clearly and add an appropriate notice on the pertinent resources. Otherwise people reading TS book / What's new will still be led astray.

**Comment by aluanhaddad** [comment]
I'm not sure I understand the notion of shallow intersections. 
I would expect the intersection to be as deep as the deepest common path between between the types in question. 
Maybe I'm missing something fundamental, but I don't see what else it could be.

**Comment by gcnew** [comment]
It seems Flow has taken the shallow path with the left operand being a base type and the right one an extension. [link](https://flowtype.org/try/#0C4TwDgpgBAglC8UDeAoK6oEMBcUDOwATgJYB2A5gNxoYAeuS+uBJFUAvteyqJFAEIJkNdACNmRMlRFR6yKMAmtyHLihQA3TISgbcMAGSDEAClIBXADaXcmUiACU1FAGMA9qQJYlUoRoB0mNTunsBQ4viSbIgBosEeXhC29n7+EJRQAPSZUBC0kC7AEAAmuYSEboSuCWF4PtG6-rT+eNWhCvUqMU3+Ydll5ZUoQA)

It is also what I had inferred form the TS documentation as nothing is said about intersections being deep and all the motivating examples being shallow. The inclusion of `extend` which is infamously  shallow (and also implemented in this way) doesn't help either. I believe this has been the reason for the many issues asking why the right hand intersection type doesn't override the properties on the left one.

From another perspective this is breaking the code in the official documentation. There are two routes of action, either the behaviour is changed to match the documentation, or the documentation is updated. Either way, there should be a notice clearing up the confusion and the relevant parts updated.
