### ISSUE TITLE
JavaScript files not compiled when a .d.ts definition file is provided

### ISSUE THREAD

**Issue by kunnix** [Microsoft/TypeScript#13021]
**TypeScript Version:**  2.1.4

**Zipped Code for easier repro:** [tsc-js-not-compiled.zip](https://github.com/Microsoft/TypeScript/files/660978/tsc-js-not-compiled.zip)

**Code**

```ts
// ./src/js-no-def.js

export let test = 'js-no-def';

// ./src/js-with-def.d.ts

export var test: string;

// ./src/js-with-def.js

export let test = 'js-with-def';

// ./src/main.ts

import * as jsNoDef from './js-no-def';
import * as jsWithDef from './js-with-def';
```

**Expected behavior:**

```shell
$ tsc ./src/main.ts --allowJs true --outDir ./out/ && ls -1 ./out/
js-no-def.js
js-with-def.js
main.js
```

**Actual behavior:**

```shell
$ tsc ./src/main.ts --allowJs true --outDir ./out/ && ls -1 ./out/
js-no-def.js
main.js
```

**Comment by mhegazy** [comment]
A declaration file is always considered as a "better" candidate than a `.js` file. A .d.ts file has more type information, and is smaller in size (no expressions). The automatic inclusion (tsconfig.josn including all files in the folder) and module resolution (following imports) would favor a .d.ts file over a .js file.
if you want this file to be transformed, pass it explicitly on the command line.

**Comment by kunnix** [comment]
But it results in `tsc` generating an output (in `outDir`) that can't be executed.

Do you confirm it's the expected behavior?

**Comment by mhegazy** [comment]
> But it results in tsc generating an output (in outDir) that can't be executed.

can you elaborate what you mean here by "can't be executed"?

**Comment by kunnix** [comment]
My expectation was that running `tsc` with the `--allowJs` option would resolve my `import`(ed) modules (both `.ts` and `.js`) and compile them to `outDir` in such a way that running my entry point with `nodejs main.ts` would work (modules are resolved properly).

Currently, it would throw an error:

```
Error: Cannot find module './js-with-def'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/tmp/tsc-js-not-compiled/out/main.js:3:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

*(I've made the repro steps available: [tsc-js-not-compiled-2.zip](https://github.com/Microsoft/TypeScript/files/662215/tsc-js-not-compiled-2.zip), see `repro.txt`)*

Can you confirm this is the expected behavior?

**Comment by mhegazy** [comment]
thanks for the clarification; the existence of the declaration file tells the compiler there is a file in the output with this name. so the emit is skipped.

**Comment by kunnix** [comment]
OK thanks for the explanation, my understanding of '.d.ts' files was that they were used to provide additional typing information to TypeScript about JavaScript files and modules, I wasn't aware they were also skipping relative-path JavaScript compilation.

I still find this behavior confusing, but I understand there might be reasons for it.

Feel free to close as "By design" :)

**Comment by mhegazy** [comment]
a .js and .d.ts provide a view of a file. the compiler will favor .js automatically. if it picked the .d.ts it will not pick up the .js. .d.ts files are not emitted, since there is nothing to write for them.

if you want your .js file to be transformed and emitted pass it explicitly, `tsc ./src/main.ts ./src/js-with-def.js  --allowJs true --outDir ./out/`
