### ISSUE TITLE
Writing declarations for libraries with polymorphic return types is difficult.

### ISSUE THREAD

**Issue by akdor1154** [Microsoft/TypeScript#13037]
To jump straight to an example, I'm trying to write typings for the JXON library: https://github.com/tyrasd/jxon .

The library exports, among other things, a function that converts a JS object to an XML document:
```ts
module.exports = {
   ...
   jsToXml(jsObject: any, ...): XMLDocument;
}
```

The library when used in browser uses the browser's native XMLDocument interface, and when used in Node uses that of `'xmldom'`. At present, there are two ways to represent this, each with significant drawbacks.
  - `jsToXml(jsObject: any, ...): XMLDocument & 'xmldom'.Document;`
    - requires browser projects to pull in `@types/xmldom`, and requires node projects to build with `lib: ['dom']`. Neither of these are requirements of the underlying library.
    - the return type is not accurately represented; native XMLDocument might have methods available that are not on `xmldom`'s implementation, and vice versa. ` XMLDocument | 'xmldom'.Document` is also not accurate.

  - `jsToXml<XMLDocumentImpl>(jsObject: any, ...): XmlDocumentImpl;`
    - requires library users to specify the generic parameter every time they call the function. This is pretty shitty. If the library exported a factory function it could at least be a single manual parameter specification, but this library does not work that way.

Am I right in my conclusion that there is no way to achieve a 'proper' declaration currently?

At first glance, what I think might be needed is some way to conditionally specify types based on other types being available, without introducing a dependency on those types. Shitty syntax strawman:
```ts

type XMLDocumentImpl =( exists(XMLDocument)  ) ? XMLDocument 
  : (exists('xmldom')) ? 'xmldom'.Document
  : CompileTimeThrow('dependency not satisfied')
```

Thoughts?

**Comment by RyanCavanaugh** [comment]
The union type seems like the correct representation - one or the other might be returned, and the only way to know is with extrinsic information. In the generic case where you don't know which, you certainly need a follow-up `if` to determine which case you're in; in the case where you're only writing for one platform, a type assertion to "add in" that additional knowledge is appropriate.

**Comment by akdor1154** [comment]
The problem with that is the dependencies. It means projects using this library can't be built unless `lib: dom` is available. Also it's a bit frustrating, as to me it seems the information to determine what is going to be used is definitely available at compile time.

**Comment by RyanCavanaugh** [comment]
The usual solution there is to declare the relevant type
```ts
declare global {
  interface XMLDocument { }
}
```
which will merge harmlessly with the DOM declaration (when present) or prevent a type error (when not present).

**Comment by akdor1154** [comment]
oh, that's a useful workaround. It's certainly helpful to me now, but if I publish these typings, is polluting the global scope with a declaration like this likely to be frowned upon? What about the analog for the `xmldoc` type, something like

```ts
declare module 'xmldoc' {
   interface Document
}
```

Again, will this pollute the global scope for users of this library?

**Comment by RyanCavanaugh** [comment]
If you do it that way, it won't merge with the global interface (i.e. that won't work).

Polluting the global NS with something that is likely to be there most of the time anyway isn't a big problem IMO

**Comment by akdor1154** [comment]
OK, thanks. I'll have a play around with that and see where it gets me. I've had a similar problem writing my own library that uses either `'node-fetch'` or `window.fetch`, again dependant on environment, so I'll try this in both places and see if it's adequate for me / library users. Thanks!

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
