### ISSUE TITLE
Constraints cannot be proven in mapped types combination

### ISSUE THREAD

**Issue by Igorbek** [Microsoft/TypeScript#13039]
**TypeScript Version:**  2.1.4 / nightly (2.2.0-dev.20161219)

**Code**

```ts
type A<T> = () => T;
type B<T, C extends A<T>> = C;
type As<Ts> = {
    [P in keyof Ts]: A<Ts[P]>;
};

type Failing<Ts, Cs extends As<Ts>> = {
    [P in keyof Ts]: B<Ts[P], Cs[P]>;
//                            ~~~~~ Type 'Cs[P]' does not satisfy the constraint 'A<Ts[P]>'.
};
```

**Expected behavior:**

No errors, the constraint has been proven

**Actual behavior:**

Error in `Failing` type at `B<Ts[P], Cs[P]>`: Type 'Cs[P]' does not satisfy the constraint 'A<Ts[P]>'.

**Note**

If I change `A<T>` to be just `T` (`type A<T> = T;`), all compiles just fine.

**Comment by aleksey-bykov** [comment]
might be related #8459 which presumably growing from #8397

**Comment by aleksey-bykov** [comment]
ha! don't downvote me, downvote the design team how is making typescript is the only language out there that sacrifices correctness for "convenience" of use, this is blatant and unprecedented

**Comment by RyanCavanaugh** [comment]
Guess what we're spending the swag budget on this year

**Comment by RyanCavanaugh** [comment]
Repro with some thing renamed / simplified a little
```ts
  interface Thing { blah };
  type B<C extends Thing> = { m: C };
  type ThingMap<M> = {
    [P in keyof M]: Thing;
  };

  type Failing<T, Cs extends ThingMap<T>> = {
    foo: B<Cs[keyof T]>;
  };

  type Passing<T> = {
    foo: B<ThingMap<T>[keyof T]>;
  };
```

**Comment by falsandtru** [comment]
@RyanCavanaugh Seems like your repro is fixed now, but @Igorbek 's repro still throws errors.

**Comment by aleksey-bykov** [comment]
https://github.com/Microsoft/TypeScript/issues/15957

> ... Guess what we're spending the swag budget on this year...

https://www.youtube.com/watch?v=hqAVuE524Gk&feature=youtu.be&t=1m12s

**Comment by mhegazy** [comment]
should be fixed in latest.
