### ISSUE TITLE
Allow type casts around shorthand property names

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [microsoft/TypeScript#13035]
Is there any reason shorthand property names (`{ a }`, etc.) don't allow type casting around the names? It would be a mildly useful feature.

**Code**

The following object literals are all intended to compile to `{ foo: foo }`:

```typescript
function take(arg: { foo: string }) { }

let foo: string;

// Allowed
take({ foo });
take({ foo: foo });
take({ foo: foo as string });
take({ foo: <string>foo });

// Syntax errors
take({ <string>foo });
take({ foo as string });
```

**Expected behavior:**
These should all compile to the same thing.

**Actual behavior:**
The lines with type casting in the names are syntax errors.

**Comment by JoshuaKGoldberg** [comment]
I've found this variants of `catch(error)` come up once in a while and get flagged by TSLint for unsafe `any` usage without type casts:

```typescript
try {
    return {
        data: riskyOperation(),
        succeeded: true,
    };
} catch (error) {
    return {
        error: error as Error,
        succeeded: false
    };
}
```

**Comment by RyanCavanaugh** [comment]
Somewhat wurprised at the lack of feedback here, but in practice this isn't a huge annoyance for me when I encounter it so maybe that makes sense. I think we want to stay well-clear of this syntactic space to keep room for future TC39.
