### ISSUE TITLE
Enums can not be used for index signature types

### ISSUE THREAD

**Issue by Yuudaari** [Microsoft/TypeScript#13042]
**TypeScript Version:**  2.1.4

```ts
export interface UserInterfaceColors {
    [index in UserInterfaceElement]: ColorInfo;
}
export interface ColorInfo {
    r: number;
    g: number;
    b: number;
    a: number;
}
export enum UserInterfaceElement {
    ActiveTitleBar = 0,
    InactiveTitleBar = 1,
}
```

**Expected behavior:**
No errors will be thrown.

**Actual behavior:**
`index in UserInterfaceElement` throws the error `Type 'UserInterfaceElement' is not assignable to type 'string'`

This is a regression caused by #12425. The change makes sense, but there are very valid use cases for supporting enums in index signatures.

For another use case, in a project I'm working on, we use an enum to list all types of items. We have a function that takes an object with the enum values as keys, and data as values.

```ts
function loadItemData (data: { [index in ItemType]: string }): void;
```
A workaround is to use `index: number`, but then it's not enforced that you have to use a valid ItemType as a key.

**Original Issue**: #2491

**Comment by aleksey-bykov** [comment]
can we allow `string & Whatever` for index signatures too?

**Comment by RyanCavanaugh** [comment]
Approved.

# Note that this will not cause nominal enforcement of enum index expressions!

Specifically, ` [index in UserInterfaceElement]: ColorInfo;` will eagerly reduce to `"0" | "1" : ColorInfo`, so indexing by any other 0- or 1-valued enum value will *not* cause an error.

**Comment by amitbeck** [comment]
Thanks for handling this! Waiting for the fix 👍🏻

**Comment by sandersn** [comment]
Fix is up at #18346, although I think we'll need to discuss this at a design meeting before merging it.

**Comment by augusto-moura** [comment]
So, this issue isn't actually fixed right?
#18346 was closed without merging

There's any ongoing work for fixing it?

**Comment by amitbeck** [comment]
@augusto-moura Looks like it's been moved from milestone [TypeScript 2.6](https://github.com/Microsoft/TypeScript/milestone/53) to [TypeScript 2.7](https://github.com/Microsoft/TypeScript/milestone/56) as seen above 😞

**Comment by yordis** [comment]
@sandersn do you know when could we have this released?

**Comment by aselbie** [comment]
@yordis Not sure, but looks like it got bumped back to 2.8, so probably at least another 3 months.

**Comment by yordis** [comment]
😭

**Comment by kompot** [comment]
I'm not sure why and how but it started working for me (2.7.1).

So a long awaited (by me ;) feature of enum exhaustive checking finally works.

Given
```
enum X {
  Y = 'y',
  Z = 'z',
}

type A = { [TKey in X]: string };
```

the following is ok

```
const a: A = {
  [X.Y]: 'x',
  [X.Z]: 'x',
}
```

but this is compile time error

```
const a: A = {
  [X.Y]: 'x',
}

```

**Comment by Yuudaari** [comment]
That's because you're mapping the enums to string values. You're really just using strings as keys. This issue is for the use of numeric enum entries (which would allow auto-assigned enums to work as well)

As far as I know, it's worked via string since `in` and string enums were both present in the language.

**Comment by kompot** [comment]
Well, it definitely didn't work like 6 months ago when I was banging my head trying to get some concise way of exhaustive enum checking. I understand that this is a different issue, yes.

**Comment by bsdunx** [comment]
```typescript
        const descriptor = ({
            [UnitType.PLAYER as number]: Player.descriptor,
            [UnitType.MONSTER as number]: Monster.descriptor
        })[type]
``` Doing it like so may help some in the interim

**Comment by mhegazy** [comment]
Should be fixed by https://github.com/Microsoft/TypeScript/pull/23592

**Comment by gyandeeps** [comment]
Was this actually fixed by #23592 ?
Using TS 2.9.1,

```.ts
enum Test {
    A = "a",
    B = "b"
}
export interface PhaseApi1 {
    [x in Test]: () => void;
}
```

still have issues

```sh
* A computed property name in an interface must refer to an expression whose type is a literal type or a 'unique symbol' type.
* A computed property name must be of type 'string', 'number', 'symbol', or 'any'.
* Cannot find name 'x'.
```

[Playground link](https://www.typescriptlang.org/play/index.html#src=enum%20Test%20%7B%0D%0A%20%20%20%20A%20%3D%20%22a%22%2C%0D%0A%20%20%20%20B%20%3D%20%22b%22%0D%0A%7D%0D%0Ainterface%20PhaseApi1%20%7B%0D%0A%20%20%20%20%5Bx%20in%20Test%5D%3A%20()%20%3D%3E%20void%3B%0D%0A%7D%0D%0A%0D%0A)

**Comment by mhegazy** [comment]
```ts
enum Test {
    A = "a",
    B = "b"
}
type PhaseApi1 = {
    [x in Test]: () => void;
};
```

**Comment by timkinnane** [comment]
Just a postmortem FYI for anyone who's gone through what I did, trying for hours to solve this with all manner of type rejigging to remove index signature errors... Make sure your IDE linter has the latest version of Typescript. Those errors might not actually be errors at all.

+1 for the 😭 reaction option.

**Comment by aboyton** [comment]
@mhegazy Any reason that this works for `type` and not `interface`? I know it's easy to use one over the other but it seems a strange restriction.

**Comment by cbengtson85** [comment]
I also tried 
```enum Test {
    A = "a",
    B = "b"
}
type PhaseApi1 = {
    [x in Test]: () => void;
};```
in TS v 2.9.1 and getting an error not assignable to type string

**Comment by VitamintK** [comment]
It's unlikely that this happens to anyone else but me, but if you're trying to figure out why the fix isn't working for you, check that you spelled your enum correctly.

**Comment by bgl-tand** [comment]
This doesn't solve this case when you have different interfaces for each enum key.

`interface foo {[EnumX.A]: InterfaceA[], [EnumX.B]: InterfaceB[], [EnumX.C]: InterfaceC[]}`

The above code will complain about an index signature when trying to reference an object with square bracket notation. 

`type foo = {[key in EnumX]: InterfaceA[] | InterfaceB[] | InterfaceC[]}`

This solution isn't very helpful as the type then needs to be further examined to figure out what it is.

**Comment by psxvoid** [comment]
My question may be partially related to this issue but what about *generics*?

Currently it's possible to define a string map interface:
`export interface IStringMap<T> { [key: string]: T; };`

But it's not possible to specify a generic `const enum` constraint for an object. Let's say I'd like to define a type similar to IStringMap<T> interface but instead of using string key I'd like to restring it to const enums. Here is an example:
``````
const enum Numbered {
    ValueZero,
    ValueOne
}

// works:
export type NumberMap<TKey extends Numbered, TValue> = { [key in TKey]: TValue }
let nmap: NumberMap<Numbered, string> = {
    [Numbered.ValueZero]: 'zero',
    [Numbered.ValueOne]: 'sdf',
}
``````
But it seems like it's not possible to specify any const enum as a generic constraint:
``````
export type ConstMap<TKey extends **???**, TValue> = { [key in TKey]: TValue }
``````

It would be nice to do this:
``````
let nmap2: ConstMap<Numbered, string> = {
    [Numbered.ValueZero]: 'zero',
    [Numbered.ValueOne]: 'one',
}
``````
Logically, if you can use `string | number` as a key then why can't you specify a generic constraint that directly convertible to it?

**Comment by kg-currenxie** [comment]
> ```ts
> enum Test {
>     A = "a",
>     B = "b"
> }
> type PhaseApi1 = {
>     [x in Test]: () => void;
> };
> ```

Is there a way to make either key optional?

**Comment by Yuudaari** [comment]
@kg-currenxie 
```ts
type PhaseApi1 = {
    [x in Test]?: () => void;
};
```
