### ISSUE TITLE
Function with overloads that uses a union type parameter in implementation function throws error

### ISSUE THREAD

**Issue by chase-smith** [Microsoft/TypeScript#13041]
**TypeScript Version:**  both 2.1.4 and nightly (2.2.0-dev.20161219)

**Code**

```ts
function func(foo: string): number;
function func(foo: number): number;
function func(foo: any): number {
    return 0;
}

function func2(bar: number): number;
function func2(bar: string): number;
function func2(bar: any): number {
    return func(bar); // no problem here
}

function func3(bar: string): number;
function func3(bar: number): number;
function func3(bar: string | number): number {
    let v = func(bar); // error here
    return v;
}
```

**Expected behavior:**
There should be no issue with the call in `func3`.
**Actual behavior:**
```
error TS2345: Argument of type 'string | number' is not assignable to parameter of type 'number'.
  Type 'string' is not assignable to type 'number'.
```

This seems to be in direct contradiction to what the TS GitHub wiki says about function overloading, and the impact of the shape of the implementation function on the allowed types of the function:
![image](https://cloud.githubusercontent.com/assets/18446539/21334850/0acd8416-c620-11e6-8a1f-4ea83ba42593.png)

**Comment by RyanCavanaugh** [comment]
Duplicate #1805
