### ISSUE TITLE
Type inference with for...in

### ISSUE THREAD

**Issue by johnfn** [Microsoft/TypeScript#13046]
I would expect the following code to typecheck and work:

```
const x = { a : 1, b : 2 };

for (const foo in x) {
    console.log(x[foo]);
}
```

However, it gives an error that `x` has no index signature.

The problem appears to be that `foo` is not inferred to be of type `keyof (typeof x)`. If I do the following, there are no errors:

```
const x = { a : 1, b : 2 };

for (const foo in x) {
    console.log(x[foo as keyof (typeof x)]);
}
```

Shouldn't `x` be inferred to be that type?

(Apologies if this issue already exists somewhere. I searched pretty hard and I could not find it.)

-----

It also seems weird that something like this infers the type of `foo` properly. We have _less_ information about `x`, yet our type constraint on `x` is stricter.

```
function test<T>(x: T) {
    for (const foo in x) {
        console.log(x[foo]);
    }
}
```

**Comment by RyanCavanaugh** [comment]
#12314, #12988

**Comment by johnfn** [comment]
Ah, that's pretty tough for something which developers do all the time. 

Are there any workarounds for iterating over and indexing an object? One workaround I see is to give all my types index signatures, but I have a habit of defining object literals and allowing the type inference to take over.

**Comment by RyanCavanaugh** [comment]
`any` (non-strict) or `{ [k: string]: { } }` (strict) are the types you should assert `x` to in this case.

Since we don't know (in general) that `x` doesn't actually reference a subtype with other keys of different types, there's no known-correct type for us to produce for `x[k]` in a `for(k in x)`.
