### ISSUE TITLE
Ignore certain variables when using --noUnusedLocals

### ISSUE THREAD

**Issue by cvle** [Microsoft/TypeScript#13048]
I want to use destructuring of objects while being able to ignore certain parameters. But with `--noUnusedLocals` I get an error. 

~~~typescript
const {
  children,
  active: _a,
  ...rest,
} = props;
~~~

~~~bash
'_a' is declared but never used.
~~~

I formerly used the tslint rule `no-unsued-variable` which supported ignoring any variable having a certain pattern, e.g. any name starting with a `_`. As `tslint` deprecated `no-unsued-variable` in favor of  `noUnusedLocals` I cannot rely on `tslint` anymore.

Is this something which can be supported, or do I need to port over something like `lodash.omit`?

**Comment by RyanCavanaugh** [comment]
Duplicate #12766 ?

**Comment by basarat** [comment]
With nightly, tested in alm : 

@cvle if you do it at the root level it errors on all. Within a function it only errors if `rest` is not used: 

![image](https://cloud.githubusercontent.com/assets/874898/21370821/e915ded4-c761-11e6-841a-969f11097b87.png)

I'm not the best judge of what would be *expected*, but I can see ways of suppressing global version but just wrapping and calling a function :rose:

**Comment by DanielRosenwasser** [comment]
@cvle with @12766, you shouldn't need to rename your parameter to `_a`.

@basarat I'm not seeing that in my own editor:
![image](https://cloud.githubusercontent.com/assets/972891/21372790/5426402c-c6ce-11e6-9945-eccadef30da0.png)

**Comment by basarat** [comment]
@DanielRosenwasser sorry I had an export so the file was a module. Complete example: 

```ts
declare let props: any;
const {
  children,
  active: _a,
  ...rest,
} = props;
function foo() {
  const {
    children,
    active: _a,
    ...rest,
  } = props;
}

export const asdf = 123;
```

![image](https://cloud.githubusercontent.com/assets/874898/21373210/31482ffe-c771-11e6-9911-2b5dc9ebb45d.png)

**Comment by basarat** [comment]
_interesting_ that its different for function vs. module used variables :rose:

**Comment by DanielRosenwasser** [comment]
Closing in favor of #13076.
