### ISSUE TITLE
Array.join has improper typing in .d.ts file

### ISSUE THREAD

**Issue by markboyall** [Microsoft/TypeScript#13049]
To reproduce:

class X {}
let arr: X[] = [];
arr.join("");

Expected behaviour: compiler error.
Actual behaviour: compiler accepts.

The array.join function should only be available for arrays of strings.

**Comment by Aarilight** [comment]
All arrays have the `join` method in JS. The type shouldn't reflect what's exposed natively?

**Comment by markboyall** [comment]
The output is utterly meaningless in every respect, so no, it certainly should not.

**Comment by HerringtonDarkholme** [comment]
IMHO`join` has its unique usage in Array if elements have proper `toString` method. Joining number, symbol and string are quite common, such as concatenating template code. Forbidding that will be a huge breaking change.

Also, I'm afraid you cannot express a method that can be only used in some specific instance of a class. You might need introduce a new `StringArray` interface, though.

**Comment by markboyall** [comment]
I considered doing that, but we thought that it was not worth having to maintain our own copies of lib.d.ts to fix this issue.

Since there is absolutely no way to determine if the toString() method is proper or not, forbidding it seems like the only safe way to go.

**Comment by RyanCavanaugh** [comment]
This would be a fairly substantial breaking change, and I think you're going to get a **lot** of people who object to disallowing this on `number[]`s. But we can consider it.

**Comment by markboyall** [comment]
I'm more concerned about forbidding it for user-defined random interfaces and class types. Permitting it on, say, (string | number)[] would be fine.

**Comment by RyanCavanaugh** [comment]
`Array#join` is the same as `"" + arr[0] + sep + arr[1] + ...` which we allow for any array type already. It'd be inconsistent to have stricter rules for `join` than for regular string concatenation.

**Comment by markboyall** [comment]
That sounds less like an argument for not fixing join() and more like an argument for also fixing string concatenation.
