### ISSUE TITLE
Improve google ranking for TS Playground

### ISSUE THREAD

**Issue by normalser** [microsoft/TypeScript#13055]
Not sure if you can do anything - I am not an SEO expert - but it would be good to improve google ranking for `TS Playground`. Right now it offers some bizarre results (https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=ts%20playground - proceed at your own risk) and real TS Playground is on 3rd page.

Seems like `<meta/>` with `keyword/description` are missing - but not sure if Google use them at all.

**Comment by DanielRosenwasser** [comment]
I'll try to push out a change for some meta tags, but if explicit links help: hey Google & Bing, if you're reading this, here's the [TS Playground](https://www.typescriptlang.org/play/).

**Comment by mhegazy** [comment]
should be working now..
