### ISSUE TITLE
allow better typechecks by setting a max-recursion depth

### ISSUE THREAD

**Issue by zpdDG4gta8XKpMCd** [microsoft/TypeScript#13052]
it's been said many times that certain features cannot be implemented properly due to hitting infinite recursion, and because of that all sort of shortcuts been taken to keep performance acceptable

consider adding a `max-depth` parameter to the `compilerOptions` which controls how deep the type checker can go 

for developers who don't care about thorough type checks the depth can be 0
others can set it to any comfortable number which gives acceptable results in acceptable time

**Comment by RyanCavanaugh** [comment]
Very few people could use this flag usefully and many more people would set it to nonsense values and feel that the results were unexpected.
