### ISSUE TITLE
allow tsserver to be restarted via its public API

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#13059]
every time i open a JS file in my TS project in VSCode, i stop getting any help from tsserver, no autocomplete/hints/anything

i have to close VSCode and start it over, it would be nice to tell tsserver to restart itself instead

**Comment by aluanhaddad** [comment]
I actually have set this up because the problem is so rampant
```json
  {
    "key": "ctrl+shift+l",
    "command": "workbench.action.reloadWindow"
  }
```

**Comment by mhegazy** [comment]
This sounds like a bug. we would appreciate it if you can share some repro steps/project samples to help us diagnose the issue.

**Comment by vladima** [comment]
@aleksey-bykov can you please enable tracing for tsserver in VSCode via `"typescript.tsserver.trace": "verbose"` and send us the content of TypeScript output window after opening .js file and requesting i.e. quick info?

**Comment by aleksey-bykov** [comment]
```
[Trace - 2:20:18 PM] Sending request: quickinfo (7). Response expected: yes. Current queue length: 0
Arguments: {}
[Trace - 2:20:18 PM] Response received: quickinfo (7). Request took 1 ms. Success: false . Message: No content available.
[Trace - 2:20:24 PM] Sending request: open (8). Response expected: no. Current queue length: 0
Arguments: {}
[Trace - 2:20:24 PM] Sending request: geterr (9). Response expected: no. Current queue length: 0
Arguments: {}
[Trace - 2:20:30 PM] Sending request: quickinfo (10). Response expected: yes. Current queue length: 0
Arguments: {}
[Trace - 2:20:31 PM] TypeScript Service: tried to cancel request with sequence number 10. But request got already delivered.
[Trace - 2:20:42 PM] TypeScript Service: canceled request with sequence number 11
```

**Comment by mhegazy** [comment]
looks like the same symptoms of https://github.com/Microsoft/TypeScript/issues/10735. do you see this with all projects, or just one?

**Comment by mhegazy** [comment]
@aleksey-bykov is this still a problem?

**Comment by aleksey-bykov** [comment]
yes, it still hangs any time i open javascript file

**Comment by mhegazy** [comment]
Can you share a repro project?

**Comment by aleksey-bykov** [comment]
no, it's not mine, and the client is very serious about not showing it to anyone

**Comment by mhegazy** [comment]
Do you see this on other projects? Anything special stands out to you about this project? Do you see any exceptions in the log?

**Comment by aleksey-bykov** [comment]
i cannot see it on my own personal project that uses javascript along side with typescript, but i see in at the work project, i think i might know the reason, there are a bunch of heavy javascript libraries like knockout, jquery, jqx, etc in a close vicinity, i think what happens is that when i open a generated javascript files these libs are getting loaded via dependencies and it's just too much for the language service to handle

while coding typescript there is no such problem because instead of the implementation of these libs we only work with definitions which several times shorter

although it's the speculation i don't have a better explanation, so i blame heavy javascript libs

**Comment by aleksey-bykov** [comment]
to clear it up, i see this problem when i open a javascript emitted by the typescript compiler

i cannot see it in my own personal project that uses javascript along side with typescript, but i see in at the work project, i think i might know the reason, there are a bunch of heavy javascript libraries like knockout, jquery, jqx, etc in a close vicinity of the typescript generated javascript files, i think what happens is that when i open a generated javascript file these libs get loaded via dependencies and it's just too much for the language service to handle

while coding typescript there is no such problem because instead of the implementation we work with definitions which are several times shorter

although it's the speculation i don't have a better explanation, so i blame heavy javascript libs

**Comment by aleksey-bykov** [comment]
just checked my theory, i think i found it

i have `test.js`
```javascript
var hey = 'hey';

alert(hey);
```

when i put it to my `src` folder (where i keep all *.ts files) it works!


```
    - src
       - test.js // <-- typescript service works
       - ...*.ts
```

![image](https://cloud.githubusercontent.com/assets/937933/24507732/4508e4c8-152f-11e7-844d-8b3435056395.png)


when i put it outside of src at the same level where the heavy js libs sit, it hangs:

```
    - test.js // <-- typescript service doesn't work (hangs)
    - libs
       - ...*.js
    - src
       - ...*.ts    
```

![image](https://cloud.githubusercontent.com/assets/937933/24507973/0a975fbc-1530-11e7-8e58-ce7dd1bc7066.png)

**Comment by mhegazy** [comment]
VS Code's `Restart TS server` command should address the request in the OP.

from the screen shots above, we are just loading too many files, we have added some checks for detecting too many files cases and handling them gracefully. but enumerating directories and parsing JS files still take resources. our recommendation is to add excludes to tsconfig.
