### ISSUE TITLE
strictNullChecks breaks typeof

### ISSUE THREAD

**Issue by anvish** [Microsoft/TypeScript#13063]
**TypeScript Version:**  2.1.4

**Code**
```ts
let a: number
let b: typeof a // [ts] Variable 'a' is used before being assigned.
```
tsconfig.json: 
```js
{ "compilerOptions": { "strictNullChecks": true } }
```
**Expected behavior:**
No errors, like `"strictNullChecks": false`
**Actual behavior:**
`typeof` wants variable to be assigned

**Comment by slawomir** [comment]
Pull request: #13192

**Comment by mhegazy** [comment]
Thanks @slawomir !
