### ISSUE TITLE
Network Shares resolves incorrectly caused by GetFinalPathNameByHandle

### ISSUE THREAD

**Issue by flts** [Microsoft/TypeScript#13060]
**TypeScript Version:**  2.1.4
**Visual Studio Version:**  2015.3

**Scenario:**
Developing web applications on a Windows 10 virtual machine running in Parallels using Shared Folders to not have duplicated files in multiple development environments.
Parallels Shared Folders are basically network shares mapped to a drive id. 
So for example drive Y: is mapped to \\mac\home\.

**Expected behavior:**
Expected behavior would be to be able to use Visual Studio 2015.3 with TypeScript on network shares and have Intellisense, compile on save and compile on build work like regular folders (d:\folder\).
TypeScript 1.8.4 didn't have this problem.

**Actual behavior:**
Currently in 2.1.4 compile on build results in the tsc.exe giving back a exitcode 1.
compile on save and intellisense aren't even working.
 
Even when using a local symlink from C:\Projects\ to \\mac\home\projects\, the realPath() resolving method fails to correctly give back an usable 

**Rootcause(s):**
Microsoft.CodeAnalysis.TypeScript.EditorFeatures.dll uses the Windows API call 'GetFinalPathNameByHandle' to resolve paths. Unfortunately this realPath method does not take into account that a path could be resolved to start with '\\?\UNC\', it only takes into account that all paths will be resolved to start with \\?\.
So when we resolve path 'Y:\companyname\projects\client\application\' it will come out as 'UNC\mac\home\companyname\projects\client\application\'.

Possibly ChakraCore.dll (still) has this same problem.

**Workaround for VS2015:**
In the following files make the changes below:
_File: C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.1\tsc.js_
_Change:_
Line 2342:
```
var realpath = ChakraHost.realpath && (function (path) { return ChakraHost.realpath(path); });
```
to
```
var realpath = ChakraHost.realpath && (function (path) { return ChakraHost.realpath(path).replace('UNC\\', '\\\\'); });
```

_File: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TypeScript\typescriptServices.js_

_Change:_
Line 3789:
```
var realpath = ChakraHost.realpath && (function (path) { return ChakraHost.realpath(path); });
```
to
```
var realpath = ChakraHost.realpath && (function (path) { return ChakraHost.realpath(path).replace('UNC\\', '\\\\'); });
```

Line 80444:
```
this.realpath = function (path) { return _this.shimHost.realpath(path); };
```
to
```
this.realpath = function (path) { 
	var rlpath = _this.shimHost.realpath(path); 
	if (rlpath.indexOf('UNC\\') == 0) {
		return path;
	}
	else {
		return rlpath;
	}
};
```

**Workaround for NPM:**
The same changes could be applied to these files in npm\typescript\lib folder:

- tsc.js
- tsserver.js
- tsserverlibrary.js
- typescript.js
- typescriptServices.js

**Comment by mhegazy** [comment]
thanks for the detailed drill down. we are actually working on fixing this now.

**Comment by mhegazy** [comment]
@flts can you give https://myget.org/gallery/typescript-preview a try?

**Comment by mhegazy** [comment]
Thanks for confirming the build issue is resolved. 

The language service issue looks like a different issue. Can you share a project i can look at?

**Comment by mhegazy** [comment]
I am closing this since the original issue has been resolved. Feel free to share your project here on in a new issue. i would be happy to investigate the other issue more.

**Comment by flts** [comment]
Hi @mhegazy actually the original issue also stated Intellisense issues but I have created a new issue #13319 for this.
