### ISSUE TITLE
Visual studio and VS code don't apply tsconfig.json if it uses braces in glob

### ISSUE THREAD

**Issue by scriby** [microsoft/TypeScript#13062]
**TypeScript Version:**  2.1.4

**Code**

```json
{
  "compilerOptions": {
    "noEmitOnError": true,
    "removeComments": false,
    "experimentalDecorators": true,
    "sourceMap": true,
    "target": "es5",
    "jsx": "react",
    "module": "amd"
  },
  "compileOnSave": true,
  "include": [ "**/*{.ts,.tsx}", "../App", "../Scripts" ],
  "exclude": [ "../App/**/*spec.ts", "../App/**/*.e2e.*ts" ] 
}
```

**Expected behavior:**

Decorators can be used without issue in Visual Studio and VS Code for ts/tsx files in the current directory.

**Actual behavior:**

Visual Studio and VS Code give an error indicating decorators are not supported. The tsc compiler works just fine. Changing `"**/*{.ts,.tsx}"` to `"**/*.ts", "**/*.tsx"` works around the error. It appears the glob implementation in VS does not support braces properly.

**Comment by DanielRosenwasser** [comment]
Right now curly braces aren't supported in our glob patterns, so that's what you're seeing.

**Comment by RyanCavanaugh** [comment]
Didn't get any additional feedback on this one...
