### ISSUE TITLE
Can't downcast by self-assignment

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#13069]
**TypeScript Version:**  nightly (2.2.0-dev.20161220)

**Code**

```ts
function f(x: {}): number {
    x = x as number;
    return x;
}

function g(x: {}): number {
    const y = x as number;
    return y;
}

function h(x: string | number): number {
    x = x as number;
    return x;
}
```

**Expected behavior:**

No error.

**Actual behavior:**

`a.ts(3,12): error TS2322: Type '{}' is not assignable to type 'number'.`

Funny that it works with union "downcasting", but not for supertype->subtype downcasting.

**Comment by mhegazy** [comment]
assignment is not a form of casting. what is going on here is narrowing. and narrowing only works on unions. that is why `x: {}` was not narrowed to `number`, where as it was narrowed in `x: string | number`
