### ISSUE TITLE
Interface with all optional params not enforced in function signature

### ISSUE THREAD

**Issue by zelein** [Microsoft/TypeScript#13070]
**TypeScript Version:**  2.1.4

**Code**

[TS Playground of code](https://www.typescriptlang.org/play/index.html#src=interface%20Test%20%7B%0D%0A%20%20%20%20foo%3F%3A%20number%3B%0D%0A%20%20%20%20bar%3F%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Afunction%20exec(obj%3A%20Test)%3A%20void%20%7B%0D%0A%20%20%20%20return%3B%0D%0A%7D%0D%0A%0D%0Aconst%20testVar%3A%20number%20%3D%201%3B%0D%0A%0D%0Aexec(testVar)%3B%0D%0Aexec(1)%3B%0D%0Aexec(%22hello%20world%22)%3B)

**Expected behavior:**
TypeScript should be throwing an error stating that I have passed in something that does not conform to that object. 
Since all of the properties are optional, I would expect it to at a minimum only allow an empty object. Not primitives. 

**Actual behavior:**
It's letting me pass in any type to the function.

**Comment by aluanhaddad** [comment]
>Since all of the properties are optional, I would expect it to at a minimum only allow an empty object. Not primitives.

Why exactly? TypeScript is a structurally typed language language.
An interface with no required members is compatible with the empty type `{}`.

The behavior you have observed is both correct and fundamental to the nature of the language.

**Comment by zelein** [comment]
> An interface with no required members is compatible with the empty type {}.

Precisely. Why is TypeScript allowing more than just the empty type ```{}```?
Are you saying that TypeScript sees primitives and empty object structures as equals?

**Comment by aluanhaddad** [comment]
Not quite. It sees all types as _assignable_ to the empty object type. Consider:
```ts
let x: {};
let y = 1;
x = y; // OK
y = x; // Error

**Comment by RyanCavanaugh** [comment]
The problem with saying primitives shouldn't be assignable to any object-like type is that primitives still have useful things like `toString` which can satisfy target interfaces in some places.

See also https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-all-types-assignable-to-empty-interfaces or #11862 or many of the dozens of other bugs logged to this effect.

Which search terms did you use before logging this? We're trying to reduce duplicates/questions and are curious what people are searching (and why they're not finding the existing issues) when logging bugs. Thanks!

**Comment by aluanhaddad** [comment]
@RyanCavanaugh I would say it's not a problem at all and actually it's a feature of JavaScript and many other high-level language they deliberately avoid making a sharp distinction between primitive types and other kinds of types. For example, this difference is observable between C# and Java. It is perhaps a small thing but it raises the level of abstraction by making the language more regular and allowing us to think about logically equivalent operations in a uniform way.
