### ISSUE TITLE
allow absolute paths in import codefix to support AMD modules

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#13078]
~~Undeclared identifier can be searched though all known modules, a codefix that imports the said identifier from one of the found modules should be offered to the user~~

Import codefix adds a relative path to a module, please allow absolute paths too to support AMD

**Comment by mhegazy** [comment]
What do you mean by absolute? if the `baseUrl` is set, the module name should use that.

**Comment by aleksey-bykov** [comment]
`./` or `../..` are relative paths against the current dir, this is what the import codefix uses, and which is if fine when you program for node

what we need is paths without `./` or `../` but rather looking like this `basics/optional` or ` data/attributes/settings`
 Corresponding to
```
baseUrl
  basics/
     - optional.TS
  data/
     attributes/
        - settings.TS
```

**Comment by aleksey-bykov** [comment]
Ideally the "paths" mappings from tsconfig.json need to be taken it accout to calculate the correct module path from a given filepath, which would be an inverse problem to mapping module paths to filepaths that is already done by TS

**Comment by mhegazy** [comment]
so just to be clear, you have a baseUrl in your tsconfig.json, and the quick fix returns something that is has `../`?

**Comment by aleksey-bykov** [comment]
I went and checked if we had baseUrl, we did not. I added `"baseUrl": "./"`. Not it resolves to non-relative module path. Problem has gone. Thanks.
