### ISSUE TITLE
add codefix that eliminates unused imports

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#13079]
For any unused import there should be an option to automatically remove it. There also should be an option to remove all unused modules together at once.

**Comment by aleksey-bykov** [comment]
works per remove unused identifiers

**Comment by aleksey-bykov** [comment]
currently codefix only removes an unused identifier at which the caret is, which is silly because it's easier to cut the current line or word (there are hotkeys for this)

this feature would have been more useful if it removed *all unused inputs*

please consider

**Comment by mhegazy** [comment]
Please see https://github.com/Microsoft/TypeScript/issues/13131
