### ISSUE TITLE
Declaration of string guard for number-only keys aren't possible

### ISSUE THREAD

**Issue by pocesar** [Microsoft/TypeScript#13085]
**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)

**Code**

```ts
/* the current typings are impossible to achieve. the material-colors library exports an object with number keys that looks like
{
  "green": {
    "50": "#xxx",
    "100": "#xxx",
    "200": "#xxx",
    "a700": "#xxx"
  }
}
*/
declare module 'material-colors' {
   type Spectrum = '50' | '100' | '200' | '300' | '400' | '500' | 'a700';
   /*
  interface Spectrum {
    50: string;
    100: string;
    a700: string;
  }
  this doesn't work for obvious reasons, only a700 appears when doing MK.color.a700
  */
   interface Colors<T extends string> {
      [index: T]: string; // won't allow to use this, asks for string or number
     // [index: Spectrum]: string; won't work as well
   }
  
  export const green: Colors<Spectrum>;
  
  type Z2S = '0' | '1' | '2' | '3' | '4' | '5' | '6';
  export const white: Colors<Z2S>;
}
// 
import * as MK from 'material-colors';

MK.green['222']; // compiler won't complain if "noImplicityAny" is false
```

**Expected behavior:**

Define guarded string types for 'number only' keys as strings

**Actual behavior:**

Won't allow definition of number-only keys, that at runtime are coerced to strings, unless it's a symbol

**Comment by gcnew** [comment]
Is the gist of this issue unsafe indexing?

i.e.
```ts
declare const n: number;
n["hello"]; // any     -- what?
```

**Comment by gcnew** [comment]
If it is about the indexing signature of `Colors`/`Spectrum` you can use the following. It will yield correct types for keys already present and `any` otherwise as you have observed.

```ts
type SpectrumKeys = '50' | '100' | '200' | '300' | '400' | '500' | 'a700';

type Spectrum = {
    [key in SpectrumKeys]: string
}
```

.. and a workaround

```ts
function safeIndex<K extends SpectrumKeys>(key: K, spectrum: Spectrum): Spectrum[K] {
    return spectrum[key];
}

declare const green: Spectrum;

green["100"] // string, OK
green["20"] // any, Not OK

safeIndex("100", green) // OK
safeIndex("20", green) // error, OK
```

**Comment by pocesar** [comment]
yes, unsafe indexing is one of the problems. you can't define interfaces with numbers are keys (they won't appear in autocomplete, since you can't access numbers using `somevar.0`)

**Comment by gcnew** [comment]
Well, I don't see what more can be done on the safety side as "noImplicitAny" already solves the checking problem. I guess the IDE should be made smarter to show all indexing options and autocomplete with the appropriate syntax (even if you typed `.`).

**Comment by RyanCavanaugh** [comment]
> ` this doesn't work for obvious reasons, only a700 appears when doing MK.color.a700`

What's wrong about this? You can still write `MK.color["100"]` and get a typed value back.

Between mapped types, as suggested, and just doing it the "normal" way, I think you can get what you're looking for. Let me know if that's not the case

**Comment by pocesar** [comment]
when using `MK.color[| ]` the autocomplete won't show the possible values like it does with `MK.color.|`. so you will only know what possible values are after the compile complains
