### ISSUE TITLE
allow configuration section in tsconfig for customizing codefixes 

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#13084]
There might be a section in tsconfig say `"codefixes"` which would be a dictionary of arbitrary configuration objects keyed by names of codefixes. Such object containing customization would be passed to the code of a corresponding codefix.

**Comment by mhegazy** [comment]
More of an implementation detail for https://github.com/Microsoft/TypeScript/issues/6508. I do not think we want to separate extensions into categories, e.g. "code fixes", "refactorings" and "completions" etc..
