### ISSUE TITLE
Empty `super` call should be allowed when extending map

### ISSUE THREAD

**Issue by paulvanbrenk** [microsoft/TypeScript#13099]
Consider the following code:
```typescript
class DefaultMap extends Map {
    constructor(iterable:any){
        super(iterable);
    }
}
```
This will give an error that the supplied parameters do not match the signature on the `super` call, where `new Map(iterable)` works as expected.

**Comment by RyanCavanaugh** [comment]
Should change lib.d.ts to read as follows (move generic signature up, add optional parameter to non-generic signature):
```ts
interface MapConstructor {
    new <K, V>(entries?: [K, V][]): Map<K, V>;
    new (entries?: any[]): Map<any, any>;
    readonly prototype: Map<any, any>;
}
```

**Comment by RyanCavanaugh** [comment]
Doesn't seem like anyone cares.
