### ISSUE TITLE
wrong WebGLRenderingContext interface definition about gl.pixelStore

### ISSUE THREAD

**Issue by ReadingSteiner** [Microsoft/TypeScript#13093]
**TypeScript Version:  2.1.4**

**Code**

```ts
gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL, true)

```

**Expected behavior:**
well compiled

**Actual behavior:**
error TS2345: Argument of type 'true' is not assignable to parameter of type 'number'

I checked the `lib.d.ts` and got this 
```ts
pixelStorei(pname: number, param: number): void;
```
but it should be
```ts
pixelStorei(pname: number, param: number | boolean): void;
```
check this API at MDN [here](https://developer.mozilla.org/zh-CN/docs/Web/API/WebGLRenderingContext/pixelStorei)

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.
