### ISSUE TITLE
No encoding config option for compiler

### ISSUE THREAD

**Issue by marcelh-gh** [Microsoft/TypeScript#13091]
**TypeScript Version:**  2.1.4

There seems to be no option to configure the encoding for the generated .js files.

Based on a project with Typescript files encoded in Windows1252 exclusively the .js files generated are all in UTF-8.

**Comment by RyanCavanaugh** [comment]
What other encoding do you want, and why?

**Comment by mhegazy** [comment]
All the generated files are in UTF-8. you have the option to add a BOM in generated files using `--emitBOM`.

**Comment by marcelh-gh** [comment]
as stated in my op my sources are encoded in Windows1252. that is what I need for the outputs as well.
maybe if you don't want to implement a compiler option for this you can just use the encoding of the source files.

**Comment by RyanCavanaugh** [comment]
What runtime wants 1252 but can't accept UTF-8?

**Comment by marcelh-gh** [comment]
there are no problems as long as you only deal with English. the moment you are dealing with strings in other languages like German you have characters which won't we displayed properly if you just use UTF-8.

**Comment by RyanCavanaugh** [comment]
UTF-8 encodes all Unicode characters and is recognized by all JS runtimes. Practically the reverse is true of 1252.

**Comment by marcelh-gh** [comment]
Ryan, we don't have to argue about this. Pretty much every text/code editor there is lets you configure the text encoding to be used. That would not be the case if nothing but UTF-8 was necessary at any given time.

If you are reluctant to implement different encoding options for tsc that is fine. I can just convert the results myself. The problem i am facing right now is that all my sources are in 1252 and tsc messes up the characters in the results.
So I would have to first convert all my sources to UTF-8 and then always convert the compilation results to 1252. Fair enough.

**Comment by RyanCavanaugh** [comment]
I really am asking which runtime you're using that supports 1252 but not UTF-8. To our knowledge these do not exist so we want to understand the scenario here.

**Comment by marcelh-gh** [comment]
The compiled javascripts are used within an Adobe environment. It is ECMA Script 3 based and requires 1252 for the German characters to be displayed properly.
Obviously I usually use UTF-8 normally.... ;-)
