### ISSUE TITLE
add codefix for stub method/function

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#13094]
offer a codefix as an option (among others, for example importing) that would create a stub of a function or method, when undeclared identifier is used in a call expression

**Comment by mhegazy** [comment]
duplicate of https://github.com/Microsoft/TypeScript/issues/10140

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
