### ISSUE TITLE
Generic type is not inferred correctly when used as callback argument and return type

### ISSUE THREAD

**Issue by kimamula** [microsoft/TypeScript#13096]
Probably related to #12915

**TypeScript Version:**  2.1.4 / nightly (2.2.0-dev.20161221)

**Code**

```ts
declare function f<T>(f: (t: T) => T): T;

f(() => ({ a: '' })).a; // no error
f((t) => ({ a: '' })).a; // error TS2339: Property 'a' does not exist on type '{}'.
```

**Expected behavior:**
Generic type `T` is inferred as `{ a: string }` for both `f(() => ({ a: '' }))` and `f((t) => ({ a: '' }))`

**Actual behavior:**
 `T` is inferred as `{}` for `f((t) => ({ a: '' }))`

**Comment by RyanCavanaugh** [comment]
This is a correct error because inference rules around co- and contra-variant candidates follow from reality. From the perspective of "How could `f` be implemented", it can't possibly construct a value matching `{ a: string }` *before* calling the function to get that value from its return type.
