### ISSUE TITLE
Unhelpful error when using increment with stricter checks on uninitialized variables

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#13108]
Version: TypeScript 2.1.4

```ts
function f() {
    var x;
    x++;
    return x;
}
```

Turn on `noImplicitAny` and/or `strictNullChecks`.

The error that you'll get is 

```
An arithmetic operand must be of type 'any', 'number' or an enum type.
```

However, quick info for this variable reports that it's `any`, and the error itself doesn't tell us what the type is.

**Comment by mhegazy** [comment]
they type of `x` should be `undefined`. the issue seems to be with your quick info and not the error message.

**Comment by Andarist** [comment]
The error has been improved since then and it nows states this:
> 'x' is possibly 'undefined'.(18048)

This is quite helpful and points to the issue with the code directly. I think this issue could be closed (cc @jakebailey )
