### ISSUE TITLE
TypeScript Version:  2.1.4 TS6133 ''attr' is declared but ever used.

### ISSUE THREAD

**Issue by cwoodland** [Microsoft/TypeScript#13101]
**TypeScript Version:**  2.1.4 TS6133 ''attr' is declared but ever used.

**Code:**   
```
public link: ng.IDirectiveLinkFn = (scope: any, element: ng.IAugmentedJQuery, attr: ng.IAttributes, ctrl: Array<any>) => {
            let ngModel: IEditorModel = ctrl[0];
            let isTextarea: boolean = element[0].tagName.toLowerCase() === 'textarea';

            if (!isTextarea) {
                return;
            }

            let ckInstance: CKEDITOR.editor = CKEDITOR.replace(<HTMLTextAreaElement> element[0]);
            CKEDITOR.config.customConfig = scope.customConfig;
            CKEDITOR.config.startupFocus = scope.hasStartupFocus;
            CKEDITOR.config.height = scope.desktopHeight;

            element.bind('$destroy', () => {
                ckInstance.destroy(false);
            });

            ckInstance.on('instanceReady', (instanceObj: CKEDITOR.eventInfo) => {
                scope.$apply(() => {
                    ngModel.$setViewValue(ckInstance.getData());
                });
                instanceObj.editor.removeMenuItem('editdiv');
                instanceObj.editor.removeMenuItem('removediv');
            });

            ngModel.$render = () => {
                if (ngModel.$viewValue === undefined) {
                    ngModel.$setViewValue('');
                    ngModel.$viewValue = null;
                } else {
                    if (ngModel.$viewValue) {
                        let viewValue: string = ngModel.$viewValue;
                        ckInstance.setData(viewValue);
                    }
                }
            };

            let updateModel: any = () => {
                this.$timeout(() => {
                    ngModel.$setViewValue(ckInstance.getData());
                });
            };

            ckInstance.on('change', updateModel);
            ckInstance.on('key', updateModel);
            ckInstance.on('blur', updateModel);
            ckInstance.on('dataReady', updateModel);
        }

        public static factory(): any {
            let directive: Function = ($timeout: ng.ITimeoutService): CkEditor => {
                return new CkEditor($timeout);
            };
            directive.$inject = ['$timeout'];
            return directive;
        };
    }
```

**Expected behavior: ** 
We have created a directive in typescript and have declared the link function as described above.  
We would expect that the signature for the link method be recognized and not throw an error 
of TS6133 for unused argument 'attr'

**Actual behavior:**  
src\app\webmail\directives\webmail.ckEditor.ts(21,87): error TS6133: 
'attr' is declared but never used.**

**Comment by RyanCavanaugh** [comment]
I don't understand what the complaint is? The error is correct; the `attr` parameter is not used in the function. This is an error about declaring a parameter without using it, not a type system error.

You may omit the parameter (it will still be assignable to the `IDirectiveLinkFn` type), or name it with a leading underscore (`_attr`).

**Comment by cwoodland** [comment]
Omitting the parameter gives us:

[ts]
Type '(scope: any, element: IAugmentedJQuery, ctrl: any[]) => void' is not assignable to type 'IDirectiveLinkFn'.
  Types of parameters 'ctrl' and 'instanceAttributes' are incompatible.
    Type 'IAttributes' is not assignable to type 'any[]'.
      Property 'length' is missing in type 'IAttributes'.

What does the leading underscore do?? I am not familiar.
Adding _attr does work.

Thank you for your quick response.

**Comment by RyanCavanaugh** [comment]
Unused parameter errors aren't issued for names starting with `_` (specifically for this case).

**Comment by cwoodland** [comment]
Awesome thank you again!

**Comment by simonua** [comment]
Ryan,

Is this documented anywhere by chance? I must have missed it, if so.

> Unused parameter errors aren't issued for names starting with _ (specifically for this case).

Thank you.

**Comment by mhegazy** [comment]
> Is this documented anywhere by chance? 

http://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#flag-unused-declarations-with---nounusedparameters-and---nounusedlocals

**Comment by simonua** [comment]
That's perfect! Thank you very much. I truly missed it. =)

Could the compiler warning perhaps suggest that if a parameter must be accepted due to a function's signature, that an underscore could be used to prevent TS6133, please?
