### ISSUE TITLE
Rename not available in playground

### ISSUE THREAD

**Issue by RyanCavanaugh** [Microsoft/TypeScript#13106]
**TypeScript Version:**  Current Playground

**Code**
```ts
interface Cat { // <- rename 'Cat' to 'Dog'

}

interface Catamaran {
  
}
```

**Expected behavior:**
```ts
interface Dog {

}

interface Catamaran {
  
}
```

**Actual behavior:**
```ts
interface Dog {

}

interface Dogamaran {
  
}
```

**Comment by mhegazy** [comment]
Rename is not working currentlly.. not sure how you got this to work...

**Comment by wallverb** [comment]
![rmiaatp2b7](https://cloud.githubusercontent.com/assets/1723815/21412624/97bbd454-c7bf-11e6-8df8-a519b53b5588.gif)

**Comment by DanielRosenwasser** [comment]
Change all occurrences is, while misleadingly similar, not actually the same as rename.

**Comment by DanielRosenwasser** [comment]
Also https://github.com/Microsoft/monaco-editor/issues/300

**Comment by mhegazy** [comment]
change all occurrences is find and replace. rename is not implemented yet. closing in favor of  Microsoft/monaco-editor#300
