### ISSUE TITLE
Incorrect type for first element of a string

### ISSUE THREAD

**Issue by marzelin** [Microsoft/TypeScript#13119]
**TypeScript Version:**  2.1.4

Accessing first element of a string can return a string or undefined (in case of an empty string).

**Code**

```ts
const head = (str: string) => str[0]
```

**Expected behavior:**
function signature: `head: (s: string) => string | undefined`

**Actual behavior:**
function signature: `head: (s: string) => string`

**Comment by mhegazy** [comment]
Please see https://github.com/Microsoft/TypeScript/issues/9754
