### ISSUE TITLE
error TS1057, when resolving an `async` function with a 

### ISSUE THREAD

**Issue by eschwartz** [Microsoft/TypeScript#13128]
**TypeScript Version:**  2.2.0-dev.20161221

**Code**

## Use Case A: Fails with `async` keyword, and `any` lookup type

```ts
interface SomeObj {
  stringProp: string;
  anyProp: any;
}

async function getAnyProp<TObj extends SomeObj>(obj:TObj):Promise<TObj['anyProp']> {
  return Promise.resolve(obj.anyProp);
}
```

**Expected behavior:**

Code should compile successfully

**Actual behavior:**

Code does not compile. Emits an error:

```
(6,16): error TS1057: An async function or method must have a valid awaitable return type.
```

Where `(6,16)` is the location of `getAnyProp`

## Use case B: Succeeds without `async` keyword

Note that the code _will compile_ if you remove the `async` keyword:

```ts
function getAnyProp<TObj extends SomeObj>(obj:TObj):Promise<TObj['anyProp']> {
  return Promise.resolve(obj.anyProp);
}
// compiles successfully
```

## Use case C: Fails with `async` keyword, and generic passed to `Promise.resolve`

I also get a strange error if I pass a generic to `Promise.resolve`:

```ts
async function getAnyProp<TObj extends SomeObj>(obj:TObj):Promise<TObj['anyProp']> {
  return Promise.resolve<TObj['anyProp']>(obj.anyProp);
}
```

Results in:

```
(6,16): error TS1057: An async function or method must have a valid awaitable return type.
(7,10): error TS1059: Return expression in async function does not have a valid callable 'then' member.
```

Again, if I remove the `async` keyword, this example compiles successfully.

## Use Case D: Succeeds with `string` lookup type

The issue seems only to occur if the resolved lookup type is of type `any`.

This code, for example, compile successfully.

```ts
interface SomeObj {
  stringProp: string;
  anyProp: any;
}

async function getStringProp<TObj extends SomeObj>(obj:TObj):Promise<TObj['stringProp']> {
  return Promise.resolve<TObj['stringProp']>(obj.anyProp);
}
```

It will also compile successfully with `number`, `boolean`, `void`, or `{}`.

## Use Case E: Succeeds without generic

If I do not use generics, the code compiles successfully.

For example:

```ts
interface SomeObj {
  anyProp: any;
}

async function getAnyProp():Promise<SomeObj['anyProp']> {
  return Promise.resolve<SomeObj['anyProp']>('foo');
}
```

----

Thank you for your help! I'm really loving the new lookup types.

**Comment by rbuckton** [comment]
This is due to the fact that an `IndexedType` in our type system that points to `any` does not itself have the `TypeFlags.Any` flag, so it fails one of the conditions for checking for a "thenable" type. However, when we compare the type to `Thenable`, our type checking logic treats `TObj['anyProp']` as `any`, which is why it is failing. 

I'm testing a fix for this now.

**Comment by eschwartz** [comment]
Wow, you guys rock.
