### ISSUE TITLE
CodeFix for missing import should take into acount @types

### ISSUE THREAD

**Issue by wallverb** [Microsoft/TypeScript#13129]
![image](https://cloud.githubusercontent.com/assets/1723815/21434215/3a2d4c14-c841-11e6-83d4-87f3f029fb4d.png)

**Comment by zhengbli** [comment]
I do not repro though on my machine:

![image](https://cloud.githubusercontent.com/assets/1171301/21831754/0af4f55e-d75b-11e6-9d02-88491685ba5e.png)

Can you post a sample code? Thanks

**Comment by wallverb** [comment]
Sure, here is the the sample: https://github.com/wallverb/test
Clone, `npm install` and I get this:

![image](https://cloud.githubusercontent.com/assets/1723815/21832187/4aacbca6-d777-11e6-8480-c1c990114967.png)

Looks like it might be related to `"baseUrl": "."` in `tsconfig.json`

**Comment by DanielRosenwasser** [comment]
I feel like you need to change this to

```json
            "*": [
                "node_modules/@types/*"
                "node_modules/*"
            ]
```

or just omit the entire `"*"` field if you're using `"moduleResolution": "node"`

**Comment by wallverb** [comment]
@DanielRosenwasser - Thanks - first suggestion does the trick

If I omit entire `'*'` field with `"moduleResultion": "node"` then I get this:

![image](https://cloud.githubusercontent.com/assets/1723815/21833348/8b0a8366-d77f-11e6-9b9e-df41c69288fe.png)

**Comment by DanielRosenwasser** [comment]
Looks like there's an issue when it comes to using path mapping. Thanks!
