### ISSUE TITLE
Static variables class variables of another class in the same module cannot be instantiated before the class has been declared

### ISSUE THREAD

**Issue by Saulzi** [Microsoft/TypeScript#13121]
**TypeScript Version:**  2.1.4 
Static variables class variables of another class in the same module cannot be instantiated before the class has been declared

for example

```ts
class Issue {
    static readonly X = new DoesntWork();
}

class DoesntWork {
    
}
```
this is because of where X is being set in the generated javascript
```js
var Issue = (function () {
    function Issue() {
    }
    return Issue;
}());
Issue.X = new DoesntWork();
var DoesntWork = (function () {
    function DoesntWork() {
    }
    return DoesntWork;
}());
```

Issue.X should be set after DoesntWork is defined rather than before

If I swap the order of definition, it works, i.e.
```ts
class DoesntWork {

}
class Issue {
    static readonly X = new DoesntWork();
}
```
Generated JS
```js
var DoesntWork = (function () {
    function DoesntWork() {
    }
    return DoesntWork;
}());
var Issue = (function () {
    function Issue() {
    }
    return Issue;
}());
Issue.X = new DoesntWork();
```

Swapping around kind of works but if you want class DoesntWork to inherit Issue Issue needs to be declared first

**Expected behavior:**
No error and able to reference Issue.X
Issue.X = new DoesntWork needs to be dumped at either the end of the js or after where DoesntWork is declared.

**Actual behavior:**
Error is raised, 
Uncaught TypeError: DoesntWork is not a constructor (chrome)
Object doesn't support this action (edge)
etc etc

**Comment by mhegazy** [comment]
seems like a duplicate of https://github.com/Microsoft/TypeScript/issues/12673

**Comment by Saulzi** [comment]
This is not a duplicate as #12673 as that is suggesting blocking using b before it is defined. What I am essentually trying to acheive is have a 'static readonly 'null instance'' the suggestion above will not allow exporting a hidden class which inherits from Issue and impements a 'null instance' of issue if that makes sense??
 
```ts
export class Issue {
    static readonly X = new DoesntWork();
    SomeMethod() { // Do something }
}

class DoesntWork extends Issue {
    SomeMethod() { // Do Nothing }
}
```

**Comment by mhegazy** [comment]
The compiler does not reorder code. #12673 tracks giving a warning at compile time that this is going to fail at runtime.

**Comment by Saulzi** [comment]
had worked around this with static get and backing field set after definition which is not exported. would be nice to have this with less code :P
