### ISSUE TITLE
add codefix that rewrites var to let to const where appropriate

### ISSUE THREAD

**Issue by zpdDG4gta8XKpMCd** [microsoft/TypeScript#13133]
consider adding a codefix that transforms `var` to `let` to `const` by picking strictest declaration possible

**Comment by mhegazy** [comment]
We can do a refactoring for this. will have to think about cases where the `var` declaration is used outside the block where it is defined, we will need to hoist the declaration as well as change it to block-scoped declaration.

**Comment by aleksey-bykov** [comment]
btw are refactorings even a thing that is somehow different from codefixes (i am asking because i see different tags are used to label similar issues)?

**Comment by DanielRosenwasser** [comment]
A code fix usually implies something is wrong - there's an error that can be amended. A refactoring implies rewriting working code in some manner. I think that both fall under the umbrella of "code actions".

In general, I've been sloppy with the terminology with @paulvanbrenk correcting me every so often.

**Comment by mhegazy** [comment]
> btw are refactorings even a thing that is somehow different from codefixes (i am asking because i see different tags are used to label similar issues)?

Code Fix is tied to a diagnostic message, e.g. an error. If the error is shown, the editor shows you the option to "fix" it.

Refactoring are more free form. you would right-click on a position and ask for possible refactorings.

it is possible that you have the same change available as a Fix and as a refactoring.

**Comment by angelozerr** [comment]
tslint supports that. I have started to write a tslint plugin (for TypeScript 2.2.1) https://github.com/angelozerr/tslint-language-service . Here a demo with Eclipse but it works too with other IDE like VSCode:

![tslintnovardemo](https://cloud.githubusercontent.com/assets/1932211/25174174/d2878fa8-24f6-11e7-9b52-93a95f438c58.gif)

**Comment by aleksey-bykov** [comment]
why does it turn into `let` instead of `const` on the annimation?

**Comment by jessetrinity** [comment]
ESLint already has a fix that does this - I don't think we should overlap.
