### ISSUE TITLE
Partial<T> accepts arbitrary Function

### ISSUE THREAD

**Issue by anvish** [Microsoft/TypeScript#13132]
**TypeScript Version:**  2.1.4

**Code**

```ts
interface State {
    num: number
}

function setState(state: Partial<State>) { }

setState((a, b) => ({ x: 7 })) // no errors
```

**Expected behavior:**
Does not compile.
**Actual behavior:**
Compiles without errors.

**Comment by mhegazy** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/12936

**Comment by anvish** [comment]
Not sure if this is really a duplicate of exact type proposal, because this code is checked correctly:
```ts
setState({ a: 1 }) //   Object literal may only specify known properties, and 'a' does not exist in type 'Partial<State>'.
```

**Comment by mhegazy** [comment]
U are correct sort about that. This is a duplicate of https://github.com/Microsoft/TypeScript/issues/7485 and should be fixed by https://github.com/Microsoft/TypeScript/pull/16047
