### ISSUE TITLE
Non-null assertion operator should work on index signature

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#13146]
I think the following code should work:
```ts
interface A {
    [index: string]: string;
}
interface B {
    a: A;
}
let b: B = { } as any;
b.a.some!; // error? some
```
Because you have asserted it to be non-null and an index signature tells that `A` can contain more props than what is defined in `A`. It makes sense to let people assert non-null in those cases.

**Comment by gcnew** [comment]
I think https://github.com/Microsoft/TypeScript/issues/12596 is what you are after.
