### ISSUE TITLE
TypeScript 2.1 regressed #4952 (UMD modules requirejs optimizer compatibility)

### ISSUE THREAD

**Issue by michalrousal** [Microsoft/TypeScript#13147]
**TypeScript Version:**  2.1.1

Format of the generated UMD modules changed with TS 2.1 and isn't compatible with requirejs optimizer anymore (dependencies moved from define() to self invocation argument), please refer to the linked ticket #4952 for more detailed description.

**Comment by aluanhaddad** [comment]
This looks serious
