### ISSUE TITLE
CFA not work in function

### ISSUE THREAD

**Issue by twoeo** [Microsoft/TypeScript#13142]
**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)
2.1.4

**Code**

```ts
let f:string | null = 'xx';
let v:string;
if(f){
    [].forEach(item=>{
        v = f;
    })
}
```

**Expected behavior:**
Compile successfully

**Actual behavior:**
> test.ts(5,9): error TS2322: Type 'string | null' is not assignable to type 'string'.
  Type 'null' is not assignable to type 'string'.

**Comment by HerringtonDarkholme** [comment]
https://github.com/Microsoft/TypeScript/issues/9998
