### ISSUE TITLE
How to change a optional field to required with Mapped Types?

### ISSUE THREAD

**Issue by twoeo** [Microsoft/TypeScript#13143]
**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)
2.1.4

**Code**

```ts
interface A{
    a?: {
        a1: string;
    }
}

type B = {
    a: A['a']
}

let aa:B = { a: {a1: 'A1'} };
console.log(aa.a.a1)
```

`A.a` is optional field,
anyway to change it to required field ?

Maybe it's better that `A['a']` is always required. 

**Expected behavior:**
Compile successfully

**Actual behavior:**
> test.ts(12,13): error TS2532: Object is possibly 'undefined'.

**Comment by HerringtonDarkholme** [comment]
https://github.com/Microsoft/TypeScript/issues/12578#issuecomment-263948325

Please, do search existing issues before making new ones. GitHub issue is not StackOverflow.
