### ISSUE TITLE
Highlighting issue

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/TypeScript#13158]
Highlighting is different in this too cases:
```ts
export const fun = (param: ParamType): FunResult => {
```

```ts
export const fun = 
  (param: ParamType): 
    FunResult => {
```

In the first snippet `param` is highlighted with orange, and types (`ParamType`, `FunResult`) are purple. And in the second `param` and `ParamType` has the same color as `fun` (const name) and `Result` is orange.

**Comment by DanielRosenwasser** [comment]
In what editor?

**Comment by whitecolor** [comment]
@DanielRosenwasser you see that the highlighting in too code snippets are different? In the first `param` is highlighted with orange, and types (`ParamType`, `FunResult`) are purple. And in the second `param` and `ParamType` has the same color as `fun` (const name) and `Result` is orange.

**Comment by DanielRosenwasser** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#388

**Comment by whitecolor** [comment]
Next time will create issues of highlighting there.
