### ISSUE TITLE
export interface with a property decorator not working

### ISSUE THREAD

**Issue by omouse** [Microsoft/TypeScript#13155]
**TypeScript Version:**  2.1.4

**Code**

Interface definition:

```ts
export interface Event { title: string };
```

Decorated property:

```ts
import { Event } from './event.ts';
import { Input } from '@angular/core';

export class SomeClass {
  @Input() event: Event;
}
```

**Expected behavior:**

In the generated code it should be able to find the event module.

**Actual behavior:**

It compiles and in the browser, the Input function is looking for a variable named Event which doesn't exist on the module.

The error is this:

    Uncaught ReferenceError: event_1 is not defined

And the code generated looks like this:

```javascript
    __decorate([
	    core_1.Input(),
	    __metadata("design:type", event_1.Event)
	]
```

Leaving out the type declaration for the decorated property or declare it as an `any` type works. Is there a better workaround than this? Perhaps declaring the type of that property in a declarations file?

*edit:* I found another workaround, I can declare an extra variable, export it from the event.ts and then import it and do a console.log (just to make sure it isn't compiled out). There's a bunch of logs in the console but it does load up.

**Comment by aluanhaddad** [comment]
This looks serious. It is not related to exporting an interface. It seems like it may be merging your Event interface with the dom Event for some reason. I am pretty condifdent this is the case because because if I change `"lib": ["dom", es2017"]` to `"lib": ["es2017"]`, _or_ if I rename the local `Event` interface to `Thing`, everything works as expected
Here is a minimal repro
```ts
interface Event { title: string; };

declare function property(target: Object, key: string): void;

export class SomeClass {
  @property event: Event;
}
```
This produces
```js
__decorate([
    property,
    __metadata("design:type", Event)
], SomeClass.prototype, "event", void 0);
```
But this
```ts
interface Thing { title: string; };

declare function property(target: Object, key: string): void;

export class SomeClass {
  @property event: Event;
}
```
Correctly produces
```js
__decorate([
  property,
  __metadata("design:type", Object)
], SomeClass.prototype, "event", void 0);
```

**Comment by omouse** [comment]
So I will use the workaround of renaming it from Event to something else.

Also I should have mentioned I'm targeting es5 and the libs I'm using are es2015 and dom.

**Comment by aluanhaddad** [comment]
@omouse More information is always helpful but this should work regardless.

**Comment by aluanhaddad** [comment]
I don't believe any of these changes should be necessary. I think this is a legitimate bug
