### ISSUE TITLE
Tuples are inferred as arrays, losing information

### ISSUE THREAD

**Issue by pelotom** [Microsoft/TypeScript#13151]
**TypeScript Version:**  2.1.4

The inferred type of a tuple expression is an array, for example

```ts
const foo = ['hello', 3, true] // foo: (string | number | boolean)[]
```

which is a pain when what you really wanted was a tuple; you need to give a type ascription in order to tell the compiler you meant it to be a tuple, e.g.

```ts
const foo: [string, number, boolean] = ['hello', 3, true]
```

It seems like this is wholly unnecessary, because the type `[string, number, boolean]` is assignable to `(string | number | boolean)[]`, and carries strictly more information. So the compiler is prematurely throwing away information, when it could just wait and see if later on the type needs to be specialized to an array.

**Comment by wallverb** [comment]
FYI https://github.com/Microsoft/TypeScript/issues/11924#issuecomment-257029046

**Comment by pelotom** [comment]
Aha, mutability rears its ugly head once again :(

**Comment by aleksey-bykov** [comment]
There is a thread on adding special syntax for literals, including tuples: #10195
