### ISSUE TITLE
Salsa template intellisense not determined type by type of function callback

### ISSUE THREAD

**Issue by Thaina** [Microsoft/TypeScript#13164]
I made a function like this

```js
/** @template T,U
 *  @param {T[]} arrays
 *  @param {function(T,number):Promise<U>} func
 *  @returns {Promise<U[]>} */
function AsyncEach(arrays,func) {
	var results = [];
	return arrays.reduce((promise,item,i) => {
		return promise.then(() => func(item,i)).then((res) => {
			results.push(res);
		});
	},Promise.resolve()).then(() => results);
}
```

then use it like this

```js
	var zz	= AsyncEach(league.results,(stat,i) => {
		return Promise.resolve(i);
	});
```

and expect `zz` it to return type `Promise<number[]>`

But I got this instead

![image](https://cloud.githubusercontent.com/assets/1042507/21471707/5c2d856e-caed-11e6-96b8-d5f005611156.png)

Using typescript 2.1.0-dev.20161031

**Comment by aluanhaddad** [comment]
Perhaps update?
![image](https://cloud.githubusercontent.com/assets/5034656/21471720/4ea9297a-ca89-11e6-9a79-8446432ba7f5.png)

**Comment by Thaina** [comment]
@aluanhaddad Is 2.2 released or still in dev state?

**Comment by aluanhaddad** [comment]
The latest release is 2.1.4 which is more recent than the version you are using but still demonstrates the issue.

**Comment by Thaina** [comment]
Thanks. I would wait for 2.2 release then
