### ISSUE TITLE
constant string in map initializing result in weird behaviour

### ISSUE THREAD

**Issue by Thaina** [Microsoft/TypeScript#13168]
I try to make a map object like this

```js
var abc = {
	["TTTT"]: [0,1,2,3]
};
```

And it result in intellisense like this

![image](https://cloud.githubusercontent.com/assets/1042507/21480786/0ad8b5b6-cb93-11e6-80e0-00469905402b.png)

While I was expect it to be

![image](https://cloud.githubusercontent.com/assets/1042507/21480793/26e2a56e-cb93-11e6-8fa6-9453e5cde367.png)

Because above will cause this kind of result

![image](https://cloud.githubusercontent.com/assets/1042507/21480806/7020f500-cb93-11e6-8092-e2958cda0423.png)

While below will be

![image](https://cloud.githubusercontent.com/assets/1042507/21480815/81108754-cb93-11e6-980d-8f2fb6727705.png)

This is typescript 2.2.0-dev.20161225

**Comment by aluanhaddad** [comment]
Why would you expect that? Computed properties that happen to have a string literal key are just like normal properties. They do not infer a string index signature. What you want is likely
```js
/**
 * @type {{[key:string]:number[]}}
 */
var abc = {
  ["TTTT"]: [0, 1, 2, 3]
};
```
Come over to the dark side, use TypeScript 😛

**Comment by Thaina** [comment]
I could just use this. More easy

```js
var abc = {
	["TTTT" + ""]: [0,1,2,3]
};
```

Well, actually I was expect that computed properties should always be map. Because we intentionally make it as computed property instead of normal properties

**Comment by mhegazy** [comment]
```ts
var abc = {
	["TTTT"]: [0,1,2,3]
};
```

is identical to

```ts
var abc = {
	"TTTT": [0,1,2,3]
};
```

if you want the resulting type to have an index signature, add a type annotation:

```ts
var abc: { [x: string]: number[] } = {
    ["TTTT"]: [0, 1, 2, 3]
};
```
