### ISSUE TITLE
Import aliases are not permitted in a global augmentation

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#13175]
Found from http://stackoverflow.com/questions/41336330/typescript-how-can-i-make-an-existing-namespace-global

```ts
export {};

declare global {
    namespace foo {
        export var a;
    }
    import bar = foo;
}
```

I believe this should yield no error, however, it gives back the error

```
Imports are not permitted in module augmentations. Consider moving them to the enclosing external module.
```

**Comment by aluanhaddad** [comment]
Interesting. I thought this was by design. It would definitely be convenient if this worked.
