### ISSUE TITLE
Discriminated Unions don't work on external types

### ISSUE THREAD

**Issue by berwyn** [Microsoft/TypeScript#13176]
I have an application that I've split up into multiple npm packages for cleanliness, however it seems that tsc cannot properly discriminate a union declared in an external package. When the type is imported and used in a `switch` block, the `case` arms do not narrow the type, instead always showing the type as the aggregate and not allowing narrowed members to be accessed. Similarly, `if` statements don't narrow the type at all, always instead showing the variable to be the aggregate type. The problem disappears if I pull the union type into the same source tree, or if I use a declaration file to inform the compiler that the union type exists, so it seems to only be for external packages.

Works:
- Union type is in same source tree as function consuming it
- Union type is declared in a declaration file in the same source tree as the function consuming it

Does not work:
- Union type is in a declaration file belonging to an external package

**TypeScript Version:**  2.1.4

**Code**

```ts
// packages/@namespace/actions/index.ts
export type ActionA = { type: 'A', foo: string }
export type ActionB = { type: 'B', bar: MyObject }
export type ActionC = { type: 'C', baz: number }
export type Action = ActionA | ActionB | ActionC

// packages/@namespace/reducers/index.ts
import { Action } from '@namespace/actions'

const initialState = { ... }
export function reduce(state = initialState, action: Action) {
  switch(action.type) {
    case 'A':
      console.log(action.foo) // Error property 'foo' doesn't exist on type 'Action'
    ...
  }
}

```

**Expected behavior:**
`Action` is narrowed to type `ActionA`

**Actual behavior:**
`Action` is not narrowed at all, and only union members are available

**Comment by weswigham** [comment]
@berwyn Is this still an issue for you on our nightlies? I went to go look in to this and found the test I wrote already behaving as expected.
