### ISSUE TITLE
Incorrect metadata emitted for property decorators when the property type is inferred (e.g. from an assignment), but not explicitly defined.

### ISSUE THREAD

**Issue by JohnWeisz** [Microsoft/TypeScript#13174]
**TypeScript Version:**  2.1.4

**Code**

```ts
function PropDeco(target: Object, propKey: string | symbol) { }

class Foo {
    @PropDeco
    public foo = "bar";
}

```

**Expected behavior:**

Since the runtime type (constructor reference) of `Foo.foo` is supposed to be `String`, the compiler should emit `String` as the type of `Foo.foo`, as it does when the property has an explicitly defined type (i.e. `foo: string = "bar"`):

```ts
__metadata("design:type", String)
```

**Actual behavior:**

The compiler emits `Object` as the type of `Foo.foo`, which I believe is incorrect:

```ts
__metadata("design:type", Object)
```

**Comment by JohnWhiteTB** [comment]
The issue is also observable with getters/setters:

```ts
@PropDeco
public get foo() { return "bar" }
```

will emit:

```ts
__metadata("design:type", Object),
```

**Comment by mhegazy** [comment]
Looking at this issue again, this working as intened. We want to emit the same code regardless of what the type system thinks your code is. The scenario here is using the `transpile`/`transpileModule` functions where the whole project is not loaded, just a single file. so consider: 
```ts
import {imported} from “./another”; 
class C { 
    @dec 
    public s = imported;
}
```

We want this to be always be the same type, and that is not possible if you call `transpile`/`transpileModule` since the other module is not loaded.

MetaData will only be whatever the *explicitlly* declared type annotation.

**Comment by JohnWeisz** [comment]
Although I understand the limitations described here, I respectfully disagree that this should be, or would be generally _working as intended_, at least in the scope of this single issue. I'm not aware of the implementation of the metadata type-serialization system in TypeScript, but this _seems_ wrong:

 > MetaData will only be whatever the explicitlly declared type annotation.

In practice, this means that a property with an _explicitly_ declared type annotation and a property with an _inferred_ type are semantically _two different things_. Two different things which, while identical at compilation, are deemed different at runtime.

```ts
class C { 
    @dec
    public s = 7;

    @dec
    public s2: number = 7;
}
```

To the best of my knowledge, `C.s` and `C.s2` are treated identically regarding their types. I see no reason it should be intentional for them to be treated differently at runtime, unless this is a serious limitation we are talking about, that would require disproportionately large amounts of work to get around.

**Comment by mhegazy** [comment]
@JohnWeisz, is this is a limitation of the current system. we would be open to suggestions on how to support the [scenario](https://github.com/Microsoft/TypeScript/issues/13174#issuecomment-270244631) i have outlined above.
