### ISSUE TITLE
Issue in mapped types inference

### ISSUE THREAD

**Issue by ikeyan** [microsoft/TypeScript#13178]
**TypeScript Version:**  Playground and 2.1.4

**Code**

```ts
type SomeRequired<K extends keyof T, T> = Partial<T> & {
    [P in K]: T[P]
}
type ValueUnion<T> = T[keyof T];
type NonEmpty<T> = ValueUnion<{
    [P in keyof T]: SomeRequired<P, T>
}>

const x0: ValueUnion<{
    [P in keyof { a: number, b: string }]: SomeRequired<P, { a: number, b: string }>
}>
    = {b:""}; // OK
const x1: NonEmpty<{a: number, b: string}>
    = {b:""}; // Error
/*
Type '{ b: string; }' is not assignable to type 'SomeRequired<"a" | "b", { a: number; b: string; }>'.
  Type '{ b: string; }' is not assignable to type '{ a: number; b: string; }'.
    Property 'a' is missing in type '{ b: string; }'.
*/
```

[Playground](https://www.typescriptlang.org/play/#src=type%20SomeRequired%3CK%20extends%20keyof%20T%2C%20T%3E%20%3D%20Partial%3CT%3E%20%26%20%7B%0D%0A%20%20%20%20%5BP%20in%20K%5D%3A%20T%5BP%5D%0D%0A%7D%0D%0Atype%20ValueUnion%3CT%3E%20%3D%20T%5Bkeyof%20T%5D%3B%0D%0Atype%20NonEmpty%3CT%3E%20%3D%20ValueUnion%3C%7B%0D%0A%20%20%20%20%5BP%20in%20keyof%20T%5D%3A%20SomeRequired%3CP%2C%20T%3E%0D%0A%7D%3E%0D%0A%0D%0Aconst%20x0%3A%20ValueUnion%3C%7B%0D%0A%20%20%20%20%5BP%20in%20keyof%20%7B%20a%3A%20number%2C%20b%3A%20string%20%7D%5D%3A%20SomeRequired%3CP%2C%20%7B%20a%3A%20number%2C%20b%3A%20string%20%7D%3E%0D%0A%7D%3E%0D%0A%20%20%20%20%3D%20%7Bb%3A%22%22%7D%3B%20%2F%2F%20OK%0D%0Aconst%20x1%3A%20NonEmpty%3C%7Ba%3A%20number%2C%20b%3A%20string%7D%3E%0D%0A%20%20%20%20%3D%20%7Bb%3A%22%22%7D%3B%20%2F%2F%20Error)

**Expected behavior:**
The x0 and x1 lines should behave the same, because substituting NonEmpty<..> in the latter with its definition turns to be the latter type.

**Actual behavior:**
Only the x1 line gets an error.

**Comment by RyanCavanaugh** [comment]
These behave consistently now
