### ISSUE TITLE
[Docs] tsconfig.json link is wrong for 'React & Webpack` doc

### ISSUE THREAD

**Issue by yajiex** [Microsoft/TypeScript#13177]
For the "Add a TypeScript configuration file" part of ["React & Webpack" doc](https://www.typescriptlang.org/docs/handbook/react-&-webpack.html), there is a link pointed to `tsconfig.json`, which should be  https://www.typescriptlang.org/docs/handbook/tsconfig-json.html rather than https://www.typescriptlang.org/tsconfig-json.html

**Comment by dumblole** [comment]
@mhegazy The link is still broken, may I submit a PR to fix this?
