### ISSUE TITLE
Suggestion: "as exists" to tell CFA remove null and undefined from a Type

### ISSUE THREAD

**Issue by twoeo** [Microsoft/TypeScript#13170]
**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)
2.1.4

### Problem
Always we use `strictNullChecks` and Flow Analyse to find error at compile time.
But somewhere we do know the type and do not need CFA, such as:

```ts
interface Test{
  a?: {
    b: string;
  }
}

let tests: Test[] = [];
tests.filter(v=>v.a)
  .map(v=>v.a.b.substr(4))
  .forEach(v=>{
    console.log(v.a.b)
  })
```

Because of the prefilter `v=>v.a`, we can make sure that latter `v.a` is exists.
Of course it is not easy for CFA to accomplish this.

**It is always need to tell compiler whether a variable is exists.** (not `null` and not `undefined`)
But maybe not so always to change type A to type B.

### Suggestion
Consider a new grammer: `as exists`.
For example to code above:

```ts
tests.filter(v=>v.a)
  .map(v=>(v.a as exists).b.substr(4))  // as exists, to tell the CFA remove null and undefined here
  .forEach(v=>{
    console.log((v.a as exists).b)  // as exists, to tell the CFA remove null and undefined here
  })
```

**Comment by DanielRosenwasser** [comment]
We have the non-null assertion operator.

```ts
declare let x: number[] | undefined;

let xWithoutNullOrUndefined = x!;

x!.push(100);
```
