### ISSUE TITLE
Shorter syntax for optional return types

### ISSUE THREAD

**Issue by zakjan** [Microsoft/TypeScript#13184]
Currently there is shorter syntax for optional named fields, the question mark next to the field name, `field?: string` means `field: string | undefined`.

Could this syntax be extended from named fields to all types in general? For example `string?` would mean `string | undefined`.

It would allow using this shorter syntax in function return types:

**Proposed syntax:**
```ts
function identity(value: string?): string? {
    return value;
}
```

**Current syntax:**
```ts
function identity(value?: string): string | undefined {
    return value;
}
```
(This should stay supported for backward compatibility.)

**Comment by aluanhaddad** [comment]
@zakjan have fun in #7426
