### ISSUE TITLE
Single-element enums do not narrow to never

### ISSUE THREAD

**Issue by krryan** [Microsoft/TypeScript#13182]
**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)

**Code**

[In playground](http://www.typescriptlang.org/play/index.html#src=const%20enum%20One%20%7B%0D%0A%20%20%20%20Foo%20%3D%201%2C%0D%0A%7D%0D%0A%0D%0Aconst%20enum%20Two%20%7B%0D%0A%20%20%20%20Foo%20%3D%201%2C%0D%0A%20%20%20%20Bar%20%3D%202%0D%0A%7D%0D%0A%0D%0Afunction%20neverFn(n%3A%20never)%20%7B%20%7D%0D%0A%0D%0Afunction%20oneSwitch(one%3A%20One)%20%7B%0D%0A%20%20%20%20switch%20(one)%20%7B%0D%0A%20%20%20%20%20%20%20%20case%20One.Foo%3A%20break%3B%0D%0A%20%20%20%20%20%20%20%20default%3A%20neverFn(one)%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Afunction%20twoSwitch(two%3A%20Two)%20%7B%0D%0A%20%20%20%20switch%20(two)%20%7B%0D%0A%20%20%20%20%20%20%20%20case%20Two.Foo%3A%20break%3B%0D%0A%20%20%20%20%20%20%20%20case%20Two.Bar%3A%20break%3B%0D%0A%20%20%20%20%20%20%20%20default%3A%20neverFn(two)%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Afunction%20oneIfElse(one%3A%20One)%20%7B%0D%0A%20%20%20%20if%20(one%20%3D%3D%3D%20One.Foo)%20%7B%0D%0A%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20else%20%7B%0D%0A%20%20%20%20%20%20%20%20neverFn(one)%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Afunction%20twoIfElse(two%3A%20Two)%20%7B%0D%0A%20%20%20%20if%20(two%20%3D%3D%3D%20Two.Foo)%20%7B%0D%0A%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20else%20if%20(two%20%3D%3D%3D%20Two.Bar)%20%7B%0D%0A%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20else%20%7B%0D%0A%20%20%20%20%20%20%20%20neverFn(two)%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A)

```ts
const enum One {
    Foo = 1,
}

const enum Two {
    Foo = 1,
    Bar = 2
}

function neverFn(n: never) { }

function oneSwitch(one: One) {
    switch (one) {
        case One.Foo: break;
        default: neverFn(one);
    }
}

function twoSwitch(two: Two) {
    switch (two) {
        case Two.Foo: break;
        case Two.Bar: break;
        default: neverFn(two);
    }
}

function oneIfElse(one: One) {
    if (one === One.Foo) {

    }
    else {
        neverFn(one);
    }
}

function twoIfElse(two: Two) {
    if (two === Two.Foo) {

    }
    else if (two === Two.Bar) {

    }
    else {
        neverFn(two);
    }
}
```

**Expected behavior:**
`one` and `two` are both narrowed to `never` in the `default` case for their respective `Switch` functions, and in the `else` case for their respective `IfElse` functions, making them valid arguments to the `neverFn` call.

**Actual behavior:**
`two` narrows correctly, but the `neverFn` call in `oneSwitch` and `oneIfElse` has the error

>Argument of type `One` is not assignable to parameter of type `never`.

**Comment by aluanhaddad** [comment]
Aren't these contradictions in terms?

**Comment by wallverb** [comment]
See https://github.com/Microsoft/TypeScript/issues/12771
