### ISSUE TITLE
support of native async/await is missing 

### ISSUE THREAD

**Issue by dharmax** [Microsoft/TypeScript#13197]
**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)

**Code**

```ts

async function f() {
 let value = await anotherAsyncFunction()
  ....
}
```

**Expected behavior:**
If target type is set to ES7 (which it currently doesn't even support) it should leave the above code _as is_, since the current versions of Node already support it (and it is much easier to debug, too).

**Actual behavior:**
1. Currently it generates the __awaiter code and uses yield, etc.
1. There's no support for target type es7

**Comment by alitaheri** [comment]
@dharmax es doesn't follow that versioning semantic anymore. use `es2017`.

**Comment by aluanhaddad** [comment]
`--target esnext` should disable all transformations that are not module format related.
@alitaheri did they ever?😝

**Comment by dharmax** [comment]
:+1: 
@alitaheri oh, i see. I gave it a try and indeed it outputs the right code now. However, seems like my node doesn't understand async, although it's version 7.3....

**Comment by blakeembrey** [comment]
@dharmax it's still behind a flag, try `node --harmony-async-await`.
