### ISSUE TITLE
Provide a lib.win.d.ts file for Windows

### ISSUE THREAD

**Issue by jonathandturner** [Microsoft/TypeScript#1319]
One suggestion we heard from some of the testing inside MS is that it'd be helpful to have a revised lib.d.ts that was geared for Windows development.  Here's the original request:

"To support WWA development with TypeScript, we discussed adding a new lib.win.d.ts file for Windows development that tailors the DOM and system types to WWA development. The priority item called out right now is to modify the constructors for typed arrays to explicitly accept Windows.Storage.Steam.IBuffer objects in constructors.
 
This may be as simple as altering typed array definitions here to look like the following, with the IBuffer signature added to the existing list of constructors:

```ts
declare var Uint32Array: {
    prototype: Uint32Array;
    new (length: number): Uint32Array;
    new (array: Uint32Array): Uint32Array;
    new (array: number[]): Uint32Array;
    new (buffer: ArrayBuffer, byteOffset?: number, length?: number): Uint32Array;
    new (buffer: Windows.Storage.Streams.IBuffer, byteOffset?: number, length?: number): Uint32Array;
    BYTES_PER_ELEMENT: number;
}
```
 
This does place a hard dependency in lib.win.d.ts on a winrt.d.ts with the definition of IBuffer. We may want to consider just making it possible to extend the typed array constructors external to the lib.win.d.ts file and then include an overload with the IBuffer constructor inside of a winrt.d.ts. Similar to:
 
```ts
interface Uint32ArrayConstructor {
    prototype: Uint32Array;
    new (length: number): Uint32Array;
    new (array: Uint32Array): Uint32Array;
    new (array: number[]): Uint32Array;
    new (buffer: ArrayBuffer, byteOffset?: number, length?: number): Uint32Array;
    BYTES_PER_ELEMENT: number;
}

declare var Uint32Array: Uint32ArrayConstructor;
```

**Comment by mhegazy** [comment]
This is out of scope in the current time. https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/winrt/winrt.d.ts is a better place for such definitions.
