### ISSUE TITLE
Visual Studio 2015 with TypeScript 2.1.4 extension provides incorrect "Cannot find module" Intellisense

### ISSUE THREAD

**Issue by ryanelian** [Microsoft/TypeScript#13194]
**TypeScript Version:**  2.1.4

**Code**

Any package will do, as long as you don't install the `@types` for the said package. (According to https://blogs.msdn.microsoft.com/typescript/2016/12/07/announcing-typescript-2-1/ it's now possible.)

```ts
import * as uib from 'angular-ui-bootstrap';
```

Using `tsc` from the project root folder compiles the source without issues.

**Expected behavior:**

No squiggly line because `angular-ui-bootstrap` is installed in my `node_modules` folder and the source can be compiled by `tsc` without errors.

**Actual behavior:**

Visual Studio gives you squiggly red lines: `Cannot find module 'angular-ui-bootstrap'`

Interestingly, the import syntax which lets you import a module without using it as a variable does not cause squiggly lines:

```ts
import 'bootstrap-sass/assets/javascripts/bootstrap';
```

Also, Visual Studio Code does not give squiggly lines.

**Comment by dustin-page** [comment]
I have the same issue. Spent a couple of hours trying to fix it and didn't get anywhere.

**Comment by jpleclerc** [comment]
Very annoying problem. It can be solved by restarting VS.
