### ISSUE TITLE
λ return object

### ISSUE THREAD

**Issue by kgtkr** [Microsoft/TypeScript#13207]
let func=(val:number)=>{x:val};//error
let func=(val:number)=>{return {x:val};};//ok

**Comment by mhegazy** [comment]
The first line is, unfortunately , a valid JS grammar production. the `{}` represent the body of the function, the `x` is a label, the `val` is an expression, the function as a whole implicitly returns `undefined`.

you can wrap it in parans to avoid this. e.g. 
```ts
let func1 = (val: number) => ({ x: val });
```

**Comment by kgtkr** [comment]
thank you
