### ISSUE TITLE
Generic types are incorrectly narrowed by instanceof

### ISSUE THREAD

**Issue by ylepikhov** [Microsoft/TypeScript#13211]
**TypeScript Version:**  2.1.4
[see in playground](https://www.typescriptlang.org/play/index.html#src=class%20A%3CT%3E%20%7B%0D%0A%0D%0A%20%20%20%20constructor(readonly%20a%3A%20string)%20%7B%20%7D%0D%0A%7D%0D%0A%0D%0Aclass%20B%3CT%3E%20%7B%20%0D%0A%0D%0A%20%20%20%20%2F%2F%20uncomment%2C%20to%20partially%20fix%20type%20inference%20below%0D%0A%20%20%20%20%2F%2Fprivate%20fix%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Atype%20C%3CT%3E%20%3D%20A%3CT%3E%20%7C%20B%3CT%3E%3B%0D%0A%0D%0Afunction%20acceptA%3CT%3E(a%3A%20A%3CT%3E)%20%7B%20%7D%0D%0A%0D%0Afunction%20acceptB%3CT%3E(b%3A%20B%3CT%3E)%20%7B%20%7D%0D%0A%0D%0Afunction%20test%3CT%3E(x%3A%20C%3CT%3E)%20%7B%0D%0A%0D%0A%20%20%20%20if%20(x%20instanceof%20B)%20%7B%0D%0A%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20must%20be%20compile%20error!%0D%0A%20%20%20%20%20%20%20%20acceptA(x)%3B%20%2F%2F%20x%20is%20of%20A%3CT%3E%20type%2C%20while%20B%20has%20no%20members%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20if%20(x%20instanceof%20A)%20%7B%0D%0A%0D%0A%20%20%20%20%20%20%20%20acceptA(x)%3B%20%2F%2F%20x%20is%20of%20A%3Cany%3E%20type%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%7D)
**Code**

```ts
    class A<T> {

        constructor(readonly a: string) { }
    }

    class B<T> { 

        // uncomment, to partially fix type inference
        //private fix: string;
    }

    type C<T> = A<T> | B<T>;

    function acceptA<T>(a: A<T>) { }

    function acceptB<T>(b: B<T>) { }

    function test<T>(x: C<T>) {

        if (x instanceof B) {

            // must be compile error!
            acceptA(x); // x is of A<T> type, while B has no members
        }

        if (x instanceof A) {

            acceptA(x); // x is of A<any> type
        }

    }
```

**Expected behavior:**

Line 23: Must be a compile error. Type of variable `x` must be `B<T>` (I hope so).
Line 28: Type of variable `x` must be `A<T>`.

**Actual behavior:**

Line 23: No compile error. Type of variable `x` is (highlighted as) `A<T>`.
Line 28: Type of variable `x` is `A<any>`.

If uncomment Line 9, then there is compile error at line 23, but type of variable `x` is `B<any>`.

**Comment by DanielRosenwasser** [comment]
Here's what I think is happening -  we have `isTypeInstanceof`:

```ts
// A type S is considered to be an instance of a type T if S and T are the same type or if S is a
// subtype of T but not structurally identical to T. This specifically means that two distinct but
// structurally identical types (such as two classes) are not considered instances of each other.
function isTypeInstanceOf(source: Type, target: Type): boolean {
    return source === target || isTypeSubtypeOf(source, target) && !isTypeIdenticalTo(source, target);
}
```

Is it possible that `source === target` is not going to be true here given that `B<T>` is generic on `T`? In other words, won't different instantiations of `B` be two distinct types?

**Comment by DanielRosenwasser** [comment]
Indeed, if you remove the type parameter on `B`, you get the "correct" behavior. [Try it in the playground](https://www.typescriptlang.org/play/#src=%20class%20A%3CT%3E%20%7B%0D%0A%0D%0A%20%20%20%20%20%20%20%20constructor(readonly%20a%3A%20string)%20%7B%20%7D%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20class%20B%20%7B%20%0D%0A%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20uncomment%2C%20to%20partially%20fix%20type%20inference%0D%0A%20%20%20%20%20%20%20%20%2F%2Fprivate%20fix%3A%20string%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20type%20C%3CT%3E%20%3D%20A%3CT%3E%20%7C%20B%3B%0D%0A%0D%0A%20%20%20%20function%20acceptA%3CT%3E(a%3A%20A%3CT%3E)%20%7B%20%7D%0D%0A%0D%0A%20%20%20%20function%20acceptB%3CT%3E(b%3A%20B)%20%7B%20%7D%0D%0A%0D%0A%20%20%20%20function%20test%3CT%3E(x%3A%20C%3CT%3E)%20%7B%0D%0A%0D%0A%20%20%20%20%20%20%20%20if%20(x%20instanceof%20B)%20%7B%0D%0A%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20must%20be%20compile%20error!%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20acceptA(x)%3B%20%2F%2F%20x%20is%20of%20A%3CT%3E%20type%2C%20until%20B%20has%20no%20members%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20%20%20%20%20if%20(x%20instanceof%20A)%20%7B%0D%0A%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20acceptA(x)%3B%20%2F%2F%20x%20is%20of%20A%3Cany%3E%20type%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20%7D).

**Comment by ylepikhov** [comment]
More on this, [see](https://www.typescriptlang.org/play/index.html#src=class%20A%20%7B%0D%0A%0D%0A%20%20%20%20constructor(readonly%20a%3A%20string)%20%7B%20%7D%0D%0A%7D%0D%0A%0D%0Aclass%20B%20%7B%20%0D%0A%0D%0A%20%20%20%20%2F%2F%20uncomment%2C%20to%20partially%20fix%20type%20inference%0D%0A%20%20%20%20%2F%2Fprivate%20fix%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Atype%20C%20%3D%20A%20%7C%20B%3B%0D%0A%0D%0Afunction%20acceptB(b%3A%20B)%20%7B%20%7D%0D%0A%0D%0Afunction%20test(x%3A%20C)%20%7B%0D%0A%0D%0A%20%20%20%20if%20(x%20instanceof%20B)%20%7B%0D%0A%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20must%20be%20compile%20error!%0D%0A%20%20%20%20%20%20%20%20acceptB(x)%3B%20%2F%2F%20x%20is%20of%20C%20type%2C%20until%20B%20has%20no%20members%0D%0A%20%20%20%20%7D%0D%0A%7D):

```ts
class A {

    constructor(readonly a: string) { }
}

class B { 

    // uncomment, to partially fix type inference
    //private fix: string;
}

type C = A | B;

function acceptB(b: B) { }

function test(x: C) {

    if (x instanceof B) {

        // must be compile error!
        acceptB(x); // x is of C type, until B has no members
    }
}
```

No generics. See line `acceptB(x); // x is of C type, until B has no members`
If you move mouse at `x` variable, you will see `(parameter) x: C` (same in VS Code).
If you uncomment `fix` member of class `B`, you will see `(parameter) x: B`.
