### ISSUE TITLE
Salsa: Include declaration files in different directories

### ISSUE THREAD

**Issue by SaschaNaz** [Microsoft/TypeScript#13213]
**TypeScript Version:**  nightly (2.2.0-dev.20161229)

**Situation**

I have an existing project written in pure JS. My file tree:

```
-declarations
  -node-foo.d.ts
  -node-bar.d.ts
-node_modules
  -foo/ (private)
  -bar/ (private)
  -baz/ (public)
  -@types/baz/ (public)
-sources
  -some.js
  -existing.js
  -source.js
  -in.js
  -pure.js
  -javascript.js
```

I want to add some node module declaration files for my private node modules. I added the modules on my package.json as `git+ssh` form to directly get them from git repositories. They are written in pure JS, so now I want to write some TS declaration for typing.

**Expected behavior:**

I should be able to include d.ts files from arbitrary directories as I can with TS project.

**Actual behavior:**

Salsa acquire types only from files within same directory ("sources" here).

**Comment by mhegazy** [comment]
Did you add path mapping? have you added them in the `include` in your jsconfig.json?

**Comment by SaschaNaz** [comment]
Yes, I added "declarations/node-foo.d.ts" or "declarations" or "declarations/*" but nothing worked.

**Comment by mhegazy** [comment]
can you share a sample i can look at?

**Comment by SaschaNaz** [comment]
Sorry for late response! I made a sample here: https://github.com/SaschaNaz/salsa-dts-sample/

Moving `es-cancelable.d.ts` into `scripts` folder suddenly activates typing, and returning it to `declarations` folder makes its type `any`.

**Comment by mhegazy** [comment]
thanks @SaschaNaz. 

I am a bit confused about what you want to do in `es-cancelable.d.ts`. you have at the top `import * as PG from "pg";` which makes this file a module, yet you do not export any thing. then you have a `declare module "es-cancelable" {` which is an "augmentation", to the same module!

i would say you should just stick with a modul, e.g.

```ts
/// declarations/es-cancelable.d.ts
import * as PG from "pg";

export class Foo {
    ...
}
```

and in your jsonfig.json add `paths` mapping:

```ts
{
    "compilerOptions": {
        "target": "es2015",
        "baseUrl": "./",
        "paths": {
            "*" :["declarations/*", "*" ]
        }
    },
    "typeAcquisition": {
        "enable": true
    }
}
```

then you should see:

![animation](https://cloud.githubusercontent.com/assets/8000722/21571816/d8aa3f5e-ce87-11e6-8774-9f85b1e2ba64.gif)

**Comment by SaschaNaz** [comment]
Great, now it works as expected! The `es-cancelable.d.ts` is newly written just to make a minimal repro. I hope TS language service show an error or a warning for this case rather than failing silently to resolve, should I open a new issue?

**Comment by mhegazy** [comment]
errors are disabled if you are using a jsconfig.json. we should be enabling more of htese errors as part of https://github.com/Microsoft/TypeScript/issues/6802

**Comment by mhegazy** [comment]
the easiest way is to add a tsconfig.json on this folder, and open the files from this folder first. also running `tsc` in this folder would give you errors.
