### ISSUE TITLE
Unexpected Operator '===' cannot be applied to types 'false' and 'true'.

### ISSUE THREAD

**Issue by Strate** [Microsoft/TypeScript#13229]
**TypeScript Version:**  2.1.4

**Code**

```tsx
let a = false
function change() {
  a = true
}
change()
const b = a === true
```

**Expected behavior:**
No error

**Actual behavior:**
error TS2365: Operator '===' cannot be applied to types 'false' and 'true'.

**Comment by RyanCavanaugh** [comment]
See #9998. Can I ask how you didn't find #11178 or #12772 when searching?

**Comment by Strate** [comment]
@RyanCavanaugh sorry for that, I thought that '==' and '===' is notable difference for that case.
