### ISSUE TITLE
`isNaN()` should accept any value (in type definition)

### ISSUE THREAD

**Issue by KostyaTretyak** [Microsoft/TypeScript#13227]
**TypeScript Version:**  2.1.4

**Code**

```ts
isNaN('222');
```

**Expected behavior:**
Works without error

**Actual behavior:**
Throw error:
> [ts] Argument of type '"222"' is not assignable to parameter of type 'number'.

**Comment by KostyaTretyak** [comment]
This also applies to `Number.isInteger()`, `Number.isNaN()` methods.

For example, I have the following code:

```ts
function some(one: string | number)
{
  if( Number.isInteger(one) )
  {
    // Code...
  }
}
```

Why TypeScript throwing error?

> Argument of type 'string | number' is not assignable to parameter of type 'number'.
  Type 'string' is not assignable to type 'number'.

**Comment by DickvdBrink** [comment]
@RyanCavanaugh explained it pretty clear in this issue why it is the way it is
https://github.com/Microsoft/TypeScript/issues/4002#issuecomment-124201510

So it is by design
