### ISSUE TITLE
Checkbox selected value

### ISSUE THREAD

**Issue by Ashwani44** [Microsoft/TypeScript#13221]
I am making a small static demo in angular 2
I have 3 checkboxes and the user will make the selection as required.
I wish to save the selected checkbox values on button click  in table, in horizontal manner, separated by comma.
e.g
here is my table with only one column :
Skills 
Angular2,Typescript,HTML5

So far i have done this :
----------------------------
### subject.ts

export interface ISkills
{
     _skillID:number,
     _skillName:string
}
-----------------------------------------
### subject.component.ts

import { Component, OnInit } from '@angular/core';
import {ISkills} from './../Student/subject';
@Component({
     selector: 'stud',
     templateUrl: 'app/Student/subject-list.component.html'
})
export class StudentComponent implements OnInit {
     checked = false;

    sk:ISkills[]=[{
         _skillID:1,
         _skillName:'Angular 2'
    },
    {
          _skillID:2,
         _skillName:'Typescript'
    },
    {
          _skillID:3,
         _skillName:'HTML 5'
    }]
     constructor() { }

     ngOnInit() {
          this.checked=!this.checked;
      }
}
------------------------------------------------
**subject.component.html**

         <md-card>
    <md-card-content>
        <section class="example-section">
            <md-checkbox class="example-margin" *ngFor="let item of sk">{{item._skillName}}</md-checkbox>
        </section>
        
        <button type="button">Submit</button><br/><br/>

        <h4>My Table below :</h4>
        <table>
            <thead>
                <tr>
                    <th>Skills</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td></td>
                </tr>
            </tbody>
        </table>
    </md-card-content>
</md-card>
---------------------------------------------------------------
can anybody tell me how do i get the value separated with comma on my table.
Any help would be much appreciated

**Comment by RyanCavanaugh** [comment]
This is a bug tracker, not a general support forum. **Read the issue template**.
