### ISSUE TITLE
New Website Logo: WhereDat

### ISSUE THREAD

**Issue by odedhb** [Microsoft/TypeScript#13226]
Please fill the following out:

- Name: WhereDat
- Homepage url: https://wheredatapp.com
- Brand Guidelines/Licensing: free to use
- Logo: https://static1.squarespace.com/static/555a85bfe4b04d1c654b1c08/586634811b631bc753055f7d/5866349a440243e45d7c0c7f/1483093294611/blue_logo_no_text.png?format=2500w

**Comment by DanielRosenwasser** [comment]
HereDat: https://www.typescriptlang.org/community/friends.html

Thanks!
