### ISSUE TITLE
Module Variable Assignment Issue

### ISSUE THREAD

**Issue by todd** [Microsoft/TypeScript#13222]
**TypeScript Version:**  2.0.8 / 2.1.4

Attempting to migrate from TS 1.8 to 2.x.

**Code**

```ts
// myApp.ts
import * as MyLogger from "my-logger";
MyLogger.requestMetadataMapper = () => {
    // Does some stuff
}
```

```ts
// Declaration file for MyLogger
import * as winston from "winston";
import * as express from "express";

export var loggerMetadata: {};
export var sequencenumber: number;
export var requestMetadataMapper: any;

// Additional contents truncated
```

**Expected behavior:**
Compiles cleanly.

**Actual behavior:**
`error TS2540: Cannot assign to 'requestMetadataMapper' because it is a constant or a read-only property.`

`requestMetadataMapper` isn't defined as a `const`, so I would expect reassignment to be allowed. This worked properly in TypeScript 1.8.

**Comment by mhegazy** [comment]
This matches the ES6 spec for modules. The export bindings on the module object as well as the module object itself are immutable.

**Comment by mhegazy** [comment]
here is the reference to the spec: http://www.ecma-international.org/ecma-262/6.0/#sec-module-namespace-exotic-objects

**Comment by todd** [comment]
Thanks, @mhegazy. I wasn't aware of that part of the spec. Appreciate the quick response.
