### ISSUE TITLE
No straightforward/stable way to consume lib/tsserverlibrary.js

### ISSUE THREAD

**Issue by joelday** [Microsoft/TypeScript#13236]
**TypeScript Version:**  2.\*.\*-\*

**Code**
This is in a project that needs to use tsserverlibrary.js:

test.ts:
```ts
import * as ts from "typescript/lib/tsserverlibrary";
```
Because tsserverlibrary.d.ts is not a module:
```ts
/// <reference ...
declare module "typescript/lib/tsserverlibrary" {
    export = ts;
}
```

This still fails due to the following line in tsserverlibrary.d.ts, which in an installed package, resolves to the nonexistent file node_modules/src/types.d.ts:
```ts
/// <reference path="../../src/server/types.d.ts" />
```

With a custom copy of tsserverlibrary.d.ts, `const ts = require(...` is a potential option, but options for consuming `ts` as the declared namespace instead of `any` are clumsy.

**Expected behavior:**
Consumer of the TypeScript Node package can import tsserverlibrary.js without issue.

**Comment by mhegazy** [comment]
We should make the .d.ts file a module; we do that as part of the build already for typescript.d.ts; a PR would be appreciated.

**Comment by joelday** [comment]
Thanks, @mhegazy! Any suggestions/details I should know on resolving the types.d.ts reference? There are reference tags down the tree that refer to .ts files as well. I assume the .js file export the ts global?

I'll look at the existing lib generation code and go from there.

**Comment by joelday** [comment]
@mhegazy Submitted a PR. Thanks!
