### ISSUE TITLE
codefix for adding type parameter

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#13237]
unknown identifier in a type position should be considered for fixing by adding a corresponding type parameter:

```typescript
// Media, At, and Value are all unknown identifiers in this scope
// it would be helpful if a codefix could declare them as type parameters
function valueAt(media: Media, at: At): Value { // <-- unknown identifiers
}

// expected and fixed
function valueAt<Media, At, Value>(media: Media, at: At): Value {
}
```

**Comment by aleksey-bykov** [comment]
### ALSO NOTE

that it's not always preferable to add type parameters immediately to the closest scope, sometimes it makes sense to add them higher scopes:

```
// another expected fix:
function toBeingTraveling<Media, At, Value>() { // <-- type parameters might go higher
   function valueAt(media: Media, at: At): Value {
   }
}
```

**Comment by RyanCavanaugh** [comment]
General observation from the field is that people use type parameters way more often than they should; would rather not encourage this.

**Comment by aleksey-bykov** [comment]
let me put it in my wisdom book, also can i order a mug with this message?
