### ISSUE TITLE
Compilation error when Enum type variable wrapped with if clause.

### ISSUE THREAD

**Issue by mahyari** [microsoft/TypeScript#13238]
**TypeScript Version:**  2.0.10

**Code**

```ts
  transform(value:any, supportUnit?: SupportUnitTypes): any {
...
    let temp = "Some Text 0";
    if(supportUnit){
      switch(supportUnit) {
        case SupportUnitTypes.technical:
          temp+= "Some text 1";
          break;
        case SupportUnitTypes.business:
          temp+= "Some text 2";
          break;
        case SupportUnitTypes.manager:
          temp+= "Some text 3";
      }
    }
...
  }
```

**Expected behavior:**
if supportUnit is not null, complete temp base on it's value.

**Actual behavior:**
Compilation error on SupportUnitTypes.technical (first case) if wrapped with `if(supportUnit){}` block!

**Comment by vladima** [comment]
Let me guess: `SupportUnitTypes.technical` either implicitly or explicitly has value 0. If statement will filter out all falsy values so switch case for `technical` will never be hit

**Comment by aluanhaddad** [comment]
@mahyari as @vladima hinted, just change
```ts
if (supportUnit) {
```
to
```ts
if (supportUnit !== undefined) {
```
and all will be well :)

**Comment by Goodwine** [comment]
The problem is that this error prone, as in... it's very easy to forget to start your enum at `1` or check `foo != null`. It would be great if there would be a compiler/linter error for `if (someEnum)`, or that typescript starts all enums at 1 instead of 0.
