### ISSUE TITLE
tsc incremental compilation rewrites all files on docker (for windows) volume

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/TypeScript#13242]
**TypeScript Version:**  nightly (2.2.0-dev.201xxxxx)

tsc incremental compilation rewrites all compiled files on docker volume (docker for windows)

To reproduce it:
- [install docker for windows](https://docs.docker.com/docker-for-windows/) or try with your instlaled docker
- create dir and make `npm init`
- `npm install typescript@next`
- create two files `1.ts` and `2.ts` with some code.
- run tsc in docker `docker run --rm -v FULL_PATH_TO_YOUR_DIR:/app -w /app mhart/alpine-node:7.1.0 ./node_modules/.bin/tsc -w`
- see that tsc created both files `1.js` and `2.js`
- wait some minute then change the code of only `1.ts`
- tsc will recompile 
- see the date for `1.js` and `2.js`, you will see that `2.js` too has been rewritten, though it should not be the case (it is not the case if you run tsc without docker windows)

This happens due to this check:
https://github.com/Microsoft/TypeScript/blob/e4b81d03311ae157486dd2ebbd7d381996066174/src/compiler/program.ts#L148

and that `ts.getModifiedTime` returns strange result, probably this is not a typescript issue, but docker/node, but an issue for typescript users.

**Btw what is a reason to check time modified, isn't the hash is just enough?**

Windows 10, docker for windows 1.12.5 (this the same case should be for docker for mac)

**Comment by jngbng** [comment]
It also happens on Docker for mac and makes the docker keep consuming lots of cpu resources.

**Comment by jngbng** [comment]
I found the reason why the cpu is pegged at 100% from here:
https://forums.docker.com/t/docker-compose-volumes-gulp-watch-100-cpu-usage/10192/7

TSC uses fs.watchFile as well (https://github.com/Microsoft/TypeScript/blob/e4b81d03311ae157486dd2ebbd7d381996066174/src/compiler/sys.ts#L464) and suffers the same problem.

**Comment by mhegazy** [comment]
@sheetalkamat is there anything we can do here?

**Comment by sheetalkamat** [comment]
@mhegazy this seems like same as #19762 and i am in final stages of prototyping few different behaviors for watching files/directories to get feedback and we can make decision afterwards
