### ISSUE TITLE
Missing onresourcetimingbufferfull event from Performance interface

### ISSUE THREAD

**Issue by ghost** [microsoft/TypeScript#13249]
The resource timing API have events like onresourcetimingbufferfull which gets fired when the limit of 150(by default) resources has been reached.
https://www.w3.org/TR/resource-timing-1/#extensions-performance-interface

The Performance interface in lib.d.ts file does not have onresourcetimingbufferfull event defined in it.

**Comment by Toxyxer** [comment]
This seems to be fixed now. It's been added in this [commit](https://github.com/microsoft/TypeScript/commit/f960d5c97fc19c6b6613214dcb57421429fbfc80#diff-0ce6916552af501746c004823c590d2aR10737).

**Comment by jakebailey** [comment]
Just looking at old issues; this one is fixed per the above. Thanks for bisecting that.
