### ISSUE TITLE
Public methods not working when call in constructor for extended basic classes

### ISSUE THREAD

**Issue by mindonline** [Microsoft/TypeScript#13255]
**Playgorund:**
http://www.typescriptlang.org/play/#src=class%20List%20extends%20Array%20%7B%0D%0A%0D%0A%20%20%20%20public%20debug()%20%7B%0D%0A%20%20%20%20%20%20%20%20console.log(%22Length%20%3D%20%22%2C%20this.length)%3B%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20%0D%0A%20%20%20%20constructor%20()%7B%0D%0A%20%20%20%20%20%20%20%20super()%3B%0D%0A%20%20%20%20%20%20%20%20this.debug()%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Avar%20L%20%3D%20new%20List()%3B%0D%0A

**TypeScript Version:**  from  2.1.4 to  2.2.0-dev.20170102

**Code**

```ts
class List extends Array {

    public debug() {
        console.log("Length = ", this.length);
    }
    
    constructor (){
        super();
        this.debug();
    }
}

var L = new List();


```

**Expected behavior:**
Console output:
Length = 0

**Actual behavior:**

Uncaught TypeError: _this.debug is not a function
    at new List (<anonymous>:10:15)
    at <anonymous>:18:9
    at HTMLButtonElement.excuteButton.onclick (http://www.typescriptlang.org/play/playground.js:242)

**Emitted code TypeScript 2.1.4 and above:**

```js
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};
var List = (function (_super) {
    __extends(List, _super);
    function List() {
        var _this = _super.call(this) || this;
        _this.debug(); // THIS IS WRONG REF
        return _this;
    }
    List.prototype.debug = function () {
        console.log("Length = ", this.length);
    };
    return List;
}(Array));
var L = new List();

```

**Comment by j-oliveras** [comment]
Maybe related to: [Extending built-ins like Error, Array, and Map](https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#extending-built-ins-like-error-array-and-map-may-no-longer-work)

**Comment by ayyash** [comment]
I got the same result with my own classes... Extended classes, with methods of their own, they cannot be seen on runtime
```
interface iA {
    prop1: string;
}

interface iB extends iA {
   method1(): any;
}

class A implements iA{
// ...
    public prop1: string;
}

class B extends A implements iB {
// ... 
   public method1(): any {
       return 'any';
   }
}
```

// on run time
```
let something = new B();
something.method1() // method1  is not a function
```

**Comment by mhegazy** [comment]
Please see https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#generated-constructor-code-substitutes-the-return-value-of-super-calls-as-this for extending built in objects like `Array`, `Map`, `Set`, `Error` etc..

**Comment by ayyash** [comment]
So basically the following should fix it: 
fair enough but it kind of breaks the promise TypeScript is making 

```
Class B extends A implements iB {
     constructor(public prop1: string){
         super();
         Object.setPrototypeOf(this, B.prototype);
      }
      public method1(): any {
        return 'any';
      }
}
```

**Comment by mhegazy** [comment]
For completeness, you should be using `new.target` instead of `B`:

```ts
class B extends Array {
     constructor(){
         super();
         Object.setPrototypeOf(this, new.target.prototype);
      }
      public method1(): any {
        return 'any';
      }
}
```
