### ISSUE TITLE
Object.keys to use keyof

### ISSUE THREAD

**Issue by staeke** [Microsoft/TypeScript#13254]
**TypeScript Version:**  2.1.1

**Code**
With the latest `keyof` feature in TypeScript, I'd expect `Object.keys()` to return them. In code:

```typescript
interface ObjectConstructor {
  ...
  keys<T>(o: T): Array<keyof T>;
}
```

**Comment by jwbay** [comment]
See https://github.com/Microsoft/TypeScript/pull/12253#issuecomment-263132208

**Comment by aleksey-bykov** [comment]
you can make a local copy of `lib.d.ts` then turn off standard definition `--noLib` from command line or `"noLib"` from `tsconfig.json` and then rewrite the local `lib.d.ts` anyway you want, including a fix to `Object.keys`

**Comment by staeke** [comment]
@jwbay thanks. Anders's comment in the other thread makes perfect sense. I'll close this.
