### ISSUE TITLE
Function's return type does not varies based on its arguments. (with overloads) 

### ISSUE THREAD

**Issue by xLama** [Microsoft/TypeScript#13258]
**TypeScript Version:**  2.1.14

**Code**

```ts
function foo(name: number): number;
function foo(name: string): string;
function foo(name: string | number): string | number {
    if (typeof name === "number") {
        name; // name is number here
        return "foo"  // ¿?
    } else {
        name; // name is string here
        return 10 // ¿?
    }
}

let bar = foo("foo"); // Return a string but it is a number 

```

**Expected behavior:**

Error on return "foo" and return 10 becasue return types does not match with  their signatures.

**Actual behavior:**

No errors.

Reading specs we can find this:

Thus, using overloads it is possible to statically describe the manner in which a function's return type varies based on its arguments. 

https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#6.2

Worked as intented, maybe?

**Comment by DanielRosenwasser** [comment]
Right now there's no verification between any overload signatures and the implementation itself. Check out #13235 which requests this sort of functionality.
