### ISSUE TITLE
Modify emitter behaviour

### ISSUE THREAD

**Issue by tomitrescak** [Microsoft/TypeScript#13266]
Is it possible somehow to modify emitter behaviour, without recompiling the whole typescript lib?
I really like to use https://www.npmjs.com/package/jsx-control-statements but because of the I always have to use babel during my compilations and I'd like to skip that.

What I would modify is emitJSXOpening element and emitJSXClosing element.

**Comment by mhegazy** [comment]
We now have public emitter transformation API: https://github.com/Microsoft/TypeScript/pull/13940.
