### ISSUE TITLE
Fix has disappeared during the merge (affects npm 2.1.4 and master) - please reopen

### ISSUE THREAD

**Issue by Artazor** [Microsoft/TypeScript#13269]
**TypeScript Version:**  2.1.4 / nightly (2.2.0-dev.201xxxxx)

#12069 need to be reopened. It has been lost on merge.

**Comment by Artazor** [comment]
At least I see missing reversion of the commit https://github.com/Microsoft/TSJS-lib-generator/pull/148/commits/6609658c1770de6ae7256ca71e628ff52aa3719e

now we have **actual** code in lib.d.ts

```ts
interface DataTransfer {
       ...
       readonly types: string[];
       ...
}
```

instead of **expected**
```ts
interface DataTransfer {
       ...
       readonly types: DOMStringList;
       ...
}
```

ping @mhegazy

**Comment by mhegazy** [comment]
this is acctually per spec. From the [spec](https://html.spec.whatwg.org/multipage/interaction.html#datatransfer):

>   readonly attribute FrozenArray<DOMString> types;

it is a `DOMString[]` and not `DOMStringList`.

**Comment by Artazor** [comment]
Ah, ok, I've seen that it was DOMStringList in previous versions, and we have a code that relies on a DOMStringList (at least in signature). It means that we should change our code (a minor breaking change). You can close the issue
