### ISSUE TITLE
keyof to produce a runtime array

### ISSUE THREAD

**Issue by markboyall** [Microsoft/TypeScript#13267]
Put simply, I'd like a variant of keyof which produces the keys at runtime. E.g.,

```
interface Foo {
   prop1: number;
   prop2: string;
}

const x = keyof Foo;

```
In this case `x` should be `["prop1", "prop2"]`.

I've seen a few cases where people have tried to use `keyof` in somewhat-similar fashions, but they all wanted the actual keys *present in the object* at runtime. I however very explicitly *want* to ignore any properties present in any hypothetical runtime Foo objects that are not present in the interface.

Should permit generic parameters as the type.

**Comment by krryan** [comment]
Perhaps this could be generalized to turning a union of literal types (as `keyof Foo` is, being `'prop1' | 'prop2'`) into an array containing each member of the union once (`['prop1', 'prop2']`). I have a number of places I would like to see that, particularly for testing (have a test iterate over the array to make sure that each value supposedly acceptable to the union does, in fact, produce an appropriate result).

**Comment by aleksey-bykov** [comment]
in what order should these properties go?

**Comment by krryan** [comment]
I for one don't care; alphabetical, as-declared, officially-undefined, I just want it to be complete.

**Comment by aleksey-bykov** [comment]
i think it should be a codefix (refactoring) rather than a runtime facility:


```
// before                                

const x = keyof Foo;
          ^^^^^^^^^
```

```
// codefix                                
                      ______________________________________________
const x = keyof Foo; |                                              |
          ^^^^^^^^^ <   Replace with all names of `Foo` properties  |
                     |______________________________________________|
```

```
// after
const x = ["prop1", "prop2"];

```

**Comment by krryan** [comment]
It's better than nothing but it definitely doesn't do everything I had hoped for. For example, in my testing example, the entire point is ensuring complete coverage of the union for the test case. If a new item is added to the union, that array is still a valid array of items from that union, but it is no longer "complete"—some values from the union are not represented in the array.

**Comment by aleksey-bykov** [comment]
on the other hand, the fact that there is no way to know the order of names in which they will be listed is disturbing

in a meanwhile there is a hack:

```
const mySample : Foo {
   prop1: 0,
   prop2: ''
};
function toKeysBySample<T>(value: T): (keyof T)[] {
    return Object.keys(value);
}
const fooPropNames = toKeysBySample(mySample);
```

although it's not perfect either: https://github.com/Microsoft/TypeScript/pull/12253#issuecomment-263132208

**Comment by krryan** [comment]
That hack does nothing for the case of a union that isn't derived from `keyof` though.

**Comment by Igorbek** [comment]
> Should permit generic parameters as the type.

that wouldn't that easy

```ts
function keys<T>(): (keyof T)[] {
  return keyof T;
}
console.log(keys<{ a: number; }>());
console.log(keys<{ c: bool; }>());
```

what would it emit? Consider:
- no object of type `T` to pass to `Object.keys`
- `T` is generic, cannot emit static value at `keyof T`
- would need to introduce ambient parameter
  - pass it only if it is used?
  - need to resolve on call-site?
  - generics can be propagated through call stack
  - generics can be constructed from other generics (`T & G[]`)
  - `.d.ts` !

**Comment by aleksey-bykov** [comment]
a better hack that is almost to the point (yet has problems with unions)
```typescript
interface Foo {
    kind: 'a';
    value: number;
}
interface Baz {
    kind: 'b';
    text: string;
}
type Bar = Foo | Baz;
type Names<T> = {[P in keyof T]: P; }
function toKeysBySample<T>(names: Names<T>): (keyof T)[] {
    return Object.values(names);
}
toKeysBySample<Bar>({ kind: 'kind', text: 'text' });
```

**Comment by aleksey-bykov** [comment]
@Igorbek has a good point, if we remember that any type driven emit is taboo

**Comment by mhegazy** [comment]
As noted by @Igorbek and @aleksey-bykov, type directed emit is something that violate the TS goals of a [fully erasable type system](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals#goals).

Moreover, a `keyof T` is not guaranteed to be the **complete** list at runt time you would get from `Object.keys` since the TS types are not [exact/final](https://github.com/Microsoft/TypeScript/issues/12936).

For both reasons, this is out of scope for the TypeScript project at the time being.

**Comment by markboyall** [comment]
The second reason is the entire reason I wanted this feature. I *don't* want the complete runtime list. I want strictly and only the ones listed in the interface.

As for the first, I guess I just don't see why that should be a goal at all.

**Comment by SaschaNaz** [comment]
Probably a duplicate or at least a sub-issue of #1549.

**Comment by kimamula** [comment]
This is possible with custom transformers introduced in #13940.
See https://github.com/kimamula/ts-transformer-keys.

**Comment by gwicksted** [comment]
What about generating an enum at compile-time?

```ts
type A = { x: number, y: string };
enum B = keyof A; // as A exists right now during compilation
for (var enumMember in B) {
   console.log("enum member: ", enumMember);
}
```

which would write:

```bash
0
1
x
y
```

and would have the following JS code:

```ts
(function (B) {
    B[B["x"] = 0] = "x";
    B[B["y"] = 1] = "y";
})(B = exports.B || (exports.B = {}));
```

As to what order... doesn't matter to me.  I just want this to validate a JSON config file against a TypeScript Interface without requiring something like `ajv` or portions of `tsc` itself like `ts-transformer-keys`
