### ISSUE TITLE
make the quote symbol configurable for import codefix

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#13270]
currently the import codefix uses double quotes for the module path string literal which makes our linter unhappy, i wish the choice of a quote was configurable

**Comment by aluanhaddad** [comment]
Yes please, this is very frustrating.

**Comment by aleksey-bykov** [comment]
the temporary fix is rather trivial if you go `./node_modules/typescript/lib/*.js` and look for `"\""`

**Comment by DanielRosenwasser** [comment]
It'd be great if this was just inferred in cases where the option isn't explicit.

**Comment by aleksey-bykov** [comment]
yeah, just look around and do it as in 90% cases

**Comment by aleksey-bykov** [comment]
another thing to consider is that since codefixes emit "typescript" (not javascript, i beg you) code, the emitter should comply to some standards

namely the quote mark should be configured at the top level of the codefix emitter configuration, so that any codefix out there used it for emitting a propert quote symbol

**Comment by stijnvn** [comment]
A related thing to consider are quick fixes of missing interface implementations. The array type declarations should also be configurable.

For example `SomeType[]` versus `Array<SomeType>`.

**Comment by vytautas-pranskunas-** [comment]
do you have any idea when it is going to be fixed?

**Comment by mjbvz** [comment]
@mhegazy Marking as high-property for VSCode since we've seen a fair number of reports of this. We could add a workaround on our side to replace the quotes but other consumers of TypeScript would also benefit from this. Can we please target 2.3 with a fix?

**Comment by RyanCavanaugh** [comment]
Where should the configuration for this be stored?

I like the idea of inferring from the current file, though. It seems fine to make the user fix the first one themselves then the remainder are "correct"

**Comment by pgrm** [comment]
Inferring from the current file would be great. If there is nothing to infer from yet, it would be awesome if the tool could try to find a configuration for the [tslint quotemark rule](https://palantir.github.io/tslint/rules/quotemark/). Currently in VS Code I use auto import code fix, followed by the tslint code fix to change from double to single quote.

**Comment by vivainio** [comment]
Making it configurable is overkill. Just find the first quote character used the file and use that.

**Comment by logic01** [comment]
I agree with pgrm. The tslint.json quotemark rule is the perfect place to infer from.

**Comment by lukeautry** [comment]
Is there any precedent for TypeScript reading directly from tslint configuration?

**Comment by vivainio** [comment]
It would seem crazy to couple tsc to tslint.json for the corner case when there are zero quotes in the file. Just use either default value and let the user fix it for the first one.

**Comment by lukeautry** [comment]
For other folks looking for a workaround: if you use vscode, ```"tslint.autoFixOnSave": true``` in your settings.json will automatically fix these import quotations when you save the file. If you're importing something, you're going to save it anyway, right?

**Comment by asadsahi** [comment]
Agree with @RyanCavanaugh it should either be inferred from existing imports or perhaps controlled by tsconfig?

**Comment by cyrilletuzi** [comment]
Would be more consistent, as tslint is a optional tool for TypeScript, that there is a new option in tsconfig.json for quotes (which would also be the easiest thing to implement in TypeScript than scanning the files), and then that tslint can recover it in the future.

**Comment by shahata** [comment]
This is not just about quotes imo. Similarly, the spacing in imports should be configurable as well (`import { blah } from 'module'` vs `import {blah} from 'module'`).

**Comment by billfranklin** [comment]
Also, using relative vs absolute paths on the import statements is an issue.  IMHO, giving the user setting, by language, whether to use some type of linting or whether to use user settings would be ideal for me.

**Comment by aleksey-bykov** [comment]
@billfranklin the path will be absolute if you add `baseUrl` to `compilerOptions` in `tsconfig.json'

**Comment by whitecolor** [comment]
Yeah, `semicolon` is an issue too.

**Comment by MetodoDigital** [comment]
As @adyavanapalli very well mentioned, you can edit the **_typescript.json_** file to get around this issue on `/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/snippets/` for MacOS and `C:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\snippets\` for Windows.

Thx buddy.

**Comment by MetodoDigital** [comment]
As @adyavanapalli very well mentioned, you can edit the **_typescript.json_** file to get around this issue on `/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/snippets/` for MacOS and `C:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\snippets\` for Windows.

Thx buddy.

**Comment by filipesilva** [comment]
We have a similar issue in Angular CLI, and the approach we took was to allow our code generation to automatically run TS Lint on generated files with `--fix`. A bit of a overhead but it's really the only way to allow for the myriad of stylistic preferences.

**Comment by Bidthedog** [comment]
> @lukeautry For other folks looking for a workaround: if you use vscode, "tslint.autoFixOnSave": true in your settings.json will automatically fix these import quotations when you save the file. If you're importing something, you're going to save it anyway, right?

Note that this only works if you have the TSLint extension installed from here: https://marketplace.visualstudio.com/items?itemName=eg2.tslint

**Comment by Maximaximum** [comment]
> @lukeautry For other folks looking for a workaround: if you use vscode, "tslint.autoFixOnSave": true in your settings.json will automatically fix these import quotations when you save the file. If you're importing something, you're going to save it anyway, right?
Note that this only works if you have the TSLint extension installed from here: https://marketplace.visualstudio.com/items?itemName=eg2.tslint

Besides, what if I don't want tslint to fix other possible errors in my code?

**Comment by asadsahi** [comment]
@Maximaximum good point. I would still like auto-import feature to have an option to import with single or double quotes as configuration option.

**Comment by Amos47** [comment]
This may be out of scope of this issue, but I would also like to see us have the ability to change from a root based path to a relative path.

Using a root based path breaks our current build process, as we have multiple root entry points depending on the configuration.

**Comment by whitecolor** [comment]
@mhegazy maybe include this simple fix/feature in the nearest release?

**Comment by cengkuru** [comment]
adding ` "prettier.singleQuote":true,` did the trick for me

**Comment by asinitson** [comment]
It may be obvious, but I still think it is worth mentioning: you do not have to update your full project to the latest TypeScript if you are using Visual Studio Code. Just switch the editor to built-in version:

Click TypeScript version number (for example 2.3.4) between "TypeScript" and a little smiley face in the lower right corner. Then switch to Visual Studio Code built-in version (2.5.3 at this moment).

**Comment by tmueller** [comment]
Now, the quotestyle is not correctly inferred. Single quotes are always used, independent of previous usage of double quotes in import statements. Can't we simply make it configurable?

**Comment by jinder** [comment]
Yeah this now seems to have switched to single quotes

**Comment by aleksey-bykov** [comment]
forgive my stupid question, how are double-quote strings literals better than single-quoted ones when it comes to JavaScript?

**Comment by Maximaximum** [comment]
@aleksey-bykov IMO, there is no huge difference, it's just a matter of taste. However, it's important to maintain consistent style, at least within a signle project

**Comment by aleksey-bykov** [comment]
no doubt consistent style is very important

single-quoted strings are more preferable in JavaScript that deals with HTML and XML (97% of all applications) because it saves your from conflicts with double quoted strings used by said standards

**Comment by jinder** [comment]
@aleksey-bykov there is no "better" - just personal preference.  If you're using HTML/XML it's probably best to use the backticks `.

**Comment by aleksey-bykov** [comment]
i am just looking for any evidence (besides personal taste) that double quoted strings are worth being the default choice

**Comment by vivainio** [comment]
Here's some evidence: Prettier is using double quotes. With everybody gradually adopting prettier, we'll be back to double quote world soon.

Can't believe this bikeshedding is still going on - is it because the inference logic had a bug?

**Comment by mickdekkers** [comment]
@vivainio prettier has a `--single-quote` option.

**Comment by aluanhaddad** [comment]
@vivainio 

> Can't believe this bikeshedding is still going on - is it because the inference logic had a bug?

This was never a bug. This is a feature request. Also, it works correctly in the nightly builds. It's been fixed for a while.

@mickdekkers @vivainio 
> Here's some evidence: Prettier is using double quotes. With everybody gradually adopting prettier, we'll be back to double quote world soon.

Why would I want _another_ formatter operating on my `*.tsx?` files? I already have TypeScript and TSLint. Maybe if you are using a linter that does not format it would make sense. Everyone should use a linter.

**Comment by Maximaximum** [comment]
Today I've found out that the bug came back.

While using `VS Code`, when I use Typescript `v2.6.1` (the VSCode's version), the codefix uses single quotes, which is what I need.

However, when I switch to my project's version (Typescript `v2.4.2`), the codefix always uses double quotes.

Is there a way to force VSCode to use single quotes while runing Typescript `v2.4.2`? Do we need to apply a bugfix to Typescript `v2.4.2` and release a new, patched version `2.4.3`?

Note: I can't upgrade to use Typescript `v2.6.x` in my project right now.

**Comment by mjbvz** [comment]
@Maximaximum This is only fixed in TS 2.5+. There is no way to fix this with older TS versions

**Comment by Maximaximum** [comment]
@mjbvz Ok, thanks for letting me know

**Comment by smasala** [comment]
I'm using 2.6.2 and I'm getting double quotes :s

**Comment by PlugaruT** [comment]
yep, double quotes are used in 2.6.2

**Comment by PlugaruT** [comment]
I don't really know, I just started to write typescript so for me are just double quotes.

**Comment by mhegazy** [comment]
The original behavior was always double quotes. That was modified in #17750 to infer from the imports in the current file the quote style; this means that if this is the first import in the file there is no place to infer the style from and couple quotes will be used.
Issue https://github.com/Microsoft/TypeScript/issues/20619 tracks making it based on a configuration in your settings file.

**Comment by filipef101** [comment]
How do I disabled semicolons in auto imports?

**Comment by mhegazy** [comment]
tracked by https://github.com/Microsoft/TypeScript/issues/19882

**Comment by filipef101** [comment]
@mhegazy Hey thanks, I did that, but still the same, do I need to specify to use ts importer somehow? I still get a ; with auto imports

**Comment by mhegazy** [comment]
the suggestion of having semicolons being configurable is tracked by #19882. I did not say it was implemented.

**Comment by filipef101** [comment]
@mhegazy Oh, still, any idea? xd
And do you know if the line numbers can be disable or at least made shorter? they occupy a lot of space :(

**Comment by aluanhaddad** [comment]
@filipef101 line numbers are a general text editor feature. How are they related to TypeScript?

**Comment by miqmago** [comment]
Comented in https://github.com/Microsoft/vscode/issues/23559#issuecomment-302378477:

As @adyavanapalli very well mentioned, you can edit the typescript.json file to get around this issue on /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/snippets/ for MacOS and C:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\snippets\ for Windows.

Thx buddy.

**Comment by daniborgs** [comment]
On VS Code 1.21.1 you can correct this editing **/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-basics/snippets/typescript.json**

**Comment by cdoremus** [comment]
On Ubuntu Linux (VS Code 1.21.1), you need to edit `/usr/share/code/resources/app/extensions/typescript-basics/snippets/typescript.json`. 

In the 'Import external module' section of that file make the body array property to be the value `"import { $0 } from '${1:module}';"` The whose section will then look like this:
```
	"Import external module.": {
		"prefix": "import statement",
		"body": [
			"import { $0 } from '${1:module}';"
		],
		"description": "Import external module."
	},
```

**Comment by AdJesumPerMariam** [comment]
Since VSCode 1.24 (June 2018) there is an option for configuring this.

https://code.visualstudio.com/updates/v1_24#_preferences-for-auto-imports-and-generated-code

**Comment by AdJesumPerMariam** [comment]
Since VSCode 1.24 (June 2018) there is an option for configuring this.

https://code.visualstudio.com/updates/v1_24#_preferences-for-auto-imports-and-generated-code

**Comment by imcotton** [comment]
> Since VSCode 1.24 (June 2018) there is an option for configuring this.

But the `import statement` completion still gives you double quote :disappointed:

**Comment by Local9** [comment]
@imcotton only works with TypeScript 2.9 and higher from what I can find

**Comment by MurhafSousli** [comment]
Where is the fix? I have been going for an issue to an issue .. related to duplicated ... where is the fix? I have the latest version of vscode and still getting the double quote

**Comment by AdJesumPerMariam** [comment]
@MurhafSousli https://code.visualstudio.com/updates/v1_24#_preferences-for-auto-imports-and-generated-code

If you are still getting the double quote then your preferences.quoteStyle are probably either set to "double" or "auto". If it is set to "auto" (the default) then it infers the import style from existing imports. If there are no existing imports, then I believe it defaults to double quote. You can change preferences.quoteStyle (see above link) to "single" if you always want single quotes.

**Comment by Local9** [comment]
Recent update, the auto generated import is working as expected with single quotes. As for auto generated snipets these are still double quoted.

**Comment by corysimmons** [comment]
#### VSCode settings.json

```json
{
  "typescript.preferences.quoteStyle": "single"
}
```

No semis if you're cool:
```json
{
  "typescript.preferences.quoteStyle": "single",
  "typescript.format.semicolons": "remove"
}
```

Example:
```tsx
import Hello from 'components/Hello'

export default () => (
  <>
    <Hello />
    <h1>app</h1>
  </>
)
```

This issue can be locked.
