### ISSUE TITLE
how do i pass a class as a parameter

### ISSUE THREAD

**Issue by rentj1** [Microsoft/TypeScript#13281]
**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)

**Code**

```ts
// A *self-contained* demonstration of the problem follows...

```

**Expected behavior:**

**Actual behavior:**

**Comment by DanielRosenwasser** [comment]
From the issue template that you just posted with:

> ***QUESTIONS: This is not a general support forum! Ask Qs at http://stackoverflow.com/questions/tagged/typescript***

That said, here's how you'd do so:

```ts
class C {
}

function foo(c: typeof C) {

}

foo(C);
```
