### ISSUE TITLE
Compile fails to find types after adding import statement

### ISSUE THREAD

**Issue by indiescripter** [Microsoft/TypeScript#13286]
**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)

Something I've been stuck on for way too many hours. Not sure if a bug or my bother.
Initially things compile:

**Code**

 src/my.ts:

```ts
/// <reference path="../types/index.ts" />

const foo: Foo = "foo";
```

../types/index.ts:

```ts
type Foo = "foo";
```

However compile fails after adding import statement in ../types/index.ts:

../types/index.ts:

```ts
import * as fs from "fs";

type Foo = "foo";
```

**Errors**
```
src/my.ts(3,12): error TS2304: Cannot find name 'Foo'.
src/my.ts(3,12): error TS4025: Exported variable 'foo' has or is using private name 'Foo'.
```

My tsconfig is:

```
{
    "compilerOptions": {
      "target": "es2015",
      "lib": [
        "es2015"
      ],
      "module": "amd",
      "moduleResolution": "node",
      "declaration": true,
      "noUnusedLocals": false,
      "noUnusedParameters": false
    }
}
```

Compiling with aforementioned named files to single output file with --outFile command line option.

**Expected behavior:**

Should compile with import statement added

**Actual behavior:**

Doesn't compile

**Comment by basarat** [comment]
Adding an import makes it a module. I cover it here https://basarat.gitbooks.io/typescript/content/docs/project/modules.html 🌹
