### ISSUE TITLE
any type incorrectly inferred for async function result, differing from sync function result

### ISSUE THREAD

**Issue by IanYates** [Microsoft/TypeScript#13296]
**TypeScript Version:**  2.1.1   (current Playground as at 2017-01-05)

**Code**
Paste this into Playground

```ts
// A *self-contained* demonstration of the problem follows...

const asyncFunc = async () => {

    //doesn't matter - just something non-deterministic
    var r = Math.random();

    //one possibility - we return an array of ints
    if (r === 0) {
        return [1, 2, 3];
    }    

    //other possibility - we return a single int wrapped in an array
    if (r === 1) {
        return [4];
    }

    //an empty array (ought to be typed as int)
    return [];
    //NOTE: changing to    return new Array<int>();    fixes this
    
}

var funcResult = asyncFunc();  //type is Promise<any[]>.  Should be Promise<int[]>
```

**Expected behavior:**
The inferred type of funcResult should be Promise<int[]>

**Actual behavior:**
It is inferred as Promise<any[]>

Note that inference works correctly with the exact same code not using async/await (since the async function didn't do any awaiting).  By that I mean, this...

```ts

const func = () => {

    //doesn't matter - just something non-deterministic
    var r = Math.random();

    //one possibility - we return an array of ints
    if (r === 0) {
        return [1, 2, 3];
    }    

    //other possibility - we return a single int wrapped in an array
    if (r === 1) {
        return [4];
    }

    //an empty array
    return [];
    
}

var funcResult = func();  //type is correctly seen as Promise<int[]>

```

**Comment by IanYates** [comment]
In case it helps, here's a shareable link to the async version.

Inspect the type of funcResult.  You'll incorrectly get Promise<any[]>
Then delete the word "async".
Inspect the type of funcResult.   You'll correctly get int[]



http://www.typescriptlang.org/play/index.html#src=const%20asyncFunc%20%3D%20async%20()%20%3D%3E%20%7B%0D%0A%0D%0A%20%20%20%20%2F%2Fdoesn't%20matter%20-%20just%20something%20non-deterministic%0D%0A%20%20%20%20var%20r%20%3D%20Math.random()%3B%0D%0A%0D%0A%20%20%20%20%2F%2Fone%20possibility%20-%20we%20return%20an%20array%20of%20ints%0D%0A%20%20%20%20if%20(r%20%3D%3D%3D%200)%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20%5B1%2C%202%2C%203%5D%3B%0D%0A%20%20%20%20%7D%20%20%20%20%0D%0A%0D%0A%20%20%20%20%2F%2Fother%20possibility%20-%20we%20return%20a%20single%20int%20wrapped%20in%20an%20array%0D%0A%20%20%20%20if%20(r%20%3D%3D%3D%201)%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20%5B4%5D%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20%2F%2Fan%20empty%20array%20(ought%20to%20be%20typed%20as%20int)%0D%0A%20%20%20%20return%20%5B%5D%3B%0D%0A%20%20%20%20%2F%2FNOTE%3A%20changing%20to%20%20%20%20return%20new%20Array%3Cint%3E()%3B%20%20%20%20fixes%20this%0D%0A%20%20%20%20%0D%0A%7D%0D%0A%0D%0Avar%20funcResult%20%3D%20asyncFunc()%3B%20%20%2F%2Ftype%20is%20Promise%3Cany%5B%5D%3E.%20%20Should%20be%20Promise%3Cint%5B%5D%3E

**Comment by HerringtonDarkholme** [comment]
It seems a valid bug! Though annotating `<number[]>[]` will resolve this case, I do think compiler should do a consistent subtype reduction in both synchronous and asynchronous function.

@rbuckton should know better.

**Comment by mhegazy** [comment]
This is working correctly in latest.
