### ISSUE TITLE
no way to configure `tsc --project tsconfig.json` to preserve folders without .ts files in the output

### ISSUE THREAD

**Issue by dgoldstein0** [Microsoft/TypeScript#13291]
**TypeScript Version:**  2.1.4
**Code**

./tsconfig.json:
```
{
  "compilerOptions": {
    "module": "amd",
    "moduleResolution": "classic",
    "target": "es5",
    "baseUrl": ".",
    "paths": {"*": ["*"]},
    "outDir": "../compiled"
  },
  "compileOnSave": false
}
```

./modules/asdf.ts:
```
export let animal = "gorilla";
export let food = "banana";
```

**Expected behavior:**
`tsc --project tsconfig.json` results in `../compiled` being generated, containing `modules/asdf.js`.  OR, at the least, there is some way to change tsconfig.json to result in this.

**Actual behavior:**
unless there is another typescript file in the current directory, the `modules` directory is omitted from the outDir - `../compiled` contains just `asdf.js`.

Why would I want this, you might ask?  I'm experimenting with using different tsconfig.json files to build some subsets of my code, without using `--noResolve` because I do want the compiler to discover dependencies.  This current behavior, of shortening the output tree by any folders without typescript files that are being used by the current compilation, means that adding an extra dependency to a file could change the resolved set of files and result in the folder structure of the output directory changing (in a non-additive way), which is not desirable.

**Comment by mhegazy** [comment]
More details can be found at https://github.com/Microsoft/TypeScript/wiki/FAQ#why-does---outdir-moves-output-after-adding-a-new-file

**Comment by dgoldstein0** [comment]
oh hey, that does exactly what I want!

I guess I wasn't reading quite the right sources - https://www.typescriptlang.org/docs/handbook/tsconfig-json.html doesn't mention it.  Guess I should have found it within https://www.typescriptlang.org/docs/handbook/compiler-options.html
