### ISSUE TITLE
getElementsByTagName should return HTMLCollection

### ISSUE THREAD

**Issue by DaSchTour** [microsoft/TypeScript#13297]
**TypeScript Version:**  2.1.4

**Code**

```ts
const nodeList = document.getElementsByTagName("p");
nodeList instanceof NodeList; // returns false, although lib.d.ts says it returns NodeList
```

Example: http://codepen.io/DaSch/pen/OWPvZZ

**Expected behavior:**
document.getElementsByTagName("*") is defined to return HTMLCollection 

**Actual behavior:**
document.getElementsByTagName("*") is defined to return NodeList 

**Spec:**
https://dom.spec.whatwg.org/#dom-element-getelementsbytagname
https://developer.mozilla.org/en-US/docs/Web/API/Element/getElementsByTagName

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by FranklinWhale** [comment]
Seem that the test case added via #11023 has to be modified too

**Comment by DaSchTour** [comment]
Oh boy, this lib.d.ts thing is way to complicated 😞 
I'm trying to add this but I really have no idea where to start.
Looking through sources I would have to change TS.fsx as it is the only file that contains something about `getElementsByTagName` that's not a test.
I thought I could simply change lib.d.ts but that would be to easy.

**Comment by JacksonKearl** [comment]
@mhegazy could this be fixed internally? It's been over 8 months with no community input and I personally just spent more time than I'd like on an issue where I thought I could `forEach` over the return value, but of course I cant, as this isn't actually a `NodeList`. I'm sure others have had similar issues.

**Comment by JacksonKearl** [comment]
`getElementsByClassName` also should be an `HTMLCollection`

**Comment by JacksonKearl** [comment]
Also `HTMLCollection` is typed as having a `forEach` method but it does not. https://developer.mozilla.org/en-US/docs/Web/API/HTMLCollection

**Comment by HolgerJeromin** [comment]
IMO the original request and both issues from @JacksonKearl are solved (at least in TS3.1).

**Comment by Andarist** [comment]
as mentioned by @HolgerJeromin, `getElementsByTagName` returns `HTMLCollectionOf<T>` today. It seems that the issue could be closed, cc @RyanCavanaugh

**Comment by jakebailey** [comment]
Just looking at old issues; yeah, this one is fixed.
