### ISSUE TITLE
TS gives up inference on self-referential argument default

### ISSUE THREAD

**Issue by Jessidhia** [microsoft/TypeScript#13307]
**TypeScript Version:**  2.2.0-dev.20170102 (--strictNullChecks)

**Code**

```js
export {}

const obj = {
  foo: 'bar',
  frob (thing = obj.foo) {}
}
obj // type is `any`
```

**Expected behavior:**

Type of `obj` to be `{foo: string, frob (thing?: string): void}`.

Breaking the reference by, say, using `frob (thing = 'foo') {}` produces the correct type (but the wrong implementation).

**Comment by aluanhaddad** [comment]
The same thing happens in a .ts file. Except it provides a compile error. 
Salsa omits these errors by deign. Personally, I think a desire for stricter errors resulting from type annotations should coincide with moving those type annotations from comments into first class constructs, which means moving to a `.ts` file.

**Comment by Kovensky** [comment]
I see, so it's a TypeScript problem. I also see that it's only a build error with `--noImplicitAny`.

This does not look like an inherent typing limitation, probably just the parser being too eager in giving up as defaults are lazily evaluated. You can write `if (thing === undefined) thing = obj.foo` after all, and it would be parsed correctly.

**Comment by RyanCavanaugh** [comment]
We currently don't have a way to just ignore a circularity and proceed - type resolution needs to finish so it can write into a cache, for example. This doesn't seem to be a huge deal in practice.
