### ISSUE TITLE
TSServer 'references' only Works if Target Location is in property name  

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#13309]
Needed for https://github.com/Microsoft/vscode/pull/18205

**TypeScript Version:**  2.2.0-dev.20170104

```ts
class Foo {
    public abc;
}

var foo = new Foo()
foo.abc = 10
```

I'm trying to execute a `references` request against the TSServer for the property `abc`. Currently, this only works if the target location is somewhere within the string `abc`. I believe the references command should work if the target location is anywhere inside of `public abc` instead. 

This blocks adopting a references code lens provider in VSCode. The problem is that when determining which symbols in the document  we want to have show reference counts for, the `navtree` request for the document returns `abc` with the entire `public abc` span. This span does not work with the `references` request that we later fire off.

**Comment by mjbvz** [comment]
@waderyan FYI

We could try working around this on the VSCode side but the TypeScript server seems much better suited to handling this since it should already have all to information about the document. These same cases also all impact the current `Find all references` command in VSCode.

**Comment by mjbvz** [comment]
Sorry for the spam but two more cases:

```ts
class Foo {
    static bla() {

    }
}
```

* `references` for `foo` cannot currently be inside `class`
* `references` for `bla` cannot currently be inside `static`

**Comment by mhegazy** [comment]
@mjbvz is this still an issue?

**Comment by mjbvz** [comment]
Yes, I just tested this on 2.5.1 and on 2.6 and still see this issue

**Comment by mjbvz** [comment]
Yes I added some workarounds for this, for example: https://github.com/Microsoft/vscode/blob/3a14fde91d1fd0b3060b9eefb0780dd8d8b80e18/extensions/typescript-language-features/src/features/baseCodeLensProvider.ts#L129

**Comment by mjbvz** [comment]
Marking this as a priority for VS Code as it makes our keyboard navigation more clunky.

When using VS Code's symbol navigation or the outline panel to move through code, we place the cursor at the first position of the definition itself (so: `|public abc;`). This means that `find all references` will not work unless you move the cursor over to the symbol name itself

**Comment by RyanCavanaugh** [comment]
@rbuckton there's an old PR from Andy that's probably worth reviving for this

**Comment by DanielRosenwasser** [comment]
Same word of caution as https://github.com/microsoft/TypeScript/issues/28268#issuecomment-577941659.

Could we also get some clarity about the scope here? Should references work on the `function`, `let`, `var`, `class`, `interface`, `type`, `enum`, `namespace`, and `const` keywords?

What should happen if a `const` has multiple declarations? Fail, or just take the first one?

**Comment by mjbvz** [comment]
@DanielRosenwasser Yes, I think that all makes sense. I'd add `export`, `abstract`, and `readonly` to this list of keywords too.

By the way, VS Code's symbol navigation has actually gotten smarter since I originally reported this: we now place the cursor on the symbol name itself (`public |abc;`).

**Comment by DanielRosenwasser** [comment]
(and `declare` and `import` and `import type` with a default import)

**Comment by rbuckton** [comment]
I should have a PR for most of the keywords that make sense shortly, though "Find all references" on other tokens like `*` may take longer (or may just be out of scope for now) as we only currently do find-references and go-to-def on "property names" and keywords.
