### ISSUE TITLE
Multiple recommendations / Issues related to TS development under Visual Studio

### ISSUE THREAD

**Issue by atomsoftwarestudios** [Microsoft/TypeScript#13305]
Hello, I have multiple recommendations to typescript (and ts for visual studio). I am using it in the similar way as the C# so I split classes to separate files and compiling each project to the single library file (or "executable"), referencing projects in the solution as libraries and so on. I have found few things I don't like so much, but in the worst case I can live with them :) On the other hand it would be great if these can be fixed. All are related to web development, not to dev for Node, but its not probably important.

Visual Studio

a) Multiple VS projects in single solution
   If there are multiple projects in the solution and one project is used as a library (js+.d.ts) in the second it is not possible to navigate directly to source code of the library (by pressing F12) but navigation to the .d.ts file is performed instead. It would be great if there can be some internal mapping mechanism and the right the source file / type is openned directly.

b) Debugging
   If the "dynamic script" (in meaning it was evaled or loaded dynamically by injecting a script tag) is about to be debugged and the source is not located directly in the main project (the js library with a map file is loaded) it is not possible to see the content of variables using a mouse over method. Breakpoints works well, watches too, but it would be great if mouse over can work too in such case. It is strange that when I switch from the dynamic code to the source I can hover, but I can't debug, because stepping forward switches me back to the dynamic of course.

TypeScript

a) Namespaces
   If there is a same namespace splited over multiple files and the transpilation target is single file it is necessary to use export keyword in order to make definitions in a one file available through other files but with the same namespace. This is strange behavior, but I get it is related to modules loaded separately.

b) Namespaces transpillation
   If the namespace with the same name is used and splitted over multiple files and the single transpillation target is used it would be great to join all the same namespaces together to the single literal. Currently, there are as many namespaces as files defining them.

If you will find any of my recommendations "fixable" I can create separate issues for them.

Regards,
Frantisek Novak

**Comment by atomsoftwarestudios** [comment]
Regarding Visual Studio b)
I have recreated the solution and not everything works as expected. But at this time I was not able to identify where the problem was. I'll keep you updated if I'll identify it.

**Comment by aluanhaddad** [comment]
👍 for item a) it's badly needed but it has nothing to do with Visual Studio. It has to do with the concept of package level references that mean more than simply files on disk.

**Comment by atomsoftwarestudios** [comment]
I can imagine this will be hard as if the source will not be available in the solution this can bring problems. I can live with it, its not that big deal, find feature works well too ;)
