### ISSUE TITLE
Salsa does not support @type annotation in object member

### ISSUE THREAD

**Issue by Kovensky** [Microsoft/TypeScript#13306]
**TypeScript Version:**  2.2.0-dev.20170102 (--strictNullChecks)

**Code**

```js
const obj = {
  /** @type {string|undefined} */
  foo: undefined
}
obj.foo = 'string'
obj.foo // type is `undefined`
```

**Expected behavior:**

Type of `obj.foo` to be `string | undefined`

Current workaround is something like:

```js
const obj = {
  foo: (/** @returns {string|undefined} */() => undefined)()
}
obj.foo // type is `string | undefined`
```

A `@type` annotation could also be placed in the `obj` itself, but that gets unwieldy when the object itself is large.

Putting all these things in an object like this is arguably an anti-pattern (should be a module or class instead), but it's a start when adapting decade-old legacy code :)

Possibly related to https://github.com/Microsoft/TypeScript/issues/5158 as supporting its "assertion-y" use would make for a simpler workaround that doesn't require an IIFE.

**Comment by mohsen1** [comment]
Is this issue related? https://github.com/Microsoft/vscode/issues/18184

**Comment by Kovensky** [comment]
Nope, that seems to be about VS Code 1.8's automatic `@types` acquisition. The annotation there is also on the variable itself, instead of a member of the object.
