### ISSUE TITLE
Typescript compiler bug or expected behavior

### ISSUE THREAD

**Issue by ChadRockwell** [Microsoft/TypeScript#13301]
**TypeScript Version:**  2.1.4

Using modules (i.e. "external" modules - NOT namespaces/internal-modules). Using Angular 1.5.9 and Angular UI Router 0.3.2.  I have Included @types/angular and @types/angular-ui-router under node_modules.  VSCode/Typescript/tsc resolves the @types *.d.ts files correctly.  

If I try to access the "angular" namespace (example: let x = angular.module("blah")) I get a compilation error of..."'angular' refers to a UMD global, but the current file is a module. Consider adding an import instead." If I add an import of angular it works correctly.  So far so good and what I would expect.

```ts
/* if I comment out the import below I get the error - ."'angular' refers to a UMD global, 
but the current file // is a module. Consider adding an import instead."*/
import * as angular from "angular";

let appName: string = "myApp";

var app: angular.IModule = angular.module(appName, [
    "ui.router"
]);
```

However, if I refer to an interface the on the global "angular" namespace or "angular.ui" namespace (this is the ui-router namespace) there is no compilation error.  Is this expected behavior? Are interfaces treated differently?  Is there a way to FORCE the compiler to require an import?

```ts
/* no import of any kind in this file and compiler doesn't complain 
about any of the parameters passed into the constructor nor does it complain
about using the "state" method on the $stateprovider interface.
*/
export default class Routing {
    constructor(
        private $locationProvider: angular.ILocationProvider,
        private $stateProvider: angular.ui.IStateProvider,
        private $urlRouterProvider: angular.ui.IUrlRouterProvider) {

        this.$urlRouterProvider.when("", "patients").when("/", "patients");

        this.$stateProvider
            .state("patients", {
                "controller": "PatientListController",
                "controllerAs": "ctrl",
                "templateUrl": "app/features/patients/patient-list.html",
                "url": "/patients"
            } as ng.ui.IState);
    }
}

```

tsconfig.json
```ts
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "ES5",
        "moduleResolution": "node",
        "experimentalDecorators": true,
        "alwaysStrict": true
    }
}
```

**Expected behavior:** Compilation error similar to..."'angular' refers to a UMD global, but the current file is a module. Consider adding an import instead."

**Actual behavior:** No error

**Comment by mhegazy** [comment]
types will be erased. so in a sense it does not matter how you use them. but for values, at run time you will be using the global instead of the imported module name. the main motivation of this check is to make sure you do not accidentally use a global name that you did not intend to access in your module.

That said, https://github.com/Microsoft/TypeScript/issues/10178 tracks relaxing this check.

**Comment by ChadRockwell** [comment]
Thanks for the quick response.  I certainly understand the complexity of mixing global namespaces and modules and now appreciate the #10178 conversation even more.  Ideally (IMHO) I would prefer the option to require imports (even though at runtime I'd being using the global instead).  It provides/forces devs to show intent in the code (i.e. what are you using in this module).  If it's not required/enforced, devs tend to be lazy/careless.

**Comment by aluanhaddad** [comment]
@ChadRockwell I agree.

Part of the trouble here is that the declarations for angular-ui-router are not UMD style declarations.
The declaration file looks like this
```ts
import * as angular from 'angular';

export default "ui.router";

declare module 'angular' {
    export namespace ui {
        ...
   }
}
```
This brings up some additional points of friction. 

I experimented trying to make it UMD but ran into some problems.

No way to `export as namespace ns` if `ns` is a qualified name. I expected as much but it is problematic in this case.

Cannot create a UMD declaration if the module contains an `export default` clause. 
This is a problem for people who want to write JavaScript libraries with compatability hacks like
```js
const global = {...};

exports.__esModule = true;
exports["default"] = global;
module.exports = exports.default;
```
@mhegazy Is there a way to type this correctly?
