### ISSUE TITLE
`--removeComments` in JS only

### ISSUE THREAD

**Issue by unional** [Microsoft/TypeScript#13318]
tsc: 2.2.0+

I try to preserve comments in typings files but remove comments in the transpiled JS file. Couldn't find a combination to do it.

One way is introducing a flag for it, but it would be overkill.
Another way is to emit typings files when `--declaration=true` and `--noEmit=true`, the draw back is I have to run `tsc` twice with different config to generate the comment removed JS files and comment retained typings files.

**Comment by mhegazy** [comment]
We have discussed this issue before; every new option combination has its cost in terms of complexity and maintenance costs, so we have limited budget for adding new switches/switch combinations.
`--removeComments` has a clear functionality, it removes comments from both .js and .d.ts. if you do not care about comments, seems reasonable to remove them from both, if you do, it is not clear why you would not keep them in .js files. any JS minifier would remove comments for you, and presumably you are already using a minifier.
