### ISSUE TITLE
Performance Query - Large String Union Types

### ISSUE THREAD

**Issue by azz** [Microsoft/TypeScript#13311]
## Background 

We have a 2000 line localization file, and a localize function in our code which pulls out the translation at run-time.

I am investigating the possibility of auto-generating a large string union type, writing it out to a file, and using it as a type parameter for the localize function.

## Code

**TypeScript Version:**  2.1.4

**Before**

```ts
function localize(id: string) {
   // ...
}

localize('not a real key'); // OK
```

**After**

```ts
function localize(id: LocalizationKey) {
   // ...
}

localize('not a real key'); // NOT OK

// auto-generated
type LocalizationKey =
    "foo"
  | "bar"
  | ... // 2000+ items.
```

This works fine.

## Question

We are concerned about type-checking performance, both at compile time, and in TypeScript language services in our IDEs (VS Code and Visual Studio).

Is this a valid concern, or will these types be cached in an efficient manner?

Thanks.

**Comment by azz** [comment]
Closing this as it doesn't seem to be an issue.

**Comment by RyanCavanaugh** [comment]
FYI - Large unions of literal types are highly optimized because that's the internal representation of an enum value. We have an enum in the compiler with ~350 members and it doesn't cause any problems (that I'm aware of). 2,000 might be pushing it but I suspect you'll be OK.
