### ISSUE TITLE
Typescript Text Editor breaks because of incorrectly resolving paths on Network Shares

### ISSUE THREAD

**Issue by flts** [Microsoft/TypeScript#13319]
**TypeScript Version:**  2.1.4 & 2.2.0-beta-20170104-1
**Visual Studio Version:**  2015.3

**Scenario:**
Developing web applications on a Windows 10 virtual machine running in Parallels using Shared Folders to not have duplicated files in multiple development environments.
Parallels Shared Folders are basically network shares mapped to a drive id. 
So for example drive Y: is mapped to \\mac\home\.

**Expected behavior:**
Expected behavior would be to be able to use Visual Studio 2015.3 with TypeScript on network shares and have Intellisense and compile on save work like regular folders (d:\folder\).
TypeScript 1.8.4 didn't have this problem.

**Actual behavior:**
Currently in 2.1.4 and 2.2.0-beta-20170104-1 compile on save and Intellisense aren't working. 
Even when using a local symlink from C:\Projects\ to \\mac\home\projects\.

Project files are no problem to resolve but the NODE_MODULES d.ts files cannot be resolved correctly and a error messages are written in the Intellisense Output window. One line as example:
`
[Failure] Could not find a part of the path 'C:\WINDOWS\System32\UNC\psf\Home\Project\NODE_MODULES\rxjs\OBSERVABLE.D.TS'.
`

In the Error List window:
Severity	Code	Description	Project	File	Line	Suppression State
Error	TS2306	File 'C:/WINDOWS/system32/UNC/Mac/Home/Project/node_modules/rxjs/Observable.d.ts' is not a module.	TypeScript Virtual Projects	\\Mac\Home\Project\App\controls\loading-indicator\LoadingService.ts	2	Active

**Rootcause:**
I believe Microsoft.CodeAnalysis.TypeScript.EditorFeatures.dll fails to give the correct paths to the Typescript Language Service. 

I have followed the instruction for the nightly builds and used the VsDevMode.ps1 file to be able to debug the typescriptService.js file.

What I have found out is that at line 81538 the following call is made to the shimHost:
``` Javascript
var resolutionsInFile = JSON.parse(_this.shimHost.getModuleResolutionsForFile(containingFile));
```

And excerpt of the variable resolutionsInFile:
``` JSON
{
	"rxjs/add/observable/of": "C:\\WINDOWS\\System32\\UNC\\psf\\Home\\Project\\NODE_MODULES\\rxjs\\add\\OBSERVABLE\\OF.D.TS",
	"rxjs/add/observable/throw": "C:\\WINDOWS\\System32\\UNC\\psf\\Home\\Project\\NODE_MODULES\\rxjs\\add\\OBSERVABLE\\THROW.D.TS",
	"rxjs/add/observable/forkJoin": "C:\\WINDOWS\\System32\\UNC\\psf\\Home\\Project\\NODE_MODULES\\rxjs\\add\\OBSERVABLE\\FORKJOIN.D.TS",
	"rxjs/add/observable/zip": "C:\\WINDOWS\\System32\\UNC\\psf\\Home\\Project\\NODE_MODULES\\rxjs\\add\\OBSERVABLE\\ZIP.D.TS",
	"rxjs/add/observable/fromEvent": "C:\\WINDOWS\\System32\\UNC\\psf\\Home\\Project\\NODE_MODULES\\rxjs\\add\\OBSERVABLE\\FROMEVENT.D.TS",
	"rxjs/add/observable/fromPromise": "C:\\WINDOWS\\System32\\UNC\\psf\\Home\\Project\\NODE_MODULES\\rxjs\\add\\OBSERVABLE\\FROMPROMISE.D.TS",
	"rxjs/add/operator/catch": "C:\\WINDOWS\\System32\\UNC\\psf\\Home\\Project\\NODE_MODULES\\rxjs\\add\\operator\\CATCH.D.TS",
	"rxjs/add/operator/debounceTime": "C:\\WINDOWS\\System32\\UNC\\psf\\Home\\Project\\NODE_MODULES\\rxjs\\add\\operator\\DEBOUNCETIME.D.TS",
	"rxjs/add/operator/distinctUntilChanged": "C:\\WINDOWS\\System32\\UNC\\psf\\Home\\Project\\NODE_MODULES\\rxjs\\add\\operator\\DISTINCTUNTILCHANGED.D.TS",
	"rxjs/add/operator/do": "C:\\WINDOWS\\System32\\UNC\\psf\\Home\\Project\\NODE_MODULES\\rxjs\\add\\operator\\DO.D.TS",
	"rxjs/add/operator/filter": "C:\\WINDOWS\\System32\\UNC\\psf\\Home\\Project\\NODE_MODULES\\rxjs\\add\\operator\\FILTER.D.TS",
	"rxjs/add/operator/map": "C:\\WINDOWS\\System32\\UNC\\psf\\Home\\Project\\NODE_MODULES\\rxjs\\add\\operator\\MAP.D.TS",
	"rxjs/add/operator/switchMap": "C:\\WINDOWS\\System32\\UNC\\psf\\Home\\Project\\NODE_MODULES\\rxjs\\add\\operator\\SWITCHMAP.D.TS",
	"rxjs/add/operator/toPromise": "C:\\WINDOWS\\System32\\UNC\\psf\\Home\\Project\\NODE_MODULES\\rxjs\\add\\operator\\TOPROMISE.D.TS",
	"rxjs/add/operator/zip": "C:\\WINDOWS\\System32\\UNC\\psf\\Home\\Project\\NODE_MODULES\\rxjs\\add\\operator\\ZIP.D.TS"
}
```

**Sample**
[sample_project.zip](https://github.com/Microsoft/TypeScript/files/689665/sample_project.zip)

**Comment by vladima** [comment]
fixed in internal repo
