### ISSUE TITLE
proposal: enum extends string

### ISSUE THREAD

**Issue by Artazor** [Microsoft/TypeScript#13313]
The proposal is to treat
```ts
// hypothetical syntax (feel free to suggest other forms)
enum MyEnum extends string { A, B, C = "ccc" }
```
as
```ts
// already working pattern
namespace MyEnum {
     export type A = "A";
     export const A = "A" as A;
     export type B = "B";
     export const B = "B" as B;
     export type C = "ccc";
     export const C = "ccc" as C;
}
type MyEnum = MyEnum.A | MyEnum.B | MyEnum.C;
```

We found it as an extremely useful pattern when dealing with lot of literal unions.
it allows the following use cases:

```ts
var x: MyEnum = MyEnum.A; // Good type checking and intellisense
type StricterEnum = MyEnum.A | MyEnum.B; // recomposable type info at compile time
```

I understand that it is not exactly an "enum" but the shorthand syntax would be highly appreciated -)

**Comment by Artazor** [comment]
Plus it allows meaningful names for literal strings, encourages to avoid magical values in a codebase, and definitely is refactoring-friendly.

**Comment by DerFlatulator** [comment]
Not sure if you've seen #1206? [This proposal](https://github.com/Microsoft/TypeScript/issues/1206#issuecomment-240581743) is what you are asking for.

**Comment by krryan** [comment]
For reference, while you're waiting for this, you can eliminate the need for duplicated string literals (which must both be updated separately if you ever want to change the string value) with this pattern:
```ts
// already working pattern
namespace MyEnum {
     export const A = "A";
     export type A = typeof A;
     export const B = "B";
     export type B = typeof B;
     export const C = "ccc";
     export type C = typeof C;
}
type MyEnum = MyEnum.A | MyEnum.B | MyEnum.C;
```

**Comment by m1gu3l** [comment]
Shorter version:

```
namespace MyEnum {
    export const A= "A";
    export const B= "B";
}
type MyEnum = (typeof MyEnum)[keyof typeof MyEnum];
```
