### ISSUE TITLE
[tsserver] Provide command "GuessType" to improve apply completion

### ISSUE THREAD

**Issue by angelozerr** [microsoft/TypeScript#13317]
I would like to provide the same feature that I had developed with tern https://github.com/angelozerr/tern-guess-types. When user apply a completion for a function, it generates the function signature and provide for each function parameters a new popup list with available type:

![](https://github.com/angelozerr/tern-guess-types/wiki/images/TernGuessTypes.png)

Here a demo with Java Eclipse:

![guesstype](https://cloud.githubusercontent.com/assets/1932211/21712789/e8496c7c-d3f6-11e6-8aaf-82c2c6ebed03.gif)

**Comment by RyanCavanaugh** [comment]
I'm not sure what's going on here or what's being requested. A more complete description in a fresh issue would be appreciated if this is still something you'd like to see.
