### ISSUE TITLE
Unexpected inconsistencies in intersected `never` overloaded functions

### ISSUE THREAD

**Issue by kamranayub** [microsoft/TypeScript#13315]
**TypeScript Version:**  2.1.4

**Code**

```ts
namespace SocketIO {
	export interface Socket {
		on(event: string, fn: Function): void;
		emit(event: string, fn: Function): void;
	}
}

interface X extends SocketIO.Socket {
	on(event: never, fn: Function): void;	
}

interface Y extends SocketIO.Socket {
	emit(event: never, fn: Function): void;
}

type Z = X & Y;

var x: X;

x.on('bar', () => { }); // error
x.emit('baz', () => { });

var y: Y;

y.on('bar', () => { });
y.emit('baz', () => { }); // error

var z: Z;

z.on('bar', () => { }); // expected to throw compiler error
z.emit('baz', () => { }); // expected to throw compiler error
```

**Expected behavior:**

I was thoroughly confused when these two extended types that each overload the `on` and `emit` functions respectively with a `never` overload are allowed in type Z. I would expect `Z` intersection to maintain both compiler errors seen in `X` and `Y` both.

**Actual behavior:**

Neither calls to Z are marked as compiler errors.

## Cause

I believe the reason this is happening is due to the intersection causing a different overwriting of declarations.

I imagine X is merged like so:

```
on(event: never, fn: Function): void;
on(event: string, fn: Function): void;
```

Since `never` overload is merged above `string`, `never` is ordered first and it works.

Y is similar:

```
emit(event: never, fn: Function): void;
emit(event: string, fn: Function): void;
```

So, then when `X & Y` are intersected something happens to the order of declarations that I'm confused about or is incorrect. Conceptually, to me it seems like if `never` overloads `string` in both instances, intersecting them both should work because precedence has been set. But I could easily be missing something.

For example, this works because the base interfaces overloads the SocketIO overloads on both merged X and Y types:

```ts
namespace SocketIO {
	export interface Socket {
		on(event: string, fn: Function): void;
		emit(event: string, fn: Function): void;
	}
}

// Base interface that blocks original overloads
interface W extends SocketIO.Socket {
	on(event: never, fn: Function): void;	
	emit(event: never, fn: Function): void;
}

interface X extends W {
  // X-specific methods
}

interface Y extends W {
  // Y-specific methods
}

type Z = X & Y;

var x: X;

x.on('bar', () => { }); // error
x.emit('baz', () => { }); // error

var y: Y;

y.on('bar', () => { }); // error
y.emit('baz', () => { }); // error

var z: Z;

z.on('bar', () => { }); // error
z.emit('baz', () => { }); // error
```

My original use case is whitelisting the event overloads on a SocketIO interface, so that I can ensure the API is used correctly throughout the application--the `never` type was a clever way to accomplish this. However, I needed to split up the single interface into an `Emitter` and `Listener`, both which I had overload their respective methods with a `never` type--but I discovered once I intersected both those types, it didn't work as a single interface did.

Is this expected from the compiler's POV? Because it definitely wasn't from my POV as a user.

**Comment by aluanhaddad** [comment]
Perhaps I am misunderstanding what your are trying to accomplish, but I do not believe that overload order is responsible. I think the reason is that the intersection contains an overload that matches and so it picks that ones and is satisfied.

**Comment by RyanCavanaugh** [comment]
This is exactly as expected: If it's legal to do something to something of type `X`, then it's supposed to be legal to do that same thing to something of type `X & Y`. Both the `on` and `emit` calls were shown to be legal for `X` and `Y` respectively, so both calls succeeding on `Z` is the intended behavior.
