### ISSUE TITLE
make codefixes and refactorings aware of coding style

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#13314]
codefixes and refactorings emit the source code in TypeScript (just like developers), coding standards and styles are common across dev teams, currently the codefix emitter can't know about these styles and standards, so inevitably it emits some bad looking code

not sure what you can do about it

**Comment by amcasey** [comment]
I understand this was the most interesting special case of this problem: https://github.com/Microsoft/TypeScript/pull/17750

**Comment by amcasey** [comment]
And code fixes and refactorings do, to some extent, have configurable formatting: https://github.com/Microsoft/TypeScript/blob/a3d113bed3ac127084c8795da43161413c072510/src/services/types.ts#L522.  Obviously, there are many more knobs that could be added.

**Comment by RyanCavanaugh** [comment]
Refactorings are supposed to read the formatting settings from your editor and then format the emitted code accordingly. If you run into a case where this doesn't happen (basically, if running Format Document after a refactor causes new edits in the refactored code to appear) please log a specific bug with repro steps.
