### ISSUE TITLE
module path autocomplete is too agressive

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#13310]
my folder structure:
```
- framework.ts
- /subproject
    - /.vscode
        - tasks.json
        - settings.json
    - /source
        - main.ts
```

so when i am in `main.ts` and i need to import `framework.ts`, i am trying to type `../../framework`

```
import {} from '../.
                   ^ <-- caret is here
```

at this moment the IDE **finishes typing for me by** going:

```
import {} from '../.vscode'
                    ^^^^^^ <-- not what i wanted
```

can you make it stop "helping" me so that i can type `../../framework` instead of `../.vscode`?

**Comment by DanielRosenwasser** [comment]
Looks like a duplicate of #11457. The work is slated for TS 2.2.
