### ISSUE TITLE
nested errors make codefixes confuse their scopes

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#13312]
```
// file1.ts

export function fold<a, r>(values: a[], result: r, folding: (result: r, value: a) => r): r {
    for (let index = 0, length = values.length; index < length; index ++) {
         result = folding(result, values[index]);
    }
    return result;
}
export function append(values: a[], value: a): a[] {
    values.push(value);
    return values;
}
```
```
// file2.ts

import { fold } from './file1';
const value = fold([1, 2, 3], '', (result, value) => append(result, value));
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ <-- type error, the `append` is unknown rendering whole expression invalid
                                                     ^^^^^^ <-- append is unknown, but can be imported
                                                          ^ <-- caret is right here, let's import `append` using the import codefix
```

so in light of that type error and despite the fact that  `fold` was already imported, the codefix suggest to import `fold` again instead of suggesting to import `append`

so it looks like
```
// file2.ts
import { fold, fold } from 'file1';
```

instead of 
```
// file2.ts
import { fold, append } form 'file1';
```

**Comment by aozgaa** [comment]
Just copied the source and couldn't repro with the latest tsserver. That is, the correct import of `append` was added. If you see the issue again, comment here and I'll investigate further.

**Comment by mhegazy** [comment]
I think this issue is the same as https://github.com/Microsoft/TypeScript/issues/16205. it will happen whenever there are multiple errors in the span, with the code action having logic to pick up a token based on the span.

As noted in https://github.com/Microsoft/TypeScript/issues/16205#issuecomment-305669404, i think this should be fixed on vscode side by ensuring the correct span is used.
