### ISSUE TITLE
Invalid argument candidate for this type inference

### ISSUE THREAD

**Issue by edevine** [Microsoft/TypeScript#13323]
**TypeScript Version:**  2.1
The infered argument candidate 'string' is not considered valid when it should be.
**Code:**
```ts
class MyArray<T> extends Array<T> {
    flatten<R>(this: R[][]): R[] {
        return (new Array<R>()).concat(...this);
    }
}

var a = new MyArray<string>();
a.flatten<string>(); // Desired Error

var b = new MyArray<string[]>();
b.flatten<string>(); // string[]
b.flatten(); // Inference error
```

**Expected behavior:**
`b.flatten()` infers the type parameter as `string` and returns `string[]`

**Actual behavior:**
>The type argument for type parameter 'R' cannot be inferred from the usage. Consider specifying the type arguments explicitly.
>Type argument candidate 'string' is not a valid type argument because it is not a supertype of candidate 'string[]'.

**Comment by mhegazy** [comment]
Seems fixed in latest.
