### ISSUE TITLE
Bug with type inference

### ISSUE THREAD

**Issue by bjornbacklund** [Microsoft/TypeScript#13324]
**TypeScript Version:**  2.1.4.0
```
enum E {
	X,
	Y
}

class C
{
	public f(arg:E)
	{
		if (arg == E.X)   
		{
			return 0;
		}

		switch (arg)
		{
			case E.X:  // (1) does not compile, error "Type E.X is not comparable..."
				return 0;

			case E.Y:
				return 1;
		}
	}
}
```
**Expected behavior:**
Should compile. Warning should be issued for unreachable code at (1)

**Actual behavior:**
Compiler error

**Comment by RyanCavanaugh** [comment]
The error you get is basically the error you're asking for. It's just an implementation detail of how it's reported.

**Comment by bjornbacklund** [comment]
Not really right? It should compile with a warning, not with an error code. And the message doesn't make much sense. I had to look at the original code (which is much more complicated) for a loooooooong time to understand why the compiler was puking.

**Comment by RyanCavanaugh** [comment]
There is no distinction between error and warning.

The error message is correct. The value no longer has the possible value `E.A`. It's maybe not the best possible message, but it's the same message you'd see if you had used an `if` instead of a `switch`
