### ISSUE TITLE
Improved syntax to instantiate anonymous classes

### ISSUE THREAD

**Issue by ivaynberg** [Microsoft/TypeScript#13326]
**Code**

With the introduction of class expressions it is now possible to instantiate an anonymous class inline. Given an abstract class:

```ts

export abstract class ArrayView<T> extends Container {
    private model:Model<T[]>;

    public constructor(id:string, model:Model<T[]>) {
        super(id);
        this.model=model;
    }

    protected abstract populateItem(item:ArrayItem<T>);
}

```

it can be instantiated inline like this:

```ts

this.add(new class extends ArrayView<Todo> {
            protected populateItem(item: ArrayItem<Todo>) {
                item.add(new Checkbox("check", new PropertyModel<boolean>(item.model, "done")))
                item.add(new Label("title", new PropertyModel<string>(item.model, "title")));
            }
        }("items", itemsModel));
```

The syntax is cumbersome because it pushes the constructor parameters below the class body. 

When scanning code I would expect to see the constructor parameters first because they help me identify the code I am looking for.

When writing code I think about constructor parameters first before deciding what the rest of the class should do so having to write them first would remove some cognitive dissonance.

It would also be great to add some sugar by removing the need for "class extends" keywords for anonymous class instantiations.

**Expected behavior:**

```ts

this.add(new ArrayView<Todo>("items", itemsModel) {
        protected populateItem(item: ArrayItem<Todo>) {
                item.add(new Checkbox("check", new PropertyModel<boolean>(item.model, "done")))
                item.add(new Label("title", new PropertyModel<string>(item.model, "title")));
            }
        });
``` 

I hope something like this is possible, it will greatly improve readability of code written in a style that uses anonymous classes.

**Comment by RyanCavanaugh** [comment]
This should be brought up with TC39 / es-discuss. There's nothing TypeScript-specific about this pattern.

**Comment by ivaynberg** [comment]
Yes, that makes sense. I did not think of ES6 as a transpilation target for some reason. I posted it here for reference: https://mail.mozilla.org/pipermail/es-discuss/2017-January/047508.html

**Comment by miyelo** [comment]
use partial :3
https://stackoverflow.com/questions/14142071/typescript-and-field-initializers

`class Person {
    public name: string = "default"
    public address: string = "default"
    public age: number = 0;

    public constructor(init?:Partial<Person>) {
        Object.assign(this, init);
    }
}

let persons = [
    new Person(),
    new Person({}),
    new Person({name:"John"}),
    new Person({address:"Earth"}),    
    new Person({age:20, address:"Earth", name:"John"}),
];`

Have a nice day

**Comment by ivaynberg** [comment]
partials like this are good for fields, but not for methods because they do not allow the provided method overrides to call super.
