### ISSUE TITLE
Auto import code fix, file name is lowercase

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#13339]
So if i have a File _"../TestTest.js"_ and i want to get the class _"Test"_ from it then it should be:
`import { Test } from "../TestTest";`
but I get:
`import { Test } from "../testtest";`

refs https://github.com/alm-tools/alm-tools.github.io/issues/3 :rose: 

OS: MacOSX

**Comment by aluanhaddad** [comment]
Possible duplicate of #13109?

**Comment by basarat** [comment]
Indeed 🌹❤
