### ISSUE TITLE
JavaScript Property Suggestions Do not Pick Up Type From JSDoc Comment

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#13333]
_From @mohsen1 on January 5, 2017 18:28_

- VSCode Version: 1.8.1
- OS Version: macOS

Steps to Reproduce:

1. Make a file with following contents 

```js
var webpack = require('webpack')

/** @type {webpack.Configuration} */
var config = {
    module: {
        loa // expected autocomplete 
    }
}

module.exports = config;
```
2. In line 6, based on webpak type definition I should autocomplete for `loaders`.

![screen shot 2017-01-05 at 10 26 04 am](https://cloud.githubusercontent.com/assets/543633/21692426/b3ebb338-d331-11e6-82f1-812701538bdf.png)

_Copied from original issue: Microsoft/vscode#18184_

**Comment by mjbvz** [comment]
Looks like a TS issue, unrelated to webpack and imports. Here's a simpler repo:

```ts
interface IFoo {
    bar: number
}

/** @type {IFoo} */
const foo = {
    
}
```

When getting typing inside of `foo`, we do not get a completion item for `bar`. If the code is changed to

```ts
interface IFoo {
    bar: number
}

const foo: IFoo = {
    
}
```

then `bar` is returned as a completion inside of `foo`.

**Comment by Sayan751** [comment]
Ran into similar problem, and just wanted to point out that I have imported types as follows. And this (workaround?) works pretty well in vscode v1.35.0-insider.

```javascript
const HtmlWebpackPlugin = require('html-webpack-plugin');
const baseUrl = "/";

/** @type {() => import("webpack").Configuration} */
module.exports = () => ({
    plugins: [
        new HtmlWebpackPlugin({
            template: "index.ejs",
            metadata: { baseUrl }
        })
    ]
})
```

**Comment by mohsen1** [comment]
Yes the `import("webpack").Configuration` works now.

**Comment by johnbillion** [comment]
This appears to work as expected now using a standard JSDoc comment for the type of the config object. With the following code I get intellisense for its properties:

```js
const webpack = require('webpack');

/** @type {webpack.Configuration} */
module.exports = {
  ...
};
```

**Screenshot:**

<img alt="" src="https://user-images.githubusercontent.com/208434/82766162-94ba6700-9e14-11ea-8c8b-faa729c85dff.png">

Using VS Code 1.45.1.
