### ISSUE TITLE
Add navigator.sendBeacon to lib.es6.d.ts ?

### ISSUE THREAD

**Issue by glen-84** [Microsoft/TypeScript#13349]
https://www.w3.org/TR/beacon/

http://caniuse.com/#search=sendBeacon

**Comment by FranklinWhale** [comment]
Beacon is still a working draft and not likely to be added until it becomes, at least, a Candidate Recommendation.

https://github.com/FranklinWhale/TSJS-lib-generator/blob/master/README.md#w3c

**Comment by glen-84** [comment]
Thanks for the info. I'll close this for now.
