### ISSUE TITLE
Array.reduce - initialValue agrument should be optional

### ISSUE THREAD

**Issue by llRandom** [Microsoft/TypeScript#13343]
**TypeScript Version:**  2.1.1

**Code**

```ts
function reducer(state: IState = defaultState, action: IAction): IState {
    // implementation
    return state
}
let actions: IAction[] = [
    // actions
]
let state = actions.reduce(reducer)
```

**Expected behavior:**
It should be possible to call `reduce` without `initialValue` agrument. Currently it's optional only if `currentValue` (`action`) and `previousValue` (`state`) have the same type

**Actual behavior:**
Compile-time error because of required last agrument (`initialValue`)

**Comment by aluanhaddad** [comment]
> It should be possible to call reduce without initialValue agrument. Currently it's optional only if currentValue (action) and previousValue (state) have the same type

Indeed but the type declaration is correct as per how `Array.prototype.reduce` is specified.
From https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce

>The first time the callback is called, accumulator and currentValue can be one of two values. If initialValue is provided in the call to reduce, then accumulator will be equal to initialValue and currentValue will be equal to the first value in the array. If no initialValue was provided, then accumulator will be equal to the first value in the array and currentValue will be equal to the second.

Any other declaration would be misleading. Personally, what I dislike about reduce is the order of arguments. I would prefer the initial value to come first, but again this is not how it works in the runtime.

**Comment by llRandom** [comment]
Maybe I misunderstood you but it says that `initialValue` is optional. And current TSD includes two overloads: the first ore reduces array `T[]` to value `T`, the second one reduces array `T[]` to value `U`. The first overload marks `initialValue` as optional which is correct. The second one doesn't mark it as an optional argument and that's what I wanted to fix.

**Comment by llRandom** [comment]
Sorry, now I realize why the second case requires an `initialValue`. Array has a different element type and it can't be used as `initialValue` if it's reduced to a different type. I was just confused with my case where a reducer has default value.
