### ISSUE TITLE
Incorrect return type for get{Leading,Trailing}CommentRanges

### ISSUE THREAD

**Issue by ajafff** [Microsoft/TypeScript#13353]
**TypeScript Version:**  2.1.4

`getLeadingCommentRanges` and `getTrailingCommentRanges` return `undefined` if there is no comment. The return type of both functions does not include `undefined` as possible return value.

**Code**

```ts
import { consoleTestResultHandler } from 'tslint/lib/test';
import * as ts from 'typescript';

const sourceCode = `
{}
`.trim();

const sourceFile = ts.createSourceFile('foo.ts', sourceCode, ts.ScriptTarget.ES5, true);

let openBrace = sourceFile.getFirstToken();
let trailingComments = ts.getTrailingCommentRanges(sourceFile.getFullText(), openBrace.getEnd());
console.log(`${trailingComments}`); // prints undefined
let closeBrace = sourceFile.getChildAt(0).getLastToken();
let leadingComments = ts.getLeadingCommentRanges(sourceFile.getFullText(), closeBrace.getFullStart());
console.log(`${leadingComments}`); // prints undefined
```

**Expected behavior:**
Add `undefined` to the possible return types. I don't want you to change the behaviour of the function, just the type annotation.

**Actual behavior:**
`undefined` is returned where only `CommentRange[]` is documented to be returned.

**Comment by DanielRosenwasser** [comment]
The codebase is not fully rewritten for `strictNullChecks`. Feel free to send a PR to help out here.

**Comment by Manish-Giri** [comment]
I'm new here, am interested in making a PR for this.

**Comment by Manish-Giri** [comment]
@DanielRosenwasser Sorry to ask, I just wanted to verify before submitting a PR here. I am to add the possible return type of `undefined` for functions `getLeadingCommentRanges` and `getTrailingCommentRanges`, in the function implementation and on all the declarations, right?

**Comment by mhegazy** [comment]
Just the implementation. the declaration file is generated at build time.
