### ISSUE TITLE
[tsserver] Format command ignores "options" argument

### ISSUE THREAD

**Issue by guncha** [microsoft/TypeScript#13354]
**TypeScript Version:** 2.2.0-dev.20170108

**Code**

Sending the following command to tsserver:

```json
{
  "line": 1,
  "offset": 1,
  "endLine": 81,
  "endOffset": 1,
  "options": {
    "indentSize": 2,
    "tabSize": 2
  },
  "file": "/source.ts"
}
```

**Expected behavior:**

Expect the file to be formatted using 2 spaces for indentation.

**Actual behavior:**

The project indentation settings are used instead (defaults to 4 spaces).

**Comment by RyanCavanaugh** [comment]
Going to assume this has been fixed by now or was user error. Please refile with a more complete repro otherwise. Thanks!
