### ISSUE TITLE
Intellisense fails with function in type options

### ISSUE THREAD

**Issue by Bobris** [microsoft/TypeScript#13357]
**TypeScript Version:**  2.1.4 (including 2.4.1 version)

Just insert this to current TypeScript Playground:

```
interface CSSStyle {
    zoom?: string;
}

function works(s: CSSStyle) {
}

works({ /* intellisence works as expected here */ });

function nogo(s: CSSStyle | (()=>CSSStyle)) {
}

nogo({ /* intellisence does not work here */ });

```
I don't understand why Typescript fail to advice `zoom` inside `nogo` call, why it is different from `works` case?

**Expected behavior:**

`zoom` will be advised on both places.

**Actual behavior:**

`zoom` is advised only on simpler type without function option.

**Comment by RyanCavanaugh** [comment]
Works now
