### ISSUE TITLE
Duplicate Module Entries in `from` Path Completions 

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#13373]
**TypeScript Version:**  2.2.0-dev.20170109

1. Have installed `lodash` typings into global typings cache at some point previously. I see the file here: `/Users/matb/Library/Caches/typescript/node_modules/@types/lodash/index.d.ts`
2. Create a new folder with a simple `package.json` and a `main.js`
3. Install `@types/lodash`: `npm install @types/lodash`
4. Enter `import {} from ''` in `main.js`
5. Try to get suggestions for the path in `from`

**Expected behavior:**
A single entry for lodash is returned.

**Actual behavior:**
I see three entries for `lodash` returned.

Here's the TSserver communications:

```
[Trace - 4:28:52 PM] Sending request: completions (65). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/Users/matb/projects/sand/test/main.js",
    "line": 1,
    "offset": 17
}
[Trace - 4:28:52 PM] Response received: completions (65). Request took 3 ms. Success: true 
Result: [
    {
        "name": "lodash",
        "kind": "external module name",
        "kindModifiers": "",
        "sortText": "lodash",
        "replacementSpan": {
            "start": {
                "line": 1,
                "offset": 17
            },
            "end": {
                "line": 1,
                "offset": 17
            }
        }
    },
    {
        "name": "lodash",
        "kind": "external module name",
        "kindModifiers": "",
        "sortText": "lodash",
        "replacementSpan": {
            "start": {
                "line": 1,
                "offset": 17
            },
            "end": {
                "line": 1,
                "offset": 17
            }
        }
    },
    {
        "name": "lodash",
        "kind": "external module name",
        "kindModifiers": "",
        "sortText": "lodash",
        "replacementSpan": {
            "start": {
                "line": 1,
                "offset": 17
            },
            "end": {
                "line": 1,
                "offset": 17
            }
        }
    },
    {
        "name": "react",
        "kind": "external module name",
        "kindModifiers": "",
        "sortText": "react",
        "replacementSpan": {
            "start": {
                "line": 1,
                "offset": 17
            },
            "end": {
                "line": 1,
                "offset": 17
            }
        }
    }
]
```

**Comment by Chris-Petty** [comment]
I have a similar problem developing a react native project. Really annoying as it blocks out the useful snippets I actually want to use.

All the extra logs are the same auto import from `core-js`

![image](https://user-images.githubusercontent.com/7684221/36176788-aeea026e-1178-11e8-8089-f58b27dbcb69.png)

**Comment by Chris-Petty** [comment]
If I disable [Javascript (ES6) code snippets](https://marketplace.visualstudio.com/items?itemName=xabikos.JavaScriptSnippets) and reload, reenable and reload, the problem goes away. Maybe an issue with that extension?

**Comment by andy-ms** [comment]
@Chris-Petty That may be coming from yet another extension -- `log, Log to the console` doesn't sound like it comes from TypeScript.

**Comment by Chris-Petty** [comment]
I have a suspicion I was on a red herring there with the extension, I think just the act of reloading was briefly fixing it because it was taking a while for `"typescript.autoImportSuggestions.enabled" in settings to populate that list.

Obviously `"typescript.autoImportSuggestions.enabled": false,` resolves it... at the cost of not being able to use that feature anymore.

Wondering if this in settings is maybe failing to ignore node_modules or something?
```
// Configure glob patterns for excluding folders
  "java.import.exclusions": [
    "**/node_modules",
    "**/.metadata",
    "**/archetype-resources"
  ],
```

**Comment by andy-ms** [comment]
`java.import.exclusions` shouldn't affect TypeScript?

**Comment by Chris-Petty** [comment]
Yea probably not ha.

Addressing that snippet for `log, Log to the console`, RN project is just JS(X), but following issue references while looking for this problem I ended up here.

Alright, I reenabled `autoImportSuggestions` in settings and disabled all extensions. The problem persists so I'm pretty sure it isn't extension related.

**Comment by Chris-Petty** [comment]
Deleting node_module solves the problem too, but kinda introduces a couple other problems 😃

**Comment by andy-ms** [comment]
Is there any chance you could share the project?

**Comment by Chris-Petty** [comment]
Yup: https://github.com/sussol/mobile

**Comment by andy-ms** [comment]
@mjbvz I'm having trouble reproducing this now. The duplicate entry will show up in the completion list, right? (Though to be sure I also looked at the log.) Verified that I have `lodash` in the typings cache.
@Chris-Petty installed that repo and also only see one definition for `log` if I request completions in `main.js`.

**Comment by Chris-Petty** [comment]
@andy-ms forgot about this, glad you found repro for the issue.

That said, I just tried it and cannot reproduce 🙄your PR already in the wild? I don't recall having this issue in recent history either.

**Comment by andy-ms** [comment]
@Chris-Petty Yep, it should already be in `typescript@next`.
