### ISSUE TITLE
Matching brace/parenthesis highlight fails when enclosed in parentheses

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/TypeScript#1337]
Hi,

VS 2013 Update 4 RC
TS: 1.3

This refers to the subtle highlighting of matching braces and parentheses, which occurs when the cursor is moved over them. This feature does not work when there is an outer set of parentheses.

![closingbracerepro](https://cloud.githubusercontent.com/assets/1106823/5270243/3b4e279c-7a61-11e4-9783-65f10dd8f6b5.gif)

**Comment by vladima** [comment]
I've tried to reproduce this issue in different machines - no luck. If you still experience this problem using the latest bits can you attach managed debugger to VS and check if any relevant exceptions were raised when you are moving the cursor to trigger brace highlighting?

**Comment by vladima** [comment]
I found a repro, this issue is fixed in our internal bits

**Comment by NoelAbrahams** [comment]
Great. Thanks.
