### ISSUE TITLE
Type inference from a parameter of a callback not working for generics

### ISSUE THREAD

**Issue by kenotron** [microsoft/TypeScript#13370]
**TypeScript Version:**  2.1.4

**Code**

```ts
export function lazify<T extends () => void>(ensureCallback: (t: T) => void): () => Promise<void>;
export function lazify<A, T extends (a: A) => void>(ensureCallback: (t: T) => void): (a: A) => Promise<void>;
export function lazify<A, A2, T extends (a: A, a2: A2) => void>(ensureCallback: (t: T) => void): (a: A, a2: A2) => Promise<void>;

export function lazify(ensureCallback: any) {
    return function() {
        let originalArgs = arguments;

        return <any>new Promise((resolve, reject) => {
            resolve(ensureCallback.apply(null, originalArgs));
        });
    };
}

// The action
function foo(name: string, num: number) {
    console.log(name, num);
}

// Lazy wrapper - note developers have to specify the types manually
let lazyFoo = lazify((action: typeof foo) => {
    // the require ensure stuff
});

// Using wrapper
lazyFoo("hi", 5).then(() => {
    // do additional stuff
});
```

**Expected behavior:**
lazyFoo on the bottom should be able to infer the type of T based on the parameter inside the callback given the generic def of lazyFoo. 

**Actual behavior:**
It cannot figure this out and is given an error in the last usage of the wrapper. This would be great addition in helping write lazy wrappers for delay loaded (code splitted) scripts via webpack & require.ensure, etc.

I'm attaching a screenshot of this problem.
![image](https://cloud.githubusercontent.com/assets/34725/21783460/3ecac07e-d66c-11e6-979d-f4591e638c18.png)

**Comment by kenotron** [comment]
@mhegazy We're beginning our work to delay load some scripts, and the API is getting awkward without better type inference on the part of Typescript compiler.

**Comment by aluanhaddad** [comment]
@kenotron in order for this to work, you need to order your overload signatures from greatest to least specificity. The compiler is picking the one with a single type parameter because it is specified first.
If you use the following order, the code works as expected.
```ts
export function lazify<A, A2, T extends (a: A, a2: A2) => void>(ensureCallback: (t: T) => void): (a: A, a2: A2) => Promise<void>;
export function lazify<A, T extends (a: A) => void>(ensureCallback: (t: T) => void): (a: A) => Promise<void>;
export function lazify<T extends () => void>(ensureCallback: (t: T) => void): () => Promise<void>;
```

**Comment by aluanhaddad** [comment]
@kenotron Actually I spoke to soon, while overload order was a factor, you have issues related to method overloads that only differ by callback arity.

**Comment by RyanCavanaugh** [comment]
This is solvable with rest arg typing now.
