### ISSUE TITLE
CodeFix import for lodash does not work

### ISSUE THREAD

**Issue by normalser** [Microsoft/TypeScript#13377]
Not sure if it's the issue with lodash typings or something else, but CodeFix import for lodash does not work:

![image](https://cloud.githubusercontent.com/assets/1723815/21790875/3fc9913a-d6ad-11e6-8845-90c5809efc3b.png)

but if I import manually then it's ok

![image](https://cloud.githubusercontent.com/assets/1723815/21790884/4c411eec-d6ad-11e6-8148-5b0dd019a351.png)

**Comment by wallverb** [comment]
Not sure if related: https://github.com/Microsoft/TypeScript/issues/13374

**Comment by aluanhaddad** [comment]
Man **lodash/index.d.ts** is daunting.

**Comment by aozgaa** [comment]
Repro's on master, commit cbdf02f47c1af41a985c970
