### ISSUE TITLE
using certain require() pattern results in extraneous project files in outDir

### ISSUE THREAD

**Issue by ORESoftware** [Microsoft/TypeScript#13380]
**TypeScript Version:**  

$ tsc -v
Version 2.1.4

**Code**

```js
// code in a .js file in my project (note: it is in a .js file not a .ts file)
// the following line of code is simply importing code from another project called "live-mutex"
const Client = require('live-mutex/client');

```

.tsconfig

```json
{
  "compilerOptions": {
    "module": "amd",
    "noImplicitAny": true,
    "removeComments": true,
    "preserveConstEnums": true,
    "outDir": "dist",
    "allowJs": true
  },
  "include": [
    "./**/*"
  ],
  "exclude": [
    "test",
    "node_modules"
  ]
}
```

**Expected behavior:**

Would expect that it would handle the require('live-mutex/client') path without putting that whole project in the the outDir directory ("dist" directory).

**Actual behavior:**

What happens is that if my project uses the require statement like so:

`const Client = require('live-mutex/client');`

then when it writes out the code to the dist directory it does this:

```
/dist
   /my-current-project
   /live-mutex
```

normally we would expect to see:

```
/dist
   /lib
   /whatever
```

so for some reason TS thinks I want the live-mutex directory in my dist folder, but I am not sure why.
Is there a good reason for that? Please let me know if it does not make sense.

**Comment by mthurlin** [comment]
You required that code, so naturally it needs to be part of the output?
What are you expecting to happen?

**Comment by ORESoftware** [comment]
@mthurlin sure, right now I am 90% certain this is a minor bug - well as you can see in my tsconfig.json file, I have ignored node_modules. live-mutex is a dependency in my project and resides in node_modules.

In my project code, I require live mutex like so:

`const Client = require('live-mutex/client');`

what then happens is that during the tsc build it will output live-mutex as a separate project in my outDir
this is totally unexpected

*however*, if I change the above code to:

`const Client = require('live-mutex').Client;`

then everything behaves as normal, and live-mutex is *not* pulled into the build as it's own entity

this is either a bug, or there is a good reason for this behavior, but hopefully you at least understand what I am describing. Is it clear?

**Comment by mhegazy** [comment]
first, `const = require(..)` is not a module import, it is a function call to a function called `require`. TypeScript does not treat this any differently from `const foo = bar("baz");`. use `import Client = require("..")`.

Second, i am not sure i understand any thing about the problem :) how is live-mutex defined, where is the source file, where is it emitted to? what did you expect instead? in general, sharing a self-contained reproduction to the issue is needed.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
