### ISSUE TITLE
Add module option called "omit"

### ISSUE THREAD

**Issue by bertyhell** [Microsoft/TypeScript#13387]
**TypeScript Version:**  2.1.4

# Add module option called "omit"

example tsconfig.json:
```ts
{
  "compilerOptions": {
    "module": "omit"
  }
}
```

This would not output any of the module import statements. Eg: 
```ts
// start imports
import * as $ from 'jquery';
import * as _ from 'lodash';
// end imports
```

Would output import statements to javascript as no code at all:
```js
// start imports
// end imports
```

instead of:
```ts
// start imports
var $ = require('jquery');
var _ = require('lodash');
// end imports
```

This will be useful for people that have an existing frontend project.
The'll be able to use the benefits of Typescript including external modules with type checking like Lodash and jQuery without having to setup a module loader on the client side (require.js), or package their Javascript in a build process (webpack or browserify).
Using this approach will require adding the packages manually to the html files. Eg:
```html
<html>
  <head>
    <script src="node_modules/lodash/index.js"></script>
    <script src="node_modules/jquery/index.js"></script>
  </head>
  <body>
    ...
  </body>
</html>
```

If you currently want to do this you have to include a hack like this to neutralize the require statements. Which causes a wanrning (TS2441: Duplicate identifier 'require'. Compiler reserves name 'require' in top level scope of a module.).
```ts
function require(moduleName: string) {
  switch (moduleName) {
    case 'jquery':
      return $;
    case 'lodash':
      return _;
  }
}
```

Some other people that have the same issue:
http://stackoverflow.com/questions/39854655/typescript-and-react-outputting-require

**Comment by gcnew** [comment]
Try not are using modules at all. If you don't have any imports/exports everithing is considered global scope and works the way you describe.

**Comment by bertyhell** [comment]
But then I don't get code completion for 3rd party library, right?

**Comment by RyanCavanaugh** [comment]
... have you tried?

**Comment by DanielRosenwasser** [comment]
@bertyhell to clarify, you should, even using the mechanism of installing from `@types`. If you don't get completions for the libraries you're using, try adding the name of the package to the `"types"` field in your `tsconfig.json`'s `"compilerOptions"` field.

For example:

```json
{
    "compilerOptions": {
        "types": ["jquery", "lodash"]
    }
}
```

This will force TypeScript to try to grab the declarations for `jquery` and `lodash`.

**Comment by gcnew** [comment]
Just for completeness sake: @DanielRosenwasser suggestion is the new and better approach (for TypeScript >= 2.0). In older versions `@types` were not a thing and you had 2 options:
 - either use [`reference` directives](https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html) (in any file, it will work from then on everywhere)
 - or put the declaration file among `files` in `tsconfig.json` or directly pass it to the compiler

**Comment by bertyhell** [comment]
Ok, i tried this out:

## Result when i use the fake require function and import statements
```ts
function require(moduleName: string) {
  switch (moduleName) {
    case 'jquery':
      return $;
    case 'lodash':
      return _;
  }
}

import * as $ from 'jquery';
import * as _ from 'lodash';
```

Result: Correct autocomplete in intellij and typechecking
![image](https://cloud.githubusercontent.com/assets/1710840/21842050/522df72e-d7e5-11e6-9c29-6af381d83248.png)



## Attempt 1: tsconfig types
```json
{
    "compilerOptions": {
        "types": ["jquery", "lodash"]
    }
}
```

Result: No autocomplete but i do get correct type checking
![image](https://cloud.githubusercontent.com/assets/1710840/21842012/292d06a8-d7e5-11e6-8c1c-efe24bc73a82.png)


##Attempt 2: Reference directives
```ts
/// <reference path="../../../node_modules/@types/lodash/index.d.ts" />
/// <reference path="../../../node_modules/@types/jquery/index.d.ts" />
```

Result: No autocomplete but i do get correct type checking
![image](https://cloud.githubusercontent.com/assets/1710840/21842176/e1e0dd82-d7e5-11e6-8ce6-dbea64eaad9f.png)


##Attempt 3: put the declaration file among files in tsconfig.json
```ts
{
  "include": [
    "node_modules/@types/**/*.d.ts",
    "js/**/*.ts"
  ]
}
```

Result: No autocomplete but i do get correct type checking
![image](https://cloud.githubusercontent.com/assets/1710840/21842241/28d0dd46-d7e6-11e6-94d4-ab160c8ee561.png)

**Comment by mhegazy** [comment]
Why are you using modules if you want to use `$` as global?

just use it as a global. you do not need any `/// <references....`

```sh
npm install @types/jquery
echo $("p").add("div").addClass("widget"); > a.ts
tsc 
```

**Comment by bertyhell** [comment]
> Why are you using modules if you want to use $ as global?

Because then i don't get any autocompletion in my IDE
Did you read my last reply?

**Comment by mhegazy** [comment]
This seems to be a problem with webstorm. i would recommend filing this issue on their issue tracker. Here is what i see with VSCode.

![animation](https://cloud.githubusercontent.com/assets/8000722/21904286/f599e7f6-d8b7-11e6-9feb-784361f071aa.gif)

**Comment by bertyhell** [comment]
ok, will do

**Comment by endel** [comment]
I was trying to define my own `require` function, which doesn't exist in the JavaScript runtime I'm working on (Adobe Animate / JSFL) and came across this issue. (due to error `Compiler reserves name 'require' in top level scope of a module.`)

I've managed to define my own `require` function this way (simplified version): 

```typescript
this['require'] = function(modulePath) {
    let exports = {};
    // ... evaluate the module
    return exports;
}
```
