### ISSUE TITLE
Interface 'HTMLSelectElement' incorrectly extends interface 'HTMLElement'

### ISSUE THREAD

**Issue by AsciiSmoke** [Microsoft/TypeScript#13395]
**TypeScript Version:**  2.1.4

**ISSUE**
When running tsc on solution I'm getting an error from definitions file **_in the npm typescript package_** (/lib/lib.d.ts).

The following code appears at line 10066:
```ts
add(element: HTMLElement, before?: HTMLElement | number): void;
```

This is causing the error:

> ../typescript/lib/lib.d.ts(10005,11): error TS2430: Interface 'HTMLSelectElement' incorrectly extends interface 'HTMLElement'.
  Types of property 'add' are incompatible.
    Type '(element: HTMLElement, before?: number | HTMLElement) => any' is not assignable to type '(els: string) => HTMLElement'.
      Types of parameters 'element' and 'els' are incompatible.
        Type 'string' is not assignable to type 'HTMLElement'.

As a test, if I comment out the line the error goes away.

**Comment by FranklinWhale** [comment]
It appears that you are assigning a string varible (`els`) to the `element` parameter of the `add` method, which is of type `HTMLElement`.

**Comment by AsciiSmoke** [comment]
To be clear, this is **not** in my code. This is the in lib.d.ts that comes down from npm.
