### ISSUE TITLE
Visual Studio Plugin missing lib.es2017.string.d.ts

### ISSUE THREAD

**Issue by collinempting** [Microsoft/TypeScript#13396]
**TypeScript Version:**  2.1.4

Program Files (x86)\Microsoft SDKs\Typescript\2.1\lib.es2017.d.ts is referencing lib.es2017.string.d.ts which does not exist in that directory.

It does exist in my node_modules\typescript installation so wondering if just overlooked for visual studio's plugin.  This causes a build error when building the project from visual studios.

**Comment by yuit** [comment]
Thanks @collinempting. The fix will have to be done in our VS repo. Does the bug block you ? In the meantime, would a workaround of copy/paste the file from node_modules\typescript solved your issue? (not

**Comment by collinempting** [comment]
Thanks @yuit 

I am currently implementing that workaround in a npm postinstall step to copy the correct file over.

**Comment by yuit** [comment]
The fix is in. We will have this fix in our next release!
