### ISSUE TITLE
CodeFix duplicate import issue if module exports type and element with the same name

### ISSUE THREAD

**Issue by normalser** [Microsoft/TypeScript#13394]
```ts
// File: foo.ts
export const Foo = 1
export type Foo = number
```

![pxn79b79qs](https://cloud.githubusercontent.com/assets/1723815/21816795/65090746-d72f-11e6-9ade-d02d67aae383.gif)

**Comment by aozgaa** [comment]
I cannot reproduce the issue as no codefix appears when I copy the above situation. If you can reproduce the issue, please give a description includinf the source of all files prior to getting/applying the codefix, in the style of https://github.com/Microsoft/TypeScript/issues/15533, and I'll investigate further.

**Comment by normalser** [comment]
Looks like not an issue anymore
