### ISSUE TITLE
files/dirs that start with a dot (.) do not get copied or transpiled by default

### ISSUE THREAD

**Issue by ORESoftware** [Microsoft/TypeScript#13399]
**TypeScript Version:**  2.1.4

**Code**

```
/lib
/test
    /.suman
    /test-src
```

if I build this project with `tsc` and use the outDir option, the .suman directory **won't** get moved/transpiled, presumably because it starts with a dot .

based on the above project structure, the resulting _incorrect_ build would look like:

```
/dist
   /lib
   /test
       /test-src  
```
above we can see that the .suman dir is missing from the test dir

if I rename the .suman directory to suman like so:

```
/lib
/test
    /suman    // renamed from .suman to suman
    /test-src
```

then it will get moved to the outDir, because it no longer starts with a dot .

so the expected result actually happens, which is of course:

```
/dist
   /lib
   /test
       /suman
       /test-src
```

here is my config, which shows that I want to `include` my test dir, in the build.

```json
{
  "compilerOptions": {
    "compileOnSave": true,
    "target": "es5",
    "noImplicitAny": false,
    "removeComments": true,
    "preserveConstEnums": true,
    "outDir": "dist",
    "allowJs": true,
    "allowUnreachableCode": true,
    "lib": ["es2015", "dom"]
  },
  "include": [
    "./**/*"
  ],
  "exclude": [
    "node_modules"
  ]
}

```

**Expected behavior:**

I would expect it would include files/directories that start with a dot, unless you exclude files/dirs that start with a dot

**Actual behavior:**

TS/tsc seems to exclude files/dirs that start with a dot by default, which seems very strange, since users could easily specify with a regex to ignore dirs/files that start with a dot!

**My question is then, is there a tsconfig.json setting I can use to include the .suman directory with my build?**

**Comment by mhegazy** [comment]
files and folders starting with a `.` are ignored by the glob patterns. this to accomodate for hidden folders that tools like git rely on. You need to add the folder starting with a `.` explcitlly in your include patter:

```json
  "include": [
    "./**/*",
    "./test/.suman/**/*"
  ],
```

also one note, you need to exclude your outDir, or you will be consuming the output again, given that you have `--allowJs` set. so your exclude patterns should be:
```json
  "exclude": [
    "node_modules",
    "./dist"
  ]
```

**Comment by ORESoftware** [comment]
ahh thanks so much that helps a ton!
