### ISSUE TITLE
add a dirty flag

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#13416]
it would be nice to know if the code wasn't changed since last successful build

**Comment by DanielRosenwasser** [comment]
Can you elaborate a little bit about what you have in mind?

**Comment by aleksey-bykov** [comment]
at any point in time i would like to know if the generated javascript in sync with the current typescript of a project, or put it differently: was the source code changed since the last build

i need it to avoid running a build on source code that  wasn't changed

**Comment by mhegazy** [comment]
check the time stamps of the output and compare it to the input.

**Comment by aleksey-bykov** [comment]
will do
