### ISSUE TITLE
Incomplete Metadata for subclass with default constructor

### ISSUE THREAD

**Issue by ajafff** [Microsoft/TypeScript#13410]
**TypeScript Version:**  2.1.4

`tsc` is run with `--experimentalDecorators` and `--emitDecoratorMetadata`

**Code**

```ts
function foo(_: any) {}

@foo
class Foo {
    constructor(public bar: number) {}
}
@foo
class Bar extends Foo {
}
```

**Expected behavior:**

```diff
 Bar = __decorate([
     foo,
-    __metadata("design:paramtypes", [])
+    __metadata("design:paramtypes", [Number])
 ], Bar);
```

Metadata for subclass with default constructor should include parameter types of super constructor.

**Actual behavior:**

`tsc` emit:

```javascript
/* ... helper functions ... */

function foo(_) { }
var Foo = (function () {
    function Foo(bar) {
        this.bar = bar;
    }
    return Foo;
}());
Foo = __decorate([
    foo,
    __metadata("design:paramtypes", [Number])
], Foo);
var Bar = (function (_super) {
    __extends(Bar, _super);
    function Bar() {
        return _super.apply(this, arguments) || this;
    }
    return Bar;
}(Foo));
Bar = __decorate([
    foo,
    __metadata("design:paramtypes", [])
], Bar);
```

**Comment by mhegazy** [comment]
This is behaving as intended. the derived class does not have a constructor, the compiler can not just delegate the constructor in the general case. Consider a case where the type of the argument in the base class is not accessible to the derived. the emit would be invalid.  Noting that the output generation needs to work as single file transformation (i.e. in isolation of the rest of the project) . e.g.:

```ts
// File1.ts
class Inner { }
export class Base {
    constructor (p: Inner) {}
}
```

```ts
//File2.ts
import {Base} from "./File1";
class Derived extends Base {} // Inner here is not visible
```

If you are using TS 2.2 (specifically the change to `__extends` in https://github.com/Microsoft/TypeScript/pull/12488) you should be able to get the parent meta data by walking up the prototype chain.

**Comment by ajafff** [comment]
That sounds pretty reasonable.
Feel free to close this issue.
