### ISSUE TITLE
Cannot augment an UMD module declaration from global scope

### ISSUE THREAD

**Issue by cervengoc** [Microsoft/TypeScript#13412]
**TypeScript Version:**  2.1.4

**Code**

```ts

// test.d.ts

declare namespace MyNamesapce {
  export interface MyInterface {
    DoSomething();
  }
  export var Var: MyInterface;
}
export = MyNamesapce;
export as namespace MyUMDGlobal;
```

```ts
// main.ts

declare module "test" {
  interface MyInterface {
    DoAnotherThing();
  }
}

var a = MyUMDGlobal.Var.DoSomething();
var b = MyUMDGlobal.Var.DoAnotherThing();
```

**Expected behavior:**

It should compile fine, because I've augmented the module `test` and it's interface `MyInterface` with the method `DoAnotherThing`.

**Actual behavior:**

It gives a compile error that it doesn't find the symbol `DoAnotherThing`. Visual Studio intellisense doesn't resolve it either.

**Comment by cervengoc** [comment]
@mhegazy Could you please have a look at this? This one currently breaks my work on updating some library typings to be TS2 friendly.

**Comment by mhegazy** [comment]
you need a top-level import or export in this file.  in other words you need to import the module first to be able to augment it.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
