### ISSUE TITLE
Freshness broken for empty state

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#13423]
**TypeScript Version:**  nightly

**Code**

```ts
class Foo extends React.Component<{}, {}>{
  render() { return <noscript /> }
  foo() {
    this.setState({ something: true }); // Should error but doesn't
  }
}
```
:rose:

**Comment by wallverb** [comment]
Isn't it because you can assign anything to `{}` ?
```ts
let a:{} = {something:true} // OK
```

**Comment by basarat** [comment]
It is and thats the issue I should have created.

But is there a reason why `{}` should be allowed to bypass the *strict object checking* (freshness) rule ? :heart:

**Comment by wallverb** [comment]
FYI https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-all-types-assignable-to-empty-interfaces

**Comment by basarat** [comment]
@wallverb Thanks! 

> In general, you should never find yourself declaring an interface with no properties. 

But we do cause `setState` is dangerous for beginners https://medium.com/@mweststrate/3-reasons-why-i-stopped-using-react-setstate-ab73fc67a42e#.ja8gt8txu so we swapped state to `{}` 

And then migrating code from `setState` to `@observable` becomes painful to clean up as all those calls to `setState` don't highlight as errors. We instead needed to painfully find references to `setState` :rose:

**Comment by wallverb** [comment]
@basarat Maybe exact types would help https://github.com/Microsoft/TypeScript/issues/12936

Here is the result in Flow:
```js
type Foo = {  };
type Bar = {|  |};

const foo:Foo = { a: 4 } // Works
const bar:Bar = { a: 5 } // Error Property `a` not found in object type
```

**Comment by basarat** [comment]
They would help. 

I would still argue that it is okay that `{foo:true}` works with `{}`, but should respect the freshness check just like other things that fail in the presence of freshness :rose:

**Comment by RyanCavanaugh** [comment]
`{ }` is a frequent "safer" alternative to `any` for input positions. Freshness detection is generally intended to detect typos (`this.setState({ weigt: 12 });`); the "typo" of including a property where *none* are allowed (?) is a very strange error to make. It's very unlikely the recipient of the value *demands* an empty object -- why would anyone be doing that?

**Comment by basarat** [comment]
> why would anyone be doing that

@RyanCavanaugh for migrating off of `setState` : https://github.com/Microsoft/TypeScript/issues/13423#issuecomment-272020013 :rose:

**Comment by RyanCavanaugh** [comment]
If you want something that nothing is assignable to, use `void`

**Comment by basarat** [comment]
> If you want something that nothing is assignable to, use void

Excellent. That solves my need. Closing as I don't need this changed anymore :rose: and the decision to do the freshness checks for `{}` is a choice I leave for you / other humans 🤗 , create an issue or ignore :heart:
