### ISSUE TITLE
feature request: please print more vertical space (newlines) between tsc --watch results

### ISSUE THREAD

**Issue by ORESoftware** [Microsoft/TypeScript#13428]
I read this:
https://github.com/Microsoft/TypeScript-wiki/blob/master/Writing-Good-Design-Proposals.md

doesn't seem to apply here

**TypeScript Version:**  2.1.4

I am loving `tsc --watch`

but **problem:** what's making` tsc --watch` much more difficult to use than otherwise, is the fact that there is no obvious delineation for when previous compile fails happen and current compile fails happen in the terminal. It takes a lot of work for the human to search in the terminal for where the current compile results begin/start.

All it would take would be for tsc to print a couple more newline characters. Seems totally reasonable, please let me know if you think it is reasonable too. `tsc --watch `would be so much more usable, and with a couple extra newlines, should not be any less machine readable.

Thanks!

**Comment by mhegazy** [comment]
Sounds reasonable. A PR would be appreciated.
