### ISSUE TITLE
Promise type inference issue with supertypes

### ISSUE THREAD

**Issue by rkirov** [Microsoft/TypeScript#13420]
**TypeScript Version:**  2.1.4 

**Code**

```ts
declare let p: Promise<number>;
declare let p2: Promise<number|string>;

// TS infers pfinal to be Promise<number> incorrectly.
// pfinal should be Promise<number|string>
let pfinal = p.then(_ => p2);
```

**Expected behavior:**
Pfinal should be `Promise<number|string>`

**Actual behavior:**
Pfinal is inferred to be `Promise<number>`

Note any choice of `Promise<T>` and `Promise<S>` where S is a supertype of T will trigger this error.

This happens because then function overload ```then(onfulfilled?: ((value: T) => T | PromiseLike<T>) | undefined | null, ...): Promise<T>;``` is matching before the one with the free type parameter `TResult`.

As far I can tell it is a consequence of the fix in https://github.com/Microsoft/TypeScript/issues/10524#issuecomment-245120857 and not a desired change.

//cc @calebegg

**Comment by aluanhaddad** [comment]
This is related to #13015, #13008 and in particular this comment from the latter https://github.com/Microsoft/TypeScript/issues/13008#issuecomment-267819249

**Comment by rkirov** [comment]
Agree, thanks for reference, closing in favor of https://github.com/Microsoft/TypeScript/issues/10977 as the canonical bug for this.
