### ISSUE TITLE
[TSServer] Formatting RulesProvider (re)initialization performance issues

### ISSUE THREAD

**Issue by jramsay** [microsoft/TypeScript#13429]
The RulesProvider currently gets initialized in the LanguageService on the first formatting call to GetRuleProvider().  Initialization takes ~60ms.  Every time the editor options change the RulesProvider's RuleMap is repopulated. When edits occur in a script block file (.html, .cshtml) and then a .js/.ts file the editor options change (ex: baseIndentation) and the RulesProvider is reinitialized.

Creating this item for perf improvements to the RulesProvider.

ex:
1. Convert RulesProvider to be a singleton in TSServer 
2. Add another property to Rule to specify the ScriptKind or IsMixedContent type it applies to.

**Comment by amcasey** [comment]
There is no longer a type with that name, but an out of date test suggests that it was probably the thing that returned formatting items.  At this point, I'm inclined to say that we should wait until we see evidence of this in a CPU trace.
