### ISSUE TITLE
Type null is not assignable to type object with strictNullChecks

### ISSUE THREAD

**Issue by xLama** [Microsoft/TypeScript#13438]
**TypeScript Version:**  2.2.0-dev20170112

**Code**

```json

{
    "compilerOptions": {
        "strictNullChecks": true
    },
}
```

```ts
let foo : object = null

```

**Expected behavior:**

No error due to typeof null === "object"

**Actual behavior:**
Error. Type null is not assignable to type object

**Comment by ahejlsberg** [comment]
This is working as intended. The fact that `typeof null === "object"` is [generally considered a mistake](http://stackoverflow.com/questions/18808226/why-is-typeof-null-object), but it would be a breaking change for JavaScript to fix it. Luckily we can have TypeScript catch it!
