### ISSUE TITLE
Unfinished Types

### ISSUE THREAD

**Issue by mavericken** [Microsoft/TypeScript#13439]
I think there should be a way to describe a type that is finished for the properties that are defined, but unfinished for properties that are not defined.

Example Use Case:
```
unfinished interface FancyAPI {
  version: number,
  endpointURL: string
}

var test:FancyAPI = getFancyAPI();
test.version = "test" // should have an error here
test.endpointName = "localhost/fancyAPI" // should have no error here
test.someExtraInformation = "extra info" // should have no error here, should be type any
```

Really why I would want this is so I can incrementally build a type definition for code that previously had no type information.

**Comment by RyanCavanaugh** [comment]
What you're asking for is effectively #12596

**Comment by mavericken** [comment]
Ah, sorry for the duplicate-- it is tricky to find these things with such a large pile of issues.  I like the feature as proposed in #12596 more.
