### ISSUE TITLE
Formatting is ignored on function argument

### ISSUE THREAD

**Issue by saschanaz** [microsoft/TypeScript#13434]
**TypeScript Version:**  master branch

**Code**

```ts
foo().then
    <
    void
    >
    (
            3 // indent this line with more tabs after copy-pasting and then tap enter key
    )
```

**Expected behavior:** The line should be formatted

**Actual behavior:** Formatting is ignored.

**Comment by RyanCavanaugh** [comment]
This doesn't seem to come up in practice
