### ISSUE TITLE
How to register custom CodeAction?

### ISSUE THREAD

**Issue by angelozerr** [microsoft/TypeScript#13435]
I'm implementing a tslint language service tsserver plugin at https://github.com/angelozerr/tslint-language-service like Angular2 is providing. It starts working well (I can use the TypeScript source file parsed by tsserver to do the validation).

Now I would like to support CodeFix but it seems that it's not possible? I would like to call the `registerCodeFix` function but it seems that CodeFix feature are marked as internal.

My naive idea is that LanguageService should provide the `LanguageService #registerCodeFix(CodeAction action)`

Many thanks for your help!

**Comment by angelozerr** [comment]
Thanks @mhegazy to have tagged this issue. Which fix do you think you will to do? Add a new method `LanguageService #registerCodeFix(CodeAction action)` ?

**Comment by jakebailey** [comment]
Just looking at old issues; this largely has been supported for a while via proxying `getCodeFixesAtPosition` in the plugin, a la: https://github.com/microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin#decorator-creation

A concrete example in angular: https://github.com/angular/angular/blob/5d11844a7c31df56d2b97e3aa6cd1a70b5fccc70/packages/language-service/src/ts_plugin.ts#L166
