### ISSUE TITLE
How to implement TypeScript 2.2 plugin?

### ISSUE THREAD

**Issue by angelozerr** [microsoft/TypeScript#13436]
TypeScript 2.2 will provide the capability to customize TypeScript tsserver commands with plugin.

Today it exists 2 plugins :

 * A plugin for Angular2 => https://github.com/angular/angular/tree/master/modules/%40angular/language-service
 * A plugin for tslint => https://github.com/angelozerr/tslint-language-service 

I'm trying to implement tslint plugin like Angular2 plugin, but it should be cool if we could have a guide like "How to implement TypeScript plugin". For instance I have noticed that Angular2 plugin waits a method `create(info: ts.server.PluginCreateInfo)`. Could you specify please which properties contains ts.server.PluginCreateInfo (it seems that there is `languageServiceHost`, `languageService `and `project`)

Could you tell me please the strategy for loading the plugin? How tsserver which plugins it must load?

Many thanks for your clarification!

**Comment by mhegazy** [comment]
This is still work in progress. so there is not really a TS 2.2 plugin. you can follow the progress in https://github.com/Microsoft/TypeScript/pull/12231

**Comment by angelozerr** [comment]
Thanks @mhegazy for your answer. Now I see how to plugins to load are declared (in the tsconfig.json).

Thanks again!
