### ISSUE TITLE
compileOnSave not working with version control

### ISSUE THREAD

**Issue by strohhut** [Microsoft/TypeScript#13443]
**TypeScript Version:**  2.1.4 

I have a folder with a tsconfig.json file and ~30 .ts files in the same folder or sub folders of it. For version control I'm using the GIT that comes with Visual Studio. There are added, modified and unmodified .ts files inside the folder. Now when I build the whole project .js files are generated but when I change a .ts file and save it nothing happens.

I copied the whole content of the folder to another folder and now all files have the added state. Inside this new folder both building and saving modified .ts files work as expected (.js files are generated).

Because it always seems to work when building the whole project and compileOnSave works if I copy everything to a new folder I'm pretty confident that it's not a problem of my tsconfig.json or other setup.

I tested it with/without outFile. The result is the same.

I'm using Visual Studio 2015 Community Edition Update 3 on Windows 7 SP1 64 Bit.

**Expected behavior:**
.js files are generated regarldess of version control

**Actual behavior:**
.js files aren't generated with version control in use.

**Comment by strohhut** [comment]
Same with 2.1.5

**Comment by mhegazy** [comment]
Please share a repro project or clear steps to get this to reproduce locally.

**Comment by strohhut** [comment]
It's not reproducible with a new, simple project. Unfortunately I can't share my real code.

I found out that probably the state of the file (modified, unmodified,...) might not be the cause because it worked when I simply renamed the root folder of the ts project where compileOnSave fails (instead of copying the content to another folder which worked too).

When I renamed the folder to its old name compileOnSave again stopped to work. I have no dependencies on the folder name (the tsconfig paths are relative) so I guess it has to be some strange locking issue. Running VS in admin mode, stopping antivirus and removing all read-only flags didn't help.

**Comment by mhegazy** [comment]
> Also node.exe is randomly locking some ts files for unknown reasons. So I needed to kill all node processes before I could even rename the folder in order to find out that compileOnSave works with a different folder name.

The TS language service does not use node. so looks like there is something else going on.

**Comment by strohhut** [comment]
Yeah, I just wanted to explain why I can't make a simple repro (because it's a complex real-life project with multiple things going on). But I still think it might be a TypeScript bug because on buildings it generates the js file correctly and if I use gulp-typescript with save watches on my .ts files it works too (so it's not like everything is looked in my project and nothing works). It's just that compileOnSave won't fire under some circumstances which I don't know.

**Comment by mhegazy** [comment]
> It's just that compileOnSave won't fire under some circumstances which I don't know.

I would love to help. but you see there is not much i can do here without some repro steps/projects.

**Comment by strohhut** [comment]
Thanks, I'll re-open if I can provide more information (probably will end up with renaming the folder and updating all other projects that depend on it though).
