### ISSUE TITLE
No error when using uninitialized class members

### ISSUE THREAD

**Issue by mthurlin** [Microsoft/TypeScript#13445]
Not sure if this is a bug or a missing feature.

**TypeScript Version:**  Playground, with strictNullChecks turned on

**Code**

```ts
class Foo {
    public bar: string; 
}

const foo = new Foo();
const x = foo.bar.indexOf("x");
```

**Expected behavior:**

A warning/error on the line ```const x = foo.bar.indexOf("x");``` about ```bar``` being used before assignment (or being possibly undefined).
_Alternatively:_
A warning that ```public bar: string;``` must be assigned in the constructor or declared optional with ```?```.

**Actual behavior:**

No warnings/errors

**Comment by RyanCavanaugh** [comment]
Duplicate #8476. Please search before logging new issues!

![image](https://cloud.githubusercontent.com/assets/6685088/21899171/2970e0d4-d8a4-11e6-89ab-213e6236ac3d.png)
