### ISSUE TITLE
Error when trying to iterate over Map with for..of when targetting es5

### ISSUE THREAD

**Issue by zgredzik** [Microsoft/TypeScript#13440]
**TypeScript Version:**  2.1.5

**Code**

```ts
for(let [k, v] of new Map()) {
}
```

**Expected behavior:**
Compiles without errors when targeting es5 but including appropriate libraries in compilation

**Actual behavior:**
The compilation error depends on the `lib` and `target` configuration options:
* when simply targeting es5 the compilation results in an error:
`test.ts(1,23): error TS2304: Cannot find name 'Map'.`
which is fine
* when targeting es6 the compilation runs smoothly
* when targeting es5 but adding the same libs as the ones being injected by default when targeting es6 (according to [docs](http://www.typescriptlang.org/docs/handbook/compiler-options.html)):
`"target": "es6", "lib": ["DOM","ES6","DOM.Iterable","ScriptHost"]` (part of `tsconfig.json`)
there is an error:
`test.ts(1,19): error TS2495: Type 'Map<any, any>' is not an array type or a string type.`

Is this a bug or an expected behaviour? From my understanding the `--lib` option was added explicitly for the purpose of being able to write proper es6 code when targetting es5.

**Comment by aluanhaddad** [comment]
This is currently being worked on https://github.com/Microsoft/TypeScript/pull/12346

**Comment by mhegazy** [comment]
This should be addressed by https://github.com/Microsoft/TypeScript/pull/12346 under `--downlevelIteration`. Make sure  `es2015` or `es2015.iterable` is part of your `--lib` arguments.

**Comment by PeterHorvathIsento** [comment]
Typescript 2.6, having still the same problem. I remember, it was the same already for a year ago, too.

Only workaround was to emit ES6 code, and then compile it further with additional tools to ES5.

**Comment by mhegazy** [comment]
have u used `--downlevelIteration` and ensured `es2015` or `es2015.iterable` is part of your `--lib` arguments?
