### ISSUE TITLE
Suggest to provide Chinese error message

### ISSUE THREAD

**Issue by mishengqiang** [Microsoft/TypeScript#13458]
Hello,
I am a Chinese TypeScript developer.
I write the code, if there is an error, the information is prompted to present in English。
Suggest to provide Chinese error message for the Chinese TypeScript developer code.

This is the file location of the error message: https://github.com/Microsoft/TypeScript/blob/2.1/src/compiler/diagnosticMessages.json

**Comment by mhegazy** [comment]
What OS are you running against, and what editor are you using?

VS has all these errors localized, and so is tsc.exe. VSCode does not have this support thought.

**Comment by mishengqiang** [comment]
OS: macOS Sierra or Windows 10
Editor: VSCode

**Comment by aluanhaddad** [comment]
那太不好! 😢

**Comment by mishengqiang** [comment]
@aluanhaddad vscode团队可以帮我提供支持吗，或者说我能写个vscode的扩展程序来解决吗？

**Comment by aluanhaddad** [comment]
我不认为。在问没有中文。可是 将您试图 Visual Studio

**Comment by mishengqiang** [comment]
I don't want to use Visual Studio, because Visual Studio is not VSCode portable, and there is no Visual Stuido on macOS.
If TypeScript does not provide Chinese support, I'll go to the VSCode team to ask.

**Comment by DanielRosenwasser** [comment]
This should be supported in TypeScript 2.6.
