### ISSUE TITLE
Poor inference with union this

### ISSUE THREAD

**Issue by AlexGalays** [Microsoft/TypeScript#13454]
**TypeScript Version:**  2.2.0-dev.20161221

**Code**

```ts
type Union =
  { type: 'one', data: string } |
  { type: 'two', foo: number }

function doIt(this: Union) {
  switch(this.type) {
    case 'one': return this.data
  }
}
```

**Expected behavior:**
`this.data` should be available

**Actual behavior:**
this was not infered to be of the `{ type: 'one' }` variety.

**Workaround:**
Assign `this` to a const first and use that instead.

**Comment by mhegazy** [comment]
Seems fixed in latest.
