### ISSUE TITLE
Visual studio brace completion is a bit overzealous

### ISSUE THREAD

**Issue by Vilx2** [microsoft/TypeScript#13457]
First world problems. :smiley: 

**TypeScript Version:**  2.1.4.0
**Visual Studio Version:** Community 2015, 14.0.25431.01 Update 3
**Code**
```ts
for ( let i = 0; i < arr.length; i++ )
```
**Expected behavior:**
You can just type the whole line in one breath.

**Actual behavior:**
When typing this line the brace completion feature also tries to complete the angle bracket, resulting at one point in code like this:
```ts
for ( let i = 0; i <>
```
This is a bit annoying, since the other bracket now needs to be deleted. The same thing happens when trying to type anything with a "less than" comparison involved.

I don't know if proper context awareness is feasible for bracket completion, but perhaps the auto completion can be skipped for angle brackets? Or maybe it can be a separate setting for people with different tastes. I find that in my code I use comparisons more often that casts or generics, so the auto completion for angle brackets is doing more harm than good. But I like it for other kinds of brackets and strings, so the net gain is positive.

**Comment by victords** [comment]
I'm facing the same problem. Just commenting so the issue gets more attention. :)

**Comment by amcasey** [comment]
In VS 2019 with TS 3.6, I'm not seeing brace completion on `<`, even in JSX/TSX contexts.  Please let us know if you're still having issues.
