### ISSUE TITLE
Add ES4/AS3 is operator

### ISSUE THREAD

**Issue by klaiderklai** [Microsoft/TypeScript#13452]
**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)

There could be an *`is`* operator, it'd be so cool! I'm saying about the *`is`* operator that exists in [ES4](http://www.ecmascript.org/es4/spec/overview.pdf) and ActionScript 3.

**Example**

```ts
console.log(
    0 is Number,
    true is Boolean
);
```

It's like *`instanceof`*. The unique difference is that it checks for the constructor of primitive values.

Please implement it ! Thanks !

**Comment by RyanCavanaugh** [comment]
Abandoned ES4 runtime features should be taken to ES-Discuss / TC39.

**Comment by hydroper** [comment]
@RyanCavanaugh Thanks ! I'll check it out
