### ISSUE TITLE
Unable to find Interface within an interface

### ISSUE THREAD

**Issue by salmankhann** [Microsoft/TypeScript#13468]
**TypeScript Version:**  2.1.5
I'm following the instructions for splitting files using namespaces [(Typescript namespaces docs)](https://www.typescriptlang.org/docs/handbook/namespaces.html) but tsc is unable to import interfaces that are embedded within an namespace in another file.

Is this a bug in tsc or has the documentation on the site not been updated yet

```
//B.ts in another folder
namespace TestNameSpace {
    export interface B {

    }
}

//A.ts in another folder
/// <reference path="../xx/B.ts" />
namespace TestNameSpace {
    export class A implements B { //cannot find name B

    }
}
```

**Expected behavior:**
B should be found in A.ts

**Actual behavior:**
Cannot find name B

**Comment by mhegazy** [comment]
Please include a self contained repro.

```ts
c:\test\13468>type xx\b.ts
namespace TestNameSpace {
    export interface B {

    }
}

c:\test\13468>type yy\a.ts
/// <reference path="../xx/b.ts" />
namespace TestNameSpace {
    export class A implements B { //cannot find name B

    }
}
c:\test\13468>tsc --v
Version 2.1.4

c:\test\13468>tsc

c:\test\13468>echo %ERRORLEVEL%
0

```

**Comment by salmankhann** [comment]
I'm unable to execute those commands. I'm on a mac. Whatever I do it just tells me type xx not found. Here is my tsconfig

```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es2015",
        "inlineSourceMap": true
    },
    "include": [
        "source/**/*"
    ]
}
```

**Comment by aluanhaddad** [comment]
Works perfectly.

**Comment by salmankhann** [comment]
hmm interesting. does it matter that its is different folders? I have the interface in 'foundation' folder and the implementation in the 'datasource' folder. Foundation and datasource being siblings

**Comment by aluanhaddad** [comment]
as long as the paths in the
```ts
/// <reference path="../xx/B.ts" />
```
It will work.

I tested with:
**source/yy/a.ts**
and
**source/xx/b.ts**
Ensure your **tsconfig.json** is located in the directory that _contains_ **source**.

**Comment by salmankhann** [comment]
the tsconfig already is in the source folder. Funnily enough, even when I place the implementation in the same folder as the interface, it still tells me that the interface is not found. Does the name of the interface file need to be same as the interface (like in Java)?

**Comment by aluanhaddad** [comment]
@salmankhann no this is not like Java names are abstracted from files.
>the tsconfig already is in the source folder

If you lay it out like that and run `tsc` you will get the error
>No inputs were found in config file 'C:/Source/GitHub/ts-13468/tsconfig.json'. Specified 'include' paths were '["source/**/*"]' and 'exclud
e' paths were '[]'.

**Comment by salmankhann** [comment]
@aluanhaddad @mhegazy  My config seems to be correct. I've uploaded my demo repo here. https://github.com/salmankhann/crawler-test.git

Can you tell me what I'm doing wrong? Thanks!
