### ISSUE TITLE
Interfaces do not require constraints in implementations

### ISSUE THREAD

**Issue by sevaru** [Microsoft/TypeScript#13463]
**TypeScript Version:**  2.1.5

**Code**

```ts
interface IFoo {
    method(a: number, b: string): void;
}

// No errors in compilation
class Foo implements IFoo {
    public method(): void {
          ///...
    }
}

// No errors in compilation
class Bar implements IFoo {
    public method(a: number): void {
          ///...
    }
}

```

**Expected behavior:**
Compilation error due to incorrect interface implementation

**Actual behavior:**
Compilation is ok

**Comment by mhegazy** [comment]
Please see https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-functions-with-fewer-parameters-assignable-to-functions-that-take-more-parameters

**Comment by sevaru** [comment]
@mhegazy I was a little bit confused. Thank you for your explanation.
