### ISSUE TITLE
Error when implementing abstract class, cannot declare abstract private property abstract class.

### ISSUE THREAD

**Issue by supermoos** [Microsoft/TypeScript#13465]
**TypeScript Version:** 
2.1.4
**Code**

```ts
export abstract class A {
    public abstract somePublicMethod: () => void;
    private abstract somePrivateProperty:string;
}

class B implements A {
    private somePrivateProperty:string;

    public somePublicMethod = () => {
        console.log(this.somePrivateProperty);
    }
}

```

**Expected behavior:**
Should require Class B to have a private property named somePrivateProperty of type string.
**Actual behavior:**
```
Error:(23, 7) TS2420:Class 'B' incorrectly implements interface 'A'.
  Types have separate declarations of a private property 'somePrivateProperty'.
```

doesnt' work marking `private abstract somePrivateProperty:string;` as `protected abstract somePrivateProperty:string;` either.

**Comment by mhegazy** [comment]
Private properties are visible **only** in their declaring class. a derived class can not re-declare a private member. this makes a class with a `private abstract ` field impossible to implement.

**Comment by supermoos** [comment]
Hmm, should this not be possible as an exception in abstract classes though?
