### ISSUE TITLE
GADT distinguished by boolean property not narrowed on test for truthiness

### ISSUE THREAD

**Issue by svieira** [Microsoft/TypeScript#13464]
I have a `Success` / `Failure` tagged union type called `Result`, where the tag property is of the one of the two literal types in `boolean`.  `Success` uses the literal type `true` and `Failure` uses the literal type `false`.  I would expect that a test like `if (someResult.success)` would narrow the type in the `else` branch to `Failure`, but it does not.

**TypeScript Version:**  2.1.4-insiders.20161201 (on the Playground)

**Code**

```ts
type Success<T> = { success: true, result: T };
type Failure = {success: false, err: Error};
type Result<T> = Success<T> | Failure;

// Also possibly a bug - type assertion is necessary too
// Otherwise r is upcast to a Success<T> in spite of the type ascription
const r: Result<number> = { success: true, result: 1 } as Result<number>;

if (r.success) {
  r.result;
} else {
  r.err
}
```

**Expected behavior:**

No compilation error

**Actual behavior:**
Compilation error at the `r.err`:

> Property 'err' does not exist on type 'Result<number>'.
>  Property 'err' does not exist on type 'Success<number>'.

**Comment by ahejlsberg** [comment]
Duplicate of #10564. It works as expected in `--strictNullChecks` mode.

The behavior without the `as` assertion is expected because control flow analysis has narrowed the actual type of `r` to `Success<number>`.

**Comment by svieira** [comment]
Fantastic - thanks for the explanation!
