### ISSUE TITLE
HTMLElement.style defined as readonly when it is mutable

### ISSUE THREAD

**Issue by kg** [Microsoft/TypeScript#13466]
**TypeScript Version:**  2.1.5
**Code**

```ts
var elt = document.createElement("div");
elt.style = "test";
```

**Expected behavior:**
Should compile and run

**Actual behavior:**
Typescript compiler rejects the assignment to ``style`` as invalid.
[According to MDN](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/style) this is a valid assignment, and it works in every modern browser. The *value* returned by ``.style`` is readonly, but the property itself is not.

**Comment by mhegazy** [comment]
Base on the spec:  https://www.w3.org/TR/DOM-Level-2-Style/css.html#CSS-ElementCSSInlineStyle, `style` is readonly.
