### ISSUE TITLE
Infer a union from a set of candidates instead of only a super-type

### ISSUE THREAD

**Issue by chuckjaz** [Microsoft/TypeScript#13481]
**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)

Consider the following:

```ts
function first(items: T[] | Iterable<T>): T {
  for (let item of items) return item;
  throw new Error('No first element');
}

let items: number[] | string[];

let i1 = first(items);

for (let i2 of items) {
  // ...
  break;
}
```

**Desired behavior:**

Infer `number | string` for both `i1` and `i2`.

**Actual behavior:**

A type cannot be inferred for `i1` (candidate `number` not a sub-type of `string`). `number | string` is inferred for `i2`.

**Proposal**:
Change [4.15.2](https://github.com/Microsoft/TypeScript/blob/2.1/doc/spec.md#4152-type-argument-inference) second clause from:

> * Otherwise, if at least one of the candidate types is a supertype of all of the other candidate types, let *C* denote the widened form (section [3.12](#3.12)) of the first such candidate type. If *C* satisfies *T*'s constraint, the inferred type argument for *T* is *C*. Otherwise, the inferred type argument for *T* is *T*'s constraint.

to:

> * Otherwise, remove all types from the set for which another type in the set is a supertype of the type and is not the type itself. Let *C* denote the union of the widened form (section [3.12]) of all remaining types. If *C* satisfies *T*'s constraint, the inferred type argument for *T* is *C*. Otherwise, the inferred type argument for *T* is *T*'s constraint.

It should be clear that in all cases that the previous algorithm produces a type *C* this change produces the same type *C* without introducing additional algorithmic complexity. It should also be clear that the above change produces the desired result of `number | string` for `i2`. 

The current implementation diverges from the specification but it should be clear how to map this change with the current implementation (that is, inferiority does not significantly change it and union factoring helps it).

If this change is implemented, consider removing the special case typing rules for `for let x of` (declarations in a `ForInStatement` node) as the current behavior is a direct consequence of the change in typing rule if the element type is inferred as `T` from the type:

```ts
  type NgForOfElementType<T> = Iterable<T> | { readonly length: number; readonly [index: number]: T;
```

which would then enable abstraction over a `for` to produce the same type as an inlined `for`.

**Background**:

Angular has a type `NgFor` which we are adding a type parameter to allow inferring element type of the iterated instance. However, there appears to be no way declare  `NgFor` such that it will infer the same type an equivalent `for of` would produce. For example,

```html
<ul>
  <li *ngFor="let item of items">
    {{item}}
  </li>
</ul>
```

The expectation is that the type of `item` would be `number | string`. However, there appears to be no way to construct a set of calls that produces the implied instances and infers `number | string` for `item` (https://github.com/angular/angular/issues/12398).

We believe this change would be helpful for TypeScript but we are not blocked by its absence.

**Comment by mhegazy** [comment]
This is only safe in read positions, but not in write positions. consider:
```ts
declare function add<T>(list: T[], value: T): void;

let items: number | string[];
add(items, 2);
```
Inferring `number|string` here would result in unsafe code.

We really need in/out annotations on parameters to be able to do this without violating safety. 

Is providing an explicit type parameter an option (e.g. `typeof items[number]`) ?

**Comment by aluanhaddad** [comment]
@mhegazy Perhaps this could work for `ReadonlyArray<T>`?

Also, I noticed a weird issue.
I tried to work around this using union types and I got this

![image](https://cloud.githubusercontent.com/assets/5034656/21959251/57bce25c-da8f-11e6-868b-4c83a4b50395.png)

Based on [@ahejlsberg's comment in #13346](https://github.com/Microsoft/TypeScript/issues/13346#issuecomment-271163885) this should not happen.

**Comment by mhegazy** [comment]
>  Perhaps this could work for ReadonlyArray<T>?

the issue here is not about `Array` or `ReadonlyArray`. the issue is no way to mark parameters in general as `readOnly`/`in`, `writeOnly`/`out` or `readWrite`. the type system does not track that, and a full support is needed in the type system first, then we can annotate `ReadonlyArray` accordingly.

**Comment by chuckjaz** [comment]
@mhegazy The current algorthim is similarly unsafe as it selects a super-type in the candidate list so your example could easily be written as:

```ts
declare function add<T>(list: T[], value: T): void;

let items: number[] | string[] | (number| string)[] = [];

add(items,2);
```
and type-check because of the candidate types `string`, `number` and `number | string`, `number | string` is a super-type of all other types and is selected even though it is unsafe used co-variantly.

The whole is really that following type-checks,

```ts
add<number|string>(items);
```

The whole is introduce not by type inference but, rather that array's type parameter is type-check variant instead of invariant (that is T[] is consider a super-type of S[] if T is a super-type of S) . Regardless of the inferencing, treating arrays as variant is a whole. (It should be invariant because `T` is used in both a variant and co-variant position meaning the only safe typing is invariant).

My change, therefore, doesn't introduce a new whole though it probably makes an existing whole easier to hit. C# and Java have similar wholes, because invariant typing arrays here is a pain, but their VM type-checks the write at runtime.

The issue is really not safety, but rather, whether synthesizing a super-type during type inference is useful and doesn't cause the algorithm to diverge. I believe I have made a case for both.

**Comment by mhegazy** [comment]
The type whole does exist. but as you noted it is less likely for sub type reduction to produce an error now than with this proposed change; and i am not sure if the utility resulting from this change overweights the loss of safety introduced.

**Comment by chuckjaz** [comment]
I don't find using expanding the cases a user can run into the type whole very persuasive as your example is rather a corner case and whole itself is huge. For example, even with no type-inferencing, the following code type-checks:

```ts
class A {}
class B extends A {}

let a: A = new A();
let items: B[] = [];
items.push(a);
```

Even if this was disallowed as obviously wrong you are still left with,

```ts
class A {}
class B extends A {}

let a: A = new A();
let items: B[] = [];
let aItems: A[] = items;
aItems.push(a);
```

which is equally wrong but is allowed because of variant subtype relation. These, I would argue, are much more common errors that a user would run into that can easily be transformed into type inferencing problems with either algorithm.

The reason your example doesn't type-check is not because it is unsafe, rather, it is because a super-type was not found. This only bans a very narrow set of cases and is easily accidentally thwarted. Plus it introduces a false sense of security as the user might think, since some cases are caught, all cases are caught. Preventing new ways to run into the whole seems to be like keeping the back door closed while the front door is wide open.

In TypeScript, writing to an array is not sufficiently checked. The whole is deep and wide and makes TypeScript's type system unsound; but it would be extremely taxing to fix as it would throw co-variance in the users face where they don't expect it. In a customer segment that is already type hostile, adding a feature that makes even type enthusiasts hostile, sounds like something that should be done very carefully.

I would say, given this, that the utility of a change only has to meet a very low bar to cross the threshold to justify itself against increasing the number of paths to the whole. I believe my change, which allows expressing the type relation implied by `for...of`, meets that bar.

**Comment by chuckjaz** [comment]
Thinking about this more I believe the potential change in overloading resolution results is not worth the benefit of this change. I still like this idea but the change should be tied together with something else that has more general utility, like type parameter variant declaration as you suggest above, as potentially breaking something like `Promise.then()` would definitely not be worth this change.
