### ISSUE TITLE
typeRoot lookup failing on Windows

### ISSUE THREAD

**Issue by colinskow** [Microsoft/TypeScript#13486]
This issue affects TypeScript v2.1.5 only on Windows and works fine on Mac/Linux. TypeScript v2.0.10 has no problem. According to the TypeScript [documentation](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types), the compiler should automatically look in `node_modules/@types` to resolve specified `types` in `tsconfig.json`.

On Windows I am getting the error: `Cannot find type definition file for 'hammerjs'` when compiling. Adding the following to `tsconfig.json` resolves the issue:

```json
"typeRoots": [
      "node_modules/@types"
    ],
```

The expected behavior is that this declaration should be unnecessary. This bug is appearing from within `awesome-typescript-loader` v3.0.0-beta.18 using Webpack v2.2.0-rc.4. It also appears when running Protractor with TS test files. I haven't been able to reproduce it using TSC command line yet.

**Comment by colinskow** [comment]
Sample `tsconfig.json` that is producing the issue:

```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "es2015",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "noEmit": true,
    "noEmitHelpers": true,
    "strictNullChecks": false,
    "lib": [
      "es2015",
      "dom"
    ],
    "types": [
      "hammerjs",
      "node"
    ]
  },
  "exclude": [
    "node_modules",
    "dist",
    "src/**/*.spec.ts",
    "src/**/*.e2e.ts"
  ],
  "awesomeTypescriptLoaderOptions": {
    "forkChecker": true,
    "useWebpackText": true
  },
  "angularCompilerOptions": {
    "genDir": "./compiled",
    "skipMetadataEmit": true
  },
  "compileOnSave": false,
  "buildOnSave": false,
  "atom": {
    "rewriteTsconfig": false
  }
}
```

**Comment by mhegazy** [comment]
I can not reproduce this locally runnig with `tsc`. Possibly an `awesomeTypescriptLoader` issue.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
