### ISSUE TITLE
Cannot to extends classes with static methods after Babel

### ISSUE THREAD

**Issue by microshine** [Microsoft/TypeScript#13480]
**TypeScript Version:**  2.1.4

**Code**

![image](https://cloud.githubusercontent.com/assets/7333669/21945897/f4c459e6-d9ee-11e6-9db0-7802d52ddbf1.png)

It's not a TypeScript error. But maybe it would be good to support modules created with Babel

http://stackoverflow.com/questions/41644241/how-to-set-enumerable-property-for-babel

**Comment by aluanhaddad** [comment]
I believe you will find this pertinent https://github.com/Microsoft/TypeScript/pull/12488

**Comment by DanielRosenwasser** [comment]
Should be fixed by #12488, thanks for finding @aluanhaddad.
