### ISSUE TITLE
Module resolution failed when the main entry is a directory

### ISSUE THREAD

**Issue by idiotWu** [Microsoft/TypeScript#13484]
**TypeScript Version:**  2.1.5

**Code**

```ts
import * as HttpStatus from 'http-status';
```

**Expected behavior:**

Compiled without error.

**Actual behavior:**

```
error TS2307: Cannot find module 'http-status'.
```

This module declares `main: ./lib` in package.json, so the module resolution fails. Compilation succeeds only if I change it into `main: ./lib/index.js`.

**Comment by blakeembrey** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/13406?

**Comment by idiotWu** [comment]
Ah, hadn't noticed that...

**Comment by DanielRosenwasser** [comment]
Duplicate of #12974.
