### ISSUE TITLE
Enable/disable compiler options / checks at Module level

### ISSUE THREAD

**Issue by pcj** [Microsoft/TypeScript#13496]
Closure has the nice ability to enable or disable checks on a fine-grained basis, including module-level, such as:

```js
/**
 * @fileoverview
 * @suppress {reportUnknownTypes}
 */
import * from 'foo';
...
```

https://github.com/google/closure-compiler/wiki/@suppress-annotations

In my case, trying to migrate an existing large-ish codebase to `strictNullChecks`is simply overwhelming to do all at once.  

WDYT? Is this possible?  

I was thinking that instead of having statements like `if (compilerOptions.strictNullChecks) { ... }` in `checker.ts`, it could would delegate the check to the `Symbol` in scope, then to the File the symbol was declared in, and encapsulate checks there.
 

> Note: This issue is likely duplicate, but could not find others.

**Comment by aluanhaddad** [comment]
See #9448
