### ISSUE TITLE
'this' should initially refer to 'self'/'window'

### ISSUE THREAD

**Issue by klaiderklai** [Microsoft/TypeScript#13497]
**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)

**Code**

```ts
this
```

**Expected behavior:** No exceptions.

**Actual behavior:** Exception: `'this' implicity has type 'any' because it does not have a type annotation.`

Unfortunately there looks to be no way to annotate a type for 'this' globally. For example, `declare var this: any` causes the same error above, non-sense.

**Comment by Mosho1** [comment]
According to the ES2015 spec, in a `module` `this` evaluates to `undefined`, as opposed to a `script`. As TypeScript follows ES2015 for modules, this would be the case there as well.

**Comment by hydroper** [comment]
Hmm, it looks like even not declaring module files the error is thrown, in both `this` and `declare var this: any` occasions. I guess this should be something to be fixed and detected automatically.

**Comment by aluanhaddad** [comment]
How can you know if it is `window` or some other global? This would not be portable and require declaring an assumption about the environment. This would be similar to jslint's `assume-browser` option.
That said, are there any use cases for the desired behavior that don't involve writing bad code?

**Comment by hydroper** [comment]
@aluanhaddad Hm, so that means there's a problem to detect the `this`. But why can't I add a type notation for `this`, then ? My use case was to get () the global addEventListener property.

**Comment by aluanhaddad** [comment]
You need to get the global then, not `this`. If you're working in the browser you can get it from the `window` object.

**Comment by hydroper** [comment]
I don't need to get the addEventListener as a property as I can do that directly, but I'll try continue using `window` then -_-. My code gets unreadable when I relate with the global things

**Comment by aluanhaddad** [comment]
Are you saying you want to get a callable reference to the property?

**Comment by hydroper** [comment]
I just want to directly call that property. But I was not satisfied by just getting the global addEventListener reference, so I've tried to beautifulize it adding `this.` before `addEventListener`, but TypeScript gives the above warning about `this` type annotation. So my solution was to add `window.` instead.

**Comment by mhegazy** [comment]
`this` intentionally have the type `any`. this allows you to call `Window` methods on it, but will result in an error under `--noImplicitAny`. As noted earlier the meaning of `this` in the global scope is a [bit tricky](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this) and not recommended to be used. my recommendation is to use `window`, `self` or `global` based on your context.

**Comment by alitaheri** [comment]
Best use `global` with [this](https://github.com/tc39/proposal-global/blob/master/polyfill.js) polyfill as it will be the standard across all environments in the possibly near future.

**Comment by aluanhaddad** [comment]
@alitaheri That is an entertaining piece of code 😆. You don't realize it is 100% in earnest until you have finished reading it.
