### ISSUE TITLE
Compatibility check between .d.ts and corresponding js file.

### ISSUE THREAD

**Issue by HamedFathi** [Microsoft/TypeScript#13491]
HI

Suppose I have 'jquery-2.2.4.js' and a downloaded 'jquery.d.ts' for that based on description 

// Type definitions for jQuery 1.10.x / 2.0.x

But I have a question

Is there anyway (of course automatic way) for checking Compatibility check between .d.ts and corresponding js file ?

eg : tsc checkcompatibility  'jquery-2.2.4.js' 'jquery.d.ts' => No error or ...

because in most times in developing process we find problem(s) with .d.ts files.

**Comment by aluanhaddad** [comment]
No there is no way to do this automatically. If you find problem(s) with .d.ts files. I think everyone would be very appreciate of any PRs you might send to https://github.com/DefinitelyTyped/DefinitelyTyped as a result.

**Comment by ClickSimply** [comment]
Using the new @types npm install method is probably going to go a long way in helping to prevent this problem, for example:
`npm install @types/jquery --save` will get you jquery types.

Second, if you use the [TypeSearch](https://microsoft.github.io/TypeSearch/) tool it'll show you the version the types are written for.

![TypeSearch Screenshot](https://cloud.githubusercontent.com/assets/14365337/21954541/f85e9840-da08-11e6-95db-e8756c6d739a.png)

**Comment by HamedFathi** [comment]
@aluanhaddad   
@ClickSimply 

ok thanks
