### ISSUE TITLE
Use `object` non primitive type instead of `Object` interface

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#13493]
Most `Object` type should be replaced by `object` type added by #12501.

**TypeScript Version:**  master

**Code**

lib/*.d.ts

**Comment by falsandtru** [comment]
@mhegazy @DanielRosenwasser Can you update?

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.
