### ISSUE TITLE
expose Harness

### ISSUE THREAD

**Issue by tycho01** [Microsoft/TypeScript#13507]
**TypeScript Version:**  2.1.1

To properly [test type definitions](https://github.com/types/npm-ramda/issues/123), I'd like to use a similar test harness as TypeScript itself is. From my understanding, this is the only known way we could test to ensure a type is inferred properly, rather than returning `any` -- traditional tests used by typing definition repositories appear largely based on verifying absence of compilation errors, which would not be raised in this case.

I tried to reproduce the way TypeScript is testing [internally](https://github.com/Microsoft/TypeScript/blob/2d16b19ef9693f21e09bc933ee5a1709d848aaec/src/harness/rwcRunner.ts#L227-L231), but got stuck trying to get the `Harness` in scope, which appears magically in scope without imports in the TypeScript tests, while it appears [not directly exported](https://github.com/Microsoft/TypeScript/blob/9a3dd3e81cb02a52f16b8f9c7b30bcd43eb76cb2/src/harness/harness.ts#L473).

Could this be exported so as to allow definition writers to test for correctness with similar rigor? Am I just doing it wrong? Might others have managed to pull this off before?

**Comment by mhegazy** [comment]
The test harness just uses the compiler API. Can you elaborate on why you can not do the same?

for the issue of different inferences, the compiler issues an error if two variable declarations have a different type. We rely on this for some of our baselines tests. for instance:

```ts
var x: number;
var x = foo();  // Error if `foo()` returns anything that is not a number.
```

**Comment by tycho01** [comment]
Thank you, your example here was insightful; I hadn't realized.

I tried a few different versions just now; I must say the distinction feels un-intuitive to me, which makes me wonder if this was self-evident to others:
```ts
var x: number;
var x = foo();  // error: Subsequent variable declarations must have the same type.  Variable 'x' must be of type 'number', but here has type 'any'.
var y: number;
y = foo();  //passes
var z: number = foo();  //passes
```

That said, with your suggestion my problem is addressed, thank you. :)

~tl;dr I probably just don't know how.~

~The trial-and-error that lead me there:~
- ~look at the baseline tests in the Gulpfile~
- ~realize it didn't seem to handle generating the baseline output~
- ~find clear mention of the `symbols` files [here](https://github.com/Microsoft/TypeScript/blob/2d16b19ef9693f21e09bc933ee5a1709d848aaec/src/harness/rwcRunner.ts#L227-L231) -- I'd searched for this as the `types` extension seemed harder to search for.~
- ~try to mimic that approach~
- ~file because it's referring to `Harness` which I seemed unable to import from~

~Those functions used over there (`doTypeAndSymbolBaseline`, `compileFiles`, `isDefaultLibraryFile`, ...) did appear to come from that `harness.ts` file as the `Harness` namespace had implied.
You mention it should be possible to do from the compiler directly, so evidently I've searched in the wrong direction.~

**Comment by tycho01** [comment]
In retrospect, I think I'm still interested in figuring out how to pull off the baseline testing for type definition libraries -- `@types/npm-ramda` still have such an amount of typing issues (many caused by erased generics) that I kind of need to learn the resulting diffs rather than just error output to accurately judge commits' impact.

To answer your "why not do the same", tl;dr I probably just don't know how.

The trial-and-error that lead me there:
- look at the baseline tests in the Gulpfile
- realize it didn't seem to handle generating the baseline output
- find clear mention of the `symbols` files [here](https://github.com/Microsoft/TypeScript/blob/2d16b19ef9693f21e09bc933ee5a1709d848aaec/src/harness/rwcRunner.ts#L227-L231) -- I'd searched for this as the `types` extension seemed harder to search for.
- try to mimic that approach
- file because it's referring to `Harness` which I seemed unable to import from

Those functions used over there (`doTypeAndSymbolBaseline`, `compileFiles`, `isDefaultLibraryFile`, ...) did appear to come from that `harness.ts` file as the `Harness` namespace had implied.
You mention it should be possible to do from the compiler directly, so evidently I've searched in the wrong direction.

**Comment by RyanCavanaugh** [comment]
@tycho01 you might be interested in work going on here: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/1572

You're correct that generating type and symbol baselines is done in the Harness, not the compiler.

As for exposing Harness, though, I would recommend against taking a dependency on it for several reasons. First is that it's really not great code (no one has bothered to get it into shape for several years now) so it is not at all resilient to being run under any environment except exactly our repo. Second is that we are likely to refactor this code, often substantially, without warning or concern for external consumers (because there aren't any).

Assuming it's compatible with your license (I have no idea) I'd just rip the code directly from the TS source base and go from there.

**Comment by tycho01** [comment]
@RyanCavanaugh Thank you!
I can totally sympathize with wanting to retain the freedom to change it.
I imagine for the future others might be interested in something like this as well, but for my purposes these should suffice for now. Thanks!
