### ISSUE TITLE
error TS2339: Property 'userSelect' does  not exist on type 'CSSStyleDeclaration'

### ISSUE THREAD

**Issue by martinlindhe** [Microsoft/TypeScript#13506]
**TypeScript Version:**  2.1.5

**Code**

```ts
const el = document.createElement("div");
el.style.userSelect = "none"; // error here, property dont exist
```

**Expected behavior:**
since the user-select css property is now unprefixed, it would be good to be able to set it!

**Actual behavior:**
tsc compile error: `error TS2339: Property 'userSelect' does
 not exist on type 'CSSStyleDeclaration'.`

**More**
According to [caniuse.com](http://caniuse.com/#feat=user-select-none), unprefixed user-select is available in IE11, Edge, Chrome and Firefox

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by micopc** [comment]
Hi, I wanted to work on this but I found out that the code for this is located on dom.generated.d.ts which according to the CONTRIBUTING.md needs to be modified on https://github.com/Microsoft/TSJS-lib-generator. Am i correct or is there something I'm missing?

**Comment by mhegazy** [comment]
you are correct. the changes need to be made to  https://github.com/Microsoft/TSJS-lib-generator, we periodically port the changes back to this repo.
