### ISSUE TITLE
Cannot selectively include types in a declares from a modular node package.

### ISSUE THREAD

**Issue by andrewplummer** [Microsoft/TypeScript#13501]
I've bounced this around StackOverflow without any luck, so it may be something that declares files are currently unable to handle... I am trying to create a declares file for a node package, let's call it simply `package`. This package has different modules that define methods on a single core object. The structure looks like this:

```javascript
// index.js
require('./foo');
require('./bar');
module.exports = require('./core');
```

```javascript
// foo/index.js
var obj = require('../core');
obj.foo_method_1 = require('./foo_method_1');
obj.foo_method_2 = require('./foo_method_2');
// etc
module.exports = obj;
```

```javascript
// bar/index.js
var obj = require('../core');
obj.bar_method_1 = require('./bar_method_1');
obj.bar_method_2 = require('./bar_method_2');
// etc
module.exports = obj;
```

When requiring in node, using `require('package')`, `require('package/foo')`, and `require('package/bar')` all return the same object, however the last 2 will only define the methods within that module, while the first will define methods in all modules.

The goal is to be able structure the declares in a way that will model this, with only types for `foo` defined when using `import * as package from 'package/foo';`. However, the problem I keep hitting is that no matter how I structure it (I've tried several approaches), typescript will always end up loading the root declares file (`package/index.d.ts`) so that all members exist on the object, when this may not be the case.

How can I structure the declares so that only certain members exist when importing sub-modules?

Any help is appreciated. Thank you.

**Comment by aluanhaddad** [comment]
This one is a pain to figure out. RxJS is probably the best example to follow here.
However, trying to do so in your local folder structure, say for testing within the package or from a sibling directory, say **test**, does not work at all.

The directory containing the library needs to be matched, implicitly or explicitly, by the **_exclude_** property of your tsconfig.json!

Here is a working example:
Note that "exclude" defaults to `["node_modules", "jspm_packages", "bower_components"]` if left unspecified.
**tsconfig.json** (in test project)
```json
{
  "compilerOptions": {
    "module": "system",
    "moduleResolution": "node",
    "target": "es5"
  },
  "exclude" : [
    "node_modules", 
    "jspm_packages"
  ]
}
```
**node_modules/pkg/pkg.d.ts**
```ts
export declare class Pkg {
  withName: (this: this, name: string) => this & { name: string };
}
```
**node_modules/pkg/imbue/with-property.d.ts**
```ts
import { Pkg } from '../../pkg'; // this file must be a module
declare module '../../pkg' {
  interface Pkg {
    withProperty: <K extends string, V>(this: this, key: K, value: V) => this & {[P in K]: V };
  }
}
```
**consumer.ts**
```ts
import { Pkg } from 'pkg/pkg'
// import .withProperty
import 'pkg/imbue/with-property';

const p = new Pkg()
  .withName('Fred')
  .withProperty('age', 49);
```
Note that if you move **pkg** to a non-excluded location, say vendor, and import it from there, all methods will be available regardless of importing `'pkg/imbue/with-property'`.

This behavior is a bit confusing but also kind of makes sense.

**Comment by mhegazy** [comment]
You can find documentation about authoring declaration files at http://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html.

**Comment by aluanhaddad** [comment]
Maybe it would be good to clarify the RxJS usage where mutations are selectively brought into scope along with their implementations. Sure it is just one library, but it is very popular. I think the ambient merging nature of the augmentations that people are likely to add to their own projects is a source of confusion.

**Comment by mhegazy** [comment]
It would be helpful to add a section to http://www.typescriptlang.org/docs/handbook/declaration-files/by-example.html with this example.

**Comment by andrewplummer** [comment]
@mhegazy I've been in and out of the declare file documentation, but haven't found any way to do this. I would definitely be in favor of adding more examples.

@aluanhaddad To clarify, the `tsconfig.json` file needs to be in the project consuming the library, not in the `@types` repo, correct?

If this is the case, then it doesn't really work for me as I am trying to create declares files that will be consumed. Also, in your example, importing from `pkg/pkg` would not include the `withProperty` method, correct? This also differs from my use case, as in my case importing `pkg/pkg` would essentially include everything, where importing from `pkg/imbue/with-property` would only import that method.

**Comment by aluanhaddad** [comment]
I believe it will work. The reason it will work is that your consumers will install the type declarations under the node_modules folder.
You can make your scenario, which admittedly is different than I had thought, work using the same technique by breaking your declarations apart into individual augmentations and then reproviding them in specific groups to match the shape of your library.

**Comment by andrewplummer** [comment]
@aluanhaddad Apologies if I'm being obtuse here, but let me clarify my understanding. Are you saying that after installing `@types/pkg`, consumers would use `import { Pkg } from 'pkg/pkg'` instead of `import { Pkg } from 'pkg'`?

**Comment by aluanhaddad** [comment]
You can lay it out in a bunch of different ways. The directory structure itself is fairly arbitrary. The reason I used PKG / PKG was as an experiment trying to fix something else that wasn't working that turned out to be unrelated but I never changed it back to index.

**Comment by aluanhaddad** [comment]
The caveat to this is that the module augmentations have to map to whatever directory structure you ultimately choose

**Comment by andrewplummer** [comment]
This leads me back to my original issue, however. My directory structure is fixed (it already exists) and in node requiring the entire package would be `require('pkg')`, which would map to `import * as Pkg from 'pkg'` with types loaded from `/index.d.ts`. However, importing just a subset with `import * as Pkg from 'pkg/imbue/with-property'` (to use your example) results in superfluous types on `Pkg`, as this **also** loads the types from `/index.d.ts`.

**Comment by aluanhaddad** [comment]
Declare the primary module in core/index.d.ts, declare augmentations for this module in each corresponding subdirectory/index.d.ts. In the package main import each augmentation from its corresponding subdirectory/index.d.ts and additionally re-export core. Essentially you are there by mimicking the behavior of the corresponding requires. Import as needed.

**Comment by andrewplummer** [comment]
Hi, sorry for taking so long to respond to this. I've been attempting different approaches here while reading your comments and following along with the [declaration merging docs](https://www.typescriptlang.org/docs/handbook/declaration-merging.html) at the same time, but I just can't seem to get module augmentation working as documented. Since there's a lot of files, I finally decided to set up a repo [here](https://github.com/andrewplummer/typescript-test) to make it very clear what I'm trying to do. I feel like there is some core concept I'm missing that is preventing it from working right from the start....

**Comment by mhegazy** [comment]
`export = N ` makes the module an alias of the namespace, and it does not declare a namespace `N` under the module. so:

```ts
declare function pkg() : any;

declare namespace pkg {
  export function core_method(): any;
}

export = pkg;
```

your module `core` does not have a namespace `pkg`. it only has a function called `core_method`. 

An easy way to visualize this is to use vscode, and hit dot on your import `pkg`.


As for the solution to your issue, `pkg\foo\index.d.ts` should be :

```ts
import * as pkg from '../core';

declare module "../core" {

 // export namespace pkg {
    export function foo(): any;
    export namespace foo {
      export function method(): any;
    }
 // }

}
```

**Comment by andrewplummer** [comment]
Hmm... ok this seems to have worked for the namespace, but what about classes? I now have:

`pkg/core/index.ts`

```typescript
declare function pkg() : any;

declare namespace pkg {
  //function core_method(): any;

  export namespace FooNamespace {
    function method1(): any;
  }

  export class FooClass {
    method1(): any;
  }
}

export = pkg;

```
`pkg/foo/index.ts`

```typescript
import * as pkg from '../core';

declare module "../core" {

 // export namespace pkg {
    export namespace FooNamespace {
      export function method2(): any;
    }
    export class FooClass {
      method2(): any;
    }
 // }

}
```

...but this seems to just throw `Duplicate identifier 'FooClass'`...

**Comment by mhegazy** [comment]
Classes do not merge. at runtime, there is only one value. 

Classes and interfaces do though. so you can augment it using an interface.

You can find information about declaration merging at: http://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html.

**Comment by andrewplummer** [comment]
Thank you for following up with me so thoroughly on this! I got a bit busy and haven't had the chance to circle back around to this yet, but everything you mentioned helped point me in the right direction and I think it makes sense now!
