### ISSUE TITLE
Assignability checks in API

### ISSUE THREAD

**Issue by andy-hanson** [Microsoft/TypeScript#13502]
Could `isTypeAssignableTo` be exposed on the type-checker for use by API consumers? This would be helpful for analyzing code using type information. I would like to check `instanceof` expressions for assignability in a lint rule (palantir/tslint#2046).
`getBaseConstraintOfType` would also be useful for doing checks inside generic functions.
`isTypeAssignableTo` would also be useful for a `no-unnecessary-cast` rule.

**Comment by andy-hanson** [comment]
On that note, it would be useful to have some way of accessing control flow information too. https://github.com/palantir/tslint/pull/2038#discussion_r96126767

**Comment by danvk** [comment]
Related to #11728

I'd also like have this exposed for https://github.com/danvk/typings-checker/issues/15

**Comment by andy-hanson** [comment]
Would be resolved by #9943.

**Comment by mhegazy** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/9879
