### ISSUE TITLE
Visual Studio uses suddenly TypeScript 2.1 instead of 1.8 

### ISSUE THREAD

**Issue by 304NotModified** [Microsoft/TypeScript#13511]
I have updated Resharper (2016.3 -> 2016.3.1) and installed VS2017 RC1.

and suddenly VS2015 (update 3) is using Typescript 2.1 instead of 1.8.  I'm not sure which of the two broke my typescript build.

I have installed TypeScript 1.8 in VS2015:

![image](https://cloud.githubusercontent.com/assets/5808377/21980143/512782c2-dbe2-11e6-898f-4539e1b7fdaf.png)

If I run MSBUILD (v14) is see also 

> CompileTypeScript:
  C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.1\tsc.exe  --removeComments --module None

the typescript version in my csproj is 1.7 (`  <TypeScriptToolsVersion>1.7</TypeScriptToolsVersion>`)

**Expected behavior:**

VS2015 still runs Typescript 1.8

**Actual behavior:**

VS2015 uses runs Typescript 2.1, and therefor Typescript errors as my scripts aren't typescript 2 compatible. 

How do I force Typescript to 1.8? 

**tried** 
- reinstalling Typescript plugin for VS2015
- checking the PATH

**Comment by 304NotModified** [comment]
updated: fixed by updating `<TypeScriptToolsVersion>1.7</TypeScriptToolsVersion>`

to `<TypeScriptToolsVersion>1.8</TypeScriptToolsVersion>` (csproj file)

Any idea why it's choosing 2.1?

**Comment by aluanhaddad** [comment]
>Is VS2017 installing Typescript 2.1?

Yes it is. 1.8 is like a very old release.
