### ISSUE TITLE
Loop break exits wrong loop in some scenarios

### ISSUE THREAD

**Issue by Durza007** [Microsoft/TypeScript#13512]
**TypeScript Version:**  2.1.5

Break statements can in some scenarios break the wrong loop.

**Code**
The most basic code I could create that show the issue. Does not do anything meaningful but it was adapted from real code.
```ts
let array = [1, 2, 3];
for (let i = 0; i < array.length; i++) {
    let curr = array[i];
    for (var j = 0; j < array.length; j++) {
        break;
    }

    let func = () => curr;
}
```

**Expected behavior:**
It should compile to something like this:
```js
var array = [1, 2, 3];
var _loop_1 = function (i) {
    var curr = array[i];
    for (var j = 0; j < array.length; j++) {
        break;
    }
    var func = function () { return curr; };
};
for (var i = 0; i < array.length; i++) {
    var state_1 = _loop_1(i);
    if (state_1 === "break")
        break;
}

```

**Actual behavior:**
It compiles to this with default settings. The same output is generated in the Playground as well.
```js
var array = [1, 2, 3];
var _loop_1 = function (i) {
    var curr = array[i];
    for (var j = 0; j < array.length; j++) {
        return "break";
    }
    var func = function () { return curr; };
};
for (var i = 0; i < array.length; i++) {
    var state_1 = _loop_1(i);
    if (state_1 === "break")
        break;
}

```

**Comment by aluanhaddad** [comment]
> let array = [1, 2, 3];
> for (let i in array) {
>     let curr = array[i];
>     for (var j in array) {
>         break;
>     }
> 
>     let func = () => curr;
> }

This code is very odd. Perhaps it wasn't accounted for. Did you mean to use ```for ..of```?

**Comment by Durza007** [comment]
@aluanhaddad No, I don't want to share my real code so I created this example that just have the elements that trigger the bug. The real code is old JavaScript code that has been moved to TypeScript. That is why it does not take advantage of newer features in all places.

If you were to change `var j` to `let j` it would work as expected.

**Comment by aluanhaddad** [comment]
@Durza007 No I mean that in whatever version of JavaScript you are targeting, `for..in` is the wrong way to iterate over an array.

**Comment by Durza007** [comment]
@aluanhaddad Ok, I updated the example to use a proper loop.

**Comment by aluanhaddad** [comment]
In the nightly build I see this emit which looks correct.
```js
let array = [1, 2, 3];
for (let i = 0; i < array.length; i++) {
  let curr = array[i];
  for (var j = 0; j < array.length; j++) {
    break;
  }

  let func = () => curr;
}
```

**Comment by Durza007** [comment]
@aluanhaddad Yes, it seems to be working in the nightly for me as well.

**Comment by aluanhaddad** [comment]
@Durza007 I can't find the ticket but there was a relatively recent fix for block scoped bindings. Perhaps this was addressed there as well.
