### ISSUE TITLE
Red squiggly line under code using TSLib constructs

### ISSUE THREAD

**Issue by Strato** [Microsoft/TypeScript#13517]
**TypeScript Version:** 

2.1.4 or 2.1.5

**Code**

```ts
// Red squiggly under 'extends...'
class FooBar extends React.Component<{}, {}> { }
```

Also on other code using constructs relative to TSLib.

Tooltip error: "This syntax requires an imported helper but module 'tslib' cannot be found".

**Expected behavior:**

No red squiggly line.

**Actual behavior:**

Visual Studio 2015 Update 3 reports the line as faulty, when it's not. TypeScript transpilation (through Webpack) works fine.

I had the problem on TypeScript 2.1.4 and expected 2.1.5 to fix it. But it doesn't.

TSLib 1.5.0 is in my package.json dependencies section, and it's in node_modules. tsconfig has importHelpers = true. I DO NOT import the library in my code as the documentation doesn't mention it (no `import from 'tslib'`).

Since it's Visual Studio related I tried to add this line (not documented but makes sense) in my .csproj:

`<TypeScriptImportHelpers>True</TypeScriptImportHelpers>`

Visual Studio TypeScript compilation is disabled through .csproj as well.

I think it's "TypeScript for Visual Studio" tools related. Am I missing something?

**Comment by PavelPZ** [comment]
I have the same problem with Red squiggly line in VS.NET IDE. Other not mentioned observation:
- Visual Studio project compilation (without WebPack, just ```Build``` from VS.NET IDE) works fine with "Build succeeded" message.
- If I add 
```import * as tslib from 'tslib';```
to code, Red line disappears.
-------------------
Microsoft Visual Studio Community 2015, Version 14.0.25431.01 Update 3
TypeScript for Visual Studio 2015, ver. 2.1.5

**Comment by vladima** [comment]
fixed in internal repro

**Comment by rachelxi** [comment]
@vladima I'm getting the same problem with 2.1.5. Does it mean we can get the bug fixed in next release?

**Comment by marcusjwhelan** [comment]
@vladima was this ever resolved? I have the same issues today.

**Comment by mariuslundgard** [comment]
I having this issue in v2.4.2.
