### ISSUE TITLE
for...of iterator fail with `FormData.entries()`

### ISSUE THREAD

**Issue by KhaledElAnsari** [Microsoft/TypeScript#13515]
Hello,

I was trying to iterate through the [`FormData`](https://developer.mozilla.org/en-US/docs/Web/API/FormData) values with the [`.entries()`](https://developer.mozilla.org/en-US/docs/Web/API/FormData/entries) function using [`for...of`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Statements/for...of) iterator and it failed! I tried to do the same thing with other transpiler and it worked!

**TypeScript Version:**  2.0.10
**Browser Used:** Chrome 55.0.2883.87, FireFox 50.1.0
**Code**

```ts
// same simple MDN example
let formData = new FormData();
formData.append('key1', 'value1');
formData.append('key2', 'value2');
for(let pair of formData.entries()) {
   console.log(pair[0] + ": ", pair[1]); 
}
```

**Expected behavior:**

Nothing was printed in the console

**Actual behavior:**

```
key1: value1
key2: value2
```

**Comment by hzoo** [comment]
I didn't mean that this needed to be a new issue, in https://github.com/Microsoft/TypeScript/issues/3164#issuecomment-104443321

@mhegazy already explained why TypeScript isn't supporting it unless you are compiling to ES6, otherwise you can use TS -> Babel

**Comment by KhaledElAnsari** [comment]
@hzoo did't see that :\ but it explains a lot! thanks

**Comment by aluanhaddad** [comment]
This is no longer the case. https://github.com/Microsoft/TypeScript/pull/12346

**Comment by hzoo** [comment]
Oh right 👍 forgot about that.

**Comment by arciisine** [comment]
I'm experiencing the same behavior, running in node 7.  My work around was to wrap the `.entries()` call with `Array.from(...)`.  I'm inclined to believe it's a Node issue.

**Comment by aluanhaddad** [comment]
@arciisine This feature has not yet landed for `--target` < es2015
Since you are on Node 7. You can use `--target` >= es2015 and it will just work.

**Comment by arciisine** [comment]
I am using the target es2015 and I had the same issue that the loop was not iterating.  I had to add `Array.from` to get the loop to iterate properly.

**Comment by blakeembrey** [comment]
@arciisine What's the error you're getting? There's no `FormData` object natively in node.

**Comment by arciisine** [comment]
The error was wrt to iterating on `map.entries()`, and the iteration being skipped unless I wrapped `map.entries()` in `Array.from(...)`.  I'm assuming it is something to do with the Iterator construct vs having an array.

**Comment by ollwenjones** [comment]
Just ran across this issue with `Map.entries()` (and `.values()` and `.keys()`) Why doesn't TS follow the spec? Or is MDN wrong about the `for...of` loop working on Map?
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map

**Comment by mhegazy** [comment]
Should be fixed by https://github.com/Microsoft/TypeScript/pull/14859 in TS 2.3.

if you are using `--lib` option in your tsconfig.json make sure you add `dom.iterable`
