### ISSUE TITLE
No function type checking

### ISSUE THREAD

**Issue by katyo** [Microsoft/TypeScript#13529]
**TypeScript Version:**  2.1.5

**Code**

```ts
export type ModFn = (name: string) => void;

/* OR
export interface ModFn {
  (name: string): void;
}
*/

export default function(): ModFn {
  return function(): number {
    return 0;
  };
}
```

**Expected behavior:**

```
error TS2322: Type '() => number' is not assignable to type 'ModFn'.
```

**Actual behavior:**

No errors.

**Comment by gcnew** [comment]
See https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-functions-with-fewer-parameters-assignable-to-functions-that-take-more-parameters and https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-functions-returning-non-void-assignable-to-function-returning-void.

**Comment by katyo** [comment]
Thanks for explanation,

It may looks strange from point of view C programmer (and Haskell programmer too), but I think this is correct behavior.
