### ISSUE TITLE
string literal completion for `<K extends keyof Foo>` does not work (reopen)

### ISSUE THREAD

**Issue by wonderful-panda** [microsoft/TypeScript#13527]
#12536 is still not fixed.

When the type has two or more members, it works.
But when the type has only one member, it does not work.

**TypeScript Version:**  nightly (2.2.0-dev.20170116)

**Code**
```ts
interface Foo { foo: string; }
interface FooBar { foo: string; bar: string; }
function ok<K extends keyof FooBar>(a: K) {};
function ng<K extends keyof Foo>(a: K) {};

ok("/*position 1*/");
ng("/*position 2*/");
```

**Expected behavior:**
tsserver returns `foo` as completion candidate for position 2.

**Actual behavior:**
tsserver returns no candidate for position 2.

**Comment by RyanCavanaugh** [comment]
This has been fixed now
