### ISSUE TITLE
Access to constructor variables in context of a abstract class

### ISSUE THREAD

**Issue by lexon0011** [Microsoft/TypeScript#13532]
I try to write the following simple code:

```
abstract class Department {
    constructor() {
        this.printMeeting();
    }
    abstract printMeeting(): void; // is implemented in derived classes
}

class AccountingDepartment extends Department {
    constructor(public name: string) {
        super(); 
    }
    printMeeting(): void {        
        console.log(this.name);
    }
}
var sampleInstance = new AccountingDepartment("Sales Meeting");
```

As you can see, I tried to access in the methode `printMeeting()` to the constructor parameter `name`. If I call the method from the contructor of the base class, the variable `name` would be undefined. 

Is there a way to access to the constructor variables, also when the method would be called from the base class/constructor?

Thanks!

**Comment by RyanCavanaugh** [comment]
Don't call virtual functions from constructors (in C#, C++, or JS): http://stackoverflow.com/questions/962132/calling-virtual-functions-inside-constructors

See also #13525 and many other initialization order questions linked from there.
