### ISSUE TITLE
Type guards don't work with derived classes with no extra members

### ISSUE THREAD

**Issue by markboyall** [Microsoft/TypeScript#13533]
**TypeScript Version:**  2.1.5

```ts
class TypeTagged { type: string; }
class X extends TypeTagged { }
class Y extends TypeTagged { state2: boolean }

function typeguard<T>(obj: any): obj is T { return true; }

function f(obj: TypeTagged) {
  if (typeguard<X>(obj)) {
    return true;
  }

  if (typeguard<Y>(obj)) {
    return obj.state2;
  }
  return false;
}
```

**Expected behavior:**
Code compiles

**Actual behavior:**
Code fails to compile, as obj is inferred as never in the second branch.

Even if the distinct classes themselves have no semantic distinction, the discriminator used to discriminate them does. They can't be assumed to be the same in the case of a typeguard just because they are structurally the same.

**Comment by mhegazy** [comment]
This is an expected behavior given the structural nature of the type system. Reversing the order of the check should work.
