### ISSUE TITLE
Illegal constructor in JS

### ISSUE THREAD

**Issue by sebab97** [Microsoft/TypeScript#13531]
TypeScript Version:  2.1.4

Code

```
module graphics {

	export class Texture extends HTMLImageElement {

		constructor(src: string) {
			super();
			this.src = src;
		}

	}

}
```

```
/* another file */
var texture: Texture = new graphics.Texture('png/0.png');
```

`

```
/* tsconfig.json */
{
	"compilerOptions": {
		"outFile": "../public/js/app.js",
		"target": "es5"
	}
}
```

Expected behavior: Execute in browser without errors.

Actual behavior: TypeError: Illegal constructor.

**Comment by mhegazy** [comment]
Please find more details in [MDN](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Custom_Elements/Custom_Elements_with_Classes) on how custom elements work. 

Also see https://github.com/Microsoft/TypeScript/issues/574#issuecomment-231683089
