### ISSUE TITLE
using non-recursive walks over the AST

### ISSUE THREAD

**Issue by rkirov** [microsoft/TypeScript#13549]
**TypeScript Version:**  nightly (2.2.0-dev.201xxxxx)

**Code**

```ts
'' + (repeats 2000 times) + '';
```

**Expected behavior:**
Accept as valid TS.

**Actual behavior:**
`RangeError: Maximum call stack size exceeded`

Not sure if this is feasible (so feel free to close), but we did reach this error during some code generation from html to ts. We resolved it by using `['', '', ...., ''].join()` (could have also added some parens), which generates a flat AST, vs the deep AST coming from multiple '+' expressions.

//cc @mprobst, @evmar, @calebegg

**Comment by RyanCavanaugh** [comment]
Fixed (hopefully?) by #21754
