### ISSUE TITLE
Interface doesn't match default params

### ISSUE THREAD

**Issue by donaldpipowitch** [microsoft/TypeScript#13545]
**TypeScript Version:**  Playground (2.1.1?)

**Code**

```ts
interface Props {
  type: 'error' | 'warning';
}

const Bar = ({ type2 = 'error' }: Props) => `This is my type: ${type2}`;
                   ^----- this is an error

const Foo = ({ type = 'error2' }: Props) => `This is my type: ${type}`;
                            ^----- this is no error :(
```

**Expected behavior:**

It should not be possible to set `type` to `error2`, just like it is not possible to use `type2` instead of `type`.

**Actual behavior:**

It is possible to set `type` to `error2`. Hovering over `type` currently shows `var type = "error" | "warning" | "error2"`.

**Comment by RyanCavanaugh** [comment]
This has been fixed
