### ISSUE TITLE
Properties P in generic type U that extends type T should allow use of type T[P]

### ISSUE THREAD

**Issue by DmitryEfimenko** [Microsoft/TypeScript#13547]
**TypeScript Version:**  2.1.4 / Playground

**Code**

```ts
type shouldCompile<T, U extends T> = {
    [P in keyof U]: T[P];
}
```

**Expected behavior:**
Should compile because U extends T, thus has the same properties

**Actual behavior:**
Does not compile.

**Additional comments**
I think I saw something similar beeing discussed in one of the previous issues, but I could not find it. Sorry if this is a duplicate.

The type is kept simple for the purposes of demonstration of the issue. It's unlikely it'd be created like that. In a more real situation `U` would be extending a `Partial<T>` or some other variation of `T`

Also, the title of this issue proves once again that naming things is hard!

**Comment by RyanCavanaugh** [comment]
`U` has a superset of the properties of `T`, so it's not guaranteed that something in `U` is in `T` (concretely if `T` is `{ a }` then `U` could be `{ a, b }` and there is no `b` in `T`) . The reverse declaration works:
```ts
type shouldCompile<T, U extends T> = {
    [P in keyof T]: U[P];
}
```

**Comment by DmitryEfimenko** [comment]
You are correct. For the real world scenario, I was thinking about `U extends Partial<T>`, but even in that case, it's the same situation as you described.

Is there anything that would specify that `U` can only have props of `T`?
Something like `U subset T`

**Comment by NN---** [comment]
If there was something which produced only common properties between two types.
Such as  {a:number;b:number;} @ {b:number;} = {b:number;} it would be easy to achieve:

```typescript
type shouldCompile<T, U extends (T @ U)> = {
    [P in keyof U]: T[P];
}
```

**Comment by DmitryEfimenko** [comment]
I think the problem is with the word `extends`. The moment it's used (in example `U extends T`), it's assumed that U is a superset of T, and we fall back into the problem described by @RyanCavanaugh .

That's why I think there should be a whole separate keyword. For example, `subset`

**Comment by DmitryEfimenko** [comment]
hey, @mhegazy, I understand that the word `extends` works as intended, but that does not solve the underlying issue I had. Is there anything in the works, like the word `subset` I mentioned above that would allow the scenario I was talking about in the first comment?

**Comment by mhegazy** [comment]
As described by @RyanCavanaugh in https://github.com/Microsoft/TypeScript/issues/13547#issuecomment-273325295, it is not guaranteed that `T` will have the properties in `U`. if you can elaborate on the original scenario you are trying to achieve we can think of solution.

**Comment by DmitryEfimenko** [comment]
I'm trying to have TypeScript recognize the return type of the function given its parameters.
For example, a function that would query database table of a known type, but only return selected columns:
```typescript
interface IPerson { id: string; name: string; age: number }
let person = db.getAll<IPerson>({ id: 1, name: 1 });
// typescript should recognize the type of `person` is `{ id: string; name: string }` - without age property
```
Here is my [best shot at this example in TypeScript playground](http://www.typescriptlang.org/play/#src=interface%20Person%20%7B%0D%0A%20%20%20%20id%3A%20number%3B%0D%0A%20%20%20%20firstName%3A%20string%3B%0D%0A%20%20%20%20lastName%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Aclass%20Db%3CT%3E%20%7B%0D%0A%20%20%20%20getAll%3C%0D%0A%20%20%20%20%20%20%20%20C%20extends%20MongoColSelector%3CT%3E%2C%0D%0A%20%20%20%20%20%20%20%20R%20extends%20MergePropsAndType%3CC%2C%20T%3E%0D%0A%20%20%20%20%3E(cols%3A%20C)%3A%20R%20%7B%0D%0A%20%20%20%20%20%20%20%20let%20p%3A%20R%20%3D%20%3Cany%3E%7B%7D%3B%0D%0A%20%20%20%20%20%20%20%20return%20p%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Alet%20db%20%3D%20new%20Db%3CPerson%3E()%3B%0D%0Alet%20p%20%3D%20db.getAll(%7B%20id%3A%201%2C%20firstName%3A%201%20%7D)%3B%0D%0A%0D%0A%2F%2F%20should%20not%20have%20compile%20error%3B%0D%0Ap.id%20%3D%201%3B%0D%0Ap.firstName%20%3D%20'asd'%3B%0D%0A%0D%0A%2F%2F%20should%20have%20compile%20error%3B%0D%0Ap.id%20%3D%20'2'%3B%0D%0Ap.firstName%20%3D%201%3B%0D%0Ap.lastName%0D%0A%0D%0Atype%20MongoColSelector%3CT%3E%20%3D%20%7B%0D%0A%20%20%5BP%20in%20keyof%20T%5D%3F%3A%201%20%7C%20-1%3B%0D%0A%7D%3B%0D%0A%0D%0Atype%20MergePropsAndType%3CC%2C%20T%20extends%20PropsOfType%3CC%2C%20any%3E%3E%20%3D%20%7B%0D%0A%20%20%20%20%5BP%20in%20keyof%20C%5D%3A%20T%5BP%5D%0D%0A%7D%0D%0A%0D%0Atype%20PropsOfType%3CT%2C%20Type%3E%20%3D%20%7B%0D%0A%20%20%20%20%5Bp%20in%20keyof%20T%5D%3A%20Type%3B%0D%0A%7D).
Interestingly enough, typescript figures out types properly but has compile error.

**Comment by mhegazy** [comment]
I am assuming the object literal has `number` type for properties `id` and `name` intentionally.. you could use `Record` to infer the keys provided, call it `K`, then use `Record` again to get the types of `IPerson` for properties with the keys `K` specified:

```ts
getPerson<K extends keyof IPerson>(obj: Record<K, number>): Record<K, IPerson>;
```

**Comment by DmitryEfimenko** [comment]
yes, type for properties of `id` and `name` in the `params` object is intentionally a number. This is similar to MongoDb's query interface.

returning `Record<K, IPerson>` isn't right. It would be an object of type.
```ts
{ id: IPerson; name: IPerson}
```
instead of what's needed:
```ts
{ id: string; name: string }
```

**Comment by mhegazy** [comment]
Sorry. In my brain I was thinking of `Pick` but wrote `Record` :D..

```ts
declare function getPerson<K extends keyof IPerson>(obj: Record<K, number>): Pick<IPerson, K>;
```

**Comment by DmitryEfimenko** [comment]
this is fantastic! Thanks for the help! That alone made my day!
