### ISSUE TITLE
[Salsa] Expected completion list for "this." to contain global scope items for JS files

### ISSUE THREAD

**Issue by jramsay** [Microsoft/TypeScript#13551]
TypeScript Version:  nightly 

Expected completion list for "this." to contain global scope items for JS files

![this](https://cloud.githubusercontent.com/assets/8161247/22045920/2ac921da-dcd2-11e6-9611-188dcbe6dd83.JPG)

**Expected behavior:**

Completion list should contain "window" and all other items that appear in the global scope.  This was the previous model in the JSLS. 

![global](https://cloud.githubusercontent.com/assets/8161247/22046031/dda92d86-dcd2-11e6-9626-2508cc857a3a.JPG)

**Actual behavior:**
No global scope items appear in the completion list

**Comment by mhegazy** [comment]
This is working as designed. Getting this type correctelly is a tricky task.
