### ISSUE TITLE
Spread operator should work with `object` type

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#13556]
cc @HerringtonDarkholme 

**TypeScript Version:**  master

**Code**

```ts
var o = { ...<object>{} };
```

**Expected behavior:**

ok

**Actual behavior:**

index.ts(1,10): error TS2698: Spread types may only be created from object types.

**Comment by HerringtonDarkholme** [comment]
Good Catch! Will fix it soon!

**Comment by falsandtru** [comment]
Thanks!
