### ISSUE TITLE
Spread operator should work with generic types

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#13557]
**TypeScript Version:**  master

**Code**

```ts
function f<a extends Object>() {
	return {...<a>{}};
}
function g<a extends object>() {
	return {...<a>{}};
}

```

**Expected behavior:**

ok

**Actual behavior:**

index.ts(2,10): error TS2698: Spread types may only be created from object types.
index.ts(5,10): error TS2698: Spread types may only be created from object types.

**Comment by HerringtonDarkholme** [comment]
Another example, it's quite hard for TypeScript to prove a type constraint is spreadable given structural typing

```ts
class NonPrimitive {
    private cannotBePrimitiveBrand
}
function t<T extends NonPrimitive>(a: T, b: NonPrimitive) {
    var c = { ...a }
    var d = { ...b }
}
```

https://github.com/Microsoft/TypeScript/issues/2103#issuecomment-219553288

**Comment by billba** [comment]
Another example: 

```typescript
interface Foo {
    foo: string;
}

const addBar = <F extends Foo>(input: F) => ({
    ... input,
    bar: 5
});
```

Throws `error TS2698: Spread types may only be created from object types.` on `...input,`

**Comment by mhegazy** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/10727. Fixed by https://github.com/Microsoft/TypeScript/pull/13288

**Comment by billba** [comment]
This is still happening in the current build.

**Comment by mhegazy** [comment]
yes. #13288 is not merged yet. we do not have an ETA at the moment.

**Comment by billba** [comment]
Aha, thanks.

**Comment by LKay** [comment]
When it will be fixed finally? The problem persists and it's breaking code all over the place!

**Comment by massimonewsuk** [comment]
Is there a milestone or version that we can expect this to be fixed in?

**Comment by nblavoie** [comment]
Count me in !

**Comment by mcamou** [comment]
Any news on when/whether #13288 will be merged? This bug has been open for over a year now.

**Comment by ivansky** [comment]
@mhegazy 
It's not a duplicate! I am interested in fixing too. 
Could you remove label and reopen the issue?

**Comment by RyanCavanaugh** [comment]
Please read https://github.com/Microsoft/TypeScript/pull/13288#issuecomment-412230721
