### ISSUE TITLE
[Suggestion] Allow use of const enum values in computed properties in type literals and interfaces

### ISSUE THREAD

**Issue by PyroVortex** [Microsoft/TypeScript#13550]
Considering how `const enum` operates at compile-time, it seems odd that the following is not valid:
```ts
const enum Ids {
    alpha = 1
}

interface Foo {
    [Ids.alpha]: string
}
```
when it should be precisely equivalent to:
```ts
interface Foo {
    [1]: string
}
```
which compiles just fine.

### Proposal
Allow `const enum` values to be used in computed property specifiers in interface declarations and type literals, just as well-known symbols are today.

**Comment by RyanCavanaugh** [comment]
#10770 / #5579

**Comment by PyroVortex** [comment]
Ah, I missed #10770 because I was filtering on currently open issues, and then #5579 didn't reference const enums in the description.
