### ISSUE TITLE
Microsoft.TypeScript.targets(164,5): Error MSB4018: The "FindConfigFiles" task failed unexpectedly.

### ISSUE THREAD

**Issue by JoelAdamWeiss** [Microsoft/TypeScript#13564]
**TypeScript Version:**  2.1.5

******************************************************************************
Starting task: Build solution **/*.sln
******************************************************************************
"C:\Program Files (x86)\MSBuild\14.0\bin\amd64\msbuild.exe" "C:\TfsData\Build\_work\34\s\PfClubServiceDNC.sln" /nologo /nr:false /dl:CentralLogger,"C:\TfsBuildAgents\VsoBuildAgent\tasks\VSBuild\1.0.37\ps_modules\MSBuildHelpers\Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll"*ForwardingLogger,"C:\TfsBuildAgents\VsoBuildAgent\tasks\VSBuild\1.0.37\ps_modules\MSBuildHelpers\Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll" /verbosity:n /p:platform="any cpu" /p:configuration="release" /p:VisualStudioVersion="14.0"
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 1/18/2017 7:57:21 AM.
Project "C:\TfsData\Build\_work\34\s\PfClubServiceDNC.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "release|any cpu".
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\Microsoft.TypeScript.targets(164,5): Error MSB4018: The "FindConfigFiles" task failed unexpectedly.
System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetDirectoryName(String path)
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.EnumerateFiles(String path)
   at TypeScript.Tasks.FileHelpers.RecursiveGatherFiles(String directoryPath, String projectPath, Func`2 filter)

We first encountered this problem yesterday.  I saw post #9435, we were using version 1.8.x
We upgraded to version 2.1.5, but the problem continued, just moved down a few lines.

This morning I tried creating a new Web App in VS 2015 r3, hoping to narrow down where the issue was coming from, but we got the same error.

Any assistance would be appreciated.  We did turn on verbose logging and I can send the log to someone if necessary.  

Thanks in advance for any and all assistance.

**Comment by mhegazy** [comment]
The findConfigFiles is searching your project directory for a tsconfig.json file, but then running into long file names. Do you know what folders with nested content do you have under your project root?

**Comment by JoelAdamWeiss** [comment]
I got it taken care of.

 

Thanks!

**Comment by fabianPas** [comment]
What did you do to take care of it? I'm running into the same problem but have no idea on how to fix it.

**Comment by minestarks** [comment]
@fabianPas Is the full path to your project directory longer than 248 characters?

**Comment by Hoshinokoe** [comment]
I have the same problem after windows update. E.g. nothing changed inside project, I am unable to build it, but yesterday everything was fine. Project directory path is no so long to exceed 260 chars.

I installed the latest version of TypeScript - 2.3.3.

**Comment by minestarks** [comment]
@Hoshinokoe you get the same error about long paths? 

Even if the project directory isn't too long, if you have any paths _within_ the project directory that exceed 260 characters (e.g. this happens a lot with ```node_modules``` directories) you might run into this issue. I'll look into how we can mitigate this for TypeScript (we really shouldn't be searching for tsconfig.json files that deep). But unfortunately, even then, until MSBuild fully supports long paths (see https://github.com/Microsoft/msbuild/issues/53) you are likely to run into issues in other parts of the build.
