### ISSUE TITLE
Variables from different modules seem to be considered to be in the same scope

### ISSUE THREAD

**Issue by rjmunro** [Microsoft/TypeScript#13561]
**TypeScript Version:**  2.1.5

**Code**
(Copied from [this gist](https://gist.github.com/rjmunro/428ec644b6e53a499ca3a5ba8de2edc7))

index.ts:
```ts
var a = require('./module1');
var b = require('./module2');

// import a from './module1';
// import b from './module2';

console.log('a',a);
console.log('b',b);
```
module1.ts:
```ts
let foo = 'hello1';

module.exports = foo;
```
 module2.ts:
```ts
let foo = 'hello2';

module.exports = foo;
```
 package.json:
```ts
{
  "dependencies": {
    "@types/node": "^7.0.0",
    "typescript": "^2.1.5"
  }
}
```
 tsconfig.json:
```ts
{
  "compilerOptions": {
    "outDir": "build"
  },
  "exclude": [
    "node_modules",
    "build"
  ]
}
```

**Expected behaviour:**
I would expect the above to compile without errors.

**Actual behaviour:**
After putting the above files in a folder and running `npm install`

```
$ node_modules/.bin/tsc
module1.ts(1,5): error TS2451: Cannot redeclare block-scoped variable 'foo'.
module2.ts(1,5): error TS2451: Cannot redeclare block-scoped variable 'foo'.
$ node build/index.js 
a hello1
b hello2
```

So the compiler throws an error but emits working code anyway.

If you comment out one of the `let foo = ..` lines, typescript's warnings go away, but the code it emits doesn't run. (I've commented line 1 of module2.ts below):

```
$ node_modules/.bin/tsc
$ node build/index.js 
/Users/rjmunro/personal_projects/tstest/build/module2.js:2
module.exports = foo;
                 ^

ReferenceError: foo is not defined
    at Object.<anonymous> (/Users/rjmunro/personal_projects/tstest/build/module2.js:2:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/rjmunro/personal_projects/tstest/build/index.js:2:9)
    at Module._compile (module.js:571:32)
```

You can fix the problem by changing the export syntax from `module.exports = foo;` to `export default foo;`, but I would expect the legacy syntax to work.

**Comment by RyanCavanaugh** [comment]
TypeScript doesn't info CommonJS modules from normal property assignments or `var`s.

Use `import x = require('x')` instead of `var x = require('x')` in consumer files, and use `export = foo` instead of `module.exports = foo` in the providing files, and this will all work as expected

**Comment by RyanCavanaugh** [comment]
Alternatively you can just rename these to `.js` and compile with `--allowJs` (CJS modules are inferred in .js files)

**Comment by rjmunro** [comment]
Why is it telling me that a variable is already defined when it isn't?

Are there circumstances where this behaviour is useful?

Is it assuming that I am going to concatenate the files together or something?

**Comment by RyanCavanaugh** [comment]
> Why is it telling me that a variable is already defined when it isn't?

Files which don't have top-level `import` or `export` declarations are assumed to be global code. Under this assumption, you do have two different `foo` declarations in the same scope.

> Are there circumstances where this behaviour is useful?

People do indeed write code that executes in the global scope :smile:

> Is it assuming that I am going to concatenate the files together or something?

Concatenated, or ran in the same HTML page via multiple script blocks, or otherwise ran together, yes

**Comment by rjmunro** [comment]
Is this affected by the `module` and / or `moduleResolution` options in `tsconfig.json`?

**Comment by ggarek** [comment]
This behaviour also bugged me for a while. I tried to use typescript for a nodejs project (a CLI). Basically i need to compile `src/**/*.ts` to `lib/`, but was getting  `Cannot redeclare block-scoped variable` (e.g. for base node modules like 'fs', 'path' etc).

**Switching to import/export syntax** helped. But it was not obvious at all. Imo, if there were a flag to treat all files during transpilation as in global scope, it would be much clearer compared to current implicit global scope assumption behaviour.

**Comment by tabudev** [comment]
I am using TypeScript ver. 2.5.3 and encountered the same issue. Defining separate namespaces per module helped. Please, see https://www.typescriptlang.org/docs/handbook/namespaces.html

**Comment by peterjwest** [comment]
It seems like a very weird default to treat files without import/export as global, since TypeScript supports `require()`, there is no reason to believe that a file without import/export _must_ be global.

And the presence of `require()` implies the code will run similarly to node, with separate module namespaces.

Surely the edge case of "treating modules as global scripts" should be a compiler option, and not switch based on pattern matching.
