### ISSUE TITLE
After adding tsconfig.json, .ts doestn't compile anymore [VS 2015.3]

### ISSUE THREAD

**Issue by dehghani-mehdi** [Microsoft/TypeScript#13562]
Hi,

I'm using latest version of `TypeScript`, `VS 2015.3` & `Windows 10 x64`.
When I add `tsconfig.json` to my project (_web application, using web-form_), `.ts` file doesn't compile anymore.

I added `tsconfig.json` in root of my project, also didn't change any options (_vs add some default config to it_), I moved config file to the folder that contains `.ts` file, but no success.

p.s: When I using `command-line` with `tsc --p tsconfig.json` command, everything works just fine.

Thank you!
-mehdi

**Comment by mhegazy** [comment]
Please share your full build log with 'MSBuild /verbosity: diagnostic' or a project that reproduces the issue.

**Comment by dehghani-mehdi** [comment]
@mhegazy I figured out you added similar answer to almost all reported bugs, I think I added enough info in my post. below you can see how you can get my project :)

- Open Visual Studio 2015.3
- Hit `Ctrl+Shift+N`
- Select `C# - Web - ASP.NET Web Application (.Net Framework)`, then form `ASP.NET 4.5 Templates`, select `Empty`
- Try to add new `typescript` file
- Add some JS code and hit `Ctrl+S`, you can see, the compiled `JS file` will show up.
- Add `tsconfig.jon`, make some change to `JS file`, hit `Ctrl+S`, you can see, the compiled JS file won't update.

If you can get compiled file when `tsconfig.json` file is exists, please share your project with me.

**Comment by mhegazy** [comment]
Thanks for the info. Your original report did not have any mention to Compile-on-Save. you only mentioned build. To enable compile-on-save, set `"compileOnSave": true`  in your tsconfig.json file. Please find documentation at http://www.typescriptlang.org/docs/handbook/tsconfig-json.html#compileonsave

Given the volume of issues we get everyday, and the finite nature of time, we would appreciate it if you give us enough details to reproduce issues locally.

Here is my project as requested:
[WebApplication11.zip](https://github.com/Microsoft/TypeScript/files/733137/WebApplication11.zip)

**Comment by dehghani-mehdi** [comment]
Thank you for your answer, seems like I reported wrong issue. with `"compileOnSave": true` everything works, but I need to add `outDir` option too. right now my `tsconfig.json` has following content:

    {
        "compilerOptions": {
            "noImplicitAny": false,
           "noEmitOnError": true,
           "removeComments": false,
           "sourceMap": true,
           "target": "es5",
           "outDir": "../js/modules/"
        },
        "compileOnSave": true,
        "exclude": [
            "node_modules",
            "wwwroot"
        ]
    }

If I remove `"outDir": "../js/modules/"` everything works.

BTW as I said when I using command-line with `tsc --p tsconfig.json` _including `"outDir": "../js/modules/"`_ command, everything works just fine.

![111](https://cloud.githubusercontent.com/assets/9152330/22394950/0121af4e-e544-11e6-96b4-5792515df776.png)

**Comment by mhegazy** [comment]
not sure i follow the issue now. so with `outDir` there is no output generated? or is it generated in the wrong place?

**Comment by dehghani-mehdi** [comment]
@mhegazy there is no output generated, but (_as I mentioned_) using command-line files will be generated successfully.

**Comment by mhegazy** [comment]
does setting `"rootDir": "./"` helps?

**Comment by dehghani-mehdi** [comment]
Works like a charm ! Why I didn't that before !! 
Thank you!
