### ISSUE TITLE
Generic constraint on returned function should generate type mismatch, but doesn't

### ISSUE THREAD

**Issue by MadaraUchiha** [microsoft/TypeScript#13567]
**TypeScript Version:**  2.1.5

**Code**

The following is closest to the actual code we used to discover the bug.

[Playground link](http://www.typescriptlang.org/play/index.html#src=interface%20ComponentClass%3CP%3E%20%7B%0D%0A%20%20%20%20new%20()%3A%20Component%3CP%2C%20%7B%7D%3E%3B%0D%0A%7D%0D%0A%0D%0Aclass%20Component%3CP%2C%20S%3E%20%7B%20%7D%0D%0A%0D%0Afunction%20decorator(someArg%3A%20string)%3A%20%3CP%2C%20Comp%20extends%20ComponentClass%3CP%3E%3E%20(DecoratedComponent%3A%20Comp)%20%3D%3E%20Comp%20%7B%0D%0A%20%20%20%20return%20function%20%3CProps%3E(DecoratedComponent%3A%20ComponentClass%3CProps%3E)%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20class%20Inner%20extends%20Component%3CProps%2C%20void%3E%20%7B%7D%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Afunction%20badDecorator(someArg%3A%20string)%3A%20%3CT%3E%20(DecoratedComponent%3A%20T)%20%3D%3E%20T%20%7B%0D%0A%20%20%20%20return%20function%20%3CProps%3E(DecoratedComponent%3A%20ComponentClass%3CProps%3E)%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20class%20Inner%20extends%20Number%20%7B%20%7D%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0A%40decorator('foo')%20%2F%2F%20This%20infers%20Props%20correctly%0D%0Aclass%20FooComponent%20extends%20Component%3C%7B%20some%3A%20string%2C%20props%3A%20number%20%7D%2C%20void%3E%20%7B%20%7D%0D%0A%0D%0A%40badDecorator('foo')%20%2F%2F%20Bullshit%2C%20T%20cannot%20be%20both%20typeof%20OtherComponent%20and%20T%20extends%20Number%0D%0Aclass%20OtherComponent%20extends%20Component%3C%7B%20some%3A%20string%2C%20props%3A%20number%20%7D%2C%20void%3E%20%7B%20%7D%0D%0A%0D%0A%2F%2F%20foo%20is%20typeof%20OtherComponent%2C%20but%20it's%20actually%20typeof%20Inner%0D%0Avar%20foo%20%3D%20badDecorator('foo')(OtherComponent))
```ts
// import {Component, ComponentClass} from 'react'
interface ComponentClass<P> {
    new (): Component<P, {}>;
}

class Component<P, S> { }

function decorator(someArg: string): <P, Comp extends ComponentClass<P>> (DecoratedComponent: Comp) => Comp {
    return function <Props>(DecoratedComponent: ComponentClass<Props>) {
        return class Inner extends Component<Props, void> {}
    }
}

function badDecorator(someArg: string): <T> (DecoratedComponent: T) => T {
    return function <Props>(DecoratedComponent: ComponentClass<Props>) {
        return class Inner extends Number { }
    }
}

@decorator('foo') // This infers Props correctly
class FooComponent extends Component<{ some: string, props: number }, void> { }

@badDecorator('foo') // Bullshit, T cannot be both typeof OtherComponent and T extends Number
class OtherComponent extends Component<{ some: string, props: number }, void> { }

// foo is typeof OtherComponent, but it's actually typeof Inner
var foo = badDecorator('foo')(OtherComponent)
```

An even simpler example is as follows:

```ts
function foo(): <T> (arg: T) => T {
  return function(arg) {
    return 42;
  }
}

var x = foo()('string'); // typeof x = string, wrong, x is a number.
console.log(x); // 42
```

**Expected behavior:**
A compiler error of some sort:
- Either don't let me return `42` because it can't guarantee that it matches any T (if it were `T extends number`, it would have been fine)
- Or don't let me pass `'string'` because it can't guarantee that the it will match the return type of `T extends number`.

**Actual behavior:**
Compiler doesn't complain.

cc @benjamingr @mosho1 @awalgarg

**Comment by MadaraUchiha** [comment]
cc @linkgoron

**Comment by RyanCavanaugh** [comment]
This is an error now
