### ISSUE TITLE
error TS5042: Option 'project' cannot be mixed with source files on a command line.

### ISSUE THREAD

**Issue by ORESoftware** [Microsoft/TypeScript#13575]
On latest version of TS - 

I am calling tsc like so:

```js 
 shell.stdin.write('tsc --jsx react --project tsconfig-fe.json ' + path + '\n');
```

I get an error saying:

`error TS5042: Option 'project' cannot be mixed with source files on a command line.`

this seems like an unncessary error. I would really like to be able to specify which tsconfig file to use ( I use one for backend and a different one for frontend ).

Is there any workaround for this besides taking all the settings from my tsconfig and putting them on the command line?

**Comment by LucienLee** [comment]
I would like check my staged files with path resolution, which I need to pass source files and paths from cli. However, the `paths` options only can assign from `tsconfig.json` instead of passing from cli. Hence, I really need mix source files and project options.

**Comment by RyanCavanaugh** [comment]
Tracking at #12958
