### ISSUE TITLE
Partial<Foo> does not match {[key: string]: value} with strictNullChecks

### ISSUE THREAD

**Issue by danvk** [Microsoft/TypeScript#13577]
**TypeScript Version:**  2.1.1

**Code**

```ts
interface SearchParams {
    first: string;
    last: string;
}

function getAPI(url: string, params: { [key: string]: string } = {}) {
    // ...
}

function search(params: Partial<SearchParams>) {
    return getAPI('/search', params);  // error
}
```

I'm using `strictNullChecks`. This code checks fine without it.

**Expected behavior:**

This code should be valid: params is always a subtype of `{ [key: string]: string }`.

**Actual behavior:**

I get the following error:

```
Argument of type 'Partial<SearchParams>' is not assignable to parameter of type '{ [key: string]: string; } | undefined'.
  Type 'Partial<SearchParams>' is not assignable to type '{ [key: string]: string; }'.
    Property 'first' is incompatible with index signature.
      Type 'string | undefined' is not assignable to type 'string'.
        Type 'undefined' is not assignable to type 'string'.
```

**Comment by mhegazy** [comment]
With `--strictNullChecks` off, all types have `undefined` in their domain. When `--strictNullChecks` is on, this is not the case.

Any property accessed of the type `{ [key: string]: string }`  is of type `string`. however `Partial` allows for `undefined`. thus the two types are not compatible.  

Define your type as:

```ts
function getAPI(url: string, params: { [key: string]: string | undefined } = {}) {
    // ...
}
```

**Comment by danvk** [comment]
So the issue is essentially that `{x: undefined}` and `{}` are different types, and that `Partial` is more along the lines of the former? Makes sense.
