### ISSUE TITLE
Dynamically created classes (such as higher order components) cannot be used as types

### ISSUE THREAD

**Issue by smikula** [Microsoft/TypeScript#13583]
**TypeScript Version:**  2.1.5

This is a problem I've encountered dealing with wrapping components in React (e.g. when creating a higher order component), but it would apply anywhere one is dynamically creating a class.  A code example will make clear what I'm trying to do:

**Code**

```ts
import * as React from 'react';
import { Component, ComponentClass } from 'react';

/* Higher order component */
export function wrapComponent<P>(InputTemplate: ComponentClass<P>) {
    return class extends Component<P, void> {
        someExtraMethod() { }
        render() {
            return <InputTemplate {...this.props} />;
        }
    };
}

/* Create a component and wrap it */
class MyComponent extends Component<void, void> { }
const MyWrappedComponent = wrapComponent(MyComponent);

/* This compiles fine, of course */
let referenceToComponent: MyComponent;

/* Error: Cannot find the name 'MyWrappedComponent' */
let referenceToWrappedComponent: MyWrappedComponent;

```

**Expected behavior:**

Ideally I should be able to treat MyWrappedComponent as a type (for the purposes of declaring variables, casting, etc.) just like I can MyComponent.  It is apparent that the compiler *is* aware of the type, since I can do this without issue:

```ts
let temp = new MyWrappedComponent();
temp.someExtraMethod();
```

And, in fact, once I have an instance of it I can even get the type I'm interested this way:

```ts
type MyWrappedComponentType = typeof temp;
let anotherReferenceToWrappedComponent: MyWrappedComponentType;
```

But it's far from ideal to have to instantiate a class just to get the type.  Plus it's awkward and unintuitive to have to deal separately with these two identifiers for the class: 1) the runtime reference to the class constructor and 2) the compile time type definition.

**Comment by DerFlatulator** [comment]
Is this what you are after?

```ts
let referenceToWrappedComponent: typeof MyWrappedComponent;
//                               ^-- typeof here

let temp = new MyWrappedComponent();
temp.someExtraMethod();
```

**Comment by mhegazy** [comment]
I do not think @smikula is looking for `typeof MyWrappedComponent`, but rather the instance type of this class, i.e. the `typeof temp` later on in his example. 

getting the return type of a function or a constructor is tracked by https://github.com/Microsoft/TypeScript/issues/6606.

`MyWrappedComponent` is a constant and not a type, you can read more about what the three spaces in http://www.typescriptlang.org/docs/handbook/declaration-merging.html.

**Comment by smikula** [comment]
Exactly what @mhegazy said -- I'm looking for the instance type of the class.

But I don't think #6606 quite solves the problem.  It would allow me to get the type without actually constructing an instance of it first, so that gets me 50% of the way there.  But it still means that I have to juggle the two identifiers whereas with a vanilla class one identifier can be used in both situations.  If I'm authoring a higher order component, I'd like to present its consumers with something that's as simple and intuitive to use as possible.

I'll take a look at the docs on declaration merging.  I realize there are likely underlying issues with what I'm suggesting that I don't fully understand, but it sure would be nice if this could work.

**Comment by PyroVortex** [comment]
```ts
type MyWrappedComponent = typeof MyWrappedComponent.prototype;
```
should give you what you want.
