### ISSUE TITLE
speeding up builds with tsc in child process

### ISSUE THREAD

**Issue by ORESoftware** [Microsoft/TypeScript#13588]
I have this line of code in Node.js which sends stdin to a bash child process 

```js
shell.stdin.write('tsc --jsx react --module amd --target es5 ' + path + '\n');
```

even transpiling 1 file takes about 1.5 seconds. Is there anyway I could somehow speed this up? the only thing I can think of is to have `tsc` be already running as a server and send it an ipc or socket message.

The problem with using `tsc --watch` is that I need to add a hook, such that when tsc is done with a transpilation I can run some other code. I would be happy to use` tsc --watch` to speed this up but I don't know how in this case.

**Comment by mhegazy** [comment]
Please see https://github.com/Microsoft/TypeScript/issues/13538

**Comment by ORESoftware** [comment]
thanks, looking at that convo, it appears that `--skipLibCheck `is the best option for my needs, but I will keep researching
