### ISSUE TITLE
tsc doesn't resolve module specified in the typeRoots

### ISSUE THREAD

**Issue by maximusk** [Microsoft/TypeScript#13581]
**TypeScript Version:**  2.1.5

I have the following directory structure:
```
tsconfig.json
a.ts
node_modules
|--- custom
     |--- rembo
           |---index.d.ts
```

The content of `index.d.ts` is the following:
```
export declare class Rembo {
    name: string;
}
```

I reference this module in `a.ts`:
`import {Rembo} from 'rembo';`

The `package.json` is the following:
```
{
  "compilerOptions": {
    "moduleResolution": "node",
    "module": "es6",
    "target": "es6",
    "typeRoots": [
      "node_modules/custom"
    ]
  }
}
```
The problem is that `rembo` module can't be resolved. When compiled, I get the following result:

`$ tsc --traceResolution`

```
======== Resolving type reference directive 'rembo', containing file 'D:/Projects/typescript/__inferred type names__.ts', root directory 'D:/Projects/typescript/node_modules/custom'. ========
Resolving with primary search path 'D:/Projects/typescript/node_modules/custom'
File 'D:/Projects/typescript/node_modules/custom/rembo/package.json' does not exist.
File 'D:/Projects/typescript/node_modules/custom/rembo/index.d.ts' exist - use it as a name resolution result.
Resolving real path for 'D:/Projects/typescript/node_modules/custom/rembo/index.d.ts', result 'D:/Projects/typescript/node_modules/custom/rembo/index.d.ts'
======== Type reference directive 'rembo' was successfully resolved to 'D:/Projects/typescript/node_modules/custom/rembo/index.d.ts', primary: true. ========
a.ts(3,21): error TS2307: Cannot find module 'rembo'.
```

I don't understand why the error, since it reports then:

> Type reference directive 'rembo' was **successfully** resolved to 'D:/Projects/typescript/node_modules/custom/rembo/index.d.ts', primary: true.

**Comment by mhegazy** [comment]
TypeRoots is useful for global declarations, things that you do not `import`, e.g. node definition file. when the compiler starts it loads all files under `typeRoots` and adds them in the global scope.

Seems like this is not what you are looking for, what you need is [Path mapping](www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping):

```ts
{
  "compilerOptions": {
    "moduleResolution": "node",
    "module": "es6",
    "target": "es6",
    "baseUrl": "./",
    "paths": {
      "*" : ["node_modules/custom/*"]
    }
  }
}
```

This tells the compiler to look under `<baseUrl>/node_modules/custom` for any import it sees.

**Comment by maximusk** [comment]
Thanks, a lot for you quick reply. As I understand, the `node_modules/@types` are automatically added to "paths", correct? I have an import of a module residing inside `node_modules/@types` and don't have "paths" configured for `node_modules/@types`, and module is still successfully resolved.

And is my understanding correct that both "typeRoots" and "types" is used for global modules resolve?

**Comment by mhegazy** [comment]
that is correct. I would not think about `typeRoots` unless you are using something global, e.g. `node`. otherwise, just think about modules.

**Comment by maximusk** [comment]
Got it, thanks. Where can I read about all supported patterns for `paths`? For example, can I match part of the module name and provide mappings for that part? Or only `*` pattern is supported?

**Comment by gdamjan** [comment]
What if the node_modules including node_modules/@types are outside the source directory alltogether?

```
SRC=$HOME/Pojects/demo
DEST=/tmp/build

ln -s $SRC/package.json $DEST/package.json
cd $DEST
npm install

cd $SRC
tsc --outDir $DEST/build --typeRoots $DEST/???
```
this doesn't work




(ts 2.1.6)

**Comment by mhegazy** [comment]
`paths` is relative to the `baseUrl` and not the `projectRoot`. so you can make the `baseUrl` whatever you want.
