### ISSUE TITLE
Compiler uses var hoisting instead of putting vars at the top of functions.

### ISSUE THREAD

**Issue by ryansmith94** [Microsoft/TypeScript#13592]
When using the **code** below, the compiler produces the **actual result** below using my [TS config](https://github.com/LearningLocker/xapi-validation/blob/master/tsconfig.json), but I think it should produce the **expected result** below. The `var` obviously gets hoisted to the top at runtime, however, in [code coverage tools this line is considered to be uncovered](https://codecov.io/gh/LearningLocker/xapi-validation/src/3176eb45497a5b1cf1b3668a2d2a2c3234bae7d5/dist/Tests/DescribeInteractionProp.js) (very small annoyance). Maybe this is an issue with the code coverage tool and this is really tricky for you guys to change, but I thought I'd make sure you're aware of the issue.

**TypeScript Version:**  Version 2.1.5

**Code**
```ts
itsInvalid({
  interactionType: type,
  [prop]: [],
}, `containing unsupported component ${prop} for ${type}`, test)
```

[Source file](https://github.com/LearningLocker/xapi-validation/blob/master/src/Tests/DescribeInteractionProp.ts)

**Expected behavior:**
```js
var _a;
return ItsInvalid_1.default((_a = {
        interactionType: type
    },
    _a[prop] = [],
    _a), "containing unsupported component " + prop + " for " + type, test);
```

**Actual behavior:**
```js
return ItsInvalid_1.default((_a = {
        interactionType: type
    },
    _a[prop] = [],
    _a), "containing unsupported component " + prop + " for " + type, test);
var _a;
```

[Built file](https://github.com/LearningLocker/xapi-validation/blob/master/dist/Tests/DescribeInteractionProp.js)

**Comment by RyanCavanaugh** [comment]
I'd say this is a bug in the coverage tool. A `var` declaration without an initializer is "executed" at the top regardless of its location in the block.

**Comment by mhegazy** [comment]
With the new emitter in place, there is no reason why we can not emit the variables at the top of the function. 

This is definitely a bug in the coverage tool, and the tool needs to be fixed to handle JS semantics correctly. but, we bride ourselves on emitting clean and idiomatic JS code, and emitting the var atop of the function would definitely be cleaner and more idiomatic.

https://github.com/Microsoft/TypeScript/issues/7017 tracks updating the emitter to emit vars at the beginning of the scope instead of the end.

**Comment by ryansmith94** [comment]
Thanks for responses @RyanCavanaugh @mhegazy, I really appreciate you taking the time to look at this and reply.

I agree, this is a bug in the coverage tool and I'll report an issue there too with a reference to this issue. I also agree that it would be cleaner and more idiomatic to emit the var at the top.

Thanks for referencing that issue @mhegazy, I've subscribed to notifications 👍 

Have a great weekend both, take care 😄
