### ISSUE TITLE
Issues with order of files in combined output

### ISSUE THREAD

**Issue by bjornbacklund** [Microsoft/TypeScript#1359]
Context: Visual Studio 2013 Ultimate w/ Update 4 with TS 1.3
I've got a TS project with 500+ files that compiled fine until today when I added a few new files. Now the order of the output file is messed up, parent class gets defined after subclass. I've tried both using a "_references.ts" file and without. 
Where can I learn about how the compiler arranges the files when combining into one output file? Is there a trick how to force a certain file to be placed earlier? What would cause a parent class to placed after a subclass?
Hoping for some hints.
---bjorn

**Comment by PaulHuizer** [comment]
I really whish this could be fixed. Typescript intellisense does not seem to have any problem at all  infering the proper order. When the compiler, which has the option "Combine into one file" does not solve this, it renders larger js files upfront unreliable ... 
The normal response to this issue is, user dynamic loading ... that is true. But in my case, the modules which are dynamicaly loaded, already exist of many classes which are in seperate projects compiled into a single file. Hence the problem exists in that scenario as well ...

**Comment by Elephant-Vessel** [comment]
Is the above information still valid? Is there no way to have the compiler in gulp-typescript or in visual studio analyze dependencies and concatenate files in a working order without us having to somehow specify the order manually or decorate each file with all its dependencies in reference-tags?

**Comment by Elephant-Vessel** [comment]
I understand that the typescript compiler in itself might be bound to reference-tags and imports, but do you know if there is any way to have Visual Studio do the dependency analysis and maintain a file like _references.ts automatically for all files in a project? The overhead of having to maintain reference-tags in all files in the project in order for it to compile properly is getting a little painful.

 Visual Studio seems capable enough to resolve the source for the implicit references that occur in a file, doesn't of feel like a relatively small investment to have it doing a dependency analysis and updating a text file as well?

**Comment by M0ns1gn0r** [comment]
Please implement the suggest automatic dependency analysis, maintaining a _references.ts in a large project is difficult.

**Comment by domchen** [comment]
This may help： https://github.com/domchen/typescript-plus . The typescript-plus compiler is an enhanced version of the original typescript compiler, which provides extra features to the original typescript compiler, such as accessors optimization, class reflection, conditional compilation and the most useful one : **automatically reordering the source files by analyzing their denpendencies in code.** 

It is basicly the same to the original compiler on usage, for a documentation of how to use the extra options please see the [README](https://github.com/domchen/typescript-plus#readme).

**Comment by haxiomic** [comment]
Looks good domchen! Do you plan to integrate the automatic ordering work back upstream into typescript?

**Comment by domchen** [comment]
@haxiomic If the typescript team accepts this feature some day, I will be happy to integrate it back to the original typescript project.  Util then, I will keep update the typescript-plus project.
