### ISSUE TITLE
Support/feature - tscserver / hooking into tsc --watch results

### ISSUE THREAD

**Issue by ORESoftware** [Microsoft/TypeScript#13608]
With these issues in mind:

https://github.com/Microsoft/TypeScript/issues/10879
https://github.com/Microsoft/TypeScript/issues/13588

I saw mention of `"tscserver"` - but I am not sure if that still exists - it sounds like that became `tsc --watch`?

### _What I want to do:_
Compile a .tsx file on demand, and when it's done compiling, send a socket message to the browser, telling the browser that the file is compiled and ready to be loaded into the browser.

### _The problem:_
 The problem is that` tsc --watch `does not allow me to listen for when the compilation is finished.

### _Temporary solution:_
So what I am currently doing now - instead of using `tsc --watch`, I am just running `tsc` as a child process on demand. When the child process closes, and exits with 0, I know compilation is done. And the problem is that it's a little bit slower this way, maybe 100 ms slower.

### _Longer term solution proposal:_
As a better solution, it would be great to pre-start a Node.js process with tsc loaded already - essentially creating a `tscserver`, but I am not sure if this is possible. Alternatively, `tsc --watch` would allow me to somehow listen for compilation completion events.

To re-iterate, I am looking for:

- (a) a way to hook into tsc --watch, to create actions that occur after compilation completes, 

and/or

- (b) a way to create tscserver that can process requests on demand, and where I can listen for compilation completion events.

Any help much appreciated, thanks.

**Comment by mhegazy** [comment]
The server supports a similar feature to `tsc --watch`, called compile-on-save, see https://github.com/Microsoft/TypeScript/blob/master/lib/protocol.d.ts#L893 for the server command.

`tsc` is just a command line tool, so running costume actions after it is done is really not in scope. 

All the pieces that allow `tsc --watch` to work are available to you through the [compiler API](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API), so you should be able to build a process that watches changes, and calls the compiler when needed. 

There are already existing tools like [tsb](https://www.npmjs.com/package/gulp-tsb) that does more or less what you are asking for, i would recommend investigating these before building you own.

**Comment by ORESoftware** [comment]
@mhegazy thanks

I opened an issue with tsb

https://github.com/jrieken/gulp-tsb/issues/61

I am not sure if they have what I am looking for, I probably can't use Gulp for this.

https://github.com/Microsoft/TypeScript/issues/14722
