### ISSUE TITLE
Consider making implicit `any` the default for all generic type parameters

### ISSUE THREAD

**Issue by RyanCavanaugh** [Microsoft/TypeScript#13609]
Now that we have generic defaults (:tada:), we should consider making all type parameters have an implicit `any` default. An unspecified uninferred type parameter would have type `any` and trigger a warning under `noImplicitAny`.

Benefits:
 * We'll need to do this in Salsa anyway
 * Improves JS migration story for codebases which inherit from generic base classes

Drawbacks:
 * There may exist people who run with `noImplicitAny` *off* but still want to enforce type parameters to be provided?

**Comment by falsandtru** [comment]
> **trigger a warning under noImplicitAny.**

**It's a really great improvement.**
I definitely want it.

**Comment by RyanCavanaugh** [comment]
@rbuckton interested in folding this into your current PR? We can also do it later instead

**Comment by mhegazy** [comment]
I would keep this in a separate PR.

**Comment by gcnew** [comment]
Wouldn't this be at odds with https://github.com/Microsoft/TypeScript/issues/1213 and https://github.com/Microsoft/TypeScript/issues/9949?

**Comment by DanielRosenwasser** [comment]
@gcnew could you elaborate on that thought?

**Comment by gcnew** [comment]
My hunch is that defaulting parameters to an implicit value is not a good idea in general. I don't have anything specific, it was more like throwing in areas where potential issues may reside.

Giving it a second thought, defaulting parameters to `any` will make the checker more permissive for users with `noImplicitAny` off. If #1213 and #9949 get implemented, the checker will become more restrictive again, which may be viewed as a backwards compatibility problem. On the other hand this proposal is beneficial for `noImplicitAny` users.

**Comment by DanielRosenwasser** [comment]
@gcnew I don't think that the implicit `{}` constraint type is much better though. If anything, `{}` is confusing for newcomers, and the behavior of getting it rather than `any` is actually more confusing for those who are familiar with `noImplicitAny`. I do think that the positives you listed are pretty compelling though, and explain much of the rationale for this proposal.

@RyanCavanaugh I just want to clarify the intent - is it *all* type parameters including those which have explicit defaults?

**Comment by RyanCavanaugh** [comment]
If there's an explicit default, we would obviously use that instead of `any`. Maybe I don't understand the question.

**Comment by DanielRosenwasser** [comment]
Sorry, I meant to ask about explicit constraints, not explicit defaults.

**Comment by RyanCavanaugh** [comment]
Somehow decided we should do #10571 as part of this discussion
