### ISSUE TITLE
Compiler allows to use undeclared names, failing at runtime

### ISSUE THREAD

**Issue by ntrrgc** [Microsoft/TypeScript#13605]
I was adapting some code to work with modules and I found something I did not expect.

**TypeScript Version:**  2.1.5

**Code**

package.json:
```json
{
  "name": "tsbug",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "tslib": "^1.5.0",
    "typescript": "^2.1.5"
  }
}
```

tsconfig.json:

```ts
{
    "compilerOptions": {
        "strictNullChecks": true,
        "noImplicitAny": true,
        "target": "es5",
        "module": "commonjs",
        "outDir": "build",
        "moduleResolution": "node",
        "lib": [
            "es5",
            "dom"
        ]
    },
    "include": [
        "src/**/*.ts"
    ]
}
```

src/main.ts:

```
new Thing();

export function main() {
}
```

src/Thing.ts:

```
// Note this class is not exported!
class Thing {
}
```

**Expected behavior:**

Running `tsc` should show a big error because `Thing` is not defined nor imported in `src/main.ts`.

**Actual behavior:**

`src/main.ts` compiles and breaks at run time instead.

```
"use strict";
new Thing();
function main() {
}
exports.main = main;
```

**Comment by RyanCavanaugh** [comment]
`src/Thing.ts` is not a module (it has no imports / exports) so it's assumed to be global code, i.e. included via a script tag.

**Comment by ntrrgc** [comment]
Interesting... Since when is there this behavior? Previously it would at least require a `<ref/>` tag if I recall correctly.

**Comment by RyanCavanaugh** [comment]
It's always worked this way

**Comment by ntrrgc** [comment]
Alright then... I'm just surprised. 

Running `tsc ./src/main.ts` fails, so using globals this way impedes you to perform file-by-file compilation... which sort of makes sense since in order to know if that declaration is an error you would need to compile every other file in the project that is not proven to be a module.

Furthermore, in my original code VS Code highlighted the undeclared name (I was not able to reproduce that in the test case) as an error...

**Comment by mhegazy** [comment]
use `--isolatedModules` if this is what you want to achieve, and every file would be expected to be a module, or you will get an error.

**Comment by ntrrgc** [comment]
Thanks, I'll use that.
