### ISSUE TITLE
tsc with no comment flags remove some comments.

### ISSUE THREAD

**Issue by mxtopher** [Microsoft/TypeScript#13602]
**TypeScript Version:  2.1.5**

**Code**

```ts
class Promise {
    then(callback:any){};
};

function commentedPromise(){
    new Promise()
    /* Commented Promise */.then(function(){});
}

function commentedParameters(
/* Parameter a */
a
/* End of parameter a */
/* Parameter b */
,
b
/* End of parameter b */
){}
```

**Expected behavior:**

This should be the compiled version:

```js
var Promise = (function () {
    function Promise() {
    }
    Promise.prototype.then = function (callback) { };
    ;
    return Promise;
}());
;
function commentedPromise() {
    new Promise()
        /* Commented Promise */.then(function () { });
}
function commentedParameters(
/* Parameter a */
a
/* End of parameter a */
/* Parameter b */
,
b
/* End of parameter b */
) { }
```

**Actual behavior:**

This is what I get

```js
var Promise = (function () {
    function Promise() {
    }
    Promise.prototype.then = function (callback) { };
    ;
    return Promise;
}());
;
function commentedPromise() {
    new Promise()
        .then(function () { });
}
function commentedParameters(
    /* Parameter a */
    a, b) { }
```

I agree these comments are in very weird positions, but I have a custom build system which uses /*#IFDEF*/ style guards, and I'm migrating a codebase with some hundreds of them.

Typescript is stripping some of these comments without warning.

**Comment by mxtopher** [comment]
A comment in the last line of an if block which precedes an else block is also removed:

```ts
function ifelse() {
    if(commentedParameters(1,2)){
        /*comment1*/
        commentedParameters(3,4);
        /*comment2*/
    }else{
        commentedParameters(5,6);
    }
}
```

Comment2 is removed when compiled.

**Comment by zelein** [comment]
Posting this here for freshness

TypeScript also appears to be removing comments in this fashion:
ts:
`const foo: boolean = var1 || /* istanbul ignore next */ null;`

js:
`var foo = var1 || null;`

This is painful when trying to get code coverage and are setting ignore statements.

**Comment by grovesNL** [comment]
I believe this one is also relevant ([TypeScript Playground](https://www.typescriptlang.org/play/#src=const%20a%20%3D%20%7B%0D%0A%20%20%20%20b%3A%201%2C%20%2F%2F%20Invisible%20comment%0D%0A%20%20%20%20c%3A%201%20%2F%2F%20Visible%20comment%0D%0A%7D%3B)):

TypeScript:
```
const a = {
    b: 1, // Invisible comment
    c: 1 // Visible comment
};
```

JavaScript:
```
var a = {
    b: 1,
    c: 1 // Visible comment
};
```

**Comment by yuit** [comment]
@zelein after investigating the issue, your example is different than original issue and would require much larger change to our code, mainly how leading comments (current we use linefeed to differentiate between leading comments of current node and trailing comment of previous node) are computed and possible our tree structure. To unblock your scenario, I would suggest do the following instead.
```ts
const foo: boolean = false || 
    /* istanbul ignore next */ null;
```

**Comment by grovesNL** [comment]
@yuit: Thanks for the quick feedback, opened #13939

**Comment by zelein** [comment]
Thanks @yuit. I will try this out the next time I come across this bug. I've worked around it for now.

**Comment by mhegazy** [comment]
@mxtopher please give `typescript@next` a try and let us know if this unblocks your tool chain.

**Comment by mxtopher** [comment]
Hello, thanks for the fix!
One of the cases I reported is still broken though. A comment in the middle of a chain of methods. I found other corner cases as well, as follows:
Typescript source
```ts
interface returnsAny {
    ():any;
};
declare var getObj: returnsAny;

var obj = getObj();

obj
    .something() // comment1
    .something() /* comment 2 */
    // comment3
    .something()
    /* comment4 */
    .something()
    /* comment5 */
;

if(/* comment 6 */ obj.something() /* comment 7 */) {
    obj.something();
}
/* comment 8 */
else {
    obj.something();
}
/* comment 9 */
```
Compiled Javascript
```js
var obj = getObj();
obj
    .something() // comment1
    .something() /* comment 2 */
    .something()
    .something();
if (obj.something() /* comment 7 */) {
    obj.something();
}
else {
    obj.something();
}
/* comment 9 */
```

Specifically:
- Comments in the middle of a chain of methods
- Comments on a conditional inside an if.
- Comments embracing an else clause.

Thanks!

**Comment by mxtopher** [comment]
Hello!

We are seeing the same errors on arrays that span more than one line:

Typescript source

````typescript
/* comment1 */
[1 /* comment2 */ ,2, /* comment3 */ 3, /* comment4 */
4,5];
function hue (a, /* comment5 */
b, c) {
}

Compiled Javascript:

````javascript
/* comment1 */
[1 /* comment2 */, 2, /* comment3 */ 3,
    4, 5];
function hue(a, /* comment5 */ b, c) {
}

(comment4 is being stripped)
It only happens when it's the last thing in a line.

Thank you for investigating.

**Comment by mhegazy** [comment]
Should be tracked by https://github.com/Microsoft/TypeScript/issues/13939
