### ISSUE TITLE
fixed params last in variable argument functions

### ISSUE THREAD

**Issue by JeroMiya** [microsoft/TypeScript#1360]
Extracting this suggestion from this issue:
https://github.com/Microsoft/TypeScript/issues/1336

Currently the variable arguments list supports variable arguments only as the last argument to the function:

``` typescript
function foo(arg1: number, ...arg2: string[]) {
}
```

This compiles to the following javascript:

``` javascript
function foo(arg1) {
    var arg2 = [];
    for (var _i = 1; _i < arguments.length; _i++) {
        arg2[_i - 1] = arguments[_i];
    }
}
```

However, variable argument functions are limited to appearing only as the last argument and not the first argument. I propose support be added for having a variable argument appear first, followed by one or more fixed arguments:

``` ts
function subscribe(...events: string[], callback: (message: string) => void) {
}

// the following would compile
subscribe(message => alert(message)); // gets all messages
subscribe('errorMessages', message => alert(message));
subscribe(
  'errorMessages',
  'customMessageTypeFoo123', 
  (message: string) => {
     alert(message);
  });

// the following would not compile
subscribe(); // supplied parameters do not match any signature of call target
subscribe('a1'); // argument of type 'string' does not match parameter of type '(message: string) => void'
subscribe('a1', 'a2'); // argument of type 'string' does not match parameter of type '(message: string) => void'
```

subscribe compiles to the following JavaScript:

``` javascript
function subscribe() {
  var events= [];
  var callback = arguments[arguments.length - 1];
  for(var _i = 0; _i < arguments.length - 2; _i++) {
    events[_i] = arguments[_i];
  }
}
```

notes: it should be impossible for typescript code to call this function with zero arguments when typechecking. If JS or untyped TS code calls it without arguments, callback will be undefined. However, the same is true of fixed arguments at the beginning of the function.

edit: used a more realistic/motivating example for the fixed-last/variable-arguments-first function.

**Comment by noobiept** [comment]
Createjs uses this, for example:

http://createjs.com/Docs/EaselJS/classes/Container.html#method_addChildAt
http://createjs.com/Docs/EaselJS/files/easeljs_display_Container.js.html#l200

**Comment by mhesler** [comment]
One example is String.prototype.replace.  Although this occurs in the middle and not exclusively at the beginning or end.
lib.d.ts dies this:
```
replace(searchValue: RegExp, replaceValue: (substring: string, ...args: any[]) => string): string;
```
should be this:
```
replace (searchValue: RegExp, replaceValue: (match: string, ...refs: string[], index: number, input: string) => string): string;
```

**Comment by pgrm** [comment]
I just came across this when updating TypeDefinitions for rethinkdb. `getAll` (http://rethinkdb.com/api/javascript/get_all/) should look like this:

    getAll(key: string, ...keys: string[]): Selection
    getAll(key: string, ...keys: string[], index: {index: string}): Selection

The problem here is `index` in the end being optional, but that is there problem, in an interface this still should work. Another example from rethinkdb client is the `map` function (http://rethinkdb.com/api/javascript/map/) which doesn't have the last field as optional.

For now I'm kind of "solving" it like `Action` and `Func` are defined in C# by simply creating new functions with more parameters:

    getAll(key: string, ...keys: string[]): Selection;
    getAll(key: string, key2: string, index?: Index): Selection;
    getAll(key: string, key2: string, key3: string, index?: Index): Selection;
    getAll(key: string, key2: string, key3: string, key4: string, index?: Index): Selection;
    getAll(key: string, key2: string, key3: string, key4: string, key5: string, index?: Index): Selection;
    getAll(key: string, key2: string, key3: string, key4: string, key5: string, key6: string, index?: Index): Selection;
    getAll(key: string, key2: string, key3: string, key4: string, key5: string, key6: string, key7: string, index?: Index): Selection;
    getAll(key: string, key2: string, key3: string, key4: string, key5: string, key6: string, key7: string, key8: string, index?: Index): Selection;
    getAll(key: string, key2: string, key3: string, key4: string, key5: string, key6: string, key7: string, key8: string, key9: string, index?: Index): Selection;

but this isn't just  a pain to do, it's also not the representation of the underlying javascript library

**Comment by aholmes** [comment]
As mentioned in #3686, to add to the list of libraries doing this, lodash uses this pattern in extend/assign.

**Comment by Xananax** [comment]
I'm getting stumped by something. Trying to create the typings for [Flyd](https://github.com/paldepind/flyd); it's a library that creates streams. It has a function `combine` that combines a variable amount of streams in one. It works like this:
```js
const combinedSignal = flyd.combine(function(s1:Signal,s2:signal2,s3:signal3....,self:signal,changed:signal[]){})
```

I've tried the method described by @pgrm, but I'm getting `Argument of type '(s: FlydStream, self: FlydStream) => void' is not assignable to parameter of type 'FlydCombinator'`, even if one of the overloaded calls matches this pattern exactly.

It seems the method works as long as I don't have another interface with overload that uses an overloaded interface. But the library is entirely made of curried functions calling each other, I just can't not have overloads using overloads.

I think I've managed to recreate a minimal test case [here](http://www.typescriptlang.org/play/#src=interface%20FlydStream%7B%0D%0A%09val%3Aany%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20FlydCombinator%20extends%20Function%7B%0D%0A%09%2F%2F%20if%20you%20remove%20the%20overloads%2C%20that%20is%0D%0A%09%2F%2F%20comment%20lines%208%20and%2010%20below%2C%20remove%20error%3A%0D%0A%09(s1%3F%3AFlydStream)%3Aany%3B%0D%0A%09(s1%3F%3AFlydStream%2Cself%3F%3AFlydStream)%3Aany%0D%0A%09(s1%3F%3AFlydStream%2Cs2%3F%3AFlydStream%2Cself%3F%3AFlydStream%2Cchanged%3F%3AFlydStream%5B%5D)%3Aany%3B%0D%0A%7D%0D%0A%0D%0A%2F%2F%20or%20enable%20comment%20block%20below%20on%20line%2015%0D%0A%2F%2F%20and%20uncomment%20on%20line%2023%0D%0A%2F**%2F%0D%0Ainterface%20FlydCombineFactory%7B%0D%0A%09(body%3AFlydCombinator)%3A(deps%3Aany%5B%5D)%3D%3EFlydStream%3B%0D%0A%09(body%3AFlydCombinator%2Cdeps%3Aany%5B%5D)%3AFlydStream%3B%0D%0A%7D%0D%0Aconst%20a%3AFlydCombineFactory%20%3D%20%3CFlydCombineFactory%3Efunction(body%3AFlydCombinator%2Cdeps%3Aany%5B%5D)%3AFlydStream%7B%0D%0A%09return%20%7Bval%3A'something'%7D%3B%0D%0A%7D%0D%0A%2F**%2F%2F**%20%2F%0D%0Aconst%20a%20%3D%20function(body%3AFlydCombinator%2Cdeps%3Aany%5B%5D)%3AFlydStream%7B%0D%0A%09return%20%7Bval%3A'something'%7D%3B%0D%0A%7D%0D%0A%2F**%2F%0D%0A%0D%0A%0D%0A%2F%2F%20notice%20the%20overload%20isn't%20used%3A%0D%0A%2F%2F%20%60type(s%2Cs)%3Avoid%20is%20not%20assignable%20to%20FlydCombinator%60%0D%0Aconst%20s%3AFlydCombinator%20%3D%20function(s%3AFlydStream%2Cself%3AFlydStream)%7B%0D%0A%09%0D%0A%7D%0D%0A%0D%0A%2F%2F%20but%20it%20works%20with%20one%20argument...%0D%0Aconst%20s2%3AFlydCombinator%20%3D%20function(s%3AFlydStream)%7B%0D%0A%09%0D%0A%7D%0D%0A%0D%0A%2F%2F%20and%20this%20is%20not%20recognized%20either%0D%0Aa(function(s%3AFlydStream%2Cself%3AFlydStream)%7B%0D%0A%09%0D%0A%7D%2C%5B%5D))

**Comment by olee** [comment]
Same here.
Tried to write type definitions for an library function which accepts a list of string arguments for filtering and as a last argument a callback. Only way to solve this right now I know is to prepare many copies of the function so it can be used in most cases.

Considering this issue was first opened in Dec 2014, I think this should definitely be added in the near future!

**Comment by DanielRosenwasser** [comment]
It looks like [`Ember.computed` uses it](https://guides.emberjs.com/v2.6.0/object-model/observers/).

I wonder if allowing rest arguments in *non-implementation signatures* would be acceptable. That way we could potentially support this at the type level but we'd leave the runtime implementation to be decided by users.

**Comment by thorn0** [comment]
lodash uses it: [`_.differenceBy`](https://lodash.com/docs/4.17.4#differenceBy), [`_.xorBy`](https://lodash.com/docs/4.17.4#xorBy).

**Comment by jsdevel** [comment]
koa-router also uses fixed params _after_ varargs: https://www.npmjs.com/package/koa-router#named-routes

**Comment by u8sand** [comment]
This has come a lot with certain style of function calling I've seen.

The following is not possible as far as I'm aware, related to this issue.

```ts
type FnWithCallbackAtEnd<
  FnA extends Array<unknown>,
  FnR extends unknown,
  CbA extends Array<unknown>,
  CbR extends unknown
> = (
  ...args: FnA,
  cb: (...args: CbA) => CbR
) => FnR
```

google api client library uses these types of callbacks, params where the last argument is a callback.

In general the args are usually fixed, but I want to easily convert *any* callback function in this style into a promise. To do so, it'd be nice to maintain type safety throughout.

**Comment by IlCallo** [comment]
Another use case: Jest `.each` function for data driven testing.

https://github.com/DefinitelyTyped/DefinitelyTyped/issues/34617

**Comment by thierrymichel** [comment]
Some personal use case here passing a context as last argument: https://stackblitz.com/edit/ts-with-rest-params
BTW, if someone have a better approach… 😊

**Comment by spion** [comment]
FastCheck uses a callback at the end of the parameter list to define a property:

**Comment by RecuencoJones** [comment]
Joi also uses this pattern:

- https://hapi.dev/family/joi/?v=16.0.1#objectandpeers-options
- https://hapi.dev/family/joi/?v=16.0.1#objectnandpeers-options
- https://hapi.dev/family/joi/?v=16.0.1#objectorpeers-options
- https://hapi.dev/family/joi/?v=16.0.1#objectoxorpeers-options
- https://hapi.dev/family/joi/?v=16.0.1#objectxorpeers-options

**Comment by trusktr** [comment]
I was trying to make a function whose variable arguments are effectively a tuple of the same type, and I wanted to add an optional last parameter to allow a user to be able to optionally specify options on how to handle all the previous args (how to handle the tuple).

F.e.

```js
someFunction(1,2,3,5,2,6,73,3,{method: 'factorial-numbers'})
```

I think the easiest solution, as I have the ability to modify the signature of the API, is to allow it to be called as

```js
someFunction(1,2,3,5,2,6,73,3)
```

or

```js
someFunction([1,2,3,5,2,6,73,3], options)
```

This is easy to do. Here's a [playground example](http://www.typescriptlang.org/play/#code/C4TwDgpgBA8mwEsD2A7AzlAvFA3gWACgpioIAPAQwFswAbCALijWACcEUBzQgX0MIAmEAMa0KraADMArimGJUUYBBYAKBMqpomKaVQBGEVgG0AugBooSeMnQB+JnAXoAlDr2HWgkWIlQZcs5KKsCqAHQRGhBa7gZGZm5QunFeBEKi4lKy8rbBahFh4pzaUBQoIAmxnvwEAPS1UNJo0BoMNcpqAIyWAGyWAMyWAEyWACy9vQDsLlD1sADShB2hxt1QfVCDUCNQ4+tTFriklDT0TADk+mIAFudQPDNzMPNAA).

**Comment by trusktr** [comment]
Another way you can do it is to track a variable in  the outer scope of your function. The call site would look like this:

```js
someFunction(1,2,3,5,2,6,73,3)
```

or

```js
someFunction.callback = () => {...}
someFunction(1,2,3,5,2,6,73,3)
```

**Comment by Morikko** [comment]
```
You will almost always want to follow the error callback convention, since most Node.js users will expect your project to follow them. The general idea is that the callback is the last parameter
```
From https://nodejs.org/en/knowledge/getting-started/control-flow/what-are-callbacks/
Module example:
- Stream: https://nodejs.org/dist/latest-v12.x/docs/api/stream.html#stream_writable_write_chunk_encoding_callback_1
- HTTP: https://nodejs.org/dist/latest-v12.x/docs/api/http.html#http_request_end_data_encoding_callback
- File System: https://nodejs.org/dist/latest-v12.x/docs/api/fs.html#fs_dir_close_callback

Also there is `callbackify` and `promisify` in the `util` module.
https://nodejs.org/dist/latest-v12.x/docs/api/util.html#util_util_promisify_original

The types for `promisify` are incredibly long and not complete after too many parameters: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/util.promisify/index.d.ts

---
I wanted this feature for typing a decorator that takes a function with a callback (node style) and add the promise api if no callback is provided. Thus, the function is now retro-compatible with the callback call and as a promise with async/await.

I wanted the types for the decorated function interface to be inferred from the original function.

**Comment by martinheidegger** [comment]
While I agree that this feature is very important and long overdue, there is a good reason not to implement it: It is not compatible with the ecmascript implementation of the rest spread operator.

```javascript
function x (a, ...b, c) {}
```

results in an error like: `SyntaxError: Rest parameter must be last formal parameter`.
I couldn't find a documented reason as to why this syntax is prohibited in ecmascript. But I believe it might warrant a request to the TC39 to add this functionality.

**Comment by phaux** [comment]
But it still could be supported in function overloads and function types.

**Comment by ChuckJonas** [comment]
it almost seems like this should be possible with the new Variadic Tuple Types releasing in 4.0?


Messed around with it a bit, but couldn't get it.  

Attempt

```ts
type StandardCallback<R> = (error: Error, result: R) => any

type Append<I, T extends unknown[]> = [...T, I]
function functionEndsWithCallback(...args: Append< StandardCallback<string>, unknown[]>){
  
}

functionEndsWithCallback(1, 2, (error) => {}); // not typesafe :(
```

**Comment by Andarist** [comment]
@RyanCavanaugh @andrewbranch this could be closed as it's currently possible with variadic tuple types.

**Comment by RyanCavanaugh** [comment]
Thanks!
