### ISSUE TITLE
Ambient module declarations with wildcards giving errors (official docs example not working)

### ISSUE THREAD

**Issue by mmc41** [Microsoft/TypeScript#13613]
**TypeScript Version:**

2.1.5

**Code examples taken directly from typescript [doc](https://www.typescriptlang.org/docs/handbook/modules.html#wildcard-module-declarations):**

```ts
declare module '*!text' {
    const content: string;
    export default content;
}

declare module 'json!*' {
    const value: any;
    export default value;
}
```

**Expected behavior:**

Should compile according to the official typescript [doc](https://www.typescriptlang.org/docs/handbook/modules.html#wildcard-module-declarations)

**Actual behavior:**

Errors:

3 declare module '*!text' {
                 ~~~~~~~~

src/lib/datasets.ts(3,16): error TS2664: Invalid module name in augmentation, module '*!text' cannot be found.


8 declare module 'json!*' {
                 ~~~~~~~~

src/lib/datasets.ts(8,16): error TS2664: Invalid module name in augmentation, module 'json!*' cannot be found.

**Comment by mmc41** [comment]
For reference, here is the associated tsconfig.json file:
{
    "compileOnSave": true,
    "compilerOptions": {
        "outDir": "dist",
        "rootDir": "src",
        "target": "es5",
        "module": "commonjs",
        "moduleResolution": "node",
        "lib": [ "es5", "es2015.core", "es2015.collection" ],
        "declaration": true,
        "watch": false,
        "allowJs": false,
        "removeComments": false,
        "forceConsistentCasingInFileNames": true,
        "noImplicitReturns": true,
        "noFallthroughCasesInSwitch": true,
        "pretty": true,
        "listFiles": false,
        "listEmittedFiles": false
    },
    "include": [
        "src/**/*"
    ],
    "exclude": [
      "node_modules"
    ]
}

**Comment by blakeembrey** [comment]
@mmc41 Did you write this inside of another file? When you write `declare module ''` inside of a module it's used for module augmentation, not a declaration. Make sure you put it in it's own file without any top-level `import` or `export` (that's what makes the compiler use the file as a module and would make the `declare module` a module augmentation).

**Comment by mmc41** [comment]
Thanks - You are right. Works if in it's own file.

P.S. Maybe the docs should mentions something about this - it was not obvious to me.

**Comment by lokeshdaiya** [comment]
@mmc41  Did it work for you 
I am trying it for markdown files 
in My typings.d.ts i have below code 
`
declare module "*!txt" {
    const value: string;
    export default value;
}
`

my  app.ts 

`
import readme from "./README.md!txt";
console.log(readme);
`

but it giving error 
![image](https://user-images.githubusercontent.com/7831299/27422616-7be47020-574c-11e7-8af9-55061b3c2829.png)

Here is sample plnkr https://plnkr.co/edit/7qT4Tu?p=preview

**Comment by kitsonk** [comment]
That is not a TypeScript error.  That is a run-time JavaScript error.  You need to be using a module loader that understands and has plugins available to it, not be using the CommonJS module loader provided by Node.js.

**Comment by lokeshdaiya** [comment]
If I don't want to use any module loader then is it possible to import with only typescript

**Comment by kitsonk** [comment]
No.  TypeScript does not JavaScript at run-time.  A JavaScript engine runs JavaScript at run-time.  Your engine of choice appears to be Node.js.  You _are_ using a module loader, the one that is supplied with Node.js.  It does not support plugins.  If you want to use plugins, you need to use a module loader that supports plugins.
