### ISSUE TITLE
TS does not like Object.values

### ISSUE THREAD

**Issue by ORESoftware** [Microsoft/TypeScript#13620]
I am seeing this (unnecessary) error:

![screenshot from 2017-01-22 00-04-21](https://cloud.githubusercontent.com/assets/11139560/22180993/8880d20c-e036-11e6-8b29-7a8070c68a74.png)

Is this a bug or can I  add something to my tsconfig.json to cover this?

```json
{
  "compilerOptions": {
    "baseUrl": "public",
    "paths": {
    },
    "types": [
      "requirejs",
      "node"
    ],
    "typeRoots": [
      "node_modules/@types"
    ],
    "compileOnSave": true,
    "target": "es5",
    "module": "amd",
    "outFile": "dist/blt.js",
    "noImplicitAny": false,
    "removeComments": true,
    "preserveConstEnums": true,
    "allowJs": false,
    "allowUnreachableCode": true,
    "moduleResolution": "node",
    "lib": [
      "es2015",
      "dom"
    ]
  },
  "include": [
    "./**/*.ts",
    "./**/*.tsx"
  ]
}
```

**Comment by HerringtonDarkholme** [comment]
Because it is in es2017.

https://github.com/Microsoft/TypeScript/blob/master/lib/lib.es2017.object.d.ts

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/values

**Comment by ORESoftware** [comment]
thanks! I didn't realize that
