### ISSUE TITLE
Generics return type check with arrow functions

### ISSUE THREAD

**Issue by zerkms** [Microsoft/TypeScript#13631]
**TypeScript Version:**  playground (2.1.4-insiders.20161201)

**Code**

```ts
let f1: <T>(a: T) => T = a => 42;

function f2<T>(a: T): T {
    return 42;
};
```

**Expected behavior:**

Since those functions are identical I expect both to behave the same: to fail the type check.

**Actual behavior:**

The `f1` type checks fine.

**Comment by mhegazy** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/5616
