### ISSUE TITLE
`noImplicitAny` and generic arrow functions misbehave

### ISSUE THREAD

**Issue by zerkms** [Microsoft/TypeScript#13632]
**TypeScript Version:**  playground (2.1.4-insiders.20161201)

**Code**

The following code should be run with the `noImplicitAny` set:

```ts
let f1: <T>(a: T) => T = a => a;

function f2<T>(a: T): T {
    return a;
};
```

**Expected behavior:**

Both functions should compile fine.

**Actual behavior:**

The `f1` arrow function fails the type check as the compiler thinks `a` is of `any` type.

**Comment by mhegazy** [comment]
When the compiler compares any generic signature, it erases the generic type parameters, and replaces them with `any`. the result is that the parameter on the  right hand-side here gets a type `any` implicitly. the error is telling you that this has happened.

If the compiler gets "smarter" comparing generic signatures, the error would go away.

**Comment by zerkms** [comment]
@mhegazy as I demonstrated in the sample code it only happens with arrow functions. The function statements work fine.

**Comment by aleksey-bykov** [comment]
> If the compiler gets "smarter" comparing generic signatures, the error would go away.

what are the chances?

**Comment by zerkms** [comment]
@mhegazy what is the final resolution?

**Comment by mhegazy** [comment]
> @mhegazy what is the final resolution?

resolutions, just like types, are always open in TS :D

Should be tracked under https://github.com/Microsoft/TypeScript/issues/9366
