### ISSUE TITLE
Uninitialized variable from outer scope can be used inside function

### ISSUE THREAD

**Issue by ikokostya** [Microsoft/TypeScript#13638]
**TypeScript Version:**  2.2.0-dev.20170123 

**Code**

```ts
function f() {
    x.match(/\d/);
}

let x: string;

f();
```

**Expected behavior:**

Error `Variable 'x' is used before being assigned`.

**Actual behavior:**

No errors.

**Config:**

```json
{
    "compilerOptions": {
        "module": "commonjs",
        "moduleResolution": "node",
        "target": "es2015",
        "noImplicitAny": true,
        "noImplicitThis": true,
        "strictNullChecks": true,
        "outDir": "build"
    },
    "files": [
        "test.ts"
    ]
}
```

**Comment by mhegazy** [comment]
The compiler does not do flow analysis at call sites. so the assumption here is that you declared `x` as `string`, so it should be `string`.

The complete solution requires running the control flow analysis with in lining the function at every call site, which is not that feasible. you can see more related discussion in https://github.com/Microsoft/TypeScript/issues/9998

**Comment by sccolbert** [comment]
Related to #4244

**Comment by dmikis** [comment]
@mhegazy That's OK, but why does `let x: string;` even compile with strict `null` checks on? Shouldn't it requite `x` to be `string | undefined` to  `x` be able to uninitialised?

**Comment by mhegazy** [comment]
that would be too restrictive. consider..

```ts
let x: string;
if (condition) {
   var foo = ..
   x = foo();
}
else {
    var bar = ..
    x = bar();
}

x.indexOf("...") //OK.
```

**Comment by dmikis** [comment]
What's wrong with writing `let x: string = '';`?

For me it basically breaks whole 'if something is not `| null` (or `| undefine`) then it's definitely a valid object` guarantee.
