### ISSUE TITLE
Typing of CanvasRenderingContext2D.measureText is incorrect

### ISSUE THREAD

**Issue by Bambuuh** [Microsoft/TypeScript#13637]
**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)

**Code**

```ts

measureText(text: string): TextMetrics;

// Should be 

measureText(text: string | number): TextMetrics;
```

**Comment by RyanCavanaugh** [comment]
It doesn't accept a `number` any more than it accepts a `function` -- an implicit conversion occurs.
