### ISSUE TITLE
CSSStyleDeclaration string properties all have `| null` type declaration.

### ISSUE THREAD

**Issue by sccolbert** [microsoft/TypeScript#13644]
`lib.dom.d.ts` has recently suffixed all of the properties of `CSSStyleDeclaration` with `| null`:
https://github.com/Microsoft/TypeScript/blob/master/lib/lib.dom.d.ts#L1382
https://github.com/Microsoft/TypeScript/commit/6814c1d883791a1ad976f3146315de30e00dc0b9

For those of us using `--strictNullChecks`, this is forcing a null assertion (!) every time a property is used, even though according to the spec `null` will never be returned, only an empty string:
https://drafts.csswg.org/cssom/#dom-cssstyledeclaration-getpropertyvalue
> The camel-cased attribute attribute, on getting, must return the result of invoking getPropertyValue() with the argument being the result of running the IDL attribute to CSS property algorithm for camel-cased attribute.

The spec does seem to allow `null` as an argument for `setPropertyValue`, so technically this a case where allowing a different type for a getter and setter (#2521) would be required to accurately model a builtin. 

But in the absence of that, this particular object treats the empty string the same as `null` for setting, so I think it would be cleaner to simply remove `| null` from this definition so that we don't have to needlessly null-assert everywhere `CSSStyleDeclaration` is used.

**Comment by mhegazy** [comment]
Since this is strictly not per spec, we would like to get some more user feedback to warrant the change.

**Comment by inad9300** [comment]
Just as a curiosity, why were the `null`s added in the first place? What was the feedback then?

**Comment by kitsonk** [comment]
The libraries are generated from a WebIDL, with overrides.  I believe it is still the WebIDL from Edge, though there was a desire to generate it from the spec.

There is seldom any feedback required to make something more compliant with the spec and in many cases it is automatic as the upstream "authority" gets updated.  The generator is available at [Microsoft/TSJS-lib-generator](https://github.com/Microsoft/TSJS-lib-generator/), which includes the current version of the spec files it uses.

**Comment by inad9300** [comment]
It's very interesting to know this, thanks! I didn't know such level of automation was in place. This is then definitely related with the issue I just opened about [missing HTML tags](https://github.com/Microsoft/TypeScript/issues/17828).

**Comment by HolgerJeromin** [comment]
Currently we have mixed `string` and `string | null` typings 8-/
https://github.com/Microsoft/TypeScript/blob/master/lib/lib.dom.d.ts#L2749

**Comment by ypresto** [comment]
Perhaps already fixed around here?:
https://github.com/microsoft/TSJS-lib-generator/pull/723

**Comment by amakhrov** [comment]
Looks like this has landed in TS 3.6.4
