### ISSUE TITLE
getCompletionsAtPosition should (optionally?) include type

### ISSUE THREAD

**Issue by jeffreymorlan** [Microsoft/TypeScript#13647]
In many popular IDEs, the completion list includes shows each item's type alongside its name. Take, for example, Eclipse:
![eclipse](https://cloud.githubusercontent.com/assets/1071296/22235644/b40f2876-e1b5-11e6-947e-f46bd5db019e.png)
Or IntelliJ IDEA:
![intellij](https://cloud.githubusercontent.com/assets/1071296/22235963/8ed82736-e1b7-11e6-8cb4-d21180f01df3.png)
And the one I use, NetBeans:
![netbeans](https://cloud.githubusercontent.com/assets/1071296/22235647/b81bd77a-e1b5-11e6-82d6-c375fdccfe66.png)

If you want to make a TypeScript editor like that, you can't do it with a stock `typescriptServices`, because the `CompletionEntry` only includes the `kind` of each symbol and not the type. Calling `getCompletionEntryDetails` on every entry is impractical as it includes far more verbose information than belongs in the menu items, and makes bringing up the completion list O(n^2).

In the NetBeans plugin I wrote, I made a small change to include the type in `CompletionEntry`:
```diff
--- services/completions.ts
+++ services/completions.ts
@@ -110,6 +110,7 @@
                 kind: SymbolDisplay.getSymbolKind(typeChecker, symbol, location),
                 kindModifiers: SymbolDisplay.getSymbolModifiers(symbol),
                 sortText: "0",
+                type: typeChecker.typeToString(typeChecker.getTypeOfSymbolAtLocation(symbol, location))
             };
 
         }
```

**Comment by mhegazy** [comment]
> If you want to make a TypeScript editor like that, you can't do it with a stock typescriptServices, because the CompletionEntry only includes the kind of each symbol and not the type. Calling getCompletionEntryDetails on every entry is impractical as it includes far more verbose information than belongs in the menu items, and makes bringing up the completion list O(n^2).

The completion list can include many items, e.g. all globals for instance in a global completion. these are thousands of symbols. if the completion list were to resolve types for each of these on every request, completion will take order of minutes to finish.

Most of the time the user selects the information of a few completion entries, either as they are typing, or through browsing. it much more economical to request the type when the user selects an entry, or even the visible items in the list instead of getting them all.

**Comment by jeffreymorlan** [comment]
> The completion list can include many items, e.g. all globals for instance in a global completion. these are thousands of symbols. if the completion list were to resolve types for each of these on every request, completion will take order of minutes to finish.

This has not been my experience. Let's take TypeScript's source itself for example: inside `namespace ts {}`, my patched `getCompletionEntries` takes ~50ms to bring up 2,721 entries. If the `Program` has just been re-created so that nothing has any type info yet, it takes ~250ms. Given that this is the worst case, it's really not that bad.

> Most of the time the user selects the information of a few completion entries, either as they are typing, or through browsing. it much more economical to request the type when the user selects an entry, or even the visible items in the list instead of getting them all.

Knowing the type is often useful in figuring out which entries you might be interested in. Being able to skim a list of types saves a lot of time I'd otherwise spend having to look at a bunch of entries' details one at a time.

Fetching details for items as they become visible may not be possible depending on how the completion list UI works, and it has its own performance problems (`getCompletionEntryDetails` has to perform a minimal completion in order to get the symbol for the one entry, which is fine if it's being called on a single user-selected entry, but not so good on a whole page of entries).

**Comment by mhegazy** [comment]
Completion list time, including the UI should be sub 200ms. getting the type is a function of your code complexity and project size. We originally had completions get all types, and that did not scale. splitting the two APIs allows for better utilization of the time allowance for completion. again most users are not interested in the full list.

If what you are asking about is filtering the list based on the context, e.g. getting the enum name if `x` is an enum in a position like `if (x === | ` , or filtering out types in a value position, this should be done in the API itself and not after the fact. I would be interested to know what entries you get that you believe should not be there.
