### ISSUE TITLE
JSDoc @summary tag

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#13650]
I propose to use the jsdoc `@summary` tag when showing the hover information.

<img width="300" alt="screen shot 2017-01-24 at 9 48 01 am" src="https://cloud.githubusercontent.com/assets/1324476/22240412/65ace4d2-e21b-11e6-8538-dccf95655ba8.png">

```ts
/**
 * @summary 
 * Get Document body.
 *
 * @description
 * Get the document body of the view. Sometimes, it is useful to render an
 * alert view or notify the user of something that have happened. These views
 * are owned by the document body, so to reference the document body, you use
 * `this.document`. And it is only, `ContentBaseView` and it derivatives that
 * has a reference to the document body.
 *
 * @example
 * ```
 * render () {
 *     return (
 *         <div className='NameField'>{this.l('NAME_FIELD')}</div>
 *     );
 * }
 * ```
 */
function getDocument() {
    return '';
}
```

Right now, the summary of the hover info is empty. I guess it doesn't recognize it at the moment?

**Comment by mjbvz** [comment]
I believe this tag is now displayed in TS 2.7 with VS Code insiders 1.20:

<img width="588" alt="screen shot 2017-12-21 at 4 27 24 pm" src="https://user-images.githubusercontent.com/12821956/34280347-f01b9c26-e66b-11e7-9949-cb1131c1ec66.png">
