### ISSUE TITLE
The --importHelpers option is unsupported when building with MSBuild

### ISSUE THREAD

**Issue by avonwyss** [Microsoft/TypeScript#13653]
**TypeScript Version:**  2.1.5

In a MSBUILD project, I have a property set like this:

```xml
    <TypeScriptImportHelpers>True</TypeScriptImportHelpers>
```

**Expected behavior:**
TSC should be called with the `--importHelpers` parameter.

**Actual behavior:**
TSC is called without this command line parameter. The MSBUILD targets file from the NuGet package (tested version 2.1.5) do only support `TypeScriptNoEmitHelpers`, but nothing else related to `helpers` is in the file, so that including this was apparently forgotten.

**Comment by mhegazy** [comment]
@yui, it would be good to do a pass over the other options as well, and make sure they are all covered correctly.

**Comment by mhegazy** [comment]
@avonwyss consider switching your project to using a tsconfig.json.

**Comment by avonwyss** [comment]
@mhegazy Switching is not an option, since the MSBUILD also does code generation which is then dynamically included in the ItemGroup of files to be compiled by TSC, and the TSC output files are then included into the .NET assembly being compiled as embedded resource, so using MSBuild seems to be the only option.

For now I have added the necessary option explicitly to the `TypeScriptBuildConfigurations` MSBuild property and this works until this is fixed.
