### ISSUE TITLE
Allow yield expression in a closure referencing the generator body.

### ISSUE THREAD

**Issue by frgomes** [Microsoft/TypeScript#13657]
The compiler complains when an **yield** is employed inside a **function** even though directly enclosed by the generator body.

**TypeScript Version:**  2.1.5

**Code**

```ts
function *myGenerator(base: string, file: string) {
    const fs   = require("fs");
    const lines1 = fs.readFileSync(`${base}/${file}`, {encoding: "utf-8"}).toString().split('\n');
    for (let i=0; i<lines1.length; i++) {
        const line = lines1[i];
        yield line; // COMPILES
    };
                
    const lines2 = fs.readFileSync(`${base}/${file}`, {encoding: "utf-8"}).toString().split('\n')
        .forEach(function (line) {
            yield line; // DOES NOT COMPILE
        });
}
```

**Expected behavior:**

Being absolutely oblivious about the current capabilities of the compiler in regards to this functionality, I'm naively hoping that the compiler is able to capture the outer scope of the generator definition.

**Actual behavior:**

```
error TS1163: A 'yield' expression is only allowed in a generator body.
```

**Comment by frgomes** [comment]
Question raised at StackOverflow:
http://stackoverflow.com/questions/41810518/cannot-compile-async-code-with-generators-in-typescript

**Comment by RyanCavanaugh** [comment]
`yield` is only valid in generator functions and cannot be used in the body of function expressions inside generators. This is actually a *syntactic* error in JS; TS just gives you a more informative error message.
