### ISSUE TITLE
Support 'EventSource' in lib.dom.d.ts

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#13666]
_From @rocketRobin on January 24, 2017 8:30_

- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 6.1.7601

---

Steps to Reproduce:

1. javascript intellesence do not support EventSource
2.

_Copied from original issue: Microsoft/vscode#19117_

**Comment by mjbvz** [comment]
_From @mousetraps on January 24, 2017 23:5_

@mjbvz - looks like [EventSource](https://developer.mozilla.org/en-US/docs/Web/API/EventSource) is missing from [lib.dom.d.ts](https://github.com/Microsoft/TypeScript/blob/master/lib/lib.dom.d.ts)

**Comment by mjbvz** [comment]
As per @mousetraps' comment, a type definition for `EventSource` should be added to the dom `d.ts`

**Comment by Pappa** [comment]
I have opened a PR for this issue:

https://github.com/Microsoft/TypeScript/pull/14658

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by jeff3dx** [comment]
For a workaround you can reference EventSource like this:
`const sse = new window['EventSource'](url);`
