### ISSUE TITLE
Allow to find-all-references on the `default` keyword.

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#13662]
Could be useful for code like `export default 0;`.
Original suggestion: https://github.com/Microsoft/TypeScript/issues/11551#issuecomment-271492560

**Comment by OliverJAsh** [comment]
I have a large codebase where we use anonymous exports everywhere. It's quite common in React component files, for example, where you want to apply higher-order components to the export:

``` ts
const Component = () => null
export default connect(mapStateToProps)(Component);
```

I would love to see this fixed so we can continue using find references on these exports.

**Comment by borekb** [comment]
This would be useful indeed. In our React project, we have something similar that @OliverJAsh described. Here's an example that compares a plain component with a wrapped one:

## Plain component

![image](https://user-images.githubusercontent.com/101152/29625488-25b097fe-882c-11e7-91ac-b537fd5dff3b.png)

F12 navigates to `MyComponent`:

![image](https://user-images.githubusercontent.com/101152/29625870-425c749e-882d-11e7-86c6-bd860c6ed3c3.png)

and Find All References lists usages in `App.tsx`:

![image](https://user-images.githubusercontent.com/101152/29625609-84ac031a-882c-11e7-9e91-59e6e64c6960.png)

## Wrapped component

F12 from `App.tsx` takes me here:

![image](https://user-images.githubusercontent.com/101152/29625720-c90fbc54-882c-11e7-87d4-e7a79be65de5.png)

but running Find All References at this very place produces no results:

![image](https://user-images.githubusercontent.com/101152/29625753-e879efce-882c-11e7-8449-991b18273a68.png)

so the experience is quite a bit worse.

Thanks for considering this.
