### ISSUE TITLE
TypeScript's frailty when import 2 classes together in one namespace.

### ISSUE THREAD

**Issue by krzysztofstefanowski** [Microsoft/TypeScript#13672]
Have two files ClassA.ts and ClassB.ts with following code. Run it. 'TypeError: ClassB is not a constructor' occurs.

**TypeScript Version:**  2.1.4

**Code**

ClassA.ts
```ts
namespace MyNamespace{
    import ClassB = MyNamespace.ClassB;
    export class ClassA {
        private b : ClassB;
        public init(){
            this.b = new ClassB();
        }
    }
}
```

ClassB.ts
```ts
namespace MyNamespace{
    import ClassA = MyNamespace.ClassB;
    export class ClassB {
        private a : ClassA;
        public init(){
            this.a = new ClassA();
        }
    }
}
```

then type in your code:
```ts
let a : MyNamespace.ClassA = new MyNamespace.ClassA();
let b : MyNamespace.ClassB = new MyNamespace.ClassB();
a.init();
b.init();
```

**Expected behavior:**
Everything should be ok.

**Actual behavior:**
TypeError: ClassB is not a constructor when `a.init()`

ClassA imports ClassB but ClassB is not 'defined' yet.
In javascript it looks like this:
`var ClassB = MyNamespace.ClassB;`
But object ClassB is not defined in object MyNamespace.

**This frail behaviour makes 'import' mechanism useless.**

**Comment by mhegazy** [comment]
`import` gets you a copy of the value, so the runtime error is expected.

**Comment by krzysztofstefanowski** [comment]
I agree with you, mhegazy, this is how it works, as you described and as i described. But from programmer's point of view if programmer wants to import something, it is expected that 'thing' will be imported. Typescript has been designed to create a high layer that hides javascript, has been designed to provide object-oriented language and in my opinion all of these are moving in the right direction - it is good, but this one issue still makes 'import' mechanism useless (or limited within a certain range). It is not a bug, but a small frailty.

I know it requires probably a lot of changes, but I believe it is possible to improve the compiler and make Typescript even better, close to C# ;)

It is only my suggestion to do something with that.

**Comment by mhegazy** [comment]
The namespace provides you with the indirection already. so you can just refeence `MyNamespace.ClassB` and that will be the intended value. alternatively you can alias the namespace, `import N = MyNamespace` and reference `N.ClassB`.

**Comment by krzysztofstefanowski** [comment]
**Yes**, in the entire project i must use full namespace references `MyNamespace.ClassB` by hand.. and still **import is useless**. Also making namespaces' shortcuts is not a solution because code becomes illegible. 

**This could be done automatically by the compiler.**
