### ISSUE TITLE
Make TypeScriptLang's Playground configurable

### ISSUE THREAD

**Issue by series0ne** [microsoft/TypeScript#13673]
Would it be possible to add an editable tsconfig.json to TSL's Playground?

This would be useful for seeing how various rules are enforced and how tsc is able to emit different ES(n) versions.

**Comment by DanielRosenwasser** [comment]
We'd have to get multi-file support into the playground in that case, but in the mean time we recently added some common compiler options for you to use:

![image](https://cloud.githubusercontent.com/assets/972891/22303213/11a899ea-e2e7-11e6-8018-eb24747f51c3.png)

**Comment by series0ne** [comment]
@DanielRosenwasser could "target" be added?

In the past I've found the playground very useful for seeing how TypeScript emits code. It would be useful to be able to see how it emits for different ES* versions.

**Comment by michaeljota** [comment]
I think also `lib` should be added. This is a must for quick testing about the TSC, with ES2016, and ES2017 features and so.

**Comment by michaeljota** [comment]
This also needs to be designed with #15662 in mind, to not select options that the selected compiler would not understand.

**Comment by zheeeng** [comment]
Need `lib` and `target` be configurable. Need this feature for prototyping codes in TS playground and copy-paste to run in the browser or other envrionment.

**Comment by orta** [comment]
These features are in the new playground! So I'm closing this issue.
