### ISSUE TITLE
Parameters with default values accept undefined, but lose it in method body

### ISSUE THREAD

**Issue by mprobst** [Microsoft/TypeScript#13679]
**TypeScript Version:**  2.1.5

**Code**

```ts
function x(canBeUndefined: number = 1) {
  let noLongerUndefined: number = canBeUndefined;   
}
x(undefined); // Can pass undefined!
```

That is, I'm able to 
```

**Expected behavior:**

I'd (preferably) expect TypeScript to reject the `x(undefined);` call, or understand that `canBeUndefined` is of type `number|undefined`.

**Actual behavior:**

With TypeScript 2.1.5 and `--strictNullChecks` this code is accepted as is.

**Comment by mprobst** [comment]
This is probably related, but not identical, to #11424 and #11900.

**Comment by RyanCavanaugh** [comment]
`canBeUndefined` *cannot* be `undefined` in the body.

We allow passing `undefined` here because parameter defaults can actually appear anywhere in a signature; explicitly passing `undefined` is a legal way to tell the function to use its default parameter value instead.

**Comment by mprobst** [comment]
Ah right, my bad. Thanks Ryan!
