### ISSUE TITLE
Questions about string index types, and Record as a `Dictionary` type. Suggestions needed

### ISSUE THREAD

**Issue by schwers** [Microsoft/TypeScript#13689]
**TypeScript Version:**  2.1.4

I'm working in a new code base that's making heavy use of TypeScript for our models, and collections of models. Our team was hoping to write collection types that make it clear to the reader that this collection is:

- a map of id (a string) to model instance
- any key in this map, must be a string, but more restrictively, should be of type Model-Id.

TypeScript currently limits the type of indexes to be `string` or `number`. This is technically more correct, but makes for types that have a less clear meaning. Our team found the `Record` type, but I need some clarification on its usage.

**Code**

TypeScript doesn't allow specifying the type of indexes to be a user defined type, even if that type is string. 
```ts
type PostId = string;

type Post = {
  id: PostId,
  title: string,
  url: string,
};

// For storing `Post`s, we keep an object that maps a `PostId` -> `Post`.
// This plays nicely with Redux, and since we pass these 'PostMaps` around
// between functions, it would be nice to have a clear type defintion.
// Ideally this type definition should make it clear that we're not mapping
// just any string to a `Post`, but that the keys of this map will be `PostId`s.
// I expected to be able to write something like this:
type PostDictionary = {
  [postId: PostId]: Post,
};
```

But that is invalid TypeScript.

```ts
// Our codebase has multiple places where we want to define 'Dictionary' types.
// Ideally this could be written in a way that conveys the keys of this 'Dictionary'
// aren't just any string, but rather a specific type of string.
// We expected to be able to write something like this:
type Dictionary<K is string, T> = {
  [key: K]: T,
];

// This would let us re-write the `PostDictionary` type as follows:
type PostDictionary = Dictionary<PostId, Post>;
```

That is also invalid. After further reading of the advanced-types, we discovered `Record`

**Record**

```ts
// With the Record Type, we can re-write the `PostDictionary` type.
// At first glance, it seems like this is what we wanted from the hypothetical `Dictionary` type
type PostDictionary = Record<PostId, Post>;

// i.e. this is ends producing something like
type PostDictionary = {
    [key: string]: Post,
}
```

Is this an expected use case of `Record`? Digging into `Record`'s definition, it seems like it's intended to be used to define a fixed set of string keys, mapping to `T`.

```ts
// `Record` maps over its generic argument K, which lets you write things such as:
type PostRecord = Record<'a' | 'b' | 'c', Post>;

// This ends up being a very different type than the example `PostDictionary`.
// i.e. its equivalent to
type PostRecord = {
  a: Post,
  b: Post,
  c: Post,
};
```

The advanced-types documentation feel a little too concise when it comes to `Record`.
[examples in the TypeScript-Handbook](https://github.com/Microsoft/TypeScript-Handbook/blob/ae6832a6aaaaf2396b689d10d5c27ca0592657c5/pages/Advanced%20Types.md#mapped-types) seem to also indicate that `Record` is intended to be used with `K` being a union of string literals.

The IsomorphicMappedTypeInference tests for [makeRecord](https://github.com/Microsoft/TypeScript/blob/23992ba106219372f1fed83e51f0bca4f9d78233/tests/baselines/reference/isomorphicMappedTypeInference.js#L80) and [makeDictionary](https://github.com/Microsoft/TypeScript/blob/23992ba106219372f1fed83e51f0bca4f9d78233/tests/baselines/reference/isomorphicMappedTypeInference.js#L94) seem to also illustrate that `Record` is intended to be used with an explicit union of string keys, as opposed to creating a general `Dictionary` Type.

Could you provide guidance on the 'correct' usage of `Record`? As is we're starting to use it in place of the hypothetical `Dictionary` type, but this doesn't seem like the right way to use it.

**Comment by mhegazy** [comment]
So just for me to understand `PostId` is just an alias to `string`, it is not a subtype of `string`? if so `Record<PostId, Post>` is just a complicated way to say `{ [key: string]: Post }`, it should work, but it does not do any thing different from the other type; and I would argue not readable.

**Comment by mhegazy** [comment]
Using record as you mentioned would work. it is important to reiterate that it is just a `string`, and the compiler will not enforce any special rules on `CommentDictionary` because you called it `commentId`.

If `commandId` is a finite subset of `string`, e.g. `"command1" | "command2" | "command3" ..|"command100"`, then you can use it with mapped types to enforce only using one of these when accessing the dictionary.

If `commandId` represents an infinite set that is subtype of `string`, like you have to call a factory function to get one of these, e.g. `function getCommandId (): string & { _commandId: true }` then that would be more interesting. the problem here is that the compiler does not support this today. you can either index with `string` or with a set of known literals. it is possible that the suggestion in https://github.com/Microsoft/TypeScript/issues/6579 would apply to your case.

**Comment by geirsagberg** [comment]
Is there a way to infer the finite subset of `string` based on the keys of an object? Relevant SO question: https://stackoverflow.com/questions/49538199/is-it-possible-to-infer-the-keys-of-a-record-in-typescript
