### ISSUE TITLE
Typescript compiler should support ordered dependency resolution and tree-shaking when emitting single files.

### ISSUE THREAD

**Issue by series0ne** [microsoft/TypeScript#13682]
# Scenario
I have a library that has several TypeScript files:

**lib.core.ts**
```
module LibCore {
    export class Model {
        ...
    }

    export class TrustModel extends Model {
        private exfn: LibCore.Extensions.NumberFunctions;
        ...
    }
}
```

**lib.core.ext.ts**
```
module LibCore.Extensions {
    export class NumberFunctions {
        ...
    }

    export class StringFunctions {
        ...
    }
}
```

**lib.core.web.ts**
```
module LibCore.Web {
    export class SomethingWebRelated {
    }
}
```

**app.ts**
```
class Program {
    private model: LibCore.TrustModel;
}
```

My dependency graph here should be

```
Program
    TrustModel : Model
        NumberFunctions
```

Notice that In this app, `LibCore.Web.SomethingWebRelated` and `LibCore.Extensions.StringFunctions` were not used, therefore tree-shaking should omit this from the final app.js, however I would expect to see (in rough pseudocode)...

```
__extends...
var Model...
var TrustModel (Model)...
var NumberFunctions...
var Program...
```

# Reason
Ordered dependency resolution would ensure that there were no JS runtime issues, where an object has been defined in the emitted source, but appears after it's use, and is therefore undefined.

Tree-shaking would omit objects that were not required by the final application, thus reducing the emitted JS size.

# Question
I'm not entirely sure whether this is already supported by TypeScript, or whether there are other build tools to facilitate this; either way, I'm open to any suggestions on how to solve this problem.

# Reference
http://stackoverflow.com/questions/31412557/typescript-compilation-causing-dependency-errors

**Comment by RyanCavanaugh** [comment]
Single-file-based compilations are increasingly rare and there are bundlers/tree-shakers capable of doing robust analysis against ES modules now.
