### ISSUE TITLE
ChangeRequest is very hard to implement for emacs

### ISSUE THREAD

**Issue by AndyMoreland** [microsoft/TypeScript#13696]
Hello!

td;dr: Could `ChangeRequest` (optionally?) take `startPosition` and `endPosition` rather than `line, offset, endLine, endOffset`? Alternately, could I implement a `ChangePositionRangeRequest` that has those as options? Computing `endLine` is hard for Emacs.

I work on an emacs <-> typescript language server project called "tsunami" that is based on the canonical one called "tide".

Unfortunately the way that "tide" works is by synchronizing buffer contents to the language server using the `ReloadCommand`. This is starting to suck performance-wise in my 100k loc typescript project with large files.

I'd like to implement the synchronization using the `ChangeRequest` command, but the `ChangeRequest` command requires a `((line, offset), (endLine, endOffset), insertText)` structure. Emacs only provides me with `(startPosition, endPosition, insertText)`. At first glance you might think that I can convert the emacs change event into a typescript change request, but it turns out that computing `endLine` is extremely difficult without access to the buffer state from before the change was made. 

For example, consider the case where the user deletes 10 lines of code: since we don't have access to the previous buffer text, if we convert `endPosition` to a line in the new text we'll be off by 10 lines.

Andy

**Comment by angelozerr** [comment]
See https://github.com/Microsoft/TypeScript/issues/5668

**Comment by AndyMoreland** [comment]
Thanks for the pointer -- I'll comment there!
