### ISSUE TITLE
Generic resolution within Readonly

### ISSUE THREAD

**Issue by ericanderson** [Microsoft/TypeScript#13692]
**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)

**Code**

```ts
class TBaseState {
  public value: string;
}

declare function globalFunc<T extends Readonly<TBaseState>>(item: T): void;


class MyComponent<TState extends TBaseState> {
  public state: Readonly<TState>;
  broken() {
    // typing of this.state is Readonly<TState>
    // this is not assignable to Readonly<TBase>
    globalFunc(this.state);

    // this is a horrible hack to fix the generics variance issue
    globalFunc(this.state as TState as Readonly<TBaseState>);
  }
}

class MyState extends TBaseState {
}

let component: MyComponent<MyState> = new MyComponent<MyState>();

// here the typing of component.state is Readonly<MyState>
// this is assignable to Readonly<TBase>
globalFunc(component.state);
```

**Expected behavior:**

The first call to `globalFunc` in `broken` should be able to infer that this.state is a superset of `readonly<TBaseState>`

**Actual behavior:**

Errors as marked above.

Raised by @patsissons in https://github.com/DefinitelyTyped/DefinitelyTyped/issues/14250

**Comment by patsissons** [comment]
the hack is a little less horrible as the following, which is still valid
```ts
globalFunc(this.state as TState);
```

**Comment by mhegazy** [comment]
should not it be?

```ts
declare function globalFunc<T extends TBaseState>(item: Readonly<T>): void;
```

**Comment by patsissons** [comment]
I think it could be either or, but I ran into a similar typing issue one way or the other. I believe I went with the first version because in my scenario there was a function delegate that was consuming the generic type.

**Comment by ericanderson** [comment]
Perhaps. I filed on behalf of @patsission

**Comment by mhegazy** [comment]
The error you are getting in the OP seems correct to me. I can not comment on the other code sample.

**Comment by patsissons** [comment]
so `Readonly<TState extends TBaseState>` should not be compatible with `T extends Readonly<TBaseState>`? It seems on the surface that the types should line up, but this is a bit of a complicated type intersection for me to visualize.

I will mention that you are correct that `globalFunc<T extends TBaseState>(item: Readonly<T>)` is more appropriate, I have adjusted my code to use that form instead.

**Comment by patsissons** [comment]
Here is an updated sample that (i think) better illustrates the typing issue. Or if you guys think there is no issue, it would just be nice to better understand why the typing system is rejecting the covariant conversion.

```ts
interface Base {
  // the typing only fails if we have a member defined in the base type
  val: string;
}

interface Derived extends Base {
}

function funcA<T extends Readonly<Base>>(item: T) {
  funcB(item);
}

function funcB<T extends Base>(item: Readonly<T>) {
  // this fails generic covariance
  // error TS2345: Argument of type 'Readonly<T>' is not assignable to parameter of type 'Readonly<Base>'.
  funcA(item);

  // this passes generic covariance
  funcA(item as T);
}

let rw = <Derived>{ val: 'test' };
let ro = <Readonly<Derived>>rw;

// rw typing has no problem with either function
funcA(rw);
funcB(rw);

// ro typing has no problem with either function
funcA(ro);
funcB(ro);
```

**Comment by mhegazy** [comment]
The error seems correct to me. the first `funcA` says it needs a type that is at least `Readonly<Base>`, that means that other properties that are not in `Base` can be writable. `funcB` has a stricter requirement, that all properties must be `readonly`. 

Again I think what you mean is:
```ts
function funcA<T extends Base>(item: Readonly<T>) {
  funcB(item);
}
```

**Comment by patsissons** [comment]
ah, so `T extends Readonly<Base>` means only the `Base` members must be readonly, and not the `T` members as well. I was reading the type constraint a little different and that threw me off i guess.

`funcA` was written as intended, as it results in the typing issue. But im guessing the resulting type constraint is a bit awkward and probably not desired.
