### ISSUE TITLE
inconsistencies with string literal values after always use literal types pr

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#13705]
nightly build jan 26

```typescript
interface Wrapped<T> {
    wrapped: T;
}
function wrap<T>(value: T): Wrapped<T> {
    return { wrapped: value };
}

const one = 'test'; // one is 'test'
const oneWrapped = wrap(one); // oneWrapped is Wrapped<string>

const another: 'test' = 'test'; // another is 'test'
const anotherWrapped = wrap(another); // anotherWrapped is Wrapped<'test'> <--- WHY?
```

is that how #10676 supposed to work?

**Comment by aleksey-bykov** [comment]
@ahejlsberg you might be interested

**Comment by mhegazy** [comment]
> is that how #10676 supposed to work?

yes. the inferred literal type is not widened in two cases, 1. it is present unwrapped in the output, e.g. identity function, 2. if the type parameter is constraint to its base type, e.g. `string`. explicit literal types are never widened.

**Comment by aleksey-bykov** [comment]
this is super counterintuitive

**Comment by mhegazy** [comment]
There is a long discussion in and in https://github.com/Microsoft/TypeScript/pull/10676, 
 https://github.com/Microsoft/TypeScript/issues/10898 and https://github.com/Microsoft/TypeScript/pull/11126 about why it does work this way. all other options were less intuitive overall.

**Comment by aleksey-bykov** [comment]
i missed #11126 somehow, closing
