### ISSUE TITLE
Include localized message files in the typescript npm package

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#13703]
In order to support https://github.com/Microsoft/vscode/issues/18634#issuecomment-273280003, we need to publish localized messages with the TS package.

**Comment by gcnew** [comment]
What will the process be for contributing changes that add or touch existing messages? Who will translate them?

**Comment by mhegazy** [comment]
We already have translated messages that are shipped as part of VS. I will need to figure out the process of getting these into the main TS npm package..
