### ISSUE TITLE
"trunc" is not defined on Math

### ISSUE THREAD

**Issue by rodrigomb81** [Microsoft/TypeScript#13714]
**TypeScript Version:**  2.1.5
**Code**

```ts
const k = Math.trunc(1.25)

// tsc: property 'trunc' does not exist on type 'Math'
```

**Expected behavior:**
`trunc` is defined

**Actual behavior:**
`trunc` is not defined

Should I go ahead and add it to [Math](https://github.com/Microsoft/TypeScript/blob/master/src/lib/es5.d.ts#L535)?

**Comment by mhegazy** [comment]
This is part of the ES2015 spec, use `--lib es2015` or `--lib dom,es2015`

**Comment by rodrigomb81** [comment]
Oh, I didn't know that. Thanks!
