### ISSUE TITLE
Interface 'LocalForageDriver' incorrectly extends interface 'LocalForageDbMethods' in windows but working in mac

### ISSUE THREAD

**Issue by sesn** [Microsoft/TypeScript#13716]
Typescript Error
Interface 'LocalForageDriver' incorrectly extends interface 'LocalForageDbMethods'. Types of property 'getItem' are incompatible. Type '(key: string, callback: (err: any, value: any) => void) => void' is not assignable to type '{ <T>(key: string): Promise<T>; <T>(key: string, callback: (err: any, value: T) => void): void; }'.

```
...ime-front/node_modules/@ionic/storage/node_modules/@types/localforage/index.d.ts
    _support: boolean | Promise<boolean>;
```

**Comment by mhegazy** [comment]
What version of the compiler are you using? do you have other definitions of `LocalForageDriver` or `LocalForageDbMethods` in your project?
