### ISSUE TITLE
Proposal: add type `PickPrototype`

### ISSUE THREAD

**Issue by KostyaTretyak** [Microsoft/TypeScript#13718]
**TypeScript Version:**  2.1.5

**Pseudocode** (for now it's not works)

```ts
type PickPrototype<T, K extends keyof T['prototype']> = {
    [P in K]: T['prototype'][P];
}
```

**Expected behavior:**

This feature will allow "picks" class prototype, and this will be resolve [problem like this](http://stackoverflow.com/q/41891022/1716560).

**Comment by gcnew** [comment]
The problem in your linked SO question is that `MyClass` is both a type and a value. What you want is to treat `MyClass` as a value and then take the type of that value. To do that use `typeof` as follows:

```ts
class MyClass
{
  one(c: boolean){};
  two(){};
}

declare const test: PickPrototype<typeof MyClass, 'one'>;

type PickPrototype<T extends { prototype: any }, K extends keyof T['prototype']> = {
    [P in K]: T['prototype'][P];
}
```

Note that you have to constrain `T` to something that has a `prototype` property.

**Comment by KostyaTretyak** [comment]
Wow! It works! Thank you very much. I could mark your answer on SO as resolved question (if you want).

But perhaps proposal of `PickPrototype` does not close, as well?

**Comment by gcnew** [comment]
You're welcome!

Thank you, but I don't have an active SO account. You can post it yourself if you wish.

I don't think the TS team can do much more about it. The typechecking is working as it is, maybe they could include it in the stdlib, but I don't see that happening as the usecases are rather niche.

PS: Nitzan Tomer's pieces of advice are really good.
