### ISSUE TITLE
Readonly option dose not have correct operation

### ISSUE THREAD

**Issue by captainhamid** [Microsoft/TypeScript#13725]
in ReadOnly property  it seems has a Ambiguity.

```
let a: number[] = [1, 2, 3, 4];
let b: number[] = [1, 2, 3, 4, 6];
let ro: ReadonlyArray<number> = a;
ro[10] = 12; // error!

ro = b; // is ok; not error
ro = a; // is ok; not error
```

**Comment by mhegazy** [comment]
`ReadonlyArray` talks about the content of the array. `ro` is a reference. if you want `ro` to be constant, declare it as:

```ts
const ro:  ReadonlyArray<number> = a;
```

**Comment by mhegazy** [comment]
In general StackOverflow is the right place for such questions. this issue tracker is for compiler/language bugs and suggestions.
