### ISSUE TITLE
[feature request] Configure what the default export is.

### ISSUE THREAD

**Issue by trusktr** [microsoft/TypeScript#13727]
**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)

2.1.5

**Code**

```js
// Foo.js
define([], function() {
  return class Foo {}
})
```

```ts
// Bar.ts
import Foo from './Foo'

class Bar extends Foo {} // error `Foo.default` is not defined.
```

**Expected behavior:**

After some type of configuration,

```js
// Foo.js
define([], function() {
  return class Foo {}
})
```

```ts
// Bar.ts
import Foo from './Foo'

class Bar extends Foo {} // no error at runtime!
```

**Actual behavior:**

One hack is to do

```ts
import * as Foo from './Foo'
```

That works at runtime, but it makes type errors at compile time. I wish there was a way to configure this, especially since these aren't real ES6 modules, we're just transpiling, and we're dealing with things like AMD modules that aren't part of the ES Loader spec anyways, so why not let us configure our behavior since the whole thing is a non-spec situation anyways?

**Comment by trusktr** [comment]
I have a feeling this new option would be similar to `allowSyntheticDefaultImports`, but it will also emit differently.

**Comment by RyanCavanaugh** [comment]
There doesn't seem to be enough demand to justify a new way to help people confuse themselves with modules 😜
