### ISSUE TITLE
Allow testing/coalescing of union type properties

### ISSUE THREAD

**Issue by errorx666** [Microsoft/TypeScript#13731]
**TypeScript Version:**  2.2.0-dev.20170127

**Code**
```ts
type Foo = { foo: 'foo'; }
type Bar = { bar: 'bar'; }

function example( foobar: Foo|Bar ): Foo&Bar {
    const foo = foobar.foo || 'foo',
        bar = foobar.bar || 'bar';
    return { foo, bar };
}
```

**Expected behavior:**
No error.

**Actual behavior:**
Property "foo" does not exist on type Bar.
Property "bar" does not exist on type Foo.

In this case, I'm aware of the possibility for `foo` or `bar` to be `undefined`, and handling it by using `||` to ensure a truthy value.  Similar in function to:

```ts
let foo: 'foo';
if( foobar.foo ) {
    foo = foobar.foo;
} else {
    foo = 'foo';
}
```

Which has the same errors, where I would expect testing for the property in that `if` block to activate type narrowing.  (See also: `'foo' in foo`, `typeof foo === 'string'`, et al.)

I may be expecting this to behave more like `foobar` was of type `Partial<Foo&Bar>`, which seems to behave better but is overly permissive.

**Comment by ahejlsberg** [comment]
It works if you declare `Foo` and `Bar` as follows:

```ts
type Foo = { foo: 'foo', bar: undefined }
type Bar = { foo: undefined, bar: 'bar' }
```

Unless each constituent contains a declaration of a particular property, the type system can't really provide any guarantees about that property. For example, with the original declarations, `Foo` can be assigned a type that contains a `bar` property of any type, and vice versa for `Bar`.
