### ISSUE TITLE
Possible strict null checks bug

### ISSUE THREAD

**Issue by silviogutierrez** [Microsoft/TypeScript#13733]
**TypeScript Version:**  2.1.5

**Code**

```ts
interface Thing {
    quantity: string;
}

export const processThing = (item: Thing) => {
}

let someItem: Thing & {quantity: string|null} = {} as any;

processThing(someItem);
```

**Expected behavior:**
I believe this should fail. An object of type `{quantity: string} & {quantity: string|null}` should not be accepted by a function expecting only `{quantity: string}`. Right?

**Actual behavior:**
The code compiles where I believe it should not.

**Comment by jeffreymorlan** [comment]
If someItem is both an `X` *and* a `Y`, then someItem is an `X`. (Perhaps you're thinking of `|` instead of `&`)

**Comment by ahejlsberg** [comment]
This is indeed working as intended. The type `string & (string | null)` is the same as `string | string & null`, and that type is assignable to `string` because every constituent contains the type `string`.

**Comment by silviogutierrez** [comment]
@ahejlsberg : thanks, that makes sense. Does this then mean it's not possible to make only a few fields in a type nullable? I know Partial<T> will do this for all fields.

Thanks again.
