### ISSUE TITLE
Warn against inconsistent behaviour in JS

### ISSUE THREAD

**Issue by wildeyes** [Microsoft/TypeScript#13737]
I just got burned by `Array.prototype.sort`, specifically the fact that when one returns zero from sort the behaviour of the function becomes different across browsers. 

From mdn:
> If compareFunction(a, b) returns 0, leave a and b unchanged with respect to each other, but sorted with respect to all different elements. Note: the ECMAscript standard does not guarantee this behaviour, and thus not all browsers (e.g. Mozilla versions dating back to at least 2003) respect this.

It would have been useful, if typescript could have warned me via inference that I am returning zero and that I shouldn't.

**Comment by RyanCavanaugh** [comment]
There's nothing wrong with returning 0 from your compare function; it just means that you consider those elements to be identical. It's hard to imagine how you would implement a comparator function for numbers that never returned 0, for example. It's really the *caller* of `sort` expecting a host-provided API to be deterministic in the presence of identical elements which is the problem, but it's not like the type system can "warn" you to read the documentation before making an assumption like that.
