### ISSUE TITLE
[possible bug] "include" glob-like patterns are excluding definition files if there are regular files with the same name

### ISSUE THREAD

**Issue by noomorph** [Microsoft/TypeScript#13739]
**TypeScript Versions:**  apparently, `2.0.x` and later, because I checked manually `2.0.10`, `2.1.5`, `2.2.0-dev.20170129` and both had this issue.

**Code**

See the repo: https://github.com/noomorph/typescript-include-bug and its [README](https://github.com/noomorph/typescript-include-bug/blob/master/README.md). 

**Expected behavior:**

Should compile OK using both configuration files.

**Actual behavior:**

In case of [tsconfig.include.bug.json](https://github.com/noomorph/typescript-include-bug/blob/master/tsconfig.include.bug.json) it skips [index.d.ts](https://github.com/noomorph/typescript-include-bug/blob/master/src/same/index.d.ts) and afterwards is unable [to find Greetings class](https://travis-ci.org/noomorph/typescript-include-bug#L164). [![Build Status](https://travis-ci.org/noomorph/typescript-include-bug.svg?branch=master)](https://travis-ci.org/noomorph/typescript-include-bug)

**Question**

@rbuckton, @andy-ms, Is this behavior absolutely intended?

If yes, what are the official recommendations for such cases? It is obviously not a documented behavior (examine http://www.typescriptlang.org/docs/handbook/tsconfig-json.html ). Could you explain why does this behavior exist, please?

If that is not something intended, do you think it is a bug or lack of configuration possibilities? I think I can work on a pull request, but I need more details for that.

Thanks in advance.

**Comment by noomorph** [comment]
@rbuckton, @andy-ms, any comments?

**Comment by mhegazy** [comment]
The compiler does not include files that can be possible outputs. e.g. if the input includes `index.ts`, then `index.d.ts` and `index.js` is excluded. 

We do not recommend having files that differ only in extension next to each other, that breaks assumptions the compiler makes about module resolution.

**Comment by noomorph** [comment]
@mhegazy, thanks! Does it make sense if I add this information to the handbook in a PR ?

**Comment by mhegazy** [comment]
sure. PRs welcomed.
