### ISSUE TITLE
Consider contextually typing class member functions by their base class/interface members

### ISSUE THREAD

**Issue by kns98** [Microsoft/TypeScript#1373]
here is my code

```ts
    export enum SortDir
    {
        Asc,
        Desc,
        Flip
    }

    export interface ISortInfo
    {
        getvalue(x: QuerySummary): any; //change to number|string in TypeScript 1.4
        order: SortDir;
        ordercalc?: number;
    }

    class SortByQueryId implements ISortInfo
    {
        getvalue = x => x.QueryId;
        order = SortDir.Flip;
    }
```

when I type "x." I expect to see the properties of QuerySummary but I do not. VS still thinks the type is 'any'

**Comment by jbrantly** [comment]
Can the scope of this be expanded to support member properties and static properties? See my comment in #1887 for an example.

**Comment by hdachev** [comment]
Adding an example of broken return value inference that results in a compiler error:

```
type Events = {
    [event: string]: () => void;
};

class A {
    getEvents(): Events {
        return null;
    }
}

class B extends A {
    getEvents() {
        return {
            'click': () => {

            }
        };
    }
}

// test.ts(12,7): error TS2415: Class 'B' incorrectly extends base class 'A'.
//   Types of property 'getEvents' are incompatible.
//     Type '() => { 'click': () => void; }' is not assignable to type '() => { [event: string]: () => void; }'.
//       Type '{ 'click': () => void; }' is not assignable to type '{ [event: string]: () => void; }'.
//         Index signature is missing in type '{ 'click': () => void; }'.
```

**Comment by omidkrad** [comment]
+1 vote for this. Related issues: #178 and #2073

I think it's not intuitive for contextual typing not to apply when overriding a class member. i.e. it should.

**Comment by j-walker23** [comment]
+1

**Comment by Coderah** [comment]
+1

**Comment by RyanCavanaugh** [comment]
Approved.

**Comment by sandersn** [comment]
This will be fixed by #6118.

**Comment by tinganho** [comment]
>Can the scope of this be expanded to support member properties and static properties? See my comment in #1887 for an example.

I'm also in support for extending it to base class members and statics.

**Comment by sandersn** [comment]
Unfortunately, we couldn't come up with a solution that was consistent and backward-compatible. See #6118 for details. I'm closing this for now.
