### ISSUE TITLE
Duplicate interface declaration - no error

### ISSUE THREAD

**Issue by GordonSmith** [Microsoft/TypeScript#13736]
TypeScript Version:  2.1.4

```ts
interface MyInterface {
  ...
}
interface MyInterface {  //  No error?!?
  ...
}
```

Expected behavior:  Syntax Error similar to duplicate class declaration

Actual behavior:  No Error

**Comment by DickvdBrink** [comment]
This is actually by design, see the documentation here: https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Declaration%20Merging.md#merging-interfaces

**Comment by GordonSmith** [comment]
I wasn't expecting that answer - closing invalid.
