### ISSUE TITLE
instanceof + extended native class

### ISSUE THREAD

**Issue by GordonSmith** [Microsoft/TypeScript#13735]
TypeScript Version:  2.1.4

```ts
class MyC extends Error {
    constructor(msg: string) {
        super(msg);
    }
}

let myC = new MyC("Hmmm");
let test3 = myC instanceof Error;   //TRUE
let test4 = myC instanceof MyC;     //!!!FALSE!!!
```

Expected behavior:  test4 should be TRUE

Actual behavior:  test4 is FALSE

**Comment by alitaheri** [comment]
Test nightly too. It might be fixed there.

**Comment by gcnew** [comment]
Don't extend natives, it does't work ([FAQ](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-doesnt-extending-built-ins-like-error-array-and-map-work)).

Also [use search](https://github.com/Microsoft/TypeScript/issues?utf8=%E2%9C%93&q=is%3Aissue%20extending%20native).

**Comment by GordonSmith** [comment]
That FAQ is out of date and that specific section is no longer valid since 1.6 - I did make it as far as:  https://github.com/Microsoft/TypeScript/issues/1168 - still my bad for not spotting this is a duplicate and I will close.

**Comment by gcnew** [comment]
Actually that specific section is fairly new. According to the [history](https://github.com/Microsoft/TypeScript/wiki/FAQ/_history) (see [5c207fc](https://github.com/Microsoft/TypeScript/wiki/FAQ/5c207fccc238990b875956b5bf943545b0a0be57)  it is 25 days old as of today. As such it is the most recent and preferred approach.
