### ISSUE TITLE
Errors (warnings?) hidden by tsc

### ISSUE THREAD

**Issue by martinheidegger** [Microsoft/TypeScript#13742]
In postgraphql the recent commits were run through the tsc without an issue, even ts-node works with the `"--disableWarnings"` flag, but if that flag is not set we receive an Type error which is weird because this error should be thrown by the tsc as well. Could it be that this error is somehow obfuscated when running tsc?

**TypeScript Version:**  2.1.5

**Code**

https://github.com/calebmer/postgraphql/commit/4da7b611d5530f7dcd6542166c9b6da3eba683f2

**Expected behavior:**

TSC and ts-node exit with the same error.

**Actual behavior:**

tsc finishes without error, ts-node exits with error 

```
TSError: ⨯ Unable to compile TypeScript
src/postgres/inventory/collection/PgCollectionKey.ts (60,19): Cannot find name 'ObjectType'. (2304)
src/postgres/inventory/collection/PgCollectionKey.ts (66,17): Parameter 'value' implicitly has an 'any' type. (7006)
```

**Comment by calebmer** [comment]
I can confirm this happens. It also looks like `tsc` passes in CI, so this might not be an environment problem.

**Comment by mhegazy** [comment]
@blakeembrey any thoughts?

**Comment by blakeembrey** [comment]
Not sure, the errors sound like they _should_ be happening, so `ts-node` output is correct while `tsc` is not. Have I read this right?

**Comment by calebmer** [comment]
@blakeembrey correct

**Comment by martinheidegger** [comment]
@mhegazy Where should this issue be posted? If its here not at the right place? (Why is it closed?)

**Comment by mhegazy** [comment]
https://github.com/TypeStrong/ts-node ?

**Comment by martinheidegger** [comment]
Created new issue here: https://github.com/TypeStrong/ts-node/issues/314

**Comment by blakeembrey** [comment]
@mhegazy did you look into this at all after my last comment? The errors were correct but tsc wasn't showing them.

**Comment by mhegazy** [comment]
@martinheidegger is this still an issue? can you give TS 2.3 a try? i am getting a lot of compile errors running on postgraphql/postgraphql@4da7b61

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
