### ISSUE TITLE
Feature request: __DATE__, __TIME__ etc. like C/C++ macro

### ISSUE THREAD

**Issue by a8775** [Microsoft/TypeScript#13748]
As TS is a compiler it's possible to insert compile time value for date/time similar to the `__DATE__` C/C++macro. 

I was looking on the issue: https://github.com/Microsoft/TypeScript/issues/4892
and it could be implemented in one of the proposed way.

The macro `__DATE__`, `__TIME__` I'm find the most useful but can be extend for `__FILE__`, `__LINE__` etc. 

The solution I use now is gulp task, but it could be nice build-in feature in th TS language :)

**Comment by Strate** [comment]
I think it's better to use post-processor, such as babel

**Comment by a8775** [comment]
This is what actually I do with `gulp`, but this is not always the optimal solution.
In fact I never used babel as macro processing and it sounds interesting I will give a try next time :)

Anyway, I think the easy solution borrowed from the old **"C"** could have its place ;)

**Comment by aluanhaddad** [comment]
Adding macros would introduce substantial complexity and could well conflict with future versions of ECMAScript. also, while simple use cases such as yours makes sense it could well get out of hand. I think this is something that is better done by a build tool such as the already mentioned gulp, jspm, or webpack

**Comment by mhegazy** [comment]
As @aluanhaddad noted, expression level features are only added when absolutely necessary, e.g. type assertion, to avoid possible conflict with feature ES direction. I would recommend either using variables, e.g. `declare var __DATE__: Date;` and/or using a post build tool to replace the references with the intended value.
