### ISSUE TITLE
Empty object is not assignable to all-optional mapped type when used with generic inside class

### ISSUE THREAD

**Issue by Strate** [Microsoft/TypeScript#13747]
**TypeScript Version:**  2.1.1 (http://www.typescriptlang.org/play/index.html)

**Code**

```ts
class Form<T> {
    private values: {[P in keyof T]?: T[P]} = {}
}
```

**Expected behavior:**
No compile error

**Actual behavior:**
Type '{}' is not assignable to '{[P in keyof T]?: T[P]}'

**Comment by ahejlsberg** [comment]
I agree, it seems meaningful to support this.
