### ISSUE TITLE
Using `"module": "system"` breaks embedded definitions

### ISSUE THREAD

**Issue by kube** [Microsoft/TypeScript#13745]
**TypeScript Version:**  nightly (2.2.0-dev.20170127)

I use a bunch of packages that embed definitions :
Two of my own, [Monolite](https://github.com/kube/monolite) and [When-Switch](https://github.com/kube/when-switch), but also [TypeStyle](https://github.com/typestyle/typestyle).

**Code**
With `"module": "commonjs"` in my package.json, everything works fine, TypeScript finds definitions and does correct completion and linting.

But once I change for `"module": "system"`, none of these packages work anymore.

```ts
import { style } from 'typestyle'
// [ts] Cannot find module 'typestyle'

import when from 'when-switch'
// [ts] Cannot find module 'when-switch'

import { set } from 'monolite'
// [ts] Cannot find module 'monolite'

```

**Comment by vladima** [comment]
can you try to set `moduleResolution: node` to see if it resolves the issue? When target module kind is `commonjs` compiler uses `node` module resolution strategy and for other cases it uses `classic` scheme. For more details please see [this page](http://www.typescriptlang.org/docs/handbook/module-resolution.html)

**Comment by kube** [comment]
Thanks, it works now.
Sorry for the issue creation.
