### ISSUE TITLE
Assignment issue on constrained type parameter

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#13740]
I think this was working before for me:
```ts
interface BaseState {
    a: string;
}
class Some<P, S extends BaseState> extends React.Component<P, S> {
    state = { a: '' };// Error { a: '' } is not assignable to S

    componentDidMount() {
        this.setState({ a: '' }); // Error { a: '' } is not assignable to S
    }
}
```

**Comment by ahejlsberg** [comment]
If so it must have been a bug, it is definitely working as intended. A type parameter constrained to `BaseState` is assignable to `BaseState`, but not the other way around. This makes sense because an actual type argument may be a further derived type.

**Comment by tinganho** [comment]
Hmm probably I that was confused here.
