### ISSUE TITLE
ObjectConstructor does not declare more specific call signature overloads

### ISSUE THREAD

**Issue by kpreisser** [Microsoft/TypeScript#13741]
**TypeScript Version:**  master

Hi,

currently, in [lib.es5.d.ts](https://github.com/Microsoft/TypeScript/blob/aeeff28fd6e7a6b599f8eff084008ac9bdc36d03/src/lib/es5.d.ts#L110), the interface `ObjectConstructor` defines only one call signature taking a value argument and returning `any`:
```ts
interface ObjectConstructor {
    new (value?: any): Object;
    (): any;
    (value: any): any;
    // (...)
}
```
whereas I expected overloads that return object wrappers from primitive types:
```ts
interface ObjectConstructor {
    new (value?: any): Object;
    (): Object;
    (value: boolean): Boolean;
    (value: number): Number;
    (value: string): String;
    (value: null): Object;
    (value: void): Object;
    <T>(value: T): T;
    // (...)
}
// lib.es2015.core.d.ts
interface ObjectConstructor {
    (value: symbol): Symbol;
}
```

Is there a specific reason for the `any` parameter and return type, or can this be changed like in the above example (though I don't know if the `null`, `void` overloads would be necessary)?
Thanks!

**Comment by mhegazy** [comment]
Using boxed types is not recommended in general. `(v:any): any` already coves these scenarios.

**Comment by kpreisser** [comment]
Hi @mhegazy,
I understand that boxed types should normally not be used. However, I would think specifying explicit types is generally preferable over using the `any` type (and it seems a bit inconsistent, since `NumberConstructor`, `StringConstructor` and `BooleanConstructor` also contain constructor signatures that return boxed types).
This also means that when calling `Object(...)` using an object type, I still get `any` back.
Thanks!

**Comment by mhegazy** [comment]
do you have a scenario that you can share?

**Comment by kpreisser** [comment]
Hi @mhegazy,
no, I don't have a specific scenario; I was just looking for the reasoning behing specifying the `any` type there.
Thanks!
