### ISSUE TITLE
Expose transformations as a public API

### ISSUE THREAD

**Issue by rbuckton** [Microsoft/TypeScript#13764]
Expose the `transformFiles` and `getTransformers` functions as a public API.

**Comment by jwbay** [comment]
@rbuckton Before I get too excited about this set of issues/PRs, can you comment on whether they (collectively) enable 'codemods' on TypeScript source code, ala https://github.com/facebook/jscodeshift? To be clear, I think the critical thing is to be able to ingest some file `foo.ts`, parse it into an AST, transform it, then emit it back to source text, all without touching other files (other than maybe tsconfig.json) or involving typechecking.

**Comment by dherges** [comment]
Hi @rbuckton,

is there documentation on the transformations API? (#13940)

Here is a blog post http://blog.scottlogic.com/2017/05/02/typescript-compiler-api-revisited.html

My use case is inlining external resources into TypeScript from decorator metadata (more specific: Angular components):

Source Code:
```ts
@Component({
  templateUrl: './foo.component.html'
})
export class FooComponent {}
```

Expected transformed result will be similar to:
```ts
@Component({
  template: '<h1>Content from foo.component.html here...</h1>'
})
export class FooComponent {}
```

(and then compiled to es2015 syntax / es2015 module format)

**Comment by geovanisouza92** [comment]
I'm looking for inlining things too (XML in my case).

Currently I'm using webpack loaders (have used babel-preval before, but it doesn't work with TS).
