### ISSUE TITLE
Suggestion: keyof EnumType should return the enum keys/values

### ISSUE THREAD

**Issue by Knagis** [Microsoft/TypeScript#13775]
Currently `keyof EnumType` is the same as `keyof 1`.

**Code**

```
enum Foo {
    foo1 = 1
}

let a: keyof Foo;
a = "foo1"; // fails
a = "toExponential"; // works
```

**Expected behavior:**

`a = "foo1";` would work.

**Use case**

I wanted to use the `keyof` for the public API of our library:

```
class Api {
  public method(param: Enum | keyof Enum) {
    if (typeof param === "string") {
      param = Enum[param];
    }
    // ...
  }
}
```

**Question**

Presumably, to be correct, `keyof Foo` should be `"foo1" | 1`, in the use case above it would still fit very well.

**Comment by ahejlsberg** [comment]
An enum declaration actually introduces two meanings for the identifier: One as a *type* (which is always a subtype of `number`) and one as a *value* (the enum object that you can reference in expressions). When you ask for `keyof Foo` you're going to get a union of the literal property names of `number`. Here it sounds like you want the property names of the enum object, so you need to use `keyof typeof Foo`. In your example that gives you the literal type `"foo1"`.

**Comment by Knagis** [comment]
Thank you!
