### ISSUE TITLE
Non-exported entities are available from ambient namespace declaration 

### ISSUE THREAD

**Issue by ikokostya** [Microsoft/TypeScript#13770]
**TypeScript Version:**  2.2.0-dev.20170128

**Code**

`a.d.ts`

```ts
declare namespace ns {
    interface Private {}
}
export = ns;
```

`b.ts`
```ts
import * as ns from './a';

let x: ns.Private = {};
```

**Expected behavior:**

Error: `Namespace 'ns' has no exported member 'Private'.`

**Actual behavior:**

No errors.

**Comment by mhegazy** [comment]
All declarations in an ambient namespace are exported by default. you can either not include it, or move it outside your namespace, e.g.:
```ts
 interface Private {}
declare namespace ns {
    interface Public{ }
}
export = ns;
```

**Comment by ikokostya** [comment]
I often see `export` keyword inside ambient namespace in declarations from `DefinitelyTyped` (e.g. for Node.js: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/node/v6/index.d.ts#L255). 
Amusingly that all this declaration are redundant.

I expected that ambient namespace will be exported like usual namespace. Compilation fails if change `a.d.ts` to `a.ts` in example above

```ts
namespace ns {
    interface Public{ }
}
export = ns;
```

Could you please explain why ambient declarations are exported differently? Can't found answer in documentation and specification.

**Comment by mhegazy** [comment]
> Could you please explain why ambient declarations are exported differently? Can't found answer in documentation and specification.

the assumption is if it is in a declaration file it is meant to be public. The compiler does not generate these unless they are public as well;  the declaration emitter will give you an error if one of your declarations depends on a non-exported declaration.

the result is every declaration in an ambient namespace has to start with `export`. that seemed like a lot of repetition, and thus elided. the same applies to the use of `declare` keywords inside namespaces.

I do not think this is documented explicitly anywhere. feel free to send a PR to update https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Namespaces.md

For completeness, this also applies to modules, with the exception of modules containing `export { x }` or `export default ..`.

**Comment by ikokostya** [comment]
Thanks.
