### ISSUE TITLE
entry point named with .js

### ISSUE THREAD

**Issue by zzzgit** [Microsoft/TypeScript#13777]
![image](https://cloud.githubusercontent.com/assets/1060733/22460052/38ab70de-e7de-11e6-80fe-6b4aa6820fe5.png)

why can't i name the entry point file with a the exension .js

**Comment by DanielRosenwasser** [comment]
Do you have `--allowJs` turned on?

**Comment by mhegazy** [comment]
Curious, why you have no .ts files in your sources?
