### ISSUE TITLE
Proposal: Vertical bar before discriminated unions

### ISSUE THREAD

**Issue by ErikCupal** [Microsoft/TypeScript#13781]
If we want to align discriminated unions vertically, we can write them like this

```ts
type Action =
    Increment |
    Decrement |
    Reset

// or

type Action =
    Increment 
    | Decrement 
    | Reset
```

It doesn't look bad, but it can be quite annoying to check if the bars are at right places when you want to add new types at the beginning or at the end or when you want to reorginize them - basically the same issue as [trailing commas](https://github.com/tc39/proposal-trailing-function-commas).

What I would love to have is this:

```ts
type Action =
    | Increment 
    | Decrement 
    | Reset
```

It is easier to read and easier to maintain.

**Comment by normalser** [comment]
https://github.com/Microsoft/TypeScript/pull/12386

**Comment by ErikCupal** [comment]
Ah, sorry, I'm closing it
