### ISSUE TITLE
[feature request] Runtime type checking when possible.

### ISSUE THREAD

**Issue by trusktr** [Microsoft/TypeScript#13790]
**TypeScript Version:**  2.1.5

**Code**

N/A

**Expected behavior:**

To see runtime implementation of things that are possible to check. For example, if I write the following typescript:

```ts
function log(msg:string) {
    console.log(msg)
}

log()
```

it'd be nice to have an option so that compiled output would be like

```js
function log(msg) {
    if (typeof msg != 'string') throw new TypeError('Argument msg expected to be a string.')
    console.log(msg)
}

log()
```

**Actual behavior:**

TypeScript doesn't do this.

The rationale is that an app might import libraries made with TypeScript, but that app might be plain JS with no type checking. It'd be nice for the app to benefit from type checking when possible.

There's overhead with runtime type checking, but that's why this is an option. I think it would nice for the library author to be able to weigh the productivity gains vs performance cost, and choose to enable the option or not.

**Comment by trusktr** [comment]
Similar request: https://github.com/Microsoft/TypeScript/issues/1573

**Comment by mhegazy** [comment]
How is this a different request from #1573? and if not, why do we need two issues?
