### ISSUE TITLE
barEqual/plusEqual should always work even if `strictNullChecks` is `true`

### ISSUE THREAD

**Issue by gdh1995** [Microsoft/TypeScript#13799]
**TypeScript Version:**  2.2.0 / master

**Code**

```ts
// a.ts
function test(num?: number, str?: string) {
  num |= 0; // force `num` to be a valid number
  str += ""; // force `str` to be a valid string
  let output += num + ' / ' + str.substring(0, 10);
  console.log(output);
}
test();

// tsconfig.json
{
  "compilerOptions": {
    "strictNullChecks": true
  }
}
```

**Expected behavior:**
`tsc` compiles the project without any error.

**Actual behavior:**
It reports:
```
a.ts(3,3): error TS2532: Object is possibly 'undefined'.
a.ts(5,30): error TS2532: Object is possibly 'undefined'.
```

**Intention**
I want to use some fast path to ensure the value of arguments are valid, which mainly includes `|= 0`, `+= ""`. but TypeScript only accept this usage if `strictNullChecks` is `false`. Considering that `+=` and `|=` are both valid common JavaScript operator and they don't make any ambiguities, the usage above should be supported whatever `strictNullChecks` is.

This refers to #13751.

**Comment by HerringtonDarkholme** [comment]
The second case `strOrUndefined += ""` does not make sense to me.
I do want an empty string, not something like `"undefined"`.

If I do need a literal "undefined", I prefer use the `strOrUndefined!` to tell readers that I do it intentionally.

**Comment by mhegazy** [comment]
Adding special type "meanings" to some operators is not something we would be interested in pursuing at the time being.

**Comment by gdh1995** [comment]
Well, but `a |= 0` is very useful, because `null | 0` is `0`, unless `a` needs to be larger than INT_MAX.
