### ISSUE TITLE
Computed property in a class

### ISSUE THREAD

**Issue by juanluispaz** [Microsoft/TypeScript#13794]
**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)

**Code**

```ts
declare class Person {
    name: string,
    age: number
}

declare class Test {
    [K in keyof Person]: Person[K]; // Error: A computed property must be of type...
}
```

**Expected behavior:**
It should work like in a type declaration

**Actual behavior:**
It doesn't allow use computed properties in a class

**Comment by mhegazy** [comment]
Mapped types are not allowed in classes. only in types. Not sure i understand what you are trying to do, but you can define a class as a constructor function if you need to.
