### ISSUE TITLE
[request] allow namespaces to become types

### ISSUE THREAD

**Issue by devdoomari** [Microsoft/TypeScript#13809]
How about allowing namespaces to become types?

e.g.)

```typescript
// some declaration file I can't touch
declare module monaco {   //this is monaco, not 'monaco'. so it's a namespace.
   ...
}

type _MonacoNamespaceType = ::monaco; // or any other syntax is fine.
```
--------------------------------
background: I'm having problems trying to write d.ts file for react-monaco-editor.

monaco-editor's typescript definition has everything in ts namespaces, so I'm stuck trying to get 'monaco' as a type.

here's the definition file I'm working on:
```typescript
/// <reference path="../../node_modules/monaco-editor/monaco.d.ts" />


declare module 'react-monaco-editor' {
  import { Component } from 'react';
  export type ReactMonacoEditorProps = {
    width: string,
    height: string,
    language: string,
    options: monaco.editor.IEditorOptions,
    editorDidMount?: (editor: monaco.editor.ICodeEditor, monaco: any) => any,
  };
  import test = monaco;
  export type ICodeEditor = monaco.editor.ICodeEditor;
  export default class ReactMonacoEditor
      extends Component<ReactMonacoEditorProps, void> { }
}
```
As you can see on **editorDidMount?: (editor: monaco.editor.ICodeEditor, monaco: any) => any,**
I couldn't give the 'monaco' type on monaco as 'monaco' namespace cannot be a type.

**Comment by mhegazy** [comment]
`typeof monaco` ?

**Comment by devdoomari** [comment]
@mhegazy oh so there was already a way! Thanks : )

**Comment by devdoomari** [comment]
.
