### ISSUE TITLE
Configure JS / TS Project via package.json

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#13800]
_From @tivac on October 14, 2016 22:3_

I don't love needing to add yet another metadata file to my projects. But I love the improved `vscode` intellisense from adding a `jsconfig.json` file to my projects.

Has there been any discussion of allowing `vscode` configuration via `package.json`, much like [ESLint](eslint.org/docs/user-guide/configuring#configuring-eslint)?

Something like this:

``` js
{
  "name": "package-name",
  "version": "1.0.0",
  "description": "...",
  "license": "MIT",
  "dependencies": {
    // ...
  },
  "vscodeConfig": {
    "compilerOptions": {
      "target": "ES6",
      "module": "commonjs"
    }
  }
}
```

That way no extra editor-specific file is required to be added to every single project that you want the benefits of configuring `vscode`.

_Copied from original issue: Microsoft/vscode#13786_

**Comment by mjbvz** [comment]
_From @waderyan on October 24, 2016 21:47_

@tivac thank you for opening this issue. We are evaluating this experience right now and appreciate your insight! Stay tuned.

**Comment by mjbvz** [comment]
_From @waderyan on December 9, 2016 23:13_

@bowdenk7 I'm thinking this feature request might more sense in TS repo. What are your thoughts? Is this something on your radar? I searched TS issues and couldn't find it.

**Comment by mjbvz** [comment]
I do not believe that this is vscode specific. The feature request would be to have TypeScript pick up `tsconfig.json` or `jsconfig.json` settings from the `package.json` file instead of their own file

**Comment by mhegazy** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/6590

**Comment by mjbvz** [comment]
@mhegazy Thanks. Closing as a duplicate
