### ISSUE TITLE
Proposal: 'always' type

### ISSUE THREAD

**Issue by pelotom** [Microsoft/TypeScript#13804]
We have a `never` type representing the bottom of the type lattice... what about having a built-in corresponding "top" type? Essentially:

```ts
type always = {} | void | null
```

A variable of type `always` can be assigned any value, but nothing is known about it aside from the fact that it exists. `any` doesn't fit the bill, because we can assign an `any` to any other type and access arbitrary properties on it (it behaves like both `never` and `always` depending on the context).

**Comment by RyanCavanaugh** [comment]
The suggestion is simply to add that line to lib.d.ts?

**Comment by pelotom** [comment]
It would be ideal if it was built-in rather than a type alias, so that it didn't get expanded to `{} | undefined | null` everywhere, but failing that a type alias in the lib would be fine.

**Comment by isiahmeadows** [comment]
This sounds like a dupe of #10715, just with a different name. `unknown` there and `always` here are both [top types](https://en.wikipedia.org/wiki/Top_type).

**Comment by RyanCavanaugh** [comment]
Some elaboration of the desired use of this type would be helpful. What's it for? Why would I use it? What would the documentation say about it?

**Comment by pelotom** [comment]
@RyanCavanaugh #10715 has a good detailed description of why this is desirable.

**Comment by RyanCavanaugh** [comment]
Is this a duplicate then?

**Comment by pelotom** [comment]
Yes, modulo a suggestion of what to call this type.
