### ISSUE TITLE
Returning Promise<any> from Promise<T>.then results in Promise<T> not Promise<any>

### ISSUE THREAD

**Issue by RubenSlabbert** [Microsoft/TypeScript#13808]
**TypeScript Version:**  2.1.5

**Code**

```ts
// Example
const a: Promise<number> = Promise.resolve(2);
const b = a.then(x => Promise.resolve(x.toString() as any));

const x = await b; // x: Promise<number> should be Promise<any>

// In practice
// fetch returns Promise<ResponseInterface>
const response = fetch('url');

// body.json returns Promise<any>
const doStuff = fetch.then(b => b.json());

const data = await doStuff;
data.jsonField // Error: jsonField does not exist on type ResponseInterface
```

**Expected behavior:**
When `.then` on a promise returns a `Promise<any>` the previous generic type `T` in the promise will be kept instead of it being set to `any`.

**Actual behavior:**
Returning a `Promise<any>` from a `.then` method should return a `Promise<any>` instead of `Promise<T>`.

I was able to momentarily fix the code by editing the `lib.es205.promise.d.ts` file to move `then` (line 25) without a type parameter to be after `then<TResult>`(line 41). Running `npm test` in the TypeScript afterwards gave me linting errors on the compiler source, but all the tests passed. I'd be happy to make a pull request if that is sufficient.

**Comment by mhegazy** [comment]
Should be fixed in latest.
