### ISSUE TITLE
Mixin classes don't allow constructors of 'object' types

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#13805]
```ts

type Constructor<T> = new (...args: any[]) => T;

export const Timestamped = <CT extends Constructor<object>>(Base: CT) => {
    return class extends Base {
        timestamp = new Date();
    };
}
```

Expected: It just works
Actual: It doesn't work - I get an error on `Base` in the extends clause stating that `object` is not a class or interface type.

This makes little sense given that this is a better restriction than `{}`.

**Comment by DanielRosenwasser** [comment]
@ahejlsberg can you merge this into `release-2.2`?

**Comment by ahejlsberg** [comment]
@DanielRosenwasser Can you get @mhegazy or someone else to do it?

**Comment by mhegazy** [comment]
it is already merged.
