### ISSUE TITLE
Dot in string literal affects completion

### ISSUE THREAD

**Issue by NoelAbrahams** [microsoft/TypeScript#13812]
**TypeScript Version:**  2.1.5.0

**Code**

```ts

type Foo = 'my.foo' | 'my.bar';

function bar(foo: Foo) { }

bar('my.my.bar'); // result of hitting tab after 'my.b'

```

**Expected behavior:**

`bar('my.bar');`

**Actual behavior:**

`bar('my.my.bar');`

**Comment by jakebailey** [comment]
This has been fixed since TS 3.9 in #37490 when replacement spans were added (which are designed specifically to fix these kinds of problems).
