### ISSUE TITLE
Proposal: Type Alias Destructuring

### ISSUE THREAD

**Issue by cchamberlain** [Microsoft/TypeScript#13816]
In the instance that I have a nested generated namespaces it would be nice to be able to deconstruct some of the namespaces members to type aliases like so:

**App.d.ts**

```ts
namespace App.Web.Dtos {
  export interface Foo {
    bar: string;
  }

  export type Bar = "foo" | "bar";
}
```

**App.ts**

```ts
type { Foo, Bar } = App.Web.Dtos;

const foo: Foo = { bar: "foo" };
```

The alternative to this that I've been doing is like so:

```ts
type Foo = App.Web.Dtos.Foo;
type Bar = App.Web.Dtos.Bar;

// OR

import Foo = App.Web.Dtos.Foo;
import Bar = App.Web.Dtos.Bar;
```

To my knowledge this shouldn't conflict with current type alias assignment. Pros of this feature would be a heavy cut in the coupling of files types to their concrete usages, and would allow some a great reduction in redundant namespaces written throughout a file. I would alternatively be open to an import namespace syntax but that seems like it might be more prone to overlap with existing features.

**Comment by mhegazy** [comment]
duplicate of https://github.com/Microsoft/TypeScript/issues/13135?

**Comment by cchamberlain** [comment]
@mhegazy - Thanks did some searching around but didn't notice the other thread. Closing this one.
