### ISSUE TITLE
`this` not correctly captured when using it inside a lambda that is a super constructor parameter (still on 2.1.5)

### ISSUE THREAD

**Issue by RafaelSalguero** [Microsoft/TypeScript#13827]
Duplicated from #12889, still not fixed

**TypeScript Version:**  2.1.5

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
class A {
    constructor(func: () => void) {
        func();
    }
}

class B extends A {
    constructor() {
        super(() => console.log(this.name));
    }
    public name : string;
}

//An empty console log should be written:
B();
```

**Expected behavior:**
(this works on 2.0.xxx)
```ts
//The super call line should translate to:
 var _this = this;
_super.call(this, function () { return console.log(_this.name); });
```
**Actual behavior:**
```ts
//Variable this is not available on the lambda, this results on a referenceError, this is not defined
//exception at runtime
var _this = _super.call(this, function () { return console.log(_this.name); }) || this;
```

**Comment by mhegazy** [comment]
This works as expected. `this` should not be used before the `super` contractor is done. this is an error in ES6. 
![image](https://cloud.githubusercontent.com/assets/8000722/22537816/841314c0-e8c2-11e6-8f50-5a59c01d11fe.png)

The compiler can not know if the function will be immediately invoked, so it errors on the side of being permissive, but the runtime error is not something we can fix.
