### ISSUE TITLE
Flag to enable runtime assertions to confirm compile time type checking

### ISSUE THREAD

**Issue by nbransby** [Microsoft/TypeScript#13835]
Feature Suggestion: (Has this been considered or even implemented already?)

Flag to enable runtime assertions to confirm compile time type checking - strongly typed languages like Java do this and I think it would be very useful for debugging an issue to validate the assumptions held in the ts files. On a codebase consisting of 100% typescript this is not really an issue but I don't believe any project is 100% TypeScript when you factor in its dependencies. When it comes to dependencies (even node/browser apis) it's in declarations file we trust. One little mistake in these user contributed files and our compile time checks only help to mask a bug (even more a problem now with strict null checks).

As a sense check - first thing I would like to do when reproducing a bug would be to enable this flag and prove its not a type declaration issue

**Comment by RyanCavanaugh** [comment]
> (Has this been considered or even implemented already?)

![image](https://cloud.githubusercontent.com/assets/6685088/22558532/e3aff46a-e922-11e6-8dc5-4d79930a0c9a.png)

#1573

**Comment by nbransby** [comment]
Oops, already a hot topic I see :)
