### ISSUE TITLE
How to deal with homemade libraries

### ISSUE THREAD

**Issue by sternbel** [Microsoft/TypeScript#13837]
Hi all,

I know that I should probably post my questions to http://stackoverflow.com/questions/tagged/typescript.
However this is something related to the documentation of Typescript and I'm not sure this module topic is covered properly.

So basically I have built two libraries using Typescript 2.2 and Webpack 2, called A and B. B depends on A. Both libraries are intended to be used in a browser to display some graphics using d3.

**A/tsconfig.json**
```json
"module": "commonjs",
"target": "es5"
```

**A/package.json**
```javascript
"scripts": {
   "build": "webpack --config webpack.config.js --progress --display-error-details"
},
"dependencies": {
    "d3": "latest",
    "@types/jasmine": "latest",
    "@types/d3": "latest"
  }
```

**A/webpack.config.js**
```javascript
var webpack = require("webpack");
var LoaderOptionsPlugin = require("webpack/lib/LoaderOptionsPlugin");

module.exports = {
    entry: {
        "A": "./src/api.ts",
        "A.min": "./src/api.ts"
    },
    output: {
        path: "./dist",
        filename: "[name].js",
        library: ["A"],
        libraryTarget: "umd",
        umdNamedDefine: true
    },
    devtool: "source-map",
    resolve: {
        extensions: [".ts", ".js"]
    },
    plugins: [
        new webpack.optimize.UglifyJsPlugin({
            include: /\.min\.js$/,
            minimize: true,
            compress: {
                warnings: false
            }
        }),
        new LoaderOptionsPlugin({
            debug: false,
            options: {
                resolve: {}
            }
        })
    ],
    module: {
        rules: [
            {
                test: /\.tsx?$/,
                exclude: /node_modules/,
                loader: "ts-loader"
            },
            {
                test: /\.js$/,
                loader: "source-map-loader"
            }
        ]
    }
};
```

**A/dist/A.d.ts**

```typescript
import {Selection} from "d3-selection";
declare module A{
  export class SvgView extends View {
    public constructor(svgContext: Selection<any, any, any, any>);
    public draw();
  }
}
```

**B/src/B.ts**
```typescript
import {SvgView} from "../A";

export class B {
   public draw(context) {
      new A.SvgView(context).draw();
   }
}
```

**B** config files are pretty much the same.

**testB.html** utilizes A and B libraires as follows:

```html
<head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/4.1.1/d3.min.js"></script>
</head>
<body>
<link rel="stylesheet" href="../css/A.css"/>
<link rel="stylesheet" href="../css/B.css"/>
<script src="../js/A.js"></script>
<script src="../dist/B.js"></script>

<script>
  //...
  new B.B().draw(context);
</script>
</body>
```

Here are my questions:
1. What is the recommended module format in my case (AMD, UMD, commonjs, es2015, ...), knowing that I have to support IE11 and Chrome latest version? (I would like to avoid using tricks like systemjs, and use only <script...> in my html file)
2. In tsconfig.json I'm using commonjs and in Webpack umd modules. Is it ok like that?
2. Is there some documentation somewhere explaining when to use what module with which scenarii?
3. B is importing SvgView from A using `import {SvgView} from "../A";`. A.d.ts and A.js are both located one level up (../) to make webpack happy. Compiling directly with tsc requires only A.d.ts but webpack (I guess it's ts-loader actually) also requires A.js.
3.1 Why webpack/ts-loader requires A.js on top of A.d.ts?
3.2 In my html file I'm using `<script src="../js/A.js"></script>` which of course does not because (I guess) `import {SvgView} from "../A";` does not work properly because of the path. How to fix this?

**Comment by mhegazy** [comment]
> 1. What is the recommended module format in my case (AMD, UMD, commonjs, es2015, ...), knowing that I have to support IE11 and Chrome latest version? (I would like to avoid using tricks like systemjs, and use only <script...> in my html file)

If you are working with non-trivial amount code, then you should be using modules. You can not assume the existance of a module system in your browser, so you need to use a module loader and /or a bundler like webpack, browserify, etc..

> 2. In tsconfig.json I'm using commonjs and in Webpack umd modules. Is it ok like that?

sure.

> 3. Is there some documentation somewhere explaining when to use what module with which scenarii?

Modules is not a TypeScript -specific concept. any JS module loader you chose should with TS.

> 4. B is importing SvgView from A using import {SvgView} from "../A";. A.d.ts and A.js are both located one level up (../) to make webpack happy. Compiling directly with tsc requires only A.d.ts but webpack (I guess it's ts-loader actually) also requires A.js.
3.1 Why webpack/ts-loader requires A.js on top of A.d.ts?
3.2 In my html file I'm using <script src="../js/A.js"></script> which of course does not because (I guess) import {SvgView} from "../A"; does not work properly because of the path. How to fix this?

I do not have enough info about the loader implementation to be able to help here.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
