### ISSUE TITLE
Invoking methods on the type casted variable throws exception

### ISSUE THREAD

**Issue by thekalinga** [Microsoft/TypeScript#13838]
**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)

**Code**

```ts
class Animal {
    protected _name: string;
    constructor(name: string) {
        this._name = name;
    }
}

class AnimalInternal extends Animal {
    get name(): string {
        return this._name;
    }

    getName(): string {
        return this._name;
    }
}

let animal = new Animal("Sammy the Python");
let animalInternal: AnimalInternal = <AnimalInternal>animal;
console.log(animalInternal.name); // <- becomes undefined
console.log(animalInternal.getName());  // <- throws exception
```

**Expected behavior:**

The method invocation should succeed

**Actual behavior:**

Exception being thrown

**Comment by NN---** [comment]
Why should it ?
Animal doesn't have 'getName'.
Did you mean the opposite inheritance where Animal extends AnimalInternal ?

**Comment by RyanCavanaugh** [comment]
Type assertions do not change runtime behavior.

**Comment by thekalinga** [comment]
If this is not going to work at runtime, the compiler should throw error in this scenario, rather than allowing it fail at runtime.

**Comment by RyanCavanaugh** [comment]
The entire point of a type assertion is that you're asserting, yourself, that something is of a specific type. You can get the behavior you desire by simply not using the type assertion in the first place.
