### ISSUE TITLE
strictNullChecks does not respect excludes

### ISSUE THREAD

**Issue by yavuzmester** [Microsoft/TypeScript#13833]
**TypeScript Version:**  2.1.5

**Code**
```
{
    "version": "2.1.5",
    "compilerOptions": {
        "module": "commonjs",
        "lib": ["es2015", "es2016", "dom"],
        "target": "es5",
        "jsx": "react",
        "skipLibCheck": true,
        "strictNullChecks": true
    },
    "include": [
        "packages/**/*"
    ],
    "exclude": [
        "**/node_modules",
        "**/*.d.ts"
    ]
}
```

// A *self-contained* demonstration of the problem follows...

**Expected behavior:**
strictNullChecks should respect excludes.

**Actual behavior:**
it does not. If I remove strictNullChecks then the node_modules folders are excluded as expected.

**Comment by blakeembrey** [comment]
@yavuzmester What's the error? It might not be related to `strictNullChecks`, but an error that's only apparent for a node module under `strictNullChecks`. The excluded files are still used for type checking, just not compilation, so they are "used" when you import types from them.
