### ISSUE TITLE
Warning when writing a generator function without any yield

### ISSUE THREAD

**Issue by krryan** [microsoft/TypeScript#13847]
**TypeScript Version:**  2.2.0-dev.20170126

**Code**

```ts
export function* keyed<K, V>(values: Iterable<V>, toKey: (value: V) => K): IterableIterator<[K, V]> {
    for (const value of values) {
        return [toKey(value), value];
    }
}
```

**Expected behavior:**
Some kind of notice that this generator function never actually yields anything.

**Actual behavior:**
Compiles, and runs for that matter, without error, just silently yielding nothing.

I just spent a couple of hours tracking down a bug here, where `return` was accidentally used instead of `yield`. I'll admit I'm only starting to learn about generator functions and their uses, so it may be entirely possible that there are generator functions that want to return, rather than yield, in some cases, but my understanding is that every generator function should yield _at some point_.

Could we get a compiler warning for something like this? I'm not looking for a halt detector or anything :P just some kind of warning like "No 'yield' in reachable code," or something.

**Comment by RyanCavanaugh** [comment]
Accepting PRs for the rule: *a generator function with a `return` statement must not have zero `yield return` statements* (please make the error message less spec-like!)

**Comment by mhegazy** [comment]
https://github.com/Microsoft/TypeScript/issues/14043 has a valid example, a default implementation for a generator. the alternative would be to implement a function that returns the generator protocol, but that seems overly verbose.

**Comment by mhegazy** [comment]
In light of the [discussion about errors vs warnings](https://github.com/Microsoft/TypeScript/issues/19393) we should instead move this to tslint.

**Comment by rbuckton** [comment]
Note: #30790 will address this only in cases where the return type is explicitly specified as `Generator<T, void>`, as returning the value above would not be assignable to `void`.
