### ISSUE TITLE
new.target is not inferred as a "this" type

### ISSUE THREAD

**Issue by justinfagnani** [Microsoft/TypeScript#13849]
**TypeScript Version:**  typescript@2.2.0-dev.20170202

**Code**

```ts
class A {
  a: this;

  constructor() {
    super();
    this.a = Object.create(new.target.prototype); // [ts] Type 'A' is not assignable to type 'this'.
    this.a = new (new.target)(); // [ts] Type 'A' is not assignable to type 'this'.
  }
}
```

The assignment should be allowed in both cases.

**Expected behavior:**

No errors

**Actual behavior:**

Errors

**Comment by rbuckton** [comment]
We don't currently expose a `this` type for the static side of a class, and we do not currently expose the prototype of the static side of a class as a `this` type. Until such time as we decide to change that behavior, this is functioning as intended.

Please note, that you can avoid the error by introducing a type assertion in both cases:

```ts
class A {
  a: this;

  constructor() {
    this.a = Object.create(<this>new.target.prototype);
    this.a = <this>new (new.target)();
  }
}
```
