### ISSUE TITLE
Missing this reference for function declaration instead of fat arrow functions

### ISSUE THREAD

**Issue by CSchulz** [Microsoft/TypeScript#13842]
**TypeScript Version:**  2.0.10 / 2.0.2 / 2.1.5

**Code**
http://plnkr.co/edit/ZQONYB5oaLhO8aVRaLjE?p=preview

```ts
    this.service.getData().subscribe(
      function(x) {
        this.data = x;
      });

    this.service.getData().subscribe(
      (x) => {
         this.data = x;
      });
```

```js
// transpiled output
    App.prototype.ngOnInit = function () {
        this.service.getData().subscribe(function (x) {
            this.data = x;
        });
    };

    App.prototype.ngOnInit = function () {
        var _this = this;
        this.service.getData().subscribe(function (x) {
            _this.data = x;
        });
    };
```

**Expected behavior:**
It should make no difference between function or fat arrow function.

**Actual behavior:**
Missing this reference. `var _this = this;` for the function

```js
// transpiled output
    App.prototype.ngOnInit = function () {
        var _this = this;
        this.service.getData().subscribe(function (x) {
            _this.data = x;
        });
    };
```

**Comment by sandersn** [comment]
There *is* a difference between `function` and `=>`, which is that `function` binds `this` and `=>` does not. Can you explain which line of the transpiled output you expected to be different?

**Comment by CSchulz** [comment]
I think you mean the other way around, right? `=>` binds `this` to a variable.

I have updated the description.

It seems it was a misunderstanding of fat arrow. I thought it is the same as function, just another way to write it.
https://basarat.gitbooks.io/typescript/content/docs/arrow-functions.html told me something else.

**Comment by sandersn** [comment]
Sorry, I was talking about the Javascript standard, not the code that Typescript emits. In Javascript,

```js
function () {
  this;
  function () {
    this; // not the same as the outer this
  }
}
```

the two this references are different because `function` binds a fresh `this` that is basically an implicit parameter to the function. `=>` does not:

```js
function () {
  this;
  () => this; // SAME as outer this;
}
```

The `_this = this` that Typescript emits is a workaround since it has to emit `function` in old JS versions that don't have `=>`.
