### ISSUE TITLE
Inferring types without a function call

### ISSUE THREAD

**Issue by nevir** [microsoft/TypeScript#13843]
Apologies if this is part of another issue; I've searched for similar issues, but have come up dry (but also have been struggling to find the right terms to use when describing this).

---

(I believe this is not a bug, and is more of a feature request/design proposal)

TL;DR - When declaring a value that you wish to conform to a generic type - that can also have its template types inferred from the declaration - there doesn't appear to be a way to have TypeScript infer the template types without wrapping it in a function call.

The current workaround is to make an identity function to force the compiler to infer the types at the call site.

---

**TypeScript Version:**  2.1.1

[Playground](https://www.typescriptlang.org/play/index.html#src=%2F%2F%20So%2C%20let's%20say%20we%20want%20to%20have%20functions%20that%20accept%20an%20object%0A%2F%2F%20where%20each%20key%20in%20the%20object%20maps%20to%20a%20value%20that%20has%20a%20property%0A%2F%2F%20that%20corresponds%20to%20the%20key%20(for%20runtime%20use)%3A%0Atype%20TaggedFunction%3CTKeys%20extends%20string%3E%20%3D%0A%20%20%20%20(params%3A%20TaggedParams%3CTKeys%3E)%20%3D%3E%20TaggedResult%3CTKeys%3E%3B%0A%0Atype%20TaggedParams%3CTKeys%20extends%20string%3E%20%3D%20%7B%0A%20%20%20%20%5BTKey%20in%20TKeys%5D%3A%20TaggedParam%3CTKey%3E%0A%7D%3B%0A%0Ainterface%20TaggedParam%3CTKey%20extends%20string%3E%20%7B%0A%20%20%20%20key%3A%20TKey%3B%0A%20%20%20%20%2F%2F%20In%20real%20use%2C%20there's%20other%20data%20hanging%20off%20this.%0A%7D%0A%0Atype%20TaggedResult%3CTKeys%20extends%20string%3E%20%3D%20any%3B%20%2F%2F%20%C2%AF%5C_(%E3%83%84)_%2F%C2%AF%0A%0A%2F%2F%20The%20explicit%20way%20to%20build%20a%20function%20(and%20assert%20it%20matches)%0A%2F%2F%20the%20type%3A%0Aexport%20const%20Func1%3A%20TaggedFunction%3C'foo'%20%7C%20'bar'%3E%20%3D%20(%7B%20foo%2C%20bar%20%7D)%20%3D%3E%20%5Bfoo%2C%20bar%5D%3B%20%0A%0A%2F%2F%20Ideally%2C%20it%20would%20be%20great%20if%20TypeScript%20could%20infer%20the%0A%2F%2F%20keys%20being%20used%20without%20having%20to%20duplicate%20them%20in%20the%20template%0A%2F%2F%20parameter%3A%0Aexport%20const%20Func2%3A%20TaggedFunction%20%3D%20(%7B%20foo%2C%20bar%20%7D)%20%3D%3E%20%5Bfoo%2C%20bar%5D%3B%0A%2F%2F%20or%20maybe%3A%0Aexport%20const%20Func3%3A%20TaggedFunction%3Cauto%3E%20%3D%20(%7B%20foo%2C%20bar%20%7D)%20%3D%3E%20%5Bfoo%2C%20bar%5D%3B%0A%0A%2F%2F%20As%20a%20workaround%2C%20I%20currently%20use%20an%20identity%20function%2C%20since%0A%2F%2F%20TypeScript%20will%20infer%20types%20at%20a%20function%20call%20site%3A%0Afunction%20tagged%3CTKeys%20extends%20string%3E(func%3A%20TaggedFunction%3CTKeys%3E)%20%7B%0A%20%20%20%20return%20func%3B%0A%7D%0Aexport%20const%20func4%20%3D%20tagged((%7B%20foo%2C%20bar%20%7D)%20%3D%3E%20%5Bfoo%2C%20bar%5D)%3B%0A)
```ts
// So, let's say we want to have functions that accept an object where each key
// in the object maps to a value that has a property that corresponds to the key
// (for runtime use):
type TaggedFunction<TKeys extends string> =
    (params: TaggedParams<TKeys>) => TaggedResult<TKeys>;
type TaggedParams<TKeys extends string> = {
    [TKey in TKeys]: TaggedParam<TKey>
};
interface TaggedParam<TKey extends string> {
    key: TKey;
    // In real world use, there's other data hanging off this.
}
type TaggedResult<TKeys extends string> = any; // ¯\_(ツ)_/¯

// The explicit way to build a function, and assert it matches the type:
export const func1: TaggedFunction<'foo' | 'bar'> = ({ foo, bar }) => [foo, bar]; 

// Ideally, it would be great if TypeScript could infer the keys being used
// without having to duplicate them in the template parameter:
export const func2: TaggedFunction = ({ foo, bar }) => [foo, bar];
// or maybe:
export const func3: TaggedFunction<auto> = ({ foo, bar }) => [foo, bar];

// As a workaround, I currently use an identity function, since TypeScript will
// infer types at a function call site:
function tagged<TKeys extends string>(func: TaggedFunction<TKeys>) {
    return func;
}
export const func4 = tagged(({ foo, bar }) => [foo, bar]);
```

**Comment by nevir** [comment]
Edit: I think I'm also misunderstanding something, since `func4` is actually not being inferred at all (it's coming out as `TaggedFunction<string>`, *not* `TaggedFunction<'foo' | 'bar'>`)

**Comment by RyanCavanaugh** [comment]
This is possible with conditional types e.g. `ReturnType` now.
