### ISSUE TITLE
_awaiter should support cancel

### ISSUE THREAD

**Issue by errisy** [Microsoft/TypeScript#13854]
**TypeScript Version:**  2.1.x

**Scenarios and Reasons**

The async/await is amazing syntactic sugar. However, in UI programming, in many scenarios, we should manage the uncompleted Promises. Those uncompleted promises are sources of errors/bugs.

For example: when the user triggered some events and the event handlers, which are async functions and start to do something. But the user suddenly decide to jump to another UI view/component, and those uncompleted async functions are very likely to cause errors when they callback and try to do something to the destroyed view, and they are wasting CPU and memory resources.

**Code**

    public async DoSomething(){
        await DoFirst();
        DoSecond();
        await DoThird();
        await DoFourth();
        await DoLast();
    }

```javascript
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : new P(function (resolve) { resolve(result.value); }).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments)).next());
    });
};
```

**Expected behavior:**
the cancellation token should be added to the awaiter, so that we can manage and cancel the awaiter promises.
```javascript
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    return new (P || (P = Promise))(function (resolve, reject, token) {
        function fulfilled(value) {if(token.cancelled) return; try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) {if(token.cancelled) return; try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) {if(token.cancelled) return; result.done ? resolve(result.value) : new P(function (resolve) { resolve(result.value); }).then(fulfilled, rejected); }
        if(token.cancelled) return;
        step((generator = generator.apply(thisArg, _arguments)).next());
    });
};
```
Then we can PolyFilll the standard Promise to enable cancellation and status check.
Here is a typical scenario, where we do want to cancel.
```ts
class SomeUIComponent {    

    Dispose() {
        let canceller = (promise) => promise.cancel();
        this._DoSomethingPromises.forEach(canceller);
        this._QueryAutoCompleteDataSourcePromises.forEach(canceller);
    }

    public async DoSomething(){
        await DoFirst();
        DoSecond();
        await DoThird();
        await DoFourth();
        await DoLast();
    }
    private _DoSomethingPromises: CancellablePromise<any>[] = []; 
    public onMouseClick() {
        this._DoSomethingPromises =
            this._DoSomethingPromises.filter(promise => promise.Status == 'pending');
        this._DoSomethingPromises.push(this.DoSomething());
    }

    public async QueryAutoCompleteDataSource() {
        await Wait500ms(); //avoid flooding
        this.AutoCompleter.DataSource = await XHRQuery('some url');
    }
    private _QueryAutoCompleteDataSourcePromises: CancellablePromise<any>[] = []; 

    public onAutoCompleterKeyDown() {
        this._QueryAutoCompleteDataSourcePromises =
            this._QueryAutoCompleteDataSourcePromises.filter(promise => promise.Cancel(), false);
        this._QueryAutoCompleteDataSourcePromises.push(this.QueryAutoCompleteDataSource());
    }

}
```

Generally, a typescript async function is doing almost the same thing as an RxJS operator chain. The nature as a instance instead of a function is actually the advantage of RxJS over async function. However, RxJS is still the callback style programming, and is not as convenient as async/await in many scenarios. In the TypeScript async/await world, we should have more elegant way to manage an async function, such as a TypeScript decorator that converts an async member function to a promise queue manager to avoid managing the queue yourself.

The folllowing automation can be easily done with TypeScript decorators.
```ts
@AsyncService.Component
class SomeUIComponent {    
    @AsyncService.Dispose //the decorator modified the prototype. calling Dispose will cancel all registerd AsyncService of this instance.
    Dispose() {}
    @AsyncService.Multiple //allows multiple promises running at the same time.
    public onMouseClick() {
        //access the promise array 
        let promises = AsyncService.Instances(this, () => SomeUIComponent.prototype.onMouseClick));
        //keeps no more than two promises 
        promises.filter((promise, index) => (index > 2) ? (promise.Cancel(), false) : true);
        
        await DoFirst();
        DoSecond();
        await DoThird();
        await DoFourth();
        await DoLast();
    }
    @AsyncService.Single //always cancel the previous ones before start a new Promise
    public onAutoCompleterKeyDown() {
        await Wait500ms(); //avoid flooding
        this.AutoCompleter.DataSource = await XHRQuery('some url');
    }
}
```

**Actual behavior:**

**Comment by mhegazy** [comment]
Cancelable promises is something TC39 is discussing currently, see https://github.com/tc39/proposal-cancellation for more details. I would recommend moving this discussion to the cancellation API proposal instead. TypeScript will not be adding new features to a built-in API like `Promise` that would conflict with future changes in the ECMAScript.
