### ISSUE TITLE
No suggestions returned when adding property before other properties in object literal 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#13850]
_From @victorschinaider on January 24, 2017 23:43_

- VSCode Version: 1.8.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:
![ezgif com-631dcaef81](https://cloud.githubusercontent.com/assets/16581931/22270561/ef51c04c-e26e-11e6-9c85-2d0d56cea7b1.gif)

I'm using the VSCode to work with Angular 2 and Typescript.
When i'm in the Component decorator definition, i'm getting this strange behavior.
The autocomplete don't work when the vscode Interprets an error in syntax (see the gif), only autcompletes if there is no "error", but wheni think vscode needs to autocomplete when there was an error, to correct it.

_Copied from original issue: Microsoft/vscode#19304_

**Comment by mjbvz** [comment]
Moved this issue over too soon. I don't think this is a vscode issue but will try to get more info because I'm having trouble reproducing this now.

**Comment by mjbvz** [comment]
This does look like a ts issue. Here's a simplified repo:

```ts
interface Foo {
    abc: number;
    xyz: string;
};

({
    a|
    xyz: `string`
} as Foo);

```

Trigger the completion at the `|` gives:

```
[Trace - 4:03:14 PM] Sending request: completions (21). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/Users/matb/projects/sand/bar.ts",
    "line": 7,
    "offset": 6
}
[Trace - 4:03:14 PM] Response received: completions (21). Request took 2 ms. Success: false . Message: No content available.
```

Collecting logs now

**Comment by mhegazy** [comment]
it is a parsing issue. not sure what can be done here though.

**Comment by DanielRosenwasser** [comment]
Pretty sure this works now. Can you verify @mjbvz?

**Comment by mjbvz** [comment]
Yep, also works for me with TS 3.7.5!
