### ISSUE TITLE
Specialize declared generic interfaces based on parameter shape

### ISSUE THREAD

**Issue by danvk** [microsoft/TypeScript#13852]
For typing something like underscore's `_.chain`, it would be helpful if interfaces could be extended based on the shape of their type parameters.

For example:

```ts
// These methods are available for any T.
declare interface Chainable<T> {
  value(): T;
}

// These methods are only available for array types.
declare interface Chainable<T[]> {
  map<U>(mapFn: (t: T) => U): Chainable<U[]>;
}
```

[Existing type definitions][1] try to infer whether `T` is an array, object, array of objects, etc. But this is cumbersome and they'll never be able to do it as well as TypeScript itself.

The snippet above doesn't parse with TypeScript 2.1.5:

```
[ts] Operator '>' cannot be applied to types 'undefined[]' and '{ map<U>(mapFn: (t: any) => U): Chainable<U[]>; }'.
```

[1]: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/dba28e960820108dcfc6fe1a4b04e3a35724cec8/underscore/index.d.ts#L5072

**Comment by danvk** [comment]
maybe related to https://github.com/Microsoft/TypeScript/issues/12424

**Comment by mhegazy** [comment]
either  #12424 or have some sort of overload on generic type parameters

**Comment by danvk** [comment]
I wrote a [post][2] that touched on this issue and got some [great feedback][1] from the /r/javascript reddit. As it turns out, there's a workaround that already works: specialize by overloading the `this` parameter.

```ts
declare interface Chainable<T> {
  value(): T;  // This methods is available for any T.

  // This method is only available for array types, where T matches V[].
  map<U, V>(this: V[], mapFn: (v: V) => U): Chainable<U[]>;
}
```

[1]: https://www.reddit.com/r/javascript/comments/62f531/a_typed_chain_exploring_the_limits_of_typescript/
[2]: https://medium.com/@danvdk/a-typed-chain-exploring-the-limits-of-typescript-b50153be53d8

**Comment by danvk** [comment]
Overloading on the type of `this` works great. The lodash declarations in DefinitelyTyped do this now. Closing.
