### ISSUE TITLE
Release announcement and download links for 2.2 RC are wrong

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/TypeScript#13862]
The [Github release page for the 2.2 RC](https://github.com/Microsoft/TypeScript/releases/tag/v2.2-rc) has a couple of incorrect links.

Correct links:

* Release announcement: https://blogs.msdn.microsoft.com/typescript/2017/02/02/announcing-typescript-2-2-rc/

* Visual Studio Plugin link (Don't click on this unless you want to start the download): http://download.microsoft.com/download/6/D/8/6D8381B0-03C1-4BD2-AE65-30FF0A4C62DA/TS-2.2-dev14update3-20170201.4/TypeScript_Dev14Full.exe

**Comment by RyanCavanaugh** [comment]
@DanielRosenwasser

**Comment by mhegazy** [comment]
Thanks. should be updated now.
