### ISSUE TITLE
Typecheck spread attributes in JSX

### ISSUE THREAD

**Issue by clayne11** [Microsoft/TypeScript#13868]
**TypeScript Version:**  2.1.5
When using spread attributes in JSX, I would like to see the values typechecked. I use spread attributes in all of my JSX rather than `property='value'` because it's much easier to copy / paste / manipulate these properties into and out of regular JavaScript.

When you use the `property='value'` syntax it's painful if you have to move this code into JavaScript to manipulate it.

**Code**

```ts
// Foo.tsx
interface IFooProps {
  bar: string,
  baz: number
}

const Foo = (props: IFooProps) => (
  <div>
    bar = {props.bar}
    baz = {props.baz}
  </div>
)

// Foobar.tsx
import Foo from './Foo'

// Example 1
// my preference
const Foobar = () => (
  <Foo {...{
    bar: 45,
    baz: 'test',
  }}/>
)

vs.

// Example 2
const Foobar = () => (
  <Foo 
    bar={45}
    baz='test'
  />
)
```

**Expected behavior:**
Example 1 should be typechecked, however it isn't.

**Actual behavior:**
Example 1 is not typechecked. Example 2 is.

I have a codebase with 500+ components using the style of example 1 and Typescript essentially doesn't work for me.

**Comment by RyanCavanaugh** [comment]
What do you mean by "not typechecked" ? The types of spread attributes are checked.

**Comment by clayne11** [comment]
It looks like the issue is in the higher-order-components I'm using that return `any`. My bad.
