### ISSUE TITLE
Suggestion: --jsx hyperscript 

### ISSUE THREAD

**Issue by SteveALee** [Microsoft/TypeScript#13860]
Just a semi random thought but the new --jsx value for react native made me thinking that a hyperscript value might prove to be of interest. 

Many frameworks and vdoms use [hyperscript](https://github.com/hyperhype/hyperscript) or the [hyperscript helpers](https://github.com/ohanhi/hyperscript-helpers). While many devs are happy with this functional style for HTML, others might prefer to use JSX.

I think the mapping from React to hyperscript is straight forward.

**Comment by devdoomari** [comment]
I'm hoping this would get resolved using 'plugins' as babel does...
e.g.
```
plugins: [
    'ts-plugins-jsx-hyperscript'
]
```

**Comment by DanielRosenwasser** [comment]
I'll point out that right now you can get hyperscript working, but not necessarily compile directly down to syntax that uses hyperscript helpers. You can accomplish this using the `--jsxFactory` (or potentially `--reactNamespace`) flags. If you're familiar with Babel's JSX pragma, the `jsxFactory` flag should be equivalent.

As an example, if you're using Mithril's API, and you've imported it as `m`, you can use `--jsxFactory m` and write

```ts
let x = <div></div>l
```

which will get compiled to

```js
let x = m.a("div", null);
```

Would that suffice, or is compiling down to hyperscript-helpers really the goal here?

**Comment by SteveALee** [comment]
@devdoomari well that makes sense - but why are existing JSX options not done hat way but given explicit TS support?

It looks like it can be done with webpack:
https://github.com/cyclejs-community/create-cycle-app-flavors/blob/master/packages/cycle-scripts-one-fits-all/scripts/configs/webpack.config.js#L38-L39

**Comment by SteveALee** [comment]
@DanielRosenwasser I'd say the use of helpers is irrelevant if the mapping is jsx -> hyperscript. The helpers are really for when you are created the vdom manually with JS.

Hmm, how and why does babel fit in with TS? I've seen referecnes to that but do not understand the use case. Sure TS does all you want? Or is it for ES6 etc support in browers?

**Comment by DanielRosenwasser** [comment]
> Hmm, how and why does babel fit in with TS? 

React may be independent, but as far as I can see, the transformation is effectively the same with a different function to manufacture JSX elements. If that's the case, then the infrastructure is already there and you can use it today. If not, can you correct me and give me a counter-example?

To refocus a little bit: is there a hyperscript-like API that you're interested in having JSX target at the moment?

**Comment by SteveALee** [comment]
@DanielRosenwasser I guess the jsx-factory approach would work fine. I see a little variation in hyperscript implementations though.

I'm using snabbdom but [this config](https://github.com/cyclejs-community/create-cycle-app-flavors/tree/master/packages/cycle-scripts-one-fits-all) works for me by using the webpack ```'snabbdom-jsx' plugin.

Thanks for you feedback
