### ISSUE TITLE
Unsafe coercion from "any type" to {}

### ISSUE THREAD

**Issue by AlexGalays** [Microsoft/TypeScript#13861]
**TypeScript Version:**  2.1.5 and 2.2.0-dev.20170201
Using --noImplicitAny and --strictNullChecks

**Code**

```ts
function doItWithAnObject<A extends {}>(a: A) {
  a.toString()
}

function doItWithAnything<B>(b: B) {
  doItWithAnObject(b)
}

doItWithAnything(null)
doItWithAnything(undefined)
```

**Expected behavior:**
`doItWithAnything` should not compile because it calls `doItWithAnObject` with something that is potentially not an object.

**Actual behavior:**
No compilation error. Runtime errors.

Perhaps related: If I have an abstract type A, and I narrow it down to A minus null minus undefined, it isn't considered as an object.

**Comment by mhegazy** [comment]
if you want to exclude `null` and `undefined`, give the generic type parameter a constraint for `{}`. if you want to further exclude primitives, give it a constraint `object`. otherwise, it goes to the top type, i.e. `{} | null | undefined`

**Comment by AlexGalays** [comment]
Oh, I see. Thanks.

**Comment by ikokostya** [comment]
> if you want to exclude null and undefined, give the generic type parameter a constraint for {}

But it already done for `doItWithAnObject` function:

```ts
function doItWithAnObject<A extends {}>(a: A) {
  a.toString();
}
doItWithAnObject(null); // Error: Argument of type 'null' is not assignable to parameter of type '{}'
```

Why compiled doesn't check this inside `doItWithAnything` function?

```ts
function doItWithAnything<B>(b: B) {
  doItWithAnObject(b); // No errors
}
doItWithAnything(null);
```
