### ISSUE TITLE
TSServer Crashes When Opening Sharepoint Folder 

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#13874]
**TypeScript Version:**  2.1.5

We're seeing a large number of reports of TSServer crashes from VSCode users when they attempt to open a project stored on sharepoint. I can repo this by opening a simple sharepoint folder with a single empty js file on windows.

Here's an example trace of the communications from VSCode:

```
Insiders\resources\app\extensions\typescript\node_modules\typescript\lib\tsserver.js
[Trace - 1:31:58 PM] Sending request: configure (153). Response expected: yes. Current queue length: 0
Arguments: {
    "hostInfo": "vscode"
}
[Trace - 1:31:58 PM] Response received: configure (153). Request took 294 ms. Success: true 
[Trace - 1:31:58 PM] Sending request: compilerOptionsForInferredProjects (154). Response expected: yes. Current queue length: 3
Arguments: {
    "options": {
        "module": "CommonJS",
        "target": "ES6",
        "allowSyntheticDefaultImports": true,
        "allowNonTsExtensions": true,
        "allowJs": true,
        "jsx": "Preserve"
    }
}
[Trace - 1:31:58 PM] Response received: compilerOptionsForInferredProjects (154). Request took 296 ms. Success: true 
Result: true
[Trace - 1:31:58 PM] Sending request: open (155). Response expected: no. Current queue length: 2
Arguments: {
    "file": "//microsoft.sharepoint.com@SSL/DavWWWRoot/teams/DD_OTP/Documents/Java and Open Tools/Node/test/main.js",
    "fileContent": ""
}
[Trace - 1:31:58 PM] Sending request: geterr (156). Response expected: no. Current queue length: 1
Arguments: {
    "delay": 0,
    "files": []
}
[Trace - 1:31:58 PM] Sending request: geterr (157). Response expected: no. Current queue length: 0
Arguments: {
    "delay": 0,
    "files": [
        "//microsoft.sharepoint.com@SSL/DavWWWRoot/teams/DD_OTP/Documents/Java and Open Tools/Node/test/main.js"
    ]
}
[Error - 1:31:58 PM] TSServer exited with code: 3221226356
```

TSS_LOG did not produce any data, just `Info 0    Binding...`

**Comment by bpasero** [comment]
Imho this should be backported to `2.1.x` so that we can do a recovery build.

**Comment by thriggle** [comment]
Does this TypeScript issue's resolution fix issue [19870](https://github.com/Microsoft/vscode/issues/19870) as well? That problem occurs for any js file, even with the TypeScript extension removed, yet it was closed last week as a duplicate of this issue.

**Comment by mhegazy** [comment]
> Does this TypeScript issue's resolution fix issue 19870 as well?
https://github.com/Microsoft/vscode/issues/19870 is rather scarce on details, but seems like the same symptoms.

>That problem occurs for any js file, even with the TypeScript extension removed, yet it was closed last week as a duplicate of this issue.

The JavaScript language service in VSCode is driven by the TypeScript engine. The problem is really caused by a bug in libuv https://github.com/libuv/libuv/issues/1221. We have a mitigation in place in [typescript@2.1.6](https://github.com/Microsoft/TypeScript/releases/tag/v2.1.6). The VSCode team is looking for releasing a new build with the fix shortly.
