### ISSUE TITLE
Promises in es5 target are not correctly typed

### ISSUE THREAD

**Issue by danperkins** [Microsoft/TypeScript#13876]
Create a new Typescript File (.ts)
Paste this code in the editor:

***Edit by @DanielRosenwasser***

```ts
// bar typed by VSCode (with 'es2015.promise lib configuration) -- Promise
// bar typed by VSCode with 'es6-promise' module -- Promise
// bar typed by Typescript Playground -- Promise<number | string>
let bar = Promise.resolve()
.then(() => 5)
.catch(() => {
return 'true';
});
// foo typed by VSCode (with 'es2015.promise lib configuration) -- Promise<{}>
// foo typed by VSCode with 'es6-promise' module -- Promise 
// foo typed by Typescript Playground -- Promise 
let foo = Promise
.resolve(5)
.then(() => 'test')
.catch(() => {
return Promise.reject(false);
});
```

tsconfig has target: es5

The typings for the Promises don't match what I would expect them to (compared to https://www.typescriptlang.org/play/ which does the right thing. I was using npm module 'es6-promise' instead of including a polyfill, but switched to trying the --lib declaration for 'es2015.promise' in my tsconfig file. Both cases gave me different typings for the Promise, but both were wrong and didn't match Typescripts playground.

Are there alternative typings files that I can pull in to get correct typing, or is there some other way to configure the es5 target plus --lib es2015.promise to get correct typing?

***setting target ot es6 does provide the correct typing so I guess switching to that target and then tracking down all the relevant polyfills is a possibility?

**Comment by DanielRosenwasser** [comment]
It's unclear what `lib` option you are using. `es2015.promise, es5, dom` will probably give you the appropriate results.
