### ISSUE TITLE
Potential bug with mapped types and type guards

### ISSUE THREAD

**Issue by maghis** [Microsoft/TypeScript#13872]
Not sure if this is a bug or the intended behavior, but typeguards don't seem to be working on a mapped type value.

**TypeScript Version:**  2.1.5

**Code**

```ts
function fun<T>(item: { [P in keyof T]: T[P] }) {
    const strings: string[] = [];
    for (const key in item) {
        const value = item[key];
        if (typeof value === "string") {
            strings.push(value);
        }
    }
}
```

**Expected behavior:**
`value` should be assignable to `string`

**Actual behavior:**
```
error TS2345: Argument of type 'T[keyof T]' is not assignable to parameter of type 'string'.
```

**Comment by ahejlsberg** [comment]
This ought to work given that `T[P]` has no constraint and *could* be a string.
