### ISSUE TITLE
true private members & symbols ?

### ISSUE THREAD

**Issue by ichiriac** [Microsoft/TypeScript#13879]
Hi,

Is there any reason you don't use symbols for private properties on classes ? I'm really interested on what you have done with typescript and try something similar so I'm maybe missing something.

Best Regards,
Ioan

**Comment by ichiriac** [comment]
BTW, I've read all thread on Stackoverflow http://stackoverflow.com/questions/12713659/typescript-private-members and Codeplex https://typescript.codeplex.com/discussions/397651 but they don't speak about symbols so maybe they are too old as symbols were introduced lately.

**Comment by DanielRosenwasser** [comment]
We once got a PR from @Arnavion (see #684), however, the emit causes issues.

At the time, @NoelAbrahams noted:

> - Class instantiation [is about 60% slower](http://jsperf.com/privates-using-symbols-vs-current-codegen) when using symbols.
> - Property and method access [is about 90% slower](http://jsperf.com/privates-using-symbols-vs-current-codegen/3) when using symbols.
> - The codegen when using symbols is not minification-friendly; even advanced optimisation will not minify string literals such as `__symbol("_property_p");`

Things might have changed in terms of speed, but at this point I'd rather we didn't change our `private` emit until we see the direction ECMAScript takes with the private slots proposal. In fact, I don't think our `public`, `private`, or `protected` modifiers should have *any* sort of impact on emit.

**Comment by ichiriac** [comment]
Hi @DanielRosenwasser,

Many thanks, it's very helpfull all these links. Finger crossed for private slots, anyway they already reserved the private keyword http://www.ecma-international.org/ecma-262/6.0/#sec-future-reserved-words

**Comment by Yogu** [comment]
> Class instantiation is about 60% slower when using symbols.
> Property and method access is about 90% slower when using symbols.

Seems no longer to be true, property access is 2% slower and instanciation performance is equal for me (Chrome 56). By the *private slot proposal*, do you mean the tc39 [proposal-private-fields](https://github.com/tc39/proposal-private-fields)?

**Comment by ichiriac** [comment]
Sadly, symbols will not be a guarantee to make things fully private : https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertySymbols
