### ISSUE TITLE
[DOCS] react webpack docs are outdated or incorrect

### ISSUE THREAD

**Issue by tbremer** [microsoft/TypeScript#13873]
### Invalid config:

The [config file](//www.typescriptlang.org/docs/handbook/react-&-webpack.html#create-a-webpack-configuration-file) posted in your docs references an older version of webpack, `preLoaders` [have since been removed](https://webpack.js.org/guides/migrating/#module-preloaders-and-module-postloaders-was-removed). As such the `source-map-loader` suggests moving it to a `module.rule`.
However, the `source-map-loader` plugin throws the following error (assuming this is because it is running _before_ TS compiler)…

```
ERROR in ./src/index.tsx
Module parse failed: /Users/thomas.bremer/Desktop/micro-router/src/index.tsx Unexpected token (11:4)
You may need an appropriate loader to handle this file type.
|
| ReactDOM.render(
|     <Hello compiler="TypeScript" framework="React" />,
|     document.getElementById("example")
| );
```

#### empty extensions are no longer valid

```javascript
/* this config portion */
resolve: {
  // Add '.ts' and '.tsx' as resolvable extensions.
  extensions: ["", ".webpack.js", ".web.js", ".ts", ".tsx", ".js"]
},

/* produces this error */
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.resolve.extensions[0] should not be empty.
```

### Possible config that could be used:

_this config drops `source-map-loader` as a `devDependency`_

```javascript
module.exports = {
  entry: './src/index.tsx',
  output: {
    filename: 'bundle.js',
    path: __dirname + '/dist'
  },

  // Enable sourcemaps for debugging webpack's output.
  devtool: 'source-map',

  resolve: {
    // Add '.ts' and '.tsx' as resolvable extensions.
    extensions: ['.webpack.js', '.web.js', '.ts', '.tsx', '.js']
  },

  module: {
    loaders: [
      // All files with a '.ts' or '.tsx' extension will be handled by 'awesome-typescript-loader'.
      { test: /\.tsx?$/, loader: 'awesome-typescript-loader' }
    ]
  },

  // When importing a module whose path matches one of the following, just
  // assume a corresponding global variable exists and use that instead.
  // This is important because it allows us to avoid bundling all of our
  // dependencies, which allows browsers to cache those libraries between builds.
  externals: {
    'react': 'React',
    'react-dom': 'ReactDOM'
  },
};

```

**Comment by DanielRosenwasser** [comment]
We actually accept PRs on our documentation. Feel free to send one on the repo!

https://github.com/Microsoft/TypeScript-Handbook

**Comment by DanielRosenwasser** [comment]
By the way, are the changes backward-compatible with Webpack 1.x? CC @TheLarkInn

**Comment by Kovensky** [comment]
The second snippet _appears_ to be, as it is using the `loaders` key instead of `rules`, but I haven't used webpack 1 before to confirm.

**Comment by melito00** [comment]
I changed below.

```json
    rules: [
      {
        test: /\.js$/, 
        enforce: "pre",
        loader: "source-map-loader"
      }
    ]
    /*
    preLoaders: [
      { test: /\.js$/, loader: "source-map-loader" }
    ]
    */
```

**Comment by mattnedrich** [comment]
What is the preferred solution to this problem? Is it possible to still include `source-map-loader` somehow?

**Comment by EduardJS** [comment]
I'm also confused as to how should we use this.

**Comment by radix** [comment]
I am trying to follow this tutorial and I'm getting errors about "You may need an appropriate loader to handle this file type", as this ticket describes, but the suggested change in the ticket doesn't seem to be having any effect.

**Comment by radix** [comment]
my bad, the reason I was getting that error is that I was accidentally feeding the bundle.js back into webpack. disregard :)

**Comment by RyanCavanaugh** [comment]
This has been updated for modern webpack
