### ISSUE TITLE
Object rest properties in import statements

### ISSUE THREAD

**Issue by Wenzil** [Microsoft/TypeScript#13885]
**TypeScript Version:**  2.1.5

Hi,

I just realized that object rest properties introduced in TypeScript 2.1 don't work with module imports. We lose flexibility by not being able to do something like the following.

**Code**
```ts
// ./abcd.ts
export const a = 'a';
export const b = 'b';
export const c = 'c';
export const d = 'd';
```
```ts
import {a, b, ...cd} from './abcd';. 
```

**Expected behavior:**

The import statement should result in the following three variables
- a equals 'a'
- b equals 'b'
- cd deep equals { c: 'c', d: 'd' }

**Actual behavior:**

This currently results in a compiler error:

> [ts] Module '"/myproject/abcd"' has no exported member 'cd'.

**Comment by DanielRosenwasser** [comment]
Unfortunately this is out of scope unless something like this gets standardized by TC39. In the mean time, you can write something like

```ts
import * as abcd from "./abcd";
const { a, b, ...cd } = abcd;
```

which is mostly the same.
