### ISSUE TITLE
Method decorator does not get the correct target

### ISSUE THREAD

**Issue by unional** [Microsoft/TypeScript#13887]
tsc: 2.1.5 / 2.2.0-dev.20170205

```ts
function deco() {
    return function (target, key, descriptor) {
        const fn = descriptor.value
        const newFn = function (...args) {
            console.log('calling fn')
            const result = fn.apply(target, args)
            console.log('done fn')
            return result
        }

        descriptor.value = newFn
        return descriptor
    }
}

class Foo {
    @deco()
    do() {
        console.log(this)
    }

    doLess() {
        console.log(this)
    }
}

const foo = new Foo()

foo.do()
foo.doLess()
```

Expect the two console log print out the same thing.

Actual:
![image](https://cloud.githubusercontent.com/assets/3254987/22629259/87ce96ac-eb97-11e6-9b99-c65222013d7a.png)

http://www.typescriptlang.org/play/index.html#src=function%20deco()%20%7B%0D%0A%20%20%20%20return%20function%20(target%2C%20key%2C%20descriptor)%20%7B%0D%0A%20%20%20%20%20%20%20%20const%20fn%20%3D%20descriptor.value%0D%0A%20%20%20%20%20%20%20%20const%20newFn%20%3D%20function%20(...args)%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20console.log('calling%20fn')%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20const%20result%20%3D%20fn.apply(target%2C%20args)%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20console.log('done%20fn')%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20result%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20%20%20%20%20descriptor.value%20%3D%20newFn%0D%0A%20%20%20%20%20%20%20%20return%20descriptor%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aclass%20Foo%20%7B%0D%0A%20%20%20%20%40deco()%0D%0A%20%20%20%20do()%20%7B%0D%0A%20%20%20%20%20%20%20%20console.log(this)%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20doLess()%20%7B%0D%0A%20%20%20%20%20%20%20%20console.log(this)%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aconst%20foo%20%3D%20new%20Foo()%0D%0A%0D%0Afoo.do()%0D%0Afoo.doLess()

UPDATE: return descriptor
UPDATE2: Update screenshot

**Comment by mhegazy** [comment]
you need to return the descriptor and not just change it.

**Comment by unional** [comment]
Also tried that. That's what in the playground.

**Comment by unional** [comment]
Updated the screenshot to show that `target` is the `__proto__` object instead of the instance.

**Comment by mhegazy** [comment]
sorry, missed that part. you should not use `target` nor `target.proto`, you want to use `this`. you want the same instance that the original method was triggered on.

**Comment by unional** [comment]
I see. Thanks. It is working correctly now. 🌷

**Comment by unional** [comment]
Regarding returning descriptor, the handbook example also didn't return the descriptor:
