### ISSUE TITLE
Types for TransitionEvent object

### ISSUE THREAD

**Issue by DevVersion** [Microsoft/TypeScript#13888]
**TypeScript Version:**  Master

**Code**

```ts
/* propertyName and elapsedTime are variables above. */
let event = new TransitionEvent('transitionend', {propertyName, elapsedTime});
```
As per the definition of the `TransitionEvent` object, there are no parameters supported (See [here](https://github.com/Microsoft/TypeScript/blob/master/lib/lib.dom.d.ts#L10791)) 

**Expected behavior:**

As specified in MDN, the `TransitionEvent` has a different constructor signature and should accept a `type` and an options object.

Here is the MDN artice: https://developer.mozilla.org/en-US/docs/Web/API/TransitionEvent/TransitionEvent

> Also confirmed that this works the same way in Chrome right now.

**Actual behavior:**

TypeScript currently only allows us to create a `TransitionEvent` without any parameters.

Would like to submit a PR if desired and if bug is valid.

**Comment by mhegazy** [comment]
Should be fixed by https://github.com/Microsoft/TypeScript/pull/13856

**Comment by DevVersion** [comment]
@mhegazy Cool. Thanks!
