### ISSUE TITLE
Runtime crash because wrong order of definitions is not detected

### ISSUE THREAD

**Issue by nponeccop** [Microsoft/TypeScript#13893]
**TypeScript Version:**  2.1.5
**Code**

```ts
export const bar = new Foo()

export class Foo {
}
```

**Expected behavior:**

Either a compilation error is thrown or working code is generated

**Actual behavior:**

The following code is generated:

```js
"use strict";
exports.bar = new Foo();
var Foo = (function () {
    function Foo() {
    }
    return Foo;
}());
```

It fails at runtime both in Edge and Node because `var Foo` is not yet defined.

**Comment by yuit** [comment]
We should issue an error for this case. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes#Hoisting

**Comment by nponeccop** [comment]
Another reference (it's the latest draft, but probably there is similar place in the latest approved text of ECMAScript standard):

https://tc39.github.io/ecma262/#prod-Declaration

See `Declaration` vs `HoistableDeclaration` non-terminals.
