### ISSUE TITLE
Ability to control project scope

### ISSUE THREAD

**Issue by johnnyreilly** [Microsoft/TypeScript#13895]
This is a cross post of a behaviour that people have repeatedly requested be added to the webpack loaders for TypeScript (awesome-typescript-loader and ts-loader). To quote @s-panferov:

> It looks like that people want to typecheck only files directly included by an entry point. My opinion is that the loader should output the same errors as in direct tsc call.
>
> I decided to conduct a small survey about the preferred default behavior:
>
> 1. Align with TypeScript and IDEs, check errors in files, specified by tsconfig.json and included from a resolution graph.
> 2. Don't align with TypeScript and IDEs, check errors in files from a resolution graph only. Ignore files from tsconfig.json

https://github.com/s-panferov/awesome-typescript-loader/issues/364

Are there any thoughts around supporting this behaviour in tsc itself? I can understand the desire but am very wary of introducing different behaviour in a loader to the actual compiler.

https://github.com/TypeStrong/ts-loader/issues/267

**Comment by colinskow** [comment]
As it relates to the TypeScript compiler, I would like to be able to pass in a list of files to the command line AND use a `tsconfig.json` file for compiler options. Currently TypeScript throws an error if I try to do both. To overcome this I have to hardcode the `files` array in the config file, which is less than ideal for dynamic builds.

**Comment by mhegazy** [comment]
@colinskow this is tracked by https://github.com/Microsoft/TypeScript/issues/13575

**Comment by mhegazy** [comment]
@johnnyreilly, the compiler provide an API for transpilation (`transpileModule`) that reports no semantic errors. The intention here is you get your errors from the IDE for instance, and the transpilation process only transforms code. I would say this is a supported scenario, but i do not think it fits in tsc itself.

**Comment by johnnyreilly** [comment]
@mhegazy thanks for responding.  I think the idea here is to have an alternative to `files` which allows you to specify root or entry files.  `entryFiles` if you will.  The idea being that each entry denotes the root file of a distinct project context; all other files being pulled in the files it needs via `import` / `require` statements.  Is that something that's ever been considered for tsc?

**Comment by mhegazy** [comment]
this is how `files` behave today anyways. you do not need to specify all the files in the `files` list, just the roots.
