### ISSUE TITLE
Exported variable name error

### ISSUE THREAD

**Issue by rocketRobin** [Microsoft/TypeScript#13894]
**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
Code like this

```
![image](https://cloud.githubusercontent.com/assets/9987850/22636631/a66aaf02-ec77-11e6-9602-0e8d0778dc25.png)

**Expected behavior:**

**Actual behavior:**
![image](https://cloud.githubusercontent.com/assets/9987850/22636642/badd2668-ec77-11e6-8c65-e52725edb08e.png)

**Comment by RyanCavanaugh** [comment]
See e.g. https://github.com/Microsoft/TypeScript/issues/6307#issuecomment-168321011
