### ISSUE TITLE
Promise<string | string[]> should be interchangable with type Promise<string> | Promise<string[]>

### ISSUE THREAD

**Issue by mmc41** [Microsoft/TypeScript#13899]
**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)

2.1.5

**Code**

Currently if, I expect a type 'Promise<string | string[]>' but got a type 'Promise<string> | Promise<string[]>' the compiler will complain. I would expect the types to be interchangeable.

**Comment by RyanCavanaugh** [comment]
>  I would expect the types to be interchangeable.

This isn't correct. Without some justification for this statement I can't provide a meaningful counterexample.

**Comment by mmc41** [comment]
I have correct the example - the formatted text got the wrong GitHub markup so it distorted the example. Is it better?

**Comment by RyanCavanaugh** [comment]
The formatting was good enough to know what you meant. These types just simply are not the same. One is not substitutable for the other. They are different. If you provide some reasoning or example of why you think they should be the same (this should be our default assumption since they're not identical) I could explain why that's not the case.

**Comment by aleksey-bykov** [comment]
@mmc41 

consider:

```typescript
declare var x: (number | string)[];
declare var y: (number[]) | (string[]);
y = x; // <-- do you think you can do it?
```

**Comment by aleksey-bykov** [comment]
oh, it's the other way around, then yes, it should work, @RyanCavanaugh please fix

**Comment by aleksey-bykov** [comment]
indeed `Promise<string[]>` can be assigned to (a subtype of) `Promise<(string | number)[]>` being a special case of it (as long as we are structural), dying to see a counter example

**Comment by aleksey-bykov** [comment]
@RyanCavanaugh can we get a counterexample or reopen it?
