### ISSUE TITLE
Interface augmentation fails with imported modules

### ISSUE THREAD

**Issue by sinedied** [Microsoft/TypeScript#13897]
**TypeScript Version:**  2.0.10

I and have an issue when trying to augment one of Angular interface:

**Code**

```ts
// request-options-args.ts
import { RequestOptionsArgs } from '@angular/http';
declare module '@angular/http' {
  // Use this interface to extend requests options if needed
  export interface RequestOptionsArgs {
    skipErrorHandler?: boolean;
  }
}

// For reference, RequestOptionsArgs is defined in interfaces.d.ts and import in @angular/http
// @angular/http.d.ts
...
import { ConnectionBackend, RequestOptionsArgs } from './interfaces';
...
```

**Expected behavior:**

`RequestOptionsArgs` should retain the original interface properties, with the addition `skipErrorHandler` from my augmentation.

**Actual behavior:**

When trying to augment the `RequestOptionsArgs` from Angular this way, instead of being augmented it is overwritten (without further errors in my app code), as the interface only expose my added property but no more properties from the original interface.

However, changing my augmentation code use this module instead works as intended:
```ts
// request-options-args.ts
import { RequestOptionsArgs } from '@angular/http';
declare module '@angular/http/src/interface' {
  // Use this interface to extend requests options if needed
  export interface RequestOptionsArgs {
    skipErrorHandler?: boolean;
  }
}
```

Is this the supposed normal behavior??
If so, it seems very dangerous to me as to be able to augment the class, we need to know the implementation details of the `http` module, which is a bad practice as it may change in future versions.

Is there any other way to make it work as intended, or maybe it's just a bug?

**Comment by mhegazy** [comment]
Augmenting a re-export is not clear in its meaning nor impact. the source of the declaration is the module that should be augmented.

The compiler probably should give you an error if you try to augment a re-export.

**Comment by sinedied** [comment]
At least yes, an error or warning would be helpful in this case since I had no idea that it was a re-export in the first place.

> Augmenting a re-export is not clear in its meaning nor impact.
I'm wondering why is that, because from the "consumer" point of view it does not matter (and it shouldn't I think) if it is a re-export or not because it's implementation details at this point and it does not change the original intent?
Or maybe there could be side effects I'm not thinking of?

**Comment by mhegazy** [comment]
yes, it is the side effects. augmenting a re-export would not (at runtime) not only change this module, but the original as well. The type system does not track this now, it just silently not merge, which is incorrect either way you look at it.

**Comment by sinedied** [comment]
@mhegazy Sorry I was thinking more of what could be problematic if the merging was fixed, ie if augmenting a re-export would properly merge back in the original module instead of overwriting it like currently?

But yes, the current behavior is clearly nasty ^^

**Comment by NickClark** [comment]
Wow, ya, just got stuck on this for about an hour. Totally unclear why it was only being overwritten. Thanks so much for this Github issue, would have never figured it out on my own 😄

**Comment by gneuvill** [comment]
A pretty serious bug indeed that renders type checking null and void : 
```typescript
// A.ts
export interface A {
  a: string
}

export const getA: A = {
  a: "foo"
} 
```

```typescript
// B.ts
import A from './A'

declare module './A' {
  export interface A extends B {}
}

export interface B {
  b: number
}
```

```typescript
// Main.ts
import getA from './A'
import B from './B'

const testB = (b: B): number => b.b * 2

testB(getA) // incorrectly compiles and rightfully fails too late (at runtime)
```

Has it been forgotten ? Or is a fix unreasonably costly ?
