### ISSUE TITLE
Should a nested `declare module` be a compile error?

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#13901]
**TypeScript Version:**  nightly (2.2.0-dev.20170206)

**Code**

```ts
declare module "a" {
    module "b" {
        export const x: number;
    }
}

declare module "c" {
    import { x } from "b";
}
```

**Expected behavior:**

Error at declaration: `module "b"`

**Actual behavior:**

Error at use: `Cannot find module 'b'.`

**Comment by mhegazy** [comment]
it is an augmentation :). so if module "b" is already defined, you should get no error.
