### ISSUE TITLE
typescriptlang.org tsc version needs to be updated

### ISSUE THREAD

**Issue by rkavalap** [Microsoft/TypeScript#13902]
typescriptServices.js returns me the below header in source. 
/*!-----------------------------------------------------------------------------
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * monaco-typescript version: 2.0.1(68ba05ecd8ae00267184b3a26c859c1cbdff644f)
 * Released under the MIT license
 * https://github.com/Microsoft/monaco-typescript/blob/master/LICENSE.md
 *-----------------------------------------------------------------------------*/

From my understanding,
to use the 2.1.5 version of tsc playground needs to be updated from 2.1.1(ab02fc640209fa57ff4703663be59d93c37b2b5b @alexandrudima alexandrudima committed 19 days ago) of monaco-typescript repo. 
Issues were not enabled in monaco-typescript repo so opening one here.

**Comment by mhegazy** [comment]
update to 2.3
