### ISSUE TITLE
Encapsulate Field Refactoring

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#13911]
From https://github.com/Microsoft/vscode/issues/19905

Add a refactoring to encapsulate a field in a class, similar to https://msdn.microsoft.com/en-us/library/a5adyhe9.aspx:

```ts
class Foo {
    bar: string;
}
```

Encapsulating the `bar` field would change the class to:

```ts
class Foo {
    private _bar: string;

    public get bar() { return _bar; }
    public set bar(value: string) { _bar = value; }
}
```

**Comment by mhegazy** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/12417

**Comment by mjbvz** [comment]
Thanks @mhegazy 

Closing as duplicate
