### ISSUE TITLE
A tree-view of the project structure?

### ISSUE THREAD

**Issue by antonkh** [microsoft/TypeScript#13942]
I'm sure tsc has this structure internally, but have you guys considered exposing it in the API? It would be useful to see what top-level global variables/namespaces/functions are, what members they have and so on. This could be then used to inspect the structure of existing js libs.

I just needed to see what global vars a certain js lib (that was complied from a ts project, btw) uses that's included in my ts project, but couldn't find an easy way to do that with typescript.

**Comment by mhegazy** [comment]
have you tried navigate to (Ctrl + ,) in VS or Find symbol (Ctr+Shift +O) in VSCode ?

**Comment by antonkh** [comment]
It does give me the list of variables, but that list is flat and includes local variables as well. I was rather thinking about a tree-like view. For instance:

```js
var microsoft;
(function (microsoft) {
    var applications;
    (function (applications) {
        var telemetry;
        (function (telemetry) {
```

could be shown as

```
microsoft
  applications
    telemetry
```

Plus a list of variables it needs from outside, e.g. `window` and `XMLHttpRequest`.

**Comment by mhegazy** [comment]
That would be a request on vscode side. The result of that call to the tsserver is a tree structure.

**Comment by RyanCavanaugh** [comment]
Doesn't seem to be much demand for this. The API is available if someone wants to write a third-party tool or something.
