### ISSUE TITLE
Incorrect type inference of tuple when underlying array is extended

### ISSUE THREAD

**Issue by anfedorov** [Microsoft/TypeScript#13941]
**TypeScript Version:**  2.1.5

**Code**

```ts
let x: [string, number];

x = ["hello", 10];
x[3] = 'hi';

let y = x[2];
if (y == null) {
    console.log('yes ever');
    y;
}

```
<img width="255" alt="screen shot 2017-02-07 at 3 23 32 pm" src="https://cloud.githubusercontent.com/assets/9820/22716258/f7cd8afe-ed49-11e6-9eb2-6a6865fe3327.png">

```
$ node static/build/js/test.js 
yes ever
```

**Expected behavior:**

Before reading the docs, I would expect the type checker to find an error on line 4.

Given the feature set defined in the docs, I would expect the type at line 4 to be ` let y : undefined `.

**Actual behavior:**

Type is incorrectly inferred as ` let y : never `.

**Comment by aluanhaddad** [comment]
Using `--strictNullChecks` and typescript@2.1.5, the type of `y` is `string | number`, outside of the if statement, and `never` inside of it.
The inference of `never` is correct and expected because `y` is not not nullable, and therefore the block will never execute.
With respect to the inferred type of the array element, I believe it is covered by the proposal in #6229

**Comment by anfedorov** [comment]
But the block *does* execute and the code compiles without warnings or errors, even with `--strictNullChecks`:

```
code $ cat test.ts
let x: [string, number];

x = ["hello", 10];
x[3] = 'hi';

let y = x[2];
if (y == null) {
    console.log('yes ever');
    y;
}
code $ tsc --strictNullChecks test.ts 
code $ node test.js
yes ever
```

Thanks for the reference to the proposal — that is indeed a little closer to the behavior I would have expected.

**Comment by aluanhaddad** [comment]
@anfedorov Ah, I see your point now. I misread it as `y === null` which would not be taken. It seems there may be a bug here, but I am not sure.

**Comment by anfedorov** [comment]
Yup, y is `undefined`, and the proposal you linked might be the most elegant fix.

**Comment by mhegazy** [comment]
unfortunately  there is no way to do this correctly in the general case, e.g.: `for (var z = 0, z<10, z++) x[z];`. you can also find more details in https://github.com/Microsoft/TypeScript/issues/13778 on why the index signature intentionally, does not include `undefined`.

**Comment by anfedorov** [comment]
copying tuple behavior from Python seems like one way to handle it. i.e. `x[3] = 'hi'` could raise an error. another option is for `x[3] = 'hi'` to mutate the type of `x` to `[string, number, undefined, string]`, fixing the error inside the if block.

this seems to work fine in the playground: https://www.typescriptlang.org/play/index.html#src=let%20x%3A%20%5Bnumber%2C%20string%2C%20undefined%2C%20number%5D%3B%0D%0Ax%20%3D%20%5B1%2C%20'1'%2C%20undefined%2C%202%5D%3B%0D%0A%0D%0Ax%5B3%5D%20%3D%202%0D%0Ax%5B2%5D%20%3D%203%0D%0A

regardless, `x[z]` just like `x[prompt()]` could be `string | number | undefined`?

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
