### ISSUE TITLE
VS 2017 compiles TS unexpectedly

### ISSUE THREAD

**Issue by jods4** [Microsoft/TypeScript#13950]
I am running VS 2017, the Feb 7th update.

The IDE/Typescript insists on compiling and saving a `main.js` (when I open the solution, every time I change a file, e.g. when I delete `main.js` it instantly re-appears -- I have `allowJs: true`).

I can't figure out why it does or how to disable it.

I do have a `tsconfig.json`. I tried explicitely adding `compileOnSave: false`. Still compiles.
I couldn't find something relevant in the VS options.

I do not want VS to compile my code because I have a custom gulp build that does so.

**Comment by mhegazy** [comment]
Seems related to the issue reported in https://vsfeedback/comment/770127

**Comment by jods4** [comment]
@mhegazy not really :(
It's a large solution... I'll try to remove almost all bits and see if it still reproduces, if it doesn't it will be hard to create a minimal demo.
If it matters:
- this is a .NET Core `.csproj` kind of project.
- it has `typescript@2.1.5` in its `node_modules` (gulp build).

Let me know if there's anything I can do that might help you diagnose the issue.

**Comment by vladima** [comment]
I cannot repro it locally:
- created a new .NET Core Web App
- added a few `.ts` files and `tsconfig.json`
- verified that if `compileOnSave` is set to `true` in config file then compile on save works as expected
- verified that if `compileOnSave` is set to `false` in config file then nothing happens if I save the `.ts` file

The symptoms sound strange: can you please check when you open `main.ts` what is displayed as its containing project?
![image](https://cloud.githubusercontent.com/assets/8052307/22758641/6ebfad6c-ee04-11e6-88de-6556f0b4120b.png)

**Comment by jods4** [comment]
Here are some infos, let me know if there's anything else I can provide.

My ASP.NET core app has all the front-end under `/App`. This is also where `tsconfig.json` is found, i.e. the tsconfig is _not_ at the root of my project.

Because it generates the `main.js` inside `/App`, it creates lots of fun issues because it becomes part of the sources, like TS5055 _cannot write file ... because it would overwrite input file._.

The box you highlighted is confusing. For `main.ts` and `main.js`, it says `App (tsconfig project)` and  `Miscellaneous` but interchangeably. Right now the TS is misc and JS is App but I swear moments ago it was the opposite.

I have `typescript@2.1` in my `node_modules` folder at the root of my project.

I have moved my PATH global web tools above VS tools folder because I have more recent NodeJS + NPM versions.

There also seems to be some problem with the built-in TS. It uses `lib.es2017.d.ts` from the VS folder but highlights the last two lines as _"not found"_.
```ts
/// <reference path="lib.es2017.sharedmemory.d.ts" />
/// <reference path="lib.es2017.string.d.ts" />
```

Here's my tsconfig:
```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "amd",
    "moduleResolution": "classic",
    "outFile": "main.js",
    "allowJs": true,
    "lib": [ "dom", "es2017" ],
    "skipDefaultLibCheck": true,

    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "noFallthroughCasesInSwitch": true
  }
}
```

I have the new lightweight solution loading enabled.

**Comment by jramsay** [comment]
@jods4:  We're now able to repro the unexpected compile issue and missing d.ts references with the information you included above.   Many thanks!

**Comment by jods4** [comment]
Glad that this was fixed. 
Now that you know the cause, can you suggest a workaround before the next update?
This bug is highly annoying and requires locally modified configs to fight it.
