### ISSUE TITLE
VS 2017 complains about unsupported extensions

### ISSUE THREAD

**Issue by jods4** [Microsoft/TypeScript#13951]
I am running VS 2017 RC, Feb 7th update.

In my project the source folder mixes `.ts` and `.html` files.
It's an Aurelia application and the HTML files are views for each ViewModel.

When I open this project in IDE, there are a lot of Errors in the Error List. One for each HTML file, complaining that it is an unsupported extensions.

I don't have `include` or `exclude` in my `tsconfig.json`. It works on the assumption that all files in the tsconfig folder are part of my TS project.

It seems this is a change of behavior from previous TS versions, which would silently ignore non js/ts/jsx/tsx files in the source folder. I think it's common to have other files along (readme.txt, data.json, view.html) and ignoring them doesn't seem to warrant an error.

**Comment by jramsay** [comment]
@jods4:  thanks for filing this issue!  Would you be able to point us to a sample project where this repros & provide repro steps on how you're opening the project?  I've tried opening a few of your samples from the aurelia-webpack-build repo using Open > Folder in VS and haven't yet been able to hit the issue.

**Comment by jods4** [comment]
@jramsay Yes, it's not from those small demos. 
This is from a large (private) solution inside an ASP.NET Core project that was migrated to `.csproj`. 
I shall add that there is `typescript@2.1` inside the `node_modules` folder of the project.

Is this behavior not expected?
If it's not I'll try to watch out for it and hopefully be able to extract bits to repro it.

**Comment by jods4** [comment]
@jramsay I don't get it. 
The errors sometimes disappear and sometimes re-appear. I have no idea what triggers them.

There is more info on my config in #13951.

At first I was going to say I could not reproduce the problem anymore... and just as I was about to write that, here's what appeared:
![image](https://cloud.githubusercontent.com/assets/3832820/22773393/3aa4c8ca-eea2-11e6-9e04-ae4b85ae705b.png)

**Comment by jramsay** [comment]
@jods4:  Thanks!  I'm able to repro this now by using the info you provided in #13950 - much appreciated.
