### ISSUE TITLE
Local @types

### ISSUE THREAD

**Issue by sternbel** [Microsoft/TypeScript#13952]
Hi all,

I'm developing 2 libraries `A` and `B` in different folders where `A` is exported as target es5 and module commonjs.

In `B` I'd like to use `index.d.ts` from `A` among other @types libraries which are in node_modules folder. And then use some classes from `A` via in import like this: `import {MyClass} from "a";`.
Unfortunately this doesn't work: a not found in `node_modules/@types/a` etc.
I tried without success with:
 
```typescript
"baseUrl": ".",
    "paths": {
      "a": [
        "lib/a"
      ]
    },
```

How to setup typescript to find lib/a/index.d.ts without modifying my import with relative path (e.g. `import {MyClass} from "../lib/a/index";`)?

**Comment by mhegazy** [comment]
The target in the "paths" list is relative to `"baseUrl"`. so your "paths" here says `"a" => "./lib/a"` so you either want to set the `"baseUrl"` to `"../"` or set the target to `"../lib/a"`.

**Comment by sternbel** [comment]
Hi @mhegazy,

Thanks a lot, it's working now!
