### ISSUE TITLE
Possible bug with index signatures and the ? : operator

### ISSUE THREAD

**Issue by Jendrik3** [Microsoft/TypeScript#13953]
**TypeScript Version:**  2.1.5

**Code**

```ts
//Example 1
const foo: { x: number } | {} = { x: 1 };
const bar: { [index: string]: never } = foo; //compile error

//Example 2
const foo2: { x: number } | {} = true ? { x: 1 } : {};
const bar2: { [index: string]: never } = foo2; //ok
```
**Expected behavior:**
Both examples should behave the same way, since the types are the same.

**Actual behavior:**
The first example gives a compile error:
```
bug.ts(2,7): error TS2322: Type '{} | { x: number; }' is not assignable to type '{ [index: string]: never; }'.
  Type '{ x: number; }' is not assignable to type '{ [index: string]: never; }'.
    Property 'x' is incompatible with index signature.
      Type 'number' is not assignable to type 'never'.
```
The second example compiles fine. I'm not sure, but I don't think it should.

**Comment by sandersn** [comment]
Typescript uses the assigned type of `foo` and `foo2` because it can track their assignments in the current scope. So `foo2` is fine because its type is `{}`, which is indeed assignable to `{ [index: string]: never }`; it doesn't have any properties that could violate the constraint. `foo` fails because its type is `{ x: number }`.

**Comment by Jendrik3** [comment]
I don't understand how `foo2` has type `{}`. What if you replace `true` with `Math.random() < 0.5`, would that change anything? How is the type `{ x: number } | {}` compatible with `{ [index: string]: never }`

**Comment by sandersn** [comment]
Oh, looks like the type of ?: is more complicated than I thought. Looking at the code, I see (in `getBestChoiceType`) that if the `whenTrue` type is assignable to the `whenFalse` type, it returns the `whenFalse` type. And vice-versa. If neither are assignable, then the type is the union of the `whenTrue | whenFalse`.

`{ x: number }` is assignable to `{}`, so the ternary's type is `{}`, regardless of whether we can constant-fold the conditional.

(The spec in section 4.20 just says that the type is the union of `whenTrue | whenFalse`. I think with, subtype reduction, that is equivalent to the rule I described above. It's just less efficient.
