### ISSUE TITLE
instanceof is broken when class extends Error type

### ISSUE THREAD

**Issue by tikurahul** [Microsoft/TypeScript#13965]
**TypeScript Version:**  2.1.1

```ts
class BaseError extends Error {}
class Error1 extends BaseError {}

let error = new Error1();
console.log(error instanceof Error1);
```

**Expected behavior:**
prints `true`.

**Actual behavior:**
prints `false`.

**Note:**
This happens only when a type extends `Error`. 
After removing `extends Error` from BaseError everything works as expected.

**Links**
[Test case](https://www.typescriptlang.org/play/#src=class%20Base%20extends%20Error%20%7B%20%7D%0D%0Aclass%20Derived%20extends%20Base%20%7B%20%7D%0D%0A%0D%0Alet%20d%20%3D%20new%20Derived()%3B%0D%0Aconsole.log(d%20instanceof%20Derived)%3B%0D%0A)

**Comment by DanielRosenwasser** [comment]
Unfortunately this is a change that we made to try to try to adopt a more standard-compliant emit so that we could enable Polymer to work with TypeScript. 

For background, was an intentional change in 2.2 (see #12123 and [the section on our wiki](https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#extending-built-ins-like-error-array-and-map-may-no-longer-work)), but is difficult to overcome through compilation. I believe there's some conversation in #12790 for workarounds.

A workaround you can take now is create an intermediate class that you can extend from.

```ts
export interface MyErrorStatic {
    new (message?: string): RxError;
}
export interface MyError extends Error {}

export const MyError: MyErrorStatic = function MyError(this: Error, message: string) {
    const err = Error.call(this, message);
    this.message = message;
    this.stack = err.stack;
    return err;
} as any;

export class HttpError extends MyError {
    // ...
}

```

In TypeScript 2.2, you'll be able to set the prototype on your own.

```ts
// Use this class to correct the prototype chain.
export class MyError extends Error {
    __proto__: Error;
    constructor(message?: string) {
        const trueProto = new.target.prototype;
        super(message);

        // Alternatively use Object.setPrototypeOf if you have an ES6 environment.
        this.__proto__ = trueProto;
    }
}
```

Sorry for the inconvenience of this.

**Comment by tamf** [comment]
Seriously...

[https://media.giphy.com/media/sIE0hveuiwCNG/giphy.gif](url)

**Comment by creativeprogramming** [comment]
What's the issue this is a duplicate of? I think this is still unresolved.

**Comment by DanielSchaffer** [comment]
For anyone looking for a workaround that will let them test their custom error classes, I made a shim that does so: [DanielSchaffer/ts-custom-error-shim](https://github.com/DanielSchaffer/ts-custom-error-shim)

**Comment by taoyouh** [comment]
@cjam You can set the prototype yourself as noted here: https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#extending-built-ins-like-error-array-and-map-may-no-longer-work

**Comment by banacorn** [comment]
@cjam breaking point reached, tired of JS stuff, I'm now digging into ReasonML.

**Comment by odahcam** [comment]
Was this fixed?

**Comment by nediamond** [comment]
Workaround, requires unique attrs on each error:
`
function isError1(error: Error): error is Error1 {
  return (<Error1>error).attr1 !== undefined;
}
`

**Comment by stephengardner** [comment]
I ran into this today.  Is this a bug?

**Comment by dhessler** [comment]
@DanielRosenwasser I think this should be re-opened; this feels seriously broken as-is.

**Comment by RyanCavanaugh** [comment]
Locking due to unproductive/repetitive discussion

[Please read the FAQ entry for details][(https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#extending-built-ins-like-error-array-and-map-may-no-longer-work)
