### ISSUE TITLE
Is it possible to only transform a subset of fields in mapped types

### ISSUE THREAD

**Issue by marty-wang** [Microsoft/TypeScript#13968]
**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)

According to the doc, like below, it seems that one can transform all the fields in the mapped types. I wonder if it is possible that one can select and only transform a subset of fields?

```
type Nullable<T> = { [P in keyof T]: T[P] | null }
type Partial<T> = { [P in keyof T]?: T[P] }
```

For example,  
```
interface Size { width: number, height: number }
```
Is there a generic way to only transform width to optional and keep height as is?

**Comment by DanielRosenwasser** [comment]
At the moment, it's not possible (as far as I've been able to experiment). It might be if we had a type difference operator for union types, or if we had conditional mappers, it might be.

I'd like to suggest that one thing you could do is intersect with an object that picks the original properties out (i.e. `Nullable<Rectangle> & Pick<Rectangle, "height">`) but that doesn't seem to work.

**Comment by DanielRosenwasser** [comment]
As an update to the above comment, that seems to work just fine with the exception of creating an odd union type (`number | (number & null)`)

**Comment by marty-wang** [comment]
Thanks @DanielRosenwasser. In my case, what I actually need to have something like below, except that I dont know how to do **Remove**. Do you know how?

```
Remove<Rectangle, 'height'> & Nullable<Pick<Rectangle, 'height'>>
```

**Comment by gcanti** [comment]
What about

```ts
interface Size { width: number, height: number }

/** make all properties not in K (keys) optional */
type Semipartial<A, K extends keyof A> = Partial<A> & Pick<A, K>;

type OptionalWidth = Semipartial<Size, 'height'>;

const ow1: OptionalWidth = { height: 1 }
const ow2: OptionalWidth = { height: 1, width: undefined }
const ow3: OptionalWidth = { height: 1, width: 2 }
const ow4: OptionalWidth = { height: 1, width: 'a' } // error: Type 'string' is not assignable to type 'number | undefined'
```

Also 

```ts
/** make all properties not in type B optional */
type Diff<A, B> = Semipartial<A, keyof B & keyof A>;

interface Depth { depth: number, height: number }

type OptionalWidth = Diff<Size, Depth>;

const ow1: OptionalWidth = { height: 1 }
const ow2: OptionalWidth = { height: 1, width: undefined }
const ow3: OptionalWidth = { height: 1, width: 2 }
const ow4: OptionalWidth = { height: 1, width: 'a' } // error: Type 'string' is not assignable to type 'number | undefined'
```

**Comment by marty-wang** [comment]
@gcanti What I need to make specific fields optional and keep the rest as are.

To give full context of what I am trying to do, in the React world, it is common to create higher order component and in the process one can manipulate the props of the resultant higher order component. Below is part of my code.

```
interface ISize {
    width: number;
    height: number;
}

// Something that can make given types optional
type MakeOptional<T, K extends keyof T> = ...

const enableContainerAware = <TP extends ISize>(SizedComponent: React.ComponentClass<TP>) => (
    class extends React.Component<MakeOptional<TP, 'width'|'height'>, ISize> {

        public state: ISize = { width: 0, height: 0 };

        public render() {
            let { width, height } = this.props;

            width = width !== null && width !== undefined ? width : this.state.width;
            height = height !== null && height !== undefined ? height : this.state.height;

            return (
                <div
                    style={{ width: '100%', height: '100%' }}
                    ref={(element) => this._element = element}>
                    <SizedComponent
                        {...this.props}
                        width={width}
                        height={height}/>
                </div>
            );
        }
...
);
```

What I am missing is that **MakeOptional** type. If there is any other way to do it, I am all ears.

Given the popularity of the higher order component, such ability will be really useful.

**Comment by rikkertkoppes** [comment]
To add another use case, I often have three different versions of interfaces:

- Persisted, having an `id` and `link` property, which are already stored
- Transient, with `id` and `link` optional, for new resources in the frontend
- Partial, with everything optional, for updates

Since the majority of the code deals with persisted values, I'd like to keep the code as concise as possible on those places. For example I have a user

    interface User {
        id: string;
        link: string;
        name: string;
        email: string;
        ...
    }

But when creating a new User, I don't have id and link yet (those are created when saved). So I'd like to have

    Transient<User>

To equal

    interface User {
        id?: string;
        link?: string;
        name: string;
        email: string;
        ...
    }

Which is to just copy everything and make specific fields optional.

**Comment by rikkertkoppes** [comment]
Any reason why this is closed? Is this already possible somehow. Some pointers with the close message would be nice
