### ISSUE TITLE
error TS18003: No inputs were found in config file...

### ISSUE THREAD

**Issue by oldrich-s** [microsoft/TypeScript#13978]
I would like to watch all `*.ts` files in a folder and automatically compile them to `*.js`. The folder is empty to start with but then new `*.ts` files are added into it.

As it is now, the compiler errors because there are no files in the folder. I think that the error should not occur when `watch=true` as `*.ts` files can be added later on...

What do you think?

**Comment by mhegazy** [comment]
So no single .ts file anywhere?

**Comment by czb** [comment]
Well it is rare but it can happen so I need to deal with it ;)

I personally think that if you allow adding ts files during watch then you should also allow starting with no files as it is a legitimate use case.

**Comment by mhegazy** [comment]
I think the error message should still be shown, but it should not block watching.

**Comment by whitecolor** [comment]
@mhegazy I think there should be at least flag that would prevent this "error" from failing (exiting with code 1),  for example this breaks some automatic build process if it happens to be on folders that are not yet TS converted.  Just really strange error, warning should be yes.
