### ISSUE TITLE
Number type narrowing from `number|undefined` within arithmetic conditions

### ISSUE THREAD

**Issue by Knagis** [Microsoft/TypeScript#13974]
**TypeScript Version:**  2.1.5

JavaScript evaluates `undefined > 0` (and other similar constructs) as `false` and this could be used for type narrowing. Unlike comparisons with `null`, `undefined` is rather consistent (<https://jsfiddle.net/4u11p7u0/1/>). 

**Code**

```ts
let a: number | undefined;

function expectNumber(a: number) { }

if (a != null) {
    // works
    expectNumber(a);    
}

if (a > 0) {
    // does not work but should because "undefined > 0 === false"
    expectNumber(a);
}
```

**Expected behavior:**

the `if (a > 0)` branch narrows the type to number.

**Actual behavior:**

the type of `a` within the branch stays as `number|undefined`.

**Comment by ahejlsberg** [comment]
We're actually going in the opposite direction on this one. In the upcoming TypeScript 2.2 release, for an operand `a` that is possibly `undefined` we consider the expression `a > 0` to be an error. See #13483 for more details.

Generally the results of the `<`, `>`, `<=`, and `>=` operators with `null` and `undefined` operands are surprising and merit reporting an error. For example, `a > 0` and `a < 0` are *both* false when `a` is `undefined`.

**Comment by Knagis** [comment]
Thank you for the information.
