### ISSUE TITLE
Typescript fails to throw error when a generic is assigned to another generic of whom it's generic type is a superset

### ISSUE THREAD

**Issue by scamden** [Microsoft/TypeScript#13970]
**TypeScript Version:**  2.1.4

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
export interface MyInterface {
  myFunction(): Promise<number | string>;
}

export class MyClass implements MyInterface {
  async myFunction() { // inferred return type Promise<number | string | string[]>
    let num = 1;
    let text = 'text';
    if (num) {
      return num;
    }
    if (text) {
      return text;
    }
    return [text];
  }
}
```

**Expected behavior:**
TS throws an error that MyClass incorrectly implements MyInterface
type `Promise<number | string | string[]>` not assignable to `Promise<number | string>`

otherwise a client using the class as `MyInterface` can call the method and only handle a return promise of string or number and have errors when the promise is resolved with the array.

**Actual behavior:**
No error is thrown. (It's worth noting this doesn't repro without the generic. If for example the method were not async.) This also is not thrown if the return type is manually specified as `Promise<number | string | string[]>` just to be clear inference is not to blame.

**Comment by scamden** [comment]
here's an even simpler example that doesn't require classes or interfaces

```
const myPromise: Promise<string> = 
  new Promise<string | string[]>((resolve) => { resolve(['anything']) })

myPromise.then(value => {
  value.substr(0, 3); //throws an error because arrays lack this function
});
```

and using inference rather than explicit same thing:
```
 const myPromise: Promise<string> = new Promise((resolve) => {
    let text = '';
    if (text) {
      resolve(text);
    }
    resolve([text]);
  });

  myPromise.then(value => {
    value.substr(0, 3); //throws an error because arrays lack this function
  });
```

**Comment by scamden** [comment]
code example for without the generic to prove that normally a superset is unassignable

```
function myFunction() { // inferred return 'number | string | string[]'
  let num = 1;
  let text = 'text';
  if (num) {
    return num;
  }
  if (text) {
    return text;
  }
  return [text];
}
const myValue: string | number = myFunction(); //ts throws unassignable error
```

**Comment by scamden** [comment]
@gmoothart @evmar @bb @joshk @huerlisi sorry to ping you all. not sure who should take a look at this. seems like a pretty major bug.

**Comment by DanielRosenwasser** [comment]
This is actually a result of structural compatibility and function parameter bivariance. Essentially the results of `Promise#then` is compared between the two, and then the parameter type of arguments are compared in a bivariant way. Since the contravariant side succeeds, the two are compatible in either direction.

This is undesirable, but we're thinking about fixes. See [this section in our FAQ for more details](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-function-parameters-bivariant).

**Comment by scamden** [comment]
@DanielRosenwasser ok :) i don't fully understand the terms you used but i think i get the gist. glad to hear it's being worked on :)

**Comment by mhegazy** [comment]
The correct error should be reported with https://github.com/Microsoft/TypeScript/pull/15104.

**Comment by scamden** [comment]
awesome!

**Comment by DanielRosenwasser** [comment]
> @DanielRosenwasser ok :) i don't fully understand the terms you used but i think i get the gist. glad to hear it's being worked on :)

Sorry about that - that was a bit more jargon-y than I realized. 😄 

![image](https://cloud.githubusercontent.com/assets/972891/26220693/7999d318-3bc8-11e7-9f79-44ad256789a9.png)
