### ISSUE TITLE
Type comparison incorrect with inherited string literals

### ISSUE THREAD

**Issue by davewasmer** [Microsoft/TypeScript#13985]
**TypeScript Version:**  2.2.0

**Code**

```ts
class Foo {
    bar: "boop";
}
class Buzz extends Foo {
    bar = 'boop'
}
```

[Playground Link](https://www.typescriptlang.org/play/index.html#src=class%20Foo%20%7B%0D%0A%20%20%20%20bar%3A%20%22boop%22%3B%0D%0A%7D%0D%0A%0D%0Aclass%20Buzz%20extends%20Foo%20%7B%0D%0A%20%20%20%20bar%20%3D%20'boop'%0D%0A%7D%0D%0A)

**Expected behavior:**

Compiles without error.

**Actual behavior:**

```
Class 'Buzz' incorrectly extends base class 'Foo'.
  Types of property 'bar' are incompatible.
    Type 'string' is not assignable to type '"boop"'.
```

----

Apologies if I'm missing something obvious, this is by design, or there are existing issues for this. I searched and didn't find anything like it.

**Comment by ahejlsberg** [comment]
See #6118. Ideally we'd have the declaration of `bar` in `Buzz` somehow contextually typed by the declaration of `bar` in `Foo`, but it turns out not to be an easy change.
