### ISSUE TITLE
Visual Studio Unit Test Integration

### ISSUE THREAD

**Issue by chriscamicas** [Microsoft/TypeScript#1398]
Could you please provide a unit test platform integrated within Visual Studio Test Explorer and of course TFS builds.

I know about Chutzpah extension, but : 
- it doesn't integrate well with VS
- it's very slow (iterating over the entire solution content)
- it doesn't follow the new tools for front/web dev (eg TaskRunnerExplorer) 

I also know about Javascript Unit Test framework (QUnit, Jasmine), but they don't integrate with VS either.

Thanks

**Comment by mhegazy** [comment]
This is out of scope of this repo. We would love to see this end-to-end integration happening though. The TypeScript core team does not have resources to address all such requests. We would be happy to work with any interested parties to facilitate the solution in any way possible, but I do not think we can take on such feature at the time being.

**Comment by resnyanskiy** [comment]
@NoelAbrahams thank's for the link to NTVS and explanation :+1:
