### ISSUE TITLE
QuickInfo for property of union: Do something smarter than concatenate

### ISSUE THREAD

**Issue by andy-ms** [microsoft/TypeScript#13984]
**TypeScript Version:**  nightly (2.2.0-dev.20170209)

**Code**

```ts
interface A {
    /** This is the */
    x: number;
}

interface B {
    /** documentation for x. */
    x: string;
}

function f(ab: A | B) {
    ab.x;
}
```

**Expected behavior:**

Something indicating that these are two separate pieces of documentation.

**Actual behavior:**

When I hover over `x` in `ab.x` I see:

```
(property) x: string | number
This is the documentation for x.
```

**Comment by RyanCavanaugh** [comment]
Punting until someone else notices
