### ISSUE TITLE
Suggestion: Add signature for Object.keys() to remove "element implicitly has an 'any'" error

### ISSUE THREAD

**Issue by nitzantomer** [Microsoft/TypeScript#13989]
When using `noImplicitAny` the following code:
```
interface Point3D {
    x: number;
    y: number;
    z: number;
}

let p1: Point3D = { x: 0, y: 0, z: 0 };
let p2 = {} as Point3D;
Object.keys(p1).forEach(key => p2[key] = p1[key]);
```
Results with the following error:

> error TS7017: Element implicitly has an 'any' type because type 'Point3D' has no index signature

There are ways to avoid it:

1. Use `suppressImplicitAnyIndexErrors`
2. Adding an index signature to the interface
3. Cast `p2` and `p1` to `any`
4. Don't use `noImplicitAny`

There's another option:
```
type keys = keyof Point3D;
(Object.keys(p1) as keys[]).forEach(key => p2[key] = p1[key]);
```

That can be supported by adding a signature for `Object.keys` in the `lib.d.ts`:
```
interface ObjectConstructor {
    ...
    keys(o: any): string[];
    keys<T>(o: T): (keyof T)[];
}
```
Then the original code would work without the need for `suppressImplicitAnyIndexErrors`.

**Comment by mhegazy** [comment]
Just to be clear, the error is correct to me. Types in typescript are not final, so there is no guarantees that `p1` does not have more keys.. consider:

```ts
function fix(p: Point3D) {
    Object.keys(p).forEach(key => p[key] = p[key].toFixed()); // p[comment] does not have 
}

let p1 = { x: 0, y: 0, z: 0, comment: "my 3d point" };
fix(p1);
```

If you are sure, then cast before access. Alternatively, you can define an index signature on your `Point3D`.

**Comment by KostyaTretyak** [comment]
> Alternatively, you can define an index signature on your Point3D

@mhegazy, but if we define this way its not works:

```ts
type WithSignaturePoint3D = { [P in 'x' | 'y' | 'z']: number };

function fix(p: WithSignaturePoint3D)
{
  // Why here throw error?
  Object.keys(p).forEach(key => p[key] = p[key].toFixed());
}
```

**Comment by mhegazy** [comment]
`{ [P in 'x' | 'y' | 'z']: number }` === `{ x: number; y: number; z: number }`. So not sure i understand the question.

**Comment by KostyaTretyak** [comment]
@mhegazy, you say that

> Alternatively, you can define an index signature on your Point3D

I define `WithSignaturePoint3D` with index signature, but TypeScript still throw error.
