### ISSUE TITLE
(withdrawn) type inference of a heterogeneous list of classes fails

### ISSUE THREAD

**Issue by anfedorov** [Microsoft/TypeScript#13987]
**TypeScript Version:**  2.1.6

**Code**

```ts
class Animal { }
class Snake extends Animal { }
class Rhino extends Animal { }
class Elephant extends Animal { }

let zoo = ["", 3, null, new Snake()];

zoo.push(new Elephant())
zoo.push(3)
```
**Visual Studio Code Screenshot**

<img width="334" alt="screen shot 2017-02-09 at 3 43 08 pm" src="https://cloud.githubusercontent.com/assets/9820/22807959/927c9438-eede-11e6-8ac0-0c6759ef2b9e.png">

**Expected behavior:**
For `zoo` to be of type `(string | number | null | Snake | Elephant)[]`, or, per [the documentation](https://www.typescriptlang.org/docs/handbook/type-inference.html) ("we make no inference about the array element type"), `any[]`.

**Actual behavior:**
Visual Studio Code reports `zoo` as type `(Snake | null)[]` but does not mark error when a `new Elephant()` is pushed.

Apologies if this is a bug in VSC — let me know if it would be more appropriate to move it there.

**Comment by RyanCavanaugh** [comment]
https://github.com/Microsoft/TypeScript/wiki/FAQ#why-do-these-empty-classes-behave-strangely

**Comment by anfedorov** [comment]
Original example was as it is in the docs, with the classes having a `keeper` property, and behaved identically. I just simplified it for the sake of brevity here.

**Comment by anfedorov** [comment]
(i.e. I think the issue is with the inferred type of an array, not with classes)

**Comment by RyanCavanaugh** [comment]
If the classes were identical, then the *next* question in the FAQ applies

**Comment by anfedorov** [comment]
Good call, thanks!
