### ISSUE TITLE
Path2D definition is missing

### ISSUE THREAD

**Issue by impankratov** [Microsoft/TypeScript#13994]
**TypeScript Version:**  2.1.6

**Code**

```ts
// Try to instantiate new Path2D object to work with canvas
const rect = new Path2D();
```

**Expected behavior:**
Typescript compiler should now about Path2D and compile to javascript.

**Actual behavior:**
Got an error from typescript: Cannot find name 'Path2D'. Looks like there is no Path2D definition.

There's a related question on StackOverflow with some actual definitions ready: [Using Path2D in a TypeScript project is not resolved](http://stackoverflow.com/questions/34109921/using-path2d-in-a-typescript-project-is-not-resolved). Could we integrate those definitions?

**Comment by mhegazy** [comment]
Should be fixed in latest.
