### ISSUE TITLE
TSServer Crashes when Opening file from Mapped Sharepoint Drive

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#13997]
From: https://github.com/Microsoft/vscode/issues/20445

**TypeScript Version:**  2.1.6

This issue is similar to #13874 but when opening a mapped sharepoint drive on windows instead of opening the WebDAV drive directly.

**Repo Steps**
* In windows, mount a sharepoint WebDAV drive by going to `This PC` ->  `map network drive`.
    * This should not be the root folder where the js/ts files are stored
    * I used https://microsoft.sharepoint.com/teams/DD_OTP/Documents/ mounted on the z drive
* Open a file on this drive in VSCode. For example: `Z:\Java and Open Tools\Node\test`

This produces the same symptoms as #13874 

```js
[Info  - 11:32:02 AM] Using tsserver from location: c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\node_modules\typescript\lib\tsserver.js
[Trace - 11:32:02 AM] Sending request: configure (33). Response expected: yes. Current queue length: 0
Arguments: {
    "hostInfo": "vscode"
}
[Trace - 11:32:03 AM] Response received: configure (33). Request took 467 ms. Success: true 
[Trace - 11:32:03 AM] Sending request: compilerOptionsForInferredProjects (34). Response expected: yes. Current queue length: 3
Arguments: {
    "options": {
        "module": "CommonJS",
        "target": "ES6",
        "allowSyntheticDefaultImports": true,
        "allowNonTsExtensions": true,
        "allowJs": true,
        "jsx": "Preserve"
    }
}
[Trace - 11:32:03 AM] Response received: compilerOptionsForInferredProjects (34). Request took 483 ms. Success: true 
Result: true
[Trace - 11:32:03 AM] Sending request: open (35). Response expected: no. Current queue length: 2
Arguments: {
    "file": "z:/Java and Open Tools/Node/test/main.js",
    "fileContent": "console.log()\r\nfdsaf gdsczx"
}
[Trace - 11:32:03 AM] Sending request: geterr (36). Response expected: no. Current queue length: 1
Arguments: {
    "delay": 0,
    "files": []
}
[Trace - 11:32:03 AM] Sending request: geterr (37). Response expected: no. Current queue length: 0
Arguments: {
    "delay": 0,
    "files": [
        "z:/Java and Open Tools/Node/test/main.js"
    ]
}
[Error - 11:32:03 AM] TSServer exited with code: 3221226356
````

**Comment by kieferrm** [comment]
@mhegazy an update?

**Comment by mhegazy** [comment]
Not sure there is an easy fix here. Node crashes. the options we have are either:
- have a new process to probe if watching is possible.
- have VSCode tell us what directories is safe to watch.
- disable watching for all folders mapped to network share.

I should add, this issue

**Comment by mjbvz** [comment]
There is probably a better way to do this, but on windows would the `net use` command work? This would let us understand if target drive is a mapped network drive. For example:

```
> net use z:
Local name        z:
Remote name       \\microsoft.sharepoint.com@SSL\DavWWWRoot\teams\DD_OTP\Documents\Java and Open Tools
Resource type     Disk
The command completed successfully.
```

**Comment by semmy2010** [comment]
As soon as I opened the *.ts of  TypeScript file, it reported the error. I did not mapped the virtual disk.
