### ISSUE TITLE
How to block typescript 2.0 from walking up all parent directories while resolving modules?

### ISSUE THREAD

**Issue by zakimaksyutov** [Microsoft/TypeScript#13992]
Upgraded to Typescript 2.0 (2.1.6) and it started giving "Duplicate identifier" errors. After taking a closer look it turned out that Typescript started importing @types from all upper directories (essentially other projects).

What should be the configuration to let Typescript to ignore upper node_modules?

src
 └── node_modules << *** how to ignore it? ***
     └── @types

 └── my.app << *** how to build this folder and down only? ***
         └── node_modules
             └── @types

EDIT: Here is an example of error I'm getting:

typings/globals/mocha/index.d.ts(30,13): error TS2300: Duplicate identifier 'describe'. ../../../node_modules/@types/jasmine/index.d.ts(9,18): error TS2300: Duplicate identifier 'describe'.

listFiles: true shows @types/jasmine being imported from upper folder:

C:/src/<project>/<folder>/<my.app>/typings/globals/mocha/index.d.ts
C:/src/node_modules/@types/jasmine/index.d.ts
If I rename upper node_modules folder then build succeeds.

http://stackoverflow.com/questions/42150920/how-to-block-typescript-2-0-from-walking-up-all-parent-directories-while-resolvi

**Comment by mhegazy** [comment]
use `--types node` or set `"types" : ["node"]`. this tells the compile to **only** include `@types\node` in your compilation.

using `--types` or set `"types": []` to avoid including any of them.

**Comment by zakimaksyutov** [comment]
Thank you!

Used "typeRoots": ["./typings"] and it resulted in 

error TS2688: Cannot find type definition file for 'globals'.

Specifying --types didn't fix this error.

**Comment by mhegazy** [comment]
`typeRoots` change where the system is looking for packages. unless you want to include files from typings, do not change it. you can find more information about types and typeroots at http://www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types

**Comment by blakeembrey** [comment]
@zakimaksyutov Typings puts things under two directories (globals vs modules) - try with `typings/globals` if you're using Typings.

**Comment by jurosh** [comment]
Is there real solution ? I've tested all suggested options but with no luck.. compilation failed because in parent `../../node_modules` is another project which will duplicate all typings...

**Comment by evil-shrike** [comment]
I had the same issue:
given a project with tsconfig and inside it there's a folder with a completely separated ts-project with its own tsconfig. it didn't want to compile as tsc was importing `node_modules/@types` from parent folder.
Settings `"types" : ["node"]` in that tsconfig.json did help.

**Comment by peterjwest** [comment]
As far as I know, using `"typeRoots": ["./node_modules/@types"]` should prevent typescript looking in parent directories, but it doesn't solve the problem for me.

**Comment by rjmunro** [comment]
Here's the stupid fix we are now using:

```
  "scripts": {
    "build": "if [ -d ../node_modules ]; then mv ../node_modules ../node_modules_tmp; fi; <normal build command here>; if [ -d ../node_modules_tmp ]; then mv ../node_modules_tmp ../node_modules; fi",
  }
```
