### ISSUE TITLE
VS2017 doesn't respect editorconfig

### ISSUE THREAD

**Issue by jods4** [microsoft/TypeScript#14008]
Using VS 2017 RC, Feb 7th release.

I have a `.editorconfig` at the root of my solution, that contains:
```ini
[*]
indent_size = 2
```

This is properly picked in the TS editor in the sense that when I hit `TAB` I get 2 spaces.

But the automatic formatting is not respecting this and is constantly fighting with me.

Any time I trigger an automatic format (e.g. hitting `ENTER` at the end of a line after `{`) my code is reformatted and everything is aligned on 4 spaces.

**Comment by mhegazy** [comment]
This is a general VS feature request and not specific to TS. I would suggest posting this on https://visualstudio.uservoice.com/forums/121579-visual-studio-ide instead. TypeScript gets these settings in the form of an API calls, so assuming VS supports reading/using editorconfig files, TS should get that almost for free.

**Comment by jods4** [comment]
@mhegazy Are you 100% sure?
Because VS _does_ pick up my `.editorconfig` settings and in fact it does work in the editor. As I wrote above, hitting `TAB` actually produces 2 spaces.

It's the code formatting service -- which I assume is specific to TS? -- that doesn't apply those preferences.

**Comment by mhegazy** [comment]
let me check and get back to you on this.

**Comment by mhegazy** [comment]
I was wrong. the APIs do exist, we just need to call them.

**Comment by methodbox** [comment]
I realize this is for Visual Studio, but the same issue exists (and multiple issues have been closed for it, as well) in VS Code - tab width is not respected.

AFAIK the space is hard-coded into the node TS module:

https://github.com/Microsoft/TypeScript/issues/4042
https://stackoverflow.com/questions/27994120/is-there-a-way-to-make-typescript-honor-tabs

The result is that the generated JS files do not respect the tab width until re-saved. The tab width is correct inside TS files.

**Comment by jessetrinity** [comment]
I have confirmed that this works in [Visual Studio 16.4 Preview 4](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview#16.4.0-pre.4.0) (it worked in VS 2019 previous o this but there was a break in 16.3).

See [this developer community post](https://developercommunity.visualstudio.com/content/problem/760838/visual-studio-formatting-no-longer-honors-indent-s.html) for more details.

Thanks!
