### ISSUE TITLE
Hard coded identifier for react in TSX

### ISSUE THREAD

**Issue by pjako** [Microsoft/TypeScript#14018]
```
Note: The identifier React is hard-coded, so you must make React available with an uppercase React.
See: https://www.typescriptlang.org/docs/handbook/jsx.html
```
I'm currently developing a library that uses tsx but not react.
So for me its is currently a bit inconvinien that I have to import my Library as "React" to make it work with tsx.
There are also other libraries that use jsx, for example deku.

In Babel you can customize the identifier per file or per project via the .babelrc.
See: https://babeljs.io/docs/plugins/transform-react-jsx/

Can you make this possible with TypeScript too?  Adding an option to the tsconfig.json would be enough imho.
```json
{
    "compilerOptions": {
        "jsx": "react",
        "jsxIdentifier": "Deku",
    }
}
```

**Comment by jwbay** [comment]
Have you tried reactNamespace and/or jsxFactory? https://www.typescriptlang.org/docs/handbook/compiler-options.html

**Comment by pjako** [comment]
"reactNamespace" worked for me, thanks!
