### ISSUE TITLE
Circular references in type declarations can be made using objects but not arrays

### ISSUE THREAD

**Issue by jameswilddev** [Microsoft/TypeScript#14016]
**TypeScript Version:**  2.1.4-insiders.20161201

https://www.typescriptlang.org/play/index.html#src=type%20SelfRefObj%20%3D%20%22A%22%20%7C%20%7B%20%5Bkey%3A%20string%5D%3A%20SelfRefObj%20%7D%0D%0Atype%20SelfRefArr%20%3D%20%22A%22%20%7C%20%5BSelfRefArr%5D

**Expected behavior:**

Either both objects and arrays in type declarations can reference the type being declared, or neither.

**Actual behavior:**

Objects may reference the type being declared, but arrays throw an error 

**Use case:**

Defining valid JSON as a type:
type Json = boolean | number | string | null | { [key: string]: Json } | [Json]

**Comment by ahejlsberg** [comment]
This is a known design limitation. However, you can use an intermediate interface type as described [here](https://github.com/Microsoft/TypeScript/issues/3496#issuecomment-128553540).
