### ISSUE TITLE
No literal type for Number constants (and missing parenthesis in doc)

### ISSUE THREAD

**Issue by kpreisser** [Microsoft/TypeScript#14029]
**TypeScript Version:**  master

Hi,
I found that in the current [es5.d.ts](https://github.com/Microsoft/TypeScript/blob/master/src/lib/es5.d.ts) and [es2015.core.d.ts](https://github.com/Microsoft/TypeScript/blob/master/src/lib/es2015.core.d.ts), some constants of the `NumberConstructor` return type `number` whereas they could return a literal type. This includes `MAX_SAFE_INTEGER`, `MIN_SAFE_INTEGER`, `MAX_VALUE`, `MIN_VALUE`, `EPSILON`.
I also noticed that in `MAX_SAFE_INTEGER` there seems to be a parenthesis missing:

**Actual behavior:**
```ts
interface NumberConstructor {
    // ...
    /**
      * The value of the largest integer n such that n and n + 1 are both exactly representable as
      * a Number value.
      * The value of Number.MAX_SAFE_INTEGER is 9007199254740991 2^53 − 1.
      */
    readonly MAX_SAFE_INTEGER: number;
}
```
**Expected behavior:**
```ts
interface NumberConstructor {
    // ...
    /**
      * The value of the largest integer n such that n and n + 1 are both exactly representable as
      * a Number value.
      * The value of Number.MAX_SAFE_INTEGER is 9007199254740991 (2^53 − 1).
      */
    readonly MAX_SAFE_INTEGER: 9007199254740991;
}
```

Do you think it makes sense to change the delcarations to return literal types?

On a related note, I found that the JSDocs sometimes contain line breaks for word wrapping, e.g. as seen in the above example there is a line break after ` representable as`. However, at least the Monaco Editor seem to actually insert a line break in that position when displaying the documentation:
![ts-monaco-linebreak](https://cloud.githubusercontent.com/assets/13289184/22875522/7eea55cc-f1cc-11e6-9020-2b9398b8a3db.png)

Does this mean such line breaks should be removed in the `.d.ts` files?

Thanks!

**Comment by kpreisser** [comment]
Hi @mhegazy,
should I submit a PR to use literal types for these properties (and add the missing parentheses)?

Thanks!

**Comment by mhegazy** [comment]
> Does this mean such line breaks should be removed in the .d.ts files?

Do not think so. the breaks are added to keep the length of the lines constant. @mjbvz thoughts?

**Comment by mhegazy** [comment]
I suppose adding the literal types would be better than having them in the documentation.

**Comment by kpreisser** [comment]
I realized that specifying a literal type for these properties might actually be a breaking change because they are non-widening literal types. So e.g. if someone writes
```ts
let n = Number.MAX_SAFE_INTEGER;
n = 123;
```
this will fail after using a literal type for `MAX_SAFE_INTEGER` because `n` is not widened to `number`.

Is it possible somehow to specify a widening numeric literal type for properties (like `declare const abc = 123;` vs. `declare const abc: 123;`)?

**Comment by mhegazy** [comment]
This is the best i can think of. 

```ts
declare const _MAX_SAFE_INTEGE =  9007199254740991;
...
    readonly MAX_SAFE_INTEGE : typeof _MAX_SAFE_INTEGE ;
```

Not sure it is worth it though..

**Comment by mjbvz** [comment]
For the jsdoc suggestion, we currently treat the documentation as plain test. https://github.com/Microsoft/vscode/issues/11877 tracks rendering suggestion item documentation as markdown content

**Comment by kpreisser** [comment]
Hi @mhegazy,
thanks, that was also what came to my mind. But I agree that this (declaring non-existing const variables) probably shouldn't be done in lib files. So I think unless there will be a way to explicitely specify widening literal types as property types in the future, we probably shouldn't use literal types for those properties.

Hi @mjbvz,
thanks, good to know!

**Comment by RyanCavanaugh** [comment]
Not clear how/why this would help anything
