### ISSUE TITLE
How to import modules from root path?

### ISSUE THREAD

**Issue by hydroper** [Microsoft/TypeScript#14023]
**TypeScript Version:**  2.12 / nightly (2.2.0-dev.201xxxxx)

**Code**

```ts
//////////////////////// entry.ts ////////////////////////
import { Main } from './src/Main';
new Main;

//////////////////////// adsad.ts ////////////////////////
export const A = 0;

//////////////////////// src/Main.ts ////////////////////////
import { A } from '/adsad';

export class Main {

    constructor() {
        console.log(A);
    }
}
```

**Expected behavior:** Compile without errors.

**Actual behavior:** Resulting `Cannot find module '/adsad'`.

**Comment by jwbay** [comment]
Sounds like you want https://www.typescriptlang.org/docs/handbook/module-resolution.html#base-url

**Comment by hydroper** [comment]
@jwbay That's what I was looking for, but unfortunately it doesn't work yet.

`tsconfig.json` file

```
{
    "compilerOptions": {
        "baseUrl": ".",
        "module": "commonjs",
        "noImplicitReturns": true,
        "noImplicitThis": true,
        "noUnusedLocals": true,
        "paths": {
            "*": [
                "*", "src/*"
            ]
        },
        "preserveConstEnums": true,
        "removeComments": true,
        "sourceMap": true,
        "strictNullChecks": true,
        "target": "ES6"
    },

    "include": [
        "./src/**/*.ts",
        "./src/**/*.d.ts"
    ]
}
```

It's still saying the module doesn't exist. :(

**Comment by hydroper** [comment]
@jwbay  THANK YOU!

**Comment by hydroper** [comment]
@jwbay Thanks! But when I import the module, the compiler says the module is not found, but my editor doesn't warn me.

![image](https://cloud.githubusercontent.com/assets/15965072/22867167/ae844d28-f169-11e6-9b23-679f487f2a72.png)

**Comment by jwbay** [comment]
That's an error from webpack, not typescript. It doesn't know or care about your tsconfig. You need to tell webpack to resolve modules against your root directory.

**Comment by hydroper** [comment]
@jwbay Do you know how can I tell it? I've tried with `{ ... context: __dirname ... }` and `{ ... context: path.join(__dirname, './src') ... }`, but nothing changed.

**Comment by hydroper** [comment]
@jwbay Thank you! I've checked the webpack documentation and got it working. THANK YOU!!!
