### ISSUE TITLE
`false` in type signature prevents autocomplete for objects

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#14024]
**TypeScript Version:** nightly today

**Code**

```ts
declare function style(val: false | { color: string }): string;
declare const someCondition: boolean;

style(someCondition && {/*cursor*/});
```

**Expected behavior:**
Should autocomplete. 
**Actual behavior:**
Doesn't autocomplete 
![image](https://cloud.githubusercontent.com/assets/874898/22867245/9b45bf5c-f1d8-11e6-8871-7e34388ba3ff.png)

We use this pattern heavily in [TypeStyle](http://typestyle.io/#/).

In React / JSX where you do `{someCondition && <SomeComponent/>}`. You can do the same with styles in TypeStyle `style(someCondition && {someStyle:'someValue'})`

As always, Thanks in advance :rose: :heart:

# Footnotes 
Please note that `null` and `undefined` work fine: 

![image](https://cloud.githubusercontent.com/assets/874898/22867260/0242be58-f1d9-11e6-900e-88d7ba9d8e49.png)

**Comment by mhegazy** [comment]
should be fixed in latest.
