### ISSUE TITLE
Implement prototype attribute in body of classes

### ISSUE THREAD

**Issue by ghost** [microsoft/TypeScript#14025]
What I'd like to see implemented is a shortcut for declaring/defining something for a class prototype through its body. This existed on ECMAScript 4, with a prototype attribute before a declaration:

```es4
class URLRequest {

    prototype var contentType: string =
        'application/x-www-form-urlencoded';
}
```

It's not standard in today ECMAScript, but helpful, it helps code readability. I don't see troubles on repeating the existence of the `prototype` attribute.

**Comment by RyanCavanaugh** [comment]
Available today under alternate syntax
```ts
class URLRequest {
    contentType: string;
}
URLRequest.prototype.contentType = 'application/x-www-form-urlencoded';
```

**Comment by hydroper** [comment]
@RyanCavanaugh When I set more prototype properties in this way I optionally shorthand the prototype getter (store `URLRequest.prototype` elsewhere), that's what made me think it'd be a little helpful feature.
