### ISSUE TITLE
tsconfig is not excluding node_modules  

### ISSUE THREAD

**Issue by xtianus79** [Microsoft/TypeScript#14028]
no matter what i do it won't ignore node_modules... form the documentation this is supposed to even be by default. 

**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)
2.1.6

**Code**
         {
            "compilerOptions": {
            "module": "commonjs",
            "target": "es5",
            "emitDecoratorMetadata": true,
            "experimentalDecorators": true,
           "moduleResolution": "node",
            "sourceMap": true,
           "removeComments": false,
           "noImplicitAny": false,
           "declaration": true,
          "outDir": "../dist"

        },
        "files": [
          "../src/multiple-date-picker.module.ts"
         ]
       }
```ts
// A *self-contained* demonstration of the problem follows...

```

**Expected behavior:**
it should work
**Actual behavior:**
it is not working

**Comment by mhegazy** [comment]
Please see https://github.com/Microsoft/TypeScript/wiki/FAQ#why-is-a-file-in-the-exclude-list-still-picked-up-by-the-compiler for more information.

**Comment by diegodesouza** [comment]
@xtianus79 Did you figure this out? 
The article isn't much of a help quite frankly. Says what I tried already which is add the `node_modules` to the `exclude` also tried the `files` portion. Nothing.

**Comment by rolesvillesoftware** [comment]
I do not know if you are still having this issue - I got around it by the following:

  "exclude": [
    "./node_modules/*"
  ]

**Comment by trsh** [comment]
Same issue here

**Comment by valeriob** [comment]
I found out the problem thanks to --traceResolution : 
i had installed @types/moment, then i read the readme (it says you do not need this package, types are already included in moment) so i removed that package from packages.json.
Well typescript has many heuristics taking place to look for type informations so, i had to manually delete tye @types/moment folder to avoid them to kick in.

This is very anoying, the amount of automation behind typescript configuration makes everything simple very hard ! and it's the manifestation of how messy the ui dev is 😄, with layers of  things on top of each other.

**Comment by NelsonRothermel** [comment]
@valeriob : What package had you installed that was not necessary and which readme did it mention that in?

**Comment by valeriob** [comment]
types/moment in  my case, because types are already bundled in moment package.
