### ISSUE TITLE
Add dynamic and static classes

### ISSUE THREAD

**Issue by klaiderklai** [Microsoft/TypeScript#14033]
## Static class

A static class couldn't be constructed, and couldn't declare instance-base/prototype members.

There are workarounds, but anyways I suggest adding a standard way to declare static classes:

```typescript
export static class URLRequestMethod {
    static staticMember: boolean;
    instanceMember: boolean; // WARN!

    constructor() { ... } // WARN!
}

new URLRequestMethod; // WARN!
```

## Dynamic class

A dynamic class could set any undeclared property in its static-base and in its instance-base/prototype. I.e.:

```typescript
export dynamic class Dictionary { }

let d = new Dictionary;

// prop is not declared in Dictionary, but the class itself is dynamic.
// So this would be deeply valid:
d.prop = true;
```

**Comment by gcnew** [comment]
What's the difference between a static class and a const object with the desired fields? Every class should be "dynamic", otherwise it's simply a constant.

**Comment by hydroper** [comment]
@gcnew 
> What's the difference between a static class and a const object with the desired fields?
A const object isn't a class, very simple. I need it to be considered a "class", as in the AS3's net reference (it references that URLRequestMethod is a class).

> Every class should be "dynamic", otherwise it's simply a constant.
No, not actually.

![image](https://cloud.githubusercontent.com/assets/15965072/22890966/f91cff5c-f1f4-11e6-8767-eacacde129e6.png)

**Comment by mhegazy** [comment]
I am not sure i understand the request here. can you elaborate.

**Comment by hydroper** [comment]
@mhegazy I improved the issue. Is it better now?

**Comment by mhegazy** [comment]
For a "static" class, that looks like a `namespace` to me.

```ts
export namespace URLRequestMethod {
    export const staticMember: boolean;
}
```

For a "dynamic" class, you get this in TS 2.2 with an index signature:

```ts
class D { 
    [x: string]: any;
}
(new D).blah = 0; 
```

**Comment by hydroper** [comment]
@mhegazy Yes, but in AS3 URLRequestMethod is a static class, really, a class, as at flash.net reference, for example. I need real static classes, 'til because `typeof URLRequestMethod` will result in function.

I didn't understand very well this index signature, I'll give it a check.

**Comment by mhegazy** [comment]
> @mhegazy Yes, but in AS3 URLRequestMethod is a static class, really, a class, as at flash.net reference, for example. I need real static classes, 'til because typeof URLRequestMethod will result in function, and this is anyways a workaround.

Why? how would it be used? If i understand correctly, you will never call `new` on it, you will never use it as a target of `instanceof`, so not sue why the runtime value of `typeof` matters here.

**Comment by isiahmeadows** [comment]
What's the difference between this proposal and just using the `any` type, as in `const dict: any = Object.create(null)`?

**Comment by isiahmeadows** [comment]
Alternatively, you could define such a "dynamic" type like this:

```ts
interface Dynamic {
    [key: string]: Dynamic;
    [key: number]: Dynamic;
    [key: symbol]: Dynamic;
}
```
