### ISSUE TITLE
Deletion of readonly property is allowed

### ISSUE THREAD

**Issue by hamishdh** [Microsoft/TypeScript#14034]
**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)

**Code**

```ts
interface Foo {
    readonly Property: string;
}

let bar: Foo = {
    Property: "Baz!"
};

bar.Property = undefined; // Disallowed - Cannot Assign to 'Property' because it is a constant or a read-only property
delete bar.Property; // Allowed
```

**Expected behavior:**

The TS compiler should disallow deletion of a read-only property.

**Actual behavior:**

The TS compiler allows deletion of a read-only property.

**Comment by RyanCavanaugh** [comment]
See #11480. Please search before logging new issues and please fill in a correct version number in the template. This is now an error.

>  error TS2704: The operand of a delete operator cannot be a read-only property

![image](https://cloud.githubusercontent.com/assets/6685088/22895947/22043a60-f1d3-11e6-895e-3c1fe7dcedfa.png)
