### ISSUE TITLE
TSC returns an error for TSX code where the plain TS equivalent compiles fine

### ISSUE THREAD

**Issue by avonwyss** [Microsoft/TypeScript#14036]
**TypeScript Version:**  2.1.5

**Code**
```ts
type SelectProps<T> = { items: T[] }
class Select<T> extends React.Component<SelectProps<T>, any> { }

const someItems: [1, 2, 3, 4];

function renderJsx() {
return <Select items={someItems} />; // Error: Generic type 'Select<T>' requires 1 type argument(s).
}

function renderJs() {
return React.createElement(Select, { items: someItems }); // No error
}
```

**Expected behavior:**
TS should infer the generic type in the `renderJsx` function just as it does in the `renderJs` function.

**Actual behavior:**
TS requires a generic type argument which unfortunately cannot be specified because this is not supported by the parser.

See also #3960 for some related discussions.

**Comment by basarat** [comment]
Probably worth raising here : https://github.com/facebook/jsx/issues/new for some explicit syntax in JSX :rose:

**Comment by avonwyss** [comment]
@basarat I'm not sure what you are suggesting; it has nothing to do with the original JSX syntax IMHO.
The type inference is related to TypeScript only, and I do think that it would solve most (if not all) JSX generic component use cases *without* requiring any syntax enhancement (or kludges as discussed in #3960).

**Comment by basarat** [comment]
I understand 🌹

**Comment by MastroLindus** [comment]
+1 for this or at least #6395

**Comment by ksmutny** [comment]
+1 Yes please, type inference would be IMHO the correct (and welcomed) solution.

**Comment by Pajn** [comment]
It would be great if TypeScript at least could infer generics even though you can't write them explicitly.
See this:
```
export function AsyncList<D extends {loading: boolean}>(props: {data: D, getItems: (data: D) => Array<any>}) {
  return (
    <div>
    </div>
  )
}

const data = {loading: false, items: [1, 2, 3]}

function a() {
  return <AsyncList
    data={data}
    getItems={data => data.items}
  />
}
function b() {
  return AsyncList({
    data,
    getItems: data => data.items
  })
}
```
a fails with
```
Type '{ loading: boolean; items: number[]; }' is not assignable to type 'D'.
Property 'items' does not exist on type 'D'.
```
but b have no issues.
I think TS should be able to infer D as `typeof data` in the JSX case just as it does int the call/object literal case.

**Comment by mhegazy** [comment]
There is not really a place for inference to happen here. there is no reason to assume that the `T` in `Select<T>` is the propTypes, unless we hard-code the `React` component handling, which is something we would not want to do.

The best option here is https://github.com/Microsoft/TypeScript/issues/6395, where you can explicitly specify your type arguments.

**Comment by avonwyss** [comment]
@mhegazy Maybe "type inference" is the wrong terminology. Nevertheless, since the `renderJs` is the code equivalt to what should be generated by the compiler in the `renderJsx` case, I don't get why the first is acceptable *without type argument* while the JSX case is not. Basically, since they are equivalent AFAIK they should also both be accepted the same by the compiler.

**Comment by mhegazy** [comment]
> @mhegazy Maybe "type inference" is the wrong terminology. Nevertheless, since the renderJs is the code equivalent to what should be generated by the compiler for the renderJsx case, I don't get why the first is acceptable without type argument while the JSX case is not. Basically, since they are equivalent AFAIK they should also both be accepted the same by the compiler.

There is no inference happening in the second one either (`renderJsx`), the type parameters both go to `any`. you just not getting an error. you can get the same behavior by not having the component be generic, and setting `T` to `any`.

**Comment by avonwyss** [comment]
@mhegazy OK, even if `any` is used for `T`, it still does check that the properties of the props are as required by the component. See [Playground](https://www.typescriptlang.org/play/#src=type%20SelectProps%3CT%3E%20%3D%20%7B%20items%3A%20T%5B%5D%20%7D%0D%0Aclass%20Select%3CT%3E%20extends%20React.Component%3CSelectProps%3CT%3E%2C%20any%3E%20%7B%20%7D%0D%0A%0D%0Aconst%20someItems%20%3D%20%5B1%2C%202%2C%203%2C%204%5D%3B%0D%0A%0D%0Afunction%20renderJsOk()%20%7B%0D%0A%20%20%20%20return%20React.createElement(Select%2C%20%7B%20items%3A%20someItems%20%7D)%3B%20%2F%2F%20No%20error%0D%0A%7D%0D%0A%0D%0Afunction%20renderJsFail()%20%7B%0D%0A%20%20%20%20return%20React.createElement(Select%2C%20%7B%20itemz%3A%20someItems%20%7D)%3B%20%2F%2F%20Error%0D%0A%7D%0D%0A%0D%0A%2F%2F%20Type%20definitions%20taken%20from%20DT%20react%20typings%0D%0Adeclare%20namespace%20React%20%7B%0D%0A%09type%20ReactInstance%20%3D%20Component%3Cany%2C%20any%3E%20%7C%20Element%3B%0D%0A%0D%0A%20%20%20%20type%20ReactType%20%3D%20string%20%7C%20ComponentClass%3Cany%3E%3B%0D%0A%0D%0A%20%20%20%20type%20Key%20%3D%20string%20%7C%20number%3B%0D%0A%20%20%20%20type%20Ref%3CT%3E%20%3D%20string%20%7C%20((instance%3A%20T)%20%3D%3E%20any)%3B%0D%0A%20%20%20%20type%20ComponentState%20%3D%20%7B%7D%20%7C%20void%3B%0D%0A%0D%0A%20%20%20%20interface%20Attributes%20%7B%0D%0A%20%20%20%20%20%20%20%20key%3F%3A%20Key%3B%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20interface%20ClassAttributes%3CT%3E%20extends%20Attributes%20%7B%0D%0A%20%20%20%20%20%20%20%20ref%3F%3A%20Ref%3CT%3E%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20interface%20ReactElement%3CP%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20type%3A%20string%20%7C%20ComponentClass%3CP%3E%3B%0D%0A%20%20%20%20%20%20%20%20props%3A%20P%3B%0D%0A%20%20%20%20%20%20%20%20key%3A%20Key%20%7C%20null%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20type%20CElement%3CP%2C%20T%20extends%20Component%3CP%2C%20ComponentState%3E%3E%20%3D%20ComponentElement%3CP%2C%20T%3E%3B%0D%0A%20%20%20%20interface%20ComponentElement%3CP%2C%20T%20extends%20Component%3CP%2C%20ComponentState%3E%3E%20extends%20ReactElement%3CP%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20type%3A%20ComponentClass%3CP%3E%3B%0D%0A%20%20%20%20%20%20%20%20ref%3F%3A%20Ref%3CT%3E%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20interface%20DOMElement%3CP%2C%20T%20extends%20Element%3E%20extends%20ReactElement%3CP%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20type%3A%20string%3B%0D%0A%20%20%20%20%20%20%20%20ref%3A%20Ref%3CT%3E%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20%2F%2F%0D%0A%20%20%20%20%2F%2F%20Factories%0D%0A%20%20%20%20%2F%2F%20----------------------------------------------------------------------%0D%0A%0D%0A%20%20%20%20interface%20Factory%3CP%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20(props%3F%3A%20Attributes%20%26%20P%2C%20...children%3A%20ReactNode%5B%5D)%3A%20ReactElement%3CP%3E%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20interface%20ComponentFactory%3CP%2C%20T%20extends%20Component%3CP%2C%20ComponentState%3E%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20(props%3F%3A%20ClassAttributes%3CT%3E%20%26%20P%2C%20...children%3A%20ReactNode%5B%5D)%3A%20CElement%3CP%2C%20T%3E%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20type%20CFactory%3CP%2C%20T%20extends%20Component%3CP%2C%20ComponentState%3E%3E%20%3D%20ComponentFactory%3CP%2C%20T%3E%3B%0D%0A%0D%0A%09interface%20ComponentLifecycle%3CP%2C%20S%3E%20%7B%0D%0A%09%09componentWillMount%3F()%3A%20void%3B%0D%0A%09%09componentDidMount%3F()%3A%20void%3B%0D%0A%09%09componentWillReceiveProps%3F(nextProps%3A%20P%2C%20nextContext%3A%20any)%3A%20void%3B%0D%0A%09%09shouldComponentUpdate%3F(nextProps%3A%20P%2C%20nextState%3A%20S%2C%20nextContext%3A%20any)%3A%20boolean%3B%0D%0A%09%09componentWillUpdate%3F(nextProps%3A%20P%2C%20nextState%3A%20S%2C%20nextContext%3A%20any)%3A%20void%3B%0D%0A%09%09componentDidUpdate%3F(prevProps%3A%20P%2C%20prevState%3A%20S%2C%20prevContext%3A%20any)%3A%20void%3B%0D%0A%09%09componentWillUnmount%3F()%3A%20void%3B%0D%0A%09%7D%0D%0A%0D%0A%20%20%20%20class%20Component%3CP%2C%20S%3E%20implements%20ComponentLifecycle%3CP%2C%20S%3E%20%7B%0D%0A%09%09constructor(props%3F%3A%20P%2C%20context%3F%3A%20any)%3B%0D%0A%09%09setState%3CK%20extends%20keyof%20S%3E(f%3A%20(prevState%3A%20S%2C%20props%3A%20P)%20%3D%3E%20Pick%3CS%2C%20K%3E%2C%20callback%3F%3A%20()%20%3D%3E%20any)%3A%20void%3B%0D%0A%09%09setState%3CK%20extends%20keyof%20S%3E(state%3A%20Pick%3CS%2C%20K%3E%2C%20callback%3F%3A%20()%20%3D%3E%20any)%3A%20void%3B%0D%0A%09%09forceUpdate(callBack%3F%3A%20()%20%3D%3E%20any)%3A%20void%3B%0D%0A%09%09render()%3A%20JSX.Element%20%7C%20null%3B%0D%0A%0D%0A%09%09%2F%2F%20React.Props%3CT%3E%20is%20now%20deprecated%2C%20which%20means%20that%20the%20%60children%60%0D%0A%09%09%2F%2F%20property%20is%20not%20available%20on%20%60P%60%20by%20default%2C%20even%20though%20you%20can%0D%0A%09%09%2F%2F%20always%20pass%20children%20as%20variadic%20arguments%20to%20%60createElement%60.%0D%0A%09%09%2F%2F%20In%20the%20future%2C%20if%20we%20can%20define%20its%20call%20signature%20conditionally%0D%0A%09%09%2F%2F%20on%20the%20existence%20of%20%60children%60%20in%20%60P%60%2C%20then%20we%20should%20remove%20this.%0D%0A%09%09props%3A%20Readonly%3C%7B%20children%3F%3A%20ReactNode%20%7D%3E%20%26%20Readonly%3CP%3E%3B%0D%0A%09%09state%3A%20Readonly%3CS%3E%3B%0D%0A%09%09context%3A%20any%3B%0D%0A%09%09refs%3A%20%7B%0D%0A%09%09%09%09%5Bkey%3A%20string%5D%3A%20ReactInstance%0D%0A%09%09%09%7D%3B%0D%0A%09%7D%0D%0A%0D%0A%09interface%20ComponentClass%3CP%3E%20%7B%0D%0A%09%09new%20(props%3F%3A%20P%2C%20context%3F%3A%20any)%3A%20Component%3CP%2C%20ComponentState%3E%3B%0D%0A%09%09propTypes%3F%3A%20ValidationMap%3CP%3E%3B%0D%0A%09%09contextTypes%3F%3A%20ValidationMap%3Cany%3E%3B%0D%0A%09%09childContextTypes%3F%3A%20ValidationMap%3Cany%3E%3B%0D%0A%09%09defaultProps%3F%3A%20Partial%3CP%3E%3B%0D%0A%09%09displayName%3F%3A%20string%3B%0D%0A%09%7D%0D%0A%0D%0A%09interface%20Validator%3CT%3E%20%7B%0D%0A%09%09(object%3A%20T%2C%20key%3A%20string%2C%20componentName%3A%20string%2C%20...rest%3A%20any%5B%5D)%3A%20Error%20%7C%20null%3B%0D%0A%09%7D%0D%0A%0D%0A%09interface%20ValidationMap%3CT%3E%20%7B%0D%0A%09%09%5Bkey%3A%20string%5D%3A%20Validator%3CT%3E%3B%0D%0A%09%7D%0D%0A%0D%0A%20%20%20%20type%20ReactText%20%3D%20string%20%7C%20number%3B%0D%0A%20%20%20%20type%20ReactChild%20%3D%20ReactElement%3Cany%3E%20%7C%20ReactText%3B%0D%0A%0D%0A%20%20%20%20%2F%2F%20Should%20be%20Array%3CReactNode%3E%20but%20type%20aliases%20cannot%20be%20recursive%0D%0A%20%20%20%20type%20ReactFragment%20%3D%20%7B%7D%20%7C%20Array%3CReactChild%20%7C%20any%5B%5D%20%7C%20boolean%3E%3B%0D%0A%20%20%20%20type%20ReactNode%20%3D%20ReactChild%20%7C%20ReactFragment%20%7C%20boolean%20%7C%20null%20%7C%20undefined%3B%0D%0A%0D%0A%20%20%20%20function%20createElement%3CP%3E(%0D%0A%20%20%20%20%20%20%20%20type%3A%20ComponentClass%3CP%3E%2C%0D%0A%20%20%20%20%20%20%20%20props%3F%3A%20Attributes%20%26%20P%2C%0D%0A%20%20%20%20%20%20%20%20...children%3A%20ReactNode%5B%5D)%3A%20ReactElement%3CP%3E%3B%0D%0A%7D%0D%0A%0D%0Adeclare%20namespace%20JSX%20%7B%0D%0A%20%20%20%20interface%20Element%20extends%20React.ReactElement%3Cany%3E%20%7B%20%7D%0D%0A%7D%0D%0A).

```ts
type SelectProps<T> = { items: T[] }
class Select<T> extends React.Component<SelectProps<T>, any> { }

const someItems = [1, 2, 3, 4];

function renderJsOk() {
    return React.createElement(Select, { items: someItems }); // No error
}

function renderJsFail() {
    return React.createElement(Select, { itemz: someItems }); // Error
}
```

**The question I'm asking really is this:** why does the plain and the JSX version not behave the same, e.g. why is there a compile error in the JSX case? If the JSX case was acting the same as the plain version I'd be pretty happy already, as it would allow people to use JSX syntax throughout and achieve the same level of type safety as with the plain version, e.g. checking that the passed in properties are valid (even if it is using `any` for `T`).

**Comment by mhegazy** [comment]
with https://github.com/Microsoft/TypeScript/issues/15455, you can get the same bahvuour with default paramters:

```ts
import * as React from "react";

type SelectProps<T > = { items: T[] }
class Select<T = any> extends React.Component<SelectProps<T>, any> { }

const someItems = [1, 2, 3, 4];
const someItems2 = ["ss"];

function renderJsx() {
    return <Select items={someItems} />; // OK
}
```

**Comment by avonwyss** [comment]
@mhegazy Thank you for the hint, I'll use that when it becomes available in the stable version.

Nevertheless it remains unclear to me why the plain and the JSX-style code do not behave the same, could you maybe shed some light on that?

**Comment by yuit** [comment]
@avonwyss  The reason is on how we resolve JSX.Expression.  The way we resolve React.Component in JSX-style syntax is different than how we do for normal function in particular it doesn't go through overload resolution logic (like how  new call expression does).

In 2.3, however, stateless-function component does go through overload resolution and so if you declare `Select` as SFC and using 2.3 we will be able to infer type parameter
```ts
function Select<T>(attr: SelectProps<T>) {...}
```
We are considering using overload resolution when we are trying to resolve JSX expression that is declared as React Component class.

**Comment by avonwyss** [comment]
Thank you @yuit for explaining the difference. Indeed, I think that using the same overload resolution would be the correct way to do things, so that behavior remains consistent (even more so in the light of using other JSX factories).

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
