### ISSUE TITLE
Generic Type Inference Bug?

### ISSUE THREAD

**Issue by evanbb** [Microsoft/TypeScript#14037]
**TypeScript Version:**  2.1.6

**Code**

```ts
declare module 'module' {
  interface result<T> {
    item: T
  }

  export interface resulter {
    <T extends keyof validKeys>(): result<T>
  }

  export interface validKeys {
    validKey: string
  }

  export interface results {
    [key: string]: resulter
  }
}
```

```ts
import { results } from 'module';

const d: results = {
  something: () => ({
    item: 'invalidKey'
  })
};
```

**Expected behavior:**
Valid values for 'item' property on result would be restricted to keys of validKeys.

**Actual behavior:**
Inspecting the error if the 'item' property is removed from the result confirms that the result object is typed as result<any>.

**Comment by krryan** [comment]
Related to https://github.com/Microsoft/TypeScript/issues/13995

**Comment by mhegazy** [comment]
Not sure i understand what the use of a generic signature here is meant to enforce. but either ways, the function API says it can be called with any `T`, and it will somehow return you a result of the same `T` passed..  
```ts
d.something<"validKey">();  // result<"validKey">
d.something<"anotherValidKey">();  // result<"anotherValidKey">
```
