### ISSUE TITLE
tsserver does not know about projects that have no file open

### ISSUE THREAD

**Issue by lorenzodallavecchia** [Microsoft/TypeScript#14030]
**TypeScript Version:**  2.1.6

**Expected behavior:**
For an IDE to even know that a file is in the scope of a _tsconfig.json_, at least one tsserver command (`projectInfo` maybe?) should work even if no file from that project is open.

**Actual behavior:**
If a project has no files open, no command ever considers that project, directly or indirectly. In the case of `projectInfo` it fails with _No project_ exception. Other commands (e.g. `references`) just ignore the project.

## Background Information

While integrating tsserver with the Eclipse IDE, I realized that it is not possible to have it process multiple TS projects reliably. I think this is a failrly common situation in large codebasese: having shared "library" projects and larger projects using them as dependencies.

The main issue here is the fact that tsserver is considering a project as "existing" only if at least one of its files is open. Currently, I am opening files on tsserver only when the user has a visible editor for them. Consequently, if the user is not editing any file of a project, it is like that tsconfig.json did not exist!

### Example Scenarios

Suppose to have the following project structure.

```
A
+- src
|  +- main_a.ts         import { foo } from "./utils"
|  +- other_a.ts
|  +- utils.ts          export function foo() {}
+- tsconfig.json        { include: [ "src" ] }
  
B
+- src
|  +- main_b.ts         import { foo } from "../../project_A/src/utils"
|  +- other_b.ts
+- tsconfig.json        { include: [ "src" ] }
```

Now, for incremental compilation.

Step | User Action  | IDE tsserver Interaction
---- | ------------ | ------------------------
1 | Open an editor for `A/src/utils.ts`. | Send `open` to tsserver.
2 | Edit `A/src/utils.ts` by changing the name of `foo`. | Send `change` to tsserver.
3 | Save `A/src/utils.ts`. | Send `compileOnSaveAffectedFileList` to tsserver.<br>It returns `A/src/utils.ts` and `A/src/main_a.ts`.<br>For each of those affected files, send `compileOnSaveEmitFile`, `semanticDiagnosticsSync` and `syntacticDiagnosticsSync`.<br>Display returned diagnostics to the user.

The intent of the IDE was to immediately recompile and report any errors caused by saving that file. However, the resulting errors are visible on `A/src/main_a.ts` but not on `B/src/main_b.ts`, because `compileOnSaveAffectedFileList` did not return it.

Something similar happens for references.

Step | User Action  | IDE tsserver Interaction
---- | ------------ | ------------------------
1 | Open an editor for `A/src/utils.ts`. | Send `open` to tsserver.
2 | Ask for references to the `foo` function. | Send `references` to tsserver.<br>It returns references from `A/src/utils.ts` itself and from `A/src/main_a.ts`.<br>Display references to the user.

While the IDE was expected to find all references, only those inside project `A` are found.

### Possible Workarounds

As a workaround I was thinking about keeping all existing files open on the server even if the user is not editing them, but I'm afraid this could hurt performance.

If at least `projectInfo` worked, the IDE could implement some smarter workarounds by opening files on the fly to ensure that all _tsconfig.json_ projects can be found.

**Comment by mhegazy** [comment]
is using [OpenExternalProject](https://github.com/Microsoft/TypeScript/blob/d24b6891d870dbaa6bbc358ab787da935f471186/lib/protocol.d.ts#L786-L789) an option?

**Comment by angelozerr** [comment]
> is using OpenExternalProject an option?

No @mhegazy, could you give more info how to consume this request please. Thanks!

**Comment by mhegazy** [comment]
You can call `OpenExternalProject` with list of files. 

It depends if you have a concept of "Project" that you can leverage in your plugin.  VS for instance has a concept of "project" that may or may not include a tsconfig.json file(s).

**Comment by angelozerr** [comment]
Thanks a lot @mhegazy for your explanation. 

> It depends if you have a concept of "Project" that you can leverage in your plugin

Yes Eclipse has concept of project (and referenced project). 

> You can call OpenExternalProject with list of files.

Can we set in this files list, tsconfig.json files (coming from referenced projects) instead of ts files?

**Comment by mhegazy** [comment]
> Can we set in this files list, tsconfig.json files (coming from referenced projects) instead of ts files?

no. these are ts files. the server will find the tsconfig.json itself. so the project can include 0-n tsconfig.json.

**Comment by lorenzodallavecchia** [comment]
Thanks for the suggestion @mhegazy.

I did experiment with `openExternalProject` a while back, but I gave up on that one as it looked to me like a way for defining "virtual" projects, precisely because of the need to specify a list of "root files".

In this case we have two equal projects that are both edited in the IDE. So, at times, each one of the two may be the "external" one because the user is editing files from the other one.
Normal "configured" projects would therefore overlap with "external" projects. Wouldn't they conflict?

**Comment by alpapad** [comment]
I think open external project  will open a project if the passed files contain a tsconfig.json file.

see:
`openExternalProject(proj: protocol.ExternalProject, suppressRefreshOfInferredProjects = false): void`

```
            for (const file of proj.rootFiles) {
                const normalized = toNormalizedPath(file.fileName);
                if (getBaseFileName(normalized) === "tsconfig.json") {
                    if (this.host.fileExists(normalized)) {
                        (tsConfigFiles || (tsConfigFiles = [])).push(normalized);
                    }
                }
                else {
                    rootFiles.push(file);
                }
            }
```
Will it stay open after a "gc", I don;t know.

In any case, if you are not planning to support 'virtual projects' how do you plan to handle the case of a project like typescript itself (where the same file is referenced from different tsconfig.json files)?

**Comment by lorenzodallavecchia** [comment]
Ok, I was assumning that `rootFiles` were supposed to be only TS files, especially since you also have to pass a `projectFileName` and also that "external project" meant "external **TS** project".
If that command is really used for defining a different concept of IDE project, it may just work. I'm definitely trying that again.

> In any case, if you are not planning to support 'virtual projects' how do you plan to handle the case of a project like typescript itself (where the same file is referenced from different tsconfig.json files)?

Well, as @angelozerr said, Eclipse does have its concept of "project" that is different from "TS project". We surely want to support them.
I was somehow deceived by the word "external" meaning something that is of secondary importance to the server and not editable like ordinary projects.

I have just re-read the documentato of `ExternalFile` with a new perspective, and I realize it may just be the solution to this problem.
