### ISSUE TITLE
Intellisense shows never members

### ISSUE THREAD

**Issue by markboyall** [Microsoft/TypeScript#14040]
**TypeScript Version:**  2.1.5

```
var x: { caption?: never; }
x = { caption: "" };
```

**Expected behavior:**
When filling out the object assigned to x, the caption field should not be presented to the user as an option, since it is of type `never`. 

**Actual behavior:**
The user is encouraged to pick the option, even though it can't ever compile.

**Comment by mhegazy** [comment]
actually it is type `undefined`, since `caption?` is `undefined | never`, and this `undefined`.

it seems like a corner case, not sure it is worth adding the specialized filtering code in completions.

**Comment by markboyall** [comment]
Our desired use case is to remove properties- e.g. `Partial<T> & { prop: never}`. We have a lot of cases where we pass in objects that are mostly another interface, but the caller provides one or two extra properties that the callee should not set.
