### ISSUE TITLE
Docs have error in type signature

### ISSUE THREAD

**Issue by anfedorov** [Microsoft/TypeScript#14047]
On https://www.typescriptlang.org/docs/handbook/modules.html

```export const isPrime(x: number): boolean;```

is invalid and should be

```export const isPrime: (x: number) => boolean;```

**Comment by mrdulin** [comment]
I found this too. 

`export const isPrime(x: number): boolean;`  is not correct.

`Error:(5, 17) TS1005:'=' expected.`
`Error:(5, 37) TS1005:'=>' expected.`
