### ISSUE TITLE
Spread operator should allow to remove readonly form properties.

### ISSUE THREAD

**Issue by scharf** [Microsoft/TypeScript#14058]
A typical reason to make a copy of data is to be able to modify it locally. However in typescript the spread operator does not remove the `readonly` properties form the copy:

```
interface ReadOnlyData {
   readonly value: string;
}

const data:ReadOnlyData = { value:'foo' }

// What is the reason to make the local copy of the data readonly?
const copyOfData = {...data};

copyOfData.value = 'bar'
```

I would expect that the `copyOfData` is writable! Or there should be a simple way to make all `readonly` properties in `copyOfData` writable.

**Comment by sandersn** [comment]
Fix is up at #15036
