### ISSUE TITLE
JSDoc Does not Pick up Type imported using Require

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#14056]
From https://github.com/Microsoft/vscode/issues/20238

**TypeScript Version:**  2.1.6

**Code**

foo.js:
```js
export class Foo {
    /**
     * @param {string} name
     * @param {number} id
     */
    constructor(name, id) {
        this.name = name;
        this.id = id
    }
}
```

index.js:
```js
const {Foo} = require('./foo');

/**
 * @param {Foo} param
 */
function func(param) {

}
```

**Expected behavior:**
The type of `param` is `Foo`

**Actual behavior:**
The type of `param` is `any`.

If I change the import to `import {Foo} from './foo'`, the type of `param` is correct

**Comment by mhegazy** [comment]
`Foo` is not a type. it is a constructor function. I suppose we can check if we could not look up a type, but the value points to a constructor function, use that instead.

**Comment by MicahZoltu** [comment]
@mhegazy see the repro case over in https://github.com/Microsoft/vscode/issues/21933 in particular, notice how to behavior is different for `var foo = new Foo()`.  This suggests to me that the engine understands that `Foo` is a type (with a constructor), not just a function, but it doesn't seem to follow the same rules when told via the annotation.  Perhaps I'm misunderstanding to difference between a type and a constructor function?

**Comment by MicahZoltu** [comment]
For record keeping and improving google search of this issue, the same problem occurs with local variables, it is not limited to function parameters:

```javascript
var Foo = require("./foo");

/** @type {Foo} */
var bar; // VSCode (via TypeScript engine) considers `bar` to be of type `any`
```

Also note that the recommended workaround of using the import syntax only applies if you are writing ES2015+, in which case you really should be using import syntax anyway.  For code written in ES5 I don't believe there is any workaround to this issue.

**Comment by Zarel** [comment]
@mhegazy

> `Foo` is not a type. it is a constructor function.

If I define `Foo` as a class within the file, it's a type. Why is it not a type if I import it from a different file? How do I make it a type?

I've googled this a lot and I can't find any documentation on how to make it a type. Now that TypeScript emits errors when I try to do this, I think that error is a good place to provide guidance on how to make it a type.

**Comment by mhegazy** [comment]
Based on the discussion in https://github.com/Microsoft/TypeScript/issues/15747, we want to look up the reference as a value of the look up as a type failed, and add special handling for classes.
