### ISSUE TITLE
Promise.all with array.map async callback broken, version 2.1.x

### ISSUE THREAD

**Issue by PyroGreg8** [Microsoft/TypeScript#14063]
**TypeScript Version:**  2.1.x

**Code**

For some class with these methods.

```ts
async getUserNamesFromIds(ids: number[]) {

    //userNames is expected to be type string[], but instead it is any[]
    var userNames = await Promise.all(ids.map(async (id) => {
        return await this.FetchName(id);
    }));

    return userNames;
}

FetchName(id: number): Promise<string> {
    //Simulate getting name from database
    return Promise.resolve("John Smith");
}
```

You would expect the `userNames` variable to resolve to type `string[]`, as it does in typescript version 2.0.x. But in 2.1.x it resolves to type `any[]`. This seems to be as Promise.all expects `PromiseLike[]` but the array map with the async callback produces `Promise[]` which is apparently not compatible with `PromiseLike[]` anymore.

This is just a simplified example. For a case where I am using type unions to nest interfaces and such, having to convert the Promise to PromiseLike is not feasible. Is there a reason this behaves like this in 2.1.x?

**Comment by IanYates** [comment]
Seems to work in playground for me.  I can inspect the type of `userNames` and see `string[]`.

What settings do you have in your `tsconfig.json`?  I wonder if you're pulling in different core libs.

Playground link:
http://www.typescriptlang.org/play/index.html#src=class%20X%20%7B%0D%0A%20%20%20%20async%20getUserNamesFromIds(ids%3A%20number%5B%5D)%20%7B%0D%0A%0D%0A%20%20%20%20%20%20%20%20%2F%2FuserNames%20is%20expected%20to%20be%20type%20string%5B%5D%2C%20but%20instead%20it%20is%20any%5B%5D%0D%0A%20%20%20%20%20%20%20%20var%20userNames%20%3D%20await%20Promise.all(ids.map(async%20(id)%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20await%20this.FetchName(id)%3B%0D%0A%20%20%20%20%20%20%20%20%7D))%3B%0D%0A%0D%0A%20%20%20%20%20%20%20%20return%20userNames%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20FetchName(id%3A%20number)%3A%20Promise%3Cstring%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20%2F%2FSimulate%20getting%20name%20from%20database%0D%0A%20%20%20%20%20%20%20%20return%20Promise.resolve(%22John%20Smith%22)%3B%0D%0A%20%20%20%20%7D%0D%0A%7D

**Comment by PyroGreg8** [comment]
My tsconfig looks like this

```
{
	"compilerOptions": {
		"target": "es6",
		"module": "commonjs",
		"noImplicitAny": true,
		"noImplicitReturns": true,
		"removeComments": true,
		"preserveConstEnums": true,
		"inlineSourceMap": true,
		"outDir": "build"
	},
	"exclude": [
		"typings/browser.d.ts",
		"typings/browser",
		"node_modules/**/*",
		".git",
		"build"
	]
}
```
