### ISSUE TITLE
The signature for document.implementation.hasFeature is incorrect

### ISSUE THREAD

**Issue by argelius** [Microsoft/TypeScript#14062]
**TypeScript Version:**  nightly (2.2.0-dev.20170213)

**Code**

```ts
document.implementation.hasFeature("http://www.w3.org/TR/SVG11/feature#BasicStructure", "1.1");
```

**Expected behavior:**

It should not emit an error.

**Actual behavior:**

The following error is emitted:

```
test.ts(1,1): error TS2346: Supplied parameters do not match any signature of call target.
```

The function is deprecated so this error actually helped me realize that the code was using a deprecated function but I guess it should work :)

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.
