### ISSUE TITLE
Incorrect emits from declaration files

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#14066]
**TypeScript Version:**  master

**Code**

```ts
// index.d.ts
export interface Parser<R, P extends Parser<any, any>[]> {
}

declare abstract class Markdown<T> {
  private MARKDOWN?: T;
}
export interface MarkdownParser extends
  Markdown<'markdown'>,
  Parser<HTMLElement, [
    MarkdownParser.BlockParser
  ]> {
}
export namespace MarkdownParser {
  export interface BlockParser extends
    Markdown<'block'>,
    Parser<HTMLElement, [
      never
    ]> {
  }
  export interface UListParser extends
    Markdown<'ulist'>,
    Parser<HTMLElement, [
      UListParser.ListParser
    ]> {
  }
  export namespace UListParser {
    export interface ListParser extends
      Markdown<'list'>,
      Parser<HTMLElement | Text, [
        UListParser,
        OListParser
      ]> {
    }
  }
  export interface OListParser extends
    Markdown<'olist'>,
    Parser<HTMLElement, [
      OListParser.ListParser
    ]> {
  }
  export namespace OListParser {
    export import ListParser = UListParser.ListParser;
  }
}
// index.ts
export {MarkdownParser} from './index.d';
```

**Expected behavior:**

```js
// index.js
```

**Actual behavior:**

```js
// index.js
export { MarkdownParser } from './index.d';
```

**Comment by mhegazy** [comment]
`MarkdownParser` is a value. Type-only exports are elided, but not values.

consider changing your code to be:

```ts
import {MarkdownParser } from './index.d';
type MarkdownParser_type = MarkdownParser;
export { MarkdownParser_type  as MarkdownParser};
```

**Comment by falsandtru** [comment]
The turning point is here:

```diff
  export namespace OListParser {
-    export import ListParser = UListParser.ListParser;
+    export type ListParser = UListParser.ListParser;
  }
```

When i change as above, outputs are removed. `export import` doesn't work correctly. Additionally, is there a correct case that imports from .d.ts files in emitted code?

**Comment by falsandtru** [comment]
cc @vladima

**Comment by falsandtru** [comment]
Even when i use only interfaces and namespaces (**values don't exist anywhere**), this incorrect importing will be emitted. `export import` is confused. This is a bug. @ahejlsberg @DanielRosenwasser @vladima 

```diff
- declare abstract class Markdown<T> {
+ interface Markdown<T> {
  MARKDOWN?: T;
}
```

**Comment by mhegazy** [comment]
I thought `MarkdownParser` was a class. Sorry about that.

The issue as you noted is the `import` and import is always considered to have a value. if you want it to be a type, use `export type` instead.

**Comment by falsandtru** [comment]
> import is always considered to have a value.

Is this a spec? It seems the unfavorite behavior.

**Comment by mhegazy** [comment]
> Is this a spec? It seems the unfavorite behavior.

Yes. though the spec only talks about what makes a module un-instantiated, see https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#10.1

The rational here is that these decisions, on whether a module is instantiated or not are done on local level, e.g. just by inspecting a single file, where as `imports` can alias entities from other namespaces/files, which makes this analysis much more complicated.

I would recommend using type aliases if/when you only need to alias types.

**Comment by falsandtru** [comment]
> which makes this analysis much more complicated.

I see, thanks for letting me know.
