### ISSUE TITLE
Issue with open ended enums

### ISSUE THREAD

**Issue by koninos** [Microsoft/TypeScript#14065]
**TypeScript Version:**  2.1.x

**Code**
Typescript Enums are number based and are also open ended. This means that I can have
```ts
enum Color {
   Red = 0,
   Green,
   Blue
}

enum Color {
   Black
}

```
the issue here is that now I have Color.Red associated with value 0 and Color.Black also associated with value 0. I would expect Color.Black to be associated with the next available value which is 3.

**Expected behavior:**
```ts
enum Color {
   Red = 0,
   Green = 1,
   Blue = 2,
   Black = 3
}
```
**Actual behavior:**
```ts
enum Color {
   Red = 0,
   Green = 1,
   Blue = 2,
   Black = 0
}
```

**Comment by RyanCavanaugh** [comment]
Arguments can be made either way for whether to pick up at 3 or 0. We had to pick one and did; there is absolutely no way we'd change it now and break who knows how much code.
