### ISSUE TITLE
getTypeAtLocation returns 'any' on ExpressionStatement

### ISSUE THREAD

**Issue by andy-ms** [microsoft/TypeScript#14077]
**TypeScript Version:**  nightly (2.2.0-dev.20170214)

Don't have a simple way to repro this yet. This should be easy to fix, just by using its child expression.

**Comment by mhegazy** [comment]
Well, statements do not have a type. Can you elaborate on the scenario?

**Comment by andy-ms** [comment]
I needed a workaround when looking for the type of the AST node on a line of code. https://github.com/Microsoft/dtslint/blob/8b855d032e3340444635fd47e352bd3f6f88892f/src/rules/expectRule.ts#L148

**Comment by mhegazy** [comment]
And why is not your fix of getting the expression of  the statement fits sufficient?

**Comment by andy-ms** [comment]
It is, just wasn't obvious that callers were responsible for getting the nearest expression. If this function only works on `Expression` nodes, maybe that should be its parameter type?

**Comment by mhegazy** [comment]
It was ment originally for identifiers.. so it should work on declarations as well as expressions..

**Comment by mhegazy** [comment]
which would suggest that it should work on statements as well :)
