### ISSUE TITLE
Decorators do not recognize class inheritance

### ISSUE THREAD

**Issue by IIIristraM** [Microsoft/TypeScript#14082]
Hello, I'm using TypeScript version 2.1.6. It looks like class decorators don't handle class type properly. 

This code emits error, while ChildClass is inherited from Base and should not be any problems with it's casting to a parent class.

```
declare class Base {}

function decorator(inputClass: typeof Base): typeof Base {
  return inputClass;
}

@decorator
class ChildClass extends Base {
  public foo() {}
} 
```

Compilation error:

> Unable to resolve signature of class decorator when called as an expression.
>   Type 'typeof Base' is not assignable to type 'typeof ChildClass'.
>     Type 'Base' is not assignable to type 'ChildClass'.
>       Property 'foo' is missing in type 'Base'.

**Comment by mhegazy** [comment]
The return value of a decorators becomes the declaration. think of this as `const ChildClass = decorator(class childClass extends Base {...});`. In that sense decorators can not change the type. 

Your decroator function says it always returns `Base` constructor, even if you pass it a `Child` constructor.

I think what you want is to use generics:

```ts
function decorator<T extends typeof Base>(inputClass: T): T {
  return inputClass;
}
```

**Comment by IIIristraM** [comment]
No, initially I faced with a problem to use Redux with TypeScript.
react-redux lib contains decorator @connect which always applied to a class that inherited from React.Component, like
```
@connect()
class MyComponent extends React.Component<Props, State> {
   ...
}
```

In most cases MyComponent has its own methods, so class signature differs from a base class.
So in current realisation there's no way to use this decorator in a manner it was designed.

More details on original issue (https://github.com/Microsoft/TypeScript/issues/9365). The problem of inheritance was mentioned there but not accented.

Current type-definition of the decorator briefly:
```
type ComponentClass<P> = React.ComponentClass<P>;

interface ComponentDecorator<TOriginalProps, TOwnProps> {
    (component: ComponentClass<TOriginalProps> | StatelessComponent<TOriginalProps>): ComponentClass<TOwnProps>;
}

export declare function connect<TStateProps, TDispatchProps, TOwnProps>(
    mapStateToProps: FuncOrSelf<MapStateToProps<TStateProps, TOwnProps>>,
    mapDispatchToProps?: FuncOrSelf<MapDispatchToPropsFunction<TDispatchProps, TOwnProps> | MapDispatchToPropsObject>
): ComponentDecorator<TStateProps & TDispatchProps, TOwnProps>;
```

So finally its input and output are `React.ComponentClass<P>`, that is the base class of the target class, which leads to compilation error

**Comment by IIIristraM** [comment]
Ok, I see.

Well, but I need to express more complex case, something like

```
class Base<T> {
}

interface IBaseCtr<T> {
  new(): Base<T>;
}

function wrapper<TOut extends IBaseCtr<number>, TIn extends IBaseCtr<string>>(ctr: TIn): TOut {
  return class Wrapper extends Base<number> {
    inner: Base<string> = new ctr();
  }
}

@wrapper
class Child extends Base<string> {
  foo() {}
}
```

So, I need to convert one class to another while both of them inherits from same generic class with different generic parameter. But this code also fails to compile.

Actually there are problems with react-redux `@connect` decorator, kind of https://github.com/Microsoft/TypeScript/issues/9365

Also it's strange that code below compiles fine
```
declare class Base {}

function decorator(inputClass: typeof Base): typeof Base {
  return inputClass;
}

class ChildClass extends Base {
  public foo() {}
} 

decorator(ChildClass)
```

`@decorator `and `decorator(...)` express the same thing but type-checked differently, which is quite strange

**Comment by gcanti** [comment]
> @decorator and decorator(...) express the same thing but type-checked differently, which is quite strange

This is strange indeed, and makes hard to use decorators for defining "HOC"s in React
