### ISSUE TITLE
FormData should be exposed in a webworkers

### ISSUE THREAD

**Issue by dmikis** [microsoft/TypeScript#14085]
**TypeScript Version:**  2.1.6

`FormData` interface isn't present in `lib.webworker.d.ts`, but [according to spec](https://xhr.spec.whatwg.org/#interface-formdata), should be.

AFAIK, those files are generated, so there's no point in sending patches for them. Is there a repo with sources for this files? If so, can I send a patch to it?

**Comment by dmikis** [comment]
For some reason threre's `FormData` interface in `lib.es6.d.ts`:

```
$ grep 'FormData' node_modules/typescript/lib/lib.es6.d.ts
interface FormData {
declare var FormData: {
    prototype: FormData;
    new (form?: HTMLFormElement): FormData;
$
```

We definitely should delete it from there.

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by Manish-Giri** [comment]
I'll try to work on this.

**Comment by saschanaz** [comment]
This has been fixed.

**Comment by vhscom** [comment]
Hi @RyanCavanaugh. Could you clarify the remaining backlogged work needed to close this issue? Thanks!

**Comment by jakebailey** [comment]
I don't think there's anything, just wasn't closed after the PR was pulled into TS.
