### ISSUE TITLE
Define an optional variable

### ISSUE THREAD

**Issue by alex3165** [Microsoft/TypeScript#14087]
This is a proposal, I would like to be able to define an optional variable which automatically set the type to the variable of type `T` or `undefined`.

Currently we can only define optional function parameter or object property.

**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)

**Code**

```ts
  const getParams = (state: State): NextState | undefined => (state.blabla || undefined)
  const prevParams?: NextState | undefined = getParams(state);
```

**Expected behavior:**

```ts
  const getParams = (state: State): NextState | undefined => (state.blabla || undefined)
  const prevParams?: NextState = getParams(state);
```

(Inspired from Swift)

**Comment by RyanCavanaugh** [comment]
Duplicate #13321. Please search before logging new issues.

![image](https://cloud.githubusercontent.com/assets/6685088/22988893/95638c54-f368-11e6-89eb-8d5dce7ea01e.png)
