### ISSUE TITLE
WorkerGlobalScope and Window don't have a common ancestor type

### ISSUE THREAD

**Issue by dmikis** [Microsoft/TypeScript#14086]
Subj. Should there be one?

Right now it creates difficulties to define types those are common for DOM and WebWorkers environments (see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14641, for example).

**Comment by SaschaNaz** [comment]
The spec says about [`WindowOrWorkerGlobalScope`](https://html.spec.whatwg.org/multipage/webappapis.html#windoworworkerglobalscope) but it does not exist on lib.d.ts.

**Comment by mhegazy** [comment]
The global polluter for WebWorkers is `WorkerGlobalScope`.

The two types can not co-exist. the workers do not have access to the DOM, and the regular script does not have access to the Worker APIs. 

if you are writing a webworker, then you should be using `--lib webworker`. 

Also `fetch` should be in the default library starting TS 2.3.

**Comment by SaschaNaz** [comment]
I think we are not talking about co-existing.

Case 1:

```ts
interface Window {
  foo(): void;
}
let foo: typeof window.foo;

// in normal.ts
window.foo(); // ok
foo(); // ok

// in worker.ts
self.foo(); // error
```

Case 2

```ts
// The interface which should be referenced from both Window and WorkerGlobalScope
interface WindowOrWorkerGlobalScope {
  foo(): void;
}
let foo: typeof self.foo;

// in normal.ts
window.foo(); // ok
foo(); // ok

// in worker.ts
self.foo(); // ok

```

**Comment by mhegazy** [comment]
if it is present in both, then declare it twice., i.e.:

```ts
declare global {
    // window.foo
    interface Window {
         foo(): void;
    }
    // self.foo
    interface WorkerGlobalScope {
         foo(): void;
    }
    function foo(): void; // in global for both
}
```

**Comment by SaschaNaz** [comment]
Can't we add `interface WindowOrWorkerGlobalScope` to remove the duplication, as the HTML specification says?

**Comment by mhegazy** [comment]
> Can't we add interface WindowOrWorkerGlobalScope to remove the duplication, as the HTML specification says?

we can. not convinced that this is makes that much simpler.

**Comment by dmikis** [comment]
I think it's OK to just declare it twice.
