### ISSUE TITLE
this.constructor.name changes in TypeScript >2.0.0.

### ISSUE THREAD

**Issue by fluffywaffles** [Microsoft/TypeScript#14099]
**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)

**Code**

```ts
class Base {
  name: string
  constructor () {
    this.name  = this.constructor.name
  }
}

class SomeThing extends Base {
  constructor () {
    super()
  }
}

let thing1 : SomeThing = new SomeThing()

console.log(thing1.name)
```

**Expected behavior:**

In TypeScript 2.0.0 and prior, the code above will output "SomeThing".

**Actual behavior:**

In TypeScript 2.1.6 and 2.2.0, the code above will output "Base".

**Comment by mhegazy** [comment]
Something else is going on here. i do not see this locally:

```sh
c:\test>type a.ts
class Base {
  name: string
  constructor () {
    this.name  = this.constructor.name
  }
}

class SomeThing extends Base {
  constructor () {
    super()
  }
}

let thing1 : SomeThing = new SomeThing()

console.log(thing1.name)
c:\test>tsc --v
Version 2.3.0-dev.20170215

c:\test>tsc c:\test\a.ts --lib es6,dom

c:\test>node a.js
SomeThing

c:\test>npm install -g typescript@rc
C:\Users\mhegazy\AppData\Roaming\npm\tsc -> C:\Users\mhegazy\AppData\Roaming\npm\node_modules\typescript\bin\tsc
C:\Users\mhegazy\AppData\Roaming\npm\tsserver -> C:\Users\mhegazy\AppData\Roaming\npm\node_modules\typescript\bin\tsserver
C:\Users\mhegazy\AppData\Roaming\npm
`-- typescript@2.2.0


c:\test>tsc --v
Version 2.2.0

c:\test>tsc c:\test\a.ts --lib es6,dom

c:\test>node a.js
SomeThing

c:\test>npm install -g typescript@latest
C:\Users\mhegazy\AppData\Roaming\npm\tsc -> C:\Users\mhegazy\AppData\Roaming\npm\node_modules\typescript\bin\tsc
C:\Users\mhegazy\AppData\Roaming\npm\tsserver -> C:\Users\mhegazy\AppData\Roaming\npm\node_modules\typescript\bin\tsserver
C:\Users\mhegazy\AppData\Roaming\npm
`-- typescript@2.1.6


c:\test>tsc --v
Version 2.1.6

c:\test>tsc c:\test\a.ts --lib es6,dom

c:\test>node a.js
SomeThing
```

**Comment by fluffywaffles** [comment]
I foolishly over-simplified my least minimal reproduction. My apologies. The problem only occurs when you are extending the built-in `Error` type. I am testing in Nodejs v4.3, btw. This error also occurs in node latest (at time of writing v7.6.0) and lts (at time of writing v6.10.0).

```ts
class AnError extends Error {
  constructor () {
    super()
    this.name = this.constructor.name
  }
}

let x : AnError = new AnError()

console.log(x.name)

// When you aren't inheriting from Error, however...

class AbstractThing {
  public name : string
  constructor () {
    this.name = this.constructor.name
  }
}

class Thing extends AbstractThing {
  constructor () {
    super()
  }
}

let y : Thing = new Thing()

console.log(y.name)
```

Expected output:

```
AnError
Thing
```

Actual output:

![output](http://i.imgur.com/Mp0D886.png)

**Comment by steverob2k** [comment]
This is outlined in the breaking changes documentation when 2.1 came out....

https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#extending-built-ins-like-error-array-and-map-may-no-longer-work

**Comment by fluffywaffles** [comment]
Oh!! I didn't see that. Thanks! I guess that explains it.

**Comment by fluffywaffles** [comment]
Actually, this fix:
```
class AnError extends Error {
  constructor () {
    super()

    this.name = this.constructor.name
    Object.setPrototypeOf(this, AnError.prototype)
  }
}
```

Does not affect the behavior I have described.

I am sure the problem is related; but after looking again I realized I had already read that documentation and it never occurred to me that these were the same. `instanceof` isn't even broken! And the Prototype chain is clearly being inherited correctly -- all the stuff I expect to see on an Error object is there. The problem is, it's somehow the case that the `name` inherited from Error is... overwriting? The `name` for my constructor.

**Comment by fluffywaffles** [comment]
Here's my new minimal reproduction:

```ts
class AnError extends Error {
  constructor () {
    super()
    this.name = this.constructor.name
    Object.setPrototypeOf(this, AnError.prototype)
  }
}

let x : AnError = new AnError()

console.log(x instanceof AnError) // => true, tsc v2.2.1

console.log(x.name) // => Error
```

**Comment by steverob2k** [comment]
I am pretty sure you need to have the Object.setPrototype call straight after calling super() then add the line to set the name

**Comment by fluffywaffles** [comment]
@steverob2k That did it. Inconvenient though it is to add those two lines to every function that specializes Error, AnError, etc. on down, it does work.
