### ISSUE TITLE
Object literal not matching class interface when overriding prototype methods

### ISSUE THREAD

**Issue by whitneyit** [Microsoft/TypeScript#14101]
**TypeScript Version:**  2.1.1 / nightly

**Code**

```ts
class Student {

    public id: number;

    public name: string;

    public constructor(options: { id: number, name: string }) {
        this.id = options.id;
        this.name = options.name;
    }

    public toString() {
        return `#${this.id}: ${this.name}`;
    }

}

const Huey = new Student({ id: 1, name: 'Huey' });
const Duey = new Student({ id: 2, name: 'Duey' });
const Luey = { id: 3, name: 'Luey' };

const students: Array<Student> = [
    Huey,
    Duey,
    Luey,
];
```

**Expected behavior:**
Expected a TypeError because `Luey` doesn't have a custom `toString` method.

**Actual behavior:**
No Error.

**Comments:**
If a custom method of `test()` is added to the `Student` class, `Luey` correctly fails the type check. However, when overriding certain prototype methods, this is no longer the case. The above code example demonstrates this.

Is it possible to add an option in `tsconfig` to allow narrowing of types such that `Luey` would be prevented from being added to the `students` Array? This restriction should apply regardless of the `toString` change.

**Comment by RyanCavanaugh** [comment]
Objects have a built-in `toString`, so there's nothing *per se* wrong with this code. There's no mechanism in the type system to pick and choose what is "custom" and what isn't.

**Comment by whitneyit** [comment]
I figured as much. That's why I asked about adding an option to `tsconfig`.

> Is it possible to add an option in `tsconfig` to allow narrowing of types such that `Luey` would be prevented from being added to the `students` Array?

I'm fine to champion this work.

**Comment by RyanCavanaugh** [comment]
If you really want this behavior, just use a custom `lib.d.ts` that deletes these properties from `Object`

**Comment by whitneyit** [comment]
Unfortunately that doesn't help with this example :(

```ts
class Student {

    public id: number;

    public name: string;

    public constructor(options: { id: number, name: string }) {
        this.id = options.id;
        this.name = options.name;
    }

}

const Huey = new Student({ id: 1, name: 'Huey' });
const Duey = new Student({ id: 2, name: 'Duey' });
const Luey = { id: 3, name: 'Luey' };

const students: Array<Student> = [
    Huey,
    Duey,
    Luey,
];

alert(students.every(student => student instanceof Student));
```

**Comment by RyanCavanaugh** [comment]
If you have any private or protected members in your class, the object literal won't be considered a substitute.

**Comment by whitneyit** [comment]
That's good to know. I suppose that I could use the following then :)

```ts
class Student {

    private gh14101: boolean;

}
```

Does that mean that it's a no go on the `tsconfig` rule?

**Comment by RyanCavanaugh** [comment]
Flags need to justify the fact that they increment `k` in the `2 ^ k` growth in configuration space, and need to make sense as global options; I don't think either criteria is met here. The workarounds to get the behavior you want are simple, and it's not at all clear that this is a rule you would apply to *all* classes rather than *some* classes.

**Comment by whitneyit** [comment]
Fair enough. Thanks mate
