### ISSUE TITLE
Allow banning ///<reference> when using --noResolve

### ISSUE THREAD

**Issue by DeneshPohar** [Microsoft/TypeScript#14119]
**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)
**Background/Context**
Our team is currently migrating a large codebase from internal to external modules.  For various reasons we'd like to use the ```--noResolve``` tsc compiler option.

**Code**
myFile.ts:
```ts
/// <reference path="abc.ts"/>

namespace foo {
    // do stuff
}
```

tsconfig.json:
```json
{
    "compilerOptions": {
        "target": "ES5",
        "noResolve": true
    }    
}
```

**Actual behavior:**
The ```/// <reference>``` is *silently* ignored, because of the ```noResolve```.  This is documented & by design.

**Expected behavior:**
Because the ```/// <reference>``` is ignored, I'd like to ban it completely to prevent anyone from adding new ones.  I'd like an optional compiler warning to be raised if ```/// <reference>``` is used with ```noResolve```.

**Comment by mhegazy** [comment]
noResolve has a different meaning. it is there for historic reasons, i would recommend not using it unless you have to.

I would recommend setting a tslint [no-reference](https://palantir.github.io/tslint/rules/no-reference/) rule to flag unwanted triple-slash-references
