### ISSUE TITLE
Enum switch case metching issue

### ISSUE THREAD

**Issue by teterovic** [Microsoft/TypeScript#14115]
**TypeScript Version:**  
tsc -v
Version 2.1.5

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
export class User {
       preferences: UserPreferences;
}

export class UserPreferences {
    landingPage: LandingPageEnum = LandingPageEnum.Library;
}
....
.map((res: Response) => Object.assign(new User(), res.json())))
.....
switch (this.user.preferences.landingPage) {
            case LandingPageEnum.Library:
                ///////// Should jump here but it doesn't the json value was "landingPage" : "Library"
                break;
            case LandingPageEnum.LastActiveView:
                ////////////
                break;
        }
```
Visual Studio code says the value is of type LandingPageEnum after the convertion 
![image](https://cloud.githubusercontent.com/assets/7413906/23028756/90e8dae8-f468-11e6-8a59-ca530c7e4eb2.png).

But when compiled to javascript it's not matching the case

At the end(after debugging the generated code) i got the expected behaviour with accessing the variable inside the enum but i got errors TS2678 by VS Code / TS lint?
![image](https://cloud.githubusercontent.com/assets/7413906/23028861/e5c67b9c-f468-11e6-8524-765774aaa57e.png). 
Could also be a VS Code issue but logically it shouldn't. Please look at the generated code and the fixed code but with bugs in expected behavior

**Expected behavior:**
switch (user_preferences_model_1.LandingPageEnum[this.userService.loggedInUser.preferences.landingPage]) {
            case user_preferences_model_1.LandingPageEnum.Library:
                this.router.navigateByUrl('/collection/library');
                break;
            case user_preferences_model_1.LandingPageEnum.LastActiveView:
                this.router.navigateByUrl('/collection/empty');
                break;
        }

**Actual behavior:**
switch (this.userService.loggedInUser.preferences.landingPage) {   // It leaves the string it's not encapsulated in the enum user_preferences_model_1.LandingPageEnum[] so it cant be matched by number value
            case user_preferences_model_1.LandingPageEnum.Library:
                this.router.navigateByUrl('/collection/library');
                break;
            case user_preferences_model_1.LandingPageEnum.LastActiveView:
                this.router.navigateByUrl('/collection/empty');
                break;
        }

**Comment by RyanCavanaugh** [comment]
Please provide a **self-contained** repro.

**Comment by teterovic** [comment]
```
class User {
    preferences: Preferences;
}

class Preferences {
    entry: EntryEnum;
}

enum EntryEnum {
    Library,
    Test
}

let json: any = {
    "username": "test",
    "preferences": {
        "entry": "Library"
    }
};

let user: User = Object.assign(new User(), json);

console.log(user);

switch (user.preferences.entry) {
    case EntryEnum.Library:
        console.log("WORKS");
        break;
}

```

![image](https://cloud.githubusercontent.com/assets/7413906/23036269/7b2a4bf0-f482-11e6-924f-46ec6b6c0e4e.png)

the output is different then when i use it inside angular but it still doesn't work. The switch is not triggered.
Sorry, maybe I misunderstand some typescript concept. The same problem when I try to cast with 
let user: User = <User>json;

**Comment by teterovic** [comment]
ok i got it it can be solved with

`enum EntryEnum {
    Library = <any>"Library",
    Test = <any>"Test"
}`

 a bit ugly but it works, would be better to encapsulate it like proposed

**Comment by gcnew** [comment]
The real problem is that you are cheating the type system with
```ts
let user: User = Object.assign(new User(), json);
```

`json` is not a valid `User`  because the type of `EntryEnum.Lybrary` is `0` and you've provided a `string`. The error is reported clearly in the following definition:

```ts
// error: Type '"Library"' is not assignable to type 'EntryEnum'.
let json: User = {
    "preferences": {
        "entry": "Library"
    }
};
```

If you want string enums, better stay away from TypeScript's non-standard `enums`. String literal unions work very well for such cases:

```ts
type EntryEnum = 'Library' | 'Test'

let json: User = {
    "preferences": {
        "entry": "Library"
    }
};

let user: User = Object.assign(new User(), json);

switch (user.preferences.entry) {
    case 'Library':
        break;
}
```

PS:  You may find [io-ts](https://github.com/gcanti/io-ts) interesting. It's a library for validation and conversion of parsed JSON into well-typed objects.
