### ISSUE TITLE
Method focus does not exist on type 'Element'.

### ISSUE THREAD

**Issue by prostoandrei** [Microsoft/TypeScript#14111]
Hello!

**TypeScript Version:**  2.1.6

**Code**

```ts
document.querySelector(`#id`).focus(); // Property 'focus' does not exist on type 'Element'
// but this work fine..
const a = <HTMLElement>document.querySelector(`[${this.horizonatalItemAttrName}]`);
a.focus();
```

**Expected behavior:** Focus exist on type 'Element' 

**Actual behavior:** Property 'focus' does not exist on type 'Element'

**Comment by jamiewinder** [comment]
This is correct; `focus` is a method on `HTMLElement`, but not on `Element` itself:
https://developer.mozilla.org/en-US/docs/Web/API/Element

**Comment by prostoandrei** [comment]
Oh) Ok, thank you)
