### ISSUE TITLE
TypeScript compilation breaks inheritance from native Objects

### ISSUE THREAD

**Issue by vTripes** [Microsoft/TypeScript#14117]
**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)
**NodeJS Version:** 7.4.0

**Code**

```ts
// window.classname to have the class available in every scope
window.Myclass = class extends Date {
  constructor ()
  {
    super()
  }
}
var myVar = new Myclass();
myVar.getDate(); // => 16
```

**Expected behavior:**
It should return the Date number of actual date (from 1 to 31) as the user class should have inherited of the properties and methods.

**Actual behavior:**
TypeScript compilation breaks inheritance and JavaScript throws a `TypeError: this is not a Date object.` (message of TypeError may vary depending of the browser used).

**Comment by zelein** [comment]
Try this:

`
window.MyClass = class extends Date {
  constructor() {
    super();
    (<any> this).__proto__ = Myclass.prototype;
  }
}
`

**Comment by zelein** [comment]
Try this:

```
window.MyClass = class extends Date {
  constructor() {
    super();
    (<any> this).__proto__ = Myclass.prototype;
  }
}
```

**Comment by vTripes** [comment]
It doesn't seem to work in my environment.
So I ended up writing a old school wrapper function and pretending this is a class.
