### ISSUE TITLE
compileOnSave doesn't transpile .js files on save

### ISSUE THREAD

**Issue by sgjoy1** [Microsoft/TypeScript#14120]
My Setup:
Visual Studio 2015 Update 3
Microsoft.TypeScript.MsBuild 2.1.5
tsc version 1.8.34

tsconfig.json:
```
{
	"compileOnSave": true,
	"compilerOptions": {
		"target": "es5",        
		"allowJs": true,
		"outDir": "GeneratedScripts",
		"disableSizeLimit": true
	},
	"include": [
		"Scripts/**/*"
	],
	"exclude": [
		"GeneratedScripts"
	]
}
```
My .js and .ts files are in the Scripts folder and my tsconfig.json is at the same root level as the Scripts folder in my project.

I can build to transpile .js and .ts files, and I can save to transpile .ts files, but saving does not transpile .js files. Is this a known issue?

**Comment by bowdenk7** [comment]
This is a known issue and the fix has already been merged in. Unfortunately we can't ship anything back to VS 2015 now that 2017 RC is out.

You can work around this right now by running tsc in watch mode (`tsc -w`) from the command line or other task runner extensions. 

A better solution might be to port [this extension](https://github.com/madskristensen/TypeScriptCompileOnSave) back to VS 2015. This extension launches its own compile step using tsc and thus circumvents the current issue with the JS file watchers. I've already spoken to the extension author and he is going to try to publish a 2015 version sometime next week.

**Comment by sgjoy1** [comment]
Thanks for the update! For now I think we'll work around the issue by simply building the solution to transpile js files. I'm not sure when we'll be able to upgrade to VS2017, so a VS2015 port would be nice, but it's understandable if you can't put a port out.

**Comment by madelson** [comment]
+1 for a VS2015 port.

**Comment by jcrben** [comment]
@mhegazy is the policy to leave won't fix issues open?
