### ISSUE TITLE
Add flag to enforce strict signature checking on interface methods and abstract class methods

### ISSUE THREAD

**Issue by jws305** [microsoft/TypeScript#14125]
```
abstract class MyClassBase {
    abstract foo(a: number, b: number);
}
class MyClassImpl {
    foo(a: number) { }
}
```
The above example is valid Typescript according to http://typescript.codeplex.com/workitem/350.  The issue I am running in to is that while refactoring some code, I added an additional number parameter to the `abstract foo` method and expected the compiler to warn me that the derived implementations were invalid since the additional parameter is not optional.  This breaks type safety since it makes all parameters implicitly optional.

My suggestion is to add a compiler flag that would enforce strict method signature checking.  When parameters are optional, they must be explicitly defined.  For example.
```
abstract class MyClassBase {
    abstract foo(a: number, b: number);
    abstract bar(a: number, b?:number);
    abstract baz(a: number, b?: number);
}
class MyClassImpl {
    foo(a: number) { } // Invalid
   bar(a: number) { } // Invalid
   bar(a: number, b?:number) { } // Valid
}
```
The only issues I can see with enabling this hypothetical flag would be using dependent libraries that were built without it.

**Comment by leoasis** [comment]
This is causing issues when typing methods that have multiple parameters:

```ts
interface Foo {
    foo(a: {}, b: {}, c: (err: Error | null, res?: string) => void): void
}

class Bar implements Foo {
    foo(a: {}, /*b: {},*/ c: (err: Error | null, res?: string) => void) {
        c(null, 'success');
    }
}

const a: Foo = new Bar();

a.foo({}, {}, (err, res) => { 
  console.log(res);
}); // throws "Uncaught TypeError: c is not a function"
```

**Comment by RyanCavanaugh** [comment]
Closing due to low feedback volume
