### ISSUE TITLE
'index' shouldn't be included as part of module path in quick fix

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#14138]
Basing this off of my current setup.

Try creating the following folder structure:

* foo/
  * index.ts
* bar/
  * index.ts

Contents in `foo/index.ts`:

```ts
export interface Thing {
}
```

Contents in `bar/index.ts`:

```ts
export let thing: Thing;
```

Try using the appropriate code action to import `Thing`. The generated code is currently:

```ts
import { Thing } from "../foo/index"; 
```

The fix is correct, however, most people don't include `index` as part of their path when importing a module. I'd argue that TypeScript shouldn't either.

**Comment by amcasey** [comment]
@minestarks Did you already fix this?

**Comment by minestarks** [comment]
Yes #17078 should have fixed this.
