### ISSUE TITLE
`lib.dom.ts` incorrect return type for `Document.elementFromPoint`

### ISSUE THREAD

**Issue by sccolbert** [microsoft/TypeScript#14139]
According to:
https://drafts.csswg.org/cssom-view/#dom-document-elementfrompoint

`Document.elementFromPoint` should return `Element | null`. It currently returns `Element`.

**Comment by mhegazy** [comment]
Seems fixed in latest.

**Comment by sccolbert** [comment]
Not fixed in master:
https://github.com/Microsoft/TypeScript/blob/master/lib/lib.dom.d.ts#L3356

**Comment by mhegazy** [comment]
Sorry about that.

**Comment by saschanaz** [comment]
Has been fixed now.

**Comment by jakebailey** [comment]
Just looking at old issues; yeah, this was fixed in #25944.
