### ISSUE TITLE
TypeScriptToolsVersion uses unexpected TypeScript version without warning/error

### ISSUE THREAD

**Issue by 304NotModified** [Microsoft/TypeScript#14149]
**TypeScript Version:**  1.8

I have `<TypeScriptToolsVersion>1.7</TypeScriptToolsVersion>` in my csproj
I have installed:

- TypeScript Version 1.8
- TypeScript Version 2.1 (got it with VS2017)
- Visual Studio 2015

**Expected behavior:**

- Visual Studio uses TypeScript version 1.8, or
- Visual Studio gives an error, or
- Visual Studio gives a warning,

**Actual behavior:**

- Visual Studio uses TypeScript 2.1
- No error/warning shown
- Broke a lot of builds after installing VS2017!

**Comment by yuit** [comment]
Ping @paulvanbrenk is this something we could issue an error from our side?

**Comment by paulvanbrenk** [comment]
If we can't find the version specified we use the newest installed version, which is arbitrary, but easier to reason about than 'next' version... or the 'previous' version.

We had an error/warning before, but got a lot of complaints about that too...
