### ISSUE TITLE
strictNullChecks incorrectly determines type

### ISSUE THREAD

**Issue by KalitaAlexey** [Microsoft/TypeScript#14145]
**TypeScript Version:**  2.1.6
**Code**

```ts
class TextDocument {}
class Promise<T> {
    public then(closure: (T)=>void) {}
}
class B {
    public constructor(p: Position, p2: Position) {}
}

class A {
    private firstDanglingParen(): Position | undefined {
        return undefined;
    }

    private foo() {
        let startPos = this.firstDanglingParen();
        if (startPos === undefined) {
            return undefined;
        }
        if (!startPos) {
            return undefined;
        }
        return this.runCommand().then(() => {
            new B(startPos, startPos);
            // error TS2345: Argument of type 'Position | undefined' is not assignable to parameter of type 'Position'.
            // Type 'undefined' is not assignable to type 'Position'
        });
    }

    private runCommand(): Promise<void> {
        return new Promise<void>();
    }
}
```

**Expected behavior:**
It doesn't give me an error: `Argument of type 'number | undefined' is not assignable to parameter of type 'number'` at the line `printValue(n);`.

**Actual behavior:**
It does.

**Comment by RyanCavanaugh** [comment]
What's the definition of `getValueOrUndefined` ?

**Comment by KalitaAlexey** [comment]
@RyanCavanaugh,
I have edited the description.

**Comment by blakeembrey** [comment]
That looks right to me, the value is number or undefined according to your functions return signature. If you expect it to always be a number, the return signature should probably just be a number.

**Comment by KalitaAlexey** [comment]
@blakeembrey,
Wait I again mistyped.

**Comment by KalitaAlexey** [comment]
I will close it since I can't reproduce it on small example.

**Comment by KalitaAlexey** [comment]
I have a big piece of code. I can't reduce it.

**Comment by KalitaAlexey** [comment]
I have updated the description.

**Comment by RyanCavanaugh** [comment]
Change `let startPos` to `const startPos` - the compiler doesn't "know" that there might not be future assignments of the value `undefined` to `startPos` which run after the callback has been kicked off

**Comment by KalitaAlexey** [comment]
@RyanCavanaugh,
How he can not to know?
