### ISSUE TITLE
Implement `slot` attribute type.

### ISSUE THREAD

**Issue by trusktr** [Microsoft/TypeScript#14147]
v2.1.5

```
ERROR in ./src/app.tsx
(53,25): error TS2339: Property 'slot' does not exist on type 'HTMLProps<HTMLHeadingElement>'.
```

All browsers support this property now.

Not much more detail is needed for this issue.

**Comment by trusktr** [comment]
Or is that a React type problem?

**Comment by yuit** [comment]
Hi @trusktr....this issue is from @type/react we will have to add that attributes into the .d.ts file of react. I will close the issue...[Here ](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/14711)is the one in .d.ts repo .
