### ISSUE TITLE
"for await" inside async functions

### ISSUE THREAD

**Issue by LeviticusMB** [Microsoft/TypeScript#14151]
With PR #11326 now merged, isn't this supposed to work?

**TypeScript Version:**
Version 2.3.0-dev.20170217

**Node version**
v6.9.1

**Command line**
```sh
tsc --target es6 --lib esnext --outFile for-await.js for-await.ts ; node for-await.js
```

**Code**

```ts
function delay(ms) {
    return new Promise((resolve, reject) => {
        setTimeout(resolve, ms);
    });
}

async function* numbers() {
    yield 1;
    await delay(500);
    yield 2;
    await delay(1000);
    yield 3;
    await delay(2000);
    yield 4;
}

(async () => {
    let n = numbers();
    console.log(await n.next());
    console.log(await n.next());
    console.log(await n.next());
    console.log(await n.next());
    console.log(await n.next());

    for await (let next of numbers()) {
        console.log(next);
    }
})();
```

**Expected behavior:**
```
{ value: 1, done: false }
{ value: 2, done: false }
{ value: 3, done: false }
{ value: 4, done: false }
{ value: undefined, done: true }
1
2
3
4
```

**Actual behavior:**
```
{ value: 1, done: false }
{ value: 2, done: false }
{ value: 3, done: false }
{ value: 4, done: false }
{ value: undefined, done: true }
undefined
undefined
undefined
undefined
undefined
undefined
undefined
undefined
undefined
...
```

**Comment by rbuckton** [comment]
There are two underlying issues here: 

1. The `for-await-of` transformation isn't emitting the correct `await` downleveling for each step. 
2. The second is that you do not have `Symbol.asyncIterator` defined, and we are not reporting an error at runtime for this.

I'm working on a fix for (1) and part of (2) now. Afterwards you will need to ensure you have a shim for `Symbol.asyncIterator`, for example:

```ts
(<any>Symbol).asyncIterator = Symbol.asyncIterator || Symbol.for("Symbol.asyncIterator");
```

TypeScript does not currently plan to emit this shim itself, as it could collide with existing shim libraries.

**Comment by LeviticusMB** [comment]
Awesome, thanks! 👍
