### ISSUE TITLE
ReadonlyArray lost sort method

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#14167]
It is the non-destructive operation.

**TypeScript Version:**  master

**Code**

```ts
Object.freeze([]).sort();
```

**Expected behavior:**

ok

**Actual behavior:**

error

**Comment by DanielRosenwasser** [comment]
`sort` actually *is* a destructive operation, but you need to have some elements:

```ts
var x = Object.freeze([3,2,1]);
var y = x.sort();
```

![image](https://cloud.githubusercontent.com/assets/972891/23096928/1f43b26c-f5dc-11e6-984b-2ead5303565c.png)

I don't really see sorting an empty readonly array as useful, so I think this is working as intended.

**Comment by falsandtru** [comment]
Sorry, indeed.
