### ISSUE TITLE
How do I export the type?

### ISSUE THREAD

**Issue by ktalebian** [Microsoft/TypeScript#14168]
I have a project library that will be used in other projects. After compiling the project into vanilla JS, I also want to get a single `index.d.ts` file that contains all the types, similar to all the files available on https://github.com/DefinitelyTyped/DefinitelyTyped. 

Let's say, this project is called `components`. I want to be able to install this library and do the following:

```JSX
import {Page} from 'components'; // These are actual react components;
import {IPageObject} from 'components';   // This is an interface used in Page

const obj: IPageObject = {
   ...
}

<Page obj={obj} />
```

How is this done?

**Comment by blakeembrey** [comment]
You should add `declaration: true` to your `tsconfig.json` to generate `.d.ts` files and then set `typings` in `package.json` to the entry `.d.ts` file. That's all you'll need to do. For example: https://github.com/blakeembrey/free-style/blob/80253357ba0ce1cba5709b641e8aeca73e0f0cc6/package.json#L6.

**Comment by mhegazy** [comment]
Relevant information from the handbook: http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

**Comment by ktalebian** [comment]
Thanks all.
