### ISSUE TITLE
Type alias circularly references itself

### ISSUE THREAD

**Issue by pelotom** [microsoft/TypeScript#14174]
Why does this work:

```ts
type Foo = { x: Foo }
```

but this doesn't:

```ts
type Bar<A> = { x: A }
type Foo = Bar<Foo>
//   ^^^ Type alias 'Foo' circularly references itself
```

Shouldn't they be equivalent?

**Comment by tycho01** [comment]
See the explanation [here](https://github.com/Microsoft/TypeScript/issues/12525#issuecomment-263166239) for more info.

**Comment by RyanCavanaugh** [comment]
```ts
type Foo = Bar<Foo>
```
Illegal because we don't know that the definition of `Bar` isn't
```
type Bar<T> = T;
```

**Comment by pelotom** [comment]
Don't you have access to the definition of `Bar` so you could check that?

**Comment by RyanCavanaugh** [comment]
`Bar` might be
```
type Bar<T> = Foo<T>;
```
and now we're going infinitely deep.

Type aliases and interfaces are subtly different and there are rules about self-recursion for aliases that don't apply to interfaces. Because an alias is supposed to always be "immediately expandable" (it's as if it were an in-place expansion of its referand), there are things you can do interfaces you can't do with type aliases.

**Comment by pelotom** [comment]
Cycles can be detected and you can give up at that point, but as long as you can topologically order the type aliases by their references to one another it's fine. Haskell, PureScript, Scala etc have no problem with this.

**Comment by RyanCavanaugh** [comment]
I mean, we could, it's just that writing `interface Bar<T> extends Foo<T> { }` accomplishes the same thing without requiring us to rearchitect how type aliases work

**Comment by pelotom** [comment]
Sure, you can do that to emulate

```ts
type Bar<T> = Foo<T>
```

But what about

```ts
type Bar<T> = Foo<T> | Baz<T>
```

**Comment by skreborn** [comment]
I'm trying to create a type that circularly references itself, but in a way that it makes sense - or at least it does to me. This is basically the same problem as @pelotom is having.

    type Data = number | string | Data[] | Record<string, Data>;

If I modify it to the following, it works as intended, but this really is just more work for the user. This gets even worse when the data types are more complicated than a simple key-value pair.

    type Data = number | string | { [key: number]: Data } | { [key: string]: Data };

This type allows me to create values like the following and handle them in a type safe way even when they are deeply nested.

    const data: Data = {
        foo: [ 1, 'one', { two: 2 } ],
        bar: 'foobar'
    };

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Comment by pelotom** [comment]
I think this is a reasonable feature request for reasons that are made clear in the comments, can we reopen please?

**Comment by brandonbloom** [comment]
I think aleksey-bykov nailed the primary goal use case in this comment:
https://github.com/Microsoft/TypeScript/issues/6230#issuecomment-167023181

```typescript
type Json = null | string | number | boolean | Json[] | { [name: string]: Json }
```

**Comment by aleksey-bykov** [comment]
please stop bringing this silly "going infinitely deep" excuse, will you? we are all mature developers to know how to deal with it, aren't we?

**Comment by aleksey-bykov** [comment]
@brandonbloom the json problem was solved without recursive types, was posted somewhere in the issues

**Comment by RyanCavanaugh** [comment]
> please stop bringing this silly "going infinitely deep" excuse, will you? we are all mature developers to know how to deal with it, aren't we?

[Definitely 😆](https://github.com/Microsoft/TypeScript/search?q=overflow&type=Issues&utf8=%E2%9C%93)

**Comment by aleksey-bykov** [comment]
come on, if you know you going deep you can prevent it, if you dont then you will see those overflows and thrn you know, it is not a stopper by any means or not an excuse 


moreover if a problem is so bad maybe it makse sense to add some static checks to see where tge problem is likely to arise?

and why are so few new features to typescript been made lately, are you guys on a cut budget?

**Comment by RyanCavanaugh** [comment]
Lots of summer vacations, some parental leave, slightly more staff turnover than usual, and mapped types had a substantial bug tail that's taken a lot of time.

**Comment by pelotom** [comment]
I appreciate the TypeScript team's hard work. Mapped types have been a great addition and well worth the added complexity and corner cases!

**Comment by thorn0** [comment]
Is it the same issue? [playground](https://www.typescriptlang.org/play/index.html#src=%2F%2F%20Error%3A%20Type%20alias%20'DeepPartial'%20circularly%20references%20itself%0D%0Atype%20DeepPartial%3CT%3E%20%3D%20T%20extends%20Array%3Cinfer%20U%3E%0D%0A%20%20%3F%20Array%3CDeepPartial%3CU%3E%3E%0D%0A%20%20%3A%20T%20extends%20ReadonlyArray%3Cinfer%20U%3E%0D%0A%20%20%20%20%3F%20ReadonlyArray%3CDeepPartial%3CU%3E%3E%0D%0A%20%20%20%20%3A%20T%20extends%20Date%20%7C%20string%20%7C%20number%20%7C%20boolean%0D%0A%20%20%20%20%20%20%3F%20T%0D%0A%20%20%20%20%20%20%3A%20%7B%20%5BP%20in%20keyof%20T%5D%3F%3A%20DeepPartial%3CT%5BP%5D%3E%20%7D%3B)
```ts
// Error: Type alias 'DeepPartial' circularly references itself
type DeepPartial<T> = T extends Array<infer U>
  ? Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U>
    ? ReadonlyArray<DeepPartial<U>>
    : T extends Date | string | number | boolean
      ? T
      : { [P in keyof T]?: DeepPartial<T[P]> };
```

**Comment by donaldpipowitch** [comment]
I also wonder if I hit this bug or if it is different (modified example from [this Tweet](https://twitter.com/basarat/status/1007404668857679872)):

```ts
type FormValue<T> = { value: T }; // potentially many more fields

type FormModel<T> =
    //T extends Array<infer U> ? { value: FormModel<U>[] } : // THIS WORKS
    T extends Array<infer U> ? FormValue<FormModel<U>[]>:    // THIS ERRORS
    T extends object ? FormValue<FormModelObject<T>> :
    FormValue<T>;

type FormModelObject<T> = {
    [key in keyof T]: FormModel<T[key]>;
};

const model: FormModel<{
    bar: string,
    baz: {
        foo: string
    },
    items: string[]
}> = {} as any;

model.value.bar.value.toLowerCase();
model.value.baz.value.foo.value.toLowerCase();
model.value.items.value.map(item => item.value.toLowerCase());
```

([Playground](https://www.typescriptlang.org/play/index.html#src=type%20FormValue%3CT%3E%20%3D%20%7B%20value%3A%20T%20%7D%3B%20%2F%2F%20potentially%20many%20more%20fields%0D%0A%0D%0Atype%20FormModel%3CT%3E%20%3D%0D%0A%20%20%20%20%2F%2FT%20extends%20Array%3Cinfer%20U%3E%20%3F%20%7B%20value%3A%20FormModel%3CU%3E%5B%5D%20%7D%20%3A%20%2F%2F%20THIS%20WORKS%0D%0A%20%20%20%20T%20extends%20Array%3Cinfer%20U%3E%20%3F%20FormValue%3CFormModel%3CU%3E%5B%5D%3E%3A%20%20%20%20%2F%2F%20THIS%20ERRORS%0D%0A%20%20%20%20T%20extends%20object%20%3F%20FormValue%3CFormModelObject%3CT%3E%3E%20%3A%0D%0A%20%20%20%20FormValue%3CT%3E%3B%0D%0A%0D%0Atype%20FormModelObject%3CT%3E%20%3D%20%7B%0D%0A%20%20%20%20%5Bkey%20in%20keyof%20T%5D%3A%20FormModel%3CT%5Bkey%5D%3E%3B%0D%0A%7D%3B%0D%0A%0D%0Aconst%20model%3A%20FormModel%3C%7B%0D%0A%20%20%20%20bar%3A%20string%2C%0D%0A%20%20%20%20baz%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20foo%3A%20string%0D%0A%20%20%20%20%7D%2C%0D%0A%20%20%20%20items%3A%20string%5B%5D%0D%0A%7D%3E%20%3D%20%7B%7D%20as%20any%3B%0D%0A%0D%0Amodel.value.bar.value.toLowerCase()%3B%0D%0Amodel.value.baz.value.foo.value.toLowerCase()%3B%0D%0Amodel.value.items.value.map(item%20%3D%3E%20item.value.toLowerCase())%3B))

I wonder if there is a solution were I can re-use `FormValue` for the array-case instead of re-writing it...?

**Comment by kgtkr** [comment]
Is not it possible to solve this problem if `type F<T>` is considered to execute the function

**Comment by tycho01** [comment]
for visibility to others finding this thread in an attempt to pull off recursion, see @fightingcat's [trick](https://github.com/Microsoft/TypeScript/pull/24897#issuecomment-401423920) to get the compiler to overlook the recursion.

**Comment by aleksey-bykov** [comment]
@tycho01 can you share a minimal example of how recursion in types can be done?

**Comment by aleksey-bykov** [comment]
might be relevant: #8517

**Comment by tycho01** [comment]
@aleksey-bykov the trick was pretty old, not unlike the recursion I'd been using.
His code on the actual recursive type there:

```
type Concat_<RA extends any[], B extends any[]> = {
    1: Reverse<RA>,
    0: Concat_<Unshift<RA, Head<B>>, Tail<B>>,
}[B extends [] ? 1 : 0];
```

The idea is basically to ensure the recursive call is wrapped such that it cannot immediately evaluate the whole thing and complain about the recursion.

This is done by wrapping the call into an object type (traditionally in the form `{ 0: ..., 1: ... }`), which you then navigate using a condition it is unable to simplify out right away (here using conditional types: `B extends [] ? 1 : 0`).

What this solves is the issue you run into when trying this the easy way, e.g. `type Rec<T> = T extends ... ? ... : Rec<...>;`, which has the recursive call at the top level, which it'll try to evaluate right away, and therefore trigger an error.

**Comment by zabracks** [comment]
Thanks @fightingcat and @tycho01! 

Did... did the type system just become Turing-complete? I was thinking that recursive dependent types were the last thing really holding it back.

**Comment by RyanCavanaugh** [comment]
Re: Turing completeness, see #14833, or some of the issues lately where people have written compilations which never stop (that we are unable to detect) 😆

**Comment by babakness** [comment]
@tycho01 The code quoted by @aleksey-bykov is brilliant and it works; but only the first time. If I change the value of one of the tuples being concatenated, TypeScript hangs. 

Also adding this function to the bottom of the concat example will hang Typescript

```ts
declare function foo<A, B>(a: A[], b: B[]): Concat<A,B>
```

Example link:

http://www.typescriptlang.org/play/#src=%0D%0Atype%20ToTuple%3CT%3E%20%3D%20T%20extends%20any%5B%5D%20%3F%20T%20%3A%20any%5B%5D%3B%0D%0A%0D%0Atype%20Head%3CTuple%20extends%20any%5B%5D%3E%20%3D%20Tuple%20extends%20%5Binfer%20H%2C%20...any%5B%5D%5D%20%3F%20H%20%3A%20never%3B%0D%0Atype%20Tail%3CTuple%20extends%20any%5B%5D%3E%20%3D%20((...t%3A%20Tuple)%20%3D%3E%20void)%20extends%20((h%3A%20any%2C%20...rest%3A%20infer%20R)%20%3D%3E%20void)%20%3F%20R%20%3A%20never%3B%0D%0Atype%20Unshift%3CTuple%20extends%20any%5B%5D%2C%20Element%3E%20%3D%20((h%3A%20Element%2C%20...t%3A%20Tuple)%20%3D%3E%20void)%20extends%20(...t%3A%20infer%20R)%20%3D%3E%20void%20%3F%20R%20%3A%20never%3B%0D%0Atype%20Push%3CTuple%20extends%20any%5B%5D%2C%20Element%2C%20R%20%3D%20Reverse%3CTuple%3E%2C%20T%20extends%20any%5B%5D%3D%20ToTuple%3CR%3E%3E%20%3D%20Reverse%3CUnshift%3CT%2C%20Element%3E%3E%3B%0D%0A%0D%0Atype%20Reverse%3CTuple%20extends%20any%5B%5D%3E%20%3D%20Reverse_%3CTuple%2C%20%5B%5D%3E%3B%0D%0Atype%20Reverse_%3CTuple%20extends%20any%5B%5D%2C%20Result%20extends%20any%5B%5D%3E%20%3D%20%7B%0D%0A%20%20%20%201%3A%20Result%2C%0D%0A%20%20%20%200%3A%20Reverse_%3CTail%3CTuple%3E%2C%20Unshift%3CResult%2C%20Head%3CTuple%3E%3E%3E%0D%0A%7D%5BTuple%20extends%20%5B%5D%20%3F%201%20%3A%200%5D%3B%0D%0A%0D%0Atype%20Concat%3CTuple1%20extends%20any%5B%5D%2C%20Tuple2%20extends%20any%5B%5D%2C%20R%20%3D%20Reverse%3CTuple1%3E%2C%20T%20extends%20any%5B%5D%3D%20ToTuple%3CR%3E%3E%20%3D%20Concat_%3CT%2C%20Tuple2%3E%3B%0D%0Atype%20Concat_%3CTuple1%20extends%20any%5B%5D%2C%20Tuple2%20extends%20any%5B%5D%3E%20%3D%20%7B%0D%0A%20%20%20%201%3A%20Reverse%3CTuple1%3E%2C%0D%0A%20%20%20%200%3A%20Concat_%3CUnshift%3CTuple1%2C%20Head%3CTuple2%3E%3E%2C%20Tail%3CTuple2%3E%3E%2C%0D%0A%7D%5BTuple2%20extends%20%5B%5D%20%3F%201%20%3A%200%5D%3B%0D%0A%0D%0Atype%20x%20%3D%20Concat%3C%5B1%2C%202%2C%203%5D%2C%20%5B4%2C%205%2C%206%5D%3E%3B%20%2F%2F%20%5B1%2C%202%2C%203%2C%204%2C%205%2C%206%5D%0D%0Atype%20y%20%3D%20Concat%3C%5B1%2C%202%2C%203%2C%204%5D%2C%20%5B5%2C%206%2C%207%5D%3E%3B%20%2F%2F%20%5B1%2C%202%2C%203%2C%204%2C%205%2C%206%5D%0D%0A%0D%0Adeclare%20function%20foo%3CA%2C%20B%3E(a%3A%20A%5B%5D%2C%20b%3A%20B%5B%5D)%3A%20Concat%3CA%2CB%3E

**Comment by bobvanderlinden** [comment]
Hmm, I think I also ran into this issue when trying to implement a type that deeply removes `| null` and `optionalField?`s from GraphQL-like structures:

```
type GraphQLObject = { '__typename': string }
type DeepRequired<T> = NonNullable<
  T extends Array<infer TItem>
    ? Array<DeepRequired<TItem>>
    : T extends GraphQLObject
      ? Required<{ [TKey in keyof T]: DeepRequired<T[TKey]> }>
      : T
>
```

The hack mentioned earlier will not work for me (or I haven't figured it out yet), because I need to infer `TItem`.

**Comment by skreborn** [comment]
@bobvanderlinden Would the following satisfy your requirements?

```typescript
type GraphQLObject = { '__typename': string }

type DeepRequired<T> = T extends GraphQLObject ?
    Required<{ [TKey in keyof T]: DeepRequiredObject<T[TKey]> }> :
    (T extends Array<infer TItem> ? DeepRequiredArray<TItem> : DeepRequiredObject<T>);

interface DeepRequiredArray<T> extends Array<DeepRequired<T>> {}

type DeepRequiredObject<T> = {
    readonly [K in keyof T]: DeepRequired<T[K]>;
}
```

It seems to be producing the correct result in a simple case, but I'm unsure if it works in all required scenarios as I haven't yet used GraphQL myself.

```typescript
interface Result {
    data: {
        search: [
            {
                __typename: string,
                name: string | null
            }
        ]
    }
}

const result: DeepRequired<Result> = {
    data: {
        search: [
            {
                __typename: "Human",
                name: "Han Solo"
            },
            {
                __typename: "Human",
                name: "Leia Organa"
            },
            {
                __typename: "Starship",
                name: "TIE Advanced x1"
            }
        ]
    }
};

result.data.search[0].name; // string
```

**Comment by bobvanderlinden** [comment]
@skreborn Wow, thanks for that one 😁👍. It's still a bit confusing why this variant does work, but directly inlining `DeepRequiredObject` and `DeepRequiredArray` doesn't. Is such a solution considered a workaround for this issue? Or am I just doing something fundamentally wrong in my type definition?

**Comment by skreborn** [comment]
@bobvanderlinden This is, as far as I know, the only workaround for now. Inlining them doesn't work because circular referencing is not allowed. So why is it allowed if you put an extra step between the two? It's black magic that might have something to do with lazy evaluation, but it's definitely beyond my knowledge on the internal workings of the type system.

**Comment by babakness** [comment]
You can sort of induce lazy evaluation by using the following pattern

```ts
type DeepUnnest<P extends any[]> = {
  'more': P extends Array<infer U>
    ?  U extends any[]
       ? DeepUnnest<U>
       : never
    : never
  'end': P extends Array<infer U>
    ? U
    : never,
}[
  P extends Array<infer U>
   ? U extends any[]
     ? 'more'
     : 'end'
   : 'end'
]
```
Its ugly but it works avoiding circular reference problems.

**Comment by pronebird** [comment]
I found that cyclic references work very well with nested objects

```ts
class Node<T> {}

type ExtractType<T> =
    T extends SchemaNode<infer S>
        ? S extends { [name: string]: SchemaNode<infer _> } 
            ? { [K in keyof S]: ExtractType<S[K]> }
            : S extends Array<infer E> 
                ? any[]
                : S           
    : T;
```
But as soon as I add an `Array` into the mix and attempt to type it, the whole thing breaks, i.e:

```ts
class Node<T> {}

type ExtractType<T> =
    T extends SchemaNode<infer S>
        ? S extends { [name: string]: SchemaNode<infer _> } 
            ? { [K in keyof S]: ExtractType<S[K]> }
            : S extends Array<infer E> 
                ? Array<ExtractType<E>> 
                : S           
    : T;
```

Full source:

```ts
class SchemaNode<T> {
    constructor(private value: T) { }
    validate(): ExtractType<SchemaNode<T>> {
        return this.value as any; // [redacted]
    }
}

type ExtractType<T> =
    T extends SchemaNode<infer S>
        ? S extends { [name: string]: SchemaNode<infer _> } 
            ? { [K in keyof S]: ExtractType<S[K]> }
            : S extends Array<infer E> 
                ? Array<ExtractType<E>>
                : S           
    : T;

type AccountType = "retail" | "company";

const mySchema = new SchemaNode({
    account: new SchemaNode({
        token: new SchemaNode("john doe"),
        type: new SchemaNode<AccountType>("retail"),
        options: new SchemaNode({
            autoLogin: new SchemaNode(true)
        }),
        isActive: new SchemaNode(true),
    }),
    history: new SchemaNode([
        new SchemaNode("went to barber shop")
    ]),
    credits: new SchemaNode(1000)
});

const res = mySchema.validate();

(res.account.token as string);
(res.account.isActive as boolean);
(res.account.type as AccountType);
(res.account.options.autoLogin as boolean);
(res.history as string[]);
(res.credits as number);
```

**Comment by flux627** [comment]
> I think aleksey-bykov nailed the primary goal use case in this comment:
> [#6230 (comment)](https://github.com/microsoft/TypeScript/issues/6230#issuecomment-167023181)
> 
> ```ts
> type Json = null | string | number | boolean | Json[] | { [name: string]: Json }
> ```

This seems to no longer work. This is my work-around:

```typescript
type JsonPrimative = string | number | boolean | null
interface JsonMap { [member: string]: JsonPrimative | JsonArray | JsonMap }
interface JsonArray extends Array<JsonPrimative | JsonArray | JsonMap> {}
type Json = JsonPrimative | JsonMap | JsonArray
```

**Comment by kevinbeal** [comment]
I wanted to do this:

```typescript
type lineOfCode = [string, lineOfCode[], [string, void | number]];
```

But I had to do this workaround:

```typescript
type _lineOfCode = [string, unknown, [string, void | number]];
interface ILineOfCode extends _lineOfCode {
	1: ILineOfCode[];
}
```

Maybe this will help someone else.

**Comment by ahejlsberg** [comment]
With #33050 the original example can now be written as:

```
interface Bar<A> { x: A }
type Foo = Bar<Foo>
```

**Comment by kettanaito** [comment]
Thank you, @ahejlsberg, for tackling this!

Could somebody please suggest me a way to type annotate the following circular structure?

```ts
export type Schema<DataType = UnknownData> = {
  [K in keyof DataType]?: ResolverOrNestedSchema<DataType[K], DataType>
}

type ResolverPredicate<ValueType, DataType> = (
  value: ValueType,
  key: string,
  pointer: Pointer,
  data: DataType,
  schema: Schema<ValueType>,
) => boolean

type ConditionalResolver<ValueType, DataType> = [
  ResolverPredicate<ValueType, DataType>,
  ResolverOrNestedSchema<ValueType, DataType>,
]

type ResolverOrNestedSchema<ValueType, DataType> =
  | Resolver<ValueType>
  | ConditionalResolver<ValueType, DataType>
  | Schema<ValueType>

type Pointer = string[]

type Resolver<ValueType> = (
  value: ValueType,
  pointer: Pointer,
) => Record<string, boolean> | boolean
```

**Comment by amatiasq** [comment]
> ```ts
> type JsonPrimitive = string | number | boolean | null
> interface JsonMap { [member: string]: JsonPrimitive | JsonArray | JsonMap }
> interface JsonArray extends Array<JsonPrimitive | JsonArray | JsonMap> {}
> type Json = JsonPrimitive | JsonMap | JsonArray
> ```

Maybe that worked in a previous version but I'm getting this:

![Screenshot 2021-06-08 at 16 20 31](https://user-images.githubusercontent.com/1533589/121202479-9c10af00-c875-11eb-99b4-a5be873e80fc.png)

**Comment by RebeccaStevens** [comment]
Is it possible to write a tuple type that repeats a pattern?

```ts
// [A] or [A, B, A] or [A, B, A, B, A] or [A, B, A, B, A, B, A] or ...
type PatternTuple<A, B> = [A] | [A, B, ...PatternTuple<A, B>];
```

**Comment by zaydek** [comment]
This is working fine for me so far. \*crosses fingers\*

```ts
type JSONValue =
  | null
  | boolean
  | number
  | string

type JSONArray =
  | JSONValue[]
  | JSONArray[]
  | JSONMap[]

// Use interface because type errors:
//
//   type JSONMap = Record<string, JSONValue | JSONArray | JSONMap>
//   -> Type alias 'JSONMap' circularly references itself. ts(2456)
//
interface JSONMap { [key: string]: | JSONValue | JSONArray | JSONMap }
```

**Comment by gajus** [comment]
@RebeccaStevens did you ever figure this out? I asked a related question:

https://stackoverflow.com/q/75851865/368691

**Comment by RebeccaStevens** [comment]
No. The best I came up with was:

```ts
export type Alternate<A, B> =
  | [A]
  | [A, B, A]
  | [A, B, A, B, A, ...Array<A | B>];
```

**Comment by gajus** [comment]
_ah_, I missed `[]` in my question/example.

```ts
type NodeSnapshot =
  | string
  | [string, Attributes, ...NodeSnapshot]
```

The above should have been:

```ts
type NodeSnapshot =
  | string
  | [string, Attributes, ...NodeSnapshot[]]
```

The circular reference error threw me off.

Maybe it would make sense to change the error to:

```diff
- Type alias 'PlaywrightNodeSnapshot' circularly references itself.
+ Type alias 'PlaywrightNodeSnapshot' circularly references itself. Did you mean to spread NodeSnapshot[]?
```
