### ISSUE TITLE
Enums should be able to use constant values in a .d.ts

### ISSUE THREAD

**Issue by lf-** [Microsoft/TypeScript#14179]
**TypeScript Version:**  2.1.6

**Code**

```ts
declare const COLOR_RED: 1;
declare const COLOR_PURPLE: 2;
declare const COLOR_BLUE: 3;
declare const COLOR_CYAN: 4;
declare const COLOR_GREEN: 5;
declare const COLOR_YELLOW: 6;
declare const COLOR_ORANGE: 7;
declare const COLOR_BROWN: 8;
declare const COLOR_GREY: 9;
declare const COLOR_WHITE: 10;

declare enum FlagColor {
    resource = COLOR_GREEN,
    road = COLOR_BROWN,
    extension = COLOR_YELLOW,
    centralStorage = COLOR_GREY
}
```

**Expected behavior:**

Compiles

**Actual behavior:**

`error TS1066: In ambient enum declarations member initializer must be constant expression.`

-------

This doesn't make sense to me because those variables *are* constant at compile time. This code works fine in a non .d.ts without the `declare`. I guess the workaround is to just use the numbers and put some comments in as to what they mean.

**Comment by lf-** [comment]
Ambient enums don't make sense in this case.

**Comment by alvin-reyes** [comment]
Getting a similar error on my app. Posted the issue in stackoverflow

https://stackoverflow.com/questions/45498552/ambient-enum-declaration-error/45498606#45498606
