### ISSUE TITLE
`for ... in obj` where `obj: object` gives TS2407

### ISSUE THREAD

**Issue by mattpap** [Microsoft/TypeScript#14187]
**TypeScript Version:**  2.2.0

```
$ node_modules/.bin/tsc --version
Version 2.2.0
```

**Code**

```ts
let obj: object = {}

for (const attr in obj) {
  const val = obj[attr]
}
```

**Expected behavior:**

Compiles without errors.

**Actual behavior:**

```
some.ts(3,20): error TS2407: The right-hand side of a 'for...in' statement must be of type 'any', an object type or a type parameter.
```

This is a new feature, so I'm not sure if I'm using this properly, but the error message says that `an object type` is allowed, so I expect this behavior to be a bug.

**Comment by tobiasmuehl** [comment]
Try spelling `object` in uppercase: `Object`

**Comment by DanielRosenwasser** [comment]
No, `object` should be acceptable here. Looks like a bug.

**Comment by HerringtonDarkholme** [comment]
Thanks for reporting! I'm looking on it!

**Comment by kirillgroshkov** [comment]
+1

**Comment by mhegazy** [comment]
thanks @HerringtonDarkholme!

**Comment by niemyjski** [comment]
Is this in the next 2.3.0 release?

**Comment by niemyjski** [comment]
I pulled down the 2.3.0 release off nom and I'm still seeing this error.

**Comment by mhegazy** [comment]
```sh
c:\test\sandbox7>tsc --v
Version 2.3.0

c:\test\sandbox7>type a.ts
let obj: object = {}

for (const attr in obj) {
  const val = obj[attr]
}
c:\test\sandbox7>tsc a.ts

c:\test\sandbox7>echo %ERRORLEVEL%
0
```
