### ISSUE TITLE
Loop with `for ... of` over a `Map`

### ISSUE THREAD

**Issue by tiberiucorbu** [Microsoft/TypeScript#14185]
**TypeScript Version:**  2.1.6

**Code**

```ts
let entries: Map<string, string[]> = new Map<string, string[]>();
entries.set('a', ['foo'])
for (let entry of entries.values()) {
// do something with the entry
}
```

**Expected behavior:**
Since Typescript is advertised as a superset of ES6 than expected is that it should support es6 features.  Therefor `for ... of` should work properly with `IterableIterator` as described here : https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Map

**Actual behavior:**
Compilation fails

> TS2495: Type 'IterableIterator<string[]>' is not an array type or a string type.

**Comment by basarat** [comment]
The main complexity is the `emit` required for iterator support : http://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=latest%2Creact%2Cstage-2&targets=&browsers=&builtIns=false&code=let%20entries%3A%20Map%3Cstring%2C%20string%5B%5D%3E%20%3D%20new%20Map()%3B%0Aentries.set('a'%2C%20%5B'foo'%5D)%0Afor%20(let%20entry%20of%20entries.values())%20%7B%0A%2F%2F%20do%20something%20with%20the%20entry%0A%7D&experimental=false&loose=false&spec=false&playground=true 

TypeScript emitter doesn't have this support yet :rose:

**Comment by mhegazy** [comment]
This should be addressed by https://github.com/Microsoft/TypeScript/pull/12346 under `--downlevelIteration`. Make sure `es2015` or `es2015.iterable` is part of your `--lib` arguments.
