### ISSUE TITLE
Errors not propagated correctly to visual studio via webpack via msbuild

### ISSUE THREAD

**Issue by EamonNerbonne** [microsoft/TypeScript#14183]
**TypeScript Version:**  2.1.6

**Expected behavior:**
Upon error, the error is formatted such that it appears in the visual studio error list with a file name and line number.

**Actual behavior:**

Errors are assigned to file "EXEC"

**Why:**

I injected a trivial error in my project such that running `node .\node_modules\typescript\bin\tsc` fails with the following error message (first line included only):

```
ClientApp/store/ApplicationStateReducer.ts(7,14): error TS2322: Type '(state: ApplicationState, action: KnownAction) => { isLoading: boolean; account: Account; electio...' is not assignable to type 'Reducer<ApplicationState>'.
```

When typescript is run though webpack (ts-loader), this error appears as follows:

```
    ERROR in C:\vcs\ProgressElections\src\ProgressElections\ClientApp\store\ApplicationStateReducer.ts
    (7,14): error TS2322: Type '(state: ApplicationState, action: KnownAction) => { isLoading: boolean; account: Account; electio...' is not assignable to type 'Reducer<ApplicationState>'.
```

Note that the webpack error is split over lines now.

when webpack is run via an msbuild `<Exec>` task, the error is formatted as follows:

```
      ERROR in C:\vcs\ProgressElections\src\ProgressElections\ClientApp\store\ApplicationStateReducer.ts
EXEC(7,14): error TS2322: Type '(state: ApplicationState, action: KnownAction) => { isLoading: boolean; account: Account; electio...' is not assignable to type 'Reducer<ApplicationState>'. 
```
Note that msbuild uses some pattern matching to find lines with errors.  Because the line containing TS2322... no longer contains the filename, msbuild uses the name of the task instead.  The Exec task supports something called `CustomErrorRegularExpression`, but according to my experiments and [the relevant msbuild source](https://github.com/Microsoft/msbuild/blob/e5bc7994348dba88d1f6fe2ebd6aa354355f0063/src/Tasks/Exec.cs#L407) that applies line-by-line and as such cannot be used to workaround the error being split over two lines.

The end result is,  visual studio fails to display a useful error message; the error is labelled as being in the EXEC file on line 7, which is obviously not the expected behavior.

---

I'm not sure what to do about this, nor where to best fix this: Here, ts-loader, webpack, or msbuild all appear to be reasonable candidates...

**Comment by qub1n** [comment]
In my opinion Webpack (ts-loader) should not split the line. Does it solve the issue?

This issue and all related issues that MSBuild cannot recognize TypeScript errors and warnings are very sever for our company. We receive a message that "process (yarn or npm) exited with error code 1" which is not descriptive enough and you need to search in the log every time something is wrong. The log can be huge! This is blocking the CI process significantly.

**Comment by RyanCavanaugh** [comment]
We don't control how webpack emits errors

**Comment by EamonNerbonne** [comment]
So the bug is in ts-loader?
