### ISSUE TITLE
tsconfig.json extends impossible to cancel / override previous settings

### ISSUE THREAD

**Issue by pocesar** [Microsoft/TypeScript#14184]
**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)

**Code**

```json
// tsconfig.json
{
   "compilerOptions": {
     "outFile": "dist/app.js"
   }
}
// extends.json
{
   "extends": "./tsconfig.json",
   "compilerOptions": {
       "outFile": null,
       "outDir": "mapped"
   }
}
```

**Expected behavior:**

Be able to "cancel" previous outFile setting by setting the "outFile" to null in the extended version

**Actual behavior:**

error TS5024: Compiler option 'outFile' requires a value of type string.

if outFile is set to `""`, it tries to write to `.` giving a ESDIR error in Node

**Comment by pocesar** [comment]
ok, it seems that it needs to be the otherway around, the base minimum in a `base.json` and then `"extends": "base.json"` inside `tsconfig.json` and `vendor.json` with only the settings not defined in `base.json`

**Comment by mhegazy** [comment]
We have a few reports for this already in #16838 and #17357, we should fix this.
