### ISSUE TITLE
Default value of field pulled from object via destructuring isn't being checked if it's of proper type. 

### ISSUE THREAD

**Issue by pietmichal** [Microsoft/TypeScript#14193]
**TypeScript Version:**  2.1.6

**Code**

```ts

interface ITest {
    example?: string;
}

const foo = ({example = 123}: ITest) => console.log(example) // No error

function bar({example = 123}: ITest) { // No error
    console.log(example);
}

const { example = 123 }: ITest = { };  // No error

foo({});
bar({});

```

**Expected behavior:**
TypeScript showing an error saying that `123` isn't of type `string`.

**Actual behavior:**
TypeScript shows no error.

**Comment by mhegazy** [comment]
The type of the initializer is unioned with that of the destructed property. so the type here is `string | 123`.
