### ISSUE TITLE
EventTarget.removeEventListener's second argument is incorrectly optional

### ISSUE THREAD

**Issue by Jessidhia** [microsoft/TypeScript#14196]
**TypeScript Version:**  2.2.0

**Code**

```ts
// this throws at runtime due to the missing second argument,
// but it typechecks as the second argument is marked optional
document.createElement('div').removeEventListener('onclick')
```

**Expected behavior:**
Compile error due to missing second argument

**Actual behavior:**
Runtime error due to missing second argument

The runtime error is possibly engine-specific; however, not supplying the second argument still makes it a meaningless invocation, as it would attempt remove the event listener callback that is `=== undefined`, which is not possible.

**Comment by HolgerJeromin** [comment]
ref https://github.com/Microsoft/TSJS-lib-generator/issues/174

**Comment by mhegazy** [comment]
It is not clear why the [spec](https://dom.spec.whatwg.org/#ref-for-dom-eventtarget-removeeventlistener%E2%91%A0) makes it optional, but the explanation later on for what `removeEventListener` does, it does not mention anything about callback being undefined.

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by yukulele** [comment]
Is `[EventTarget.removeEventListener](url)` also affected?

**Comment by HolgerJeromin** [comment]
both 
`document.createElement('div').removeEventListener('onclick')`
`document.createElement('div').addEventListener('onclick')`
fails with:
> Expected 2-3 arguments, but got 1.

We should close this issue.

**Comment by jakebailey** [comment]
Just looking at old issues; this is indeed fixed, yeah.
