### ISSUE TITLE
Why interface for function is not working same for returning void and other basic types in typescript

### ISSUE THREAD

**Issue by bunnyvishal6** [Microsoft/TypeScript#14192]
```ts
//case 1
interface Lol {
    (s: string): void;
}
let meow: Lol = a => {
    return a;
};
console.log(meow('a'));
//***************************

//case 2
interface Lol2 {
    (s: string): string;
}
let meow2: Lol2 = a => {
    return a.length;
}
console.log(meow2('a'));
//*************************

//case 3
interface Lol3 {
    (s: string): number;
}
let meow3: Lol3 = a => {
    return a;
}

```

**Expected behavior:**
Should highlight meow in case1 as error like meow2 and meow3 in case2 and case 3 by the typescript intelliSense in typescript playground. 
**Actual behavior:**
Not highlighting meow as error in case1 in typescript playground. 

here is typescript playground url: https://www.typescriptlang.org/play/index.html#src=%2F%2Fcase%201%0D%0Ainterface%20Lol%20%7B%0D%0A%20%20%20%20(s%3A%20string)%3A%20void%3B%0D%0A%7D%0D%0Alet%20meow%3A%20Lol%20%3D%20a%20%3D%3E%20%7B%0D%0A%20%20%20%20return%20a%3B%0D%0A%7D%3B%0D%0Aconsole.log(meow('a'))%3B%0D%0A%2F%2F***************************%0D%0A%0D%0A%2F%2Fcase%202%0D%0Ainterface%20Lol2%20%7B%0D%0A%20%20%20%20(s%3A%20string)%3A%20string%3B%0D%0A%7D%0D%0Alet%20meow2%3A%20Lol2%20%3D%20a%20%3D%3E%20%7B%0D%0A%20%20%20%20return%20a.length%3B%0D%0A%7D%0D%0Aconsole.log(meow2('a'))%3B%0D%0A%2F%2F*************************%0D%0A%0D%0A%2F%2Fcase%203%0D%0Ainterface%20Lol3%20%7B%0D%0A%20%20%20%20(s%3A%20string)%3A%20number%3B%0D%0A%7D%0D%0Alet%20meow3%3A%20Lol3%20%3D%20a%20%3D%3E%20%7B%0D%0A%20%20%20%20return%20a%3B%0D%0A%7D%0D%0A

**Comment by DanielRosenwasser** [comment]
This behavior's often been a bit surprising for me as well, but you can read more about it [in our FAQ](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-functions-returning-non-void-assignable-to-function-returning-void)
