### ISSUE TITLE
Decorator should able to remap the method type

### ISSUE THREAD

**Issue by aight8** [Microsoft/TypeScript#14199]
I tried to override the method type definition, but the **MyClass.prototype.set** method's return type is still hinted as ```{ var: number }``` - see the example below!

I tried with some other variation (PropertyDescriptor etc.) but it seems this function is really not available.

# This is the full use-case:

I narrowed the code a little bit but I post more than just the minimum to demonstrate how powerful this function could be. It's a library I write for the redux ecosystem. Because the nice structure of methods and decorators I really try to stick on this kind of strategy - and hope this could be possible soon and create awesome new library architectures.

```JS
class ActionInterface {
    constructor(
        public readonly action: Action,
        private dispatchFunction: Dispatch<Action>,
        private objectTarget: any
    ) {

    }

    dispatch() {
        this.dispatchFunction.call(this.objectTarget, this.objectTarget, this.action);
    }
}

const actionType = (actionType: string) => {
   return (
        target: Object,
        key: string,
        attributes: TypedPropertyDescriptor<Function>
    ): TypedPropertyDescriptor<ActionInterfaceCreator> {
        const originalMethod = attributes.value;
        return {
            value: function(...args: any[]) {
                const payload = originalMethod(...args);
                return new ActionInterface({type: "bla"}, () => {}, this);
            },
            writable: false,
            enumerable: true,
            configurable: true,
        }
    }
}

class MyClass {
    @action('USER/SET')
    set(n: number) {
        return { var: 123 };
    }
}

let my = new MyClass();
my.set(235);
```

**I currently don't see any reason this should not be possible because every attached decorators provide a TypedPropertyDescriptor as return value which can be static analysed in the row. The last decorator which modify the property descriptor attributes is the final type which is used for validation and autocompletion.**

The documentation write this should be possible theoretically.
https://www.typescriptlang.org/docs/handbook/decorators.html#method-decorators

> A Method Decorator is declared just before a method declaration. The decorator is applied to the Property Descriptor for the method, and can be used to observe, **modify, or replace a method definition**. A method decorator cannot be used in a declaration file, on an overload, or in any other ambient context (such as in a declare class).

**Comment by mhegazy** [comment]
Should be covered by https://github.com/Microsoft/TypeScript/issues/4881

**Comment by aight8** [comment]
Okey I read trough that it's really the same. A question, is this function in the near pipeline to modify the value types?

Generic question maybe someone could say some words to it for this small use case:
```JS
// impl. class ActionInterface
// dec wrap the method which returns a ActionInterface object

class ActionInterface {
   
}

class Abc {
   @dec('bla')
   test(id: number) {
       return { id: id };
    }
}

let abc = new Abc();
(abc.test(123) as any as ActionInterface).dispatch();
```

The **as any as ActionInterface** is currently my workaround. (note: I cannot define the **test** method return type on the method to ActionInterface logically since the methods return type don't match it then).
Other experiments: I experimented to create a sub object on the Abc class with **keyof** but since It returns automatically all keys and cannot filtered, it's not temporary solution neither.
Is this currently the only workaround?

**Comment by beary** [comment]
Agree. 
Like [Python's decorator](https://docs.python.org/3/glossary.html#term-decorator), its powerful and easy to use.
