### ISSUE TITLE
Type aliases impossible to use with `declaration: true`

### ISSUE THREAD

**Issue by s-panferov** [Microsoft/TypeScript#14198]
It's not a bug, I believe, but it's an ergonomic issue.

**TypeScript Version:**  2.1.6

**Code**

**state.ts**:
```
export interface State {
  field: number
}
```

**alias.ts**:
```
import { State } from './state.ts'
import { Dispatch as ReduxDispatch } from 'redux'

export type Dispatch = ReduxDispatch<State>
```

**actions.ts**
```
import { Dispatch } from './alias'

export function action() {
  return (dispatch: Dispatch) => { return; }
}
```

**Expected behavior:**

No errors. When I compile the example with `declaration: true`, it should generate:

**actions.d.ts**
```
import { Dispatch } from './alias'
export function action(): (dispatch: Dispatch) => void
```

**Actual behavior:**

**Error**
```
Return type of exported function has or is using name 'Dispatch' from external module "./node_modules/redux/index" but cannot be named.
```
____
The problem here is that I can't use the type alias to simplify my code, I should operate only with "origin" library types. I see an ergonomic issue here, because I should repeat myself and avoid useful type aliases.

**Comment by mhegazy** [comment]
Should be fixed in latest.
