### ISSUE TITLE
Suggestion: Conditional catch clauses

### ISSUE THREAD

**Issue by Shnatsel** [Microsoft/TypeScript#14191]
I have a rather lengthy function that calls other smaller functions which can fail for a specific reason. The failures are expected to occur at runtime and be handled. First thing I've written was this:

```
my_func() {
    let first_action_succeeded = do_something();
    if (first_action_succeeded) {
        let second_action_succeeded = do_something_else();
        if (second_action_succeeded) {
            return true;
        } else {
            return false;
        }
    }
}

wrapper_func() {
    if ( ! my_func() ) {
        cleanup();
        show_error_message();
        return;
    }
    do_stuff();
}
```
This looks like a prime use case for exceptions, so I made the functions that can fail throw exceptions, and the code got much cleaner:

```
my_func() {
    do_something();
    do_something_else();
}

wrapper_func() {
    try {
        my_func();
    } catch (e) {
        cleanup();
        show_error_message();
        return;
    }
    do_stuff();
}
```

But this created another problem: such a construct catches *any* errors, not only the specific error I expect. It will not fail on a RangeError or TypeError as it is supposed to. I also use a custom AssertionError that is raised on assertion failures and should crash the entire application if triggered; those will be swallowed as well.

I could work around that by re-throwing the error if it didn't match the expected one:

```
my_func() {
    do_something();
    do_something_else();
}

wrapper_func() {
    try {
        my_func();
    } catch (e) {
        if (e instanceof MyExpectedError) {
            cleanup();
            show_error_message();
            return;
        } else {
            throw e;
        }
    }
    do_stuff();
}
```

But that creates extra boilerplate at every single try-catch clause dealing with these errors and is not particularly readable. Also, since it's not an obvious construction it's easy to forget to add such clauses to a newly written function, or forget to re-throw the error and then find yourself running in circles because of completely mysterious application behavior months later.

So this is clearly a job for a preprocessor.

I'd expect the preprocessor to emit such code from the following human-readable notation:

```
my_func() {
    do_something();
    do_something_else();
}

wrapper_func() {
    try {
        my_func();
    } catch (e if instanceof MyExpectedError) {
        cleanup();
        show_error_message();
        return;
    }
    do_stuff();
}
```

Firefox [already implements this exact syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch#Conditional_catch_clauses) as a non-standard extension to JS. Moreover, Firefox can handle chained conditional catch clauses.

A similar thing has already been suggested in #13877; my proposal is distinct in that it allows writing arbitrary conditional expressions instead of just `instanceOf`, since [subclassing built-in objects like Error has poor browser support and may no longer work starting with TypeScript 2.1](https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#extending-built-ins-like-error-array-and-map-may-no-longer-work). The upside of allowing only the `instanceOf` statement is that, unlike an arbitrary conditional statement, it guarantees that the conditional expression has no side effects.

**Comment by DerFlatulator** [comment]
> it guarantees that the conditional expression has no side effects.

I'd argue that it should be up to the developer to decide that.

I'd heavily favour:

```js
try {
} catch (e=> e instanceof MyError, e) {
} catch (e => e.message === 'Access Denied', e) {
}
```

Due to increased flexibility.

Regardless, this is more of a JavaScript language proposal than a TypeScript feature request.

Interestingly, Bluebird accepts a constructor, a boolean producing function, or an object to match on:

http://bluebirdjs.com/docs/api/catch.html

**Comment by danpantry** [comment]
I think a good start would be to have TypeScript emit something desugared, rather than emit a non-standard language extension.

Using your example, I'd like to see TypeScript emit:

````tsc
wrapper_func() {
    try {
        my_func();
    } catch (e) {
        if (e instanceof MyExpectedError) {
          cleanup();
          show_error_message();
          return;
       }
       throw e;
    }
    do_stuff();
}
````

**Comment by RyanCavanaugh** [comment]
This is purely a runtime feature and should be pushed into the JS standard if it's sufficiently useful.

See also https://esdiscuss.org/topic/conditional-catch-clause

**Comment by aequasi** [comment]
What about doing something like

```
try {

} catch (error: TypeError) {

}
```

Wouldn't be something that JS standard could do
