### ISSUE TITLE
Error messages are vague when types have the same name

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#1419]
Consider the following:

```TypeScript
module ts {
    export interface Node {
        kind: SyntaxKind;
        pos: number;
        end: number;
    }
}

function f(n: Node) {
    ts.forEachChild(n, () => { /* ... */ });
}
```

The subtlety is that the user meant to declare `ts.Node` as the type of `n`.

Here you'll get the error on `n` within the `forEachChild` call, with the message

```
TS2345 Argument of type 'Node' is not assignable to parameter of type 'Node'.
```

which is unhelpful because it makes the user feel like they've completely lost their mind.

We should use a qualified name in such cases.

**Comment by NoelAbrahams** [comment]
@DanielRosenwasser /@chrisbubernak,

I ran into this gem today using 1.4:

![image](https://cloud.githubusercontent.com/assets/1106823/5874639/fade160e-a2fb-11e4-9d8b-b78e7ed34d09.png)


I mean `Types of parameters 'other' and 'other' are incompatible` might be a candidate for the error messages hall of fame? :smile:

**Comment by RyanCavanaugh** [comment]
That error looks like a bug. Do you have a repro?

**Comment by NoelAbrahams** [comment]
@RyanCavanaugh, there's only one `DomElement`. While implementing the interface there was a parameter clash with a type in `lib.d.ts`. Seems to be in the same ball park as this issue, but will take a look at producing a repro.

**Comment by DanielRosenwasser** [comment]
We're almost there; #1798 is probably the next pain-point to tackle.
