### ISSUE TITLE
Intersection Types: & operator not commutative

### ISSUE THREAD

**Issue by benjamin-hg** [Microsoft/TypeScript#14190]
**TypeScript Version:**  2.0.9

**Code**

```ts
type A = {
    get(): {
        a: number;
    };

    a: number;
}

type B = {
    get(): {
        b: string;
    }

    b: string;
}

(<A & B>(undefined)).a;  // fine
(<A & B>(undefined)).b; // fine
(<A & B>(undefined)).get().a; // fine
(<A & B>(undefined)).get().b; // error: property 'b' does not exist on type {a: number;}

(<B & A>(undefined)).a; // fine
(<B & A>(undefined)).b; // fine
(<B & A>(undefined)).get().a; // error: property 'a' does not exist on type {b: string;}
(<B & A>(undefined)).get().b; // fine
```

**Expected behavior:**
No errors, because set intersection is defined as commutative, see https://en.wikipedia.org/wiki/Algebra_of_sets 

**Actual behavior:**
Errors (see comments in code)

**Comment by DanielRosenwasser** [comment]
When it comes to overloads, there's only so much you can do. Traditionally we just give precedence to overloads from the left side of the intersection, which does make things non-commutative. For identical signatures, we can try to intersect their return types which I think we did at some point. Others on the team might remember better if that was the case.

**Comment by benjamin-hg** [comment]
> For identical signatures, we can try to intersect their return types which I think we did at some point

This is exactly what I had expected. 

Can someone please give a definition to what extend the merging is done in such cases?

In my use case, I have a main component composed of two sub components: `AConsumer` and `BConsumer`. 
`AConsumer` and `BConsumer` work an the same thing, but with a slightly different view. So `AConsumer` works with `interface A` and `BConsumer` works with `interface B`, both implemented by the same object.
To pass in this object to my main component, it needs the intersection type `A & B`.

As I think it is a good practice to define interfaces as narrow as possible (providing just the required members), I would be glad to know how to deal with the given example in TypeScript.

Best workaround I found so far:

```ts
interface A  {
    get(): {
		a: number;
    };

    a: number;
}

interface B  {
    get(): {
		b: string;
    }

    b: string;
}

interface C extends A, B { 
	get(): { // manual merging
		a: number;
		b: string;
	}
}

(<C>(undefined)).a; // fine
(<C>(undefined)).b; // fine
(<C>(undefined)).get().a; // fine
(<C>(undefined)).get().b; // fine
```
But this comes with the cost of manually extending the return value of `C#get()` whenever a property is added to either the return value of `A#get()` or `B#get()`
