### ISSUE TITLE
No error on missing properties in an interface

### ISSUE THREAD

**Issue by abenhamdine** [Microsoft/TypeScript#14203]
**TypeScript Version:**  2.2.0RC

**Code**

```ts
declare interface ITrigger {
	tableName: string,
	action: "fetch" | "add" | "remove" | "update",
	method: () => void, // NB : same results are observed whith method: Function
	fields: string[]
}

const foo1 = {
	triggers: <ITrigger[]>[{
		tableName: 'pay_contrat_cnt',
		action: 'bar', // OK : TS error on wrong action type
		fields: []
	}]
}

const foo2 = {
	triggers: <ITrigger[]>[{
		tableName: 'pay_contrat_cnt',
		action: 'add',
		// why no error on missing property method ??
		fields: ['id1', 'id2']
	}]
}

const foo3 = {
	triggers: <ITrigger[]>[{
		tableName: 'pay_contrat_cnt',
		method: () => { },
		// why no error on missing property 'action' ??
		fields: ['id1', 'id2']
	}]
}

const foo4 = {
	triggers: <ITrigger[]>[{
		tableName: 'pay_contrat_cnt',
		action: 'add',
		method: 'wrongType', // OK, TS error 'Type "string" is not comparable to type "Function"
		fields: ['id1', 'id2']
	}]
}

const foo5 = {
	triggers: <ITrigger[]>[{
		tableName: 'pay_contrat_cnt',
		action: 'add',
		// what is this magic ?? when fields is assigned with numbers (thus wrong type), now TS show error 'Property "method" is missing'
		// and where is the error on wrong fields type ??
		fields: [1, 2]
	}]
}

const foo6 = {
	triggers: <ITrigger[]>[{
		tableName: 'pay_contrat_cnt',
		action: 'add',
		method: () => { },
		fields: [1, 2] // OK, TS error on 'type Number[] is not comparable to type String[]'
	}]
}

```

**Expected behavior:**

cases foo2 and foo3 should error on missing properties (see comments)
case foo5 should error on wrong type for 'fields' property in addition to missing property 'method'

**Actual behavior:**

No errors on cases foo2 et foo3
Error on foo5 but seems (weirdly) triggered by the wrong type on property 'fields'.

**Comment by Rascaile** [comment]
To add to this, since I was just playing with something similar;

Creating an intermediate interface where you declare `triggers` as an array of `ITrigger` seems to work correctly, so the issues should be in using the `<ITrigger[]>` syntax.

    interface collection {
        triggers: ITrigger[];
    }

    const foo2: collection = {
        triggers: [{
            tableName: 'pay_contrat_cnt',
            action: 'add',
            // Property 'method' is missing in type '{ tableName: string; action: "add"; fields: string[]; }'.
            fields: ['id1', 'id2']
        }]
    }

**Comment by GeekyMonkey** [comment]
Still a problem in tsc 2.6.1

**Comment by mhegazy** [comment]
the `<ITrigger[]>` is a type assertion.. it tells the compiler trust me it is an `ITrigger[]`. 
The compiler does an extra check for type assertions to verify that one of the two is assignable to the other.. in `foo1`, `foo3` and `foo5` that is what happens, and you do not get the error.. this is the same as `<Dog>(new Animal())`. the compiler will not complain if you down-cast your way to a more specialized type..

you can read more about type assertions in http://www.typescriptlang.org/docs/handbook/basic-types.html#type-assertions

It seems what you intend here is to use a type annotation on the target of your assignment, and not cast your way through
```ts
const foo2: {triggers: ITrigger[] } = {
	triggers: [{
		tableName: 'pay_contrat_cnt',
		action: 'add',
		// why no error on missing property method ??
		fields: ['id1', 'id2']
	}]
}
```
