### ISSUE TITLE
A conditional operator literal string type problem

### ISSUE THREAD

**Issue by BirdLeeSCUT** [Microsoft/TypeScript#14204]
**TypeScript Version:**   2.1.5

There is a conditional operator literal string type problem, ts cannot resolve `true ? "a" : "b"` as a type, which may call some errors.

for example:
```ts
type a_or_b = "a" | "b" ;
let v1 = (true ? "a" : "b");
let v2: a_or_b;
v2 = v1; // ERROR
```
**Expected behavior:**
expect no error.

**Actual behavior:**
but it comes up with an error as follow:
TS2322
![image](https://cloud.githubusercontent.com/assets/10753131/23167617/113340ba-f880-11e6-8c60-7089ef84b668.png)

I know a solution to refrain this error is changing the line 2 to be  `let v1: any = (true ? "a" : "b");` or  `let v1: a_or_b  = (true ? "a" : "b");` , but this procedure seem to should be needless.

**Comment by krryan** [comment]
Try `const v1 = (true ? "a" : "b");`. Since you are using `let` you are allowing `v1` to be reassigned and the compiler assumes you want it to accept the wider range of values (`string`), but with `const` it can be narrower.

**Comment by BirdLeeSCUT** [comment]
@krryan Thanks, it works well!
