### ISSUE TITLE
Computed properties do not check for toString method

### ISSUE THREAD

**Issue by antoinerey** [Microsoft/TypeScript#14207]
**TypeScript Version:**  2.1.6

**Code**

```ts
class Action {
  toString() {
    return 'my-type'
  }
}

const action = new Action()
const handler = {
  [action]: 'my-handler',
}

console.log(handler) // Object { my-type: "my-handler" }
```

**Expected behavior:**

JavaScript calls `toString` when computing object properties.

I think that TypeScript should check if the computed property implements the `toString` method, which is called automatically in JavaScript.

**Actual behavior:**

Typescript thows : `error TS2464: A computed property name must be of type 'string', 'number', 'symbol', or 'any'`

```ts
const handler = {
  [action as any]: 'my-handler',
}
```

This works as workaround but it is far from optimal.

**Comment by syabro** [comment]
Any news here? @RyanCavanaugh 
It's bothering me when I'm using https://github.com/acdlite/redux-actions

**Comment by mhegazy** [comment]
This is the same underling request in https://github.com/Microsoft/TypeScript/issues/1415. in general all objects have toString() methods, and honoring it would hide more bugs than enable valid patterns. our recommendation is to either use `action.toString()` or cast to `any` as noted earlier.

**Comment by theGABS** [comment]
Still want! 
Maybe you allow function, but add rules to TSLint, so people who want can just 
`/* tslint:disable: rule */ ?`
