### ISSUE TITLE
No compiler error on missing return statement when using if branch 

### ISSUE THREAD

**Issue by alexpeelman** [Microsoft/TypeScript#14200]
#**TypeScript Version:**  2.1.6 

**Code**

```ts
private someFunction(): string {
    if (false) {
      return "a value"
    }

    //wrong code which does an assignment or declaration instead of returning a value
   "b value"
  }

private callerFunction(): void {
    //prints undefined
    console.log(someFunction())
}
```

**Expected behavior:**
Typescript compiler giving an error that a return statement is required for non void types.

**Actual behavior:**
Code is executed and nothing is returned, giving undefined values. 
The compiler doesn't see that a return type is missing when the if branch is skipped.

**Comment by Kovensky** [comment]
Not sure if it is necessary or not in this case, but do you have `strictNullChecks` enabled? It's possible, if you have `strictNullChecks` off, that it's allowing the branch that returns nothing because it has at least one branch that returns string (even if unreachable).

**Comment by alexpeelman** [comment]
strictNullChecks are disabled AFAIK, I don't see them in my compiler flags. But if I may nitpick, shouldn't the compiler then ignore it always ? If the return keyword is removed in the if branch the compiler gives a useful error : A function whose declared type is neither 'void' nor 'any' must return a value. I find this behaviour rather ambiguous :)

**Comment by jeffreymorlan** [comment]
`noImplicitReturns` will also give an error on a function like that

**Comment by alexpeelman** [comment]
Fair enough closing this issue. Setting the right compiler flags gives the expected behaviour.
Thx guys !
