### ISSUE TITLE
Sub generic returns wrong type

### ISSUE THREAD

**Issue by mc-petry** [Microsoft/TypeScript#14205]
**TypeScript Version:**  2.2.0 / nightly (2.3.0-dev.20170221)

**Code**

```ts
interface IAction<T> {
  value: T
}

const method = <T, P extends IAction<T>>(value: () => P): T => {
  return value().value
}

const value = method(() => ({ value: 25 }))
```

**Expected behavior:**

Variable **value** of type **number**

**Actual behavior:**

Variable **value** of type **{}**

![2017-02-21 17_20_44- library ts - redux-rb - visual studio code](https://cloud.githubusercontent.com/assets/8122711/23171236/9bd84448-f85a-11e6-9afe-75e1cf0794af.png)

**Comment by mc-petry** [comment]
Some workaround:
```ts
const method = <T, P extends IAction<T>>(value: () => P & IAction<T>): T => {
  return value().value
}
```

**Comment by mhegazy** [comment]
There is no place for the compiler to infer `T` from, and thus it gets the default inferred type `{}`. 

you can write your signature to use the type of the property `"value"` on the type parameter `P` instead:

```ts
const method = <P extends IAction<any>>(value: () => P): P["value"] => {
  return value().value
}
```
