### ISSUE TITLE
Unable pass parameter with type property type {new(): TGeneric} to another generic method

### ISSUE THREAD

**Issue by MarenkovIgor** [Microsoft/TypeScript#14201]
**TypeScript Version:**  2.1.1

**Code**

```ts
class Animal {
    numLegs: number;
}

class Lion extends Animal {
}

function testFunc<A extends Animal>(opts: { a: { new (): A } }) {
    opts = normalize(opts, { a: Lion });
}

testFunc({ a: Lion });

function normalize<T>(paramObject: T, defaults: T): T {
    return Object.assign(paramObject, defaults);
}
```
**Expected behavior:**
Compiles fine.

**Actual behavior:**
Compilation failed with message: 
Type '{ a: typeof Lion; }' is not assignable to type '{ a: new () => A; }'.
  Types of property 'a' are incompatible.
    Type 'typeof Lion' is not assignable to type 'new () => A'.
      Type 'Lion' is not assignable to type 'A'.

**Comment by mhegazy** [comment]
The function is defined as generic, with argument `A`, it can be called with a more derived type than `Lion`, yet, you are always returning a `Lion` and `Lion` doe not have to be assignable to `A`.
