### ISSUE TITLE
allowJs breaks the shebang

### ISSUE THREAD

**Issue by darkoverlordofdata** [Microsoft/TypeScript#14217]
**TypeScript Version:**  2.1.6 
**Code**

```ts
#!/usr/bin/env gjs
class Doo {}
class Scooby extends Doo {}
```

**Expected behavior:**
it should keep the shebang on the first line, and it does. Until I add javascript files, set allowJs, and target ES5. Then, it inserts the extends polyfill before the shebang line. If I change the filetype of my *.js to *.ts, it works correctly again.
**Actual behavior:**
```
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};
#!/usr/bin/env gjs
var Frodo = (function () {
    function Frodo() {
    }
    return Frodo;
}());
var Bilbo = (function (_super) {
    __extends(Bilbo, _super);
    function Bilbo() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    return Bilbo;
}(Frodo));
```

**Comment by DanielRosenwasser** [comment]
Can you check whether you're experiencing the same problem with `typescript@next`? `npm install -g typescript@next` to install it.

**Comment by yuit** [comment]
@darkoverlordofdata I can't repo the issue. I am trying to repo using setup below and typescript@next

With following javascript
```javascript
#!/usr/bin/env gjs
class Doo {}
class Scooby extends Doo {}
```
and tsconfig.json
```json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "noImplicitAny": false,
        "sourceMap": false,
        "allowJs": true,
        "outDir": "wwwroot"
    }
}
```

the output is as expected
```javascript
#!/usr/bin/env gjs
var __extends = (this && this.__extends) || (function () {
    var extendStatics = Object.setPrototypeOf ||
        ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
        function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
var Doo = (function () {
    function Doo() {
    }
    return Doo;
}());
var Scooby = (function (_super) {
    __extends(Scooby, _super);
    function Scooby() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    return Scooby;
}(Doo));
```
Could you give `typescript@next` a try? I will close this issue for now. Please feel free to reopen if it is persist.

**Comment by mhegazy** [comment]
Have you tried with --outfile

**Comment by yuit** [comment]
@mhegazy not yet....hmmm this may change the behavior

**Comment by yuit** [comment]
After investigate this issue, I can't still not repo using just `allowJS` option.

However, one thing, as pointed out by @mhegazy, using `outFile` trigger this problem. I am sure if this is what the original problem is @darkoverlordofdata let me know you also use `outFile` option or not.

**Problem**
Using `outFile` causes shebang and prologue directives to be emitted after helper

```ts
#!/usr/bin/env gjs
"use strict"
class Doo {}
class Scooby extends Doo {}
```

```js
var __extends = (this && this.__extends) || (function () {
    var extendStatics = Object.setPrototypeOf ||
        ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
        function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
#!/usr/bin/env gjs                   -> // ERROR
"use strict";                             -> // ERROR
var Doo = (function () {
    function Doo() {
    }
    return Doo;
}());
var Scooby = (function (_super) {
    __extends(Scooby, _super);
    function Scooby() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    return Scooby;
}(Doo));
var x = 2000;
function foo() { }
```
**Solution**
We have to move how we emit both shebang and prologue directives to be before emit helper
- Shebang
Emit the first shebang we encounter. To be clear If there are different shebang in the file, emitter will still just emit the first shebang.

- Prologue directives
Emit "use strict" follow by other prologue directive. We will check if we have emit this string literal prologue directives before and will omit if that is the case. This is not applicable with custom prologue directive (such as "this" capturing)

**Comment by darkoverlordofdata** [comment]
Since upgrading to version 2.2.1, I'm no longer having an issue with this!
