### ISSUE TITLE
`jake baseline-accept` does not update project,transpile baselines

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/TypeScript#14213]
**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)

**Repro**
```
git checkout 7b58be779b8dbf8bbf6d7f28cfcc4444ccee08b6
jake runtests-parallel
jake baseline-accept
jake runtests-parallel
```
Observe that the baselines for project, transpile are not updated by `jake baseline-accept`.

To see the changes needed to correctly update the baselines, run
```
git diff 7b58be779b8dbf8bbf6d7f28cfcc4444ccee08b6  b0d916bd994f667ab6b6c3c9c885da3a161f490f
```

**Comment by mhegazy** [comment]
Should be fixd now.
