### ISSUE TITLE
Decorator metadata is order-dependent at runtime

### ISSUE THREAD

**Issue by thesbros** [Microsoft/TypeScript#14218]
**TypeScript Version:**  2.1.6 / nightly (2.3.0-dev.20170221)

**Code**

```ts
import "reflect-metadata";

function test(t, k)
{
	console.log(Reflect.getMetadata("design:paramtypes", t, k));
}

class ScenesStore
{
	@test
	addScene(scene: Scene)
	{

	}
}

class Scene
{
	name = "Scene";
}
```

**Expected behavior:**

"[ Scene ]" is printed to the console.

**Actual behavior:**

"[ undefined ]" is printed to the console.

Moving `Scene` above `ScenesStore` causes the correct value to be printed.

**Comment by alexey-pelykh** [comment]
In my case, things are a bit more complicated:
```
import {dbModel, dbTable, dbColumn} from '../helpers/mapping';

@dbTable('documents')
export class DocumentModel {
    @dbColumn(DocumentModel.Columns.ID)
    public documentId?: number = null;
}

export namespace DocumentModel {
    export namespace Columns {
        export const ID = 'id';
    }
    export type ColumnsType = 'id';
}
```

gives:

```
    @dbColumn(DocumentModel.Columns.ID)
                                   ^
TypeError: Cannot read property 'ID' of undefined
```

and it's impossible to move namespace above the class

**Comment by alexey-pelykh** [comment]
As a workaround I use deferred values as
```
@dbColumn(() => DocumentModel.Columns.ID)
```

**Comment by aluanhaddad** [comment]
@alexey-pelykh you could make them static members as that is effectively what the `namespace` is doing, then the order would not matter.

**Comment by aluanhaddad** [comment]
```ts
export class DocumentModel {
    @dbColumn(DocumentModel.Columns.ID)
    public documentId?: number = null;

    static readonly Columns = Object.freeze({ ID = 'id' as 'id' });
    static readonly ColumnsType = 'id';
}
```

**Comment by alexey-pelykh** [comment]
@aluanhaddad thanks, I was unaware of such a workaround. Yet it gives
```
Cannot find name 'ID'. (2304)
```
on ```Object.freeze()``` line

**Comment by alexey-pelykh** [comment]
@aluanhaddad yet I suspect I just miss something due to limited knowledge of both TypeScript and JavaScript =)

**Comment by mhegazy** [comment]
Decorators and metadata emit capture the JS value. it happens here that when class `ScenesStore` is being declared (and decorated), `Scene` is not defined yet. so the value of `Scene` is undefined. moving the class declaration higher would address the issue.

**Comment by ulrichb** [comment]
This answer is dissatisfying. What about class A uses class B + B uses A? Further the feedback is really bad. No compile error, just a undefined value of `design:type` at runtime. 

=> IMO this is a bug and the constructor for `design:type` must be returned lazily/set later.
