### ISSUE TITLE
tsc -m system: a module with no exports doesn't generate a system module

### ISSUE THREAD

**Issue by nahuel** [Microsoft/TypeScript#14220]
Given these files:

```ts
// a.ts: 
const a = 1

// b.ts:
export const b = 1
```

If you run `tsc -m system a.ts` and `tsc -m system b.ts` you get:

```js
// a.js:
var a = 1;

// b.js:
System.register([], function (exports_1, context_1) {
    "use strict";
    var __moduleName = context_1 && context_1.id;
    var b;
    return {
        setters: [],
        execute: function () {
            exports_1("b", b = 1);
        }
    };
});
```

So, a file with no exports (or imports) doesn't generate a system module. I don't think this is right, but if this is not a bug but the expected behavior, what's the rationale?

**TypeScript Version:**  Version 2.3.0-dev.20170221

**Comment by DanielRosenwasser** [comment]
This is working as intended, though I agree that it is extremely frustrating - the idea is that there are some cases where you'd like to have global code along with your modules (for instance, any calls to `System.config`.

You can get around this with an `export {};`
