### ISSUE TITLE
TS2345 error:  Bug with document example variable destructuring (or bug with TS?)

### ISSUE THREAD

**Issue by momoadeli** [Microsoft/TypeScript#14228]
BUGS: With either documentation or Typescript.

**TypeScript Version:**  2.1.6

**Actual behavior:**
[simple playground example](https://www.typescriptlang.org/play/index.html#src=let%20input%20%3D%20%5B1%2C%202%5D%3B%0D%0Alet%20%5Bfirst%2C%20second%5D%20%3D%20input%3B%0D%0Aconsole.log(first)%3B%20%2F%2F%20outputs%201%0D%0Aconsole.log(second)%3B%20%2F%2F%20outputs%202%0D%0A%0D%0Afunction%20f(%5Bfirst%2C%20second%5D%3A%20%5Bnumber%2C%20number%5D)%20%7B%0D%0A%20%20%20%20console.log(first)%3B%0D%0A%20%20%20%20console.log(second)%3B%0D%0A%7D%0D%0Af(input)%3B) copied from docs 'destructuring' segment in 'Variable Declarations'

f(input) has a TS2345 error/warning

**Expected behavior:**
No warnings for f(input). Perhaps doc should be updated to add tuple type as such:
`let input:[number,number] = [1, 2];`

**Comment by mhegazy** [comment]
Tuple types are only inferred in the presence of a contextual type. as you noted.

The example in the documentation needs to be updated. PRs are welcomed.
