### ISSUE TITLE
DocumentFragment interface doesn't inherit NodeSelector and ParentNode interfaces

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#14223]
For example, DocumentFragment doesn't have children property as standard apis yet. Edge doesn't actually have that api.

https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment
https://dom.spec.whatwg.org/#documentfragment

**TypeScript Version:**  master

**Expected behavior:**

```ts
interface DocumentFragment extends Node {
}
```

**Actual behavior:**

```ts
interface DocumentFragment extends Node, NodeSelector, ParentNode {
}
```

**Comment by falsandtru** [comment]
ping @DanielRosenwasser @mhegazy

**Comment by mhegazy** [comment]
looks like MDN says it has properties but the spec does say that.

**Comment by falsandtru** [comment]
> the spec does say that.

where?

MDN says they are **experimental** apis. In fact, `Array.from(document.createDocumentFragment().children)` **causes an error on Edge** even through it can compile. If you are right, Edge isn't following the spec.

**Comment by mhegazy** [comment]
QuerySeletor and querySelectorAll are not experimental, but there are not in the spec. Does chrome supports them at least?

**Comment by falsandtru** [comment]
I think so. I recommend to define those methods again within DocumentFragment interface (I need to update my pr).

**Comment by falsandtru** [comment]
updated. see https://github.com/Microsoft/TSJS-lib-generator/issues/199 @mhegazy

**Comment by falsandtru** [comment]
Hey @mhegazy @DanielRosenwasser Don't you fix this?

**Comment by falsandtru** [comment]
See https://github.com/Microsoft/TSJS-lib-generator/issues/199
