### ISSUE TITLE
docCommentTemplate Should Provide JSDoc Template Parameters

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#14221]
**Code**
```ts
|
class List<T> {
    
}
```

Trigger `docCommentTemplate` request against TSServer where `|` is.

**Expected behavior:**
A comment like: 

```ts
/**
 * @template T
 */
```

is returned

**Actual behavior:**
An empty comment is returned:

```ts
/**
 * 
 */
```

**Comment by mhegazy** [comment]
In a .ts file, generic types already have a way to be represented. `@template` seems to be superfluous in that context.
