### ISSUE TITLE
there appears to be a newline issue with the currrent release

### ISSUE THREAD

**Issue by tedrob** [Microsoft/TypeScript#14225]
there appears to be a bug with the newline property?

Module build failed: TypeError: Cannot read property 'newLine' of undefined
typescript\lib\typescript.js:9426:20)
typescript.js:62475:26)

**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)

**Code**

```ts
// A *self-contained* demonstration of the problem follows...

```

**Expected behavior:**

**Actual behavior:**

**Comment by mhegazy** [comment]
Can you share a self-contained repro? also a version number?

**Comment by tedrob** [comment]
ERROR in ./src/main.ts
Module build failed: TypeError: Cannot read property 'newLine' of undefined
    at Object.getNewLineCharacter (C:\aaa-angular2\angular2cli\foo\node_modules\typescript\lib\typescript.js:8062:20)

it appears to be in version 2.0.0/2.2.1

**Comment by mhegazy** [comment]
can you share your ` ./src/main.ts` and/or your tsconfig.json?

**Comment by mhegazy** [comment]
```sh
c:\test>tsc --v
Version 2.2.1

c:\test>type a.ts
var x = 0;

c:\test>tsc a.ts --newLine lf

c:\test>type a.js
var x = 0;

c:\test>tsc a.ts --newLine crlf

c:\test>type a.js
var x = 0;
```

**Comment by tedrob** [comment]
this has been fixed with the lastest version of typescript installed in node_modules

**Comment by mhegazy** [comment]
Thanks
