### ISSUE TITLE
lib.d.ts: DOMImplementation.createDocument does not follow specification

### ISSUE THREAD

**Issue by bobappleyard** [Microsoft/TypeScript#14229]
The declaration of [DOMImplementation in lib.d.ts](https://github.com/Microsoft/TypeScript/blob/master/lib/lib.d.ts#L6632) includes the method:

    createDocument(namespaceURI: string | null, qualifiedName: string | null, doctype: DocumentType): Document;

However, according to the [DOM Specification](https://www.w3.org/TR/DOM-Level-2-Core/core.html#ID-102161490) the doctype parameter can be `null`. This accords with almost every use of this method that I have ever seen in JavaScript code.

**Comment by bobappleyard** [comment]
I assume I should place this issue with the TSJS-lib-generator. Sorry.

**Comment by bobappleyard** [comment]
So TSJS-lib-generator says to raise the issue here.

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by bondz** [comment]
Microsoft/TSJS-lib-generator#205 should fix this
