### ISSUE TITLE
Using Type Parameters in Generic Constraints - type check failure

### ISSUE THREAD

**Issue by ccodin** [microsoft/TypeScript#14226]
**TypeScript Version:**  2.1.6
Hi,
I was following the sweet features "Generics" on the official website, but it looks like type check failed at some point. 
(I did not have this failure on version 2.0.9, but maybe generics was not implemented yet ?)

**Code**

```ts
copyFields<T extends U, U>(target: T, source: U): T {
        for (let id in source) {
            target[id] = source[id];
        }
        return target;
    }
// compiler output :
// 'Type 'U[keyof U]' is not assignable to type 'T[keyof U]'.
// Type 'U' is not assignable to type 'T'.'
```

**Expected behavior:**
No error thrown
**Actual behavior:**
Error output : 'Type 'U[keyof U]' is not assignable to type 'T[keyof U]'.

Since it's just a copy/paste of the official doc, I assume there is a little problem here =)

**Comment by RyanCavanaugh** [comment]
This is a correct error; it would be unsound since `T` is a subtype of `U` thus might have more-specific property types at any given key.
