### ISSUE TITLE
Can't assign to readonly property in constructor using an alias for "this"

### ISSUE THREAD

**Issue by richard-gebbia** [Microsoft/TypeScript#14241]
**TypeScript Version:**  2.1.4

**Code**

```ts
class Foo {
    readonly bar: number;

    constructor() {
        const that = this;
        that.bar = 3;
    }
}

```

**Expected behavior:** Should be able to assign to `that.bar` in the constructor.

**Actual behavior:** Error: Cannot assign to 'bar' because it is a constant or a read-only property. 

If `that` is changed to `this`, it will compile.

The use case here is that we would like to minify the ES3/ES5 output, but most minifiers won't shorten the `this` keyword due to its nature in JS. We have a convention where we assign `this` to a different variable, which will get minified, and use that one instead.

**Comment by mhegazy** [comment]
This seems correct to me. if accessing readonly is allowed on non-this values no guarantees that you are not modifying other instances (i.e. different from eh one being created).

**Comment by snood1205** [comment]
I don't see why this is correct. It has long been a thing in JS to do something like `var self = this;`, so I don't see why TS should disallow this for `readonly` properties.

**Comment by richard-gebbia** [comment]
It would make sense to allow the assignment if the alias was explicitly declared `const x = this`. I can certainly understand disallowing `let` and `var` declarations, since there's no guarantee that the variable would be pointing to `this` at the time of assignment, but that's not the case with `const`. 

Also, this is a common pattern in OO JS codebases whose authors are concerned with payload size. I can't imagine I'm the first to run into this issue.

**Comment by nicervan** [comment]
I also don't see why this would be considered correct. From the TypeScript handbook: 
> Readonly properties must be initialized at their declaration or in the constructor.

As long as this done in the constructor, I don't see why a const alias to `this` would not be treated the same as `this`.
