### ISSUE TITLE
Should 'Partial<T>' and Readonly<T> should have their type parameters constrained to 'object'?

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#14249]
Given #14224, I think that `Partial` should be defined as follows:

```ts
type Partial<T extends object> = {
    [K in keyof T]?: T[K]
}
```

`Readonly` could be defined similarly.

I don't necessarily know if `Pick` should be defined that way. Part of me thinks that this `Pick` has a different intent.

**Comment by mhegazy** [comment]
mapped type in general handle primitives differently. but i agree that these types should not be used on a primitive.

the problem now is in any generic function every-time you write `Partial<T>` you have to constrain `T extends object`.

**Comment by Knagis** [comment]
I have recently used `Partial<>` like this:

```
type Foo<T> = {
  [K in keyof T]: Partial<T[K]>
}
```

Wouldn't the constraint prohibit this? Of course, I could create my own `Partial<>` definition that skips the constraint.

**Comment by RyanCavanaugh** [comment]
Too annoying to force authors to constrain their own type parameters to `object` if we did this
