### ISSUE TITLE
JSDoc generation - generate @returns when function returns a value

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#14248]
_From @egamma on February 22, 2017 11:14_

In the following generated JS Doc comment I would have expected that there is also a `@returns` comment.
 
```js
/**
 * 
 * @param {any} a
 * @param {any} b
 */
function foo(a, b) {
  return 12;
}
```

_Copied from original issue: Microsoft/vscode#21109_

**Comment by faintsignal** [comment]
This was actually supported at one point and disappeared after an update earlier this year. :(

**Comment by David-Else** [comment]
I would also like to see a @returns!

**Comment by PhoneixS** [comment]
@mhegazy  what feedback are you expecting?

This is something it should do the same way it does with `@param`. I think there is no need for the tag "Awaiting More Feedback".

**Comment by Kamadake** [comment]
recently just had a discussion about this with a colleague of mine where he noticed @returns wasn't being outputted automatically when he types `/**` inside his .ts files.

this should be adjustable in the setting.json. If a user wants it or it's mandatory for a project, let it be configureable by the editor if said team works with VSCode.

**Comment by mpf82** [comment]
Any progress on this issues?

**Comment by a-tarasyuk** [comment]
TS should add  `@return` tag for functions that contain a `return` statement. Am I right?

```ts
/**
 * 
 * @param {any} a
 * @param {any} b
 * @return {any}
 */
function foo(a, b) {
  return 12;
}
```

In the current implementation of automatic JSDoc generation, there is no type detection based on parameters usage, I suppose we need to do the same for the `@return` tag. Is it true?

/cc @mjbvz @jessetrinity @RyanCavanaugh
