### ISSUE TITLE
ParentNode interface's all methods are missing

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#14246]
NodeSelector interface is not defined by the spec. It must merge into ParentNode.

https://dom.spec.whatwg.org/#parentnode

**TypeScript Version:**  master

**Code**

https://github.com/Microsoft/TypeScript/blob/master/src/lib/dom.generated.d.ts#L13721-L13725
https://github.com/Microsoft/TypeScript/blob/master/src/lib/dom.generated.d.ts#L14097-L14102

**Comment by mhegazy** [comment]
I do not think they ever existed. PRs welcomed though.

**Comment by falsandtru** [comment]
@mhegazy TSJS-lib-generator lacks the feature to fix this bug.

**Comment by falsandtru** [comment]
@mhegazy Are you really accept this? Seems like you changed your mind in https://github.com/Microsoft/TSJS-lib-generator/issues/199

**Comment by mhegazy** [comment]
your right. thanks.

**Comment by falsandtru** [comment]
Seems like we misunderstood the specs. MDN also updated own document after opening this issue https://developer.mozilla.org/en-US/docs/Web/API/ParentNode$history. I refined my pr. Can you review it again?

https://github.com/Microsoft/TSJS-lib-generator/pull/234

ParentNode: https://dom.spec.whatwg.org/#parentnode
NodeSelector: https://www.w3.org/TR/selectors-api/#interface-definitions
