### ISSUE TITLE
Inheriting constructor through extends clause with a wrapped type argument does not work

### ISSUE THREAD

**Issue by JsonFreeman** [Microsoft/TypeScript#1424]
The following code should compile just fine, but there is an error when doesNotWork tries to pass `this` to the constructor for CBase.

```ts
class C<T1> extends CBase<T1> {
    public works() {
        new CBaseBase<Wrapper<T1>>(this);
    }
    public doesNotWork() {
        new CBase<T1>(this);
    }

    public method(t: Wrapper<T1>) { }
}

class CBase<T2> extends CBaseBase<Wrapper<T2>> {

}

class CBaseBase<T3> {
    constructor(x: Parameter<T3>) { }
}

class Parameter<T4> {
    method(t: T4) { }
}

class Wrapper<T5> {
    property: T5;
}
```

**Comment by DanielRosenwasser** [comment]
Slightly more minimal (or at least clearer to me)

```
class Parameter<T4> {
    method(t: T4) { }
}

class Wrapper<T5> {
    property: T5;
}

class A<T3> {
    constructor(x: Parameter<T3>) { }
}

class B<T2> extends A<Wrapper<T2>> {

}

class C<T1> extends B<T1> {
}

var x: C<number>;
new A(x);
new B(x);
```

**Comment by RyanCavanaugh** [comment]
Re [Breaking Change] -- when did this last work? It's an error in 0.9, 1.0, 1.1, and 1.3.

**Comment by JsonFreeman** [comment]
@DanielRosenwasser, I do not understand your example. How could those constructor calls work, if the constructor takes a `Parameter`? `C<number>` is not a `Parameter` because it is missing `method`.

@RyanCavanaugh, I did not realize that. There was a user on 1.0, and they claimed to hit it on upgrade to 1.4 directly from 1.0.

**Comment by DanielRosenwasser** [comment]
Ah, disregard my comment.

**Comment by RyanCavanaugh** [comment]
Might be a more specific repro required to not error in 1.0. Removing tag for now.
