### ISSUE TITLE
jsdoc autocomplete should prefer {Object} over {any} in JavaScript

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#14242]
_From @Tyriar on February 22, 2017 18:9_

#21031

`any` is a TypeScript concept, `Object` is the most generic type in JavaScript which is more meaningful to non-TS devs:

![image](https://cloud.githubusercontent.com/assets/2193314/23225467/d8eb67e8-f8e6-11e6-9008-ee314dbebb0c.png)

_Copied from original issue: Microsoft/vscode#21179_

**Comment by DanielRosenwasser** [comment]
I would think that if anything you'd want `*`, not `Object`.

**Comment by Tyriar** [comment]
Yes that would be better :+1: http://usejsdoc.org/tags-param.html#multiple-types-and-repeatable-parameters
