### ISSUE TITLE
Fix DefinitelyTyped type definitions before publishing a new version

### ISSUE THREAD

**Issue by tkrotoff** [microsoft/TypeScript#14256]
Problem:
Each TypeScript release breaks popular DefinitelyTyped type definitions, example with TypeScript 2.2 release:
- whatwg-fetch and isomorphic-fetch broken: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/14765
- lodash broken: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/14324
- probably others

Not a good developer experience

Solution:
Fix the most popular DefinitelyTyped type definitions before publishing on npm

**Comment by corbinu** [comment]
Given the issue with loads at least was that the change would break older versions of TS. Maybe if there was some sort of @next option for DefinitelyTyped that way at least we call you have updated to that version of the definition when the RC has launched. That would have made things a little easier at least.

**Comment by jaredmahan** [comment]
When can we expect isomorphic-fetch type fixes to be deployed? Waiting on this currently...

**Comment by mhegazy** [comment]
` @types/isomorphic-fetch@0.0.33` is already out and should have the fix.

**Comment by mhegazy** [comment]
For lodash, the change https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14662 needs to be updated and then we can merge it.

**Comment by mhegazy** [comment]
As for the original request, we used to validate against every drop of the compiler but as the size of DT grew it became harder to do that. 
I agree We should be running the validation on all DT packages at least once before every release. @andy-ms is updating the testing system to make this doable.

**Comment by weswigham** [comment]
We do this regularly now, thanks to the `@typescript-bot run dt` command (not just before publish, but regularly before merge), in addition to nightly testing of DT vs the nightly TS. 😄
