### ISSUE TITLE
TSServer navTree Returns Inconsistent locations for exported const function

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#14251]
Follow up on #13336
**TypeScript Version:**  2.2.1

**Code**

```ts
export const x = 2

export const y = () => 2
```

**Bug**
For a `navTree` request on this document, the starting location of the symbol is inconsistent:

```json
 {
            "text": "x",
            "kind": "const",
            "kindModifiers": "export",
            "spans": [
                {
                    "start": {
                        "line": 1,
                        "offset": 14
                    },
                    "end": {
                        "line": 1,
                        "offset": 19
                    }
                }
            ]
        },
        {
            "text": "y",
            "kind": "function",
            "kindModifiers": "export",
            "spans": [
                {
                    "start": {
                        "line": 3,
                        "offset": 18
                    },
                    "end": {
                        "line": 3,
                        "offset": 25
                    }
                }
            ]
        },
```

Both `x` and `y` should have the same offset, but `x` has an offset of 14 which correctly marks the start of the `x = 2` expression, while `y` has an offset of `18` which starts at `() => 2`

**Comment by johnnyreilly** [comment]
I've been meaning to raise this as a bug for ages and discovered this was already tracked.  

My own scenario is well described by [this issue](https://github.com/Microsoft/vscode/issues/30212).  Roughly speaking: in VS Code exported const arrow functions have 0 references with code lens whilst exported functions do.

FWIW I have known teams to actually change their coding style to accomodate this.  It'd be super lovely if this was looked at. Much :heart: as ever :wink:
