### ISSUE TITLE
Contextual type does not flow into a super call if it is based on a type argument to the base class

### ISSUE THREAD

**Issue by JsonFreeman** [Microsoft/TypeScript#1425]
If you extend a generic class and pass a type argument, the instantiated constructor of the base class fails to contextually type the argument of a super call. This works correctly for base class methods, and it works correctly for constructors if the contextual type is not based on a type argument that was passed in the extends clause.

```ts
class C extends CBase<string> {
    constructor() {
        // Does not work
        super({
            method(p) { p.length; } // Error
        });

        // Works
        super.foo({
            method(p) { p.length; }
        });
    }
}

class CBase<T>  {
    constructor(param: ContextualType<T>) { } // Works if you change this to ContextualType<string>
    foo(param: ContextualType<T>) { }
}

interface ContextualType<T2> {
    method(parameter: T2): void;
}
```

**Comment by DanielRosenwasser** [comment]
Seems possibly related to #1480.

**Comment by DanielRosenwasser** [comment]
I think this should be fixed in #1425.

**Comment by DanielRosenwasser** [comment]
Also, is this really a breaking change?

**Comment by JsonFreeman** [comment]
Yeah it is a breaking change in 1.1 because the old compiler did not have this bug.
