### ISSUE TITLE
[Salsa] Function parameters type guessed by use of function (tern like)

### ISSUE THREAD

**Issue by angelozerr** [microsoft/TypeScript#14255]
tern.js is able to guess function parameters according the use of the function.

Takes a sample:

```js
function add(a, b) {
  	return a + b;
}
```

At this step, `a` and `b` parameters type cannot be guessed.

The user add this content:

```js
add(1, 1);
```

So now `a` and `b` parameters of the function can be guessed (number parameter) and you can have completion for number methods for a and b.

```js
function add(a, b) {
        a. // here Ctrl+Spaces shows number methods.
  	return a + b;
}
```

The user add this content:

```js
add("", 1);
```

Now `a` has `string `and `number `types.

I tell me if Salsa could support this case?

**Comment by RyanCavanaugh** [comment]
This is the "infer from usage" quickfix that is now available.
