### ISSUE TITLE
Support `getSymbolAtLocation` for builtin symbols

### ISSUE THREAD

**Issue by andy-hanson** [Microsoft/TypeScript#14257]
**TypeScript Version:**  nightly (2.3.0-dev.20170222)

**Code**

```ts
interface I {
    method(): void;
    [Symbol.iterator](): void;
}
```

**Expected behavior:**

At each member, `checker.getSymbolAtLocation(member.name)` is defined.

**Actual behavior:**

It's `undefined` for `Symbol.iterator`.

**Comment by mhegazy** [comment]
I think it should be working now. Please reopen if not.
