### ISSUE TITLE
object type does not work with in operator

### ISSUE THREAD

**Issue by EliSnow** [Microsoft/TypeScript#14269]
**TypeScript Version:**  2.2.1

**Code**

```ts
const b = "foo" in <object> {};
```

**Expected behavior:**
The `in` operator works

**Actual behavior:**
A compile error is provided:
`The right-hand side of an 'in' expression must be of type 'any', an object type or a type parameter`

**Comment by axefrog** [comment]
Just experienced the same issue:

```ts
export function isIterable<T>(value: object): value is Iterable<T> {
  return Symbol.iterator in value;
}
```

![image](https://cloud.githubusercontent.com/assets/298883/24518564/ca03a2d0-15c5-11e7-81a1-43045476dff0.png)
