### ISSUE TITLE
Add a `noEmitResolved` compiler option.

### ISSUE THREAD

**Issue by JHawkley** [Microsoft/TypeScript#14266]
### Problem
At present, TypeScript emits the JavaScript for all modules that are brought into a TypeScript module via an `import` statement, even when those files are not explicitly specified for inclusion by the command line or tsconfig.

The `noResolve` compiler option provides a means of blocking these modules from being resolved; this results in TypeScript completely ignoring the module's existence and raising a "module not found" error.

There is currently no option (that I've found after several hours of research) that allows TypeScript to use a module import for type-checking purposes and then not emit a compiled JS file for that module, when that module's source file wasn't explicitly included for compilation.

This has become problematic for me, trying to create separate build steps for my core program and its test suite.  I build my core program first, then I build its tests separately (the reason for this is that I have additional build steps that manipulate both of these outputs).  The tests, naturally, import parts of my program to test, which results in those parts of the program being compiled and emitted a second time by the compiler.  Since my specs are compiled into a different directory from the main program, I end up with duplicates of my main program scattered around.

I simply do not have any way to tell TypeScript that I know best; to trust that I'm providing it all the files I need and emit only what I ask it to.  I can certainly see how this "automatic inclusion" feature can be very helpful and nice to have, but there are the few odd scenarios where the TypeScript compiler is being just a little TOO helpful.

### Proposal
I would like to propose a compiler option to allow the TypeScript compiler to emit only explicitly included files, the `noEmitResolved` option.

When set, this flag tells TypeScript to resolve and use module imports for type-checking purposes, but only emit their compiled JavaScript if the module's source file:
1. Was explicitly provided to the compiler via the command line.
2. Was explicitly included in the `files` list in the tsconfig.
3. Does not match an `exclude` glob in the tsconfig.
4. Matches an `include` glob in the tsconfig.

This flag acts as a good companion to the `noResolve` flag; where `noResolve` controls whether a module that wasn't explicitly included is resolved at all, `noEmitResolved` controls whether such a module should be added to the list of files to ultimately emit when the compiler finishes its work.

**Comment by mhegazy** [comment]
If you have two build steps already, why not point the compiler to your generated .d.ts files from the first build instead of re-parsing, and re-checking the sources again?

**Comment by JHawkley** [comment]
I considered doing that and may still do that, but it'd require refactoring a lot of my modules.  Running with the `generated` option isn't something I've been doing, as there hadn't been a need up until now.  And even then, this "need" is somewhat contrived.  The source files provide type information as well as any definition file; their use may just slow compilation down a little, but it beats me having to spend time to reconfigure my entire build pipeline to satisfy the TypeScript compiler's idiosyncrasies.

Anyways, this suggestion is helpful in my example circumstance, but there are still many other cases where a user might only want to see the compiled output of a single source file, or only those files they specifically list, and TypeScript's compiler will not accommodate.

There is no good reason to force this "automatic inclusion" behavior on the user when they do not want it.  Let's have an option to turn it off.
