### ISSUE TITLE
Compile error in lib.dom.d.ts with Typescript 2.2.1

### ISSUE THREAD

**Issue by Kesshi** [Microsoft/TypeScript#14261]
**TypeScript Version:**  2.2.1

I updated to typescript 2.2.1 (from 2.1.6). I get the following error now if i build my project:

node_modules/typescript/lib/lib.dom.d.ts(1380,11): error TS2320: Interface 'AudioContext' cannot simultaneously extend types 'AudioContextBase' and 'EventTarget'.
      Named property 'addEventListener' of types 'AudioContextBase' and 'EventTarget' are not identical.

Here is the minimal set of compiler options to reproduce this issue:
"compilerOptions": {
    "target": "es5",
    "lib": ["es2015", "dom"]
 }

**Comment by MichalCafe** [comment]
There are similar issues with `lib.es6.d.ts`.

**Comment by mhegazy** [comment]
Do you have `AudioContextBase` and `EventTarget` defined some where else in your project? do you have an `@types` package that defines them?

**Comment by Kesshi** [comment]
Thank you i found the problem. Its beause of the BabylonJs library i'm using. They define AudioContext again here: https://github.com/BabylonJS/Babylon.js/blob/master/src/babylon.mixins.ts#L44
Without that definition i can compile my project. I will report a bug at BabylonJs.

**Comment by deltakosh** [comment]
It is now fixed in Babylon.js dev branch
