### ISSUE TITLE
Improve resolveModule for loading TypeScript 2.2 Plugin

### ISSUE THREAD

**Issue by angelozerr** [microsoft/TypeScript#14260]
TypeScript 2.2 Plugin must be stored in the same `node_modules` folder than the parent directory of the `tsconfig.json` .  There are 2 limitations with that:

 - if you have several tsconfig.json in your project, it means that you must have a `node_modules/$ts-plugin` per `tsconfig.json`

  * node_modules
    * ts-plugin
  * tsconfig.json
  * src    
    * node_modules
      * ts-plugin
    * tsconfig.json

- if you have several project, you cannnot share your `ts-plugin`

IMHO, I think resolveModule  should be improved to search ts-plugin inside `node_modules`:

- of the root of the project (the working directory of the tsserver)

  * node_modules
    * ts-plugin
  * tsconfig.json
  * src    
    * tsconfig.json
 
 - of the TypeScript (tsserver) 

  * node_modules
    * typescript (bin/tsserver)
    * ts-plugin

**Comment by RyanCavanaugh** [comment]
This doesn't seem to have affected anyone else
