### ISSUE TITLE
Instanceof in type guards should not narrow any

### ISSUE THREAD

**Issue by JsonFreeman** [microsoft/TypeScript#1426]
Usually narrowing a type causes us to have access to more properties. Not so if the original type was any. In this case, narrowing actually causes us to _lose_ properties. So we should not get an error in the following case:

``` ts
var x: any = { p: 0 };
if (x instanceof Object) {
    x.p; // Error that p does not exist on Object
}
```

**Comment by basarat** [comment]
`any` is evil
