### ISSUE TITLE
Map should not be accepted as Object

### ISSUE THREAD

**Issue by FLWrd** [Microsoft/TypeScript#14263]
**TypeScript Version:**  2.1.6 

**Code**

    let m = new Map<string, string>();

    if ("a" in m) {
        console.log("yes");
    }

**Expected behavior:**
An error message saying m does not have the correct type for this operation.

**Actual behavior:**
Compiler accepts it.

**Comment by mhegazy** [comment]
`Map` is an `Object`, it just happens to be one with no enumrable properties. It is not any different from `{}` in that regard. 
![image](https://cloud.githubusercontent.com/assets/8000722/23272900/d5d7be0a-f9b1-11e6-9afc-ac0502e60eed.png)

I would say a lint rule would be a more applicable place for this check.

**Comment by FLWrd** [comment]
Almost everything is an Object. But in Javascript! TypeScript was created to check types. There's no point in checking if some attribute is in a Map or an Array. If you want to test if an attribute is in a Map anyway, you can always cast it with <any>, I say.

**Comment by mhegazy** [comment]
I do not think we can pick and chose which types are "safe" to add properties to and which are not.
