### ISSUE TITLE
@types results throw errors in Typescript Virtual Project build

### ISSUE THREAD

**Issue by kimballjohnson** [Microsoft/TypeScript#14262]
**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)

This is happening in Visual Studio Enterprise v3 using an existing, traditional ASP.NET 4 MVC 5 project type. This is not ASP.NET Core, not an angular project, not an SPA, and does not use node except for npm support.

```
    "types": [
    "chai",
    "mocha",
    "mocha-phantomjs",
    "sinon-chai",
    "chai-as-promised",
    "phantomjs",
    "sinon",
    "sinon-chai",
    "jquery",
    "yuazl",
    "extend"
  ],
```
```
  "devDependencies": {
    "@types/chai": ">=3.4.0",
    "@types/chai-as-promised": ">=0.0.29",
    "@types/mocha": ">=2.2.0",
    "@types/mocha-phantomjs": ">=3.4.0",
    "@types/sinon": ">=1.0.0",
    "@types/sinon-chai": ">=2.7.0"
  },
  "dependencies": {
    "@types/jquery": ">=2.0.4",
    "jquery": ">=2.0.4",
    "phantomjs": ">=2.1.7"
  }
```

Building the project produces a properly constructed node_modules

**Expected behavior:**
No errors.
**Actual behavior:**
205 VS Build errors of the type:
Error TS2688	Cannot find type definition file for 'yauzl'. TypeScript Virtual Projects 1 Active
Error TS2688	Cannot find type definition file for 'extend'. TypeScript Virtual Projects 1 Active

I don't understand why the Typescript Virtual Project would be looking at these dependent js libraries at all. They are not directly referenced in any of the Typescript-specific configurations. I did add the first two that are listed in the build errors to the types: section of the tsconfig just for sanity, but clearly the error process is not looking at tsconfig.

**Comment by mhegazy** [comment]
is there `node_modules/@types/yauzl` on disk?

**Comment by kimballjohnson** [comment]
Yes, those libraries exist.
The issue has been solved. My tsconfig.json contained the following:
"typeRoots": [ "node_modules/@types/", "node_modules"]
When I removed "node_modules" the problem went away, which was instructive as to the way the typeroots settings values are used. The settings as initially set were the default recommendation in the documentation I discovered.l
Sorry...

**Comment by kimballjohnson** [comment]
I'm closing this.
