### ISSUE TITLE
Array.from in ES2015 should return instance of a subclass

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#14270]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from

> In ES2015, the class syntax allows for sub-classing of both built-in and user defined classes; as a result, static methods such as Array.from are "inherited" by subclasses of Array and create new instances of the subclass, not Array.

```json
{ "compilerOptions": { "target": "ES2015" } }
```

```typescript
class A {
    public static from(): A { return new A(); }
}

class B extends A { }

const value = B.from(); // expected value to be B, actual value is A
```

**Comment by Kovensky** [comment]
Note, that in your code snippet, the actual value there _is_ A. Unless `from` is overridden, it will always return a new `A`.

`Array.from` also will always return an `Array`, but if you have a `class Foo extends Array {}`, `Foo.from([])` will return a new `Foo`. However, `Foo` _isa_ `Array`, so the type definition is still not invalid, just not precise enough for `Array` subclassing.

**Comment by mhegazy** [comment]
> `// expected value to be B, actual value is A`

not sure how this would be true at runtime.

**Comment by aleksey-bykov** [comment]
check it in your favorite browser:

![image](https://cloud.githubusercontent.com/assets/937933/25600717/35844756-2eb4-11e7-9b26-b7687a7c02f9.png)

**Comment by aleksey-bykov** [comment]
![image](https://cloud.githubusercontent.com/assets/937933/25600781/ad0fb396-2eb4-11e7-9a2e-cca3d8f2d348.png)

**Comment by Kovensky** [comment]
It's not possible to give a type to these functions that will be automatically 100% accurate unless you declare the overrides yourself.

```ts
class X extends Promise  {}
// what's the type of x?
const x = new X(resolve => resolve()).then(() => {})

Object.defineProperty(X, Symbol.species, { configurable: true, value: Promise })
// what's the type of y?
const y = x.then(() => {})
```

**Comment by DanielRosenwasser** [comment]
@aleksey-bykov I think you're conflating [the behavior of `Array.from`](https://tc39.github.io/ecma262/#sec-array.from) with the behavior of static subclassing.

In any case ,what you might want is this:

```ts
class C {
    static from<T>(this: new () => T): T {
        return new this()
    }
}

const c: C = C.from();

class D extends C { }

const d: D = D.from();

console.log(d instanceof C);
console.log(d instanceof D);
```

So @Kovensky, I don't know if it's true that you have to provide the overwrites yourself - *however*, if you wanted `C` and `D` to be generic, you'd need parameterized type parameters (i.e. higher order kinds) which we don't have.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
