### ISSUE TITLE
Can't import submodules from lodash-es

### ISSUE THREAD

**Issue by screendriver** [Microsoft/TypeScript#14271]
**TypeScript Version:**  2.2.1

**Code**

```ts
import { random } from 'lodash-es/number/random';
```

**Expected behavior:**

Make use of the `random()` function.

**Actual behavior:**

`Module not found: Error: Can't resolve 'lodash-es/number/random'`

If I make a `import random from 'lodash-es/random';` it works :thinking: 

The source code of `lodash-es/number.js` looks like:

```js
export { default as clamp } from './clamp.js';
export { default as inRange } from './inRange.js';
export { default as random } from './random.js';
export { default } from './number.default.js';
```

Could it be that this syntax is not support by TypeScript and therefore can't be imported?

**Comment by mhegazy** [comment]
I think you mean `import { random } from 'lodash-es/number';`

**Comment by screendriver** [comment]
Oh, sorry. My bad! 😕  Yesterday I read something that webpack 2 does not tree shake as expected  and found a sample that looks like `import { chunk } from 'lodash-es/array/chunk'`

I blindly copy pasted that and rewrote it to `random.`

Thank you for your help @mhegazy
