### ISSUE TITLE
'in' expression should be a type guard

### ISSUE THREAD

**Issue by JsonFreeman** [Microsoft/TypeScript#1427]
The in operator provides an opportunity for us to narrow a type. There are two ways that this could work:

1. We can select particular constituents of a union type based on which members are present:
```ts
interface I1 {
    p: string;
}
interface I2 {
    q: string;
}

var v: I1 | I2;
if ("p" in v) {
    v.p; // Error
}
```

2. If we have a general type like Object, we can clone the type and add a specific property to it when narrowing:
```ts
var v: Object;
if ("p" in v) {
    v.p; // Type should be { p: any }
}
```

**Comment by awerlang** [comment]
Today we would have:

```cs
interface I1 {
    prop1: string;
    doSomething(): string;
}
interface I2 {
    prop2: string;
    doAnotherThing(): string;
}
class MyObject implements I2 {
    prop1: string = "";
    prop2: string = "";
    doAnotherThing() {
		return 'doAnotherThing';
	}
    doSomething() {
		return 'doSomething';
	}
}
function test(obj: I1 | I2) {
    if ('prop1' in obj) {
        alert('doSomething() = ' + (<I1> obj).doSomething());
    } else {
        alert('doAnotherThing() = ' + (<I2> obj).doAnotherThing());
    }
}

test(new MyObject);
```

As there's no type guard, I just type cast. I believe having 'in' as type guard is no more dangerous than a typecast. It's even a little better, perharps .

**Comment by mhegazy** [comment]
closing in favor of https://github.com/Microsoft/TypeScript/issues/10485
