### ISSUE TITLE
[Salsa] Type completions not available for @param annotations

### ISSUE THREAD

**Issue by Kovensky** [Microsoft/TypeScript#14285]
**TypeScript Version:**  2.2.0

**Code**

```js
/**
 * @param {|} bar
 * @returns {}
 */
function foo(bar) {}
```

**Expected behavior:**
Requesting a completion inside the `{}` after `@param` should return type name completion

**Actual behavior:**
No suggestions besides text suggestions are available.

Note that suggestions do work inside the `{}` after `@returns`.

**Comment by andy-ms** [comment]
We don't do this for regular types either.

![screenshot](https://cloud.githubusercontent.com/assets/19274678/26501920/c730f106-41ef-11e7-919b-20fc67bf869a.jpg)

There's a comment in `completions.ts` saying `/// TODO filter meaning based on the current context`.

**Comment by mhegazy** [comment]
@sheetalkamat  this looks related to your change to filter completions based on location. we probably should filter completions in a jsdoc comment between `{}` to types and namespaces only.
