### ISSUE TITLE
Path Suggestions include  Excluded Folders and Files 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#14283]
From https://github.com/Microsoft/vscode/issues/20557

**TypeScript Version:**  2.2.1

```json
{
    "exclude": [
        "node_modules"
    ]
}
```

```ts
import * as  x from './|'
```

Request `completions` from TSServer at the `|`

**Expected behavior:**
No folder suggestion for `node_modules` is returned since the folder has been explicitly excluded

**Actual behavior:**
An entry for `node_modules` is included in the results

**Comment by RyanCavanaugh** [comment]
This is the intended behavior; `exclude` is just a filter on `include` and doesn't prevent those files from entering the compilation via `import`
