### ISSUE TITLE
Bug: ES6-style exports counted as `private` when building with `declaration` flag.

### ISSUE THREAD

**Issue by JHawkley** [microsoft/TypeScript#14281]
**TypeScript Version:**  2.2.1

**Code**
```ts
type SomeData = { name: string, values: Array<SomeContainer> };

class SomeContainer {
  data: SomeData;
}

export { SomeData, SomeContainer };
export default SomeContainer;
```

**Expected behavior:**
This program should build when compiled with the `declaration` compiler option enabled.

**Actual behavior:**
TypeScript provides the error:
`error TS4081: Exported type alias 'SomeData' has or is using private name 'SomeContainer'.`

This error occurs even though all these types are being exported and are, therefore, not private.

**Workaround:**
The error is resolved with the following workaround:
```ts
export type SomeData = { name: string, values: Array<SomeContainer> };

export class SomeContainer {
  data: SomeData;
}

export default SomeContainer;
```

While this workaround is fine for this simple example, if your module's code is of a large class with many helper types defined, it's usually cleaner in that case to place exports at the end of the file as a known, standardized location to see all of the module's exports at a glance.  The ES6 export syntax works wonderfully for this.

Issue #12983 might be related; seems like TypeScript may treat ES6 exports differently from TypeScript-style exports, and this bug is born from that.

**Comment by Andarist** [comment]
This one doesn't occur anymore, cc @jakebailey
