### ISSUE TITLE
Bug: Class extending & incompatible methods

### ISSUE THREAD

**Issue by alexcorvi** [Microsoft/TypeScript#14288]
**TypeScript Version:**  2.1.1

**Code** ([playground link](http://www.typescriptlang.org/play/#src=interface%20Details%20%7B%20%0D%0A%20%20%20%20name%3A%20%22Alex%22%20%7C%20%22Dan%22%2C%0D%0A%20%20%20%20age%3Anumber%0D%0A%7D%0D%0A%0D%0Aclass%20A%20%7B%0D%0A%20%20%20%20method()%3A%20Details%20%7B%20%0D%0A%20%20%20%20%20%20%20%20return%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20name%3A%20%22Alex%22%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20age%3A30%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aclass%20B%20extends%20A%20%7B%0D%0A%20%20%20%20method()%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20name%3A%20%22Alex%22%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20age%3A50%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%7D%0D%0A%7D))

```ts
interface Details { 
    name: "Alex" | "Dan",
    age:number
}

class A {
    method(): Details { 
        return {
            name: "Alex", // this doesn't fire any error
            age:30
        }
    }
}

class B extends A {
    method() {
        return {
            name: "Alex", // this fires an error
            age:50
        }
    }
}
```

**Expected behavior:**

No compilation errors

**Actual behavior:**

An error that says:

> Class 'B' incorrectly extends base class 'A'.
  Types of property 'method' are incompatible.
    Type '() => { name: string; age: number; }' is not assignable to type '() => Details'.
      Type '{ name: string; age: number; }' is not assignable to type 'Details'.
        Types of property 'name' are incompatible.
          Type 'string' is not assignable to type '"Alex" | "Dan"'.

But `method` in class B _is_ returning an object that is compatible with the declared interface an the error doesn't show up on class A `method`.

**Comment by alexcorvi** [comment]
Adding the `Details` interface as a declaration for the return type in the class B method does solve the issue.

```ts
interface Details { 
    name: "Alex" | "Dan",
    age:number
}

class A {
    method(): Details { 
        return {
            name: "Alex",
            age:30
        }
    }
}

class B extends A {
    method(): Details {
        return {
            name: "Alex",
            age:50
        }
    }
}
```

However, I don't have to add a declaration for the `method()` in class `B` since the class `B` is extending another class (`B`) where the method has a return declaration.

**Comment by mhegazy** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/1373

Related discussion in https://github.com/Microsoft/TypeScript/pull/6118 and https://github.com/Microsoft/TypeScript/issues/10570
