### ISSUE TITLE
Inconsistent behaviour of Pick<T, keyof T> for readonly attributes.

### ISSUE THREAD

**Issue by fahrradflucht** [microsoft/TypeScript#14295]
**TypeScript Version:**  2.2.1

**Code**
[Typescript Playground](https://www.typescriptlang.org/play/index.html#src=%2F%2F%20This%20fails%3A%0D%0A%0D%0Ainterface%20TestA%20%7B%0D%0A%20%20%20%20readonly%20foo%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Atype%20MutableTestA%20%3D%20Pick%3CTestA%2C%20keyof%20TestA%3E%0D%0A%0D%0Aconst%20a%3A%20MutableTestA%20%3D%20%7B%0D%0A%20%20%20%20foo%3A%20'bar'%0D%0A%7D%0D%0A%0D%0Aa.foo%20%3D%20'baz'%3B%0D%0A%0D%0A%2F%2F%20This%20works%3A%0D%0A%0D%0Ainterface%20TestB%20%7B%0D%0A%20%20%20%20readonly%20%5Bkey%3A%20string%5D%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Atype%20MutableTestB%20%3D%20Pick%3CTestB%2C%20keyof%20TestB%3E%0D%0A%0D%0Aconst%20b%3A%20MutableTestB%20%3D%20%7B%0D%0A%20%20%20%20foo%3A%20'bar'%0D%0A%7D%0D%0A%0D%0Ab%5B'foo'%5D%20%3D%20'baz'%3B%0D%0A%0D%0A%2F%2F%20WAT%3A%0D%0A%0D%0Aconst%20b2%3A%20TestB%20%3D%20%7B%0D%0A%20%20%20%20foo%3A%20'bar'%0D%0A%7D%0D%0A%0D%0A%2F%2F%20expected%20error%3A%0D%0Ab2%5B'foo'%5D%20%3D%20'baz'%3B%0D%0A%0D%0A%2F%2F%20should%20error%20but%20doesn't%3A%0D%0Ab2.foo%20%3D%20'baz'%3B%0D%0A)

```ts
// This fails:

interface TestA {
    readonly foo: string;
}

type MutableTestA = Pick<TestA, keyof TestA>

const a: MutableTestA = {
    foo: 'bar'
}

a.foo = 'baz';

// This works:

interface TestB {
    readonly [key: string]: string;
}

type MutableTestB = Pick<TestB, keyof TestB>

const b: MutableTestB = {
    foo: 'bar'
}

b['foo'] = 'baz';
```

In Typescript `2.1.4` you could use `Pick<>` to remove the `readonly` modifier from all attributes of an interface `T` by calling `Pick<T, keyof T>`. From 2.1.5 this (mostly) doesn't work anymore. "Mostly" because it does still work for readonly index signatures.

**Expected behavior:**
I personally would prefer if there would be some way to make an object mutable analog to `Readonly<>`but at least the behaviour should be consistent.

**Actual behavior:**
The behaviour is inconsistent.

---

**Edit:**

I bisected this and it seems like 33b512548e8fcfc5cd0046eab33023a1bc7d7b0e that types propagate modifiers when using `Pick<T, K>` which suggests that the behaviour of the index signature example is the bug.

**Comment by r00ger** [comment]
Seems like there is no way to reset readonly modifier which is not very convenient 
```ts
const foo = {
    bar: "baz",
}
const readonlyFoo = Object.freeze(foo);
const writableFoo = { ...readonlyFoo };
writableFoo.bar = 1;
            ~~~  [ts] Cannot assign to 'bar' because it is a constant or a read-only property.

```

**Comment by r00ger** [comment]
@RyanCavanaugh will you please take a look at the problem? If I understand correctly it is an issue

**Comment by mhegazy** [comment]
@r00ger your issue with spread is a different issue, please see https://github.com/Microsoft/TypeScript/issues/14058.

The fix for the issue in the OP is to make the resulting string indexer inherit `readonly` (as well as nationality) in a homomorphic mapped type, just like it does with named properties.

**Comment by jcalz** [comment]
So, this is still a bug, right?  But instead of there being no way to remove modifiers (which was [addressed](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#improved-control-over-mapped-type-modifiers) in TS2.8), there is now no way to *preserve* the `readonly` modifier on an index signature when you map over it.  Should that be filed as a separate bug and have this one closed, or should it live on here?

**Comment by unicornware** [comment]
@RyanCavanaugh 

> there is now no way to preserve the readonly modifier on an index signature when you map over it. Should that be filed as a separate bug and have this one closed, or should it live on here?

i'm facing this issue as well. should this be filed as a separate bug?
