### ISSUE TITLE
keyof enum behavior

### ISSUE THREAD

**Issue by npenin** [Microsoft/TypeScript#14294]
**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)

**Code**

```ts
public enum MyEnum
{
A=1,
B=2,
C=3
}

public type MyEnumKeys=keyof MyEnum;
```

**Expected behavior:**
MyEnumKeys would contain "A" | "B" | "C"

**Actual behavior:**
MyEnumKeys contains  "toString" | "toFixed" | "toExponential" | "toPrecision" | "valueOf" | "toLocaleString"

**Comment by ahejlsberg** [comment]
This is working as intended. You need to use `keyof typeof MyEnum` to get `'A' | 'B' | 'C'`.

**Comment by bcherny** [comment]
@ahejlsberg How do you suggest getting the values back? Today, this doesn't seem to work:

```ts
enum A {
  One = "one",
  Two = "two"
}

type Key = keyof typeof A  // "One" | "Two"
type Val = (typeof A)[Key]

let a: Val = "one" // Error: Type '"one"' is not assignable to type 'A'.
```

[Playground link](https://www.typescriptlang.org/play/#src=enum%20A%20%7B%0D%0A%20%20One%20%3D%20%22one%22%2C%0D%0A%20%20Two%20%3D%20%22two%22%0D%0A%7D%0D%0A%0D%0Atype%20Key%20%3D%20keyof%20typeof%20A%20%20%2F%2F%20%22One%22%20%7C%20%22Two%22%0D%0Atype%20Val%20%3D%20(typeof%20A)%5BKey%5D%0D%0A%0D%0Alet%20a%3A%20Val%20%3D%20%22one%22%20%2F%2F%20Error%3A%20Type%20'%22one%22'%20is%20not%20assignable%20to%20type%20'A'.%0D%0A)

I am happy to file a separate issue for this.

**Comment by mhegazy** [comment]
the enum type is a tagged version of the string literal type. so the error you are getting is what i would expect.

**Comment by bcherny** [comment]
@mhegazy I can use keyof to get an interface's keys, and T[keyof T] to get its values. I can also use keyof to get an enum's keys, but is there a way to get the values?

**Comment by mhegazy** [comment]
`(typeof A)[keyof A]` is just `A` which is just `A.One | A.Two`.

`A.One` is a subtype of `"one"`, and is assignable to it, but not the other way around. `A.One` is a spacial `"one"` a tagged `"one"` if you may.

**Comment by bcherny** [comment]
@mhegazy Makes sense. Thanks for the explanation.
