### ISSUE TITLE
typscript continues not to ignore node_modules even when specified

### ISSUE THREAD

**Issue by xtianus79** [Microsoft/TypeScript#14293]
**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)
2.2.1

**Code**

```ts
{
    "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true,
    "strictNullChecks": true
    },
    "exclude": [
        "node_modules",
        "**/*.spec.ts"
    ]
}

```

**Expected behavior:**
to ignore node_modules

**Actual behavior:**

doesn't ignore node modules

````
webpack: Compiled successfully.
[at-loader] node_modules/@angular/compiler/src/aot/static_reflector.d.ts:8:49 
    TS2422: A class may only implement another class or interface. 

[at-loader] node_modules/@angular/core/src/util/decorators.d.ts:11:5 
    TS2411: Property 'extends' of type 'Type<any> | undefined' is not assignable to string index type 'Function | any[] | Type<any>'. 

[at-loader] node_modules/@angular/forms/src/model.d.ts:168:20 
    TS2459: Type '{ onlySelf?: boolean | undefined; } | undefined' has no property 'onlySelf' and no string index signature. 

[at-loader] node_modules/@angular/forms/src/model.d.ts:178:22 
    TS2459: Type '{ onlySelf?: boolean | undefined; } | undefined' has no property 'onlySelf' and no string index signature. 
````

**Comment by alhugone** [comment]
Hi,

Use --skipLibCheck option.

**Comment by ikokostya** [comment]
`exclude` option specifies a list of files to be excluded from compilation.

From http://www.typescriptlang.org/docs/handbook/tsconfig-json.html

> By default all visible “@types” packages are included in your compilation.

If you want ignore all declarations from `node_modules`, add the empty `types` option to `tsconfig.json`:

```
{
   "compilerOptions": {
       "types" : []
   }
}
```

**Comment by KostyaTretyak** [comment]
Your config (above) should be in root of your project. If it is, may be in your code is explicit import from `node_modules`:

```ts
import { Some } from './node_modules/some';
```

**Comment by xtianus79** [comment]
@KostyaTretyak if that was the case it would only give checks for the module i was importing... this is importing all of angular for example

**Comment by KostyaTretyak** [comment]
@xtianus79, your configuration is at the root of the project and you run tsc from this root?

**Comment by mhegazy** [comment]
Please see https://github.com/Microsoft/TypeScript/wiki/FAQ#why-is-a-file-in-the-exclude-list-still-picked-up-by-the-compiler
