### ISSUE TITLE
Readonly index signatures aren't respected with dot-notation

### ISSUE THREAD

**Issue by Fahrradflucht** [Microsoft/TypeScript#14296]
**TypeScript Version:**  2.2.1

**Code**
[Typescript Playground](https://www.typescriptlang.org/play/index.html#src=interface%20Test%20%7B%0D%0A%20%20%20%20readonly%20%5Bkey%3A%20string%5D%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Aconst%20a%3A%20Test%20%3D%20%7B%0D%0A%20%20%20%20foo%3A%20'bar'%0D%0A%7D%0D%0A%0D%0A%2F%2F%20expected%20error%3A%0D%0Aa%5B'foo'%5D%20%3D%20'baz'%3B%0D%0A%0D%0A%2F%2F%20should%20error%20but%20doesn't%3A%0D%0Aa.foo%20%3D%20'baz'%3B%0D%0A)
```ts
interface Test {
    readonly [key: string]: string;
}

const a: Test = {
    foo: 'bar'
}

// expected error:
a['foo'] = 'baz';

// should error but doesn't:
a.foo = 'baz';
```

**Expected behavior:**
Readonly index signature attributes should be read-only regardless of the way they are accessed.

**Actual behavior:**
Readonly index signature attributes are modifiable when using dot-notation.

**Comment by sandersn** [comment]
Fix is up at #17710
