### ISSUE TITLE
Error: Can't resolve all parameters for ...: when migrating from 2.0.10

### ISSUE THREAD

**Issue by acostaf** [Microsoft/TypeScript#14290]
HI All

I am moving my library from TS 2.0.10 to 2.2.1 (or 2.1.5, 2.1.6) but I keep getting and error described by 'Can't resolve all parameters for ..' so I have to roll back to 2.0.10 to fix the issue but it is stopping me from moving to TS newer version

This library it is an external library written just in TS and consumed by another project which uses TS version 2.2.1 sand angular 2.4.8

Any idea

**Comment by Davy-F** [comment]
Did you manage to fix this issue?

**Comment by mhegazy** [comment]
That is not a message that the TS compiler emits as far as i can tell. please provide a self contained reproduction of the issue.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
