### ISSUE TITLE
LINQ syntax in TS

### ISSUE THREAD

**Issue by KAHI4** [Microsoft/TypeScript#14300]
So, LINQ syntax is very powerfull feature of C#. In many case in typescript it can improve ours code.

For example (if your application based on normalized store):
**Code**
```ts
import { UserStore } from './store/users';
import { TaskStore } from './store/tasks';

/* ... */
// somewhere in render function
function getUndoneTasks(): FullTask[] {
    return TaskStore.filter(task => !task.done)
       .map(task => new FullTask(task, UserStore.find(user => user.id === task.userId));
}
```
vs 
``` ts
import { UserStore } from './store/users';
Import { TaskStore} from './store/tasks';

function getUndoneTasks(): FullTask[] {
   return from task in TaskStore from user in UserStore 
       where not task.done and user.id === task.userId
       select new FullTask(task, user);
}
```

It can be much powerfull instrument when used with Rx, Redux or some other instruments. For example, when stores are observable or streams, and when you build your requests to server by this LINQ (like in graphQL)

**Possible realizations**

1. Most stuped and easiest realization is translating to es6 enumerable objects (such filter, map and others). Works fust, but have a lot of restrictions in use.

2. Using some kind of queryBuilder. For example
``` ts
import { LINQ } from 'some-stream-lib';

/* ... */

const c = from a in foo from b in bar where a.barId === b.id select new FooBar(a,b);

```

Will be
``` ts
import { LINQ } from 'some-stream-lib';

const c = LINQ.from(foo).from(bar).where((a1, a2) => a1.barId === a2.id).select((a1, a2) => new FooBar(a1, a2)).execute();
```

Props: easy to use, easy to write, easy to extend, can realize many cool streams, fetch-api, json-api or other stuff.
Cons: builder shoud be executed in runtime and can be slow.

3. "Smart" way: builders has same syntax like in p.2, but executed in compile-time.

**Syntax and capabilities**
I think it should use same syntax as in C#. But if we want use something like queryBuilder question is how to use two different linq builder in one module.

**Comment by KAHI4** [comment]
Let's extends example.

So, supposing we have two backend API routes: `/item?groupId[]=x` and `/itemSuggestion?itemId[]=x1&itemId[]=x2...`

We want to display any item in group with their suggesions. Code is been like this:
``` ts
import { Item, ItemSuggestion } from 'models';
import { ItemService, SuggestionService } from 'services'';

/* ... */
const fulfilledItems = async from item in ItemService from suggestion in SuggestionService
    where item.group ===  currentGroup and suggestion.itemId === item.id
    group suggestions by item
    select new Item(item, suggestions);
```

After compile and builded by queryBuilder will create promises chain like this:
``` ts
const fetchedItems = async ItemService.fetchByGroups([currentGroup])
const fulfilledItems = async suggestionService.fetch(fetchedItems))
    .then(fetchedSuggestions => fetchedItems.map(item => fetchedSuggestions.filter(suggestion.itemId === item.id)));
```

Even we use some kind of reactive programming, query in LINQ-style doesn't change, but we have possibility to create beautiful code with one-direction data flow and changing ours model via service (after backend answer). It is possible now, but LINQ in my opinion makes code much more readable

**Comment by DanielRosenwasser** [comment]
We've generally taken a very conservative policy on adding certain new syntax because of how it might play with ECMAScript. Unless this was first provided by ECMAScript itself, this is something we wouldn't be willing to add to the language.

**Comment by isc30** [comment]
I would delegate the responsibility of this to some library, not to the TS compiler.
There are [very nice alternatives](https://github.com/isc30/linq-collections) out there
