### ISSUE TITLE
`Conversly when importing:` typo!

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [Microsoft/TypeScript#14304]
# `Conversly` when importing: typo! 

<del>Conversly</del> when importing: 

<mark>Conversely</mark> when importing: 

https://www.typescriptlang.org/docs/handbook/modules.html

### Conversly when importing:
> **_Explicitly list imported names_**
> **_Consumer.ts_**

```
import { SomeType, someFunc } from "./MyThings";
let x = new SomeType();
let y = someFunc();
```

**Comment by mhegazy** [comment]
Thanks @xgqfrms-GitHub. feel free to send PRs to https://github.com/Microsoft/TypeScript-Handbook
