### ISSUE TITLE
Allow classes to extend from values of type `any`

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#14301]
```ts
declare var Base: any;

class C extends Base {
}
```

This comes up in the context of untyped imports, as well as in js files.

Referenced in https://github.com/Microsoft/TypeScript/issues/13348 and https://github.com/Microsoft/TypeScript/issues/12971

**Comment by RyanCavanaugh** [comment]
Add `[s: string]: any` index signature to the instance and static types when this happens.
