### ISSUE TITLE
Allow variable declaration in if condition statements

### ISSUE THREAD

**Issue by miniak** [Microsoft/TypeScript#14309]
Example:

```
if (let element = document.getElementyById('foobar')) {
    element.someMethod();
}
```

This allows to have the variable properly block scoped, making it only available in the conditional block body. It should be possible to use `const` and `let`.

**Comment by DanielRosenwasser** [comment]
As much as I've liked this in other languages, it will probably not get implemented by us unless ECMAScript itself pursues it.
