### ISSUE TITLE
Doesn't resolve module via path settings tsconfig.json

### ISSUE THREAD

**Issue by xblox** [Microsoft/TypeScript#14311]
I'd like to import directly an external Typescript module from within another package but without using npm or index.d.ts file.

Let's say you have 2 Typescript packages (root/core-ts and root/consumer-ts) in one directory, each with its own 'src' folder, containing all TS files. I did set the paths for consuming package in the tsconfig.json:

```json
"baseUrl": "./src/",
"module": "amd",
"target": "es6",
"paths": {
            "@xblox/core/*": [
              "../../core-ts/src/", // <-- relative to baseUrl ?
            ]
        }
```

Now in my consuming package I'd like to consume "@xblox/core/foo":

`import {test} from '@xblox/core/foo';`

The packages contain isomorphic code, for "amd" and "commonjs".

I tried already all sorts of things but "tsc" seems never to pick it up.

Does someone has a pointer how to develop re-usable packages in Typescript? Most tutorials I found on the internet were assuming that the package comes from npm but at I am far from that stage and I actually don't want to publish these modules on npm at all. I just want import some stuff without relative paths, simple thing.

thanks

**Comment by vladima** [comment]
in its current form `paths` map any module name that starts with `@xblox/core/` to `../../core-ts/src/` which looks strange - maybe it should be 
```
"@xblox/core/*": [ "../../core-ts/src/*" ]
```

usually any unclear moments with module resolution can be clarified by using `traceResolution` compiler option - see [Tracing module resolution](http://www.typescriptlang.org/docs/handbook/module-resolution.html) section in documentation.

**Comment by xblox** [comment]
@vladima If i use this * on the right, its actually worst. VSCode does not enumerate my exports anymore but offers me @xblox/core/* instead. In top the compilation fails I import anything that way. 
and yes, I am using --traceResolution. 

tried with tsc 2.2.1 and VSCode 1.9 and recent VSCode-Insider.
Thanks a lot.

**Comment by xblox** [comment]
the only working setup I figured is to have a typings files in place (and specified in package.json) for the package to be consumed but that's exactly not what I want (using Typescript modules directly from an external location).

**Comment by vladima** [comment]
Can you please share your repro code?

**Comment by xblox** [comment]
I added you to https://github.com/xblox/ts-tests. 

So this is quite simple, the "library" to consumed is in core-ts. And the project from which I'd like to acquire external modules is "xblox-ts"

for instance, in [xblox-ts/src/index.ts](https://github.com/xblox/ts-tests/blob/master/xblox-ts/src/index.ts) I'd like to use "isArray" from [core-ts/src/primitives.ts](https://github.com/xblox/ts-tests/blob/master/core-ts/src/primitives.ts#L18). 

As said, I'd like my use Typescript modules without typings or npm, directly. No matter what I tried, it won't work. 

thanks again for looking at. Till today, I am in the dark whether I can use reusable modules between Typescript projects.

**Comment by vladima** [comment]
with this two changes I can compile `ts-tests` with no errors
```diff
diff --git a/xblox-ts/src/index.ts b/xblox-ts/src/index.ts
index 239d9bc..a1285e0 100644
--- a/xblox-ts/src/index.ts
+++ b/xblox-ts/src/index.ts
@@ -1 +1 @@
-import {isArray} from '@xblox/core/primitves';
+import {isArray} from '@xblox/core/primitives';
diff --git a/xblox-ts/tsconfig.json b/xblox-ts/tsconfig.json
index 10db50a..dee3da1 100644
--- a/xblox-ts/tsconfig.json
+++ b/xblox-ts/tsconfig.json
@@ -12,9 +12,7 @@
     "baseUrl": "./src/",
     "rootDir": "../",
     "paths": {
-      "@xblox/core/*": [
-        "../../core-ts/src/"
-      ]
+      "@xblox/core/*": ["../../core-ts/src/*" ]
     }
   },
   "compileOnSave": false,
```

**Comment by xblox** [comment]
@vladima : weird, indeed. seems that VSCode isn't really taking this path mapping into account. 

thanks again, closing this here.
