### ISSUE TITLE
type constraint in arithmetic operations

### ISSUE THREAD

**Issue by npenin** [microsoft/TypeScript#14316]
Hi,

Little weird behavior with generics and primitive constraints.

**TypeScript Version:**  2.2.1-insiders.20170217)

**Code**

```ts
export class Message<TUnitCode extends number> 
    {
        constructor()
        {
        }

        public unitCode: TUnitCode;

        public write()
        {
            data[7] = (this.unitCode & 0xFF) << 4;
            return data;
        }

        public parse(data: Buffer)
        {
            super.parse(data);
            this.unitCode = data[7] & 0xFF;
        }
    }
```

**Expected behavior:**
No compilation error: TUnitCode extends number and should behave as if it were a number

**Actual behavior:**
Compilation errors:
- [ts] The left-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.
- [ts] Type 'number' is not assignable to type 'TUnitCode'.

**Comment by npenin** [comment]
Possibly related to #2694

**Comment by mhegazy** [comment]
The first error should be addressed. the second error is accurate. you can not assign `number` to something that can be more specific than `number` , e.g. an enum.
