### ISSUE TITLE
lib.dom.d.ts: IDBKeyPath defined as string instead of string|string[].

### ISSUE THREAD

**Issue by mikelehen** [microsoft/TypeScript#14322]
**TypeScript Version:**  2.1.6

**Code**

```ts
    let request = window.indexedDB.open('database', /*version=*/1);

    request.onsuccess = (event: Event) => {
      let db = (event.target as IDBOpenDBRequest).result as IDBDatabase;
      db.createObjectStore('employees', {
        keyPath: ['company_id', 'employee_id']
      });
    };
```

**Expected behavior:**
Compiles.

**Actual behavior:**
```
test_db.ts(26,35): error TS2345: Argument of type '{ keyPath: string[]; }' is not assignable to parameter of type 'IDBObjectStoreParameters | undefined'.
  Type '{ keyPath: string[]; }' is not assignable to type 'IDBObjectStoreParameters'.
    Types of property 'keyPath' are incompatible.
      Type 'string[]' is not assignable to type 'string | undefined'.
        Type 'string[]' is not assignable to type 'string'.
```

**Notes:**
IndexedDB definition of keypath: https://www.w3.org/TR/IndexedDB/#dfn-key-path

**Comment by Kovensky** [comment]
On the other hand, this technically keeps your code IE-compatible 🤔

**Comment by mikelehen** [comment]
Do you have more details on that?  FWIW, it seems to be defined correctly in other places (e.g. [IDBObjectStore.keyPath](https://github.com/Microsoft/TypeScript/blob/master/lib/lib.dom.d.ts#L7081))

**Comment by Kovensky** [comment]
Nah, it's definitely a bug. It's just that IE doesn't support IDB path nesting.

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by rtm** [comment]
`IDBObjectStore.getAll()` is also not defined.
