### ISSUE TITLE
for...in loop not narrowing key

### ISSUE THREAD

**Issue by nsgundy** [Microsoft/TypeScript#14328]
**TypeScript Version:**  2.2.1

**Code**
```ts
type AB = 'A' | 'B';

type ABMAP = {
    [P in AB]: string
}

const abMap: ABMAP = {
    'A': 'a',
    'B': 'b'
}

function log(p: AB) {
    //
}

for (const p in abMap) {
    log(p); // <<-- Argument of type 'string' is not assignable to parameter of type 'AB'.
}
```

**Expected behavior:**
`p` is of type `AB`.

**Actual behavior:**
`p` is of type `string`

**Comment by Kovensky** [comment]
Any object can match your ABMAP type as long as it has _at least_ `A` and `B` as keys. There is no exact object type declaration 😢

**Comment by nsgundy** [comment]
That's a bummer. Any other way for the `log` function to keep its parameter typed as `AB`?

**Comment by mhegazy** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/13989

**Comment by nsgundy** [comment]
Thanks all, closing 👍
