### ISSUE TITLE
error TS2347: Untyped function calls may not accept type arguments.

### ISSUE THREAD

**Issue by P4** [Microsoft/TypeScript#14335]
**TypeScript Version:**  2.2.1, also tested on 2.1.1

**Code**
I'm using type definitions for d3JS version 3.5. Function `d3.layout.pie()` is defined as
```ts
        export function pie(): Pie<number>;
        export function pie<T>(): Pie<T>;
```

I want to use the second signature like this:
```ts
    interface Data {label:string, value:number}
    var pie = d3.layout.pie<Data>()
        .value(datum => datum.value);

```

**Expected behavior:**
Calling `pie<Data>()` returns `Pie<Data>` as per second signature

**Actual behavior:**
Call to `pie<Data>()` results in the following error:
```
error TS2347: Untyped function calls may not accept type arguments.
```
I'm not certain, but I think this implies that the 1st signature is used instead.

I'll be grateful for suggesting any solutions or workarounds.

**Comment by mhegazy** [comment]
The error indicate that either `d3.layout.pie` is of type `any`. Where are the declarations of `d3.layout` coming form? can you share a minimal repro?

**Comment by P4** [comment]
Thanks to your comment I managed to find the source of the error. 

One of the files in a different directory had `declare var d3: any`, which was interfering with the real definitions.

Replacing it with the proper directive ` ///<reference types="d3"/>` solved the problem.
