### ISSUE TITLE
String literal overload does not provide completion when `undefined` or `void` parameter present 

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/TypeScript#14333]
**TypeScript Version:**  2.2

**Code**

```ts

type Options = {
        text: string;
};

// Demonstrates fail with undefined
interface Foo {
    foo(kind: 'Bar', state?: undefined): void;
    foo(kind: 'Foo', state?: Options): void;
}

let f: Foo;
f.foo('Foo', { t }) // No completion offered for 't'

// Demonstrates fail with void
interface Foo2 {
    foo(kind: 'Bar', state?: void): void;
    foo(kind: 'Foo', state?: Options): void;
}

let ff: Foo2;
ff.foo('Foo', { t  }) // No completion here either

// Demonstrates success after changing order of overloads
interface Foo3 {
    foo(kind: 'Foo', state?: Options): void;
    foo(kind: 'Bar', state?: undefined): void;
}

let fff: Foo3;
fff.foo('Foo', { t }) // Okay: completion offered for 't'

```

**Expected behavior:**

Completion for the property "text" where it says "No completion offered for 't'"

**Actual behavior:**

There is no completion for "text" when "t" is typed.

**Comment by mhegazy** [comment]
This is a design limitation I am afraid. The completion list logic does an overload resolution first, it just happens that neither signatures match when you are typing the object literal, the result is picking the first, it happens that the first has no useful completions. 

This is a side effect of the issue tracked by https://github.com/Microsoft/TypeScript/issues/10523; if/when https://github.com/Microsoft/TypeScript/issues/10523 is fixed,  this should just work.
