### ISSUE TITLE
Update mixin docs

### ISSUE THREAD

**Issue by edjroot** [microsoft/TypeScript#14336]
Since #13743, I believe the [mixin docs](http://www.typescriptlang.org/docs/handbook/mixins.html) should be updated to showcase [TS 2.2 support](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-2.html). I actually only found out about the new feature through [this package](https://github.com/likerRr/ts-mixin), which linked to #2919, which in turn linked to the PR.

**Comment by j** [comment]
@mhegazy @DanielRosenwasser Any info on this?

**Comment by RyanCavanaugh** [comment]
The Handbook has been rewritten
