### ISSUE TITLE
Default imports not sourcemapped correctly

### ISSUE THREAD

**Issue by kgroat** [Microsoft/TypeScript#14348]
**TypeScript Version:**  2.2.1 (also in 2.3.0-dev.20170227)

**Code**

**`index.ts`**
```ts
import myModule from './myModule';
console.log(myModule);
```

**`myModule.ts`**
```ts
export default 'test';
```

**`tsconfig.json`**
```
{
  "compilerOptions": {
    "lib": [
      "es2015",
      "dom"
    ],
    "sourceMap": true,
    "target": "es5"
  }
}
```

**Expected behavior:**
Sourcemaps would correctly map the default export of `myModule.ts` in `index.ts` -- i.e. In Google Chrome, placing a breakpoint on the second line of `index.ts` and hovering the mouse over `myModule` should show `"test"`.

**Actual behavior:**
The debugger actually shows `{ "default": "test" }`

<img width="1440" alt="screen shot 2017-02-27 at 19 44 14" src="https://cloud.githubusercontent.com/assets/595616/23386596/4e19386e-fd25-11e6-859a-7551f95d5349.png">

Note that the watch on the variable also is not mapped correctly, because every reference is actually transpiled to `myModule_1.default`.

**Comment by Kovensky** [comment]
That is required to ensure live bindings work correctly. While the export from `myModule.ts` itself happens to not be live (`export default (non-function/class expression)` is the only case that's not), the code generation in `index.ts` cannot assume that.

**Comment by kgroat** [comment]
@Kovensky I'm not sure that I follow.  What do you mean by 'live'?  Is this something like what you mean?
```ts
export = {
  default: 5,
  setDefault(newVal) {
    this.default = newVal;
  }
};
```

**Comment by rbuckton** [comment]
@kgroat This isn't an issue with source map positions, as illustrated here:
![mapping](https://cloud.githubusercontent.com/assets/3902892/25411758/64c30bfa-29d3-11e7-9df8-3968c71b8ca3.png)

JavaScript Source Maps are primarily a way to assist a debugger when stepping through transpiled code, but do little to help with expression evaluation for things like "watch" expressions. Unfortunately, there's no good way to handle expression evaluation for debugging in most developer tools. The `"names"` field in the source map isn't flexible enough to handle this. Source maps only contain the starting offsets for a mapping, and do not include the length of the mapping. Even though there are offset mapped at the beginning and end of `myModule`, that does not necessarily mean that `myModule` points to all of the source text between the two mappings. Some compilers (TypeScript included) do not include mappings for every token when it doesn't affect debug stepping.

What Chrome is likely doing here is taking the position of the variable under the cursor (`myModule`) and finding the variable starting at that position. As a result, Chrome scans the source text starting at the original offset for an identifier, which returns `myModule_1`. There's no way for Chrome to know that the remaining `.default` should be considered part of the expression, so it doesn't include it.

Without changes to the Source Map specification to improve this, there's nothing we can do here that isn't already being done.
