### ISSUE TITLE
False sentence in the Typescript handbook since 2.2

### ISSUE THREAD

**Issue by alexjoverm** [Microsoft/TypeScript#14340]
**TypeScript Version:**  Just docs, applicable to version 2.2

The sentence in [the handbook docs](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html), is not true anymore, since the addition of `object` type in ts 2.2:

> If you’re tempted to use the type Object, consider using any instead. There is currently no way in TypeScript to specify an object that is “not a primitive”.

**Comment by mhegazy** [comment]
A PR to https://github.com/Microsoft/TypeScript-Handbook would be appreciated.

**Comment by alexjoverm** [comment]
Done https://github.com/Microsoft/TypeScript-Handbook/pull/521

**Comment by mhegazy** [comment]
thanks!
