### ISSUE TITLE
Suggestion: support exclusion in "types" compiler option

### ISSUE THREAD

**Issue by cnshenj** [Microsoft/TypeScript#14341]
Assume we have a project which uses Node.js on server and JavaScript on client. We can share a lot of code this way, especially data models.

However, the module systems are different between server and client. The server side uses standard Node.js module system, while the client side uses RequireJS AMD. The definitions of @types/node and @types/requirejs have conflicts (e.g. both define require variable, but different type).

Currently, we can specify all types except @types/node on client side; and specify all types except @types/requirejs on server side. This is inconvenient because we have to include many types instead of just excluding one. And whenever there is any change in types, we not only have to install/uninstall it via npm, but also edit **both** server and client tsconfig.json.

It would be much easier to read and maintain, to just write something like:
`"excludeTypes": ["node"]`

**Comment by mhegazy** [comment]
you do not need to specify all types in `"types"` field; the compiler still follows `import`s to `@types`. so all you need are ones that are not module, e.g. `node`.

**Comment by cnshenj** [comment]
Closed since it's not that big of a deal with mhegazy's suggestion.
