### ISSUE TITLE
Allow Configuring Quick Fix Auto-Import Quotes Type

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#14347]
From https://github.com/Microsoft/vscode/issues/21424

**TypeScript Version:**  2.2.1 

Using the new auto import quick fix, imports paths are always added with double quotes. This feature request is the ability to configure the TSServer to use single quotes instead, potentially with another  formatting setting

Potentially related to https://github.com/Microsoft/TypeScript/issues/11320

**Comment by mhegazy** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/13270

**Comment by mjbvz** [comment]
@mhegazy Thanks. Closing as a duplicate
