### ISSUE TITLE
Mapped types incorrect intellisense

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#14344]
_From @goodmind on February 27, 2017 20:15_

- VSCode Version: 1.9.1
- OS Version: OS X El Capitan 10.11.6

Steps to Reproduce:

1. Clone this repo: https://github.com/goodmind/vscode-intellisense-bug
2. Open files `test/ok_intellisense.ts` and `test/fail_intellisense.ts` and try to write some properties

FAIL              | OK
------------ | ------------
![image](https://cloud.githubusercontent.com/assets/3275424/23377707/d28862f0-fd52-11e6-9679-fb539cdb9dce.png) | ![image](https://cloud.githubusercontent.com/assets/3275424/23377714/d9905f8a-fd52-11e6-93da-a54eaaeff597.png)

_Copied from original issue: Microsoft/vscode#21519_

**Comment by mjbvz** [comment]
Here's an isolated repo of the issue:

```ts
interface SendCode {
  phone_number: string
}

interface Other {

}

interface ParamsTypes {
  "other": Other
  'auth.sendCode': SendCode
}

const invoke = <T extends keyof ParamsTypes>(
  method: T,
  params: ParamsTypes[T]
): void => { }

invoke<'auth.sendCode'>('auth.sendCode', {
  phone_
})


invoke('auth.sendCode', {
  phone_
})
```

We only get  suggestions in the `invoke<'auth.sendCode'>(...)` case

**Comment by goodmind** [comment]
@mhegazy can you take a look?

**Comment by LestaD** [comment]
Any progress here?

**Comment by doommm** [comment]
It seems that i get the same problem.
```
export interface MutationMaps {
    'm1': { enable: boolean; };
    'm2': { msgs: string[]; };
}
export function createMutation<K extends keyof MutationMaps>(type: K, payload: MutationMaps[K]) {        
    return { type, payload };
}
const t = createMutation('m1', { /* intellisense doesn't work here*/ });
```

**Comment by mhegazy** [comment]
Seems like a duplicate of https://github.com/Microsoft/TypeScript/issues/14772

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
