### ISSUE TITLE
Captured variable in async loop causing infinite execution with Promise polyfill in TS 2.3.0-dev (but not in 2.2.1)

### ISSUE THREAD

**Issue by rotemdan** [Microsoft/TypeScript#14357]
**TypeScript Version:**  2.3.0-dev.20170228

**Code**

_[Load [es6-promise](https://github.com/stefanpenner/es6-promise) polyfill]_

```ts
async function func(f: () => number) {
}

async function test() {
	console.log("Test started");
	for (let i = 0; i < 10; i++) {
		console.log(i);

		await func(() => i)
	}
	console.log("Test ended");
}

test()
```

**Expected behavior:**
Should execute correctly with a Promise polyfill, like in 2.2.1.

**Actual behavior:**
Non-terminating execution (and 100% CPU usage) with the Promise polyfill. The loop body (i.e. `console.log(i)`) is never reached.

**Reproduction:**

I've created a GitHub repository for the test code:

https://github.com/rotemdan/ts_emitterbugtest

To run, clone the repository, and open `index.html` in a browser not natively supporting promises (IE11, IE10, Android 4.x etc.).

Compare:
* [The emitted JS in 2.2.1](https://github.com/rotemdan/ts_emitterbugtest/blob/master/test.2.2.1.js)
* [The emitted JS in 2.3.0-dev](https://github.com/rotemdan/ts_emitterbugtest/blob/master/test.next.js)

**Comment by rbuckton** [comment]
The issue seems to be due to the addition of a call to `__values` in the new output, which looks for a `Symbol.iterator` property. I should have a fix up for review shortly.

**Comment by rbuckton** [comment]
@rotemdan This has been fixed and will be in tonight's build. Let me know if you continue to see issues.
