### ISSUE TITLE
webaudioapi : cannot connect an AudioNode to an AudioParam

### ISSUE THREAD

**Issue by jice-nospam** [Microsoft/TypeScript#14355]
**TypeScript Version:**  2.2.1

The connect prototype for AudioNode interface in lib.dom.d.ts should be 
```
    connect(destination: AudioNode|AudioParam, output?: number, input?: number): void;
```
instead of
```
connect(destination: AudioNode, output?: number, input?: number): void;
```

see [this](https://developer.mozilla.org/en-US/docs/Web/API/AudioNode/connect(AudioParam))

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by bondz** [comment]
Microsoft/TSJS-lib-generator#206 should fix this.
