### ISSUE TITLE
Class generics constrains is not used in class functions 

### ISSUE THREAD

**Issue by zivni** [Microsoft/TypeScript#14356]
**TypeScript Version:**  2.1.1 

**Code**
This generates an error:
```ts
interface IDerived {
    text: string
}

class Base<T>{
    protected internal: T
    protected setData(data: Partial<T>) {
        this.internal = Object.assign({}, this.internal, data)
    }
}

class Derived<T extends IDerived> extends Base<T> {
    public getText() {
        return this.internal.text //this is OK
    }

    public setText(text: string) {
        this.setData({ text }) //this gives Argument of type '{ text: string; }' is not assignable to parameter of type 'Partial<T>'.
    }
}
```
This also generates an error:
```ts
class Derived<T extends IDerived> {
    private internal: T

    private setData(data:T) {
        this.internal = Object.assign({}, this.internal, data)
    }

    public getText() {
        return this.internal.text
    }

    public setText(text: string) {
        this.setData({ text }) //Argument of type '{ text: string; }' is not assignable to parameter of type 'T'.
    }
}
```
In the second example, if I change the setData signature to `setData<T extends IDerived>(data:T)` there is no error. 

**Expected behavior:**
No Error

**Actual behavior:**
Error

**Comment by mhegazy** [comment]
`T` is a generic type argument. it has to be at least `IDerived` but it can be more specific. consider:

```ts
interface IDerived {
    text: string | number;
}

class Derived<T extends IDerived> extends Base<T> {
    public setText(text: string) {
        // IDerived.text can be string | number
        this.setData({ text }) 
    }
}

new Derived<{ text: number }>(); // but number also fits the constraint
```

**Comment by zivni** [comment]
Well it's strange that you can substitute with more specific as it seems to violate the Liskov Substitution Principle. T extends IDerived so you should be able to use T where ever you use IDerived. It means that, when using IDerived from @mhegazy example,  you should always be able to set the text property to string or number.

This should always be correct (and it compiles as it should):
```TS
interface IDerived {
    text: string | number;
}

function foo<T extends IDerived>(t: T): T {
    if (someCondition) {
        t.text += "a";
    } else {
        t.text += 3;
    }
    return t;
}
```
But this also compile and I believe it shouldn't 
```TS
var a = foo<{ text: number }>({ text: 5 });
```
Because the type of a is {text:number}. But if `someCondition = true`, then a.text is "5a" - a string. The actual return type is {text: string | number} as depending on the value of text and someCondition it can be a string or a number. 

Also your explanation doesn't explain how in my second example when  we change the setData signature to setData<T extends IDerived>(data:T) there is no error.
