### ISSUE TITLE
import support alias?

### ISSUE THREAD

**Issue by Midqiu** [Microsoft/TypeScript#14354]
I write code like this:
![image](https://cloud.githubusercontent.com/assets/5728399/23394992/22eff4c8-fdc7-11e6-8995-5bcdeb92e7b7.png)

I want to code like this:

```ts
import DB from '!#src/common/DB/DB';
import config from '!#src/common/Config/Config';

```

**Comment by HerringtonDarkholme** [comment]
Please read the doc. 
http://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping

**Comment by Midqiu** [comment]
this .ts is:
![image](https://cloud.githubusercontent.com/assets/5728399/25418021/2dd3166e-2a7b-11e7-880e-f4ec73c14920.png)

but the build js .is :

![image](https://cloud.githubusercontent.com/assets/5728399/25418010/0ded1a34-2a7b-11e7-9ec9-919e270847a6.png)

I want :
`const Permission_1 = require("../../../common/Permission");`
in the build js file.
