### ISSUE TITLE
Can ts infer "never" return type without reduntant return?

### ISSUE THREAD

**Issue by liujunxing** [Microsoft/TypeScript#14353]
**TypeScript Version:**  2.1.5 / nightly (2.2.0-dev.201xxxxx)

**Code**

```ts
// A function return "never"
function foo(msg): never {
  throw new Error(msg);
}

// A function call to foo and return "never" too.
function bar(): never {  // ERROR: Return statement is required for non-void return type
  foo('custom message');
  // We can resolve the question by add reduntant return foo(...) statement 
  // return foo('custom message');   -- correct
}

```

**Expected behavior:**
Hope need not add the reduntant return keyword here.

**Actual behavior:**
ERROR: Return statement is required for non-void return type

**Comment by mhegazy** [comment]
This is a design limitation of the current system. the process of inferring return types depend on having a throw/return statement. 

you can instead use `return foo(..)` as you noted.
