### ISSUE TITLE
Documentation is bloqued to version 1.8

### ISSUE THREAD

**Issue by mtabaj** [Microsoft/TypeScript#14364]
The documentation doesn't include all the new features of version 2

**Comment by mhegazy** [comment]
Which documentation are you referring to? what features are missing?

**Comment by mtabaj** [comment]
I refer to GitHub docs. If you look at

http://www.typescriptlang.org/index.html#download-links

the specification you can read/download are those of version 1.8

 

Marcos

 

 

De : Mohamed Hegazy [mailto:notifications@github.com] 
Envoyé : mardi 28 février 2017 20:07
À : Microsoft/TypeScript <TypeScript@noreply.github.com>
Cc : Marcos Tabaj <mtabaj@netiness.com>; Author <author@noreply.github.com>
Objet : Re: [Microsoft/TypeScript] Documentation is bloqued to version 1.8 (#14364)

 

Which documentation are you referring to? what features are missing?

**Comment by mhegazy** [comment]
The link points to the latest version of the spec, it is just that the spec is out of date at this point. we have some [work items](https://github.com/Microsoft/TypeScript/issues?q=is%3Aopen+is%3Aissue+label%3ASpec+sort%3Acreated-desc) tracking updating the spec
