### ISSUE TITLE
Should not widen in type argument inference

### ISSUE THREAD

**Issue by JsonFreeman** [Microsoft/TypeScript#1436]
Compile the following using noImplicitAny:
```ts
function foo<T>(x: T): T { return x }

interface I {
    x: string;
}

var i: I = foo({ x: null }); // Error
var s: string = f(null); // No error
```

Neither of these should be errors. According to the spec, both of these should widen, but in #531 @DanielRosenwasser and I explain why these should not widen.

The noImplicitAny error resulting from widening is a breaking change from 1.0, and it broke a customer.

**Comment by JsonFreeman** [comment]
I think the following code would break if we do this:
```ts
declare function makeArray<T>(x: T): T[];
makeArray(null)[0] = 0; // Error that number is not assignable to null
```
I am not sure if there are useful examples where the user would blocked by this. But the point is, it leads to null and undefined leaking out in a lot more places. The cost of doing this would involve taking inventory of all the places where this could happen and widening in all those places.

**Comment by JsonFreeman** [comment]
Then again, the following code is already an error because of a null leak:
```ts
[null][0] = 0;
```

So this may not really have to do with type argument inference at the core.

**Comment by osdm** [comment]
Hi @JsonFreeman ! You say "According to the spec...". Could you point me, where does the spec says about widening in the type inference? I searched through 1.3, 1.4 and 1.5 versions of the spec and found nothing about widening in the type inference. Maybe it's just me being dumb...

**Comment by JsonFreeman** [comment]
Hmm, now I can't find it anymore. I remember it being in the second bullet point in section 4.12.2 (Type argument inference).

@ahejlsberg, was it intentional that widening at the end of type argument inference was removed from the spec?

**Comment by osdm** [comment]
@JsonFreeman Ok, I was wrong about 1.3, sorry. Widening is really there. But it disappeared in 1.4.

**Comment by JsonFreeman** [comment]
Ok, I see it was removed in 7a2701b5c50681af9f43272c19ed039dd92dad16. I think this was just an oversight, as the definition of C moved inside the bullet. The change we were trying to make was just to add the capability for type argument inference to error. This was at the time we introduced union types.

**Comment by JsonFreeman** [comment]
See my comment on #3733. Also, there is a nice sample their that exercises contrasting cases.
