### ISSUE TITLE
Spread '...' should throw TypeError for 'undefined'

### ISSUE THREAD

**Issue by DLehenbauer** [Microsoft/TypeScript#14362]
**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)

**Code**

```ts
const a = [];
const x: number[] | undefined = undefined;

a.push(...x);
```

**Expected behavior:**
Always throws 'TypeError: x is not iterable', regardless of the '--target'.

**Actual behavior:**
For '--target es5', no error is thrown.  This is because the spread is transformed into a call to '.apply()', which accepts 'undefined'.

(I stumbled on this when compiling tsc with '--target es2015', which revealed that the compiler had a minor dependency on the noncompliant spread behavior.)

**Comment by mhegazy** [comment]
Seems to be the same issue as https://github.com/Microsoft/TypeScript/issues/1679

**Comment by DLehenbauer** [comment]
You're right, it's a dupe.  (Sorry, I didn't include closed issues in my search.)

**Comment by mhegazy** [comment]
thanks. closing.
