### ISSUE TITLE
Extend Lookup Types to function calls

### ISSUE THREAD

**Issue by danvk** [Microsoft/TypeScript#14372]
I can map between two types using overloaded function declarations:

```ts
declare function mapTypes(x: TypeA): number;
declare function mapTypes(x: TypeB): string;

let a: TypeA;
let b = mapTypes(a);  // b has type number
```

It would be great if I could if I could extend this mapping to types whose values were all either `TypeA` or `TypeB` using `keyof` and something like lookup types:

```ts
interface Foo {
  a: TypeA;
  b: TypeB;
}

// should be { a: number; b: string; }
type MappedFoo = {[K in keyof Foo]: typeof mapTypes(K)};
```

Really I'd like some way to take an interface and define a new one by mapping all of its value types in some specific ways. Context: see [Map between types in TypeScript][1] on StackOverflow.

[1]: http://stackoverflow.com/questions/42520459/map-between-types-in-typescript

**Comment by mhegazy** [comment]
Should be covered by https://github.com/Microsoft/TypeScript/issues/6606
