### ISSUE TITLE
Escaping $ in a template string not working

### ISSUE THREAD

**Issue by StrahilKazlachev** [Microsoft/TypeScript#14370]
**TypeScript Version:**  2.2.1

**Code**

```ts
`$${label}`;
`\${label}`;
```

**Expected behavior:**
The two expressions to have the same output.

**Actual behavior:**
```
`$${label}`; // "$" + label; // Can not find name 'label'.
`\${label}`; // "${label}"; // OK
```

**Comment by mhegazy** [comment]
This behavior seems correct to me. From the ES6 spec( see http://www.ecma-international.org/ecma-262/6.0/#sec-template-literal-lexical-components),:

> TemplateCharacter ::
$ [lookahead ≠ { ]
\ EscapeSequence
LineContinuation
LineTerminatorSequence
SourceCharacter but not one of ` or \ or $ or LineTerminator

Do not see any reference to `$$` being template charter.

**Comment by mhegazy** [comment]
![image](https://cloud.githubusercontent.com/assets/8000722/23438806/6af58318-fdc8-11e6-95d0-d3b899579732.png)

**Comment by StrahilKazlachev** [comment]
OK, sometimes I start doubting myself...
