### ISSUE TITLE
Function overloading based on string enum parameter.

### ISSUE THREAD

**Issue by realyze** [Microsoft/TypeScript#14375]
typescript@2.1.6

I'd like to write a polymorphic function whose return type is inferred based on string enum value of a parameter.

Is there a way to do that?

Here's my - probably quite naive - approach (which doesn't compile):

```
type Test1 = 'foo';
type Test2 = 'bar';
type TUnion = Test1 | Test2;

interface TReturnForTest1 { }
interface TReturnForTest2 { }

function unionTypeTest(arg: Test1): TReturnForTest1;
function unionTypeTest(arg: Test2): TReturnForTest2;
function unionTypeTest(arg: TUnion): any {
    return null;
}

const bar = unionTypeTest('foo' as TUnion);  // Error: Type '"foo"' is not assignable to type '"bar"'.
```

**Comment by mhegazy** [comment]
```ts
function unionTypeTest(arg: Test1): TReturnForTest1;
function unionTypeTest(arg: Test2): TReturnForTest2;
function unionTypeTest(arg: Test1|Test2): TReturnForTest1 | TReturnForTest2;
function unionTypeTest(arg: TUnion): any {
    return null;
}
```

see https://github.com/Microsoft/TypeScript/issues/14337 for relevant discussion.

**Comment by realyze** [comment]
@mhegazy Thanks for the reply! Not sure I grok the scalability concerns though. I'd expect tsc would just check the declarations from top to bottom and use the first one that matches, no? (i.e., linear w/r to number of declaration overloads). Doesn't seem unscalable to me.
