### ISSUE TITLE
In lib.d.ts hasn't signature for formData types (Fetch API)

### ISSUE THREAD

**Issue by alfaslash** [Microsoft/TypeScript#14378]
**TypeScript Version:**  2.2.1

After adding typings for Fetch API in core typescript I got an error `Property 'formData' does not exist on type 'Response'`. Because in lib.dom.d.ts I see:
```
interface Body {
    readonly bodyUsed: boolean;
    arrayBuffer(): Promise<ArrayBuffer>;
    blob(): Promise<Blob>;
    json(): Promise<any>;
    text(): Promise<string>;
}
```
But for [typings whatwg-fetch](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/whatwg-fetch/index.d.ts#L37):
```
interface Body {
    readonly bodyUsed: boolean;
    arrayBuffer(): Promise<ArrayBuffer>;
    blob(): Promise<Blob>;
    formData(): Promise<FormData>;
    json(): Promise<any>;
    json<T>(): Promise<T>;
    text(): Promise<string>;
}
```

And this types in Fetch API spec https://fetch.spec.whatwg.org/#body

I sent a [PR](https://github.com/Microsoft/TSJS-lib-generator/pull/208) to the repository **TSJS-lib-generator**

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by alfaslash** [comment]
My [PR](https://github.com/Microsoft/TSJS-lib-generator/pull/208) was merged.

**Comment by mhegazy** [comment]
We still need to port the changes from https://github.com/Microsoft/TSJS-lib-generator. keeping it open until a new drop is ported.
