### ISSUE TITLE
Possible bug: Hybrid between two interfaces of a union passes type checking

### ISSUE THREAD

**Issue by dsifford** [Microsoft/TypeScript#14383]
**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.20170228)

[Went to StackOverflow with this first](http://stackoverflow.com/questions/42522431/union-type-one-or-the-other-failing-not-sure-if-this-is-by-design-or-a-bug/42523664#42523664) and the consensus there seems to be that this is a bug.

Here's my question again for convenience:

---

Consider a situation where an object can have exactly the `FooBar` or `Baz` interface listed below.

```ts
interface FooBar {
    foo: string;
    bar: string;
}

interface Baz {
    baz: string;
}
```

It's my understanding that this "one or the other" situation can be handled by creating a union between `FooBar` and `Baz`.

```ts
type FooBarOrBaz = FooBar | Baz;
```

So far so good...

The issue I'm having is that the following object passes type checking:

```ts
const x: FooBarOrBaz = {
    foo: 'foo',
    baz: 'foo',
};
```

**Expected behavior:** `x` should not pass type checking. It's neither `FooBar` nor `Baz`, but rather a combination between the two.

**Actual behavior:** `x` passes type checking.

[Playground Example](http://www.typescriptlang.org/play/index.html#src=interface%20FooBar%20%7B%0D%0A%20%20%20%20foo%3A%20string%3B%0D%0A%20%20%20%20bar%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20Baz%20%7B%0D%0A%20%20%20%20baz%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Atype%20FooBarOrBaz%20%3D%20FooBar%20%7C%20Baz%3B%0D%0A%0D%0Aconst%20x%3A%20FooBarOrBaz%20%3D%20%7B%0D%0A%20%20%20%20foo%3A%20'foo'%2C%0D%0A%20%20%20%20baz%3A%20'foo'%2C%0D%0A%7D)

**Comment by ahejlsberg** [comment]
This is working as intended. The type `{ foo: string, baz: string }` is indeed assignable to `{ baz: string }` because a subtype is free to add additional properties. The thing that is perhaps surprising is that you don't get an error in your example, but you do get an error in the following:

```ts
const x: Baz = {
    foo: 'foo',  // Error, excess property
    baz: 'foo',
};
```

This is because when the target is a union type our excess property checking logic (#3823) only checks that each property exists in *some* variant of the target. It should perhaps be stricter and check that the source is assignable to at least one variant with no excess properties (which would then error on your example).

**Comment by dsifford** [comment]
@ahejlsberg Ah, okay that makes sense I suppose.

I'm admittedly ignorant as to how much added complexity it would take to add the stricter checking but, intuitively speaking, I would assume the example above to only compile successfully with interfaces having an index signature.

The use-case I had when I ran into this issue was when I was attempting to create a function parameter that accepted two different forms of authentication: One being basic username and password auth (in which case, both of these fields is required), and the other being browser cookie authentication where only a single field is required.

I ended up just creating a union between a `BasicAuth` interface and `string` which solved the problem.

Thanks for the education on this.

**Comment by fcrick** [comment]
I'd love to see these stricter checks at some point - any way to work around this issue without changing the types themselves? I'm trying to validate some existing data, and I can describe all the types I need, but the lack of the stricter check lets bad data through.

```
// no error - this is what I hoped would work
let x: { a: number; } | { b: number; } = {
    a: 5,
    b: 5
};

// errors as expected
x = { a: 5 };
x.b = 4;

// errors as expected
const y: { b: number; } = {
    a: 5,
    b: 5
};
```

**Comment by RyanCavanaugh** [comment]
Some relevant discussion of this at https://github.com/Microsoft/TypeScript/issues/12936#issuecomment-284590083
