### ISSUE TITLE
add nodePosToString to the public API

### ISSUE THREAD

**Issue by bjouhier** [microsoft/TypeScript#14386]
**TypeScript Version:**  2.1.6

I'm using the typescript library to parse ts source code and I would like to have access to the `nodePosToString` function to format diagnostics. This function is internal for now.

**Comment by bjouhier** [comment]
just saw tslib (I was mislead by the @internal comment). I'll close the issue if I can find it in tslib.

**Comment by bjouhier** [comment]
No, I was mislead again by the `export const externalHelpersModuleNameText = "tslib";` line below the `@internal` line. I'm keeping the issue open.

**Comment by reduckted** [comment]
Not sure if anything has changed since v2.1.6, but in v2.3.2 it's at least accessible, though it's still not publicly exposed.

```typescript
import * as ts from 'typescript';

let node = getNodeFromSomewhere();
let position = (ts as any).nodePosToString(node); // <-- It's on the `ts` object, but just not part of the definition.
```

**Comment by RyanCavanaugh** [comment]
Haven't gotten enough feedback on this one to warrant exposing it
