### ISSUE TITLE
import is treated as keyword, hence using import() is impossible

### ISSUE THREAD

**Issue by aanno** [Microsoft/TypeScript#14381]
**TypeScript Version:**  2.2.1

**Code**

```ts
// I want to use the dynamic import feature of webpack (2.2.1) with the react-router.
// Sorry, this example is *not* self-contained
...
    // <Route path={ baseUrl + "/filters" } component={Filters}/>
    {
      path: baseUrl + "/filters",
      getComponent: function (location: RouterState, cb: ComponentCallback): undefined {
        import("./Pages/Filters").then(loadRoute(cb)).catch(errorLoading)
        return undefined
      },
    },
...
```

**Expected behavior:**
`import()` could be used for dynamic module loading.

**Work around**
If I replace `import()` with `System.import()`, everything works as expected. However, `System.import()` is deprecated in webpack.

**Actual behavior:**
`import` is treated as keyword. There is no way to use `import()` as suggested in the webpack doc (https://webpack.js.org/guides/code-splitting-import/). I already suggested there that `import` might not be the best name for dynamic module loading, but it is the name currently in discussion for the next ES standard. See https://github.com/webpack/webpack/issues/4372 for more details.

Errors:
```
[at-loader] Checking finished with 102 errors                                                                                 
[at-loader] src/components/MyRouter.tsx:101:9 
    TS1128: Declaration or statement expected. 

[at-loader] src/components/MyRouter.tsx:101:16 
    TS1138: Parameter declaration expected. 

[at-loader] src/components/MyRouter.tsx:101:33 
    TS1005: ':' expected. 

[at-loader] src/components/MyRouter.tsx:101:34 
    TS1136: Property assignment expected. 

[at-loader] src/components/MyRouter.tsx:101:49 
    TS1005: '=' expected. 

[at-loader] src/components/MyRouter.tsx:101:54 
    TS1005: '{' expected. 
```

**Comment by mhegazy** [comment]
`import` is a [reserved JS word](http://www.ecma-international.org/ecma-262/6.0/#sec-keywords). support for `import()` is tracked by https://github.com/Microsoft/TypeScript/issues/12364
