### ISSUE TITLE
JSDoc Property Name with Dash Not Recognized

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#14395]
From  https://github.com/Microsoft/vscode/issues/21592

**TypeScript Version:**  2.2.1

**Code**

```js
/**
 * @typedef Product
 * @property {string} title
 * @property {boolean} high-top
 */

/**
 * @type {Product}
 */
const product = null
```

**Expected behavior:**
`product` has a `high-top` property.

**Actual behavior:**
`product` has a `high` property:

```
Trace - 12:00:17 PM] Sending request: completions (39). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/Users/matb/projects/sand/bar.js",
    "line": 12,
    "offset": 9
}
[Trace - 12:00:17 PM] Response received: completions (39). Request took 16 ms. Success: true 
Result: [
    {
        "name": "Product",
        "kind": "warning",
        "kindModifiers": "",
        "sortText": "1"
    },
    {
        "name": "high",
        "kind": "property",
        "kindModifiers": "",
        "sortText": "0"
    },
    {
        "name": "product",
        "kind": "warning",
        "kindModifiers": "",
        "sortText": "1"
    },
    {
        "name": "title",
        "kind": "property",
        "kindModifiers": "",
        "sortText": "0"
    }
]
```

**Comment by ChristianReifberger** [comment]
Hi, can I try this one? Would be my first PR in TS

**Comment by mhegazy** [comment]
go for it.

**Comment by jcowman2** [comment]
This issue looks like it hasn't been touched in a while, so I'd love to try it. Do you have any suggestions for where to start?

**Comment by VitorLuizC** [comment]
@fuafa maybe with a char after and before  its name, similar to string values.

```js
/**
 * ...
 * @property {boolean} "high-top"
 */
```

**Comment by gangsthub** [comment]
Unfortunately not yet, @VitorLuizC.

**Comment by enjikaka** [comment]
It says this is fixed but in VSCode I'm seeing: 

![](https://i.imgur.com/cv6S1kR.png)

**Comment by sandersn** [comment]
@enjikaka It is fixed in 3.7 but not 3.6: http://www.typescriptlang.org/play/?ts=3.7-Beta&useJavaScript=true#code/PQKhCgAIUgBAXAngBwKYBNUDNIAUBOA9ugK4DG8UMsyRa+SkA3gM7z4CWAdgOYC+keB3gAbVFTi1C9RkwBGhQmICGXAQAsOPdQFp40qsHDgAHpAC8kAIxA

**Comment by enjikaka** [comment]
Aha, not out yet. I though it would be out by now as it was merged in August.

**Comment by mlajtos** [comment]
TypeScript handles this OK. However, syntax highlighting in VSCode does not.

**Comment by kilgarenone** [comment]
Looks like **JSDoc** doesn't recognize names with dash in VSCode. Is it just me?

**Comment by goldingdamien** [comment]
For anyone just looking for a way to document. This seems possible:

/**
* @typedef {{
* "a-b-c": number
* }} MyObject
*/

**Comment by pedroposada** [comment]
This is working fine for me in VSCode version 1.66.1
```
/**
 * @typedef {Object} User
 * @property {string} user-name
 * @property {string} user-id
 */
```

**Comment by RyanCavanaugh** [comment]
This seems to work in completion, tooltips, and doc comments, so closing. Please open a new issue if there's another behavior that you see not working.
