### ISSUE TITLE
Namespace clobbering in IE8

### ISSUE THREAD

**Issue by richard-gebbia** [Microsoft/TypeScript#14393]
**TypeScript Version:**  2.1.4

**Code**

With the following Typescript:

```ts
namespace Foo {
    var bar;
}

```

The emitted JS is: 
```ts
var Foo;
(function (Foo) {
    var bar;
})(Foo || (Foo = {}));
```

If `Foo` is a namespace spread across two or more files, there will be two `var Foo;`s, which, in IE8 and below, cause `Foo` to be re-initialized, thus clobbering the previous contents of the namespace.

**Expected behavior:** Not sure what the exact implementation should be, but the end goal is to be able to use namespaces and still have the emitted JS run in IE8. 

**Actual behavior:** Any namespace spanning two or more files will raise a JS exception in IE8 and lower.

**Comment by mhegazy** [comment]
Are you using `--outFile`?

**Comment by richard-gebbia** [comment]
`--outFile` will unfortunately not work for two reasons:
1. `--outFile` still produces multiple `var` declarations
2. It's possible that the namespace is coming from JS with interop

**Comment by mhegazy** [comment]
For `--outFile` we can elide the var`s withing the same file, i.e. make sure we emit only one `var Foo`. for multiple files, i do not know what we can do really.

**Comment by RyanCavanaugh** [comment]
I think we've waited out IE8 long enough
