### ISSUE TITLE
No dependencies installed on node 7

### ISSUE THREAD

**Issue by MickL** [microsoft/TypeScript#14390]
**TypeScript Version:** 
2.2.1

**Software versions used:**
Ubuntu Server 16.04.2 LTS (Fresh installation)
Node js 7.7.0 (latest stable)
npm 4.4.0

**Issue:**
Installing TypeScript with `npm install -g typescript` does not install ANY dependencies (like @types).

- `node_modules/` contains only `typescript/`
- `node_modules/typescript/ `contains no `node_modules/`

Therefor tsc produces errors "Can not find name ..."

Can anyone reproduce?

**Comment by MickL** [comment]
If i go into `node_modules/typescript/` and do `npm i` it does install devDependencies.

**Comment by mhegazy** [comment]
TypeScript node package has no dependencies. If you need `@types` packages you should install them independently, and add them to your package.json.

If you go the package folder, you get the devdependencies of TypeScript, which is something you only need if you are contributing to the TypeScript project.
