### ISSUE TITLE
Incorrect casing: property "URL.searchparams" should be "URL.searchParams"

### ISSUE THREAD

**Issue by JeffJacobson** [Microsoft/TypeScript#14399]
In lib.dom.d.ts, the [searchparams property of the URL interface](https://github.com/Microsoft/TypeScript/blob/master/lib/lib.dom.d.ts#L11860) should be cased as searchParams according to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/URL/searchParams).

**TypeScript Version:**  2.2.1

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
let pageUrl = new URL(location.href);
let url = pageUrl.searchParams.get("url");
```

**Expected behavior:**

Should compile successfully.

**Actual behavior:**

`tsc` returns an error when compiling.

```console
src/index.ts(9,19): error TS2339: Property 'searchParams' does not exist on type 'URL'.
```

**Comment by mhegazy** [comment]
Should be fixed by https://github.com/Microsoft/TSJS-lib-generator/pull/198

**Comment by epicgirl1998** [comment]
i installed `typescript@2.3.0-dev.20170322` via npm but it doesn't seem to have the change in it yet

it has today's date on it but not a change from 21 days ago

i hope this can be fixed soon

**Comment by mhegazy** [comment]
the fixes has not been ported to the main TS repo, pushed a PR to port them in #14805.
