### ISSUE TITLE
tsconfig.js ignore and module resolution problems in Visual Studio.NET 2017 RC4

### ISSUE THREAD

**Issue by deastr** [Microsoft/TypeScript#14408]
**TypeScript Version:**  2.1 (the one which comes with the VS.NET 2017 RC4. Also 1.7 and 1.8 is installed)

TS files generate lots of errors with decorators and module resolution in VS.NET 2017 RC4. I'd appreciate if I can get any insight if this is a bug or something wrong with my setup.

Here's an example screenshot:

![capture](https://cloud.githubusercontent.com/assets/18551424/23505756/bda43f7e-ff4d-11e6-88fb-0c66b68b0e63.PNG)

Example file is located in this location:

`<root>\wwwroot\Application\Components\Task\Search\Search.ts`

Here's my `tsconfig.json` in the root folder of the project:

```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [ "es2015", "dom" ],
    "suppressImplicitAnyIndexErrors": true
  },
  "exclude": [
    "node_modules",
    "wwwroot/Application" 
  ]
}
```

I have Typings globally installed.

**Comment by mhegazy** [comment]
The errors suggest that your tsconfig.json is not picked up for your file `Search.ts`. can you verify that:
- tsconfig.json is added to your project, and that its content type is `content`
- tsconfig.json is in a parent folder of `Search.ts`

If yes for both, can you share a sample project to look at?

**Comment by deastr** [comment]
@mhegazy : I can confirm both. 

I don't know what happened but I'm not getting errors now so I'm closing this issue. Thank you for your help.
