### ISSUE TITLE
`--target ESNext` does not include lib.dom.d.ts by default

### ISSUE THREAD

**Issue by molant** [Microsoft/TypeScript#14401]
**TypeScript Version:**
2.2.1

**Code**

Try running tsc in a file that contains the following (`tsc test.ts` for example):
```ts
var a  = new Map();
```

**Expected behavior:**
Not to get an error message in the output (`test.js` gets generated though)

**Actual behavior:**

The output of the command above (`tsc test.ts`) is as follows:
> test.ts(1,15): error TS2693: 'Map' only refers to a type, but is being used as a value here.

**Comment by mhegazy** [comment]
Do you have `--lib es6` or `--target es6` ? if not, do you have a declaration of `Map` any where in your project?

**Comment by molant** [comment]
I've tried using es6 and esnext in a tsconfig.json file:
```json
{
    "compilerOptions": {
        "target": "esnext"
    }
}
```

**Comment by molant** [comment]
`tsc .\test.js --target esnext` gives the following error:
> node_modules/@types/highlight.js/index.d.ts(19,40): error TS2304: Cannot find name 'Node'.

Guess that something related with my project

`tsc .\test.js --target es6` doesn't output any error/warning

`tsc .\test.js` with the tsconfig.json and target `es6` next outputs:
> test.ts(1,15): error TS2693: 'Map' only refers to a type, but is being used as a value here.

**Comment by molant** [comment]
This is for a node project running node-chakracore so no worries about es6 support.

**Comment by blakeembrey** [comment]
@molant Did you try running just `tsc` and using the `include` or `files` option in `tsconfig.json`? There's a little gotcha that happens from the command line - when you specify the files manually it doesn't use the `tsconfig.json` file anymore and it'll use the CLI flags instead (hence the results you got above).

**Comment by molant** [comment]
@blakeembrey specifying `test.ts` in the `tsconfig.json` and with `es6` and `esnext` returns:
> node_modules/@types/highlight.js/index.d.ts(19,40): error TS2304: Cannot find name 'Node'.

even if I have excluded `node_modules`:

```json
{
    "compilerOptions": {
        "target": "esnext"
    },
    "files": [
        "test.ts"
    ],
   "exclude": [
        "node_modules"
    ]
}
```
Not sure why I'm getting that message but I guess the output is the expected then?

**Comment by mhegazy** [comment]
The issue is the DOM definitions are not included by default when `--target ESNext` is set. we should fix that.

for now, you can specify the library explicitly:

```json
{
    "compilerOptions": {
        "target": "esnext",
        "lib": ["esNext", "dom", "dom.iterable"]
    }
}
```

Also `"files"` and `"exclude"` should not be specified together. `"files"` always win.
