### ISSUE TITLE
compile error when re-assigning an initialized readonly boolean in the constructor

### ISSUE THREAD

**Issue by gmoothart** [Microsoft/TypeScript#14416]
**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)

If you initialize a readonly class field to `false` and then assign it to a boolean in the constructor, you get a compile error that boolean is not assignable to false.

playground link: 
https://www.typescriptlang.org/play/#src=export%20class%20Hello%20%7B%0D%0A%20%20%20%20readonly%20foo%20%3D%20false%3B%0D%0A%20%20%20%20constructor(foo%3A%20boolean%7Cundefined)%20%7B%0D%0A%20%20%20%20%20%20%20%20this.foo%20%3D%20foo%20%7C%7C%20this.foo%3B%0D%0A%20%20%20%20%7D%0D%0A%7D

**Code**

```ts
export class Hello {
    readonly foo = false;
    constructor(foo: boolean|undefined) {
        this.foo = foo || this.foo;
    }
}
```

**Expected behavior:**

Code should compile

**Actual behavior:**

`ERROR: Type 'boolean' is not assignable to type 'false'.`

**Comment by mhegazy** [comment]
`readonly` properties, just like `const` declarations get literal types if initialized. in this case `foo` gets the type `false` and not `boolean`. in the constructor you are assigning `boolean`, i.e. `true | false` and that is not assignable to `false`. 

declare your property as `boolean` instead:

`readonly foo: boolean = false;`

**Comment by gmoothart** [comment]
Yes, that is a workaround. But it fails a tslint check (no-inferrable-types) which leads to the compiler fighting with the linter (in fact that is how we found the issue).

And it is counterintuitive in any case. At minimum I think this needs a more descriptive error message.

**Comment by mhegazy** [comment]
The error message is not the issue. the type of the property is. it is a bit late to figure this out when the compiler is checking assignable to issue a different error.

I would recommend changing the tslint rule to exclude readonly properties and constants.

**Comment by gmoothart** [comment]
`boolean` is the only primitive that exhibits this automatic narrowing behavior, right?

**Comment by mhegazy** [comment]
`number`, `string` and `boolean`.

**Comment by evmar** [comment]
Is it intentional that you can overwrite a `readonly` property?

**Comment by vladima** [comment]
yes but only inside the constructor

**Comment by ajafff** [comment]
> But it fails a tslint check (no-inferrable-types) which leads to the compiler fighting with the linter (in fact that is how we found the issue).

@gmoothart can you open an issue in tslint's bug tracker? I'll take care of that problem. 
https://github.com/palantir/tslint/issues
