### ISSUE TITLE
Build Action: None setting ignored in Visual Studio.NET 2017 RC4

### ISSUE THREAD

**Issue by deastr** [Microsoft/TypeScript#14410]
**TypeScript Version:**  2.1 (which comes with VS.NET 2017)

I have the following TS file:

```
    export class BaseSearchResponse extends BaseResponse {
        
        public Page: number = 0;
        
        public TotalPageCount: number = 0;
        
        public TotalRecordCount: number = 0;
        
        public Results: Array<Object> = new Array<Object>();
        
    }

```

which is set to "`Build Action: None`" in VS.NET. CSPROJ file:

```
...
<ItemGroup>
    <Content Remove="wwwroot/Application\Models\Generator\BaseSearchResponse.ts" />
...
```

When I build solution I get the following error:

`TS2304	Cannot find name 'BaseResponse'.	Identity.Management.Web.UI (tsconfig project)	D:\Projects\KYSV3\Source\Identity.Management\Identity.Management.Web.UI\wwwroot\Application\Models\Generator\BaseSearchResponse.ts`

Here's my `tsconfig.json`:

```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [ "es2015", "dom" ],
    "suppressImplicitAnyIndexErrors": true
  },
  "exclude": [
    "node_modules",
    "wwwroot/Scripts/TypeScriptDefinitions"
  ]
}
```

Why do I have a file with obviously errorenous code? I'm using TypeWriter VS.NET extension to generate TS model classes from CS model classes. Since TypeWriter can't produce single output file I generate seperate files for each class and merge them using Gulp. This method was working in VS.NET 2015 Update3.

**Comment by mhegazy** [comment]
do you have an `import`/ `/// <reference ... />` to the file in your project?

**Comment by deastr** [comment]
@mhegazy I don't have either

```
Find all "<reference", Subfolders, Keep modified files open, Find Results 1, Current Project: Identity.Management\Identity.Management.Web.UI\Identity.Management.Web.UI.csproj, ""
  D:\Projects\KYSV3\Source\Identity.Management\Identity.Management.Web.UI\wwwroot\Scripts\TypeScriptDefinitions\kendo.all.d.ts(3):/// <reference path="jquery.d.ts" />
  Matching lines: 1    Matching files: 1    Total files searched: 2217
```

```
Find all "(import {).*BaseSearchResponse", Regular expressions, Subfolders, Keep modified files open, Find Results 1, Current Project: Identity.Management\Identity.Management.Web.UI\Identity.Management.Web.UI.csproj, ""
  Matching lines: 0    Matching files: 0    Total files searched: 2217
```

**Comment by billti** [comment]
If you are using a tsconfig.json file, then the build settings (i.e. which files to exclude from compilation) should be specified in there. It doesn't uses the settings on the items in the MSBuild file.

**Comment by deastr** [comment]
@billti : That did the trick, thank you.
