### ISSUE TITLE
nested class declaration

### ISSUE THREAD

**Issue by farfromrefug** [Microsoft/TypeScript#14413]
I am trying to write a declaration file for the Titanium Mobile framework.
To do so i need to declare nested classes. Let me explain
In the Titanium mobile javascript environnement you have a global var ```Titanium```
it would look like something like this:
```typescript
declare module titanium {
    class Proxy extends EventEmitter {}
    class Module extends EventEmitter {}
    class View extends Proxy {}
    class TitaniumModule extends Module {
        UI: UIModule
    }
    class UIModule extends Module {
        View = View
    }
    export var Titanium: TitaniumModule
}
```
The idea is that you can do: 
```typescript
Titanium.UI.on('event', function() {}) ///eventEmitter
```
as well as
```typescript
var view = new Titanium.UI.View();
```

The example i wrote for the declaration file does not work because of the error ```Initializers are not allowed in ambient contexts``` for all nested class declarations.
I also can't make Titanium.UI a namespace because then i cant have it extend ```Module``` and thus ```EventEmitter```

Is there a way achieve this right now?
I saw [that](http://stackoverflow.com/a/17459565/993813) trick but it does not seem to work anymore.

It seems that it could be achieved if i was actually writing the objects and not just the declaration file, using static nested classes (thus the title). Could be added as a feature in a ```.d.ts``` file?

**Comment by mhegazy** [comment]
`npm install @types/titanium`?
[to download titanium's declaration file](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/titanium/index.d.ts) ?

**Comment by farfromrefug** [comment]
@mhegazy the issue is not about about getting the definition ;) The definition is wrong!
I also maintain my own for Ti which automatically build the definition file.

And that definition file you pointed has that exact issue i am talking about.

**Comment by farfromrefug** [comment]
@mhegazy you closed it? I don't see it as fix. Nor do i see a workaround for this.
Can you just explain a bit?
Thanks

**Comment by j-oliveras** [comment]
@farfromrefug This is not an Typescript issue, if the definition is wrong open an issue to [DefinitelyTyped/DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) (this is the repository from is generated the @types/titanium definitions).

**Comment by farfromrefug** [comment]
@j-oliveras The definition is not wrong! It's just that you can't do with typescript what we need for the definition to be correct...
That's what i explained in this issue.

**Comment by basarat** [comment]
`        View = View` should be ` View: View`

Complete : :rose:
```
declare module titanium {
    class Proxy extends EventEmitter {}
    class Module extends EventEmitter {}
    class View extends Proxy {}
    class TitaniumModule extends Module {
        UI: UIModule
    }
    class UIModule extends Module {
        View: View
    }
    export var Titanium: TitaniumModule
}
```
In this case I think TypeScript is preventing you from using invalid syntax ❤️

**Comment by farfromrefug** [comment]
@basarat It does not work. If i try your way i can't do ```var view = new Titanium.UI.View();```

**Comment by basarat** [comment]
Sorry. Change `View: View` to `View: typeof View`. More https://basarat.gitbooks.io/typescript/content/docs/types/moving-types.html :rose:

**Comment by farfromrefug** [comment]
@basarat It works !
Thank you so much for this.
Now i think we can close that issue

**Comment by farfromrefug** [comment]
@basarat actually it does not fully work.

i can do
```Titanium.UI.on('event', function() {})```
or
```var view = new Titanium.UI.View();```

but i can do
```
class A {
   variable:Ti.UI.View
   aFun(view:Ti.UI.View) {
}
}
```
It says ```cannot find namespace Ti```
```Ti``` is indeed not a namespace but a ```titanium.TitaniumModule```.
Can it be solved?

Thanks
