### ISSUE TITLE
Methods are missing on the union of two instantiations of the same generic type

### ISSUE THREAD

**Issue by JsonFreeman** [Microsoft/TypeScript#1442]
Our design for processing calls on union types, is that in order for a call signature to appear on the union, it must be present (and identical) for all constituents. The reason is that there is no clearly correct way to merge two arbitrary groups of overloads. However, when the constituents are instantiations of the same generic type, the overloads will have come from the same place, and the user expects will expect them to be merged. For example, if we have `string[] | number[]`, we expect that to have a forEach method with one signature, instantiated at `string | number`, just like pop does. But instead we get an error that forEach is not callable. In fact, any method that T appeared in is uncallable.

```ts
var strings: string[];
var numbers: number[];

(strings || numbers).pop(); // Works
(strings || numbers).push(null); // Error that push is not callable
(strings || numbers).concat([]); // Error that concat is not callable
(strings || numbers).forEach(x => x); // Error that forEach is not callable


// These both destroy the well-typedness of the arrays, but are allowed.
// This is just a consequence of the covariance of indexers.
(strings || numbers)[0] = "";
(strings || numbers)[0] = 0;
(strings || numbers)[0] = 0 || "";
```

I'm not sure there is a good solution here, but one thing we could do is make the error better. We should indicate that the method wasn't missing, it was just unioned away.

This behavior is also a breaking change from 1.0.

**Comment by ahejlsberg** [comment]
We can't just union together the argument types because the resulting signature would allow non-uniform mixing. For example, for `string[] | number[]` we'd end up with a `push(...items: (string | number)[])` which would allow you to pass a mix of string and numbers. That's clearly not correct.
