### ISSUE TITLE
Invalid `Not all code paths return a value` error

### ISSUE THREAD

**Issue by onury** [Microsoft/TypeScript#14429]
**TypeScript Version:**  2.2.1 

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
import * as _ from 'lodash';
function find(obj, word:string):string {
    let found:string;
    _.each(obj, (val:string, key:string) => { // —> TS complains for this line
         if (val === word) {
            found = key;
             return false;
        }
    });
    return found;
}
find(someObj, 'foo');
```

**Expected behavior:**
No complaints/errors/
**Actual behavior:**
TS complains for the marked line (@ `_.each()` method) 
lodash's `_.each()` breaks the loop if returned `false`.
TS complains: `Not all code paths return a value`.

**Comment by mhegazy** [comment]
you have `noImplicitReturns` set, which tells the compiler to make sure all functions have an "explicit" return value. the callback has a condition, and only one return statement. if `val == word` evaluated to `false` this function will implicitly return `undefined`.
either add an explicit return statement to your function, or disable the `noImplicitReturns` check.

**Comment by onury** [comment]
Yes I avoid it by returning `undefined`. But should be noted. Thanks.
