### ISSUE TITLE
Generator .throw() causes a "Object is possibly 'undefined'" error during compilation with strictNullChecks is enabled

### ISSUE THREAD

**Issue by dsole** [Microsoft/TypeScript#14431]
**TypeScript Version:**  2.1.1

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
function* myGen() {
  yield "foo";
}

let gen = myGen();

gen.throw(new Error("err"));
```
Compiled with the command
`tsc --strictNullChecks --target ES6 example.ts`

**Expected behavior:**
Compilation passes successfully.

**Actual behavior:**
example.ts(8,1): error TS2532: Object is possibly 'undefined'.

The error is on the gen.throw() line.
I have already tried putting undefined checks, assigning a local variable, trycatch blocks etc in the code but the error persists.

**Comment by dsole** [comment]
The error is resolved if I do wrap the `gen.throw()` line with a check for gen.throw

```ts
if (gen.throw) {
  gen.throw(new Error("err"));
}
```

Is there a valid case where the throw function would _not_ exist on a generator ?

**Comment by dsole** [comment]
I'll raise this as a question on SO rather than a bug here.
I see that the Iterator declaration has the throw and return functions marked as optional.

```ts
interface Iterator<T> {
    next(value?: any): IteratorResult<T>;
    return?(value?: any): IteratorResult<T>;
    throw?(e?: any): IteratorResult<T>;
}
```

**Comment by rclmenezes** [comment]
I dislike this behavior in TypeScript. All generators *can* raise an exception and all of them *do* return something. 

Instead, why not make generators return a new interface that extends Iterator? This way, we can make `return` and `throw` required fields:

```
interface GeneratorIterator<T> extends IterableIterator<T> {
    return(value?: any): IteratorResult<T>;
    throw(e?: any): IteratorResult<T>;
}
```

[True, the ECMA2015 schema says](http://www.ecma-international.org/ecma-262/6.0/#sec-iteration):

> A Generator object is an instance of a generator function and conforms to both the Iterator and Iterable interfaces.

However, I'd argue that an extension of Iterator still conforms to Iterator!

This change would be less confusing for newcomers using `strictNullChecks`. Currently, you have to do a hack like:

```
const iter = gen();
if (iter.throw) {
    iter.throw();
} 
```

Thanks!
