### ISSUE TITLE
Can not override 'toString' method of a mix-in class

### ISSUE THREAD

**Issue by spacemeowx2** [Microsoft/TypeScript#14439]
**TypeScript Version:**  2.2.1

**Code**

```ts
type Constructor<T> = new(...args: any[]) => T
function Tagged<T extends Constructor<{}>>(Base: T) {
  return class extends Base {
    _tag: string;
    constructor(...args: any[]) {
      super(...args)
      this._tag = ''
    }
  }
}

class A {
  toString () {
    return 'class A'
  }
}

class B extends Tagged(A) {
  // error TS2425
  toString () {
    return 'class B'
  }
}

class C extends A {
  toString () {
    return 'class C'
  }
}
```

**Expected behavior:**
No error.

**Actual behavior:**
error TS2425: Class 'Tagged<typeof A>.(Anonymous class) & A' defines instance member property 'toString'
, but extended class 'B' defines it as instance member function.

**Comment by govis** [comment]
Same here - it won't allow derived class to override any method that exists in both base class and the mixin. A workaround would be highly appreciated.

**Comment by RyanCavanaugh** [comment]
We should be treating *apparent* properties as if they were on the prototype (because they are)

**Comment by Kingwl** [comment]
it's very helpful to me!
