### ISSUE TITLE
Resolving .d.ts definition files in Visual Studio.NET 2017 RC4

### ISSUE THREAD

**Issue by deastr** [Microsoft/TypeScript#14433]
**TypeScript version:** 2.1.5

I have an Angular 2 project which uses definition files like `jquery.d.ts` and my own `shims.d.ts`:

`declare var module: any;`

The definition files were automatically used in VS.NET 2015 without referencing them in TS files. But now in VS.NET 2017 RC4 I'm getting `TS2304 Cannot find name '$'` and `TS2304 Cannot find name 'module'` errors. The errors stop if I add reference to definition files. Is this expected behaviour or am I doing something wrong or is something amiss?

Here's a sample file:

```
@Component({
    selector: 'kdys-field-update',
    templateUrl: 'Update.html',
    moduleId: module.id, // <--error
    providers: [FieldService]
})
export class FieldUpdateComponent extends BaseComponent {
    ...
    ngAfterViewInit() {
        $(this.tabStrip.nativeElement).kendoTabStrip();  // <--error
    }
}
```

My `tsconfig.json`:

```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [ "es2015", "dom" ],
    "suppressImplicitAnyIndexErrors": true
  },
  "exclude": [
    "node_modules",
    "wwwroot/Scripts/TypeScriptDefinitions"
  ]
}
```

Definition files are located in `wwwroot/Scripts/TypeScriptDefinitions`.

**Comment by billti** [comment]
If your definition files are located in `wwwroot/Scripts/TypeScriptDefinitions`, and you want them to be automatically included without referencing them, why have you listed that folder under the `exclude` setting in your `tsconfig.json`?

**Comment by deastr** [comment]
@billti : I was using the `exclude `setting because I didn't want them to compiled but it seems I've misunderstood this settings purpose. I've removed it and I'm not getting any errors. Thank you.
