### ISSUE TITLE
ES6 re-export breaks circular dependencies

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/TypeScript#14434]
TS version 2.2.1

``` ts
// entry.ts
import * as a from './a'
console.log('entry', { a })
import * as b from './b'
console.log('entry', { b })
```

``` ts
// a.ts
import * as b from './b'

console.log('a', { b })

export const Foo = 'Foo'
```

``` ts
b.ts
export * from './a'

export const Bar = 'Bar'
```

When I run `tsc --outDir target entry.ts && node entry.js`, the output is:

```
a { b: { __esModule: true, Bar: 'Bar' } }
entry { a: { __esModule: true, Foo: 'Foo' } }
entry { b: { __esModule: true, Bar: 'Bar' } }
```

I expected both modules, a and b, logged from `entry` to include the `Foo` exported property, however this is only the case for `a`.

**Comment by OliverJAsh** [comment]
Just tested the same code with babel and it seems to work. The output becomes:

```
a { b: { Foo: [Getter], Bar: 'Bar' } }
entry { a: { Foo: 'Foo' } }
entry { b: { Foo: [Getter], Bar: 'Bar' } }
```

The circular dependency works because `Foo` is evaluated lazily.

**Comment by yortus** [comment]
I think this and #12522 share the same cause, namely the eager evaluation of re-exports (which should be lazy like they are in Babel).
