### ISSUE TITLE
npm run build:compiler is failing

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#14432]
Errors along the lines of `Accessors are only available when targeting ECMAScript 5 and higher.` in `transformer.ts`
Example build : https://travis-ci.org/basarat/byots/builds/207254271#L807

As always :heart: :rose:

**Comment by HerringtonDarkholme** [comment]
I guess TS' compiler target can be bumped to "ES5"? Because TS already uses `Object.create`.

**Comment by mhegazy** [comment]
Not sure which command is failing. i can not see this locally. they all should be targeting ES5.

**Comment by basarat** [comment]
> Not sure which command is failing. i can not see this locally. they all should be targeting ES5.

I was simply running `./prepare.sh` https://github.com/basarat/byots/blob/b500c26b6c92ca8318ff0dc8127061048669e01d/prepare.sh#L12-L27. Somehow it ended up picking the wrong tsconfig.json. Sorry for the invalid issue :rose:  Fixed with https://github.com/basarat/byots/commit/3abd451503c80bbe13aa279a4b972146a4a9e669#diff-3a9c05fa57212221e20e8fefb20fb9deR3 in my automation (😞  in myself ... and unable to figure out how it could happen ... but that's a problem in my repo)
