### ISSUE TITLE
TS server - call tsc programmatically from Node.js server

### ISSUE THREAD

**Issue by ORESoftware** [Microsoft/TypeScript#14449]
I have the following command, which I run in a new child process, and which will transpile a single file:

```bash
tsc --skipLibCheck --noResolve --jsx react --module amd --target es5 /foo/bar/baz
```

I am looking to speed this up by 500ms. This command probably takes 300ms to warm up and run. I can probably do this if I can issue this command programmatically from a pre-running process (a.k.a server).

Is there a way to call tsc programmatically from inside a Node.js server? This is the feature I am looking for - calling tsc programmatically instead of from the command line.

**Comment by ORESoftware** [comment]
The problem with tsc -w is that is transpiles all the .ts/tsx files in my project upon a change to only one file. In this case I only want to transpile the one file that changed.

**Comment by ORESoftware** [comment]
Should I write my own using this:

https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API

?

**Comment by RyanCavanaugh** [comment]
The docs you found describe how to do what you want to do. The `ts.transpile` function will likely be the fastest possible way to transform a single file

**Comment by ORESoftware** [comment]
@RyanCavanaugh thanks, I will work with those docs
