### ISSUE TITLE
Nested contextually sensitive function expressions cause early fixing in overload resolution

### ISSUE THREAD

**Issue by JsonFreeman** [Microsoft/TypeScript#1444]
Our ordering scheme for type argument inference defers contextually typed lambdas so that we don't fix type parameters too early. However, it does not work for nested functions.

```ts
declare function foo1<T>(xx: (xx: T) => void, yy: T);
foo1(x => x.length, ""); // We appropriately defer the lambda until after the ""

declare function foo2<T>(xx: (xx: string) => (xx: T) => void, yy: T);
foo2((x1: string) => x2 => x2.length, ""); // We do not defer the lambda and x2 is {}
```

**Comment by mhegazy** [comment]
Assuming we want to do this, we will need to also consider cases where the lambda body contains other statements, which can grow complex and expensive quickly. Closing it for now.
