### ISSUE TITLE
Add -ifChanged option to tsc

### ISSUE THREAD

**Issue by mihailik** [Microsoft/TypeScript#14453]
As TSC resolves the graph of inputs, it can collect timestamps on file and compare with output[s] timestamp[s].

Currently this check needs to be done in external tooling, and cannot be very precise (indeed there were [bugs in TS build dependency calculation](https://github.com/Microsoft/TypeScript/commit/efcca8ce468d2245faa087e30255cb99f4e89479) itself!)

TSC is in the best position to know the full dependencies/outputs graph -- and can skip emit if outputs are younger than inputs.

**Comment by mhegazy** [comment]
covered by https://github.com/Microsoft/TypeScript/issues/10879
