### ISSUE TITLE
Difference in runtime behavior of decorators between commonjs and either systemjs or amd

### ISSUE THREAD

**Issue by jeremythuff** [Microsoft/TypeScript#14455]
**TypeScript Version:**  2.1.6
```
function myDecorator(decorated : any) : void {
    console.log(decorated);
}

@myDecorator
class MyClass {}
```

**Expected behavior:**
When transpiled to es5 using any of the module strategies, the log statement will be reached when code is run. No instantiation of the class is necessary. The behavior should be identical no mater what module strategy has been employed.

**Actual behavior:**
In commonjs the log occurs at runtime as is. In systemjs and amd the whole thing resides in the describe or register and block and the log statement is not run without instantiation of the class.

Here is SO [question ](http://stackoverflow.com/questions/42593432/typescript-decorators-in-systemjs-or-amd)based on this

**Comment by mhegazy** [comment]
But these are the semantics of SystemJs and AMD modules. the module is not executed until it is loaded. hence the "A" (Asynchronous) in AMD.
