### ISSUE TITLE
Is there a way to compile as script?

### ISSUE THREAD

**Issue by fatcerberus** [Microsoft/TypeScript#14456]
`ts.transpileModule()` is documented to treat all input as a module.  I'm trying to use the TS API in my toolchain as an ES6 transpiler for `.js` files, however there doesn't seem to be a way to transpile plain scripts, only modules.  This is a dealbreaker and forces me to use Babel, which is a lot slower.

The Compiler API doesn't seem to be well-documented - so I'm asking here, what do I have to do to the TS compiler API to treat input as script code?

**Comment by fatcerberus** [comment]
For now I managed to fake a top-level script by providing a global `exports` binding in my environment (which maps to the global object) and passing `noImplicitUseStrict` to the transpiler.  This seems to be fully compatible.  But of course it would be cleaner and less hacky if there were a real compile-as-script option.

**Comment by mhegazy** [comment]
what do you mean by "script"? do you have an `export` / `import` in your file?

**Comment by mhegazy** [comment]
I see the issue now. this is a bug.

**Comment by fatcerberus** [comment]
By script, I meant global code, i.e. the way a browser would treat the file.  `var` at top level goes to global object, etc.

**Comment by mhegazy** [comment]
Should be fixed by https://github.com/Microsoft/TypeScript/pull/14493. The fix should be in `typescript@next` later tonight
