### ISSUE TITLE
Generic type parameters considered private in protected methods when generating .d.ts

### ISSUE THREAD

**Issue by jctitor** [Microsoft/TypeScript#1445]
The following code fails in TypeScript 1.4 with the below errors:

```
export class MyClass {
    protected myMethod<T>(val: T): T {
        return val;
    }
}
```

Parameter 'val' of public method from exported class has or is using private name 'T'.
Return type of public method from exported class has or is using private name 'T'.

**Comment by danquirk** [comment]
This was broken by 1.4, it worked in 1.3.

**Comment by bluong** [comment]
We have an issue arising from the fact that this worked in 1.3 but not in 1.4.  Is it possible for a fix for this to be made for the 1.4 release.  Otherwise, we're gonna have a back-compat break.

**Comment by RyanCavanaugh** [comment]
Referenced PR got cherry-picked into 1.4

**Comment by derekcicerone** [comment]
Awesome, thanks for the quick fix!
