### ISSUE TITLE
No Circular Dependency Compile Time Warnings on Imports

### ISSUE THREAD

**Issue by AcousticGuitar** [Microsoft/TypeScript#14469]
**TypeScript Version:**  2.1.5.0

**Code**

```ts
/// module A has an import requiring moduleB
import MA = require("../scripts/moduleB");

///module B  is requiring moduleA
import MB = require("../scripts/moduleA);

```

**Expected behavior:**
Compile should fail because of the circular dependency.
**Actual behavior:**
Compile works fine, but at runtime, the content of one of the modules is never injected by require. 
This is documented [here.](https://github.com/Microsoft/vss-web-extension-sdk/issues/31)

**Comment by RyanCavanaugh** [comment]
Most module systems allow this without error. We can't disallow it just because some module loaders are limited in this regard.

**Comment by AcousticGuitar** [comment]
Hi Ryan I never suggested disallowing it, rather a warning could be helpful.
