### ISSUE TITLE
Typescript 2.2 introduces breaking change to Map interface's set() method in lib.es2015.collection.d.ts

### ISSUE THREAD

**Issue by BurtHarris** [Microsoft/TypeScript#14476]
**TypeScript Version:**  2.2.1 
A change to the declaration interface `Map` introduced a breaking change, was this intended?
 
**Code**

```ts
function copyMapKeys(map: Map<string,string>, keys: string[]): Map<string,string> {
    const result = new Map<string, string>();
    for (var k in keys) { 
        result.set(k, map.get(k));
    }
    return result;
}
```

**Expected behavior:**
Compile w/o error

**Actual behavior:**
Generates error message *"Argument of type 'string | undefined' is not assignable to parameter of type 'string'."*

** Note ** 
This seems to be because the "?" optional flag was removed from the `set` method's `value` parameter in **lib.es2015.collection.d.ts**.   I'm not sure if this was by design or not.

**Comment by RyanCavanaugh** [comment]
Isn't this error correct? The Map does not accept `undefined` values but there's no guarantee that the `keys` array only contains actual keys from the source Map.

**Comment by BurtHarris** [comment]
Thanks Ryan.   Frankly I wasn't sure.   We've previously assumed on the fact that setting a Map entry's value to `undefined` behaves like deleting it.   We've updated our code to make the call to `delete` explicit so this certainly isn't a big deal if you think it's by-design.   

I guess you could make the case that docs say says the argument is required, but obviously the semantics of providing it using a expression that can return `undefined` are less than well defined.

References supporting your argument:
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/set 
- https://msdn.microsoft.com/en-us/library/dn280900(v=vs.94).aspx

**Comment by RyanCavanaugh** [comment]
![image](https://cloud.githubusercontent.com/assets/6685088/23719917/f2102572-03f1-11e7-82de-bc5db1a93b2d.png)
