### ISSUE TITLE
Recursive type definition

### ISSUE THREAD

**Issue by tomitrescak** [Microsoft/TypeScript#14478]
Hi, with `keyof` operator we can do really cool thing such as the one from `enzyme`

```typescript
interface MockInstance<T> {
  ....
}

type Mocked<T> = {
    [P in keyof T]: T[P] & MockInstance<T[P]>;
  } & T;
```

This changes every parameter of a type to its mocked version.

I would be interested if it is possible somehow to define that not only parameters of type T are mocked, but also all parameters of types that comprise of parameters of type T.  Thanks.

e.g.

`
class Foo {
}

class Boo {
 f: Foo;
}

class Moo {
 b: Boo;
}
`

if I mock instance of moo, the definition will mark that b is mocked as well as b.f is mocked.

**Comment by aleksey-bykov** [comment]
does #6230 have anything to do with it?

**Comment by aleksey-bykov** [comment]
notoriously #3496
