### ISSUE TITLE
TypeScript 2.2.1 generates surprising null checking error

### ISSUE THREAD

**Issue by BurtHarris** [Microsoft/TypeScript#14487]
**TypeScript Version:**  2.2.1 

Effective type of argument `p` below seems to not match explicit declaration under tsc 2.2.1

**Code**

```ts
interface RuleContext  {
    _parent: RuleContext | undefined;
};

var  _ctx = { _parent: undefined};

function walk( p: RuleContext | undefined = _ctx ) {
    while (p) {
        p = p._parent; // Error w/ "strictNullChecks": true !
    }
}
```

**Expected behavior:**
Compiled w/o error under 2.1
**Actual behavior:**
Generates error:
```
index.ts(9,4): error TS2322: Type 'RuleContext | undefined' is not assignable to type 'RuleContext'.
  Type 'undefined' is not assignable to type 'RuleContext'.
```

**Comment by BurtHarris** [comment]
Simple workarounds possible, just surprised at the change in behavior.

**Comment by RyanCavanaugh** [comment]
We changed the type of defaulted parameters from `T | undefined` to `T` in 2.2, but it seems wrong to strip out `undefined` from an explicitly-written type annotation

**Comment by sandersn** [comment]
This is an intended result of #12033, but we should revisit whether to use the control-flow-narrowing mechanism instead of the one that shipped, which simply strips off `| undefined` from default-initialised and optional parameters.
