### ISSUE TITLE
how can i alter definitions in @types?

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#14483]
my story, i am using postgre so i do:

1. `npm install pg`
2. `npm install @types/pg`
3. `/// <reference types="pg" />`
4. `import * as pg from 'pg'`

problem is that these definitions are imperfect, so i feel urge to go ahead and alter `node_modules/@types/pg/index.d.ts` which is a way to nowhere because these changes will be lost on  next `npm install`

so what steps should i take to get a local copy of **corrected** definitions of `pg` that would work the same way as one in `node_modules/@types/pg` **together** with `node_modules/pg`?

----------------------------------------------------------

what i tried:

- i made a copy of  `./node_modules/@types` to `./my_types`
- added `"typeRoots": ["./my_types"]` to `tsconfig.json`

so `/// <reference types="pg" />` works but `import * as pg from 'pg'` **still doesn't**

![image](https://cloud.githubusercontent.com/assets/937933/23610922/b2db9ee6-0242-11e7-9dd4-86fe018adab5.png)

did i miss something?

-----------------------------------------------------------------

self contained project demonstrating the problem:

[demo.zip.zip](https://github.com/Microsoft/TypeScript/files/821228/demo.zip.zip)

**Comment by mhegazy** [comment]
A quick clarification. `/// <reference types=".."/>` is a for globals, it is not needed for modules. think of this as `import ..` for somthing that is not a module. 

for globals, copy your `@types/foo` => `./my_types/foo` and update `typeRoots` as you noted
For modules, , copy your `@types` => `./my_types` and add a path mapping rule: ` "paths": { "*": [ "my_types/*", "*" ]}`

**Comment by tinganho** [comment]
@mhegazy I think I got the exact problem, though I have tried all the suggestion problem and I think I cannot get it to work.

I'm trying to use [jayson](https://www.npmjs.com/package/jayson). Since, there are no typings for it, I just try to write a custom one in a folder called `Typings`.

```
/Typings
  /jayson
    /jayson.d.ts
Main.ts
tsconfig.json
```

`jayson.d.ts:`
```ts
declare module "jayson" {
	class Jayson {
		client: () => string;
	}
	const jayson: Jayson;
	export = jayson;
}
```

`tsconfig.json:`
```json
{
	"compilerOptions": {
		"module": "commonjs",
		"target": "es6",
		"noImplicitAny": true,
		"sourceMap": false,
		"strictNullChecks": true,
		"outDir": "Build",
		"moduleResolution": "node",
		"typeRoots": [
			"Typings"
		],
		"baseUrl": ".",
		"paths": {
			"*": [
				"Typings/*",
				"*"
			]
		}
	},
	"exclude": [
		"node_modules"
	]
}
```
`Main.ts`
```
import jayson = require('jayson');
jayson.client();
```

I compile it:
```
$ tsc
error TS2688: Cannot find type definition file for 'jayson'.
```

My editor VSCode doesn't show any errors.

**Comment by gcanti** [comment]
@tinganho I'm using the following setup and seems to work fine:

Project folders

```
src
  index.ts
typings
  x.d.ts
```

x.d.ts

```ts
declare module 'x' {
  export function f(): void
}
```

tsconfig.json

```ts
{
  "compilerOptions": {
    "outDir": "./lib"
  },
  "include": [
    "./src/**/*",
    "typings"
  ]
}
```

index.ts

```ts
import * as x from 'x'

x.f() // ok
```

**Comment by aluanhaddad** [comment]
@gcanti that is an ambient external module declaration so it will be available for import, and cause a potential name collision, regardless of path mappings so long as the containing directory is including in the compilation context.
[@types/pg](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/pg/index.d.ts) is just an external module

**Comment by mhegazy** [comment]
@tinganho either name your file as 'jayson/index.d.ts' or add a full path making "jayson":"Typings/jayson/jayson.d.ts"

**Comment by weswigham** [comment]
What I believe is the most ergonomic way to fork `@types` right now is to copy the npm package, upload it to GitHub with your changes, then point the package.json entry for those types are your git repo rather than at npm. Easily upgradable, requires no TS configuration.
