### ISSUE TITLE
Support for Node.js Domain core module .exit() method

### ISSUE THREAD

**Issue by ORESoftware** [Microsoft/TypeScript#14480]
I am seeing this typing problem with `domain.exit()`

as in

`require('domain').create().exit()`

I am certain this method exists, simply does not seem to be supported by a d.ts somewhere.

Can someone verify?

thanks

<img width="536" alt="screenshot 2017-03-05 23 16 16" src="https://cloud.githubusercontent.com/assets/11139560/23600177/16a3d6f8-01fa-11e7-9a0f-340a04eed918.png">

**Comment by ikokostya** [comment]
Node.js type declarations are placed in separate repository https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/node

**Comment by ORESoftware** [comment]
yeah it should have it

https://nodejs.org/api/domain.html#domain_domain_exit

@RyanCavanaugh for the laypeople out there, where should we report this? that's all I need to know and I will take it to the right people. That's why I report it to you, so you can tell me who to report it to. This is just me doing the commune a favor (in theory).

**Comment by RyanCavanaugh** [comment]
The best thing to do would be send a PR, the next best thing is to log an issue :wink:
