### ISSUE TITLE
CLI format should be compatible the GNU Coding Standards

### ISSUE THREAD

**Issue by monolithed** [Microsoft/TypeScript#14482]
TypeScript error line format doesn't appear to be [compatible](https://www.gnu.org/prep/standards/html_node/Errors.html#Errors) with the GNU Coding Standards.

**Actual behavior:**

```
utils/user/info.ts(91,9): 
```

**Expected behavior:**

```
utils/user/info.ts:91:9
```
![cak3zzhxks](https://cloud.githubusercontent.com/assets/803674/23610050/1505005a-0282-11e7-9e31-a3154c917e18.gif)

**Comment by mhegazy** [comment]
The compiler error messages are compatible with [MSBuild error message format](https://blogs.msdn.microsoft.com/msbuild/2006/11/02/msbuild-visual-studio-aware-error-messages-and-message-formats/).

For other tools, the [Compiler API](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API) provides a raw data and it should be straight forward to extract the needed information.

**Comment by monolithed** [comment]
MSBuild error message format is a platform specific format for Visual Studio. The current issue is just a proposal to follow GNU Coding Standards on other platforms where the tsc is available.

**Comment by mhegazy** [comment]
We can not break existing users who have been getting this behavior for so long.

so the only option is to add another output format. not sure if adding multiple formats would be worth the hassle.

I would recommend using the API to integrate with the build tool similar to what [gulp-typescript](https://github.com/ivogabe/gulp-typescript), [broccoli-typescript](https://github.com/tildeio/broccoli-typescript-compiler), [grunt-typescript](https://github.com/k-maru/grunt-typescript), etc..

**Comment by monolithed** [comment]
> We can not break existing users who have been getting this behavior for so long.

How is it possible if the current format is used only by VS? ))

> I would recommend using the API to integrate with the build tool similar to what gulp-typescript, broccoli-typescript, grunt-typescript, etc..

I like the tsc command and I don't see any sense to use Grunt or something else as an alternative...

**Comment by DanielRosenwasser** [comment]
That's an assumption - we've had people relying on the fact that our error messages forwarded to stderr in the past, and when we switched to stdout they were very unhappy. People will come to rely on these patterns.

Why not just wrap the output with sed or something similar to get what you want?

**Comment by monolithed** [comment]
> Why not just wrap the output with sed or something similar to get what you want?

I haven't seen this format before. And I haven't seen any editor (probably only VS) that can work with this format as well.

`:91:9` — is a standard  format for systems are based on POSIX standard
`(91,9):` — is a standard format for Windows system only

That's why I don't see any reason why this format should be on my *nix system.

> Why not just wrap the output with sed or something similar to get what you want?

Why do you not want to do exactly the same thing? 😄

**Comment by RyanCavanaugh** [comment]
Why is the conversation on this repo in English when so many more people speak Chinese? Reasons, man 😃
