### ISSUE TITLE
Gulp won't build Typescript: Permission denied trying to write outside the project directory

### ISSUE THREAD

**Issue by sandersn** [Microsoft/TypeScript#14497]
When I run `gulp local` from project root it fails with "Permission denied, mkdir /media/sandersn/built", which looks like it's trying to write to the path `TypeScript/../../built/local`, where `TypeScript` is the project root.

I blew away my `node_modules` and did `npm install` but the error persisted. #14368 sounds very similar to this bug, except that it's `../..` instead of `~` Any ideas @andy-ms ?

**Comment by andy-ms** [comment]
Should be fixed by #14512.
