### ISSUE TITLE
[Design Spec] ESNext import()

### ISSUE THREAD

**Issue by yuit** [Microsoft/TypeScript#14495]
`import(specifier)` is a newly proposed syntax for dynamically module loading. `import(specifier)` takes an assignment expression as an input (Note: unlike ES6 static import which only allow string literal as [module specifier](https://tc39.github.io/ecma262/#prod-ModuleSpecifier)) and returns a promise of [module namespace object](https://tc39.github.io/ecma262/#sec-module-namespace-objects).

The full proposal can be found [here](https://github.com/tc39/proposal-dynamic-import)
Original issue: #12364

This issue will discuss design proposal for implementing `import()`: parsing, type-checking, and emitting. 

The proposal will NOT include "module namespace object" type  and expressing the shape of the loaded module (To be able to express such type will allow users to cast the result instead of "any" to be what they expected at runtime)...The issue will be discussed and implemented separately.

**Parsing**
`import(specifier)` will be parsed as [CallExpression](https://tc39.github.io/proposal-dynamic-import/#prod-ImportCall). and `specifier` will be parsed as [AssignmentExpression](https://tc39.github.io/ecma262/#prod-AssignmentExpression)

**Error**

- Error if the `module` flag is ES2015.

- Error if `specifier` is not assignable to string type

**Type-checking**

- `specifier` is type checked as string type. (Clarification: the only limitation for `specifier` in original proposal is that it can called `toString()`)
- The return of `import(specifier)` will be as following
-- if known module can be resolved from `specifier`, then we return Promise of module namespace object   
-- if not known module, then we return Promise of any. ~~This will give an error in `noImplicitAny` mode and `import()` is used as an expression~~ After offline discussion with @mhegazy @bowdenk7 @DanielRosenwasser, we think reporting an error without providing a way to easily get out of it (see #14844 for more detail) is undesirable. By casting to `Promise<any>` to satisfy the compiler will not provide users any benefit and arguably is a drawback because if in the future, there is a way to type the module easily, upgrading to use such syntax will not be convenient. Therefore, we will not issue an `noImplicitAny` error with this feature but with #14844 instead.

- We will use existed module resolution logic to try to figure out the module of the dynamic import.

**Emit**
Emit for each different `module` kind emit is outlined below
```typescript
import('blah');
```
- Node
```js
Promise.resolve().then(() => require('blah'));
```

- AMD
```js
define(["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    new Promise(resolve => require(['blah'], resolve));
});
```
- UMD

``` js
(function (factory) {
    if (typeof module === "object" && typeof module.exports === "object") {
        var v = factory(require, exports);
        if (v !== undefined) module.exports = v;
    }
    else if (typeof define === "function" && define.amd) {
        define(["require", "exports"], factory);
    }
})(function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    require.length === 1 ?
        /*CommonJs Require*/ Promise.resolve().then(() => require('blah'));
        /*Amd Require*/ new Promise(resolve => require(['blah'], resolve));
});
```

- System (Updated from [comment](https://github.com/Microsoft/TypeScript/issues/14495#issuecomment-285294096))
```js
System.register([], function (_export, _context) {
  return {
    setters: [],
    execute: () => {
      _context.import('dynamic');
    }
  };
});
```

- ES2018 _new value_
```js
import('blah')
```

**Comment by mhegazy** [comment]
`import` should not be allowed if `--module ES2015`.. we have no way of emitting them correctly.

**Comment by jods4** [comment]
@mhegazy Maybe you should let `import()` passthrough when `--module ES2015`. 
Likely scenario for me here is using a bundler like Webpack that will take care of it (as of webpack 2.2, `import()` is supported).

This behavior is useful and we _need_ a way to generate output with `import()`. If you feel uncomfortable with labeling `ES2015` something that really is an extension thereof, maybe we need a new `ES201?` target.

My interpretation is that `ES2015` is the native, standard, ES module system and I'm not shocked to see the newly approved `import()` inside it, even if it was not strictly speaking in 2015.

**Comment by Igorbek** [comment]
Shouldn't the _'if not known module'_ reflect the possibility of missing module and do not expose `any`?
I'm proposing in this case return `Promise<{} | undefined>`. Then the caller would be responsible to properly check result of the promise.

**Comment by Igorbek** [comment]
Ah, sorry, forgot it would go to failure channel of the promise. Then it should be `Promise<{}>`.

**Comment by mhegazy** [comment]
> @mhegazy Maybe you should let import() passthrough when --module ES2015.
Likely scenario for me here is using a bundler like Webpack that will take care of it (as of webpack 2.2, import() is supported).

this is not valid ES2015 code. even if the engine supports ES2015 modules, `import` is a keyword and it would be an error.

I guess what you are looking for is a `--module ES2018`.

**Comment by mhegazy** [comment]
> Then it should be Promise<{}>.

`{}` is fairly useless.. it will force users to case. `any` is more forgiving, and will allow users to proceed without adding a cast. the `--noImplicitAny` error would help those users interested in stomping out `any`s.

**Comment by Kovensky** [comment]
The emit for Node is slightly incorrect. The `require` should _only_ start after the stack has unwinded, but the example snippet does it synchronously. It should look like:

```js
Promise.resolve().then(() => require('blah'))
```

**Comment by Kovensky** [comment]
@mhegazy the main (existing) implementer of `import()` is webpack, so it would be highly desirable to have a passthrough for it. Currently, TypeScript users are stuck with using the deprecated and, eventually, "worsly typed" `System.import()` method in webpack.

**Comment by mhegazy** [comment]
Would `--module esNext` do? this will pass through `import(..)` as well as `import ..` and `export ..`?

**Comment by Kovensky** [comment]
Yeah, that would definitely do.

**Comment by mohsen1** [comment]
If spec is scheduled for es2018 I thing module=es2018 is better than esNext. Next is relative 😀

**Comment by jods4** [comment]
@mhegazy I think whether you graft it to `--module es2015` or you create a new `--module es2018` doesn't matter much (I could argue for both), as long as we can use it. 👍

**Comment by bmeck** [comment]
Note: import() needs to wait until the stack unwinds prior to doing any eval.

For node it is also important to note that CJS modules only produce a `default` export according to the rewritten proposal:

```js
Promise.resolve().then(() => {
  return {default: require('blah')}
});
```

**Comment by mhegazy** [comment]
CJS modules returning a `default` is an orthogonal issue. it applies to all ES6 import forms as well. this is tracked under https://github.com/Microsoft/TypeScript/issues/8687, and should be done around the time the node ES6 module implementation is starting to solidify.

**Comment by yuit** [comment]
Thanks all for the feedback. I have updated the spec accordingly. I decided that to introduce new flag since the syntax is not ES2015 valid

**Comment by mhegazy** [comment]
@yuit, For UMD modules, `function.length` is an ES5 feature, so i do not think we can use that. so we will have to use the boolean flag instead, or come up with another alternative.

**Comment by guybedford** [comment]
Just to mention here, the transform for System.register should be the following:

```javascript
import x from 'x';
import('dynamic').then(...);
// ->
System.register(['x'], function (_export, _context) {
  var x;
  return {
    setters: [X => x = X.default],
    execute: () => {
      _context.import('dynamic').then(...);
    }
  };
});
```

This has been supported as of SystemJS 0.20 and is included in the Babel transformer.

**Comment by Kovensky** [comment]
@mhegazy If you consider that there never was a pre-ES5 implementation of commonjs, it should be safe to rely _specifically_ on `require.length === 1`. If it's `undefined` or otherwise different than `1`, you're either running on ES3 (for which there are no commonjs implementations) or on AMD.

**Comment by mhegazy** [comment]
@Kovensky you are correct. i was wrong. `function.length` should be fine to use.

**Comment by Igorbek** [comment]
Sorry for bringing this once again, but I didn't really get the reason why unresolved module will end up being `any`.
My understanding is that a dynamic module loading feature will be used in two major ways:
1. module specified explicitly as a string literal (in form of module specifier in `import from`) or string constant expression (or, I'm not sure, as a union of string literal types)
    - in that case module can be resolved statically and TS can reason about this and give more specific type of the module like it does this for static module binding now
    - it has very limited set of usage scenarios (I can think of just module splitting with lazy loading)
2. module specified as a dynamic expression which can be resulted in some string in runtime.
    - that case, to me, is going to be much common; it covers scenarios where modules are loaded as a result of some runtime module name calculation (plugins, configuration, use demand, ...)
    - it is common, that a module consumer expects a module with a specific contract and need to perform some duck-type checking to be sure that module is actually what was expected

My claim is that supplying _unknown_ modules with type `any` would result in too permissive modules.
Moreover, with `noImplicitAny` there's no legal way to allow such _unknown_ modules and not get "implicit any" error, isn't it? Having `{}` as a module type would allow type asserting in the way that module consumer needs without possibility to be poisoned by any.

**Comment by mhegazy** [comment]
this is already the behavior today, a module that does not exist, but a .js file for it existed is resolved as `any`. i do not see why this is any different.

**Comment by Igorbek** [comment]
I do see, actually. The behavior today assumes the static binding to done where the module specifier is known at compile time. With `import`, that is by design to have a module specifier to not be known at compile time.

So, to be more practical, it comes up to a question: how can I avoid "implicit any" error under `noImplicitAny` with a code like this:
```ts
const module = await import(dynamicallyReceivedPluginModule);
```

**Comment by mhegazy** [comment]
Ah, you should be able to cast to suppress the noImplicitAny error:

```ts
const module = await import(dynamic) as any;
```

Potentially we could allow `import<T>(...)` as sugar as well.

Another part of this change would be to enable some sort of syntactic form to express a module shape.. e.g. `import (....) as moduleof "./blah"`. or `import<moduleof "./blah">(...)`.

**Comment by Igorbek** [comment]
ok, got it. It may work. Thanks for clarification.

**Comment by jods4** [comment]
The following seems more natural?
```ts
const module: any = await import(dynamic);
```
That's how I fix "implicitely any" errors when they are intended: by adding the type declaration.

**Comment by mhegazy** [comment]
if we assume it is a contextual-type-able then sure.

**Comment by yuit** [comment]
@Igorbek Thanks for raise your concern. To be clear here, the PR addressing this issue will not involve way to express module shape.... I will open a separate issue where we can devote the entire discussion on how to express such concept

**Comment by dasa** [comment]
I don't think "blah" should be passed to `define` as a dependency in the AMD output.

**Comment by yuit** [comment]
@dasa thanks for catching this. You are correct.

**Comment by SaschaNaz** [comment]
I think using `import('blah')` with `--outFile` and `--module systemjs` should just emit `System.import('blah')` for migration like #12473. Is this already considered?

```ts
// older-namespace.ts
// namespace-based code which will eventually migrate to module-based code
namespace Foo {
  export async function foo() {
    const blah = await import('blah.js'); // should be System.import
  }
}

// blah.ts
// already migrated module
export function blah() {}
```

**Comment by olmobrutall** [comment]
Hi guys, 

I'm having problems using `esnext` as a replacement of `commonjs` that will preserve `import` for webpack. 

This is the issue: https://github.com/Microsoft/TypeScript/issues/16820
