### ISSUE TITLE
Handle Objects with a toString method implemented

### ISSUE THREAD

**Issue by ORESoftware** [Microsoft/TypeScript#14502]
Looks like TS has a bug or can be improved here -

I am using an event emitter (NodeJS) like so:

```js
const EE = require('events');

const ee = new EE();

const obj = {
  foo: 'bar',
  toString: function(){           
       return 'all dogs go to heaven';
  }
}

ee.emit(obj);   // in the node.js core codebase for EventEmitter, toString() will be called on obj

```

What's happening is it's saying ee.emit doesn't take an object like this - but with the `toString` method defined, `ee.emit `should actually accept it. Sometimes TS can do inference sometimes it can't.

I am 99% certain this is a bug or deficiency. I am not sure which party would be responsible for updating a d.ts somewhere, but would be happy to help out if this an actual bug or whatever. Not sure if it's possible to inspect objects like this to see if they have a toString method implemented, so might be asking too much, especially considering the object is not typed with TS.

Maybe the answer is that I should type it with TS.

In the image below, you can see that `events.NODE_VERSION` is being passed to `ee.emit`. In this case, `events.NODE_VERSION` has the same signature as `obj` above.

<img width="1095" alt="screenshot 2017-03-07 00 14 40" src="https://cloud.githubusercontent.com/assets/11139560/23648409/72ed91bc-02cf-11e7-89de-2889ac0ce84d.png">

**Comment by RyanCavanaugh** [comment]
The function should be declared with a signature like this:
```ts
declare function log(x: string | { toString(): string }): void;
```
