### ISSUE TITLE
Function arrays emitted incorrectly in .d.ts files

### ISSUE THREAD

**Issue by jctitor** [Microsoft/TypeScript#1451]
In TypeScript 1.4, given the following input
```
export var stuff = <{
    doStuff(fns: { (val: any): any }[]): void;
}> null;
```
the generated .d.ts file uses the syntactically incorrect function arrow notation.
```
export declare var stuff: {
    doStuff(fns: ((val: any) => any)[]): void;
};
```

**Comment by mhegazy** [comment]
The syntax is valid on a 1.4 compiler, and the change would not be simple. closing for now.
