### ISSUE TITLE
"Rename Symbol" should not rename shorthand property names

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#14514]
_From @geon on March 7, 2017 8:37_

- VSCode Version: 1.10.1
- OS Version: macOS 10.12.3 

Steps to Reproduce:

1.

    const foo = 'foo';
    const bar = {foo};

2. Try renaming the symbol `foo`. It will change the property name in the object `bar` as well, which is semantically different, not just cosmetically.

Result:

    const newName = 'foo';
    const bar = {newName};

Expected result

    const newName = 'foo';
    const bar = {foo: newName};

_Copied from original issue: Microsoft/vscode#22133_

**Comment by normalser** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/12007

**Comment by mjbvz** [comment]
Thanks @normalser!

Closing as duplicate of #12007
