### ISSUE TITLE
Users shouldn't need 'noImplicitThis' on to benefit from 'ThisType<T>'

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#14518]
From #14141:

> * Otherwise, **if `--noImplicitThis` is enabled** and the containing object literal has a contextual type that includes a `ThisType<T>`, `this` has type `T`.

Is there a reason that users need `noImplicitThis` on to benefit from `ThisType<T>`? This seems unnecessarily restrictive, especially given that we want to give better support in JS files.

**Comment by ahejlsberg** [comment]
@DanielRosenwasser There are multiple new inferences made for `this` in #14141 and, except for the one where we look for a `ThisType<T>` in the contextual type, they are breaking changes. I suppose we could consider *always* applying the `ThisType<T>` rule but not applying the other two rules unless `--noImplicitThis` is enabled. Is that what you are suggesting? It seems odd to separate it like that. Or are you suggesting that we should always strongly type `this` and live with the breakage?

**Comment by DanielRosenwasser** [comment]
> I suppose we could consider *always* applying the `ThisType<T>` rule but not applying the other two rules unless `--noImplicitThis` is enabled. Is that what you are suggesting?

Yup, sounds like what I had in mind. The thing is that we need to enable this logic for Salsa users anyway, and if a library author wrote `ThisType<T>` somewhere, they probably meant to use it.

I suppose there is a chance that library authors using the `ThisType` type could potentially break existing code that relies on `this` being typed as `any` within methods, but I do wonder how often that comes up in practice.

**Comment by ahejlsberg** [comment]
Indeed, even `ThisType<T>` might break existing code. So each of the new inferences in #14141 is potentially a breaking change. But treating `ThisType<T>` differently just seems really confusing. Users don't really care *how* the type of `this` got inferred, they just care whether it is strongly typed or not. I think we either stick with the current scheme (my preference) or we take the breaking change and always have strongly typed `this`.

**Comment by RyanCavanaugh** [comment]
Doesn't really seem worth a breaking change
