### ISSUE TITLE
Generated typings private variables always any

### ISSUE THREAD

**Issue by yesman85** [Microsoft/TypeScript#14525]
**TypeScript Version:**  2.1.6

**Code**

```ts
class Test 
{
	private _test: string;
	public test: number;
	
	constructor(a: number)
	{
		
	}
}
```

compile with command: tsc --declaration test.ts

**Expected behavior:**
```ts
declare class Test {
    private _test: string;
    test: number;
    constructor(a: number);
}
```

**Actual behavior:**
```ts
declare class Test {
    private _test;
    test: number;
    constructor(a: number);
}
```

Types for private variables are omitted, I understand the reasoning but I believe this recently changed and there doesn't seem to be an option to add the types to privates.

**Comment by RyanCavanaugh** [comment]
> I understand the reasoning but I believe this recently changed

This hasn't ever been the case.

**Comment by yesman85** [comment]
OK I was under the impression I did do that but after trying with 1.8  see the same behaviour.
