### ISSUE TITLE
intellisense shows 'any' type for instance of classes with jsDoc's @param tag added to their constructor.

### ISSUE THREAD

**Issue by GrenouilleToxique** [Microsoft/TypeScript#14532]
**TypeScript Version:**  2.1.1 (vscode version : 1.10.1)

**Code**

```ts
class Foo {
	/**
	 * Creates an instance of Foo.
	 * @param {string} bar 
	 */
	constructor(bar) {}
}

let myFoo = new Foo();
```
Then trigger intellisense for myFoo.

**Expected behavior:**
intellisense should show myFoo: Foo

**Actual behavior:**
intellisense shows myFoo: any

**Comment by GrenouilleToxique** [comment]
Nevermind, it was because constructor was called without the 'bar' arg (7am here... ^^). Closed

**Comment by RyanCavanaugh** [comment]
We're trying to do this (return `any` in the presence of errors) less often, so we should fix this

**Comment by mhegazy** [comment]
seems fixed in latest.
