### ISSUE TITLE
doc/spec.md: AmbientLexicalDeclaration is undefined

### ISSUE THREAD

**Issue by Gottox** [microsoft/TypeScript#14534]
doc/spec.md mentions an ```AmbientLexicalDeclaration```-rule for the grammar, but it's neither in the TypeScript nor in the ECMA-262 specification.

**Comment by nelsonlaquet** [comment]
Any way this can be resolved?

**Comment by RyanCavanaugh** [comment]
The spec is now an "archived" artifact and we won't be tracking defects against it anymore.
