### ISSUE TITLE
Question : Is typescript compiler can compile javascript files instead typescript files?

### ISSUE THREAD

**Issue by ifle** [Microsoft/TypeScript#14536]
Will be nice if typescript compiler can compile javascript code instead typescript. 
We would like to start to use  the async\await syntax only with ES5 target and use as input the js files.

**Comment by ifle** [comment]
I tried allowJs flag, but itdoes not work in Visual Studio

**Comment by mhegazy** [comment]
> I tried allowJs flag, but it does not work in Visual Studio

what do you mean by does not work? how are you calling the compiler?

**Comment by ifle** [comment]
I rechecked again. The allowJs flag does not works in saving a file in VS2015 Update3
I have following tsconfig 
```ts
{
  "compileOnSave": true,
  "compilerOptions": {
    "noImplicitAny": false,
    "noEmitOnError": false,
    "removeComments": false,
    "sourceMap": true,
    "listEmittedFiles": true,
    "target": "es5",
	  "lib": [
              "dom",
              "es5",            
              "es2015.promise"
          ],
      "outDir": "./html/js",
      "allowJs": true
  },
  "include": [
        "./html/ts/*"
    ],
  "exclude": [
    "node_modules",
    "wwwroot"
  ]
}
```

**Comment by mhegazy** [comment]
Compile-on-save will not work for .js files in VS 2015; this should be supported in VS 2017 now.

Build should generate the files in both versions.

**Comment by ifle** [comment]
You are righrs. Build work, compile on save does not work. Is there any plans to fix tgis issue?

**Comment by mhegazy** [comment]
The fix requires some major rearchitecture of both the JS and TS language services in VS; something that we already have done in VS 2017, and have no plans to back-port to VS 2015 at the time being.

**Comment by ifle** [comment]
Thanks for your answer.

**Comment by styfle** [comment]
@mhegazy Is this enabled by default in VS 2017? I noticed a bunch of javascript files generated a corresponding `.map.js` and their formatting was changed a bit after compiling and existing VS 2015 project.

**Comment by mhegazy** [comment]
if your project has both `--allowJs: true` and `compileOnSave` enabled, then yes. the output should be the same though, if it is different then there is a miss configuration/compiler bug somewhere. If you can share more details we can investigate more.

**Comment by styfle** [comment]
I am not use the `tsconfig` or setting any command line flags myself. The property group looks like the following:

```xml
<PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Build|AnyCPU'">
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>bin\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <DebugType>full</DebugType>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <ErrorReport>prompt</ErrorReport>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
    <TypeScriptTarget>ES5</TypeScriptTarget>
    <TypeScriptJSXEmit>React</TypeScriptJSXEmit>
    <TypeScriptCompileOnSaveEnabled>True</TypeScriptCompileOnSaveEnabled>
    <TypeScriptNoImplicitAny>True</TypeScriptNoImplicitAny>
    <TypeScriptModuleKind>CommonJS</TypeScriptModuleKind>
    <TypeScriptRemoveComments>False</TypeScriptRemoveComments>
    <TypeScriptOutFile />
    <TypeScriptOutDir />
    <TypeScriptGeneratesDeclarations>False</TypeScriptGeneratesDeclarations>
    <TypeScriptNoEmitOnError>True</TypeScriptNoEmitOnError>
    <TypeScriptSourceMap>True</TypeScriptSourceMap>
    <TypeScriptMapRoot />
    <TypeScriptSourceRoot />
  </PropertyGroup>
```

I believe it might be related to #14565 but the other reason might be if the default is now true in VS 2017 when it was false in VS 2015 (TS 1.8).

**Comment by mhegazy** [comment]
@styfle can you elaborate on the details of the issues you are seeing? you have .js files in your project, when you save them, you see output generated for them in your `bin\` dir, and no tsconfig.json? is this accurate?

**Comment by billti** [comment]
`<TypeScriptOutDir />` is empty above, so its likely not compiling as the output would overwrite the input. Can you specify a location to put the compiled files and see if that works?

**Comment by styfle** [comment]
I am not using a bin folder. The `.js` file gets generated next to the `.ts` file.

I opened an existing project in VS 2017, edited a `.d..ts` file, saved, and VS started compiling a lot of files....files that do not have a `.ts` associated with them 😨 

![image](https://cloud.githubusercontent.com/assets/229881/24255569/450d89d8-0fbc-11e7-8f31-1c75d188d96e.png)

Then I looked at git changes in Team Explorer tab and I can see that a bunch of `.js` files were modified and a bunch of `.js.map` files were added.

![image](https://cloud.githubusercontent.com/assets/229881/24255545/32badf2e-0fbc-11e7-8d72-bde7be819705.png)

**Comment by billti** [comment]
@styfle VS should not be compiling those files on save. I'll try and repro the issue you are seeing, but in case I am unable to, if you have a repro project you can share that would be helpful. Thanks.

**Comment by billti** [comment]
@styfle I just tried this with your project settings and didn't see the issue. A couple requests:

1. Could you switch on Virtual Projects (Tools / Options / Text Editor / JavaScript/TypeScript / Project / Display Virtual Projects when a solution is loaded).
2. Open a .js or .ts file in the affected project (so the language service loads the project) and get a screen shot of the virtual projects in Solution Explorer. (You should have one containing your .ts files, and another named "&lt;ProjectName&gt; JavaScript Content Files").
3. Please open another issue for this problem and mention me so I see it (as this issue is for _wanting to compile_ JavaScript files).

Thanks.

**Comment by styfle** [comment]
For reference, I opened #14827
