### ISSUE TITLE
doc/spec.md: formatting issue in EnumMember rule

### ISSUE THREAD

**Issue by Gottox** [microsoft/TypeScript#14535]
In the EnumMember rule there's the following line:

`&emsp;&emsp;&emsp;*PropertyName*&emsp;=&emsp;*EnumValue*`

In contrast to other rules, this one does not mark the `=` sign as a literal, resulting in a warning in one of our inhouse parser generator scripts.

I suspect, that the correct rule should be

``&emsp;&emsp;&emsp;*PropertyName*&emsp;`=`&emsp;*EnumValue*``

**Comment by RyanCavanaugh** [comment]
The spec is now an "archived" artifact and we won't be tracking defects against it anymore.
