### ISSUE TITLE
tsc returns base class instead of "this" class

### ISSUE THREAD

**Issue by sevensc** [Microsoft/TypeScript#14547]
**TypeScript Version:**  2.2.1
You can test the issue with this: https://github.com/sevensc/linqscript

This is my class:
```ts
    export class List<T> extends Array<T> {}
```

When compiling with latest typescript version on Mac "tsc source.ts", the source.js function looks like this:

```ts
function List() {
            return _super !== null && _super.apply(this, arguments) || this;
        }
```
which returns a new instance of an "Array", instead of an instance of a "List"

**Actual behavior:**
```ts
var list = new List<string>() // -> list = []
```
Anyhow, when i change the function to:

```ts
function List() {
            _super !== null && _super.apply(this, arguments) || this;
        }
```
or
```ts
function List() {
           return this;
        }
```
everything works just fine.

**Expected behavior:**
```ts
var list = new List<string>() // -> list = List {}
```

**Comment by RyanCavanaugh** [comment]
https://github.com/Microsoft/TypeScript/wiki/FAQ#why-doesnt-extending-built-ins-like-error-array-and-map-work

**Comment by sevensc** [comment]
@RyanCavanaugh Thanks for the quick answer.  Since i created this repo with an older version of typescript and this is in productive usage, is there any way to fix this, except for the not IE working
`Object.setPrototypeOf(this, FooError.prototype);` ?

**Comment by sevensc** [comment]
I just saw that im having the same trouble, extending from  `Date`

**Comment by DanielRosenwasser** [comment]
One thing you could do is rewrite as an ES5-style class and set up the prototype chain between the two manually.

**Comment by sevensc** [comment]
Hi @DanielRosenwasser! Thanks you for your response! This i my "workaround":

```typescript

export class List<T> extends Array<T> {
public _array: Array<T>;
public Where(delegate: (value: T) => boolean, args?: any): List<T> {
  try {
     const list = new Array<T>();
     if (!this.validDelegate(delegate))
         return list.ToList();

     for (let i = 0; i < this._array.length; i++) { //replaced 'this' with property 'this._array'
           const c = this._array[i]; //replaced 'this' with property 'this._array'
           if (c === null)
               continue;

           if (delegate.call(args, c))
               list.push(c);
           }

           return list.ToList();
  }
  catch (ex) {
     this._array = null;
     return new List<T>();
  }
}
...
```

**Interface**
```typescript
interface Array<T> {
    Where(delegate, args?);
}
```

**prototype**
```javascript
Array.prototype.Where = function(delegate, args){
    ls.List.prototype._array = this; //set public variable on class List
    var returnValue = ls.List.prototype.Where(delegate, args);
    ls.List.prototype._array = null; //and reset
    return returnValue;
}
```
