### ISSUE TITLE
Visual Stuidio 2015 won't clear Typescript errors

### ISSUE THREAD

**Issue by AcousticGuitar** [Microsoft/TypeScript#14540]
**TypeScript Version:**  2.1.5.0

Visual Studio 2015 TypeScript Project

**Recreation**

-  To recreate, rename a Typescript file from lower case to proper case.
- Typescript autocompile automatically catches all lower case imports statements (which are now wrong) as shown in image below (except we already changed it to upper case to get rid of error).
- Change the TSConfig.json to refer to the new proper case name.
- Find all improper lower case import statements in entire project and rename them to the proper case.
- Recompile the project and note the errors still indicate the following:

<img width="600" alt="rename" src="https://cloud.githubusercontent.com/assets/10676026/23711795/84f3d232-03e6-11e7-899c-97332e0a5675.png">

The type script build is driven by json as follows:  NOTE: the proper name change has been made.

```xml
{
  "compilerOptions": {
    "module": "amd",
    "moduleResolution": "node",
    "target": "es2016",
    "lib": [
      "es2016",
      "dom"
    ],
    "outDir": "dist",
    "types": [
      "vss-web-extension-sdk",
      "c3",
      "d3",
      "jquery",
      "knockout"
    ]
  },

  "files": [
   ...
    "scripts/Constants.ts",
    ...
    

  ]
}
```

With package.json looking like this.

```xml
{
  "name": "metrics",
  "version": "1.0.0",
  "description": "A simple extension",
  "scripts": {
    "build": "tsc -p .",
    "postbuild": "npm run package",
    "package": "node_modules\\.bin\\tfx extension publish --output-path bin --token %VSTSMarketplaceToken% --manifest-globs vss-extension.json --rev-version --publisher %VSTSMarketplacePublisher%",
    "clean": "rimraf ./dist && rimraf ./*.vsix"
  },
  "author": "SomeAuthor",
  "devDependencies": {
    "ncp": "^2.0.0",
    "rimraf": "^2.5.4",
    "typescript": "^2.1.4"
  },
  "dependencies": {
    "@types/c3": "^0.4.38",
    "@types/d3": "^4.4.1",
    "@types/jquery": "^2.0.34",
    "@types/q": "0.0.32",
    "c3": "^0.4.11",
    "d3": "~3.5.0",
    "knockout": "~3.4.1",
    "q": "^1.4.1",
    "vss-web-extension-sdk": "^2.109.1"
  }
}
```

**Expected behavior:**

When compiling via the command line "tsc -p ." there are no errors.  Additionally, when publishing to VSTS extensions, all code runs fine. 

**Actual behavior:**

<img width="600" alt="rename" src="https://cloud.githubusercontent.com/assets/10676026/23712373/582dcfda-03e8-11e7-8c64-95ab22ee4e68.png">

Screen shot of the file:

<img width="150" alt="constants" src="https://cloud.githubusercontent.com/assets/10676026/23712450/9357bc42-03e8-11e7-9ca6-d03dd375b288.png">

**Comment by mhegazy** [comment]
do you see this in a simple project, with just two files? can you share your project? have you tried with TS 2.2 ?

**Comment by AcousticGuitar** [comment]
I found the root cause of this problem just yesterday, which would be a good candidate for enhancement. 
Short: When Visual Studio compiles a Typescript project, it puts the Javascript files into same directory as the TS files. I call these the "in-line" .js files. 

**Actual Behavior**

<img width="400" alt="outputs" src="https://cloud.githubusercontent.com/assets/10676026/23761571/df00895a-04b8-11e7-986a-9b1e4cd33a39.png">

But none of those files are visible to the project until one clicks "Show All Files".   They are simply hidden from developers view by default. 

Now if you rename a Typescript file, that apparently doesn't qualify as a legitimate recompile of that TS file.  It seems like the Typescript compiler only recompiles files that it thinks qualify.  If a change is made internal to the file then there's no problem, but simply renaming it seems to cause issues.  Perhaps this is also due to improper import statements still in the project. 

One of the "other" issues is that any preexisting Import still has the other name and needs to be changed.  To be consistent, the tsconfig.json should be changed too, so that everything in the project is the same.  

**Manual Solution to "Renaming a File Breaks Compile"**

- Rename a TS file in your solution first
- Rename all Imports in entire project referring to that file.
- Change the TSConfig.json files section to the new name (case sensitive)
- Click on show all files in your project and hunt down any .JS files with old name, delete them
- If the TSConfig.json has specified an Outdir, delete the entire folder.

The recompile now works and all the files are "fresh"

**Expected Behvior**

When running Build/Clean Solution:

- The entire  Outdir folder is deleted. 
- All previously compiled .js files are deleted
- "tsc -p ." Should do this by default or at least have a JSON configuration option that allows us to say "Yes clean all residual content" before compiling
- When renaming files, a prompt (just like C#) should ask "Include all references in project?.   Answering "Yes" would rename all imports, update the tsconfig.json file and optionally rename any string references.  No recompile would be needed.

I've written an article on this issue [here](https://www.linkedin.com/pulse/typescript-compiler-gotchas-john-peters).

**Comment by mhegazy** [comment]
> The compile first compiles in-place and then collects the ".js" files to be copied into the "outdir", but you wouldn't know this unless you had clicked on "Show All Files" in your Visual Studio project! When you "Show all Files" you should see this:

I am sorry, but the article is not accurate. the compiler does not copy files around. files are create once and they are place in the `outDir` directly.

If i were to guess, you had an earlier iteration with no `outDir`, the output in this case goes next to the source by default, then you added `outDir` and did not clean first. the result is having multiple files laying around.

**Comment by AcousticGuitar** [comment]
Yes, you are right, I just checked current project, now that the Outdir folder is specified there is no compile in place files.  And yes I did not clean those residual files,  mostly because I never saw the output until after clicking "Show All Files".  That's when I saw both the Outdir content and the in-line content making me believe this was normal.  After cleaning all the in-line residual files behavior is better but still needs improvement. 

The inability to have Build/Clean Solution do what is done in C# causes loss of productivity when simply  renaming a file.   There's no documentation that adding an Outdir will have this impact, but it shouldn't matter.  If an OutDir is added then a recompile should handle all older now non-legitimate content.  This is what C# does by default.

**Comment by mhegazy** [comment]
> The inability to have Build/Clean Solution do what is done in C# causes loss of productivity when simply renaming a file. There's no documentation that adding an Outdir will have this impact, but it shouldn't matter. If an OutDir is added then a recompile should handle all older now non-legitimate content. This is what C# does by default.

Clean does remove the files you created. you just changed where the output is before cleaning. you would get the same behavior in C# if you built, did not clean, changed the output location to somewhere different than `./bin` and built again.

the build process is stateless, it does not know the last time it ran what it created. all it knows is what it will create this time around. similarly the clean target, all what it does is figure out what it would have built, and then remove it. if you change the settings on it midway, there is no way for it to know that.

**Comment by mhegazy** [comment]
I would also appreciate if you were to update the article to avoid confusion in the future.

**Comment by AcousticGuitar** [comment]
Ok here's the same situation today on same project as listed above:

I have a typescript project ..  It is controlled by a typescript.json file.   VS does not allow any configuration settings to be set at project level if a tsconfig.json file is in project per this picture. 

<img width="353" alt="tsproject" src="https://cloud.githubusercontent.com/assets/10676026/24105502/0f896720-0d53-11e7-819e-4a1cc3f51071.PNG">

This is confirmation from VS that it is solely using the tsconfig.json file as found here:
```{
  "compilerOptions": {
    "module": "amd",
    "moduleResolution": "node",
    "target": "es2016",
    "lib": [
      "es2016",
      "dom"
    ],
    "outDir": "dist",
    "types": [
      "vss-web-extension-sdk",
      "c3",
      "d3",
      "jquery",
      "knockout"
    ]
  },

  "files": [
    "scripts/A.ts",
    "scripts/B.ts",
    "scripts/C.ts",
    "scripts/D.ts"
    ...etc... 
  ]
}```

Notice the "outDir" of "dist".  In a previous answer I was told that if the "outDir" is specified in the the tsconfig.json file we should not see any of the inline compiles of the files.  I call them inline because they show up in the same folder as the scripts folder (they are in-line with the ts files).   Here's example
 
<img width="115" alt="inlineex" src="https://cloud.githubusercontent.com/assets/10676026/24105864/3a0623c0-0d54-11e7-9480-410ebc9174d3.PNG">


But they are also found in the dist folder after a compile. 
 
<img width="99" alt="dist" src="https://cloud.githubusercontent.com/assets/10676026/24105891/51b09e60-0d54-11e7-8446-1d2b0796edcd.png">

This is the package.json content:
```
{
  "name": "qametrics",
  "version": "1.0.0",
  "description": "A simple extension",
  "scripts": {
    "build": "tsc -p .",
    "postbuild": "npm run package",
    "package": "node_modules\\.bin\\tfx extension publish --output-path bin --token %VSTSMarketplaceToken% --manifest-globs vss-extension.json --rev-version --publisher %VSTSMarketplacePublisher%",
    "clean": "rimraf ./dist && rimraf ./*.vsix && rimraf ./scripts/*.d.* && rimraf .scripts/*.js*"
  },
  "author": "Magenic",
  "devDependencies": {
    "ncp": "^2.0.0",
    "rimraf": "^2.5.4",
    "typescript": "^2.1.4"
  },
  "dependencies": {
    "@types/c3": "^0.4.38",
    "@types/d3": "^4.4.1",
    "@types/jquery": "^2.0.34",
    "@types/q": "0.0.32",
    "c3": "^0.4.11",
    "d3": "~3.5.0",
    "knockout": "~3.4.1",
    "q": "^1.4.1",
    "vss-web-extension-sdk": "^2.109.1"
  }
}
```

The only part affecting the build is the command  'tsc -p .'  command.  The postbuild command merely publishes the package to VSTS. 

If I clean the project prior to build... (which removes all of the in-line files, and manually delete the dist directory and then go to Visual Studio's Build/Rebuild Solution, and then refresh the solution explorer, this is what I see...  The dist folder is recreated (good) but the inline compiled files reappear!

<img width="170" alt="distandinlines" src="https://cloud.githubusercontent.com/assets/10676026/24106501/0da9f2dc-0d56-11e7-92ca-31cdf814681d.PNG">


Please tell me, why are the inlines reappearing when the Dist folder is specified?
