### ISSUE TITLE
Proposal: 'Fix All In File' for CodeFixes

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#14549]
From https://github.com/Microsoft/vscode/issues/22220

**Problem**
The current TypeScript code fixes must be applied individual. For fixes such as `remove unused import`, we would also like to support applying the fix to across all effected locations in a file.

**Possible Approaches**
To support this scenario across various editors and tools, the best approach would have the TSServer itself return `Fix all in File` type code fixes when `getCodeFixes` is requested. No TSServer API/protocol would have to be updated to support this. My only concern is that calculating the edits for fixing all problem in a file may be expensive and could bog down the TSServer. 

The alternative would be to implement the `fix all in file` logic in VSCode. To do this, we would make multiple calls to `getCodeFixes` against the TSServer to build up a set of `fix all in file` code actions. Each type of `CodeAction` returned by TSServer would need a kind identifier so that we can bundle all instances of the same kind together. We would also need to know which types of code fixes can be applied across an entire file

@mhegazy and anyone else, please let me know if you have any thoughts on this

**Comment by pcgeek86** [comment]
Just ran into this with the VSCode-PowerShell extension. If I select some code and try to `Quick Fix All`, there is no option to do so.

![screen shot 2017-05-11 at 10 00 58 am](https://cloud.githubusercontent.com/assets/466713/25962014/1a33ec84-3631-11e7-8fd6-a8cc7901329a.png)

Cheers,
Trevor Sullivan

**Comment by DanielRosenwasser** [comment]
Perhaps related to #19255.

**Comment by mjbvz** [comment]
Hey @andy-ms, is this new API exposed in `protocol.d.ts`? I took a quick look in typescript@next but didn't see it

**Comment by andy-ms** [comment]
@mjbvz Sorry, shouldn't have closed this. It's available at runtime but we haven't solidified the API. See #20538.

**Comment by andy-ms** [comment]
The API is now public (#21234).

**Comment by mjbvz** [comment]
Thanks @andy-ms!

Question on testing: we should now see a `fixId` returned on some code actions returned from `getCodeFixes`, correct?  I'm using a master TS build but am not seeing these. Any specific quick fixes / errors I should be using for testing?

**Comment by andy-ms** [comment]
Try again with #21247

**Comment by mjbvz** [comment]
Ok, working now. Will try to get initial vs code support for this in today
