### ISSUE TITLE
Typescript removes comment

### ISSUE THREAD

**Issue by RainingChain** [Microsoft/TypeScript#14550]
**TypeScript Version:**  2.2.1

**Code**

```ts
module A {     /*! My comment */
    export var a = 1;
}

```

**Expected behavior:**
```
var A;
(function (A) { /*! My comment */
    A.a = 1;
})(A || (A = {}));
```

**Actual behavior:**
```
var A;
(function (A) {
    A.a = 1;
})(A || (A = {}));
```

**Note**
Placing the comment on another line works but not if the comment is on the same line than `module`.
```
module A {     
   /*! This will work. */
    export var a = 1;
}
```

**Comment by RyanCavanaugh** [comment]
Same as #8800 / #2546 - comments between open braces and the first line of the block are not preserved
