### ISSUE TITLE
Extends in generic loose keys type

### ISSUE THREAD

**Issue by etienne-dldc** [Microsoft/TypeScript#14557]
**TypeScript Version:**  2.2.1 (also with 2.3.0-dev.20170308)

**Code**

```ts
interface IData<T> {
  Content?: T;
}

type Data<T> = {
  get: <K extends keyof T>(prop: K) => T[K];
};

class Parent<M> {
  private data: Data<M>;

  getData(): Data<M> {
    return this.data;
  }
}

export class Foo<C> extends Parent<IData<C>> {
  getContent(): C {
    return this.getData().get('Content'); // OK
  }
}

export class Bar<C, T extends IData<C>> extends Parent<T> {
  getContent(): C {
    return this.getData().get('Content');
    // [ts] Type 'T["Content"]' is not assignable to type 'C'. (property) get: <"Content">(prop: "Content") => T["Content"]
  }
}
```

**Expected behavior:**
`this.getData().get('Content');` should be of type `C`;

**Actual behavior:**
`Error: [ts] Type 'T["Content"]' is not assignable to type 'C'. (property) get: <"Content">(prop: "Content") => T["Content"]`

The behavior was correct with TypeScript 2.1.6.
Notice that the only difference between `Foo` (no error) and `Bar` (compile error) is how generic are declared.

**Comment by ahejlsberg** [comment]
A shorter repro:

```ts
function foo<C, T extends { content: C }>(x: C, y: T['content']) {
    x = y;  // Should not be an error
}
```

It worked in 2.1 because we eagerly resolved `T['content']` (which was wrong for other reasons).
