### ISSUE TITLE
Function in decorator arguments has false context

### ISSUE THREAD

**Issue by aight8** [Microsoft/TypeScript#14564]
**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)

**Code**

```ts
class Abc {
    @decorator('A/BLA', function(isCool: boolean) {
        // this is undefined
    })
    bla(isCool: boolean) { return Action(isCool); }
}

// if:

const decorator = function(actionType: string, reducer: Function) {
   function(target, key, descriptor) {
      // target is here the prototype so you cant use even .bind on the descriptor value
   }
}
```

**Expected behavior:**
this should be the current object

**Actual behavior:**
this is undefined or the prototype

**Comment by mhegazy** [comment]
I think you are mixing the decorator withe the decorator factory.

the decorator is the result of the call `decorator('A/BLA', function(isCool: boolean) { .. })` and not just `decorator`. so your decorator should be declared as:

```ts
const decorator = function (path: string, func: (isCool: boolean) => void) {
    return function (target, key, descriptor) {
        // target is here the prototype so you cant use even .bind on the descriptor value
    }
}
```

You can find more details at http://www.typescriptlang.org/docs/handbook/decorators.html#decorator-factories

**Comment by aight8** [comment]
Ou sorry I mistyped it. The problem is the same

**Comment by mhegazy** [comment]
`this` in that context depends on how you will call `reducer`. the compiler has nothing to do with that.

**Comment by Hotell** [comment]
exactly what @mhegazy said.

if you wanna override or set explicitly this type in the function, just

```ts
type MyContext = ...

class Abc {
    @decorator('A/BLA', function(this:MyContext, isCool: boolean) {
        // this is MyContext
    })
    bla(isCool: boolean) { return Action(isCool); }
}
```

https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#specifying-the-type-of-this-for-functions

**Comment by aluanhaddad** [comment]
You need to return the decorator from the decorator factory.
