### ISSUE TITLE
Array subscript access returns non-optional

### ISSUE THREAD

**Issue by iv-mexx** [Microsoft/TypeScript#14563]
**TypeScript Version:**  2.2.1

**Code**

```ts
const array: number[] = []
const maybeNumber = array[10]
```

**Expected behavior:**

`maybeNumber` is inferred as optional `number | undefined`

**Actual behavior:**

`maybeNumber` is inferred as non-optional `number`

![screengrab](https://cloud.githubusercontent.com/assets/3407787/23768507/905ff2fa-050c-11e7-9078-200a27059653.png)

**Comment by RyanCavanaugh** [comment]
Duplicate #9235
