### ISSUE TITLE
Suggestion: Consider passing name of class to class decorators

### ISSUE THREAD

**Issue by papercuptech** [Microsoft/TypeScript#14572]
A common convenience is for reflectors to use function and property names as metadata to create identifiers for other purposes. However, when .js is pushed through an uglifier, in many cases the names get mangled and then can't be used in that way.

Using property decorators has the side effect of preserving the property name (as it's passed to the decorator as a string literal) as metadata, even when the generated .js has been mangled. Handy way around the above problem.

Unfortunately, class decorators are only passed the class constructor function, whose name is usually then mangled by uglifiers.

I realize decorator support is meant to be ES7 compatible, but this would be an 'extension' rather than something breaking? yeah??

**Comment by kitsonk** [comment]
It only makes sense for it to align to the [ES Proposal](https://tc39.github.io/proposal-decorators/), which isn't ES7... it is only Stage 2 and I know it was being re-worked a while ago.  It is open for debate, so it would be better to champion changes to the proposal through TC39 (as the class name is as meaningful to ES as it would be to TS).

**Comment by papercuptech** [comment]
I'm looking towards an implementation sooner than later, and in that regard I wouldn't agree championing with a proposal (be it ES7 or otherwise) is better. I do agree it should be championed there as well. No harm in attempting to garner all possible support from Typescript, from positive communications in this repo up to actual implementation (even now decorator support is an opt in experiment, so more wiggle room for innovation?).

I imagine an actual implementation would be quite trivial: a minor change to __decorate, and emitting the call to it to include the additional class name literal argument.

Maybe this can be done using a custom emit transform; is api for that yet released?

**Comment by RyanCavanaugh** [comment]
We'd really prefer changes / augmentations to ES-standard features be championed at the appropriate ES forum. TypeScript has enough going on already; we can't simultaneously handle our own stuff and also be an out-of-band channel for garnering support for ES changes.

**Comment by papercuptech** [comment]
@RyanCavanaugh would you be so kind as to provide a link of the appropriate form, where I can create an issue, or begin a discussion/thread regarding this issue?

**Comment by RyanCavanaugh** [comment]
https://github.com/tc39/proposal-decorators
