### ISSUE TITLE
Object is possibly undefined even though it is not possible

### ISSUE THREAD

**Issue by honzabrecka** [Microsoft/TypeScript#14579]
**TypeScript Version:**  2.1.1

**Code**

```ts
interface Foo {
  bar: string;
}

interface F {
  (foo?: Foo): string;
}
const f: F = (foo = { bar: 'hi' }) => foo.bar

// working workaround
const f: F = (foo) => (foo || { bar: 'hi' }).bar;
```

**Actual behavior:**

Object (foo) is possibly undefined. But it's never possible.

**Expected behavior:**

No error. Do not look only inside interface, but merge it with actual implementation.

**Comment by ahejlsberg** [comment]
I believe this was already fixed in 2.2 and it doesn't repro in typescript@next.
