### ISSUE TITLE
Type checking embedded expressions in tsx

### ISSUE THREAD

**Issue by ceymard** [Microsoft/TypeScript#14577]
It would seem that typescript treats anything between curly braces in tsx expressions as any.

There is no option on the JSX namespace that I know of that allows restricting the result of expressions to certain types.

**TypeScript Version:**  2.2.1

**Code**

```tsx
var div = <div>
  {new Date()}
</div>
```

This always compiles. How do I prevent certain types from being validated there ? Should there be a modification of the JSX namespace ?

**Comment by RyanCavanaugh** [comment]
Duplicate #13618
