### ISSUE TITLE
"Salsa" intellisense not working in nested files (under html) in VS 2017

### ISSUE THREAD

**Issue by mrahhal** [Microsoft/TypeScript#14578]
Platform: VS 2017 (RTM), using ".js" files with auto type acquisition (without a tsconfig file).

External packages (like angular type definitions from bower) are not being included in intellisense in nested files. Everything works fine in normal files, but when the file is nested (under an html file for example), intellisense won't include external packages:

![capture](https://cloud.githubusercontent.com/assets/4404199/23799764/5c78a882-05b2-11e7-9ca3-a2d4738f93c5.PNG)

**Comment by mrahhal** [comment]
Looks like adding an empty "jsconfig.json" (containing only "{}") fixed this. But I'm kinda seeing inconsistent behavior across VS Code and VS 2017.

**Comment by jramsay** [comment]
@mrahhal :  thanks for raising this issue.  I'm also able to repro

**Comment by jramsay** [comment]
@mrahhal : thanks for raising this issue. I'm also able to repro when using nested files without a tsconfig.json. Nested JS files are being placed in a separate (intellisense) project context which isn't ideal.  I've reopened this issue as we should be able to do better here.

**Comment by billti** [comment]
This bug was on the Visual Studio 2017 side. The fix is checked in and it will be included in the next update (unfortunately it just missed "update 3" which went out this week).

**Comment by mhegazy** [comment]
Should be fixed in [15.3](https://www.visualstudio.com/en-us/news/releasenotes/vs2017-relnotes).

**Comment by billti** [comment]
See prior comment. This didn't make 15.3. It'll be in 15.4.
