### ISSUE TITLE
JSLint error with ES2017 Decorator

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#14587]
_From @AntSworD on March 8, 2017 7:31_

- VSCode Version: 1.10.1 (1.10.1)
- OS Version: MacOS sierra 10.12.3 (16D32)

When use decorator with koa:
![image](https://cloud.githubusercontent.com/assets/2549087/23694292/fe4d893e-0413-11e7-9707-e115ab918935.png)

I got: 
![image](https://cloud.githubusercontent.com/assets/2549087/23694306/11c399ea-0414-11e7-9995-2f78cb9f4db6.png)

My setting:
.babelrc:
```
{
  "presets": ["es2015", "es2017"],
  "plugins": [
    "transform-decorators-legacy",
    "transform-runtime",
    "add-module-exports"
  ]
}
```
jsconfig.json:
```
{
  "compilerOptions": {
    "target": "ES6",
    "module": "commonjs",
    "experimentalDecorators": true
  },
  "exclude": [
    "node_modules"
  ]
}
```

_Copied from original issue: Microsoft/vscode#22198_

**Comment by mjbvz** [comment]
Here's a small repo of the issue:

```js
function deco(x) { return x; }

({
    @deco
    func() { return 2; }
})
```

Babel legacy decorators supports decorators on object methods but I don't know what the current state of the decorators proposal says about this

**Comment by aluanhaddad** [comment]
I take it that this regards the VS Code plugin that extends JSLint, not JSLint.  JSLint does not tolerate classes so I doubt it supports decorators (even for object literals).

**Comment by RyanCavanaugh** [comment]
The current proposal does not support this

https://tc39.github.io/proposal-decorators/

**Comment by AntSworD** [comment]
I'm still not sure about this issue. If `Decorator` didn't been support, what is `experimentalDecorators` mean on the `jsconfig.json`. [jsonconfig options](https://code.visualstudio.com/docs/languages/jsconfig#_jsconfig-options)

**Comment by RyanCavanaugh** [comment]
Decorators are supported. They are not supported in places where the spec does not allow them to be written.

**Comment by AntSworD** [comment]
Got it. 
Bable [decorators](https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy) support [object-literal-method-declaration](https://github.com/wycats/javascript-decorators/blob/master/README.md#object-literal-method-declaration), but typeScript only support class decorator!

It might be better if [jsconfig options](https://code.visualstudio.com/docs/languages/jsconfig#_jsconfig-options) have a HINT. Just a suggestion.

Finally, Thank you ALL!

**Comment by aluanhaddad** [comment]
I'm still perplexed by the title of this issue, what does any of this have to do with JSLint?

If y'all were talking about some other tool then my comments must have sounded insane...
