### ISSUE TITLE
Incorrect indentation on chained methods

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#14586]
_From @ofabricio on March 9, 2017 13:25_

- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|EditorConfig|EditorConfig|0.6.0|
|autoimport|steoates|1.2.2|
|Angular2|UVBrain|0.4.1|;

---

Steps to Reproduce:

I made a gif to illustrate:

![hi](https://cloud.githubusercontent.com/assets/1385704/23751550/a7ef8504-04b0-11e7-8b51-9ceab7d83b20.gif)

Notice how `C` parameter and `.do` method are not correctly indented after format document depending on `.mergeMap` position.

It happens either in Typescript or Javascript syntax.

It seems a bug. People in gitter/vscode agreed, so I opened this issue.

_Copied from original issue: Microsoft/vscode#22295_

**Comment by mjbvz** [comment]
Here's the code:

```js
object
    .method(() =>
        1,
        2)
```

Is currently formatted to:

```js
object
    .method(() =>
        1,
    2)
```

**Comment by ofabricio** [comment]
Also

```
object.method(() =>
    1,
    2
)
.do()
```

Is currently formatted to:

```
object.method(() =>
    1,
    2
)
    .do()
```

And

```
object
    .method(
        1,
        2
    )
    .do()
```
to:

```
object
    .mergeMap(
    1,
    2
    )
    .do()
```

**Comment by mjbvz** [comment]
Another example from https://github.com/Microsoft/vscode/issues/23482:

```js
func(1)
    .subscribe(
    1,
    2
    )
```

is left unformatted. The expected formatting here would be:

```js
func(1)
    .subscribe(
        1,
        2
    )
```

**Comment by mjbvz** [comment]
Tested in TS 3.7.5. The formatting for the original example now appears to be correct:

```
object
    .method(a =>
        1,
        2
    )
    .method(r => { })
```
