### ISSUE TITLE
Design Meeting Nodes, 3/10/2017

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#14583]
# The `checkJs` flag

* A soft form of type checking that is acceptable for JavaScript files.
* We took several JS projects and looked at what TypeScript errors got to be too much.
    * Turned off reporting for those errors.
* A few comments that turn checking on and off.
    * `ts-suppress`
        * Check preceding line
    * `ts-nocheck` - turn off checking for the whole file.
        * Must be the first comment.

* Still to fix:
    * Using `arguments` should make all parameters optional.

## Do we allow annotations in `checkJs`?

* Currently, `checkJs` mode disallows type annotations.
* We discussed having a mode for JS files where they're treated as plain TypeScript.
* But that means that certain constructs need to be switched to their TypeScript equivalent.
    * Annoying example:
        * JS: `const foo = require("foo");`
        * TS: `import foo = require("foo");`
    * We have some quick fixes to help guide you.
        * But it's sort of one step back to move many steps forward.
* It becomes extremely difficult to understand the levels of checking in JS files, versus TS files.
* If you're moving to TypeScript, JSDoc is a bit of a weird side-step - you're going to migrate to annotations anyway.
* Conclusion: Keep JavaScript as JavaScript.
    * Tooling can help transitioning care of this.
    * Revisit if necessary.

## What do we name the soft-check annotation?

* Candidates are
    * `@ts-check`
    * `@ts-nocheck`
    * `@ts-suppress`
    * ...
* Unresolved.

## Do we allow suppression in TS files?
* Many instances of "I want to suppress errors" are cases where people are better off figuring out the errors.
* But transitioning is hard. People want to fix, move on, and come back when they understand the language.
* Example: `foo(bar, baz, biz)` - what if this gives you an error of "invalid call signature blah blah blah"?
    * Typically "cast to `any`" is the advice.
    * But...
    * `foo(bar, baz, biz) as any` doesn't work
    * `foo(bar as any, baz as any, biz as any) as any` doesn't work
    * `(foo as any)(bar, baz, biz)` works! Oh, obviously!
        * Sympathize with new user - nobody would think of this.
            Let them grow their understanding of the language as they transition.
* Question: if you're giving such a terrible error there, why not improve error messages?
    * Ultimately, this is an ideal goal but it is doubtful that we can realistically do this consistently and cover all of the bases.
    * Should still do this.
* Removing suppressions can be viewed as part of transition step to TypeScript.
* Conclusion: allow this in JavaScript, see what demand in TS mode is.

## Do we want suppression for specific error messages?

* People seem uncertain that this is a good idea.
* Makes more sense when every check has a name.
    * But TypeScript uses error codes! Nobody would know what "Suppress TS1234" means.
* What about error suppression for specific flags like `noImplicitAny`?
    * Makes sense for `noImplicitAny`, not clear about `strictNullChecks` for all locations.
    * Declaration emit errors?
* Conclusion: hold off on this idea.

**Comment by mihailik** [comment]
Suppression in TS is analogous to `asm { }` in C language.

Basically, you've got already tried and tested (minified?) code in JavaScript, which you want to encapsulate in a TS scope. Ideally you want that code verbatim, just so you don't have to re-test it.

Just recently I've had that use case. I was implementing a plugin that transforms data, and wanted to add compression. So I've picked LZW library and embedded right into the code. It's minified, so it sits nicely there without getting in the way. But it's completely useless to try and patch it for TS validator benefit -- too much changes and you're guaranteed to add a bunch of typos.

In my case the only sane option is to inject that JS library post-compilation at some kind of predefined `/* INSERT LZW HERE */` marker I need to put in TS code. Would be so much simpler to make TS skip the piece.

Another reasonable use case is embedding hand-written ASM.js in a bigger TS library. Trying to satisfy both ASM.js and TS syntax is too much pain.
