### ISSUE TITLE
Challenge - need to manually generate reference path for *.d.ts files?

### ISSUE THREAD

**Issue by ORESoftware** [Microsoft/TypeScript#14598]
I am using `declaration:true` in my `compilerOptions` in tsconfig.json.

I have a directory in my project root called `dts` which contains manually created .d.ts files, which are shared by multiple files in my project (maybe that's the wrong way to do it, dunno).

So when I transpile, TS will generate *.d.ts for all my .ts files, but then I get something like this in a file:

declare var _default: (suman: ISuman, zuite: ITestSuite) => Function;
export = _default;

Webstorm will say:

> Cannot find name ISuman
> Cannot find name ITestSuite

so then I click "Generate reference path"

<img width="632" alt="screenshot 2017-03-11 10 11 32" src="https://cloud.githubusercontent.com/assets/11139560/23825687/3088adf8-0643-11e7-9b1b-2bb26d5d82db.png">

and then I get the reference paths and all seems well

```js
///<reference path="../../dts/suman.d.ts"/>
///<reference path="../../dts/test-suite.d.ts"/>
declare var _default: (suman: ISuman, zuite: ITestSuite) => Function;
export = _default;
```

so, I don't want to have to manually generate these reference paths, what do I do to configure my project so that this info doesn't need to be manually generated?

**Comment by Hotell** [comment]
This has nothing to do with TS, but is Webstorm misconception instead. You have probably not properly configured `tsconfig.json`

Can you shared it pls?

**Comment by ORESoftware** [comment]
Sure thing, thanks

```json
{
  "compilerOptions": {
    "declaration": true,
    "baseUrl": ".",
    "paths": {
    },
    "types": [
      "node"
    ],
    "typeRoots": [
      "node_modules/@types"
    ],
    "target": "es5",
    "module": "commonjs",
    "noImplicitAny": true,
    "removeComments": true,
    "allowUnreachableCode": true,
    "lib": [
      "es2015",
      "es2016"
    ],
    "experimentalDecorators": true,
    "noUnusedLocals": true,
    "strictNullChecks": true,
    "newLine": "LF",
    "noUnusedParameters": false,
    "emitDecoratorMetadata": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true
  },
  "compileOnSave": false,
  "include": [
    "./**/*.ts"
  ],
  "exclude": [
    "test",
    "node_modules"
  ]
}
```

**Comment by Hotell** [comment]
add folder with manual ambient types here

```
  "include": [
    "./**/*.ts",
    "folder-with-manual-types"
  ],
```

and you should be good to go

**Comment by ORESoftware** [comment]
oh nice let me give that a shot, although the folder with manual types all has *.ts files (which should match .d.ts so I would think it would be captured?

**Comment by ORESoftware** [comment]
unfortunately that didn't seem to work. Webstorm is still asking for the reference path.

///<reference path="../../dts/suman.d.ts"/>

So I need to put lines like the above in the generated *.d.ts files.  

Could I share my project with you? It's here:

Here's a .ts file:

https://github.com/sumanjs/suman/blob/rebase_branch/lib/test-suite-methods/make-after-each.ts

and here is it's corresponding .d.ts:

https://github.com/sumanjs/suman/blob/rebase_branch/lib/test-suite-methods/make-after-each.d.ts

as you can see, the make-after-each.d.ts file does not have reference paths.
My IDE compains that it can't find the `ISuman` and `ITestSuite` symbols.

That's when I have to put a reference path in there, manually.

**Comment by aluanhaddad** [comment]
Consider following Webstorm/IntelliJ IDEA documentation on how to replace JetBrains language server with tsserver. They are also often a few language versions behind, although they are catching up. Love JetBrains btw, if I ever use a JVM language their tools are a joy to work with.
