### ISSUE TITLE
Add a "throws" decorator to methods

### ISSUE THREAD

**Issue by agonzalezjr** [Microsoft/TypeScript#14599]
Could a `throws` decorator be added to methods that could throw an error or raise an exception?

That way methods that call them could be checked to make sure they are either handling it or throwing themselves as well.

Example:

```ts
public doSomethingThatCouldGoWrong(x: int) throws {
  return 1 / x;
}
```

**Comment by DanielRosenwasser** [comment]
Closing as a duplicate of #13219.

**Comment by agonzalezjr** [comment]
Thanks! Didn't find it.
