### ISSUE TITLE
Misleading CanvasRenderingContext2D.drawImage signature

### ISSUE THREAD

**Issue by nkemnitz** [Microsoft/TypeScript#14592]
**TypeScript Version:**  2.2.1

**Current `lib.dom.d.ts` signature w/o types**:
```ts
drawImage(image, offsetX, offsetY, width?, height?, canvasOffsetX?, canvasOffsetY?, canvasImageWidth?, canvasImageHeight?)
```

**[WHATWG HTML spec](https://html.spec.whatwg.org/multipage/scripting.html#dom-context-2d-drawimage) w/o types**
```ts
drawImage(image, canvasOffsetX, canvasOffsetY)
drawImage(image, canvasOffsetX, canvasOffsetY, canvasImageWidth, canvasImageHeight)
drawImage(image, offsetX, offsetY, width, height, canvasOffsetX, canvasOffsetY, canvasImageWidth, canvasImageHeight)
```

The TS description matches the 9 parameter version of the Standard, but because they sneaked in the 4 additional parameters right after `image`, it doesn't fit the first two signatures.

I would create a PR and split the signature into three, if that is acceptable?

**Comment by DanielRosenwasser** [comment]
Sounds reasonable. Sorry this got lost. Check out https://github.com/Microsoft/TSJS-lib-generator to send a PR. I think you want to look [here](https://github.com/Microsoft/TSJS-lib-generator/blob/c15a33929d62233462532e2ca1c6413424af3016/inputfiles/browser.webidl.xml#L2831-L2841).

**Comment by nkemnitz** [comment]
No problem, [PR #214](https://github.com/Microsoft/TSJS-lib-generator/pull/214) contains the suggested changes.
