### ISSUE TITLE
Problems with Object.freeze and 'kind' properties

### ISSUE THREAD

**Issue by mmc41** [Microsoft/TypeScript#14595]
**TypeScript Version:**  2.2.1

**Code**

```
export interface MetaEntityInfo<T> {
    readonly name: string;
    readonly docExample?: T;
}

export interface Organisation {
    readonly id: string;
    readonly kind: 'organisation';
    readonly description: string;
}

export namespace Organisation {
    export const meta: MetaEntityInfo<Organisation> = Object.freeze({
        name: 'organisation',
        docExample: {
            id: 'myorg',
            kind: 'organisation',
            description: 'this is a description of the organisation'
        }
    });
};
```

**Expected behavior:**

Compilation succesful

**Actual behavior:**

error TS2322: Type 'Readonly<{ name: string; docExample: { id: string; kind: ...' is not assignable to type 'MetaEntityInfo<Organisation>'.
  Types of property 'docExample' are incompatible.
    Type '{ id: string; kind: string; description: string; }' is not assignable to type 'Organisation | undefined'.
      Type '{ id: string; kind: string; description: string; }' is not assignable to type 'Organisation'.
        Types of property 'kind' are incompatible.
          Type 'string' is not assignable to type '"organisation"'.

NOTE: The problem only occurs if I provide the example instance inside the namespace. Outside, I can declare the same example and the compiler will accept it.

**Comment by RyanCavanaugh** [comment]
TypeScript knows that `Object.freeze` takes a `T` and returns a `T`, which means it's type-preserving, but it doesn't know that it's value-preserving for every field. You could imagine some function `toUpperify<T>(x: T): T` that traversed an object and returned a copy where all strings had been replaced by upper-cased versions of themselves - this function would not be safe to use here.

A good alternative is
```
export const meta = Object.freeze({
    name: 'organisation',
    docExample: {
        id: 'myorg',
        kind: 'organisation',
        description: 'this is a description of the organisation'
    }
}) as MetaEntityInfo<Organisation>;
```

> The problem only occurs if I provide the example instance inside the namespace. Outside, I can declare the same example and the compiler will accept it.

I'm not seeing this behavior - are you sure?

**Comment by mmc41** [comment]
Sorry, you are right. When I got it working outside the namespace it was without readonly.
I noticed, you marked the issue as a limitation with current TS. Is there a plan to resolve this limitation in a future TS version ?

**Comment by RyanCavanaugh** [comment]
There is no current plan in place
