### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by kgtkr** [Microsoft/TypeScript#14604]
**TypeScript Version:**  2.2.1

**Code**
```ts
// A *self-contained* demonstration of the problem follows...
type AB=A|B;

interface A{
  a:number
}

interface B{
  a:string
}

interface C{
  a:number|string;
}

function hoge(c:C):AB{
  return c;//error
}
```

**Expected behavior:**

**Actual behavior:**

**Comment by kitsonk** [comment]
This has been discussed many times before...  The type system is a structural type system and TypeScript compares based on structure.  Type `AB` is either:

```typescript
interface A {
  a: number;
}
```

Or:

```typescript
interface B {
  a: string;
}
```

Where as you are returning something that has a single member `a` that is *either* a string or a number.  That is not assignable to interface `A` or interface `B`.

You can fix the error by better modelling the type:

```typescript
type AB=A|B;

interface A{
  a:number
}

interface B{
  a:string
}

type C = { a: number } | { a: string };

function hoge(c: C): AB{
  return c;//no error
}
```

*Sidenote:* your issue really leaves a lot to be desired.

**Comment by kgtkr** [comment]
The actual code is more complicated, so it can not be done

```ts
interface DBModelA{
    type:'a',
    hoge:number
}

interface DBModelB{
    type:'b',
    foo:number
}

interface DBModelC{
    type:'c',
    hoge:number,
    foo:number
}

type DBModel=DBModelA|DBModelB|DBModelC;
```

**Comment by kgtkr** [comment]
```ts
function toModel(t:OriginalTweet):OriginalTweetModel;
function toModel(t:ReTweet):ReTweetModel;
function toModel(t:Tweet):TweetModel{
    //process
}

let hoge=toModel(Tweet);//error
```

**Comment by gcnew** [comment]
You can add one more overload:

```ts
function toModel(t:Tweet):TweetModel;
```
And it should be fine. The problem with your current approach is that none of the overloads is actually callable with the provided argument. It can be argued that the compiler may synthesise a compatible call signature based on the intersection of existing ones, but it's actually very hard and confusing.

**Comment by kgtkr** [comment]
Thank you
