### ISSUE TITLE
Iteration methods missing from ReadonlyMap and ReadonlySet.

### ISSUE THREAD

**Issue by lddubeau** [Microsoft/TypeScript#14602]
**TypeScript Version:**  2.2.1
**Code**

```ts
const x: ReadonlyMap<number, string> = new Map([[1, "a"], [2, "b"]]);

for (const k of x.keys()) {
  console.log(k);
}
```

**Expected behavior:**

No error.

**Actual behavior:**

```
error TS2339: Property 'keys' does not exist on type 'ReadonlyMap<number, string>'.
```

`ReadonlyMap` and `ReadonlySet` both lack all the methods that return iterators. `Map` has this set:

```
interface Map<K, V> {
    [Symbol.iterator](): IterableIterator<[K,V]>;
    entries(): IterableIterator<[K, V]>;
    keys(): IterableIterator<K>;
    values(): IterableIterator<V>;
}
```

There's an similar set of declarations for `Set`. None of these should be modifying the `Map` or the `Set` so they should be available on the readonly versions too.

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.
