### ISSUE TITLE
Publishing a npm package with multiple declaration files each of which supports a distinct version of TypeScript

### ISSUE THREAD

**Issue by kimamula** [microsoft/TypeScript#14603]
There was a problem with publishing declaration files for multiple versions of TypeScript under @types organization, which had been solved a few month ago.

https://github.com/Microsoft/types-publisher/issues/214

Is something similar possible when including declaration files in a npm package?
If TypeScript does not provide a such feature currently, I would like to request the feature.

It would also be helpful if tsc could emit declaration files for lower versions of TypeScript by specifying the versions in compiler options.

**Comment by RyanCavanaugh** [comment]
This is supported with `typesVersions` now
