### ISSUE TITLE
Typescript Error No best common type exists among return expressions.

### ISSUE THREAD

**Issue by IAmNoP** [Microsoft/TypeScript#14609]
Hello, I feel like there is a bug here. please let me know :).
A bit of class inception.

The principals:
the class Number is a CalcNode;
push requires a CalcNode return;
push local variable is a CalcNode;

I have a multiple "if" condition with "else" at the end. It seems like a "no condition" return is attended.

```
Typescript Error
No best common type exists among return expressions.
src/pages/calculator/engine/number.class.ts
  push(new_value: CalcNode){
    if(new_value.get_priority() === Priority.THREE){
```

```
export class Number implements CalcNode {
  value: string = "";
  priority: Priority = Priority.THREE;

  constructor(new_value: string){
    this.value = new_value;
  }

  get_priority(){
    return this.priority;
  }

  push(new_value: CalcNode){
    if(new_value.get_priority() === Priority.THREE){
      this.value += ""+new_value.evaluate();
      return this;
    }
    else if (new_value.get_priority() === Priority.ZERO){
      var temp: CalcNode =  new Multiply();
      temp.push(this);
      temp.push(new Parenthese());
      return temp;
    }
    else {
      return new_value.push(this);
    }
  }
```

**Comment by kitsonk** [comment]
Try annotating your return of the method `push()`, because it will help highlight where the compiler is getting confused.  I suspect it is the circular logic in trying to identify the return type of `push()` that is causing it to be confused.

**Comment by ahejlsberg** [comment]
If you post a complete example we can take a look, however I don't think there is a bug here.

**Comment by halaproliu** [comment]
Hey, I have the same problem, when I use this following code, the same tip was appear, can you guys tell me how to fix this?Thx a lot!

**Comment by halaproliu** [comment]
Hey, I have the same problem, when I use this following code, the same tip was appear, can you guys tell me how to fix this?Thx a lot!
`export default class Chain {
    fn: any;
    successor: any;
    constructor (fn: any) {
        this.fn = fn;
        this.successor = null;
    }

    setNextSuccessor (successor: any) : any {
        this.successor = successor;
        return this.successor;
    }

    passRequest ():any {
        let ret = this.fn.apply(this, arguments);
        if (ret === 'nextSuccessor') {
            return this.successor && this.successor.passRequest.apply(this.successor, arguments);
        }
    }
}`

**Comment by halaproliu** [comment]
Hey, I have the same problem, when I use this following code, the same tip was appear, can you guys tell me how to fix this?Thx a lot!
`export default class Chain {
    fn: any;
    successor: any;
    constructor (fn: any) {
        this.fn = fn;
        this.successor = null;
    }

    setNextSuccessor (successor: any) : any {
        this.successor = successor;
        return this.successor;
    }

    passRequest ():any {
        let ret = this.fn.apply(this, arguments);
        if (ret === 'nextSuccessor') {
            return this.successor && this.successor.passRequest.apply(this.successor, arguments);
        }
    }
}`

**Comment by halaproliu** [comment]
Hey, guys!I have the same problem when I use the following code!Please tell me how to fix this!Thx!`export default class Chain {
    fn: any;
    successor: any;
    constructor (fn: any) {
        this.fn = fn;
        this.successor = null;
    }

    setNextSuccessor (successor: any) : any {
        this.successor = successor;
        return this.successor;
    }

    passRequest ():any {
        let ret = this.fn.apply(this, arguments);
        if (ret === 'nextSuccessor') {
            return this.successor && this.successor.passRequest.apply(this.successor, arguments);
        }
    }
}`
