### ISSUE TITLE
Promises are not checked for null/undefined on assignment

### ISSUE THREAD

**Issue by wkrueger** [Microsoft/TypeScript#14605]
TS version: 2.2.1
strict null checks on

Is this desired/expected behavior?

```typescript
let p1: Promise<number|undefined> = Promise.resolve(undefined)
let p2: Promise<number>

p2 = p1
//no error. Expected "cannot assign number|undefined to number" 
```

**Comment by ahejlsberg** [comment]
Duplicate of #13513. We still thinking about the best way to resolve this issue.

**Comment by wkrueger** [comment]
thx!
applying the "branding" workaround for now, just found it from https://github.com/Microsoft/TypeScript/issues/9953
```typescript
interface Promise<T> { __promiseBrand: T }
```
