### ISSUE TITLE
Decorators within mixins

### ISSUE THREAD

**Issue by Eric-W0** [Microsoft/TypeScript#14607]
I wonder if there's any plans to support decorators within mixins?

```typescript
  type Constructor<T> = { new (...args: any[]): T }

  function Mixin<T extends Constructor<{}>>(Base : T) {
    return class extends Base {
      constructor(...args: any[]) {
        super(...args)
      }

      @decorator
      get y() {
        return this.x + 3
      }
  }
```

TSC 2.2.1 currently rejects this construction: [Decorators are not valid here]

**Comment by Hotell** [comment]
We got into same issues here https://github.com/wc-catalogue/blaze-elements/blob/master/packages/common/mixins.ts#L10

the quickfix is easy just define the mixin class and return it afterwards:

```ts
  type Constructor<T> = { new (...args: any[]): T }

  function Mixin<T extends Constructor<{}>>(Base : T) {
    class MixinClass extends Base {
      constructor(...args: any[]) {
        super(...args)
      }

      @decorator
      get y() {
        return this.x + 3
      }
  }
  
  return MixinClass;
}
```

**Comment by Eric-W0** [comment]
Ah, Wonderful!

Thanks!

**Comment by Hotell** [comment]
Hmm I would rather keep it open to get core team opinion on this cc @RyanCavanaugh @DanielRosenwasser  - if it's desing limitation or bug.
What I suggested is just "hotfix" to not get stuck

thx!

**Comment by Eric-W0** [comment]
True.

**Comment by aluanhaddad** [comment]
See https://github.com/Microsoft/TypeScript/issues/7342

**Comment by DanielRosenwasser** [comment]
I think the idea that decorators can inform the type system of changes that it may be performing is something we will be considering over time.

**Comment by Hotell** [comment]
Cool so I guess we can close this and reference the hotfix to #7342  ?

**Comment by DanielRosenwasser** [comment]
Sorry, I misread this. My previous comment has nothing to do with this, but yeah, looks like #7432 seems like the right place to discuss the issue.
