### ISSUE TITLE
Autocompletion in subclass for method overriding / declaration

### ISSUE THREAD

**Issue by aight8** [Microsoft/TypeScript#14618]
**TypeScript Version:**  2.3 / nightly

**Code**

### Example 1 (implementation suggestion):
```ts
interface AI {
    methodA(): void;
}

class A implements AI {
    /*|*/
}
```

### Example 2 (method overriding suggestion):
```ts
class A {
    methodA() {

    }
}

class B {
   /*|*/
}
```

### Example 3 (member and static properties **override** and **declaration** suggestion):
```ts
class A {
    static someStaticValue: number;
    someValue: number;
}

class B {
   /*|*/
}
```

### Example 4 (member and static properties type suggestion):
```ts
class A {
    static someStaticValue: { a: number, b: string };
    someValue: { a: number, b: string };
}

class B {
   static someStaticValue = { /*|*/ } // suggest possible property type property keys
   someValue = { /*|*/ } // suggest possible property type property keys
}
```

**Expected behavior:**
```/*|*/``` is the cursor position. If the cursor is direct inside a class the autocompletion request should list all 1) public/protected methods 2) public/protected properties 3) public/protected static properties of the parent class.
If the parent class

**Actual behavior:**
No autocompletion (it shows the default autocompletion list of everything)

----
*side notes*
Ideally the access modificators should be suggested too so the IDE can automatically generate the whole method signature.

**Comment by RyanCavanaugh** [comment]
Duplicate #7158
