### ISSUE TITLE
Type inference broke down in Visual Studio 2017

### ISSUE THREAD

**Issue by ArtemAvramenko** [Microsoft/TypeScript#14629]
**TypeScript Version:**  2.1.1

**Code**

```ts
class A {

    func(callback: () => void);
    func(callback: (code: number) => void);
    func(callback: Function) {
    }

    test() {
        this.func(code => { });
    }
}
```

**Expected behavior:**
![typeinference2015](https://cloud.githubusercontent.com/assets/11413326/23854709/4e2d5ffc-07fb-11e7-9fa9-8241587c4f2e.png)

**Actual behavior:**
![typeinference2017](https://cloud.githubusercontent.com/assets/11413326/23854713/530999e6-07fb-11e7-8b94-dc3a15bb424f.png)

**Comment by mhegazy** [comment]
If i were to guess, your VS 2015 was using 2.0 or earlier, your VS 2017 is using 2.1. If so, you can find more details about this in https://github.com/Microsoft/TypeScript/issues/11936.

it has always been `any`, the parameter help was showing the wrong overload in this case, but at build time the type was `any` silently, with TS 2.1, you should get an error under `--noImplicitAny`.

**Comment by ArtemAvramenko** [comment]
Why it is `any`? Function has two overloads, one of them is parameterless. If I specify parameter, it is definitely second overload with `number` parameter.

**Comment by mhegazy** [comment]
#11936 has discussion on why overload resolution works this way. it is mostly a design limitation. It is important to note, that previously it was `any` (though your hover in VS told you it was number), now it is still `any`,  but will consistently report an error if `--noImplicitany` is enabled.
