### ISSUE TITLE
Typescript compiler is compiling files automatically.

### ISSUE THREAD

**Issue by bhubanstha** [Microsoft/TypeScript#14623]
**TypeScript Version:**  2.2.1 
**Visual Studio:** 2017 Community Edition

**Typescript Configuration**
{
  "compilerOptions": {
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "module": "system",
    "lib": ["es5", "es2015", "dom"],
    "moduleResolution": "node",
    "noImplicitAny": false,
    "noEmitOnError": false,
    "removeComments": false,
    "sourceMap": false,
    "target": "es5"
  },
  "exclude": [
    "node_modules",
    "wwwroot"
  ],
  "compileOnSave": false
}

**Expected behavior:**
Typescript compiler should not compile any typescript file located in a project.

**Actual behavior:**
Typescript compiler compiled typescript file and generated JavaScript file.

**Comment by mhegazy** [comment]
Is the tsconfig added to your project? And is its content type: "Content"?
