### ISSUE TITLE
Proposal: emit warning or error when coercing array to boolean

### ISSUE THREAD

**Issue by realyze** [Microsoft/TypeScript#14638]
typescript@2.1.6

This snippet compiles without any warning:
```typescript
const result: string[] = gimmeResult(); // returns an array type
if (!result) { 
 // code
}
```

And I'd argue it's almost always a masked bug (the programmer did not realise the return value was an array).

Would it be sensible to emit some sort of a warning?

**Comment by mhegazy** [comment]
and `if (result) { ..` is not allowed either?

**Comment by RyanCavanaugh** [comment]
Duplicate #9041 ?

**Comment by RyanCavanaugh** [comment]
Or #14114

**Comment by realyze** [comment]
@mhegazy Yeah, good point. :-) I would say any `array -> boolean` coercion is a code smell and most probably a bug.

@RyanCavanaugh Thanks. Man, you must have a really good memory. :-D

**Comment by RyanCavanaugh** [comment]
I just keep all the issue numbers scrawled on a scrap of paper near my desk :wink:

**Comment by aluanhaddad** [comment]
@RyanCavanaugh the hyperspace I<sup>n</sup> | n ∈ Z ≥ 14638 over the field of Typescript issues reduced to a single flat physical object 😲

**Comment by realyze** [comment]
@RyanCavanaugh Man, you must have a really large desk. :)

**Comment by realyze** [comment]
At work:

![image](https://cloud.githubusercontent.com/assets/596749/23885213/cf2180b4-08c5-11e7-94ea-bf291de19dc9.png)

...sorry couldn't help it, I'll stop spamming now :-)
