### ISSUE TITLE
Bad null error in destructuring

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#14630]
**TypeScript Version:**  nightly (2.3.0-dev.20170313)

**Code**

```ts
interface A {
    foo?: { x: number };
    bar?: { y: number };
}

function f(a: A) {
    if (a.foo && a.bar) {
        const xx = a.foo.x; const yy = a.bar.y; // No error
        const { foo: { x }, bar: { y } } = a; // Error
    }
}
```

**Expected behavior:**

No errors.

**Actual behavior:**

```
a.ts(9,24): error TS2459: Type '{ x: number; } | undefined' has no property 'x' and no string index signature.
a.ts(9,36): error TS2459: Type '{ y: number; } | undefined' has no property 'y' and no string index signature.
```

May be related: #12620, #6784

**Comment by mhegazy** [comment]
This is a design limitation. The narrowing expression only narrows a.foo and not a itself; so when the destructring happens you still have the undefined. I will try to look up the original issue later for you.
