### ISSUE TITLE
IntelliSense wrongly highlight object properties with names starting with reserved keyword "let"

### ISSUE THREAD

**Issue by gibbok** [Microsoft/TypeScript#14649]
**TypeScript Version:**  2.2.1 / nightly (2.2.0-dev.201xxxxx)

**Code**

```ts
var cssWdgNode = {
    letterSpacing: 10
};
```

**Expected behavior:**
IntelliSense in Visual Studio should highlight with a different color (blue in the example image) only the reserved keyword "var". 

**Actual behavior:**
IntelliSense in Visual Studio highlights with a different color (blue in the example image) the reserved keyword "var" (right behavior) and also the beginning of an property for an object "letterSpacing"  as the property name contains the reserved keyword "let" (wrong behavior).

Example shows the wrongly highlighted property name:

![2017-03-14 11_25_47-src - microsoft visual studio](https://cloud.githubusercontent.com/assets/17195702/23896347/5bd0988c-08a9-11e7-86da-8e5093905ad9.png)

--- 
More info on environment:
Windows 10 Anniversary Update.

Microsoft Visual Studio Community 2017
Version 15.0.26228.4 D15RTWSVC
Microsoft .NET Framework
Version 4.6.01055

Installed Version: Community

Visual Basic 2017   00369-60000-00001-AA927
Microsoft Visual Basic 2017

Visual C# 2017   00369-60000-00001-AA927
Microsoft Visual C# 2017

Add New File   3.5
The fastest and easiest way to add new files to any project - including files that start with a dot

ASP.NET and Web Tools 2017   15.0.30223.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   1.0
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.50127.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.30209.0
Azure App Service Tools v3.0.0

Bundler & Minifier   2.4.340
Adds support for bundling and minifying JavaScript, CSS and HTML files in any project.

Common Azure Tools   1.9
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

CSS Tools   1.0.14
Provides additional features to the CSS editor in Visual Studio.

EditorConfig Language Service   1.15.194
Language service for .editorconfig files.

EditorConfig helps developers define and maintain consistent coding styles between different editors and IDEs.

File Icons   2.5
Adds icons for files that are not recognized by Solution Explorer

File Nesting   2.6.67
Automatically nest files based on file name and enables developers to nest and unnest any file manually

FormatDocumentOnSave   1.0
Enables auto formatting of the code when you save a file. Visual Studio supports auto formatting of the code with the CTRL+E,D or CTRL+E,F key shortcuts but with this extension the command 'Format Document' is executed on Save.

You can find the source here: https://github.com/Elders/VSE-FormatDocumentOnSave

GitHub.VisualStudio   2.1.1.4
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

HTML Tools   1.0.3
Productivity tools for the HTML editor

Image Optimizer   3.6.103
Uses industry standard tools to optimize any JPEG, PNG and Gifs - including animated Gifs. Can do both lossy and lossless optimization.

Image Sprites   1.4.47
Boost your website's performance by creating image sprites to reduce the amount of HTTP requests needed.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript Transpiler   0.8.20
The simplest way to transpile JS and JSX to EcmaScript 5 without any complicated node.js tools in your project. It uses the TypeScript compiler behind the scenes.

Markdown Editor   1.11.201
A full featured Markdown editor with live preview and syntax highlighting. Supports GitHub flavored Markdown.

Node.js Tools   1.3.50201.08
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   4.0.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Open Command Line   2.1.179
Opens a command line at the root of the project. Support for all consoles such as CMD, PowerShell, Bash etc. Provides syntax highlighting, Intellisense and execution of .cmd and .bat files.

Package Installer   2.0.99
Makes it easier, faster and more convenient than ever to install Bower, npm, Yarn, JSPM, TSD, Typings and NuGet packages to any project

Package Security Alerts   1.0.17
Identifies npm and Bower packages that contains known security vulnerabilities to ensure your project is always using the most secure package versions.

Project File Tools   1.0.1
Provides Intellisense and other tooling for XML based project files such as .csproj and .vbproj files.

SQL Server Data Tools   15.1.61702.140
Microsoft SQL Server Data Tools

Syntax Highlighting Pack   2.5.113
Adds syntax highlighting and snippet support for a wide variety of programming languages such as Clojure, Go, Jade, Lua, Swift, Ruby and many more...

TypeScript   2.1.5.0
TypeScript tools for Visual Studio

Vue.js Pack 2017   1.0.5
Contains HTML Intellisense and code snippets for the Vue.js JavaScript library

Web Accessibility Checker   1.4.47
The easiest way to perform accessibility checks on any ASP.NET web application. Fully customizable and support all the major international accessibility standards.

Web Compiler   1.11.326
Compiler for LESS, Sass and CoffeeScript files

ZenCoding   1.2.11
Provides ZenCoding for the HTML Editor - full support for static HTML, Razor and WebForms.

**Comment by RyanCavanaugh** [comment]
Odd, I can't repro this

![image](https://cloud.githubusercontent.com/assets/6685088/24056802/5131a302-0b02-11e7-8d0c-80f4ff8bc446.png)

Can you try running with all extensions disabled?

**Comment by gibbok** [comment]
I have disabled all extensions and enabled each one separately restarting VS each time.
Oddly enough, I cannot reproduce any longer the issue reported as the highlight work fine now.
I had tested on VS default dark-theme.

Please let me know if I could provide you more information.
Thanks for your time.
