### ISSUE TITLE
Document how to get code actions working like in your blog video example

### ISSUE THREAD

**Issue by xnnkmd** [Microsoft/TypeScript#14648]
**TypeScript Version:**  2.2.1

The typescript [blog](https://blogs.msdn.microsoft.com/typescript/2017/02/22/announcing-typescript-2-2/) shows a VS code video of "goodness to your editor. This release introduces some more useful quick fixes (also called code actions) which can guide you in fixing up pesky errors". 

It is not clear how to enable the shown behavior and listed quick fixes in VS Code ? Which specific plugin(s) should be installed ?

**Comment by mhegazy** [comment]
You can see all the new quickfixes if you are using VSCode insiders (https://code.visualstudio.com/insiders); or by setting your VSCode to use TS 2.2. (see [Using Newer TypeScript Versions](https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions) documentation for more details on updating your VSCode to use a different version of TypeScript).
