### ISSUE TITLE
Suggestion: Add an 'any until I come back to it' type with a corresponding flag to make it an error

### ISSUE THREAD

**Issue by benstevens48** [Microsoft/TypeScript#14645]
I've been avoiding using noImplicitAny for the following reason: I would end up typing a lot of stuff explicitly as any just to get it working, then when I came back to it to put in a better type, it would look like I'd already typed it.

To solve this, it would be useful add another type that has the same effect as any (perhaps anz, for ansatz!), but is meant to be used by the developer as a temporary measure before going back and putting a better type in. Then there could be a flag which would highlight any instances of this type as an error if turned on. This would allow me to use noImplicitAny without the above concern.

**Comment by benstevens48** [comment]
Actually, just realised I could effectively do this myself by adding a type alias for any, but still could be useful as an official feature.

**Comment by poseidonCore** [comment]
I do exactly the same thing, but I solve this by just defining an ambient type AnyObject, which is easy enough to search for later on and replace with a more refined type.

declare type AnyObject = any;

Over-crowding the type system with pseudo types may be counter-productive.

**Comment by RyanCavanaugh** [comment]
The type alias for any is the recommended way to do this. Enabling another type + another flag doesn't provide any extra value compared to the type alias + a simple grep, at the cost of extra complexity, so we'd rather not do this unless there's some new scenario enabled.

**Comment by benstevens48** [comment]
Yes that makes sense. It might be useful to suggest this approach somewhere in the documentation relating to noImplicitAny (assuming it isn't already suggested), to save people from having to rediscover this idea themselves.
