### ISSUE TITLE
Suggestion : allows declare variables by regex pattern

### ISSUE THREAD

**Issue by ifle** [Microsoft/TypeScript#14644]
**TypeScript Version:**  2.2.1 / nightly (2.2.0-dev.201xxxxx)

Will be very helpfull for migration of legacy applications that used global ID html objects ability to define the declaration name by regex.

**Expected behavior:**
```ts
var declare /(tbl|cmb)\w+/ : HTMLElement;

tblControl.innerHTML = ""
```
**Actual behavior:**
```ts
var declare tblControl1 : HTMLElement;
var declare tblControl2 : HTMLElement;
var declare cmdControl1 : HTMLElement;
--more--
```

**Comment by poseidonCore** [comment]
I agree, but given how complex RegExp can become, this may create performance lags and unresolvable conflicts in the type comprehension phase in TypeScript itself given that the process would mean "If a type annotation/assertion does not literally match an existing type then compare this against a hierarchy of RegExp types regressively".

If you have just a few RegExp types, then I think that's workable, but imagine using RegExp types in nested/distributed interfaces and namespaces ... where there may be more than one RegExp type that may match a given literal usage ... what takes precedence in the matching algorithm ... ambient vs local vs first declared vs last declared ... and then apply union and intersection rules on top of that.

**Comment by RyanCavanaugh** [comment]
This doesn't seem common enough (to say nothing of whether or not this is even a *good* way to solve the issue presented -- surely the list is finite?) to justify massively complicating the compiler's name resolution process.
