### ISSUE TITLE
default type parameters for type aliases, interfaces and functions

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#14653]
currently only classes can have default type parameters, allow default type parameters on interfaces, type aliases and functions too

**Comment by RyanCavanaugh** [comment]
@rbuckton I was sort of surprised this wasn't implemented with your other changes -- thoughts?

**Comment by rbuckton** [comment]
Default type parameters should work fine for Type Aliases, Interfaces, and Functions. See the [test case](https://github.com/Microsoft/TypeScript/blob/master/tests/cases/compiler/genericDefaults.ts). Are there specific cases where this is not working?

**Comment by rbuckton** [comment]
Specific examples:

* [function](https://github.com/Microsoft/TypeScript/blob/master/tests/cases/compiler/genericDefaults.ts#L33)
* [interface](https://github.com/Microsoft/TypeScript/blob/master/tests/cases/compiler/genericDefaults.ts#L397)
* [class](https://github.com/Microsoft/TypeScript/blob/master/tests/cases/compiler/genericDefaults.ts#L455)
* [type alias](https://github.com/Microsoft/TypeScript/blob/master/tests/cases/compiler/genericDefaults.ts#L461)

**Comment by aleksey-bykov** [comment]
here is what i see:

![image](https://cloud.githubusercontent.com/assets/937933/23919447/3c81a88a-08cd-11e7-87b0-fa9211415724.png)


![image](https://cloud.githubusercontent.com/assets/937933/23919485/5ed8a9b0-08cd-11e7-9799-8e9a8c1b7b82.png)


supid VSCode turned out it was set up to use 2.2.1 version, ignoring `tsdk` parameter in `settings.json`


sorry for troubles
