### ISSUE TITLE
Path resolution after build

### ISSUE THREAD

**Issue by Clowning** [Microsoft/TypeScript#14651]
Hi there,

This is my problem : I use Path resolution in my TypeScript app like this => 

```
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es5",
    "pretty": true,
    "outDir": "./build",
    "baseUrl": ".",
    "paths": {
      "Internal/*": ["./src/*"]
    }
  }
}
```

And when i import my module i write that => 

```
import * as Interfaces from 'Internal/Interfaces';
```

My problem is, when i build my project with the tsc command, i can execute my js native file because import path are the same ! So, i have forgot something or ???

Thanks!

**Comment by vladima** [comment]
not sure that  I understand the problem correctly. Path mappings were introduced to address the issue with flexible module loading in runtime when loader can map module id from the source code to a physical file using some additional configuration (i.e. via `paths` section in SystemJS or RequireJs). Module imports are never altered by the compiler - it assumes that whatever was written by user is correct and will apply`baseUrl`, `paths` and `rootDirs` to map this module id to a file to be used as type infor for module in design time.

**Comment by Clowning** [comment]
@vladima  Mhhh ok i understand but, when i compile my code how can i change this path by absolute path ? :/ !

**Comment by mhegazy** [comment]
Presumablly you have a babel-plugin or some post-build script that updates the reference. the setting here is just to "tell" the compiler what happens at build time.

**Comment by Clowning** [comment]
Ok great ! Thanks for your help :-)
