### ISSUE TITLE
Unavoidable Type System Design limitation?

### ISSUE THREAD

**Issue by Artazor** [Microsoft/TypeScript#14656]
**TypeScript Version:**  2.2.1 / nightly (2.2.0-dev.201xxxxx)

**Code**

```ts
type Pair<T> = {fisrt:T, second: T}
var x: Pair<string> | Pair<number>;
x.fisrt = 1;
x.second = "A"; // corrupted semantic state
```

**Expected behavior:**

Type system should prevent creating invalid values 

**Actual behavior:**

type system designed as 
```
{a: A1, b: B1} | {a: A2, b: B2}   ->   {a: A1|A2, b: B1|B2 }
```

Is it a lesser evil, that will be always with us?
Any chances to get more sophisticated control-flow driven narrowing (generalization of discriminated unions)?
However it looks too complex... 
Arrrgh!

**Comment by RyanCavanaugh** [comment]
See #1394
