### ISSUE TITLE
String literal type argument inference is too greedy

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#14659]
Version: 2.3.0-dev.20170308

**Background**: Right now I want to be able to take an array of string literals, or a plain object whose keys will map to some "validator" ([see Vue's `props` for an example API](https://vuejs.org/v2/api/#props)).

In either case, I want to take the string literals from the array or the keys from the object to create a brand new object.

```ts
interface Validator {
    validationFunction: (x: any) => boolean
}

declare function foo<K extends string>(x: K[] | Record<K, Validator>): Record<K, any>;

let newObj = foo(["hello", "world"])
```

**Expected**: `newObj` has only properties named `hello` and `world`.
**Actual**: `newObj` also has properties from `Array`.

What I'd like in the above case is that TypeScript infers `"hello" | "world"` for `K`, and gives me an object with the shape `{ hello: any, world: any }`. Unfortunately, `K` *also* includes properties like `length`, `splice`, `map`, and `forEach`. It appears that TypeScript making inferences for `K` from the properties of `Array` as well.

I understand that right now TypeScript makes as many inferences as it can to try to correctly check parameter assignability later on, and doesn't backtrack in the process. Is there any way to get around this/mitigate the issue?

@ahejlsberg @sandersn @mhegazy

**Comment by ahejlsberg** [comment]
Did you consider using overloads?

```ts
declare function foo<K extends string>(x: K[]): Record<K, any>;
declare function foo<K extends string>(x: Record<K, Validator>): Record<K, any>;
```

**Comment by DanielRosenwasser** [comment]
I did think of doing so, and I was about to write up why I didn't want to... but instead, I decided to try it out.

Well, I did it, and it's horrendous. But it ***does*** work!

To elaborate, I need to have two overloads for:

* `Vue`'s construct signatures
* `Vue.component`
* `Vue.extend`

Each of those overloads uses one of the following helper type:

```ts
export type ThisTypedComponentOptionsWithRecordProps<Data, Methods, Computed, Props, Instance extends AnyVue = Vue<Data, Methods, Computed, Props>> =
  ComponentOptions<Data, Methods, Computed, Props> &
  ThisType<Data & Methods & Computed & Props & Instance>;

export type ThisTypedComponentOptionsWithArrayProps<Data, Methods, Computed, Props extends string, Instance extends AnyVue = Vue<Data, Methods, Computed, Props>> =
  ComponentOptions<Data, Methods, Computed, Props[]> &
  ThisType<Data & Methods & Computed & Record<Props, any> & Instance>;
```

As an example, the Vue constructor has the following overloads:

```ts
  new <Data, Methods, Computed, PropNames extends string = never>(options?: ThisTypedComponentOptionsWithArrayProps<Data, Methods, Computed, PropNames>): Data & Methods & Computed & Record<PropNames, any> & Vue<Data, Methods, Computed, Record<PropNames, any>>;
  new <Data, Methods, Computed, Props>(options?: ThisTypedComponentOptionsWithRecordProps<Data, Methods, Computed, Props>): Data & Methods & Computed & Record<keyof Props, any> & Vue<Data, Methods, Computed, Record<keyof Props, any>>;
```

**Comment by DanielRosenwasser** [comment]
Actually, this gets very insane. In addition to a `ThisTypedComponentOptions`, there's also a `FunctionalComponentOptions` which would also need to undergo the same procedure, but I'll keep chugging at it.

**Comment by andy-ms** [comment]
@DanielRosenwasser Does this still need to be open? Compiling your original example today, I get `newObj: Record<"hello" | "world", any>` with no properties from `Array`.

**Comment by RyanCavanaugh** [comment]
Seems to have been fixed
