### ISSUE TITLE
Property 'outerHTML' missing from 'Element'

### ISSUE THREAD

**Issue by bradleyayers** [Microsoft/TypeScript#14667]
Seems related to https://github.com/Microsoft/TypeScript/issues/5754

MDN claims it exists on Element https://developer.mozilla.org/en-US/docs/Web/API/Element/outerHTML. It is missing from `lib.dom.d.ts`.

**Comment by httpdigest** [comment]
Cannot reproduce. Which version are you using? The latest release version 2.2.1 at least has it in lib/lib.dom.d.ts:7829

**Comment by mhegazy** [comment]
seems to exist on `Element` in latest: https://github.com/Microsoft/TypeScript/blob/2b10611fbfb63c4fe24d865dc275fec016af003e/lib/lib.dom.d.ts#L3606

**Comment by bradleyayers** [comment]
Apologies, this was indeed from 2.2.0-dev
