### ISSUE TITLE
TypeChecker returns incorrect flags & types on boolean type

### ISSUE THREAD

**Issue by novakf** [Microsoft/TypeScript#14668]
**TypeScript Version:**  2.2.1

While using the API & TypeChecker I have noticed strange behavior for boolean type in AST tree (see bellow). Is it correct? If so, is there a simple way how to reconstruct the original TypeScript code form AST with the boolean type instead of union type?

**Code**

Code used in test file:
```ts
function(): boolean { return false; }
function(): true | false { return false; }
function(): string | boolean { return "" }
```
Code using API:
```
let program: ts.Program = ts.createProgram(...);
let checker: ts.TypeChecker = program.getTypeChecker();
...
ts.forEachChild(node, (n: ts.Node) => {
   ...
   let t: ts.Type = checker.getTypeAtLocation(n.type);
   ...
}
```
**Expected behavior:**
for boolean:
```
t: ts.Type === {
   ...
   flags: TypeFlags.Boolean
   types: undefined
   ...
}
```
for: true | false
```
t: ts.Type === {
   ...
   flags: TypeFlags.Boolean | TypeFlags.Union
   types: [ { ... false ...}, { ... true ... } ]
   ...
}
```
for: string | boolean
```
t: ts.Type === {
   ...
   flags: TypeFlags.Union
   types: [ { ... string ...}, { ... boolean ... } ]
   ...
}
```
**Actual behavior:**
for: boolean (Incorrect)
```
t: ts.Type = {
   ...
   flags TypeFlags.Boolean | TypeFlags.Union
   types: [ { ... false ... }, { ... true ... } ]
   ...
}
```
for: true | false (Correct)
```
t: ts.Type = {
   ...
   flags: TypeFlags.Boolean | TypeFlags.Union
   types: [ { ... false ... }, { ... true ... } ]
   ...
}
```
for: string | boolean (Incorrect)
```
t: ts.Type = {
   ...
   flags: TypeFlags.Union
   types: [ { ... string ...}, { ... true ... }, { ... false ... } ]
   ...
}
```

**Comment by ahejlsberg** [comment]
The actual behavior you're seeing is intended. There is no difference between `boolean`, `false | true`, and `true | false`, they're just different ways of referencing the exact same type. In fact, `boolean` is effectively just a predefined type alias for `false | true`.

**Comment by ahejlsberg** [comment]
And, to answer your second question, there is no way to get back to the original AST representation from a type object.

**Comment by novakf** [comment]
Thanks for answer. A was afraid of it :) Actually, there is one way, but not ideal - it is .getText() of symbol which returns the exactly the same text as is defined in source.
