### ISSUE TITLE
How can use Type Checker get  Interface or Class extends type

### ISSUE THREAD

**Issue by myxvisual** [Microsoft/TypeScript#14666]
example code:
```` javaScript
class Animal {
    name: string;
}
class Dog extends Animal {
    breed: string;
}

interface DataProps {
    color?: string;
}

interface DogProps extends DataProps {
    type?: "Beagle" | "Sheepdog"；
}
````

in `Class` extends I can use check extends names:
```` javaScript
const symbol = this.checker.getSymbolAtLocation((<ts.ClassDeclaration> node).name);
const extendsDocEntry = "declarations" in symbol? symbol.declarations.map((declaration: any) => (
	"expression" in declaration && declaration.expression.text
)).filter((extendsName: any) => extendsName) : void 0;
````
but i do not know if this is the correct code.
and i still don't know how get  `Interface` extends.

Please help me solve this problem, very grateful.

**Comment by hherman1** [comment]
I'm not part of this project but I think you're meant to ask questions [here](http://stackoverflow.com/questions/tagged/typescript)

**Comment by myxvisual** [comment]
@hherman1 Thanks for your help, i will try, but i can not find any useful documentation and useful data in `symbol`

**Comment by RyanCavanaugh** [comment]
(n.b. names may not be exact, this is from memory) You can walk the `declarations` array to look for something that has a `kind === SyntaxKind.InterfaceDeclaration`; that node has an optional `heritageClauses` array which will have an element for the `extends DataProps` clause.

**Comment by dsherret** [comment]
@myxvisual I answered your question [here](http://stackoverflow.com/a/42823835/188246).

**Comment by RyanCavanaugh** [comment]
Please don't cross-post to SO without linking the question here - it creates duplication of effort.

**Comment by myxvisual** [comment]
@RyanCavanaugh @dsherret Very grateful, thanks
