### ISSUE TITLE
Array Access with strictNullChecks does not include 'undefined' type

### ISSUE THREAD

**Issue by hherman1** [Microsoft/TypeScript#14665]
**TypeScript Version:**  2.2.1 / nightly (2.2.0-dev.201xxxxx)

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
let x:number[] = [1,2,3]
let a = x[-1]
```

**Expected behavior:**
`a` has type `number | undefined`

**Actual behavior:**

`a` has type `number`

**Comment by RyanCavanaugh** [comment]
Duplicate #13778, **please search before logging new issues**

![image](https://cloud.githubusercontent.com/assets/6685088/23968299/69e21e60-097f-11e7-82b5-ad3d764be21f.png)
