### ISSUE TITLE
Add insertSpaceAfterTypeAssertion Formatting Option to TSServer Protocol

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#14661]
#10402 added a `insertSpaceAfterTypeAssertion` formatting setting. We'd like this exposed in the TSServer protocol so that users can configure it in VSCode: https://github.com/Microsoft/vscode/issues/10296

**Comment by csentis** [comment]
Could someone kindly pick this up? It has been a blocker for VScode to autoformat TS appropriately since August last year. Thanks greatly!

**Comment by mhegazy** [comment]
Sorry for the delay, fell off my list.

**Comment by lucap86** [comment]
Note that insertSpaceAfterTypeAssertion doesn't work with sintax 
<MyType>(a||b)
