### ISSUE TITLE
Interface or Class with only optional properties does not do type checking

### ISSUE THREAD

**Issue by tobalsgithub** [Microsoft/TypeScript#14673]
**TypeScript Version:**  2.1.4

**Code**

```ts
class AllOptionalClass {
  optional?: string;
}

let x = new AllOptionalClass();
x = 'asdf'; // good

class RequiredClass {
  requiredClass: string;
}

let y = new RequiredClass();
y = 'asdf'; // Type '"asdf"' is not assignable to type 'RequiredClass'

interface IAllOptional {
  optional?: string;
}

let a : IAllOptional = {
  optional: 'asdf'
};

a = 'asdf'; // good

interface IRequired {
  required: string;
}

let b : IRequired = {
  required: 'asdf'
};

b = 'asdf'; // Type '"asdf"' is not assignable to type 'IRequired'

```

**Expected behavior:**
I would expect `x = 'asdf';` to fail with the same error as `y = 'asdf';`, and I would expeect `a = 'asdf';` to fail with the same error as  `b = 'asdf';` 

**Actual behavior:**
A variable that has a type of a class or interface with all optional properties can have anything assigned to it as far as I can tell.

**Comment by tobalsgithub** [comment]
It may be worth noting that the way I came across this was actually in a class that implements an interface with only optional properties.

```ts
interface IAllOptional {
  optional?: string;
}

interface RecordClass {
  optional? : IAllOptional;
}

class AllOptional implements RecordClass {
  optional: number; // would expect this to be an error
}
```

**Comment by mhegazy** [comment]
Please see https://github.com/Microsoft/TypeScript/issues/7485
