### ISSUE TITLE
Incorrect formatting in fluent API call 

### ISSUE THREAD

**Issue by magnushiie** [Microsoft/TypeScript#14675]
**TypeScript Version:**  2.2.1

**Code**

Format the following code snippet using VS Code or typescript-formatter:
```ts
someVar
  .chain(
    'arg1',
    'arg2',
  )
  .chain(
    3,
    4,
  );
```

**Expected behavior:**
```ts
someVar
  .chain(
    'arg1',
    'arg2',
  )
  .chain(
    3,
    4,
  );
```

**Actual behavior:**
```ts
someVar
  .chain(
  'arg1',
  'arg2',
)
  .chain(
  3,
  4,
);
```

This is a common occurrence with fluent APIs (test frameworks, ORMs, etc) and tslint rules requiring trailing comma.

**Comment by magnushiie** [comment]
Note also that even without the trailing comma, the formatting is not correct:
```ts
someVar
  .chain(
  'arg1',
  'arg2'
  )
  .chain(
  3,
  4
  );
```

**Comment by SaschaNaz** [comment]
Duplicate of #5830

**Comment by magnushiie** [comment]
Indeed it's a duplicate of #5830, although the trailing comma here causes different formatting currently, so the fix should work with both with and without trailing comma - I will make a note on the other issue about this.
