### ISSUE TITLE
keyof doesn't work when using "this"

### ISSUE THREAD

**Issue by jmlee2k** [Microsoft/TypeScript#14672]
**TypeScript Version:**  2.2.1

**Code**

```ts
type TweenParams<T> = {[P in keyof T]?:number}

function tween<T>(obj:T,params:TweenParams<T>)
{
	//...
}

function testWorking()
{
	var obj = {'x':0,'y':0};
	tween(obj,{'x':20});	//works fine
}

class Actor
{
	public x:number;
	public y:number;

	public moveTo(x:number,y:number)
	{
		tween(this,{'x':x,'y':y}); //Argument of type '{ 'x': number; 'y': number; }' is not assignable to parameter of type 'TweenParams<this>'.
	}
}
```

**Expected behavior:**
the tween call in Actor::moveTo() should have no issues.

**Actual behavior:**
Argument of type '{ 'x': number; 'y': number; }' is not assignable to parameter of type 'TweenParams<this>'.

This is the first time I've used the keyof operator, so it's quite likely lack of experience on my part, but it seems to me like this should work.  

I'm not sure if this is of any help, but autocomplete does suggest the members of Actor, as expected.

**Comment by holi-java** [comment]
you can set the generic type implicitly.

```ts
tween<Actor>(this, {'x': x});
```

**Comment by jmlee2k** [comment]
@holi-java Thanks!  I figured something like this would work, but didn't actually try it. It works as expected, but it would be great if the compiler was able to figure it out without it.  I realize that may be complicated due to the nature of the "this" object, but I'll leave that to the professionals :).
