### ISSUE TITLE
Object.constructor should have a constructor type

### ISSUE THREAD

**Issue by JonathanMEdwards** [Microsoft/TypeScript#14674]
in lib.es6.d.ts:
interface Object {
    constructor: Function;

Shouldn't this be:
    constructor: { new (...args: any[]): any };

so that it is well-typed to say:
    new x.constructor

**Comment by mhegazy** [comment]
https://github.com/Microsoft/TypeScript/issues/3841?

**Comment by JonathanMEdwards** [comment]
more specifically dup of #4356
