### ISSUE TITLE
Proposal: for comprehension / do notation -> generalization of async/await

### ISSUE THREAD

**Issue by bgrieder** [Microsoft/TypeScript#14680]
Support for async/await provides a fantastic opportunity to write shorter more readable code when chaining Promises.

```typescript
async function getCompany(username: string): Promise<Company> {
    const user = await getUser(username)
    const company = await getCompany(user.companyName)
    return company
}
```
where 

```typescript
getUser: (username: string) => Promise<User>
getCompany: (companyName: string) => Promise<Company>
```

The same can be said for `for comprehensions` in Scala or its equivalent `do notation` in Haskell.

The semantics are pretty close to async/await and assuming we have a monad `Either[L,R]` (a.k.a. `Maybe` in Haskell), it would be fantastic to be able to write

```typescript
async function getCompany(username: string): Either<string, Company> {
    const user = await getUser(username)
    const company = await getCompany(user.companyName)
    return company
}
```
where 
```typescript
getUser: (username: string) => Either<string, User>
getCompany: (companyName: string) => Either<string, Company>       
//string holds the reason why the the record cannot be retrieved
```
Obviously `async` and `await` are probably not the best choice keywords and we could have more generic keywords, for instance `do` and `run`
```typescript
do function getCompany(username: string): Either<string, Company> {
    const user = run getUser(username)
    const company = run getCompany(user.companyName)
    return company
}
```

**Comment by aluanhaddad** [comment]
I would love to see some form of generalized monad comprehensions in the language but it needs to be proposed for introduction into a future version of ECMAScript, and championed by a TC39 member, before TypeScript can adopt it because it involves runtime behaviors and introduces new value level syntax. Consider proposing this feature on https://esdiscuss.org

**Comment by bgrieder** [comment]
@aluanhaddad 

>it needs to be proposed for introduction into a future version of ECMAScript

Is this really a firm requirement for Typescript ? After all `async/await` in TS compiles down to ES6, and now ES5, although the syntax is not supported by any of these ECMAScript versions.

Comprehensions really are syntactic sugar around `map` and `flatMap`, not really a new language feature

**Comment by Kovensky** [comment]
The downlevel emits are (most often partial) implementations of new language features.

**Comment by aluanhaddad** [comment]
> Comprehensions really are syntactic sugar around map and flatMap, not really a new language feature

> The downlevel emits are (most often partial) implementations of new language features, even if they look like sugar.

Speaking of which it's really annoying that there's no `Array.prototype.flatMap` after all these years.

**Comment by DanielRosenwasser** [comment]
> Is this really a firm requirement for Typescript 

Yes, it's really for the best.

> After all `async/await` in TS compiles down to ES6, and now ES5, although the syntax is not supported by any of these ECMAScript versions.

Sure, but it is part of today's ECMAScript, of which TypeScript is a superset.
