### ISSUE TITLE
Type of property is not inferred from base class

### ISSUE THREAD

**Issue by Lenne231** [Microsoft/TypeScript#14684]
**TypeScript Version:**  2.2.1

Is it possible to infer the type of `state` from the base class instead of being explicit?
This would be very useful for reactjs.

**Code**
![image](https://cloud.githubusercontent.com/assets/2046557/23995576/84c0e0a6-0a4a-11e7-9919-26f4ca9d0711.png)

**Expected behavior:**

`state` should be of type `{ tags: string[] }`

**Actual behavior:**

`state` is of type `{ tags: any[] }`

**Comment by Lenne231** [comment]
```typescript
class MyComponent extends Component<State> {
    state = { tags: [] }
}
```

**Comment by RyanCavanaugh** [comment]
#10570
