### ISSUE TITLE
TS2304: Cannot find name HTMLMediElement

### ISSUE THREAD

**Issue by monolithed** [Microsoft/TypeScript#14685]
Please add this interface very useful interface.
https://developer.mozilla.org/en/docs/Web/API/HTMLMediaElement

**Comment by senyaak** [comment]
Just check on v.2.2.1 the definition is there

**Comment by monolithed** [comment]
@senyaak, Have you tested yourself? Could you show a place where this interface is defined?

**Comment by senyaak** [comment]
@monolithed 
lib.d.ts:9804: interface HTMLMediaElement extends HTMLElement {.....
