### ISSUE TITLE
Ban class with empty type parameter list

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#14696]
**TypeScript Version:**  nightly (2.3.0-dev.20170316)

**Code**

```ts
class X<> {}
function f<>() {}
const x: X<> = new X<>();
```

**Expected behavior:**

All are errors.

**Actual behavior:**

All but `class X<> {}` are errors. We should consistently fail when a type parameter list is empty.

**Comment by misoguy** [comment]
I'd like to give this a shot if no one is already on it :)
