### ISSUE TITLE
Bad inferences with error TS2365

### ISSUE THREAD

**Issue by ghost** [Microsoft/TypeScript#14695]
**TypeScript Version:**  2.2.1

**Code**

```ts
class Foo {
  _elements: string[];

  constructor(input: string) {
    this._elements = input.split("");
  }

  get top(): string {
    return (this._elements.length > 0) ?
      this._elements[this._elements.length - 1] :
      "";
  }

  strip(): number {
    if (this.top == "$") {
      this._elements.pop(); // $
      let count = 0;
      while (this.top != "^") { // XXX TS2365
        ++count;
        this._elements.pop();
      }
      this._elements.pop(); // ^
      return count;
    }

    return 0;
  }
}

let f = new Foo("ba^z$");
console.log(f.strip());
```

**Expected behavior:**

Clean compilation, with no errors or warnings.

**Actual behavior:**

> foo.ts(18,14): error TS2365: Operator '!=' cannot be applied to types '"$"' and '"^"'.

**Comment by colbyrussell** [comment]
This may be related to issue #12794, or maybe not, but even if so, it looks like there's a lot of noise and casted aspersions wrt the testcases in that issue, rather than engineering.

**Comment by gcnew** [comment]
It is. See https://github.com/Microsoft/TypeScript/issues/9998#issuecomment-235963457

**Comment by RyanCavanaugh** [comment]
Duplicate #13904 / we don't keep open issues from :ghost: s, too spooky
