### ISSUE TITLE
HTMLElement.onclick property require 'this' as parameter name.

### ISSUE THREAD

**Issue by Oopsxy** [Microsoft/TypeScript#14704]
**TypeScript Version:**  2.2.1 / nightly (2.2.0-dev.201xxxxx)

**Code**

```ts
// A *self-contained* demonstration of the problem follows...

class FooClass {
    foo() {
        var table = <HTMLTableElement>document.getElementById("table_name");
        var row = table.insertRow(i);
        var cell = row.insertCell(0);
        cell.onclick = this.cell_Click;
    }
    
    cell_Click(sender: HTMLElement, event: MouseEvent): any {
        // some code
        if (!sender.classList.contains("someclass")) {
            sender.classList.add("someclass");
        }
    }
}
```
I receive the message: 

> Type '(sender: HTMLElement, event: MouseEvent) => any' is not assignable to type '(this: HTMLElement, ev: MouseEvent) => any'.

**Expected behavior:**
I expect that the compiler will accept the code above 

**Actual behavior:**
I am getting the error message:

> Type '(sender: HTMLElement, event: MouseEvent) => any' is not assignable to type '(this: HTMLElement, ev: MouseEvent) => any'.

If i change the parameter name of 'sender' to 'this' then the compiler accept that without any error. But i can choose the parameter name of 'event' freely and the compiler will accept that.

**Comment by shadeglare** [comment]
Actually you misread the type signature of the `onclick` method. `this: HTMLElement` is an implicit argument that will be passed automatically like:

```typescript
let x = <HTMLElement>elem;
x.onclick = function(e) {
  this.classList.add("new_class");
};
```

And `e` is going to be those `MouseEvent` type.

**Comment by senyaak** [comment]
How about that?
```ts
class FooClass {
    foo() {
        var table = <HTMLTableElement>document.getElementById("table_name");
        var row = table.insertRow(1);
        var cell = row.insertCell(0);
        cell.onclick = this.cell_Click;
    }

    cell_Click(event: MouseEvent): any {
        // some code
        if (!event.srcElement.classList.contains("someclass")) {
            event.srcElement.classList.add("someclass");
        }
    }
}

```
I think "this" argument is passed to declare function scope what is important for events.

**Comment by Oopsxy** [comment]
Yes renaming `sender` to `this` would solve the problem that the compiler will accept the code but then i am not able to call class functions. That was the meaning of the `// some code` comment.

@senyaak your suggestion works fine for me, thanks a lot.
