### ISSUE TITLE
Bug suggestion: Class setter

### ISSUE THREAD

**Issue by senyaak** [Microsoft/TypeScript#14708]
Im not sure if this is a bug:
```ts
class A {
  set Setter(value) {
    value = this.Setter;
  }
}
```

This code cause endless loop. But the compiler do not show anything. I didn't find anything about this.Probably it is correct, but to be sure I'll create this ticket :)

**Comment by RyanCavanaugh** [comment]
Not a bug. Getters / setters can be recursive - they just have to have a base case, which we don't have any means of detecting.
