### ISSUE TITLE
Formatting tests ignored?

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#14712]
The files in `src/harness/unittests/services/formatting` don't seem to be used.
They seem to be using an older version of the API, and reference files that no longer exist.
They are also badly in need of linting (they are currently excluded from the command in #14711).

**Comment by mhegazy** [comment]
I would just delete these. we had these during the 1.0-1.1 rewrite and never turned them on again. i would also remove `tests/cases/fourslash-old`.

**Comment by andy-ms** [comment]
Tests in `harness/unittests/services/*.ts` don't seem to run either, although they don't have compile errors. Are they salvageable?

**Comment by mhegazy** [comment]
These should work. and we should turn them on again.

**Comment by andy-ms** [comment]
Looks like those tests are running, they just weren't getting recompiled for some reason.
