### ISSUE TITLE
`jake lint` isn't linting everything

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#14711]
`jake lint` and `gulp lint` don't seem to be catching all (any?) lint errors.
The following command *will* work:

```
node_modules/tslint/bin/tslint 'src/**/*.ts' --exclude 'src/lib/*.generated.d.ts' --exclude 'src/harness/unittests/services/formatting/**/*.ts' --exclude 'src/harness/unittests/services/formatting/*.ts' --format stylish
```

Why don't we just use that? Tslint is fast enough now that we don't really need a parallelized linter.

**Comment by mhegazy** [comment]
works for me.
