### ISSUE TITLE
Output .js files as read/execute only

### ISSUE THREAD

**Issue by ORESoftware** [Microsoft/TypeScript#14726]
Regarding this issue thread:
https://github.com/Microsoft/TypeScript/issues/843

It seems like it would be a nice-to-have to configure `tsc` to output .js files that were readonly/execute only. That would prevent people from editing the wrong file. (Editing the .js instead of editing the .ts/.tsx).

This will be especially useful in conjunction with a "preserveWhitespace" compiler option which would make the outputted .js files look much more like source code than before such an option.

So in the compiler options, I would like to see something like:

```js
{
  "compilerOptions": {
    "declaration": true,
    "permissions":{
      "read": true,
      "write": false,
      "execute": true
    }
}
```

or instead of that perhaps this:

```js
{
  "compilerOptions": {
    "permissions": "555",   // read and execute only

}
```

I suppose it's possible that someone may wish to write out js code that was no executable either, or whatever.

like I was saying - I haven't had too many problems as of yet editing the wrong files *but* with a "preserveWhitespace" option in place, it will be much more likely to happen to unsuspecting developers.

**Comment by mhegazy** [comment]
The compiler does not do file manipulation of this sort. i would recommend having a post-build step, or using a build driver like gulp or grunt to do that.
