### ISSUE TITLE
add a supertype constraint 

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#14728]
currently when we see a constraint `<A extends B>` it means A is a subtype of B, so that 
```typescript
declare var a: A;
declare var b: B;
b = a; // allowed
a = b; // not allowed
```
consider adding a new constraint of the reversed relation: `<A within B>` that would mean A is a supertype of B (or in other words B is subtype of A), so that:
```typescript
declare var a: A;
declare var b: B;
b = a; // not allowed
a = b; // allowed
```

**use case**

i have a `BigFatClass` with 50 methods and a 1 little property, now i want to run some assertions  over it, if i declare these assertions like `expect<T>()` and `toEqual<T>` of the same `T` then `toEqual` asks me for 50 methods that don't matter for the test, and that's the problem

what i need it to declare `expect<T>()` and `toEqual<U within T>()` so that i could simply write:
```typescript
expect(new BigFatClass()).toEqual({ value: true });
```

**Comment by aaronbeall** [comment]
Can't you use `Partial<T>` for your assertion?

**Comment by aleksey-bykov** [comment]
@aaronbeall yes, it should work for this very use case, thanks for an idea

**Comment by RyanCavanaugh** [comment]
Most recent one tracking this is #14520

**Comment by aleksey-bykov** [comment]
thanks
