### ISSUE TITLE
const variable in destructuring statement of object of type `any` is narrowed to string literal type.

### ISSUE THREAD

**Issue by bsouthga** [Microsoft/TypeScript#14721]
**TypeScript Version:**  2.2.1

**Code**

```ts
const params: any = {
    s3Operation: 'putObject',
};

const {
    s3Operation = 'getObject'
} = params;

// error here
if (s3Operation === 'putObject') {
    console.log('expected this to be ok');
}
```

**Expected behavior:**
No error, as s3Operation is of type string

**Actual behavior:**
Error, as s3Operation is narrowed to string literal type of `'getObject'`

[Link to playground example](https://www.typescriptlang.org/play/index.html#src=const%20params%3A%20any%20%3D%20%7B%0D%0A%20%20%20%20s3Operation%3A%20'putObject'%2C%0D%0A%7D%3B%0D%0A%0D%0Aconst%20%7B%0D%0A%20%20%20%20s3Operation%20%3D%20'getObject'%0D%0A%7D%20%3D%20params%3B%0D%0A%0D%0A%0D%0Aif%20(s3Operation%20%3D%3D%3D%20'putObject')%20%7B%0D%0A%20%20%20%20console.log('why%20not%3F')%3B%0D%0A%7D%0D%0A)

**Comment by jwbay** [comment]
Can't reproduce this in 2.7 (found something similar)
