### ISSUE TITLE
Declaration merging when using rootDirs?

### ISSUE THREAD

**Issue by pleerock** [Microsoft/TypeScript#14738]
I have tsconfig in `src/postgres` with rootDirs set:

```json
{
        "rootDirs": [
            "../core",
            "../common-rdbms",
            "."
        ]
}
```

Now, `common-rdbms` has `column/ColumnOptions.ts` with `ColumnOptions` interface inside.
What I want is to have `postgres/column/ColumnOptions.ts` with `ColumnOptions` interface inside with another properties. What I expect is when I use `ColumnOptions` inside "postgres" project, it will have properties from both `ColumnOptions` from `common-rdbms` and `postgres` package.

**Comment by vladima** [comment]
can you please make a small repro project to demonstrate the problem to make sure that root cause of the issue is addressed?

**Comment by pleerock** [comment]
[here you are](https://github.com/pleerock/typescript-root-dir-declaration-merging-issue). See error in `./src/postgres/index.ts`
