### ISSUE TITLE
typescript npm link

### ISSUE THREAD

**Issue by patrikx3** [Microsoft/TypeScript#14732]
It is an ```npm link``` module.
Since it is a symlink, it should work by default with JS no problem.
But with TS, it is not working. 
Either it doesn't find because I removed the ```node_modules``` from the linked project.
Or if I keep in the linked lib I get the ```Duplicate identifier```

How can I fix it? I have multiple lib's and it is hard to always have to ```npm publish```, so I use ```npm link``` which with JS it works, with TypeScript it doesn't.

**Comment by mhegazy** [comment]
Can you provide a sample project, or a clear set of repro steps for us to reproduce the issue locally?

**Comment by patrikx3** [comment]
Never mind! I fixed it like this.
The problems when I use linked project but with that settings it works right now.
```typescript
{
  "compilerOptions": {
    "baseUrl": "./",
    "paths": {
      "*": [ "node_modules/@types/*", "*"]
    }
  }
}
```
