### ISSUE TITLE
Add support WebGL v2

### ISSUE THREAD

**Issue by MaxGraey** [microsoft/TypeScript#14733]
Hi guys,
I know most of DOM declaration for TypeScript generated automatically using Edge and TSJS-lib-generator. Edge's browser still doesn't support WebGL2, so I'm implement WebGL2 binding manually =) So I'm not in a hurry to make a pull request and require assistance for quality testing.

#### Production plan
- add unit tests
- battle testing
- PR for DefinitelyTyped
- PR for TypeScript

[TypeScript WebGL 2 Repositary](https://github.com/MaxGraey/WebGL2-TypeScript)

**Comment by dannyfritz** [comment]
Thanks for this!

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by nkemnitz** [comment]
WebGL2 is on DefinitelyTyped, if that helps: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/webgl2

**Comment by clark-stevenson** [comment]
If anyone comes past this way, does anyone know how to include this definitely typed in Angular?

I detailed this question on[ StackOverflow ](https://stackoverflow.com/questions/48318276/how-do-i-include-stand-alone-declarations-in-my-angular-project)if preferred

**Comment by MaxGraey** [comment]
> If anyone comes past this way, does anyone know how to include this definitely typed webgl2 in Angular?

Are you try include WebGL2.d. ts to files in tsconfig.json?

```js
{
    "compilerOptions": {
         ...
    },
    "files": [
        "<may-be-some-dir>/WebGL2.d.ts"
    ]
}
```

**Comment by clark-stevenson** [comment]
Hey @MaxGraey 

I think so, but I don't see why as this is already set:

   ```
"typeRoots": [
      "node_modules/@types"
    ],
```

And the webgl2 declaration lives at `node_modules/@types/webgl2/index.d.ts`

If I try files. I get `Unknown compiler option 'files'`

**Comment by MaxGraey** [comment]
@clark-stevenson 
You install via DefinitelyTyped? I'm not contribute this package. But this should work.
In my case I put WebGL.d.ts to separate @types folder and use this config:
```js
"files": [
  "./@types/WebGL2.d.ts"
],
```
Or this:
```js
"typeRoots": [
  "node_modules/@types",
  "./@types"
]
```

**Comment by jacobbogers** [comment]
MAxGraey, thanks 
Is this incorperated in the standard already???, my vscode still not see WebGL2RenderingContext

**Comment by LubosD** [comment]
Yup, in my Angular app, after installing `@types/webgl2`, I had to edit `src/tsconfig.app.json` to add the following:

```
"typeRoots": [ "./types" ]
```

where `types` is a symlink I created like this:

```
ln -s ../node_modules/\@types/ types
```

Putting anything like `../node_modules/@types` directly into the TS config file doesn't work. This is a big WTF. It makes no sense at all.

**Comment by frou** [comment]
AFAIK, TypeScript since v3.6 has had built-in knowledge of WebGL 2.0 (no extra DefinitelyTyped packages needed). So this issue can probably be closed.
