### ISSUE TITLE
Functions with never return type as the only call

### ISSUE THREAD

**Issue by sebdoucet** [Microsoft/TypeScript#14735]
**TypeScript Version:**  2.1.4

**Code**

```ts

function foo(): string {
    throwError();
}

function throwError(): never {
    throw new Error();
}

```

**Expected behavior:**
Compiling perfectly :)

**Actual behavior:**
Expect a return value but we already know that the throwError() function never gonna step after.

**Comment by RyanCavanaugh** [comment]
Discussed at #12825, #8655, #12883, etc
