### ISSUE TITLE
private Modifier compiler method

### ISSUE THREAD

**Issue by ganeshkbhat** [Microsoft/TypeScript#14740]
I was creating a simple implementation of a class one with public and one with private usage in the class.  The class is as follows:

class Tester{
    private a: string = 'Test';
    public b:number = 10;
    constructor(){}
}

The class in .ts does not allow usage of of a private variable but seems like compiled code will in real JS code. The above class gets compiled to the following (is it how it is supposed to be?):
var Tester = (function () {
    function Tester() {
        this.a = 'Test';
        this.b = 10;
    }
    return Tester;
}());

As far as I am aware and as far as I have looked through a lot of stackoverflows and JS documentation and saw that private variables can be implemented in JS.
http://stackoverflow.com/questions/12713659/typescript-private-members

The tsc compiler should yield the following result (logically) for the above class definition:

**TypeScript Version:**  2.2.1 / nightly (2.2.0-dev.201xxxxx)
version 2.1.5

**Code**

```ts
class Tester{
    private a: string = 'Test';
    public b:number = 10;
    constructor(){}
}

**Expected behavior:**
var Tester = (function () {
    function Tester() {
        var a = 'Test';
        this.b = 10;
    }
    return Tester;
}());


**Actual behavior:**
var Tester = (function () {
    function Tester() {
        this.a = 'Test';
        this.b = 10;
    }
    return Tester;
}());

**Comment by RyanCavanaugh** [comment]
https://github.com/Microsoft/TypeScript/wiki/FAQ#you-should-emit-classes-like-this-so-they-have-real-private-members ?
