### ISSUE TITLE
miscellaneous parser bugs

### ISSUE THREAD

**Issue by nowindowsowrking** [Microsoft/TypeScript#14744]
**TypeScript Version:**  2.2.1 / nightly (2.2.0-dev.201xxxxx)

**Code**
({a})
(a) ? (b) : (c)
({a, a: 1, c})
({ get a() { return a }, set a(a) { return a; } })
({a:1, get 'b'(){}, set 3(c){}})

```ts

Tested in the playground.

```

**Expected behavior:**

Should parse

**Actual behavior:**

Throws an error

**Comment by cevek** [comment]
```ts
var a, b, c;
({ a });
(a) ? (b) : (c);
({ a, a: 1, c }); // duplicate identifier "a"
({ get a() { return a }, set a(a) { return a; } }); // incorrect return in setter
({ a: 1, get 'b'() { }, set 3(c) { } }); // getter b return void
```

**Comment by RyanCavanaugh** [comment]
None of these errors are incorrect. Maybe you could be more specific?

**Comment by nowindowsowrking** [comment]
@RyanCavanaugh More specific? According to ECMA standards, this combinations are all valid and should parse. They are not errors. See [TC39](https://github.com/tc39).

**Comment by nowindowsowrking** [comment]
I recommend studying [this](https://github.com/tc39/test262).

**Comment by RyanCavanaugh** [comment]
You're confusing parse errors with type errors.
