### ISSUE TITLE
"new" keyword doesn't parse correctly

### ISSUE THREAD

**Issue by nowindowsowrking** [Microsoft/TypeScript#14741]
**TypeScript Version:**  2.2.1 / nightly (2.2.0-dev.201xxxxx)

**Code**
new a(b,c)
new a(b)
new a(...b = c)
new a(...b, ...c)
```ts

Tested in the playground.

```

**Expected behavior:**

Should parse

**Actual behavior:**

Throws an error

**Comment by cevek** [comment]
You are joking, I hope? :)

No, errors
```ts
var a,b,c
new a(b,c)
new a(b)
new a(...b = c)
new a(...b, ...c)
```
http://www.typescriptlang.org/play/index.html#src=var%20a%2Cb%2Cc%3B%0D%0Anew%20a(b%2C%20c)%0D%0Anew%20a(b)%0D%0Anew%20a(...b%20%3D%20c)%0D%0Anew%20a(...b%2C%20...c)%0D%0A%0D%0A

**Comment by RyanCavanaugh** [comment]
These are all working as intended.

Please be specific in your bug reports; this is not a sufficient level of detail.

**Comment by nowindowsowrking** [comment]
@RyanCavanaugh Good to know this works as intended. Try another one that is actually an early error bug
`break = 1;`

If you try this is the playground, you will see this is an error. But probably works as intended.

See this [TC39 note](https://github.com/tc39/test262/blob/master/test/language/keywords/S7.6.1.1_A1.1.js)

As you see this is actually an error.
