### ISSUE TITLE
JSDoc apparently taking effect in TypeScript code

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#14752]
**TypeScript Version:**  nightly (2.3.0-dev.20170320)

**Code**

```ts
import {} from "fs"; // Make it a module

class X {
    foo: Y;
    /** @typedef {function} Y */
    bar: number;
}

class Y {
    baz: number;
}

const x = new X();
x.foo.baz;
```

**Expected behavior:**

No error.

**Actual behavior:**

`src/a.ts(14,7): error TS2339: Property 'baz' does not exist on type '() => any'.`

**Comment by Kovensky** [comment]
More strangely, it's a `@typedef`, which makes no sense even when used as a salsa jsdoc o_O
