### ISSUE TITLE
Completions on class: put statics first

### ISSUE THREAD

**Issue by andy-ms** [microsoft/TypeScript#14751]
**TypeScript Version:**  nightly (typescript@2.3.0-dev.20170320)

**Code**

```ts
class C {
  static foo() {}
  static bar() {}
}

C.
```

**Expected behavior:**

Completions `foo` and `bar` are first.

**Actual behavior:**

They are hidden among `apply`, `arguments`, `bind`, `call`, `caller`, `length`, `name`, `prototype`, and `toString`.

**Comment by jameshulse** [comment]
I've taken a crack at this for my contribution to TypeScript.

When creating the completion entries in competions.ts `createCompletionEntry` all entries are given a `sortText` of `"0"` which means they end up in the default alphabetical order. My logic is to give the symbols merged from `Function` sortText that will cause them to appear after. The concept that seems to indicate these symbols are from an inherited class are the `mergeId` so I have gone for something similar to the following:

```
let sortText = ";

if(symbol.parent.mergeId) { // undefined on symbols directly from 'C' but numerical for Function symbols
    sortText = `0-${symbol.parent.mergeId}`;
}
```

If this doesn't sound too far off then I would happily follow the standard procedure and create a pull request etc.

**Comment by RyanCavanaugh** [comment]
@jameshulse sounds about right to me

**Comment by andy-ms** [comment]
@jameshulse I think we're not correctly testing `sortText` right now. I'll try to look into that on monday.

**Comment by jameshulse** [comment]
Cheers @andy-ms. A potential risk is whether all clients are happy to handle non numeric `sortText`.

**Comment by RyanCavanaugh** [comment]
I think we should be fine. The name is `sortText` after all, and even the built-in JS `sort` function sorts numbers as if they were strings 😆

**Comment by jameshulse** [comment]
Ha good point @RyanCavanaugh. I've created a pull request to show my suggested fix. I struggled with testing part so I'm sorry if this causes more work for you guys. If you can point me in the right direction I can give it another go (was also running in to mocha errors locally annoyingly)
