### ISSUE TITLE
Path mapping does not support special symbols

### ISSUE THREAD

**Issue by AntJanus** [Microsoft/TypeScript#14756]
**TypeScript Version:**  2.2.1 

**Code**

tsconfig.json:

```json
{
  "compilerOptions": {
     "baseUrl": ".",
     "paths": {
        "<config>": ["app/config"]
     }
  }
}
```

another file in application:

```ts
import envConfig from '<config>/envConfig';
```

**Expected behavior:**
Module resolution finds `envConfig` file in the `app/config` folder relative to root no matter where the file is imported from.

**Actual behavior:**
Get an error `Cannot find module '<config>/envConfig'`. Removing the angle brackets from the config and the import statement causes TypeScript to resolve the path correctly.

Webpack has no issue resolving aliases with special characters/names in the key. There are also Babel plugins that rewrite imports with the alias to a relative path and have no issues with the special characters.

I'm not sure if this is the place to discuss it but I use the special characters to denote importing a module via an alias thus making it more explicit that the path/module is a special one rather than either a `node_module` or a module that's within the same directory.

**Comment by mhegazy** [comment]
did you mean:

```json
{
  "compilerOptions": {
     "baseUrl": ".",
     "paths": {
        "<config>/*": ["app/config/*"]
     }
  }
}
```

**Comment by AntJanus** [comment]
Okay, yeah, that worked. Thanks!

But here's my question, why did it work as:

```
"paths": {
  "config": ["app/config"]
}
```

but not when the key had angle brackets?

**Comment by mhegazy** [comment]
>But why did it work as:

do not know how that would work. use `tsc --traceResolution` to see how the compiler resolve your imports.
