### ISSUE TITLE
ternary operator with an empty object always gives an empty object

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#14758]
```typescript
const data = Math.random() > 0.5 ? { value: 1 } : { }; 
// expected data to be {} | { value: number }, actual data is {}
```

**Comment by gcnew** [comment]
I think its caused by subtype reduction. Unfortunately `{}` is really poisonous.

I've stumbled upon a similar issue, where because of https://github.com/Microsoft/TypeScript/issues/13039#issuecomment-268129526 the reduction is unsafe: https://github.com/Microsoft/TypeScript/issues/12970.

**Comment by jurosh** [comment]
It's really dangerous, also code like this which looks to be properly typed can silently introduce errors to codebase:

```JavaScript
interface IObject {
  foo?: boolean;
}

const condition = true;
const fooBar: IObject = condition ? {
  foo: 'not boolean', // should be boolean only
  notExisting: '132' // should not exist
} : {};
```

It's always taking `{}`, so we can type everything into `fooBar`, no matter strictly defined `IObject` as return type.

**Comment by mhegazy** [comment]
`{}` is a super type of `{value: number}`, and `{} | {value:number}` is the same as `{}` from assignability point of view.

**Comment by aleksey-bykov** [comment]
by the same logic `6 | false` is `{}` too which is a super type

**Comment by mhegazy** [comment]
well, yes, `{}` is the top type.

**Comment by aleksey-bykov** [comment]
i love your sense of humor, dear sir

**Comment by OliverJAsh** [comment]
How come this behaviour only applies to ternary operators, not functions?

``` ts
    // expected error, but got none!
    const x2: { blur?: string } = 'foo' ? { blur: 1 } : {};

    // expected error, got error
    const x3: { blur?: string } = (() => {
        if ('foo') {
            return { blur: 1 };
        } else {
            return {};
        }
    })();
```

**Comment by RyanCavanaugh** [comment]
Tracking this at #19236
