### ISSUE TITLE
Interfaces can't extend typeof types

### ISSUE THREAD

**Issue by dempfi** [Microsoft/TypeScript#14757]
**TypeScript Version:**  2.2.1 / nightly (2.2.0-dev.201xxxxx)

**Code**

```ts
// This doesn't work
const a = {
  b: 'some string'
}
interface X extends typeof a {
  a: number
}

// This does
const a = {
  b: 'some string'
}
type A = typeof a
interface X extends A {
  a: number
}
```

**Expected behavior:**
Treat `typeof` expression as type expression in type definition context.

**Actual behavior:**
Compiler throws an `Expression expected.` error.

**Comment by RyanCavanaugh** [comment]
The grammar for `typeof` is currently simple (dotted identifiers only) but may get substantially more complex in the future (#6606); we don't want this to become a weird ambiguous thing when it's already easy enough to write the type alias. Feel free to comment if this is especially troublesome and we can rework this as a suggestion, though it would likely be very low priority.

**Comment by dempfi** [comment]
@RyanCavanaugh thx for explanation. 👍
