### ISSUE TITLE
Proposal: function return types

### ISSUE THREAD

**Issue by mmkal** [Microsoft/TypeScript#14765]
[Index types](https://www.typescriptlang.org/docs/handbook/advanced-types.html#index-types) are awesome. But it'd be even more awesome if advanced types could go a step further, and allow getting the types that a function returns:

Say you have a function that transforms some data:
```TypeScript
const formatPerson = (person: Person) => ({
    name: person.firstName + person.lastName,
    age: Date.now() - person.birthTime
});
```

There's currently no (good) way to get the type of the return value, even though it's completely determinstic - the compiler knows that it's of type `{ name: string, age: number }`.

It'd be great if we could do something like this:
```TypeScript
const greetPerson = (formatted: formatPerson()) => {
    console.log('hi', formatted.name);
};
```
Or to reuse the type, `type FormattedPerson = typeof formatPerson();`.

Where using the `()` tells the compiler to use the return type of the `formatPerson` function.
Currently the only way something like this is possible is to trick the compiler into giving you this type information, but in a very hacky way that involves creating a real variable at runtime:

```TypeScript
const dummyFormattedPerson = null as {} && formatPerson(null);

const greetPerson = (formatted: typeof dummyFormattedPerson) => {
    console.log('hi', formatted.name);
};
```

Is there any reason this couldn't be done? The compiler has done the hard part of tracking the type information already, so it would only require adding the syntax (which is always invalid right now, so it'd unambiguous and backwards compatible).

This might also be useful for doing things like tracking the types for utility function that [promisify an entire object that uses callbacks](http://bluebirdjs.com/docs/api/promise.promisifyall.html):
```TypeScript
type Promisified<T> = {
    [P in keyof T]: (...args: any[]) => Promise<T[P]()>;
};
```
The above example is pretty far from perfect though - to be complete there would need to be more advanced types, like function parameter types, and constraints for `keyof` to include only functions and not other properties.

Some potential edge-cases/pitfalls:

* Overloaded functions - two different overloads of a function definition could have different return types. e.g. `format(x: string): number` and `format(x: string, y: string): number[]`. The solution for this could be either:
  * Have the return type be a intersection type. e.g. `typeof format()` is `number | number[]`.
  * Allow "passing in" types to the function, as if they were real arguments. e.g. `typeof format(string)` is `number` and `typeof format(string, string)` is `number[]`. Then I guess as a convenience you could have `typeof format()` being `number | number[]` as above.

* Clashing with the "real" `typeof` operator. This should be handled by only looking for this syntax when the compiler is expecting a type annotation, e.g. decorating a variable (`x: format()`) or in a `type` assignment (`type formatted = typeof format()`). I imagine this is exactly how index types work too.

**Comment by RyanCavanaugh** [comment]
See #6606

**Comment by paldepind** [comment]
I just came here to request excactly this.

@RyanCavanaugh The issue you linked is related to this but it also seems to be much broader in scope and the specific proposal is quite different. #6606 seems to be related to the getting the type of a value-level terms. This issue is closer related to #12342.

What this issue asks for is just to get the return value of a function at the type-level. It doesn't even have to include new syntax. Just a generic type called `Return` that gives the return type of a function type would be enough. I.e. it would work like this:

```typescript
type A = Return<(a: string, b: number) => boolean>;
type B = Return<() => number>;
```

In the above `A` would be assigned to `boolean` and `B` to `number`.

Here is a simple use case where a function cannot be given a proper return type without the above `Return`.

```typescript
function applyObject<O extends { [n: string]: () => any }>(object: O): ????? {
  const newObject: any = {};
  for (const key of Object.keys(object)) {
    newObject[key] = object[key]();
  }
  return newObject;
}
```

If something like `Return` existed the above function could be given a proper return type like this:

```ts
type ApplyObject<O extends Record<string, Pair>> = {
  [K in keyof O]: Return<O[K]>
}

function applyObject<O extends { [p: string]: () => any }>(object: O): ApplyObject<O> {
  const newObject: any = {};
  for (const key of Object.keys(object)) {
    newObject[key] = object[key](); // <- Note difference here
  }
  return newObject;
}
```

To see how this relates to index types consider how the above function actually could be given a proper return type if it had indexed an array instead of applying a function.

```typescript
type Pair = [any, any];
type Second<P extends Pair> = P[1];

type SecondObject<O extends Record<string, Pair>> = {
  [K in keyof O]: Second<O[K]>
}

function secondObject<O extends { [p: string]: Pair }>(object: O): SecondObject<O> {
  const newObject: any = {};
  for (const key of Object.keys(object)) {
    newObject[key] = object[key][1];
  }
  return newObject;
}
```

**Comment by mmkal** [comment]
@RyanCavanaugh great! Glad to see it might be in the pipeline.
