### ISSUE TITLE
Search symlinks dependency relative to symlink location

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/TypeScript#14760]
Currently TSC for symlinked packages resolves their dependencies relative to their file system real location, it would be very useful to have an option to make TSC resolve dependencies relative to current symlink locations.

Such behavior ins implemented in node using [`--preserve-symlinks` options](https://nodejs.org/api/cli.html#cli_preserve_symlinks):
> The --preserve-symlinks command line flag instructs Node.js to use the symlink path for modules as opposed to the real path, allowing symbolically linked peer dependencies to be found.

other module loaders [for example webpack](https://webpack.js.org/configuration/resolve/#resolve-symlinks):
> Whether to resolve symlinks to their symlinked location.

I think it should be easy to add. Without this for workflows that involve linked packages can often be a real problem requiring much effort to make things work.

There was a PR on symlinks lately https://github.com/Microsoft/TypeScript/pull/12020 I'm not sure if it relates to described issue @andy-ms

**Comment by calebmer** [comment]
It looks like that PR does not fix this issue.

**Comment by whitecolor** [comment]
Yeah it doesn't fix. But the problem persists. 

cc @andy-ms
