### ISSUE TITLE
Constraints of functions passed as argument are not checked

### ISSUE THREAD

**Issue by gcnew** [Microsoft/TypeScript#14766]
**TypeScript Version:**  nightly

**Code**

```ts
declare function p(x: 'hello'): 'hello';
declare function g<T extends string>(x: T): T;

declare function h(f: (x: number) => number): number;
declare function f<T extends number>(f: (x: T) => T): T;

h(p); // Error as expected
h(g); // Uncaught error
f(g); // Uncaught error
```

**Expected behavior:**
All of the above invokations should be errors.

**Comment by aleksey-bykov** [comment]
might be related: https://github.com/Microsoft/TypeScript/issues/13039#issuecomment-268129526

**Comment by gcnew** [comment]
@aleksey-bykov Thanks. Yes, it is a duplicate of https://github.com/Microsoft/TypeScript/issues/3410. I'll still leave it open to see if the attitude towards this problem has changed.

**Comment by aleksey-bykov** [comment]
i am with you let the duplicates rain!

**Comment by gcnew** [comment]
Another issue that is a probable incarnation of the same cause: https://github.com/Microsoft/TypeScript/issues/12970

**Comment by gcnew** [comment]
I changed my mind, closing 😄
