### ISSUE TITLE
Completion at bad position

### ISSUE THREAD

**Issue by jrieken** [Microsoft/TypeScript#14767]
**TypeScript Version:**  2.2.2-insiders.20170317
**Code**

```ts
class Foo {
    append() {
    }
    private c<cursor>
}

```

**Expected behavior:**
* remove `<cursor>` and place your cursor there
* trigger completions
* :bug: global symbols like `clearInterval` are suggested, I'd expect no suggestions

fyi @mjbvz

**Comment by mhegazy** [comment]
should be fixed in latest.
