### ISSUE TITLE
empty object should be an identity type relative to the intersection operation

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#14762]
```typescript
type T = {} & { value: 1 } // expected to be { value: 1 }, actual { value: 1 } & {}
```

**Comment by RyanCavanaugh** [comment]
What's the observable effect of this? Other than the string representation looking weirdish

**Comment by aleksey-bykov** [comment]
none

**Comment by RyanCavanaugh** [comment]
Seems like we should just special case it out of `&` in `typeToString`

**Comment by aleksey-bykov** [comment]
just checked the latest nightly version, still see it:
![image](https://cloud.githubusercontent.com/assets/937933/24169627/9787b210-0e54-11e7-972b-d4b3f8ad15a4.png)

**Comment by RyanCavanaugh** [comment]
We can remove this during `createIntersectionType` as long as at least one of the other constituents is objectlike (thus there would be no effects of having it in the intersection). Types like `string & { }` are still distinct from `string` so will need to keep `{ }` in the intersection
