### ISSUE TITLE
Transpile problem: constructor property of extended class has enumerable:true, apparent with for-in loops

### ISSUE THREAD

**Issue by briancodes** [microsoft/TypeScript#14769]
**TypeScript Version:**  2.2.1 

**Code**

```ts
class DataService {
    constructor(public name: string) { }
}
class UpdateService extends DataService {    
    constructor(name: string) { super(name); }
}
let updateService = new UpdateService("service"); 
for (var k in updateService) {
    console.log(k); // constructor of updateService should not be enumerable
}
```
Transpiled JavaScript (__extends function)
```js
var __extends = (this && this.__extends) || (function () {
    var extendStatics = Object.setPrototypeOf ||
        ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
        function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
```

**Expected behavior:**

- console.log() output: 
- name

**Actual behavior:**
console.log() output: 

- name
- constructor (this should not be output)

**Note on fix/workaround**
The `constructor` `enumerable` property is not being set to false by default in `__extends` function. Setting this via an `Object.defineProperty()` works ok. Not 100% about compatibility if support for ES3 is required
```js
//function __() { this.constructor = d; }
function __() {
     Object.defineProperty(this, 'constructor', {
          value: d,
           enumerable: false,
           configurable: true,
           writable: true
      });
}    
```
Think the extendStatics is created in 
https://github.com/Microsoft/TypeScript/blob/master/src/compiler/transformers/es2015.ts
 - const extendsHelper

**Comment by briancodes** [comment]
I was thinking about this issue recently. If ES5 classes using `B.prototype = Object.create(A.prototype)` result in prototype methods (including constructor) being enumerable, then maybe it should be the expected behavior for TypeScript targeting ES5

**Comment by RyanCavanaugh** [comment]
Downleveling this low is pretty rare these days, and caring about enumerability of `constructor` is even rarer. This can be written off as an observable spec deviation due to downleveling.
