### ISSUE TITLE
Replace 'tsc --help' output message's example for using response files

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#14775]
Right now if you write `tsc --help`, you'll get

```
Version 2.x.x-dev.123456
Syntax:   tsc [options] [file ...]

Examples: tsc hello.ts
          tsc --outFile file.js file.ts
          tsc @args.txt
```

Notice that last part: **`tsc @args.txt`**.

Response files are not something we've thought about in forever. `tsconfig.json` has been the standard way to use TypeScript for quite a bit now. The example given is confusing at this point.

I think we should either remove it entirely or use **`tsc --project tsconfig.json`**

**Comment by misoguy** [comment]
I'd like to help out on this issue if no one is on it yet.
