### ISSUE TITLE
Generic parameters not fully type-checked (e.g., Promise)

### ISSUE THREAD

**Issue by stephencelis** [Microsoft/TypeScript#14770]
**TypeScript Version:**  2.2.1

**Code**

```ts
const a: Promise<{ foo: 'bar' }> = Promise.resolve({ foo: 'typo' });
const b: Promise<{ foo: 'bar' }> = Promise.resolve({});
```

**Expected behavior:**

- `a` should type-check: it constrains `foo` to `'bar'` but is given `'typo'`.
- `b` should type-check: it requires `foo` but is given an object without `foo`.

**Actual behavior:**

Neither type-check.

The same types check fine when resolved directly:

```ts
// Type '{ foo: "typo"; }' is not assignable to type '{ foo: "bar"; }'.
//   Types of property 'foo' are incompatible.
//     Type '"typo"' is not assignable to type '"bar"'.
const a: { foo: 'bar' } = { foo: 'typo' });

// Type '{}' is not assignable to type '{ foo: "bar"; }'.
//   Property 'foo' is missing in type '{}'.
const b: { foo: 'bar' } = {};
```

Generic parameter type checks fail for objects/types of different shapes:

```ts
// Type 'Promise<{ foo: string; bar: string; }>' is not assignable to type 'Promise<{ foo: "bar"; }>'.
//   Type '{ foo: string; bar: string; }' is not assignable to type '{ foo: "bar"; }'.
//     Types of property 'foo' are incompatible.
//       Type 'string' is not assignable to type '"bar"'.
const a: Promise<{ foo: 'bar' }> = Promise.resolve({ foo: 'bar', bar: 'baz' });

// Type 'Promise<number>' is not assignable to type 'Promise<{ foo: "bar"; }>'.
//   Type 'number' is not assignable to type '{ foo: "bar"; }'.
const b: Promise<{ foo: 'bar' }> = Promise.resolve(1);
```

**Comment by ikokostya** [comment]
Related to https://github.com/Microsoft/TypeScript/issues/10717. See comment https://github.com/Microsoft/TypeScript/issues/10717#issuecomment-246726793

**Comment by ikokostya** [comment]
JFI it works in `flow`, because type parameter in promise [declared](https://github.com/facebook/flow/blob/cabc14e1fb31d3d51a04bf12629b13969af9c714/lib/core.js#L627) as [covariant](https://flowtype.org/docs/classes.html#polymorphism-and-type-parameter-variance).
