### ISSUE TITLE
Template string syntax highlighting (release-1.4)

### ISSUE THREAD

**Issue by derekcicerone-zz** [microsoft/TypeScript#1477]
I'm playing with the new support for template strings in release-1.4 and seeing potential issues with syntax highlighting.

In a single-line template string it looks like the string is classified as a keyword.

In a multi-line template string like this:

```
var template = `/hello/
/world/`;
```

It looks like the "/hello/" is classified as a keyword and the "/world/" as a regexp.

Sorry if this is just not implemented yet. I looked for an issue first but didn't see one.

**Comment by DanielRosenwasser** [comment]
@derekcicerone, you may be interested in my comment on https://github.com/Microsoft/TypeScript/issues/1698#issuecomment-70594428.

In short, you can get very basic support if you cherry pick off e42ce9c3199c9449ac04e0ce09815d7f1e69db88.

**Comment by derekcicerone** [comment]
Ah cool, thanks for the tip!

**Comment by DanielRosenwasser** [comment]
A fix is now in `master`.

**Comment by derekcicerone** [comment]
Awesome, thanks for the fix! I will check this out shortly.

Related question: what is the proper design for using the 3 classifiers? It seems like the lexical classifier can be used synchronously but I'm guessing the semantic/syntactic classifiers need to be used asynchronously. I can add those to some existing async logic for showing occurrences, finding errors as the user is typing etc. I was wondering though, do I call both the syntactic and semantic classifiers? Only one? I'm not really clear on when each is supposed to be used. Any advice would be greatly appreciated!

**Comment by derekcicerone** [comment]
This looks great! Much better! Thanks!

**Comment by DanielRosenwasser** [comment]
@basarat might also be interested in this for https://github.com/TypeStrong/atom-typescript/issues/71.

You can use the lexical classifier synchronously, and to ensure speed, you probably should, but it ultimately depends on your use case and platform - it's a matter of fine-tuning.

Ideally, you'll have the other two classifiers running concurrently as well (or you can let them take over entirely at some point). As long as you prioritize the classifications of tokens in a certain way such that some can be appropriately overwritten by others, the ordering won't matter in practice. Syntactic classifications should always overwrite lexical classifications, and semantic classifications will overwrite some syntactic classifications (but only for identifiers).

The semantic classifier can be run on the same thread as any other semantically-aware feature (e.g. completions lists), and the syntactic classifier *can* also be run on the same thread as any syntactically aware feature - though you may want to play around with this; syntactic classifications should also be as fast as possible, so we actually run it on a separate thread.

Glad to hear it's working well for you so far - let me know if you have any other suggestions!

**Comment by derekcicerone** [comment]
Cool, thanks for the explanation!
