### ISSUE TITLE
Visual Studio 2015 cannot find module @angular/core when using tsconfig.json

### ISSUE THREAD

**Issue by gchurchley** [Microsoft/TypeScript#14776]
**Visual Studio Enterprise 2015**
**TypeScript Version:**  2.0.6
**Visual Studio Version:** 14.0.25431.01 Update 3

**Issue**
Create a new web TypeScript project (I don't think it matters what the project type is; I've also tried this with MVC projects).
Add a simple Angular2 component, build and test.  Everything works perfectly.
Now add a tsconfig.json file and compile TypeScript using gulp instead of utilizing MSBuild.
Again, it builds and runs perfectly, however, the editor shows red squiggly lines in many places. The first place the squiggly lines appear is under the "@angular/core" import statement. The error is 'Cannot find module "@angular/core".  
Note that the same code, tsconfig.json, package.json, and gulfile, work perfectly when using VSCode.

**Expected behavior:**
No editor errors when using tsconfig.json

**Actual behavior:**
Editor errors when using tsconfig.json

**Comment by billti** [comment]
Not sure why they would behavior different. Can you point to a sample repo to clone/look at what might be up here (the devil is in the details - so the description is a little vague to ensure we get an exact repro). Thanks.
