### ISSUE TITLE
auto-complete broken when a generic is used as both function parameter and argument

### ISSUE THREAD

**Issue by tomsdev** [Microsoft/TypeScript#14772]
**TypeScript Version:**  2.2.1 / nightly (2.2.0-dev.201xxxxx)

**Code**

Copy paste the code below in [TypeScript Playground](http://www.typescriptlang.org/play/).

```ts
// a function that takes one typed object argument
function doSomething(props: { a: number, b?: string }) {
    // code
}

// a function that takes a function and calls it with the given props
function call<P>(fn: (props: P) => any, props: P): void {
    // code
}

// type { or {} and ctrl-space and you see nothing
// type {a or {a} and you see a: any
// type {a:1, } and ctrl-space and you see b: string
// type {a:1, b} and ctrl-space and you see nothing
call(doSomething, { a: 1 });

// I managed to get a different behavior if I use
// keyof on the generic type
export type Same<T> = {
    [P in keyof T]: T[P];
};

// Same as call() but wraps P with Same<>
function callSame<P>(fn: (props: P) => any, props: Same<P>): void {
    // code
}

// type { or {} and ctrl-space and you see nothing
// type {a or {a} and you see a: number
// type {a:1, } and ctrl-space and you see b: string
// type {a:1, b} and ctrl-space and you see b: string
callSame(doSomething, { a: 1 });


// I managed to get a different behavior if I use
// T extends P for the second parameter
function callExtends<P, T extends P>(fn: (props: P) => any, props: T): void {
    // code
}
// type { or {} and ctrl-space and you see nothing
// type {a or {a} and you see a: any
// type {a:1, } and ctrl-space and you see nothing
// type {a:1, b} and ctrl-space and you see b: any
callExtends(doSomething, { a: 1 });
```

**Expected behavior:**
Auto-complete (ctrl-space) should display the properties 'a: number' and 'b: string'.

**Actual behavior:**
It's very inconsistent but overall doesn't work. I even managed to get some different behavior if I use keyof on the generic type or use generic extends.

**Comment by mhegazy** [comment]
The issue here is that the argument is in an inference position. the compiler uses the type of the object literal to infer the generic type argument type; this happens to be the same type the language service uses to provide completions, so you basically get completions for the same type you are just writing, which is nothing.
There is not really a simple way to know if this is a place where you want to infer from, or just one to check against the type from the other argument.

**Comment by tomsdev** [comment]
I agree with your comment @mhegazy for the first 2 examples, however in the 3rd example I made it explicit that the first argument is the source of truth and the second argument needs to be type-checked against it (using T extends P):
`function callExtends<P, T extends P>(fn: (props: P) => any, props: T): void {`

**Comment by mhegazy** [comment]
again, `T` is an inference target. and constraints are only used to check inferences once they occurred, and they are not inference positions themselves. so if you write `callExtends(fn, {})` `T` is inferred as `{}`.

**Comment by goodmind** [comment]
Why this is closed?

**Comment by kitsonk** [comment]
Because as the issue is tagged and as explained, it is a design limitation as it is difficult to infer type information in the locations exampled and therefore impossible to auto-completion intellisense.
