### ISSUE TITLE
ElementTagNameMap should extend HTMLElementTagNameMap

### ISSUE THREAD

**Issue by justinfagnani** [Microsoft/TypeScript#14784]
**TypeScript Version:**  2.2.1

**Code**

Along with #14782, this would let custom element definitions be able to augment only one tag name map:

```ts
export class FooElement extends HTMLElement {}
customElements.define('foo', FooElement);

declare global {
  interface HTMLElementTagNameMap {
    "foo": FooElement,
  }
}
```

And with #14783 `ElementTagNameMap` could extend both `HTMLElementTagNameMap` and the proposed `SVGElementTagNameMap`.

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by justinfagnani** [comment]
Looks like this was fixed in https://github.com/Microsoft/TSJS-lib-generator/commit/072c5487550dda70fe82d063680b3e7d7f478090
