### ISSUE TITLE
Add SVGElementTagNameMap

### ISSUE THREAD

**Issue by justinfagnani** [Microsoft/TypeScript#14783]
**TypeScript Version:**  2.2.1

APIs that use ElementTagNameMap or HTMLElementTagNameMap could benefit the same from a SVGElementTagNameMap.

**Comment by mhegazy** [comment]
`HTMLElementTagNameMap` is only used for `createElement`, and as far as i understand `createElement` does not generate `SVGElement`s, so what APIs did you have in mind?

**Comment by falsandtru** [comment]
I want this too. When we make some SVGElement builder, need to define its type as

```ts
createElement<K extends keyof SVGElementTagNameMap>(tagName: K): SVGElementTagNameMap[K];
```

to avoid the built-in method that requires specifying namespace URI.

```ts
createElementNS(namespaceURI: "http://www.w3.org/2000/svg", qualifiedName: "a"): SVGAElement;
```

But `SVGElementTagNameMap` doesn't exist. Can you accept this PR?

**Comment by falsandtru** [comment]
e.g.

```ts
type TypedHTML = {
  //readonly [K in keyof HTMLElementTagNameMap]: ElBuilder<K, HTMLElementTagNameMap[K]>;
  readonly [K in keyof ElementTagNameMap]: ElBuilder<K, ElementTagNameMap[K]>;
};
export const TypedHTML: TypedHTML = new Proxy({} as TypedHTML, {
  get: (obj, tag) =>
    obj[tag]
      ? obj[tag]
      : obj[tag] = builder(NS.HTML, `${tag}`),
});

/*
type TypedSVG = {
  readonly [K in keyof SVGElementTagNameMap]: ElBuilder<K, SVGElementTagNameMap[K]>;
};
export const TypedSVG: TypedSVG = new Proxy({} as TypedSVG, {
  get: (obj, tag) =>
    obj[tag]
      ? obj[tag]
      : obj[tag] = builder(NS.SVG, `${tag}`),
});
*/
```

https://github.com/falsandtru/typed-dom/blob/master/src/dom/html.ts

**Comment by falsandtru** [comment]
I made a PR https://github.com/Microsoft/TSJS-lib-generator/pull/324

**Comment by falsandtru** [comment]
@RyanCavanaugh @mhegazy Can you take a look?
