### ISSUE TITLE
global.d.ts not working

### ISSUE THREAD

**Issue by aight8** [Microsoft/TypeScript#14788]
**Typescript version > 2**

I using vscode, but the global.d.ts in the src folder (or tried it everywhere), is not included only if I reference to it with the <reference> statement.

```TS
{
    "compilerOptions": {
        "allowJs": true,
        "allowSyntheticDefaultImports": true,
        "strictNullChecks": true,
        "preserveConstEnums": true,
        "experimentalDecorators": true,
        "moduleResolution": "node",
        "target": "es2016",
        "module": "es2015",
        "jsx": "preserve",
        "skipLibCheck": true,
        "lib": [
            "dom",
            "es2015",
            "es2016"
        ],
        "typeRoots": [
            "types"
        ],
        "baseUrl": "./src",
        "pretty": true
    }
}
```

**Comment by mhegazy** [comment]
what do you mean by "no included"? if you run `tsc --p <tsconfig> --listFiles` do you see it or not?

**Comment by saostad** [comment]
[Better Solution ](https://stackoverflow.com/questions/42233987/how-to-configure-custom-global-interfaces-d-ts-files-for-typescript?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa)
