### ISSUE TITLE
ElementListTagNameMap should be a mapped type derived from ElementTagNameMap

### ISSUE THREAD

**Issue by justinfagnani** [Microsoft/TypeScript#14782]
**TypeScript Version:**  2.2.1

**Code**

Right now there's some extra boilerplate when defining custom elements and augmenting dom.d.ts's tag name maps that could go away if mapped types were used more:

```ts
export class FooElement extends HTMLElement {}
customElements.define('foo', FooElement);

declare global {
  interface ElementTagNameMap {
    "foo": FooElement,
  }
  interface HTMLElementTagNameMap {
    "foo": FooElement,
  }
  interface ElementListTagNameMap {
    "foo": NodeListOf<FooElement>;
  }
}
```

It would be nice to only have to augment one interface, like so:

```ts
declare global {
  interface HTMLElementTagNameMap {
    "foo": FooElement,
  }
}
```

We could get closer if `ElementListTagNameMap` was defined like this:

```ts
type ElementListTagNameMap = {
  [P in keyof ElementTagNameMap]: NodeListOf<ElementTagNameMap[P]>;
}
```

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by justinfagnani** [comment]
Looks like it was fixed in https://github.com/Microsoft/TSJS-lib-generator/commit/14029e6214124d6712ddd5ddf9f4486add14d8d6
