### ISSUE TITLE
CustomEvent should be parameterized by detail type.

### ISSUE THREAD

**Issue by justinfagnani** [Microsoft/TypeScript#14785]
**TypeScript Version:**  2.2.1

**Code**

If `CustomEvent` were parameterized, code that fires events could declare what the type of `detail` is so that listeners could be more type safe:

```ts
interface MyDetail {
  foo: string;
}

declare global {
  interface DocumentEventMap {
    'my-event': CustomEvent<MyDetail>;
  }
}

document.addEventListener('my-event', (e) => {
  e.detail.foo; // ok
  e.detail.bar; // warning
});
```

**Comment by mhegazy** [comment]
now that we have default type parameters, we could add a type parameter without breaking existing users.

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by arjunyel** [comment]
Hey need some guidance, do these changes look right? I feel like they aren't because I don't see another example with a similar signature in the rest of definitions https://github.com/arjunyel/TSJS-lib-generator/commit/49dd4a5539de4a51547a3969dadc97598bbfb98d

**Comment by justinfagnani** [comment]
Looks right to me at least.

**Comment by RonPenton** [comment]
Should 

```
detailArg: any
```

be 
```
detailArg: T
```

instead?

**Comment by justinfagnani** [comment]
@RonPenton yes, good catch
