### ISSUE TITLE
Introduce option to tell tsc prefere *.d.ts over *.ts

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/TypeScript#14787]
This was discussed in the issue [Using a library that has both ts and d.ts files in the same folder causes issues](https://github.com/Microsoft/TypeScript/issues/10704)

This actual for dev process when you develop a lib that builds `js/d.ts` files near corresponding `.ts` sources and one want to uses this modules while development of other project (usually as linked modules). Currenlty TS compiler perferes `*.ts` extension over `*.d.ts` compiled definintions, in the issue above it was discussed that for some devs it is convinient workflow, because it allows to have most recent code attached to the project. But it also may create some problems, depending on how library is attached and used, it may require in you current project to have additional type dependencies (that are required while lib development, but not its usage), also **it requires the same version and otpions of typescript** used for both attached library module and project itself.

So it will be still default, but I would introduce some option that allowed to make compiler prefer `d.ts` over `*.ts`, something like `prefereDefinitions`.

**Comment by kitsonk** [comment]
Or people could just use TypeScript correctly.  Anyone who is publishing a library with `.ts` co-located with `.d.ts` files of the same name should be informed that are mis-using TypeScript and informed of the correct way.

**Comment by whitecolor** [comment]
@kitsonk Yes, but I'm not talking about published third party libraries (though the issue mentioned was about it) I'm telling about internal dev process of some lib while development. Which was too discussed in that issue mentioned above, and actually previous behavior was that TS preferred `.d.ts` over `.ts`, but then it was changed if I get it correct. But I say that there is cases that this approach brings problems to dev workflow when linked (internal) library's code is messing with projects TS code.

**Comment by kitsonk** [comment]
> I'm telling about internal dev process of some lib while development

Then people are developing wrong, internally.

**Comment by whitecolor** [comment]
@kitsonk 
Why? How they should develop correctly? Not to use linked modules with code that is in progress?

**Comment by kitsonk** [comment]
Emit your definitions and code to a different path, e.g. `build`.  Co-locating your emitted code with your source code is a recipe for disaster.

**Comment by whitecolor** [comment]
@kitsonk 
1) It is not always convenient and possible currenlty, if you have a monorepo with different packages, but the same ts settings it is convenient to build them using one TSC process, but TS compiler still can not handle multiple tsconfigs with for example different settings of `outDir`, files, etc, you will have to have multiple builds started, it maybe a little bit of overhead.

2) If you emit built file in different location, you definitely have no problems with messing of `d.ts/ts` but it also make senseless any justifications about the preference of `*.ts` over `*.d.ts ([such justification that was actually mentioned in the above issue](https://github.com/Microsoft/TypeScript/issues/10704#issuecomment-274558365)) ` because *they never go tougher* as you propose.

What I'm proposing is quite a small change, allowing to design/experiment with more flexible workflows.

**Comment by kitsonk** [comment]
> but it also make senseless any justifications about the preference of *.ts over *.d.ts because they never go tougher as you propose

It isn't a "preference" as much as a logical order of resolution.  TypeScript correctly assumes that the `.ts` is the module.  The `.d.ts` with the same name in the same path is the definition of that module when it is transpiled.  Therefore TypeScript can totally ignore it because the `.ts` would be authoritative (or in other words, never attempts to find a `.d.ts` because it has "original" source).

If you are naming a definition file the same name as an untranspiled `.ts` file in the same path, you are doing it wrong.  If it is an UMD definition file for some other library, it should be located in a different path.  If it is ambient/global declarations for your project, it should not be named the same as a TypeScript module.  You should name it something like `interfaces.d.ts` or something.  Making it match a module name is wrong.

Changing this will break stuff in all sorts of ugly ways.  Why continue to insist to do things wrong?

**Comment by whitecolor** [comment]
> If you are naming a definition file the same name as an untranspiled .ts 

I'm not naming and I don't create any manual `.d.ts`, I just use **default** option of TS compiler to compile JS (and definition) along with original TS source. And TS source will be removed from published version. But while development TS files are still in place and there is tsc process that watches sources and produces JS for running tests. And also I want to link this library to other project and try to use it here while still begin in realtime development. It is a common process of working with linked modules that are in development. 

And I think there is no "wrong" or "right" way, if TS allows producing `.d.ts` near corresponding `.ts` source it also assumes there should be no corresponding `*.ts` to allow usage of this `.d.ts`. I just want to make compiler behave with such modules that are in active development as if they where published in production (without original TS source).

I'm not trying to just push my "wrong" version of the workflow, I see its issues, and I also see the issues and limitations of other workflows (when for example you place compiled files in the other path). If there is something really bad/wrong/flaw about it I still didn't hear yet the reason.

cc @mhegazy

**Comment by mhegazy** [comment]
Since this is a desing-time only issues, have you considered adding `"paths"` mapping rules to your tsconfig.json?

**Comment by whitecolor** [comment]
@mhegazy can you suggest what a proper `"path"` mappings should be for this case?

**Comment by mhegazy** [comment]
Assuming you have `Client` and `Library` projects that you are working on them concurrently, and will publish to separate npm packages. in `Client`'s tsconfig.json i would add:

```ts
{
    "compilerOptions": {
        "baseUrl" : "./",
        "paths": {
              "Library\*" : [ "node_modules\library\*.ts"]
         }
    }
}
```
