### ISSUE TITLE
MSBuild error lib.es2017.sharedmemory.d.ts and lib.es2017.string.d.ts not found 

### ISSUE THREAD

**Issue by rgozim** [Microsoft/TypeScript#14793]
**TypeScript Version:**  2.2.2 - MSBuild (Nuget package)

Inside `lib.es2017.d.ts` the following references cannot be found (and are not present in the Typescript Nuget Package folder)

```ts
/// <reference path="lib.es2017.sharedmemory.d.ts" />
/// <reference path="lib.es2017.string.d.ts" />
````
**Expected behavior:**

**Actual behavior:**

**Comment by mhegazy** [comment]
Also missing now is `lib.esnext.d.ts` and `lib.esnext.asynciterable.d.ts`.

**Comment by yuit** [comment]
Fixed in the vso repo. WE have missed lots more @mhegazy  you can see the change in our VS repo :)

**Comment by mhegazy** [comment]
Should be in the [nightly nuget package](https://www.myget.org/gallery/typescript-preview) tomorrow.
