### ISSUE TITLE
AppData Roam Issue

### ISSUE THREAD

**Issue by weezykon** [Microsoft/TypeScript#14791]
**TypeScript Version:**  2.2.1 / nightly (2.2.0-dev.201xxxxx)

**Code**

I tried to install typescript using command prompt locally but it kept giving me this AppData roaming error, pls how do i solve this. Thanks.
![capture](https://cloud.githubusercontent.com/assets/586490/24189589/e5d441fe-0ee5-11e7-8490-ca044ef4dc58.JPG)

**Expected behavior:**

**Actual behavior:**

**Comment by mhegazy** [comment]
That is not an error. this is just npm telling you what it installed and where.

it is in AppData\Roaming\npm cause you using `-g` in your `npm install -g typescript`, meaning you wanted to install it globally.

Please see npm docs: https://docs.npmjs.com/cli/install for more info.

**Comment by weezykon** [comment]
so whats the best way to install typescript, in my own case, please?

**Comment by mhegazy** [comment]
Typings is a separate tool. It seems you are looking at an old sample though I would recommend using the official angular2 quick start sample in https://angular.io/docs/ts/latest/quickstart.html
