### ISSUE TITLE
typescript class diagram editor

### ISSUE THREAD

**Issue by technicalmedia** [microsoft/TypeScript#1479]
It would be useful to have a class diagram tool for typescript classes where i could drag multiple classes and create a visual overview of the methods and properties for each.  

It would also be useful if the editor would show dependency arrows between the classes when a class is a constructor parameter of another class

Note: TypeScript is awesome, elegant, and amazing :)

**Comment by Laggie** [comment]
++1

**Comment by RobMoloney** [comment]
+++1

**Comment by Infer-On** [comment]
+1

**Comment by brphelps** [comment]
+1

**Comment by A-Russell** [comment]
+1

**Comment by mjohnsonengr** [comment]
Big +1.  Even if it is read-only.  Often times it is a hassle to look through inheritance to find public fields in a class.  IntelliSense helps with this but a class diagram would be so much better!

**Comment by javierquevedo** [comment]
+1

**Comment by waynejuckts** [comment]
+1

**Comment by eyalvardi** [comment]
++1

**Comment by koroandr** [comment]
+1

**Comment by Elephant-Vessel** [comment]
+1

**Comment by selganor74** [comment]
+1 +1 +1 !!!

**Comment by fuksi** [comment]
+1

**Comment by aafische** [comment]
+1

**Comment by FunkeyFlo** [comment]
+1, microsoft, pliss!

**Comment by basarat** [comment]
I'm working on a class diagram view (ref  : https://github.com/alm-tools/alm/pull/85 / https://github.com/alm-tools/alm/issues/84 )

![image](https://cloud.githubusercontent.com/assets/874898/15415069/5fcf09fc-1e83-11e6-8c33-f6e30cb90992.png)

**Comment by basarat** [comment]
released with `0.0.51` http://npmjs.com/package/alm :rose:

![live](https://cloud.githubusercontent.com/assets/874898/15416181/d6b9ea84-1e8b-11e6-99eb-e151dcb2e288.gif)

**Comment by jkanchelov** [comment]
+1

**Comment by AlGantori** [comment]
@basarat what would be useful is to be able to do UML class diagram .  and it would read all .ts files, I need to see the big picture rather than just what is a single file.   On another topic, how would you compare React and Ionic2 (they adopted typescript) which made it attractive but I still struggle with injection, providers, etc... I don't have a good grasp of what pattern to follow, so I thought I would hunt for a class diagramming tool.  I come from .NET so I am at least half brain damaged :)

**Comment by basarat** [comment]
> how would you compare React and Ionic2

@AlGantori I cannot comment personally on Ionic2 as I haven't used it. But people who use it love it :heart:

I can also tell you that plenty of [TypeScript developers love React](https://medium.com/@basarat/typescript-developers-love-react-9871b494bc1a) :rose:

Use what makes you happy 🎉 🤗

**Comment by trusktr** [comment]
@basarat It would be amazing  if the class diagram would show the UML diagram across files, start at the selected file, and make a diagram based on all classes encountered in the dependencies of that file.

**Comment by tomdavidson** [comment]
Specifically I would like to see PlantUML <-> TS

**Comment by leocaseiro** [comment]
This is a nice tool to play https://tsuml-demo.firebaseapp.com/

Via https://github.com/fsahmad/typescript-uml

**Comment by trusktr** [comment]
@leocaseiro Oh, that's nice!! And it works in the web, so it'd be very easy to put this inside Atom for example. Thanks for sharing this!

**Comment by ratikanta-sdrc** [comment]
I managed with https://github.com/joaompneves/tsviz

**Comment by lixaotec** [comment]
+1

**Comment by fenixsolorzano** [comment]
+1

**Comment by ZibanPirate** [comment]
this one has no dependencies and comes with cool features:
https://github.com/demike/TsUML2

[interactive example](https://raw.githubusercontent.com/demike/TsUML2/master/assets/uml_diagram.svg)

**Comment by RyanCavanaugh** [comment]
I think it's safe to say we're not going to do this given the cost to build and maintain it, vs the availability of other tools which fulfill the same role.
