### ISSUE TITLE
Adds DataTransfer.setDragImage to dom.d.ts

### ISSUE THREAD

**Issue by loganmzz** [Microsoft/TypeScript#14795]
**TypeScript Version:**  2.1.6

DataTransfer type is missing the method setDragImage. See https://html.spec.whatwg.org/multipage/interaction.html#dom-datatransfer-setdragimage

The expected declaration is:

```ts
interface DataTransfer {
    setDragImage(element:Element, x:number, y:number): void;
}
```

**Comment by mhegazy** [comment]
We need the whole DataTransder APIs: https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by loganmzz** [comment]
Ok, I will prepare that ;)

**Comment by loganmzz** [comment]
For later reference, I drop a link to last spec : https://www.w3.org/TR/2016/REC-html51-20161101/editing.html#the-datatransfer-interface

**Comment by loganmzz** [comment]
@mhegazy Are there any support for TSJS-lib-generator ? I have updated inputFiles/overridingTypes.json and then run build.sh but generated/dom.generated.d.ts isn't changed :(

**Comment by mhegazy** [comment]
can you share your change

**Comment by mhegazy** [comment]
This is a new method, the change should be done in `addedTypes.json`:

```json
   {
        "kind": "method",
        "interface": "DataTransfer",
        "name": "setDragImage",
        "flavor": "DOM",
        "signatures": ["setDragImage(image: Element, x: number, y: number): void"]
    }
```

`overridingTypes.json` apply only to declarations that already exist.

**Comment by loganmzz** [comment]
Ok I thought addedTypes.json was for new types, not new declarations ^^ I will submit PR tomorrow morning (CET)
