### ISSUE TITLE
Type inference resulting in incorrect type for function result

### ISSUE THREAD

**Issue by magnushiie** [Microsoft/TypeScript#14798]
**TypeScript Version:**  2.2.1

**Code**

```ts
function functionReturningVoid() {
}
function functionReturningNumber() {
  return 0;
}
function returnValueFrom<R, F extends (() => R)>(f: F) {
  return f();
}
const rVoid = returnValueFrom(functionReturningVoid); // Argument of type '() => void' is not assignable to parameter of type '() => {}'.
const rNumber: number = returnValueFrom(functionReturningNumber); // Type '{}' is not assignable to type 'number'.
```

**Expected behavior:**
Compiles successfully.

**Actual behavior:**
Compiles with the above errors noted in comments.

**Comment by magnushiie** [comment]
Note: it's valid to assign the value of a void-returning function, e.g. the following compiles:
```ts
const v = functionReturningVoid();
```

**Comment by magnushiie** [comment]
This might be related to #5884 and #5254 (for which #5884 was closed in favor of) but as all the types are specified at each line, it seems it's not a problem that call site inference is not taking place, but rather that R is widened unneccesarily?

**Comment by akaRem** [comment]
@magnushiie 
Have you tried this?
(I've checked this snippet on http://www.typescriptlang.org/play/)
```ts
function functionReturningVoid()  {
}
function functionReturningNumber() {
  return 0;
}
function returnValueFrom<R>(f: () => R): R {
  return f();
}
const rVoid = returnValueFrom(functionReturningVoid); // ok
const rNumber : number = returnValueFrom(functionReturningNumber); // ok
```
Or are you trying to illustrate some more generic problem?

**Comment by magnushiie** [comment]
Ah, yes, this solves it. I thought I had a more generic instance where this would not be a solution, but I can't find it anymore.

**Comment by RyanCavanaugh** [comment]
Constraints don't produce an inference site, so there's nothing to infer `R` from.
