### ISSUE TITLE
How to get sourceFile with parentNode set?

### ISSUE THREAD

**Issue by octref** [Microsoft/TypeScript#14808]
**TypeScript Version:**  2.2.1

I'm looking at the Compiler API and trying to figure out a way to parse a object literal like so:

```js
export default {
  name: 'foo',
  props: ['bar', 'baz'],
  methods: {
    a () { return 1; },
    b () { return 2; }
  }
}

// Want to get object like this:
const info = {
  name: 'foo',
  props: ['bar', 'baz'],
  methods: ['a', 'b']
}
```

When I try to do it this way:

```ts
let program = ts.createProgram(['test.ts'], {
  target: ts.ScriptTarget.ES5, module: ts.ModuleKind.CommonJS
});
const sourceFile = program.getSourceFile('test.ts');
const exportDefaultObject = find(sourceFile.statements, st => st.kind === ts.SyntaxKind.ExportAssignment &&
  (st as ts.ExportAssignment).expression.kind === ts.SyntaxKind.ObjectLiteralExpression);
ts.forEachChild((exportDefaultObject as ts.ExportAssignment).expression, (literal: ts.ObjectLiteralExpression) => {
  const children = literal.getChildren();
  ...
}
```

`literal.getChildren()` or `literal.getText()` throws exception:
```
TypeError: Cannot read property 'text' of undefined
```

However, if I'm creating the sourceFile this way:

```ts
const sourceFile = ts.createSourceFile('test.ts', fs.readFileSync('test.ts').toString(), ts.ScriptTarget.ES5, true);
```

The same code works fine.

However, with `setParentNodes` as false, it throws same exception `Cannot read property 'text'`.

**Full Code**: https://github.com/octref/vueinfo/blob/master/index.ts#L13-L25

So my two questions are:

1. What's the difference between these two ways of creating `sourceFile`, and why am I getting `Cannot read property 'text'` in one of them?
2. Is there anyway I can use `program.getSourceFile` with `setParentNodes`, so I can access the AST behind it?

**Comment by ajafff** [comment]
Call `program.getTypeChecker()`. This set's the parent property on all nodes. The result can be ignored.

**Comment by octref** [comment]
@ajafff It worked! Wondering why the lack of parent property would cause property `text` not set, though.

**Comment by ajafff** [comment]
`node.getText()` internally does *something like* `node.getSouceFile().text.substring(start, end)`

`getSourceFile()` walks up the parent chain until it finds `ts.SourceFile` or `undefined`

you could avoid that by passing the sourceFile to `getText`, `getChildren`, `getStart`, etc ... basically every function or method that has an optional `sourceFile` parameter (which you should do anyways to avoid unnecessary cpu work)
```ts
node.getText(sourceFile); // works even if parent is not set
```

**Comment by octref** [comment]
Oh I see -- but TypeChecker seems pretty useful too.
Thanks for the detailed explanation. I guess I'll always pass the sourceFile as a rule of thumb.
