### ISSUE TITLE
[bug] moduleResolution:node not with index files

### ISSUE THREAD

**Issue by trusktr** [Microsoft/TypeScript#14803]
**TypeScript Version:**  2.2.1 / nightly (2.2.0-dev.201xxxxx)

2.2.1

**Code**

This doesn't work:

```ts
import { UpdateTrackAmplitudeAction } from "app/actions"
```

but this works:

```ts
import { UpdateTrackAmplitudeAction } from "app/actions/index"
```

**Expected behavior:**

importing `index` directly should not be required.

**Actual behavior:**

Node.js looks for index files when importing a directory. TypeScript doesn't seem to do this.

Also, `app` is configured in paths (not sure if that affects anything):

```json
"paths": {
    "app/*":    ["./src/*"],
}
```

**Comment by mhegazy** [comment]
Do you have `"moduleResolution": "node"` in your tsconfig.json?

**Comment by trusktr** [comment]
It was a while back, but based on the title, I believe I was using `"moduleResolution":"node"`. Feel free to close, and I can re-open when I get back on a TS project and if I have the problem again.
