### ISSUE TITLE
Mapped types on optional property results in any when intersected

### ISSUE THREAD

**Issue by paldepind** [microsoft/TypeScript#14800]
**TypeScript Version:**  2.2.1 and 2.3.0-dev.20170322

**Code**

```ts
type StringObj<A> = {[K in keyof A]: string};
type Optional = {foo?: {[s: string]: string[]}};
type StringFoo<A extends Optional> = StringObj<A["foo"]> & {foo: string};
type Test = StringFoo<{}>;
```

**Expected behavior:**

In the code above `Test` would be equal to `{foo: string}`

**Actual behavior:**

In the code above `Test` is equal to `any`.

**Additional remarks:**

Note that if I change the code above like this:

```diff
  type StringObj<A> = {[K in keyof A]: string};
  type Optional = {foo?: {[s: string]: string[]}};
- type StringFoo<A extends Optional> = StringObj<A["foo"]> & {foo: string};
+ type StringFoo<A extends Optional> = StringObj<A["foo"]>;
  type Test = StringFoo<{}>;
```

Then `Test` has the type `{}` as I would expect. This implies that `StringObj<A["foo"]>` results in `{}` when `A = {}`. So it seems very inconsistent that it turns into `any` when used with `& {}`.

In my actual use case I now use a fix like this:

```ts
type StringObj<A> = {[K in keyof A]: string};
type Optional = {foo?: {[s: string]: string[]}};
type StringFoo<A extends Optional> = StringObj<(A & {foo: {}}>["foo"]> & {foo: string};
type Test = StringFoo<{}>;
```

Which makes `Test` be of type `{foo: string}` as I want. But that is less than ideal.

**Comment by RyanCavanaugh** [comment]
This works better now
