### ISSUE TITLE
signatureHelp Always Uses Declaring Function's JSDoc Info

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#14804]
From https://github.com/Microsoft/vscode/issues/22679

**TypeScript Version:**  2.2.1

**Code**

```ts
/**
 * Description of a
 *
 * @param {*} x Base param x
 */
function a(x) { }


/**
 * Description of C
 *
 * @param {string} x Specific param x
 */
var b = a;

b(|)
```

Trigger signatureHelp at `|` in `b(|)` 

**Expected behavior:**
The documentation for `b` is returned.

**Actual behavior:**
The documentation for `a` is returned.

This seems related to the discussion in https://github.com/Microsoft/TypeScript/issues/3520

**Comment by mhegazy** [comment]
`b`'s type has changed as a result of the assignment. it is now `a`'s type.
