### ISSUE TITLE
Not again: A class must be declared after its base class.

### ISSUE THREAD

**Issue by pankleks** [Microsoft/TypeScript#14806]
Hello,

I just upgraded 2.1.5 to 2.2.2 and get lots of this errors (was all fine on 2.1.5).
For your information I'm not using modules - generating all into single JS file.

**Comment by benjamingr** [comment]
Can you share an isolated snippet of code that causes this issue and broke between 2.1.5 and 2.2.2?

**Comment by pankleks** [comment]
Hello,

It will be hard as solution has over 300 files. I think this functionality had some issues from the very beginning. I was never able to figure it out.
Since beginning I had situations where it worked, and situations where I had to manually add `/// <reference ...` 
With different releases of TS I could remove some references or add some - meaning this was not stable.
But with `2.2.2` release I have over 100 errors like that.

In `tsconfig` I'm using `outFile` and not listing all `ts` files explicitly but using `include` with `*.ts`.
Can you explain how it works in case `outFile` is used?
I'm quite sure if I would put all of my classes in single file it would work - so I don't know why TSC is not able to figure out proper over of including files.

I don't know if many people uses `outFile` instead of modules, but I still think this is very desired option especially for web dev.

Let me know how I can help ...

**Comment by mhegazy** [comment]
@pankleks can you share a repro, we would love to investigate more and fix the underlying issue.

**Comment by pankleks** [comment]
@mhegazy it's not code I can share publicly - only on priv.

**Comment by mhegazy** [comment]
can you reproduce the issue on a sample project, if you distill it down to two/three files that are showing the symptoms, we would only be interested in class heritage clauses, and triple-slash references not the rest of the file.

**Comment by pankleks** [comment]
[Planck.zip](https://github.com/Microsoft/TypeScript/files/877037/Planck.zip)

Hello,

Please find solution strip from most of the code.
Some of the errors disappeared but there are still some. Hope it will be enough to investigate.

Compiles OK with 2.1.5, fails with 2.2.2

**Comment by RyanCavanaugh** [comment]
I can't repro this with 2.2.2

**Comment by RyanCavanaugh** [comment]
What file ordering mechanism does this project use? I don't see any reference directives or explicit file list - it's likely TS is just picking up these files in the order they appear on disk, which isn't even stable machine-to-machine

**Comment by pankleks** [comment]
hmm, this is what I have:
![image](https://cloud.githubusercontent.com/assets/14176066/24429080/db379ca2-1410-11e7-9d20-c47f1c09558e.png)

I'm not using npm - using official installer release from MS.

**Comment by pankleks** [comment]
@RyanCavanaugh just use:
```json
    "incluide": [
        
        "Planck.Core/*.ts",
        "Planck.UI/*.ts"
    ]
```

**Comment by RyanCavanaugh** [comment]
What's the output of `tsc --listFiles` ?

**Comment by pankleks** [comment]
@RyanCavanaugh 
That's exactly my point - why should I use `reference`? They are all compiled to single file, TS should be able to figure out dependencies.

If I put all classes in single TS file it's compiling fine.

And at last, why it's working in 2.1.5 and not in 2.2.2?

**Comment by pankleks** [comment]
[listFiles.txt](https://github.com/Microsoft/TypeScript/files/877180/listFiles.txt)

**Comment by RyanCavanaugh** [comment]
It's always been the case that tsc does not figure out an ordering of your input files (see #1359 and similar threads). I can't figure out how this code *ever* ran without error -- certainly any class defined in a file alphabetically before `Component` should have failed.

Can you confirm that `tsc --listFiles` in 2.1.5 produces a different order?

**Comment by pankleks** [comment]
[listFiles.215.txt](https://github.com/Microsoft/TypeScript/files/877235/listFiles.215.txt)

Looks like 2.1.5 order is following one specified in include.

**Comment by pankleks** [comment]
so here are my thoughts:
1) `tsc` (both 2.1.5 and 2.2.2) are able to find proper order if all classes are in single TS file. I really don't understand why (in case modules are not used and output is generated to single file) `tsc` could not load all the files and then compile
2) I think `tsc` should respect `include` order - IMO very logical expectation
3) In the end - it looks there is some instability in `tsc` anyway - as order of files (for same solution) is different between 2.1.5 and 2.2.2

Using `/// <reference` is really nightmare when you have large solutions (my has over 300 files).
If you think point 1 is too specific/hard to implement, I believe point 2 should be very simple and gives you means to solve such errors without referencing.

**Comment by pankleks** [comment]
Hello, any update on this?

I really think solution 2 is the way to go here, and it should be easy to implement.
In the end - it looks today that `include` order is not deterministic anyway.

**Comment by RyanCavanaugh** [comment]
Bug. While the order from any given `include` directive's globbing is not deterministic, each *set* of `include` results should appear in the same order as the directives

**Comment by pankleks** [comment]
Awesome - thank you so much!

**Comment by pankleks** [comment]
Hello, any update when this might be implemented? If you point me to code maybe I can try to help.

**Comment by andy-ms** [comment]
!
The `tsconfig.json` uses `"incluide"` instead of `"include"`, so the default include is used instead, which gives you undefined ordering.

**Comment by pankleks** [comment]
Guys, I used "include" and have same result.

**Comment by andy-ms** [comment]
It's working for me on the `Planck.zip` sample you uploaded (testing with `typescript@2.2.2`); when I change "incluide" to "include", the output of `--listFiles` matches the order of the "include" array.
