### ISSUE TITLE
Overload resolution fails to use type arguments from base type in 'super' constructor calls

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#1480]
http://www.typescriptlang.org/Playground#src=class%20A%3Cx%2C%20y%3E%20%7B%0D%0A%09constructor(private%20map%3A%20(value%3A%20x)%20%3D%3E%20y)%20%7B%0D%0A%09%09%0D%0A%09%7D%0D%0A%7D%0D%0A%0D%0Aclass%20B%20extends%20A%3Cnumber%2C%20string%3E%20%7B%0D%0A%09%0D%0A%09constructor()%20%7B%20super(value%20%3D%3E%20String(value))%3B%20%7D%0D%0A%7D

![image](https://cloud.githubusercontent.com/assets/937933/5428417/f29dd590-8390-11e4-9287-bbdff5c742a9.png)

**Comment by DanielRosenwasser** [comment]
Should be fixed in `master`.
