### ISSUE TITLE
Type Guards do not narrow `this` parameters with union types.

### ISSUE THREAD

**Issue by louisditzel** [microsoft/TypeScript#14817]
**TypeScript Version:**  2.2.1

**Code**

```ts
interface A {
    a: number;
}

interface B {
    b: number;
}

function isA(arg: any): arg is A {
    return arg.a !== undefined;
}

function test(arg: A | B) {
    if (isA(arg)) {
        console.log(arg.a);
    } else {
        console.log(arg.b);
    }
}

function testThis(this: A | B) {
    if (isA(this)) {
        console.log(this.a);
    } else {
        console.log(this.b);
    }
}

```

**Expected behavior:**
`arg` is of type `A` or `B` in the function `test`, after passing the type guard. 
`this` is of type `A` or `B` in the function `testThis`, after passing the type guard. 

**Actual behavior:**
`arg` is the correct type.
`this` remains of type `A | B`, so typescript reports an error on both calls to `this.a` and `this.b`.

This can be seen in the playground [here](http://www.typescriptlang.org/play/index.html#src=interface%20A%20%7B%0D%0A%20%20%20%20a%3A%20null%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20B%20%7B%0D%0A%20%20%20%20b%3A%20number%3B%0D%0A%7D%0D%0A%0D%0Afunction%20isA(arg%3A%20any)%3A%20arg%20is%20A%20%7B%0D%0A%20%20%20%20return%20arg.a%20!%3D%3D%20undefined%3B%0D%0A%7D%0D%0A%0D%0Afunction%20test(arg%3A%20A%20%7C%20B)%20%7B%0D%0A%20%20%20%20if%20(isA(arg))%20%7B%0D%0A%20%20%20%20%20%20%20%20console.log(arg.a)%3B%0D%0A%20%20%20%20%7D%20else%20%7B%0D%0A%20%20%20%20%20%20%20%20console.log(arg.b)%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Afunction%20testThis(this%3A%20A%20%7C%20B)%20%7B%0D%0A%20%20%20%20%20%20%20%20if%20(isA(this))%20%7B%0D%0A%20%20%20%20%20%20%20%20console.log(this.a)%3B%0D%0A%20%20%20%20%7D%20else%20%7B%0D%0A%20%20%20%20%20%20%20%20console.log(this.b)%3B%0D%0A%20%20%20%20%7D%0D%0A%7D).

**Comment by jakebailey** [comment]
Yeah, this was fixed by #21490 (so is the same as the later #21248).
