### ISSUE TITLE
Property 'get' does not exist on type 'FormData'.

### ISSUE THREAD

**Issue by ravirajhalli** [Microsoft/TypeScript#14813]
Expected behavior:**
[(https://developer.mozilla.org/en-US/docs/Web/API/FormData/get)](https://developer.mozilla.org/en-US/docs/Web/API/FormData)
The above method tells about methods which can be used on formData.
**Actual behavior:**
Throws error 

> Property 'get' does not exist on type 'FormData'.)

**Comment by mhegazy** [comment]
We are missing almost all methods for `FormData`, e.g. `delete`, `has`, `getAll`, etc..

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by mhegazy** [comment]
`entries`, `values` and `keys`, are special, and should be added to https://github.com/Microsoft/TypeScript/blob/master/src/lib/dom.iterable.d.ts. PRs are appreciated, feel free to ping me if you want to send a PR and have any questions.

**Comment by NColey** [comment]
Hi @mhegazy. I prepared a PR that should fix this issue here: https://github.com/Microsoft/TypeScript/pull/14859. Feel free to let me know if there is anything in it I should update or change.

**Comment by Ra1da35ma** [comment]
Property 'set' does not exist on type 'FormData'

any resolution?
