### ISSUE TITLE
Resolve types for a package `@foo/bar` at `@types/foo__bar`

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#14819]
We currently have no way of providing third-party types for scoped packages.
This should presumably work the same for any type root.

**Comment by mhegazy** [comment]
@andy-ms we need to document this in Definitely Typed readme as well.

**Comment by joscha** [comment]
references https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16970

**Comment by joscha** [comment]
@andy-ms I am not sure this change works as expected, or there might be something else wrong - could you please have a glance at the discussion in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17399#discussion_r123605812 ?
