### ISSUE TITLE
TypeScript doesn't accept reserved keyword `export` in namespace paths

### ISSUE THREAD

**Issue by mprobst** [Microsoft/TypeScript#14815]
**TypeScript Version:**  2.2.1 / nightly (2.2.0-dev.201xxxxx)

**Code**

```ts
namespace foo.export {
    export let bar = 1;
}
```

[According to MDN](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Lexical_grammar#Reserved_keywords_as_of_ECMAScript_2015), `export` should only be a reserved keyword, it should be legal in `Identifier` positions (as opposed to `IdentifierName`), which is what I'd expect in a namespace path.

**Expected behavior:**

Successful parse.

**Actual behavior:**

Reports `Identifier expected.` for the exports keyword. [See playground](http://www.typescriptlang.org/play/#src=namespace%20foo.export%20%7B%0A%20%20%20%20export%20let%20bar%20%3D%201%3B%0A%7D%0A)

**Comment by mhegazy** [comment]
Seems like the same issue as https://github.com/Microsoft/TypeScript/issues/7840

**Comment by DanielRosenwasser** [comment]
As mentioned offline, if you only need to declare the namespace, you can write

```ts
namespace foo {
  namespace bar {
    // ...
  }
  export { bar as export }
}
```
