### ISSUE TITLE
Completions don't work for strings contextually typed by keyof type parameter

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#14812]
```ts
declare function get<K extends keyof T, T>(obj: T, x: K): T[K];

get({a:10, b:20}, '')
```

Request string literal completions in the second parameter.

**Expected:** `a`, `b`
**Actual** No completions.

**Comment by mhegazy** [comment]
seems like the same issue as https://github.com/Microsoft/TypeScript/issues/14772. we infer to `K`, then we have no candidates for completions.
