### ISSUE TITLE
Can an optional and required field of merged interfaces yield a required field?

### ISSUE THREAD

**Issue by psnider** [Microsoft/TypeScript#1481]
I have this case from using the mongoose library, in which my domain object, A, might have a DB _id, but the mongoose.Document always has an _id.
I use type A when not in the mongoose portions of the app, and type ADocument only within those parts that deal directly with mongoose.  Note that mongoose defines Document to contain _id like this:

```
interface Document {
	_id: string;
}
```

I tried to model the A - ADocument relationship like this:

```
interface A {
	_id?: string;
}
interface ADoc extends A, mongoose.Document {	
}
```
but I get this error:
_Interface 'ADoc' cannot simultaneously extend types 'A' and 'Document':
 Named properties '_id' of types 'A' and 'Document' are not identical._

I can get around this error by making _id be either optional in both definitions, or required in both.

I expect that the compiler can infer that _id is now required in ADoc. 
Is the current behavior of issuing an error the correct behavior? 
If so, does it make sense to merge such fields so they become required?

**Comment by danquirk** [comment]
@Igorbek You've now overridden the declarations from the inherited members. The compiler then checks that with the overridden declaration ADoc is a subtype of A and a subtype of Document.

**Comment by mhegazy** [comment]
looks like no further information required. closing.

**Comment by shrishailya** [comment]
Thanks @DanielRosenwasser
