### ISSUE TITLE
Intellisense does not recover from missing .d.ts reference files until solution is reopened.

### ISSUE THREAD

**Issue by cjwainwright** [Microsoft/TypeScript#14818]
**TypeScript Version:**  2.1.5
**Visual Studio Version:** Enterprise 2017 (15.0.0-RTW+26228.4)

**Code**

I have created a simple repository to reproduce this issue, code available at [https://github.com/cjwainwright/vs2017-ts-intellisense-bug](https://github.com/cjwainwright/vs2017-ts-intellisense-bug)

In summary the solution has two separate typescript projects, one referencing the others output .d.ts file via `///<reference />` elements.

Initially the intellisense is broken as the .d.ts files have not been built, which is fine. However once built I would expect intellisense to pick up the new file, it does not.

This did not used to be a problem in vs2015 with TypeScript 1.8.

**Expected behavior:**

Intellisense correctly finds the .d.ts file in the reference once it has been created, without the need to reopen the solution.

**Actual behavior:**

Even after building the solution and creating the .d.ts file that is referenced, intellisense complains that it cannot find the file, and errors are shown in the error list. Reopening the solution temporarily fixes the problem, until e.g. the next clean or rebuild which removes the .d.ts file - requiring the solution be reopened again!

**Comment by cjwainwright** [comment]
A little bit of further information on this:

VisualStudio 2017 with projects set as either TypeScript 1.8 or 2.1 is affected.

VisualStudio 2015 with projects set as TypeScript 1.8 is not affected.

Running the clean target on a project using TypeScript 1.8 does not delete the d.ts files (or any of the output files), which makes this issue less noticeable with 1.8 as the old d.ts files are still there for the reference to use. The improved behaviour to delete these files on clean in 2.1 makes this issue appear more often.

In VisualStudio 2015 there is clearly a point when interacting with a file when it rescans the references and updates accordingly. This does not seem to be happening in VisualStudio 2017.

**Comment by cjwainwright** [comment]
Note, to reproduce this it is important that you open file2.ts whilst the proj1.d.ts file is not present to initially get the error. Only once you have the error build the project to create proj1.d.ts and note that the intellisense error remains until the solution is reopened.

**Comment by amcasey** [comment]
The TS server now tracks missing files (https://github.com/Microsoft/TypeScript/commit/ac72803bb2b299e6b331329a9781cb73cc55c156) and a future release of VS will consume the newly available information.
