### ISSUE TITLE
[MSBuild] Compiler log in MSbuild "TypeScriptCompilerOutput.txt" FilePath is longer than 260 so it cannot be writted

### ISSUE THREAD

**Issue by yuit** [Microsoft/TypeScript#14821]
Our users who use TypeScript Compiler in MSbuild report of receiving a warning:

>  Exception: 'The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.' 

We will want to fix in our target file. As this seems to be a known issue in MSBuild (https://github.com/Microsoft/msbuild/issues/53) that won't get fixed anytime soon.

One possible solution is to patch the local target file. 
Though it doesn't affect local development. This issue block users to be able to create PR as it will pull down its own NuGet which won't allow one to patch the target file

@paulvanbrenk  @billti @minestarks  @mhegazy

**Comment by mhegazy** [comment]
Seems related to https://github.com/Microsoft/TypeScript/issues/13564.

> One possible solution is to patch the local target file.

what do you mean by this

**Comment by yuit** [comment]
look like the same issue as #13564.....you can set that value manually in your local target file.

**Comment by yuit** [comment]
Fix is in the VS repo
