### ISSUE TITLE
Need a flag to check if checking an expression for null or undefined has not that types

### ISSUE THREAD

**Issue by cevek** [Microsoft/TypeScript#14839]
Often we have to check variables for empty values.
If variables has `undefined` or `null` types we check for that types.
But if we want to refactor our code, and replace nullable variables to always with value, we init its with empty values like `false, 0, -1, ""`
But checks that variables for null or undefined in other parts of program are still there, and make a lot of bugs
```ts
let a: string | undefined;
if (a !== undefined) {
   foo(a);
}

// and if we refactor

let a = '';
// In this check we potentially has a bug, cause undefined is not possible here, 
if (a !== undefined) {
   foo(a);
}
```

**Comment by andy-ms** [comment]
https://palantir.github.io/tslint/rules/strict-type-predicates/ attempts this. It could use #13502 to work even better, but should be capable of handling undefined checks already.

**Comment by cevek** [comment]
Another issue linked with this one

```ts
// no error
if (typeof v === null) {} 
if (typeof v === undefined) {} 
```
`typeof v ` is always string, and check with raw `null` or `undefined` is incorrect

**Comment by RyanCavanaugh** [comment]
Covered by #14764?

**Comment by cevek** [comment]
@RyanCavanaugh yeah, it's the same what I want
