### ISSUE TITLE
How could I solve duplicated identifiers in global libraries?

### ISSUE THREAD

**Issue by holi-java** [Microsoft/TypeScript#14831]
let's say I have a project use both `jest` & `jasmine` for test purpose.when I install them the tsc compiler report duplicate identifiers.I try to find issues to solve my problem,but never success.for examples:
-  in spec directory I want to use jasmine

```ts
///<reference types="jasmine"/>
describe("jasmine tests",...);
```

-  in test directory I want to use jest

```ts
///<reference types="jest"/>
describe("jest tests",...);
```

**Comment by andy-ms** [comment]
You could use separate tsconfigs for spec/test.
