### ISSUE TITLE
Projects with "useSingleInferredProject"=false are disconnected from Configured Project randomly

### ISSUE THREAD

**Issue by anstarovoyt** [Microsoft/TypeScript#14838]
1. Create two files "foo.ts" and "bar.ts"
**foo.ts**
`export class Bar {}`
**bar.ts**
`import {Bar} from "./foo"`

2. Create the tsconfig:
`{ "exclude": [ "bar.ts"] }`
3. Start tsserver with the option **useSingleInferredProject**=false
4. Open "bar.ts" file. The file will be connected to "Configured Project" with the tsconfig.json
5. Open "foo.ts" file. The file will be connected to "Inferred Project". The file "bar.ts" will be connect to the "Inferred Project" also (it is ok) but _the file "bar.ts" will be disconnected from the "Configured Project" and it is very unexpected behaviour_.

I found the cause:
Here: [Link to code](https://github.com/Microsoft/TypeScript/blob/master/src/server/editorServices.ts#L618)
definitely must be `isRootFileInInferredProject(f)` instead of `isRootFileInInferredProject(info)`

**Comment by zhengbli** [comment]
@anstarovoyt thanks for the find! I just found the cause as well and searched the issues then found your post :)
