### ISSUE TITLE
Small typo in the sample codes in TypeScript main page.

### ISSUE THREAD

**Issue by pkkj** [microsoft/TypeScript#1483]
In the "Starts from JavaScript, Ends with JavaScript" session, there is an example code. 
![typescript](https://cloud.githubusercontent.com/assets/7818153/5429895/5ac56a62-83b3-11e4-82a7-7d3db9b32cca.jpg)

It seems that the IDE already detects the errors: getDst() is invalid. But someone just ignored it and copied such codes to the page....
If we are not demonstrating the "error detection feature" of our IDE, I suggest that we should fix it.
Thanks.

**Comment by danquirk** [comment]
More than a few people have been confused by this over time, it's possible we need to make the purpose of the example clearer.

**Comment by basarat** [comment]
> More than a few people have been confused by this over time, it's possible we need to make the purpose of the example clearer.

"TypeScript points out code errors at compile time so your JavaScript code runs reliably at runtime"
