### ISSUE TITLE
WeakSet<T> should be WeakSet<T extends object>

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#14840]
**TypeScript Version:**  nightly (2.3.0-dev.20170324)

**Code**

```ts
const s = new WeakSet<string>();
s.add("foo");
```

**Expected behavior:**

An error, since this will fail at runtime.

**Actual behavior:**

No error.

**Comment by falsandtru** [comment]
I done it, but @mhegazy reverted that fix in #15278. His reverting doesn't comply with the spec of ecma. We should comply with the spec.

@mhegazy says `object` constraints of WeakSet causes errors in @types/lodash, but WeakMap is not. Why? lodash has correct constraints for WeakMap like https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/lodash/index.d.ts#L12898. **So WeakMap already have `object` constraints. WeakSet also should be so.**

**Comment by mhegazy** [comment]
We reverted the change to avoid breaking `@types/lodash`. we should reply it, but first we need either 1. remove these definitions from `@types/lodash` alltogahter, or 2. relax the rule on the compiler side that all declarations have the same constraint.


The definition in lodash is at the end of the file, not visible on github view:

```ts
// Backward compatibility with --target es5
declare global {
    interface Set<T> { }
    interface Map<K, V> { }
    interface WeakSet<T> { }  // this breaks if lib.es6.d.ts has WeakSet<T extends object>
    interface WeakMap<K extends object, V> { }
}
```

**Comment by falsandtru** [comment]
Now that problem seems to have go away.

**Comment by mhegazy** [comment]
so what happened to lodash use of this API?

**Comment by falsandtru** [comment]
A last fix is https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21502 and https://github.com/Microsoft/TypeScript/pull/19756. We need to accept some breaking changes, or never fix this bug.

**Comment by mhegazy** [comment]
As i mentioned [earlier](https://github.com/Microsoft/TypeScript/issues/14840#issuecomment-297476088), we need to first:

> relax the rule on the compiler side that all declarations have the same constraint.

**Comment by falsandtru** [comment]
Is there a proposal issue of that?

**Comment by mhegazy** [comment]
nope.

**Comment by falsandtru** [comment]
Can you make it to resolve this issue?

**Comment by mhegazy** [comment]
feel free to file a new issue for it.

**Comment by falsandtru** [comment]
Why you don't do that?

**Comment by mhegazy** [comment]
here you go https://github.com/Microsoft/TypeScript/issues/20018

**Comment by falsandtru** [comment]
Thanks.
