### ISSUE TITLE
Union type case incorrectly eliminated

### ISSUE THREAD

**Issue by WuTheFWasThat** [Microsoft/TypeScript#14843]
**TypeScript Version:**  2.2.1

**Code**

```ts
function toy_example() {
  let found: null | [number, number] = null;
  [1, 2, 3].forEach((num) => {
    if (num % 2 === 0) {
      found = [num, num / 2];
    }
  });
  if (found != null) {
    const result = found[0];
    const halved = found[1];
    console.log(result, halved);
  }
}

toy_example();
```

**Expected behavior:**

No compilation error

**Actual behavior:**

Element implicitly has an 'any' type because type 'never' has no index signature.

**Comment by RyanCavanaugh** [comment]
See #11498

Possible workarounds (only need to do one of these):
 * Use `for / of` instead
 * `let found: null | [number, number] = <any>null;`
