### ISSUE TITLE
Declaring class after consumption code in the same TS file will encounter TypeError.

### ISSUE THREAD

**Issue by daiyip** [Microsoft/TypeScript#14847]
**TypeScript Version:**  2.2.1 / nightly (2.2.0-dev.201xxxxx)

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
let _object = new ObjectA();

class ObjectA {
  doNothing(): void {
  }
}

```
**Expected behavior:**
This code can run without error.

**Actual behavior:**
TypeError: ObjectA is not a function

*Generated code*:
```js
var _object = new ObjectA();
var ObjectA = (function () {
    function ObjectA() {
    }
    ObjectA.prototype.doSomething = function () {
    };
    return ObjectA;
}());
```
new ObjectA() is called before ObjectA is assigned with the constructor function.

**Comment by RyanCavanaugh** [comment]
Duplicate #5207
