### ISSUE TITLE
Intersections allow assignment of incompatible types

### ISSUE THREAD

**Issue by PyroVortex** [Microsoft/TypeScript#14855]
**TypeScript Version:**  2.1.6

**Code**

```ts
// A *self-contained* demonstration of the problem follows...

let x: string & { a: string };
let y: string & { a?: number } = x; // 1
```

**Expected behavior:**
Compiler error at (1), because types of property 'a' are incompatible. 'string' is not assignable to type 'number | undefined'
**Actual behavior:**
Compiles fine, no error.

Edit: fixed assignability ordering.

**Comment by mhegazy** [comment]
I am seeing the error in latest.
