### ISSUE TITLE
Unexpected result of instanceof related to different capitalization imports

### ISSUE THREAD

**Issue by qmuntal** [Microsoft/TypeScript#14851]
**TypeScript Version:**  2.2.1
**OS: Windows 10**

**Code**

File: ./foo.ts

``export class Foo {}``

File: ./foo-factory.ts
```
import {Foo} from "./Foo";
export class FooFactory {
    function create: Foo {
        return new Foo();
    }
}
```
File: ./foo-factory.Spec.ts
```
import {Foo} from "./foo";
import {FooFactory } from "./foo-factory";
export class FooFactorySpec {
    function assert(): boolean {
        return new FooFactory().create() instanceof Foo;
    }
}
```
**Expected behavior:**
FooFactory.create() returned object is instance of Foo

**Actual behavior:**
FooFactory.create() returned object is not instance of Foo

**Cause**
The cause is the mismatch in the import path, as the one in the FooFactory is capitalized but not in the FooFactorySpec.

**Comment by ajafff** [comment]
That's not specific to typescript. Your file system is case insensitive, but the cache of node's `require` is case sensitive. So it will load the same file twice which will create duplicates of your classes that are totally unrelated to each other.

**Comment by RyanCavanaugh** [comment]
You can use the `--forceConsistentCasingInFileNames` switch to detect these mistakes
