### ISSUE TITLE
how can i escape braces in JSX?

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#14852]
so in my *.tsx i need to do:
```typescript
const styles = <style>
   body { font-family: Arial; }
</style>
```

how can i do that?

**Comment by ajafff** [comment]
Seems like you are on the wrong issue tracker / help forum for that question.

30 seconds of googling led me to this (you could have done that too):
JSX does not support escaping.
https://github.com/facebook/react/issues/1545
http://stackoverflow.com/questions/32363706/escape-curly-brackets-in-props-children

**Comment by aleksey-bykov** [comment]
people who were lookin this very answer and end up here, this is what you do:
```
const styles = <style>
   body {'`{ font-family: Arial; }`}
</style>
```

**Comment by aleksey-bykov** [comment]
@RyanCavanaugh  thanks for help ;)

**Comment by aleksey-bykov** [comment]
it was a question, not a feature request

**Comment by aleksey-bykov** [comment]
take it easy
