### ISSUE TITLE
Generalize methods returning Node type

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#14863]
All methods returning the node type value should return their actual type, like #283(cloneNode) and #12048(appendChild).

**TypeScript Version:**  master

**Expected behavior:**

e.g.

```ts
    insertBefore<T extends Node>(newChild: T, refChild: Node | null): T;
```

**Actual behavior:**

```ts
    insertBefore(newChild: Node, refChild: Node | null): Node;
```

**Comment by RyanCavanaugh** [comment]
@mhegazy ...aren't you busy? 😨

**Comment by mhegazy** [comment]
Just sitting there doing nothing; the wife is doing most of the work :D
