### ISSUE TITLE
Auto-initialisation of string literal types in some circumstances

### ISSUE THREAD

**Issue by danielearwicker** [Microsoft/TypeScript#1486]
Regarding issue #1003. Given:

    interface A { P: "P"; }

All of the following are valid:

    var v1: A = { P: undefined };
    var v2: A = { P: null };
    var v3: A = { P: <any>5 };
    var v4: A = { P: "P" };

But (consistent with TS 1.3) this is not, because it doesn't explicitly initialise `P`:

    var v5: A = { };

I suggest the compiler behave as if `P` had been initialised, as for `v4`. This is the overwhelmingly likely option and avoids the redundancy of both stating the type `A` and repeating the definition of `P`.

For classes:

    class C1 implements A { }
    class C2 { P: "P" }
    class C3 { P: "P" = "P" }

I suggest for C1 and C2 the compiler behave as for C3, for a similar reason: that's almost certain to be what I'd have to write out by hand.

**Comment by mhegazy** [comment]
This looks like a lot of magic. it is not clear when this would happen and when it would not. how can users opt-out of this auto-initialization? what if the object literal has some property declarations, does the auto-initialization still occur? what about optional properties? what about properties that does not have default values...

**Comment by SaschaNaz** [comment]
I think auto-completion list will be better here.

**Comment by mhegazy** [comment]
+1 for @SaschaNaz proposal.

**Comment by SaschaNaz** [comment]
#606 discusses auto-completion of string literals so we can talk more there.
