### ISSUE TITLE
Type inference is not casting inheritance interfaces

### ISSUE THREAD

**Issue by HefloRicardo** [Microsoft/TypeScript#14866]
**TypeScript Version:**  2.2.1

**Code**
```ts
export function sample<T, P extends base<T>, R extends base<T>>(originalFunc: OriginalFunction<T, P, R>) {
}


interface base<T>{
    Misc?: {[keyName: string]: keyof T};  // this will just make evident the cast error and cause the compilation error, without it will compile successfully but if you check the typings will be casted to <any>
}
interface child<T> extends base<T> {
	Items: Array<T>;
}

interface OriginalFunction <T, P, R> {
    <T>(params: P, callback: OriginalCallbacFunc<R>): any;
}

interface OriginalCallbacFunc<R> {
    (err: Error, data: R): any;
}



function functionWithCallback<T>(params: child<T>, callback: (err: Error, data: child<T>) => void) {
}

sample(functionWithCallback); // wrong type inference causes error
```

**Expected behavior:**
Correct typing inference instead of the compilation error.
**Actual behavior:**
The Generic typings are not correctly inferred, so it generates a compilation error.

**Comment by mhegazy** [comment]
Just as a comment. the `T` in `OriginalFunction` is never used. `    <T>(params: P ...)` declares a new type parameter `T` that shadows the `T` from the interface. my guess is you do not need either.
```ts
interface OriginalFunction <T, P, R> {
    <T>(params: P, callback: OriginalCallbacFunc<R>): any;
}
```

**Comment by mhegazy** [comment]
By using that `T` in a place where it can not be infered, you are getting a `{}`, this then does not satisfy the constraint. removing it should address the error you are seeing.
