### ISSUE TITLE
No intellisense when using declare var jQueryAny: JQueryStatic | any;

### ISSUE THREAD

**Issue by born2net** [Microsoft/TypeScript#14862]
**TypeScript Version:**  2.2.1 / nightly (2.2.0-dev.201xxxxx)
TS 2.2.1

**Code**
```
declare var jQueryAny: JQueryStatic | any;
```
**Expected behavior:**
would expect to get intellisense when I type ``` jQueryAny('#foo'). <<< ```
and yet when I use a plugin that does not exist (no d.ts) , I expect to get no errors
so we get the best of both words:  ``` jQueryAny('#foo').carousel() ```

**Actual behavior:**
only ```any``` is being used

Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/Angular-kitchen-sink
Regards,

Sean

**Comment by aluanhaddad** [comment]
That's just the way `any` has always worked. If we think about it, it makes sense that any would subsume the entire Union type because, once at the level of individual members, their types would be more restrictive then the any type.

**Comment by aluanhaddad** [comment]
I should add that I definitely understand the use case here, because they're maybe members not declared in the Declaration file that we still need to use. In fact I've tried to do the same thing myself before. It doesn't work, and overall, manually declaring members leads to more maintainable code, but you know that already.

**Comment by born2net** [comment]
hopefully they reconsider
tx

**Comment by aluanhaddad** [comment]
Actually, after thinking it over, I believe what we are talking about is more what one might expect from intersection types.
The issue with union types is that `any` can not be narrowed.

It would be useful to be able to say that a certain identifier is of the type `any extends JQueryStatic`, that is to say it is at minimum JQueryStatic, but I'm not sure how much sense that makes. This is basically the behavior of the Salsa language service except that it essentially applies to all types always.

**Comment by born2net** [comment]
sure that works for me

**Comment by aluanhaddad** [comment]
Actually it doesn't work at all 😝 and I'm just not sure if it makes sense for it to work, I was just throwing the idea out there.

**Comment by mhegazy** [comment]
Any is both the top and the bottom type; thus any union or intersection with any devolves to any.

The question is why do you need to declare jQueryAny as any?

**Comment by aluanhaddad** [comment]
@mhegazy indeed, the current behavior makes complete sense. I was saying that the functionality that I think is being described here is sometimes useful and that _it_ might not make sense.

The use was
```ts
declare var jQueryAny: JQueryStatic | any;
```
Or in my interpretation
```ts
declare var jQueryAny: JQueryStatic & any;
```
As a way to to declare something that has all of the members of `JQueryStatic` in addition to allowing arbitrary access of unspecified members

**Comment by born2net** [comment]
That's because I often use jquery plug-ins that do not have any definitions which is fine I don't need  them but typescript would complain

**Comment by mhegazy** [comment]
Why not add the plugins you use to JQueryStatic as any instead of declaring the whole thing as any?

**Comment by born2net** [comment]
not sure I understand, can you give an example.. for example I use $.carousel

**Comment by aluanhaddad** [comment]
@born2net when the current file is a _Module_ (a module is a file containing one or more top level `import` or `export` statements) write the following:
```ts
declare global {
  interface JQueryStatic {
    carousel;
  }
}
```

When the current file is **not** a _Module_ write the following:
```ts
interface JQueryStatic {
  carousel;
}
```

**Comment by born2net** [comment]
got it tx!!!

**Comment by born2net** [comment]
so putting 
```
declare global {
    interface JQueryStatic {
        base64:any
    }
}
``` 
in the module does work, but can't I put it in my global typings.d.ts ? as when I try it it won't take it

tx

Sean

**Comment by aluanhaddad** [comment]
In a global file, you would remove the `declare global { }` wrapper. Then interface merging will naturally kick in. The reason for the special construct is simply to access the global scope from within a module.

**Comment by born2net** [comment]
thank you
