### ISSUE TITLE
Typescript compiler is not making separate js files in configured typescriptoutputdirectory when typescriptoutfile is not given

### ISSUE THREAD

**Issue by Nanda-Nandan** [Microsoft/TypeScript#14867]
In my project i have imported msbuild typescript target.If i have 3 files in project after compilation it is generating 3 js files in the root directory of my project,but as per the requirement output should be generated in a specific directory named as "OutputJs".For that i have explicitily set TypeScriptOutDirectory to OutputJs and TypeScriptOutFile to test.js.In this case compiler was able to generate a file named test.js in OutputJs directory.But my requirement is to keep the js files separately so when i removed TypeScriptOutFile setting it stored the compiled file in rootdirectory.
**TypeScript Version:**  2.0.6

**Comment by billti** [comment]
The OutFile setting is for combining the emitted code into one file. The OutDir setting is for specifying the location of the emitted code. If OutFile is not specified, you should get one .js file for each .ts file compiled.

**Comment by Nanda-Nandan** [comment]
@billti  I agree billti,if outfile is not specified it is emiting the code into separate file but not in outDir,it is emitting in project directory,is there any  setting I am missing

**Comment by billti** [comment]
From looking on the docs at https://www.typescriptlang.org/docs/handbook/compiler-options-in-msbuild.html, it states the setting name should be `TypeScriptOutDir`, which is different to what you state above. Can you confirm what the XML element name is? Also, did you edit this manually, or via a VS property page?

**Comment by Nanda-Nandan** [comment]
Thanks @billti that was the problem instead of TypeScriptOutDir i was using TypeScriptOutDirectory .Closing the issue
