### ISSUE TITLE
comment/uncomment operations disabled when Javascript Lang Service is enabled

### ISSUE THREAD

**Issue by markshyn** [Microsoft/TypeScript#14875]
I recently installed Visual Studio 2017 and discovered after a while that the "comment/uncomment code block" operations were disabled.  They were disabled whether I invoked them via the tool bar or via keyboard shortcuts.  Once I unchecked **Tools -> Options -> Text Editor -> Javascript/TypeScript -> Language Service -> Enable the new JavaScript Language service**, the problem went away.  By the way, the problem only happened when opening a javascript file while a solution was open.  If no solution was open, and I opened a javascript file via source control explorer, the problem did not occur.    In addition, if I hover over a close curly brace, the corresponding open curly brace is normally highlighted; with the new editor, this behavior was absent.  I've reverted to the old javascript editor to avoid these issues.

**Comment by RyanCavanaugh** [comment]
@jramsay Bill says you might have fixed this?

**Comment by DominikJaniec** [comment]
I'm facing this problem also. Disabled "Language Services" fixes this, only for just JS files. Any TypeScript file speaks to me with message: "The key combination (Ctrl+K, Ctrl+C) is bound to command (Comment Selection) which is not currently available.", when I try `Ctrl+K+C`...

----

I'm using: Microsoft Visual Studio Enterprise 2017 Version 15.2 (26430.16) Release
VS also shows: TypeScript 2.2.2.0 (TypeScript tools for Visual Studio)

I have installed also:
  * TypeScript SDK 2.4.1.0
  * TypeScript Tools for Microsoft Visual Studio 2015 2.0.6.0
  * Old VS 2015 for stable work experience...

**Comment by mhegazy** [comment]
This should be fixed in [15.3](https://www.visualstudio.com/en-us/news/releasenotes/vs2017-relnotes). please reopen if that is not the case.
