### ISSUE TITLE
JSDoc description for ES6 class properties does not show up in intellisense

### ISSUE THREAD

**Issue by abecks** [Microsoft/TypeScript#14879]
**TypeScript Version:**  2.2.1

This is a JS only project.

**Code**

```js
/**
 * Test class description.
 *
 * @export
 * @class Tester
 */
export class Tester {
  /**
   * Creates an instance of Tester.
   * @param {any} [params]
   */
  constructor (params) {
    /**
     * Test description 1
     * @type {String}
     * @description test description 2
     */
    this.name = params.name
  }

  /**
   * Test method description
   * @memberOf Tester
   */
  testMethod () {

  }
}

// Then open intellisense for an instance of Tester
const test = new Tester()
test.
```

**Expected behavior:**
Show the description, like testMethod:
<img width="577" alt="screen shot 2017-03-27 at 11 30 30 am" src="https://cloud.githubusercontent.com/assets/2068353/24371839/f91b8fde-12e0-11e7-9b6e-2da396ca0066.png">

Should show "Test description 1" or "test description 2"

**Actual behavior:**
No description is shown for the property `name`:
<img width="541" alt="screen shot 2017-03-27 at 11 30 24 am" src="https://cloud.githubusercontent.com/assets/2068353/24371838/f91b1b9e-12e0-11e7-9726-ce2498f86d58.png">

**Comment by arsdimer** [comment]
I have the same problem. JSDoc description for class properties is not shown in intellisense as expected.

This is a single JS file for demo
![2017-06-04 17-46-03](https://cloud.githubusercontent.com/assets/29145109/26761827/2c61d90c-4950-11e7-9930-e44762602a09.png)
