### ISSUE TITLE
Type 'Promise<{}>' is not assignable to type 'Promise<void>'

### ISSUE THREAD

**Issue by Humberd** [Microsoft/TypeScript#14871]
**TypeScript Version:**  2.2.1

**Code**

```ts
create(options: NotificationOptions): Promise<void> {

  return new Promise((resolve, reject) => {
    resolve();
  })
}
```

**Expected behavior:**

As I resolve without parameters it should be a valid statement.

**Actual behavior:**

```
Type 'Promise<{}>' is not assignable to type 'Promise<void>'
```
I did the exact syntax in Typescript `2.0.1` and it worked there.

What's the workaround or a fix?

**Comment by cevek** [comment]
The first problem that ts cannot infer a `void` type
```ts
class Foo<T> {
  constructor(public value?: T) {    
  }
}
var a = new Foo(); // a type is Foo<{}>
```

And second problem is `{}` type is not compatible with `void` type;
```ts
var b = new Foo<void>();
a = b; // error
``` 


So, you must specify return Promise type directly:
```ts
return new Promise<void>((resolve, reject) => {
    resolve();
})
```

**Comment by marcusjwhelan** [comment]
Till an issue with 2.6 as far as I can tell

**Comment by HibaH1** [comment]
Hi All,
Any fix for this issue please?

Thanks

**Comment by changkun** [comment]
I fixed this problem by replace Promise<void> by Promise<any>.

**Comment by MarkWilsoncom** [comment]
Issue still in 2.6.2 - thx changkun for the workaround :-)

**Comment by mhegazy** [comment]
The original issue seems to be working as expected in `typescript@next`

**Comment by mhegazy** [comment]
For the case in https://github.com/Microsoft/TypeScript/issues/14871#issuecomment-289443759, i would recommend using generic parameter defaults.. e.g.:

```ts
function f<T=undefined>(a? : T) : T { .. }
```
