### ISSUE TITLE
`URL` typing is missed in ServiceWorkerGlobalScope

### ISSUE THREAD

**Issue by VincentBel** [Microsoft/TypeScript#14878]
The `URL` typing is not in ServiceWorkerGlobalScope in [`lib/lib.webworker.d.ts`](https://github.com/Microsoft/TypeScript/blob/v2.2.2/lib/lib.webworker.d.ts#L1374-L1389), but [it is available in Web Workers(from mdn)](https://developer.mozilla.org/en/docs/Web/API/URL):

> **Note**: This feature is available in Web Workers.

---

**TypeScript Version:**  2.2.1

**Expected behavior:**

Can access `URL` in ServiceWorkerGlobalScope.

**Actual behavior:**

Access `URL` in ServiceWorkerGlobalScope with error.

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.
