### ISSUE TITLE
Erroneous "Object is possibly null" message

### ISSUE THREAD

**Issue by nathantreid** [Microsoft/TypeScript#14889]
**TypeScript Version:**  2.2.1

The option `strictNullChecks` is enabled.

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
class Foo {
  public foo: string | null;

  bar() {
    const shouldDoSomething = this.foo !== null;

    if (shouldDoSomething) {
      return this.foo.length;
    }
  }
}
```

**Expected behavior:**
There should not be an error, since I have just checked that the object isn't null. This should have the same effect as the following:
```ts
class Foo {
  public foo: string | null;

  bar() {
    if (this.foo !== null) {
      return this.foo.length;
    }
  }
}
```

**Actual behavior:**
TypeScript throws an error on the `foo` object: "TS2531 Object is possibly null".

The workaround I'm using follows, but isn't what I'd consider ideal:
```ts
class Foo {
  public foo: string | null;

  bar() {
    const shouldDoSomething = this.foo !== null;

    if (shouldDoSomething) {
      return (<string>this.foo).length;
    }
  }
}
```
As a real example, I have a boolean `shouldEmitToOccupant` that determines whether or not an event should be emitted to an occupant of a certain tile in my game. This variable is only true if several tests are passed, the first of which is the null check. For now I'm using an assertion, but it seems like I shouldn't have to...

**Comment by RyanCavanaugh** [comment]
Same response as #10830. #10421 would be a good solution.

What I usually do is move out the `null` check to an early return:
```ts
class Foo {
  public foo: string | null;

  bar() {
    if (this.foo === null) return;
    const shouldDoSomething = (more checks...);

    if (shouldDoSomething) {
      return (<string>this.foo).length;
    }
  }
}
```

**Comment by aluanhaddad** [comment]
Why not use a local `const` bonding? If foo were a getter there would be no way to know that it would not return null the next time it was evaluated.

**Comment by RyanCavanaugh** [comment]
That wouldn't help since there's still no tracking between `shouldDoSomething` and the local `const`'s `null`ness

**Comment by aluanhaddad** [comment]
@RyanCavanaugh gotcha, thanks for explaining.
