### ISSUE TITLE
"this" type constraint incorrectly and automatically gets widened to a nullable type

### ISSUE THREAD

**Issue by AlexGalays** [Microsoft/TypeScript#14894]
**TypeScript Version:**  2.2.2

**Code**

```ts
export interface Message<P> {
  with<Data, E extends Event>(this: Message<[E, Data]>, data: Data): Message<E>
}

function Message<P>(): Message<P> { return {} as any }

const myMessage = Message<[Event, string]>()

myMessage.with(null)
```

**Expected behavior:**
I shouldn't be able to call `with()` with `null` when using `strictNullChecks` = true. `string` is not a nullable type.

**Actual behavior:**
It compiles.

Notes:

It's only broken when using `null` or `undefined`. I can't pass a completely different type like ` number`.

It also seems possible to work around it with this redundant hack:

```ts
export interface Message<P> {
  with<Data extends P[1], E extends Event>(this: Message<[E, Data]>, data: Data): Message<E>
}
```

**Comment by RyanCavanaugh** [comment]
I don't understand why we infer a union type for `Data` here.

**Comment by mhegazy** [comment]
> I don't understand why we infer a union type for Data here.
We have two inferences, `string` and `null`, we try to get the common super type,  but we first remove nullable types, get the super type, then add nullable back. I do not think this is the intended behavior here though..

**Comment by DanielRosenwasser** [comment]
Here's something that will avoid drawing `null` as an inference for `Data`:

```ts
export interface Message<P> {
  with<Data, E extends Event, Arg extends Data>(this: Message<[E, Data]>, data: Arg): Message<Arg>
}

function Message<P>(): Message<P> { return {} as any }
const myMessage = Message<[Event, string]>()
myMessage.with(null)
 
```

**Comment by sandersn** [comment]
Unfortunately, this is a place where the inference algorithm doesn't match intuitions. @AlexGalays does @DanielRosenwasser's workaround help?

**Comment by AlexGalays** [comment]
@sandersn  / @DanielRosenwasser  The workaround appears to work fine. Is it "safe" because function params are stuck to being bivariant anyway? Otherwise I wouldn't want a covariant argument.

**Comment by AlexGalays** [comment]
There are other issues with the this pointer constraint. Not sure if it's related?

In 2.3.2 or next

```ts
type ObjectLiteral = object & { reduceRight?: 'nope' }

interface CanBeChained<O> {
  at<A>(this: CanBeChained<A[]>, index: number): CanBeChained<A | undefined>
  at<K extends keyof O>(this: CanBeChained<ObjectLiteral>, key: K): CanBeChained<O[K]>
}

({} as any as CanBeChained<string>).at('oops')
```

I would expect `at` to not be callable at all (e.g fail with a no signature found error) when using a CanBeChained<string> since it's not an object or an Array.

Instead the error is : 

```
[ts] Argument of type '"oops"' is not assignable to parameter of type '"match" | "replace" | "search" | "split" | "codePointAt" | "includes" | "endsWith" | "normalize" ...'.
```

Which indicates the compiler decided to infer string as being an ObjectLiteral. In fact, it will give up and use the last function definition.
