### ISSUE TITLE
Suggestion: Emit argument validators

### ISSUE THREAD

**Issue by aaronbeall** [Microsoft/TypeScript#14898]
**TypeScript Version:**  2.2.1 / nightly (2.2.0-dev.201xxxxx)

In JS its a common practice to perform basic type validation on input parameters:

```js
function foo(str, required) {
  if (typeof str !== "string")
    throw "Argument 'str' must be a string."
  if (typeof required === "undefined")
    throw "Argument 'required' must not be undefined."
}
```

Of course, at compile-time in TS we have a much more robust system to express this stuff. However, when it gets compiled to JS we lose all safety. This is probably not a big concern when you're dealing with a pure TS project (although there are still plenty of ways to encounter JS runtime types that are inconsistent with compile-time types), but it becomes a bigger problem if some of your project is written in JS (`allowJs`), or you are consuming JS libraries that don't have strict static interop with TS, or you are publishing a library to JS for other JS projects. 

In my experience with TS I still spend a lot of time debugging down-stream JS errors that could have been caught by a function argument validator much sooner.

Of course there's nothing stopping us from manually writing argument validators all the time. However it would be very useful if TS could emit basic validators based on the static type information we have already meticulously built in our project. 

Or maybe this would be a good use case for compiler extensibility?

**Comment by RyanCavanaugh** [comment]
See #1573
