### ISSUE TITLE
Inferred return type for function that return type assertion should be `is [type]`

### ISSUE THREAD

**Issue by mohsen1** [Microsoft/TypeScript#14891]
**TypeScript Version:**  2.2.1 

**Code**

```ts
function isString(x: any) {
    return typeof x === 'string';
}
```

**Expected behavior:**

Inferred type of foo is `function isString(x: any): boolean`

**Actual behavior:**

Inferred type should be `function isString(x: any): x is string`

**Comment by mhegazy** [comment]
Related to https://github.com/Microsoft/TypeScript/issues/5101 (and https://github.com/Microsoft/TypeScript/issues/10734 tangentially)

I believe we discussed this before in the past, and concluded it was too complex to implement in the general case. doing it right needs to combine control-flow analysis with some sort of data flow analysis.
