### ISSUE TITLE
VS: Compile-on-save ignores Combine-JavaScript-output option

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/TypeScript#1489]
Hi,

**VS**: 2013 Update 4 RC
**TS**: typeScriptServices.js from LKG as of 12-Dec

When both the options "Compile-on-save" and "Combine-JavaScript-output" are set, saving a TypeScript code file results in the `.js` output file being generated as a separate file instead of being added to the combined output file.

**Comment by paulvanbrenk** [comment]
In the TypeScript HTML app I don't reproduce either of the issues you've reported using the version of TypeScript we plan to ship for 1.4.

In a node project I do reproduce the "Redirect-JavaScript-output-to-directory" problem using their NTVS 1.0 RC2 release, which looks like it's a known issue on their end.
