### ISSUE TITLE
Property 'href' does not exist on SVGUseElement

### ISSUE THREAD

**Issue by jacobwindsor** [Microsoft/TypeScript#14893]
**TypeScript Version:**  2.2.2

**Code**
In React:
```
Property 'href' does not exist on type 'SVGProps<SVGUseElement>'.
```

**Expected behavior:**
The MDN [SVGUseElement](https://developer.mozilla.org/en-US/docs/Web/API/SVGUseElement) does not include the `href` property but I believe it is required to actually 'use' it. If you look [here](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/use) `xlink:href` was used in the example. However, that has now been deprecated in SVG 2 to drop the xlink namespace, see [here](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href).

**Actual behavior:**
Allow href property

**Comment by mhegazy** [comment]
Where is `SVGProps` defined?

**Comment by RyanCavanaugh** [comment]
This comes from a definition file
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/354cec620daccfa0ad167ba046651fb5fef69e8a/types/react/index.d.ts

React does *not* list `href` as a supported SVG property.
https://facebook.github.io/react/docs/dom-elements.html

See also
http://stackoverflow.com/questions/26815738/svg-use-tag-and-reactjs

It looks like you want `xlinkHref` instead
