### ISSUE TITLE
[bug] Blob type is not supported, TSC 2.2.2

### ISSUE THREAD

**Issue by nkrass** [Microsoft/TypeScript#14897]
TypeScript Version: 2.2.1, 2.2.2

After installing @types for aws-sdk I receive an error that the type Blob is not supported:
Error message: 
349         Data: Buffer | string | Blob;
                                                   ~~~~

node_modules/@types/aws-sdk/index.d.ts(349,33): error TS2304: Cannot find name 'Blob'.

Expected behavior: Should support this type

**Comment by mhegazy** [comment]
Do you have `--lib` specified? if so make sure you have `DOM` included in the argument, e.g. `--lib es6,dom`

**Comment by nkrass** [comment]
@mhegazy yes, it helped. thank you.
the issue can be closed

**Comment by ToanP** [comment]
1) tsconfig.json should be 
{
  "compileOnSave": true,
  "compilerOptions": {
    "module": "commonjs",
    "target": "es5",
    "noImplicitAny": false,
    "strictNullChecks": true,
    "alwaysStrict": true,
    "preserveConstEnums": true,
    "sourceMap": false,
    "moduleResolution": "Node",
    "lib": [
      "dom",
      "es2015",
      "es5",
      "es6"
    ]
  },
  "include": [
    "*",
    "src/**/*"
  ],
  "exclude": [
    "./node_modules"
  ]
}

2) to build a specific typescript file main.ts, the command is:
tsc --lib "es5,es6,es2015,dom" ./main.ts

**Comment by ToanP** [comment]
1) tsconfig.json should be 
{
  "compileOnSave": true,
  "compilerOptions": {
    "module": "commonjs",
    "target": "es5",
    "noImplicitAny": false,
    "strictNullChecks": true,
    "alwaysStrict": true,
    "preserveConstEnums": true,
    "sourceMap": false,
    "moduleResolution": "Node",
    "lib": [
      "dom",
      "es2015",
      "es5",
      "es6"
    ]
  },
  "include": [
    "*",
    "src/**/*"
  ],
  "exclude": [
    "./node_modules"
  ]
}

2) to transpile a specific typescript file main.ts
tsc --lib "es5,es6,es2015,dom" ./src/main.ts
