### ISSUE TITLE
2.2.2 lib.es6.d.ts type resolutions

### ISSUE THREAD

**Issue by mrtristan** [Microsoft/TypeScript#14906]
this is probably a dupe but was having trouble matching this to one of the existing issues:

upgrading to `2.2.2` from `2.1.6` while targeting `ES6` is yielding the existence of interfaces like `PaymentResponse` within lib.es6.d.ts which incidentally is already the name of an interface in my world that would not be so simple to change around... how can i exclude some definitions such as that one to get past this `TS2300: Duplicate identifier` problem?

is this really some sort of public api that belongs in there? `PaymentResponse` for what exactly?

thanks!

**Comment by mhegazy** [comment]
[`PaymentResponse`](https://developer.mozilla.org/en-US/docs/Web/API/PaymentResponse) is part of the [Payment Request DOM API](https://developer.mozilla.org/en-US/docs/Web/API/Payment_Request_API); as new DOM APIs get added, the standard library will add their definitions.

Are you using the DOM API's in your project? if not you can exclude this portion of the library using `--lib`.

If not, consider using modules, since modules provide their own scoping, and/or use `namespace`s for organizing your code.

**Comment by mrtristan** [comment]
not to stifle progress in realms i'm not familiar with, but i would expect something like that to be an explicit inclusion rather than an exclusion. i did try `noLib` in my `tsconfig` yet that yielded some other problems along the lines of 

```error TS2318: Cannot find global type 'Array'.
error TS2318: Cannot find global type 'Boolean'.
error TS2318: Cannot find global type 'Function'.
error TS2318: Cannot find global type 'IArguments'.
error TS2318: Cannot find global type 'Number'.
error TS2318: Cannot find global type 'Object'.
error TS2318: Cannot find global type 'RegExp'.
error TS2318: Cannot find global type 'String'.
```

is this the appropriate path to take? set `noLib` and then somehow bolt these guys back in? sorry for the perhaps silly questions, i'm having trouble finding some documentation on some of the latest and greatest nuances of TS.

i intend to take your suggestion as well, just looking for a solution for this problem before taking on a refactor.

**Comment by mhegazy** [comment]
If you use `--noLib` the assumption is you have a hand-crafted library file that you included. the minimum to be included in this file are the declarations of the built in types listed in the error messages, these can be as simple as `interface Array<T> {}` if you so choose.

you also have the option to use `--lib es5`. this will give you the standard library as would be on an ES5-compliant JS engine, but will exclude the `DOM`, `webworkers`, etc..

**Comment by mrtristan** [comment]
gotcha. i appreciate the time and thoughts and apologize if this is perhaps an inappropriate venue for all of this. only real remaining question to you i think at this point is if you're aware of any way to essentially keep everything in place, yet circumvent some interfaces by perhaps deleting them or overwriting them in some way at compile time or something along those lines.

it sounds like the proper approach for me at this point is the namespacing and such, my only challenge there is coordinating the refactor of the process that i wrote that generates all of the typings based off of the model definitions within my Web API dlls...

**Comment by mhegazy** [comment]
The library file is just a regular declaration file. you can start with `lib.d.ts` as it stands today, and remove the APIs you do not need, and include this in your compilation, doing so will avoid the compiler injecting its own library file in the compilation, and avoids the issues.
