### ISSUE TITLE
emit generators when targeting es5

### ISSUE THREAD

**Issue by marzelin** [Microsoft/TypeScript#14903]
**TypeScript Version:**  2.2.1

When I use generators in my code while targeting es5, the following error appears:
*'Generators are only available when targeting ECMAScript 2015 or higher.'*
but tslib already provides a generator helper (it's used when converting async functions).
It would be nice if typescript was able to emit bare generators as well.

**Comment by mhegazy** [comment]
This should be coming in [TS 2.3](https://github.com/Microsoft/TypeScript/wiki/Roadmap#23-may-2017) under `---downlevelIteration` flag. You should be able to try it out in `typescript@next` today.

**Comment by mhegazy** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/1564. Fixed by https://github.com/Microsoft/TypeScript/pull/12346
