### ISSUE TITLE
noUnusedLocals and object spread destructuring of function arguments

### ISSUE THREAD

**Issue by steadicat** [Microsoft/TypeScript#14901]
**TypeScript Version:**  2.2.2

**Code**

```ts
// no error
function one(arg) {
  const {a, ...bar} = arg;
  console.log(bar);
}
one({a: 1, b: 2});

// 'a' is declared but never used
function two({a, ...bar}) {
  console.log(bar);
}
two({a: 1, b: 2});

```

**Expected behavior:**
Unused variable `a` declared in `two()` causes no error, just like `a` in `one()`.

**Actual behavior:**
TypeScript complains about `a` being unused in function `two()`, but not in function `one()`, even though they are equivalent.

Ignoring unused variables in object destructuring was allowed in https://github.com/Microsoft/TypeScript/issues/12766, but that only fixed the assignment. The function argument case wasn't changed to match. They should behave the same way.

**Comment by mhegazy** [comment]
Should be fixed in latest.
