### ISSUE TITLE
Static analysis ignores side effects

### ISSUE THREAD

**Issue by sigise** [Microsoft/TypeScript#14908]
**TypeScript Version:**  2.2.1

**Code**

```ts
class X
{
  m = 1;

  a(): void
  {
    if (this.m == 2) {
      this.b();
      if (this.m == 3) { // error TS2365: Operator '==' cannot be applied to types '2' and '3'.
      }
      this.m=3;
      if (this.m == 3) { // here we are fine.
      }
    }
  }
  b(): void
  {
    this.m = 3;
  }
}
```

**Expected behavior:**
Compile without errors.

**Actual behavior:**
x.ts(9,11): error TS2365: Operator '==' cannot be applied to types '2' and '3'.

The compiler seems to miss side effects of a member function call.

**Workaround:**
Make the member access an expression (eg. this.m+0 == 3) 👎

**Comment by RyanCavanaugh** [comment]
See #9998

**Comment by aluanhaddad** [comment]
Does writing code like that have any advantage? returning `3` from `b` would be so much more readable.

**Comment by sigise** [comment]
Why do I write code like this? Just to give a small example of the general problem ;)
