### ISSUE TITLE
Webworker library is missing Date type

### ISSUE THREAD

**Issue by FraserKillip** [microsoft/TypeScript#14914]
**TypeScript Version:**  next / 2.3.0-dev.20170327

**Code**

```ts
// file: shift-roster.worker.ts

/// <reference path="../../../node_modules/typescript/lib/lib.webworker.d.ts" />

// Line 48
param => new Date(param.StartDateTime),


// Lines 89 - 95
self.addEventListener('message', (event) => {
    const command = event.data; // line 90

    self.postMessage(shiftRosterWorker[command.action](...command.data), null); // line 94
});

```

**Expected behavior:**
Referencing the webworker library changes signature of 'self' to reflect the different api in DedicatedWorkerGlobalScope such as self.postMessage

**Actual behavior:**
Types are not found and methods don't exist. Type `Date` is is not available. Error log below:

ERROR in [at-loader] ./src/app/workers/shift-roster.worker.ts:48:48 
    TS2304: Cannot find name 'Date'.

ERROR in [at-loader] ./src/app/workers/shift-roster.worker.ts:90:27 
    TS2339: Property 'data' does not exist on type 'Event'.

ERROR in [at-loader] ./src/app/workers/shift-roster.worker.ts:94:10 
    TS2339: Property 'postMessage' does not exist on type 'WorkerGlobalScope'.

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by isao** [comment]
I see this with 2.3.2 as well.

tscconfig.json:

    "lib": ["ES6", "WebWorker"],
    "module": "es2015",
    "target": "es2015"

error:

    19         self.postMessage({success: false, reason: '...'});
                    ~~~~~~~~~~~
    src/foo/index.ts(19,14): error TS2339: Property 'postMessage' does not exist on type 'WorkerGlobalScope'.

However omitting `self` works without error: `postMessage({success: false, reason: '...'});`

I looked at the generated file `TSJS-lib-generator/inputfiles/webworkers.specidl.xml` and noticed that `DedicatedWorkerGlobalScope` extends `WorkerGlobalScope` and adds `postMessage` and `onmessage`. I'd like to make a fix, but.. this should be fully supported by Edge and the contribution/readme suggests to me this should come from the "XML spec file generated by Microsoft Edge that contains types for Web Workers"

**Comment by saschanaz** [comment]
Should probably have been fixed?

**Comment by unadlib** [comment]
Need to define or assert type:

```ts
declare var self: DedicatedWorkerGlobalScope;
```

or

```ts
(self as DedicatedWorkerGlobalScope).postMessage({success: false, reason: '...'});
```

**Comment by DominicTobias** [comment]
Hm I get `Cannot find name 'DedicatedWorkerGlobalScope'.ts(2304)` doing `declare var self: DedicatedWorkerGlobalScope`

```json
{
  "compilerOptions": {
    "strict": true,
    "target": "ES2021",
    "module": "ESNext",
    "lib": ["WebWorker", "DOM", "ES2021"],
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "jsx": "preserve",
    "jsxImportSource": "solid-js",
    "types": ["vite/client"],
    "noEmit": true,
    "isolatedModules": true,
    "baseUrl": "."
  },
  "include": ["vite.config.ts", "src"]
}
```

**Comment by fatihgozenc** [comment]
```ts
/// <reference types="typescript/lib/lib.webworker" />

declare const self: DedicatedWorkerGlobalScope;
export default {} as typeof Worker & { new(): Worker; };

self.onmessage = async (e) => {
	const dateTest = new Date(1675601809619)
	console.log(`(WORKER)`, dateTest, e.data );
};
```

Referencing can be used in this way. `Date` and `DedicatedWorkerGlobalScope` didn't create an error for me. `compilerOptions.lib` doesn't have `WebWorker` in my project and I am using version `4.9.4`.

**Comment by saschanaz** [comment]
It's `webworker`, not `WebWorker`.

**Comment by Andarist** [comment]
I don't think that the webworker library should declare `Date`. Just like DOM library doesn't declare it. It belongs to es5 and to make it available you should have that in your `lib` option.

There are some other issues mentioned in this thread but I think they deserve their own threads (some of them already have them). I'd say that this issue can be closed, cc @jakebailey

**Comment by jakebailey** [comment]
Yes, agreed; not sure how this got derailed.
