### ISSUE TITLE
Type mapping of transformation

### ISSUE THREAD

**Issue by Roam-Cooper** [Microsoft/TypeScript#14919]
This is more of a suggestion than a proposal. I think it's nicer to get developer and community feedback on an idea before creating a proposal.

We've been playing around with TS 2.1's type mapping features, enforcing the types of an interface on developers' implementations in an indirect way, which is excellent.

But we're also wondering if it's possible to do the reverse. For example creating an "interface"/type by mapping the values of the types passed to an implementation. We specifically want to extract the type of a generic on properties of an object.

For example if I have an object defined as
```ts
let thing = {
    a: new SSchema<number>(),
    b: new SSchema<string>(),
    c: new SSchema<boolean>()
};
```

It would be cool to be able to use type mapping to remap the known type of the variable in say, a function so that we can perceive "thing" as:

```ts
interface Thing{
    a: number;
    b: string;
    c: boolean;
}
```

Ie type mapping has extracted the names of the keys as well as the type of the value of each key and has also extracted the type of the generic types.

All of the types that are passed in are known at design time so this should definitely be possible to implement if it hasn't been already. The reason that this is incredibly useful is that my implementation might perform a transformation at run-time, so being able to map the transformation using the type system would be absolutely amazing!

If there's some way to do this already then I would be very interested! Especially being able to extract the type from a generic when type mapping!

**Comment by Roam-Cooper** [comment]
Never mind, I've figured it out! I'll pop back and edit this comment to include how I did it in case someone arrives here in the future!

**Comment by Roam-Cooper** [comment]
It seems as though what I'd done hadn't actually fixed it, my work around is still to have developers write an interface and then use type mapping to force them to implement a value that matches this interface, whereas what we can't seem to do currently is create the type from the value/implementation through type mapping when generics are involved.

There's also a problem with {} type generics being accepted/ignoring the type system when using generics in type mapping unless the generic type T is used in a property on the class...it's not the type system being switched off completely, either, for an interface type, it refuses primitives like number, but accepts {} or a partial implementation of the interface unless said property is on the class.

I will return to do a write up after the work day has ended here.

**Comment by michael8090** [comment]
@Roam-Cooper How did you solve your problem? Could you provide some code here?
