### ISSUE TITLE
Mixins, really? Why not compile-time partial class support?

### ISSUE THREAD

**Issue by cosmoKenney** [Microsoft/TypeScript#14913]
Mixins, to me, are a mess. Each time I start to read about them my head hurts trying to figure out how they work. 

Lots of people have asked for COMPILE-TIME partial class and method support. 

I would propose the following -- just like C#:
File1.ts:
```javascript
// Imagine this file is code generated and could be regenerated during development
export partial class Contact
{
    firstName: string;
    lastName: string;
    partial OnInit( args: any ) : void;
    constuctor( args: any )
    {
        this.OnInit( args );
    }
}
export class Address
{
    addr: string;
    city: string;
    state: string;
    zip: string;
}
```

File2.ts
```javascript
// See where I'm going with this? This file would be hand edited and allows me to specify associations and children.
partial class Contact
{
    Addresses: string[] = [];
    partial OnInit( args: any ) void
    {
        this.firstName = args.firstName;
        this.lastName = args.lastName;
        this.Addresses.push( new Address() );
    }
}
```

Transpiling the above would emit one JS class for Contact, something like this:
```javascript
var Contact = (function () {
    function Contact() {
         this.Addresses = [];
   }
   Contact.prototype.constuctor = function (args) {
       this.OnInit( args );
   };
   Contact.prototype.OnInit = function (args) {
       this.firstName = args.firstName;
       this.lastName = args.lastName;
       this.Addresses.push(new Address());
   };
   return Contact;
})();

var Address = (function () {
    function Address() {
    }
    return Address;
})();
```

**Comment by RyanCavanaugh** [comment]
#563
![image](https://cloud.githubusercontent.com/assets/6685088/24472553/faffe4da-147a-11e7-90a4-dbdd6460c368.png)

**Comment by cosmoKenney** [comment]
I wish you wouldn't have closed this because the other issues asking for partial classes have turned argumentative matches between people who's opinion sways towards mixins and the partial class proponents. Mixins do not address the issues being asked for by the proponents of partial casses.

**Comment by cosmoKenney** [comment]
@RyanCavanaugh I wish you wouldn't have closed this because the other issues asking for partial classes have turned argumentative matches between people who's opinion sways towards mixins and the partial class proponents. Mixins do not address the issues being asked for by the proponents of partial classes.

**Comment by RyanCavanaugh** [comment]
I don't see how opening a duplicative issue with a combative title is going to fix that situation. There's a ton of discussion in that thread and if you really want to open a "fresh start" issue, it needs to start with a summary of the positions in that thread, drawbacks, benefits, an examination of the current state of the world, and an emit proposal that could handles single-file transpilation.

**Comment by cosmoKenney** [comment]
Okay, that's fine with me. I commented over on the other thread. I just want to make it work. If you can comment over there or provide a like that might lead to guidelines I'd appreciate.
