### ISSUE TITLE
Allow `let` and `const` together in one declaration

### ISSUE THREAD

**Issue by jhpratt** [Microsoft/TypeScript#14922]
This doesn't have much use case outside of `for` loops, which is where it would be quite useful.

**Use case**

```ts
for( let i=0, const len=5; i<len; i++ ) { ... }
```

**Expected behavior:**
Same as:
```ts
let i = 0;
const len = 5;
```

**Actual behavior:**
Error - it has to be either `let i=0, len=5` or `const i=0, len=5`, which is not what is wanted. The length does not change, where `i` does.

**Comment by mhegazy** [comment]
This is the syntax as specified by the JS spec; we try to keep the divisions from the js spec to a minimum, and in general avoid adding new syntax outside the type annotations space to prevent collisions with future changes of js. 

In general we recommend making these proposals for TC39 instead (https://github.com/tc39/proposals/blob/master/README.md).

**Comment by jhpratt** [comment]
Gotcha. I'll definitely bring it up for a future version of ECMAScript.
