### ISSUE TITLE
Type arguments for WebGLRenderingContext.uniform*fv as ArrayLike<number> instead of number[]

### ISSUE THREAD

**Issue by jkieboom** [Microsoft/TypeScript#14925]
The `uniform*fv` methods on `WebGLRenderingContext` currently accept a `Float32Array | number[]`, however it would be nicer if they could accept `Float32Array | ArrayLike<number>`. The webgl specification gives two signatures for these methods, one accepting a `Float32Array` and another accepting a `sequence<GLFloat>`. Hence it doesn't require an actual array, just something that may be indexed. `ArrayLike<number>` seems like a better fit.

**TypeScript Version:**  2.2.1 / nightly (2.2.0-dev.201xxxxx)

**Code**

```ts
function applyUniforms(v: ArrayLike<number>) {
  // Cannot pass v to uniform4fv and friends
  gl.uniform4fv(location, v);
}
```

**Expected behavior:**

I expected that I could, the webgl specification does not require this to be an actual array, it says `sequence<GLFloat>`.

**Actual behavior:**

It refuses to compile and I need to cast `v`.

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by lankaapura** [comment]
@mhegazy I'd like to work on this. Can you confirm following is correct?
1. PR to [Microsoft/TSJS-lib-generator](https://github.com/Microsoft/TSJS-lib-generator) to update `dom.generated.d.ts`, `webworker.generated.d.ts` and `dom.es6.generated.d.ts`
2. updating method signatures of uniform* in lib.d.ts and lib.*.d.ts files except for above files
3. Do I need to do any modifications in tests\lib\lib.d.ts?

**Comment by mhegazy** [comment]
> PR to Microsoft/TSJS-lib-generator to update dom.generated.d.ts, webworker.generated.d.ts and dom.es6.generated.d.ts

you want to update the input files like https://github.com/Microsoft/TSJS-lib-generator/blob/master/inputfiles/overridingTypes.json, then rerun the script. you then need to update baseline\* with your local generated\* and send a PR.

**Comment by lankaapura** [comment]
Thanks @mhegazy, Create PR  https://github.com/Microsoft/TSJS-lib-generator/pull/368 for this. Let me know if there any issues.
