### ISSUE TITLE
Dev Mode on VS2017 does not work

### ISSUE THREAD

**Issue by SaschaNaz** [Microsoft/TypeScript#14928]
[The Dev Mode document](https://github.com/Microsoft/TypeScript/wiki/Dev-Mode-in-Visual-Studio) says "Dev Mode does not currently work with Dev15 Preview 5", does the same applies to VS2017 stable? EnableDevMode does not show script files when attaching to VS2017 process so I cannot debug. It seems CustemTypeScriptServicesFileLocation also does not work.

I used Computer\HKEY_CURRENT_USER\Software\Microsoft\VisualStudio\15.0\TypeScriptLanguageService directory.

**Comment by billti** [comment]
The language service no longer runs either inside Visual Studio, or inside the chakra engine, so the old method of script debugging no longer works.

You can still set a custom tsserver.js location to use. See https://github.com/Microsoft/TypeScript/issues/14529#issuecomment-287517438 .
