### ISSUE TITLE
Typed instance.constructor

### ISSUE THREAD

**Issue by pleerock** [Microsoft/TypeScript#14927]
This is a valid javascript code:

```ts
const ExtendedPostRepository = new class extends PostRepository.constructor {
};
console.log(ExtendedPostRepository.getList());
```

however I can't extend `PostRepository.constructor` in typescript. Is there a way typescript can make magic properties like constructor and prototype type-safe? This will help to extend anonymous classes:

```ts
export const PostRepository = new class {

    getList() {
        return [];
    }

};

const ExtendedPostRepository = new class extends PostRepository.constructor {
   /// override if needed, have "this." with proper type hinting
};
console.log(ExtendedPostRepository.getList());
```

Another side note, but related - dynamic usage of prototype/constructor properties are heavily used in testing. Refactoring makes easy to refactor domain logic code, but not tests. We still should manually add corrections in tests. 

I believe typescript team and community can came up here with something after recent mixins and mapped types innovations 😉

**Comment by RyanCavanaugh** [comment]
#3841
