### ISSUE TITLE
multiple destructurings of the same function doesnt 

### ISSUE THREAD

**Issue by typedefJorge** [Microsoft/TypeScript#14921]
**TypeScript Version:**  2.2.1 / nightly (2.2.0-dev.201xxxxx)

So my issue is that I want to destructure from the same function multiple times in the same function. I wanted to destructure into a couple of variables declared with let, and then reassign into those same variables on a second or third destructure. I wanted to ideally do something like:
```ts
let { first, second } = ThirdPoints.between(boundingRect.topLeft, boundingRect.topRight);
arr[0] = first.x;
arr[1] = first.y;
arr[2] = second.x;
arr[3] = second.y;
let mid = Midpoint.between(boundingRect.topRight, boundingRect.bottomRight);
arr[4] = mid.x;
arr[5] = mid.y;
{ first, second } = ThirdPoints.between(boundingRect.bottomRight, boundingRect.bottomLeft);
```
But instead I had to use var and declare the same variables multiple times.
```ts
let arr = new Float32Array(12);
var { first, second } = ThirdPoints.between(boundingRect.topLeft, boundingRect.topRight);
arr[0] = first.x;
arr[1] = first.y;
arr[2] = second.x;
arr[3] = second.y;
let mid = Midpoint.between(boundingRect.topRight, boundingRect.bottomRight);
arr[4] = mid.x;
arr[5] = mid.y;
var { first, second } = ThirdPoints.between(boundingRect.bottomRight, boundingRect.bottomLeft);
arr[6] = second.x;
arr[7] = second.y;
arr[8] = first.x;
arr[9] = first.y;
```
heres the code for the function and the tuple type
```ts
export interface Tuple<T1, T2>
{
    first: T1;
    second: T2;
}

export class ThirdPoints
{
    public static between(point1: Point2d, point2: Point2d): Tuple<Point2d, Point2d>
    {
        let largerX = Math.max(point1.x, point2.x);
        let smallerX = Math.min(point1.x, point2.x);
        let largerY = Math.max(point1.y, point2.y);
        let smallerY = Math.min(point1.y, point2.y);
        let thirdX = (largerX - smallerX) / 3;
        let thirdY = (largerY - smallerY) / 3;
        let firstThird = {x: smallerX + thirdX, y: smallerY + thirdY};
        let secondThird = {x: firstThird.x + thirdX, y: firstThird.y + thirdY};
        return { first: firstThird, second: secondThird };
    }
}
```
So even though i got it to work with var, id prefer to use let and not have to reallocate space to store the data in another variable where it could maybe be stored in the same location.

Also here is the link to the playground compiling all of this: https://www.typescriptlang.org/play/index.html#src=interface%20Point2d%0D%0A%7B%0D%0A%20%20%20%20x%3A%20number%3B%0D%0A%20%20%20%20y%3A%20number%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20Tuple%3CT1%2C%20T2%3E%0D%0A%7B%0D%0A%20%20%20%20first%3A%20T1%3B%0D%0A%20%20%20%20second%3A%20T2%3B%0D%0A%7D%0D%0A%0D%0Aclass%20ThirdPoints%0D%0A%7B%0D%0A%20%20%20%20public%20static%20between(point1%3A%20Point2d%2C%20point2%3A%20Point2d)%3A%20Tuple%3CPoint2d%2C%20Point2d%3E%0D%0A%20%20%20%20%7B%0D%0A%20%20%20%20%20%20%20%20let%20largerX%20%3D%20Math.max(point1.x%2C%20point2.x)%3B%0D%0A%20%20%20%20%20%20%20%20let%20smallerX%20%3D%20Math.min(point1.x%2C%20point2.x)%3B%0D%0A%20%20%20%20%20%20%20%20let%20largerY%20%3D%20Math.max(point1.y%2C%20point2.y)%3B%0D%0A%20%20%20%20%20%20%20%20let%20smallerY%20%3D%20Math.min(point1.y%2C%20point2.y)%3B%0D%0A%20%20%20%20%20%20%20%20let%20thirdX%20%3D%20(largerX%20-%20smallerX)%20%2F%203%3B%0D%0A%20%20%20%20%20%20%20%20let%20thirdY%20%3D%20(largerY%20-%20smallerY)%20%2F%203%3B%0D%0A%20%20%20%20%20%20%20%20let%20firstThird%20%3D%20%7Bx%3A%20smallerX%20%2B%20thirdX%2C%20y%3A%20smallerY%20%2B%20thirdY%7D%3B%0D%0A%20%20%20%20%20%20%20%20let%20secondThird%20%3D%20%7Bx%3A%20firstThird.x%20%2B%20thirdX%2C%20y%3A%20firstThird.y%20%2B%20thirdY%7D%3B%0D%0A%20%20%20%20%20%20%20%20return%20%7B%20first%3A%20firstThird%2C%20second%3A%20secondThird%20%7D%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Alet%20arr%20%3D%20new%20Float32Array(12)%3B%0D%0Avar%20%7B%20first%2C%20second%20%7D%20%3D%20ThirdPoints.between(%7Bx%3A%201%2C%20y%3A%202%7D%2C%20%7Bx%3A%201%2C%20y%3A%202%7D)%3B%0D%0Aarr%5B0%5D%20%3D%20first.x%3B%0D%0Aarr%5B1%5D%20%3D%20first.y%3B%0D%0Aarr%5B2%5D%20%3D%20second.x%3B%0D%0Aarr%5B3%5D%20%3D%20second.y%3B%0D%0Avar%20%7B%20first%2C%20second%20%7D%20%3D%20ThirdPoints.between(%7Bx%3A%201%2C%20y%3A%202%7D%2C%20%7Bx%3A%201%2C%20y%3A%202%7D)%3B%0D%0Aarr%5B6%5D%20%3D%20second.x%3B%0D%0Aarr%5B7%5D%20%3D%20second.y%3B%0D%0Aarr%5B8%5D%20%3D%20first.x%3B%0D%0Aarr%5B9%5D%20%3D%20first.y%3B

**Comment by DanielRosenwasser** [comment]
This is how ECMAScript is specified. You'll get the same issue if you re-declare a block-scoped variable as well. What you can do instead is write an object literal destructuring by wrapping the assignment in parentheses.

```ts
({ first, second } = ThirdPoints.between({ x: 1, y: 2 }, { x: 1, y: 2 }));
```

Alternatively, use `var` like you have if you really like the stylistic parallelism.

**Comment by typedefJorge** [comment]
Dang yeah the parentheses did the job. Thanks for getting back so quickly!! Dang just kinda lame that its considered a double declaration with destructuring... it would be super cool if the compiler could check if a block-scoped variable with that name already excisted in that scope and then just overwrite the contents.

**Comment by typedefJorge** [comment]
But i know you guys probably have to follow the es6 standard too. Itd probably cause confusion. Oh wells, guess thats what you get when your language isnt all about that performance/efficiency life lol
