### ISSUE TITLE
An index signature parameter type must be 'string' or 'number' - why not its's equivalent?

### ISSUE THREAD

**Issue by m1gu3l** [Microsoft/TypeScript#14934]
**TypeScript Version:**  2.2.1

**Code**

```ts
type LimitedFieldName = "name" | "email" | "phone";

interface ObjectWithLimitedField {
	[key: LimitedFieldName]: string;
}

// not ok

type AnyFieldName = string;

interface ObjectWithAnyField {
	[key: AnyFieldName]: string;
}

// not ok

interface ObjectWithStringField {
	[key: string]: string;
}

// ok
```

**Expected behavior:**
Index signature should allow types that evaluate to string or subset of string. The same for number.

**Actual behavior:**
Any literal other than **string** and **number** is explicitly disallowed.

**Comment by LOZORD** [comment]
For your first example, see [Mapped Types](https://www.typescriptlang.org/docs/handbook/advanced-types.html).

```ts
type Keys = 'option1' | 'option2';
type Flags = { [K in Keys]: boolean };
```

WRT using `string` type aliases as the index type for interfaces, etc., I believe this is being worked on, but I don't remember which issue is tracking it.

**Comment by RyanCavanaugh** [comment]
See #5683

**Comment by RyanCavanaugh** [comment]
Or #7374

**Comment by m1gu3l** [comment]
@LOZORD , thanks, I must have missed that.
@RyanCavanaugh, sorry, closing.
