### ISSUE TITLE
potential bug when transpiling to System.js

### ISSUE THREAD

**Issue by ORESoftware** [Microsoft/TypeScript#14939]
TypeScript Version:  2.2.1 

I have this tsconfig.json file:

```js
{
  "compilerOptions": {
    "outFile": "dist/suman.js",
    "declaration": true,
    "baseUrl": ".",
    "paths": {
    },
    "types": [
      "node",
      "async",
      "lodash"
    ],
    "typeRoots": [
      "node_modules/@types"
    ],
    "target": "es5",
    "module": "system",
    "moduleResolution": "node",
    "noImplicitAny": true,
    "removeComments": true,
    "allowUnreachableCode": true,
    "lib": [
      "es2015",
      "es2016",
      "es2017",
      "dom"
    ]
  },
  "allowJs": true,
  "compileOnSave": false,
  "include": [
    "./**/*.ts",
    "./**/*.js"
  ],
  "exclude": [
    "test",
    "node_modules",
    "dist"
  ]
}
```

a file called freeze-existing.ts, looks like:

```ts
'use strict';

export = function freezeExistingProps(obj: any) {

    try {
        Object.keys(obj).forEach(function (key) {
            Object.defineProperty(obj, key, {
                writable: false
            });
        });
    }

    catch(err){

    }

    return obj;

};
```

and it gets compiled to:

```js
System.register("freeze-existing", [], function (exports_1, context_1) {
    'use strict';
    var __moduleName = context_1 && context_1.id;
    return {
        setters: [],
        execute: function () {
        }
    };
});

```

Perhaps this is because Object.defineProperty is not available in the browser?

I would expect that the module would be basically transpiled verbatim but that's clearly not what happened.

**Comment by aluanhaddad** [comment]
> Perhaps this is because Object.defineProperty is not available in the browser?

`Object.defineProperty` most definitely is available in browsers.

Your code is invalid. The `system` format is not defined in terms of assignments to `module.exports` and does not provide any of `module`, `exports`, or `require`.

TypeScript throws an error on this code and the error is very specific:
> Export assignment is not supported when '--module' flag is 'system'.

Use 
```ts
export default function freezeExistingProps(obj: {}) { ... }
```
instead

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
