### ISSUE TITLE
this in methods not type of enclosing class

### ISSUE THREAD

**Issue by EricTetz** [Microsoft/TypeScript#14936]
**TypeScript Version:**  2.2.1

**Code**

```ts
function consumer(valueProducer: (this: void) => number) {
    console.log(valueProducer());
}

class Foo {
    private _value: number = 100;

    // this method requires `this: this` or `this: Foo` to provide type safety
    getValue(): number {
        return this._value;
    }

    constructor() {
        // callback does not have `this: void`, but Typescript can't warn me
        consumer(this.getValue);
    }
}
```

**Expected behavior:**

Class methods default to `this: this`.

**Actual behavior:**

Class methods default to `this: any`?

I'm not familiar with Git so I'm not good at distinguishing discussions vs actually implemented code, but [#6739](https://github.com/Microsoft/TypeScript/pull/6739) appears to address the problem directly and includes the line:

    "if --strictThis is specified, then functions will default this: void and methods will default this: this."

Which is exactly what I want. However, that page has an edit saying that the feature was "removed from this release". That was over a year ago. Was a fix reintroduced somewhere else? Catching this error seems like exactly the thing you'd want a type system for.

**Comment by aluanhaddad** [comment]
I am not sure what you mean, this works in the playground and the latest nightly, with all of the settings at their strictest.

http://www.typescriptlang.org/play/#src=function%20consumer(valueProducer%3A%20(this%3A%20void)%20%3D%3E%20number)%20%7B%0D%0A%20%20%20%20console.log(valueProducer())%3B%0D%0A%7D%0D%0Aclass%20Foo%20%7B%0D%0A%20%20%20%20private%20_value%3A%20number%20%3D%20100%3B%0D%0A%0D%0A%20%20%20%20%2F%2F%20this%20method%20requires%20%60this%3A%20this%60%20or%20%60this%3A%20Foo%60%20to%20provide%20type%20safety%0D%0A%20%20%20%20getValue()%3A%20number%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20this._value%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20constructor()%20%7B%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20callback%20does%20not%20have%20%60this%3A%20void%60%2C%20but%20Typescript%20can't%20warn%20me%0D%0A%20%20%20%20%20%20%20%20consumer(this.getValue)%3B%0D%0A%20%20%20%20%7D%0D%0A%7D

**Comment by RyanCavanaugh** [comment]
Unfortunately the perf cost of automatically putting the `this` type in class methods was extremely high (30% or worse degradation in all scenarios involving classes) and we weren't able to find a solution that had acceptable performance trade-offs.

**Comment by EricTetz** [comment]
> I am not sure what you mean, this works

aluanhaddad, if you instantiate foo, you'll log "undefined". 

Read the comments in the supplied example code, and the expected vs actual behavior.

I want typescript to recognize that the method passed to `consumer` will be called with the wrong `this`. I can achieve this by explicitly typing this in the method, e.g. (`getValue(this: this): number`), but that requires annotating every class method in my codebase with something Typescript seemingly should already know.  [#6739](https://github.com/Microsoft/TypeScript/pull/6739) addresses this directly, but it looks like the crucial part was pulled at the last minute. This was over a year ago, and there are other proposals about this issue referenced there. I am (was: Ryan answer the question) trying to figure out if this was ever actually addressed and how I can enable it.

>  we weren't able to find a solution that had acceptable performance trade-offs

Thank, Ryan. That's a bummer.

**Comment by aluanhaddad** [comment]
Sorry I misunderstood your post. Sorry for wasting your time.
