### ISSUE TITLE
URL encode parenthesis in playground

### ISSUE THREAD

**Issue by appsforartists** [microsoft/TypeScript#14943]
The Share button in the TypeScript Playground emits URLs like this:

http://www.typescriptlang.org/play/index.html#src=export%20type%20Point2D%20%3D%20%7B%0A%20%20x%3A%20number%2C%0A%20%20y%3A%20number%2C%0A%7D%3B%0A%0Atype%20Plucker%3CT%2C%20K%20extends%20keyof%20T%3E%20%3D%20(value%3A%20T)%20%3D%3E%20Pick%3CT%2C%20K%3E%3B%0Afunction%20createPlucker%3CT%2C%20K%20extends%20keyof%20T%3E(path%3A%20string)%3A%20Plucker%3CT%2C%20K%3E%20%7B%0A%20%20const%20pathSegments%20%3D%20path.split('.')%20as%20Array%3CK%3E%3B%0A%0A%20%20return%20function%20plucker(value%3A%20T)%3A%20Pick%3CT%2C%20K%3E%20%7B%0A%20%20%20%20let%20result%3A%20any%20%3D%20value%3B%0A%0A%20%20%20%20for%20(const%20pathSegment%20of%20pathSegments)%20%7B%0A%20%20%20%20%20%20result%20%3D%20result%5BpathSegment%5D%3B%0A%20%20%20%20%7D%0A%0A%20%20%20%20return%20result%20as%20Pick%3CT%2C%20K%3E%3B%0A%20%20%7D%3B%0A%7D%0A%0Aconst%20pluckX%20%3D%20createPlucker('x')%3B%0Aconst%20point%3A%20Point2D%20%3D%20%7B%0A%20%20x%3A%20100%2C%0A%20%20y%3A%20100%2C%0A%7D%3B%0A%0Aconst%20test%20%3D%20pluckX(point)%3B%0Atest.toFixed()%3B

which are incompatible with Markdown because the `()` characters are not serialized.  Please replace them with `%28` and `%29` so they can be used with Markdown.

**Comment by orta** [comment]
This is fixed in the new playground 👍
