### ISSUE TITLE
[Bug] Emitter prints TemplateExpression very wrong!

### ISSUE THREAD

**Issue by grandsong** [Microsoft/TypeScript#14948]
I found this bug when I parse some typescript code into AST (by `sf = ts.createSourceFile`  ) and then `ts.createPrinter().printFile(sf)` *back to typescript* (not js) code again.

# What's the Problem

You can reproduce this bug online with [npm runkit](https://runkit.com/npm/typescript).

Chrome is recommended.

Paste these code and click "Run".

	var ts =  require("typescript")
	var s = "let greeting = `Hi ${name}, how are you?`";
	var sf = ts.createSourceFile('', s, ts.ScriptTarget.ES2017, true);
	console.info(ts.createPrinter().printFile(sf));

The output is supposed to be the same as `s`. However, you will see:

	"let greeting = \"Hi \"name\", how are you?\";\n"

The printed ts code for the TemplateExpression AST node is completed messed up .

# Probably Helpful Info

I did my little investigation in typescript.js.

Finally, I reached the function `emitLiteral` where a TemplateHead node (such as that of "Hi ") is converted into a string `text = getLiteralTextOfNode(node)` with double quotes.

I am not sure what to edit to fix this bug. So I stopped and post this issue.

Hope someone kindly fix it.

**Comment by DanielRosenwasser** [comment]
Strangley, you don't see the same problem with `transpileModule`.

```
var ts =  require("typescript")
var s = "let greeting = `Hi ${name}, how are you?`";
console.info(ts.transpileModule(s, { compilerOptions: {target: ts.ScriptTarget.ES5}}).outputText);
```

**Comment by rbuckton** [comment]
I believe this is because the compiler options were not passed to the printer.
