### ISSUE TITLE
bug - TS seems to trace require/import statements but should use a different strategy

### ISSUE THREAD

**Issue by ORESoftware** [Microsoft/TypeScript#14941]
TypeScript Version: 2.2.1 

I have a project with a mixture of .js and .ts files. I want to create a bundle that can be used as a browser script, so would like to use --outFile option, and that's what I am doing :)

What's happening is that despite this in my tsconfig.json file:

```js
 "include": [
    "lib/**/*"
  ],
  "exclude": [
    "test",
    "node_modules",
    "dist"
  ]

```

...TS fails to include all the .js/.ts files in my lib directory. I think what's happening is that TS is tracing require/import statements, but some of my code uses fairly dynamic module resolution.

I am hoping there might be a compiler option to simply not use the require tracing strategy to find module, and simply transpile all modules in that match the globs in the include array.

**Expected behavior:**

Expect all files in my lib directory to be transpiled to dist/outfile.js

**Actual behavior:**

Only a fraction of the .js/.ts files in my lib directory get transpiled. My hypothesis is that tsc is using static analysis to determine which files to transpile, that won't work with my code as is.

Here is my complete tsconfig.json file for reference:

```js
{
  "compilerOptions": {
    "outFile": "dist/suman.js",
    "declaration": true,
    "baseUrl": ".",
    "paths": {
    },
    "types": [
      "node",
      "async",
      "lodash"
    ],
    "typeRoots": [
      "node_modules/@types"
    ],
    "target": "es5",
    "module": "system",
    "moduleResolution": "node",
    "noImplicitAny": true,
    "removeComments": true,
    "allowUnreachableCode": true,
    "lib": [
      "es2015",
      "es2016",
      "es2017",
      "dom"
    ]
  },
  "allowJs": true,
  "compileOnSave": false,
  "include": [
    "lib/**/*"
  ],
  "exclude": [
    "test",
    "node_modules",
    "dist"
  ]
}
```

**Comment by RyanCavanaugh** [comment]
A minimal repro is required.

**Comment by ORESoftware** [comment]
sure thing, will get that over in the next day or so

**Comment by RyanCavanaugh** [comment]
Right; from what you're describing this should be something you can demonstrate with three or four files (tsconfig, a js file, and two ts files?) with only a few lines of code each

**Comment by ORESoftware** [comment]
@RyanCavanaugh taking a step back, my goal is to create SystemJS deps that can be loaded in the browser. Do you happen to know if TypeScript is capable of bundling dependencies in node_modules and browserifying them into SystemJS deps? That's my assumption, but I am not sure. When I do include node_modules, tsc/node.js runs out of memory, but that's not the issue right now.

Here are a couple observations:

`tsc --project tsconfig-browser.json`

will not do anything if we use

```
  "include": [
    "**/*.js"
  ],

```

We get:

`error TS18003: No inputs were found in config file '/Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman/tsconfig-browser.json'. Specified 'include' paths were '["**/*.js"]' and 'exclude' paths were '["test","node_modules","dist"]'.
`

but it **should** do something, because we need to create an --outFile from all the (previously) transpiled .js files.

So that bug is:

`TSC should create an --outFile bundle from .js files even if there are no matching .ts files.`


anyway, moving on to the original issue:

One problem I see is that I am getting SystemJS modules that look like this:

```js
System.register("test-suite-methods/make-after", [], function (exports_7, context_7) {
    'use strict';
    var __moduleName = context_7 && context_7.id;
    function handleBadOptions(opts) {
        if (opts.plan !== undefined && !Number.isInteger(opts.plan)) {
            console.error(' => Suman usage error => "plan" option is not an integer.');
            process.exit(constants.EXIT_CODES.OPTS_PLAN_NOT_AN_INTEGER);
            return;
        }
    }
    var process, global, domain, util, pragmatik, async, colors, _suman, rules, constants, handleSetupComplete;
    return {
        setters: [],
        execute: function () {
            process = require('suman-browser-polyfills/modules/process');
            global = require('suman-browser-polyfills/modules/global');
            domain = require('domain');
            util = require('util');
            pragmatik = require('pragmatik');
            async = require('async');
            colors = require('colors/safe');
            _suman = global.__suman = (global.__suman || {});
            rules = require('../helpers/handle-varargs');
            constants = require('../../config/suman-constants');
            handleSetupComplete = require('../handle-setup-complete');
        }
    };
});
```

but the original code, looks like this:

```ts
'use strict';

//polyfills
const process = require('suman-browser-polyfills/modules/process');
const global = require('suman-browser-polyfills/modules/global');

//core
const domain = require('domain');
const util = require('util');

//npm
const pragmatik = require('pragmatik');
const async = require('async');
const colors = require('colors/safe');

//project
const _suman = global.__suman = (global.__suman || {});
const rules = require('../helpers/handle-varargs');
const constants = require('../../config/suman-constants');
const handleSetupComplete = require('../handle-setup-complete');


function handleBadOptions(opts: IAfterOpts): void {

    if (opts.plan !== undefined && !Number.isInteger(opts.plan)) {
        console.error(' => Suman usage error => "plan" option is not an integer.');
        process.exit(constants.EXIT_CODES.OPTS_PLAN_NOT_AN_INTEGER);
        return;
    }
}

export = function (suman: ISuman, zuite: ITestSuite): Function {

    return function ($desc: string, $opts: IAfterOpts, $fn: Function): ITestSuite {

        handleSetupComplete(zuite);

        const args: Array<any> = pragmatik.parse(arguments, rules.hookSignature, {
            preParsed: typeof $opts === 'object' ? $opts.__preParsed : null
        });

        const [desc, opts, fn] = args;
        handleBadOptions(opts);

        if (opts.skip) {
            suman.numHooksSkipped++;
        }
        else if (!fn) {
            suman.numHooksStubbed++;
        }
        else {
            zuite.getAfters().push({
                ctx: zuite,
                timeout: opts.timeout || 11000,
                desc: desc || (fn ? fn.name : '(unknown due to stubbed function)'),
                cb: opts.cb || false,
                throws: opts.throws,
                planCountExpected: opts.plan,
                fatal: !(opts.fatal === false),
                fn: fn,
                type: 'after/teardown',
                warningErr: new Error('SUMAN_TEMP_WARNING_ERROR')
            });
        }

        return zuite;

    };
};
```

My project has probably 100 files, but only 12 System.register calls appear in the --outFile bundle, so something is wrong.

**Comment by ORESoftware** [comment]
@RyanCavanaugh thanks, the above is also re-iterated in the readme file in this example project:

https://github.com/ORESoftware/tsc-systemjs-example

I created that project as a repro, please let me know what you think, would like to get to the bottom of this, thanks!

**Comment by ORESoftware** [comment]
It definitely seems to me that given the tsconfig in the above project (see link), that TSC will only include .ts file as part of the build. That's a shame, I wish it could include JS files too.

**Comment by ORESoftware** [comment]
Any word on this bird? thanks @RyanCavanaugh

**Comment by mhegazy** [comment]
>  Do you happen to know if TypeScript is capable of bundling dependencies in node_modules and browserifying them into SystemJS deps? 

This is not something the TS compiler supports.

**Comment by ORESoftware** [comment]
@mhegazy yeah, bummer

**Comment by mhegazy** [comment]
For both issues `"allowJs": true` should be inside your `"compilerOptions"` not outside it. this is why the value is ignored.

For the second issue, a file is a module iff it has a top-level `import` or `export`. `const s = require("..\s");` does not meet this requirement, so these files are transpiled as is.

The issue seems to me here is that you want to use the typescript compiler as a bundler, a la webpack or browserify. The TS compiler is not designed to do this. TSC supports a limited form of bundling with the --outFile, but this is not meant to be a general purpose bundling tool.

I would recommend emitting your files whether .js or .ts separately, and then using a bundler like webpack or browserify to bundle them.

**Comment by mhegazy** [comment]
This issue seems to have been already addressed or is unactionable at the moment. I am auto-closing it for now.
