### ISSUE TITLE
is there a way to guarantee that all properties of an interface are addressed

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#14947]
say i have an interface
```typescript
    interface Data { one: number; another: string; }
```
i have a serialization method
```typescript
    serialize(data: Data): string {
        return 'one: ' + data.one + ', another: ' + data.another;
    }
```
now i am doing refactoring and want to add a new property to the `Data` interface, so that
```typescript
    interface Data { one: number, another: string, yetAnother: boolean }
```
now by requirement the new property `yetAnother` must be serialized too, yet the compiler won't point out to that because i didn't ask for it, so there is a chance of a bug to slip in

**now my question**: is there a way to ask the TypeScript compiler if i addressed all properties of an interface?

crossposted to StackOverflow:  http://stackoverflow.com/questions/43140675/is-there-a-way-to-guarantee-that-all-properties-of-an-interface-are-addressed

**Comment by cevek** [comment]
Would be nice see that also with switch enums:
```ts
const enum Foo {
   A, B, C
}
switch (x) {
  case A: return 1;
  case B: return 1;
  // C missed
}
```

**Comment by RyanCavanaugh** [comment]
@cevek see http://stackoverflow.com/questions/39419170/how-do-i-check-that-a-switch-block-is-exhaustive-in-typescript

**Comment by RyanCavanaugh** [comment]
@aleksey-bykov here's a fairly odd solution you may or may not like
```ts
interface Data { one: number; another: string; theNewOne: Date }

function assertNever(x: never) {
    throw new Error(`Oops! Forgot about ${x}`);
}

function serialize(data: Data) {
    var keys = Object.keys(data) as Array<keyof Data>;
    const parts: string[] = [];
    for (const k of keys) {
        switch (k) {
            case 'one':
                parts.push('uno: ', data.one.toString());
                break;
            case 'another':
                parts.push('another: ', data.another);
                break;
            case 'mispeld': // Error
                break;
            default:
                assertNever(k); //  Error, can't convert theNewOne to never               
        }
    }
    return parts.join('');
} 
```

**Comment by aleksey-bykov** [comment]
i like it, thanks

**Comment by aleksey-bykov** [comment]
inspired by @RyanCavanaugh, i ended up with some extremely elegant little function:
```
export type Around<T extends object, R> = { [P in keyof T]: (result: R, name: P, value: T[P]) => R; }
export function around<T extends object, R>(data: T, result: R, around: Around<T, R>): R {
    for (const name in data) {
        result = around[name](result, name, data[name]);
    }
    return result;
}
```
problem solved

**Comment by cevek** [comment]
@aleksey-bykov How to use this function?

**Comment by aleksey-bykov** [comment]
check my latest update to the initial post in this topic, there is an example there
