### ISSUE TITLE
New Website Logo: Templafy

### ISSUE THREAD

**Issue by konstanto** [Microsoft/TypeScript#14949]
- Name: Templafy
- Homepage url: http://templafy.com
- Brand Guidelines/Licensing: Should be used on light background.
- Logo: https://d3vv6lp55qjaqc.cloudfront.net/items/3E183O3f1A0y3i3w3F12/Templafy.svg?X-CloudApp-Visitor-Id=870059

**Comment by mhegazy** [comment]
looks like the https is not working, http://templafy.com is though.

**Comment by konstanto** [comment]
@mhegazy Thank you - I have edited it!
