### ISSUE TITLE
Throw error when use class Decorator in react Component

### ISSUE THREAD

**Issue by infeng** [Microsoft/TypeScript#14942]
**TypeScript Version:**  2.2.2

**Code**

```tsx
import * as React from 'react';
import * as ReactDOM from 'react-dom';
import { Form } from 'antd';

// Form type
// export interface FormComponentProps {
//     form: WrappedFormUtils;
// }
// export interface ComponentDecorator<TOwnProps> {
//     (component: React.ComponentClass<FormComponentProps & TOwnProps>): React.ComponentClass<TOwnProps>;
// }
// Form.create: <TOwnProps>(options?: FormCreateOption | undefined) => ComponentDecorator<TOwnProps>; 

interface TestFormOwnProps {
  name: string;
}

interface TestFormProps extends TestFormOwnProps {
  form?: any;
}

@Form.create<TestFormOwnProps>()
class TestForm extends React.Component<TestFormProps, any> {
  render() {
    const { form } = this.props;
    console.log('form', form);

    return (
      <Form>
        <input />
      </Form>
    );
  }
}

ReactDOM.render(
  <TestForm
    name="233"
  />,
  document.getElementById('root')
);
```

**Expected behavior:**
no error

**Actual behavior:**
`@Form.create<TestFormOwnProps>()` throw error:

'Argument of type 'typeof TestForm' is not assignable to parameter of type 'ComponentClass<FormComponentProps & TestFormOwnProps>'.
  Type 'TestForm' is not assignable to type 'Component<FormComponentProps & TestFormOwnProps, ComponentState>'.
    Types of property 'props' are incompatible.
      Type '{ children?: ReactNode; } & TestFormProps' is not assignable to type '{ children?: ReactNode; } & FormComponentProps & TestFormOwnProps'.
        Type '{ children?: ReactNode; } & TestFormProps' is not assignable to type 'FormComponentProps'.
          Property 'form' is optional in type '{ children?: ReactNode; } & TestFormProps' but required in type 'FormComponentProps'.'

**Comment by aluanhaddad** [comment]
Your class does not meet the requirements specified by the decorator. See https://github.com/ant-design/ant-design/blob/master/components/form/Form.tsx#L88, `form` is required.

**Comment by infeng** [comment]
```javascript
interface TestFormProps extends TestFormOwnProps {
  form: any;
}
```
Although I change `form` required, @Form.create<TestFormOwnProps>() still throw error.

'Unable to resolve signature of class decorator when called as an expression.
  Type 'ComponentClass<TestFormOwnProps>' is not assignable to type 'typeof TestForm'.
    Type 'Component<TestFormOwnProps, ComponentState>' is not assignable to type 'TestForm'.
      Types of property 'props' are incompatible.
        Type '{ children?: ReactNode; } & TestFormOwnProps' is not assignable to type '{ children?: ReactNode; } & TestFormProps'.
          Type '{ children?: ReactNode; } & TestFormOwnProps' is not assignable to type 'TestFormProps'.
            Property 'form' is missing in type '{ children?: ReactNode; } & TestFormOwnProps'.'

**Comment by infeng** [comment]
If the `TestForm` has been decorated by `Form.create` then it has this.props.form property. When I use TestForm, I should not pass `form` property, so I define `@Form.create<TestFormOwnProps>()` type is `React.ComponentClass<TOwnProps>`, unfortunately, it throw error.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
