### ISSUE TITLE
Issue implementing interface

### ISSUE THREAD

**Issue by testerez** [Microsoft/TypeScript#14954]
**TypeScript Version:**  2.2.2

**Code**

```ts
interface I {
  foo: 'foo' | 'bar';
}

interface IClass {
  i: I;
}

class C implements IClass {
  i = { foo: 'foo' };
}

```

**Expected behavior:**
no error

**Actual behavior:**
> Class 'C' incorrectly implements interface 'IClass'.
  Types of property 'i' are incompatible.
    Type '{ foo: string; }' is not assignable to type 'I'.
      Types of property 'foo' are incompatible.
        Type 'string' is not assignable to type '"foo" | "bar"'.

**Comment by andy-ms** [comment]
The type of 'foo' will be widened to `string` in this case. You can fix this by adding a type annotation: `i: I = { foo: 'foo' };`.

**Comment by vkurchatkin** [comment]
Typescript is unable to infer literal types, unless it is a constant. For example:

```ts
let x = 1;
const y: 1 = x; // error, but shouldn't be
```

```ts
const x = 1;
const y: 1 = x; // no error
```

```ts
const x = { foo: 'bar' };
const y: { foo: 'bar' } = x; // error, but shouldn't be
```

```ts
const x: { foo: 'bar' } = { foo: 'bar' };
const y: { foo: 'bar' } = x; // no error
```

**Comment by testerez** [comment]
@andy-ms yes I did something similar: ` i = { foo: 'foo' } as I;`
But It seams like typescript could do better here...

@vkurchatkin in your third example, `x` is constant but not `x.foo`...

**Comment by vkurchatkin** [comment]
@testerez right, you can't make property a constant in TypeScript. Still, this shouldn't be an error.

**Comment by RyanCavanaugh** [comment]
Duplicate #7011 - if the initializer were contextually typed this would work as expected
