### ISSUE TITLE
Type guards don't work on key/value objects

### ISSUE THREAD

**Issue by diestrin** [microsoft/TypeScript#14957]
**TypeScript Version:**  2.2.2 with `--strictNullChecks`

**Code**

```ts
let test: string;

const obj1: {val: string|number} = {val: ''};
if (typeof obj1.val === 'string') {
  test = obj1.val; // => Works fine
}

const obj2: {[k: string]: string|number} = {val: ''};
if (typeof obj2.val === 'string') {
  test = obj2.val; // => Type 'string | number' is not assignable to type 'string'
}
```

**Expected behavior:**
Type guards to work on key/value objects

**Actual behavior:**
Can't infer the correct type after check

**Comment by RyanCavanaugh** [comment]
Interesting. This will likely require some architectural changes as we currently have no symbol to associate with the `.val` property access and thus nothing to narrow by.

**Comment by RyanCavanaugh** [comment]
This works now
