### ISSUE TITLE
'declared but never used' for type parameter when there is a broken import

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#14953]
**TypeScript Version:**  nightly (2.3.0-dev.20170331)

**Code**

```ts
import { Foo } from "bad-import";

export interface I<T> {
    x: Foo<T>;
}
```

**Expected behavior:**

Only an error at the import.

**Actual behavior:**

`src/a.ts(3,20): error TS6133: 'T' is declared but never used.`

**Comment by andy-ms** [comment]
Another case:

```ts
import { foo } from "badImport";

type T = number;
foo<T>();
```

**Comment by andy-ms** [comment]
Another case:
```ts
import { A, B } from "unknown";
export class C extends A<B> {}
```
`B` is marked unused.

**Comment by kevynb** [comment]
Hello, it seems to be fixed on typescript@next. However since this issue can affect users of Typescript v2.2.2 and v2.3 and tslint, would it be possible to ship it in typescript@2.3.3 instead of 2.4?

**Comment by Chris2011** [comment]
I have a similar problem: ```ERROR in ng:///C:/Projekte/groupify/src/app/export/export.component.html (2,1): '$event' is declared but never used.```

But the code inside my export.component.html looks like: ````<button (click)="export()">Export</button>````

**Comment by Chris2011** [comment]
And yes, the error go away after I set noUnusedParameters to false.

**Comment by andy-ms** [comment]
@Chris2011 I can't really help you without a reproducible code sample. Can you find-all-references on `$event` to see if you have any uses?

**Comment by Chris2011** [comment]
I did a full text search. I will have a look later to see where it comes from. I thought it could be the same error here, thats why I jumped in.

**Comment by jaredpalmer** [comment]
Not sure if this helps anyone, but I solved this "bug" by removing an incorrect spread props `{...this.props}` in a parent react component.

**Comment by juanpablodelatorre** [comment]
I'm getting a lot of these in a piece of code that was working fine a couple of days ago. They seem a bit random. One that caught my eye (because it happens again and again in different files) says:

```
[16:12:52]  tslint: src/pages/detail.ts, line: 4
                  All imports are unused.
       L4:  import { Http } from "@angular/http";
```

And the relevant code is:
```typescript
import { Http } from "@angular/http";
export class detail {
    constructor(private http: Http) {}

    pushData(url, payload) {
        this.http.post(url, payload).map(res => res.json()).subscribe(data => console.log(data));
    }
}
```

Also, this one:
```
'ErrorHandler' is declared but never used.
```

```typescript
import { ErrorHandler } from "@angular/core";
export class MyErrorHandler implements ErrorHandler {
}
```

I don't know why TSLint started picking these as errors. But it sure started today.

**Comment by juanpablodelatorre** [comment]
@andy-ms Yep, that worked. Thanks!
