### ISSUE TITLE
Upgrade Playground to 2.2

### ISSUE THREAD

**Issue by appsforartists** [Microsoft/TypeScript#14958]
The Playground doesn't understand `object` or the Mixin pattern.  I suspect it is not running 2.2:

http://www.typescriptlang.org/play/index.html#src=type%20Constructor%3CT%3E%20%3D%20new(...args%3A%20any%5B%5D)%20%3D%3E%20T%3B%0A%0Aclass%20A%20extends%20Timed(C)%20%7B%0A%0A%7D%0A%0Afunction%20Timed%3CT%20extends%20Constructor%3Cobject%3E%3E(superclass%3A%20T)%20%7B%0A%20%20return%20class%20Timed%20extends%20superclass%20%7B%0A%20%20%20%20startTime%3A%20number%3B%0A%20%20%20%20endTime%3A%20number%3B%0A%20%20%20%20get%20duration()%3A%20number%20%7B%20...%20%7D%0A%20%20%7D%3B%0A%7D%0A%0Aclass%20C%20%7B%20%7D

**Comment by aaronbeall** [comment]
It would also be helpful if the compiler version was stated somewhere on the page (I've often wondered what version I'm playing with compared to the version in my project), or even better if you could select compiler version from a list.

**Comment by mhegazy** [comment]
updated. having different versions is tracked by https://github.com/Microsoft/TypeScript/issues/15662
