### ISSUE TITLE
variable incorrectly typed when set inside a closure

### ISSUE THREAD

**Issue by tjhance** [Microsoft/TypeScript#14961]
**TypeScript Version:**  2.2.2

```
class A {
  foo() { }
}

let a: A | null = null;

function setA() {
  a = new A();
}

setA();

if (a) {
  a.foo();
}
```

**Expected behavior:**

I expect this to compile with no errors.

**Actual behavior:**

TypeScript does not realize it is possible for `a` to be of type `A` at the `a.foo()` call. It gives the following error:

`test.ts(14,5): error TS2339: Property 'foo' does not exist on type 'never'.`

**Comment by RyanCavanaugh** [comment]
#9998
