### ISSUE TITLE
Bug (or documentation oversight): Mapped type with multiple definitions throws many syntax errors

### ISSUE THREAD

**Issue by dallonf** [Microsoft/TypeScript#14969]
**TypeScript Version:**  2.2.2

**Code**

```ts
interface Person {
  name: string;
  nickname: string;
}
type ModifiedPerson = {
  [P in keyof Person]: Person[P];
  // Adding a property
  age: number;
  // Overriding a property to make it optional
  nickname?: string
}
```

**Expected behavior:**
I would expect `ModifiedPerson` to be equivalent to:
```
type ModifiedPerson = {
  name: string;
  age: number;
  nickname?: string
}
```

**Actual behavior:**
Syntax errors:
```
type ModifiedPerson = {
  [P in keyof Person]: Person[P];
  age: number;  // '}' expected; unexpected label; cannot find name 'number'
  nickname?: string // Cannot find name 'nickname'; Expression expected; cannot find name 'string'
}
```

It seems like it's invalid syntax to add more than one property definition to a mapped type? If that's by design, then I suppose this is just a documentation issue; the documentation for mapped types doesn't mention this limitation. (Maybe I'm just the first person stupid enough to try! 😆 )

Also, if this is by design, would someone be kind enough to point me in the right direction regarding this sort of dynamic type modification?

**Comment by aluanhaddad** [comment]
@dallonf The reason for this is that the mapped type is not a member it is a type.
In other words, 
```ts
[P in keyof Person]: Person[P]
```
is not a valid member declaration, but
```ts
{
  [P in keyof Person]: Person[P];
  // Adding a property
  age: number;
  // Overriding a property to make it optional
  nickname?: string
}
```
_is_ a valid type.

You can get the desired declaration (for the most part) by writing
```ts
interface Person {
    name: string;
    nickname: string;
}
type ModifiedPerson = { [P in keyof Person]: Person[P] } & {
  age: number,
  nickname?: string
};
```
although the behavior of `nickname` is not quite what you may expect.

**Comment by dallonf** [comment]
Ah, I see. Would you accept a docs PR to clarify this? Probably in the Advanced Types -> Mapped Types section.

**Comment by aluanhaddad** [comment]
We would need to ask a team member such as @DanielRosenwasser

**Comment by DanielRosenwasser** [comment]
This issue was moved to Microsoft/TypeScript-Handbook#540
