### ISSUE TITLE
Cannot seem to exclude own linked package from being compiled

### ISSUE THREAD

**Issue by Anupheaus** [Microsoft/TypeScript#14968]
**TypeScript Version:**  2.2.1

**Setup**
Directory structure:
```
Project
 |- Server
 |- Client
 |- Common
 `- Database
```

In each of the above folders I have a `tsconfig.json` file, each with various different options depending on the requirements, but the server project for example, depends on the client and common packages, which are `npm link`ed into the server package.  However, despite excluding `node_modules`, and trying various other additional excludes, I cannot, for the life of me, prevent `tsc` parsing all the files within the client and common projects.  Is this by design?  Is it because the server project needs to know what is in the client and common projects?  Is it recompiling them or just looking at them?  If I can something in the other projects I noticed that the watch on the server project also seems to be compiling it.  I really don't think it should do that.  It is listing the problems in other projects as well.

**tsconfig.json**

```json
{
    "compilerOptions": {
        "experimentalDecorators": true,
        "jsx": "react",
        "module": "commonjs",
        "lib": [
            "es2016",
            "dom"
        ],
        "target": "es2015",
        "noImplicitAny": false,
        "sourceMap": true,
        "watch": true
    },
    "compileOnSave": true,
    "exclude": [
        "Client",
        "Common",
        "node_modules",
        "src/views"
    ]
}
```

I have tried the following options for the exclude path and none seem to make a difference:
`Client`
`Client/**/*.ts`
`<path from C:\>\\Client`
`<path from C:\>\\Client\**.*ts`
`../Client`
`../Client/**/*.ts`

**Expected behavior:**
Only the files within the project should be watched (or at least compiled when a change occurs) and only errors within the current project should be described.

**Actual behavior:**
All files within the project or are linked are being watched and compiled on a change.  It is also displaying errors for all linked projects.

**Comment by mhegazy** [comment]
https://github.com/Microsoft/TypeScript/wiki/FAQ#why-is-a-file-in-the-exclude-list-still-picked-up-by-the-compiler?

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
