### ISSUE TITLE
Infer implementation signature based on overload signatures

### ISSUE THREAD

**Issue by vilic** [Microsoft/TypeScript#14972]
Probably a duplicate, but I cannot find one.

```ts
function foo(p1: string): void;
function foo(p1: number, p2: boolean): void;
function foo(p1, p2) {
    // p1: string | number;
    // p2: boolean | undefined;
}
```

If there could be constraints among parameters via type guards, it would be awesome.

**Comment by aluanhaddad** [comment]
See also #10570, #6118

**Comment by RyanCavanaugh** [comment]
#7763

Just literally search for the title?
![image](https://cloud.githubusercontent.com/assets/6685088/24622590/67715508-185a-11e7-80eb-d080a88e15c4.png)

**Comment by vilic** [comment]
@RyanCavanaugh huh, I tried many combinations but not the title... Thanks for doing that for me, closing.
