### ISSUE TITLE
type assertion in switch expression prevents from narrowing

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#14974]
```typescript
export function otherwise<R>(_: never, result: R): R {
    return result;
}
export type S = 'a' | 'b';
export function isS(value: string): value is S {
    switch (<S>value) {
        case 'a': case 'b': return true;
        default: return otherwise(value, false); // <-- value is not narrowed, expected never, actual string
    }
}
```

the following works though

```typescript
export function isS(value: string): value is S {
    const casted = <S>value;
    switch (casted) {
        case 'a': case 'b': return true;
        default: return otherwise(casted, false); // <-- never as expected
    }
}

```

**Comment by aluanhaddad** [comment]
It seems like that should work. It works with `let cast = <S>value` also, so its not a mutability thing.

On another note, that snippet seems like part of a quite elegant looking little pattern matching library or perhaps a convention 👍

**Comment by aleksey-bykov** [comment]
thanks for kind words, help yourself: https://github.com/aleksey-bykov/basic
speaking of elegance, this is one of all time brightest thing i came across: https://github.com/Microsoft/TypeScript/issues/14947

**Comment by RyanCavanaugh** [comment]
I think we just need to unwrap assertions for tracking the control flow

**Comment by ahejlsberg** [comment]
We only do control flow based type analysis on expressions that are simple names or dotted names, so the behavior above is as designed. I suppose we could special case type assertions of simple or dotted names, but I'm not sure by what principle we would pick that and not other expressions.
