### ISSUE TITLE
🤡 support for es2018

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#14970]
ES2018 has almost made it to an official standard, what is the timeline for adopting upcoming features?

https://www.youtube.com/watch?v=s-G_RZ4RJLU

**Comment by mchambaud** [comment]
It's now a standard.

**Comment by kitsonk** [comment]
> It's now a standard.

Wrong year.

**Comment by RyanCavanaugh** [comment]
Revisit once the spec for ES20NaN is final

**Comment by aleksey-bykov** [comment]
you forgot the revisit tag

**Comment by mariusschulz** [comment]
… and here we go, ES2018 is an official standard! :tada:

**Comment by mhegazy** [comment]
https://github.com/Microsoft/TypeScript/issues/20463 tracks this now.
