### ISSUE TITLE
【BUG】"await" should be a type error other than "Promise"

### ISSUE THREAD

**Issue by kgtkr** [Microsoft/TypeScript#14976]
**BUG**

**TypeScript Version:2.1.6**

**Code**
```ts
//example
(async()=>{
  await 1;
  await "";
  await new Date();
  await [];
  await null;
  await undefined;
})();
```

**Expected behavior:Type error**

**Actual behavior:Successful compilation**

**Comment by aluanhaddad** [comment]
But that is OK. See the behavior of `await` as documented
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await
Specifically MDN states that:
> If the value is not a Promise, it converts the value to a resolved Promise, and waits for it.

**Comment by andy-ms** [comment]
Tslint has a rule for this. https://palantir.github.io/tslint/rules/await-promise/

**Comment by aluanhaddad** [comment]
Thank you. I am going to go turn that on.

**Comment by RyanCavanaugh** [comment]
Previously discussed at #8310 and #9921

**Comment by kgtkr** [comment]
I understand
thank you
