### ISSUE TITLE
TSConfig to support glob typeRoots

### ISSUE THREAD

**Issue by maraisr** [Microsoft/TypeScript#14979]
So I have my typescript config file coming from a sub-module, and various of other internal packages being git submoduled in, each supplying its own types.

Without specifying each one of them explicitly, is there a possibility to go something like this:

My reason for this is - we have 4 teams sub moulding in what package they want (rather than use NPM, don't ask...), and would hate for the developer to have to add the line of config into the json file considering it comes from another sub-module.

```json
{
    "compilerOptions": {
        "typeRoots": [
            "lib/**/node_modules/@types/"
        ]
    }
}
```

rather than going:

```json
{
    "compilerOptions": {
        "typeRoots": [
            "lib/core/node_modules/@types/",
            "lib/tools/node_modules/@types/"
            "lib/utils/mock/node_modules/@types/",
            "lib/utils/query/node_modules/@types/"
        ]
    }
}
```

I get that maybe there might be some overlap in type def's but maybe do something cute whereby it'll pick the first def it finds, and ignore the rest?

**Comment by aluanhaddad** [comment]
Its best to be explicit about this kind of thing. In my opinion the compiler is already far too eager to traverse an entire disk drive (following the very bad example set by the NodeJS `require` algorithm) to pull in anything with a name that matches, ignoring versions and manifests.
If you use any of the same dependencies as these teams, for example if you use _moment.js_ or _core-js_, and even more so if you are using different package managers (nothing wrong with that by the 😛), there is a high probability of version conflicts and duplicated type declarations.

**Comment by maraisr** [comment]
@aluanhaddad really its convention over configuration.

I'm not asking this to be supported natively, more so if there was a way to get it done.

**Comment by mhegazy** [comment]
typeRoots is rather an advanced feature. that and the limited number of these folder, suggest that this can be left to humans to figure out, and does not need to be done by the compiler.

**Comment by maraisr** [comment]
Fair enough @mhegazy appreciate you having taken the time. Once again love your work, and the rest of the TypeScript's team! :heart:

**Comment by mhegazy** [comment]
thanks!
