### ISSUE TITLE
Async getter won't compile : 'async' modifier cannot be used here

### ISSUE THREAD

**Issue by xnnkmd** [Microsoft/TypeScript#14982]
**TypeScript Version:**  2.2.1

**Code**

```ts

class GetterExample {
 // Async method works:
  async ftest(): Promise<number> {
    return Promise.reject(52);
  }
  // Async getter gives error: ''async' modifier cannot be used here.'
  async get gtest(): Promise<number> {
    return Promise.reject(52);
  }
}

```

**Expected behavior:**
I would expect TS to allow an async getter method to be declared.

**Actual behavior:**
TS gives errror:  ''async' modifier cannot be used here.'

**Comment by cevek** [comment]
async modifier cannot be used with getters.

**Comment by antanas-arvasevicius** [comment]
Currently we need to write getters like this:
```typescript
    export class A {
        static get title() {
            return (async () => await someOp())();
        }
    }
```

instead of just:
```typescript
    export class A {
        static async get title() {
            return await someOp();
        }
    }
```
Are there any technical reasons to not allow "async" within getters?

**Comment by cevek** [comment]
Because getter call is like plain object property usage
```ts
A.title.substr();
```

If you want to do some async action just return a promise:
```ts
    export class A {
        static get title() {
            return someAsyncOp();
        }
    }
(await A.title).substr()
```

**Comment by akdor1154** [comment]
I would expect `async` getters to work as the following:
```ts
class A {
  constructor(id) { this.id = id; }
  async get title() {
    const dbObj = await db.getObject(this.id);
    return dbObj.title;
  }
}

const a = new A(42);
(await A.title).substr();
```

Is there any reason why this should not be the case?

**Comment by kitsonk** [comment]
async getters (and setters) are not part of the final ES proposal.  The reasons why are discussed [here](https://github.com/tc39/ecmascript-asyncawait/issues/15).  It therefore doesn't make sense for TypeScript to implement something that isn't part of the standard.  The slightly odd work around mentioned [above](#issuecomment-294437284) seems to be the way to do it.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
