### ISSUE TITLE
Compiler does not error when passing a `(Interface[])=>void` parameter to a function that wants a `(Interface)=>void`.

### ISSUE THREAD

**Issue by MicahZoltu** [Microsoft/TypeScript#14993]
**TypeScript Version:**  2.2.1

**Code**

```ts
interface Interface {
	cherry?: string;
}
function apple(consumer: (apple: Interface[]) => void) {
	banana(consumer);
}
function banana(consumer: (apple: Interface) => void) { }
```

**Expected behavior:**
Expect a compiler error because I'm passing a function `(Interface[]) => void` as a parameter to a function that wants a `(Interface) => void`

**Actual behavior:**
The compiler seems totally fine with the situation.

**Notes:** The problem does not occur if `string` is used as the type instead of `Interface`.

**Comment by RyanCavanaugh** [comment]
https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-all-types-assignable-to-empty-interfaces

**Comment by MicahZoltu** [comment]
I updated the example with a non-empty interface, though I suspect the fact that the property is nullable results in the same answer?

**Comment by MicahZoltu** [comment]
This is with `--strictNullChecks` enabled, I'm not sure if the same behavior would occur without?

**Comment by RyanCavanaugh** [comment]
All-optional is basically the same as empty. See also https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-function-parameters-bivariant

**Comment by MicahZoltu** [comment]
OK.  Thanks for the links.  While the situation is unfortunate, I recognize that resolving it is probably way out of scope for any near-term TypeScript updates, so feel free to close.
