### ISSUE TITLE
No warning/errors about unreachable code when using the instanceof operator

### ISSUE THREAD

**Issue by olamothe** [Microsoft/TypeScript#15004]
**TypeScript Version:**  2.2.2

**Code**

```ts
class Foo {
}

class Bar { 
}

const doOtherStuff = () => {
  console.log('Hello');
}

const test = new Foo()


  // Here, there is no warning or compilation error that doOtherStuff() is unreachable
if (test instanceof Bar) { 
  doOtherStuff();
}

```

**Expected behavior:**

A compilation error, or a warning of some sort about unreachable or suspicious code.

**Actual behavior:**

Compiles successfully, with no warning.

**Comment by mhegazy** [comment]
The compiler does nto flag cases like so, since types are structural in nature, and are technically open.
