### ISSUE TITLE
WriteFileCallback: sourceFiles is optional

### ISSUE THREAD

**Issue by ivogabe** [Microsoft/TypeScript#15007]
`WriteFileCallback` is defined as follows:

```typescript
export interface WriteFileCallback {
    (fileName: string, data: string, writeByteOrderMark: boolean, onError?: (message: string) => void, sourceFiles?: SourceFile[]): void;
}
```
I was wondering why `sourceFiles` marked as optional. As of version 3.6, we're using this in gulp-typescript. This works fine, but ivogabe/gulp-typescript#499 describes that `sourceFiles` is `undefined` in some special case. So, when is `sourceFiles` `undefined`, and is there some way to force it being set?

**Comment by ivogabe** [comment]
@vladima Any ideas?

**Comment by mhegazy** [comment]
That is a bug int he declaration, soruceFiles should always be passed, it can be a single file or all files in the program.

**Comment by DickvdBrink** [comment]
@mhegazy, this is a bit difficult to change because `onError` is also optional. So making to make sourceFiles mandatory it is necessary to change the order of the parameters which is a bit difficult in a public API

**Comment by ivogabe** [comment]
Why is `onError` optional? It could also be marked as `| undefined` instead, or is this parameter also always provided and not optional?
