### ISSUE TITLE
Constructor emit is not correct for truly primitives returning by super

### ISSUE THREAD

**Issue by cevek** [microsoft/TypeScript#15003]
**TypeScript Version:**  2.3.0-dev.20170321

```ts
class A {
    constructor() {
        return 1;
    }
}
class B extends A{
    foo: number;
    constructor() {
        super();
        this.foo = 1;
    }
}
```

The output is: 
```js
    function B() {
        var _this = _super.call(this) || this; // Not quite correctly
        _this.foo = 1;
        return _this;
    }
```
Because boolean, number and string truly primitives is fit for that condition and `_this` will be not an object.

Fix: 
```js
var _sup = _super.call(this);
var _this = typeof _sup === 'object' && _sup !== null ? _sup : this;
```
Or some helper:
```js
function _sup(val, _this) {
      return typeof val === 'object' && val !== null ? val : _this;
}

 function B() {
         var _this = _sup(_super.call(this), this);
        _this.foo = 1;
        return _this;
    }
```
Also [explicitly condition check for null or undefined](https://pbs.twimg.com/media/C7oOFqIXQAArioG.jpg) in new TurboFan v8 engine works faster.

**Comment by aluanhaddad** [comment]
It would probably be better if `A` were just an error.

**Comment by cevek** [comment]
@aluanhaddad In chrome it works nicely. I think it possible by the spec

**Comment by aluanhaddad** [comment]
Yeah but so is
```ts
class { } + class { }
```

**Comment by RyanCavanaugh** [comment]
This doesn't seem to happen in practice and we'd have to complicate our emit quite a bit to get it "right"
