### ISSUE TITLE
Unintuitive behavior for `isIdentifier`

### ISSUE THREAD

**Issue by andy-ms** [microsoft/TypeScript#15008]
**TypeScript Version:**  nightly (2.3.0-dev.20170404)

**Code**

```ts
function f() {
    interface I {
        [yield: string]: boolean;
    }
}

function* g() {
    interface I {
        [yield: string]: boolean;
    }
}
```

**Expected behavior:**

No errors.

**Actual behavior:**

```ts
src/a.ts(9,15): error TS1005: ']' expected.
src/a.ts(9,23): error TS1005: ';' expected.
src/a.ts(9,24): error TS1131: Property or signature expected.
```

We use `isIdentifier` in a few places where it doesn't really make sense to care whether we're in a yield context or not.

**Comment by RyanCavanaugh** [comment]
Isn't this just about the parser calling `parseIdentifier` when it should call `parseIdentifierName` ?

**Comment by andy-ms** [comment]
Turns out we *do* allow `yield` in all these other cases:

```ts
function* f() {
    interface I {
        (yield: number): void;
        new (yield: number): void;
        f(yield: number): void;
    }
}
```

The reason is that those use `fillSignature`, which sets yield/await context.
`parseIndexSignatureDeclaration` doesn't, presumably because the parameters are delimited by `[]` instead of `()`.
So we could simply modify the `parseIndexSignatureDeclaration` code to set yield/await context too.

Or, pass the open/close token as parameters to `parseParameterList` instead of hardcoding parens there, then call that instead of `parseBracketedList`.

**Comment by RyanCavanaugh** [comment]
Doesn't seem like anyone else has noticed
