### ISSUE TITLE
type error of React.createElement(React.ComponentClass | React.StatelessComponent)

### ISSUE THREAD

**Issue by plantain-00** [Microsoft/TypeScript#15019]
**TypeScript Version:**  2.2.2

**Code**

```ts
// no compilation error as expected.
function foo1(child: React.ComponentClass<{ name: string }>) {
    React.createElement(child, { name: "bar" });
}

// no compilation error as expected.
function foo2(child: React.StatelessComponent<{ name: string }>) {
    React.createElement(child, { name: "bar" });
}

// compilation error.
function foo3(child: React.ComponentClass<{ name: string }> | React.StatelessComponent<{ name: string }>) {
    React.createElement(child, { name: "bar" });
}
```

**Expected behavior:**
no compilation error.

**Actual behavior:**
```bash
error TS2345: Argument of type 'ComponentClass<{ name: string; }> | StatelessComponent<{ name: string; }>' is
not assignable to parameter of type 'ComponentClass<{ name: string; }>'.
  Type 'StatelessComponent<{ name: string; }>' is not assignable to type 'ComponentClass<{ name: string; }>'.
    Type 'StatelessComponent<{ name: string; }>' provides no match for the signature 'new (props?: { name: string; }, contex
t?: any): Component<{ name: string; }, ComponentState>'
```

update:
I investigated react lib for a while, adding this should fix the problem:

```ts
function createElement<P>(
        type: SFC<P> | ComponentClass<P>,
        props?: Attributes & P,
        ...children: ReactNode[]): SFCElement<P> | ReactElement<P>;
```

**Comment by cevek** [comment]
It is not a react lib problem
```ts
function foo(name: string): void;
function foo(name: number): void;
function foo() {}

function bar(name: string | number) {
    foo(name); 
// Argument of type 'string | number' is not assignable to parameter of type 'number'.
//  Type 'string' is not assignable to type 'number'.
}
```

You just need cast `child` to `React.ComponentClass<{ name: string }>`
```ts
React.createElement(child as React.ComponentClass<{ name: string }>, { name: "bar" });
```

**Comment by plantain-00** [comment]
@cevek Thanks, that helps.

According to https://facebook.github.io/react/docs/react-api.html#createelement 
> The type argument can be either a tag name string (such as 'div' or 'span'), or a React component type (a class or a function).
maybe something like this is better:
```ts
function foo(name: string): void;
function foo(name: number): void;
function foo(name: string | number): void;

function bar(name: string | number) {
    foo(name);
}
```

anyway, feel free to close this issue, if not plan to change.

**Comment by spoco2** [comment]
This is definitely a bug in the way that it's causing compile issues for completely valid strings, such as "span" being passed into createElement. Should not have to cast things for it to accept them.
This very valid code fails now, was working until I updated type defs `React.createElement("span", {style: this.screenReaderStyles}, ariaLabel) : null,`

**Comment by ralexand56** [comment]
This makes no sense to me. The documentation states it clearly supports strings.

**Comment by Aldredcz** [comment]
+1

**Comment by mhegazy** [comment]
A change to the react declaration file should address the issue. for instance the last overload for `createElement` can be changed to:
```ts
    function createElement<P>(
        type: SFC<P> | ComponentClass<P>,
        props?: Attributes & P,
        ...children: ReactNode[]): ReactElement<P>;
```
Feel free to send a PR to https://github.com/DefinitelyTyped/DefinitelyTyped for this change.
