### ISSUE TITLE
Path casing in require

### ISSUE THREAD

**Issue by FilippoPolo** [Microsoft/TypeScript#1502]
The path specified in the require keyword is case-sensitive. There are good reasons for that, but it can be confusing, especially given that a project folder in Visual Studio Solution Explorer can have a different casing from the corresponding filesystem folder. It is entirely possible for a project to look like everything is correct in VS, including the casing, and still get "unable to resolve".

It would be nice if, in cases where a module cannot be found, but a module with the same path in different case exists, the compiler gave some kind of hint or warning.

**Comment by benliddicott** [comment]
see also #3626 and #2011
My vote: If it's going to fail *anywhere* make it fail *everywhere* and fail *fast* and with a good message.

**Comment by vladima** [comment]
#5275 introduces a flag `forceConsistentCasingInFileNames` - when it is set compiler will report an error if some file has multiple references with inconsistent casing inside the program

**Comment by vladima** [comment]
fixed in e811fecda645cd7905821d48fcf5f757dbedfa50
