### ISSUE TITLE
Extending Array, could not pass arguments using rest param to super() in constructor().

### ISSUE THREAD

**Issue by CamelKing** [Microsoft/TypeScript#15026]
**TypeScript Version:**  2.2.2 (tested 2.3 as well)

**Code**

```ts
// A simple code that subclass the Array object.
class SortedArray extends Array {
  constructor(...args: any[]) {
    return super(...args);
   }
}
```

**Expected behavior:**

Array() accepts two form of parameters:

1) Array(element0, element1[, ...[, elementN]])
2) Array(arrayLength)

I would expect the code above, calling the constructor of Array by using super() and passing all arguments to it (in the event of form (1) above) should be accepted by the tsc transpiler.

**Actual behavior:**

Error from tsc:
error TS2346: Supplied parameters do not match any signature of call target.

Pointing to the `super(...args)`. Further check reveals that the transpiler seems to be expecting a number type argument, as in the (2) syntax format above.

I tried ignoring the error, and run the resulting .js file. Everything seems to work fine.

Upon checking the typings file, I noticed the Array Constructor typing is defined as the following:

```ts
interface ArrayConstructor {
    new (arrayLength?: number): any[];
    new <T>(arrayLength: number): T[];
    new <T>(...items: T[]): T[];
    (arrayLength?: number): any[];
    <T>(arrayLength: number): T[];
    <T>(...items: T[]): T[];
    isArray(arg: any): arg is Array<any>;
    readonly prototype: Array<any>;
}
```

It seems there isn't one that cater for 

```ts 
(...items: any[]): any[]
```

while there is one that is similar but for the length argument.

```ts
(arrayLength?: number): any[];
```

**Comment by mhegazy** [comment]
you need to specify the generic type parameter for `Array`. i.e. `Array<any>` or even better `class SortedArray<T> extends Array<T> `. 

When resolving a super call, if your class reference does not have any generic type arguments, the compiler will try to find the non-generic signatures only. this excludes `<T>(...items: T[]): T[]`.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
