### ISSUE TITLE
Inexplicable behavior

### ISSUE THREAD

**Issue by monolithed** [Microsoft/TypeScript#15025]
**Example 1**

```ts
class foo {
  readonly 1 // the same with private and static
}
```

**Error**

No

**Result**:

```js
var foo = (function () {
    function foo() {
    }
    return foo;
}());

```

**Example 2**

```ts
class foo {
  const a () {} 
}
```

**Error**

```
Error:(2, 9) TS1248:A class member cannot have the 'const' keyword.
```

**Result**:

```js
var foo = (function () {
    function foo() {
    }
    foo.prototype.a = function () { };
    return foo;
}());
```

Is it ok?

**Comment by andy-ms** [comment]
**Example 1**:
It might help clarify to turn on `"noImplicitAny": true,` in your tsconfig. `1` is the *key* of the property there, and the type is omitted.
Property declarations have no effect on emit (unless they have an initializer).

**Example 2**:
`const` isn't allowed on a method, so TypeScript correctly gave you an error here.
TS will still have a best-guess emit even after an error; in this case it simply ignores `const`.

**Comment by monolithed** [comment]
Got it, thanks
