### ISSUE TITLE
Call signatures with differing `this` types

### ISSUE THREAD

**Issue by poseidonCore** [Microsoft/TypeScript#15023]
I would like to clarify whether this is a bug or just a design limitation or an implication of some quacky duck typing assumption.

I can get around this with type annotations and rarely comes up, but would have expected that the type inference system would have picked it up.

Many thanks

Todd

**TypeScript Version:**  2.1.5 @ Visual Studio 2017, TypeScript playground

**Code**

```ts
class A {
	newMe = handler;
}

class B {
	newMe = handler;
}

function handler(this:A):A;
function handler(this:B):B;
function handler(this:A|B):A|B {
	if (this instanceof A) return new A();
	if (this instanceof B) return new B();
}

var a = new A();
var x = a.newMe();  // This is correctly an A.

var b = new B();
var y = b.newMe(); // This is an A but should be a B.

```

**Expected behavior:**

y is instance of B

**Actual behavior:**

y is instance of A

-----

However, if I differentiate A from B at the point of definition, then it works fine:

```ts
class A {
	newMe = handler;
	n:number;
}

class B {
	newMe = handler;
	s:string;
}

function handler(this:A):A;
function handler(this:B):B;
function handler(this:A|B):A|B {
	if (this instanceof A) return new A();
	if (this instanceof B) return new B();
}

var a = new A();
var x = a.newMe(); // This is correctly an A.

var b = new B();
var y = b.newMe(); // This is correctly a B.
```

**Comment by RyanCavanaugh** [comment]
The TS type system is structural, and A and B are identical, so the signature `(this: B): B` can't be hit because it always matches the `A` signature instead. See also https://github.com/Microsoft/TypeScript/wiki/FAQ#when-and-why-are-classes-nominal

**Comment by poseidonCore** [comment]
POSTSCRIPT: This has been fixed now:

https://blogs.msdn.microsoft.com/typescript/2018/01/31/announcing-typescript-2-7/#in-operator-narrowing-and-accurate-instanceof
