### ISSUE TITLE
Change plugin loading logic

### ISSUE THREAD

**Issue by RyanCavanaugh** [Microsoft/TypeScript#15035]
We need to change the plugin loading logic as follows:

 * TS Server should only load plugins from its peer/parent node_modules folders ("local" folders)
 * Hosts can specify additional plugin probing folders ("global" folders)
 * Hosts can also specify global plugins to load; these plugins do not get configuration settings

Open question: Should globally-specified plugin names probe from local folders before global folders? Or probe global folders only?

/cc @mhegazy @mjbvz

**Comment by mjbvz** [comment]
//cc @kieferrm

Looks good.

On the last point, my understanding was that TypeScript would always search locally (in the peer folders) before searching the global paths. This logic would be needed for the case where a user points `tsdk` in vscode to a global typescript install. In that instance, I believe we would want to prefer any globally installed plugins over the the plugin copies found in the global paths passed to TS Server
