### ISSUE TITLE
Error when importing untyped JS modules

### ISSUE THREAD

**Issue by balajikris** [Microsoft/TypeScript#15031]
**TypeScript Version:**  2.2.1

**Steps**
1. In a simple TS project in VSCode, add `"adal-node": "^0.1.22",` to `package.json` and run `npm install`. This is a JS library with no types.
1. Import the library in your `index.ts` as below

**Code**

```ts
import adal from "adal-node";
```

**Expected behavior:**
Per this bug's resolution #3019 this code should compile with no errors

**Actual behavior:**
tsc.exe: 'Could not find a declaration file for module 'adal-node'. 'e:/proj/node_modules/adal-node/lib/adal.js' implicitly has an 'any' type.'

**References**:
see #3019 and all its linked bugs

**Comment by unional** [comment]
Because you have turned on `noImplicitAny`. You need to get around it by doing `declare module 'adal-node'`

**Comment by unional** [comment]
https://github.com/Microsoft/TypeScript/issues/13348

**Comment by balajikris** [comment]
oops! you're right that I have `noImplicitAny` compiler option set in my `tsconfig.json`. Totally forgot about it as its one of my default configs to writing TS. 

I think I can work with the solution you posted on the other thread. Thanks for the quick feedback ! Appreciate it.

**Comment by balajikris** [comment]
I tried the suggestions mentioned in the linked bug like so:

```ts
declare module 'adal-node/*'{
    var _a: any;
    export = any;
}
```

and i get this error:
tsc.exe : Invalid module in augmentation, module 'adal-node/*' cannot be found.

**Comment by masaeedu** [comment]
@balajikris Have you tried: 

```ts
declare module 'adal-node' {
    var _a: any;
    export = any;
}
```

instead?

**Comment by balajikris** [comment]
@masaeedu : Thanks for the comment. Yes, I did try that earlier. I also errored out, but a slightly different message.

tsc: 'Invalid module name in augmentation. Module 'adal-node' resolves to an untyped module at 'e:/repos/samples/keyvault-management-typescript/node_modules/adal-node/lib/adal.js', which cannot be augmented.'

**Comment by billti** [comment]
So it's loading the module via the .js file also it seems. Do you have 'allowJs' set in your project config?

**Comment by balajikris** [comment]
@billti : Thank you for the hint. I tried after setting `allowJs: true` and the error message remains the same as above.

**Comment by aluanhaddad** [comment]
```js
declare module 'adal-node/*'{
    var _a: any;
    export = any;
}
```
did you mean
```ts
declare module 'adal-node/*'{
    var _a: any;
    export = _a;
}
```
?

**Comment by balajikris** [comment]
@aluanhaddad -- yes ofcourse. sorry, that was a typo! updated my post

**Comment by TAGC** [comment]
Is there any way to do something simple like `import * as BabiliPlugin from "babili-webpack-plugin";` with `noImplicitAny` enabled *without* getting warning TS7016 ("could not find a declaration file...implicitly has an 'any' type")?

**Comment by mhegazy** [comment]
> Is there any way to do something simple like import * as BabiliPlugin from "babili-webpack-plugin"; with noImplicitAny enabled without getting warning TS7016 ("could not find a declaration file...implicitly has an 'any' type")?

Add a declaration for your module, e.g.:

```ts
declare module "babili-webpack-plugin" {
     export ...
}
```

or simply:

```ts
declare module "babili-webpack-plugin";
```

**Comment by mhegazy** [comment]
The issue as described by the OP seems fixed. 

The other issue described in https://github.com/Microsoft/TypeScript/issues/15031#issuecomment-292011200, is because a module declaration (i.e `declare module 'adal-node'  {... }`) inside another module (i.e. a file with at least one top-level `import` or `export`) is considered an "augmentation". 
What you want is to move this declaration to a global .d.ts (as you want it to be in the global scope) file instead of keeping it in your module.

**Comment by balajikris** [comment]
@mhegazy : I'm still not sure how to correctly use this `declare module` and `import` syntax to import untyped JS modules. Could you please provide a small snippet demonstrating how to accomplish that? Thanks.

**Comment by mhegazy** [comment]
```ts
c:\test\15031>npm install adal-node
npm WARN deprecated node-uuid@1.4.7: Use uuid module instead
test@1.0.0 c:\test\15031
`-- adal-node@0.1.22

c:\test\15031>echo import adal from "adal-node"; > a.ts

c:\test\15031>type a.ts
import adal from "adal-node";

c:\test\15031>tsc a.ts

```

**Comment by balajikris** [comment]
Interesting, so i do not have to do a `declare xxx` and a simple `import adal from "adal-node";` as in my original bug report should work. 

I'm on tsc v2.2.2 and I'm seeing `error TS1192: Module ''adal-node'' has no default export.` for the above usage. What version of tsc.exe is this supposed to work on?

**Comment by TAGC** [comment]
@balajikris I've just tried it using Typescript v2.2.2 and it works fine for me. Are you sure you're not picking up a stray `.tsconfig`? Are you testing in the same directory?

**Comment by balajikris** [comment]
Thanks for checking @TAGC . I do have a .tsconfig but that's intentional and not a stray one. I'll play with this a little more to understand what i'm missing.

**Comment by SaschaNaz** [comment]
@balajikris probably `import * as adal from "adal-node";`?

**Comment by oreporan** [comment]
Still not being able to work with adal-node in typescript
I tried creating adal-node.d.ts:

```
declare module 'adal-node/*'{
    var _a: any;
    export = _a;
}
```

my import ts file still says:

```
error TS7016: Could not find a declaration file for module 'adal-node'. 'node_modules/adal-node/lib/adal.js' implicitly has an 'any' type.
  Try `npm install @types/adal-node` if it exists or add a new declaration (.d.ts) file containing `declare module 'adal-node';`
```

**Comment by mhegazy** [comment]
@oreporan i am unable to reproduce any errors for this scenario. 

One note, if your import looks like `import * as adal from "adal-node/argument";` then your module declaration looks correct, if it is however `import * as adal from "adal-node";` then the module declaration does not match that. consider instead declaring it as `declare module 'adal-node' { .. }`

**Comment by oreporan** [comment]
Thanks
I ended up forking and making a pull request with typings and adding an index.js outside the lib, which solves the issues

**Comment by Spongman** [comment]
why does the noImplicitAny check fire when import .js files? surely when you're importing a .js file you're _explicitly_ declaring everything within it as `any` ?

**Comment by mhegazy** [comment]
> it seems too heavy a burden to require everything to have a @types 

you do not need to include `@types`. just add:
```ts
declare module "foo";
```

**Comment by xobs** [comment]
It is still impossible to import untyped Javascript modules.

I've spent the past few hours trying to figure out how to use `adapter.js` with Typescript, and I've run into no end of problems.  At this point, I'm ready to give up again on Typescript.

I've saved `adapter.js` in the `src/` directory, along with `main.ts`.  Things I've tried that haven't worked:

```typescript
import * as webrtc from 'adapter.js';
```
7:25 Cannot find module 'adapter.js'.

```typescript
import * as webrtc from 'adapter';
```
7:25 Cannot find module 'adapter'.

```typescript
declare module 'adapter.js';
```
5:16 Invalid module name in augmentation, module 'adapter.js' cannot be found.

```typescript
declare module 'adapter.js';
```
5:16 Invalid module name in augmentation, module 'adapter' cannot be found.

```typescript
import * as webrtc from './adapter.js';
```
7:25 Could not find a declaration file for module './adapter.js'. 'PROJECT/src/adapter.js' implicitly has an 'any' type.

```typescript
declare module './adapter.js';
import * as webrtc from './adapter.js';
```
ERROR in PROJECT/src/main.ts
5:16 Invalid module name in augmentation. Module './adapter.js' resolves to an untyped module at ERROR in PROJECT/src/main.ts
6:25 Could not find a declaration file for module './adapter.js'. 'PROJECT/src/adapter.js' implicitly has an 'any' type.

```typescript
// adapter.d.ts
declare module "adapter" {
    var _temp: any;
    export = _temp;  
}

// main.ts
declare module './adapter.js';
import * as webrtc from './adapter.js';
```
5:16 File 'PROJECT/src/adapter.d.ts' is not a module.
6:25 File 'PROJECT/src/adapter.d.ts' is not a module.

```typescript
import adapter = require("./adapter.js");
```
5:1 Import assignment cannot be used when targeting ECMAScript modules. Consider using 'import * as ns from "mod"', 'import {a} from "mod"', 'import d from "mod"', or another module format instead.

**Comment by slavafomin** [comment]
Hello! Could you please clarify where do I put this declaration file:

```
declare module 'adal-node';
```

And how do I instruct compiler to actually use it?

**Comment by zbicin** [comment]
@slavafomin it worked for me in a similar case in another project, when I've put a new `index.d.ts` in the project root directory (i.e. in the same directory as the `tsconfig.json` is located).

**Comment by SCLeoX** [comment]
@Spongman Actually, you can just have a `global.d.ts` at your project root with following content:

```
declare module '*';
```

It automatically makes all js modules any while ts modules keep working as intended.

**Comment by icfantv** [comment]
I can confirm @SCLeoX's suggestion.  I just created a root-level `global.d.ts` file for untyped 3rd party libs.  IMO, `*` is a bit too heavy-handed and I'd rather be explicit, so I simply took the module that the compiler was complaining about and declared it explicitly.  But, that's just my opinion.

**Comment by nodefish** [comment]
I migrated my project away from TypeScript in 2015 because of this issue. I recently saw there was a new TypeScript release on hackernews, so I figured I'd check if in 2018 it was finally possible to import untyped JavaScript modules while having `noImplicitAny` apply to TS code, an extremely common use case given the widespread use of npm.

I see it's settled on having a shorthand for a workaround, which, ok, but I have to ask: why? Is it so damaging to the maintainers' ego to have gone with the obvious solution? TS has not been a drop-in replacement for JS, for years, because of this one minor issue. Get some perspective guys!

**Comment by bitadj** [comment]
I've been hunting around for this answer for the better part of a month now. I found a solution that works in VS Code that isn't a wholesale disabling of all validation for javascript and also did not require that I add files/declarations to a repository that is not mine.

Add this line to your user settings:

`"javascript.suggestionActions.enabled": false`

Unlike `"javascript.validate.enable": false` (which you should not use), the above setting will remove those annoying `[ts] Could not find a declaration file for module` errors for untyped module imports in javascript files and it will still play nice with linters and give you appropriate and relevant errors.

**Comment by gunar** [comment]
I took @SCLeoX's suggestion and made the pattern-matching a bit narrower.

```diff
- declare module '*' {
+ declare module '*.js' {
   const value: any
   export default value
 }
```

**Comment by ackvf** [comment]
Is it possible to re-export an existing typed module and use its types for the untyped module?

I am importing a library `react-final-form-html5-validation` that is just a tiny wrapper around typed `react-final-form`.

Are there any options for this?

I have tried many many many things ......., but this looks most promising, however, `react-final-form` does not declare a namespace and so I cannot use its types like I can use the `React` below.


`project/index.d.ts`

    /// <reference types="react-final-form" />
    //// <reference types="./node_modules/react-final-form/dist/index.d.ts" />
    //// <reference path="./node_modules/react-final-form/dist/index.d.ts" />
    //// <amd-dependency path="./node_modules/react-final-form/dist/index.d.ts" />
    // importing resolves the types, but also turns it into a module, which in turn breaks it
    // import * as RFF from react-final-form; 
    // import { FieldProps } from react-final-form;
    // export * from react-final-form;

    declare module 'react-final-form-html5-validation' {
      var Field: React.ComponentType<FieldProps>
    }

`project/src/index.tsx`

    import { Field, Abc } from 'react-final-form-html5-validation'
    // correct: Module '"react-final-form-html5-validation"' has no exported member 'Abc'

    // later in App.render() { return ( .....
          <Field />

    // Field is of type React.ComponentType<any>

**Comment by P0oOOOo0YA** [comment]
Typescript should act smarter in these cases. WHY ON EARTH we need to define a type definition if we explicitly import a JS module.

**Comment by squarewave24** [comment]
i found this to be a helpful write up.  https://medium.com/@chris_72272/migrating-to-typescript-write-a-declaration-file-for-a-third-party-npm-module-b1f75808ed2

in my case i just had to place the migration file in `src/@types/@okta/library-name/index.d.ts` and as long as the part after @types matched the import, it was picked up. inside can be just 1 line declaring the module

**Comment by rbrisita** [comment]
**Two year problem still plagues developers...**

Below is an example using Angular to help anyone else who faces this issue with an untyped package:

1. `npm install --save-dev motion-ui`
1. `echo "declare module '*';" >  resources/ts/global.d.ts`
1. To use in a component:
    `import * as MotionUI from '../../../node_modules/motion-ui/dist/motion-ui';`
1. npm run dev

The code should transpile correctly. Also to ignore TypeScript errors one can use `// @ts-ignore` just above the line that errors but I would recommend resolving the error correctly.

**Comment by EhsanSarshar** [comment]
tried all the solutions not working! :(

**Comment by kud** [comment]
Same here.

![image](https://user-images.githubusercontent.com/655838/84512272-05dc9400-acc8-11ea-8ec1-bddaccb0a492.png)

**Comment by jQrgen** [comment]
Same here

**Comment by jQrgen** [comment]
How would one import this library in typescript? https://www.npmjs.com/package/grudus-timepicker

**Comment by uythoang** [comment]
> i found this to be a helpful write up. https://medium.com/@chris_72272/migrating-to-typescript-write-a-declaration-file-for-a-third-party-npm-module-b1f75808ed2
> 
> in my case i just had to place the migration file in `src/@types/@okta/library-name/index.d.ts` and as long as the part after @types matched the import, it was picked up. inside can be just 1 line declaring the module

Thanks for this, I was racking my brain trying to figure it out. The only other thing I had to do was add the following to `tsconfig.json`:

`
{
  "compilerOptions": {
    "paths": {
      "*": [
        "node_modules/*",
        "src/@types/*"
      ]
    }
  }
}
`

**Comment by blabadi** [comment]
In my case I had a module that declares  a .d.ts and in that .d.ts they use an implicitly any module, which all the solutions above don't help with, but this did the trick:
```
{
    "compilerOptions": {
        "skipLibCheck": true,
        ...
    },
    ...
}
```
