### ISSUE TITLE
Incorrect emit for module M with import M inside it

### ISSUE THREAD

**Issue by JsonFreeman** [microsoft/TypeScript#1503]
Two different modules with the same last name. One imports the other with an alias of that same name. The variable M in the emitted code corresponding to A.M needs to be _M.

``` ts
module Z.M {
    export function bar() {
        console.log(1);
    }
}
module A.M {
    import M = Z.M;
    export function bar() {
        console.log(2);
    }
    M.bar(); // Calls the wrong function at runtime, works if you change the above import to a var
}
```

This is a severe breaking change because it leads to subtle behavioral bugs at runtime.

**Comment by JsonFreeman** [comment]
Oh sorry, I thought github closed it via analysis of the phrase "Fix issue #1503"

**Comment by NoelAbrahams** [comment]
@JsonFreeman, [apparently](https://help.github.com/articles/closing-issues-via-commit-messages) the issue number should immediate follow the "Fix" keyword.

**Comment by JsonFreeman** [comment]
Aha, thanks. That's what I was missing
