### ISSUE TITLE
VS2017 debugger does not see .js.map when --outFile is specified

### ISSUE THREAD

**Issue by SaschaNaz** [Microsoft/TypeScript#15043]
**TypeScript Version:**  VS2017 default 2.1.5.0

**Repro**

1. Create a new Blank App (Universal Windows) project
2. Rename js/main.js to js/main.ts
3. Build+Deploy by clicking "Local Machine"
4. You will see js/main.ts below Script Documents
5. Go (Project) Properties->TypeScript Build
6. Write js/main.js on "Combine JavaScript output into file"
  ![image](https://cloud.githubusercontent.com/assets/3396686/24792225/13c7b620-1bb8-11e7-9e30-8e7962583ad7.png)
7. Build+Deploy

**Expected behavior:**

You should still be able to see js/main.ts.

**Actual behavior:**

The file disappears from Script Documents.

**Comment by minestarks** [comment]
Hey @SaschaNaz, thank you for the report. When you say "The file disappears from Script Documents", which "Script Documents" view are you referring to exactly?

**Comment by SaschaNaz** [comment]
"Script Documents" in the right pane here: 

![image](https://cloud.githubusercontent.com/assets/3396686/24781986/58a05700-1b7e-11e7-9bc9-be4d27447668.png)

**Comment by SaschaNaz** [comment]
Debug output says VS tries loading js.map in wrong directory:

```
SourceMap C:\Users\sasch\Documents\Visual Studio 2017\Projects\TSOutFileJSMapFailure\TSOutFileJSMapFailure\main.js.map read failed: Could not find file 'C:\Users\sasch\Documents\Visual Studio 2017\Projects\TSOutFileJSMapFailure\TSOutFileJSMapFailure\main.js.map'..
```

... even when the compiler emitted it at js/main.js.map.

**Comment by SaschaNaz** [comment]
The path on sourceMappingURL comment itself is wrong.

```js
//# sourceMappingURL=C:/Users/sasch/documents/visual studio 2017/Projects/TSOutFileJSMapFailure/TSOutFileJSMapFailure/main.js.map
```

Should be:

```js
//# sourceMappingURL=C:/Users/sasch/documents/visual studio 2017/Projects/TSOutFileJSMapFailure/TSOutFileJSMapFailure/js/main.js.map
```

**Comment by SaschaNaz** [comment]
A workaround is to add `<TypeScriptMapRoot>$(MSBuildProjectDirectory)/js</TypeScriptMapRoot>` to match the outFile directory.

**Comment by minestarks** [comment]
In addition to the above workaround of changing the ```TypeScriptMapRoot```, you can unset ```TypeScriptMapRoot``` and add your output JS file to the project as a ```Content``` item.

**Comment by minestarks** [comment]
Thanks for reporting. Though I see the issue, I'm closing this and marking as Won't Fix, as setting source map path settings is the recommended way of handling the problem at the moment.
