### ISSUE TITLE
HTMLOptionElement gives error Property 'value' does not exist on type 'Element'.

### ISSUE THREAD

**Issue by quantuminformation** [microsoft/TypeScript#15047]
I'm getting this in this case of an HTMLOptionElement value

![image](https://cloud.githubusercontent.com/assets/216566/24753004/4a4f29c6-1ac8-11e7-956a-9972309f7651.png)

It should have that value as HTMLOptionsCollection contains HTMLOptionElement elements:
    `readonly options: HTMLOptionsCollection;`

```js
interface HTMLOptionsCollection extends HTMLCollectionOf<HTMLOptionElement> {
    length: number;
    selectedIndex: number;
    add(element: HTMLOptionElement | HTMLOptGroupElement, before?: HTMLElement | number): void;
    remove(index: number): void;
}
```

Using typescript@2.2.1

My workaround was to use an unnecessary cast
`    let newValue = (target.options[newSelectedIndex] as HTMLOptionElement).value`

**Comment by SaschaNaz** [comment]
Probably this is because the indexer of HTMLCollectionOf only returns Element, not HTMLOptionElement.

**Comment by QuantumInformation** [comment]
The generic should return type of T right?

**Comment by SaschaNaz** [comment]
That's right.

**Comment by marcus-petty** [comment]
Please fix!

**Comment by QuantumInformation** [comment]
That would be awesome!

**Comment by Andarist** [comment]
I believe that this can be closed since this is very much accessible today:
```ts
const select = {} as HTMLSelectElement
select.options[0].value // ok! :)
```

cc @jakebailey
