### ISSUE TITLE
underscore prefix fails to override noUnusedLocals in Destructing Assignment

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/TypeScript#15053]
**TypeScript Version:**  master, commit  dce7fca83d6bbf0bf

Found while working on https://github.com/Microsoft/TypeScript/issues/14420

**Code**

```ts
let {x} = {x: 1};
let {x: _x} = {x: 1};
let {_y} = {_y:1};

```

**Expected behavior:**

Error on `x` for being unused, but not `_x` or `_y`.

**Actual behavior:**

Error on `x`, `_x`, and `_y` for being unused.

EDIT: added a case.

**Comment by mhegazy** [comment]
Should be fixed in latest.

**Comment by zwhitchcox** [comment]
This still doesn't work for me
