### ISSUE TITLE
Type widening works incorrect (maybe?) 

### ISSUE THREAD

**Issue by cevek** [Microsoft/TypeScript#15054]
**TypeScript Version:**  2.3.0-dev.20170403

**Code**

```ts
function abc(): number | false {
    return 1;
}

let x;
x = abc(); // x type widened to number | boolean, but why?
// let x = abc(); // if uncomment this example works as expected
if (x !== false) {
    let y = x + 1;  // Operator '+' cannot be applied to types 'number | true' and '1'
}
```

**Expected behavior:**
No error

**Actual behavior:**
Operator '+' cannot be applied to types 'number | true' and '1'

**Comment by aluanhaddad** [comment]
Interestingly this only happens when you do not join the declaration and assignment of `x`. Not sure why that changes things but it could well be by design, or it could be an edge case. The last time I wrote a variable that was not initialized in its declaration... I can barely remember.

**Comment by RyanCavanaugh** [comment]
@ahejlsberg thoughts?

**Comment by cevek** [comment]
Another relative issue
```ts
const enum Type {
  A, B
}
interface A {
   type: Type.A;
}
function createA(): A {
     return _createA(); // Type '{ type: Type; }' is not assignable to type 'A'.
}
function _createA() {
   return {
      type: Type.A
   }
}
```

**Comment by mhegazy** [comment]
We have discussed this issue multiple times in the past, and every change to how widening works has potential of breaking some other scenarios. the truth of the matter is that intent in these cases is not clear.. and the compiler tries to strike a balance. I think this is, and possibly others, are design limitation of the current implementation.
