### ISSUE TITLE
`noImplicitReturns` ignored when some return value is `any`

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#15064]
**TypeScript Version:**   nightly (2.3.0-dev.20170325)

**Code**

With `--noImplicitReturns` on:

```ts
declare var x: any;
function f() {
    if (1 + 1 === 3) {
        return x;
    }
}
```

**Expected behavior:**

The same error we get if we use `declare var x: number;`: `Not all code paths return a value.`

**Actual behavior:**

No error.

**Comment by DanielRosenwasser** [comment]
This is "working as intended" as per #13112, but I still don't but I wasn't given an explanation for why the issue was closed out.

**Comment by aluanhaddad** [comment]
Seems fairly logical. Since `void` is assignable to `any`. Perhaps I am missing something.

**Comment by gcnew** [comment]
Maybe related https://github.com/Microsoft/TypeScript/issues/13284.
