### ISSUE TITLE
add warnings when import/require might be ambiguous

### ISSUE THREAD

**Issue by devdoomari** [Microsoft/TypeScript#15067]
how about adding a warning when:

```typescript
import * as aws from './configs/aws';
```
might be resolved to aws.json OR aws.ts ?

I've wasted 2 hours debugging an issue related to this : (
(expected aws.ts to load, but aws.json loaded instead)

**Comment by RyanCavanaugh** [comment]
There wouldn't be a way to silence that warning. We don't add "warnings" that can only accumulate
