### ISSUE TITLE
duplicate variable/parameter declaration not being enforced correctly

### ISSUE THREAD

**Issue by fletchsod-developer** [Microsoft/TypeScript#15072]
**Comment**
If this is a duplicate issue then my bad!  Make this a duplicate of other issues.  Thanks.

**TypeScript Version:**  2.1.5 or later
**Visual Studio Enterprise 2017 Version:** 15.1 (26403.0) Release

**Code**
    //Warning works
    setHand1(dx: number): void {
        let dx: number = 0;
    }
    //Warning doesnt work
    setHand2(dx: number): void {
        var dx: number = 0;
    }
    //Warning works
    setHand3(dx: number): void {
        let dx = 0;
    }
    //Warning doesnt work
    setHand4(dx: number): void {
        var dx = 0;
    }
    //Warning doesnt work
    setHand5(dx: number): void {
        for (let dx = 0; dx < 1; dx++) { }
    }
   //Warning doesnt work
    setHand6(dx: number): void {
        for (var dx = 0; dx < 1; dx++) { }
    }

**Expected behavior:**
TypeScript code should raise red underline and throw compiler warning (or error).  But it didn't on some setHand methods.   setHand1() and setHand3() works but all other doesn't.  When you're dealing with large TypeScript code, it does help to waste less time figuring out why the script dont work.  In this case, setHand5() had failed on me when the "dx" parameter end up as undefined value when entering into the method scope.

**Actual behavior:**
Show red underline and compiler warning (or error)

**Comment by j-oliveras** [comment]
You can use [tslint](https://palantir.github.io/tslint/)'s `no-shadowed-variable` rule for this.

**Comment by RyanCavanaugh** [comment]
It's valid to lexically shadow like that and it'd be very annoying to not be able to (imagine not being able to write `let name = "hello"` because it would shadow the *global* `name`).

Declaring a var is similarly legal.

**Comment by fletchsod-developer** [comment]
Ah cool!  If that's the way it should be then I'm okay with it.  

One thing here that don't make sense here on the "setHand5()" method, is that the method's parameter "dx" becomes undefined (instead of containing the actual passed-in value), just because the "let dx" in the for loop happen to wipe out the "setHand5()" method's passed-in parameter.    So, if you said it is working as intended then feel free to close this bug.   If it's not suppose to happen when the two "dx" variables becomes a seperate variable with no shared value then I believe it is a bug in this case.

**Comment by RyanCavanaugh** [comment]
That's just what JavaScript does. An uninitialized shadowing variable is uninitialized.
