### ISSUE TITLE
functions expected to return objects with only optional keys can return other primitives

### ISSUE THREAD

**Issue by dan-james-deeson** [Microsoft/TypeScript#15070]
**TypeScript Version:**  whatever this uses: https://www.typescriptlang.org/play/

**Code**

```ts
function foo1 (): {id?} {
    return { id: 'true' };
}

function foo2 (): {id?} {
    return {};
}

function foo3 (): {id?} {
    return 13;
}
```

**Expected behavior:**
foo3 to have some kind of compile error

**Actual behavior:**
It compiles. Same behaviour if you return strings and booleans.

**Comment by RyanCavanaugh** [comment]
This isn't wrong. For example, you *can* pass a `string` to something that expects `{ length: number }` and that's not incorrect.

See also https://github.com/Microsoft/TypeScript/wiki/FAQ#what-is-structural-typing

**Comment by dan-james-deeson** [comment]
I can see why that would be the case. But `id` isn't a property of `string`, so it definitely feels like an unusual behaviour.

This, for example, produces an error:
```
const x = "string";
x.id = 123;
```

I suppose that really this all stems from the fact that typescript relies on duck typing...

I agree it's working as intended, but it still somehow feels wrong to me. Perhaps it's just something that a type-checker could never be definitive about.
