### ISSUE TITLE
Compiled generators does not have correct constructor name

### ISSUE THREAD

**Issue by paldepind** [microsoft/TypeScript#15088]
**TypeScript Version:**  2.3.0-dev.20170407

```ts
function* myGeneratorFunction() {
    yield 1;
    return 2;
}

console.log(myGeneratorFunction.constructor.name);
```

**Expected behavior:**

Code logs "GeneratorFunction" when compiled to ES5.

**Actual behavior:**

Code logs "Function" when compiled to ES5.

**Description:**

Babel compiles this code so that the constructor name is set correctly. They do that by including a small run-time function that marks all generator functions as such. The source code for the marking function can be [found here](https://github.com/facebook/regenerator/blob/9e6762adf26d8886ff6987343d29abb20c909695/packages/regenerator-runtime/runtime.js#L131-L142).

Compiling this per the specification is important since using the constructor name is the only way to check if a certain function is a generator function or not. See for instance [this SO question and answer](http://stackoverflow.com/questions/16754956/check-if-function-is-a-generator).

**Comment by KatSick** [comment]
Is there any updates ?

**Comment by paldepind** [comment]
@KatSick I am not aware of any updates. Previously it was tagged for the 2.4 release but now it's just tagged as future. I still really hope it'll be fixed as it's quite problematic for a project I'm working on.

@rbuckton is assigned to this issue. Do you have any idea about a timeline for this?

**Comment by nickbreaton** [comment]
This also applies to async functions:

TypeScript:
```ts
async function a() {}

a.constructor.name // "Function"
```

Latest version of Chrome:
```js
async function a() {}

a.constructor.name // "AsyncFunction"
```

**Comment by rotu** [comment]
[I think this is resolved](https://www.typescriptlang.org/play?ts=3.3.3#code/GYVwdgxgLglg9mAVAAgLYE8DiBTM2BOAhlHPgGLjTxgAUAlMgN4BQyby6M2ANgCbIBGANyt2+bFBD4wyAEwiAvs2YQEAZzjdsAOm5wA5jQw48REuUqwE21WDVR8IaKW1hCqbHSFA).

**Comment by RyanCavanaugh** [comment]
This doesn't seem like an important scenario for modern JS development - folks can either target ES6 which is supported basically everywhere, or use an alternate transpiler with stricter adherence semantics if this is important for their scenario.
