### ISSUE TITLE
When using allowJs, you are unable to use classes that do not extend a declared class without including its generic type arguments.

### ISSUE THREAD

**Issue by joelday** [Microsoft/TypeScript#15087]
**TypeScript Version:**  2.2.2

In this specific scenario, allowJs is enabled and react.d.ts is available. The React typings declares `Component<P, S>`. In a JavaScript file, a class is defined that extends `React.Component`, but without the generic arguments.

**Code**
foo.js:
```js
export class FooComponent extends React.Component {
  ...
}
```

bar.tsx:
```ts
import { FooComponent } from './foo'

...

<FooComponent />
or
const f = new FooComponent(…)
```

**Expected behavior:**
An ES6 class from './foo' that extends `React.Component` without generic arguments can be used in a .tsx file that imports it.

**Actual behavior:**
"[ts] Cannot use 'new' with an expression whose type lacks a call or construct signature." errors. 

I think that this class should be automatically inferred to have extended `React.Component<any, any>`

**Comment by jwbay** [comment]
Seems like #14907 might resolve this

**Comment by joelday** [comment]
Dupe of #14907
