### ISSUE TITLE
Destructuring and lambdas

### ISSUE THREAD

**Issue by przemo098** [Microsoft/TypeScript#15082]
**TypeScript Version:**  2.2.2

**Code**
![image](https://cloud.githubusercontent.com/assets/6282239/24827582/d20d3ff8-1c4c-11e7-8f69-8616a10b2fa7.png)

Also specyfing type doesn;t work:
![image](https://cloud.githubusercontent.com/assets/6282239/24827613/5832109a-1c4d-11e7-8e01-ba84388656b1.png)

It's impossible to use destructuring with lambda expression or I don't know how :).

**Expected behavior:**
Code should get compiled

**Actual behavior:**
I need to get full object and destruct it later..

**Comment by ikatyang** [comment]
It should be something like this:
```ts
export default ( { match }: { match: string } ) => match;
```
or you can just disable the `--noImplicitAny` option.


The following code is just renaming:
```ts
var example = { a: 'a', b: 'b' };
var { a: b } = example;
a // a is not defined
b // "a"
```

**Comment by aluanhaddad** [comment]
@ikatyang is 100% correct. It's also worth noting that this has nothing to do with arrow functions (what you refer to as lambda expressions) as it applies to anything the declares parameters.

**Comment by przemo098** [comment]
Thanks ikatyang in meantime I tried
` { match } : any`
and it worked.

Thanks guys !
