### ISSUE TITLE
SVGLocatable missing in lib.dom.d.ts

### ISSUE THREAD

**Issue by obiwan007** [Microsoft/TypeScript#15085]
**TypeScript Version:**  2.2.1 / nightly (2.2.0-dev.201xxxxx)

**Expected behavior:**
type SVGLocatable should be available in some d.ts file.

**Actual behavior:**
type SVGLocatable (and a bunch of derived classes) are missing since 2.2.1. In Version 2.2.0 there are still there.

**Comment by extremeandy** [comment]
I believe it was removed from lib.d.ts also

**Comment by gatimus** [comment]
This https://developer.mozilla.org/en-US/docs/Web/API/SVGSVGElement#Specifications makes it sounds like they are removing `SVGLocatable` interface and if you look at [SVG 2](https://www.w3.org/TR/SVG2/types.html) there is no mention of `SVGLocatable`. Could that be why?

**Comment by extremeandy** [comment]
So is the recommendation to use `SVGElement` instead?

**Comment by mblandfo** [comment]
I was looking for getBBox() and found it on SVGGraphicsElement
