### ISSUE TITLE
Object which extends the Array<BoxModel> can not call the inside methods anymore

### ISSUE THREAD

**Issue by sasos90** [Microsoft/TypeScript#15084]
**TypeScript Version:**  2.2.1

**Code**

```ts
export class BoxList extends Array<BoxModel> {

    constructor() {
        super();
    }

    public allHit(boxTarget: BoxModel) : boolean {
        return this.findIndex(box => box.doesMatch(boxTarget) && !box.isHit) === -1;
    }
}

.. somewhere in other classes
this.boxList = new BoxList();
this.boxList.allHit(someBoxModel); ( produces an error )


```

**Expected behavior:**
Should call "allHit" method.

**Actual behavior:**
Throws an error:
-> main.js:1 ERROR TypeError: this.boxList.allHit is not a function(…)

**Comment by aluanhaddad** [comment]
https://github.com/Microsoft/TypeScript-wiki/blob/master/Breaking-Changes.md#extending-built-ins-like-error-array-and-map-may-no-longer-work

**Comment by aluanhaddad** [comment]
> Thanks. That Object prototype solved the problem!

Glad to hear that but _personally_ I strongly recommend that you avoid it and not subclass `Array` at all. There are plenty of environments in which it can fail.

**Comment by sasos90** [comment]
So what is the alternative to create the so called arraylist implementation like in java?

**Comment by aluanhaddad** [comment]
You mean you want a dynamically resizing array? Just use `Array`.

**Comment by sasos90** [comment]
No actually I want some custom methods that will work on behalf of that existing array. So for example i call the list method disableAllBoxes and that method will loop through its own array and change the flags. If I can not extend the array I will have to use some new model who will cope with that.

**Comment by sasos90** [comment]
Now I would have to have 2 objects instantiated if you know what I mean.

**Comment by aluanhaddad** [comment]
As you have observed you can extend array, it is just awkward and will fail in some environments. I would wrap the array. I think that is better design anyway. Of course this is subjective.

**Comment by sasos90** [comment]
In the end I am creating cordova app which is going to have the crosswalk installed for android so if it works once, it works always. I will give it a try :) Tnx!

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
