### ISSUE TITLE
code completion with "." and "(" broken (again and again)

### ISSUE THREAD

**Issue by nippur72** [Microsoft/TypeScript#15091]
This bug keeps on returning, we had it in #3202 then it was fixed, later in #9777 and it was fixed again, now we have the same issue (Visual Studio 2017 CE).

Code completion should complete when typing `.` or `(`, e.g:
 
text is `JSO` but typing `.` does not autocomplete to `JSON`
text is `JSON.par` but typing `(` does not autocomplete to `JSON.parse(`

Only `TAB` key does the autocomplete.

**Comment by aluanhaddad** [comment]
I am using Visual Studio 17.1 24603.0 RTM, I tried your exact example and I do not experience this issue

Can you check the setting below
![image](https://cloud.githubusercontent.com/assets/5034656/24840128/7a3387e4-1d35-11e7-9003-3e6a04e6d83f.png)

**Comment by nippur72** [comment]
😳 aehm... where can I run and hide?
