### ISSUE TITLE
Generics and type inference

### ISSUE THREAD

**Issue by Roam-Cooper** [Microsoft/TypeScript#15095]
**TypeScript Version:**  2.2.2 / nightly (2.2.0-dev.201xxxxx)

**Code**

```ts
export class Thing<T>{
    constructor(input: Fruit<T>, mapping: () => T) { }
}

new Thing(Fruit<apple>null, ()=>{
return {};
});
```

**Expected behavior:**
Compiler complains that `{}` is not assignable to Fruit<apple> as the compiler sees `T` as a `Fruit<apple>` FIRST.
**Actual behavior:**
Compiler finds best common type between `Fruit<apple>` and `{}` for `T` which ends up being `{}`. However, this means that the mapping function is not forced to return `Fruit<apple>`.

Additionally, if I specify mapping as:
```ts
mapping: () => T & {}
```
Then it works, and the mapping function must return a structure meeting the shape of `Fruit<apple>`.

If the appropriate generic types are explicitly provided, however, it also works. It just seems to try to best case guess `T` from all of its uses, and that best case almost always seems to be `{}` which means that this will always be broken...

Is this a problem related to the compiler picking the best common type/type inference for the generic, or am I wrong? (Also, sorry for opening so many issues recently, I'm building something new for work...)

**Comment by Roam-Cooper** [comment]
Found that this is related to https://github.com/Microsoft/TypeScript/issues/5254

**Comment by Roam-Cooper** [comment]
I feel like the only way to solve this is something like
```ts
let a: {} = { b: 1 };
```
Causing the error: `{ b: 1 } is not assignable to {} because b: number does not exist on {}`
But I have a funny feeling that this is already "working as intended"...

**Comment by mhegazy** [comment]
> But I have a funny feeling that this is already "working as intended"...

yup.  unfortunately , a type with no members ( i.e. `{}`), is a super type of all types. more in https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-all-types-assignable-to-empty-interfaces
