### ISSUE TITLE
for var key in object of interface should be keyof type

### ISSUE THREAD

**Issue by Gregroam** [Microsoft/TypeScript#15092]
**TypeScript Version:**  2.2.2

**Code**

```ts
interface MyInterface {
  a: number;
  b: string;
  c: boolean;
}

var myObj: MyInterface = {a: 5, b: "foo", c: true};

for (var key in myObj) {
    var getValue = myObj[key];
}
```

**Expected behavior:**
The var `key` should have type `keyof typeof myObj` evaluating to `'a' | 'b' | 'c'` instead of just `string`. This would then allow the use of `myObj[key]` without having to cast to any
ie `(myObj as any)[key]`

**Comment by DanielRosenwasser** [comment]
Unfortunately this wouldn't be appropriate behavior - if you have a subtype of `MyInterface` (i.e. a type that's *more* specific than `MyInterface`), then the keys of `myObj` actually grow, which gives you a *less* specific type.

So you might think that at runtime your keys are `a`, `b`, and `c`, but in reality you might also have a `d`, `e`, and `f` property as well.

See #12892 for a similar discussion.
