### ISSUE TITLE
Quick Info needs to have its size capped

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#1510]
I am all for showing more in Quick Info with overloads and such but we'll need a size limit. Try hovering over createElement:

![attachfilehandler](https://cloud.githubusercontent.com/assets/8000722/5460879/5e441f6c-851b-11e4-9029-406b8640bde5.png)

**Comment by danquirk** [comment]
It is, but you can imagine even formatted correctly with each overload signature on its own line this QuickInfo item is going to be 100+ lines long.

**Comment by sheetalkamat** [comment]
Handled by #24258

**Comment by weswigham** [comment]
Fixed by #24258
