### ISSUE TITLE
Support Object.<type1, type2>  JSDoc notation for index signatures 

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#15105]
From: https://github.com/Microsoft/vscode/issues/24291
**TypeScript Version:**  2.2.2

**Code**

```ts
/**
 * Test.
 *
 * @param {Object.<string, number>} obj An object.
 */
function func(obj) {
	console.log(obj);
}
```

**Expected behavior:**

`obj` has a type of `Object<string, number>` (at at least some equivalent type with an index signature). This syntax is valid according to http://usejsdoc.org/tags-type.html

**Actual behavior:**
`obj` has an `any` type

**Comment by yuit** [comment]
I think `{object}` and `{Object}` both should be `object` type and only object type is assignable to it. Because it is any at the moment, all kind of stuffs are allowed

**Comment by sandersn** [comment]
Fix is up at #17254

**Comment by michaeljota** [comment]
Should the fix work with `object.<string, T>` annotations or just with capitalized `Object.<string, T>`.

**Comment by sandersn** [comment]
The code currently only checks for `Object`, not `object`. But note that we treat `Object` as different from `object` in Javascript already: `Object` is a synonym for `any`, but `object` means "anything that's not number/boolean/string/null/undefined".

Feel free to open an issue and we can decide what the correct behaviour should be.

**Comment by michaeljota** [comment]
I understand that when is being used as a JSDoc annotation, `object` and `Object` should be treated as the same, but I may be wrong. I will try to post another issues with similarities on this.

**Comment by sandersn** [comment]
Yep, the current behaviour may be wrong because it is largely inherited from Typescript. A new issue to discuss it would be helpful so we can examine all the issues.

**Comment by michaeljota** [comment]
Done. 👍 Thanks you.
