### ISSUE TITLE
TypeScript combines JSDoc seperated comment blocks into one

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#15106]
_From @MartynasZilinskas on April 10, 2017 18:22_

- VSCode Version: v1.11.1

Steps to Reproduce:

1. 
```typescript
/**
 * Unnecessary JSDoc comment block
 * ===============================
 */

/**
 * Example function that returns 0.
 */
function Example() {
    return 0;
}
```
2.
![image](https://cloud.githubusercontent.com/assets/562658/24876092/13f64fbc-1e33-11e7-8961-53ec6bf3bf3c.png)

_Copied from original issue: Microsoft/vscode#24458_

**Comment by mjbvz** [comment]
Verified that this is not a VSCode specific issue. This behavior may be by-design, but it does seem unexpected

**Comment by mhegazy** [comment]
comments are attached to the declarations that follows them. this is how the comment system is built. changing that would not be simple,
