### ISSUE TITLE
Javascript Outlining Stops after a certain depth

### ISSUE THREAD

**Issue by paulvanbrenk** [Microsoft/TypeScript#15112]
Copied from  https://github.com/Microsoft/nodejstools/issues/1496

**Expected Behavior**
.JS files that belong to a NodeJS Tools project should have their outlining behave the same way as in other project types.
**Actual Behavior**
.JS files are outlined, but only to a certain "depth" or "level". After that, outlining stops until the depth is reduced again.

- NTVS Version: 1.3.41102.01 (11-02-2016 Dev Build)
- Visual Studio Version: 2015 Community
- Node.js Version: v4.4.5

**Steps to Reproduce**
Create 2 identical javascript files with the following contents, one under a NodeJSTools Project and one under a .csproj (you can copy paste the file from one project to another)
(function () {
    var a = {
        
    };

    (function () {
        var a = {

        };

        (function () {
            var a = {

            };

            (function () {
                var a = {

                };

                (function () {
                    //Outlining Stops here

                    var a = {

                    };

                    (function () {
                        var a = {

                        };

                        (function () {

                        });
                    });
                });
            });
        });
    });
})
2. In the file that lives under NodeJS Tools, the outlining will "give up" after reaching a certain depth:

![image](https://cloud.githubusercontent.com/assets/5273975/24887539/37119b5e-1e11-11e7-9c49-efde1edbc10f.png)

**Comment by mhegazy** [comment]
We do this intentionally to ensure the request ends in a timely fashion.
