### ISSUE TITLE
Can't add a property of MongoDB's Db type to node's global object

### ISSUE THREAD

**Issue by ctusch** [Microsoft/TypeScript#15110]
**TypeScript Version:**  2.2.1

**Code**

```ts
// file vendor.d.ts
/// <reference types="mongodb" />

declare namespace NodeJS{
  interface Global {
    db: Db
  }
}
```

**Expected behavior:**
I'd expect the code to compile and the `db` property of type `Db` to be available on node's `global` object (I do assign it in my main.ts).
**Actual behavior:**
I get the following compiler error: 
> vendor.d.ts(5,9): error TS2304: Cannot find name 'Db'.

Maybe I'm misunderstanding something but I haven't been able to find any more information and got no answer on [Stackoverflow](http://stackoverflow.com/questions/42754233/how-to-add-a-property-with-a-custom-type-to-nodes-global-interface).

**Comment by aluanhaddad** [comment]
I answered your question on Staclasses Overflow.

**Comment by ctusch** [comment]
Thank you!
