### ISSUE TITLE
Suggestion: extend union/intersection type combinations with negation

### ISSUE THREAD

**Issue by awto** [Microsoft/TypeScript#15117]
**Problem**

Working on a syntax translator, I have a huge number of interfaces representing AST nodes with a constant field to specify the exact type. And AST as a union of all node interfaces. 

There are quite a few passes to transform AST. Some of the passes add additional information, and some require some information to be present in AST nodes. To avoid keeping all the information in a single AST node type, we could use type combinators.

Say, with the AST:

```ts

type NodeA = { kind: "a", fieldA: number}
type NodeB = { kind: "b", fieldB: number}
type AST = NodeA | NodeB

```

And, say, there is a path adding `field2` to nodes with kind "b", without the negation combinator I would have to write something like this:

```ts

type NodeA = { kind: "a", fieldA: number}
type NodeB2 = NodeB & {field2: string}
type AST2 = NodeA | NodeB2

function transform1(a: AST): AST2;
```

If there is a huge number of AST nodes (literally hundreds in my project), writing AST unions for each pass would be hard. So we have to resort to use a single type keeping information about all fields and extend it while adding new passes. 

**Solution**

Add another type combinator to negate unions. As an example, say, I use `-` sign syntax extension.

```ts
function transform1(a: AST): (AST - {kind:"b"}) | NodeB & {field2: string};
```

if there is another pass requiring that `field2` field in `kind: "b"` I would just specify this like:

```ts
function transform1(a: (AST - {kind:"b"}) | NodeB & {field2: string}): AST;
```

Or with some type alias, but anyway, this makes the code self-documenting and provides more means to decouple not related parts.

Semantically this sounds pretty simple, during normalization of union/intersection combinators remove matching union arguments. And nothing to be done in next stages.

**Comment by aluanhaddad** [comment]
Possible duplicate of #4183

**Comment by awto** [comment]
thanks, indeed, closing this one
