### ISSUE TITLE
the ability to run typescript directly with node libraries?

### ISSUE THREAD

**Issue by calidion** [Microsoft/TypeScript#15118]
```ts
ts a.ts
```
can be executed just the same as 
```js
node a.js
```

**Comment by jesseschalken** [comment]
https://www.npmjs.com/package/ts-node

**Comment by calidion** [comment]
@jesseschalken 

thanks. but ts-node seems not sync with typescript language.

**Comment by calidion** [comment]
I have encountered a problem with ts-node which cannot compile files using Promise :

Cannot find global value 'Promise'. (2468)
An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option. (2705)

**Comment by calidion** [comment]
when i change target to es6, the error will be fixed.
but it would be better if it works even when target is es5.

**Comment by aluanhaddad** [comment]
Try this

```bash
> ts-node --compilerOptions '{"lib": ["es2015"]}'
```

**Comment by calidion** [comment]
@aluanhaddad 
thanks.  works with es5 now.

**Comment by robhobbes** [comment]
I found this project useful: https://www.npmjs.com/package/tsun

**Comment by blakeembrey** [comment]
@calidion The reason `ts-node` failed when targeting ES6 is that node doesn't understand some ES6 features (assuming you're using node >= 6, that feature was probably ES6 modules). If you really do want to execute ES6 code, you should set `module: commonjs` so it can be executed using node.
