### ISSUE TITLE
File comment lost when adjacent to certain statement types

### ISSUE THREAD

**Issue by evmar** [Microsoft/TypeScript#15127]
TypeScript has some logic that attempts to preserve the file-level comment at the top of the file.  However it does not work reliably -- if it's adjacent to a statement that works with types, then the comment is lost.

Experimentally, these cause the comment to be retained:

```js
/** Important copyright statement here. */
var x = 3;
```

```js
/** Important copyright statement here. */

type x = string;
```

```js
/** Important copyright statement here. */
import {x} from 'foo';
x;  // use x as a value
```

but these don't:

```js
/** Important copyright statement here. */
type x = string;
```

```js
/** Important copyright statement here. */
import {x} from 'foo';
```

**Comment by evmar** [comment]
See the tests named `copyrightWithNewline` and `copyrightWithoutNewline` for some tests that attempt to verify this, but they failed to cover all the cases.

**Comment by mprobst** [comment]
Actually taking a second look at https://github.com/Microsoft/TypeScript/blob/master/tests/baselines/reference/copyrightWithoutNewLine1.js, it seems this is indeed tested for. Not sure if it's intentional, but it seems very surprising to have a load bearing newline like that.

FYI if I search for all source files on github that contain `^/** ... */\n\n` vs all sources that contain `^/** ... */\n[^\n]`, I get 25,631,920 files with a single wrap after the file start comment (don't work in TS), and 21,073,377 with a double wrap (work in TS).

**Comment by yuit** [comment]
@evmar in your scenario, you are mainly talking about when `--removeComments` is true right? 

@evmar @mprobst  So the behavior in example is actually intended because we use that newline to differentiate copyright comment  (we called it detached comment) from being leading comment of the statement follow it (without newline those copyright will be considered leading comment and therefore will be removed when `--removeComments` is true)  That being says.. it may be make sense given @mprobst  data that we should also keep top-of-file comment (regardless if it is following by new line or not) that contains a signal word such as "copy-right". @CyrusNajmabadi any thought?

**Comment by evmar** [comment]
@yuit I don't think so; we use the default value of --removeComments, which I think is false.

In our particular case our files don't contain the word "copyright" in the file-level comment.

Within Google we worked around this via a tslint check, which checks that if the ts.SourceFile has leading comments that they end with \n\n.

**Comment by CyrusNajmabadi** [comment]
AFAIK, this is 'by design'.  Comments are inherently ambiguous.  We use simple heuristics to distinguish things and those heuristics will invariably not work all the time.  After all, what do you when you have the following two pieces of code:

```ts
/** i am a copyright! */
function foo() { }
```

and

```ts
/** i am not a copyright! */
function foo() { }
```

?

**Comment by CyrusNajmabadi** [comment]
Because of this, we ask that you supply enough information to help guide the TS compiler.  A simple newline helps us distinguish between a comment you intend to apply to the entire file, vs a comment you intend for the first construct.

**Comment by CyrusNajmabadi** [comment]
> that we should also keep top-of-file comment (regardless if it is following by new line or not) that contains a signal word such as "Copyright". @CyrusNajmabadi any thought?

I would avoid anything like this.  It's just going to make for a more complex, and harder to understand heuristic.

**Comment by evmar** [comment]
I agree with your general point.  I also agree that making this logic even more complex will make things more confusing.

But in practice the resulting behavior is very confusing from a user's perspective -- depending on whether your first line is interpreted as a statement about types or values, a comment is either retained or dropped depending on the whitespace after it.

So you might consider is some sort of special handling around the very first comment in the file, if it is ambiguously attached to either the ts.SourceFile or the first statement.  (I appreciate that it is unambiguous from the compiler's perspective, but it is very uncommon for users to write comments on imports so the TS parse of it is usually wrong.)

**Comment by CyrusNajmabadi** [comment]
> so the TS parse of it is usually wrong

Just wanted to comment on this.  One of the core goals of the Roslyn approach to parsing (which TS has somewhat modeled itself after) is that parsing does not try to make these sort of semantic distinctions.  Instead, it tries to have a consistent set of rules that it follows uniformly.  This ensures that later layers don't have to know the ins and outs of how the parser did things.

A core example of that is how we treat 'trivia' (i.e. comments and whitespace).  Trivia follows strict rules that layers can depend on.  Namely that it is 'attached' to the next real token in the file (Roslyn C#/VB is slightly different, but equally consistent).  

We've had systems in the past that attempted to do things differently, and it just made later portions of our compilers (and especially our language services) much more difficult as they would have to know about all the special cases.  When we did our new system we explicitly wanted to avoid all that complexity, even if it does mean you may end up in situations where the resultant parse isn't exactly what some consumer might prefer.

**Comment by yuit** [comment]
@CyrusNajmabadi thanks for your feedback and explanation @evmar I agree that this behavior is a bit unexpected and I am going to add additional documentation on this topic related to comment so that there will be less confusing

**Comment by evmar** [comment]
I coincidentally stumbled across this code in TypeScript that special-cases some of this already, was a surprise to me!  It turns out TS is working around exactly this issue but only for certain forms of comments.

https://github.com/Microsoft/TypeScript/blob/977525b37ea7648e87044be8d72c8fdffa78c373/src/compiler/comments.ts#L245

**Comment by evmar** [comment]
```
              // If the node will not be emitted in JS, remove all the comments(normal, pinned and ///) associated with the node,
                // unless it is a triple slash comment at the top of the file.
                // For Example:
                //      /// <reference-path ...>
                //      declare var x;
                //      /// <reference-path ...>
                //      interface F {}
                //  The first /// will NOT be removed while the second one will be removed even though both node will not be emitted
```

**Comment by CyrusNajmabadi** [comment]
Yes.  These comments have specific meaning to TypeScript and thus are specially handled.  You can think of them similarly to #pragmas.

**Comment by evmar** [comment]
Would it make sense for us to always use /// for file-level comments?

**Comment by CyrusNajmabadi** [comment]
I don't see why.  We already have a good system for file-level comments.  Just put a top level comment and a single newline.
