### ISSUE TITLE
npm up => 2.3.0 is installed

### ISSUE THREAD

**Issue by larsenwork** [Microsoft/TypeScript#15125]
**TypeScript Version:**  2.2.2

**Code**

```terminal
npm up
```

**Expected behavior:**
Install typescript 2.2.2 since we have uptick 2.2.0 in pkg json

**Actual behavior:**
Installs typescript 2.3.0

![screen shot](https://cloud.githubusercontent.com/assets/3859425/24909448/3ed9986a-1ec4-11e7-98d2-1b015f3fa5c9.png)

**Comment by pscanf** [comment]
Having the same "problem". But indeed there seems to be a `2.3.0` version published on npm (output from `npm info typescript`):

<img width="418" alt="screenshot 2017-04-11 15 01 23" src="https://cloud.githubusercontent.com/assets/3725458/24910429/0594a0f0-1ec8-11e7-8283-ef000c632c7f.png">

**Comment by RyanCavanaugh** [comment]
Well, we screwed that one up. I don't think we can do anything about it now, though.

**Comment by RyanCavanaugh** [comment]
@DanielRosenwasser for future releases we need prereleases to have prerelease tags in their versions so this doesn't happen. Not updating `@latest` isn't enough.

**Comment by tsvetomir** [comment]
Looks like there's a similar issue with 2.4.0 :(

```
   { latest: '2.3.4',
     next: '2.5.0-dev.20170613',
     beta: '2.0.0',
     rc: '2.4.0',
     insiders: '2.3.3-insiders.20170512' },
```

**Comment by larsenwork** [comment]
@tsvetomir indeed — had to do `npm install typescript@2.3.4` to make it work this morning.

**Comment by tsvetomir** [comment]
For the time being, use the "~2.3.0" semver range.
