### ISSUE TITLE
Using the compiler API to list all the (inherited) members of a type?

### ISSUE THREAD

**Issue by kevinder** [Microsoft/TypeScript#15147]
For each interface, intersection type, or type literal, I'm trying to print all of their members as well as indicating whether that member is inherited from a different type.

I've got this working via the compiler API by building a program out of a set of source files and traversing the nodes in the AST. I'm getting the members of each node by using `TypeChecker.getPropertiesOfType()`. The problem I'm running into is that if a node's subtree involves types that are imported from another file, this function returns an empty array.

In this example, the program correctly lists `a` as a property of `B:`
```
export type A = {
    a: boolean;
}
export type B = A;
```

but not if `A` and `B` are in different files:

```
// other.ts
export type A = {
    a: boolean;
}

// main.ts
import * as Other from "other";
export type B = Other.A;
```

Is there a more suitable function other than `TypeChecker.getPropertiesOfType()` to use, or otherwise is there a different overall approach to make this work?

**Comment by andy-ms** [comment]
You are probably getting compile errors. TypeScript won't throw an exception, but they can be shown like so:

```ts
function debugPrintErrors(program: ts.Program): void {
    const diagnostics = ts.getPreEmitDiagnostics(program);
    for (const diag of diagnostics) {
        console.error(ts.flattenDiagnosticMessageText(diag.messageText, "\n"));
    }
}
```

You might want to use [`--traceResolution`](http://www.typescriptlang.org/docs/handbook/compiler-options.html) because this looks like a module resolution error. Try importing from `"./other"`.

**Comment by kevinder** [comment]
@andy-ms you were right - thanks!

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
