### ISSUE TITLE
Merged class namespace types not visible from a subclass

### ISSUE THREAD

**Issue by sccolbert** [microsoft/TypeScript#15159]
**TypeScript Version:**  2.2.1 

I have a namespace merged with a class. This namespace has exported types as well as values. The exported values are accessible from (inherited by) derived subclasses, but the exported types are not. I can't seem to find anything about this in the language spec, but my intuition is that the types would be inherited as well, unless overridden by the subclass.

```ts
class Foo {
  a: number;
}

namespace Foo {
  export interface IStuff {
    thing: string;
  }
  export class Data {
    value = 'data';
  }
  export const apple = 42;
}


class Bar extends Foo {
  b: number;
}

namespace Bar {

}


let stuff: Bar.IStuff;       // not okay: "Namespace 'Bar' has no exported member 'IStuff'."
let data: Bar.Data;          // not okay: "Namespace 'Bar' has no exported member 'Data'."
let data2 = new Bar.Data();  // okay `data2` has type 'Foo.Data'
let apple = Bar.apple;       // also okay
```

**Comment by krryan** [comment]
I don't think there's support for types inside classes to begin with, which is probably why this is happening. Personally, I would certainly appreciate _that_ feature.

**Comment by mhegazy** [comment]
I am not sure why we even support `Bar.apple` as a value..

**Comment by RyanCavanaugh** [comment]
This would be a breaking change if modified -- it's legal to declare a new `IStuff` inside `Bar` today and that already has a meaning; we can't change it now.
