### ISSUE TITLE
Bad error message when importing empty namespace

### ISSUE THREAD

**Issue by evmar** [Microsoft/TypeScript#15155]
In `foo.d.ts`:
```js
declare module 'x' {
  namespace z {}
  export = z;
}
```

In `bar.ts`:
```js
import * as foo from 'x';
foo.bar();
```

Running tsc (2.2):
```
bar.ts(2,1): error TS2304: Cannot find name 'foo'.
```

I think `foo` exists, it's really just missing a `bar` attribute?

**Comment by RyanCavanaugh** [comment]
There's no *value* named `foo`, just a namespace, because there are no values in the `namespace z { }` declaration.

In other cases like this we issue a more useful error message, we should do the same here.
