### ISSUE TITLE
JavaScript Class Prototype Assignment not Recognized for IntelliSense

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#15163]
From http://stackoverflow.com/questions/43354977/how-can-i-make-intellisense-reference-a-js-file-in-another-folder

**TypeScript Version:**  2.2.2

**Code**

```ts
/**
 * @class
 */
function MyClass() { this.xyz = 1; }
MyClass.prototype = { abc: 2 };

const x = new MyClass()
```

**Expected behavior:**
Suggestions on `x` know about the property `xyz` from the class itself, and `abc` from the `prototype`

**Actual behavior:**
Only a suggestion for `xyz` is shown

**Comment by sandersn** [comment]
Note that this works for `var MyClass = function { this.xyz = 1; }`! The compiler's special-case for a combined definition just assumes that it only happens with function expressions, not with function declarations.
