### ISSUE TITLE
TS2134 build error for 2 isolated TS files (shouldn't conflict)

### ISSUE THREAD

**Issue by jt000** [Microsoft/TypeScript#1516]
This is related to borisyankov/DefinitelyTyped#2734
See repo at https://github.com/jt000/RepoForTypescriptBuildIssue

The issue is that in a single project I have two TS files that are for separate scenarios, which don't overlap in functionality (common for nodejs projects that have client, server, and test code in one project). Since there is a commonly named variable with different types the typescript compiler throws the TS2134 build error. However, since neither TS files share common references this should be allowed.

**Comment by tigerswithguitars** [comment]
+1 would be nice if VS ext could understand the references paths.

**Comment by mhegazy** [comment]
@jt000 sorry the delayed response, this fell off my radar during the holidays. 

> we have angular-protractor which exposes a $ var and jquery which also exposes a $ var of a different type. Since they will never be used in the same context, then there should be a way to get this to work without an error message when they are in the same Visual Studio project.

If they are never used together in a single application then they should not be passed to the compiler in a single compilation. you can still share your common files using /// references. this way if you ever mistakenly use $ from jQuery in the project that does not use jQuery the compiler will be able to alert you to that instead of silently failing.

so my suggestion is simply use two projects. for instance, if you have two projects (webpage1, webpage2) where both use jQuery.d.ts, and another not related one that does not. 

+ jQuery.d.ts
+ common.ts
+ webpage1.ts
+ webpage2.ts
+ anotherNotRelatedPage.ts

in webpage1.ts, webPage2.ts you add /// <reference path="jQuery.d.ts"/> and /// <reference path="common.ts" />

and call the compiler using:
```
tsc webpage1.ts webpage2.ts
```

and in anotherNotRelatedPage.ts add a reference to /// <reference path="common.ts" />

and call the compiler using:
```
tsc anotherNotRelatedPage.ts
```

this way you have two "contexts", and you are still sharing common.ts


you can do that in VS as well, just create two projects.

**Comment by jt000** [comment]
Thanks @mhegazy for the reply. 

Applications make sense in a desktop environment, but when working with javascript what constitutes an "application"? Each Node.js project? Each page that's hosted in a site? Each different entry-point for "npm start *x*"? Javascript is extremely flexible in how it is loaded & run and I don't think its fair to say that there is even a single application even for the same JS file.

What you suggest for having multiple projects is a fair workaround, but I don't think it would be what you'd want to suggest as a de facto process for creating typescript files. When using CommonJS or Require each TS file should theoretically have their own context, which would suggest they need to be in their own project. This would get unmanageable very quickly... Or you could create them all in the same context until you ran into a conflict, then pull it out into its own project, but this isn't really the best user experience. It would be much better to have a solution for this built into VS build for typescript.

The way I've resolved this was to remove VS from the equation entirely and instead used Gulp within WebStorm, so that I can define what my own contexts are without creating new projects. This allows me to use multiple tsc.d.ts files within the same "project" and even recompile multiple flavors of my end JS file. (i.e. compile A.ts, B.ts, D.ts into "DPage.js", compile A.ts, B.ts, C.ts into "CPage.js"). I would be surprised if there wasn't a way to design the VS build for typescript to do something similar (i.e. using VS project item properties, maybe).

As a ex-Microsoft employee, I'd love to help you understand my scenario so you can improve the VS building of TS files and ensure more people in the future don't migrate to WebStorm or other IDEs for their Typescript development environment... This isn't blocking for me, but I would like to get back to supporting Visual Studio (it's such a great IDE). *(Feel free to send me an email if you'd prefer to speak offline)*

**Comment by NoelAbrahams** [comment]
> What you suggest for having multiple projects is a fair workaround, but I don't think it would be what you'd want to suggest as a de facto process for creating typescript files

Why not? The idea of having a project context for individual files (or tiny collections of them) seems rather strange and will not scale at all.

> Or you could create them all in the same context until you ran into a conflict, then pull it out into its own project, but this isn't really the best user experience.

That's a somewhat ad-hoc approach. Each project is a logical and physical container for related files. Their composition should be planned out in advance.

**Comment by mhegazy** [comment]
So external modules, whether commonJS or require (AMD) are nice in the sense that they declare dependencies and do not pollute the global namespace. So these can all be in the same project and the compiler would know what dependencies they need and they will not cause conflicting definitions, etc.. and the compiler will emit each to its file. this this is sort of a happy scenario. i would just lump all node modules in one project for instance, unless you are building them with different configurations (e.g. --noImplictAny for some but not others).

The problem arises from JS files that would be included in an html page in script tags, these can affect each other, and the compiler here has two options, either 1. do not bother when it sees a conflicting definition of the same variable or a use of an undefined global, or 2. complain. I think the second option is generally more helpful.

I understand that adding a project file for every entry point may be a lot of work. for this we have added support for tsconfig (#1667), which we plan to support in VS as well. Using tsconfig, you would divide your code base in folders for instance, and you would add a tsconfig.json to each folder representing a website for instance (i.e. all scripts that are expected to live together) including shared files. the tsconfig file can be empty, no need to list your files unlike a project file, it implicitly include all files from the folder. In VS you just open a file, and VS will figure out which tsconfig file to load and what other files are part of this context and will load them for you. 

I think this should work well in your scenario with no project creation/management, then you can wire your gulp/grunt build to use tsconfig and you will be all set.

I would be happy to get more feedback about your specific scenario and we definitely appreciate your input.

**Comment by jt000** [comment]
Thanks @mhegazy for taking the time to understand the scenario and for the write-up. I was unaware of the [tsconfig](#1667) feature you added. Once there is support for that in VS, then I think this will help resolve borisyankov/DefinitelyTyped#2734 by making it easier to have both client & server TS files (or test & production TS files) in the same project which is very common in node.js projects.

Is VS support of #1667 planned?

**Comment by mhegazy** [comment]
Yes. Hopefully in the next release.

**Comment by NoelAbrahams** [comment]
@mhegazy,

>  the tsconfig file can be empty, no need to list your files unlike a project file, it implicitly include all files from the folder

I believe this is true, provided no files have been added to the `files` property. Can the logic be extended to the following:

> tsconfig implicitly includes all files from the folder, provided no files ***from the active directory*** (or subdirectories) have been specified. If files from the active directory or subdirectories have been added then only those files will be included. ***External references*** are not included in the calculation.

So, it should be possible to say: "Include external reference `...\foo\bar\baz.ts` and all files from the active directory and subdirectories."

This would cater for having code in multiple projects, with references between them.

Without this caveat it will be difficult to convert our current source tree to use `tsconfig`.

**Comment by mhegazy** [comment]
@NoelAbrahams can you provide more details and why combing tsconfig with no files is not sufficient for you (combined with ///references to externals)?
It sounds like you want glob support in files, something like ./**/*.ts, is that correct?

**Comment by jt000** [comment]
Are these comments for #1667 or do they relate to this issue somehow?

**Comment by NoelAbrahams** [comment]
@mhegazy,

I want to add external references, but not have to list all the files in the current project.

(@jt100, it's probably more related to the other issue - sorry for mucking up your issue!)

**Comment by mhegazy** [comment]
@NoelAbrahams why not add a /// reference in one of your files?

**Comment by NoelAbrahams** [comment]
We're hoping to get rid of `///reference` altogether. `tsconfig` is a nice solution.  Just shouldn't create more work.
