### ISSUE TITLE
"Warning: Cannot read property 'resolvedReturnType' of undefined"

### ISSUE THREAD

**Issue by Kovensky** [Microsoft/TypeScript#15166]
**TypeScript Version:**  2.3.0

Running a webpack build with typescript 2.3.0 prints to the console `Warning: Cannot read property 'resolvedReturnType' of undefined`.

I am unsure of the cause, as there is no stack trace when this happens -- it appears as just a simple `console.log` line during the build. Searching for "resolvedReturnType" in my node_modules folder only shows results inside typescript itself.

As for third party libraries that do use the typescript API, I am using awesome-typescript-loader and tslint-loader with tslint ^5.0. Is this perhaps an API change in 2.3.0?

EDIT: looks like that is not the only suspicious warning; saw a `Warning: Cannot read property 'getStart' of undefined` later on. I wonder what's to blame...

**Comment by ajafff** [comment]
I guess that's coming from tslint. Unfortunately it only prints the message of the exception and doesn't show the stack trace

**Comment by RyanCavanaugh** [comment]
Indeed that's how tslint prints exceptions that occur during lint, so it's likely a TSLint issue. If you can at least narrow it down to the rule + file that produces the exception, we can take a look

**Comment by Kovensky** [comment]
I've found the `console.warn` in tslint's `linter.js` and edited it to print the file / stack trace.

The stack trace is like:

```
TypeError: Cannot read property 'resolvedReturnType' of undefined
    at Object.getReturnTypeOfSignature (.../node_modules/typescript/lib/typescript.js:31019:27)
    at getReturnKind (.../node_modules/tslint/lib/rules/returnUndefinedRule.js:120:30)
    at check (.../node_modules/tslint/lib/rules/returnUndefinedRule.js:76:34)
```

However, the file that triggers it is pretty large so it's hard to isolate the actual cause; I'll investigate it more.

The other error was:

```
TypeError: Cannot read property 'getStart' of undefined
  at JsxAlignmentWalker.getLineAndCharacter (.../node_modules/tslint-react/rules/jsxAlignmentRule.js:128:61)
  at JsxAlignmentWalker._this.getCharacter (.../node_modules/tslint-react/rules/jsxAlignmentRule.js:52:61)
  at JsxAlignmentWalker.checkElement (.../node_modules/tslint-react/rules/jsxAlignmentRule.js:80:39)
```

At any rate, it seems that at least the second one is unrelated to typescript itself.

**Comment by Kovensky** [comment]
It seems the following snippet triggers the `resolvedReturnType` crash:

```
import $ from 'jquery'

$.Deferred()
.done(foo => {
  if (!foo) {
    return
  }
})
```

I'll report it on tslint.

**Comment by Kovensky** [comment]
The `getStart` error is an actual API change in TS 2.3, which I guess was added by https://github.com/Microsoft/TypeScript/commit/41108dba

https://github.com/palantir/tslint-react/issues/87
