### ISSUE TITLE
Type 'Subscription' is not assignable to type 'Subscription'

### ISSUE THREAD

**Issue by cozzbie** [Microsoft/TypeScript#15167]
**TypeScript Version:** 

2.2.2

**Code:**

```ts
private ts:Subscription
this.ts = Keyboard.onKeyboardShow().subscribe(e => this.onShow(e));

```
**Expected behavior:**

Should work with no errors

**Actual behavior:**
Throws error

`Type 'Subscription' is not assignable to type 'Subscription'. Two different types with this name exist, but they are unrelated. Property '_parent' is missing in type 'Subscription'.`

**Notes:**

This just started happening after I upgraded Angular to 2.2.2 and rxjs to 5.1.1

**Comment by RyanCavanaugh** [comment]
Please provide a self-contained repro. We don't maintain the Angular or rxjs definition files, nor can we see your code

**Comment by marek1** [comment]
+1

**Comment by rodriguesgm** [comment]
same to me

**Comment by mhegazy** [comment]
@marek1 and @rodriguesgm please provide a self-contained repro we can use to investigate, otherwise, i am afraid this issue is not actionable for us.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Comment by metalraf** [comment]
i have same problem with videogular2 im trying to getisHidden status 
this.subscriptions.push(this.hidden.isHidden.subscribe(this.onHideControls.bind(this)));

error Type 'Subscription' is not assignable to type 'Subscription' 
Property '_parent' is missing in type  'Subsciption'

**Comment by vanillabridge** [comment]
I solved this problem by downgrading rxjs to 5.0.1

**Comment by GonzoBard** [comment]
I suddenly had the exact same problem in the code that had worked successfully before.
I just deleted import:
`import {Subscription} from 'rxjs/Subscription';`
re-imported and the error did not appear

**Comment by chalcrow** [comment]
Thanks @GonzoBard this was also my issue. I had the following import:

`import { Observable, Subscription } from 'rxjs/Rx';`

I had to delete this line, save the .ts file, re-add the line and save again, and this fixed the errors (deleting only 'Subscription' from the import didn't work - I had to remove and re-add the whole line)

**Comment by ganqqwerty** [comment]
Seems like angular v8 is guilty in that error as well. Downgrading rxjs to "rxjs": "6.4.0" helped me.

**Comment by pflugich** [comment]
Had the same problem and found this solution on [stackoverflow:](https://stackoverflow.com/a/52412329/4235777)

>So, I'm not sure why this worked but I'm answering my own question just in case someone else runs into this issue.
>
>I uninstalled rxjs
>I re-installed rxjs
>I deleted my node_modules folder
>I deleted my package-lock.json
>I ran npm clean cache --force
>I ran npm install
>Then everything started working again :)

**Comment by vitaly-t** [comment]
I'm using Angular 8.1, and the same issues cropped up.

Use of the exact following declaration solved the issue:

```ts
import {Subscription} from 'rxjs';
```

This imports the type from Angular declarations, so somehow the conflict isn't there anymore.
