### ISSUE TITLE
isNaN only takes number and does not implement typeguard

### ISSUE THREAD

**Issue by npenin** [Microsoft/TypeScript#15173]
**TypeScript Version:**  2.2.2

**Code**

```ts
var obj='1'

if(!isNaN(obj))
{
   ///here obj should be a number or equivalent
}
```

**Expected behavior:**
- isNaN should take any kind of data, not only numbers
- isNaN should implement typeguards so that in the if statement, obj is considered as a number or equivalent

**Actual behavior:**
- isNaN(obj) breaks on compilation

**Comment by RyanCavanaugh** [comment]
#12302 / #13227

Please search before logging new issues, both of the things here have been covered before
![image](https://cloud.githubusercontent.com/assets/6685088/25009767/acb736fe-201c-11e7-84ea-830890e60e54.png)
