### ISSUE TITLE
Export and import of module is not working

### ISSUE THREAD

**Issue by Nanda-Nandan** [Microsoft/TypeScript#15188]
TypeScript Version:  2.0
Project structure in file explorer:-  src->Microsoft.OrgUse.Client->app1.ts,app2.ts
					 ->Microsoft.Orguse.Tests->app1Test.ts
In app1.ts my code is like
```ts
 module Microsoft.OrgUse.Client
{
	export class ContactPersons
	{}
}
```
and in app2.ts my code is like
```ts
module Microsoft.OrgUse.Client
{
	export Class KeyMembers
	{}
}
```

if i want to use both classes in other project in this case in my test project
then i have to import it in my app1Test.ts file
But if i want to import it as-
```ts
import * as contact from "Microsoft.OrgUse.Client.ContactCard"
```
then it is throwing error "is not module"
if i modified app1.ts code and added at last
```ts
export
{
Microsoft.OrgUse.Client
}
```
then it is giving error as compiler treating Microsoft as module and Orguse as nested module.
so i removed the export code and tried to find out something in d.ts file
generated d.ts file of app1.ts and app2.ts combinely is like

```ts
declare module Microsoft.OrgUse.Client {
    class ContactPersons {        
    }
}
declare module Microsoft.OrgUse.Client {
    class ContactPersons {        
    }
}
```
if I changed it by adding some code segment at last like
```ts
declare var client: Microsoft.OrgUse.Client.ContactPersons
declare module "SomeClient"
{
export = client;
}
```

and in my apptest.ts if i am importing like 
```ts
import * as contact from "SomeClient" 
```
then it is able to import but how to make it achieve through ts compiler means it should be generated automatically in d.ts

**Comment by Nanda-Nandan** [comment]
@mhegazy @RyanCavanaugh Could you please help me in this.Thank you guys.FYI TypeScriptModuleKind IS AMD

**Comment by aluanhaddad** [comment]
@Nanda-Nandan You are mixing and matching _namespaces_ and _modules_, two extremely different forms of code organization. They can, indeed be mixed, although it is best to stick to one or the other.

Part of the reason this confusion occurs is that JavaScript evolves very rapidly and both the patterns, and importantly the terminology for those patterns, has changed dramatically compared to what was common when TypeScript was first introduced.

To clarify the following code expresses its structure via _namespaces_.
```ts
module Microsoft.OrgUse.Client {
  export class ContactPersons { }
}
```
These used to be called _internal_ modules, and were expressed in with the `module` keyword syntax. The `namespace` keyword has the exact same semantics and was introduced purely to disambiguate what comes next. (Never use the `module` keyword to declare a `namespace`)

the following code expresses its structure via _modules_.
```ts
import * as contact from "Microsoft.OrgUse.Client.ContactCard";
export ...
```
These used to be called _external_ modules but now they are simply called modules. The new nomenclature aligns with the _modern_ meaning of the term module in JavaScript. Importantly the `module` keyword is not used here because the _file_ is the _module_.

So how does this information help you solve your problem?

Namespace based patterns, which again look like
```ts
// module keyword could be used but should not be for reasons listed above (same meaning)
namespace things { // NO export here.
  export class Something { }
}
```
introduce global variables, here a single global `things`.

Module based pattern, which again look like
```ts
// import and export, used at top level, make this file a module
import {Something} from "something"; // imports from another MODULE
export class SomethingElse {
  something = new Something();
}
```
The error message
> "Microsoft.OrgUse.Client.ContactCard" is not module.

is correct. That file does not contain a module, it contains a _namespace_.

How to resolve this (short term):

**app1.ts**
```ts
namespace Microsoft.OrgUse.Client { //  use namespace for clarity
  export class ContactPersons { }
}
```
**app2.ts**
```ts
// creates a global `Microsoft` variable, or adds members to it if it already exists
namespace Microsoft.OrgUse.Client { // use namespace keyword for clarity
  export class KeyMembers { }
}
```

**app1Test.ts**
```ts
// a MODULE by defintion (has top level import)
import "app1"; // imports the "app1.ts" defining the global variable, Microsoft via namespace
import "app2"; // imports the "app2.ts" contributing to global variable, Microsoft via namespace

const contacts = new Microsoft.Microsoft.OrgUse.Client.ContactPersons(); // refers to the global
```

**Comment by Nanda-Nandan** [comment]
@aluanhaddad Thanks for reply.
First thing i have tried with namespaces with doing same things i have explained before,it was not working,but i didnt try with global variable concept.

how i can introduce a global variable which will be having my namespace inside one project and i can use it in other project?                                                                                                                                                          
 In app1Test.ts you just imported it like import "app1".How it will import ts file of one project to another .Do i have to specify the relative path here?

**Comment by aluanhaddad** [comment]
Use relative paths. I updated my example to use relative paths.
Make sure RequireJS (or whatever AMD loader you happen to be using) can find them, and it will work.
Also checkout the documentation on the `compilerOptions.{paths, baseUrl}` options.

> how i can introduce a global variable which will be having my namespace inside one project and i can use it in other project?

By importing the file
```ts
import "some/relative/or-absolute/path";
```
_Long term, you will want to migrate your whole application to use modules._

That means the current **app1.ts**
```ts
namespace Microsoft.OrgUse.Client {
  export class ContactPersons { }
}
```
will become
**microsoft/org-use/client.ts**
```ts
export class ContactPersons { }
```
and that the current
**app1Test.ts**
```ts
import "./app1"; // imports the "app1.ts" defining the global variable, Microsoft via namespace
import "./app2"; // imports the "app2.ts" contributing to global variable, Microsoft via namespace

const contacts = new Microsoft.Microsoft.OrgUse.Client.ContactPersons(); // refers to the global
```
will become
```ts
import {ContactPersons} from "./microsoft/org-use/client";

const contacts = new ContactPersons();
```

**Comment by Nanda-Nandan** [comment]
I tried with the solution you have suggested still i got tsc compilation error:-
"Build:File 'D:/Solutions/src/Microsoft.OrgUse.Client/app1.ts' is not under 'rootDir' 'D:\Solutions\src\Microsoft.Orguse.Tests'. 'rootDir' is expected to contain all source files.	"
I am assuming you have considered test project and client project are different and their directory structure is parallel with each other but inside src directory.

Since i am using MSBuild there is no option for paths property that u have suggested to check.

**Comment by aluanhaddad** [comment]
I think you _can_ use paths with MSbuild, you probably just need to update MSBuild.
>I am assuming you have considered test project and client project are different and their directory structure is parallel with each other but inside src directory.

Quick fix? Just move the tsconfig.json file up a directory, so that it is shared, or use multiple tsconfigs, or create a minimal `package.json` (setting "main")  files in each subdirectory and link them directory or something (depends on Loader), or ... there are so many ways to achieve this.

**Comment by Nanda-Nandan** [comment]
@aluanhaddad  i am using msbuild typescript package.so i am not using any tsconfig.json.i am setting necessary configs inside target and my target is like below



<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
<Import Project="$(MSBuildBinPath)\Microsoft.CSharp.targets" />
	<PropertyGroup>
		<TSOutputDir>$(OutputPath)ts</TSOutputDir>
    <TypeScriptOutDir>$(TSOutputDir)\$(RootNamespace)</TypeScriptOutDir>
  <TypeScriptOutFile></TypeScriptOutFile>
	</PropertyGroup>

	<PropertyGroup>


		<TypeScriptCompileOnSaveEnabled>false</TypeScriptCompileOnSaveEnabled>
		<TypeScriptToolsVersion>2.0</TypeScriptToolsVersion>
		<TypeScriptNoImplicitAny>true</TypeScriptNoImplicitAny>
		<TypeScriptStripInternal>true</TypeScriptStripInternal>
		<TypeScriptRootDir>$(MSBuildProjectDirectory)</TypeScriptRootDir>
		<TypeScriptDropTypingDeclaration >false</TypeScriptDropTypingDeclaration>
		<TypeScriptGeneratesDeclarations Condition="'$(TypeScriptDropTypingDeclaration)' == 'true'">$(TypeScriptDropTypingDeclaration)</TypeScriptGeneratesDeclarations>
		
		<TypeScriptExtPath>$(PKG_TYPESCRIPT_MSBUILD)\tools</TypeScriptExtPath>
		<TypeScriptBuildPath>$(TypeScriptExtPath)</TypeScriptBuildPath>
		<TypeScriptJSXEmit>react</TypeScriptJSXEmit>
		<TypeScriptExperimentalDecorators>true</TypeScriptExperimentalDecorators>
		<TscToolPath Condition="'$(TscToolPath)' == ''">$(TypeScriptExtPath)\tsc</TscToolPath>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)' == 'Debug'">
		<TypeScriptTarget>ES5</TypeScriptTarget>
		<TypeScriptRemoveComments>false</TypeScriptRemoveComments>
		<TypeScriptSourceMap Condition="'$(TypeScriptSourceMap)' == ''">false</TypeScriptSourceMap>
		<TypeScriptModuleKind>AMD</TypeScriptModuleKind>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)' == 'Release'">
		<TypeScriptTarget>ES5</TypeScriptTarget>
		<TypeScriptRemoveComments>true</TypeScriptRemoveComments>
		<TypeScriptSourceMap>false</TypeScriptSourceMap>
		<TypeScriptModuleKind>AMD</TypeScriptModuleKind>
	</PropertyGroup>

	<PropertyGroup>
		
		<NoWarn>2008</NoWarn>
	</PropertyGroup>





	<UsingTask TaskName="TypeScript.Tasks.VsTsc" AssemblyFile="$(TypeScriptBuildPath)\TypeScript.Tasks.dll" />
	<Import Project="$(TypeScriptBuildPath)\Microsoft.TypeScript.targets" Condition="Exists($(PKG_TYPESCRIPT_MSBUILD))"/>


	

</Project>

and TypeScriptBuildPath is configured to D:\Solutions\Packages\Microsoft.TypeScript.MSBuild.2.0.6

**Comment by aluanhaddad** [comment]
I think there's a more recent MSBuild package. VS supports higher toolsversion that 2.0

**Comment by Nanda-Nandan** [comment]
it is there,but Path is not supported as Typescript documentation.And my question is if there is upgraded package also,Is it resolving the error that i have mentioned in previous comment about rootdir

**Comment by aluanhaddad** [comment]
As I said earlier, you can create additional package.json files in each project, heck just restructure your directories, etc. None of these require `"paths"` but if you are using ```--module AMD``` (or `--module system`), you will want/need paths sooner or later as most of the world, present company excepted of course, continues to reject every module format besides CommonJS (I am including ES Modules because they are most often compiled to CommonJS, breaking their semantics).

My intention was to explain the semantic errors caused by the conflation of `modules` and `namespaces`, provide historical context on how these errors became common place, and set you on the recommended path.

All of this assumed you were running TypeScript 2.0, something stated in the OP. TypeScript 2.0 supports paths, but again you do not need paths.

I do not have sufficient MSBuild knowledge as it pertains to TypeScript to aid you further.

**Comment by Nanda-Nandan** [comment]
Thanks for the suggestion,but I no need to add package.json for each directory, because there is a different project with same structure using msbuild working fine,but difference is their it is not using namespace and exporting class and function directly but in this case I am exporting namespace. Without adding package.json is it possible??

**Comment by Nanda-Nandan** [comment]
@aluanhaddad @mhegazy @RyanCavanaugh can i achieve it through d.ts??

**Comment by mhegazy** [comment]
I do not think you should mix namespaces and modules. if you are organizing your code as global namespaces, then do not use `import`;  if you are using modules, do not use global namespaces.

Just to be clear ` module Microsoft.OrgUse.Client` is a namespace.  you can find more information about this in http://www.typescriptlang.org/docs/handbook/namespaces-and-modules.html

**Comment by Nanda-Nandan** [comment]
@mhegazy I understood we cant mix namespaces and modules.But there are scenarios where we have to use some libraries which are defined as module and our project will be consisting of namespace.In that case we have to use two formats import and reference.Is it best practice??

**Comment by mhegazy** [comment]
If understand correctly, your have a compilation unit that is in global namespaces today; you want to expose it to another compilation as a single module, is this accurate?

if so, I would recommend building the first using `--outFile`, and `--declaration`; then have a post build script that modifies your declaration file to be a module (i.e. adding `export =  Microsoft.OrgUse.Client;`) at the bottom of your .d.ts file; pass this .d.ts file to your second compilation and you should be able to import it as a module.

**Comment by Nanda-Nandan** [comment]
@mhegazy Your understanding is correct.But adding the statement export=Microsoft.OrgUse.Client is making the compilation error of intellisence gone.But after building it is displaying error cannot find module ''.

**Comment by Nanda-Nandan** [comment]
@mhegazy I think we can modify the declaration file and make it as module but in .js file of declaration file is not changed according,thats why it is not getting module while building.Am I correct??

**Comment by mhegazy** [comment]
I was under the impression that your code worked as a module, and the only issue was convincing the compiler that you can import it as one.

**Comment by Nanda-Nandan** [comment]
let me simplify it.Lets say I have a project in which all the classes(spliteed in different ts files) are under one namespace.lets say  Microsoft.OrgUse.Client.I want the all classes to of this namespaces to consume in other project.But in other project lets say a unit test project i am importing Chai,sinon(predefined unit test libraries) using chai.d.ts and Sinon.d.ts  and using Import * as chai(module type) syntax.But to consume the classes of Microsoft.OrgUse.Client namespace we can not import it as module so we are importing it giving reference path to the d.ts files of each ts files.so it is best practice to include import and reference both type of syntax in one ts file??

**Comment by mhegazy** [comment]
I would recommend moving your code to all be modules.

Until this happens, 1. make sure your code is consumable as a node module, see https://github.com/Microsoft/TypeScript/blob/master/src/services/shims.ts#L1225-L1230, then 2. add a post build step to your generated .d.ts to add `export = Microsoft.OrgUse.Client`

**Comment by Nanda-Nandan** [comment]
@mhegazy I will try and let you know

**Comment by Nanda-Nandan** [comment]
Thanks

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
