### ISSUE TITLE
DragEvent constructor is missing parameters

### ISSUE THREAD

**Issue by markthemarkest** [Microsoft/TypeScript#15182]
**TypeScript Version:**  2.2.1

It seems that the constructor for `DragEvent` is declared incorrectly in `lib.d.ts`. It should have one (or more?) parameters, not zero.

**Code**

```ts
let event = new DragEvent();
```

**Expected behavior:**
This should instantiate a new synthetic `DragEvent` which can be initialized with `initDragEvent`, or else fail to compile.

**Actual behavior:**
We receive the runtime error "TypeError: Failed to construct 'DragEvent': 1 argument required, but only 0 present."

```ts
let event = new DragEvent('dragstart');
```

**Expected behavior:**
This should instantiate a new synthetic `DragEvent` of the type `dragstart` which can be further configured with `initDragEvent`.

**Actual behavior:**
We receive the compile error "Supplied parameters do not match any signature of call target."

Written in collaboration with: @markikollasch

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by mhegazy** [comment]
Ported in https://github.com/Microsoft/TypeScript/commit/c8d33bc38ec61e923d6ff62c2e7b004bc56c6e5b
