### ISSUE TITLE
Cannot set Type of module.exports using JSDocs

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#15187]
From: https://github.com/Microsoft/vscode/issues/24657

**TypeScript Version:**  2.3.1-insiders

**Code**

For the JavaScript:

```js
class Foo { }

/**
 * @type {Foo}
 */
module.exports = {}

/**
 * @type {Foo}
 */
const exp = {}
```

**Expected behavior:**
The type of `module.exports` and `exp` are both `Foo`

**Actual behavior:**
The type of `module.exports` is `any`. The type of `exp` is `Foo`

**Comment by Kovensky** [comment]
The problem here is that `@type` applies only to `var`/`let`/`const` declarations, not to expressions. It also doesn't work for setting the type of an object key, for example:

```ts
// @ts-check

const foo = {
  /** @type {string|null} */
  bar: null
}
foo.bar = '' // type error
```

**Comment by mhegazy** [comment]
`module.exports  = {} ` is not a declaration, it is just an assignment, and you can have multiple of these in a single file. 

@Kovensky's suggestion is more attainable. keeping this issue open to enable that.

**Comment by mhegazy** [comment]
https://github.com/Microsoft/TypeScript/issues/13306 is already tracking @Kovensky's suggestion.
