### ISSUE TITLE
Overloaded Function Signature: Can't delegate to function with same signature

### ISSUE THREAD

**Issue by tp** [Microsoft/TypeScript#15180]
**TypeScript Version:**  2.2.1

**Code**

```ts
interface NumberOption {
    returnNumber: true;
}

interface NoNumberOption {
    returnNumber?: false;
}

function eitherOuter(option: NumberOption): number;
function eitherOuter(option: NoNumberOption): string;
function eitherOuter(option: NumberOption | NoNumberOption = {}): string | number {
    // return eitherInner(option); // Does not compile
    if (option.returnNumber === true) {
        return eitherInner(option);
    } else {
        return eitherInner(option);
    }
}

function eitherInner(option: NumberOption): number;
function eitherInner(option: NoNumberOption): string;
function eitherInner(option: NumberOption | NoNumberOption = {}): string | number {
    if (option.returnNumber) {
        return 1;
    } else {
        return 's';
    }
}

const n = eitherOuter({ returnNumber: true });
const s1 = eitherOuter({ returnNumber: false });
const s2 = eitherOuter({});

```

**Expected behavior:**
I would expect to be able to delegate from `eitherOuter` to `eitherInner` without any special annotations.

**Actual behavior:**
Delegating from `eitherOuter` to `eitherInner` is not possible, instead the simplest workaround I was able to find was to write an `if` statement, which had the same statement in both branches.

**Comment by aluanhaddad** [comment]
Type Checking the _implementation_ of `eitherOuter` fails because there is no overload _declaration_ of `eitherInner` that takes `NumberOption | NoNumberOption`. It looks at the first declared overload and rejects it since it cannot except the union type. It rejects the second declared overload for the same reason.

Simplest solution
```ts
function eitherOuter(option: NumberOption): number;
function eitherOuter(option: NoNumberOption): string;
function eitherOuter(option = {}): string | number {
  return eitherInner(option); // Compiles
}
```

**Comment by mhegazy** [comment]
I am not seeing any errors on the latest drop. closing as fixed. please reopen if this is not the case.
