### ISSUE TITLE
Add Number.parseFloat to es2015 lib.d.ts

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#15198]
**TypeScript Version:**  2.2.2  and 2.3.1-insiders

**Code**

```ts
Number.parseFloat('1.2')
```

**Expected behavior:**
No error. This function was added in es2015: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/parseFloat

**Actual behavior:**

```
test.ts(1,8): error TS2339: Property 'parseFloat' does not exist on type 'NumberConstructor'.
```

Other methods to make sure exist:

```
Number.isFinite()
Number.isInteger()
Number.isNaN()
Number.isSafeInteger()
Number.parseFloat()
Number.parseInt()
```

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by NaridaL** [comment]
It looks like parseFloat and co have been in es2015.core for two years... what am I missing?

https://github.com/Microsoft/TypeScript/blame/de313ff1bd11daf484aa421a5d9fde954b8e6fc7/src/lib/es2015.core.d.ts#L241

**Comment by RyanCavanaugh** [comment]
@mjbvz confirm?

**Comment by mjbvz** [comment]
Yes, looks like the originally reporting user and I were on the es3 lib
