### ISSUE TITLE
Type from `declare module "*";` import can't be accessed.

### ISSUE THREAD

**Issue by andy-hanson** [microsoft/TypeScript#15207]
**TypeScript Version:**  nightly (2.3.0-dev.20170415)

**Code**

**declarations.d.ts**

```ts
declare module "*";
```

**a.ts**

```ts
import { T } from "foo";
export const x: T = 0;
```

**Expected behavior:**

No error.

**Actual behavior:**

```ts
a.ts(1,10): error TS6133: 'T' is declared but never used.
a.ts(2,17): error TS2304: Cannot find name 'T'.
```

**Comment by andy-hanson** [comment]
On second thought, this is probably correct to be an error, although the error message(s) could be more helpful.

**Comment by mhegazy** [comment]
I do not think you should be able to pick a concrete type from an unknown entity. +1 for the error message.

**Comment by andy-ms** [comment]
This is a problem with any value used as a type:
```ts
const T = 0;
type U = T;
```

Gives `a.ts(2,10): error TS2304: Cannot find name 'T'.`

In contrast, we have a nice error message for:
```ts
type T = number;
const x = T;
```

Gives `a.ts(2,11): error TS2693: 'T' only refers to a type, but is being used as a value here.`

**Comment by RyanCavanaugh** [comment]
I don't know what this would mean.
