### ISSUE TITLE
Access object with empty-string key

### ISSUE THREAD

**Issue by ikatyang** [Microsoft/TypeScript#15209]
**TypeScript Version:**  2.3.0-dev.20170415

```json
{
  "compilerOptions": {
    "strict": true
  }
}
```

**Code**

```ts
declare const x: {
  '': string;
  'a': string;
  'a-b': string;
}

x[''] // error TS7017: Element implicitly has an 'any' type because type '{ '': string; 'a': string; 'a-b': string; }' has no index signature.
x['a'] // fine
x['a-b'] // fine
```

**Expected behavior:**
no error

**Actual behavior:**
error TS7017: Element implicitly has an 'any' type because type '{ '': string; 'a': string; 'a-b': string; }' has no index signature.

**Comment by HerringtonDarkholme** [comment]
May I ask the use case of empty string key? It seems like a strange pattern for me.

**Comment by ikatyang** [comment]
I just find out this bug accidentally, it looks strange to me too.

But it is still a legal case, so I reported it. :sweat_smile:
