### ISSUE TITLE
Class name duplicated on call stack

### ISSUE THREAD

**Issue by digeff** [Microsoft/TypeScript#15201]
**TypeScript Version:**  2.1.5.0
While debugging this code on Chrome DevTools or VS the class name appears duplicated as the function name in the call stack. Is this intended?

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
class OtherMyClass {
    private recursionDepth = 0;

    public mainMethod = (value: string = "init") => {
        this.recursionDepth++;
        var result: string;
        if (this.recursionDepth === 4) {
            result = this.finalMethod();
        } else {
            result = this.mainMethod(value + "\more");
        }
        this.recursionDepth--;
        return result;
    }

    private finalMethod = () => {
        return "some string";
    }
}

```

**Expected behavior:**
Function name on call stack is: <OtherMyClass.mainMethod>

**Actual behavior:**
Function name on call stack is: <OtherMyClass.OtherMyClass.mainMethod>

**Comment by RyanCavanaugh** [comment]
I don't know if it's intentional or not but it's definitely out of our control
