### ISSUE TITLE
Destructuring assignment must not suggest private/protected properties

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#15214]
Not limited to variable declarations.

**TypeScript Version:**  2.2.2

**Code**

```ts
const { b } = new class {
    private ab;
    protected bc;
};
```

**Expected behavior:**

No suggestion.

**Actual behavior:**

Suggested.

**Comment by mhegazy** [comment]
PRs welcomed.

**Comment by charlespierce** [comment]
PR opened to resolve this: #16953

**Comment by charlespierce** [comment]
@mhegazy If you get a chance could you take a look at the above PR for this issue? Thanks!

**Comment by charlespierce** [comment]
I'd like to prevent #16953 from becoming stale, so if someone could take a few minutes to review, that would be greatly appreciated!

**Comment by falsandtru** [comment]
@mhegazy What are you doing?
