### ISSUE TITLE
Performance request/question: direct use of "arguments" variable inside a function 

### ISSUE THREAD

**Issue by raould** [Microsoft/TypeScript#15215]
**TypeScript Version:**  2.2.2, Linux Ubuntu 16.04 x86_64.

I find it depressing that I cannot use the arguments variable somehow directly, that I have to see TypeScript creating a horrible duplication of memory, and waste of time. I think/wish/dream we should be able to use "...arguments" so that the generated javascript can just use "arguments" directly.

I think I want something like:

```ts
function foo(...arguments) {
   console.log( arguments[0] ); // TS2396
}
```

so I have to do something like:

```ts
function foo(...args) {
   console.log( args[0] ); // ok
}
```

but it generates depressing overhead in the final js:

```js
// the generated js 
    var args = [];
    for (var _i = 0; _i < arguments.length; _i++) {
        args[_i] = arguments[_i];
    }
```

**Comment by ikatyang** [comment]
Default target is `es5`, you have to set `es6`

CLI

```sh
tsc test.ts --target es6
```

or using `tsconfig.json`:

```json
{
    "compilerOptions": {
        "target": "es6"
    }
}

```
test.ts
```ts
function foo(...args) {
   console.log( args[0] ); // ok
}
```

test.js
```js
function foo(...args) {
    console.log(args[0]); // ok
}
```

**Comment by raould** [comment]
thank you, will try!
