### ISSUE TITLE
Support jsx mode "string"

### ISSUE THREAD

**Issue by MeirionHughes** [microsoft/TypeScript#15217]
## Suggestion
Add a new mode for the tsx/jsx mode: **"string"** that, when used and given the input 
```tsx
let foo = 
  <div>
    <div>hello world</div>
  </div>
```
outputs
```ts
let foo =` 
  <div>
    <div>hello world</div>
  </div>`;
```
OR (maybe an alt mode?)
```ts
let foo = `
<div>
<div>hello world</div>
</div>`;
```

### Use case A
I'm currently doing a lot of unit tests (requiring line-number) that look like: 

```ts
  let html = `
  <template>
    <div></div>
  </template>
  `;
```
There are several reasons why the string literal use here is less than ideal: 
 - indentation is done manually / no automatic formatting
 - spaces become part of the string. 
 - time consuming to rearrange (i.e. deeper indentation, several uses in a test suite).

### Use case B

Other frameworks can make use of tsx formatting: for example, Aurelia has an inlineView decorator that allows passing markup to the view compiler: 

```ts
import {inlineView} from 'aurelia-framework';

@inlineView('<template><div>Hello World</div></template>')
export class Foo{
}
```

with tsx - mode: string, this could be improved to 
```tsx

const FooView =
  <template>
    <div>Hello World</div>
  </template>

@inlineView(FooView)
export class FooViewModel{
}
```

the improvement here being better support for indentation, formatting in editors and markup checking.

**Comment by bang88** [comment]
Why not just use template string instead ?

**Comment by MeirionHughes** [comment]
I am, and its annoying when a) I need to rearrange, b) want to format a large chunk, or c) want to ensure correct markup; see Case A.

**Comment by WorldMaker** [comment]
You could implement this today with a custom `--jsxFactory` that calls an "h" factory that produces a string. You take a runtime hit for that, of course, though maybe not a terrible one. The benefit here is that there are a couple options you could use today, thanks to server-side rendering work in the "isomorphic rendering space", for instance [snabbdom-to-html](https://github.com/snabbdom/snabbdom-to-html).

That said, some ability for TS to just stringify JSX could still be handy as a compile-time optimization. (I'd also like to see at something that could be done for some JSX but not all, maybe through a decorator tag or something.)

**Comment by RyanCavanaugh** [comment]
There doesn't seem to be ecosystem demand for this in any appreciable amount. `jsx: "preserve"` is still there if you have some post-build transformer for it
