### ISSUE TITLE
KeyboardEventInit missing props

### ISSUE THREAD

**Issue by quantuminformation** [microsoft/TypeScript#15228]
The KeyboardEvent list is props is [here](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/KeyboardEvent): 

**TypeScript Version:**  
2.1.6
**Code**
I'm trying to create a KeyboardEvent 
```ts
    let e = new KeyboardEvent("keyup", {
      bubbles : true,
      cancelable : true,
      charCode : "1",
      key : "1",
      shiftKey : true,
      keyCode : 81
    });

```

**Expected behavior:**
No error
**Actual behavior:**
I get error:
```
ERROR in /Users/nikos/WebstormProjects/angular-finance/tests/src/app/app.component.spec.ts (33,7): Argument of type '{ bubbles: true; cancelable: true; char: string; key: string; shiftKey: true; keyCode: number; }' is not assignable to parameter of type 'KeyboardEventInit'.
  Object literal may only specify known properties, and 'char' does not exist in type 'KeyboardEventInit'.)
```

Because this only has 4 props:

![image](https://cloud.githubusercontent.com/assets/216566/25102969/91d70a3c-23b2-11e7-82b5-86cbdc28f7d0.png)

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by QuantumInformation** [comment]
Cool I will work on a fix.
-- 

Kind regards

Nikos
quantumjs.com

**Comment by QuantumInformation** [comment]
I've got quite a few hits in lib/ do I need to change them all? 

![image](https://cloud.githubusercontent.com/assets/216566/25132144/5a000de6-2440-11e7-8459-f5247fbf4fe8.png)

**Comment by mhegazy** [comment]
The files under `lib` are not manually edited, they are auto-generatd from a script. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TSJS-lib-generator. 

Changes should be done in https://github.com/Microsoft/TSJS-lib-generator instead.

**Comment by QuantumInformation** [comment]
Cool thanks, I'll have a play.

**Comment by QuantumInformation** [comment]
I'll update the added types:

![image](https://cloud.githubusercontent.com/assets/216566/25173411/deec4776-24eb-11e7-8e27-c7fe3e38b4a1.png)

**Comment by QuantumInformation** [comment]
I see this:
![image](https://cloud.githubusercontent.com/assets/216566/25176933/e3c0d04e-24f7-11e7-85d4-9dc7168d5dd4.png)
But its not clear how this is generated from:

![image](https://cloud.githubusercontent.com/assets/216566/25176950/f43c8940-24f7-11e7-8f50-7169e24ce038.png)

**Comment by QuantumInformation** [comment]
I see this, but is it a user generated file?
![image](https://cloud.githubusercontent.com/assets/216566/25177005/24a58ae6-24f8-11e7-83c4-17532008ea0f.png)

**Comment by QuantumInformation** [comment]
I can't see where this KeyboardEventInit is defnied. Only thing in added types is:

```js
    {
        "kind": "property",
        "interface": "KeyboardEventInit",
        "name": "code?",
        "type": "string"
    },
```

![image](https://cloud.githubusercontent.com/assets/216566/25177391/a5d265e8-24f9-11e7-94e2-d92914c27324.png)

**Comment by mhegazy** [comment]
in overridingTypes.json, add:

```ts
    {
        "kind": "constructor",
        "interface": "KeyboardEvent",
        "signatures": ["new(type: string, eventInitDict?: KeyboardEventInit): KeyboardEvent"]
    },
```

**Comment by QuantumInformation** [comment]
I tried installing mono but am getting:
![image](https://cloud.githubusercontent.com/assets/216566/25200133/31493534-2545-11e7-9c59-7793f5ec754f.png)

**Comment by kostia** [comment]
Any updates on this? Or any workaround for creating proper keyboard events?

**Comment by kscoulter** [comment]
I would also like to see this resolved. Any movement on this?

**Comment by ioanungurean** [comment]
@kscoulter 

https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode

Above it clearly states that `keyCode`,  has been deprecated and should not be used. Instead, `code` should be used.

**Comment by tmccombs** [comment]
@ioanungurean 
> Instead, you should use KeyboardEvent.code, if it's implemented. Unfortunately, some browsers still don't have it, so you'll have to be careful to make sure you use one which is supported on all target browsers.

If you need to support IE/Edge you can't use `code` and need to still need to use `keyCode`.

**Comment by alecmolloy** [comment]
I'm happy to make a PR fixing this if it would be welcome. Understand it is deprecated but it is still very much supported and unfortunately necessary in some cases.

**Comment by taejs** [comment]
Is there any progress on it

**Comment by taejs** [comment]
I made PR for it 
Hope it would be merged

**Comment by devniel** [comment]
I think that Angular uses `keyCode`, I was trying to dispatch a `KeyboardEvent` in jest but it wasn't catched by the component, so I found a nice solution and it works.

```typescript
Object.defineProperty(event, 'keyCode', {
  get: () => 27,
});
```

**Comment by taejs** [comment]
PR merged.
