### ISSUE TITLE
Support to distinguish diagnostics from TS from the diagnostics from a language server plugin

### ISSUE THREAD

**Issue by egamma** [Microsoft/TypeScript#15224]
Experimenting with tslint running as a language server plugin. 

When providing the diagnostics from tslint from the language server plugin decorator, then the diagnostics cannot be distinguished from the original typescript diagnostics, see below:

![image](https://cloud.githubusercontent.com/assets/172399/25098822/42bcb152-23aa-11e7-8483-cc58840c8f3b.png)

With the existing vscode-tslint extension we prefix the message with the source of the diagnostic, e.g., `tslint`.

**Comment by cyrilletuzi** [comment]
It's already possible, Angular Language Service is already doing it.

**Comment by mhegazy** [comment]
looks like this is covered by https://github.com/Microsoft/TypeScript/issues/15237

**Comment by egamma** [comment]
@cyrilletuzi goodness, do you have a pointer to the repo please.

**Comment by egamma** [comment]
@mhegazy issue #15237 is about distingushing between warnings and errors. This issue related but different. It is about distinguishing warning/errors that come from TS and warnings that come from TSLint. To make this more clear here is an example from how the diagnostics show up in VS Code.

This is an error from TypeScript, notice the `[ts]` prefix:
![image](https://cloud.githubusercontent.com/assets/172399/25118008/aac4be24-2414-11e7-8339-fb8f82ee2df2.png)

This is a warning from tslint, notice the `[tslint]` prefix:
![image](https://cloud.githubusercontent.com/assets/172399/25118045/d37f8a88-2414-11e7-9e6f-ea8271158181.png)

This source of a diagnostic is important when the user wants to configure a diagnostics, e.g., for TS diagnostics this is done in the `tsconfig.json` for tslint this is done in `tslint.json`.

In the VS Code diagnostics API a diagnsotic has an optional field `source`, that the creator of a diagnostic can set and this then rendered in the UI.

(removing the duplicate label)

**Comment by cyrilletuzi** [comment]
Maybe in the VS Code plugin : https://github.com/angular/vscode-ng-language-service

**Comment by egamma** [comment]
@cyrilletuzi thanks the pointer, but please keep in mind that the VS Code angular language service extension is not yet using the TS language server plugin support and runs a duplicate TypeScript language server. In this setup the extension can use the VS Code diagnostic API to set the source of the diagnostic to `Angular`, which it does [here](https://github.com/angular/vscode-ng-language-service/blob/bd8f2c2e1849b66bf5cd805e72a8848b4fa80a67/server/src/errors.ts#L46).

Once the angular language service extension runs as a TS language server plugin this will no longer be possible. So this is another scenario that there is a need for an optional `source` attribute in the TS Diagnostic.

**Comment by cyrilletuzi** [comment]
Sorry, I forgot about this.

Indeed, when using directly `@angular/language-service` from tsconfig.json, errors are just prefixed with `[ts]`.
