### ISSUE TITLE
Compile error on JS project

### ISSUE THREAD

**Issue by alippai** [Microsoft/TypeScript#15220]
**TypeScript Version:** Version 2.3.0-dev.20170417

**Code**

```json
{
  "compilerOptions": {
    "target": "ES2017",
    "module": "es2015",
    "allowJs": true,
    "checkJs": true,
    "outDir": "./.ts",
    "rootDir": "./app",
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitAny": false
  },
  "files": [
    "app/entry.js"
  ]
}
```

**Expected behavior:**
My project is a JS only, ES2017 project.
It should compile (with warnings and errors). ES5 target emits errors however I can't add ES2015 lib or switch to ES2017 target.

**Actual behavior:**
Throws error:
```
$ tsc
C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:53716
                throw e;
                ^

TypeError: Cannot read property 'lineMap' of undefined
    at Object.getLineStarts (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:3514:26)
    at shouldReportDiagnostic (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:53739:33)
    at Object.filter (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:393:31)
    at C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:53733:26
    at runWithCancellationToken (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:53709:24)
    at getSemanticDiagnosticsForFileNoCache (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:53723:20)
    at getAndCacheDiagnostics (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:53924:26)
    at getSemanticDiagnosticsForFile (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:53720:20)
    at C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:53679:45
    at Object.forEach (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:288:30)
```

**Comment by mhegazy** [comment]
@alippai can you share the input that you are seeing this crash on?

**Comment by alippai** [comment]
It's a huge private repo. I tried to create a small input example, however I had no luck.

Do you have any idea how to narrow this down? Is there a debug / verbose flag or anything helpful I can start with?

**Comment by mhegazy** [comment]
assuming you have node v7 or later

```sh
node --inspect --debug-brk node_modules\typescript\lib\tsc.js --p <path to your tsconfig.json>
```

you should see a link to attach to node at that point, copy this link and past it in your chrome browser.  let the process run, when it breaks, there should be `getSemanticDiagnosticsForFileNoCache` on the stack. Look up the value of `sourceFile.fileName` in your watch window, this should tell you which file is causing the issue. you can also dump the `diagnostic` object that is the argument of the function.

**Comment by alippai** [comment]
Thank you, this was the answer I was looking for!
The error is: ```"Class 'Container' defines instance member function '_getKey', but extended class 'MasterKeyContainer' defines it as instance member property."```

**Comment by mhegazy** [comment]
can you share the file that caused the issue? or at least the full JSON dump of the diagnostic object for us to fix the underlying issue.

**Comment by alippai** [comment]
This fails with the same error:
```
class A {
  constructor() {

  }
  foo() {
    return 4;
  }
}

class B extends A {
  constructor() {
    super();
    this.foo = () => 3;
  }
}

const i = new B();
i.foo();
```

**Comment by mhegazy** [comment]
Thanks! fix up in https://github.com/Microsoft/TypeScript/pull/15229
