### ISSUE TITLE
Comment removed from JSX even with `--removeComments false --jsx preserve`

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#15235]
**TypeScript Version:**  2.2.1 / nightly (2.2.0-dev.201xxxxx)

**Code**

**a.tsx**

```ts
/* comment */
<div>
    {/* comment */}
</div>
```

**Expected behavior:**

Output same as input.

**Actual behavior:**

**a.jsx**

```js
/* comment */
<div>
    
</div>;
```

**Comment by yuit** [comment]
Couple reason

- We omit the empty JSX Expression so we may not need to emit the comment

- "{" is not stored in tree so it will be impossible to get the comment out unless we store it some how
