### ISSUE TITLE
Can't iterate over DOM elements even with dom.iterable

### ISSUE THREAD

**Issue by seivan** [Microsoft/TypeScript#15236]
I might have missed something here. Feel free to close this ticket if it's related to https://github.com/Microsoft/TypeScript/issues/4947 

**TypeScript Version:**  2.2.1 / nightly (2.2.0-dev.201xxxxx)

**Code**

`tsconfig.json`

```json
    "compilerOptions": {
        "outDir": "./dist/",
        "sourceMap": true,
        "noImplicitAny": false,
        "suppressImplicitAnyIndexErrors": true,
        "module": "commonjs",
        "target": "es5",
        "strictNullChecks": true,
        "experimentalDecorators": true,
        "jsx": "react",
        "lib" : ["dom","es6","dom.iterable","scripthost", "es2015.iterable", "es2015.collection"],
        "alwaysStrict": true,
        "removeComments": true,
        "emitDecoratorMetadata": false,
        "noEmitHelpers" : false,
        "importHelpers" : true,
        "allowJs": true,
        "forceConsistentCasingInFileNames": true,
        "noUnusedLocals": false

    },
```

```ts
const myNodeListOfBrs = document.querySelectorAll("br")
myNodeListOfBrs.forEach(element => {
  console.log(element);            
});

```

**Expected behavior:**
It should compile 

**Actual behavior:**
It does not compile with error: `property 'forEach' does not exist on type 'NodeListOf<HTMLBRElement>`

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by mhegazy** [comment]
Documentation for NodeList.forEach can be found at https://developer.mozilla.org/en-US/docs/Web/API/NodeList/forEach

**Comment by seivan** [comment]
@mhegazy Uhm, But I am not sure if there even is a problem. From what I understand the interfaces exists but maybe you have to import them somehow. I was just trying to figure out what I'm doing wrong.

**Comment by mhegazy** [comment]
`NodeList` in `lib.d.ts` needs to have a definition for `forEach`. it does not today.

**Comment by mhegazy** [comment]
Fixed by https://github.com/Microsoft/TypeScript/pull/14641

**Comment by seivan** [comment]
@mhegazy Yeah I know it's been fixed and they exist, I write so in my previous comment. I am just wondering on how to use them? Since they don't actually work out of the box. What do I need to import?

**Comment by mhegazy** [comment]
```sh
c:\test>type b.ts
const myNodeListOfBrs = document.querySelectorAll("br")
myNodeListOfBrs.forEach(element => {
  console.log(element);
})
c:\test>tsc --v
Version 2.3.0-dev.20170419

c:\test>tsc --lib dom.iterable,es6 C:\test\b.ts
```

**Comment by seivan** [comment]
@mhegazy Thanks, I'll give it a try. It should be available on 2.2.0 as well.

**Comment by mhegazy** [comment]
that is a 2.3 change.

**Comment by jhpratt** [comment]
@mhegazy I'm running tsc 2.3.2 and it fails on the exact example given above.

**Comment by mhegazy** [comment]
make sure your `--lib es6,dom,dom.iterable`, or tsconfig.json has:
```json
        "lib": [
            "dom", "es6", "dom.iterable"
        ]
```

**Comment by trusktr** [comment]
If I recall correctly, not all browser put a `forEach` method on NodeLists.
