### ISSUE TITLE
new URL() does not take URL object as base parameter

### ISSUE THREAD

**Issue by felixfbecker** [microsoft/TypeScript#15246]
**TypeScript Version:**  2.3.0

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
const base = new URL('http://foo.com')
new URL('bar.html', base) 
```

**Expected behavior:**
Should compile

**Actual behavior:**
```
[ts]
Argument of type 'URL' is not assignable to parameter of type 'string | undefined'.
  Type 'URL' is not assignable to type 'string'.
```

Reference: https://developer.mozilla.org/en-US/docs/Web/API/URL/URL

**Comment by RyanCavanaugh** [comment]
The W3C definition clearly defines this as a string https://url.spec.whatwg.org/#constructors , so the ability to pass a URL is just an implicit string conversion. Not sure why MDN documents this as if it's a different constructor.

**Comment by RyanCavanaugh** [comment]
... but the spec also shows an implicit string conversion as an example usage, so we should play along

**Comment by felixfbecker** [comment]
Yeah, you are right. It seems to accept `URL` objects for both input and base.

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by TimvdLippe** [comment]
https://github.com/Microsoft/TSJS-lib-generator/pull/332 has been merged and the update has been incorporated in this repository per https://github.com/Microsoft/TypeScript/blob/f2a1a428ea99ace495a8ca769b0a7c857ea6486a/lib/lib.dom.d.ts#L14860

**Comment by BarryThePenguin** [comment]
I think this can be closed now? It looks like the latest `lib.dom.d.ts` supports this

https://github.com/microsoft/TypeScript/blob/a03227d60e2da470a8a964903016e2b3d0106950/lib/lib.dom.d.ts#L16070
