### ISSUE TITLE
URLSearchParams should be iterable

### ISSUE THREAD

**Issue by zh99998** [Microsoft/TypeScript#15243]
**TypeScript Version:**  2.2.2

according to https://url.spec.whatwg.org/#urlsearchparams
URLSearchParams is iterable, but it is not iterable in typescript now.

this code failed to compile but run successful as plain JavaScript in google chrome.
**Code**

```ts
// A *self-contained* demonstration of the problem follows...
const params = new URLSearchParams()
params.set('k', 'v')
for(let [key, value] of params) {
    console.log(key, value)
}
```

**Expected behavior:**
compile successfully
**Actual behavior:**
error TS2488: Type must have a '[Symbol.iterator]()' method that returns an iterator.

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by mhegazy** [comment]
The change would need to go in https://github.com/Microsoft/TypeScript/blob/master/src/lib/dom.iterable.d.ts
