### ISSUE TITLE
Add "virtual" and "override" keywords for methods

### ISSUE THREAD

**Issue by ghost** [microsoft/TypeScript#1524]
I know that my suggestion (as what you see above in the title) is something (not a must)……Well, however, it would be nice if we can use this "syntax suger" to make TypeScript "more professional", the wrapper of js. Those without the "virtual" cannot be overridden. And when you type something like "override", it will offer you functions that can be overridden.

Thanks anyway!

**Comment by ngates87** [comment]
this may be a superfluous suggestion, but maybe one idea for purely syntactic sugar that maybe wouldn't break anything, is just allow you to have the override keyword after a function, to make it clear that is overriding a specific function?

**Comment by RyanCavanaugh** [comment]
@ngates87 #2000

**Comment by MaleDong** [comment]
@ngates87：Yes.
@RyanCavanaugh：Please make my issue open, for #2000 have the same issue.

**Comment by kitsonk** [comment]
@MaleDong #2000 is open, the suggestion is that is the only thing that is being considered and you should add any thoughts to that issue.
