### ISSUE TITLE
Feature request: add 'as' to function and constructor

### ISSUE THREAD

**Issue by Alphapage** [Microsoft/TypeScript#15248]
Hello,

Classic:
```
test(param1:string, param2:Number) : boolean {
        return true
    }
```
New feature:
```
test(param1, param2) as (string, Number): boolean {
        return true
    } 
```

It would be great to enhance typescript with such 'as' feature to have a group of typings after a function or a constructor (a kind of resume).

Thank you in advance for your feedback.

**Comment by RyanCavanaugh** [comment]
This doesn't really seem to do anything in exchange for a bunch of extra complexity
