### ISSUE TITLE
JSDoc Cannot Add Properties to `object` Type

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#15250]
From: https://github.com/Microsoft/vscode/issues/24942

**TypeScript Version:**  2.3.1-insiders0416

**Code**

```ts
/**
 * @typedef {object} MyType
 * @prop {string} myProp
 */

/**
 * @param {MyType} param
 */
function x(param) {
}
```

**Expected behavior:**
`param` is a type that knows about `myProp`

**Actual behavior:**
`param` is `object`. No suggestions for `myProp` are provided by intellisense.

Using `Object` instead:

```js
/**
 * @typedef {Object} MyType
 * @prop {string} myProp
 */

/**
 * @param {MyType} param
 */
function x(param) {
}
```

We do see proper intellisense.

I'm not sure if this difference is by design or not. The jsdoc docs seem to show both `Object` and `object` being used: http://usejsdoc.org/tags-type.html

**Comment by mhegazy** [comment]
We may need to parse `object` in JSDoc as `Object` to avoid such errors.
