### ISSUE TITLE
Errors in `src/services/goToImplementation.ts`

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#15259]
Sample build : https://travis-ci.org/basarat/byots/builds/223035023#L804

```
src/services/goToImplementation.ts(4,47): error TS2339: Property 'FindImplementationsContext' does not exist on type 'typeof FindAllReferences'.
src/services/goToImplementation.ts(9,31): error TS2339: Property 'getReferenceEntriesForShorthandPropertyAssignment' does not exist on type 'typeof FindAllReferences'.
src/services/goToImplementation.ts(20,57): error TS2339: Property 'getReferencedSymbolsForNode' does not exist on type 'typeof FindAllReferences'.
src/services/goToImplementation.ts(22,72): error TS2339: Property 'references' does not exist on type '{}'.
```

Searching for the first one `FindImplementationsContext` https://github.com/Microsoft/TypeScript/search?utf8=%E2%9C%93&q=FindImplementationsContext yields 0 *definitions* (only 1 usage)
![image](https://cloud.githubusercontent.com/assets/874898/25157008/dc3c68a8-24e1-11e7-9ed7-5ce57c7b2dee.png)

Perhaps I am doing something wrong? Thanks as always :rose: :heart:

**Comment by basarat** [comment]
# More 

* Hot fix (aka .. delete the feature to get the build working): I've excluded the file : https://github.com/basarat/byots/commit/e8a7eebc9c545fa159ba901ae992b786b4fa64e4#diff-3a9c05fa57212221e20e8fefb20fb9deR22

* Code probably worked at this point : https://github.com/Microsoft/TypeScript/commit/595342615b8e9c729626668f3a1eff3c764fb77b#diff-e393a975fae9a2d241a5a38e3fb02fd2R4 This code was removed recently breaking the build

Hope that helps the person debugging this issue :rose:

**Comment by mhegazy** [comment]
@andy-ms can you take a look
