### ISSUE TITLE
Typing static class

### ISSUE THREAD

**Issue by wesleycho** [Microsoft/TypeScript#15263]
**TypeScript Version:**  2.2.1

**Code**

```ts
import { Component, DebugElement, Type } from '@angular/core';
import { ComponentFixture, TestBed } from '@angular/core/testing';

interface TestFixture<T> {
  component: T;
  debugElement: DebugElement;
  element: any;
  fixture: ComponentFixture<T>;
}

export function createComponent<T>(TestBed: Static<TestBed>, cmpt: Type<T>): TestFixture<T> {
  const fixture = TestBed.createComponent(cmpt);
  const component = fixture.componentInstance;
  const debugElement = fixture.debugElement;
  const element = fixture.nativeElement;

  return { component, debugElement, element, fixture };
}
```

**Expected behavior:**

I propose that we have a good way of typing a static class value in a function argument - in this example, this prevents me from accurately typing `fixture`, `component`, `debugElement`, and `element` without force casting since TypeScript does not appear to support typing static instances.

In my example, I am proposing that a syntax such as `Static<TestBed>` represent the static class `TestBed`, which is not meant to be newed.

**Actual behavior:**

I get errors such as
```
TS2345: Argument of type 'typeof TestBed' is not assignable to parameter of type 'TestBed'
```

**Comment by aluanhaddad** [comment]
> In my example, I am proposing that a syntax such as Static<TestBed> represent the static class TestBed, which is not meant to be newed.

There is such syntax already:
```ts
interface TestBed {
  createComponent<T extends new (...args:{}[]) =>{});
}
```
> TypeScript does not appear to support typing static instances.

Maybe I misunderstand, but what is a static instance? Everything is just an object, even a class which is why the interface declaration above will work.

**Comment by wesleycho** [comment]
TestBed is not something I own - it is something that the Angular team provides with static methods on the class itself.

Looks like the answer was to use `typeof TestBed` in this instance though.

Closing as this appears to have a good enough solution for my case.

**Comment by aluanhaddad** [comment]
@wesleycho that doesn't mean you can't declare type for it. Just use another name
