### ISSUE TITLE
No --target es2016 support on VS2017?

### ISSUE THREAD

**Issue by SaschaNaz** [Microsoft/TypeScript#15264]
**TypeScript Version:**  2.1.5.0 (VS2017)

**Code**

```xml
  <PropertyGroup Label="Configuration" Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <TypeScriptTarget>ES2016</TypeScriptTarget>
    <TypeScriptNoImplicitAny>true</TypeScriptNoImplicitAny>
    <TypeScriptOutFile>js/app.js</TypeScriptOutFile>
  </PropertyGroup>
```

**Expected behavior:**

It should compile

**Actual behavior:**

`Build:Cannot find name '(every type in lib.d.ts e.g. Document)'`

**Comment by DanielRosenwasser** [comment]
I think this is related to #14401. Can you try out adding `"lib": ["es2016", "dom"]`?

**Comment by SaschaNaz** [comment]
Seems it does the work. Thanks!:
