### ISSUE TITLE
Destructuring with default values allows invalid references for the defaults

### ISSUE THREAD

**Issue by voithos** [Microsoft/TypeScript#15273]
**TypeScript Version:**  2.3-rc

**Code**

```ts
class Foo {
  constructor({someVar = false}: {
    someVar: boolean,
  } = {someVar}) {}
}
```

**Expected behavior:**
This should result in an error, since `someVar` is an invalid reference in the default list (the destructured variable hasn't been initialized yet).

**Actual behavior:**
This compiles without error, resulting in ES5 output like this (notice the invalid reference to `{ someVar: someVar }`):

```ts
function Foo(_a) {
    var _b = (_a === void 0 ? { someVar: someVar } : _a).someVar, someVar = _b === void 0 ? false : _b;
}
```

**Comment by RyanCavanaugh** [comment]
Tracking at #15274
