### ISSUE TITLE
Resolving module declaration path should prefer d.ts over .ts

### ISSUE THREAD

**Issue by SaschaNaz** [Microsoft/TypeScript#15272]
**TypeScript Version:**  master branch

**Repro:**

1. Get this file and unzip: [ts-module-declaration-resolving.zip](https://github.com/Microsoft/TypeScript/files/936633/ts-module-declaration-resolving.zip)
2. Run `tsc` on the `test` subdirectory

**Expected behavior:**

test-output directory should only contain inner.js

**Actual behavior:**

test-output directory contains outer.js and test/inner.js

**Why?:**

`import test from "../outer.js"` causes this bug, it should try finding outer.d.ts before outer.ts to remove the need to recompile.

**Comment by mhegazy** [comment]
`.ts` files are considered sources, where `.d.ts` are considered outputs. the compiler will always prefer a source file for an output when it is resolving modules, the rational, is that sources are more up-to-date than an output.

In general, do not put .d.ts next to your .ts if you intend to import them, use `--outDir` or `--declrationDir` instead.
