### ISSUE TITLE
Move TS implementation of FindRefs onto new Roslyn APIs

### ISSUE THREAD

**Issue by CyrusNajmabadi** [Microsoft/TypeScript#15281]
Roslyn has a new api that allows for a much richer FindRefs/FindImpls experience: https://github.com/dotnet/roslyn/blob/master/src/EditorFeatures/Core/FindUsages/IFindUsagesService.cs#L9

This provides this sort of rich experience that you now get in C#/Vb/F#:

![image](https://cloud.githubusercontent.com/assets/4564579/25206383/8b7ba420-251c-11e7-8517-5f657cd0b2e9.png)

We would really like it if TypeScript could move to these APIs to help give that same rich experience to TS/JS developers while also alowing Roslyn to eliminate many thousands of LOC that we have around to maintain the old system :)

I believe @vladima had this working before he left.  It would be great if it could be resurrected and done in the 15.4 timeline.  

Thanks much!

**Comment by amcasey** [comment]
I'm still cleaning up some issues that are not regressions, but this can reasonably be considered to be complete (i.e. we're no longer implementing the old API).
