### ISSUE TITLE
Typescript 2.3.0 in npm while latest stable is 2.2.2

### ISSUE THREAD

**Issue by SkeLLLa** [Microsoft/TypeScript#15293]
**TypeScript Version:**  2.3.0

During npm installation phase non-stable release (2.3.0) is installed.

How it's possible?

**Expected behavior:**
Npm site reports that's latest version is 2.2.2
Github version 2.2.2
During npm install it installs version 2.2.2

**Actual behavior:**
Npm site reports that's latest version is 2.2.2
According to github there is version 2.3.0-rc
During npm install it installs version 2.3.0 (with both `^2.0.0` or `*` in package.json)

**Comment by RyanCavanaugh** [comment]
#15125

**Comment by SkeLLLa** [comment]
Thanks for explanation.
