### ISSUE TITLE
Add `checkJs` to TSServer Protocol `CompilerOptions`

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#15297]
**TypeScript Version:**  2.3.1-insiders0416

It looks like the `checkJS` setting is currently not on the TSServer `CompilerOptions` object. If we add a setting in vscode to enable checkJS for implicit projects, we need this flag exposed in the protocol

**Comment by mhegazy** [comment]
Fixed by https://github.com/Microsoft/TypeScript/commit/8534b430beff7f122091d19d2536b5cc798860ce
