### ISSUE TITLE
document.Stylesheets appears to be wrongly defined

### ISSUE THREAD

**Issue by coderangerdan** [Microsoft/TypeScript#15319]
**TypeScript Version:**  2.2.2

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
for ( var r = 0; r < document.styleSheets.length; r++ )
{
    var css = document.styleSheets[r];
    if ( css )
    {
        var rules = css.cssRules ? css.cssRules : css.rules;
        if ( rules )
        {
            for ( var i = 0; i < rules.length; i++ )
            {
                if ( rules[i].selectorText == ".dlmDetail" )
                {
                    // change the rule
                    break;
                }
            }
        }
    }
}
```

**Expected behavior:**
cssRules should be defined in the StyleSheet interface, or perhaps item in StyleSheetList should be defined as a CSSStyleSheet; but then the rules should be defined as CSSStyleRule and not CSSRule.

**Actual behavior:**
cssRules does not exist; looking at the definition, cssRules appears to be defined in CSSPageRule which is part of StyleSheetPageList; however document.styleSheets is not defined as a StyleSheetPageList but as a StyleSheetList

**Further information:**
[Mozilla: CSSRuleList Definition](https://developer.mozilla.org/en-US/docs/Web/API/CSSRuleList)

**Comment by SaschaNaz** [comment]
`cssRules` is defined in [`CSSStyleSheet`](http://www.w3.org/TR/cssom-1/#the-cssstylesheet-interface) interface. You can cast abstract StyleSheet object as CSSStyleSheet to access the property.

**Comment by coderangerdan** [comment]
But surely it should work out the box, why would i need to create my own abstract interfaces just to get the default vanilla javascript to work? Sorry, I am a bit confused.

**Comment by SaschaNaz** [comment]
By the code itself TypeScript cannot be sure your sheet is a CSS sheet or your rule is a CSSStyleRule because by definition there can be a non-CSS stylesheet or non-style rule. (There is no non-CSS stylesheet but the CSS spec writers made it abstract so that someone can make one in future.)

This works without casting:

```ts
for ( var r = 0; r < document.styleSheets.length; r++ )
{
    var css = document.styleSheets[r];
    if ( !( css instanceof CSSStyleSheet ) )
    {
        continue;
    }
    // Now TypeScript knows that your sheet is CSS sheet
    if ( css )
    {
        var rules = css.cssRules ? css.cssRules : css.rules;
        if ( rules )
        {
            for ( var i = 0; i < rules.length; i++ )
            {
                const rule = rules[i]
                if ( !( rule instanceof CSSStyleRule ) )
                {
                    continue;
                }
                // Now TypeScript knows that your rule is CSSStyleRule
                if ( rule.selectorText == ".dlmDetail" )
                {
                    break;
                }
            }
        }
    }
}
```

**Comment by coderangerdan** [comment]
Ah i didnt realise that about the spec, thanks.
