### ISSUE TITLE
Battery Status API typing support

### ISSUE THREAD

**Issue by Jack-Works** [Microsoft/TypeScript#15314]
https://developer.mozilla.org/en-US/docs/Web/API/Battery_Status_API

There should be a ```getBattery(): Promise<BatteryManager>``` on the interface ```Navigator``` in lib.dom.d.ts, but there is not.

Reported: 
```
[ts] Property 'getBattery' does not exist on type 'Navigator'
```

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by Jack-Works** [comment]
Umm, I'll try it

**Comment by mhegazy** [comment]
Looks like the API is deprecated. see https://github.com/Microsoft/TSJS-lib-generator/pull/236 for relevant discussion.
