### ISSUE TITLE
Have generated js file from TS, my query is that, i want to use this generated js file into another application(Not in angular 2 framework)

### ISSUE THREAD

**Issue by mohammedismais** [Microsoft/TypeScript#15318]
**TypeScript Version:**  2.2.1 / nightly (2.2.0-dev.201xxxxx)

**Code**

```ts
// A *self-contained* demonstration of the problem follows...

```

**Expected behavior:**

**Actual behavior:**

**Comment by mhegazy** [comment]
For questions we ask you post them on SO. this repo is for compiler/language bug reports and suggestions.

I am guessing you are looking for `--declaration` flag to generate a .d.ts file from a .ts file.
