### ISSUE TITLE
Custom transformers does not work with tsx and jsx: 'react' compiler option

### ISSUE THREAD

**Issue by kimamula** [Microsoft/TypeScript#15317]
**TypeScript Version:**  2.3.0-dev.20170422

**Code**

* test.tsx
```ts
import * as React from 'react';

class Test extends React.Component<{}, {}> {
  render() {
    return <div></div>;
  }
}
```

* compile.js

```js
const ts = require('typescript');

const program = ts.createProgram(['./test.tsx'], {
  strict: true,
  noEmitOnError: true,
  target: ts.ScriptTarget.ES5,
  jsx: 'react'
});

const transformers = {
  before: [context => file => file], // use a custom transformer that does nothing
  after: []
};
program.emit(undefined, undefined, undefined, false, transformers);
```

And then run

```sh
$ node compile.js
```

**Expected behavior:**
`return <div></div>;` is converted to `return React.createElement("div", null);`

**Actual behavior:**
`return <div></div>;` remains in the emitted JavaScript file.

**Comment by kimamula** [comment]
Sorry, this was my fault.
`jsx: 'react'` should be `jsx: ts.JsxEmit.React`.

**Comment by RyanCavanaugh** [comment]
Someone should write a typechecker to catch those kinds of problems 🤔 😉
