### ISSUE TITLE
Object value types are unioned when computed property names are used

### ISSUE THREAD

**Issue by zakjan** [Microsoft/TypeScript#15324]
**TypeScript Version:**  2.2.2

**Code**

```ts
const a = "a";
const b = "b";

const x = {
    [a]: "aaa",
    [b]: 123,
};

const y = {
    a: "aaa",
    b: 123,
};
```

**Expected behavior:**
both `x`, `y` have type `{a: string, b: number}`

**Actual behavior:**
`x` has type `{[x: string]: string | number}`
`y` has type `{a: string, b: number}`

**Comment by mhegazy** [comment]
Same underlying cause as https://github.com/Microsoft/TypeScript/issues/5579
