### ISSUE TITLE
Incorrect parsing when semicolon is omitted

### ISSUE THREAD

**Issue by pedrovagner** [Microsoft/TypeScript#15325]
**TypeScript Version:**  2.2.1

**Code**

```ts
function foo(cb, bar) {
    // Omitting semicolon here cause the unexpected behavior
    if (bar) return cb(true)

    (function () { return cb(false) })()
}
```

**Expected behavior:**

```js
function foo(cb, bar) {
    if (bar)
        return cb(true);
    (function () { return cb(false); })();
}
```

**Actual behavior:**

```js
function foo(cb, bar) {
    if (bar)
        return cb(true)(function () { return cb(false); })();
}
```

**Comment by fatcerberus** [comment]
Isn't this how automatic semicolon insertion is supposed to work?  The parser only inserts a semicolon if omitting it would cause a syntax error, which is not the case here.

**Comment by mhegazy** [comment]
TypeScript follows the [JS rules for semicolon insertions](http://www.ecma-international.org/ecma-262/6.0/#sec-automatic-semicolon-insertion). I would recommend using a [style rule](https://palantir.github.io/tslint/rules/semicolon/) to flag missing semicolons.

**Comment by pedrovagner** [comment]
Sorry guys, now I know that TypeScript isn't used to fix JavaScript. I thought TypeScript should advocate in favor of _"developer's intention"_, but it can't because JavaScript won't let. TypeScript source code must follow the _"JS compiler intention"_.

Feel free to delete this issue.
