### ISSUE TITLE
Merge all code of same namespaces declared in different files together

### ISSUE THREAD

**Issue by novakf** [Microsoft/TypeScript#15321]
I am writing class per file, interface per file. However, these classes and namespaces are declared in the same namespace.

Currently, we need to export everything from the namespace to be accessible form the same namespace but declared in another file. This makes everything declared in the namespace available outside of it, even if I don't want to.
Also, It makes impossible to perform effective code minification.

Is there any special reason why this can't be done? I can imagine there can be a compilator option for it.

Thanks,
Frantisek

**Comment by mhegazy** [comment]
Seems like a duplicate of https://github.com/Microsoft/TypeScript/issues/447

**Comment by novakf** [comment]
Yep, it is.
