### ISSUE TITLE
String type lost at right-hand side of `||` operator

### ISSUE THREAD

**Issue by akfish** [Microsoft/TypeScript#15336]
**TypeScript Version:**  2.2.2

**Code**

```ts
let str: string = 'c'

if (str !== 'a' || str !== 'b') {
                // ^ Type of this `str` is `"a"`
                    // ^  error TS2365: Operator '!==' cannot be applied to types '"a"' and '"b"'
}
```

**Expected behavior:**

* No type error should be thrown. 
* `str` at rhs of `||`'s type should be `string`. 

**Actual behavior:**

* Error thrown:
  > error TS2365: Operator '!==' cannot be applied to types '"a"' and '"b"'
* `str` at rhs of `||`'s type is `"a"`

**Comment by akfish** [comment]
I just realized that this is actually correct. Sleep deprivation got me confused. :(

**Comment by RyanCavanaugh** [comment]
TYPESCRIPT NEVER SLEEPS
