### ISSUE TITLE
Missing readAttribute and setAttribute methods on elements

### ISSUE THREAD

**Issue by coderangerdan** [Microsoft/TypeScript#15331]
**TypeScript Version:**  2.2.2

**Code**

```ts
var fieldName = this.readAttribute( "fieldName" );

this.setAttribute( "fieldName", "new value" );
```

**Expected behavior:**
To not produce an error

**Actual behavior:**
Produces an error "property 'readAttribute' or 'setAttribute' does not exist on type "HTMLElement"

**Further information:**
[Mozilla: Element.getAttribute Definition](https://developer.mozilla.org/en/docs/Web/API/Element/getAttribute)

**Comment by RyanCavanaugh** [comment]
These things are defined. See http://www.typescriptlang.org/play/#src=var%20x%20%3D%20document.getElementById('foo')%3B%0D%0Ax.getAttribute(%22huh%22)%3B%0D%0A

Please provide a **self-contained** repro for your issue. Something is probably wrong with your options?

**Comment by coderangerdan** [comment]
That's all I need to type, not sure how I can make it any more self contained, I don't really have options which would make a difference and if I F12 on a TS type to go to lib.ts.d, I dot see those methods anywhere. 

My lib.ts.d is coming from C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TypeScript\lib.d.ts and I downloaded the v2.2.2 VS extension from the site.

**Comment by coderangerdan** [comment]
My bad, i was using readAttribute which isnt the correct method, it is "getAttribute"
