### ISSUE TITLE
Suggestions for misspelled properties and variables (based on Levenshtein distance for variables/properties in scope)

### ISSUE THREAD

**Issue by artr73** [Microsoft/TypeScript#15333]
Consider the following code:
```
class X {
  public longName = 10;
  public otherName = 11;

  public do(){
    this.lognName = 20;
  }
}
```
Currently compilation fails with the message:
```
Property 'lognName' does not exist on the type 'X'.
```
In case when a variable is misspelled, the error is even less helpful:

```
public longMethod(){
  let firstVariable = 10;
  let secondVariable = "hello,world";
  
  //lots of code here
  fristVariable = 20;
}
```

```
Cannot find name 'fristVariable'.
```
It could offer variable/property suggestion, like:
```
Cannot find name 'fristVariable'. Did you mean 'firstVariable'?
```

For example, Rust compiler (1.16) would suggest an existing variable that most resembles the misspelled one, based on Levenstein distance, if I'm correct.

**Comment by RyanCavanaugh** [comment]
@sandersn notes from backlog slog:
 * Do some sort of limiting to avoid this being too expensive (caching? limit the number of times we do this? etc?)
 * Levensthein / Hamming / Shiveldistance is up to you
 * Have some minimal threshold of "might be close enough"
 * Filter based on the *kind* of symbol (identifier / namespace / type) to make sure we only suggest valid stuff
 * Include a quickfix
 * Everyone's gonna 😍 this

**Comment by sandersn** [comment]
You can track the progress of this at the branch `sandersn/did-you-mean`. It's at a very early stage right now -- the suggested replacement is the first name whose length is no more than 3 different from the misspelled name's length. This works pretty well for property accesses for but lone identifiers tends to suggest `NaN` and `Infinity`.

There's a quick fix for property accesses. My next step is to make it work for standalone identifiers as well.

**Comment by Igorbek** [comment]
Should intellisense also suggest something when you misspell?

**Comment by sandersn** [comment]
Are you saying that it should provide spelling corrections when the list would otherwise be empty? For example, when the very first letter is misspelled? I think that could work, but I'd have to play around with it to know for sure.

**Comment by Igorbek** [comment]
@sandersn yes, exactly
