### ISSUE TITLE
Silently removed constructor signature when extending class type

### ISSUE THREAD

**Issue by SaschaNaz** [Microsoft/TypeScript#15349]
**TypeScript Version:**  2.2.1 / nightly (2.2.0-dev.201xxxxx)

**Code**

```ts
declare class A {
}
interface A {
    new (b: boolean);
}

new A(false); // error, no matching signature
```

**Expected behavior:**

It should work or at least there should be a warning message that this will not work.

**Actual behavior:**

`interface A` silently does nothing.

**Comment by mhegazy** [comment]
The interface extends the instance side of the class. so now `new (new A())(false)` is allowed.

**Comment by SaschaNaz** [comment]
Oh.
