### ISSUE TITLE
TS2307 Error during web deploy package creation

### ISSUE THREAD

**Issue by JWiersema** [Microsoft/TypeScript#15345]
**TypeScript Version:**  2.2.1 

I have an ASP.NET MVC project in VS2015 Update 3. When I build or rebuild the project everything goes smoothly. But when I use Publish to Azure to do a web deploy or create a web deploy package, I get multiple errors in the build phase, all like:  error TS2307: Build:Cannot find module 'System'. This started happening after installing TS2.2 (or other MS update on the dev machine?)

**Expected behavior:**
Build works and publish to azure succeeds
**Actual behavior:**
Build does not work, but only when doing web deploy.

**Comment by mhegazy** [comment]
@yuit can you take a look.

**Comment by novakf** [comment]
Until it will be released, check this https://github.com/atomsoftwarestudios/AjsWebApp
Maybe you'll find it handy.
For webdeploy (not described yet, but I count with it) it will be neccessary to exclude some files from AjsWebApp to be published.

**Comment by yuit** [comment]
@JWiersema Does this problem repo in 2.4 as well ?

**Comment by yuit** [comment]
Closing issue for house keeping sake. Please feel free to reopen if you have more info for me or the issue doesn't resolve in 2.4
