### ISSUE TITLE
Show Proper Suggestions within Class Body

### ISSUE THREAD

**Issue by audinue** [Microsoft/TypeScript#15340]
**TypeScript Version:**  2.2.2

**Code**

```ts
class Component {

    /**
     * Called when this component is updated.
     */
    componentUpdated () {
    }
}

class MyComponent extends Component {

    // CTRL+SPACE here...
}
```

**Expected behavior:**
TypeScript [language service] shows proper sugestions **including the documentation** for the class members.

For example:
```ts
constructor
toString
componentUpdated
```

**Actual behavior:**
![screenshot_1](https://cloud.githubusercontent.com/assets/1407800/25334445/d6b57cf4-2918-11e7-903a-bce0ad4112e4.jpg)

TypeScript showed irrelevant suggestions.

**Comment by mhegazy** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/7158
