### ISSUE TITLE
allow +1 be a number literal type

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#15346]
const a : +1 = +1; // <-- problem
const b: 1= +1; // <-- still problem
const c: 1 = 1; // now we all square

**Comment by rozzzly** [comment]
Assuming this is for parity with `const c: -1 = -1;` being valid?

**Comment by aleksey-bykov** [comment]
@rozzzly yes please

**Comment by vkurchatkin** [comment]
@aleksey-bykov second example doesn't work either

**Comment by aleksey-bykov** [comment]
you must be using an old version of TypeScript

**Comment by vkurchatkin** [comment]
@aleksey-bykov not really, built it from source.

**Comment by aleksey-bykov** [comment]
you are right, stupid compiler can't see the constant behind the numberic expression

**Comment by DanielRosenwasser** [comment]
Fixed by #17425.
