### ISSUE TITLE
KeyboardEvent which/keyCode issue

### ISSUE THREAD

**Issue by meeCnu** [Microsoft/TypeScript#15343]
**TypeScript Version:**  2.2.2

**Code**

```ts
added keydown event for input control and written function to capture KeyboardEvent like below 
    validateInput(evt: KeyboardEvent): void {
.....
}
```

**Expected behavior:**

keyCode/which should be different for capital and small characters

**Actual behavior:**
getting keyCode/which as same for both capital and small characters

**Comment by simonsarris** [comment]
`KeyboardEvent.which` and `KeyboardEvent.keyCode` transpile 1:1 to JavaScript. This is not a TypeScript bug, but a mistaken expectation on your part.

`keyCode` and `which` always return the same value for capital and small ASCII characters.

https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode

**Comment by meeCnu** [comment]
Thanks for the reply @simonsarris  

but how javaScript native event object providing different values for the same above case

**Comment by simonsarris** [comment]
I don't know and I cannot debug your code for you. But this is not a TypeScript issue, this is either a browser issue or an issue with your own code.

I suggest the issue be closed.

**Comment by meeCnu** [comment]
Thanks for your reply @simonsarris
