### ISSUE TITLE
#182 for dom.generated.d.ts?

### ISSUE THREAD

**Issue by SaschaNaz** [Microsoft/TypeScript#15348]
**TypeScript Version:**  2.2.1 / nightly (2.2.0-dev.201xxxxx)

**Code**

(Covered by #15338)

```ts
declare var URLSearchParams: {
    prototype: URLSearchParams;
    /**
      * Constructor returning a URLSearchParams object.
      */
    new (init?: string | URLSearchParams): URLSearchParams;

}

new URLSearchParams({key: "730d67"}) // valid but error
```

**Expected behavior:**

#182 should be applied to DOM types

**Actual behavior:**

No way to add a new overload signature before a PR to fix

**Comment by SaschaNaz** [comment]
Or can we please just convert them to classes?

**Comment by DanielRosenwasser** [comment]
Classes wouldn't allow you to add new construct signatures - only new members.

**Comment by SaschaNaz** [comment]
Ah yes, you're right.

**Comment by mhegazy** [comment]
I would not want to add a static interface for every DOM interface, that is a lot of global scope pollution. 

If you are really blocked, just copy lib.d.ts change the declaration, and use it until the issue is fixed.

**Comment by SaschaNaz** [comment]
>that is a lot of global scope pollution.

I agree, but then what do you think about class-ifying them? It will still not allow adding constructor signatures but at least will do for other members.

**Comment by mhegazy** [comment]
I think we should add classes regardless. that is covered by https://github.com/Microsoft/TypeScript/issues/574
