### ISSUE TITLE
Another Temporary variable declared too late

### ISSUE THREAD

**Issue by peblpebl** [Microsoft/TypeScript#15342]
**Code**

[playground](https://www.typescriptlang.org/play/#src=class%20C%20{%0D%0A%20%20%20%20foo%28arg1%2C%20arg2%29%20{%0D%0A%20%20%20%20%20%20%20%20[arg1%2C%20arg2]%20%3D%20[arg2%2C%20arg1]%3B%0D%0A%20%20%20%20%20%20%20%20return%20arg1%3B%0D%0A%20%20%20%20}%0D%0A})

class C {
    foo(arg1, arg2) {
        [arg1, arg2] = [arg2, arg1];
        return arg1;
    }
}

**Expected behavior:**

I would expect any temporary variable declaration to be inserted before use (in this case _a).
I would certainly not expect it after a return statement , giving unreachable code.

**Actual behavior:**

var C = (function () {
    function C() {
    }
    C.prototype.foo = function (arg1, arg2) {
        _a = [arg2, arg1], arg1 = _a[0], arg2 = _a[1];
        return arg1;
        var _a;
    };
    return C;
}());

**Comment by peblpebl** [comment]
[playground](https://www.typescriptlang.org/play/#src=class%20C%20{%0D%0A%20%20%20%20foo%28arg1%2C%20arg2%29%20{%0D%0A%20%20%20%20%20%20%20%20[arg1%2C%20arg2]%20%3D%20[arg2%2C%20arg1]%3B%0D%0A%20%20%20%20%20%20%20%20return%20arg1%3B%0D%0A%20%20%20%20}%0D%0A})

**Comment by ahejlsberg** [comment]
See #4138 and #7297.

**Comment by peblpebl** [comment]
Nearly duplicate of #7297.
