### ISSUE TITLE
Expecting directions on a PR

### ISSUE THREAD

**Issue by nmaxcom** [Microsoft/TypeScript#15354]
I'm the OP in [this post regarding](https://github.com/Microsoft/vscode/issues/25022#issuecomment-295376618) the improvement of TypeScript documentation for VSCode.

The sooner there's info to be known the sooner I can get to work.

Thanks.

**Comment by mhegazy** [comment]
PRs are welcomed. most of the DOM APIs are autogenerated from a script in https://github.com/Microsoft/TSJS-lib-generator. Comments are all kept in https://github.com/Microsoft/TSJS-lib-generator/blob/master/inputfiles/comments.json.

For non-DOM APIs, you can find the sources in https://github.com/Microsoft/TypeScript/tree/master/src/lib, comments can be jsut added to the declarations, and should show in quick info/completion/etc..

**Comment by nmaxcom** [comment]
I'll get on it right away. I like my intellisense with complete doc info :)

**Comment by mhegazy** [comment]
Once the PR makes it in https://github.com/Microsoft/TSJS-lib-generator, I will manually move it to the TS repo, and then it should be in the next day's `typescript@next` package.

**Comment by nmaxcom** [comment]
As soon as I get back home in a few days I'll get on it. Thanks.

**Comment by nmaxcom** [comment]
I'm back :) Trying to piece together all the info so I get this right and everyone's job is as easy as possible. Let's break it down:

1. I want VSCode's quick info to have more explained methods since it's lacking some
1. Quick info pulls from the TypeScript repo, specifically from `lib/lib.d.ts`:
    1. I'm after DOM APIs first (like Element.getAttribute), and you pointed out those should be done in TSJS-lib-generator so I'm a bit lost now. Let me know if you got confused or I'm confused.

So. If it really is lib.d.ts what needs to be modified, and I read there that:

> The files within this directory are used to generate lib.d.ts and lib.es6.d.ts.

![image](https://cloud.githubusercontent.com/assets/8936090/25885143/1b3b6e98-3557-11e7-8360-5efd9734a372.png)

I just have to find in that folder what files contain the` lib.d.ts` bits that I want to modify and PR's those files modified so someone pushes them to` lib.d.ts`. Is that right?

**Comment by mhegazy** [comment]
The DOM APIs come from  https://github.com/Microsoft/TSJS-lib-generator. so you want to make your edits to https://github.com/Microsoft/TSJS-lib-generator/blob/master/inputfiles/comments.json

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
