### ISSUE TITLE
Don't Show Global Extension from @types Module Unless Module is Explicitly Imported

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#15359]
From: https://github.com/Microsoft/vscode/issues/25187

**TypeScript Version:**  2.2.2

**Code**
In a new workspace:

1.  `npm i colors`

```ts
'abc'.|
```

**Expected behavior:**
Only standard string completions are shown.

**Actual behavior:**
Completions from `colors` are also shown. 
<img width="188" alt="screen shot 2017-04-24 at 3 33 57 pm" src="https://cloud.githubusercontent.com/assets/12821956/25361527/7d9c931a-2903-11e7-8d8e-0895ed7e8fda.png">

These items are only valid if `colors` has actually been imported.

**Comment by mhegazy** [comment]
Works for me without an import...
![animation](https://cloud.githubusercontent.com/assets/8000722/25362415/9f4132be-2908-11e7-8ce0-3aa265434c71.gif)

What am i missing?

**Comment by mjbvz** [comment]
Yes, the bug is that we show the completions from `colors` even though they may not be valid in the context

In the case of the original issue filed against VSCode, as far as I know @svipben was not working in a file that referenced `colors` anywhere but the completion items for the module were still shown

**Comment by svipben** [comment]
@mjbvz @mhegazy If you guys are talking if I was using `colors` lib, I wasn't, I was using only `chalk` lib, which showed me these suggestions in all strings (which is out of context).

It shows bad suggestions for string ONLY if I include `chalk` in my file with (`require('chalk')` or `import chalk from 'chalk')`). Tested it right now.

**Comment by mhegazy** [comment]
Ah. OK then. ATA looks through your `package.json` and your `node_modules` to figure out what libraries you need. it found `colors`, if you want to remove it, add it to the exclude list in you ATA config section of your `jsconfig.json`.

```js
{
    "typeAcquisition": {
        "exclude": [
            "colors"
        ]
    }
}
```

**Comment by svipben** [comment]
@mhegazy This is only one solution? I mean there will be update to fix this issue or the fix is this one? Because it seems not so nice :smile:

**Comment by mhegazy** [comment]
ATA is meant to be convenient, you open a file and it figures out all the packages you would use. It does work for the most part. we do have an option to exclude definitions you do not care about. you could also choose to disable it all together:

```ts
{
    "typeAcquisition": {
        "enable": false
    }
}
```

and manage your declarations manually installing `@types` packages.

**Comment by svipben** [comment]
@mhegazy I don't want to install `@types` packages, especially when I'm using ONLY `.js` files. I don't use neither of these options, but anyway thanks.

**Comment by mhegazy** [comment]
ATA is enabled by default. if you want to disable it, add a `jsconfig.json` with:

```ts
{
    "typeAcquisition": {
        "enable": false
    }
}
```

**Comment by svipben** [comment]
@mhegazy Tested, seems it disabled suggestions if I require `chalk` in file, but when all my other suggestions are not working, for e. g. `require('express')` before that it showed me a lot of suggestions and after that option it shows only several not related with `express`. So I think better to don't include this option and instead of that have "bug" with strings, but with good auto completion for other types :smile:

**Comment by mhegazy** [comment]
Then use "exclude" in your `jsconfig.json`:

```ts
{
    "typeAcquisition": {
        "exclude": [
            "colors"
        ]
    }
}

```

**Comment by svipben** [comment]
@mhegazy But this is not solution, I can say it's temp fix for such case. Because imagine right now to configure this for every project and if it will increase in the future? My opinion is need to disable suggestions from `node_modules` if they are not required or imported.

**Comment by gcnew** [comment]
As I understand it, the suggestions you are recieving are valid. They are contaminations of the dependencies you are using. If these properties actually exist, then TypeScript's behaviour is a good warning. However, if they don't, that's a real issue. In the second case, the problem is not necesarily in the compiler, it might also be in the declaration files.
