### ISSUE TITLE
Suggestion: Improved Paths Replacement Modules Support

### ISSUE THREAD

**Issue by jdolle** [microsoft/TypeScript#15353]
My preferred layout for React components is:
```
/src
    /components
        /ComponentName
            /ComponentName.ext
```

Currently, that means my import statements are a bit verbose, `./components/ComponentName/ComponentName`.

I would like to propose an improvement to the `paths` option that would allow me to remove the redundant ComponentName:

```
"paths": {
    "components/*": ["./components/*/*"]
}
```

Currently this path transforms as:
`components/ComponentName` => `components/ComponentName/*`

I am proposing that paths should replace every instance of `*`, instead of just the first, so that "./components/*/*" can be translated to `components/ComponentName/ComponentName` as expected.

**Comment by RyanCavanaugh** [comment]
This doesn't appear to be a common enough scenario to warrant adding support for
