### ISSUE TITLE
setAttribute signature too strict

### ISSUE THREAD

**Issue by mightyiam** [Microsoft/TypeScript#15368]
**TypeScript Version:**  2.2.2

```ts
elm.setAttribute('disabled', true) // should be allowed
elm.setAttribute('disabled', 1) // should be allowed
```

**Expected behavior:**

> value
> A DOMString containing the value to assign to the attribute. **Any non-string value specified is converted automatically into a string**.

https://developer.mozilla.org/en/docs/Web/API/Element/setAttribute

**Actual behavior:**

`setAttribute(name: string, value: string): void`

**Comment by RyanCavanaugh** [comment]
TypeScript generally warns on implicit conversions, e.g. calling `Math.sign("hello world")` is an error *even though* the spec says "hello world" will be converted to a string automatically.

**Comment by mightyiam** [comment]
@RyanCavanaugh I think you might mean "converted to a number automatically". But I'm too laze to check what `Math.sign` does.

**Comment by RyanCavanaugh** [comment]
Right (fixed)

**Comment by mightyiam** [comment]
For `Math.sign` string might not make sense. As in the example you provided @RyanCavanaugh.

For `setAttribute`, I think that `string | number | boolean` is always reasonable, right? That's my PR:
https://github.com/Microsoft/TSJS-lib-generator/pull/237

**Comment by kitsonk** [comment]
Implicit conversion guarding is one of those great features of TypeScript.  I would hate for that to be eroded.

**Comment by calebegg** [comment]
Being able to pass in a boolean or number makes sense for a lot of different types of attributes -- I support this change. It's annoying to have to do `.setAttribute('aria-hidden', (!this.isVisible()).toString())` when the underlying API intentionally supports the simpler `.setAttribute('aria-hidden', !this.isVisible())`

I think this is different than `Math.sign`, since `Math.sign('hello')` is plainly a bug, while `.setAttribute` with a number or boolean is very often valid/desirable.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Comment by mightyiam** [comment]
@mhegazy @RyanCavanaugh I don't agree. This needlessly limiting the DOM interface.

**Comment by mikehaas763** [comment]
I agree that these types protecting us are a good thing out of principle. However, what are we to do when porting existing code to TypeScript?

I have code like `canvas.setAttribute('width', config.canvasWidth);` where `config.canvasWidth` is a `number`. I can't cast a number to a string so how can I make my existing code work?

**Comment by kitsonk** [comment]
```ts
declare global {
  interface Element {
    setAttribute(name: string, value: boolean): void;
    setAttribute(name: string, value: number): void;
  }
}
```
