### ISSUE TITLE
Wrapped types

### ISSUE THREAD

**Issue by mindplay-dk** [Microsoft/TypeScript#15367]
Has anyone proposed support for wrapped types?

I don't know if this is the correct name for it, but what I mean is, the ability to "specialize" primitive types, in the static sense only, e.g. meaning a particular assertion has been made about the pseudo-type or the content, range, format, etc. of a given value.

Examples:

 * Columns (e.g. grid units) are a kind of number
 * Zip-code is a kind of number
 * E-mail address is a kind of string
 * Hex color code is a kind of string
 * User ID is a kind of number

And so on.

Currently we can't define types for these types.

That is, type aliases don't really work for this:

```
type Columns = number;

var c = 12 as Columns; // inferred type is number
```

Becaus they're just aliases, obviously.

But even extending Number into Columns doesn't really work:

```
interface Columns extends Number { }

var c = 12 as Columns; // works, but...

c = 6; // ... doesn't really work
```

Here the type of `c` is `Columns`, but a regular number is direcly assignable to it with no assertion about the unit - there's no guarantee here that 6 is actually a number of columns.

So the behavior I'm looking for is something more along the lines of this:

```
typedef Columns = number;

var c = 12 as Columns; // c inferred as Columns

c = 6; // should error
```

So `typedef` would work more like `extends`, but with stricter type-checking: you should be able to cast a `number` to `Columns`, but the compiler should *not* permit you to *implicitly* cast a `number` literal to `Columns`.

This would enable us to make "type-casts" in the form of simple functions that make various assertions - for example:

```
typedef Color = string;

function color(hex: string): Color {
    if (/^[0-9a-f]{6}$/.test(hex)) {
        return hex as Color;
    }
    throw new Error("out of range: " + hex);
}

let maroon = color("ee30a7");

let blue = color("blue"); // throws Error
```

How come we don't have this feature?

Seems like this would be low hanging fruit?

**Comment by jesseschalken** [comment]
I would just wrap it in a class with a private property to get nominal typing.

```ts
class Color {
    constructor(private value: string) {
        if (!/^[0-9a-f]{6}$/.test(value)) {
            throw new Error("out of range: " + value);
        }
    }

    toString(): string {
        return this.value;
    }
}
```

The cast has to be explicit both ways though (`new Color(string)`, `color->toString()`).

Otherwise I tend to do what you want in Hack using `newtype`, which creates a type that only the file it is declared in has permission to instantiate. For example Hack (and PHP) have no native type for text/unicode, only `string` which is a byte string, so to express that a string is valid UTF-8 in the type system I have a file like this:

```php
newtype utf8 as string = string;

function assert_utf8(string $x): utf8 {
  if (!\preg_match('//u', $x)) {
    throw new Exception('Invalid UTF8');
  }
  return $x;
}

function concat_utf8(utf8 ...$xs): utf8 {
  return \join('', $xs);
}

// .. other utils for utf8 strings
```

Then `utf8` can be used as `string` anywhere, but to create a `utf8` you have to go through `assert_utf8()`, and there is no boxing/unboxing overhead.

**Comment by aleksey-bykov** [comment]
@mindplay-dk take a look at this: #4895

**Comment by svieira** [comment]
This is also discussed at some length in #202 - there is already a way to do this that works for `number` as well using enums:

```typescript
interface Nominal<T> {
    'nominal structural brand': T
}

const enum ColumnsT { }
const enum RowsT { }

type Rows = number & Nominal<RowsT>
type Columns = number & Nominal<ColumnsT>

const x = 123 as Rows
const y = 123 as Columns

let z: Rows = y; // error
let a: Rows = 123; // error

// Colors

const enum ColorT { }
type Color = string & ColorT

function color(hex: string): Color {
    if (/^[0-9a-f]{6}$/.test(hex)) {
        return hex as Color;
    }
    throw new Error("out of range: " + hex);
}

let b = color('FFFFFF');
let c: Color = 'CCCCCC'; // error
```

**Comment by mindplay-dk** [comment]
@svieira so this kind of uses a dummy enum as a "tag" of sorts - that's a clever hack, but kind of pollutes the type-space and it's not really semantic. It's clever though :-)

I suppose I'll hold out for tags.

@RyanCavanaugh so tags is the solution, is why you marked this a duplicate, correct?

**Comment by jesseschalken** [comment]
@mindplay-dk Is the reason you don't want a wrapper class because of the boxing/unboxing overhead (both syntactic overhead and runtime overhead)?

**Comment by mindplay-dk** [comment]
@jesseschalken boxing/unboxing has more side-effects and drawbacks besides the (memory and CPU) overhead, but, yeah - that's one reason. Tags look interesting and solve the same (and more) problems, so let's see where that leads :-)

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
