### ISSUE TITLE
Type inference for string index is not correct

### ISSUE THREAD

**Issue by thynson** [Microsoft/TypeScript#15365]
**TypeScript Version:**  2.2.2

**Code**

```ts

interface PlainObject {
    [idx: string]: PlainObject | number | string | boolean | Array<PlainObject> | null | undefined
}

let x: PlainObject = {
    yy: {
        zz : 1
    }
};
console.log(x.yy.zz);
```

**Expected behavior:**
No compile error

**Actual behavior:**
Error:(54, 18) TS2339:Property 'zz' does not exist on type 'string | number | boolean | PlainObject | PlainObject[]'.
  Property 'zz' does not exist on type 'string'.

**Comment by RyanCavanaugh** [comment]
The information about the type of the object literal was "lost" when you wrote an explicit type annotation. Without a type guard on `x.yy` we don't know what its type is; it could be `number` for example, in which case there is no `zz` property

**Comment by thynson** [comment]
Thanks for explain.
