### ISSUE TITLE
tsconfig outFile generates SystemJS module names using the first innermost common ts file directory

### ISSUE THREAD

**Issue by bessgeor** [Microsoft/TypeScript#15373]
**TypeScript Version:**  2.2.1

**Code**
tsconfig.json:
```json
{
	"compileOnSave": true,
	"compilerOptions": {
		"noImplicitAny": false,
		"noEmitOnError": true,
		"removeComments": false,
		"sourceMap": true,
		"target": "es5",
		"jsx": "react",
		"module": "system",
		"outFile": "Content/cid.demo.js"
	},
	"exclude": [
		"node_modules",
		"wwwroot"
	]
}
```

Main layout used everywhere, before Content/cid.demo.js is loaded
```js
SystemJS.config( { baseURL: '/' } );
System.defaultJSExtensions = true;
```

Foo.ts
```ts
export class Foo { a: number; }
```

Bar.ts
```ts
export class Bar { b: number; }
```

## Case 1, working as expected
Foo.ts is located at {ProjectRoot}/Tasks/
Bar.ts is located at {ProjectRoot}/Accounts/

**Behavior:**

Content/cid.demo.js contains modules
```js
System.register("Tasks/Foo", ...
System.register("Accounts/Bar", ...
```

## Case 2, bug
Foo.ts is located at {ProjectRoot}/Tasks/
Bar.ts is not existing

**Expected behavior:**
Content/cid.demo.js contains module
```js
System.register("Tasks/Foo", ...
```

**Actual behavior:**
Content/cid.demo.js contains module
```js
System.register("Foo", ...
```

So if I use module name specified above, if someone will add an .ts file somewhere outside of Tasks directory, she will break my
```js
SystemJS.import( 'Foo' ).then( ...
```

I can still use
```js
SystemJS.import( 'Tasks/Foo' ).then( ...
```
but it issues additional http request until someone will add an .ts file somewhere outside of Tasks directory.

**Comment by mhegazy** [comment]
Can you set `--rootDir ./`?

**Comment by bessgeor** [comment]
Added
```json
"rootDir": "./"
```
into compilerOptions section of tsconfig.json

Now both of the cases are working as expected, thank you.

**Comment by mhegazy** [comment]
glad that helped.
