### ISSUE TITLE
Error TS2346 when importing React components written in JavaScript 

### ISSUE THREAD

**Issue by mohsen1** [Microsoft/TypeScript#15375]
**TypeScript Version:**  2.3.0

**Code**
See repo here: https://github.com/mohsen1/ts23-super-issue

```js
import React from 'react';

export default class Component extends React.Component {
    constructor(...args) {
        super(...args)
    }
}
```

**Expected behavior:**

No error

**Actual behavior:**

```
Error: src/component.js(5,9): error TS2346: Supplied parameters do not match any signature of call target.
```

**Comment by mhegazy** [comment]
Covered by https://github.com/Microsoft/TypeScript/issues/5296

**Comment by mohsen1** [comment]
This is a very common pattern in React. For now we can `@ts-ignore` that line.


```js
import React from 'react';

export default class Component extends React.Component {
    constructor(...args) {
        // @ts-ignore
        super(...args)
    }
}
```

**Comment by silicakes** [comment]
It also seems that TypeScript ignores the good 'ol es5 spread pattern:
`super.apply(this, ...args);`

#### A more complete demo:

```
function bar(a: any, b: any, c: any): void { 
    console.log(a, b, c);
}

function foo(a: number, b: number, c: number): void {
    bar.apply(null, arguments);
}
```

**Comment by Almenon** [comment]
Has this not been fixed or am I doing someting wrong? Just ran into this issue with typescript 2.9.1

```typescript
    public handleSpawnError(pythonCommand:string, pythonPath:string, err:string){
        this.pythonPreview.handleSpawnError(...arguments)
         // gives me error: Expected three arguments, but got 0 or more
    }
```

pythonPreview:
```typescript
    public handleSpawnError(pythonCommand:string, pythonPath:string, err:string){
        // ... code is irrelevant
    }
```

**Comment by shirshak55** [comment]
```(super as any)(...args)```

**Comment by bluEEil** [comment]
I couldn't find online any good solution to writing stuffs like:

`authenticateUser = (...args: any[]) => this.authManager.authenticateUser(...args);`

Is there any update on a way to do this without having to do something ugly like:

`authenticateUser = (...args: any[]) => (this.authManager.authenticateUser as any)(...args);`
