### ISSUE TITLE
Union type enums clash at runtime

### ISSUE THREAD

**Issue by Jameskmonger** [Microsoft/TypeScript#15372]
**TypeScript Version:**  2.2.1

**Code**

```ts
enum LightColor {
  RED,
  BLUE
}

enum DarkColor {
  GREY,
  BLACK
}

const evaluateColor = (color: LightColor | DarkColor) => {
  if (color === LightColor.RED || color === LightColor.BLUE) {
    console.log("Color is light!");
  }

  if (color === DarkColor.GREY || color === DarkColor.BLACK) {
    console.log("Color is dark!");
  }
};

evaluateColor(LightColor.RED);
evaluateColor(DarkColor.GREY);
```

**Expected behavior:**
Output should be:
```
Color is light!
Color is dark!
```

**Actual behavior:**
Output is:
```
Color is light!
Color is dark!
Color is light!
Color is dark!
```

This is because at runtime, `DarkColor.GREY` and `LightColor.RED` are both 0, and `DarkColor.BLACK` and `LightColor.BLUE` are both 1.

**Comment by Jameskmonger** [comment]
My real-world use case for this is as follows:

I have two methods on a ByteBuffer: `push16BitInt` and `push32BitInt`. I want each to take a number and an "order" - which specifies whether the data should be sent in little-endian or big-endian order.

However, `push32BitInt` should also allow you to specify little-endian-mixed or big-endian-mixed - `push16BitInt` should not let you. I want to split the enum apart so that the TypeScript compiler can catch this, rather than being at runtime.

Here is my code:

```
enum DataOrder {
    LITTLE_ENDIAN,
    BIG_ENDIAN
}

enum DataOrderMixed {
    LITTLE_ENDIAN_MIXED,
    BIG_ENDIAN_MIXED
}

// only take non-mixed data orders
public push16BitInt(value: number, order: DataOrder) { }

// take mixed or non-mixed data orders
public push32BitInt(value: number, order: DataOrder | DataOrderMixed) { }
```

**Comment by Jameskmonger** [comment]
I can of course solve this by manually applying values to the enum children, but I'm not sure if that is the intended solution:

```
enum LightColor {
  RED = 0,
  BLUE = 1
}

enum DarkColor {
  GREY = 2,
  BLACK = 3
}
```

**Comment by NN---** [comment]
Possible solution is to use literals:

```ts
enum LightColor {
  RED = "RED" as any,
  BLUE = "BLUE" as any
}

enum DarkColor {
  GREY = "GREY" as any,
  BLACK = "BLACK" as any
}

var b = LightColor.BLUE;
if (b == DarkColor.GREY) { // Doesn't compile!
    
}
```

**Comment by RyanCavanaugh** [comment]
Types are erased; accepting *either* of two enums that have overlapping values is not going to work. Not clear what a solution on the TS side would even look like given full erasure of types.
