### ISSUE TITLE
[Proposal]: Template string literal types

### ISSUE THREAD

**Issue by ErikCupal** [Microsoft/TypeScript#15382]
There are cases when string literal types are not expressive enough. Consider this example:

```ts
// CSS margin type
type Margin: string;
```

This is not bad, but the string type could be narrowed down. For this example, we would probably want to allow values like `"10px"`, `"15%"`, `"1em"`, `"1rem"`.... There is is definitely a pattern here: `number` and (`"px"` | `"%"` | `"em"` | `"rem"`).

My idea looks like this:

```ts
// let's allow number + "px"
type Margin: `${number}px`;

const a: Margin = "5px"; // ok
const b: Margin = "5blabla"; // error

// let's allow number + ("px" | "%" | "em" | "rem")
type Margin: `${number}${"px" | "%" | "em" | "rem"}`;

const a: Margin = "5px"; // ok
const b: Margin = "5blabla"; // error
const c: Margin = "5rem"; // ok
```

It looks very much like template strings and it actually behave very similarly. The only difference is that we do not put primitive/array/object in the dollar brackets `${}`. Instead we put there a type. Allowing putting there any type would not make much sense. The only possible types that could be put there are `string`, `number` and discriminated unions created from `string` and `number`.

I would be happy for any suggestion or comment 😊. I'm not sure how complex this would be to implement, hope not so much. If there is already an issue with such a proposal, I'm sorry - didn't found it.

**Comment by mhegazy** [comment]
Looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/6579

**Comment by ErikCupal** [comment]
@mhegazy Yup, sorry for duplicate
