### ISSUE TITLE
'debugger' statement in the tsserver assert function?

### ISSUE THREAD

**Issue by egamma** [Microsoft/TypeScript#15389]
When there is an assertion failure in the tsserver, then the tsserver appears to hang to the user without any visible indication of the error state. This is caused by a `debugger` statement inside the assert function. This will make the tsserver wait until a debugger attaches. This makes good sense under development, but it is confusing to the user in production.

```js
        function assert(expression, message, verboseDebugInfo) {
            if (!expression) {
                var verboseDebugString = "";
                if (verboseDebugInfo) {
                    verboseDebugString = "\r\nVerbose Debug Information: " + verboseDebugInfo();
                }
                debugger;
                throw new Error("Debug Failure. False expression: " + (message || "") + verboseDebugString);
            }
        }
```

**Comment by mhegazy** [comment]
Is the node process for tsserver started under debug? do you have `TSS_DEBUG` set?

**Comment by fatcerberus** [comment]
I was under the impression that `debugger;` is a no-op when a debugger is not attached.  Kind of odd it would hang like that.

**Comment by egamma** [comment]
Closing I had the `TSS_DEBUG` environment variable set.
