### ISSUE TITLE
broken link in docs on site

### ISSUE THREAD

**Issue by tolik89u** [Microsoft/TypeScript#15384]
On [this page](http://www.typescriptlang.org/docs/handbook/react-&-webpack.html) in docs on TypeScript's site there's a link:

> You can learn more about tsconfig.json files [here](http://www.typescriptlang.org/tsconfig-json.html).

but that page is missing:

> The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

**Comment by simonsarris** [comment]
Good catch, pull request for fix is here: https://github.com/Microsoft/TypeScript-Handbook/pull/567

**Comment by mhegazy** [comment]
fixed by https://github.com/Microsoft/TypeScript-Handbook/pull/566
