### ISSUE TITLE
[bug?] "this" is possibly undefined inside class method.

### ISSUE THREAD

**Issue by trusktr** [Microsoft/TypeScript#15385]
**TypeScript Version:**  2.2.1 

**Code**
I've got a class method that looks like this:

```ts
 updateHeight() {
     if (this.frame) cancelAnimationFrame(this.frame)

     this.frame = requestAnimationFrame(() => {
         const el = ReactDOM.findDOMNode(this.foo).children[0]
         const height = el != null ? el.clientHeight +
             this // <-- HERE, error line number points here
                 .props.padding || 0 :
             0
         this.setState({ height })
         this.frame = 0
     })
 }
```

**Expected behavior:**

It should work.

**Actual behavior:**
Instead TypeScript says

```
ERROR in ./src/foo.tsx
(XX,XX): error TS2532: Object is possibly 'undefined'.
```

I can work around the problem for now, by casting `this` to `any` like so:

```ts
 updateHeight() {
     if (this.frame) cancelAnimationFrame(this.frame)

     this.frame = requestAnimationFrame(() => {
         const el = ReactDOM.findDOMNode(this.foo).children[0]
         const height = el != null ? el.clientHeight +
             (this as any) // <-- HERE, works fine now.
                 .props.padding || 0 :
             0
         this.setState({ height })
         this.frame = 0
     })
 }
```

Seems like a bug, how can `this` ever be undefined?

The error specifically happens on that line where `this` is, not on the `.props.padding` line, which is hinting to me that it isn't `props` that could be undefined (unless the error is pointing to the wrong line?).

This is a React component.

**Comment by RyanCavanaugh** [comment]
I tried to make this self-contained, but the error does not occur:
```ts
class X {
    props: any = null;
    updateHeight() {
        requestAnimationFrame(() => {
            const el: any = null;
            const height = el != null ? el.clientHeight +
                this // <-- no error
                    .props.padding || 0 :
                0
        });
    }
}
```

Please provide a self-contained repro as indicated in the template instructions.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Comment by trusktr** [comment]
I'm not sure how to replicate in a simple way. The code I have is much more complex than that example, and yes that example works fine, but I have some private code I'm not allowed to share, and it is much bigger, and the problem does happen. Oh well, Maybe someone else will stumble on it with a non-private example sometime.
