### ISSUE TITLE
Lookup types always return the any type when property is prefixed with at least two underscores

### ISSUE THREAD

**Issue by RoboPhred** [Microsoft/TypeScript#15383]
**TypeScript Version:**  2.2.2

When using a type lookup, the resulting type is always "any" if the property name is prefixed with two (and exactly two) underscores.

**Code**

```

// getProperty func copied from TS 2.1 release notes:
function getProperty<T, K extends keyof T>(obj: T, key: K) {
    return obj[key];  // Inferred type is T[K]
}

const obj = {
    str: "foo",
    _str: "bar",
    __str: "baz",
    ___str: "egg"
};

const strVal = getProperty(obj, "str"); // typed "string"
const _strVal = getProperty(obj, "_str"); // typed "string"
const __strVal = getProperty(obj, "__str"); // INCORRECT: typed "any"
const ___strVal = getProperty(obj, "___str"); // typed "string"
```

**Expected behavior:**
The type of obj["__str"] and __strVal should be string

**Actual behavior:**
The type of obj["__str] and __strVal is any

**Comment by RoboPhred** [comment]
I reworked my use case to use 3 underscores which works in the example above, but the same issue happened.  It seems the issue is dependent on other properties in the object:

```
// Single value with 1 underscore gets correct type
const obj6 = {
    _tsReplyTypeMeta: 42    
};
const _tsReplyTypeMeta6 = getProperty(obj6, "_tsReplyTypeMeta"); // CORRECT: typed "number"

// Single value with 2 underscore gets incorrect type
const obj7 = {
    __tsReplyTypeMeta: 42    
};
const __tsReplyTypeMeta6 = getProperty(obj7, "__tsReplyTypeMeta"); // INCORRECT: typed "any"

// Single value with 3 underscores gets incorrect type
//  Still broken after vscode restart
const obj2 = {
    ___tsReplyTypeMeta: 42    
};
const ___tsReplyTypeMeta2 = getProperty(obj2, "___tsReplyTypeMeta"); // INCORRECT: typed "any"


// Two values, 2-underscore is incorrect, 3-underscore is correct.
const obj3 = {
    __tsReplyTypeMeta: 42,
    ___tsReplyTypeMeta: 42
};
const __tsReplyTypeMeta3 = getProperty(obj3, "__tsReplyTypeMeta"); // INCORRECT: typed "any" (2 underscores)
const ___tsReplyTypeMeta3 = getProperty(obj3, "___tsReplyTypeMeta"); // CORRECT: typed "number" (3 underscores)


// Two values, order swapped: same as above.
const obj4 = {
    ___tsReplyTypeMeta: 42,
    __tsReplyTypeMeta: 42
};
const ___tsReplyTypeMeta4 = getProperty(obj4, "___tsReplyTypeMeta"); // CORRECT: typed "number" (3 underscores)
const __tsReplyTypeMeta4 = getProperty(obj4, "__tsReplyTypeMeta"); // INCORRECT: typed "any" (2 underscores)

// Three values: 2-underscore is incorrect.
const obj5 = {
    __tsReplyTypeMeta: 42,
    ___tsReplyTypeMeta: 42,
    ____tsReplyTypeMeta: 42,
};
const __tsReplyTypeMeta5 = getProperty(obj5, "__tsReplyTypeMeta"); // INCORRECT: typed "any" (2 underscores)
const ___tsReplyTypeMeta5 = getProperty(obj5, "___tsReplyTypeMeta"); // CORRECT: typed "number" (3 underscores)
const ____tsReplyTypeMeta5 = getProperty(obj5, "____tsReplyTypeMeta"); // CORRECT: typed "number" (3 underscores)

```

[Playground link](https://www.typescriptlang.org/play/#src=function%20getProperty%3CT%2C%20K%20extends%20keyof%20T%3E(obj%3A%20T%2C%20key%3A%20K)%20%7B%0D%0A%20%20%20%20return%20obj%5Bkey%5D%3B%20%20%2F%2F%20Inferred%20type%20is%20T%5BK%5D%0D%0A%7D%0D%0A%0D%0A%2F%2F%20Single%20value%20with%201%20underscore%20gets%20correct%20type%0D%0Aconst%20obj6%20%3D%20%7B%0D%0A%20%20%20%20_tsReplyTypeMeta%3A%2042%20%20%20%20%0D%0A%7D%3B%0D%0Aconst%20_tsReplyTypeMeta6%20%3D%20getProperty(obj6%2C%20%22_tsReplyTypeMeta%22)%3B%20%2F%2F%20CORRECT%3A%20typed%20%22number%22%0D%0A%0D%0A%2F%2F%20Single%20value%20with%202%20underscore%20gets%20incorrect%20type%0D%0Aconst%20obj7%20%3D%20%7B%0D%0A%20%20%20%20__tsReplyTypeMeta%3A%2042%20%20%20%20%0D%0A%7D%3B%0D%0Aconst%20__tsReplyTypeMeta6%20%3D%20getProperty(obj7%2C%20%22__tsReplyTypeMeta%22)%3B%20%2F%2F%20INCORRECT%3A%20typed%20%22any%22%0D%0A%0D%0A%2F%2F%20Single%20value%20with%203%20underscores%20gets%20incorrect%20type%0D%0A%2F%2F%20%20Still%20broken%20after%20vscode%20restart%0D%0Aconst%20obj2%20%3D%20%7B%0D%0A%20%20%20%20___tsReplyTypeMeta%3A%2042%20%20%20%20%0D%0A%7D%3B%0D%0Aconst%20___tsReplyTypeMeta2%20%3D%20getProperty(obj2%2C%20%22___tsReplyTypeMeta%22)%3B%20%2F%2F%20INCORRECT%3A%20typed%20%22any%22%0D%0A%0D%0A%0D%0A%2F%2F%20Two%20values%2C%202-underscore%20is%20incorrect%2C%203-underscore%20is%20correct.%0D%0Aconst%20obj3%20%3D%20%7B%0D%0A%20%20%20%20__tsReplyTypeMeta%3A%2042%2C%0D%0A%20%20%20%20___tsReplyTypeMeta%3A%2042%0D%0A%7D%3B%0D%0Aconst%20__tsReplyTypeMeta3%20%3D%20getProperty(obj3%2C%20%22__tsReplyTypeMeta%22)%3B%20%2F%2F%20INCORRECT%3A%20typed%20%22any%22%20(2%20underscores)%0D%0Aconst%20___tsReplyTypeMeta3%20%3D%20getProperty(obj3%2C%20%22___tsReplyTypeMeta%22)%3B%20%2F%2F%20CORRECT%3A%20typed%20%22number%22%20(3%20underscores)%0D%0A%0D%0A%0D%0A%2F%2F%20Two%20values%2C%20order%20swapped%3A%20same%20as%20above.%0D%0Aconst%20obj4%20%3D%20%7B%0D%0A%20%20%20%20___tsReplyTypeMeta%3A%2042%2C%0D%0A%20%20%20%20__tsReplyTypeMeta%3A%2042%0D%0A%7D%3B%0D%0Aconst%20___tsReplyTypeMeta4%20%3D%20getProperty(obj4%2C%20%22___tsReplyTypeMeta%22)%3B%20%2F%2F%20CORRECT%3A%20typed%20%22number%22%20(3%20underscores)%0D%0Aconst%20__tsReplyTypeMeta4%20%3D%20getProperty(obj4%2C%20%22__tsReplyTypeMeta%22)%3B%20%2F%2F%20INCORRECT%3A%20typed%20%22any%22%20(2%20underscores)%0D%0A%0D%0A%2F%2F%20Three%20values%3A%202-underscore%20is%20incorrect.%0D%0Aconst%20obj5%20%3D%20%7B%0D%0A%20%20%20%20__tsReplyTypeMeta%3A%2042%2C%0D%0A%20%20%20%20___tsReplyTypeMeta%3A%2042%2C%0D%0A%20%20%20%20____tsReplyTypeMeta%3A%2042%2C%0D%0A%7D%3B%0D%0Aconst%20__tsReplyTypeMeta5%20%3D%20getProperty(obj5%2C%20%22__tsReplyTypeMeta%22)%3B%20%2F%2F%20INCORRECT%3A%20typed%20%22any%22%20(2%20underscores)%0D%0Aconst%20___tsReplyTypeMeta5%20%3D%20getProperty(obj5%2C%20%22___tsReplyTypeMeta%22)%3B%20%2F%2F%20CORRECT%3A%20typed%20%22number%22%20(3%20underscores)%0D%0Aconst%20____tsReplyTypeMeta5%20%3D%20getProperty(obj5%2C%20%22____tsReplyTypeMeta%22)%3B%20%2F%2F%20CORRECT%3A%20typed%20%22number%22%20(3%20underscores)%0D%0A)

It seems the issue will only affect the lowest variable prefix count per unprefixed-name when the count is > 1

For example:
```
let obj =  {
 _first: 42,
__first: 42, // Lookup will be incorrect with 2 underscores
___first: 42, // lookup will be correct with 3 underscores
 _second: 42,
 ___second: 42, // Lookup will be incorrect with 3 underscores, as ___second is not defined
}
```

**Comment by DanielRosenwasser** [comment]
Potentially something related to `escapeIdentifier`

**Comment by mhegazy** [comment]
Should be fixed in latest.
