### ISSUE TITLE
Changing a property to use getters/setters alters behavior of Object.keys because property set on protoype and not instance

### ISSUE THREAD

**Issue by willseitz** [Microsoft/TypeScript#15396]
**TypeScript Version:**  2.2.1 / nightly (2.2.0-dev.201xxxxx)

When I transition from a using a basic property to one using getters/setters code behavior changes. This is because property show up in Object.keys while properties with getters/setters are set on the prototype and therefore don't show up using Object.keys. Using getters and setters should probably encapsulate a property instead of changing its behavior. Note that this setting of properties on the prototype will mess up the stuff in https://github.com/tc39/proposal-class-public-fields/blob/24232cb/README.md#instance-field-declaration-process

**Code**

```ts
class Greeter {
    //greeting: string;
    _greeting: string;
    constructor(message: string) {
        this.greeting = message;
    }
    greet() {
        return "Hello, " + this.greeting;
    }

    get greeting(): string {
        return this._greeting;
    }

    set greeting(g: string) {
        this._greeting = g;
    }
}

let greeter = new Greeter("world");

alert(Object.keys(greeter))

```

**Expected behavior:**

Alert includes greeting because using getters and setters shouldn't change external behavior

**Actual behavior:**

Alert doesn't include greeting (just _greeting) because property is defined on prototype which is not iterated by Object.keys

**Comment by RyanCavanaugh** [comment]
This is the ES6 behavior.

![image](https://cloud.githubusercontent.com/assets/6685088/25454324/eed46c32-2a80-11e7-87c0-d5da3de267c6.png)
