### ISSUE TITLE
Bundle generator runtime for async / await only if absolutely necessary

### ISSUE THREAD

**Issue by avindra** [Microsoft/TypeScript#15393]
The babel toolchain has [babel-preset-env](https://github.com/babel/babel-preset-env), which has rich support for polyfilling things only if they are absolutely necessary.

For example, with the following `.babelrc` file:

```json
{
  "presets": [
    ["env", {
      "targets": {
        "browsers": ["last 2 versions"]
      }
   }]
  ]
}
```

You can only polyfill the things you need to support the last 2 stable versions of every released browser.

Further, you can do:

```json
{
  "presets": [
    ["env", {
      "targets": {
        "node": true
      }
    }]
  ]
}
```

Which will target the current version of node you are running. This is terrific feature.

In this instance, with `"node" : true`, if you run babel using the latest stable version of node, babel will *not* include the regenerator runtime, since `async` / `await` is natively supported in node 7.6 and higher.

----

I am particularly interested in `async`/`await` since the runtime for it is the heaviest out of all the polyfills, and causes the most stack trace pollution, but this concept should really apply to any ECMAScript feature that can be polyfilled.

Given the context above, my questions are  :

 * Is this currently possible with `tsc` / `tsconfig.json` options?
 * If not, is something planned?
 * Is there any way to de-duplicate the `async`/`await` runtime in projects that use `typescript` AND `babel`? Both compilers use their own runtimes, which is wasteful, especially in client side javascript bundles.

**Comment by mhegazy** [comment]
TypeScript does not have a fine-grained transformation management. there is however `--target` flag that allows you to choose an ES version to target. for instance `--target ES2017` will not transform generators or async/await. 

you can also use `--target ESNext`, this will not transform any feature that is on the standards track,  and then pass the output into babel to do a more fine-grained transformation.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
