### ISSUE TITLE
Type 'a'|'b' is assignable to 'a' in overwriting method signature of subclass

### ISSUE THREAD

**Issue by janv** [Microsoft/TypeScript#15391]
**TypeScript Version:**  2.2.2

**Code**
```ts
// Working Example
function Baz(x: 'a' | 'b') {
    var y:'a' = x
}
// This correctly errors:
// Type '"a" | "b"' is not assignable to type '"a"'.
//  Type '"b"' is not assignable to type '"a"'.

// Failing Example
class Foo {
  x(x:'a'|'b'):void {}
}

class Bar extends Foo {
  x(x:'a'):void {}
}

var foo:Foo = new Foo()
var bar:Foo = new Bar()

foo.x('b')
bar.x('b') // Whoa there!
```
<a href="http://www.typescriptlang.org/play/index.html#src=%2F%2F%20Working%20Example%0Afunction%20Baz(x%3A%20'a'%20%7C%20'b')%20%7B%0A%20%20%20%20var%20y%3A'a'%20%3D%20x%0A%7D%0A%0A%2F%2F%20Failing%20Example%0Aclass%20Foo%20%7B%0A%20%20x(x%3A'a'%7C'b')%3Avoid%20%7B%7D%0A%7D%0A%0Aclass%20Bar%20extends%20Foo%20%7B%0A%20%20x(x%3A'a')%3Avoid%20%7B%7D%0A%7D%0A%0Avar%20foo%3AFoo%20%3D%20new%20Foo()%0Avar%20bar%3AFoo%20%3D%20new%20Bar()%0A%0Afoo.x('b')%0Abar.x('b')">Playground link<a/>

**Expected behavior:**
The extension of class `Foo` by `Bar` should fail because the signatures of the `x` method implementations are incompatible as illustrated in the last 4 lines.

- Calling `Foo.x` with `'b'` is allowed.
- We should be able to transparently substitute instances of `Foo` with instances of `Bar` since `Bar` is a subclass of `Foo`
- But `Bar.x` does not accept `'b'` as an argument

**Actual behavior:**

Typescript doesn't complain and let's me extend `Foo` with `Bar`.

As seen in the `Baz` function, checking assignability of Unions seems to work in other cases but apparently not in the case of method overwriting by a subclass.

**Comment by mhegazy** [comment]
Please see https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-function-parameters-bivariant

**Comment by janv** [comment]
Interesting, thank you

Linking these here for completeness:
- https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Type%20Compatibility.md#function-parameter-bivariance
- https://github.com/Igorbek/TypeScript-proposals/tree/covariance/covariance
- https://github.com/Microsoft/TypeScript/issues/10717
- https://github.com/Microsoft/TypeScript/issues/1394
