### ISSUE TITLE
feature request: question mark expression for shorten safe nullable call

### ISSUE THREAD

**Issue by zh99998** [Microsoft/TypeScript#15406]
allow expr?.func() syntax shorten for "call func only if expr not null"
like https://angular.io/docs/ts/latest/guide/template-syntax.html#!#safe-navigation-operator
or https://kotlinlang.org/docs/reference/null-safety.html#safe-calls

**Code**

expr is a nullable expression

```ts
expr?.attr
expr?.func()

```

**Compile to**
```js
expr == null ? expr : expr.attr
expr == null ? expr : expr.func()
```

**Comment by blakeembrey** [comment]
See https://github.com/Microsoft/TypeScript/issues/16 😄
