### ISSUE TITLE
Different enums in the same function scope need different names

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#15403]
**TypeScript Version:**   nightly (2.3.0-dev.20170426)

**Code**

```ts
function f() {
    {
        enum E { A = 1 }
    }
    {
        enum E { A = 3 }
        console.log(E);
    }
}

f();
```

**Expected behavior:**

`{ '3': 'A', A: 3 }`

**Actual behavior:**

`{ '1': 'A', '3': 'A', A: 3 }`

This is because we compile these two different enums as `var`s in the same function scope:

```js
function f() {
    {
        var E;
        (function (E) {
            E[E["A"] = 1] = "A";
        })(E || (E = {}));
    }
    {
        var E;
        (function (E) {
            E[E["A"] = 3] = "A";
        })(E || (E = {}));
        console.log(E);
    }
}
f();
```

Similar to #15401, but doesn't depend on `--target`.

**Comment by rbuckton** [comment]
See my [comment](https://github.com/Microsoft/TypeScript/issues/15401#issuecomment-297553810) in #15401. I'm in favor of `enum` and `const enum` being block-scoped at runtime if that's how we're treating it at design time.

**Comment by rbuckton** [comment]
Turns out we have the same issue for classes as well.

**Comment by rbuckton** [comment]
Another example of this issue:
```ts
{ class C { A = 1 } }
{ enum C { B = 2 } }
```

For the emit resolver, the checker does not consider it a collision if the block-scoped declaration does not hide another declaration in an outer scope. We probably need to consider it a collision if there are any declarations with the same name in any block scopes in the same non-block scope container. For example:

```ts
{
  // (1)
  class C {}
}
{
  {
    // collides with (1)
    class C { }
  }
}
```

**Comment by rbuckton** [comment]
Interestingly enough, if I emit the enum as a `let` declaration, our existing transforms will inject an assignment to `void 0`, which seems to address this:

```js
{
    var E = void 0;
    (function (E) {
        E[E["A"] = 1] = "A";
    })(E || (E = {}));
}
{
    var E = void 0;
    (function (E) {
        E[E["A"] = 3] = "A";
    })(E || (E = {}));
}
```
