### ISSUE TITLE
Possible regression with JSX and 2.3.1: Type '{}' is not assignable to type 'void'

### ISSUE THREAD

**Issue by tkrotoff** [Microsoft/TypeScript#15409]
With TypeScript 2.3.1 and 2.4.0-dev.20170427:

```ts
import * as React from 'react';
import * as ReactDOM from 'react-dom';

const FooBar1 = () => (
  <div></div>
);

const FooBar2: React.SFC<void> = () => (
  <div></div>
);

const FooBar3: React.SFC<{}> = () => (
  <div></div>
);

ReactDOM.render(
  <div>
    <FooBar1 />
    
    <FooBar2 />
    // error TS2322: Type '{}' is not assignable to type 'IntrinsicAttributes & void & { children?: ReactNode; }'.
    //   Type '{}' is not assignable to type 'void'.

    <FooBar3 />
  </div>,
  document.getElementById('app')
);
```

With TypeScript 2.2 => no error.

Is it an expected behavior?

**Comment by yuit** [comment]
@tkrotoff this is expected so `props` in React is always empty object even when you don't specify any attribute. [Here](https://github.com/facebook/react/blob/master/src/isomorphic/classic/element/ReactElement.js#L187) So with the 2.3 we parse JSX expression with no attributes the same way (e.g it is an empty object literal) that is why it is not assignable to `void`.

**Comment by tkrotoff** [comment]
@yuit Ok, thx for the answer
