### ISSUE TITLE
Variable declared after use in generated code

### ISSUE THREAD

**Issue by tsvetomir** [Microsoft/TypeScript#15410]
**TypeScript Version:**  2.2.2

**Code**

```ts
function foo() {
    const key = 'bar';

    return {
        [key || 'baz']: true
    }
}
```

**Expected behavior:**
```js
function foo() {
    var key = 'bar';
    var _a;
    return _a = {},
        _a[key || 'baz'] = true,
        _a;
}
```

**Actual behavior:**
```js
function foo() {
    var key = 'bar';
    return _a = {},
        _a[key || 'baz'] = true,
        _a;
    var _a;
}
```

**Comment by tsvetomir** [comment]
Note that the generated code is actually correct as `_a` is hoisted to the function scope.
The problem is that minifiers such as UglifyJS will complain about it as it follows a `return` statement.

```
Dropping unreachable code
Declarations in unreachable code!
```

**Comment by fatcerberus** [comment]
This is a known issue - see #4138.

**Comment by tsvetomir** [comment]
Thanks! The original issue is closed, should we keep this one or reopen it instead?

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
