### ISSUE TITLE
Use declared type parameters in signature help

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#15412]
From: https://github.com/Microsoft/vscode/issues/25363

**TypeScript Version:**  2.3.1

**Code**

```ts
type Z = { abc: number, xyz: string }

function foo<T>(z: keyof T) { }

foo<Z>('')
```

Trigger suggestions inside of the quotes in the function call.

**Expected behavior:**
Returns suggestions for `abc` and `xyz`

**Actual behavior:**
No suggestions returned in this case.

If a non-generic type is used:

```ts
type Z = { abc: number, xyz: string }

function foo(z: keyof Z) { }

foo('')
```

Then suggestions are returned

**Comment by andy-ms** [comment]
The real problem is that we don't use a declared type parameter when getting signature help.
```ts
declare function f<T>(x: T): void;
f<number>(
```
Signature help here still shows `f<T>(x: T): void`.

**Comment by dkirchhof** [comment]
I don't know, if it fits exactly to this problem, but i'm struggling with the autocompletion while using keyof.  
Small example:  
```ts
function keyofTest<Type>(context: Type, key: keyof Type)
{
	return context;
}

class Test
{
	a: string;
	b: number;
}

keyofTest<Test>(new Test(), "a") // this works as expected
keyofTest(new Test(), "") // this not really
```
The second function call shows me all possible types, while the cursor is before the comma, but not between the quotes anymore. A wrong key would also be marked. Two images attached to see the behaviour:

![intellisense1](https://user-images.githubusercontent.com/2778643/34145899-4d624ae0-e498-11e7-8b81-7dd0c8d5f752.png)
![intellisense2](https://user-images.githubusercontent.com/2778643/34145900-4d7cc9a6-e498-11e7-87de-c356f341d2da.png)

**Comment by andy-ms** [comment]
@dkirchhof In the second case type inference has failed, since we can't infer any type `Type` such that `new Test() : Type` and `"" : keyof Type`. All parameters are used for type inference, not just the first. In this case you really only need the first, but it would be hard to change type inference to know about that, so instead it infers from all parameters and fails.

**Comment by dkirchhof** [comment]
Sorry, but i don't get it. At first, it shows me all possible keys (`key: "a" | "b"`), then it can't infer the type anymore and if a type in "c" or something else, which isn't a key of `Test`, it will be marked as a wrong argument until i change it to "a" or "b". So it just don't work for the "suggestions popup"?!

**Comment by andy-ms** [comment]
It works in the compiler layer but that information doesn't get to services which provides the completions. I've made an issue #20843.
