### ISSUE TITLE
Destructured parameter properties do not introduce properties into their respective class

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#1541]
```TypeScript
class C {
    constructor(public [x, y, z]: string[]) {
    }
}

var c = new C([]);
c.x === c.y;
```

which gives us

```
error TS2339: Property 'x' does not exist on type 'C'
error TS2339: Property 'y' does not exist on type 'C'
```

The question is *should* we be adding properties when destructuring in the face of a visibility modifier?

**Comment by DanielRosenwasser** [comment]
@jonathandturner and I spoke offline and decided that the binding parameters *should* introduce properties of the appropriate visibility.

**Comment by DanielRosenwasser** [comment]
@ahejlsberg and I spoke offline and decided that binding parameters *should not* introduce properties of the appropriate visibility.

**Comment by mhegazy** [comment]
Reopening to update the spec.

**Comment by DanielRosenwasser** [comment]
This is Fixed as far as the work goes; the spec work needs to be done.

**Comment by danquirk** [comment]
Let's create new bugs for spec work, that way you can close this with the fixed label. Otherwise we should remove the fixed label from this one, which then makes confusing the fact that it does represent dev work that fixed an issue.

**Comment by DanielRosenwasser** [comment]
Agreed; I've opened up #1691 instead.
