### ISSUE TITLE
Improve type safety of `name` global variable

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#15424]
`name` global variable is still assignable to `string` type. So `name` is still unsafe. `name: string | undefined` works better than current definition `name: never`.

**TypeScript Version:**  master

**Code**

```ts
const n1: string = <never>name; // pass
const n2: string = <string | never>name; // pass
const n3: string = <string | undefined>name; // error, expected
```

**Expected behavior:**

```ts
declare const name: string | undefined;
```

**Actual behavior:**

```ts
declare const name: never;
```

**Comment by falsandtru** [comment]
related: #9850 @DanielRosenwasser

**Comment by falsandtru** [comment]
@mhegazy @DanielRosenwasser @rbuckton

**Comment by falsandtru** [comment]
@mhegazy @DanielRosenwasser Can you please also review this?

**Comment by mhegazy** [comment]
@DanielRosenwasser any thoughts

**Comment by mhegazy** [comment]
The resons we made it `never` was that ppl were stepping on it by mistake..

````ts
class C {
    name: string;
    method() {
        doSomething(name); // not this.name
    }
}

```
by making it `never` at least you will get an error and you will go back and check the source of the declaration. 

`string | undefined` will put us back where we started for most users.

**Comment by mhegazy** [comment]
as noted in https://github.com/Microsoft/TypeScript/issues/15424#issuecomment-301207034, `never` was added for a specific reason. It is much more common for users to use the global `name` by mistake vs intentionally. this change was meant to alert users in these cases; unfortunately it breaks other cases, but we believe this gets the 90% case right. for other cases, `window.name`.
