### ISSUE TITLE
TSX spread regression in 2.3

### ISSUE THREAD

**Issue by Igorbek** [Microsoft/TypeScript#15420]
**TypeScript Version:**  2.3.1

**Code**

```ts
import * as React from 'react';

function test<T extends object>(Component: React.StatelessComponent<T>, props: T) {
    return <Component {...props} />
                      ~~~~~~~~~~ error TS2698: Spread types may only be created from object types.
}
```
(same with `React.ComponentClass`)

**Expected behavior:**

Compile without an error.

**Actual behavior:**

Error: error TS2698: Spread types may only be created from object types.

That was already reported in closed issue #14112

**Comment by mhegazy** [comment]
This is tracked by https://github.com/Microsoft/TypeScript/issues/10727 and fixed by https://github.com/Microsoft/TypeScript/pull/13288

**Comment by Igorbek** [comment]
Ah, ok, that is unfortunate that you didn't make it into 2.3. Closing as dup
