### ISSUE TITLE
webpack ts-loader arrow function change this 

### ISSUE THREAD

**Issue by icssjs** [Microsoft/TypeScript#15429]
**TypeScript Version:**  2.2.1 / nightly (2.2.0-dev.201xxxxx)
tsconifg
`
{
    "compilerOptions": {
        "outDir": "./dist/",
        "sourceMap": true,
        "noImplicitAny": true,
        "module": "commonjs",
        "target": "es5",
        "jsx": "react"
    },
    "include": [
        "./typings/index.d.ts",
        "./src/**/*"
    ]
}
`
**Code**
`$('.btn').on('click',()=>{
   console.log($(this))
})`
```ts
// A *self-contained* demonstration of the problem follows...

```

**Expected behavior:**
`$('.btn').on('click',function(){
   console.log($(this))
})`

**Actual behavior:**
`$('.btn').on('click',function(){
   console.log($(_this))
})`

**Comment by HerringtonDarkholme** [comment]
This works as intended. Arrow function captures the enclosing `this`. 

Please refer to 
https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Functions.md#this-and-arrow-functions

http://exploringjs.com/es6/ch_arrow-functions.html is a good resource too.
