### ISSUE TITLE
DocComment does not update after editing

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/TypeScript#15427]
![quickinfo_update](https://cloud.githubusercontent.com/assets/3226984/25511897/e2eb8dac-2b7e-11e7-8fb0-3b0b18d8aeb3.gif)

**TypeScript Version:**  repo'd with stock tsserver in vscode 1.11.2
vscode commit 6eaebe3b
and
TypeScript: master, commit 3d23b9c15a2c2f

**Code**

```ts
// file.ts
function foo() {
    /**
     * Existing doc comment
     *
     * ^
     */
    let x: any[];
}
```

1) At `^`, write `new doc comment`.
2) hover for quickinfo on `x`, observe that quickinfo contains the new part of the doc comment.
3) select `new doc comment` and delete with `Backspace`.
4)  hover for quickinfo on `x`, 

**Expected behavior:**
Quickinfo doesn't contain the new part of the doc comment.
**Actual behavior:**
Quickinfo contains the new part of the doc comment.

**Comment by mhegazy** [comment]
should be fixed in latest.
