### ISSUE TITLE
Parameters with binding patterns should not be allowed to be optional 

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#1542]
Consider the following:

```TypeScript
function foo([x,y,z]? : string[]) {
    return; // we don't even need to use `x`, `y`, or `z`.
}
```

But this will ***always*** crash when the argument is omitted because we'll effectively be running the following:

```JavaScript
x = undefined[0],
y = undefined[1],
z = undefined[2];
````

 It seems fine to have default initializers, but optionality should be disallowed.

**Comment by jonathandturner** [comment]
Tagging @mhegazy so that we can talk about this.

**Comment by jonathandturner** [comment]
We should be conservative initially and disallow.  We can enable later.
