### ISSUE TITLE
Lenient members using keyof 

### ISSUE THREAD

**Issue by pocesar** [Microsoft/TypeScript#15431]
**TypeScript Version:**  2.3.0-dev.20170428

**Code**

As instructed by @mjbvz in Microsoft/vscode#25363 opening a separated issue here
the repro lies in https://github.com/pocesar/ts-issue-25363

**Expected behavior:**

Everything marked as `should error` in comments, should error

**Actual behavior:**

TS is being lenient when using keyof on nested objects

**Comment by RyanCavanaugh** [comment]
Can you reduce this to something that you could just post on the Playground?

**Comment by pocesar** [comment]
here:

```ts
type KeyOfValue<T> = T | keyof T;
 
interface Q<T> {
    $eq?: KeyOfValue<T>; $exists?: boolean; $all?: Array<T>;
}

type KeyOf<T extends any[]> = {
    [i in keyof T[0]]?: Q<T[0]> | Partial<T[0][i]>;
}

type AQ<T extends any[]> = Q<T[0]> | KeyOf<T>;
const myF = <T extends any[]>(q: AQ<T>, target: T) => {}

myF({$eq:1,$exists:'false'}, [1, 2, 3])
myF({state:'true',s:{$exists:true}}, [{state:'one',s:{one:1}},{state:'two',s:{two:2}},{state:'three',s:{one:3}}])
```

can't share directly because it's saying "Text buffer too large to share"

side totally unrelated note: typing 'ts playground' in Google with safe search off is a no-go

**Comment by mhegazy** [comment]
so what is the error you are expecting here? is it for `$exists` being a `string`?

**Comment by mhegazy** [comment]
also on a side note the `T[0]` makes the whole thing more complicated than it should be.. you are better off capturing `T` in myF as `const myF = <T>(q: AQ<T>, target: T[]) => { }`.

**Comment by mhegazy** [comment]
I think `KeyOf` should not be optional:

```ts
type KeyOf<T extends any[]> = {
    [i in keyof T[0]]: Q<T[0]> | Partial<T[0][i]>;
}
```

instead of:

```ts
type KeyOf<T extends any[]> = {
    [i in keyof T[0]]?: Q<T[0]> | Partial<T[0][i]>;
}
```

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
