### ISSUE TITLE
Return function types, weird behaviour.

### ISSUE THREAD

**Issue by llaine** [Microsoft/TypeScript#15434]
**TypeScript Version:**  2.2

[Code snippet example](https://www.typescriptlang.org/play/#src=type%20ReturnType%20%3D%20%7B%20a%3A%20string%20%7D%0D%0Atype%20Fn%20%3D%20()%20%3D%3E%20ReturnType%0D%0A%0D%0Aconst%20fn%3A%20Fn%20%3D%20()%20%3D%3E%20(%7B%0D%0A%20%20%20%20a%3A%20''%2C%0D%0A%20%20%20%20b%3A%20''%20%2F%2F%20This%20should%20breaks%0D%0A%7D)%0D%0A%0D%0A%20)

**Code**

```ts
// Here is my problem
type ReturnType = { a: string }
type Fn = () => ReturnType

// OK - This breaks and that what we wants.
const fn: Fn = () => ({
    a: 0,
})

// Not ok - It doesn't and I don't know why.
const fn: Fn = () => ({
    a: '',
    b: '' // This should breaks my ReturnType interface doesn't have 
})
```

**Comment by ikokostya** [comment]
TypeScript uses `structural typing` (see https://www.typescriptlang.org/docs/handbook/type-compatibility.html for more information). That's why

```ts
{a: '', b: ''}
```
in your example is assignable to `ReturnType` type.

**Comment by llaine** [comment]
What does it mean? Sorry, I'm a TS beginner and I feel I'm missing something here...

**Comment by ahanriat** [comment]
@ikokostya I'm having the same issue, do you know if there is a way to force TS to not use this structural typing?

**Comment by ikokostya** [comment]
@ahanriat As I known there is now way. There is only suggestion https://github.com/Microsoft/TypeScript/issues/202

**Comment by llaine** [comment]
@ikokostya Okay after reading through I managed to make something more permissive, but I'm still stuck.
Am I blocked because of TS design's ?

```ts
type ReturnType = { a: string }
type Nominal<T> = {
    [K in keyof T]: T[K]
};

const fn: Fn<Nominal<ReturnType>> = () => ({
    a: false,
    b: '',
})
```

**Comment by llaine** [comment]
Okay actually I mixed it up with down casting.
This solved it
```ts
class ReturnType { a: string }

type Nominal<T> = {
    [K in keyof T]: T[K]
};
type Fn<T> = () => Nominal<T>

const fn: Fn<ReturnType> = (): ReturnType => ({
    a: '',
    b: '',
})
```
