### ISSUE TITLE
Destructing in For-in statement

### ISSUE THREAD

**Issue by yuit** [Microsoft/TypeScript#1543]
So I try the following example from the wiki-ecmascript website

```typescript
for ( let [name, value] in obj ) {
    print("Name: " + name + ", Value: " + value);
}
```

When compile using typescript on master, the compiler report an "error - A destructing declaration must have an initializer"; However, shouldn't this be allowed since initializer is optional?

**Comment by Ceane** [comment]
I don't believe this should be allowed, the `for-of` loop in ES6 is what I believe you are referring to, which isn't currently supported by Typescript. The `for-in` loop does not assign values as such.
