### ISSUE TITLE
Related Generic Type Inferrence

### ISSUE THREAD

**Issue by kitsonk** [Microsoft/TypeScript#15439]
**TypeScript Version:**  2.3.1 (or 2.2.1)

**Code**

```ts
interface Properties {
	key?: string;
}

class Base<P extends Properties> {
	properties: P;
}

interface Constructor<T> {
	new (...args: any[]): T;
	prototype: T;
};

interface ANode<P extends Properties> {
	ctor: Constructor<Base<P>>;
	properties: P;
}

function createNode<P extends Properties>(ctor: Constructor<Base<P>>, properties: P): ANode<P> {
	return {
		ctor,
		properties
	};
}

interface ExtendedProperties extends Properties {
	requiredProp1: string;
	requiredProp2: string;
}

class Extended extends Base<ExtendedProperties> {
};

const node1 = createNode(Extended, { requiredProp1: '' }); // should error, but doesn't
const node2 = createNode(Extended, { requiredProp1: '', something: '' }); // should error, and does

const node3 = createNode<ExtendedProperties>(Extended, { requiredProp1: '' }); // should error, and does
const node4 = createNode<ExtendedProperties>(Base, { requiredProp1: '', requiredProp2: '' }); // should error? but doesn't
```

**Expected behavior:**

That when generics are inferred from one argument, that the other argument is constrained to meet that inferred generic, as when the generics are explicit.

**Actual behavior:**

[Playground Version](https://www.typescriptlang.org/play/#src=interface%20Properties%20%7B%0A%09key%3F%3A%20string%3B%0A%7D%0A%0Aclass%20Base%3CP%20extends%20Properties%3E%20%7B%0A%09properties%3A%20P%3B%0A%7D%0A%0Ainterface%20Constructor%3CT%3E%20%7B%0A%09new%20(...args%3A%20any%5B%5D)%3A%20T%3B%0A%09prototype%3A%20T%3B%0A%7D%3B%0A%0Ainterface%20ANode%3CP%20extends%20Properties%3E%20%7B%0A%09ctor%3A%20Constructor%3CBase%3CP%3E%3E%3B%0A%09properties%3A%20P%3B%0A%7D%0A%0Afunction%20createNode%3CP%20extends%20Properties%3E(ctor%3A%20Constructor%3CBase%3CP%3E%3E%2C%20properties%3A%20P)%3A%20ANode%3CP%3E%20%7B%0A%09return%20%7B%0A%09%09ctor%2C%0A%09%09properties%0A%09%7D%3B%0A%7D%0A%0Ainterface%20ExtendedProperties%20extends%20Properties%20%7B%0A%09requiredProp1%3A%20string%3B%0A%09requiredProp2%3A%20string%3B%0A%7D%0A%0Aclass%20Extended%20extends%20Base%3CExtendedProperties%3E%20%7B%0A%7D%3B%0A%0Aconst%20node1%20%3D%20createNode(Extended%2C%20%7B%20requiredProp1%3A%20''%20%7D)%3B%20%2F%2F%20should%20error%2C%20but%20doesn't%0Aconst%20node2%20%3D%20createNode(Extended%2C%20%7B%20requiredProp1%3A%20''%2C%20something%3A%20''%20%7D)%3B%20%2F%2F%20should%20error%2C%20and%20does%0A%0Aconst%20node3%20%3D%20createNode%3CExtendedProperties%3E(Extended%2C%20%7B%20requiredProp1%3A%20''%20%7D)%3B%20%2F%2F%20should%20error%2C%20and%20does%0Aconst%20node4%20%3D%20createNode%3CExtendedProperties%3E(Base%2C%20%7B%20requiredProp1%3A%20''%2C%20requiredProp2%3A%20''%20%7D)%3B%20%2F%2F%20should%20error%3F%20but%20doesn't%0A)

Essentially, when the generic type is inferred, the object literal is allowed to be narrower than the related generic, but not wider.  In the example, the argument `properties: P` can be narrower (`{ requiredProp1: '' }`) of `ExtendedProperties` but cannot be wider (`{ requiredProp1: '', something: '' }`).  When specified, `properties` has to match the interface.

**Comment by kitsonk** [comment]
After we thought we have been over every permutation, we found a way to [express it](https://www.typescriptlang.org/play/#src=interface%20Properties%20%7B%0A%09key%3F%3A%20string%3B%0A%7D%0A%0Aclass%20Base%3CP%20extends%20Properties%3E%20%7B%0A%09properties%3A%20P%3B%0A%7D%0A%0Ainterface%20Constructor%3CT%3E%20%7B%0A%09new%20(...args%3A%20any%5B%5D)%3A%20T%3B%0A%09prototype%3A%20T%3B%0A%7D%3B%0A%0Ainterface%20ANode%3CP%20extends%20Properties%3E%20%7B%0A%09ctor%3A%20Constructor%3CBase%3CP%3E%3E%3B%0A%09properties%3A%20P%3B%0A%7D%0A%0Afunction%20createNode%3CP%20extends%20Properties%3E(ctor%3A%20Constructor%3CBase%3CP%3E%3E%2C%20properties%3A%20Properties%20%26%20P)%3A%20ANode%3CP%3E%20%7B%0A%09return%20%7B%0A%09%09ctor%2C%0A%09%09properties%0A%09%7D%3B%0A%7D%0A%0Ainterface%20ExtendedProperties%20extends%20Properties%20%7B%0A%09requiredProp1%3A%20string%3B%0A%09requiredProp2%3A%20string%3B%0A%7D%0A%0Aclass%20Extended%20extends%20Base%3CExtendedProperties%3E%20%7B%0A%7D%3B%0A%0Aconst%20node1%20%3D%20createNode(Extended%2C%20%7B%20requiredProp1%3A%20''%20%7D)%3B%20%2F%2F%20should%20error%2C%20and%20does%0Aconst%20node2%20%3D%20createNode(Extended%2C%20%7B%20requiredProp1%3A%20''%2C%20something%3A%20''%20%7D)%3B%20%2F%2F%20should%20error%2C%20and%20does%0A%0Aconst%20node3%20%3D%20createNode%3CExtendedProperties%3E(Extended%2C%20%7B%20requiredProp1%3A%20''%20%7D)%3B%20%2F%2F%20should%20error%2C%20and%20does%0Aconst%20node4%20%3D%20createNode%3CExtendedProperties%3E(Base%2C%20%7B%20requiredProp1%3A%20''%2C%20requiredProp2%3A%20''%20%7D)%3B%20%2F%2F%20should%20error%3F%20but%20doesn't%0A), by changing the `properties` from `P` to `Properties & P`:

```
function createNode<P extends Properties>(ctor: Constructor<Base<P>>, properties: Properties & P): ANode<P> {
	return {
		ctor,
		properties
	};
}
```

It would still be nice to understand why the generic inference works that way and keeps the argument from not being allowed to be narrow anymore.

**Comment by mhegazy** [comment]
I would use `Class["properties"]` to get the type here instead of inferring it. so `createNode` would be defined to capture the type of the class, and not the class properties:

```ts
function createNode<C extends Base<any>>(ctor: Constructor<C>, properties: C["properties"]): ANode<C["properties"]> { .. }
```

I think this will flag all your use-cases  as errors.

**Comment by kitsonk** [comment]
Thank you!  That worked a charm, and is logical.  Accessing properties of generics was new to me.  I am not sure when that came around, but pretty awesome.
