### ISSUE TITLE
Breaking changes in tsserver API between 2.3.0rc and 2.3.1.

### ISSUE THREAD

**Issue by anstarovoyt** [Microsoft/TypeScript#15433]
Hi. We (WebStorm & Intellij IDEA) use public API of tsserver (in fact we use 'tsserverlibrary.js') and every time when you introduce changes in the public API we have to change our code accordingly. 
For example this commit https://github.com/Microsoft/TypeScript/commit/3cc379c3c0c8f3e5ee8b1be5bad8bbc31cfcb610
changed the constructor of the exported class "Session" and we really depend on it.

Could you please not introduce breaking changes in stable branches?
rel. https://youtrack.jetbrains.com/issue/WEB-26641

cc @RyanCavanaugh

**Comment by mhegazy** [comment]
This slipped through unnoticed, and is not intentional. we will try and get a fix for you shortelly. sorry for the hassle.

**Comment by RyanCavanaugh** [comment]
@anstarovoyt I'll have a fix up shortly that you can try locally

**Comment by mhegazy** [comment]
[TypeScript 2.3.2](https://github.com/Microsoft/TypeScript/releases/tag/v2.3.2) should be available now with the fix. sorry for the trouble.

**Comment by anstarovoyt** [comment]
@mhegazy awesome! Thank you

**Comment by alexeagle** [comment]
Are you tracking a fix for the root cause here? Seems like there is some missing testing that would have caught the API instability.

**Comment by Rituza** [comment]
## ### # 
## ### #

**Comment by mhegazy** [comment]
yes. we now have tests that baseline the API.
