### ISSUE TITLE
Emit issue with member access dot operator and parentheses usually in conjunction with type assertion

### ISSUE THREAD

**Issue by gdelmas** [Microsoft/TypeScript#15444]
**Code**

    a.foo()
    (b).foo()

**Expected emit:**

    a.foo();
    (b).foo();

**Actual emit:**

    a.foo()(b).foo();

This becomes an issue when using type assertions inline:

**Code**

    a.foo()
    (b as Bar).foo()

**Expected emit:**

    a.foo();
    b.foo();

**Actual emit:**

    a.foo()(b).foo();

---

Angle brackets type assertion have a similar issue:

**Code**

    a.foo()
    <Bar>b.foo()

**Actual emit:**

    a.foo()
        < Bar > b.foo();

**Comment by mhegazy** [comment]
Unfortunately these are the [JavaScript Automatic SemiColon Insertion rules](https://www.ecma-international.org/ecma-262/6.0/#sec-automatic-semicolon-insertion).

TypeScript is a super-set of JavaScript, and the samples above are valid JS code samples, and they have valid semantics. the emitted code has to match these semantics.

**Comment by gdelmas** [comment]
thanks for your reply @mhegazy. i thought that it is a tricky case, as sometimes a multiline expression might be intended.

i might create a tslint warning to detect it in conjunction with assertions. or might this be a case where `tsc` can warn itself?

**Comment by RyanCavanaugh** [comment]
I believe there's already a TSLint rule for missing semicolons

**Comment by gdelmas** [comment]
do you mean this core rule:

    "semicolon": [true, "never"]

> "never" disallows semicolons at the end of every statement except for when they are necessary.

the rule does not warn if a semicolon in conjunction with a type assertion might be required. it also fails in some other cases, and warns. for example:

    super(); <-- rule thinks this is unnecessary
    (a as Bar).foo()

**Comment by RyanCavanaugh** [comment]
Sorry, I totally misread that. Disregard.

@mhegazy perhaps we should disallow `boolean` as an operand to `>` / `<`, even if the other operand is `any` ?

**Comment by ajafff** [comment]
@gdelmas you can use the `no-unexpected-multiline` provided by `tslint-eslint-rules`

**Comment by mhegazy** [comment]
> @mhegazy perhaps we should disallow boolean as an operand to > / <, even if the other operand is any

👍

**Comment by mhegazy** [comment]
Filed https://github.com/Microsoft/TypeScript/issues/15506 to track it.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
