### ISSUE TITLE
for...of loop not working with downlevelIteration when Symbol is not defined

### ISSUE THREAD

**Issue by jacobgardner** [Microsoft/TypeScript#15446]
**TypeScript Version:**  2.3.1

**Code**

```ts
function makeNumbers(): number[] {
    const arr = [];
    for (const it of makeNumbersIterator()) {
        arr.push(it);
    }

    return arr;
}

function *makeNumbersIterator() {
    yield 5;
    yield 10;
    yield 15;
    yield 20;
}

if (typeof print === 'function') {
    print(makeNumbers());
} else {
    console.log(makeNumbers());
}
```

tsconfig.json
```json
{
  "compilerOptions": {
    "target": "es5",
    "downlevelIteration": true
  }
}

```

**Expected behavior:**
Using a javascript interpreter without `Symbol` defined should output [5, 10, 15, 20].    

I used Rhino to replicate this, but an early node version should work as well or IE. 

**Actual behavior:**
An infinite loop occurs because __values treats the iterator as if it's an array instead of an iterator. 

```js
var __values = (this && this.__values) || function (o) {
    var m = typeof Symbol === "function" && o[Symbol.iterator], i = 0;
    if (m) return m.call(o);
    // even though o is not an array, it is treated as if it were 
    // because the above conditional fails.  Now `next` it is called infinitely 
    // since o is set to undefined every time `next` is called. 
    // if I return o here instead, it works correctly.  
    return {
        next: function () {
            if (o && i >= o.length) o = void 0;
            return { value: o && o[i++], done: !o };
        }
    };
};
```

**Comment by mhegazy** [comment]
`for..of` should work on `Array` or an `Iterable` object. an iterable object needs to implement the iterator protocol, and this relies on `Symbol`. You will need to add a polyfill (e.g. [core.js](https://github.com/zloirock/core-js/blob/master/es6/symbol.js))for `Symbol`.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Comment by BartolomeoItaliano** [comment]
Hi, I solved it different way by adding property "lib" to to tsconfig.json 
`"lib": ["es2015", "dom", "ES5", "ScriptHost"],`
it looks that default configuration for "es5" misses "es2015" library in defulat configuration.
