### ISSUE TITLE
Should be possible to update typings .lib file used by visual studio extension

### ISSUE THREAD

**Issue by SaphuA** [Microsoft/TypeScript#15448]
We develop our project using visual studio, but use webpack instead of the vs extension to compile typescript. We do use the extension's great support for intellisense. However we recently ran into an issue where the typings used by the extension and the one in npm were different. It would be great if we could either update the typings or point to the version used by webpack.

**Comment by mhegazy** [comment]
In VS 2015 you can install the matching version through: https://www.microsoft.com/en-us/download/details.aspx?id=48593

In VS 2017 ([currently available in the Preview channel](https://www.visualstudio.com/en-us/news/releasenotes/vs2017-preview-relnotes#typescript)) , this should be available through tools/options menu, see https://github.com/Microsoft/TypeScript/issues/14529 for relevant discussions.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
