### ISSUE TITLE
The last example of chapter Generics in docs errors at runtime, while type checking is good

### ISSUE THREAD

**Issue by twhy** [Microsoft/TypeScript#15441]
**TypeScript Version:**  2.3.1

The code is copied from the official documentation https://www.typescriptlang.org/docs/handbook/generics.html
The last example at page bottom.

Typechecking is good, but when you actually run the code, it errors.

**Code**
```ts
class BeeKeeper {
  hasMask: boolean;
}

class ZooKeeper {
  nametag: string;
}

class Animal {
  numLegs: number;
}

class Bee extends Animal {
  keeper: BeeKeeper;
}

class Lion extends Animal {
  keeper: ZooKeeper;
}

function findKeeper<A extends Animal, K>(a: {
  new (): A;
  prototype: { keeper: K }
}): K {

  return a.prototype.keeper;
}

findKeeper(Lion).nametag;  // typechecks!
```
```ts
// doing this doesn't guarantee `Lion.prototype.keeper` exists.
class Lion extends Animal {
  keeper: ZooKeeper;
}
```

**Expected behavior:**
This example need to be modified to be run without errors

**Actual behavior:**
<img width="687" alt="error" src="https://cloud.githubusercontent.com/assets/7459812/25534711/420cf0ee-2c67-11e7-8ad7-2f74c88ae251.png">

**Comment by mhegazy** [comment]
That was supposed to be fixed by https://github.com/Microsoft/TypeScript-Handbook/pull/538, but looks like @lifuhuang  gave up on it. A PR to https://github.com/Microsoft/TypeScript-Handbook/ would be appreciated.

**Comment by mhegazy** [comment]
here is a possible update to this example: 

```ts
class BeeKeeper {
    hasMask: boolean;
}

class ZooKeeper {
    nametag: string;
}

class Animal {
    numLegs: number;
}

class Bee extends Animal {
    keeper: BeeKeeper;
}

class Lion extends Animal {
    keeper: ZooKeeper;
}

function createInstance<A extends Animal>(c: new () => A): A {
    return new c();
}

createInstance(Lion).keeper.nametag;  // typechecks!
createInstance(Bee).keeper.hasMask;   // typechecks!
```

**Comment by twhy** [comment]
@mhegazy Thanks for your quick response.

But even the updated version run into errors, because the code below doesn't guarantee there is a valid keeper on a Lion instance, `lion.keeper` is `undefined`.
```ts
class Lion extends Animal {
    keeper: ZooKeeper;
}
```
You need to initialize the keeper in the constructor of Lion at least.
```ts
class Lion extends Animal {
    keeper: ZooKeeper;
    constructor() {
      super();
      this.keeper = new ZooKeeper();
    }
}
```
* Is this a problem?   
TypeScript introduces type system trying to eliminate runtime errors. But in the example code and the updated code (without constructor), all type checkings pass but it still fails at runtime.

* Is it possible to do more dynamic type checking?  
That means when `lion.keeper` is `undefined`, the compiler will point out `lion.keeper.nametag` will cause errors.

Thanks.

**Comment by mhegazy** [comment]
sure. a PR is welcomed.
