### ISSUE TITLE
Error when using `{}` intersection types with object literal

### ISSUE THREAD

**Issue by voithos** [Microsoft/TypeScript#15447]
**TypeScript Version:**  2.3.1
**Code**

```ts
const foo: object & {} = {bar: 'bar'};
```

**Expected behavior:**
No error.

**Actual behavior:**
I get the following error:

    Type '{ bar: string; }' is not assignable to type 'object & {}'.
      Object literal may only specify known properties, and 'bar' does not exist in type 'object & {}'.

This error is not present in 2.2 or 2.3-rc. Interestingly enough, the following all work fine:

```ts
const foo1: object = {bar: 'bar'};
const foo2: {} = {bar: 'bar'};

class Bar {}
const bar = new Bar();
const foo3: Bar & {} = bar;
```

**Comment by nowy** [comment]
I would like to tackle this if possible. Will create a PR. Any idea where to start?

**Comment by DanielRosenwasser** [comment]
Sorry we didnt' catch your comment @nowy. It's somewhat difficult to catch every comment with our volume of activity, and I just saw this because @HerringtonDarkholme sent out a PR. Definitely feel free to look into other issues with the Accepting PRs label though.
