### ISSUE TITLE
Object spread unsound w.r.t. width subtyping of object types

### ISSUE THREAD

**Issue by samwgoldman** [Microsoft/TypeScript#15454]
**TypeScript Version:**  Whatever is running on TypeScript Playground

**Code**

```ts
var o1: { p: string, q: number } = { p: "", q: 0 };
var o2: { p: string } = o1;
var o3: { p: string, q: string } = { q: "", ...o2 };
```

**Expected behavior:**

Some type error somewhere. `o3` has type `{p: string, q: number}` at runtime, but we think `q` has type `string`.

**Actual behavior:**

No error. Potential runtime type error.

**Comment by RyanCavanaugh** [comment]
"somewhere" is doing a lot of work there 😉 . Where specifically should the error be (and by what process)?

**Comment by samwgoldman** [comment]
Hah, fair! I thought the example was small enough to make it clear :)

One option would be to forbid width subtyping between object types, so the error would be on line 2. This is pretty limiting, so not a great option.

Another option would be to error on line 3. Because the `p` property of `o2` could be *anything* as far as TS knows, you could infer the type of the spread to be `{ p: string, q: {} }`, which would be incompatible with `{ p: string, q: string }`.

**Comment by RyanCavanaugh** [comment]
Without closed types, that's effectively the same as "don't allow spreading, ever", which doesn't really seem helpful.

**Comment by samwgoldman** [comment]
Just confirming this is by design.

**Comment by RyanCavanaugh** [comment]
Yep

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
