### ISSUE TITLE
Visual Studio 2015 plugin distribution is broken

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#15457]
You navigate us to https://www.microsoft.com/en-us/download/details.aspx?id=48593 but this link still distributes the old version 2.2.2, not 2.3. Additionally, When moving to that link from https://github.com/Microsoft/TypeScript/releases, https://www.microsoft.com/en-us/download/details.aspx?id=48593 displays the following Details correctly

```
Details
Version:
2.3.1
File Name:
2.3.1-TS-release-dev14update3-20170425.3\TypeScript_Dev14Full.exe
Date Published:
4/28/2017
File Size:
10.0 MB
```

But sometimes this page displays different Details incorrectly after reloading the page!! I can download only this old version.

```
Details
Version:
2.2.2
File Name:
TS-2.2-dev14update3-20170321.1\TypeScript_Dev14Full.exe
Date Published:
4/4/2017
File Size:
8.8 MB
```

cc @mhegazy @DanielRosenwasser @yuit

**Comment by mhegazy** [comment]
I updated the page today, we have had issues in the past with the update propagating through the diffrent mirrors. I would give it a few hours and try again.

**Comment by falsandtru** [comment]
Thanks, I got the latest one!
