### ISSUE TITLE
Type 'RegExpMatchArray' is not assignable to type 'boolean'

### ISSUE THREAD

**Issue by philipmw** [Microsoft/TypeScript#15450]
**TypeScript Version:**  2.2.1

**Code**

```ts
console.log( true && [/hi/].find(regex => "hello".match(regex)) );
```

**Expected behavior:**
false

**Actual behavior:**
> error TS2345: Argument of type '(regex: RegExp) => RegExpMatchArray' is not assignable to parameter of type '(value: RegExp, index: number, obj: RegExp[]) => boolean'.
>  Type 'RegExpMatchArray' is not assignable to type 'boolean'.

The [documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find?v=example) says:
> The find() method returns the value of the first element in the array that satisfies the provided testing function. Otherwise undefined is returned.

So I am expecting to take advantage of comparing for truthiness.

Whereas, this works as expected:

```ts
console.log( true && [1, 2, 3, 4].find(v => v === 2) );
```

**Comment by j-oliveras** [comment]
`"hello".match(regex)` returns an array. [Documentation from MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/match).
Use:
`console.log( true && [/hi/].find(regex => "hello".match(regex) !== null) );`

**Comment by philipmw** [comment]
Thanks, @j-oliveras. I don't think the problem is with `String.match`, because this works fine:

```tsc
console.log( true && "hello".match(/hi/) );
```

I think it's something to do with `Array.find`.

**Comment by RyanCavanaugh** [comment]
In general when a function expects a truthiness value, we expect an explicit coercion of non-booleans. Otherwise it becomes to easy write something like `[NaN, 3, 3].find(n => isFinite)` - literally any JS value is a valid truthiness value.

We can make an exception if it's truly burdensome in some cases, but that's the general idea.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
