### ISSUE TITLE
typescript visual studio integration

### ISSUE THREAD

**Issue by icepower03** [Microsoft/TypeScript#15464]
hello,
as far as typescript becomes so huge as C#, it becomes very hard sometimes to differenciate C# and typescript at first sight.

i'm not sure you can but it would be very useful to be able to set a diffrent background color for the editor in typescript.
it's a year that i search about this in visual studio themes, but they can't be associated with file extension.

thank you to think about that.

regards

**Comment by mhegazy** [comment]
I do not think this request is specific to TS or C#, it is a VS-specific request. I would say this should be reported on https://connect.microsoft.com/VisualStudio/Feedback

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
