### ISSUE TITLE
List of plugins for "Language server plugin support"

### ISSUE THREAD

**Issue by angelozerr** [microsoft/TypeScript#15460]
I have discovered in https://blogs.msdn.microsoft.com/typescript/2017/04/27/announcing-typescript-2-3/ the existing of new language server plugin support.

It should be cool if the wiki https://github.com/Microsoft/TypeScript/wiki could host the list of those plugins:

 * [Angular Language Service](https://marketplace.visualstudio.com/items?itemName=Angular.ng-template)
 * [TSLint Language Service](https://github.com/angelozerr/tslint-language-service)
 * [TypeScript Language Service Plugin for GraphQL developers](https://github.com/Quramy/ts-graphql-plugin)
 * [Vetur plugin](https://github.com/octref/vetur/)
 * [PLugin sample](https://github.com/RyanCavanaugh/sample-ts-plugin)

Thanks!

**Comment by mhegazy** [comment]
We have docs about plugins in https://github.com/Microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin, a PR to add the list would be welcomed. 


Vetur plugin is not an LS plugin, it uses the LS directly. so i would not include it under this section.

**Comment by josephliccini** [comment]
I was also having a hard time understanding `plugins` from the docs available.  This 'Writing a Language Service Plugin' helped a lot.  Thanks for linking that.

I didn't see it in this documentation: https://www.typescriptlang.org/docs/handbook/compiler-options.html

**Comment by RyanCavanaugh** [comment]
@mjbvz want to link your styled plugin here?

**Comment by mjbvz** [comment]
TS plugin for styled-components: https://github.com/Microsoft/typescript-styled-plugin

I've added a link to it on the wiki page
