### ISSUE TITLE
【Bug】TypeError

### ISSUE THREAD

**Issue by kgtkr** [Microsoft/TypeScript#15461]
**TypeScript Version:** 2.2.2

**Code**
```ts
toDate(val: string | number): Date {
  return new Date(val);
}
```

**Expected behavior:** success

**Actual behavior:** Error

**Comment by rjamesnw** [comment]
This works in the playground: https://goo.gl/KtQZwT

Did you mean a compiler error?

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
