### ISSUE TITLE
JSDoc @arg and @argument tags not recognized as synonyms for @param

### ISSUE THREAD

**Issue by joechung-msft** [Microsoft/TypeScript#15477]
**TypeScript Version:**  2.3

Recognize @arg and @argument as synonyms for the [@param](http://usejsdoc.org/tags-param.html) tag.

I don't know if this was by design or not, but @returns is recognized as a synonym for @return so I expected synonyms to work.

**Code**
```js
// @ts-check

/**
 * @arg {string} input
 * @returns {string}
 */
export function foo(input) {
    return input.toLowerCase();
}
```

**Expected behavior:**
input is of type "string".

**Actual behavior:**
input is of type "any".

**Comment by joechung-msft** [comment]
For what it's worth, it looks like it is an easily correctable omission (including the code for the return/returns synonym for reference).

````
case "param":
    tag = parseParamTag(atToken, tagName);
    break;
case "return":
case "returns":
    tag = parseReturnTag(atToken, tagName);
    break;
````

https://github.com/Microsoft/TypeScript/blob/a1a2006074a01ca0b75b08294377cc52302e3e71/src/compiler/parser.ts#L6505-L6511

**Comment by mhegazy** [comment]
@joechung-msft a PR would be appreciated.
