### ISSUE TITLE
Compilation error with possibly nullable object

### ISSUE THREAD

**Issue by jurajkocan** [Microsoft/TypeScript#15482]
**TypeScript Version:**  2.3.2

**Code**

```ts
export const Fun1 = (): [string, null] | [null, string] => {
    return [null, 'string'];
};

export const Fun2 = (): string => {
    const [val1, val2] = Fun1();
    if (val1) {
        return val1;
    }
    return val2;
// compiler dosn't know val2 can't be ever null
};

```

**Expected behavior:**

No error

**Actual behavior:**

Type 'string | null' is not assignable to type 'string'.
Type 'null' is not assignable to type 'string'.

**Detail**

This seems like [10198](https://github.com/Microsoft/TypeScript/issues/10198), i have already new version of typescript but this is still not fixed.

**Comment by kitsonk** [comment]
It seems like for objects, the compiler properly tracks the types, as this works:

```ts
export const Fun3 = (): { val1: string; val2: null } | { val1: null; val2: string } => {
    return { val1: null, val2: 'string' };
};

export const Fun4 = (): string => {
    const { val1, val2 } = Fun3();
    if (val1) {
        return val1;
    }
    return val2;
};
```

So it seems the compiler doesn't properly track and narrow tuple members in the same way it does object property members.

**Comment by mhegazy** [comment]
The type of one of the keys is not a discriminant.  in both examples, the type of `val2` is `string|null` narrowing `val1` does not narrow the type of the return value of `func3`. 

Moreover, it is really hard to for the compiler to build a relationship between two variables in such a destructuring pattern.


see: https://github.com/Microsoft/TypeScript/issues/14630, https://github.com/Microsoft/TypeScript/issues/10976, https://github.com/Microsoft/TypeScript/issues/12263, https://github.com/Microsoft/TypeScript/issues/10065, and https://github.com/Microsoft/TypeScript/issues/10846

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
