### ISSUE TITLE
add ts.createTypeAliasDeclaration

### ISSUE THREAD

**Issue by mohsen1** [Microsoft/TypeScript#15489]
**TypeScript Version:**  2.3.2
Code

```ts
type Foo = {}
```

How can I generate a node that is equivalent of above source code?

**Comment by mhegazy** [comment]
You need to add a `createTypeAliasDeclaration` to factory.ts, something a la [createClassDeclaration](https://github.com/Microsoft/TypeScript/blob/7080c4155b2c6cc69c5dae3f312d720d434da3a3/src/compiler/factory.ts#L1421-L1430).

**Comment by mhegazy** [comment]
PRs welcomed.

**Comment by mohsen1** [comment]
Also need to add `{create|update}InterfaceDeclaration`

**Comment by mohsen1** [comment]
I came up with this hack for now:


```ts
    function buildTypeDeclarationStatement(name: string, type: ts.TypeNode, sourceFile: ts.SourceFile) {
        const printer = ts.createPrinter()
        const typeString = printer.printNode(ts.EmitHint.Unspecified, type, sourceFile);
        const newSource = ts.createSourceFile('temp.ts', `type ${name} = ${typeString}`, sourceFile.languageVersion);
        return newSource.statements[0];
    }
```

**Comment by mhegazy** [comment]
yup, https://github.com/Microsoft/TypeScript/issues/15497
