### ISSUE TITLE
instanceof check throws TS2454 variable is used before being assigned

### ISSUE THREAD

**Issue by StrikeForceZero** [Microsoft/TypeScript#15499]
**TypeScript Version:**  2.2.1, 2.3.2

`--strictNullChecks`

**Code**

[playground](https://www.typescriptlang.org/play/index.html#src=class%20Foo%20%7B%7D%3B%0D%0A%0D%0Alet%20foo%3A%20Foo%3B%0D%0A%0D%0Aif%20(foo%20instanceof%20Foo)%20%7B%0D%0A%20%20%20%20%2F%2F%20foo%20is%20Foo%0D%0A%7D%0D%0A%0D%0Aclass%20Bar%20%7B%7D%3B%0D%0Alet%20bar%3A%20Bar%20%7C%20undefined%3B%0D%0A%0D%0Aif%20(bar%20instanceof%20Bar)%20%7B%0D%0A%20%20%20%20%2F%2F%20bar%20is%20Bar%0D%0A%7D)

```ts
class Foo {};

let foo: Foo;

if (foo instanceof Foo) { // Throws TS2454 variable foo is used before being assigned
    // foo is Foo
}

class Bar {};
let bar: Bar | undefined;

if (bar instanceof Bar) {
    // bar is Bar
}
```

**Expected behavior:**

Unassigned left hand variables in a `instanceof` check should not throw `TS2454`. 
`instanceof` can return `false` when left hand unassigned variables, or `null`, or `undefined`

**Actual behavior:**

Throws `TS2454` variable foo is used before being assigned
Inconsistent behavior when variable type is a union with `undefined`

**Comment by RyanCavanaugh** [comment]
Why write a condition which is always false? That doesn't make any sense

**Comment by StrikeForceZero** [comment]
You make a good point. However, the use-case I discovered it in was using a `try-catch-finally`. 

The variable declared outside of the `try-catch-finally` may have been assigned anytime inside the `try`, `catch`,  or `finally` blocks thus `instanceof` has a possibility of returning true.

example:

```ts
class Foo {
    doSomethingThatMayThrow() {
        throw new Error('whoops');
    }
    cleanup() {
        // perform some kind of cleanup
    }
};

let foo: Foo;

try {
    foo = new Foo();
    foo.doSomethingThatMayThrow();
} finally {
    if (foo instanceof Foo) { // Throws TS2454 variable foo is used before being assigned
        // foo is still Foo
        foo.cleanup();
    }
}
```

**Comment by demisx** [comment]
I have this block of code that throws the same error. Is this related to this bug or am I doing something wrong? 

```ts
async function foo() {
  let bar: IBar

  try {
    bar = await Bar
      .query()
      ....
  } catch (err) {
  ...
  }

  ctx.body = bar // <- Throws variable 'bar' is used before being assigned. (TS2454)
```

**Comment by RyanCavanaugh** [comment]
@demisx the error is correct; it's possible `bar` doesn't get assigned

**Comment by demisx** [comment]
@RyanCavanaugh Thanks. I see. I've updated the example above with a little more detail inside the `catch {...}`. Please note, that if I uncomment `throw new Error()` in the catch block, TS understands that this block will never exit and the error goes away. 

What would be the right way to help TS compiler understand that `ctx.throw()` also never exits? This is the method's signature, but TS still doesn't see it as never exiting:

```ts
throw(...properties: Array<number | string | {}>): never;
```

**Comment by RyanCavanaugh** [comment]
`return ctx.throw('some error')`

**Comment by demisx** [comment]
@RyanCavanaugh That's what I did. 👍

**Comment by mhegazy** [comment]
if `foo` is not assigned at declaration site, consider declaring it using the `!` modifier:

```ts
let foo!: Foo;

try {
    foo = new Foo();
    foo.doSomethingThatMayThrow();
} finally {
    if (foo instanceof Foo) { 
        // foo is still Foo
        foo.cleanup();
    }
}
```

**Comment by debuglevel** [comment]
Is this actually best practice for `try catch` or is there some better pattern? I'm not a huge fan of forcefully removing any subsequent null checks.

In my code, I used `if (foo! ...` instead, which also seems to work. But as im a complete novice, better solutions are welcome.

```typescript
let foo: Foo;

try {
    foo = new Foo();
    foo.doSomethingThatMayThrow();
} finally {
    if (foo! instanceof Foo) { 
        // foo is still Foo
        foo.cleanup();
    }
}
```

**Comment by jgentes** [comment]
This does seem odd; notice the error even if the variable's existence is checked before use:

```ts
let foo: string

try {
  foo = 'bar'
} finally {
  if (foo) console.log('done')
  //  ^^^ Variable 'foo' is used before being assigned. ts(2454)
}
```

Reproduced here: https://www.typescriptlang.org/play?#code/DYUwLgBAZg9jBcEDOYBOBLAdgcwLACgC0BPCAbwImjggF4IByAIwENUGCBfaLF4YUhXxV0UCAApYMAJQQAxjExIYoAHTAY2cQwAmikA2lcCQA

**Comment by jgentes** [comment]
> This does seem odd; notice the error even if the variable's existence is checked before use:
> 
> ```ts
> let foo: string 
> ```
> 

I see, the type declaration doesn't allow for the variable to be undefined. So the fix is to allow it:
```ts
let foo: string | undefined
```

**Comment by RyanCavanaugh** [comment]
If you have some code that can't possibly throw, it doesn't make sense to put it inside the `try` in the first place. If you do have code that can possibly throw, then it's definitely the case that `foo` might not be initialized yet.
