### ISSUE TITLE
Compiling file does not result in expected error..

### ISSUE THREAD

**Issue by Thomasp24** [Microsoft/TypeScript#15493]
**TypeScript Version:**  2.2.2 / nightly (2.2.0-dev.201xxxxx)
I’m currently working on a mutation testing framework for TypeScript. My program must read a given set of files, change the code (mutate) and recompile, to find out if the mutated code results in a compile error so it can be excluded from the test process. As a test I have a file that, when mutated, should result in a compilation error:

```Typescript
class HelloWorld {
	public sayHello(name: string): string {
		return “Hello ” – name; // <-- should result in compile error!!
        }
}

```
**Code**
For compilation I created a CompilerHost which extends from a LanguageService host
```Typescript
// My CompilerHost
import MyLanguageServiceHost from "./MyLanguageServiceHost";
import * as ts from "typescript";

export default class MyCompilerHost extends MyLanguageServiceHost implements ts.CompilerHost {
    getSourceFile(filename: string, languageVersion: ts.ScriptTarget, onError?: (message: string) => void): ts.SourceFile {
        var f = this.files[filename];
        if (!f) return null;
        var sourceFile = ts.createLanguageServiceSourceFile(filename, f.file, ts.ScriptTarget.ES5, f.ver.toString(), true, 1);
        return sourceFile;
    }
    writeFile(filename: string, data: string, writeByteOrderMark: boolean, onError?: (message: string) => void): void {
    }
    getCanonicalFileName = (fileName: string) => fileName;
    useCaseSensitiveFileNames = () => true;
    getNewLine = () => "\n";
    getDirectories = path => ts.sys.getDirectories(path);
    fileExists = fileName => ts.sys.fileExists(fileName);
    readFile = fileName => ts.sys.readFile(fileName);
}

```
```Typescript
// MyLanguageServiceHost
import * as ts from "typescript";
export default class MyLanguageServiceHost implements ts.LanguageServiceHost {
    files: { [fileName: string]: { file: ts.IScriptSnapshot; ver: number } } = {}

    log = _ => { };
    trace = _ => { };
    error = _ => { };
    getCompilationSettings = ts.getDefaultCompilerOptions;
    getScriptIsOpen = _ => true;
    getCurrentDirectory = () => "";
    getDefaultLibFileName = _ => ts.getDefaultLibFileName(this.getCompilationSettings());

    getScriptVersion = fileName => this.files[fileName].ver.toString();
    getScriptSnapshot = fileName => this.files[fileName].file;

    getScriptFileNames(): string[] {
        var names: string[] = [];
        for (var name in this.files) {
            if (this.files.hasOwnProperty(name)) {
                names.push(name);
            }
        }
        return names;
    }

    addFile(fileName: string, body: string) {
        var snap = ts.ScriptSnapshot.fromString(body);
        snap.getChangeRange = _ => undefined;
        var existing = this.files[fileName];
        if (existing) {
            this.files[fileName].ver++;
            this.files[fileName].file = snap
          } else {
            this.files[fileName] = { ver: 1, file: snap };
        }
    }
}
```

To compile the changed code I do the following

```Typescript
import * as ts from "typescript";

const code: string = /* HelloWorld class mentioned above */
const sourceFilePaths: string[] = [/* Path to HelloWorld class */ ]
const index = 0; /* in this case there is only 1 file */

const compilerOptions: ts.CompilerOptions = {noEmitOnError: true, target: ts.ScriptTarget.ES5, noImplicitAny: true, module: ts.ModuleKind.CommonJS};
    
compilerHost.addFile(this.sourceFilePaths[index], code
compilerHost.addFile(sourceFilePaths[index], code /* code as string */);

let program = ts.createProgram(sourceFilePaths[index], compilerOptions, compilerHost);
let emitResult = this.program.emit();
let diagnostics = emitResult.diagnostics;
diagnostics.forEach(diagnostic => {
            console.log(ts.flattenDiagnosticMessageText(diagnostic.messageText, "\n"));
        });
```

**Expected behavior:**
Give compile error:
```
The left-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.
```

**Actual behavior:**
console output:
```
File 'lib.d.ts' not found.
'private' can only be used in a .ts file.
'types' can only be used in a .ts file.
'public' can only be used in a .ts file.
'types' can only be used in a .ts file.
Cannot find global type 'Array'.
Cannot find global type 'Boolean'.
Cannot find global type 'Function'.
Cannot find global type 'IArguments'.
Cannot find global type 'Number'.
Cannot find global type 'Object'.
Cannot find global type 'RegExp'.
Cannot find global type 'String'.
```
**Side Question**
For this program I want to compile my files in memory, without writing the mutated code to disk first. Is it possible to compile multiple ```ts.SourceFile``` objects instead of reading an existing file.
I'll be doing this a lot, so writing and reading from disk would take much time... 
I already keep track of all the SourceFile object in the ```MyCompilerHost``` object using ```ts.ScriptSnapShot```. 
Is there a way to use those instead?

**Comment by mhegazy** [comment]
the errors you are getting is because,  is the file name is `.js` and you do not have `--allowJs` enabled. and because the standard library was not included, nor was the compilerHost able to include it.

**Comment by mhegazy** [comment]
I would recommend reading up on the compiler architecture first: https://github.com/Microsoft/TypeScript/wiki/Architectural-Overview#data-structures

A `SourceFile` is a tree, you can generate it from a file by parsing it, or incrementally parsing it, providing an edit, or mutating the tree manually (as long as it is valid).

Note that it is assumed to be an immutable object, and identity is used to detect change. so if you change it, make sure you have a new SourceFile Object.

A `Program` is an immutable collection of `SourceFiles`. So every time you change one file, you need to create a new program.  You can pass the old program to the `createProgram` and it will try to reuse as much as possible. 

A good example to look at is the `--watch` implementation. see https://github.com/Microsoft/TypeScript/blob/master/src/compiler/tsc.ts#L486-L490

**Comment by Thomasp24** [comment]
First of all, thanks for the quick response! 
The file I am compiling is ```.ts``` , so that shouldn't be an issue.
The problem is the fact that the ```lib.d.ts``` file cannot be found, resulting in
```File 'lib.d.ts' not found.```.
I tried changing 
```getDefaultLibFileName = _ => ts.getDefaultLibFileName(this.getCompilationSettings());```
to
```getDefaultLibFileName = _ => ts.getDefaultLibFilePath(this.getCompilationSettings());```
Which is a valid path, but I doesn't seem to be able to include it...
How can I resolve this?

**Comment by mhegazy** [comment]
you need the full path.. see https://github.com/Microsoft/TypeScript/blob/d483df94ef07a6df5b91da077aa8f665a6425992/src/compiler/program.ts#L192

**Comment by Thomasp24** [comment]
I see.. However, ```ts.getDefaultLibFilePath()``` does return the full path. 
When I log it to console the path is valid, but I get the following error:
```File '/Users/thomasp/Desktop/projectfoler/node_modules/typescript/lib/lib.d.ts' not found.```
Do you have any idea why the file can't be read?
Would it help if I made a demo project for you to execute?

**Comment by mhegazy** [comment]
> Would it help if I made a demo project for you to execute?

sure.

**Comment by Thomasp24** [comment]
I made the situation described in the original post into a runnable project: 
https://github.com/Thomasp24/Typescript-Compiler-Test

**Comment by Thomasp24** [comment]
Found the issue. ```lib.d.ts``` wasn't included in the LanguageServiceHost for in-memory compilation. 
If anyone is trying something similar in the future:
Don't forget to add ```lib.d.ts``` tot the LanguageServiceHost!
```TypeScript
// File necessary for compilation
let libFile = readFileSync(this.compilerHost.getDefaultLibFileLocation());
this.compilerHost.addFile("lib.d.ts", libFile.toString());
```
Thanks for the help!
