### ISSUE TITLE
Suggestion: reflection for interface?

### ISSUE THREAD

**Issue by vilic** [Microsoft/TypeScript#1549]
Interface is a useful tool in TypeScript, but sometimes we'll need to write two pieces of almost identical code for intellisense and functionality respectively.

Is it acceptable to add a simple statement for generating part of interface information (properties)?

E.g.

```typescript
class SomeClass { }

interface ISubFace {
    abc: string;
    def: number;
}

interface IFace {
    str: string;
    num: number;
    obj: SomeClass;
    sub: ISubFace;
}

var faceInfo = reflect IFace;
```

Would emit:

```javascript
var SomeClass = (function () {
    function SomeClass() {
    }
    return SomeClass;
})();

var _ISubFaceReflection = {
    abc: 'string',
    def: 'number'
};
var _IFaceReflection = {
    str: 'string',
    num: 'number',
    obj: SomeClass,
    sub: _ISubFaceReflection
};

var faceInfo = _IFaceReflection;
```

**Comment by danquirk** [comment]
Run time type information (ie reflection) is currently outside our design goals (https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals). If we were to do something like what you're requesting it would most likely surface in the form of attributes like #1557

**Comment by SaschaNaz** [comment]
I saw @vilic saying this idea is not only for RTTI. (Now the comment is gone)

**Comment by ipy** [comment]
+1 for this feature. It will be of great help to deal with POJO ajax data and convert their types.

**Comment by meirgottlieb** [comment]
Take a look at this project: https://github.com/artifacthealth/tsreflect-compiler.

**Comment by vilic** [comment]
@meirgottlieb that is great but I guess it won't fit the needs. :'(

**Comment by rebeccapo** [comment]
Will TypeScript have reverse-engineering features like Reflection?

**Comment by remojansen** [comment]
:+1: I also think that it would be great to be able to access interfaces via reflection.

https://github.com/Microsoft/TypeScript/issues/3148#issuecomment-101945407

**Comment by electricmonk** [comment]
+1, would be very useful for stubbing interfaces, a-la Mockito (http://mockito.org/), something like:

```typescript
interface Animal {
   makeSound(): void;
}

const anAnimal = Mock.<Animal>create();
...
anAnimal.makeSound();
```

**Comment by mmiszy** [comment]
Unfortunately [tscompiler-reflect](https://github.com/artifacthealth/tsreflect-compiler) project is discontinued. Is there any way to get runtime type check in TypeScript? RTTC was one of the main design goals of AtScript.

**Comment by jianwu** [comment]
+1. I really hope to see typescript supports Java like reflection which is very useful for metadata driven designs such as use type information to generate auto-completion UI. The type information is valuable information which shouldn't be erased at runtime.

**Comment by blue112** [comment]
+1. This is a must have feature in any grown up language. One cannot be expected to rewrite all the types of an interface over again just to check the type.

**Comment by shumy** [comment]
The "keyof" and "reflect" is not the same! This has type information and can probably be usefull e.g in Angular2 Dependency Injection, injecting Interfaces.
We can have both or at least "reflect" that is more generic with.
