### ISSUE TITLE
Question:  what am I doing wrong?

### ISSUE THREAD

**Issue by daBishMan** [Microsoft/TypeScript#15508]
**TypeScript Version:**  2.2.1 / nightly (2.2.0-dev.201xxxxx)
version 2.2.2

**Code**
 I am using angular CLI 1.0.1, trying to incorporate ngrx

I create a map, an initialize it
  selectedCandidates: Map<string, SelectedProfile>;

When I try to delete it does not remove it from the map.
  newState.selectedCandidates.delete(candidateToRemove.id);

```ts
// A *self-contained* demonstration of the problem follows...
It does not remove the item using delete


```

**Expected behavior:**

**Actual behavior:**

**Comment by RyanCavanaugh** [comment]
This is a bug tracker, not a support forum.
