### ISSUE TITLE
Do not load plugins targetting older server versions

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#15504]
Tsserver should not load plugins that target newer versions. or ones that do not match its current version (after accounting for breaking changes).

Plugins should have a supported Version string in their package.json that is checked at load time.

**Comment by RyanCavanaugh** [comment]
Discussed with @mhegazy and we are going to document this and have plugins decide their own behavior rather than try to enforce a specific versioning scheme

**Comment by mhegazy** [comment]
// CC @chuckjaz and @egamma
