### ISSUE TITLE
Mapped type loses type bound when used with arithmetic operator

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#15501]
**TypeScript Version:**  nightly (2.4.0-dev.20170501)

**Code**

```ts
interface I { x: number; }

type IdentityMap<T> = {
    [P in keyof T]: T[P];
};

function f<T extends I>(i: IdentityMap<T>) {
    const n: number = i.x; // No error, good
    i.x * 2; // Error
}
```

**Expected behavior:**

No error.

**Actual behavior:**

`src/a.ts(9,5): error TS2362: The left-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.`

May be related to #14360.

**Comment by mhegazy** [comment]
This is not really special to mapped types. this is true for all generic variables:

```ts
function f2<T extends number>(x: T) {
    const n: number = x; // No error, good
    x * 2; // Error
}
```

the check we perform for these operators is that it has to be the type `number`, and not just a number. 

I am sure we have another issue for strings somewhere, but could not find it.
