### ISSUE TITLE
Send event to host if plugin failed to load

### ISSUE THREAD

**Issue by mhegazy** [microsoft/TypeScript#15503]
Based on the discussion with VSCode last week, we need to marshal an event about failing plugin loads.

**Comment by mhegazy** [comment]
From https://github.com/angelozerr/tslint-language-service/issues/32, we also need a way for plugins have send events to the host. for instance, in tslint, if a rule is deprecated, the plugin needs to send a warning to the user. currently they use console.log, but obviously this is not what we want.

**Comment by RyanCavanaugh** [comment]
This doesn't seem to be needed
