### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined in getNavigateToItems()

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/TypeScript#15509]
**TypeScript Version:**  2.3.2

When calling `getNavigateToItems()` with query `LanguageService` on a clone of this repo (Microsoft/TypeScript), it throws

```
 TypeError: Cannot read property 'name' of undefined
    at mergeSymbol (../node_modules/typescript/lib/typescript.js:25830:46)
    at ../node_modules/typescript/lib/typescript.js:25854:21
    at Map.forEach (native)
    at mergeSymbolTable (../node_modules/typescript/lib/typescript.js:25844:20)
    at initializeTypeChecker (../node_modules/typescript/lib/typescript.js:45947:21)
    at Object.createTypeChecker (../node_modules/typescript/lib/typescript.js:25710:9)
    at Object.getTypeChecker (../node_modules/typescript/lib/typescript.js:66883:79)
    at Object.getNavigateToItems (../node_modules/typescript/lib/typescript.js:85361:74)
```

**Comment by andy-ms** [comment]
Do you know what code you were testing this on?

**Comment by felixfbecker** [comment]
The code of this repository.

**Comment by andy-ms** [comment]
So you're both using the checkout of this repository, and you're testing the language service out on the repository?
Could you share the code you used to test this out?

**Comment by felixfbecker** [comment]
I am using TypeScript version 2.3.2 and call `getNavigateToItems('LanguageService')` to get the NavigateToItems of this repository.

The code is not very self-contained, but open source: https://sourcegraph.com/github.com/sourcegraph/javascript-typescript-langserver/-/blob/src/typescript-service.ts#L901:41-901:59
I am not sure how to create a self-contained repro case, would it help if I added a failing test case on a branch that you can step through?

**Comment by andy-ms** [comment]
I'll look at this tomorrow. Hopefully I can reproduce the error with a simple language service.

**Comment by andy-ms** [comment]
OK, this is hard to reproduce. Having a branch that reproduces the error would definitely help. Thanks!

**Comment by mhegazy** [comment]
closing for now. feel free to reopen if there are more information.
