### ISSUE TITLE
Add Missing Import Quick Fix Inserts Import Before "Use Strict" Directive 

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#15515]
**TypeScript Version:**  2.3.2

**Code**

`a.ts`:
```ts
"use strict";
export class A {}
```

`b.ts`
```ts
"use strict";
export class B extends A {}
```

Trigger a quickfix on `A` in `B extends A` to add the missing import

**Expected behavior:**
Resulting code:

```ts
"use strict";
import { A } from "./a";
export class B extends A {}
```

**Actual behavior:**
Import is to the head of the file, before `"use strict"`

```ts
import { A } from "./a";
"use strict";
export class B extends A {}
```

**Comment by mhegazy** [comment]
`"use strict"` is useless here. modules are always in strict more in ES6, and the code emitted by TS will do that too. so it is redundant.

**Comment by fatcerberus** [comment]
@mhegazy We do have `--noImplicitUseStrict` though.  That's not ES standards compliant of course, but is a documented option, so that would be a potential use case for the directive.

**Comment by DanielRosenwasser** [comment]
This should apply to both prologue directives and header comments (as referenced in #25907).
