### ISSUE TITLE
New Website Logo: DIMDATA

### ISSUE THREAD

**Issue by Tirmisee** [Microsoft/TypeScript#15526]
​Hi TypeScript

- Name: DIMDATA
- Homepage url: https://www.dimdata.com
- Brand Guidelines/Licensing: https://www.dimdata.com/terms.html
- Logo: https://www.dimdata.com/logo_l1.zip

Thanks

**Comment by Tirmisee** [comment]
Any updates?

**Comment by mhegazy** [comment]
We do them in patches. should be in the website when we do the next update.

**Comment by Tirmisee** [comment]
Thanks @mhegazy 

Can i request to update the logo?
New logo with fixed: https://www.dimdata.com/logo_t_m.png
