### ISSUE TITLE
Documentation tool is missing

### ISSUE THREAD

**Issue by jkufner** [Microsoft/TypeScript#15520]
I usually use Doxygen to generate documentation for my PHP and C++ projects. I would like to use it for TypeScript code as well. I looked for tools to build the docs and found nothing, except a feature request in JSDoc — https://github.com/jsdoc3/jsdoc/issues/272.

The documentation generator should scan source code tree and produce HTML output with the desired documentation, or provide a dox file for Doxygen. The dox file would be better as Doxygen already knows how to deal with the HTML output. Or it could integrate to any other widely-used documentation generator. The tool must be independent of any IDE, so it can be used in automated CI builds.

In case the documentation tool already exists, there should be a page in the TS documentation dedicated to it, so developers know what to use.

In case the documentation tool does not exist, it would be nice to add dox output to `tsc` so the `tsc --dox` can be used as input filter for Doxygen. It should be quite simple to implement as it only needs to collect doc comments and prepend them with few doxygen commands (very similar to javadoc) to specify class/method/function name, parameters, and types. It could be done the same way as `tsc --declaratinon`.

**Comment by rozzzly** [comment]
Check out [`typedoc`](https://github.com/TypeStrong/typedoc)

**Comment by feamsr00** [comment]
I'd have to +1 this and explicitly insist that `tsc` output dox (or similar intermediate format). Something like "typedoc" (or "jsdoc" for that matter) would not work in environments that might be using typescript heavily but are not using a node toolchain (indeed, relying on the tsc.exe deliverable!).

(An alternative might be shipping a tsdoc.exe deliverable, but that would be exactly that, a separate deliverable.) Additionally, (if I understand having TS' compiler targets correctly) having that functionality in tsc would make it easier for to use it on "non-.exe" targets and platforms.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Comment by jkufner** [comment]
@mhegazy This issue is not a question and it is not unactionable.

**Comment by mhegazy** [comment]
https://github.com/Microsoft/TypeScript/issues/10 is tracking that.
