### ISSUE TITLE
VS2017.2 Preview: Inconsistent error on array spread with Uint8Array

### ISSUE THREAD

**Issue by saschanaz** [microsoft/TypeScript#15524]
**TypeScript Version:**  2.3 (Visual Studio 2017 15.2 with "Intellisense - Use TypeScript Version": 2.3)

**Code**

```ts
[...Uint8Array.of(1, 2, 3)]
```

**Expected behavior:**

Should work without error

**Actual behavior:**

IntelliSense complains that Uint8Array is not array but build anyway proceeds without error, both with `--target es2017`. `dom.iterable` type is included.

**Comment by SaschaNaz** [comment]
Couldn't reopen #15366 so reposting.

**Comment by SaschaNaz** [comment]
Screenshot: 

![image](https://cloud.githubusercontent.com/assets/3396686/26540205/30e7386a-448b-11e7-9945-22acc24e76a5.png)

Relevant issue on VS Community side: https://developercommunity.visualstudio.com/content/problem/51859/vs-keeps-using-ts22-for-intellisense-while-using-t.html

**Comment by RyanCavanaugh** [comment]
Going to assume this is fixed by now 😑
