### ISSUE TITLE
Playground is broken 

### ISSUE THREAD

**Issue by mohsen1** [Microsoft/TypeScript#15522]
http://www.typescriptlang.org/play/index.html

monaco is not defined...

**Comment by DanielRosenwasser** [comment]
I'm actually not seeing the breakage 😕 

@mhegazy @bowdenk7 ?

**Comment by jesseschalken** [comment]
I got the same thing (`monaco is not defined` error in the console, both text areas are empty and don't respond to input). Using Chromium 56.0.2924.87 (64-bit).

**Comment by fatcerberus** [comment]
Yeah, same here.  Tested in Chrome, Firefox and Edge, doesn't work in any of them.

**Comment by DanielRosenwasser** [comment]
Verified. One of us on the team will try to look at this tomorrow morning.

**Comment by mhegazy** [comment]
Should be working now.

For those who are curious, looks like github.com updated their buttons script (https://buttons.github.io/buttons.js) which we had a link to in the footer of the page, the change overwrite the exports consumed by the custom loader from monaco.. :D
