### ISSUE TITLE
2.3.2 regression: class used before declaration

### ISSUE THREAD

**Issue by bjouhier** [Microsoft/TypeScript#15530]
**TypeScript Version:**  2.3.2

**Code**

```ts
const bar = { "foo": Foo };
class Foo {};
```

**Expected behavior:**

Compiles without errors (was the case in 2.2.2)

**Actual behavior:**

```
bug.ts(1,22): error TS2449: Class 'Foo' used before its declaration.
```

This is a regression from 2.2.2. I've seen #15102 and #15307 but they say that the problem is fixed in 2.3.1. This one is still in 2.3.2 (and also in `typescript@next`)

**Comment by vkurchatkin** [comment]
This code will throw at runtime, so this actually makes sense

**Comment by RyanCavanaugh** [comment]
The repro as written fails at runtime. If you're encountering this in code that *doesn't* fail at runtime, please provide a repro that demonstrates that behavior.

**Comment by bjouhier** [comment]
Of course! I did not notice that this code was in a side module that wasn't even imported yet. So this is definitely a feature, not a bug.

**Comment by flyfishMT** [comment]
When will this be available in Visual Studio?
