### ISSUE TITLE
Bad Completion on import of scoped package defined with @types

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/TypeScript#15533]
![scopedpackageimportcompletion2](https://cloud.githubusercontent.com/assets/3226984/25636807/6686c260-2f37-11e7-9432-18e5212e4903.png)

**TypeScript Version:**  master, commit c349dea8714f384c24

**Code**

At the caret (`^`), get completions, typing ctrl+space to do so.
```ts
// app.ts
import * as A from "^";

// node_modules/@types/foo__bar/index.d.ts
declare module "@biz/baz" { function fun(): string; }

// node_modules/@types/a__b/index.d.ts
export declare let x: number;
```

**Expected behavior:**
Get import for `@foo/bar` ,`@biz/baz` and `@a/b`

**Actual behavior:**

Get import for `foo__bar`, `@biz/baz` and `a__b`.

EDIT: clarifications

**Comment by mhegazy** [comment]
This is caused by https://github.com/Microsoft/TypeScript/pull/15051. since `@types` is scoped we have to flatten scoped packages. 
For this issue, the completion needs to reverse engineer the flattened names.

**Comment by andy-ms** [comment]
Related: #15545

**Comment by aozgaa** [comment]
I additionally observed that writing
``` ts
import * as A from "foo__bar"
```
yields no error, though it probably ought to.

**Comment by amcasey** [comment]
Current behavior:

| Import | Offered by Completion | Compiles|
| --- | --- | --- |
|`@foo/bar`|No|TS2306 - not a module|
|`@biz/baz`|Yes|Yes|
|`@a/b`|**No**|Yes|
|`foo__bar`|No|TS2306 - not a module|
|`biz__baz`|No|TS2307 - not found|
|`a__b`|No|**Yes**|

@minestarks I believe you did some cleanup in this area.  Do the bolded cells seem like the right things to fix?

**Comment by minestarks** [comment]
@amcasey I'm not sure... Couldn't `a__b` be a legitimate package on npm? The last box could be by design. How do we disambiguate?

**Comment by amcasey** [comment]
@minestarks Yes, I understand that packages `@a/b` and `a__b` both map to `@types/a__b`.  Maybe we want to produce an error if you import either `@a/b` and `a__b` and only the other is present?

**Comment by amcasey** [comment]
That is probably a separate, lower-priority item.  Two bigger problems:
 1. We don't de-dup the completion entries for type modules.
 2. We don't unmangle the names.

Question: do we offer both mangled and unmangled?

**Comment by andy-ms** [comment]
If there is a `@types/a__b` present, I think we should only offer a completion for `@a`, not for `a__b`, since we haven't published any `@types` packages that correspond to an NPM package with a `__` in its name.

**Comment by amcasey** [comment]
The import code fix defaults to the unmangled name, which seems reasonable.
