### ISSUE TITLE
typescriptlang.org Playground not working

### ISSUE THREAD

**Issue by marekpetak** [Microsoft/TypeScript#15549]
No sure if this is the right place to report this ...

https://www.typescriptlang.org/play/

ReferenceError: monaco is not defined - playground.js

The Playground for not seems to work. Cannot type code to the the boxes neither the drop downs will not select example code...

![capture](https://cloud.githubusercontent.com/assets/7045818/25651169/71d3adb6-2fd9-11e7-8680-58868690bf45.PNG)

Tired this on latest Chrome, FF and Opera.

**Comment by ikatyang** [comment]
duplicate https://github.com/Microsoft/TypeScript/issues/15522
