### ISSUE TITLE
doesn't respect symlinks

### ISSUE THREAD

**Issue by patrikx3** [Microsoft/TypeScript#15544]
Hi!
How are you?

**TypeScript Version:**  2.2.1 / nightly (2.2.0-dev.201xxxxx)
2.3.2

**Compile**
when i use an npm/yarn linked package, and i compile a lib, it uses the hard path, instead of the symlink path, it should use the expected path, not the hard path

**Expected behavior:**
respect symlinks, resolve to the expected path.

**Actual behavior:**
it resolves not to the sylink location but the hard link.
there is no solution, please make typescript use symlinks

**Comment by andy-ms** [comment]
Why is it a problem that TypeScript resolves symlinks?

**Comment by patrikx3** [comment]
ciao!
how are you?

there is a module
```/project/modulle/module-sub```

i use it in another module:
```project/module/app/node_modules/module-sub```

when it is not a symlink, it works. since in the ```module-sub``` looking for path, it is going up and up, like node does. with commonjs ```require```

but when 

```project/module/app/node_modules/~module-sub``` is a symlink

typescript finds out it is a symlink and when it compiles, it just changes to ```/project/module/module-sub/```

of course with ```node```, it is not working.
when typescript compiles, and if it is a symlink, it should keep the symlink where it is, it should not change the path, since with ```node_modules``` ```commonjs``` uses the ```require``` going up to up.
since it was a symlink, it changed, it is not finding the modules. and it often with ```angular```, ```webpack```, cannot work with linked modules and it is with typescript only, with ```node``` javascript, it works.

since the commonjs ```require``` looks in the path from going to the top looking for the ```node_modules```-s, but since it is changed by typesciprt, it is not working.

can you get it clear?

**Comment by patrikx3** [comment]
there are some workarounds, but in actually doesn't work, like ```node```, ```commonjs``` and the issue is that typescript is changes the paths, it should respect the symlink and not change to hard link path.
```node``` js works with ```require```

you can override paths, but you always have to change here, then different module i have to change, it will not working.

please keep the path and not override the symlink path :)

if typescript founds it is a symlink. it compiles from the hard link, instead of the expected symlink path, please compile to the symlink location path. :)

**Comment by andy-ms** [comment]
> since with node_modules commonjs uses the require going up to up.

It looks like node's require is relative to the real path, not the symlinked path. So when you have:

```
/module
	/app
		/node_modules
			/dep
				index.js: `module.exports = "dep from symlink path";`
			/module-sub = a symlink to ../../module-sub
		index.js: `require("module-sub");`
	/module-sub
		index.js: `console.log(require("dep"));`
	/node_modules
		/dep
			index.js: `module.exports = "dep from real path";`
```

Running `app/index.js` will print `dep from real path`.

**Comment by patrikx3** [comment]
That's true.
The problem is, that it resolves to the hard link, see on the bottom.
It doesn't find the ```node_modules```, and it looks to the up, but there is nothing on the top, since it is in the top when it is a symlink, but since it finds the hard path, it doesn't find.
When I use real hard links it is working, but when i use symlink it uses the hard instead the symlink. :(

![image](https://cloud.githubusercontent.com/assets/4770180/25680524/6e1c2ee6-3051-11e7-8c30-64d53d1ae3b5.png)

![image](https://cloud.githubusercontent.com/assets/4770180/25680548/8582a628-3051-11e7-80d3-eab917d9fd8e.png)

![image](https://cloud.githubusercontent.com/assets/4770180/25680592/b30383e2-3051-11e7-9eb4-7378077fd4b9.png)

Why is it looking for the hard path when it is a symlink? Why doesn't keep where it should be? 
It changes the path!

**Comment by patrikx3** [comment]
Of course, when I do not use symlinks, it is expected.
With NODEJS it finds, with typescript it doesnt find with symlinks.

So it does not respect the symlink, it uses hard link. Drops symlinks always. I can find the actual file, but it uses modules, which since it is somehwere else , it doesn't find the required node modules.

I am in a symlinked file:
```typescript
import { anyModule } form 'your-module'
```
Yes the file is there! 
Cannot find module `your-module'

**Comment by andy-ms** [comment]
Can you get a reproducible example of some code that works through node.js but not in TypeScript's module resolution?

**Comment by patrikx3** [comment]
its right there on the screen, it is in node_modules, it thinks it not in node_modules.
it should say: ```/corifeus/corifeus-app-web-pages/node_moduels/corifeus-web-material/src/...```
and it thinks
```../corifeus-web-material/src/...```

**Comment by andy-ms** [comment]
Hi, can you provide instructions that I could use to create such a scenario on my end? Something like my above comment https://github.com/Microsoft/TypeScript/issues/15544#issuecomment-298977233
