### ISSUE TITLE
@types import considered valid

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/TypeScript#15540]
**TypeScript Version:**  2.2.1 / nightly (2.2.0-dev.201xxxxx)

**Code**

```ts
// tsconfig.json
{}

// app.ts
import {x} from "@types/myLib";

// node_modules/@types/myLib/index.d.ts
export declare let x: number;

```

**Expected behavior:**
Error on import in `app.ts`. Perhaps with a suggestion/quickfix to remove the `@types/` prefix?

**Actual behavior:**
No error on import.

**Comment by nowy** [comment]
@aozgaa I will be submitting a PR today for this
