### ISSUE TITLE
Error TS2532 should identify the variable reference that could be undefined.

### ISSUE THREAD

**Issue by hawketh** [Microsoft/TypeScript#15556]
**TypeScript Version:**  2.2.1 / nightly (2.2.0-dev.201xxxxx)

**Code**

```ts
// Angular code reference:  {{wrapper.event}}, {{wrapper.event.idSpec.name}}
// Wrapper contains various things, here an 'event' all of whose members could be null/undefined.

@Component({}) export class X { @Input() wrapper?: Wrapper; }
```

**Expected behavior:**
Something like this:
  * `error TS2532: Object [wrapper] is possibly 'undefined'.`
  * `error TS2532: Object [wrapper.event.idSpec] is possibly 'undefined'.`

**Actual behavior:**
Multiple occurrences of unhelpful message because it's coming from the ng_factory class, and you can't readily relate back to the source file:  `error TS2532: Object is possibly 'undefined'.`

**Comment by mhegazy** [comment]
I am having troupe piecing together the input. can you share more context?

**Comment by hawketh** [comment]
I have an Angular 2 template that contains value insertion, something like:  `<span class="title">{{wrapper.event.idSpec.name}}</span>`.  Wrapper is an instance of a support class that is initialized with an `event` parameter (among other things).  The `event` class is generated from a protobuf declaration, and it contains an `idSpec` submessage.  The nature of the generated protobuf files is that all fields are defined as `<type>|null`.

```ts
// message IdentifierSpec {
//   string name = 1;
//   yada yada yada
// }
// message Event {
//   IdentifierSpec idSpec = 1;
//   blah blah blah
// }
import {Event} from 'event_proto_js_api';
export class EventWrapper {
  event: Event;
  // and so forth
}
```

When it gets around to compiling the ngFactory generated class, it complains about the text insertion `{{wrapper.event.idSpec.name}}` because the last three components could all be null, so dereferencing can produce errors.  Technically, the reference should be written as `{{wrapper.event?.idSpec?.name}}`.  My objection is the error message:  it doesn't tell me which part of the name it's complaining about, and getting multiple messages for the same line is confusing without that context.  Since to do null detection you've had to do a symbol table lookup on [part of] the name, just insert the name, either the individual field or the qualified reference up to that point, into the diagnostic.

[Yes, the problem is partially because it's compiling a generated file without back-references to the original, so you have no context to help with this.  Let's skip that for the moment.]

**Comment by mhegazy** [comment]
> The event class is generated from a protobuf declaration, and it contains an idSpec submessage. The nature of the generated protobuf files is that all fields are defined as <type>|null.

Who generates that definition file? the TS compiler does not.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Comment by hawketh** [comment]
This is not about what code gets generated.  It's about the diagnostic message the compiler produces when it encounters a possibly null or undefined field.  If you have a sequence of a.b.c and any of them could be undefined, the compiler doesn't tell you what part of the variable reference it's complaining about.  It just says "Object could be undefined".  It doesn't matter that this may have come from a protobuf.  It's the _message_ content, not the actual fact that you get a message.

**Comment by hawketh** [comment]
Please reopen.

**Comment by RyanCavanaugh** [comment]
@hawketh you'll need to provide a repro that doesn't involve components which we have no control over
