### ISSUE TITLE
VS2017 and automatic type acquisition

### ISSUE THREAD

**Issue by DickvdBrink** [Microsoft/TypeScript#15554]
I'm using VS2017 with a `csproj` for TypeScript; I don't use the VS `Open folder`, is it possible to disable the automatic type acquisition feature? I did put this in my `tsconfig.json` but I suspect it doesn't work that way when using a `csproj` right?

I used the tsconfig with as defined [here](https://github.com/Microsoft/TypeScript/wiki/JavaScript-Language-Service-in-Visual-Studio#-automatic-acquisition-of-type-definitions)
```
"typingOptions": {
  "enableAutoDiscovery": true
}
```
but I still see a node process (after restarting VS) with a commandline for `typinginstaller.js`. I wish to disable this feature because it is conflicting with my other definitions which are part of the source code and the downloaded definitions by TypeScript.

I do not have @types packages in my package.json btw

VS 15.1 (26403.3)

**Comment by mhegazy** [comment]
>  I wish to disable this feature because it is conflicting with my other definitions which are part of the source code and the downloaded definitions by TypeScript.

Can you share some information about what you are seeing? are you seeing the same symptoms as https://github.com/Microsoft/TypeScript/issues/14565? Can you try using 15.2?

**Comment by DickvdBrink** [comment]
Will reopen when I have more info and when I have access to that pc. Symptoms where similar to the issue you mentioned

**Comment by DickvdBrink** [comment]
Ah, 15.2 is preview; not allowed to install that on this pc. The symptoms are similar so I suspect it is fixed. Will wait for it to become available in a public release and report back when I still have the issue. 

Though a setting to disable ATA might still be desirable from within VS :)
