### ISSUE TITLE
Incorrect typecheck on generic Promise<T> with inheritance

### ISSUE THREAD

**Issue by 19majkel94** [Microsoft/TypeScript#15564]
**TypeScript Version:**  2.3.2

**Code**

```ts
class A {
    a: number;
}

class Aplus extends A {
    plus = () => true;
}

function newAplusAsync(): Promise<Aplus> {
    return Promise.resolve(new A());
}

(async () => {
    const aplus = await newAplusAsync();
    console.log(aplus.plus());
})();
```

**Expected behavior:**
Compiler error: `Type 'Promise<A>' is not assignable to type 'Promise<Aplus>'`

**Actual behavior:**
Runtime error: `aplus.plus is not a function​​`

**Comment by mhegazy** [comment]
Should be fixed by https://github.com/Microsoft/TypeScript/pull/15104, fix should be available today in `typescript@next`.
