### ISSUE TITLE
JSDoc output types

### ISSUE THREAD

**Issue by NN---** [Microsoft/TypeScript#15563]
**TypeScript Version:**  2.2.1 / nightly (2.2.0-dev.201xxxxx)

**Code**
Is there an option to autogenerate types in JSDoc for any function ?

For instance given
```ts
function f(x:number):number { return x+1; }

/**
 * @param x Something
 */
function g(x:number):number { return x+1; }
```

I would get output of:
```ts
/**
 * @param x {number}
 */
function f(x:number):number { return x+1; }

/**
 * @param x {number} Something
 */
function g(x:number):number { return x+1; }
```

It helps debugging JS code.

**Comment by j-oliveras** [comment]
Duplicated of #10?

**Comment by NN---** [comment]
Seems so.
Couldn't find it.
Thanks.
