### ISSUE TITLE
Generic hash base type (Suggestion)

### ISSUE THREAD

**Issue by cwunderly** [Microsoft/TypeScript#15561]
In Typescript and javascript  all variables are hashes.  There isn't necessarily a specific hash object.  But the hash is a non generic type that returns type any and there is no way of have a typed hash without creating your own object which of course then adds overhead.  It would be nice to have a base type in typescript that can be used generically that would cast the return of a [] statement on a variable with the type specific in the generic declaration of the variable.  
An example would be the following.
`var hash: Hash<string> = {};
var value = hash['somekey'];
`

The value would have the implicit type of string based on the declaration of the hash and wouldn't require additional casting of the value coming back from the object.

**Comment by kitsonk** [comment]
How would this differ from:

```ts
interface Hash<T> {
  [key: string]: T;
}

const hash: Hash<string> = {};
hash['somekey'] = 'foo';
```

**Comment by cwunderly** [comment]
Didn't realize you could declare that in an interface.  Would still be nice to have it as a base type i guess but i could very easily make that myself.

**Comment by cwunderly** [comment]
Trying that out this does bring up a slight irregularity in the error reporting behavior.  I would have declared
the hash to be this instead. `interface Hash<T> {
  [key: string|number]: T;
}
`
But the compiler tells me it has to be a string or number but it can't be a string "or" number in the syntactical sense.

**Comment by kitsonk** [comment]
> But the compiler tells me it has to be a string or number but it can't be a string "or" number in the syntactical sense.

Because you can't... indexes have to be `string` or `number` not the intersection of the two.  At runtime they are technically always `string`, but `number` is allowed to make it easier to model `Array` and its related types.

**Comment by cwunderly** [comment]
OK I read up on the union symbol.  I had seen it and used in other code and assumed that | meant or.  I realize now that it isn't the same thing.  That makes sense.  Thanks for the clarification.
