### ISSUE TITLE
Lack of type checking for callback parameters

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#15579]
**TypeScript Version:**  master

**Code**

```ts
function f(g: (ev: Event) => any) { }
function g(ev: MouseEvent) { }
f(g);
f(ev => g(ev));
```

**Expected behavior:**

```
$ node built/local/tsc.js index.ts --noEmit --strict
index.ts(3,3): error ...
index.ts(4,11): error TS2345: Argument of type 'Event' is not assignable to parameter of type 'MouseEvent'.
  Property 'altKey' is missing in type 'Event'.
```

**Actual behavior:**

```
$ node built/local/tsc.js index.ts --noEmit --strict
index.ts(4,11): error TS2345: Argument of type 'Event' is not assignable to parameter of type 'MouseEvent'.
  Property 'altKey' is missing in type 'Event'.
```

**Comment by mhegazy** [comment]
https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-function-parameters-bivariant

**Comment by falsandtru** [comment]
I didn't know that well because the FAQ doesn't say specific definitions of types of Animal and Dog. But it seems like you can keep the consistency of `f(g)` and `f(ev => g(ev))`. Are you really choosing the current inconsistency?

**Comment by RyanCavanaugh** [comment]
Suffice to say we've thought about this problem *a lot* and are sticking with the current situation.
