### ISSUE TITLE
Cant import modules by absolute path

### ISSUE THREAD

**Issue by nonamez** [Microsoft/TypeScript#15578]
**TypeScript Version:**  2.2.1 

**Code**
```
{
	"compilerOptions": {
		"allowSyntheticDefaultImports": true,
		"declaration": false,
		"emitDecoratorMetadata": true,
		"experimentalDecorators": true,
		"lib": [
			"dom",
			"es2015"
		],
		"module": "es2015",
		"moduleResolution": "node",
		"sourceMap": true,
		"target": "es5",
		"baseUrl": ".",
		"paths": {
			"providers/*": ["src/providers/*"]
		}
	},
	"include": [
		"src/**/*.ts"
	],
	"exclude": [
		"node_modules"
	],
	"compileOnSave": false,
	"atom": {
		"rewriteTsconfig": false
	}
}
```
```ts
import { APIRequest } from 'providers/api-request';
```

**Expected behavior:**
The module should be imported by absolute path

**Actual behavior:**
The module not found

**My app structure:** 
![image](https://cloud.githubusercontent.com/assets/1894964/25695758/044b9512-30bd-11e7-8f16-a909154d9ba2.png)

**Error description:** 
![image](https://cloud.githubusercontent.com/assets/1894964/25695743/f96ba8a8-30bc-11e7-8ca3-894397554740.png)

**Comment by kitsonk** [comment]
This has nothing to do with TypeScript.  You have told TypeScript that at run time `providers/api-request` will be available for importing using the `paths` but you have not configured your WebPack build to actually make that module available with that absolute MID.  You need to change your WebPack configuration/build.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
