### ISSUE TITLE
Unable to modify class after `export =`

### ISSUE THREAD

**Issue by trusktr** [Microsoft/TypeScript#15571]
**TypeScript Version:**  2.2.1

**Code**

```ts
export = class Foo { }
Foo.default = ['asdf','qwer']
```

**Expected behavior:**

We should be able to modify the class,

**Actual behavior:**

but instead we get 

```
Cannot find name 'Foo'.
```

We can work around the problem by doing

```ts
class Foo { }
Foo.default = ['asdf','qwer']
export = Foo
```

or

```ts
class Foo { }
export = Foo
Foo.default = ['asdf', 'qwer']
```

I am thinking that it would be nice to follow ES6 module behavior, where for example we can do:

```
export class Foo { }
Foo.default = ['asdf', 'qwer']
```

and we can modify the class after having defined it as an export.

`export = ` is merely a different type of export, but I think it would be nice for it to follow that ES6 pattern.

**Comment by mhegazy** [comment]
First `export = ` is not an ES6 export form. it is a CommonJS/AMD compat form.

Second, `export = class Foo` the right hand is an expression, meaning that `Foo` is not visible outside the class expression, which is different from `export default class Foo`.

It is also worth noting that:

```ts
export = class Foo {}
```
only exports the value (i.e. the class expression), and not the type. where exporting an identifier exports all meaning of a type.

```ts
class Foo{ }
export = Foo;
```
Moreover the second line is not legal either:

```ts
class Foo { }
Foo.default = ['asdf','qwer'] // Error: default does not exist on class Foo
export = Foo
```

**Comment by AJamesPhillips** [comment]
I'm still struggling to get my head around all the import, export, defaults, different module definitions, different tsconfig modules, targets.  It's pretty daunting.  Thanks for the explanation mhegazy.  I feel like it'd be good to track all of these together in one place so that people can understand by example to support the theory and examples in the handbook https://www.typescriptlang.org/docs/handbook/modules.html.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
