### ISSUE TITLE
[JS] React stateless components propTypes error

### ISSUE THREAD

**Issue by methyl** [Microsoft/TypeScript#15587]
**TypeScript Version:**  2.2.1 / nightly (2.2.0-dev.201xxxxx)

**Code**

```ts
const ReactComponent = ({ props }) =>
  <div
    {props.children}
  </div>

ReactComponent.propTypes = {
  name: PropTypes.string,
  navBar: PropTypes.node,
  children: PropTypes.node,
}

```

**Expected behavior:**

propTypes is a valid property on React stateless component and should be passed.

**Actual behavior:**
`[js] Property 'propTypes' does not exist on type '({props}: { props: any; }) => Element`

**Comment by mhegazy** [comment]
You need to tell the compiler that it is a `StatelessComponent` and not just any random function:

```ts
const ReactComponent: React.StatelessComponent<....> = (props) =>
  <div>
    {props.children}
  </div>
```

**Comment by methyl** [comment]
I'm using plain JS and not TS, leveraging Typescript 2.3 possibility to check it. Is there any way to silence down some errors that TypeScript engine can't properly infer, as I see big value anyway from other stuff it provides?

**Comment by mhegazy** [comment]
```ts
// @ts-check

import { PropTypes, StatelessComponent }from "react";

/** @type { StatelessComponent<{name, navBar, children}> } */
const ReactComponent = (props) =>
    <div>
        {props.children}
    </div>;

ReactComponent.propTypes = {
    name: PropTypes.string,
    navBar: PropTypes.node,
    children: PropTypes.node,
}
```

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
