### ISSUE TITLE
Type not inferred in error message

### ISSUE THREAD

**Issue by CoenraadS** [Microsoft/TypeScript#15580]
**TypeScript Version:**  2.3.2

**Code**

```ts
const a = 12;
a.foo = "Property 'foo' does not exist on type '12'";

const b: number = 12;
b.foo = "Property 'foo' does not exist on type 'number'";
```

**Expected behavior:**

a.foo error message should be the same as b.foo.

**Actual behavior:**
`"Property 'foo' does not exist on type '12'"`

But 12 is not a type.

**Comment by kitsonk** [comment]
It is a type... It is a literal type of `number`, a subset.

When you declare primatives as `const`, TypeScript will infer a literal type.  `1`, `2`, `3`, etc. are literal types of `number`, just like `'a'`, `'b'`, `'c'`, etc... are literal types of `string` and `true`, `false` are literal types of `boolean`.

If you changed it to:

```
let a = 12;
a.foo; // Property 'foo' does not exist on type 'number'
```
