### ISSUE TITLE
Incomplete enum type check

### ISSUE THREAD

**Issue by svr93** [Microsoft/TypeScript#15591]
enum with custom values not fully checked
**TypeScript Version:**  2.3.2

**Code**

```ts
enum A {
    B = 2,
    C = 7
}

function getSomething(str: string, a: A): void {

}

getSomething('str', A.B) // 1
getSomething('str', 9) // 2
getSomething('str', 'x') // 3
```

**Expected behavior:**
1. OK.
2. Should throw.
3. Should throw.
**Actual behavior:**
1) OK.
2) OK.
3) error TS2345: Argument of type '"x"' is not assignable to parameter of type 'A'.

**Comment by mhegazy** [comment]
numbers are assignable to enums to allow for flag manipulations.

**Comment by svr93** [comment]
I think that enum and union type should have similar behaviour:

ts```
enum A {
    B = 2,
    C = 7
}

function getSomethingWithEnum(str: string, a: A): void {

}

getSomethingWithEnum('str', 9) // 1

type X = 2 | 7
function getSomethingWithUnion(str: string, x: X): void {

}
getSomethingWithUnion('str', 9) // 2
```
**Expected behavior:**

1) Should throw.
2) Should throw.
**Actual behavior:**
1) OK.
2) error TS2345: Argument of type '9' is not assignable to parameter of type 'X'.

**Comment by mhegazy** [comment]
Enums have a special behaviour here to allow for flag manibulations. it is common to have enums like:
```ts
    export const enum SymbolFlags {
        None                    = 0,
        FunctionScopedVariable  = 1 << 0,   // Variable (var) or parameter
        BlockScopedVariable     = 1 << 1,   // A block-scoped variable (let or const)
        Property                = 1 << 2,   // Property or enum member
        EnumMember              = 1 << 3,   // Enum member
        Function                = 1 << 4,   // Function
        Class                   = 1 << 5,   // Class
        Interface               = 1 << 6,   // Interface
        ConstEnum               = 1 << 7,   // Const enum
        RegularEnum             = 1 << 8,   // Enum
        ValueModule             = 1 << 9,   // Instantiated module
        NamespaceModule         = 1 << 10,  // Uninstantiated module
        TypeLiteral             = 1 << 11,  // Type Literal or mapped type
        ObjectLiteral           = 1 << 12,  // Object Literal
        Method                  = 1 << 13,  // Method
        .....
```

A union type here would not be correct. and everytime you want to set `flags |= Flags.Method` you need to cast.

**Comment by DanielRosenwasser** [comment]
[From the spec](https://github.com/Microsoft/TypeScript/blob/96aca4c7d090ed0842bc464c3ab683400f9679ef/doc/spec.md#328-enum-types).

> Enum types are distinct user defined subtypes of the Number primitive type. Enum types are declared using enum declarations (section [9.1](https://github.com/Microsoft/TypeScript/blob/96aca4c7d090ed0842bc464c3ab683400f9679ef/doc/spec.md#9.1)) and referenced using type references (section [3.8.2](https://github.com/Microsoft/TypeScript/blob/96aca4c7d090ed0842bc464c3ab683400f9679ef/doc/spec.md#3.8.2)).
>
> Enum types are assignable to the Number primitive type, and vice versa, but different enum types are not assignable to each other.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
