### ISSUE TITLE
Class+interface declaration merging is significantly slower than interface+variable pattern

### ISSUE THREAD

**Issue by saschanaz** [microsoft/TypeScript#15592]
**TypeScript Version:**  2.2.1 / nightly (2.2.0-dev.201xxxxx)

**Code**

```ts
interface CSSConditionRule extends CSSGroupingRule {}
declare class CSSConditionRule {
    conditionText: string;
}
```

```ts
interface CSSConditionRule extends CSSGroupingRule {
    conditionText: string;
}

declare var CSSConditionRule: {
    prototype: CSSConditionRule;
    new(): CSSConditionRule;
}
```

**Expected behavior:**

Both should show similar performance

**Actual behavior:**

Former creates much more symbols and thus significantly slower. Authors should be able to write types as class declarations without performance degradation.

See https://github.com/Microsoft/TSJS-lib-generator/pull/244 for actual performance diagnostics.

**Comment by RyanCavanaugh** [comment]
I don't know what we're supposed to do with this. Which symbols *shouldn't* have been created a result, etc?
