### ISSUE TITLE
JSDoc Recursive Type Not Displayed Properly

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#15597]
From https://github.com/Microsoft/vscode/issues/25957

**TypeScript Version:**  2.3.2

**Code**

```js
/**
 * @typedef RecursiveObject
 * @property {RecursiveObject} children
 */

/**
 * @param {RecursiveObject} param
 */
function func(param){
    param.children
}
```

**Expected behavior:**
Type of `param` is displayed as `RecursiveObject` or `{"children": RecursiveObject}`

Type of `param.children` is displayed as `RecursiveObject` or `{"children": RecursiveObject}`

**Actual behavior:**
Type of `param` is displayed as `{"children": any }`

Type of `param.children` is displayed as `{"children": any }`

---

This only seems to effect the display values. The type checking itself works fine

**Comment by sandersn** [comment]
Fixed in 3.8.
