### ISSUE TITLE
Mapped types, trouble with array member?

### ISSUE THREAD

**Issue by JasonKleban** [Microsoft/TypeScript#15598]
I'm thinking this is a bug.  The intention here is to create a parallel nested type.  I'm having trouble with the array member here - there are some type restrictions being enforced, but not enough.  `myValidation.c` shouldn't be allowed to be an array at all, let alone an array of string, but it seems to allow an array of any type there.

```
interface ValidationRule<T, RootState extends object> {
    isValid: (value: T, state?: RootState) => boolean
}

type Validated<State extends object, Root extends object = State> = {
    [Member in keyof State]:
        Validated<State[Member], Root>
        | ValidationRule<State[Member], Root>;
}

interface AppState {
    a: number,
    b: string,
    c: number[]
}

var myAppState: AppState = {
    a: 5,
    b: "Hello",
    c: [7, 11]
}

var myValidation: Validated<AppState> = {
    a: {
        isValid: (v, s) => true
    },
    b: {
        isValid: (v) => true
    },
    // c: {} //does error, good
    // c: "" //does error, good
    c: ["Why", "doesn't", "this", "error"] // <-- should error
}
```

[Playground link](https://www.typescriptlang.org/play/#src=%0D%0Ainterface%20ValidationRule%3CT%2C%20RootState%20extends%20object%3E%20%7B%0D%0A%20%20%20%20isValid%3A%20(value%3A%20T%2C%20state%3F%3A%20RootState)%20%3D%3E%20boolean%0D%0A%7D%0D%0A%0D%0Atype%20Validated%3CState%20extends%20object%2C%20Root%20extends%20object%20%3D%20State%3E%20%3D%20%7B%0D%0A%20%20%20%20%5BMember%20in%20keyof%20State%5D%3A%0D%0A%20%20%20%20%20%20%20%20Validated%3CState%5BMember%5D%2C%20Root%3E%0D%0A%20%20%20%20%20%20%20%20%7C%20ValidationRule%3CState%5BMember%5D%2C%20Root%3E%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20AppState%20%7B%0D%0A%20%20%20%20a%3A%20number%2C%0D%0A%20%20%20%20b%3A%20string%2C%0D%0A%20%20%20%20c%3A%20number%5B%5D%0D%0A%7D%0D%0A%0D%0Avar%20myAppState%3A%20AppState%20%3D%20%7B%0D%0A%20%20%20%20a%3A%205%2C%0D%0A%20%20%20%20b%3A%20%22Hello%22%2C%0D%0A%20%20%20%20c%3A%20%5B7%2C%2011%5D%0D%0A%7D%0D%0A%0D%0Avar%20myValidation%3A%20Validated%3CAppState%3E%20%3D%20%7B%0D%0A%20%20%20%20a%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20isValid%3A%20(v%2C%20s)%20%3D%3E%20true%0D%0A%20%20%20%20%7D%2C%0D%0A%20%20%20%20b%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20isValid%3A%20(v)%20%3D%3E%20true%0D%0A%20%20%20%20%7D%2C%0D%0A%20%20%20%20%2F%2F%20c%3A%20%7B%7D%20%2F%2Fdoes%20error%2C%20good%0D%0A%20%20%20%20%2F%2F%20c%3A%20%22%22%20%2F%2Fdoes%20error%2C%20good%0D%0A%20%20%20%20c%3A%20%5B%22Why%22%2C%20%22doesn't%22%2C%20%22this%22%2C%20%22error%22%5D%20%2F%2F%20%3C--%20should%20error%0D%0A%7D)

Also, is there a way to see the mapped type in its expanded form?

**Comment by andy-ms** [comment]
Probably has to do with the recursion in `Validated`.
```ts
type Validated<State extends object> = {
    [Member in keyof State]: Validated<State[Member]>;
}
const c: Validated<number[]> = ["why", "doesn't", "this", "error"];
```

**Comment by mhegazy** [comment]
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/12769

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
