### ISSUE TITLE
Misplaced error span for multiple var declarations in for..in

### ISSUE THREAD

**Issue by JsonFreeman** [Microsoft/TypeScript#156]
```TS
for (var a: number = 1, b: string = "" in X) { }
```

Error: Only a single variable declaration is allowed in a 'for...in' statement.

The error should be on the second declaration (b), but it's on the first (a).

**Comment by DickvdBrink** [comment]
Looks fixed to me.
https://github.com/Microsoft/TypeScript/blob/master/tests/baselines/reference/parserForInStatement7.errors.txt

**Comment by danquirk** [comment]
Yep, errors and their spans look great here. Thanks for the help.
