### ISSUE TITLE
Spread operator and es2015 module option causes missing import

### ISSUE THREAD

**Issue by Kebab** [Microsoft/TypeScript#15608]
**TypeScript Version:**  2.3.1 - 2.3.2

Start a fresh typescript project using tsc --init. Set **target** and **module** to **es2015**, set **jsx** to **react**. When **Text** is imported using a named import, the import for **Text** will not appear in the generated Javascript when a spread operator is used in the parent JSX element.

**Code**
```ts
import React, { Component } from 'react'
import { View, Text } from 'react-native'

class Example {
  things: any;

  render() {
    return (
      <View {...this.things}>
        <Text />
      </View>
    );
  }
}
```

**Expected behavior:**
Text should be included in the import in the generated Javascript

Output from tsc version 2.3.0
```ts
import React from 'react';
import { View, Text } from 'react-native';
class Example {
    render() {
        return (React.createElement(View, Object.assign({}, this.things),
            React.createElement(Text, null)));
    }
}
```

**Actual behavior:**
Output from affected versions

```ts
import React from 'react';
import { View } from 'react-native';
class Example {
    render() {
        return (React.createElement(View, Object.assign({}, this.things),
            React.createElement(Text, null)));
    }
}
```

This appears to be fixed in Version 2.4.0-dev.20170505, but is it possible for a fix to be released for 2.3? Using a spread operator to pass around props is very common behaviour. Thanks!

**Comment by yuit** [comment]
@Kebab we will release this fix to update of 2.3 as well!
