### ISSUE TITLE
Wrong order of multi-var initialization with mixed let/var lamdba usage in for loop

### ISSUE THREAD

**Issue by lmartorella** [Microsoft/TypeScript#15603]
**TypeScript Version:**  Latest (replicable with the Playground at https://www.typescriptlang.org/play)

**Code**
```ts
for (var i = 0; i < 10; i++) {
    var str = 'x', len = str.length;
    let lambda1 = (y) => { };
    let lambda2 = () => lambda1(len);
}
```
**Actual behavior:**
```js
var _loop_1 = function () {
    len = str.length, str = 'x';     **// EXC -> len assigned before str. Additional pars are always inverted**
    var lambda1 = function (y) { };
    var lambda2 = function () { return lambda1(len); };
};
var str, len;
for (var i = 0; i < 10; i++) {
    _loop_1();
}

```
Thank you!
 Luciano

**Comment by kitsonk** [comment]
It does appear to be an odd issue, as to why the assignment of `var`s is reordered and does cause a runtime issue.  [Simply breaking it up into separate statements](https://www.typescriptlang.org/play/#src=for%20(var%20i%20%3D%200%3B%20i%20%3C%2010%3B%20i%2B%2B)%20%7B%0A%09var%20str%20%3D%20'x'%0A%09var%20len%20%3D%20str.length%3B%0A%09let%20lambda1%20%3D%20(y)%20%3D%3E%20%7B%20%7D%3B%0A%09let%20lambda2%20%3D%20()%20%3D%3E%20lambda1(len)%3B%0A%7D%0A) corrects the issue.  It seems like some sort of AST array is not being replayed properly:

**input:**
```ts
for (var i = 0; i < 10; i++) {
	var str = 'x'
	var len = str.length;
	let lambda1 = (y) => { };
	let lambda2 = () => lambda1(len);
}
```

**output:**
```js
var _loop_1 = function () {
    str = 'x';
    len = str.length;
    var lambda1 = function (y) { };
    var lambda2 = function () { return lambda1(len); };
};
var str, len;
for (var i = 0; i < 10; i++) {
    _loop_1();
}
```

**Comment by lmartorella** [comment]
Oh yeah, we actually splitted the assignment to work-around the build as you said.

We are coping with big libraries written in JS with that code-style, and progressively migrating it to TS until we stumbled upon this strange issue.
It seems that using mixed var/let inside the for loop triggers the new loop syntax (to fix the lambda capturing scoping rule I assume), and then the var are initialized in the reversed order.

Thanks.

**Comment by mhegazy** [comment]
@rbuckton can you take a look.

**Comment by mhegazy** [comment]
@lmartorella the fix should be in `typescript@next` tomorrow. give it a try and let us know if you are still running into issues.

**Comment by lmartorella** [comment]
Thank you!
