### ISSUE TITLE
ReferenceError: __generator is not defined

### ISSUE THREAD

**Issue by a1029563229** [Microsoft/TypeScript#15602]
**TypeScript Version:**  2.1.0 / nightly (2.2.0-dev.201xxxxx)

**Code**
<pre>
export class allPipePipe implements PipeTransform {
  constructor (
      @Inject('dynamicFormService') private formService,
  ) {}

  async transform(val:string) {
    const value = val.split('/')[0];
    const type = val.split('/')[1];
    const number = val.split('/')[2] ? val.split('/')[2] : '';
    switch (type) {
      default:
        let name = await this.getTypeName(value,number);
        return name;
    }
  }

  getTypeName (value,number) {
    return new Promise((resolve,reject) => {
      this.formService.getDictionary(10).subscribe((data:any) => {
          let val:any = data.pageData.filter(item => item.value == value)[0];
          resolve(val.name);
      });
    })
  }
}
</pre>
```ts
// A *self-contained* demonstration of the problem follows...
thanks
```

**Expected behavior:**
return name = await promise
**Actual behavior:**
__generator is not defined

**Comment by kitsonk** [comment]
The error you mention seems like a runtime error.  If that is correct, then it is likely more of an issue with your TypeScript configuration or how the code is being run at runtime.

You should provide accurate version information, your TypeScript configuration, and how the code is being run at runtime in order for anyone to provide help.

**Comment by a1029563229** [comment]
I've solved this problem with the webpack configuration problem
Finally, I solved my problem in a non-async method

**Comment by mt-webdev** [comment]
and HOW did you solve it? @a1029563229
