### ISSUE TITLE
[JS/JSX] Children prop is not recognized properly

### ISSUE THREAD

**Issue by methyl** [Microsoft/TypeScript#15605]
**TypeScript Version:**  2.3.1

**Code**

```ts
import React from "react";

const Foo = ({ children }) =>
  <div>
    {children}
  </div>

const Bar = () =>
  <Foo>Test</Foo>

```

**Expected behavior:**
Children prop is recognized, type check passes.

**Actual behavior:**

Error occurs:
```
message: 'Type '{}' is not assignable to type 'IntrinsicAttributes & { children: any; }'.
  Type '{}' is not assignable to type '{ children: any; }'.
    Property 'children' is missing in type '{}'.'
at: '9,3'
source: 'ts'
```

**Comment by methyl** [comment]
The same happens for typescript code:
```ts
import React from "react";

const Foo: React.StatelessComponent<{ children: Element }> = ({ children }) =>
  <div>
    {children}
  </div>

const Bar:React.StatelessComponent <{}> = () =>
  <Foo>Test</Foo>

```

**Comment by methyl** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/6471

**Comment by mhegazy** [comment]
This is actually a duplicate of https://github.com/Microsoft/TypeScript/issues/15583. Please update your `@types/react`. see https://github.com/Microsoft/TypeScript/issues/15583#issuecomment-299309427 for more info.
