### ISSUE TITLE
Calling method in constructor in current class gives runtime error (is not a function)

### ISSUE THREAD

**Issue by 304NotModified** [Microsoft/TypeScript#15606]
Bug: when calling a method in the constructor, Typescript won't complain but gives it gives runtime error

**TypeScript Version:**  2.1, current playground (dunno which version)

**Code**

```ts
class MyArray<T> extends Array<T> {
    constructor(items: T[]) {
        super();
        // runtime error 
        this.addRange(items);
    }


    public addRange(items: T[]) {
        if (items && items.length) {
            for (const item of items) {
                this.push(item);
            }
        }
    }
}

var items: string[] = [];
items.push("a");
items.push("b");
var myArray = new MyArray(items)
```

**Expected behavior:**
works at runtime OR compile error

**Actual behavior:**
runtime error:

```
Uncaught TypeError: _this.addRange is not a function
    at new MyArray (<anonymous>:16:15)
    at <anonymous>:32:15
    at HTMLButtonElement.excuteButton.onclick (https://www.typescriptlang.org/play/playground.js:242)
```
See [playground](https://www.typescriptlang.org/play/index.html#src=class%20MyArray%3CT%3E%20extends%20Array%3CT%3E%20%7B%0D%0A%20%20%20%20constructor(items%3A%20T%5B%5D)%20%7B%0D%0A%20%20%20%20%20%20%20%20super()%3B%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20runtime%20error%20%0D%0A%20%20%20%20%20%20%20%20this.addRange(items)%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%0D%0A%20%20%20%20public%20addRange(items%3A%20T%5B%5D)%20%7B%0D%0A%20%20%20%20%20%20%20%20if%20(items%20%26%26%20items.length)%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20for%20(const%20item%20of%20items)%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20this.push(item)%3B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Avar%20items%3A%20string%5B%5D%20%3D%20%5B%5D%3B%0D%0Aitems.push(%22a%22)%3B%0D%0Aitems.push(%22b%22)%3B%0D%0Avar%20myArray%20%3D%20new%20MyArray(items))

**Comment by DanielRosenwasser** [comment]
Same issue as #15202. This is a limitation of the way that built-ins like `Array`, `Error`, etc. function. If your environment supports `Object.setPrototypeOf`, you can get around this with the following:

```ts
class MyArray<T> extends Array<T> {
    constructor(items: T[]) {
        super();
        Object.setPrototypeOf(this, new.target.prototype);

        // Works!
        this.addRange(items);
    }


    public addRange(items: T[]) {
        if (items && items.length) {
            for (const item of items) {
                this.push(item);
            }
        }
    }
}
```

See https://github.com/Microsoft/TypeScript-wiki/blob/master/Breaking-Changes.md#extending-built-ins-like-error-array-and-map-may-no-longer-work for more details.

**Comment by 304NotModified** [comment]
thanks, I need typescript 2.3 for it? Is the rule (if no support for `Object.setPrototypeOf`) - never extends build-in types?

PS: 
can confirm it works in the [playground](https://www.typescriptlang.org/play/index.html#src=class%20MyArray%3CT%3E%20extends%20Array%3CT%3E%20%7B%0D%0A%20%20%20%20constructor(items%3A%20T%5B%5D)%20%7B%0D%0A%20%20%20%20%20%20%20%20super()%3B%0D%0A%20%20%20%20%20%20%20%20%20Object.setPrototypeOf(this%2C%20new.target.prototype)%3B%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20runtime%20error%20%0D%0A%20%20%20%20%20%20%20%20this.addRange(items)%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%0D%0A%20%20%20%20public%20addRange(items%3A%20T%5B%5D)%20%7B%0D%0A%20%20%20%20%20%20%20%20if%20(items%20%26%26%20items.length)%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20for%20(const%20item%20of%20items)%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20this.push(item)%3B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Avar%20items%3A%20string%5B%5D%20%3D%20%5B%5D%3B%0D%0Aitems.push(%22a%22)%3B%0D%0Aitems.push(%22b%22)%3B%0D%0Avar%20myArray%20%3D%20new%20MyArray(items)%0D%0Aconsole.log(myArray)) 

thanks!
