### ISSUE TITLE
Recursive generic constraint

### ISSUE THREAD

**Issue by NN---** [Microsoft/TypeScript#1561]
Didn't find this issue.
Will TypeScript allow recursive generic constraints known as CRTP: 

```typescript
interface B<T extends B> {}
```

There is a workaround but it is not nice.

```typescript
interface A {
	f() : void;
}

interface B<T extends A> extends A {
}

class C implements B<C> {
	f() : void {}
}
```

**Comment by danquirk** [comment]
Recursive types and structural types like this are not a great mix. Consider your definition of B with some actual members (or else its meaningless):

```ts
interface B<T extends B> {
    foo: string;
}
```

Now imagine the steps the compiler has to go through to validate whether the T in a particular B<T> instantiation satisfies the constraint ```T extends B```. It has to inspect the shape of B to structurally check T against, which causes another elaboration of B and asking again whether this other ```T extends B``` is satisfied, and so on. Eventually the compiler ends up having to just short circuit the comparison.

**Comment by jbondc** [comment]
Seems doable, I'll keep it as a note for #3496
