### ISSUE TITLE
Visual Studio 2015 TypeScript intellisense not resolving external types

### ISSUE THREAD

**Issue by elliot-j** [Microsoft/TypeScript#15612]
I originally asked this question on SO in March, but have not been able to get a response to the issue.  I am in the process of adding TypeScript support to an existing ASP.NET MVC 5 project, with gulp powering the TypeScript build instead of MSBuild. For the time being we will not be using an external module loader and instead be using namespaced typescript files. I've installed v2.2.1 of the TypeScript tools for Visual Studio 2015, and I've added the following to the **csproj** file so MSBuild does not attempt to build the TypeScript files:

`<TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>`

Everything builds fine and I don't get any errors reported from the Task Runner Explorer or gulp-typescript. However, Visual Stuido's intellisense is not able to resolve third-party type references that have been specified through the `typeRoots` setting in `tsconfig.json` unless I add a `/// <reference>` comment to files. Additionally Intellisense does not resolve types for classes or interfaces declared in other TS files inside the project unless the file is open in Visual Studio or I use `///<reference>`

If I create a new TypeScript Project in visual studio using the same `tsconfig.json`, `package.json` and `gulpfile.js` files, Visual Studio intellisense resolves the types just fine and I do not need to use `/// <reference>` comments. Is there some config setting in Visual Studio I've overlooked in the MVC project to have Intellisense work without `/// <reference>` comments? 

**tsconfig.json**

    {
        "compilerOptions": {
            "target": "es5",
            "noImplicitAny": true,
            "noImplicitReturns": true,
            "removeComments": true,
            "alwaysStrict": true,
            "declaration": true,        
            "noEmitOnError": true
        },    
        "typeRoots": [
            "./node_modules/@types/"        
        ],
        "exclude": [
            "node_modules"
        ]
    }

**package.json**

    {
      "version": "1.0.0",
      "private": true,
      "devDependencies": {
        "@types/angular": "^1.6.4",
        "@types/jasmine": "^2.5.46",
        "@types/jquery": "^2.0.40",
        "@types/underscore": "^1.7.36",
        "gulp": "^3.9.1",
        "gulp-typescript": "^3.1.4", 
        "merge2": "^1.0.3",
        "typescript": "2.2.1"
      },
      "-vs-binding": {
        "ProjectOpened": [
          "install"
        ]
      }
    }

**folder structure**

    |- package.json
    |- tsconfig.json
    |- gulpfile.js
    |--/Content
       |--/Scripts
          |--/JavaScript
          |--/TypeScript
	         |--app.ts
		        |--/Components
			       |--ExampleComponent.ts

**ExampleComponent.ts**

    namespace Vue.Examples {
        export class ExampleComponentController {
            static inject: Array<string> = ["$scope", "stSharedResourcesService"];

            //Intellisense does not find the  ng or Vue.Common namespaces without ///<reference> here
            constructor($scope: ng.IScope, private stSharedResourcesService: Vue.Common.IStSharedResourcesService) { }
        };
        commonModule.component("exampleComponent", {
            bindings: {},
            controller: ExampleComponentController
        });
    }

**app.ts**

    //This file declares references to existing JS variables so we can get proper
    //TS intellisense.
    declare var commonModule: ng.IModule;
    declare var adminModule: ng.IModule;
    declare var searchModule: ng.IModule;

**Platform config**

Visual Studio 2015 Update 3
TypeScript Tools v2.2.1
Windows 7 Enterprise
NodeJS v 6.10.2
NPM v3.10.10

**Comment by billti** [comment]
This is the confusing part:

> If I create a new TypeScript Project in visual studio using the same tsconfig.json, package.json and gulpfile.js files, Visual Studio intellisense resolves the types just fine and I do not need to use /// <reference> comments.

Is there something else in your project file that could be interfering? If you go into Tools / Options and find the Project settings for TypeScript, and enable the "Virtual Project when Solution is loaded", you should get a structure in Solution Explorer that shows the projects TypeScript has built up. Does anything here not match expectations? (i.e. its creating a project you weren't aware of, etc.)

**Comment by elliot-j** [comment]
In the project I am having issues, the Virtual TS project does not have the folder structure showing all the TypeScript files (missing the Content folder) but the TypeScript project for I created includes this directory. Below is a screenshot showing the structures from Solution Explorer


![typescirpt-intellisense-github-issue](https://cloud.githubusercontent.com/assets/17621302/25765494/3590320a-31a2-11e7-8a18-aabf99951c2f.png)

**Comment by billti** [comment]
That is weird. You've not done anything unusual like linked to the .ts files into the VS project instead of actually having them on disk?

What might be useful: If you open the developer command prompt and go to the folder containing the project, does the `tsc -p ./` command-line compile the project OK? (there's also a `--listFiles` flag you can add to see what is being included).

**Comment by elliot-j** [comment]
Im not sure what you mean by linking to the .ts files so I assume I haven't done that. All TS files are on my local disk.

running `tsc --listFiles -p ./` through dev command prompt compiles with no errors and I do not see any files missing in the file list. I do see both the source files and the referenced `d.ts` files from node_modules. I also double checked the version of TSC to see if it was  matching that in my gulp build (it is).

**Comment by elliot-j** [comment]
@billti is there any additional info I can provide to aid in troubleshooting this issue?

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Comment by corymickelson** [comment]
Having the same issue. Project compiles without issue from command prompt, but in visual studio, import modules can't be resolved (at least as far as intellisense is concerned). Webstorm, vscode, vim (with ts plugin) also work as expected. I've tried loading in vs as a web site, a folder, virtual project, each approach produces the same results. I dont believe there is anything unique about my tsconfig file, but just in case here it is:
``` json {
  "compilerOptions": {
    "outDir": "build/dist",
    "module": "es6",
    "target": "es5",
    "lib": ["es6", "dom", "es2016.array.include"],
    "sourceMap": true,
    "allowJs": true,
    "jsx": "react",
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "rootDir": "src",
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": true
  },
  "typeRoots": [
    "./node_modules/@types"
  ],
  "exclude": [
    "node_modules",
    "build",
    "scripts",
    "acceptance-tests",
    "webpack",
    "jest",
    "src/setupTests.ts"
  ]
}
```
