### ISSUE TITLE
For JavaScript Projects, Mark Unreachable Code as a Warning Instead of an Error

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#15617]
From https://github.com/Microsoft/vscode/issues/26016

**Feature Request**
Using the TypeScript 2.3 `checkJs` feature, we've seen a few requests in VSCode to downgrade the `unreachable code` error's severity from error to warning

I'm not sure if we should downgrade this error specifically, but I do think we should allow users to configure this. I believe that #6802 and #13408 track this

**Comment by mjbvz** [comment]
There are currently no workarounds to mark this error as a warning but you can suppress the error entirely using `// @ts-ignore`:

```js
function foo(){
    return 1;
    // @ts-ignore
    return 2;
    return 3;
}
```

or for an entire project by creating a [`jsconfig.json`](http://www.typescriptlang.org/docs/handbook/tsconfig-json.html) at the root of your workspace that sets `allowUnreachableCode`:

```json
{
    "compilerOptions": {
        "checkJs": true,
        "allowUnreachableCode": true
    },
    "exclude": [
        "node_modules"
    ]
}
```

**Comment by mhegazy** [comment]
The overarching issue of treeing specific errors as warnings is tracked by #13408. For this unreachable code specifically, @mjbvz's [comment](https://github.com/Microsoft/TypeScript/issues/15617#issuecomment-299569757) provide remedies.

**Comment by mhegazy** [comment]
closing in favor of #13408.
