### ISSUE TITLE
delete operator and strict null checks

### ISSUE THREAD

**Issue by jmlopez-rod** [Microsoft/TypeScript#15629]
**TypeScript Version:**  2.3 (the one in the playground)

**Code**

```ts
interface IName {
    name?: string;
}

class A {
    prop: IName;

    constructor(param: IName) {
        this.prop = param;
    }

    printProp() {
        if (this.prop) {
            // this.prop = undefined;  // TS will catch this error
            delete this.prop;  // Oh no, now we'll have a runtime error
            console.log(this.prop.name);
        }
    }
}

const a = new A({ name: 'a' });
a.printProp();
```
Or click [here](https://www.typescriptlang.org/play/index.html#src=interface%20IName%20%7B%0D%0A%20%20%20%20name%3F%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Aclass%20A%20%7B%0D%0A%20%20%20%20prop%3A%20IName%3B%0D%0A%0D%0A%20%20%20%20constructor(param%3A%20IName)%20%7B%0D%0A%20%20%20%20%20%20%20%20this.prop%20%3D%20param%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20printProp()%20%7B%0D%0A%20%20%20%20%20%20%20%20if%20(this.prop)%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20this.prop%20%3D%20undefined%3B%20%20%2F%2F%20TS%20will%20catch%20this%20error%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20delete%20this.prop%3B%20%20%2F%2F%20Oh%20no%2C%20now%20we'll%20have%20a%20runtime%20error%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20console.log(this.prop.name)%3B%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aconst%20a%20%3D%20new%20A(%7B%20name%3A%20'a'%20%7D)%3B%0D%0Aa.printProp()%3B%0D%0A) to see it in the playground.

**Expected behavior:**

Should warn us about using the delete operator since we told typescript that `prop` is an `IName`.

**Actual behavior:**

Currently as the code stands typescript is not able to warn us of the oncoming failure. I have left the line `this.prop = undefined` and typescript will complain about it. Using the `delete` operator will do the same as setting as undefined but there is no warning.

Make sure to use the `strictNullChecks` option when running the code.

**Comment by mhegazy** [comment]
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/13783

**Comment by jmlopez-rod** [comment]
That seems to be the case.
