### ISSUE TITLE
Improve 'insertAdjancentElement' type definition

### ISSUE THREAD

**Issue by noobiept** [Microsoft/TypeScript#15620]
Right now, the 'position' parameter of the ['Element.insertAdjacentElement()'](https://github.com/Microsoft/TypeScript/blob/master/src/lib/dom.generated.d.ts#L3644) function has the basic type 'string', but if we look at the [documentation](https://developer.mozilla.org/en-US/docs/Web/API/Element/insertAdjacentElement), we see that only a few selected string values are actually valid.

I propose we add a new type for this parameter, that is a string literal type, with all the valid values.

So for example:

`type InsertPosition = 'beforebegin' | 'afterbegin' | 'beforeend' | 'afterend';`
`insertAdjacentElement(position: InsertPosition, insertedElement: Element): Element | null;`

This would also be used for the other insertion functions that share the same style of parameter.
    
- https://developer.mozilla.org/en-US/docs/Web/API/Element/insertAdjacentHTML
- https://developer.mozilla.org/en-US/docs/Web/API/Element/insertAdjacentElement
- https://developer.mozilla.org/en-US/docs/Web/API/Element/insertAdjacentText

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by noobiept** [comment]
Alright, I'll look into it.
