### ISSUE TITLE
JSDoc @typedef is removed when it precedes type declaration

### ISSUE THREAD

**Issue by kimamula** [Microsoft/TypeScript#15637]
**TypeScript Version:**  2.3.2

**Code**

```ts
/**
 * This one is not emitted
 * @typedef {(number|string)} NumberOrString1
 */
type NumberOrString1 = string | number;

/**
 * while this one is
 * @typedef {(number|string)} NumberOrString2
 */
```

**Expected behavior:**

Both of the two `@typedef` appear in the emitted JavaScript code.

```ts
/**
 * This one is not emitted
 * @typedef {(number|string)} NumberOrString1
 */
/**
 * while this one is
 * @typedef {(number|string)} NumberOrString2
 */
```

**Actual behavior:**

Only the second one appears in the emitted JavaScript code.

```ts
/**
 * while this one is
 * @typedef {(number|string)} NumberOrString2
 */
```

It is likely this behavior is due to https://github.com/Microsoft/TypeScript/blob/2b61d18996c182b7de8ef2a9367210a70e3d4031/src/compiler/comments.ts#L239-L241, in which comments preceding a node are emitted only if the node itself is emitted.

**Comment by mhegazy** [comment]
Comments are associated with declarations and/or statements. if the associated declaration/statement is not emitted, the comment is not. in this case, `type` alias declaration, as well as `interfaces` do not get emitted, and so are there comments.

**Comment by kimamula** [comment]
@typedef is a standalone JSDoc, which has a meaning even if it's not associated to any statement in the emitted JavaScript.
As I think it's natural to add @typedef immediately before the corresponding type declaration, I hope TypeScript not to remove @typedef preceding type declarations.

**Comment by mhegazy** [comment]
the comment content is not checked. the comment is either emitted or not. and they are only emitted if they are associated with a statement or declaration that gets emitted. otherwise, it will be just a random series of comments that do not make much sense.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
