### ISSUE TITLE
Kebab-case intellisense

### ISSUE THREAD

**Issue by LeviticusMB** [Microsoft/TypeScript#15635]
**TypeScript Version:**  2.3.2 (VSCode embedded)

**Code**

```ts
interface Foo {
    'id': number;
    'snake_case': number;
    'kebab-case': number;
}

let foo: Foo;

foo.|  <-- Will get suggestions for 'id' and 'snake_case' here

foo[|] <-- Will no not get suggestions for any property here

foo['|'] <-- Will no not get suggestions for any property here

```

**Expected behavior:**
That the `kebab-case` property is suggested somehow

**Actual behavior:**
I always have to type `kebab-case` manually.

**Comment by hediet** [comment]
I cannot reproduce that in the typescript playground:
![image](https://cloud.githubusercontent.com/assets/2931520/25780407/d728ff94-3327-11e7-8d19-088f25b3e2da.png)

Neither in VS Code with typescript 2.3.2:
![image](https://cloud.githubusercontent.com/assets/2931520/25780431/57ab7e80-3328-11e7-99e9-ebe3bde80113.png)

**Comment by LeviticusMB** [comment]
Eh, OK... That's really odd?

This is the Playground:

![skarmavbild 2017-05-07 kl 15 25 06](https://cloud.githubusercontent.com/assets/1094822/25781763/f4b3e8a6-333d-11e7-981d-0341ea5dfb3c.png)

I do, however get suggestions if I type a letter in the Playground:

![skarmavbild 2017-05-07 kl 15 25 46](https://cloud.githubusercontent.com/assets/1094822/25781768/18059e58-333e-11e7-8a9b-7affd6fe7b6a.png)

But in VS Code, nothing (this is the new 1.12 standard release for macOS, all extensions disabled, all custom config in *config.json* commented out):

![skarmavbild 2017-05-07 kl 15 56 38](https://cloud.githubusercontent.com/assets/1094822/25781780/3ddcb3aa-333e-11e7-8b40-1b0b0a652014.png)

![skarmavbild 2017-05-07 kl 15 56 47](https://cloud.githubusercontent.com/assets/1094822/25781783/459b22ca-333e-11e7-9f11-7f4aae3c18c1.png)

![skarmavbild 2017-05-07 kl 15 56 54](https://cloud.githubusercontent.com/assets/1094822/25781785/48d16558-333e-11e7-8c80-4028287b6228.png)

**Comment by LeviticusMB** [comment]
Addendum: In Playground *and* VS Code, if I type a dot insided the index string, I get do completions (that are wrong since the property will begin with a dot):

![skarmavbild 2017-05-07 kl 16 10 52](https://cloud.githubusercontent.com/assets/1094822/25781901/0bc3988c-3340-11e7-86a1-1a7b6cf0d109.png)

![skarmavbild 2017-05-07 kl 16 13 10](https://cloud.githubusercontent.com/assets/1094822/25781904/15ed68ec-3340-11e7-937c-8a787a9704fe.png)

**Comment by LeviticusMB** [comment]
Alright, if I invoke "Trigger Suggest" manually in VS Code, all is fine. So I guess the bug is just that the editor does not automatically trigger suggestions for indexed properties. Plus that weird dot thing.

Thanks for the help. Closing this.
