### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by htwx** [Microsoft/TypeScript#15636]
**TypeScript Version:**  2.2.1 / nightly (2.2.0-dev.201xxxxx)

**Code**
function  name(参数:string,数字:number){
   return 参数+数字.toString()
}

```ts
// A *self-contained* demonstration of the problem follows...
参数名称不支持 utf8 字符
```

**Expected behavior:**

**Actual behavior:**

**Comment by DanielRosenwasser** [comment]
I'm not sure what you're asking, but I'll guess.

Every major browser's JavaScript runtime includes a declaration called `name`. That's probably why you're getting an error.
