### ISSUE TITLE
Cannot add or modify JSDoc with custom transformers

### ISSUE THREAD

**Issue by kimamula** [microsoft/TypeScript#15639]
**TypeScript Version:**  2.3.2

It is likely that TypeScript basically emits comments as they were in the original TypeScript code and any mutation of `ts.JSDoc` objects with custom transformers is ignored.

Though it is possible to add comments by `ts.addSyntheticLeadingComment()` or `ts.addSyntheticTrailingComment()`, they cannot be used to add JSDoc style comments.

Is it possible to enable adding or modifying JSDoc with custom transformers?
This feature would be helpful for solving the problem like #10, for example.

**Comment by RyanCavanaugh** [comment]
Will track at #17146
