### ISSUE TITLE
Check JavaScript: require flagged as error in simple node project

### ISSUE THREAD

**Issue by egamma** [Microsoft/TypeScript#15632]
Please see the screenshot below. Since this workspace has a package.json I would have expected that this is recognized as commonJS project:

![image](https://cloud.githubusercontent.com/assets/172399/25775893/3ff5014e-32b0-11e7-8667-710444568128.png)

When adding a jsconfig.json with `module: commonJs` then `require` is no longer marked as an error.

```json
{
    "compilerOptions": {
        "module": "commonjs",
        "checkJs": true
    }
}
```

// CC @mjbvz

**Comment by mhegazy** [comment]
We do not categorize projects based on package.json. ATA just looks for module imports, and should have seen `util` and loaded `@types/node`, which brings a declaration of require. 

what is happening here is we have not reset the errors for the file after ATA downloaded the `@types/node`. if you make an edit in the file the error should go away.

**Comment by ccprog** [comment]
Just to aid users that get confused like me: adding a `"exclude": [ "node_modules" ]` to jsconfig.json will prevent`@types/node` from loading.

The doc page is a bit misleading here, as it says
> If you do not have a `jsconfig.json` in your workspace, VS Code will by default exclude the `node_modules` folder.

But if you have it, `node_modules` is _still_ excluded by default.

**Comment by andy-ms** [comment]
It's currently possible for us to add new errors at any time. But the problem is that if we start doing a new error check the moment a typing is installed, this could take an arbitrarily long time, and wouldn't be cancelable (since the editor didn't ask for it, so there would be no cancellation token).
It would be nice if we could send a new message to the editor, telling it that the language service has some updated information and would like to redo some checks. Then the editor could send a cancelable request for new errors.

**Comment by andy-ms** [comment]
I can reproduce this problem in a TypeScript project. If I just have `import * as fs from "fs";` in a file, then `npm install @types/node`, that file's diagnostics are not updated -- even if I type in it. I also don't see anything happen in the log after installing the types, although that should have been covered by the watcher.

**Comment by andy-ms** [comment]
Thanks to @sheetalkamat for pointing out that this is a limitation of how we currently do watch:
[fs.watch() resolves the path to an inode and watches the inode. If the watched path is deleted and recreated, it is assigned a new inode](https://nodejs.org/api/fs.html#fs_fs_watch_filename_options_listener).
