### ISSUE TITLE
Invalid union type compatibility inference

### ISSUE THREAD

**Issue by lagunoff** [Microsoft/TypeScript#15633]
Typechecker doesn't take into account that union types can occur in negative position inside generic interfaces

**TypeScript Version:**  TypeScript 2.3 (from playground)

**Code**

```ts

interface Contravariant<a> {
  run: (a: a) => string,
}

type U = 'One' | 'Two' | 'Three'

declare const one: 'One';
const thatsOk: U = one;

declare const contraOne: Contravariant<'One'>
const shouldNotTypeCheck: Contravariant<U> = contraOne;

```

**Expected behavior:**
type error
**Actual behavior:**
no type errors

**Comment by hediet** [comment]
See [here](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Type%20Compatibility.md#function-parameter-bivariance) and #10717.
In your case, `'One'` is assignable to `U`, so it typechecks.

**Comment by lagunoff** [comment]
Thanks, turns out it's a well-known problem and applies not only to union types
