### ISSUE TITLE
[2339] Property ... does not exist on type 'typeof (Anonymous class)'

### ISSUE THREAD

**Issue by jhpratt** [Microsoft/TypeScript#15646]
**TypeScript Version:**  2.2.1 stable

**Code**

```ts
class skrolr {
    private static _Array = class extends Array {
        from( obj: HTMLCollection ) {
            let arr = [];
            for( let i=0, len=obj.length; i<len; i++ ) {
                arr[i] = obj[i];
            }
        }
    }
    
    // in another class
    skrolr._Array.from( [HTMLCollection object] );
}
```

**Expected behavior:**
Successful transpiling to ES3

**Actual behavior:**
Error 2339

Basically just trying to have a simplified polyfill for Array.from(), but I don't want this to be global, so I'm doing it in a subclass. It works as expected in ES6, and the subclass transpiles correctly to ES3, it's just the parser for some reason isn't seeing it.

**Comment by hediet** [comment]
You are not instantiating your class `_Array`, so either you want to make `from` static or put it in an object rather than a class:
```
... 
private static _array = { from: function() {...}} ;
... 
```

**Comment by mhegazy** [comment]
` skrolr._Array` is a class, whose instances have a function called `from`. 

so either defined `from` as `static`, or call `(new skrolr._Array()).from`

**Comment by jhpratt** [comment]
Ok, yes, that was the issue. However, why does it transpile to ES6 but not ES3 without declaring `static`?

**Comment by mhegazy** [comment]
not sure what you mean by `transpile`..

the generated code is the same semantically, it just happens that on ES6 engine, your class has a static `from` method that it got from the base `Array`, on an ES3 engine, that is not the same..

in both cases, your new function goes not get to execute.
