### ISSUE TITLE
extension authoring:need some api

### ISSUE THREAD

**Issue by Midqiu** [Microsoft/TypeScript#15649]
I'd like to witre an extension : "when rename a file ,auto repalce the reference in other files" for ts project and nodejs project.

I looked for the doc but can't find the rename event or move file event or delete file event (
Maybe it's my carelessness ). So , can support the apis?

and by the way ,

find string api (the doc show it has the find file api)

replace string api

is not exist ,and it's useful too. eg: the TODO Parser Extension .the exist TODO Parser Extension is not good and fast.

**Comment by mhegazy** [comment]
The server does not have such events, you want to get that from the editor.
