### ISSUE TITLE
Invalid intellisense when typing a dot in index key

### ISSUE THREAD

**Issue by LeviticusMB** [microsoft/TypeScript#15642]
Found this as part of issue #15635.

**TypeScript Version:**  2.3 (current Playground)

**Code**

```ts
window['.|'] // <-- Triggers suggestions (the | is the cursor)

```

**Expected behavior:**
Only properties that contain a dot are shown.

**Actual behavior:**
All properties are shown as suggestions. Select `alert`, for instance, and the result will be 

```ts
window['.alert']
```

which is not a valid `window` member.

**Comment by RyanCavanaugh** [comment]
This gets a correct replacement span now
