### ISSUE TITLE
Shorthand initializer with object properties

### ISSUE THREAD

**Issue by NN---** [Microsoft/TypeScript#15644]
Shorthand initializer with kind of 'nameof' for the expression:
```ts
var a = {x: 1, y: 2, z: 3};
// Shorthand form
var b = {a.x, a.y};
// Long form
var b = {x: a.x, y: a.y};
```

Are there plans for this?
Couldn't find similar suggestion.

**Comment by mhegazy** [comment]
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/8932

**Comment by NN---** [comment]
Seems so.
Do you know if there is a proposal for ES already?
Thanks.

**Comment by mhegazy** [comment]
> Do you know if there is a proposal for ES already?

not that i am aware of.
