### ISSUE TITLE
checkJs too strict about module.exports assignment

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#15647]
I was trying to run with `// @ts-check` on a webpack config file. Unfortunately, it choked on the following simplified repro:

```js
// @ts-check

module.exports = {
    a: 100,
    b: 200,
}

module.exports.devtool = true;
```

I get

```
severity: 'Error'
message: 'An export assignment cannot be used in a module with other exported elements.'
at: '3,1'
source: 'js'
```

**Comment by mohsen1** [comment]
This is a blocker for https://github.com/webpack/webpack/pull/6862

@sandersn  @DanielRosenwasser 
Thanks!

**Comment by sandersn** [comment]
https://github.com/Microsoft/TypeScript/pull/23228 Should fix this. Can you try typescript@next?

**Comment by mohsen1** [comment]
@sandersn Your changes resolved this! Thank you!

The only thing that's still erroring is this:

```ts
exports = module.exports = webpack;
```

**Comment by mhegazy** [comment]
@mohsen1 https://github.com/Microsoft/TypeScript/pull/23319 should fix this. give it a try in tommrow's build.
