### ISSUE TITLE
Default argument function causing Supplied parameters do not match any signature of call target

### ISSUE THREAD

**Issue by Jamesernator** [Microsoft/TypeScript#15650]
**TypeScript Version:**  2.3.2

**Code**

```ts
function map<T, R>(
    iterable: AsyncIterable<T> | Iterable<T>,
    func?: (item: T, index: number) => R
): AsyncIterable<R>

async function* map(iterable, func=x => x) {
    let idx = 0
    for await (const item of iterable) {
        yield func(item, idx) // Supplied parameters do not match any signature of call target.
        idx += 1
    }
}
```

**What Happened:**

Basically TypeScript complains about "Supplied parameters do not match any signature of call target" at the call of `func`, this only occurs with the default parameter present, without it it works as expected.

**What I'd expect:**

Now according to the handbook under the section "Optional parameters in callbacks" it mentions that callbacks can be passed excess parameters, and this does work without using default arguments:

```ts
map([1,2,3,4], x => x)
```

Essentially I'd expect anything that is treated as a default argument to undergo the same type inference as something passed into the function directly, it appears that isn't the case currently.

**Comment by RyanCavanaugh** [comment]
I'm not sure which specific behavior you consider a bug.

If you don't have the default, then the type of `func` is `any`, so anything goes.

If you do have the default, it's of type `(x: any) => any`, which you can only *directly* invoke with one parameter. It'd be silly to allow `Math.abs(x, y)`, of course, because that's clearly wrong.

**Comment by Jamesernator** [comment]
But `Math.abs` is perfectly permissible to pass to my `map` function, it takes a `T` and maps it onto an `R` it doesn't matter that the second argument is ignored, and further TypeScript does not even complain about this:

```ts
// This is valid by the definition of map!
map([1,2,3,4], Math.abs)
```

Or this:

```ts
map([1,2,3,4], x => x)
```

Essentially my question is why is the `x => x` typing inferred in that case, but not this case:

```ts
map([1,2,3,4] /* 
   It seems obvious to me that the default
   argument here should be inferred to be (x: number) => number
   as the definition can simply be inserted in place of no argument,
   and because it's dynamic that's effectively exactly how 
*/)
```

Even though the latter is obviously equivalent to the former as the function is completely identical to the default argument?

What'd make sense to me is if default parameters were a bit like a type guard, e.g.

```ts
// Ideally I'd be able to define my function
// without y?: because the type of y isn't undefined | number
// y should always be guaranteed to be a number, it's the parameter
// passed in that can be undefined | number NOT y itself!
function add(x: number, y: number)

/* This effectively guards against y being undefined */
function add(x, y=2) {
    // y can never be undefined so the type of y is actually
    // just number, not undefined | number!
    return x + y
}

/* x can have type undefined or number that's fine, but that doesn't
   mean y can
*/
const x?: number = 10
add(10, x)
```

Also this satisfies the type and behaves exactly the same and TypeScript doesn't complain.

```ts
function map<T, R>(
    iterable: AsyncIterable<T> | Iterable<T>,
    func?: (item: T, index: number) => R
): AsyncIterable<R>

async function* map(iterable, func) {
    /* This is what default parameters already do! So this shouldn't
       somehow be different to default parameters.
    */
    if (func === undefined) {
        func = x => x
    }
    let idx = 0
    for await (const item of iterable) {
        yield func(item, idx) // Supplied parameters do not match any signature of call target.
        idx += 1
    }
}
```

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
