### ISSUE TITLE
getDefinitionAtPosition() on import alias returns incorrect containerName

### ISSUE THREAD

**Issue by felixfbecker** [microsoft/TypeScript#15658]
**TypeScript Version:**  2.3.2

**Code**

```ts
import * as util from 'gulp-util';

util.colors; // call getDefinitionAtPosition() on `color`
```
[`node_modules/@types/gulp-util/index.d.ts`](https://sourcegraph.com/github.com/DefinitelyTyped/DefinitelyTyped/-/blob/types/gulp-util/index.d.ts#L22)
```ts
import chalk = require('chalk');
export var colors: typeof chalk;
```

**Expected behavior:**
Returns empty `containerName` since the export is not contained in any namespace:
```js
{ containerKind: undefined
  containerName: undefined
  fileName: "/node_modules/@types/gulp-util/index.d.ts"
  kind: "var"
  name: "colors"
  textSpan: {start: 610, length: 6} }
```

**Actual behavior:**
Returns `containerName: "util"` which is the import alias at the reference location, not the definition.
```js
{ containerKind: undefined
  containerName: "util"
  fileName: "/node_modules/@types/gulp-util/index.d.ts"
  kind: "var"
  name: "colors"
  textSpan: {start: 610, length: 6} }
```

The `NavigateToItem` produced for the definition has a correct `containerName`, which prevents matching the two against each other:
```js
{
  "name": "colors",
  "kind": "var",
  "kindModifiers": "export,declare",
  "matchKind": "exact",
  "isCaseSensitive": true,
  "fileName": "/types/gulp-util/index.d.ts",
  "textSpan": {
    "start": 590,
    "length": 20
  },
  "containerName": "",
  "containerKind": ""
}
```

**Comment by RyanCavanaugh** [comment]
@felixfbecker what an amazing two years it's been. Do you know if this still repros?
