### ISSUE TITLE
Proposal: new mapped type - Reach

### ISSUE THREAD

**Issue by rokoroku** [Microsoft/TypeScript#15653]
**TypeScript Version:**  2.3.1

With built-in type `Pick<T, K extends keyof T>`, we can extract some props of given keys as a new object interface, but **we cannot extract the single type of the key**.

So I'd like to suggest a new built-in mapped type that will extract a specific type of key from an object interface. It could be named like `Reach`, `Extract` or something else.

It can reduce some redundant type definitions, and nicely adapted to methods like `lodash` (or `underscore`)'s `_.get(value, path)`.  

**Code**

```ts 
type Reach<T, K extends keyof T> = T[K];

interface SomeObject {
  id: number | string;
  data: { text: string };
}

type SomeObjectData = Reach<SomeObject, 'data'> // typeof SomeObjectData = { text: string }
type SomeObjectId = Reach<SomeObject, 'id'> // typeof SomeObjectId = number | string
```

**Comment by hediet** [comment]
What is wrong with
```
type SomeObjectId = SomeObject['id'];
```
?

**Comment by rokoroku** [comment]
Oh. There is a simple way to achieve this!
Thanks, @hediet. I'd better just using that syntax.
