### ISSUE TITLE
Type inference on arrays of generic elements

### ISSUE THREAD

**Issue by kujon** [Microsoft/TypeScript#15659]
**TypeScript Version:**  2.3.2

Generics are a great way of representing relationships between various values:

**Code**

```ts
const foo = <T extends number | string>(one: T, two: T) => [one, two];

// Grand, values are of the same type.
foo(1, 2);

// The type argument for type parameter 'T' cannot be inferred from the usage.
// Consider specifying the type arguments explicitly.
foo(3, '4');
```

---

All awesome so far, until we choose to define an array with elements of generic type:

**Code**

```ts
const bar = <T extends number | string>(value: T[]) => value;

// Works beautifully
bar([1, 2]);

// Also compiles.
bar([3, '4']);
```

**Expected behavior:**
Generics are inferred in a consistent manner irrespectively of whether they're used directly or within an array.

**Actual behavior:**
The following 2 definitions are equivalent:
```ts
const bar = <T extends number | string>(value: T[]) => value;

const bar = (value: Array<number | string>) => value;
```
whereas these are not:
```ts
const foo = <T extends number | string>(one: T, two: T) => [one, two];

const foo = (one: number | string, two: number | string) => [one, two];
```

**Comment by vkurchatkin** [comment]
The difference is that in the first case you use `T` two times, and in second case only once.

**Comment by mhegazy** [comment]
The two forms above have two different meanings. 

The first example asks the compiler to infer the same parameter from two usage locations, and the compiler does that, but then it could not find a reasonable way to unify them. using union types would muffle errors like:

```ts
function insert<T extends string | number>(list: T[], item: T) { 
    list.push(item);
}

declare var numberArray: number[];

insert(numberArray, "string"); 
```

The second sample, is inferring the type of an array literal, and that is not different from any array literal in the program, you would be surprised if these behaved differently:

```ts
bar([3, '4']);

const arr = [3, '4'];
bar(arr);
```

**Comment by kujon** [comment]
So if I understand it correctly, there is no way to tell the compiler to enforce a consistent type for the elements of the array (without specifying what those elements are explicitly), but there are 2 (3*) ways of telling it to use either of those?

```ts
// 1
const bar = <T extends number | string>(value: T[]) => value;
// 2
const bar = (value: Array<number | string>) => value;
// 3*
const bar = <T = number | string>(value: T[]) => value;
```

Or am I missing something?

**Comment by RyanCavanaugh** [comment]
It seems like what you mean to write is this:
```ts
const bar = (value: Array<string> | Array<number>) => value;
```

Those three declarations mean three different things. I'm not sure what the question is.

**Comment by kujon** [comment]
Apologies for the confusion, my examples might have been a little bit too specific. The general question/problem I'm facing is this: I want to ensure that the elements in the array are of consistent type (whatever the type is).

To take the example from above:

```ts
function insert<T>(list: T[], item: T) { 
    list.push(item);
}

insert([{}, [], 5, false, 'foo'], "string"); // <-- this is perfectly legal
```

I was wondering whether there is a way to do it without having to explicitily type things.

**Comment by mhegazy** [comment]
> ` insert([{}, [], 5, false, 'foo'], "string"); // <-- this is perfectly legal`

And what is wrong with that? you are inserting a string to an array that already have strings. this will give you an error `insert([4,5,3], "string")`.

Reading the OP, i think what you are looking for is:

```ts
function insert(list: number[], item: number);
function insert(list: string[], item: string);
function insert(list: (number | string)[], item: number | string) {
    list.push(item);
}
```
