### ISSUE TITLE
Invalid diagnostics produced

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/TypeScript#15666]
**TypeScript Version:**  2.3.1

TS produces `Diagnostic`s with `undefined` `file` field here: https://github.com/Microsoft/TypeScript/blob/2150a7796b0dfe83c5286755410e0fd1646ed86c/src/compiler/core.ts#L1235-L1251

But `Diagnostic.file` is declared as non-optional.

This causes unexpected "Cannot read property x of undefined" errors, even with strict null checks on.

**Comment by mhegazy** [comment]
A PR to update the declaration to `SourceFile | undefined` would be appreciated.

**Comment by felixfbecker** [comment]
Btw, are you planning to adopt `strictNullChecks` into the TS codebase? It would probably prevent issues like this [and many more](https://github.com/Microsoft/TypeScript/issues?utf8=%E2%9C%93&q=cannot%20read%20of%20undefined) in the future

**Comment by mhegazy** [comment]
[It](https://github.com/Microsoft/TypeScript/issues/9432) is on our list of work items.
