### ISSUE TITLE
Array indexing with strictNullChecks should return ItemType | undefined

### ISSUE THREAD

**Issue by mmkal** [Microsoft/TypeScript#15661]
**TypeScript Version:**  2.2.2

**Code**

```ts
const words = new Array<string>();
words.push("foo");
const bar = words[2];
```

**Expected behavior:**
When `strictNullChecks` is turned on, the type of `bar` should be `string | undefined`. In the case above, it will *definitely* be undefined. 

**Actual behavior:**
The type is `string`.

**Comment by ahejlsberg** [comment]
Duplicate of #13778.
