### ISSUE TITLE
Cannot invoke the non-abstract members of an abstract base class via 'super'

### ISSUE THREAD

**Issue by aschwartz-satcom** [Microsoft/TypeScript#15672]
**TypeScript Version:**  2.3.1 

**Code**

```ts
abstract class MyAbstractBase{
    abstract name: string;
    public doSomething = () => {
        console.log(this.name);
    }
}

class SomeChild extends MyAbstractBase{
    name = 'Child';
    public doSomething = () => {
        console.log('Hello from ');
        super.doSomething();
    }
}

```

**Expected behavior:**

No compiler error when invoking public, non-abstract super.doSomething()

**Actual behavior:**

Cannot invoke super.doSomething().
Compiler error: "Only public and protected members of the base class are accessible via the 'super' keyword"

**Comment by RyanCavanaugh** [comment]
You can only `super` call things on the base class prototype, but `doSomething` is an instance property. The property slot here is overwritten by the derived class; there's no code we could possibly emit for that `super` call - there's literally no reachable value that has the base class implementation.

**Comment by aschwartz-satcom** [comment]
Thanks, Ryan, that makes sense.
