### ISSUE TITLE
Cannot use relative import paths with RequireJS

### ISSUE THREAD

**Issue by eschwartz** [Microsoft/TypeScript#1567]
I am trying to convert a RequireJS project over to TypeScript, and I'm running into a problem with relative AMD module paths, where generated TypeScript files are not playing nicely with RequireJS.

TL;DR: RequireJS does not support using relative paths from more than one location. TypeScript only supports relative import paths.

Here's what I've got going on:

```
app/
- MyClass.ts
- MyClass.js
- AnotherClass.ts
- AnotherClass.ts
tests/
- MyClassTest.ts
- MyClassTest.js
```

```js
// app/MyClass.ts
class MyClass = {
  // ...
}
export = MyClass;

// app/MyClass.js
define(["require", "exports"], function (require, exports) {
    var MyClass = (function () {
        function MyClass() {
        }
       
        // ...       

        return MyClass;
    })();
    return MyClass;
});

// app/AnotherClass.ts
import MyClass = ('./MyClass')
class AnotherClass = {
  // Do some stuff that uses MyClass...
}
export = AnotherClass;

// app/AnotherClass.js
define(["require", "exports", "./MyClass"], function (require, exports, MyClass) {
    var AnotherClass = (function () {
        function AnotherClass() {
        }
       
         // Do some stuff that uses MyClass ...

        return AnotherClass;
    })();
    return AnotherClass;
});

// tests/MyClassTest.ts
import MyClass = require('../app/MyClass');
/// some tests...

// tests/MyClassTest.js
define(["require", "exports", "../app/MyClass"], function (require, exports, MyClass) {
    // some tests...
});
```

When I run `tests/MyClassTest.js` I get a RequireJS  timeout error `Load timeout for module 'app/MyClass'.

From what I can find, RequireJS does not support using relative paths in this way. @jburke recommends to always use a `paths` config to specify aliases or root paths, so that all modules can be referenced with the exact same id. My experience with RequireJS confirms this -- I've had the same issue if I reference a module with inconsistent casing, if I use two different path aliases to reference the same module, or if I mix relative paths with aliased module IDs.

I've seen some discussion related to this (#293). But I'm wondering if anyone has found a way to work around this issue. I can't imagine I'm the only one trying to use TypeScript with RequireJS.

**Comment by benjamin-hg** [comment]
@eschwartz: yes, you cannot use relative module paths, but in some cases relative and 'absolute' paths look the same! 
Here is an example:
~~~
app/
- MyClass.ts
- MyClass.js
- AnotherClass.ts
- AnotherClass.ts
- module-aliases.d.ts
tests/
- MyClassTest.ts
- MyClassTest.js
~~~

Let's say, we've configured our AMD loader so there are two packages for the app and test: 'appPackage' and 'testPackage'. (The loader will look for `require`d module IDs starting with that package names and resolve the rest of the module ID relative to the package folder)

module-aliases.d.ts:
~~~typescript
declare module "appPackage/MyClass" {
  import imp = require('MyClass'); // this behaves like a relative path, but tsc eats it as 'not relative'.
  export = imp;
}
~~~

tests/MyClassTest.ts:
~~~typescript
/// <reference path="../app/module-aliases.d.ts" /> // that's the relative part, must match at compile time. 
import MyClass = require('appPackage/MyClass'); // resolves at compile time and at run time
// some tests...
~~~

This module-aliases.d.ts file could be generated with some assumptions about the file structure. I've done this for a larger project. It works quite well with Dojo module loader.

**Comment by eschwartz** [comment]
Thanks, @WorldMaker.

> This module-aliases.d.ts file could be generated with some assumptions about the file structure.

This is what I ended up doing on my project. I created [a little grunt task](https://gist.github.com/eschwartz/9876bb8166d1a98d483b), which generates a definitions file using a RequireJS style `paths` config. So far, it's doing it's job. The only real pain is that my IDE (PHPStorm) does not seem to follow the trail all the way through to the original module, which is a real pain.

**Comment by benjamin-hg** [comment]
Thanks for the quote, @eschwartz, but I'm not WorldMaker ;-)
BTW, I'm using WebStorm and I can navigate through my aliases ... it is jumping to the alias module of course, from there I reach the actual module -- so I need  to click twice.

**Comment by eschwartz** [comment]
Oops, sorry!

You expect me to click twice?! :smirk:

I really which JetBrains would open up their language plugins, so you could extend the behavior of built-in languages. Of course, then I have to learn how to write IntelliJIDEA plugins...

**Comment by electricessence** [comment]
Uhg.  Any fix for this?
I'm finding it frustrating that I'm following a solid pattern of app vs test and I can't get it to work right.
But if I bundle them in a common folder, it works? :(

**Comment by bomzj** [comment]
https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html
Maybe declaring ///<amd-module name="Relative/Path/To/ModuleName"/> at the top of the *.ts file will help.
