### ISSUE TITLE
Property not found on some environments but not others

### ISSUE THREAD

**Issue by viridia** [Microsoft/TypeScript#15676]
**TypeScript Version:**  2.3.2

**Code**

```ts
// In my index.d.ts:
declare class Queue<P extends Queue.Job> extends EventEmitter {
  public readonly name: string;
  public readonly id: string;
  public readonly host: string;
  public readonly port: number;
  public readonly db: string;
  public readonly r: any; // Actually RethinkDbDash handle
  // Many more properties omitted for clarity
}

// In my main file
const q: Queue<MyClass> = queue;
console.log(q.host); // OK
console.log(q.port); // OK
console.log(q.r); // Property 'r' does not exist on type Queue<MyClass>
```

**Expected behavior:**

Should be able to access property 'r' without error.

**Actual behavior:**

On my linux laptop, this compiles fine, but on my OS X machine I get the indicated error. The node_module environments are identical as far as I can determine. (I'm using yarn so the package versions should be the same).

Note: Actual code is here: https://github.com/viridia/factory/blob/master/director/src/App.ts

**Comment by RyanCavanaugh** [comment]
We need a way to reproduce this.

You should try running with the `forceConsistentCasingInFileNames` flag on to make sure this isn't a file name casing issue

**Comment by viridia** [comment]
I am no longer able to reproduce this, please close.
