### ISSUE TITLE
wrong type when using require from .js file

### ISSUE THREAD

**Issue by Pyrolistical** [Microsoft/TypeScript#15683]
**TypeScript Version:**  2.3.2

**Code**

https://gist.github.com/Pyrolistical/f6d5acf7746203aadb46e905de5b8054

**Expected behavior:**
`./node_modules/.bin/tsc` completes without error

**Actual behavior:**
`./node_modules/.bin/tsc` errors with 
`index.js(3,13): error TS2339: Property 'validfunction' does not exist on type 'typeof "/Users/me/tstest/anotherfile"'.`

---

some how the type is being lost when using `require`

**Comment by blakeembrey** [comment]
@Pyrolistical Your `.d.ts` isn't typed correctly to mirror `module.exports` - you should use `export =` instead of `export default`.

**Comment by Pyrolistical** [comment]
OK, what if anotherfile was axios? They use export default. Is it possible to still use require in that case?

**Comment by RyanCavanaugh** [comment]
If your .d.ts file is incorrect, then you're not going to be able to write code that passes both the typecheck and the runtime. The only thing to do is to write the correct .d.ts file

**Comment by Pyrolistical** [comment]
I don't get it. So you want me to request the axios library to change their export to be `export =`?

That seems silly...?

**Comment by Pyrolistical** [comment]
OK. So for third-party libs, I can use `const axios = require('axios').default` and that works for run time as well....but why?

**Comment by mhegazy** [comment]
Are you using babel/SystemJS?

**Comment by Pyrolistical** [comment]
i'm just using nodejs, all files are in gist

**Comment by Pyrolistical** [comment]
node 6.9.2

**Comment by Pyrolistical** [comment]
I just don't get why you can't unify `export =` and `export default` to mean the same thing...?

**Comment by mhegazy** [comment]
cause they do not mean the same thing :)

**Comment by mhegazy** [comment]
`export default` says there is a property called `default` on the module.

**Comment by mhegazy** [comment]
if you are using babel/systemJs, they do change your code so that `default` lookups get you the `default` or the module, e.g.:
```js
import d from "mod";
```

in babel, generates:

```js
"use strict";
var _mod = require("mod");
var _mod2 = _interopRequireDefault(_mod);
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
```

notice `obj && obj.__esModule ? obj : { default: obj }; `..

if that is the case, set `--allowSyntheticDefaultImports`.

**Comment by mhegazy** [comment]
in either cases, do not put `export default` in the .d.ts unless the module has a `.default` property.

**Comment by Pyrolistical** [comment]
OK, i kinda understand `export default` now.

I'm trying to not use babel. I'm trying to just add .d.ts to an existing node project.

**Comment by mhegazy** [comment]
then your .d.ts should match your .js file. if your .js file just `module.exports = { ...}` then the .d.ts should say `export = {... }`

**Comment by Pyrolistical** [comment]
But why is the type of `const axios = require('axios');` different from `const axios = require('axios').default;`?  Axios exported axios to both `module.exports` and `module.exports.default`, so shouldn't it be the same type?

**Comment by mhegazy** [comment]
Cause you did not tell the compiler that you have monkeypatched the `default` property to point to the module export.

`require` as defined by AMD/CommonJS semantics gets you the module object. 
`default` is an ES6 concept. that is a property on the module..

The assumption is, you are either in ES6 land or in AMD/CommonJS land and not in both.

I would recommend sticking with `export =` for now.. then move all your code to ES6 in one shot.

if you want to model what `axios` does, you can use:

```ts

declare namespace A {
  // on the module object
  export function validfunction(greeting: string): void;

  // self reference  
  export { A as default };
}

export = A;
```

but again, i would recommend you do not do that, this makes it hard for you to know what will work in ES6 and what will not.
