### ISSUE TITLE
Intellisense doesn't detect possible variable name if cursor is not at the end of name

### ISSUE THREAD

**Issue by WaldemarH** [Microsoft/TypeScript#15698]
Hi guys

I hoped that in time this one will come from VC++, so hopefully post will help it a little.

For example I have a variable named m_UniqueId_permanent_checkBLABLA and I rename it to m_UniqueId_permanent_checkout.
At this time I would like to change that m_UniqueId_permanent_checkBLABLA to m_UniqueId_permanent_checkout, but intellisense doesn't give you the new name option until you remove the BLABLA text (ctrl+space).
So could you please do it like in VC++ where position of the cursor in the name defines the name search position. i.e. everything left of the cursor is assumed to be searchable (the fixed part of the name) and then it gives you all the names that start with that 'root'.

I know that this doesn't sound much, but let me tell you that this is something that I constantly use in VC++ and get annoyed when it's not there in TS also. :)

So a small change in the 'search' code... just use the left side of the name for searching.

Thanks
Waldemar
p.s. I know about rename name option, but upper one is very useful when coding.

**Comment by mhegazy** [comment]
@CyrusNajmabadi is this something that we can tell Roslyn about?

**Comment by CyrusNajmabadi** [comment]
Roslyn agrees that this should be fixed.  Here's our bug for it: https://github.com/dotnet/roslyn/issues/13594

**Comment by mhegazy** [comment]
thanks @CyrusNajmabadi!

**Comment by CyrusNajmabadi** [comment]
Yup yup!

**Comment by WaldemarH** [comment]
Thanks guys.
