### ISSUE TITLE
missing ts.NodeFlags.Export

### ISSUE THREAD

**Issue by donaldpipowitch** [microsoft/TypeScript#15693]
**TypeScript Version:**  2.3.2

**Code**

["Using the type checker"](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#using-the-type-checker)

**Expected behavior:**

???

**Actual behavior:**

`ts.NodeFlags.Export`: Property `Export` does not exist on `typeof NodeFlags`.

---

What is the best way to learn TypeScripts compiler API? Is it still ["Using the compiler API"](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API)? Is there something like ["Babel Plugin Handbook"](https://github.com/thejameskyle/babel-handbook/blob/master/translations/en/plugin-handbook.md)? Would _love_ to see that. ♥

**Comment by RyanCavanaugh** [comment]
This works now
