### ISSUE TITLE
ES5 Transpilation error when combining async/await with try-catch and parameter object destructuring. 

### ISSUE THREAD

**Issue by Todberg** [Microsoft/TypeScript#15695]
**TypeScript Version:**  2.2.2 (target **ES5**)

**Problem Description**
There is an error in the ES5 emitted JavaScript code when awaiting a promise inside of a `try` block and then using `parameter object destructuring` on the error object in the `catch` clause. The `_c.message` in the switch case of the emitted code needs to be `_a.message`.

**TypeScript Code**

```ts
class Foo {
  public async bar(): Promise<void> {
    try {
      await Promise.reject(new Error("exception"));
    } catch ({ message }) {
      console.log(message);
    }
  }
}

const foo = new Foo();
foo.bar();
```
**ES5 Emitted JavaScript Code**
```ts
Foo.prototype.bar = function () {
  return tslib_1.__awaiter(this, void 0, void 0, function () {
    var _a, message;
    return tslib_1.__generator(this, function (_b) {
      switch (_b.label) {
        case 0:
          _b.trys.push([0, 2, , 3]);
          return [4 /*yield*/, Promise.reject(new Error("exception"))];
        case 1:
          _b.sent();
          return [3 /*break*/, 3];
        case 2:
          _a = _b.sent();
          message = _c.message;
          console.log(message);
          return [3 /*break*/, 3];
        case 3: return [2 /*return*/];
      }
    });
  });
};
```

**Expected behavior:**
Output is the `exception` message.

**Actual behavior:**
Output is a script error: `Unhandled rejection ReferenceError: _c is not defined`

**Comment by mhegazy** [comment]
Looks like it is fixed in latest.
