### ISSUE TITLE
Type intersection by type guards is inconsistent with 'typeof'

### ISSUE THREAD

**Issue by SaschaNaz** [Microsoft/TypeScript#15690]
**TypeScript Version:**  2.3

**Code**

```ts
var a: any;
if (typeof a === "number" && typeof a === "string") {
    a // is never
}

function isA(x: any): x is { a: number } {
    return true;
}

function isB(x: any): x is { a: string } {
    return true;
}

if (isA(a) && isB(a)) {
    a.a // is "number & string"
}
```

**Expected behavior:**

Both should be never or both should be "number & string"

**Actual behavior:**

One is never and the other is "number & string"

**Comment by RyanCavanaugh** [comment]
The first is clearly a bug - it can't possibly be true.

The second situation is just a consequence of how we treat multiple type guards. The type `number & string` will always be possible due to generic instantiation; it's not going to be possible to always resolve this type to `never`.
