### ISSUE TITLE
Array of tuple default initializer assignability issue

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#15696]
**TypeScript Version:**  2.2.1 / nightly (2.2.0-dev.201xxxxx)

**Code**

```ts
let a: [string, 'asc' | 'desc'][];
a = [['some', 'asc']]; // No error

class A {
    a: [string, 'asc' | 'desc'][];
}

class B extends A {
    a = [['some', 'asc']]; // Error string[][] is not assignable to [string, 'asc' | 'desc'][]
}
```

**Expected behavior:**
The default initialised member `a` in class `B` should not error.

**Actual behavior:**
The default initialised member `a` errors.

**Comment by RyanCavanaugh** [comment]
Duplicate #10570

**Comment by RyanCavanaugh** [comment]
See #10570
