### ISSUE TITLE
Suggestion - Missing of a declarationFile option

### ISSUE THREAD

**Issue by maikelhendriksen** [Microsoft/TypeScript#15701]
**TypeScript Version:**  2.2.1 / nightly (2.2.0-dev.201xxxxx)

**Code**

```ts
tsc app.ts --declarationFile app-test.d.ts --declaration

```

**Expected behavior:**
Compiling the TypeScript and generating a declaration file with the name app-test.d.ts in the current folder.

**Actual behavior:**
error TS5023: Unknown compiler option 'declarationFile'.

**Comment by mhegazy** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/8372

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
