### ISSUE TITLE
Excessive stack depth comparing types - No filename or line for error tracing

### ISSUE THREAD

**Issue by lukephills** [Microsoft/TypeScript#15712]
I'm getting this error in my build:
`TS2321: Excessive stack depth comparing types 'Map<string, {}>' and 'Iterable<any, any>'`
It seemed to come out of nowhere. I'm running Vscode on osx 10.11.6. 

**TypeScript Version:**  2.2.1 / nightly (2.2.0-dev.201xxxxx)
2.2.1

**Code**
Unfortunately I can't trace the error. I've tried rolling back commits to previous working versions. Also tried deleted and reinstalled node modules, upgrading and downgrading typescript versions.

**Expected behavior:**
Should build

**Actual behavior:**
TS2321: Excessive stack depth comparing types 'Map<string, {}>' and 'Iterable<any, any>'

**Comment by lukephills** [comment]
With the --verbose and --display-error-details flags in webpack this is the info I get:

```
...

[825] ./~/xtend/immutable.js 384 bytes {0} [depth 7] [built]
       cjs require xtend [824] ./~/xhr/index.js 5:12-28
 [826] ./package.json 5.16 kB {0} [depth 3] [built]
       cjs require ../package.json [380] ./src/App.js 27:18-44

ERROR in [at-loader] TS2321: Excessive stack depth comparing types 'Map<string, {}>' and 'Iterable<any, any>'.
Child extract-text-webpack-plugin:
    Entrypoint undefined = extract-text-webpack-plugin-output-filename
       [0] ./~/css-loader/lib/css-base.js 1.46 kB {0} [depth 1] [built]
           cjs require ../css-loader/lib/css-base.js [1] ./~/css-loader?{"modules":false,"importLoaders":1}!./~/postcss-loader!./~/reset-css/reset.css 1:27-67
       [1] ./~/css-loader?{"modules":false,"importLoaders":1}!./~/postcss-loader!./~/reset-css/reset.css 926 bytes {0} [depth 0] [built]
Child extract-text-webpack-plugin:
    Entrypoint undefined = extract-text-webpack-plugin-output-filename
       [0] ./~/css-loader?{"modules":true,"importLoaders":1,"localIdentName":"[hash:base64:5]"}!./~/postcss-loader!./src/shared/values.css 759 bytes {0} [depth 1] [built]
           cjs require -!../node_modules/css-loader/index.js?{"modules":true,"importLoaders":1,"localIdentName":"[hash:base64:5]"}!../node_modules/postcss-loader/index.js!./shared/values.css [2] ./~/css-loader?{"modules":true,"importLoaders":1,"localIdentName":"[hash:base64:5]"}!./~/postcss-loader!./src/style.css 3:10-196
...
```

**Comment by lukephills** [comment]
I tried switching at-loader for ts-loader and still the same untraceable error

**Comment by mhegazy** [comment]
Can you give `typescript@next` a try, we made a recent change that might have addressed the issue.

otherwise we will need to have access to a sample code, we will be happy to do this over email if this works best for you.

**Comment by lukephills** [comment]
The error is still there using v2.3.2. 
It seems to be environmental since I tried on another machine and there is no error. Have you come across anything like that previously? I'm wondering whether there's anything I should delete and reinstall like node?

node v6.5.0
npm v3.10.3
OSX El Capitan 10.11.6

**Comment by mhegazy** [comment]
> The error is still there using v2.3.2.

i meant `typescript@next`  and not `typescript@2.3.2`.

**Comment by mhegazy** [comment]
> It seems to be environmental since I tried on another machine and there is no error. Have you come across anything like that previously? I'm wondering whether there's anything I should delete and reinstall like node?

if i were to guess, it is the bitness, node x64 has more memory than x32, and thus you have more room before running out of stack space

**Comment by lukephills** [comment]
Okay cool, I tried @latest (2.4.0-dev.20170509) and the error is still there.
I wasn't sure of the which node bitness i was using but logging `process` in the terminal gives me this:

arch: x64

```
process {
  title: 'node',
  version: 'v6.5.0',
  moduleLoadList: 
   [ 'Binding contextify',
     'Binding natives',
     'NativeModule events',
     'NativeModule util',
     'Binding uv',
     'NativeModule buffer',
     'Binding buffer',
     'Binding util',
     'NativeModule internal/util',
     'NativeModule timers',
     'Binding timer_wrap',
     'NativeModule internal/linkedlist',
     'NativeModule assert',
     'NativeModule internal/process',
     'Binding config',
     'NativeModule internal/process/warning',
     'NativeModule internal/process/next_tick',
     'NativeModule internal/process/promises',
     'NativeModule internal/process/stdio',
     'Binding constants',
     'NativeModule tty',
     'NativeModule net',
     'NativeModule stream',
     'NativeModule _stream_readable',
     'NativeModule internal/streams/BufferList',
     'NativeModule _stream_writable',
     'NativeModule _stream_duplex',
     'NativeModule _stream_transform',
     'NativeModule _stream_passthrough',
     'NativeModule internal/net',
     'Binding cares_wrap',
     'Binding tty_wrap',
     'Binding tcp_wrap',
     'Binding pipe_wrap',
     'Binding stream_wrap',
     'NativeModule internal/repl',
     'NativeModule readline',
     'NativeModule internal/readline',
     'NativeModule repl',
     'NativeModule internal/module',
     'NativeModule vm',
     'NativeModule path',
     'NativeModule fs',
     'Binding fs',
     'Binding fs_event_wrap',
     'NativeModule console',
     'Binding signal_wrap',
     'NativeModule module',
     'NativeModule domain',
     'NativeModule os',
     'Binding os',
     'NativeModule string_decoder' ],
  versions: 
   { http_parser: '2.7.0',
     node: '6.5.0',
     v8: '5.1.281.81',
     uv: '1.9.1',
     zlib: '1.2.8',
     ares: '1.10.1-DEV',
     icu: '57.1',
     modules: '48',
     openssl: '1.0.2h' },
  arch: 'x64',
  platform: 'darwin',
...
}

**Comment by mhegazy** [comment]
Can you share the project, or a simplified version of it that demonstrates the same issue?

**Comment by lukephills** [comment]
The error was environmental. I restored my machine and the error has gone away. Thanks for your help.
