### ISSUE TITLE
how can i get an automatic build number/version?

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#15710]
i need a time stamp in my code which would tell whether the client and server code match or crash otherwise to prevent execution in an inconsistent environment

is there a way to get an incremental number in my code every time i run a build?

**Comment by gcnew** [comment]
I've previously solved this issue by using the number of git commits during building. It can get a little tricky if your CI pulls with depth 1 (as you likely do), however commit timestamp is still there waiting :).

**Comment by mhegazy** [comment]
C++ has had this in a macro [`__TIME__`](https://gcc.gnu.org/onlinedocs/cpp/Standard-Predefined-Macros.html); compile-time macros are not that uncommon [C# has caller file](https://msdn.microsoft.com/en-us/library/system.runtime.compilerservices.callerfilepathattribute(v=vs.110).aspx), and [VB and C# have nameof operator](https://docs.microsoft.com/en-us/dotnet/articles/csharp/language-reference/keywords/nameof).

But i guess we decided not to do compile-time macros at the time being.

**Comment by aleksey-bykov** [comment]
it's simple, just change your mind and decide you need  them

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
