### ISSUE TITLE
Go to definition fails when maxNodeModuleJsDepth = 0

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#15717]
_From @Wenzil on May 9, 2017 17:14_

- VSCode Version: 1.12.1
- OS Version: OS X

### Steps to Reproduce:

1. Open VS Code in a new workspace
2. `npm init -y`
3. `npm install --save express`
4. In `tsconfig.json`:
```json
{
    "compilerOptions": {
        "target": "es6",
        "module": "commonjs",
        "allowJs": true,
        "checkJs": true,
        "noEmit": true,
        "maxNodeModuleJsDepth": 0
    },
    "exclude": [
        "node_modules"
    ]
}
```
5. In `index.js`: 
```js
const express = require('express')
```

6. Right click on `'express'`, and choose *Go to definition*

### Expected behaviour: 

The editor navigates to the .js file containing the module implementation (under node_modules/express)

### Actual behaviour: 

The editor says 

> No definition found for 'express'

_Copied from original issue: Microsoft/vscode#26329_

**Comment by mjbvz** [comment]
Since `maxNodeModuleJsDepth` is zero, I believe the failure to find `express` is expected. Can someone on the TS team please verify this

**Comment by mhegazy** [comment]
This is correct. the issue here is that ATA should kick in and download the .d.ts for you. with that goto def will go to the .d.ts.

The issue here is you are using a `tsconfig.json` and not a `jsconfig.json`, and that changes the defaults for ATA. 

So to enable ATA, in the `tsconfig.json` add:

```ts
    "typeAcquisition": {
        "enable": true
    }
```

Alternatively, `npm install -D @types/express`

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
