### ISSUE TITLE
Spread: methods are also getting cloned in spread variable

### ISSUE THREAD

**Issue by nikhilgoyal94** [Microsoft/TypeScript#15724]
**TypeScript Version:**  2.2.1 / nightly (2.2.0-dev.201xxxxx)
Method m is also getting cloned to the variable d but according to the document, it should not.

**Code**
```ts
// A *self-contained* demonstration of the problem follows...
class C {
    a: number = 2;
    b: string = "Nikhil";
    m = function () {
        return this.a;
    }
}

let c = new C();

let d = { ...c };

console.log(c);
console.log(d.m());
```

**Expected behavior:**
Error should be there while calling d.m()

**Actual behavior:**
It is displaying the value as 2.

**Comment by kitsonk** [comment]
In the case above, `m` is not a method.  It is a property with a function value.  It is therefore copied when you spread properties.  The behaviour matches the [proposed spec](https://github.com/tc39/proposal-object-rest-spread).  [An example](https://jsfiddle.net/97La3Lsr/) (requires experimental JavaScript in Chrome or Safari TP) of what this would look like in JavaScript:

```js
class C {
	constructor() {
		this.a = 2;
    	this.b = "Nikhil";
    	this.m = function () {
			return this.a;
		}
	}
}

let c = new C();

let d = { ...c };

console.log(c);
console.log(d.m());
```
