### ISSUE TITLE
Ambient module declaration (Specification)

### ISSUE THREAD

**Issue by olegdunkan** [microsoft/TypeScript#15729]
Specification states that: 
12.2 Ambient Module Declarations

This type of declaration is permitted only at the top level in a source file that contributes to the global namespace (section 11.1).

But I can do so:

```ts
//in i.ts (this is a module, not script)
    export interface I {
        x:number;
    }


//in i.1.ts  (this is a module, not script)
   import { I } from './i'

   declare module './i' {
      interface I {
         y:number;
      }
   }
````
Specification states the grammar for my case:

ImplementationModule ->
ImplementationModuleElement ->
ImplementationElement->
AmbientDeclaration->
           declare AmbientVariableDeclaration
   declare AmbientFunctionDeclaration
   declare AmbientClassDeclaration
   declare AmbientEnumDeclaration
   declare AmbientNamespaceDeclaration

We see that there is no AmbientModuleDeclaration.

**The question is, where AmbientModuleDeclaration is described in specification for module, not for script?**

**Comment by RyanCavanaugh** [comment]
Need to update the spec for module augmentation semantics

**Comment by RyanCavanaugh** [comment]
The spec is now an "archived" artifact and we won't be tracking defects against it anymore.
