### ISSUE TITLE
Unable to determine secondary keyof type in a generic definition

### ISSUE THREAD

**Issue by nomaed** [Microsoft/TypeScript#15728]
(please update the title if it doesn't precisely describe the source of the issue)

**TypeScript Version:**  2.3.2

**Code**

```ts
interface IState {
    title: string;
    count: number;
    stuff: Array<string>;
}

const state: IState = {
    title: "Foo",
    count: 42,
    stuff: ["foo", "bar", "baz"],
};

function logStateChange<T, K extends keyof T>(property: K, newValue: T[K], oldValue: T[K]) {
    console.log("changing", property, "from", oldValue, "to", newValue);
}

const prop: keyof IState = "title";
const val: IState["title"] = "Foofoo";

// cannot determine types at all
logStateChange(prop, val, state[prop]);
//             ^^^^ Argument of type "K is not assignable to parameter of type "never"

// even though "T" is provided, keyof T is not resolved
logStateChange<IState>(prop, val, state[prop]);
// ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Supplied parameters do not match any signature of call target

// this one works but seems like a waste of keystrokes to add the keyof type
logStateChange<IState, keyof IState>(prop, val, state[prop]);
```

[Playground link](https://www.typescriptlang.org/play/index.html#src=interface%20IState%20%7B%0D%0A%20%20%20%20title%3A%20string%3B%0D%0A%20%20%20%20count%3A%20number%3B%0D%0A%20%20%20%20stuff%3A%20Array%3Cstring%3E%3B%0D%0A%7D%0D%0A%0D%0Aconst%20state%3A%20IState%20%3D%20%7B%0D%0A%20%20%20%20title%3A%20%22Foo%22%2C%0D%0A%20%20%20%20count%3A%2042%2C%0D%0A%20%20%20%20stuff%3A%20%5B%22foo%22%2C%20%22bar%22%2C%20%22baz%22%5D%2C%0D%0A%7D%3B%0D%0A%0D%0Afunction%20logStateChange%3CT%2C%20K%20extends%20keyof%20T%3E(property%3A%20K%2C%20newValue%3A%20T%5BK%5D%2C%20oldValue%3A%20T%5BK%5D)%20%7B%0D%0A%20%20%20%20console.log(%22changing%22%2C%20property%2C%20%22from%22%2C%20oldValue%2C%20%22to%22%2C%20newValue)%3B%0D%0A%7D%0D%0A%0D%0Aconst%20prop%3A%20keyof%20IState%20%3D%20%22title%22%3B%0D%0Aconst%20val%3A%20IState%5B%22title%22%5D%20%3D%20%22Foofoo%22%3B%0D%0A%0D%0A%2F%2F%20cannot%20determine%20types%20at%20all%0D%0AlogStateChange(prop%2C%20val%2C%20state%5Bprop%5D)%3B%0D%0A%2F%2F%20%20%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%20Argument%20of%20type%20%22K%20is%20not%20assignable%20to%20parameter%20of%20type%20%22never%22%0D%0A%0D%0A%2F%2F%20even%20though%20%22T%22%20is%20provided%2C%20keyof%20T%20is%20not%20resolved%0D%0AlogStateChange%3CIState%3E(prop%2C%20val%2C%20state%5Bprop%5D)%3B%0D%0A%2F%2F%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%20Supplied%20parameters%20do%20not%20match%20any%20signature%20of%20call%20target%0D%0A%0D%0A%2F%2F%20this%20one%20works%20but%20seems%20like%20a%20waste%20of%20keystrokes%20to%20add%20the%20keyof%20type%0D%0AlogStateChange%3CIState%2C%20keyof%20IState%3E(prop%2C%20val%2C%20state%5Bprop%5D)%3B%0D%0A)

**Expected behavior:**
It looks to me that the compiler has all the info to correctly determine types without any additional annotation in this case.
At the least, I would expect providing the main type (T) to be enough.

**Actual behavior:**
Doesn't work without giving the main type and also "keyof" this type.

If I change the generic definition to be:
```ts
function logStateChange<T>(property: keyof T, newValue: T[keyof T], oldValue: T[keyof T]) {
    console.log('changing', property, 'from', oldValue, 'to', newValue);
}
```
then it works with just a single type (`IState`) but it still won't work without any types at all.

**Comment by mhegazy** [comment]
The first call, there is no way for the compiler to know the type `T`. `prop` is just a string literal, the annotation `const prop: keyof IState = "title";` just means that `prop` is `"title" | "count" | "stuff"`, and the type `IState` is not maintained in any way on the type of `prop`.
Since `T` is not known, then, it is assumed to be the lower bound, `{}`, and thus `K` is `never`, since it has no known properties, and thus the error.

The second call, is a bit more subtle. TypeScript does not do partial type inference. either type parameters are specified, or inferred. Once you specify a single type parameter you shutoff any inference that could happen. Since this function needs 2 type parameters and you specified one, the error is that it could not find a signature with just one type parameter.

The third call supplies all the type arguments, and thus no error. 

I would recommend changing the function to have a source of inference for T, e.g.:

```ts
function logStateChange<T, K extends keyof T>(obj: T, property: K, newValue: T[K], oldValue: T[K]) {
    console.log("changing", property, "from", oldValue, "to", newValue);
}
```

this way you get the inference without having to specify the type arguments on every call.

**Comment by nomaed** [comment]
I see. If "keyof" only expands the keys of an interface but keeps no reference to the source interface then. 
The example I provided is simplified, in my actual use case it's a method that's modifying instance member, so it wouldn't make sense passing the source. It makes sense for stateless use cases though.

**Comment by mhegazy** [comment]
Generic type inference needs a source. and keyof is just a list of literal string types, does not matter how they are specified.
