### ISSUE TITLE
Typescript Compiler for PHP

### ISSUE THREAD

**Issue by lakinmohapatra** [Microsoft/TypeScript#15739]
Can we expect a tool of Typescript which can convert typescript code to php ?
It will be very useful .

**Comment by RyanCavanaugh** [comment]
No

**Comment by sajjadkazemi10ss** [comment]
http://cretz.github.io/pratphall/

**Comment by avifatal** [comment]
@sajjadkazemi10ss this project was not updated 5 years...
@RyanCavanaugh Very ugly answer.
