### ISSUE TITLE
JSDoc stripping leading whitespace in code blocks

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#15749]
From: https://github.com/Microsoft/vscode/issues/26415

**TypeScript Version:**  2.3.2

**Code**

```ts
/**
 * @example
 * ```
 * if (true) {
 *     foo()
 * }
 * ```
 */
function foo() {
    return '2';
}
```

**Expected behavior:**
For the `@example` tag, we should return content including any leading whitespace

**Actual behavior:**
In this case, whitespace is stripped: 

```
[Trace - 3:32:54 PM] Response received: quickinfo (120). Request took 2 ms. Success: true 
Result: {
    "kind": "function",
    "kindModifiers": "",
    "start": {
        "line": 9,
        "offset": 10
    },
    "end": {
        "line": 9,
        "offset": 13
    },
    "displayString": "function foo(): string",
    "documentation": "",
    "tags": [
        {
            "name": "example",
            "text": "```\nif (true) {\nfoo()\n}\n```"
        }
    ]
}
```

This results in incorrect rendering of the code example:

![screen shot 2017-05-10 at 3 33 17 pm](https://cloud.githubusercontent.com/assets/12821956/25924131/067f5bc4-3596-11e7-877a-cf5d73c601a5.png)

**Comment by mjbvz** [comment]
This does not happen if you have an extra newlines before the code block:

```js
/**
 * @example
 * 
 * ```
 * if (true) {
 *     foo()
 * }
 * ```
 */
function foo() {
    return '2';
}
```

![screen shot 2017-05-10 at 3 34 17 pm](https://cloud.githubusercontent.com/assets/12821956/25924159/24c26d4c-3596-11e7-9875-17d96a471e49.png)

**Comment by jiayihu** [comment]
The issue is still there, where should I have a look in order to fix it and open a PR?

**Comment by mhegazy** [comment]
@sandersn, can you point @jiayihu to where this change needs to be made

**Comment by sandersn** [comment]
Take a look at [`parseTagComments`](https://github.com/Microsoft/TypeScript/blob/4bf42fd1c4a6d81a511e1b4c0bce515cc616ad35/src/compiler/parser.ts#L6551), although the bug might be in the initial state when calling the function, since there's an initial `indent` passed in.

**Comment by psyrendust** [comment]
I'm getting a slightly different results in vscode Version 1.28.2 (1.28.2)

#### with newline after `@example`
```ts
/**
 * @example
 *
 * ```
 * if (true) {
 *     foo()
 * }
 * ```
 */
function foo() {
    return '2';
}
```
![image](https://user-images.githubusercontent.com/928502/47758187-1eb94280-dc67-11e8-9a8e-654f1395cc0f.png)


#### no newline after `@example`
```ts
/**
 * @example
 * ```
 * if (true) {
 *     foo()
 * }
 * ```
 */
function foo() {
    return '2';
}
```
![image](https://user-images.githubusercontent.com/928502/47758170-0c3f0900-dc67-11e8-9747-0099ca5b5729.png)


#### no fenced code blocks
```ts
/**
 * @example
 * if (true) {
 *     foo()
 * }
 */
function foo() {
    return '2';
}
```
![image](https://user-images.githubusercontent.com/928502/47758146-ef0a3a80-dc66-11e8-87bc-7ea5184e8a4e.png)

**Comment by sandersn** [comment]
In summary, the original issue is fixed, but unfenced code blocks still squash leading white space as in @psyrendust's last example.

The parser doesn't know about markdown, so I suspect this is caused later in the pipeline. Needs investigation.

**Comment by sandersn** [comment]
The problem is that the code currently only handle indentations of the form

```js
/**
 * @example if (true) {
 *              foo()
 *          }
 */
```

The code starts off parsing `@example`'s comment with the wrong indentation because it doesn't reset the indent level after parsing `@example` followed by newline.

**Comment by ibbignerd** [comment]
This is a separate issue. This is only talking about leading whitespace,
not example blocks.

**Comment by justinmchase** [comment]
I see that this is closed but it appears to still be a bug in the latest release.

**Comment by mjbvz** [comment]
The original example works for me in VS Code 1.43:

![Screen Shot 2020-02-26 at 10 22 09 AM](https://user-images.githubusercontent.com/12821956/75374869-e426e080-5881-11ea-86b1-939a1904cff9.png)

**Comment by justinmchase** [comment]
False alarm. It wasn't working for me I swear, but just trying it again its now fine... Please ignore.

**Comment by tulio-coppola** [comment]
A Related issue still occurring on version 1.44.0

The original example works:
<img width="328" alt="Screen Shot 2020-05-11 at 16 42 54" src="https://user-images.githubusercontent.com/49724601/81604737-bba18380-93a6-11ea-902e-f1a810e8af90.png">

But if you use the `<caption>` tag on the `@example` it breaks again and trims the whitespaces:
<img width="359" alt="Screen Shot 2020-05-11 at 16 43 13" src="https://user-images.githubusercontent.com/49724601/81604796-d673f800-93a6-11ea-8247-1f4e43341747.png">

**Comment by erichiller** [comment]
Doubling what @tulio-coppola said, `<caption>` seems to break things.

Example:
```ts
/**
 * Create a new type which has the properties of `Base` that match `Condition`
 * 
 * @example <caption>This example extracts properties of `foo` that have a value type of `string`</caption>
 *          // `fooT` is now { a: string, d: string }
 *          // `fooKT` is now ` 'a' | 'd' `
 *          interface foo {
 *              a: string;
 *              b: number;
 *              c: string[];
 *              d: string;
 *          }
 *          type fooT = SubType<foo, string>;
 *          type fooKT = keyof fooT ;
 * @example
 * interface foo {
 *      prop: string;
 * }
 */
export type SubType<Base, Condition> =
    Pick<Base, AllowedNames<Base, Condition>>;
```

results in:
![image](https://user-images.githubusercontent.com/5379325/84029961-7abe6f80-a950-11ea-9667-071ca8b235ec.png)

This is 1.45.1 on Windows

**Comment by davwheat** [comment]
This issue is still present in the latest version of TS.

**Comment by sandersn** [comment]
Please open a new issue; this one has been closed a long time.
