### ISSUE TITLE
Block scoped variable from a *.d.ts file used before its declaration (VS2015 TS2.3.1 only)

### ISSUE THREAD

**Issue by makana** [Microsoft/TypeScript#15757]
**TypeScript Version:**  2.3.1 for Visual Studio 2015 (2.3.1-TS-release-dev14update3-20170425.3)

With the latest TypeScript version for Visual Studio 2015 2.3.1 from 4/28/2017 there's the following behavior:

If there is a class decalred in a d.ts declaration file and it is included via tsconfig.json and it is used and initialized in a static property of a class, and the outFile option is used, the following error occurs:

TS2448: Block-scoped variable 'xyz' used before its declaration.

I guess, types from any declaration files should always be considered declared and not taken into account for the check.

This is just an issue with the latest Visual Studio 2015 version. This is not an issue for Visual Studio code or the 2.3.1 or latest npm package.

This is just an issue if all of the following settings come together:

- the d.ts is included via the "include" option of the tsconfig.json (which sometimes makes sense because of the wildcards)
- the type is used and instantiated in a static class property
- the outFile option is used

This is not an issue if one of the upper is replaced e.g. by

- using the /// <reference tag instead of include option
- using the type in a const or variable
- not using the outFile option

**Code**

tsconfig.json
```json
{
	"compilerOptions": {
		"module": "none",
		"outFile": "../dist/code.js"
	},
	"include": [
		"*.d.ts",
		"**/*.ts"
	]
}
```

types.d.ts
```ts
declare namespace Foo
{
	class Bar
	{

	}
}
```

code.ts
```ts
namespace MyNamespace
{
	export class MyClass
	{
		public static readonly myBar = new Foo.Bar(); // not OK: TS2448: Block-scoped variable 'Bar' used before its declaration.
	}

	export const myBar = new Foo.Bar(); // OK
}
```

cmd
```
C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.3\tsc -p .
```

**Expected behavior:**

- All Types that originate from a *.d.ts declaration file should be considered declared and should therefore not produces errors when used and initialized in a static property.

**Actual behavior:**

- TS2448 error occurs if all of the following settings are applied:

  - the d.ts is included via the "include" option of the tsconfig.json (which sometimes makes sense because of the wildcards)
  - the type is used and instantiated in a static class property
  - the outFile option is used

**Comment by mhegazy** [comment]
Looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/15734

**Comment by makana** [comment]
You're right. Sorry about that. Glad seeing this fixed, thanks!
