### ISSUE TITLE
I Love Typescript

### ISSUE THREAD

**Issue by TheWizz** [Microsoft/TypeScript#15758]
Right in the middle of this stream of problems and complaints, I just want to express how much I love Typescript. Without Typescript I would most likely not have been able to write the kind of complex application I'm working on. And I would definitely NOT have been able to do the kind of major refactoring I'm in the midst of right now. Having the Typescript compiler watching over my sholder, combined with a good IDE that picks up and presents all the "intellisense" it can get, is just amazing!

Thank you Anders, Microsoft and everyone else involved with Typescript who spent countless hours of your life making my life easier and more enjoyable. And all this for free! Open source at its very best.

-JM

**Comment by AJamesPhillips** [comment]
Exactly.  Thanks for sharing!  More of this please :)

**Comment by RyanCavanaugh** [comment]
See also #10011, but for once I won't complain about a duplicate issue
