### ISSUE TITLE
Filter unnecessary type suggestions in completion list

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#15750]
From https://github.com/Microsoft/vscode/issues/26340

**Problem**
When working in JavaScript files, we currently show the same suggestions as we do in TypeScript files. These suggestions include many interfaces and types that JavaScript users usually do not care about:

![screen shot 2017-05-10 at 3 41 39 pm](https://cloud.githubusercontent.com/assets/12821956/25924386/50397398-3597-11e7-843e-6bd1ab6117f4.png)

**Proposed Fix**
Suggestions for interfaces and types should only be returned in JavaScript contexts where they are actually useful, such as inside JSDoc

**Comment by mhegazy** [comment]
JSDoc should still be considered a type location.

We probably should also do a quick pass over gotodef and find all refs, to make sure we are filtering the results in the same way.

**Comment by mhegazy** [comment]
To clarify, this issue tracks filtering the entries in the completion list based on the location where the completion is requested. i.e. in a value postilion, type names are not returned, and in a type position, values names are not returned

**Comment by waaronking** [comment]
I know this was marked as `Fixed`, but it's still an issue in the latest version of VS Code. Is this maybe because a fix is planned?

**Comment by xhy279** [comment]
this is not fixed. still see interface suggestions. Thats sucks and annoying

**Comment by mhegazy** [comment]
We believe this is fixed. if you are still running into issues, please file a new issue, give us the version you are using and enough context to be able to diagnose it. commenting on an old and closed issue does not really help much.
