### ISSUE TITLE
Type <generic> cannot be used to index type <array>

### ISSUE THREAD

**Issue by tycho01** [Microsoft/TypeScript#15768]
**TypeScript Version:**
0 2.3.1-insiders.20170416 (Playground)

**Code**
```ts
type X<I extends number> = ['a'][I];
```

**Expected behavior:**
No error

**Actual behavior:**
`Type 'I' cannot be used to index type '["a"]'.`

I thought this may have worked before. Potential regression?

**Comment by WanderWang** [comment]
I have a simular issue .

```
type ValueType = { 0: { name: string }, 36: { id: string } };
type KeyType = 0 | 36

function getValue<T extends KeyType>(key: T): ValueType[T] {
    let data: ValueType;
    let result = data[key.toString()];
    return result;
}
let a = getValue(0).name;
let b = getValue(36).id;
```

**Expected behavior:**
No error

**Actual behavior:**
Type 'I' cannot be used to index type '["a"]'.

**Comment by tycho01** [comment]
Temp workaround from [here](https://github.com/gcanti/typelevel-ts/pull/7): throw the generic through another type that outputs a `number`.

**Comment by tycho01** [comment]
Hm, not having as much luck with that workaround anymore on nightlies, potentially related to #17455.

This problem still seems to manifest even in cases where I'd think the needed type info should be present:
```
type NumberToString = { [i: number]: string; };
type StringToNumber = { [k: string]: number; };
type A = NumberToString[StringToNumber[string]];
// -> ok
type B<T extends string> = NumberToString[StringToNumber[T]];
// -> Type 'StringToNumber[T]' cannot be used to index type 'NumberToString'.
```

**Comment by tycho01** [comment]
Hm, not having as much luck with that workaround anymore on nightlies, maybe related to #17455.

Here's another bigger example showing it fails when generics are involved even if separated by operations that would work:
```
type NumberToString = { [i: number]: string; };
type StringToNumber = { [k: string]: number; };

type A = NumberToString[StringToNumber[string]];
// -> ok, string
type B<T extends string> = NumberToString[StringToNumber[T]];
// -> Type 'StringToNumber[T]' cannot be used to index type 'NumberToString'.
```

**Comment by tycho01** [comment]
I *think* the cause here is `checkIndexedAccessIndexType` in the TS compiler's `checker.ts`, which does a `TypeVariable` check for the object type yet not for the index type.

**Comment by tycho01** [comment]
PR at #17767.
