### ISSUE TITLE
Formatting javascript wrong in aspx page with Format Document command in VS2017 

### ISSUE THREAD

**Issue by cm9988** [Microsoft/TypeScript#15764]
Please check the error screenshot here:

https://developercommunity.visualstudio.com/content/problem/51190/when-using-format-document-on-an-aspx-page-the-ide.html

VS2017 (15.2)

If the new JavaScript language service is disabled, the format is OK, but the New Lines options do not work when the service is disabled.

**Comment by mhegazy** [comment]
@jramsay looks related to the base indentation.

**Comment by mhegazy** [comment]
tracked by https://developercommunity.visualstudio.com/content/problem/51190/when-using-format-document-on-an-aspx-page-the-ide.html
