### ISSUE TITLE
Named function type annotation and assertions

### ISSUE THREAD

**Issue by backbone87** [Microsoft/TypeScript#15773]
**TypeScript Version:**  2.3

After searching for a few hours, i found no way how to provide type annotations for a named function, so its definition becomes more concise.

```ts
import _Vue, { PluginFunction } from 'vue'

type MyPluginOptions = (Some & Complex) | Type[]
type MyVuePlugin = PluginFunction<MyPluginOptions>

// 1. works as type assertion (infers types correctly), but "hides" the function
// (a) the unary expr after a type assertion has an own scope (?)
export default <MyVuePlugin>function install(Vue, options) { ... }

// 2. works but not very nice, since the export must go after the function definition
var test: MyVuePlugin = function test(Vue, options) { }
export default test;
var test: MyVuePlugin = function(Vue, options) { }
export default test;

// 3. none of the "as" type assertions work
export default function as MyVuePlugin install(Vue, options) { ... }
export default function: as MyVuePlugin install(Vue, options) { ... }
export default function install(Vue, options): as MyVuePlugin { ... }

// 4. type annotation? doesnt work
export default function MyVuePlugin install(Vue, options) { ... }
export default function: MyVuePlugin install(Vue, options) { ... } // (b)
export default function install(Vue, options): is MyVuePlugin { ... } // "is" syntax borrowed from another ticket
```

- is a type assertion the same as a type annotation in the demonstrated case? i dont know
- why dont just declare type annotations in the function? because they can get complex and bloat the function declaration
- is the statement of (a) correct? if so, it shouldnt be possible at all to write (useable) type assertations for named functions
- i personally would prefer (b) for (named) function type annotation

wdyt?

**Comment by mhegazy** [comment]
you could try `export default ((Vue, options) => { }) as MyVuePlugin;`.

TypeScript tries to limit any new syntax that is not in JS. functions do have a clear way to be defined, and have a clear way to specify their argument types, so adding a new export or function declaration syntax just for this scenario is out side the scope of the TS project.
