### ISSUE TITLE
Question: Migrating from namespace to external modules

### ISSUE THREAD

**Issue by CodySchaaf** [Microsoft/TypeScript#15774]
This is just a question, and I know that is not encouraged, but I'm having trouble finding any help on stackoverflow. There are a few posts with no answers and the people asking are still stuck. 

We have been using TypeScript at my company for a little over 3 years with our AngularJs app. Everything is written in TypeScript using internal modules (now over 2556 files...). It has become increasing clear that we should be using external modules. For example wanting to take advantage of build tools like webpack to utilize tree shaking ect. Not to mention our upgrade to angular2. 

Is there any documentation on upgrading in a more piecewise fashion? It doesn't look like you can require external components inside the internal modules without types breaking, and importing from the namespace in an external modules is a little weird.

Also Most the tsc plugins for webpack and browserify can't validate certain sub directories separately, they hit the whole directory ever time. 

Not sure if my only option is to figure out a way to convert all files at once. 

Any thoughts or direction would be great.

Thanks!

**Comment by mhegazy** [comment]
There is relevant discussion in https://github.com/Microsoft/TypeScript/issues/12473. 

I also have a comment related to this in https://github.com/Microsoft/TypeScript/issues/8004#issuecomment-262673275. what we have seen is it is always your logic, and not the file organization that is the most painful to migrate.

My recommendation is to do it incrementally. pick a leaf component, and move it to a module, make sure you keep it in the global scope as well to keep your existing code working, then find its users, migrate them, and so on recursively. hopefully the first couple of components you migrate will shed some light on the architectural changes you need to make.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
