### ISSUE TITLE
Refactoring operations shouldn't reach external definitions such as lib.d.ts and node_modules

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#15776]
**TypeScript Version:**  2.3

**Comment by mhegazy** [comment]
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/7458

**Comment by falsandtru** [comment]
#7458 treats a part of this issue. But I think #7458 is not enough. It is too much detail.

**Comment by mhegazy** [comment]
it is the issue we are using to track this change. not sure having two issues helps any one.

**Comment by falsandtru** [comment]
I feel if #8227 is not dup, this is not dup. If this is dup, #8227 is dup.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
