### ISSUE TITLE
Provide option "Enter outlining mode when files open"

### ISSUE THREAD

**Issue by NoelAbrahams** [microsoft/TypeScript#15770]
**TypeScript Version:**  2.3 / Visual Studio 2017 Preview 2

Please provide the following option for TypeScript files, shown here for C#:

![image](https://cloud.githubusercontent.com/assets/1106823/25964825/1a8b36f4-367e-11e7-8215-b27c788c8c12.png)

Since VS 2017 has structure guidelines, the outlining is redundant for those who do not normally collapse sections of code.

![image](https://cloud.githubusercontent.com/assets/1106823/25965119/f50725f4-367e-11e7-80ae-6826328d8087.png)

**Comment by mhegazy** [comment]
//cc @billti

**Comment by RyanCavanaugh** [comment]
Closing due to lack of additional feedback
