### ISSUE TITLE
Unable to rename the property of destructuring assignment

### ISSUE THREAD

**Issue by mhegazy** [microsoft/TypeScript#15787]
From https://github.com/Microsoft/TypeScript/issues/6312#issuecomment-278974537

```ts
const x = 1;
const o = { x };
{
    const { x } = o;
    x;
}
```

Renaming any `x` will result in broken code.

**Comment by andy-ms** [comment]
#### Option 1
The safe route would be to always leave local variables alone:
* If I rename `const x = 1;` to `y`, I get `const o = { x: y }`.
* If I rename `x` the property, I get `const o = { y: x }` and `const { y: x } = o`.

#### Option 2
Whenever we are renaming a property, we might recursively rename any locals that are used in a shorthand property declaration with it.
This would be doable; we handle imports in a similar way. But it could result in incorrect code if there is shadowing involved.

In the case of renaming a local that happens to be used in a shorthand declaration, you probably want option 1 anyway.

**Comment by mhegazy** [comment]
Related to #19173 and #15787

**Comment by OliverJAsh** [comment]
> Renaming any `x` will result in broken code.

I can't reproduce this now on 3.4.1. Renaming `x` to `f` produces valid code:

``` ts
const x = 1;
const o = { x };
{
    const { x: f } = o;
    f;
}
```

``` ts
const f = 1;
const o = { x: f };
{
    const { x } = o;
    x;
}
```

**Comment by dsherret** [comment]
@OliverJAsh is this a VS code thing? I also see that behaviour in VS code, but not in the TypeScript playground.

When calling `findRenameLocations` on the language service in 3.6.0-dev.20190530 however, I get the following objects (with no `prefixText` or `suffixText`):

```
[ { textSpan: { start: 6, length: 1 }, fileName: '/testFile.ts' },
  { textSpan: { start: 25, length: 1 }, fileName: '/testFile.ts' } ]
```

So I'm not sure this is actually fixed in TypeScript's language service.

**Comment by OliverJAsh** [comment]
Hmm, what behaviour do you see in the playground?

VS Code does have an option to control this behaviour ([`typescript.preferences.renameShorthandProperties`](https://github.com/microsoft/TypeScript/issues/29238)), which they pass through to TS, but AFAIK they don't change the default value.

**Comment by dsherret** [comment]
@OliverJAsh my bad. I didn't realize this was configurable. Probably the playground is not using this.

There is a new `providePrefixAndSuffixTextForRename` parameter on `findRenameLocations`:

```ts
findRenameLocations(fileName: string, position: number, findInStrings: boolean, findInComments: boolean, providePrefixAndSuffixTextForRename?: boolean): ReadonlyArray<RenameLocation> | undefined;
```

Once I provided `true` for that I got the expected results:

```
[ { textSpan: { start: 6, length: 1 }, fileName: '/testFile.ts' },
  { textSpan: { start: 25, length: 1 },
    fileName: '/testFile.ts',
    prefixText: 'x: ' } ]
```

Thanks for the help!

**Comment by fatcerberus** [comment]
From what I can tell the Playground doesn’t actually have a Rename function in the same capacity as VS Code’s - it’s “Change All Occurrences” which is a dumb find-and-replace utilizing multiple cursors:

```ts
function f() { let f = 0; }
```

Right click one of the `f`s, hit Change All Occurrences and type `g`.  For your trouble, you end up with a `gunction`. :smile:
