### ISSUE TITLE
Preserve Indentation of Closing > in Multiline Type List

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#15782]
From: https://github.com/Microsoft/vscode/issues/26485

**TypeScript Version:**  2.3.2

**Code**

```ts
class Favorite extends Array<
    string
> {
    private foo = 2
}
```

Run format document

**Expected behavior:**
Formatting is preserved

**Actual behavior:**
The closing `>` is indented
```ts
class Favorite extends Array<
    string
    > {
    private foo = 2
}
```

**Comment by jhanschoo** [comment]
Just a quick note that this bug still exists in version 3.1.6

**Comment by andrewbranch** [comment]
@DanielRosenwasser, it seems like you had some reservations when we talked about this one but we ended moving on—just want to make sure you have a chance to follow up before I put up a PR. (Not going to do this one before the beta probably, but didn’t want to forget.)

**Comment by DanielRosenwasser** [comment]
I wouldn't sweat it, it's more about "don't touch the indentation at all" potentially not being the right direction.

But we probably can do this post-beta.
