### ISSUE TITLE
Object types (Specification)

### ISSUE THREAD

**Issue by olegdunkan** [Microsoft/TypeScript#15793]
From specification:
````
3.3 Object Types

Object types are composed from properties, call signatures, construct signatures, 
and index signatures, collectively called members.
3.8.3 Object Type Literals
  ...
  TypeMember:
   PropertySignature
   CallSignature
   ConstructSignature
   IndexSignature
   MethodSignature
  ...
  Object type members are described in section 3.9.

3.9 Specifying Members
3.9.5 Method Signatures

  A method signature is shorthand for declaring a property of a function type.

````
Why there is no **method signatures** in the first sentence?
_Object types are composed from properties, call signatures, construct signatures, 
and index signatures, collectively called members._

Does `properties` mean `method and property signatures` together?
If so it is not evidently.
May be it is better to split `properties` into `property and method signatures`,
because we will enumerate entities from one domain (signatures).

**Comment by olegdunkan** [comment]
@DanielRosenwasser thanks, I expected that they are the same entity but in the context of object literal they are apart.

**Comment by DanielRosenwasser** [comment]
No prob! It's more a difference between the syntax and the type itself
