### ISSUE TITLE
TypeScript dynamic module loading issue using typeof

### ISSUE THREAD

**Issue by rishabhpoddar** [Microsoft/TypeScript#15798]
I am dynamically loading modules I have created like so:

myModule.ts
`export class SomeClass {
 ...
}
export type SomeType = {...}`

In another file, I do:
`
  import * as MyModuleType from "./myModule"
  if(...) {
    let loadedModule: typeof MyModuleType = require("./myModule");
     ...
  }
`

(Sorry the code isn't formatted correctly. See http://stackoverflow.com/q/43938280/3867175)

The type of MyModuleType has both SomeClass and SomeType (as expected). Whereas the type of loadedModule has only SomeClass (incomplete type!). How can I solve this issue?

Version of typescript: 2.3.2

editor: atom, using atom-typescript v10.1.15

Thank you.

**Comment by mhegazy** [comment]
Replied to your post.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
