### ISSUE TITLE
Interface with optional properties is not assignable to indexable type with strict-null-checks

### ISSUE THREAD

**Issue by maghis** [Microsoft/TypeScript#15799]
I understand this is more a feature request then a bug report :)

**TypeScript Version:**  2.3.2

**Code**

```ts
const test: { [key: string]: string } = {} as { foo?: string };
```

**Expected behavior:**
A type with optional properties should be assignable to an indexable, even if the indexable values do not include `undefined`.

**Actual behavior:**
```
error TS2322: Type '{ foo?: string | undefined; }' is not assignable to type '{ [key: string]: string; }'.
  Property 'foo' is incompatible with index signature.
    Type 'string | undefined' is not assignable to type 'string'.
      Type 'undefined' is not assignable to type 'string'.
```

**Comment by mhegazy** [comment]
the type should be `const test: { [key: string]: string | undefined } = {} as { foo?: string };`.

see https://github.com/Microsoft/TypeScript/issues/13778 for relevant discussion on why the indexer does not include `undefined` by default.

**Comment by maghis** [comment]
@mhegazy thanks for the pointer, the for loop on an array use case made it perfectly clear.
