### ISSUE TITLE
--allowJs Unexpected behavior

### ISSUE THREAD

**Issue by Odol** [Microsoft/TypeScript#15801]
Hello mates, 
I have a problem, when enable option "allowJs" , The ts compiler goes crazy 
trying to compile again and again the same files 👎 

They could tell me why, Thanks for your time greetings!

Typescript 2.3.2 
vscode 1.12.1

**Comment by aaronbeall** [comment]
Are you outputting the JS in the same folder you are compiling?

**Comment by mhegazy** [comment]
make sure you have your output folder in your `exclude` property.

**Comment by Odol** [comment]
Thanks for your answers.
I have a nodejs server completely written with typescript
Disabling the option allowJs  works perfectly, but I need to consume a javascript file to do something special.

this my tsconfig file

{
	"version": "2.3.2",
	"compilerOptions": {
		"target": "es6",
		"module": "commonjs",
		"moduleResolution": "node",
		"pretty": true,
		"removeComments": true,
		"preserveConstEnums": true,
		"outDir": "bin",
		"skipLibCheck": true,
		"sourceMap": true
	},
	"exclude": [
		"node_modules"
	]
}

**Comment by Odol** [comment]
I have included the output folder in my exclude property and now works perfectly thank you for your time
regards!!

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
