### ISSUE TITLE
Rename on enum member does not rename enum literal use sites

### ISSUE THREAD

**Issue by rbuckton** [Microsoft/TypeScript#15800]
**TypeScript Version:**  2.4.0-dev.20170501

**Code**

```ts
const enum Kind {
    A // (1)
}
interface X {
  kind: Kind.A; // (2)
}
```

Steps:
1. Use 'Rename' to rename the symbol `A` to `B` at position (1)

**Expected behavior:**

The symbol at position (2) is renamed to `Kind.B`.

**Actual behavior:**

The symbol at position (2) does not change.

**Comment by andy-ms** [comment]
Should be fixed by #15743.
