### ISSUE TITLE
New Website Logo: Artsy

### ISSUE THREAD

**Issue by alloy** [Microsoft/TypeScript#15804]
Please fill the following out:

- Name: Artsy
- Homepage url: https://www.artsy.net
- Brand Guidelines/Licensing: n/a
- Logo: SVG https://cl.ly/0B3G071n0v2s

One of our OSS sample apps got featured in the “What’s new in TypeScript” talk at MS Build, so I guess we’re friends? :) http://twitter.com/alloy/status/862987779839586304

**Comment by mhegazy** [comment]
@alloy can you repost the logo? the link above does not seem to work any longer.

**Comment by alloy** [comment]
@mhegazy On it!

**Comment by alloy** [comment]
[Here we go](https://github.com/Microsoft/TypeScript/files/1039474/Artsy_Logo.svg.zip)

**Comment by mhegazy** [comment]
thanks!
