### ISSUE TITLE
Salsa works for imported module members but not within the exporting module

### ISSUE THREAD

**Issue by pitaj** [Microsoft/TypeScript#15809]
**TypeScript Version:**  2.3.2

**Code**

```js
// ==== main.js ====

const foobar = require('./module');

foobar.foo
foobar.bar

// ==== module.js ====

/** @type {{ spacing: number, perLine: number }} */
const defaults = {
  spacing: 2,
  perLine: 6,
};

/**
 * @param {{ spacing: number, perLine: number }} options
 * @returns {{ spacing: number, perLine: number }}
 */
exports.foo = (options) => Object.assign({}, defaults, options);

/**
 * @param {string} name
 * @param {number} age
 */
exports.bar = (name, age) => {
  return `The person named "${name}" is ${age} years old!`;
};
```

I emulated the expected behavior by adding this at the bottom of `module.js`:
```js
/** @type {{ foo(options: { spacing: number, perLine: number }): { spacing: number, perLine: number }, bar(name: string, age: number): string }} */
const exports = module.exports;
```

#### IntelliSense in `main.js`

Autocomplete should work
![image](https://cloud.githubusercontent.com/assets/803701/26019312/bc070d74-3731-11e7-9b27-aaefc26d5a41.png)

Hovering over references should work
![image](https://cloud.githubusercontent.com/assets/803701/26019472/b5d7a7dc-3732-11e7-8af4-b7ca2bda3772.png)

#### IntelliSense in `module.js`
Hovering over the definitions should work
![image](https://cloud.githubusercontent.com/assets/803701/26019374/283df778-3732-11e7-9414-39b7aad22472.png)

Autocomplete should work
![image](https://cloud.githubusercontent.com/assets/803701/26019793/90721cc2-3735-11e7-9625-8877d1d7f798.png)

Hovering over references should work
![image](https://cloud.githubusercontent.com/assets/803701/26019812/bce11f92-3735-11e7-981a-32a8300874fe.png)

#### IntelliSense in `main.js`

Works just fine in autocomplete
![image](https://cloud.githubusercontent.com/assets/803701/26019312/bc070d74-3731-11e7-9b27-aaefc26d5a41.png)

Or when hovering over references to imports
![image](https://cloud.githubusercontent.com/assets/803701/26019472/b5d7a7dc-3732-11e7-8af4-b7ca2bda3772.png)

#### Failing IntelliSense in `module.js`

It works when hovering over the members themselves
![image](https://cloud.githubusercontent.com/assets/803701/26019374/283df778-3732-11e7-9414-39b7aad22472.png)

But doesn't work when trying to get autocompletes
![image](https://cloud.githubusercontent.com/assets/803701/26019412/57e34b04-3732-11e7-8b91-05064856fad6.png)

Nor when hovering over other references to exports
![image](https://cloud.githubusercontent.com/assets/803701/26019448/8d247928-3732-11e7-85dd-42098ed1d7ea.png)

**Comment by mhegazy** [comment]
`exports` and `module.exports` are special properties that the compiler knows about in the binder; they are used to extract declarations for exports, yet we do not give them the right type in the checker, which is the type of the module.

**Comment by andy-ms** [comment]
I'm not sure if we're even binding it. If you have `@types/node` installed you will get a definition of `exports` from there, otherwise you get `Cannot find name 'exports'.`

```ts
// @module: commonjs
// @allowJs: true
// @checkJs: true
// @noEmit: true

// @Filename: /a.js
exports;
```

**Comment by mhegazy** [comment]
Yeah. We have to spcial case the global export and module object somehow.
