### ISSUE TITLE
TypeScript Playground "Share" button creates invalid URL when pressed more than once

### ISSUE THREAD

**Issue by aaronbeall** [microsoft/TypeScript#15803]
If you click the "Share" button in the TypeScript Playground more than once, it keeps appending a new hash `#src=` as opposed to updating the current hash, resulting in an invalid share link. If you manually remove the hash and hit "Share" again, it still appends to the old hash. This makes it hard to edit and re-share.

Using Chrome 57.

![screenshot](http://g.recordit.co/jQrGA5GamF.gif)

**Comment by orta** [comment]
This has been replaced with a better playground 👍

**Comment by aaronbeall** [comment]
The new playground is awesome!
