### ISSUE TITLE
Export markTypeNodeAsReferenced from TypeChecker api

### ISSUE THREAD

**Issue by goloveychuk** [Microsoft/TypeScript#15816]
Hey, I'm working on library which emits type metadata for classes.
https://github.com/goloveychuk/tsruntime

Problem I faced.

```ts
//file 1
export class ExportedCls { }
```

```ts
//file 2
import {ExportedCls} form './file1'

@Reflective
class B {
 ref: ExportedCls
}
```
And I'm trying to emit 
```js
__decorate([
    Reflect.metadata("tsruntime:type", { kind: 18, optional: false, type: module_1.ExportedCls, arguments: [] }),
], Imported.prototype, "ref", void 0);
```
But  import `A` will be elided, sinse `isReferencedAliasDeclaration` for ExportedCls == false. Because checks was performed before transformer modify ast.

I see you have        `function checkDecorators(node: Node): void {` in `checker.ts`
where you marking typeNodes as referenced if they decorated. 

So the solution could be:
1) export `markTypeNodeAsReferenced` method as public. (maybe in emitResolver)
2) in checkDecorators visit class children recursively and mark properties types as referenced. 
Second way is not general and produces potentially ununsed imports. 
First way is much more general, and you could use it from typescript transformer, to mark some type nodes. And remove checkDecorators method from checker.ts.

**Comment by mhegazy** [comment]
This is an internal checker detail, do not think it should be exposed. the meaning of the function and its use can change with no notice. 

And i do not think marking all types as references if a class is decorated is correct either.

the semantics of the meta-data emit is clear, only the decorated declaration is maintained, so if you want the prop type to be maintained, decorate the property.

The decorator feature will undergo changes in the future as we implement the new decorator proposal, and until then we are not planning on making any changes to the scope of the implementation of the feature.

**Comment by goloveychuk** [comment]
ok, that's understandable. Just wondered, if you're planning, after new proposal, emitting additional info (like prop optionalness, generic arguments etc...).

**Comment by mhegazy** [comment]
That is something we have discussed in the past but have not reached a conclusion about to be frank. Optionality seems simple to add, generic types however is more down the type serialization route.
