### ISSUE TITLE
Make node type predicates public

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#15811]
There are a bunch of useful functions in `utilities.ts` that just test against a node kind, such as `isImportClause`. Currently these are all `@internal`. Could these be made public?
This would help slim down [tsutils](https://github.com/ajafff/tsutils/blob/master/src/typeguard.ts), which duplicates much of this behavior. Predicates like `isDeclaration` would be especially hard to maintain duplicates of.

**Comment by mhegazy** [comment]
Go for it.
