### ISSUE TITLE
VS2017.2 can't load language server plugins from the project directory

### ISSUE THREAD

**Issue by gentoo90** [Microsoft/TypeScript#15822]
**TypeScript Version:**  2.3.1
**Visual Studio Version:** 2017.2

`tsconfig.json`:

```json
{
    "compilerOptions": {
        ...
        "plugins": [
            { "name": "tslint-language-service" }
        ],
        ...
    }
}
```

**Expected behavior:**

Visual Studio should be able to find plugins in `$(ProjectDir)\node_modules`

**Actual behavior:**

Visual Studio only looks for plugins in TypeScript SDK's installation directory and in `C:\Windows\system32`

`tsserver.log`

```
Info 455  Loading tslint-language-service from C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.3\tsserver.js/../../.. (resolved to C:/Program Files (x86)/Microsoft SDKs/node_modules)
Info 456  Failed to load module: {}
Info 457  Loading tslint-language-service from  (resolved to C:/Windows/system32/node_modules)
Info 458  Failed to load module: {}
Info 459  Couldn't find tslint-language-service anywhere in paths: C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.3\tsserver.js/../../..,
```

**Comment by mhegazy** [comment]
That is something we are working on right now. should be enabled in the next VS release.

**Comment by aslatter** [comment]
Would this same bug also affect Visual Studio Code, or is this specific to Visual Studio?

I'm seeing something similar trying to follow the instructions [here](https://github.com/Microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin#testing-locally) for "Testing Locally", and in the language-service logs I'm seeing:

    Info 10   [22:34:18.702] Config file name: c:/Users/User/Documents/Projects/test-proj/tsconfig.json
    Info 11   [22:34:18.778] Loading demo-plugin from c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js/../../.. (resolved to c:/Program Files (x86)/Microsoft VS Code/resources/app/extensions/node_modules/node_modules)
    Info 12   [22:34:18.802] Failed to load module 'demo-plugin': Error: Could not resolve JS module 'demo-plugin' starting at 'c:/Program Files (x86)/Microsoft VS Code/resources/app/extensions/node_modules/node_modules'. Looked in: <elided>

I don't have the TypeScript SDK installed. I'm using Visual Studio Code 1.16.0.

**Comment by josephliccini** [comment]
Just downloaded Visual Studio 2017 15.5 and this seems to be working!

TSLint Language Service works very nicely, with fixers and everything in VS2017!

Our Angular Language Service (`@angular/langauge-service`) seems to only check TS Files (not HTML templates) and also seems to not update properly after fixing errors, but I can probably follow up with the Angular team on these ones.
