### ISSUE TITLE
Extending classes with generic parameters fails when no parameters provided 

### ISSUE THREAD

**Issue by yhaskell** [Microsoft/TypeScript#15820]
As TypeScript is a super-set of JavaScript, every correct javascript program should be also a correct typescript program.

**TypeScript Version:**  2.3.2

**Code**

```ts
class Container<T> {
   constructor(protected _value: T) {}
   value() : T { return this._value }
}

class MutableContainer extends Container {
   setValue(newValue) { this._value = newValue }
}

let con = new MutableContainer(42);
console.log(con.value());
```

**Expected behavior:**
42

**Actual behavior:**
```
example.ts(6,32): error TS2314: Generic type 'Container<T>' requires 1 type argument(s).
```

Lets suppose for a minute that our `Container` class is a strongly typed javascript library, and we wrote our MutableContainer in JavaScript file `mutable-container.js`. The moment we rename our javascript file to `mutable-container.ts`, everything will fail, although it should've still worked.

Possible fix:
* When no type arguments are provided, infer them to any. 
* Show warnings (maybe)
* Add `--noImplicitTypeArguments` key that will disable this behaviour 
* Add it into `--strict` mode

**Comment by aluanhaddad** [comment]
Just provide a default type parameter.
```ts
class Container<T = {}> {
   constructor(protected _value: T) {}
   value() : T { return this._value }
}
```
[Playground](http://www.typescriptlang.org/play/#src=class%20Container%3CT%20%3D%20%7B%7D%3E%20%7B%0D%0A%20%20%20constructor(protected%20_value%3A%20T)%20%7B%7D%0D%0A%20%20%20value()%20%3A%20T%20%7B%20return%20this._value%20%7D%0D%0A%7D%0D%0A%0D%0Aclass%20MutableContainer%20extends%20Container%20%7B%0D%0A%20%20%20setValue(newValue)%20%7B%20this._value%20%3D%20newValue%20%7D%0D%0A%7D%0D%0A%0D%0Alet%20con%20%3D%20new%20MutableContainer(42)%3B%0D%0Aconsole.log(con.value())%3B)

**Comment by yhaskell** [comment]
That is not a solution. There are tons of existing libraries which end user cannot actually fix without forking.
