### ISSUE TITLE
Homomorphic mapped types do not adopt documentation comments

### ISSUE THREAD

**Issue by hediet** [Microsoft/TypeScript#15821]
**TypeScript Version:**  2.3.0

Homomorphic mapped types do not adopt documentation comments, as shown in the following example:
**Code**
```ts
interface Foo {
	/** Gets the bar. */
	bar: any;
}

let t: Foo = null!;
t.bar; // Has the comment "Gets the bar" associated with it.

let t2: { [TKey in keyof Foo]: any } = null!;
t2.bar; // Has no comment associated with it.
```

Even though the type of the propery changes, mapped properties are still very related to the property they originate from and thus adopting the doc comments from the originating property should be reasonable.

## Use Case
Mixin classes together with mapped types provide a much more sophisticated alternative to decorators:
```ts
class MyService {
	queryData() { return "Data"; }
}

class MyClass extends annotate(Object,
	{
		/**
		 * All services. (This comment is lost)
		 */
		myServices: injectMany(MyService, "MyService1")
	})
{
	public doSth() {
		return this.myServices.map(s => s.queryData()).join(",");
	}
}

function injectMany<T>(clazz: new() => T, name: string): { _type: T[] } {
	throw "todo";
}

type Constructable<T> = new (...args: any[]) => T;

function annotate<TBC extends Constructable<object>, TProps extends { [name: string]: { _type: any } }>
	(base: TBC, props: TProps): Constructable<{[TKey in keyof TProps]: TProps[TKey]["_type"]}> & TBC {

	return class extends base {
		constructor(...args: any[]) {
			super(args);
		}
	} as any;
}
```
In contrast to decorators, this approach allows to infer the type of the property from its annotation.

However, not being able to specify documentation comments for the properties that are introduced by `annotate` is a show-stopper.

**Comment by rozzzly** [comment]
What's the significance of `null!`? I know there is the non-null assertion operator, `!.`, eg: `foo!.bar` so is this related to that? Asserting that null is non-null?

**Comment by hediet** [comment]
@rozzzly The exclamation mark subtracts the `null` type from the given expression. Since `null` has the type `null`, the type of `null!` is `never` (which is the empty union type).
This is a trick to make typescript think that `t` is being initialized.

**Comment by rozzzly** [comment]
@hediet I thought as much, thanks for explaining how it gets reduced to `never`. I wouldn't have expected `never` to be assigable to an interface.  Is there a particular reason you didn't just use `undefined` or drop the assignment from the initializer?

**Comment by hediet** [comment]
@rozzzly If you have
![](https://latex.codecogs.com/gif.latex?a_1%20%5Cmid%20%5Cdots%20%5Cmid%20a_n%20%5C%3B%20%3D%3A%20%5C%3B%20%5C%3B%5Cmid%20%5C%7B%20a_1%2C%20%5Cdots%2C%20a_n%20%5C%7D%20%5C%3B%20%5Cleq%20%5C%3B%20b%20%5C%3B%5C%3B%20%5CLeftrightarrow%20%5C%3B%5C%3B%20%5Cforall%20i%3A%20a_i%20%5Cleq%20b)
where `a1, ..., an, b` are types and  `<=` means "assignable to", it follows that `|{}` (the empty union type, aka `never`) is assignable to every type, including interfaces.
`undefined` (which is of the predefined type `undefined`) is also not assignable to `Foo`. If I had dropped the assignment from the initializer, TypeScript wouldn't let me use `t` before assigning it.

**Comment by Kovensky** [comment]
This seems similar to the case of a `class` or `interface` that `extends` / `implements` a type with documentation not inheriting the original documentation.
