### ISSUE TITLE
Editing ".js" file does not update errors in ".ts" file

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#15826]
**TypeScript Version:**  nightly (2.4.0-dev.20170513)

**Code**

(with `--allowJs`)

**a.js**

```js
export const x = 0;
```

**b.ts**

```ts
import * as a from "./a";
a.x;
a.y;
```

See the error in `b.ts` on `a.y`. Then add `export const y = 1;` to `a.js`.

**Expected behavior:**

No more error in `b.ts`.

**Actual behavior:**

Still see the error.

Note: I tried writing a fourslash test but couldn't produce the error that way. May be a problem in vscode.
```ts
/// <reference path="fourslash.ts" />

// @allowJs: true

// @Filename: /a.js
////export const x = 0;
/////*insert*/

// @Filename: /b.ts
/// <reference path="fourslash.ts" />
////import * as a from "./a";
////a.x;
////a.y;

goTo.file("/b.ts");
verify.numberOfErrorsInCurrentFile(1);

goTo.marker("insert");
edit.insertLine("export const y = 1;");

goTo.file("/b.ts");
verify.numberOfErrorsInCurrentFile(0);
```

**Comment by mhegazy** [comment]
Does making an edit to b.ts cause the error to disappear?

**Comment by DanielRosenwasser** [comment]
Is it possible that because only the trivia is being changed, that some check on whether the tree changes isn't getting triggered?

**Comment by mhegazy** [comment]
Ah u are right. We are not clearing the jsdoc when do an incremental parsing if the edit is in the jsdoc only. You need to change the node. Looks like you found a good one :)

**Comment by andy-ms** [comment]
There's no jsdoc here, the problem is that even actual node changes in '.js' files aren't picked up.
Editing 'b.ts' gets you correct errors again.

**Comment by mhegazy** [comment]
In this case that should be expected. You should see the same behavior in two TS files.

**Comment by andy-ms** [comment]
I use '.ts' files the error in 'b.ts' will be fixed the moment I edit 'a.ts'.

**Comment by DanielRosenwasser** [comment]
> There's no jsdoc here

Derp - sorry, though that is certainly something we should look at.

**Comment by mhegazy** [comment]
Could not reproduce this locally. please reopen if it is still an issue.

**Comment by andy-ms** [comment]
I can still reproduce this with `typescript@next`.
![ajsbts](https://user-images.githubusercontent.com/19274678/38708501-68fed1e2-3e6b-11e8-823a-15b9db36f1cc.jpg)

**Comment by andy-ms** [comment]
Also, sometimes when I do a fresh restart with both `a.js` and `b.ts` open, I see no errors in `b.ts` even if `a.js` doesn't have `export const y`.
In both cases, correct behavior is restored if I make an edit to `b.ts`.
My `tsconfig.json` is just `{ "compilerOptions": { "allowJs": true } }`.

**Comment by sheetalkamat** [comment]
@andy-ms can you check in latest vscode insiders i cant repro this any more with typescript@next

**Comment by andy-ms** [comment]
Thanks, seems to be working now.
