### ISSUE TITLE
[Feature Request] A way to instruct how to infer `this`

### ISSUE THREAD

**Issue by bigopon** [microsoft/TypeScript#15836]
**TypeScript Version:**  2.3.2

**Code**

I have this definition:
```ts
extend<T, K>(cls: (...args: {}[]) => T, xtn: K): new (...args: {}[]) => T & K
```

Usage:

```js
var NewClass = extend(MyClass, {
  init(a) {
    this.doSomething();
  },

  // ....
})
```

The `NewClass` will still have all expected method `init` ..., but the `this` cannot be inferred inside the extension object.

It would be great if there is a way to instruct Typescript how to infer the `this` inside extension object based on the first passed param meter. (`MyClass` in the example). The reason is to have better intellisense.

**Comment by DanielRosenwasser** [comment]
We actually shipped this in TypeScript 2.3 to support APIs like those in Ember and Vue.

See #14141.

**Comment by DanielRosenwasser** [comment]
For the record, you probably want

```ts
extend<T, K>(cls: (...args: {}[]) => T, xtn: K & ThisType<T & K>): new (...args: {}[]) => T & K
```

**Comment by bigopon** [comment]
It looks awesome. But I couldn't make it work. Tried adding `noImplicitThis` to the jsconfig but i got warning that it is not a valid config.

And makes me wonder if the following is doable

```ts
interface Observable {
  /**
   * Very long long long comment to explain how to use `options`
   */
  on(event: string, handler: Function, options?: object): Observable
}

interface MyClass extends Observable {
  // ...
}
```

We know that using `new MyClass().on(...)` will return MyClass instance, but how to tell Typescript to return `MyClass` instead of `Observable`. I don't wanna rewrite all the comment on the overload method on MyClass interface.

**Comment by kitsonk** [comment]
```ts
interface Observable {
  /**
   * Very long long long comment to explain how to use `options`
   */
  on(event: string, handler: Function, options?: object): this
}

interface MyClass extends Observable {
  // ...
}
```
