### ISSUE TITLE
How to compile typescirpt .ts code into WebAssembly .wasm ?

### ISSUE THREAD

**Issue by liangzeng** [Microsoft/TypeScript#15837]
How to compile typescirpt .ts code into WebAssembly .wasm ?

**Comment by DanielRosenwasser** [comment]
Check out the conversation at #9202. At face value, it really doesn't make a ton of sense to compile JavaScript to Web Assembly when it needs a full JavaScript runtime associated with it.

**Comment by HyphnKnight** [comment]
There is another project attempting to this exact thing called assemblyScript its still in development but if this is of interest to you. You can find it [HERE](https://github.com/AssemblyScript/assemblyscript).
