### ISSUE TITLE
Class extension in generics does not work when using Partial.

### ISSUE THREAD

**Issue by TomerKr** [Microsoft/TypeScript#15832]
**TypeScript Version:**  2.3.2 (or whatever is running in the playground, something similar is reproduced locally of course.)

**Code**

```ts
class Foo{
    something: boolean;
    something2: boolean;
}

class MyClass<T extends Foo>{
    func(x): Partial<T>{
        return {
            something: true
        }
    }
}
```

**Expected behavior:**
The code is valid and the TS compiler recognizes that T in the context of MyClass can have a 'something' field.

**Actual behavior:**
The code does not compile. The error is: "Type '{ something: true; }' is not assignable to type 'Partial<T>'."

**Comment by RyanCavanaugh** [comment]
Duplicate #12731

**Comment by TomerKr** [comment]
I'll be closing this issue then and try discussing it in the duplicate. Thanks.
