### ISSUE TITLE
When module not found, show output of `--traceResolution` for that module

### ISSUE THREAD

**Issue by andy-ms** [microsoft/TypeScript#15845]
**TypeScript Version:**  latest

**Code**

```ts
import { x } from "unresolved-module";
```

**Expected behavior:**

Shows the attempts to resolve "unresolved-module".

**Actual behavior:**

Just says that the module wasn't resolved.

People can always turn on `--traceResolution` after getting such an error, but that shows the resolution for *all* modules, which can be pretty long.

**Comment by mhegazy** [comment]
It is strange that you get a punch of trace messages with your errors.. i wounder if there is a way to just say trace resolutions for failed modules..

**Comment by DanielRosenwasser** [comment]
traceResolution: `true | false | "maybe"`

**Comment by mhegazy** [comment]
or `--traceResolution "myModule"`

**Comment by aluanhaddad** [comment]
This would be an extremely valuable and very much appreciated feature.

**Comment by pirtim** [comment]
For future lurkers - rather obvious - workaround:
`tsc --traceResolution | grep 'unresolved-module'`

**Comment by RyanCavanaugh** [comment]
Not much feedback on this, and the module resolution trace is extremely verbose and not formatted for everyday usage. I'm honestly not sure it would even help, since if the module is present, the trace doesn't explain why it didn't look in the place you expected it to be found.
