### ISSUE TITLE
How to find definition of a re-exported variable with the compiler API?

### ISSUE THREAD

**Issue by donaldpipowitch** [Microsoft/TypeScript#15840]
**TypeScript Version:**  2.3.2

Given the following project:

```ts
// src/index.ts
import { add } from './add';
export { add };
```

```ts
/**
 * This function adds two summands.
 * @param a The first summand.
 * @param b The second summand.
 * @returns The sum.
 */
export function add(a: number, b: number): number {
  return a + b;
}
```

And a compiler usage like this:

```ts
const program = createProgram([ 'src/index.ts' ], compilerOptions);
const checker = program.getTypeChecker();
const sourceFile = program.getSourceFiles().find(sourceFile => sourceFile.fileName === 'src/index.ts');

const exports = checker.getExportsOfModule(checker.getSymbolAtLocation(sourceFile))[0];
exports.forEach(e =>
  const documentation = displayPartsToString(e.getDocumentationComment());
  if (!documentation) {
    // documentation is an empty string here, because there is no comment for `add` in `index.ts`
    // how do I get the comment for `add` from `add.ts`
  }
);
```

Is there a way to find the original declaration of a given node or symbol?

**Comment by andy-ms** [comment]
`checker.getAliasedSymbol(symbol)` should help. Note: You need to check `symbol.flags & ts.SymbolFlags.Alias` first or it will throw an error.
(`checker.getExportSpecifierLocalTargetSymbol` is relevant but would get the *locally* aliased symbol for the re-export, which is the import.)

**Comment by donaldpipowitch** [comment]
@andy-ms Thank you _so much_. I wouldn't have figured it out without you. I tried `checker.getAliasedSymbol(symbol)` before, but without `symbol.flags & ts.SymbolFlags.Alias`. Can you explain me _why_ this is needed? It seems to be a little bit counterintuitive. Thank you!
