### ISSUE TITLE
any type in callback parameter

### ISSUE THREAD

**Issue by NN---** [Microsoft/TypeScript#1584]
Is it intended behavior ?

```typescript
function x(f: (g: number) => void): void { f(1); }

x(function (d) {
   // d is number
});
```

Adding parentheses around the function makes 'd' to be any type:

```typescript
function x(f: (g: number) => void): void { f(1); }

x((function (d) {
  // d is any
}));
```

**Comment by DanielRosenwasser** [comment]
Yes; parentheses "turns off" contextual typing.

It is definitely something we're aware tends to be a problem for many, and #920 moves to give you the behavior you expect.

**Comment by NN---** [comment]
The problem is that I have code like this:

f((function(d){
}).bind(abc));

I do need parentheses here and then I lose type safety:(

**Comment by CyrusNajmabadi** [comment]
@nn there is nothing we can do in that case.  Contextual typing wouldn't apply anyways as the expression being passed to 'f' is the '.bind' call, not the function expression.

**Comment by NN---** [comment]
I see but in the function itself I expect  parameter "d" to be a number and get an appropriate code completion.
The real case is some class and it is more complicated.

Also there is a workaround specifying type explicitly :

x((function (d:number){
}).bind(abc));

I really would like to make the compiler inferring the type instead of writing by myself.

Thanks .

**Comment by DanielRosenwasser** [comment]
I see - so you want contextual typing to apply simply for the sake of editing prior to the call to `bind`. That's an interesting scenario, but keep in mind that even with the relevant change, if you ever went back to change your function, your parameter would implicitly be typed as `any`.

**Comment by NN---** [comment]
It is pretty annoying but I don't know how to solve it .
I think VS integration could propose a type hint in this case. I mean it can show a  popup suggesting adding explicit types to callback function parameters until there will be a  perfect solution.

**Comment by DanielRosenwasser** [comment]
As a note, compiling with the `--noImplicitAny` flag will appropriately hint that off to you.

**Comment by NN---** [comment]
Thanks.
I didn't notice that it is off by default.

In any case I would like to see some solution for this.
It is very common in JS to use 'bind' function and losing type safety is not a good option.

**Comment by danquirk** [comment]
See https://github.com/Microsoft/TypeScript/issues/212

**Comment by DanielRosenwasser** [comment]
Additionally, we have contextual typing on parenthesized expressions in `master` now.
