### ISSUE TITLE
array.filter() should have an overload for type guards

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/TypeScript#15847]
```ts
const a = [1, '2', 3]; // (number | string)[]
const b = a.filter(el => typeof el === 'number') // still (number | string)[], expected number[]
```
`array.filter()` should have an overload:
```ts
filter(predicate: (el: T, i, arr) => el is R): R[]
```
The same kind of overload is in rxjs' `filter` operator.

**Comment by RyanCavanaugh** [comment]
Please search

![image](https://cloud.githubusercontent.com/assets/6685088/26068202/9a6000dc-3951-11e7-9d01-1ec12e7b3836.png)
