### ISSUE TITLE
The type checker ignores the result of 'typeof' statements assigned to variables

### ISSUE THREAD

**Issue by jsepia** [Microsoft/TypeScript#15859]
**TypeScript Version:**  2.3.2

**Code**

**test.js**
```js
// @ts-check

/**
 * Removes all listeners from a specified event.
 *
 * @param {String|RegExp} [evt] Optional name of the event to remove all listeners for. Will remove from every event if not passed.
 * @return {Object} Current instance of EventEmitter for chaining.
 * @license MIT
 * @see {@link https://github.com/Olical/EventEmitter|EventEmitter by Oliver Caldwell}
 */
function removeEvent(evt) {
  const type = typeof evt
  const events = this._getEvents()

  // Remove different things depending on the state of evt
  if (type === 'string') {
    // Remove all listeners for the specified event
    delete events[evt]
  }
  return this
}
```

**Expected behavior:**
On line 18, the type checker should know that `evt` is a string, from the `if (type === 'string)` in line 16, and it should allow the use of `evt` as an object key.

**Actual behavior:**
Error on line 18, around the variable `evt`: "[js] Type 'RegExp' cannot be used as an index type." This error is unhelpful since we already checked that `evt` is a string in line 16.

**Additional notes:**

This works fine:

```js
// ...
  if (typeof evt === 'string') {
    // Remove all listeners for the specified event
    delete events[evt]
  }
// ...
```

But this doesn't:

```js
// ...
  let type
  if ((type = typeof evt) === 'string') {
    // Remove all listeners for the specified event
    delete events[evt]
  }
// ...
```

And neither does this:

```js
// ...
  let type = typeof evt
  if (type === 'string') {
    // Remove all listeners for the specified event
    delete events[evt]
  }
// ...
```

**Comment by mhegazy** [comment]
This is the same underlying cause as https://github.com/Microsoft/TypeScript/issues/10976. The compiler can not reason about relationship between values in such a fashion.
the fix is to do something like `if (typeof evt === 'string') {`

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
