### ISSUE TITLE
Initialize downlevel rest arguments with 'new Array(...)' instead of an empty array literal

### ISSUE THREAD

**Issue by cevek** [Microsoft/TypeScript#1585]
var args = new Array(arguments.length) is more faster than var args = [];

http://jsperf.com/typescript-rest-operator/3

**Comment by DanielRosenwasser** [comment]
Just to make sure, are you suggesting that for

```TypeScript
function foo(p1, p2, /* ... */ pN, ...rest) {
    // ...
}
```

we'd emit

```JavaScript
function foo(p1, p2, /* ... */ pN) {
    var rest = new Array(arguments.length - N);
    for (var _i = N; _i < arguments.length; _i++) {
        rest[_i - 0] = arguments[_i];
    }
    // ...
}
```

instead of

```JavaScript
function foo(p1, p2, /* ... */ pN) {
    var rest = [];
    for (var _i = N; _i < arguments.length; _i++) {
        rest[_i - 0] = arguments[_i];
    }
    // ...
}
```

?

**Comment by RyanCavanaugh** [comment]
We don't know for sure that the current meaning of `Array` in a function is the global `Array` - it could be shadowed by something else. `[]` is always guaranteed to work.

If your function is actually so performance sensitive as to have this matter, you shouldn't even be allocating an array at all (if possible). You can use the "no rest args in implementation signature" pattern:

```ts
function fn(...args: any[]);
function fn() {
    // Do fast things with 'arguments' here
}
```
