### ISSUE TITLE
`never` type shouldn't be usable to variable and parameter declarations

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#15854]
It means unreachable code. So these declarations are useless and dangerous.

**TypeScript Version:**  2.3

**Code**

```ts
var a: never;
function f(p: never) {}
```

**Expected behavior:**

error

**Actual behavior:**

pass

**Comment by DanielRosenwasser** [comment]
But being able to define `assertNever` is kind of supposed to be a feature to ensure exhaustiveness checking. Check this out:

```ts
function handleMessage(msg: "subscribe" | "unsubscribe") {
    switch (msg) {
        case "subscribe":
        case "unsubscribe":
            console.log("Handled a " + msg);
            return;
        default:
            assertNever(msg);
    }
}

function assertNever(param: never) {
    throw new Error("Unhandled value: \n" + JSON.stringify(param));
}
```

**Comment by mhegazy** [comment]
Looks like a tslint rule rather than a compiler check.
