### ISSUE TITLE
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by aebmknrl** [Microsoft/TypeScript#15864]
**TypeScript Version:**  2.3.2 

**Code**
When start my project

```ts
// A *self-contained* demonstration of the problem follows...

When i run: tsc command, brings me the error:

```
$ npm start

> cayena-oak@1.0.0 start C:\nodejs\project-oak\cayena-front-end
> tsc && concurrently "tsc -w" "lite-server -c my-bs-config.json"

<--- Last few GCs --->

   86704 ms: Mark-sweep 1289.3 (1413.5) -> 1289.3 (1434.5) MB, 2088.6 / 0.0 ms [allocation failure] [GC in old space requested].
   88915 ms: Mark-sweep 1289.3 (1434.5) -> 1289.3 (1434.5) MB, 2211.4 / 0.0 ms [allocation failure] [GC in old space requested].
   91198 ms: Mark-sweep 1289.3 (1434.5) -> 1302.2 (1412.5) MB, 2282.4 / 0.0 ms [last resort gc].
   92864 ms: Mark-sweep 1302.2 (1412.5) -> 1315.0 (1411.5) MB, 1665.8 / 0.0 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

    2: arguments adaptor frame: 3->2
Security context: 0000011CEC1CFB49 <JS Object>
    3: forEach [native collection.js:~335] [pc=0000036ED756E59B] (this=000003EE9BBF2729 <a Map with map 0000033B5280A191>,F=000003EE9BB
F2B31 <JS Function (SharedFunctionInfo 000001F790BC09D9)>,G=0000011CEC104381 <undefined>)
    4: arguments adaptor frame: 1->2
    5: copyEntries [C:\nodejs\project-oak\cayena-front-end\node_modules\typescript\lib\tsc.js:~9...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

```

Please note:
If i run this:

node  --max_old_space_size=4096  ./node_modules/.bin/tsc
This error is not displayed, the memory increases at top level and the .js files are never created. The process keep and keep running (i just left this process running about 1 hour and nothing happens)

My machine specs:

Windows Server 2008 R2
4 GB RAM


**Expected behavior:**

**Actual behavior:**

**Comment by mhegazy** [comment]
Can you share the source of the project that is causing this out of stack space?

**Comment by aebmknrl** [comment]
Thanks for the answer. I have 2 problems with that... 1) The software is propietary and 2) The project is soooo heavy (many files) What specifically do you need to help me?

**Comment by mhegazy** [comment]
can you give `typescript@next` a try, and see if it address your issue?

**Comment by mhegazy** [comment]
if not, then we will need access to the sources to be able to replicate the issue and diagnose the problem. we would be happy to sign any required NDA to get access to the source.

**Comment by aebmknrl** [comment]
Can you please give me the steps to use "typescript@next"? I do:
`npm unistall typescript`

then

`npm install typescript@next` 

and npm marks the "2.4.0..." as 'invalid'

**Comment by mhegazy** [comment]
> and npm marks the "2.4.0..." as 'invalid'

I am guessing you have a peer dependency on TS 2.3 some where. it should still work for the purposes of validation here.

just `npm install typescript@next` and then run `node_modules\.bin\tsc --p <tsconfig.json path>`

**Comment by aebmknrl** [comment]
Ok... this works!... but... i have this command on my package.json:

```
 "scripts": {
    "start": "tsc && concurrently \"tsc -w\" \"lite-server -c my-bs-config.json\" ",
.
.
.
```

How i can replace this with your new command? What this mean? Thanks!!!

**Comment by aebmknrl** [comment]
I mean... i have on my dependencies the 2.3.2 version... how i replace this with this version that is working? I still don't understand why works...

**Comment by mhegazy** [comment]
in your pacakge.json, you have an entry for `typescript`. make that `"typescript": "next"`.

**Comment by mhegazy** [comment]
we are also planning on pushing a new `typescript@2.3.3` later this week with a fix to these issues.

**Comment by aebmknrl** [comment]
Thanks a lot for your help @mhegazy we can close this now! And i wait for the new version...
