### ISSUE TITLE
new A() instanceof A == false?

### ISSUE THREAD

**Issue by impworks** [Microsoft/TypeScript#15875]
**TypeScript Version:**  2.3

**Code**

```ts
class MyError extends Error {
    constructor() {
        super();
    }
}

console.log(new MyError() instanceof Error);
console.log(new MyError() instanceof MyError);
```

**Expected behavior:**
```
true
true
```

**Actual behavior:**
```
true
false
```

This worked fine in Typescript 1.8, but after updating to 2.3 my code silently broke.

The compiler now emits a `return` statement in the constructor code, which breaks the inheritance chain.
Strangely, it only happens with `Error` as base class. If you replace it with any other class replaced in your code, the bug does not reproduce.

**Comment by fis-cz** [comment]
Its documented breaking change.

See https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#extending-built-ins-like-error-array-and-map-may-no-longer-work

**Comment by impworks** [comment]
So, there's no workaround for IE10?
