### ISSUE TITLE
Different bundle behavior when we have .ts files and .d.ts files

### ISSUE THREAD

**Issue by soulcorrosion** [Microsoft/TypeScript#15876]
**TypeScript Version:**  2.2.1

**Code**

I have the following folder structure in my development environment.

```ts
projectB/src/moduleB.ts
packages/projectA/src/moduleA.ts
```

Both projects have the following tsconfig:

```
{
  "compileOnSave": true,
  "compilerOptions": {
    "target": "es5",
    "module": "system",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false,
    "declaration": true,    
    "rootDir": "../"
  },
  "include": [    
    "src/**/*"       
  ]
}
```
projectB is a dependency of projectA via node_modules. If I make a bundle on projectA, I have the following output:

```
System.register("projectA/src/moduleA", ["../projectB/src/moduleB"], function (exports_1, context_1) {
```
The dependency module name which equates to the file path is not OK (../). If I remove the moduleB.ts and leave only the typing file (moduleB.d.ts), then the path becomes "projectB/src/moduleB", which is correct.
Also, if both packages were at the same level, it would also work as expected, even with .ts and .d.ts files present.

**Expected behavior:**
We should get the same behavior when we have .ts files or .d.ts files. 

**Actual behavior:**
If the packages are not at the same level and we have .ts files, the bundle produces wrong names for depenceny modules.

**Comment by mhegazy** [comment]
How are your imports defined? can you share a self contained reproduction of the issue?

**Comment by soulcorrosion** [comment]
Sure, you can find a repo here https://github.com/soulcorrosion/typescriptSimpleProject
On projectA please call 
```
npm install
```
This will link projectA to projectB in node_modules. You can then make the bundle using the target version.
```
tsc --outFile bundle.js
```

Thank you for looking into this. At the moment we have to dive in some regex to make the paths ok, but it would be great if we could avoid it.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Comment by jpsfs** [comment]
@mhegazy
Can you review this please?

@soulcorrosion added more info to the issue after you added the label.
This issue is really annoying, I hope it gets fixed! :)

**Comment by pocesar** [comment]
this shouldn't be closed, I'm having to resort to manually patching the generated files...
