### ISSUE TITLE
Suggest relative paths when showing 'add missing import' code action

### ISSUE THREAD

**Issue by AdamWillden** [Microsoft/TypeScript#15888]
The code action for adding missing imports currently provides a list of possible matches, but all seem to use absolute paths :

![image](https://cloud.githubusercontent.com/assets/4629144/26128528/9a35ff06-3a84-11e7-937c-8248c3e1521c.png)

This will not work for my packages. I would like an additional option which uses a relative path from the current file (i.e. `import { TreeNodeBase } from './tree-node-base';`)

--------------

I'm sure this request must be somewhere in the 2000+ issues but multiple keyword searches has failed to return a result.

**Comment by mhegazy** [comment]
can you share your tsconfig.json?

**Comment by AdamWillden** [comment]
Sure, does that mean it should be supported by my using a `rootDir` removes that support??

```js
{
  "compileOnSave": false,
  "compilerOptions": {
    "rootDir": "src",
    "outDir": "dist",
    "sourceMap": true,
    "inlineSources": true,
    "target": "es2015",
    "module": "es2015",
    "declaration": true,
    "importHelpers": true,
    "noImplicitAny": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "strictNullChecks": true,
    "forceConsistentCasingInFileNames": true,
    "baseUrl": "./",
    "paths": {
      "tslib" : ["jspm_packages/npm/tslib@1.6.0/tslib.d.ts"]
    }
  },
  "exclude": [
    "dist",
    "node_modules",
    "jspm_packages"
  ],
  "filesGlob": [
    "./src/**/*.ts",
    "./test/**/*.ts",
    "./typings/index.d.ts",
    "./custom_typings/**/*.d.ts",
    "./jspm_packages/**/*.d.ts"
  ]
}
```

**Comment by mhegazy** [comment]
I think this is caused by the `baseUrl`, i can not be sure until i look at the whole project. 

`baseUrl` gets a preferential treatment, if the module is under the `baseUrl` it will always use the absolute path. 

A possible fix here is to allow `paths` to be specified without an explicit `baseUrl`, with the value implicitly known to be `./`, and then not using that in the code action. but this seems like a much bigger change.

**Comment by AdamWillden** [comment]
hmm, I'll try to see why I have it in my tsconfig. Hopefully I can remove it and get it working for my use-case...

**Comment by mhegazy** [comment]
> hmm, I'll try to see why I have it in my tsconfig. Hopefully I can remove it and get it working for my use-case...

if you do, you will need to install tslib@1.6.0 to your local `node_modules` instead of using path mapping.

**Comment by aluanhaddad** [comment]
I use a very similar configuration and I really like the current behavior.

With the possible exception of modules that are direct siblings of the current module, I find base URL rooted imports to be much more maintainable.

Sure, they lead to module specifiers that are sometimes a half-dozen characters longer than their relative ones would be, but they are easy to read, and they make reorganization painless.

I feel like it would be strange to have introduce an implicit `--baseUrl` to support a code fix.

**Comment by rosieks** [comment]
I'm using JavaScriptServices template and in my case it adds incorrect import (probably due to incorrect baseUrl) but still in case if I want to add sibling React component that's in the same folder it adds:

    import { LogsList } from 'ClientApp/logs/components/LogsList'

instead of just

    import { LogsList } from './LogsList'

**Comment by whitecolor** [comment]
The problem is that it doesn't work well with `node.js` which can not be tuned (without hacks) to handle import paths.

And relative paths are often preferred.

**Comment by asvetliakov** [comment]
Any news? Autoimports in TS 2.6 are affected by this issue and totally unusable.

**Comment by mhegazy** [comment]
Ideally we do not break the existing use case of baseUrl, one proposal here is to use relative path as long as it is below the baseUrl. in other words, you never need to climb up to the baseUrl directory itself to reach the target, always below it.

**Comment by aluanhaddad** [comment]
I prefer the current behavior.

**Comment by weswigham** [comment]
Why not just provide both options in the code fix list? As far as the typesystem/binder is concerned, if the file is lookupable form either the relative or the absolute path, it's style choice as to which is the preferred result.

**Comment by andy-ms** [comment]
We can provide both but order them based on the heuristic.
