### ISSUE TITLE
Allow properties pane in web projects

### ISSUE THREAD

**Issue by altano** [Microsoft/TypeScript#1588]
Hello,

If I create any of the Node.js web projects (using Node.js Tools for VS), I cannot get the properties pane for TS to show up.  I've tried adding a .ts file to the project but that didn't do the trick.  I also copied over the relevant lines from a blank TypeScript & HTML app, which does have the properties pane, but no matter what I do the TS properties will not show up in the project properties.

Any help?

**Comment by danquirk** [comment]
Did you log any issue on the Node Tools guys? We don't own that tool so if it's for example some bug in the project template or installer we're not able to fix it.

**Comment by altano** [comment]
@danquirk it doesn't work on a new, blank ASP.NET MVC Web Application either, so I don't think it's specific to the Node stuff.  The problem seems to lie elsewhere.

**Comment by danquirk** [comment]
When did this start happening? After some particular update or install? Are you on the latest VS and VS Update?

**Comment by altano** [comment]
No idea when it started.  I'm on VS 2013 Update 4, up to date on everything that I know of.  Let me know if it would be helpful to send you my sln or anything.

**Comment by paulvanbrenk** [comment]
Can you create a new typescript html application, does that work as expected? And does the colorization etc. work in a ts file in a different kind of project?

Do you have just update 4 installed, or did you install TypeScript 1.3 from the VS gallery?

**Comment by altano** [comment]
The TypeScript HTML Application project works fine: I see a property pane labeled "TypeScript Build".

Colorization of TS files works in every project type I've tried, whether or not the property pane is present.  So does build functionality.  It's only the property pane that is missing as far as I can tell.

> Do you have just update 4 installed, or did you install TypeScript 1.3 from the VS gallery?

I don't remember installing TypeScript 1.3 from the VS gallery.  If I did, would it show up in my list of extensions?  Because I don't see it there.

**Comment by altano** [comment]
If it would be helpful I'm happy to share my screen over Lync or whatever.  Let me know.

**Comment by mhegazy** [comment]
With TS 1.8, tsconfig.json can be treated as the main source of configuration even in a project context. see https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#improved-support-for-tsconfigjson-in-visual-studio-2015, though this does not address the original issue, tsconfig.json is the recommended way of managing configuration moving forwards.
