### ISSUE TITLE
Specialized function overloading (type guards)

### ISSUE THREAD

**Issue by olegdunkan** [Microsoft/TypeScript#15885]
Sorry, It maybe duplicate, but I can't find an issue.   
Let we have this code:
```ts
class C {
    x:number;
}
function fn(name:"a" );
function fn(name:"b", x:string );
function fn(name:"c", x:C);
function fn(name:"a"|"b"|"c", x?:string|C) {
    if (name ==="c") {
        x.x = 1; //error     
    }
}
```
We can infer that `x` has `C` type inside `"c" = true` branch of the condition.
Is there special type guard for this case?
If isn't then are there any plans to support this behavior?

**Comment by RyanCavanaugh** [comment]
#14515

**Comment by olegdunkan** [comment]
@RyanCavanaugh thanks
