### ISSUE TITLE
Formatting with multi-line if condition

### ISSUE THREAD

**Issue by ghost** [microsoft/TypeScript#15895]
**TypeScript Version:**  nightly (2.4.0-dev.20170516)

**Code**

Type:

```ts
if (a
    && b) {
```

Hit enter. Type `return true;`. Hit enter. Type `}`.

**Expected behavior:**

```ts
if (a
    && b) {
    return true;
}
```

**Actual behavior:**

```ts
if (a
    && b) {
        return true;
    }
```

**Comment by SaschaNaz** [comment]
This is a regression from some point of 2.2-2.4.

**Comment by RyanCavanaugh** [comment]
Closing due to lack of interest
