### ISSUE TITLE
private/protected member and "this" type for functions 

### ISSUE THREAD

**Issue by shlomiassaf** [Microsoft/TypeScript#15892]
**TypeScript Version:**  2.32

**Code**

```ts
class MyClass {
  private x: number;
  protected y: number;
  public z: number;
}

function temp(this: MyClass): void {
  this.x // type error
  this.y // type error
  this.z // ok
}
```

There is no expected / unexpected behaviour here...

When using a context (this) type for a function where the this type is a class one can not access private/protected members.

At first this is reasonable, but when thinking about composition/mixins etc, it is common to access properties on the class, changing internal values of the root mixinto class (which holds state) .

A plugin might want to change internal values that are not exposed to the end user but only to mixins...

I understand the security concerns, so "private" members shouldn't get access, but for **protected** properties, there is some logic in exposing it.

Working around the issue, while preserving types, is not difficult but does have some runtime cost...

```ts
class MyClassB extends MyClass {
  static temp(this: MyClassB): void {
    this.x // type error
    this.y // ok
    this.z // ok
  }
}
```
now MyClassB.temp can be assigned to a mixin or composed, etc...

Seems like exposing the protected properties also aligns with the workaround, it's doable anyway.

Can you expose **protected** properties in this function type.

**Comment by mhegazy** [comment]
it boils down to what `private` and `protected` mean. From the [spec](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#822-accessibility)

> Private property members can be accessed only within their declaring class. Specifically, a private member M declared in a class C can be accessed only within the class body of C.
> Protected property members can be accessed only **within their declaring class** and classes derived from their declaring class, and a protected instance property member must be accessed **through an instance of the enclosing class or a subclass thereof**. Specifically, a protected member M declared in a class C can be accessed only within the class body of C or the class body of a class derived from C. Furthermore, when a protected instance member M is accessed in a property access E.M within the body of a class D, the type of E is required to be D or a type that directly or indirectly has D as a base type, regardless of type arguments.

not honoring these rules, renders these modifiers meaningless.

> I understand the security concerns, so "private" members shouldn't get access, but for protected properties, there is some logic in exposing it.

this is not really about privacy or security. it is just that the whole oop encapsulations do not make much sense with the mixin patterns. i would recommend just using public for these case.

**Comment by shlomiassaf** [comment]
Ok, thanks!
