### ISSUE TITLE
for…of through Map broken if target is "es5"

### ISSUE THREAD

**Issue by evgenymarkov** [Microsoft/TypeScript#15891]
**TypeScript Version:**  2.3.2

**Code**

```ts
this.edges = new Map();
...
for (let [key, value] of this.edges) {
    console.log(this.edges);
    if (value.has(nodeId)) {
        value.delete(nodeId);
        if (value.size === 0) {
            this.edges.delete(key);
         }
         console.warn(`Edge from ${key} to ${nodeId} implicitly removed.`);
    }
}
```

**Expected behavior:**
If transpilation target is "es5" tsc will generate wrong code where loop doesn't iterate over `this.edges` because length field in generated object `_a` doesn't exist.
**Actual behavior:**
Generated code should loop through array as expected.

I've prepared the repository to easily check the bug: https://github.com/evgenymarkov/forof-bug

**Comment by mhegazy** [comment]
use [`--downlevelIteration`](https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#new---downleveliteration).

Normally the compiler would give you an error about that, but errors are suppressed by default in .js files.
