### ISSUE TITLE
Wrong union type matching

### ISSUE THREAD

**Issue by dfilatov** [Microsoft/TypeScript#15907]
**TypeScript Version:**  2.3.2

**Code**

```ts
type Action = { type: 'activate' } | { type: 'disactivate' };

function dispatchAction(action: Action): void {

}

const active = true;

dispatchAction({ type : (active? 'disactivate' : 'activate') });
```

**Expected behavior:**
Everything is correct. And if I change last line to:
```ts
dispatchAction(active? { type : 'disactivate' } : { type : 'activate' });
```
then no errors will be produced.

**Actual behavior:**
Error:
Argument of type '{ type: "activate" | "disactivate"; }' is not assignable to parameter of type 'Action'.
  Type '{ type: "activate" | "disactivate"; }' is not assignable to type '{ type: "disactivate"; }'.
    Types of property 'type' are incompatible.
      Type '"activate" | "disactivate"' is not assignable to type '"disactivate"'.
        Type '"activate"' is not assignable to type '"disactivate"'.

**Comment by ahejlsberg** [comment]
This is working as intended. I would suggest writing the declaration of type `Action` as follows to clearly indicate that the `type` property has two possible values regardless of the rest of the properties:

```ts
type Action = { type: 'activate' | 'disactivate' };
```

In general, the unification you propose is only possible for a small subset of types. See my comment in #12052.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
