### ISSUE TITLE
Using spread operator breaks typechecking

### ISSUE THREAD

**Issue by huesforalice** [Microsoft/TypeScript#15908]
My apologies if this has been reported before, I have done a search of the issues, and with the keyword spread this has not come up. I also believe that this functionality worked in TS 2.1 but is now broken. 

**TypeScript Version:**  2.3.2 

**Code**

```ts
interface ICar {
  wheels: number
  brand: string
}

let car:ICar = {
  wheels: 4,
  brand: 'volvo'
}

car = {
  ...car,
  legs: 5 // this should not work
}
```

**Expected behavior:**
Compile error when trying to add the legs attribute to a variable of type ICar.

**Actual behavior:**
Will compile and add the faulty attribute

**Comment by mhegazy** [comment]
We did discuss this in https://github.com/Microsoft/TypeScript/issues/14853 and the decision was to flag these as errors.

**Comment by huesforalice** [comment]
Hey @mhegazy , thanks for getting back to me so promptly. Great to hear that it is in the roadmap.
