### ISSUE TITLE
Comments next to functions, if, ... are not accessible in transfoms

### ISSUE THREAD

**Issue by thomaspink** [microsoft/TypeScript#15900]
Comments next to functions/if/... declarations are not accessible through `forEachLeadingCommentRange` or `forEachTrailingCommentRange`.

**TypeScript Version:**  2.3.0 / nightly (2.2.0-dev.201xxxxx)

**Code**

```ts
function test() { // this comment is not accessible
    const a = true;
    console.log(a);
    console.log('saf'); // this one is fine
    if(a) { // this comment is also not accessible
        console.log(a); // this is also fine
    }
}
```

**Expected behavior:**
When you look at the example above, my assumption on how to get the comments next to the function of if would be calling `forEachTrailingCommentRange` with the functions node `getEnd()` position.
**Actual behavior:**
No comments are return when calling these functions.

**Info:**
This issue could be related to #11046

PS:
Keep up the good work. <3 Typescript

**Comment by thomaspink** [comment]
**UPDATE:**
Found more comment position that are not accessible with this functions

```ts
function test() {
    const a = true;
    console.log(a);
    console.log('saf');
    if(a) {
        console.log(a);
    } // this comment is not accessible
  // also this one
}
// and this on is also not accessible
```

**Comment by DanielRosenwasser** [comment]
The problem is that the comments belong to the *tokens to the left of them* if they reside on the same line. Unfortunately, without the language service API augmentations, there's no way to dive in and grab the tokens and get their trivia with the same API.

It sucks as a workaround, but what you can do is create a trivia-aware scanner with

```ts
ts.createScanner(ts.ScriptTarget.Latest, /*skipTrivia*/ false, /*... other arguments here... */)
```

until you stop getting trivia tokens.

Maybe @rbuckton or @mhegazy have a better workaround.

**Comment by thomaspink** [comment]
@DanielRosenwasser thanks for the response. 
* Is there a documentation on how to implement such a scanner? 
* Do i also have to implement a complete new scanner or what is the best practice (so i won't run into issues with future typescript versions)?

**To give a bit of context on our problem so it get a bit clearer and we can better discuss workarounds or other solutions:**
We want to run our js-codebase(with jsdoc type information) trough the typescript compiler (with turned on @ts-check) so we get all the benefits of a typed environment and then maybe incrementally switch to a full typescript codebase.
Our code has some (java-like) annotations in comments (like `// #DEBUG`). We then need to change the code depending on the annotation and the environment.
E.g.: 
If a line has the `#DEBUG` flag, we remove this line in the production version
If there are a `#DEBUG:BEGIN` and a `#DEBUG:END` annotations, we remove all the code between them. Example: 
```ts
function test() {
    const a = true;
    console.log(a); // #DEBUG
    console.log('saf');
    // #DEBUG:BEGIN
    if(a) {
        console.log(a);
    }
  // #DEBUG:END
}
```
There are also annotations that transform the code (like wrap it in a try an catch).

Right now this is done with string search and replacements. As this is very error prone we want to make use of the information a AST can give us.
So we need a way to get all the annotations in comments assign them to nodes.
Ideally there is a way to run over the tree, get the comments/annotations and set them as flags on the node:

```ts
```
