### ISSUE TITLE
Optionality not honored using @property tags

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#15916]
Courtesy of @MikeyBurkman, reported in https://github.com/Microsoft/TypeScript/issues/11597#issuecomment-302213303

```js
/**
 * @typedef {Object} Opts
 * @property {string} x
 * @property {string=} y
 * 
 * @param {Opts} opts
 */
function foo(opts) {
  console.log(opts);
}

foo({x: 'abc'});
```
That call to foo() will be flagged because it's missing `y` in the opts. The type checker does not recognize any of the methods of specifying optional parameters listed on the [wiki](https://github.com/Microsoft/TypeScript/wiki/JsDoc-support-in-JavaScript). I even tried doing TS-style using `@property {string?} y` and still no luck.

**Comment by yuit** [comment]
Note: we should make sure that quick-info reflect the optionality as well
