### ISSUE TITLE
Should createTypeAliasDeclaration have decorators/modifiers arguments?

### ISSUE THREAD

**Issue by phated** [Microsoft/TypeScript#15918]
**TypeScript Version:**  nightly (2.4.0-dev.20170517)

**Code**

```ts
// A *self-contained* demonstration of the problem follows...

// Unable to add `export` this Type Alias
var typeDef = ts.createTypeAliasDeclaration(
  'myType',
  ts.createKeywordTypeNode(ts.SyntaxKind.StringKeyword)
);
```

**Expected behavior:**
Should be able to add an export modifier to the node.

**Actual behavior:**
This API doesn't seem to have the same signature as `createInterfaceDeclaration` or `createEnumDeclaration`, etc.  Should it have `decorators` and `modifiers` parameters like the other APIs?

I'm willing to send a PR if so.

**Comment by mhegazy** [comment]
PRs welcomed.

**Comment by phated** [comment]
Thanks for the response.  PR submitted.
