### ISSUE TITLE
Plugins - support plugin specific logging

### ISSUE THREAD

**Issue by egamma** [Microsoft/TypeScript#15913]
The tslint language server plugin has to handle the situation that a `tslint.json` file cannot be read. The tslint API to get the configuration returns an exception in this case. There needs to be a way to show the exception to the user. The VS Code tslint extension shows this exception in the tslint output channel, see the screenshot below.

![image](https://cloud.githubusercontent.com/assets/172399/26172249/09fd9f60-3b48-11e7-9125-2a22a11332f1.png)

A plugin has access to the TS logger `info.project.projectService.logger`, but this log is intended for plugin authors to trace the execution of a plugin. It is not intended to be shown and understood by the end user.

What would be needed is an API that allows a plugin to send a log message event under a particular topic to the language server client. A client like VS Code can then append this message to a plugin specific output channel, in this case to the tslint channel.

// fyi @mjbvz

**Comment by alexwalter88** [comment]
I was just bit by this: palantir/tslint#3063. Would have certainly have saved me some time had I been able to see errors logged from the plugin.

**Comment by RyanCavanaugh** [comment]
Doesn't seem to be much demand for this
