### ISSUE TITLE
Plugins - notify a plugin when a tsconfig.json file changes

### ISSUE THREAD

**Issue by egamma** [Microsoft/TypeScript#15915]
A plugin can define plugin specific properties in the `plugin` section of the `tsconfig.json` file. When the user edits a `tsconfig.json` then the plugin should be notified so that it can react to setting changes.

**Comment by mhegazy** [comment]
Piping events from tsserver to the plugin regarding changes to the config file that in sections that do not touch project configuration requires some reworking of the server. Today we make multiple assumptions about what changes require a requery for errors vs others. It also seems that the plugins in general need to monitor other files, e.g. `tslint.json` for the tslint plugin. I would recommend adding a file watcher on the tsconfig.json as well, and triggering a refresh of errors if the lint configuration section changes. With https://github.com/Microsoft/TypeScript/issues/15914 in (PR: https://github.com/Microsoft/TypeScript/pull/23824), the plugin should be able to trigger a refresh to errors using `project.refreshDiagnostics`.

**Comment by egamma** [comment]
@mhegazy having the plugin watch the tsonfig.json makes sense. Is there a way for a plugin to find out which tsconfig.json file should be watched?

**Comment by mhegazy** [comment]
Calling `getProjectName` on a `ConfiguredProject` should give you the path to the `tsconfig.json`/`jsconfig.json` file path. The path is also stored on `CompilerOptions.configFilePath` ( that is an internal property, so does not show in the .d.ts, but we can make it visible through a helper).
