### ISSUE TITLE
[Proposal] Allow ES5 setters to support super-types of their getters

### ISSUE THREAD

**Issue by sean-vieira** [Microsoft/TypeScript#15919]
**TypeScript Version:** 2.3.1-insiders.20170416 (from the playground)
**Flags:** `--strictNullChecks`

#### Code

```ts
const thing = {
    _backingBean: "",
    get magicBeans(): string {
        return this._backingBean;
    },

    // ERROR: 'get' and 'set' accessor must have the same type.
    // (property) magicBeans: string
    set magicBeans(newValue: string | null) {
        this._backingBean = newValue == null ? "" : newValue;
    }
}

const aString: string = thing.magicBeans;
// ERROR: Type 'null' is not assignable to type 'string'.
thing.magicBeans = null;
thing.magicBeans = "";

```

#### Expected behavior

Allowing for "be lenient in what you accept, strict with what you send", super-types of the getter's return type in an ES5 getter / setter pair should be allowed in the setter's argument.  This is already possible with informal get / set methods, and is required to type certain portions of the DOM specification correctly (hat tip @SaschaNaz in #15834)

#### Actual behavior

Errors are thrown at the `get` / `set` declarations and at any place the setter is invoked.

**Comment by RyanCavanaugh** [comment]
See #2521
