### ISSUE TITLE
Arrow functions attached to a `const` compiled to ES5 should be named

### ISSUE THREAD

**Issue by davetayls** [Microsoft/TypeScript#15927]
**TypeScript Version:**  2.3.2

**Code**

```ts
const myName = () => 'hello';
```

**Expected behavior:**

The resulting es5 JavaScript should be

```javascript
var myName = function myName() { return 'hello'; };
```

**Actual behavior:**

```javascript
var myName = function () { return 'hello'; };
```

**Comment by MasterCassim** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/15871

**Comment by davetayls** [comment]
Thanks @MasterCassim I didn't find those in my search
