### ISSUE TITLE
Missing `error` event

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#15921]
In Global scope objects.

https://html.spec.whatwg.org/multipage/indices.html#event-error

**TypeScript Version:**  master

**expected**

```ts
interface WindowEventMap {
  "error": ErrorEvent;
}
```

**Comment by falsandtru** [comment]
Also see https://github.com/Microsoft/TSJS-lib-generator/issues/261

**Comment by falsandtru** [comment]
@mhegazy @RyanCavanaugh ?

**Comment by mhegazy** [comment]
Fixed by https://github.com/Microsoft/TSJS-lib-generator/pull/262
