### ISSUE TITLE
[JSDoc] Cannot assign array of string to array of literal type.

### ISSUE THREAD

**Issue by pc-lover** [Microsoft/TypeScript#15929]
**TypeScript Version:**  2.3.2

**Code**
Using TypeScript to check JavaScript code (`allowJs` and `checkJs` enabled)
```js
/** @type {("foo" | "bar")[]>} */
const test = ["foo", "bar"];
```

**Expected behavior:**
No errors occur.

**Actual behavior:**
```
Type 'string[]' is not assignable to type '("foo" | "bar")[]'.
Type 'string' is not assignable to type '"foo" | "bar"'.
```

**Comment by mhegazy** [comment]
Should be tracked by https://github.com/Microsoft/TypeScript/issues/15618#issuecomment-300632637

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
