### ISSUE TITLE
Generic constraint not playing well with new 'object' type.

### ISSUE THREAD

**Issue by indiescripter** [Microsoft/TypeScript#15920]
**TypeScript Version:**  Version 2.4.0-dev.20170517

In the code below, I am am uncertain if this is a bug or a misunderstanding on my part to do with the new, more restrictive, 'object' type.

**Code**

```ts
// The following produces a compiler error:
//   Type 'A & B' does not satisfy the constraint 'Base'.
//   Type 'A & B' is not assignable to type 'object'.
//   (type parameter) B in foo<A extends Base, B extends Base>(): Foo<Base, A & B>
//
type Base = boolean|object;

type Foo<DOM, CODOM extends DOM> = (dom: DOM) => CODOM;

function foo<A extends Base, B extends Base>(): Foo<Base, A & B>    // <= error at A & B
{
  return <any> function(x: Base) { return x; };
}


// Removing the constraint on CODOM in type Foo2 and
// all is well.
//
type Base2 = boolean|object;

type Foo2<DOM, CODOM> = (dom: DOM) => CODOM;    // <= "fixed" by removing extends DOM

function foo2<A extends Base2, B extends Base2>(): Foo2<Base2, A & B>
{
  return <any> function(x: Base2) { return x; };
}


// All can also be made well by changing object to Object in
// type Base3.
//
type Base3 = boolean|Object;  // <= also "fixed" by resorting to 'Object' instead of 'object'

type Foo3<DOM, CODOM extends DOM> = (dom: DOM) => CODOM;

function foo3<A extends Base3, B extends Base3>(): Foo3<Base3, A & B>
{
  return <any> function(x: Base2) { return x; };
}
```

**Comment by ahejlsberg** [comment]
A simpler repro:

```ts
function f<A extends object | boolean, B extends object | boolean>(x: A & B) {
    let z: object | boolean = x;  // Error here
}
```

The issue relates to how we break down union and intersection types in type relationship checking. We always first break down union types, i.e. we check that `A & B` is assignable to `object` or `boolean`. Neither of those are true (because, for example, `A` could be a `boolean` which isn't assignable to `object`). Effectively, when checking the constraints, we end up with union types sitting below an intersection type, which produces wrong results. In order to solve this we would have to "lift" the constraints up and distribute the `&` operator over any `|` operators in the constraints. It's doable, but not trivial.

**Comment by ahejlsberg** [comment]
See #11717 for context on union/intersection normalization.

**Comment by indiescripter** [comment]
Thanks @ahejlsberg for quick response & right from the top!

Coming in completely cold on the TS compiler internals, I've spent a bit of time perusing checker.ts to get a handle on the "doability" of a fix for this; it could be an interesting challenge. To that end, I would be interested if you are able to expand upon the non-trivialities that perceive now that I am more likely to understand portions of the checker.ts code that you might mention. I'm feeling(and hope) that the fix would more-or-less be confined to checker.ts -- please enlighten me otherwise.

Having said that, I guess I should ask if a PR would be welcome on this issue, say, unless checker.ts code is sacrosanct.

May I say, as an outside observer, that there are tons of typecasts going on in checker.ts code that would disappear if a serious effort was put into welcoming TypeScript's excellent 'is type' guard feature in the code which, in its current state, is tightly coupled to TypeFlag bit field tests. Confession -- I've put in quite a few hours over this last weekend as an investigative exercise to get a feeling for how much type guards would improve the readability of checker.ts code. Result: the code feels a lot, lot cleaner and also a number of dubious and redundant typecasts were found in that exercise. Would you be interested in receiving a PR for this code readability/robustness/quality improvement -- perhaps as a first step towards a complete fix for this issue?

Justin Johansson
