### ISSUE TITLE
Error recognizing string literal type

### ISSUE THREAD

**Issue by Zarel** [Microsoft/TypeScript#15925]
**TypeScript Version:**  nightly (2.4.0-dev.20170516)

**Code**

```ts
/** @typedef {'Pokedex' | 'FormatsData' | 'Learnsets' | 'Movedex' | 'Statuses' | 'TypeChart' | 'Scripts' | 'Items' | 'Abilities' | 'Natures' | 'Formats' | 'Aliases'} DataType */
/** @type {DataType[]} */
const DATA_TYPES = ['Pokedex', 'FormatsData', 'Learnsets', 'Movedex', 'Statuses', 'TypeChart', 'Scripts', 'Items', 'Abilities', 'Natures', 'Formats', 'Aliases'];
```

**Expected behavior:**
No error

**Actual behavior:**
> sim/dex.js(87,7): error TS2322: Type 'string[]' is not assignable to type '("Pokedex" | "FormatsData" | "Learnsets" | "Movedex" | "Statuses" | "TypeChart" | "Scripts" | "It...'.
> 
>  Type 'string' is not assignable to type '"Pokedex" | "FormatsData" | "Learnsets" | "Movedex" | "Statuses" | "TypeChart" | "Scripts" | "Ite...'.

This code doesn't seem to be an error if I leave it alone in its own file, but for some reason, when part of a larger file, it's telling me something is wrong.

This can be reproduced in https://github.com/Zarel/Pokemon-Showdown/tree/149ca3759c141085d2f473fc9fdc5da5371ef32c

**Comment by mhegazy** [comment]
Looks like the same issue as https://github.com/Microsoft/TypeScript/issues/15618#issuecomment-300632637 and https://github.com/Microsoft/TypeScript/issues/15929

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
