### ISSUE TITLE
Do Not Return Completions When Writing a Property Name

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#15937]
From: https://github.com/Microsoft/vscode/issues/26857

**TypeScript Version:**  2.3.3-insiders

**Code**

```ts
let something;
class Test {
	public some|
}
```

Trigger a completions request at `|`

**Expected behavior:**
Because we are writing a property definition, no completions should be returned

**Actual behavior:**
All the normal completions are returned:

```
[Trace  - 12:56:17 PM] Sending request: completions (69). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/Users/matb/projects/sand/lot.ts",
    "line": 3,
    "offset": 13
}
[Trace  - 12:56:17 PM] Response received: completions (69). Request took 14 ms. Success: true 
Result: [
    {
        "name": "AAGUID",
        "kind": "type",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "ANGLE_instanced_arrays",
        "kind": "interface",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    {
        "name": "AbstractWorker",
        "kind": "interface",
        "kindModifiers": "declare",
        "sortText": "0"
    },
    ...
```

**Comment by sheetalkamat** [comment]
With the change to show modifiers and inherited members (#15614) currently the completion list contains the keywords like modifiers in the completion. Do we not show those either when writing identifier? It would be little difficult to identify if user meant to write say another modifier/keyword like in below eg, it could be that user is writing get keyword?

```typescript
class Test {
  public g/*completion here*/
}
```

**Comment by mhegazy** [comment]
the one i tried was even afer the method name.. e.g.

```ts
class Test {
  public g      /*here*/
}
```
