### ISSUE TITLE
Visual Studio 2017: error is being reported after it already fixed

### ISSUE THREAD

**Issue by odrozd** [Microsoft/TypeScript#15939]
**TypeScript Version:**  2.2.1
**Visual studio Version** 15.2(26430.6)

**Description:**
Periodically typescript errors doest disappear from VS error list window even after its already fixed and build is successful. This kind of errors disappear only after VS restart. 

This behavior is happening from time to time with different circumstances and conditions thus I don't have guaranteed steps to reproduce.

**Comment by odrozd** [comment]
I could not reproduce this issue anymore on latest VS 2017 15.3 Release, guess this issue could be closed

**Comment by mhegazy** [comment]
thanks!
