### ISSUE TITLE
How to call classes and function in type definition file?

### ISSUE THREAD

**Issue by alialrabi** [Microsoft/TypeScript#15936]
**TypeScript Version:**  2.2.1 / nightly (2.2.0-dev.201xxxxx)

**Code**
        
index.d.ts

        export as namespace mydefinition;

          export namespace mynamespace {

            interface Myinterface {
               width: number;
               height: number;
             }  

            class MyClass {
                  constructor(attributes?: any);
                  addCell(cell: Cell): this; 
               }
           }

app.ts

            import { mydefinition } from 'definitionfile';

            let x=new dia.Graph();
            let p=new dia.Paper("paper");
```ts
```

**Expected behavior:**

call classes and function

**Actual behavior:**
 client?afea:119 ./src/main/webapp/app/entities/model/model-detail.component.ts
Module not found: Error: Can't resolve 'definitionfile' in '/home/ali/git/gateway/src/main/webapp/app/entities/model'
 @ ./src/main/webapp/app/entities/model/model-detail.component.ts 16:16-34
 @ ./src/main/webapp/app/entities/model/index.ts
 @ ./src/main/webapp/app/entities/model/model.module.ts
 @ ./src/main/webapp/app/entities/entity.module.ts
 @ ./src/main/webapp/app/app.module.ts
 @ ./src/main/webapp/app/app.main.ts
 @ multi (webpack)-dev-server/client?http://localhost:9060 webpack/hot/dev-server ./src/main/webapp/app/app.main

**Comment by RyanCavanaugh** [comment]
This is not a support forum.
