### ISSUE TITLE
Mixins should be able to conditionally inspect `super` for properties/methods

### ISSUE THREAD

**Issue by JanMiksovsky** [Microsoft/TypeScript#15942]
It does not seem possible to write mixins that conditionally inspect `super` for the existence of particular properties or methods.

As an example, a mixin wants to implement a `greet` method that checks to see if `super` implements `greet` and _if and only a base implementation exists_ invoke `super.greet()`. This ensures that the mixin augments (rather than overrides) any greet behavior provided by other mixins, while allowing for the possibility that no other base implementation may exist.

    type Constructor<T> = new(...args: any[]) => T;

    export default function GreetMixin<T extends Constructor<{}>>(Base: T): T {
      return class Greet extends Base {
        greet() {
          if (super.greet !== undefined) { super.greet(); }  // TypeScript error
          console.log('Hello, world!');
        }
      }
    }

**Actual result:** At the commented line, the TypeScript compiler complains, "Property 'greet' does not exist on type '{}'." That statement is literally true, but doesn't allow for the _possibility_ that the base class supplied to the mixin is a class that does, in fact, implement `greet`. Because `super` is a special syntax construction, we can't skirt type-checking via something like `(<any>super).greet`.

**Expected result:** We'd like for some form of type guard on `super` (e.g., as shown above) to work, or for TypeScript to provide some other means of conditionally obtaining information about the base class type `T`.

Why this matters: We have a [web components library](https://elix.org) that makes extensive use of mixins. Multiple mixins are typically applied to the `HTMLElement` base class to create a given component class. Multiple mixins may each want to perform work when, for example, a given method is invoked. Because our mixins all work with `HTMLElement`, we'd prefer to be able to employ type checking with generic constraints like `<T extends Constructor<HTMLElement>>` (instead of `<T extends Constructor<any>>`), so that we can get type-checking on the known members of `HTMLElement`.

The project's [conventions](https://elix.org/documentation/mixins#composition-rules-for-mixin-methods-and-properties) hold that each mixin method and property implementation must take care to cooperatively invoke any corresponding implementation further up the prototype chain. We've found this pattern of conditional `super` invocation to be quite powerful, and would be interested in seeing some means to support such mixins in TypeScript.

**Comment by DanielRosenwasser** [comment]
First off: I don't think you want to return `T` on `GreetMixin`. It is less-specific than the type of `Greet` itself.

Second, it sounds like you want `T` to extend `Constructor<MaybeGreetable>` like in the following:

```ts
type Constructor<T> = new (...args: any[]) => T;

interface MaybeGreetable {
    greet?(): void;
}

export default function GreetMixin<T extends Constructor<MaybeGreetable>>(Base: T) {
  return class Greet extends Base {
    greet() {
      if (super.greet !== undefined) { super.greet(); }  // TypeScript error
      console.log('Hello, world!');
    }
  }
}


class Base {
    // ...
}

class Derived extends GreetMixin(Base) {
    hai() {
        this.greet();
    }
}
```

**Comment by JanMiksovsky** [comment]
@DanielRosenwasser That appears to meet our needs. Thanks.
