### ISSUE TITLE
Confusing error message for await expression

### ISSUE THREAD

**Issue by ikokostya** [Microsoft/TypeScript#15943]
**TypeScript Version:**  2.3.1

**Code**

```ts
function foo() {
    await 1;
}
```

**Expected behavior:**

Error with message like in the following code example:

```ts
function foo() {
    await Promise.resolve(1);
}
```

```
a.ts(2,5): error TS1308: 'await' expression is only allowed within an async function.
```

**Actual behavior:**

Error with confusing message:

```
a.ts(2,11): error TS1005: ';' expected.
```

**Comment by DanielRosenwasser** [comment]
I think the reason you get the error in the first place is a heuristic in place, which should probably be expanded from just identifiers - string/numeric/boolean literals would be a good first start. If you'd like to send a pull request, we'd definitely be willing to take one, and I think this one would be relatively approachable. 😃

**Comment by suhasdeshpande** [comment]
@DanielRosenwasser Any direction on where would be the right place to tackle this? I would love to take this.

**Comment by suhasdeshpande** [comment]
@nowy Let me take a stab at it. I will update you in asap.

**Comment by ikokostya** [comment]
Similar to issue with [yield expression](https://github.com/Microsoft/TypeScript/issues/15981) there are additional cases:

```ts
function foo() {
    await 'foo';
}
```

```
t.ts(2,11): error TS1005: ';' expected.
```

***

```ts
function foo() {
    await (1 + 2);
}
```

```
t.ts(2,5): error TS2304: Cannot find name 'await'.
```

**Comment by nowy** [comment]
@suhasdeshpande no problem!

**Comment by DanielRosenwasser** [comment]
I would not handle the `await (1 + 2)` case, as that is a valid production.

**Comment by charlespierce** [comment]
PR opened to resolve this issue: #16213

**Comment by charlespierce** [comment]
@DanielRosenwasser Would it be possible to get a review of the above PR #16213? I'd like to make sure that I'm on the right track with the necessary changes.

**Comment by DanielRosenwasser** [comment]
Thank you @charlespierce and sorry about the delay! You should see the changes effective in our next nightly, and in 2.5 as well. I'm not sure whether @rbuckton or @mhegazy would want this in 2.4, but if so you can send a PR to `release-2.4`.
