### ISSUE TITLE
Are there any tools available to export the cyclomatic complexity of code ( typescript code ) ?

### ISSUE THREAD

**Issue by deepakmhr** [Microsoft/TypeScript#15948]
I am using vscode with tslint extension installed and I want to export cyclomatic complexity of the code, are there any tools/extensions available in the market for the same ?

Please help.

**Comment by andy-ms** [comment]
https://palantir.github.io/tslint/rules/cyclomatic-complexity/
This doesn't *export* the cyclomatic complexity, it just lints for it. Not sure what you mean by export.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
