### ISSUE TITLE
type guards are not working in this case

### ISSUE THREAD

**Issue by bpasero** [Microsoft/TypeScript#1595]
I am using the following example that I took directly from the blog post (http://blogs.msdn.com/b/typescript/archive/2014/11/18/what-s-new-in-the-typescript-type-system.aspx)

```
var x: any = "foo";
if(typeof x === 'string') {
   console.log(x.subtr(1)); // Error, 'subtr' does not exist on 'string'
}
// x is still any here
x.unknown(); // OK
```

I am not seeing the error or intellisense for the console.log statement.

Are type guards actually supported in this case or only for union types?

**Comment by ahejlsberg** [comment]
Type guards do not affect variables of type `any`. This is a fairly recent change, see #1426 and #1433.

@jonathandturner We should probably update the example in the blog post.

**Comment by jonathandturner** [comment]
As per conversation off-line yesterday, I think this should continue to give the more specific type.  With simple types like 'string' we have a complete picture of what the user should be able to do in the if-block.

**Comment by RyanCavanaugh** [comment]
Strong agreement that we should narrow expressions of type `any` when there is a type guard for a primitive type (`typeof x === 'string'`), but not in other cases (`x instanceof foo`).

**Comment by bpasero** [comment]
Thanks!
Am 09.01.2015 00:57 schrieb "Anders Hejlsberg" <notifications@github.com>:

**Comment by bpasero** [comment]
Btw what is the rationale to not also support this in instanceof blocks?

**Comment by danquirk** [comment]
#1426 has a specific example of the general class of issues with that case.

**Comment by bpasero** [comment]
While I understand this for doing "instanceof Object", I cannot think of a usecase where I do "instanceof MyClass" where I would not want an error to show up when I use a property that does not exist?

**Comment by bpasero** [comment]
Also: If I explicitly assign "any" to a type, this is a good indication that I want the type to be any and no errors should show up. But when the type is simply having "any" by default because I did not set a type, you should support type guards.

**Comment by jonathandturner** [comment]
@bpasero - If you're a subclass of MyClass, then instanceof the parent class will be true.  This means, we can't say for sure that any property doesn't exist, because it may exist on the subclass. 

The net result is that we may error on perfectly valid, and correct, code.  We're trying to avoid that with type guards.

**Comment by bpasero** [comment]
I disagree. If I check of instance for a super class of my type, I should
not be allowed to use properties of any class that is below that level,
otherwise I would have checked for that class in the first place.
Typescript should be all about discouraging unsafe, untyped access to an
object.
Am 12.01.2015 18:20 schrieb "Jonathan Turner" <notifications@github.com>:
