### ISSUE TITLE
Argument of type '1' is not assignable to parameter of type 'boolean'.

### ISSUE THREAD

**Issue by jhpratt** [Microsoft/TypeScript#15956]
**TypeScript Version:**  2.3.2

**Code**
As expected. Function with boolean parameter, with another function sending `1`.

**Expected behavior:**
Successful transpilation. Using 1 to represent true is very common practice.

**Actual behavior:**
Error.

**Comment by DanielRosenwasser** [comment]
That seems unnecessarily permissive and probably isn't helpful for readability anyway. Just use `true` or even `!!1` if you feel particularly rebellious.
