### ISSUE TITLE
TypeScript allows one to declare a variable's type to be a number literal

### ISSUE THREAD

**Issue by rollandjb** [Microsoft/TypeScript#15952]
TypeScript allows a variable's type to be a number literal

**TypeScript Version:**  2.2.3

**Code**

```ts
// TypeScript allows the declaration of a variable of type 42
let x: 42;

// AND, you can assign xx to 42 ...
xx = 42;

// ... and only 42
xx = 43;
```

**Expected behavior:**
Compile error

**Actual behavior:**
No compile error

**Comment by rollandjb** [comment]
... And also a string literal

```
let ss: "Hello, World";
ss = "Hello World"; // Gives compiler error Type '"Hello World"' is not assignable to type '"Hello, World"'.
```

**Comment by krryan** [comment]
Number literal and string literal types are features, not bugs—very, very powerful features, at that.

**Comment by rollandjb** [comment]
@RyanCavanaugh: So at first I was puzzled by your response, then noticed my typo with the string example I gave, which then led to this example:

```
type Colors = "Red" | "Green" | "Blue";

let color: Colors; // Can only be one of the values "Red", "Green" or "Blue"

color = "Red";
color = "Green";
color = "Blue";

color = "Orange"; // Not allowed
```

That is a great feature!

Are there other usage scenarios you might suggest?

**Comment by krryan** [comment]
I mean, that's the gist of it, you can use it to restrict the valid options for a parameter. Can be used to document/enforce the range of values for API values (for instance, I have an interface which includes `status: 'PUBLIC' | 'PRIVATE';` because the server-side folks have told me that those are the values that response can have), for standardized error messages, and so on.

A pattern we have used a lot is to have things like this:

```ts
interface A {
    kind: 'A';
    foo: number;
}

interface B {
    kind: 'B';
    bar: string;
}

type AorB = A | B;
type AorBkind = AorB['kind'];

declare const aorb: AorB;

if (aorb.kind === 'A') {
    // TS knows that aorb is A here
}
else if (aorb.kind === 'B') {
    // TS knows that aorb is B here
}
else {
    // TS knows this should be impossible, and aorb has type `never`, which we can test:
    never(aorb, 'Impossible situation!');
}

function never(impossible: never, message: string): never {
    throw new Error(message);
}```

**Comment by rollandjb** [comment]
@krryan:  Excellent! Thank you so much!
