### ISSUE TITLE
Suggestion: Reserved diagnostic code for user's custom errors.

### ISSUE THREAD

**Issue by bowenni** [Microsoft/TypeScript#15955]
**TypeScript Version:**  2.3.1

We're checking for some error prone patterns in compile-time and making those patterns compiler errors. This involves [assigning new error code](https://github.com/Microsoft/TypeScript/blob/f489f5af4d043491d2cb4c5734e1a475a2c3bdf7/lib/typescript.d.ts#L2067) to these patterns.
We could look at the existing error code from [diagnosticMessages](https://github.com/Microsoft/TypeScript/blob/master/src/compiler/diagnosticMessages.json) and pick some code that are unused. But they can be used in future still. 

**Expected behavior:**
A range of error code is reserved for custom errors.

**Actual behavior:**
A random currently unassigned error code is used.

**Comment by mhegazy** [comment]
How are you adding these errors?

**Comment by bowenni** [comment]
Similar to a Language Service plugin, we wrap the `ts.Program` in a proxy and decorate `getSemanticDiagnostics()`.
An dummy example would be https://github.com/alexeagle/ts_plugin_prototype/blob/master/tscPlugin.ts

**Comment by mhegazy** [comment]
Diagnostics now should have a `source` property. This should be the name of your plugin. the host (VSCode for instance) would use that to indicate where the error comes from. see https://github.com/Microsoft/TypeScript/issues/15224 for more details.

**Comment by bowenni** [comment]
Thanks mhegazy.`source` property should be good for us.
