### ISSUE TITLE
issue with enumodules and const

### ISSUE THREAD

**Issue by jrieken** [Microsoft/TypeScript#1596]
While TypeScript allows me to write 

```
enum Foo {

}

module Foo {

}
```

it does not allow the same for *const* enums

```
const enum Foo {

}

module Foo {

}
```

It will report an error about a duplicated identifier. Unsure if this is by design/spec or a bug.

**Comment by vladima** [comment]
I would say this is by design - const enums are intended to be completely removed in the code. Const enums are allowed only in property\indexed access expressions. There should be no ways to capture the value side of the const enum to avoid issues with aliasing, . 

```typescript
// if merging is allowed
const enum E { A }
module E { export var B...}

var x = E; // now is prohibited but if merging is allowed then should be legal - maybe you want to use just module members
x.A; // will be undefined in runtime
```

**Comment by danquirk** [comment]
I agree with Vlad. The latest version of the spec doesn't yet mention const enums. Let's make sure whatever the decision here is makes its way into the spec.

**Comment by jrieken** [comment]
@vladima - Thanks. Sounds reasonable to me.

**Comment by garkin** [comment]
I request reopenning. 

Interfacess are removed from code too.
And this is a how exact same thing is currently working with interfaces:
```ts
interface Stuff { prop: 123; }
module Stuff {
    export function do(that:Stuff) {
        return that.prop * that.prop; 
    }
}
 
const error = Stuff; // it's just a module
```
I can't find a reason this to be different or difficult to implement.

**Comment by garkin** [comment]
And also this works:
```ts
type Test = Test.T;
namespace Test {
	export const enum T { A, B, C }
	export function transform(that: T) {
		switch (that) {
			case T.A: return 'aaa';
			case T.B: return 'bbb';
			case T.C: return 'ccc';
		}

	}
}
```
