### ISSUE TITLE
EPERM Issue for JavaScript Project with ATA Enabled

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#15961]
From https://github.com/Microsoft/vscode/issues/26644

@mikerhyssmith  reported that running `npm install` caused:

```
Error: EPERM: operation not permitted,
```

From the initial investigation, this seems related to automatic typings acquisition. It could also be similar to the issue from #7762

**Comment by joejustesen** [comment]
Is anybody looking into this?  I have several plain node express app in JS that I have to close to install any packages from NPM.  I am running 1.28.1 vscode on Windows 10.  Does not happen on my Linux box.

**Comment by mjbvz** [comment]
Seems like the same issue as #32113 (which is newer but has had more activity)
