### ISSUE TITLE
insertSpaceBeforeFunctionParenthesis Does Not Apply To Constructor 

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#15960]
From https://github.com/Microsoft/vscode/issues/26917
**TypeScript Version:**  2.3.3-insiders

**Code**

```ts
class Foo {
    constructor() { }

    bar() { }
}
```

Run format with `insertSpaceBeforeFunctionParenthesis: true`

**Expected behavior:**
Spaces are inserted after both `constructor` and `bar`

```ts
class Foo {
    constructor () { }

    bar () { }
}
```

**Actual behavior:**
Spaces is inserted after `bar` but not after `constructor`:

```ts
class Foo {
    constructor() { }

    bar () { }
}
```

**Comment by ikatyang** [comment]
@mjbvz @mhegazy There is already an `insertSpaceAfterConstructor` rule to handle this case, but it seems not exposed in VSCode.

Should merge these two rules to fix this bug(?) or just expose it on the VSCode side?

**Comment by mhegazy** [comment]
looks exposed to me: https://github.com/Microsoft/TypeScript/blob/b57830f7f952b8858c44a65b48f157f46f0ac547/src/server/protocol.ts#L2363

**Comment by mjbvz** [comment]
I've opened https://github.com/Microsoft/vscode/issues/28206 to track picking this this setting up in VS Code. Should be in the 1.14 insiders builds once those start up again
