### ISSUE TITLE
Compiler API: How to get the "type" of an interface?

### ISSUE THREAD

**Issue by donaldpipowitch** [Microsoft/TypeScript#15976]
**TypeScript Version:**  2.3.2

**Code**

Given an interface like this:

```ts
/**
 * The props which can be passed to `<Foo/>`.
 */
export interface FooProps {
  /**
   * Use a date formatted as RFC 3339/ISO 8601 (e.g. `'2017-02-22T10:36:24Z'`).
   */
  date: string;
}
```

I'd like to get the documentation of the interface. Currently I do something like this:

```ts
const exports = checker.getExportsOfModule(checker.getSymbolAtLocation(sourceFile));
const docs: Array<DocumentedExport> = exports.map(exportedSymbol => {
    const symbol = getOriginalSymbol(exportedSymbol, checker);  // returns exportedSymbol or the aliased symbol if it is a re-export
    const documentation = displayPartsToString(symbol.getDocumentationComment());

    const declaration = symbol.declarations![0];
    const sourceFile = declaration.getSourceFile();
    const { fileName } = sourceFile;
    const { line, character } = sourceFile.getLineAndCharacterOfPosition(declaration.getStart());
    const type = checker.typeToString(checker.getTypeOfSymbolAtLocation(symbol, declaration));

    if (declaration.kind === SyntaxKind.InterfaceDeclaration) {
      console.log('Found FooProps!');
    }

    return {
      name: symbol.getName(),
      kind: declaration.kind,
      fileName,
      line,
      character,
      documentation,
      type  // this is `'any'`
    }
  });
```

My `type` is `'any'`. Shouldn't it be something like `{ date: string; }`? And how would I get the documentation for `date` (the `Use a date formatted as...'` line).`? 

Thank you :)

**Comment by donaldpipowitch** [comment]
Is this the correct way? :)

```ts
const exports = checker.getExportsOfModule(checker.getSymbolAtLocation(sourceFile));
const docs: Array<DocumentedExport> = exports.map(exportedSymbol => {
  const symbol = getOriginalSymbol(exportedSymbol, checker);  // returns exportedSymbol or the aliased symbol if it is a re-export
  const documentation = displayPartsToString(symbol.getDocumentationComment());

  const declaration = symbol.declarations![0];
  const sourceFile = declaration.getSourceFile();
  const { fileName } = sourceFile;
  const { line, character } = sourceFile.getLineAndCharacterOfPosition(declaration.getStart());
  let type = checker.typeToString(checker.getTypeOfSymbolAtLocation(symbol, declaration));

  if (declaration.kind === SyntaxKind.InterfaceDeclaration) {
    type = checker.typeToString(checker.getTypeAtLocation(declaration));
  }

  return {
    name: symbol.getName(),
    kind: declaration.kind,
    fileName,
    line,
    character,
    documentation,
    type  // this is `'FooProps'` now \o/
  }
});
```

Can someone explain me when `getTypeOfSymbolAtLocation` and when `getTypeAtLocation` should be closed?

**Comment by RyanCavanaugh** [comment]
There are two functions, `getDeclaredTypeOfSymbol` and `getTypeOfSymbol`. The former is for getting the types of *types*, the latter is for getting the types of *values*. So `getTypeOfSymbol(/*the FooProps symbol*/)` tries to get the type of the *value identifier* (variable) named `FooProps`. `getDeclaredTypeOfSymbol` will do the right thing here.

I cannot coherently explain the naming convention.

**Comment by donaldpipowitch** [comment]
Cool, thank you again. ❤

**Comment by donaldpipowitch** [comment]
> There are two functions, getDeclaredTypeOfSymbol and getTypeOfSymbol.

There is a `getTypeOfSymbol` function in the `checker.ts`, but it is not public. Should it be public? Or is `getTypeOfSymbolAtLocation` (which is public) basically for similar use cases like `getTypeOfSymbol`?

(`getDeclaredTypeOfSymbol` is on the public `interface TypeChecker`.)

**Comment by donaldpipowitch** [comment]
> The former is for getting the types of types

Types of types are... `interface` and `type`? So basically TypeScript keywords/primitives which aren't included in your compiled JS code?

**Comment by RyanCavanaugh** [comment]
Not sure on the first question.

For the second, there are also classes and imports to consider. The identifier for a class resolves to both a value (which is the constructor function) and a type (the instance type); similarly an `import`ed identifier *may* have both type and value meanings (or possibly neither, if it's a namespace).
