### ISSUE TITLE
`@lib: ES6` on fourslash test case breaks tests

### ISSUE THREAD

**Issue by saschanaz** [microsoft/TypeScript#15978]
**TypeScript Version:** master

**Repro:**

1. Insert `// @lib: ES6` on `test/fourslash/commentsFunctionExpression.ts`
2. Run `jake runtests t=commentsFunctionExpression`

**Expected behavior:**

The test should run well

**Actual behavior:**

Numbers unexpectedly becomes `any`:

`AssertionError: At 14: quick info text: expected 'var assigned: (s: string) => any' to equal 'var assigned: (s: string) => number'`

Probably the test code does not correctly check `/// <reference />` comment in lib.d.ts files but not sure how can it be fixed.

**Comment by jakebailey** [comment]
Just looking at old issues; this doesn't break anymore.
