### ISSUE TITLE
VS 2015 Preview language service not recognize --module (TypeScriptModuleKing) flag

### ISSUE THREAD

**Issue by flaticols** [Microsoft/TypeScript#1597]
Hi!

I'm build TypeScript from 4e5a3ae69534ba0fbdc4af1ee0cb2173c6901877 commit and **release-1.4** branch. After this. in VS where use **export** keyword for modules . classes and etc. Visual Studio highlight as error
**Cannot compile external modules unless the '--module' flag is provided**

But it's compiled well fine.

Examples:
```typescript
export module Foo {}
```

```typescript
module Foo {}
export = Foo;
```

In project file "TypeScriptModuleKind" property set as "commonjs" or "amd".

**Comment by ctaggart** [comment]
I forgot to update the `tsc.js` to `C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.1`, so I was getting the error when building too. This is no longer blocking me,  but still pops up as an error in `Error List`.

**Comment by flaticols** [comment]
@ctaggart yeap. But 
> still pops up as an error in  Error List 
And this is a problem.

**Comment by mhegazy** [comment]
Can you give this a try on TypeScript 1.4 release?

**Comment by flaticols** [comment]
In 1.4 it's works

**Comment by mhegazy** [comment]
thanks @flaticols
