### ISSUE TITLE
Decorator on class expression

### ISSUE THREAD

**Issue by BurtHarris** [Microsoft/TypeScript#15975]
I hit an snag porting a unit test from Babel to TypeScript.   I'm not following the decorator spec closely, so it might be as-intended, but I thought I'd ask.

**TypeScript Version:**  2.3.2 

```ts
import mixin from '../../lib/mixin';

function applyMixins(...mixins) {
  return @mixin(...mixins)
    class Foo {
      getStuff3() {
        return 'stuff3';
      }
    };
}

```

**Expected behavior:**
Compiles as under Babel

**Actual behavior:**
This fails with an **Expression expected** error

**Comment by aluanhaddad** [comment]
This is a duplicate of #7342.

**Comment by BurtHarris** [comment]
Thanks
