### ISSUE TITLE
Missing documentation in lib.d.ts

### ISSUE THREAD

**Issue by drake7707** [microsoft/TypeScript#15980]
**TypeScript Version:**  2.2.1

While a lot of the available interfaces and functions have documentation in lib.d.ts, there is still a lot of documentation missing. I've noticed that most definitions are available and elaborately documented on http://devdocs.io/, which contains data scraped from the Mozilla MDN Web API.

I always find it rather handy to have documentation readily listed in intellisense, especially when I'm working with unfamiliar classes or interfaces.

Are there any rules/guidelines regarding documentation in lib.d.ts? How is it determined what gets documented and what doesn't? Is there an official source required?

I've looked up a few of the undocumented interfaces and I think it should be possible to match the documentation provided by devdocs.io for most cases where the current documentation is missing. I guess it should also be possible to verify if there aren't any missing properties in the lib.d.ts and use the browser compatibility mentioned in #3250 when the exact syntax is finalized.

**Comment by mhegazy** [comment]
> Are there any rules/guidelines regarding documentation in lib.d.ts? How is it determined what gets documented and what doesn't? Is there an official source required?

The documented APIs are documented by hand. you can find the soruces for the JS built-in objects in https://github.com/Microsoft/TypeScript/tree/master/src/lib, and for the DOM APIs in https://github.com/Microsoft/TSJS-lib-generator/blob/master/inputfiles/comments.json.

If you want to contribute new docs, feel free to send us a PR.


> I've looked up a few of the undocumented interfaces and I think it should be possible to match the documentation provided by devdocs.io for most cases where the current documentation is missing. 

Let me get back to you on this. I need to ask our lawyers if there is any issue with using docs from an external source like devdocs.io

**Comment by RyanCavanaugh** [comment]
We pull in MDN docs now
