### ISSUE TITLE
Type inference inconsistent when generic extends literal

### ISSUE THREAD

**Issue by wkornewald** [Microsoft/TypeScript#15983]
**TypeScript Version:**  2.3.2

**Code**

```ts
function ff<T extends {[k: string]: number | boolean}, K extends keyof T>(x: T, k: K, v: T[K]): void {
}
let val = {a: 5}
ff(val, 'a', 9)
// PROBLEM: argument of type '9' is not assignable to parameter of type '5'
ff({a: 5}, 'a', 9)

function gg<T extends {[k: string]: number | string}, K extends keyof T>(x: T, k: K, v: T[K]): void {
}
gg({a: 5}, 'a', 9)
gg(val, 'a', 9)
```

**Expected behavior:**
The type inferencer makes no difference between any of those four calls.

**Actual behavior:**
The type inferencer seems to treat the generic T differently based on whether there's a literal in the union of allowed types and based on whether the argument is passed from a variable or directly. The first `ff()` call infers `a` as the literal 5 while the second one infers it as `number`.

This happens when you have a literal in the union. I suppose `boolean` is equivalent to `true | false`? You can trigger the same behavior when replacing `boolean` with some string literal. However, if you use `number | string` like in `gg` the type of `a` becomes `number` in both cases.

What's unexpected here is that I've told the compiler about my allowed types: `number | boolean`. No other type (not even a more specific one) should be inferred unless I explicitly list it (e.g.: `number | 5`). Especially, some unrelated literal (`boolean`) shouldn't change the inference behavior of `number`.

**Comment by mhegazy** [comment]
`boolean` behaves more or less the same as `true | false`. Type inference uses the existence of a literal to know if it should infer literal types or widen them to their base type.

**Comment by unional** [comment]
Similar case but likely different cause:
```ts
interface ParsedArgs {
    x: string[];       
    y?: string;
}

declare function deepEqual<U>(value: U, expected: U, message?: string): void;

let x: ParsedArgs = {} as any

deepEqual(x, { x: [] })

const expected = { x: [] }
deepEqual(x, expected) // error
```
http://www.typescriptlang.org/play/index.html#src=interface%20ParsedArgs%20%7B%0D%0A%20%20%20%20x%3A%20string%5B%5D%3B%20%20%20%20%20%20%20%0D%0A%20%20%20%20y%3F%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Adeclare%20function%20deepEqual%3CU%3E(value%3A%20U%2C%20expected%3A%20U%2C%20message%3F%3A%20string)%3A%20void%3B%0D%0A%0D%0Alet%20x%3A%20ParsedArgs%20%3D%20%7B%7D%20as%20any%0D%0A%0D%0AdeepEqual(x%2C%20%7B%20x%3A%20%5B%5D%20%7D)%0D%0A%0D%0Aconst%20expected%20%3D%20%7B%20x%3A%20%5B%5D%20%7D%0D%0AdeepEqual(x%2C%20expected)%0D%0A

Let me know if you want to new issue to track this one 🌷

**Comment by mhegazy** [comment]
Seems fixed in latest.
