### ISSUE TITLE
Class.name of a derived class reported incorrectly in IE 11

### ISSUE THREAD

**Issue by kevmeister68** [Microsoft/TypeScript#15986]
I can't categorically say that this is specifically a typescript issue, but it is an issue involving typescript that is affecting me.

We are presently upgrading from Typescript 1.7.2 to 2.3. Our development environment is Microsoft Visual Studio 2015 (which probably has no relevance to this question).

Two simple classes:

    class Foo {
       me: string;

       constructor() {
          this.me = "I am Foo";
       }
    }

    class Bar extends Foo {
       constructor() {
          super();
          this.me = "I am Bar";
       }
    }

    var fooName = Foo.name;
    var barName = Bar.name;
    console.log( "fooName is " + fooName + ", barName is " + barName );

In TS 1.7, on IE11:

fooName = Foo, barName = Bar

In TS 2.3 on IE11:

fooName = Foo, barName = Foo

The output from Chrome is correct.

Have been digging around. Have found out that IE does not support Function.name property and that it is shimmed. We use core-js. We were running 1.2.6 to produce the above output. Upgraded to 2.4.1 and it produced the same output. Using requires as our loader if it makes any difference.

So, my dilemma is that I am not really sure who is "responsible" for this problem -- it used to work fine in TS 1.7 and now it doesn't.

**Comment by mhegazy** [comment]
Looks related to the [changes in class emit in TS 2.1](https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#generated-constructor-code-substitutes-the-return-value-of-super-calls-as-this).

Looks like [core-js](https://github.com/zloirock/core-js/blob/master/modules/es6.function.name.js) just puts the `name` pollyfill on the function prototype. with TS 2.1 the class now inherits from the base constructor, and not directly from the `function` object, so you get the base `name` and not the `Function.prototype.name`.

The change was made in accordance with the ES6 spec; so i would say this should a core-js issue.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
