### ISSUE TITLE
[Request] Extend tsconfig via a package

### ISSUE THREAD

**Issue by Timer** [Microsoft/TypeScript#15984]
**TypeScript Version:**  2.3.2

**Code**

```ts
{
  "extends": "tsconfig-react-app"
}
```

**Expected behavior:**

Using the node module resolution, finds the specified package and inspects the `package.json`'s `main` field for a `.json` file, which is used to extend the configuration.

**Actual behavior:**
Something along the lines "must be a relative path".

**Comment by vtabary** [comment]
I think it could use the same behavior than the [module resolution](https://www.typescriptlang.org/docs/handbook/module-resolution.html) to be consistent.

**Comment by Timer** [comment]
Would love to know if this would be considered or if I could contribute support.

We'd really like it for `create-react-app`.
Thanks!

**Comment by lukeshiru** [comment]
This is very simmilar to this issue: https://github.com/Microsoft/TypeScript/issues/18865 I really want to see this solved. Is currently making my dev experience really annoying.

**Comment by mhegazy** [comment]
Closing in favor of https://github.com/Microsoft/TypeScript/issues/18865. 

Though https://github.com/Microsoft/TypeScript/issues/18865 is a duplicate of this one, https://github.com/Microsoft/TypeScript/issues/18865 seems to have more discussion.

**Comment by Timer** [comment]
I think you forgot to close :)
