### ISSUE TITLE
Confusing error message for yield expression

### ISSUE THREAD

**Issue by ikokostya** [Microsoft/TypeScript#15981]
**TypeScript Version:**   2.3.1

**Code**

Example 1:

```ts
function foo() {
    yield 'foo';
}
```

Example 2:

```ts
function bar() {
    yield (1 + 2);
}
```

**Expected behavior:**

Descriptive error message similar to 

```ts
function foo() {
    yield 1;
}
```

```
t.ts(2,5): error TS1163: A 'yield' expression is only allowed in a generator body.
```

**Actual behavior:**

Example 1: 
```
t.ts(2,11): error TS1005: ';' expected.
```

Example 2:

```
t.ts(2,5): error TS2304: Cannot find name 'yield'.
```

Related to https://github.com/Microsoft/TypeScript/issues/15943

**Comment by charlespierce** [comment]
PR opened to resolve this issue: #16213
