### ISSUE TITLE
Type inference not 100% correct with ||

### ISSUE THREAD

**Issue by donaldpipowitch** [Microsoft/TypeScript#15982]
**TypeScript Version:**  2.3.2

**Code**

```ts
interface Foo {
    type: 'foo';
}

interface Bar {
    type: 'bar';
}

interface Else {
    type: any;
}

type Types = Foo | Bar | Else;

function getFoo(a: any): Foo | undefined {
    if (a.type === 'foo') {
        return a;
    }
}

function getBar(a: any): Bar | undefined {
    if (a.type === 'bar') {
        return a;
    }
}

function getElse(a: any): Else {
    return a;
}

function checkType(a: any) {
    return (
        getFoo(a) ||
        getBar(a) ||
        getElse(a)
    );
}
```

**Expected behavior:**

Hovering over `checkType` should show `Foo | Bar | Else` as return types.

**Actual behavior:**

Hovering over `checkType` shows `Else` as return types.

**Comment by ajafff** [comment]
`Foo` and `Bar` are subtypes of `Else`. The type checker erases them as part of an optimization IIRC. 
For the same reason for example `"foo" | string` will result in just `string`

**Comment by aluanhaddad** [comment]
@ajafff indeed. A nice way to see this in action is to write
```ts
type Types = Foo | Bar | Else;
type TypesType = Types['type']; // any
```

**Comment by donaldpipowitch** [comment]
I see, thanks.
