### ISSUE TITLE
Go to Definiton does not work in JavaScript namespace

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#15996]
_From @StaticNoiseLog on May 22, 2017 1:6_

- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.11|
|vscode-firefox-debug|hbenl|0.13.1|
|debugger-for-chrome|msjsdiag|3.1.1|
|unity-debug|Unity|1.2.0|;

---

Steps to Reproduce:

1. Create a JavaScript File with this content (the variable c99 is used to wrap the Game class in its own namespace, a common pattern in JavaScript):

```js
var c99 = {};

c99.Game = (function () {
    function Count99Game() {
        console.log('Count99 game starts.');
        this.initGame();
    }

    Count99Game.prototype.initGame = function () {
        this.nextCountLabel = document.getElementById('next-count');
    };

    return Count99Game;
})();
```

2. Right-click on the "initGame" function on line 6 and choose "Go to Definition". Nothing happens. Expected behavior: The cursor should be positioned on line 9 where the function is defined. Works in NetBeans, for example.

_Copied from original issue: Microsoft/vscode#27045_

**Comment by mhegazy** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/12416

**Comment by mhegazy** [comment]
Seems to be same root cause as https://github.com/Microsoft/TypeScript/issues/16489

**Comment by mhegazy** [comment]
Partially fixed by https://github.com/Microsoft/TypeScript/pull/21974. `this` assignments in nested functions are not tracked correctly still.

**Comment by mjbvz** [comment]
This example now seems to be working for me (shown by the references code lens):
 
<img width="1125" alt="Screen Shot 2020-10-27 at 3 37 33 PM" src="https://user-images.githubusercontent.com/12821956/97369522-55cc8980-186a-11eb-9d8d-d512775c57c6.png">
