### ISSUE TITLE
Control flow type narrowing doesn't work

### ISSUE THREAD

**Issue by pc-lover** [Microsoft/TypeScript#15994]
**TypeScript Version:**  2.3.2

**Code**

```ts
type JoinModels<A, K extends string, B> = A & {
    [k in K]: B;
};

interface User {
    username: string;
}

interface Post {
    title: string;
}

type UserWithPosts = JoinModels<User, "posts", Post[]> | null;

let userWithPosts: UserWithPosts = null;
if (userWithPosts == null) {
    console.log(userWithPosts.posts[0].title);
}
```

**Expected behavior:**
`userWithPosts` should be narrowed to null;

**Actual behavior:**
No error occurs

**Comment by blakeembrey** [comment]
@pc-lover If you enable `strictNullChecks`, this should work as expected. Without it, there is no `null` or `undefined` types used. Do you have an expected behaviour without `strictNullChecks` enabled?

**Comment by pc-lover** [comment]
@blakeembrey I'm sorry, my mistake
