### ISSUE TITLE
Call to function returning never can not be used to narrow type

### ISSUE THREAD

**Issue by bwrrp** [Microsoft/TypeScript#15991]
**TypeScript Version:**  2.3.2

A function that never returns (return type `never`) can not be used in a type guard to narrow the type after the branch.

**Code**

```ts
class Thing { };

function diverges(): never {
    throw new Error('Never returns');
}

function problem(thing: Thing | null): Thing {
    if (thing === null) {
        diverges();
        // throw new Error('Works!');
    }

    return thing; // fails type check
}
```

**Expected behavior:**

Replacing the call to `diverges()` with a return or throw statement causes thing to be marked as type `Thing` after the branch, as code will never flow from the `if (thing === null)` branch to the code below. I expected a call to a function with return type `never` to achieve the same, as this should indicate that the call never returns.

**Actual behavior:**

The code does not compile due to an error, as the type of `thing` is not narrowed to `Thing`:
"Type 'Thing | null' is not assignable to type 'Thing'. Type 'null' is not assignable to type 'Thing'."

**Comment by krryan** [comment]
I suspect this won't happen, because it *is* possible to return a `never`-type value, which means it's possible for that function to complete and return and control to move on down to `return thing;`.

**Comment by RyanCavanaugh** [comment]
Duplicate #12825. The recommended workaround is to write `return diverges();`

**Comment by RyanCavanaugh** [comment]
> I suspect this won't happen, because it is possible to return a never-type value

The intent of `never` is that it *shouldn't* be possible.

**Comment by bwrrp** [comment]
Sorry, must have missed that one in my search. Thanks for the explanation!
