### ISSUE TITLE
typescript angular2 失败

### ISSUE THREAD

**Issue by Hareis** [microsoft/TypeScript#16009]
**TypeScript Version:**  2.2.1 / nightly (2.2.0-dev.201xxxxx)
2.1.1
**Code**
按照http://www.typescriptlang.org/docs/handbook/asp-net-core.html 这个来创建angular 应用，然后就出现这个错误
![qq 20170523091537](https://cloud.githubusercontent.com/assets/11290701/26334643/fedaf344-3f98-11e7-8b99-ea2bdc039439.png)

**Comment by mhegazy** [comment]
courtesy of google translate:

In accordance with http://www.typescriptlang.org/docs/handbook/asp-net-core.html this to create the angular application, and then this error
