### ISSUE TITLE
Import = require() in d.ts files do not work in declaration area

### ISSUE THREAD

**Issue by SowingSadness** [Microsoft/TypeScript#16003]
Strange behavior import in d.ts files. It do not allow use object from AMD module as declaration.
If i use *import* in d.ts file then is not apply in *.ts files.
**TypeScript Version:**  2.3.2

**Code**
[ImportReactjs.zip](https://github.com/Microsoft/TypeScript/files/1019994/ImportReactjs.zip)

*Import* in d.ts file
![ts_import](https://cloud.githubusercontent.com/assets/576443/26325027/ef8584d2-3f3d-11e7-8916-b4ff60d4246e.png)

*Import* in submodule declaration 
![ts_import_ok](https://cloud.githubusercontent.com/assets/576443/26325028/ef860aba-3f3d-11e7-958d-175ffd980989.png)

**Expected behavior:**
*.ts files see interfaces from interfaces.d.ts

**Actual behavior:**
*.ts files do not undrestand IModule interface from interfaces.d.ts

**Comment by RyanCavanaugh** [comment]
Adding an import or export to a file means its declarations are not in the global scope.
