### ISSUE TITLE
TypeScript 2.3.3 download page for VS 2017 typos

### ISSUE THREAD

**Issue by flcdrg** [Microsoft/TypeScript#16011]
**TypeScript Version:**  2.3.3

The download page [TypeScript SDK for Visual Studio 2017](https://www.microsoft.com/en-us/download/details.aspx?id=55258) includes the following under the Releases heading:

> TypeScript 2.3.3 for Visual Studio 2015 — June 22, 2017

1. The date is incorrect - should be May 22, 2017
2. It's a bit confusing that it says "Visual Studio 2015" when this page is for 2017. Might be good either to change the text to say "2017" or that it is for 2015 and 2017 (if that is the case)

**Comment by mhegazy** [comment]
Thanks for the report, just pushed a fix for the link.
