### ISSUE TITLE
'convertFunctionToEs6Class' is not a syntactic check

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#16013]
From the declaration:

```ts
        /** A fast syntactic check to see if the refactor is applicable at given position. */
        isApplicable(context: RefactorContext): boolean;
```

However, in `convertFunctionToEs6Class`, the implementation is semantic - it uses the type-checker. So I guess my question is, is that okay? Or should the checking logic be moved into `getCodeActions`?

**Comment by mhegazy** [comment]
> However, in convertFunctionToEs6Class, the implementation is semantic - it uses the type-checker. So I guess my question is, is that okay? 

yes. the intention for the check to be quick, and not block. syntactic is the fastest category, but pulling on the checker for one symbol should be close too.

>  Or should the checking logic be moved into getCodeActions?

it is too late at this point. you want to know if this is something you should show to the user or not.

**Comment by RyanCavanaugh** [comment]
Comment needs to be updated

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
