### ISSUE TITLE
React: Type inference not working for ref callback

### ISSUE THREAD

**Issue by simonvizzini** [microsoft/TypeScript#16019]
Type inference is not working for the ``ref`` callback prop.
I believe this is the same issue as in #7088, which was fixed over a year ago.

**TypeScript Version:**  2.3.2

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
class Other extends React.Component<any, any> {
	render() {
		return <div />;
	}
}

class Container extends React.Component<any, any> {
	private _ref: Other;

	render() {
                // Parameter 'ref' implicitly has an 'any' type.
		return <Other ref={ ref => this._ref = ref } />;
	}
}
```

**Expected behavior:**
Type of parameter ``ref`` should be inferred as ``Test``

**Actual behavior:**
Parameter 'ref' implicitly has an 'any' type.

**Comment by mhegazy** [comment]
The issue here is that the type of `props` is `any`, since `Other` is declared to extend from `React.Component<any, any>`. The result here is that all references to props are practically unchecked. 

if this component does not have any properties, then declare it as `extends React.Component<{}, any>`.

if the intention is to allow any property to be defined on this component, then declare at as `extends React.Component<Record<string, any>, any>`.

**Comment by simonvizzini** [comment]
Thank you, @mhegazy! In my concrete case I actually did have a concrete Props interface defined, I just didn't think about this when trying to come up with a minimal example (I'm still learning the nuances of the type system). Nonetheless, I'm simply unable to properly type the ref callbacks, especially when defining Props interfaces that extend other, generic props (e.g. ``interface Props extends React.HTMLProps<HTMLInput>``). Typescript gave funny errors along the lines of "got type A but expected B", where A extends from B, and when I changed the type def to type to B it said "got B but expected C", where B again extends from C...

It's most likely a misunderstanding on my side, still learning ts and so I'll come up with a more concrete example today or tomorrow.

**Comment by mhegazy** [comment]
this works for me. if you have a sample we can look more.

```ts
interface ContainerProps { 
    someProp: number;
}
class Container extends React.Component<ContainerProps, any> {
    render() {
        return <div ref={p => 0} />; // p is HTMLDivElement
    }
}

var x = <Container someProp={3} ref={p => 0} /> // p is Container
```

**Comment by simonvizzini** [comment]
Thank you, your example indeed works. Finally I had time to come up with a better example that doesn't work for me. I'm probably doing something wrong I think:

````javascript
interface MyInputProps extends React.ChangeTargetHTMLProps<HTMLInputElement> {
    onValid?(): boolean;
    onInvalid?(): boolean;
}

class MyInput extends React.Component<MyInputProps, {}> {
    render() {
        const { onValid, onInvalid, ...inputProps } = this.props;
        return (
            <input { ...inputProps } />
        );
    }
}

class Container extends React.Component<{}, {}> {
    render() {
        return <MyInput ref={p => 0} />; // p is any
    }
}
````

**Comment by simonvizzini** [comment]
I'm so sorry for spamming your inbox :) I think I finally figured out why TS is complaining (somehow I always missed the ``Property 'render' is missing in type 'HTMLInputElement'.'`` part in the error message, which gave me a hint in the right direction):

When I define the props like like ````interface MyInputProps extends React.ChangeTargetHTMLProps<JSX.ElementClass & HTMLInputElement>```` then the compiler won't complain anymore. Type of ``p`` is still ``any`` but at least I can explicitly give it a type now.

**Comment by mhegazy** [comment]
`React.ChangeTargetHTMLProps` extends `React.ClassAttributes` which overrides `ref` to be a union type. here is the definition from [react declaration file on DT](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/83226ba8a71d2eaf1a335f8a0fb4e112d117186c/types/react/index.d.ts#L38).

```ts
    type Ref<T> = string | ((instance: T) => any);

    interface ClassAttributes<T> extends Attributes {
        ref?: Ref<T>;
    }
```

The result here is that there is no contextual type for the function, and this `p` is `any`. this looks like a bug that we should fix. this should behave the same way it does with something like:
```ts
declare var x: string | ((a: HTMLInputElement) =>void);
x = a => { };
```

**Comment by simonvizzini** [comment]
Awesome, thank you!

**Comment by yuit** [comment]
The reason we didn't do inference here because when React component is declared as a class declaration. The constructor signature doesn't same treatment to get contextual type as with using SFC.....We should try to do the same thing when component is declared as class.

So in your example, if you do the follow:
```ts
....
function MyInput2(props: MyInputProps) {
    const { onValid, onInvalid, ...inputProps } = this.props;
    return (
            <input { ...inputProps } />
        );
}

var y = <MyInput2 ref={(p) => 0} />  // p is inferred correctly to be HTMLInputElement
```

**Comment by yuit** [comment]
`ref` in this case come from MyInputProps as it extends React.ChangeTargetHTMLProps....normally ref is the property of intrinsicClassAttribute.... We should instantiate such the property.

**Comment by simonvizzini** [comment]
Hi @yuit, I'm sorry, but somehow I got never notified about the edit and mention in your comment.

The reason I'm doing ``MyInputProps extends React.ChangeTargetHTMLProps<HTMLInputElement>`` is that so I don't have to manually specify "onChange" in the props interface. I'm not sure if this is good or correct, what do you think?

**Comment by yuit** [comment]
@simonvizzini  no problem at all.  Just to understand it better, are you plan to pass `onChange` property in like
```ts
interface MyInputProps extends React.ChangeTargetHTMLProps<HTMLInputElement> {
    onValid?(): boolean;
    onInvalid?(): boolean;
}

class MyInput extends React.Component<MyInputProps, any> {
    render() {
        const { onValid, onInvalid, ...inputProps } = this.props;
        return (
            <input { ...inputProps } />
        );
    }
}

function someFunction(...) {...}
var x = <MyInput ref={p => 0}  onChange={someFunction} /> // p is any
```

**Comment by simonvizzini** [comment]
Hi @yuit, sorry once more for the late reply- I got kind of lost in other tasks and I didn't keep track of this issue.

To answer your question, the intention is to intercept the ``onChange`` event, do some validation and then call the ``onChange`` callback property, if it has been passed down. Like this:

````javascript
interface MyInputProps extends React.ChangeTargetHTMLProps<HTMLInputElement> {
    onValid?(): boolean;
    onInvalid?(): boolean;
}

class MyInput extends React.Component<MyInputProps, any> {
    render() {
        const { onValid, onInvalid, onChange, ...inputProps } = this.props;
        return (
            <input
                { ...inputProps }
                onChange={ this._onChange }
            />
        );
    }
    
    private _onChange = (event: React.ChangeEvent<HTMLInputElement>) => {
        // do some validation first...

        // ... then trigger onChange callback, if present:
        if (this.props.onChange) {
            this.props.onChange(event);
        }
    }
}

function someFunction(...) {...}
var x = <MyInput ref={p => 0}  onChange={someFunction} />
````

Hope this makes sense. Let me know if you have any other questions.

**Comment by timc13** [comment]
would love to see this get fixed!

**Comment by ImAbhishekTomar** [comment]
i am also facing similar type of issue.

**ERROR**
```

(JSX attribute) ref: React.Dispatch<(prevState: undefined) => undefined>
Type 'Dispatch<(prevState: undefined) => undefined>' is not assignable to type 'LegacyRef<HTMLButtonElement>'.
  Type 'Dispatch<(prevState: undefined) => undefined>' is not assignable to type '(instance: HTMLButtonElement) => void'.
    Types of parameters 'value' and 'instance' are incompatible.
      Type 'HTMLButtonElement' is not assignable to type '(prevState: undefined) => undefined'.
        Type 'HTMLButtonElement' provides no match for the signature '(prevState: undefined): undefined'.ts(2322)
index.d.ts(140, 9): The expected type comes from property 'ref' which is declared here on type 'IntrinsicAttributes & Props<"button", ButtonRenderPropArg, ButtonPropsWeControl>'
```


![Screenshot 2021-06-04 at 3 05 48 AM](https://user-images.githubusercontent.com/6933841/120715121-c8c56f00-c4e1-11eb-96a8-c497938b345b.png)

**Comment by Andarist** [comment]
The reported case is about the parameter not being contextually typed for this `ref`. It works today so I think it's fair to close this issue

cc @RyanCavanaugh @jakebailey
