### ISSUE TITLE
Cannot visit object member in strict mode

### ISSUE THREAD

**Issue by k8w** [Microsoft/TypeScript#16015]
**TypeScript Version:**  2.2.1 / nightly (2.2.0-dev.201xxxxx)
2.3.3
**Code**

```bash
# strict is true
tsc --init 
```

```ts
function test1(obj:object,key:any){
    console.log(obj[key])
}

function test2(obj:object,key:string){
    console.log(obj['test'])
}

function test3(obj:object){
    console.log(obj['test'])
}
```

**Expected behavior:**
Compile successfully.

**Actual behavior:**
> Test1.ts(2,17): error TS7017: Element implicitly has an 'any' type because type '{}' has no index signature.
Test1.ts(6,17): error TS7017: Element implicitly has an 'any' type because type '{}' has no index signature.
Test1.ts(10,17): error TS7017: Element implicitly has an 'any' type because type '{}' has no index signature.

**In addition**
```ts
let a:object = {
    a:1
}

a.a = 1;
a['b'] = 2;
a.c = 3;
```

> Test3.ts(5,3): error TS2339: Property 'a' does not exist on type 'object'.
Test3.ts(6,1): error TS7017: Element implicitly has an 'any' type because type '{}' has no index signature.
Test3.ts(7,3): error TS2339: Property 'c' does not exist on type 'object'.

It seems `object` is equal to `{}`, rather than `{ [key: string | number]: any }`

**Comment by artem-malko** [comment]
@twoeo index is string and number only.

**Comment by twoeo** [comment]
@artem-malko 

```ts
function test2(obj:object,key:string){
    console.log(obj[key])
    console.log(obj['test'])
}
```

Still get 
> Test1.ts(2,17): error TS7017: Element implicitly has an 'any' type because type '{}' has no index signature.
Test1.ts(3,17): error TS7017: Element implicitly has an 'any' type because type '{}' has no index signature.

**Comment by RyanCavanaugh** [comment]
> Shouldn't object be the same with { [index:any]: any } ?

It is not.

**Comment by twoeo** [comment]
@RyanCavanaugh 

While, but even this get an error.

```ts
function test(obj:object){
    console.log(obj['test'])
}
```

> Test1.ts(2,17): error TS7017: Element implicitly has an 'any' type because type '{}' has no index signature.

**Comment by mhegazy** [comment]
Either give it a type with an index signature or turn off --noImplicitAny

**Comment by twoeo** [comment]
```ts
let a:object = {
    a:1
}
console.log(a['a']);
```

So it even cannot use `obj['xxx']` to visit a object member ?

**Comment by twoeo** [comment]
Anyone still here? 
Is that really work as intended as last example above ?

**Comment by ikatyang** [comment]
```ts
let a:object = {
    a:1
}
```
The `let a: object` means that `a` is an `object` whether you assign something to it or not

It's equivalent to 
```ts
declare let a: object
```

And `object` means non-primitive type, you can simply thought that `object` is a type of `{}` except primitive type (`string`, `number`, etc.)

So that `{}` does not have any member and index-signature, it is just an empty object.

If you want to access everything without error, just use `any` or `{[key: string]: any}`.

**Comment by mhegazy** [comment]
> Is that really work as intended as last example above ?

yes.

**Comment by twoeo** [comment]
Well, I've just read this: 
[https://blogs.msdn.microsoft.com/typescript/2017/02/22/announcing-typescript-2-2/](https://blogs.msdn.microsoft.com/typescript/2017/02/22/announcing-typescript-2-2/)

> The object type is a new type in 2.2 that matches any types except for primitive types. In other words, you can assign anything to the object type except for string, boolean, number, symbol, and, when using strictNullChecks, null and undefined.

Of course **any types except for primitive types** includes `{ [key: string]: any }` ?

But does `object` is only designed for assigning check, but would throw error when used in getting value ?

**Comment by aluanhaddad** [comment]
Those non primitive values are assignable to `object` but not from `object`. With respect to non primitives it behaves like `{}`
```ts
declare const x: { [key: string]: any };
const y: {} = x; // OK
const z: { p: any } = {}; // Error
```

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
