### ISSUE TITLE
Typescript could not resolve typing error

### ISSUE THREAD

**Issue by artem-malko** [Microsoft/TypeScript#16014]
**TypeScript Version:**  2.3.3

**Code**

```ts
interface Animal {
    name: string;
    size: {
        w?: number;
        h?: number;
    };
}

var dog: Animal = {
    name: 'John',
    size: 'asd',
}
```
And you can open the [link](http://www.typescriptlang.org/play/#src=interface%20Animal%20%7B%0D%0A%20%20%20%20name%3A%20string%3B%0D%0A%20%20%20%20size%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20w%3F%3A%20number%3B%0D%0A%20%20%20%20%20%20%20%20h%3F%3A%20number%3B%0D%0A%20%20%20%20%7D%3B%0D%0A%7D%0D%0A%0D%0Avar%20dog%3A%20Animal%20%3D%20%7B%0D%0A%20%20%20%20name%3A%20'John'%2C%0D%0A%20%20%20%20size%3A%20'asd'%2C%0D%0A%7D) from typescript playground.

**Expected behavior:**

Typing error, because size is not a string, it is an object with specific shape.

**Actual behavior:**

No errors.

**Comment by ctizen** [comment]
This simpler example also compiles without any error, which seems weird to me:
```
interface Animal {
    name: string;
    size: {
        w?: number;
        h?: number;
    };
}

var dog: Animal = {
    name: 'John',
    size: 'some_string',
}
```
Looks like it treats literal string as object, and it matches declared shape which may be empty. Is it an expected behavior?

**Comment by ctizen** [comment]
Looks like it treats literal string as object, and it matches declared object shape which may be empty. I'm not sure if this is expected behavior.

**Comment by artem-malko** [comment]
Sorry, I've just found the same issue In Progress) https://github.com/Microsoft/TypeScript/issues/7485
