### ISSUE TITLE
Intersection type (T & never) should reduce to never, not T

### ISSUE THREAD

**Issue by jcalz** [Microsoft/TypeScript#16038]
**TypeScript Version:**  2.3.3 / master up to and including e2cc27b / since 424074b

**Code** 
```ts 
interface SomeType {
    name: string,
    size: number
}
var someObject:SomeType = { name: 'thing', size: 42 };

// the type (never & T) should reduce to never, but instead reduces to T:
var badIntersection: never & SomeType = someObject;

// but since (o ∈ A∩B) implies (o ∈ A) 
function upcast<A, B>(o: A & B): A {
    return o;
}

// then you can convert any value to type never
function toNever<T>(o: T): never {
    return upcast<never, T>(o);
}

// which seems like a problem
var seemsLikeAProblem: never = toNever('weirdness');
```

**Expected behavior:**
The type `never` is a bottom type; its set of possible values is empty.  The intersection of any type with `never` should reduce to `never`.

**Actual behavior:**
The type checker reduces `never & T` to `T`.  One bizarre consequence is the ability to cast any value to `never`.

---

This behavior was introduced in [424074b](https://github.com/Microsoft/TypeScript/blob/424074ba6bd1b9cf699cf6da15e95f5822272499/src/compiler/checker.ts#L4873) as a reduction rule appropriate for union types (as `never | T` should indeed reduce to `T`), and has been preserved ever since, most recently in [b673d5f](https://github.com/Microsoft/TypeScript/commit/b673d5ff031#diff-c3ed224e4daa84352f7f1abcd23e8ccaR5375).  It looks like an oversight and a bug to me, but maybe people rely on this behavior somewhere?

**Comment by RyanCavanaugh** [comment]
@ahejlsberg - @DanielRosenwasser and I think this is a bug. Agree?

**Comment by ahejlsberg** [comment]
@RyanCavanaugh @DanielRosenwasser Yes, I agree.
