### ISSUE TITLE
Playground feature request: import stuff from @types

### ISSUE THREAD

**Issue by aaronbeall** [microsoft/TypeScript#16041]
It would be really useful if the Playground could import modules from published typings, simplest solution I can think of would be to expose everything from @types, for example:
```
import {Component} from "react";
```

Currently that just [gives the error](http://www.typescriptlang.org/play/#src=import%20%7BComponent%7D%20from%20%22react%22%3B) `Cannot find module 'react'`

**Comment by RyanCavanaugh** [comment]
This would be so sweet. @DanielRosenwasser maybe a checkout of DT on the webserver + some server-side magic could make this happen?

**Comment by mhegazy** [comment]
We also need JSX support.

**Comment by aaronbeall** [comment]
> We also need JSX support.

Completely agree! I think a lot of people don't realize how brilliantly React and TypeScript play together. An example in the playground wouldn't hurt. :)

**Comment by markbjerke** [comment]
Would love to have this and of course I'd like to import my own stuff, why limit to @types.  I'm sure if you have one we can have our own types as well?

**Comment by jakebailey** [comment]
Just looking at old issues; the playground's supported type acquisition and JSX for a good long while.
