### ISSUE TITLE
Incorrect formatting of expression lists

### ISSUE THREAD

**Issue by igelbox** [microsoft/TypeScript#16043]
**TypeScript Version:**  2.3.2

**Code**
Format the following code snippet using VS Code or typescript-formatter:
```js
func({
a: 1,
}, {
b: {},
});
```

**Expected behavior:**
```js
func({
    a: 1,
}, {
    b: {},
});
```
**Actual behavior:**
```js
func({
    a: 1,
}, {
        b: {},
    });
```
After that, source code doesn't pass ESLint checks.

**Comment by RyanCavanaugh** [comment]
Formats as requested now
