### ISSUE TITLE
Object initializer properties not converted to Object.defineProperty when targeting ES5

### ISSUE THREAD

**Issue by strantr** [Microsoft/TypeScript#16058]
**TypeScript Version:**  2.3.3

Properties that are defined on objects are not being converted into ES5 syntax.

**Code**

```ts
var o = {
  get property() {return 1},
  set property(value) {}
};
```

tsconfig.json
```
{
    "compilerOptions": {
        "target": "es5",
    }
}
```
**Expected behavior:**
The generated code should be:
```ts
    Object.defineProperty(o, "property", {
        get: function () { return 1; },
        set: function (value) { },
        enumerable: true,
        configurable: true
    });
```
**Actual behavior:**
It does not convert the properties to ES5 syntax

MDN Object initializer syntax: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer

**Comment by ajafff** [comment]
Your example code is already valid ES5

**Comment by strantr** [comment]
Looks like this was an issue with uglifyjs, sorry.
