### ISSUE TITLE
Consider adding match based type guarnding

### ISSUE THREAD

**Issue by Gozala** [microsoft/TypeScript#16067]
Right now typescript provides type refinements using `typeof`, `instanceof` and user defined type predicates. This is proposal is to enhance user defined type predicates (although it does not necessary needs to be a change for type predicates, it just approach seems compatible).

Here is example illustrating proposed feature:

```ts
interface Square {
    size: number;
}
interface Rectangle {
    width: number;
    height: number;
}
interface Circle {
    radius: number;
}

type Shape = Square | Rectangle | Circle;

function typeOf(shape:Shape):"Square" shape is Square
function typeOf(shape:Shape):"Rectangle" shape is Rectangle
function typeOf(shape:Shape):"Circle" shape is Circle
function typeOf(shape:Shape):"Square"|"Rectangle"|"Circle" {
  if (shape.size) return "Square"
  else if (shape.radius) return "Circle"
  else return "Rectangle"
}

function area(s: Shape):number {
    switch (typeOf(s)) {
        case "Square": return s.size * s.size;
        case "Rectangle": return s.height * s.width;
        case "Circle": return Math.PI * s.radius ** 2;
    }
}
```

### Why not just user defined predicates ?

Sure you could define `isSquare`, `isRectangle`, `isCircle` and it's probably a fine option when you just have only 3 variants, but there are cases where there are far more variants to match over, and in those cases you wind up with `if else` with many arms. It also comes with runtime overhead as matching each variant requires extra function call.

### Why not use discriminant field ?

That is a great option when writing a new code, but unfortunately sometimes you need to interface with pre-existing JS code base, or with a code base you don't have a control of. Yet another example is sometime you may need to create union coming from two different code bases and get them to all add discriminant field may not be possible. This feature essentially provides a way to provide`discriminant` for constructs that you may not necessarily have control of.

**Comment by aluanhaddad** [comment]
```ts
typeOf(shape: Shape): "Square" | "Rectangle" | "Circle" {
  const s = <any>shape; // tslint:disable-line: no-any;
  if (shape.size) return "Square";
  else if (shape.radius) return "Circle";
  else return "Rectangle";
}
```

**Comment by gcanti** [comment]
@aluanhaddad that wouldn't narrow down the types

```ts
function typeOf(shape: Shape): "Square" | "Rectangle" | "Circle" {
  const s = shape as any;
  if (s.size) return "Square";
  else if (s.radius) return "Circle";
  else return "Rectangle";
}

function area(s: Shape): number {
    switch (typeOf(s)) {
        case "Square": return s.size * s.size; // Property 'size' does not exist on type 'Shape'
        case "Rectangle": return s.height * s.width; // Property 'height' does not exist on type 'Shape'
        case "Circle": return Math.PI * s.radius ** 2; // Property 'radius' does not exist on type 'Shape'
    }
}
```

I would make `typeOf` parametric, it's a good surrogate of pattern matching

```ts
function match<R>(
    square: (s: Square) => R,
    rectangle: (s: Rectangle) => R,
    circle: (s: Circle) => R
  ): (shape: Shape) => R {
  return (s: any) => {
    if (s.size) return square(s)
    else if (s.radius) return circle(s)
    else return rectangle(s)
  }
}

// area :: (shape: Shape) => number
const area = match(
  ({ size }) => size * size,
  ({ height, width }) => height * width,
  ({ radius }) => Math.PI * radius ** 2
)
```

**Comment by Gozala** [comment]
@aluanhaddad As @gcanti already pointed out that does not help narrow down type which is the whole point of this proposal.

@gcanti Indeed that pattern does work & that is in fact what I currently use. I do find it little cumbersome, mostly because it forces you to write everything as mapping function which is not always a good fit. It is also that inference isn't doing so great when surrogate functions don't return exact same type.

**Comment by Gozala** [comment]
For instance here is [IMO fairly simple example](https://www.typescriptlang.org/play/#src=interface JSONArray extends Array<Value> {%0A}%0A%0Atype JSONObject %3D {%0A [key%3Astring]%3A Value%0A}%0A%0Atype Value %3D%0A | null%0A | boolean%0A | number%0A | string%0A | JSONArray%0A | JSONObject%0A%0A%0Aexport const match %3D <a>%0A ( Null%3A(value%3Anull) %3D> a%2C%0A Boolean%3A(value%3Aboolean) %3D> a%2C%0A Number%3A(value%3Anumber) %3D> a%2C%0A String%3A(value%3Astring) %3D> a%2C%0A Array%3A(value%3AJSONArray) %3D> a%2C%0A Object%3A(value%3AJSONObject) %3D> a) %3D>%0A (value%3AValue)%3Aa %3D> {%0A switch (typeof value) {%0A case 'number'%3A%0A return Number(<number>value)%0A case 'boolean'%3A%0A return Boolean(<boolean>value)%0A case 'string'%3A%0A return String(<string>value)%0A case 'object'%3A%0A default%3A%0A if (value %3D%3D null) {%0A return Null(<null>value)%0A } else if (value.constructor.name %3D%3D%3D "Array") {%0A return Array(<JSONArray>value)%0A } else {%0A return Object(<JSONObject>value)%0A }%0A }%0A }%0A%0Aconst type %3D match%0A ( value %3D> 'null'%2C%0A value %3D> value.toString()%2C%0A value %3D> value.toFixed()%2C%0A value %3D> value.toUpperCase()%2C%0A array %3D> '(' %2B array.map(type).join('%2C ') %2B ')'%2C%0A object %3D> 'object')%0A) of such API that is still not inferred correctly:

**Comment by aluanhaddad** [comment]
Sorry, I believe I missed the point. I did not see why you would need to acquire the discriminator if you already knew the type and vice versa.

**Comment by niieani** [comment]
It would be great if one could do this:

```ts
function typeOf(shape: Shape) {
  if (shape.size) return "Square" as "Square" & shape is Square
  else if (shape.radius) return "Circle" as "Circle" & shape is Circle
  else return "Rectangle" as "Rectangle" & shape is Rectangle
}
```

Generally, if the current constraint that you need to return a `boolean` when returning "param is T" would be lifted, we could add some very useful type guards.

Also, guarding for more than one parameter is currently unavailable too, it would be nice to be able to return any type AND multiple type guards, i.e. `(shape is Square) & (otherParam is T)`.

**Comment by RyanCavanaugh** [comment]
Even if this legal from an outer perspective, it wouldn't be terribly useful in the type system since you couldn't store the result in a variable (because TS doesn't track relationships between variables and other variables when tracing the control flow graph). There are a lot of other ways you could write this (e.g. returning a synthesized object with a real discriminant) to accomplish the intended effect.
