### ISSUE TITLE
Error if a function don't use first param but uses others

### ISSUE THREAD

**Issue by dmikis** [Microsoft/TypeScript#16062]
**TypeScript Version:**  2.3.3

**Code**

```ts
function foo(a: any, b: any): void {
    console.log(b);
}
```

`noUnusedParameters: true` in `tsconfig.json`.
**Expected behavior:**

No errors.

**Actual behavior:**

Error about a being unused.

**Comment by mhegazy** [comment]
Parameters with `_` in their name are exempt from the check, so either rename the first parameter to `_a` or disable `--noUnusedParameters`

**Comment by mhegazy** [comment]
Docs available at https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#flag-unused-declarations-with---nounusedparameters-and---nounusedlocals

**Comment by dmikis** [comment]
Why not detect that since we use `b` we're **forced** to specify `a`? JS static analysis tools (closest analog I can think of) do that.
