### ISSUE TITLE
Codefix & refactoring contexts have APIs that slightly differ for no apparent reason

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#16071]
I'm currently writing a refactoring, but I'm running it through the codefix API so I can actually iterate and test on it in VS Code. To do so, I wrote this wonderful hack that takes a codefix context and converts it to a refactoring context.

```ts
    function getCodeFixActions(ctxt: CodeFixContext) {
        const refactorContext: RefactorContext = {
            ...ctxt,
            startPosition: ctxt.span.start,
            endPosition: ctxt.span.start + ctxt.span.length,
            file: ctxt.sourceFile,
        };
        // ...
    }
```

Notice that

1. One API uses `file` and the other uses `sourceFile`.
2. One API uses `startPosition` and `endPosition` while the other uses a `span` with a `start` & `length`.

At the very least, could the first be addressed?

**Comment by RyanCavanaugh** [comment]
Changed in #16278 and it makes more sense now
