### ISSUE TITLE
Proposal: polyfill or covert [includes] method with target < es5

### ISSUE THREAD

**Issue by e-cloud** [Microsoft/TypeScript#16079]
**TypeScript Version:**  2.3.2

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
const str = "hello world"
if(str.includes("hello")) {
  // do something
}
```

with compile target as **es5**
**Expected behavior:**
```js
var str = "hello world"
if(str.indexOf("hello") > -1) {
  // do something
}
```
**Actual behavior:**
```js
var str = "hello world"
if(str.includes("hello")) {
  // do something
}
```

An unreasonable thing is some of members refuse to support that feature for ES2016 not being widely used in #2340. However, async and await features in ES2017 are supported by TS 2.3.

Therefore, i think it's time to revisit this requirement.
Otherwise, I have to use babel to transpile the ts output. That's really really ugly and stupid.

**Comment by RichiCoder1** [comment]
I'm curious, is there a reason you couldn't include a polyfill? As far as I'm aware, TypeScript only attempted to transpile language features, not library functions.

**Comment by mhegazy** [comment]
This has been one of the [design goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals#goals) to first impose no additional runtime cost. as a developer you have full control on what polyfills to include, and what to avoid.  and second TS does make any type-directed emit. this allows you to use the compiler in a transpile mode where every file is processed in isolation.
