### ISSUE TITLE
noUnusedLocals: Don't count self-call in recursive function

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#16078]
**TypeScript Version:**  nightly (2.4.0-dev.20170525)

**Code**

```ts
function f(): void { f(); }
```

**Expected behavior:**

Function `f` is unused.

**Actual behavior:**

No error.

(Ref: palantir/tslint#1937)

**Comment by mhegazy** [comment]
how far do we want to go with this? is a class that is only instantiated in an instance method the same? a var that is only referenced in its own intializer? etc..

**Comment by andy-ms** [comment]
It makes sense to disclude *any* use of a class inside itself, since the self-references won't be used unless the class is. But I don't think I would treat instantiation specially, since it's hard to when a reference to a class might instantiate it.

```ts
class C {
    static s() {
        new C().m();
    }

    m() {
        new C();
    }
}

maybeThisInstantiatesIt(C);

function maybeThisInstantiatesIt(klass: any) {
    klass.s();
}
```

Without the `maybeThisInstantiatesIt(C)` call, I would definitely mark the class as unused.

**Comment by aozgaa** [comment]
On the other hand, the mere presence of a static property may be side-affecting in its initialization, so the following code, which marks `D` unused today, actually uses the static initialization of `s`.
``` ts

function sideAffecting(): number {
    console.log("called");
    return 10;
}

function foo() {
    class C {
        static s: number = sideAffecting();
    }
}
foo();
```

But perhaps this should be a separate issue.

**Comment by andy-ms** [comment]
`D` itself is unused though, so TypeScript is correctly telling you that your code stinks. Similarly, if you write `const x = sideAffecting();` we will give you an unused-variable error.

**Comment by falsandtru** [comment]
I agree with @andy-ms . This is an issue on checking recursive functions. We don't need to consider classes.

@aozgaa In your case, `D` should be unused, and `sideAffecting` should be used.
