### ISSUE TITLE
How to use bundle-loader to load js file with requires?

### ISSUE THREAD

**Issue by EysaDun** [Microsoft/TypeScript#16073]
**TypeScript Version:**  2.2.1 / nightly (2.2.0-dev.201xxxxx)

**import * as ArticleDetailContainer from 'bundle-loader?lazy!../containers/article/ArticleDetailContainer'
**

```ts
// A *self-contained* demonstration of the problem follows...

```

**Expected behavior:**
this code was error,VS 2017 throw a error: can not find module '....'
**Actual behavior:**
Can you give me some suggestion about bundle-loader in TypeScript?
or a blog can direct me to complete this task.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
