### ISSUE TITLE
Discriminated Union accept wrong assignment

### ISSUE THREAD

**Issue by DarkHarlock** [Microsoft/TypeScript#16074]
**TypeScript Version:**  2.3.2

**Code**

```ts

interface Square {
    kind: "square";
    size: number;
}
interface Circle {
    kind: "circle";
    radius: number;
}

type Shape = Square | Circle;
var shape: Shape = { kind: "square", size: 4, radius: "`radius` does not exists in `square` and also accept a string even if in `circle` is defined as `number`" };

```

**Expected behavior:**
Compiler error:
`Object literal may only specify known properties, and 'radius' does not exist in type 'Square'.`
or at least, if for some reasons the field `radius` can exists on `Shape`,
`Type 'string' is not assignable to type 'number'.`

**Actual behavior:**
No errors.

**Comment by RyanCavanaugh** [comment]
Duplicate #12745

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
