### ISSUE TITLE
Formatting of lines starting from `;`

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/TypeScript#16082]
Well, this is the special case for people developing without semicolons, sometimes we need to do such trick:

```ts
const x = obj
  // next line we start with semicolon, not to get the error
  //typescript formatter inserts indent spaces before it
  ;(something as Type).doThis(...)
```

So, currently, typescript formatter inserts indent spaces before it. Can it be handled/changed?

**Comment by mhegazy** [comment]
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/10392

**Comment by whitecolor** [comment]
So it seems to be `Wont fix` or what?

**Comment by mhegazy** [comment]
> So it seems to be Wont fix or what?

correct.

**Comment by whitecolor** [comment]
So it is not possible to work it around any how?

**Comment by mhegazy** [comment]
Other than putting the semicolon on the previous line, no.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
