### ISSUE TITLE
Infer type parameters that are not supplied

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/TypeScript#16083]
This question was probably already discussed somewhere, kind of general issue (probalby some related bigger issue is out there). If we have some signature for function TS will try to infer params only if we don't supply any type params. But will NOT try to infer if we supply any and will demand all the params (except for default since 2.3)

So the simple case:
```ts
// property getter maker
const prop =
  <Obj extends {[K in P]?: {}}, P extends string>(prop: P):
  (obj: Obj) => Obj[P] => {
  return (obj) => obj[prop]
}
type ObjA = { a: 1 }

// So to get type checking on property getter, I need to do
// it will check if type `ObjA` has property 'a'
prop<ObjA, 'a'>('a')
```

Why is it not possible to supply explicit `Obj` param for this case and infer second `P` param? It doesn't seem to be complex.

With default syntax I think it would look like this:

```ts
const prop =
  <Obj extends {[K in P]?: {}}, P extends string = P>(prop: P):
```
so that if P not supplied, it would be inferred. But it doesn't work.

**Comment by mhegazy** [comment]
> so that if P not supplied, it would be inferred. But it doesn't work.

Type parameters are either all specified or all inferred. https://github.com/Microsoft/TypeScript/issues/10571 tracks enabling some partial type inference.

**Comment by whitecolor** [comment]
@mhegazy thanks, then would close. Not sure if community is capable of doing such things)
