### ISSUE TITLE
Emit format for methods and accessors in object literals

### ISSUE THREAD

**Issue by JsonFreeman** [Microsoft/TypeScript#1608]
```ts
var obj = { foo() { } };
```
emits as
```js
var obj = { foo: function () {
} };
```

Note the extra newline

**Comment by ahejlsberg** [comment]
We do that for all function bodies, regardless of how they are written. Not sure I agree this is a bug.

**Comment by JsonFreeman** [comment]
I will leave it open and let others decide.

**Comment by DanielRosenwasser** [comment]
The way I see it, we should continuously be improving our emit to get closer to the way the user originally wrote it.

**Comment by yuit** [comment]
It will be nicer if we preserve the user or may be insert new line at the beginning of foo

**Comment by ahejlsberg** [comment]
If we're going to have a bug on this it should be a general suggestion to more accurately preserve white space formatting in the emitted code. We don't do that right now (by design) and this is particular example is just one of and endless number of ways in which we reformat the code.

**Comment by JsonFreeman** [comment]
I'm not really talking about preserving white space. This is more about emitting empty function bodies on one line instead of two.

**Comment by RyanCavanaugh** [comment]
It's not like we're emitting poorer-formatted code than we got *on purpose*, but I don't see this as a high-priority thing either.
