### ISSUE TITLE
Please make default import check __esModule flag at runtime!

### ISSUE THREAD

**Issue by BurtHarris** [Microsoft/TypeScript#16090]
**TypeScript Version:**  2.3.3
**Input Code**

My example is from a `.js` file with --allowJs.   I've tried with and without --allowSyntheticDefaultImports, doesn't seem to make a difference.

```
import chai from 'chai'
const should = chai.should();
```

**Expected behavior:**
I *think* this should generate something like:

```
var chai_1 = require("chai");
var should = chai_1.__esModule ? chai_1.default.should() : chai_1.should();
```

**Actual behavior:**

```
var chai_1 = require("chai");
var should = chai_1.default.should();

```
**babel's output**
```
Here's what I've seen babel generate.  

var _chai = require('chai');
var _chai2 = _interopRequireDefault(_chai);
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
var should = _chai2.default.should();
```

**workaround**
Obviously I can work around this with a change to the input code:

```
import * as chai from 'chai'
const should = chai.should();
```

**Comment by aluanhaddad** [comment]
Yes it should! See #16093 🎉 🎉

**Comment by fatcerberus** [comment]
It'll be great to see this change.  I recently switched from Babel to TS as my transpiler for miniSphere as it's so much faster, but since I support both CommonJS and ES modules, my standard library is entirely CJS.  The change broke a few modules as a result.

**Comment by BurtHarris** [comment]
Updated title to make it a request rather than a question.

**Comment by mhegazy** [comment]
tracked by #16093

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
