### ISSUE TITLE
'never' isn't inferred for object property type after exhaustive type guards check 

### ISSUE THREAD

**Issue by fictitious** [Microsoft/TypeScript#16091]
**TypeScript Version:**  2.3.2

**Code**

```ts

let sn = Math.random() < 0.5 ? 'a' : 0; // string | number
let dsn = { data: sn };                 // {data: string | number}

function isDataString(t: { data: string | number }): t is { data: string } { return typeof t.data === 'string' }
function isDataNumber(t: { data: string | number }): t is { data: number } { return typeof t.data === 'number' }

if (isDataString(dsn)) {
    let v = dsn.data;  // inferred as let v: string
} else if (isDataNumber(dsn)) {
    let v = dsn.data;  // inferred as let v: number
} else {
    let v = dsn.data;  // inferred as let v: string | number. shouldn't it be never?.
    v = '2'; // ok
}

```

**Expected behavior:**

`v` should be inferred to have `never` type, as in the identical example for a simple value of  `string | number` type:

```ts
function isString(t: string | number): t is string { return typeof t === 'string' }
function isNumber(t: string | number): t is number { return typeof t === 'number' }

if (isString(sn)) {
    let v = sn;
} else if (isNumber(sn)) {
    let v = sn;
} else {
    let v = sn; // never, as expected
    v = '2'; //Type '"2"' is not assignable to type 'never'
}


```

**Actual behavior:**

Type guards checking for a type of object property are somehow less suited for type inference, compared to type guards for primitive values.

**Comment by mhegazy** [comment]
these ar not unit types; objects can have additional properties other than the tags. so the condition can only assert that within the true branch that they have these types, but can not assume that the set of possible types is finite like in the case of unit types or primitives.
for instance your object `dns` could be `{ data: sn, other: 1 }`, failing both checks does not mean it is `never`, it just means it is not narrowed.

**Comment by fictitious** [comment]
Why is it narrowed when it's a union of literal types, and uses built-in type guards? How is it different from this:

```
let sn: 'a' | 'b' = Math.random() < 0.5 ? 'a' : 'b'; 
let dsn = { data: sn };                 // {data: "a" | "b"}

if (dsn.data === 'a') {
    let v = dsn.data;  // inferred as let v: "a"
} else if (dsn.data === 'b') {
    let v = dsn.data;  // inferred as let v: "b"
} else {
    let v = dsn.data;  // inferred as let v: never
    v = '2'; // Type '"2"' is not assignable to type 'never'
}
```

**Comment by mhegazy** [comment]
these are considered ["tags" on types](https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#tagged-union-types).

**Comment by fictitious** [comment]
So, does that mean basically that  the condition `if (typeGuardOn(something.foo))` is narrowing the type of `something` and not type of `something.foo`?  That was not obvious for me from documentation.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
