### ISSUE TITLE
rootDir uncomfortable behavior

### ISSUE THREAD

**Issue by baklanovavpulter** [Microsoft/TypeScript#16097]
**TypeScript Version:**  2.3.3

On Windows. Here I'm using command line, but the same behaviour with using tsconfig file. The same with rootDirs option.

**Case 1: All works fine**

*Code*
```batch
tsc --listFiles "../src/a.ts"
```
*Expected behavior:*
```
C:/Program Files (x86)/Microsoft SDKs/TypeScript/2.3/lib.d.ts
../src/a.ts
```
*Actual behavior:*
```
C:/Program Files (x86)/Microsoft SDKs/TypeScript/2.3/lib.d.ts
../src/a.ts
```

**Case 2: Nothing works**

*Code*
```batch
tsc --listFiles --rootDir ".." "src/a.ts"
```
or
```batch
tsc --listFiles --rootDir ".." "/src/a.ts"
```
or
```batch
tsc --listFiles --rootDir "../" "src/a.ts"
```
*Expected behavior:*
```
C:/Program Files (x86)/Microsoft SDKs/TypeScript/2.3/lib.d.ts
../src/a.ts
```
*Actual behavior:*
```
error TS6053: File 'src/a.ts' not found.
C:/Program Files (x86)/Microsoft SDKs/TypeScript/2.3/lib.d.ts
```

**Case 3: Works, but it's ugly**

*Code*
```batch
tsc --listFiles --rootDir "..\" "src/a.ts"
```
*Expected behavior:*
```
C:/Program Files (x86)/Microsoft SDKs/TypeScript/2.3/lib.d.ts
../src/a.ts
```
*Actual behavior:*
```
C:/Program Files (x86)/Microsoft SDKs/TypeScript/2.3/lib.d.ts
D:/Projects/_Tests/tsc/typescript-rootrir-issue/src/a.ts
```
Why full path to "a.ts" now? Why necessary "\" at the end of rootDir?

**Case 4: Can't make it beauty**

*Code*
```batch
tsc --listFiles --rootDir ".." "\src\a.ts"
```
*Expected behavior:*
```
C:/Program Files (x86)/Microsoft SDKs/TypeScript/2.3/lib.d.ts
D:/Projects/_Tests/tsc/typescript-rootrir-issue/src/a.ts
```
*Actual behavior:*
```
error TS6053: File '/src/a.ts' not found.
C:/Program Files (x86)/Microsoft SDKs/TypeScript/2.3/lib.d.ts
```

**Comment by baklanovavpulter** [comment]
**Case 5: Still can't make it work**

*Code*
```batch
tsc --listFiles --rootDir "..\" "../src/a.ts"
```
or
```batch
tsc --listFiles --rootDir "..\..\" "src/a.ts"
```
*Expected behavior:*
```
C:/Program Files (x86)/Microsoft SDKs/TypeScript/2.3/lib.d.ts
../../src/a.ts
```
*Actual behavior:*
```
Version 2.3.3
Syntax:   tsc [options] [file ...]
...
```

**Case 5: Still can't make it work**

*Code*
```batch
tsc --listFiles --rootDir "..\\..\\" "src/a.ts"
```
or
```batch
tsc --listFiles --rootDir "..\\.." "src/a.ts"
```
or
```batch
tsc --listFiles --rootDir "..\\" "../src/a.ts"
```
*Expected behavior:*
```
C:/Program Files (x86)/Microsoft SDKs/TypeScript/2.3/lib.d.ts
../../src/a.ts
```
*Actual behavior:*
```
error TS6053: File 'src/a.ts' not found.
C:/Program Files (x86)/Microsoft SDKs/TypeScript/2.3/lib.d.ts
```

**Comment by mhegazy** [comment]
I am not sure i understand the issue, is it that `--listFile` does not always return absolute paths?

**Comment by baklanovavpulter** [comment]
On my windows console - it depends on how you specify input files. See first example in initial post - it's all real console output.

**Comment by baklanovavpulter** [comment]
This issue in that I can't set to rootDir any folder outside project root (term "project root" means "tsconfig.json" folder or compiler current dir).

**Comment by baklanovavpulter** [comment]
Example project files:
```
./src/a.ts
./proj/tsconfig.json
```
In this example I still haven't found way to correct set rootDir to "../../src" without compile error.

**Comment by mhegazy** [comment]
can you share a self contained repro?

**Comment by baklanovavpulter** [comment]
https://github.com/baklanovavpulter/typescript-rootdir-issue

**Comment by mhegazy** [comment]
rootDir has nothing to do with inclusion. the only use of `rootDir` is to specify the root of the folder that the compiler is recreating in `outDir`. if you are not using `outDir`, do not use `rootDir`. sorry if the name of the flag suggested something different.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
