### ISSUE TITLE
Error not meaningful for Number Type

### ISSUE THREAD

**Issue by ramasamykasiviswanathan** [Microsoft/TypeScript#16098]
**TypeScript Version:**  2.3.3

**Code**
var num : number;

num = 0xABE;  //Assigning HexaDecimal Value.

num = (function (){
  return 0b1011;
})(); //lets assume a function call returns binary value rather than HexaDecimal.

```ts
// When I run tsc getting error as "error TS1005 : ';' expected.".
If I return Hexa-decimal value (e.g. return 0xCE) it works fine without any error.
I'm a novice TypeScript programmer, so didn't tweak anything.
```

**Expected behavior:**
It should accept as both are of same data type
**Actual behavior:**
Error stating "error TS1005 : ';' expected."

**Comment by ikatyang** [comment]
I cannot reproduce this behavior, it works fine for me, did I misunderstand something?

(test.ts)

```ts
var num: number;

num = 0xABE;

num = (function () {
  return 0b1011;
})();
```

```
node_modules/.bin/tsc test.ts
```

(test.js)

```js
var num;
num = 0xABE;
num = (function () {
    return 11;
})();

```

**Comment by ramasamykasiviswanathan** [comment]
For me I could see the error if I run tsc <filename>.ts (tested now as well)
Not sure what has caused the problem, anyways if it works fine for you without any error you may close this.

**Comment by aluanhaddad** [comment]
This works fine in the playground as well. It looks like you have a syntax error in code that is not part of your example.
