### ISSUE TITLE
Defining a type for the result of a dynamic expression

### ISSUE THREAD

**Issue by pospi** [Microsoft/TypeScript#16100]
I have searched far and wide for a way to do this so apologies if is an answered question, or simply "not thinking Typescript" (I have come from Flow).

Say I have something like this:

```
const config = {
  all: { /*... */ },
  test: { /*... */},
  development: { /*... */},
  production: { /*... */  },
}

const conf: Config = Object.assign({}, config.all, config[config.all.env])
export default conf
```

Is there a way to define that the exported object has this shape? I always get `Module [...] has no exported member 'env'` when I try this.
I found an older article which indicated the syntax was `const conf = <Config> Object.assign({}, config.all, config[config.all.env])`, but this simply caused a compile error which isn't surprising considering the presence of JSX parsing.

**TypeScript Version:**  2.2.2

**Comment by ikatyang** [comment]
Did you mean the following code?

![image](https://cloud.githubusercontent.com/assets/8341033/26495511/7663ea0a-4256-11e7-8c55-548c275ab7e3.png)

It seems you just export `default`, and you want to `import {env} from 'path/to/config'` ?

**Comment by pospi** [comment]
Ah! The `exports =` is the syntax I needed. Thanks!
