### ISSUE TITLE
Unknown compiler option 'exclude'

### ISSUE THREAD

**Issue by geoctrl** [Microsoft/TypeScript#16103]
**TypeScript Version:**  2.2.3

**Code**
```shell
$ tsc
```

```ts
// tsconfig.json
{
  "compilerOptions": {
    "declaration": true,
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false,
    "outDir": "dist",
    "typeRoots": [
      "./node_modules/@types/"
    ],
    "exclude": [
      "dist"
    ]
  }
}
```

**Expected behavior:**
Exclude the list of paths given.

**Actual behavior:**
Throws error: `error TS5023: Unknown compiler option 'exclude'`

**Last Note**
This also occurs when using the options `include` or `files`. Were these options depreciated in a recent update to typescript? I can't find any documentation to suggest this...

**Comment by ikatyang** [comment]
Actually, `files`, `include`, etc. are top level fields

```json
{
  "compilerOptions": {},
  "exclude": []
}
```

**Comment by mhegazy** [comment]
more docs available at http://www.typescriptlang.org/docs/handbook/tsconfig-json.html

**Comment by geoctrl** [comment]
@ikatyang thanks - can't believe I missed that 🙄

**Comment by noobfan-kevin** [comment]
{
  "compilerOptions": {
    "declaration": true,
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false,
    "outDir": "dist",
    "typeRoots": [
      "./node_modules/@types/"
    ]
  },
    "exclude": [
      "dist"
    ]
}
