### ISSUE TITLE
Function.prototype.bind and setTimeout are typed unfortunately

### ISSUE THREAD

**Issue by andyfriesen** [Microsoft/TypeScript#16105]
**TypeScript Version:**  2.3.3

**Code**

Note that this requires the `@types/node` package to demonstrate.  I have a full example project here to make replication straightforward: https://github.com/andyfriesen/ts-bind-any .  Run `npm i --only=dev && ./node_modules/.bin/tsc -p .`

```ts
class A {
  sayHi() {
    console.log('Hello!');
  }
}

const a = new A();

const t1: NodeJS.Timer = setTimeout(() => a.sayHi(), 500); // Line 10
const t2: NodeJS.Timer = setTimeout(a.sayHi.bind(a), 500); // Line 11
```

**Expected behavior:**
No errors.

**Actual behavior:**
Error on line 11: error TS2322: Type 'number' is not assignable to type 'Timer'.

There are a few things going on here.

First, `Function.prototype.bind` is typed to produce an `any`.  While still not perfect, it would be nice if it returned something like `(...args: any[]) => any`.

Secondly, `lib.d.ts` defines setTimeout thus:
```ts
declare function setTimeout(handler: (...args: any[]) => void, timeout: number): number;
declare function setTimeout(handler: any, timeout?: any, ...args: any[]): number;
```

I can't find any documentation or evidence that setTimeout can accept anything other than a function or a string.  If so, the second overload could be tightened up without breaking any working programs.

Lastly, it's a bit unfortunate that these definitions for `setTimeout` are available by default from lib.d.ts.  On Node, `setTimeout` never returns a number.

**Comment by aluanhaddad** [comment]
> Lastly, it's a bit unfortunate that these definitions for setTimeout are available by default from lib.d.ts. On Node, setTimeout never returns a number.

Seems like they should be moved into `lib.dom.d.ts` but that would be a breaking change.

**Comment by Kovensky** [comment]
Using both DOM and Node definitions is always a big problem for `setTimeout` / `clearTimeout` typings. Node fights with the DOM definition and wins :cry:

**Comment by mhegazy** [comment]
use `--lib core` or `--lib es6` if you are using node.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
