### ISSUE TITLE
ES6 Map to Array @ Typescript

### ISSUE THREAD

**Issue by yoyo837** [Microsoft/TypeScript#16101]
First, my English is very poor...

**TypeScript Version:**  2.3.2

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
const map = new Map<number, any>();

[...map] 
```
Can not convert to array?
**Expected behavior:**
array []
**Actual behavior:**
message: 'Type 'IterableIterator<Stock>' is not an array type.'

What should I do to make it work fine？
Thank you,

**Comment by ikatyang** [comment]
?

![image](https://cloud.githubusercontent.com/assets/8341033/26495112/b1827252-4254-11e7-8821-e3376d5f91c3.png)

**Comment by aluanhaddad** [comment]
@yoyo837 You need to specify the `--downlevelIteration` flag.

**Comment by DanielRosenwasser** [comment]
Use the `downlevelIteration` flag like @aluanhaddad said (along with the appropriate `"lib": ["es2015", "dom"]` flag).

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
