### ISSUE TITLE
how do i get a type guard that narrows to a type with a certain property

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#16118]
say i am interested in getting an object of `Data` where 
```
interface Data {
    value: number;
}
```
i am given what looks like an empty object `{}` that might or might now be a valid instance of `Data`

in order to figure it out i need to verify that it has all properties i am interested in, if so i can say that it is an instance of `Data`

so i wish i could do it property by property with a help   of type guards

so if i had a type guard that could verify that a certain property is there i could just apply it a few times to make sure all properties that i need are there

so why doesn't the following work:

```typescript
function hasProperty<T extends object, N extends keyof T>(something: {}, name: N): something is { [N]: T[N}; } {
    return name in something;
}

function toData(something: {}): Data {
    if (hasProperty(something,  'value')) {
        return something;
    } else {
        throw new Error('Invalid data.');
    }
}

```

?

**Comment by aluanhaddad** [comment]
It is not working because the inferred type of the key is `never`. This happens because `T` is inferred from `something` which is `{}`.
```ts
function hasProperty<N extends string>(something: {}, name: N): something is {[P in N]: any} {
    return name in something;
}
```
May be what you are after.

**Comment by aleksey-bykov** [comment]
@aluanhaddad thanks, this is what i end up with, have a hard time to find what exactly `P in N` is


```typescript
function hasAt<T extends object, N extends keyof T>(something: {}, name: N, is: (value: Unknown) => value is T[N]): something is {[P in N]: T[N]; } {
    if (name in something) {
        const value = (something as any)[name];
        return is(value);
    } else {
        return false;
    }
}
```

**Comment by ahejlsberg** [comment]
@aleksey-bykov For inspiration you may want to check out [io-ts](https://github.com/gcanti/io-ts). There are some clever ideas in there you might be able to use.

**Comment by aleksey-bykov** [comment]
i saw it, quite impressive, i like the overall idea, would implement it slightly differently in a more functional way (without classes and mutations)
