### ISSUE TITLE
Contextual typing of object literal getters not working for return expressions

### ISSUE THREAD

**Issue by JsonFreeman** [Microsoft/TypeScript#1611]
```ts
interface I {
    x: (p: number) => void;
}

var obj: I = {
    get x() {
        return q => { };
    }
}
```

q has type any, but should be number.

This is related to #1610

**Comment by JsonFreeman** [comment]
We should probably do this for setters too. The parameter of the setter would acquire the contextual type if it has no type annotation, and a default initializer would also be contextually typed.

**Comment by RyanCavanaugh** [comment]
Punting based on complexity (due to how we might fix the type of `q` during overload resolution) and lack of feedback.
