### ISSUE TITLE
Change or reassign object typing dynamically for better intellisense

### ISSUE THREAD

**Issue by Alphapage** [Microsoft/TypeScript#16127]
Hello,

I asked a question to stackoverflow without success:
https://stackoverflow.com/questions/44203804/change-or-reassign-object-typing-dynamically-in-typescript

Is it possible or do you plan to implement this feature ?

Thanks in advance for your help.

**Comment by RyanCavanaugh** [comment]
This is a bug tracker, not a support forum.

**Comment by Alphapage** [comment]
Ok, no problem. I will try to find a workaround for this limitation in typescript.
