### ISSUE TITLE
Add support for diff3-style git merge markers

### ISSUE THREAD

**Issue by katemihalikova** [Microsoft/TypeScript#16129]
**TypeScript Version:** (2.4.0-dev.20170528)

**Code**
When merging files with conflicting changes, git puts both changes together with conflicts markers that are correctly supported by TypeScript (markers emit `TS1185` errors and only the first block is used, the other one is treated as a comment):
```ts
class C {
<<<<<<< HEAD
   v = 1;
=======
   v = 2;
>>>>>>> Branch - a
}
```
Unfortunately, in many cases it is not sufficient to have just both changes to successfully resolve the conflict. Git also supports `diff3` style (`merge.conflictStyle = diff3`) that shows common ancestors block in addition to both conflicting changes, it is thus superset of the default algorithm:
```ts
class C {
<<<<<<< HEAD
   v = 1;
||||||| merged common ancestors
   v = 3;
=======
   v = 2;
>>>>>>> Branch - a
}
```

**Expected behavior:**
I'd expect the common ancestors token `|||||||` be also recognised as merge token `TS1185` and content of this block be treated as a comment.
```livescript
test.ts(2,1): error TS1185: Merge conflict marker encountered.
test.ts(4,1): error TS1185: Merge conflict marker encountered.
test.ts(6,1): error TS1185: Merge conflict marker encountered.
test.ts(8,1): error TS1185: Merge conflict marker encountered.
```
```javascript
var C = (function () {
    function C() {
        this.v = 1;
    }
    return C;
}());
```

**Actual behavior:**
Currently it parses the `|||||||` token as three `||` and one `|`, emits several errors that are unrelated to the root cause (git merge) and the javascript output is wrong.
```livescript
test.ts(2,1): error TS1185: Merge conflict marker encountered.
test.ts(4,1): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
test.ts(4,3): error TS1109: Expression expected.
test.ts(4,5): error TS1109: Expression expected.
test.ts(4,7): error TS1109: Expression expected.
test.ts(4,16): error TS1005: ';' expected.
test.ts(4,23): error TS1005: ';' expected.
test.ts(6,1): error TS1185: Merge conflict marker encountered.
test.ts(8,1): error TS1185: Merge conflict marker encountered.
test.ts(9,1): error TS1128: Declaration or statement expected.
```
```javascript
var C = (function () {
    function C() {
        this.v = 1;
    }
    return C;
}());
    ||  ||  ||  | merged;
common;
ancestors;
v = 3;
```
**Fix:**
I've already made a fix while trying to resolve this for me in 1ccbaab and added tests in 64a754c.

**Comment by RyanCavanaugh** [comment]
Sounds like a good idea. That commit you have looks basically ready (probably undo the `ch` rename just to minimize changed lines), care to send a PR?

**Comment by katemihalikova** [comment]
Sure, will send in a moment. Thanks!

**Comment by DanielRosenwasser** [comment]
@CyrusNajmabadi in case you're interested in this too.

**Comment by CyrusNajmabadi** [comment]
Thanks for letting me know.  We'll make a similar change to Roslyn if we hear any feedback about this.
