### ISSUE TITLE
Intellisense should understand clodules/fundules

### ISSUE THREAD

**Issue by danquirk** [Microsoft/TypeScript#1612]
Intellisense currently only has 1 completion list item and no special icon to indicate various merged declaration types. When looking at a clodule in an Intellisense list it appears to only be a module (via icon and description) with no clear indication it is also a class. Likewise for fundules. We could consider having separate completion list items for each part of the merged declaration, or create a new icon/display scheme for them.

**Comment by mhegazy** [comment]
In general we do not find users aware of these merged constructs. more over adding new icons requires changes to different places of the system, and i am not sure the value gained justifies the cost.
