### ISSUE TITLE
Formatter: indent switch case

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#16124]
**TypeScript Version:**  nightly (typescript@2.4.0-dev.20170528)

**Code**

Type:

```ts
switch (x) {
    case 0:
```

Hit enter and type `break;`.

**Expected behavior:**

```ts
switch (x) {
    case 0:
        break;
```

**Actual behavior:**

```ts
switch (x) {
    case 0:
    break;
```

Formatting the entire document will correctly indent the `break;`.

**Comment by mhegazy** [comment]
but hitting <enter> or adding `;` should format it..

**Comment by andy-ms** [comment]
My bad. Must have been testing in vscode which doesn't appear to make any formatting requests to tsserver. This works in visual studio.
