### ISSUE TITLE
Wrong tab-size in Playground

### ISSUE THREAD

**Issue by mindplay-dk** [Microsoft/TypeScript#16128]
Looks like you accidentally set the tab-width to 8 spaces in the playground?

All of your examples use 4 spaces.

**Comment by RyanCavanaugh** [comment]
I don't see this happening. Writing
```ts
var p = {
m: 2
};
```
and formatting results in 4 spaces on the second line.

**Comment by mindplay-dk** [comment]
Working normally again now. Odd.
