### ISSUE TITLE
Compiling TypeScript files with doc-comments should automatically add the correct type to documented parameters

### ISSUE THREAD

**Issue by javacoolme** [Microsoft/TypeScript#16125]
**TypeScript Version:**  2.3.2

**Code**

```ts
/**
 * Some test function.
 * @param arg An argument.
 */
function test(arg: string) {
    // Do something here...
}
```

**Expected behavior:**
Compiling the TypeScript file results in the following code:
```javascript
/**
 * Some test function.
 * @param {string} arg An argument.
 */
function test(arg) {
    // Do something here...
}
```

**Actual behavior:**
Compiling the TypeScript file results in the following code:
```javascript
/**
 * Some test function.
 * @param arg An argument.
 */
function test(arg) {
    // Do something here...
}
```

Compiling TypeScript files with doc-comments should automatically add the correct type to documented parameters.

**Comment by mhegazy** [comment]
Already tracked by https://github.com/Microsoft/TypeScript/issues/10

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
