### ISSUE TITLE
More specific DOM types (especially for checkJs)

### ISSUE THREAD

**Issue by cyrilletuzi** [Microsoft/TypeScript#16138]
**TypeScript Version:**  2.3.3

**Code**

In a JavaScript file (_not_ TypeScript), with `checkJs` option enabled.

```js
let elementRoot = document.getElementById('test');

if (elementRoot) {

  /** @type {HTMLElement} */
  let elementFirstChild = elementRoot.children[0];
  
}
```

**Actual behavior:**

It raises the error `[js] Type 'Element' is not assignable to type 'HTMLElement'`. If switching back to type `Element`, Intellisense will be wrong and other errors will be raised when I'll use `elementFirstChild` like a HTML element, for example by setting styles : `elementFirstChild.style.color = 'red';`.

**Expected behavior:**

`elementFirstChild` should be of type `HTMLElement` instead of `Element`, because if `elementRoot` is an HTMLElement, its `children` will be too.

In TS files, we solve this situation with type casting : `elementRoot.children[0] as HTMLElement`.

But in JS files with the `checkJs` option, type casting is not possible as it's not valid JS (even if TS allows it while checking). So we're stuck, and the only (bad) solution is a `// @ts-ignore`.

It would be better for TS files too. And there may be similar issues with other DOM properties.

I know that some DOM types are already inferred dynamically (like with `createElement`), is there a specific reason it's not the case here ? If none, I can try to take care of the PR.

**Comment by cyrilletuzi** [comment]
Same problem with `event.target`.

**Comment by mhegazy** [comment]
Adding type assertion support is tracked by https://github.com/Microsoft/TypeScript/issues/15618#issuecomment-300632637

**Comment by cyrilletuzi** [comment]
Will the issue you mention resolve this case ? Because the relation between the two cases (this one and the one from the other issue) is not obvious to me.

**Comment by mhegazy** [comment]
#15618 tracks adding type assertion syntax. so you would write your example as

```ts
let elementRoot = /** @type {HTMLDIVElement} */ document.getElementById('test');
```

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Comment by cyrilletuzi** [comment]
#15618 is marked as closed as the corresponding PR is merged. But I tried with `typescript@next` (2.5 at the moment) and it does not work.
