### ISSUE TITLE
Array.isArray on object index does not set type for that object index

### ISSUE THREAD

**Issue by Arlen22** [Microsoft/TypeScript#16146]
**TypeScript Version:**  2.3.2

**Code**

```ts
function getQueryString(query?: { [k: string]: string | string[] }){
  return Object.keys(query).map(a => {
    return Array.isArray(query[a] as string[]) ? query[a].join(',') : query[a];
  });
}
```

**Expected behavior:**
When Array.isArray(query[a]) returns true, query[a] should be expected to be an array. Or can we not guarantee that `a` has not changed somehow?

**Actual behavior:**
**Typescript red underline on `.join(',')`.**

> Property 'join' does not exist on type 'string | string[]'.
>   Property 'join' does not exist on type 'string'.

**Comment by zoltan-mihalyi** [comment]
- type guards does not work on complex expressions (query[a]), they work on member expressions however (query.x)
- no need to cast query[a] to string[] in isArray check, and this makes it a complex expression.

Introducing a new variable solves the problem:
```typescript
function getQueryString(query?: { [k: string]: string | string[] }){
    return Object.keys(query).map(a => {
        const q = query[a];
        return Array.isArray(q) ? q.join(',') : q;
    });
}
```

**Comment by Arlen22** [comment]
Thank you, this works.
