### ISSUE TITLE
Duplicate identifier error when naming a class 'Node'

### ISSUE THREAD

**Issue by pb82** [Microsoft/TypeScript#16143]
**TypeScript Version:**  2.3.3
**Node.js Version:**  7.10.0

**Code**

```ts
class Node {}
```

Safe the file as `index.ts` and run `tsc index.ts`. No `tsconfig.json`.

**Expected behavior:**
Compiles without error.

**Actual behavior:**
Compiler returns the following error:
```
../../../usr/lib/node_modules/typescript/lib/lib.d.ts(12520,11): error TS2300: Duplicate identifier 'Node'.
../../../usr/lib/node_modules/typescript/lib/lib.d.ts(12572,13): error TS2300: Duplicate identifier 'Node'.
index.ts(1,7): error TS2300: Duplicate identifier 'Node'.
```

Renaming the class makes it pass.

**Comment by kitsonk** [comment]
Because [Node](https://developer.mozilla.org/en/docs/Web/API/Node) is already part of the global namespace and cannot be redeclared.  It needs to be part of a module, so it is not part of the global namespace.

**Comment by pb82** [comment]
That makes sense, thanks. Closing it now.

**Comment by brandonbloom** [comment]
What do you mean by "It needs to be part of a module"? I ran in to this exactly name collision, but I've got my class definition in a .ts file that is being loaded via import. My tsconfig.json has the module system set to "commonjs".

**Comment by kitsonk** [comment]
You would need to provide more details.  What does your module look like?  If it doesn't have any `import`s or `export`s then TypeScript won't treat it as a module.

[This will error](http://www.typescriptlang.org/play/#src=class%20Node%20%7B%0A%20%20%20%20%0A%7D) while [this](http://www.typescriptlang.org/play/#src=export%20class%20Node%20%7B%0A%0A%7D%0A) works:

```diff
-class Node {
+export class Node {

}
```

**Comment by brandonbloom** [comment]
>  If it doesn't have any imports or exports then TypeScript won't treat it as a module.

Whoa. I did not realize that.

This particular module will have no imports and did not _yet_ have any exports, since I had just started writing it. I wasn't planning to export the Node type, but was going to export some functions that used it.

Thank you!

**Comment by kitsonk** [comment]
As just discussed in #18232, if you need have something that you want to be considered a module without any `import`s or `export`s you can simply use:

```ts
export { }
```

Which will end up being stripped when the module is emitted.
