### ISSUE TITLE
Inconsistent type inference

### ISSUE THREAD

**Issue by ylepikhov** [Microsoft/TypeScript#16145]
**TypeScript Version:**  2.3.3
See also [playground](https://www.typescriptlang.org/play/index.html#src=interface%20I%20%7B%0D%0A%0D%0A%20%20%20%20p%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Aclass%20C%20implements%20I%20%7B%0D%0A%0D%0A%20%20%20%20p%3A%20string%3B%0D%0A%20%20%20%20pp%3A%20number%3B%0D%0A%7D%0D%0A%0D%0A%2F%2F%20no%20error%0D%0Aconst%20c%3A%20Partial%3CC%3E%20%3D%20%7B%20p%3A%20%22%22%20%7D%3B%0D%0A%0D%0Afunction%20ff%3CT%20extends%20I%3E(v%3A%20Partial%3CT%3E)%20%7B%0D%0A%0D%0A%20%20%20%20%2F%2F%20no%20error%0D%0A%20%20%20%20return%20v.p%3B%0D%0A%7D%0D%0A%0D%0Afunction%20f%3CT%20extends%20I%3E()%20%7B%0D%0A%0D%0A%20%20%20%20%2F%2F%20error%20TS2322%3A%20Type%20'%7B%20p%3A%20string%3B%20%7D'%20is%20not%20assignable%20to%20type%20'Partial%3CT%3E'%0D%0A%20%20%20%20%2F%2F%20why%3F%0D%0A%20%20%20%20const%20t%3A%20Partial%3CT%3E%20%3D%20%7B%20p%3A%20%22%22%20%7D%3B%0D%0A%7D)

**Code**

```ts
interface I {

    p: string;
}

class C implements I {

    p: string;
    pp: number;
}

// no error
const c: Partial<C> = { p: "" };

function ff<T extends I>(v: Partial<T>) {

    // no error
    return v.p;
}

function f<T extends I>() {

    // error TS2322: Type '{ p: string; }' is not assignable to type 'Partial<T>'
    // why?
    const t: Partial<T> = { p: "" };
}
```

**Expected behavior:**
No error

**Actual behavior:**
Error at line: `const t: Partial<T> = { p: "" };`

**Comment by mhegazy** [comment]
`Partial` is not really a special type. it is just a mapping operation that happens on a type. This is already tracked by https://github.com/Microsoft/TypeScript/issues/12731

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
