### ISSUE TITLE
Module resolution with paths not working

### ISSUE THREAD

**Issue by CedricMalfreytBL** [Microsoft/TypeScript#16147]
**TypeScript Version:**  2.3.3

**Code**

tsconfig.json :
```json
{
  "compileOnSave": true,
  "compilerOptions": {
    "baseUrl": ".",
    "sourceMap": true,
    "target": "es5",
    "module": "amd",
    "declaration": false,
    "noImplicitAny": false,
    "noResolve": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "mapRoot": "src/",
    "allowSyntheticDefaultImports": true,
    "paths": {
      "*": [ "./src/*"],
      "project/*": [ "./src/../../../../../../Project.Portail/DevArea/Sources/DR.Core.Portail/DR.Project.Web/src/project/*" ]
    }
  },
  "typeRoots": [
    "./typings/index.d.ts",
    "./custom_typings/**/*.d.ts",
    "./jspm_packages/**/*.d.ts"
  ],
  "exclude": [
    "node_modules",
    "jspm_packages"
  ],
  "atom": {
    "rewriteTsconfig": false
  }
}
```

An import using the path project/* :
```ts
import { MyService } from "project/services/users/questionnaireService";
```

**Expected behavior:**
The module should be resolved.

**Actual behavior:**
tsc.exe --project tsconfig.json --traceResolution shows the module is resolved but throws an error at the end of the compilation process. **Why ?**

tsc.exe --project tsconfig.json --traceResolution output :

```
======== Resolving module 'project/services/users/questionnaireService' from 'D:/Code/abcd/Project.Soins/DevArea/Sources/DR.Project.Soins/DR.Project.Soins.Web/src/project.soins/ui/papresident/papresident.ts'.
 ========
Explicitly specified module resolution kind: 'NodeJs'.
'baseUrl' option is set to 'D:/Code/abcd/Project.Soins/DevArea/Sources/DR.Project.Soins/DR.Project.Soins.Web', using this value to resolve non-relative module name 'project/services/users/questionnaireServi
ce'.
'paths' option is specified, looking for a pattern to match module name 'project/services/users/questionnaireService'.
Module name 'project/services/users/questionnaireService', matched pattern 'project/*'.
Trying substitution './src/../../../../../../Project.Portail/DevArea/Sources/DR.Core.Portail/DR.Project.Web/src/project/*', candidate module location: './src/../../../../../../Project.Portail/DevArea/Sources/
DR.Core.Portail/DR.Project.Web/src/project/services/users/questionnaireService'.
Loading module as file / folder, candidate module location 'D:/Code/abcd/Project.Portail/DevArea/Sources/DR.Core.Portail/DR.Project.Web/src/project/services/users/questionnaireService', target file type '
TypeScript'.
File 'D:/Code/abcd/Project.Portail/DevArea/Sources/DR.Core.Portail/DR.Project.Web/src/project/services/users/questionnaireService.ts' exist - use it as a name resolution result.
======== Module name 'project/services/users/questionnaireService' was successfully resolved to 'D:/Code/abcd/Project.Portail/DevArea/Sources/DR.Core.Portail/DR.Project.Web/src/project/services/users/ques
tionnaireService.ts'. ========
...<some other compilation info> ...
D:/Code/abcd/Project.Soins/DevArea/Sources/DR.Project.Soins/DR.Project.Soins.Web/src/project.soins/ui/papresident/papresident.ts(23,54): error TS2307: Cannot find module 'project/services/users/questionnaireService'.
```

**Comment by mhegazy** [comment]
can you share a self contained repro we can look at?

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Comment by douglasg14b** [comment]
@mhegazy Would be nice if all these issues were not being closed, it's beyond difficult to find any information related to this. It's just a giant mess of fragmented and closed issues with bits and pieces of information that paints a very incomplete picture.

**Comment by kitsonk** [comment]
@douglasg14b how does keeping issues open, where the OP does not provide sufficient information to identify the issue for extended periods of time.  Two weeks seems like a totally reasonable time period and issue can easily be re-opened if the required information is provided.

It would be more appropriate to direct your "wrath" at members of the community open thousands of issues without complete information, leaving everyone else scratching their heads.

**Comment by RyanCavanaugh** [comment]
I'm not sure how having the issue be open rather than closed is going to fix anything. If the OP isn't providing a working repro (which happens all the time), what are we supposed to do? Let the open issues accumulate into the tens of thousands?

**Comment by douglasg14b** [comment]
@RyanCavanaugh @kitsonk  You're right, I was off the hook on frustration trying to solve a similar issue, and running into github issue after github issue that describes it, but didn't have follow up.

**Comment by CedricMalfreytBL** [comment]
Hi, I'm no more working on the project in which the issue happened. As it was a professional project, I've no more access to the sources and so unable to provide a repro.
