### ISSUE TITLE
Goto definition for destructuring should go to the property definition

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#16151]
**TypeScript Version:**  nightly (2.4.0-dev.20170530)

**Code**

```ts
interface I { x: number; }

function f({ x }: I) {
    return x;
}
```

**Expected behavior:**

Goto-definition at `x` in `{ x }` should go to the property declaration.

**Actual behavior:**

It takes me to the beginning of the identifier that I'm already at.

**Comment by evansb** [comment]
It works correctly if we don't use shorthand property assignment

```
interface I {
  x: number
}

function f({ x: x }: I)  {
}
```

Might be caused by https://github.com/Microsoft/TypeScript/blob/master/src/services/goToDefinition.ts#L60

**Comment by andy-ms** [comment]
Already fixed.
