### ISSUE TITLE
Is it possible to update VS 2015 language service?

### ISSUE THREAD

**Issue by ctaggart** [Microsoft/TypeScript#1615]
It it possible to update the VS 2015 Preview language service somehow so that it works with `typescript.d.ts` built from `master`? Right now, it is show errors for everything with `const`, but more importantly  `CompilerOptions.option` causes cascading errors where I am unable to use the `const enum`s below it. Notice the errors for `ScriptTarget` and `ModuleKind`.

![image](https://cloud.githubusercontent.com/assets/80104/5655965/922f2da0-968a-11e4-88af-8fcfcc3f1f37.png)

My work-a-round right now is to comment out the `CompilerOptions` `[option: string]: string | number | boolean;` line. Is that a new construct? 

![image](https://cloud.githubusercontent.com/assets/80104/5655975/c7f438fe-968a-11e4-9f7a-4e612bb5190b.png)

**Comment by basarat** [comment]
Here's whats supposed to work : https://github.com/TypeStrong/tscs/blob/master/CONTRIBUTING.md#using-visual-studio 

Thanks to @DanielRosenwasser : https://github.com/Microsoft/TypeScript/issues/1110#issuecomment-62451204

**Comment by basarat** [comment]
@ctaggart you might want to clone : https://github.com/TypeStrong/tscs as I did *some* stuff to play around with the new compiler API with a nice workflow

**Comment by ctaggart** [comment]
@basarat will definitely check that out! Thanks for a link to the instructions. They worked, but now I've run into issue #1597 I believe:
![image](https://cloud.githubusercontent.com/assets/80104/5656277/ee16b1d4-968e-11e4-821f-87ae1784399e.png)

Here are the steps I did:
```
git pull
jake LKG
npm install -g
explorer built\local
```
 * copy typescriptServices.js to
C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TypeScript

**Comment by ctaggart** [comment]
Don't forget to copy the tsc.js too:
 * Copy tsc.js to C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.1
