### ISSUE TITLE
Add flag to allow bivariant callback parameter comparison

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#16150]
This follow up on https://github.com/Microsoft/TypeScript/pull/15104; we need a new flag to allow users affected by this change to suppress the errors.

**Comment by gcnew** [comment]
When is #15104 giving an unjustified error?

**Comment by mhegazy** [comment]
the error is correct. it just to simplify migration to new version for large code bases.

**Comment by rbuckton** [comment]
We are opting not to do this at this time. Our primary concern was how much friction this would cause users of TypeScript in Visual Studio and VS Code. In both cases there are options allowing users to stay on TypeScript 2.3 until they can address errors in their codebase exposed by this change.
