### ISSUE TITLE
MSBuild compiler options for TypeScript 2.3

### ISSUE THREAD

**Issue by nycdotnet** [Microsoft/TypeScript#16164]
**TypeScript Version:**  2.3.3

**Expected behavior:**
I expected the new TypeScript 2.3 switch "MSBuild" analogues to be documented here:
http://www.typescriptlang.org/docs/handbook/compiler-options-in-msbuild.html

**Actual behavior:**
Not documented.

I'm updating [csproj2ts](https://github.com/TypeStrong/csproj2ts/) for TypeScript 2.3, and I need to know the MSBuild analogues for the following switches, if any.  I will submit a PR for the docs.  :-)

  * `--checkJs`
  * `--downlevelIteration`
  * `--strict`  - will there be an MSBuild analog for this macro?

Thank you!

**Comment by mhegazy** [comment]
@minestarks can you take a look.

**Comment by minestarks** [comment]
@nycdotnet have you considered ```$(TypeScriptAdditionalFlags)```?

**Comment by nycdotnet** [comment]
Thanks @minestarks.  The library I'm working on parses csproj files to get the TS settings, so I just need to know what the official MSBuild properties for these settings will be called.  It's meant to facilitate cross platform compilation of TS from the cli.  If they are not/ will not be implemented for MSBuild that answers my question too.  Thanks!

**Comment by minestarks** [comment]
Oh, got it. Cool project. Sorry for the delay in answering - as you've already figured out these are not currently mapped. We don't necessarily map all compiler switches unless there's an immediate reason to, like exposing them through the properties UI. Check out the Microsoft.TypeScript.Targets file that ships with our SDK, these should contain new MSBuild properties as we add them. I'm closing this issue.

**Comment by nycdotnet** [comment]
Thanks - I wasn't aware of the SDK - I'll use that from now on. Thank you!

**Comment by minestarks** [comment]
@nycdotnet just as a heads up we added these for 2.4 to the MSBuild targets:

```TypeScriptCheckJs``` -> ```--checkJs```
```TypeScriptDownlevelIteration``` ->  ```--downlevelIteration```
```TypeScriptStrict` -> ```--strict```

**Comment by nycdotnet** [comment]
good to know ty
