### ISSUE TITLE
Compiler allows for using a value before it is imported

### ISSUE THREAD

**Issue by lambda-fairy** [microsoft/TypeScript#16166]
**TypeScript Version:**  2.3.4

**Code**

```ts
// foo.ts
console.log(BAR);
import {BAR} from './bar';
```

```ts
// bar.ts
export const BAR = 'bar';
```

```js
// tsconfig.json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "strict": true
  }
}
```

**Expected behavior:**

TypeScript should reject `foo.ts`, because it is referring to `BAR` before it is initialized.

**Actual behavior:**

`tsc` raises no errors, and generates the following `foo.js` file:

```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
console.log(bar_1.BAR);
var bar_1 = require("./bar");
```

This fails at runtime with a `TypeError`.

**Comment by lfairy** [comment]
Note that when I first encountered this bug, it was in code like this:

```ts
// ...
import BAR = innerNamespace.BAR;
// ...
import {innerNamespace} from './bar';
// ...
```

So it wasn't as obvious what was wrong.

**Comment by yortus** [comment]
ES6 `import`s are hoisted, so the code in `foo.ts` *is* valid and should run without errors. The problem here seems to be with the emitted code, which does not hoist the import. Not sure if changing the emit order would be problematic when emitting to other module systems like CommonJS.

**Comment by yortus** [comment]
FWIW I was curious what babel emits for `foo.ts`, and it correctly hoists the `import`, emitting the following JS code ([see repl here](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&targets=&browsers=&builtIns=false&debug=false&experimental=false&loose=false&spec=false&code=console.log(BAR)%3B%0D%0Aimport%20%7BBAR%7D%20from%20'.%2Fbar'%3B%0D%0A)):

```js
'use strict';

var _bar = require('./bar');

console.log(_bar.BAR);
```

**Comment by lfairy** [comment]
That's interesting, thanks for the info!

I guess changing the emit order would technically be a breaking change, since importing a module can have side effects. But I'm not sure how common this is in practice.

**Comment by rbuckton** [comment]
Ideally we would hoist the imports, but not change the emit order. This is what already happens for AMD and SystemJS.

**Comment by appsforartists** [comment]
I just found a similar surprise, and a place where TS should throw and doesn't:

```typescript
function useA() {
  // using `a` before it is declared surprisingly doesn't error in either TS or the 
  // DevTools console
  console.log(a);
}

useA(); // This does error at runtime and should error at compile time

const a = 1;
useA();
```

**Comment by scottmas** [comment]
It looks like this issue is scheduled to be closed soon with https://github.com/microsoft/TypeScript/pull/39764 which tweaks import hoisting, but this fix will NOT fix the issue described by @appsforartists, which is the same bug I've experienced in my code. 

Are there plans to fix this error?

**Comment by uhyo** [comment]
I proposed a fix two years ago, but today it got closed without getting any reviews.

I must say that apparently TypeScript Team is not interested in fixing this issue.

Please do not expect this issue to be fixed. 🥲

**Comment by RyanCavanaugh** [comment]
Unfortunately, surveying the landscape, there are definitely projects that have taken a hard dependency on the current behavior and would by broken by any fix to hoist the imports, e.g. https://github.com/microsoft/tsdoc/blob/b7bddc1ceb6b6759857c66ef3af6e5e95655fb8c/tsdoc/src/nodes/DocDeclarationReference.ts#L165 where the lines are reordered to prevent a circular dependency problem.

Since writing `import`s below the top of the file is extremely rare (seems like only book and transpiler authors do this 😅) we don't think this is worth potentially breaking people for the sake of a spec compliance that no one encounters in practice.

**Comment by appsforartists** [comment]
@RyanCavanaugh 
Is [this](https://github.com/microsoft/TypeScript/issues/16166#issuecomment-374791295) worth elevating to its own issue?

**Comment by RyanCavanaugh** [comment]
@appsforartists that behavior is intentional. Many programs "look" like they will TDZ under static analysis, but don't at runtime, so it's not practical to flag those as errors
