### ISSUE TITLE
Cann't use a decorator to change the method signature

### ISSUE THREAD

**Issue by foisonocean** [Microsoft/TypeScript#16162]
**TypeScript Version:**  2.3.2

**Code**

```ts
class A {
  static foo () {
    return 10;
  }
}
function decorator (OriginalClass: any) {
  const originalFoo = OriginalClass.foo;
  class NewClass extends OriginalClass {}
  NewClass.foo = function () {
    return 'hello' + originalFoo()
  }
}

@decorator
class B extends A {}

let str: string;
str = B.foo()

```

**Expected behavior:**
TypeScript should think `B.foo()` return a string.

**Actual behavior:**
TypeScript thinks `B.foo()` return a number.

**Comment by HerringtonDarkholme** [comment]
Hi, it seems https://github.com/Microsoft/TypeScript/issues/4881 covers this feature request.

Moving discussion to a common issue helps feature request :).

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
