### ISSUE TITLE
ts.getOptionNameMap no longer marked as `export`

### ISSUE THREAD

**Issue by chrish619** [Microsoft/TypeScript#16168]
**TypeScript Version:**  2.3.4

**Expected behavior:**
`ts.getOptionNameMap` [commandLineParser](https://github.com/Microsoft/TypeScript/blob/v2.3.3/src/compiler/commandLineParser.ts#L695) in version 2.3.3 was marked as exports

**Actual behavior:**
`ts.getOptionNameMap` [commandLineParser](https://github.com/Microsoft/TypeScript/blob/v2.3.4/src/compiler/commandLineParser.ts#L694) in version 2.3.4 was marked as private (non exports) breaking existing functionality

Is this intentional?

**Comment by gcnew** [comment]
It's an internal export. Internal exports are not part of the public API and you are not supposed to use them.

**Comment by chrish619** [comment]
I had guessed as much: And logged this mainly for awareness / linking.
Thanks.
