### ISSUE TITLE
Interface is assignable to generic string indexer but type literal isn't

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#16176]
**TypeScript Version:**  nightly (2.4.0-dev.20170531)

**Code**

```ts
interface I { x: string; y: string; }
declare const a: I;
declare const b: { x: string, y: string };

declare function hasProperty<T>(map: { [index: string]: T; }, key: string): boolean;

hasProperty(a, "x");
hasProperty(b, "y");

```

**Expected behavior:**

Consistent behavior between interfaces and type literals.

**Actual behavior:**

```
src/a.ts(7,13): error TS2345: Argument of type 'I' is not assignable to parameter of type '{ [index: string]: {}; }'.
  Index signature is missing in type 'I'.
```

**Comment by mhegazy** [comment]
we treat literal types differently than named ones. the assumption is that if this is an anonymous type, chances are no more properties added, while an interface this is not the case. so we give the earlier an index signature.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
