### ISSUE TITLE
[Question] When the Typescript 2.3 will be available in VS2017?

### ISSUE THREAD

**Issue by ifle** [Microsoft/TypeScript#16177]
[When the Typescript 2.3 will be available in VS2017?

**Comment by SaschaNaz** [comment]
Now that the VS2017.2 is released, the installer for VS2015 should also work for VS2017. The site does not mention about this, though.

**Comment by joeangry** [comment]
Am I supposed to do anything particular to make 2.3 work with VS17? I installed the VS15 package and restarted the IDE but that changed nothing.

**Comment by SaschaNaz** [comment]
Open Tools->Options->Text Editor->JavaScript/TypeScript->Intellisense and you should see "Use TypeScript version" which should be set as 2.3. This should be automatically set but it seems sometimes not.

**Comment by danko-d** [comment]
You should install Typescript SDK for VS2017 from https://www.microsoft.com/en-us/download/confirmation.aspx?id=55258

**Comment by ifle** [comment]
I've installed the Typescript SDK, changed the Tools->Options->Text Editor->JavaScript/TypeScript>Intellisense to 2.3 version, but when I check the version of typescript in the About screen of VS, I still have 2.2.2 version
![image](https://cloud.githubusercontent.com/assets/1140474/26741910/0cde23fa-47e4-11e7-8d9c-ab3f314651a6.png)

![image](https://cloud.githubusercontent.com/assets/1140474/26741837/b4990610-47e3-11e7-9ce5-ea29016f9e16.png)

**Comment by SaschaNaz** [comment]
Try something specific with TS 2.3, for example:

```
class Component<P, S = object> { }
```

If this does not show error then you have TS 2.3.

**Comment by ifle** [comment]
this does not show error

**Comment by SaschaNaz** [comment]
Then you have TS2.3, regardless of what About page says 🎉

**Comment by ifle** [comment]
Thanks to all.

I don't know how that critical, but VS 2017 ignore the TypeScriptToolsVersion setting of csproj with ToolsVersion="14.0".

**Comment by minestarks** [comment]
@ifle Visual Studio 2017 15.3 will respect your ```TypeScriptToolsVersion``` setting in Intellisense as well.

**Comment by minestarks** [comment]
Forgot to mention, 15.3 also includes TypeScript 2.3 by default.
