### ISSUE TITLE
Problem with returning a mongoose promise from a then() when using Bluebird

### ISSUE THREAD

**Issue by cmgreivel** [microsoft/TypeScript#16180]
**TypeScript Version:**  2.3.3
**Code**

```
        return model.findById(thingId)
        .then((thing) => {
            return model.findByIdAndUpdate(findDoc, updateInfo, { 'new': true }).exec();
        })
        .then((savedThing) => {
            if (savedThing.parameter) {}

```
model is a mongoose model.

Following the documentation at https://github.com/DefinitelyTyped/DefinitelyTyped/tree/4869992bc079b88280b9ff91213528904109e8ae/mongoose#promises, we have a file in our project to let tsc know that mongoose uses Bluebird promises:
```
import Bluebird = require('bluebird');
declare module 'mongoose' {
    type Promise<T> = Bluebird<T>;
}
```
**Expected behavior:**
savedThing should be of type ThingModel.  tsc v2.2.2 does treat savedThing as a ThingModel.

**Actual behavior:**
savedThing is of type Bluebird<ThingModel>, resulting in 
```
error TS2339: Property 'parameter' does not exist on type 'Bluebird<ThingModel>'.
```
I was wondering if this might be related to https://github.com/Microsoft/TypeScript/issues/16055

Or maybe there's something that I should be doing differently.

**Comment by RyanCavanaugh** [comment]
This doesn't seem to be a TypeScript bug
