### ISSUE TITLE
Add syntax to function parameter types to indicate how they are called

### ISSUE THREAD

**Issue by Spensaur-K** [Microsoft/TypeScript#16186]
I wrote some code earlier and was surprised that it crashed in runtime after compiling successfully since I'm used to typescript catching most of my errors.

Suppose I'm writing a class, ReplaceablePromise, that extends Promise and exposes a method that allows the promise to be replaced with another promise transparently so that anything that was waiting for the initial promise will now wait for the new promise. To achieve this, the resolve / reject functions passed by the Promise constructor need to be stored in instance variables and called when the promise eventually resolves.

```ts
class ReplaceablePromise<T> extends Promise<T> {
    private resolve: (v?: T | PromiseLike<T>) => void;
    private reject: (v?: T | PromiseLike<T>) => void;
    constructor(provide: (resolve: (v?: T | PromiseLike<T>) => void, reject: (v?: T | PromiseLike<T>) => void ) => void) {
        super((resolve, reject) => {
           this.resolve = resolve;
           this.reject = reject
        });
    }

}
```

This code has an error that is not caught by typescript. The Promise constructor calls the function passed to it synchronously before super returns so `this` hasn't been created yet;

It can be fixed by assigning resolve / reject into local variables first:

```ts
class ReplaceablePromise<T> extends Promise<T> {
    private resolve: (v?: T | PromiseLike<T>) => void;
    private reject: (v?: T | PromiseLike<T>) => void;
    constructor(provide: (resolve: (v?: T | PromiseLike<T>) => void, reject: (v?: T | PromiseLike<T>) => void ) => void) {
        let res, rej;
        super((resolve, reject) => {
            // `this` does not exist yet inside function
            // because super calls function synchronously
            res = resolve;
            rej = reject;
        });
        this.resolve = res;
        this.reject = rej;
    }

}
```

However, typescript will not catch the previous error. I suspect the reason is because function types lack information about how they are called.

I want to suggest adding a type to function's passed as parameters to dictate whether a function type will be called synchronously, asynchronously, never be called, or can be called both synchronously and asynchronously when passed as a function parameter.

Typescript could statically determine how a function parameter is called but external functions need a way to define how they're called

For example,

```ts
function foo(a: () => void) {
    a();
}

function bar(a: () => void) {
    setTimeout(a, 0);
}

function far(a: () => void) {
    Math.random() > 0.5 ? setTimeout(a, 0) : a();
}

function boo(a: () => void) {
    alert("Hello world");
}

```

Since foo calls a immediately, foo's type could look something like this
`function foo(a: (sync) => void) {`
Where bar would 
`function foo(a: (async) => void) {`
because setTimeout takes a function parameter with the type: `(async) => void`
Since a is called both synchronously and asynchronously in far, its type would be
`function far(a: (async | sync) => void) {`
In boo, a's call type is never, since a is never called in the body of boo
`function boo(a: (never) => void) {`

Adding call types could help catch errors caused by situations where the user of a function expects the function they pass as an argument to be called asynchronously but it is actually called synchronously:

```ts
function makeManyRequests(urls: string[], done: (v: string[])) {
    responses = [];
    for (let i = 0; i < urls.length; i++) {
        ajax(urls[i], res => {
             responses[i] = res;
             if (--i == 0) {
                   done(responses);
             }
        });
    }
}
```
Here we have a function that takes an array of urls, fetches the urls from a server using a likely ajax function, and calls a callback with an array of responses.

The  makeManyRequests function depends on the ajax library calling the provided callback asynchronously. If ajax were to retrieve a response synchronously (let's say from a cache) and call the passed function parameter the outer i variable may be decremented before it reaches url.length in the for loop, resulting in the done callback being called multiple times.

**Comment by RyanCavanaugh** [comment]
See #11498

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
