### ISSUE TITLE
Node 8 util.promisify

### ISSUE THREAD

**Issue by lautarodragan** [Microsoft/TypeScript#16185]
**TypeScript Version:**  2.3.4

**Code**

```ts
import * as fs from 'fs'
import * as util from 'util'

const readdir = util.promisify(fs.readdir)

```

**Expected behavior:**
No error

**Actual behavior:**
Property `promisify` does not exist on type 'typeof "util"'.

I did [a quick search for 'promisify'](https://github.com/Microsoft/TypeScript/search?utf8=%E2%9C%93&q=promisify&type=) in typescript's repository and only found references in test files about bluebird.

**Comment by andy-ms** [comment]
Duplicate of DefinitelyTyped/DefinitelyTyped#16860.
node.js types are not part of TypeScript itself, they are in the `@types/node` package.

**Comment by lautarodragan** [comment]
Oops, thanks!
