### ISSUE TITLE
TS2363: The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.

### ISSUE THREAD

**Issue by chanakaDe** [Microsoft/TypeScript#16189]
Guys, 

> TS2363: The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.

This is the error I'm getting and this is the function I used. Can anyone please give me a solution for this ?

user_checking(registerdata, tested_users):boolean {
    return registerdata.userid && typeof tested_users[registerdata.userid] == 'undefined';
}

This is really annoying . It's really helpful if someone can help me on this please :)

**Comment by ikatyang** [comment]
Can you provide a self-contained code with TS version and tsconfig?

Otherwise we don't know how to reproduce.

Additionally, I do not see any arithmetic operator (`+ - / * %`) there, is that the code throwed the error message?

**Comment by chanakaDe** [comment]
@ikatyang  Hi, This is the full code of the : https://gitlab.com/snippets/1663479
I'm sure error is coming from this code and also within this function i have added above. When I commented the code block, no error.

**Comment by chanakaDe** [comment]
And also this is tsconfig.json

`{
  "compileOnSave": false,
  "compilerOptions": {
    "sourceMap": true,
    "target": "es5",
    "module": "amd",
    "declaration": false,
    "noImplicitAny": false,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "lib": ["es2015", "dom"]
  },
  "exclude": [
    "node_modules"
  ],
  "filesGlob": [
    "./src/**/*.ts",
    "./test/**/*.ts",
    "./typings/index.d.ts",
    "./custom_typings/**/*.d.ts"
  ],
  "atom": {
    "rewriteTsconfig": false
  }
}
`

**Comment by ikatyang** [comment]
I have tested it with TS v2.3.4, it works fine without any error message. The `tsconfig.json` and `register_full.ts` are fully copied from your comments, did I misunderstand something?

![image](https://cloud.githubusercontent.com/assets/8341033/26682203/3358b2d4-4712-11e7-85ff-9053f90703e4.png)

**Comment by chanakaDe** [comment]
@ikatyang  Oh, that's so strange.

**Comment by aluanhaddad** [comment]
@chanakaDe use `"typescript": "~2.3.4"`

**Comment by ikatyang** [comment]
@chanakaDe  You can list up your TS version using `npm ls --depth=0`, since `>=1.9.0-dev || ^2.0.0` is also comaptable with `2.3.4`, I have no idea what your version is.

Also, you can try the newest version of TS.

And I realize that you're using the `filesGlob`(from `atom-typescript`) field instead of `files` (from TS), I have no idea if it will affect something?

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
