### ISSUE TITLE
No reassign of parameters

### ISSUE THREAD

**Issue by blake-newman** [Microsoft/TypeScript#16191]
Similar to the ESLint rule http://eslint.org/docs/rules/no-param-reassign

Using `strictNullChecks` causes issues with asynchronous events. Multiple control flow arguments need to be used. 
```
function createLink(input: HTMLElement, options: LinkOptions) {
   // ...
  if (options.onClick) {
    input.addEventListener(() => {
      options.onClick && options.onClick()
    })
  }
} 
```

The onClick method can be reassigned before the  onClick function line is executed, thus unable to infer that the property is defined. Enabling the ability to refuse mutations of parameters will improve the control flow.

Adding a flag `noParamReassign` could be the most elegant solution, as this enforces code standards and improves control flow.

**Comment by mhegazy** [comment]
that would not be sufficient. `options` can be aliased, so you need `onClick` to be declared as `readonly` as well.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
