### ISSUE TITLE
Class property inheritance and constructor usage

### ISSUE THREAD

**Issue by albohlabs** [Microsoft/TypeScript#16190]
**TypeScript Version:**  2.3

**Code**

```ts
class A {
    prop = 'A';

    constructor() {
	this.outputProp();
    }

    outputProp() {
	console.log(this.prop);
    }
}

class B extends A {
   prop = 'B';

    constructor() {
        super();
	this.outputProp();
    }
}

new B();

```

**Expected behavior:**

The output of `console.log` should be the value of `prop` from `class B`.

I would expect that a method call from the `constructor` is not evaluated before the class properties are assigned.

**Actual behavior:**

`console.log` output is `A`.

**Comment by ikatyang** [comment]
Possible duplicate of https://github.com/Microsoft/TypeScript/issues/7724

See https://github.com/Microsoft/TypeScript/issues/7724#issuecomment-203070116

**Comment by albohlabs** [comment]
@ikatyang Yes, you are right.

Will close this.
