### ISSUE TITLE
Wrong CodeAction for function call with incorrect argument count

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#16205]
From https://github.com/Microsoft/vscode/issues/27392#issuecomment-305635430

**TypeScript Version:**  2.3.4

**Code**
`package.json`:

```
{
  "dependencies": {,
    "discord.js": "^11.1.0"
   }
}
```

`main.ts`

```ts
import { waitForMessages } from "./interactive";

waitForMessages({} as Channel);
```

`interactive.js`:

```ts
import { TextChannel, DMChannel } from "discord.js";

export function waitForMessages(channel:TextChannel|DMChannel, rules:string) { }
```

Try getting the code for at `Channel` in `waitForMessages({} as Channel, );`

**Expected behavior:**
A code fix for importing `Channel` from `discord.js` is returned

**Actual behavior:**
A code fix for reimporting `waitForMessages` is returned:

<img width="841" alt="screen shot 2017-06-01 at 3 39 44 pm" src="https://cloud.githubusercontent.com/assets/12821956/26703872/a820bff8-46e0-11e7-8418-b8a37a59d49d.png">

Updating the code to have the correct number of arguments (even if they are incorrect types) fixes the issue:

<img width="589" alt="screen shot 2017-06-01 at 3 39 35 pm" src="https://cloud.githubusercontent.com/assets/12821956/26703890/ba50a59e-46e0-11e7-85ca-ce3933dd366b.png">

**Comment by mjbvz** [comment]
Here's a trace of the server communications:


```
Trace  - 3:43:22 PM] Response received: occurrences (747). Request took 1 ms. Success: false . Message: No content available.
[Trace  - 3:43:23 PM] Sending request: getCodeFixes (748). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/Users/matb/projects/test/poor_snowball/src/main.ts",
    "startLine": 3,
    "endLine": 3,
    "startOffset": 1,
    "endOffset": 33,
    "errorCodes": [
        2346,
        2304
    ]
}
[Trace  - 3:43:23 PM] Response received: getCodeFixes (748). Request took 2 ms. Success: true 
Result: [
    {
        "description": "Add waitForMessages to existing import declaration from ./interactive.",
        "changes": [
            {
                "fileName": "/Users/matb/projects/test/poor_snowball/src/main.ts",
                "textChanges": [
                    {
                        "start": {
                            "line": 1,
                            "offset": 25
                        },
                        "end": {
                            "line": 1,
                            "offset": 25
                        },
                        "newText": ", waitForMessages"
                    }
                ]
            }
        ]
    }
]

**Comment by mhegazy** [comment]
The span provided to the server in `getCodeFixes` is for the first error not the second. the code fix code assumes a correct span from the caller. can you call getCodeFixes twice if the spans are not identical?

**Comment by mhegazy** [comment]
ping @mjbvz

**Comment by mjbvz** [comment]
Yes, we can make a request for each span but I'll have to see if this introduces any odd behavior (such as multiple `// @ts-ignore` fix suggestions). Reopening Microsoft/vscode#27392

**Comment by mjbvz** [comment]
After reviewing this again, I think TS should be less restrictive here. We request the quick fixes for a set of error codes and a range, so my expectation is that the TS Server would return all available fixes within that range for those error codes. Having to make a  request per error range does not seem correct and makes de-duping fixes more difficult

**Comment by mhegazy** [comment]
The server does not know what errors are there. doing so involves querying for errors again on every `GetCodeFixes` call, which is expensive, and we would rather avoid that. that is why the editor asks for errorCodes and not for a location for example.
