### ISSUE TITLE
IntelliSense for `self.prop = ...` class member definitions in JavaScript

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#16200]
From https://github.com/Microsoft/vscode/issues/27825

**TypeScript Version:**  2.3.4

**Code**

```ts
var MyClass = function(){
  var self = this;
  self.foo= "";
  this.bar = "";
}
```

Currently our IntelliSense only suggests `bar` on instances of `MyClass` and not `foo`

I believe this may be a special case of https://github.com/Microsoft/TypeScript/issues/10868

**Comment by mhegazy** [comment]
The compiler has no way to track aliasing `this` for write purposes at the time being.
