### ISSUE TITLE
reference to exported entity

### ISSUE THREAD

**Issue by alexeyk777** [Microsoft/TypeScript#1620]
Hello!
I hard work on project with phantom.js and node.js haves some shared code.
Phantomjs code file uses "reference" comments to join modules and compiled in single js file (using -out parameter). 
Node.js code uses 'import' keyword (commonJs system).
The problem is while I use "reference" compiller cant found classes/functions market with 'export'.
For example:
```ts
// one.ts
class A {
   function Foo(){ }
}
export B {
  function Foo(){ }
}
```
```ts
// two.ts
/// <reference path="one.ts" />
class C extend A {
}
class D extend B {
}
```
if anythin in one.ts contains export, compiler ignore 'reference' comment and throw error about  A or B not found.

**Comment by RyanCavanaugh** [comment]
Please see the page https://typescript.codeplex.com/wikipage?title=Modules%20in%20TypeScript for information on internal vs external modules, in particular the section "/// <reference> to an external module"

We're working on better documentation for this as it seems to be a common question.

**Comment by alexeyk777** [comment]
Sorry! The problem is in PhantomJS (I have found issue in phantomjs code).
Typescript works great!
