### ISSUE TITLE
Compiler hangs with v2.3.1

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#16212]
This bug is fixed now. It is nice if some tests exist.

cc @ahejlsberg 

**TypeScript Version:**  2.3.1

**Code**

The added test code in https://github.com/falsandtru/spica/commit/b775633e5d5949f277e6a6436e08e99202e499bc

**Comment by mhegazy** [comment]
looks like subsumed by https://github.com/Microsoft/TypeScript/issues/16511
