### ISSUE TITLE
Feature Request: updateProgram or program.getHost

### ISSUE THREAD

**Issue by ajafff** [Microsoft/TypeScript#16217]
TypeScript is missing an API to update a `Program` (something like `updateSourceFile`).
Currently I'm trying to achieve it by doing this:
```ts
const options = program.getCompilerOptions();
program = ts.createProgram(program.getRootFileNames(), options, ts.createCompilerHost(options, true), program);
```
Unfortunately I have no control over the creation of `program`. Hence I cannot be sure that the `Host` is correct.

There should either be an `updateProgram(oldProgram: Program): Program` or a method to retrieve the `Host` used to create the `Program`: `Program#getHost(): Host`.

Use case:
`tslint` allows linting the whole `Program`. It can also automatically fix failures. After fixing the `Program` needs to be updated. Unfortunately `tslint` does not necessarily know which host was used to create the program.

**Comment by mhegazy** [comment]
i am not sure i understand the reuest about the host. can you elaborate.

**Comment by ajafff** [comment]
The actual request is to provide a function `updateProgram(oldProgram: Program): Program` that reuses the same rootFiles, compilerOptions and host internally to create a new updated Program.

If that's implemented, I'm fine.

If the above is not implemented, There's no way I can create a copy of a Program without knowing the `host` that was used to create it.
For everything else there are getter methods: `getRootFileNames()`, `getCompilerOptions()`. To create a copy I would need a `program.getHost()` method.

**Comment by mhegazy** [comment]
sorry for the delay, but the creator of the program is the one that created the host. seems like you already have that.. we can add the method, but seems unnecessary.
