### ISSUE TITLE
No error when interface declares a function and property with same name and return type

### ISSUE THREAD

**Issue by mattmccutchen** [Microsoft/TypeScript#16214]
**TypeScript Version:**  2.3.4 (same in 2.4.0-dev.20170601)

**Code**
```ts
interface Oops {
  foo(x: string): number;
  foo: number;
}
```

**Expected behavior:**
`error TS2300: Duplicate identifier 'foo'.`

**Actual behavior:**
No error.

I bisected using the NPM nightly builds (I ran into build problems trying to bisect from source), and this broke between 1.9.0-dev.20160524-1.0 and 1.9.0-dev.20160525-1.0.  I suspect #8696.

**Comment by bashdx** [comment]
I would like to check on this one as a first shot. Could anybody please point me in the right direction? Thank you

**Comment by mattmccutchen** [comment]
Duplicate of #20826.
