### ISSUE TITLE
Cannot extend from type which constructs intersection of type parameter with a default

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#16211]
```ts
interface VueCtor {
    new <D = object>(d: D): Vue & D;
}

interface Vue {
}

declare var Vue: VueCtor;


class A extends Vue {
    //          ~~~
    // Error: Base constructor return type 'Vue & D' is not a class or interface type.
}
```

I thought this might have to do with the constraint, but adding an explicit `D extends object = object` doesn't work either.

Is it possible that `D` isn't correctly getting instantiated with its default type argument when extending from `Vue`?

**Comment by DanielRosenwasser** [comment]
For the record, `class A extends Vue<object>` works.

**Comment by sandersn** [comment]
Looks like `D` doesn't get substituted and then doesn't get instantiated.

**Comment by DanielRosenwasser** [comment]
Yup, @mhegazy and I are talking about why this is difficult to solve in a general context offline. 

Hilariously this works:

```ts
  interface VueCtor {
    new <D = object>(d: D): Vue & D;
}

interface Vue {
}

declare var Vue: VueCtor;


class A extends Vue<> {
    //          ~~~
    // Error: Base constructor return type 'Vue & D' is not a class or interface type.
}
```

**Comment by rbuckton** [comment]
Regarding https://github.com/Microsoft/TypeScript/issues/16211#issuecomment-305933544, apparently we do not have a grammar check for `ExpressionWithTypeArguments` to enforce that a type argument list is non-empty.
