### ISSUE TITLE
Incorrect path is used when a module installed via npm use require to load a modules contained in its node_module directory

### ISSUE THREAD

**Issue by chabb** [Microsoft/TypeScript#16224]
Importing a module that import other module using require fails
**TypeScript Version:**  2.2.1 / nightly (2.2.0-dev.201xxxxx)
**Code**
``` npm i d3```
```npm install --save @types/d3```

d3 is a library broken in submodules, it just loads other modules :

```var d3Queue = require('d3-queue');
var d3Random = require('d3-random');
var d3Request = require('d3-request');
var d3Scale = require('d3-scale');
var d3Selection = require('d3-selection');
var d3Shape = require('d3-shape');
var d3Time = require('d3-time');
var d3TimeFormat = require('d3-time-format');
var d3Timer = require('d3-timer');
var d3Transition = require('d3-transition');
var d3Voronoi = require('d3-voronoi');
var d3Zoom = require('d3-zoom');
```

The issue comes from the fact that when i launch my application, my script will look at the top node_modules folders for loading all those d3 submodules, but it should look in the node_modules of the d3 library.

**Comment by j-oliveras** [comment]
Just tested and works.

Did you use npm 2.x? If is the case try upgrading to 3.x or newer and delete node_modules and reinstall it.

**Comment by chabb** [comment]
Thank You @j-oliveras  ! That fixed it
