### ISSUE TITLE
Error in breaking changes docs (wiki)

### ISSUE THREAD

**Issue by trusktr** [Microsoft/TypeScript#16236]
Right [here](https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#promises), is is

```ts
let p: Promise<number> = new Promise((c, e) => { c('foo') });
//                                                 ~~~~~
//  Argument of type 'foo' is not assignable to 'number'
```

but it should be

```ts
let p: Promise<number> = new Promise<number>((c, e) => { c('foo') });
//                                                         ~~~~~
//  Argument of type 'foo' is not assignable to 'number'
```

. `<number>` is missing, right?

**Comment by DanielRosenwasser** [comment]
Yup, there's https://github.com/Microsoft/TypeScript-wiki for future reference.

**Comment by DanielRosenwasser** [comment]
Actually the code might be correct - I think we have appropriate inference for return types coming up in 2.4, but for the sake of it I've changed the example.

**Comment by mhegazy** [comment]
fixed by https://github.com/Microsoft/TypeScript-wiki/commit/3958533a6ec260c8a601ebffa8b384fdfafa6f7f
