### ISSUE TITLE
Suggestion: Add new --emitHelpersFile compile flag

### ISSUE THREAD

**Issue by ifle** [Microsoft/TypeScript#16237]
The new --emitHelpersFile compile flag will generate tslib file according to TS version, that will allows do not forget update tslib file.

**Comment by mhegazy** [comment]
The compiler should give you an error if the tslib version is not compatible with the compiler. otherwise the version should be matching. 
can you elaborate on the problems you are running into? and why they are not just versioning problem on tslib side.

**Comment by ifle** [comment]
I did not now that. How parser determines the correct version?

**Comment by mhegazy** [comment]
it checks the .d.ts in tslib for the functions it needs. if the functions do not exist, or their signature changed, it will complain.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
