### ISSUE TITLE
Property 'languages' does not exist on type 'Navigator'.

### ISSUE THREAD

**Issue by coreh** [Microsoft/TypeScript#16246]
**TypeScript Version:** 2.3.2

**Code**

```ts
navigator.languages
```

**Expected behavior:**
It should be defined and be of `string[]` type.

**Actual behavior:**
compiler error:
```
Property 'languages' does not exist on type 'Navigator'.
```

I've opened a PR here to fix this: https://github.com/Microsoft/TSJS-lib-generator/pull/263

**Comment by coreh** [comment]
The PR was merged on [Microsoft/TSJS-lib-generator](https://github.com/Microsoft/TSJS-lib-generator), so I'm closing this.

**Comment by mhegazy** [comment]
Fixed by https://github.com/Microsoft/TypeScript/commit/c8d33bc38ec61e923d6ff62c2e7b004bc56c6e5b

**Comment by titusfx** [comment]
Im using the Typescript 2.4.2 and I have the same problem.

**Comment by aditya1109** [comment]
same issue **I am using the Typescript 2.4.2 ( And Angular 4)**
