### ISSUE TITLE
No typecheck errors on optional object method param

### ISSUE THREAD

**Issue by giuseppelt** [Microsoft/TypeScript#16247]
**TypeScript Version:**  2.3.4

**Code**
```ts
type MethodOptions = {
    opt1?: string
    opt2?: number
}
class Test {
    method(options?: MethodOptions) {
    }
}

var test = new Test();
test.method("ciao");  //there should be an error here
test.method(1); // idem
test.method([]); // idem
```
directly on [playground](http://www.typescriptlang.org/play/#src=type%20MethodOptions%20%3D%20%7B%0D%0A%20%20%20%20opt1%3F%3A%20string%0D%0A%20%20%20%20opt2%3F%3A%20number%0D%0A%7D%0D%0Aclass%20Test%20%7B%0D%0A%20%20%20%20method(options%3F%3A%20MethodOptions)%20%7B%0D%0A%20%20%20%20%20%20%20%20%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Avar%20test%20%3D%20new%20Test()%3B%0D%0Atest.method(%22ciao%22)%3B%0D%0Atest.method(1)%3B%0D%0Atest.method(%5B%5D)%3B)

**Expected behavior:**
Type checking errors

**Actual behavior:**
No errors

**Comment by ikatyang** [comment]
In my opinion, `MethodOptions` is considered to be one of these types:

- `{}`
- `{opt1: string}`
- `{opt2: number}`
- `{opt1: string, opt2: number}`

So `"ciao" | 1 | []` is a valid `MethodOptions`, since they match the type of `{}`.

**Comment by jwbay** [comment]
Duplicate of #7485, fixed by #16047
