### ISSUE TITLE
Spelling suggestion is too eager and ignores exact match

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#16245]
```ts
enum U8 {
    BIT_0 = 1 << 0,
    BIT_1 = 1 << 1,
    BIT_2 = 1 << 2
}

U8.bit_2
// ~~~~~
```

Expected: "Did you mean 'BIT_2'?"
Actual: "Did you mean 'BIT_0'?"

**Comment by sandersn** [comment]
that's weird, because `'bit_2'.toLowerCase() === "BIT_2".toLowerCase()` so it should never suggest anything else.

**Comment by sandersn** [comment]
Turns out the code loops through each suggestion in order and takes the first one that is close enough. They're *all* close enough, even though `bit_2` is closer.
