### ISSUE TITLE
Modules documentation needs deployment instructions

### ISSUE THREAD

**Issue by KokoDoko** [Microsoft/TypeScript#16249]
**Using Modules in Typescript**

The [Typescript documentation](https://www.typescriptlang.org/docs/handbook/modules.html) explains how to set up and use Modules while developing in the IDE. You won't get code completion errors in the IDE if you follow the documentation. Your modules will get bundled into one .js file that uses one of the available methods (systemjs, amd, etc).

**Expected behavior:**

I expect the modules to work when I follow the documentation instructions.

**Actual behavior:**

If you deploy your project, you WILL get errors because the browser doesn't recognise the module system. Nowhere in the Typescript docs does it even suggest what you need to do to get modules actually working in the browser. I suppose this is because there are so many systems and they're not really part of Typescript.

**problem**
If you follow the instructions of (in my case) SystemJS on their own github page, you will find a LOT of different configurations, but none of them works right out of the box with the way TSC bundles modules. Some instructions are even downright wrong, for example the suggestion to work with system-production.js for Typescript bundles.

**problem**
Once you DO get your modules loaded using (for example) SystemJS, there is no explanation in the Typescript docs on how to kickstart the app / define the entry point for your app.

**Suggestion**

- Include a working setup example for loading typescript-compiled modules in the browser.
- Explain how to kickstart an app that uses modules.

**Comment by mhegazy** [comment]
We have samples for modules in:
- amd: https://github.com/Microsoft/TypeScriptSamples/tree/master/amd
- umd: https://github.com/Microsoft/TypeScriptSamples/tree/master/umd
- sytemjs: https://github.com/Microsoft/TypeScriptSamples/tree/master/systemjs
- node: https://github.com/Microsoft/TypeScript-Node-Starter#typescript-node-starter
- webpack: https://github.com/Microsoft/TypeScript-React-Starter#typescript-react-starter
- browserify: https://github.com/Microsoft/TypeScriptSamples/tree/master/browserify

let us know if you have something else in mind.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
