### ISSUE TITLE
Duplicate switch cases in TypeScript sources

### ISSUE THREAD

**Issue by kpreisser** [Microsoft/TypeScript#16243]
**TypeScript Version:**  master

Hi,
when minifying `typescriptServices.js` built from current master branch with Google Closure Compiler, I get some warnings about duplicate cases in `switch` statements:

1) `compiler/utilities.ts`, [line 1137](https://github.com/Microsoft/TypeScript/blob/5ea8466103747fe38e846999577bbb0f2ce1b553/src/compiler/utilities.ts#L1137) and [1186](https://github.com/Microsoft/TypeScript/blob/5ea8466103747fe38e846999577bbb0f2ce1b553/src/compiler/utilities.ts#L1186):
```ts
    export function isPartOfExpression(node: Node): boolean {
        switch (node.kind) {
            case SyntaxKind.ThisKeyword:   // <---
            // (...)
            case SyntaxKind.StringLiteral:
            case SyntaxKind.ThisKeyword:   // <---

```

2) `compiler/utilities.ts`, [line 1203](https://github.com/Microsoft/TypeScript/blob/5ea8466103747fe38e846999577bbb0f2ce1b553/src/compiler/utilities.ts#L1203) and [1206](https://github.com/Microsoft/TypeScript/blob/5ea8466103747fe38e846999577bbb0f2ce1b553/src/compiler/utilities.ts#L1206):
```ts
                    case SyntaxKind.SwitchStatement:   // <---
                    case SyntaxKind.CaseClause:
                    case SyntaxKind.ThrowStatement:
                    case SyntaxKind.SwitchStatement:   // <---
```

3) `compiler/visitor.ts`, [line 1108](https://github.com/Microsoft/TypeScript/blob/5ea8466103747fe38e846999577bbb0f2ce1b553/src/compiler/visitor.ts#L1108) and [1151](https://github.com/Microsoft/TypeScript/blob/5ea8466103747fe38e846999577bbb0f2ce1b553/src/compiler/visitor.ts#L1151):
```ts
            case SyntaxKind.NonNullExpression:   // <---
                result = reduceNode((<ParenthesizedExpression | DeleteExpression | TypeOfExpression | VoidExpression | AwaitExpression | YieldExpression | SpreadElement | NonNullExpression>node).expression, cbNode, result);
                break;
            // (...)
            case SyntaxKind.NonNullExpression:   // <---
                result = reduceNode((<NonNullExpression>node).expression, cbNode, result);
                break;
```

4) `compiler/program.ts`, [line 1137](https://github.com/Microsoft/TypeScript/blob/5ea8466103747fe38e846999577bbb0f2ce1b553/src/compiler/program.ts#L1137) and [1139](https://github.com/Microsoft/TypeScript/blob/5ea8466103747fe38e846999577bbb0f2ce1b553/src/compiler/program.ts#L1139), and also [line 1202](https://github.com/Microsoft/TypeScript/blob/5ea8466103747fe38e846999577bbb0f2ce1b553/src/compiler/program.ts#L1202) and [1204](https://github.com/Microsoft/TypeScript/blob/5ea8466103747fe38e846999577bbb0f2ce1b553/src/compiler/program.ts#L1204):
```ts
                        case SyntaxKind.FunctionDeclaration:   // <---
                        case SyntaxKind.ArrowFunction:
                        case SyntaxKind.FunctionDeclaration:   // <---
```

5) `services/services.ts`, [line 660](https://github.com/Microsoft/TypeScript/blob/5ea8466103747fe38e846999577bbb0f2ce1b553/src/services/services.ts#L660) and [663](https://github.com/Microsoft/TypeScript/blob/5ea8466103747fe38e846999577bbb0f2ce1b553/src/services/services.ts#L663):
```ts
                    case SyntaxKind.ImportEqualsDeclaration:   // <---
                    case SyntaxKind.ExportSpecifier:
                    case SyntaxKind.ImportSpecifier:
                    case SyntaxKind.ImportEqualsDeclaration:   // <---
```

Are there any reasons for these duplicate cases, or can/should they be removed?
Thanks!

**Comment by DanielRosenwasser** [comment]
Probably not, these sound like bugs! Thanks for the report!
