### ISSUE TITLE
Typescript compiler should use "let" or "const" instead of "var" when compilling to ES6

### ISSUE THREAD

**Issue by niokasgami** [Microsoft/TypeScript#16256]
**TypeScript Version:**  latest

**Code**

```ts
namespace MyNamespace {

    import $dataSystem = Manager.$dataSystem;
    export class MyClass {

        constructor() {
            // some code here...
        }
        
        public static MyMethod(): string {
            return $dataSystem.locale;
        }
    }
}

// Output to : 
var MyNamespace;
(function (MyNamespace) {
    var $dataSystem = Manager.$dataSystem;
    class MyClass {
        constructor() {
            // some code here...
        }
        static MyMethod() {
            return $dataSystem.locale;
        }
    }
    MyNamespace.MyClass = MyClass;
})(MyNamespace || (MyNamespace = {}));

```

**Expected behavior:**
The Expected behavior should be that when compiling to ES6, variable for namespace and imports should be using let or const (when the variable is not used again).

**Actual behavior:**
The compiler still output var when exporting to ES6.

After this not super tragic but we can now output to ES6 then why not using let and const when we can use them?

**Comment by jwbay** [comment]
See #12261

**Comment by niokasgami** [comment]
@jwbay Oh well the difference is although not similar? 

Meanwhile arrow functions can be annoying to deal with,

Let and const dont have any drawback in my opinion

**Comment by DanielRosenwasser** [comment]
Namespaces allow for declaration merging, which is why they need `var`. A `let` declaration would lead to a scoping collision since you can't have multiple `let` declarations of the same name in the same scope.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
