### ISSUE TITLE
DOM lib is missing Intersection Observer API on window global

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/TypeScript#16255]
**TypeScript Version:**  2.3.4

**Code**

The browser Intersection Observer API defines these on the window:

```ts
window.IntersectionObserver
window.IntersectionObserverEntry
```

**Expected behavior:**
These should be defined in the DOM lib typings.

**Actual behavior:**
They are not defined, so I get type errors.

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by remojansen** [comment]
Can this issue be closed? Looks like the change has [already been merged into master](https://github.com/Microsoft/TypeScript/blob/master/lib/lib.dom.d.ts#L7212-L7239)?

**Comment by OliverJAsh** [comment]
Aha, looks like they are in the typings, just not exposed on the `window` interface:

``` ts
new IntersectionObserver(() => {}); // no error
window.IntersectionObserver // error
```

**Comment by Hiswe** [comment]
As a temporary fix

```ts
export {}
declare global {
  interface Window {
    IntersectionObserver: typeof IntersectionObserver
  }
}

```

**Comment by felipedrumond** [comment]
_IntersectionObserverEntry_ lacks isVisible property.
Chrome Version 87.0.4280.88 

![image](https://user-images.githubusercontent.com/17038136/102679874-379a5e80-4207-11eb-8f55-411f75078392.png)

**Comment by Andarist** [comment]
This has been added in 3.6, the issue can be closed
