### ISSUE TITLE
Dotted type in jsdoc is not parsed correctly

### ISSUE THREAD

**Issue by flaviut** [Microsoft/TypeScript#16268]
**TypeScript Version:**  2.4.0-dev.20170605 
**Code**

```ts
import React from 'react';

/**
 * @param {React.FormEventHandler<Checkbox>} a
 */
function foo(a) {}
```

**Expected behavior:**
The language service parses the jsdoc as documented in https://github.com/Microsoft/TypeScript/wiki/JSDoc-support-in-JavaScript

**Actual behavior:**
`[js] '}' expected.` at the `<`. This appears to be a problem with the dotted type, i.e. `import React, {FormEventHandler} from react; …{FormEventHandler<Checkbox>} …` works fine.

Reproduced using visual studio code (I don't know how to manually launch and use the language service).

**Comment by DanielRosenwasser** [comment]
Does it work if you write `import * as React from "react"`?

**Comment by flaviut** [comment]
Nope:

```jsx
import * as React from 'react';

/**
 * @param {React.FormEventHandler<Checkbox>} a
 */
function foo(a) {}
```
`'}' expected.`

-------

This error also happens, as expected, so I think that confirms that the type can be correctly resolved:

```jsx
import React from 'react';

/**
 * @param {React.FormEventHandler} a
 */
function foo(a) {}
```
`Generic type 'FormEventHandler' requires 1 type argument(s).`

**Comment by Volox** [comment]
Is this also somehow related to #14233 ? Is there a semantic difference from `namespace` and dotted notation in Typescript?

**Comment by sandersn** [comment]
JSDoc syntax requires a dot before the type arguments: `React.FormEventHandler.<CheckBox>`. Closure Compiler syntax does not, though.

#17176 should have fixed this because now JSDoc and Typescript use the same parser for all types, so this should be parsed as a normal Typescript-syntax type reference.
