### ISSUE TITLE
Assignment does Not Cause Type Widening

### ISSUE THREAD

**Issue by evansb** [Microsoft/TypeScript#16262]
**TypeScript Version:**  2.3.2
Modified from a question from a [StackOverflow thread](https://stackoverflow.com/questions/44367208/error-ts2365-operator-cannot-be-applied-to-types-and/44367472#44367472). Not sure if this is a bug.
**Code**

```ts
let id: string = ")";

function myFunc() {
  id = "("; /*1*/
};


if (id !== '(')
  throw "Expected '(' in prototype";
// id is narrowed to "("

myFunc();

// id is still "(", 

// now id and ')' does not have same type, this causes type error
if (id !== ')')
  throw "Expected ')' in prototype";
```

**Expected behavior:**
(1) should widen the type of id back to string, so the second if should typecheck.

**Actual behavior:**
`id` still have the literal type '('

**Comment by ahejlsberg** [comment]
See discussion in #9998.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
