### ISSUE TITLE
object destructuring with default values

### ISSUE THREAD

**Issue by arnm** [Microsoft/TypeScript#16260]
**TypeScript Version:**  2.3.2

**Code**

```ts
interface A {
  field: { [a: string]: Array<number> }
}

const someString = 'bob';
const someA: A = ...;

 // correctly infers 'field' is of [a: string]: Array<number>
const { field = {} } = someA;

// incorrectly infers 'someThing' and 'array' to be of type 'any'
const { [someString]: array = [] } = field;
```

In order to get TS to correctly infer types I must do the following:

```ts
// correctly infers 'array' if of type 'Array<number'
// but does not let me easily set default
const array = field[someString];
```

**Expected behavior:**

Type inference should work with object destructuring.

**Actual behavior:**

Type inference cannot correctly infer types when doing object destructuring and providing default values.

**Comment by mhegazy** [comment]
Should be fixed in latest.
