### ISSUE TITLE
Excess property error for spread type appears in interface declaration

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#16272]
**TypeScript Version:** nightly (2.4.0-dev.20170605)

**Code**

```ts
interface A { a: string; }
interface B { b: boolean; }
function aToB(a: A, b: boolean): B {
    return { ...a, b };
}
```

**Expected behavior:**

Error appears inside the object literal that caused it.

**Actual behavior:**

Error appears on the interface.

```
src/a.ts(1,15): error TS2322: Type '{ b: boolean; a: string; }' is not assignable to type 'B'.
  Object literal may only specify known properties, and 'a' does not exist in type 'B'.
```

This could be in a completely different file from the actual source of the error. That's flow's thing.

**Comment by mhegazy** [comment]
This should be fixed now.
