### ISSUE TITLE
Generators and Iteration for ES5/ES3 in VS2017 ,What Should I do ?

### ISSUE THREAD

**Issue by lusess123** [Microsoft/TypeScript#16286]
**TypeScript Version:**  2.3.1 / nightly (23.0-dev.201xxxxx)

**Code**

Microsoft.TypeScript.targets 
```xml

 <TypeScriptBuildConfigurations Condition="'$(TypeScriptDownlevelIteration)' == 'true'">$(TypeScriptBuildConfigurations) --downlevelIteration</TypeScriptBuildConfigurations>
```

project.csproj
```xml
   <TypeScriptDownlevelIteration>True</TypeScriptDownlevelIteration>
```

But it doesn't work ？？？

**Comment by mhegazy** [comment]
Tracked by https://github.com/Microsoft/TypeScript/issues/16164.

As a workaround, you can set `<TypeScriptAdditionalFlags> --downlevelIteration </TypeScriptAdditionalFlags>` or add a tsconfig.json to your project and use it to drive the build.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
