### ISSUE TITLE
Dynamic, generic superclass results in incorrect declaration output

### ISSUE THREAD

**Issue by ngrewe** [Microsoft/TypeScript#16287]
**TypeScript Version:**  2.3.2 

**Code**

The following is considered to be valid TypeScript code:

```ts
export interface IBase<X,Y> {}

export class Base<X,Y> implements IBase<X,Y> {}

export interface BaseCtor<X,Y> {
	new(): IBase<X,Y>;
}

export function CtorFactory<X,Y>(): BaseCtor<X,Y> {
	return Base;
}

export class Derived<X,Y> extends CtorFactory<X,Y>() {
}
```

**Expected behavior:**

Unsure. I believe this is a bit of a non-standard way of using `extends`. Two options:

* The code sample above should be rejected as invalid
* A correct declaration file should be generated when invoking `tsc --declaration`.

**Actual behavior:**

The following declaration file is generated:
```ts
export interface IBase<X, Y> {
}
export declare class Base<X, Y> implements IBase<X, Y> {
}
export interface BaseCtor<X, Y> {
    new (): IBase<X, Y>;
}
export declare function CtorFactory<X, Y>(): BaseCtor<X, Y>;
declare const Derived_base: BaseCtor<X, Y>;
export declare class Derived<X, Y> extends Derived_base {
}
```
The declaration invalid and cannot be used because X and Y are not bound for the declaration of `Derived_base`.

**Comment by mhegazy** [comment]
Should be working as expected in latest.
