### ISSUE TITLE
Parse error on async IIFE with nightly build (javascript file)

### ISSUE THREAD

**Issue by Kovensky** [Microsoft/TypeScript#16289]
**TypeScript Version:**  2.4.0-dev.20170606

**Code**

I am unsure of how to get a proper reproduction for this problem. It doesn't seem to happen consistently either, and just writing an async IIFE anywhere is not enough to cause the error.

![image](https://cloud.githubusercontent.com/assets/73085/26821900/110b7cc8-4ae3-11e7-9ab2-b6faa8bd4512.png)

**Expected behavior:**

Code should parse.

**Actual behavior:**

Parse error wanting an `=` in a place that doesn't make sense.

**Comment by DanielRosenwasser** [comment]
Any idea which nightly you were using prior?

**Comment by Kovensky** [comment]
I was running the latest 2.3 stable. Can try to bisect in a bit.

**Comment by Kovensky** [comment]
Can confirm that it parses on 20170601; will check the days in between.

**Comment by Kovensky** [comment]
This seems to only reproduce with 20170606, but only if `--modules esnext` is enabled.

**Comment by mhegazy** [comment]
@yuit can you take a look.

**Comment by yuit** [comment]
I can't repo this just from the code in the image. Would you be able to share more code in the same file?

**Comment by Kovensky** [comment]
I can't seem to find any way to reproduce this in less code than the entire 2800 line file so far.

The error happens on a .js file with `// @ts-check`, and only in this particular async IIFE. Converting it into a non-arrow expression changes the error to "identifier expected". I thought details such as being inside an async method inside an object, and having self-references could be a problem, but doing that in another file still doesn't reproduce it.

The only clue so far is that removing `// @ts-check` from this file makes it not have a parse error anymore.

The object structure is similar to:

```ts
const message = {
  /** @param {JQuery} inputField */
  async method (inputField) {
    // ...
    const receiverId = inputField.data('receiverId')
    if (receiverId) {
      (async () => {
        try {
          // ...
        } finally {
          // ...
        }
      )()
    }
  }
}
```

**Comment by mhegazy** [comment]
Would it be possible to share the file over email?

**Comment by yuit** [comment]
@Kovensky if you could send it over the email, that will be great. I also have a branch up (https://github.com/Microsoft/TypeScript/tree/master-fixIncrementalParsingWithDynamicImport) if you would like to give it a try !

**Comment by yuit** [comment]
@Kovensky  The PR is checked into master today. If you would like to give `typescript@nightly` a shot...Closing it for house keeping sake but feel free to reopen if the issue persist

**Comment by Kovensky** [comment]
It does seem to still be a parse error if I write it as an IIFE.

The workaround of saving the function in a variable before calling it is working for us, though.

I will see what I can do about getting a reproducible version of the file, but I'm not sure if I'll be able to do that soon 😕

**Comment by BjornMelgaard** [comment]
passed with `;` in begining

```ts
import * as puppeteer from 'puppeteer'

const url: string = 'https://www.socks-proxy.net'
;(async () => {
  const browser = await puppeteer.launch()
  const page = await browser.newPage()
  await page.goto(url)
  debugger

  await browser.close()
})().catch(console.error)

```
