### ISSUE TITLE
SUGGESTIONS: Would be great to have the shortend get, set like in C#

### ISSUE THREAD

**Issue by Chris2011** [Microsoft/TypeScript#16288]
**TypeScript Version:**  2.3.3

**Code**

I know there are several ways to make a getter and a setter in TS. Atm I use:

```typescript
private _test: string = '';

public get Test(): string {
   return this._test;
}

public set Test(value: string) {
   this._test = value;
}
```

this is quite cool, but from the C# perspective, I would like to see an other alternative:

```csharp
string _myProperty;

public string myProperty
{
    get { return _myProperty; }
    set { _myProperty = value; }
}
```

would be great to have this as an alternative option to create setter and getter.

Regards

Chris

**Comment by RyanCavanaugh** [comment]
See #7628
