### ISSUE TITLE
Strict mode: Object is possibly 'null' when it really isn't

### ISSUE THREAD

**Issue by zaggino** [Microsoft/TypeScript#16285]
**TypeScript Version:**  2.3.4

**Code**

```ts
/*
tsconfig.json
{
  "compilerOptions": {
    "target": "ES2015",
    "module": "commonjs",
    "strict": true
  }
}
*/

let maybeNumber = Math.random() > 0.5 ? 2 : null;
let ones = [1, 1, 1];
let twoes;
if (maybeNumber) {
  twoes = ones.map(x => x * maybeNumber);
}
console.log(maybeNumber, twoes);
```

**Expected behavior:**
Compilation passes, TS should know that .map function will be executed immediately and so `maybeNumber` will not be `null`

**Actual behavior:**
Compilation error: `error TS2531: Object is possibly 'null'`

**Weird:**
When I change `let maybeNumber` to `const maybeNumber` compilation passes for some reason, even though type of `maybeNumber` should be still `number | null`

**Comment by DanielRosenwasser** [comment]
See #9998.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
