### ISSUE TITLE
Type guard via `if` does not make value compatible as argument

### ISSUE THREAD

**Issue by Yogu** [Microsoft/TypeScript#16295]
**TypeScript Version:**  2.3.3 (with --strictNullChecks)

The condition `test.a` ensures that `a` can not be `undefined`, thus `test` should be suitable to be passed as `A`. Note that `test.a` is already narrowed down to `string`.

The reason I declare the fields `a` and `b` in `Base` is so that the `if` below does not type error on `test.a`.

**Code**

```ts
interface Base {
    a?: string;
    b?: string;
}

interface A extends Base {
    a: string;
}

interface B extends Base {
    b: string;
}

type Any = A | B;

function source(): Any {
    return {a: ''};
}

function sink(a: A) {

}

let test: Any = source();
if (test.a) {
    const a: string = test.a;
    sink(test);
}
```

**Expected behavior:** It compiles.

**Actual behavior:** error at `sink(test)`:

```
Error:(27, 10) TS2345:Argument of type 'Any' is not assignable to parameter of type 'A'.
  Type 'B' is not assignable to type 'A'.
    Types of property 'a' are incompatible.
      Type 'string | undefined' is not assignable to type 'string'.
        Type 'undefined' is not assignable to type 'string'.
```

**Comment by ikatyang** [comment]
Based on my experience, `if (test.a)` will just narrow the type of `test.a` instead of `test`, so that `if` will do nothing for `test`, you have to use some assertion to narrow the type, for example:

```ts
declare function hasA(v: any): v is {a: any};

if (hasA(test)) {
  sink(test);
}
```

**Comment by Yogu** [comment]
@ikatyang Thanks, that would be an explanation. I guess implementing the suggested feature would add a substantial amount of complexity, then.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
