### ISSUE TITLE
Intellisense issues with commit on space and other punctuation

### ISSUE THREAD

**Issue by danquirk** [Microsoft/TypeScript#1629]
VS now commits completion lists on more than tab and enter, including space and a variety of punctuation characters (semicolon, parens, brackets, etc). There are places where we offer completion lists that we shouldn't, or poor completion lists, which were previously visual distractions but now are significant annoyances in the actual typing experience, requiring constantly dismissing completion lists via Esc to type what you intended.

**Fat arrow functions**
![writealambda](https://cloud.githubusercontent.com/assets/7121557/5688657/d16729f2-980e-11e4-941e-656b974b3a66.gif)
Typing a space after the fat arrow argument commits a suggestion that is never correct, and then happens frequently in the body as well.

**Type argument declarations**
![typeargumentcompletion](https://cloud.githubusercontent.com/assets/7121557/5689110/4b9db39e-9814-11e4-8b4d-1e69299feeed.gif)
Tracked here https://github.com/Microsoft/TypeScript/issues/1428

**Destrucuring Assignments**
![destructuringcompletions](https://cloud.githubusercontent.com/assets/7121557/5689074/ee4c0a92-9813-11e4-8a37-8a0710464913.gif)
Not supported in the editor yet but will need to work like var declaration completion lists.

There are likely other cases as well but these ones stand out immediately. This also ties into #315 which is asking for a toggle on this behavior. Depending on the fix we use for this behavior we may also have some significant test costs associated with these fixes.

**Comment by Peter-Juhasz** [comment]
Sometimes an Esc is better than an Enter every single time. :) You are on the right track.
