### ISSUE TITLE
TS2403: Subsequent variable declarations must have the same type. After NPM install

### ISSUE THREAD

**Issue by AcousticGuitar** [Microsoft/TypeScript#16298]
**TypeScript Version:**  2.2.2

**Code**
This is my TSCConfig file content
```ts
{
    "compilerOptions": {
        "module": "amd",
        "moduleResolution": "node",
        "target": "es5",
        "noImplicitAny": false,
        "jsx": "react",
        "sourceMap": false,
        "baseUrl": ".",
        "paths": {
            "OfficeFabric/*": [
                "node_modules/office-ui-fabric-react/lib-amd/*"
            ]
        }
    } 
}
```

**Expected behavior:**
After running npm install &#64; types/node --save 
The project should compile ok.
**Actual behavior:**
The error message TS2403 is indicated.
Uninstalling the node types fixes the problem. 

Could this be a clash between : module:"amd" and moduleresolution: "node"

Current Node version is 7.0.3 
The installed types was for version + @types/node@7.0.28

**Comment by andy-ms** [comment]
We would need to know the variable that is causing you this problem, and the places where it is defined.

**Comment by AcousticGuitar** [comment]
The error is calling out the index.d.ts Type definition file here.  
This file is found here: node_modules\@types\node\index.d.ts


![noderequire](https://user-images.githubusercontent.com/10676026/26839878-f19bc750-4aa9-11e7-95f8-cc9a226281c3.GIF)

**Comment by andy-ms** [comment]
There must be another definition of `require` somewhere.

**Comment by AcousticGuitar** [comment]
I'm using React when the TSX files are compiled they produce this JS equivalent as first line of JS file.

define(["require", "exports", "react", "OfficeFabric/components/DetailsList/DetailsList"], function (require, exports, React, DetailsList_1) 

Could that be it?

**Comment by andy-ms** [comment]
Try using find-all-references on `declare var require`. It should show you another `declare var require` with a differen type.

**Comment by AcousticGuitar** [comment]
Project is not in Visual Studio, rather VS Code, find all require shows no other vars being declared but I'll look again.

**Comment by AcousticGuitar** [comment]
declare var noderequire: Require;  from vss.d.ts (The VSTS extension SDK)   
declare var require : noderequire from index.d.ts (for Node)

Maybe it's these two that are conflicting?

**Comment by andy-ms** [comment]
Not if they have different names.

**Comment by AcousticGuitar** [comment]
Ok maybe I found it..... I renamed the var require to nrequire and then searched project for all nrequires.  This is what it found:


![nrequire](https://user-images.githubusercontent.com/10676026/26842282-e40880ee-4ab1-11e7-872d-b3d4f970c70b.GIF)

Looks like there is a variable conflict between Node and Require.

**Comment by andy-ms** [comment]
It doesn't make sense to use both of those types at once. Use the [`--types`](http://www.typescriptlang.org/docs/handbook/compiler-options.html) compiler option to choose just the types you need.

**Comment by AcousticGuitar** [comment]
andy, 
Thanks so much for your help I think I understand this now!

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Comment by CJ-Johnson** [comment]
I had the same error and solved it by manually adding `tslint` and `tslint-react` to the `package.json`. It was installed globally before and so switching node versions with nvm was causing issues.

**Comment by jstaro** [comment]
For now, I did this, which seems to work, but feels like a hack:

```typescript
interface AppRequire {
    <T>(path: string): T | any;
    (paths: string[], callback: (...modules: any[]) => void): void | any;
    ensure: (paths: string[], callback: (require: <T>(path: string) => T) => void, chunkName?: string) => void | any;
    context: any;
}

interface NodeRequire extends AppRequire {}
```

**Comment by andy-ms** [comment]
@jstaro It looks like `Jest` defines an interface `NodeRequire` but doesn't actually declare the `require` variable -- I think you could just ignore it then?

**Comment by Thavaprakash** [comment]
I'm getting similar error in `should` npm

node_modules/should/should.d.ts(237,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'should' must be of type 'Assertion', but here has type 'Assertion'.

**Comment by andy-ms** [comment]
@Thavaprakash You probably have 2 such errors -- one in this location and one in another location. For example, you might accidentally have 2 versions of "should" installed that are incompatible.

**Comment by Thavaprakash** [comment]
@andy-ms Thanks for your prompt reply, I don't have 2 versions of "should".  I grepped, i found only one place. 

# grep 'should: should.Assertion' * -inr
node_modules/should/should.d.ts:237:    should: should.Assertion;

**Comment by andy-ms** [comment]
@Thavaprakash OK, could you find-all-references on `should` to look for the other declaration?

**Comment by Thavaprakash** [comment]
`should` references are many places, we can't dig into that. [I tried this, it works but this global varibale](https://github.com/shouldjs/should.js/issues/147#issuecomment-364402149)

**Comment by andy-ms** [comment]
You could also go-to-definition on any of the references and you will probably see two definitions.

**Comment by Thavaprakash** [comment]
Issue is [fixed](https://github.com/shouldjs/should.js/issues/166#issuecomment-364957615)
