### ISSUE TITLE
Error: Debug Failure - Assertion in reportError / hasExcessProperties

### ISSUE THREAD

**Issue by cri5ti** [Microsoft/TypeScript#16292]
Using typescript@2.4.0-dev.20170605
(Via awesome-typescript-loader@3.1.3)

```
[at-loader]: Child process failed to process the request:  Error: Debug Failure.
    at reportError (C:\Iplicit\src\Web\node_modules\typescript\lib\typescript.js:34490:26)
    at hasExcessProperties (C:\Iplicit\src\Web\node_modules\typescript\lib\typescript.js:34682:37)
    at isRelatedTo (C:\Iplicit\src\Web\node_modules\typescript\lib\typescript.js:34564:25)
    at checkTypeRelatedTo (C:\Iplicit\src\Web\node_modules\typescript\lib\typescript.js:34478:26)
    at checkApplicableSignature (C:\Iplicit\src\Web\node_modules\typescript\lib\typescript.js:40390:26)
    at resolveCall (C:\Iplicit\src\Web\node_modules\typescript\lib\typescript.js:40812:17)
    at resolveCallExpression (C:\Iplicit\src\Web\node_modules\typescript\lib\typescript.js:40997:20)
    at resolveSignature (C:\Iplicit\src\Web\node_modules\typescript\lib\typescript.js:41232:28)
    at getResolvedSignature (C:\Iplicit\src\Web\node_modules\typescript\lib\typescript.js:41264:26)
    at checkCallExpression (C:\Iplicit\src\Web\node_modules\typescript\lib\typescript.js:41291:29)
    at checkExpressionWorker (C:\Iplicit\src\Web\node_modules\typescript\lib\typescript.js:42761:28)
    at checkExpression (C:\Iplicit\src\Web\node_modules\typescript\lib\typescript.js:42713:42)
    at checkExpressionCached (C:\Iplicit\src\Web\node_modules\typescript\lib\typescript.js:42594:38)
    at C:\Iplicit\src\Web\node_modules\typescript\lib\typescript.js:41653:32
    at traverse (C:\Iplicit\src\Web\node_modules\typescript\lib\typescript.js:7419:28)
    at visitEachNode (C:\Iplicit\src\Web\node_modules\typescript\lib\typescript.js:15816:30)
```

The code I'm getting this in is too big to share, but if you think you need a test case I can try to reduce the problem to a single file.

---

A quick look seems to point to an assertion on `errorNode` in `reportError()`:

Which seems to be caused by this assignment in `hasExcessProperties()`

    errorNode = prop.valueDeclaration;                                 

I think the offending expression node is an object literal property value shorthand
(Would the valueDeclaration part of the tree be missing in this case?)

This "fixed" it for me, though not sure how correct it is:
typescript.js:34685:

    if (prop.valueDeclaration)
        errorNode = prop.valueDeclaration;

**Comment by mhegazy** [comment]
Can you share the call expression that triggered the crash?

**Comment by cri5ti** [comment]
@mhegazy The code that triggered that error was: 
The errorNode before the assignment was pointing at the `rows` symbol above (I did a quick console.log on that). 

```
return React.createElement(this.Layout, {
	rows,
	hasMore: {
		setView: source.setView.bind(source),
		from: source.viewStatus.skip,
		pageSize: source.viewStatus.pageSize,
		total: source.allLength
	},
	...rest,
	...this.tableProps
});
```

I'm going to try to reduce it to a basic example of the issue, so you can reproduce it as well.

**Comment by sandersn** [comment]
Since it's a missing `valueDeclaration` on a property, I'd guess that `...rest` is at fault, or maybe `...this.tableProps`. Probably one of the properties from the spreads is synthetic and doesn't have `valueDeclaration` set.

**Comment by sandersn** [comment]
@cri5ti can you give more context? Since I suspect `...rest`, I tried this program, but it did not crash. It properly detected `c` as an excess property.

```ts
declare function f({ a: number }): void
class C {
    test({ b, ...rest }: { b: number, c: number }, [d, ...lr]: number[]) {
        f({
            a: d,
            ...rest,
        })
    }
}
```

Specifically, I'd like to know the type of `rest`, `this.tableProps` and probably `rows`.

**Comment by sandersn** [comment]
It was not rest, but spread's synthetic properties that are at fault. I found two cases that triggered the crash since `getSpreadType` creates two different kinds of synthetic properties:

```ts
declare function f({ a: number }): void
interface I {
    readonly n: number;
}
declare let i: I;
f({ a: 1, ...i });

interface R {
    opt?: number
}
interface L {
    opt: string
}
declare let l: L;
declare let r: R;
f({ a: 1, ...l, ...r });
```

**Comment by cri5ti** [comment]
I've also tried to reproduce the bug on a small example, but ended up noticing that the crash does not occur running tsc directly on my example, but only via awesome-typescript-loader which it seems uses a two stage process, emitting and checking. The crash occurred during the getSemanticDiagnostics() of the language service. 
I haven't managed to track it down yet.

**Comment by sandersn** [comment]
Probably `rest` or `tableProps` has some (1) readonly properties or (2) `tableProps` has some optional properties, since those are the cases when `getSpreadType` creates synthetic properties.

Given the example is react, I'd guess that it's `tableProps` having optional properties. You can try making those required to see if it fixes the error.

**Comment by sandersn** [comment]
Fix is up at #16377

**Comment by cri5ti** [comment]
Indeed, `tableProps` was the offending expression.
Though it was not the optional props, but it was a `Partial<T>`. Changing the tableProps declaration type from `Partial<T>` to `T` bypasses the crash.

Here's more of the code:
https://gist.github.com/cri5ti/16a3d4e2163d64a88adcef3564693861#file-table-ts-L38

**Comment by sandersn** [comment]
I see: `rest` is derived from `IMetaTableProps` and `tableProps` comes from `ITableProps`. Presumably those two types have some optional properties with the same name, which is why `getSpreadType` would combine them into a synthetic property. (Just like the `L/R` case in the repro I gave above.)
