### ISSUE TITLE
Bug with default export class in namespace

### ISSUE THREAD

**Issue by ajafff** [Microsoft/TypeScript#16301]
**TypeScript Version:**  2.3.4 and current playground

**Code**

```ts
namespace ns {
    export default class Foo{ } // no error
}
ns.Foo; // error
ns.default; // no error
```
[playground](http://www.typescriptlang.org/play/#src=namespace%20ns%20%7B%0A%20%20%20%20export%20default%20class%20Foo%7B%20%7D%20%2F%2F%20no%20error%0A%7D%0Ans.Foo%3B%0Ans.default%3B)

**Expected behavior:**
Error at declaration that default exports are only allowed in ECMAScript modules.

**Actual behavior:**
No error at declaration.

Code completion shows `ns.Foo` but compiler prints warning.
Code completion does not show `ns.default` but tooltip reveals it is `class ns.Foo`. That's completely wrong because the emit does not contain any default export.

**Comment by charlespierce** [comment]
PR opened to address this issue: #16704

**Comment by DanielRosenwasser** [comment]
Thanks!
