### ISSUE TITLE
[Bug] Class method is nameless

### ISSUE THREAD

**Issue by luchillo17** [Microsoft/TypeScript#16304]
**TypeScript Version:**  2.3.4

**Code**

![image](https://user-images.githubusercontent.com/9698639/26848158-1e0a2618-4ac5-11e7-8200-6042479937ac.png)

**Expected behavior:**
Expected to obtain the `save` string.

**Actual behavior:**
Got empty string.

**Motivation:**
I was doing this:
```ts
let method = 'newNotification'; 
if (this.mode === 'edit') { 
  method = 'updateNotification'; 
}
this.notifService[method](this.notif);
```
But if i refactor with VSCode those string doesn't rename, so i tough this would solve that:
```ts
let method = NotificationService.prototype.saveNotification.name;
if (this.mode === 'edit') {
  method = NotificationService.prototype.updateNotification.name;
}
this.notifService[method](this.notif);
```
But typescript would transpile like a nameless function in a property of the class proto:
```ts
var NotificationService = (function () {
...
NotificationService.prototype.saveNotification = function (notification) {...}
...
}
```

**Comment by mhegazy** [comment]
duplicate of https://github.com/Microsoft/TypeScript/issues/5611

**Comment by luchillo17** [comment]
Duplicated indeed.
