### ISSUE TITLE
Declaration emit is incorrect when type parameter names collide

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#16313]
```ts
function f<T>(p: T) {
    let g: <T>(x: T) => typeof p = null as any;
    return g;
}
```

Calling `f(10)` will produce something of type `<T>(x: T) => number`, however, the declaration emit is the following:

```ts
declare function f<T>(p: T): <T>(x: T) => T;
```

But calling that `f` produces the type `<T>(x: T) => T`.

**Comment by gcnew** [comment]
I'm looking forward for a solution to this issue. It would be a big problem when polymorphic unification gets implemented, because generic parameters must be instantiated with a copy of their type parameters for inference to properly work.

```ts
declare function id<X>(x: X): X;
declare function mapPair<A, B, C, D>(
    fx: (a: A) => B,
    fy: (c: C) => D
): (a: A, c: C) => [B, D];

mapPair(id, id) // = mapPair<X, X, X, X>, but should be mapPair<X1, X1, X2, X2>
```
