### ISSUE TITLE
Refine type of "typeof" operator

### ISSUE THREAD

**Issue by DylanRJohnston** [Microsoft/TypeScript#16314]
It would be super useful when trying to index into mapped types if the result of the `typeof` operator was aware of its context.

Right now
```
type PrimitiveLiterals = "string" | "number" | "boolean" | "symbol" | "undefined" | "object" | "function"

function foo(x : number | string | boolean): PrimitiveLiterals {
    return typeof x;
}
```

Proposed
```
function foo(x: number | string | boolean): "number" | "string" | "boolean" {
    return typeof x;
}
```

I guess this essentially amounts to wanting a way to go from a Primitive type to a string literal representing that type.

**Comment by DylanRJohnston** [comment]
Alternatively we could allow for primitive types as indexes, you would never be able to actually assign an value to the type, but it would work really well for mapped types.

```
type Foo = {
    [number]: "NUMBER"
}

const foo : Foo = {...anything at all} // Error

type Bar = Foo[number]; // type bar = "NUMBER"
```

**Comment by RyanCavanaugh** [comment]
Makes sense (the first part, at least). The only concern I'd have is that (in strict null checks mode) we allow comparisons to `undefined` for safety when dealing with JS callers, and I think we'd want to still allow people to write `typeof x === 'undefined'` for arbitrary `x`... which means if `x` is `string | number` then `typeof x` would be `"string" | "number" | "undefined"` which just feels like a bug at first glance.

Maybe I'm overthinking it and everyone writes `x === undefined` or `x == null` and we don't need to worry about consistency for `typeof`

**Comment by DylanRJohnston** [comment]
Yeah I agree the second proposal is pretty silly. I'm not sure I follow why that's the case in strict null check mode? I would have thought it would be the other way around?

**Comment by RyanCavanaugh** [comment]
On balance this doesn't seem worth it. We want to always allow checks for `null` / `undefined` for defensive programming, which means `undefined` *and* `object` would always be in the return type. And if any object type appears in the operand, then subtyping means `function` needs to be in there too, so a simple type `number | { x: number }` now returns `number | object | function | undefined`... which isn't a very big improvement over the current result.

**Comment by mihailik** [comment]
Keep in mind `BigInt` proposal introduces `typeof` of `"bigint"`. Other exotic JS engines may already have similar quirks.

https://tc39.github.io/proposal-bigint/#sec-typeof-operator

BigInt folks <a href="https://github.com/tc39/proposal-bigint/issues/35">argue</a> that `typeof X` result set is not an invariant they care much about, by the way.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
