### ISSUE TITLE
two incorrect transpilation? arrow-args and for-of-objects

### ISSUE THREAD

**Issue by unional** [Microsoft/TypeScript#16318]
I just notice this:
http://incaseofstairs.com/six-speed
It says the following two code produces incorrect behavior in TypeScript:

```js
var obj = {
  value: 42,
  fn: function() {
    return () => arguments[0];
  }
};

var fn = obj.fn(1);
assertEqual(fn(), 1);

test(function() {
  fn();
});
```

```js
var data = {'a': 'b', 'c': 'd'};
data[Symbol.iterator] = function() {
  var array = Object.keys(data),
      nextIndex = 0;

  return {
    next: function() {
       return nextIndex < array.length ?
         {value: data[array[nextIndex++]], done: false} :
         {done: true};
    }
  };
};

function fn() {
  var ret = '';
  for (var value of data) {
    ret += value;
  }
  return ret;
}

assertEqual(fn(), 'bd');
test(fn);
```

Is this true / still true?
Is there some fix issue pending for these?

**Comment by mhegazy** [comment]
Please see https://github.com/Microsoft/TypeScript/issues/2430. the compiler flags these as errors instead.

**Comment by unional** [comment]
Same for `for-of-objects`? It is not mentioned in #2430

**Comment by mhegazy** [comment]
should work with `--downlevelIteration`

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
