### ISSUE TITLE
Curly brace enforcing with tslint

### ISSUE THREAD

**Issue by TravCav** [Microsoft/TypeScript#16322]
I'm seeing a lot of places where rule 6 of the style standard in the [coding guidelines](https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines) isn't being followed.
_6. Always surround loop and conditional bodies with curly braces._

Can we consider enabling **"curly": true** or **"curly": [true, "ignore-same-line"]** to tslint.json

**Comment by mhegazy** [comment]
thanks!
