### ISSUE TITLE
Diagnostic codes are numbers, not enums

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Microsoft/TypeScript#16332]
**TypeScript Version:**  2.3.X

**Code**

*(copy & pasted from [TSLint's noUnusedVariableRule](https://github.com/palantir/tslint/blob/master/src/rules/noUnusedVariableRule.ts))*
```typescript
const enum UnusedKind {
    VARIABLE_OR_PARAMETER,
    PROPERTY,
}
function getUnusedDiagnostic(diag: ts.Diagnostic): UnusedKind | undefined  {
    switch (diag.code) {
        case 6133:
            return UnusedKind.VARIABLE_OR_PARAMETER; // "'{0}' is declared but never used.
        case 6138:
            return UnusedKind.PROPERTY; // "Property '{0}' is declared but never used."
        default:
            return undefined;
    }
}
```

**Expected behavior:**

Shouldn't TypeScript provide an enum describing the diagnostic codes?

**Actual behavior:**

They're just typed as numbers.

**Comment by mhegazy** [comment]
We do have a map for diagnostic messages as a while under `ts.Diagnotics`, we do not rely pay much attention to the codes (other than in quick fixes).

**Comment by DanielRosenwasser** [comment]
`case 6133:` 😨 

Why didn't someone reference the code of the diagnostic itself?

**Comment by JoshuaKGoldberg** [comment]
> reference the code of the diagnostic itself

Great question. However, I think that's outside the scope of this issue - I was just curious why the typing of `code` is `number` and not some `DiagnosticCode`.

**Comment by mhegazy** [comment]
> Great question. However, I think that's outside the scope of this issue - I was just curious why the typing of code is number and not some DiagnosticCode.

to make sure that adding a diagnostic had only one place to edit.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
