### ISSUE TITLE
allowjs

### ISSUE THREAD

**Issue by BobFrGit** [Microsoft/TypeScript#16349]
**TypeScript Version:**  2.2.1 / nightly (2.2.0-dev.201xxxxx)

**Code**

```ts
// A *self-contained* demonstration of the problem follows...

```

**Expected behavior:**

**Actual behavior:**

**Comment by BobFrGit** [comment]
If I accidentally press "new issue" how do I delete a post before it goes on the record?

**Comment by ikatyang** [comment]
GitHub does not allow to delete a issue, just close it.
