### ISSUE TITLE
JS Transform: telling it to use ES5

### ISSUE THREAD

**Issue by puppetmaster3** [Microsoft/TypeScript#16340]
When using node to compile ( https://github.com/jstransformers/jstransformer-typescript/blob/master/index.js ) typescript (https://github.com/jstransformers/jstransformer-typescript ) how is the string 'target es5' passed?

**Comment by mhegazy** [comment]
```ts
let result = ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.CommonJS } });
```

see https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#a-simple-transform-function

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
