### ISSUE TITLE
Untyped function calls may not accept type arguments

### ISSUE THREAD

**Issue by rogergl** [Microsoft/TypeScript#1634]
The following code results in this error message:

mu.ts(52,10): error TS2347: Untyped function calls may not accept type arguments.

Why ?

```JavaScript
class JsonRequest<T> {
	makePromise(request: https.RequestOptions): Promise<T> {
52: 		return new Promise<T>(function(resolve, reject) {
```

**Comment by DanielRosenwasser** [comment]
Generally you use type arguments if you want to have type safety. What would it mean to give `T` as a type argument to `Promise` if it's typed as `any`? Just `any`? Sure, that's somewhat intuitionistic even if `any` doesn't have type parameters - but didn't you give a type argument to get type safety? So it makes little sense.

Maybe you can explain your use case better - why isn't `Promise` just typed?

**Comment by rogergl** [comment]
The JsonRequest is created like this:

```JavaScript
var categoryJsonRequest = new JsonRequest<CategoryResult>();
```
Therefore I expected that I can use the generic type parameter to create a Promise of the given type (CategoryResult in this case). 

BTW: the definition in the d.ts file looks like this

```JavaScript
declare class Promise<R> implements Thenable<R> {
	constructor(callback: (resolve : (result?: R) => void, reject: (error: any) => void) => void);
```

**Comment by DanielRosenwasser** [comment]
Ah, my apologies, I misunderstood your question - I thought your definition of `Promise` was typed as `any`.

I'm not able to reproduce this issue - have you tried using the compiler from our `release-1.4` or `master` branches?

**Comment by rogergl** [comment]
Just checked it with the latest release from master (message TS6029: Version 1.4.0.0). Same result.

**Comment by DanielRosenwasser** [comment]
Could you share more code? Also, what promises library are you using?

**Comment by rogergl** [comment]
I made a gist: https://gist.github.com/rogergl/e22afc63dafd8c2b0f6a

**Comment by DanielRosenwasser** [comment]
Replace 

```TypeScript
var Promise = require('es6-promise').Promise;
```

with

```TypeScript
import es6PromiseLib = require('es6-promise');
var Promise = es6PromiseLib.Promise;
```

Let me know if that fixes your issue.

**Comment by rogergl** [comment]
Yes it fixes my issue.

**Comment by DanielRosenwasser** [comment]
Great! As an explanation, the reason this happened is because we only try to fetch type information in the presence of an `import` directive, so the `require` on its own isn't sufficient.

**Comment by rogergl** [comment]
Thanks a lot for the help and the explanation.
