### ISSUE TITLE
Object destructuring fails if defaults are set

### ISSUE THREAD

**Issue by jantimon** [Microsoft/TypeScript#16355]
**TypeScript Version:**  2.2.1 / nightly (2.2.0-dev.201xxxxx)
[Try it yourself in the playground](http://www.typescriptlang.org/play/index.html#src=function%20fancyMethod(%7B%20option1%3Aboolean%20%3D%20true%2C%20option2%3A%20number%20%3D%201%20%7D%20%3D%20%7B%7D)%20%7B%0A%20%20%20%20console.log(option1%2C%20option2)%3B%0A%7D%0A%0AfancyMethod()%3B%0AfancyMethod(%7Boption2%3A%203%7D)%3B)

**Code**

```ts
function fancyMethod({ option1:boolean = true, option2: number = 1 } = {}) {
    console.log(option1, option2);
}

fancyMethod();
fancyMethod({option2: 3});
```

**Expected behavior:**
Console log shows value of option1 and option 2

**Actual behavior:**
Typescript shows errors:
* Cannot find name 'option1'.
* Cannot find name 'option2'.

**Comment by ikatyang** [comment]
I think this is what you want. Object destructuring with type sometime really confuses people.

```ts
function fancyMethod({ option1 = true, option2 = 1 }: { option1?: boolean, option2?: number } = {}) {
    console.log(option1, option2);
}
fancyMethod();
fancyMethod({option2: 3});
```

**Comment by jantimon** [comment]
Thanks I tried this but didn't use it because of https://github.com/Microsoft/TypeScript/issues/16354

The solution now is:

```
function fancyMethod({ option1 = true, option2 = 1 }: object & { option1?: boolean, option2?: number } = {}) {
    console.log(option1, option2);
}
```

Which is a lot harder to read than 

```
function fancyMethod({ option1:boolean = true, option2: number = 1 } = {}) {
    console.log(option1, option2);
}
```

**Comment by ikatyang** [comment]
This is not a valid TS code, since `:` in destructuring is considered renaming.

```ts
function fancyMethod({ option1: boolean = true, option2: number = 1 } = {}) { // <--
    console.log(option1, option2);
}
```

Additionally, `{}` is not assignable to `{ option1, option2 }`, since there is no `option1` and `option2` in `{}`.

---

I think you can use `type` or `interface` to simplify the type declaration. For example:

```ts
interface X {
  option1?: boolean;
  option2?: number;
}
type NonPrimitive<T> = object & T;

function fancyMethod(x: NonPrimitive<X> = {}) {
  const {
    option1 = true,
    option2 = 1,
  } = x;
  console.log(option1, option2);
}
```

**Comment by jantimon** [comment]
Unfortunately the interface would be far away from the method as it is a class method.

But thanks to your explanation with the renaming I am now understanding the reason behind it  👍
