### ISSUE TITLE
'typeof' check ignored by the TS compiler

### ISSUE THREAD

**Issue by karvapallo** [microsoft/TypeScript#16361]
**TypeScript Version:**  2.3.4

**Code**

```ts
  set value(value: T) {
    if (typeof value === 'object') {
      this._value = new Proxy(value, {
        get: (target, property) => {
          return target[property];
        },
        set: (target, property, value, receiver) => {
          target[property] = value;
          this.changed.next(this);
          return true;
        },
        deleteProperty: (target, property) => {
          return true;
        }
      });
    } else {
      this._value = value;
    }

    this.changed.next(this);
  }

```

**Expected behavior:**

I would expect this to compile fine, as we are checking to make sure that `value` is of type `object` before passing it as the first parameter to `Proxy`. And I can't mark T as `<T extends object>` since it might also be a simple `number`.

**Actual behavior:**

I get a compilation error like this one:
```
(35,30): error TS2345: Argument of type 'T' is not assignable to parameter of type 'object'.
````

**Comment by RyanCavanaugh** [comment]
Closing due to lack of additional feedback. Possible this has been fixed but the repro isn't very isolated.
