### ISSUE TITLE
Const enum indexing not checked correctly

### ISSUE THREAD

**Issue by ahejlsberg** [Microsoft/TypeScript#1636]
Something is busted in the way we check indexed access with const enums. The behavior should be that you get an error if you index with anything but a string literal that denotes an existing member. You do indeed get an error if you index with an expression that isn’t a string literal, but you get no error if the string literal doesn’t denote a member. Instead you get bogus code emitted. For example:
```typescript
const enum Color { r, g, b }
var x = Color["r"];
var y = Color["x"];  // Error expected here
```
The resulting emitted code is:
```javascript
var x = 0 /* "r" */;
var y = Color["x"];
```
which obviously won't work since nothing is emitted for `Color` (as expected).

**Comment by danquirk** [comment]
We should try to get a spec and corresponding conformance tests checked in for this (const enums). We have an increasingly large number of features without our usual formal process of spec + tests.
