### ISSUE TITLE
Type checking is not working properly with promises. 

### ISSUE THREAD

**Issue by joeuy** [Microsoft/TypeScript#16369]
**TypeScript Version:**  2.2.1 / nightly (2.2.0-dev.201xxxxx)

**Code**
```ts
var p1: Promise<{ a: string }>;
var p2: Promise<{ a: string, b: string }>;
p2 = p1;
```
[link to playground](https://www.typescriptlang.org/play/#src=var%20p1%3A%20Promise%3C%7B%20a%3A%20string%20%7D%3E%3B%0D%0Avar%20p2%3A%20Promise%3C%7B%20a%3A%20string%2C%20b%3A%20string%20%7D%3E%3B%0D%0Ap2%20%3D%20p1%3B)

**Expected behavior:**
Type error

**Actual behavior:**
No error

**Comment by RyanCavanaugh** [comment]
See #15104
