### ISSUE TITLE
Unstable values of enum SyntaxKind break compatibility with language service plugins

### ISSUE THREAD

**Issue by mvirkkunen** [Microsoft/TypeScript#16367]
The enum values of SyntaxKind (plus a few smaller enums) in [types.ts](https://github.com/Microsoft/TypeScript/blob/b94c51360bf740011fdcc6c6e91a42e040d98f4e/src/compiler/types.ts) are not specified as constant values and therefore adding new members between existing ones changes the values of other members. These values end up in [tsserverlibrary.d.ts](https://github.com/Microsoft/TypeScript/blob/b94c51360bf740011fdcc6c6e91a42e040d98f4e/lib/tsserverlibrary.d.ts) and through that into compiled language service plugins that are published on for instance npm. In a compiled plugin the values will be simple numeric constants from whatever version it was compiled against. Due to this, a language service plugin will probably work incorrectly if the compiler version it's running under is even slightly different from the one it was compiled against.

The edit history of this file looks like members are being added without taking this into account:

https://github.com/Microsoft/TypeScript/blame/d450b8b2ab788d0ca6a22e5202685ac39fc86e9f/src/compiler/types.ts#L50

Even though these values might be semi-internal, I think it would make sense to keep the values stable at least within the same major version in order to not unnecessarily break compatibility with language service plugins. I ran into this problem while playing around with a plugin compiled against the newest version of TypeScript from npm and running it within VS 2017 which apparently has a slightly older version of TypeScript and the enum values are slightly different.

**Comment by mhegazy** [comment]
The enum is not meant to be const, we use the const to get an optimized output for tsc.js, but we have a post build step to remove the `const` from `typescript.js` along with maintaining the enum object in there (see [JakeFile](https://github.com/Microsoft/TypeScript/blob/b94c51360bf740011fdcc6c6e91a42e040d98f4e/Jakefile.js#L554)), we need to do the same for tsserverLibrary.d.ts.

PRs appreciated.

**Comment by mhegazy** [comment]
Fix up in  #16367

**Comment by DanielRosenwasser** [comment]
I think you meant #16381 😄
