### ISSUE TITLE
Jsdoc: Allow @type annotation on function declaration

### ISSUE THREAD

**Issue by andy-ms** [microsoft/TypeScript#16371]
**TypeScript Version:**  nightly (2.4.0-dev.20170608)

**Code**

```js
/** @type {function(number): number} */
function f(x) { return x + 1; }
f(""); // Expect error
```

**Expected behavior:**

Uses a `@type` comment to type a function declaration.
In a JS codebase with `--noImplicitAny` it would get annoying to have to type
```js
/**
 * @param {number} x
 * @return {number}
 */
```
on every function.

**Actual behavior:**

`@type` declaration ignored.

**Comment by rbuckton** [comment]
The [`@type` tag](http://usejsdoc.org/tags-type.html) is not very clear on its usage WRT functions. According to the documentation:
> The `@type` tag allows you to provide a type expression identifying the type of value that a symbol may contain, or _the type of value returned by a function_ **[emphasis added]**. You can also include type expressions with many other JSDoc tags, such as the `@param` tag.

From this, it seems unclear whether or not the `@type` tag is equivalent to `@return` in this case.

**Comment by kaleb** [comment]
`@callback` seems like the way to typedef functions.

http://usejsdoc.org/tags-callback.html

**Comment by michaeljota** [comment]
This would be a nice thing to have, even to use with Typescript, cause with this you would type the function itself, instead of create a typed variable that reference a function. This is when using interfaces for typing functions.

**Comment by sandersn** [comment]
This works, since 2.7 or so I believe. I don't think it's standard jsdoc, though.
