### ISSUE TITLE
Improve error message "Cannot compile namespaces when the '--isolatedModules' flag is provided"

### ISSUE THREAD

**Issue by andy-ms** [microsoft/TypeScript#16398]
**TypeScript Version:**  nightly (2.4.0-dev.20170609)

**Code**

```ts
declare module "foo" {}
```

**Expected behavior:**

"Cannot compile ambient module declarations" or "Cannot compile module augmentations".

**Actual behavior:**

"Cannot compile namespaces"

**Comment by mhegazy** [comment]
related to https://github.com/Microsoft/TypeScript/issues/15230

**Comment by jakebailey** [comment]
Just looking at old issues; this was fixed by #40032 (and this issue was a dupe of the above, effectively).
