### ISSUE TITLE
Some questions regarding some concepts of TypeScript

### ISSUE THREAD

**Issue by rogergl** [Microsoft/TypeScript#1639]
I'm just trying to understand the main difference between Typescript and Flow. So far I have the following questions.

1. Does the typescript Compiler caches any informations from the last compile or does it just watch for changes to a file and then starts always from the beginning ?

2. Is it true to say that TypeScript is primarily using type annotations and does not support type inference like flow does ?

**Comment by CyrusNajmabadi** [comment]
Hey @rogergl thanks for your questions.  As to '1'.  The typescript compiler, when using --watch, will watch for changes to files on disk and will only reparse and rebind files that are changed.  The ASTs and symbols we create for unchanged files will be preserved.  Not that --watch is only currently supported if you compile using 'node'.  

As for '2', it's unclear what you mean by 'primarily'.  It's true that TypeScript and Flow have different forms of inference.  However, TypeScript still uses inference heavily in its design. Now, how you use the language is a personal decision.  You may choose to use annotations if you want, or you can use inference heavily.  Personally, i go for the latter (preferring brevity in the code).

**Comment by DanielRosenwasser** [comment]
Really a "persistent server" that detects file changes is exactly what `--watch` does.

@CyrusNajmabadi answered before me, but I'll also add that in a future release, the `--watch` compiler flag can be used in conjunction with `--noEmit` to speed up the feedback loop when prototyping code.

**Comment by basarat** [comment]
> 2.) Is it true to say that TypeScript is primarily using type annotations and does not support type inference like flow does ?

As answered already, No. However the manner of Type Inference in `flow` is much different. In flow the types *flow* through your code more. e.g. the following will be an error in `flow`:
```ts
function onlyWorksOnNumbers(x) {
  return x * 10;
}
onlyWorksOnNumbers('Hello, world!');
```
Because x is assumed to be a `number` as you are doing some multiplication `*` with it. Here TypeScript would assume x to be `:any` and then `x*10` to be `any` and then everything will compile. Note that TypeScript is still doing *inference* here for `x` as well as `onlyWorksOnNumbers` but the inference rules are different (and IMHO well defined and more easy to reason about). 

Note: If you are worried about `any` you can always compile TypeScript with `--noImplicitAny`

**Comment by rogergl** [comment]
Thanks for the explanation. Is there any documentation available that explain the inference rules Typescript uses in detail ?

**Comment by rogergl** [comment]
One more question. Does TypeScript assume that z is of type number ?

```JavaScript
function test(y: number) {
  var z = y;
  if (z > 1) {
    foo(2);
    } else {
      foo(1);
    }
  }
```
  test(2);

**Comment by DanielRosenwasser** [comment]
> Does TypeScript assume that z is of type number ?

Yes.

**Comment by DanielRosenwasser** [comment]
I encourage you to try out TypeScript on our playground: http://www.typescriptlang.org/Playground

There, you'll be able to see how TypeScript works (including the kind of tooling support that it enables). Try hovering your mouse over variables to see what their types are.

**Comment by danquirk** [comment]
The language specification details precisely how inference works in all cases if you want to understand precisely what's happening but you'll probably have an easier time getting a feel for how it works in practice by using the Playground linked previously.

**Comment by rogergl** [comment]
Yes, being able to see the inferred types in the playground  is very helpful.

Thanks.
