### ISSUE TITLE
Broken public API in tsserver

### ISSUE THREAD

**Issue by anstarovoyt** [Microsoft/TypeScript#16393]
Hi. [This commit](https://github.com/Microsoft/TypeScript/commit/f6240cb6f91fb202c8c0b8fc21d965fd83ea62b7#diff-121b46a8c0f71b73817f429b57e27e61R6) broke our integration with tsserver. Now the commands are 'phantom' and we cannot reference them in our code. For example we use it here:
https://github.com/JetBrains/intellij-plugins/blob/master/AngularJS/src/ngLanguageService/angular-session.ts#L46

We use own abstraction under tsserver (in fact tsserverlibrary.js) in IDEA / WebStorm / other jetbrains products so a lot of users will be affected. 

Is it expected breaking change?
//cc @andy-ms

**Comment by anstarovoyt** [comment]
rel. https://youtrack.jetbrains.com/issue/WEB-27249

**Comment by mhegazy** [comment]
can you build against lib\protocol.d.ts instead?

**Comment by anstarovoyt** [comment]
@mhegazy yes, I can. But it requires to rebuild the app with ts2.4 and unfortunately the version will be broken for all our users WS2017.1 / IDEA2017.1 etc.

**Comment by mhegazy** [comment]
The file is built with preserveConstEnums, so the enum should still be there. i am not sure i understand the issue.. do you have tsserverlibrary in the same process? if so, after this change is ts.server.protocol.CommandTypes non-existent?

**Comment by anstarovoyt** [comment]
@mhegazy sorry, I will clarify.
In our javascript (typescript) code we use ts.server.protocol.CommandNames. After the 
[121b46a8c0f71b73817f429b57e27e61R6](https://github.com/Microsoft/TypeScript/commit/f6240cb6f91fb202c8c0b8fc21d965fd83ea62b7#diff-121b46a8c0f71b73817f429b57e27e61R6) and [e3155e304f4c857fb1d9df7fc74154e9L115](
https://github.com/Microsoft/TypeScript/commit/f94818da36c58f9fc0d6d535677f6500a096f6de#diff-e3155e304f4c857fb1d9df7fc74154e9L115)
ts.server.protocol.CommandNames doesn't exist in runtime.

**Comment by mhegazy** [comment]
I see the issue now, can you give https://github.com/Microsoft/TypeScript/pull/16409 a try?

**Comment by anstarovoyt** [comment]
@mhegazy Yes, it works. The version typescript@rc doesn't contain the changes. Is it ok?

**Comment by mhegazy** [comment]
the next one (`typescript@2.4.1`) will be out in 2 weeks.

**Comment by istiti** [comment]
same issue here

**Comment by eclimoom** [comment]
same issue like
Process: Error processing message: Cannot read property 'getOrCreateScriptInfo' of undefined TypeError: Cannot read property 'getOrCreateScriptInfo' of undefined

**Comment by andy-ms** [comment]
@eclimoom Could you create a new issue for that and provide instructions to reproduce the error?

**Comment by eclimoom** [comment]
thank you,
after update my webstorm no this error.
