### ISSUE TITLE
Cannot write file because it would overwrite input file

### ISSUE THREAD

**Issue by Sampath-Lokuge** [Microsoft/TypeScript#16394]
**TypeScript Version:**  2.3.3

**tsconfig.json**

```
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "dom",
      "es2015"
    ],
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "target": "es5",
    "allowJs": true
  },
  "include": [
    "src/**/*.ts"
  ],
  "exclude": [
    "node_modules"
  ],
  "compileOnSave": false,
  "atom": {
    "rewriteTsconfig": false
  }
}
```

**Error:**

```
typescript error
            Cannot write file '/sophy/node_modules/nprogress/nprogress.js' because it
            would overwrite input file.
```
I'm using [**Ionic 3.3.0** ](https://github.com/ionic-team/ionic/releases/tag/v3.3.0)

According to the above release notes, I have removed `src/declarations.d.ts` file.After that above error came.

> Another optional step is to remove the src/declarations.d.ts file. This is a legacy file introduced early with ionic-angular projects to improve compatibility between TypeScript and third-party libraries. Due to improvements in TypeScript, this file is no longer necessary. By removing this file, the TypeScript compiler will be able to provide more accurate error messages for import statements.

I think this is the issue here.So how can I solve it? When I remove the `declarations.d.ts` than above errors are coming.If I add it then no issues (I have to remove the ` "allowJs": true` too).Any solution, please.

**src\assets\load.ts**

```
  import * as NProgress from '../../../node_modules/nprogress/nprogress.js'
    (() => {
      NProgress.start();
    })()
```

**Comment by ikatyang** [comment]
I think you have to use absolute path for importing to tell TS that `nprogress.js` is a external module so that it does not need to be compiled.

```ts
import * as NProgress from 'nprogress/nprogress.js'
(() => {
  NProgress.start();
})()
```

---

Or if it is considered an internal module, you might need to use [`--outDir`](http://www.typescriptlang.org/docs/handbook/compiler-options.html) option to redirect output files, since TS will generate compiled `*.js` file next to the source files (_*.ts_, and _*.js with allowJs_) if there is no redirecting, thus `allowjs` will cause overwriting ( `*.js` -> `*.js` ).

**Comment by Sampath-Lokuge** [comment]
Hmm.. Thanks a lot for the info.I have found another workaround too:[Stackoverflow](https://stackoverflow.com/questions/44457138/typescript-error-would-overwrite-input-file)
