### ISSUE TITLE
Language Service For Dynamic Import

### ISSUE THREAD

**Issue by yuit** [Microsoft/TypeScript#16402]
- [x] go-to-definition on string literal module name (#16383)
- [x] find all reference on string literal module name
- [x] go-to-definition on imported property
- [x]  find all ref on imported property
- [x]  rename on imported property

**Comment by donaldpipowitch** [comment]
> go-to-definition on imported property

Taking [this example](https://github.com/Nitive/typescript-dynamic-import) it looks like go-to-definition for `sum` only works on [line 3](https://github.com/Nitive/typescript-dynamic-import/blob/master/src/index.ts#L3), but not [line 2](https://github.com/Nitive/typescript-dynamic-import/blob/master/src/index.ts#L2) (with current insiders build).

Is this a bug or expected?
