### ISSUE TITLE
Type should be simplified for quickInfo

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#16404]
**TypeScript Version:**  nightly (2.4.0-dev.20170609)

**Code**

```ts
/// <reference path="fourslash.ts" />
////interface I { x: string | number; }
////declare const i: I & { x: number };
////i./**/x;

verify.quickInfoAt("", "(property) x: number");
```

**Expected behavior:**

Test succeeds.

**Actual behavior:**

Shows `(property) x: number | (string & number)`.

**Comment by mhegazy** [comment]
not sure what you mean by "simplified". that s the type of `x`.

**Comment by andy-ms** [comment]
When we intersect `{ x: number }` with `{ x: string | number }`, can't we simplify it to just `{ x: number }`?

**Comment by mhegazy** [comment]
nope... it is not just a number, it is `number & (string | number)` which then distributes to `(number & string) | (number & number)` which is `(number & string) | number`.

it is true that `number & string` is an empty set, but we have no special treatment for these in intersection type. 
you could argue that the compiler should reduce types that are guaranteed to have no values to `never`, but that would break cases like tagged types (e.g. `string & {tag: any}`). we do use that for instance see `Path` in src\compiler\types.ts

**Comment by jcalz** [comment]
@mhegazy Even if `(number & string)` weren't empty, `number & (string | number)` should still reduce to `number` by absorption (see coincidentally recent #16386).

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
