### ISSUE TITLE
FilePropertyBag should extends BlobPropertyBag according to the standard

### ISSUE THREAD

**Issue by lygstate** [Microsoft/TypeScript#16400]
The reference URL 
https://w3c.github.io/FileAPI/#idl-index
**TypeScript Version:**  2.2.1 / nightly (2.2.0-dev.201xxxxx)

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by tudorgergely** [comment]
Fixed this issue here: https://github.com/Microsoft/TSJS-lib-generator/pull/265
