### ISSUE TITLE
Number check functions such as `isNaN` shouldn't constrain their parameter type

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#16427]
**TypeScript Version:**  master

**Code**

```ts
isNaN(<any>null); // should be able to pass any value without type casting
```

**Expected behavior:**

```ts
declare function isNaN(target: any): boolean;
```

**Actual behavior:**

```ts
declare function isNaN(number: number): boolean;
```

**Comment by andy-ms** [comment]
While code like `Number.isNaN("foo")` technically won't crash, it won't accomplish anything either.
We also errors for `new Set<string>().has(0);` and `/rgx/.test(0);`.

**Comment by falsandtru** [comment]
For example, when we write compare function also working with `NaN`, we need the exact function detecting `NaN`.

```ts
var a: number | string = '';
[''].findIndex(b => a === b || Number.isNaN(a) && Number.isNaN(b));
```

I believe this code should be accepted.

**Comment by falsandtru** [comment]
Sorry, I found global `isNaN` also constrains the parameter type. So I fix the code to:

```ts
var a: number | string = '';
[''].findIndex(b => a === b || isNaN(a) && isNaN(b));
```

**Comment by DanielRosenwasser** [comment]
https://github.com/Microsoft/TypeScript/issues/4002

https://github.com/Microsoft/TypeScript/issues/15173#issuecomment-293915634

**Comment by falsandtru** [comment]
I searched it but probably I had some typo. Thanks.

**Comment by DanielRosenwasser** [comment]
No worries! Sorry if that came off the wrong way, didn't mean to be abrasive.
