### ISSUE TITLE
Comments on namespace name paths pollute the base/root namespace

### ISSUE THREAD

**Issue by rjamesnw** [microsoft/TypeScript#16428]
The code should be self-explanatory.  If I add a comment to the base/root namespace, then add a comment for a nested namespace, the base/root namespace contains all comments. 

```
/** Comment for A */
module A {
    export var a = 1;
}

/** Comment for B */
module A.B {
    export var b = 1;
}

// 'A' help now shows "Comment for A Comment for B"
```
(https://goo.gl/1mSo6J)

This behavior is NOT consistent if module B above is nested in a different way:
```
module A {
 /** Comment for B */
 export module B {
    export var b = 1;
 }
}
```
The first one should really behave the same as the last code above. I certainly hope this isn't by design (would be a bad one I'd think).  If there's an existing issue, I could not find it, sorry.

**Comment by namansancheti** [comment]
Hi @mhegazy,
I would like to work on this. Could you please guide as to how the above bug can be fixed ?
Thanks.

**Comment by rjamesnw** [comment]
If your asking me, I have no idea how to program the fix. I only know that if a namespace "a.b.c" has a jsdoc comment, then 'a' AND 'b' get it also which is NOT correct. It should only apply to the LAST name in that dot notation.

**Comment by RyanCavanaugh** [comment]
Duplicate [#13855](https://github.com/microsoft/TypeScript/issues/13855)
