### ISSUE TITLE
Compiler not detecting invalid properties on type when using spread operator in tsx

### ISSUE THREAD

**Issue by RyanThomas73** [Microsoft/TypeScript#16429]
**TypeScript Version:**  2.3.4

**Code**

```
interface FooProps {
   name: string;
}

class FooComponent extends React.Component<FooProps, void> {
    public render() {
        return (<Text>{this.props.name}</Text>)
    }
}

interface BarProps {
}

class BarComponent extends React.Component<BarProps, void> {
    public render() {
        const fooProps = { name: 'Bob McBobberson', age: 15 };

        return (
            <FooComponent {...fooProps} />
        )
    }
}
```

**Expected behavior:**
Error:  Property age does not exist on type `FooProps`

**Actual behavior:**
No error

I only see the incorrect behavior when the extra properties are being applied via a {...something} spread operator. If I attempt to put an `age={..}` property directly on the component tag then I get the expected error output.

I see the incorrect behavior in both **Typescript Version:** 2.3.3 and 2.3.4

If I downgrade to 2.3.2, I see the expected error.

**Comment by RyanCavanaugh** [comment]
This is intended to be allowed. See #15463 for lots of complaining when it didn't :wink:.
