### ISSUE TITLE
Unexpected strict mode reserved word  at createScript

### ISSUE THREAD

**Issue by Viipiin** [Microsoft/TypeScript#16431]
Hello ,
When I'm running my typescript file using node file.ts
it is showing unexpected error.
 Unexpected token : in one file when I'm using 
let burger: string = "McD";
and in other file it is showing Unexpected strict mode reserved word  at createScript when I'm running the below code:
class program {
    constructor(private msg: string) {

    }
error:

constructor(private msg: string) {
                ^^^^^^^
SyntaxError: Unexpected strict mode reserved word
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
Don't know why but was working fine previously now it is showing error.
I'm using node ,npm,typescript latest versions and VS Code.

Please need some help.

**Comment by ikatyang** [comment]
`*.ts` file cannot be executed directly via node.

You have to:

- compile it into `*.js` file, then execute it via node. e.g. `tsc file.ts && node file.js`
- or using [ts-node](https://github.com/TypeStrong/ts-node) to execute. e.g. `ts-node file.ts`

**Comment by Viipiin** [comment]
Hey just correct yourself ...I found the solution.
you can run *.ts file in node command and *.js files on browsers.
Simply remove extension while running *.ts file using cmd like..
>node tsc a
>node a
and everything will work smoothly..
Happy TS...
