### ISSUE TITLE
Allow for declarations of JS modules imported by path

### ISSUE THREAD

**Issue by justinfagnani** [microsoft/TypeScript#16437]
When importing third party modules by path, I lose the ability to provide declarations for them because they no longer have a name.

Example:

`incremental-dom` @ master now loads in browsers that support ES6 modules. I check it out into a third_party folder and import as a module:

`src/foo.js`:
```js
import * as idom from '../third_party/incremental-dom/index.js';
```

The typings as available via DefinitelyTyped, but declarare the module 'incremental-dom'. There's no way to tell tsc that the module at third_party/incremental-dom _is_ `incremental-dom`.

Even if incremental-dom had already released a ES6 module compatible version to npm, the import of:

`src/foo.js`:
```js
import * as idom from '../../incremental-dom/index.js';
```

wouldn't be associated with the module identified by the 'incremental-dom' name.

I wonder if there could be some mapping from names to paths that would let existing name-based types declarations work standard path-based imports?

**Comment by DanielRosenwasser** [comment]
So technically, you can get around this with the following `../third_party/incremental-dom/index.d.ts`:

```ts
export * from "incremental-dom";
```

But I don't think that quite gets to the root of the problem.

**Comment by mhegazy** [comment]
would supporting some sort of project root indicator be sufficient?

i.e. `import * as idom from '/thirdt_party/incremental-dom/index.js';` where `/` refers to a "project root".

**Comment by RyanCavanaugh** [comment]
Closing due to lack of additional feedback
