### ISSUE TITLE
how defined symbol class property?

### ISSUE THREAD

**Issue by liangzeng** [Microsoft/TypeScript#16432]
**TypeScript Version:**  2.3.4 

**Code**

```ts

const key = Symbol.for("key");

class C{
     [key]:number = 1;  // error!  A computed property name in a class property declaration must directly refer to a built-in symbol.
}

```

**Comment by DanielRosenwasser** [comment]
See #15473 for progress on making this potentially work.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
