### ISSUE TITLE
variable renaming should take into account ES6 property value shorthand

### ISSUE THREAD

**Issue by nippur72** [Microsoft/TypeScript#16435]
Renaming from the IDE is not safe if the renamed variable is used to initialize an object with the ES6 property value shorthand syntax. 

Example:
```ts
interface IFoo {
   foo: string
}
const foo = "hello";   // <- rename foo into foo1
const bar: IFoo = { foo };
```
if on the IDE I rename `foo` into `foo1` (at line 4), then the code will break because `bar` now has a property named `foo1` which does not exist in its interface:
```ts
const bar: IFoo = { foo1 };
```
Ideally the IDE should be smart enough and modify the code in:
```ts
const bar: IFoo = { foo: foo1 };
```

**Comment by ikatyang** [comment]
I think https://github.com/Microsoft/TypeScript/issues/15787 should cover this issue.

**Comment by nippur72** [comment]
@ikatyang yes, and it also covers the opposite case of destructuring from an object, so I'm closing this.
