### ISSUE TITLE
Using Readonly<Class> makes a type incompatible only if there are private fields

### ISSUE THREAD

**Issue by sceutre** [Microsoft/TypeScript#16441]
**TypeScript Version:**  2.3.2

**Code**

```ts
class A { public x:number; }
class B { private x:number; }

let a:A = new A as Readonly<A>; // succeeds
let b:B = new B as Readonly<B>; // type error: Property x is missing in Readonly<B>

class AA { private x:number; }
class BB extends AA {}

let bb:BB = new BB as Readonly<BB>; // type error: Property x is missing in Readonly<BB>
```

**Expected behavior:**

To me it appears B and its Readonly are the same (since there are no external visible properties) while A and its Readonly differ in the mutability in x.  Although I also think it would be fine if all assignments worked.

I actually noticed this with the case of BB and it being a private field in the super class that caused the assignment to fail.

**Actual behavior:**

As per code comments

**Comment by mhegazy** [comment]
mapped types, which `Readonly` is one, only operate on public fields of a type.

**Comment by sceutre** [comment]
Ah ok, I was thinking (not very deeply) that the issue was more that the type of a class should similarly only include its public members.

**Comment by evmar** [comment]
Idea: one thing that would maybe solve this and some related issues is something like Interface<T> that is "T" with only public fields.

That would mean that
  let x: Interface<T> = T
would always be legal, and other things could implement Interface<T>.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
