### ISSUE TITLE
Potential bug - d.ts file does not match .ts file

### ISSUE THREAD

**Issue by ORESoftware** [Microsoft/TypeScript#16442]
BUGS: Please use this template.

**TypeScript Version:**  2.2.2

You will notice that the following .d.ts file:
https://github.com/sumanjs/suman-utils/blob/master/lib/index.d.ts

does not reflect its counterpart:
https://github.com/sumanjs/suman-utils/blob/master/lib/index.ts

Namely we see on line 44 of all.ts:
https://github.com/sumanjs/suman-utils/blob/master/lib/index.ts#L44

that this default export is not reflected in the all.d.ts file

**Expected behavior:**

We would expect the default export to be reflected in the all.d.ts file

**Actual behavior:**

We are not seeing the default export reflected in the all.d.ts file.

I believe this is a bug. In the meantime, I will try to upgrade my tsc versions. I am using tsc -w to transpile.

Thank you.

**Comment by DanielRosenwasser** [comment]
In the meantime, try something like

```ts
const tempExports = module.exports;
export default tempExports;
```

**Comment by ORESoftware** [comment]
that appears to solve the problem, not the most elegant but works for now

**Comment by mhegazy** [comment]
@ORESoftware can you repost the links, i can not find the sources in the OP any longer.

**Comment by ORESoftware** [comment]
@mhegazy np, I renamed the file from all.ts to index.ts:
https://github.com/sumanjs/suman-utils/blob/master/lib/index.ts

**Comment by mhegazy** [comment]
So what was the issue again?

**Comment by ORESoftware** [comment]
np, the original issue was that if you did this

```ts
// index.ts
export default module.exports;
```
then in the index.d.ts file, nothing would be there for default exports

but if you change the index.ts file to this

```ts
// index.ts
const tempExports = module.exports;
export default tempExports;
```

then the index.d.ts file has a default export reflected:

```.d.ts
declare let tempExports: any;
export default tempExports;
```

unfortunately it's `any`, but maybe one day TS can type module.exports

**Comment by mhegazy** [comment]
Here is what i am seeing on latest:

```sh
C:\test\21544>type a.ts
/// <reference types="node" />

///////////// support node style imports ////////////////////////////////////////////////

export default module.exports;

//////////////////////////////////////////////////////////////////////////////////////////

C:\test\21544>tsc --v
Version 2.8.0-dev.20180131

C:\test\21544>tsc a.ts --d

C:\test\21544>type a.d.ts
declare const _default: any;
export default _default;
```

**Comment by ORESoftware** [comment]
yeah if it's `any` then the new version isn't much more functional than the old, but we can close the issue...is there any potential progress on typing module.exports?

**Comment by mhegazy** [comment]
`moduel.exports` is coming from `@types/node.d.ts` which is defined as `any`. the compiler does not do anything special here.

**Comment by ORESoftware** [comment]
yeah I'd love to be able to type `module.exports`, this is what I think works for me atm:

```typescript
export interface ISumanExports {
  s: typeof s,
  init: IInitFn,
  run: ISumanRunFn,
  autoPass: typeof autoPass,
  autoFail: typeof autoFail
}

const $exports = module.exports;
export default $exports as  ISumanExports;
```
