### ISSUE TITLE
Thrown "error TS4022: 'extends' clause of exported interface '...' has or is using private name ..." with --declaration flag and mixing imported export name with equal export interface name

### ISSUE THREAD

**Issue by Manusan42** [Microsoft/TypeScript#16440]
**TypeScript Version:** 2.3.4 and nightly (2.4.0-dev.20170610)

Trying to build up a hierarchical namespace structure with modules. 
All seems fine till setting --declaration flag to true.

**Code**

`index.ts`
```ts
import * as Service from './Service';

class MySuccessMessage implements Service.Response.Message {
  public type = 'successMessage'
}

class MyResponse implements Service.Response {
  public message: MySuccessMessage = new MySuccessMessage();
}

class MyTypedResponse implements Service.TypedResponse {
  public type = 'successResponse';
  public message: MySuccessMessage = new MySuccessMessage();
}

console.log((new MyResponse()).message.type);
console.log((new MyTypedResponse()).type);
```

`Service.ts`
```ts
import * as Response from './Response';
export { Response };

export interface Response {
  message: Response.Message;
}

export interface TypedResponse extends Response {
  type: string;
  message: Response.Message;
}
```

`Response.ts`
```ts
export interface Message {
  key?: string;
  type: string;
}
```
Compiling with:
```json
{
  "compilerOptions": {
    "baseUrl": "",
    "outDir": "../dist/app",
    "target": "es2015",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "declaration": true
  }
}

```

**Expected behavior:**
No errors while compiling and printing out:
```
successMessage
successResponse
```
just like it does without setting `--declaration` to true or by removing the `extends Response ` from `export interface TypedResponse extends Response`.

**Actual behavior:**
Getting error:
```
src/Service.ts(8,40): error TS4022: 'extends' clause of exported interface 'TypedResponse' has or is using private name 'Response'.
```

sample project with code from above:
[export-error-test.zip](https://github.com/Microsoft/TypeScript/files/1066191/export-error-test.zip)

**Comment by Manusan42** [comment]
Any suggestions yet? I really need this for my project and would appreciate any tips to overcome this problem. Is this a bug or have I just forgotten something?

**Comment by DanielRosenwasser** [comment]
Can you try changing `import * as Response from './Response';` to `import * as R from './Response';` and seeing if that changes things?

In other words, rename `Response` to `R`

**Comment by Manusan42** [comment]
Thanks you for quick response but if you mean this:
```ts
import * as R from './Response';
export { R as Response };

export interface Response {
  message: R.Message;
}

export interface TypedResponse extends Response {
  type: string;
  message: R.Message;
}
```
sadly not resolves the problem.

If you meant this:
```ts
import * as R from './Response';
export { R };

export interface Response {
  message: R.Message;
}

export interface TypedResponse extends Response {
  type: string;
  message: R.Message;
}
```
and using it that way:
```ts
import * as Service from './Service';
class MySuccessMessage implements Service.R.Message ...
class MyResponse implements Service.Response ...
...
```
bypasses the problem but thats the whole point here, that I try to merge the reexported "Response"-module-namespace with the equal named interface to get a nice hierarchical structure which I can use like this:
```ts
import * as Service from './Service';
class MySuccessMessage implements Service.Response.Message ...
class MyResponse implements Service.Response ...
```

**Comment by Manusan42** [comment]
Ok, till this (hopefully) gets done, my workaround is to not generate the declarations and instead pointing the typings to source in my package.json:
```json
...
  "main": "dist/app/index.js",
  "typings": "src/index",
...
```
Because it's a private module, I'm publishing the source anyways, so it seems totally fine for now.

**Comment by mhegazy** [comment]
the interface `Response` does not really merge the way you expect. if you want to augment the module you should instead do something like:
```ts
import * as Response from './Response';
export { Response };

declare module  './Response' {
     interface Response {
         message: Response.Message;
    }
}

export interface TypedResponse extends Response.Response {
    type: string;
    message: Response.Message;
}
```

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Comment by Manusan42** [comment]
Sorry I'm really busy at the moment and had no time to test the solution. Anyways, thanks for the response. The solution looks ugly but makes sense.
