### ISSUE TITLE
Unarrayify a type

### ISSUE THREAD

**Issue by Gregroam** [Microsoft/TypeScript#16449]
With the new types such as Pick, Partial etc, could we possibly introduce the idea of a type to Dearray an array? A use case I need it for. I define my DB tables, and use a script to generate an interface an object of field names that matches to their string literal.
From that, I want to specify an array of allowed updatable fields, then create a sub interface from that array using Pick.

```ts
var UserFields = {
    firstName: <"firstName">"firstName",
    lastName: <"lastName">"lastName",
    password: <"password">"password"
}; //This is generated by script

interface IUserFields {
    firstName: string;
    lastName: string;
    password: string;
}; //This is generated by script

var changeableFields = [UserFields.firstName, UserFields.lastName] //Type is ("firstName" | "lastName")[];

//Now I want to de-arrayify this type so I can use it in a Pick
//Something like this
type IUpdateableFields = Pick<IUserFields, Dearray<typeof changeableFields>>; //Type is {firstName: string; lastName: string}
```

**Comment by DanielRosenwasser** [comment]
You can use an indexed access type (aka lookup type) with `number` on the type of `changeableFields`:

```ts
var UserFields = {
    firstName: <"firstName">"firstName",
    lastName: <"lastName">"lastName",
    password: <"password">"password"
};

interface IUserFields {
    firstName: string;
    lastName: string;
    password: string;
};

var changeableFields = [UserFields.firstName, UserFields.lastName] //Type is ("firstName" | "lastName")[];

// This has type { firstName: string; lastName: string; }
type IUpdateableFields = Pick<IUserFields, (typeof changeableFields)[number]>;
```

[See it in action here](https://www.typescriptlang.org/play/#src=var%20UserFields%20%3D%20%7B%0D%0A%20%20%20%20firstName%3A%20%3C%22firstName%22%3E%22firstName%22%2C%0D%0A%20%20%20%20lastName%3A%20%3C%22lastName%22%3E%22lastName%22%2C%0D%0A%20%20%20%20password%3A%20%3C%22password%22%3E%22password%22%0D%0A%7D%3B%20%2F%2FThis%20is%20generated%20by%20script%0D%0A%0D%0Ainterface%20IUserFields%20%7B%0D%0A%20%20%20%20firstName%3A%20string%3B%0D%0A%20%20%20%20lastName%3A%20string%3B%0D%0A%20%20%20%20password%3A%20string%3B%0D%0A%7D%3B%20%2F%2FThis%20is%20generated%20by%20script%0D%0A%0D%0Avar%20changeableFields%20%3D%20%5BUserFields.firstName%2C%20UserFields.lastName%5D%20%2F%2FType%20is%20(%22firstName%22%20%7C%20%22lastName%22)%5B%5D%3B%0D%0A%0D%0A%2F%2FNow%20I%20want%20to%20de-arrayify%20this%20type%20so%20I%20can%20use%20it%20in%20a%20Pick%0D%0A%2F%2FSomething%20like%20this%0D%0Atype%20IUpdateableFields%20%3D%20Pick%3CIUserFields%2C%20(typeof%20changeableFields)%5Bnumber%5D%3E%3B).

**Comment by Gregroam** [comment]
Oh wow I totally didn't realise that. Thank you!

**Comment by DanielRosenwasser** [comment]
No worries, you're welcome!

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
