### ISSUE TITLE
[Question] Should removeEventListener in Window interface be similar to addEventListener?

### ISSUE THREAD

**Issue by yuit** [Microsoft/TypeScript#16447]
Like [this](https://github.com/Microsoft/TypeScript/blob/master/src/lib/dom.generated.d.ts#L13297) 

```ts
    removeEventListener<K extends keyof WindowEventMap>(type: K, listener: (this: Window, ev: WindowEventMap[K]) => any, useCapture?: boolean): void;
    removeEventListener(type: string, listener: EventListenerOrEventListenerObject, useCapture?: boolean): void;    
```

**Comment by mhegazy** [comment]
The sample in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17119/files#diff-3eedac065f66664c918123a09e849240R5 is rather useless. why would you call removeEventListener and pass in a new function. 

form https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/removeEventListener (emphasis mine)
>The EventTarget.removeEventListener() method removes from the EventTarget an event listener **previously registered with `EventTarget.addEventListener()`**. The event listener to be removed is identified using a combination of the event type, the event listener function itself, and various optional options that may affect the matching process; see Matching event listeners for removal.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
