### ISSUE TITLE
colorize of 'number' fails if open brace is not on the same line

### ISSUE THREAD

**Issue by nippur72** [Microsoft/TypeScript#16443]
a small glitch: when declaring an interface, if the open brace is not on the same line of the declaring member then `number` (or any other fundamental type) is colorized incorrectly:

![screen](https://user-images.githubusercontent.com/2598443/27010079-aac83628-4e9c-11e7-876d-b86c0d2520e0.png)

**Comment by ikatyang** [comment]
I think this kind of issue should be tracked in [Microsoft/TypeScript-TmLanguage](https://github.com/Microsoft/TypeScript-TmLanguage/issues).

**Comment by nippur72** [comment]
ok, thanks, closing here and reopening as https://github.com/Microsoft/TypeScript-TmLanguage/issues/472
