### ISSUE TITLE
Suggestion: Add support for dispose pattern

### ISSUE THREAD

**Issue by sheiidan** [Microsoft/TypeScript#16459]
This suggestion propose adding support for the good known and familiar Dispose pattern (e.g. 'using' statement like we have in C#).
Since there's no class destructor in ts/js there's a need for a resource management (or cleanup) pattern in order to do smart/auto handling for releasing resources and cleanup our code. 
This TS with USING statement:
```ts
export class MyDisposable {
    public dispose() {

    }
}

using(let x = new MyDisposable()) {
    console.log("Hi");
}
```

should be transpiled into:
```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var MyDisposable = (function () {
    function MyDisposable() {
    }
    MyDisposable.prototype.dispose = function () {
    };
    return MyDisposable;
}());
exports.MyDisposable = MyDisposable;
var x;
try {
    x = new MyDisposable();
    console.log("Hi");
}
finally {
    if (typeof x !== "undefined") x.dispose();
}
```

**Comment by DanielRosenwasser** [comment]
Hi @sheiidan, this really isn't something in the scope of our project - specifically, TypeScript's direction is to overlay types on top of JavaScript moreso than to add any new runtime syntax that isn't part of the ECMAScript standards track.

While I'm sure there might be people who would get good use from this feature, this isn't something we're looking to take at this time. I know you put work into the pull request at #16460, so I hope that doesn't discourage you from contributing to the project in others ways. Definitely keep an eye out for issues marked as `Accepting PRs`.

**Comment by sheiidan** [comment]
@DanielRosenwasser thank you for the quick response.
Too bad that Typecript direction is too tight to ECMAScript syntax. With this direction you restrict yourself from all the great patterns we have out there.
for example, what's your opinion about Null-conditional Operators (a?.b?.c) ? is this should be part of TS? if this is the direction you're not going to implement this important operator (and for example, this operator is already implemented in Angular2 compiler instead to be implemented in TS compiler).
What about other patterns, such as LINQ ? I really hope to see these patterns in TS sometime in the future

**Comment by RyanCavanaugh** [comment]
@sheiidan I recommend searching the issue tracker; these have all been discussed at great length.
