### ISSUE TITLE
typescript.d.ts and typescriptServices.d.ts generate compile errors

### ISSUE THREAD

**Issue by rufio620** [Microsoft/TypeScript#1645]
I am trying to use the typescriptServices.js file to build some compilation tools around typescript. However when I include the typescript.d.ts or typescriptServices.d.ts, tsc generates several errors. I'm not sure if I am doing something wrong or if something is wrong with the definition files generated by the latest typescript build.

--GetAutoCompleteEntries.ts
/// <reference path="node.d.ts" />
/// <reference path="typescript.d.ts" />

import ts = require("typescript");

export function compile(filenames: string[], options: ts.CompilerOptions): void {
    var host = ts.createCompilerHost(options);
    var program = ts.createProgram(filenames, options, host);
    var checker = ts.createTypeChecker(program, /*produceDiagnostics*/ true);
    var result = checker.emitFiles();

    var allDiagnostics = program.getDiagnostics()
        .concat(checker.getDiagnostics())
        .concat(result.diagnostics);

    allDiagnostics.forEach(diagnostic => {
        var lineChar = diagnostic.file.getLineAndCharacterFromPosition(diagnostic.start);
        console.log('${diagnostic.file.filename } (${lineChar.line },${lineChar.character }): ${diagnostic.messageText}');
    });

    console.log('Process exited with code \'${result.emitResultStatus}\'.');
}

compile(process.argv.slice(2), {
    noImplicitAny: true, noEmitOnError: true,
    target: ts.ScriptTarget.ES5, module: ts.ModuleKind.CommonJS
});

--Build Output

C:\Users\Greg\Documents\GitHub\ace-builds\demo\TypeScriptAutoComplete [master +3 ~0 -0 !]> tsc .\GetAutoCompleteEntries.ts --module "commonjs"
typescript.d.ts(24,5): error TS1128: Declaration or statement expected.
typescript.d.ts(259,5): error TS1128: Declaration or statement expected.
typescript.d.ts(276,5): error TS1128: Declaration or statement expected.
typescript.d.ts(311,10): error TS1005: ';' expected.
typescript.d.ts(311,10): error TS1036: Statements are not allowed in ambient contexts.
typescript.d.ts(312,10): error TS1005: ';' expected.
typescript.d.ts(312,10): error TS1036: Statements are not allowed in ambient contexts.
typescript.d.ts(332,26): error TS1005: ';' expected.
typescript.d.ts(341,26): error TS1005: ';' expected.
typescript.d.ts(349,26): error TS1005: ';' expected.
typescript.d.ts(394,22): error TS1005: ';' expected.
typescript.d.ts(495,21): error TS1005: ';' expected.
typescript.d.ts(541,37): error TS1005: ';' expected.
typescript.d.ts(543,10): error TS1005: ';' expected.
typescript.d.ts(543,10): error TS1036: Statements are not allowed in ambient contexts.
typescript.d.ts(575,47): error TS1005: ';' expected.
typescript.d.ts(580,46): error TS1005: ';' expected.
typescript.d.ts(604,10): error TS1005: ';' expected.
typescript.d.ts(604,10): error TS1036: Statements are not allowed in ambient contexts.
typescript.d.ts(657,26): error TS1005: ';' expected.
typescript.d.ts(658,27): error TS1005: ';' expected.
typescript.d.ts(665,37): error TS1005: ';' expected.
typescript.d.ts(789,62): error TS1005: ',' expected.
typescript.d.ts(817,5): error TS1128: Declaration or statement expected.
typescript.d.ts(827,5): error TS1128: Declaration or statement expected.
typescript.d.ts(832,5): error TS1128: Declaration or statement expected.
typescript.d.ts(847,62): error TS1005: ',' expected.
typescript.d.ts(857,65): error TS1005: ',' expected.
typescript.d.ts(861,57): error TS1005: ',' expected.
typescript.d.ts(864,5): error TS1128: Declaration or statement expected.
typescript.d.ts(956,5): error TS1128: Declaration or statement expected.
typescript.d.ts(979,5): error TS1128: Declaration or statement expected.
typescript.d.ts(1053,5): error TS1128: Declaration or statement expected.
typescript.d.ts(1071,5): error TS1128: Declaration or statement expected.
typescript.d.ts(1146,34): error TS1005: ';' expected.
typescript.d.ts(1146,36): error TS1036: Statements are not allowed in ambient contexts.
typescript.d.ts(1146,36): error TS1131: Property or signature expected.
typescript.d.ts(1148,5): error TS1128: Declaration or statement expected.
typescript.d.ts(1148,11): error TS1046: A 'declare' modifier is required for a top level declaration in a .d.ts file.
typescript.d.ts(1157,5): error TS1128: Declaration or statement expected.
typescript.d.ts(1157,11): error TS1046: A 'declare' modifier is required for a top level declaration in a .d.ts file.
typescript.d.ts(1170,22): error TS1005: ';' expected.
typescript.d.ts(1170,35): error TS1005: '(' expected.
typescript.d.ts(1176,5): error TS1128: Declaration or statement expected.
typescript.d.ts(1176,11): error TS1046: A 'declare' modifier is required for a top level declaration in a .d.ts file.
typescript.d.ts(1322,1): error TS1128: Declaration or statement expected.
typescript.d.ts(1691,5): error TS1128: Declaration or statement expected.
typescript.d.ts(1701,5): error TS1128: Declaration or statement expected.

**Comment by DanielRosenwasser** [comment]
What version of TypeScript are you using?

**Comment by danquirk** [comment]
typescript.d.ts has a const enum on line 24. You'll need to upgrade to a newer version of the compiler to compile that file, we haven't done a public release with const enum support but there'll be one relatively soon. Alternatively you could remove the 'const' part of the enums as a workaround for now.

**Comment by rufio620** [comment]
Just realized the path to my compiler was pointing at 1.3. However the npm packages do not seem to include the typescriptServices.d.ts and typescript.d.ts definition files. Is there any way to get these files other than building from sources?

**Comment by danquirk** [comment]
Not at the moment since we haven't published 1.4 to npm yet. We should try to avoid doing this in the future (putting unreleased features into files like this).
