### ISSUE TITLE
Refine unions in contextual typing

### ISSUE THREAD

**Issue by RyanCavanaugh** [Microsoft/TypeScript#16457]
Source issue #16450 and others (TODO: find them)

This code should work, but doesn't:
```ts
interface X {
    type: 'x';
    value: string;
}

interface Y {
    type: 'y';
    value: 'none' | 'done';
}

function foo(bar: X | Y) { }

foo({
    type: 'y',
    value: 'done',
});
```

Similar example:
```ts
interface X {
    type1: 'x';
    value: string;
}

interface Y {
    type2: 'y';
    value: 'none' | 'done';
}

function foo(bar: X | Y) { }

foo({
    type2: 'y',
    value: 'done',
});
```

We can, in principle, make this work by discarding `X` from the union.

In the first example, this can be done (somehow) by using the discriminating union from the object literal.

In the second example, this can be done by noting that we have a fresh object literal type (meaning there are known to be no additional properties) and a missing `type1` property.

**Comment by timwangdev** [comment]
+1
Looking forward to see any progress on this!

**Comment by jebcat1982** [comment]
Microsoft has the current version at typescript.com

**Comment by LeandritGo** [comment]
A solution to this would be welcomed

**Comment by mhegazy** [comment]
seems to be the same underlying issue as https://github.com/Microsoft/TypeScript/issues/18365

**Comment by sandersn** [comment]
I have a fix for the first example, but note that the first example won't magically work because `value` *looks* like a discriminant too, albeit not a useful one. This fails with current narrowing as well:

```ts
function f(xy: X | Y) {
  if (xy.value === 'done') {
    // xy: X | Y
  }
  else {
    // xy: X | Y
  }
}
```

That's because, as a discriminant, `string | 'none' | 'done'` boils down to just `string`.

**Comment by mhegazy** [comment]
Another alternative here is to always maintain the literal type if the contextual type is its base type. i.e. give `value` the type `"done"` even thought the contextual type is `string`.

**Comment by sandersn** [comment]
I think #19587 will fix this.

**Comment by mifopen** [comment]
Should this code work after fix?
```ts
interface Control {
    CurrentMode: "View" | "Edit";
}

let controls: Control[];
let controlsToEdit: Control[] = controls.map(c => c
    ? { CurrentMode: "Edit" }
    : c);
```
For now (ts 2.8.3) I get `Type 'string' is not assignable to type '"View" | "Edit"'`
