### ISSUE TITLE
[QUESTION] i need generic, result of execution function -> generic for T[K]

### ISSUE THREAD

**Issue by qwabra** [Microsoft/TypeScript#16462]
**TypeScript Version:**  2.3.4
**Code Version:** 1.13.0

question on [stackoverflow](https://stackoverflow.com/questions/44486818/typescript-generic-for-getting-type-of-function-result-number)

**function**
```ts
	//function:
	function Obj<T>(gen: T) {// gen - Object with functions
		return {
			data: <{[Key in keyof T]: /*-->-*/T[Key]/*-<--*/   }>{},// i need generic, result of execution function -> T[Key]
			gen,
		}
	}
```

**example**
```ts
	//example:
	let obj = Obj({
		foo(): number { return; },
		qwa(): string { return; },
		div(text: string) {
			let div = document.createElement('div');
			div.innerHTML = text
			obj.data.div = div
			return div//typeof HTMLDivElement
		},
		list(arr: Array<string>) {
			let ul = document.createElement('ul')
			arr.forEach(str => {
				let li = document.createElement('li')
				li.innerHTML = str
				ul.appendChild(li)
			})
			obj.data.list = ul
			return ul//typeof HTMLUListElement
		}
	})
```

**Expected behavior:**
```ts
/* //need:
	let obj: {
		data: {
			foo: number;            //-<--good
			qwa: string;            //-<--good
			div: HTMLDivElement;    //-<--good
			list: HTMLUListElement; //-<--good
		};
		gen: {
			foo(): number;
			qwa(): string;
			div(text: string): HTMLDivElement;
			list(arr: string[]): HTMLUListElement;
		};
	}
	 */
```

**Actual behavior:**
```ts
/* //result:
	let obj: {
		data: {
			foo: () => number;                         //-<--bad
			qwa: () => string;                         //-<--bad
			div: (text: string) => HTMLDivElement;     //-<--bad
			list: (arr: string[]) => HTMLUListElement; //-<--bad
		};
		gen: {
			foo(): number;
			qwa(): string;
			div(text: string): HTMLDivElement;
			list(arr: string[]): HTMLUListElement;
		};
	}
	 */
```

**thinks**
```ts
	//thinks:
	type qqw<R> = () => R;
	function ZcddF<Q>(foo: qqw<Q>): Q { return; }

	function foo(): number { return; }
	let aaaa = ZcddF(foo)// 4a is number
	
	function foo2(a,b,c): string { return; }
	let bbbb = ZcddF(foo2)// broken
```

**and finally**
where i can find syntax  dictionary/glossary for "generics" and "types"

for example  
 in Javascript  
var, let, for, if, ...

in typescript generics
in keyof, extends, extends keyof, ...

**Comment by RyanCavanaugh** [comment]
See #6606 and also read the issue template (search first, this is not a support forum, etc)

**Comment by RyanCavanaugh** [comment]
Right, unimplemented features don't exist yet

**Comment by qwabra** [comment]
pleas answer, a little bit more question

1. it can be in the future, and maybe i can subscribe to road map webpage?  
for expect or not this tricks

2. maybe i can read syntax dictionary/glossary page for "generics" and "types"

3. so, i understand that this question haven't easy way or can't be realised
without key patching tsconfig.json for dynamic calculate
```ts
let data = {}
data.num = 78
```
and it can did'n work 

4. oh, and finaly Q: where i can read docs page for tsconfig.json version: 2.0

__
this hope and regards
