### ISSUE TITLE
js intellisense issues about the custom export module.

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#16467]
_From @tsanie on June 12, 2017 12:40_

**Issues:**

The intellisense doesn't work when I import a constructor, but after I change the `module.exports` to an object, it seems right.

**Steps to Reproduce:**

1. Create a file named 'mod.js', write these lines.
```javascript
function Test(name) {
  this.name = name;
}
Test.prototype.log = function (msg) {};
module.exports = Test;
```
2. Create another file named 'test.js'.
```javascript
const Test = require('./mod');
let a = new Test('test');
a.    // <- here, the intellisense cannot list the 'name' and 'log'
```
3. Then change the files.

'mod.js'
```diff
-module.exports = Test;
+module.exports = { Test };
```
'test.js'
```diff
-let a = new Test('test');
+let a = new Test.Test('test');
a.    // now the intellisense seems good.
```

**Screen record**

![vsc](https://user-images.githubusercontent.com/980449/27034248-4fd014a2-4faf-11e7-8d69-c92400140366.gif)

_Copied from original issue: Microsoft/vscode#28517_

**Comment by mjbvz** [comment]
Tested with current TS 2.4-insiders. I believe the issue is that the type of `module.exports` in

```js
function Test(name) {
  this.name = name;
}
Test.prototype.log = function (msg) {}

module.exports = Test;
```

is a function with signature `(name: any) => void` instead of being identified as a class

**Comment by rbuckton** [comment]
Fixed, pending PR.
