### ISSUE TITLE
Can not find module of 3rd-party library when `module` is `esnext` in `tsconfig.json` for typescript 2.4.0

### ISSUE THREAD

**Issue by plantain-00** [Microsoft/TypeScript#16476]
**TypeScript Version:**  2.4.0

**Code**

```ts
import * as Vue from "vue";
console.log(Vue);
```

```json
{
    "compilerOptions": {
        "target": "es5",
        "module": "esnext"
    }
}
```

**Expected behavior:**

no error.

**Actual behavior:**

error TS2307: Cannot find module 'vue'.

**Reference 1 of js file with same source code:**

Result: works fine with webpack.

**Reference 2 of with same source code and this tsconfig.json:**

```json
{
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs"
    }
}
```

Result: no compilation error, and works fine with webpack.

**Comment by DanielRosenwasser** [comment]
Try setting `moduleResolution` to `node`.

**Comment by plantain-00** [comment]
Solved.
Maybe better document about this at here: https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Compiler%20Options.md

**Comment by RehanSaeed** [comment]
I've started getting the error wherever I try to import a `.vue` file: `TS2307: Cannot find module './components/app/app.vue'`. I'm trying to upgrade to using TypeScript 2.7.1.

#### tsconfig.json
```
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "lib": [
      "dom",
      "es2017"
    ],
    "module": "esnext",
    "moduleResolution": "node",
    "target": "es5",
    "sourceMap": true,
    "skipDefaultLibCheck": true,
    "strict": true,
    "types": [ "webpack-env" ]
  },
  "exclude": [
    "bin",
    "node_modules",
    "webpack.config.ts"
  ]
}
```
