### ISSUE TITLE
error: module has no exported member, even if the member is exported

### ISSUE THREAD

**Issue by mayacode** [Microsoft/TypeScript#16475]
**TypeScript Version:**  2.2.1

**Code**

```ts
import { formValueSelector } from 'redux-form/immutable';

```

**Expected behavior:**
Should work without problems, as `formValueSelector ` is exported in immutable: https://github.com/erikras/redux-form/blob/master/src/immutable.js#L21

**Actual behavior:**
Error:(6, 10) TS2305:Module ''redux-form/immutable'' has no exported member 'formValueSelector'.

**Comment by martindederer** [comment]
How did you resolve this issue? I'm getting the same error message with two different libraries (resul-ts, option-t). Either both are broken or the typescript compiler (version 2.7.1) has some kind of hiccup with exported types.
