### ISSUE TITLE
NPM module autocomplete (Mocha) turns on only after creating a jsconfig.json file

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#16470]
_From @stoberov on June 10, 2017 15:34_

Hey,

I've noticed some odd behavior whilst using **mocha** inside a React app. In fact, I've noticed this on other modules, too, but I'm providing the **mocha** example here.

Initially, some modules (mocha) do not provide any intellisense. It is only after creating an empty jsconfig.json file that intellisense is turned on. The opposite is also true - after deleting the empty jsconfig.json file, intellisense (for some modules, like **mocha**) is turned off.

I wonder if there is a bug lurking in VS Code responsible for this?

![](https://media.giphy.com/media/xUA7bfDDGF8ihd9LdS/giphy.gif)

- VSCode Version: Code 1.13.0
- OS Version: Windows_NT

_Copied from original issue: Microsoft/vscode#28426_

**Comment by mjbvz** [comment]
The root cause seems to be that for workspaces without a `jsconfig.json`, when you first open a js file, we create an implicit project that only contains that file. If the js file is a subdirectory of the workspace, we will not look at the node modules at the root of the workspace and therefore will not pick up mocha.

Creating the jsconfig creates an explicit project that will search the node modules and pick up mocha's typings

I'm not sure if the current behavior is correct or not. Mocha is kind of an odd case because of it's reliance on globals. Normally, I believe that ATA hides this issue in implicit projects

**Comment by mhegazy** [comment]
ATA infers that mocha is needed from looking at `package.json`. `jsconfig.json` makes it possible for ATA to find it, opening the file by itself is does not do the trick. 

We can address that by using "projectRootPath" in the "open" command and vscode would pass it along and ATA can use that to search. but if the user opens the file from a different folder we will be back to the same case. adding a jsconfig.json makes sure we have a consistent view of the world.
