### ISSUE TITLE
JSX for everything

### ISSUE THREAD

**Issue by pie6k** [Microsoft/TypeScript#16474]
JSX is great for defining parts of DOM tree eg `div`s etc. But it's also great for other things, like for example defining language grammar: https://github.com/laconalabs/elliptical for parsing library.

However:

1. how can I have multiple jsx factories in the same project (eg. I'm using react for most of the things, but I've got few files where I want to use jsx for something else)
    - My 'hack' for that is I import 'fake' `React` with `createElement` function into file scope that will be used instead like `import React from './fakeReact'` but it's not that elegant.
    - and, using custom factory this way, when my jsx factory returns some custom value, `ts` is complaining that my `component` (which is not actual component in this context) doent have `render` method: 
![image](https://user-images.githubusercontent.com/7311462/27068493-a983acb4-5010-11e7-87a3-af61fae74b21.png)

Right now I have 'feeling' that JSX of Typescript is strongly tied with DOM definitions and React while it's great for many other things too or even for such things like defining complex data structures as 'xml' matching some typescript interface?

**Comment by DanielRosenwasser** [comment]
> how can I have multiple jsx factories in the same project (eg. I'm using react for most of the things, but I've got few files where I want to use jsx for something else)

For the record, it looks like this is tracked by #15386, and I think some of the same points have been made there.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
