### ISSUE TITLE
No tests for jsconfig.json

### ISSUE THREAD

**Issue by andy-ms** [microsoft/TypeScript#16482]
The string `jsconfig` does not occur in any tests.

**Comment by DanielRosenwasser** [comment]
Feel free to triage this next time around. 😉

**Comment by weswigham** [comment]
Well. we could probably still use more, but we have 4 tests that use `jsconfig.json`s nowadays (all `fourslash`-based), all testing some jsconfig-specific scenarios, so generally good jsconfig-specific coverage. I'm going to close this issue unless someone has some specific tests they want written ❤️
