### ISSUE TITLE
Wrong behavior when translate Class to ES5

### ISSUE THREAD

**Issue by Jack-Works** [Microsoft/TypeScript#16480]
**TypeScript Version:**  2.3.4
**Code**

```ts
class N {
    q() {}
}
let x = new N().q.name
```

**Expected behavior:**
x should be "q"
**Actual behavior:**
x is ""

**Problem**
```js
var N = (function () {
    function N() {
    }
    N.prototype.q = function () { };
    //  ↑ should be N.proptotype.q = function q() {};
    return N;
}());
```

**Comment by RyanCavanaugh** [comment]
Duplicate #5611

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
