### ISSUE TITLE
JSDoc: function declarations are not type checked when exported

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/TypeScript#16487]
**TypeScript Version:**  2.3.4

**Code**

```js
/** @return {string} */
function reducer() {
  return 1;
}

export default reducer; // If this is commented out, the function above errors as expected.
```

**Expected behavior:**
The above program should error, regardless of whether the function is exported.

**Actual behavior:**
The above program only errors when the function is not exported.

**Comment by mhegazy** [comment]
Should be fixed in latest.
