### ISSUE TITLE
Locale must be of the form <language> or <language>-<territory>

### ISSUE THREAD

**Issue by mersadk** [Microsoft/TypeScript#16492]
**TypeScript Version:**  2.3

When I try to publish web site from VS2017 I get following error:
> Locale must be of the form \<language> or \<language>-\<territory>. For example 'en' or 'ja-jp'.	

In output window there is this line:

> C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.3\tsc.exe --project "C:\VS_Projects\MyWebProject\tsconfig.json" --listEmittedFiles --locale bs-Latn-BA

I didn't set --locale anywhere, it was set either by operating system or visual studio.

_Edit: Probably not important for this, but if I publish to folder, instead of web deploy, VS2017 will publish it with locale en-US._

**Comment by mhegazy** [comment]
As a workaround, set the `PreferedUILang` in your project to a different language, e.g. `en-us`

```xml
  <PropertyGroup>
    <PreferredUILang>en-us</PreferredUILang>
  </PropertyGroup>
```

**Comment by hmendozap** [comment]
Can confirm also happens in TypeScript 2.2

**Comment by DanielRosenwasser** [comment]
What OS and VS versions are you using? Have you customized your language settings somehow?

**Comment by hmendozap** [comment]
Win 10 Creators Update with VS2017 (15.2 - 26430.16) Release. 

Customized language settings? That's the weird part, I work in latin america, but all my dev is in english, my keyboard is dvorak-spanish, does that count?

**Comment by minestarks** [comment]
[bs-Latn-BA = Bosnian (Bosnia and Herzegovina, Latin)](https://msdn.microsoft.com/en-us/library/ms172470(v=vs.80).aspx) for what it's worth

we should be able to parse locales like this.

**Comment by minestarks** [comment]
@hmendozap Are you still running into this? Do you have a build log you can share?

**Comment by minestarks** [comment]
I don't have enough details to make progress on this. As far as I can tell the locale passed into tsc.exe has to be one of the supported VS display languages, which this isn't one of. Without a project file / build log I'm not going to be able to understand where this string came from. Closing the issue.
