### ISSUE TITLE
Uninstantiated type in error message

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#1649]
As seen in [this commit](https://github.com/Microsoft/TypeScript/commit/22174a17c64319942f56da8d19ff97f3f14f8f54#diff-26bfe3d8e390ffbda8420d86d6626f8bR15):

```
The type argument for type parameter 'T' cannot be inferred from the usage. Consider specifying the type arguments explicitly.
  Type argument candidate 'string' is not a valid type argument because it is not a supertype of candidate 'T'.
```

But the second part of the message should have 'number' in place of 'T'.

**Comment by DickvdBrink** [comment]
The message changed a bit but I think it is right now:
Argument of type 'number' is not assignable to parameter of type 'string'.

https://github.com/Microsoft/TypeScript/blob/master/tests/baselines/reference/contextualTypingWithFixedTypeParameters1.errors.txt

**Comment by danquirk** [comment]
Agreed, looks better now, thanks.
