### ISSUE TITLE
Imported types are unrecognized in complex typedefs in --checkJs

### ISSUE THREAD

**Issue by Zarel** [Microsoft/TypeScript#16500]
**TypeScript Version:**  nightly (2.5.0-dev.20170613)

**Code**

`test-externclassdef.js`
```js
class Foo {
  constructor() {}
}

exports.Foo = Foo;
```

`test.js`
```js
const {Foo} = require('./test-externclassdef');

// this works
/** @type {Map<string, Foo>}} */
let fooMap = new Map();

// this is an error
/** @type {{foo: Map<string, Foo>}} */
let fooMapHolder = {foo: new Map()};
```

**Expected behavior:**
No error

**Actual behavior:**
```
test.js(8,30): error TS2304: Cannot find name 'Foo'.
```

**Comment by mhegazy** [comment]
this is going to be a bit hard. we leverage the same TS infrastructure once you have an object type in JSDoc. teasing it out would not be simple.

**Comment by mhegazy** [comment]
Should be fixed in latest.
