### ISSUE TITLE
Cannot remove on<event>

### ISSUE THREAD

**Issue by ecymerman** [microsoft/TypeScript#16508]
**TypeScript Version:**  2.3.0

**Code**

```ts
let img = document.createElement('img');
img.onload = function () { /*...*/ };
//somewhere further... we want to remove the event handler
img.onload = undefined;

```

**Expected behavior:**
It should allow this, even with strictNullChecks.

**Actual behavior:**
It doesn't, when strictNullChecks is on.

**Comment by TroyTae** [comment]
@elicym 
How about to use removeEventListener?
https://developer.mozilla.org/ko/docs/Web/API/EventTarget/removeEventListener

**Comment by Kovensky** [comment]
The spec says that they may be set (in javascript types) to a function or to `null`, but not `undefined`. https://html.spec.whatwg.org/multipage/webappapis.html#event-handlers

However, lib.d.ts as is does not allow either anyway.

The workaround I am currently using is `null!`, but that produces a `never` type that probably works by accident.

**Comment by mhegazy** [comment]
the type of the event should be `null | ((this: Document, ev: UIEvent) => any;)`

**Comment by heejongahn** [comment]
@mhegazy I encountered this issue at work and would like to tackle on this. However, I couldn't find `onkeyup` and other event listeners' typedef in any of json input files in https://github.com/Microsoft/TSJS-lib-generator. Could you let me know which files (in which repo) should I change?

**Comment by saschanaz** [comment]
This has been fixed (with only `null` being allowed).

**Comment by jakebailey** [comment]
Just looking at old issues, this has been fixed for some time (per above); you can assign `null` to them.
