### ISSUE TITLE
TS2339, TS2694 errors in Visual Studio 2017

### ISSUE THREAD

**Issue by govis** [Microsoft/TypeScript#16504]
I have a project that was originally developed with VS2015 and migrated to VS2017. The project consists of a few dozen .ts files.  Upon build I see numerous TS2339 and TS2694 errors complaining about not finding namespaces, members, types, etc showing in the error list even though it builds and runs successfully. Adding a single simple code break also adds a few dozen bogus TS2304, TS2503 dumped on top of the real error.

TypeScript Intellisense is unusable. The project was originally developed in VS2015 and everything is fine when I open it there. Adding <code>///&lt;reference path="...ts" /></code> seems to help, but shouldn't it pick up all .ts files that are included in the project automatically just like VS2015 does?

![image](https://user-images.githubusercontent.com/971651/27103873-2a136b0c-5058-11e7-91df-97dd809fdcc6.png)

I am using latest (as of today) VS and TS/SDK builds: VS 15.2 (26430.13) with TypeScript 2.3.3.
Thanks.

**Comment by mhegazy** [comment]
I will need to look at the project to see what is going on. seems like files in the project are not picked up correctly. things to look for:
- do you have tsconfig.json in your project? if so make sure its include/exclude patterns are correct
- make sure content type of all your .ts files are TypeScriptCompile
- enable virtual project  (Tools / Options / Text Editor / JavaScript/TypeScript / Project / Display Virtual Projects when a solution is loaded). reload your project and share the view in your solution explorer.

**Comment by govis** [comment]
Thank you for suggestions. I don't have the tsconfig.json file and .ts files do have TypeScriptCompile as the build action. There're no changes to the project structure/files as I simply open a fully functional VS2015 project in VS2017.

I checked "Display Virtual Projects" as you recommended. This added a couple of projects to the solution, but the errors remain even though tsc build is successful and generates combined .js output.

![image](https://user-images.githubusercontent.com/971651/27137210-50159fbc-50eb-11e7-8de0-99f31c07e84f.png)

One thing to note is that I have <code>DependentUpon</code> attribute on my the .ts files so I can neatly nest them under respective .html  files:

<pre><code>&lt;TypeScriptCompile Include="component\list\filter.ts">
    &lt;DependentUpon>filter.html&lt;/DependentUpon>
&lt;/TypeScriptCompile></code></pre>

It seems that removing <code>DependentUpon</code> might be alleviating some errors. Thanks.

**Comment by mhegazy** [comment]
from the screen shot above looks like `forms.ts` is not considered as part of your project `Website`. can you unload the project file, edit it, and share how `form.ts` is defined in the project XML?

**Comment by govis** [comment]
<pre><code>&lt;TypeScriptCompile Include="component\confirm\form.ts">
    &lt;DependentUpon>form.html&lt;/DependentUpon>
&lt;/TypeScriptCompile></code></pre>

I believe it's <code>DependentUpon</code> that's causing this. Thanks.

**Comment by mhegazy** [comment]
@jramsay has a fix for this one. thanks for the debugging info. fix should be included in update 4.
