### ISSUE TITLE
Allows comparison of types that are not comparable

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#16507]
**TypeScript Version:**  nightly (2.5.0-dev.20170613)

**Code**

```ts
const a = new Date();
const b = new Date();
console.log(a < b); // false
console.log(a > b); // false
console.log(a === b); // false
```

**Expected behavior:**

Compile error: can't compare `Date`s.

**Actual behavior:**

No error.

**Comment by mhegazy** [comment]
See https://github.com/Microsoft/TypeScript/issues/2361

**Comment by mhegazy** [comment]
Looks like it should be covered under https://github.com/Microsoft/TypeScript/issues/15506
