### ISSUE TITLE
Cloning a tuple turns it into an array

### ISSUE THREAD

**Issue by Zarel** [microsoft/TypeScript#16503]
**TypeScript Version:**  every version tested (from 2.3.0 to 2.5.0-dev.20170613)

**Code**

```ts
type Tuple = [number, number];
let t1: Tuple = [1, 2];
let t2: Tuple = t1.slice();
let t3: Tuple = t1.slice(0);
let t4: Tuple = [...t1];
```

**Expected behavior:**
No error

**Actual behavior:**
```
test-slice.ts(3,5): error TS2322: Type 'number[]' is not assignable to type '[number, number]'.
  Property '0' is missing in type 'number[]'.
test-slice.ts(4,5): error TS2322: Type 'number[]' is not assignable to type '[number, number]'.
test-slice.ts(5,5): error TS2322: Type 'number[]' is not assignable to type '[number, number]'.
```

`array.slice()` and `array.slice(0)` and `[...array]` are common idiomatic ways to shallow-clone an array. Unfortunately, this loses the tuple type information.

I don't know how easy this would be to fix, but even something like supporting only tuples below a certain length (by hardcoding `[T1, T2] => [T1, T2]` type signatures for `Array#slice`) would be a pretty big improvement for my own use-case.

**Comment by mhegazy** [comment]
I suppose we can make Tuple extend from a new `Tuple` interface instead of `Array`, and make that return `this` in a punch of places.

**Comment by thw0rted** [comment]
For some reason #4988 was closed but this was left open.  I just want *one* correct, non-verbose way to clone a tuple.

**Comment by thw0rted** [comment]
I don't remember exactly what led me to post this a few months ago but as of now it looks like `slice` does return the same tuple.  Unfortunately, so does `slice(0,1)` so you can easily give yourself a tuple that's actually shorter than should be guaranteed.  Is that intentional?

**Comment by y-nk** [comment]
@thw0rted [it seems not the case anymore at least in 4.8.0-dev](https://www.typescriptlang.org/play?ts=4.8.0-dev.20220519#code/MYewdgzgLgBAZiEAuGBtMBXAtgIwKYBOANDJroQLowC8aAjCQEwUBQoksOAhgTfIgDoIAGwCWwPAAoAlEA)

**Comment by thw0rted** [comment]
I don't remember the circumstances when I posted that, but it looks like I was probably wrong.  I spent a minute trying different versions of the playground and all the ones I can find behave the same way -- `slice` returns an array.

**Comment by RyanCavanaugh** [comment]
Spread works now, which seems sufficient + idiomatic, and I think we don't have any good mechanisms to hardcode `slice` in a satisfying way.

**Comment by thw0rted** [comment]
Thanks Ryan, is this in the docs anywhere?  I can't find anything about spread on [the Tuple page](https://www.typescriptlang.org/docs/handbook/2/objects.html?#tuple-types), or anything about tuples on [the Spread page](https://www.typescriptlang.org/docs/handbook/variable-declarations.html#spread).

I'm trying to understand how implied types work with spread, specifically.  In [this example](https://www.typescriptlang.org/play?ts=4.6.2#code/CYUwxgNghgTiAEAzArgOzAFwJYHtVIAoAPALngG1VkBbAIxBgBp4q6GBdASjIDcctgAbgBQwsHgDOGJDhxlKNekxaKO8ALwUAjMwBM7EeNRT4UeayXMLazeQB0DxLINjJ02hpk5Db+GE-2js4iwogEUJwiYbSRoQRgkfAA9EnwDDA4yrRQAF7wWNQADhBYIMDwGACehQhYEipsMOTsQA), you can explicitly type an assignment from a spread-clone without any errors, but if you don't give any hints, it still winds up as a non-tuple array.

I'd still like to have a built-in that copies a tuple and always treats the result as the same tuple signature; I guess I could write a lightweight wrapper that just uses spread if I have to.

**Comment by RyanCavanaugh** [comment]
This is a facet of contextual typing: array literals get checked as tuples if contextually typed by a tuple type.
