### ISSUE TITLE
Can't namespace-merge into Class returned from a method / variable.

### ISSUE THREAD

**Issue by bennadel** [microsoft/TypeScript#16517]
I am attempting to namespace-merge into a Class that is returned from a method. The core task at hand is creating an application-local copy of the Bluebird library; then, adding additional static and prototype methods to it. In order to get an application-local copy, I have to call:

```ts
var BluebirdX = Bluebird.getNewLibraryCopy();
```

... however, it seems that namespace-merging cannot be done on a variable that references a class. This can be duplicated with simple code.

**TypeScript Version:**  2.3.2

**Code**

```ts
function X(){}
namespace X {
	export function foo(){};
}
console.log( X.foo );
```

... works fine and logs the `X.foo` method injected. However, if we store `X` in a variable:

```ts
var X = function (){}
namespace X {
	export function foo(){};
}
console.log( X.foo );
```

... which is basically equivalent code, we get the TypeScript error:

```
bluebird-extended.ts (16,5): Duplicate identifier 'X'. (2300)
bluebird-extended.ts (17,11): Duplicate identifier 'X'. (2300)
bluebird-extended.ts (20,16): Property 'foo' does not exist on type '() => void'. (2339)
```

**Expected behavior:**

The class referenced in the variable should be augmented.

**Actual behavior:**

TypeScript complains about a duplicate identifier. Since I am necessarily dealing with a class that is returned from a method call, I am not sure what kind of work-around I can use.

**Comment by jcalz** [comment]
Workaround: maybe something like
```ts
class BirdBlue { static getNewLibraryCopy: () => typeof BirdBlue };
var _X: typeof BirdBlue = BirdBlue.getNewLibraryCopy();
class X extends _X {}
namespace X {
	export function foo(){};
}
console.log( X.foo );
```
(I don't know anything about the typings for bluebirdjs, so I made up `BirdBlue` for the example)

**Comment by bennadel** [comment]
@jcalz I think the problem with going down the `extends` route is that I lose the _static_ methods on the `_X` class. But, to be honest, I am not sure what the expected behavior of _static_ methods are with extends. I will try it out.

**Comment by bennadel** [comment]
This was actually pretty close. First, I didn't realize that _static_ methods were inherited. That's cool. But, the problem with using `extends` is that the original methods, inherited from the `getNewLibraryCopy()` instance, internally create new instances of the `_X` library, not the `X` one. So, the first call will work as expected; but, the chained calls will not since they lose the context of the sub-class.

**Comment by jcalz** [comment]
Close but no cigar.  Oh well, I tried!

**Comment by bennadel** [comment]
This morning, I tried moving the augmentation to a regular `.js` file, and then just declaring a class that `extends` the base-class. But, that didn't seem to work either :) Mostly, I'm just throwing anything I can against the wall to see what sticks.

**Comment by jcalz** [comment]
Did you try throwing this against the wall?
```ts
class BirdBlue { static getNewLibraryCopy: () => typeof BirdBlue };
interface ExtraStatics {
    foo();
}
var X = <typeof BirdBlue & ExtraStatics> BirdBlue.getNewLibraryCopy();
X.foo = function foo () {
    
}
console.log(X.foo);
```
This mostly emits the same thing as your original. 

But I feel like you will still run into the same problem with chained methods, at least with the typings.  That is, even if the returned object has the new methods at runtime, the compiler will probably not recognize this:
```ts
class BirdBlue {
    static getNewLibraryCopy: () => typeof BirdBlue
    static statChained: () => typeof BirdBlue;
    instChained: () => BirdBlue;
};
interface ExtraStatics {
    foo();
}
var X = <typeof BirdBlue & ExtraStatics> BirdBlue.getNewLibraryCopy();
X.foo = function foo () {
    
}
console.log(X.foo);
console.log(X.statChained().foo); // nope
```

If you need *that* to work, you might need to do something like:
```ts
class BirdBlue {
    static getNewLibraryCopy: () => typeof BirdBlue;
    static statChained: () => typeof BirdBlue;
    instChained: () => BirdBlue;
};
class _X extends BirdBlue {
    static statChained: () => typeof _X; // narrow
    instChained: () => _X; // narrow
    static foo: () => void; 
} // this class never actually gets instantiated

var X = <typeof _X> BirdBlue.getNewLibraryCopy();
X.foo = function foo() {
    
}
console.log(X.foo);
console.log(X.statChained().foo) // works now
```

**Comment by bennadel** [comment]
@jcalz wow, this is super interesting stuff. This definitely is far outside my current comfort zone with TypeScript (and on top of that, Bluebird uses all kind of Generics, so I'm trying to weave that into your example as well). I've tried a couple of different ways to do what you're doing, but I kept falling over when I had to implement methods on the `.prototype.` as well as static.

I really appreciate all the help; just wish I could merge into a Class stored in a variable :P

**Comment by DanielRosenwasser** [comment]
I can't find the original issue for reopening the type of any declared binding, so we'll mark this as the suggestion.

**Comment by bennadel** [comment]
@DanielRosenwasser to be clear, I am not suggesting any arbitrary variable being augmentable at runtime (I've seen tickets that discuss that). I'm specifically speaking to the case where the variable references a Class. Not sure if that's a meaningful distinction there.

**Comment by RyanCavanaugh** [comment]
Declining due to lack of demand
