### ISSUE TITLE
Checkbox for alwaysStrict missing in Visual Studio project properties

### ISSUE THREAD

**Issue by MatejQ** [Microsoft/TypeScript#16519]
**TypeScript Version:**  2.3.3

**Expected behavior:**
There should be a checkbox to turn on compiler option --alwaysStrict in project properties.

**Actual behavior:**
There is currently no way to turn on --alwaysStrict via Visual Studio. There is no checkbox for that.
![capture](https://user-images.githubusercontent.com/14346231/27132037-91de288e-510d-11e7-9f22-66197cc7aae0.PNG)
Maybe it would be possible by tsconfig.json, but we don't use (or have) it inside our project currently and when I added it, a plethora of other stuff broke (build errors).

Please add a user-friendly checkbox to Visual Studio project properties to turn alwaysStrict on.

**Comment by mhegazy** [comment]
not all options are available in the UI. only a small subset. for all options you can either set them manually in your proj file, see http://www.typescriptlang.org/docs/handbook/compiler-options-in-msbuild.html for the full list of properties, or you can use a tsconfig.json instead to manage your project properties.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
