### ISSUE TITLE
Unused files

### ISSUE THREAD

**Issue by DickvdBrink** [Microsoft/TypeScript#1652]
I created a small program and it checks which files are actually used. If I remove the following files everything still compiles and works (tsc.js and typescriptservices.js output is the same). 
Am I totally messing this's up? If not, why are they on git? 

edit: I can make a PR if you want [see change](https://github.com/DickvdBrink/TypeScript/compare/unused-stuff2?expand=1)

**Changed list after some feedback**

../typescript-github/src/harness/exec.ts
../typescript-github/src/harness/project.ts
../typescript-github/src/services/compiler/declarationEmitter.ts
../typescript-github/src/services/compiler/diagnostics.ts
../typescript-github/src/services/compiler/emitter.ts
../typescript-github/src/services/compiler/enumerator.ts
../typescript-github/src/services/compiler/hashTable.ts
../typescript-github/src/services/compiler/identifierWalker.ts
../typescript-github/src/services/compiler/io.ts
../typescript-github/src/services/compiler/optionsParser.ts
../typescript-github/src/services/compiler/pathUtils.ts
../typescript-github/src/services/compiler/process.ts
../typescript-github/src/services/compiler/references.ts
../typescript-github/src/services/compiler/sourceMapping.ts
../typescript-github/src/services/compiler/tsc.ts
../typescript-github/src/services/compiler/typescript.ts
../typescript-github/src/services/compiler/walkContext.ts
../typescript-github/src/services/core/arrayUtilities.ts
../typescript-github/src/services/core/debug.ts
../typescript-github/src/services/core/diagnosticCategory.ts
../typescript-github/src/services/core/diagnosticCore.ts
../typescript-github/src/services/core/diagnosticInfo.ts
../typescript-github/src/services/core/errors.ts
../typescript-github/src/services/core/integerUtilities.ts
../typescript-github/src/services/core/lineMap.ts
../typescript-github/src/services/core/linePosition.ts
../typescript-github/src/services/core/mathPrototype.ts
../typescript-github/src/services/core/references.ts
../typescript-github/src/services/core/stringTable.ts
../typescript-github/src/services/core/stringUtilities.ts
../typescript-github/src/services/formatting/indentation.ts
../typescript-github/src/services/resources/diagnosticCode.generated.ts
../typescript-github/src/services/resources/references.ts
../typescript-github/src/services/syntax/characterInfo.ts
../typescript-github/src/services/syntax/constants.ts
../typescript-github/src/services/syntax/emitter.ts
../typescript-github/src/services/syntax/formattingOptions.ts
../typescript-github/src/services/syntax/incrementalParser.ts
../typescript-github/src/services/syntax/languageVersion.ts
../typescript-github/src/services/syntax/parser.ts
../typescript-github/src/services/syntax/prettyPrinter.ts
../typescript-github/src/services/syntax/references.ts
../typescript-github/src/services/syntax/scanner.ts
../typescript-github/src/services/syntax/scannerUtilities.generated.ts
../typescript-github/src/services/syntax/slidingWindow.ts
../typescript-github/src/services/syntax/syntax.ts
../typescript-github/src/services/syntax/syntaxCursor.ts
../typescript-github/src/services/syntax/syntaxDedenter.ts
../typescript-github/src/services/syntax/syntaxElement.ts
../typescript-github/src/services/syntax/syntaxFacts.ts
../typescript-github/src/services/syntax/syntaxFacts2.ts
../typescript-github/src/services/syntax/syntaxGenerator.ts
../typescript-github/src/services/syntax/syntaxIndenter.ts
../typescript-github/src/services/syntax/syntaxInterfaces.generated.ts
../typescript-github/src/services/syntax/syntaxKind.ts
../typescript-github/src/services/syntax/syntaxList.ts
../typescript-github/src/services/syntax/syntaxNodeInvariantsChecker.ts
../typescript-github/src/services/syntax/syntaxNodeOrToken.ts
../typescript-github/src/services/syntax/syntaxNodes.concrete.generated.ts
../typescript-github/src/services/syntax/syntaxNodes.interfaces.generated.ts
../typescript-github/src/services/syntax/syntaxToken.ts
../typescript-github/src/services/syntax/syntaxTree.ts
../typescript-github/src/services/syntax/syntaxTrivia.ts
../typescript-github/src/services/syntax/syntaxTriviaList.ts
../typescript-github/src/services/syntax/syntaxUtilities.ts
../typescript-github/src/services/syntax/syntaxVisitor.generated.ts
../typescript-github/src/services/syntax/syntaxWalker.generated.ts
../typescript-github/src/services/syntax/testUtilities.ts
../typescript-github/src/services/syntax/unicode.ts
../typescript-github/src/services/syntax/utilities.generated.ts
../typescript-github/src/services/text/characterCodes.ts
../typescript-github/src/services/text/lineMap.ts
../typescript-github/src/services/text/references.ts
../typescript-github/src/services/text/scriptSnapshot.ts
../typescript-github/src/services/text/text.ts
../typescript-github/src/services/text/textChangeRange.ts
../typescript-github/src/services/text/textFactory.ts
../typescript-github/src/services/text/textSpan.ts
../typescript-github/src/services/text/textUtilities.ts

**Comment by DanielRosenwasser** [comment]
I'm pretty sure @CyrusNajmabadi uses a lot of these files in prototyping incremental parsing functionality.

**Comment by RyanCavanaugh** [comment]
I believe `instrumenter.ts` is used in `jake tsc-instrumented`, so you might want to double-check that your script hits all of our jake targets

**Comment by DickvdBrink** [comment]
@RyanCavanaugh, ouch thanks my mistake.. updated the list above (it is now 2 items smaller because of the instrumented). List is still quite large, I will check if I missed some more targets, thanks!
Sorry

**Comment by DickvdBrink** [comment]
Don't think it is necessary to keep this one open. It was more meant as a FYI
