### ISSUE TITLE
Add a formatter like Go fmt or eslint --fix

### ISSUE THREAD

**Issue by jpolo** [Microsoft/TypeScript#16522]
One of the main javascript / typescript problems when sharing code is the lack of unified way of coding. 

An interesting way of solving that is to include a format option in the compiler that will normalize the code.
The good side effect would also to remove some tools/file in the projects such as tslint.json (Which are also very fragmented).

Another application is the inclusion of codemods in this formatter feature to "upgrade" old deprecated code with the new syntax. This would allow Typescript to move faster forward without breaking developers code.
(Example: it would be possible to automatically fix old Typescript import  import syntax to ES6)

**Comment by mhegazy** [comment]
have you looked at https://www.npmjs.com/package/typescript-formatter

**Comment by RichiCoder1** [comment]
Or [Prettier](https://github.com/prettier/prettier) which has recently been very popular and would standardize formatting w/ the broader JS ecosystem. Though I don't think either address auto-fixes, but that's a path fraught with peril I'd imagine.

**Comment by jpolo** [comment]
The fact that you are both citing two different tools shows again the
fragmentation and the multiplication of sources of truth.
In addition those tools are only used if the developer choose to.
If typescript compiler took the responsibility for this subject, there
would be only one recommended way to write TS.


Le 14 juin 2017 6:25 PM, "Richard Simpson" <notifications@github.com> a
écrit :

**Comment by DanielRosenwasser** [comment]
At this time, I don't think that the TypeScript team is or wants to be in the business of being prescriptive on code formatting. See my response [here](https://github.com/Microsoft/TypeScript/issues/6195#issuecomment-166836293). Given the number of issues & questions we've gotten about our own team's coding guidelines, we'd rather not go there.

Rather than pushing developers to change their coding preferences to use TypeScript, we'd rather integrate into existing tools. Yes, there is Prettier, tsfmt, and typescript-formatter, but don't feel overwhelmed. If it helps, I've heard great things about Prettier since support for TypeScript came out.

**Comment by jpolo** [comment]
I cannot agree more with myictv on the thread you posted.
If the formatter included does not suit to a dev they would use another one.
In contrary the format option has the power to provide a default standard
for 80% of people writing ts code.

Of course the included formatter would at first lead to complains because
it would change habits. But the complains are often a matter of taste. In
the long run people will get used to it as newcomers would only know the
standard syntax.

I can understand the decision taken by typescript team and have a lot
respect for the work you've done. Thus I won't insist more if nothing
cannot be done at the moment.



Le 14 juin 2017 10:01 PM, "Daniel Rosenwasser" <notifications@github.com> a
écrit :

**Comment by mhegazy** [comment]
TypeScript already has a formatting engine. it is exposed on our public API, and it is the same engine that is used in editors today.
The formatting engine is not exposed as a command line utility though. typescript-formatter  exposes that. it is the same engine and not a different one. and assuming you are using typescript-formatter on the commandline, and VSCode for editing , you should see the same formatting output in both.

**Comment by jpolo** [comment]
@mhegazy If I understand well there is a formatter engine but no default rules. Indeed this is a really cool feature. That was the point of this suggestion request : let's go further and provide a standard set of rules bundled with tsc command.

**Comment by mhegazy** [comment]
there are rules. and there are options to modify the rules. if you ever used VSCode to format a .ts or a .js file, that the TS format engine at work for you.

typescript-fromatter just gives you a command line command (ts-fmt) to access the compiler API you already use in VSCode, VS, sublime text, etc... 

if you are interested to look more, here is the main entry point in the compiler API: https://github.com/Microsoft/TypeScript/blob/5b12a04965bce1820fc7e6dc44cf20b850fe29ec/lib/typescript.d.ts#L3457

here are the options to configure it: https://github.com/Microsoft/TypeScript/blob/5b12a04965bce1820fc7e6dc44cf20b850fe29ec/lib/typescript.d.ts#L3624-L3640

and if you are curious about the implementation, here are all the rules that are applied on the code: https://github.com/Microsoft/TypeScript/blob/5b12a04965bce1820fc7e6dc44cf20b850fe29ec/src/services/formatting/rules.ts

and here is the line in typescript-formatter that calls into the API: https://github.com/vvakame/typescript-formatter/blob/d33dd0f6e18907274fd165648ba9532015cd4905/lib/formatter.ts#L14

**Comment by jpolo** [comment]
@mhegazy Very interesting links thanks. 
By "rules" I meant "rules preset". typescript-formatter scan for many config provider files that are still dependant from the good will of the developer => They are different on each project.
I should not have put the eslint --fix in the subject because it's misleading.

The Go example is more what I wanted to suggest : one bundled formatter with one default preset that will format the code in the standard way.

**Comment by mhegazy** [comment]
> By "rules" I meant "rules preset". typescript-formatter scan for many config provider files that are still dependant from the good will of the developer => They are different on each project.

not sure i understand. the options are available as [i mentioned above](https://github.com/Microsoft/TypeScript/blob/5b12a04965bce1820fc7e6dc44cf20b850fe29ec/lib/typescript.d.ts#L3624-L3640), you can set them in your editor, or in typescript-formatter. 

> The Go example is more what I wanted to suggest : one bundled formatter with one default preset that will format the code in the standard way.

that is what the TS provides, and it has always been the same way since 0.8.3. one formatting engine, one set of rules in all editors.

**Comment by jpolo** [comment]
As an example, a rule is `insertSpaceAfterCommaDelimiter` a preset is `insertSpaceAfterCommaDelimiter=true`. The fact that anybody can or cannot set the many options of formatting in the editor _is_ the problem. This leads to fragmentation of the way of coding among javascript/typescript projects.

> that is what the TS provides, and it has always been the same way since 0.8.3. one formatting engine, one > set of rules in all editors.
In the links you posted there is the engine and the rules but not the presets included. This is left to the IDE / tsfmt config file / typescript-formatter config file.

If you want another example take a look at https://www.npmjs.com/package/standard . No config file in the project, everything is bundled with the cli. The only thing that the dev has to do is run standard.js command...
The problem with standard.js is that if nobody knows this project nobody uses the standard and therefore the standard is not a real one.
That's why providing the formatter engine AND the formatter default rule settings is the key to the adoption to standard typescript syntax.

**Comment by mhegazy** [comment]
> As an example, a rule is insertSpaceAfterCommaDelimiter a preset is insertSpaceAfterCommaDelimiter=true. The fact that anybody can or cannot set the many options of formatting in the editor is the problem. This leads to fragmentation of the way of coding among javascript/typescript projects.

From the get go, TypeScript has avoided being prescriptive. The JS community is diverse, and ppl already have their rules and styles in place, and TypeScript aims to fit into these tool chains and not replace/change them.

**Comment by jpolo** [comment]
As you said the formatter API is present and everyone is free to used it and would continue to use it with the tools if they want.
That's the difference between a standard (as I am proposing) and an edict (ex: a tool forced to be use). 
For a community, a standard is good. People can choose to be out of it and that's okay. Just they have to know what is standard and why they chose to ignore it.
