### ISSUE TITLE
Distinguish missing and undefined

### ISSUE THREAD

**Issue by sandersn** [Microsoft/TypeScript#16524]
Typescript should distinguish `missing` and `undefined` at the type level in order to distinguish the following two statements:

```ts
// @strictNullChecks: true
type A = { x?: string }
let x: A = {}
let y: A = { x: undefined } // should not be allowed, but currently is
```

**Comment by dgoldstein0** [comment]
I believe this is a dupe of #13195

**Comment by mhegazy** [comment]
you are right. closing.
