### ISSUE TITLE
Allow Running TypeScript in Strict Mode

### ISSUE THREAD

**Issue by SlurpTheo** [Microsoft/TypeScript#16531]
**TypeScript Version:**
typescript@rc (typescript@2.4.0)
typescript@next (typescript@2.5.0-dev.20170614)

**Expected behavior:**
No SyntaxError.

**Actual behavior:**
```
...\path>node --version
v6.11.0

...\path>node --use_strict node_modules\typescript\bin\tsc --version
...\path\node_modules\typescript\lib\tsc.js:40882
            var arguments = node.arguments;
                ^^^^^^^^^
SyntaxError: Unexpected eval or arguments in strict mode
```

Similar to previous versions/issues:
https://github.com/Microsoft/TypeScript/issues/9449
https://github.com/Microsoft/TypeScript/issues/10755

**Comment by DanielRosenwasser** [comment]
We'd be willing to take a PR to the `release-2.4` and `master` branches to rename `arguments` to `args`.

**Comment by mhegazy** [comment]
we should also turn `--alwaysStrict` on on the compiler code base. this should have caught this:
```sh
tsc --p src\compiler\tsconfig.json --alwaysStrict

24727             const arguments = node.arguments;
                        ~~~~~~~~~

src/compiler/checker.ts(24727,19): error TS1100: Invalid use of 'arguments' in strict mode.

```
