### ISSUE TITLE
Language services hard-codes newline to \r\n

### ISSUE THREAD

**Issue by csnover** [Microsoft/TypeScript#1653]
services/services.ts `createCompilerHost` function hardcodes `getNewLine` to "\r\n" instead of providing a way for the LanguageServiceHost to define it (or at least using ts.sys.newLine).

Refs #372.

**Comment by nycdotnet** [comment]
@mhegazy Would you consider a PR to add this to tsc?  We've gotten requests for this in grunt-ts, and we don't currently have a way to support it without tsc supporting it directly.  Thanks.

**Comment by mhegazy** [comment]
We already have an issue for it #1693. Looks like we need a new compiler flag for it. PR welcomed. I have no good ideas for the name though... --newLine \n or --newLine CRLR / LR.
