### ISSUE TITLE
feature request: always-throw functions detect in null check

### ISSUE THREAD

**Issue by zh99998** [Microsoft/TypeScript#16546]
currently null check can detect `throw`, such code will works.
```typescript
        const x = localStorage.getItem('test');
        if (!x) {
            throw 'error'
        }
        console.log(x.length);
```
but when `throw` was wrapped in a function, it fails. `TS2531: Object is possibly 'null'`

```typescript
class Example {
    throw(something = true) {
        if (something) {
            throw 'error';
        } else {
            throw 'another';
        }

    }

    main() {
        const x = localStorage.getItem('test');
        if (!x) {
            this.throw();
        }
        console.log(x.length);
    }
}

```

now `throw()` will always `throw` an exception in any condition, it's better if this could be detected

**Comment by DanielRosenwasser** [comment]
You can instead `return `this.throw()` if you make its return type `never` to get something like this.

But it's not currently possible to signal that a function invocation completely changes the control flow graph, and I don't know if we ever will be able to.

**Comment by zh99998** [comment]
coule we simply make all code after `never` be unreachable ?
class Example {
    throw(): never { ... }
    main() {
        this.throw();
        console.log(1); // Unreachable code detected.
    }
}

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
