### ISSUE TITLE
Type-based flow control

### ISSUE THREAD

**Issue by kol-93** [Microsoft/TypeScript#16541]
**SUGGESTION**
Compilation-time type-based flow control in overloaded functions and/or type-based generic specializations and/or safe static castings are NEEDED.

Suggested syntax:
 * Compilation-time type-based flow control: [C++ compile-time](http://en.cppreference.com/w/cpp/language/overload_resolution)
 * Compilation-time generic specializations: [C++ compile-time](http://en.cppreference.com/w/cpp/language/template_specialization)
 * Safe static castings: static_cast<TargetType>(x: object) => TargetType | void 

**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

**Code**
**Example that shows inconsistency of current language abilities**
```
interface IFirst { 
	f1(): void;
}

interface ISecond { 
	f2(): void; 
}

function isFirst(obj: object) {
	return typeof (obj as IFirst).f1 == 'function';
}

function isSecond(obj: object) {
	return typeof (obj as ISecond).f2 == 'function';
}



class CorrectImplementation implements IFirst, ISecond {
	f1() {
		console.info('+f1');
	}
	
	f2() {
		console.info('+f2');
	}

}

interface IPerson {
	name: string;
}

class IncorrectImplementation implements ISecond {
	f1(x: IPerson): void {
		console.info(`f1(person: ${JSON.stringify(x.name)})`);
	}
	
	f2() {
		console.info('+f2');
	}

}

let objects:Array<IFirst | ISecond> = [
	new CorrectImplementation(),
	new IncorrectImplementation()
];

for (let inst of objects) {
	if (isFirst(inst)) { ///
		// invalid function type for IncorrectImplementation: (x: IPerson) => void
		// expected () => void
		// => TypeError (runtime): Cannot read property 'name' of undefined
		(inst as IFirst).f1();
	}
	if (isSecond(inst)) {
		(inst as ISecond).f2();
	}
}

```
**Summary:**
* Type guards do not work as needed.
* There is no type-based flow control.
* 'Compilation-time type checks' does not wor as expected

**Comment by mhegazy** [comment]
Should not your type guard check the function length as well, if you want to be safe?

not sure how this is related to type guards or not. you are using type assertions to access your properties, which is telling the compiler to shut up and let you do what you want. 
also runtime casting checks is something out of scope of the TypeScript project. please see https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals for more information.

**Comment by kol-93** [comment]
I'm not speaking about runtime type assertions here.
I'm speaking about compilation-time conditions like  [std::type_traits::is_base_of<Base, Derived>](http://en.cppreference.com/w/cpp/types/is_base_of) or something like this to check if (typeof value) implements or extends some concrete interface or class.
I don't want to check length of function and make many other spikes. Situation in the code above is very usual situation in the overloaded functions for example. And this language gives no chance to make good library that can be safe for users.

This is **IN THE SCOPE**.
Can you be honest with yourselves and write language for clever people not for stupids?

**Comment by kol-93** [comment]
I only want to write something like
```
for (let inst of objects) {
	if (is_base_of<IFirst, typeof inst)>.value) { ///
		(inst as IFirst).f1();
	}
	if (is_base_of<ISecond, typeof inst)>.value) {
		(inst as ISecond).f2();
	}
}
```
without any type guards and other spikes. It's only compilation-time type-based flow.
TypeScript has no good implementation of overloaded functions (because of single implementation for many types). It also has no good implementation for generics for the same reasons. But if you want to make strong language for compilation-time process you ** HAVE TO MAKE ** theese things.

**Comment by DanielRosenwasser** [comment]
@kol-93 please keep our [code of conduct](https://opensource.microsoft.com/codeofconduct/) in mind.

I think you're just looking for [type predicate types](https://www.typescriptlang.org/docs/handbook/advanced-types.html#user-defined-type-guards).

**Comment by kol-93** [comment]
@DanielRosenwasser please look carefully at my code in the first message before you write your's next.
There are we can see **type guards**, that can check only JavaScript-compatible properties and types. So if you have function, you can't check it's signature, if you have interface-typed property, you can check it only with other **type guards** and so on.
So you **think** wrong. You have too much **suggestions** about type assertions in this repo here and you or your **friends** from Microsoft are closing all of them with same reason **"out of scope"**. Please don't tell me about **code of conduct** because you ignore clever things from good programming languages and implement too many spikes without understanding of basics. 

Please look how overloaded functions implemented in other languages before you answer this post. Do you have such implementation?? Do you have generics (or just templates) specialisations? Ok, you don't want to add **RTTI** to this language (but there too many clever things that it's a bad idea), but in this case you have to implement some instruments for compilation-type assertions else your language will be only a **JavaScript with syntax sugar**, but not a **TypeScript**.

**Comment by gcnew** [comment]
Very helpful, precise and constructive commentary. Thee wise man, shalt you share more of your infinite knowledge with us, the uninitiated?

**Comment by RyanCavanaugh** [comment]
That will be enough for this thread. Runtime type instantiation has been discussed to death and conduct like this will not be changing anyone's mind.
