### ISSUE TITLE
geterr Stops Returning Results

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#16540]
From https://github.com/Microsoft/vscode/issues/28630

**TypeScript Version**: 2.3.4

In some cases, it seems that the `geterr` request against the TSServer stops returning any results. I've been unable to reproduce this reliably but here's a log from one of the sessions that ran into this problem: [tsserver.txt](https://github.com/Microsoft/TypeScript/files/1076202/tsserver.txt)

In this case, I was deliberately introducing syntax errors into `markdownEngine.ts`

```
Info 1562 request: {"seq":524,"type":"request","command":"geterr","arguments":{"delay":0,"files":["/Users/matb/projects/vscode/extensions/markdown/src/markdownEngine.ts"]}}
Perf 1563 524::geterr: async elapsed time (in milliseconds) 0.3660
Info 1564 event: {"seq":0,"type":"event","event":"requestCompleted","body":{"request_seq":524}}
```

This file is part of the project but no syntax errors are returned for it

**Comment by andy-ms** [comment]
@mjbvz Could you try again once #17269 is in?
