### ISSUE TITLE
DOM HTMLFormElement relationship should be nullable type

### ISSUE THREAD

**Issue by yokomotod** [Microsoft/TypeScript#16543]
**TypeScript Version:**  2.3.2

In `lib.dom.d.ts`, form-associated elements (`HTMLInputelement`, `HTMLInputelement`, etc...) have `.form` field as NOT-nullable, but it could be null when it is not associated to any form element.

Reference: [WHATWG HTML Living Standard](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#association-of-controls-and-forms)

> A form-associated element can have a relationship with a form element, which is called the element's form owner. If a form-associated element is not associated with a form element, **its form owner is said to be null**.

**Expected behavior:**

```
readonly form: HTMLFormElement | null;
```

**Actual behavior:**

```
readonly form: HTMLFormElement;
```

**Comment by NColey** [comment]
Hi I just opened a PR that I think should fix the above issue here: https://github.com/Microsoft/TSJS-lib-generator/pull/281 . Let me know if there is anything I should change, thanks so much!
