### ISSUE TITLE
JSDoc: support intersection types

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/TypeScript#16550]
**TypeScript Version:**  2.3.4

**Code**

In this example, the type def `Props` fails because of the intersection syntax, which is not supported by JSDoc:

```ts
{
  /** @typedef { { foo: number } & { bar: number } } Props */
  /** @type {function(Props): Props} */
  const fn = props => props;
  fn({ foo: 'x' }); // <-- expected error, got none
}
```

Is TypeScript planning to extend the JSDoc syntax to support TypeScript syntax within the comments, or is it only following the official JSDoc standard?

For context, this would be useful because we are gradually introducing TypeScript to our codebase via `checkJs`. As a workaround, I am putting these typings into a declaration file on a global namespace:

``` ts
declare namespace MyTypings {
  export type Props = { foo: number } & { bar: number }
}
```

``` js
{
  /** @type {function(MyTypings.Props): MyTypings.Props} */
  const fn = props => props;
  fn({ foo: 'x' }); // <-- error as expected
}
```

**Comment by mhegazy** [comment]
@sandersn, we should make sure we support the full list of options here, i.e intersection, typeof, call and construct signatures, etc..
