### ISSUE TITLE
typescriptlang.org suggestion: make subsections of Handbook pages easily linkable

### ISSUE THREAD

**Issue by daprahamian** [microsoft/TypeScript#16558]
Right now, if I want to link someone to the Type Guards section of Advanced Types, I need to manually construct the link http://www.typescriptlang.org/docs/handbook/advanced-types.html#type-guards-and-differentiating-types

It would be nice if I could just click on the header and have the link update in my browser.

**Comment by orta** [comment]
This is in as of last month 👍
