### ISSUE TITLE
Infer type from the usage

### ISSUE THREAD

**Issue by NN---** [Microsoft/TypeScript#1656]
Are there any plans for type inference from the usage ?
For instance:

```typescript
function f() : number;

var a;
try {  
  a = f();
} catch {
  a = 2;
}
```

I would like to see this code compiling.
Now I must put the type explicitly.

**Comment by RyanCavanaugh** [comment]
No. In general, inference from usage can be hard to reason about (e.g. if `a` were initialized with a `Cat` in the `try` and a `Dog` in the `finally` is that an error?) and often detects fewer errors than expected.
