### ISSUE TITLE
Colored output looks bad on black-on-white terminals

### ISSUE THREAD

**Issue by evmar** [Microsoft/TypeScript#16567]
TypeScript's `--pretty` output produces line numbers that show up as black-on-dark-gray when run on a terminal that is black-on-white.  See the number on the left here.  (Sorry for the giant picture, I run a hidpi screen.)

![image](https://user-images.githubusercontent.com/3847/27198842-c88d1c1c-51c8-11e7-9c82-3cd53b65409b.png)

Suggested fix: if you set the background color in the output, also force the foreground color.  I guess here you want to force white.

Also note that the special colors 38 and 48 are available for "the terminal's default foreground/background color":
https://en.wikipedia.org/wiki/ANSI_escape_code#Colors

**Comment by mhegazy** [comment]
PRs welcomed.
