### ISSUE TITLE
Not preserving folder structure in emit with one file 

### ISSUE THREAD

**Issue by bowdenk7** [microsoft/TypeScript#16563]
**TypeScript Version:**  nightly (2.5.0-dev.20170615)

**Code**

tsconfig.json
```json
{
  "compilerOptions": {
    "target": "es5",   
    "module": "commonjs",
    "outDir": "out",
    "allowJs": true
  }
}
```

Create a ts file in the following folder structure:
`TopFolder/SecondFolder/foo.ts`

Then run `tsc`.

**Expected behavior:**
Emitted code with the structure:
`out/TopFolder/SecondFolder/foo.js`

**Actual behavior:**
Emitted code with structure:
`out/foo.js`

As soon as you add a second file or folder, we start preserving the folder structure.

**Comment by bowdenk7** [comment]
There are multiple fairly simple workarounds:
- add `"rootDir": "."` to your `tsconfig.json` (definitely the best)
- add another peer level file/folder
- change `ourDir` to match the folder structure you want 

I'm not sure if this is by design or not, but it is certainly not intuitive. Though I think to fix it we would have to default `rootDir` to the same directory as the tsconfig which would probably break a bunch of people.

**Comment by bowdenk7** [comment]
@mhegazy  Yes, that >.<

**Comment by mhegazy** [comment]
@yui, let's put an optimization in to say if rootDir is not specified, and a tsconfig.json is, use the tsconfig.json location as root locaiton. in a sense defaulting `rootDir` to `.` if a tsconfig.json is used.

this is a breaking change, but i think it is a good one.

**Comment by andy-ms** [comment]
This would be a breaking change for anyone with `my_project/tsconfig.json` with all TypeScript files in `my_project/src` -- expecting to get e.g. `my_project/bin/a.js` and not `my_project/bin/src/a.js`. Many of our own projects are structured this way, and if we changed TypeScript to use `tsconfig.json` as the root, they would all have to be changed to manually specify `src` as the root instead.

**Comment by RyanCavanaugh** [comment]
Not going to break this scenario for the sake of intuition
