### ISSUE TITLE
Inconsistent behavior a class not being readonly if it is inside a module

### ISSUE THREAD

**Issue by webbiesdk** [Microsoft/TypeScript#16579]
**TypeScript Version:**  2.3.4

**Code**

```ts
module Bar {
    export class Foo {
        bla = 123;
    }
}

class Foo {
    bla = 123;
}

Bar.Foo = Foo; // no error
Foo = Bar.Foo; // error: "Cannot assign to 'Foo' because it is not a variable.
```

**Expected behavior:**
Either both of the last two lines to report an error, or none of them. 

**Actual behavior:**
It is only an error to replace a class, if it is not inside a module.

**Comment by DanielRosenwasser** [comment]
We should discuss what the "correct" behavior is.

**Comment by webbiesdk** [comment]
Modules have the same behavior. 

````TypeScript
module Bar {
    export module Sub {
        export var stuff = 321;
    }
}
module Sub {
    export var stuff = 321;
}

Bar.Sub = Sub; // no error
Sub = Bar.Sub; // error: "Cannot assign to 'Sub' because it is not a variable.
````

I think the "correct" behavior should be to have an error in both cases, since it seems unlikely that a programmer intends to overwrite a class/module definition.  
You can always cast to `any` if you really want to do it.

**Comment by andy-ms** [comment]
See #17502.
