### ISSUE TITLE
--pretty output is confusing

### ISSUE THREAD

**Issue by mitchellwills** [Microsoft/TypeScript#16583]
**TypeScript Version:**  2.3.4

When the compiler outputs errors it uses this format:
```
EXCERPT 1
   ^^   1

FILE: ERROR 1
EXCERPT 2
  ^^    2

FILE: ERROR 2
```

However, this is confusing since the first error is more closely associated with the second excerpt since it is separated by an empty line and a mostly blank line. I would propose changing it to:

```
FILE: ERROR 1
EXCERPT 1
   ^^   1

FILE: ERROR 2
EXCERPT 2
  ^^    2

```

**Comment by alexeagle** [comment]
+1 - we also got reports that it breaks in webstorm/intellij which tries to parse compiler errors when running `tsc` in the terminal pane.

**Comment by DanielRosenwasser** [comment]
> we also got reports that it breaks in webstorm/intellij which tries to parse compiler errors when running `tsc` in the terminal pane.

Oh no, `--pretty` output is not meant to be parsed! That's why we have the ordinary output as an option (as well as a language service). :/

**Comment by DanielRosenwasser** [comment]
For some context, the original design was to mimick how tooltips appear below the error span.

> However, this is confusing since the first error is more closely associated with the second excerpt since it is separated by an empty line and a mostly blank line

But there's two lines between each reported diagnostic. I guess I'm not seeing it to be honest, but we can bikeshed with the rest of the team.

**Comment by alexeagle** [comment]
There is a very minor bug: one of those newlines is in tsc.ts but should be
part of the format helper in program.ts. so we are missing a newline. I'll
send a tiny PR for that.

**Comment by evmar** [comment]
> Oh no, --pretty output is not meant to be parsed! That's why we have the ordinary output as an option (as well as a language service). :/

In our environment, we have a project that specifies `--pretty` in its build options, then another person trying to work on that project using an IDE that wants to parse the output.  Perhaps we need some sort of `--nopretty` to turn it off?

Out of curiosity I experimented locally with some other languages that have nice compiler output.  Both Rust and Clang always output pretty diagnostics.  Even when emitting to a log file (the only difference there is that they both suppress the colors in the output when emitting to a log file).

**Comment by DanielRosenwasser** [comment]
You can use `"pretty": false` in `tsconfig.json` (or `--pretty false` - boolean flags can take explicit `true`/`false` options on the command line).

**Comment by calebegg** [comment]
I find the ordering here, with excerpt above error, really unintuitive. Every other compiler I can think of to check does it in the other order:

javac
```
Test.java:3: error: cannot find symbol
  public static void main(Stirng args[]) {
                          ^
```

clang
```
test.cc:4:3: error: use of undeclared identifier 'cuot'
  cuot << "hello";
  ^
```

gcc
```
test.cc: In function ‘int main()’:
test.cc:4:3: error: ‘cuot’ was not declared in this scope
   cuot << "hello";
   ^
```

Closure compiler:
```
input0:1: WARNING - Property lgo never defined on Console
console.lgo('hello');
        ^^^
```

Swift:
```
test.swift:1:1: error: use of unresolved identifier 'prnit'
prnit("Hello, world!")
^~~~~
```

> For some context, the original design was to mimick how tooltips appear below the error span.

But...they don't, at least not in VS Code, unless you're on the very first line.

![image](https://user-images.githubusercontent.com/782920/27973896-abc1de0c-6329-11e7-8291-e0420b6408eb.png)

**Comment by DanielRosenwasser** [comment]
Thanks @alexeagle!
