### ISSUE TITLE
Different folder and package names causes errors messages

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#16589]
_From @victorschinaider on June 15, 2017 12:32_

- VSCode Version: Version 1.13.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Give a name to name property of package.json
2. Give a different name from package name property to root folder
3. intellisense for Javascript will stop to work and tsconfig.json will give strange errors.

Is it intentional?

Example:

**Folder structure**
```
   -> root-folder
       -> file1.ts
       -> package.json
       -> tsconfig.json
```

**Package snnipet*
```json
{
   "name": "root-folder-different",
   ...
}
```

_Copied from original issue: Microsoft/vscode#28813_

**Comment by mhegazy** [comment]
The module resolution logic does not look at `"name"`, only the folder name.
