### ISSUE TITLE
Type inference for method overrides in derived classes

### ISSUE THREAD

**Issue by Dru89** [Microsoft/TypeScript#16590]
**TypeScript Version:**  2.4.0

**Code**

```ts
interface IPage {
    method: (ev: string | number) => any;
}

class Page implements IPage {
    method(e): any {
        // this "e" is implicitly any
    }
}

let x = new Page();
x.method = (e) => {
    // this "e" is inferred to be 'string | number'
}
```

**Expected behavior:**
The method override in `Page` should be inferred type `string | number`.

**Actual behavior:**
The method override in `Page` is implicitly the `any` type.

This seems like it should instead infer the parent type, because 

1. instance overrides already have this sort of inference (see the [Contextual Type](https://www.typescriptlang.org/docs/handbook/type-inference.html#contextual-type) example about `window.onmousedown`), and
2.  if the class's override signature was something like `method(e: object): any`, there would be an error that says the class wasn't matching the interface's signature. (`Class 'Page' incorrectly implements interface 'IPage'.`)

**Comment by Dru89** [comment]
My apologies if this either isn't a bug (or feature request) or it's already been closed in a separate ticket.  

I wasn't able to really find anything related to this in search, and it seemed sort of like a bug to me.

**Comment by DanielRosenwasser** [comment]
It's not easy to find - check out #1373. Unfortunately we weren't able to solve this, but I think we're still considering some ideas here.

**Comment by Dru89** [comment]
Thanks for pointing this one out (and the rabbit hole of tickets that I found that came from it). 

Should I subscribe to #10610 as a potential solution and to #10570 as the open ticket for this dupe?  I can definitely see why this is hard to solve. 😄

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
