### ISSUE TITLE
Function that always throws is not inferred as having `never` return type

### ISSUE THREAD

**Issue by masaeedu** [Microsoft/TypeScript#16608]
**TypeScript Version:** 2.5.0-dev.20170618

**Code**

```ts
function fail1() {
  throw new Error()
}

const fail2 = function () {
  throw new Error()
}
```

**Expected behavior:**
Inferred return type of both functions is `never`

**Actual behavior:**
Only the return type of the second function is `never`. The return type of `fail1` is inferred as `void`.

**Comment by ahejlsberg** [comment]
This is by design. We had it the way you suggest originally but I was too much of a breaking change. See #8767 for more details.

**Comment by masaeedu** [comment]
@ahejlsberg Could we have a compiler flag that unifies this behavior?

**Comment by basarat** [comment]
Perhaps only class methods should get `void` inference :rose:

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Comment by aluanhaddad** [comment]
I really like @basarat's suggestion.
