### ISSUE TITLE
tsc --watch only seems to use the tsconfig.json file in the root of the project

### ISSUE THREAD

**Issue by ORESoftware** [Microsoft/TypeScript#16604]
I asked this question on SO:
https://stackoverflow.com/questions/44608091/transpile-all-typescript-files-to-a-relative-adjacent-directory

After some investigation, it seems like there is a bug or some features are needed with tsc -w because it does not do the expected behavior.

**Code**
See SO question, thanks.

**Expected behavior:**

I would expect `tsc -w` to use all the tsconfig.json files in a project. If there are tsconfig.json files in subdirectories, those tsconfig.json files should apply to all .ts files in those subdirectories.

**Actual behavior:**

Instead, it appears that tsc -w only uses the tsconfig.json file at the root of the project. That's how it looks to me after some experimenting.

I know this feature might be a pain in the ass to implement, but it would be a huge boon, because then I only need to run one tsc -w command. Actually, thinking about it, it shouldn't be that hard to implement it if you do it the *easy* way, explained below.

Suggestion:

` tsc -w `should do the following under the hood 

```
# algorithm
for each  tsconfig.json file X
cd $(dirname  X) && tsc -w 
```

that's all that really needs to happen TMK. So what will happen is a single tsc -w command may spawn several tsc -w commands.

I could implement this myself, but I think tsc -w should come with an extra flag that tells tsc -w to look for all tsconfig.json files.

**Comment by DanielRosenwasser** [comment]
tsc will only operate on one project (i.e. one `tsconfig.json`) at a time at the moment, and I don't think trying to support multiple different `tsconfig.json`s simultaneously is in scope. We do have some ideas for project-to-project references though #3469, but that is not something we'll see in the 2.5 timeframe.

**Comment by ORESoftware** [comment]
Alright, glad I was about right in my observation

I created this today, using the approach I mentioned above
https://github.com/ORESoftware/tsc-multi-watch

Given what you said, I don't see why tsc -w as it stands now, couldn't do what I suggested -

my suggestion is to do something like:

tsc -w --all-configs

or whatever, that way it won't break existing setups, but if you want to try watch for all different tsconfig.json files in a project, you can.

**Comment by GongT** [comment]
-1
this can be done by many exist tools.
do not need implement again.

the simplest way may be `find -exec`

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
