### ISSUE TITLE
TypeScript@next type acquisition approach may be broken

### ISSUE THREAD

**Issue by johnnyreilly** [Microsoft/TypeScript#16609]
Hey folks!

I'm one of the maintainers of [ts-loader](https://github.com/TypeStrong/ts-loader/)

We have a nightly build that runs which includes typescript@next in its matrix.  I've noticed this has been failing for a week or so now.  See the travis failure [here](https://travis-ci.org/TypeStrong/ts-loader).  Note that TypeScript 2.3 and earlier all run fine.

**TypeScript Version:**  nightly (2.5.0-dev.20170618)

**Code**

The problem is a failing jasmine test here:

https://github.com/TypeStrong/ts-loader/tree/master/test/execution-tests/2.0.3_typesResolution

**Expected behavior:**

This test should pass - it's not really a runtime test at all; it's purpose is to validate that the @types/jasmine types were acquired.

**Actual behavior:**

Test fails.  Types don't appear to be being acquired.  

I'm afraid I don't have too much time to look further into this but it appears that there is something potentially problematic with the TypeScript@next type acquisition approach and I wanted to give you a heads up.

**Comment by DanielRosenwasser** [comment]
Does this repro in the 2.4 RC?

**Comment by johnnyreilly** [comment]
Gimme a mo - I'll find out

**Comment by johnnyreilly** [comment]
The build is running now - answer should be yours in the output 😄

**Comment by DanielRosenwasser** [comment]
So it sounds like the RC doesn't exhibit this behavior, but something we ported over to 2.4 proper might have broken it. Do you know which specific day the build started failing?

**Comment by rbuckton** [comment]
@johnnyreilly, is this resolved as of ts-loader@2.2.1, per [this comment](https://github.com/Microsoft/TypeScript/issues/16772#issuecomment-311761959)?

**Comment by johnnyreilly** [comment]
Yes it is - closing!

**Comment by johnnyreilly** [comment]
@DanielRosenwasser  looking back through our [nightly builds](https://travis-ci.org/TypeStrong/ts-loader/builds) I think this is the one where it first appeared:

https://travis-ci.org/TypeStrong/ts-loader/builds/243198621
