### ISSUE TITLE
@types don't play nice as a dependency of a dependency when installed with pnpm

### ISSUE THREAD

**Issue by donaldpipowitch** [Microsoft/TypeScript#16611]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

**Code**

Our "build tool" uses Mocha for tests. We write our tests in TypeScript. So we have [`@types/mocha` as a dependency](https://github.com/Mercateo/ws/blob/master/package.json#L32). Because Mocha calls the tests and the tests never require Mocha directly we need to use a `tsconfig.json` like this to add Mocha global variables:

```
  "compilerOptions": {
    "types": [
      "mocha"
    ]
  }
```

**Expected behavior:**

Install our "build tool" with [pnpm](https://github.com/pnpm/pnpm) and run tests.

**Actual behavior:**

Tests can't be compiled, because `@types/mocha` can't be found. pnpm saves `@types/mocha` inside `./node_modules/.registry.npmjs.org/@types/mocha` and not `./node_modules/@types/mocha`.
I can't change `tsconfig.json` in a way that is compatible for npm, yarn and pnpm users.

(For tracking https://github.com/pnpm/pnpm/issues/801.)

**Comment by rbuckton** [comment]
Would the [`"typeRoots"`](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types) entry in tsconfig.json not work in this case?

**Comment by DanielRosenwasser** [comment]
I think this is by design - shouldn't you have mocha installed as an explicit dev dependency?

**Comment by DanielRosenwasser** [comment]
I just saw [your response to the same suggestion on the linked issue](https://github.com/pnpm/pnpm/issues/801#issuecomment-309372155). I think @rbuckton's suggestion is probably the best way forward, but an explicit dependency also makes sense to some extent. When it comes to globals, all individual packages need to effectively come to an "agreement" about which globals they're going to use.

**Comment by DanielRosenwasser** [comment]
Two thoughts here after discussing with @rbuckton:

1. Global dependencies should be pushed to the root (i.e. `@mercateo/ws` shouldn't depend on `@types/mocha`, but projects using it potentially should. The same applies to things like `@types/node`.).
2. This seems specific to pnpm, so we are marking this as External. `typeRoots` should be able to help and we can revisit the issue if we hear more feedback from users.

**Comment by donaldpipowitch** [comment]
How would `typeRoots` look like? `./node_modules/.registry.npmjs.org`? That would be specific to pnpm users.

But yeah... using `@types/mocha` as a direct dependency would be an "okay-ish" solution. Maybe even the "right" solution. I don't know.

Thank you all.
