### ISSUE TITLE
Compiler ERROR using @types/gapi -> @types/gapi/index.d.ts (243,23): ',' expected.

### ISSUE THREAD

**Issue by dpasquali** [Microsoft/TypeScript#16618]
### 

**TypeScript Version:** 2.3.4
**Code**
 /**
     * HttpRequest supports promises.
     * See Google API Client JavaScript Using Promises https://developers.google.com/api-client-library/javascript/features/promises
     */
     class HttpRequestPromise<T> {
        // Taken and adapted from https://github.com/Microsoft/TypeScript/blob/v2.3.1/lib/lib.es5.d.ts#L1343
        **then<TResult1 = T, TResult2 = never>**(
            onfulfilled?: ((response: HttpRequestFulfilled<T>) => TResult1 | PromiseLike<TResult1>) | undefined | null,
            onrejected?: ((reason: HttpRequestRejected) => TResult2 | PromiseLike<TResult2>) | undefined | null,
            opt_context?: any
        ): Promise<TResult1 | TResult2>;
    }

```ts
// A *self-contained* demonstration of the problem follows...

```

**Expected behavior:**
No errors.
**Actual behavior:**
ERROR in E:/VSProjects/MyCalendar/myCalendar/node_modules/@types/gapi/index.d.ts (243,23): ',' expected.

**Comment by DanielRosenwasser** [comment]
This isn't a self-contained repro of the issue so we wont be able to help with the issue until that's available.

**Comment by josbell** [comment]
@dpasquali did you find a solution for this issue? I'm also facing the same error.
I'm trying to deploy my angular 2 app on Ubuntu 16.4 and facing this error when running ng serve

**Comment by Spaceage1217** [comment]
same!

**Comment by kinoxhio** [comment]
+1

**Comment by erikzaadi** [comment]
+1

**Comment by kinoxhio** [comment]
I fix this error , only change in package.json line "typescript": "~2.3.1"

**Comment by Spaceage1217** [comment]
cool thanks, Ill try it out.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Comment by midhunadarvin** [comment]
Hi,
I am still getting this error. The line number has changed from 243 to 267 .
It occurs at the same line of code. Can anybody help?
```

class HttpRequestPromise<T> {
        // Taken and adapted from https://github.com/Microsoft/TypeScript/blob/v2.3.1/lib/lib.es5.d.ts#L1343
        then<TResult1 = T, TResult2 = never>(
            onfulfilled?: ((response: HttpRequestFulfilled<T>) => TResult1 | PromiseLike<TResult1>) | undefined | null,
            onrejected?: ((reason: HttpRequestRejected) => TResult2 | PromiseLike<TResult2>) | undefined | null,
            opt_context?: any
        ): Promise<TResult1 | TResult2>;
    }
```

**Comment by mhegazy** [comment]
I am unable to reproduce this locally. can you please share a self contained reproduction of the issue.
