### ISSUE TITLE
breaking change in ES5 target mode in typescript >= 2.3.0

### ISSUE THREAD

**Issue by ex37** [Microsoft/TypeScript#16613]
**TypeScript Version:**  2.4.0, 2.3.x
**Target:** ES5

**Code**

```ts
namespace App.modules {

	@Config(modules.main)

	class CompilerConfig {
		constructor(private $compileProvider) {
			$compileProvider.preAssignBindingsEnabled(true);
			$compileProvider.commentDirectivesEnabled(false);
			$compileProvider.cssClassDirectivesEnabled(false);
		}
	}

}

function Config(module: ng.IModule): Function {
	return (target: Function) => {
		return module.config(target);
	};
}

```

**Expected behavior:**
on versions 2.2.2 and older this code compiles to:
```js
var App;
(function (App) {
    var modules;
    (function (modules) {
        var CompilerConfig = (function () {
            function CompilerConfig($compileProvider) {
                this.$compileProvider = $compileProvider;
                $compileProvider.preAssignBindingsEnabled(true);
                $compileProvider.commentDirectivesEnabled(false);
                $compileProvider.cssClassDirectivesEnabled(false);
            }
            return CompilerConfig;
        }());
        CompilerConfig = __decorate([
            Config(modules.main),
            __metadata("design:paramtypes", [Object])
        ], CompilerConfig);
    })(modules = App.modules || (App.modules = {}));
})(App || (App = {}));
```

**Actual behavior:**
on versions >= 2.3 as follows

```js
var App;
(function (App) {
    var modules;
    (function (modules) {
        var CompilerConfig = (function () {
            function CompilerConfig($compileProvider) {
                this.$compileProvider = $compileProvider;
                $compileProvider.preAssignBindingsEnabled(true);
                $compileProvider.commentDirectivesEnabled(false);
                $compileProvider.cssClassDirectivesEnabled(false);
            }
            CompilerConfig = __decorate([
                Config(modules.main),
                __metadata("design:paramtypes", [Object])
            ], CompilerConfig);
            return CompilerConfig;
        }());
    })(modules = App.modules || (App.modules = {}));
})(App || (App = {}));
```
Note the `CompilerConfig = __decorate` was outside the closure, and in newer versions it's inside, which causes an error like this:
`TypeError: Cannot set property '$compileProvider' of undefined`
for the following statement `this.$compileProvider = $compileProvider;`

**Comment by DanielRosenwasser** [comment]
You said you're seeing this in 2.3? We only made this change in 2.4 as far as I recall.

**Comment by ex37** [comment]
exactly, I've seen this first in 2.3, in multiple versions.

**Comment by rbuckton** [comment]
We only moved the `__decorate` call inside of the IIFE in 2.4. I'm also not seeing how an error would be raised here, unless the `Config` decorator or some other code is calling `CompilerConfig` as a function rather than constructing it as a class. Can you review the call stack for the exception and determine how `CompilerConfig` is being called. That might provide more insight into the cause of this issue.

**Comment by ex37** [comment]
@rbuckton you are right. it was indeed moved to IIFE in 2.4, I was just getting the same error starting from 2.3.

Did a diff on `outFile` from 2.3 and 2.2, and the only difference is the following fact:
if there is a `"use strict";` statement found at the top of at least one .ts file, typescript >= 2.3 moves the `"use strict";` to the top of `outFile`, thus forcing strict mode for the whole code, no matter if `"strict": false` is explicitely set in `compilerOptions`.

**Comment by mhegazy** [comment]
> no matter if "strict": false is explicitely set in compilerOptions.

set `--alwaysStrict` to `false` instead.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
