### ISSUE TITLE
ts to wasm

### ISSUE THREAD

**Issue by apoliszk** [Microsoft/TypeScript#16617]
Will there be a tool to compile ts files to wasm files?

**Comment by chicoxyzzy** [comment]
Probably not, but you can try https://github.com/dcodeIO/AssemblyScript or https://github.com/01alchemist/TurboScript

**Comment by DanielRosenwasser** [comment]
Nope, please use the search functionality on our issue tracker in the future. See #9202 and #15837.

**Comment by DanielRosenwasser** [comment]
As a heads up, I just found this today if you're interested: https://github.com/MaxGraey/Assembleash

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
