### ISSUE TITLE
[JSDoc] Destructured parameter of type function

### ISSUE THREAD

**Issue by SergioMorchon** [Microsoft/TypeScript#16612]
**TypeScript Version:**  Shipped with production vscode

**Code**

```js
/**
 * 
 * @return {{cancel: function}}
 */
const a = () => ({
    cancel: () => {},
});
```

**Expected behavior:**
No JS errors

**Actual behavior:**
Shows an error
```
[js] Type expected.
(property) function: any
```

The inferred type is wrong (hovering `a` with vscode:
```
const a: () => {
    cancel: any;
    function: any;
}
```

*BUT* if I change `function` by `Function` it works as expected. What is the difference?

**Comment by mhegazy** [comment]
Seems to be working correctly in latest.
