### ISSUE TITLE
Mapped Types Not working correctly with arrays

### ISSUE THREAD

**Issue by thomasd16** [Microsoft/TypeScript#16614]
**TypeScript Version:**  2.3.4
**Code**

```ts
interface BaseType {
    "foo":string;
    "bar":number;
}
type MappedType = {
    [P in keyof BaseType]:BaseType[P][]
}
function addToMappedType<P extends keyof BaseType>(mapped:MappedType, key:P, value:BaseType[P]) {
    let array = mapped[key];
    array.push(value);
}
```
**Expected behavior:**
array.push should have type signature ```ts (...items:BaseType[P][])=>number``` 
**Actual behavior:**
array.push has the type signature ```ts ((...items:string[])=>number) |((...items:number[])=>number)```
And because it lacks a unique call signature it is not able to be invoked.

**Comment by jcalz** [comment]
I don't think this has much to do with arrays, but rather with the types in the mapping being evaluated eagerly or something.  This gives the same problem:

```ts
interface BaseType {
    "foo":string;
    "bar":number;
}
type WrappedType = {
    [P in keyof BaseType]: { contents: BaseType[P] }; 
}
function openPresent<P extends keyof BaseType>(present: WrappedType, key: P) {
    var v = present[key].contents;
    // next line is an error because the type of v
    // is inferred as string | number instead of BaseType[P]
    var v: BaseType[P]; 
} 
```

I'm guessing this is a design limitation?  Anyway this workaround might help:
```ts
function addToMappedType<P extends keyof BaseType>(mapped:MappedType, key:P, value:BaseType[P]) {
    let array = mapped[key] as BaseType[P][]; // explicit cast
    array.push(value); // no error now
}
```

**Comment by DanielRosenwasser** [comment]
Try this

```ts
interface BaseType {
    "foo":string;
    "bar":number;
}

type Arrayify<T> = {
    [P in keyof T]: T[P][]
}

function addToMappedType<T extends BaseType, P extends keyof T>(mapped: Arrayify<T>, key: P, value: T[P]) {
    let array = mapped[key];
    array.push(value);
}
```

**Comment by jcalz** [comment]
I don't think it's clear to a developer when the type checker discards the information about the mapping it would need for the code in OP to work.

Given
- a type function `R<>`
- a homomorphic mapped type `M<>`
```ts
type M<T> = {
    [K in keyof T] : R<T[K]>
}
```
- a type `A`
- and a generic type `K extends keyof A`,

it seems like the type `M<A>[K]` should always resolve to `R<A[K]>`, *whether `A` is generic or concrete*.  But today, this only works for generic `A` and not concrete `A`.  Is this a bug, a design limitation, or working as intended?  If it's not a bug then maybe we need some documentation to explain what's going on.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
