### ISSUE TITLE
Type guards do not work as expected when a string literal is not used

### ISSUE THREAD

**Issue by cliffkoh** [Microsoft/TypeScript#16620]
**TypeScript Version:**  2.3.4

**Code**

```ts
const Obj = {
  'hello': 'hello',
  'B': 'B'
}

enum MyEnum {
  'hello',
  'B'
}

interface A {
  type: 'hello',
  payload: { foo: boolean }
}

interface B {
  type: 'B',
  payload: { bar: boolean }
}

let foo: A | B;


if(foo.type === 'hello'){
    foo.payload.foo; // working as expected
}

if(foo.type === MyEnum[MyEnum.hello]){
    foo.payload.foo; // error, unexpected 
}

if(foo.type === Obj.hello){
    foo.payload.foo; // error, unexpected 
}
```

**Expected behavior:**
```ts

if(foo.type === MyEnum[MyEnum.hello]){
    foo.payload.foo; // expect no error
}

if(foo.type === Obj.hello){
    foo.payload.foo; // expect no error
}
```
Type guard to take effect and for code above to not throw errors.

**Actual behavior:**
```ts
if(foo.type === MyEnum[MyEnum.hello]){
    foo.payload.foo; // errors
}

if(foo.type === Obj.hello){
    foo.payload.foo; // errors
}
```

**Comment by DanielRosenwasser** [comment]
1. `MyEnum` isn't a valid enum declaration.
2. The problem is that within `Obj`, each property is mutable so TypeScript *widens* each of them to `string.

If you give an explicit type annotation of the following, the checks should work:

```ts
const Obj: {hello: "hello", "B": "B"} = {
  'hello': 'hello',
  'B': 'B'
}

const MyEnum: {hello: "hello", "B": "B"} = {
  'hello': "hello",
  'B': "B"
}
```

By the way, 2.4 will have string enums so you don't have to do the double-indexing.

**Comment by cliffkoh** [comment]
@DanielRosenwasser Apologies for that, there was a transcription issue, I've fixed the definition of myEnum.

I get your point about mutability of the object, but what about the case of Enum, which TS enforces as non-mutable? 

```ts
enum MyEnum {
  'hello',
  'B'
}

interface A {
  type: 'hello',
  payload: { foo: boolean }
}

interface B {
  type: 'B',
  payload: { bar: boolean }
}

let foo: A | B;

if(foo.type === MyEnum[MyEnum.hello]){
    foo.payload.foo; // error, unexpected 
}
```

is an error...

**Comment by cliffkoh** [comment]
Apologies again, looking at the initial issue, even the expected/actual is confusing. I've cleaned it up.

**Comment by cliffkoh** [comment]
Ping @DanielRosenwasser to review if the enum case is working as intended (and if so, why).

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
