### ISSUE TITLE
JavaScript ES5 Class Properties Always Marked as Possibly Undefined When Using strictNullChecks

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#16623]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

**Code**
For the javascript:

```js
/**
 * @param {number} numberOxen 
 */
function Wagon(numberOxen) {
    this.numberOxen = numberOxen
}

const wagon = new Wagon(1)
```

With this `jsconfig.json`

```json
{
    "compilerOptions": {
        "checkJs": true,
        "strictNullChecks": true
    }
}
```

**Expected behavior:**
The type of `wagon.numberOxen` should be `number`

**Actual behavior:**
The type of `wagon.numberOxen` is `number | undefined`

The type is correct when using an es6 class:

**Comment by sandersn** [comment]
This was fixed, I think in 2.8.
