### ISSUE TITLE
How can I install the latest version of Typescript without Internet (offline)?

### ISSUE THREAD

**Issue by sia-git** [Microsoft/TypeScript#16626]
I have Internet connection in my home and I can install the latest version of `TypeScript` with this command: **npm install -g typescript** , But unfortunately There is no Internet at my work place (in fact we are not allowed to use Internet , I know its  embarrassing!! )

Beside this I googled But It seems There is no offline installer for Typescript. My question is how can I handle this problem ?

I am totally new to npm and a step by step workaround would be so appreciated .

**Comment by cliffkoh** [comment]
GitHub isn't quite the place for Q&A, but to answer your question...

When at home, making sure you don't already have a node_modules folder, type
`npm i typescript`

Then copy the entire node_modules folder to a flash drive and copy to your work machine. To install it on your work machine, you can just copy it to the destination and invoke Typescript through `node`. You can also create a .sh or .bat file (depending on platform/terminal) in a globally accessible directory that runs `node node_modules/typescript/bin/tsc` so you can use `tsc` from the command line globally.

**Comment by DanielRosenwasser** [comment]
You can also download from the [Releases](https://github.com/Microsoft/TypeScript/releases) page (though all of those include the tests, source code, etc).

There's also other mechanisms like [npmbox](https://github.com/arei/npmbox) though I've never tried that.

**Comment by DanielRosenwasser** [comment]
@sia-git could you tell me a little bit more about what your workplace's restrictions are? For example, can you bring in a USB drive? Do you have an internal npm mirror? Bringing in @bowdenk7.

**Comment by sia-git** [comment]
@cliffkoh 
Hi and thanks for your response
I know GitHub isn't quite the place for Q&A , But really I couldn't find a reference about my problem ,
 anyway , I think, offline installation could be an important issue for many people and should be  handled.
could you please elaborate this part of your answer that was about creating a .bat file ? what is your mean by a global access directory in windows Os ? 
@DanielRosenwasser 
yes I can use a USB drive at my work place  , But we have not an internal npm mirror .
I have no idea  how its possible to create that ?

**Comment by cliffkoh** [comment]
@sia-git You should be able to find the .bat file at node_modules/.bin/tsc.bat. One way to make it globally accessible is to [add it to the PATH environment](https://www.bing.com/search?q=set+windows+path+environment+variable) variable.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
