### ISSUE TITLE
An error occurred trying to load the page.

### ISSUE THREAD

**Issue by Kaelum** [Microsoft/TypeScript#16630]
I found a previous issue #11110 that appears to again be a problem again.  Last Friday my system was working perfectly, and then today, after doing nothing more than doing a Get Latest... and opening the solution, this occurs when attempting to open any JavaScript or TypeScript file:

```
An error occurred trying to load the page.
No exports were found that match the constraint: 
	ContractName	Microsoft.CodeAnalysis.Editor.TypeScript.ScriptContexts.ITypeScriptProjectProvider
	RequiredTypeIdentity	Microsoft.CodeAnalysis.Editor.TypeScript.ScriptContexts.ITypeScriptProjectProvider
```

Right now, I'm dead in the water and I have no idea as to why.  Nothing at all has changed on my system.

**Comment by yuit** [comment]
@Kaelum  Could you try delete this folder ""C:\Users\<userName>\AppData\Local\Microsoft\VisualStudio\14.0\ComponentModelCache""

@paulvanbrenk  and @rbuckton  suggest this issue may be dued to mef cache

**Comment by Kaelum** [comment]
Hey @yuit, that worked.  Thank you so much!
