### ISSUE TITLE
Proposal to curb amount of open issues on TypeScript project

### ISSUE THREAD

**Issue by jpaulin** [Microsoft/TypeScript#16637]
Another project that I've checked quite often, had an bit of issue with a huge amount of
open issues. I'm wondering if TypeScript would benefit, management-wise, from the
automatic curbing of issues that have not received any activity here on Github for 
some period of time?

[A blog posting on NPM site about automatically curbing open issues](http://blog.npmjs.org/post/161832149430/npm-the-npm-github-issue-tracker-and-you)

**Comment by RyanCavanaugh** [comment]
We already do this (e.g. https://github.com/Microsoft/TypeScript/issues/16080#issuecomment-307447116 - that is done by a script)

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
