### ISSUE TITLE
Quick info shows method with type `any[]` at declaration and `string[]` at use

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#16643]
**TypeScript Version:**  nightly (2.5.0-dev.20170619)

**Code**

```ts
/// <reference path='fourslash.ts'/>

// @noImplicitAny: true

////interface I { m(): string[] }
////
////const i: I = {
////    /*1*/m() { return []; }
////}
////
////i./*2*/m();

verify.quickInfoAt("2", "(method) I.m(): string[]");
verify.quickInfoAt("1", "(method) m(): string[]");
```

**Expected behavior:**

Test passes.

**Actual behavior:**

`AssertionError: At 1: quick info text: expected '(method) m(): any[]' to equal '(method) m(): string[]'`

**Comment by DanielRosenwasser** [comment]
Here's what's happening here:

1. The object is contextually typed by `I`
2. The method `m` is contextually typed by the type of the property `m` within `I`
3. The return expressions of `m` are contextually typed by the return type of the `m` within `I`
4. The array literal is contextually typed, but arrays only change their type when contextually typed by a tuple type. You end up with a regular array whose element type is the widening `undefined` type.

I believe the fact that you don't get an implicit `any` is a symptom of either #241 or #7220.

cc @JsonFreeman if you're interested in chiming in.

**Comment by JsonFreeman** [comment]
Would it be reasonable for an empty array literal with a contextual type to just acquire the element type as its own? Even if the contextual type isn't a tuple

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
