### ISSUE TITLE
Module path mapping is not working in generated js files

### ISSUE THREAD

**Issue by lovedota** [Microsoft/TypeScript#16640]
**TypeScript Version:**  2.4.0 

**Code**
- I have a config

```ts
"paths": {
      "pages/*": ["./app/pages/*", "../../pages/*"],
      "helpers/*": ["./app/helpers/*", "../../helpers/*"]
}
```

**Expected behavior:**
``` js
var element_helpers_1 = require("../../helpers/element-helpers");
var manage_documents_page_1 = require("../../pages/manage-documents-page");
```

**Actual behavior:**
``` js
var element_helpers_1 = require("helpers/element-helpers");
var manage_documents_page_1 = require("pages/manage-documents-page");
```

**Comment by kitsonk** [comment]
`path` does not change the emit... it simply allows TypeScript to resolve dependencies at design time that would otherwise not be automatically resolved.  Whatever run-time module loader you are using would need to support any run-time configuration you need to reflect your desired run-time configuration.

**Comment by lovedota** [comment]
@kitsonk but actually I don't use webpack so that i cannot use `alias` for mapping, can we automatically generate the correct path from mapping table ?

**Comment by kitsonk** [comment]
Simple answer is no.  TypeScript does not re-write module names.  You will need to move the modules via external tooling or use a loader that allows mapping (e.g. like RequireJS or SystemJS).

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
