### ISSUE TITLE
Incorrect this type when casting method signature.

### ISSUE THREAD

**Issue by NaridaL** [Microsoft/TypeScript#16654]
**TypeScript Version:**  2.5.0-dev.20170619

**Code**

```ts
class MyTable {
    foo(): MyTable {
        return new MyTable()
    }
}
type ReturnsSelf = <T>(this: T) => T;
const x = new MyTable();
const y: MyTable = (x.foo as ReturnsSelf)() // void not assignable to MyTable
// `this` is actually bound correctly at runtime, even with the brackets.
```

**Expected behavior:**
No error.
**Actual behavior:**
above error

I searched for `this type method type assertion ` and ` method type cast this type ` and didn't find anything.

Some background as to why I'm even trying to do the above: 
```ts
declare class M4 {}
declare abstract class Curve {
    abstract transform(m4: M4): Curve;
}
declare abstract class XiEtaCurve extends Curve {
    transform<T extends XiEtaCurve>(this: T, m4: M4): T;
}
declare class L3 extends Curve {
    transform(m4: M4): L3;
}
declare const curve: XiEtaCurve | L3
declare const m4: M4
const res1 = curve.transform(m4) // Cannot invoke an expression whose type lacks a call 
// signature. Type '(<T extends XiEtaCurve>(this: T, m4: M4) => T) | ((m4: M4) => L3)'
// has no compatible call signatures.
const res2: XiEtaCurve | L3 = (curve.transform as (<T>(this: T, m4: M4) => T))(m4)
// Type 'void' is not assignable to type 'XiEtaCurve | L3'.
```

maybe I'm overthinking this...

**Comment by DanielRosenwasser** [comment]
The problem you're seeing is that there is no `this` parameter from which to infer - in other words, you're calling a method that's been orphaned from the instance, so TypeScript assumes the type is `void`.

Really, you may be better off with an explicit type assertion on `curve` itself.

**Comment by NaridaL** [comment]
Explicit type assertion on curve is indeed what I've gone with.

I don't entirely follow what you mean by "orphaned from the instance". `([1,2,3].slice)(1,2) == [2]`, i.e. the array is still bound to `this` when calling slice. Wouldn't it make sense that in `(x.foo as ReturnsSelf)()`, TS would infer the type of `this` from `x`?

**Comment by DanielRosenwasser** [comment]
Ah you're right - I just filed #16673.

In any case, at the point that you have a type assertion, I don't think we have any other places where after a type assertion, the type system dives back into the original expression to get some useful information. That would be strange behavior, since the assertion tells TypeScript to override the existing type.

**Comment by NaridaL** [comment]
Well arguably the underlying behavior is strange, usually you'd expect: `(whatever)()` and `const foo = whatever; whatever()` to be equivalent. As it seems a pretty outlandish edge case, do you want to close this a Bug/Won't fix?

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
