### ISSUE TITLE
Odd behavior with --noImplicitAny false --strictNullChecks true

### ISSUE THREAD

**Issue by andy-ms** [microsoft/TypeScript#16651]
Given this code:

```ts
const x = [];
x.push(1);
const y: string = x[0];
```

With various settings of `--noImplicitAny` and `strictNullChecks`, we get the following types for `x` on line 3:

| | `--noImplicitAny false` | `--noImplicitAny true` |
| --- | --- | --- |
| **`--strictNullChecks false`** | `any[]` | `number[]` |
| **`--strictNullChecks true`**  | `never[]` | `number[]` |

I would expect the lower-left corner to also be `any[]`, not `never[]`.
(Ref: https://github.com/Microsoft/TypeScript/issues/16218#issuecomment-305971027)

**Comment by andy-ms** [comment]
With `--noImplicitAny true --strictNullChecks false`, I would expect an un-annotated `[]` to fail -- and it does, but only inside another array, as in `[[]]`.
```ts
const a = []; // OK?
const b = [[]]; // Error
const c = [].map(() => []); // OK?
```

**Comment by paleo** [comment]
> I would expect the lower-left corner to also be any[], not never[].

Thank you.

With the `--strict true` and `--noImplicitAny false` compiler options, the compiler forces us to sprinkle the code with unpleasant statements:

    const arr: any[] = []
