### ISSUE TITLE
Comparison typeof with undefined (not "undefined" string) in commandParser

### ISSUE THREAD

**Issue by mihailik** [Microsoft/TypeScript#16660]
Recent PR #12336  **Use parser to parse tsconfig json instead of using Json.parse** contained an apparent bug:

```typescript
if (typeof keyText !== undefined && typeof value !== undefined) {
```

`typeof` operator can never produce `undefined`, it's guaranteed to return a string for any value.

@andy-ms [have noticed it](https://github.com/Microsoft/TypeScript/pull/12336#discussion_r120488542), but it's got lost in the large review.

Here is the link to that place on the master branch for convenience. It still compares typeof to undefined: [commandLineParser.ts#L1056](https://github.com/Microsoft/TypeScript/blob/master/src/compiler/commandLineParser.ts#L1056)

**Comment by sheetalkamat** [comment]
#16560 tracks the resolution of pending PR comments,
