### ISSUE TITLE
Omit value identifiers in function type declarations

### ISSUE THREAD

**Issue by jasonkuhrt** [Microsoft/TypeScript#16668]
This is a syntactic feature request. I often find the indentation caused by inline types does great harm to signature readability, e.g.:

```js
const fetchFromQueue = (
  queue: SQS,
  settings: Settings,
): Promise<Array<Error | Job>> =>
  // ...
```

One of the ways Haskell types are well designed is in this regard IMO. In TypeScript, what I've taken to doing is a bit of a workaround like so:

```js
type fetchFromQueue = (x: SQS, z: Settings) => Promise<Array<Error | Job>>
const fetchFromQueue: fetchFromQueue = (queue, settings) =>
  // ...
```

This helps me but it would be even better if we were not forced to write the value-level identifiers`x:` and `z:`, allowing us to simply write:

```js
type fetchFromQueue = (SQS, Settings) => Promise<Array<Error | Job>>
const fetchFromQueue: fetchFromQueue = (queue, settings) =>
```

**Comment by DanielRosenwasser** [comment]
Unfortunately it's not possible at this point because unannotated parameter names implicitly got an `any` type. Check out the discussion at #13152.

**Comment by jasonkuhrt** [comment]
@DanielRosenwasser Thanks for pointing me to the existing discussion on this topic! Is it conceivable that this could be resolved in say a future 3.x.x release series or is TS going to the way it is on this point indefinitely?

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Comment by jasonkuhrt** [comment]
That's fine I guess... heh. I would appreciate an answer to my last question though (if there is a known answer).

**Comment by kitsonk** [comment]
I doubt there is a known answer.  Especially, as noted in the other issue that this is marked a duplicate of, some of the core team felt it was worth taking the hit from a breaking change, but ultimately the change didn't occur.  But never say never...  The core team has re-evaluated things before.
