### ISSUE TITLE
Allow customizable permissions on emitted files

### ISSUE THREAD

**Issue by ORESoftware** [Microsoft/TypeScript#16667]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

**Expected behavior:**

I would expect TypeScript / tsc to output .js and .d.ts files that were readable + executable, but not writable by default. Furthermore, I would expect there to be options in tsconfig.json files, to allow end-users to choose which permissions .js and .d.ts files have.

**Actual behavior:**

TMK, by default tsc writes files that do not have the correct permissions. If tsc creates a directory, sometimes that I do not have permissions to read/write/execute files in that dir, which is very strange.

**Comment by ORESoftware** [comment]
This guy suggests using a Language Service Plugin to accomplish this

https://github.com/Microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin

is that a good idea?

https://stackoverflow.com/questions/44612118/typescripts-transpiles-files-which-are-non-executable

**Comment by DanielRosenwasser** [comment]
I don't really see what a language service plugin has to do with any of this; however, I do agree that file permissions are something we want to get involved with. I'd be willing to hear from others on the team about this though.

**Comment by DanielRosenwasser** [comment]
By the way, if you don't have permissions on output files, I wonder whether that has to do with TypeScript being installed globally with root privileges.

**Comment by ORESoftware** [comment]
@DanielRosenwasser in my case, this doesn't have anything to do with sudo.
I use NVM, and everything is installed in my user home dir. I haven't touched sudo when working with NPM in days. I frankly don't know what is causing the issue, but it's not the first time I have been baffled as to why files and folders generated by TypeScript / tsc do not have the expected permssions.

Expected:
.d.ts and .js files should be readable and executable but not writable.

folders should be readable, writable by the current user.

**Comment by ORESoftware** [comment]
So I get this error with git when running a commit

warning: unable to unlink test/src/typescript/@target/a.test.js: Permission denied
warning: unable to unlink test/src/typescript/@target/b.test.js: Permission denied


Here is the tsconfig.json file I have:

```js
{
  "compilerOptions": {
    "declaration": false,
    "outDir": "./@target",
    "baseUrl": ".",
    "paths": {
    },
    "types": [
      "node",
      "async",
      "lodash"
    ],
    "target": "es5",
    "module": "commonjs",
    "noImplicitAny": true,
    "removeComments": true,
    "allowUnreachableCode": true,
    "lib": [
      "es2015",
      "es2016",
      "es2017"
    ]
  },
  "include": [
    "./**/*.ts"
  ],
  "exclude": [
    "@target",
    "test",
    "node_modules"
  ]
}
```

so I am writing all transpiled files to an adjacent directory called @target, and that directory gets written with very restrictive permissions.

**Comment by andrew8er** [comment]
This is possibly a broader approach to #16257.

**Comment by mhegazy** [comment]
As noted in https://github.com/Microsoft/TypeScript/issues/14726 and https://github.com/Microsoft/TypeScript/issues/16257 this such file permissions modifications are outside the scope of the TS project. you can always add a post build step that sets the permissions on the files as needed.

**Comment by ORESoftware** [comment]
yeah idk about this...do you happen to know if the emitted files have the same permissions as the source files?

**Comment by mhegazy** [comment]
The compiler does not do anything with permissions neither reading them from input nor changing them on the output.

**Comment by ORESoftware** [comment]
Right so I am confused, what permissions are used then by default when files get written? Surely someone knows.
