### ISSUE TITLE
Type inference for recomposed generic object

### ISSUE THREAD

**Issue by Rokt33r** [Microsoft/TypeScript#16666]
**TypeScript Version:** 
2.4-rc

**Code**

```ts
interface Action<T extends string, P = undefined> {
  type: T
  payload: P
}

function creatActionCreators<A extends Action<A['type'], A['type']>>(type: A['type']) {
  return (payload: A['payload']): A => ({
    // Type '{ type: A["type"]; payload: A["payload"]; }' is not assignable to type 'A'.
    type,
    payload
  })
}
```

**Expected behavior:**

No error.

**Actual behavior:**

Type '{ type: A["type"]; payload: A["payload"]; }' is not assignable to type 'A'.

**Comment by DanielRosenwasser** [comment]
This is correct behavior - you don't really know whether `A` is an object that contains more than what's defined in `Action` itself. Basically, if you ever find yourself trying to synthesize a new value for a generic type, that is the sign of a potential problem.

What about the following, arguably simpler code?

```ts
interface Action<T extends string, P = undefined> {
    type: T
    payload: P
}

function createActionCreator<T extends string>(type: T) {
    return <P extends {} | undefined>(payload: P): Action<T, P> => ({
        type,
        payload
    });
}

const action = createActionCreator("CREATE_USER")(undefined);
```

**Comment by Rokt33r** [comment]
I've just wanted for typescript to check my payload. 
[I've created an example for this to typescript playground](https://www.typescriptlang.org/play/#src=interface%20Action%3CT%20extends%20string%2C%20P%20%3D%20undefined%3E%20%7B%0D%0A%20%20type%3A%20T%0D%0A%20%20payload%3A%20P%0D%0A%7D%0D%0A%0D%0Afunction%20createActionCreator%3CT%20extends%20string%3E(type%3A%20T)%20%7B%0D%0A%20%20return%20%3CP%20extends%20%7B%7D%20%7C%20undefined%3E(payload%3A%20P)%3A%20Action%3CT%2C%20P%3E%20%3D%3E%20(%7B%0D%0A%20%20%20%20type%2C%0D%0A%20%20%20%20payload%0D%0A%20%20%7D)%3B%0D%0A%7D%0D%0A%0D%0Afunction%20createActionCreator2%3CACTION%20extends%20Action%3CACTION%5B'type'%5D%2C%20ACTION%5B'payload'%5D%3E%3E(type%3A%20ACTION%5B'type'%5D)%20%7B%0D%0A%20%20return%20(payload%3F%3A%20ACTION%5B'payload'%5D)%3A%20ACTION%20%3D%3E%20(%7B%0D%0A%20%20%20%20type%2C%0D%0A%20%20%20%20payload%0D%0A%20%20%7D%20as%20ACTION)%3B%0D%0A%7D%0D%0A%0D%0Atype%20CREATE_USER%20%3D%20'CREATE_USER'%0D%0Ainterface%20CreateUserPayload%20%7B%0D%0A%20%20email%3A%20string%0D%0A%7D%0D%0A%0D%0Atype%20CreateUserAction%20%3D%20Action%3CCREATE_USER%2C%20CreateUserPayload%3E%0D%0A%0D%0Aconst%20action%20%3D%20createActionCreator%3CCREATE_USER%3E(%22CREATE_USER%22)(%7B%0D%0A%20%20name%3A%20'I%20Screwed'%2C%20%2F%2F%20No%20type%20checking%0D%0A%20%20email%3A%2012345%0D%0A%7D)%3B%0D%0A%0D%0Aconst%20action2%20%3D%20createActionCreator2%3CCreateUserAction%3E(%22CREATE_USER%22)(%7B%0D%0A%20%20%2F%2F%20name%20should%20not%20included%0D%0A%20%20name%3A%20'I%20%20Screwed'%2C%0D%0A%7D)%3B%0D%0A%0D%0Aconst%20action3%20%3D%20createActionCreator2%3CCreateUserAction%3E(%22CREATE_USER%22)(%7B%0D%0A%20%20%2F%2F%20email%20should%20be%20string%0D%0A%20%20email%3A%2012345%20%0D%0A%7D)%3B%0D%0A)

```ts
interface Action<T extends string, P = undefined> {
  type: T
  payload: P
}

function createActionCreator<T extends string>(type: T) {
  return <P extends {} | undefined>(payload: P): Action<T, P> => ({
    type,
    payload
  });
}

function createActionCreator2<ACTION extends Action<ACTION['type'], ACTION['payload']>>(type: ACTION['type']) {
  return (payload?: ACTION['payload']): ACTION => ({
    type,
    payload
  } as ACTION);
}

type CREATE_USER = 'CREATE_USER'
interface CreateUserPayload {
  email: string
}

type CreateUserAction = Action<CREATE_USER, CreateUserPayload>

const action = createActionCreator<CREATE_USER>("CREATE_USER")({
  name: 'I Screwed', // No type checking
  email: 12345
});

const action2 = createActionCreator2<CreateUserAction>("CREATE_USER")({
  // name should not included
  name: 'I  Screwed',
});

const action3 = createActionCreator2<CreateUserAction>("CREATE_USER")({
  // email should be string
  email: 12345 
});
```

So...It means I have no choice except using `as ACTION`...
Please let me know if there are another way to do.

**Comment by Rokt33r** [comment]
Recently, I've felt quite confident this is the place I should use `as SomeInterface`. 
Thank you for the replying.
