### ISSUE TITLE
Error when trying to use dynamic import with module: "es2015"

### ISSUE THREAD

**Issue by Nitive** [Microsoft/TypeScript#16675]
**TypeScript Version:**  2.4.0

**Code**

```ts
import('./utils')
  .then(({ sum }) => {
    console.log(sum(1, 2))
  })
  .catch(console.error)
```
**tsconfig.json (short version)**
```json
{
  "compilerOptions": {
    "moduleResolution": "node",
    "module": "es2015"
  }
}
```

**Expected behavior:**
No errors

**Actual behavior:**
`Dynamic import cannot be used when targeting ECMAScript 2015 modules.` with non-obvious reasons why.

[Example repository](https://github.com/Nitive/typescript-dynamic-import)

---

I get error `Dynamic import cannot be used when targeting ECMAScript 2015 modules.`
when I try to use dynamic import inside typescript project with `"module": "es2015"`
in configuration. The error message makes it clear that I can't use `import()` with
es modules but it doesn't make sense because `import()` is part of es modules.

However, it compiles correctly but throw annoing error.

I created [a repository](https://github.com/Nitive/typescript-dynamic-import) to reproduce an error.
`npm run build-ts`: compile ts files into `build/` folder.
`npm run build-webpack`: compile js into `dist/`. (Then open `index.html` to see that everything works fine)

**Comment by DanielRosenwasser** [comment]
We should just be more helpful here.

**Comment by Nitive** [comment]
Thanks, it works!

**Comment by Sebazzz** [comment]
@DanielRosenwasser Does that mean if you want to target es5 you need to transpile the outputted JS with something like babel? Is there any other way to fool Typescript into emitting `import` so Webpack can work with that?

**Comment by mhegazy** [comment]
es2015 is ES6 and not es5. if you want to target es5, just set target to es5, and module to whatever module you are using.

ES6 modules as they stand have no way to support `import()`

**Comment by Sebazzz** [comment]
Ah, right, the module compiler flag, not the target compiler flag. My bad.

**Comment by codeaid** [comment]
I always had `module` compiler option set to `commonjs` and dynamic imports worked just fine.

Updated from 2.5.3 to 2.6.1 earlier today, ran NPM build in my React application and instead of getting errors like @Nitive did I got one bundle file instead of the usual multiple chunks. Changed `module` to be `esnext` as @DanielRosenwasser suggested and that fixed the issue!

Just leaving it here for people who might have a similar issue.

**Comment by hnviradiya9** [comment]
Hey, Guys.
I still have this issue, even if I set it to `"module": "esnext"`

Anything more I need to do?

**Comment by mhegazy** [comment]
@hnviradiya9 please file a new issue with repro steps to reproduce the issue you are running into.

**Comment by tomavic** [comment]
Hi @mhegazy 
I have updated typescript to 2.7.2. I have an Injectable service file which contains this line

```
  createMetaLoader(id, folderName): Promise<any> {
    let clientfolder = ACTIVE_CLIENT;
    let promise = import("../../../assets/meta/"+ clientfolder + "/" + folderName + "/" + id + ".ts")
    return promise;
  }
```

and it throws an Error
```
ERROR in src/app/shared/meta/meta-loader.service.ts(26,19): error TS1323: Dynamic import cannot be used when targeting ECMAScript 2015 modules.
```

**Comment by mhegazy** [comment]
you have `--module ES2015`, `ES2015` does not support this form of importing. so either use `--module esnext` or `--module commonjs`.

**Comment by paulkoerbitz** [comment]
I would like to take a look at improving the error message since this keeps coming up if this is OK.

**Comment by tomavic** [comment]
@mhegazy 

In angular project created by Angular CLI, I have two files `tsconfig.json` located in root directory, and other one in src folder named `tsconfig.app` 

Should I change ` "module": "esnext" ` in both files ??

**Comment by Hotell** [comment]
@tomavic depends what you are after. If u wanna make it work for both app and unit tests then go for root. Cheers

**Comment by tomavic** [comment]
I changed it in both and now it works like charm <3 
Thanks @Hotell @mhegazy foll ya basha :D

**Comment by mhegazy** [comment]
thanks @paulkoerbitz!

**Comment by bennypowers** [comment]
"module": "esnext" is invalid in a jsconfig.json file.

```
Value is not accepted. Valid values: "commonjs", "amd", "umd", "system", "es6", "es2015".
```

**Comment by tomavic** [comment]
@bennypowers Please check your typescript version, and write it here

**Comment by facundocoto** [comment]
I try to 

"target": "es5",
"module": "esnext",

"target": "es6",
"module": "esnext",

and I have the same error. 

My typescript version is 2.8.3.

Any suggestions?

**Comment by facundocoto** [comment]
@tomavic I had to edit both, then works for me

**Comment by enjikaka** [comment]
Having issues with `import.meta.url` not working. In my source code hovering `item.meta.url`  in VSCode tells me:

`The 'import.meta' meta-property is only allowed using 'ESNext' for the 'target' and 'module' compiler options.ts(1343)`

My jsconfig.json is:
`{
  "compilerOptions": {
    "target": "esnext",
    "checkJs": true
  }
}
`

When setting adding "module": "esnext" to jsconfig.json it still errors on import.meta.url, and a warning in jsconfig.json on the module line says: 

`
Value is not accepted. Valid values: "commonjs", "amd", "umd", "system", "es6", "es2015".(1)
---
When down-level compiling, specify module code generation: 'CommonJS', 'Amd', 'System', 'UMD', 'es6', or 'es2015'.
`

**Comment by DanielRosenwasser** [comment]
@enjikaka see https://github.com/SchemaStore/schemastore/pull/602

**Comment by ferencbalogh** [comment]
ES6" and "ES2015" values may be used when targeting "ES5" or lower.

**Comment by syed-mustaqhim** [comment]
@[hnviradiya9](https://github.com/hnviradiya9) After making the change `"module": "esnext"` in `tsconfig.json`, Reload your code editor (in my case VSCode) and the error is gone

**Comment by ShemiNechmad** [comment]
Hi,
is it safe to change es2015 to esnext in tsconfig.ts file, in an Angular 8 project?
The build looks fine, however-
could it create any problems which I don't see at the moment when running it?
Thank you
