### ISSUE TITLE
How to write the jasmine specs when module: amd in tsConfig.json

### ISSUE THREAD

**Issue by usmanaridian** [Microsoft/TypeScript#16678]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

**Code**

```ts
// A *self-contained* demonstration of the problem follows...

```

**Expected behavior:**
I have tsConfig.json on the project's root level where i set the module property to equal amd , and I have a tests folder where I am trying to write the jasmine specs for my project. I don't want my jasmine specs.ts files to be translated as amd module in js. So I have added a tsConfig.json in tests sub directory and set the module to none. 
**Actual behavior:**
But now all of my ts file which are out side of the tests folder are also getting translated to js  as non-amd modules. 

Shouldn't it just impact the .ts file in tests folder ?. The reason of 2 files is I want my all javascript code to be AMD Modules but jasmine don't recognize the amd modules so I want to keep the specs javascript to be non-amd.

**Comment by mhegazy** [comment]
Stackoverflow would be a better place for such issues. I do not think ppl on this issue tracker have the expertise to answer such questions.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
