### ISSUE TITLE
why ts.transpile not compile HTMLInputElement

### ISSUE THREAD

**Issue by QuietWind** [Microsoft/TypeScript#16677]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)
v2.3.4
**Code**
``` ts
const lanNode: HTMLInputElement = <HTMLInputElement>document.getElementById("LanguageCode");

```
// A *self-contained* demonstration of the problem follows...

```

**Expected behavior:**
I want to use `ts.transpile` compile ts code to javascript. 

compile code is:
```ts
const defaultOptions = ts.getDefaultCompilerOptions();
const tsConfig: ts.CompilerOptions = {
  ...defaultOptions,
  jsx: ts.JsxEmit.Preserve,
  target: ts.ScriptTarget.ES2015,
  sourceMap: false,
  module: ts.ModuleKind.CommonJS
};

ts.transpile(`const lanNode: HTMLInputElement = <HTMLInputElement>document.getElementById("LanguageCode");
`, tsConfig);
```
result is:
const lanNode = <HTMLInputElement>document.getElementById("LanguageCode");</>;
`
**Actual behavior:**
i want to gen code like:
```js
const lanNode = document.getElementById("LanguageCode");
```
please help me !

**Comment by ikatyang** [comment]
It seems you should use `as HTMLInputElement` instead of `<HTMLInputElement>`.

```ts
const lanNode: HTMLInputElement =
  document.getElementById("LanguageCode") as HTMLInputElement;
```

`<xyz>` is considered a HTML tag in jsx/tsx file.

**Comment by RyanCavanaugh** [comment]
You specified a JSX mode and didn't specify a filename, so the compiler thinks you're trying to transpile a .tsx file. Either specify a filename ending with .ts, or specify JSX mode = None (this is the default; you can just remove that from your config file).

Docs:

https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#transpiling-a-single-file

>  If the file name is omitted, then compiler will check if the jsx options is specified. If it is set and is not JsxEmit.None, then source text will be interpreted as '.tsx'.

**Comment by QuietWind** [comment]
update ts.transpile  to function ts.transpileModule, and add filename resolve this problem.

thx @RyanCavanaugh
