### ISSUE TITLE
Provide a way to enforce a 0 return code from 'tsc'

### ISSUE THREAD

**Issue by cncolder** [microsoft/TypeScript#16674]
**TypeScript Version:**  2.3.4

**Code**

```bash
tsc -p client 2>&1 && compile another project
tsc -p client >/dev/null 2>&1 && compile another project
```

**Expected behavior:**

In a real project. Sometime I cannot fix all ts error. But it's ok to emit js files.

The `tsc` command seem always return error code.

**Actual behavior:**

```bash
tsc -p client 2>&1 || compile another project
```

**Comment by DanielRosenwasser** [comment]
Is the problem that you want to be able to get a `0` return code so that you can continue build scripts? I'm assuming so and changing this issue's title to reflect that.

**Comment by DanielRosenwasser** [comment]
CC @bowdenk7

**Comment by cncolder** [comment]
Yes @DanielRosenwasser. That's what I'm saying. Sorry for my bad English.

**Comment by DanielRosenwasser** [comment]
No worries! Thanks for filing this issue, this is something that we've experienced ourselves as well.

**Comment by gcnew** [comment]
Is adding `|| true` on the command line good enough?

e.g.
```bash
tsc -p client 2>&1 || true && compile another project
```

**Comment by cncolder** [comment]
@gcnew This worked. But after you resolve all ts problem. `tsc` will return 0.

**Comment by DanielRosenwasser** [comment]
@gcnew It doesn't work in Windows which is the real pain-point in our experience.

**Comment by RyanCavanaugh** [comment]
Declining due to shortage of demand
