### ISSUE TITLE
interface error: class implementing interface via object assignment in constructor

### ISSUE THREAD

**Issue by Eraldo** [Microsoft/TypeScript#16672]
**TypeScript Version:**  2.4.0

**Code**

```ts
interface MyClassObject {
  foo: string;
}

export class MyClass implements MyClassObject {
  constructor(myClassObject: MyClassObject) {
    Object.assign(this, myClassObject);
  }
}
```

**Expected behavior:**

No error since the return type of `Object.assign(this, myClassObject)` should match the interface MyClassObject.

Conceptually I think it would make sense to deduct that the interface must be implemented if all needed properties of the constructors `MyClassObject` are added by assignment -- which is the case.

**Actual behavior:**

I get typescript errors telling me that MyClass incorrectly implements MyClassObject interface.

**Workaround:**

I know that as a workaround I could add the fields to the class once more:
```ts
interface MyClassObject {
  foo: string;
}

class MyClass implements MyClassObject {
  foo: string;
  constructor(myClassObject: MyClassObject) {
    return Object.assign(this, myClassObject);
  }
}
```

**Comment by DanielRosenwasser** [comment]
I don't think that this is something we could plausibly track. We don't currently have a way of encoding side-effects.

**Comment by Eraldo** [comment]
I see.
Could I turn it around somehow and create the interface from the class?
(so that I only have one place to define the properties)
Would something like keyof work here?

**Comment by arturkulig** [comment]
if you `implement` a class it should work as implementing an interface

**Comment by Eraldo** [comment]
@arturkulig Are you suggesting to remove the interface completely?
Arn't there use cases where I cannot use the class where I can use interfaces?

**Comment by arturkulig** [comment]
Well... if your interface was meant to be equal to class type - yes. Though, I usually create interfaces that are just a part of class(es) implementing it.

**Comment by Eraldo** [comment]
@DanielRosenwasser Any other suggestions for getting rid of duplicated property definitions?

**Comment by Eraldo** [comment]
In some functions in my code I pass around objects that have the same properties as my classes .. however they are just data objects and do not really have any interactive purposes (methods).
Declaring these input parameters as MyClass (class) type instead of MyClassObject (interface) type would suggest I could 'do' things with them, which is not the case. That is why I added both MyClassObject and MyClass.
Does that make sense to you?

So, if it does, my question is how can I create a class from an interface or an interface from a class without having to define the properties twice?

**Comment by Eraldo** [comment]
If I decide to remove the interface, how can I rewrite this:
```ts
export class MyClass implements MyClassObject {
  foo: string;
  bar: string;
  ...

  constructor(myClassObject: MyClassObject) {
    Object.assign(this, myClassObject);
  }
}
```
So that I don't have to repeat the properties in the constructor?

**Comment by arturkulig** [comment]
I get it. I'm not aware of way to do that.

Easiest solution would be to drop a class and create a regular function that would return a union type between interfaces.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
