### ISSUE TITLE
Suggestion: add the ability to dynamically name anonymous classes

### ISSUE THREAD

**Issue by voodooattack** [Microsoft/TypeScript#16670]
**Code**

```ts
    const model = class extends Model {
        ...
    };
    model.constructor.name = blueprint.name; // 
```

**Expected behavior:**

TypeScript should provide a way to rename anonymous classes.

**Actual behavior:**

```
src/model.ts(24,24): error TS2540: Cannot assign to 'name' because it is a constant or a read-only property.
```

**Suggested syntax:**
```ts
    const model = class [blueprint.name] extends Model {
        ...
    };
```

**Comment by Kovensky** [comment]
It's defined to not be writable, but it is configurable.

```js
Object.defineProperty(model.constructor, 'name', { configurable: true, value: blueprint.name })
```

Note that it is not configurable in some pre-ES2015 browsers and may throw on assignment.

**Comment by RyanCavanaugh** [comment]
Suggestions like this should go to TC39. We didn't design anonymous classes and aren't keen to add random runtime features on top of an expression-level construct.

**Comment by voodooattack** [comment]
@RyanCavanaugh I understand that the recommendation might have been better presented elsewhere, but why does TypeScript not allow something like this for example:

```ts
      class T extends Model {
        static readonly name = blueprint.name;
      }
```

I think it should be allowed.

**Comment by RyanCavanaugh** [comment]
@voodooattack let's try the emit for that
```js
class T { }
T.name = "blue";
console.log(T.name);

> T
```
The spec defines `T.name` to be immutable. We can't change it.

**Comment by Kovensky** [comment]
This will work at runtime because of how getters are installed, but at a performance loss:

```ts
class T {
  static get name () { return 'blue' }
}
```

Just call Object.defineProperty yourself. Note that you need to check if the name property exists and if it is configurable. JSC at one point implemented an older version of the spec where Function#name was not configurable.

**Comment by RyanCavanaugh** [comment]
Do we just need to remove the error about conflicting with `Function.name`, then?

**Comment by Kovensky** [comment]
@RyanCavanaugh it _only_ works if it's a getter, and then only in post-ES5 engines.
