### ISSUE TITLE
Improved types map behavior

### ISSUE THREAD

**Issue by RyanCavanaugh** [Microsoft/TypeScript#16685]
* Add new tsserver commandline option `--typesMapLocation filename.json`
* Types map looks like this:
```
{
  "typesMap": {
    /* the current hardcoded thing */
  }
  "simpleMap": ["jquery", "lodash", "leftpad", ...]
}
```
* Apply this logic to configured and inferred projects (not just external)

/cc @billti

**Comment by billti** [comment]
Sounds good. Should only be used when Auto-Type-Acquisition is on.

**Comment by DanielRosenwasser** [comment]
For the benefit of others on the team, what does this do?

**Comment by RyanCavanaugh** [comment]
Two main things:
 * Allows users to drop in a new `typeMap.json` file if they're having problems with large .js files messing with their VS memory consumption
 * Fixes an issue where ATA wasn't working on .min.js files
