### ISSUE TITLE
Cannot infer right type from overload functions

### ISSUE THREAD

**Issue by twoeo** [Microsoft/TypeScript#16689]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)
2.4.0

**Code**

```ts
interface Test{
    show(): string;
    show(arg: (a:string)=>void): void;
    show(arg: (a:string, b:number)=>void): void;
}

declare let t:Test;

t.show();
t.show(a=>{});
t.show((a,b)=>{});
```

**Expected behavior:**
Compile success. 
Both `a=>{}` and `(a,b)=>{}` can infer right type to `a` and `b` instead of `implicitly has an 'any' type`

**Actual behavior:**
> index.ts(11,9): error TS7006: Parameter 'a' implicitly has an 'any' type.
index.ts(11,11): error TS7006: Parameter 'b' implicitly has an 'any' type.

**Comment by kitsonk** [comment]
[Don't over complicated things](http://www.typescriptlang.org/play/#src=interface%20Test%7B%0D%0A%20%20%20%20show(arg%3F%3A%20(a%3Astring%2C%20b%3F%3Anumber)%3D%3Evoid)%3A%20void%3B%0D%0A%7D%0D%0A%0D%0Adeclare%20let%20t%3ATest%3B%0D%0A%0D%0At.show()%3B%0D%0At.show(a%3D%3E%7B%7D)%3B%0D%0At.show((a%2C%20b)%20%3D%3E%20%7B%20%7D)%3B%0D%0A):

```ts
interface Test{
    show(arg?: (a:string, b?:number)=>void): void;
}

declare let t:Test;

t.show();
t.show(a=>{});
t.show((a, b) => { });
```

**Comment by RyanCavanaugh** [comment]
Duplicate #11936

Note: Don't mark callback parameters as optional
```ts
interface Test{
    show(arg?: (a:string, b:number)=>void): void;
}

declare let t:Test;

t.show();
t.show(a=>{});
t.show((a, b) => { });
```

**Comment by kitsonk** [comment]
> Note: Don't mark callback parameters as optional

Ooops, sorry, yes I forgot.
