### ISSUE TITLE
Importing files from outside the tsconfig.json directory changes the output folder structure

### ISSUE THREAD

**Issue by Arlen22** [Microsoft/TypeScript#16683]
Something I have been trying to do several times lately is share type definitions and code between related projects, such as a client and server project where I have defined the types for the JSON that gets transferred between them and would like to use the same files instead of copying changes back and forth between the two projects. I normally output the `js` files right next to the `ts` files, as I have no need to do otherwise on the server. The client gets bundled using the Angular CLI, so it is unrelated.

**TypeScript Version:**  2.3.4

**Code**

```ts
import * as test from './cousin';
```

And in tsconfig.json

```json
        "outDir": ".",
        "rootDirs": [
            "../uncle",
            "."
        ],
```

**Expected behavior:**
I expect to see an output folder structure like this:

 - `me.ts`
 - `me.js`
 - Maybe `cousin.js`, or nothing. I could expect cousin.js to be built separately.

**Actual behavior:**
 - `me.ts`
 - `parent/`
    - `me.js`
 - `uncle/`
    - `cousin.js`

**Comment by Saulzi** [comment]
I had the same some time ago.. By design.. See

https://github.com/Microsoft/TypeScript/issues/9786

**Comment by mhegazy** [comment]
Please see https://github.com/Microsoft/TypeScript/wiki/FAQ#why-does---outdir-moves-output-after-adding-a-new-file

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
