### ISSUE TITLE
Partial type passes for values that are strings and incorrect objects

### ISSUE THREAD

**Issue by luke-john** [Microsoft/TypeScript#16691]
**TypeScript Version:**  2.3.4

**Code**

```ts
interface Foo {
    key: string
    value: string
}

const shouldFail0: Partial<Foo> = '' // does not fail
const shouldPass0: Partial<Foo> = {} // does not fail
const shouldFail1: Partial<Foo> = {
    ker: ''
} // fails

interface Bar {
    (): Partial<Foo>
}

const shouldFail2: Bar = () => ({
    car: ''
}) // does not fails
const shouldFail3: Bar = () => ('') // does not fails
const shouldFail4: Bar = () => {
    return undefined
} // fails
```

I've setup a [typescript playground example](typescript-playground-example).

**Expected behavior:**

Partial type should not pass for values that are strings or incorrect objects.

**Actual behavior:**

Partial type passes for values that are strings and incorrect objects.

[typescript-playground-example]: https://www.typescriptlang.org/play/#src=interface%20Foo%20%7B%0D%0A%20%20%20%20key%3A%20string%0D%0A%20%20%20%20value%3A%20string%0D%0A%7D%0D%0A%0D%0A%0D%0Aconst%20shouldFail0%3A%20Partial%3CFoo%3E%20%3D%20''%20%2F%2F%20does%20not%20fail%0D%0A%0D%0Aconst%20shouldPass0%3A%20Partial%3CFoo%3E%20%3D%20%7B%7D%20%2F%2F%20does%20not%20fail%0D%0A%0D%0Aconst%20shouldFail1%3A%20Partial%3CFoo%3E%20%3D%20%7B%0D%0A%20%20%20%20ker%3A%20''%20%2F%2F%20fails%0D%0A%7D%0D%0A%0D%0Ainterface%20Bar%20%7B%0D%0A%20%20%20%20()%3A%20Partial%3CFoo%3E%0D%0A%7D%0D%0A%0D%0Aconst%20shouldFail2%3A%20Bar%20%3D%20()%20%3D%3E%20(%7B%0D%0A%20%20%20%20car%3A%20''%0D%0A%7D)%20%2F%2F%20does%20not%20fails%0D%0A%0D%0A%0D%0Aconst%20shouldFail3%3A%20Bar%20%3D%20()%20%3D%3E%20('')%20%2F%2F%20does%20not%20fails%0D%0A%0D%0Aconst%20shouldFail4%3A%20Bar%20%3D%20()%20%3D%3E%20%7B%0D%0A%20%20%20%20return%20undefined%0D%0A%7D%20%2F%2F%20fails%0D%0A

**Comment by ikatyang** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/16333, fixed by https://github.com/Microsoft/TypeScript/pull/16343 (v2.4.1 milestone).

For now, you can try `typescript@next` to get the following result:

![image](https://user-images.githubusercontent.com/8341033/27440776-4edb86e8-579e-11e7-80dc-96fb8b1670f5.png)

**Comment by luke-john** [comment]
Just updated to `2.4.1` and it's all working now.

Cheers.
