### ISSUE TITLE
Add a way to get a typed AST

### ISSUE THREAD

**Issue by jslegers** [Microsoft/TypeScript#16692]
I understand that TypeScript [is not intented to be compiled to eg. asm.js or C/C++](https://github.com/Microsoft/TypeScript/issues/375), but the ability to export a language like Flow or TypeScript to typed AST in some way or another would allow another team of developers to use that as a basis for "TypeScript to C/C++", "TypeScript to asm.js" or "TypeScript to whatever" conversions, as suggested in [this issue for Flow](https://github.com/facebook/flow/issues/248). 

The short term benefit would obviously be small, but the large term benefit would be quite significant, as it would basically provide a pluggable interface that allows (subsets of?) TypeScript to be converted to any language that is sufficiently compatible. In theory, it would allow TypeScript - when combined with third party plug-ins" - to be used as some kind of "convert to anything" kind of language, which is what many people are trying to use JavaScript for but for which JavaScript (due to the lack of static typing) happens to be less suitable than TypeScript or Flow. And this, with - I imagine - little effort from the TypeScript core devs, as exporting the typed AST that is used internally would be all they would have to do to make this possible.

Is there any chance you might consider exporting the typed AST?

**Comment by kitsonk** [comment]
You can access the AST, including all the types, via the language services, and you can then in theory emit whatever you wanted.

**Comment by jslegers** [comment]
@kitsonk 

Now, that's interesting. Can you think of any online source that to recommend on accessing the AST through the language services?
As far as I can tell, the [official docs](https://github.com/Microsoft/TypeScript/wiki/Using-the-Language-Service-API) are very limited...

**Comment by kitsonk** [comment]
[This has the best official examples](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API), but yes, the documentation is not overly strong.  Taking a look at [vscode's integration](https://github.com/Microsoft/vscode/tree/master/extensions/typescript/src) can be helpful as well as [tslint](https://github.com/palantir/tslint/tree/master/src/language/walker) has integration to the language services as well.

**Comment by jslegers** [comment]
@kitsonk

Thanks!

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
