### ISSUE TITLE
Typescript compiler in VS 2017 does not check out .map and .js if checked into Source Control

### ISSUE THREAD

**Issue by AndrePageot** [microsoft/TypeScript#16690]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

I am in visual studio 2017 professional
I have a solution containing several projects, most of which are dll libraries
I have a website project that I added through right clicking solution > add existing website > then browsing to where the website folder was

The solution is in source control with TFS 2015

The website project has default setting for Typescript configured, ie auto compile on save

When I open a .ts file to edit, I can make changes, if the file is checked in it will check it out automatically, this is expected by design of VS

HOWEVER
When I save the changes, if the .map and .js are checked into source control, the typescript auto compiler does NOT check the files out, and therefore does NOT write the .map and .js file. 

ALSO there is no log anywhere to tell me that nothing has happened

```ts
// A *self-contained* demonstration of the problem follows...
```

**Expected behavior:**
check out the files and compile the .map and .js
 **Actual behavior:**
does nothing, and no log of the event failure

**Comment by tobijuthomas** [comment]
I am also facing the same issue. .js files and .map files once checked in TFS, saving the .ts files does not check out or update the .js/.map files.

**Comment by mikisr** [comment]
This issue affects us as well. Visual Studio 2017 15.2 (26430.16), Typescript 2.2.3.

**Comment by peha123** [comment]
The bug seems to persist even in Visual Studio 2017 15.3.3. Now it's a blocker for us..

**Comment by PrisonerZERO** [comment]
What is the correct setup/solution for this?

**Comment by jon001** [comment]
It's nearly 2020 and I still have to remember to check out the .js under each .ts that I'm editing. Is there a plan to fix this or am I using obsolete tools?

**Comment by atkeranov** [comment]
Hey guys, can someone give more info on the state of this. Is it planned? Can we expect it to be fixed in the foreseeable future?

**Comment by jon001** [comment]
In case this is of any use to anyone else, it occurred to me that the generated .js and .js.map needn't be under source control (in fact, perhaps *shouldn't* be) in my configuration since they're rebuilt when necessary on solution build. Having removed these from source control there's no longer a problem.
It is slightly annoying that I can no longer nest these under the TS file (when nested their source control status can no longer be independently set) but I can live with that.

**Comment by RyanCavanaugh** [comment]
Closing as we don't think we're going to change this behavior at any point. Checking in build outputs is... confusing? from the generating tool's perspective, and it's not clear that checking out those outputs *automatically* would be the right thing to do. We'd recommend excluding these files from source code control consideration if you're using a checkout-based source control system.
