### ISSUE TITLE
compiler freezes in an "edge case"

### ISSUE THREAD

**Issue by dzsodzso63** [Microsoft/TypeScript#1669]
This code never compiles, no error, just frozen tsc (even in playground):

```typescript
class B {
	static staticMethod<U>():C<U> {
		return B.method();
	}
}
interface A<U> {
	strangeThing(): A<Array<U>>;
}
interface C<U> extends A<U> {
}
class D {
	private a: C<Array<string>>;
	constructor() {
		this.a = B.staticMethod();
	}
}
```

**Comment by RyanCavanaugh** [comment]
Looks to be fixed in the master branch. Completes quickly and issues the error

 > a.ts(3,18): error TS2339: Property 'method' does not exist on type 'typeof B'.
