### ISSUE TITLE
non-working case of inference on a generic function reference

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#16708]
```typescript
export function idOf<T extends { id: U }, U>(value: T): U {
    return value.id;
}

const ids = [{ id: 1 }].map(idOf); // <-- expected ids of type number[], actual {}[]
```

**Comment by aleksey-bykov** [comment]
@ahejlsberg you might want to look

**Comment by ahejlsberg** [comment]
This is working as intended. Constraints do not participate in type inference, so we make no inferences for `U` in your example. It works if you write it this way:

```ts
export function idOf<U>(value: { id: U }): U {
    return value.id;
}

const ids = [{ id: 1 }].map(idOf);  // number[]
```

Think of constraints as simply an extra type check that is performed after the actual types have been determined.

**Comment by aleksey-bykov** [comment]
we use exactly what you said and it works in 95% of our cases, however there are a few situations where the unification process restrains a full type to a single property type because of using an accessor function defined this way

consider 

### using constraints

![image](https://user-images.githubusercontent.com/937933/27495297-69bb7ed8-581f-11e7-941a-0e5981dada99.png)

![image](https://user-images.githubusercontent.com/937933/27495335-8f6e494e-581f-11e7-8748-374b06ca6cf8.png)


### not using constraints

![image](https://user-images.githubusercontent.com/937933/27495404-c134aca2-581f-11e7-8159-a3aaa9acb83f.png)

![image](https://user-images.githubusercontent.com/937933/27495439-e6085e16-581f-11e7-92c3-a9c05d4e2e80.png)


PS
sorry for awkward code snippets, i will work on a self-contained example in meanwhile to illustrate it better, i guess my point here is that these 2 ways of getting a value of a property of an object aren't equivalent
