### ISSUE TITLE
Formatter indents interface to align with comment asterisks

### ISSUE THREAD

**Issue by ghost** [microsoft/TypeScript#16711]
**TypeScript Version:**  nightly (2.5.0-dev.20170623)

**Code**

```ts
/**
 * Comment
 */
export interface I {}
```

Select `export ` and cut.
Then paste it again.

**Expected behavior:**

Back where you started.

**Actual behavior:**

```ts
/**
 * Comment
 */
 export interface I {}
```

Also, my vscode settings are:
```json
"editor.formatOnType": false,
"editor.formatOnPaste": false,
"typescript.format.enable": false,
```
so this shouldn't be happening at all?

**Comment by andy-ms** [comment]
A possibly related problem: This is more obvious if you use tabs.
```ts
function f() {
	const x = 1;
	return x;
}
```

Go to the beginning of line 2 and insert a newline.
The result is:
```ts
function f() {

		const x = 1;
	return x;
}
```

I would expect the `const` to remain at the same indent level.
(If you indent with 4 spaces, the `const` will be indented 5 spaces.)

**Comment by andy-ms** [comment]
Another problem:
```ts
function f(x) {
	return x === 1
		|| x === 2;
}
```
Navigate to just right of the `}`, hit enter, get:
```ts
function f(x) {
	return x === 1
		|| x === 2;
	}
```

**Comment by andy-ms** [comment]
Similar:
```ts
type U =
    | string
    | number;
```
Hit enter and type something, and it will be indented.
