### ISSUE TITLE
Different interface behavior with an object variable vs. direct object

### ISSUE THREAD

**Issue by ststeiger** [Microsoft/TypeScript#16712]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

**Code**

```ts
// A *self-contained* demonstration of the problem follows...

interface ICookieOptionsTest
{
    name?: string;
    value?: string;
    secure?: boolean;
    session?: boolean;
    sameSite?: boolean;
}


var testOptions =
    {
         name: "foo"
        ,session: true
        ,LoLspellingMistake: true
    };



var notme1: ICookieOptionsTest & object = testOptions;
var notme2: ICookieOptionsTest & object = 
{
     name: "foo"
    ,session: true
    ,LoLspellingMistake: true
};

```

**Expected behavior:**
The line notme1 = variable outputs an error. 
Type "any" should not be assignable to ICookieOptionsTest & object ...

**Actual behavior:**
The line notme1 outputs no error, but notme2 does. 
Type "any" is assignable to ICookieOptionsTest & object ...

**Comment by andy-ms** [comment]
This is because `testOptions` has no type declaration, so we make up a type for it. This type is technically assignable to `ICookieOptionsTest` because it has at least one property in common.
The `& object` is having no effect here.
You might be interested in palantir/tslint#2581.

**Comment by DanielRosenwasser** [comment]
Actually, that's not quite the reason. Check out the section we have on [*Excess Property Checking* in our handbook](https://www.typescriptlang.org/docs/handbook/interfaces.html#excess-property-checks).

**Comment by ststeiger** [comment]
Actually, this happens as well if you add the type to the testOptions  variable.

**Comment by andy-ms** [comment]
Huh? Wouldn't that make it equivalent to the `notme2` example? What type did you add?

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
