### ISSUE TITLE
JSX Spread Type Safety

### ISSUE THREAD

**Issue by ccorcos** [Microsoft/TypeScript#16725]
**TypeScript Version:**  2.2.2, 2.3.4

**Code**

```ts
class Test extends React.Component<{ x: number }, {}> {}

<Test /> // Error 👍
<Test x={1} /> // No Error 👍
<Text y={1} /> // Error 👍
<Test x={1} y={2} /> // Error 👍
<Test {...{ x: 1 }} /> // No Error 👍
<Test {...{ y: 2 }} /> // Error 👍
<Test {...{ x: 1, y: 2 }} /> // No Error 👎
```

**Expected behavior:**

I would expect extra props passed in an object spread to throw a type error. Otherwise I don't know if I'm passing props that are lost in translation.

**Actual behavior:**

I don't get a type error.

**Comment by devdoomari** [comment]
but what about codes that actually make use of that property?
eg.

```typescript
const someProps = Object.assign({}, defaultProps, data1, data2);
...
<Test {...someProps} />
```
?

**Comment by mohsen1** [comment]
@sandersn #16530 didn't fix TSX spread?

**Comment by sandersn** [comment]
It's in release 2.4 @ccorcos can you try `typescript@next` or `typescript@rc` ?

**Comment by ccorcos** [comment]
I'll try it out and get back you -- thanks for the help!

**Comment by mohsen1** [comment]
I saw this working in 2.4 for JSX this weekend.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
