### ISSUE TITLE
tsserver returns error that does not exist for generic type constraint

### ISSUE THREAD

**Issue by mattacosta** [Microsoft/TypeScript#16722]
**TypeScript Version:**  2.3.4 / 2.4.0

**Code**

```ts
// Stripped down version of some actual code.

interface A {
  withProperty<T extends A>(): T;
}

class B implements A {
  public withProperty(): B {
    return new B();
  }
}

class Factory {
  public create<T extends A>(x: T): T {
    // TS2322: Type 'A' is not assignable to type 'T'.
    return x.withProperty();
  }
}
```

**Expected behavior:**
No error.

**Actual behavior:**
VS Code ends up showing squigglies on the return statement of the `create` method, however compiling produces no error, and the error temporarily disappears until a future change is made.

**Comment by DanielRosenwasser** [comment]
What version of VS Code are you using? Does it have an updated language server?

**Comment by mattacosta** [comment]
I was using the 1.13.1 build of VS Code. Using the 1.14 insiders build (with typescript 2.4.1) showed an error on the declaration of `B` on line 7 though, so I uninstalled my global version of typescript to make sure that wasn't an issue and tested a few versions by building from the command line:

2.3.4 - error on return statement
2.4.0 - no errors, compiles fine
2.4.1 - error on class declaration
typescript@next - same as 2.4.1

Looks like whatever it was got changed, so going to close this issue.
