### ISSUE TITLE
failed case of generic function inference

### ISSUE THREAD

**Issue by zpdDG4gta8XKpMCd** [microsoft/TypeScript#16729]
```typescript

export function parseAttributeAt<T, E>(
    html: HTMLElement,
    name: string,
    parseOrElse: (
        value: string,
        orElse: (reason: string) => E
    ) => T | E,
    orElse: (reason: string) => E
): T | E {
    if (html.hasAttribute(name)) {
        return orElse('There is no at \'' + name + '\'.');
    } else {
        const value = html.getAttribute(name);
        if (value === null) {
            return orElse('Value is null at \'' + name + '\'.');
        } else {
            const parsed = parseOrElse(
                value,
                reason => orElse('Unable to read a value at \'' + name + '\'. ' + reason)
            );
            return parsed;
        }
    }
}

function parseNumberOrElse<E>(value: string, orElse: (reason: string) => E): number | E {
    const parsed = parseInt(value, 10);
    if (isNaN(parsed)) return orElse('Value \'' + value + '\' is not a number.');
    if (!isFinite(parsed)) return orElse('Value \'' + value + '\' is not finite.');
    return parsed;
}

function fail(reason: string): never {
    throw new Error(reason);
}
declare const element: HTMLElement
const value = parseAttributeAt(  // <-- expected result of number, actual {}
    element, 'test', parseNumberOrElse, fail
);
```

@ahejlsberg might be of interest for you

**Comment by sylvanaar** [comment]
This seems like an order of operations issue.

In order to resolve the type of parseAttributeAt you need to evaluate its return, but you passed it a generic function parseNumberOrElse which needs parseAttributeAt to infer its type first before parseNumberOrElse can have its type inferred. 

Seems like you would require multiple passes to resolve these types.

**Comment by aleksey-bykov** [comment]
not sure i am following from a layman standpoint all type arguments are known at the call site:
- E is known to be `never` from the `fail` being an argument to `orElse`
- T is known to be `number` from the `parseNumberOrElse`
the hard part, as i see it, is the return type of the `parseOrElse` parameter which is `T | E`  which might pose a problem of associating `T` with `number` and `E` with `never` (and not vise versa)

**Comment by aleksey-bykov** [comment]
it's more of a practical question, i am willing to rewrite this code any way necessary as long as i don't have to specify type arguments explicitly

**Comment by aleksey-bykov** [comment]
there is a "workaround" of "fixating" `E` before exposing it `T | E`, but it looks rather extremely awkward:
```typescript

export function parseAttributeAt<E>(
    html: HTMLElement,
    name: string,
    orElse: (reason: string) => E
): <T>(
        parseOrElse: (
            value: string,
            orElse: (reason: string) => E
        ) => T | E
    ) => T | E {
    
    return function <T>(parseOrElse: (
        value: string,
        orElse: (reason: string) => E
    ) => T | E) {
        if (html.hasAttribute(name)) {
            return orElse('There is no at \'' + name + '\'.');
        } else {
            const value = html.getAttribute(name);
            if (value === null) {
                return orElse('Value is null at \'' + name + '\'.');
            } else {
                const parsed = parseOrElse(
                    value,
                    reason => orElse('Unable to read a value at \'' + name + '\'. ' + reason)
                );
                return parsed;
            }
        }
    };
}

function parseNumberOrElse<E>(value: string, orElse: (reason: string) => E): number | E {
    const parsed = parseInt(value, 10);
    if (isNaN(parsed)) return orElse('Value \'' + value + '\' is not a number.');
    if (!isFinite(parsed)) return orElse('Value \'' + value + '\' is not finite.');
    return parsed;
}

function fail(reason: string): never {
    throw new Error(reason);
}
declare const element: HTMLElement
const value = parseAttributeAt(  // <-- works! value is number
    element, 'test', fail
)(parseNumberOrElse);
```

such an unnecessary complication without obvious reasons, anyone who sees this code would call the cops on me

**Comment by sylvanaar** [comment]
Inference doesn't work on union types, which is why you get {}, how would it know how to relate the types in the union(s)

It seems like inference really only makes one attempt to resolve the types, if information is missing because it hasn't yet been calculated (like the return type of .parseNumberOrElse) then you get {}

We don't know the return value of parseNumberOrElse at the parseAttributeAt call site, it requires us to know that fail is passed as the orElse parameter of parseAttributeAt then passed to parseNumberOrElse at its call site, only then would we know the return value and be able to fill in the value of the generic return type of the function parameter. 

Here is a clearer way of doing it at the call site:

`const value = parseAttributeAt( 
    element, 'test', (reason:string) => parseNumberOrElse("test", fail), fail
);`

**Comment by RyanCavanaugh** [comment]
@aleksey-bykov can you get this down to a minimal repro first, please?

**Comment by aleksey-bykov** [comment]
@RyanCavanaugh yes, here is tyhe original problem:
```
declare function f<T, E>(g: (o: () => E) => T | E, o: () => E): T | E;
declare function o(): never;
declare function g<E>(o: () => E): number | E;
var result = f(g, o); // <-- expected number, actual {}
```

### workaround 1: awkward yet still in point free style
```
declare function f<E>(o: () => E): <T>(g: (o: () => E) => T | E) => T | E;
declare function o(): never;
declare function g<E>(o: () => E): number | E;
var result = f(o)(g); // <-- number as expected
```

### workaround 2: lame manual annotations
```
declare function f<T, E>(g: (o: () => E) => T | E, o: () => E): T | E;
declare function o(): never;
declare function g<E>(o: () => E): number | E;
var result = f<number, never>(g, o); // <-- number as requested
```

**Comment by RyanCavanaugh** [comment]
Function returns `number` as expected now
