### ISSUE TITLE
checkJs should imply allowJs

### ISSUE THREAD

**Issue by graingert** [microsoft/TypeScript#16738]
**TypeScript Version:**  2.3.4

**Code**

```js
function someJs() {}
```

**Expected behavior:**
typechecks ok with --checkJs

**Actual behavior:**
TS18003: No inputs were found in config file

**Comment by graingert** [comment]
also setting checkJs true and allowJs false should fail to run

**Comment by nickmccurdy** [comment]
I agree, I was about to make an issue for this myself. `checkJs` is invalid without `allowJs`, and other `compilerOptions` are implied, so I think it would be more consistent and convenient to imply this as well.

**Comment by glen-84** [comment]
Fixed in #40275.

**Comment by graingert** [comment]
Nice! Thanks all
