### ISSUE TITLE
Space before parenthesis 

### ISSUE THREAD

**Issue by darklight3it** [microsoft/TypeScript#16739]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

**Code**

setting the property

```json
"javascript.format.insertSpaceBeforeFunctionParenthesis": false

```

**Expected behavior:**

I expect the auto formatter to not insert the space before function parenthesis.

**Actual behavior:**

The formatter continues to insert space on formatting.
Probably linked to [https://github.com/Microsoft/vscode/pull/21712](https://github.com/Microsoft/vscode/pull/21712)

**Comment by DanielRosenwasser** [comment]
Could you provide a code repro as well?

**Comment by darklight3it** [comment]
It's a general behaviour of the javascript formatter, i think that the bug should be independent by the code base. If you think it's useful my code base relies mostly on an object literal notation, e.g.

```javascript

var object = {
  method1: function(){
    //code here
  },
  method2: function(){
   //code here
  }
}
```

**Comment by yume-chan** [comment]
@darklight3it Your problem is actually caused by `javascript.format.insertSpaceAfterFunctionKeywordForAnonymousFunctions` default with `true`.

The naming is... a mess...

**Comment by darklight3it** [comment]
thanks

**Comment by RyanCavanaugh** [comment]
Seems like this was a configuration problem, not a bug
