### ISSUE TITLE
Shallow copy via object spread does not type check

### ISSUE THREAD

**Issue by mmmichl** [Microsoft/TypeScript#16747]
**TypeScript Version:**  2.4.0 (playground)

**Code**

```ts
interface Car {
    doors: number;
}

const car = {
    doors: 4,
}

const carCopy: Car = {
    ...car,
    hp: 700,  // would expect a type error here
}

console.log(carCopy);  // {doors: 4, hp: 700}
```

**Expected behavior:**
When making a shallow copy of an object, where the resulting type is defined (via explicit typing, return type), I would expect unknown properties to be reported.

**Actual behavior:**
Compile error at mistyped/extraneous property.

This behaviour is consistent with `Object.assign`. Typescript will only complain about missing properties, but not of extraneous.

**Comment by RyanCavanaugh** [comment]
The playground is running 2.3. This is an error in 2.4. See #13878
