### ISSUE TITLE
Formatter: Don't indent comment

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#16745]
**TypeScript Version:**  nightly (2.5.0-dev.20170626)

**Code**

```ts
// Sample code:
// function f() {
```

Hit enter and type `// return g;`, hit enter and type `// }`

**Expected behavior:**

```ts
// Sample code:
// function f() {
//    return g;
// }
```

**Actual behavior:**

```ts
// Sample code:
// function f() {
    // return g;
    // }
```

**Comment by MrAndersen1** [comment]
Just don't always remove indenting of comments.
For instance when pressing format document, or similar, it is very nice that it indents comments as they break code folding.
Eg comment that breaks folding:
```
function f() {
	if (true)
	{
// here
	}
}
```

**Comment by mhegazy** [comment]
Comments need to be indented with their matching nodes. think of a function with a comment.. if the function moves, you expect the comment to move.. not doing that would be bad..

**Comment by andy-ms** [comment]
I think this is a vscode issue since they don't seem to be making a tsserver request for this. Microsoft/vscode#38890

**Comment by rebornix** [comment]
It's a VSCode indentation issue, feel free to close it here.
