### ISSUE TITLE
URLSearchParams type inference

### ISSUE THREAD

**Issue by Hirevo** [Microsoft/TypeScript#16753]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

**Code**

```ts
let searchParams = new URLSearchParams(window.location.search)

if (searchParams.has("foo")) {
    var arg = searchParams.get("foo")
    // ....
    if (arg.length == 4)
    // ....
}
```

**Expected behavior:**
No error, "arg" gets inferred as being of type "string" because of the if check and arg.length is therefore guaranteed to be defined.

**Actual behavior:**
Error on arg.length: Object is possibly null. "arg" gets an inferred type of "string | null" despite the check.

I think it has to do with the type declaration for URLSearchParams as the type checker may not be aware that searchParams.has() ensures the string type of the return value of searchParams.get() for the same argument.
I know I can get away with something like this:
```ts
var arg = <string>searchParams.get("foo")
```
But is there a way to inform the type checker about something like this, in the same way that Array.isArray(someArg) ensures that someArg is an array ?

**Comment by Kovensky** [comment]
`searchParams.get("foo")!`.

Unfortunately, whether a particular key exists or not is not part of the type information for `URLSearchParams` or other `Map`/`Set`-like collections.

**Comment by Hirevo** [comment]
@Kovensky I had no idea about this type of race condition.
I’m a student in my first year so I don’t know much about security. You definitely made me learn something here and I’ll try to avoid those errors in the future.

For the type issue, I’ve kind of suspected that this case was different from the Array.isArray() example as it checks the type of the argument itself instead of the type of a value for the given key in the intern key/value pairs. So I understand why it’s not really feasible for the language to check for it.

This issue can therefore be closed, as my question has now been answered.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
