### ISSUE TITLE
Declaration output bug with mapped types and keys needing quotes

### ISSUE THREAD

**Issue by garthk** [Microsoft/TypeScript#16754]
**TypeScript Version:**  2.3.4

**Code:**

See the [gist](https://gist.github.com/garthk/1824311d2cae52a67c7bc73f5c9abfe7) for the full demo, but the meat is this file and `declaration` enabled in `compilerOptions`:

```ts
function strEnum<T extends string>(strings: Array<T>): {[K in T]: K} {
    return strings.reduce((res, key) => {
        res[key] = key;
        return res;
    }, Object.create(null));
}

export const scopes = strEnum([
    'noun:verb',
    'verb:adjective',
    'noun'
]);

export type Scope = keyof typeof scopes;
```

**Expected behavior:**

The output `index.d.ts` declaration file should quote the keys in the `scopes` object:

```ts
export declare const scopes: {
    "noun:verb": "noun:verb";
    "verb:adjective": "verb:adjective";
    "noun": "noun";
};
```

**Actual behavior:**

The output `index.d.ts` declaration file _does not_ quote  the keys in the `scopes` object:

```ts
export declare const scopes: {
    noun:verb: "noun:verb";
    verb:adjective: "verb:adjective";
    noun: "noun";
};
```

… leading to errors building dependent packages:

```
dependent: ../dependency/dist/index.d.ts(3,13): error TS1005: ';' expected.
```

**Comment by weswigham** [comment]
Fixed by #18023. I would say duplicates #18012, but this came first. ;)
