### ISSUE TITLE
Cannot define a module for a specific file extension in 2.4.1

### ISSUE THREAD

**Issue by vekexasia** [Microsoft/TypeScript#16769]
**TypeScript Version:**  2.4.1
**Code**
```ts
// A *self-contained* demonstration of the problem follows...
declare module "*.vue" {
  import Vue from 'vue'
  export default typeof Vue
}
```

**Expected behavior:**
A file with the above content used to work when importing `.vue` files.
In 2.4.1 It looks like the file is not taken into account as every .vue file gets imported as "string"? 
**Actual behavior:**
Everything seems to be imported as string?

**Comment by vekexasia** [comment]
That file is perfectly working in `2.3.4`

**Comment by mhegazy** [comment]
The right hand side of an `export default` is an expression not a type. `typeof Vue` is just calling the regular JS `typeof` operator on the reference `Vue`; and that happens to be a `string` all the time..

This should have been an error to have an expression in an ambient context. the only possible value should be an identifier name. files https://github.com/Microsoft/TypeScript/issues/17991 to track it.

so for this definition, you need to change your declaration to be:

```ts
declare module "*.vue" {
    import Vue from 'vue'
    const _: typeof Vue;
    export default _;
}
```

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
