### ISSUE TITLE
bug: optional properties and assignability to empty values (e.g. `never`)

### ISSUE THREAD

**Issue by tycho01** [Microsoft/TypeScript#16762]
Based on a [comment](https://github.com/Microsoft/TypeScript/issues/12215#issuecomment-310529729): 

**TypeScript Version:** 2.5.0-dev.20170626

**Code**

```ts
type T = { a: never; b?: 1; c: 1; };
const v: T = { c: 1 };
// Property 'a' is missing in type '{ c: 1; }'.
```

**Expected behavior:**
Probably no error, since requiring `never` / `undefined` on a prop seems sorta useless (it'd default to that anyway). 

**Actual behavior:**
Error: `Property 'a' is missing in type '{ c: 1; }'`

How much of this is by design?

Related [comment](https://github.com/Microsoft/TypeScript/issues/12215#issuecomment-310613181) by @niieani:
> I think the TypeScript team mentioned somewhere that `| undefined` should be considered equivalent to `?` -- i.e. it aligns with their goals. For most intents and purposes this is how TS currently behaves, although I see what you mean by compiler differentiating somehow.
> For example Flow treats these (`?` and `| void`) as different things, i.e. you could technically have a property and expect its type to be `undefined`. However for (all?) practical reasons they are pretty much the same.

**Comment by ikatyang** [comment]
I used to suggest that use `never` for optional parameter, but it seems `never` is not the right type, see https://github.com/Microsoft/TypeScript/issues/14452#issuecomment-285496544.

Thus I realize that `?` is currently the only way to set a parameter to be optional, for example:

```ts

type A = {
    a: undefined;
    b: string;
}
type X = A['a']; //=> undefined
const a: A = {b: 'str'};
//    ^ [ts]
// Type '{ b: string; }' is not assignable to type '{ a: undefined; b: string; }'.
//   Property 'a' is missing in type '{ b: string; }'.

type B = {
    a: never;
    b: string;
}
type Y = B['a']; //=> never
const b: B = {b: 'str'};
//    ^ [ts]
// Type '{ b: string; }' is not assignable to type 'B'.
//   Property 'a' is missing in type '{ b: string; }'.

type C = {
    a?: undefined;
    b: string;
}
type Z = C['a']; //=> undefined
const c: C = {b: 'str'};
// passed
```

**Comment by tycho01** [comment]
Thanks for your response. Pinging @dleavitt too. Seems #13195 is related then.
If simple solutions fail here I'd suggest #6606 as an alternative to enable type-level type checks.
