### ISSUE TITLE
State of 1.4

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#1677]
Curious what's the state of affairs with `1.4`. I see its on [releases](https://github.com/Microsoft/TypeScript/releases) and also completed on [milestones](https://github.com/Microsoft/TypeScript/milestones) 

But not on NPM, no blog post, no VS update. Perhaps thats coming with `1.4.1`? Purely curious. Thanks for all this awesome stuff (and a stable language service!).

**Comment by DanielRosenwasser** [comment]
Just be patient, I promise it will be out soon.

**Comment by DanielRosenwasser** [comment]
We're just finalizing a few things. Just be patient, I promise it will be out soon. :smile:

**Comment by johnnyreilly** [comment]
:+1:

**Comment by DickvdBrink** [comment]
21th together with the Microsoft Windows 10 event (just a guess haha) :) ? xD
Can't wait !

**Comment by NoelAbrahams** [comment]
please

**Comment by RyanCavanaugh** [comment]
Our major releases are often aligned with other product releases with nonpublic release dates, so we can't say any more than we already have. But yes, the 1.4 branch is stabilizing.

Begin speculation / rumors here :wink:

**Comment by vvakame** [comment]
> But yes, the 1.4 branch is stabilizing.

good news!
https://github.com/borisyankov/DefinitelyTyped/pull/3466
I was create new branch to DefinitelyTyped.

**Comment by DanielRosenwasser** [comment]
If you hadn't heard, [we released it today](http://blogs.msdn.com/b/typescript/archive/2015/01/16/announcing-typescript-1-4.aspx) - enjoy guys!
