### ISSUE TITLE
`watchDirectory` called unconditionally, but it is typed as optional

### ISSUE THREAD

**Issue by ghost** [microsoft/TypeScript#16776]
In `editorServices.ts`:

```ts
this.directoryWatchersForTsconfig.set(currentPath, this.projectService.host.watchDirectory(currentPath, callback));
```

However, `watchDirectory` is optional on `interface System`.
Since that code has been there for [over](https://github.com/Microsoft/TypeScript/blame/3212e25a3ab0581ebfac205b34004aa16735c05a/src/server/editorServices.ts#L127) a year, maybe we should just make `watchDirectory` required now?

**Comment by sheetalkamat** [comment]
Agreed with @andy-ms that [ServerHost](https://github.com/Microsoft/TypeScript/blob/master/src/server/types.ts#L17) needs to have watchDirectory and watchFile as required, just like setTimeout and such optional calls of the system to ensure correct working on the server.

**Comment by gagoman** [comment]
It was discussed at https://github.com/Microsoft/TypeScript/pull/18728 that `watchDirectory` can not be required

**Comment by sheetalkamat** [comment]
But #18728 is for ```tsc``` not for ```tsserver```. For ```tsserver``` watchDirectory and watchFile should be required. For ```tsc``` we already check for it [here](https://github.com/Microsoft/TypeScript/blob/master/src/compiler/tsc.ts#L137).
