### ISSUE TITLE
Allow tsc and tsc --watch to transpile source files relative to the source path instead of relative to tsconfig.json

### ISSUE THREAD

**Issue by ORESoftware** [Microsoft/TypeScript#16779]
Right now, using `tsc --watch`, it will transpile files according to the rules in tsconfig.json.

If I want to write the target files to a different directory, I should use --outDir. However --outDir appears relative to the cwd or is hard coded in tsconfig like so:

` "outDir": "./target-dir"`

I am looking for a way to transpile files and have the outDir be relative to the source file, not relative to the current working directory or hardcoded outDir.

One way to do it, would be to allow for some bash in tsconfig.json, like so:

` "outDir": "$(dirname ${sourceFile})/target-dir"`

As you can see, I wish to place each source file in a directory called target, right next door to the source file.

Is this possible? Seems like a useful feature for users.

**Comment by ORESoftware** [comment]
ahhhh, maybe I can use this tsc option to accomplish this:

`--rootDir	string	(common root directory is computed from the list of input files)	Specifies the root directory of input files. Only use to control the output directory structure with --outDir.`

**Comment by ORESoftware** [comment]
Ok, I got this working manually like so:

 tsc ${x} --outDir "$(dirname $(dirname ${x}))/target-dir" 

however, the problem is `tsc --watch` does not seem to support the same behavior

**Comment by mhegazy** [comment]
Options specified in your tsconfig.json can be overwritten with options on the commmandline. so my recommendation is
```sh
tsc --p <name of your tsconfig.json> --watch --outDir <your new outDir>
```

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
