### ISSUE TITLE
Show completions for small types first

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#16783]
**TypeScript Version:**  nightly (2.5.0-dev.20170627)

**Code**

```ts
interface Point { x: number, y: number }
type Points = Point | Point[];
const x: Points = { /**/ }
```

**Expected behavior:**

Show completions for `x` and `y` first. Since `Point` is the smallest type, it is the most likely to be implemented by an object literal.

**Actual behavior:**

They are all the way at the bottom. We get `concat`, `copyWithin`, and other properties of `Array` first.
Ref: https://github.com/Microsoft/TypeScript/issues/16781#issuecomment-311548696

**Comment by DanielRosenwasser** [comment]
I guess any primitive or literal type is strictly "smaller" than an object type, but is an object type "bigger" than a union of primitive types?

**Comment by andy-ms** [comment]
Also, we shouldn't show completions for literals, because no one in their right mind writes `const x: string = { charAt(n) { ... }, charCodeAt(n) { ... }, ... }`.

**Comment by mhegazy** [comment]
@andy-ms is this still an issue?

**Comment by andy-ms** [comment]
We did a workaround specifically for arrays in #18124. I guess we can wait and see if that's a good enough solution.

**Comment by mhegazy** [comment]
For this specific issue, i believe we did address the problem. closing for now. i do not think users interested in the original proposal will land here given the search keywords and the example.
