### ISSUE TITLE
tsserverlibrary.d.ts throws error TS2304: Cannot find name 'Comparison'

### ISSUE THREAD

**Issue by Quramy** [Microsoft/TypeScript#16782]
**TypeScript Version:**  2.4.1

**Code**

```ts
import * as ts from "typescript/lib/tsserverlibrary";
let factory: ts.server.PluginModuleFactory;
```

Compiling the above code, a compilation error, `error TS2304: Cannot find name 'Comparison'`, occurs.

And my tsconfig.json is the following :
(It's just generated one by `tsc --init`) 

```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "strict": true
  }
}
```

**Expected behavior:**

No compilation error.

**Actual behavior:**

tsc throws the following error:

```txt
node_modules/typescript/lib/tsserverlibrary.d.ts(3845,181): error TS2304: Cannot find name 'Comparison'.
```

**Comment by zoharyosef** [comment]
Same here running ng serve

**Comment by rand0me** [comment]
Faced same issue in `v2.4.2`, rolling back to `v2.3.4` successfully avoided it.

**Comment by jeff3dx** [comment]
Same problem using create-react-app my-app --scripts-version=react-scripts-ts
"Comparison" appears to be an undefined function in tsserverlibrary.d.ts.  Looks like bug in typescript to me.

**Comment by DanielRosenwasser** [comment]
Are you seeing the nightly releases?
