### ISSUE TITLE
Do not return global completions while typing getter identifier

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#16784]
From https://github.com/Microsoft/vscode/issues/29477

**TypeScript Version:**  2.5.0-dev.20170627

**Code**

```ts
var abcd = 123


interface Foo {
    get ab|
}
```

Trigger completions at `|` in `get ab`

**Expected behavior:**
No completions for `abcd` are returned. This is consistent with the behavior when you are inside of a `class` or object literal instead of an `interface`

**Actual behavior:**
global completions are returned:

```
[Trace  - 10:53:31 PM] Sending request: completions (266). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/Users/matb/projects/san/src/y/x.ts",
    "line": 5,
    "offset": 11
}
[Trace  - 10:53:31 PM] Response received: completions (266). Request took 5 ms. Success: true 
Result: [
    {
        "name": "Array",
        "kind": "interface",
        "kindModifiers": "declare",
        "sortText": "0"
    },
...
```

This includes `abcd` which we automatically complete for in VSCode when you press `(`

**Comment by mhegazy** [comment]
`get`/`set` is not allowed in interfaces any ways. completions should be filters in classes correctly.
