### ISSUE TITLE
Type 'T' is not assignable to type 'T'. Two different types with this name exist, but they are unrelated

### ISSUE THREAD

**Issue by alan-agius4** [Microsoft/TypeScript#16786]
**TypeScript Version:**  2.4.1

**Code**

```ts
interface myModel {
	prop: <T>(update: T) => void;
}

class myClass {
	test<T>(model: T) {
		const x = {
			prop: (model: T) => {
				// do something
			}
		}
		this.test2(x);
	}

	test2(model: myModel) {
		
	}
}

```

**Expected behavior:**
no errors

**Actual behavior:**
Type 'T' is not assignable to type 'T'. Two different types with this name exist, but they are unrelated.

**Comment by alan-agius4** [comment]
I also have the same error using `ngrx` 

```
(operator: Operator<any, Action>) => Observable<Action>' is not assignable to type '<R>(operator: Operator<any, R>) => Observable<R>
```

**Comment by dozer75** [comment]
Also get the same error in the latest typescript release on rxjs. 

I really starting to be frustrated over open source and the lack of quality checking on releases in different open source projects.

**Comment by HerringtonDarkholme** [comment]
TypeScript did find a bug in your code.

```ts
interface myModel {
	prop: <T>(update: T) => void;
}
```

The generic signature means `myModel` can accept "any" type. Because the type parameter T here is totally free, without any constraint.

However, in `myClass`. 

```ts
test<T>(model: T) {
		const x = {
			prop: (model: T) => { // T here is a usage, it refers to the type parameter above.
			}
		}
		this.test2(x);
	}
```

Note the comment, `T` is not free, it is "bound" to the outer declaration.

It is hard to explain. But TS is right here.

**Comment by alan-agius4** [comment]
So in reality here, from what I am understanding it's point less to use a
generic type in such cases? Since the T in the model is "free"

**Comment by RyanCavanaugh** [comment]
The intent of `prop: <T>(update: T) => void;` is very unclear. There's not really anything distinguishing it from `prop: (update: { }) => void;` or `prop: (update: any) => void;` other than it looking more typesafe than it actually is.

**Comment by ahejlsberg** [comment]
See #16368 for more context. Note that you can use the `--noStrictGenericChecks` to turn off the new stricter checks as a stopgap solution.

**Comment by alan-agius4** [comment]
Cheers for the fast feedback, much appreciated.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Comment by khanhhc** [comment]
Why this bug is not fixed?????

**Comment by dave0688** [comment]
+1 
Still having the bug... Why is it not adressed yet??

**Comment by ahejlsberg** [comment]
This is working as intended. It so happens there are two type parameters named `T` in the example, but they're distinct and not assignment compatible.
