### ISSUE TITLE
Misleading overload resolution error in 2.4.1

### ISSUE THREAD

**Issue by kpreisser** [Microsoft/TypeScript#16793]
**TypeScript Version:**  2.4.1

**Code**

* Create a TS file and add the content of [Google Visualization APIs definitions](https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/3b213274c4e610aec0b622d7b9727931ad11b0a2/types/google.visualization/index.d.ts)
* Add the following code:

```ts
function abc() {
    let data = new google.visualization.DataTable();
    let chart = new google.visualization.LineChart(null as Element);
    let options = {
        legend: 'none'
    };

    chart.draw(data, options);
}
```

**Expected behavior:**
```
type '{ legend: string; }' is not assignable to type 'LineChartOptions'.
```

**Actual behavior:**
```
error TS2345: Build:Argument of type 'DataTable' is not assignable to parameter of type 'DataView'.
```
![overloaderror1](https://user-images.githubusercontent.com/13289184/27627752-316e1118-5bed-11e7-8651-edac26d11db3.png)

Note: `draw` has two overloads, one with `DataTable` and one with `DataView`. It seems when reporting the error, TS incorrectly chooses the overload with `DataView`.

```ts
export class LineChart extends CoreChartBase {
    draw(data: DataTable, options: LineChartOptions): void;
    draw(data: DataView, options: LineChartOptions): void;
}
```

However, when hovering over `draw`, VS displays the correct overload that accepts a `DataTable`:
![overloaderror2](https://user-images.githubusercontent.com/13289184/27627768-40b536b0-5bed-11e7-9613-cb360055b969.png)

EDIT: It seems the "wrong" overload is a side effect of another error, the incompatibility of `LineChartOptions` (`ChartLegend` is an interface with only optional members, so in previous versions, a `string` was assignable to it).
Still, I think the error should not report an error of `DataTable` not being assignable to `DataView` here.

Thanks!

**Comment by RyanCavanaugh** [comment]
Once overload resolution fails, we have no idea which overload you were "trying" to match. It's best-effort at this point.

Side note, this should be written as
```
    draw(data: DataTable | DataView, options: LineChartOptions): void;
```
instead of
```
    draw(data: DataTable, options: LineChartOptions): void;
    draw(data: DataView, options: LineChartOptions): void;
```
which *may* improve the error message quality.
