### ISSUE TITLE
Use type name in error messages and inline doc

### ISSUE THREAD

**Issue by testerez** [Microsoft/TypeScript#16798]
**TypeScript Version:**  2.4.0

**Code**

```ts
const foo = {
  name: 'Foo',
  age: 20,
}
type Foo = typeof foo;

function test(foo: Foo) { }

test('');
```

**Expected behavior:**

I'd like the error message to be:
```
Argument of type '""' is not assignable to parameter of type Foo
```
And the inline doc to be:
```
function test(foo: Foo): void
```

**Actual behavior:**
But the error message is
```
Argument of type '""' is not assignable to parameter of type '{ name: string; age: number; }'.
```

And the inline doc is
```
function test(foo: {
    name: string;
    age: number;
}): void
```

In this example, the current behavior is alright but in more complicated situations the error messages can become very verbose and intimidating. Using the types name would make them a lot cleaner IMO.

**Comment by mhegazy** [comment]
Type aliases are just aliases, and they are eagerly resolved to what they alias by the compiler. This saves the compiler time and space when dealing with types. we try to do a reverse lookup process when we are writing the type name, but there is a limit to that.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
