### ISSUE TITLE
Modify behavior of generics extending string literal union? 

### ISSUE THREAD

**Issue by rozzzly** [Microsoft/TypeScript#16794]
Consider the following code:

```typescript
type Color = 'red' | 'green' | 'blue';

function setBackgroundColor(color: Color) {
    // ...
}
```

This snippet gives us handy type completions at the `?` in `setBackgroundColor('?')`. This is super useful; prevents errors, saves time, etc. But what if you wanted to support lots of colors.... like say every shade the hardware store sells? Well, currently you have two options:

  1. Add the list of all conceivable colors to the `Color` union **BUT, that's a prohibitive pain.**

  2. Get rid of `Color` and just use `string` **BUT, you loose completions.**

There are often times I wish I could offer "hints" to a consuming developer. Or give a few default values, but allow devs to supply their own. Unfortunately, `string | 'Red' | 'Blue'` widens to `string` and the suggestions are lost! So it'd be great if either those completions could be maintained or perhaps if something akin  to the following were possible:
```typescript
type Color = 'red' | 'green' | 'blue';

function setBackgroundColor<C extends Color>(color: C) {
    // ...
}

setBackgroundColor('r?');
// completion:   red ^
setBackgroundColor('orange');
// no completions:   ^
// but no error thrown either

```

I just came up against shortfall for like the 3rd time, and figured I ought to open an issue, see how receptive the TS team was to something like this.

**Comment by rozzzly** [comment]
Okay so I just noticed:

from <kbd>lib.dom.d.ts</kbd>
```typescript
addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, useCapture?: boolean): void;
addEventListener(type: string, listener: EventListenerOrEventListenerObject, useCapture?: boolean): void;
````

allows both

```typescript
document.addEventListener('scroll', undefined);
document.addEventListener('foo', undefined);
```

`foo` obviously isn't a DOM event, just some made up value. **But it passes!** When I copy the type definition to create my own function, 


```typescript
function foo<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, useCapture?: boolean): void;
function foo(type: string, listener: EventListenerOrEventListenerObject, useCapture?: boolean): void { };

foo('abort', undefined); // works as expected
foo('bar', undefined); // doesn't work
```

I've tested this in `2.5.0-dev.20170628` and whatever the typescript playground is running

So it looks like there's some voodoo magic going on behind the scenes to silence the type checker and preserve completions for this special case.  But that just proves my point about! Wouldn't it be a lot less hacky to remove that hidden logic and change the behavior of extending string literal unions?

**Comment by mhegazy** [comment]
We get a lot of savings in memory and performance by flatting types, and dropping literal types if they are unioned with string. so somehting like `string | 'red' | 'blue'` just for completions would be worth it.
changing the meaning of extends is not a possiblity. it is a breaking change, and does not make fit the rest of the language.

You can however use overloads to achieve what you want. and that is what we use for addeventListener and the like, e.g.:

```ts
function setBackgroundColor(color: Color);
function setBackgroundColor(color: string); 
function setBackgroundColor(color: string) { 
...
}
```

just make sure your `string` overload is last.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
