### ISSUE TITLE
TS 2.4.1: ReadonlyArray<Identifiable> not assignable to type ReadonlyArray<T> even though <T extends Identifiable>

### ISSUE THREAD

**Issue by mmc41** [Microsoft/TypeScript#16805]
**TypeScript Version:**  2.4.1

**Code**

```ts
export interface Identifiable {
 id: string;
}

export function test<T extends Identifiable>(): ReadonlyArray<T> {
    const result: ReadonlyArray<Identifiable> = [];
    return result;
}

```

**Expected behavior:**
Should compile ok.

**Actual behavior:**

```
Error: 'Type 'ReadonlyArray<Identifiable>' is not assignable to type 'ReadonlyArray<T>'.
  Type 'Identifiable' is not assignable to type 'T'.
```'

**Comment by kitsonk** [comment]
```ts
export interface Identifiable {
 id: string;
}

export function test<T extends Identifiable>(): ReadonlyArray<T> {
    const result: ReadonlyArray<T> = [];
    return result;
}
```

2.4 is correct, `Identifiable` is not assignable to `T`.  Previously the compiler ignored these types of errors.  Now it correctly flags them. See #16368 and #15104.

**Comment by mmc41** [comment]
@kitsonk Thanks for info. Then the Q is, how to change the signature of test method above to work returning an readonly array of either Identifiables or subclasses of Identifiables ?

**Comment by mmc41** [comment]
Ok. Got it myself:

```
export function test<T extends Identifiable>(): ReadonlyArray<T> {
    const result: ReadonlyArray<T> = [];
    return result;
}
```

**Comment by kitsonk** [comment]
For the record, I did exactly that in the example I provided back... 😁
