### ISSUE TITLE
[Requests] Insert space before or after * in generator function

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#16809]
_From @DRL9 on June 28, 2017 15:2_

Hi. This is a feature request about javascript format.
There are three formats in javascript generator function as follows: 
1. `function* gen()`
2. `function * gen()`
3. `function *gen()`

However, every time I format my js file, it will always be the first. 
It'll be better if we can choose which one. How about adding properties in `settings.json`, such as `javascript.format.insertSpaceBeforeGeneratorStar`, `javascript.format.insertSpaceAfterGeneratorStar`.

_Copied from original issue: Microsoft/vscode#29767_

**Comment by mjbvz** [comment]
#9001 may already track this. Can someone on the TS team please let me know if this is a duplicate

**Comment by mhegazy** [comment]
indeed a duplicate.
