### ISSUE TITLE
Constants in interfaces

### ISSUE THREAD

**Issue by NN---** [Microsoft/TypeScript#1681]
Will it be possible to have constants in interfaces like this:

```typescript
interface Request {
  const ACTION_GET = "get";
  const ACTION_SET = "set";
 
  action: string; // Can be ACTION_GET or ACTION_SET
}
```

It would be better to have string enum like that:

```typescript
interface Request {
  enum Action {
    ACTION_GET = "get",
    ACTION_SET = "set"
  }
  action: Action;
}
```

Or perhaps union types with strings which is the shortest one.

```typescript
interface Request {
  action: "get"|"set";
}
```

**Comment by danquirk** [comment]
Could you describe the scenario you're thinking of using these for? A code example of the new behavior/errors you would like to see are usually useful in these types of suggestions. Are you asking for explicit accessor signatures in interfaces?

**Comment by DanielRosenwasser** [comment]
In the following, the interface declaration will merge with the module, so that `Request` becomes a value, namespace, and type. This might be what you want.

```TypeScript
module Request {
   export enum Action {
      ACTION_GET,
      ACTION_SET
    }
}

interface Request {
    action: Request.Action
}
```

**Comment by NN---** [comment]
@DanielRosenwasser right, forgot about it.
Not the obvious one, but it solves the problem.
