### ISSUE TITLE
error TS2304: Cannot find name 'object' when using checkJs

### ISSUE THREAD

**Issue by Wenzil** [Microsoft/TypeScript#16811]
**TypeScript Version:**  2.4.1

**Code**
- tsconfig.json
```json
{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "allowJs": true,
    "checkJs": true,
    "noEmit": true,
    "maxNodeModuleJsDepth": 0
  },
  "exclude": [
    "node_modules"
  ]
}
```
- package.json
```json
{
  "name": "ts-object-test",
  "version": "0.1.0",
  "description": "Typescript object test",
  "main": "lib/index.js",
  "scripts": {
    "start": "node lib/index",
    "check": "node_modules/.bin/tsc"
  },
  "devDependencies": {
    "@types/node": "^6.0.72",
    "typescript": "^2.4.1"
  }
}
```
- lib/index.js
```js
const util = require('util')

/**
 * Pretty-print an object
 *
 * @param {object} obj - The object to pretty print
 * @returns {void}
 */
function prettyPrint (obj) {
  console.log(util.inspect(obj))
}

prettyPrint({a: 'b'})
```
- CLI
```bash
npm install
npm run check
```

**Expected behavior:**
Type checking reports no error

**Actual behavior:**
Type checking reports `lib/index.js(6,12): error TS2304: Cannot find name 'object'.`

Note that when using typescript 2.3, type checking behaves as expected.

**Comment by thw0rted** [comment]
I know `boolean` and `string` and `number` are primitives with corresponding capitalized boxed objects, but I didn't think that (little-"o") `object` was a primitive.  Does `object` (little-"o") actually exist?

**Comment by kitsonk** [comment]
It was introduced in [TypeScript 2.2](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#object-type).
