### ISSUE TITLE
Contextual typing not working on optional members

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#16817]
The following sample works perfectly in `noImplicitAny` *unless* I turn on `strictNullChecks`. In that event, the `s` parameter on `foo` seems to get an implicit `any`.

```ts
interface ActionsObject<State> {
    [prop: string]: (state: State) => State
}

interface Options<State, Actions> {
    state?: State;
    view?: (state: State, actions: Actions) => any;
    actions?: Actions;
}

declare function app<State, Actions extends ActionsObject<State>>(obj: Options<State, Actions>): void;

app({
    state: 100,
    actions: {
        foo: s => s
    },
    view: (s, a) => null as any,
})
```

If I make `actions` non-optional, then things work perfectly again.

Context: https://github.com/hyperapp/hyperapp/issues/87

**Comment by weswigham** [comment]
This isn't `strictNullChecks` specific (though it's much easier to see the bug there); we're failing to produce parameter inferences for any parameter within an index within a union:
```ts
interface ActionsObject<State> {
        [prop: string]: (state: State) => State;
    }
    
    interface Options<State, Actions> {
        state?: State;
        view?: (state: State, actions: Actions) => any;
        actions: string | Actions;
    }
    
    declare function app<State, Actions extends ActionsObject<State>>(obj: Options<State, Actions>): void;
    
    app({
        state: 100,
        actions: {
            foo: s => s
                 ~
!!! error TS7006: Parameter 's' implicitly has an 'any' type.
        },
        view: (s, a) => undefined as any,
    });
```

**Comment by ahejlsberg** [comment]
This is working as intended. The `actions` property of the object literal is contextually typed by a type parameter type `Actions`, and during the inference process we don't yet know what the type argument for `Actions` will be (and constraints don't factor into type inference). I suggest rewriting the example to:

```ts
interface ActionsObject<State> {
    [prop: string]: (state: State) => State
}

interface Options<State> {
    state?: State;
    actions?: ActionsObject<State>;
}

declare function app<State>(obj: Options<State>): void;

app({
    state: 100,
    actions: {
        foo: s => s
    },
})
```

If it is really important to capture the *actual* type of the object literal, it can be done with an intersection type:

```ts
interface ActionsObject<State> {
    [prop: string]: (state: State) => State
}

interface Options<State> {
    state?: State;
    actions?: ActionsObject<State>;
}

declare function app<State, Actions>(obj: Options<State> & Actions): void;

app({
    state: 100,
    actions: {
        foo: s => s
    },
})
```

(I omitted the `view` property to reduce noise.)

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Comment by weswigham** [comment]
This issue is tagged incorrectly and we have a fix up, it's pretty simple. We do contextually type the nonunion case right (the constraint is the contextual type), so it is, in fact, a bug that a union is not appropriately contextually typed. The issue is that when we get the apparent type of a contextual type, we didn't get the apparent type of all union members - we just returned the union.
