### ISSUE TITLE
Classes with symbols don't pass validation in strict mode

### ISSUE THREAD

**Issue by amir-arad** [Microsoft/TypeScript#16819]
**TypeScript Version:**  2.3.3

**Code**
(copy-paste from the [symbols documentation](https://www.typescriptlang.org/docs/handbook/symbols.html))
```ts
const getClassNameSymbol = Symbol();

class C {
    [getClassNameSymbol](){
       return "C";
    }
}

let c = new C();
let className = c[getClassNameSymbol](); // Error TS7017
```

**Expected behavior:**
pass walidation
**Actual behavior:**
TS7017:Element implicitly has an 'any' type because type 'C' has no index signature.

**Comment by andy-ms** [comment]
May be fixed by #15473? @rbuckton

**Comment by mhegazy** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/5579

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
