### ISSUE TITLE
Formatter dedents after typing inline comment

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#16824]
**TypeScript Version:**  nightly (2.5.0-dev.20170629)

**Code**

```ts
function f() {
	f();
}
```

Navigate inside the parentheses in `f()` and type `/*comment*/`

**Expected behavior:**

```ts
function f() {
	f(/*comment*/);
}
```

**Actual behavior:**

```ts
function f() {
f(/*comment*/);
}
```

**Comment by mhegazy** [comment]
Seems not to repro locally for me.
