### ISSUE TITLE
Diagnostic message is not correct 

### ISSUE THREAD

**Issue by olegdunkan** [Microsoft/TypeScript#16821]
**TypeScript Version:**  2.4.0 

**Code**

```ts
var f: { (): number } | { (): string } = () => true; //error
```
**Expected behavior:**
Type '() => boolean' is not assignable to type '(() => number) | (() => string)'.
 **Type '() => boolean' is not assignable to type '() =>number | string'.**
   **Type 'boolean' is not assignable to type 'string'|'number'**.

**Actual behavior:**
[ts]
Type '() => boolean' is not assignable to type '(() => number) | (() => string)'.
  **Type '() => boolean' is not assignable to type '() => string'.**
    **Type 'boolean' is not assignable to type 'string'.**

**Comment by kitsonk** [comment]
Actually it is correct... TypeScript does not magically combine return types.  `(() => number) | (() => string)` is not equal to `(() =>number | string)` (or is it assignable to that type).  So when there is more than one type involved, TypeScript has to try to resolve an assignment type and report back why it can't assign, so in this case, it is the _last_ type it tried to see if it could assign to, which is `() => string`.  It _could_ also say every other type in the _union_ but that likely wouldn't help anyone and the original union type is already reported.

**Comment by olegdunkan** [comment]
@kitsonk 
Ok, you say about internal stuff of tsc.
But I am a user of tsc, I see at the specification and expect the same.
Spec says that Typescript tries to extract **(produce, combine - any-word)** S signature from type annotation if possibly.
I don't understand why I can't expect it.
I see `Type '() => boolean' is not assignable to type '() => string'` it deceives me.
[Form spec](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#410-function-expressions):
If T is a union type, let U be the set of element types in T that have call signatures. If each type in U has exactly one call signature and that call signature is non-generic, and if all of the signatures are identical ignoring return types, **then S is a signature with the same parameters and a union of the return types.**

**Comment by olegdunkan** [comment]
@kitsonk maybe it is simply to leave only 
**Type '() => boolean' is not assignable to type '(() => number) | (() => string)'.**

**Comment by olegdunkan** [comment]
@kitsonk 

Why does the spec state that  S is a signature with the same parameters and a union of the return types but in actual is with only one of the return types?  

```ts
var f: { (): number } | { (): string } = function s() {
    let fn: typeof s; //type of fn is {():number};    

    return 1;
};
````

**Comment by kitsonk** [comment]
In the above example, you are assigning the type on the left hand, which is a valid assignment, but the right hand type of `s` is being inferred, and you are only returning a value of a number.

```ts
var f: { (): number } | { (): string } = function s() {
  let fn: typeof s; //type of fn is {():1|'foo'};  
  let r = Math.random();  

    return r % 2 ? 1 : 'foo';
};
```

`s` is now inferred to be `() => 1 | 'foo'`... but that isn't assignable to the disjoint on the left, so you get an error.

So unions are inferred, but union of return types are not assignable to explicit disjoint of return types.

**Comment by olegdunkan** [comment]
@kitsonk Thanks for feedback!!!
