### ISSUE TITLE
Error when directly returning promise chain from within Array::map

### ISSUE THREAD

**Issue by jmlee2k** [Microsoft/TypeScript#16825]
After upgrading to TypeScript 2.4.1, we're getting errors in several places in our code (it worked as expected in TypeScript 2.3.4).

The only time we're getting the errors is when mapping an array to ()=>Promise<void>.  I've reduced one of the cases as much as I could to come up with the test case below.

**TypeScript Version:**  2.4.1

**Code**

```ts
class Timing
{
	public static delay(duration:number)
	{
		return {wait:Promise.resolve()};
	}
}

export default class SomeObject
{
	public doSomething():Promise<void>
	{
		const list = [1,2,3,4];
		const steps:Array<()=>Promise<void>> = list.map(s=>{
			return ()=>{
				const delay = Timing.delay(100);
				
				/*A - no chain, works as expected

				return delay.wait;
				*/

				/*B - assigning the promise chain before returning it also 
				works as expected
				
				const result = delay.wait
					.then(()=>{
						return Promise.resolve();
					});
				return result;
				*/

				/*C - returning the promise chain directly results in the 
				      following error:
				
				  returning the Function implicitly has return type 'any' because it does 
				  not have a return type annotation and is referenced directly 
				  or indirectly in one of its return expressions.
				*/

				return delay.wait
					.then(()=>{
						return Promise.resolve();
					});
			}
		});

		return steps.reduce((p,c)=>p.then(c),Promise.resolve());
	}
}
```

**Expected behavior:**
No error

**Actual behavior:**
Error: returning the Function implicitly has return type 'any' because it does not have a return type annotation and is referenced directly or indirectly in one of its return expressions.

**Comment by sylvanaar** [comment]
Are you sure you posted the code giving the error. I can't reproduce it.

**Comment by jmlee2k** [comment]
@sylvanaar Thanks, I took a look, and the error only happens when using the "noImplicitAny" compiler option (or the "strict" option, which includes it).

**Comment by mhegazy** [comment]
I can not reproduce errors on latest with `--strict`

**Comment by jmlee2k** [comment]
Thanks for the fix, our code now works as expected without errors.
