### ISSUE TITLE
(Large project) FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Microsoft/TypeScript#16834]
Spin-off of #16165.

On large project with (very rough ball park) 100k `.ts` lines and another ~50k `.d.ts` lines, `tsc --watch` will consistently run out of memory after >= dozen recompiles.

**TypeScript Version:**  2.3

`tsconfig.json`:
```json
{
    "compilerOptions": {
        "experimentalDecorators": true,
        "noImplicitAny": true,
        "noResolve": false,
        "target": "ES5"
    }
}
```

Eventual error:
```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
```

**Comment by williamg** [comment]
I get this same issue on a smaller project using watchify with tsify.

**Comment by mhegazy** [comment]
@JoshuaKGoldberg can you give [TS 2.5-rc](https://github.com/Microsoft/TypeScript/releases/tag/v2.5.0) a try and let us know if you are still seeing failures? and if so please share enlistment instructions with @sandersn to investigate further.

**Comment by JoshuaKGoldberg** [comment]
@mhegazy I would love to, though we'll need a NuGet package for the MSBuild release. Pinging @minestarks ?

**Comment by minestarks** [comment]
https://www.nuget.org/packages/Microsoft.TypeScript.MSBuild/2.5.0 (yes, it should be rc tagged but it isn't at the moment)

**Comment by JoshuaKGoldberg** [comment]
🔥
