### ISSUE TITLE
Roslyn in Typescript ?

### ISSUE THREAD

**Issue by HamedFathi** [Microsoft/TypeScript#16832]
One of the brightest features in the [Kotlin language](https://kotlinlang.org) is its ability to translate/transpile/convert to javascript. but for C# language we did not have like that. (of course some libraries exist but not good)

so I think If Typescript support Roslyn itself, we can use 

1. For refactoring,analyzing , ... like C#
2. Mapping C# => TypeScript => JavaScript (in the best way as possible)

that would be very useful in some projects and scenarios (Especially in Generators)

so does Typescript team have plan for **Roslyn in Typescript** ? (Especially with Great @ahejlsberg)

**Comment by andy-ms** [comment]
See the TypeScript [design goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).
Note that TypeScript already supports some refactorings, and tslint rules can use type information.

**Comment by HamedFathi** [comment]
@andy-ms 

thanks for your answer but my question is about Roslyn in typescript not refactoring with Roslyn we can have Typescript compiler as service that will support refactoring too.

**Comment by andy-ms** [comment]
The TypeScript compiler is already available as a service. Tslint uses it, for example.

**Comment by HamedFathi** [comment]
@andy-ms 

Roslyn like in Typescript in out of scope ?! C# to Typescript is just an example, an application.

**Comment by RyanCavanaugh** [comment]
Rest assured with a third of the TypeScript team having worked on Roslyn itself we're well aware of what it is and what the trade-offs would be to "support Roslyn itself", whatever that would mean outside of the existing language service support we already have in Visual Studio.
