### ISSUE TITLE
Is it possible to override type definitions for browser?

### ISSUE THREAD

**Issue by daprahamian** [Microsoft/TypeScript#16839]
Hi,

I am currently working on a project that exports two different packages depending on platform:

example `package.json`
```
{
  "name": "my-lib",
  "main": "lib/commonjs/my-lib.js",
  "browser": "lib/umd/my-lib.js"
  ...
}
```

My question is: is it possible to override the `"types"` field in the `package.json` to make the module resolve to the `main` types in node, and the `browser` types in a web browser?

Thanks

**Comment by ikatyang** [comment]
I haven't used `browser` field before, but It seems you have to add the [umd declaration](http://www.typescriptlang.org/docs/handbook/modules.html#umd-modules) in your generated `my-lib.d.ts` file, for example:

(package.json)

```json
{
  "name": "my-lib",
  "main": "lib/commonjs/my-lib.js",
  "browser": "lib/umd/my-lib.js",
  "types": "lib/my-lib.d.ts"
}
```

(lib/my-lib.d.ts)

```ts
export const example = 1;
export as namespace NS; // <--- mark this declaration file as umd compatible
```

(somewhere/you/want/to/use/umd.ts)

```ts
/// <reference types="my-lib" />
NS.example; //=> 1
```

(somewhere/you/want/to/use/commonjs.ts)

```ts
import * as MyLib from 'my-lib';
MyLib.example; //=> 1
```

**Comment by blakeembrey** [comment]
No, it's not. See https://github.com/Microsoft/TypeScript/issues/7753.

**Comment by daprahamian** [comment]
Closing in favor of #7753
