### ISSUE TITLE
jsdoc can't parse type `this` in javascript files

### ISSUE THREAD

**Issue by sandersn** [Microsoft/TypeScript#16831]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

**Code**

```js
// @Filename: foo.js
/**
 * @param {this} x
 * @return {this}
 */
function test() { return this }
```

**Expected behavior:**
No errors

**Actual behavior:**
Two errors: ':' expected, at the end of each `{this}`.

Doesn't repro in typescript.

**Comment by mhegazy** [comment]
it is parsing now. and i am getting an error for use of `this` in a non-class function

![image](https://user-images.githubusercontent.com/8000722/29629137-9ba3dcae-87ec-11e7-8518-ff58e6ce514c.png)
