### ISSUE TITLE
Generic classes does not properly detect types

### ISSUE THREAD

**Issue by mainnika** [Microsoft/TypeScript#16835]
**TypeScript Version:**  2.4.1

**Code**

```ts
interface IBase {
    base?: {};
}

abstract class Base<T1 extends IBase, T2 extends IBase> {

    public t1(t1: T1): void { }
    // public t2(t2: T2): void { }
}

interface IOne extends IBase {
    one: number;
}

interface ITwo extends IBase {
    two: string;
}

class Foo extends Base<IOne, ITwo> { }
class Bar extends Base<ITwo, IOne> { }

class Logic {
    public static do<T1, T2>(
        foo: Base<T1, T2>,
    ): T2 {

        return {} as T2;
    }
}

const t1 = Logic.do(new Bar())
const t2 = Logic.do(new Foo())

t1.one = 1;
t2.two = 'two';
```

**Expected behavior:**
compilation should be fine

**Actual behavior:**
error at last two lines
```
[ts] Property 'one' does not exist on type '{}'.
[ts] Property 'two' does not exist on type '{}'.
```

By the way, if I uncomment Base::t2, everything will be fine.

**Comment by andy-ms** [comment]
TypeScript uses a structural type system. If a type parameter isn't used, it might as well not exist; so we can't detect a type of `T2` and just fill in `{}` instead.

**Comment by mainnika** [comment]
Thanks, I've understood. 
But it sounds like a bug. At the moment I need to define a dummy function to avoid errors and resolve T2 automatically.

**Comment by andy-ms** [comment]
From the compiler's perspective, the fact that `Foo` is *declared* as `Base<IOne, ITwo>` is irrelevant.
It just checks that whatever object it receives is assignable to all the methods in `Base`, none of which uses `T2`. So there's no point where it would get any inference about `T2`.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
