### ISSUE TITLE
Specific .d.ts scenario  issue

### ISSUE THREAD

**Issue by sandorfr** [Microsoft/TypeScript#1683]
I'm currently writing a bunch of javascript libraries typings and I'm currently struggling with merging types and constructor for an ambiant module declaration. I checked codeplex writing .d.ts guide and [this stackoverflow question](http://stackoverflow.com/questions/26242880/how-do-i-write-a-typescript-declaration-file-for-an-external-commonjs-module-tha) without any luck.

You can check the [Javascript sample code](https://github.com/pekim/tedious-connection-pool) and my [current typings](https://github.com/sandorfr/DefinitelyTyped/blob/tediousConnectionPool/tedious-connection-pool) .

You can repro my issue compiling files with this command:
```
tsc --noImplicitAny --module commonjs tedious-connection-pool/tedious-connection-pool-tests.ts
```

It fails with message "error TS7009: 'new' expression, which lacks a constructor signature, implicitly has an 'any' type.". Obvisously if I remove the --noImplicitAny it builds but this is not what I want. To workaround this issue I tested it with and interface instead a function.
```typescript
interface tcp
    {
        /**
         * Connection Pool constructor
         * @param poolConfig the pool configuration
         * @param connectionConfig the connection configuration
         */
        new(poolConfig:tcp.PoolConfig, connectionConfig:any): tcp.ConnectionPool;
    }
```

but it fails with two errors:
error TS7009: 'new' expression, which lacks a constructor signature, implicitly has an 'any' type.
error TS2083: Invalid 'new' expression.

I tried to fix it by putting every declaration in a TediousConnectionPool module  (simalar to sendgrid typings). Sadly, It does not work because import tedious = require('tedious') is not allowed in an internal module.

Thanks for any help

**Comment by mhegazy** [comment]
Here is the error i am getting:
> tedious-connection-pool/tedious-connection-pool-tests.ts(28,50): error TS7009: 'new' expression, whose target lacks a construct signature, implicitly has an 'any' type.

The error means that you are trying to call a function with a 'new' operator, which is a valid JavaScript call, it is just that the type system can not know what the return type would be.

The error comes from:
```TypeScript
import tediousConnectionPool = require("tedious-connection-pool");
var pool: tediousConnectionPool.ConnectionPool = new tediousConnectionPool(poolConfig, config);
```

now looking at tedios-connection-pool
```TypeScript
declare module "tedious-connection-pool" {
    module tcp { ... }

    function tcp(poolConfig:tcp.PoolConfig, connectionConfig:any): void;

    export = tcp;
}
```
looks like your module is exporting a module+function combination. if you want to call tedious-connection-pool module as a class, then need to define a module+class instead.

hope that helps.

**Comment by danquirk** [comment]
That function signature should be newable, will take a look.

**Comment by sandorfr** [comment]
Thanks for your input @mhegazy, I actually tried the class + module but I guess i'm doing something wrong because I can't use module types inside the class (and its constructor). Maybe I'm doing something wrong :

```typescript
declare module "tedious-connection-pool" {
    import tedious = require('tedious');

    module tcp {

        // [...]

        /**
         *  Pool Configuration interface
         */
        export interface PoolConfig {

          // [...]
        }
    }

    /**
     * Tedious Connection Pool Class
     */
    export class tcp {

        /**
         * Connection Pool constructor
         * @param poolConfig the pool configuration
         * @param connectionConfig the connection configuration
         */
        constructor(poolConfig:tcp.PoolConfig, connectionConfig:tedious.ConnectionConfig);

        /**
         * acquires a connection from the pool
         * @param callback invoked when the connection is retrieved and ready
         */
        acquire(callback:ConnectionCallback):void;

        /**
         * listens for a specific connection pool event
         * @param event the event name
         * @param callback invoked when the event is raised
         */
        on(event:string, callback:Function):void;

        /**
         * closes opened connections
         */
        drain():void;
    }
    export = tcp;
}
```

Regarding my current code and the fact that it returns void, it is due to the fact that typescript does not allow to define the return type for a new function.

**Comment by danquirk** [comment]
Your latest example compiles without error if you don't have an export declaration on the class (you cannot export individual elements and have an export= statement).

a.d.ts:
```ts
declare module "tedious-connection-pool" {
    module tcp {
        export interface PoolConfig {
          a: string;
        }
    }

    function tcp(x: tcp.PoolConfig, y: any): void;
    
    // alternatively, this class definition works
    /*class tcp {
        constructor(x: tcp.PoolConfig, y: any);
    }*/
    export = tcp;
}
```
a.d.ts:
```ts
/// <reference path='a.d.ts'/>
import i = require('tedious-connection-pool');
//var r = new i({ a: 3 }, 2); // error
var r2 = new i({ a: 'ok' }, 2); // ok
```

**Comment by sandorfr** [comment]
When I remove export in front of class I end up with this error : 
error TS2095: Could not find symbol 'PoolConfig'

Your sample does not compile with --noImplicitAny (this is a requirement for Definitely Type contributions).

**Comment by danquirk** [comment]
You need to qualify the use of PoolConfig in the same way my example did. I don't know what version of the compiler you're using but 1.1 and the latest bits in master compile the sample in my last post without error with --noImplicitAny.

**Comment by sandorfr** [comment]
Just made sure I'm using the latest available on npm and it matches your sample exactly and it runs. Thanks.
