### ISSUE TITLE
Decorators on parent class causes issues with the resulting objects constructor function.

### ISSUE THREAD

**Issue by moneydance** [Microsoft/TypeScript#16843]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

**Code**

```ts
@overrideConstructor
class A {
  constructor(public a:number){}
}

@overrideConstructor
class B extends A {
  constructor(a:number, public b:number){
    super(a);
  }
}

@overrideConstructor
class C extends B {
  constructor(a:number, b:number, public c:number){
    super(a, b);
  }
}

function getClassHierarchy(baseClass:Function): Function[] {
  let constructors:Function[] = [];
  let currentConstructor:Function = baseClass;
  while (currentConstructor != Function.prototype) {
    constructors.push(currentConstructor);
    currentConstructor = Object.getPrototypeOf(currentConstructor);
  }
  return constructors;
}

function overrideConstructor(target:any) {
  var f:any = function(...args:any[]) {
    let instance = new target(...args);
    return instance;
  }
  f.prototype = target;
  return f;
}

let c = new C(1,2,3);
console.log(c);
console.log(getClassHierarchy(c.constructor));

```

**Expected behavior:**
I expect the constructor function of c to be C, and its hierarchy to be [C(), B(), A()]
**Actual behavior:**
In reality the the constructor function of c is A. Its hierarchy is [A()]

I roughly followed this blog post http://blog.wolksoftware.com/decorators-metadata-reflection-in-typescript-from-novice-to-expert-part-ii

Please let me know if this is a bug or if I am misunderstanding something.

**Comment by mhegazy** [comment]
I believe the correct definition of this decorator should be:
```ts
function overrideConstructor<T extends new (...args: any[]) => object>(target: T) {
    return class extends target {
    }
}
```

The result is a new anonymous class wrapping each of your classes. the hierarchy should be 
- Wrapper
- C
- Wrapper 
- B
- Wrapper
- A

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
