### ISSUE TITLE
Const enum leaves behind semicolons

### ISSUE THREAD

**Issue by jonathandturner** [Microsoft/TypeScript#1685]
If I do this:

```TypeScript
const enum Color { Blue, Green };
var c = Color.Blue;
```

I get this as output:

```JavaScript
;
var c = 0 /* Blue */;
```

Notice the extra semicolon on the first line.  Can we clean this up?  Looks messy and doesn't really fit with our "clean JS" output effort.

**Comment by mhegazy** [comment]
this is by design. as the ";" is not part of the const enum declaration just like classes and modules. what you are seeing there is an empty statement being preserved.
