### ISSUE TITLE
Cannot read property 'args' of undefined

### ISSUE THREAD

**Issue by yakiler** [Microsoft/TypeScript#16850]
**TypeScript Version:**  2.4.1 / nightly (2.5.0-dev.201xxxxx)

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
class Greet 
{
       say():void
       {
           console.log( "Hello world" );
       }
}

```
I initialized a TS project in cmd, And then generate a tsconfig.json file.I wrote a Greet.ts file. 
Now I use ctrl + shift + b to compile in vsCode ,Then i got a hint "Cannot read property 'args' of undefined"
**Expected behavior:**
Compiled to get a JS file
**Actual behavior:**
Found a hint

**Comment by davedevv** [comment]
Yup!.. I too face the same issue here, Posted this in StackOverflow at the below URL,

https://stackoverflow.com/questions/44859973/cannot-read-property-args-of-undefined-error-while-compiling-a-ts-file-visual

Any solutions?

**Comment by Enet4** [comment]
According to that SO question, this might actually be an issue with Visual Studio Code integration, since runnning `tsc` directly works fine. Can you try adding this to a new ".vscode/tasks.json" file and running the command again?

```json
{
    "version": "0.1.0",
    "command": "tsc",
    "isShellCommand": true,
    "showOutput": "always"
}
```

**Comment by yakiler** [comment]
Tried your answer, the perfect solution to my problem.Very feeling

**Comment by davedevv** [comment]
Hi Enet4,

Thanks for the solution!. I worked perfectly!

**Comment by SwamyVaditya** [comment]
Yes, this solution works perfectly! Thanks.
