### ISSUE TITLE
Angular 2, Event from enum

### ISSUE THREAD

**Issue by edwardtapiero** [Microsoft/TypeScript#16859]
I have a problem I do not know how to make invisible the value 2 of the "Titulo" enum and that when I click on the value "no" (1) of the radio button "existio contacto" of coincidence.component.html is visible

This is coincidence html

      <div class="row">
          <div class="small-12 columns">
            <md-card class="cards">
              <span class="title">{{titulo}} </span>
              <div class="row">
                <div class="small-6 columns">
                  <div class="row">
                    <div class="small-6 columns">
                      <span class="subtitle">
        Number matching</span>
                      <span>3333333333</span>
                    </div>
                    <div class="small-6 columns">
                      <span class="subtitle">
        existio contacto</span>
                      <md-radio-group class="radio-vertical" [(ngModel)]="valorRadio" (change)="opcionNoExistioContacto($event)">
                        <md-radio-button value="0">Yes</md-radio-button>
                        <md-radio-button value="1">No</md-radio-button>
                        <md-radio-button value="2">Yes third</md-radio-button>
                      </md-radio-group>
                    </div>
                  </div>
                  <div class="small-12 columns">
                    <md-select *ngIf="valorRadio == 1" placeholder="Causal" class="select_100">
                      <md-option value="0">Does not answer</md-option>
                      <md-option value="1">
                        Occupied phone</md-option>
                    </md-select>
                    <md-select *ngIf="valorRadio == 2" placeholder="No Contacto" [(ngModel)]="valorOpcion" class="select_100">
                      <md-option value="0">
                        Third does not provide new contact number but serves as reference</md-option>
                      <md-option value="1">
                        Third does not provide information</md-option>
                    </md-select>
                  </div>
                </div>
                <div *ngIf="valorOpcion == 3 || valorOpcion == 2">
                  <div class="small-6 columns">
                    <div class="row">
                      <div class="small-6 columns">
                        <span>phone</span>
                        <input type="tel" maxlength="10">
                      </div>
    
                    </div>
    
                  </div>
                </div>
              </div>
            </md-card>
          </div>
        </div>

This is coincidence ts

    import {
      Component,
      OnInit,
      Input,
      Output,
      EventEmitter
    } from '@angular/core';
    import {
      MdRadioChange
    } from "@angular/material";

    import {
      ValorGestionTelefonica
    } from "app/dto/datos";

    @Component({
      selector: 'app-coincidence',
      templateUrl: './coincidence.component.html',
      styleUrls: ['./coincidence.component.css']
    })
    export class CoincidenceComponent implements OnInit {
      @Input() titulo: number;
      @Input() indice: number;
      @Output() evaluarOpciones = new EventEmitter < ValorGestionTelefonica > ();

      constructor() {}

      ngOnInit() {}

      opcionNoExistioContacto(evento: MdRadioChange) {
        if (evento.source) {
          let valor = new ValorGestionTelefonica();
          valor.indice = this.indice;
          valor.valor = evento["value"];

          this.evaluarOpciones.emit(valor);
        }
      }
    }

This is panel tres html

    <app-coincidence *ngFor="let a of titulos; let i = index" [indice]=i [titulo]=a (evaluarOpciones)="evaluarOpciones($event)"></app-coincidence>

This is panel tres ts

    import {
      Component,
      OnInit,
      Input,
      Provider
    } from '@angular/core';
    import {
      ValorGestionTelefonica
    } from '../../dto/datos';

    enum Titulo {
      'Celular Coincidente con Reconocer' = 1, 'Primer Celular Reconocer' = 2
    }
    @Component({
      selector: 'app-panel-tres',
      templateUrl: './panel-tres.component.html',
      styleUrls: ['./panel-tres.component.css']
    })
    export class PanelTresComponent implements OnInit {

      titulos: string[];

      constructor() {}

      ngOnInit() {
        let titulos = Object.keys(Titulo);
        this.titulos = titulos.slice(titulos.length / 2);
        console.log(titulos);
        console.log("titulos");

      }

      evaluarOpciones(valor: ValorGestionTelefonica): void {
        console.log(valor.valor + "--" + valor.indice);
      }

    }

class ValorGestionTelefonica

    export class ValorGestionTelefonica {
      valor: any;
      indice: number;
    }

**Comment by mhegazy** [comment]
I would recommend logging this on https://github.com/angular/angular/issues

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
