### ISSUE TITLE
module resolution goes sideways when module-names contains '/'

### ISSUE THREAD

**Issue by sbAtGit** [Microsoft/TypeScript#16855]
TypeScript Version: 2.3.1 and 2.4.1

We use the amd module system and require-js.

We believe to have found a bug in the module resolution of typescript.
Since we have a huge javascript codebase, we only add new stuff in typescript and keep the javascript sources we already got. Hence the project mixes typescript and javascript files.

In new ts-files we need to require modules that are given as js-files.
We added a definition file (.d.ts) to define typings for the existing js-modules.

What we observed is that, the module resolution runs into resolving the import = require('...') statements to the js-files instead of the d.ts file, despite the fact that the js-files exist in a directory that should not be traversed by the module-resolution, because it does not exist in the 'traverse upwards or downwards' directory tree, but sideways to it.
Obviously this is caused by the module name we chose which contains a '/'. Unfortunately we can not change the name, because otherwise the javascript-client with require-js can not find the files.

Excluding the js-directory and setting 'allowJs' to false did not have any effect.

Here is the module resolution trace:
```txt
1>  Unknown output: ======== Das Modul "X/T" aus "C:/Users/xxx/Documents/Visual Studio 2015/Projects/TypeScriptHTMLApp4/TypeScriptHTMLApp4/U/A.ts" wird aufgelöst. ======== (Aufgaben-ID: 16)
1>  Unknown output: Die Art der Modulauflösung wird nicht angegeben. "Classic" wird verwendet. (Aufgaben-ID: 16)
1>  Unknown output: Die Datei "C:/Users/xxx/Documents/Visual Studio 2015/Projects/TypeScriptHTMLApp4/TypeScriptHTMLApp4/X/T.ts" ist nicht vorhanden. (Aufgaben-ID: 16)
1>  Unknown output: Die Datei "C:/Users/xxx/Documents/Visual Studio 2015/Projects/TypeScriptHTMLApp4/TypeScriptHTMLApp4/X/T.tsx" ist nicht vorhanden. (Aufgaben-ID: 16)
1>  Unknown output: Die Datei "C:/Users/xxx/Documents/Visual Studio 2015/Projects/TypeScriptHTMLApp4/TypeScriptHTMLApp4/X/T.d.ts" ist nicht vorhanden. (Aufgaben-ID: 16)
1>  Unknown output: Das Verzeichnis "C:/Users/xxx/Documents/Visual Studio 2015/Projects/TypeScriptHTMLApp4/TypeScriptHTMLApp4/U/node_modules" ist nicht vorhanden, Suchvorgänge darin werden übersprungen. (Aufgaben-ID: 16)
1>  Unknown output: Das Verzeichnis "C:/Users/xxx/Documents/Visual Studio 2015/Projects/TypeScriptHTMLApp4/TypeScriptHTMLApp4/node_modules" ist nicht vorhanden, Suchvorgänge darin werden übersprungen. (Aufgaben-ID: 16)
1>  Unknown output: Das Verzeichnis "C:/Users/xxx/Documents/Visual Studio 2015/Projects/TypeScriptHTMLApp4/node_modules" ist nicht vorhanden, Suchvorgänge darin werden übersprungen. (Aufgaben-ID: 16)
1>  Unknown output: Das Verzeichnis "C:/Users/xxx/Documents/Visual Studio 2015/Projects/node_modules" ist nicht vorhanden, Suchvorgänge darin werden übersprungen. (Aufgaben-ID: 16)
1>  Unknown output: Das Verzeichnis "C:/Users/xxx/Documents/Visual Studio 2015/node_modules" ist nicht vorhanden, Suchvorgänge darin werden übersprungen. (Aufgaben-ID: 16)
1>  Unknown output: Das Verzeichnis "C:/Users/xxx/Documents/node_modules" ist nicht vorhanden, Suchvorgänge darin werden übersprungen. (Aufgaben-ID: 16)
1>  Unknown output: Das Verzeichnis "C:/Users/node_modules" ist nicht vorhanden, Suchvorgänge darin werden übersprungen. (Aufgaben-ID: 16)
1>  Unknown output: Das Verzeichnis "C:/node_modules" ist nicht vorhanden, Suchvorgänge darin werden übersprungen. (Aufgaben-ID: 16)
1>  **Unknown output: Die Datei "C:/Users/xxx/Documents/Visual Studio 2015/Projects/TypeScriptHTMLApp4/TypeScriptHTMLApp4/X/T.js" ist vorhanden – sie wird als Ergebnis der Namensauflösung verwendet. (Aufgaben-ID: 16)
1>  Unknown output: ======== Der Modulname "X/T" wurde erfolgreich in "C:/Users/xxx/Documents/Visual Studio 2015/Projects/TypeScriptHTMLApp4/TypeScriptHTMLApp4/X/T.js" aufgelöst. ======== (Aufgaben-ID: 16)
```

And this is a screenshot of the project setup, which should be sufficient to reproduce the problem.
![ts module resolution issue](https://user-images.githubusercontent.com/29794402/27729207-36c75748-5d85-11e7-8622-a11dad8294fe.png)

```

**Expected behavior:**
Module resolution recognizes the definition in the d.ts file and does not resolve to the js-file.

**Actual behavior:**
Resolution concludes to the js-file, which causes it to be used as an input for the compilation which raises the error shown saying '...the file ... T.js can not be written because it would override an input-file.'

**Comment by mhegazy** [comment]
I am not sure i understand the issue fully. if you provide more details of which part of the resolution you find problematic i can look more.

I can tell you thought that the `classic` module resolution historically works by walking up and then concatenating the module name. so in this case `X/T` it will look for a folder called `X` with a file called `T` as it walks up.

we have maintained this behavior to avoid breaking existing code that relied on this. our recommendation now is to use `node` as a resolution strategy, and set `baseUrl` to your project root instead.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
