### ISSUE TITLE
Parallelism - Need proposal, documentation, example & guideline for starter

### ISSUE THREAD

**Issue by fletchsod-developer** [Microsoft/TypeScript#1686]
The title above pretty much sum it up.  

No hurry on this and hopefully it will lead to healthy discussions.

There is conflicting knowledges on wanting to use parallism for javascript.  There isn't good info out there and ES6 / ES7 is starting to come together but not much on how to use them.

The lack of parallism kept coming back to haunt us as we're forcing ourselves to use plug-ins, JQuery promises and callback hells.

The idea is to start discussing parallism leading to new TypeScript issue ticket with proposal then attach this ticket to new TypeScript issue ticket, and close this ticket.

**Comment by fletchsod-developer** [comment]
.NET framework (for C#) have a Task API, something like Task.Run() for example.

**Comment by DanielRosenwasser** [comment]
There's no way to provide runtime support for actual parallelism. Web workers are your browser side facility, which have typings in our `lib.es6.d.ts which will be out for 1.4. On the Node side, you there are packages with relevant typings on DefinitelyTyped.

**Comment by fletchsod-developer** [comment]
What are the typings in TypeScript or DefinitelyTyped in Node.js?   What are the example of what they looks like?

Thanks.

**Comment by DanielRosenwasser** [comment]
First off, I realized you might mean concurrency, not parallelism. Use ES6 promises (currently typed [here](https://github.com/Microsoft/TypeScript/blob/cf8afc31244693361f7444acc12fa3025fca0458/bin/lib.es6.d.ts#L4718)). Other than that there is a proposal for [`async`/`await`](https://github.com/Microsoft/TypeScript/issues/1664).

For Web Workers, here[https://github.com/Microsoft/TypeScript/blob/cf8afc31244693361f7444acc12fa3025fca0458/bin/lib.es6.d.ts#L15362] are the typings as of this writing.

For Node.js, find a package that appeals to you. Then see if there exist typings in DefinitelyTyped. For instance, if you find parallel.js to be appealing, [use the parallel.js typing on DefinitelyTyped](https://github.com/borisyankov/DefinitelyTyped/blob/master/parallel/parallel.d.ts).

**Comment by fletchsod-developer** [comment]
Thanks.   The promises and async / await are something I will have to wait on, and for web browser products to catch up.

Thanks again.

**Comment by lethalman** [comment]
Promises already have a way to run parallel tasks and wait for all of them:

```javascript
await Promise.all([promise1, promise2]);
```

**Comment by fletchsod-developer** [comment]
That's true.  I have learned alot 1 year later from my last posting.  

One other nice addition here down below, something I saw over the summer.

Here's beautiful example of what to do with ES5, ES6 and ES7 when it comes to async, promise, etc. and the usual old versions.

http://www.sitepoint.com/javascript-goes-asynchronous-awesome/
