### ISSUE TITLE
Symbol tables should keep internal properties separate

### ISSUE THREAD

**Issue by sandersn** [microsoft/TypeScript#16868]
Right now symbol tables store things like `__call` and `__construct` alongside user-provided symbols. This forces us to mangle/unmangle symbols that start with two underscores. Instead, symbol tables should keep a map of user-provided symbols as before, but also provide optional properties for internals like `__call` et al.

When the `symbol()` type becomes available, the symbol table should also include an "dynamic names" map in addition to the "user-provided names" map.

**Comment by ahejlsberg** [comment]
In principle I agree, but the challenge here is to make a new representation not consume more memory. We allocate an awful lot of symbol tables (many of them very small), and we wouldn't want to double that number. The advantage of the current representation is that we can put it all in a single map.

**Comment by RyanCavanaugh** [comment]
Would welcome a PR that shows substantive perf improvement here (seems like the cognitive penalty is reasonably low), but either way this is speculative.
