### ISSUE TITLE
Support question - Webstorm, NPM symlinks, static type checking

### ISSUE THREAD

**Issue by ORESoftware** [Microsoft/TypeScript#16876]
Sorry on mobile right now. I am curious as to the state of following symlinks so that you can get static type checking across local symlinked NPM projects. Is this currently possible? If it is, are there instructions somewhere on how to accomplish this? AFAICT right now, it seems like type checking is not working when projects are symlinked with NPM link.

One related question - if I want to import types from a project X but project X is not a dependency of my project (nor do I want it to be), is there any other avenue besides making `@types/X` a devDependency of project? What I am afraid of is that @types/X will be out-of-sync with X itself.

If I can solve the out-of-sync problem, then I would fine with publishing types to `@types/X`, and sharing that type information. But that does not solve the original symlinking issue above, which remains a problem.

**Comment by DanielRosenwasser** [comment]
This really seems like something that is a better fit for StackOverflow. We don't have a set of instructions for setting this up, though investigating project-to-project references is something we're investigating, which may be related to what you're trying to accomplish.

**Comment by ORESoftware** [comment]
I might drop it on programmers.stackexchange.com -> probably a better place for this than SO.

but can you confirm that tsc doesn't work with NPM symlinks? It might be a Webstorm issue, less so tsc itself.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
