### ISSUE TITLE
In Type Compatibility chapter, something seems ambiguous.

### ISSUE THREAD

**Issue by powerformer** [Microsoft/TypeScript#16879]
As we see under `Private and protected members in classes`  headline.
`This allows a class to be assignment compatible with its super class`  seems ambiguous.I thought it might be `This allows a instance of a class to be assignment compatible with its super class`

```
class Animal {
  feet: number;
  constructor(name: string, feetNumber: number) {}
}

class Cat extends Animal {
  constructor(theName: string, theFeetNumber: number) {
    super(theName, theFeetNumber);
  }
}
// the Cat class and it's super class
let tom: Animal = Cat;

// the instance of Cat class and the Cat's super class
let jessica: Animal = new Cat('jessica', 4);
```

![image](https://user-images.githubusercontent.com/26423749/27759058-6418d190-5e57-11e7-93c4-c1caba83860e.png)

If I'm wrong, please fix it.

**Comment by ikatyang** [comment]
`tom` is considered an instance of Animal in this case:

```ts
let tom: Animal = Cat; // failed
```

If you want to specify the class itself, you have to use something like `Constructor`: 

```ts
type Constructor<T> = new (...args: any[]) => T;

let tom: Constructor<Animal> = Cat; // passed
```

**Comment by pathurs** [comment]
Try this in VSCode:

`let cat = Cat; //let cat: typeof Cat
let kitten = new Cat('Pat', 4); //let kitten: Cat
let dog = Animal; //let dog: typeof Animal
let puppy = new Animal('Alice', 4);` //let puppy: Animal

As @ikatyang said, you cannot convert those types like that.

Cat and Animal are Constructors, they do NOT equal to the type Cat and Animal, respectively.

**Comment by DanielRosenwasser** [comment]
In the future, consider asking questions like this in StackOverflow. Thanks!

**Comment by powerformer** [comment]
I understand, thanks!

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
