### ISSUE TITLE
Compiler API behaves differently than CLI when using reflection

### ISSUE THREAD

**Issue by thevtm** [Microsoft/TypeScript#16872]
**TypeScript Version:**  2.4.1

I really like using TS, its a great language makes me a least 3x more productive and happy comparing to JS. :smile: 
But I managed to run into a weird behavior when I was trying to do some exploration testing on [class-transformer](https://github.com/pleerock/class-transformer).
The test would fail indicating that an object was an instance of class `Weapon` when it should have been `Map`.
I noticed that this problem only occurred when the code was run through `jest`. Doing `tsc` then `node` worked just fine.
[So I created an issue in the `ts-jest` repository.](https://github.com/kulshekhar/ts-jest/issues/257)
@kulshekhar (creator of [`ts-jest`](https://github.com/kulshekhar/ts-jest/issues/257)) managed to narrow down the issue to the standalone compiler `tsc` and the compiler API.

**Code**
[Repository](https://github.com/kulshekhar/typescript-reflection-difference) run `npm test`
```ts
import "reflect-metadata";
import { plainToClass, Type } from "class-transformer";

export class Weapon {
  constructor(public model: string,
    public range: number) {
  }
}

export class User {
  public id: number;
  public name: string;

  @Type(() => Weapon)
  public weapons: Map<string, Weapon>;
}

export const plainUser = {
  id: 1,
  name: "Max Pain",
  weapons: {
    firstWeapon: {
      model: "knife",
      range: 1,
    },
    secondWeapon: {
      model: "eagle",
      range: 200,
    },
    thirdWeapon: {
      model: "ak-47",
      range: 800,
    },
  },
};

const classedUser = plainToClass(User, plainUser);

console.log("classedUser is instance of User?", classedUser instanceof User);
console.log("classedUser.weapons is instance of Map?", classedUser.weapons instanceof Map);
console.log("classedUser.weapons is instance of Weapon?", classedUser.weapons instanceof Weapon);
```
Transpiler:
```ts
import * as tsc from 'typescript';
import * as fs from 'fs';
import * as path from 'path';

const content = fs.readFileSync(path.join(__dirname, '..', 'direct.ts'), 'utf8');
const config = tsc.readConfigFile(path.join(__dirname, '..', 'tsconfig.json'), file => {
  const read = tsc.sys.readFile(file);
  return read;
});

const transpiled = tsc.transpile(content, config.config.compilerOptions);
fs.writeFileSync(path.join(__dirname, 'transpiled.js'), transpiled, 'utf8');
```

**Expected behavior:**
```
Running code transpiled from CLI:
classedUser is instance of User? true
classedUser.weapons is instance of Map? true
classedUser.weapons is instance of Weapon? false

Running code transpiled using the typescript package:
classedUser is instance of User? true
classedUser.weapons is instance of Map? true
classedUser.weapons is instance of Weapon? false
```
User class generated by `tsc`:
```js
var User = (function () {
    function User() {
    }
    __decorate([
        class_transformer_1.Type(function () { return Weapon; }),
        __metadata("design:type", Map) // NOTICE THE "MAP" HERE
    ], User.prototype, "weapons", void 0);
    return User;
}());
```

**Actual behavior:**
```
Running code transpiled from CLI:
classedUser is instance of User? true
classedUser.weapons is instance of Map? true
classedUser.weapons is instance of Weapon? false

Running code transpiled using the typescript package:
classedUser is instance of User? true
classedUser.weapons is instance of Map? false
classedUser.weapons is instance of Weapon? true
```
User class generated by calling `transpile()` form the API:
```js
var User = (function () {
    function User() {
    }
    __decorate([
        class_transformer_1.Type(function () { return Weapon; }),
        __metadata("design:type", Object) // NOTICE THE "OBJECT" HERE
    ], User.prototype, "weapons", void 0);
    return User;
}());
```

**Comment by rbuckton** [comment]
The `transpile` (and `transpileModule`) functions unconditionally set `isolatedModules`, `noLib`, and `noResolve` to true. As a result, we cannot resolve `Map` to its constructor and instead return `Object`.

**Comment by thevtm** [comment]
Thank you!

`ts-jest` is using `transpileModule`. So should I tell the author to avoid that?

**Comment by bcruddy** [comment]
@rbuckton is there another approach that would be more effective?

**Comment by rbuckton** [comment]
I'm discussing this with the team. There are some cases where we attempt to emit the type with fallback (something like `__metadata("design:type", typeof Map === "function" ? Map : Object)`) when `isolatedModules` is set. We need to investigate to determine if we are missing a case that should be triggering that here.

**Comment by asvetliakov** [comment]
Just run into this issue. Workaround for now:
```
lib.ts:

const MyMap = Map;
const MyDate = Date;
export { MyMap as Map};
export { MyDate as Date};


consumer.ts:
import { Map, Date }  from "./lib";

export class Test {
  @SomeDecorator()
  public weapons: Map<string, string>;
}
```

**Comment by eyelidlessness** [comment]
Is there any progress on this? This is a blocker for anyone trying to use Jest's `onlyChanged` flag in a project that depends on decorator metadata.

**Comment by GeeWee** [comment]
We're working on this in #439 currently in ts-jest.

**Comment by mhegazy** [comment]
Fix should be in `typescript@next` today, and in `typesript@2.9.1` next week.

**Comment by csuich2** [comment]
Just confirmed the issue is resolved in typescript@next. I'll confirm with 2.9.1 when it is released.

Thanks!
