### ISSUE TITLE
VS 2015 Preview massive use RAM

### ISSUE THREAD

**Issue by flaticols** [Microsoft/TypeScript#1687]
Sometimes VS with open TypeScript project (I'm testing with another languages, machine, and VS 2013. 
Reproduced only on VS2015 Preview and only in TS projects) can use gigabytes of RAM.
![vsml](https://cloud.githubusercontent.com/assets/7881854/5766516/38240508-9d13-11e4-9e7b-db618662a3c6.png)

it is not necessarily associated with TS, but it's reproduced only in TS projects.

**Comment by danquirk** [comment]
Yikes. Are you able to share the associated project? How large is it (in terms of files or LOC)? Is this only happening after VS has been open for awhile or does it happen very quickly?

**Comment by flaticols** [comment]
Project very small (~15 files and ~4k of LOC).
Now I have found more information. The sequence of actions leading to such behavior:
1. Open our solution.
2. Open two ts files from different projects and 1 HTML file from any project.
3. Close one TS file and HTML.
4. In open file, you have seen how text editor start work very slow.
5. In Task Manager you have seen how VS use ~ +10 MB of RAM every seconds. Until then, until you fall

**Comment by mhegazy** [comment]
@flaticols can you give the latest version of TypeScript ([TypeScript 1.4](http://blogs.msdn.com/b/typescript/archive/2015/01/16/announcing-typescript-1-4.aspx)) a try and see if this issue still reproduces?

**Comment by flaticols** [comment]
@mhegazy in 1.4 don't reproduced

**Comment by mhegazy** [comment]
Thanks @flaticols for trying it out. i will close the issue for now. please reopen if you do see it again. thanks again!

**Comment by flaticols** [comment]
@mhegazy  thanks for you!
