### ISSUE TITLE
ternary type inference is wrong

### ISSUE THREAD

**Issue by Spongman** [Microsoft/TypeScript#16870]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

**Code**

```ts
class Base { }
class Derived1 extends Base { }
class Derived2 extends Base { }

var t1 = (Math.random() < 0.5) ? "asdasd" : 34;
// t1: string | number

var t2 = (Math.random() < 0.5) ? new Derived1() : new Derived2();
// t2: Derived1
```

**Expected behavior:**
````
// t2: Derived1 | Derived2
````

I understand the shapes are the same, but this means the runtime types don't match up with the static type.

**Comment by kitsonk** [comment]
TypeScript uses a structural type system.  To TypeScript, an instance of `Derived1` and `Derived2` look the same, so as it infers the type, it sees that there is no structural difference between `Derived1` and `Derived2` and so doesn't create a union.

Here, there is a structural difference between the two types, so you get what you expect:

```ts
class Base { }
class Derived1 extends Base {
	foo = 'bar'
}
class Derived2 extends Base {
	bar = 1
}

var t1 = (Math.random() < 0.5) ? "asdasd" : 34;
// t1: string | number

var t2 = (Math.random() < 0.5) ? new Derived1() : new Derived2();
// t2: Derived1 | Derived 2
```

JavaScript behaves in a structural way in everything except the `instanceof` operator.  The discussion of some sort of nominal typing support for TypeScript is covered in issue #202 (as well as loads of other information on the subject).

**Comment by Spongman** [comment]
> there is no structural difference between Derived1 and Derived2

really? `(new Derived1()).constructor !== (new Derived2()).constructor`

**Comment by RyanCavanaugh** [comment]
Please read the FAQ https://github.com/Microsoft/TypeScript/wiki/FAQ

**Comment by kitsonk** [comment]
> really? `(new Derived1()).constructor !== (new Derived2()).constructor`

And for the record, those are pointers to functions that _ermmm_ have the same structure...  This is, I am afraid, basic TypeScript concepts.
