### ISSUE TITLE
Object Literal destructuring assignment fails when LHS is parenthesized

### ISSUE THREAD

**Issue by rbuckton** [Microsoft/TypeScript#1688]
The following is valid ES6[1], however the second case results in an error during compilation:
```js
({ a } = o);
({ a }) = o; // error TS2364: Invalid left-hand side of assignment expression.
```

[1] Tested in Firefox Nightly

**Comment by NoelAbrahams** [comment]
Superscript<sup>1</sup>

`<sup>1</sup>`

**Comment by JsonFreeman** [comment]
I do not think this is valid, per section 12.14.5:
>In certain circumstances when processing the production AssignmentExpression : LeftHandSideExpression = AssignmentExpression the following grammar is used to refine the interpretation of LeftHandSideExpression.

Then it lists the destructuring grammar productions, but they do not include parenthesized expressions. So I think this is by design.
