### ISSUE TITLE
Invalid output of dynamic import with template string argument in ES5.

### ISSUE THREAD

**Issue by odensc** [Microsoft/TypeScript#16886]
**TypeScript Version:**  2.4.1 / nightly (2.5.0-dev.20170629)

**Code**

```ts
import(`./${"module"}`)
```

**Expected behavior:**
Output of:

```ts
import("./" + "module");
```

**Actual behavior:**
Output of:

```ts
(import)("./" + "module");
```

Using `"target": "es5"`  and `"module": "esnext"`, TypeScript outputs invalid syntax for the dynamic import expression, wrapping it in parentheses.

Using a target of `es2015` or higher, TypeScript outputs valid syntax with no parentheses.

This is only happens if `import` is given a template string.

**Comment by ikatyang** [comment]
It seems duplicate of https://github.com/Microsoft/TypeScript/issues/16763

**Comment by odensc** [comment]
@ikatyang Thanks. I searched the issues for "es5", but that issue doesn't say it anywhere - so it must have not came up. I'll close this issue and mention in the other one that it only happens in es5.
