### ISSUE TITLE
why is compile-time error occurring in the code

### ISSUE THREAD

**Issue by softwhygo** [Microsoft/TypeScript#16884]
The code comes from the website(http://www.typescriptlang.org/docs/handbook/advanced-types.html) :
```typescript
function extend<T, U>(first: T, second: U): T & U {
    let result = <T & U>{};
    for (let id in first) {
        (<any>result)[id] = (<any>first)[id];
    }
    for (let id in second) {
        if (!result.hasOwnProperty(id)) {
            result)[id] = second[id];
        }
    }
    return result;
}
```

 modify the code slightly：
```typescript
function extend<T, U>(first: T, second: U): T & U {
    let result = <T & U>{};
    for (let id in first) {
        result[id] = first[id];
    }
    for (let id in second) {
        if (!result.hasOwnProperty(id)) {
            (<any>result)[id] = (<any>second)[id];
        }
    }
    return result;
}
```
Just remove the type assertion for result and first in the fourth line。
I thought that the code above will be correct，because result is defined as T & U which is considered a type containing both properties from T and U, so that accessing result[keyof T] is valid, since keyof T is assignable to keyof (T & U)。

**Comment by porglezomp** [comment]
Hey, please change your code blocks to be
````
```typescript
code
```
````
instead of `` `code` `` to make your code blocks readable. It's very hard to tell what the problem is with the current form.

**Comment by softwhygo** [comment]
@porglezomp thank you very much 
I have changed the formate

**Comment by ikatyang** [comment]
`any` is assignable to everything, so that `result[id] = (<any>first)[id]` is valid.

```ts
first //=> T
<any>first //=> any
(<any>first)[id] //=> any
```

---

The reason there is an `<any>` before the `first` is that TS inferred `id` as `string` instead of `keyof T` in the past, the docs needs update.

**Comment by softwhygo** [comment]
@ikatyang 
maybe ，result don't have the property "id"

**Comment by ikatyang** [comment]
`result` is defined as `T & U`, that is, it is considered a type contains both properties from `T` and `U`, so that access `result[keyof T]` is valid, since `keyof T` is assignable to `keyof (T & U)`, for example:

```ts
type First = {a: number, b: string};
type Result = First & {c: boolean};

type Id = keyof First; //=> 'a' | 'b'
type ResultId = keyof Result; //=> 'a' | 'b' | 'c'

declare const result: Result;
declare const id: Id;
declare const resultId: ResultId;

result[id] //=> string | number
result[resultId] //=> string | number | boolean
```

**Comment by softwhygo** [comment]
@ikatyang 
I don't agree with you .maybe ,first has excess properties with respect to T,like following:
```typescript
interface Itest{
  name:string
}
function func(par:Itest){
  //code
}
let obj={
  name:"wang",
  age:20
}
func(obj);
```

**Comment by ikatyang** [comment]
Ah, I'm just explain the type-level operation, see https://github.com/Microsoft/TypeScript/issues/12936 and https://github.com/Microsoft/TypeScript/issues/12936#issuecomment-284590083 for those needs exact types.

**Comment by softwhygo** [comment]
@ikatyang 
thank you very much 
because of your answer ，I think of some other questions.
so ,i modefied the question

**Comment by softwhygo** [comment]
@ikatyang 
您好，如果有时间，用汉语帮我解释一下吧，我又修改了一下问题，如果按照您的思路，result[id] = first[id]这样就是正确的，但是实际上会报错

**Comment by ikatyang** [comment]
@softwhygo `T` 和 `U` 的交集有可能会导致某一属性冲突，就像下面的例子：

`(T & U)[key]` might be conflict with `T[key]`, consider the following case:

```ts
interface T1 {
    a: boolean;
    b: string;
}

interface T2 {
    a: boolean;
    b: number;
}

type T = T1 & T2;

type Ta = T['a']; //=> boolean
type Tb = T['b']; //=> string & number

declare const t: T;
declare const t1: T1;

Object.keys(t1).forEach((k: keyof T1) => {
    t['b'] = t1['b'];
//  ^^^^^^ [ts]
//         Type 'string' is not assignable to type 'string & number'.
//           Type 'string' is not assignable to type 'number'.
});
```

**Comment by softwhygo** [comment]
@ikatyang 非常感谢台湾的朋友，我来自山东青岛，欢迎来玩
