### ISSUE TITLE
Object is possibily undefined, but it's not

### ISSUE THREAD

**Issue by screendriver** [Microsoft/TypeScript#16889]
**TypeScript Version:**  2.4.1

**Code**

```ts
type cb = () => void;
function foo(cb?: cb) {
  const defaultFn = () => {};
  cb = cb || defaultFn;
  function bar() {
    cb(); // here I get the compiler error
  }
  bar();
}
```

**Expected behavior:**

The function `foo` should call `second()`.

**Actual behavior:**

I get `Object is possibily 'undefined'` in that line where I left a comment.

I know it is not a good idea to reasign function arguments. Following code would work as expected:

```ts
type cb = () => void;
function foo(cb?: cb) {
  const defaultFn = () => {};
  const innerCb = cb || defaultFn; // don't override argument
  function bar() {
    innerCb()
  }
  bar();
}
```

But should the TypeScript compiler  not be smart enough to recognize the closure? It only happens in the callback function `onSomethingHappened`. If I write it in the scope of the function `foo` it works as well. I only get the compiler error in the closure:

```ts
type cb = () => void;
function foo(cb?: cb) {
  const defaultFn = () => {};
  cb = cb || defaultFn;
  cb(); // no closure
}
```

PS: I know I could work with default arguments in the example above but my real production code is far more complex as this one 😉

**Comment by ikatyang** [comment]
```ts
type cb = () => void;

function foo(cb?: cb) {
  const defaultFn = () => {};
  cb = cb || defaultFn;

  function bar() {
    cb(); // <-- should check if undefined first, error as expected
  }

  assignUndefinedToCb(); // <------ TS won't know what did you do to `cb`

  bar(); // 💥

  function assignUndefinedToCb() {
    cb = undefined;
  }
}
```

See https://github.com/Microsoft/TypeScript/issues/9998 for more details.

**Comment by screendriver** [comment]
Big thank you! It seems that TypeScript is more intelligent than I 😂 👍👍
