### ISSUE TITLE
TS 2.4's "May only specify known properties" behavior is too restrictive

### ISSUE THREAD

**Issue by AlexGalays** [Microsoft/TypeScript#16885]
**TypeScript Version:**  2.4.1

**Code**

```ts
function test<P extends { p?: number }>(props: P) {
  console.log(props)
}

test({ hello: true })
```

**Expected behavior:**
It should compile as the `props` argument structurally extends { p?: number }.
This is a useful behavior as when  the `p` property is present, I want to type check it, but it should be optional and I want to retain the passed type as a whole for further inference (the example is simplified).
e.g this is a dynamic config object with a few special, privileged property names.

**Actual behavior:**
```
error TS2345: Argument of type '{ hello: boolean; }' is not assignable to parameter of type '{ p?: number | undefined; }'.
  Object literal may only specify known properties, and 'hello' does not exist in type '{ p?: number | undefined; }'.
```

**Comment by sylvanaar** [comment]
Optional properties work just like required properties during type resolution, you have to supply the property, you can't just leave it out.

```Typescript
function test<P extends { p?: number }>(props: P) {
  console.log(props)
}

test({ hello: true, p:undefined })
`

**Comment by AlexGalays** [comment]
This isn't convenient or intuitive though, and it's only since version 2.4

**Comment by sylvanaar** [comment]
Actually, see the breaking change for weak types introduced in 2.4. 

{p?: number} is a weak type. I missed that.

https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes

**Comment by AlexGalays** [comment]
Oh, I randomly tried to add an index signature then saw it was mentioned in the release notes in the first place; it works now :)

```
function test<P extends { p?: number, [key: string]: {} | undefined }>(props: P) {
  console.log(props)
}
```
