### ISSUE TITLE
String literals doesn't work with object childs

### ISSUE THREAD

**Issue by fathyb** [Microsoft/TypeScript#16894]
**TypeScript Version:**  2.3.4

**Code**

```ts
const obj = {
    type: 'literal'
}
const type = 'literal'
const type2 = obj.type
const type3 = obj.type as 'literal'

// error: Argument of type 'string' is not assignable to parameter of type '"literal"'
void function(arg: 'literal') {}(obj.type) 

// error: Argument of type 'string' is not assignable to parameter of type '"literal"'
void function(arg: 'literal') {}(type2)

// works
void function(arg: 'literal') {}(type)

// works
void function(arg: 'literal') {}(type2 as 'literal')

// works
void function(arg: 'literal') {}(type3)

```

**Expected behavior:**
It should accept string literals from objects

**Actual behavior:**
We need to manually cast the variable to the literal type

**Comment by rbuckton** [comment]
This is intended behavior as we widen `'literal'` to `string` in an object literal with no contextual type.

If you instead were to write:

```ts
const obj: { type: 'literal' } = { type: 'literal' };
const type2 = obj.type;
```

Then you would see the behavior you anticipate. We do not infer `'literal'` for `obj.type` in this case is it would break many other use cases of `const obj = { x: 'a' }; obj.x = 'b';`.
