### ISSUE TITLE
Built-in transformers break parent node links during transformation

### ISSUE THREAD

**Issue by jwbay** [Microsoft/TypeScript#16891]
**TypeScript Version:**  2.4.1

**Code**

```ts
const path = require('path');
path.resolve('a');
```

Compiled with
```ts
transpileModule(source, {
	compilerOptions: {
		jsx: JsxEmit.React,
		newLine: NewLineKind.LineFeed,
		sourceMap: true,
		target: ScriptTarget.ES5,
	},
	fileName: 'module.tsx',
	reportDiagnostics: true,
	transformers: {
		after: [transformer],
	},
});
```

What `transformer` does is actually not important here -- the SourceFile it's passed already has some missing links in the AST after passing through the built-in transformers.

**Expected behavior:**
Transformed nodes have an intact `.parent` reference.

**Actual behavior:**
Transformed nodes often (always?) have an undefined `.parent` reference. For this code specifically, `node.statements[0].declarationList.parent` is undefined, presumably because the first line has been changed to `var path = require('path')`.

**Comment by rbuckton** [comment]
This is the intended behavior. `parent` pointers are only valid on original parse-tree nodes. One of the main reasons for this is that we do not want to mutate the `parent` pointer of parse-tree nodes that we reuse in the transformation as those nodes may also be reused during incremental parsing. We also don't want to recreate an entire subtree that will generally remain unchanged.

Instead, if your transformer needs to make decisions based on the ancestors of a node, you must track the parent yourself as you descend through the tree.
