### ISSUE TITLE
Mixins. No TS2339 `property does not exists`

### ISSUE THREAD

**Issue by WiseBird** [Microsoft/TypeScript#16898]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

**Code**

Code with error:
![2](https://user-images.githubusercontent.com/1745378/27783883-1300124e-5fe9-11e7-81a8-7ed40fa15f51.png)

When mixin is used TS stops reporting missing property:
![1](https://user-images.githubusercontent.com/1745378/27783926-3b20ec1c-5fe9-11e7-99b5-579d093712a2.png)

[Playground](http://www.typescriptlang.org/play/index.html#src=type%20Constructor%3CT%3E%20%3D%20new(...args%3A%20any%5B%5D)%20%3D%3E%20T%3B%0D%0A%0D%0Afunction%20Mixin%3CT%20extends%20Constructor%3Cany%3E%3E(Base%3A%20T)%20%7B%0D%0A%20%20%20%20return%20class%20extends%20Base%20%7B%0D%0A%20%20%20%20%20%20%20%20field%20%3D%201%3B%0D%0A%20%20%20%20%7D%3B%0D%0A%7D%0D%0A%0D%0Aclass%20Base%20%7B%20%7D%0D%0A%0D%0Aclass%20Child%20extends%20Mixin(Base)%20%7B%0D%0A%20%20%20%20do()%20%7B%0D%0A%20%20%20%20%20%20%20%20console.log(this.field1)%3B%0D%0A%20%20%20%20%7D%0D%0A%7D)

**Comment by olegdunkan** [comment]
You have constraint in `MIxin` function `<T extends Constructor<any>`  therefore by default type of `this` has string index signature with any type (`{[key:string]:any}`). 
You have to change constraint to   `<T extends Constructor<{}>`.

**Comment by WiseBird** [comment]
Oh, shame on me. Thank you.
