### ISSUE TITLE
Formatter dedents 'catch' after 'if'

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#16890]
**TypeScript Version:**  nightly (2.5.0-dev.20170629)

**Code**

```ts
function f() {
	try {
		if (1)
			return 1;
		return 2;
	} catch (e) {
		return 3;
	}
}
```

Place the cursor after `e` and type `rror`.

**Expected behavior:**

No formatting changes.

**Actual behavior:**

```ts
function f() {
	try {
		if (1)
			return 1;
		return 2;
} catch (error) {
		return 3;
	}
}
```

There's no error without the `if`.

**Comment by mhegazy** [comment]
do not see this locally.
