### ISSUE TITLE
Return statement expression in the contextual typing 

### ISSUE THREAD

**Issue by olegdunkan** [Microsoft/TypeScript#16899]
I've asked the question https://stackoverflow.com/questions/44854711/contextual-typing-in-typescript

@DanielRosenwasser gave me the answer but for part of my question that is well described in the specification. 

Here it is:
```ts 
class A {
    x: number;
}

class B extends A {
    y: number;
}

var f1: { (y: A): void } | { (y: B): void };
f1 = (y)=>{} // y :any

var f2: { (x: number): (y: A) => void } | { (x: number): (y: B) => void };
f2 = ((x) => { return (y)=>{}; }); //y :A
````
In the first `f1` assignment `y` gets `any` type and that case is described in [spec](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#410-function-expressions), because 
`{ (y: A): void } | { (y: B): void }` type combines call signatures with different parameters type.
But in the case of `f2` assignment, return statement  expression of `(x)=>{return (y)=>{};}` arrow function 
 is contextually typed by the same type  `{ (y: A): void } | { (y: B): void }` according the referred above section of the specification. But in this case the type `{ (y: A): void } | { (y: B): void }` is reduced to `{y:A}:void}` and `y` has the `A` type. And we can see that it is by design:
```ts
function getReturnTypeOfSignature(signature: Signature): Type {
            if (!signature.resolvedReturnType) {
                if (!pushTypeResolution(signature, TypeSystemPropertyName.ResolvedReturnType)) {
                    return unknownType;
                }
                let type: Type;
                if (signature.target) {
                    type = instantiateType(getReturnTypeOfSignature(signature.target), signature.mapper);
                }
                else if (signature.unionSignatures) {
//*********************************************************************************************
                    type = getUnionType(map(signature.unionSignatures, getReturnTypeOfSignature), /*subtypeReduction*/ true);
//*********************************************************************************************
                }
                else {
                    type = getReturnTypeFromBody(<FunctionLikeDeclaration>signature.declaration);
                }
                if (!popTypeResolution()) {
                    type = anyType;
                    if (noImplicitAny) {
                        const declaration = <Declaration>signature.declaration;
                        const name = getNameOfDeclaration(declaration);
                        if (name) {
                            error(name, Diagnostics._0_implicitly_has_return_type_any_because_it_does_not_have_a_return_type_annotation_and_is_referenced_directly_or_indirectly_in_one_of_its_return_expressions, declarationNameToString(name));
                        }
                        else {
                            error(declaration, Diagnostics.Function_implicitly_has_return_type_any_because_it_does_not_have_a_return_type_annotation_and_is_referenced_directly_or_indirectly_in_one_of_its_return_expressions);
                        }
                    }
                }
                signature.resolvedReturnType = type;
            }
            return signature.resolvedReturnType;
        }
```
	
The same contextual type is in both cases but in the first place `tsc` compares for parameter equivalence, in the second makes reduction using `getUnionType`, why does typescript apply different strategies to at first glance the same cases?
I expected the same behavior for `f1` and for `f2`. 
I know that maybe there is some reason to implement this approach, what is the reason?

**Comment by kitsonk** [comment]
Why not wait for Daniel to respond to you on StackOverflow, instead of opening another issue here?  It was the weekend, people do have lives.

**Comment by olegdunkan** [comment]
@kitsonk yes you are right, sorry, I am closing the issue and will wait for answer at stackoverflow. Sorry, please!
