### ISSUE TITLE
Follow-up from Codeplex: TypeScript and JSDoc not playing well together

### ISSUE THREAD

**Issue by dandv** [Microsoft/TypeScript#16897]
Just wanted to bring attention to this issue from Codeplex, [TypeScript and JSDoc not playing well together](http://typescript.codeplex.com/workitem/504). It's linked from https://github.com/jsdoc3/jsdoc/issues/272 and I guess a number of people would be curious about an update since 2012. Thanks!

**Comment by mhegazy** [comment]
So this is another request for https://github.com/Microsoft/TypeScript/issues/10, or there is more specific requests here?

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
