### ISSUE TITLE
Type inference based on expression "target"

### ISSUE THREAD

**Issue by jeffijoe** [Microsoft/TypeScript#16903]
**TypeScript Version:**  2.4.0

**Code**

```ts
export type Extractor<T> = (item: T) => string
export type Comparator<T> = (a: T, b: T) => number

export function createStringComparator<T> (extractor: Extractor<T>): Comparator<T> {
  return function compare (a, b) {
    const strA = (extractor(a) || '')
    const strB = (extractor(b) || '')

    if (strA < strB) {
      return -1
    }

    if (strA > strB) {
      return 1
    }

    return 0
  }
}

// in another file..
interface IStuff {
  name: string
}

const arrOfStuff: IStuff[] = [{ name: 'Test1' }, { name: 'Test2' }]

arrOfStuff.sort(createStringComparator(x => x.name)) // not inferred
```

**Expected behavior:**

The generic input to `createStringComparator` should be inferred from usage (by passing it to a function that expects `(a: IStuff, b: IStuff) => number`).

**Actual behavior:**

Type is not being inferred.

**Comment by sylvanaar** [comment]
This seems to be working in the latest dev build.  I can't reproduce it.

**Comment by jeffijoe** [comment]
@sylvanaar if you paste it into a TypeScript playground it should give you an error. :)

**Comment by olegdunkan** [comment]
@sylvanaar I've reproduce it and it works

**Comment by olegdunkan** [comment]
@jeffijoe playground is not often up to date according to my feelings

**Comment by jeffijoe** [comment]
@olegdunkan so you're saying you can't reproduce the error?

**Comment by sylvanaar** [comment]
https://github.com/Microsoft/TypeScript/pull/16535

**Comment by jeffijoe** [comment]
@sylvanaar oh excellent! Any idea when this is slated for official release?

**Comment by sylvanaar** [comment]
I can point you towards some information, but I do not know.

https://blogs.msdn.microsoft.com/typescript/2017/03/27/typescripts-new-release-cadence/

**Comment by jeffijoe** [comment]
Thanks! I guess I can close this then :)
