### ISSUE TITLE
cant use setter on a class members

### ISSUE THREAD

**Issue by itayod** [Microsoft/TypeScript#16907]
**typescript version:** 2.3.3

**Code**

```
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'elevator',
  templateUrl: './elevator.component.html',
  styleUrls: ['./elevator.component.scss']
})
export class ElevatorComponent implements OnInit {
  @Input() floor: number;

  constructor() { }

  set floor(value){

  }

}


```

**Expected behavior:**
I expect to be able to use setter on the floor member

**Actual behavior:**
I get this error: Duplicate identifier 'floor'. !!!!

**Comment by sylvanaar** [comment]
Make the name of the field different than the property.

**Comment by itayod** [comment]
Actually I wanted to use the setter for change detection...
if i change the name of the field I won't be able to do that,
I mean i can do that with `ngOnChanges ` but I think using a setter is much more elegant.

**Comment by kitsonk** [comment]
@itayod that is not how JavaScript, and therefore TypeScript works.  You cannot have a value property and a setter property of the same name.  You can have a getter and setter that reads and sets a value from another property, or you can have a value property, not both.

This is fairly basic JavaScript, and these sorts of questions should be asked on Gitter or StackOverflow.  As how to implement the `@Input` decorator with a setter and a getter, you would need to discuss it in an Angular 2 forum.  This is not a TypeScript issue, it is preventing you from creating invalid JavaScript.

**Comment by itayod** [comment]
Thanks for the answer,

This is a es5 class with class member and a setter,
basically this is what i wanted to do with my angular component to detect a change in my member:
```
var Class = function() {
	this.member = 'member'
}
Class.prototype = {
	set member(val) {
  	console.log('member changed')
  }
}
var c = new Class();
c.member = 'member2';
```

**Comment by kitsonk** [comment]
Don't redeclare the member... [a setter is sufficient](http://www.typescriptlang.org/play/#src=import%20%7B%20Component%2C%20OnInit%2C%20Input%20%7D%20from%20'%40angular%2Fcore'%3B%0D%0A%0D%0A%40Component(%7B%0D%0A%20%20selector%3A%20'elevator'%2C%0D%0A%20%20templateUrl%3A%20'.%2Felevator.component.html'%2C%0D%0A%20%20styleUrls%3A%20%5B'.%2Felevator.component.scss'%5D%0D%0A%7D)%0D%0Aexport%20class%20ElevatorComponent%20implements%20OnInit%20%7B%0D%0A%0D%0A%20%20constructor()%20%7B%0D%0A%20%20%20%20%20%20this.floor%20%3D%202%3B%0D%0A%20%20%7D%0D%0A%0D%0A%20%20%40Input%20set%20floor(value)%7B%0D%0A%0D%0A%20%20%7D%0D%0A%0D%0A%7D) (though TypeScript doesn't model write only properties, which is what you are creating).  All TypeScript does anyways is move any intializers to the constructor anyways:

```ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'elevator',
  templateUrl: './elevator.component.html',
  styleUrls: ['./elevator.component.scss']
})
export class ElevatorComponent implements OnInit {

  constructor() {
      this.floor = 2;
  }

  @Input set floor(value){

  }

}
```

**Comment by itayod** [comment]
Ok, so I guess that the problem is the decorator as you said.

Thanks.

**Comment by kitsonk** [comment]
The property descriptor is passed to decorator, so the decorator _could_ support a setter only property, but the would be, as you imply, an ng2 thing.
