### ISSUE TITLE
Format inserting unnecessary indentation when line starts with semicolon

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#16909]
From https://github.com/Microsoft/vscode/issues/29827

**TypeScript Version:**  2.4.1

**Code**

Format the following code:

```ts
const a = 'b'
;(() => { console.log('c') })()
```

**Expected behavior:**

```ts
const a = 'b'
; (() => { console.log('c') })()
```

**Actual behavior:**
Indentation added:

```ts
const a = 'b'
    ; (() => { console.log('c') })()
```

**Comment by rightaway** [comment]
Could an option be included to not add a space after the semicolon? So in this example the formatted result would be the same as the original code.

**Comment by mhegazy** [comment]
duplicate of https://github.com/Microsoft/TypeScript/issues/10392
