### ISSUE TITLE
Math.floor() and Math.ceil() descriptions are wrong

### ISSUE THREAD

**Issue by inad9300** [Microsoft/TypeScript#16900]
**TypeScript Version:**  2.4.0

**Code**
The documentation says about [Math.ceil()](https://github.com/Microsoft/TypeScript/blob/02547fe664a1b5d1f07ea459f054c34e356d3746/tests/cases/conformance/decorators/1.0lib-noErrors.ts#L551) (the equivalent goes for [Math.floor()](https://github.com/Microsoft/TypeScript/blob/02547fe664a1b5d1f07ea459f054c34e356d3746/tests/cases/conformance/decorators/1.0lib-noErrors.ts#L566)):

```ts
    /**
      * Returns the smallest number greater than or equal to its numeric argument. 
      * @param x A numeric expression.
      */
    ceil(x: number): number;
```

Compare this with [MDN's description](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/ceil):
> The Math.ceil() function returns the smallest _integer_ greater than or equal to a given number.

**Comment by mhegazy** [comment]
A PR would be appreciated.

**Comment by DanielRosenwasser** [comment]
Thanks @gagoman!
