### ISSUE TITLE
Getting an "UNABLE_TO_GET_ISSUER_CERT_LOCALLY" while using "tsd" command

### ISSUE THREAD

**Issue by davedevv** [Microsoft/TypeScript#16905]
I'm trying to use the below **tsd** command to install angular type definition files in my project. 

`tsd install angular --resolve --save`

**TypeScript Version:**  2.3.4

However when I try to do that, I'm getting the below error.

    [ERR!] node : v7.8.0
    [ERR!] tsd  : 0.6.5
    [ERR!] Error: unable to get local issuer certificate
    [ERR!] CODE : UNABLE_TO_GET_ISSUER_CERT_LOCALLY
    [ERR!] unable to get local issuer certificate

Can someone help?

**Comment by ikatyang** [comment]
I thought [`tsd`](https://github.com/DefinitelyTyped/tsd) was [deprecated](https://github.com/DefinitelyTyped/tsd/issues/269)...

Have you tried `npm install @types/angular`?

**Comment by davedevv** [comment]
Yes!. That's resolved the issue!. Thanks @ikatyang :+1:
