### ISSUE TITLE
SUGGESTION: Revise docs to make adoption faster and easier

### ISSUE THREAD

**Issue by bodawei** [microsoft/TypeScript#16910]
I'm doing a bit of a "bake off" between TypeScript and Flow (as, I suspect, are many others). I've got project with a couple tens of thousands of lines of JavaScript that I want to move to a more well typed system. I think there are several ways you can remove some significant barrier to adoption located purely in your docs.

The simple mechanics of making the code changes for both things is pretty straightforward.  However, the process of figuring out how to re-jigger my build and test processes as part of an incremental transition is near trivial with Flow (add 'flow' to my babel presets), and a nightmare with TypeScript (how do I get a hybrid javascript and typescript codebase through karma and get code coverage).  I'm sure it is doable, but I think it would benefit your cause dramatically to put more examples and detailed guidance in https://www.typescriptlang.org/docs/handbook/integrating-with-build-tools.html ).

As part of my transition, I find myself frequently consulting your docs in a window on the side of my screen. The responsive layout design you have happens to make me scroll through half a screen of "what's new in TypeScript x.y" back to 1.1 before I can get to the useful docs.  It's a nit, but it's a painful nit if one's bouncing around the docs a lot.

More importantly, in at least my corner of the world, there's a lot of movement towards the ES style of modules (import/export). You've got a lot of documentation space devoted to various other module systems, and your namespace system, both of which seem less relevant, looking forward.  I wonder if it would benefit your docs to be reorganized to focus on the "present and future" case, and most some of the other stuff into a "support for the present and past".

More guidance about how to bridge JS and TS might be nice (I don't know how many people are like me, and migrating an existing code base).  In particular, more guidance about where and how to create individual type definitions to parallel the implementations that I've got in files that I'm not ready to migrate to TS yet would be pretty useful.  The current docs for migrating are good, but don't really get into the stuff that causes one to gnash one's teeth and lose an hour trying to figure out how to get a single line to not give an error.

My macro point is: as someone new to flow and typescript, both seem similar at the basic level, TypeScript has some attractive features beyond what flow has (enums, decorators, private and readonly members), but the impediments towards quickly and easily dropping TypeScript in are not small, and we know that people will often abandon in the face of those kinds of hurdles. That concerns me when it comes to adoption of your tools.

**Comment by mhegazy** [comment]
We have talked about making this page (integrating-with-build-tools) somewhere more prominent, and making it a page on the site by itself. 
We would appreciate suggestions here on how to make the docs more approachable and more beneficial to new users.

**Comment by bodawei** [comment]
I definitely think tackling as much of the "quick recipes for all the common build tools/etc", while a bunch of work, would be quite valuable.

**Comment by RyanCavanaugh** [comment]
We've decided this sort of thing to be out of scope for our official documentation efforts, since it's largely "How it best works *today*" and quickly goes out of date.
