### ISSUE TITLE
Typescript Automatic Type Acquisition cache update

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#16912]
_From @orenklein on July 2, 2017 12:39_

Typescript cache for typings (@types) is global and it is not automatically updated:
1. It would be great to have an option to update the typescript typings cache.
2. Updating typings cache can be achieved by deleting the content of @types folder and reload vs code - it should be considered mentioning in the documentations under ATA
3. In case a developer works on multiple projects with different versions of packages - Is there any better way other than manually and specifically install typings for each project?

_Copied from original issue: Microsoft/vscode#30011_

**Comment by mhegazy** [comment]
> Typescript cache for typings (@types) is global and it is not automatically updated:

A small correction, as of https://github.com/Microsoft/TypeScript/pull/16374, the cache is refreshed with every version of the TS installed. so still global, but per TS version.

> 2. Updating typings cache can be achieved by deleting the content of @types folder and reload vs code - it should be considered mentioning in the documentations under ATA

A PR to the wiki would be highly appreciated.

> 3. In case a developer works on multiple projects with different versions of packages - Is there any better way other than manually and specifically install typings for each project?

We have an issue allowing storing ATA data locally in https://github.com/Microsoft/TypeScript/issues/14231. I suggest adding this scenario there.

> 1. It would be great to have an option to update the typescript typings cache.

We could add a command that deletes the cache, but we have deemed this operation to be rather in frequent, and deleting the folder is equivalent in nature any ways.
And I think https://github.com/Microsoft/TypeScript/issues/14231 would be a better solution for this scenario as well, so need to worry about the cache, you can manage it locally, and delete it if you so choose.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
