### ISSUE TITLE
ReferenceError not given when compiling

### ISSUE THREAD

**Issue by uushuo** [Microsoft/TypeScript#16919]
**TypeScript Version:**  2.4.1 

**Code**

```ts
// A.ts
class A {
}

// Main.ts
var a = new A();
```

**Expected behavior:**
Compiling Error excepted.

**Actual behavior:**
js file(output) is generated, and ReferenceError thrown in runtime

**Comment by kitsonk** [comment]
What does your `tsconfig.json` look like.  It appears you are compiling with no modules, which informs TypeScript that all your project files will be available at runtime.  You need to ensure that they are all loaded at runtime.

Basic questions like these though should be asked on Gitter or on StackOverflow.

**Comment by uushuo** [comment]
Thank you, but I do think this is an issue.
my `tsconfig.json` is quite simple,
```
{
    "compilerOptions": {
        "module": "commonjs",
        "sourceMap": true
    }
}
```
I don't know if any other flag works for this.
for more information, if `export` is given in class declaration, compiling error will given, which is as expected.

**Comment by rbuckton** [comment]
If your project has a tsconfig.json, by default TypeScript will include all TypeScript source files in the project folder and its subfolders. As @kitsonk commented above, both _A.ts_ and _Main.ts_ do not contain `import` or `export` declarations and are treated as global scripts. As such, the symbol for `A` is included in the global scope.

It is up to your application to ensure non-module scripts are loaded in the correct order.
