### ISSUE TITLE
Inferring type of function parameters from usage

### ISSUE THREAD

**Issue by yahiko00** [Microsoft/TypeScript#16916]
When dealing with large JavaScript codebases, it would be convenient if TypeScript could infer the type of function parameters from their usage in the body.

As a short example:

```ts
function inferenceParam(param) {
    let x = param * 3; // param is inferred to be a number as well as x
    ...
    let str = "Value of param : " + param; // Here param is implicitly casted to a string
    console.log(param.wrongProperty); // Error since param is a number and no wrongProperty exists on Number.
}
```

TypeScript inferred `x` is a number. I am just wondering if this could be possible the type inference could backtrack the type of `param`, also as a `number`?

**Comment by Kovensky** [comment]
`x` is inferred as a number because, no matter what the operand is, the result _will_ be a number.

```js
const x = ({ toString () { return '42' } }) * 3
console.log(typeof x, x) // "number", 126
```

TypeScript does not infer the type of function parameters, unless they come from a function expression's context.

**Comment by mhegazy** [comment]
Please see https://github.com/Microsoft/TypeScript/issues/15196

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
