### ISSUE TITLE
JavaScript parameter hints for local variable picking up signatures from @types 

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#16913]
From https://github.com/Microsoft/vscode/issues/29269

**TypeScript Version:**  2.4.1

**Code**
For a javascript project with `@types/jquery` installed. In the file:

```js
function foo() {
    const $ = 1
    $(
}
```

Trigger parameter hints on `$(`

**Expected behavior:**
No suggestion is shown or `$(): void` is shown. The latter is what happens if you use another variable name such as `a` instead of `$`

**Actual behavior:**
Suggestions for jquery are shown. Suggestions on `$.` do not show the jquery suggestions

**Comment by mhegazy** [comment]
the local `const $` shadows the jquery `$`. that is what is gonna happen at runtime as well.

**Comment by mhegazy** [comment]
misunderstood the issue. in a .js file the signature help behavior is rather probabilistic. so it will search for some function that has this name, and will show that to you. in this case, it is the `$`. but that is how we can do things like:

```js
function f(a) { 
    a.forEach( | )
}
```

and get help for `forEach`.

**Comment by simonsarris** [comment]
But why isn't the definition or re-definition of a var, even if that var is `$`, what that signature behavior search finds?

Is there a way to simply "turn off" jQuery typings here?

**Comment by mhegazy** [comment]
> Is there a way to simply "turn off" jQuery typings here?

add `"jquery"` to your `typeAquisition` field in your jsconfig.json:

```ts
{
    "compilerOptions": {
        "target": "es5"
    },
    "typeAcquisition": {
        "exclude": [
            "jquery"
        ]
    }
}
```
