### ISSUE TITLE
Specific config options for TSC

### ISSUE THREAD

**Issue by Matheus-Ribeiro95** [Microsoft/TypeScript#16926]
Hello guys!
Is there a way to specify things like "ident size", "new line at end of the file"<
Using webpack or tsconfig as itself?
Thanks adv.

**Comment by ikatyang** [comment]
There is no option for "ident size" and "new line at end of the file" in TSC, but there are options for them in [tslint](https://github.com/palantir/tslint) and [tsfmt](https://github.com/vvakame/typescript-formatter).

**Comment by kitsonk** [comment]
These general type questions should be asked on Gitter or StackOverflow.  This is the place for reporting suspected bugs with TypeScript.

**Comment by leonadler** [comment]
Take a look at [editorconfig](https://github.com/editorconfig/). This is a responsibility of the editor or a linter, not of the compiler.

**Comment by Matheus-Ribeiro95** [comment]
@ikatyang Oh, so configs in tslint will propagate in compiler process?! Thanks.

@kitsonk Sorry, my bad.

@leonadler This is really nice, thanks for this link! Saved.
