### ISSUE TITLE
Improve Error for Invalid Augmentation on Multiple Declarations

### ISSUE THREAD

**Issue by fny** [Microsoft/TypeScript#16929]
**TypeScript Version:**  2.4.0

I spent the last four hours trying to add a TypeScript declaration for an untyped module, and died a little inside when I realized this error message betrayed me:

    [ts] Invalid module name in augmentation. Module 'ephori' resolves to an untyped module at '/Users/faraz/Workspace/app/node_modules/ephori/dist/index.js', which cannot be augmented.

I interpret this to mean that I can't augment an untyped module, as in there was no way to add types to an existing untyped module, but as I learned through misery and luck, the message was trying to tell me I can't have two declarations like this in the same file:

```
declare global {
  const apples: string
}

declare module 'bananas' {
  export function throwBanana(): void
}
```

Can we pretty please improve this error message so I shan't have suffer in vain? 😇

**Comment by mhegazy** [comment]
that is not true. you can have a module augmentation and global augmentation in the same module. 

what you can not have, is augmentation to a module that was not defined initially. you need to define the module first.
The compiler tries to look for types for `ephori` every where and could not find any. it first looks in `ephori`'s package.json for `types` property (a la `main`), then it looks for `@types/ephori` to be there and did not find that either. it also looks under your `"paths"` in your tsconfig.json if you have a redirect to `"ephori"` definition, and none was found.

the simplest way to do this is to create a new .d.ts file, e.g. `addtional.d.ts` and add:
```ts
declare module "ephori" { 
    ...
}
```

**Comment by fny** [comment]
Ah, makes much more sense now. Thanks for the clarification! But I still think the error message in no way explains the issue.

The error message "[ts] Invalid module name in augmentation. Module 'ephori' resolves to an untyped module which cannot be augmented." Mentions nothing about a module not being found, and caused my misunderstanding of what was really happening, which you just corrected.

**Comment by mhegazy** [comment]
open to suggestions for a better error message.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Comment by jwalton** [comment]
Can we reopen this?  I just spent 20 minutes banging my head against a wall because I created a file called `/src/@types/json-schema-traverse.d.ts`, and inside I put:

```ts
import { JSONSchema4, JSONSchema6 } from "json-schema";
declare module 'json-schema-traverse' {
}
```

which caused this error, and it was only when I found this issue that I realized I should try:

```ts
declare module 'json-schema-traverse' {
    import { JSONSchema4, JSONSchema6 } from "json-schema";
}
```

And to be honest I still don't know why the first one complains that "json-schema-traverse" can't be augmented, but the second one works.  -_-
