### ISSUE TITLE
 Property 'style' does not exist on type 'Element'

### ISSUE THREAD

**Issue by itayod** [Microsoft/TypeScript#16920]
**TypeScript Version:** ~2.3.3

**Code**

```ts
  let floorElements = document.getElementsByClassName("floor");
    for(var i in floorElements) {
      floorElements[i].style.height = AppConstants.FLOOR_SIZE_IN_PX + 'px';
    }

```

**Expected behavior:**
Not display an error.
**Actual behavior:**
I get this error :  Property 'style' does not exist on type 'Element'

**Comment by ThomasdenH** [comment]
You need to cast the [`Element`](https://developer.mozilla.org/en-US/docs/Web/API/Element) to a [`HTMLElement`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement), which has got the style property.

**Comment by kitsonk** [comment]
The simplest way is to cast the return of `getElementsByClassName`:

```ts
let floorElements = document.getElementsByClassName("floor") as HTMLCollectionOf<HTMLElement>;
```

Again though, these sorts of general questions should be being asked in Gitter or on StackOverflow.

**Comment by itayod** [comment]
Ok thanks.

**Comment by Rep1ay** [comment]
@kitsonk it dosn't work with css style...I getting error "Property 'style' does not exist on type 'HTMLCollectionOf<HTMLElement>'."

**Comment by ThomasdenH** [comment]
The function returns a collection of elements, so to access their style you should loop over the elements or index them directly.

**Comment by rafaltybor** [comment]
https://stackoverflow.com/questions/48093614/typescritp-set-css-style-for-htmlcollectionofelement-nodecollectionelement/48110472#48110472

**Comment by chadupton** [comment]
@Rep1ay 

If you only have one element with that classname, try this:

let drawingBuffer:HTMLElement = document.getElementsByClassName("drawingBuffer")[0] as HTMLElement;

**Comment by CR7LOVE** [comment]
@chadupton   It works.Thank you!

**Comment by MrBugatti** [comment]
Syntactically best way for a single element (below). You don't need to identity the first element within array because it's the only element.

let drawingBuffer:HTMLElement = document.getElementsByClassName("drawingBuffer") as HTMLElement;

**Comment by Umaid1** [comment]
> @Rep1ay
> 
> If you only have one element with that classname, try this:
> 
> let drawingBuffer:HTMLElement = document.getElementsByClassName("drawingBuffer")[0] as HTMLElement;

Thanks it worked!

**Comment by dhruvitmakadia** [comment]
> 
> 
> Syntactically best way for a single element (below). You don't need to identity the first element within array if it's the only element.
> 
> const node = document.querySelector(element) as HTMLElement;

It Works thanks

**Comment by titusfx** [comment]
At current date you can do

`const node = document.querySelector<HTMLElement>(element);`

Which is cleaner than use `as` operator
