### ISSUE TITLE
[ts] Cannot find name 'PasswordCredential'

### ISSUE THREAD

**Issue by Gianfranco97** [Microsoft/TypeScript#16925]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

**Code**

```ts
var cred = new PasswordCredential({
  id: '1234',
  password: '1234'
})

```

**Expected behavior:**
PasswordCredential {idName: "username", passwordName: "password", additionalData: null, name: "", iconURL: ""…}

**Actual behavior:**
a mistake

**Comment by sylvanaar** [comment]
Where did you define PasswordCredential in an interface or a class?

**Comment by Gianfranco97** [comment]
I would not know how to define it, I just want to be able to use this new language feature https://developer.mozilla.org/en-US/docs/Web/API/PasswordCredential

**Comment by kitsonk** [comment]
Experimental features are generally not included in the libraries until the point where the get general browser support.  You would have to acquire the types from somewhere or create them yourself.

**Comment by Gianfranco97** [comment]
I've been looking for some interface that can serve me, but for now I find nothing u.u

**Comment by kitsonk** [comment]
So you will have to create your own...

```ts
declare global {
    interface PasswordCredentialConstructor {
        // stuff
    }

    interface PasswordCredential {
        // stuff
    }

    const PasswordCredential: PasswordCredentialConstructor;
}
```

**Comment by Gianfranco97** [comment]
Fine my friend, let me see what I can do
thanks for your attention n.n

**Comment by ahmedwaleed1** [comment]
Did anyone find solution ?

**Comment by TrogloGeek** [comment]
@ahmedwaleed1:  Yes, @kitsonk answered, you have to define the interface yourself so TypeScript is aware about this type.
