### ISSUE TITLE
ReferenceError: _this is not defined, if an arrow function is a static member of a class.

### ISSUE THREAD

**Issue by laszlopandy** [Microsoft/TypeScript#16924]
**TypeScript Version:**  2.4.0 / 2.4.1 / 2.5.0-dev.20170629

**Code**
```ts
/* TsBug.ts */
class Test {
    static member = async (x: string) => { };
}
Test.member("");
```
Compiled with: `tsc TsBug.ts --lib es2015.promise,es5`
Run with: `node TsBug.js` 

**Expected behavior:**
No output.

**Actual behavior:**
```
/..<snip>../TsBug.js:39
    Test.member = function (x) { return __awaiter(_this, void 0, void 0, function () { return __generator(this, function (_a) {
                                                  ^

ReferenceError: _this is not defined
    at Function.Test.member (/..<snip>../TsBug.js:39:51)
```

**Comment by ikatyang** [comment]
Something wrong between v2.3.4 and v2.4.0

![image](https://user-images.githubusercontent.com/8341033/27835892-82d32ab2-610f-11e7-948d-4474040df123.png)

**Comment by jwbay** [comment]
Ref: https://github.com/Microsoft/TypeScript/pull/16120
