### ISSUE TITLE
Failed to launch external program tsc -p ts spawn tsc ENOENT

### ISSUE THREAD

**Issue by kylerdanielster** [Microsoft/TypeScript#16927]
**TypeScript Version:**  2.4.1
**VSCode Version:** 1.3.1
**OS Version:** Linux Mint 18.1
**node:** 6.11.0
**npm:** 5.0.3

Steps to Reproduce:

Open VSCode insider from Nemo or from terminal
Try to run build task **Ctrl+Shift+B** (using tsc -p in task.json 'args')

tasks.json
```javascript
{
    "version": "0.1.0",
    "command": "tsc",
    "isShellCommand": true,
    "args": ["-p", "ts"],
    "showOutput": "silent",
    "problemMatcher": "$tsc"
}
```

helloworld.ts in **ts** folder
```typescript
class HelloWorld {
    
}
```
tsconfig.json
```javascript
{
    "compilerOptions": {
        "target": "es5",
        "outFile": "../js/app.js",
        "sourceMap": true
    }
}
```

Empty folder **js**

**Expected behavior:**
I believe that this setup should compile the typescrpt files in my project to js files and put them in my js folder.

**Actual behavior:**
When I hit **Ctrl+Shift+B** i get: 
**Failed to launch external program tsc -p ts.**
**spawn tsc ENOENT**
in the output window

Its worth noting that if I run the **tsc** command with args in the VSCode terminal window in my projects root directory (tsc -p ts) it **DOES** seem to work fine(I get the expected behavior). 

This issues is similar to #8434 
I do have custom code in my .profile and .bashrc, but in my case it does not matter if I open from the terminal or from the file explorer

running process.env.PATH in VScode dev tools console outputs the same path as running echo $PATH from my command line.

**Comment by leonadler** [comment]
This is normally caused by `tsc` not being in your $PATH. Double-check if your global node_modules/.bin is reachable outside of bash, e.g. via running `which tsc` in `sh`/`zsh`.

While not a fix for your issue per se, consider running the local `tsc` in your project:
```json
{
    "version": "0.1.0",
    "command": "node",
    "isShellCommand": true,
    "args": ["${workSpaceRoot}/node_modules/typescript/bin/tsc", "-p", "ts"],
    "showOutput": "silent",
    "problemMatcher": "$tsc"
}
```

This allows you to track the version of the TypeScript compiler you want to use in your package.json independent of the globally installed one (`npm i -g typescript`).

**Comment by kylerdanielster** [comment]
This worked.

Installed typescript locally with `npm i typescript` and changed tasks.json to 
```
{
    "version": "0.1.0",
    "command": "node",
    "isShellCommand": true,
    "args": ["{pathToWorkSpaceRoot}/node_modules/typescript/bin/tsc", "-p", "ts"],
    "showOutput": "silent",
    "problemMatcher": "$tsc"
}
```
Which as you say "allows you to track the version of the TypeScript compiler you want to use in your package.json independent of the globally installed one". Seems like a good idea. 

I think it is worth noting that: ~/.npm-global/bin is in my path which contains the tsc package. This should be equivalent to node_modules/.bin I believe. 

Regardless, running 'sh' and 'tcs' I get 'tsc: not found'.

**Comment by leonadler** [comment]
@kylerdanielster glad it solves your issue!
Just a little addendum, since you wrote "{pathToWorkSpaceRoot}", I assume you hard-coded the path - you can use the actual string `${workSpaceRoot}` so it works regardless of where you checkout the project.

**Comment by kylerdanielster** [comment]
@leonadler "${workSpaceRoot}/node_modules/typescript/bin/tsc" did not work for me, that is why I hard coded it. 

I played around with the path some more and "node_modules/typescript/bin/tsc" this did the trick as well.

Current task.json (in .vscode folder)
```
{
    "version": "0.1.0",
    "command": "node",
    "isShellCommand": true,
    "args": ["node_modules/typescript/bin/tsc", "-p", "ts"],
    "showOutput": "silent",
    "problemMatcher": "$tsc"
}
```

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
