### ISSUE TITLE
Compiler flag to specify line ending 

### ISSUE THREAD

**Issue by fMads** [Microsoft/TypeScript#1693]
All generated js-files have windows-style line endings.
It would be great, if we could specify the line endings - windows, unix etc.

We use PhpStorm as editor, and it keeps marking generated js, d.ts etc files as changed, even though the code is the same. The only difference is \n -> \r\n.

Relates to https://typescript.codeplex.com/workitem/258

**Comment by DanielRosenwasser** [comment]
I don't know if you'd get different results if the line endings were the same - but you could also [configure your editor's line ending options](https://www.jetbrains.com/phpstorm/help/configuring-line-separators.html)

**Comment by fMads** [comment]
I have configured the editor - but I think the difference is, that this is an external change to the files and the editor therefor isn't updating the line endings.
Git is also configures to use unix-style, so it will be commited with unix style line endings.

The main problem is, when we're changing branches, and the .ts files are changed in the new branch. The TSC will se the .ts file change and recompile the file and thus overwriting the .js file (which was committed with unix style line endings) with windows style line endings. It marks as a change in PhpStorm.

**Comment by mhegazy** [comment]
The line endings of the generated .js, .d.ts, and .sourcemap files are currently only dependent on the underlying system. so if you are running on windows you will always get /r/n if you are on macOS you would get /n. 

@fMads you want a new compiler flag to toggle line endings, correct?

**Comment by DanielRosenwasser** [comment]
If this is a matter of checking out something with Unix line endings, have you tried setting your git repo's `autocrlf` option?

**Comment by lilred** [comment]
@fMads: any particular reason you're committing the generated js files? I feel like they should be left out of the repo, just like binaries. Not being snarky, just curious.

**Comment by fMads** [comment]
@mhegazy Yes, a compiler flag would be great :)

@lilred You're proberbly right - that would be the best way to handle it.
We just don't have any post-processing of our code at our live systems. We commit and push to remote repo, when we do an update to our clients.
We could of course change it, so we compile the code at post-receive - but it's just easier doing it on dev-system (Before pushing)

**Comment by mhegazy** [comment]
updating the title for the issue.

@fMads, a PR would definitely be welcomed. The system now is wired to get the sys.newline, (see [program.ts L72](https://github.com/Microsoft/TypeScript/blob/a99b9584848baeaac88f5e5b57ac45580146f784/src/compiler/program.ts#L72)) the change would be to pass options.newLine instead.

**Comment by kmashint** [comment]
+1 for this feature of specifying a line ending.  GIT doesn't have quite the right mix of options for dealing with cross-platform line endings and the best I've found on a mixed team that deploys to UNIX-style systems is to just force those common line endings everywhere.  Yes, having JS files in version control may not be ideal but it's pragmatic.

**Comment by hranicka** [comment]
+1 for this feature of specifying a line ending.

**Comment by mhegazy** [comment]
Thanks @kmashint!
