### ISSUE TITLE
rest parameter does not play well with generic array

### ISSUE THREAD

**Issue by amir-arad** [Microsoft/TypeScript#16931]
**TypeScript Version:**  2.3.4

**Code**
```ts
//  error, defined as ???
type Method<A extends Array<any>, R = void> = (...args: A) => R;

// this is still passed
const foo: Method<[number, string], string> = (a: string, b: number) => a + b;
//                 ^^^^^^  ^^^^^^              ^          ^
```
**Expected behavior:**
pass validation
**Actual behavior:**
Error:(1, 47) TS2370:A rest parameter must be of an array type.

**Comment by amir-arad** [comment]
my current workaround (which I suggest adding to the lib.d.ts as an alternative) is:
```ts
 type Method0<R = void> = () => R;
 type Method1<T1, R = void> = (t1: T1) => R;
 type Method2<T1, T2, R = void> = (t1: T1, t2: T2) => R;
 type Method3<T1, T2, T3, R = void> = (t1: T1, t2: T2, t3: T3) => R;
 type Method4<T1, T2, T3, T4, R = void> = (t1: T1, t2: T2, t3: T3, t4: T4) => R;
```

**Comment by ikatyang** [comment]
It seems duplicate of https://github.com/Microsoft/TypeScript/issues/5331 and https://github.com/Microsoft/TypeScript/issues/5453.

**Comment by amir-arad** [comment]
thanks for the edit @ikatyang . seems like a duplicate indeed.
