### ISSUE TITLE
Module "none" not suggested when doing tsc --init

### ISSUE THREAD

**Issue by massimocode** [Microsoft/TypeScript#16941]
As per title

The tsconfig generated by tsc --init doesn't suggest "none" as an option for module.

Version 2.4.1

**Comment by DanielRosenwasser** [comment]
Why would it?

**Comment by DanielRosenwasser** [comment]
Just realized that this pertains to the comment placed in the tsconfig.json, and the request isn't that `tsc` should warn users to use `none`.
