### ISSUE TITLE
Regression: Promise-related type inferencing failing in 2.4.1

### ISSUE THREAD

**Issue by jiaweihli** [Microsoft/TypeScript#16940]
TypeScript Version: 2.4.1

After upgrading from 2.3.4, some tests fail to inference correctly.  An overloaded method that's called resolves to the wrong version, and the only workaround I can find is explicitly declaring the correct variable type to choose the correct overloaded method.

Here is a [repo/branch/CI with a repro](https://circleci.com/gh/jiaweihli/monapt/tree/upgrade-to-ts-2.4):

1.  [Baseline](https://circleci.com/gh/jiaweihli/monapt/71) - `master` on 2.3.4
2.  [Trying to upgrade to 2.4.1](https://circleci.com/gh/jiaweihli/monapt/72) - note the errors (lint needs to compile the files)
3.  [Forced type casts](https://circleci.com/gh/jiaweihli/monapt/73) - tests pass now

Each CI run is a single commit, you can jump to the Github links to see what changed.

**Comment by yuit** [comment]
@jiaweihli  could you share the small repo of the issue? also from reading the description, I think this may be the cause (https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#stricter-variance-in-callback-parameters)

**Comment by jiaweihli** [comment]
Here is the full branch I repro'd this on: https://github.com/jiaweihli/monapt/commits/upgrade-to-ts-2.4

**Comment by kitsonk** [comment]
> could you share the small repo of the issue?

> Here is the full branch I repro'd this on

😖

**Comment by jiaweihli** [comment]
The code is open-source, and I documented each step I took in a separate commit.  Each of these has also been run independently through CI.

Do you still need a small repro?

**Comment by kitsonk** [comment]
> Do you still need a small repro?

I am not part of the TypeScript team, but I think the answer will be yes.  It is like saying "go read through the TypeScript source code to find your issue, it is open source, all the commits are there."

**Comment by jiaweihli** [comment]
https://github.com/Microsoft/TypeScript/issues/17315
