### ISSUE TITLE
typeof x === "y" type guard not working in strict mode

### ISSUE THREAD

**Issue by Torwori** [Microsoft/TypeScript#16949]
**TypeScript Version:**  2.4.0

**Code**

```ts
interface Repro {
  env: {
    [key: string]: string | undefined;
  };
}

const process: Repro = {
  env: {
    PORT: "3000"
  }
};

if (typeof process.env.PORT === "string") {
  parseInt(process.env.PORT);
}
```

**Expected behavior:**
The code is valid and passes compilation.

**Actual behavior:**
`error TS2345: Argument of type 'string | undefined' is not assignable to parameter of type 'string'.`
`Type 'undefined' is not assignable to type 'string'.`

**Comment by RyanCavanaugh** [comment]
Duplicate #10442 - we don't currently narrow except by *declared* properties, and there is no declared property named `PORT`

**Comment by Lord-Haji** [comment]
;D
