### ISSUE TITLE
DOM File.lastModifiedDate is deprecated

### ISSUE THREAD

**Issue by cncolder** [microsoft/TypeScript#16942]
**TypeScript Version:**  2.4.1

**Code**
[https://github.com/Microsoft/TypeScript/blob/2a6aacd0ef614a38b08ef712adc377c13648f373/lib/lib.dom.d.ts#L3758](https://github.com/Microsoft/TypeScript/blob/2a6aacd0ef614a38b08ef712adc377c13648f373/lib/lib.dom.d.ts#L3758)

**Expected behavior:**

Add `lastModified` and leave `lastModifiedDate` there.

```ts
  readonly lastModified: number;
```

**Actual behavior:**

```log
file: 'file:///test.ts'
severity: '错误'
message: 'Property 'lastModified' does not exist on type 'File'.'
at: '56,14'
source: 'ts'
```

**Comment by kitsonk** [comment]
The lib files are generated by [TSJS-lib-generator](https://github.com/Microsoft/TSJS-lib-generator/) and changes to those files should be issues on that repo.  There are [contribution guidelines](https://github.com/Microsoft/TSJS-lib-generator/#contribution-guidelines) on how to raise a PR to change this.

**Comment by renchap** [comment]
Duplicate of #20354, solved by https://github.com/Microsoft/TSJS-lib-generator/pull/337

**Comment by mhegazy** [comment]
We still need to remove the deprecated property.

**Comment by saschanaz** [comment]
Has been removed by https://github.com/Microsoft/TSJS-lib-generator/pull/448.

**Comment by HolgerJeromin** [comment]
I think this issue can be closed. We have `lastModified` and no `lastModifiedDate` now:

```ts
interface File extends Blob {
    readonly lastModified: number;
    readonly name: string;
}
