### ISSUE TITLE
Infer arguments types from interface

### ISSUE THREAD

**Issue by patrick91** [Microsoft/TypeScript#16944]
I've tried to look for this issues, but I didn't find any. 
Here's an example of the problem:

```ts
interface IComponentLifecycle<P> {
  componentWillReceiveProps?(nextProps: Readonly<P>, nextContext: any): void;
}

interface IProps {
  hello: string;
}

class X implements IComponentLifecycle<IProps> {
  componentWillReceiveProps(nextProps) { // <-- nextProps is any
    // TODO: logic
  }
}
```

This is based on react's typings (that's how I found the issue).

Is this an expected behaviour or not?

**Comment by ikatyang** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/16590, see https://github.com/Microsoft/TypeScript/issues/1373 and https://github.com/Microsoft/TypeScript/pull/6118.

**Comment by patrick91** [comment]
Thanks, sorry I didn't find that issue, I'll close this
