### ISSUE TITLE
Unable to come up with d.ts file for this module

### ISSUE THREAD

**Issue by bpasero** [Microsoft/TypeScript#1695]
I require a module that I can new() up and I dont find a way in d.ts to express this.

Usage:
var mod = require("foo");
var foo = new mod();

I would come up with something like this in my d.ts file but I dont think its possible:

declare module "foo" {
  new():ISomething
}

**Comment by basarat** [comment]
You can do
```ts
declare module "foo" {
 var newAble:{
    new():ISomething
 }
 export = newAble;
}
```

**Comment by RyanCavanaugh** [comment]
Yep, `export =` is the correct way to model this.

**Comment by bpasero** [comment]
Thanks. In general I think d.ts creation needs better documentation. Is there somewhere else to go than the TypeScript documentation? Maybe a place with common patterns and snippets?

**Comment by basarat** [comment]
@bpasero https://github.com/Microsoft/TypeScript/wiki/Writing-Definition-Files#single-complex-object-in-external-modules ?

**Comment by bpasero** [comment]
Looks good. It seems on that page another solution is being presented where I can export the module with a name "foo" and a constructor function. https://github.com/Microsoft/TypeScript/wiki/Writing-Definition-Files#typing-4

**Comment by basarat** [comment]
> It seems on that page another solution is being presented where I can export the module with a name "foo" and a constructor function

Are you saying : *that* solution (https://github.com/Microsoft/TypeScript/wiki/Writing-Definition-Files#typing-4) is different from *this* (https://github.com/Microsoft/TypeScript/issues/1695#issuecomment-70282520)? 

If so, then I disagree. The only real difference is that I stripped it down for your case, used things inline (which is actually naughty of me as I've locked it out of type extensiblity) and wrapped it up in a `declare module "foo"` (which is a different concept covered here : https://github.com/Microsoft/TypeScript/wiki/Writing-Definition-Files#typing-3)

**Comment by bpasero** [comment]
Oh I see. In my case I need to be able to declare multiple modules, all of them potentially able to "new" them up. I think your variant should work nicely in this case.
