### ISSUE TITLE
why T can't be Undefined type

### ISSUE THREAD

**Issue by remoteTest** [microsoft/TypeScript#16965]
https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#3.11.4
S is assignable to a type T, and T is assignable from S, if S has no excess properties with respect to T (3.11.5) and one of the following is true:

S and T are identical types.
S or T is the Any type.
S is the Undefined type.
S is the Null type and T is not the Undefined type.
In the last line，the spec tells us that S is the Null type and T is not the Undefined type,why?

**Comment by DanielRosenwasser** [comment]
The spec predates TypeScript 2.0.

**Comment by softwhygo** [comment]
@thank you

**Comment by DanielRosenwasser** [comment]
Even so, `null` shouldn't be assignable to to `undefined`, and vice versa. Under `strictNullChecks`, only `undefined` is assignable to `undefined` and only `null` is assignable to `null`.

**Comment by softwhygo** [comment]
@DanielRosenwasser thank you very much

**Comment by crimx** [comment]
@DanielRosenwasser Under what circumstance would T be a Undefined type? As spec [mentioned](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#3.2.7):

> The `undefined` literal denotes the value given to all uninitialized variables and is ***the one and only*** value of the Undefined type. It is not possible to directly reference the Undefined type itself.
>
> ```javascript
> var e: Undefined;       // Error, can't reference Undefined type
>```

**Comment by softwhygo** [comment]
@crimx confusing me too

**Comment by expressiveco** [comment]
I lost some time due to this specification error in documentation.
But i learned something that i should check the publication date and the commit history to determine if easily possible that nothing has been changed since the publication so it is outdated for current version or not.
I hope that it will be upgraded as soon as possible and others will not be affected.

**Comment by RyanCavanaugh** [comment]
The spec is now an "archived" artifact and we won't be tracking defects against it anymore.
