### ISSUE TITLE
error: Property 'innnerHTML' does not exist on type 'DocumentFragment'

### ISSUE THREAD

**Issue by fiznool** [Microsoft/TypeScript#16966]
**TypeScript Version:**  2.3.4

**Code**

```ts
const container = document.createDocumentFragment();
container.innerHTML = '<p>Hello World</p>';
```

**Expected behavior:**

No error message

**Actual behavior:**

error: Property 'innnerHTML' does not exist on type 'DocumentFragment'

**Comment by kitsonk** [comment]
```js
console.log('innerHTML' in document.createDocumentFragment()); // false
```

[DocumentFragment](https://developer.mozilla.org/en/docs/Web/API/DocumentFragment) has a [Node](https://developer.mozilla.org/en-US/docs/Web/API/Node) interface, which does not include [`innerHTML`](https://dom.spec.whatwg.org/#node).

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
