### ISSUE TITLE
Support disabling weak type checking

### ISSUE THREAD

**Issue by smhc** [Microsoft/TypeScript#16968]
**TypeScript Version:**  2.4.1

**Expected behavior:**

Can compile projects using third party dependencies that have not been upgraded to support strict weak type checks in typescript 2.4.1.

**Actual behavior:**

Projects that depend on third party libraries that have 'weak type' errors cause compilation errors. The proposed workarounds are not possible when the type definitions reside in third party code.

**Proposed Solution:**

A flag to disable strict weak type checks.
Even better would be the ability to enable/disable similar strict checks for third party libraries (node_modules) selectively. 
The dependency may very well have a bug or poor definition, and it may or may not get fixed. But even if it does get fixed, the fix may be in a version that is impractical to upgrade to.

I hit the issue with protractor and was fortunately able to upgrade to a version that didn't have regressions. I am now hitting the problem with ag-grid: https://github.com/ceolter/ag-grid/issues/1745
This one doesn't seem like a 'bug', but rather a poor definition. If it is fixed, I may not be able to upgrade to the version it is fixed in.

**Comment by smhc** [comment]
Some further discussion of this is located here: https://github.com/ceolter/ag-grid/issues/1708

I thought weak type 'implements' may still be useful for code like the below. However typescript doesn't actually pick this up as an error.

```ts

// Library code

interface IDisposable {
    // implement if you want custom dispose code
    dispose?: () => boolean;
}

class DefaultThing implements IDisposable {
    // doesn't require custom dispose, but extenders should implement it correctly if they do
    public work(): number {
        return 0;
    }
}

// Project code

class MyThing extends DefaultThing {
    // want to inherit 'work()', but also the type checking of 'dispose(): boolean'
    public dispose(): string {  // want an error here
        return '';
    }
}
```

**Comment by RyanCavanaugh** [comment]
The referenced issue has an explanation from me of what you should be doing in that case.

**Comment by smhc** [comment]
Closing this issue as it is discussed elsewhere.
Will wait to see if many others are hit by the same problem that prevents being able to upgrade before following it up further.
