### ISSUE TITLE
Building with --target es6 in VS with release 1.4 fails

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#1696]
Building a project using --target es6 results in error:
File 'C:\program files(x86)/Microsoft SDKs/TypeScript/1.4/lib.es6.d.ts' not found

**Comment by mhegazy** [comment]
To work around it please include [lib.es6.d.ts](https://github.com/Microsoft/TypeScript/blob/release-1.4/bin/lib.es6.d.ts) in your project, or add a /// reference to it.

**Comment by mhegazy** [comment]
This should be resolved in the next VS release.

**Comment by goblinfactory** [comment]
It doesnt look like this is resolved yet, why is this marked as "fixed"? I downloaded the typescript extension (22/5/2015) for vs2013 and I still get this exact build error, should not have to "reference..include lib.es5.d.ts in the project, that'st still a bug IMHO?
