### ISSUE TITLE
Incorrect missing import quick fix suggested for colorful-text

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#16963]
From https://github.com/Microsoft/vscode/issues/30001#issuecomment-313264638

**TypeScript Version:**  2.4.1

**Code**
`package.json`

```json
{
  "name": "sand",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "colorful-text": "0.0.1"
  }
}

```

`index.js`:

```js
// @ts-check
import {bold} from 'colorful-text'
bold('')
```

`other.js`:
```ts
// @ts-check
bold('')
```

In `other.js`, try triggering the fix missing import quick fix on `bold`

**Expected behavior:**
See quick fix for `import from `'colorful-text'`

**Actual behavior:**
See quick fix for importing the `d.ts` file from the full path inside of `colorful-text`

![screen shot 2017-07-05 at 6 25 04 pm](https://user-images.githubusercontent.com/12821956/27891554-54386622-61af-11e7-8884-c47a7e703764.png)

Note that colorful-text ships with its own `d.ts` file listed in the `package.json`. However they do not use a module:

```ts
export declare function reset(text: string): string;
export declare function bold(text: string): string;
...
```

Changing the `d.ts` file to use a module fixes things:

```ts
declare module 'colorful-text' {
  export declare function reset(text: string): string;
  export declare function bold(text: string): string;
}
```

**Comment by minestarks** [comment]
@mjbvz I can repro this fine, but can't repro this bit at the end:
> Changing the d.ts file to use a module fixes things

In fact I see us ignoring the .d.ts file completely, regardless of how the module is declared. If I add the module declaration inside the current source file (or any other source file already included in the compilation), then we're fine. Is there a step you omitted to mention?

**Comment by mjbvz** [comment]
I believe I update the d.ts file and then restarted the ts server. After that, the import path was correct

**Comment by minestarks** [comment]
@mjbvz got it eventually, thanks.
