### ISSUE TITLE
Void doesn't collapse when intersected

### ISSUE THREAD

**Issue by yeerkkiller1** [Microsoft/TypeScript#16962]
**TypeScript Version:**  2.4.2 / nightly (2.5.0-dev.20170629)

**Code**

```ts
// Gives an error `Type '5' is not assignable to type 'void'.`
let withVoid: number & void = 5;
```

**Expected behavior:**
5 should satisfy the void shape, given that void has no requirements.

The documentation describes `void is a little like the opposite of any: the absence of having any type at all.`. So while an intersection with `any` adds 'everything' to a type, intersecting with 'void' seems like it should add 'nothing'.

In https://github.com/Microsoft/TypeScript/issues/10913 @mhegazy explains that `Given that void is the empty set, in the example, you can assign any thing to a void, but you can not assign void to anything.`, which seems to make sense, except in practice you cannot assign anything but `null`, `undefined` and `any` to void.

Previous I was using code that intersected types with `never` to erase the `never` type, but that behavior has been changed (fixed) in https://github.com/Microsoft/TypeScript/issues/16038 .

For backwards compatibility it makes sense that it is undesirable to have values assigned to void, but perhaps intersecting a type with void could collapse void, to allow the inverse of never.

This would allow the following code to compile without an error
```ts
type Obj = { x: void };
type ObjWithValue = Obj & { x: number };
type Value = { x: number };

let objWithValue: ObjWithValue;
let value: Value;

// Error: Type 'number' is not assignable to type 'void'.
objWithValue = value;
value = objWithValue;
```

Without this it seems like there is a deficit of a type that is truly the opposite of `any`. 

**Actual behavior:**
It gives a type error.

**Comment by yortus** [comment]
Could you use the type `{}`? That type 'adds nothing' to an intersection and compiles fine in your examples.

e.g.:
```ts
let withVoid: number & {} = 5;  // OK
```

**Comment by yeerkkiller1** [comment]
Oh, I didn't think that would work! Yep, that appears to be exactly what I need. Thanks!
