### ISSUE TITLE
Remove trailing comma from the last tsconfig setting

### ISSUE THREAD

**Issue by prashaantt** [Microsoft/TypeScript#16974]
**TypeScript Version:**  2.4.1 / nightly (2.5.0-dev.20170621)

The default generated `tsconfig.json` has a trailing comma for the `emitDecoratorMetadata` setting that's not required and often causes silent bugs.

**Current settings file**

```json
{
  {
    ...
    // "emitDecoratorMetadata": true,         /* Enables experimental support for emitting type metadata for decorators. */
  }
}
```

**Expected**
```json
{
  {
    ...
    // "emitDecoratorMetadata": true          /* Enables experimental support for emitting type metadata for decorators. */
  }
}
```

**Comment by RyanCavanaugh** [comment]
It's convenient to have this so you can move it to another location in the file without adding the comma yourself. How exactly is this causing problems?

**Comment by prashaantt** [comment]
OK, I can't speak for others but at least I tend to not move around these options at all — I only go out and enable or change them in-place, in which case this last option will always break the json. Still, I'll go ahead and make the (somehow weak) argument that not many are likely to place them before the 3 options already enabled by default because those 3 seem far more significant by virtue of being explicitly enabled.

There's already the slight constant friction of needing to add the comma after `"strict": true` whenever an option below it needs to be set, I thought this small change might help make things a bit smoother. :)

**Comment by simonua** [comment]
@RyanCavanaugh, does your same rationale apply to this enum example, and, more importantly, is this done deliberately by the TypeScript compiler? It gives us a bit of trouble with TSLint's _[no-trailing-comma](https://palantir.github.io/tslint/rules/trailing-comma/)_ rule.

```
enum Colors {
    Blue = "BLUE",
    Green = "GREEN",
    Red = "RED"
}
```
results in TypeScript definition with trailing comma:
```
declare enum Colors {
    Blue,
    Green,
    Red,
}
```

**Comment by RyanCavanaugh** [comment]
@simonua I would consider that a bug - we should write out the same commas you did

**Comment by simonua** [comment]
@RyanCavanaugh, glad to hear that. Thank you! Would you like me to create a new issue (and reference this) or is this current issue sufficient?

**Comment by RyanCavanaugh** [comment]
Please create a new issue. Thanks!

**Comment by rbuckton** [comment]
@prashaantt, can you elaborate on your comment that "the last option will always break the json"? As of TypeScript 2.4 we are a little bit more relaxed when parsing JSON files used by the compiler to improve the experience when using an editor to modify configuration.

I can see how it could make the tsconfig.json file unreadable in earlier versions of the compiler (which do not allow the trailing comma), though that can be remedied by manually removing the comma.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
