### ISSUE TITLE
type check issue

### ISSUE THREAD

**Issue by pankleks** [Microsoft/TypeScript#16986]
I know it's a tricky construction in begin with - but it was compiling fine before 2.4.

```ts
class Foo {
  [id: string]: { a?: number, b?: number };
  v1?: string;
}
```
with TSC 2.4.1, it gives me an error:
`TS2411: Property 'v1' of type 'string' is not assignable to string index type '{ a?: number, b?: number }'.`

**Comment by RyanCavanaugh** [comment]
See #16047 for details on this change
