### ISSUE TITLE
Formatter indents pasted method too far

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#16989]
**TypeScript Version:** nightly (2.5.0-dev.20170629)

**Code**

```ts
class C {

	m() {}
}
```

Copy the text from just after the `{` in `class C {` to just after the `}` in `m() {}`.
Paste it after the `}` in `m() {}`.

**Expected behavior:**

```ts
class C {

	m() {}
	
	m() {}
}
```

**Actual behavior:**

```ts
class C {

	m() {}
	
		m() {}
}
```

**Comment by mhegazy** [comment]
I think this is another VSCode specific issue.
