### ISSUE TITLE
No "sidecasting"

### ISSUE THREAD

**Issue by pauldraper** [Microsoft/TypeScript#16995]
**TypeScript Version:**  2.4

**Code**

```ts
interface A { }
interface B { }
class AandB implements A, B { }
const u: AandB = new AandB;
const v: A     = u;      // upcast
const w: B     = v as B; // downcast

const x: {a:number, b:number} = {a:0, b:1};
const y: {a:number}           = x;               // upcast
const z: {b:number}           = y as {b:number}; // downcast, ERROR
```

[Playground](https://www.typescriptlang.org/play/index.html#src=interface%20A%20%7B%20%7D%0D%0Ainterface%20B%20%7B%20%7D%0D%0Aclass%20AandB%20implements%20A%2C%20B%20%7B%20%7D%0D%0Aconst%20u%3A%20AandB%20%3D%20new%20AandB%3B%0D%0Aconst%20v%3A%20A%20%20%20%20%20%3D%20u%3B%20%20%20%20%20%20%2F%2F%20upcast%0D%0Aconst%20w%3A%20B%20%20%20%20%20%3D%20v%20as%20B%3B%20%2F%2F%20downcast%0D%0A%0D%0Aconst%20x%3A%20%7Ba%3Anumber%2C%20b%3Anumber%7D%20%3D%20%7Ba%3A0%2C%20b%3A1%7D%3B%0D%0Aconst%20y%3A%20%7Ba%3Anumber%7D%20%20%20%20%20%20%20%20%20%20%20%3D%20x%3B%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20upcast%0D%0Aconst%20z%3A%20%7Bb%3Anumber%7D%20%20%20%20%20%20%20%20%20%20%20%3D%20y%20as%20%7Bb%3Anumber%7D%3B%20%2F%2F%20downcast%0D%0A)

**Expected behavior:**

Both downcasts compile without error.

(Alternatively, neither downcast compiles.)

**Actual behavior:**

The class downcast compiles. The object literal downcast for `z` does not compile.

FYI, `u: A & B` also works

**Workaround:**

Upcast to `Object` first.

```ts
const x: {a:number, b:number} = {a:0, b:1};
const y: {a:number}           = x;
const z: {b:number}           = y as Object as {b:number};
```

**Comment by RyanCavanaugh** [comment]
That's a sidecast (?), not a downcast. There's no relation whatsoever between `y`'s declared type `{a: number}` and the target type `{ b: number }` - neither is a supertype nor subtype of the other. You can only type-assert between types where one is a subtype or supertype of the other.

**Comment by kitsonk** [comment]
And the earlier interfaces were empty, so they were simply recasts.  TypeScript is a _structural_ type system, not a _nominal_ one.

**Comment by gcnew** [comment]
Talking about sidecasting, shouldn't we take a second look at https://github.com/Microsoft/TypeScript/issues/14156? Sidecasting is allowed for literal types, which is both inconsistent and incorrect, for no apparent reason.

**Comment by pauldraper** [comment]
> TypeScript is a structural type system, not a nominal one.

Ah.

> That's a sidecast (?), not a downcast. 

In C#

```c#
interface A {}
interface B {}
class AandB : A, B {}
public class Program {
    public static void Main() {
        AandB x = new AandB();
        A y = x;      // upcast
        B z = y as B; // downcast/sidecast/whatever
    }
}
```

Similarly in Java. Can't really find anything about C# or Java sidecasting, so IDK what the proper terms are.

> You can only type-assert between types where one is a subtype or supertype of the other.

Ah.

```ts
const x1 = {a:0};
const y1 = {};

const x2 = x1 as {b:number}; // okay
const y2 = y1 as {b:number}; // not okay
```

That sems weird. The presence of `a:number` makes it no more or less likely to have `b:number`.

**Comment by kitsonk** [comment]
Because it is structural, and not nominal, classes and object literals are _duck typed_ in the sense that if they look like a duck and quack like a duck, they are equivalent.  A super type and a sub type are determined by their structural relationship, not their nominal relationship.  This is because JavaScript behaves largely in a structural way (with the exception of `instanceof` operator but let's not go there).

If you wanted to explore the assignability of interfaces and classes, you would have to have them be structurally different:

```ts
interface A { a: string; }
interface B { b: string; }
class AandB implements A, B { a = 'foo'; b = 'bar'; }
const u: AandB = new AandB;
const v: A     = u;      // this is fine
const w: B     = v as B; // nope, this is now a side cast
```

Also, casts are casts in TypeScript.  Basically if the compiler allows it, it trusts what you are saying.  This is because, even with good CFA, there are some assignments that can't be tracked by the type system, because JavaScript is so malleable...  So unless it _knows_ for certain you are doing something wrong, it will stop you, but even then, then you might be tempted to cast `as any` to really just go _a f* it, stop bugging me_.

Type `{}` relates to type `{ b: number }` (I am not so good on if it is strictly super or sub) but `{ b: number }` and `{ a: number }` are unrelated types, therefore TypeScript disallows it.  To demonstrate though _how_ `{}` could actually be `{ b: number }` at runtime, where TypeScript wouldn't notice it would be something like this:

```ts
const x1 = {};
Object.defineProperty(x1, 'b', { value: 0, enumerable: true, configurable: true, writable: true });
```

Now, `x1` contains a property `b` with a value of `0`.  TypeScript doesn't know that.  Yeah, if you are coming from C# or Java, it is foreign.  For those of us who have been living in JavaScript land, we are so used to a weakly typed language, that TypeScript doesn't seem so foreign.

Of course this would work...

```ts
const x1 = {};
const y1 = {a:0};

const x2 = x1 as {b:number}; // okay
const y2 = y1 as {a: number; b:number}; // this is fine!
```

**Comment by pauldraper** [comment]
I completely understand structural typing (though I wasn't aware TS has). Many type systems have it (Go, Scala sort of).

The main issue comes from not from structural typing but casting.

```
  Super
   /   \
SubA   SubB
```

Every type system with casting I know of (C, C++, Java, C#, Go, Scala, Closure JS) allows casting from SubA to SubB.

But TS does not.

```
           {}
         /    \
{a:number} {b:number}

```const x1 = {};
const y1 = {a:0};
const x2 = x1 as {b:number}; // okay
const y2 = y1 as {b:number}; // not okay
```

Why should the presence of `a:number` influence the possibility of `b:number`?

**Comment by RyanCavanaugh** [comment]
> Every type system with casting I know of (C, C++, Java, C#, Go, Scala, Closure JS, Flow) allows casting from SubA to SubB

Huh?

This isn't legal in C#. For example, you can't cast from `Button` to `TextBox` despite the common heritage of `Control`:
![image](https://user-images.githubusercontent.com/6685088/27977333-1118b7cc-631f-11e7-83ab-8f0320401505.png)

This isn't legal in Java https://stackoverflow.com/questions/21370179/java-casting-one-subclass-to-another

Flow doesn't even allow downcasting.

The intuition here is that your type assertion need to be plausible. It's plausible that someone gave you a `HTMLElement` that you know to actually be a `HTMLDivElement`. It's *not* plausible that someone gave you a `Truck` and you actually know it to be a `Dog` - there's a difference between *refining* to a subtype and just "let's make this a totally different type".

**Comment by pauldraper** [comment]
@RyanCavanaugh it is possible, with my qualication that _the SubA & SubB intersection is non-empty_ .

Button and TextBox are classes and C# types are such that a Button can never, ever, ever be a TextBox (well, except for null which is simultaneously everything). 

But if Button and TextBox are interfaces, then the intersection is not empty and it [does work](https://dotnetfiddle.net/EI15v9).

Same for Java, same for Scala. (I guess not for Flow -- my mistake.)

> It's not plausible that someone gave you a Truck and you actually know it to be a Dog

It is plausible, assuming a TruckDog is possible. http://www.littletikes.co.uk/big-dog-truck.html

Typescript says that JanitorPerson isn't castable to StudentPerson, even though Person is castable to StudentPerson and JanitorPerson is a Person. Were you to have Person, not specifically JanitorPerson, only then could you cast to StudentPerson.

It may not technically violate the Liskov substitution principle (since that operates on instances not types), but it comes pretty close.

**Comment by RyanCavanaugh** [comment]
> And I completely agree that it's good to reject casts between "totally different" types that share no instances.

> It is plausible, assuming a TruckDog is possible.

You can always synthesize some type that is a subtype of two other types. The two statements of "Some assertions should be rejected" and "You should allow it if some possible go-between type may exist" are contradictory.

**Comment by pauldraper** [comment]
> are contradictory

Not in general. Your example proved C# rejects known impossibilities.

> You can always synthesize some type that is a subtype of two other types. 

No. For example, you can't have a number & function subtype.

---

I concede the point. Any casting except upcasting is undesirable. So if TS chooses very special rules and is more awkward that other systems for casts, it's not a big deal.

Probably there are many other things more important things do to.
