### ISSUE TITLE
Missing type checking for lazy object literal initialization

### ISSUE THREAD

**Issue by leonchen** [Microsoft/TypeScript#16996]
**TypeScript Version:**  2.4.1

**Code**

```ts
interface Shape {
  color: string;
}

function getColor(s: Shape): string {
  console.log('shape:', s);
  return s.color;
}

let s = {} as Shape;
// s.color = 'green';

console.log('color:', getColor(s));
```

**Expected behavior:**
compiler error as s doesn't have the color property.
**Actual behavior:**
No compile error but getColor(s) returns undefined.

**Comment by RyanCavanaugh** [comment]
`{} as Shape` is a *type assertion* whose explicit purpose is to cause that sort of error not to occur.

**Comment by gcnew** [comment]
I'm asking out of curiosity: why and where would you expect a compile time error?

**Comment by leonchen** [comment]
At first, 'let s = {} as Shape;' looks like a bug to me until I read this article: https://basarat.gitbooks.io/typescript/docs/tips/lazyObjectLiteralInitialization.html. So I guess there is some magic happening just for the empty object as 'let s = { name: 'name' } as Shape;' will cause a compile error. But this magic isn't safe as there is no checking for the requirements of the interface. In the above example the color property is undefined while it should be string, and all the further usages may fail.
So I expect either '{} as Shape' should fail(as common type assertions) or the first time the variable gets used should fail(if lazy object literal initialization is considered to be a feature).
