### ISSUE TITLE
@types/bootbox gitving error

### ISSUE THREAD

**Issue by mantuonweb** [Microsoft/TypeScript#17006]
TypeScript Version:**  2.4.0 

 npm install @types/jquery @types/bootbox bootstrap jquery --save

```ts
import * as bootbox from 'bootbox'

```

**Expected behavior:**
Module should be added and application should be compiled
**Actual behavior:**
Application is not compiled and giving errors

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (4904,46): Duplicate identifier 'never'.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (4907,46): Generic type 'Promise<TR, TJ, any, TN>' requires 4 type argument(s).

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (4907,93): Generic type 'Promise<TR, TJ, any, TN>' requires 4 type argument(s).

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (4916,33): Duplicate identifier 'never'.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (4916,46): Duplicate identifier 'never'.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (4917,19): Duplicate identifier 'never'.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (4917,32): Duplicate identifier 'never'.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (4917,45): Duplicate identifier 'never'.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (4918,42): Generic type 'Promise<TR, TJ, any, TN>' requires 4 type argument(s).

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (4919,42): Generic type 'Promise<TR, TJ, any, TN>' requires 4 type argument(s).

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (4920,38): Generic type 'Promise<TR, TJ, any, TN>' requires 4 type argument(s).

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (4929,33): Duplicate identifier 'never'.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (4929,46): Duplicate identifier 'never'.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (4931,42): Generic type 'Promise<TR, TJ, any, TN>' requires 4 type argument(s).

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (4932,38): Generic type 'Promise<TR, TJ, any, TN>' requires 4 type argument(s).

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (4940,33): Duplicate identifier 'never'.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (4940,46): Duplicate identifier 'never'.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (4941,42): Generic type 'Promise<TR, TJ, any, TN>' requires 4 type argument(s).

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (4943,38): Generic type 'Promise<TR, TJ, any, TN>' requires 4 type argument(s).

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (4952,34): Duplicate identifier 'never'.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (4952,47): Duplicate identifier 'never'.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (4953,42): Generic type 'Promise<TR, TJ, any, TN>' requires 4 type argument(s).

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (4953,89): Generic type 'Promise<TR, TJ, any, TN>' requires 4 type argument(s).

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (4959,15): Type parameter name cannot be 'any'

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (4959,25): Duplicate identifier 'any'.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (4959,25): Type parameter name cannot be 'any'

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (4959,35): Duplicate identifier 'any'.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (4959,35): Type parameter name cannot be 'any'

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (4959,61): Generic type 'Deferred<TR, TJ, any, TN>' requires 4 type argument(s).

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (4959,100): Generic type 'Deferred<TR, TJ, any, TN>' requires 4 type argument(s).

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (4959,139): Generic type 'Deferred<TR, TJ, any, TN>' requires 4 type argument(s).

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (4962,33): Type parameter name cannot be 'any'

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (4962,43): Duplicate identifier 'any'.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (4962,43): Type parameter name cannot be 'any'

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (4962,56): Generic type 'Promise<TR, TJ, any, TN>' requires 4 type argument(s).

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (4979,29): Cannot find name 'object'.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (4996,29): Cannot find name 'object'.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5013,30): Cannot find name 'object'.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5066,44): Generic type 'Promise<TR, TJ, any, TN>' requires 4 type argument(s).

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5074,42): Generic type 'Promise<TR, TJ, any, TN>' requires 4 type argument(s).

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5086,42): Generic type 'Promise<TR, TJ, any, TN>' requires 4 type argument(s).

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5091,46): Generic type 'Promise<TR, TJ, any, TN>' requires 4 type argument(s).

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5103,25): Generic type 'PlainObject<T, any>' requires 2 type argument(s).

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5107,43): Generic type 'Promise<TR, TJ, any, TN>' requires 4 type argument(s).

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5267,15): All declarations of 'Event' must have identical type parameters.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5268,31): Cannot find name 'Partial'.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5268,31): The left-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5268,31): Operator '<' cannot be applied to types 'boolean' and '{ new (typeArg: string, eventInitDict?: PointerEventInit): PointerEvent; prototype: PointerEvent; }'.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5268,39): Cannot find name 'Pick'.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5268,59): The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5268,75): The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5268,87): The left-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5268,98): The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5268,110): The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5269,9): The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5269,28): The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5269,40): The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5269,51): The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5269,66): The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5269,78): The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5269,88): The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5269,98): The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5269,111): The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5270,9): The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5270,18): The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5270,31): The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5270,39): The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5270,51): The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5270,62): The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5270,74): The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5270,86): The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5270,98): The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5270,110): The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5271,9): The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5271,23): The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5271,39): The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5271,51): The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5271,63): The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5271,81): The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5271,95): The left-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5271,107): The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5278,24): Cannot find name 'TTarget'.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5285,15): Cannot find name 'TData'.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5292,25): Cannot find name 'TTarget'.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5293,24): Cannot find name '_Event'.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5300,24): Cannot find name 'TTarget'.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5307,17): Cannot find name 'TTarget'.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5312,20): Cannot find name 'object'.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5312,60): Generic type 'Event<TTarget, EventTarget, TData>' requires 3 type argument(s).

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5313,47): Generic type 'Event<TTarget, EventTarget, TData>' requires 3 type argument(s).

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5314,24): Cannot find name 'object'.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5314,64): Generic type 'Event<TTarget, EventTarget, TData>' requires 3 type argument(s).

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5315,51): Generic type 'Event<TTarget, EventTarget, TData>' requires 3 type argument(s).

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5325,52): Cannot invoke an expression whose type lacks a call signature.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5326,10): 'this' cannot be referenced in a module or namespace body.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5326,16): Cannot find name 'TContext'.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5326,26): Cannot find name 'eventObject'.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5326,46): Property 'Event' does not exist on type 'typeof JQuery'.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5326,52): Cannot find name 'TContext'.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5326,62): Cannot find name 'TData'.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5326,73): Cannot find name 'args'.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5326,79): Cannot find name 'any'.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5326,87): The '|' operator is not allowed for boolean types. Consider using '||' instead.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5326,102): Cannot find name 'any'.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5474,34): Generic type 'Callbacks<T, Function>' requires 2 type argument(s).

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5475,37): Generic type 'Deferred<TR, TJ, any, TN>' requires 4 type argument(s).

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5476,42): Generic type 'Event<TTarget, EventTarget, TData>' requires 3 type argument(s).

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5477,37): Generic type 'Deferred<TR, TJ, any, TN>' requires 4 type argument(s).

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5478,38): Generic type 'AjaxSettings<TContext, any>' requires 2 type argument(s).

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5480,44): Module 'JQuery' has no exported member 'Coordinates'.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5482,29): Generic type 'jqXHR<TResolve, any>' requires 2 type argument(s).

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5483,36): Generic type 'Promise<TR, TJ, any, TN>' requires 4 type argument(s).

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5484,54): Module 'JQuery' has no exported member 'NameValuePair'.

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/jquery/index.d.ts (5489,33): Generic type 'PlainObject<T, any>' requires 2 type argument(s).

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/bootbox/index.d.ts (89,49): Generic type 'JQuery<TElement, HTMLElement>' requires 2 type argument(s).

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/bootbox/index.d.ts (90,39): Generic type 'JQuery<TElement, HTMLElement>' requires 2 type argument(s).

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/bootbox/index.d.ts (91,65): Generic type 'JQuery<TElement, HTMLElement>' requires 2 type argument(s).

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/bootbox/index.d.ts (92,43): Generic type 'JQuery<TElement, HTMLElement>' requires 2 type argument(s).

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/bootbox/index.d.ts (93,63): Generic type 'JQuery<TElement, HTMLElement>' requires 2 type argument(s).

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/bootbox/index.d.ts (94,41): Generic type 'JQuery<TElement, HTMLElement>' requires 2 type argument(s).

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/bootbox/index.d.ts (95,64): Generic type 'JQuery<TElement, HTMLElement>' requires 2 type argument(s).

ERROR in /Users/mantu.nigam/Documents/DEMO/hello/node_modules/@types/bootbox/index.d.ts (96,41): Generic type 'JQuery<TElement, HTMLElement>' requires 2 type argument(s).

**Comment by Dmitry44** [comment]
@mantuonweb Did you find solution? I have the same error

**Comment by bcherny** [comment]
This probably belongs in https://github.com/DefinitelyTyped/DefinitelyTyped/issues.

**Comment by RyanCavanaugh** [comment]
⬆️
