### ISSUE TITLE
Find references does not work for re-exported default

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/TypeScript#17007]
**TypeScript Version:**  2.4.1

**Code**

```ts
// export.ts
const foo = 1;
export default foo;
```

``` ts
// re-export.ts
export { default } from './export';
```

``` ts
// re-export-dep.ts
import fooDefault from './re-export';
```

``` json
// tsconfig.json
{
    "files": [
        "./re-export-dep.ts"
    ]
}
```

**Expected behavior:**
When running "find references" on `foo` in `export.ts`, the usage in `re-export-dep.ts` should be found.

**Actual behavior:**
The reference is not found.

![image](https://user-images.githubusercontent.com/921609/27959567-e572046a-631f-11e7-8720-e01b35c04dc3.png)

If changed to a named export, the references can be found.
![image](https://user-images.githubusercontent.com/921609/27959575-ed706ea4-631f-11e7-9153-abad0d31b0c5.png)

**Comment by andy-ms** [comment]
Looks like this was fixed as part of #17992. @OliverJAsh can you verify that it works in your situation?

**Comment by OliverJAsh** [comment]
@andy-ms Is it on insiders or next?

**Comment by andy-ms** [comment]
I don't think this made it into `typescript@2.5`, so you'll have to install `typescript@next` and [set up](https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions) vscode to point to it.

**Comment by OliverJAsh** [comment]
Confirmed it fixes this and https://github.com/Microsoft/TypeScript/issues/13662. This will make a big difference. Thank you!
