### ISSUE TITLE
Partials accept functions

### ISSUE THREAD

**Issue by luke-john** [Microsoft/TypeScript#17003]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

2.4.1 and 2.5.0-dev.20170629 and 2.5.0-dev.20170707

**Code**

```ts
interface Foo {
    cat: string
    bar: number
}

type Bar = Partial<Foo>

const notBar: Bar = () => { } // passes on 2.4.1 and 2.5.0-dev.20170629 and 2.5.0-dev.20170707
```

**Expected behavior:**

Partials should not accept functions

**Actual behavior:**

Partials accept functions

[typescript-playground-example](https://www.typescriptlang.org/play/#src=interface%20Foo%20%7B%0D%0A%20%20%20%20cat%3A%20string%0D%0A%20%20%20%20bar%3A%20number%0D%0A%7D%0D%0A%0D%0Atype%20Bar%3CBaz%3E%20%3D%20Partial%3CBaz%3E%0D%0A%0D%0Aconst%20notBar%3A%20Bar%3CFoo%3E%20%3D%20()%20%3D%3E%20%7B%20%7D%20%2F%2F%20passes%20on%202.4.1%20and%202.5.0-dev.20170629%20%0D%0A%0D%0Aconst%20alsoNotBar%3A%20Bar%3CFoo%3E%20%3D%20'test'%20%2F%2F%20fails%20on%202.4.1%0D%0A%0D%0Aconst%20alsoAlsoNotBar%3A%20Bar%3CFoo%3E%20%3D%20false%20%2F%2F%20fails%20on%202.4.1)

**Related Issues:**

[13132](https://github.com/Microsoft/TypeScript/issues/13132) has been marked as a duplicate of [7485](https://github.com/Microsoft/TypeScript/issues/7485) which has been closed

7485 is meant was meant to be closed by [16047](https://github.com/Microsoft/TypeScript/pull/16047) which has merged.

Edit: updated after testing on latest nightly and simplified example code

**Comment by kitsonk** [comment]
Addressed in [TypeScript FAQs](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-functions-with-fewer-parameters-assignable-to-functions-that-take-more-parameters).

**Comment by luke-john** [comment]
Apologies but it's not clear to me why a function is assingable to a partial interface based on that.

My isue is not to do with the parameters on the function, but that a function is assingable to a partial interface

**Comment by kitsonk** [comment]
Ah, I see the challenge...

From a type perspective, functions are a type of object, which can have properties.  You are assigning a function to an object with no required properties.  Therefore, a function with no properties is assignable to an interface with all optional properties.

Why all the cases you have in your playground example was because TypeScript did not detect weak types properly, and as of 2.4 it does.  That means that strings and numbers are no longer assignable but these weak types.

I tried to use `object & Partial<T>` as a type to avoid functions being assignable, but I am afraid functions are still considered subtypes of objects by the type system.  But I might be missing something...

**Comment by luke-john** [comment]
So after sleeping on it, I think I can restructure my use of Partial to achieve what I want with the following.

```
type ValueOne = { valueOne: 'value-one' }
type ValueTwo = { valueTwo: 'value-two' }

type SingleValue =
    | ValueOne
    | ValueTwo

type MultiValue =
    & Partial<
        & ValueOne
        & ValueTwo
    >
    & SingleValue

type Value = SingleValue | MultiValue

type Method = () => Value

type Argument = Method | Value

type Library = (argument: Argument) => void

const library: Library = (props) => {}

library({
})

library(() => ({
}))
```

[typescript-playground-example](https://www.typescriptlang.org/play/#src=type%20ValueOne%20%3D%20%7B%0D%0A%20%20%20%20valueOne%3A%20'value-one'%0D%0A%7D%0D%0A%0D%0Atype%20ValueTwo%20%3D%20%7B%0D%0A%20%20%20%20valueTwo%3A%20'value-two'%0D%0A%7D%0D%0A%0D%0Atype%20SingleValue%20%3D%20%0D%0A%20%20%20%20%7C%20ValueOne%0D%0A%20%20%20%20%7C%20ValueTwo%0D%0A%0D%0Atype%20MultiValue%20%3D%0D%0A%20%20%20%20%26%20Partial%3C%0D%0A%20%20%20%20%20%20%20%20%26%20ValueOne%0D%0A%20%20%20%20%20%20%20%20%26%20ValueTwo%0D%0A%20%20%20%20%3E%0D%0A%20%20%20%20%26%20SingleValue%0D%0A%0D%0Atype%20Value%20%3D%20SingleValue%20%7C%20MultiValue%0D%0A%0D%0Atype%20Method%20%3D%20()%20%3D%3E%20Value%0D%0A%0D%0Atype%20Argument%20%3D%20Method%20%7C%20Value%0D%0A%0D%0Atype%20Library%20%3D%20(argument%3A%20Argument)%20%3D%3E%20void%0D%0A%0D%0Aconst%20library%3A%20Library%20%3D%20(props)%20%3D%3E%20%7B%7D%0D%0A%0D%0Alibrary(%7B%0D%0A%7D)%0D%0A%0D%0Alibrary(()%20%3D%3E%20(%7B%0D%0A%7D)))

**Comment by luke-john** [comment]
Adding an index signature to the interface you pass to the `Partial` prevents it accepting functions.

[typescript playground example](https://www.typescriptlang.org/play/#src=interface%20Foo%20%7B%0D%0A%20%20%20%20cat%3A%20string%0D%0A%20%20%20%20bar%3A%20number%0D%0A%0D%0A%20%20%20%20%5Bkey%3A%20string%5D%3A%20string%20%7C%20number%20%7C%20undefined%0D%0A%7D%0D%0A%0D%0Atype%20Bar%3CBaz%3E%20%3D%0D%0A%20%20%20%20%7C%20Partial%3CBaz%3E%0D%0A%20%20%20%20%7C%20(%0D%0A%20%20%20%20%20%20%20%20()%20%3D%3E%20Partial%3CBaz%3E%0D%0A%20%20%20%20)%0D%0A%0D%0Aconst%20notBar%3A%20Bar%3CFoo%3E%20%3D%20()%20%3D%3E%20%7B%20%7D%20%2F%2F%20fails%20on%202.4.1%20and%202.5.0-dev.20170629%20%0D%0A%0D%0Aconst%20alsoNotBar%3A%20Bar%3CFoo%3E%20%3D%20'test'%20%2F%2F%20fails%20on%202.4.1%0D%0A%0D%0Aconst%20alsoAlsoNotBar%3A%20Bar%3CFoo%3E%20%3D%20false%20%2F%2F%20fails%20on%202.4.1)

```ts
interface Foo {
    cat: string
    bar: number

    [key: string]: string | number | undefined
}

type Bar<Baz> =
    | Partial<Baz>
    | (
        () => Partial<Baz>
    )

const notBar: Bar<Foo> = () => { } // fails on 2.4.1 and 2.5.0-dev.20170629 

const alsoNotBar: Bar<Foo> = 'test' // fails on 2.4.1

const alsoAlsoNotBar: Bar<Foo> = false // fails on 2.4.1
```

**Comment by luke-john** [comment]
just updating for anyone who comes across this via google.

on 2.4.1 the following works and retains autocomplete.

```
interface StylesComplete {
  propA: 'letter a' | 'a',
  propB: 'letter b' | 'b',
}

// A Partial on an interface will normally accept arbitrary functions
// due to partials accepting empty objects which validate to anything in
// typescript
const doesNotFail: Partial<StylesComplete> = () => { }


interface StylesLossy {
  [key: string]: string | undefined
}

type Styles =
  & StylesComplete
  & StylesLossy

// intersection of
// * an interface containing random props
// * index signature interface
// allows  you to do a partial which will successfully fail on arbitrary
// functions.

// successfully fails
const doesFail: Partial<Styles> = () => { }
```

[typescript-playground-example](http://www.typescriptlang.org/play/#src=interface%20StylesComplete%20%7B%0D%0A%20%20propA%3A%20'letter%20a'%20%7C%20'a'%2C%0D%0A%20%20propB%3A%20'letter%20b'%20%7C%20'b'%2C%0D%0A%7D%0D%0A%0D%0A%2F%2F%20A%20Partial%20on%20an%20interface%20will%20normally%20accept%20arbitrary%20functions%0D%0A%2F%2F%20due%20to%20partials%20accepting%20empty%20objects%20which%20validate%20to%20anything%20in%0D%0A%2F%2F%20typescript%0D%0Aconst%20doesNotFail%3A%20Partial%3CStylesComplete%3E%20%3D%20()%20%3D%3E%20%7B%20%7D%0D%0A%0D%0A%0D%0A%0D%0Ainterface%20StylesLossy%20%7B%0D%0A%20%20%5Bkey%3A%20string%5D%3A%20string%20%7C%20undefined%0D%0A%7D%0D%0A%0D%0Atype%20Styles%20%3D%0D%0A%20%20%26%20StylesComplete%0D%0A%20%20%26%20StylesLossy%0D%0A%0D%0A%2F%2F%20intersection%20of%0D%0A%2F%2F%20*%20an%20interface%20containing%20random%20props%0D%0A%2F%2F%20*%20index%20signature%20interface%0D%0A%2F%2F%20allows%20%20you%20to%20do%20a%20partial%20which%20will%20succesfully%20fail%20on%20arbitrary%0D%0A%2F%2F%20functions.%0D%0A%0D%0A%2F%2F%20succesfully%20fails%0D%0Aconst%20doesFail%3A%20Partial%3CStyles%3E%20%3D%20()%20%3D%3E%20%7B%20%7D%0D%0A)
