### ISSUE TITLE
Incorrect behavior of type guard after assignment

### ISSUE THREAD

**Issue by AndrewMayorov** [Microsoft/TypeScript#17008]
**TypeScript Version:**  2.4.1 

**Code**

```ts
toFilterOptions<TDefinition>(
    src: { id; def: TDefinition }[],
    name?: ( id, def: TDefinition ) => string,
    sort?: string | ( ( id, def: TDefinition ) => any ) )
{
    sort = sort; // Remove this line to fix the problem

    const fnGetSortField = (typeof sort === "string" ) 
        ?  _.property( sort )   // Here sort is string
        :  ( ( x: { id, def: TDefinition } ) =>  sort( x.id, x.def ) ); // ERROR: here it is still: string | ( ( id, def: TDefinition ) => any ) 

    // return ...
}
```

**Expected behavior:**
I expect that on the negative branch of the ?: expression "sort" will have type _( id, def: TDefinition ) => any_  

**Actual behavior:**
It is still _string | ( ( id, def: TDefinition ) => any )_. If you'd remove the "sort = sort" assignment then things get fixed.

**Comment by AndrewMayorov** [comment]
It is still the same in TS 2.9.1

**Comment by mhegazy** [comment]
The compiler can not verify the type when the function is called. it does not know when or if the function will be called. See https://github.com/Microsoft/TypeScript/issues/16928 for more details.
declaring the variable as `const` gives the compiler assurance that the variable will not change until the function is called. There is an additional feature that the compiler treats a parameter that is never written to as `const`. you assigning to it invalidates that assumption and we are back to the base case.

**Comment by AndrewMayorov** [comment]
It makes sense. Thank you for explanation!
