### ISSUE TITLE
npm i typescript@next stopped on 20170629

### ISSUE THREAD

**Issue by pocesar** [Microsoft/TypeScript#17012]
**TypeScript Version:**  nightly

```
npm i typescript@next -g
C:\nodejs\tsc -> C:\nodejs\node_modules\typescript\bin\tsc
C:\nodejs\tsserver -> C:\nodejs\node_modules\typescript\bin\tsserver
C:\nodejs
`-- typescript@2.5.0-dev.20170629
```

**Expected behavior:**

Install the lastest dev nightly

**Actual behavior:**

Seems that the automated builds stopped almost 2 weeks ago

**Comment by DanielRosenwasser** [comment]
@yuit is looking into it, I'll publish the latest.

**Comment by DanielRosenwasser** [comment]
@andy-ms, your change in #16646 broke the `configureNightly` script. Can you please fix this?

**Comment by pocesar** [comment]
now stopped in 20170707 (not sure if the current state of TS is badly broken for it to not have a nightly)

**Comment by RyanCavanaugh** [comment]
Our CI server died. Nothing serious

**Comment by pocesar** [comment]
still happening, last nightly from 07/19

**Comment by pocesar** [comment]
latest released version is `typescript@2.5.0-dev.20170808`

**Comment by pocesar** [comment]
somebody uploaded it after I posted

**Comment by weswigham** [comment]
@pocesar We were having trouble with our new internal CI/CD infrastructure at the time; but we've been reliably publishing the nightly (without human intervention) for more than a week now, so I think this is fixed ;)

**Comment by pocesar** [comment]
![image](https://user-images.githubusercontent.com/461084/29811833-2c2745c6-8c7b-11e7-92db-386e20ba9d8d.png)

**Comment by weswigham** [comment]
We no longer publish nightlies on nights when no changes have been merged; so there won't often be a nightly publish over weekends, which is most of that gap. Though we should have done a publish 9 hours ago - I'll check and see what's up.

**Comment by pocesar** [comment]
it's usually around 4AM in my timezone when the new release is out
