### ISSUE TITLE
Cant Use TS in VS 2013 Existing Projects

### ISSUE THREAD

**Issue by rrrobson** [Microsoft/TypeScript#1701]
I have VS 2013 Community Edition Update 4 and have installed TS 1.14 from download today.

Went into VS and created a new TS project.  All worked fine, just like in the playground.

Then, I went into several of my existing projects in VS 2013 and tried to add new item, typescript file.  No such menu choice was presented.  In fact, when in the EXISTING projects, it is as though Typescript was never installed for my VS 2013; however, the fact that I can create a NEW typescript project and run all the demos OK negates that conclusion.

Why am I not able to "see"/use Typescript in my existing VS 2013 projects but AM able to do so in a new project in the same instance of VS 2013?

**Comment by RyanCavanaugh** [comment]
What kind of existing projects? Can you upload a sample project that reproduces the problem?

**Comment by rrrobson** [comment]
I discovered my problem.  It was one of comprehension and understanding.

I added a NEW PROJECT (using the typescript template) to my solution.  I had been trying to shoehorn typescript functionality into the existing project in my solution, which, up to that point was a single-project solution.  I did not understand that typescript functionality has to be in its own project, with the overall solution benefitting from the js files generated out of that project.

Am I correct that you always need a two(or more)-project solution if you want to use typescript with an existing project?

**Comment by danquirk** [comment]
It depends on your existing project. For example, if you create a normal ASP.NET MVC app and then Add New Item -> TypeScript File to it you'll get this dialog:

![image](https://cloud.githubusercontent.com/assets/7121557/5824467/a13a7d7c-a099-11e4-9ab5-85cc2a58884e.png)

You can see the changes to the project file that occur after this that enable TypeScript support if you wanted to try hacking them into some other project type (no guarantee it would work in some arbitrary project type). What is your existing project exactly?

**Comment by rrrobson** [comment]
Project started out in WebMatrix.  It is a WebPages  Website project.

**Comment by danquirk** [comment]
I took a brief look at WebMatrix and it doesn't appear to use .csproj files that would allow this scenario to work. I don't know the product well but it appears to have some ASP.NET project templates or no project file at all.
