### ISSUE TITLE
Invalid emit for property decorators on computed property names in classes

### ISSUE THREAD

**Issue by Chacha-26** [Microsoft/TypeScript#17028]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.20170707)

**N.B.:** The syntax for using `x[0]` as a decorator is `@(x[0])` with parentheses. `@x[0]` without parentheses is the decorator `x` applied to the property `0`.

**Code [(Playground link)][play1]:**

```ts
function x(o: object, k: PropertyKey) { }
class A {
    @x ["property"]: any;
    @x [Symbol.toStringTag]: any;
}
```

**Expected behavior:**

The standard emit for classes, followed by:

```js
__decorate([
    x
], A.prototype, "property", void 0);
__decorate([
    x
], A.prototype, Symbol.toStringTag, void 0);
```

**Actual behavior:**

The standard emit for classes, followed by:

```js
__decorate([
    x
], A.prototype, _a, void 0);
__decorate([
    x
], A.prototype, _b, void 0);
```
This causes a reference error since `_a` and `_b` are never declared.
Note that this doesn't affect string property names without the square brackets (e.g. `@x "property": any;`), but this is still an issue when Symbols as property names.

------

In addition, the temporary variables produced for methods, properties, and properties with values are all conflicting [(Playground link)][play2]:
```ts
function x(o: object, k: PropertyKey) { }
class A {
    @x [Symbol.unscopables] = {};
    @x [Symbol.match]() { }
    @x [Symbol.toStringTag]: string;
}
```
produces
```js
function x(o, k) { }
class A {
    constructor() {
        this[_a = Symbol.unscopables] = {};
        var _a;
    }
    [_a = Symbol.match]() { }
}
__decorate([
    x
], A.prototype, _a, void 0);
__decorate([
    x
], A.prototype, _a, null);
__decorate([
    x
], A.prototype, _a, void 0);
var _a;
```
In this case there are three distinct `_a` variables used in the same scope:  
1. For `Symbol.unscopables`: Declared on line 5, but used out of scope.
2. For `Symbol.match`: Declared on line 18 and used in scope. This works as expected.
3. For `Symbol.toStringTag`: Never declared.

[play1]: https://www.typescriptlang.org/play/#src=function%20x(o%3A%20object%2C%20k%3A%20PropertyKey)%20%7B%20%7D%0D%0Aclass%20A%20%7B%0D%0A%20%20%20%20%40x%20%5B%22property%22%5D%3A%20any%3B%0D%0A%20%20%20%20%40x%20%5BSymbol.toStringTag%5D%3A%20any%3B%0D%0A%7D%0D%0A
[play2]: https://www.typescriptlang.org/play/#src=function%20x(o%3A%20object%2C%20k%3A%20PropertyKey)%20%7B%20%7D%0D%0Aclass%20A%20%7B%0D%0A%20%20%20%20%40x%20%5BSymbol.unscopables%5D%20%3D%20%7B%7D%3B%0D%0A%20%20%20%20%40x%20%5BSymbol.match%5D()%20%7B%20%7D%0D%0A%20%20%20%20%40x%20%5BSymbol.toStringTag%5D%3A%20string%3B%0D%0A%7D

**Comment by weswigham** [comment]
We also do not hoist computed property name expressions correctly when an initializer _is_ present. The name should be hoisted out of the class, but instead gets executed on every class construction.
