### ISSUE TITLE
`catch` of  a Promise can violate type safety.

### ISSUE THREAD

**Issue by pope** [Microsoft/TypeScript#17022]
**TypeScript Version:**  2.3.4 from vscode

**Code**

```ts
function foo(): Promise<string> {
  return new Promise((resolve, reject) => {
    setTimeout(() => reject(new Error('oops')), 100);
  });
}

function bar(): Promise<string> {
  return foo().then(
    (res) => res.substr(1),
    (err) => {
      console.log(err);
      return 1;
    });
}
```

**Expected behavior:**

I would expect typescript to fail because the resolved type from the `then` inside of `bar` is `Promise<string | number>`, but the return type is `Promise<string>`.

**Actual behavior:**

It compiles fine even though the resolution of `bar()` is a `number` and not a `string`.

**Comment by rbuckton** [comment]
It seems this was addressed in TypeScript 2.4 due to improvements in checks for inference and callbacks.
