### ISSUE TITLE
Show doc for type on the field

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/TypeScript#17029]
Snippet:
```
/**
 * This is very useful interface
 */
interface MyInterface {
  /**
   * This is very useful property
   */
  prop: string
}

type Obj = {
  my: MyInterface
}

const obj: Obj = {
  my: {
    
  }
}
```

I can see docs for `prop`

![image](https://user-images.githubusercontent.com/736697/27982947-873179d4-63ca-11e7-9837-4d58cf48531d.png)

But property `my` on `Obj` has no docs. As a suggestion as property's type has docs for it maybe it is worth to show this doc if there are no docs for the property itself? 

![image](https://user-images.githubusercontent.com/736697/27982956-dab8aadc-63ca-11e7-8b60-20f8f017295e.png)

**Comment by mhegazy** [comment]
The comments are for the interface, and not the obj. i do not think you want to see the documentation for `Array` interface, on every property that happens to be an array of something. if you want the documentation to be on `my`, add a comment on `my`.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
