### ISSUE TITLE
Implement package validator as a compiler flag

### ISSUE THREAD

**Issue by weswigham** [microsoft/TypeScript#17024]
Similar to how `--init` generates a tsconfig, we should add a `--validateLib`, which looks at the package.json in the current directory, checks it for a valid entrypoint for library usage (so a `"types"` field referencing a file or an `index.d.ts` file), then loads up the `.d.ts` files found into a compilation, checks them, and issues errors if any `.d.ts` files within the project are not module files/have triple slash references.

cc @DanielRosenwasser

**Comment by mhegazy** [comment]
I would say this should be a standalone tool. either way, we should implement the logic as proposed.

**Comment by RyanCavanaugh** [comment]
ATTW FTW
