### ISSUE TITLE
Proposal: Type check default function parameters at the calling end

### ISSUE THREAD

**Issue by buu700** [Microsoft/TypeScript#17038]
Edit: I may have confused things a bit by initially considering this related to default generic type parameters, when the idea really isn't related to that at all. What I'm suggesting is that default parameters of any type that don't contradict the parameter's type be allowed.

For example, one could define `function f<T> (t: T = 5)`, and it would be up to calling code to ensure that either `T` is defined/inferred as `number` or that a non-default `t` is passed in with the correct type. However, defining `function f (s: string = 5)` or `function f<T extends boolean|string> (t: T = 5)` would still be an error since `number` isn't a possible sub-type of `string` or `boolean|string`.

---

Right now, you can have a function like this and use it as such:

```
function convertToString<T> (
    data: T,
    f: (t: T) => string
) {
    return f(data);
}

convertToString(5, n => n.toString());
convertToString(true, b => b ? 'foo' : 'bar');
convertToString('', s => s + 'balls');
```

And (although it doesn't add any value here) you can make that `<T>`, say, a `<T = number[]>`.

My proposal: allow default parameters to take advantage of default generic types in the following way:

```
function convertToString<T = number[]> (
    data: T,
    f: (t: T) => string = (arr: number[]) => arr.join('')
) {
    return f(data);
}
```

Here, when calling `convertToString` with a `data` argument of type `number[]`, the second argument could be omitted. However, trying to do so with any other type would cause a compile error.

(Alternatively, this may work just as well without depending on the presence of a default generic type.)

**Comment by rozzzly** [comment]
Aforementioned error is:
```
Type '(arr: number[]) => string' is not assignable to type '(t: T) => string'.
  Types of parameters 'arr' and 't' are incompatible.
    Type 'T' is not assignable to type 'number[]'.
```
though I'd save everyone a sec

**Comment by HerringtonDarkholme** [comment]
Default generic type has nothing to do with default parameter. The former is for type and the latter is for value. 

Default generic type only enable one to skip type argument, it cannot associate default function argument to one specific type. Otherwise it causes runtime error or breaks current checking.

> Here, when calling convertToString with a data argument of type number[], the second argument could be omitted.

There is no guarantee that when calling convertToString with `string`, users will provide the second argument.  Consider this call `convertToString('string')`. Should TS report error? If so, which error should TS report?

The best solution is to define convertToString as overriding.

**Comment by buu700** [comment]
Cool. Yeah, after writing the idea out the two didn't seem liked they'd necessarily be related, but I didn't know enough about TS internals to be sure.

> There is no guarantee that when calling convertToString with `string`, users will provide the second argument. Consider this call `convertToString('string')`. Should TS report error? If so, which error should TS report?

Yep, my idea was that it would behave exactly as though the user had explicitly typed `convertToString('string', (arr: number[]) => arr.join(''))`.

**Comment by HerringtonDarkholme** [comment]
But this is not how default generic type works. TypeScript will infer generic type argument if you write no `<>` type argument part. So in your case the type argument `converToString` will be inferred as both string and number[], which is a conflict and thus a compiling error.

When will default generic type work? Only when you have multiple type arguments and users do provide incomplete type argument. Because you specify type argument, TS will not infer.

For example for the definition `map<U, V=object>(u: U, v: V)`, users call it like `map<string>('str', new Cat)`.  The type parameter `V` will be resolved to `object`, not `Cat`. 

Please refer to https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-3.html

**Comment by buu700** [comment]
> So in your case the type argument `convertToString` will be inferred as both string and number[], which is a conflict and thus a compiling error.

Yes, that's what my suggestion is. Right now, a function with that signature can't even be defined (see error pasted above by @rozzzly). I'm suggesting that TypeScript allow the function to be defined with default parameters of any type, and enforce it at the calling end instead.

To give another contrived example:

```
function doStuff<T> (foo: T = 0, bar: T = 'hello') { ... }

doStuff(); // Compile error
doStuff(5); // Compile error
doStuff(undefined, 'test'); // Compile error

doStuff('string'); // Valid
doStuff(undefined, 1337); // Valid
doStuff(true, false); // Valid
```

**Comment by buu700** [comment]
I think I made this more confusing than it needed to be by mentioning default generic types at all. See the new issue title and edit at the top for clarification, @HerringtonDarkholme.

**Comment by mhegazy** [comment]
An optional parameter with an initializer is just sugar for an initialization check then an assignment.. This makes the problem much simpler to understand.. for instance,
`function f(a = 0)` is `f(a) { if (a === void 0) { a = 0; } ..` this is how it will execute, and this is how the compiler checks it..

Now, if you give a parameter a type (generic or not), the compiler has to verify that any assignments you make are valid. in the case of a generic type, the compiler does not know what it gonna be, it can be anything.. and thus it can not let you assign anything to it, as that would allow for unsafe assignments that left flagged would lead to run time failures.

The other thing to note is that the type of a function can not depend on its caller. so when the compiler sees something like `f(x: T, y?: T): T` it knows this function takes two parameter of the same type and that is what it returns.. it is a contract, now if the function body was allowed to assign some default value, to one of the parameters that would break the contract.. e.g.:

```ts
function f<T>(x: T, y?: T): T {
    if (y === void 0) y = 0;  // number is not safe here

    // since you might use y later on, and y has the type T, which may or may not be number
    return y;  
}

// for instance, you can call it with
f("string").length;
```

**Comment by buu700** [comment]
Got it, thanks for the detailed explanation. So it sounds like this feature would just take a lot of refactoring work to implement, as opposed to something that the team would necessarily oppose on a language design level?

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
