### ISSUE TITLE
Please support symlinks - (1) project X depends on Y at runtime, but not at compile time (2) project X depends on Y at compile time, but not at runtime

### ISSUE THREAD

**Issue by ORESoftware** [Microsoft/TypeScript#17037]
This issue regards having TS and tsc work with symlinks. I have a scenario where a project X depends on Y at runtime. But Y is not declared as a dependency in X's package.json, nor is it installed in the local node_modules directory.

I also have a use case where I want to import the types from project X into project Y for the purposes of static type checking, but I do not need project X at runtime. In both cases, I need tsc to support symlinks, so that tsc can see the types across symlinked projects. (I am mostly taking about symlinks generated by NPM link, but I suppose it could be any old symlinked project).

The quality of code and projects in the JS world largely depends on the quality of the code of the popular libraries in the JS world. A lot of libraries have interesting use cases that applications don't have, and even though the libraries comprise < 1% of the actual codebases out there, they are, let's say, 80% of the important code. 

My point is that I see it as very important that TS and tsc support symlinked dependencies for the purposes of static type-checking, and this will mostly be library code. Currently it is my belief that it is not the case that tsc supports symlinks, but I really hope that you guys work to make it so.

Please correct me where I am wrong.

**Comment by mhegazy** [comment]
And https://github.com/Microsoft/TypeScript/pull/16661 is not sufficient?

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
