### ISSUE TITLE
how to disable 'this' tranform to '_this'，I want to add linq extension metthod for Array

### ISSUE THREAD

**Issue by mokeyish** [Microsoft/TypeScript#17034]
I want to add linq extension metthod for Array, like c# static Extension method。

here is the code

declare interface Array<T> {
    where(predicate: (value?: T, index?: number, list?: T[]) => boolean): T[];
}
Array.prototype.where = (predicate?: (value?: T, index?: number, list?: T[]) => boolean) => {
 return this.filter(predicate);
};

but the tsc compiled 'this 'into '_this',and code work incorrect.

**Comment by ikatyang** [comment]
You should use `function () { /* ... */ }`(function) instead of `() => { /* ... */ }`(arrow-function), arrow-function is a function that does not have its own `this`.

**Comment by mokeyish** [comment]
@ikatyang Thank you for your answer.The problem's been solved.
