### ISSUE TITLE
Find references doesn't return all the results

### ISSUE THREAD

**Issue by JsonFreeman** [Microsoft/TypeScript#1703]
Try to find all references on getThisContainer, which is called in checker.ts.

Expected: The list includes the calls in checker.ts
Actual: It just includes the definition in utilities.ts, and the calls in services.ts, but not the calls in checker.ts

**Comment by JsonFreeman** [comment]
The same is true for occurrences

**Comment by DanielRosenwasser** [comment]
Unable to reproduce the issue.
