### ISSUE TITLE
Formatter dedents when completing regexp

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#17031]
**TypeScript Version:**  nightly (2.5.0-dev.20170707)

**Code**

```ts
function f() {
	return f();
}
```

Go inside the parentheses in `return f();` and type `/.*/`.

**Expected behavior:**

No formatting changes.

**Actual behavior:**

```ts
function f() {
return f(/.*/);
}
```

It will also dedent if you first type in `return f(/.*/` then add a closing parenthesis.

**Comment by mhegazy** [comment]
I can not reproduce this locally
