### ISSUE TITLE
Can not see docs for quoted object properties 

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/TypeScript#17040]
![image](https://user-images.githubusercontent.com/736697/27992388-1fdf7d42-64ad-11e7-9e93-0f716f3eb7d8.png)

```ts
export type IngressAnnotations = {  
  /**
   * doc here
   */
  'kubernetes.io/ingress.class': string,
  'kubernetes.io/tls-acme': 'true' | 'false',  
  /**
   * x docs here
   */
  x: string
}

const annotation: IngressAnnotations = {
  
}
```

does not show options and docs for quoted `kubernetes.io/ingress.class`

**Comment by mhegazy** [comment]
it should be visible in string literals: 
![image](https://user-images.githubusercontent.com/8000722/29797957-ed1dc7ea-8c0e-11e7-875c-e4c5a55accf0.png)

**Comment by mhegazy** [comment]
though we are not showing the doc comments here.

**Comment by whitecolor** [comment]
Well but I think those quoted props should be shown and treated as normal props (without quotes), users may not be aware that they need to puts quotes to get the pros.

**Comment by mhegazy** [comment]
> Well but I think those quoted props should be shown and treated as normal props (without quotes), users may not be aware that they need to puts quotes to get the pros.

we should do that. but then we need to have support for placing quotes around them when we apply the change.
