### ISSUE TITLE
Completions get lost for CSSProperties[K] in interface with <K extends keyof CSSProperties>

### ISSUE THREAD

**Issue by rozzzly** [Microsoft/TypeScript#17047]
Consider the following:
```typescript
interface CSSProperties {
    height?: any;
    color?: any;
    position?: (
        | 'static'
        | 'absolute'
        | 'fixed'
        | 'relative'
        | 'initial'
        | 'inherit'
    );
    // .... rest of css properties, some of them with defined acceptable values (like `position`)
}

export interface CSSDeclaration<K extends keyof CSSProperties> {
    propertyName: K;
    value: CSSProperties[K];
}

function proclaim<T extends keyof CSSProperties>(decl: CSSDeclaration<T>): CSSDeclaration<T> {
  return decl;
 }
```

```typescript
proclaim({
    propertyName: 'position', // you get completions here, OK
    value: '??' // no completions here, :sadface:
});
```

The type checker will error if you put a value other than one of those defined in `CSSProperties`, so obviously the type doesn't get lost along the way, but the completions do.

**version:** `2.5.0-dev.20170707` and whatever the playground is running

**Comment by mhegazy** [comment]
looks like the same issue as https://github.com/Microsoft/TypeScript/issues/11997

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
