### ISSUE TITLE
Unions accept extra keys with incorrect properties

### ISSUE THREAD

**Issue by luke-john** [Microsoft/TypeScript#17046]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

**Code**

```ts
interface SinglePropA { a: 'test-a' }
interface SinglePropB { b: 'test-b' }
type AorB =
    | SinglePropA
    | SinglePropB

const testAandB: AorB = {
    a: 'test-a',
    b: 'test-bs'
} // passes on 2.4.1 and 2.5.0-dev.20170629 

const testAandC: AorB = {
    a: 'test-a',
    c: 'test-b'
} // fails on 2.4.1 and 2.5.0-dev.20170629
/*
    Object literal may only specify known properties,
    and 'c' does not exist in type 'SubsetAnimal'.
*/
```

[typescript playground example](https://www.typescriptlang.org/play/#src=interface%20SinglePropA%20%7B%20a%3A%20'test-a'%20%7D%0D%0Ainterface%20SinglePropB%20%7B%20b%3A%20'test-b'%20%7D%0D%0A%0D%0Atype%20AorB%20%3D%0D%0A%20%20%20%20%7C%20SinglePropA%0D%0A%20%20%20%20%7C%20SinglePropB%0D%0A%0D%0Aconst%20testAandB%3A%20AorB%20%3D%20%7B%0D%0A%20%20%20%20a%3A%20'test-ab'%2C%0D%0A%20%20%20%20b%3A%20'test-b'%0D%0A%7D%20%2F%2F%20passes%20on%202.4.1%20and%202.5.0-dev.20170629%20%0D%0A%0D%0Aconst%20testAandBandC%3A%20AorB%20%3D%20%7B%0D%0A%20%20%20%20a%3A%20'test-a'%2C%0D%0A%20%20%20%20c%3A%20'test-b'%0D%0A%7D%20%2F%2F%20fails%20on%202.4.1%20and%202.5.0-dev.20170629%0D%0A%2F*%0D%0A%20%20%20%20Object%20literal%20may%20only%20specify%20known%20properties%2C%0D%0A%20%20%20%20and%20'c'%20does%20not%20exist%20in%20type%20'SubsetAnimal'.%0D%0A*%2F)

**Expected behavior:**

Unions don't accept extra properties where the key matches another member of the union.

**Actual behavior:**

Unions accept extra properties where the key matches another member of the union but the value is incorrect.

Note. Came across this when trying to find a workaround for the following issue https://github.com/Microsoft/TypeScript/issues/17003

**Comment by RyanCavanaugh** [comment]
See discussion in  #16679

**Comment by luke-john** [comment]
Thanks for that.
