### ISSUE TITLE
Unable to use any 1.4 language features after update

### ISSUE THREAD

**Issue by grantfeldman** [Microsoft/TypeScript#1704]
I have installed the 1.4 update [TypeScript_1.4_VS2013.exe] and am not able to use any of the example from the blog post.

Typing tsc from the command line indicated 1.03. After updating the path to remove the old version it is now reporting 1.4 but i still cant use any of the features.

**Comment by DanielRosenwasser** [comment]
@grantfeldman has this issue been resolved on your end?

**Comment by grantfeldman** [comment]
Hi Daniel, turns out the examples were compiling fine. Resharper was the culprit. i guess they need to update to 1.4 as well.
