### ISSUE TITLE
Is it possible to define generator function that has different yield and return type?

### ISSUE THREAD

**Issue by pietrasiak** [Microsoft/TypeScript#17045]
eg. Let's imagine generator function that yields only numbers, but returns only booleans

```
function* myGenerator() {
  yield 1;
  yield 2;
  yield 3;

  return true;
}
```

For now it's type is just `number | boolean` so it'd allow me to yield bool and return number without errors.

I wonder if is it possible to create type that distinguishes it.

**Comment by RyanCavanaugh** [comment]
This is a bug tracker, not a support forum. Please ask questions on e.g. StackOverflow.
