### ISSUE TITLE
Can't narrow down value type of enum type

### ISSUE THREAD

**Issue by donaldpipowitch** [Microsoft/TypeScript#17043]
**TypeScript Version:**  2.4.1

**Code**

```ts
enum SyntaxKind {
  Foo = 1,
  Bar = 2,
  // and more...
}

type Declaration = {
  kind: SyntaxKind;
  // and more...
}

function processFoo(decl: Declaration & { kind: SyntaxKind.Foo }) {
  // process foo...
}

function processAnyKind(decl: Declaration) {
  // process any kind...
}

function checkDeclaration(decl: Declaration) {
  if (decl.kind === SyntaxKind.Foo) {
    processFoo(decl); // ERROR: Types of property 'kind' are incompatible.
  } else {
    processAnyKind(decl);
  }
}
```

**Expected behavior:**

I can pass `decl` to `processFoo`.

**Actual behavior:**

`ERROR: Types of property 'kind' are incompatible. Type 'SyntaxKind' is not assignable to type 'SyntaxKind.Foo'.` when I pass `decl` to `processFoo`.

**Comment by ikatyang** [comment]
I think the issue here is that control flow analysis can only narrow types to their sub-types, e.g. 

```ts
if (decl.kind === SyntaxKind.Foo) {
  decl //=> Declaration
  decl.kind //=> SyntaxKind.Foo
}
```

If you change your definition to this:

```ts
type Declaration = FooDeclaration | BarDeclaration;

type FooDeclaration = {
    kind: SyntaxKind.Foo;
    // and more...
}
type BarDeclaration = {
    kind: SyntaxKind.Bar;
    // and more...
}
```

You'll get the expected behavior:

```ts
if (decl.kind === SyntaxKind.Foo) {
  decl //=> FooDeclaration
  decl.kind //=> SyntaxKind.Foo
}
```

```ts
enum SyntaxKind {
  Foo = 1,
  Bar = 2,
  // and more...
}

type Declaration = FooDeclaration | BarDeclaration;

type FooDeclaration = {
    kind: SyntaxKind.Foo;
    // and more...
}
type BarDeclaration = {
    kind: SyntaxKind.Bar;
    // and more...
}

function processFoo(decl: Declaration & { kind: SyntaxKind.Foo }) {
  // process foo...
}

function processAnyKind(decl: Declaration) {
  // process any kind...
}

function checkDeclaration(decl: Declaration) {
  if (decl.kind === SyntaxKind.Foo) {
    processFoo(decl); // no error
  } else {
    processAnyKind(decl);
  }
}
```

**Comment by donaldpipowitch** [comment]
Thank you. I wonder if this is "by design" or if it could be solved with a new feature inside the TypeScript compiler.

I actually use the `Declaration` type from TypeScript itself, so I can't manipulate it directly. I'd like to find a type-checked way to pass a `Declaration` with a specific `SyntaxKind` to a function. Currently I need an additional check like this:

```ts
function processFoo(decl: Declaration) {
  if (decl.kind !== SyntaxKind.Foo) {
    throw 'This is not SyntaxKind.Foo.' 
  }

  // process foo...
  // here is other code which won't compile, if `decl.kind` is
  // not `SyntaxKind.Fo`
}

function checkDeclaration(decl: Declaration) {
  if (decl.kind === SyntaxKind.Foo) {
    // I already checked `decl.kind` here. Would be nice, if I could get rid of the additional 
    // check inside `processFoo`.
    processFoo(decl);
  } else {
    processAnyKind(decl);
  }
}
```

**Comment by mhegazy** [comment]
This boils down to the behavior of intersection. intersection does not eliminate supertypes, i.e. `number & 1` is `number` and not `1`. the way this is possible now is using interfaces and `extends` to override the definition of a property, which is what most AST nodes are in the typescript compiler .d.ts

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
