### ISSUE TITLE
Doesn't handle unicode identifiers correctly

### ISSUE THREAD

**Issue by ghost** [microsoft/TypeScript#17048]
**TypeScript Version:**  2.4.0

**Code**
      `let a = 𪘀`

Tested in the playground. Displays nothing. And further investigation shows that this unicode are seen with a length of 2, where the actually length are 1.  You see it [here](http://www.fileformat.info/info/unicode/char/2a600/index.htm)

There are also other unicode characters in the range of >0xFFFF that is not handled correctly. And also identifiers with a  unicode sequences wrapped inside `{` and `}` are not part of the TS code, but allowed from ECMAScript 2015.

**Expected behavior:**
Should handle unicode characters correctly

**Actual behavior:**
Doesn't handle unicode characters correctly

**Comment by kitsonk** [comment]
As implied, it is [not valid for ES5](https://mothereff.in/js-variables#%F0%AA%98%80).  What was the target for your compile?  The target in playground is ES5.  Though, at the very least it should error, if not down emit IMO.

**Comment by crazyhuggins** [comment]
@kitsonk i tried the playground first and then looked at the source code. I expected es2015 stuff to fail as the target is es5. But also the source code when parsing an identifer does not support this. Same for surrogate pairs wich should work fo es5 as well.

**Comment by RyanCavanaugh** [comment]
Works fine now? Not sure what the bug is supposed to be here.
