### ISSUE TITLE
String Enum v2.4.1

### ISSUE THREAD

**Issue by acopalipsis** [Microsoft/TypeScript#17057]
```
enum Enumeration {
    A = "value",
    B // Enum member must have initializer.
}
```
It should be or it's a bug?

**Comment by ikatyang** [comment]
This is `Working as Intended`, see https://github.com/Microsoft/TypeScript/pull/15486 for more detail.

> Enum members with string literal values must always specify an initializer, but enum members with numeric literal values may omit the initializer provided it is the first member or the preceding member has a numeric value.
