### ISSUE TITLE
tsserver crashes randomly in VS Code

### ISSUE THREAD

**Issue by jeffijoe** [Microsoft/TypeScript#17054]
**TypeScript Version:**  2.4.1

I don't know exactly _what_ causes tsserver to (seemingly) crash in VS Code, but I opened DevTools while working and waited for everything TS to stop working. This is what was logged:

![image](https://user-images.githubusercontent.com/2505474/28020446-c36e4f4c-6584-11e7-8995-abfffa10e245.png)

**Comment by mhegazy** [comment]
Please give TS 2.5 a try (VSCode insiders), and let us know if you are still experiencing the issue. if so, please share the tsserver log. you can use Open TSServer log command.

**Comment by jeffijoe** [comment]
I'm not too keen on installing insider builds, I'll come back to this when 2.5 drops in mainline. Should I close now and reopen later?

**Comment by mhegazy** [comment]
up to you, we automatically close stale issues every 2 weeks anyways.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
