### ISSUE TITLE
Unions not supported in map indexes (version 1.4.1.0)

### ISSUE THREAD

**Issue by jice-nospam** [Microsoft/TypeScript#1705]
This syntax :
var map: { [index: string|number ]: number };

results in compiler error :
An index signature parameter type must be 'string' or 'number'.

**Comment by ahejlsberg** [comment]
This is by design. It is already the case that a string index signature defines a constraint for all properties in a type and allows index expressions of type string, number, or any, so you can get the effect above simply by defining:
```typescript
var map: { [index: string]: number };
```
