### ISSUE TITLE
Proposal - merge enums with spread operator

### ISSUE THREAD

**Issue by pie6k** [Microsoft/TypeScript#17059]
Consider enums with such syntax:

```
enum GoodMusic {
  RockAndRoll,
  Country,
}

enum BadMusic {
  Rap,
  DnB,
}

enum AllTheMusic {
  ...GoodMusic,
  ...BadMusic,
}
```

As enums are known at compile time compiler could detect conflicts

**Comment by weswigham** [comment]
You can just write `type AllTheMusic = GoodMusic | BadMusic`.

**Comment by andy-ms** [comment]
@weswigham But then there would be conflicts, because they both use `0` to represent `RockAndRoll` / `Rap`.

**Comment by weswigham** [comment]
I suppose you could write a lint rule for tslint which checks if a union contains enums whose values overlap.

**Comment by andy-ms** [comment]
You could also approach the problem "backwards":
```ts
enum AllTheMusic {
    // good
    RockAndRoll,
    Country,

    // bad
    Rap,
    DnB,
}

type GoodMusic = AllMusic.RockAndRoll | AllMusic.Country;
type BadMusic = AllMusic.Rap | AllMusic.DnB;
```

This has the advantage of ensuring that every `GoodMusic` value is a valid `AllTheMusic` value, whereas if you concatted two enums that were both using `0` in different ways, you would need different conversion functions to convert `GoodMusic -> AllTheMusic` or `BadMusic -> AllTheMusic`.

**Comment by pietrasiak** [comment]
@andy-ms yup, but then - AllTheMusic needs to be aware of 'implementation' of 'sub-modules' and that lowers 'encapsulation'.

**Comment by weswigham** [comment]
It would need to be "aware" of their implementation in order to issue an
error about conflicting members, anyway.

**Comment by mhegazy** [comment]
Not sure i see how feasible this is, and more importantly, the use case this solves.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
