### ISSUE TITLE
Importing namespaced properties in a typings file following the format of module-function.d.ts throws 'cannot find namespace' error.

### ISSUE THREAD

**Issue by shirakaba** [Microsoft/TypeScript#17050]
**TypeScript Version:**  2.4.0

**Summary**
I have an untyped JS module, [promise-retry](https://github.com/IndigoUnited/node-promise-retry) that I am trying to import and provide typings for. However, despite following the [module-function.d.ts](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-function-d-ts.html) guide from the TypeScript handbook closely, it throws compile-time errors.

**Code**

#### `node_modules/promise-retry/index.js`:
```js
// Here is the library structure; I think it's of CommonJS type?
var retry = require('retry');
function promiseRetry(fn, options) { /*...*/ }
module.exports = promiseRetry;
```

#### `promise-retry/index.d.ts`:
```ts
// In the style of module-function.d.ts
export = promiseRetry;

declare function promiseRetry(options: Partial<PromiseRetry.NodeRetryOptions>, fn: (retry: PromiseRetry.RetryFn, attempt: number) => Promise<any>): Promise<any>;
declare function promiseRetry(fn: (retry: PromiseRetry.RetryFn, attempt: number) => Promise<any>, options ?: Partial<PromiseRetry.NodeRetryOptions>): Promise<any>;

declare namespace PromiseRetry {
    export interface NodeRetryOptions {
        forever: boolean;
        unref: boolean;
        retries: number;
        factor: number;
        minTimeout: number;
        maxTimeout: number;
        randomize: number | false;
    }

    export type RetryFn = (err: any) => never;
}
```

#### `Usage.ts`:
```ts
import promiseRetry = require("promise-retry");
import PromiseRetry = require("promise-retry");

promiseRetry((retry, attempt) => Promise.resolve(), {forever: true}); // no error
// Both of these throw the following error: "Cannot find namespace 'PromiseRetry'"
let options: PromiseRetry.NodeRetryOptions = { forever: false };
let retryFn: PromiseRetry.RetryFn = (err:any)=>{ throw "despair"; };
```

#### `tsconfig.json`:
```js
{
    "compilerOptions": {
        "watch": true,
        "sourceMap": true,
        "target": "es5",
        "baseUrl": ".",
        "outDir": "dist/types",
        "declaration": true,
        "allowJs": false,
        "noImplicitAny": true,
        "noImplicitThis": true,
        "strictNullChecks": true,
        "module": "commonjs",
        "noLib": false
    }
}
```

**Expected behavior:**
Allows me to use namespaced typings for the parameters and compiles.

**Actual behavior:**
`Usage.ts` throws the error `Cannot find namespace 'PromiseRetry'`, and `promise-retry/index.d.ts` throws the error `Module build failed: Error: Typescript emitted no output for /Users/shirakaba/Documents/git/promise-retry/index.d.ts.`

**Comment by ikatyang** [comment]
(./tsconfig.json)

```json5
{
    "compilerOptions": {
        "target": "es6",
        "strict": true,
        "module": "commonjs",
        "typeRoots": [ // <--- provide path to your definition files
            "node_modules/@types", 
            "types"
        ]
    }
}
```

(./types/promise-retry.d.ts)

```ts
declare module "promise-retry" { // <--- if this is not in `node_modules/@types`, you should provide its module name

    export = promiseRetry;

    function promiseRetry(options: Partial<promiseRetry.NodeRetryOptions>, fn: (retry: promiseRetry.RetryFn, attempt: number) => Promise<any>): Promise<any>;
    function promiseRetry(fn: (retry: promiseRetry.RetryFn, attempt: number) => Promise<any>, options ?: Partial<promiseRetry.NodeRetryOptions>): Promise<any>;

    namespace promiseRetry { // <--- if you want to merge namespace, you should use the same name
        
        export interface NodeRetryOptions {
            forever: boolean;
            unref: boolean;
            retries: number;
            factor: number;
            minTimeout: number;
            maxTimeout: number;
            randomize: number | false;
        }

        export type RetryFn = (err: any) => never;
    }

}
```

(./Usage.ts)

```ts
import promiseRetry = require("promise-retry");

promiseRetry((retry, attempt) => Promise.resolve(), {forever: true});

let options: promiseRetry.NodeRetryOptions = { forever: false };
//  ^^^^^^^ [ts]
//          Type '{ forever: false; }' is not assignable to type 'NodeRetryOptions'.
//            Property 'unref' is missing in type '{ forever: false; }'.

let retryFn: promiseRetry.RetryFn = (err: any) => { throw "despair"; };
```

**Comment by shirakaba** [comment]
Thank you so much!! This has really saved me. The error your code receives on the line `let options: promiseRetry.NodeRetryOptions = { forever: false};` is my fault (the type should actually have been `Partial<promiseRetry.NodeRetryOptions>`).

A summary of your steps:

0) Prerequisite: Ensure the target library is installed as a dependency, eg. `npm install --save "promise-retry"`.

1) Wrap the whole typings file in: `declare module "promise-retry" {}`.

2) Put `promise-retry/index.d.ts` into an enclosing 'types' folder wherever you'd like and add that 'types' folder  to `tsconfig.json`'s `typeRoots`.

3) Import the JS library (along with the typings from the previous step) via `import promiseRetry = require("promise-retry");`.

4) Access its function as `promiseRetry()` and its namespaced typings as `: promiseRetry.RetryFn`.

---

I do have one question, though: You mention *"<--- if you want to merge namespace, you should use the same name"*. If wanted a distinct namespace for those types, like `PromiseRetry` (which starts with a capital letter), how would I import and use that? I've tried:

```ts
import PromiseRetry = require("promise-retry");
let options: Partial<promiseRetry.NodeRetryOptions> = { forever: false};
```

... but I'm unsure whether it worked because it seems that my IDE takes a very, very long time to update its indexes and thus can incorrectly show an error for a very long time when a package is changed.

**Comment by ikatyang** [comment]
If the module uses `module.exports = xxx`, the only way to export types is to use namespace merging, since there is only one entry point.

And if you just want a different import-name for better meaning(?), it seems importing twice is what you want (or use other alias like `const a = b;` for value-level, `type a = b;` for type-level etc.).

```ts
import promiseRetry = require("promise-retry");
import PromiseRetry = require("promise-retry"); // PromiseRetry === promiseRetry

promiseRetry((retry, attempt) => Promise.resolve(), {forever: true});

let options: Partial<PromiseRetry.NodeRetryOptions> = {forever: false};
let retryFn: PromiseRetry.RetryFn = (err: any) => { throw "despair"; };
```

**Comment by shirakaba** [comment]
I see, that's very clear. Thank you again! If you have a StackOverflow account, I can accept your response as a solution to my related problem [https://stackoverflow.com/questions/44977454/error-ts2497-module-resolves-to-a-non-module-entity-and-cannot-be-importe](here). Copy-pasting my numbered summary of your steps (with a link to your full answer) would suffice. 🙂
