### ISSUE TITLE
What's on the roadmap for TypeScript 2.5?

### ISSUE THREAD

**Issue by fruchtose** [Microsoft/TypeScript#17062]
The wiki was last updated to report on the status of 2.4:

https://github.com/Microsoft/TypeScript/wiki/Roadmap

I don't see any updates reflecting what features are being added for 2.5. I see some bug issues in the [2.5 milestone](https://github.com/Microsoft/TypeScript/milestone/49), but it would be nice to know what changes are being planned. Could someone please update the roadmap?

**Comment by RyanCavanaugh** [comment]
We're working on feature prioritization and will be updating the roadmap as decisions are made. I don't have anything concrete we're committing to at this point.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
