### ISSUE TITLE
Bug - Dynamic import not correctly transpiled in all cases

### ISSUE THREAD

**Issue by jason-krypton** [Microsoft/TypeScript#17060]
We ran into an issue trying to use the new dynamic import support when trying to split our webpack bundles. I was able to create a simplified repro below. It looks like importing does not get transpiled correctly but it does when within a function. We have a simple work around for now which is hoist the code up into a function outside the class, but this is pretty annoying.

**TypeScript Version:**  2.4.1
**Code**

foo.ts
```
export default class Foo {
    render() {
        return 'foo';
    }
}
```

foo_async.ts
```
export class FooAsync {
  render() {
    const loadAsync = import( './foo');
    return loadAsync;
  }
}
```

foo_async_working.ts (Example where the transpiling has the correct behavior)
```
const loadAsync = import( './foo');
export class FooAsync {
  render() {
    return loadAsync;
  }
}
```

Command line option: `tsc -t es6 -m commonjs foo_async.ts`

**Expected behavior:**

Dynamic `import('./foo')` should be transpiled to `Promise.resolve().then(function () { return require('./foo'); });`

As noted above this is correctly translated when put at the top of the file or inside a function outside of the class that the class calls.

**Actual behavior:**

The import is not transpiled and leads to a syntax error because `import` is an unrecognized token.

**Comment by yuit** [comment]
The PR is up. Once it checked in, you can try the nightly version!

**Comment by jason-krypton** [comment]
Awesome. Thanks!

**Comment by Fahrradflucht** [comment]
I don't understand this change at all and it actually broke my setup after upgrading to TS 2.5. Probably I have gotten something completely wrong:

Wasn't the whole point to preserve the `import` statements and not transpile them? Reading the [webpack](https://webpack.js.org/api/module-methods/#import) [docs](https://webpack.js.org/guides/code-splitting/#dynamic-imports) I comprehend that it expects an import token to be on the code and then extracts a new bundle.

I had exactly this working.

Now after this change all `import` statement get transpiled to `require` statements and webpack generates one big bundle.

I would really appreciate someone telling what I have gotten wrong.

**Comment by mhegazy** [comment]
> Wasn't the whole point to preserve the import statements and not transpile them? 

use `--module esNext` to avoid transpiling the `import` statements.

**Comment by Fahrradflucht** [comment]
Thanks. For some reason this breaks my ability to use `import` statements and `export default` in my `webpack.config.ts` but I fixes the issue 😃

**Comment by kohlikohl** [comment]
This is still an issue when the dynamic import is used when exporting a default object:
```js
export default {
    getInstance: function () {
        return import('./foo2');
    }
}
```
transpiles to 
```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = {
    getInstance: function () {
        return import('./foo2');
    }
};
```
whereas naming the export it works:
```js
export let defaultExport = {
    getInstance: function () {
        return import('./foo2');
    }
}

// transpiles to

"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.defaultExport = {
    getInstance: function () {
        return Promise.resolve().then(function () { return require('.foo2'); });
    }
};
```

**typescript version:** 2.5.3

**Comment by mhegazy** [comment]
@kohlikohl, files #18968 to track this one.
