### ISSUE TITLE
How can we define custom global variable type?

### ISSUE THREAD

**Issue by Thaina** [Microsoft/TypeScript#17065]
I try to use jshint to define global variable in javascript. It avoid error but cannot register that variable into intellisense

![image](https://user-images.githubusercontent.com/1042507/28033441-79636208-65d8-11e7-9949-e579ea0250bf.png)

**Comment by andy-ms** [comment]
TypeScript won't do anything with jshint comments.
Consider adding a `test.d.ts` file using `declare var test: any;`. (Or use a more specific type.)

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
