### ISSUE TITLE
Enum Literal Types  2.4.1

### ISSUE THREAD

**Issue by acopalipsis** [Microsoft/TypeScript#17068]
```
enum E {
    A = 1,
    B = "b"
}

let valye: E.A | E.B = 123; // Ok?
```

**Comment by andy-ms** [comment]
Duplicate of #6131

**Comment by acopalipsis** [comment]
@andy-ms there on the enum in the role of type

**Comment by andy-ms** [comment]
I can't tell what the question is -- besides the problem of an arbitrary number being assignable to an enum type, which is issue #6131.
