### ISSUE TITLE
ESNext is missing from ts.ModuleKind

### ISSUE THREAD

**Issue by mohsen1** [Microsoft/TypeScript#17067]
https://github.com/Microsoft/TypeScript/blob/73ee2feb51c9b7e24a29eb4cee19d7c14b933065/lib/typescript.d.ts#L2193-L2199

I see esnext missing in some places where list of possible module kinds are written.

**Comment by kitsonk** [comment]
There is no such thing as an _ESNext_ module.  ES2015 was the specification for modules which introduced the top level `import` and `export` keywords.  Are you confusing it with a **target** of `esnext`?

**Comment by mohsen1** [comment]
I don't think that's true. See results for 

https://github.com/Microsoft/TypeScript/search?utf8=%E2%9C%93&q=module+esNext+&type=

**Comment by ikatyang** [comment]
module: `esnext` -> support dynamic import

There is the `ModuleKind.ESNext` in [src/compiler/types.ts](https://github.com/Microsoft/TypeScript/blob/master/src/compiler/types.ts#L3664-L3672) and published package, they just haven't updated their LKG, which is just for building typescript itself.

**Comment by kitsonk** [comment]
Ay, yes... you are right.  Apologies.

**Comment by mhegazy** [comment]
Fixed in latest.
