### ISSUE TITLE
Partial<generic> fails at matching types

### ISSUE THREAD

**Issue by testerez** [Microsoft/TypeScript#17071]
**TypeScript Version:**  2.4.0
**Code**

```ts
interface Foo { foo: string };

function test<T extends Foo>(): Partial<T> {
  return { foo: '' };
}

```

**Expected behavior:** should be ok

**Actual behavior:** `[ts] Type '{ foo: ""; }' is not assignable to type 'Partial<T>'.`

**Comment by RyanCavanaugh** [comment]
This is a correct error. Your definition for `test` says it's legal to write this:
```ts
test<{foo: "bar" | "qua"}>();
```
but your implementation clearly fails to return a `Partial<{foo: "bar" | "qua"}>`

**Comment by testerez** [comment]
Humm ok I see. Is there a way to work around you can think of? 
Because in my implementation I d'ont expect that a subtype of string will be used...

**Comment by RyanCavanaugh** [comment]
What's `T` even doing there? Just write `function test(): Partial<Foo>`

**Comment by testerez** [comment]
Yes, I guess I simplified my example too much. Here is a simplified example closer to what I'm tring to achieve:

```ts
interface Foo {
  foo: boolean;
}

const assign = <T>(o: T, newValues: Partial<T>): T => (
  Object.assign({}, o, newValues)
);

const setFoo = <T extends Foo>(o: T): T => assign(o, { foo: true });
// [ts] Argument of type '{ foo: true; }' is not assignable to parameter of type 'Partial<T>'.

const bar = {
  foo: false,
  bar: true,
}

const bar2 = setFoo(bar); // bar and bar2 have the same type

console.log(bar2); // ​​​​​{ foo: true, bar: true }​​​​​
```

**Comment by RyanCavanaugh** [comment]
You're going to need a type assertion here:
```ts
const toggleFoo = <T extends Foo>(o: T): T => assign(o, <T>{ foo: !o.foo });
                                                        ~~~
```

**Comment by testerez** [comment]
Ok thanks for the help

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
