### ISSUE TITLE
Wrong version strings

### ISSUE THREAD

**Issue by hastebrot** [Microsoft/TypeScript#1707]
So, TypeScript 1.4.0 was released. 

NPM tells me that there is a version 1.4.1, but no 1.4.0. The installed version 1.4.1 tells me `Version 1.3.0.0` using `tsc --version`.

~~~
λ tsc --version
message TS6029: Version 1.3.0.0
~~~

**Comment by erichillah** [comment]
This can happen if you've installed Typescript tools for visual studio along with npm for example. Try verifying `tsc` is in your path 
In my case for example i have this : 
```
where  tsc

D:\Users\[your_username]\AppData\Roaming\npm\tsc
D:\Users\[your_username]\AppData\Roaming\npm\tsc.cmd
C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.4\tsc.exe
C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.4\tsc.js

```
In case the first result is for example `C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.1\tsc.exe`, that can be the reason you're have version 1.3.0.0.

You can fix this by putting the path `D:\Users\[your_username]\AppData\Roaming\npm\tsc` after the one from visual studio in your path variable.

**Comment by hastebrot** [comment]
Thanks for the useful hint! The wrong version was due to I ran `npm install typescript` instead of `npm install -g typescript`. My bad.

Closed: Not an issue.

**Comment by basarat** [comment]
> TypeScript 1.4.0 was released. NPM tells me that there is a version 1.4.1, but no 1.4.0.

@hastebrot This is still true and perhaps this issue should not be closed and just the body updated ~~crossing out~~ sections that were invalid.

**Comment by erichillah** [comment]
@basarat typescript latest package published on NPM is version 1.4.1.

**Comment by basarat** [comment]
@erichillah yes. But its not a tagged release : https://github.com/Microsoft/TypeScript/releases and its unclear if its different from the `v1.4.0` that comes with Visual studio.

**Comment by basarat** [comment]
I'll create a separate issue
