### ISSUE TITLE
Optional destructured parameters do not work with default values

### ISSUE THREAD

**Issue by jqyu** [Microsoft/TypeScript#17080]
**TypeScript Version:**  2.4.0

**Code**

The following code incorrectly type checks:
```ts
interface Attrs {
    foo?: number;
    bar?: number;
}

function unsafe({ foo, bar }: Attrs = {}): number {
    return foo * bar.toString().length + 1;
}
```

**Expected behavior:**
This should fail to type check since `foo` and `bar` may both be of type `undefined`

**Actual behavior:**

Match behaviour of omitting default value:
```ts
function failsToTypecheck({ foo, bar }: Attrs): number {
    return foo * bar.toString().length + 1;
}
```
Or behaviour of omitting destructuring:
```ts
function failsToTypecheck(attrs: Attrs = {}): number {
    return attrs.foo * attrs.bar.toString().length + 1;
}
```

**Comment by mhegazy** [comment]
@sandersn we talked about this one before, any thoughts here?

**Comment by johnsoft** [comment]
Here's another example of this that I wrote up before searching for an existing issue:

```ts
interface Foo {
  readonly bar?: number;
}

function performFoo({ bar }: Foo = {}) {
  useBar(bar);  // `bar` should have type `number | undefined`, so this shouldn't compile.
}

function useBar(bar: number) {
  alert('The number is: ' + bar);
}

performFoo();
```

We've started using this pattern in our code, so I'm also interested in a fix for this.

**Comment by johnsoft** [comment]
If someone takes up fixing this, here is another potentially useful test case:

```ts
interface Foo {
  readonly bar?: number;
}

function performFoo({ bar = null }: Foo = {}) {
  useBar(bar);  // `bar` should have type `number | null`, so this call shouldn't compile.
}

function useBar(bar: number | undefined) {
  alert('The number is: ' + bar);
}

performFoo();
```

**Comment by Lazarus535** [comment]
I fixed the issue in PR https://github.com/Microsoft/TypeScript/pull/21328
