### ISSUE TITLE
Suggestion: Infer Narrowed Return Type of Immediately-Invoked Function Expression

### ISSUE THREAD

**Issue by Nathan-Fenner** [microsoft/TypeScript#17084]
**TypeScript Version:**  2.4.0

**Code**

```ts
let exampleError: "foo" | "bar" = (() => "foo")(); // error: 'string is not assignable to "foo" | "bar"
let exampleOkay1: "foo" | "bar" = ((): "foo" | "bar" => "foo")();
```

**Expected behavior:**

Both compile, with the return type of `exampleError` inferred to be `"foo" | "bar"`.

**Actual behavior:**

The first example doesn't narrow the inferred return type of the function, so we get an error.

**Suggested behavior:**

When a function expression (either an arrow function or an ordinary function expression) is called immediately where it is defined as in `(function(){})()` and an "expected" return type is known, we can infer this narrowed type, instead of only using the body of the function to narrow the type.

This introduces some very slightly non-local analysis, but it should be noted that it's not appreciable different from another case that narrowing already happens: function expressions as arguments with no return type annotation.

In particular, the following already works:

```ts
function onlyFooer(f: () => "foo") {
    // ...
}

onlyFooer(  () => "foo"  );
```

**Comment by forivall** [comment]
with #29510, you can do `() => "foo" as const`

**Comment by RyanCavanaugh** [comment]
Probably #241's fault anyway, but `as const` is a good enough workaround and this seems seldom-encountered.
