### ISSUE TITLE
tslib is polluting window object

### ISSUE THREAD

**Issue by MasterCassim** [microsoft/TypeScript#17089]
I got no answer over at the tslib repo, therefore I'm trying to get an answer here. Is there a reason why tslib is pushing the helper functions to the window object when module.exports is available?

-> https://github.com/Microsoft/tslib/blob/master/tslib.js#L38
-> https://github.com/Microsoft/tslib/issues/32

**Comment by RyanCavanaugh** [comment]
Continuing to track at the issue in the tslib repo
