### ISSUE TITLE
--noStrictGenericChecks isn't documented or in the NuGet package

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Microsoft/TypeScript#17099]
https://www.typescriptlang.org/docs/handbook/compiler-options.html
https://www.typescriptlang.org/docs/handbook/compiler-options-in-msbuild.html
http://json.schemastore.org/tsconfig

Strict generic checking can be a pretty major breaking change. It'd be nice to document the option to turn it off.

**Comment by JoshuaKGoldberg** [comment]
I'm also not seeing it in the MSBuild targets file on NuGet or in the default `tsc` output, though it is accepted as a compiler option.

**Comment by JoshuaKGoldberg** [comment]
@DanielRosenwasser by "Fixed" do you mean this shouldn't be placed in the `Options:` text in `--help`?

**Comment by DanielRosenwasser** [comment]
You can see the option if you use `--help --all`, but it's not currently in the default `--help`. The website should be updated.

**Comment by DanielRosenwasser** [comment]
Currently we don't have an MSBuild target for it though.

**Comment by andy-ms** [comment]
I noticed that we don't autocomplete this in `tsconfig.json` -- is that because the schema hasn't been updated?

**Comment by mhegazy** [comment]
MSBuild support for the two properties needs to be added still. tracked by https://github.com/Microsoft/TypeScript/issues/17848
