### ISSUE TITLE
Bug in type of RegExpMatchArray/RegExpExecArray

### ISSUE THREAD

**Issue by abramobagnara** [Microsoft/TypeScript#17094]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

**Expected behavior:**

From ECMA specification it should be:

```ts
interface RegExpMatchArray extends Array<string | undefined> {
    index?: number;
    input?: string;
}

interface RegExpExecArray extends Array<string | undefined> {
    index: number;
    input: string;
}

```

**Actual behavior:**

Currently is:

```ts
interface RegExpMatchArray extends Array<string> {
    index?: number;
    input?: string;
}

interface RegExpExecArray extends Array<string> {
    index: number;
    input: string;
}

```

**Comment by ikatyang** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/17053.

**Comment by jedmao** [comment]
@abramobagnara, where in the ECMA specification does it have the `index` prop as optional (undefined)?

**Comment by abramobagnara** [comment]
@jedmao, this is not what I've written: the fix should be about array items type.
