### ISSUE TITLE
Incorrect type assignment 

### ISSUE THREAD

**Issue by whitneyit** [Microsoft/TypeScript#17090]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

**Code**

```ts
type short = {
    a: number;
};

type long = short & {
    b: number;
    c: number;
};

type either = short | long;

const test: either = {
    a: 1,
    b: 2,
};
```

**Expected behavior:**
The `testBoth` variable would not be assignable to either the `short` or `long` type.

**Actual behavior:**
`testBoth` has some odd interim type.

**Notes:**
This also fails if `long` is defined as:

```ts
type long = {
    a: number;
    b: number;
    c: number;
};
```

**Comment by RyanCavanaugh** [comment]
See #16679

**Comment by whitneyit** [comment]
I'm not sure if that works. In the examples from #16679 there's unique properties on each type.

Given the following [example](http://www.typescriptlang.org/play/#src=type%20short%20%3D%20%7B%0A%20%20%20%20a%3A%20number%3B%0A%20%20%20%20b%3A%20never%3B%0A%20%20%20%20c%3A%20never%3B%0A%7D%3B%0A%0Atype%20long%20%3D%20%7B%0A%20%20%20%20a%3A%20number%3B%0A%20%20%20%20b%3A%20number%3B%0A%20%20%20%20c%3A%20number%3B%0A%7D%3B%0A%0Atype%20either%20%3D%20short%20%7C%20long%3B%0A%0Aconst%20obj%3A%20either%20%3D%20%7B%0A%20%20%20%20a%3A%201%2C%0A%7D%3B), `obj` cannot be assigned to type `either`.

```ts
type short = {
    a: number;
    b: never;
    c: never;
};

type long = {
    a: number;
    b: number;
    c: number;
};

type either = short | long;

const obj: either = {
    a: 1,
};
```

I'm looking at a way to type something as a subset of a larger object.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
