### ISSUE TITLE
2.4.1 Error: Type "typeof _" has no properties in common with type 'Component'

### ISSUE THREAD

**Issue by dgroh** [Microsoft/TypeScript#17100]
**TypeScript Version:**  2.4.1

**Code**

```ts
import { Component } from "@angular/core";

export function MockComponent(options: Component): Component {
  let metadata: Component = {
    selector: options.selector,
    template: options.template || "",
    inputs: options.inputs,
    outputs: options.outputs
  };

  return Component(metadata)(class {});
}
```

**Expected behavior:**

**Actual behavior:**

![image](https://user-images.githubusercontent.com/16785357/28084508-1a5feb36-6679-11e7-9d38-da7a4d8e081a.png)

**Comment by dgroh** [comment]
This was working with the previous version

**Comment by dgroh** [comment]
Closing this issue as it seems to be something with the new update of **Visual Studio Code**

**Comment by Kamilius** [comment]
Got same error but in terminal, for me it seems like it's not a **Visual Studio Code** issue

**Comment by ValentinHruzinski** [comment]
You can find temp solution of problem in this issue:
https://github.com/cnunciato/ng2-mock-component/issues/8

**Comment by satish-pokala** [comment]
I got same error I am using "typescript": "2.6.2"

Type 'typeof UserMgmtComponent' has no properties in common with type 'Component'.

with old versions it was working fine for me.

did any one find any solution for it.

**Comment by RyanCavanaugh** [comment]
See https://blog.mariusschulz.com/2017/12/01/typescript-2-4-weak-type-detection for an explanation of this message
