### ISSUE TITLE
`MediaError` interface in lib.dom.d.ts missing "message" property

### ISSUE THREAD

**Issue by trash** [microsoft/TypeScript#17101]
The `MediaError` interface in [`lib.dom.d.ts`](https://github.com/Microsoft/TypeScript/blob/master/lib/lib.dom.d.ts#L7805) is missing the ["message" string property from the spec.](https://html.spec.whatwg.org/multipage/media.html#mediaerror) It looks like it's included in most modern browsers except IE/Edge. So perhaps define it as: `message?: string;`.

Not sure if that file is supposed to be edited directly otherwise I'd open a PR myself.

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by nowy** [comment]
I can take care of this

**Comment by vlinder** [comment]
Think this has been fixed already. :)

Should be able to close it?

https://github.com/microsoft/TypeScript/blob/847992b64b4d79e0370de1c0001ce8c903482b9e/lib/lib.dom.d.ts#L10181-L10189

**Comment by jakebailey** [comment]
This has been fixed for a while (see above).
