### ISSUE TITLE
Formatter dedents pasted union

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#17108]
**TypeScript Version:**  nightly (2.5.0-dev.20170707)

**Code**

```ts
type T =
    | number
    | string;
```

Run "Format Document" and there is no change.
Cut this and paste it back, and it will be dedented to:

```ts
type T =
| number
| string;
```

**Comment by mhegazy** [comment]
The cut+past issue seems to be VSCode specific. @mjbvz do you have any insights here?

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/vscode#38833
