### ISSUE TITLE
TypeScript version v1.4.1

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#1711]
The version on NPM is `v1.4.1` is it any different from `v1.4.0`? https://github.com/Microsoft/TypeScript/releases

**Comment by johnnyreilly** [comment]
I was wondering the same...

**Comment by RyanCavanaugh** [comment]
For really boring technical reasons, we needed these version numbers to be different. There isn't any difference in code/behavior between the two as far as I know.

**Comment by mhegazy** [comment]
To be specific 1.4.1 inclueds these two addtional code changes:https://github.com/Microsoft/TypeScript/commit/d8468f7e8c01476dae59b83b4570227072194780 and  https://github.com/Microsoft/TypeScript/commit/1ebf90561b310eee24b8b376b3854e546f5ef03b

**Comment by mhegazy** [comment]
I have also cleared up the milestones for issues to align with releases, we had some issues sitting in 1.4.1 milestone.
