### ISSUE TITLE
VS code editor version 1.8.1 typescript intellicense and compiler error highlight stopped working after removal of admin rights

### ISSUE THREAD

**Issue by AbhishekSenSharma** [Microsoft/TypeScript#17115]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

**Code**

```ts
// A *self-contained* demonstration of the problem follows...

```

**Expected behavior:**

**Actual behavior:**

**Comment by mhegazy** [comment]
We will need more info here. and 1.8 has been out in a while and we have not made any changes to that package. I would recommend filing this to https://github.com/Microsoft/vscode/issues

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
