### ISSUE TITLE
Print warning when two Dates are compared

### ISSUE THREAD

**Issue by adius** [Microsoft/TypeScript#17119]
**Code**

```ts
const dateA = new Date()
const dateB = new Date()

if (dateA === dateB) {
  console.log('Can I haz warning?')
}
```

**Expected behavior:**
TypeScript compiler prints a warning because comparing if dateA and dateB are the same Date object is probably not what I want to do.

**Actual behavior:**
Nothing happens.

**Comment by andy-ms** [comment]
Duplicate of #15506

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
