### ISSUE TITLE
Structural type compatibility

### ISSUE THREAD

**Issue by acopalipsis** [Microsoft/TypeScript#17116]
```
class Bird { name; }
class Fish { name; fins; }

var animal: Bird = new Fish(); // Ok
var animal: Fish = new Bird(); // Error
```

```
class Bird { name; wings; }
class Fish { name; }

var animal: Bird = new Fish(); // Error
var animal: Fish = new Bird(); // Error
```

This is a bug?

**Comment by olegdunkan** [comment]
`var animal: Bird = new Fish(); // Error` is error as expected 
`var animal: Fish = new Bird(); // Error` is error because you redeclare `var` `animal` with other type.
stackoverflow.com is the best place to ask questions.
