### ISSUE TITLE
Invalid JS emitted when passing async fat arrow function as argument to decorator factory function

### ISSUE THREAD

**Issue by thomas-r7** [Microsoft/TypeScript#17118]
**TypeScript Version:**  2.4.1 (release-2.4 branch)

When passing an async fat arrow function to a decorator factory function for a decorator on a class, when targeting ES5, invalid JavaScript is emitted. The __awaiter helper call makes reference to a _this variable which is never defined. 

**Code**

```ts
function TestDecorator(f: () => PromiseLike<void>): ClassDecorator
{
    return function(target) { };
}

@TestDecorator(async () => { })
class TestClass { }

```

**Expected behavior:**
The following JS code is emitted.
```js
// ... helpers ...
var _this = this;
function TestDecorator(f) {
    return function (target) { };
}
var TestClass = (function () {
    function TestClass() {
    }
    TestClass = __decorate([
        TestDecorator(function () { return __awaiter(_this, void 0, void 0, function () { return __generator(this, function (_a) {
            return [2 /*return*/];
        }); }); })
    ], TestClass);
    return TestClass;
}());
```
JS executes without error.

**Actual behavior:**
The following JS code is emitted.
```js
// ... helpers ...
function TestDecorator(f) {
    return function (target) { };
}
var TestClass = (function () {
    function TestClass() {
    }
    TestClass = __decorate([
        TestDecorator(function () { return __awaiter(_this, void 0, void 0, function () { return __generator(this, function (_a) {
            return [2 /*return*/];
        }); }); })
    ], TestClass);
    return TestClass;
}());
```
JS executes with following error: "ReferenceError: _this is not defined"

The _this variable is **correctly** emitted in the following circumstances:

- The fat arrow async function is changed to a normal function
- The fat arrow async function is not passed into a decorator and is instead passed into a normal function call
- The fat arrow async function is declared and stored in a local, then that local is passed into the decorator factory

The incorrect behaviour is NOT observed in 2.3.5.

Compiler command line: _tsc --target es5 --experimentalDecorators --lib ES2015 ./test.ts_

**Comment by aluanhaddad** [comment]
Seems to works in the [playground](https://www.typescriptlang.org/play/#src=function%20TestDecorator(f%3A%20()%20%3D%3E%20PromiseLike%3Cvoid%3E)%3A%20ClassDecorator%20%7B%0D%0A%20%20return%20function%20(target)%20%7B%20%7D%3B%0D%0A%7D%0D%0A%0D%0A%40TestDecorator(async%20()%20%3D%3E%20%7B%20%7D)%0D%0Aclass%20TestClass%20%7B%20%7D)

**Comment by thomas-r7** [comment]
Are we able to determine the current version of TS that the playground is running? I did try that and assumed (perhaps incorrectly) that the playground is running 2.3 and not 2.4.

**Comment by mhegazy** [comment]
Can not seem to get this to reproduce on latest.

```sh
c:\test\sandbox>tsc --v
Version 2.5.0-dev.20170816

c:\test\sandbox>type a.tsx
function TestDecorator(f: () => PromiseLike<void>): ClassDecorator
{
    return function(target) { };
}

@TestDecorator(async () => { })
class TestClass { }
c:\test\sandbox>tsc a.tsx --experimentalDecorators --types --lib es6

c:\test\sandbox>node a.js

c:\test\sandbox>
```

**Comment by thomas-r7** [comment]
Try targeting ES5:
`tsc a.tsx --experimentalDecorators --target
 es5`

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
