### ISSUE TITLE
Support new compiler flags in Visual Studio

### ISSUE THREAD

**Issue by nycdotnet** [Microsoft/TypeScript#1712]
It would be great to get checkboxes for the new TypeScript 1.4 compiler flags in Visual Studio 2013.  In particular, `noEmitOnError` (actually to disable it, since this seems to default to on now in VS, but seemingly not on the command line).  `suppressImplicitAnyIndexErrors` and `preserveConstEnums` would also be great to see.  Many thanks!

**Comment by mhegazy** [comment]
There is no UI support (project property pages) for all switch, we only have the ones most commonly used. however, you can still control them from the project file by adding an MSBuild property. so for noEmitOnError, just add:
```XML
<PropertyGroup>
    <TypeScriptNoEmitOnError>false</TypeScriptNoEmitOnError>
</PropertyGroup>
```

Just as a note, the reason why noEmitOnError is set by default is to allow incremental build to work correctly. MSBuild incremental build relies on checking the timestamps of input (.ts) files against those of the output (.js) files. The typescript compiler does generate outputs in the face of semantic errors (e.g. number not assignable to string). this means that if you have an error, build first time, build fails, then build a second time with no changes to your project, this time the build succeeds, cause it finds all outputs up-to-date. This can be really confusing in big projects where you only see all errors on rebuild.

And for future references, here is the full list of MSBuild property names for controling diffrent flags.

```XML
<TypeScriptRemoveComments>               
<TypeScriptNoImplicitAny>                     
<TypeScriptGeneratesDeclarations>             
<TypeScriptModuleKind>                        
<TypeScriptOutFile>                           
<TypeScriptOutDir>                            
<TypeScriptSourceMap>                         
<TypeScriptTarget>                            
<TypeScriptNoResolve>                         
<TypeScriptAdditionalFlags>                   
<TypeScriptMapRoot>                           
<TypeScriptSourceRoot>                        
<TypeScriptCodePage>                          
<TypeScriptCharset>                           
<TypeScriptEmitBOM>                           
<TypeScriptNoLib>                             
<TypeScriptPreserveConstEnums>                
<TypeScriptSuppressImplicitAnyIndexErrors> 
```

**Comment by nycdotnet** [comment]
Thanks.  This documentation is very helpful.  I may submit a PR to web essentials to add a separate UI.  For future versions of the VS extension, it would be so great to have an option to treat type errors as warnings.  This would allow "first time converters" to get the old default behavior which in my opinion was better while you were just getting started.  Technically 1.4 is a breaking change for people in that phase of TypeScript implementation.  Thanks so much!  I think 1 4 is awesome.

**Comment by nycdotnet** [comment]
Looks like Mads isn't interested to add this to Web Essentials so I guess manually editing the project is the only way.  Thanks Mohamed.

**Comment by danquirk** [comment]
I really don't think we should ask people to manually hack up the project file. If it's important enough to expose a compiler option for then we should provide UI for that setting. If we don't want to make the project properties have 30 different checkboxes then we could always provide a textbox for writing out command line args.

**Comment by nycdotnet** [comment]
> If it's important enough to expose a compiler option for then we should provide UI for that setting.

Awesome.  +1000000 if this could mean type errors as Visual Studio warnings.

**Comment by mhegazy** [comment]
Not all compiler options have the same usage numbers, some are more common than others. for instance --module vs. --emitBOM. 

Adding a text box for a command line gets a bit tricky with Language Service and compiler having different versions, MSBuild properties are nicer in this front, as they are honored only by the systems that understand them and ignored by others. 

@nycdotnet this is a different feature, the compiler currently only emits errors, and there is no commandline option for changing their category to 'warning'. I would file another issue for this request.

**Comment by nycdotnet** [comment]
@mhegazy Understood.  We've had good luck on the grunt-ts team identifying the difference (emit-preventing vs non-emit preventing), but agreed it's a separate issue.  I will submit and try to find the old codeplex request as well.  Many thanks.

**Comment by mhegazy** [comment]
@nycdotnet, on a side note, the compiler now returns a code that tells you if the errors have prohibited emit or not. See [EmitReturnStatus](https://github.com/Microsoft/TypeScript/blob/master/src/compiler/types.ts#L976)]

**Comment by gulbanana** [comment]
editing the project file is no use for typescript files in a virtual project

**Comment by mhegazy** [comment]
@gulbanana we will be adding tsconfig support to VS in the next release. So that would be your way to configure your virtual projects.

**Comment by danquirk** [comment]
We need to fix this. Asking people to edit project files is a bad user experience, especially for core flags like this one.

**Comment by basarat** [comment]
> editing the project file is no use for typescript files in a virtual project

perhaps virtual projects can be `tsconfig.json` based

**Comment by gulbanana** [comment]
cool, sounds good- when you say the next version, do you mean VS2015?

**Comment by mhegazy** [comment]
By next release I mean TypeScript 1.5. we do not have a set scheduled for this release yet.
