### ISSUE TITLE
Mixins documentation is out of date in the handbook

### ISSUE THREAD

**Issue by Taytay** [microsoft/TypeScript#17126]
I don't know if this is where documentation bugs are filed, but the Mixins section of the Handbook (https://www.typescriptlang.org/docs/handbook/mixins.html) appears to be incomplete now that enhanced Mixin support of 2.2 is out: 
https://github.com/Microsoft/TypeScript/pull/13743

If there's a better place for this, please just say the word!

**Comment by DanielRosenwasser** [comment]
I'd say this is a duplicate of https://github.com/Microsoft/TypeScript-Handbook/issues/574, but I'll keep it open on this side as well.

**Comment by Taytay** [comment]
Thanks @DanielRosenwasser! I'll file over there next time around :)

**Comment by RyanCavanaugh** [comment]
Handbook has since been rewritten
