### ISSUE TITLE
[Jsdoc] Optional parameter types should be merged with 'undefined'

### ISSUE THREAD

**Issue by pc-lover** [Microsoft/TypeScript#17134]
**TypeScript Version:**  2.4.1
with `checkJs` and `strict` both are enabled in the `tsconfig` file

**Code (js)**

```js
/**
 * @param {string=} bar
 */
function foo(bar) {
    if (bar == null) {
        bar; // hover shows 'never'
    }
}

foo(); // calling foo is okay without any arguments
```

**Expected behavior:**
Type of `bar` should be `string | undefined`

**Actual behavior:**
Type of `bar` is `string`

**Comment by mhegazy** [comment]
Should be working in latest.
