### ISSUE TITLE
Variable which is modified in a hidden IIFE is locked to its original type

### ISSUE THREAD

**Issue by LordJZ** [Microsoft/TypeScript#17137]
**TypeScript Version:**  playground (2.2+)

**Code**

```ts
enum A { a, b }
const execute = (f: Function) => f();

let v = A.a; // 1
execute(() => {
    v = A.b;
});

console.log(v == A.a);
console.log(v == A.b); // 2
```

**Expected behavior:**
Compiles fine

**Actual behavior:**
Error on the last line (`// 2`)

Inlining `execute` or removing IIFE helps. If that is impossible, only casting `A.a` to `any` helps (at `// 1`), which is ugly.

**Comment by andy-ms** [comment]
Wider issue: #9998

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
