### ISSUE TITLE
Dot syntax for inferred enums

### ISSUE THREAD

**Issue by kozlowski-mathias** [Microsoft/TypeScript#1713]
Hi, a Swift-like short dot syntax for enums could be handy, what do you think?

enum Color {Red, Green, Blue};
var c: Color = .Green;    // instead of var c: Color = Color.Green;

**Comment by DanielRosenwasser** [comment]
I'll point out that it's not especially useful in your example because the type annotation can be omitted.

So instead of
```TypeScript
var c: Color = Color.Green;
```
you can get away with the following:
```TypeScript
var c = Color.Green;
```

The real power of this syntax in Swift is in `switch`/`case`s as follows:

```Swift
switch c {                      
    case TokenKind.OpenParen:        
        // yadda
        break;
    case TokenKind.CloseParen:      
        // yadda
        break;
    case TokenKind.OpenCurlyBrace:        
        // yadda
        break;
    case TokenKind.CloseCurlyBrace:
        // yadda
        break;
    case TokenKind.OpenSquareBrace:   
        // yadda
        break;
}
```
rather than

```Swift
switch c {                      
    case .OpenParen:        
        // yadda
        break;
    case .CloseParen:      
        // yadda
        break;
    case .OpenCurlyBrace:        
        // yadda
        break;
    case .CloseCurlyBrace:
        // yadda
        break;
    case .OpenSquareBrace:   
        // yadda
        break;
}
```

I know, I yadda-yadda'd over all the best parts.

I personally don't mind full qualification here, but it can be a pain when you have to write out `ts.SyntaxKind.NoSubstitutionTemplateString`.

**Comment by kozlowski-mathias** [comment]
My example was extracted from typescriptlang.org handbook to illustrate
what I mean by "short dot syntax", not because it is my most useful case
:-p I think every one is coding can appreciate syntax advantages...
Yes, less typing and less visual distraction.

2015-01-18 21:08 GMT+01:00 Daniel Rosenwasser <notifications@github.com>:

**Comment by cevek** [comment]
That sounds great!
`var c: Color = .Green; ` this looks nice

**Comment by LinusU** [comment]
It's also very useful when calling third party functions:

```typescript
Framework.ColorUtils.Combine(Framework.Colors.Red, Framework.Colors.Green)
```

vs.

```typescript
Framework.ColorUtils.Combine(.Red, .Green)
```

**Comment by mhegazy** [comment]
We have historically rejected features that does type-directed emit (in this case knowing the type of the enum is the only way to write a valid property access at runtime). moreover, this introduces a new expression-level syntax that may collide with future ES standards.
