### ISSUE TITLE
getApplicableRefactors taking a long time

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#17133]
The log from https://github.com/Microsoft/vscode/issues/30449#issuecomment-314699601 shows that `getApplicableRefactors` can take a long time after a small change has been made to one file. The tsserver log doesn't tell us much about what is taking the time -- we could add deeper logging to help investigate.
CC @RyanCavanaugh

**Comment by billti** [comment]
What's the latest with this? Does VS Code need this fix so they can reenable the refactorings they had to disable via the 1.14.1 recovery build? cc @mjbvz

**Comment by andy-ms** [comment]
It's still not certain that `getApplicableRefactors` was actually to blame; something else might have been going on. It would be nice to have functionality to turn that on and off so users could test if that was causing the problem for them.
Linking Microsoft/TypeScript#17269 since that might be related to apparent performance problems too.

**Comment by mjbvz** [comment]
We re-enabled the refactorings in VS Codes insiders builds and have not seen any further CPU usage issues reported. If there is still any concern about this feature in TS 2.4, we could always gate it to ts 2.5 on the VSCode side

**Comment by mhegazy** [comment]
Discussing this offline today with @andy-ms and @mjbvz, we do not believe this is related to refactoring. closing for now, please open a new issue if there are perf degradation and we will investigate.
