### ISSUE TITLE
Block comment corrupts emit

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/TypeScript#1714]
Hi,

**TS Version**: 1.4

The following code:

```TypeScript
var x: any;
/*
var bar;
*/
```

Emits the following JavaScript

```JavaScript
var x;
/*
var bar;
var x: any;
/*
var bar;
```

Expected

```JavaScript
var x;
/*
var bar;
*/
```

**Comment by DickvdBrink** [comment]
Notice what happens when you add an additional newline after the comment (the problem disappears) at least on the playground

**Comment by NoelAbrahams** [comment]
Yes, that's probably why it slipped through.

**Comment by DickvdBrink** [comment]
For what is worth it:
With the below code:

    console.log("1")
    /*bar*/

https://github.com/Microsoft/TypeScript/blob/1e8e65c8396c29403023ad52bf3501f13b08f3f4/src/compiler/emitter.ts#L175
currentSourceFile.getPositionFromLineAndCharacter(currentLine + 1, 1) is called with 3 and returns `NaN`.

This is actually a really big issue because with the above issue it generates the console.log statement 2 times.

**Comment by RyanCavanaugh** [comment]
This seems to have been the behavior since v1.1; anyone have any clues why we're just seeing it being reported today? (Are people going straight from 1.0 to 1.4?). Just curious.

**Comment by basarat** [comment]
I thought I was updated (continuously) till I saw this, I was surprised by `1.0.3` 

![image](https://cloud.githubusercontent.com/assets/874898/5809181/f2a86530-a089-11e4-9b29-370358313aae.png)

Fortunately I've been using `grunt` for actual production compilations :)

**Comment by DickvdBrink** [comment]
@RyanCavanaugh I only used 1.1 briefly for my own projects (not in production at work). Not sure why I never saw this on 1.3 because we are using that heavily. But yeah, it is not to common to have documentation on the last line.

**Comment by NoelAbrahams** [comment]
@RyanCavanaugh, the same code was compiling fine in `1.3`.

**Comment by basarat** [comment]
@RyanCavanaugh I agree not in `1.3`:

![image](https://cloud.githubusercontent.com/assets/874898/5828519/709ce11c-a159-11e4-9b3e-8033d1eb5d47.png)

**Comment by RyanCavanaugh** [comment]
This is confusing. :disappointed: 

```ts
C:\github\TypeScript-1.3>type a.ts
var x; /* foo */

C:\github\TypeScript-1.3>node built\local\tsc.js a.ts && type a.js
var x; var x;

C:\github\TypeScript-1.3>node built\local\tsc.js --v
message TS6029: Version 1.3.0.0

C:\github\TypeScript-1.3>git status
HEAD detached at v1.3
```
Need to figure out if our git tag and npm package don't match or if something else is going on...

**Comment by basarat** [comment]
@RyanCavanaugh `npm install Microsoft/TypeScript#v1.3` is same as `npm install typescript@1.3.0` (did a file diff)

My test was wrong for `1.3` (it is correct for 1.4 from experimentation in the playground): 
```

C:\Users\basaratsyed\Downloads\ts\comments>type test.ts
console.log("1")
/*bar*/

C:\Users\basaratsyed\Downloads\ts\comments>node ./node_modules/typescriptGITHUB/bin/tsc test.ts

C:\Users\basaratsyed\Downloads\ts\comments>type test.js
console.log("1");

C:\Users\basaratsyed\Downloads\ts\comments>type test.ts
console.log("1")/*bar*/

C:\Users\basaratsyed\Downloads\ts\comments>node ./node_modules/typescriptGITHUB/bin/tsc test.ts

C:\Users\basaratsyed\Downloads\ts\comments>type test.js
console.log("1"); console.log("1")

```
