### ISSUE TITLE
Intellisense not detecting array type

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#17140]
_From @benjaminmillhouse on July 12, 2017 18:57_

- VSCode Version: 1.14.0

Steps to Reproduce:

1. Add an array as a property of an object and document the @type
2. View Intellisense for the property

<img width="489" alt="screen shot 2017-07-12 at 2 44 36 pm" src="https://user-images.githubusercontent.com/13835886/28134836-3646bd68-6712-11e7-9627-245b251d13d8.png">

Reproduces without extensions: Yes

_Copied from original issue: Microsoft/vscode#30537_

**Comment by mjbvz** [comment]
Tested on TS 2.4.1

Code sample:

```js
const z = {
	/** @type {number[]} */
	x: []
}

z.
```

**Comment by andy-ms** [comment]
I could reproduce this with `typescript@2.4.1` but not with `typescript@next`.

**Comment by mhegazy** [comment]
should be working in latest.
