### ISSUE TITLE
Cannot annotate caught exception type with JSDocs

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#17142]
**TypeScript Version:**  2.4.1

**Code**
In a JS file:

```ts
try {
	throw 'I am error'
} catch (/** @type {string} */ e) {
	e
}
```

**Expected behavior:**
Type of `e` is `string`

**Actual behavior:**
Type of `e` is `any`

**Comment by mhegazy** [comment]
i do not think this is accurate. you have no way to force the type of the exception to be `string`. the exception can by anything inside the block. a better approach is to cast, e.g.
```ts
try {
} catch ( e) {
	/** @type {string} */(e).|
}
```
