### ISSUE TITLE
Union types are not allowed in indexers

### ISSUE THREAD

**Issue by jods4** [Microsoft/TypeScript#1715]
I have declared `function getter(key: string|number)`.
Inside I try to do `var x = someObject[key]`
I get a TS error saying "An index expression argument must be of type 'string', 'number' or 'any'.
Obviously `key` satisfies this constraint as it is either a string or a number. But I guess the TS compiler does hard type equality checks in this case.

**Comment by ahejlsberg** [comment]
You're right, we'll fix that.
