### ISSUE TITLE
vscode does not recognize ts files as belonging to the project 

### ISSUE THREAD

**Issue by akosyakov** [Microsoft/TypeScript#17159]
I have `tsconfig.json` that makes use of paths:
```json
{
    "compilerOptions": {
        "baseUrl": ".",
        "paths": {
            "trash": [
                "typings/trash"
            ]
        }
    }
}
```

In vscode `typings/trash/index.js` is opened as an external file to the project with the following uri: `~/myproject/typings/trash/index.js`. If i replace `baseUrl` with the absolute path to the project then a uri looks like `/Users/kosyakov/myproject/typings/trash/index.js` and vscode is able to open the file properly.

**Comment by mhegazy** [comment]
so you have `--allowjs` enabled?

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
