### ISSUE TITLE
JSDocs: @augments only works with Component and not with React.Component 

### ISSUE THREAD

**Issue by zanza00** [Microsoft/TypeScript#17157]
﻿I think I found a bug about javascript files, jsdocs comments `@augments` and react components.

If I use `React.PureComponent` code completions doesn't works, if I  use `PureComponent` it works 

**TypeScript Version:**  2.4.1 (the one shipped in vscode insiders)

**Code**

```javascript
// doesn't works
import React from "react";

/**
 * @augments {React.PureComponent<{ text: string }, {}>}
 */
export default class Text extends React.PureComponent {
  render() {
    <div>
      {this.props.text}
    </div>;
  }
}
```

```javascript
// works as expected
import React, { PureComponent } from "react";

/**
 * @augments {PureComponent<{ text: string }, {}>}
 */
export default class Text extends PureComponent {
  render() {
    <div>
      {this.props.text}
    </div>;
  }
}

```

**Expected behavior:**

with the second example the type is correct so code completion works as expected
```
(property) React.Component<{
    text: string;
}, {}>.props: Readonly<{
    children?: React.ReactNode;
}> & Readonly<{
    text: string;
}>
```

**Actual behavior:**

the type in the first example the inferred type is this 
```
(property) React.Component<{}, {}>.props: Readonly<{
    children?: React.ReactNode;
}> & Readonly<{}>
```

so `ctrl + space` doesn't have _text_

**Comment by mhegazy** [comment]
Should be working correctly in latest drop of TypeSript (TS 2.5.0 or later). VSCode ships with an older version of TypeScript. Please see [Using Newer TypeScript Versions](https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions) documentation for more details on updating your VSCode to use a different version of TypeScript.
