### ISSUE TITLE
error TS18003: No inputs were found in config file 'tsconfig.json'. Specified 'include' paths were '["src/**/*"]' and 'exclude' paths were '["node_modules"]'.

### ISSUE THREAD

**Issue by Hal-pan** [Microsoft/TypeScript#17155]
can't parsing tsconfig.json

error TS18003: No inputs were found in config file 'tsconfig.json'. Specified 'include' paths were '["src/**/*"]' and 'exclude' paths were '["node_modules"]'.

tsconfig.json:

> {
  "compileOnSave": true,
  "compilerOptions": {
    "experimentalDecorators": true,
    "sourceMap": true,
    "strict": true,
    "module": "es2015",
    "moduleResolution": "node",
    "target": "es5"
  },
  "include": [
    "src/**/*"
  ],
  "exclude": [
    "node_modules"
  ]
}

webpack config:

>   {
        test: /\.tsx?$/,
        loader: 'ts-loader',
        include: [resolve('src')],
        options: {
          appendTsSuffixTo: [/\.vue$/],
        }
      },

use:
vue2, webpack2, typescript2.4.1

**Comment by andy-ms** [comment]
Are you using `tsc` to compile your project?
Is there a `src` directory next to your `tsconfig.json` that contains `.ts` files?

**Comment by Hal-pan** [comment]
this ok now, thank. `.ts` files write wrong.

**Comment by saishbhende24** [comment]
I am getting the same error I also have `.ts` files in src folder. My `package.json` is like this 
```

{
  "compilerOptions": {
    "rootDir": ".",
    "experimentalDecorators": true,
    "module": "es2015",
    "moduleResolution": "node",
    "noUnusedParameters": true,
    "strictNullChecks": true,
    "skipLibCheck": true,
    "outDir": "./dist/packages/all",
    "target": "es2015",
    "lib": ["es5", "es2015", "dom"],
    "types": ["jasmine"],
    "baseUrl": ".",
    "paths": {
      "@angular/material": ["./src/lib/public_api.ts"],
      "@angular/cdk/*": ["./src/cdk/*"],
      "@angular/material-examples": ["./src/material-examples"],
      "material2-build-tools": ["./tools/package-tools"]
    }
  },
  "include": [
 "/"
  ],
  "exclude": [
    "/"
  ]
}
```

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Comment by andy-ms** [comment]
@saishbhende24 Maybe remove the `"exclude"`?

**Comment by kishorequalitlabs** [comment]
I to have the same issue, the error was not there before, suddenly it appeared and not able to find root cause
