### ISSUE TITLE
Where can I find the definitive list of types?

### ISSUE THREAD

**Issue by goldingdamien** [Microsoft/TypeScript#17152]
Is there a page listing all the types(TypeScript only. Do not require JavaScript classes) available in an easy to read format(not a guide which might or might not be comprehensive)?

If so, please can you provide the link. If not, I would like to request this to be made.

Regards.

**Comment by akdor1154** [comment]
What examples of types would you expect to see in such a page? What you're asking for is a bit vague.

**Comment by goldingdamien** [comment]
I would expect just definitions(name, description, any other meta data, links).
Main usage would be for knowing quickly what is available for learning and comparing with other libraries.

*I know what TypeScript is but have never used it before. I generally like to compare things before committing a lot of time to learning something.
I was quickly able to find the below, but it is a guide so is very verbose and is difficult to understand if there are more types and where they are.
https://www.typescriptlang.org/docs/handbook/basic-types.html

Regards.

**Comment by ikatyang** [comment]
Did you mean the [Specification](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md)?

**Comment by akdor1154** [comment]
As an aside, I'm not sure if your approach for comparing is feasible to be honest. You couldn't compare two human languages by looking at a list of their 100 most common words for instance. Trying to compare programming languages in the same way is similarly futile. Sorry, but I think you're either going to have to either do some reading (the guide is not hard to read) or just start experimenting.
If English isn't your native language, would you request a translation of the guide?

**Comment by goldingdamien** [comment]
@ikatyang Thank you. The ts file is of much help. Ideally, something with that information in an easy-to-read api documentation style format would be better, but the code seems easy enough to read through so I'll use it for now.

**Comment by goldingdamien** [comment]
@akdor1154 I don't understand why it is not feasible. Presenting data in a simpler form is only of benefit. I am not trying to compare entire programming languages, just the available typing. English is my native language.

Regards.
