### ISSUE TITLE
vs2017 typescript 2.4.1 : no code completion, goto definition ....

### ISSUE THREAD

**Issue by rekna1** [Microsoft/TypeScript#17158]
**TypeScript Version:**  2.4.1,  VS 2017 15.2 (26430.15)

After upgrading to Typescript 2.4.1, I get no code completion, goto definition. Seems whole language service is not working.

- PATH settings adjust to point to C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.4 folder
- tried uninstalling all previous versions + devenv /updateconfiguration  + devenv /clearcache + reinstall

Are there any steps I could do to diagnose/fix the problem?

No problem in VSCode...

**Expected behavior:**
Working code completion, goto definition, ...

**Actual behavior:**
no code completion, no goto definition..

**Comment by rekna1** [comment]
Solved : check 

Tools/Options/"Javascript/Typescript"/Intellisense/General

"Use TypeScript version"  should be set.

**Comment by odrozd** [comment]
I am still have some sort of issues with VS intellisense and TS 2.4, I created separate issue to address it #17351
