### ISSUE TITLE
New Website Logo: IrCrypto

### ISSUE THREAD

**Issue by mohammadKarimi** [Microsoft/TypeScript#17153]
Please fill the following out:

- Name: IrCrypto
- Homepage url: http://ircrypto.com/
- Brand Guidelines/Licensing: 
- Logo: http://ircrypto.com/content/images/logo.png

**Comment by DanielRosenwasser** [comment]
Hey @mohammadKarimi can you provide a larger size PNG? Something around 500x200px would work better.

**Comment by DanielRosenwasser** [comment]
Actually, it looks fine in the current display.
