### ISSUE TITLE
Suggestion: ability to use types, that are import-exported

### ISSUE THREAD

**Issue by CzBuCHi** [Microsoft/TypeScript#17160]
**TypeScript Version:**  2.4.1 

**Code**

```ts
export { that } from 'there';

var what = that; // error
```

**~~Expected~~ Desired behavior:**
No error

**Actual behavior:**
tsc shows error 'Cannot find name 'that'

---
- i know that i can fix this error by adding import line but it feels like code duplication:
```ts
export { that } from 'there'; // these two lines diffs only
import { that } from 'there'; // by keyword import / export

var what = that; // all fine now
```

- for backward compatibility import clause could be somethind like (or whatever new keyword)
```ts
importexport { that } from 'there';
```

- Priority: low

**Comment by kitsonk** [comment]
TypeScript aligns to the ES Import syntax.  Changes to that syntax should be addressed with [TC39](https://www.ecma-international.org/memento/TC39.htm)/[ESDiscuss](https://esdiscuss.org/).

**Comment by CzBuCHi** [comment]
Ah i see ... so just wait couple of years :) ... nevermind. Forget about this ...
