### ISSUE TITLE
Template strings and keyword colorization

### ISSUE THREAD

**Issue by DickvdBrink** [Microsoft/TypeScript#1716]
See screenshot, only happens after the `${num}` stuff
Running VS 2013

Because I didn't have an ending `*/` the whole file is now shown as a comment

![capture](https://cloud.githubusercontent.com/assets/765657/5792975/b93ef542-9f31-11e4-9c87-d4cf4ee69f67.PNG)

**Comment by DanielRosenwasser** [comment]
Known issue and duplicate of #1477 and #1698. Unfortunately this won't work in VS2013 but it does for VS2015.

**Comment by DanielRosenwasser** [comment]
@DickvdBrink if you're still interested, there's a partial fix here: https://github.com/Microsoft/TypeScript/issues/1698#issuecomment-70594428

**Comment by DanielRosenwasser** [comment]
A fix is now in `master`.

**Comment by DickvdBrink** [comment]
Wow, I didn't saw this until today xD Thanks @DanielRosenwasser

**Comment by DanielRosenwasser** [comment]
You're very welcome! Did you just see the change with 1.5-alpha?

**Comment by DickvdBrink** [comment]
Yes, I made a build myself and the above one was fixed! Thanks!
