### ISSUE TITLE
Nullable boolean defaults true

### ISSUE THREAD

**Issue by NitayRabi** [Microsoft/TypeScript#17164]
**TypeScript Version:**  2.3.4 

// A *self-contained* demonstration of the problem follows...
![image](https://user-images.githubusercontent.com/24541325/28173874-7924e682-67f8-11e7-854b-a4e1fc080ecc.png)

**Expected behavior:**
Nullable boolean defaults to false | undefined
**Actual behavior:**
nullable boolean defaults to true

**Comment by weswigham** [comment]
You're at a break point in your editor. That quick info is the debugger showing you that the value passed into that function for `refreshCache` is true. There's nothing typesystem-wise going on here, that's just the actual runtime value you've passed in.

![image](https://user-images.githubusercontent.com/2932786/28177973-9d48aec8-67b1-11e7-9ee8-5f2be9ae6484.png)

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
