### ISSUE TITLE
Why not of a type mismatch error?

### ISSUE THREAD

**Issue by acopalipsis** [Microsoft/TypeScript#17171]
```
type FuncWith2ParamAndReturnVoid = (a: number, b: string) => void;

let func: FuncWith2ParamAndReturnVoid = function (): number {
    return 0;
} // ??? where error?
```

**Comment by ikatyang** [comment]
`void` means not return value, so that whatever value you want to return, that does not matter, since no one uses its return value.

**Comment by acopalipsis** [comment]
@ikatyang why the parameters are not taken into account?

**Comment by ikatyang** [comment]
for example:

```ts
function forEach(array: any[], callback: (value: any, index: number, array: any[]) => void) {
    for (let i = 0; i < array.length; i++) {
        callback(array[i], i, array);
    }
}

// the following cases are all assignable
forEach([1, 2, 3], (n, i, a) => console.log(n, i, a));
forEach([1, 2, 3], (n, i) => console.log(n, i));
forEach([1, 2, 3], n => console.log(n));
//                 ^
// you can omit its parameter
```

**Comment by acopalipsis** [comment]
@ikatyang problem as an example?? This is nonsense.

**Comment by olegdunkan** [comment]
[See spec](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#3114-assignment-compatibility)

[See FAQ](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-functions-with-fewer-parameters-assignable-to-functions-that-take-more-parameters)

**Comment by acopalipsis** [comment]
@olegdunkan the name of the topic on the link

> Why are functions with fewer parameters assignable to functions that take more parameters?
I understand. But in my case Vice versa!

**Comment by olegdunkan** [comment]
`FuncWith2ParamAndReturnVoid` has two parameters,   `function (): void {  return 0; }` has zero parameters 
you assign  `function (): void {  return 0; }` to `FuncWith2ParamAndReturnVoid`

**Comment by acopalipsis** [comment]
@olegdunkan You are reading what is written on the link you gave me?

**Comment by olegdunkan** [comment]
Typescript is the very wise language it combines dynamic nature and experience of java script programming and type-safe languages like C#, C++.

**Comment by acopalipsis** [comment]
@olegdunkan is not noticeable. I spent two years of his praise, and now I think that this is another ms product.

**Comment by RyanCavanaugh** [comment]
@acopalipsis Please stop using the issue tracker as a support forum or discussion board. This is not the correct place to ask questions, complain about FAQ answers, or :-1: people who are responding to your questions. You are free to disagree with design decisions made in TypeScript but the issue tracker is for tracking bugs, and we do not consider these behaviors do be bugs.
