### ISSUE TITLE
Incorrect check for objects in callback arguments

### ISSUE THREAD

**Issue by darkartur** [Microsoft/TypeScript#17170]
**TypeScript Version:**  2.4.1, 2.3.4

**Code**

```ts
interface SmallOptions {
	option1: boolean;
	option2: string;
}

interface BigOptions extends SmallOptions {
	option3: string[];
}

function receiver(expectedFunction: (options: SmallOptions) => void) {
	expectedFunction({
		option1: true,
		option2: 'Second option value',
	});
}

function implementation(options: BigOptions) {
	options.option3.forEach(
		value => console.log(value), // TypeError: Cannot read property 'forEach' of undefined
	);
}

receiver(implementation); // Typescript allows this


```

**Expected behavior:**
Any compiler error

**Actual behavior:**
No Errors

**Comment by olegdunkan** [comment]
[See FAQ](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-function-parameters-bivariant)

**Comment by darkartur** [comment]
So by design TypeScript thinks that `(options: BigOptions) => void` is assignable to `(options: SmallOptions) => void`?

**Comment by olegdunkan** [comment]
Yes

**Comment by darkartur** [comment]
Should I close task then or it will be changed?
Can I do something to avoid runtime expection like this at future?

**Comment by olegdunkan** [comment]
@darkartur it is the question that have to be addressed to the TypeScript team, but I think they will not change this approach, search this repo for a lot of info on the topic.

**Comment by RubaXa** [comment]
@olegdunkan  what about this case?

### 1. Correct behavior
```ts
interface A {foo: boolean}
interface B extends A {bar: string}

function call(x: B)  {}

const a: A = null;
const b: B = null;

call(a);        // Error:(9, 6) TS2345: Argument of type 'A' is not assignable to parameter of type 'B'.
                   // Property 'bar' is missing in type 'A'.
call(b);
```

### 2. ????? behavior

```ts
interface A {foo: boolean}
interface B extends A {bar: string}

function call(fn: (x: B) => void)  {
}

const a = (x: A) => {};
const b = (x: B) => {};

call(a);     //            <-----                     No errors, why?
call(b);
```

**Comment by olegdunkan** [comment]
@RubaXa because `(x: A) => {}` assignable to `(x: B) => void` and vise versa, parameter `x` in `call(fn: (x: B) => void)` is bevariant.

**Comment by RubaXa** [comment]
🤕
