### ISSUE TITLE
Reexport symbols in single statement does not worked

### ISSUE THREAD

**Issue by oklas** [Microsoft/TypeScript#17186]
**TypeScript Version:**  2.4.1

**Code** worked fine and as expected, (`Connection` is exported as default):

```ts
import Connection from './Connection'
export default Connection
```

**Code** does not worked:

```ts
export default from './Connection'
```

the output:

> ```
>   ? Test suite failed to run
> 
>     ReferenceError: from is not defined
> 
>       at Object.<anonymous> (src/index.ts:1:20)
>       at Object.<anonymous> (test/index.test.ts:2:8)
>       at process._tickCallback (internal/process/next_tick.js:103:7)
> ```

**Code** does not worked too:

```ts
export * from './Connection'
```

the output:

>```
>     TypeError: _src2.default is not a constructor
> 
>       at launching (test/index.test.ts:22:12)
>       at Object.<anonymous>.beforeAll (test/index.test.ts:69:3)
>       at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)
>       at process._tickCallback (internal/process/next_tick.js:103:7)
>```

**Comment by andy-ms** [comment]
That isn't valid syntax. Running `tsc` should show you the relevant diagnostics; we will still emit *something* but as you can see it won't work at runtime.
You might be interested in https://github.com/tc39/proposal-export-ns-from and https://github.com/tc39/proposal-export-default-from .
