### ISSUE TITLE
Decorators stage 2 draft

### ISSUE THREAD

**Issue by BurtHarris** [Microsoft/TypeScript#17185]
Is there an effort underway to implement the [stage 2 draft of](https://tc39.github.io/proposal-decorators/) decorators in TypeScript?  If not is this something that might be within reason for external contributor(s) to get started on?

**Comment by kitsonk** [comment]
It is on [the roadmap](https://github.com/Microsoft/TypeScript/wiki/Roadmap#future).  I know that the TypeScript team have been very involved influencing the changes to the proposal and I believe it is fairly important to the core team to address.  Once we get the scope for 2.5, I would highly expect that it will be there, but I suspect a lot of it will be conversations with Brian Terlson (the Microsoft TC39 rep and co-champion for the proposal) on how solid the proposal is and what sort of breaking changes it is likely to incur.

**Comment by BurtHarris** [comment]
Thanks @kitsonk, I'll keep an eye on that roadmap.
