### ISSUE TITLE
Arrays can be treated as string-indexable types 

### ISSUE THREAD

**Issue by kujon** [Microsoft/TypeScript#17191]
**TypeScript Version:**  2.4.0
**Code**

```ts
const foo: { [index: string]: any } = [42];
```

**Expected behavior:**
The code above doesn't compile.

**Actual behavior:**
Typescript silently accepts such code.

**Comment by RyanCavanaugh** [comment]
You can think of it this way - *for the purposes of indexing*, `number` is a subtype of `string` due to how JavaScript works

**Comment by JRGranell** [comment]
@RyanCavanaugh - could this be addressed in strict-mode? 

In strict mode, not all JS is a valid TS (e.g. no implicit any), therefore this presents an opportunity to discourage  `const foo = {'42': 'foo'}; const bar = foo[42]` in favour of stricter typings.

Alternatively I would be interested in in other approaches or workarounds given that assigning an array to what is expected to be an object could have significant issues at run-time.

**Comment by RyanCavanaugh** [comment]
Arrays *are* objects.
