### ISSUE TITLE
Tslib helpers not imported for js files with non ES6 style modules when `importHelpers` is true

### ISSUE THREAD

**Issue by bfrost2893** [Microsoft/TypeScript#17192]
The tslib helpers that are generated to allow valid typescript to run for a specific target are not imported when using common JS modules and `importHelpers` set to true. This causes a valid typescript file to fail, as functions like `__extend` will be undefined.

**TypeScript Version:**  2.4.1 / nightly (2.5.0-dev.201xxxxx)

**Code**

```ts
class Foo {

}

class Bar extends Foo {

}

module.exports = Bar;
```
with the `tsconfig.json`

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "skipLibCheck": true,
    "module": "commonjs",
    "target": "es5",
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "moduleResolution": "node",
    "lib": [
      "dom",
      "es5",
      "scripthost",
      "es2015.iterable"
    ],
    "noEmitHelpers": true,
    "importHelpers": true
  }
}
```
generates the following code:

```js
var Foo = (function () {
    function Foo() {
    }
    return Foo;
}());
var Bar = (function (_super) {
    __extends(Bar, _super);
    function Bar() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    return Bar;
}(Foo));
module.exports = Bar;
```

However, simply switching the typescript code to use es6 style export:

```ts
class Foo {

}

class Bar extends Foo {

}

export {
    Bar
};
```

generates the expected result:

```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var tslib_1 = require("tslib");
var Foo = (function () {
    function Foo() {
    }
    return Foo;
}());
var Bar = (function (_super) {
    tslib_1.__extends(Bar, _super);
    function Bar() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    return Bar;
}(Foo));
exports.Bar = Bar;
```

**Expected behavior:**
CommonJS modules also receive the tslib helpers when `importHelpers` is set to true.

**Actual behavior:**
The tslib helpers are not imported, thus the code breaks due to `__extends` not being defined.
`ReferenceError: __extends is not defined`

**Comment by weswigham** [comment]
@bfrost2893 your file 
```ts
class Foo {

}

class Bar extends Foo {

}

module.exports = Bar;
```
is not a module, as it has no `import` or `export` statements, so it is being compiled as a global script file. A global script file does not import helpers (instead, it expects the globals to be available). Adding a `export {}` to your file will cause it to be parsed as a module and should act as expected.

**Comment by mhegazy** [comment]
chatted with @rbuckton and seems like emitted the import if `commonJsModuleIndicator` is set seems like the best option.
