### ISSUE TITLE
addition assignment behaves surprisingly with union types

### ISSUE THREAD

**Issue by rkirov** [microsoft/TypeScript#17204]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

**Code**

```ts
let x: string | number = 0;
x += ''; // ERROR(2,1): Type 'string' is not assignable to type 'number'.
```

**Expected behavior:**
Since this is ok
```ts
let x: string | number = 0;
x = x + ''; 
```
similarly (showing that this has to do with type-narrowing)

```ts
function f(x: string | number) {
  x += '';
}
```

and finally TS allows string and number additions, thus I expect the original to also be accepted by the compiler.

Generally treating `x = x + 1` and `x += 1` differently from type checking perspective is surprising, but maybe this is byproduct of other designed behaviors.

**Actual behavior:**
Error - Type 'string' is not assignable to type 'number'.

**Comment by RyanCavanaugh** [comment]
I'm not really sure if this is a bug per se or not, but it doesn't seem like something that needs time spent on it either way.
