### ISSUE TITLE
Spelling correction fixes should not be case-agnostic for two equally weighted options

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#17219]
Occurs both as part of the error and as part of the fix.

```ts
class Greeter {
    name: string;

    constructor(name: string) {
        this.name = name;
    }

    greet(otherName: string) {
        conole/**/
    }
}
```

![image](https://user-images.githubusercontent.com/972891/28234823-f87f5d84-68b8-11e7-80c0-68a708fa6438.png)

**Comment by prateekgoel** [comment]
Can I work on this issue? I would be my first PR to Typescript.
This seems much easier than other issues.

**Comment by DanielRosenwasser** [comment]
Sure! Take a stab at it. Keep in mind that changes here should be fairly local to the code around spelling suggestions.

**Comment by prateekgoel** [comment]
Thanks @DanielRosenwasser .
Just want to confirm that the file I need to edit is TypeScript/src/services/codefixes/fixSpelling.ts, right?
I need to make sure that the `suggestion` is always in lower case. So probably I can just use `toLowerCase()` function there, right?

**Comment by sandersn** [comment]
This bug is actually fixed -- present-day suggestions are filtered by meaning, so `Console` is no longer suggested for `conole`. 

Are there other bad examples that occur in real code? I'd like to see other real failures of the algorithm before making it more complex. It's intentionally simple.
