### ISSUE TITLE
Type narrowing for fields

### ISSUE THREAD

**Issue by laszlojakab** [Microsoft/TypeScript#1721]
Hi!

Type narrowing is not working (not supported?) for fields (VS2013, TypeScript 1.4). 

```typescript
class O1Cls {
    x: any;
}

class O2Cls {
    y: any;
}

interface Options {
    opt: O1Cls|O2Cls;
}

class MyClass {
    constructor(options: Options) {
        if (options.opt instanceof O1Cls) {
            console.log(options.opt.x); // Error: Property 'x' does not exists on type 'O1Cls | O2Cls'
        }

        var opt = options.opt;
        if (opt instanceof O1Cls)
        {
            console.log(opt.x); // OK
        }
    }
}
```

Will it be supported or is this a "by design" behaviour?

**Comment by GuilhermeBernal** [comment]
Fields can have getters, so `options.opt` may return different things each time it is evaluated. Not sure if it can be statically checked.

**Comment by laszlojakab** [comment]
@GuilhermeBernal: since i wrote this I've already noticed that. So probably it is not an issue.

**Comment by RyanCavanaugh** [comment]
See also #1706
