### ISSUE TITLE
Visual Studio with TS 1.4 without project on save creates ES6 and not ES3 like before

### ISSUE THREAD

**Issue by Bobris** [Microsoft/TypeScript#1722]
We trying to find how to force ES3 mode again with TS 1.4 and VS2013 on save without project.

**Comment by danquirk** [comment]
This should be in VS setting.

**Comment by mhegazy** [comment]
VS always default to the latest version of ECMAScript standard. so in 1.3 it was ES5 (accessors were allowed for instance). now that ES6 is a valid target that is the default (let and const are alllowed). 

the work to support tsconfig.json (issue#1667) should be the way to specify what configurations you want with a .ts file not belonging to a project.
