### ISSUE TITLE
Include specific file from excluded folder

### ISSUE THREAD

**Issue by rohmanhm** [Microsoft/TypeScript#17228]
**TypeScript Version:**  nightly (2.5.0-dev.201xxxxx)

**Code**

```ts
// tsconfig.json
{
  "compilerOptions": {
    "target": "es6",
    "module": "esnext",
    "moduleResolution": "node",
    "jsx": "react",
    "sourceMap": true,
    "outDir": "./dist",
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "allowSyntheticDefaultImports": true,
    "noUnusedLocals": true,
    "baseUrl": "./",
    "paths": {
      "@/*": ["./app/*"],
      "~/*": ["./*"]
    },
    "experimentalDecorators": true,
    "typeRoots": [
      "typings"
    ]
  },
  "exclude": [
    "node_modules",
    "dist",
    "server",
    "scripts",
    ".vscode"
  ],
  "include": [
    "server/i18n.ts"
  ]
}

```

**Expected behavior:**
I ignored all files from server folder except "server/i18n.ts" file.

**Actual behavior:**
It's fail, and throw an error something like this
> error TS18003: No inputs were found in config file 'pathproject/tsconfig.json'. Specified 'include' paths were '["server/i18n.ts"]' and 'exclude' paths were '["node_modules","dist","server","scripts",".vscode"]'.

**Comment by ikatyang** [comment]
Have you tried `files`?

> Files included using "include" can be filtered using the "exclude" property. However, files included explicitly **using the "files" property are always included regardless of "exclude"**. The "exclude" property defaults to excluding the node_modules, bower_components, jspm_packages and <outDir> directories when not specified. (<http://www.typescriptlang.org/docs/handbook/tsconfig-json.html#details>)

**Comment by mhegazy** [comment]
from http://www.typescriptlang.org/docs/handbook/tsconfig-json.html#details

> Files included using "include" can be **filtered** using the "exclude" property. 

and what @ikatyang said should work.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
