### ISSUE TITLE
tsserver and emacs

### ISSUE THREAD

**Issue by perveziqbal** [Microsoft/TypeScript#17229]
I am currently using emacs with tide package to write an angular 4 application. Thanks to language service, emacs/tide checks my inline templates. Unfortunately for external templates(html) emacs does nothing more display exception thrown by tsserver. I am using TypeScript  2.4.1. When I looked at TSS log, after throwing an exception, it actually returns error messages in the template.

I changed the line at 79728 in tsserver.js from 
``
    var diagnostics = selector(project, file);
``
to
``
    var diagnostics = selector(project, file) || [];
``

and emacs now correctly shows all error messages in the external template too!

**Comment by ikatyang** [comment]
Uh, what's the difference between them, it seems 100% the same thing, and it's L79721 not L79728...

**Comment by perveziqbal** [comment]
I changed the line to
``ts
    var diagnostics = selector(project, file) || [];
``
I have edited the opening post.

Looks like selector(...) is returning undefined. And I get map not defined on undefined exception.

**Comment by ikatyang** [comment]
Indeed, TS itself does not enable the `strictNullChecks`, so there are always some `undefined`-related issues.

**Comment by perveziqbal** [comment]
I see that, typescript 2.4.2 released and the problem still exists for me and perhaps many angular users using emacs. Fix  looks really simple. Just change line L79743 to
`
ts var diagnostics = selector(project, file) || [];
`
Using [] list if selector(...) returns null.

Can this be fixed any time soon?

**Comment by ikatyang** [comment]
Can you give a try with typescript@next? since this kind of issue will usually be considered in next minor release (see milestone).

If this issue still reproduce in typescript@next, you may have to consider sending a PR directly or somehow ping them, since this issue may be overlooked.

**Comment by DanielRosenwasser** [comment]
Nathan's the only one on our team who uses tide, but I'm curious - VS Code manages to operate on templates correctly. Why do you believe this is an issue in TSServer rather than tide itself?

**Comment by ananthakumaran** [comment]
```

**Comment by sheetalkamat** [comment]
can you check if this still repros. If it repros can you please share your tsserver log to see whats going on. Thank you.

**Comment by rtm** [comment]
@perveziqbal  

> Thanks to language service, emacs/tide checks my inline templates. 

How did you get it to do that? How can tide check Angular template syntax?

**Comment by wesselvdv** [comment]
@rtm Check this repo for instructions:

https://github.com/perveziqbal/angular-tide-demo

As for this error, it is still occurring. What can I provide and how?

**Comment by sandersn** [comment]
@wesselvdv instructions for tracing the log to a file are here: 
https://github.com/ananthakumaran/tide#debugging

**Comment by sheetalkamat** [comment]
I think the issue lies in https://github.com/angular/angular/blob/master/packages/language-service/src/ts_plugin.ts#L77 where it returns undefined. The definition for getSyntacticDiagnostics expects array as return value. https://github.com/Microsoft/TypeScript/blob/master/src/services/types.ts#L254

**Comment by sheetalkamat** [comment]
Closing this since this isn't issue with typescript repository.
