### ISSUE TITLE
String escape conversion can create accidental octal literal

### ISSUE THREAD

**Issue by alangpierce** [Microsoft/TypeScript#17226]
**TypeScript Version:**  2.4.1

**Code**

```ts
"use strict"
console.log(`\x001`);
```

[Playground link](https://www.typescriptlang.org/play/index.html#src=%22use%20strict%22%0D%0Aconsole.log(%60%5Cx001%60)%3B)

**Expected behavior:**

Produces code that prints a null character followed by 1.

**Actual behavior:**

Produces this code:

```js
"use strict";
console.log("\01");
```

This crashes because `\01` is an octal literal, which isn't allowed in strict mode.

Note that this TypeScript code fails in a similar way:
```
console.log(`\u00001`);
```

**Context:**

This came up when converting the [decaffeinate](https://github.com/decaffeinate/decaffeinate) test suite to TypeScript, and the test case was based on a test from the CoffeeScript test suite. The CoffeeScript test suite has lots of edge cases like this, so I don't necessarily think this bug is likely to come up in real production code, but still would be good to fix. I was able to work around the issue ([diff](https://github.com/decaffeinate/decaffeinate/commit/7d25fd5b5d9323aa120e847e9857847a33061e5f#diff-52d3864ce1e85dde54c8275a6e3e4d64)), so it's not blocking me, but CoffeeScript and Babel handle this sort of thing, so would be good if TypeScript did as well.

**Comment by DanielRosenwasser** [comment]
Sorry for the delay, thanks for reporting!
