### ISSUE TITLE
Inference for mapped types 

### ISSUE THREAD

**Issue by olegdunkan** [microsoft/TypeScript#17232]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

**Code**

```ts
// A *self-contained* demonstration of the problem follows...


type A<T> = {[K in keyof T]: A<T[K]> | B<T[K]>};
type B<T> = {
    x: T
};

var obj = {
    a: {
        a: { x: 1 },
        b: { x: "" }
    },
    b: {
        a: {
            a: { x: 1 },
            b: { x: true },
            c: { x: "we are here"}            
        },
        b: { x: 3 },
        c: { x: "" }
    }
}


declare function f<T>(v: A<T>): T;


if (f(obj).b.a.c == "we are here") {
    //perfectly works
} 


type AL<T> = {[K in ("a" | "b") & keyof T]: AL<T[K]> | B<T[K]>};


declare function fL<T>(v: AL<T>): T;

var objL = {
    a: {
        a: { x: 1 },
        b: { x: "" }
    },
    b: {
        a: { x: 3 },
        b: {
            a: { x: 1 },
            b: { x: "" }            
        }
    }
}

var x: AL<typeof objL> = objL; //ok


fL(obj).????? //doesn't work

```
I expected it to be working.
Is it design limitations?

**Comment by DanielRosenwasser** [comment]
It's not clear that it should work -  two intersections types of unions don't always produce the intersection of possible types in each union. In other words, `("a" | "b") & ("a" | "b" | "c")` is not `"a" | "b"`, but is instead `"a" | "b" | ("a" & "b") | ("a" & "c") | ("b" & "a") | ("b" & "c")`.

What exactly do you want to express here?

**Comment by olegdunkan** [comment]
When I write `("a" | "b") & keyof T` I try to say to the compiler that if you meet property with name `a` or `b` in `T` then follow the production `AL<T[K]> | B<T[K]>` if not then do nothing. 

Next example shows us that the compiler maps properties with name `a` and `b` only. 
```ts
type M<T> = {[K in ("a" | "b") & keyof T]: { x: T[K] } };
var v: M<{ a: string, b: number, c: boolean }>; //M<T> is map for K in set of {"a","b"} to {x:T[K]}  

v.a.x.charAt;//ok
v.b.x.toExponential;//ok
v.c//error 
```
Thus I want  *tsc* to do the same inference as in the first case (`A<T>` in the first issue's example above) but for only limited property's names.
