### ISSUE TITLE
JSDoc: Support `@readonly` tag

### ISSUE THREAD

**Issue by andy-ms** [microsoft/TypeScript#17233]
**TypeScript Version:**  nightly (2.5.0-dev.20170712)

**Code**

```ts
class C {
	constructor() {
		/**
		 * @readonly
		 * @type {number}
		 */
		this.x = 0;
	}

	m() {
		this.x = "1"; // Error
		this.x = 1; // No error
	}
}
```

**Expected behavior:**

Both lines in `m` are errors.

**Actual behavior:**

No error when trying to write to `@readonly` property.

**Comment by niedzielski** [comment]
This would be awesome! There's already support for `Readonly` and `readonly` in JSDoc closure syntax. E.g.:

```ts
/** 
 * @typedef {Readonly<{
 *   foo: ReadonlyArray<Foo>
 *   bar: number
 * }>} Baz
 */
```
```ts
/**
 * @typedef {{
 *   readonly foo: ReadonlyArray<Foo>
 *   readonly bar: number
 * }} Baz
 */
```

Both of the above examples work as expected. However, resolving this ticket would enable readonly support for member properties too:

```ts
/**
 * @typedef {Object} Baz
 * @prop {ReadonlyArray<Foo>} foo This syntax supports comments.
 * @prop {number} bar But there's no support for marking properties as @readonly.
 */
```
