### ISSUE TITLE
Problem with /* */

### ISSUE THREAD

**Issue by edvinv** [Microsoft/TypeScript#1725]
There is a bug (TypeScript 1.4.1) in js code generation when new line is missing after end comment.

To reproduce create new ts project add foo.ts:
```typescript
/*
class Foo {
    foo() {
    }
}	*/
```
The generated js is:
```typescript
/*
class Foo {
    foo() {
    }
/*
class Foo {
    foo() {
    }
 
//# sourceMappingURL=foo.js.map
```
If there is new line after */ it works ok.

**Comment by Arnavion** [comment]
Duplicate of #1714

**Comment by RyanCavanaugh** [comment]
Workaround is to not have the `/` be the last character in the file
