### ISSUE TITLE
Underscore arrow function error highlighting

### ISSUE THREAD

**Issue by mterczynski** [Microsoft/TypeScript#17263]
**TypeScript Version:**  2.4.1

**Code**

    const test =()=>3;
    console.log(test);
    console.log(test());

    const test2 =_=>3;
    console.log(test2);
    console.log(test2());

**Expected behavior:**

No error highlighting

**Actual behavior:**
![image](https://user-images.githubusercontent.com/27309340/28318819-6840bcb0-6bcc-11e7-810f-8c3ae289be7b.png)

**Comment by ikatyang** [comment]
You have to mark it as optional parameter, otherwise it'll be considered required parameter.

```diff
const test =()=>3;
console.log(test);
console.log(test());

-const test2 =_=>3;
+const test2 =(_?)=>3;
console.log(test2);
console.log(test2());
```

**Comment by mterczynski** [comment]
Wow, I thought that underscore was some special syntax of ES6, and it is in fact just normal argument.
