### ISSUE TITLE
TS doesn't check types in implementation of interface

### ISSUE THREAD

**Issue by maxkorz** [Microsoft/TypeScript#17270]
Sorry if such issue already exists.

**TypeScript Version:**  2.4.1

**TypeScript Config:**
```json
{
  "compilerOptions": {
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es2015", "dom"],
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "strict": true,
    "suppressImplicitAnyIndexErrors": true,
    "target": "es5",
    "typeRoots" : ["node_modules/@types"]
  },
  "compileOnSave": true,
  "exclude": [
    "node_modules/*"
  ]
}
```

**Code**

```ts
type element = {
  id: number;
  name: string;
};

interface IComponent {
  element: element;

  add(): void;
  edit(el: element): void;
  delete(el: element): void;
}

class Component implements IComponent {
  element: any;
  add(): any {}
  edit(el: any): any { }
  delete(el): any { }
}
```

**Expected behavior:**
I expect to see such errors as:
```
Class 'Component' incorrectly implements interface 'IComponent'.
  Types of property 'add' are incompatible.
    Type '() => any' is not assignable to type '() => void'.
  Types of property 'edit' are incompatible.
    Type '(el: any) => any' is not assignable to type '(el: element) => void'.
```
**Actual behavior:**
This code throws one error `Parameter 'el' implicitly has an 'any' type.` and that's all.

I believe TS should guess and check type of arguments and type of returning value

by the way, this code:
```ts
class Component implements IComponent {
  element: any;
  add(el: any): any {}
  edit(el: any): any { }
  delete(el: any): any { }
}
```
throws error
```
Class 'Component' incorrectly implements interface 'IComponent'.
  Types of property 'add' are incompatible.
    Type '(el: any) => any' is not assignable to type '() => void'.
```
so, TypesScript validates the number of arguments, but doesn't check the type of arguments.

**Comment by andy-ms** [comment]
The `any` type is magic -- it's assignable to anything, and anything is assignable to it. It's basically a way of turning type-checking off. If you want stronger type checking, avoid using `any`.

**Comment by maxkorz** [comment]
thanks

**Comment by maxkorz** [comment]
@andy-ms quick question. Same code.
```ts
type element = {
  id: number;
  name: string;
};

interface IComponent {
  element: element;

  add(): void;
  edit(el: element): void;
}

class Component implements IComponent {
  element: any;
  add(): any {}
  edit(el): any { }
}
```
Why do I get error `Parameter 'el' implicitly has an 'any' type.`? Why TS can't guess the type based on interface?

**Comment by andy-ms** [comment]
That is unfortunate; I can't find the issue, but I know we've discussed that in the past and decided it was a design limitation.

**Comment by maxkorz** [comment]
That's sad. This limitation makes such usage of interface useless for small classes. I do not see the point in making interfaces for classes where code can fit in one screen... Ok, thanks anyway!

**Comment by RyanCavanaugh** [comment]
See also https://github.com/Microsoft/TypeScript/issues/2000#issuecomment-245964251
