### ISSUE TITLE
Compile outputs js files correctly but shows error `TS2688 ` with `typeRoots` specified.

### ISSUE THREAD

**Issue by shunia** [Microsoft/TypeScript#17284]
**TypeScript Version:**  2.4.1

**Code**

Porject structure: 
```
 proj
  -src
    Index.ts
  -libs
    -a
      a.d.ts
    -b
      b.d.ts
    -modules
      -c
        -c.d.ts
  -node_modules
    -d
      d.d.ts
```

All definition files starts with: `declare namespace a` or `declare module b`.

tsconfig.json:
```json
{
    "compilerOptions": {
        "target": "es5",
        "typeRoots": [
            "node_modules", 
            "libs"
        ]
    }, 
    "include": [
        "src"
    ]
}
```

**Expected behavior:**
When running `tsc -p .`, everything is right without errors.

**Actual behavior:**
When running `tsc -p .`, `Index.js` shows, but errors occur:
```
error TS2688: Cannot find type definition file for 'a'.
error TS2688: Cannot find type definition file for 'b'.
error TS2688: Cannot find type definition file for 'modules'.
```
Definition file inside `node_modules` not showing errors.

**Comment by fanzeyi** [comment]
I run into a similar situation that `typeRoots` configuration in `tsconfig.json` is not used either.

**Comment by mhegazy** [comment]
typeRoots points to a folder that contain module declarations. these have to be of the form of a node pacakge, i.e. either they have a file called `a.d.ts` or `a\index.d.ts` or `a\package.json` that has a reference to the declaration file.

use `tsc --traceResolution` to see what the compiler is doing to find these files. 

Also you can find more information at https://www.typescriptlang.org/docs/handbook/module-resolution.html

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
