### ISSUE TITLE
Infer minimal types for function arguments required for the function to work

### ISSUE THREAD

**Issue by Vana-tur** [Microsoft/TypeScript#17280]
**TypeScript Version:**  2.4.0 

**Code**
```ts
function f(x, y) :number {
    return x.name1 + y.name1
}
```

**Expected behavior:**

type of `f` is inferred as `function f(x: {name1:number}, y: {name1:number}): number`
since other types wouldn't pass the typechecker.

**Actual behavior:**

Argument types are not inferred and the type of `f` is `function f(x: any, y: any): number`

**Comment by RyanCavanaugh** [comment]
Reverse inference like this would basically be a complete rewrite level of change for TypeScript.

**Comment by Vana-tur** [comment]
Is implementation complexity the only argument against implementing this, or are there other issues too?
