### ISSUE TITLE
forceConsistentCasingInFileNames checks shouldn't apply to other packages

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#17286]
Should allow to have different rules in other packages.

**TypeScript Version:**  2.4.0

**Code**

https://github.com/falsandtru/typed-dom

**Expected behavior:**

no error.

**Actual behavior:**

```
Error TS1149: File name '.../typed-dom/node_modules/spica/monad/sequence/member/instance/takeWhile.ts' differs from already included file name 'node_modules/spica/monad/sequence/member/instance/takewhile.ts' only in casing.
...
```

**Comment by mhegazy** [comment]
all compiler checks do not differentiate between local and imported .d.ts. for instance `--noImplicitAny`, `--noImplicitThis`, `--noStricitGenericChecks`, etc..
For @types package we make sure new packages all have these flags set up on the definition.
