### ISSUE TITLE
Feature request: warn on unused result

### ISSUE THREAD

**Issue by krisselden** [Microsoft/TypeScript#17282]
It can be easy to forget an `await` for a method returning `Promise<void>` and have your code appear to work.

I would be nice to have something like `must_use` in Rust or the `__attribute__((warn_unused_result))` in C or `@warn_unused_result` in Swift.

**Comment by krisselden** [comment]
This is my same struggle https://github.com/Microsoft/TypeScript/issues/13376

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Comment by dannycochran** [comment]
Can this be re-opened, I think having a "warn_on_unused" annotation is actually different than #13376.

There are plenty of non-async cases where you'd want to be warned about an unused result, for instance with redux.

```javascript
const someActionCreator = (payload: string) => ({
  type: SOME_ACTION,
  payload
});

const someAction = () => (dispatch) => {
  // Compute the payload...
  const payload = 'foo.bar';
  // The correct way:
  // dispatch(someActionCreator(payload));

  // What can easily happen:
  someActionCreator(payload);
};

const onTouchTarget = () => this.props.dispatch(someAction());
```

This could be solved a number of ways, but a decorator seems pretty natural:

```javascript
@warn_unused_result
const someActionCreator = (payload: string):  => ({
  type: SOME_ACTION,
  payload
});
```

**Comment by krisselden** [comment]
this was mistakenly marked as a duplicate of #13376 that was the reason I had the motivated me opening this, but this feature is used in other languages for many reasons and is more generalized than #13376

**Comment by RyanCavanaugh** [comment]
There's another issue I can't find at the moment that covers non-discardable function return values

**Comment by mhegazy** [comment]
tracked now by https://github.com/Microsoft/TypeScript/issues/8584
