### ISSUE TITLE
undefined for class property

### ISSUE THREAD

**Issue by chaoxihailing** [Microsoft/TypeScript#17289]
**TypeScript Version:**  2.4.1

**Code**

      public async loginUser(mobile: string, password: string): Promise<number> {
        debugger
        logger.info("Preparing to login user");
        let user: User = await this.getUser({ mobile: mobile });
        if (!user) {
            throw new BizError(ErrorInfo.USER_NOT_EXIST);
        }
        let pwdResult = user.password;
        if (!pwdResult) {
            throw new Error("fail");
        }
        logger.info("Successfully login user");
        return user.id;
    }

I write class User，and want to get user data from database， actually，i get real user data from database，but ，I want to give user.password property data to pwdResult, however, this is undefined  for user.password. How it happend?

**Comment by ikatyang** [comment]
Can you share a self-contained demo? There is no enough information to understand what's going on.

**Comment by chaoxihailing** [comment]
This is my error， I in db sequelize exclude password，so it can’t get password value
