### ISSUE TITLE
Why tsc compiles export default xyz to xyz.default?

### ISSUE THREAD

**Issue by NeekSandhu** [Microsoft/TypeScript#17283]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

**Code**

Given `foo.ts`
```ts
function foo() { }
export default foo;
```
transpiles to `foo.js` as

```javascript
function foo() { }
exports.default = foo
```
Why is that? Since consumers of my lib are used to

```javascript
import foo from 'foo'
foo()
```

But now they need to

```javascript
import foo from 'foo'
foo.default()
```

**Expected behavior:**
Shouldn't it transpile to

```javascript
function foo() { }
exports = foo
```
Similar to what we see around most libs.

**Comment by MrKou47** [comment]
It's typescript design.

**Comment by NeekSandhu** [comment]
Some background would be appreciated like what was TS team thinking when they designed this?
As this feels like going against a well known pattern/convention.

**Comment by RyanCavanaugh** [comment]
You have a default export and a default import here. If that's not working (`foo()` rather than `foo.default()`), then some other tool in your build/run pipeline is broken. TypeScript definitely emits the correct code for this.

**Comment by NeekSandhu** [comment]
Thanks I figured it out, the issue started out of bad `d.ts` file.
