### ISSUE TITLE
Spec inconsistency for type aliases

### ISSUE THREAD

**Issue by impworks** [microsoft/TypeScript#17287]
[Specification, chapter 3.10](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#3.10):

> An interface can be named in an extends or implements clause, but a type alias for an object type literal cannot.

This contradicts the actual behaviour seen in current Playground:

* Interface cannot be used in the `extends` clause
* Type alias can be used in the `implements` clause as well as an interface

**Comment by olegdunkan** [comment]
> Interface cannot be used in the extends clause

It can
```ts
interface A { x:number;}
interface B  extends A { y:number;}
```` 
> Type alias can be used in the implements clause as well as an interface
[Now it is true.](https://github.com/Microsoft/TypeScript/pull/13604)

Spec now is in stale state.

**Comment by impworks** [comment]
You're right. I meant the `extends` clause for a `class` definition.
The following line is also misleading:

> since interface types offer more capabilities they are generally preferred to type aliases

* The `type` syntax supports mapped types, while interfaces do not
* There's no way to emulate `A | B` using interfaces (or is there?)

> Spec now is in stale state.

So is the spec going to be updated, or it is abandoned for the sake of faster development?

**Comment by ikatyang** [comment]
> So is the spec going to be updated, or it is abandoned for the sake of faster development?

See https://github.com/Microsoft/TypeScript/pull/17215#issue-243137359

**Comment by olegdunkan** [comment]
> since interface types offer more capabilities they are generally preferred to type aliases


Type alias is like named references to any kind of type (primitive types, object types, union types, intersection types, mapped types), interface is like named reference to object type. You can't extend (in the sense of adding extensions to the existed class) class with an alias but with an interface can. Declaration merging is working for interfaces (class and interface, interface and interface) and enums, namespaces.   

```ts
import {A} from "./a"

declare module './i' {
  interface A {
    f2():void;
  }
}

A.prototype.fn2 = function() {

};
```
By the way, spec doesn't contain that.

**Comment by DanielRosenwasser** [comment]
I believe this was a change we made where if a type reference resolves to an object type, then you can use it in an implements clause.

Thanks for reporting!

**Comment by RyanCavanaugh** [comment]
The spec is now an "archived" artifact and we won't be tracking defects against it anymore.
