### ISSUE TITLE
sort member is missing for ReadonlyArray<T>

### ISSUE THREAD

**Issue by TobiasSekan** [Microsoft/TypeScript#17291]
**TypeScript Version:**  2.4.0

**Code**
```TypeScript
const testArray: ReadonlyArray<string>;
testArray = new Array<string>();
const newArray = testArray.sort();
```

**Expected behavior:**
Return a new resorted array

**Actual behavior:**
ReadOnlyArray have no **sort** member

**Comment by ikatyang** [comment]
`Array#sort()` will affect original array, it is not readonly.

**Comment by olegdunkan** [comment]
First issue is that you can't assign to `const` variable except in a declaration.  
`ReadonlyArray` is immutable  you can't change it (apply push, pop, sort and etc methods).
`var testArray: ReadonlyArray<string>;` - you declare that array can't change itself as whole entity

**Comment by TobiasSekan** [comment]
Sorry guys, that was my fault, I don't know that **sort** return **this**
I was spoiled from C# **.OrderBy** extension function.
Have a nice day

@olegdunkan 
you are right, that should be **let**
