### ISSUE TITLE
Overload type checking bug in JSX

### ISSUE THREAD

**Issue by alshain** [Microsoft/TypeScript#17295]
**TypeScript Version:**  2.4.1

**Code**
Unfortunately, I haven't yet been able to create a small reproducible example. Of course, I can't post the entire company project here in order to reproduce the bug.

Instead, I'm going to sketch out my code and my reasoning to explain, why I think there is a bug lurking somewhere, also to gather advice on how I could create an example to reproduce it in a small self-contained example.

```ts
1. export function ReferenceField<V, T, R>(props: StringReferenceFieldProps<string, T, R>): JSX.Element;
2. export function ReferenceField<V, T, R>(props: ReferenceFieldPropsWithRest<V, T, R>): JSX.Element;
3. export function ReferenceField<V, T, R>(props: ReferenceFieldProps<V, T, R>) {
```

The general idea is, that I've got React type-safe react components. In (2), an additional parameter property `parse` is expected of type `(v: V) => string`. So if you provide some component with string storage, it doesn't need to parse and won't demand a parser. Otherwise, it will demand a parser.

```ts

I call it with props where `V` is (would be) inferred to be `number` and I provide a  `(number) => string` parser.

```
**Expected behavior:**

* I expect my code to type check.
* If it doesn't I expect TypeScript to tell me which overload failed.

From my experiments, it seems that if the first overload signature doesn't match, it will try the second, until the last (2), and report errors *only* with respect to the last. It might be better to output an error message for each mis-match instead.

**Actual behavior:**

I get an error message:

```
(313,49): error TS2322: Type '{ for: MappedDataType<number, SourceDataType>; parser: (s: string) => { v: undefined; error: boolean...' is not assignable to type 'IntrinsicAttributes & ReferenceFieldPropsWithRest<number, SourceDataType, FetchResult>'.
  Type '{ for: MappedDataType<number, SourceDataType>; parser: (s: string) => { v: undefined; error: boolean...' is not assignable to type 'ReferenceFieldPropsWithRest<number, SourceDataType, FetchResult>'.
    Types of property 'onChangeField' are incompatible.
      Type '(v: number, field: MappedDataType<string, SourceDataType>, oldV: string | undefined) => void' is not assignable to type 'FieldChangeEventHandler<number, SourceDataType> | undefined'.
        Type '(v: number, field: MappedDataType<string, SourceDataType>, oldV: string | undefined) => void' is not assignable to type 'FieldChangeEventHandler<number, SourceDataType>'.
          Types of parameters 'field' and 'field' are incompatible.
            Type 'MappedDataType<number, SourceDataType>' is not assignable to type 'MappedDataType<string, SourceDataType>'.
              Type 'number' is not assignable to type 'string'.


```

Commenting line (1) type checking works just fine. How can this be? Shouldn't choose the overload (2) in the case where (1) is not commented?

Investigating further, if I change the `string` type parameter in (1) to something else, it will reflect this in the error message. Important is, that neither in (2) nor in my calling code does `string` appear anywhere. Why then does the first overload influence the error message?

Even more interestingly, if I comment (2), the code must not compile. It doesn't, however, I get a completely different error message.

This suggests that TS does not fail my code against (1) if both are un-commented.

Also, swapping (1) and (2) makes the code compile. However, this is pointless since then the more general version comes first which leads to unhelpful error messages. (i.e. forget to provide a `parser`, and you're told to pass in stuff of type `string`, not that `parser` is missing)

**Comment by alshain** [comment]
I've found that this only happens with JSX syntax. If I call it without JSX syntax, the overload resolution appears to work fine.

**Comment by mhegazy** [comment]
I will need some more context to be able to comment.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
