### ISSUE TITLE
VS 2017 Intellisense does not use file order and gives false TS2449 errors

### ISSUE THREAD

**Issue by hoegge** [Microsoft/TypeScript#17290]
**TypeScript Version:**  2.4.1
**Visual studio: 15.3 preview 4 or 15.2 **

When something defined in one .ts file in a project is used in a second .ts file, it only works, if the first .ts file is compiled before second. That can normally be solved by ordering the compilation 1) editing the .csproj file or 2) specifying the files in the correct order in the tsconfig.json file.

Intellisense does not seem to respect that order, which means it gives a lot of false alarms:

`TS2449 Class "xxx" used before its declaration`

Is the VS 2017 typescript intellisense also part of the typescript project?

**Comment by mhegazy** [comment]
Please provide a self-contained reproduction of the issue for us to investigate. 

You can also find more information about controlling the order of your files in https://github.com/Microsoft/TypeScript/wiki/FAQ#how-do-i-control-file-ordering-in-combined-output---out-

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
