### ISSUE TITLE
VS 2015 and 2017 intellisense for typing not working after version TS 2.4 

### ISSUE THREAD

**Issue by ltlombardi** [Microsoft/TypeScript#17300]
**TypeScript Version:**  2.4.1.0
Visual Studio 2015 Community. Extensions installed, in the attached txt info obtained from help->about
[vs2015 info.txt](https://github.com/Microsoft/TypeScript/files/1159955/vs2015.info.txt)

Worked fine in version 2.3.1.0. Stopped working after typescript update. Reproduced the bug in my colleague computer with Visual Studio 2015 enterprise and Visual Studio 2017 Enterprise.

**Expected behavior:**
See pic 1 
![1](https://user-images.githubusercontent.com/898124/28381435-39ba19ac-6c91-11e7-8dd1-12be0f2188ac.png)

**Actual behavior:**
See pic 2
![2](https://user-images.githubusercontent.com/898124/28381440-3c202cb8-6c91-11e7-8499-e8cc5394c9d4.png)

strangely, it still works, some places, like in this enum in pic 3
![3](https://user-images.githubusercontent.com/898124/28381446-3f43d3b8-6c91-11e7-97ed-ade46015a45a.png)

**Comment by mhegazy** [comment]
If this behavior still persists, please file this using the [VS 2017 Report a problem tool](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017). the tool will capture enough information to allow us to understand what was going on in your system at the time you experience the issue.

**Comment by ltlombardi** [comment]
Ok, I'll do that

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
