### ISSUE TITLE
Promise.then inference bug

### ISSUE THREAD

**Issue by sodiumjoe** [microsoft/TypeScript#17315]
**TypeScript Version:**  2.4.1

**Code**

[typescript playground link](http://www.typescriptlang.org/play/#src=const%20promise%20%3D%20Promise.resolve(true)%3B%0D%0A%0D%0Aconst%20bar%20%3D%20()%20%3A%20Promise%3Cstring%3E%20%3D%3E%20promise.then((condition)%20%3D%3E%20%7B%0D%0A%09if%20(condition)%20%7B%0D%0A%09%09return%20'foo'%3B%0D%0A%09%7D%0D%0A%09return%20Promise.reject('bar')%3B%0D%0A%7D)%3B%0D%0A)
```ts
const promise = Promise.resolve(true);

const bar = () : Promise<string> => promise.then((condition) => {
	if (condition) {
		return 'foo';
	}
	return Promise.reject('bar');
});
```

```bash
tsc --target es6
```

**Expected behavior:**
Should compile.

**Actual behavior:**
```bash
src/foo.ts(3,50): error TS2345: Argument of type '(condition: boolean) => Promise<never> | "foo"' is not assignable to parameter of type '(value: boolean) => PromiseLike<never>'.
  Type 'Promise<never> | "foo"' is not assignable to type 'PromiseLike<never>'.
    Type '"foo"' is not assignable to type 'PromiseLike<never>'.
```

**Comment by MrKou47** [comment]
i guess this error because of the code `const promise = Promise.resolve(true);`. If you add type `any` to `promise` it will be compiled.

**Comment by sodiumjoe** [comment]
@MrKou47 thanks for the response. You're right, that does make the code compile, but it seems like my original example should also work, since [Promise.reject is a valid es6 method on the Promise constructor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/reject).

**Comment by MrKou47** [comment]
```ts
// lib.es6.d.ts
PromiseConstructor {
    // ... some code
    /**
     * Creates a new rejected promise for the provided reason.
     * @param reason The reason the promise was rejected.
     * @returns A new rejected Promise.
     */
    reject(reason: any): Promise<never>;
    // ...some code 
    resolve<T>(value: T | PromiseLike<T>): Promise<T>;
}
```
As you can see, `Promise.reject(xxx)` will return a `Promise<never>`. But the function `bar` which you declared want to return a `Promise<string>`.  

And:
>The never type is a subtype of, and assignable to, every type; however, no type is a subtype of, or assignable to, never (except never itself). Even any isn’t assignable to never.

If you use assert, The code will run successful too.
```ts
const promise = Promise.resolve(true);

const bar = () : Promise<string> => promise.then((condition) => {
	if (condition) {
		return 'foo';
	}
	return <Promise<string>>Promise.reject('bar');
});
```
I guess the answer is this

**Comment by sodiumjoe** [comment]
Thanks for your answer, that makes sense, but it seems like `Promise<never>` is not a correct or useful return type for `Promise.reject`.

**Comment by svieira** [comment]
Here, for what it's worth is what I came up with - you could definitely use this instead of the default one in lib.es6.d (or feel free to create a PR with it or a better version):

```js
abstract class Promisish<T, E = Error> {
    static reject<T = never, E = Error>(value: E): Promisish<T, E> {
        return {} as Promisish<T, E>
    }
    static resolve<T, E = Error>(value: T): Promisish<T, E> {
        return {} as Promisish<T, E>
    }
    abstract then<R, E2 = E>(f: (r: T) => R): Promisish<R, E>
    abstract catch<R, E2 = E>(f: (e: E) => R): Promisish<T | R, E2>
    abstract finally<E2 = E>(f: () => never): Promisish<T, E2>
}
```

**Comment by phorsuedzie** [comment]
Looks as if a mix of promise and non-promise return values confuse typescript ([playground](https://www.typescriptlang.org/play/index.html#src=interface%20A%20%7B%0A%20%20%20%20isA%3A%20true%3B%0A%7D%0Ainterface%20B%20%7B%0A%20%20%20%20isA%3A%20false%3B%0A%7D%0A%0Afunction%20x()%3A%20Promise%3CA%20%7C%20B%3E%20%7B%0A%20%20%20%20return%20Promise.resolve(true).then(wantA%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20if%20(wantA)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20%7B%20isA%3A%20true%20as%20true%7D%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20return%20Promise.resolve(undefined).then(%0A%20%20%20%20%20%20%20%20%20%20%20%20()%20%3D%3E%20(%7B%20isA%3A%20false%20as%20false%20%7D)%3B%0A%20%20%20%20%20%20%20%20)%0A%20%20%20%20%7D)%3B%20%0A%7D)):

```
interface A {
    isA: true;
}
interface B {
    isA: false;
}

function x(): Promise<A | B> {
    return Promise.resolve(true).then(wantA => { // <= Error here
        if (wantA) {
            return { isA: true as true};
        }
        return Promise.resolve().then(
            () => ({ isA: false as false });
        )
    }); 
}
```

```
Argument of type '(wantA: boolean) => Promise<{ isA: false; }> | { isA: true; }' is not assignable to parameter of type '(value: boolean) => { isA: false; } | PromiseLike<{ isA: false; }>'.
  Type 'Promise<{ isA: false; }> | { isA: true; }' is not assignable to type '{ isA: false; } | PromiseLike<{ isA: false; }>'.
    Type '{ isA: true; }' is not assignable to type '{ isA: false; } | PromiseLike<{ isA: false; }>'.
      Type '{ isA: true; }' is not assignable to type 'PromiseLike<{ isA: false; }>'.
        Property 'then' is missing in type '{ isA: true; }'.
```

**Comment by RyanCavanaugh** [comment]
Seems to be fixed now
