### ISSUE TITLE
Fields of class generic type constraint are not assignable anything but null or undefined without assertion

### ISSUE THREAD

**Issue by sgwatgit** [Microsoft/TypeScript#17317]
**TypeScript Version:**  2.4.1

**Code**
[Typescript Playground](http://www.typescriptlang.org/play/#src=interface%20State%20%7B%0D%0A%20%20%20%20isReady%3A%20false%3B%0D%0A%7D%0D%0A%0D%0A%2F%2F%20Does%20not%20work%0D%0Aclass%20Base1%3CT%20extends%20State%3E%20%7B%0D%0A%20%20%20%20myState%3A%20Readonly%3CT%3E%20%3D%20%7B%20isReady%3A%20false%20%7D%3B%0D%0A%20%20%20%20myOtherState%3A%20T%20%3D%20%7B%20isReady%3A%20false%20%7D%3B%0D%0A%20%20%20%20mySecondState%3A%20T%20%3D%20null%3B%20%2F%2F%20Sure!%0D%0A%20%20%20%20theThirdEstate%3A%20T%20%3D%20undefined%20%2F%2F%20Ok!%0D%0A%0D%0A%20%20%20%20setState(state%3A%20Partial%3CT%3E)%20%7B%0D%0A%20%20%20%20%20%20%20%20this.myState%20%3D%20Object.assign(this.myState%2C%20state)%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20update()%20%7B%0D%0A%20%20%20%20%20%20%20%20this.setState(%7B%20isReady%3A%20false%20%7D)%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0A%2F%2F%20Works%20with%20'as%20T'%0D%0Aclass%20Base2%3CT%20extends%20State%3E%20%7B%0D%0A%20%20%20%20myState%3A%20Readonly%3CT%3E%20%3D%20%7B%20isReady%3A%20false%20%7D%20as%20T%3B%0D%0A%20%20%20%20myOtherState%3A%20T%20%3D%20%7B%20isReady%3A%20false%20%7D%20as%20T%3B%0D%0A%0D%0A%20%20%20%20setState(state%3A%20Partial%3CT%3E)%20%7B%0D%0A%20%20%20%20%20%20%20%20this.myState%20%3D%20Object.assign(this.myState%2C%20state)%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20update()%20%7B%0D%0A%20%20%20%20%20%20%20%20this.setState(%7B%20isReady%3A%20false%20%7D%20as%20T)%3B%0D%0A%20%20%20%20%7D%0D%0A%7D)
```ts
interface State {
    isReady: false;
}

// Does not work
class Base1<T extends State> {
    myState: Readonly<T> = { isReady: false }; // Nope
    myOtherState: T = { isReady: false }; // Nope
    mySecondState: T = null; // Sure!
    theThirdEstate: T = undefined // Ok!

    setState(state: Partial<T>) {
        this.myState = Object.assign(this.myState, state);
    }

    update() {
        this.setState({ isReady: false }); // Nope
    }
}

// Works with 'as T'
class Base2<T extends State> {
    myState: Readonly<T> = { isReady: false } as T;
    myOtherState: T = { isReady: false } as T;

    setState(state: Partial<T>) {
        this.myState = Object.assign(this.myState, state);
    }

    update() {
        this.setState({ isReady: false } as T);
    }
}
```

**Expected behavior:**
The constraint of T as having a property `isReady` is flowed through and `{ isReady: false }` is considered to have the same shape as `T` and is valid for `T`, `Partial<T>` or `Readonly<T>` without having use the explicit type assertion.

**Actual behavior:**
Manual type assertion is required but then compiles. Null and undefined are the only valid values to assign these class fields.

I suppose I could also replace all references to `T` outside of the generic constraint with `State` but that's no fun.

**Comment by ikatyang** [comment]
See https://github.com/Microsoft/TypeScript/issues/16985#issuecomment-316072227

And if you enable the `--strictNullChecks` option, you'll see errors on `null` and `undefined`.

**Comment by sgwatgit** [comment]
Thanks for the heads up - wouldn't have found that issue myself. I'll follow along there - this issue can be closed if needed.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
