### ISSUE TITLE
tsc compiler command switch to override variable value

### ISSUE THREAD

**Issue by faisalloe** [Microsoft/TypeScript#17328]
I want to pass command line switch to tsc compiler like enviornment.production = true to override value in .js file. 

do we have support for this ?
```
export const enviornment = {
  production:false
}
if(this.enviornment.production){
enableProdMode();
}
platformBrowserDynamic().bootstrapMOdule(AppModule);

```

**Comment by andy-ms** [comment]
No, TypeScript will never change the behavior of your code.
If you want your code to have different behavior depending on how you build it, you would have to add a build step to do something like generate code, or write a value somewhere that the program could read it.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
