### ISSUE TITLE
tsconfig outDir does not fully replicate directory structure if all files are nested

### ISSUE THREAD

**Issue by madelson** [Microsoft/TypeScript#17332]
**TypeScript Version:**  2.4.1

**Code**

tsconfig.json:
```
{
	"compileOnSave": true,
	"compilerOptions": {
		"target": "es5",
		"allowJs": true,
                "sourceMap" true,
		"outDir": "GeneratedScripts",
		"disableSizeLimit": true,
		"removeComments": false
	},
	"include": [
		"Scripts/**/*"
	],
	"exclude": [
		"GeneratedScripts"
	]
}
```

**Expected behavior:**

I am using Microsoft.TypeScript.MsBuild 2.4.1 to transpile JavaScript and TypeScript files in my Scripts folder to another folder called GeneratedScripts. I would expect that the folder structure under Scripts is replicated under GeneratedScripts so that I can easily match up source files to transpiled files.

```
// input
- Scripts
   - Folder
     - Foo.js

// expected output
- GeneratedScripts
  - Folder
    - Foo.js
```

**Actual behavior:**

The output replicates the folder structure under Scripts UNLESS all files are nested another layer deep within Scripts.

```
// input
- Scripts
   - Folder
     - Foo.js

// actual output
- GeneratedScripts
  - Foo.js
```

However:

```
// input
- Scripts
   - Folder1
     - Foo.js
   - Folder2
     - Bar.js

// actual output
- GeneratedScripts
  - Folder1
    - Foo.js
  - Folder 2
    - Bar.js
```

**Comment by j-oliveras** [comment]
Try adding `"rootDir": "./Scripts"` into tsconfig.json.

[Compiler options.](https://www.typescriptlang.org/docs/handbook/compiler-options.html)

**Comment by madelson** [comment]
@j-oliveras thanks this makes sense. Didn't realize that this was an option.
