### ISSUE TITLE
Relax rule about `super` followed by member access

### ISSUE THREAD

**Issue by yebrahim** [Microsoft/TypeScript#17333]
I have a method that takes a class type. I can pass an explicit class name to it `Foo`, or I can pass `this`, but I cannot pass `super` because of the ts error:

> 'super' must be followed by an argument list of member access.

Is there a specific design goal behind disabling this?

**TypeScript Version:**  2.4.1

**Comment by RyanCavanaugh** [comment]
> Is there a specific design goal behind disabling this?

It's not in any sense "disabled" as much as simply not existing in the first place - it's not legal ES6 code to nakedly reference `super`, and there's not an immediately obvious ES5 transpilation.

**Comment by yebrahim** [comment]
I see, I'll close this then. Thanks for the quick reply!
