### ISSUE TITLE
unhelpful error message when missing outer parens in `string|(x: string) => any` field decl

### ISSUE THREAD

**Issue by mtaran-google** [microsoft/TypeScript#17334]
**TypeScript Version:**  2.3

**Code**

```ts
interface Foo {
  bar: string|(p1: string) => any;
}
```

**Expected behavior:**
This should compile, or give some useful error message telling me that I need to add some parens around `(p1: string) => any`.

**Actual behavior:**
Doesn't compile, and instead gives:

ERROR(2,18): : ')' expected.
ERROR(2,20): : Property or signature expected.
ERROR(2,26): : ';' expected.
ERROR(2,28): : Declaration or statement expected.
ERROR(3,1): : Declaration or statement expected.
ERROR(2,16): : Cannot find name 'p1'.
ERROR(2,20): : Cannot find name 'string'.
ERROR(2,31): : Cannot find name 'any'.

**Comment by JoshuaKGoldberg** [comment]
This has since been fixed.

https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgGIHt3IN4FgBQyyARnFAFzIDOYUoA5gD4AUADgIyU10j0CUyALwA+ZHBABPANwEAvkA

```
interface Foo {
  bar: string|(p1: string) => any;
//            ~~~~~~~~~~~~~~~~~~~
//            Function type notation must be parenthesized when used in a union type.(1385)
}
```
