### ISSUE TITLE
Unable to import thirdparty modules where js files contain jsx content

### ISSUE THREAD

**Issue by raygerami** [Microsoft/TypeScript#17341]
We are using TypeScript majorly as transpiler.
I have enabled allowJs and jsx=react in my tsconfig.json so for my project whereever I have react component with jsx content I am creating files with .jsx extension.  

However, we are using many thirdparty libaraies that have .js files with jsx content in which case we get compiler Unexpected token.
Is there a way to configure TypeScript to treat .js files with jsx content.

**Comment by mhegazy** [comment]
Not sure i understand the issue, compiling a .js file should transpile your JSX to react:

```sh
c:\test\17341>type a.js
var x = <div>some string</div>;

c:\test\17341>tsc a.js --allowjs --jsx react --outDir out

c:\test\17341>type out\a.js
var x = React.createElement("div", null, "some string");
```

**Comment by raygerami** [comment]
Thanks for getting back to me the issue is with thirdparty libraries that have jsx content but their file has .js instead of jsx.  In such case typescript throws syntax error as it does not recongnize jsx content to be valid in js.
In order to make the project compile, I am coping those libraries to my src folder

**Comment by mhegazy** [comment]
I am still sure i understand the issue. please provide a self-contained reproduction of the issue and we will be happy to investigate further.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
