### ISSUE TITLE
Cannot import named module by name unless it is in the same directory

### ISSUE THREAD

**Issue by madelson** [Microsoft/TypeScript#17342]
**TypeScript Version:**  Microsoft.TypeScript.MSBuild 2.4.1

**Code**

/Scripts/Foo/Foo1.ts

```ts
/// <amd-module name="X" />
export const x = 1;
```

/Scripts/Foo/Foo2.ts

```ts
/// <amd-module name="X" />
import { x } from "X"; // works
console.log(x);
```

/Scripts/Bar/Bar.ts

```ts
/// <amd-module name="Z" />
import { x } from "X"; // does not compile: "Cannot find module 'platformui::DateTime"
import { x } from "../Foo/Foo1"; // compiles!
```

**Expected behavior:**

Either form of import in Bar.ts will compile

**Actual behavior:**

Bar.ts is restricted to referencing the X module by file name and cannot use the AMD name.

**Comment by mhegazy** [comment]
Consider adding path mapping entries in your tsconfig.json: https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
