### ISSUE TITLE
Tsc uses wrong type when infer deterministic code

### ISSUE THREAD

**Issue by lochbrunner** [Microsoft/TypeScript#17343]
**TypeScript Version:**  2.4.2

**Code**

```ts
const A = (true) ? { b: 1 } : { c: 3 };

if (A.b === undefined) {
    const c = A.c;
}
```
(The condition should be replaceable by any other expression)

**Expected behavior:**

No compiler errors.

**Actual behavior:**

The following compiler errors:

> src/index.ts(3,7): error TS2339: Property 'b' does not exist on type '{ b: number; } | { c: number; }'.
  Property 'b' does not exist on type '{ c: number; }'.  
> src/index.ts(4,17): error TS2339: Property 'c' does not exist on type '{ b: number; } | { c: number; }'.
  Property 'c' does not exist on type '{ b: number; }'.

**Comment by andy-ms** [comment]
TypeScript won't let you access a property that might not exist.
You could try this:
```ts
const A: { kind: "b", b: number } | { kind: "c", c: number } = true ? { kind: "b", b: 1 } : { kind: "c", c: 3 };
if (A.kind === "c") {
    const c = A.c;
}
```

**Comment by jcalz** [comment]
Or, using type guards instead of discriminated unions:

```ts
function hasKey<K extends string>(x: any, k: K): x is { [_ in K]: any } {
  return k in x;  // or some other key check
}

const A = (Math.random()>0.5) ? { b: 1 } : { c: 3 };

if (!hasKey(A,'b')) {
  const c = A.c;
} else {
  const c = A.b;
}
```

**Comment by lochbrunner** [comment]
Is there a reason for that behavior?
Or is this not implemented yet?

**Comment by andy-ms** [comment]
The compiler logic is simpler if we only support property access to properties that definitely exist.
Also, without exact types (#12936), it would be unsound to take the existence or non-existence of a property as proof that a value is of a certain type.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
