### ISSUE TITLE
Playground at http://www.typescriptlang.org/play doesn't appear to be updated to 2.4

### ISSUE THREAD

**Issue by sceutre** [Microsoft/TypeScript#17353]
I'd like to use the typescript playground at http://www.typescriptlang.org/play as a tool for co-workers to explore the language, but we're using 2.4 (especially string enums) and that doesn't seem to work there.  Apologies if this is wrong place to report.

**TypeScript Version:**  less that 2.4 I'd assume

**Code**

```ts
enum Colors {
    Red = "RED",
    Green = "GREEN",
    Blue = "BLUE",
}
```

**Expected behavior:**
No errors when typed in on http://www.typescriptlang.org/play

**Actual behavior:**
Shows errors

**Comment by chriskrycho** [comment]
Confirm: the playground is running 2.3.3.

**Comment by mhegazy** [comment]
should be update to 2.5 now.

**Comment by mhegazy** [comment]
should be fixed now

**Comment by RyanCavanaugh** [comment]
Now reporting
```
ts.version: 2.5.1-insiders.20170825
````

**Comment by mhegazy** [comment]
yeah. that was the same as 2.5.2. i will update it to the latest insiders drop once we publish a new one.
