### ISSUE TITLE
Cannot use `this` to index private or protected properties

### ISSUE THREAD

**Issue by Pauan** [Microsoft/TypeScript#17362]
**TypeScript Version:**  2.4.1

**Code**

This works fine:

```ts
class Foo {
  _foo: number;

  foo(): this["_foo"] {
    return this._foo;
  }
}
```

This works fine:

```ts
class Foo {
  protected _foo: number;

  foo(): Foo["_foo"] {
    return this._foo;
  }
}
```

I expect this to work, but it does *not* work:

```ts
class Foo {
  protected _foo: number;

  foo(): this["_foo"] {
    return this._foo;
  }
}
```

It fails with this error:

```
(4,10): error TS2536: Type '"_foo"' cannot be used to index type 'this'.
```

**Comment by weswigham** [comment]
I think this is expected given our rules on indexed access types - given that the indexed access operator is defined in terms of `keyof T` (see [here](https://github.com/Microsoft/TypeScript/pull/11929)) and `keyof T` is:
> If T has no apparent string index signature, keyof T is a type of the form "p1" | "p2" | ... | "pX", where the string literals represent the names of the _public_ properties of T. If T has no public properties, keyof T is the type never.

So this would require adding an exception whereby private names are actually accessible when indexing `this`.

**Comment by Pauan** [comment]
@weswigham But `Foo["_foo"]` is the same situation, and it works fine.

So does indexing on classes have an exception for private/protected members, but that exception wasn't applied to `this`?

**Comment by mhegazy** [comment]
As @weswigham noted, this is the intended behavior. it becomes very hard to reason about these types in higher order if you have to carry around a context to know if the name is visible or not.
