### ISSUE TITLE
Crash when JS Doc comment contains uninstantiable type

### ISSUE THREAD

**Issue by haburka** [Microsoft/TypeScript#17377]
**TypeScript Version:** 2.5.0 & 2.4.2

**Code**

While compiling my angular 4 project, after upgrading typescript to 2.4.2, I found an error that I could not identify the source of. I avoided the error by reverting to 2.3.4.

Here's the error and stack trace for 2.5.0: 

```
/home/rob/ic-platform/web/build/node_modules/typescript/lib/typescript.js:39449
                        var typeParameters = symbol.flags & 524288 /* TypeAlias */ ? getSymbolLinks(symbol).typeParameters : type.target.localTypeParameters;
                                                                                                                                        ^
TypeError: Cannot read property 'localTypeParameters' of undefined
    at checkTypeReferenceNode (/home/rob/ic-platform/web/build/node_modules/typescript/lib/typescript.js:39449:137)
    at checkSourceElement (/home/rob/ic-platform/web/build/node_modules/typescript/lib/typescript.js:42629:28)
    at checkVariableLikeDeclaration (/home/rob/ic-platform/web/build/node_modules/typescript/lib/typescript.js:40735:13)
    at checkParameter (/home/rob/ic-platform/web/build/node_modules/typescript/lib/typescript.js:38903:13)
    at Object.forEach (/home/rob/ic-platform/web/build/node_modules/typescript/lib/typescript.js:1496:30)
    at checkSignatureDeclaration (/home/rob/ic-platform/web/build/node_modules/typescript/lib/typescript.js:39044:16)
    at checkSourceElement (/home/rob/ic-platform/web/build/node_modules/typescript/lib/typescript.js:42651:21)
    at checkSourceElement (/home/rob/ic-platform/web/build/node_modules/typescript/lib/typescript.js:42663:28)
    at checkSourceElement (/home/rob/ic-platform/web/build/node_modules/typescript/lib/typescript.js:42649:28)
    at checkJSDocComment (/home/rob/ic-platform/web/build/node_modules/typescript/lib/typescript.js:40244:21)
```

I would have no problem creating a fiddle that shows the minimum case to trigger this, but I haven't been able to decipher what code is causing this because I don't understand how to extract a line number from typescript, even while inspecting the code in a debugger. Thanks. 

**Expected behavior:**
Typescript should not error in a way where I can't see what file or code snippet is causing an error. 
**Actual behavior:**
If there is an error, the node that causes this issue should be explained in a somewhat human readable way.

**Comment by RyanCavanaugh** [comment]
It's a crash -- if we knew *why* we were crashing, we'd simply not crash in the first place, of course.

If you have this up in a debugger, the `node` value in the `checkVariableLikeDeclaration` frame will have a `.getText()` method that should return an unambiguous string that matches something from your source text. Since it's a crash we can also just investigate a full repo if that's an option for you

**Comment by RyanCavanaugh** [comment]
Found a repro with the same callstack - I'm guessing your code looks something like this
```ts
function fn() {

}
/**
 * @param {fn<T>} somebody
 */
function sayHello(somebody) {
    alert('Hello ' + somebody);
}

```

**Comment by haburka** [comment]
Thanks for the node.getText() tip! I found the code that is causing the crash. 

`    /** 
     * @param {function} func Function with a callback as the last parameter.
     * @param {function} [selector] A function which takes the arguments from the
     * callback and maps those to a value to emit on the output Observable.
     * @param {Scheduler} [scheduler] The scheduler on which to schedule the
     * callbacks.
     * @return {function(...params: *): Observable} A function which returns the
     * Observable that delivers the same values the callback would deliver.
     * @static true
     * @name bindCallback
     * @owner Observable
     */
    BoundCallbackObservable.create = function (func, selector, scheduler) {
        if (selector === void 0) { selector = undefined; }
        return function () {
            var args = [];
            for (var _i = 0; _i < arguments.length; _i++) {
                args[_i - 0] = arguments[_i];
            }
            return new BoundCallbackObservable(func, selector, args, this, scheduler);
        };
    };
`

I recognize this as RxJS code and here's a link to the file in question : [https://github.com/ReactiveX/rxjs/blob/master/src/observable/BoundCallbackObservable.ts#L176](BoundCallbackObserable)

If you like, I can provide more details. I love using typescript and anything I can do to help would be good.
