### ISSUE TITLE
A better way to define readonly properties ?

### ISSUE THREAD

**Issue by NN---** [Microsoft/TypeScript#1737]
Current solution involves a lot of boilerplate code:

```typescript
class A {
 constructor(a: number) {
  this._a = a;
 }
 
 private _a: number;
 get a(): number { return _a; }
```

It would be nice to have something simpler.
Now you can define properties from the constructor, why not define getter there as well ?

```typescript
class A {
 constructor(get a: number) {
 }
```

**Comment by danquirk** [comment]
You can use parameter properties today for similar shorthand:

```ts
class A {
    constructor(public x: number, private x: string) {}
}

var a:A;
var r = a.x; // number
var r2 = a.y; // error
```

See #12 for read only issues.

**Comment by NN---** [comment]
I know about shorthand.
My intention is shorthand for readonly from constructor.
I didn't see this proposal in the #12 .

**Comment by BBGONE** [comment]
It is very much awaited feature since the first typescript compilerr release and still not implemented. But in the new  TS 1.6 you already began to implement support for third party libraries like ReactJS.

**Comment by fabm22** [comment]
@danquirk You sure meant to write a  ```y``` in second parameter of your constructor right ??

**Comment by danquirk** [comment]
Correct. Fixed. You'll probably be interested in https://github.com/Microsoft/TypeScript/pull/6532
