### ISSUE TITLE
Global Variable Undefined When Calling Directly

### ISSUE THREAD

**Issue by Jonatino** [Microsoft/TypeScript#17374]
**TypeScript Version:**  2.4.0

**Code**

```ts
import { EventEmitter, Injectable } from "@angular/core";
declare var gadgets;

@Injectable()
export class TaskDataListener {
	
	constructor() {
		console.error(gadgets);
		console.error(gadgets.Hub);
		console.error(gadgets.HubSettings);
		if (gadgets.Hub) {
			console.error("subbing");
		}
	}
	
}
```

**Expected behavior:**
gadgets.Hub should exist as we see it in the `console.error(gadgets);`.

**Actual behavior:**
![image](https://user-images.githubusercontent.com/1808569/28537199-0d4bff30-7078-11e7-93f9-67325aa80f12.png)

**Comment by RyanCavanaugh** [comment]
The output you see in the console window is not a snapshot of the object, e.g. :

![image](https://user-images.githubusercontent.com/6685088/28537489-e3fb0648-705f-11e7-878e-e033202710eb.png)

So the `.Hub` property was set *after* the constructor ran.

Anyway TypeScript couldn't possibly be *causing* this behavior so please take future questions like this to an appropriate JavaScript help forum.
