### ISSUE TITLE
Cannot use 'new' error on intersection type with constructor

### ISSUE THREAD

**Issue by unional** [Microsoft/TypeScript#17388]
tsc: 2.4.2

```ts
class X { }
declare interface ConstructorAnyArgs<TClass> {
    new (...args: any[]): TClass
}


function foo(): ConstructorAnyArgs<X> { return }
function boo(): ConstructorAnyArgs<X> & { superclass: any } { return }

let Y = foo()
let y = new Y()

let Z = boo()
let z = new Z() // Cannot use 'new' with an expression whose type lacks a call or construct signature.
```

http://www.typescriptlang.org/play/index.html#src=class%20X%20%7B%20%7D%0D%0Adeclare%20interface%20ConstructorAnyArgs%3CTClass%3E%20%7B%0D%0A%20%20%20%20new%20(...args%3A%20any%5B%5D)%3A%20TClass%0D%0A%7D%0D%0A%0D%0A%0D%0Afunction%20foo()%3A%20ConstructorAnyArgs%3CX%3E%20%7B%20return%20%7D%0D%0Afunction%20boo()%3A%20ConstructorAnyArgs%3CX%3E%20%26%20%7B%20superclass%3A%20any%20%7D%20%7B%20return%20%7D%0D%0A%0D%0Alet%20Y%20%3D%20foo()%0D%0Alet%20y%20%3D%20new%20Y()%0D%0A%0D%0Alet%20Z%20%3D%20boo()%0D%0Alet%20z%20%3D%20new%20Z()%20%2F%2F%20Cannot%20use%20'new'%20with%20an%20expression%20whose%20type%20lacks%20a%20call%20or%20construct%20signature.%0D%0A

**Comment by RyanCavanaugh** [comment]
This regressed between 2.1 and 2.2

**Comment by series0ne** [comment]
@mhegazy @RyanCavanaugh 

**Adding this from [StackOverflow ](https://stackoverflow.com/questions/49511958/intersection-types-in-typescript-cannot-use-new-with-an-expression-whose-typ)for completeness**

I have identified a problem when using intersection types in TypeScript...

I have three type aliases: 

 - `Prototype<T>` - expresses an object/class that has a `prototype` property.
 - `DefaultCtor<T>` - expresses an object/class with a default constructor.
 - `ParameterizedCtor<T>` expresses an object/class with a parameterized constructor.

I have tried these intersection permutations:

 - `Prototype<T> & DefaultCtor<T>` - works fine.
 - `Prototype<T> & ParameterizedCtor<T>` - raises a compiler error.

**Example**

    type Prototype<T> = {
        prototype: T;
    }
    
    type DefaultCtor<T> = {
        new(): T;
    }
    
    type ParameterizedCtor<T> = {
        new(...args: any[]): T
    }
    
    function makeDefault<T>(ctor: Prototype<T> & DefaultCtor<T>): T {
        return new ctor();
    }
    
    function makeWithArgs<T>(ctor: Prototype<T> & ParameterizedCtor<T>, ...args: any[]): T {
        return new ctor(...args);
        // ERROR: Cannot use 'new' with an expression whose type lacks a call or construct signature.
    }

Try it in the [Playground][1]

**Error**
The error occurs with the `Prototype<T> & ParameterizedCtor<T>` intersection:

> Cannot use 'new' with an expression whose type lacks a call or
> construct signature.

Why does the TypeScript compiler recognise the `Prototype<T> & DefaultCtor<T>` intersection type as having a constructor, but not the `Prototype<T> & ParameterizedCtor<T>` intersection type?


  [1]: http://www.typescriptlang.org/play/index.html#src=type%20Prototype%3CT%3E%20%3D%20%7B%0D%0A%20%20%20%20prototype%3A%20T%3B%0D%0A%7D%0D%0A%0D%0Atype%20DefaultCtor%3CT%3E%20%3D%20%7B%0D%0A%20%20%20%20new()%3A%20T%3B%0D%0A%7D%0D%0A%0D%0Atype%20ParameterizedCtor%3CT%3E%20%3D%20%7B%0D%0A%20%20%20%20new(...args%3A%20any%5B%5D)%3A%20T%0D%0A%7D%0D%0A%0D%0Afunction%20makeDefault%3CT%3E(ctor%3A%20Prototype%3CT%3E%20%26%20DefaultCtor%3CT%3E)%3A%20T%20%7B%0D%0A%20%20%20%20return%20new%20ctor()%3B%0D%0A%7D%0D%0A%0D%0Afunction%20makeWithArgs%3CT%3E(ctor%3A%20Prototype%3CT%3E%20%26%20ParameterizedCtor%3CT%3E%2C%20...args%3A%20any%5B%5D)%3A%20T%20%7B%0D%0A%20%20%20%20return%20new%20ctor(...args)%3B%0D%0A%20%20%20%20%2F%2F%20ERROR%3A%20Cannot%20use%20'new'%20with%20an%20expression%20whose%20type%20lacks%20a%20call%20or%20construct%20signature.%0D%0A%7D

**Comment by gssjr** [comment]
I may be running into this as well. Here's my example:

```
declare namespace __example {
  interface A {
    aProp;
  }

  interface AConstructor {
    new(): A;
  }

  export const A: AConstructor;
}

class MyClass {
  myInvalidFunc = (A: __example.A) => {
    // [ts] Cannot use 'new' with an expression whose type lacks a call or construct signature.
    const a: __example.A = new A();
  }

  myValidFunc = (A: __example.AConstructor) => {
    const a: __example.A = new A();
  }
}
```

**Comment by weswigham** [comment]
> myInvalidFunc = (A: __example.A) => {
    // [ts] Cannot use 'new' with an expression whose type lacks a call or construct signature.
    const a: __example.A = new A();
  }


This is correct. `__example.A` isn't a constructor.

**Comment by gssjr** [comment]
> > myInvalidFunc = (A: __example.A) => {
> > // [ts] Cannot use 'new' with an expression whose type lacks a call or construct signature.
> > const a: __example.A = new A();
> > }
> 
> This is correct. `__example.A` isn't a constructor.

This is the part that confuses me: `export const A: AConstructor;` which makes me think that it is a constructor?
