### ISSUE TITLE
typescript 1.4 0x80070005 - JavaScript runtime error: Access is denied.

### ISSUE THREAD

**Issue by v-vairam** [Microsoft/TypeScript#1738]
0x80070005 - JavaScript runtime error: Access is denied.this.addExtension("Microsoft.VisualStudio.Web.BrowserLink.SourceMappingExtensionFactory",

receiving this error since installing TypeScript 1.4

**Comment by v-vairam** [comment]
b=function(n,t,i){var u=n.cssRules, is where error happening in dynamic script downloaded using  browserLink dynamic script

**Comment by mhegazy** [comment]
@v-vairam can you share more information about the project you are trying to build?

**Comment by v-vairam** [comment]
This error is occurring when a html content is loaded with a css class not found. Don't know why SourceMappingExtensionFactory would cause error.

**Comment by mhegazy** [comment]
We still need more information about the JS code, the TS code that generated it, and the expected "correct" behavior.
