### ISSUE TITLE
Type inference in switch statements based on class token

### ISSUE THREAD

**Issue by ovangle** [Microsoft/TypeScript#17397]
**TypeScript Version:**  2.4.2 

**Code**

Some common interfaces used in code examples below:

```ts
interface Type<T> {
  new (...args: any[]): T;
}

interface Action {
  type: string | Type<any>;
}
```

Typescript infers the correct type to use in a case statement, if the switch is on a `readonly` property of the object and the value is `const`. e.g.

```ts
export const SET_LOGIN_USER = 'set login user';
export class SetLoginUser implements Action {
  readonly type = SET_LOGIN_USER;
  constructor(public user: number) {}
}

export const SET_LOGIN_ERRORS = 'set login errors';
export class SetLoginErrors implements Action {
  readonly type = SET_LOGIN_ERRORS;
  constructor(public errors: any) {}
}

export type Actions = SetLoginUser | SetLoginErrors;

export function run(action: Actions): void {
  switch (action.type) {
    case SET_LOGIN_USER:
      // No type error is printed here, the type is inferred as `LoginUser`
      console.log(action.user);
      break;
  }
}
```

**Expected behavior:**

Since typescript is able to infer the type based on the value of a string constant, I'd expect it to infer the type based on the type token as well,

**Actual behaviour:**

However, it fails with a TS2339 error. A class/function definition is effectively `const`, isn't it? So why shouldn't it work in exactly the same way as a explicitly typed `const` value?

```ts
export class SetLoginUser implements Action {
  readonly type = SetLoginUser;
  constructor(public user: number) {}
}

export function run(action: Actions): void {
  switch (action.type) {
    case SetLoginUser:
      // Fails with TS2339: Property 'user' does not exist on type 'Actions'
      action.user;
      break;
  }
}
```

**Comment by RyanCavanaugh** [comment]
Type discriminants can only be *unit types* - types for which there is exactly one value. For example, `3` is a unit type because there's only one `3`, and we know that for all values `x` and `y` of type `3`, `x === y`.

For rather obvious reasons, it's only safe to discriminate on the basis of unit types. For example, this declaration is legal and completely breaks the `switch` (in terms of substitutability) when a `SetLoginUser` reference aliases a `SetLoginUser2` :
```ts
export class SetLoginUser2 extends SetLoginUser {
  readonly type = SetLoginUser2;
  constructor(public user: number) { super(user) }
}
```

The class constructor function (or any function for that matter) is *not* a unit type. There may be multiple constructor functions that return the same class (sounds weird but it is true) so we don't consider the `switch` here to be a valid narrowing.

**Comment by ovangle** [comment]
But using the string keys violates liskov substutability too doesn't it? So that's not a very good reason.

```
export class SetLoginUser2 extends SetLoginUser {
   readonly type = "SET_LOGIN_USER_2"; /* etc. */
}

switch (action.type) {
   case "SET_LOGIN_USER":
      // The type inference here means that `action.type === "SET_LOGIN_USER"` is a provable fact 
      // about SetLoginUser. 
      console.log(action.user);
      // But all instances of SetLoginUser2 have a different type.
      // The point is you're not expecting substitutability here, because you're in a case statement,
      // so you know that only actions with action.type === "SET_LOGIN_USER" are allowed.
}
```

Now I agree that a function is not a unit type, but a module, function pair _is_ a unit type, isn't it? There can only be one `'module_x.foo'` object? That if I _could_ express the idea

```ts
interface Type<T> {
   module M;
   new (...args): T;
}
```

Then that type, *would* be a unit type? But it's impossible to express "I belong to the module M" in the type system (nor would I think you want to), so `Type<T>` is the closest approximation to that idea we can express.

**Comment by ovangle** [comment]
I mean, the javascript operates precisely the way I expect it to when I use the class token as a key in a switch statement, why shouldn't the type system?

Unless it's because of `eval`... Yes, `eval`/`new Function()` is a problem for these types, but I also think developers would be _very_ surprised that `eval` or `new Function()`-ing a type would still match in a switch statement.

**Comment by ovangle** [comment]
Sorry, no I'm 100% wrong as usual. 

I didn't check whether the first example was actually valid typescript before posting -- but now that I understand that the language prevents overriding a "unit typed" readonly declaration in a subclass your example became a whole lot more straight forward. Yes, working as intended.

You guys think about this stuff far more than I do.

**Comment by ovangle** [comment]
Wait, so if it was possible to declare a final/sealed class in typescript, then this would this be possible? 

Obviously I'm not saying "add sealed classes" or anything, just wondering...

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Comment by ovangle** [comment]
@mhegazy @RyanCavanaugh 

Could you at least answer my question about final types? I understand why this question was closed and I don't mind, I'm just interested. I also understand that final types are unlikely to ever appear in typescript because any class can be "implemented" by an arbitrary object, so I'm not going to go open a feature request if you say that yes, that's right.

**Comment by kitsonk** [comment]
Final classes are #8306, which is currently tagged as _Won't Fix_.

**Comment by ovangle** [comment]
@kitsonk

Yeah, that still doesn't answer my question (I'm not _interested_ in seeing them implemented), but thanks...

**Comment by kitsonk** [comment]
> I just wanted to know that if they _were_ implemented, would it mean you'd be able to treat a "final" class as a unit type

That is a "how long is a piece of string question"...  You seem to be asking, if something that is not currently planned to be implemented was implemented how would it work.

**Comment by ovangle** [comment]
Basically why I'm asking is that we use this pattern a lot in our angular code base, and it's never caused us problems (although we enforce a pretty strict "interface, don't subclass" policy). 

I've got a pending issue in our issue tracker which says we should change any occurrences of this because typescript team thinks it's broken, but I wanted to know whether it could be changed in order to make it more "correct".

**Comment by vladimiry** [comment]
@ovangle did you try to use constructor based switching https://github.com/ngrx/example-app/issues/110#issuecomment-326866631 (`switch (action.constructor) {`)? Looks like it will allow you to get rid of the `readonly type` stuff.
