### ISSUE TITLE
Files missing when using NuGet lib.es2017.sharedmemory.d.ts, lib.es2017.string.d.ts, lib.es2017.intl.d.ts

### ISSUE THREAD

**Issue by bmarotta** [Microsoft/TypeScript#17395]
**TypeScript Version:**  2.4.1

**Code**

When updating typescript to the latest version, some files are missing and the code doesn't compile anymore

1>C:\(...)/packages/Microsoft.TypeScript.Compiler.2.4.1/tools/lib.es2017.d.ts(23,22): error TS6053: File 'C:/Temp/SP/GalleryGenerator/packages/Microsoft.TypeScript.Compiler.2.4.1/tools/lib.es2017.sharedmemory.d.ts' not found.
1>  
1>C:\(...)/packages/Microsoft.TypeScript.Compiler.2.4.1/tools/lib.es2017.d.ts(24,22): error TS6053: File 'C:/Temp/SP/GalleryGenerator/packages/Microsoft.TypeScript.Compiler.2.4.1/tools/lib.es2017.string.d.ts' not found.
1>  
1>C:\(...)/packages/Microsoft.TypeScript.Compiler.2.4.1/tools/lib.es2017.d.ts(25,22): error TS6053: File 'C:/Temp/SP/GalleryGenerator/packages/Microsoft.TypeScript.Compiler.2.4.1/tools/lib.es2017.intl.d.ts' not found.
1>  
1>C:\windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(4291,5): error MSB3073: The command "tsc" exited with code 2.

Apparently this is a recurrent bug that happens for every now and then:

 #14793

It should be fixed for good

**Expected behavior:**
That the code compiles

**Actual behavior:**
The code doesn't compile

**Workaround:**
Manually download the files from github. lib.es2017.intl.d.ts cannot even be found in the lib folder!

**Comment by minestarks** [comment]
This is fixed in the [nightlies](https://www.myget.org/feed/typescript-preview/package/nuget/Microsoft.TypeScript.Compiler)
