### ISSUE TITLE
There is a conflict between import and multi file namspace

### ISSUE THREAD

**Issue by ReevesSher** [Microsoft/TypeScript#17393]
**TypeScript Version:**  2.4.2 / nightly (2.5.0-dev.201xxxxx)
i dunno if i use it in a wrong way , please help , thx.
**Code**

```ts
// official demo
//Validation.ts
namespace Validation {
    export interface StringValidator {
        isAcceptable(s: string): boolean;
    }
}

//LettersOnlyValidator.ts
/// <reference path="Validation.ts" />
// once i import anything here and then a error that can`t find StringValdator occurs
namespace Validation {
    const lettersRegexp = /^[A-Za-z]+$/;
    export class LettersOnlyValidator implements StringValidator {
        isAcceptable(s: string) {
            return lettersRegexp.test(s);
        }
    }
}

```

**Expected behavior:**
nothing wrong
**Actual behavior:**
[ts] Cannot find name 'StringValidator'.

**Comment by DanielRosenwasser** [comment]
Having any import/export at the top level of a file makes your file a *module*. Things that are declared in modules (like `Validation` in `LettersOnlyValidator.ts`) aren't visible globally. Your `Validation` namespace *used* to merge across multiple files that shared the same global scope, but no longer does.

Module augmentations can achieve this, but in general I'd just say avoid writing code with namespaces nowadays unless it's necessary.
