### ISSUE TITLE
Short not null notation

### ISSUE THREAD

**Issue by Riim** [Microsoft/TypeScript#17402]
Sorry for my English.

Example:
```ts
@computed get someName() {
	const tags = (store.get('Contact', id) as Contact).tags as Array<Tag>;
	// ...
}
```
These ` as Contact`, ` as Array<Tag>`, etc. already give me nightmares.

Why not add to TS a short notation for not null value? Example:
```ts
@computed get someName() {
	const tags = store.get('Contact', id)!.tags!;
	// ...
}
```

https://kotlinlang.org/docs/reference/null-safety.html#the--operator

**Comment by ikatyang** [comment]
Did you mean the [non-null-assertion](https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#non-null-assertion-operator)?

**Comment by Riim** [comment]
Excellent!

**Comment by RyanCavanaugh** [comment]
:confused:

**Comment by kitsonk** [comment]
@RyanCavanaugh you mean:❗️ 😱 ❗️ right?

**Comment by RyanCavanaugh** [comment]
Suggestion: It'd be useful if pressing the center of the steering wheel made a beeping noise
