### ISSUE TITLE
Display version on the Playground

### ISSUE THREAD

**Issue by glentakahashi** [microsoft/TypeScript#17406]
Currently playground is running 2.3.3 even though there is a "2.4 is released" banner at the top. It should show the version of Typescript that is deployed to avoid confusion.

**Comment by RyanCavanaugh** [comment]
Yes please

**Comment by MgSam** [comment]
I've been asking for this for literally years.

**Comment by ichpuchtli** [comment]
Please god.

**Comment by mhegazy** [comment]
any suggestion where?

**Comment by mhegazy** [comment]
also note that it should show up in the console output. 
![image](https://user-images.githubusercontent.com/8000722/29592512-7909875e-8759-11e7-9b0b-722c2c83672d.png)

**Comment by glentakahashi** [comment]
How about:
<img width="558" alt="screen shot 2017-08-22 at 7 51 58 pm" src="https://user-images.githubusercontent.com/1022767/29592645-62550bf4-8773-11e7-8db3-afd3ab97e818.png">

**Comment by orta** [comment]
The new version does this 👍
