### ISSUE TITLE
Rethink having JSDocFunctionType inherit from SignatureDeclaration

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#17403]
See #17326.

**Comment by mhegazy** [comment]
that would be a breaking change as well..

**Comment by andy-ms** [comment]
It looks like we don't currently expose any way of getting jsdoc nodes, though?

**Comment by mhegazy** [comment]
nope.

**Comment by mhegazy** [comment]
nope.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Comment by andy-ms** [comment]
@sandersn wasn't happy with #18213 but I still think we should do something about this -- trying to force users of `SignatureDeclaration` to always check for undefined `name` proved difficult to implement in tslint.

**Comment by sandersn** [comment]
Does #18213 help significantly more than tslint did? It looks like it does (esp since, in comparison, it sounds like tslint failed to help). I guess it is worth the bloat if so.

**Comment by andy-ms** [comment]
@sandersn I meant that changing TypeScript to make `name` optional made fixing the tslint repository difficult, which probably means similar things for other users of the TypeScript API.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
