### ISSUE TITLE
The `: never` function, does not recognize another `: never` function it its body

### ISSUE THREAD

**Issue by parzh** [Microsoft/TypeScript#17408]
**TypeScript Version:**  2.4.1

**Code**

```ts
function foo(): never {
  throw new Error();
}


function bar(): never {
  foo(); // there's no reachable end point here
}
```

**Expected behavior:**
No compiler errors / warnings, since type annotation is present on function `foo`

**Actual behavior:**
Compiler: `[ts] A function returning 'never' cannot have a reachable end point.`

**Comment by RyanCavanaugh** [comment]
Duplicate of #14735 and its related issues
