### ISSUE TITLE
Wrong type inference with user-defined type guard methods

### ISSUE THREAD

**Issue by hbenl** [Microsoft/TypeScript#17411]
**TypeScript Version:**  2.2.0 - 2.4.2

**Code**

```ts
class Base {
	type: string;
	isA(): this is A { return this.type === 'A'; }
	isB(): this is B { return this.type === 'B'; }
}

class A extends Base {
}

class B extends Base {
}

declare const x: Base;

const isAorB = x.isA() || x.isB();
```

**Expected behavior:**
No compilation errors

**Actual behavior:**
error TS2339: Property 'isB' does not exist on type 'never'.

I tested this with several versions of Typescript:
2.1.1 - works as expected
2.2.0 - error TS2339
2.3.0 - error TS2339
2.4.2 - error TS2339

Also, it works when the type guard is a function rather than a method on the base class:
```ts
function itIsA(it: Base): it is A {
	return it.type === 'A';
}

function itIsB(it: Base): it is B {
	return it.type === 'B';
}

const itIsAorB = itIsA(x) || itIsB(x); // works
```

Finally, it also starts to work as expected when the definition of `A` is modified like this:
```ts
class A extends Base {
	type: 'A';
}
```

**Comment by jcalz** [comment]
It works as soon as you put any property into `A`:

```ts
class A extends Base {
    foo: 'bar';
}
```

My *guess* is that this has something to do with structural typing.  If `A` is structurally identical to `Base`, then once it decides that `x` is a `Base` but not an `A` then it concludes that `x` is `never`.  You can't call a method on a `never` (so it fails in your first example) but you can (apparently) pass a `never` as a parameter to another function (so it succeeds in your second example). 

I'm not sure if this is a bug or a design limitation, but it sure is strange.

**Comment by hbenl** [comment]
Yes, that would explain it. And indeed when I look at it in VS Code, in both cases (`x.isB()` and `itIsB(x)`) it thinks that `x` is of type `never`.
Can someone confirm that the conclusion "if `Base` and `A` are structurally identical and `x` is `Base` and not `A`, then `x` is `never`" is a design limitation? And is it really necessary?

**Comment by RyanCavanaugh** [comment]
Classes are structural, not nominal, so there's no difference whatsoever between `Base` and `A`. In the type system's view, if something's not an `A` then it must not be a `Base` either because those things are identical.

**Comment by hbenl** [comment]
While I'm not entirely convinced yet that this is a useful type inference, it is a corner case that can be easily avoided by making the typings more explicit - in this example, `A` and `B` should state that their `type` field must be set to `'A'` and `'B'` respectively.
