### ISSUE TITLE
Document creating in-memory programs with the API?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Microsoft/TypeScript#17410]
**TypeScript Version:**  2.4.0

**Code**

```typescript
import { createSourceFile } from "typescript";

const sourceTest = "const value = 7;";
const sourceFile = createSourceFile("source.ts", sourceText, ScriptTarget.Latest)

// Todo here: get type of `value`
```

**Expected behavior:**

It'd be useful to create a `Program` and `TypeChecker` for the source file in-memory, without using the disk.

**Actual behavior:**

The only API I can find is `createProgram`, but had to dig deep for examples of using it.

**Comment by JoshuaKGoldberg** [comment]
Edit: Found https://github.com/Microsoft/TypeScript/issues/13629. Can this be better documented?

**Comment by mhegazy** [comment]
> The only API I can find is createProgram, but had to dig deep for examples of using it.

`createProgram` is the entry point. all you need is implementing your own `TypeCheckerHost`. Let us know what specific details you need and will try to put them in the wiki.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
