### ISSUE TITLE
Longer Type descriptions?

### ISSUE THREAD

**Issue by pconerly** [Microsoft/TypeScript#17419]
How do I get longer typescript type descriptions in the error messages?

Right now I get error messages like:
```
TS2345: Argument of type '(action: TAction<TPayloadPanelIdTitle>, undoHandler: "utx-handler-standard" | "utx-handler-crop" ...' is not assignable to parameter of type 'CallEffectNamedFn<{ [x: string]: Func1<any>; }, string>'.
  Type '(action: TAction<TPayloadPanelIdTitle>, undoHandler: "utx-handler-standard" | "utx-handler-crop" ...' is not assignable to type '[{ [x: string]: Func1<any>; }, string]'.
    Property '0' is missing in type '(action: TAction<TPayloadPanelIdTitle>, undoHandler: "utx-handler-standard" | "utx-handler-crop" ...'.
```
and the ellipses gulp away a lot of information. Frustrating!

**TypeScript Version:**  2.4.1 

**Expected behavior:**
An option in tsconfig to have longer type descriptions

**Actual behavior:**
Short type descriptions.

**Comment by DanielRosenwasser** [comment]
Unfortunately it's not obvious, but we have a flag called `--noErrorTruncation`.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
