### ISSUE TITLE
Trailing Whitespace in Comments Not Preserved

### ISSUE THREAD

**Issue by Gochida** [microsoft/TypeScript#17421]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
/** { Uint32[] } Array of block sizes.  
     * Stores the block size of a memory target in bytes.
     */
    _block_size:number[] = [];
```

**Expected behavior:**
Trailing white space is preserved
**Actual behavior:**
Trailing white space is lost.

For general comments trailing white space is likely unimportant. However with jsdoc style comments, or any kind of comment which uses markdown, double trailing white space indicates a new line. This should be preserved, otherwise when documentation is generated from the output .js files, newlines are lost. Additionally, in editors such as VSCode, a neatly formatted doc comment gives you something like [this](http://i.imgur.com/gmhDQQs.jpg)
However in the .js file trailing white space is removed, and the neatly formatted tooltip for that function becomes [this](http://i.imgur.com/TqUnfrm.jpg)

A compiler option to preserve trailing white space within comments in the tsconfig.json would fix this.

**Comment by DanielRosenwasser** [comment]
Where exactly is the trailing whitespace in this example? On the line?

**Comment by Gochida** [comment]
At the end of the line, like [this](http://i.imgur.com/mXCeUXI.jpg)

**Comment by RyanCavanaugh** [comment]
Doesn't look like anyone else has noticed this, and it would require some significant work in the parser to handle it.
