### ISSUE TITLE
Type inference fails in JSX if union type is involved.

### ISSUE THREAD

**Issue by alshain** [Microsoft/TypeScript#17427]
**TypeScript Version:**  2.4.2

**Code**

```ts
type Props<T> = PropsBase<string> | PropsWithConvert<T>;

interface PropsBase<T> {
    data: T;
}

interface PropsWithConvert<T> extends PropsBase<T> {
    convert: (t: T) => string;
}

function InferenceFail<T>(props: Props<T>): JSX.Element {
    return <div />;
}

InferenceFail({data: '1'});
const test = <InferenceFail data={'1'} convert={n => '' + n} />;
InferenceFail({data: 2, convert: n => '' + n});
```

**Expected behavior:**

All lines should compile.

**Actual behavior:**

The JSX version does not compile.

Removing the type union, the JSX version is able to compile

Possibly related: #17295

**Comment by weswigham** [comment]
This no longer errors in our nightlies, but I hesitate to call it "fixed". The signature is being instantiated in a way which is inconsistent with the types of the members passed; for example, in `<InferenceFail data={'1'} convert={n => '' + n} />;`, `InferenceFail` has signature `function InferenceFail<"1">(props: Props<"1">): JSX.Element`, but `data` has the type `string`, and `convert` has the type `(n: any) => string`. The callback is incorrectly typed, which is the big issue here.

**Comment by alshain** [comment]
@weswigham That's not the same semantics as far as I can tell.

```interface Props<T> {
    data: string | T;
    convert?: (t: T) => string;
}
```

This would allow me to have `T` be `int`, but not provide a `convert` function.

**Comment by weswigham** [comment]
@alshain correct. I was merely pointing out a similar instance where we performed inference correctly. In any case, we should do inferences correctly in master/the nightly since #17790 is merged.
