### ISSUE TITLE
Generic component composition in JSX

### ISSUE THREAD

**Issue by voliva** [Microsoft/TypeScript#17426]
**TypeScript Version:**  2.2.2

**Code**

```ts
interface GenericListProps<T> {
    items: T[];
    onItemClick: (item: T) => void;
    getStringRepresentation: (item: T) => string;
}
class GenericList<T> extends React.Component<GenericListProps<T>, {}> {
    // Does stuff
}

interface GenericFilteredListProps<T> {
    items: T[];
    onItemClick: (item: T) => void;
    getStringRepresentation: (item: T) => string;
    filterValue: string;
}
class GenericFilteredList<T> extends React.Component<GenericFilteredListProps<T>, {}> {
    filterItems(items:T[]):T[] {
        // Does stuff
    }

    render() {
        return <GenericList
            items={this.filterItems(this.props.items)}
            onItemClick={this.props.onItemClick}
            getStringRepresentation={this.props.getStringRepresentation} />
    }
}
```

**Expected behavior:**
`<GenericList>` gets its generic type inferred properly

**Actual behavior:**
Compiler throws error `Type 'T[]' is not assignable to type 'T[]'. Two different types with this name exist, but they are unrelated.`

**Literature**
I'm not quite sure why isn't tsc able to infer those generic types... If you use this `<GenericList>` with no type variables (for instance, you have a string list) it will properly infer that the generic type is `string`, throwing any error if the `onItemClick` method doesn't accept strings. But if the list type is variable, then it's not able to do it.

I've seen there are workarounds on this but having this makes the code of any application more dirty:
```ts
type GenericListType = new () => GenericList<T>;
const FixedGenericList = GenericList as GenericListType;
<FixedGenericList ... />
```

**Comment by aluanhaddad** [comment]
Why don't you upgrade? I don't see any errors from this code in 2.4.2.

**Comment by voliva** [comment]
@aluanhaddad Correct, my bad. Upgrading dependencies fixes this issue.
What was causing it was aparently @types/react@15.0.2, upgrading to 15.0.39 fixes this but gets a bunch of other errors on typescript@2.2.2, but upgrading it to 2.4.2 everything's OK.
