### ISSUE TITLE
Consider exposing multiLine for ArrayLiteralExpression, ObjectLiteralExpression

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Microsoft/TypeScript#17429]
**TypeScript Version:**  2.4.0

**Code**

In `types.ts`:

```typescript
export interface ArrayLiteralExpression extends PrimaryExpression {
    kind: SyntaxKind.ArrayLiteralExpression;
    elements: NodeArray<Expression>;
    /* @internal */
    multiLine?: boolean;
}
```
```typescript
export interface ObjectLiteralExpression extends ObjectLiteralExpressionBase<ObjectLiteralElementLike> {
    kind: SyntaxKind.ObjectLiteralExpression;
    /* @internal */
    multiLine?: boolean;
}
```

It can be useful for `multiLine` to be exposed as a visible property. Was there a definite reason for it being kept `@internal`?

As a sample use case, I'm writing a transpiler for TypeScript to a syntax that distinguishes between declaring a variable on one line verses multiple lines. The `multiLine` property looks like the cleanest way to check this for the array & object literals. Without it being exposed, the options are to either `.getText(sourceFile).indexOf("\n") !== -1` or `any` cast / add to the interfaces externally.

**Comment by mhegazy** [comment]
We usually do not keep such information on the AST. this one is an outlier. i would not be open to exposing it, since i would rather we did not have it in the first place :)

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
