### ISSUE TITLE
Dynamic import does not respect --allowSyntheticDefaultImports

### ISSUE THREAD

**Issue by aluanhaddad** [Microsoft/TypeScript#17444]
**TypeScript Version:**  2.5.0-dev.20170725

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// --module esnext --allowSyntheticDefaultImports (or with --module system)
import('jquery').then(({default: $}) => $('div'));
```

**Expected behavior:**
The shape of the dynamically imported `jquery`'s module namespace object includes a `default` member having the type `JQueryStatic<HTMLElement>` as it does when using the static import syntax as in
```ts
import {default as $} from 'jquery';
$('div');
```
under `--module system` or with `--allowSyntheticDefaultImports`

**Actual behavior:**
> error TS2459: Type 'JQueryStatic&lt;HTMLElement&gt;' has no property 'default' and no string index signature.

Note that this is tricky since the expected mapping does not quite correspond to that of a static import since `import('jquery').then($ => $('div'));` probably should _not_ work, but the `default` member should be present.

**Comment by Kovensky** [comment]
This can be tricky as it won't behave correctly at runtime in webpack either.

I'd recommend just never using dynamic import with a commonjs module.

**Comment by aluanhaddad** [comment]
> I'd recommend just never using dynamic import with a commonjs module.

Do you mean that modules transpiled from ESNext to CommonJS should never use dynamic import, that modules in CommonJS format should never be imported using the construct, or both?

**Comment by Kovensky** [comment]
While we are stuck in a transpiling world, it’s safe to import transpiled
modules (that don’t do add-module-exports shenanigans), but it will not
work with transpiled modules either in real module implementation.
