### ISSUE TITLE
[API Question] How to get jsDoc comment for return tag?

### ISSUE THREAD

**Issue by dempfi** [Microsoft/TypeScript#17446]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

**Problem:** 
I'm using the compiler API and traversing AST to generate docs for my package and I did get all required information except the documentation for JSDoc return tags. Such as `return tag documentation ` in the example below.

```ts
/**
 * Function comment
 * @return {any} return tag documentation
 */
declare function x(): any
```

That comment is available in `JSDocReturnTag` type nodes but they seem to be available only in internal `jsDoc` tags array https://github.com/Microsoft/TypeScript/blob/master/src/compiler/types.ts#L519.21§

**Question:** 
How can I get that comment without relying on the internals of the nodes?

_I know these issues are not for questions in general. But the problem I have seems more suitable here since it requires some knowledge of recent changes in the compiler._

**Comment by rbuckton** [comment]
You can use `ts.getLeadingCommentRanges` today but would have to parse it yourself. We may consider making `jsDoc` public in the future, but we've been making a number of changes to jsDoc parsing and it is undergoing significant flux. As such we do not recommend any implementation take a dependency on this internal functionality as it is subject to change between releases.

**Comment by dempfi** [comment]
I see, thank you @rbuckton for reply.
