### ISSUE TITLE
Report error for duplicate @type declaration in @typedef

### ISSUE THREAD

**Issue by andy-ms** [microsoft/TypeScript#17442]
**TypeScript Version:** master

**Code**

```ts
/**
 * @typedef Name
 * @type {string}
 * @type {Oops} - this is dropped and we stop parsing the @typedef
 */
```

**Expected behavior:**

Error.

**Actual behavior:**

No error.

**Comment by noamyogev84** [comment]
Hi @mhegazy can I try that one?

**Comment by sandersn** [comment]
@noamyogev84 Go for it!

**Comment by noamyogev84** [comment]
Thanks @sandersn. can you please share some code pointers?

**Comment by sandersn** [comment]
You'll want to start in `parseTypedefTag` in parser.ts. There is a section of code that checks for the child `@type` inside `@typedef`:

```ts
while (child = tryParse(() => parseChildPropertyTag(indent))) {
    // ...
    if (child.kind === SyntaxKind.JSDocTypeTag) {
        if (childTypeTag) {
            break;
        }
        else {
            childTypeTag = child;
        }
    }
    // ...
}
```

As you can see, in case of duplicate `@type` tags, the code just breaks out of the loop with no error. Add a call to `parseErrorAtCurrentToken` before breaking out of the loop. `DiagnosticMessages.Unexpected_token` is probably good enough for the message, but you can add a new one in diagnosticMessages.json if you want. Maybe "Unexpected tag '{0}'." or "Duplicate tag '{0}'."

For adding tests, follow the directions in [CONTRIBUTING](https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#adding-a-test), except that you should add your test in `ts/tests/cases/conformance/jsdoc`, and you will need to explicitly allow JS at the top:

```ts
// @allowJS: true
// @checkJS: true
// @noEmit: true
// @Filename: bug17442.js
// ... actual test goes here ...
```

@DanielRosenwasser any opinions on what the error message should be?

**Comment by noamyogev84** [comment]
Great I'm on it.

**Comment by noamyogev84** [comment]
Hi @sandersn,
Following your directions does not produce the wanted result, or maybe i'm missing something. (No error message is outputted by the compiler)
I'm debugging tsc.js and it seems like `parseErrorAtCurrentToken` does not affect the rest of the method.

"Planting" an arbitrary syntax error in the above example **does** produce error, but I still can't figure out where it's being handled. Do you have any idea what's missing?

**Comment by noamyogev84** [comment]
@sandersn, @DanielRosenwasser
Pinging you to get your thoughts on this...

**Comment by nisha-kaushik** [comment]
Can I try this one?

**Comment by noamyogev84** [comment]
@nisha-kaushik go ahead.
