### ISSUE TITLE
Suggestion: CFA, assignment, strict null checks and function scope

### ISSUE THREAD

**Issue by kitsonk** [Microsoft/TypeScript#17449]
**TypeScript Version:**  2.4.2

**Code**

```ts
// @strictNullChecks: true
let foo: { foo: string; } | undefined;

foo = { foo: 'bar' };
document.addEventListener('click', () => {
    foo.foo; // Object is possibly 'undefined'
});

foo.foo;
```

Currently, TypeScript resets the type of variables within a function scope, giving the error that the variable is possibly `undefined`, but it can be statically determined that after the function, the outer scope does no re-assignment.  So it is possible to determine that there is no re-assignment and therefore `foo` will always be assigned.

Related to #9998 (trade-offs in CFA)
Related to #11498 (annotate immediately invoked callbacks)

**Expected behavior:**

No errors.

**Actual behavior:**

Object is possibly 'undefined'

**Comment by DanielRosenwasser** [comment]
We could do wider analysis, but I don't know how computationally expensive that would get.

I personally do think that a solution in the same vein of #11498 would be more ideal, but we haven't explored that very deeply.

**Comment by mhegazy** [comment]
As @DanielRosenwasser noted, i do not think we can do the full analysis, where a function body is inlined at the call site for control flow analysis purposes.. #11498 might be a more viable path here.
