### ISSUE TITLE
Set is not an Array type

### ISSUE THREAD

**Issue by ashubham** [Microsoft/TypeScript#17443]
**TypeScript Version:**  2.2.2

**Code**

```ts
let keys = new Set([1,2,4,5]);
let keyArray = [...keys]; // Set is not an array type.
```

**Expected behavior:**

Should be able to spread. I dont see any reason why this require ES6  as a target. Given babel is also able to transpile this.

**Comment by aluanhaddad** [comment]
I tested this with 2.2.2 and it gives no errors. It is also worth mentioning that, as of TypeScript 2.3, you can specify the `--downlevelIteration` flag and the compiler will spread the `Set`. Babel is no longer required to handle this scenario.

Also, `ES2015` should be preferred over `ES6` as the latter terminology is being phased out and seems to be interpreted inconsistently by some tools.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
