### ISSUE TITLE
Give a more helpful error message when using 'Type.propertyName' as a qualified type.

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#17458]
![image](https://user-images.githubusercontent.com/972891/28686819-619ff3fc-72c1-11e7-96a8-deb5d5ded8e0.png)

https://twitter.com/KrisJordan/status/890594965541269505

**Comment by osi-oswald** [comment]
What was the reason to disallow qualified names? It feels more natural to be able to use both ways to look up member types.

**Comment by RyanCavanaugh** [comment]
This code has always been legal:
```ts
interface Person { name: string; }
namespace Person {
  export type name = number;
}
var x: Person.name;
```
We didn't want to make a breaking change to make it illegal, or change the meaning of this code

**Comment by osi-oswald** [comment]
I see, but I guess this kind of ambiguity is quite rare (at least nowadays)? Could the following be a valid workaround:
- Allow qualified names for interfaces/classes
- If there is an ambiguity, namespaces take precedence (to not break existing code)
