### ISSUE TITLE
Mapped types intersections are too eagerly resolved

### ISSUE THREAD

**Issue by gcnew** [Microsoft/TypeScript#17456]
**TypeScript Version:**  nightly (2.5.0-dev.20170727)

**Code**

```ts
type StringContains<S extends string, L extends string> = (
    { [K in S]:      'true' } &
    { [key: string]: 'false' }
  )[L]

type ObjectHasKey<O, L extends string> = StringContains<keyof O, L>

type First<T> = ObjectHasKey<T, '0'> // eagerly resolved as 'false'
```

**Expected behavior:**
Type `First` should be left as an indexing operation.

PS: origin of the issue: https://github.com/gcanti/typelevel-ts/issues/8

**Comment by SimonMeskens** [comment]
@ahejlsberg Could you have a look at this one too?
