### ISSUE TITLE
Make catch clause variables optional

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#17467]
[The proposal](https://michaelficarra.github.io/optional-catch-binding-proposal/) by @michaelficarra makes the binding identifier in catch clauses optional.

For example:

```ts
try {
    JSON.parse("...");
}
catch {
    // Don't care, the error message is completely useless,
    // but we need to handle it.
}
```

This proposal reached stage 3 immediately upon presentation.

**Comment by RyanCavanaugh** [comment]
🚲 🏠 what should we name the variable when downleveling?

**Comment by DanielRosenwasser** [comment]
I was thinking `unexpectedTokenInJsonAtPositionSyntaxError`.

**Comment by jwbay** [comment]
I'd vote 🤷‍♀️, with downleveling as appropriate.

**Comment by SaschaNaz** [comment]
The page is moved to https://tc39.github.io/proposal-optional-catch-binding/, for someone who wants to track the change of TS 2.5.

**Comment by ZanderBrown** [comment]
Just a thought but how about having the catch block itself as optional?

For example we have the tradition try catch:

```typescript
try {
    // Something risky
} catch (e) {
    // Handle the specifics of e
}
```

The I don't care what went wrong try catch:

**Comment by kitsonk** [comment]
That would be a good suggestion for [ESDiscuss](https://esdiscuss.org/) and I am sure that TypeScript would follow suit if the proposal made it.  Diverging outside of that just in TypeScript wouldn't likely make sense.

**Comment by errorx666** [comment]
@ZanderBrown `try` doesn't imply `catch`.  Consider `try...finally`.
