### ISSUE TITLE
why the code is valid

### ISSUE THREAD

**Issue by softwhygo** [Microsoft/TypeScript#17477]
```typescript
interface B {
    (start: number): void;
}
let b:B=function(start:number){return 6};
```
why the code above is valid。the Interface limits the function's returnValue type  is void 
@

**Comment by kitsonk** [comment]
Please try searching for your answers before posting issues, or at least ask in Gitter or StackOverflow.

See: [FAQ: Why are functions returning non `void` assignable to function returning `void`?](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-functions-returning-non-void-assignable-to-function-returning-void)

**Comment by softwhygo** [comment]
@kitsonk 
thank you very much
