### ISSUE TITLE
Spelling correction quick fix not given in expressions of property accesses

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#17472]
```ts
export declare const despite: {
    the: { }
}

[|dispite.the|]
```

Expected: Quick fix available that corrects to "despite.the".
Actual: Quick is unavailable entirely unless you remove `the.`

**Comment by DanielRosenwasser** [comment]
@weswigham this example repros the issue in #17465, but it only seems to repro in master with recent changes.

**Comment by weswigham** [comment]
#17474 fixes the issue's root cause and is much nicer. I'd prefer these stay as they are, anyway.
