### ISSUE TITLE
Many Pull Requests by contributors have not been maintained for a long time

### ISSUE THREAD

**Issue by falsandtru** [microsoft/TypeScript#17476]
Even though those fixes are requested officially. Specially, https://github.com/Microsoft/TSJS-lib-generator/pull/227 should be reviewed and merged quickly.

@ahejlsberg @DanielRosenwasser @sandersn @RyanCavanaugh @rbuckton @weswigham @billti @andy-ms @sheetalkamat

**Comment by DanielRosenwasser** [comment]
Sorry about that, I'll try to have others take a look. We've had some people out on vacation and take paternity leave recently.

**Comment by falsandtru** [comment]
Okay, thanks for your response.

**Comment by falsandtru** [comment]
@DanielRosenwasser @rbuckton @mhegazy Are you addressing about that now?

**Comment by mhegazy** [comment]
sorry was on parental leave for a few months. trying to work my way through issues and PRs. should start processing more PRs next week.

**Comment by falsandtru** [comment]
you must not lose that large contribution.

**Comment by falsandtru** [comment]
https://github.com/Microsoft/TSJS-lib-generator/pull/300 and many PRs are still not reviewed. Are you lazy?

@mhegazy @ahejlsberg @DanielRosenwasser @sandersn @RyanCavanaugh @rbuckton @weswigham @billti @andy-ms @sheetalkamat
