### ISSUE TITLE
Helper function names are not safely mangled.

### ISSUE THREAD

**Issue by sccolbert** [Microsoft/TypeScript#17485]
This is squarely in the "just don't do that category" but since I've noticed that generated variable names in `for of` loops are safely mangled, I thought I'd point out that helper function names *are not* safely mangled.

**TypeScript Version:**  2.4.0 

**Code**

```ts
let __assign = 12;
let __extends = 42;

class Foo { }

class Bar extends Foo { }   // fails at runtime

let a = { ...Foo }   // fails at runtime

```

**Expected behavior:**

The `__extends` and `__assign` helper functions in the generated output should be safely mangled.

**Actual behavior:**

The helper functions are not safely mangled, and this code fails at runtime.

**Comment by RyanCavanaugh** [comment]
This is actually in the "You are empowered to destroy your own code" category - you can write your own assign/extends helper in case you're not satisfied with the behavior of the built-in helpers (which are not 100.00% compliant in certain cases)

**Comment by sccolbert** [comment]
Thanks!
