### ISSUE TITLE
Spreads cannot spread generic extended from object

### ISSUE THREAD

**Issue by cevek** [Microsoft/TypeScript#17489]
**TypeScript Version:** 2.5.0-dev.2017-07-27

**Code**

```ts
function foo<T extends object>(obj: T) {
    return {...obj}; 
}
```

**Expected behavior:**
No error

**Actual behavior:**
Error:(233, 13) TS2698:Spread types may only be created from object types.

**Comment by RyanCavanaugh** [comment]
#13557

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
