### ISSUE TITLE
Don't provide completions for namespace name

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#17488]
**TypeScript Version:**  nightly (Version 2.5.0-dev.20170727)

**Code**

```ts
namespace N.M {}
```

**Expected behavior:**

No completions when typing the `.`.

**Actual behavior:**

```ts
namespace NamedNodeMap.M {}
```

**Comment by DanielRosenwasser** [comment]
There's an `isNewIdentifierLocation` and an `isSolelyIdentifierDefinitionLocation`. Since namespaces can merge, you may want the former.

**Comment by andy-ms** [comment]
It looks like we're already doing exactly as you said -- for `namespace` we make `isNewIdentifierLocation` true and for `function` we make `isSolelyIdentifierDefinitionLocation` true.
I think vscode just ignores `isNewIdentifierLocation` though.
This behavior results in some random thing from `lib.d.ts` being injected when you try writing a namespace with a dotted name -- maybe we could try to limit the symbols to only those that are already namespaces?

**Comment by mjbvz** [comment]
@andy-ms Is `isNewIdentifierLocation` something that already exists? I don't see it in the tsserver protocol

**Comment by andy-ms** [comment]
`protocol.ts` doesn't include this, but if you use the command `"completions-full"` instead of `CommandTypes.Completions`, you'll get a `CompletionInfo` response instead of `ReadonlyArray<protocol.CompletionEntry>`. `CompletionInfo` includes additional useful information. If you can make use of that we should probably add a vscode version of `CompletionsFull` that uses `protocol.CompletionEntry` instead of `ts.CompletionEntry`. (The difference is that it uses `protocol.TextSpan` instead of `ts.TextSpan`.)

**Comment by mhegazy** [comment]
VSCode should not use `completions-full`. we should add a new version of `completions` whose body is not an array of completion items, but rather an object. 

@mjbvz would this be something you are willing to use if TS version is 3.0 or higher, but fallback to the old command for older servers?

**Comment by mjbvz** [comment]
@mhegazy Yes we should be able to support that without much trouble
