### ISSUE TITLE
Typescript error TS2339

### ISSUE THREAD

**Issue by yass-dev** [Microsoft/TypeScript#17484]
I run a small project which has only one class called iterator which is like below:

**Iterator.class.ts**

```ts
export class Iterator {
  private itr: any;
  private opt: any;
  private keys: any;
  private type: string;

  constructor(iterable, options) {
    this.itr = iterable;
    this.opt = options;
    this.keys = [];

    this.prepare();
  }

  private prepare() {
    this.type = this.itr.constructor.name.toLowerCase().trim();

    if (['array', 'object'].includes(this.type)) {
      this.keys = Object.keys(this.itr);
    }
  }
}
```

I also installed typescript both with -g flag and local in my project. but whenever I try to compile my iterator.class.ts file into js file, I faced below error: 
**iterator.class.ts(18,29): error TS2339: Property 'includes' does not exist on type 'string[]'.**

This is my tsconfig.json file and I installed all requirements I mentioned in this file like @types/node:

```json
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es5",
    "moduleResolution": "node",
    "lib": ["es2016", "dom"],
    "typeRoots" : ["./node_modules/@types"],
    "types": ["node"]
  }
}
```
I try both global installed of typescript and the local one and each time I gave the error I mentioned!
I also change target to es2016 and es2017 and add "es2016.array.includes" to lib in tsconfig.js but nothing changed in result. I searched in issues on typescript and non of solutions don't worked for me!

**OS: Ubuntu 16.04 LTS**
**NODE: v8.2.1**
**npm: v5.3.0**
**typescript: v2.4.2 and 2.2.2**

**Comment by andy-ms** [comment]
It works for me with that exact setup. Is it possible that the `tsconfig.json` file isn't being used? Normally, `Iterator.class.ts` should be in the same directory as it or a subdirectory, and you compile by running `tsc` in the same directory as the `tsconfig.json`.

**Comment by yass-dev** [comment]
It's interesting.....
This project on a mac (Sierra) works fine for me too
but on this machine (Ubuntu  LTS), it gave me mentioned error.
I am not sure if this config file used or not, but when I remove tsconfig.json from project, I see the same error. It is really seems that this config does nothing!!!
is there anything I should do before using tsc, so it was known to tsc?

**Comment by andy-ms** [comment]
You can use the [`--project`](https://www.typescriptlang.org/docs/handbook/compiler-options.html) option to explicitly specify a `tsconfig.json` file. That should be unnecessary if you're running `tsc` from the same directory as your `tsconfig.json` though.

**Comment by yass-dev** [comment]
OK.
using tsc with --project has the same result
It is odd to me that this project works on mac but has this weird issue on linux
I am sure that i running tsc correctly and tsconfig.json is in correct place.
any suggestion would be great!
thanks

**Comment by yass-dev** [comment]
I also changed tsconfig in a way cause errors on compilation and it behaves as expected (I see the errors because of bad config) which is more odd!
It seems it just not working about this particular method!

**Comment by andy-ms** [comment]
Could you share an example project that reproduces the error?

**Comment by yass-dev** [comment]
you can see below project. it is small and does nothing.

https://github.com/yass-dev/NODEM

just try to compile iterator.class.ts (in packages/iterator/iterator.class.ts) to js file and see the error for include method.
Today morning I'll re-check on mac, and here I have the same problem despite what I say about it last night which this works fine on mac. My bad! sorry... (have the same error on mac and ubuntu both!)

using both global installed typescript and local one in node_modules, I faced the same error.
Thanks for your time!

**Comment by andy-ms** [comment]
I ran this on the command line:
```sh
git clone https://github.com/yass-dev/NODEM.git
cd NODEM
npm instal
tsc
```
and got no errors.

**Comment by yass-dev** [comment]
thank you! tsc command works correctly and compile (all) .ts to .js with no errors/warning(tsc version 2.2.2, 2.4.2 and 2.5.0-dev.20170727), but when I pass packages/iterator/iterator.class.ts to tsc command as its argument I faced that error.

shouldn't we use tsc command with path-to-file argument!?? (like 'tsc packages/iterator/iterator.class.ts') there is no way/need to do this??

Thanks for your time and patient! (this is my last question)

**Comment by andy-ms** [comment]
A `tsconfig.json` also specifies what files it applies to (the default being every `ts` file in its directory and sub-directories), so you shouldn't repeat that information. If you just run `tsc some-file.ts`, you will compile just that file with no project.
Not sure why you would want to compile just one file in a multi-file project; if you are editing your project and want continuous compiles of changed files you could use `tsc --watch` to do that.

**Comment by yass-dev** [comment]
Thanks for your patient...
I didn't know that about default target of compilation in tsc command. Maybe I did not read the docs carefully (my bad), otherwise it should be pointed at very first of typescript docs (in my opinion); because, I think we expect to pass the path-and-file-name to tsc command like we did in cs (for C#), as this is a Microsoft product. I really have no clue that tsc command targets all .ts file in project directory and subdirectories (again it could be my misunderstanding!)
I close this issue as it is solved!

Thanks again!

**Comment by kitsonk** [comment]
> otherwise it should be pointed at very first of typescript docs

The project configuration makes it pretty clear what a `tsconfig.json` is and how to configure it and use it to compile a project as well as goes through the details of what options are available.

<img width="231" alt="tsconfig_json_ _typescript" src="https://user-images.githubusercontent.com/1282577/28766411-5a0a214a-75c7-11e7-906c-2b1917e472cb.png">

And `tsc --help` outputs the following:

```
 -t VERSION, --target VERSION                       Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', or 'ESNEXT'.
``
