### ISSUE TITLE
TypeScript 2.4.2 release missing from GitHub releases/tags

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/TypeScript#17487]
It looks like TypeScript 2.4.2 release and the release notes are missing from GitHub releases/tags, unlike other releases. Is this intentional?

**Comment by DanielRosenwasser** [comment]
Fixed, thanks a bunch for reporting. Check out https://github.com/Microsoft/TypeScript/releases/tag/v2.4.2.
