### ISSUE TITLE
Impossible implement another class with private fields

### ISSUE THREAD

**Issue by cevek** [Microsoft/TypeScript#17490]
**TypeScript Version:**  2.5.0 nightly 

**Code**

```ts
class Foo {
    baz: string;
    private foo: string; 
}

//TS2420:Class 'Bar' incorrectly implements interface 'Foo'.
//  Property 'foo' is missing in type 'Bar'.
class Bar implements Foo {
    baz: string;
}
```
But if add private member `foo` to `Bar` it throws
TS2420:Class 'Bar' incorrectly implements interface 'Foo'.
  Types have separate declarations of a private property 'foo'.

**Comment by RyanCavanaugh** [comment]
See #471
