### ISSUE TITLE
Better error messages for mixins

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#17504]
**TypeScript Version:**  nightly (2.5.0-dev.20170727)

Issue #4890, "Allow class to extend from a generic type parameter", is marked solved. So let's try it out:

```ts
function f<T extends new() => any>(C: T) {
	return class extends C {}
}
```

Huh? We get `src/a.ts(2,23): error TS2507: Type 'T' is not a constructor function type.`.
That's not too intuitive since it worked fine with `C: new() => any`.

We actually need:

```ts
function g<T extends new(...args: any[]) => any>(C: T) {
	return class extends C {}
}
```

Maybe the error message should mention something about needing `...args: any[]`?

**Comment by aluanhaddad** [comment]
@andy-ms thank you! I didn't realize the signature had to be exactly `new (...args: any[]) => something` and was trying to use `new (...args: {}[]) => any` which currently fails with the `not a constructor function type` error.

**Comment by mhegazy** [comment]
@DanielRosenwasser recommendations?

**Comment by DanielRosenwasser** [comment]
```
Classes may only extend types bounded by constructors with a single rest parameter of type 'any[]' (e.g. 'new (...args: any[]) => {0}').
```

Related span:

```
Did you mean for '{0}' to be declared with type 'new (...args: any[]) => {1}'.
```

**Comment by andy-ms** [comment]
Correction: We actually actually need:
```ts
function g<T extends new(...args: any[]) => {}>(C: T) {
	return class extends C {}
}
```
Returning `any` is unsafe, see #26286

**Comment by thejohnfreeman** [comment]
People have been getting this wrong for over a year. Maybe TypeScript should add a `constructor<T>` built-in type?
