### ISSUE TITLE
Support inferred string-modified union types

### ISSUE THREAD

**Issue by RonPenton** [Microsoft/TypeScript#17512]
I ran into an interesting situation that I wanted to run by the community to see if there's a way to add a new feature into TypeScript to support. I'll grant that it's an edge-case, but it seems like something that could be kind of neat. 

Here's the code:

**Code**

```ts

// From Library 1
type status = "success" | "error" | "warning" | "info";

// From Library 2
type statusColor = "success" | "success-dark" | "error" | "error-dark" | "warning" | "warning-dark" | "info" | "info-dark";

// My library
function getColorFromStatus(status: status): statusColor {

    // ideal case: doesn't work:
    return status + "-dark";    // Error TS2322	Type 'string' is not assignable to type 'statusColor'

    // compromise: compiles but not type-safe. Changes to "status" type won't be caught.
    return status + "-dark" as statusColor;

    // safe case: works but extra code + runtime penalty:
    switch (status) {
        case "success": return "success-dark";
        case "error": return "error-dark";
        case "warning": return "warning-dark";
        case "info": return "info-dark";
    }
}

```

I think it would be neat if the expression:

```ts
status + "-dark"
```

could be automatically inferred to be of type:

```ts
"success-dark" | "error-dark" | "warning-dark" | "info-dark";
```

It's probably a lot more complex than it seems. And there's probably a heck of a lot of issues dealing with what happens with other string operations or if a runtime function like .toUpperCase() is called on the string, and what happens if any item in the union isn't a string, etc, etc. But still.

Any thoughts?

**Comment by aluanhaddad** [comment]
I believe this is roughly the same idea as proposed in https://github.com/Microsoft/TypeScript/issues/16746#issuecomment-311205253

I think it is a great idea, but might be highly complex.

I would say it is not an edge case because, if generalized somewhat, it could allow for
```ts
interface Outer {
  details: Inner
}
interface Inner {
  name: string;
}

type Delimiter = ".";

type DeepKey<T, OKey extends keyof T, IKey extends keyof T[OKey]> = OKey + Delimiter + IKey;


function pick<T, TDeepKey extends DeepKey<T>>(o: T, key: TDeepKey) {
  const [outer, inner] = key.split(".");
  return o[outer][inner];
}

declare const o: Outer;
const deepKey = ;
const name = pick(o, "details" + "." + "name");
```

**Comment by gcnew** [comment]
Another related issue https://github.com/Microsoft/TypeScript/issues/12940.

**Comment by DanielRosenwasser** [comment]
As well as #12754

**Comment by RyanCavanaugh** [comment]
We'd either have to invent a completely new kind of type (a deferred-expansion union), which would be a ton of work, or risk people accidently creating combinatorially explosive literal types. This doesn't seem to come up often enough to warrant either scenario.
