### ISSUE TITLE
Something wrong with `keyof` field and classic field in a type

### ISSUE THREAD

**Issue by foisonocean** [Microsoft/TypeScript#17519]
**TypeScript Version:**  2.4.2

**Code**

```ts
interface Foo {
  a: string;
  b: number;
  c: boolean;
}

type Bar = {
  foo?: string;
  [key in keyof Foo]?: string | number | boolean;
};
```

**Expected behavior:**
Compile succeed.

**Actual behavior:**
![image](https://user-images.githubusercontent.com/15059605/28752592-fec978c4-7555-11e7-833f-b1d3a0007b2c.png)

**Comment by ikatyang** [comment]
[Mapped types](http://www.typescriptlang.org/docs/handbook/advanced-types.html#mapped-types) are not allowed to have additional properties, use intersection types instead.

```ts
type Bar = {
  foo?: string;
} & {
  [key in keyof Foo]?: string | number | boolean;
};
```

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
