### ISSUE TITLE
No signature help description when JSDoc appears on variable declarations instead of signatures

### ISSUE THREAD

**Issue by Alphapage** [microsoft/TypeScript#17510]
Hello,
Here is the playground to show my problem:
https://www.typescriptlang.org/play/#src=%2F**%0D%0A%20*%20t%20comment%0D%0A%20*%40param%20%7Bstring%7D%20pa%20a%20str%0D%0A%20*%2F%0D%0Avar%20t%20%3D%20tt%20as%20((pa%3A%20string)%20%3D%3E%20void)%20%26%20((pa%3A%20string%2C%20pp%3A%20string)%20%3D%3E%20void)%0D%0At()%20%2F%2F%20no%20comments%20for%20pa%0D%0A%0D%0A%2F**%0D%0A%20*%20ttt%20comment%0D%0A%20*%40param%20pa%20a%20str%0D%0A%20*%2F%0D%0Afunction%20ttt(pa%3Astring)%20%7B%20%7D%0D%0Attt()%20%2F%2F%20working%20as%20expected

**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

**Code**

```ts
/**
 * t comment
 *@param {string} pa a str
 */
var t = tt as ((pa: string) => void) & ((pa: string, pp: string) => void)
t() // no comments for pa

/**
 * ttt comment
 *@param pa a str
 */
function ttt(pa:string) { }
ttt() // working as expected without as
```

**Expected behavior:**
I would like to use ```as``` which defines different kind of function overloads and be able to add a comment for each parameter or return value
**Actual behavior:**
Can't find a way to add comment to any parameters defined using ```as```

Thank you in advance for your help.

**Comment by DanielRosenwasser** [comment]
This is because signature help looks up the declarations of the signatures themselves. We could potentially fall back to the original declaration of the invoked expression, but as a workaround, you can declare an interface with comments on the signatures you're interested in.

```ts
interface T {
    /**
     * t comment
     *@param {string} pa a str
    */
    (pa: string): void;
    /**
     * t comment
     *@param {string} pa a str
     */
    (pa: string, pp: string): void;
}

declare var t: T;
```
