### ISSUE TITLE
Delegating to another generator

### ISSUE THREAD

**Issue by remojansen** [Microsoft/TypeScript#17518]
I tried and [example from MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/yield*):

```ts
function* g1() {
  yield 2;
  yield 3;
  yield 4;
}

function* g2() {
  yield 1;
  yield* g1(); // Error: Type 'IterableIterator<2 | 3 | 4>' is not an array type.
  yield 5;
}

var iterator = g2();

console.log(iterator.next()); // {value: 1, done: false}
console.log(iterator.next()); // {value: 2, done: false}
console.log(iterator.next()); // {value: 3, done: false}
console.log(iterator.next()); // {value: 4, done: false}
console.log(iterator.next()); // {value: 5, done: false}
console.log(iterator.next()); // {value: undefined, done: true}

```

Unfortunately, it throws an error in the [playground](https://www.typescriptlang.org/play/index.html#src=function*%20g1()%20%7B%0D%0A%20%20yield%202%3B%0D%0A%20%20yield%203%3B%0D%0A%20%20yield%204%3B%0D%0A%7D%0D%0A%0D%0Afunction*%20g2()%20%7B%0D%0A%20%20yield%201%3B%0D%0A%20%20yield*%20g1()%3B%20%2F%2F%20Error%3A%20Type%20'IterableIterator%3C2%20%7C%203%20%7C%204%3E'%20is%20not%20an%20array%20type.%0D%0A%20%20yield%205%3B%0D%0A%7D%0D%0A%0D%0Avar%20iterator%20%3D%20g2()%3B%0D%0A%0D%0Aconsole.log(iterator.next())%3B%20%2F%2F%20%7Bvalue%3A%201%2C%20done%3A%20false%7D%0D%0Aconsole.log(iterator.next())%3B%20%2F%2F%20%7Bvalue%3A%202%2C%20done%3A%20false%7D%0D%0Aconsole.log(iterator.next())%3B%20%2F%2F%20%7Bvalue%3A%203%2C%20done%3A%20false%7D%0D%0Aconsole.log(iterator.next())%3B%20%2F%2F%20%7Bvalue%3A%204%2C%20done%3A%20false%7D%0D%0Aconsole.log(iterator.next())%3B%20%2F%2F%20%7Bvalue%3A%205%2C%20done%3A%20false%7D%0D%0Aconsole.log(iterator.next())%3B%20%2F%2F%20%7Bvalue%3A%20undefined%2C%20done%3A%20true%7D%0D%0A).

> Type 'IterableIterator<2 | 3 | 4>' is not an array type.

Should that example work? Is this supported? Thanks!

**Comment by ikatyang** [comment]
You have to set `"target": "es6"` or `"downlevelIteration": true`, playground seems using the default setting, which means `"target": "es3"` and `"downlevelIteration": false`.

**Comment by remojansen** [comment]
Thanks @ikatyang, "downlevelIteration": true (not possible in the playground) fixed the issue.
