### ISSUE TITLE
Use string type(JS) when compile enum type(TS)

### ISSUE THREAD

**Issue by Aqours** [Microsoft/TypeScript#17527]
**TypeScript Version:**  2.4.2

**Code**

```ts
export enum PlayOrderEnum { Positive, Reverse, Random }
if (PlayOrderEnum.Reverse) {
    console.log('good');
} else {
    console.log('bad');
}
```

**Expected behavior:**
```js
// Compiled code (ES5)
(function (PlayOrderEnum) {
    PlayOrderEnum[PlayOrderEnum["Positive"] = 0] = "Positive";
    PlayOrderEnum[PlayOrderEnum["Reverse"] = 1] = "Reverse"; // [1]
    PlayOrderEnum[PlayOrderEnum["Random"] = 2] = "Random";
})(exports.PlayOrderEnum || (exports.PlayOrderEnum = {}));
// Use PlayOrderEnum["Reverse"] instead of PlayOrderEnum.Reverse
// If we compress property of object, PlayOrderEnum.Reverse will be transformed.
// But [1]'s 'Positive' will be always string type
if (PlayOrderEnum["Reverse"]) {
    console.log('good');
} else {
    console.log('bad');
}
```

**Actual behavior:**
```js
// Compiled code (ES5)
(function (PlayOrderEnum) {
    PlayOrderEnum[PlayOrderEnum["Positive"] = 0] = "Positive";
    PlayOrderEnum[PlayOrderEnum["Reverse"] = 1] = "Reverse";
    PlayOrderEnum[PlayOrderEnum["Random"] = 2] = "Random";
})(exports.PlayOrderEnum || (exports.PlayOrderEnum = {}));
if (PlayOrderEnum.Reverse) {
    console.log('good');
} else {
    console.log('bad');
}
```

**Comment by shivensinha4** [comment]
You could try changing the TS code to  
`if (PlayOrderEnum["Reverse"]) {
    console.log('good');  
}`

**Comment by Aqours** [comment]
@shivensinha4 You are right. But without advantage of code insight

**Comment by RyanCavanaugh** [comment]
It's not TypeScript's job to guess around at what your minifier might be doing.

**Comment by Aqours** [comment]
@RyanCavanaugh I think that the fake key in enum is string type, so compiled code should be string type, which is not relative to minifier. enum is not object, so `PlayOrderEnum['Reverse']` is better than `PlayOrderEnum.Reverse`.

**Comment by shivensinha4** [comment]
@Aqours Sure, if that happens to be your opinion. But a compiler must give the programmer the maximum amount of control of the output. Say, if you wanted the transpiled code to have foo.bar in it, maybe due to the the specific style of code of your project, and if the compiler always converts it into foo['bar'], wouldn't it be frustrating? The current behaviour of the compiler allows both the options.
