### ISSUE TITLE
Cannot access protected properties of type unions of own class

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Microsoft/TypeScript#17523]
**TypeScript Version:**  2.4.0

**Code**

```typescript
interface IDependencies {
    member: string;
}

class MyClass {
    protected readonly member: string;

    public constructor(dependencies: IDependencies | MyClass) {
        // Error: Property 'member' does not exist on type IDependencies | MyClass
        dependencies.member;

        if (dependencies instanceof MyClass) {
            dependencies.member; // fine
        } else {
            dependencies.member; // fine
        }
    }
}

new MyClass({ member: "foo" });
```

**Expected behavior:**

Neither of the erroring cases should actually be errors.

**Actual behavior:**

Both are. As per #9974, the union types don't copy information on the protected or private members. This loses the information that `member` should be accessible in this scope.

I believe this is a separate bug from 9974 because upon resolution, this particular use case should compile without errors rather than have a different error message.

**Comment by olegdunkan** [comment]
[Copying these properties or exposing them on new types (union types) would break these assumptions.](https://github.com/Microsoft/TypeScript/issues/9974#issuecomment-261422807)

```ts
        dependencies.member; //error because of see. above
        if (dependencies instanceof MyClass) {
            dependencies.member; // ok, because dependencies  is of type MyClass and we inside lexical scope of MyClass 
        } else {
            dependencies.member; // ok, because IDependencies is an interface  
        }
````

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
