### ISSUE TITLE
Type guards not working correctly when extracted as a variable

### ISSUE THREAD

**Issue by talbenari1** [Microsoft/TypeScript#17539]
**TypeScript Version:**  2.4.2

**Code**

```ts
function fun1(foo: string | number) {
  if (typeof foo === 'string') {
    const bar: string = foo // OK
  }
}

function fun2(foo: string | number) {
  const fooIsString = typeof foo === 'string'

  if (fooIsString) {
    const bar: string = foo // Type 'string | number' is not assignable to type 'string'.
  }
}

```

**Expected behavior:**
Neither `fun1` nor `fun2` should contain an error.

**Actual behavior:**
`fun2` throws `error TS2322: Type 'string | number' is not assignable to type 'string'.`

I know the example is contrived, but in my code I was using the type guard in several different places so I wanted to extract it into a variable.

**Comment by DanielRosenwasser** [comment]
Unfortunately I think being able to encode that sort of relation between the initialization and the check itself is nontrivial in terms of a control flow graph. It would also likely be expensive to perform that sort of analysis. For now I'm going to mark this as being too complex.
