### ISSUE TITLE
Cannot use empty namespace as a value

### ISSUE THREAD

**Issue by atg** [Microsoft/TypeScript#17530]
**TypeScript Version:**  2.4.2

**Code**

```ts
// OK
namespace A { class X { } }
let foo = A

// This doesn't work, but should
namespace B { /* TODO */ }
let bar = B // error TS2708: Cannot use namespace 'B' as a value.
```

**Expected behavior:**

An empty namespace should be a valid value, without having to put something in it.

**Actual behavior:**

`error TS2708: Cannot use namespace 'B' as a value.`

**Comment by ikatyang** [comment]
As you can see in [playground](http://www.typescriptlang.org/play/index.html#src=%2F%2F%20OK%0Anamespace%20A%20%7B%20class%20X%20%7B%20%7D%20%7D%0Alet%20foo%20%3D%20A%0A%0A%2F%2F%20This%20doesn't%20work%2C%20but%20should%0Anamespace%20B%20%7B%20%2F*%20TODO%20*%2F%20%7D%0Alet%20bar%20%3D%20B%20%2F%2F%20error%20TS2708%3A%20Cannot%20use%20namespace%20'B'%20as%20a%20value.), empty namespace won't be emitted.

**Comment by DanielRosenwasser** [comment]
A namespace that contains no values or statements is considered an *uninstantiated namespace*, and has no runtime value.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
