### ISSUE TITLE
SUGGESTION: enable forceConsistentCasingInFileNames by default

### ISSUE THREAD

**Issue by breathe** [microsoft/TypeScript#17542]
I just spent pretty much the whole day trying to get vscode debugger to stop on breakpoints set in typescript files.

The issue ended up being that one of the files in my project was importing a resource from a file using wrong file casing (and it just so happened to be that this file was the one I was trying to set breakpoints in) ... 

```import { foo } from "../bar/Awesomebaz"```

With the target file actually named 'AwesomeBaz.ts'. 

No warnings or execution problems occurred from this mistake ...  Everything seemed to work except my debugging experience was myseriously broken in a very hard to understand way.  It took a long time to discover the forceConsistentNaming compiler flag and get the idea to try turning it on which led immediately to the correct fix.

I think having this flag off is a bad default -- I would like to suggest turning it on by default instead.  Or at least turn it on when strict: true ...

**Comment by DanielRosenwasser** [comment]
First off, really sorry you had a lot of frustration there. This would likely be a breaking change for users, so we'd need to discuss it.

**Comment by aluanhaddad** [comment]
I forget the specific issue number but the `--forceConsistentCasingInFileNames` option does not apper to work correctly with `--paths`. I would like to use it outside of NodeJS projects but I always get `--paths` errors even though my imports are all consistent. Someone filed a bug about this recently, I will try to hunt it down.

**Comment by stephenbrady** [comment]
I'm seeing the same issue as @aluanhaddad, but I'm not able to the find the issue referred to. If the issue has not actually been filed, I'd be happy to.

**Comment by stephenbrady** [comment]
@aluanhaddad I tried reproducing our issue in a minimal setup. At first, I could not, but after setting up configuration inheritance with `extends`, I was able to expose the issue. While this could be a red herring, I'm wondering if your setup also leverages `extends`.

**Comment by stephenbrady** [comment]
FYI, issue filed: https://github.com/Microsoft/TypeScript/issues/17617
cc @aluanhaddad

**Comment by Almenon** [comment]
I've submitted a pull request for this by the way @RyanCavanaugh.  Enabling this by default would help prevent people from running into cross-platform issues with casing.

**Comment by RyanCavanaugh** [comment]
**Note**: Accepting PRs here only for changing what gets created in `tsc --init`'s `tsconfig.json` (see comments in #18394). We still don't want to change the default value due to breaking change concerns.

**Comment by timreichen** [comment]
Im interested if this died ad infinitum or if there is a plan having this implemented with a declared breaking change at some point? I just ran into the same problem using [Deno](https://deno.land). As Deno grows I could imagine there will be more and more complaints with the exact same problem.

**Comment by RyanCavanaugh** [comment]
Our general policy is that the default values of commandline values never change unless there's a very compelling reason to; I don't think this would qualify. `tsc --init` is our "good" set of commandline options.

**Comment by timreichen** [comment]
I think it would, as well as ```strict```. The most compelling reason to me is exactly that we need an extra ``` --init``` command to have it override the defaults...

**Comment by StephanTLavavej** [comment]
@jaydenseric It appears that the default was changed by #52298 on 2023-01-20.
