### ISSUE TITLE
Using the smartIndenter

### ISSUE THREAD

**Issue by fdecampredon** [Microsoft/TypeScript#1754]
To develop a codemirror mode for typescript, I'm forced to use the indenter independently of the language service, to do so I do : 
```
var sourceFile = ts.createSourceFile(Math.random()+ '.ts', text, ts.ScriptTarget.Latest, Math.random() + '');
var indent = indenter.getIndentation(position, sourceFile,  {
  IndentSize: options.indentUnit,
  TabSize: options.tabSize,
  NewLineCharacter: '\n',
  ConvertTabsToSpaces: !options.indentWithTabs
});
```
However it constantly error in `getTokenPosOfNode`, apparently it fails to find the sourceFile, after some investigation it seems that some node does not have parent. I had to tranform the obtained sourceFile with : 
```
function setParents(parent: ts.Node) {
    parent.getChildren().forEach(node => {
        if (!node.parent) {
            node.parent = parent;
        }
        setParents(node);
    })
}
```

Is there a something in the lifecycle that I should do ? Or is it a bug ?

**Comment by RyanCavanaugh** [comment]
@mhegazy or @vladima  ?

**Comment by mhegazy** [comment]
The parent pointers need to be set. there is an additional argument to the createSoruceFile to do that "setParentPointers". use this if you are using souceFiles on their own without a program or a typeChecker.

```TypeScript 
function createSourceFile(filename: string, sourceText: string, languageVersion: ScriptTarget, setParentNodes = false): SourceFile
```

**Comment by fdecampredon** [comment]
Thanks a lot, in 1.4 release the flag is called 'isOpen', so I didn't thought that it would have this effect.

**Comment by fdecampredon** [comment]
Ok just tested with 
```typescript
var sourceFile = ts.createSourceFile(Math.random()+ '.ts', text, ts.ScriptTarget.Latest, Math.random() + '', true);
var indent = indenter.getIndentation(position, sourceFile,  {
  IndentSize: options.indentUnit,
  TabSize: options.tabSize,
  NewLineCharacter: '\n',
  ConvertTabsToSpaces: !options.indentWithTabs
});
```

I still have the same error : 

```
Uncaught TypeError: Cannot read property 'text' of undefinedmain.js:7854 getTokenPosOfNodemain.js:26470 NodeObject.getStartmain.js:26479 NodeObject.getWidthmain.js:24089 nodeHasTokensmain.js:24061 findmain.js:24068 findmain.js:24045 findPrecedingTokenmain.js:32916 getIndentationmain.js:32641 indent/thirdparty/CodeMirror2/lib/codemirror.js:3861 indentLine
....
```
with typescript 1.4.1

**Comment by vladima** [comment]
Interesting. As I see the signature of [createSourceFile](https://github.com/Microsoft/TypeScript/blob/master/bin/typescript.d.ts#L1374) has 4 arguments
```typescript
function createSourceFile(filename: string, sourceText: string, languageVersion: ScriptTarget, setParentNodes?: boolean): SourceFile;
``` 

however you are passing 5 parameters

**Comment by fdecampredon** [comment]
I'm working with 1.4.1, in this version it has 5 arguments : 
```
function createSourceFile(filename: string, sourceText: string, languageVersion: ScriptTarget, version: string, isOpen?: boolean): SourceFile;
```

**Comment by mhegazy** [comment]
yes you are right. sorry about the confusion. we both were looking at the current file in master. this change did not make it to the 1.4 release. so you have a few options:
- use the latest from master, which will allow you to create a free sourceFile and use it
- create a languageService instance and use the indenter exposed on it, [here are the details](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#incremental-build-support-using-the-language-services)
- link the parent pointers yourself, using the logic in [fixupParentReferences](https://github.com/Microsoft/TypeScript/blob/release-1.4/src/services/services.ts#L1855), in service.ts

**Comment by fdecampredon** [comment]
Ok thank you, like I said I can't use ls (and don't want to) in this context so I'll go with the third solution.
