### ISSUE TITLE
Inappropriate quick fix suggestion text

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#17541]
```ts
class C {
    foo() {
        this./**/lol()
    }
}
```

The quick fix suggestion text asks the user if they want to declare a *static* method, even though the method will (appropriately) be placed on the instance side.

![image](https://user-images.githubusercontent.com/972891/28802418-35029f46-760b-11e7-94bf-7d97f01fd1ad.png)

**Comment by amcasey** [comment]
@rdosanjh, I imagine it will require more than just updating a string literal or message resource, but it should be a straightforward change to the logic that determines which string is surfaced.

**Comment by assuncaocharles** [comment]
This seems to be fixed in the lastest version in master. Am I correct ?

<img width="466" alt="screen shot 2018-10-07 at 21 16 58" src="https://user-images.githubusercontent.com/8545105/46585842-7bfe1180-ca76-11e8-902b-a27cc90cf6b0.png">

**Comment by amcasey** [comment]
@assuncaocharles it's entirely possible that @andy-ms fixed this in one of his routine fix-up passes.
