### ISSUE TITLE
[Feature] Async import for side effects

### ISSUE THREAD

**Issue by zlepper** [Microsoft/TypeScript#17549]
I would like to be able to do an async import of a side-effect module
**TypeScript Version:**  2.4.2 
**Code**

```ts
import('./side-effects-module').then(() => {
  console.log('imported')
});
```

side-effects-module.ts:
```ts
// Polyfill for browsers that donot support toBlob natively
// https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob#Polyfill
(function canvasToBlobPolyfill() {
	"use strict";

	if (!HTMLCanvasElement.prototype.toBlob) {
		Object.defineProperty(HTMLCanvasElement.prototype, 'toBlob', {
			value: function (callback, type, quality) {

				var binStr = atob(this.toDataURL(type, quality).split(',')[1]),
				    len    = binStr.length,
				    arr    = new Uint8Array(len);

				for (var i = 0; i < len; i++) {
					arr[i] = binStr.charCodeAt(i);
				}

				callback(new Blob([arr], {type: type || 'image/png'}));
			}
		});
	}
})();
```

**Expected behavior:**
The module should be imported and execute when requested

**Actual behavior:**
TS2306:File 'path/to/module/side-effects-module.ts' is not a module.

We are using this to async load polyfills before we start our application. Using normal javascript + webpack this works fine, however it's not even allowed in TypeScript.

**Comment by kitsonk** [comment]
How is this any different from the [Dynamic import expressions](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-4.html#dynamic-import-expressions) introduced in 2.4?

**Comment by zlepper** [comment]
It's using what the Dynamic import expressions should actually be able to do already in vanilla. 

So it's typescript not doing everything that it's supposed to according to the js specs.

**Comment by kitsonk** [comment]
Ok, I see your challenge `TS2306:File 'path/to/module/side-effects-module.ts' is not a module.` means that TypeScript is lacking the type information to understand that it is a module.

Any easy fix would be to do something like this in a `.d.ts` file:

```ts
declare module 'path/to/module/side-effects-module' {
    export = undefined;
}
```

Though obviously there is no equivalent at the moment of:

```
import './side-effect-module';
```

But why does the above not work for you.  Why do you need them to be dynamic, why can't they be top level?

**Comment by zlepper** [comment]
Wouldn't want to load several MBs of polyfills when 90% og out users already have those features available natively.

And your workaround could work for now, but considering that we have 17 modules like this right now, it would still be very lucky preferable if it was actually supported by the language.

**Comment by DanielRosenwasser** [comment]
Unfortunately the only way we have right now to indicate whether a file is a module or not is import/export statements. You could write `export {}` in `side-effects-module.ts` to ensure that your file is a module.

**Comment by zlepper** [comment]
Kinda what i gathered, which is why i made a feature request for it.

**Comment by aluanhaddad** [comment]
@DanielRosenwasser @zlepper perhaps I misunderstand the question here, or perhaps this is precluded by the spec explicitly, but what comes to mind is that since the following does not raise an error
```ts
import './side-effects-module'; // not a module
console.log('side-effects-module must have been loaded if we get here');
``` 
then it seems that the following _could_ also not be an error
```ts
import('./side-effects-module').then(() => {
  console.log('side-effects-module must have been loaded if we get here');
});
```
because of the nullary callback.

Does that make sense?

**Comment by zlepper** [comment]
It should not raise an error, as that is fine to do in vanilla js. The error here is being caused by the side-effect-module not being an module in the typescript definitions, so i can't deal with it. 

I would still need to get the promise from the async load, as I need to know when the module has executed, so i can start my actual application, after all needed polyfills have loaded.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
