### ISSUE TITLE
Discriminated Union support for Array types

### ISSUE THREAD

**Issue by aboyton** [Microsoft/TypeScript#17558]
**TypeScript Version:**  2.4.2

**Code**

In this code, when you are inside the `if` statement the compiler knows the type of `shape` is `Square`.
```ts
interface Square { kind: "square"; size: number; }
interface Rectangle { kind: "rectangle"; width: number; height: number; }
type Shape = Square | Rectangle;

function draw(shape: Shape) {
  if (shape.kind === 'square') {
    foo(shape);
  }
}
```
where as in this example it does not
```ts
type Square = ['square', number];
type Rectangle = ['rectangle', number, number];

type Shape = Square | Rectangle;

function draw(shape: Shape) {
  if (shape[0] === 'square') {
    foo(shape);
  }
}
```

**Expected behavior:**
It would be nice if TypeScript could tell that `shape` is of type `Square` in the second example. I'm very happy to write the check in a different manner, but it would be nice to be able to do this without having to write a User-Defined Type Guard.

**Actual behavior:**
TypeScript does not realise that `shape` is of type `Square`.

**Comment by DanielRosenwasser** [comment]
Unfortunately this is a duplicate of #10530 which we decided not to take in because of the performance impact.

**Comment by aboyton** [comment]
That makes sense. I guess they probably are the same. Thanks for the quick reply. I'll refactor my code to do things differently then.
