### ISSUE TITLE
The wiki cannot be cloned

### ISSUE THREAD

**Issue by johnnyreilly** [Microsoft/TypeScript#1755]
It looks like the wiki cannot be cloned due to the [What's new in TypeScript?](https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript%3F) page.  This is what happens when you try:

```
C:\GitHub> git clone https://github.com/Microsoft/TypeScript.wiki.git
Cloning into 'TypeScript.wiki'...
remote: Counting objects: 351, done.
remote: Compressing objects: 100% (9/9), done.
Receiving objects:  78% (274/351)   Total 351 (delta 3), reused 0 (delta 0)
Receiving objects: 100% (351/351), 94.14 KiB | 0 bytes/s, done.
Resolving deltas: 100% (206/206), done.
Checking connectivity... done.
error: Invalid path 'What's-new-in-TypeScript?.md'
```

I'm guessing this could be resolved just by dropping the "?" character in the path...

**Comment by RyanCavanaugh** [comment]
Isn't this a github bug? Questions marks are otherwise legal in wiki paths.

**Comment by johnnyreilly** [comment]
Hi @RyanCavanaugh, 

Could you clarify what you meant by a GitHub bug?  

I thought it was a file path issue.  Windows gets upset by ```What's-new-in-TypeScript?.md``` which is presumably a markdown filename.  I know Windows doesn't dig "?" in file paths and that's why I figured I couldn't clone it.

**Comment by johnnyreilly** [comment]
Just did a little reading that seems to confirm it:

https://help.github.com/articles/adding-and-editing-wiki-pages-locally/#creating-your-wiki-page-title

> Warning: Don't use the following characters in your wiki page's titles: \ / : * ? " < > |
> Users on certain operating systems won't be able to work with filenames containing these characters.

Any chance you guys could rename to drop the ```?```? (see what I did there :smile:)

**Comment by RyanCavanaugh** [comment]
OK, fixed. Let me know if you see any other issues.

**Comment by johnnyreilly** [comment]
Thanks @RyanCavanaugh.

**Comment by johnnyreilly** [comment]
Hi @RyanCavanaugh,

I tried sending a PR with a tweak to the [What's new page](https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#union-types) on the wiki but received a 403 as I don't have permission.  I don't know if you can grant me permission?  

Failing that you could do the amend yourself if you're happy with the suggested change.  It's a minor tweak to the union types section.  It includes an example of the syntax for including functions within union types.  

I enclose the updated content below.  I tried to keep this a very low impact change by amending the example already on the wiki.  I'd be happy to split it out into a separate paragraph if that makes more sense:

### Overview
Union types are a powerful way to express a value that can be one of several types. For example, you might have an API for running a program that takes a commandline as either a `string`, a `string[]` or a `Function` that returns a `string`. You can now write:
```ts
interface RunOptions {
   program: string;
   commandline: string[]|string|(() => string);
}
```

**Comment by RyanCavanaugh** [comment]
Looks like GitHub doesn't support wiki pull requests (:disappointed:). I manually merged in the change. Thanks!

**Comment by johnnyreilly** [comment]
Makes you wonder why they offer it! Thanks for merging

**Comment by danquirk** [comment]
Yeah I looked into this recently, there're some steps that can make it sorta possible but it's never as nice a Pull Request experience as the normal repo. Hopefully they add support eventually and we can make it easier for anyone to help edit the wiki.

**Comment by basarat** [comment]
Just sayin, https://github.com/Microsoft/TypeScript/issues/1514#issuecomment-69118114

**Comment by DanielRosenwasser** [comment]
Alright, alright @basarat, [I heard you the first time](https://github.com/Microsoft/TypeScript-wiki). :smiley:

**Comment by johnnyreilly** [comment]
Excellent work @DanielRosenwasser - cheers muchly :wink:
