### ISSUE TITLE
Suggestion:  Add option to make generated files read-only 

### ISSUE THREAD

**Issue by GordonSmith** [Microsoft/TypeScript#17560]
On several occasions I have accidentally modified either the generated JS file, or the generated ".d." definition file.

Typically this happens inside vscode during a debug session, or within a chrome debug session.  But it has also happened during regular edit/compile cycle (with the .d. file specifically).

**Comment by DanielRosenwasser** [comment]
Hey @GordonSmith, while I've definitely done the same, we've avoided getting involved with file permissions. For a similar request, see #14726 where we've suggested for users to incorporate a post-build step.
