### ISSUE TITLE
Suggestion: Data class support to reduce code boilerplate

### ISSUE THREAD

**Issue by hktonylee** [Microsoft/TypeScript#17578]
## Prior Work

Kotlin has a concept on this [topic](https://kotlinlang.org/docs/reference/data-classes.html). My proposal is quite to theirs but I modify their implementation in order to fit usage in Typescript and Javascript.

## Background

Sometimes when we make some simple data class, we also add the constructor, getters and setters similar to the layout of the class. For example let's make an SetNameAction (an action in react redux).

```
class SetNameAction {
    type: 'SetName';
    toName: string;

    constructor(type: 'SetName', toName: string) {
        this.type = type;
        this.toName = toName;
    }
}

function setName(type: 'SetName', toName: string): SetNameAction {
    return new SetNameAction(type, toName);
}
```

Here you can see whenever I add field to the class. I have to repeat it four times in order to get it work. And sometimes I may forget to write certain line, then it will spend me extra time to find the missing line.

## My Proposal

I would propose the extension of Typescript to the following:

```
data class SetNameAction {   // First proposal: Data Class
    readonly type: 'SetName';
    fromName: string;
    toName: string = 'no_name';
}

function setName(...args: ...SetNameAction) {  // Second proposal: Type Spread Operator
    return new SetNameAction(...args);
}
```

So that users can type once to add one field rather 4 times. Let's look into the details.

## Proposal on Data Class

Here is my proposal on data class, which is similar to the data class in Kotlin.

```
data class SetNameAction {
    readonly type: 'SetName';
    fromName: string;
    toName: string = 'no_name';
}
```

It is equivalent to the following Typescript code:

```
class SetNameAction {
    private _type: 'SetName' = 'SetName';
    private fromName: string;
    private toName: string;

    constructor(fromName: string, toName: string='no_name') {
        this.fromName = fromName;
        this.toName = toName;
    }

    get type(): string {
        return this._type;
    }
}
```

Here are the data class rules

1. Add one constructor with the same signature as the data class layout
    1. Singular literal type will be omitted in the signature
    2. Do not support optional type right now
    3. Add default parameter to the signature
2. Readonly fields are prefixed _ and private scope
3. Assign the value sequentially

The above proposal solve the problem of writing constructor and getters by hand. The next proposal is to solve the problem of writing functions with similar signature.

## Proposal on `...` operator in type

Here is the example:

```
function setName(...args: ...SetNameAction) {
    return new SetNameAction(...args);
}
```

It is equivalent to the following Typescript code

```
function setName(fromName: string, toName: string='no_name') {
    return new SetNameAction(fromName, toName);
}
```

Let's name `...SetNameAction` be type spread operator. Here the operator replicates the signature of the constructors of type or function. It can only be used in rest parameters in function.

The reason where it does not use the actual list of fields because of the data class rule 1.1: "Singular literal type is automatically filled". And replication on the constructor is more general and can be extended to function.

It should also support overloading. The receiver of the type spreading should contain all the overloading option.

**Comment by ikatyang** [comment]
It seems [parameter properties](http://www.typescriptlang.org/docs/handbook/classes.html#parameter-properties) is what you need.

The second proposal looks like duplicate of #5453.

**Comment by hktonylee** [comment]
Oh my god I should have found the parameter properties earlier. Thanks and let me close this issue.
