### ISSUE TITLE
Generate auto complete suggestions from type constraints

### ISSUE THREAD

**Issue by SamPruden** [Microsoft/TypeScript#17579]
**TypeScript Version:**  2.4.2

**Code**

```ts
declare function test<T extends Options>(options: T);

interface Options {
    a?: number;
    b?: number;
    c: number;
}

test({
    // Suggestions are given for all members of Options
});

test({
    a: 5,
    // Suggestions are still given for b and c
});

test({
    c: 5,
    // No further suggestions are given
});
```

**Expected behavior:**
Suggestions are given consistently.

**Actual behavior:**
Suggestions are only given until the provided object matches the minimum requirements of the interface.

Presumably this is because suggestions are provided based on `T` rather than `Options`, but I think generating the expressions from the type constraints might be more useful. The pattern in the example is basically just another version of 

```ts
declare function test(options: Options);
```

for when you want to capture the type of `options`, so it would make sense for the suggestions to be consistent between them.

**Comment by mhegazy** [comment]
The suggestion come from the same logic that does overload resolution. in the first two cases, there are errors that block picking an overload, and that is when the constraint comes in place. in the third case, the parameter fits the constraint, so overload resolution works, and the type is now used to infer the generic type parameter for the function. so now the only type we have is the same one the user is building. 

I suppose we can do better for some of the simple cases, where you have a naked `T` in an argument type, but it gets harder once that type is hidden.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
