### ISSUE TITLE
What is a "large" TypeScript implementation?

### ISSUE THREAD

**Issue by paulmarshall** [microsoft/TypeScript#1757]
How big (in terms of unminified JavaScript output) is a "large" typescript application you know of?

**Comment by RyanCavanaugh** [comment]
Just to kick off the thread, there's TFS at 150k LOC http://blogs.msdn.com/b/bharry/archive/2012/10/24/typescript-a-real-world-story-of-adoption-in-tfs.aspx

**Comment by jasonscharf** [comment]
I work on a project that spits out about ~80k raw LOC unminified JS. Our unminified output (including JSDoc-style comments) is about 7.2MB of JavaScript.

A quick count of semicolons across  *.ts files yields about 42k results. This includes a few definition files, however, so it's a really rough count.

We were early adopters of TypeScript, starting with 0.8.2, and while there have been some bumps along with the way with tooling, it's been incredibly successful for us so far. Today we're moving from 1.3 to 1.4 and everybody on the team just loves working with TS.

**Comment by jonathandturner** [comment]
We announced a little while back that Microsoft Azure's portal is made with TypeScript.  It's currently over a million lines of code (actually, last I heard, it's close to 1.2 million or so): http://blogs.msdn.com/b/typescript/archive/2014/10/22/typescript-and-the-road-to-2-0.aspx

**Comment by basarat** [comment]
We have around 40K lines of code in an angular app. 3.2 meg download minified.

**Comment by DanielRosenwasser** [comment]
Monaco is >200K of TypeScript - [here](https://www.youtube.com/watch?v=3Jrg8hfNXmU) you can see @jrieken discuss the team's experience in using the language.

**Comment by paulmarshall** [comment]
Looks like I'm working on the second largest TypeScript project on the planet !

**Comment by DanielRosenwasser** [comment]
Woah, great to hear you're getting some good use out of TypeScript! Would you care to shed some light on your project @paulmarshall?

**Comment by Griffork** [comment]
How do I find out how many LoC my visual studio web project has?

**Comment by basarat** [comment]
@Griffork put it on github ;) https://github.com/github/linguist

**Comment by Griffork** [comment]
Also it's 'closed source' so I can't.

**Comment by NoelAbrahams** [comment]
For an approximate count:

* Find in all files
* Enable regex
* Add filter `*.ts`
* Search for `\n`

Should print `Matching lines: xxx    Matching files: xxx    Total files searched: xxx`

**Comment by paulmarshall** [comment]
@NoelAbrahams

**Comment by paulmarshall** [comment]
It's taken a year to reply, sorry for the delay :-)

**Comment by paulmarshall** [comment]
Sorry for the delay.

@NoelAbrahams For an approximate count, "Matching lines: 278463    Matching files: 1271    Total files searched: 1273"

@DanielRosenwasser I'm part of a team developing a Lifetime Savings (Pensions to you and me) Administration application for use in the UK.

So, looks like we're the second biggest TypeScript application on the planet (#1 being Azure's portal)?

**Comment by RyanCavanaugh** [comment]
VS Code has about 300,000 lines. The race is on!
