### ISSUE TITLE
Enum with single element typed strangely

### ISSUE THREAD

**Issue by evmar** [Microsoft/TypeScript#17571]
**TypeScript Version:**  2.4.2 / playground

**Code**

```ts
enum Single { A }
enum Double { B, C }

const s: Single.A = Single.A;
const d: Double.B = Double.B;
```

The type of `s` according the playground is not `Single.A`, but rather `Single`.
The type of `d` is as you'd expect.

If you pass `s` to a function that expects a `Single.A`, it is accepted, so maybe this is only an issue in how the type presents in the UI?  But I found this reproduction because `TypeChecker.getBaseTypeOfLiteralType` returns the wrong thing on `Single.A`, so there might be more going on.

Playground link:
https://www.typescriptlang.org/play/#src=%0D%0Aenum%20Single%20%7B%20A%20%7D%0D%0Aenum%20Double%20%7B%20B%2C%20C%20%7D%0D%0A%0D%0Aconst%20s%3A%20Single.A%20%3D%20Single.A%3B%0D%0Aconst%20d%3A%20Double.B%20%3D%20Double.B%3B%0D%0A%0D%0A

**Comment by ahejlsberg** [comment]
This is working as intended. A literal enum type (an enum type where each member has no initializer or an initializer that specififes a literal value) behaves like a union of each of its members. For example, the type `Double` is just an alias for the type `Double.B | Double.C`. In the single element case that means that `Single` is just an alias for `Single.A`, and vice versa. They are basically two names for one and the same type, and the compiler simply picks the shorter name (`Single`) when displaying the type.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
