### ISSUE TITLE
Comments should be source mapped line by line

### ISSUE THREAD

**Issue by LucasSloan** [microsoft/TypeScript#17576]
If you compile code like the following:

```
/**
 * @param {number} n
 * @return {number}
 */
function incr(n: number): number {
    return n + 1;
}
```

You'll get a source map like the following (simplified):

```
generated: 1,0  original: 1,0
generated: 4,3  original: 4,3
generated: 5,0  original: 5,0
generated: 6,4  original: 6,4
generated: 7,0  original: 7,0
```

As you can see, each line of the function gets its own source mapping, but the jsdoc only gets a source mapping at the very beginning and end of the block.  For [tsickle's](https://github.com/angular/tsickle) use case, that doesn't work.  We generate the jsdoc comments from the types on the function before sending it to tsc to be compiled.  Because the jsdoc comments are semantic for Closure Compiler, if there's an issue with the jsdoc comments, we want it to get source mapped back to the original code.  That currently doesn't work because even if we generate source maps from the `@param` or `@return` lines to the function statement, it won't compose with tsc's source maps, because there aren't any mappings for those lines.  If tsc produced a line by line source map for the jsdoc comment, we could compose with it.

**Comment by DanielRosenwasser** [comment]
I think @rbuckton will know better here about a better strategy

**Comment by DanielRosenwasser** [comment]
@rbuckton, you'll need to weigh in here.

**Comment by LucasSloan** [comment]
In addition, we're currently working on migrating tsickle to run as a transformer.  This is causing problems for our source mappings, since there doesn't seem to be a way to provide source mappings for a comment.  I see 2 ways to handle this:

1.  Make synthetic comments nodes, so they can be used by ts.setOriginalNode() and ts.setSourceMapRange().
2.  Provide a way to create JSDoc nodes, so those can be source mapped, and thus the underlying comment also gets source mapped.

Option 2 seems better, since it lets you map subsets of comments back to different places in the source.

Any other options I'm missing?

**Comment by RyanCavanaugh** [comment]
Declining due to lack of interest
