### ISSUE TITLE
yield*: Delegating to other generators is not an array

### ISSUE THREAD

**Issue by JPeer264** [Microsoft/TypeScript#17585]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)
This issue might be a duplicate of #17276 (but it addresses another issue)

**Code**

The following example is straight out of the [MDN docs](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Operators/yield*) and copied it right into [TS Playground](): 
```ts
function* g1() {
  yield 2;
  yield 3;
  yield 4;
}

function* g2() {
  yield 1;
  yield* g1(); // <- gives an error: "Type 'IterableIterator<>' is not an array type"
  yield 5;
}

var iterator = g2();
```

**Expected behavior:**
Expect that the error won't appear.

**Actual behavior:**
Typescript throws an error that `g1()` is not an array type.

**Comment by DanielRosenwasser** [comment]
I'll have to fix the playground up, but make sure that

1. you have `downlevelIteration` on.
2. you're using `es2015` for your `lib` option

**Comment by JPeer264** [comment]
`downleveIteration` was not set. That solved it. Thanks.

@DanielRosenwasser The [documentation](https://www.typescriptlang.org/docs/handbook/iterators-and-generators.html) about generators are not here yet, should I update those?

**Comment by TomasHubelbauer** [comment]
I wish this was better documented, or ideally, the error message was much better. I keep running into this here and there and it would be really cool if the compiler could just let me know to enable this to make it work.

**Comment by rdsedmundo** [comment]
Definitely agree with you @TomasHubelbauer. I had the same problem, and fortunately this was posted here before, otherwise, I'd spent so much time to figure out what was the real problem.
