### ISSUE TITLE
Problems with computed property must be of type 'string', 'number', 'symbol', or 'any'.

### ISSUE THREAD

**Issue by remojansen** [Microsoft/TypeScript#17587]
I'm having problems with the restriction:

> A computed property name must be of type 'string', 'number', 'symbol', or 'any'.

And the following function:

```ts
const selectWhere = <T, W extends keyof T, S extends keyof T>(where: W, select: S) =>
    (entities: T[], value: T[W]) =>
        entities.filter(e => e[where] === value)
                .map(e => ({
                    [select]: e[select] // Error
                }));
```

The functioin shoud allow me to filter an awway by a property and select some attributes:

```ts
interface User {
    surname: string;
    age: number;
}

const selectSurnameWhereAge = selectWhere<User, "age", "surname">("age", "surname");

const users = [
    { surname: "Smith", age: 28 },
    { surname: "Johnson", age: 28 },
    { surname: "Williams", age: 14 }
];

let result = selectSurnameWhereAge(users, 28);

result[0].surname; // "Smith"
result[0].age; // Error
result[1].surname; // "Johnson"
result[2].age; // Error
```

I have a work around but it is very verbose:

```ts
const selectWhere = <T, W extends keyof T, S extends keyof T>(where: W, select: S) =>
    (entities: T[], value: T[W]) =>
        entities.filter(e => e[where] === value)
                .map(e => {
                    let obj = {};
                    Object.keys(e).forEach((k) => {
                        if (k === select) {
                            obj[k] = e[k];
                        }
                    })
                    return obj as Pick<T, S>;
                });
```

Reproduce it at [the Playground](https://www.typescriptlang.org/play/index.html#src=const%20selectWhere%20%3D%20%3CT%2C%20W%20extends%20keyof%20T%2C%20S%20extends%20keyof%20T%3E(where%3A%20W%2C%20select%3A%20S)%20%3D%3E%0D%0A%20%20%20%20(entities%3A%20T%5B%5D%2C%20value%3A%20T%5BW%5D)%20%3D%3E%0D%0A%20%20%20%20%20%20%20%20entities.filter(e%20%3D%3E%20e%5Bwhere%5D%20%3D%3D%3D%20value)%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20.map(e%20%3D%3E%20(%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5Bselect%5D%3A%20e%5Bselect%5D%20%2F%2F%20Error%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D))%3B%0D%0A%0D%0Ainterface%20User%20%7B%0D%0A%20%20%20%20surname%3A%20string%3B%0D%0A%20%20%20%20age%3A%20number%3B%0D%0A%7D%0D%0A%0D%0Aconst%20selectSurnameWhereAge%20%3D%20selectWhere%3CUser%2C%20%22age%22%2C%20%22surname%22%3E(%22age%22%2C%20%22surname%22)%3B%0D%0A%0D%0Aconst%20users%20%3D%20%5B%0D%0A%20%20%20%20%7B%20surname%3A%20%22Smith%22%2C%20age%3A%2028%20%7D%2C%0D%0A%20%20%20%20%7B%20surname%3A%20%22Johnson%22%2C%20age%3A%2028%20%7D%2C%0D%0A%20%20%20%20%7B%20surname%3A%20%22Williams%22%2C%20age%3A%2014%20%7D%0D%0A%5D%3B%0D%0A%0D%0Alet%20result%20%3D%20selectSurnameWhereAge(users%2C%2028)%3B%0D%0A%0D%0Aresult%5B0%5D.surname%3B%20%2F%2F%20%22Smith%22%0D%0Aresult%5B0%5D.age%3B%20%2F%2F%20Error%0D%0Aresult%5B1%5D.surname%3B%20%2F%2F%20%22Johnson%22%0D%0Aresult%5B2%5D.age%3B%20%2F%2F%20Error).

**Comment by RyanCavanaugh** [comment]
Duplicate of #14473 ?

**Comment by ahejlsberg** [comment]
How about just:

```ts
const selectWhere = <T, W extends keyof T, S extends keyof T>(where: W, select: S) =>
    (entities: T[], value: T[W]) => entities
        .filter(e => e[where] === value)
        .map(e => (<Pick<T, S>>{ [<string>select]: e[select]}));
```

**Comment by remojansen** [comment]
Thanks for helping out, I just tried with:
```ts
const selectWhere = <T, W extends keyof T, S extends keyof T>(where: W, select: S) =>
    (entities: T[], value: T[W]) => entities
        .filter(e => e[where] === value)
        .map(e => (<Pick<T, S>>{ [<string>select]: e[select]})); // Error
```
But I got the following error [in the playground](https://www.typescriptlang.org/play/index.html#src=const%20selectWhere%20%3D%20%3CT%2C%20W%20extends%20keyof%20T%2C%20S%20extends%20keyof%20T%3E(where%3A%20W%2C%20select%3A%20S)%20%3D%3E%0D%0A%20%20%20%20(entities%3A%20T%5B%5D%2C%20value%3A%20T%5BW%5D)%20%3D%3E%20entities%0D%0A%20%20%20%20%20%20%20%20.filter(e%20%3D%3E%20e%5Bwhere%5D%20%3D%3D%3D%20value)%0D%0A%20%20%20%20%20%20%20%20.map(e%20%3D%3E%20(%3CPick%3CT%2C%20S%3E%3E%7B%20%5B%3Cstring%3Eselect%5D%3A%20e%5Bselect%5D%7D))%3B%0D%0A%0D%0Ainterface%20User%20%7B%0D%0A%20%20%20%20surname%3A%20string%3B%0D%0A%20%20%20%20age%3A%20number%3B%0D%0A%7D%0D%0A%0D%0Aconst%20selectSurnameWhereAge%20%3D%20selectWhere%3CUser%2C%20%22surname%22%2C%20%22age%22%3E(%22surname%22%2C%20%22age%22)%3B%0D%0A%0D%0Aconst%20users%20%3D%20%5B%0D%0A%20%20%20%20%7B%20surname%3A%20%22Smith%22%2C%20age%3A%2028%20%7D%2C%0D%0A%20%20%20%20%7B%20surname%3A%20%22Johnson%22%2C%20age%3A%2028%20%7D%2C%0D%0A%20%20%20%20%7B%20surname%3A%20%22Williams%22%2C%20age%3A%2014%20%7D%0D%0A%5D%3B%0D%0A%0D%0Alet%20result%20%3D%20selectSurnameWhereAge(users%2C%2028)%3B%0D%0A%0D%0Aresult%5B0%5D.surname%3B%20%2F%2F%20%22Smith%22%0D%0Aresult%5B0%5D.age%3B%20%2F%2F%20Error%0D%0Aresult%5B1%5D.surname%3B%20%2F%2F%20%22Johnson%22%0D%0Aresult%5B2%5D.age%3B%20%2F%2F%20Error):

> Type '{ [x: string]: T[S]; }' cannot be converted to type 'Pick<T, S>'.

I reported it because I really think that it would be awesome if in the future my sample works without the need for casting.

```ts
const selectWhere = <T, W extends keyof T, S extends keyof T>(where: W, select: S) =>
    (entities: T[], value: T[W]) =>
        entities.filter(e => e[where] === value)
                .map(e => ({
                    [select]: e[select] // Error
                }));
```

Feel free to close the issue if you believe that it is a duplicate of #14473 unfortunately I don't know enough about the internals of the type system to be sure about it being a duplicate...

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
