### ISSUE TITLE
Mapping of a tuple with array functions causes an error.

### ISSUE THREAD

**Issue by Thomas-P** [Microsoft/TypeScript#17591]
**TypeScript Version:**  2.4.2 

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
//
// create a sample array of a tuple, of type (string, number)
//
const testArray: Array<[string, number]> = [['A',3], ['B', 7]];
//
// convert them to an array of a tuple, of type (string, string, number)
//
const mapToArray: Array<[string, string, number]> = testArray.map(([str, num]) => [str, str, num]);

```

**Expected behavior:**
should work fine
**Actual behavior:**

>  error TS2322: Type '(string | number)[][]' is not assignable to type '[string, string, number][]'.
>   Type '(string | number)[]' is not assignable to type '[string, string, number]'.
>     Property '0' is missing in type '(string | number)[]'.

**Workaround**
Add the result type to the map function, like this:
```ts
//
// create a sample array of a tuple, of type (string, number)
//
const testArray: Array<[string, number]> = [['A',3], ['B', 7]];
//
// convert them to an array of a tuple, of type (string, string, number)
//
const mapToArray: Array<[string, string, number]> = testArray.map(([str, num]):[string, string, number] => [str, str, num]);

```
But it themes to be a problem of converting a result type by checking the return type and map them to the outer function type.

**Comment by Thomas-P** [comment]
Closed. Themes to be a version error on my side.

**Comment by kitsonk** [comment]
Tuples are never inferred when the type is ambiguous, which it is in this case.

See: [#11924 (issue comment)](https://github.com/Microsoft/TypeScript/issues/11924#issuecomment-257029046)

There is a long discussion here about inferring literals including tuples: #10195

**Comment by Thomas-P** [comment]
ok, then I will close the issue.
