### ISSUE TITLE
getRegistration in ServiceWorkerContainer in lib.es6.d.ts returns Promise<any> instead of Promise<ServiceWorkerRegistration | undefined>

### ISSUE THREAD

**Issue by MeLlamoPablo** [Microsoft/TypeScript#17590]
[According to MDN](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerContainer/getRegistration), *The method returns a Promise that resolves to a ServiceWorkerRegistration or undefined*. Is this intended? It doesn't seem so to me because the `register` method does return `Promise<ServiceWorkerRegistration>`. This also affects `getRegistrations` which [according to MDN](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerContainer/getRegistrations) should return `Promise<Array<ServiceWorkerRegistration>>`.

If this isn't intended I'll be happy to submit a PR if you point me in the right direction to proceed.

**TypeScript Version:**  2.3.4

**Code**

```ts
const sw = await navigator.serviceWorker.getRegistration()
const swRegs = await navigator.serviceWorker.getRegistrations()
```

**Expected behavior:**

sw is ServiceWorkerRegistration | undefined
swRegs is Array<ServiceWorkerRegistration>

**Actual behavior:**

sw is any
swRegs is any

**Comment by mhegazy** [comment]
`register` seems fixed in latest: https://github.com/Microsoft/TypeScript/blob/934da9fb39d36a4afa0121468847c88457fcfe1e/lib/lib.d.ts#L1
3593, `getRegistrations` is not.

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by MeLlamoPablo** [comment]
Alright! I'm taking care of this PR then.
