### ISSUE TITLE
Find all References not working with module.exports

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#17599]
From https://github.com/Microsoft/vscode/issues/31938#issuecomment-319904587

**TypeScript Version:**  2.4.2

**Code**

```js
// main.ts
import { foo } from './lib.js';

foo();
```

```js
// lib.js
function foo() {
	console.log("hello world")
}

module.exports = { foo: foo }
```

Run `find all references` on `foo()` in `main.js`

**Expected behavior:**
`foo` references in both files are returned.

**Actual behavior:**
Only references in `main` are returned

**Comment by mhegazy** [comment]
I do not think there is a way to do this in our current system today.
