### ISSUE TITLE
Unable to suppress the original comment and emit a synthetic comment for various nodes

### ISSUE THREAD

**Issue by tbosch** [Microsoft/TypeScript#17594]
**TypeScript Version:**  2.4.2

**Context**
Needed by Angular / Tsickle for converting TypeScript types into closure type comments.
We have a workaround for this bugs, but they are not pretty and involves an `after` transformer to emit the missing comments (see [transformer_util.ts](https://github.com/angular/tsickle/blob/master/src/transformer_util.ts)).

**Code**

Plunker is [here](https://plnkr.co/edit/iifugAN6cYm1LufFfBNq?p=preview).

cases.ts:
```ts
/*importDecl*/
import {x} from './helper';

/*classStmt*/
class A {
  /*staticPropDecl*/
  static prop = 10;
  /*propDecl*/
  prop = 10;
}

/*varStmt*/
const y = x;
/*exportDecl*/
export const z = 10;
```

helper.ts:
```ts
export const x = 10;
```

transformer.ts:
```ts
const customTransformers: ts.CustomTransformers = {
  before: [suppressOriginalCommentAndEmitSyntheticComment]
};

function suppressOriginalCommentAndEmitSyntheticComment(context: ts.TransformationContext) {
  return (sourceFile: ts.SourceFile): ts.SourceFile => {
    return visitNode(sourceFile);

    function visitNode<T extends ts.Node>(node: T) {
      const leadingCommentRanges = ts.getLeadingCommentRanges(sourceFile.text, node.pos);
      if (leadingCommentRanges) {
        const synthComments = synthesizeCommentRanges(sourceFile, leadingCommentRanges);
        synthComments.forEach(c => c.text = `<${node.kind}>${c.text}`);
        ts.setSyntheticLeadingComments(node, synthComments);
        ts.setEmitFlags(node, ts.NoComments);
      }
      return ts.visitEachChild(node, visitNode, context);
    }
  };
}
```

**Expected behavior:**
No original comments are emitted (as we are using `ts.EmitFlags.NoComments`).
For every original comment, there is at least one emitted synthetic comment that also contains the node kind.

Note: It is expected that some synthetic comments show up multiple times for nodes that start at the same position.

**Actual behavior:**

- Some of the synthetic comments do not show up (import / export / prop with initializer)
- Some of the original comments are not suppressed (import / export / prop with initializer / var)

```js
"use strict";
exports.__esModule = true;
/*importDecl*/
var helper_1 = require("./helper");
/*classStmt*/
/*<229>classStmt*/
var A = (function () {
    function A() {
        /*propDecl*/
        this./*<71>propDecl*/
        prop = 10;
    }
    /*staticPropDecl*/
    A.prop = 10;
    return A;
}());
/*varStmt*/
/*<208>varStmt*/
/*<227>varStmt*/
var y = helper_1.x;
/*exportDecl*/
exports.z = 10;
```

**Comment by mprobst** [comment]
@weswigham I've looked at this a bit (trying to remove the hacks in tsickle). The problem seems to boil down to some transformer setting an emit flag like `NoComments` on a node, then TS transpiling the node to a different syntactical construct, but dropping all emit flags in the process.

Maybe a simple fix would be to have `ts.setOriginalNode` update (a subset of) `EmitFlags` onto the new node? Not sure if that always makes sense, but it would fix the issue for `NoComments`.

**Comment by weswigham** [comment]
>Maybe a simple fix would be to have ts.setOriginalNode update (a subset of) EmitFlags onto the new node? Not sure if that always makes sense, but it would fix the issue for NoComments.

It actually already copies the entire emit node, including flags.
