### ISSUE TITLE
Type inference works outside of a function, but not inside of it

### ISSUE THREAD

**Issue by RafaelSalguero** [Microsoft/TypeScript#17603]
**TypeScript Version:**  2.4.2

**Code**
```ts
const data = {
    hello: { param: 10 },
    bye: {param: "x"}
}

//Extract param types:
function paramTypes<TP>(rpc: {[K in keyof TP]: { param: TP[K] }}): TP  {
    return null as any;
}

//Correctly infered, type of "types" is {hello: number, bye: string}
let types = paramTypes(data);

function inferTypes<T>(data: T) {
    return paramTypes(data);
}

//Type of "types2" is {}
let types2 = inferTypes(data);

//error
types = types2;
```

**Expected behavior:**
Variable `types2` should have the same type as `types`

**Actual behavior:**
Variable `types2` is typed as `{}` even when the generic argument of `interTypes` is correctly inferred

**Comment by HerringtonDarkholme** [comment]
TypeScript determines function return type at declaration site. That means, `inferTypes` is typed by abstract type variable `T`, not by `typeof data`. An unbound type variable `T` is reduced to `{}`, naturally.

You can just call `paramTypes`, or annotate `inferTypes` in the same way as `paramTypes`.
