### ISSUE TITLE
checker.ts should be broken in smaller files.

### ISSUE THREAD

**Issue by 0xorial** [microsoft/TypeScript#17608]
Since I didn't find any [better place](https://stackoverflow.com/questions/45478709/should-typescript-source-code-be-organized-in-smaller-files
) to get info about that, posting it here.

**Comment by ikatyang** [comment]
See #7273

**Comment by RyanCavanaugh** [comment]
We've been slowly moving things out as it's possible. It's actually a fairly massive closure so it's harder to move things than it appears at first. The abstract suggestion of "it should be smaller" is not immediately actionable, though.
