### ISSUE TITLE
VS2017 <cast> Syntax Highlighting Issue

### ISSUE THREAD

**Issue by TeamworkGuy2** [Microsoft/TypeScript#17614]
**TypeScript Version:**  2.4.2 (2.4.1 VS2017 plugin + custom tsserver.js)
**Environment:** Visual Studio 2017 update 2, Windows 7

**Code**

```ts
var x = 0;
var y = 1;
var z = <number>x + <number>y;
```
Notice how the 2nd `<number>` and `<string>` are not syntax colored blue, but the `<Date>` is correct.
![vs2017-syntax-highlighting-issue-1](https://user-images.githubusercontent.com/890595/28973506-6735d598-7901-11e7-89f5-16f8e1b206f3.gif)

**Expected behavior:**
both `<number>` and `<string>` instances should by syntax highlighted blue
**Actual behavior:**
only the first `<number>` and `<string>` are syntax highlighted blue

**Comment by ikatyang** [comment]
SyntaxHighlighting-related issue should be tracked in [TypeScript-TmLanguage](https://github.com/Microsoft/TypeScript-TmLanguage).

**Comment by TeamworkGuy2** [comment]
Thanks for the direction!  I've created an issue over there: https://github.com/Microsoft/TypeScript-TmLanguage/issues/496

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
