### ISSUE TITLE
naming missing optional property "constructor" breaks type inference

### ISSUE THREAD

**Issue by billba** [Microsoft/TypeScript#17613]
**TypeScript Version:**  2.4.2

**Code**

```ts
interface Foo {
    constructor?: string,
    b?: string
}

const foo: Foo = {
    b: "cat"
}
```

**Expected behavior:**

`foo` is correctly initialized.

**Actual behavior:**

```
Type '{ b: string; }' is not assignable to type 'Foo'.
  Types of property 'constructor' are incompatible.
    Type 'Function' is not assignable to type 'string'.
```

Change `constructor` to anything else, including `number` or `class`, and it works.

Add `constructor` to the declaration and it works:

```ts
const foo: Foo = {
    constructor: "dog",
    b: "cat"
}
```

Cast the declaration and it works:

```ts
const foo: Foo = {
    b: "cat"
} as Foo;
```

I've looked around for any evidence that `constructor` shouldn't be allowed as the name of an object property, but I can't find any.

Obviously if this is a bug it's a pretty unimportant one, but in the framework I'm building this optional property really **is** best described as a constructor and I don't want to have to call it anything else...

**Comment by olegdunkan** [comment]
Every object has the constructor property that has type of Function, you redifine this property with string type and try to assign object literal that has constructor property of type Function. Assign incompatibly works. But I am not sure if object literal will have constructor property by default. Maybe I am wrong, but it very likely.

**Comment by billba** [comment]
@olegdunkan there is no problem creating objects with an identifier of `constructor`. The only problem is that TypeScript's type inference screws up when it's defined but missing.

**Comment by billba** [comment]
Ah I see, [every object has a constructor property](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/constructor), so this would be a bad property name. Sigh, I'll have to come up with a different name.

Closing this.
