### ISSUE TITLE
After installing TypeScript SDK for Visual Studio 2017 2.4.1 I'm stuck on 2.2.0 still

### ISSUE THREAD

**Issue by ericop** [Microsoft/TypeScript#17619]
**TypeScript Version:**  2.4.1

**Code**
In VS2017 I'm stuck on TS 2.2.2.0 according to:

![vs2017_stuck_on_ts2 2 2 0](https://user-images.githubusercontent.com/5218249/28985148-2cbabb26-792f-11e7-86fe-e6c5d241cd55.png)

 even after installing 2.4.1 from https://www.microsoft.com/en-us/download/details.aspx?id=55258 . 

I've also tried PowerShell `(Get-Package *Typescript* -MinimumVersion 1.0.0 -MaximumVersion 2.2.2) | Uninstall-Package` from https://developercommunity.visualstudio.com/content/problem/6796/installation-fails-due-to-previously-installed-typ.html with no luck. I did have VS2017 Community installed before Pro, so not sure how that might play into things.

**Expected behavior:**
*About Microsoft Visual Studio*
> Installed Products: TypeScript 2.4.1.0

**Actual behavior:**
*About Microsoft Visual Studio* 
> Installed Products: TypeScript 2.2.2.0

**Comment by ericop** [comment]
Okay, after installing  installing 2.4.1 from https://www.microsoft.com/en-us/download/details.aspx?id=55258 it seems that it un-selects the previous version you had installed and wants you to pick which one you want. It doesn't tell you it does this, which caused me 3 hours of research across StackOverflow and Microsoft sites. 

![no-typescript-compile-by-default-vs2017](https://user-images.githubusercontent.com/5218249/29044062-b6bd6c52-7b8b-11e7-8232-22835b616ec7.png)

Am i understand the idea of this right (see https://github.com/Microsoft/TypeScript/wiki/Updating-TypeScript-in-Visual-Studio-2017)?

**Comment by mhegazy** [comment]
With 15.3 this has gotten much simpler. You can find more information at: https://github.com/Microsoft/TypeScript/wiki/Updating-TypeScript-in-Visual-Studio-2017#setting-typescript-versions-in-visual-studio-2017-version-153
