### ISSUE TITLE
Update crypto.getRandomValues to use generic inference

### ISSUE THREAD

**Issue by fathyb** [Microsoft/TypeScript#17610]
**TypeScript Version:**  2.4.2
**Code**

This code does not work when using `noImplicitAny` :
```ts
const buffer = crypto.getRandomValues(new Uint8Array(31))

// Error : Element implicitly has an 'any' type because type 'ArrayBufferView' has no index signature.
const value = buffer[0]
```
To make it work we need to make an explicit cast:
```ts
const buffer = crypto.getRandomValues(new Uint8Array(31)) as Uint8Array

// Works
const value = buffer[0]
```

This is because `crypto.getRandomValues` is defined like this in `lib.dom.d.ts` :
```ts
interface RandomSource {
    getRandomValues(array: ArrayBufferView): ArrayBufferView;
}
```

We can prevent this problem by using generics as [the `array` parameter is returned](https://w3c.github.io/webcrypto/Overview.html#Crypto-method-getRandomValues):
```ts
interface RandomSource {
    getRandomValues<T extends ArrayBufferView>(array: T): T;
}
```

[off-topic] BTW isn't the index signature of an `ArrayBufferView` always a `number` no matter the internal type? [/off-topic]

**Comment by weswigham** [comment]
Tracked [here](https://github.com/Microsoft/TSJS-lib-generator/pull/278).

**Comment by sandersn** [comment]
This is fixed now. When do we close issues like this? When we update the LKG? There is only one other open, and it's from Jun 15.

**Comment by weswigham** [comment]
@sandersn I think so, but I'm not sure? @mhegazy would know what the convention is, I assume.

**Comment by fathyb** [comment]
Just found out `crypto.getRandomValues` does not take all `ArrayBufferView`s, only the integer ones [according to the last recommendation](https://www.w3.org/TR/WebCryptoAPI/#Crypto-method-getRandomValues).

The correct code should be : 
```ts
type IntArrayBufferView = Int8Array|Uint8Array|Int16Array|Uint16Array|Int32Array|Uint32Array|UInt8ClampedArray

interface RandomSource {
    getRandomValues<T extends IntArrayBufferView>(array: T): T;
}
```

**Comment by weswigham** [comment]
@fathyb [tracked](https://github.com/Microsoft/TSJS-lib-generator/pull/279).
