### ISSUE TITLE
PropertyDecorator definition doesn't match real behavior

### ISSUE THREAD

**Issue by achugaev93** [Microsoft/TypeScript#17623]
Please, help me to figure out one thing.

Recently I started using decorators a lot, and I've found that current declaration of `PropertyDecorator` is a little bit strange:

1. First argument - `target` - it's reference to a class, why does it defined as `Object`?
2. Why definition missing the third argument - property descriptor (`TypedPropertyDescriptor<T>`)? Property descriptor is available when I use decorator on property setter and not available when I use it on some simple property definition.

**TypeScript Version:**  2.4.2

**Code**

My decorator:

```ts
export function InjectProperty<T>(token: UnitToken<T>): PropertyDecorator {
    return (target: Constructor<T>, property: string | symbol): void => {
        // Here I want to modify or re-define property descriptor
    };
}
```

When using on simple property, decorator receives 2 arguments: reference to class `Uri` and property name `queryStringParser`.

```ts
export class Uri {

    @InjectProperty(QueryStringParser)
    private queryStringParser: QueryStringParser;

    // ...
}
```

When using on property setter, decorator receives 3 arguments: reference to class `Uri`, property name `queryStringParser` and descriptor of property.

```ts
export class Uri {
    private _queryStringParser: QueryStringParser;

    public get queryStringParser(): QueryStringParser {
        return this._queryStringParser;
    }

    @InjectProperty(QueryStringParser)
    public set queryStringParser(value) {
        this._queryStringParser = value;
    }

    // ...
}
```

**Expected behavior:**

In my opinion signature should be like:

```ts
declare type PropertyDecorator = <T>(target: Function, propertyKey: string | symbol, descriptor: TypedPropertyDescriptor<T>) => TypedPropertyDescriptor<T> | void;
```

**Actual behavior:**

Actual `PropertyDecorator` definition:

```ts
declare type PropertyDecorator = (target: Object, propertyKey: string | symbol) => void;
```

**Comment by achugaev93** [comment]
tsconfig.json

```json
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es6",
    "moduleResolution": "node",
    "sourceMap": true,
    "declaration": true,
    "alwaysStrict": true,
    "removeComments": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "noStrictGenericChecks": true,
    "jsx": "react",
    "typeRoots": [
      "./node_modules/@types"
    ],
    "experimentalDecorators": true,
    "lib": [
      "dom",
      "es5",
      "es6",
      "es7",
      "es2015",
      "es2015.core",
      "es2015.collection",
      "es2015.generator",
      "es2015.iterable",
      "es2015.proxy",
      "es2015.reflect",
      "es2015.symbol",
      "es2015.symbol.wellknown",
      "es2015.promise",
      "es2016",
      "es2016.array.include",
      "es2017",
      "es2017.object",
      "es2017.sharedmemory"
    ]
  },
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by aluanhaddad** [comment]
If the decorated member is prototype placed, such as a an accessor or a method, the `target` passed to  the decorator is the `prototype`. 
If the member is `static`, then the class function is passed.

See also [Decorators](https://www.typescriptlang.org/docs/handbook/decorators.html).

**Comment by achugaev93** [comment]
@aluanhaddad Thank you for explanation.
