### ISSUE TITLE
RegExp prototype needs 'flags' and Symbol-keyed properties

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#1762]
```TypeScript
/./igm.flags === "gim" && /./.flags === "";
```

Similarly, we have `Symbol.`...

* `match`
* `replace`
* `split`
* `search`

**Comment by mhegazy** [comment]
@DanielRosenwasser, I believe these two are in lib.es6.d.ts. please reactivate if i am missing something.

For `RegExp`.`flags` see https://github.com/Microsoft/TypeScript/blob/e34238cb9232a01abf2f5ab29ea62745535bddf8/src/lib/es6.d.ts#L666

For `Symbol` functions:
https://github.com/Microsoft/TypeScript/blob/e34238cb9232a01abf2f5ab29ea62745535bddf8/src/lib/es6.d.ts#L63-L87
