### ISSUE TITLE
Unused Error is misleading with side-effecting static properties

### ISSUE THREAD

**Issue by aozgaa** [Microsoft/TypeScript#17624]
The following fragment, which uses the static initialization of `s`, marks `D` unused today:
```
function sideAffecting(): number {
    console.log("called");
    return 10;
}

function foo() {
    class D {
        static s: number = sideAffecting();
    }
}
foo();
```

Initially mentioned in https://github.com/Microsoft/TypeScript/issues/16078 but this is a separate issue.

**Comment by RyanCavanaugh** [comment]
What's not unused about `D` ?

**Comment by andy-ms** [comment]
In `const x = sideAffecting();`, `x` is unused. The statement containing `x` does something, but it could be simplified to just `sideAffecting();`. (And it might be simplified to nothing at all if the side-effect is necessary to compute `x` but not desired if we don't need `x`.)

**Comment by mhegazy** [comment]
this seems like such a contrived use case of classes, that it would not be too much to ask to either disable the warning or write an extra `C;`.
