### ISSUE TITLE
Not generating output for exported const enum makes the enum useless from regular JavaScript

### ISSUE THREAD

**Issue by sccolbert** [Microsoft/TypeScript#1763]
Currently, no JavaScript is generated for const enum declarations (the language spec does not seem to address const enums).

Is there a way to get the benefit of aggressive compile-time enum evaluation while still generating the JS enum object?

It would be nice if the computed values in the example below would be computed at compile-time like is done for const enum, but retain the generated JS so that the enum can be used from non-typescript applications:

```typescript
export enum Things {
    ThingA = 0x1,
    ThingB = 0x2,
    ThingC = 0x4,
    Mask = ThingA | ThingB | ThingC,
}
```

Desired output:

```javascript
var Things;
(function (Things) {
    Things[Things["ThingA"] = 1] = "ThingA";
    Things[Things["ThingB"] = 2] = "ThingB";
    Things[Things["ThingC"] = 4] = "ThingC";
    Things[Things["Mask"] = 7] = "Mask";
})(Things || (Things = {}));
```

**Comment by RyanCavanaugh** [comment]
The `--preserveConstEnums` flag does exactly this.

**Comment by sccolbert** [comment]
Perfect. Thanks!
