### ISSUE TITLE
Suggestion: allow hooks after compile

### ISSUE THREAD

**Issue by marjune163** [Microsoft/TypeScript#17639]
Is it possible that each time the .ts file is compiled into .js file, we can have a hook to call a script to make additional process? Currently my problems is, I'm maintaing a classic ASP project which uses JavaScript. I wish to use TypeScript, but after compilation, js codes that runs on server side should be wrapped with `<%` and `%>`. So I wish to have a hook to wrap them.

**Comment by kitsonk** [comment]
You should consider using [the compiler API](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#a-minimal-compiler) for this type of advanced workflow.

Creating a bigger toolchain is not what the TypeScript compiler is about, it is considered a [non-goal](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals#non-goals):

> 4. Provide an end-to-end build pipeline. Instead, make the system extensible so that external tools can use the compiler for more complex build workflows.

Which is already is extensible enough, if you use the compiler API.

**Comment by marjune163** [comment]
Thanks @kitsonk , I will try that.
