### ISSUE TITLE
Local cache for `import { ... } from "..."` in commonjs module (nodejs `require`) mode

### ISSUE THREAD

**Issue by summivox** [Microsoft/TypeScript#17646]
**TypeScript Version:**  2.4.1

**Code**

```ts
import { join } from "path";
console.log(join('abc', 'def'));
```

**Expected behavior:**
```javascript
const path_1 = require("path");
const {join} = path_1;
console.log(join('abc', 'def'));
```

**Actual behavior:**
```javascript
const path_1 = require("path");
console.log(path_1.join('abc', 'def'));
```

-----
So for some perf-critical code I am writing, I started doing this instead (`path.join` is just placeholder --- can be anything imported):

```ts
import * as path from "path";
const {join} = path;
```

This is a lot more verbose, and I end up losing jsdoc descriptions, but at least the import is cached.

I wonder why is the codegen the way it currently is? Are there any difficulties preventing this local caching?

**Comment by HerringtonDarkholme** [comment]
This is for spec compliance. An ES6 export is, roughly, a reference pointing to the module variable/function. Changing the value inside module also impacts other modules that import the symbol.

Consider this example:

```ts
// a.ts

export var a = 1;
export function incr() { a++; }

// b.ts 
import {a, incr} from 'a'
a // 1
incr() 
a // 2
```

Changing variable value in module a also impacts module b. So TypeScript must transpile in this reference style to ensure runtime behavior compatible with spec. Babel also produces similar code.

If you want to improve the output code, you can try webpack's scope hoist optimization or rollup's.

**Comment by aluanhaddad** [comment]
@HerringtonDarkholme is entirely correct. I would add that importing named members from CommonJS modules is a very bad idea.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
