### ISSUE TITLE
Produce #17640's anonymous type declarations from function types

### ISSUE THREAD

**Issue by SamPruden** [Microsoft/TypeScript#17641]
This issue is branching out of discussion in #17636, and depends on #17636 and #17640.

Working together, these features aim to eliminate the need for #6606, by providing type switching and filtering within the type system, and making it possible to access the return types of functions.

Type declaration overloads provide all the power of function overloads.

```ts
declare function foo (num: number): {aNumber: number};
declare function foo <T> (other: T): {aDefault: T};
```

can be described by type declaration overloads as

```ts
type Foo <T extends number> = {aNumber: number};
type Foo <T> = {aDefault: T};
```
This proposal is for allowing the conversion of a function type into the equivalent anonymous overloaded type declaration.

```ts
interface Fizz {
    foo (num: number): {aNumber: number};
    foo <T> (other: T): {aDefault: T};
}

// Here we're getting the return type of foo by overload
type ANumber = (typeof Fizz["foo"])<number>;
type ADefault = (typeof Fizz["foo"])<string>;
```

where `typeof Fizz["foo"]` was expanded to

```ts
(
    type <U extends number> = {aNumber: number};
    type <U> = {aDefault: U};
)
```

**Comment by TheOtherSamP** [comment]
The title of this issue is a mess, any suggestions?

**Comment by tycho01** [comment]
Might say 'type functions from function types' following Idris's nomenclature of 'type function' referring to types with generics (takes types, returns a type), but yeah haven't heard that here as much.

**Comment by TheOtherSamP** [comment]
> type functions from function types

That seems pretty confusing to me, given that I'm a filthy casual who's never even read a line of Idris. I've tried something else, not sure if I've actually improved things though.

**Comment by tycho01** [comment]
Yeah, mine sounded pretty rather than clear. Yours sounds clearer.

> Idris

It's barely used afaik, but made some headlines in the Haskell community for doing some things better.

**Comment by mhegazy** [comment]
Looks like this should be in #17640 instead. i am not also convinced that even with #17640, this is possible for the general case. either ways, let's keep the discussion in #17640.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
