### ISSUE TITLE
"'tslib' cannot be found" when 'module' is 'es2015', but not when 'commonjs' 

### ISSUE THREAD

**Issue by papercuptech** [Microsoft/TypeScript#17642]
**TypeScript Version:**  2.4.2

**Code**

_foo.ts_
```ts
export function foo() {}
```
_index.ts_
```ts
import * as foo from './foo'
class Foo {}
class Bar extends Foo {}
```
_tsconfig.json_
```json
{
  "compilerOptions": {
    "module": "es2015",
    "importHelpers": true
  }
}
```
run `tsc`

**Expected behavior:**
No errors

**Actual behavior:**

> index.ts(3,11): error TS2354: This syntax requires an imported helper but module 'tslib' cannot be found.

**Either of these changes prevent error, but don't quite make sense**
* change `compilerOptions.module = 'commonjs'`, or
* comment out first line  in _index.ts_  : `//import * as foo from './foo'`

`npm i tslib` has no effect in any case.

**Why is this a problem?**
Leveraging `webpack` shaking requires `es2015` module output.

**Comment by j-oliveras** [comment]
Add `"moduleResolution": "node"` tp tsconfig.json. `moduleResolution` defaults to `node` if `module` are `commonjs`.

**Comment by papercuptech** [comment]
@j-oliveras thx
