### ISSUE TITLE
async  can use it at Typescript?

### ISSUE THREAD

**Issue by JLBear** [Microsoft/TypeScript#17645]
async function getStockPriceByName(name) {
  return name;
}

error TS2468: Cannot find global value 'Promise'.
test.ts(1,16): error TS2705: An async function or method in ES5/
ES3 requires the 'Promise' constructor.  Make sure you have a de
claration for the 'Promise' constructor or include 'ES2015' in y
our `--lib` option.

{
    "compilerOptions": {
        "target": "es5",
        "experimentalDecorators": true,
         "lib": [
      "dom",
      "es5",
       "es6"
    ]
    }
}

**Comment by ikatyang** [comment]
You have to specify your `tsconfig.json` for `tsc` so that TS can pick up your configs.

```sh
tsc -p path/to/your/tsconfig.json
```

`tsc test.ts` is considered using default settings.

**Comment by JLBear** [comment]
tsc -p ./tsconfig.json

still  erro
![1502074465 1](https://user-images.githubusercontent.com/19929687/29010596-fb35433c-7b5e-11e7-9edc-8b133aa890d9.png)

**Comment by JLBear** [comment]
solved by


{
    "compilerOptions": {
        "target": "es5",
        "experimentalDecorators": true,
         "lib": [
      "dom",
      "es5",
       "es6"
    ]
    },
"files": [
        
        "test.ts"
    ]
}

**Comment by JLBear** [comment]
{
    "compilerOptions": {
        "target": "es5",
        "experimentalDecorators": true,
         "lib": [
      "dom",
      "es5",
       "es6"
    ]
    },
"files": [
        
        "test.ts"
    ]
}

solved
