### ISSUE TITLE
Provide TSX Compiler API example please

### ISSUE THREAD

**Issue by blendsdk** [Microsoft/TypeScript#17649]
Hi,

Would you please provide a simple example of how one should go about creating a custom TSX transformer using the compiler API?

Thank you.

**Comment by kitsonk** [comment]
How to questions should be asked on StackOverflow or in Gitter.

This forum is for bugs or potential bugs with TypeScript.

**Comment by blendsdk** [comment]
My question is really about enhancing the API documentation. We already provide some examples there anyway!

**Comment by kitsonk** [comment]
The [wiki documentation](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API) is open for pull requests.

Creating a custom TSX transformer sounds like a very specific use case, but the documentation already covers how to walk a TypeScript AST.

**Comment by blendsdk** [comment]
Ok thanks for the prompt answer :)
