### ISSUE TITLE
about Union Types demo

### ISSUE THREAD

**Issue by JLBear** [Microsoft/TypeScript#17647]
interface Bird {
    fly();
    layEggs();
}

interface Fish {
    swim();
    layEggs();
}

function getSmallPet(): Fish | Bird {
    // ...

}

let pet = getSmallPet();
pet.layEggs(); // okay

test.ts(11,25): error TS2355: A function whose declared type is neither 'void' nor 'any' must return a value.

{
    "compilerOptions": {
        "target": "es5",
        "experimentalDecorators": true,
         "lib": [
      "dom",
      "es5",
       "es6"
    ]
    }
}

tsc -v
2.4.2

**Comment by HerringtonDarkholme** [comment]
Hi

The error reports `getSmallPet` does not return a value. This is just a demo to illustrate union type,
so implementation part is missing here.

 You can change it to `declare function getSmallPet(): Fish | Bird;` to skip implementation, or adding a dummy implementation is also fine.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
