### ISSUE TITLE
Error when compare enum variables

### ISSUE THREAD

**Issue by ccwf2006** [Microsoft/TypeScript#17652]
**TypeScript Version:**  2.4.2

**Code**

```ts
enum AuthCodeStatus{
  AuthCodeStatusInit = 0,
  AuthCodeStatusCountDown,
  AuthCodeStatusRetry
}

let tmpAuthCodeStatus:AuthCodeStatus = AuthCodeStatus.AuthCodeStatusInit;

//A compilation error occurred!
if(tmpAuthCodeStatus == AuthCodeStatus.AuthCodeStatusCountDown){
  //TODO: disable buttons
}else if(tmpAuthCodeStatus == AuthCodeStatus.AuthCodeStatusRetry){
  //TODO: show retry button
}else{

}
```

**Expected behavior:**
Compile Success! Both of AuthCodeStatus.AuthCodeStatusCountDown and AuthCodeStatus.AuthCodeStatusInit are member of AuthCodeStatus. And I think the type of variable tmpAuthCodeStatus should be AuthCodeStatus.
**Actual behavior:**
[ts] Type 'AuthCodeStatus.AuthCodeStatusInit' is not comparable to type 'AuthCodeStatus.AuthCodeStatusCountDown'.  
The type of tmpAuthCodeStatus was AuthCodeStatus.AuthCodeStatusInit.

**Comment by SaphuA** [comment]
I also get an error when I try to compare a declared enum to another enum, like this:
```ts
let a = SortDirection.ascending;
if (a == SortDirection.descending) {
    console.log("test");
}
```
This throws `error TS2365: Operator '==' cannot be applied to types 'SortDirection.ascending' and 'SortDirection.descending'.`.

However I think typescript is trying to help you because the condition (just your like your two if-statements) will never be true anyway.

**Comment by RyanCavanaugh** [comment]
The compiler can "see" that the variable still has the `AuthCodeStatusInit` value and thus can never be `AuthCodeStatusCountDown`. In general people don't write always-true or always-false conditions on purpose, so this is an error.

You may be running into one of the issues described in #9998 if this is taking place with a nonlocal write, etc.
