### ISSUE TITLE
Generic parameter type is not enforced

### ISSUE THREAD

**Issue by ownerer** [Microsoft/TypeScript#17655]
**TypeScript Version:**  2.4.0

**Code**

```ts
class Base<TParams> {
	private params: TParams; //cfr https://github.com/Microsoft/TypeScript/issues/1396
}
class Params {
	constructor(public test: string) {
		
	}
}
class Component extends Base<Params> {

}

function testInference<TParams>(component: Base<TParams>, params: TParams) {

}

var component = new Component();

testInference(component, {  });
```

**Expected behavior:**
The second parameter of the call to the "testInference" function should be coerced to be of type "Params".

**Actual behavior:**
Any type of variable can be passed.

**Comment by sylvanaar** [comment]
You problem is that you pass 2 types for TParams and {} can be a supertype of Params so it is used.

```Typescript
var v1 : {} = new Params("foo")
```

If the types are incompatible, then the first match from left to right is used:

```Typescript
class Base<TParams> {
	private params: TParams; //cfr https://github.com/Microsoft/TypeScript/issues/1396
}
class Params {
	constructor(public test: string) {
		
	}
}
class Component extends Base<Params> {

}

function testInference<TParams>(component: Base<TParams>, params: TParams) {

}

function testInference2<TParams>(params: TParams, component: Base<TParams>) {

}

var component = new Component();

testInference(component, { foo:1 });   // Error on foo
testInference2({ foo:1 }, component);  // Error on component
```

**Comment by ownerer** [comment]
What do you mean I'm "passing" 2 types for TParams"?
Clearly the type of TParams should be inferred from the first argument passed to the function, no?
And since that argument is of type "Component" and that type inherits "Base<Params>", I would expect the compiler to force every subsequent parameter that uses TParams in its type definition somehow to force it to be the same type as the firsts parameter that uses it, ie: defines it.
In this case: Params class.

**Comment by ajafff** [comment]
@ownerer you are looking for #14829

**Comment by ownerer** [comment]
Ha, well what do you know!
Thanks @ajafff !

Changing
```
function testInference<TParams>(component: Base<TParams>, params: TParams) {

}
```

To
```
function testInference<TParams>(component: Base<TParams>, params: TParams & {}) {

}
```

Works!

**Comment by ownerer** [comment]
I wanted to get back to this again.
While the suggested solution works, I fail to see why the "& {}" intersection should ever be explicitly written in the first place.
Shouldn't this be the default behavior?
Or in other words: can anyone tell me why or in which scenario(s) the observed behavior without the "& {}" intersection would ever be intended/useful?

**Comment by sylvanaar** [comment]
Here is a nicer way of writing it

```Typescript
class Base<TParams> {
	private params: TParams; //cfr https://github.com/Microsoft/TypeScript/issues/1396
}
class Params {
	constructor(public test: string) {
		
	}
}
class Component extends Base<Params> {

}

type InferLast<T> = T & {}

function testInference<TParams>(component: Base<TParams>, params: InferLast<TParams>) {

}

function testInference2<TParams>(component: Base<InferLast<TParams>>, params: TParams) {

}

var component = new Component();

testInference(component, { });   // Error on foo
testInference2(component, { foo:1 });  // Error on component
```

**Comment by ownerer** [comment]
Hmmmm, ok, thanks for the clarification.
I understand now what you originally meant by passing 2 types for TParams!

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
