### ISSUE TITLE
Expose ContextEvent in TS Server Protocol

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#17659]
**Feature Request**
The `ContextEvent` is currently exposed in the tsserver library but not in the TSServer protocol. For VS Code, we'd also like this event to be exposed in the protocol

**Comment by sheetalkamat** [comment]
I think needs to be handled in https://github.com/Microsoft/TypeScript/pull/17269 to ensure that we can update the error list correctly.
