### ISSUE TITLE
strictNullChecks fails in combination with noImplicitAny (possibly in combination with webpack?)

### ISSUE THREAD

**Issue by SaphuA** [Microsoft/TypeScript#17651]
#### Repo
I've set up a minimal repo here: https://github.com/SaphuA/ts-noImplicitAny-strictNullChecks

#### Version info:
typescript: 2.4.2
webpack: 3.4.1
ts loader: 2.3.2

#### Issue
The below code is **never** expected to compile when `strictNullChecks` is set to `true`. However, the current behavior is that it **does** compile when `noImplicitAny` is set to `true`.

```ts
let strictNullCheck = null;
if (1 === Number("1")) {
    strictNullCheck = "world";
}
```
<sup>From: https://github.com/SaphuA/ts-noImplicitAny-strictNullChecks/blob/master/js/main.ts#L11</sup>

**Comment by RyanCavanaugh** [comment]
It's sort of a weird interaction between features, but essentially `noImplicitAny` gives the compiler permission to allow a variable to float between types until it's read (at which point we evaluate its implicitness). Without that ability, it's just `null` out of the gate and is "stuck" there.
