### ISSUE TITLE
noImplicitAny seems to be broken (possibly in combination with webpack?)

### ISSUE THREAD

**Issue by SaphuA** [Microsoft/TypeScript#17650]
#### Repo
I've set up a minimal repo here: https://github.com/SaphuA/ts-noImplicitAny-strictNullChecks

#### Version info:
typescript: 2.4.2
webpack: 3.4.1
ts loader: 2.3.2

#### Issue
The below code is **not** expected to compile when `noImplicitAny` is set to `true`.

```ts
let noImplicitAny;
if (1 === Number("1")) {
    noImplicitAny = "hello";
} else {
    noImplicitAny = 1337;
}
```
<sup>From: https://github.com/SaphuA/ts-noImplicitAny-strictNullChecks/blob/master/js/main.ts#L2</sup>

**Comment by RyanCavanaugh** [comment]
The implicit any occurs at the subsequent *read* site of an implicit-any variable. If you actually observed the implicit any:
```ts
export default class Main {
    public foo(): void {
        let noImplicitAny;
        if (1 === Number("1")) {
            noImplicitAny = "hello";
        } else {
            noImplicitAny = 1337;
        }
        return noImplicitAny; // <-----
    }

    public bar(): void {
        let strictNullCheck = null;
        if (1 === Number("1")) {
            strictNullCheck = "world";
        }
    }
}
```
you would see an error

**Comment by SaphuA** [comment]
Thanks for the quick reply. So if this only occurs during read, then why does this code throw an implicit any warning?

```ts
export default class Main {
    private local;
    public foo(): void {
        if (1 === Number("1")) {
            this.local = "hello";
        } else {
            this.local = 1337;
        }
    }
}
```

**Comment by RyanCavanaugh** [comment]
A class field can't be subject to the same kind of flow control analysis (we have no idea what order your methods will be called in). `local` here will always be implicit any for that reason

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
