### ISSUE TITLE
Interface name and SyntaxKind are different for MethodDeclaration and PropertyDeclaration

### ISSUE THREAD

**Issue by gscshoyru** [Microsoft/TypeScript#1766]
This is more of a suggestion than an actual bug -- for all of the other corresponding interfaces and syntax kinds (so far) the name of the syntax kind and the name of the corresponding interface are the same (for instance IfStatement, ClassDeclaration, etc). This makes it very easy to find the other one when coding using language services, which is great. But for some reason, the interface MethodDeclaration corresponds to the syntax kind Method, and the interface PropertyDeclaration corresponds to the syntax kind Property, which makes them more difficult to find. I think it might make more sense to have them all be consistent, to make them easier to find and easier to code with. What do you guys think?

**Comment by CyrusNajmabadi** [comment]
@gscshoyru Yup.  We should def do that.  I tried to unify things a while back, but it looks like i missed a couple of cases.  Thanks!

**Comment by gscshoyru** [comment]
Found another -- Constructor is the syntax kind and ConstructorDeclaration is the interface.

**Comment by gscshoyru** [comment]
And one more -- TypeAssertion is the interface and TypeAssertionExpression is the syntaxKind

**Comment by mhegazy** [comment]
A PR would be welcomed.

**Comment by mhegazy** [comment]
this should be fixed now.
