### ISSUE TITLE
Can't reassign to properties of mapped type with "key in keyof typeof Enum"

### ISSUE THREAD

**Issue by HASHIMOTO-Takafumi** [Microsoft/TypeScript#17676]
**TypeScript Version:**  2.4.2

**Code**

```ts
enum Enum {
    foo,
}

let a: { [key in keyof typeof Enum]: number } = { foo: 0 };

a.foo++;
```

**Expected behavior:**

Should compile.

**Actual behavior:**

Results in compilation error:

```
test.ts(7,3): error TS2540: Cannot assign to 'foo' because it is a constant or a read-only property.
```

It seems this behavior is appropriate for **readonly** mapped type.

**Comment by aluanhaddad** [comment]
`enum` keys are immutable and mapping them preserves this property. I'm not sure what the purpose of the type annotation is in the example. Why not write
```ts
enum Enum {
    foo,
}

let a = {...Enum};
```

**Comment by HASHIMOTO-Takafumi** [comment]
Oh you've solved my whole problem, thanks!
