### ISSUE TITLE
Class 'IonicNamespace' incorrectly implements interface

### ISSUE THREAD

**Issue by zak0094** [Microsoft/TypeScript#17672]
<!-- QUESTIONS: 

Hey guys, does anybody here have any idea what the following means?

             typescript: node_modules/Ionic/dist/commands/index.d.ts, line: 2
            Class 'IonicNamespace' incorrectly implements interface 'IRootNamespace'. Types of 
              property 'root' are
            incompatible. Type 'boolean' is not assignable to type 'true'.

**TypeScript Version 2.4.2 / nightly (2.5.0-dev.201xxxxx)

**Code**

The error comes from this part of the Nd modules
// index.d.ts
import { CommandMap, INamespace, Namespace } from '@ionic/cli-utils';
export declare class CordovaNamespace extends Namespace implements INamespace {
    name: string;
    commands: CommandMap;
}

//my app.component

import { LoginPage } from './../pages/login/login';
import { AuthProvider } from './../providers/auth/auth';
import { firebaseConfig } from './app.module';
import { AngularFireModule } from 'angularfire2';
import { Component } from '@angular/core';
import { Platform} from 'ionic-angular';
import { StatusBar } from '@ionic-native/status-bar';
import { SplashScreen } from '@ionic-native/splash-screen';
import { HomePage } from '../pages/home/home';
import firebase from 'firebase/app';

@Component({
  templateUrl: 'app.html'
})
export class MyApp {
  rootPage:any='home';
 
  constructor(
     platform: Platform,
     statusBar: StatusBar,
     splashScreen: SplashScreen,
    ) {

    platform.ready().then(() => {
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      statusBar.styleDefault();
      splashScreen.hide();
    });

  }
}

//app.module
import { EventPage } from './../pages/event/event';
import { AuthProvider } from './../providers/auth/auth';
import { LoginPage } from './../pages/login/login';
import { StatusBar } from '@ionic-native/status-bar';
import { BrowserModule } from '@angular/platform-browser';
import { HttpModule} from '@angular/http';
import { AngularFireDatabaseModule } from 'angularfire2/database';
import { NgModule, ErrorHandler } from '@angular/core';
import { IonicApp, IonicModule, IonicErrorHandler } from 'ionic-angular';
import { MyApp } from './app.component';
import { HomePage } from '../pages/home/home';
// Import the AF2 Module
import { AngularFireModule } from 'angularfire2';
import { SplashScreen } from '@ionic-native/splash-screen';
import { AngularFireAuthModule, AngularFireAuth } from 'angularfire2/auth';
 import firebase from 'firebase/app';
// AF2 Settings
export const firebaseConfig = {

}
@NgModule({
  declarations: [
    MyApp,
  apiKey: "AIzaSyAAeV8WAwydIuAbxr",
    authDomain: "..........",
    databaseURL: "..........",
    projectId: "......",
    storageBucket: "",
    messagingSenderId:
   
  ],
  imports: [
    BrowserModule,
    HttpModule,
     AngularFireModule.initializeApp(firebaseConfig),
    IonicModule.forRoot(MyApp),
    AngularFireAuthModule,
    AngularFireDatabaseModule,
  
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    HomePage,

  ],
  providers: [
    StatusBar,
    SplashScreen,
    {provide: ErrorHandler, useClass: IonicErrorHandler},
    AngularFireAuthModule,
    AngularFireModule, 
    AuthProvider,
  
  ]
})
export class AppModule {}

**Comment by RyanCavanaugh** [comment]
Perhaps it does...

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
