### ISSUE TITLE
Destructuring object breakes IE10

### ISSUE THREAD

**Issue by LKay** [Microsoft/TypeScript#17671]
**TypeScript Version:**  2.4.2

**Code**

There is a code:
```ts
const obj = {
   label : "test"
};

const { label } = obj;
```

**Expected behavior:**

It is transpiled to ES5 (with `"target": "es5"` compiler option). Should work in IE10.

**Actual behavior:**

Destructuring seems to cause inifinite loop over something in IE10, not able to debug anything as the browser just hangs. Looks like there is something wrong with object destructuring as only destructured values causing this:

```ts
console.log(obj.label); // this is working fine and outputs value to the console
console.log(label); // accessing destructured value hangs the browser
```

The same code works without any problems with IE11 and any "normal" browsers (Chrome, FF, Edge etc.).

**Comment by RyanCavanaugh** [comment]
Please log a bug with IE10 unless you can point to something specific wrong with TypeScript's emit.
