### ISSUE TITLE
suggestion insertAdjacentHTML/insertAdjacentText should enumerate the valid string parameters

### ISSUE THREAD

**Issue by BobFrGit** [Microsoft/TypeScript#17679]
**TypeScript Version:**  2.2.2.

It would be nice to have string parameters as typed set of string
```
type insertAdjacentPlace = 'beforebegin' | 'afterbegin' | 'beforeend' | 'afterend'
```

**Comment by mhegazy** [comment]
Should be working as descried, see `InsertPosition`. Fixed by https://github.com/Microsoft/TSJS-lib-generator/pull/246
