### ISSUE TITLE
Keyword "module" is useless

### ISSUE THREAD

**Issue by FlamesoFF** [Microsoft/TypeScript#17687]
So, the keyword "module" is useless in any case, because any modules can be created or loaded without it.
Especially it's confusing during creating external modules.
Suggestion: remove it completely or update the manual to make its usage more clear.

**Comment by RyanCavanaugh** [comment]
If you have specific suggestions the docs please cite. Otherwise we've tried as much as we can to deprecate this, but won't be making a breaking change to remove the keyword completely any time soon.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
