### ISSUE TITLE
No Intellisense for linked library

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/TypeScript#17684]
**TypeScript Version:**  2.4.2

I am not sure if this is an issue with `TypeScript` or `VSCode`, but I created an `npm link`, and typescript doesn't seem to be able to pick up my typings within the linked library. Following the instructions on npmjs.com I did the following:

```
cd /libs/my-awesome-library
npm link
cd /projects/my-awesome-project
npm link my-awesome-library
```

I have a `tsconfig.json` file, in the root of my project:

```json
{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "outDir": "app"
  },
  "files": [
    "src/index"
  ]
}
```

I have tried adding: 
```json
  "include": [
    "node_modules/my-awesome-library/typings/**/*.d.ts"
  ],
```

But I still don't get completions for my library. The only completions that I get are the ones defined in the `js`, which suggests almost everything as `any` when they should be `string`, `object`, `number`, etc.

**Comment by mhegazy** [comment]
you will need a path mapping entry for it: https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
