### ISSUE TITLE
'undefined' substituted for a class type

### ISSUE THREAD

**Issue by tommitytom** [Microsoft/TypeScript#17693]
**TypeScript Version:**  2.4.2

This odd bug has popped up for me that I will most likely find a hacky workaround for (for now), but I really don't have the time to create an isolated test case, and I can't share the code base I'm working on, so I apologise in advance for this very non-verbose error message... it just seemed a bit too whacky to not create an issue for.

**Code**

```ts
import EventRecorder from './eventrecorder';

// ....

if (movement.x !== undefined) {
	this._player.velocity.x = movement.x;
}

if (movement.y !== undefined) {
	this._player.velocity.y = movement.y;
}
```

**Expected behavior:**
```js
if (movement.x !== undefined) {
    _this._player.velocity.x = movement.x;
}
if (movement.y !== undefined) {
    _this._player.velocity.y = movement.y;
}
```

**Actual behavior:**
```js
if (movement.x !== eventrecorder_1.default) {
    _this._player.velocity.x = movement.x;
}
if (movement.y !== eventrecorder_1.default) {
    _this._player.velocity.y = movement.y;
}
```

**Comment by kitsonk** [comment]
It is clear by the code you are writing you are in some sort of closure, as `this` is being rewritten to `_this` (some sort of arrow function).  There is clearly more going on here than meets the eye.  I suspect you are going to have to provide more information and try to reduce the problem.

What intellisense do you get for `undefined` at that location?

**Comment by tommitytom** [comment]
Wow OK I found the issue - it was actually a vscode plugin I was using that automatically adds imports - it added this at the top of my file: `import undefined from './eventrecorder';`!  I'll be logging an issue with them.  Sorry for wasting your time!
