### ISSUE TITLE
Support assignment in typeguard if block

### ISSUE THREAD

**Issue by fdecampredon** [microsoft/TypeScript#1769]
it would be nice to support that kind of construction : 

``` typescript
function myFunction(arr: string | string[]) {
    if (typeof arr === 'string') {
        arr = [arr]
    }
    //arr is now string[]
}
```

It's a common pattern used by library that take options in parameter.
Generally you can pass an array of string or a string if you have a single value, and internally the library will create an array in any case.

**Comment by Deathspike** [comment]
I encountered the same thing. This would be a great addition to avoid unnecessary rewrites when adopting TS.

**Comment by falsandtru** [comment]
+1

**Comment by ivogabe** [comment]
I've opened a PR at #6959.

**Comment by RyanCavanaugh** [comment]
Works now
