### ISSUE TITLE
Indent of function body after multiple params adds extra level of indent

### ISSUE THREAD

**Issue by aozgaa** [microsoft/TypeScript#17699]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

**Code**
Consider the source file
```ts
function foo(
    a: number) {^}
```
where caret is at `^`, and `tsconfig.json` is `{}`. Then hit `<Enter>`.

**Expected behavior:**
source file becomes
```ts
function foo(
    a: number) {
    ^
}
```
**Actual behavior:**
source file becomes
```ts
function foo(
    a: number) {
        ^
    }
```

**Comment by andy-ms** [comment]
Looks similar to #15895.
