### ISSUE TITLE
Resolving union type fails

### ISSUE THREAD

**Issue by andrewcharlton** [Microsoft/TypeScript#17707]
**TypeScript Version:**  2.4.2

**Code**

I'm trying to build a react/redux app using typescript.  To try and keep my actions typesafe I am using interfaces to define the various action types and their respective payloads and have an overall 'Action' union type of these interfaces. This works *most* of the time, but some actions just don't seem able to resolve.

Minimal example:

```ts
const MEDIA_CHANGE = 'MEDIA_CHANGE';
interface MediaAction {
  type: typeof MEDIA_CHANGE;
  media: string;
}

type Action = MediaAction | OtherAction0 | OtherAction1 | ... | OtherAction10

const reducer = (state: State = initialState, action: Action): State => {
  switch (action.type) {
    case MEDIA_CHANGE:
      return {
        media: action.media,
        panelVisible: action.media === 'desktop' || state.panelVisible,
      };
  }
}
```

**Expected behavior:**

The reducer should be able to resolve the type of the Action correctly - each has a unique 'type' field, and this does work *most* of the time.

**Actual behavior:**

It fails to compile with the following error:
```
error TS2339: Property 'media' does not exist on type 'Action'.
Property 'media' does not exist on type 'OtherAction5'.
```
which action it picks to resolve to seems fairly random.

**Comment by RyanCavanaugh** [comment]
Kind of obscure but I believe you need
```ts
const MEDIA_CHANGE: 'MEDIA_CHANGE' = 'MEDIA_CHANGE';
```

**Comment by andrewcharlton** [comment]
I've also resolved just by duplicating my strings, (which is what I was trying to avoid in the first place), they're always declared pretty close to each other and it will get flagged up if they don't match.

```
const MEDIA_CHANGE = 'MEDIA_CHANGE';
interface MediaAction {
  type: 'MEDIA_CHANGE'
  media: string;
}
```
