### ISSUE TITLE
Formatter: don't format contents of template string

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#17701]
**TypeScript Version:**  nightly (2.5.0-dev.20170808)

**Code**

```ts
function f(s: string) {
    f(`foo
bar`);
}
```

Cut the contents of the template string and paste them back.

**Expected behavior:**

Back to where you started.

**Actual behavior:**

```ts
function f(s: string) {
    f(`foo
    bar`);
}
```

**Comment by mhegazy** [comment]
I do not see an formatting calls.. i only see VSCode seding us an addition of new text..

<pre>
[Trace  - 2:45:11 PM] Sending request: change (1218). Response expected: no. Current queue length: 0
Arguments: {
    "file": "c:/test/a.ts",
    "line": 2,
    "offset": 8,
    "endLine": 2,
    "endOffset": 8,
    "insertString": "foo\r\nbar"
}
[Trace  - 2:45:11 PM] Sending request: change (1219). Response expected: no. Current queue length: 0
Arguments: {
    "file": "c:/test/a.ts",
    "line": 3,
    "offset": 1,
    "endLine": 3,
    "endOffset": 1,
    "insertString": "    "
}
</pre>

looks like a VSCode issue.. @mjbvz can you take a look

**Comment by mjbvz** [comment]
Thanks. Yes, looks like this is a bug with our indentation rules. Tracked by https://github.com/Microsoft/vscode/issues/19420
