### ISSUE TITLE
I can access a private variable but don't get an typescript error 

### ISSUE THREAD

**Issue by kevincam3** [Microsoft/TypeScript#17717]
![typescript-no-error-accessing-private-property](https://user-images.githubusercontent.com/870934/29167528-21107880-7da1-11e7-88ac-2e0ca727c1fa.png)
**TypeScript Version:**  2.4.2 

**Code**
import {Component, OnInit} from '@angular/core';

@Component({
    selector: 'app-servers',
    template: './servers.component.html',
    styleUrls: ['./servers.component.css']
})
export class ServersComponent implements OnInit {
    private allowNewServer: boolean = false;

    constructor() {
        setTimeout(() => {
            this.allowNewServer = true;
        }, 2000);
    }

    ngOnInit() {
    }

}

```ts
// A *self-contained* demonstration of the problem follows...
See [screenshot](url

)
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**Expected behavior:**
Typescript Error message that I'm using a private variable

**Actual behavior:**
No Warning

**Comment by jcalz** [comment]
The TypeScript compiler doesn't read HTML files, so it has no idea that you're accessing a private property.

**Comment by kevincam3** [comment]
Let me present the problem differently. I moved the code into the .ts file so you can see that it flags the error with the variable by itself and it doesn't when I use not. See both screenshots
![typescript-error-without-not](https://user-images.githubusercontent.com/870934/29173123-a47f68fe-7db8-11e7-9a93-01bff02914ef.jpg)
![typescript-no-error-with-not](https://user-images.githubusercontent.com/870934/29173152-bd5bdf9c-7db8-11e7-9e27-a906c34002d2.jpg)

**Comment by andy-ms** [comment]
From TypeScript's perspective, that's just part of a string literal. You might be using some Angular tool that gives you additional errors.

**Comment by kevincam3** [comment]
ok, I'll reach out to the Angular team. Thanks

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
