### ISSUE TITLE
Index expression arguments in 'const' enums must be s/of type 'string'/a string literal/

### ISSUE THREAD

**Issue by zhuravlikjb** [Microsoft/TypeScript#1771]
"Index expression arguments in 'const' enums must be of type 'string'"

This error message is quite ambiguous:
![type_string](https://cloud.githubusercontent.com/assets/4499495/5855689/19088796-a24c-11e4-9c29-0f1abfee01b4.png)

Seems that it should be
"Index expression argument of 'const' enum must be a string literal"

Because the compiler does so:
```javascript
if (isConstEnumObjectType(objectType) && node.argumentExpression && node.argumentExpression.kind !== SyntaxKind.StringLiteral) {
  error(node.argumentExpression, Diagnostics.Index_expression_arguments_in_const_enums_must_be_of_type_string);
}
```

**Comment by mhegazy** [comment]
A PR would be appreciated

**Comment by jbondc** [comment]
The message is now "A const enum member can only be accessed using a string literal.", looks good to me.

**Comment by iamisti** [comment]
If somebody has the same problem, just try to remove 'const' and everything will just work.
Well it's not entirely true, you have to do something like:



```javascript
enum MyEnum{ 
    A, B, C
}

let index = 2;

// this is how you can get the value from the enum without haveing tslint error message.
(<any>MyEnum)[index]
```
