### ISSUE TITLE
btw querySelector can return null

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#17729]
`element.querySelector` is returning `null | Element` per https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector

the definition has it:
```
interface NodeSelector {
    querySelector<T extends Element>(selectors: string): T;
}
```

please fix

**Comment by aluanhaddad** [comment]
Gotta love the DOM APIs...

**Comment by arjunyel** [comment]
What version of TS are you running? Looks like the current definition has it correct https://github.com/Microsoft/TSJS-lib-generator/blob/master/baselines/dom.generated.d.ts#L13745

**Comment by aleksey-bykov** [comment]
appears fixed
