### ISSUE TITLE
Incorrect type narrowing when variable of enum type is changed in another function

### ISSUE THREAD

**Issue by zenwarr** [Microsoft/TypeScript#17748]
**TypeScript Version:**  2.5.0
I've checked the code with the latest TS compiled from the master branch of this repository as well with 2.4.0 version, and behavior is the same on both.

**Code**

```ts
enum E {
  A, B, C
}

let value: E = E.A;

function change(): void {
  value = value === E.A ? E.B : E.A;
}

function func(): void {
  if (value === E.A) {
    change();

    if (value === E.B) {
      console.log('B');
    }
  }
}
```

**Expected behavior:**
No errors. It looks like a perfectly valid code to me.

**Actual behavior:**
Compiler gives the following error on line 15 (where the value is compared to E.B): error TS2365: Operator '===' cannot be applied to types 'E.A' and 'E.B'.
The error disappears if the code of 'change' function is inlined into 'func'.

**Comment by RyanCavanaugh** [comment]
Duplicate #9998
