### ISSUE TITLE
Deduplicate Type Emit

### ISSUE THREAD

**Issue by aozgaa** [microsoft/TypeScript#17746]
**TypeScript Version:**  master, commit f64b8ad902087

We currently implement the ability to serialize types into "text" in two ways:
1) Generate an AST for the type and emit: this was added to support writing quickfixes in terms of manipulating AST's in #14709 and #15790.
2)  [`SymbolDisplayBuilder`](https://github.com/Microsoft/TypeScript/blob/master/src/compiler/types.ts#L2663): this is used for quickinfo requests, where we need to annotate text with a kind so the editor can colorize the quickinfo.

(De-duplicating printing from AST's via the emitter and declaration emitter is **not** part of this issue).

We could remove the second of these if we could emit display parts with the emitter, which involves making the emitter work with a [`DisplayPartsSymbolWriter`](https://github.com/Microsoft/TypeScript/blob/master/src/services/utilities.ts#L1114), possibly extending it to include write events for each [`SymbolDisplayPartKind`](https://github.com/Microsoft/TypeScript/blob/c110ecb870c940610b5652a5ba31e8cb507e258c/src/services/types.ts#L556) and cleaning up the emitter to be consistent in calling the correct `writeX` methods on the writer.

**Comment by weswigham** [comment]
I believe we also plan on wanting to remove the `SymbolDisplayBuilder` once the declaration emitter is replaced with a tree transform, since that _also_ uses it still.

**Comment by weswigham** [comment]
This is done - the `SymbolDisplayBuilder` is no more.
