### ISSUE TITLE
Fetch API Missing Redirected Property

### ISSUE THREAD

**Issue by arjunyel** [Microsoft/TypeScript#17758]
**TypeScript Version:**  2.4.2

**Code**

```ts
fetch('flowers.jpg').then(function(response) {
  if(response.redirected) {
//  Property 'redirected' does not exist on type 'Response'.
    return response.blob();
  }
  throw new Error('Request was not redirected!.');
});
```

**Expected behavior:**

The response from a fetch API request has a redirected property per [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Response/redirected)

**Actual behavior:**

The definition does not exist

**Comment by kitsonk** [comment]
Just to note it was only recently added to the [living standard](https://www.chromestatus.com/feature/6667148676038656).  It is not present in Edge.
