### ISSUE TITLE
Apart from watching config file for the project updates, we probably should also watch extended config file

### ISSUE THREAD

**Issue by sheetalkamat** [microsoft/TypeScript#17753]
Creating the bug for TODO from PR https://github.com/Microsoft/TypeScript/pull/17269

**Comment by fis-cz** [comment]
TS3.4 is still not watching for changes in extended config file.

**Comment by 12wrigja** [comment]
I filed the issue above as this is greatly affecting TypeScript developers at Google. We use the tsconfig 'extends' feature to reference other tsconfig generated by the build system, and not having editors update as the build system updates confuses people who are used to this "just working".

If someone can provide pointers on how this might get fixed I'd be more than happy to have a go at writing a PR for it if it were to be accepted.

**Comment by molisani** [comment]
Having issues with this lack of file watching for the `extends` file as well. For anyone investigating or working on a solution, here is [a simple repro](https://github.com/molisani/tsc-watch-extends-repro) for this issue.
