### ISSUE TITLE
Generic type arguments should use the most specific possible type

### ISSUE THREAD

**Issue by aj-r** [Microsoft/TypeScript#17761]
**TypeScript Version:**  2.4.0

**Code**

I have this function definition.

```ts
forEach<T, TList extends ArrayLike<T> | null | undefined>(
    collection: TList,
    iteratee?: (value: T, index: number, collection: ArrayLike<T>) => any;
): TList;
```

The idea is that the function iterates over each item in the array, then returns the array. However, type inference isn't working for the `iteratee` callback:

```ts
forEach([1, 2, 3], (value, index, collection) => {
    // value has type {}; expected number
    // collection has type ArrayLike<{}>; expected ArrayLike<number>
});
```

**Expected behavior:** the `T` parameter should be taken as `number`.

**Actual behavior:** the `T` parameter is taken as `{}`.

I found two workarounds that exhibit the expected behavior:

```ts
forEach<T>(
    collection: ArrayLike<T> | null | undefined,
    iteratee?: (value: T, index: number, collection: ArrayLike<T>) => any;
): ArrayLike<T> | null | undefined;
```

```ts
forEach<T, TList extends ArrayLike<T> | null | undefined>(
    collection: TList & (ArrayLike<T> | null | undefined),
    iteratee?: (value: T, index: number, collection: ArrayLike<T>) => any;
): TList;
```

The former workaround isn't great because the return type isn't quite right. The latter works, but I'm surprised that ` & (ArrayLike<T> | null | undefined)` has any effect on how `T` is chosen. I would expect `T` to be chosen as the same type in all 3 of these scenarios.

I'm pretty sure the issue is caused by having a generic type argument that is based on another generic type argument.

**Comment by aluanhaddad** [comment]
One other workaround seems to be to extract the parameterization into a `type`
```ts
type List<T> = ArrayLike<T> | undefined | null;

declare function forEach<T, TList extends List<T>>(
    collection: List<T>,
    iteratee?: (value: T, index: number, col: List<T>) => any
): List<T>;

const xs = forEach([1, 2, 3], (value, index, collection) => {
    console.log(value.toFixed());
    // value has type {}; expected number
    // collection has type ArrayLike<{}>; expected ArrayLike<number>
});
```

**Comment by aj-r** [comment]
@aluanhaddad That's effectively the same thing as my first workaround, but it has the same issue where the return type isn't quite right. For example, if the `collection` has type `number[]`, then the function's return value should also be type `number[]` (not `ArrayLike<number> | undefiuned | null`), because the function returns `collection`.

**Comment by aluanhaddad** [comment]
That was a typo actually I meant to write `: TList`

**Comment by mhegazy** [comment]
Constraints are not an inference position. they are used to to check a constraint after the inference has occurred. not doing so runs  into recursion problems.

You have two options here,:

1. infer twice, once for `T` and once for `TList` using intersection, e.g.:

```ts
declare function forEach<T, TList extends ArrayLike<T> | null | undefined>(
    collection: TList & ArrayLike<T>,
    iteratee?: (value: T, index: number, collection: ArrayLike<T>) => any
): TList;

```

2. use indexed access type to get to the element type:

```ts
declare function forEach<TList extends ArrayLike<any>>(
    list: TList,
    iteratee?: (value:TList[0], index: number, collection: ArrayLike<TList[0]>) => any
): TList;
```


that does not solve the `| null | undefined` case though, but for these, i would recommend using an overload:
```ts
declare function forEach<T extends null | undefined>(
    collection: T,
    iteratee?: (value: never, index: number, collection: ArrayLike<never>) => any
): T;
declare function forEach<T, TList extends ArrayLike<T> | null | undefined>(
    collection: TList & ArrayLike<T>,
    iteratee?: (value: T, index: number, collection: ArrayLike<T>) => any
): TList;
```

**Comment by aj-r** [comment]
Yeah for now I've solved this using overloads. If there are technical reasons why this isn't possible then I'm fine with closing.
