### ISSUE TITLE
Classifier is very slow for comments

### ISSUE THREAD

**Issue by JsonFreeman** [Microsoft/TypeScript#1776]
Open src/compiler/checker.ts, find a comment, and start typing in the comment. Notice it does not classify the comment until I have reached a pause in my editing.
![slowcommentclassification](https://cloud.githubusercontent.com/assets/8052525/5866076/eff056ee-a242-11e4-8447-92587c0045c9.gif)

**Comment by DanielRosenwasser** [comment]
I don't think this could be the lexical classifier - this is definitely too slow. I think this is instead an issue with the fact that we are depending on the syntactic classifier, and that the lexical classifier isn't getting called here at all.

@paulvanbrenk may be able to give better detail.

**Comment by paulvanbrenk** [comment]
That's the syntactic classifier, same happens when typing the name for a new class.
