### ISSUE TITLE
Can we define a ReadOnly interface directly?

### ISSUE THREAD

**Issue by zheeeng** [Microsoft/TypeScript#17769]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

**Code**
There three ways we can define a readonly type or interface.

```ts
// First
type ReadonlyState = Readonly<{
  foo: string,
  bar: string,
}>

// Second
interface ReadonlyState2 {
  readonly foo: string,
  readonly bar: string,
}

// Third
interface State3 {
  foo: string,
  bar: string,
}

type ReadonlyState3 = Readonly<State3>
```

The first one we can get the readonly type directly and it's easy to writing.
The second one, we can get the readonly interface, but if there are more properties we have to repeatedly declare its readonly modifier.
The third one, we can get the readonly interface directly, it assign a non-readonly interface to a type. And the State3 seems should be eliminated.

**Whether we have a way to define a readonly interface just like the first way does?**

I expect to define a React State interface directly which is readonly.

**Comment by RyanCavanaugh** [comment]
One might imagine it being possible to write
```ts
readonly interface Foo {
  a: number;
}
```

**Comment by mhegazy** [comment]
We have discussed this in the past, and felt the right approach here should be `readonly` type operator.. this is tracked by https://github.com/Microsoft/TypeScript/issues/10725

**Comment by mhegazy** [comment]
closing in favor of https://github.com/Microsoft/TypeScript/issues/10725
