### ISSUE TITLE
Breaking on DefinitelyTyped (regression)

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#17763]
It had worked until dev0803.

**TypeScript Version:**  nightly (2.5.0-dev.20170808)

**Code**

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/prismjs/index.d.ts

**Expected behavior:**

no error.

**Actual behavior:**

```
TypeScript error: node_modules/@types/prismjs/index.d.ts(154,5): Error TS2411: Property 'extend' of type '(id: string, redef: LanguageDefinition) => LanguageDefinition' is not assignable to string index type 'LanguageDefinition'.
TypeScript error: node_modules/@types/prismjs/index.d.ts(165,5): Error TS2411: Property 'insertBefore' of type '(inside: string, before: string, insert: LanguageDefinition, root: LanguageDefinition) => any' is not assignable to string index type 'LanguageDefinition'.
```

**Comment by Kovensky** [comment]
I've seen that problem somewhere else before, with an older compiler, where the compiler expects all explicitly-declared keys of an object with an index to all behave like index elements (which kinda defeats the purpose of explicitly declaring anything besides the index). I don't remember where though...

**Comment by pocesar** [comment]
lodash `filter` is breaking as well with `Type '(recpt: Recipient) => boolean | undefined' has no properties in common with type 'Partial<Recipient>'.`

**Comment by falsandtru** [comment]
After all, we have to fix @types to use that with the next version 2.6?

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
