### ISSUE TITLE
await collapses union type

### ISSUE THREAD

**Issue by lslv1243** [Microsoft/TypeScript#17778]
If one type in a union type extends the other, when awaiting a promise with this union type the least specific type is inferred.
In the code below `a` is of type Promise\<C\> and `b` is of type A.

**TypeScript Version:**  2.4.1

**Code**

```ts
type A = { a: number }
type B = { a: number, b: number }
type C = A | B

async function f(): Promise<C> {
    throw ''
}

(async () => {
    const a = f()
    const b = await a
})()
```

**Expected behavior:**
b is of type C

**Actual behavior:**
b is of type A

**Comment by aluanhaddad** [comment]
This is presented a little strangely by the language service but I believe it is correct because
```{ a: number }``` is equivalent to ```{ a: number } | { a: number, b: number}```

**Comment by kitsonk** [comment]
There maybe assignability, [but there seems to be an issue](http://www.typescriptlang.org/play/#src=type%20A%20%3D%20%7B%20a%3A%20number%20%7D%0Atype%20B%20%3D%20%7B%20a%3A%20number%2C%20b%3A%20number%20%7D%0Atype%20C%20%3D%20A%20%7C%20B%0A%0Aasync%20function%20f()%3A%20Promise%3CC%3E%20%7B%0A%20%20%20%20throw%20''%0A%7D%0A%0Afunction%20g()%3A%20C%20%7B%0A%20%20%20%20throw%20''%0A%7D%0A%0A(async%20()%20%3D%3E%20%7B%0A%20%20%20%20const%20a%20%3D%20f()%0A%20%20%20%20const%20b%20%3D%20await%20a%0A%20%20%20%20const%20c%20%3D%20g()%0A%7D)()%0A#src=type%20A%20%3D%20%7B%20a%3A%20number%20%7D%0Atype%20B%20%3D%20%7B%20a%3A%20number%2C%20b%3A%20number%20%7D%0Atype%20C%20%3D%20A%20%7C%20B%0A%0Aasync%20function%20f()%3A%20Promise%3CC%3E%20%7B%0A%20%20%20%20throw%20''%0A%7D%0A%0Afunction%20g()%3A%20C%20%7B%0A%20%20%20%20throw%20''%0A%7D%0A%0A(async%20()%20%3D%3E%20%7B%0A%20%20%20%20const%20a%20%3D%20f()%20%2F%2F%20type%20Promise%3CC%3E%0A%20%20%20%20const%20b%20%3D%20await%20a%20%2F%2F%20type%20A%0A%20%20%20%20const%20c%20%3D%20g()%20%2F%2F%20type%20C%0A%20%20%20%20f().then((d)%20%3D%3E%20%7B%20%2F*%20d%20type%20C%20*%2F%20%7D)%0A%7D)()%0A):

```ts
type A = { a: number }
type B = { a: number, b: number }
type C = A | B

async function f(): Promise<C> {
    throw ''
}

function g(): C {
    throw ''
}

(async () => {
    const a = f() // type Promise<C>
    const b = await a // type A
    const c = g() // type C
    f().then((d) => { /* d type C */ })
})()
```

Only when `await` is used does the type change in a surprising way.

**Comment by RyanCavanaugh** [comment]
Union types of this form behave strangely because we don't "realize" that they're collapsible until we actually go and try to do something with them (e.g. map into a promise return type).

In an ideal world it would just not be legal to write a union type like this, but generic instantiation means there's not always a recognizable line of code associated with the declaration of such a type. For the time being, just... don't write types like that.

**Comment by kitsonk** [comment]
Just to be explicit, I think you are pointing out that:

```ts
type C = { a: number } | { a: number; b: number; };
```

is a _silly_ type (that ideally would be illegal) that causes issues in certain constructs and that really, it should be written as:

```ts
type C = { a: number; b?: number; };
```

and then there would be no issues.
