### ISSUE TITLE
Type guard functions do not narrow within switch/case statements

### ISSUE THREAD

**Issue by subvertallchris** [Microsoft/TypeScript#17777]
**TypeScript Version:**  2.4.2

**Code**

```ts
interface GeneralInterface {
  value: string;
  foo?: true;
  bar?: true;
}

interface FooInterface {
  value: 'FOO';
  foo: true;
}

function guard<T>(broadObject: any, comparison: string) : broadObject is T {
  return broadObject.value === comparison;
}

function passingTestIf() {
  const broadObject: GeneralInterface = { value: 'FOO', foo: true };
  if (guard<FooInterface>(broadObject, 'FOO')) {
    const narrowed = broadObject;
    return narrowed.value === 'FOO';
  }

  return false;
}

function failingTestCase() {
  const broadObject: GeneralInterface = { value: 'FOO', foo: true };
  switch (true) {
    case (guard<FooInterface>(broadObject, 'FOO')): {
      const notNarrowed = broadObject;
      return notNarrowed.value === 'FOO';
    }
  }

  return false;
}

```

**Expected behavior:**

My hope is that the behavior within the body of the `case` would match the body of `if`: the const currently defined as `notNarrowed` should be identified as type `FooInterface`.

**Actual behavior:**

Within the body of an `if` statement, the type guard is evaluated and successfully narrows the object.

![image](https://user-images.githubusercontent.com/4097271/29279156-f1390ca2-80e4-11e7-847b-b8c4252d168c.png)

When evaluated as part of switch/case, the const `notNarrowed` is still seen as a `GeneralInterface`, despite being proven to be the more arrow `FooInterface`.

![image](https://user-images.githubusercontent.com/4097271/29279119-d386af84-80e4-11e7-873b-09e85553b867.png)

Apologies if I am missing anything, I greatly appreciate your time and work!

**Comment by kujon** [comment]
See https://github.com/Microsoft/TypeScript/issues/8934

**Comment by subvertallchris** [comment]
Interesting and unfortunate, but thank you for linking me to that. I tried to find something like that but was unable. Is there any chance that this would be considered for resolution now? I'll leave this open for a maintainer to bring the Closehammer down. Thank you!

**Comment by RyanCavanaugh** [comment]
You can leave a comment in the linked issue. We periodically review them to see if things need to be revisited

**Comment by subvertallchris** [comment]
No problem, I'll close this and comment there. Thanks!
