### ISSUE TITLE
Enum Error after Using tsc --target a.ts. 

### ISSUE THREAD

**Issue by ybchoo** [Microsoft/TypeScript#17775]
enum DoorState
{
Open, Closed, Ajar
}
save as 2_a.ts
Compile using tsc --target es6 2_a.ts
Run using node 2_a.js
Result::
Unexpected reserved word.

**Comment by ikatyang** [comment]
I guess you might execute the wrong file, e.g. `node 2_a.ts`, otherwise can you share your TS/Node version and generated `2_a.js`?

**Comment by ybchoo** [comment]
Yes u r right ikat. I make a mistake. Please kindly delete this post. Thanks.
