### ISSUE TITLE
Transpile of `export enum` should use `export let`?

### ISSUE THREAD

**Issue by ghost** [microsoft/TypeScript#17783]
**TypeScript Version:** nightly (2.5.0-dev.20170808)

Trying to get TypeScript and Babel emits to match.
(Possibly related: #15403)

**Code**

```ts
var E;
(function (E) {
})(E || (E = {}));
```

**Expected behavior:**

```
export let E;

(function (E) {
  E[E["A"] = 0] = "A";
  E[E["B"] = 1] = "B";
})(E || (E = {}));
```

**Actual behavior:**

Uses `export var` instead of `export let`.

**Comment by ggajos** [comment]
@andy-ms @RyanCavanaugh 
Since #15423 is about keeping `var` for global scripts to avoid redeclaration issue. Is this issue still valid?

**Comment by RyanCavanaugh** [comment]
Good catch; I think this now has the desired behavior?

**Comment by RyanCavanaugh** [comment]
This doesn't seem to have affected more than one or two people max.
