### ISSUE TITLE
Feature Request: Intelligence hints auto popup in destructuring syntax 

### ISSUE THREAD

**Issue by zheeeng** [Microsoft/TypeScript#17798]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

**Code**
```ts
interface Params {
    foo: string,
    foobar: boolean,
    bar: number
}

const test: (params: Params) => void = ({ foo, f /* here */ }) => {
}
```

**Expected behavior:**

Before I type anything in the destructuring syntax,   I get hints to input `foo`, `foobar`, and `bar`.

**Actual behavior:**

Only when I type `f`, I get hints to input `foo` and `foobar`. Only when I type `b`, I get hint to input `bar`. I wish I can get the  Intelligence hints before typing anything.

**Comment by aluanhaddad** [comment]
Seems to work in nightly and also in the playground
![image](https://user-images.githubusercontent.com/5034656/29345599-dc8d0658-820d-11e7-8c60-0d79329428cf.png)

**Comment by zheeeng** [comment]
@aluanhaddad Weird, I still can't make that hint popup, tested in vscode latest and online playground.

**Comment by aluanhaddad** [comment]
@zheeeng that is very strange indeed. When I position my cursor before the `f` I see `bar` and `foobar` offered as completions. When I position it after the `f` I see `foobar` offered as a completion. I double checked my typescript version as well.

**Comment by ikatyang** [comment]
@zheeeng 

Have you tried to change your `triggerSuggest` keybinding (for vscode)? The default keybinding (Ctrl+Space) was sometimes eaten by something like IME or system.

**Comment by zheeeng** [comment]
@aluanhaddad @ikatyang Thx for your replies, I solved this problem. When I manually trigger suggestion popup, both vs code and online playground hint me the valid parameters.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
