### ISSUE TITLE
Seems that `LanguageService.getQuickInfoAtPosition`s return type should be `QuickInfo | undefined`

### ISSUE THREAD

**Issue by pd4d10** [Microsoft/TypeScript#17797]
**TypeScript Version:**  2.4.2

**Code**

```ts
import * as ts from 'typescript'
const file = 'test.ts'
const code = 'let a = 1'

const servicesHost: ts.LanguageServiceHost = {
  getScriptFileNames: () => [file],
  getScriptVersion: () => '0',
  getScriptSnapshot: fileName => {
    if (fileName === file) {
      return ts.ScriptSnapshot.fromString(code)
    }
  },
  getCurrentDirectory: () => '/',
  getCompilationSettings: () => ({
    module: ts.ModuleKind.CommonJS,
  }),
  getDefaultLibFileName: () => '//lib.d.ts',
}

const languageService = ts.createLanguageService(
  servicesHost,
  ts.createDocumentRegistry()
)

const quickInfo = languageService.getQuickInfoAtPosition(file, 1)

console.log(quickInfo) // undefined

```

**Expected behavior:**

Seems that `LanguageService.getQuickInfoAtPosition`'s return type should be `QuickInfo | undefined`

**Actual behavior:**

https://github.com/Microsoft/TypeScript/blob/c110ecb870c940610b5652a5ba31e8cb507e258c/src/services/types.ts#L234

**Comment by RyanCavanaugh** [comment]
The TS compiler itself is not yet running under strictNullChecks, so any function might return `undefined`. Some people are adding explicit `| undefined`s but it's not anywhere near universal yet. Hopefully sometime soon we can get the flag turned on.

**Comment by pd4d10** [comment]
Got it. Thanks.
