### ISSUE TITLE
"TS6143 --allowJs is not set" error but only on one setup

### ISSUE THREAD

**Issue by deastr** [Microsoft/TypeScript#17802]
**TypeScript Version:**  2.2

We have several machines with the same Angular 2 + ASP.NET Core 1.6 project on them. All of the setups are similar as far as we can say and one of those VS.NET setups is having this error on build and we couldn't figure out what's different/missing:

```
Error	TS6143	Build:Module './src/common' was resolved to 'D:/MyProject/node_modules/@angular/common/src/common.js', but '--allowJs' is not set.
D:\MyProject\node_modules\@angular\common\index.d.ts	13	
```

The same project builds and runs fine on other setups. Here's what they all have common:

- VS.NET 2017 15.2
- TypeScript 2.2
- .NET SDK 1.0.4

`tsconfig.json` is in the root folder of the project.

**tsconfig.json:**

```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [ "es2015", "dom" ],
    "suppressImplicitAnyIndexErrors": true
  },
  "exclude": [
    "node_modules",
    "wwwroot/Application/Models/Custom/**/*",
    "wwwroot/Application/Models/Generator/**/*",
    "wwwroot/Application/**/*.js",
    "wwwroot/Application/**/*.js.map"
  ]
}
```

What could be wrong with this problematic machine?

**Comment by RyanCavanaugh** [comment]
Seems like you must have different node_modules folder contents. Try setting up a package-lock.json and making sure you have identical NPM modules installed

**Comment by deastr** [comment]
Yes the problem was incomplete node_modules folder. We cleared cache, node_modules and restore clean and it works now.
