### ISSUE TITLE
Subsequent asses have no colour

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/TypeScript#17803]
**TypeScript Version:**  2.4.1

![image](https://user-images.githubusercontent.com/1106823/29314958-6908aa3e-81b8-11e7-83e4-40661352605d.png)

**Comment by ikatyang** [comment]
SyntaxHighlighting-related issue should be tracked in [Microsoft/TypeScript-TmLanguage](https://github.com/Microsoft/TypeScript-TmLanguage/issues).

**Comment by jcalz** [comment]
So that's the plural of "as", is it?  Good thing TS doesn't have the keyword "but".

**Comment by NoelAbrahams** [comment]
Is there someone who could move this? I feel a bit embarrassed.

**Comment by andy-ms** [comment]
Thanks moved to Microsoft/TypeScript-TmLanguage#500.

**Comment by RyanCavanaugh** [comment]
Can't believe there's no donkey emoji 🐎
