### ISSUE TITLE
Allow some comparisons with number literals for number | undefined or number | null with strict null checking

### ISSUE THREAD

**Issue by w0rp** [Microsoft/TypeScript#17801]
**TypeScript Version:**  2.4.2

**Code**

```ts
// strictNullChecks must be enabled for this code for the error to appear.
let x : number | undefined

// You will see an error here, because `x` could be undefined.
if (x > 0) {
}
```

**Expected behavior:**

The above comparison should be allowed, as `undefined > 0` is false.

**Actual behavior:**

You have to change the comparison to `x != null && x > 0`, or similar, with strict null checking on.

**Reasoning:**

I think comparisons with some numbers which can be known at compile time should be allowed, such as `x > 0` where `x` could be `null` or `undefined`. Certain comparisons should still be forbidden, like `x >= 0` where `x` could be `null`.

**Comment by krryan** [comment]
I don't think this should be implemented, and if it were it would cause me to request a `--stricterNullChecks` flag to turn it off again.

**Comment by RyanCavanaugh** [comment]
Consider the health of your future maintainers. When someone comes along and decides to refactor the code, not realizing `x` could be undefined...
```diff
- if (x > 0)
+ if (x <= 0) {
+   // something
+ } else {
   // what you had originally, which will now execute on an undefined 'x'
 }
```
