### ISSUE TITLE
Generic arguments and user defined type guard bug

### ISSUE THREAD

**Issue by cmc19** [Microsoft/TypeScript#17808]
**TypeScript Version:**  2.4.2

**Code**

```ts
interface ITestCase {
    Name: string;
    Num1: number;
    Num2: number;

}

function isTestCase(t): t is ITestCase {
    return true;
}


function ExampleMethod<T, TKey extends keyof T>(obj: T, objKey: TKey, propertyValue: T[TKey]) {
    if(isTestCase(obj) && objKey == 'Num1'){
        obj.Num2 = propertyValue;
    }
    
    return propertyValue;
}
```

**Expected behavior:**
No error
**Actual behavior:**
```
test.ts(15,9): error TS2322: Type 'T[TKey]' is not assignable to type 'number'.
  Type 'T[string]' is not assignable to type 'number'.
```

**Comment by DanielRosenwasser** [comment]
Technically knowing that `objKey` is the string `"Num1"` doesn't necessarily mean that `TKey` is the string `"Num1"`. An instantiation of `TKey` could be `"Num1" | Num2"` even though the runtime value could be more explicit than that.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
