### ISSUE TITLE
"return;" should return void

### ISSUE THREAD

**Issue by evmar** [Microsoft/TypeScript#17817]
Consider this code.  There is no useful way to make it compile without coercions.

```ts
// a function that returns Promise<void>
async function doSomething() {
  // do some async work, without producing a value
}

function foo(): Promise<void> {
  if (1 == 1) return doSomething();
  // 1) If you leave out a 'return' statement, you fail due to missing return.
  // 2) If you add a 'return;' statement, you fail due to
  // Type 'undefined' is not assignable to type 'Promise<void>'
  ???;
}
```

**Comment by andy-ms** [comment]
The error is that you are returning `void` but not `Promise<void>`.
You could change the return type to `function foo(): Promise<void> | void`.
Or, leave the return type as it is and `return Promise.resolve()`.

**Comment by evmar** [comment]
Aaargh I am sorry for the wasted time, I failed to reduce my larger test case to the underlying issue.
