### ISSUE TITLE
Feature request: "Import {*} from 'module'" for auto importing all to local scope without namespacing

### ISSUE THREAD

**Issue by pmunin** [Microsoft/TypeScript#17814]
**TypeScript Version:**  2.4.2
ES6 allows to import all to a namespace ` import * as ns from 'mymodule'`. 

But we'd like to avoid namespace hell in our code and still have all imports but in local scope.

Please add support to import all exports as local scope, without namespace, something like:
`import {*} from 'mymodule'`.

**Code**

```ts
//utils/index.ts
export function doThis(){...}
export class ThisClass {...}

//module1.ts
import {*} from './utils'; 
//all names imported to local scope automatically, so refactoring (moving across exported names modules) is easy
doThis(); 
new ThisClass();
```

this issue was started  from here #17813

**Comment by DanielRosenwasser** [comment]
We try to avoid anything that deviates from ECMAScript itself nowadays, and so I don't see TypeScript implementing this any time soon. Additionally, I believe ECMAScript specifically avoided this import form because of some of the refactoring and API impact problems that can come about from it.

**Comment by pmunin** [comment]
avoid anything that deviates ES? Lol! Isn't it a purpose of Typescript to be a superset of ES, which extends it with features that make life of developers easier? This is one of those things.

**Comment by kitsonk** [comment]
> If developer needs to move an exported name from one module to another, when this name is used in imported in bunch of other modules?

Well then you have one line to change in a bunch of different modules, instead of every use site.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
