### ISSUE TITLE
Feature request: [implicit] import by default without globals

### ISSUE THREAD

**Issue by pmunin** [Microsoft/TypeScript#17813]
Please add a way to do implicit import of modules to all project's modules.

**Problem**
Let's say I have some often used modules ./utils/index.ts, ./anotherUtils/index.ts ,..., which exports some often used stuff:
```js
//utils/doThis.ts
export function doThis() {...}

//utils/ThisClass.ts
export class ThisClass {...}

//anotherUtils/doThat.ts
export function doThat() {...}

//anotherUtils/ThatClass.ts
export class ThatClass {...}

//utils/index.ts
export * from './doThis'
export * from './ThisClass'

//anotherUtils/index.ts
export * from './doThat'
export * from './ThatClass'

```
I have to use it in all my other modules of my project (including inside ./utils/*.ts, anotherUtils). But I don't want to reveal them globally. Other words I want to have those modules content locally (in local scope, without using module namespaces so it will be easier to refactor and move exported objects across modules).

**Actual behavior**
I have to add import to the header of *every single ts module file* :-1: :disappointed: 
```ts
//module1.ts
import {doThis, ThisClass as C1} from './utils'
import {doThat, ThatClass as C2} from './anotherUtils'
...

//module2.ts
import {doThis, ThisClass as C1} from './utils'
import {doThat, ThatClass as C2} from './anotherUtils'
...

//module3.ts
import {doThis, ThisClass as C1} from './utils'
import {doThat, ThatClass as C2} from './anotherUtils'
...
```
Even more fun starts when some refactoring is needed e.g. moving doThat to other module :angry: :boom: 

**Expected behavior**
There are 2 obvious ways I see to solve that:
1. Specify it in a **tsconfig.json** (similar to "alwaysStrict") - easy to implement, but not that usefull:
```json
{
 compileOptions:{
   implicitImports:[
      {
         locals:[ "doThis", { name:"ThisClass", as: "C1"} ],
         fromModule:"/utils/index.ts",
         exclude: ["/utils/"]
      },
      {
         locals:[ "doThat", { name:"ThatClass", as: "C2"} ],
         fromModule:"/anotherUtils/index.ts"
      }
   ]
 }
}
```
2. allow wildcards for local imports (way more practical IMHO, but may be harder to implement): 
```js
//defaultImports.ts
export * from '/utils';
export * from '/anotherUtils';

//module1.ts
import {*} from './defaultImports'; 
//all names imported to local scope automatically, so refactoring is easy
doThis(); 
doThat();

//module1.ts
import {*} from './defaultImports'; 
doThat();

```
Created separate issue for that #17814 

**TypeScript Version:**  2.4.2

**Comment by aluanhaddad** [comment]
Why not
```ts
// utils.ts
import {doThis, ThisClass as C1} from './utils/index';
import {doThat, ThatClass as C2} from './anotherUtils/index';
export {doThis, doThat, C1, C2};
```
and then consume it as
```ts
//module1.ts
import * as utils from './utils';

const xs = [new utils.C1(), new utils.C2()];

xs.map(utils.doThis).forEach(utils.doThat);
```

**Comment by pmunin** [comment]
This does not solve a problem of refactoring, when you still have to mention in every single file all those hundreds of names, and then if any of the name structure changes you need to go through every single file.

I'm coming from C# where this problem is solved elegantly by namespaces and MsBuild .proj format (allowing to import default references from some template .proj). 
In Typescript namespaces is a joke, only working in non-modular (outFile) mode, which everyone recommends to avoid.

**Comment by RyanCavanaugh** [comment]
I don't see how moving the imports from files to the tsconfig file changes anything. If you don't like namespaces in the global scope and you don't like modules, then there's not really anything left.

I'd advise taking the "import *" proposal to es-discuss. TypeScript isn't going to add new ES6 import forms on its own.
