### ISSUE TITLE
Node.cloneNode returns the wrong type

### ISSUE THREAD

**Issue by kkapsner** [Microsoft/TypeScript#17818]
Node.cloneNode should return the type of "this". Therefore this line
https://github.com/Microsoft/TypeScript/blob/93abebc04af5d443a930ad84258cf2d6101d8513/lib/lib.es6.d.ts#L14166

should be 
```   cloneNode(deep?: boolean): this;```

**Comment by divyamamgai** [comment]
Can I take this up as a starting point?

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by mhegazy** [comment]
One thing to note, we do not want to add `cloneNode(deep?: boolean): this` as this will turn all HTMLElement* interfaces into generic interfaces and increase the cost of checking the standard library. instead we can update the generator to emit a `cloneNode` for every element to return the right type. see https://github.com/Microsoft/TSJS-lib-generator/pull/166 for guidance.

**Comment by HolgerJeromin** [comment]
duplicate of the older ref #283
