### ISSUE TITLE
Missing HTML tags

### ISSUE THREAD

**Issue by inad9300** [Microsoft/TypeScript#17828]
**TypeScript Version:**  2.4.0

The `HTMLElementTagNameMap` interface seems to be missing some HTML tags. From the [list of new HTML5 elements](https://www.w3schools.com/html/html5_new_elements.asp) (I haven't checked anything else), the following are missing:

- `main` (I have noticed because of this element.)
- `bdi`
- `details`
- `dialog`
- ~~`menuitem`~~ (Deprecated.)
- `rp`
- `summary`

**Comment by arjunyel** [comment]
I recently added the dialog element, I'll look into adding the others https://github.com/Microsoft/TSJS-lib-generator/pull/272

**Comment by arjunyel** [comment]
I've also added main, details, and summary https://github.com/Microsoft/TSJS-lib-generator/pull/282

However I'm not sure how to add them to the HTMLElementTagNameMap interface, it seems like this piece of F# code creates it https://github.com/Microsoft/TSJS-lib-generator/blob/master/TS.fsx#L806

**Comment by inad9300** [comment]
I've noticed that MDN has markead [`<menuitem>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/menuitem) (together with [`<menu>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/menu)) as deprecated.

**Comment by inad9300** [comment]
Update: bdi and rp are the only ones missing.

**Comment by inad9300** [comment]
A few SVG tags seem to be missing too from `SVGElementTagNameMap`, in particular a, script, style, and title.

**Comment by tonyhallett** [comment]
@inad9300 they are missing because they are in the HTMLElementTagNameMap and they cannot be in both whilst the deprecated ElementTagNameMap still remains in the definition file

**Comment by inad9300** [comment]
Please, reopen this as per https://github.com/Microsoft/TSJS-lib-generator/pull/609#issuecomment-457818505.

**Comment by inad9300** [comment]
@RyanCavanaugh thanks for taking care of this. Nevertheless, unless you found something new, the problems listed in the comment I linked were rightly dismissed by @saschanaz, and this issue can therefore remain closed. Sorry for the back and forth.
