### ISSUE TITLE
import statement: use imported identifier by default

### ISSUE THREAD

**Issue by mindplay-dk** [Microsoft/TypeScript#1783]
This gets repetitive:

    import Observable = events.Observable;

Is there any practical reason the following shouldn't work?

    import events.Observable;

That is, is there any reason the import statement shouldn't assume you want the imported symbol to retain it's original name in your local scope?

One downside to being forced to explicitly name imported symbols is, if the name of the imported symbol changes (and your import statement is automatically refactored), you end up with a misnamed symbol in your other scripts.

On a related note, it would be nice to have multiple imports with a single statement, e.g. comma-separated:

    import events.Observable, events.Listener;

Most languages allow something like this - for example, the `use` statement in PHP accepts both of these forms of imports.

**Comment by mhegazy** [comment]
I am inclined to say no to this one; there are already numerous overloaded uses for the import syntax, and adding one more would make it more complicated.

**Comment by mindplay-dk** [comment]
I wrote this request before `import {foo} from "bar"` was defined and supported, so it's obsolete :-)
