### ISSUE TITLE
VS2017 version 15.2 - Compile on build

### ISSUE THREAD

**Issue by dazinator** [Microsoft/TypeScript#17830]
**TypeScript Version:**  2.2.2.0 shows up on the VS about page. However under my VS options for typescript:

![image](https://user-images.githubusercontent.com/3176632/29363696-df92ea2c-8288-11e7-8413-be1a1e16429f.png)

**Code**

I have a vs2017 project with a folder called "Scripts" containing a `tsconfig` file that looks like this:

```
{
  "version": "1.8.0",
  "compileOnSave": true,
  "compilerOptions": {
    "noImplicitAny": false,
    "noEmitOnError": false,
    "removeComments": true,
    "sourceMap": false,
    "target": "es5",
    "outFile": "../wwwroot/Reach.GCv3.Mvc.WebApplication/js/tscompiled.js",
    "module": "amd"
  },
  "exclude": [
    "node_modules",
    "wwwroot"
  ]
}
```

If I save a change to any of the typescript files - it correctly produces the outfile - which is good.

However - if delete the generated file, and the re-build the project, the outfile is not generated. I have to save changes to a script file to generate the file again.

**Expected behavior:**

Typescript compilation should run on build?

**Actual behavior:**

Typescript compilation doesn't run on build, even if outputs are not up to date (i.e missing / deleted)

And here is relevent msbuild properties from my csproj file:

```
<Project Sdk="Microsoft.NET.Sdk.Web">
<PropertyGroup>
    <Description>Reach WebApplication</Description>
    <Authors>Darrell.Tunnell</Authors>
    <TargetFramework>net46</TargetFramework>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <AssemblyName>Reach.GCv3.Mvc.WebApplication</AssemblyName>
    <OutputType>Exe</OutputType>
    <PackageId>Reach.GCv3.Mvc.WebApplication</PackageId>  
    <UpdateVersionProperties>true</UpdateVersionProperties>
    <UseLocalGluonProjectReferences>false</UseLocalGluonProjectReferences>
  </PropertyGroup>

```

**Comment by DanielRosenwasser** [comment]
Hey, @dazinator, have you tried this with 15.3 which came out recently?

**Comment by mhegazy** [comment]
closing for now. please reopen if you issue still persists.
