### ISSUE TITLE
Typo in DateConstructor type definition

### ISSUE THREAD

**Issue by tzachshabtay** [Microsoft/TypeScript#17836]
constructor line shows: `year, month, date` when it should show `year, month, day`.

https://github.com/Microsoft/TypeScript/blob/ce2ac1751e044316066286c285818ff2d9cbbca6/lib/lib.es6.d.ts#L785

Same typo also appears in UTC:

https://github.com/Microsoft/TypeScript/blob/ce2ac1751e044316066286c285818ff2d9cbbca6/lib/lib.es6.d.ts#L803

**Comment by RyanCavanaugh** [comment]
This is what the spec calls it: http://www.ecma-international.org/ecma-262/6.0/#sec-date-year-month-date-hours-minutes-seconds-ms
