### ISSUE TITLE
Filter out impossible types in autocompletion for TypeScript comparison based on compared type

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#17837]
_From @sgronblo on August 16, 2017 2:27_

- VSCode Version: Version 1.15.0 (1.15.0)
- OS Version: MacOS 10.12.6 (16G29)

Steps to Reproduce:

1. Here is a sample file, never mind the stupidity or validity of the subject:

```
enum HorseType {
    Striped = 'striped',
    Plain = 'plain',
    Green = 'green'
}

interface Horse {
    type: HorseType
}

interface Zebra extends Horse {
    type: HorseType.Plain
    zooName: string
}

interface DomesticHorse extends Horse {
    type: HorseType.Plain
    horseName: string
}

type NormalHorse = Zebra | NormalHorse

const testZebra: Zebra = {
    zooName: 'Ueno Zoo'
}

function horseIsZebra(horse: NormalHorse): boolean {
    return horse.type === HorseType.<CURSOR_HERE>
}
```
2. The auto completion that shows up at `<CURSOR_HERE>` shows all the three options for `HorseType` even though we know that `horse` being of type `NormalHorse` can only have the values `Plain` or `Zebra`, not `Green`. So, `Green` should be filtered out in this case.

Reproduces without extensions: Yes

_Copied from original issue: Microsoft/vscode#32603_

**Comment by mjbvz** [comment]
_From @sgronblo on August 16, 2017 2:35_

I might add that if you were to pick `Green` in this case you would of course get a compiler error.

**Comment by krryan** [comment]
You gave `Zebra` the type `HorseType.Plain`, and referred to the options of a `NormalHorse['type']` as being `Zebra` or `Plain`. Meanwhile, the actual `HorseType` enum has values `Plain`, `Striped`, and `Green`. I assume you meant to give `Zebra` `type: HorseType.Plain`, and say that `NormalHorse['type']` has the options of `Plain` or `Striped` rather than `Plain` or `Zebra`.

**Comment by RyanCavanaugh** [comment]
This would be both confusing (the completion list, in all languages, is standardly "the real list of members" with no contextual filtering) and potentially very slow (you could have hundreds of members here and we'd have to speculatively typecheck all of them depending on context)
