### ISSUE TITLE
Find all references/rename for a property should include any indexed accesses

### ISSUE THREAD

**Issue by weswigham** [Microsoft/TypeScript#17841]
**TypeScript Version:**  2.4.2 / nightly

**Code**

```ts
interface X {
  member: number;
}

const x: X["member"] = 42;
```

**Expected behavior:**
Find all references on `member` in `interface X`, receive a link to the usage in the type definition for the `const x`. (or vice-versa)

**Actual behavior:**
Does not include the indexed access in the list of usages when triggered via the interface, does not show the interface when triggered via the access.

**Comment by DanielRosenwasser** [comment]
Looks like a regression, probably due to literal types.

**Comment by weswigham** [comment]
Duplicates #17782
