### ISSUE TITLE
Exporting a keyword-named function in a module 

### ISSUE THREAD

**Issue by panuhorsmalahti** [Microsoft/TypeScript#1784]
The type definition file for the Q module has the following problem:

```
 //export function try(method: Function, ...args: any[]): Promise<any>; // <- This is broken currently - not sure how to fix.
```

The compiler doesn't accept the type definition because it thinks a try/catch block is about to begin.

```
q/Q.d.ts(204,21): error TS1006: Identifier expected; 'try' is a keyword.
q/Q.d.ts(204,24): error TS1005: '{' expected.
q/Q.d.ts(204,72): error TS1005: '=>' expected.
```

Is there any way to define this exported function?

**Comment by mikaturunen** [comment]
:+1: 
I need this information also.

**Comment by danquirk** [comment]
This isn't allowed at the moment because JavaScript doesn't allow that pattern either. Presumably Q has actually defined it as something like ```module.exports.try = function() {}```. We could start allowing you to use keywords for ```export var``` names to support this.

In the meantime one workaround would be to use a merged class and module.

```ts
declare class Q {
    static try();
}

declare module Q { }

Q.try();
```
The downside here is that now the type system will think Q has a construct signature and a prototype property.

**Comment by vossad01** [comment]
I also encountered this or a variation thereof.

I was trying to do a literal port of the following JavaScript,

```js
exports.delete = function(args) { ... }
```
but, could not use the following TypeScript

```ts
export function delete(args) { ... }
```

In the end I found the JavaScript version still works in the TypeScript file and had to stick with that for this function.

**Comment by DanielRosenwasser** [comment]
Related is #9846. If I recall, we decided that it was too complex because you can rewrite your module as follows:

```ts
// Exported values go here.
interface X {
    delete(args: any[]): void;
}

// Exported types go here.
declare namespace x {
    interface Foo {
         // ...
    }
}

declare var x: X;
export = x;
```

**Comment by aluanhaddad** [comment]
@vossad01, @DanielRosenwasser I'm curious why not use this instead.
```ts
function del(...args) { }

export { del as delete }
```
