### ISSUE TITLE
deconstruction of the object 

### ISSUE THREAD

**Issue by JLBear** [Microsoft/TypeScript#17854]
let obj = {
    p: [
      'Hello',
      { y: 'World' }
    ]
  };
  
  let { p, p: [x, { y }] } = obj;
 

why 
error TS2459: Type 'string | {
y: string; }' has no property 'y' and no strin
g index signature.???????????

**Comment by aluanhaddad** [comment]
Can you please format your code examples using GitHub flavored markdown?
```markdown
```ts
TypeScript code here
```
```

**Comment by ikatyang** [comment]
The type for property will always be widened (no tuple, no literal type) unless place it in the place contextual type inference is available, e.g.

(original)

```ts
let obj = {
  p: ['Hello', { y: 'World' }],
}; //=> { p: (string | { y: string })[] }

let { p, p: [x, { y }] } = obj;
//                ^ [ts] Type 'string | { y: string; }' has no property 'y' and no string index signature.
```

(solution 1)

```ts
let { p, p: [x, { y }] } = {
  p: ['Hello', { y: 'World' }],
}; // works fine
```

(solution 2)

```ts
function deconstruction({ p, p: [x, { y }] }) {
  // do something
}

deconstruction({
  p: ['Hello', { y: 'World' }],
}); // works fine
```

**Comment by JLBear** [comment]
thanks

**Comment by JLBear** [comment]
thanks
