### ISSUE TITLE
API to tell editor to trigger rename after applying refactoring

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#17852]
**Problem**
Using the new extract method refactoring in TS 2.5, extracted methods currently are always named `newFunction*`. Renaming the extracted method requires a second step after the refactoring as been applied

A better flow would automatically trigger the rename on the new function after the refactoring has been applied.

**Proposal**
In the `getEditsForRefactor` response, return an additional field indicating that an editor should perform another action, such as rename, after the refactor has been applied.

**Comment by mhegazy** [comment]
[`renameLocation`](https://github.com/Microsoft/TypeScript/blob/babb88a0aa4f240baee1264f68e77f1a5be67bfb/src/server/protocol.ts#L491-L495) is not sufficient?

**Comment by mjbvz** [comment]
Thanks! I overlooked this but will give it a try

**Comment by mhegazy** [comment]
Looks like the property is there, but extract method is not setting it correctly. we should just set it be the span of the new function name.

**Comment by mhegazy** [comment]
@andy-ms can you take a look for release-2.5

**Comment by mhegazy** [comment]
After looking at the implementation, this is gonna be harder than we originally thought, so we will try to get this done for 2.5.3 instead.
