### ISSUE TITLE
Feature request: Support for compiler information and version requirements

### ISSUE THREAD

**Issue by hoegge** [Microsoft/TypeScript#17855]
Since the amount of different Typescript versions are now (fortunately) high, it can be a bit hard to keep up with and making sure things are compiled with the right version and finding out, what versions worked. Wouldn't it make sense to have some compiler support for that e.g.:

1) A compiler option that tells `tsc` to output a comment line in the beginning of the js file stating, which version of typescript produced the file and maybe also some of the compiler options, e.g.:
```javascript
// Compiled from Typescript with TSC version 2.4.0 
// target: ES5, Module: commonjs, options: strictNullChecks
```

2) Ability to set the required minimum tsc version number and maybe also maximum (to prevent being compiled by untested versions) in the source file, e.g. by a /// directive:
`/// tscVersion ^1.8.0`
`/// <tscVersion=^2.3.0-2.4.2>`

3) and finally if there was a way to get a constant in the resulting JS that contains the version used for compilation - not sure how to do that in a smart way, but maybe like in C/C++:
In typescript file:
```typescript
/// <define = tscVersion />

console.log("Compiled with Typescript version: "+tscVersion);
```
in JS:
```javascript
const tscVersion = "2.4.2";
console.log("Compiled with Typescript version: "+tscVersion);
```

maybe better as to enable defining all kinds of compiler info supplied by `tsc` in the object `tscInfo`:
```typescript
/// <define = {
    tscVersion: tscInfo.version,
    tscOptions: tscInfo.options
 } />
console.log("Compiled with Typescript version: "+tscVersion);
console.log("Compiled with Typescript options: "+tscOptions);
```
in JS:
```javascript
const tscVersion = "2.4.2";
const tscOptions = "strictNullChecks";
console.log("Compiled with Typescript version: "+tscVersion);
console.log("Compiled with Typescript options: "+tscOptions);
```

**Comment by kitsonk** [comment]
I would be 👍 for some sort of opt-in comment meta-data.  Any runtime emit seems anti-pattern, downstream tooling should rely upon the comment meta data, IMO.

**Comment by mhegazy** [comment]
Can you shed some light on what issues you are running into consuming generated .js files, and how this proposal would address that?

**Comment by kitsonk** [comment]
I was mis-reading a bit when I voiced my support, thinking it was generated `.d.ts` files where we have run into issues trying to manage cross package versioning where sometimes generated `.d.ts` files aren't always compatible with compiler flags and versions.

The only run-time issue in JavaScript where, not the version of TypeScript, but the compiler settings, produces incompatible code is #17088.  I don't know how to easily work around that yet, even if we have the meta data, but it is a real example of incompatible emits.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Comment by hoegge** [comment]
Well, I have not run into issues yet, but since JS code will be interpreted "forever" you might run into issues where some JS does not run. Then it would be nice to know what version it is and what TS compiler version the source was compiled with. About to build a new big enterprise system and fear we will end up in that kind of issues in the future. Is it strictly necessary - probably not - but just like this kind of tracebility, so you can see where things came from.
