### ISSUE TITLE
Generic return type of generic function gets not resolved correctly with *typeof*

### ISSUE THREAD

**Issue by lochbrunner** [Microsoft/TypeScript#17859]
**TypeScript Version:**  2.4.2

**Code**

```ts
function foo<T>(input: T): T {
    if (typeof input === 'number') {
        return 10;
    }
    if (typeof input === 'string') {
        return 'Hallo';
    }
    return input;
}
```

**Expected behavior:**

No compiler error.

**Actual behavior:**

> Type '10' is not assignable to type 'T'.  
> Type '"Hallo"' is not assignable to type 'T'.

**Comment by aluanhaddad** [comment]
`10` is assignable to type `number`.
When the first `if` condition is met, we know that, whatever `T` is, it is also assignable to type `number`.
This does not imply that 10 is assignable to `T`.

**Comment by mhegazy** [comment]
Narrowing currently works on a single variable, i.e. type of `input` inside these blocks would be `number & T` or `string & T`, but it does not narrow related types, i.e. `T` itself to a `number` or `string`. doing such non-local narrowing is fairly expensive.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
