### ISSUE TITLE
Incorrect source map generation with compile on save and outFile in VS2017

### ISSUE THREAD

**Issue by rich-newman** [microsoft/TypeScript#17858]
**BUG** (I think)

Is this the right place for a Visual Studio project issue?  This behavior does not occur with a tsconfig.json, only with VS project properties set to compile the TypeScript.

**TypeScript Version etc:**  
Visual Studio 2017 Community Edition (15.2, 26430.16), TypeScript 2.2.2.0 (in HELP/About in VS), Win 10.

**Code**
No code needed: problem occurs with empty ts file.

**Steps to reproduce:**
- Create a new empty ASP.NET Web Application (.Net framework) project.  I created one in c:\test with 'Create directory for solution' unchecked.
- Add a TypeScript file.  I added the default file1.ts.
- Go to project properties, TypeScript Build, check 'Combine JavaScript output into file:' and make it 'bundle.js'.  Change 'Module system' to AMD or None (or it won't build).
- Build Solution.  It should succeed.
- Show All Files for the project in Solution Explorer.  It should show bundle.js.map.  Open this.  It correctly shows an empty sourceRoot and "file1.ts" in sources.
- Now open file1.ts and save it (click the floppy disk icon).  Compile on save is on, so it should regenerate bundle.js.map.
- Look in bundle.js.map.  sourceRoot is still empty, now sources has some weird path.  

In my case sources has a path of "../../../../../../test/WebApplication1/file1.ts".

**Expected behavior:**
Source shows 'file1.ts' in example above.

**Actual behavior:**
Source shows "../../../../../../test/WebApplication1/file1.ts" with a sourceRoot of "".  There is no path 6 levels deep in the project.

**Workaround**
Using a tsconfig.json with the same settings correctly creates the source map.  Setting a mapRoot of '.' in the VS project properties also seems to fix the problem.

**Comment by RyanCavanaugh** [comment]
I believe this has been fixed; please let me know if you're still seeing the issue. Thanks!
