### ISSUE TITLE
Quick Fix info inconsistent when offering to import a UMD declaration.

### ISSUE THREAD

**Issue by aluanhaddad** [Microsoft/TypeScript#17860]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.20170816)

**To Reproduce:**
```bash
C:\Source\import-quick-fix-issue> npm install -D typescript@next
C:\Source\import-quick-fix-issue> tsc --init
C:\Source\import-quick-fix-issue> npm install --save lodash @types/lodash
C:\Source\import-quick-fix-issue> 'export const chain = _.chain;'> index.ts
C:\Source\import-quick-fix-issue> code-insiders .
```

Open in Visual Studio Code, move cursor to `_`, click the 💡, and observe that the following quick fix info is displayed
![image](https://user-images.githubusercontent.com/5034656/29416790-390c3656-8335-11e7-9303-77ea74c4339a.png)

**Expected behavior:**
If `--allowSyntheticDefaultImports` is `true` the quick fix info remains the same and the result is
```ts
import _ from "lodash";
export const chain = _.chain;
```
If `--allowSyntheticDefaultImports` is `false` the quick fix info changes to
![image](https://user-images.githubusercontent.com/5034656/29416697-f03a3342-8334-11e7-86ae-e2e5480841d5.png)
and the result is
```ts
import * as _ from "lodash";
export const chain = _.chain;
```
**Actual behavior:**

Regardless of the values specified for `--module` and `--allowSyntheticDefaultImports`, the quick fix info is always
![image](https://user-images.githubusercontent.com/5034656/29416790-390c3656-8335-11e7-9303-77ea74c4339a.png)

and the result is always 
```ts
import * as _ from "lodash";
export const chain = _.chain;
```

**Ideal behavior:** 😃

If `--allowSyntheticDefaultImports` is `true` the quick fix info remains the same and the result is
```ts
import _ from "lodash";
export const chain = _.chain;
```
If `--allowSyntheticDefaultImports` is `false` and `--module` is either `commonjs`, `amd`, or `umd` the quick fix info is changed to
![image](https://user-images.githubusercontent.com/5034656/29416889-79c63b92-8335-11e7-9e9d-ecb8d584199d.png)
and the result is
```ts
import _ = require("lodash");
export const chain = _.chain;
```

**Comment by mhegazy** [comment]
PRs welcomed.

**Comment by aluanhaddad** [comment]
In light of #19261, I want to try and take this on if you do not mind.

I would welcome suggestions about where to get started.

**Comment by mhegazy** [comment]
I suppose you will always make it `default` if `--allowSyntheticDefaults` in https://github.com/Microsoft/TypeScript/blob/f8f662d0a197a2b5d276d3c4130ca52d74a1c1b2/src/services/codefixes/importFixes.ts#L623

**Comment by aluanhaddad** [comment]
Great, thank you.
