### ISSUE TITLE
Extract method refactoring not returned when selection is on binary expression operator

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#17869]
**TypeScript Version:**  2.5.0-dev20170816

**Code**

```ts
class Foo {
    bar () {
       return 1 + 1;
    }
}
```

Place cursor on the `+` sign and try triggering refactorings:

![screen shot 2017-08-17 at 12 54 45 pm](https://user-images.githubusercontent.com/12821956/29431003-470a5038-834b-11e7-928d-dd2646d79432.png)

**Expected behavior:**
Extract method for the expression `1 + 1` is returned

**Actual behavior:**
No refactor returned. 

here's the ts server trace

```ts
[Trace  - 12:51:03 PM] Sending request: getApplicableRefactors (14). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/Users/matb/projects/san/castle.js",
    "startLine": 3,
    "startOffset": 17,
    "endLine": 3,
    "endOffset": 17
}
[Trace  - 12:51:03 PM] Response received: getApplicableRefactors (14). Request took 1 ms. Success: true 
Result: []
```

**Comment by amcasey** [comment]
To be honest, I'm surprised it works with any empty selection.  Is this part of a broader request or do you just want support for binary operators?

**Comment by amcasey** [comment]
https://github.com/Microsoft/TypeScript/blob/40e459117aeb0b792a23d6805af884b594dd42c4/src/services/refactors/extractMethod.ts#L169 does the wrong thing for empty spans.  @mjbvz, I'm assuming you'd prefer we attempt to handle empty spans, rather than forbidding them explicitly (which would also resolve the inconsistency in the current behavior).

**Comment by mjbvz** [comment]
With #18060 now fixed, I don't think this request makes sense anymore. It originally struck me as feeling inconsistent but I now think we should require a selection for extracting in this case

**Comment by amcasey** [comment]
Thanks, @mjbvz!  I'll create a PR explicitly disabling that (since there are a few cases where it works by accident).

One other question: what if the selection contains exactly `+`?  Should that work?  Presently, it doesn't.

**Comment by amcasey** [comment]
https://github.com/Microsoft/TypeScript/pull/18427

**Comment by mjbvz** [comment]
Hmm, I don't think so. I'd say that we should require the binary expression itself to be selected for now. If many users start reporting that extract method does not for cases like this, we can always make the rules looser again
