### ISSUE TITLE
CFA doesn't check tuples values with possible null

### ISSUE THREAD

**Issue by cevek** [Microsoft/TypeScript#17864]
**TypeScript Version:**  2.6.0-dev.20170817

**Code**

```ts
var a:[number | null, number, number] = [null, 2, 3];
if (a[0]) {
    a[0] + 1; // Error: Object is possibly 'null'.
}
```

**Comment by mhegazy** [comment]
should be covered by https://github.com/Microsoft/TypeScript/issues/10530

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
