### ISSUE TITLE
Type safety of "this" is potentially misleading in class methods

### ISSUE THREAD

**Issue by nfriend** [Microsoft/TypeScript#1787]
Given the following:

```TypeScript
class TestClass {

    myTestObject = {
        message: 'It worked!',
    }

    myTestMethod() {
        console.log(this.myTestObject.message);
    }
}

var myTestClassInstance = new TestClass();
myTestClassInstance.myTestMethod.apply({});
```

The compiler assumes that the scope of `this` is the instance of the TestClass.  However, if the method is called via `.apply()`, as in the example above, it is possible to hijack the `this` scope of the method.

This is a bit of an edge case, since most TypeScript code shouldn't be circumventing the type safety by using the `.apply()` method.  However, some third-party JavaScript libraries rely on the `.apply()` method, which undermines confidence in the `this` keyword.

The fix is to redefine the method as a property using the fat arrow syntax, i.e.:

```TypeScript
myTestMethod = () => {
    console.log(this.myTestObject.message);
}
```

Perhaps the compiler should only enforce type safety on `this` if the method is defined such that the `this` keyword is lexically scoped?

**Comment by RyanCavanaugh** [comment]
See #15.
