### ISSUE TITLE
Wrong links in Typescript 2.5 RC release

### ISSUE THREAD

**Issue by MNie** [Microsoft/TypeScript#17880]
In release notes for 2.5 RC Visual Studio 2015/17 links point to typescript 2.4.1 instead of 2.5 RC

For VS 2017 there is:
https://download.microsoft.com/download/7/0/A/70A6AC0E-8934-4396-A43E-445059F430EA/2.4.1-TS-release-dev14update3-20170626.1/TypeScript_SDK.exe
But should be:
http://download.microsoft.com/download/7/0/A/70A6AC0E-8934-4396-A43E-445059F430EA/2.5.0-TS-release-dev14update3-20170816.2/TypeScript_SDK.exe

For VS2015 there is:
https://download.microsoft.com/download/6/D/8/6D8381B0-03C1-4BD2-AE65-30FF0A4C62DA/2.4.1-TS-release-dev14update3-20170626.1/TypeScript_Dev14Full.exe
But should be:
http://download.microsoft.com/download/6/D/8/6D8381B0-03C1-4BD2-AE65-30FF0A4C62DA/2.5.0-TS-release-dev14update3-20170816.2/TypeScript_Dev14Full.exe

CC: @DanielRosenwasser

**Comment by mhegazy** [comment]
The download center main download button will always be set to the **last stable** release and not to prereleases. to get the prerelease go to "Details":

![image](https://user-images.githubusercontent.com/8000722/29480897-c6b7c492-8430-11e7-8ce1-17965de8c684.png)

**Comment by MNie** [comment]
Yup, but as a user if I saw a link to download specific version I expected that I download this version instead of the last stable one.
