### ISSUE TITLE
DragEvent should accept a DragEventInit inheriting from MouseEventInit

### ISSUE THREAD

**Issue by WojciechP** [microsoft/TypeScript#17885]
**TypeScript Version:** master, eef7d8b

**Code**

```ts
let ev = new DragEvent('drag', {clientX: 40})
```

**Expected behavior:**
This should typecheck, because the second argument to `new DragEvent` should inherit from `MouseEventInit`: https://developer.mozilla.org/en-US/docs/Web/API/DragEvent/DragEvent

**Actual behavior:**
Typechecking fails, because the typings only allow `dataTransfer` property.

**Comment by kitsonk** [comment]
These typings are imported from files generated by [Microsoft/TSJS-lib-generator](https://github.com/Microsoft/TSJS-lib-generator/).  The contribution guidelines to that are documented [here](https://github.com/Microsoft/TSJS-lib-generator#contribution-guidelines).

**Comment by mhegazy** [comment]
As @kitsonk pointed out. PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by jakebailey** [comment]
Just looking at old issues; this was fixed back in #25944.
