### ISSUE TITLE
`true`| `false` can not be used to create discriminated unions

### ISSUE THREAD

**Issue by sebald** [Microsoft/TypeScript#17882]
**TypeScript Version:**  2.4.2

**Code**

[Link to the playground](https://www.typescriptlang.org/play/##src=type%20One%20%3D%20%7B%0D%0A%20%20kind%3A%20true%3B%0D%0A%20%20foo%3A%20string%3B%0D%0A%7D%20%0D%0A%0D%0Atype%20Two%20%3D%20%7B%0D%0A%20%20kind%3A%20false%3B%0D%0A%20%20foo%3A%20boolean%3B%0D%0A%7D%0D%0A%0D%0Atype%20Options%20%3D%20One%20%7C%20Two%3B%0D%0A%0D%0Aconst%20fn%20%3D%20(options%3A%20Options)%20%3D%3E%20%7B%20%2F*%20...%20*%2F%20%7D%3B%0D%0A%0D%0Aconst%20optionsOne%20%3D%20%7B%20kind%3A%20true%2C%20foo%3A%20'bar'%20%7D%3B%0D%0A%0D%0A%2F**%0D%0A%20*%20ERROR%3A%0D%0A%20*%20Types%20of%20property%20'kind'%20are%20incompatible.%0D%0A%20*%20Type%20'boolean'%20is%20not%20assignable%20to%20type%20'false'.%0D%0A%20*%2F%0D%0Afn(optionsOne)%3B%0D%0A%0D%0A%2F**%0D%0A%20*%20No%20Error.%0D%0A%20*%2F%0D%0Afn(%7B%20kind%3A%20true%2C%20foo%3A%20'bar'%20%7D)%3B)

```ts
type One = {
  kind: true;
  foo: string;
} 

type Two = {
  kind: false;
  foo: boolean;
}

type Options = One | Two;

const fn = (options: Options) => { /* ... */ };

const optionsOne = { kind: true, foo: 'bar' };

/**
 * ERROR:
 * Types of property 'kind' are incompatible.
 * Type 'boolean' is not assignable to type 'false'.
 */
fn(optionsOne);

/**
 * No Error.
 */
fn({ kind: true, foo: 'bar' })
```

**Expected behavior:** Should be possible to use `true | false` to create a discriminated union. It seems like `true | false` and `boolean` are not interchangeable.

**Actual behavior:** TypeScript does not widen the above `kind` to `boolean` and thus `optionsOne` can not be used as input for `fn`. (That's just my wild guess :-x) It's not possible to use `true` and `false` for discriminated unions.

**Comment by ahejlsberg** [comment]
This is working as intended. In the declaration of `optionsOne` you need _some_ indication that you don't want the `kind` property widened. Absent that, the compiler widens the type because a property is a mutable location. You can add a type annotation to indicate your intent:

```ts
const optionsOne: One = { kind: true, foo: 'bar' };
```

Once you have a type annotation the object literal is contextually typed by that annotation and the compiler knows not to widen. For the same reason, there is no error in the call where you directly specify an object literal because the literal is contextually typed by the corresponding parameter type (`Options`) in the function.

**Comment by sebald** [comment]
Thanks for the quick and throughout explanation!

My actual use case for this was that I created typings for a library and wanted to have a strongly typed API. This is the original code that caused this issue:

```ts
// index.d.ts
declare module 'material-ui/List/ListItem' {
  import { ButtonBaseProps } from 'material-ui/internal/ButtonBase';

  interface ListItemCommonProps extends React.LiHTMLAttributes<HTMLLIElement> {
    component?: React.ReactNode;
    dense?: boolean;
    disabled?: boolean;
    disableGutters?: boolean;
    divider?: boolean;
  }

  export type ListItemDefaultProps = {
    button?: false;
  } & ListItemCommonProps;

  export type ListItemButtonProps = {
    button?: true;
  } & ListItemCommonProps &
    ButtonBaseProps;

  export type ListItemProps = ListItemDefaultProps | ListItemButtonProps;

  export default class ListItem extends MaterialUI.Component<ListItemProps> {}
}
```

And even casting didn't help here:

```ts
class DockedDrawer extends React.Component<{}, { docked: boolean }> {
  state = { docked: true }

  render() {
    const docked:true|false = this.state.docked;
    return (
      <Drawer
        anchor="bottom"
        open={true}
        docked={docked}
      >
        List
      </Drawer>
    );
  }
```

I thought I can use discriminated unions to only allow certain `props` on the component, depending on other props.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Comment by michaeljota** [comment]
Hi @sebald maybe if you remove the optional operator from the type, then it would work as you want. You know that the parameter could be either `true` or `false`, however I think this parameter will always exists, even if it doesn't it would simple will be evaluated to a falsy value.
