### ISSUE TITLE
Breaking change v2.5.0 in signature of `ts.matchFiles`.

### ISSUE THREAD

**Issue by rwjblue** [Microsoft/TypeScript#17891]
https://github.com/Microsoft/TypeScript/pull/16646 changed the signature of `ts.matchFiles` in a backwards incompatible way. In the original PR this exact issue was [brought up by @jramsay](https://github.com/Microsoft/TypeScript/pull/16646#discussion_r124415757), but @andy-ms indicated that the entire file was covered by the `/* @internal */` comment at the top.
 
However, this method was exposed on the main entry point without underscore or other indications that it is private (e.g. a simple `import { matchFiles } from 'typescript';` can be used to access it), and is required for implementing the filesystem abstraction logic needed in broccoli-typescript-compiler (and likely other tooling that does not process files in place). 

Cross linking from https://github.com/tildeio/broccoli-typescript-compiler/issues/49.

**Comment by chriskrycho** [comment]
I would add that I can't find any public documentation of `@internal` other than the experimental flag on the compiler, and it's certainly not obvious that this is considered private API. 😢

**Comment by andy-ms** [comment]
I found the following in [`create-parse-config-host.d.ts`](https://github.com/tildeio/broccoli-typescript-compiler/blob/3b0323150f0b4aeaeef7c7792a2c079a5057d2f0/lib/compiler/create-parse-config-host.ts):
```ts
declare module "typescript" {
    interface FileSystemEntries {
        files: string[];
        directories: string[];
    }
    function matchFiles(path: string, extensions: string[], excludes: string[], includes: string[], useCaseSensitiveFileNames: boolean, currentDirectory: string, getFileSystemEntries: (path: string) => FileSystemEntries): string[];
}
```

Without this declaration, the `matchFiles` function would never have been available -- in the compiler we use special `/* @internal */` comments to prevent private functions from leaking into a public API.

**Comment by RyanCavanaugh** [comment]
The produced .d.ts file should be considered the definitive guide to what's available for your use and what isn't. If you have to write a separate declaration in your codebase to expose something that isn't intended for public use, you might get broken without warning.

If you find yourself really wanting access to an internal function, you can log a bug here to request that we remove the `internal` tag. Can't promise we'll accept all of those requests, but it'll (hopefully) prevent this from happening again.

**Comment by rwjblue** [comment]
Thank you both for looking into this.  I didn't realize we had that separate declaration 😞 .

**Comment by krisselden** [comment]
I knew it was private and I asked if it could be made public because supporting include/exclude in a parse config host is difficult without it if you want to virtualize any of the fs. Until then, we will just have to keep adjusting to breakage
