### ISSUE TITLE
breaking change in tsserver public API in ts2.5

### ISSUE THREAD

**Issue by anstarovoyt** [Microsoft/TypeScript#17894]
Hi. I reported several similar issues before. We (WebStorm) use tsserver (in fact tsserverlibrary) integration. [This commit](https://github.com/Microsoft/TypeScript/commit/d99a492ddd7f30450268ed49fa1be308ee43690d#diff-21767a350f9d093aef26a0497b4735c7R20) broke our integration because we have to implement the logger interface manually. 
Can you provide a default logger implementation for avoiding such problems in future?
//cc @andy-ms

**Comment by mhegazy** [comment]
We will get the change reverted, and an @insiders drop released later today.

**Comment by mhegazy** [comment]
`typescript@rc` should now point to `typescript@2.5.1` which has a revert to this change. sorry for the hassle.
