### ISSUE TITLE
Mismatch between tagged v2.5.0 and published v2.5.0

### ISSUE THREAD

**Issue by rwjblue** [Microsoft/TypeScript#17897]
In the source that is tagged on GitHub as v2.5.0 a `/* @class */` annotation is emitted for every transpiled class, but in the version of `2.5.0` that is published to npm the same code does not exist.  This is possibly the result of an incorrect build being published?

### npm contents

This is the contents from `node_modules/typescript/lib/typescript.js` after `npm install typescript@2.5.0`:

![compiled output](https://monosnap.com/file/jCRr4FAC6xrNGbLL1tmwBRN50xUQ43.png)

### github sources

This is the contents of the pre-compiled source under the v2.5.0 tag ([link](https://github.com/Microsoft/TypeScript/blob/v2.5.0/src/compiler/transformers/es2015.ts#L843)):

![source](https://monosnap.com/file/OmaipYy7YUYQwXZc2E0UHdz8HOK11r.png)

**Comment by rwjblue** [comment]
This was identified during an update to broccoli-typescript-compiler (to work around the issue reported in https://github.com/Microsoft/TypeScript/issues/17891).  That project uses typescript's own test cases to confirm that it is working properly.  When we use `typescript@2.5.0` as published to `npm` the output does not match what is checked into this repo under the same tag. Specifically, these `/* @class */` comments are not being emitted, yet the expected test fixtures (in `tests/baselines/reference/project/**/*`) include those comments.

**Comment by mhegazy** [comment]
Ping @DanielRosenwasser

**Comment by DanielRosenwasser** [comment]
Should be fixed; try installing `typescript@rc` or `typescript@2.5.1`
