### ISSUE TITLE
API: moduleHasNonRelativeName is no longer public

### ISSUE THREAD

**Issue by ajafff** [Microsoft/TypeScript#17890]
**TypeScript Version:**  2.5.0

`moduleHasNonRelativeName` was a public API until `typescript@2.4.2` and is now no longer exposed.

Moving `moduleHasNonRelativeName` to `core.ts` implicitly marked it as `@internal`.
The function is deprecated, but the suggested replacement `isExternalModuleNameRelative` is also not available in the declaration files.

**Comment by mhegazy** [comment]
Feel free to send a PR making the helper function public
