### ISSUE TITLE
Extra arguments with defaults get implicit any even with noImplicitAny

### ISSUE THREAD

**Issue by steadicat** [microsoft/TypeScript#17904]
**TypeScript Version:**  2.4.2

**Code**

```ts
function foo(f: (x: number) => void) {}
foo((x, arg = true) => {});
```

Tested in Playground with `noImplicitAny` on.

**Expected behavior:**
Type of `arg` is inferred to be `boolean`, or an error is thrown ("arg implicitly has 'any' type").

**Actual behavior:**
Type of `arg` is `any`, and no error is thrown.

**Comment by mhegazy** [comment]
We need a contextual type before evaluating the expression, since the type of the expression can be impacted by that. we got one from the declaration of `foo`, it did not have a type for `arg`, so it was given a type `any`. 
the fix here is either to give the callback declaration in `foo` a type for `arg`, or give `arg` an explicit type parameter.

**Comment by steadicat** [comment]
Giving `arg` an explicit type works, but I wish there were a way to catch this issue when it's introduced. With `noImplicitAny` set, I was not expecting to have `any` types silently inferred.

**Comment by mhegazy** [comment]
that is fair. an error should have been raised here.

**Comment by falsandtru** [comment]
@mhegazy @sandersn Dup of #17559

**Comment by mhegazy** [comment]
it is, thought this issue is to track raising an error under noImplicitAny, rather than changing the behavior.

**Comment by jakebailey** [comment]
Just looking at old issues; given https://github.com/microsoft/TypeScript/issues/17904#issuecomment-328630467 and the fact that the behavior was changed, the implication is that an implicit any is no longer the desired behavior and therefore no error should appear (so this issue can be closed).
