### ISSUE TITLE
"node" moduleResolution and baseUrl

### ISSUE THREAD

**Issue by NekR** [Microsoft/TypeScript#17909]
**TypeScript Version:**  2.4.2

`moduleResolution: "node"` doesn't honor "baseUrl" option and `moduleResolution: "classic"` doesn't load `index.tsx` from folders when imported. Example:

**Code**

```ts
import Header from 'components/Header';
```

This doesn't work in any case. With `baseUrl` set and `moduleResolution: "classic"` following code works:

```ts
import Header from 'components/Header/index';
```

With `baseUrl` set (being ignored here by some reason) and `moduleResolution: "node"` followin works:

```ts
import Header from '../../components/Header';
```

(`../../` is, in my case, a real location of  the `components` folder from the file importing the `Header`)

**Comment by DanielRosenwasser** [comment]
Can you give a concrete repro?

**Comment by NekR** [comment]
Okay. The config:
```json
{
  "compilerOptions": {
    "module": "es2015",
    "moduleResolution": "classic",
    "sourceMap": false,
    "target": "es5",
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "suppressExcessPropertyErrors": false,
    "jsx": "react",
    "suppressImplicitAnyIndexErrors": true,
    "allowSyntheticDefaultImports": true,
    "rootDir": "./src",
    "outDir": "./output"
  },
  "baseUrl": "./src",
  "exclude": [
    "node_modules"
  ]
}
```

Files structure:
`src/pages/Home/index.tsx`
`src/components/Header/index.tsx`

I try to import `Header` from `Home` as I described in this issue. I also described the situation in which it works and it which it doesn't. The IDE doesn't see the resolution (both VSCode and Sublime Text 3).

I also tried different combinations of using `baseUrl`, `paths`, `rootDir`. All results the same as described in the issue.

I use webpack and `ts-loader` so it compiles just fine when I do `import Header from 'components/Header'` because I adjusted module resolution on webpack's side. Of course IDE doesn't now anything about it so I'm trying to configure it in `tsconfig.json` as it should be for `tsc`.

**Comment by aluanhaddad** [comment]
@NekR  `"baseUrl"` is a property of `"compilerOptions"`.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
