### ISSUE TITLE
Feature request: better type inference of type associated with a union tag

### ISSUE THREAD

**Issue by pelotom** [Microsoft/TypeScript#17915]
### TypeScript version: 2.4.2

Suppose I have this union type:

```ts
type Foo =
  | { tag: 'n'; num: number }
  | { tag: 's'; str: string }
```

and I want to write a function `cast` which will validate that a given member of `Foo` is in fact one of the specific variants, and then give me back the refined type:

```ts
function cast<A extends Foo>(foo: Foo, expectedTag: A['tag']): A {
  if (foo.tag !== expectedTag)
    throw Error(`expected tag ${expectedTag} but was ${foo.tag}`)
  return foo as A
}
```

This all type checks fine, but if I try to use it:

```ts
function tryCast(foo: Foo) {
  const { num } = cast(foo, 'n')
  //      ^^^ Type 'Foo' has no property 'num' and no string index signature.
}
```

In other words, the result of the call to `cast` was inferred to be `Foo` instead of `{ tag: 'n'; num: number }` as one might have hoped. We can certainly fix it by annotating the type parameter

```ts
function tryCast(foo: Foo) {
  const { num } = cast<{ tag: 'n'; num: number }>(foo, 'n')
}
```

but I hope you'll agree this is pretty gross. While `Foo` is certainly a valid thing to infer here, it seems like in general we'd like to infer the most specific type possible when dealing with tagged unions like this. This is just a simple toy example, but I've run up against this issue time and time again in real world development.

**Comment by Meligy** [comment]
A most likely related problem (the same?), is that:

```ts
type IsThisN = Foo & {tag: 'n'};
```
 is equal to
```ts
type IsThisN = ({
    tag: "n";
    num: number;
} & {
    tag: "n";
}) | ({
    tag: "s";
    str: string;
} & {
    tag: "n";
})
```
And it's not just because of equality, even the `extends` case above has the same issue, as we get the same result from:
```ts
type whatIsThis<TFoo extends Foo, TTag extends TFoo['tag']> = TFoo & { tag: TTag };
type isThisN = whatIsThis<Foo, 'n'>;
```

A use case for this is strong typing filters of Redux's Action classes which differ on `type` [property.

More explanation on why this is hard to workaround [here](https://stackoverflow.com/a/46314136/146656).

**Comment by Martaver** [comment]
I've also come across this limitation. Having this style of return type of inference for union types with a discriminant would be very handy for operations like filtering arrays, in rxjs or working with redux.

Casual +1 for this feature.

**Comment by pelotom** [comment]
> Having this style of return type of inference for union types with a discriminant would be very handy for operations like filtering arrays, in rxjs or working with redux.

You might find the [unionize](https://github.com/pelotom/unionize) library to be of interest.

**Comment by RyanCavanaugh** [comment]
@pelotom @Martaver @Meligy conditional types to the rescue!
```ts
type Foo =
  | { tag: 'n'; num: number }
  | { tag: 's'; str: string }


type FindByTag<Union, Tag> = Union extends { tag: Tag } ? Union : never; 

function cast<A extends Foo["tag"]>(foo: Foo, expectedTag: A): FindByTag<Foo, A> {
  if (foo.tag !== expectedTag)
    throw Error(`expected tag ${expectedTag} but was ${foo.tag}`)
  return foo as FindByTag<Foo, A>;
}

function tryCast(foo: Foo) {
  // OK
  const { num } = cast(foo, 'n')
  if (!!!true) {
    // Error
    const { str } = cast(foo, 'n')
  } else {
    // OK
    const { str } = cast(foo, 's')
  }
}
```

**Comment by lll000111** [comment]
@RyanCavanaugh If I may ask, how would that work for an _array_ of expected tags (any one is okay)?

Right now I merged a couple of (similar - same discriminant element) unions using a joined type `type AllMyUnionTypes = Union1 & Union2 & Union3;` (had to find out that I have to use "&" and not "|" to merge several unions).

I have a function that gets a type string as "expectedType" &mdash; _or_ an array of such strings. The single expected tag version works:

```js
function convertMicrodataToObject<K extends keyof AllMyUnionTypes>(
    html: string,
    expectedType: K
): AllMyUnionTypes[K];
```

But I don't know how to achieve a result with an array of possible tags, whatever I try ends up as `never`.

**Comment by maleetz** [comment]
@RyanCavanaugh This just made my day for managing redux actions! Thank you :)

**Comment by Torvin** [comment]
@RyanCavanaugh `FindByTag` works for me until I do this:

type Foo =
  | { tag: 'n' | 'i'; num: number }
  | { tag: 's'; str: string }

then `FindByTag<Foo, 'n'>` returns `never`. Any idea how to fix that? [Tested on](https://www.typescriptlang.org/play/?ssl=8&ssc=26&pln=8&pc=27#code/FAFwngDgpgBAYgewTAvMGMA+MDeMQCGA5gFwwDkAduVhQJbkDcMlArgLZlvsBGUATjAC+6WnkKkKAZyYwpIfmXn86lIsOChIsOKoAmAITAAVYgB4AqpToJKAGhimiAPlQwrNyjCgAPEFEo9KVx8YjInYRgAfndrWxguKAA3AUZNcGgYHzddQKMnM0QEBypyZyA) v3.8.3

**Comment by mrlubos** [comment]
> @RyanCavanaugh `FindByTag` works for me until I do this:
> 
> ```
> type Foo =
>   | { tag: 'n' | 'i'; num: number }
>   | { tag: 's'; str: string }
> ```
> 
> then `FindByTag<Foo, 'n'>` returns `never`. Any idea how to fix that? [Tested on](https://www.typescriptlang.org/play/?ssl=8&ssc=26&pln=8&pc=27#code/FAFwngDgpgBAYgewTAvMGMA+MDeMQCGA5gFwwDkAduVhQJbkDcMlArgLZlvsBGUATjAC+6WnkKkKAZyYwpIfmXn86lIsOChIsOKoAmAITAAVYgB4AqpToJKAGhimiAPlQwrNyjCgAPEFEo9KVx8YjInYRgAfndrWxguKAA3AUZNcGgYHzddQKMnM0QEBypyZyA) v3.8.3

Why not define `Foo` like this?

```ts
type Foo =
  | { tag: 'i'; num: number }
  | { tag: 'n'; num: number }
  | { tag: 's'; str: string }
```

**Comment by nickkeuning** [comment]
@Torvin I wrote up a [blog post](https://spin.atomicobject.com/2021/11/10/discriminated-unions-typescript-project/?utm_source=general-ao&utm_medium=slack&utm_campaign=discriminated-unions-typescript-project) inspired by this thread that tackles the issue you mentioned.

**Comment by moatorres** [comment]
I've been struggling for a whole week with this. Probably I understand so little that I'm trying to do something undoable or felt into a bad practice. Regardless, here's what I'm trying to do:

```ts
interface Background {
  type: "css-property"
  value: 'background'
}

interface Color {
  type: "css-property"
  value: 'color'
}

interface Display {
  type: 'css-property';
  value: 'display'
}

interface Height {
  type: 'css-property'
  value: 'height'
}

type Prop = Background | Color | Height | Display

function assertNever(x: never): never {
  throw new Error("Unexpected object: " + x);
}

const createPrefix = (a: Prop['value']) => <B extends string>(b: B) => {
  return `${a}:${b}` as `${typeof a}:${B}`
}

function getComposer(s: Prop) {
  switch (s.value) {
    case "background":
      return createPrefix(s.value)
    case "color":
      return createPrefix(s.value)
    default:
      return assertNever(s);
  }
}

const colorPrefix = getComposer({
  type: 'css-property',
  value: 'color'
})

const something = colorPrefix('blue')
console.log(something) // → color:blue
// however the type is → const something: "background:blue" | "color:blue" | "height:blue" | "display:blue"
// whereas I'd expect it to be → const something: "color:blue"
```

Another go:

```ts
type TSSProp<T> = T

function isOfType<T extends { value: any }, TValue extends string>(
  it: TSSProp<T>,
  value: TValue
): it is TSSProp<Extract<T, { value: TValue }>> {
  return it.value === value;
}

let createPrefix = (it: TSSProp<Display | Height>) => {
  if (isOfType(it, "display")) {
    return createPrefix(it.value)
  } else return createPrefix(it.value)
};

const prefix = createPrefix({ value: 'background' })
const something = prefix('blue') // → background: blue
// const something: "background:blue" | "color:blue" | "height:blue" | "display:blue"
```

Another one:

```ts
type Foo =
  | { type: 'css-property'; value: 'background' }
  | { type: 'css-property'; value: 'color' }

type FindByTag<Union, Tag> = Union extends { value: Tag } ? Union : never; 

function cast<A extends Foo["value"]>(foo: Foo, expectedTag: A): FindByTag<Foo, A> {
  if (foo.value !== expectedTag)
    throw Error(`expected type ${expectedTag} but was ${foo.type}`)
  return foo as FindByTag<Foo, A>;
}

function tryCast(foo: Foo) {
  const it = cast(foo, foo.value)
  switch(it.value){
    case 'color': return createPrefix(it.value)
    default: return assertNever(foo)
  }
}

const prefix = tryCast({ type: 'css-property', value: 'color' })
const something = prefix('blue')
console.log(something) // → 'color: blue'
// const something: "background:blue" | "color:blue" | "height:blue" | "display:blue"
```

What am I missing?
