### ISSUE TITLE
Expose isTypeRelatedTo in the compiler API

### ISSUE THREAD

**Issue by SamPruden** [Microsoft/TypeScript#17917]
I'm writing a transformer that needs to be able to evaluate type identity and assignability. I believe this is currently not possible with the compiler API. From what I can tell this could be enabled easily and harmlessly by exposing the `isTypeRelatedTo` function and providing an enum for the relation.

**Comment by DanielRosenwasser** [comment]
A PR is actually out for exactly this (#9943).

**Comment by SamPruden** [comment]
Oh that's cool, sorry I missed the dupe. Any idea why it's gone so long unmerged? Is this unlikely to materialise any time soon?

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
