### ISSUE TITLE
Index access type from intersection 

### ISSUE THREAD

**Issue by olegdunkan** [Microsoft/TypeScript#17929]
**TypeScript Version:**  playground

**Code**
```ts
var a: "x" | ("y" & "z");
var b: {x:number, y:string, z:boolean};
var c: keyof typeof b;

c = a; //ok 

var x:typeof b[typeof a];
```

**Expected behavior:**

> An indexed access type T[K] requires K to be a type that is assignable to keyof T
> ...
> T[K] is resolved as follows:
> 
> If K is a union type K1 | K2 | ... | Kn, T[K] is equivalent to T[K1] | T[K2] | ... | T[Kn]
> 
https://github.com/Microsoft/TypeScript/pull/11929

I expected the type of `x` to be `number`, because  `"x" | ("y" & "z")` is assignable to `keyof  {x:number, y:string, z:boolean}`

`T["x" | ("y" & "z")] = T["x"] | T["y" & "z"] = number | ? (never or empty)` but result of union is the `number` type; 
Edited: 
_In other words I expected `T["y" & "z"]` to be `never`_
**Actual behavior:**
error - Type '"y" & "z"' cannot be used as an index type

**Comment by mhegazy** [comment]
The compiler verifies that an index operation is legal. the way it does that is either the key is part of the known keys of the indexed type or constraint to it. in this case `"y" & " z"` are just like `"foo"`, and not part of the known keys for the type `b`, which is `"x" | "y" | "z"`.

**Comment by olegdunkan** [comment]
@mhegazy, thanks I know that complier works as intended, if we are looking at the sources. In my case we have union of types as index type, complier sees that first constituent `x` is legal key name, second `"y"&"z"` is not, why  can't compiler substitute `T["y"&"z"]` with `never`?

**Comment by mhegazy** [comment]
at run-time an index with an unknown property would result in undefined. if the compiler did not limit the access on only known index types, every generic `T[K]` would be potentially `undefined` and you would have to check for that on every use.

**Comment by olegdunkan** [comment]
@mhegazy now I see, thanks a lot for the answer.
But what will be if we reduce union to `not never` ? We will get property with not `undefined` type.
For example, `T["x"] | T["y" & "z"] = number | never = number //ok, property with type number`
`T["x" & "z"] | T["y"&"z"] = never | never = never //bad, undefined property at runtime`
`T["foo"] = never //bad, throws error`

**Comment by mhegazy** [comment]
`T["y" & "z"] ` is not `never`, it is `undefined`.

**Comment by olegdunkan** [comment]
@mhegazy yes, I know, it was my suggestion 

> why can't compiler substitute `T["y"&"z"]` with `never`


the reason of my issue I want to simplify this:
```ts
type A<T, K extends ("x"|"y") & keyof T> = T[K];
var a:A<{x:number, y:string, z:boolean}, "x"|"y">; //ok, type of a is number | string
```
to this:
```ts
type A<T> = T[("x"|"y") & keyof T];
var a:A<{x:number, y:string, z:boolean}>; //bad, type of a is any 
```
Because every time I instantiate `A<T>` I have to remember properties that are constrained in `A`.

Maybe there is some workaround to get it.
