### ISSUE TITLE
btw currentScript can return null

### ISSUE THREAD

**Issue by alexlur** [Microsoft/TypeScript#17921]
`document.currentScript` is returning `null | HTMLScriptElement | SVGScriptElement` per https://html.spec.whatwg.org/multipage/dom.html#dom-document-currentscript

the definition has it:

```typescript
interface Document extends Node, GlobalEventHandlers, NodeSelector, DocumentEvent, ParentNode, DocumentOrShadowRoot {
    readonly currentScript: HTMLScriptElement | SVGScriptElement;
}
```
please fix

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.
