### ISSUE TITLE
No way to detect elaboration message codes with quick fix API

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#17920]
Let's say I want to provide a quick fix for #17871. So far, I have a specialized elaboration:

```
    "Object literal may only specify known properties, but '{0}' does not exist in type '{1}'. Did you mean to write '{2}'?": {
        "category": "Error",
        "code": 2561
    },
```

This gets reported as

```
Type '{ fooo: number; }' is not assignable to type '{ foo: number; }'.
  Object literal may only specify known properties, but 'fooo' does not exist in type '{ foo: number; }'. Did you mean to write 'foo'?
```

However, because this is only an elaboration, I can't register the diagnostic code of

```
Diagnostics.Object_literal_may_only_specify_known_properties_but_0_does_not_exist_in_type_1_Did_you_mean_to_write_2
```

for my codefixes since it's not the root diagnostic. Instead, I have to register a codefix for

```
Diagnostics.Type_0_is_not_assignable_to_type_1
```

which is suboptimal since it's so indirect and non-prescriptive.

**Comment by DanielRosenwasser** [comment]
I'm curious to hear if folks on the Roslyn team (@CyrusNajmabadi) have ran into this at all.

**Comment by CyrusNajmabadi** [comment]
Nope.  We don't have that sort of concept for C#/Vb.

**Comment by RyanCavanaugh** [comment]
We can revisit if needed for some other case
