### ISSUE TITLE
Hindley–Milner style declarations would improve readability a lot

### ISSUE THREAD

**Issue by rlopes** [Microsoft/TypeScript#17926]
It is just a general suggestion and one thing I really appreciate with some FP languages like Haskell is this separation between declaration and implementation.

Types tend to add a cognitive load, a lot of noise around code and it would be a real killer feature if we could use Hindley–Milner style declarations. This would improve readability of the functions while providing type safety.

**Comment by aluanhaddad** [comment]
If you are proposing introducing actual syntax from Haskell directly into TypeScript, I think that will be a hard sell.

It is fairly easy separate declarations and definitions currently
```ts
export interface User {name: string; password: string;}

export type Login = (user: User) => Promise<boolean>;

export const login: Login = x => Promise.resolve(true);

export const user: User = {name: 'Robert', id: 0};

login(user);
```

**Comment by DanielRosenwasser** [comment]
See #11218.

**Comment by rlopes** [comment]
Correct I am talking about the very same thing found in #11218. This one can for the benefit of the other containing a good explanation.
