### ISSUE TITLE
IntersectingObserverEntry.isIntersecting missing from d.ts files

### ISSUE THREAD

**Issue by pottedmeat** [Microsoft/TypeScript#17928]
`IntersectingObserverEntry`'s interface is missing `isIntersecting`, though it is present in the TSJS-lib-generator project https://github.com/Microsoft/TSJS-lib-generator/blob/master/baselines/dom.generated.d.ts#L7215

**Comment by mhegazy** [comment]
Documentation in https://wicg.github.io/IntersectionObserver/#intersection-observer-entry

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by kitsonk** [comment]
@mhegazy it is already in the TSJS-lib, but the last update of the libs from there didn't seem to bring it over...  It looks like it was committed to master, but what got pulled in the TypeScript master, even though it was later, didn't have those changes.

**Comment by mhegazy** [comment]
my bad. then it should be updated soon.
