### ISSUE TITLE
Bug with object type in unions?

### ISSUE THREAD

**Issue by ethanresnick** [microsoft/TypeScript#17937]
**TypeScript Version:**  2.4.2

**Code**

```ts
function x(it: object) { return true; }
function x2(it: object | Map<string, string>) { return true; }

x({ test: true });
x2({ test: true });
```

**Expected behavior:**
The call to `x({ test: true })` succeeds but the same call to `x2` errors with: "Object literal may only specify known properties..."

**Actual behavior:**
It seems like `x2` should allow all arguments that `x` does (and more), so I would expect it not to error given that `x` doesn't.

**Comment by axiac** [comment]
This has apparently been solved a long time ago. It cannot be reproduced with TS 3.3.3 or newer (3.3.3 is the oldest version currently available in the TS playground).

**Comment by ethanresnick** [comment]
Awesome. Maybe a test should be added, and then this should be closed?
