### ISSUE TITLE
Incorrect union type inferred

### ISSUE THREAD

**Issue by pelotom** [Microsoft/TypeScript#17930]
I've found it frequently desirable to be able to "look up" the union variant associated with a type tag. For example, given a union

```ts
type Foo = { tag: 'n'; val: number } | { tag: 's'; val: string }
```

one wants to be able to write a type operator

```ts
type Lookup<T in Foo['tag']> = // ???
```

such that `Lookup<'n'>` = `number` and `Lookup<'s'>` = `string`.

I don't _think_ this is possible in the current type system (would welcome correction on that point). Instead, we can use the trick of _starting_ with a `Lookup` type, and deriving the union type from it:

```ts
type Lookup = {
  n: number
  s: string
}

type Foo = {
  [T in keyof Lookup]: { tag: T; val: Lookup[T] }
}[keyof Lookup]
```

then the inferred type of `Foo` is

```ts
type Foo = {
    tag: "n";
    val: number;
} | {
    tag: "s";
    val: string;
}
```

as desired, and we have our lookup type: `Lookup['n']` = `number` and `Lookup['s']` = `string`.

So I use this pattern a lot, and I wanted to generalize it:

```ts
type Unionize<Lookup> = {
  [T in keyof Lookup]: { tag: T; val: Lookup[T] }
}[keyof Lookup]
```

Unfortunately, this doesn't do what you want:

```ts
type Foo = Unionize<{
  n: number
  s: string
}>
```

Here, `Foo` is inferred to be

```ts
type Foo = {
    tag: "n" | "s";
    val: string | number;
}
```

This seems like a bug!

**Comment by jcalz** [comment]
Looking at quickinfo on `Unionize<Lookup>`, I see:
```ts
type Unionize<Lookup> = { tag: keyof Lookup; val: Lookup[keyof Lookup]; }
```
which is "simplified" in the same surprising/incorrect way I see in #17908.  I think these are the same underlying issue.

**Comment by gcanti** [comment]
Workaround?

```ts
type Unionize<Lookup, X = { [T in keyof Lookup]: { tag: T; val: Lookup[T] } }> = X[keyof X]
```

**Comment by gcnew** [comment]
@gcanti workaround is ingenious. The default forces type evaluation.

The first report of this issue seems to be https://github.com/Microsoft/TypeScript/issues/15756.

**Comment by pelotom** [comment]
Wow, very cool @gcanti!

**Comment by pelotom** [comment]
Using @gcanti's nifty type parameter default trick I put together a new typescript library, [unionize](https://github.com/pelotom/unionize), which allows generating tagged unions along with associated creation functions, predicates and match functions. Would welcome any feedback!

**Comment by mhegazy** [comment]
Just gotta say @gcanti's proposal is impressive :)

> This seems like a bug!

This is the expected behavior. mapped types are a transformation on properties of a type, they do not generate a union type. Many operations that happen on mapped types e.g. inference, rely on the fact that they are [homomorphic transformation](https://en.wikipedia.org/wiki/Homomorphism).

**Comment by jcalz** [comment]
@mhegazy: It may be expected behavior if you know how mapped types are implemented, but it's very surprising, as it violates the seemingly airtight principle of composition:

```ts
type X = ...
type F<T> = ...
type G<T> = ...
type FoG<T> = F<G<T>>
type FGX1 = F<G<X>> 
type FGX2 = FoG<X> 
// FGX1 should be equivalent to FGX2
```

Can you explain more about why generating a union type (i.e., `T[A|B]` → `T[A]|T[B]`) breaks a constraint about mapped types?  

Thanks!

**Comment by gcnew** [comment]
For completeness' sake/History, the workaround was first found by @nirendy / @tycho01 during their exploration in #12215 (ref https://github.com/Microsoft/TypeScript/issues/12215#issuecomment-307614501, https://github.com/Microsoft/TypeScript/issues/16018#issuecomment-307626787).

**Comment by jcalz** [comment]
Is this really "working as intended" in light of #18042 as a fix to #15756 ?

**Comment by mhegazy** [comment]
unionize should be working now after #15756.

**Comment by jcalz** [comment]
FYI to anyone who gets here, #21316 now allows you to [look up a union type by tag value](https://github.com/Microsoft/TypeScript/pull/21316#issuecomment-364982638).
