### ISSUE TITLE
Reading page querystrings

### ISSUE THREAD

**Issue by phanivaranasi** [Microsoft/TypeScript#17938]
I'm developing an application TypeScript application using VS 2015.
In my landing page, displays list of items that are available.
When user clicks on item, it should redirect to details page (details.html with selected item as querystring) ..
so that I can read item number from query string and bind relevant info in detail page.

Could any on help me in the developing this page.

**Comment by aluanhaddad** [comment]
```markdown
<!-- BUGS: Please use this template. -->
<!-- QUESTIONS: This is not a general support forum! Ask Qs at http://stackoverflow.com/questions/tagged/typescript -->
<!-- SUGGESTIONS: See https://github.com/Microsoft/TypeScript-wiki/blob/master/Writing-Good-Design-Proposals.md -->
```

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
