### ISSUE TITLE
Strings assigned to enums not supported by Playground

### ISSUE THREAD

**Issue by navneetkarnam** [Microsoft/TypeScript#17932]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

I came across that the TypeScript version 2.4 's new feature where strings can be assigned to enums is not supported by the playground.

**Comment by ikatyang** [comment]
Duplicate of #17353, the playground is currently v2.3.3.

**Comment by navneetkarnam** [comment]
Got ya!
