### ISSUE TITLE
JavaScript namespaces not working with new JavaScript language service in VS2017

### ISSUE THREAD

**Issue by BubiDevs** [Microsoft/TypeScript#17941]
**Visual Studio version:** 2017 15.3.1

**Code**

```js
if (typeof (MyNamespace) == "undefined") {
    MyNamespace = { __namespace: true };
}

MyNamespace.Foo = {
    doSomething: function () {
        MyNamespace.Foo.doSomething();
    }
};
```

**Expected behavior:**

Intellisense has to shows only valid suggestion, based on the namespace and current level. With legacy JavaScript language service it works propely:

![image](https://user-images.githubusercontent.com/847860/29515209-ca52b43a-866b-11e7-8ad1-0856dcf4d1ac.png)

![image](https://user-images.githubusercontent.com/847860/29515281-1a73f3de-866c-11e7-8e5b-3a6d5ce58abc.png)

**Actual behavior:**

In VisualStudio, if the new JavaScript language service is active, no valid Intellisense is provided:

![screen1](https://user-images.githubusercontent.com/847860/29515168-96277650-866b-11e7-83d9-a6652deb2cba.PNG)

Also, is impossible to use "Go To Definition" function:

![image](https://user-images.githubusercontent.com/847860/29515387-846ef69e-866c-11e7-82fd-835a2514746b.png)

**Comment by mhegazy** [comment]
This is a limitation of the new analysis engine. the feature is tracked by https://github.com/Microsoft/TypeScript/issues/7632

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
