### ISSUE TITLE
Object Literal Subtyping Error Message

### ISSUE THREAD

**Issue by yuit** [Microsoft/TypeScript#1794]
By adding optional property into the object literal, compilers can potentially give very long error messages. I think it will be more desirable if we could shorten them when there are too many properties

**Comment by DanielRosenwasser** [comment]
This is unclear, we need a concrete example to understand what kind of code causes this issue and what kind of error message is produced.

**Comment by RyanCavanaugh** [comment]
See e.g. https://github.com/Microsoft/TypeScript/pull/1795/files#diff-54c17b58c1e2b229d3008b39ff99be95L42 (the PR that actually fixes this issue).
