### ISSUE TITLE
JSDoc nullable template is not parsed correctly

### ISSUE THREAD

**Issue by JoelEinbinder** [Microsoft/TypeScript#17953]
**TypeScript Version:**  2.5.1

**Code**

```js
/** @type {Array<?Thing.Thung>} */
var y;
```

**Expected behavior:**
It should type the variable y as an array of Thing.Thung or null.

**Actual behavior:**
It fails to understand the JSDoc.

This is a regression. I bisected this issue to bc69c7e6d15caec2848301.

**Comment by sandersn** [comment]
Inside a list of type arguments, `?` is not recognised as the legal start of a type.

**Comment by sandersn** [comment]
Fix is up at #17994

**Comment by JoelEinbinder** [comment]
This looks like it is marked to be in the 2.5.2 release, but it is still broken for me in 2.5.2. It is fixed if I use 2.6.0-dev.20170831.

**Comment by mhegazy** [comment]
thanks for the note. updating milestone.
