### ISSUE TITLE
Type Restriction using instanceof in an if block is ignored in lambdas

### ISSUE THREAD

**Issue by ImAllInNow** [Microsoft/TypeScript#17952]
**TypeScript Version:**  ~2.3.4

**Code**
```ts
class Parent { }
class Child extends Parent {
   prop: number = 0;
}

let foo: Parent = new Child();
foo.prop; // <-- ERROR (as expected)
let values: Array<string> = [ 'a', 'b' ];
if (foo instanceof Child) {
   foo.prop; // fine here
   values.forEach((val: string) => {
      foo.prop; // <-- ERROR (not expected)
      let childFoo: Child = <Child>foo;
      childFoo.prop; // fine again
   });
}
```

**Expected behavior:**
All references to foo in the if block (even in a lambda) should know that it's a Child

**Actual behavior:**
References to foo in the lambda go back to assuming foo is a Parent

compiler options:
```json
"compilerOptions": {
   "target": "es5",
   "module": "es2015",
   "moduleResolution": "node",
   "sourceMap": false,
   "emitDecoratorMetadata": true,
   "experimentalDecorators": true,
   "lib": ["es2015", "es2016", "dom"],
   "removeComments": true,
   "noImplicitAny": false,
   "suppressImplicitAnyIndexErrors": true,
   "allowSyntheticDefaultImports": true,
   "typeRoots": [
      "../node_modules/@types/"
   ]
}
```

**Comment by mhegazy** [comment]
The compiler can not grantee when the lambda will be called, and whether there are no mutations to `foo` before the lambda is called that could change its type. declare `foo` as `const` instead.

**Comment by ImAllInNow** [comment]
Yeah, I suppose that makes sense. Might not be possible to infer. Just felt unintuitive in this case.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
