### ISSUE TITLE
Typescript not using "Typings" field in package.json for d.ts files

### ISSUE THREAD

**Issue by sg-avi** [Microsoft/TypeScript#17958]
**TypeScript Version:**  2.4.2

When importing third party libraries, shouldn't typescript use the "typings" field from the library's package.json if present for importing definition files?
Or am I missing some configuration to enable it?

Github repo that shows the bug: https://github.com/sg-avi/TS-bug

**Code**

```ts
import * as A from "@uirouter/angularjs";
import * as B from "moment";
```

**Expected behavior:**

Code should compile, intellisense and tsc should know the types exported by moment and uirouter defnition files.

**Actual behavior:**

Compilation error, intellisense doesn't know the types.

**Comment by ikatyang** [comment]
```json
 "moduleResolution": "node"
```

**Comment by sg-avi** [comment]
Thank you so much, I've been wrestling with this problem for the last few months!

**Comment by itanex** [comment]
@ikatyang I have tried this solution, however it does not seem to fix the issue that I am having. I posted a [question on SO](https://stackoverflow.com/questions/48308432/ts2694-ts-namespace-angular-has-no-exported-member-ui), perhaps you could take a second to look. If it isn't too much trouble.
