### ISSUE TITLE
After installing TypeScript SDK 2.3.4 for Visual Studio 2017 2.3.1 I'm stuck on 2.3.4 still

### ISSUE THREAD

**Issue by ericop** [Microsoft/TypeScript#17951]
**TypeScript Version:** 2.4.1

**Code**
In Visual Studio 2017 - 15.3 Pro (just downloaded today on a new windows 10 machine)

This [issue-17619](https://github.com/Microsoft/TypeScript/issues/17619) was raised and closed as "fixed" when it doesn't not appear to be fixed in the VS2017.3 updates. Others should verify, but it certainly didn't work for me today doing a clean install.

These problems still remain, but seem to make things *worse*.

1.  *(Worse)* Nothing shows in the **Tools > Options > Text Editor > JavaScript/TypeScript > IntelliSense**
![typescript version still wrong or confusing in vs2017 3](https://user-images.githubusercontent.com/5218249/29536750-f9d5c320-868c-11e7-80b4-615c6c58f36c.png)
2.  The *About* still does not the most recently installed version of Typescript
3.  *(Worse)* from https://github.com/Microsoft/TypeScript/wiki/Updating-TypeScript-in-Visual-Studio-2017#setting-typescript-versions-in-visual-studio-2017-version-153
    - "Right click on the project node in Solution Explorer 
    - Click **Properties**
    - Go to the **TypeScript Build** tab ... `NO such tab is shown!`  Is this for NodeJS Projects only? The [Docs ](https://github.com/Microsoft/TypeScript/wiki/Updating-TypeScript-in-Visual-Studio-2017#setting-typescript-versions-in-visual-studio-2017-version-153)  at minimum need to be updated since .Net projects certainly do not contain a **TypeScript Build** tab as is implied.

**Comment by mhegazy** [comment]
What do you see if you reload your solution?

**Comment by ericop** [comment]
I can put in a screen shot. What specifically are you looking for? I did
reload the solution and closed and reopened Vs2017, same results as our
seen in screen shots above. Ditto for restarting the windows. Do you run
masOS? This should be repeatable for anyone on Windows.

**Comment by mhegazy** [comment]
we have a long standing bug that after adding the first TS file to your project, the property pages will not be loaded except after a reload. 
from the screenshot above, i do not see "TypeScript Build" tab. So either your project is not a C#/VB/JS proj, or you do not have an import to Microsoft.TypeScript.targets, or you do but did not restart your IDE.

**Comment by ericop** [comment]
Okay thanks for explaining the background of the Mohamed. I'll tinker
around with this tomorrow and report back what I can find.

**Comment by billti** [comment]
I have a clean install of 15.3 (community) on a clean install of Windows 10. I just installed the TypeScript 2.4 release from the download page too.

On creating a new ASP.NET project (full .NET Framework, not ASP.NET Core, as from your property pages that looks like a regular ASP.NET project), adding a TypeScript file, and going to the properties pages for the project, I see the below. (I checked and ASP.NET Core 1.1 & 2.0 work fine also).

What workloads do you have installed? Did you get any install errors for VS or TypeScript (the logs are usually under the %TEMP% folder)? Does the property page work in any other project types? Do you see any errors in the Event Logs relating to VS or TypeScript? Is there an ActivityLog.xml file written to "%APPDATA%\Microsoft\VisualStudio\15.0_<somehash>" that has any errors in it?

If you can use the "Report a problem" feature from within VS (the person with a speech bubble icon in the top right), this will collect some useful data with the report that will help me investigate.

Thanks.

![tsproppage](https://user-images.githubusercontent.com/993909/29544137-f2fcc950-869a-11e7-99cf-c528f498bcc6.png)

**Comment by ericop** [comment]
Thanks Bill. Yeah this was a non-Core project, and I did not add additional
TS files but the project does have several TypeScript files. I'll check
into the logs and such as you have mentioned and paste back the contents
tomorrow to give you something to work with, or hopefully confirm that it
works. From memory, I have all the extension in Web Essentials 2017
installed and that's it on this new install.

**Comment by ericop** [comment]
Here's the run down after pokin garound:
- I did to a *Rebuild*, I also restarted VS and did another Rebuild as a sanity check
    - *Code Analysis* is still the last tab in the list in properties
- Install Errors: none popped up at all; in *%TEMP%* I have files like `dd_setup_20170821144453_291_Microsoft.VisualStudio.Product.Professional.log` but it's all `INFO: ...`
- In *%APPDATA%\Microsoft\VisualStudio\15.0_a4b34318* I have no `ActivityLog.xml` file, or any .xml files as i search the directory.

So next I tried making changes to my `home.controller.ts` file and saving it, and sure enough the `.js` and `.js.map` were created.

Next I tried adding a new Typescript file 
- **Right-click (on *home* folder in `app/layout/home`) > **Add* > **New Item...** > **TypeScript File     Visual C#** > **Name:** `fullEclipse.ts`
- This brought up the Modal "Update TypeScript version?"
![update typescript version](https://user-images.githubusercontent.com/5218249/29566288-510731bc-8717-11e7-9c08-7ca1cfafac2f.png)
- I chose *Yes*
- I add one line of code `var totalSolarEclipse = true;` and save the file
- VS status bar shows many files being generated and ends with "Output(s) generated Successfully"
- I checked my project file again and sadly *Code Analysis* is still the last tab in the list in properties, not *TypeScript Build*

**Comment by ericop** [comment]
​Okay, so I restarted VS 2017 after the above was done and it prompted me to save the .sln and .csproj, and now there is and *TypeScript Build* Tab ! That's good. When I had the properties open on the project file I noticed the "*" in the tab to show an unsaved change. I tried Ctrl + S but it didn't seem to do anything, but the restart of Visual Studio with the warning modal did the trick.

**Comment by ericop** [comment]
So the "work around" seems to be these:
1. Add a `temp.ts` file and save it (in my case this is a solution that is in maintenance mode so I may never need to add new .ts files for new features, etc., but to do so temporarily is trivial)
2. Open the Project > Properties and save them (*Ctrl + S* m which did work when i re-tried it, so I must have fat-fingered the keys last time)
3. Close the solution (If you don't close the solution the *TypeScript Build* Tab doesn't seem to show)
4. Reopen Solution to see  *TypeScript Build* Tab in the projects properties.
5. Delete the `temp.ts` file and pat yourself on the back for a job well done

**Comment by billti** [comment]
Sorry for the delay. I recall seeing this myself previously. I'll investigate why we need to reload the project for the property page to appear, and if the "Save..." handler is not wired up correctly.

As this is a VS specific issue, I'll track it on the DeveloperCommunity issue you opened above, and close this TypeScript issue. Thanks.
