### ISSUE TITLE
RegExpExecArray should be `Array<string | undefined>`

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#17963]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

**Code**

```ts
const rgx = /(a)?(b)(c)?(d)/;
const match = rgx.exec("bd");
if (match !== null) {
    const a: string = match[1];
    console.log(a.toUpperCase());
}
```

**Expected behavior:**

Compile error.

**Actual behavior:**

Run-time `TypeError: Cannot read property 'toUpperCase' of undefined`.

**Comment by mhegazy** [comment]
how is that different from a regular array access? you still can get `undefined`.

**Comment by andy-ms** [comment]
In this case, we're looking at an array with `undefined` values embedded in it:
```js
> /(a)?(b)(c)?(d)/.exec("bd");
[ 'bd', undefined, 'b', undefined, 'd', index: 0, input: 'bd' ]
```
If we remove the properties `index: 0` and `input: 'bd'` and paste this into TypeScript code, the inferred type is `Array<string | undefined>`:

**Comment by RyanCavanaugh** [comment]
Duplicate #17094, #17053
