### ISSUE TITLE
Use const enum values in enum declarations member initializer.

### ISSUE THREAD

**Issue by mpawelski** [Microsoft/TypeScript#1797]
Right now we can write code like this in C#:
```
enum EnumA
    {
        Foo = 1
    }

    enum EnumB
    {
        Foo = EnumA.Foo,
        Bar = 1
    }
```
and in Typescript we can simulate that with this code:
```
enum EnumA {
    Foo = 1
}

enum EnumB {
    Foo = <number>EnumA.Foo,
    Bar = 1
}
```
and everything work fine (just EnumB.Foo isn't inlined, but it is not a big problem).

It would be nice if we could do something like this with const enums:
```
const enum EnumA {
    Foo = 1
}

const enum EnumB {
    Foo = EnumA.Foo,
    Bar = 1
}
```
It would be similar to what we can do right now in C# enums. Personally, want this feature because I want my declared enums in TypeScript (API client) to be exactly like those in C# code (API server), but I think it would be useful for others too. Besides, current error `In 'const' enum declarations member initializer must be constant expression.` is a little funny because cons enum values are constant expressions in mu opinion ;)

**Comment by RyanCavanaugh** [comment]
Seems reasonable to add "previously-declared const enum members" the list of things we consider valid for const enum member initializers

**Comment by vladima** [comment]
Agree, this looks like a nice change to make

**Comment by jasonwilliams200OK** [comment]
I think this should be closed?

**Comment by RyanCavanaugh** [comment]
Seems so.
