### ISSUE TITLE
Object destructing without type narrowing

### ISSUE THREAD

**Issue by retep007** [Microsoft/TypeScript#17976]
**TypeScript Version:**  2.4.3

**Code**

Not working
```ts
class Greeter {
    readonly type = 'A';
    payload: string;
}

class Greeter2 {
    readonly type = 'B';
    payload: number;
}

type A =
    | Greeter
    | Greeter2

function m({ type, payload }: A): string {
    let a: number;
    switch (type) {
        case 'A':
            return payload;
        case 'B':
            return payload;

    }
}
```
Working
```typescript
class Greeter {
    readonly type = 'A';
    payload: string;
}

class Greeter2 {
    readonly type = 'B';
    payload: number;
}

type A =
    | Greeter
    | Greeter2

function m(action: A): string {
    let a: number;
    switch (action.type) {
        case 'A':
            return action.payload;
        case 'B':
            return action.payload;

    }
}
```

**Expected behavior:**
Should correctly narrow down type union

**Actual behavior:**
Using destructed object should be the same as not using it and type should be correctly derived

**Comment by kitsonk** [comment]
There are tradeoffs to CFA (see #9998).  In this case you are copying a property to a local variable but wanting to continue the relationship with where it came from.  That doesn't make sense.  `type` in the block of code could have any value at that point and it would no longer be reflected in the source object.  At some point TypeScript has to stop tracking things.

For example, this is valid, but does not actually touch the source object:

```ts
function m({ type, payload }: A): string {
    type = 'B'; // has no intended effect on payload
    let a: number;
    switch (type) {
        case 'A':
            return payload;
        case 'B':
            return payload;

    }
}
```

**Comment by retep007** [comment]
Thank you for explanation.
