### ISSUE TITLE
Computed properties are not type checked correctly

### ISSUE THREAD

**Issue by Roam-Cooper** [Microsoft/TypeScript#17975]
**TypeScript Version:**  2.3.3

**Code**

```ts
let properties = {
colour: "colour" as "colour"
};

interface DataFace{
colour?: "red" | "green" | "blue";
}

let data1: DataFace = {
[properties.colour]: "yellow"
};

let data2: DataFace = {} as any;
data2[properties.colour] = "yellow";
```

**Expected behavior:**
Assignment to both data1 and data2 fails because the value yellow is not a valid value of the property colour according to the DataFace interface.

**Actual behavior:**
Assignment to data2 fails as expected, but assignment to data1 succeeds because it seems like weak typing + potential internal conversion of computed properties to strings means that type checking is ignored for the computed property.

**Comment by mhegazy** [comment]
should be covered by https://github.com/Microsoft/TypeScript/issues/16760

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
