### ISSUE TITLE
Outdated WHATWG DOM Event interface and init

### ISSUE THREAD

**Issue by KamiQuasi** [Microsoft/TypeScript#17974]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
document.dispatchEvent(new CustomEvent('test-event', { detail: { foo: 'bar' }, bubbles: true, composed: true }));
```

**Expected behavior:**
Utilizing the 'composed' property should work. As per the WHATWG Living Standard the 'scoped' and 'deepPath' properties of an Event have been replaced with 'composed' and 'composedPath' respectively (see https://dom.spec.whatwg.org/)

**Actual behavior:**
Argument of type '{ detail: { term: string; }; bubbles: true; composed: boolean; }' is not assignable to parameter of type 'CustomEventInit'.
  Object literal may only specify known properties, and 'composed' does not exist in type 'CustomEventInit'.

**Comment by kitsonk** [comment]
`composed` is part of the [ShadowDom v1 specification](https://www.chromestatus.com/feature/4667415417847808) and it seems like it is only implemented in [Chrome and Firefox](https://developer.mozilla.org/en-US/docs/Web/API/Event/composed) at the moment.

That being said, changes to these interfaces are contributed via the  TSJS-lib-generator and [contribution guidelines can be found here](https://github.com/Microsoft/TSJS-lib-generator/#contribution-guidelines)

Also, interfaces are open ended, so you could easily add this to your local project, knowing that you were going to run in an environment where this was supported:

```ts
declare global {
  interface Event {
    readonly composed: boolean;
  }
}
```

**Comment by KamiQuasi** [comment]
@kitsonk hoping I didn't misread the contribution guidelines on the TSJS-lib-generator repo, but it seemed to say to make changes there I should submit an issue here to reference. I've submitted a PR on that repo that should adjust this (https://github.com/Microsoft/TSJS-lib-generator/pull/284). The main reason I wanted to get this change in was for compatibility with the webcomponents v1 polyfill, which also implements the composed and composedPath properties.

**Comment by kitsonk** [comment]
Apologies, missed the linked issue... 😊
