### ISSUE TITLE
Impossible to compare String enums

### ISSUE THREAD

**Issue by vrudikov** [Microsoft/TypeScript#17987]
**TypeScript Version:**  2.5.1

**Code**

```ts
export enum SomeEnum {
  A = 'A is the first',
  B = 'BBusiness',
  C = 'C is for cup',
  D = 'D is so good, but the last'
}

// This doesn't work, because SomeEnum.A returns 'A is the first'
mapSomeEnum(clazz: SomeEnum): string {
    let cssClass;

    if (clazz === SomeEnum.A) {
      cssClass = 'btn-danger';
    } else if (clazz === SomeEnum.B) {
      cssClass = 'btn-warning';
    } else if (clazz === SomeEnum.C) {
      cssClass = 'btn-primary';
    } else if (clazz === SomeEnum.D) {
      cssClass = 'btn-default';
    }

    return cssClass;
  }

// This not gonna work either, because SomeEnum[SomeEnum.A] returns [undefined]
mapSomeEnumOldStyle(clazz: SomeEnum): string {
    let cssClass;

    if (clazz === SomeEnum[SomeEnum.A]) {
      cssClass = 'btn-danger';
    } else if (clazz === SomeEnum[SomeEnum.B]) {
      cssClass = 'btn-warning';
    } else if (clazz === SomeEnum[SomeEnum.C]) {
      cssClass = 'btn-primary';
    } else if (clazz === SomeEnum[SomeEnum.D]) {
      cssClass = 'btn-default';
    }

    return cssClass;
  }
```

**Expected behavior:**
We should have possibility to compare enums instances

**Actual behavior:**
Doesn't work in both cases - old style and new style

**Comment by DanielRosenwasser** [comment]
You can either convince TypeScript that `cssClass` isn't `null` (use the postfix bang operator: `cssClass!`) or write an `assertNever` helper function:

```ts
export enum SomeEnum {
  A = 'A is the first',
  B = 'BBusiness',
  C = 'C is for cup',
  D = 'D is so good, but the last'
}

// This doesn't work, because SomeEnum.A returns 'A is the first'
function assertNever(x: never): never {
    throw "Unexpected value " + x;
}

function mapSomeEnum(clazz: SomeEnum): string {
    let cssClass;

    if (clazz === SomeEnum.A) {
      cssClass = 'btn-danger';
    } else if (clazz === SomeEnum.B) {
      cssClass = 'btn-warning';
    } else if (clazz === SomeEnum.C) {
      cssClass = 'btn-primary';
    } else if (clazz === SomeEnum.D) {
      cssClass = 'btn-default';
    } else {
      cssClass = assertNever(clazz);
    }

    return cssClass;
  }
```

See https://www.typescriptlang.org/docs/handbook/advanced-types.html#exhaustiveness-checking.

**Comment by vrudikov** [comment]
If so i will get "Unexpected value " error for every call of "mapSomeEnum" method. I don't need to convince TypeScript that cssClass isn't undefined. I want to compare enums `clazz === SomeEnum.A)`, but it doesn't work, because clazz is instance of SomeEnum.A and has value 'A' and SomeEnum.A has value 'A is the first'

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Comment by steviemo** [comment]
Hi,
I think this ticket should be reopened as it is a bug in typescript. String enum comparison does not work at present.

**Comment by RyanCavanaugh** [comment]
@steviemo Nothing in this issue indicates there's a bug. Please search existing issues as people frequently think there is something wrong with string enums when there isn't

**Comment by steviemo** [comment]
Hey - I cannot see how we do a comparison for string based enums (where the string value doesn't match the key)??

**Comment by mhegazy** [comment]
@steviemo please file a new issue, and provide us with a self-contained repro of the issue you are seeing, what is not working, and why you believe it is a bug.
