### ISSUE TITLE
Incomprehensible error message when parameter clashes with type in Lib.d.ts

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/TypeScript#1798]
Hi,

**TS**: 1.4

The following code:

```typeScript
declare module foo {

    interface DragEvent {

        foo(): void;
        dataTransfer: DataTransfer;
    }

    interface Baz {

        bar(handler: (event: foo.DragEvent) => void): void;
    }

    interface BazInternal {

        equals(other: Baz): boolean;
    }
}

class Baz implements foo.BazInternal {

    public equals(other: Baz) {
        return true;
    }

    public bar(handler: (event: DragEvent) => void) {
    }
}
```

Causes the compiler to issue an incomprehensible error message:

```
Class 'Baz' incorrectly implements interface 'BazInternal'.
  Types of property 'equals' are incompatible.
    Type '(other: Baz) => boolean' is not assignable to type '(other: Baz) => boolean'.
      Types of parameters 'other' and 'other' are incompatible.
        Type 'Baz' is not assignable to type 'Baz'.
          Types of property 'bar' are incompatible.
            Type '(handler: (event: DragEvent) => void) => void' is not assignable to type '(handler: (event: DragEvent) => void) => void'.
              Types of parameters 'handler' and 'handler' are incompatible.
                Type '(event: DragEvent) => void' is not assignable to type '(event: DragEvent) => void'.
                  Types of parameters 'event' and 'event' are incompatible.
                    Type 'DragEvent' is not assignable to type 'DragEvent'.
                      Property 'foo' is missing in type 'DragEvent'.	
```

The relevant items are:
* The signature for `public bar` should have been `public bar(handler: (event: foo.DragEvent) => void)`
* To reproduce the error, the interface `foo.DragEvent` should have an additional method `foo(): void;` (in order to distinguish it from the type in `lib.d.ts`)
*  For the line `Type 'Baz' is not assignable to type 'Baz'` to be printed there should be both a class and an interface called `Baz`.

Related issues: #1419 #1796

**Comment by DanielRosenwasser** [comment]
> Type 'Baz' is not assignable to type 'Baz'.

As this is related to #1419, #1575 should partially  help with some of what you're seeing here.

**Comment by DanielRosenwasser** [comment]
I think this should be fixed now that #1575 is in. Let me know if you continue to see this.

**Comment by DanielRosenwasser** [comment]
If we could actually get the `Type 'Baz' is not assignable to type 'Baz'.` portion fixed, then this would at least not be quite as crazy. Unfortunately we"re not doing that somewhere.

**Comment by mhegazy** [comment]
this shoudl be fixed now. it shows:

> Class 'Baz' incorrectly implements interface 'BazInternal'.
  Types of property 'equals' are incompatible.
    Type '(other: Baz) => boolean' is not assignable to type '(other: Baz) => boolean'.
      Types of parameters 'other' and 'other' are incompatible.
        Type 'Baz' is not assignable to type 'foo.Baz'.
          Types of property 'bar' are incompatible.
            Type '(handler: (event: DragEvent) => void) => void' is not assignable to type '(handler: (event: DragEvent) => void) => void'.
              Types of parameters 'handler' and 'handler' are incompatible.
                Type '(event: DragEvent) => void' is not assignable to type '(event: DragEvent) => void'.
                  Types of parameters 'event' and 'event' are incompatible.
                    Type 'DragEvent' is not assignable to type '**foo.DragEvent**'.
                      Property 'foo' is missing in type 'DragEvent'.
