### ISSUE TITLE
Implicit types are too strict on class decorators

### ISSUE THREAD

**Issue by MLoughry** [Microsoft/TypeScript#17989]
**TypeScript Version:**  2.4.2

I ran into this issue with some of our class decorators after upgrading to TS 2.4.2 and upgrading our React typings to 15.0.38. It seems the type checking doesn't allow for return types that are a subset of the return types of an interface to resolve to that interface.

**Code**

```ts
declare namespace React {
    class Component {
        render(): string | false;
    }

    interface ComponentClass {
        new (): Component;
    }
}

function classDecorator(
    InputTemplate: React.ComponentClass
): React.ComponentClass {
    return class classDecorator extends React.Component {

        render(): string | false {
            return 'foo';
        }
    };
}

@classDecorator // error: Type '() => string | false' is not assignable to type '() => string'.
class Foo extends React.Component {
    render() {
        return 'foo';
    }
}

```

**Expected behavior:**
No error, as `() => string` is a subest of `() => string | false`, and is therefore compatible.

**Actual behavior:**
Transpilation throws an error:
```
index.ts(22,1): error TS1238: Unable to resolve signature of class decorator when called as an expression.
  Type 'ComponentClass' is not assignable to type 'typeof Foo'.
    Type 'Component' is not assignable to type 'Foo'.
      Types of property 'render' are incompatible.
        Type '() => string | false' is not assignable to type '() => string'.
          Type 'string | false' is not assignable to type 'string'.
            Type 'false' is not assignable to type 'string'.
```
I can work around the issue in this repro by explicitly specifying the return type of `Foo.render()`
```
@classDecorator
class Foo extends React.Component {
    render(): string | false {
        return 'foo';
    }
}
```

**Comment by mhegazy** [comment]
the error seems correct to me. a decorator can not alter the type of a class it decorates. `Foo.render` can only return `string` , but the decorator `classDecorator` returns a class with render that can return `string | false`.

**Comment by MLoughry** [comment]
How is `Foo` able to even extend `React.Component` (without the decorator) in the first place, then?

Also, the issue still happens if you remove the return type specification in the class decorator:
```ts
function classDecorator(
    InputTemplate: React.ComponentClass
): React.ComponentClass {
    return class classDecorator extends React.Component {

        render() {
            return 'foo';
        }
    };
}
```

**Comment by mhegazy** [comment]
The decorator function returns `React.ComponentClass`. so that is always gonna be not assignable to `Foo`.

the fix here is to either implement `render` in the derived class the same way the base does, or you return `any` from the decoratored `render`.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
