### ISSUE TITLE
Typescript transpiler cannot resolve value making Type alias fails

### ISSUE THREAD

**Issue by tom10271** [Microsoft/TypeScript#17999]
**TypeScript Version:**  2.4.1

**Code**

```ts
export type AttributeType = 'string' | 'number' | 'boolean' | 'date' | 'array' | 'object' | 'any';

var resolved: AttributeType = 
[
    'string',
    'number',
    'boolean',
    'date',
    'array',
    'object'
].indexOf(typeof 'str') === -1 ? 'any' : typeof 'str';
```

**Expected behavior:**
Compilable.

**Actual behavior:**
Argument of type '"string" | "number" | "boolean" | "symbol" | "undefined" | "object" | "function" | "any"' is not assignable to parameter of type 'AttributeType'.
  Type '"symbol"' is not assignable to type 'AttributeType'.

**Comment by tom10271** [comment]
I need to by pass it with:

```ts
<AttributeType>(
    [
        'string',
        'number',
        'boolean',
        'date',
        'array',
        'object'
    ].indexOf(typeof '') > -1 ? typeof '' : 'any'
)
```

**Comment by QuietWind** [comment]
```ts
const typeName = typeof "";

// list all typeName types is:
// "string" | "number" | "boolean" | "symbol" | "undefined" | "object" | "function"

so like this code:

// https://github.com/Microsoft/TypeScript/issues/17999

export type AttributeType =
  | "string"
  | "number"
  | "boolean"
  | "symbol"
  | "undefined"
  | "object"
  | "function";

var resolved: AttributeType =
  ["string", "number", "boolean", "date", "array", "object"].indexOf(
    typeof "str"
  ) === -1
    ? "object"
    : typeof "str";

will work fine.
```

**Comment by tom10271** [comment]
I am sorry but that is exactly what I don't want, 

`export type AttributeType = 'string' | 'number' | 'boolean' | 'date' | 'array' | 'object' | 'any';` is a must.

**Comment by mhegazy** [comment]
the result of `typeof ` operator is `'function' | 'string' | 'number' | 'symbol' | 'boolean' | 'date' | 'array' | 'object' | 'any' | 'undefined'` and that is not assignable to your `AttributeType`. 

it is true that `typeof "str"` is always `"string"`, but this seems like a bit of a contrived use case. and i would say you can just work around this by casting:

```ts
const str = typeof 'str' as "string";
var resolved: AttributeType = 
[
    'string',
    'number',
    'boolean',
    'date',
    'array',
    'object'
    ].indexOf(str) === -1 ? 'any' : str;
```

**Comment by tom10271** [comment]
I am creating a form builder that can resolve form field type automatically. So if the typeof attribute value in object is not string, number, boolean, I will mark them as any.

```ts
var resolved: AttributeType = 
[
    'string',
    'number',
    'boolean'
].indexOf(obj[key]) === -1 ? 'any' : obj[key];
```

I use a string to illustrate the bug only, not intensionally trying to make it up.

**Comment by mhegazy** [comment]
the OP used `typeof "str"`, that is not `string`; it is `'function' | 'string' | 'number' | 'symbol' | 'boolean' | 'date' | 'array' | 'object' | 'any' | 'undefined'`.

if that is not the issue, please provide some self-contained reproduction of the issue you are seeing.

**Comment by tom10271** [comment]
```ts
export type AttributeType = 'string' | 'number' | 'boolean' | 'date' | 'array' | 'object' | 'any';

var resolved: AttributeType = 
[
    'string',
    'number',
    'boolean'
].indexOf(typeof obj[key]) === -1 ? 'any' : obj[key];
```

I made a typo. It should be like this. If `typeof obj[key]` is not `string`, `number` or `boolean`, it should return `any` else `string`, `number` or `boolean`. All values are valid for AttributeType yet compiler don't think so.

**Comment by mhegazy** [comment]
i am not sure i follow anymore. can you restate the issue again without the typo?
