### ISSUE TITLE
Flag expressions in export assignments in ambient contexts as errors

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#17991]
```ts
declare module "foo" {
  export default 1 + 1;  // should not be allowed
}
```
originally reported in https://github.com/Microsoft/TypeScript/issues/16769

**Comment by weswigham** [comment]
I think it's better to wait for #17831 to merge, then change `export default [node]` parse `[node]` as a type, rather than as an expression in ambient contexts. This aligns with how we allow interfaces/type aliases/etc as default exports through other means already.

**Comment by mhegazy** [comment]
based in #18339, we should add a grammar check.
