### ISSUE TITLE
Extract method refactoring should not show full file path 

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#17998]
**TypeScript Version:**  2.5.1

**Code**

```ts
function foo() {
    return 1 + 2;
}
```

highlight `1 + 2` and trigger code actions

**Bug:**
For the file extract, we show the entire file path:

![screen shot 2017-08-23 at 5 39 45 pm](https://user-images.githubusercontent.com/12821956/29644332-1c576770-882a-11e7-9151-a17a01643fd2.png)

This path can be very long and is not necessary since extract can currently only operate within the same file (at least to my knowledge).

**Comment by mhegazy** [comment]
i suppose getting the file name would be sufficient, or just saying `into containing file` or `into this file`.
