### ISSUE TITLE
`compilerOptions.paths` and TS6137 make declaration merging for @types definitions impossible

### ISSUE THREAD

**Issue by despairblue** [Microsoft/TypeScript#18006]
**TypeScript Version:**  2.4.2

**Folder Structure:**

```
├── overrides
│   └── shelljs.d.ts
├── package.json
├── src
│   └── index.ts
└── tsconfig.json
```

**Code**

tsconfig.json
```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "outDir": "build",
    "paths": {
      "shelljs": ["overrides/shelljs.d.ts"]
    },
    "rootDir": "src"
  },
  "exclude": ["node_modules", "scripts", "build"]
}
```

overrides/shelljs.d.ts
```ts
export * from "@types/shelljs";

export function set(option: "-e" | "+e" | "-v" | "+v" | "-f" | "+f"): void;
```

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**Expected behavior:**

I expected a way to use declaration merging to add missing types to type-definitions from `@types`. Using `export * from "shelljs"` does not work since it export the current override, thus every other function except for `set` is then missing.

What does work is `export * from '../node_modules/@types/shelljs'`, though I cannot use this because this package is in a monorepo and the type definition may be hoisted to the top-level node_modules folder.

**Actual behavior:**

```
1 export * from "@types/shelljs";
                ~~~~~~~~~~~~~~~~

overrides/shelljs.d.ts(1,15): error TS6137: Cannot import type declaration files. Consider importing 'shelljs' instead of '@types/shelljs'.
```

**Comment by mhegazy** [comment]
what you need is to "augment" the module. 

No need for `"paths"` in your tsconfig.json. In `overrides/shelljs.d.ts`, add:
```ts
import * as s from "shelljs";

declare module "shelljs" {
    export function set(option: "-e" | "+e" | "-v" | "+v" | "-f" | "+f"): void;
}
```

You can find more about module augmentation at https://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation

**Comment by despairblue** [comment]
@mhegazy Thank you. I assume the compiler looks in all directories except those in the `exclude` block in the `tsconfig.json` by default and picks up the typedefinitions?

**Comment by PavelPolyakov** [comment]
hi @mhegazy ,

I think I met the same issue as @despairblue , but I want not only to ADD something to the type definition, but EXTEND/REDEFINE it.

Here is my attempt:
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/20064#issuecomment-334832952

it works, but I also have `TS6137` error:
![image](https://user-images.githubusercontent.com/839290/31293312-14fb0688-aad7-11e7-9f0d-3d78194c1b77.png)

Any thoughts on how I can overcome it and achieve it being 100% typescript compatible?

Also join @despairblue question - why *paths* shouldn't be used? I thought this is the way to tell typescript where to look for the definitions.

Regards,

**Comment by mhegazy** [comment]
not sure i understand why you import `@types/*`, the compiler should know how to resolve `import ... from "hapi"` to `@types/hapi` if it exists.

**Comment by PavelPolyakov** [comment]
hi @mhegazy, thanks for the quick reply.

The thing is that in this file I actually `redefine` the `hapi`.
so compiler will resolve `hapi` to my newly created hapi definition, NOT to the one which I've downloaded from `DefinitelyTyped`.

![image](https://user-images.githubusercontent.com/839290/31299719-1525477c-aaf0-11e7-85d3-2b030435c6b4.png)

And this is my idea - I actually want to redefine default `import from "hapi"` so compiler points to MY declaration, but in this declaration I want to extend the community declaration.

Hope now it explains what I'm trying to do and why I need to import from the `@types`.

**Comment by mhegazy** [comment]
so you want to use `@types/hapi` but want to wrap it with another declaration (not augment it)?

**Comment by PavelPolyakov** [comment]
@mhegazy 
yes, I want to get the definitions from the community and redeclare some properties inside the class `Server`.
but I do not want to redeclare the whole `Server`, I want to extend my server from the community one, so I can benefit from the declarations which are already there.

As long as I understand `augmentation` is when we add something new, while I want to use the existing declarations and update some part of it.

**Comment by mhegazy** [comment]
> yes, I want to get the definitions from the community and redeclare some properties inside the class Server.

so why not augment it?

> As far as I understand, augmentation is when we add something new, while I want to use the existing declarations and update some part of it.

Not sure what you mean by add or update. you can not change the type of an existing declaration, but you can add new properties/overloads.


> At the same time, I want my new definition to be available under the same (default) name - hapi. So in order to achieve that I'm pointing compiler to my custom path.

how is this supposed to work at runtime?

**Comment by PavelPolyakov** [comment]
@mhegazy 
But how can I achieve it using augmentation?

Here is the case:
1. There is `DefinitelyTyped` `@types/hapi`, which exports `class Server`.
2. Inside this class there is a property `plugins` with the next typing:
```typescript
export class Server {
    plugins: PluginsStates;
}

export interface PluginsStates {
    [pluginName: string]: any;
}
```
3. What I really need to do is to overload `PluginsState` with my custom definition

I've prepared min representation for you:
https://github.com/PavelPolyakov/hapi-ts-vs-plugins-example

And this is a proof that it is working:
![image](https://user-images.githubusercontent.com/839290/31306306-4b3b641a-ab4d-11e7-95b6-4d3fcc1cccd4.png)

(please pay attention that I still require `hapi`, not MY definition, and it works `npx ts-node index.ts`)
![image](https://user-images.githubusercontent.com/839290/31306443-6a747b98-ab50-11e7-9664-abf5cfbb9d6a.png)

How can this be solved using the *augmentation*? I'd really appreciate PR or code example, as I've tried different things which seems not to work (interface merging for `PluginsStates` for example).

Thank you in advance for trying to help. Looking forward for your thoughts!

Regards,

**Comment by PavelPolyakov** [comment]
hi @mhegazy, hope you had good weekends and will be able to help me this week.
still interesting in a way to achieve my goal without TS errors.

Regards and thanks for your help!

**Comment by mhegazy** [comment]
sent you a PR with the augmentation: https://github.com/PavelPolyakov/hapi-ts-vs-plugins-example/pull/1

**Comment by mhegazy** [comment]
You can find more details at https://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation

**Comment by PavelPolyakov** [comment]
@mhegazy thank you very much, now I got it. You're the best! 🥇
