### ISSUE TITLE
Change to implicit any of single arrow function param in 2.5/2.5.1

### ISSUE THREAD

**Issue by fizzgig23** [Microsoft/TypeScript#18003]
I know that I should probably be more strict about this, with an interface or even just specifying that it's any, but is this a planned for change or issue?  I did a quick search and looked at the release notes but nothing relevant jumped out at me.  So thought I'd let you know :)

In the following hunk, rooms.promote is an array of objects.  

**TypeScript Version:**  2.5.1

**Code**

```
let roomVO:RoomVO;

_.each(this._config.rooms.promote, promote => {
    roomVO = _.remove(rooms, room => room.Id === promote.id)[0];
    //    blah
```

**Expected behavior:**
The single promote param for the function should be treated as any.  It was until 2.5.1 (possibly 2.5.0?)

**Actual behavior:**
Typescript now throws an error as it believes promote is of type string.  It's not critical; this works...
`_.each(this._config.rooms.promote, (promote: any) => {`

Thanks

**Comment by DanielRosenwasser** [comment]
Could you give a complete and self-contained reproduction of the issue you're running into? It'll be hard to diagnose the problem otherwise.

**Comment by fizzgig23** [comment]
Sure.  I started putting together a test earlier without lodash but it isn't exhibiting the same behaviour.  Could be the nested function isn't inferring? All I know so far is that it was fine before the latest package update.  2.4.2 didn't error.  I wouldn't even mention it cos the workaround is evident but it sort of breaks the tenet of being able to adopt TS gradually.

I'll look tomorrow.  It's 12:15am in the UK :)  

Thanks for replying

**Comment by fizzgig23** [comment]
I'm starting to wonder if it's the lodash d.ts actually. If I use Array.map it doesn't complain.

**Comment by fizzgig23** [comment]
Yep.  New lodash d.ts issue.

https://github.com/DefinitelyTyped/DefinitelyTyped/issues/19228

Closing
