### ISSUE TITLE
Signature test with overloading not working

### ISSUE THREAD

**Issue by HolgerJeromin** [Microsoft/TypeScript#18002]
**TypeScript Version:**  2.4.1

**Code**

```ts
export class api {
    public static works();
    public static works(propertyName: string);
    public static works(propertyNames: string[]);

    public static works(propertyName?: string | string[]) {
        return system.testing(propertyName as string); // No idea why the type assertion is needed
    }
    public static worksNot();
    public static worksNot(propertyName: string);
    public static worksNot(propertyNames: string[]);

    public static worksNot(propertyName?: string | string[]) {
        return system.testing(propertyName); // compile error!
    }
}     

export class system {
    public static testing();
    public static testing(propertyName: string);
    public static testing(propertyNames: string[]);
    // [Edit] needs
    //public static testing(propertyName?: string | string[])

    public static testing(propertyName?: string | string[]) {
        // Do some stuff with string or string[]
        return;
    }
}
```

**Expected behavior:**
Should compile without a problem
**Actual behavior:**
 error TS2345: Build:Argument of type 'string | string[]' is not assignable to parameter of type 'string[]'.

**Comment by ikatyang** [comment]
Duplicate of #17508.

**Comment by HolgerJeromin** [comment]
Thanks for the link. 
But IMO this is still a bug.

**Comment by kitsonk** [comment]
It maybe your opinion, but this has been discussed quite a lot before.  #17508 is just one example.

The reason it doesn't work is because of the need for co-variant types, which at the moment is problematic with TypeScript.  That being said, it also is totally redundant now that we have union types.  We used to have to expand overloads because we didn't have the union types, now we don't.

**Comment by HolgerJeromin** [comment]
Ok, thanks a lot both of you. My usecase is solvable. 
And you are right. It is better to leave it like that for the big picture.
