### ISSUE TITLE
how put 'declare'?

### ISSUE THREAD

**Issue by gearintellix** [Microsoft/TypeScript#18019]
it just example from my code structure:

file 'app.d.ts'
```
declare namespace app {
   var a: number;
}
```

file 'app.node.d.ts'
```
declare namespace app {
   namespace node {
      var b: number;
   }
}
```

Visual Studio 2017 update r3
Project UWP JS
```
Error TS1046	Build: A 'declare' modifier is required for a top level declaration in a .d.ts file
```

how to fixed it? or that a bugs?

-thanks

**Comment by mhegazy** [comment]
I can not reproduce this issue locally. can you share more context? your project, or a simpler reproduction of the issue.

**Comment by gearintellix** [comment]
Well, it turns out the problem on intelliSense vs2017
After i restarted visual studio, everything going well

> As information, several times visual studio crash when i coding in js and typescript
> when I do things differently than usual (documentation)
> i used jsdoc standard (http://usejsdoc.org/)
> yea, i think the problem is on intelliSense too

-thanks
