### ISSUE TITLE
Error with object shorthand + parens + this type

### ISSUE THREAD

**Issue by jwbay** [Microsoft/TypeScript#18021]
**TypeScript Version:**  Latest 2.4 and playground

**Code**
[Playground link](http://www.typescriptlang.org/play/index.html#src=let%20broken%20%3D%20(%7B%0D%0A%20%20%20%20readAsBinaryString(this%3A%20FileReader)%20%7B%20%7D%0D%0A%7D)%3B%0D%0A%0D%0Alet%20works1%20%3D%20(%7B%0D%0A%20%20%20%20readAsBinaryString(x%3A%20string)%20%7B%20%7D%0D%0A%7D)%3B%0D%0A%0D%0Alet%20works2%20%3D%20%7B%0D%0A%20%20%20%20readAsBinaryString(this%3A%20FileReader)%20%7B%20%7D%0D%0A%7D%3B%0D%0A%0D%0Alet%20works3%20%3D%20(%7B%0D%0A%20%20%20%20readAsBinaryString%3A%20function(this%3A%20FileReader)%20%7B%20%7D%0D%0A%7D)%3B%0D%0A)

```ts
let broken = ({
    readAsBinaryString(this: FileReader) { }
});

let works1 = ({
    readAsBinaryString(x: string) { }
});

let works2 = {
    readAsBinaryString(this: FileReader) { }
};

let works3 = ({
    readAsBinaryString: function(this: FileReader) { }
});
```

**Expected behavior:**
All parse correctly

**Actual behavior:**
Lots of squigglies in the first one, rest are fine

**Comment by DanielRosenwasser** [comment]
Issue is probably that we end up trying to parse an arrow function with an object literal binding.
