### ISSUE TITLE
Reference highlight is broken in Visual Studio 2017.3

### ISSUE THREAD

**Issue by Peter-Juhasz** [Microsoft/TypeScript#18037]
**TypeScript SDK Version:**  2.4.1.0
**Visual Studio version:** 2017.3.2
**TypeScript for Microsoft Visual Studio version:** 15.3.10723.1

**Code**
```ts
let a = 1;
a // a should be highlighted
```

**Expected behavior (C#):**
Highlight definition and references
![image](https://user-images.githubusercontent.com/9047283/29704874-e3af4d68-897b-11e7-81b4-1a05958cf7b3.png)

**Actual behavior:**
Neither the definition nor references are highlighted
![image](https://user-images.githubusercontent.com/9047283/29704907-05143036-897c-11e7-8ae9-f2f0bcd99b08.png)

**Comment by amcasey** [comment]
VS-side fix has been checked in.

**Comment by bm-software** [comment]
I've just updated Visual Studio 2017 to version 15.3.4. This problem still exists.
How can I solve the issue?

**Comment by amcasey** [comment]
@bm-software I haven't specifically confirmed, but I believe the fix is available in 15.4 Preview 1.

**Comment by bm-software** [comment]
@amcasey Oh ok! Then I'll wait for it, thank you!
