### ISSUE TITLE
TSServer: poor performance/crashing when there is high memory pressure

### ISSUE THREAD

**Issue by danielscottjames** [Microsoft/TypeScript#18055]
When ran from VS Code, TSServer has ~2GB of heap space available. Our TypeScript project is now large enough that TSServer consistently reaches this limit while editing files. I've observed the following symptoms happening consistently when this occurs:

- TSServer memory usage reaches ~2GB
- When profiling with Chrome devtools, the CPU spends ~90-95% non-productively garbage collecting.
- Some requests (such as opening a large file) seem to never be able to complete, other times requests complete slowly (10-20X more slowly).
- Eventually, TSServer crashes, this seems to happen most often after switching quickly between open files and/or hovering over many symbols to get their information.

When I run my fork of VS Code that runs TSServer with `--max_old_space_size=4096`, it seems that in any realistic editing scenario TSServer doesn't use more than ~75% of the available memory. (~3GB/4GB)

Some resolutions I can think of...
1) The amount of TypeScript we have is considered an edge case, and TSServer doesn't change. We continue using a fork of VS Code or adjust our project organization to be more performant with TSServer.
2) VS Code always starts TSServer with more memory, or provides a configurable flag.
3) TSServer somehow detects a high memory pressure situation (not trivial afaik, maybe by using https://nodejs.org/api/v8.html), and reduces memory usage before servicing requests.
4) Default resource allocation of a Node process (1 core, ~1.7GB of RAM) is not enough, split up work between multiple child processes. (Perhaps by having a child process per `Configured Project`?) I'm guessing this would be very ambitious.
5) ...? 

I'm interested to know what you guys think and I can provide more details/information if necessary.

(Note this happens across multiple versions of TSC (Currently using 2.4.2), and TSServer appears to be behaving correctly. i.e. there's just a lot of code and TSServer as designed doesn't have the necessary resources to handle it.)

**Comment by mhegazy** [comment]
We would love to get access to the code and see what we can do to optimize the usage in your case.  the performance is, as you noted, a side effect of the high memory pressure; V8 does not handle high memory well. we need to understand where most of the memory is gone, and why, and what strategies we can recommend to reduce the memory load. we have recently fixed a few memory leaks as well, so it is possible we have some left that we need to resolve.
We would be happy to sign any NDA to get access to the sources. 

also cc @sheetalkamat

**Comment by mhegazy** [comment]
As for the `-max_old_space_size`, i do not think this is hard to do, adding @mjbvz for that.
but i would rather we figure out what is going on first and see if we can do better before throwing more resources at the problem.

**Comment by mjbvz** [comment]
Yes, we should easily be able to start the server with that argument. Let me know if you want me to look into this next VS Code iteration

**Comment by stringham** [comment]
@mjbvz that would be great if we could get this in with the next vscode iteration. Right now a lot of us are running a custom build and it would be nice to get back onto the official build. Should we file an issue in the vscode project for this?

**Comment by mjbvz** [comment]
@stringham Yes please. It's too late to get this change in for VSCode 1.16 but I should be able to get in in the 1.17 insiders builds once those start up

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
