### ISSUE TITLE
MSB6006: "tsc.exe" exited with code 1. Script failed with error: 'JsErrorScriptException (0x3001)' if the inputs are on a partition without drive letter

### ISSUE THREAD

**Issue by ericwj** [Microsoft/TypeScript#18061]
**TypeScript Version:**
* 2.3.5
* 2.4.1
* 2.5.0 (RC)

**Code**
Basically every TypeScript compilation I try to do inside VS 15.3.2 breaks, however I configure TypeScript.
* This is likely a ChakraCore issue.
* Visual Studio will merely complain "tsc.exe" had a non-zero exit code.

The project is under `%userprofile%\Source` and `dir %userprofile%\Source.*` yields  
```
02-May-15 22:47 <JUNCTION> Source [\\?\Volume{6079456d1-12ab-34cd-9786-dd0177e78a39}\Source]
```  
i.e. it is created with `mklink /J` to a directory on a VHDX and that partition does not have a drive letter.

```
C:\Users\Eric\Source\Project\>"C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.5\tsc.exe" --target ES5 -lib es5,es2015,dom --listEmittedFiles wwwroot\ts\site.ts
```
* `Script failed with error: 'JsErrorScriptException (0x30001)'. The system cannot find the path specified.`  
And a stack trace follows with no futher clues as to which path was not found or why.  
This is also what Visual Studio will show in the Build Output with Build Verbosity Detailed.

```
pushd "C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.5"
tsc ...
```
* `../../../../Users/Eric/Source/Project/wwwroot/ts/site.ts(3,15): error TS2304: Cannot find name '$'.`  
However `npm list` will happily cough up `@types/jquery@3.2.12`.

```
$Partition | Set-Partition -NewDriveLetter D
tsc ...
```  
* Works without problem. Note I'm not using D at all:  
`TSFILE: C:/Users/Eric/Source/Project/wwwroot/ts/site.js`

**Expected Behavior**
```
TSFILE: C:/Users/Eric/Source/Project/wwwroot/ts/site.js
```

**Actual Behavior**
Either
```
Script failed with error: 'JsErrorScriptException (0x30001)'.
The system cannot find the path specified.

Error: The system cannot find the path specified.
   at ChakraHost.realpath (Unknown script code:2529:70)
   at ts.sys.realpath (Unknown script code:55470:62)
   at realpath (Unknown script code:17893:9)
   at resolveTypeReferenceDirective (Unknown script code:17525:17)
   at loader_2 (Unknown script code:55680:66)
   at loadWithLocalCache (Unknown script code:55628:17)
   at resolveTypeReferenceDirectiveNamesWorker (Unknown script code:55681:113)
   at createProgram (Unknown script code:55695:17)
   at compile (Unknown script code:59034:9)
   at performCompilation (Unknown script code:58924:13)
   at executeCommandLine (Unknown script code:58867:9)
   at Global code (Unknown script code:59225:1)
```
or
```
../../../../Users/Eric/Source/Project/wwwroot/ts/site.ts(3,15): error TS2304: Cannot find name '$'.
TSFILE: C:/Users/Eric/Source/Project/wwwroot/ts/site.js
```

**Comment by ericwj** [comment]
`node_modules\.bin\tsc --target ES5 -lib es5,es2015,dom --listEmittedFiles C:\Users\Eric\Source\Project\wwwroot\ts\site.ts`  
Also builds just fine without drive letter. Yet my project would still not build at all since TypeScript compiles first and aborts the build due to the exit code 1.

**Comment by mhegazy** [comment]
I am unable to reproduce this issue locally. please reopen if you can share more info.

**Comment by ericwj** [comment]
`tsc` (2.8.3) seems to work without drive letter (running on C: with the volume containing the solution directory mapped to an empty NTFS folder) although setting up a new ASP.NET Core project (preview2) with TypeScript, `tsc` isn't invoked or no .js file is produced whatever I put in the .csproj. But that's neither with or without a drive letter mapped.
