### ISSUE TITLE
Function Type Compiles When Not All Arguments Are Provided

### ISSUE THREAD

**Issue by willisplummer** [Microsoft/TypeScript#18063]
**TypeScript Version:**  2.4.2

**Code**

```ts
type Reducer<S> = (state: S, action: number) => S;

type Reducer2 = (state: string, action: number) => string;

// this should blow up because a reducer takes two arguments?
const reducer: Reducer<string> = (s: string) => s;

// this should blow up because a reducer takes two arguments?
const reducer2: Reducer2 = (s: string) => s;
```

**Actual behavior:**

I'm really confused about why this is compiling? Am I missing something?

**Comment by kitsonk** [comment]
From the FAQ [Why are functions with fewer parameters assignable t functions that take more parameters](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-functions-with-fewer-parameters-assignable-to-functions-that-take-more-parameters).

This is not a questions forum.  Questions should be asked on StackOverflow or Gitter (or reading reference information).  Also [search is your friend](https://github.com/Microsoft/TypeScript/search?q=functions+can+ignore+arguments&type=Issues&utf8=%E2%9C%93).

**Comment by willisplummer** [comment]
Ah, sorry for missing that... I thought I had found a bug which is why I wrote an issue. I followed up on StackOverflow about [how to write a function type that does require any function assigned to it accept all the same parameters](https://stackoverflow.com/questions/45899039/how-do-i-write-a-function-type-that-strictly-requires-its-parameters-in-typescri). Closing this issue
