### ISSUE TITLE
Can't install typescript with npm, integrity check fails

### ISSUE THREAD

**Issue by jmfgdev** [Microsoft/TypeScript#18067]
Couldn't install typescript when I tried just now, My NPM version is: 5.3.0 and my node version is 8.4.0

**Expected behavior:**
Successful install

**Actual behavior:**
npm ERR! sha1-+DlfhdRZJ2BnyYiqQYN6j4KHCEQ= integrity checksum failed when using sha1: wanted sha1-+DlfhdRZJ2BnyYiqQYN6j4KHCEQ= but got sha1-J8Hi9bh5ntWCV+b4Tqo
bbK0XVTA=. (32240 bytes)

**Comment by ikatyang** [comment]
It looks like an npm issue https://github.com/npm/npm/issues/17146.

**Comment by DanielRosenwasser** [comment]
Can you try with any of the suggestions in the issue @jmfgdev?

**Comment by jmfgdev** [comment]
I'm currently downgrading my nodejs to the LTS release, so I might not encounter the same bug

**Comment by kitsonk** [comment]
I have encountered very similar issues several times with npm 5.  It seems that it sometimes is very sensitive to individual network conditions and assuming things are corrupted.  Typically though a `rm -rf node_modules` and a `rm package-lock.json` are enough to resolve the issue (though as noted in the linked issue, sometimes a purge of the npm cache is required).

**Comment by jmfgdev** [comment]
As I suspected the issue was fine by the time I downgraded from 8 to 6

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
