### ISSUE TITLE
Automatic exhaustiveness checking

### ISSUE THREAD

**Issue by notsonotso** [Microsoft/TypeScript#18076]
Manual enforcement of exhaustiveness (https://basarat.gitbooks.io/typescript/docs/types/discriminated-unions.html) is less than ideal. Doing exhaustive checking is critical to correctness, and now checking for this requires a manual step.

What prevents the compiler from injecting the never-type test?

Maybe there needs to be an opt-out mechanism, but I sure would like such a check by default.

**Comment by RyanCavanaugh** [comment]
It's not at all apparent that a non-exhaustive check indicates incorrect code. Moreover there isn't really a "place" where exhaustiveness checking happens, it's simply a behavior that emerges from union types.

**Comment by notsonotso** [comment]
@RyanCavanaugh you are wrong, Ceylon has union types and implements exhaustiveness checking.

**Comment by notsonotso** [comment]
Nice work closing issues which you don't understand.

**Comment by RyanCavanaugh** [comment]
You can explain more about how you'd want this to work, with some examples, rather than just "you are wrong".
