### ISSUE TITLE
Why the assignment of the reference differs from the assignment of object literal?

### ISSUE THREAD

**Issue by acopalipsis** [Microsoft/TypeScript#18070]
```
interface Type {
    name: string;
}

let a = {name: '', age: 0};
let b: Type = a; // Ok
let c: Type = {name:'', age:0}; // Error, why?
```
1. Why the assignment of the reference differs from the assignment of object literal?
2. in both cases, rules assignment compatibility?

**Comment by RyanCavanaugh** [comment]
See https://stackoverflow.com/questions/45868086/generic-function-allow-arbitrary-keys/45868742#45868742
