### ISSUE TITLE
`let` as an identifier (in strict mode), `let let`, and `const let` (both in either mode) should prevent emit

### ISSUE THREAD

**Issue by isiahmeadows** [Microsoft/TypeScript#18079]
See [section 13.1.1.1](https://tc39.github.io/ecma262/#sec-let-and-const-declarations-static-semantics-early-errors) for `let`/`const`, and [section 12.1.1](https://tc39.github.io/ecma262/#sec-identifiers-static-semantics-early-errors) for `var let` and friends.

**TypeScript Version:**  Whatever's on the playground

**Code**

All of these lines should be treated individually.

```ts
// Strict mode: all invalid
// Sloppy mode: first 2 invalid
let let;
const let = 1;
var let;
let;
```

**Expected behavior:**

No emit

**Actual behavior:**

The following emit in both strict and sloppy mode:

```js
var let;
var let = 1;
var let;
let;
```

**Comment by kitsonk** [comment]
The first three lines are throwing typescript errors.  TypeScript will always emit, even when there are are errors present in the code, unless of course no emit is specified.

**Comment by mhegazy** [comment]
As @kitsonk noted, emit is not blocked by default in the face of errors. use `--noEmitOnError` to block emit.

**Comment by isiahmeadows** [comment]
So for clarification, early errors are non-fatal?

**Comment by kitsonk** [comment]
All errors in TypeScript are non-fatal, unless the `--noEmitOnError` flag is used and then all errors are fatal.
