### ISSUE TITLE
Can't append two string literal type values

### ISSUE THREAD

**Issue by justinwoo** [Microsoft/TypeScript#18081]
I'd like to append two `const` string literal values together and extract or assign a new string literal type.

Sorry if this is a duplicate of something, I couldn't find an existing issue.

**TypeScript Version:**  2.4.2 / PlayGround

**Code**

```ts
const APPLE = 'APPLE';
const PINEAPPLE = 'PINEAPPLE'

type AppleLiteralType = 'APPLE'
const APPLE2: AppleLiteralType = APPLE

// this is only `string`,
// even though it's two literals appended
const APPLEPINEAPPLE = APPLE + PINEAPPLE;

// Type 'string' is not assignable to type '"APPLEPINEAPPLE"'.
const Test: 'APPLEPINEAPPLE' = APPLE + PINEAPPLE;
const Test2: 'APPLEPINEAPPLE' = `${APPLE}${PINEAPPLE}`;
```

**Expected behavior:**
`Test` and/or `Test2` should work with the `'APPLEPINEAPPLE' string literal type

**Actual behavior:**
`Test` and `Test2` both turn into `string` types

**Comment by ikatyang** [comment]
Duplicate of #12940 or #17512.

**Comment by justinwoo** [comment]
Ahh, thanks!
