### ISSUE TITLE
Spec contradicts to itself in one of the examples with type guards

### ISSUE THREAD

**Issue by zhuravlikjb** [Microsoft/TypeScript#1808]
In the [section about type guards](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#420-type-guards), the last example seems to be invalid:
```javascript
class NamedItem {  
    name: string;  
}

function getName(obj: any) {  
    return obj instanceof NamedItem ? obj.name : "unknown";  
}
```
It is stated that `the inferred type of the 'getName' function is string`, but actually 'any' type won't be narrowed, according to the same spec, and compiler doesn't do that either:

![getname](https://cloud.githubusercontent.com/assets/4499495/5901140/09a9c548-a581-11e4-9912-a5fb6831998a.png)

A bug in the spec?

**Comment by ahejlsberg** [comment]
Yes, that is a bug in the spec.
