### ISSUE TITLE
Mixed-valued literal enums assignability issue

### ISSUE THREAD

**Issue by zhuravlik** [Microsoft/TypeScript#18082]
**TypeScript Version:**  2.6 (just checked out)

**Code**

```ts
enum E {
  A = 1,
  B = "2"
}

var q: E.A = 1; // okay
var z: E.B = "2"; // error TS2322: Type '"2"' is not assignable to type 'E.B'
```

**Expected behavior:**
In both cases assignability should work the same way.

**Actual behavior:**
Assignability passes with numeric literal enum values, but doesn't pass with string literal enum values

**Comment by zhuravlik** [comment]
By the way, looks like typechecking for numeric items in such mixed enums doesn't work at all
`
var q: E.A = 5; // still okay
`

**Comment by ikatyang** [comment]
> var z: E.B = "2"; // error TS2322: Type '"2"' is not assignable to type 'E.B'

This one seems duplicate of #16851.

**Comment by mhegazy** [comment]
The numeric values allowing numbers is there to support bit flags. it is a common use case of enums, and changing that would be a massive break. see similar discussion in https://github.com/Microsoft/TypeScript/issues/17734.

The string values behave as i would expect. enums are "tagged" versions of the string literals. the enum member type is assignable to the string literal type but not vice versa, other wise rename operations are not guaranteed to work.

**Comment by zhuravlik** [comment]
@mhegazy Thanks a lot for the explanation.
