### ISSUE TITLE
Cannot require pure C++ module

### ISSUE THREAD

**Issue by t123yh** [Microsoft/TypeScript#18083]
**TypeScript Version:**  2.4.2

**Code**
```bash
mkdir test && cd test
npm install syspipe
echo "import syspipe = require('syspipe');" > 1.ts
tsc 1.ts
```

**Expected behavior:**
Generate `const syspipe = require('syspipe');`

**Actual behavior:**
`1.ts(1,26): error TS2307: Cannot find module 'syspipe'.`

Note: the `package.json` in `syspipe` module has a `main` file `build/Release/syspipe.node`. If I change that to some js file, then the process will complete fluently.

**Comment by aluanhaddad** [comment]
You should either find a declaration or create one.
Try
```bash 
npm install --save @types/syspipe
```
If that doesn't turn up anything,
```ts 
$ echo "declare module 'syspipe';" > global.d.ts && echo "import syspipe = require('syspipe');" > 1.ts 
```

**Comment by t123yh** [comment]
I consider this a bug rather than a question. IMO we should have the ability to require such module without a declaration file because the C++ code is equal to js.

**Comment by SaschaNaz** [comment]
Every module requires a declaration file, so does syspipe.

BTW, TypeSearch shows no declaration for syspipe.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
