### ISSUE TITLE
emitDecorator metadata creates bad circular reference

### ISSUE THREAD

**Issue by staeke** [Microsoft/TypeScript#18080]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)
2.4.2

**Code**
I'm not sure whether this is a bug in TypeScript or webpack. Starting here. Please let me know if I should move the issue

Consider this code for circular reference modules:

```ts
//modal.ts
import {ModalContent} from './modal-content'
import {Component} from '@angular/core';

@Component({})
export class Modal {
    mc = new ModalContent(this)
}
```

```ts
//modal-content.ts
import {Modal} from './modal';
import {Component} from '@angular/core';

@Component({})
export class ModalContent {
    constructor(m:Modal) {}
}

```

With esnext and emitDecoratorMetadata this creates the following js

```js
// modal.js
import { ModalContent } from './.modal-content';
import { Component } from '@angular/core';
let Modal = class Modal {
    constructor() {
        this.mc = new ModalContent(this);
    }
};
Modal = __decorate([
    Component({})
], Modal);
export { Modal };
```

```js
//modal-content.js
import { Modal } from './.modal';
import { Component } from '@angular/core';
let ModalContent = class ModalContent {
    constructor(m) { }
};
ModalContent = __decorate([
    Component({}),
    __metadata("design:paramtypes", [typeof (_a = typeof Modal !== "undefined" && Modal) === "function" && _a || Object])
], ModalContent);
export { ModalContent };
var _a;
```

Currently, when piping this to the latest version of webpack (3.5.5), this produces this error:
```
: Modal is not defined
Stack:
modal.js /* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "a", function() { return Modal; });
modal-content.js   __metadata("design:paramtypes", [modal_1["a" /* Modal */]])
```

In other words, modal-content is adding an extra load time/static dependency on Modal through the implicit decorator of constructor parameter types. This breaks, as we haven't gotten to `let Modal = ...` yet. In other words, Modal isn't declared yet and produces an error when trying to be accessed. Don't know if the generated js by typescript is valid ES6 in which case I'd assume `Modal` in that case would be `undefined`.

Note that the example above is simplified. In the real-life scenario the constructor parameter is actually decorated with `@Inject` and `forwardRef` to get it to work. Also `Modal` doesn't just create `ModalContent` itself. Natually there is much more code that goes into both classes.

**Expected behavior:**

I'd expect this to not produce error. This could be accomplished either by 

1. having typescript generate a `var Modal..` instead of `let Modal...` as the var is hoisted. 
2. Or, detect circular references and in those cases either not emit the type or emit `Object`
3. Have some kind of mechanism of opting out of emitting the type for the constructor parameter per case.
4. you stating that this is in fact valid ES6 and webpack should handle it

**Actual behavior:**
Error according to above

**Comment by mhegazy** [comment]
This is a limitation to the existing design of metadata. the metadata value captures the value of the declaration, and in this case it is `undefined` because of the circular reference. we have plans to address that when we implement the new decorator proposal, see  https://github.com/Microsoft/TypeScript/issues/14971 for more details.

**Comment by staeke** [comment]
Thanks for the reply. I agree, duplicate.
