### ISSUE TITLE
Please ship interfaces for Text Encoding

### ISSUE THREAD

**Issue by oliverjanik** [Microsoft/TypeScript#18099]
As described here:
https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder

**Comment by kitsonk** [comment]
It is currently [In Development in Edge](https://caniuse.com/#feat=textencoder) which is likely why it isn't there already.

Additions are done by [contributing to TSJS-Lib-Generator](https://github.com/Microsoft/TSJS-lib-generator/#contribution-guidelines).

You can also use the community types for this experimental browser feature by installing [@types/text-encoding](https://www.npmjs.com/package/@types/text-encoding)

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by timbru31** [comment]
TS 2.8 ships TextEncoder typings in lib.dom.d.ts - this issue can be closes 🎉 (commit https://github.com/Microsoft/TypeScript/commit/79e5e79ef7724066889fbce97e9e6d6db4e746b5 and https://github.com/Microsoft/TSJS-lib-generator/commit/e79823fef7163a5ca291103dbc4b01dbb895ddbd#diff-2f12bfc74895ba966e83c710b18b2da1)

**Comment by mhegazy** [comment]
thanks @timbru31 for looking this up. closing.
