### ISSUE TITLE
Extract function produces parameter whose type is not correctly narrowed

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#18092]
```ts
export function evaluate(node: Expression): number {
    switch (node.kind) {
        case "Parenthesized":
            /*[|*/
            while (node.expression.kind === "Parenthesized") {
                node = node.expression;
            }
            return evaluate(node.expression);
            /*|]*/
        case "NumericLiteral":
            return node.value;
    }
}
```

Extract a function from the `[|` and `|]` comments.

**Expected**:

```ts
type Expression = ParenthesizedExpression | NumericLiteralExpression;

interface ParenthesizedExpression {
    kind: "Parenthesized";
    expression: Expression;
}

interface NumericLiteralExpression {
    kind: "NumericLiteral";
    value: number;
}

function newFunction(originalNode: ParenthesizedExpression) {
    let node: NumericLiteral | ParenthesizedExpression = originalNode;
    while (node.expression.kind === "Parenthesized") {
        node = node.expression;
    }
    return { __return: evaluate(node.expression), node };
}

```

**Actual** (after formatting): 

```ts
function newFunction(node: NumericLiteral | ParenthesizedExpression) {
    while (node.expression.kind === "Parenthesized") {
        node = node.expression;
    }
    return { __return: evaluate(node.expression), node };
}
```

Note that the produced code won't type-check.

**Comment by amcasey** [comment]
Does that just mean we made the wrong call to the checker?  Type instead of ContextualType or something?

**Comment by amcasey** [comment]
It's not broken across the board.  Extract `x.foo` or `x.bar` into the global scope generates a parameter of the correct type.

```
interface Foo { foo: string }
interface Bar { bar: string }

function IsFoo(x: Foo | Bar): x is Foo { return x.hasOwnProperty("foo"); }

function Test(x: Foo | Bar) {
    if (IsFoo(x)) {
        x.foo.toString();
    }
    else {
        x.bar.toString();
    }
}
```

**Comment by amcasey** [comment]
The code above compiles with these types:

```ts
type Expression = ParenthesizedExpression | NumericLiteralExpression;

interface ParenthesizedExpression {
    kind: "Parenthesized";
    expression: Expression;
}

interface NumericLiteralExpression {
    kind: "NumericLiteral";
    value: number;
}
```

**Comment by amcasey** [comment]
The fact that it won't work when `node` is captured, rather than passed, is known.  Unless it becomes a source of substantial confusion, fixing/prohibiting it is not a high priority.

**Comment by amcasey** [comment]
Extracting `node.value` works correctly (i.e. the parameter type is `NumericLiteralExpression`.

**Comment by amcasey** [comment]
I'm pretty sure the issue is that the type of `node` is `Expression` on the LHS of `node = node.expression`.  I'm assuming that's why you distinguish between `node` and `originalNode` in the Expected output.

**Comment by amcasey** [comment]
Conceivably, we could address this by introducing a local with the declared type of every argument passed with a narrower type (as in the expected code above).  We'd probably end up with more redundant locals, but it would address cases like this.

At the moment, I'm inclined to wait and see if we get more reports of this issue.

**Comment by RyanCavanaugh** [comment]
Seems like no one noticed
