### ISSUE TITLE
Parse backtick delineated string without interpolation as string literals

### ISSUE THREAD

**Issue by erkalicious** [Microsoft/TypeScript#18109]
**TypeScript Version:**  2.4.0

**Code**

```ts
let test: `a` | `b`
```

**Expected behavior:**
`test` will be a variable of type `"a" | "b"`, like when single quotes or double quotes are used.

**Actual behavior:**
It does not compile, giving various errors.

**Justification:**
We like to enforce the use of template strings instead of concatenation, but that leaves us with a mixture of backtick strings and either double or single quote strings. Ideally we would enforce just one type of quote throughout our projects and leave it at that. In order to utilize the power of template strings, we should obviously enforce only backticks for strings.

The problem now is that the compiler doesn't accurately parse strings delineated by backticks. When backtick delineated strings don't have any interpolation in them, the compiler should be able to recognize that they are just literal strings and should use them for type inference and everything else.

**Comment by erkalicious** [comment]
I'd argue that this is a duplicate of #16592 and that that particular issue wasn't fully fixed by #17704. 

@DanielRosenwasser 
> We should just allow people to use NoSubstitutionTemplates the way that they're allowed to use regular strings.

That also includes being able to put `NoSubstitutionTemplate`s as types, and anywhere else that string literals can be used.

**Comment by mhegazy** [comment]
closing in favor of  #16592. thanks.
