### ISSUE TITLE
Documentation: --strictNullChecks behaves slightly different than doc says

### ISSUE THREAD

**Issue by bodawei** [microsoft/TypeScript#18103]
**Code**

In https://www.typescriptlang.org/play/index.html
```ts
let x: void = undefined;
let x1: void = null;

let x2: null = undefined;
let x3: undefined = null;
```
**Expected behavior:**
According to the doc:
https://www.typescriptlang.org/docs/handbook/basic-types.html

> However, when using the --strictNullChecks flag, null and undefined are only assignable to void and their respective types. This helps avoid many common errors. In cases where you want to pass in either a string or null or undefined, you can use the union type string | null | undefined. Once again, more on union types later on.

when --strictNullChecks is on, x2 and x3 should be errors.

**Actual behavior:**

x1, x2 and x3 are all reporting errors.

(in truth, I don't know if the doc or the implementation is wrong)

**Comment by RyanCavanaugh** [comment]
The spec is now an "archived" artifact and we won't be tracking defects against it anymore.
