### ISSUE TITLE
Import codefix with baseUrl suggests incorrect paths

### ISSUE THREAD

**Issue by asvetliakov** [Microsoft/TypeScript#18106]
**TypeScript Version:**  2.4.2

**The Problem:**
When using baseUrl to override some packages in ```node_modules/@types``` (as i know there is no other way to do it without baseUrl) the import codefix imports local project symbols with incorrect paths.

Given following project structure
```
 src/
   a.ts
   b.ts
 types/
   some-module
 tsconfig.json
```

tsconfig.json:
```json
{
    "compilerOptions": {
        "strict": true,
        "target": "es2016",
        "module": "commonjs",
        "moduleResolution": "node",
        "outDir": "./compiled",
        "typeRoots": [
            "types",
            "node_modules/@types"
        ],
        "baseUrl": "./", // Setting baseUrl is required to locally override/add packages from node_modules/@types
        "paths": {
            "*": [
                "types/*"
            ]
        }
    },
    "include": [
        "src/**/*"
    ],
    "exclude": [
        "node_modules",
        "compiled"
    ]
}
```

and files:

a.ts:

```ts
export class A { }
```

b.ts:

```ts
const a: A; // codefix on A
```

**Expected behavior:**
import codefix generates ```import { A } from "./a";```

**Actual behavior:**
import codefix generates ```import { A } from "src/a;"```

**Comment by mhegazy** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/15888

**Comment by asvetliakov** [comment]
Yep, thanks
