### ISSUE TITLE
Request Objects

### ISSUE THREAD

**Issue by phanivaranasi** [Microsoft/TypeScript#18105]
Hi Team,
In my project, I'm using TypeScript  - with Requirejs - 
I have an blocker, when my customers browse my website in their smart phones.
I need to get request headers, similarly how we used to get request headers in ASP.NET.

Could any one suggest me right approach for fetching headers

Thanks
Krishna

**Comment by kitsonk** [comment]
This is not a support forum.

Questions should be asked on [StackOverflow](http://stackoverflow.com/questions/ask?tags=typescript) or in [Gitter.im](https://gitter.im/Microsoft/TypeScript)
