### ISSUE TITLE
Question on JSDoc array type precedence with '!' and '?'

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#18104]
It appears that we're parsing the two of these out quite differently.

```ts
interface ButHow {}
var a: ...ButHow!?;
var b: ...ButHow?;
```

See quick fixes for proof:

![image](https://user-images.githubusercontent.com/972891/29805921-5c7e221a-8c41-11e7-9f07-1f977a4f2c92.png)
![image](https://user-images.githubusercontent.com/972891/29805937-6f1895b8-8c41-11e7-8df7-bbeb225495ab.png)

Is this by design? CC @sandersn

**Comment by sandersn** [comment]
There isn't really any precedent one way or another, but I think it makes sense for postfix syntax to bind less tightly than prefix syntax. 

So `...X!?`, `...X?` and `...X?!` should all convert to `X[] | null`. They don't today; I think the two changes that have to happen are (1) `...` should not call `parseType` but `parseNonArrayType` (2) `parseJSDocPostfixTypeOrHigher` should parse as many postfix tokens as are present.
