### ISSUE TITLE
Array.prototype.find should consider type guards

### ISSUE THREAD

**Issue by roddolf** [Microsoft/TypeScript#18112]
It would perfect to pass a type guard to `Array.prototype.find` to find and cast an object
like `Array.prototype.filter` does.

**Comment by jcalz** [comment]
Oh, whoops, dueling pull requests.  I defer to @NaridaL's unless there's something particularly compelling about mine.

**Comment by NaridaL** [comment]
@jcalz No, https://github.com/Microsoft/TypeScript/pull/18116 has broken mine. I'll close it.

**Comment by NaridaL** [comment]
See https://github.com/Microsoft/TypeScript/pull/18160 instead.
