### ISSUE TITLE
Type declaration from d.ts file not merged with actual declaration in js file

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#18115]
From https://stackoverflow.com/questions/45944663/visual-studio-code-type-hints-for-javascript-files/45944869

**TypeScript Version:**  2.5.1

**Code**

`file.js`:

```js
// @ts-check
function f(x) { return x * 2; }
f('Not a number'); // This should be an error 
```

`file.d.ts`

```ts
declare function f(x: number): number;
```

`jsconfig.json`
```json
{
    "compilerOptions": {
        
    }
}
```

**Expected behavior:**
In `file.js`, the type of `f` is `function(x: number): number`

**Actual behavior:**
In `file.js`, the types of `f` is `function(x: any): number`

If you comment out the declaration of `f` in `file.js`, you get the correct type

**Comment by mhegazy** [comment]
Declarations from a .d.ts does not merger with these in a .js. use JSDoc annotations in the .js file to specify the type.

**Comment by mjbvz** [comment]
Thanks. I'm not sure what the asker's setup is but this makes sense
