### ISSUE TITLE
VS 2013 save and compile output vs build compile output

### ISSUE THREAD

**Issue by craigktreasure** [Microsoft/TypeScript#1812]
I have an enum in an interface that, when used in my TS code in TypeScript 1.3, was output as a constant. This is no longer the case in 1.4 after saving my file. When i build the project, the enum code is properly output as a constant. Using VS 2013 update 4 with TypeScript 1.4 installed.

Enum declaration file (Colors.d.ts):
```
declare module server {
    enum Colors {
        Red = 0,
        Green = 0,
        Blue = 0
    }
}
```
TS Code:
```
if(box.color === server.Colors.Red) {
...
}
```

JS Output after save:
```
if(box.color === server.Colors.Red) {
...
}
```

JS Output after build (correct, or what i consider to be correct since there is no implementation of the enum):
```
if(box.color === 0 /* Red */) {
...
}
```

The same is observed if the enum is declared using the new "const enum" feature.

**Comment by vladima** [comment]
Can you try the latest bits from master? It seems that root cause of this issue is the same with #1742 that was recently fixed

**Comment by craigktreasure** [comment]
What and where do I need to replace?

Sent from my Windows Phone
________________________________

**Comment by vladima** [comment]
- run 'jake clean local' to build the TypeScript compiler\language service bits  - build result will be dropped to 'build\local' folder
- go to `<ProgramFiles>\Microsoft Visual Studio 12.0\Common7\IDE\CommonExtensions\Microsoft\TypeScript`
- backup existing 'typescriptServices.js' somewhere and replace it with one that was build on the step 1

**Comment by basarat** [comment]
I've been getting this in `1.4` as well. Didn't investigate myself since I wasn't bothered but I've done many a commits like : https://github.com/TypeStrong/atom-typescript/commit/ed04b5805dcc34d17c3067b40689c0da976afcdc#diff-fe4e718ca060808778e53a950eb4764aL7 then again I had grunt, visual studio, and atom / ts language service fighting to build the same files :)

**Comment by craigktreasure** [comment]
@vladima A new copy of typescriptServices.js seems to have fixed the issue when i mark the enum declaration in the d.ts file as a const enum, but not for the scenario in which the enum is not a const enum.

**Comment by Stompf** [comment]
I've tried the new copy of typescriptServices.js and for me the problem still exists. It seems to work about 50% of the time when saving but in the other 50% it still compiles to a constant

**Comment by craigktreasure** [comment]
In my case, I want it to compile to a constant since it is declared in a declaration file and they're isn't an implementation of the enum.

Sent from my Windows Phone
________________________________

**Comment by Stompf** [comment]
Yea I mixed up the words :) What I mean is that the output still sometimes is wrong like "server.Colors.Red" instead of "0 /* Red */" in your example for me when I save in VS 2013 even with updated  typescriptServices.js. Tried edited my previous comment to reflect that

**Comment by vladima** [comment]
Can you write a short video with repro using [Screen2Gif](https://screentogif.codeplex.com/) or similar tool? If you can please also capture the structure of the virtual project in Solution Navigator and set of files at the top of the screen

**Comment by Stompf** [comment]
Hello! I tried building the latest master again and now it works, I think I did something wrong the first time (sorry first time building from master). So you can disregard me.

**Comment by vladima** [comment]
@craigktreasure can you please provide a video with repro that will involve non const enums?

**Comment by craigktreasure** [comment]
@vladima I'll send a sample project your way later today.

**Comment by mrcrowl** [comment]
This looks the same as the issue I'm having in #1916. 

Example project: https://www.dropbox.com/s/xc34f0q6rhc0amm/ExampleProject.zip?dl=0

**Comment by craigktreasure** [comment]
@vladima I believe this is fixed now.

**Comment by vytautas-pranskunas-** [comment]
I have replaced typescriptServices.js file and now on save it does not generate any file and console sys: "Input file contained syntax errors. Output generation skipped."

I do not have any errors and on build everything works fine.

**Comment by mhegazy** [comment]
Can you share a sample file where you are wrong this?

**Comment by vytautas-pranskunas-** [comment]
I dont know whic file exactly because after i pased same code to clean project it compile. However build passes with no errors. Console does not show anything on save except that error.

**Comment by mhegazy** [comment]
The issue would probably be linked to the contents of your project, it would help a lot if you can detect the code pattern that consistently triggers the issue.

**Comment by vytautas-pranskunas-** [comment]
Hello again,

I have found problem.
I reference <Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.Default.props" Condition="Exists('$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.Default.props')" />
in my proj file and props file contains this line:
<TypeScriptNoEmitOnError>true</TypeScriptNoEmitOnError>

if I remove it everything compiles fine.

p.s. off topic: mshould i update ToolsVersion="4.0" in same file because of typescriptservices.js file changed?

**Comment by DanielRosenwasser** [comment]
Use method syntax, since it will be initialized once on the prototype. The property initializer will be set in the constructor body and a new closure may be created once per instantiation.

**Comment by vytautas-pranskunas-** [comment]
Ok. What about my main problem about compilation problem of typescript with props set?

**Comment by mhegazy** [comment]
To disable noEmitOnError add a property to your project file, before the import you reference above:
```XML
  <PropertyGroup>
        <TypeScriptNoEmitOnError>false</TypeScriptNoEmitOnError>
    </PropertyGroup>
```

see my comment https://github.com/Microsoft/TypeScript/issues/2848#issuecomment-94880440 for more details.

also note, if you disable noEmitOnError your incremental build would not work as expected. see comment: https://github.com/Microsoft/TypeScript/issues/1915#issuecomment-73460237 for more details.

**Comment by vytautas-pranskunas-** [comment]
I have read all but still not get it right.
So as far as i understand emitonerror should always be true. And i do not want to disable it. I only pointed you the line with what compilation fails with 1.5 alpha.
So what should i do? Should i remove that line from props and it will be passed by default or this is a bug os 1.5 typescript because having that line in props looks reasonable.

**Comment by mhegazy** [comment]
Can you share the project sources where you are swing the issue? I do not think I understand the issue fully. 

noEmitOnError is set by default in projects. That means if you have any error in your error list nothing will be written to disk, that applies to compile on save and normal build (f5). If you want to change this behavior set noEmitOnError to false.

Are you saying you set it to false and nothing is emitted? Or is it that when it is true you get the "emit skipped" message even if your error list is clear?

**Comment by vytautas-pranskunas-** [comment]
No, I will try to explain again.
Because of enums being generated incorrect in 1.4 i replaced typescriptservice.js with 1.5 alpha build. After replacement, when i am trying to build project everything build fine, but when i am trying to save .ts i got an error "Input file contained syntax errors. Output generation skipped." You were asking me to  find out what cause this problem in my project because in greenfield there is no error. So after investigation i find out that i refference this line in my .proj file

```
<Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.Default.props" Condition="Exists('$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.Default.props')" />
```

and if i comment 

```
<TypeScriptNoEmitOnError>true</TypeScriptNoEmitOnError>
```

compile on save starts to work. 

So i asked is it a bug of 1.5 or what should I do to get 'compile on save' to work?

**Comment by vytautas-pranskunas-** [comment]
Daniel Rosenwasser - if I use functions over delegates what is the common practice to deal with global 'this' you can recommend? because this in function is local and in delegate is global.

**Comment by mhegazy** [comment]
when you get the message "Input file contained syntax errors. Output generation skipped." do you have any errors in your error list?

**Comment by vytautas-pranskunas-** [comment]
No, there are no errors. With 1.4 compiles perfectly.

**Comment by mhegazy** [comment]
I mean in VS, your error list, not the build.

**Comment by vytautas-pranskunas-** [comment]
Yes i mean it too :) No errors.
If there would be any errors i would fix those before rising an issue.

**Comment by mhegazy** [comment]
I will need to get a repro locally for this to be able to help more. can you share the project?

**Comment by vytautas-pranskunas-** [comment]
There is nothing to share actually. Have you tried to add line I pasted before? Because as I mentioned before it stops to compile when this import is in .proj file 

```
<Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.Default.props" Condition="Exists('$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.Default.props')" />
```

because of this line in that import

```
<TypeScriptNoEmitOnError>true</TypeScriptNoEmitOnError>
```

**Comment by mhegazy** [comment]
@vytautas-pranskunas- what kind of web project are you using. i am still not able to repro this issue with the different projects i tried.
![compileonsave](https://cloud.githubusercontent.com/assets/8000722/7404428/705b29ee-ee97-11e4-9ce7-c7c3fbc1ba75.gif)

**Comment by vytautas-pranskunas-** [comment]
I am doing it with empty MVC Web project.

**Comment by mhegazy** [comment]
I am sorry but i am still not able to get the same repro. Are you using VS2015 or VS2013? i have tried both with no luck, but just to be sure.
![compileonsave2](https://cloud.githubusercontent.com/assets/8000722/7418527/5eff7cf4-ef23-11e4-8364-eea72768e746.gif)

**Comment by vytautas-pranskunas-** [comment]
Vs2013. Its not only for me, its for all the team. Are you replacing only typescriptservices.js or something more?
I can create empty project and send it to you just tell me where. 
But it just plain setup as i wrote before.

**Comment by mhegazy** [comment]
can you give [TypeScript 1.5-Beta](https://github.com/Microsoft/TypeScript/releases/tag/v1.5.0-beta) on [VS2013](https://visualstudiogallery.msdn.microsoft.com/107f89a0-a542-4264-b0a9-eb91037cf7af) a try? it was just released :)

**Comment by vytautas-pranskunas-** [comment]
I defenetly will. Whats the best way to install it?

**Comment by vytautas-pranskunas-** [comment]
I defenetly will. Whats the best way to install it?

**Comment by mhegazy** [comment]
Here is the announcement: http://blogs.msdn.com/b/typescript/archive/2015/04/30/announcing-typescript-1-5-beta.aspx

here is the installer for VS2013: https://visualstudiogallery.msdn.microsoft.com/107f89a0-a542-4264-b0a9-eb91037cf7af

and the installer for VS2015 RC: https://visualstudiogallery.msdn.microsoft.com/3e5ba71c-abea-4d00-b81b-a62de3ad3d53

**Comment by vytautas-pranskunas-** [comment]
How this affects my MsBuild task? I mean should I update to 1.5 TS my CI server?

**Comment by mhegazy** [comment]
The TypeScript targets have a property that specify which version of the compiler to use. 
```XML
    <TypeScriptToolsVersion>1.4</TypeScriptToolsVersion>
```
if your project states `1.4` it will always build on the 1.4 compiler, even if you have 1.5 installed. so in this case you do not need to install it anywhere if you do not want to upgrade yet.

Installing the beta on production environments is up to your organizational policies. 

What i am looking for is to get a way to reproduce the issue you are running into to be able to diagnose it. It would be great if you can try the same project with same setup on 1.5 to see if the problem still exists.

**Comment by vytautas-pranskunas-** [comment]
I have tried 1.5 beta:
After installing beta vs2013 throwed some errors about typescriptLanguages asking should it continue to show this error or not.  After chosing "no" typescript compiler stoped generating .js files at all no matter what i did - tried to change ts version of the project and etc.
After uninstalling 1.5 i noticed that all tooling missing so i had to repair 1.4 :( after this everything went back to normal js files are generated except incorrect enums. When adding typescriptservices.js from alpha same as mentioned above happens.
Any thoughts?

**Comment by vytautas-pranskunas-** [comment]
More than this, after uninstall TS 1.5 beta i have run into problem that my current project not compiling because of incorrect typescript path Microsoft SDKa\TypeScript\1.4\1.4\tsc.exe
Seems like duplication of https://github.com/Microsoft/TypeScript/issues/2039
but I have tried to repair typescript 1.4 but with no luck. 
Any ideas how to fix this?

**Comment by mhegazy** [comment]
Can you share your install logs: %TEMP%\dd_TypeScript_*

**Comment by vytautas-pranskunas-** [comment]
Could you write full path to folder please?

**Comment by mhegazy** [comment]
well.. it depends where your temp folder is.. try:
> echo %TEMP%

mine is at: C:\Users\mhegazy\AppData\Local\Temp

**Comment by vytautas-pranskunas-** [comment]
Give me an email where to send zip please

**Comment by mhegazy** [comment]
mhegazy at microsoft

**Comment by vytautas-pranskunas-** [comment]
Hello again :)

We were still trying to fix that enum issue with cooworkers. 
Those examples you did while trying to reproduce it - did you put enums to .d.ts file? Because while trying to fix it we noticed that enums placed in .ts files generates as expected but enums placed in defentition files generates:
1) On build - as expected (TestEnum.One = 1 turns to 1)
2) On save - wrong (TestEnum.One = 1 turns to TestEnum.One)

Can you try to put enums in definition file and use it other file's class and then do compile on save.

**Comment by mhegazy** [comment]
so you are still on 1.4? or have you managed to updated to 1.5? The issue did exist with 1.4, and we believe it has been fixed in 1.5.

**Comment by rwilliams-scottlogic** [comment]
It took me some digging to find the fix that was made, so here it is if anyone else also needs to patch their 1.4 typescriptServices.js:  4d14e971cf1d5768f17da9283cdbbc14d26ef976

It's on line 18265.

**Comment by craigktreasure** [comment]
@mhegazy I am hitting this again with the VS 2015 RTM and TS 1.5 with my project targeting 1.5. Enum definitions are not converted to constants. Any thoughts?

**Comment by mhegazy** [comment]
are they regular enums or const enums? can you share a repro?

**Comment by craigktreasure** [comment]
They are regular enums. Same repro as the first post when i opened this issue. Workaround is to mark the enum as a const enum in the definition, but that shouldn't be necessary.

**Comment by vladima** [comment]
this is [breaking change in TypeScript 1.5](https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#enum-reference-in-lining-changes):

>For regular enums, pre 1.5, the compiler only inline constant members, and a member was only constant if its initializer was a literal. That resulted in inconsistent behavior depending on whether the enum value is initalized with a literal or an expression. Starting with Typescript 1.5 all non-const enum members are not inlined.

**Comment by craigktreasure** [comment]
Ouch. Good to know. I wish there had been a link to those in the 1.5 announcement post. If it was, i missed it.

**Comment by mhegazy** [comment]
Good point. Will do that next release. we usually put it in the release notes: https://github.com/Microsoft/TypeScript/releases/tag/v1.5.3
