### ISSUE TITLE
Bug: Various return types in NamedNodeMap in lib.dom.d.ts are slightly inaccurate

### ISSUE THREAD

**Issue by dsifford** [Microsoft/TypeScript#18129]
It's my understanding that `getNamedItem`, `getNamedItemNS`, and `item` should return `null` if the Attr node is undefined or out of range.

Additionally, it's my understanding that the return value of the indexed properties should be `undefined` if out of range.

**Sources:**

> "The NamedNodeMap.getNamedItem() method returns the Attr corresponding to the given name, or null if there is no corresponding attribute." [[Via MDN](https://developer.mozilla.org/en-US/docs/Web/API/NamedNodeMap/getNamedItem)]

> "NamedNodeMap.item() returns the Attr at the given index, or null if the index is higher or equal to the number of nodes." [[Via MDN](https://developer.mozilla.org/en-US/docs/Web/API/NamedNodeMap)]

https://github.com/Microsoft/TypeScript/blob/d7b3b6c77d45adc4542c882a3f19d2f0fdb3e76c/lib/lib.dom.d.ts#L8187-L8197

Let me know if I'm mistaken. I'm always up to learn! 😄 

Thanks in advance team for all your hard work!

**Comment by dsifford** [comment]
Whoops.. Dupe of #17695!

Happy to send in a PR if needed.

**Comment by mhegazy** [comment]
PRs welcomed.

**Comment by dsifford** [comment]
@mhegazy Great! I'll keep an eye on this and get to it in the next couple of days if it hasn't been taken care of yet. Thanks!

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
