### ISSUE TITLE
Better type inference of tagged union predicate functions

### ISSUE THREAD

**Issue by ccorcos** [Microsoft/TypeScript#18122]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

**Code**

```ts
type X = {t: "x"}
type Y = {t: "y"}
type Z = X | Y

let a: Array<Z>

function predicate(x: Z) {
  return x.t === "x"
}

const result =  a.find(predicate)
```

**Expected behavior:**
I want result to have a type of `X`. Which means I want the predicate function to have a return type of `x is X`.

**Actual behavior:**
The result of the predicate is of type `Z` and result is of type `Z`

**Comment by mhegazy** [comment]
Please see https://github.com/Microsoft/TypeScript/issues/5101#issuecomment-145693151

**Comment by ccorcos** [comment]
Hmm. so I need to overload the `.find` function? Or should I be doing something like this?

```
function predicate<T extends Z>(x: Z): x is T {
  return x.t === "x"
}
```

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
