### ISSUE TITLE
Unable to make class generic with JSDoc

### ISSUE THREAD

**Issue by JoelEinbinder** [Microsoft/TypeScript#18135]
**TypeScript Version:**  2.6.0-dev.20170829

```js
/**
 * @template T
 */
class MyArray {
  constructor() {
    /** @type {Array<T>} */
    this.array = [];
  }
}
/** @type {MyArray<string>} */
let x = new MyArray();
```

**Expected behavior:**
`x` should contain an array of strings.

**Actual behavior:**
`[js] Cannot find name 'T'.`
`[js] Type 'MyArray' is not generic.`

**Comment by kitsonk** [comment]
Could this be a duplicate of #17140?

**Comment by sandersn** [comment]
Just to make sure, this is in a .js file, right?

**Comment by JoelEinbinder** [comment]
Yes, this is in a .js file.

My `compilerOptions`:
```json
{
    "noEmit": true,
    "allowJs": true,
    "checkJs": true,
    "target": "es2017"
}
```
