### ISSUE TITLE
window.open should return `Window | null`

### ISSUE THREAD

**Issue by mikecheb** [Microsoft/TypeScript#18132]
**TypeScript Version:**  2.4.2

**Code**
(Run with `--strictNullChecks`.)
```ts
function closeWindow(window: Window) {
  window.close();
}

const newWindow = window.open('https://twitch.tv', '_blank', 'noopener');
closeWindow(newWindow);
```

**Expected behavior:**
TypeScript reports an error: `Argument of type 'Window | null' is not assignable to parameter of type 'Window'.`

This alerts the developer to the fact that `window.open` may return `null`—and is in  fact guaranteed to in this code, due to the presence of the `'noopener'` feature string. See the [spec](https://html.spec.whatwg.org/multipage/window-object.html#apis-for-creating-and-navigating-browsing-contexts-by-name). Thus, the developer knows to expect null as a possible argument of `closeWindow`.

**Actual behavior:**
TypeScript sees nothing wrong with this code, and it causes a TypeError when run (`Cannot read property 'close' of null`).

This is because `Window`'s `open` method is typed as `Window`, rather than `Window | null`: https://github.com/Microsoft/TypeScript/blob/master/lib/lib.dom.d.ts#L13296

**Comment by mikecheb** [comment]
(Should be labeled `Bug` and `Domain: lib.d.ts`.)

**Comment by mhegazy** [comment]
thanks for the triage help :)

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by heejongahn** [comment]
Hello @mhegazy . Trying to participate in TS dev community, I found this could be a good starting point. After reading the contribution guides, I tried something like [this commit](https://github.com/heejongahn/TSJS-lib-generator/commit/30d7a069b9aa5c7031ea6b43b11109139c2682c0), but running `./build.sh` locally fails with message below. (OS: macOS 10.12.6)

```
No version specified. Downloading latest stable.
Paket.exe 5.91.0 is up to date.
Paket version 5.91.0
Performance:
 - Disk IO: 97 milliseconds
 - Runtime: 1 second
Building project with version: LocalBuild
Shortened DependencyGraph for Target Test:
<== Test
   <== Run

The running order is:
  - Run
  - Test
Running build with 1 worker
Starting Target: Run
Finished Target: Run
Starting Target: Test (==> Run)
Running build failed.
Error:
System.Exception:
Test failed: dom.generated.d.ts is different from baseline file.
  at FSI_0005.Build+clo@22-1.Invoke (Microsoft.FSharp.Core.Unit _arg1) [0x000d9] in <9234261478bc4c9abc908b21861fa7c1>:0
  at Fake.TargetHelper+targetFromTemplate@209-1[a].Invoke (Microsoft.FSharp.Core.Unit unitVar0) [0x00001] in <59083baaccf1c534a7450383aa3b0859>:0
  at Fake.TargetHelper.runSingleTarget (Fake.TargetHelper+TargetTemplate`1[a] target) [0x0004b] in <59083baaccf1c534a7450383aa3b0859>:0

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target     Duration
------     --------
Run        00:00:02.4554486
Test       Failure
Total:     00:00:02.5246669
---------------------------------------------------------------------
Status:    Failure
---------------------------------------------------------------------
---------------------------------------------------------------------
  1) System.Exception:
Test failed: dom.generated.d.ts is different from baseline file.
  at FSI_0005.Build+clo@22-1.Invoke (Microsoft.FSharp.Core.Unit _arg1) [0x000d9] in <9234261478bc4c9abc908b21861fa7c1>:0
  at Fake.TargetHelper+targetFromTemplate@209-1[a].Invoke (Microsoft.FSharp.Core.Unit unitVar0) [0x00001] in <59083baaccf1c534a7450383aa3b0859>:0
  at Fake.TargetHelper.runSingleTarget (Fake.TargetHelper+TargetTemplate`1[a] target) [0x0004b] in <59083baaccf1c534a7450383aa3b0859>:0
---------------------------------------------------------------------
```

I think I probablly messed up the 

> Run the script locally to obtain new `dom.generated.d.ts` and `webworker.generated.d.ts.`

part, as in fact, I couldn't figure out what `script` it meant and just modified `dom.generated.d.ts` by myself...

I guess maybe it's too much of a rookie question, but if you could point where I went wrong (and how I can fix it), I'll really appreciate. I love this product and would be very happy to contribute :)

**Comment by mhegazy** [comment]
after making the change, you need to update the baselines with the output of the build. so first build fails, `copy ./generated/* ./baseline/` then run it again.
