### ISSUE TITLE
WebKitEntriesCallback interface should return WebKitEntry

### ISSUE THREAD

**Issue by AAudusseau** [Microsoft/TypeScript#18139]
**TypeScript Version:**  2.3.4

Why the `WebKitEntriesCallback` use in the `readEntries` method of a `WebKitDirectoryReader` has an `Event` object for parameter ? I think it should return an array of `WebKitEntry`.

**Expected behavior:**
```ts
interface WebKitEntriesCallback {
    (entries: WebKitEntry[]): void;
}
```

**Actual behavior:**
```ts
interface WebKitEntriesCallback {
    (evt: Event): void;
}
```

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by mhegazy** [comment]
We are moving the .d.ts generation to be derived from the WebIdl file from the spec. this results in many of the vendor specific declarations being removed, e.g. `WebKit*`/`MS*`/`mox*`.

See https://github.com/Microsoft/TypeScript/issues/25515#issuecomment-403897228
