### ISSUE TITLE
Extract function unecessarily returns values

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#18137]
Tested in VS Code:

```ts
function call(...args: any[]) {
}


function foo() {
	let x = 'Hello World';
	let y = 'Hello World';
	call(x = 'Bye Bye', y = ' Bye Bye');
}
```
- select `call(x = 'Bye Bye', y = ' Bye Bye');`
- extract into global scope
- you get
```ts
function foo() {
	let x = 'Hello World';
	let y = 'Hello World';
    ({ x, y } = newFunction(x, y));
}
function newFunction(x: string, y: string) {
    call(x = 'Bye Bye', y = ' Bye Bye');
    return { x, y };
}
```

- There is not need to return {x, y} from newFunction since they variable aren't used inside foo() afterwards. Extracting the rest of a function into a new function is quite common and a minimal signature should be computed.

**Comment by mhegazy** [comment]
should be covered by https://github.com/Microsoft/TypeScript/issues/18138

**Comment by RyanCavanaugh** [comment]
> There is not need to return {x, y} from newFunction since they variable aren't used inside foo() afterwards.

This seems speculative at best... if the user wanted those to be captured in the extracted function, they could have selected them. Now if I did want to use `x` and `y` later I have to undo and insert dummy references to them later in the function?

This is to say nothing of having to reason about earlier captures, e.g.
```ts
function foo() {
	let x = 'Hello World';
	let y = 'Hello World';
	window.setTimeout(() => console.log(x + y));
	call(x = 'Bye Bye', y = ' Bye Bye');
}
```

**Comment by dbaeumer** [comment]
Agree on the dup :-)

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
