### ISSUE TITLE
Keyof includes class methods

### ISSUE THREAD

**Issue by kidcosmic** [Microsoft/TypeScript#18133]
**TypeScript Version:**  2.4.2

**Code**

```ts
class Model {
    public id: string
    public createdAt: Date
    public lastModified: Date
    version: number
    private transient: Object

   save(): Promise<this> {

   }
}
enum Type {
    string,
    number,
    date
    // ...
}

type Schema<T extends Model> = { [P in keyof T]: Type }

let schema: Schema<Model> = {
   id: Type.string,
   createdAt: Type.date,
   lastModified: Type.date,
   version: Type.number
}
```

**Expected behavior:**
Expected behavior here is that keyof follows own enumerable types of class, and thus, schema is validly typed. Note, that a Partial<Model> is not an option since this example needs all properties to be defined in schema.

**Actual behavior:**
```
TypeTest.ts(20,5): error TS2322: Type '{ id: Type.string; createdAt: Type.date; lastModified: Type.date; version: Type.number; }' is not assignable to type 'Schema<Model>'.
  Property 'save' is missing in type '{ id: Type.string; createdAt: Type.date; lastModified: Type.date; version: Type.number; }'.
```

**Comment by RyanCavanaugh** [comment]
`keyof` doesn't distinguish methods vs properties

**Comment by gcnew** [comment]
There is a workaround/hacky way to filter out methods. The following works with the latest nightly build of the compiler.

```ts
type Bool = 'true' | 'false'

type Not<X extends Bool> = {
    true: 'false',
    false: 'true'
}[X]

type Intersect<T extends string, Key extends string> = (
  { [K in T]: 'true' } &
  { [key: string]: 'false' }
)[Key]

type IsNeverWorker<S extends string> = (
    { [K in S]: 'false' } &
    { [key: string]: 'true' }
)[S]

type IsNever<T extends string> = Not<Intersect<IsNeverWorker<T>, 'false'>>

class Model {
    public id: string
    public createdAt: Date
    public lastModified: Date
    version: number
    private transient: Object

    save(): Promise<this> {
       return null!;
    }
}
enum Type {
    string,
    number,
    date
    // ...
}

type Schema<
    T extends Model,

    Keys extends keyof T = {
        [K in keyof T]: {
            'false': K,
            'true': never
        }[IsNever<keyof T[K]>]
    }[keyof T]
> = { [P in Keys]: Type }

let schema: Schema<Model> = {
   id: Type.string,         // <-- try commenting me out for a type error
   createdAt: Type.date,
   lastModified: Type.date,
   version: Type.number
}
```

**Comment by olegdunkan** [comment]
@gcnew it is interesting why 
```ts
var x: NonFunctionProps<Model>;
```
produces `x` of `never` but inside mapped type it works?

**Comment by gcnew** [comment]
Which compiler version are you using? On my machine it works as expected. I've built from `master`, but `2.6.0-dev.20170829` should do as well.

```ts
type X = NonFunctionProps<Model>;   // 'id' | 'createdAt' | 'lastModified' | 'version'
```

**Comment by olegdunkan** [comment]
@gcnew yes, you are right, I have tried it at 2.5.1 version, now I've updated master branch and it works, thanks!

**Comment by kidcosmic** [comment]
@RyanCavanaugh why is that? considering that `save()` is not actually a property or owned by any instance of Model, and that Javascript respects that, why would it be typed that way?

Example:

```
class Test {
	hello() {
		console.log('hello')
	}
}
let it = new Test()
it.hello() // hello
console.log(Object.keys(t)) // []
```
hello is not a member of `it`
```
t.hello = function() { 
   console.log('world')
}
t.hello() // world
console.log(Object.keys(t)) // ['hello']
```
after assigning hello to it, hello is an actual member of it, and javascript reflects that

**Comment by DanielRosenwasser** [comment]
`"hello"` is not returned from `Object.keys`, but

1. That's fine because returning fewer keys than there are elements in a union type is permissible (i.e. returning `"foo"` if you promise `"foo" | "bar"` is just fine).
1. `Object.keys` can return keys that are not in `keyof Foo` in the first place, so trying to make the  parallel is tempting but overall misleading.

**Comment by kitsonk** [comment]
```js
class Test {
	hello() {
		console.log('hello')
	}
}
let it = new Test()
it.hello() // hello
console.log(Object.keys(it)) // []
console.log('hello' in it); // true
console.log(typeof it.hello); // function
```

Who ever said that JavaScript was rational?  This is one of the reasons why TypeScript is a structurally typed language.  In most ways `it` would be used, `hello()` is part of its structure.

**Comment by kidcosmic** [comment]
True, but in the case of keyof, or keys in general, own enumerable properties is the general consensus. Ie, `Object.assign`, `Object.keys`

Keyof's usefulness diminishes with the inclusion of the prototype chain.
For example, suppose I wanted to make a strict constructor for a class, where all properties are included:
```
class Test {
    id: string
    constructor(data: {[P in keyof Test]: Test[P]}) {
        super()
    }
    hello() {
        console.log('hello')
    }
}
let test = new Test({id:'hello'})
```
You get:
```
severity: 'Error'
message: 'Argument of type '{ id: string; }' is not assignable to parameter of type '{ id: string; hello: () => void;'.
  Property 'hello' is missing in type '{ id: string; }'.'
at: '24,21'
source: 'ts'
```
It doesn't make sense it include any prototype keys.
