### ISSUE TITLE
AddEventListenerOptions not available in Document, HTMLDivElement and others

### ISSUE THREAD

**Issue by HolgerJeromin** [Microsoft/TypeScript#18136]
**TypeScript Version:**  2.4.1

addEventListener has now an object third param type. Some were included in #15183 (closing #14188 )

But this is not fixed for Document and others in TS 2.4.1 (and ts playground)

````
document.addEventListener('readystatechange', function () { }, { once: true });
document.createElement('div').addEventListener('click', function () { }, { once: true });
````

Update:
`HTMLDivElement extends HTMLElement` (with own `addEventListener` for special `this`)
`HTMLElement extends Element` (with own `addEventListener` for special `this`)
`Element extends Node` (with own `addEventListener` for special `this`)
`Node extends EventTarget`
`EventTarget ` (with `addEventListener` with unspecific `this`)

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by HolgerJeromin** [comment]
@mhegazy @thebanjomatic
The current state now in master is a breaking change in TS2.6

https://github.com/Microsoft/TSJS-lib-generator/pull/312 (ported in #19426) added an own removeListener to document which overwrites the working signature from EventTarget with the "buggy" one without the options.

`document.removeEventListener('keydown', this.__updateLastUserinteraction, options);`
compiles in TS2.5 but not in TS2.6
