### ISSUE TITLE
Extract method breaks code with generic

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#18143]
```ts
class A<T> {
	public bar(i: number) {
		let t: T;
	}
}
```
- select `let t: T;`
- extract into global scope
- you get
```ts
function newFunction() {
    let t: A.T;
}
```
which is incorrect.

**Comment by amcasey** [comment]
Should be fixed by https://github.com/Microsoft/TypeScript/commit/ea4fdc5a9920aa1834cb1ce1bd719ad7894bc139.
