### ISSUE TITLE
Extract function breaks code with switch statement

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#18144]
```ts
function foo() {
	let x = 10;
	switch (x) {
		case 1:
			break;
	}
}
```
- select `break;`
- extract
- you get
```ts
function foo() {
	let x = 10;
	switch (x) {
		case 1:
            newFunction();
	}
}
function newFunction() {
    break;
}
```

**Comment by amcasey** [comment]
I'm guessing the bug is that we allow the extraction.  It doesn't appear to work with `break` in a loop.

**Comment by amcasey** [comment]
It looks like the loop case only works by accident - we check if the parent of the statement is a loop and it's not - it's a block.  As far as I can tell, there's no code for handling unlabeled `break` and `continue` statements with targets outside the extracted range.
