### ISSUE TITLE
Extract funtion doesn't extract single variable

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/TypeScript#18141]
```ts
	let x = 10, y = x;
```
- select x in y = x;
- try to extract

Observe: nothing happens.

**Comment by amcasey** [comment]
Comments @RyanCavanaugh ?

**Comment by RyanCavanaugh** [comment]
Maybe I'm the only dev in the world that has never wanted to do this. 🤷‍♂️

**Comment by amcasey** [comment]
FWIW, C# blocks this too.

**Comment by dbaeumer** [comment]
I was more complaining about the inconsistency since you can extract 10 in this example `let z = 10;`. And it does make sense if you want to make the initializer more complicated and you start with extracting the current one into a function.

**Comment by amcasey** [comment]
I've heard some people voice concerns that the refactoring might be offered to often if we allow it on individual identifiers, but I'm game for enabling it and seeing how it feels.

**Comment by amcasey** [comment]
I'm not aware of additional feedback on this issue.
