### ISSUE TITLE
Extract method / function should generate signature with return type

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/TypeScript#18145]
Only exception might be if an artificial return value us used (e.g. {x, y})

**Comment by mhegazy** [comment]
This is rather a style choice on our part. we opt out from explicit type annotations if the compiler can figure it out. i understand that users might have different style expectations here. so waiting to hear more user input on this.

**Comment by dbaeumer** [comment]
If it is a style option then it should be controllable by a setting. We require explicit return types for everything but private stuff (but even there most devs do add return type annotations). So it is simply more work for those devs.

We could also infer this from the function already present in the project. If they mostly carry a  return type we should generate one.

**Comment by mhegazy** [comment]
> If it is a style option then it should be controllable by a setting

I think this is a good idea and  we should do that.

**Comment by DanielRosenwasser** [comment]
Related is #18187.

**Comment by AggressiveSneeze** [comment]
I noticed this in the gif on the `v2.5` release notes and came to open an issue. Glad to see you're all on top of this already! :)

**Comment by azz** [comment]
What about if adding a return type is a separate refactoring? Then you could add the inferred return type to any function, and it wouldn't require additional configuration. You could even bind that to a keyboard shortcut.

**Comment by RyanCavanaugh** [comment]
We ended up implementing @azz's suggestion
