### ISSUE TITLE
Extract function should not extract expression if only parts are selected.

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#18146]
```ts
function foo() {
	let x = 10 * 10 + 10;
}
```
- select `10 + 10` which obviously can't be extracted
- extract
- it generates
```ts
function foo() {
	let x = newFunction();

    function newFunction() {
        return 10 * 10 + 10;
    }
}
```
which is not want the user might wanted to happen.

**Comment by mhegazy** [comment]
This behavior seemed like the best we could do given the shape of the tree. we also opted to follow what Roslyn does in similar circumstances. seems like the worst that could happen here is the user does not like the change and can undo.

**Comment by dbaeumer** [comment]
I think we should interact with the user and tell him: the selection can't be extracted since it would change the sematic. Do you want to expand the selection to '.....' and extract that instead?

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
