### ISSUE TITLE
Maybe grouping repositories

### ISSUE THREAD

**Issue by dbol55** [Microsoft/TypeScript#18157]
It is quite unorganized with all repositories in one row... maybe you can push for a better structure so that github implements grouping.

**Comment by mhegazy** [comment]
not sure i understand the request. if this is a request to a github feature consider emailing support@github.com:

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
