### ISSUE TITLE
JSDoc @enum tag support

### ISSUE THREAD

**Issue by bpaczkowski** [Microsoft/TypeScript#18161]
It'd be nice if [JSDoc's enum tag](http://usejsdoc.org/tags-enum.html) support was added, not much else to say. As it is now, the enum's name is not even recognized as a type.

**Comment by michaeljota** [comment]
This should be with support of the type of the enum, now that strings are allowed as enums values.

**Comment by sandersn** [comment]
`@enum` support is actually quite different from Typescript's enums. It's closer to string/number union support. Basically, `@enum` does two (or perhaps three) things. Here's an example:

```js
@enum {string}
const Target = {
  START: "start",
  MIDDLE: "middle",
  END: "end"
  MISTAKE: 1
  /** @type {number} */
  OK_I_GUESS: 2
}
```

1. Don't add an string index signature, unlike other object literals in JS.
2. Let the type reference `Target` be equivalent to the type reference `keyof typeof Target`
3. [Optional] Require the type of members of `Target` to be assignable to `string` unless explicitly overridden. I haven't looked, but I would be surprised if real `@enum`s use the override feature.

Note that anything with types that can be unioned works, unlike Typescript enums. Here's an enum of classes:

```js
/**
 * @enum {function (new:import("../geom").Geometry, Array, import("../geom/GeometryLayout"))}
 */
const GeometryConstructor = {
  'POINT': Point,
  'LINESTRING': LineString,
  'POLYGON': Polygon,
  'MULTIPOINT': MultiPoint,
  'MULTILINESTRING': MultiLineString,
  'MULTIPOLYGON': MultiPolygon
};
```

**Comment by djmisterjon** [comment]
@enu not work on my side 
I was ask here, if anybody can help me ?
https://stackoverflow.com/questions/59192833/how-jsdoc-classes-with-static-properties

**Comment by AmicoJoules** [comment]
This only works for me inside the file where the enum was defined, once I "require" this file intellisense doesn't suggest any of the enum values
