### ISSUE TITLE
Default exports cannot be used as type names

### ISSUE THREAD

**Issue by esprehn** [Microsoft/TypeScript#18167]
**TypeScript Version:** Version 2.4.1

**Code**

Example.tsx

```ts
import * as React from 'react';
import * as Redux from 'redux';

import { connect } from 'react-redux';

class Example extends React.Component<{}, {}> { }

export default connect()(Example)
```

Main.tsx
```ts
import * as React from 'react';
import Example from './Example';

class Main extends React.Component<{}, {}> {
  exampleRef: Example;
  render() {
    return <Example ref={ref => this.exampleRef  = ref} />;
  }
}
```

**Expected behavior:**

Compiles fine, the type of the Example component is known by looking at the return type of `connect()`, and indeed if I put the wrong props inside the render() function it fails, so it does know what type Example is, it just won't let me declare any variables with that type.

**Actual behavior:**

Main.tsx(..., ..): error TS2304: Cannot find name 'Example'.

**Comment by ikatyang** [comment]
```diff
-export connect()(Example)
+export default connect()(Example)
```

**Comment by Kovensky** [comment]
Why is `export connect()(Example)` not a syntax error? Or did it get missed in the error message log?

**Comment by mhegazy** [comment]
The function call returns a value not a type. I think what you want is `typeof ` the instance of the class constructor instead.. this is tracked by https://github.com/Microsoft/TypeScript/issues/6606


More info about the diffrent declaration spaces can be found at http://www.typescriptlang.org/docs/handbook/declaration-merging.html

**Comment by esprehn** [comment]
Sorry that was just bad copy paste into the bug, it uses "export default". I'm not saying I want typeof, I'm curious why the named import doesn't create a type for me.

I understand how a function does't by default create a type, but the act of doing:

```js
import Foo from './foo';
```

should create a type with the name Foo that matches the type of the value Foo. TypeScript knows the type of Foo here, so it can easily auto alias the type for me.

**Comment by mhegazy** [comment]
the problem is not the import, it is the export. `export default <expr>` exports a value. and expression is not a type. in this case it is a constructor function for a class. what you need is given a constructor function, a way to refer to the type of its instance method.  I would recommend reading more about types vs values in http://www.typescriptlang.org/docs/handbook/declaration-merging.html

**Comment by esprehn** [comment]
Right, I read and understand that (you linked it twice now :).

I'm saying that given that you can export a class and get both a type and a value (the constructor function). I want the import to produce a type alias of the type of the value. The compiler has this knowledge, having `import Foo from './bar';` also produce a type I can name the same as the proposed `type Foo = typeof Foo;` could would be really useful in a huge number of current cases and lets us write natural looking code instead of having to remember if we're required to do `value: Foo` or `value: typeof Foo`. It also means the creator of a class or library can switch from exporting the class directly to exporting an HOC without forcing code changes on all downstream consumers.

Separately, what is your suggestion for how to declare a variable today that is the type of what comes out of `connect()` or other HOC libraries? Using refs with react in typescript today is quite frustrating. We end up exporting both the class as FooComponent as well as the connected value. If the library forgot to export the type we seem to be SOL and have to instead make and maintain a compatible interface ourselves. We'd also really prefer to not have both Foo (the connected  default export) and FooComponent (the exported class type.) and instead be able to always refer to it as Foo the same as if we had exported the class.

**Comment by mhegazy** [comment]
> The compiler has this knowledge, having import Foo from './bar'; also produce a type I can name the same as the proposed type Foo = typeof Foo;

The compiler treats values and types differently. so type `typeof Foo` is not the same as type `Foo` for a class for instance.

A value and a type can have the same name. an export exports **all** meanings of a name. so it is perfectly legal to write:

```ts
export type Foo = number;
export const Foo = 0;
```

this gives you one import `Foo` that is both a type and a value.


> Separately, what is your suggestion for how to declare a variable today that is the type of what comes out of connect() or other HOC libraries?

this is tracked by #6606. The missing part here is having a way to name the instance type given a constructor function. the compiler knows the type, but you have no way to refer to it.
#6606 is the best option we have so far.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
