### ISSUE TITLE
Configure implement interface quick fix quote type

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#18169]
From https://github.com/Microsoft/vscode/issues/33476

**TypeScript Version:**  2.5.1

**Code**

```ts
interface IFoo {
    bar(): number;
}

class Foo implements IFoo {
    
}
```

Trigger the implement interface quick fix on `class Foo`

**Expected behavior:**
Users can configure if single or double quotes are used for the `Method not implemented error`

**Actual behavior:**
Double quotes are always used for the `Method not implemented error`

```ts
interface IFoo {
    bar(): number;
}

class Foo implements IFoo {
    bar(): number {
        throw new Error("Method not implemented.");
    }

}
```

Related to #13270

**Comment by andy-ms** [comment]
@rbuckton did something similar in #17750 -- should we generalize this to looking at all `StringLiteral` nodes in a file to determine what quote style is preferred?

**Comment by mhegazy** [comment]
I would say add a config option for users to choose quote type. in absence of that we can use @rbuckton's inference for imports still.

**Comment by mjbvz** [comment]
Yes I think it makes more sense to have an option in this case. VSCode uses both styles of quotes in its source for example, but only uses double quotes for UI strings
