### ISSUE TITLE
tsserver: @param not included in QuickInfo tags

### ISSUE THREAD

**Issue by boniatillo-com** [Microsoft/TypeScript#18177]
**TypeScript Version:**  2.4.1

The `tsserver` is not including the `@param` tag in the QuickInfo request.

**Code**

```ts
/**
 *  Show message.
 * @author arian
 * @param msg Hello msg
 */
function showMessage(msg : string) {
    console.log(msg);
}
```

**Expected behavior:**

To include the `param` and `author` tag.

**Actual behavior:**

Only include in the `tags` field the `author` info:

```json

{
"seq":0,"type":"response","command":"quickinfo","request_seq":53,"success":true,"body":{"kind":"function","kindModifiers":"","start":{"line":7,"offset":10},"end":{"line":7,"offset":21},"displayString":"function showMessage(msg: string): void","documentation":"Show message.","tags":[{"name":"author","text":"arian"}]}}
```

**Comment by kitsonk** [comment]
I believe that you don't get quick info of parameters at the function level, as that gets merged and associated with the quick info on the actual parameter.  The only things you get in the `tags` are parameters which are not associated with other nodes.  If you got quickInfo for the `msg` position you would get the docs.

**Comment by boniatillo-com** [comment]
I see, I tested and it works:

![image](https://user-images.githubusercontent.com/12187299/29924159-fe518566-8e29-11e7-8ea2-23d4f46465b4.png)

However, the real utility of a parameter info is not in the method declaration context else in the method reference context.

For example, a user who is using a third-party API would like to see the doc of all parameters of a method call, but right now only the method signature is provided, when a `quickinfo` is requested:

![image](https://user-images.githubusercontent.com/12187299/29924262-6f2072ca-8e2a-11e7-9ffb-add040f9b6a2.png)

For example something like what Eclipse shows with Java:

![image](https://user-images.githubusercontent.com/12187299/29924510-2b3093b4-8e2b-11e7-834f-2bad85e71964.png)

**Comment by boniatillo-com** [comment]
Maybe I should open a different issue for this.

**Comment by boniatillo-com** [comment]
Added a new issue for this:

https://github.com/Microsoft/TypeScript/issues/18178
