### ISSUE TITLE
strong interfaces

### ISSUE THREAD

**Issue by cevek** [Microsoft/TypeScript#1817]
```javascript
interface IArticle {
    id?: number;
    title: string;
    anons?: string;
    text?: string;
    images?: string[];
}
class Article {
    constructor(params:IArticle) {
        /// some code
    }
}

new Article({id: 1, title: "Title", text: "Hello"});
```

if I rename property `text?` to `description?` in interface `IArticle` no error occurs
and I dont know what went wrong in my code

How about strong interfaces? 

```javascript
interface strong IArticle {
    id?: number;
    title: string;
    anons?: string;
    text?: string;
    images?: string[];
}
```
And if object with this interface has over properties then compiler will throw an error

**Comment by DanielRosenwasser** [comment]
Can you share the error you're getting? I'm not able to reproduce the issue.

**Comment by AbubakerB** [comment]
I think what he means is that if he changes `text?` in `IArticle` to `description?`, then an error should be thrown at:

```javascript
new Article({id: 1, title: "Title", text: "Hello" /* this doesn't thrown an error - could a strong interface solve this? */ });
```

Also, applying a comment to this object does something weird .... [PLAYGROUND](http://www.typescriptlang.org/Playground#src=interface%20IArticle%20%7B%0A%20%20%20%20id%3F%3A%20number%3B%0A%20%20%20%20title%3A%20string%3B%0A%20%20%20%20anons%3F%3A%20string%3B%0A%20%20%20%20description%3F%3A%20string%3B%0A%20%20%20%20images%3F%3A%20string%5B%5D%3B%0A%7D%0Aclass%20Article%20%7B%0A%20%20%20%20constructor(params%3AIArticle)%20%7B%0A%20%20%20%20%20%20%20%20%2F%2F%2F%20some%20code%0A%20%20%20%20%7D%0A%7D%0A%0Anew%20Article(%7Bid%3A%201%2C%20title%3A%20%22Title%22%2C%20text%3A%20%22Hello%22%20%2F*%20text%20is%20not%20of%20IArticle%20*%2F%7D)%3B)

**Comment by cevek** [comment]
Problem is no error occurs if i rename the member `text?` to `description?`  but i need to know that is may broke my application. Or other frequent example i make typo `new Article({tite:123}) `

**Comment by NN---** [comment]
@cevek Will this code be correct in your case ?

```typescript
strong interface A {
 name?: string;
}

class B implements A {
 name: string;
 other: number;
}
```

**Comment by RyanCavanaugh** [comment]
See #391
