### ISSUE TITLE
'Promise.all()' with different behavior when changing the target from 'es2015' to 'es2016'

### ISSUE THREAD

**Issue by noobiept** [Microsoft/TypeScript#18170]
Hello, as described in the title, I noticed there's a difference in the types returned from 'Promise.all()', depending on the current target of typescript.
I'm not sure if this is due to a change on the standard, but couldn't find anything mentioning that.

Here's a simplified code of the issue I stumbled upon.

    async function getNumber(): Promise <number> {
        return 0;
    }
    
    async function getString(): Promise <string> {
        return 'a';
    }
    
    async function test() {
        let [ a, b ] = await Promise.all([
            await getNumber(),
            await getString()
        ]);
    
        a;  // 'string | number' with es2016, but a 'number' with es2015
        b;  // 'string | number' with es2016, but a 'string' with es2015
        a.toFixed( 2 );     // error with es2016, but not with 2015
        b.indexOf( 'a' );   // error with es2016, but not with 2015
    }

**Typescript version:** 2.4.2

**Expected behavior:** The compiler should continue to infer the correct type.

**Actual behavior:** The compiler infers an OR of both types.

**Comment by mhegazy** [comment]
what am i missing?

```sh
c:\test\18170>type a.ts
async function getNumber(): Promise <number> {
    return 0;
}

async function getString(): Promise <string> {
    return 'a';
}

async function test() {
    let [ a, b ] = await Promise.all([
        await getNumber(),
        await getString()
    ]);

    a;  // 'string | number' with es2016, but a 'number' with es2015
    b;  // 'string | number' with es2016, but a 'string' with es2015
    a.toFixed( 2 );     // error with es2016, but not with 2015
    b.indexOf( 'a' );   // error with es2016, but not with 2015
}

c:\test\18170>tsc --v
Version 2.5.2

c:\test\18170>tsc a.ts --t es2015

c:\test\18170>echo %errorlevel%
0

c:\test\18170>tsc a.ts --t es2016

c:\test\18170>echo %errorlevel%
0

c:\test\18170>tsc a.ts --t es2017

c:\test\18170>echo %errorlevel%
0

c:\test\18170>tsc a.ts --t es5 --lib es2016

c:\test\18170>echo %errorlevel%
0

```

**Comment by noobiept** [comment]
I tested with the version 2.5.2 of typescript that was released today, and I don't get an error anymore. Seems like it was fixed in this version, but I was definitely getting an error on version 2.4.2.
Thanks regardless, I'll just use the latest version!
