### ISSUE TITLE
tsserver: batch of commands

### ISSUE THREAD

**Issue by boniatillo-com** [Microsoft/TypeScript#18179]
**TypeScript Version:**  2.4.1

**Expected behavior:**

Allow to send multiples commands (a batch) in a single request, and receive a map of the command responses. 

**Actual behavior:**

To send multiples commands, multiples requests are needed.

----

This could be useful to get richer info, for example like parameters info, with a batch of `completionEntryDetails`:

https://github.com/angelozerr/typescript.java/issues/204

**Comment by mhegazy** [comment]
and why is that not possible with multiple calls?

**Comment by boniatillo-com** [comment]
Does it has the same performance multiple calls vs a single call? Does not involve a call I/O resources? For example if a request of `quickinfo` command in a `obj.` position returns 50 completion entries and we want to show all the details of all the entries then we have to do 50 calls of the `completionEntryDetails` command, one for each entry.

**Comment by mhegazy** [comment]
> Does it has the same performance multiple calls vs a single call?

the difference should be negligible compared to the cost of doing the operation itself, e.g. getting a semantic meaning of a name.

> position returns 50 completion entries and we want to show all the details of all the entries then we have to do 50 calls of the completionEntryDetails command, one for each entry.

that is gonna be sloooooooooooow. we deliberately split the API into completion list and entry details to avoid paying the cost of getting all info for all items. consider a project with a few libraries, and then asking for declarations in the global scope, you can easily have 30K-50K symbols.
The current design operates on the observation that most of the time users will ask for details on few entries, and most of the time they just need to text to complete the name they are editing. so additional work is usually not useful

**Comment by boniatillo-com** [comment]
Is just that I am used to Eclipse/Java, and I believe that in the way you show info to the user the user will adopt the API more easy and will code faster, no need to move to a completion to know the context of it, I think it can be shown in the completion list. 

![image](https://user-images.githubusercontent.com/12187299/29938567-3017e8a6-8e57-11e7-8161-78a57f245a9b.png)

However I understand that TypeScript is a different language and in a global context could be a lot of methods. Maybe the completion list could include more info for the first 50/100 completions, it is a practical solution.

But it is ok, it is something that can be implemented in the client side so the server side keeps simple.

Thanks!
