### ISSUE TITLE
Phrasing change for extract method? 

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#18176]
From https://github.com/Microsoft/vscode/issues/33511#event-1227495530

**TypeScript Version:**  2.5.1

**Problem**
The wording on the extract method code action currently is:

<img width="393" alt="screen shot 2017-08-30 at 10 58 11 pm" src="https://user-images.githubusercontent.com/12821956/29908551-c498d61a-8dd6-11e7-94f1-ead7bb5b779f.png">

The phrasing here is a little odd since it is not a function that is being extracted here, code is being extracted *to* a function

Perhaps wording such as `Extract to function in global scope` / `Extract to function in class Z`  would be more clear?

Thoughts?

**Comment by mhegazy** [comment]
i think it should be `extract to method` i would say in the case of the class.

**Comment by amcasey** [comment]
@andy-ms has been tweaking the phrasing.
