### ISSUE TITLE
Contextual return type is lost in extract function

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#18187]
```ts
interface UnaryExpression {
    kind: "Unary";
    operator: string;
    operand: any;
}

function parseUnaryExpression(operator: string): UnaryExpression {
    /*[|*/
     return {
        kind: "Unary",
        operator,
        operand: parsePrimaryExpression(),
    };
    /*|]*/
}

function parsePrimaryExpression(): any {
    throw "Not implemented";
}
```

Extract a function to the `parseUnaryExpression`

**Expected:**

```ts
function newFunction(): UnaryExpression {
    return {
        kind: "Unary",
        operator,
        operand: parsePrimaryExpression(),
    };
}
```

**Actual:**

```ts
function newFunction() {
    return {
        kind: "Unary",
        operator,
        operand: parsePrimaryExpression(),
    };
}
```

Notice that `newFunction` loses the return type which means that `kind` gets widened to `string`. This causes an error in the code.

**Comment by amcasey** [comment]
I know we sometimes retain the contextual type, but I'm not sure how we make the decision.  I would have guessed we only dropped it when it matched the inferred type, but that may not be the case.

**Comment by RyanCavanaugh** [comment]
We add a return type annotation when the extracted node itself is contextually typed. It's going to be tricky to figure this out for statements. We would also have to sometimes synthesize a totally new type if the return of the new function includes writes (i.e. produces a destructuring assignment).

Perhaps extracting a single return statement should just *un*-expand the extraction region to just be the return expression itself?

**Comment by amcasey** [comment]
This no longer repros, possibly as a result of https://github.com/Microsoft/TypeScript/pull/20729.
