### ISSUE TITLE
Language Service type semantics are not always accounting for logical AND operator.

### ISSUE THREAD

**Issue by IEvangelist** [Microsoft/TypeScript#18182]
**TypeScript Version:**  2.2.2.0

**Code**

```ts
const dateStr: string = "";
const date = dateStr && new Date(dateStr);
```
I recreated this issue in the [<kbd>playground</kbd>](http://www.typescriptlang.org/play/#src=const%20dateStr%3A%20string%20%3D%20%22%22%3B%20%0D%0Aconst%20date%20%3D%20this.dateStr%20%26%26%20new%20Date(dateStr)%3B%0D%0A%0D%0Aalert(typeof%20date)%3B%20%2F%2F%20string%2C%20not%20actually%20a%20Date) too.

**Expected behavior:**

I'd expect that the language service powering the IDE would be able to determine that the variable namely `date` is actually a union type of `string | Date`.

**Actual behavior:**

The IDE claims that `date` variable is actually a type of `Date`, ignoring the possibility that the left operand of the logical AND might evaluate as `false`. In the above snippet the type of `date` is actually a `string` as the short-circuit occurs, returning the value of the left operand (according to the 

I'm using version **2.2.2.0**, but the [playground exhibits this same behavior](http://www.typescriptlang.org/play/#src=const%20dateStr%3A%20string%20%3D%20%22%22%3B%20%0D%0Aconst%20date%20%3D%20this.dateStr%20%26%26%20new%20Date(dateStr)%3B%0D%0A%0D%0Aalert(typeof%20date)%3B%20%2F%2F%20string%2C%20not%20actually%20a%20Date) (although, I'm not certain what version it uses).

**Comment by mhegazy** [comment]
Under `--strictNullChecks` logical operators should have the expected type, see https://github.com/Microsoft/TypeScript/pull/8949 for more details.

**Comment by IEvangelist** [comment]
The playground still thinks it is a `Date` even after toggling `strictNullChecks` on.
![image](https://user-images.githubusercontent.com/7679720/29936833-342c184e-8e49-11e7-8870-4108df8b4353.png)
After toggle and tooltip hover of `date`.
![image](https://user-images.githubusercontent.com/7679720/29936905-66021a76-8e49-11e7-8dc3-2967fee3e82c.png)

**Comment by mhegazy** [comment]
`this` type is `any` in the global scope. so `this.dateStr` is `any` as well. remove `this` or select `noImplictThis` to see the error.

**Comment by IEvangelist** [comment]
Thank you, @mhegazy!

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
