### ISSUE TITLE
please make package.json version on github more useful

### ISSUE THREAD

**Issue by clausreinke** [Microsoft/TypeScript#1818]
What is the suggested path for taking the github version of typescript as npm package dependency?

For instance, there are some small issues with the latest npm package 1.4.1, which are fixed in master, but master package.json still has version 1.4.0. So even if I npm install from the git repo, the version for the dependency can't be specified correctly.

My (naive?) suggestion would be:
1. master version should always be at least as high as latest npm version
2. add a build number to the version in master, and bump it every time the LKG is updated, 

Btw, does anyone know how to specify a github dependency in package.json, without npm install being wasteful? Using 
```
  "dependencies": "git+ssh://git@github.com:Microsoft/TypeScript.git"
```
npm (1.4.3) seems to clone the whole repo, when a shallow clone would be sufficient, and I don't want to think whether it is going to be more clever on updates. And while npm accepts tarballs, github offers zipfiles.

My best guess would be to specify the dependency with name and version only, then manually do something like
```
(cd ..;git clone --depth 1 git@github.com:Microsoft/TypeScript.git)
npm install ../TypeScript
```
If anyone has a good solution, that should perhaps go into the docs/readme somewhere?

**Comment by RyanCavanaugh** [comment]
Welcome back claus :smile: 

We've been talking about doing a rolling-build style thing on NPM and should roll the above recommendations into that.

**Comment by Arnavion** [comment]
@clausreinke Meanwhile, you can use https://github.com/Arnavion/typescript-github

```javascript
"dependencies": {
    "typescript-github": "https://github.com/Arnavion/typescript-github/tarball/2015-01-28-67023a83d520fe72cf723359198a931e36def0de"
}
```

**Comment by mhegazy** [comment]
@DanielRosenwasser just pump up the version to 1.5 everywhere.

**Comment by clausreinke** [comment]
@mhegazy  @DanielRosenwasser as long as version bump + fresh LKG always go together, that should help. If you don't like to spend a "real" version number for every build, add a build number.

(Since I raised concerns about npm github dependencies above: after the initial (too deep) clone, subsequent installs have been fast.)

**Comment by clausreinke** [comment]
grmpf. Now that you've been so helpful, npm is driving me crazy: even though I've got typescript 1.5.0 installed globally, it refuses to accept that as a dependency, no matter what I try to convince it to ignore the registry. But that seems to be an npm bug: npm/npm#5509 (and no, the workaround doesn't for me).

**Comment by DanielRosenwasser** [comment]
> Labels:
> * `bug`
> * `i-wanna-be-the-very-best`

We should definitely adopt that label for some issues.

**Comment by DanielRosenwasser** [comment]
Should we consider this `Fixed` now?

**Comment by clausreinke** [comment]
submitter here: sure.

Is there a tracking issue for the npm build automation?

@DanielRosenwasser I wondered about the purpose of that label: since it isn't self-descriptive, it has the feeling of an inside joke.

**Comment by DanielRosenwasser** [comment]
> Is there a tracking issue for the npm build automation?

Not currently, I'll set one up.

> Since it isn't self-descriptive, it has the feeling of an inside joke.

It's a Pokémon reference. The intro song starts off with the lyrics "I wanna be the very best". The tag is basically as if to say "this is a very hard task, you must be very determined to figure out a solution".
