### ISSUE TITLE
get inputElement selectionStart(cursor postion) is error

### ISSUE THREAD

**Issue by pumpkinp** [Microsoft/TypeScript#18197]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**Expected behavior:**

**Actual behavior:**

I get inputElement selectionStart in javascript is sucess,but in typescript ,I get selectionStart,result is inputElement  value's length
odd.

**Comment by pumpkinp** [comment]
i find click a button ,in js ,inputElement foucs ,in ts,inputElement onblur

**Comment by pumpkinp** [comment]
function focus():in js ,cursor postion is nochange,but in ts,cursor position is in end...

**Comment by kitsonk** [comment]
This is not a support forum.

Questions should be asked at [StackOverflow](http://stackoverflow.com/questions/ask?tags=typescript) or on [Gitter.im](https://gitter.im/Microsoft/TypeScript).

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
