### ISSUE TITLE
Cannot iterate over union of types (used to be possible in Ts-2.3)

### ISSUE THREAD

**Issue by apr-xaml** [microsoft/TypeScript#18203]
**TypeScript Version:**  2.5.2

**Code**

```
type TypeDescription<T> = {[prop in keyof T]: undefined };

function getAllProperties<T>(typeDesc: (T|TypeDescription<T>)): ReadonlyArray<keyof T>
{
    const props: Array<keyof T> = [];

    for (var iPropName in typeDesc)
    {
        props.push(iPropName);
    }

    return props;
}
```

**Expected behavior:**
Should compile file (used to be in Ts-2.3)

**Actual behavior:**
Compile errors with "The right-hand side of 'for ... in'  ...".

**Comment by mhegazy** [comment]
`T extends object` or `T extends {}` should avoid the error for now.

**Comment by gcnew** [comment]
Please, don't fix the new correct behaviour. It's been a bug in the compiler that has allowed this unsafe iteration.

**Comment by RyanCavanaugh** [comment]
Agreed, this doesn't seem like a bug.
