### ISSUE TITLE
Trailing semicolons in interface definition emitted in generated JS

### ISSUE THREAD

**Issue by Niggler** [Microsoft/TypeScript#1820]
```typescript
interface foo { };
```

currently generates the JS code

```javascript
;
```

Is that by design?  IMHO that semicolon shouldn't be emitted

**Comment by RyanCavanaugh** [comment]
The semicolon is not part of the interface declaration. What you have here is an interface followed by an empty statement, which the compiler preserves (it is not safe to remove all empty statements from code).
