### ISSUE TITLE
Playground: Add toggle to enable downlevelIteration flag

### ISSUE THREAD

**Issue by alexsapps** [microsoft/TypeScript#18209]
When I click "Options" there are a few compiler flags that the user can check to enable. Adding "downlevelIteration" as one of the options would let me try out custom generators when transpiling to ES5.

Currently when trying to run the fibonacci generator code sample from the [for...of docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of#Iterating_over_generators):
```

function* fibonacci() { // a generator function
  let [prev, curr] = [0, 1];
  while (true) {
    [prev, curr] = [curr, prev + curr];
    yield curr;
  }
}

for (let n of fibonacci()) {
  console.log(n);
  // truncate the sequence at 1000
  if (n >= 1000) {
    break;
  }
}
```

the playground shows this error:
`Type 'IterableIterator<number>' is not an array type or a string type.`

**Comment by NN---** [comment]
As a workaround you can use: https://typescript-play.js.org

E.g. [for (const a of [1,2]) {}](https://typescript-play.js.org/?downlevelIteration=true&target=1#code/GYewTgBAFAxiB2BnALhAhhEwIG0CMANAEwC6AlBAN4C+QA)

**Comment by orta** [comment]
This should be working now that we've integrated typescript-play 👍
