### ISSUE TITLE
JSDoc type assertions for expression without parens

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#18212]
From #5158

**TypeScript Version:**  2.5.2

**Code**
For the JavaScript:

```js
//@ts-check

const img = /** @type {HTMLImageElement} */ document.getElementById('#cat')
img.src = 'cat.gif'
```

**Expected behavior:**
The type of `img` is `HTMLImageElement `

**Actual behavior:**
The type of `img` is `any`. You currently need parens around the expression for this to work properly:

```js
//@ts-check

const img = /** @type {HTMLImageElement} */ (document.getElementById('#cat'))
img.src = 'cat.gif'
```

I feel that the parens should not be required. The JSDoc cast should have the lowest precedence and apply to the entire expression on the right hand side

**Comment by mhegazy** [comment]
this is the intended design. looking up these cast expressions in comments is not cheep. moreover, scoping rules are not clear either. 
we made a design choice to only look them up for parenthesized expressions.

**Comment by weswigham** [comment]
The bigger issue, I think, is that we'd need to start parsing and maintaining JSDoc ASTs on all expressions - which we're very cheap about where we do right now. The actual lookup is fairly cheap - no moreso than a normal TS-style cast.

**Comment by mjbvz** [comment]
Ok, if there is a technical reason why the parens necessary, feel free to close this out. I only opened this because when I first tried to write a jsdoc cast I forgot the parens around the expression, and it took me a moment to realize this
