### ISSUE TITLE
Type 'BreadthFirstIterator<T>' is not an array type or a string type.

### ISSUE THREAD

**Issue by aankitkumar31** [Microsoft/TypeScript#18219]
Hello 
am getting this issue **Type 'BreadthFirstIterator<T>' is not an array type or a string type.**
this is graph.util.ts file  let bfRunner = new BreadthFirstIterator().setRootNodes(roots) in 27 th line
`
import { GraphNode, BreadthFirstIterator } from '.';
import { ArrayUtils } from '../../util';

export class GraphUtils {

	/** Tests if an element is somewhere (deep down) a child of a graph. */
	public static  isDescendantOfChilds<T extends GraphNode<T>>(root: T, potentialDescendant: T): boolean {
		if ((root == null) || !root.hasChilds()) {
			return false;
		}
		return GraphUtils.isDescendant(root.getChilds(), potentialDescendant);
	}

	public static isDescendant<T extends GraphNode<T>>(roots: T[], potentialDescendant: T): boolean {
		if (ArrayUtils.isEmpty(roots) || (potentialDescendant == null)) {
			return false;
		}

		// TODO: if we could navigate to the parent this method would be far less costly
		/*let bfRunner = new BreadthFirstIterator<T>().setRootNodes(roots);*/
		let bfRunner = new BreadthFirstIterator().setRootNodes(roots);
		for(let node of bfRunner) {
			if (node == potentialDescendant) {
				return true;
			}
		}
		return false;
	}

	public static hasChild<T extends GraphNode<T>> (node: T, potentialChild: T) {
		return node.hasChilds() ? (node.getChilds().indexOf(potentialChild)>=0) : false;
	}

} // end
`

its breadfirst iterator file

`
import { GraphNode } from './';

export class BreadthFirstIterator<T extends GraphNode<T>> implements IterableIterator<T> {

	protected rootNodes: T[];
	private queue: NodeOnQueue<T>[] = [];
	private visitedNodes: Map<T,number> = new Map<T, number>();
	private currentNode: NodeOnQueue<T>;
	private width: number;
	private maxWidth: number;
	private level: number;
	private maxLevel: number;

	constructor(rootNode?: T) {
		if(rootNode!=null) {
			this.rootNodes = [ rootNode ];
			this.rewind();
		}
	}
	
	/** BEWARE: running inside of ngFor-loops you need to call the levelFor() method. */
	public getLevel(): number {
		return this.level;
	}
	
	/**
	 * ngFor highly optimizes and only holds state for the looping variable. Atm there is no way to create custom local variables.
	 * So we either can return an according data structure in next() or hold the state ourselves. As we already need to hold state
	 * about visited entities, we can directly map the level for each traversed entity.
	 */
	public levelFor(element: T): number {
		return this.visitedNodes.get(element);
	}

	public getMaxWidth() {
		return this.maxWidth;
	}
	
	public getMaxLevel() {
		return this.maxLevel;
	}

	public getRootNodes() {
		return this.rootNodes;
	}

	public setRootNode(rootNode: T) {
		this.rootNodes = [ rootNode ];
		this.rewind();
		return this;
	}
	
	public setRootNodes(rootNodes: T[]) {
		this.rootNodes = rootNodes;
		this.rewind();
		return this;
	}

	public isVisited(element: T):boolean {
		let visitedLevel = this.visitedNodes.get(element);
		return visitedLevel!=null ? (visitedLevel>=0) : false;
	}
	
	protected isPreVisited(node: T) {
		return this.visitedNodes.has(node);	
	}

	public getCurrentNode(): T {
		return (this.currentNode != null) ? this.currentNode.node : null;
	}

	public getTraversalParent(): T {
		return (this.currentNode != null) ? this.currentNode.traversalParent : null;
	}

	public rewind(): BreadthFirstIterator<T> {
		this.queue.length = 0;
		this.visitedNodes.clear();
		this.currentNode = null;
		this.width = 0;
		this.maxWidth = 0;
		this.level = -1;
		this.maxLevel = 0;

		if(this.rootNodes!=null) {
			this.scheduleForVisit(this.rootNodes, null);
		}

		return this;
	}
	
	protected markCurrentNodeAsVisited() {
		if (this.currentNode != null) {
			this.visitedNodes.set(this.currentNode.node, this.level);
			this.currentNode = null;
		}
	}

	public hasNext(): boolean {
		this.markCurrentNodeAsVisited();
		return this.queue.length>0;
	}
	
	public nextNode(): T {
		if (!this.hasNext()) {
			return null; // force clearing visit flag of last node
		}

		if (this.width === 0) {
			this.width = this.queue.length;
			this.level++;
			this.maxWidth = this.width>this.maxWidth ? this.width : this.maxWidth;
			this.maxLevel = this.level;
		}
	
		let nodeOnQueue: NodeOnQueue<T> = this.queue.shift();
		this.currentNode = nodeOnQueue;
		this.width--;

		if (nodeOnQueue.node.hasChilds() && nodeOnQueue.node.diveIntoChilds(nodeOnQueue.traversalParent)) {
			this.scheduleForVisit(nodeOnQueue.node.getChilds(), nodeOnQueue.node);
		}

		return nodeOnQueue.node;
	}

	private scheduleForVisit(nodes: T[], traversalParent: T) {
		for(let node of nodes) {
			if ((node!=null) && !this.isPreVisited(node)) {
				this.visitedNodes.set(node, -1);
				this.queue.push(new NodeOnQueue(node, traversalParent));
			}
		}
	}
	
	public next(): IteratorResult<T> {
		return {
			done: !this.hasNext(),
			value: this.nextNode()
		};
	}
	
	[Symbol.iterator](): IterableIterator<T> {
		return this;
	}

}

class NodeOnQueue<T> {
	
	constructor(
		public node: T,
		public traversalParent: T) {}

}

export class VisitedRememberingBreadthFirstIterator<T extends GraphNode<T>> extends BreadthFirstIterator<T> {
	
	private visitedChilds: T[];
	
	public hasVisitedChilds(): boolean {
		return (this.visitedChilds!=null) && (this.visitedChilds.length>0);
	}
	
	public getVisitedChilds(): T[] {
		return this.visitedChilds;	
	}
	
	protected markCurrentNodeAsVisited() {
		this.visitedChilds = null;
		super.markCurrentNodeAsVisited();
	}
	
	public rewind(): VisitedRememberingBreadthFirstIterator<T> {
		this.visitedChilds = null;
		super.rewind();
		return this;
	}
	
	protected isPreVisited(node: T) {
		if(this.visitedChilds==null) {
			this.visitedChilds = [];
		}
		
		let isVisited = super.isPreVisited(node);
		if(isVisited) {
			this.visitedChilds.push(node);
		}
		return isVisited;
	}

}

`

please help me to get rid from that issue any help will be appreciated
thanks in advance

**Comment by kitsonk** [comment]
This is not a support forum.

Questions should be asked at [StackOverflow](http://stackoverflow.com/questions/ask?tags=typescript) or on [Gitter.im](https://gitter.im/Microsoft/TypeScript).

But, I assume you are targeting ES5.  `for ... of` will only work on Array or String types when targeting ES5.  If you have a global `Symbol` polyfill though, you can use the option [`--downlevelIteraton`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-3.html#new---downleveliteration) which will allow you to use other iterators, but you really need to ensure that the runtime behaviour of your code works as expected.
