### ISSUE TITLE
ts window 方法的调用的问题

### ISSUE THREAD

**Issue by lansefengxinzi** [Microsoft/TypeScript#18221]
我在js 文件中把一个方法绑定在window 对象上，

然后在ts 文件中 window.方法名报错，找不到这个方法

在js 文件中window.方法名没有问题。请问这个问题怎么解

**Comment by kitsonk** [comment]
This is not a support forum.

Questions should be asked at [StackOverflow](http://stackoverflow.com/questions/ask?tags=typescript) or on [Gitter.im](https://gitter.im/Microsoft/TypeScript).

这不是支持论坛。

应该在 [StackOverflow](http://stackoverflow.com/questions/ask?tags=typescript) 或 [Gitter](https://gitter.im/Microsoft/TypeScript) 询问问题。

You need to learn about TypeScript interfaces.

您需要了解TypeScript接口。

**Comment by benjamin21st** [comment]
Use `window[nameOfYourMethod]` as a workaround. 

Besides, your question can be answered through stackoverflow, so please follow the guidelines before you open up a new issue, link here : https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md .
