### ISSUE TITLE
Missing factory functions for FirstTypeNode and LastTypeNode

### ISSUE THREAD

**Issue by wessberg** [Microsoft/TypeScript#18223]
**TypeScript Version:**  2.5.2

**Expected behavior:**

I expect to be able to call `createFirstTypeNode()` and `createLastTypeNode()` like I'm able to do with any other kind of Node.

**Actual behavior:**

Neither `FirstTypeNode` or `LastTypeNode` has an importable interface declaration or predicate function, and (probably as a result), there are no factory functions for neither of them.

**Comment by mhegazy** [comment]
These are just aliases to allow for range checking in the enum. these are not nodes to be created or manipulated.

**Comment by wessberg** [comment]
From my experience, any time I expect a node of kind `TypePredicateNode`, it has the kind `FirstTypeNode`.

For example, consider the following very simple reproducible example:

```typescript
import {createSourceFile, isFunctionDeclaration, ScriptTarget, SyntaxKind} from "typescript";

const sourceFile = createSourceFile("some_file.ts", `
	function isFoo (item: any): item is Foo {
		return true;
	}
`, ScriptTarget.ES2017);

sourceFile.statements.forEach(statement => {
	if (isFunctionDeclaration(statement)) {
		if (statement.type != null) {
                        // Prints 'FirstTypeNode' to the console
			console.log(SyntaxKind[statement.type.kind]);
		}
	}
});
```

My expectation would be for it to be of kind `TypePredicateNode`. What is the rationale?

**Comment by RyanCavanaugh** [comment]
It is a `TypePredicateNode`, but you're looking at the reverse-mapped value from the SyntaxKind enum. The keys `FirstTypeNode` and `TypePredicateNode` both share the same value `158`. The reverse map is lossy, because once you have the value `158` you don't know which key it came from, so it's "last in wins" behavior and unfortunately you get the more confusing of the two keys displayed in this case.

**Comment by wessberg** [comment]
Alright. Good to know! Couldn't find any documentation on this. This issue can be closed. :-)
