### ISSUE TITLE
Returning union of interfaces and conditional parameters

### ISSUE THREAD

**Issue by armano2** [Microsoft/TypeScript#18230]
**TypeScript Version:**  2.5.2

**Code**

```ts

enum Types {
  TYPE_A = 'TYPE_A',
  TYPE_B = 'TYPE_B',
}

interface ITypeA {
  type : Types.TYPE_A
  variable : string
}

interface ITypeB {
  type : Types.TYPE_B
  variable : string
}

function myFunction (variable : string) : ITypeB | ITypeA {
  const type = (variable === 'A') ? Types.TYPE_A : Types.TYPE_B
  return {
    type,
    variable,
  }
}
```

**Expected behavior:**
there should be no type error
**Actual behavior:**
```
Type '{ type: Types; variable: string; }' is not assignable to type 'ITypeA | ITypeB'.
  Type '{ type: Types; variable: string; }' is not assignable to type 'ITypeB'.
    Types of property 'type' are incompatible.
      Type 'Types' is not assignable to type 'Types.TYPE_B'.
```

This code should work same as, because there is no logical distinction between them
```ts
function myFunction (variable : string): ITypeB | ITypeA {
  if (variable === 'A') {
    return {
      type: Types.TYPE_A,
      variable,
    }
  } else {
    return {
      type: Types.TYPE_B,
      variable,
    }
  }
}
```

**Comment by ahejlsberg** [comment]
You're asking that we treat types of the form `{ kind: 'a' | 'b', ... }` as assignable to types of the form `{ kind: 'a', ... } | { kind: 'b', ... }`. This is a valid assumption only in the narrow cases of a _single_ property differing and the remaining properties of the object types all being identical. Those situations are rare in practice, which is why we don't to this extra work in the checker right now.

A simple workaround is to replace `ITypeA | ITypeB` with single declaration:

```ts
interface ITypeAB {
  type : Types.TYPE_A | Types.TYPE_B;
  variable : string
}
```

**Comment by armano2** [comment]
@ahejlsberg i have 86 interfaces some of them with same fields and some with other.

i can't make ITypeAB cus its not going to be valid in rest of checks

**Comment by weswigham** [comment]
I actually ran into this a lot while working on #18285 - you run into more than you'd expect once you start working with discriminated unions and fields you pick from them during control flow analysis... and it's frustrating when it happens.

Also, duplicates #12052.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
