### ISSUE TITLE
Can't use 'contenteditable' property in template

### ISSUE THREAD

**Issue by jaichandra** [Microsoft/TypeScript#18241]
If I have a template like below in my `foo.tsx` file, it fails to compile.

```
export class Foo {
  render() {
    return <div id="textarea" contenteditable="true" />;
  }
}
```

Error:
```
[ ERROR ]  typescript: src/components/foo/foo.tsx, line: 11
           Property 'contenteditable' does not exist on type 'HTMLAttributes'.

     L10:  render() {
     L11:    return <div id="textarea" contenteditable="true" />;
```

**Comment by kitsonk** [comment]
This is not a support forum.

Questions should be asked at [StackOverflow](http://stackoverflow.com/questions/ask?tags=typescript) or on [Gitter.im](https://gitter.im/Microsoft/TypeScript).

But, the error means what it says.  The `@types/react` indicate the attribute is camel cased as `contentEditable`:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/38894f063d8711edebf1b846b34ba55d59a10577/types/react/index.d.ts#L2417

**Comment by jaichandra** [comment]
Thanks @kitsonk. I tried camelCase, but still got the same error. I can check on Gitter.im.

**Comment by DanielRosenwasser** [comment]
Did you get the same error? For the record, you probably want `contentEditable={true}` or just `contentEditable`, as it's a `boolean` and not a `string`.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
