### ISSUE TITLE
Refactor: Extract function/method is not available in the following case

### ISSUE THREAD

**Issue by drake7707** [Microsoft/TypeScript#18242]
**TypeScript Version:**  2.5.2

**Code**

```ts
class Hello {

    static test() {
        var x = { y:0 };
        x.y++;
        return x;
    }
}
```

**Expected behavior:**
Should probably suggest refactor option and generate the following code when applied
```ts
class Hello {
    static test() {

        var x = Hello.newFunction();
        return x;
    }
    
    static newFunction() {
        var x = { y:0 };
        x.y++;
        return x;
    }
}
```

**Actual behavior:**
Select `var x = {y:0}; x.y++;`, no refactor options are applicable. If `return x;` is also selected then a applicable refactor is suggested
![](https://i.imgur.com/S5Tiu3h.gif)

**Comment by RyanCavanaugh** [comment]
This is currently disabled because we disallow extractions which remove the declaration of an identifier that's used outside the extraction range.

It's problematic to allow this because we could change the behavior of your code:

```ts
function f() {
/*start*/
  var x = "hello";
  window.setTimeout(() => { x = "world"; }, 100);
/*end*/
  window.setTimeout(() => { console.log(x); }, 200);
}
```

If we extract this into
```ts
function f() {
  var x = g();
  window.setTimeout(() => { console.log(x); }, 200);
}
function g() {
  var x = "hello";
  window.setTimeout(() => { x = "world"; }, 100);
  return x;  
}  
```
the function prints "hello" instead of "world"

Just checking for assignments isn't enough to be correct in all cases, either, since a `setTimeout` call is bad but a `forEach` call is OK

**Comment by amcasey** [comment]
Maybe we could allow it unless the declared variable is captured?  Are there other cases where it's problematic?

**Comment by RyanCavanaugh** [comment]
Detecting captures should be sufficient, though we'll also have to check for captures *outside* the extraction range.

Turns out we allow you to extract this statement into the global scope
```ts
function f() {
    var x = "hello";
    /*start*/
    window.setTimeout(() => { x = "world"; }, 100);
    /*end*/
    window.setTimeout(() => { console.log(x) }, 200);
}
```
which changes the behavior too:
```ts
function f() {
    var x = "hello";
    x = newFunction(x);
    window.setTimeout(() => { console.log(x) }, 200);
}

function newFunction(x: string) {
    window.setTimeout(() => { x = "world"; }, 100);
    return x;
}
```
which also breaks your code.  🤷‍♂️ ?
