### ISSUE TITLE
Compiler produces invalid `Array().keys().slice()` output

### ISSUE THREAD

**Issue by alextreppass** [Microsoft/TypeScript#18247]
I was looking for a compact way to write a 'range' function and stumbled across [this stackoverflow answer](https://stackoverflow.com/a/33352604/1021051).

The spread operator variant compiles successfully but the output is not valid.

**TypeScript Version:**  2.5.2

**Code**

```ts
// expected output
const expected = [0, 1, 2, 3, 4];

// works in vanilla JS
// breaks in TS
// compiles to `Array(5).keys().slice()` which breaks as keys() returns an Iterator
const withSpread = [...Array(5).keys()];

// works in vanilla JS
// works in TS
// compiles to `Array.from(Array(5).keys())`
const from = Array.from(Array(5).keys());
```

**Expected behavior:**
The `withSpread` variant should produce valid JS that generates `[0, 1, 2, 3, 4]`

**Actual behavior:**
Resulting JS throws `TypeError: Array(...).keys(...).slice is not a function`

**Comment by ikatyang** [comment]
Target es5 -> [`--downlevelIteration`](https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#new---downleveliteration)
Target es6 -> `--target es6`

**Comment by alextreppass** [comment]
Thank you!
