### ISSUE TITLE
Use compiler from within nodejs

### ISSUE THREAD

**Issue by luisrudge** [Microsoft/TypeScript#1826]
How can I do something like that?

```javascript
var ts = 'var a: number = 1;'
var js = require('typescript-compiler').compile(js);
````

**Comment by basarat** [comment]
Not supported in `typescript` package. But coincidently there is an NPM package that does this exact thing by the exact name : https://www.npmjs.com/package/typescript-compiler 

Would be great if `typescript` compiler api exposed this. 

```ts
var ts = 'var a: number = 1;'
var js = require('typescript').compile(ts);
```
---- 
minor `var js = require('typescript-compiler').compile(js);` change to `var js = require('typescript-compiler').compile(ts);` i.e. `ts` not `js`.

**Comment by danquirk** [comment]
Yeah the compiler doesn't have an API/package that makes it that simple. Of course you can use your favorite process spawning library to just spawn ```node tsc.js <your command line>``` too.

**Comment by basarat** [comment]
> favorite process spawning library to just spawn node tsc.js <your command line> too.

good if one is willing to write the string to a `.ts` file first.

**Comment by luisrudge** [comment]
@basarat I'll try that package right now!

**Comment by DanielRosenwasser** [comment]
Also see [typescript-simple](https://github.com/teppeis/typescript-simple), courtesy of @teppeis.

**Comment by luisrudge** [comment]
@DanielRosenwasser nice! What's the difference between the two?

**Comment by DanielRosenwasser** [comment]
*Between typescript-simple and spawning tsc?*
* Just use typescript-simple and you don't need to create another process to get your emit.

*Between typescript-simple and our API?*
* typescript-simple uses our API and simplifies the interface because most people don't want to muck around with the configuration we provide.

**Comment by mhegazy** [comment]
For completeness sake. Here is how you can use the API to achieve a string transformation:
https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#a-simple-transform-function

**Comment by teppeis** [comment]
@luisrudge @DanielRosenwasser Yes, [typescript-simple](https://github.com/teppeis/typescript-simple) is simple and ***fast*** way to compile TypeScript code string!
Because,
* typescript-simple doesn't create child processes
* typescript-simple caches parsed `lib.d.ts`

For example, ES6 compat-table build time [has been improved from 300s to 2s](https://github.com/kangax/compat-table/pull/405).

Instead, it cannot compile TS code importing external modules.

**Comment by DanielRosenwasser** [comment]
> from 300s to 2s.

Wow, that's dramatic - that's actually how I knew about typescript-simple, but I didn't realize the speedup was that significant when I read it. I'm glad the the API helped in that respect.

> typescript-simple caches parsed lib.d.ts

Nice!

> Instead, it cannot compile TS code importing external modules.

What exactly is the shortcoming in that respect?

**Comment by teppeis** [comment]
@DanielRosenwasser 

> I didn't realize the speedup was that significant

There is a little trick :smile: 

ES6 compat table has over 300 tiny tests like:

```javascript
// A test code for arrow function
function() {
  return (() => 5)() === 5;
}
```

So previously ES6 compat table creates child processes and runs `tsc` over 300 times. It takes about 300s.

At first, typescript-simple prevents from creating processes. It reduces the time to 200s.

Second, typescript-simple shares cache of parsed `lib.d.ts` in all tests. It reduces the time to 2s.

It means that the time of `tsc` command for tiny code consists mostly of parsing `lib.d.ts`.
I think it's nice solution for `tsc` to run an incremental compiler server in background implicitly, like `flow` of Flowtype.

**Comment by DanielRosenwasser** [comment]
> I think it's nice solution for tsc to run an incremental compiler server in background implicitly, like flow of Flowtype.

A common misconception is that we don't have that. It's the `--watch` flag.
