### ISSUE TITLE
issue with decorator functions and type matching

### ISSUE THREAD

**Issue by bradzacher** [Microsoft/TypeScript#18269]
**TypeScript Version:**  2.5.2

**Code**

```ts
class parentClass {
  fn() {
    return null as string | false
  }
}

function deco(a: any) {
  return a as typeof parentClass
}

// USAGE ONE
const oneDeco = deco(
  class one extends parentClass {
    fn() {
      return null as string
    }
  }
)

// USAGE TWO
@deco
class two extends parentClass {
  fn() {
    return null as string
  }
}
```
Above example: https://codesandbox.io/s/7w6lp075yx?module=%2Ftest.ts&view=editor

**Expected behavior:**
both usages of `deco` should compile without issue

**Actual behavior:**
`USAGE ONE` compiles fine.
`USAGE TWO` compiles with error:
```
Unable to resolve signature of class decorator when called as an expression.
  Type 'typeof parentClass' is not assignable to type 'typeof two'.
    Type 'parentClass' is not assignable to type 'two'.
      Types of property 'fn' are incompatible.
        Type '() => string | false' is not assignable to type '() => string'.
          Type 'string | false' is not assignable to type 'string'.
            Type 'false' is not assignable to type 'string'.
```

Considering the below works fine, shouldn't the type matcher be able to understand that `string` is compatible with `string | false`?
```TS
class parentClass1 {
  fn() {
    return null as string | false
  }
}

class three extends parentClass1 {
  fn() {
    return null as string
  }
}

const worksFine : typeof parentClass1 = three // no error
```
above example: https://codesandbox.io/s/nkv1p5256m?module=%2Ftest2.ts&view=editor

This is causing an issue right now with a decorator I'm trying to type for react.
The decorator essentially returns a HOC that accepts an single extra property (i.e. it just returns `React.ComponentClass<P & { prop: type }>`).
However as my component's `render` method just returns `JSX.Element`, the decorator fails to compile (because `React.Component`'s definition defines `render() : JSX.Element | false`).

**Comment by bradzacher** [comment]
another (perhaps unrelated) instance of decorators being unable to resolve signatures:
```TS
import * as React from 'react'

function deco(a: any) : React.ComponentClass<any> {
  return a
}

// USAGE ONE
const oneDeco = deco(
  class one extends React.Component<{}, {}> {
    render() { return null }

    componentDidMount() { }
  }
)

// USAGE TWO
@deco
class two extends React.Component<{}, {}> {
  render() { return null }

  componentDidMount() { }
}
```
example above: https://codesandbox.io/s/nkv1p5256m?module=%2Ftest.ts&view=editor

As before
`USAGE ONE` works fine
`USAGE TWO` errors with:
```
Unable to resolve signature of class decorator when called as an expression.
  Type 'ComponentClass<any>' is not assignable to type 'typeof two'.
    Type 'Component<any, ComponentState>' is not assignable to type 'two'.
      Property 'componentDidMount' is optional in type 'Component<any, ComponentState>' but required in type 'two'.
```

`ComponentClass`'s definition includes the constructor definition `new (): Component`, and the interface definition of `Component` has all its lifecycle methods defined as optional (i.e. `componentDidMount?() : void`

**Comment by mhegazy** [comment]
decorators can not change the type of the class. they can override it with another class but it has to have a matching type. 
in your first example, `deco` always returns `parentClass`, so when you apply it to class `two` you still get `parentClass`. 
what you want is to make sure you are not chaining the class, i.e.:
```ts
function deco<T>(a: T): T ..
```

in practice, you can return a new class that extends the decorated class. e.g.:

```ts
function deco<T extends new (...args) => object>(a: T): T {
    return class decorated extends a {
       addtionalProp = 0;
    }
}
```

**Comment by bradzacher** [comment]
ah, I see, thank you.
I didn't realise that the return of a decorator had to be a direct subclass - I was under the impression that it could return a matching super (like a normal function call).

Thanks for your help.

For future reference, I have changed my code around to use generics to enforce expected subclassing.

```TS
// IN STEAD OF THIS:
function wrongDeco<TP>(component: React.ComponentClass<TP>) : React.ComponentClass<TP>;

// USE THIS
function deco<TP, TC extends React.ComponentClass<TP>>(component : TC) : TC;
```
