### ISSUE TITLE
JavaScript assignment should infer function parameter types from assigned values's signature

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#18260]
From https://github.com/Microsoft/vscode/issues/33824

**TypeScript Version:**  2.5.2

**Code**

For the javascript

```js
const img = document.createElement('img')
img.onclick = function(e) {
    
}
```

**Expected behavior:**
`e` is of type `MouseEvent`

**Actual behavior:**

`e` is of type `any`

Since there is no explicit jsdoc here, I believe `e` should be inferred to be of type `MouseEvent`. This is what happens in TS files with the same content

I believe this problem is similar to #18115

**Comment by mhegazy** [comment]
Seems fixed in latest.
