### ISSUE TITLE
Add refactoring option to convert string concatenation to template literals

### ISSUE THREAD

**Issue by proteriax** [microsoft/TypeScript#18267]
Consider adding the refactoring option to turn a string concatenation

```ts
console.log("My name is " + firstName + " " + lastName + ".");
```

to ES2015 template literals:
```ts
console.log(`My name is ${firstName} ${lastName}.`);
```

**Comment by glixlur** [comment]
Will you welcome a pull request for this?

**Comment by glixlur** [comment]
Would you welcome a pull request for this?

**Comment by mhegazy** [comment]
Yes.

**Comment by glixlur** [comment]
I definitely need some help on this one...

**Comment by mhegazy** [comment]
I would look at https://github.com/Microsoft/TypeScript/blob/master/src/services/refactors/generateGetAccessorAndSetAccessor.ts for a reference

**Comment by bigaru** [comment]
@glixlur is it okay for you?
If I would provide a PR for this issue

**Comment by DanielRosenwasser** [comment]
Thanks @bigaru!
