### ISSUE TITLE
Narrowing doesn't happen with Partial

### ISSUE THREAD

**Issue by ethanresnick** [Microsoft/TypeScript#18266]
**TypeScript Version:**  2.5.2

**Code**

```ts
type Keys = "a" | "b";

declare var x: Partial<{
    [K in Keys]: number
}>;

function y(k: Keys, v: any): number {
    if (x[k]) { 
        return x[k]; // should be number
    }
    return 0;
}
```

**Expected behavior:**
Compiles without errors.

**Actual behavior:**
`x[k]` in the if block is inferred as `number | undefined` and I get the error "Type 'undefined' is not assignable to type 'number'."

**Comment by mhegazy** [comment]
it is not partial it is `[k]` that is causing the issue. fix tracked in https://github.com/Microsoft/TypeScript/issues/10530

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
