### ISSUE TITLE
Extract function doesn't work for nested exponentiation operator

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#18268]
```ts
1 ** 2 ** 3 ** 4
```

Try to extract out `2 ** 3`.

**Expected**: Option to extract out `2 ** 3`
**Actual**: Nothing.

**Comment by amcasey** [comment]
Is it right associative?  I think the binary operator compensation code assumes all operators are left associative, so it might be blowing up.  Either way, I don't believe you could ever extract `2 ** 3`.  You'd either get `1 ** 2 ** 3` or `2 ** 3 ** 4`, depending on the associativity of the operator.

**Comment by DanielRosenwasser** [comment]
Yes, it's right associative. I realized the bug existed from reading the code before I actually stumbled onto it. 😄

**Comment by amcasey** [comment]
I think I reported the same bug with assignment.  I can't remember what happened with that.  @RyanCavanaugh ?
