### ISSUE TITLE
Strange warning with 'instanceof'

### ISSUE THREAD

**Issue by aeschli** [Microsoft/TypeScript#18276]
TypeScipt 2.5.2

Sorry, I wasn't able to extract a simplified example:

- `git clone https://github.com/Microsoft/vscode-css-languageservice.git`
- `cd vscode-css-languageservice` 
- `git checkout 73f8707`
- `npm install`
- `npm run compile`

`src/services/cssCompletion.ts(804,47) error TS2358: The left-hand side of an 'instanceof' expression must be of type 'any', an object type or a type parameter.`
[link to cssCompletion.ts: 804](https://github.com/Microsoft/vscode-css-languageservice/blob/73f8707a411150c49e2b6ca44ecc1d06d263c005/src/services/cssCompletion.ts#L804)

![image](https://user-images.githubusercontent.com/6461412/30122005-7865330e-932d-11e7-9703-ef08c26b4b91.png)

It's a new error, not reported by a previous version of typescript.
Both `nodes.HexColorValue`([link](https://github.com/Microsoft/vscode-css-languageservice/blob/73f8707a411150c49e2b6ca44ecc1d06d263c005/src/parser/cssNodes.ts#L1205)) and `nodes.Function`([link](https://github.com/Microsoft/vscode-css-languageservice/blob/73f8707a411150c49e2b6ca44ecc1d06d263c005/src/parser/cssNodes.ts#L704)) are classes that extend base class `nodes.Node`([link](https://github.com/Microsoft/vscode-css-languageservice/blob/73f8707a411150c49e2b6ca44ecc1d06d263c005/src/parser/cssNodes.ts#L146)). The way I see it, the instanceof test is valid code to test the runtime types of the object.

Adding a brand field `_hexColorValue : void;` to `nodes.HexColorValue` fixes the issue, so maybe this is related to #12083.
At the very least the message should be improved, but IMO the error is invalid.

**Comment by ezequiel-umu** [comment]
The compiler is telling you that the right part of your `||` operation is never happening. It may be a bug, but you should add the definitions of `nodes.HexColorValue`, `nodes.Function` and `nodes.Node` to be sure. Also, try to do a simplified version of the code and use text instead of images.

**Comment by aeschli** [comment]
@ezequiel-umu Thanks for the reply. As mentioned, I was not able to reproduce the issue with a simplified version. I added links to the source code. But the steps to reproduce are also quite simple.

**Comment by ezequiel-umu** [comment]
I didn't try to reproduce, but to me that looks like the problem you mentioned:

https://github.com/Microsoft/TypeScript/issues/12083

A bad decision making `instanceof` a structural check at compile time IMHO.
