### ISSUE TITLE
Allow redefining member type in extended interface (like "new" keyword in C#)

### ISSUE THREAD

**Issue by pmunin** [Microsoft/TypeScript#18278]
**TypeScript Version:**  2.5.2

**Code**
It would be great if extending Interface would allow to redefine member's types (similar to the "new" modifier in C#)
```ts
interface IHasData
{
   data:string|number;
}

interface IHasDataEx extends IHasData
{
   data:string|number|Function;
}

let x:IHasDataEx = {
  data:function(){
     return "Hallo world";
  }
}

```

**Expected behavior:**
Successful compilation and ability to do IHasDataEx.data = function(){...}

**Actual behavior:**
Compilation error:
```
Interface 'IHasDataEx' incorrectly extends interface 'IHasData'.
  Types of property 'data' are incompatible.
    Type 'Function' is not assignable to type 'string | number'.
      Type 'Function' is not assignable to type 'number'.
```

**Ugly workaround:**
```ts
interface IHasData
{
   data:string|number;
}

interface _IHasDataEx extends IHasData
{
   data:any;
}

interface IHasDataEx extends _IHasDataEx
{
   data:string|number|Function;
}

let x:IHasDataEx = { 
  data:function(){          //OK
     return "Hallo world";  
  }
}

x.data = "Hallo world" ;  //OK
x.data = 123;   //OK
x.data = new Promise(...)  //Compilation should fail, because data is not string|number|function

```

**Comment by andy-ms** [comment]
That wouldn't be sound though.
```ts
interface IHasData
{
   data:string|number;
}

interface IHasDataEx extends IHasData
{
   data:string|number|Function;
}

function f(x: IHasData) {
    if (typeof x.data !== "string") {
        // This is safe to use as a number, right?
        useAsNumber(x.data);
    }
}
const x: IHasDataEx = { data() {} };
f(x); // IHasDataEx extends IHasData, so safe to call `f` on one, right?
```

**Comment by pmunin** [comment]
@andy-ms,  Not sure how it helps. Function "f" must accept IHasDataEx, because internally it checks if data is of type Function (or some other type defined in IHasDataEx).

**Comment by zspitz** [comment]
> Function "f" must accept IHasDataEx, because internally it checks if data is of type Function (or some other type defined in IHasDataEx).

The problem is not in the function you're defining here to parse the `data`; the problem is in any other function in the entire codebase that takes `IHasData`, and will now have unexpected results/consequences once the `IHasDataEx` interface is introduced.

---

Perhaps the following alternative might be of use:
```tsinterface IHasData {
   data: string|number;
}

interface IHasData2 {
   data: Function;
}

function f(x: IHasData | IHasData2) {
    if (typeof x.data !== "string") {
        // Error -- x.data might be a Function
        console.log(5 + x.data);
    }
}
const x = { data() {} };
f(x); // IHasDataEx extends IHasData, so safe to call `f` on one, right?
```

**Comment by pmunin** [comment]
hmm yeah that makes sense

**Comment by andy-ms** [comment]
If your subtype can't be used in a location where the supertype is expected, maybe you shouldn't be using `extends` at all, and use a union instead as in @zspitz's post, which will force you to handle both possible cases.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
