### ISSUE TITLE
Quickfix to prefix unused arrow function parameter opens new file

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#18275]
**TypeScript Version:**  nightly (typescript@2.6.0-dev.20170906)

**Code**

```ts
const f = x => 1;
```

Apply the quickfix to prefix 'x' with an underscore.

**Expected behavior:**

Edit the current file.

**Actual behavior:**

Opens a new file:
![shot5](https://user-images.githubusercontent.com/19274678/30121615-0884b722-92e1-11e7-850d-d696304fea74.jpg)

**Comment by mhegazy** [comment]
Can you share the log? looks like paths issue.

**Comment by andy-ms** [comment]
Can't reproduce this on linux; may be related to #18316. Will test tomorrow with the new build to see if it's fixed.

**Comment by amcasey** [comment]
Is this still an issue?  I can't say that I've ever seen it.
