### ISSUE TITLE
Quickfix for unused arrow function parameter results in invalid code

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#18274]
**TypeScript Version:**  nightly (typescript@2.6.0-dev.20170906)

**Code**

```ts
const f = x => 1;
```
Apply the `Remove declaration for 'x'` quickfix.

**Expected behavior:**

```ts
const f = () => 1;
```

**Actual behavior:**

```ts
const f = => 1;
```

**Comment by amcasey** [comment]
It turns out that our infrastructure is not well-suited to synthesizing the required parameters.  We think that the emitter might do the right thing if we deleted the parameter list entry, but it might not and there would still be trivia issues.

TL;DR: This might be non-trivial.
