### ISSUE TITLE
Set a type guard for hasOwnProperty signature. 

### ISSUE THREAD

**Issue by ezequiel-umu** [Microsoft/TypeScript#18282]
**TypeScript Version:**  2.5.0-dev.20170629

Watch this code with a new version of hasOwnProperty:

```ts
function hasOwnProperty<T, K extends keyof T>(object: T, key: string): key is K {
  return object.hasOwnProperty(key);
}

const x = {
  a: "a",
  b: "b",
};

// Ensure k is unknown for the transpiler:
const k = String.fromCharCode("a".charCodeAt(0) + 1);

// This is working without any problem.
if (hasOwnProperty(x, k)) {
  x[k] = "anything";
}

// This blames: file: 'Element implicitly has an 'any' type because type '{ a: string; b: string; }' has no index 
if (x.hasOwnProperty(k)) {
  x[k] = "anything";
}

// This emits the same error:
if (k in x) {
  x[k] = "anything";
}
```

**Suggestion:**

Change the actual declaration of `hasOwnProperty`:

```ts
hasOwnProperty(v: PropertyKey): boolean;
```

With a new one type guarded:

```ts
hasOwnProperty<T, K extends keyof T>(this: T, key: string): key is K;
```

Something that also could be added is a type guard to `in` operator to work as the type guard of the suggested `hasOwnProperty`  .

**Comment by mhegazy** [comment]
you do not need the `K` type parameter. a simplified version would be:

```ts
   hasOwnProperty<T>(this: T, v: PropertyKey): v is keyof T;
```

**Comment by mhegazy** [comment]
The use of `in` is tracked by https://github.com/Microsoft/TypeScript/issues/10485

**Comment by mhegazy** [comment]
similar discussion can be found in https://github.com/Microsoft/TypeScript/pull/12253#issuecomment-263132208

**Comment by DanielRosenwasser** [comment]
This really isn't appropriate. At runtime, your object might have more keys than `T` describes, so the sort of information you're trying to convey to the type system wouldn't be true.

There are two things that this function gives information about:

1. Some value `x` of type `T` also has a property key `K` (i.e. x is T & Record<K, any>).
2. Some value `x` of type `T` that has an optionally defined key of type `U` (i.e. `T extends Partial<Record<K, U>>` ) actually has that property defined (i.e. `x is T & Record<K, U>`).
