### ISSUE TITLE
Unit testing typescript classes with jest (“Cannot read property '__extends' of null”)

### ISSUE THREAD

**Issue by davidreher** [Microsoft/TypeScript#1829]
I am trying to test class "a" (which inherits from class "b") with jest. The typescript compiler prepends the file compiled javascript of "a" with

    var __extends = this.__extends || function (d, b) { ... };

unfortunately `this` is null, when running the unit test, so I am getting

    Cannot read property '__extends' of null

I am using jest-cli@0.2.1 to run the tests and typescript@1.4.1 to compile my typescript files.
Normally `this` would point to window, when the files are run in a browser.

Does someone know how to get around that issue?

**Comment by danquirk** [comment]
Do you know why ```jest``` is executing tests in a context where ```this``` is null? We've never seen this issue before, curious why it's behaving so differently from other major test frameworks on this front.

**Comment by DanielRosenwasser** [comment]
Offhandedly, this sounds like more of an issue with jest, though I can't be certain.

**Comment by RyanCavanaugh** [comment]
I investigated this in the jest sourcecode when this got posted on StackOverflow; they do actually invoke the test function with an intentional `null` `this`. I have no idea why they would do that; I can't imagine only TypeScript gets broken by that.

**Comment by davidreher** [comment]
@RyanCavanaugh Where did you find that? I already looked into the source code but couldn't find the place ... If you would provide me with the source I could submit a pull request or something of that kind ...

I asked on stackoverflow (where you kindly responded) and in the issue tracker of jest but did not get a answer or workaround by the team ...

**Comment by RyanCavanaugh** [comment]
I'm presuming the offending line is here

https://github.com/facebook/jest/blob/5d33de730882a06f500514c1f7e37c82191619f2/src/lib/utils.js#L357

`runContentWithLocalBindings` is used by their testRunners

**Comment by davidreher** [comment]
Thanks, by adding `{}` instead of `null` as you suggested, it works for me now ... I am currently thinking about creating a fork or switch the framework ...

Nonetheless thanks for your help!

**Comment by DanielRosenwasser** [comment]
@davidreher not sure if you were implying it, but I'm sure that if you made that fork, the jest folks would probably appreciate a PR or an issue relating to it.

**Comment by jskulavik** [comment]
Hi Folks,  I'm receiving this error today.  I have member variables on a class that are undefined when running Jest tests against them.  Given that it's been three years, I have to assume the fix above is no longer valid.  Is anyone aware of an up-to-date solution to this problem?
