### ISSUE TITLE
Suggestion: callable class

### ISSUE THREAD

**Issue by fdecampredon** [microsoft/TypeScript#183]
``` typescript

class MyCallableClass {
   property: string;
   constructor() {
     //constructor body
   }
   (): MyCallableClass { // could be 'string' or any other type
     // call signature body
     return new MyCallableClass();
   }
}
```

would emit : 

``` javascript
function MyClass() {
  if (this instanceof MyClass) {
    //constructor body
  } else {
    // call signature body
    return new MyCallableClass();
  }
}
```

**Comment by SaschaNaz** [comment]
Just note: This is being discussed for ES7 - https://gist.github.com/ericelliott/1c6f451b2ed1b634c2f2#file-es7-new-fix-js

**Comment by Tragetaschen** [comment]
I'm currently missing something like this, but not particularly for a `new` replacement. I'm trying to implement [a scale in d3](https://github.com/borisyankov/DefinitelyTyped/blob/3e34cacf20575e5468d0dbee0954416100431907/d3/d3.d.ts#L1506), where the resulting object has
- function call semantics: `scale(3)` scales the value 3 from the input domain to the output range
- several functions like getting/setting the `scale.domain()` or `scale.invert()`ing the above

I haven't found any way to implement this interface in TypeScript without resorting to some hefty `<any>` casting.

**Comment by SaschaNaz** [comment]
Just note 2: ES7 Stage 1 proposal https://github.com/tc39/ecma262/blob/master/workingdocs/callconstructor.md

**Comment by qbolec** [comment]
I have a concrete problem with https://github.com/peerlibrary/meteor-reactive-field library which allows me to write code like this:
```
import { ReactiveField } from 'meteor/peerlibrary:reactive-field';
var  f = new ReactiveField(71); 
f(69); //set field to 69
console.log(f()); //retrieve 69
```
Im trying to write a declaration file for it, which would make complier happy.
I've tried:
```
declare module "meteor/peerlibrary:reactive-field" {
  export class ReactiveField<T> {
    (value?:T):T;
    constructor(value:T,equals?:(a:T,b:T)=>boolean);
  }
}
```
but it fails with error messages like:
```
client/imports/ui/recordPlayer/reusableRecordPlayer.ts (34, 7): Cannot invoke an expression whose type lacks a call signature.
```
whenever I try to call `f()`.
I would appreciate any workaround which would allow me to declare this module.

**Comment by rjamesnw** [comment]
You could force cast it to a call signature. Something like 'var _f: { ():any } = <any>f;' then call '_f()' instead.

**Comment by DanielRosenwasser** [comment]
@qbolec in the future, StackOverrflow is a better venue, but what we usually do is separate the instance/static sides into their own interfaces.

```ts
// Shape of the constructor function.
interface ReactiveFieldStatic {
    new <T>(value: T, equals: (a: T, b: T) => boolean): ReactiveField<T>;
}

// Shape of the instance.
interface ReactiveField<T> {
    (value?: T): T;
}

// The constructor function itself.
var ReactiveField: ReactiveFieldStatic;
```

**Comment by DanielRosenwasser** [comment]
For the record, callable classes are now an [inactive proposal](https://github.com/tc39/proposals/blob/58f74a51c22f7d18b8b71836e4810c4235e16e03/inactive-proposals.md). Check out portions of the discussion [here](https://github.com/rwaldron/tc39-notes/blob/924122cdc03e9ee2afbe8014193f845bddc6da2d/es7/2016-01/2016-01-28.md#progress-review-callable-class-constructors-allen).

**Comment by qbolec** [comment]
Thank you @DanielRosenwasser - it is very clever solution. I had my mind fixed on the bad assumption that "a var cannot be polymorphic", and totally failed to notice that it is not "var ReactiveField" that has to be polymorphic, but rather the "new" operator. Great idea!

**Comment by rjamesnw** [comment]
So the transcript of the discussion claims decorators can solve making classes callable.  I'm looking into that and I fail to see how that works - any examples?

**Comment by DanielRosenwasser** [comment]
@rjamesnw With TypeScript's *current* implementation of decorators, I believe the following should work to make a class both `new`-able and callable:

```ts
function callable(classTarget: any) {
    return function (...args) {
        new classTarget(...args);
    };
}

@callable
class C {
    constructor(...args) {
        console.log("Being constructed with: " + JSON.stringify(args));
    }
}

C(1, 2, 3, 4);
new C(5, 6, 7, 8);
```

However, right now TypeScript can't communicate that both types are callable and constructable.

You can also differentiate the behavior by using `new.target` and giving the decorator a callback:

```ts

// Thing that gets passed a function.
function callableWith(call: (...args: any[]) => any) {
    // Thing that actually decorates the class:
    return function decorator(construct: new (...args: any[]) => any) {
        // Thing that actually replaces the class:
        return function replacement (...args) {
            if (new.target) {
                return new construct(...args);
            }
            else {
                return call(...args);
            }
        }

    }
}

@callableWith((...args) => {
    console.warn("Hey, you probably want to use 'new C(...)' instead of 'C(...)'!)
    return new C(...args);
})
class C {
    constructor(...args) {
        console.log("Being constructed with: " + JSON.stringify(args));
    }
}
```

**Comment by rjamesnw** [comment]
Some points:

1. "new ctor(...args);" is not valid, so I assume you mean "new ctor(args);".
2. Your code doesn't work at all in the playground nor VS 2017.  The "@callable" is underlined in red with the error "unable to resolve signature of class decorator when called as an expression". As a result, 'C' is not callable.
3. I assume overloading is not supported this way, so there will only be one type of callable signature ... ?

Thanks.

**Comment by SaschaNaz** [comment]
@rjamesnw You can try VS2017.2 which includes TS2.2 😄 https://www.visualstudio.com/en-us/news/releasenotes/vs2017-preview-relnotes

**Comment by rjamesnw** [comment]
Turns out with v2.2 you can also use type intersections for this (was an issue in previous versions, as you couldn't represent both new and non-new signatures well across two different interfaces). At least now I can have an interface from a class, and merge it with a callable signature from another, and it will work now. The examples above however still don't work.

**Comment by rjamesnw** [comment]
@DanielRosenwasser For the record, `new.target` is always true, unless targeting the newer ES versions, so that logic can easily break if not careful.

**Comment by rjamesnw** [comment]
I mentioned this in another post, but thought I'd put it here also in case someone else comes here.  ES6 introduces specialized functions, and thus any direction towards a callable constructor is a bad idea. Targeting future ES versions will output using the "class" symantec, which will fail if called directly; For example, in Chrome, it generates the error `Uncaught TypeError: Class constructor ... cannot be invoked without 'new'.`  In the end, there seems to be no point for TypeScript to support it and keep in line with the standards at the same time.

**Comment by rjamesnw** [comment]
May I suggest instead, since callable constructors are not supported, that we can at least compromise with allowing the "new" modifier to allow forcing new *static* function signatures on derived types? Static functions could be used as factories (such as 'SomeType.create()') and accept different parameters based on type.

**Comment by athasach** [comment]
@DanielRosenwasser How might your decorator work for generic classes? For example, I have this case:

```ts
abstract class Try<T> {
}

class Success<T> extends Try<T> {
  constructor(public readonly value: T) {
    super();
  }
}

// How might I construct `Success<string>` without calling `new`?
const success = Success('successful');
```

**Comment by leonard-thieu** [comment]
Would it be possible to have call signatures _just_ for ambient class declarations? It'd make it possible to accurately model some JavaScript libraries. Using two interfaces gets close but you lose type narrowing on `instanceof`. Plus, it'd be a whole lot cleaner.

**Comment by Domvel** [comment]
bump ... any news? :)

**Comment by DanielRosenwasser** [comment]
Nope!

**Comment by rjamesnw** [comment]
It's not possible to have callable classes.  It is not supported in the spec.  Calling a class will cause errors (try it yourself).  For this reason it makes sense that this will never be supported.  That said, I could agree however that if we could force-enable functions (instead of the new `class` syntax) and still be able to export ES6+ code, that callable classes in this case would of course work. Anyhow, good luck with that. LOL ;)

**Comment by Domvel** [comment]
After a few month I facing this issue again. 
But now I think: Should I really support callable classes? Don't hit the 👎 yet. 😄 Let me explain my thinking. 🤔 

A class should be instantiated and not called as function. If you call the class which checks `this` is an instance of class-constructor and returns `any` (or what you want) if it called as `function` is a bit "confusing" and a bit against the strict typing in TypeScript.

Hold on ... I still 👍 this issue. But I just thinking loud. 
You can export a function which just do the job as suggested here.
e.g. 

```ts
export class UUID {
  value: string;
  constructor() {
    this.generate();
  }
  // ...
}

export const newUUID = (): string => {
  return new UUID().toString();
};

const uuidInstance = new UUID();
const uuidString = newUUID();

```
vs

```js
function UUID() {
  if (this instanceof UUID) {
    // Called as class.
    this.generate();
  } else {
    // Called as function.
    return new UUID().toString();
  }
}
```

It's a great 'feature' in JavaScript. But maybe not the right for TypeScript. 
I like JavaScript, I love TypeScript and with VS Code I would like to intimate. 😄 

**NOTE**: How should this work in ES6 and "real" classes? (`class` keyword)
If you compile TypeScript to ES6 with class-feature. You'll get an TypeError:
`Class constructor UUID cannot be invoked without 'new'` ...

**Comment by goodmind** [comment]
Agree that just enable it for ambient classes

**Comment by jpolo** [comment]
@Domvel This issue is about expressiveness of the language. The `Constructor()` is not a simple shortcut to the constructor it is often used as the coercion operator (cf https://github.com/Microsoft/TypeScript/issues/183#issuecomment-61289980). 

A good way to measure the expressiveness of Typescript is that it should allow to reimplement all ECMA spec just in pure TS (= no definitions). At the moment it is quite hard to express in Typescript a class that would behave like String, Date, Number, etc because of the lack of callable classes.
