### ISSUE TITLE
export after type guard

### ISSUE THREAD

**Issue by worudso** [Microsoft/TypeScript#18303]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)
2.5.2
**Code**

```ts
const port = process.env.PORT;
if (typeof port !== "string") {
    throw new Error("Please set PORT environment variable");
}

export {port};
```

**Expected behavior:**
I want the type of `port` to be `string`. I'm not saying it's right. I just want to let you know this kind of usage and have some discussion.
**Actual behavior:**
The type of `port` is `string|undefined`

**Comment by mhegazy** [comment]
We can not do that safely for `let`/`var`, but const seems safe. that said the change is rather big, and i am not sure if the cost warrants the value here.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
