### ISSUE TITLE
Help information doesn't contain --traceResolution flag

### ISSUE THREAD

**Issue by ikokostya** [Microsoft/TypeScript#18309]
**TypeScript Version:**  2.5.2

**Code**

Run `tsc` with `--help` flag:

```
$ tsc --help
```

**Expected behavior:**

`--traceResolution` flag is presented in help information.

**Actual behavior:**

`--traceResolution` flag is not presented.

**Comment by RyanCavanaugh** [comment]
The `--help` list is abbreviated to common options only. Run `--help --all` to see why 😉

**Comment by ikokostya** [comment]
Thanks!
