### ISSUE TITLE
Type assignment between object types fails even when compatibility was checked through type-guards on properties

### ISSUE THREAD

**Issue by fpascutti** [Microsoft/TypeScript#18304]
From [section 3.11.4 (assignment compatibility)](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#3.11.4) of the specification, an object type `T` should be assignable from an object type `S` when all `T`'s properties exist on type `S` (same name) and each can be assigned from the corresponding property on type `S`.
However this does not work when property assignability was proven through a type-guard.

**TypeScript Version:**  2.5.2

**Code**

```ts
interface Widget {
  readonly data: string | number;
}
interface Gadget {
  readonly data: string;
}

function foo(g: Gadget): void {
  console.log(g.data);
}
function bar(w: Widget): void {
  if (typeof w.data === "string") {
    const d: string = w.data; // `w.data` correctly recognized as a `string`
    foo(w); // however `w` cannot be used as a `Gadget`
  }
}
```

**Expected behavior:**

Compiles successfully.

**Actual behavior:**

Compilation fails with:
```
error TS2345: Argument of type 'Widget' is not assignable to parameter of type 'Gadget'.
  Types of property 'data' are incompatible.
    Type 'string | number' is not assignable to type 'string'.
      Type 'number' is not assignable to type 'string'.
```

**Comment by RyanCavanaugh** [comment]
See #10065

**Comment by fpascutti** [comment]
Thanks. I did not find this issue.
Your latest comment makes sense by the way.
