### ISSUE TITLE
Better completion in VS

### ISSUE THREAD

**Issue by NN---** [Microsoft/TypeScript#1830]
Supposing you have code like this one:

```
	interface Q {
		a: string;
	}

	function f(q: Q) { }

	var q = { // <-- Cursor is here
	};
	f(q);
```

I would like to have a suggestion of 'a' property inside the object since it is called by function 'f' which received a parameter of type Q.
Currently VS doesn't suggest anything as opposed to declaration with type 'var q : Q' .

It could suggest specifying an exact type for 'q' variable as well.
Is it possible to do this ?

**Comment by RyanCavanaugh** [comment]
I don't think it's reasonable for us to do this kind of backwards flow analysis at this time. While this case is simple, the complexity of figuring out the exact flow of a variable through a statement block is unending.

**Comment by mhegazy** [comment]
Completion list works on places where you have contextual type though. 
```TypeScript
    interface Q {
        a: string;
    }

    function f(q: Q) { }

    var q: Q = { 
        // <-- Cursor is here shows "a"
    };

    f({
        // <-- Cursor is here shows "a"
     });
```

hope this helps.

**Comment by NN---** [comment]
@mhegazy The question is not with intellisense with specifying the types but when you don't specify it.
