### ISSUE TITLE
Type inferring doesn't work in destructuring.

### ISSUE THREAD

**Issue by zheeeng** [Microsoft/TypeScript#18308]
**TypeScript Version:**  2.4.2
Tested in VS Code. The online playground seems broken.

**Code**

```ts
interface Person {
  name?: string,
  age?: number
}

const defaultPerson: Person = {
  name: 'Bob',
  age: 19,
}

const girl: Person = {
  name: 'Alice',
  age: 23,
}

// [ts] Initializer provides no value for this binding element and the binding element has no default value.
const { name, age } = {...defaultPerson, ...girl}

```

**Expected behavior:**

The const 'name' and 'age' are inferred as 'sting' and 'number'

**Actual behavior:**
TS report: `[ts] Initializer provides no value for this binding element and the binding element has no default value.`

The workarounds: 
```ts
// A
const p = {...defaultPerson, ...girl}
const { name, age } = p

// B
const { name, age } = {...defaultPerson, ...girl} as Person

// C
const { name = 'Tom', age = 19 } = girl
```

Although we have workarounds, I can't understand why we can't get types directly in destructuring. Compare to solution A, TS definitely can infer the types of 'p'.

**Comment by sandersn** [comment]
Fix is up at #18925

**Comment by brunolemos** [comment]
I still have this error when I add `|| {}`:
`const { name, age } = params || {}`

**Comment by sandersn** [comment]
@brunolemos can you open a separate issue or search for another existing issue? This bug has to do with a spread that is contextually typed by a binding pattern. Your example doesn't have a spread in it.

**Comment by brunolemos** [comment]
@sandersn if that works it's fine then
