### ISSUE TITLE
Is it possible to import everything from the module ?

### ISSUE THREAD

**Issue by NN---** [Microsoft/TypeScript#1831]
I can do 'import Alias = Module' but I don't find a syntax for simple 'import Module' to import everything.
Do I miss something ?

**Comment by danquirk** [comment]
```import alias = module``` creates an alias to ```module```. Anything that was accessible from ```module``` should now be accessible via ```alias```.

```import foo = require('myModule')``` works similarly, where everything exported in ```myModule``` is now accessible via ```foo```. 

What exactly are you trying to do?

**Comment by NN---** [comment]
I want something like import * from Module.

**Comment by danquirk** [comment]
We'll be fully aligning with ES6 module syntax in the near future.

**Comment by NN---** [comment]
Great, waiting for it :)
