### ISSUE TITLE
Typescript adds a space if the ts file ends with a comment

### ISSUE THREAD

**Issue by ubershmekel** [Microsoft/TypeScript#18314]
**TypeScript Version:**  2.5.2

**Code:** https://github.com/ubershmekel/typescript-extra-space

**ts file**
```ts
// a comment with no newline after it
```

**Expected behavior (js file):**
```js
// a comment with no newline after it
```

**Actual behavior (js file):**
```ts
// a comment with no newline after it[space-character]
[newline-character]
```

I don't mind the newline as much as I mind the space. I have a no-trailing-spaces eslint rule on the js that tripped up because of this. The solution is to add a newline so the file doesn't end with a comment.

I realize this is potentially the most minor nit in the history of Typescript, but this issue seemed potentially entertaining so I pursued creating an issue and reproduction anyway.

**Comment by RyanCavanaugh** [comment]
@mhegazy W/F?

**Comment by mhegazy** [comment]
i do not know what is going on. we would accept a PR to address it if the change is simple.

**Comment by ubershmekel** [comment]
I was able to fix it. Looking at the changes to the baseline it seems like an improvement in 42 out of 44 changed baselines. The two odd cases were because of typescript's white-space elimination policy. E.g.

`/*existing trivia*/ ;` in the original ts and js. Will now be rendered as:
`/*existing trivia*/;`

`/** jsdoc comment */ /*** another jsDocComment*/` in the original ts and js. Will be rendered as:
`/** jsdoc comment *//*** another jsDocComment*/`

`/*c4*/ function () { },` was vs now:
`/*c4*/function () { },`

Is that acceptable or would Typescript prefer to preserve a space after a comment?
