### ISSUE TITLE
VsTsc runs when there are no ConfigFiles or TypeScriptCompile items

### ISSUE THREAD

**Issue by dfederm** [Microsoft/TypeScript#18312]
**TypeScript Version:**  N/A (build targets from VS 15.3)

**Code**
Standard ASP.NET Core project:
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0" />
  </ItemGroup>
</Project>
```

**Expected behavior:**
PreComputeCompileTypeScript, or at least VsTsc doesn't run.

**Actual behavior:**
VsTsc runs

**More context:**
In Microsoft.Typescript.targets, there is:
```xml
  <Target Name="PreComputeCompileTypeScript"
          Condition="'@(ConfigFiles)' == ''">
    <VsTsc
      ToolPath="$(TscToolPath)"
      ToolExe="$(TscToolExe)"
      Configurations="$(TypeScriptBuildConfigurations)"
      PreferredUILang="$(PreferredUILang)"
      FullPathsToFiles="@(TypeScriptCompile)"
      YieldDuringToolExecution="$(TscYieldDuringToolExecution)"
      OutFile="$(TypeScriptOutFile)"
      OutDir="$(TypeScriptOutDir)"
      ProjectDir="$(TypeScriptProjectDir)"
      ToolsVersion="$(TypeScriptToolsVersion)"
      RootDir="$(TypeScriptRootDir)"
      TypeScriptCompileBlocked="$(TypeScriptCompileBlocked)"
      JsxPreserve="$(JsxPreserve)"
      GenerateDeclarationFiles="$(GenerateDeclarationFiles)"
      GenerateSourceMaps="$(GenerateSourceMaps)"
      ComputeOutputOnly="true">

      <Output TaskParameter="GeneratedJavascript" ItemName="emittedFiles" />
    </VsTsc>
    <ItemGroup>
      <GeneratedJavascript Include="@(emittedFiles)" KeepDuplicates="false" />
    </ItemGroup>
  </Target>
```

There's no reason to run that target when there is no tsconfig and no ts files at all. Perhaps that condition on the Target should be `'@(ConfigFiles)' == '' AND '@(TypeScriptCompile)' != ''`.

This is a problem as I have a standalone isolated build environment and `TscToolPath` is set to `$(MSBuildProgramFiles32)\Microsoft SDKs\TypeScript` by default, which does not exist on our build machines. The solution for people who do want TS compilation is to include another package which includes tsc and some props which sets `TscToolPath` explicitly, but it doesn't make sense for people who don't want TS compilation to pull in that package as well just so that `TscToolPath` will point to something that exists.

Also note that not including Microsoft.Typescript.targets at all isn't really an option as Microsoft.NET.Sdk.Web.ProjectSystem.targets (imported by Microsoft.NET.Sdk.Web.targets) imports it. There is a condition on the import which is the TypeScript targets existing and `EnableTypeScriptNuGetTarget` not being '`true'` (which I guess I can use as a workaround).

**Comment by minestarks** [comment]
@dfederm Sorry for the delay. Are you still having the issue?

I'm not sure how you got into a setup where the `Microsoft.TypeScript.targets` file exists but the TypeScript SDK isn't installed under `$(MSBuildProgramFiles32)\Microsoft SDKs\TypeScript`. As far as I know, VS (or the standalone SDK installer) should install both, or neither. So the targets referencing the SDK installation isn't a problem, per se, as any scenario where one exists without the other would be a setup bug.

I believe there might have been a bug in earlier versions of the the Visual Studio Build Tools SKU where we didn't include the latter, so perhaps you were running into that. If you're still seeing this, could you let me know which version of Visual Studio, MSBuild and/or TypeScript SDK you have installed?

**Comment by minestarks** [comment]
I should mention that the `'@(TypeScriptCompile)' != ''` has been added, so you probably won't be seeing this if you're using later versions of the targets. I'm mainly curious about what kind of environment led to this issue.

**Comment by dfederm** [comment]
@minestarks Thanks for the response. I must have been using an older version at the time as I've also noticed that the condition has been added so this is no longer a problem.

For context, the scenario is one of an isolated build environment where VS is not installed (Microsoft's own CloudBuild), so everything is pulled in via nugets. So `$(MSBuildProgramFiles32)\Microsoft SDKs\TypeScript` doesn't exist (nothing is really install on these machines) and the relevant nuget redirecting the TS tools path and other relevant properties were not pulled in since they weren't needed (no TS compilation needed for this AspNetCore app). Ideally, the TS SDK (or any SDK, particularly MS-developed ones) would rely on machine installation to better support build labs, but that's a discussion for another time :).

Thanks!

**Comment by minestarks** [comment]
Thanks for the context! I'm still a bit puzzled about how `Microsoft.Typescript.targets` got on the machine in the first place without a VS or TS SDK installation (like, how did it get installed under the path [this `<Import>`](https://github.com/aspnet/websdk/blob/bbb651e4ce9ca7eb6308babdd698a2c00f4cc208/src/ProjectSystem/Microsoft.NET.Sdk.Web.ProjectSystem.Targets/netstandard1.0/Microsoft.NET.Sdk.Web.ProjectSystem.props#L48) is looking at), but if you're using MS-provisioned machines you probably didn't have control over that. I'm chalking it up to an earlier VS install bug.

I'm closing this issue as the root bug has been fixed.
