### ISSUE TITLE
uncaught TypeError: Cannot read property 'kind' of undefined in isFunctionExpression

### ISSUE THREAD

**Issue by TysonAndre** [Microsoft/TypeScript#18323]
**TypeScript Version:**  2.5.2 / nightly (2.6.0-dev.20170907)

This was noticed when typescript was run on a folder which included minified code

**Code**

```js
var tmp = function() {
    "use strict";

    var d;  // The TypeError in typescript seems to be related to `new d()` being called in the same group of assignments used to declare d(), e.g. which can be seen in minified code
    d = function f() {
    }, l["default"].registerBidAdapter(new d());
}
```

**Expected behavior:**
Typescript emits warnings, and doesn't crash

**Actual behavior:**
Typescript has an uncaught typeError

```
TypeError: Cannot read property 'kind' of undefined       
    at Object.isFunctionExpression (/usr/local/node/lib/node_modules/typescript/lib/tsc.js:8584:20)                  
    at isJavaScriptConstructor (/usr/local/node/lib/node_modules/typescript/lib/tsc.js:31144:58)                     
    at getJavaScriptClassType (/usr/local/node/lib/node_modules/typescript/lib/tsc.js:31154:17)
    at checkCallExpression (/usr/local/node/lib/node_modules/typescript/lib/tsc.js:31192:46)
    at checkExpressionWorker (/usr/local/node/lib/node_modules/typescript/lib/tsc.js:32467:28)
    at checkExpression (/usr/local/node/lib/node_modules/typescript/lib/tsc.js:32407:42)
    at /usr/local/node/lib/node_modules/typescript/lib/tsc.js:30289:21
    at Object.forEach (/usr/local/node/lib/node_modules/typescript/lib/tsc.js:275:30)
    at resolveUntypedCall (/usr/local/node/lib/node_modules/typescript/lib/tsc.js:30288:20)
    at resolveErrorCall (/usr/local/node/lib/node_modules/typescript/lib/tsc.js:30295:13)
    at resolveCallExpression (/usr/local/node/lib/node_modules/typescript/lib/tsc.js:30920:24)
...
```

package.json contents:

```json
{
    "compilerOptions": {
        "outDir": "./built",
        "allowJs": true,
        "checkJs": true,
        "target": "es6",
        "moduleResolution": "node"
    },  
    "include": [
        "prebid-clean.js"
    ]
}  
```

**Comment by Kovensky** [comment]
This crash also happens in stylus (`stylus/lib/cache/index.js`).

```js
var getCache = module.exports = function(name, options){
  if ('function' == typeof name) return new name(options);

  var cache;
  switch (name){
    // case 'fs':
    //   cache = require('./fs')
    //   break;
    case 'memory':
      cache = require('./memory');
      break;
    default:
      cache = require('./null');
  }
  return new cache(options);
}
```

The crash happens when trying to look at the initializer of `cache` in `var cache;`.

**Comment by ksnyde** [comment]
I am using TS `2.7.x` (same problem existed in `2.6.1`) but I am still getting this error. The call stack is a little bit different in my case. Maybe this is another variant of the same issue? My error doesn't show up when compiling but at runtime when I am running **mocha** tests which run with `ts-node`.

Error:

    [Info]​​​​​ Sun, 03 Dec 2017 21:15:47 GMT wallaby:project Instrumenting src/vote-smart/shared.js, via process pool: false
    ​​​​​[Info]​​​​​ Sun, 03 Dec 2017 21:15:47 GMT wallaby:project TypeError: Cannot read property 'kind' of undefined
    ​​​​​[Info]​​​​​   at transformModuleBody (/Users/ken/Documents/mine/politics/mypolitics-services/node_modules/typescript/lib/typescript.js:54978:22)
    ​​​​​[Info]​​​​​   at visitModuleDeclaration (/Users/ken/Documents/mine/politics/mypolitics-services/node_modules/typescript/lib/typescript.js:54950:33)
    ​​​​​[Info]​​​​​   at visitTypeScript (/Users/ken/Documents/mine/politics/mypolitics-services/node_modules/typescript/lib/typescript.js:53077:28)
    ​​​​​[Info]​​​​​   at visitorWorker (/Users/ken/Documents/mine/politics/mypolitics-services/node_modules/typescript/lib/typescript.js:52798:24)
    ​​​​​[Info]​​​​​   at sourceElementVisitorWorker (/Users/ken/Documents/mine/politics/mypolitics-services/node_modules/typescript/lib/typescript.js:52827:28)
    ​​​​​[Info]​​​​​   at saveStateAndInvoke (/Users/ken/Documents/mine/politics/mypolitics-services/node_modules/typescript/lib/typescript.js:52742:27)
    ​​​​​[Info]​​​​​   at sourceElementVisitor (/Users/ken/Documents/mine/politics/mypolitics-services/node_modules/typescript/lib/typescript.js:52812:20)
    ​​​​​[Info]​​​​​   at visitNodes (/Users/ken/Documents/mine/politics/mypolitics-services/node_modules/typescript/lib/typescript.js:51104:48)
    ​​​​​[Info]​​​​​   at Object.visitLexicalEnvironment (/Users/ken/Documents/mine/politics/mypolitics-services/node_modules/typescript/lib/typescript.js:51137:22)
    ​​​​​[Info]​​​​​   at visitSourceFile (/Users/ken/Documents/mine/politics/mypolitics-services/node_modules/typescript/lib/typescript.js:53089:53)
    ​​​​​[Info]​​​​​   at saveStateAndInvoke (/Users/ken/Documents/mine/politics/mypolitics-services/node_modules/typescript/lib/typescript.js:52742:27)
    ​​​​​[Info]​​​​​   at transformSourceFile (/Users/ken/Documents/mine/politics/mypolitics-services/node_modules/typescript/lib/typescript.js:52726:27)
    ​​​​​[Info]​​​​​   at /Users/ken/Documents/mine/politics/mypolitics-services/node_modules/typescript/lib/typescript.js:2601:86
    ​​​​​[Info]​​​​​   at reduceLeft (/Users/ken/Documents/mine/politics/mypolitics-services/node_modules/typescript/lib/typescript.js:2274:30)
    ​​​​​[Info]​​​​​   at /Users/ken/Documents/mine/politics/mypolitics-services/node_modules/typescript/lib/typescript.js:2601:42
    ​​​​​[Info]​​​​​   at transformRoot (/Users/ken/Documents/mine/politics/mypolitics-services/node_modules/typescript/lib/typescript.js:65718:82)
    ​​​​​[Info]​​​​​   at Object.map (/Users/ken/Documents/mine/politics/mypolitics-services/node_modules/typescript/lib/typescript.js:1725:29)
    ​​​​​[Info]​​​​​   at Object.transformNodes (/Users/ken/Documents/mine/politics/mypolitics-services/node_modules/typescript/lib/typescript.js:65706:30)
    ​​​​​[Info]​​​​​   at Object.emitFiles (/Users/ken/Documents/mine/politics/mypolitics-services/node_modules/typescript/lib/typescript.js:68440:28)
    ​​​​​[Info]​​​​​   at emitWorker (/Users/ken/Documents/mine/politics/mypolitics-services/node_modules/typescript/lib/typescript.js:72517:33)
    ​​​​​[Info]​​​​​   at /Users/ken/Documents/mine/politics/mypolitics-services/node_modules/typescript/lib/typescript.js:72479:66
    ​​​​​[Info]​​​​​   at runWithCancellationToken (/Users/ken/Documents/mine/politics/mypolitics-services/node_modules/typescript/lib/typescript.js:72571:24)
    ​​​​​[Info]​​​​​   at Object.emit (/Users/ken/Documents/mine/politics/mypolitics-services/node_modules/typescript/lib/typescript.js:72479:20)
    ​​​​​[Info]​​​​​   at Object.getFileEmitOutput (/Users/ken/Documents/mine/politics/mypolitics-services/node_modules/typescript/lib/typescript.js:71137:34)
    ​​​​​[Info]​​​​​   at Object.getEmitOutput (/Users/ken/Documents/mine/politics/mypolitics-services/node_modules/typescript/lib/typescript.js:96004:23)
    ​​​​​[Info]​​​​​   at /Users/ken/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.68/wallaby/server.js:19:24748
    ​​​​​[Info]​​​​​   at baseFor (/Users/ken/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.68/wallaby/node_modules/lodash/index.js:1971:13)
    ​​​​​[Info]​​​​​   at baseForOwn (/Users/ken/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.68/wallaby/node_modules/lodash/index.js:2025:14)
    ​​​​​[Info]​​​​​   at baseEach (/Users/ken/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.68/wallaby/node_modules/lodash/index.js:1814:16)
    ​​​​​[Info]​​​​​   at Function.forEach (/Users/ken/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.68/wallaby/node_modules/lodash/index.js:5701:11)
    ​​​​​[Info]​​​​​   at Object.n [as postprocessor] (/Users/ken/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.68/wallaby/server.js:19:24554)
    ​​​​​[Info]​​​​​   at /Users/ken/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.68/wallaby/server.js:17:16568
    ​​​​​[Info]​​​​​   at Timeout._onTimeout (/Users/ken/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.68/wallaby/server.js:17:16006)
    ​​​​​[Info]​​​​​   at ontimeout (timers.js:475:11)
    ​​​​​[Info]​​​​​   at tryOnTimeout (timers.js:310:5)
    ​​​​​[Info]​​​​​   at Timer.listOnTimeout (timers.js:270:5)
    ​​​​​[Info]​​​​​ From previous event:
    ​​​​​[Info]​​​​​   at Timeout._onTimeout (/Users/ken/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.68/wallaby/server.js:17:16006)
    ​​​​​[Info]​​​​​   at ontimeout (timers.js:475:11)
    ​​​​​[Info]​​​​​   at tryOnTimeout (timers.js:310:5)
    ​​​​​[Info]​​​​​   at Timer.listOnTimeout (timers.js:270:5)

**Comment by ksnyde** [comment]
for what it's worth it appears `ts-node` is still using TS 2.6.1 but still expected this to work.

**Comment by mhegazy** [comment]
@ksnyde please file a new issue, and provide us with the source that caused the crash.
