### ISSUE TITLE
Extract function doesn't respect indentation settings

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#18328]
_From @dbaeumer on August 30, 2017 8:35_

Testing: #33282 

```ts
function foo() {
	console.log('Hello World');
}
```
- observe: console.log is indented using tabs
- select `console.log('Hello World');`
- run extract function
- you get
```ts
function foo() {
    newFunction();
}
function newFunction() {
    console.log('Hello World');
}
```
Observe: spaces are used as indentation.

_Copied from original issue: Microsoft/vscode#33492_

**Comment by mjbvz** [comment]
_From @dbaeumer on August 30, 2017 8:36_

@mjbvz unclear if this is us or TS

**Comment by mjbvz** [comment]
After investigating this, it does seem like this should be fixed on the TS side. We send the correct formatting configuration

**Comment by mhegazy** [comment]
For repro purposes, make sure `editor.insertSpaces` is false in the vscode settings; this should set the server format config `convertTabsToSpaces` to false. 

looks like we are not using the correct format settings when we get the refactor edits

**Comment by DanielRosenwasser** [comment]
@bterlson also ran into this with 2 spaces vs 4 spaces.

**Comment by andy-ms** [comment]
When I look at `tsserver.log` it doesn't look like any formatting options are being sent along with the `getEditsForRefactor` request? (Or anywhere else.) I've manually specified many formatting settings in my user settings, so I would expect to be seeing something. No formatting settings I set in vscode have any effect on refactorings, although running `Format Document` manually does work.

It looks like if I run `Format Document`, *then* we will receive a "configure" command setting formatting options, but I don't see any options being passed to a "getEditsForRefactor" event even after that.

Aside: I also noticed that in `services/types.ts`, all properties in `EditorSettings` and `FormatCodeSettings` are marked optional, but it seems that in our formatter we're always assuming these to be set -- if I manually use empty formatting settings in a fourslash test, I get a lot of bugs due to trying to use `undefined` as an `indentSize` or `newLineCharacter`. Should we just mark these properties non-optional?

**Comment by mhegazy** [comment]
@mjbvz looks like we are not getting the format options before the refactor command. looks like we are getting these once per session before the first format command.

**Comment by mjbvz** [comment]
I've fixed on the vscode size with https://github.com/Microsoft/vscode/commit/0e4e0d8f8108ff346000fb68f5215d10920d5768

However with the TS 2.5.3-20170919-insiders, I don't see the tab size setting being respected. Here's the source doc:

```ts
function z () {
  console.log(1)
}
```

And the server trace when trying to extract `console.log(1)`:

```
[Trace  - 4:04:37 PM] Sending request: configure (10). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/Users/matb/projects/san/y.ts",
    "formatOptions": {
        "tabSize": 2,
        "indentSize": 2,
        "convertTabsToSpaces": true,
        "newLineCharacter": "\n",
        "insertSpaceAfterCommaDelimiter": true,
        "insertSpaceAfterConstructor": false,
        "insertSpaceAfterSemicolonInForStatements": true,
        "insertSpaceBeforeAndAfterBinaryOperators": true,
        "insertSpaceAfterKeywordsInControlFlowStatements": true,
        "insertSpaceAfterFunctionKeywordForAnonymousFunctions": true,
        "insertSpaceBeforeFunctionParenthesis": false,
        "insertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis": false,
        "insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets": false,
        "insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces": true,
        "insertSpaceAfterOpeningAndBeforeClosingTemplateStringBraces": false,
        "insertSpaceAfterOpeningAndBeforeClosingJsxExpressionBraces": false,
        "insertSpaceAfterTypeAssertion": false,
        "placeOpenBraceOnNewLineForFunctions": false,
        "placeOpenBraceOnNewLineForControlBlocks": false
    }
}
[Trace  - 4:04:37 PM] Response received: configure (10). Request took 1 ms. Success: true 
[Trace  - 4:04:37 PM] Sending request: getEditsForRefactor (11). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/Users/matb/projects/san/y.ts",
    "startLine": 2,
    "startOffset": 1,
    "endLine": 2,
    "endOffset": 17,
    "refactor": "Extract Method",
    "action": "scope_0"
}
[Trace  - 4:04:37 PM] Response received: getEditsForRefactor (11). Request took 29 ms. Success: true 
Result: {
    "renameLocation": {
        "line": 2,
        "offset": 5
    },
    "renameFilename": "/Users/matb/projects/san/y.ts",
    "edits": [
        {
            "fileName": "/Users/matb/projects/san/y.ts",
            "textChanges": [
                {
                    "start": {
                        "line": 2,
                        "offset": 1
                    },
                    "end": {
                        "line": 3,
                        "offset": 1
                    },
                    "newText": "    newFunction();\n"
                },
                {
                    "start": {
                        "line": 3,
                        "offset": 1
                    },
                    "end": {
                        "line": 3,
                        "offset": 1
                    },
                    "newText": "\n    function newFunction() {\n        console.log(1);\n    }\n"
                }
            ]
        }
    ]
}
```
