### ISSUE TITLE
Cast to index signature (question)

### ISSUE THREAD

**Issue by NN---** [Microsoft/TypeScript#1832]
Each ES object is a dictionary of string keys.
Therefore it is allowed to write either a.b or a["b"] in ES.

TS doesn't allow this unless you specify index signature.
Also you cannot cast to this type without casting to 'any' .

```typescript
var q: { a: number; } = { a: 1 };

// This is not allowed since 'q' type is not assignable to this type.
(<{[x:string]:any}>q)["a"] = 2;

// This is allowed since any can be casted to anything.
(<{[x:string]:any}><any>q)["a"] = 2;
```

'Object' type from lib.d.ts doesn't have index signature either, so you cannot use it as well.
Is there anything better than casting to 'any' ?

**Comment by stephanedr** [comment]
Don't need any cast.
From playground:
```
var q: { a: number; } = { a: 1 };
q["a"] = 2;     // OK
q["a"] = "foo"; // Error "string not assignable to number"
var n = q["a"]; // n is number
```

**Comment by NN---** [comment]
This is okay, but think about more generic usage like:

```typescript
var q = {};

function f(index: string) {
 (<{[x:string]:any]}>q)[index]) = 1; // This won't work
}
```

**Comment by danquirk** [comment]
The generic usage is what was already written. You have syntax errors in your latest example.

```ts
var q = {};

function f(index: string) {
	q[index] = 1; // works
 	(<{[x:string]:any}>q)[index] = 1; // also works, but a meaningless extra cast
}
```

**Comment by NN---** [comment]
I see why it works.
I have disabled 'Allow implicit 'any' types'.

**Comment by NN---** [comment]
The question is why it does require explicit cast to any in order to make cast for type with indexer ?

**Comment by NoelAbrahams** [comment]
Hi, I think this is actually a bug and the issue should be re-opened.

Here is a more straightforward repro:

```typeScript
interface Indexer {
    [x: string]: number;
}

interface Foo {
    id: number;
}


var x: Foo

/*Error: Neither type 'Foo' nor type 'Indexer' is assignable to the other.
 Index signature is missing in type 'Foo'.*/
var y = <Indexer>x;

```

The object `Foo` is clearly indexable by `string` to produce a number, hence the type assertion should be permitted.

**Comment by RyanCavanaugh** [comment]
> The object Foo is clearly indexable by string to produce a number

This isn't how index signatures work. Consider something like this:

```ts
var z: Foo = { id: 42, name: 'bob' };
var y = <Indexer>x; // Should be allowed (?)
var j = y['name']; // j: number, j === 'bob' :(
```
