### ISSUE TITLE
TSServer --globalPlugins not working for inferred projects

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#18322]
**TypeScript Version:**  2.5.2

**Steps to reproduce**
In a folder with no `tsconfig` or `jsconfig` and a single ts file

Start the tsserver with `--globalPlugins ts-css-plugin --pluginProbeLocations  /Users/matb/projects/css-template-plugin`

**Bug**
I don't see the plugin being loaded unless I create an empty `tsconfig.json` file

**Comment by RyanCavanaugh** [comment]
@mjbvz I have a tentative fix up at https://github.com/RyanCavanaugh/TypeScript/tree/fix18322 but I'm not sure how to test it. Can you give it a spin or provide some user-side instructions?

**Comment by mjbvz** [comment]
Try installing this vscode extension: https://github.com/mjbvz/vscode-styled-components-extension by manually installing the vsix from the repo

Make sure you are using VSCode's version of typescript. We currently disable global plugins if you use the workspace versions

**Comment by mjbvz** [comment]
@RyanCavanaugh I don't see this working properly in VS Code 1.18 with TS 2.6.1. 

To test:

1. In VS Code 1.18, install the vsix from [this repo](https://github.com/mjbvz/vscode-styled-components-extension)
2. Open a empty folder in VS Code
3. Create a single ts file with the contents:

```
styled`

`
```

4. Try requesting completions inside of the template string


I do no see any css completions. However after creating a `tsconfig.json`—even without setting the `plugins`—I start seeing the expected css completions

**Comment by anstarovoyt** [comment]
starting from WS2017.3 we use ts-plugin for providing the Angular LS support in WebStorm and the issue also affects us. Rel. https://youtrack.jetbrains.com/issue/WEB-30045
