### ISSUE TITLE
MessageEvent ports should be a MessagePort array

### ISSUE THREAD

**Issue by mkohlmyr** [Microsoft/TypeScript#18334]
In the MessageEvent interface of [lib.webworker.ts](https://github.com/Microsoft/TypeScript/blob/master/lib/lib.webworker.d.ts), we define ports as being of the type any. To my understanding it should be a (nullable due to browser implementations) MessagePort array, e.g.
```typescript
interface MessageEvent extends Event {
    readonly data: any;
    readonly origin: string;
    readonly ports: MessagePort[] | null;
    readonly source: any;
    initMessageEvent(typeArg: string, canBubbleArg: boolean, cancelableArg: boolean, dataArg: any, originArg: string, lastEventIdArg: string, sourceArg: any): void;
}
```
https://github.com/Microsoft/TypeScript/blob/02cfb81ac0c9b870d31be14b16b0a08ea24ed32a/lib/lib.webworker.d.ts#L727

Is there a reason for the way it is currently defined? Happy to throw a PR otherwise.

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by a-tarasyuk** [comment]
@mhegazy I think this issue can be closed [lib.d.ts#L13289](https://github.com/Microsoft/TypeScript/blob/master/lib/lib.d.ts#L13289)

[dom-messageevent-ports](https://html.spec.whatwg.org/multipage/comms.html#dom-messageevent-ports)

**Comment by mhegazy** [comment]
thanks @a-tarasyuk
