### ISSUE TITLE
[website] Floating header covers headings when loading a page with an anchor link

### ISSUE THREAD

**Issue by MichaelZalla** [microsoft/TypeScript#18332]
**Steps to reproduce**

1. Open your web browser.
2. Enter a URL for a [typescriptlang.org](https://www.typescriptlang.org) page that includes a deep-link to a specific page section (e.g., a particular item in a release note):

- [https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-1.html#mapped-types](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-1.html#mapped-types)

**Expected behavior:**

The section's text heading (e.g., "Mapped Types") will be visible at the top of the viewport.

**Actual behavior:**

The `fixed`-position navbar (`.navbar-fixed-top`) covers the heading. This can be disorienting.

Reproduced on macOS with the following clients:
- Chrome Canary v62.0
- Safari v10.1.1
- Firefox 55.0.3

**Comment by orta** [comment]
This is now fixed 👍
