### ISSUE TITLE
Invalid function assignment is not detected

### ISSUE THREAD

**Issue by VictorNicollet** [Microsoft/TypeScript#18337]
**TypeScript Version:**  2.5.0 

**Code**

```ts
const a: (d: string) => number = (d) => d.length;
const b: (d?: string) => number = a;
b();
```

**Expected behavior:**
When compiled with `--strict`, the assignment of `b` should cause a type error along the lines of:  

> `string | undefined` is not assignable to type `string`.

**Actual behavior:**
The code compiles with `--strict`, then throws an exception at runtime on the expression `d.length`.

**Comment by gcnew** [comment]
Unfortunately that's expected behaviour: [FAQ - Why are function parameters bivariant](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-function-parameters-bivariant).

**Comment by VictorNicollet** [comment]
Thank you. This is disappointing, but I understand the reasons.
