### ISSUE TITLE
Extract method duplicates comment

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#18347]
**TypeScript Version:**  nightly (2.6.0-dev.20170908)

As shown in `extract-method-uniqueName.ts` (https://github.com/Microsoft/TypeScript/pull/18050/files#diff-7d189af3a2a25addbe9503fe2e7c9b8a)

**Code**

```ts
// comment
1 + 1;
```

Extract `1 + 1` to a function.

**Expected behavior:**

```ts
// comment
newFunction();

function newFunction() {
    1 + 1;
}
```

**Actual behavior:**

```ts
// comment
newFunction();

function newFunction() {
    // comment
    1 + 1;
}
```

**Comment by amcasey** [comment]
This is part of https://github.com/Microsoft/TypeScript/issues/18626.
