### ISSUE TITLE
npm install types-registry: Command failed

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#18344]
**TypeScript Version:**  2.5.2

From https://github.com/Microsoft/vscode/issues/24961#issuecomment-328196730

viktor-wolf reported that even after setting `typescript.npm`, they were seeing messages about the typings installer failing. Here is the log [ti-6028.txt](https://github.com/Microsoft/vscode/files/1288936/ti-6028.txt). The failure is:

```
Error updating types-registry package: Command failed: "/home/viktor/.nvm/versions/node/v8.4.0/bin/npm" install --ignore-scripts types-registry
Types registry file '/home/viktor/.cache/typescript/2.5/node_modules/types-registry/index.json' does not exist
Sending response: {"kind":"event::initializationFailed","message":"Command failed: \"/home/viktor/.nvm/versions/node/v8.4.0/bin/npm\" install --ignore-scripts types-registry"}
Response has been sent.
```

@viktor-wolf can you please try running `"/home/viktor/.nvm/versions/node/v8.4.0/bin/npm" install --ignore-scripts types-registry` on the command line and sharing the output

**Comment by viktor-wolf** [comment]
I forgot to mention in my original comment I had already successfully tried running that command, but it didn't fix the issue. The current output from both the integrated and OS terminal is:
`+ types-registry@0.1.297`
`updated 1 package in 1.691s`

**Comment by chrmarti** [comment]
It would help if the tsserver included more details of the error, like exit code and stdout/-err of npm.

**Comment by mhegazy** [comment]
@andy-ms is there any additional logging we can add here?

**Comment by andy-ms** [comment]
Added some extra logging in #19110.

**Comment by mhegazy** [comment]
closing for now. please reopen as we get more info on the new release.
