### ISSUE TITLE
TypeArray `[index: number]: number` missing `| undefined`

### ISSUE THREAD

**Issue by riggs** [Microsoft/TypeScript#18345]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

The various TypeArray definitions in lib.d.ts define index access as `[index: number]: number`, but should be `[index: number]: number | undefined` because `(new Uint8Array(1))[1]` is `undefined`.

**Comment by mhegazy** [comment]
Please see https://github.com/Microsoft/TypeScript/issues/13778

**Comment by riggs** [comment]
Thanks. I'll subscribe to that.
