### ISSUE TITLE
Merged type not inferred as a mapped type argument

### ISSUE THREAD

**Issue by dwickern** [Microsoft/TypeScript#18354]
**TypeScript Version:**  2.5.x, 2.6.0-dev.20170908

When passed as an argument, `T & U` evaluates to `T`, and the type `U` is discarded.
```ts
declare function f<T, Key extends keyof T>(obj: {[K in keyof T]: T[K]}, key: Key): T[Key];

declare const obj: { a: string } & { b: string };
f(obj, 'a');
f(obj, 'b'); // error
```

[Playground link](https://www.typescriptlang.org/play/index.html#src=declare%20function%20f%3CT%2C%20Key%20extends%20keyof%20T%20%3E(obj%3A%20%7B%5BK%20in%20keyof%20T%5D%3A%20T%5BK%5D%7D%2C%20key%3A%20Key)%3A%20T%5BKey%5D%3B%0D%0A%0D%0Adeclare%20const%20obj%3A%20%7B%20a%3A%20string%20%7D%20%26%20%7B%20b%3A%20string%20%7D%3B%0D%0Af(obj%2C%20'a')%3B%0D%0Af(obj%2C%20'b')%3B%0D%0A%0D%0Atype%20Fix%3CT%3E%20%3D%20%7B%5BP%20in%20keyof%20T%5D%3A%20T%5BP%5D%7D%0D%0A%0D%0Adeclare%20const%20obj2%3A%20Fix%3C%7B%20a%3A%20string%20%7D%20%26%20%7B%20b%3A%20string%20%7D%3E%3B%0D%0Af(obj2%2C%20'a')%3B%0D%0Af(obj2%2C%20'b')%3B%0D%0A)

---
**Workarounds**

Specify the type arguments explicitly:
```ts
f<typeof obj, keyof typeof obj>(obj, 'b');
```

An identity type mapping can be used to create an intermediate type
```ts
type Fix<T> = {[P in keyof T]: T[P]}

declare const obj: Fix<{ a: string } & { b: string }>;
f(obj, 'a');
f(obj, 'b');

```

Related issue typed-ember/ember-typings#32

**Comment by ahejlsberg** [comment]
This is an issue with how we break down intersection types in type inference. Here's a simpler repro:

```ts
declare function f<T>(x: { prop: T }): T;

declare const a: { prop: string } & { prop: number };
declare const b: { prop: number & string };

f(a);  // string
f(b);  // string & number
```

We obviously shouldn't deliver different results above. Both should be `string & number`.

**Comment by dwickern** [comment]
Thanks for the quick fix. I can confirm this is working in `typescript@2.6.0-dev.20170913`
