### ISSUE TITLE
Use generic for Object.seal(), freeze() and preventExtensions()

### ISSUE THREAD

**Issue by stephanedr** [Microsoft/TypeScript#1835]
To me, seal(), freeze() and preventExtensions() should be declared like:
`    seal<T>(o: T): T;`

Adding it to ObjectConstructor does not help, the 'any' version is taken first.
The only solution I've found is to patch lib.d.ts...
Is there a better way?
Or could you update lib.d.ts?

**Comment by mhegazy** [comment]
I think the main reason is we had these in lib.d.ts before generics were introduced. I think it would be safe to change it, if it breaks exiting code, it most probably did not work in the first place.

A PR would be appreciated. the change should be in src\lib\code.d.ts
