### ISSUE TITLE
DOM scroll event is UIEvent, but should be Event

### ISSUE THREAD

**Issue by bradleyayers** [Microsoft/TypeScript#18355]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

**Code**

```ts
document.addEventListener("scroll", e => {
    e.view;
});
```

**Expected behavior:**

This should not type check, as `view` does not exist on [Event](https://developer.mozilla.org/en-US/docs/Web/API/Event).  I ran into this because in Chrome (I tested on Chrome 60) `event.view` is undefined for `scroll` events. There's a [Chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=503280#c1) from 2015 about emitting a UIEvent and is marked as WontFix, saying:

> We intend to update the UIEvent spec to be consistent with this since we don't believe that anyone creates a UIEvent for 'scroll'.

The [spec is updated and shows](https://drafts.csswg.org/cssom-view/#event-summary) that `scroll` events should just be an `Event` rather than a `UIEvent`.

**Actual behavior:**

`e` is considered a UIEvent, which *does* have a `view` property, and so the code type checks successfully.

**Comment by cgatian** [comment]
I believe this should be closed
