### ISSUE TITLE
Adding import declarations using the Compiler API

### ISSUE THREAD

**Issue by matthewmueller** [Microsoft/TypeScript#18369]
Right now it doesn't seem possible to add an `ImportDeclaration` programmatically via the Compiler API without updating the entire AST. My use-case is to be able to create https://github.com/zeit/styled-jsx with the TS Compiler over babel. When it detects a `<style>` JSXElement, it will append `import JSXStyle from 'styled-jsx` to the top of the code. I'd like to be able to do this too.

I've looked at how Typescript adds the `tslib` and it seems like it uses an internal `imports` key on the `SourceFile` node. Would it be possible to give us access to that?

**TypeScript Version:**  Version 2.4.1

**Code**

Sorry this isn't entirely self-contained, but the original is about 100 LOC. This should give you the gist, and it's mostly from the `tslib` code in the compiler.

```ts
const node = (node as ts.Node) as ts.SourceFile
const externalHelpersModuleReference = ts.createLiteral('styled')
const importDecl = ts.createImportDeclaration(
  /*decorators*/ undefined,
  /*modifiers*/ undefined,
  /*importClause*/ undefined
)
externalHelpersModuleReference.parent = importDecl
importDecl.parent = node
```

**Expected behavior:**

Get the result text back with an import statement at the top of the source file

**Actual behavior:**

No changes

**Comment by weswigham** [comment]
Are you doing this in a `before` or an `after` transform?

**Comment by matthewmueller** [comment]
Ah good question. Currently traversing the AST it in a before transform.

**Comment by weswigham** [comment]
I think the changes made in #18017 should have got you covered, then - are you still broken on `typescript@next`?

**Comment by matthewmueller** [comment]
Awesome! I'll give it a shot. At first glance though, it seems like this PR addresses updating an existing import, it's not testing adding an import that wasn't previously there. 

Is adding an import addressed in this PR? I think I basically need a way to attach a new import onto the `statements` of the `SourceFile` node.

**Comment by weswigham** [comment]
@matthewmuller You should just be able to use `updateSourceFile` in your transformation and replace the statements list with one with your extra import added.

**Comment by matthewmueller** [comment]
@weswigham, thanks for pointing that out. I wasn't sure if that would cause the whole file to be re-parsed or not.

I tried implementing that but got a bit stuck. I think I'm 

```ts
const src = (node as ts.Node) as ts.SourceFile
const imp = "var style = require('Style')\n"
const range = ts.createTextChangeRange(
  ts.createTextSpanFromBounds(0, imp.length),
  imp.length + src.text.length
)
const updated = ts.updateSourceFile(src, imp + src.text, range)
return (updated as ts.Node) as T
```

Results in a compiler error:

```
Error: Debug Failure. False expression.
at checkChangeRange (node_modules/typescript/lib/typescript.js:18346:26)
at Object.updateSourceFile (node_modules/typescript/lib/typescript.js:17980:13)
at Object.updateSourceFile (node_modules/typescript/lib/typescript.js:12348:47)
```

I'm sure I'm doing something wrong here with the range but it's not clear to me what that could be. Any pointers would be greatly appreciated!

**Comment by weswigham** [comment]
@matthewmueller If you want to write it as a transformer (and not string manipulations), you should write it like so to add `import style = require("styles")`:
```ts
    const file = node as SourceFile;
    updateSourceFileNode(file, [createImportEqualsDeclaration(
        /*decorators*/ undefined,
        /*modifiers*/ undefined,
        "style",
        createExternalModuleReference(createLiteral("styles"))
    ), ...file.statements]);
```
or like so to add `var style = require("styles")`:
```ts
    const file = node as SourceFile;
    updateSourceFileNode(file, [createVariableStatement(
        /*modifiers*/ undefined,
        createVariableDeclarationList([createVariableDeclaration("style", /*type*/ undefined, createCall(createIdentifier("require"), [], [createLiteral("styles")]))])
    ), ...file.statements]);
```

Reparsing an entire file is incredibly wasteful (and will likely cause you to lose sourcemaps and other things).

**Comment by matthewmueller** [comment]
Soooooo good! I had no idea about the `[ ...file.statements ]`. 

Interestingly, it doesn't seem possible to do `const update: ts.NodeArray<ts.Statement> = [].concat(file.statements)`

Thanks for all your help! I'll drop a link here to the repo once it's public in case anyone else wants some more examples for modifying typescript's AST.

**Comment by matthewmueller** [comment]
Ahh one more thing. How can we indicate that it should be using the `["default"]`? I've put together a self-contained example runnable via `ts-node file.ts`:

```
import * as ts from 'typescript'

const transform = {
  [ts.SyntaxKind.SourceFile]: (node: any) => {
    const file = (node as ts.Node) as ts.SourceFile
    const update = ts.updateSourceFileNode(file, [
      ts.createImportEqualsDeclaration(
        /*decorators*/ undefined,
        /*modifiers*/ undefined,
        'salami',
        ts.createExternalModuleReference(ts.createLiteral('salami'))
      ),
      ...file.statements
    ])

    return update as ts.Node
  }
}

console.log(
  ts.transpileModule(
    'import sandwich from "sandwich"; console.log(sandwich); console.log(salami)',
    {
      reportDiagnostics: true,
      transformers: {
        before: [visitor(transform)]
      },
      compilerOptions: {
        noEmitOnError: true,
        jsx: ts.JsxEmit.React,
        module: ts.ModuleKind.CommonJS,
        // module: ts.ModuleKind.ESNext,
        importHelpers: true,
        jsxFactory: 'h'
      }
    }
  )
)

function visitor(transform: any) {
  return (context: ts.TransformationContext) => {
    return (sourceFile: ts.SourceFile): ts.SourceFile => {
      return visit(sourceFile)
      function visit<T extends ts.Node>(node: T): T {
        const t = transform[node.kind]
        if (!t) {
          return ts.visitEachChild(node, visit, context)
        }

        // enter a node
        if (typeof t === 'object' && t.enter) {
          const tr = t.enter(node, context)
          if (tr) node = tr as T
        }

        // if it's a function, treat it
        // the same way as t.enter
        if (typeof t === 'function') {
          const tr = t(node, context)
          if (tr) node = tr as T
        }

        // visit each child
        let exitNode = ts.visitEachChild(node, visit, context)

        // if we have an exit call function
        if (typeof t === 'object' && t.exit) {
          const tr = t.exit(exitNode, context)
          if (tr) exitNode = tr as T
        }

        return exitNode
      }
    }
  }
}
```

The compiled output will look like this:

```
"use strict";
exports.__esModule = true;
var salami = require("salami");
var sandwich_1 = require("sandwich");
console.log(sandwich_1["default"]);
console.log(salami);
```

You'll notice that `sandwich` gets handled properly, but the newly added import does not.

**Comment by matthewmueller** [comment]
@weswigham sorry to be a bother, but do you mind taking a look at this if you have a moment? I'm soo close, but still a bit stuck with why my newly created import doesn't get compiled to:

`myimport["default"]` when the target changes to `commonjs`

**Comment by weswigham** [comment]
Hm. I'll take a look; but this should also give you the output you want:
```ts
const file = (node as ts.Node) as ts.SourceFile;
const update = ts.updateSourceFileNode(file, [
  ts.createImportDeclaration(
    undefined,
    undefined,
    ts.createImportClause(
      ts.createIdentifier('salami'),
      ts.createNamedImports([ts.createImportSpecifier(ts.createIdentifier("default"), ts.createIdentifier("salami"))])
    ),
    ts.createLiteral('salami')
  ),
  ...file.statements
]);
```

**Comment by weswigham** [comment]
OH, wait, you're asking why the references don't get updated! That's on you and your transform, sorry! Since your new nodes aren't bound in the binder, TS has no idea that the `salami` you're adding is the same `salami` referenced elsewhere in the file; so it's up to you and your transform to rename everything appropriately! Sorry!

**Comment by matthewmueller** [comment]
> TS has no idea that the salami you're adding is the same salami referenced elsewhere in the file; so it's up to you and your transform to track and rename everything appropriately! Sorry!

Ahh that makes sense. I thought that would be happening in between the `before` and `after` transforms. Okay so that would mean that I'd need to know what we're targeting (es6 vs commonjs) within my transform. 

I'll give it a go manually and open an issue if it's quite difficult. I really appreciate you taking the time to help me out, thanks!

**Comment by matthewmueller** [comment]
Alrighty, in case this helps anyone else out. Here's how you'd support different module options:

```ts
{
    [ts.SyntaxKind.SourceFile]: (node, context) => {
      if (!context) return
      const opts = context.getCompilerOptions()
      const { module } = opts

      // const StyledTSX = require('styled-tsx')
      if (module === ts.ModuleKind.CommonJS) {
        const file = (node as ts.Node) as ts.SourceFile
        const update = ts.updateSourceFileNode(file, [
          ts.createVariableStatement(
            /*modifiers*/ undefined,
            ts.createVariableDeclarationList([
              ts.createVariableDeclaration(
                importName,
                /*type*/ undefined,
                ts.createPropertyAccess(
                  ts.createCall(
                    ts.createIdentifier('require'),
                    [],
                    [ts.createLiteral(importFrom)]
                  ),
                  ts.createIdentifier('default')
                )
              )
            ])
          ),
          ...file.statements
        ])
        return (update as ts.Node) as T
      }

      // import StyledTSX from 'styled-tsx'
      if (module === ts.ModuleKind.ES2015 || module === ts.ModuleKind.ESNext) {
        const file = (node as ts.Node) as ts.SourceFile
        const update = ts.updateSourceFileNode(file, [
          ts.createImportDeclaration(
            /* decorators */ undefined,
            /* modifiers */ undefined,
            ts.createImportClause(ts.createIdentifier(importName), undefined),
            ts.createLiteral(importFrom)
          ),
          ...file.statements
        ])
        return (update as ts.Node) as T
      }

      return node
    }
  }
```
