### ISSUE TITLE
Smart indent result is incorrect after a binary operator

### ISSUE THREAD

**Issue by JsonFreeman** [Microsoft/TypeScript#1836]
```ts
function f() {
    return a &&
        b && /*cursor here*/
}
```
Triggering smart indent will align the cursor with the return keyword, although I would expect it to be aligned with `b`. This is specifically the case when the previous line ends with a binary operator because there is no ASI interpretation available.

**Comment by JsonFreeman** [comment]
Please also fix for ternary conditional operator

**Comment by mhegazy** [comment]
Closing for housekeeping purposes. The behavior outlined in the OP has been in place for over 13 month now and have not got any updates on this issue. Please file a new issue if an action is required.
