### ISSUE TITLE
Generic Function with Indexed Type ignores readonly

### ISSUE THREAD

**Issue by Nathan-Fenner** [Microsoft/TypeScript#18374]
TypeScript Version: 2.4.2

**Code**

```ts
function mapAssign<T, K extends keyof T>(obj: T, k: K, f: (v: T[K]) => T[K]) {
    obj[k] = f(obj[k]);
}

type NoChange = {
    readonly value: number
}
const obj: NoChange = {value: 5};

mapAssign(obj, "value", x => x+1);
```

**Expected behavior:**
Since `NoChange.value` is `readonly`, it should not be modifiable.

**Actual behavior:**
The code compiles and runs, modifying `obj.value`.

This might just be a design limitation that can't be worked around.

If a stricter check was desirable, I could imagine it being something like this:

* if `K extends keyof T` and `k: K` and `x: T`, then `x[k] = e` would fail, but `T = {readonly [k]: any}` would be okay
* if `K extends !readonly keyof T` and `k: K` and `x: T` then `x[k] = e` would succeed, but `T = {readonly [k]: any}` would fail

So the above program would become

```ts
function mapAssign<T, K extends !readonly keyof T>(obj: T, k: K, f: (v: T[K]) => T[K]) {
    obj[k] = f(obj[k]); // okay, since K extends !readonly keyof T
}
mapAssign(obj, "value", x => x+1); // error: Const.value is readonly
```

An alternative change (which I think is much less ergonomic) would be the following:

* if `K extends keyof T` and `k: K` and `x: T` then `x[k] = e` would succeed, but `T = {readonly [k]: any}` would fail
* if `K extends readonly keyof T` and `k: K` and `x: T` then `x[k] = e` would fail but `T = {readonly [k]: any}` would succeed.

So the program would be
```ts
function mapAssign<T, K extends keyof T>(obj: T, k: K, f: (v: T[K]) => T[K]) {
    obj[k] = f(obj[k]);
}
mapAssign(obj, "value", x => x+1); // error: Const.value is readonly
```

**Comment by olegdunkan** [comment]
> Most significant change is that, in order to ensure backwards compatibility, the readonly modifier doesn't affect subtype and assignability type relationships of the containing type (but of course it affects assignments to individual properties).
https://github.com/Microsoft/TypeScript/pull/6532#issuecomment-174356151


You can do so:
```ts
function mapAssign<T, K extends keyof T>(obj: Readonly<T>, k: K, f: (v: T[K]) => T[K]) {
    obj[k] = f(obj[k]); //error
}

type NoChange = {
    value: number
}
const obj: NoChange = {value: 5};

mapAssign(obj, "value", x => x+1);
```

**Comment by Nathan-Fenner** [comment]
Note that the solutions I proposed does not affect subtyping or assignability of containing types, only the keys of those types. (Unfortunately, it's in a somewhat backwards incompatible manner).

The sample you gave does not resolve the problem. `mapAssign` is a perfectly reasonable function whose implementation should not produce an error. It is only incorrect to use it on readonly keys.

**Comment by olegdunkan** [comment]
My example doesn't solve your problem but mentions that we can use `Readonly` in places we want to restrict write access

**Comment by Nathan-Fenner** [comment]
The purpose of this issue is to illustrate a case where `readonly` fails to restrict write access.

```ts
function modify<T, K extends keyof T>(k: K, x: T, f: (v: T[K]) => T[K]) {
    x[k] = f(x[k]);
}
type Point = {
    x: number,
    y: number,
}
const myConstant: Readonly<Point> = { x: 4, y: 7 };
modify("x", myConstant, x => x + 1);
console.log(myConstant) // => 5
```

**Comment by RyanCavanaugh** [comment]
Same comment above about backward compatibility applies

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
