### ISSUE TITLE
Nightly code errors depending on object placement order with ype '(state: State, action: Action<Address>) => State' has no properties in common with type 'ReducerNextThrow<State, State>

### ISSUE THREAD

**Issue by pocesar** [Microsoft/TypeScript#18376]
**TypeScript Version:**  2.6.0-dev.20170910

**Code**

```ts
// fails
export default handleActions<RActions.State>({
  [`${RActions.currentAddress}`]: (state: RActions.State, action: Action<RActions.Address>): RActions.State => {
    return {
      ...state,
      currentAddress: action.payload
    }
  },
  [`${RActions.reportVoucher}`]: (state: RActions.State, action: Action<never>): RActions.State => {
    return {
      ...state,
      errors: {
        ...state.errors,
        voucher: null
      }
    }
  },
})
// works
export default handleActions<RActions.State>({
  [`${RActions.reportVoucher}`]: (state: RActions.State, action: Action<never>): RActions.State => {
    return {
      ...state,
      errors: {
        ...state.errors,
        voucher: null
      }
    }
  },
  [`${RActions.currentAddress}`]: (state: RActions.State, action: Action<RActions.Address>): RActions.State => {
    return {
      ...state,
      currentAddress: action.payload
    }
  },
})
```
![image](https://user-images.githubusercontent.com/461084/30258662-d250580a-9691-11e7-95f6-ec9d1fd771b3.png)

![image](https://user-images.githubusercontent.com/461084/30258672-dc24df90-9691-11e7-841e-921488cf00d2.png)

**Expected behavior:**

Doesn't matter where the property is put, it works

**Actual behavior:**

Errors when placing the computed property in different places

**Comment by mhegazy** [comment]
Can you share a self-contained reproduction of the issue?

**Comment by pocesar** [comment]
all my calls using handleActions from redux-actions are now failing across multiple projects that use the typings

![image](https://user-images.githubusercontent.com/461084/30316181-c55209aa-977c-11e7-8b0b-c84eb9e90b74.png)

as little as 

![image](https://user-images.githubusercontent.com/461084/30316226-f210e01a-977c-11e7-8e05-4445a614be21.png)

**Comment by mhegazy** [comment]
Can you get me a small sample i can debug against instead of screenshots?

**Comment by pocesar** [comment]
```ts
import { handleActions, Action } from 'redux-actions'

export interface State {
  cidade: string;
  access: string;
  relogin: boolean;
  groups: iGroups.GroupDataSet[];
  filters: iGroups.FilterDefinitionDataSet[];
  lastError: string;
  geo: Data.LatLng;
  user: User;
  statistics: Data.Statistics[];
}

export const initialState: State = {
  cidade: '',
  access: '',
  lastError: '',
  groups: [],
  relogin: false,
  filters: [],
  statistics: [],
  geo: {
    lat: 0,
    lng: 0,
  },
  user: {
    name: '',
    role: '',
    initials: ''
  }
}

let InitialState = function(){ /*redacted*/ }
InitialState.toString = () => 'INITIAL_STATE'

let Clear = function() { /*redacted*/ }
Clear.toString = () => 'CLEAR'

const Reducer = handleActions<State>({
    // RESET
   [`${InitialState}`]: (state, action) => {
    return {
      ...initialState
    }
  },
   // CLEAR
  [`${Clear}`]: (state, action) => {
    return {
      ...state,
      lastError: ''
    }
  },
}, initialState)
```

**Comment by mhegazy** [comment]
do not get any errors on this using `@2.5.2` or `@next`

**Comment by pocesar** [comment]
sorry, I didn't even check if that repro'd. it needs manually setting either the state, action or return value of the reducer like so

```ts
[`${Clear}`]: (state: RActions.State, action: Action<string>): RActions.State => {
  return {
    ...state,
    lastError: action.payload
  } 
}
```

**Comment by mhegazy** [comment]
This error seems correct. `Action<string>` is not `Action<State>`. when does it disappear?

**Comment by pocesar** [comment]
when I shuffle the items around

**Comment by mhegazy** [comment]
> when I shuffle the items around, it really doesn't make much sense, but I found that putting some items above others "fix" the problem

can you give me a sample with two variants, one that causes an error and one that does not?

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
