### ISSUE TITLE
Remove code duplicates in compiled JS

### ISSUE THREAD

**Issue by zeroin** [Microsoft/TypeScript#18386]
Sometimes you must add identical property or method to an extending class just for a correct type. As  in compiled code all the type information is lost, such variables or methods are duplicates and do not do anything. I would suggest adding some compile flag which would tell to strip duplicating methods from extending classes leaving them in base class only.

**Comment by mhegazy** [comment]
> Sometimes you must add identical property or method to an extending class just for a correct type.

this does not sound right. can you share some context for where this is required.

**Comment by zeroin** [comment]
Here is an example:
```

class ClassA {
    protected _dataItemTemplate: typeof DataItemA = DataItemA;

    public makeDataItem(): DataItemA{
        return new this._dataItemTemplate();
    }
}

class ClassB extends ClassA {
    protected _dataItemTemplate: typeof DataItemB = DataItemB;

    public makeDataItem(): DataItemB{
        return new this._dataItemTemplate();
    }   
}

class DataItemA {

}

class DataItemB {

}
```

The makeDataItem() method in the compiled code is a duplicate. I know that this particular situation could be handled with generics, but it's not always you want and can use generics.

**Comment by mhegazy** [comment]
normally you can use `this` types to get you the type of the property without having to redefine the function. e.g.:

```ts

class ClassA {
     _dataItemTemplate: DataItemA = new DataItemA();

	public makeDataItem(): this["_dataItemTemplate"] {
		return this._dataItemTemplate;
	}
}

class ClassB extends ClassA {
    _dataItemTemplate: DataItemB = new DataItemB();
}

class DataItemA {
	
}

class DataItemB {
	b: number;
}

new ClassB().makeDataItem().b // OK
```

The problem in your case is you want the instance type of the constructor function `this["_dataItemTemplate"]` where is no way to do this at the time being. Issue https://github.com/Microsoft/TypeScript/issues/6606 tracks adding syntax in the language to get the return type of a constructor. so if https://github.com/Microsoft/TypeScript/issues/6606 is there, you can write this as `typeof new this["_dataItemTemplate"]`.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
