### ISSUE TITLE
Support computed properties in destructuring patterns

### ISSUE THREAD

**Issue by JsonFreeman** [microsoft/TypeScript#1838]
Add support for things like

``` ts
var { ["some" + "Name"]: x } = { ["some" + "Name"]: 0 };
```

In variables, parameters, and assignments.

This involves parsing, type check and emitting in ES6. Also, eventually we will need to support Symbols in destructuring patterns as well.

**Comment by Andarist** [comment]
This particular example works and I didn't experience any problems with computed properties in TS, especially when it comes to parsing I would expect them to just work. Obviously checking and emitting is somewhat limited for them but usually, if no better type can be created then it results in an index signature and stuff.

I would say that this issue can be closed. cc @RyanCavanaugh

**Comment by jakebailey** [comment]
The above does parse/check now, but if you instead make a typo on the right side, it... still checks, for some odd reason.

```tsx
var { ["some" + "Name"]: x } = { ["oops" + "not correct"]: 0 };
//                       ^? number???
```

[Playground Link](https://www.typescriptlang.org/play?#code/G4QwTgBA3hDaBEBnA9gWwKbwgagvAciBvALoBcEAHhAL4QC80c8yyADolrvAHbIAuEAMbIwYdEP6kKABloBuALAAoAPSqImrdp27NAPQD8QA)

**Comment by Andarist** [comment]
I discussed this particular example with Jake outside of GitHub but it's worth to recap it here.

The left side here is creating a contextual type of `{ [x: string]: any }` and the right side is just `{ [x: string]: number }` so it typechecks OK and it's able to unpack a `number` into `x`. Computed properties that don't refer to const variables etc just end up producing index signatures.

**Comment by jakebailey** [comment]
Yeah, I vote closed; this issue is so old that I'm pretty sure this was asking for _any_ amount of this to work.
