### ISSUE TITLE
Unable to inherit the interface after import statement in typescript

### ISSUE THREAD

**Issue by spvjebaraj** [Microsoft/TypeScript#18381]
Hi,
I am working in SharePoint Online project with Typescript along with pnp js. I installed the sp-pnp-js via package.json file. In my code, I am using interface and I want to implement the interface in the class. In that class I want to use pnp code. Please find the code below.

**test123.ts - interface**

```
namespace Test123 {
      export interface IListService {
             getAllLists(): Promise<any>;
      }
}
```
After I import the pnp in the below code, I am unable to inherit the interface.

**test.ts - class file**

```
import pnp from "sp-pnp-js;
namespace Test123 {
     export class PnpListService implements IListService {     
     }
}
```
I got the error as Cannot find name 'IListService'.
Kindly provide the solution to fix the error.

Thanks
Philip

**Comment by mhegazy** [comment]
A file with one top-level `import`/`export` (e.g. `test.ts` in your example) is considered a module. modules have their own scope, and do not merge with global scope declarations. 
so namespacce `Test123` in `test.ts` is not another declaration of `Test123` in `test123.ts` in the global scope. it just shadows it.
you can find more about modules at: http://www.typescriptlang.org/docs/handbook/modules.html  and namespaces : http://www.typescriptlang.org/docs/handbook/namespaces-and-modules.html

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
