### ISSUE TITLE
Type not suggested when implementing an interface's overloaded method

### ISSUE THREAD

**Issue by bruce965** [microsoft/TypeScript#18384]
**TypeScript Version:**  2.5.2 / nightly (2.6.0-dev.20170910)

**Code**

```ts
interface MyInterface {
	exec(action: 'action_1'): void;
	exec(action: 'action_2'): void;
	exec(action: string): void;
}

const test: MyInterface = {
	exec(arg) {
		// `arg` type is `any`
	}
};
```

**Expected behavior:**

I would expect `arg` type to be `"action1"|"action2"|string`.

**Actual behavior:**

`arg` type is `any`.

**Comment by mhegazy** [comment]
Contextual types do not flow from overloads. this issue has been reported in https://github.com/Microsoft/TypeScript/issues/16019 and there is a proposed change for it in https://github.com/Microsoft/TypeScript/pull/17819

**Comment by RyanCavanaugh** [comment]
Declining due to lack of interest.
