### ISSUE TITLE
Overloading function with literal argument doesn't work

### ISSUE THREAD

**Issue by dfilatov** [Microsoft/TypeScript#18389]
**TypeScript Version:**  2.5.2

**Code**
```ts
function test(p: 'a'): 'a';
function test(p: string): string {
    return p;
}

test('b');
```

**Expected behavior:**
no errors

**Actual behavior:**
Argument of type '"b"' is not assignable to parameter of type '"a"'.

**Comment by mhegazy** [comment]
The function has one signature. the other one is called an "implementation" signature, is only visible within the body of the function. so if you want your function to be called with a `string`, add a new overload.

```ts
function test(p: 'a'): 'a';
function test(p: string): string;
function test(p: string): string {
    return p;
}
```

**Comment by dfilatov** [comment]
@mhegazy Thank you for explanation!
