### ISSUE TITLE
JSDoc {Object} and {object} shown as any

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#18396]
**TypeScript Version:**  2.5.2

From: https://github.com/Microsoft/vscode/issues/34107#issuecomment-328524291

**Code**

For the JavaScript

```js
/**
 * @param {Object} x 
 */
function foo(x) { } 
```

Hover over `x`.

**Expected behavior:**
Type of `x` is shown as `Object`

**Actual behavior:**
Type of `x` is shown as `any`

**Comment by mhegazy** [comment]
Cause this is what the type system thinks of them. `Object`, `object` and `*` are all synonymous of `any`.

Looking at JSDoc patterns in the wild it was clear that:
- Case is used interchangeably, i.e. that `object` and `Object`, `number` and `Number`, `array` and `Array` were used interchangeably.
- Users use `Object` to mean a plain old JS object or (POJO). in input positions (i.e. function parameters) this means the TS primitive `object` type, but in output position it rely means `any`. 

So we opted to make `Object` and `object` in JSDoc synonymous with `any`.
