### ISSUE TITLE
 Optional field type narrowing should make types compatible

### ISSUE THREAD

**Issue by rasmushalland** [Microsoft/TypeScript#18395]
**TypeScript Version:**  2.5.2

**Code**

```ts
type mytype = {
    p1: string;
}

function constructMyType_error(): mytype {
    let o: Partial<mytype> = {};
    o.p1 = 'x';

    // Error "Type 'undefined' is not assignable to type 'string'"
    return o;
}

function constructMyType_noerror(): mytype {
    let o: Partial<mytype> = {};
    o.p1 = 'x';

    // No error.
    return { p1: o.p1 };
}
```

**Expected behavior:**
No compiler errors.

**Actual behavior:**
A compiler error in the function constructMyType_error, although the compiler knows that the field p1 has type ```string``` instead of ```string | undefined```. It does not use this knowledge to conclude that the variable o is compatible with the return type.

**Why is this problematic**
In some cases it is nice to construct an object one property at a time. Without loosing any compiler checks, that is. And without having to write the code to copy the object, as the function constructMyType_noerror does.

**Comment by RyanCavanaugh** [comment]
See #10065

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
