### ISSUE TITLE
'arguments' resolution is incorrect

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#1839]
From the ES6 Specification Draft

> 18. Else if **`"arguments"`** is an element of *parameterNames*, then<br />
> &nbsp;&nbsp;a. Let *argumentsObjectNeeded* be **false**.

However, if you have

```TypeScript
function f() {
    var arguments: number;
    return arguments;
}
```

we concede the type of `arguments` to `number`. This should at least *only* be the case if `arguments` appears in the parameter list. One might assume that `arguments` has the value `undefined`, and use it inappropriately before it is actually declared.

**Comment by mhegazy** [comment]
@DanielRosenwasser, What is the proposed change?

**Comment by DanielRosenwasser** [comment]
I spoke with @ahejlsberg about this and the outcome was that the complexity that this introduces does not justify the gains.
