### ISSUE TITLE
readonly property in interface should be enforced in implementation

### ISSUE THREAD

**Issue by chrisbruford** [Microsoft/TypeScript#18405]
Currently when creating a readonly property in an interface it is not an error to create a writable property in the class that implements the interface.

Should it not flag up that the class isn't implementing correctly?

**TypeScript Version:**  2.5.3

**Code**

```ts
interface Drivable {
    readonly steeringWheel: boolean
}

class Car implements Drivable {
    steeringWheel = true;
    constructor(){}
}

let myCar = new Car();
myCar.steeringWheel = false;```

**Expected behavior:**
Error that Car does not correctly implement Drivable

**Actual behavior:**
Compiles

**Comment by ahejlsberg** [comment]
That's not really the meaning of `readonly`. When you mark a property as `readonly` it means that you can't mutate it through this particular type, but there is no guarantee that it can't be mutated by other means. In your example, the `Drivable` interface is basically a read-only view of the `Car` class. If all you expose to a consumer is `Drivable` then they won't be able to mutate the underlying `Car`. But the `Car` itself isn't constrained.

**Comment by chrisbruford** [comment]
Thanks @ahejlsberg - seems odd to me that a class implementing that interface doesn't have to implement the property as readonly, but that's just me I guess 😄

**Comment by RyanCavanaugh** [comment]
@chrisbruford you definitely would not want that behavior. If you wrote this interface
```ts
interface ReadonlyArrayish<T> {
  // Users may not mutate the array of a ReadonlyArrayish reference
  readonly count: number;
  getAt(index: number): T;
}

class MyArray implements ReadonlyArrayish<T> {
  // ...
  reset() {
    this.count = 0; // ERROR you can't mutate array??
  }
}
```
