### ISSUE TITLE
Typescript only guarantee type checking when function/constructors are used explicitly

### ISSUE THREAD

**Issue by titusfx** [Microsoft/TypeScript#18404]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

**Code**

    class Documents{
        title: string;
    
        toString() {
            return this.title;
        }
    }
    class Unit {
    
        name: string = 'My Name';
        documents: Documents[];
    
        constructor(name:string, documents:Documents[]) {
            this.name = name;
            this.documents = documents;
        }
    
        toString() {
            return this.name;
        }
    }
    
    let req = { name: 'Unit 1', documents: [{ title: 'title 1'}, { title: 'I have title' }, { title: null }] };
    
    function cast<T>(param: T) {
        let result: T = param;
        return result;
    }
    
    console.log('Unit: ', cast<Unit>(req).toString());
    console.log('docs: ', cast<Unit>(req).documents[0].toString())
    console.log('Now using unit as directly');
    console.log((req as Unit).toString())
    console.log((<Unit>req).toString())

    console.log('Converting to Unit manually')
    console.log(new Unit(req.name, req.documents).toString());
    console.log(new Unit(req.name, req.documents).documents[0].toString());

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**Expected behavior:**
Unit:  Unit 1
(unknown) docs:  title1
(unknown) Now using unit as directly
(unknown) Unit 1
(unknown) Unit 1
(unknown) Converting to Unit manually
(unknown) Unit 1
(unknown) title 1

**Actual behavior:**
Unit:  [object Object]
(unknown) docs:  [object Object]
(unknown) Now using unit as directly
(unknown) [object Object]
(unknown) [object Object]
(unknown) Converting to Unit manually
(unknown) Unit 1
(unknown) [object Object]

**Comment by ahejlsberg** [comment]
This is working as intended (and really has nothing to do with TypeScript). You would need to explicitly create new instances of the objects to get the different `toString` behavior.
