### ISSUE TITLE
Operator '+' cannot be applied to types 'number[]' and '-1000'

### ISSUE THREAD

**Issue by vhb56** [Microsoft/TypeScript#18402]
Got a function from here: 
https://stackoverflow.com/questions/105034/create-guid-uuid-in-javascript
And TS says there is an error, not sure if it is true.
And in case this is not an error, but ts does count this as error - is there any way to @suppress it?
Thanks.

**TypeScript Version:**  2.3.2 / but same in playground: https://www.typescriptlang.org/play/index.html

**Code**

```ts
  function uuidv4()
  {
    return ([1e7] + -1e3 + -4e3 + -8e3 + -1e11).replace(/[018]/g, c =>
      (c ^ crypto.getRandomValues(new Uint8Array(1))[0] & 15 >> c / 4).toString(16)
    )
  }
```

**Expected behavior:**
No error?
**Actual behavior:**
``` Operator '+' cannot be applied to types 'number[]' and '-1000'. ```

**Comment by kitsonk** [comment]
This is not a support forum.

Questions should be asked at [StackOverflow](http://stackoverflow.com/questions/ask?tags=typescript) or on [Gitter.im](https://gitter.im/Microsoft/TypeScript).

But... TypeScript is protecting you from implicit coercion, so you need to [cast the array literal](https://www.typescriptlang.org/play/index.html#src=%20%20function%20uuidv4()%0A%20%20%7B%0A%20%20%20%20return%20(%5B1e7%5D%20as%20any%20%2B%20-1e3%20%2B%20-4e3%20%2B%20-8e3%20%2B%20-1e11).replace(%2F%5B018%5D%2Fg%2C%20c%20%3D%3E%0A%20%20%20%20%20%20(c%20%5E%20crypto.getRandomValues(new%20Uint8Array(1))%5B0%5D%20%26%2015%20%3E%3E%20c%20%2F%204).toString(16)%0A%20%20%20%20)%0A%20%20%7D):

```diff
  function uuidv4()
  {
-    return ([1e7] + -1e3 + -4e3 + -8e3 + -1e11).replace(/[018]/g, c =>
+    return ([1e7] as any + -1e3 + -4e3 + -8e3 + -1e11).replace(/[018]/g, c =>
      (c ^ crypto.getRandomValues(new Uint8Array(1))[0] & 15 >> c / 4).toString(16)
    )
  }
```
