### ISSUE TITLE
No way to type-constrain a value as object-but-not-a-function

### ISSUE THREAD

**Issue by axefrog** [Microsoft/TypeScript#18401]
**TypeScript Version:**  2.5.2

Just as `typeof someFunction === 'function'`, how do I type-constrain a generic parameter to only those types which would satisfy that same expression?

**Code**

```ts
function isObject<T extends object>(value: T | string | number | boolean | symbol | Function | null | undefined): value is T {
  return typeof value === 'object' && value !== null;
}

const fn = function () { return 'foo'; };
!isObject(fn) && fn.name; // fn.name is never
```

**Expected:**

After failing the type guard check, `fn.name` should have a compile time type of `string`, seeing as `fn` is a function primitive, not a standard object primitive.

**Actual:**

After failing the type guard check, `fn.name` has a compile time type of `never`.

This issue does not occur if the function is a local function declared via a `function` statement, rather than as a variable assignment.

The `object` type seems to match variables assigned a function value, and there appears to be no primitive type keyword that TypeScript understands as meaning a value having the `function` type, rather than just an object (`Function`) that has functional characteristics. I have also tried `((...args: any[]) => any)`, though I suspect the compiler treats that the same way as `Function`. I know that in JavaScript, functions are technically objects and can have arbitrary properties attached, but they're also special in that they're callable, and are first class primitives in JavaScript in that respect, and so I would expect TypeScript would be able to help me identify objects that are *not* functions, especially seeing as functions are such an integral and fundamental type in JavaScript.

**Update:**

Function overloads appear to solve the problem:

```ts
export type Primitive = string | number | boolean | symbol | null | undefined;

export function isObject<T extends Function>(value: T): false;
export function isObject<T extends object>(value: T | Primitive): value is T;
export function isObject<T extends object>(value: T | Primitive): value is T {
  return typeof value === 'object' && value !== null;
}

// compilation tests:
function c () { return 'foo'; }
const d = function () { return 'foo'; };
const a = 'foo', b = { foo: 'bar' };
isObject(a) && a.length; // good; compiles fine
!isObject(a) && a.length; // good; compiles fine
isObject(b) && b.foo; // good; compiles fine
!isObject(b) && b.foo; // good; error as expected
isObject(c) && c.name; // good; compiles fine
!isObject(c) && c.name; // good; compiles fine
isObject(d) && d.name; // good; compiles fine
!isObject(d) && d.name; // good; compiles fine
```

I'll leave the issue open pending confirmation that I'm not missing any relevant caveats. Devs, feel free to close it if so.

**Comment by axefrog** [comment]
Update:

Function overloads appear to solve the problem:

```ts
type Primitive = string | number | boolean | symbol | null | undefined;

export function isObject<T extends Function>(value: T): false;
export function isObject<T extends object>(value: T | Primitive): value is T;
export function isObject<T extends object>(value: T | Primitive): value is T {
  return typeof value === 'object' && value !== null;
}
```

I'll leave the issue open pending confirmation that I'm not missing any relevant caveats. Devs, feel free to close it if so.

**Comment by RyanCavanaugh** [comment]
Not a bug; functions are a subtype of objects. There isn't a way to express `isObjectButNotFunction` (same as there isn't a way to express `isAnimalButNotDog`)

**Comment by axefrog** [comment]
Ok, thanks.
