### ISSUE TITLE
Support computed properties downlevel

### ISSUE THREAD

**Issue by JsonFreeman** [Microsoft/TypeScript#1840]
We can emit computed properties in ES5, using the following scheme:

```ts
var x = {
    a: 0,
    ["b"]: 0,
    ["c"]() {},
    get ["d"]() { return 0 },
    set ["d"](x) {},
    e: 0
};
```
emits as:
```js
var x = {
    a: 0
};
x["b"]: 0;
x["c"] = function() {};
Object.defineProperty(x, "d" ...);
Object.defineProperty(x, "d" ...);
x.e = 0;
```

In any other expression context, we would emit a temp variable like we do for destructuring.

**Comment by DanielRosenwasser** [comment]
I removed some of the dot accesses from the original proposed emit [1]

[1]: 
```TypeScript
x.["b"]: 0;
x.["c"] = function() {};
```

**Comment by DanielRosenwasser** [comment]
I dunno about that emit - what about this?

```TypeScript
var x = { ["abc"]: 10},
    y = (x = undefined, 10);
```

I think we'll have to do something like the following:

```TypeScript
var x = (x = { }, x["abc"]: 10, x),
    y = (x = undefined, 10);
```

**Comment by JsonFreeman** [comment]
Yeah, when there are multiple variable declarations in the same variable statement, we would have to do that.
