### ISSUE TITLE
Warning-Message for html-file with typescript

### ISSUE THREAD

**Issue by houcode** [Microsoft/TypeScript#18412]
Is there a possibility to output a error message / warning with typescript, when the data binding or the name of the variable is wrong? 

for example:

<h2> {{ classname.check().SOMETHINGSTUPID }} <h/2> 

// In this case, attaching "SOMETHINGSTUPID" to my code doesn't output a error or warning.

thank you

**Comment by mhegazy** [comment]
The typescript compiler does not check the html template. if this is an angular template, then consider posting this issue on https://github.com/angular/angular. if this is a general handelbars-like template request, https://github.com/Microsoft/TypeScript/issues/5151 tracks that proposal.

**Comment by houcode** [comment]
thanks @mhegazy. But i found a different solution for the problem by using "Angular Language Service"! 
Really nice VS Code Plugin ;)
