### ISSUE TITLE
Type inference involving exhaustive switch statements is strange

### ISSUE THREAD

**Issue by bterlson** [Microsoft/TypeScript#18419]
**TypeScript Version:**  2.6.0-dev.20170912 (--strict preset)

**Code**

```ts
type Foo = {
    a: number;
    b: 'X' | 'Y';
}

function bar(p: Foo) { // inferred return type: 1 | 2
    switch (p.b) {
        case 'X': return 1;
        case 'Y': return 2;
    }

   // code here is reachable according to TS
  return 3; // makes return type 1 | 2 | 3 as expected if this code is reachable
}
```

**Expected behavior:**
Either:
1. the inferred return type for bar should include undefined (ala chained if statements doing the exact same thing as the switch above), or
2. the inferred return type should not include undefined and the code after the switch should be marked as unreachable.

**Actual behavior:**
Code after the switch is reachable but the implicit return is not added to the inferred return type of bar.

**Comment by thomasd16** [comment]
This behavior is expected and in the documentation. 
https://www.typescriptlang.org/docs/handbook/basic-types.html
> By default null and undefined are subtypes of all other types. That means you can assign null and undefined to something like number

This should be the same even with if statements instead of case statements.

**Comment by bterlson** [comment]
@thomasd16 this is not true for --strictNullChecks, which I am using via --strict.

However after talking to @RyanCavanaugh about this I am no longer concerned with this behavior.
