### ISSUE TITLE
Another narrowing bug with `{}`

### ISSUE THREAD

**Issue by chancancode** [Microsoft/TypeScript#18413]
**TypeScript Version:**  playground

**Code**

```ts
type unknown = {} | undefined | null | void;

interface Dict {
  [key: string]: unknown;
}

function isDict(value: any): value is Dict {
  return value !== null && value !== undefined;
}

function any(): any {
}

let notSure: unknown = any();

if (isDict(notSure)) {
  notSure['foo']; // <- turn on strict mode to see error, `notSure` is `{}`
}
```

**Expected behavior:**

`notSure` is `Dict` after the narrowing

**Actual behavior:**

`notSure` is `{}` after the narrowing

[Playground link](https://www.typescriptlang.org/play/#src=type%20unknown%20%3D%20%7B%7D%20%7C%20undefined%20%7C%20null%20%7C%20void%3B%0A%0Ainterface%20Dict%20%7B%0A%20%20%5Bkey%3A%20string%5D%3A%20unknown%3B%0A%7D%0A%0Afunction%20isDict(value%3A%20any)%3A%20value%20is%20Dict%20%7B%0A%20%20return%20value%20!%3D%3D%20null%20%26%26%20value%20!%3D%3D%20undefined%3B%0A%7D%0A%0Afunction%20any()%3A%20any%20%7B%0A%7D%0A%0Alet%20notSure%3A%20unknown%20%3D%20any()%3B%0A%0Aif%20(isDict(notSure))%20%7B%0A%20%20notSure%5B'foo'%5D%3B%20%2F%2F%20%3C-%20turn%20on%20strict%20mode%20to%20see%20error%2C%20%60notSure%60%20is%20%60%7B%7D%60%0A%7D)

**Comment by chancancode** [comment]
This is only a problem with `{}` involved – the definition suggested [here](https://github.com/Microsoft/TypeScript/issues/18196#issuecomment-327332352) works

**Comment by RyanCavanaugh** [comment]
A union with `{ }` in it will eagerly collapse to `{ }` as soon as it's examined by the type system; a union like this should never be written down on purpose. Did you mean `unknown = object | undefined | null | void` ?

**Comment by chancancode** [comment]
We have switched to `unknown = object | number | string | boolean | symbol | undefined | null | void` as per #18196, just thought we would report this in case it is a bug that is not already known.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
