### ISSUE TITLE
Support computed properties in class property declarations

### ISSUE THREAD

**Issue by JsonFreeman** [Microsoft/TypeScript#1841]
We can emit computed properties class properties, using the following scheme:

```ts
class C {
    ["hello"] = 0;
    static ["bye"] = 0;
}
```
emits as:
```js
var C = (function() {
    var __t1 = "hello";
    function C() {
       this[__t1] = 0;
    }
    C["bye"] = 0;
    return C;
})();
```

**Comment by JsonFreeman** [comment]
We would only do this for initialized properties. For uninitialized properties, we would have to give an error.

**Comment by DanielRosenwasser** [comment]
So if you had something like

```TypeScript
var x = 10;

class C {
  [x++] = x;
}
```

I'm assuming that every time the constructor is invoked, the `x++` expression gets evaluated.

**Comment by JsonFreeman** [comment]
No, that is not the semantics I had in mind. It would get evaluated when the class is evaluated, which happens only once.

**Comment by DanielRosenwasser** [comment]
Why? We don't cache the initializers anyway.

```TypeScript
var x = 0;
function f(): number {
	return x++;
}

class Greeter {
    greeting: number = f();
    constructor() {
    }
}
```

```JavaScript
var x = 0;
function f() {
    return x++;
}
var Greeter = (function () {
    function Greeter() {
        this.greeting = f();
    }
    return Greeter;
})();
```

**Comment by JsonFreeman** [comment]
Yeah but we *would* cache the property name. It feels different from the initializer. But I see what you're saying, we could move the name into the constructor too, unless anyone has objections to that.

**Comment by DanielRosenwasser** [comment]
As per our design meeting last week, we've decided that we just won't support this because the semantic implications can be counterintuitive.
