### ISSUE TITLE
`Promise.then` variance issue

### ISSUE THREAD

**Issue by chancancode** [Microsoft/TypeScript#18414]
Hello!

I understand that function parameter are unsound/bi-variant in TypeScript in general, however, I thought there was a "targeted fix" for promises at some point, so I am wondering if this is a considered a bug:

```ts
function stringOrNumber(): string | number {
  return Math.random() > 0.5 ? 'hello' : 3.14;
} 

function stringToString(s: string): string {
  return s.toUpperCase();
}

Promise.resolve().then(stringOrNumber).then(stringToString);
```

[Playground link](https://www.typescriptlang.org/play/#src=function%20stringOrNumber()%3A%20string%20%7C%20number%20%7B%0A%20%20return%20Math.random()%20%3E%200.5%20%3F%20'hello'%20%3A%203.14%3B%0A%7D%20%0A%0Afunction%20stringToString(s%3A%20string)%3A%20string%20%7B%0A%20%20return%20s.toUpperCase()%3B%0A%7D%0A%0A%0APromise.resolve().then(stringOrNumber).then(stringToString)%3B)

**Comment by DanielRosenwasser** [comment]
Unfortunately this is expected from parameter bivariance (but certainly not desired). The fix you're referencing from 2.4 prevents the following bug:

```ts
    function toStringOrNumber(): string | number {
      return Math.random() > 0.5 ? 'hello' : 3.14;
    } 

    function stringToString(s: string): string {
      return s.toUpperCase();
    }


    let stringOrNumber = Promise.resolve().then(toStringOrNumber);
    let str = Promise.resolve("").then(stringToString);

    str = stringOrNumber;
//  ~~~ bad
```

**Comment by DanielRosenwasser** [comment]
Check out discussion at #18513.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
