### ISSUE TITLE
ts error code type 'string | number' is not assignable to type 'number'

### ISSUE THREAD

**Issue by Sarbdeveloper** [Microsoft/TypeScript#18418]
im getting this error code in angularjs, trying to create a countdown timer, please help

//Convert the remainders gotten above to the nearest whole number 
    intervalinsecond = (intervalinsecond < 10) ? "0" + intervalinsecond : intervalinsecond;
    intervalinminute = (intervalinminute < 10) ? "0" + intervalinminute : intervalinminute;
    intervalinhour = (intervalinhour < 10) ? "0" + intervalinhour : intervalinhour;
    //Get the value for day and output it throug the ID in the html table tags
    document.getElementById("days").textContent = intervalinday;
    document.getElementById("days").innerText = intervalinday;
    //Get the value for hour and output it throug the ID in the html table tags
    document.getElementById("hours").textContent = intervalinhour;
    document.getElementById("hours").innerText = intervalinhour;
    //Get the value for minute and output it throug the ID in the html table tags
    document.getElementById("minutes").textContent = intervalinminute;
    document.getElementById("minutes").innerText = intervalinminute;
    //Get the value for second and output it throug the ID in the html table tags
    document.getElementById("seconds").textContent = intervalinsecond;
    document.getElementById("seconds").innerText = intervalinsecond;

**Comment by RyanCavanaugh** [comment]
This is not a support forum.

**Comment by Sarbdeveloper** [comment]
where can i get one please

**Comment by mhegazy** [comment]
You would get better answers on StackOverflow or https://github.com/angular/angular
