### ISSUE TITLE
Use generic return types for frequently-casted library functions

### ISSUE THREAD

**Issue by RyanCavanaugh** [Microsoft/TypeScript#18415]
There are a handful of functions from lib.d.ts which are typically followed by a type assertion
```ts
const x = <HTMLDivElement>document.getElementById('zzz');
```
With the new inference changes, we can write a new overload
```ts
getElementById<T extends Element>(id: string): T
```
so that you can write the cleaner version
```ts
const x: HTMLDivElement = document.getElementById('zzz');
```

TODO: Figure out which functions these apply to

**Comment by gcnew** [comment]
Such generics will give a false sense of security. IMO, casts are what's appropriate there as they convey the "I know better" assertion.

**Comment by zspitz** [comment]
The following from the [DefinitelyTyped readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md) is relevant:
> #### Common mistakes
> ...
> * `getMeAT<T>(): T`:
>    If a type parameter does not appear in the types of any parameters, you don't really have a generic function, you just have a disguised type assertion.
>    Prefer to use a real type assertion, e.g. `getMeAT() as number`.
>    Example where a type parameter is acceptable: `function id<T>(value: T): T;`.
>    Example where it is not acceptable: `function parseJson<T>(json: string): T;`.
>    Exception: `new Map<string, number>()` is OK.

**Comment by mhegazy** [comment]
Though convenient, it is clearly unsafe.  users who would want to do that can do it themselves as overloads.
