### ISSUE TITLE
Union of two interfaces rejects keys that should be acceptable

### ISSUE THREAD

**Issue by dylanpyle** [Microsoft/TypeScript#18421]
**Update:** I submitted a bad code sample the first time around — I've updated this to reflect something that seems actually broken.

--

**TypeScript Version:**  2.5.2

**Code**

```ts
interface ThingTypeOne {
  type: 'one';
}

interface ThingTypeTwo {
  type: 'two';
}

type ThingType = 'one' | 'two';

type Thing = ThingTypeOne | ThingTypeTwo;

function makeNewThing(thingType: ThingType): Thing {
  return {
    type: thingType
  };
}
```

**Expected behavior:**

No error

**Actual behavior:**

```
foo.ts(14,3): error TS2322: Type '{ type: ThingType; }' is not assignable to type 'Thing'.
  Type '{ type: ThingType; }' is not assignable to type 'ThingTypeTwo'.
    Types of property 'type' are incompatible.
      Type 'ThingType' is not assignable to type '"two"'.
        Type '"one"' is not assignable to type '"two"'.
```
---

It looks to me like the issue is that the compiler doesn't figure out the union of keys within the interfaces. If that's true, it seems strange to me that this is a breaking error since this code should work just fine.

**Comment by ahejlsberg** [comment]
```ts
type Thing = ThingTypeTwo | ThingTypeTwo;
```

I'm pretty sure you meant to say:

```ts
type Thing = ThingTypeOne | ThingTypeTwo;
```

**Comment by dylanpyle** [comment]
😆  Yep. Thank you.

This was an attempt to isolate an issue that we hit in slightly more... well-vetted code, I'll open a new one if I can narrow it down to something more legitimate.

**Comment by dylanpyle** [comment]
OK, for posterity, here's a better example.

After isolating it like this though, I think I understand why it's happening; `Thing` happens to include all variations of `ThingType`, but it's not guaranteed anywhere — and I guess the compiler isn't quite smart enough to figure out the unions of each individual key in a union type.

@ahejlsberg if you have a spare sec, can you confirm that this is still working as expected?

```ts
type ThingType = 'one' | 'two';

interface BaseThing {
  type: ThingType;
}

interface ThingTypeOne extends BaseThing {
  type: 'one';
}

interface ThingTypeTwo extends BaseThing {
  type: 'two';
}

type Thing = ThingTypeOne | ThingTypeTwo;

function makeNewThing(thingType: ThingType): Partial<Thing> {
  const newThing: Partial<Thing> = {
    type: thingType
  };

  return newThing;
}
```

**Expected behavior**

No error

**Actual behavior**

```
foo.ts(18,9): error TS2322: Type '{ type: ThingType; }' is not assignable to type 'Partial<ThingTypeOne> | Partial<ThingTypeTwo>'.
  Type '{ type: ThingType; }' is not assignable to type 'Partial<ThingTypeTwo>'.
    Types of property 'type' are incompatible.
      Type 'ThingType' is not assignable to type '"two"'.
        Type '"one"' is not assignable to type '"two"'.
```

**Comment by dylanpyle** [comment]
@ahejlsberg Yep sorry about that, I've updated the original description with a new failing code sample that should illustrate this better, and updated the issue title to match.

**Comment by olegdunkan** [comment]
`{ type:"one" } | { type:"two" }` is not the same as `{ type:"one" | "two" }`

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Comment by jcalz** [comment]
@olegdunkan et al,

Could someone explain why `{ type:"one" } | { type:"two" }` is not the same as `{ type:"one" | "two" }`?  I understand that the compiler is not recognizing the identity, but they seem identical to me.  Can you produce an object of one type that is not an object of the other?  I am unable to conceive of one.
