### ISSUE TITLE
Extending class with Interface does not work as intended?

### ISSUE THREAD

**Issue by borestad** [Microsoft/TypeScript#18429]
I don't know if this is a bug, or working as intended, but it feel very wrong.

**TypeScript Version:**  2.5.2 / Typescript Playground

**Code**
https://goo.gl/rNMwRE

```ts
class IFoobar {
    setup: (a: string) => string;
}

class Foo implements IFoobar {
    setup() { // I'm expecting an error here
        return 'apa'
    }
}

const a = new Foo
a.setup() //=> No errors (why?)
a.setup('foo') //=> Error: Expecting 0 arguments, but got 1
```

Same behaviour with:
```ts
interface IFoobar {
    setup: (a: string) => string;
}
```

**Expected behavior:**
- Should receive a warning that setup doesn't implement setup correct

**Actual behavior:**
No error

**Comment by DanielRosenwasser** [comment]
When checking whether `Foo` implements `IFoobar`, TypeScript checks whether the member in `Foo` is assignable to that of `IFoobar`. Check out this section of our FAQ that further explains why one's assignable to the other: https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-functions-with-fewer-parameters-assignable-to-functions-that-take-more-parameters

**Comment by borestad** [comment]
Thank you! I did some more reading, and it makes sense. What I also discovered was that this 
code causes an error. Thank you for your reply 👍 

```ts
class Foo implements IFoobar {
    setup(a,b) { // Boom
        return 'apa'
    }
}

```
