### ISSUE TITLE
Inheritance only works if parent class is declared before child class

### ISSUE THREAD

**Issue by piersh** [Microsoft/TypeScript#1842]
i'm including a link to this codeplex issue since I believe it's a critical bug that's been incorrectly closed.

https://typescript.codeplex.com/workitem/627

when combining output into a single .js file, the compiler should NEVER emit derived classes before their base class.

this was reported 2 years ago, and it's still not fixed.

**Comment by RyanCavanaugh** [comment]
Duplicate of #21
