### ISSUE TITLE
Type narrowing on Function.length for either callable type

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#18422]
**TypeScript Version:**  2.5.2

**Code**

```ts
interface IFoo {
  a: ((x: number) => string) | ((x: number, y: boolean) => string)
}

const z: IFoo = { 
  a(x: number) { return '' }
}

if (z.a.length === 1) {
  z.a(1)
}
```

**Expected behavior:**
Type of `z.a` is narrowed to `(x: number) => string)` from the if statement

**Actual behavior:**
Error:

```
'Cannot invoke an expression whose type lacks a call signature. Type '((x: number) => string) | ((x: number, y: boolean) => string)' has no compatible call signatures.'
```

I'm trying to express an interface that can implement a method in one of two ways. Let me know if there is a better way to express this

**Comment by DanielRosenwasser** [comment]
I don't really know whether narrowing by `length` is the right thing since the underlying implementation might have nothing to do with how the signatures are described to TypeScript. In other words, you might have a parameter length of `0` if the function uses `arguments` under the cover.

I think it's worth considering whether it's the common enough case though.

**Comment by mjbvz** [comment]
Ok, that makes sense. Is there a better way to express the idea of an interface that implement a method one of two ways. I also tried:

```ts
interface X { x: number }

interface Y { y: number }

interface IFoo {
  a(x: X): string
  a(x: Y, y: boolean): string
}

const z: IFoo = { 
  a(x: X) { return '' }
} 

if (z.a.length <= 1) {
  z.a(1)
}
```

But this fails to compile since types `X` and `Y` are not compatible

**Comment by mhegazy** [comment]
The type system really does not have a good way to model function.length, in almost all its uses. The only way that works today is to have the signature part of type that that has a discriminant property, e.g.:

```ts
type IFoo = {
    kind: "x",
    a(x: X): string
} | {
    kind: "y"
    a(x: Y, y: boolean): string
};

const z: IFoo = {
    kind: "x",
    a(x: X) { return '' }
};

if (z.kind === "x") {
  z.a({ x: 1 })
}
```
