### ISSUE TITLE
TypedArrays: type thisArg correctly and other issues

### ISSUE THREAD

**Issue by NaridaL** [Microsoft/TypeScript#18425]
For example, UInt8Array.find

```ts
// currently:
find(
    predicate: (value: number, index: number, obj: Array<number>) => boolean, 
    thisArg?: any): number | undefined;
// better:
find<Z = undefined>(
    predicate: (this: Z, value: number, index: number, obj: this) => boolean,
    thisArg?: Z): number | undefined;
```

All the variants have the same issues. It seems like it would be a good idea to refactor them to:
```ts
interface TypedArray<ArrType> {
// find etc
}
interface UInt8Array extends TypedArray<UInt8Array> {}
interface UInt16Array extends TypedArray<UInt16Array> {}
// etc
```

**Comment by mhegazy** [comment]
We have explicitly removed the `this` types from arrays in #16223 #18116. you can still add the overloads locally if you so chose.

**Comment by NaridaL** [comment]
OK. Note that the callback parameter `obj` is currently wrong, it's `Array<number>`, when it should be `this`.

Would the refactoring with TypedArray help from a performance standpoint?

**Comment by mhegazy** [comment]
I do not think you need `this`, you jsut need `Int32Array` or `Int64Array`, etc.. a PR would be appreciated.

**Comment by NaridaL** [comment]
`this` would be more accurate in the unlikely case that you subclass a typed array.

**Comment by mhegazy** [comment]
yes, but will turn all these types into generic types. this costs more in terms of memory and in execution. and since this is the standard library everyone pays for the cost even if they never subclass typed arrays.
