### ISSUE TITLE
Unhelpful error in destructuring assignment

### ISSUE THREAD

**Issue by paulvanbrenk** [Microsoft/TypeScript#1843]
Consider the following:
`var [,,y] = [1, [[2], 3]];`

The error I get is Type '[number, (number | number[])[]]' has no property '2'. This is not actionable.

**Comment by mhegazy** [comment]
any suggestions on how to make this more palatable?

**Comment by DanielRosenwasser** [comment]
`Tuple of type [blah, (blah | blah[])[]] with cardinality '3' cannot be indexed at '2'`

**Comment by paulvanbrenk** [comment]
The Type .... can not be destructured in at most 2 parts. 

I would not use the word cardinality.... it has no meaning if you are not familiar with set theory.

**Comment by DanielRosenwasser** [comment]
with length*

Yeah, I'm mostly trying to avoid pluralization for 1-tuples.

**Comment by DanielRosenwasser** [comment]
@paulvanbrenk, I think @caitp has addressed this in #2238. Can you confirm?

**Comment by caitp** [comment]
It looks similar to #2090

**Comment by DanielRosenwasser** [comment]
Yup. Just spoke with Paul, this is indeed closed.
