### ISSUE TITLE
Inconsistent type-check with enum

### ISSUE THREAD

**Issue by Hachero** [Microsoft/TypeScript#18432]
**TypeScript Version:** 2.5.2

When I use numerical references in my enum I lose the ability to properly type-check with the enum in a class property

**code**
Example 1 passes type-checking, but produces run-time 404
```ts
export class Item {
  id: number;
  name: string;
  badge: ITEMBADGE; 
}

export enum ITEMBADGE {
  'item1.svg' = 1,
  'item2.svg' = 2
}

export const ITEMS: Item[] = [
  {id: 1, name: 'item1', badge: 1}, // runtime 404 error 
  {id: 2, name: 'item2', badge: 2}
]
```
Example 2 Does not pass type-check, but seems to me that it should
given: `ITEMBADGE[1] === 'item1.svg' // true` 

```ts
export class Item {
  id: number;
  name: string;
  badge: ITEMBADGE;  // changing this to type 'string' or type 'any' gets rid if the error, but I lose the type reference to enum ITEMBADGE therefore any string will suffice at run-time
}

export enum ITEMBADGE {
  'item1.svg' = 1,
  'item2.svg' = 2
}

// [ts] Type '{ id: number; name: string; badge: string; }[]' is not assignable to type 'Item[]'.
//   Type '{ id: number; name: string; badge: string; }' is not assignable to type 'Item'.
//   Types of property 'badge' are incompatible.
//     Type 'string' is not assignable to type 'ITEMBADGE'.
// const ITEMS: Item[]
export const ITEMS: Item[] = [
  {id: 1, name: 'item1', badge: ITEMBADGE[1]}, 
  {id: 2, name: 'item2', badge: ITEMBADGE[2]}
]
```

**Expected behavior:**
expected ts to see that the number reference to the enum is a string, since the class property `badge` can be set to type `string` then `ITEMBADGE[1]` produces the desired result

**Actual behavior:**
Although `ITEMBADGE[1]` is a `string` in this case, using `ITEMBADGE` as a type-check for `badge` in the class causes an error.  Assigning `badge: string;` type allows compilation

**further notes:**
It seems the issue is specific to number references with enum.  When I changed the enum to non-numerical references it works and I can use ITEMBADGE as a type-check in my class:

```ts
export class Item {
  id: number;
  name: string;
  badge: ITEMBADGE;
}

export enum ITEMBADGE {
  ITEM1 = 'item1.svg',
  ITEM2 = 'item2.svg'
}

export const ITEMS: Item[] = [
  {id: 1, name: 'item1', badge: ITEMBADGE.ITEM1},
  {id: 2, name: 'item2', badge: ITEMBADGE.ITEM2}
]
```

**Comment by RyanCavanaugh** [comment]
The reverse map (from number to string) isn't intended for regular use because it's not guaranteed that any particular *value* has only one *key*, e.g. this is legal:
```ts
enum Foo {
  bar = 1,
  baz = 1
}
Foo[1] // 'baz', not 'bar'
```
For your case I'd recommend using string enums; in general the reverse map for numeric enums should only be used for debugging / error message purposes.
