### ISSUE TITLE
Convert to ES6 Class Refactoring removes `export` keyword

### ISSUE THREAD

**Issue by hbenl** [Microsoft/TypeScript#18435]
**TypeScript Version:**  2.5.2 / nightly (2.6.0-dev.20170913)

Apply the refactoring to the following code:
**Code**
```js
export function MyClass() {
}
MyClass.prototype.foo = function() {
}
```

**Expected behavior:**
```js
export class MyClass {
    constructor() {
    }
    foo() {
    }
}
```

**Actual behavior:**
```js
class MyClass {
    constructor() {
    }
    foo() {
    }
}
```

Tested with both 2.5.2 and the latest nightly (2.6.0-dev.20170913).

**Comment by amcasey** [comment]
Copying `export` is straightforward, but handling other modifiers (`default`?) and member modifiers (e.g. could `foo` be `async`) will require further thought.

**Comment by amcasey** [comment]
Fixing exactly this problem is very easy and I'd be happy to create a PR if will unblock someone.  Making the entire refactoring modifier-aware, on the other hand, has relatively low ROI.

**Comment by charlespierce** [comment]
PR #19070 Opened to resolve this issue.
