### ISSUE TITLE
Proposal: Consider introducing a shorthand syntax for nullable types

### ISSUE THREAD

**Issue by MartinHaeusler** [Microsoft/TypeScript#18430]
Static analysis on "nullable" variables is a good thing. However,  using this feature also requires to explicitly create union types with `null` for every variable and member that can in fact be `null`. So, for example to create a nullable (and undefineable) number member...

    interface MyInterface {
      x: number | null | undefined
    }

It is currently possible to use a shortcut for `undefined`:

    interface MyInterface {
       x?: number | null
    }

Note that the two interface definitions above are equivalent, but `| null` is always required.

However, for my taste, this is all **way too verbose** for something as common as a nullable type. I would like to propose the following:

    interface MyInterface {
       x: number?
    }

... where `number?` is the shorthand for `number | null | undefined`. This little tweak would save a lot of typing and improve general acceptance of strict null checking. This isn't a new idea. Languages like  [Ceylon](https://ceylon-lang.org/) use the same method and syntax.

**Comment by MartinHaeusler** [comment]
Thanks for the pointer, but the discussion in this ticket seems a bit... inconclusive to me? The other ticket is closed, but I can't see clearly what the upshot of the discussion was.

**Comment by ahejlsberg** [comment]
Conclusion is here: https://github.com/Microsoft/TypeScript/issues/7426#issuecomment-196500331. Basically, there is no consensus on what `T?` should mean and therefore we don't have a shorthand notation.

**Comment by RyanCavanaugh** [comment]
See also #7488
