### ISSUE TITLE
Edit npm / node_modules typings for a package?

### ISSUE THREAD

**Issue by johhansantana** [Microsoft/TypeScript#18446]
Hello

I'm trying to update some typings in my projects that comes directly from an npm package that's installed.

However, I'm not sure how could I just ignore the typings that comes with the package and use my own or at least be able to edit it.

Reason:
Using [zeit nextjs](https://github.com/zeit/next.js/) I'm unable to use most of the time a regular es6 import like so:
`import enUS from 'antd/lib/locale-provider/en_US'` **when using typescript**

I have to convert this to be like:
`import * as enUS from 'antd/lib/locale-provider/en_US'`

But doing so, sometimes typescript is not happy about it like in here:
![image](https://user-images.githubusercontent.com/9933887/30395324-bfb7b70c-9893-11e7-9bd0-3d295dd3b32e.png)

How can I fix this?

**Comment by johhansantana** [comment]
I was able to fix this https://github.com/zeit/next.js/issues/2947

I still would like an answer about using own typings for installed packages but I guess this is best to ask in stackoverflow.

**Comment by weswigham** [comment]
You can make your own `@types/packagename` style package and in your package.json, instead of using a version number for the package, use a local or repo path to the package. NPM is real nifty.
