### ISSUE TITLE
Add downlevel and typing support for const enum members in computed properties

### ISSUE THREAD

**Issue by JsonFreeman** [Microsoft/TypeScript#1844]
```ts
const enum E {
    x
}

var v = {
    [E.x]: ""
};
```

There are two things we can do by taking advantage of our static knowledge of const enums. One is that we can downlevel this without using an element access:
```js
var v = {
    0: ""
};
```

Another is that we can know the type of v. Specifically, we know that it has a property named 0 of type string, which we would not know if this were not a const enum member.

**Comment by RyanCavanaugh** [comment]
Not terribly useful with numeric names. We should revisit this when we have string-based enums, where this would be more useful

**Comment by JsonFreeman** [comment]
It is useful if you do not care about what number the name evaluates to, and you just want to think of the property as being keyed by the enum member itself, much like a property keyed by a symbol.

**Comment by danquirk** [comment]
Tagging #1206 so we actually can maybe revisit this
