### ISSUE TITLE
Unnecessary variable rename for destructuring in for-of

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#18443]
**TypeScript Version:**  nightly (2.6.0-dev.20170913)

**Code**

```ts
const x = 0;
const o = { x };

function f() {
    const { x } = o;
}

function g() {
    for (const { x } of [o]) {}
}
```

**Expected behavior:**

```js
var x = 0;
var o = { x: x };
function f() {
    var x = o.x;
}
function g() {
    for (var _i = 0, _a = [o]; _i < _a.length; _i++) {
        var x = _a[_i].x;
    }
}
```

**Actual behavior:**

```js

var x = 0;
var o = { x: x };
function f() {
    var x = o.x;
}
function g() {
    for (var _i = 0, _a = [o]; _i < _a.length; _i++) {
        var x_1 = _a[_i].x; // This line renames `x` unnecessarily
    }
}
```

**Comment by vladima** [comment]
This was a deliberate design decision to conservatively rename block scoped locals that reside in non-top level scope.  Renaming is necessary to prevent cases like this:
```ts
let f;
{
    const x = 1;
    f = () => x;
}
{
    const x = 500;
}
console.log(f()); // should print 1, not 500
```
More precise behavior would require ability to answer the question: does another block scoped local with the same name exists anywhere in non-top-level scope and the cost of providing this answer was considered too high to proceed.

**Comment by andy-ms** [comment]
Thanks -- I assume by "top-level" you mean function scope, otherwise I would expect a rename in both cases.
