### ISSUE TITLE
Code fixes adding carriage returns to LF documents

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#18445]
Code fixes are generating files with mixed LF and CRLF line endings. See:
* `codeFixAddMissingMember5`
* `codeFixAddMissingMember7`
* `codeFixSuperAfterThis`
* `codeFixSuperCall`
* `importNameCodeFix*` (see comment in `fourslash.ts` tagged `GH#18445`)

**Comment by amcasey** [comment]
Do we know if this issue is test-only?  That is, have we seen the product produce inconsistent line endings?

**Comment by amcasey** [comment]
In `importNameCodeFixNewImportFile3.ts`, for instance, the test explicitly expects `\n` and the host explicitly provides `\r\n`.  Is this bug just asking that we change the value used in the host during fourslash tests?

**Comment by andy-ms** [comment]
The settings should be specifying `\n` though. May be due to #18291.

**Comment by amcasey** [comment]
When I debugged, it was getting the newline string from the host.  It sounds like that may indeed be the issue, but it also sounds like that would only affect the tests since normally the refactoring options and the host would agree, no?

**Comment by andy-ms** [comment]
We were looking at this earlier today and it seemed to work, but it looks like vscode's formatting settings are not making it through to "getEditsForRefactor" requests -- waiting on a fix for #18328 before we can test this out.
