### ISSUE TITLE
Inline local refactoring

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#18459]
**Proposal**
Add a refactoring to inline a local variable. Example:

```ts
function generatePipeName(): string {
	const hexString = makeRandomHexString(40);
	return getPipeName(hexString);
}
```

The `Inline local` refactoring on `hexString` would result in:

```ts
function generatePipeName(): string {
	return getPipeName(makeRandomHexString(40));
}
```

**Comment by D0nGiovanni** [comment]
I've been working on this issue for a while now, but I'm not too familiar with the compiler API. Is there a way to dynamically generate a new node based on the SyntaxKind of another? I'm concerned that if I just make a copy, the id will stay the same and that would lead to problems down the road.

**Comment by weswigham** [comment]
Ah, just means we're considering it for inclusion. Everything that's labeled as a "Suggestion" is supposed to have one of a set of sublabels indicative of the issue's state. I felt that was probably most correct here (it's not "committed" because we've not allocated anyone to work on it).

**Comment by jackric** [comment]
Anyone suggest a VSCode extension that does this in lieu of waiting for official support?

**Comment by OliverJAsh** [comment]
> Anyone suggest a VSCode extension that does this in lieu of waiting for official support?

https://github.com/nicoespeon/abracadabra#inline-variable

**Comment by tylerlaprade** [comment]
Thanks @MariaSolOs for the fix! Will the documentation be updated to match?
