### ISSUE TITLE
Quickinfo on destructuring is wrong.

### ISSUE THREAD

**Issue by paulvanbrenk** [Microsoft/TypeScript#1845]
Consider the following code:

		var robotA = { name: "Bender" };

		var { name: nameA } = robotA;

Hover over `name` in the bottom line, notice quickinfo show this as `any`, I think we should suppress quickinfo in this case.

![untitled](https://cloud.githubusercontent.com/assets/5273975/5950790/6ba2871a-a713-11e4-9ddf-32828884ec9e.png)

**Comment by sheetalkamat** [comment]
Fixed with 62bc9df89952e7a035a3d6248b4b018e83cc699c
