### ISSUE TITLE
Surround with refactoring

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#18458]
**Proposal**
Add a refactoring that can surround a statement with a try/catch block or potentially other blocks

For example:

```ts
class Ranger {
    rick(count: number, precision: number) {
        let result = 'r'
        for (let i = 0; i < count; ++i) 
            result += i.toPrecision(precision)
        return result
    }
}
new Ranger().rick(2, -1)
```

if a user selects the `for` block and did a `surround with try/catch` refactoring, the result would be:

```ts
class Ranger {
    rick(count: number, precision: number) {
        let result = 'r'
        try {
            for (let i = 0; i < count; ++i)
                result += i.toPrecision(precision)
        } catch (e) {

        }
        return result
    }
}
new Ranger().rick(2, -1)
```

**Comment by drake7707** [comment]
In the above example i would add "throw e;" in the catch block to have the same behaviour until the user changes it, but yes, the "try" and "tryf" snippets would be very handy.

**Comment by amcasey** [comment]
This seems to already work in VS via the `Edit.SurroundWith` command.  As far as I can tell, it's part of snippet support.

**Comment by mhegazy** [comment]
@mjbvz can you get the same support in VSCode just with snippets? if not what is missing?

**Comment by mjbvz** [comment]
Yes, we could use snippets. Are there any smarts that surround-with needs though? Example, for the code:

```js
let a = obj.throwException()
console.log(a)
```

Surround with on line 1 should generate:

```js
let a;
try {
    a = obj.throwException();
} catch (e) {
     
}
console.log(a)
```

**Comment by mhegazy** [comment]
no, but that seems to not have been an issue with VS users.
