### ISSUE TITLE
'type definition only import' transpiled to js

### ISSUE THREAD

**Issue by svenefftinge** [Microsoft/TypeScript#18468]
**TypeScript Version:**  2.4.2

**Code**

```ts
import * as tsp from "typescript/lib/protocol";

export function foo() : string {
    return tsp.CommandTypes.Brace;
}
```

**Expected behavior:**
The resulting JS should not contain 
```js
const tsp = require("typescript/lib/protocol");
```

**Actual behavior:**
but it does.

**Comment by kitsonk** [comment]
You are not using `tsp` in a value position, so it does not get erased.  Those definitions are not UMD definitions, they are global definitions.  They should not be imported into a module.  If you need to use them, it should just be in the scope of the compiler, so in your `tsconfig.json` `"include"` or as a triple slash ref.

**Comment by svenefftinge** [comment]
Yes, it is a value position but, there are no references in the generated js, as the string values from the enum are inlined. Shouldn't that be detected by the compiler?

**Comment by kitsonk** [comment]
```
$ cat test.ts
import * as tsp from "typescript/lib/protocol";

export function foo() : string {
    return tsp.CommandTypes.Brace;
}

$ tsc test.ts
test.ts(4,12): error TS2708: Cannot use namespace 'tsp' as a value.
$ tsc --version
Version 2.4.2
```

It is even telling you, you got a problem.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
