### ISSUE TITLE
typeof with extended generic class

### ISSUE THREAD

**Issue by rzcoder** [Microsoft/TypeScript#18465]
**TypeScript Version:**  2.4.0+

**Code**

```ts
interface AP {
    id: string;
}

class A<T extends AP = AP> {
    foo(a: T) { }
}

interface BP extends AP {
    n: number;
}

class B<T extends BP = BP> extends A<T> {
}

let y: typeof A;
y = B; // <<<
```

**Expected behavior:**
No errors.

**Actual behavior:**
Error in ts 2.4+ (in 2.3.4 no errors)
```
Type 'typeof B' is not assignable to type 'typeof A'.
  Type 'B<BP>' is not assignable to type 'A<T>'.
    Types of property 'foo' are incompatible.
      Type '(a: BP) => void' is not assignable to type '(a: T) => void'.
        Types of parameters 'a' and 'a' are incompatible.
          Type 'T' is not assignable to type 'BP'.
            Type 'AP' is not assignable to type 'BP'.
              Property 'n' is missing in type 'AP'.
```

**Comment by mhegazy** [comment]
looks like the same issue as https://github.com/Microsoft/TypeScript/issues/18387. please see https://github.com/Microsoft/TypeScript/issues/18387#issuecomment-328611169

**Comment by rzcoder** [comment]
so, you mean this behaviour correct?

**Comment by mhegazy** [comment]
> @mhegazy so, you mean this behavior is correct?

yes. it is unsafe to substitute a generic constructor with one that is not generic in the general case. you can either change your base class, to be non-generic, or use `--noStrictGenerics` to suppress the error.

**Comment by rzcoder** [comment]
So, in this case you just can't extend React component in that simple way. Pretty common scenario but ts failed, ok :(

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
