### ISSUE TITLE
Constraining generics by compatible property types

### ISSUE THREAD

**Issue by abdulkareemnalband** [Microsoft/TypeScript#18467]
[StackOverflow question for this](https://stackoverflow.com/q/46220347/1859367)
**TypeScript Version:**  2.5.2 

Allow Constraining Generic types generically (Something similar to C++ concepts)

Suppose we want to make sure that type of two distinct properties of objects of distinct type are same 

```ts
function compareAndUpdate<T, S , TK extends keyof T , SK extends  keyof S > -> typeof T[TK] ===
 typeof S[SK](target: T, source: S, targrtKey:TK , sourceKey:SK): boolean {
    // some processing
    target[targrtKey] = source[sourceKey]; // this line gives error 

    // some more processing

}
```
The syntax  could be extending generics declaration where

```
<<generic declaration>> -> <generic constraint boolean expression>
```

operator `->` denotes constraints ahead
Examples 
```ts
// function 
function compareAndUpdate<T, S , TK extends keyof T , SK extends  keyof S > -> typeof T[TK] ===
 typeof S[SK](target: T, source: S, targrtKey:TK , sourceKey:SK): boolean;

//method
private  compareAndUpdate<T, S , TK extends keyof T , SK extends  keyof S > -> typeof T[TK] !==
 typeof S[SK](target: T, source: S, targrtKey:TK , sourceKey:SK): boolean;

//interface
interface Foo<T , U> -> baseof T === baseof U {
// interface members
// here baseof is hypothetical operator  
}

//class
class Bar<T , U> -> baseof T !== baseof U  implements Foo<T,U> {
// class members
// here baseof is hypothetical operator  
}
// this should fail because of conflicting constaints
```

**Comment by abdulkareemnalband** [comment]
My immediate requirement was solved by [this answer in stackoverflow](https://stackoverflow.com/a/46221474/1859367)

I still think it is better to have constraint on generics

If this thing doesn't make sense then maintainers can close this issue

**Comment by mhegazy** [comment]
The SO answer by @jcalz is what i would have recommend. Many of these issues are addressed by writing your generic types in a way that captures the type you want to check for, instead of capturing two unrelated types and then needed to compare something about them.

**Comment by mhegazy** [comment]
I should add that this is the design approach we chose to limit complexity to the language.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
