### ISSUE TITLE
"use strict" in a class

### ISSUE THREAD

**Issue by nycdotnet** [Microsoft/TypeScript#1847]
Hi,
When targeting ES5 and using `--noImplicitAny`, the following is a type error:

```typescript
class foo {
    "use strict";
}
```

Variable '"use strict"' implicitly has an 'any' type.

Why is this a type error?  TypeScript seems to handle `"use strict";` within function scopes, including the class constructor.  However, allowing "use strict" as the first line in the class would allow the entire emitted IIFE to work in strict mode.  As it is today, this "use strict"; is erased by the compiler.

As a side issue, I searched the TypeScript 1.4 language spec doc and "use strict" does not occur in it.

Thanks!

**Comment by RyanCavanaugh** [comment]
This defines a class with a member named `use strict` (see the emitted code when you give it an initializer, e.g. `'use strict' = 4;`).

"use strict" in a class isn't supported; you can put this at a module or file level instead. ES6 classes are strict by default so I don't think we'd bother plumbing in a special case for downlevel emit here.

**Comment by nycdotnet** [comment]
Thanks.  Module or file level it is.
