### ISSUE TITLE
// @ts-check complains about this.constructor.properties not existing

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#18477]
_From @kenchris on September 14, 2017 13:28_

 ie. ```[js] Property 'properties' does not exist on type 'Function'.```

Though this code works fine

```
constructor() {
    super();
 
    for (const prop in this.constructor.properties) {
      const symbol = Symbol.for(prop);
      const { type: typeFn, value, reflectToAttribute } = this.constructor.properties[prop];

      Object.defineProperty(this, prop, {
        get() { return this[symbol] || value; },
        set(v) {
          let value = typeFn(v)
          this[symbol] = value;
          if (reflectToAttribute) {
            if (typeFn.name === 'Boolean') {
              if (!value) {
                this.removeAttribute(prop);  
              } else {
                this.setAttribute(prop, prop);
              }
         ...
```

_Copied from original issue: Microsoft/vscode#34378_

**Comment by mjbvz** [comment]
@kenchris How is `constructor.properties` being set in the first place? Can you provide a minimal, complete example class that demonstrates this problem?

**Comment by weswigham** [comment]
We do not presently strongly type `.constructor` - see discussion in #3841

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
