### ISSUE TITLE
exclude not working for subdirectories

### ISSUE THREAD

**Issue by kyeotic** [microsoft/TypeScript#18472]
**TypeScript Version:** 2.5.2

**Code**

```ts
{
  "compilerOptions": {
    "outDir": "dist",
    "allowJs": true,
    "target": "es2017",
    "module": "commonjs",
    "sourceMap": false,
    "alwaysStrict": true
  },
  "include": [
    "src/**/*"
  ],
  "exclude": [
    "templates/**" //or "**/templates/**" or "**/templates"
  ]
}
```

**Expected behavior:**

All directories with `templates` in them are excluded

**Actual behavior:**

They are not excluded.

```
// Example error, there are hundreds of these
src/plugins/lambdaApiNode/templates/api.js(31,10): error TS1109: Expression expected.
```

![image](https://user-images.githubusercontent.com/1187432/30445036-aa4888fa-9939-11e7-9db2-32799d7767b3.png)

**Comment by mhegazy** [comment]
`"**/templates/*"` should work.

**Comment by mhegazy** [comment]
you should not need the trailing `/*` though. that is a bug that needs to be addressed.

**Comment by tyrsius** [comment]
Yea that worked, but that doesn't fit with the documentation that `/*` does not match directory separators. There are files in `templates/someDir/file.js` that are getting excluded by `"**/templates/*"`, which seems like _another_ bug.

**Comment by andreujuanc** [comment]
Excluding "**/*.ts" or "**/**/*.ts"  does not work.. So excluding a whole directory tree wont work either.
