### ISSUE TITLE
Add Screen.orientation

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#18480]
_From @kenchris on September 14, 2017 13:42_

```[js] Property 'orientation' does not exist on type 'Screen'. Did you mean 'msOrientation'?```

Though screen.orientation is what Chrome uses

```  mat4.rotateZ(this.rotationMatrix, this.rotationMatrix, toRad(window.screen.orientation.angle || 0));```

_Copied from original issue: Microsoft/vscode#34381_

**Comment by mhegazy** [comment]
Documentation in https://developer.mozilla.org/en-US/docs/Web/API/Screen/orientation

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by kenchris** [comment]
PR here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/19779

**Comment by SaschaNaz** [comment]
The PR is merged :+1: (That was super quick.)

**Comment by SaschaNaz** [comment]
:+1: but I think it can be on TSJS-lib-generator itself.

**Comment by neo** [comment]
I think it's because it's still a draft.

**Comment by SaschaNaz** [comment]
lib.d.ts recently added several new types which are still in Working Draft status, I think the policy has been slightly changed in undocumented way.

**Comment by mhegazy** [comment]
We have found it hard for users to add the types in DT then include them later on in the default library. generates a lot of churn when we include them in the library.

For a north star, we should break up the dom into features, and let ppl opt-in experimental parts, and only include standards by default. this would be enabled by we [library references](https://github.com/Microsoft/TypeScript/pull/15780).

**Comment by saschanaz** [comment]
Both Firefox and Chrome has implemented the standard `screen.orientation` so IMO it can be in TS.
