### ISSUE TITLE
Initializing a binding by using an object literal property access should fail typecheck if TS cannot determine the resulting types match

### ISSUE THREAD

**Issue by theseyi** [Microsoft/TypeScript#18485]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
interface IRelation {
  items: Array<number>;
  mapper: () => void;
  title: string;
}

const prop = "invalidKey";

const relation: IRelation = {
  validKey: {
    items: [],
    mapper: () => { },
    title: "title"
  }
}[prop] || {};
```

**Expected behavior:**
Error: TS2322:Type '{}' is not assignable to type 'IRelation'.

**Actual behavior:**
Passes type checker

**Comment by mhegazy** [comment]
use `--noImplcitAny` to flag these accesses.

All js objects can be indexed by a string. if the compiler does not know the type of the output it will give them `any` type. `--noImplcitAny` flags these as errors.

**Comment by theseyi** [comment]
@mhegazy I already have that in my tsconfig.
`"noImplicitAny": true`, but just noticed I had `   "suppressImplicitAnyIndexErrors": true,` as well

**Comment by theseyi** [comment]
thanks
