### ISSUE TITLE
 Add definition for `Navigator.bluetooth` 

### ISSUE THREAD

**Issue by mhegazy** [microsoft/TypeScript#18481]
Documentation in https://developer.mozilla.org/en-US/docs/Web/API/Bluetooth/requestDevice

**Comment by mhegazy** [comment]
reported originally in https://github.com/Microsoft/TSJS-lib-generator/issues/294

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by RyanCavanaugh** [comment]
Assuming this is fixed or irrelevant. Please file a new issue using the lib template
