### ISSUE TITLE
Quick fix suggests corrections for wrong identifier when encountering overlapping error spans

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#18487]
```ts
function f(x, y) {

}

var hello

f(/**/helol)
```

**Repro**

1. Place cursor at the marker (`/**/`)
2. Request a quick fix for the typo `helol -> hello`

**Expected**: Quick fix is titled `Change spelling to 'hello'`, and renames `helol` to `hello.

**Actual**: Quick fix is titled `Change spelling to 'f'`, and does nothing.

![image](https://user-images.githubusercontent.com/972891/30456920-62928e90-995a-11e7-88ce-8fc689b3f161.png)

**Comment by mhegazy** [comment]
seems like a duplicate of https://github.com/Microsoft/TypeScript/issues/16205

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
