### ISSUE TITLE
Cannot resolve typings included in npm package when using "moduleResolution": "classic"

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#18492]
From https://github.com/Microsoft/vscode/issues/34346

**TypeScript Version:**  2.5.2

**Code**
In a new project

```
$ npm init -y
$ npm install axios
```

```ts
import axios from 'axios';
```

```json
{
    "compilerOptions": {
        "strict": true,
        "module": "amd",
        "moduleResolution": "classic"
    }
}
```

**Expected behavior:**
`axios` includes its own typings so these should be used for the import

**Actual behavior:**
Module `axios` cannot be resolved. 

`"moduleResolution": "node"` fixes the problem

**Comment by mhegazy** [comment]
that is by design. do not use `classic` unless you have to. the reason it is there is purely back compat.

**Comment by mjbvz** [comment]
Ok, is there a way to work around this without changing the resolution to `node`?

**Comment by mhegazy** [comment]
add a path mapping entry for module imports.

**Comment by mjbvz** [comment]
Thanks @mhegazy! I'll follow up with the user who opened this bug back on the vscode repo
