### ISSUE TITLE
Lib.d.ts should define overrides of `valueOf` for String, Number and Boolean

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/TypeScript#1849]
Hi,

**TS**: 1.4

The compiler issues error "Type 'Object' is not assignable to type 'string'" for the following:

```TypeScript
var f: string = new String('foo').valueOf();
```

This is because `valueOf` resolves to the definition on `Object` rather than `String` - which is currently missing.

According to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/valueOf):

> By default, the valueOf method is inherited by every object descended from Object. Every built-in core object overrides this method to return an appropriate value.

Is there any reason why `valueOf` is missing in the definitions for `String`, `Number` and `Boolean`? (The `Date` type seems to have one defined.)

Related issues:
#1387

**Edit**:

I understand that we want to suppress the display of the standard methods:

```TypeScript
    toString(): string;
    toLocaleString(): string;
    valueOf(): Object;
    hasOwnProperty(v: string): boolean;
    isPrototypeOf(v: Object): boolean;
    propertyIsEnumerable(v: string): boolean;
```

But unlike the other methods the return value of `valueOf` is specific to the type.

**Comment by mhegazy** [comment]
A PR would be appreciated.
