### ISSUE TITLE
Type narrowing for Union Types with instanceof

### ISSUE THREAD

**Issue by gamli** [Microsoft/TypeScript#18498]
**TypeScript Version:**  2.4.0 

**Code**

```ts
class Bird {
   fly() {
   }
}

class Fish {
   swim() {
   }
}

function moveAnimal(animal: Bird | Fish) {
   if (animal instanceof Bird) {
      // type is narrowed down to Bird => OK
      animal.fly();
   } else {
      // type is narrowed down to Fish => WRONG
      animal.swim();
   }
}

moveAnimal(
   {
      fly() {
      }
   });
```

**Expected behavior:**
Parameter `animal` should still be of type `Bird | Fish` in the `else` case.

**Actual behavior:**
Type is narrowed to `Fish` which leads to an error if called with a parameter of a type that is structurally compatible with `Bird | Fish` but is neither an instance of the `Bird` or `Fish` class. This seems to be related to some other issues related to the nominal typing of `instanceof` in combination with TypeScript's structural typing.

**Comment by RyanCavanaugh** [comment]
You can add a private field to each class to prevent this.

In general people either fall into the camp of "Only use `new` and `instanceof` works" *or* "Sometimes use object literals and don't use `instanceof`". We don't have syntax for determining which camp you want to be in for each particular class and don't intend to add it.

**Comment by gamli** [comment]
Is a special syntax even necessary? The `animal` parameter could be left as `Bird | Fish` in the `else` case. According to #1719 this should already be the case (until it changed since version 1.4).

**Comment by RyanCavanaugh** [comment]
Nearly everyone would consider that behavior to be a bug. Evidence from the linked issue is that no code in the real world does an `instanceof` check and then *doesn't* assume the other member of the union in the `else` branch

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
