### ISSUE TITLE
Unexported types from "global files" visible with isolatedModules enabled

### ISSUE THREAD

**Issue by davetemplin** [Microsoft/TypeScript#18504]
**TypeScript Version:**  2.4.2

**tsconfig.json**
```json
{
  "compilerOptions": {    
    "isolatedModules": true
  }
}
```

**a.ts**
```ts
import {b1} from './b';
console.log(b1()); // NO ERROR (as expected)
console.log(b2()); // ERROR (as expected)
console.log(c1()); // NO ERROR (an error is expected here)
```

**b.ts**
```ts
export function b1() {
    return 'b1';
}

function b2() {
    return 'b2';
}
```

**c.ts**
```ts
function c1() {
    return 'c1';
}
```

**Expected behavior:**
Referring to `c1` from `a.ts` should be an error.

**Actual behavior:**
No error regarding `c1` in `a.ts`.

**Comment**
From the description of `--isolatedModules` "transpile each file as a separate module" I do not expect types from any file to be visible that I haven't explicitly imported (unless they're coming in through `compilerOptions.types` or something like that). I get it with `--isolatedModules` the disposition of `c1.ts` is basically completely invalid. However, this behavior is very confusing particularly when migrating code bases where there might be a lot of code laying around that hasn't been refactored yet.

Is the unexpected behavior coming from the old internal module system?

**Comment by davetemplin** [comment]
By the way also seeing a lot of `error TS2393: Duplicate function implementation.` errors caused by using the same function name in multiple files, which shouldn't be a problem if the expectation is that each file is completely isolated from each other.

**Comment by mhegazy** [comment]
That is not the intention of this flag. the flag ensures that each file can be transpiled in isolation. i.e. the behavior of the emit does not depend on having full program. an example of that is `const enum`s, whose element values are inlined at use sites.

I think you are looking for https://github.com/Microsoft/TypeScript/issues/18232 instead.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
