### ISSUE TITLE
"SOURCE"

### ISSUE THREAD

**Issue by BobFrGit** [Microsoft/TypeScript#1850]
All HTML elements in lib.d.ts are lower case except for SOURCE which is upper case. Is there a reason for this. At a more general level these interfaces appear to be case insensitive -- the language needs a way of saying that.

**Comment by mhegazy** [comment]
"SOURCE" we should be able to fix by updating our dom generation logic. the case sensitivity is a bigger issue. JS is case sensitive, yet the DOM is not. Suggestions are welcomed though.
