### ISSUE TITLE
Feature request: Fat arrow (Expression-bodied members) for single expression methods, constructor, getter and setter

### ISSUE THREAD

**Issue by cyrilgandon** [Microsoft/TypeScript#18500]
Similar to what C# allows with [Expression-bodied members](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/expression-bodied-members).

This request already exists for getter and setter here: [#4491 - Suggestion: getters and setters with lambda syntax ](https://github.com/Microsoft/TypeScript/issues/4491). It has been closed for too-complex and too few added value  the 27th August 2015, 2 years ago. Let's refresh the subject!

This request extends the initial one for constructor and methods. 
It follows the functional programming paradigm to favor one expression body.

It doesn't looks like to add a lot to the langage, and I think there was some doubt on it when it come to C#. But now that Expression-bodied members exists in C#, everybody loves them.

[A quote from Jon Skeet from in his blog](https://codeblog.jonskeet.uk/category/cs6/)

>I’d expected to like this feature (Expression-bodied members)… but I hadn’t expected to fall in love with it quite as much as I’ve done. It’s really simple to describe – if you’ve got a read-only property, or a method or operator, and the body is just a single return statement (or any other simple statement for a void method), you can use => to express that instead of putting the body in braces. It’s worth noting that this is not a lambda expression, nor is the compiler converting anything to delegates – it’s just a different way of expressing the same thing.

[...]

>So what’s the benefit of this? Why do I like it? It makes the code feel more functional. It makes it really clear which methods are just shorthand for some other expression, and which really do involve a series of steps. It’s far too early to claim that this improves the quality of the code or the API, but it definitely feels nice. One interesting data point – using this has removed about half of the return statements across the whole of the NodaTime production assembly. Yup, we’ve got a lot of properties which just delegate to something else – particularly in the core types like LocalDate and LocalTime.

**Example**

```ts
class Location {
    private locationName: string;

    // Constructor
    constructor(name: string) => this.locationName = name;

    // Getter
    get name() => this.locationName;

    // Setter
    set name(value : string) => this.locationName = value;

    // Method
    getName() => this.name;
}
```

The current syntax for this code is
```ts
class Location {
    private locationName: string;

    // Constructor
    constructor(name: string) {
        this.locationName = name;
    }

    // Getter
    get name(): string {
        return this.locationName;
    }

    // Setter
    set name(value: string) {
        this.locationName = value;
    }

    // Method
    getName() {
        return this.name;
    }
}
```

**Comment by mhegazy** [comment]
We have shied away from adding new expression level syntax to avoid colliding with future ES features. We see TypeScript as a superset of JavaScript, and that can not be true if JS uses the same syntax for different meaning.

For feature suggestions like this we recommend you take them to [TC39](https://github.com/tc39/proposals). TypeScript is committed to trailing the committee on any features that reach stage 3 or above.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
