### ISSUE TITLE
Decorator metadata breaking change between TS 2.3.4 -> 2.4.0

### ISSUE THREAD

**Issue by flushentitypacket** [Microsoft/TypeScript#18509]
I couldn't find any documentation on this breaking change between TS 2.3.4 and TS 2.4.0.

I'm not sure whether this is a bug or simply an undocumented change. I suspect the latter--in which case my suggestion is to add documentation regarding that change.

**TypeScript Version:**  >= 2.4.0

Ran tsc with flags --experimentalDecorators --emitDecoratorMetadata.

Using reflect-metadata v0.1.10

**Code**

```ts
import 'reflect-metadata'

const dec = (obj: {}, prop: string) => undefined

class Foo {
  @dec public foo: string | null // seems to happen with any complex type
  @dec public bar: string
}

console.log(Reflect.getMetadata('design:type', Foo.prototype, 'foo'))
console.log(Reflect.getMetadata('design:type', Foo.prototype, 'bar'))
```

**Expected behavior:**

output in 2.3.4:

```
[Function: String]
[Function: String]
```

**Actual behavior:**

output in 2.4.0:

```
[Function: Object]
[Function: String]
```

**Comment by awendland** [comment]
Related to #9916 but different because #9916 is a feature request while this is a request to change back to previous behavior, or at least document the breaking change. Is there test coverage in the TS project for metadata like this?

**Comment by awendland** [comment]
Running `git tag --contains 0eaa8eb3ab9ad1db8cf95c51d8e02c9d65ee40cf` reports v2.4-rc, v2.4.0, v2.4.1, v2.4.2, v2.5-rc, v2.5.0, v2.5.1, and v2.5.2 as the tags containing the commit.

**Comment by ulrichb** [comment]
Hmmm. Using the current TS 2.8.3 and still see this issue. Can someone confirm this?

**Comment by weswigham** [comment]
Do you have `strictNullChecks` on?

**Comment by ulrichb** [comment]
Yes.

BTW, this works: `@myDec() public PropN?: boolean;`

The following doesn't work:

`@myDec() public PropN: boolean | undefined;`

or

`@myDec() public PropN: boolean | null = null;`

**Comment by weswigham** [comment]
Yeah, if you read the linked fix PR - #19089 - this is the expected behavior under `strictNullChecks`, as a `number | undefined` isn't just a `Number` - it's a `Number` or `undefined` (which there's no corresponding way to emit metadata for). We don't emit metadata for nonhomogenous unions, as decorator metadata is syntactic, and emit the base `Object` instead.

**Comment by ulrichb** [comment]
Okay, this was a misunderstanding. I thought this also concerns strict checking. Thanks for clarification.

**Comment by mhegazy** [comment]
We have no plans to implement a full run-time type serialization system akin to reflection C# or Java (more in https://github.com/Microsoft/TypeScript/issues/3628). The meta-data emit, continues to be an experimental feature tied to decorators, and has a very limited scope (i.e. classes and primitives). we have no plans to expand that scope either.

**Comment by ulrichb** [comment]
@mhegazy Thanks for clarification.
