### ISSUE TITLE
instanceof should error when all constituents of a union are primitives

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#18519]
```ts
function foo(x: number | string) {
    if (x instanceof Number) {
        x
    }
}
```

Expected:

```
The left-hand side of an 'instanceof' expression must be of type 'any', an object type or a type parameter
```

Actual:

No error, incorrect narrowing behavior (#14426)

**Edit:** Corrected the example to *actually* be a union.

**Comment by ajafff** [comment]
That's not always the expected behavior. When targeting a runtime with `Symbol.hasInstance` this should be allowed:
```ts
class PrimitiveNumber {
    static [Symbol.hasInstance](x) {
        return typeof x === 'number';
    }
}
console.log(123 instanceof PrimitiveNumber); // true
```

**Comment by DanielRosenwasser** [comment]
Sure, but

1. Most people aren't doing that.
2. We already error for `10 instanceof Number`

**Comment by aluanhaddad** [comment]
Wouldn't an appropriate behavior then be to issue an error unless the value on the right hand side has a `[Symbol.hasInstance]` member taking a parameter of a type to which the type of value on the left hand side is assignable?

**Comment by DanielRosenwasser** [comment]
Something like #17360?

**Comment by charlespierce** [comment]
PR #19063 opend to resolve this issue.
