### ISSUE TITLE
Type inference doesn't work when indexing a generic type

### ISSUE THREAD

**Issue by sb3700** [Microsoft/TypeScript#18510]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

**Code**

```ts
enum CFieldType {
  NUMBER,
  TEXT,
};
class CTextValue {
  fieldType: CFieldType.TEXT;
  value: string;
}
class CNumberValue {
  fieldType: CFieldType.NUMBER;
  score: number;
}
type CValue = CTextValue | CNumberValue;

class Aggregate<V extends CValue> {
  test(fieldType: V['fieldType']): string {
    return CFieldType[fieldType];
  }
}
```
(In TS playground: https://goo.gl/hctJPv)

**Expected behavior:**
In the test method, fieldType should have type CFieldType.

**Actual behavior:**
In the test method, fieldType has type CFieldType Value["fieldType"].

This causes an error:
Type 'V["fieldType"]' cannot be used to index type 'typeof CFieldType'.

**Comment by mhegazy** [comment]
Do not see any errors on latest.

**Comment by sb3700** [comment]
Can confirm, it looks fixed in 2.6, still broken in 2.5

$ tsc -v
Version 2.5.2

$ tsc ts-repro.ts 
ts-repro.ts(17,12): error TS2536: Type 'V["fieldType"]' cannot be used to index type 'typeof CFieldType'.

$ npm install -g typescript@next

$ tsc -v
Version 2.6.0-dev.20170916

$ tsc ts-repro.ts 
<no error>

**Comment by sb3700** [comment]
It can also be reproduced in TS playground https://goo.gl/hctJPv

**Comment by mhegazy** [comment]
Playground is still on 2.5
