### ISSUE TITLE
module resolution regression

### ISSUE THREAD

**Issue by ZoneRunner** [Microsoft/TypeScript#18528]
**TypeScript Version:**  2.5.2

**Code**
I have created the following basic folder structure:
```
ts
|----@types
|    |----declarations.d.ts
|
|----node_modules
|    |----foobar.ts
|    |----main.ts
|
|----tsconfig.json
```

```ts
// declarations.d.ts
declare module "testing"
{
    function test(string: string): string;
}
```
```ts
// foobar.ts
export const something = "test";
```
```ts
// main.ts
import {test} from "testing";
import {something} from "foobar";

export const result = test(something);
```
```ts
// tsconfig.json
{
    "compilerOptions": {
        "module": "commonjs",
        "alwaysStrict": true,
        "declaration": true,
        "moduleResolution": "node",
        "noImplicitAny": true,
        "strictNullChecks": true,
        "outDir": "../build/"
    },
    
    "include": ["**/*"],
    "exclude": []
}
```

**Expected behavior:**
This is pretty exotic but it should compile without errors and create javascript files and definition files. It works exactly like that with TypeScript version 2.4.2.

**Actual behavior:**
It does not create any output at all. It looks like the reason is that the node_modules directory gets excluded. Using a more specific include fixes the problem:
```
"include": ["./node_modules/**/*"]
```
However, now it cannot find the module definition for "testing". Shouldn't all definitions in @types be included by default? 
Using an even more specific include fixes this problem too:
```
"include": ["./@types/**/*", "./node_modules/**/*"]
```

I'm not sure if this is a bug or an intentional regression.

**Comment by mhegazy** [comment]
node_modules are excluded by default. if you want that to be included add an explicit include. so your solution to add it to `"include"` is correct.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
