### ISSUE TITLE
DOMStringMap is defined as an empty interface - this makes it awkward to use

### ISSUE THREAD

**Issue by sccolbert** [Microsoft/TypeScript#1852]
The `DOMStringMap` interface is defined as follows:

https://github.com/Microsoft/TypeScript/blob/master/src/lib/dom.generated.d.ts#L10556
```typescript
interface DOMStringMap {
}
declare var DOMStringMap: {
    prototype: DOMStringMap;
    new(): DOMStringMap;
}
```

This means it's a compile error to directly access the object properties, but it's also an `implicit any` error if the `--noImplicitAny` switch is turned on in the compiler. This makes using a node's `dataset` somewhat arduous since a cast is required.

I'm not sure if there is some way to declare that an object has arbitrary properties of some given type, but perhaps a minimal working solution would be to give this interface a string indexer:
```typescript
interface DOMStringMap {
  [key: string]: string;
}
```

**Comment by danquirk** [comment]
Seems like there are a few different methods on this type that aren't currently represented in the .d.ts: https://developer.mozilla.org/en-US/docs/Web/API/DOMStringMap. All of them would still be satisfied with that string indexer signature.

**Comment by SaschaNaz** [comment]
The methods described in MDN are not implemented in any of three major web browsers including Firefox.
