### ISSUE TITLE
need smarter behavior in emitDecoratorMetadata

### ISSUE THREAD

**Issue by Brooooooklyn** [Microsoft/TypeScript#18522]
**TypeScript Version:** 

2.5.2

**Code**

```ts
import 'reflect-metadata'

function foo (target, key) {
  console.log(Reflect.getMetadata('design:returntype', target, key))
}

class A {
  @foo
  decorator() {
    return 1
  }
}

```

**Expected behavior:**

log `Number`

**Actual behavior:**

log `undefined`

**Comment by HerringtonDarkholme** [comment]
Currently all JS output is type independent. TS only needs parsed AST to generate compiled JS. Thus metadata is available in transpilation only mode.

This proposal might be a breaking change.

**Comment by mhegazy** [comment]
As @HerringtonDarkholme noted this is the expected behavior. only explicitly specified types are serialized. doing anything different would break single file transpilation.
