### ISSUE TITLE
Type definition for EcKeyImportParams in lib.dom.d.ts is incorrect according to W3

### ISSUE THREAD

**Issue by Arlen22** [Microsoft/TypeScript#18524]
**TypeScript Version:**  2.5.2 (according to package.json in the directories above the offending file)

According to https://www.w3.org/TR/WebCryptoAPI/#dfn-EcKeyImportParams, the EcKeyImportParams inherits Algorithm, however in the `lib.dom.d.ts` file @ line 14022, `EcKeyImportParams` does not implement anything, which is incorrect and throws an error in Google Chrome 61 if it does not implement the "name" property from `Algorithm`

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.
