### ISSUE TITLE
CodeFixImports doesn't suggest to import from a file when this file is actually exported

### ISSUE THREAD

**Issue by DevoidCoding** [Microsoft/TypeScript#18525]
**TypeScript Version:**  2.5.2

**Code**
**index.ts**
```ts
export * from './MyClass';
var t = new MyClass();
```
**MyClass.ts**
```ts
export class MyClass { }
```

**Expected behavior:**
CodeFixImport should suggest to import 'MyClass' from the 'MyClass.ts' file.

**Actual behavior:**
No suggestion at all

**Comment by amcasey** [comment]
Looks like this works now (probably thanks to @andy-ms).  I suspect it's included in TS 2.6.2, but it'll be in 2.7 otherwise.
