### ISSUE TITLE
Support 'throw' expressions

### ISSUE THREAD

**Issue by brn** [microsoft/TypeScript#18535]
Support [proposal-throw-expressions](https://github.com/rbuckton/proposal-throw-expressions).  
 That proposal is now stage-1, but worth to implements for convenience and this proposal not break backward-compatibilities.

### Current

ts

```typescript
const errorThrowExp = () => { throw new Error('Error!'); }
function errorThrowFn(maybeTrue) {
  if (maybeTrue){ 
    return ...;
  } else {
    throw new Error('Error!');
  }
}
```

js

```javascript
const errorThrowExp = function() {throw new Error('Error!')}
function errorThrowFn(maybeTrue) {
  if (maybeTrue){ 
    return ...;
  } else {
    throw new Error('Error!');
  }
}
```

### Proposal

ts

```typescript
const errorThrower = () => throw new Error('Error!');
function errorThrowFn(maybeTrue: boolean) {
  return maybeTrue? ...: throw new Error('Error!');
}
```

js 

```javascript
const errorThrower = function() { throw new Error('Error!'); }
function errorThrowFn(maybeTrue: boolean) {
  return maybeTrue? ...: (function() { throw new Error('Error!') })();
}
```

**Comment by kitsonk** [comment]
Just to note, @rbuckton is closely aligned to the TypeScript team.  I highly suspect this proposal would be implemented when everyone is comfortable it is in a stable enough position.

**Comment by brn** [comment]
@kitsonk That make sense. 
So is this proposal premature?

**Comment by DanielRosenwasser** [comment]
> So is this proposal premature?

Nope, it's fine to track it here. Like @kitsonk said, @rbuckton is championing it and is part of our team, but we will need it to reach a later stage before adopting it in TypeScript.

For what it's worth, I'd be willing to bet he has a branch with an implementation of `throw`-expressions. 😄

**Comment by rbuckton** [comment]
https://github.com/Microsoft/TypeScript/tree/throwOperator?files=1

Currently it does not yet support unreachability checks at the expression level. Also, I am waiting for the next TC39 meeting to see if the proposal moves to Stage 2.

**Comment by brn** [comment]
@DanielRosenwasser @rbuckton 
I got it.
Thank you for the detailed explanation!

**Comment by rbuckton** [comment]
TypeScript's current stance is that we will not adopt a proposed JavaScript feature until it has reached Stage 3. Currently, Stage 3 for `throw` expressions is blocked from advancement due to overlap with the `do` expressions proposal.

**Comment by Yogu** [comment]
Ah, I see. Thanks, @rbuckton!

**Comment by luisfarzati** [comment]
This is now in stage 3 :)

**Comment by rbuckton** [comment]
No, this has not yet advanced to Stage 3.

**Comment by RyanCavanaugh** [comment]
Closing since there's nothing for us to do but wait for TC39
