### ISSUE TITLE
Possible mistake in relative modules detection

### ISSUE THREAD

**Issue by sameoldmadness** [Microsoft/TypeScript#18536]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

**Code**

```ts
declare module "b:button" {
    const value: any;
    export default value;
}
```

**Expected behavior:**

The code compiles.

**Actual behavior:**

Compiler throws an error: `Ambient module declaration cannot specify relative module name.`

**Context**

`b:button` here is not a path but rather a special syntax from [BEM](https://en.bem.info/) block. It's meant to be ignored by TypeScript and handled by a dedicated loader.

However, TypeScript thinks it is a relative module path. This happens because [`getRootLength`](https://github.com/Microsoft/TypeScript/blob/master/src/compiler/core.ts#L1524-L1550) function checks the path against Windows absolute path pattern (e.g. `'C:/Games'`).

So the question is whether this code in `getRootLength` is correct.

```js
if (path.charCodeAt(1) === CharacterCodes.colon) {
    if (path.charCodeAt(2) === CharacterCodes.slash) return 3;
    return 2;
}
```

And if it is not, would it be appropriate to update it like this.

```js
if (path.charCodeAt(1) === CharacterCodes.colon) {
    if (path.charCodeAt(2) === CharacterCodes.slash) return 3;
    return 0; // if no slash after colon, than it's not a path
}
```

**Comment by mhegazy** [comment]
PRs welcomed.

**Comment by mhegazy** [comment]
thanks @sameoldmadness!
