### ISSUE TITLE
Cant read property subscribe of undefined while implementing decorator

### ISSUE THREAD

**Issue by krischandra** [Microsoft/TypeScript#18532]
export function decorator(moduleName: any, message?: any) {
  return function (target: any, key: string, descriptor: any) {
    const original = descriptor.value;
    descriptor.value = function (...args) {
      // Before
      console.log(moduleName, target.constructor.name, 'Entering in', key, );
      let result = original.apply(this, args);

      // After
      console.log(moduleName, target.constructor.name, 'Leaving in', key, );
    }
    return descriptor;
  }
}
I am applying this on function with return type observable. My expectation is after entering and before leaving function should log on console. It is working fine for functions that has no .subscribe. 

For this function i a can log on console after entering and before leaving function. And then unexpectedly i am getting cant read property .subscribe of undefined. 

Please help.  

Thanks.

**Comment by kitsonk** [comment]
This is not a support forum.

Questions should be asked at [StackOverflow](http://stackoverflow.com/questions/ask?tags=typescript) or on [Gitter.im](https://gitter.im/Microsoft/TypeScript).

**Comment by Brooooooklyn** [comment]
because you haven't return the result that return from orignal function,
try this:

```ts
export function decorator(moduleName: any, message?: any) {
  return function (target: any, key: string, descriptor: any) {
    const original = descriptor.value;
    descriptor.value = function (...args) {
      // Before
      console.log(moduleName, target.constructor.name, 'Entering in', key, );
      let result = original.apply(this, args);

      // After
      console.log(moduleName, target.constructor.name, 'Leaving in', key, );
      return result;   // <---------  this line is important
    }
    return descriptor;
  }
}
```
