### ISSUE TITLE
No error on awaiting non-awaitable function

### ISSUE THREAD

**Issue by ZoolWay** [Microsoft/TypeScript#18542]
**TypeScript Version:**  2.5.2

**Code**

```ts
class Test {
  public async test(): Promise<void> {
    await test2();
  }
  public test2(): boolean {
    console.info('test2');
    return true;
  }
}
```

**Expected behavior:**
Compiler warning or error that `test2()` is not awaitable because it does not return a `Promise`.

**Actual behavior:**
No warning or error, compiles unnecessarily into an awaiter wrapped function.

**Comment by kitsonk** [comment]
Did you mean `await this.test2();`?

Even still, duplicate of #8310.

Search is [your friend](https://github.com/Microsoft/TypeScript/search?q=awaiting+a+non-promise+return&type=Issues&utf8=%E2%9C%93).

**Comment by ZoolWay** [comment]
Did a search but guess I just included open issues.

Nevertheless, thanks! As this is intended for the reasons meantioned in #8310 I look into linting to avoid this error.
