### ISSUE TITLE
New Website Logo: CUBA Platform

### ISSUE THREAD

**Issue by jreznot** [Microsoft/TypeScript#18543]
Hi! 
We use TypeScript for our library https://github.com/cuba-platform/cuba-rest-js

Please fill the following out:

- Name: CUBA Platform
- Homepage url: https://cuba-platform.com
- Brand Guidelines/Licensing: none
- Logo: 
![cuba-platform-logo](https://user-images.githubusercontent.com/1066152/30545606-2d143950-9c9b-11e7-87f4-13bc3f6b4c1b.png)

It would be great if you add our logo to Friends of TypeScript!

**Comment by mhegazy** [comment]
Should be up in the next day or so.
