### ISSUE TITLE
Extract-method with namespace declaration results in invalid code

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#18546]
**TypeScript Version:**  nightly (2.6.0-dev.20170916)

See test `extract-method-empty-namespace.ts`.

**Code**

```ts
function f() {
    namespace N {}
}
```

Extract "namespace N" out to a global function.

**Expected behavior:**

```ts
function f() {
    newFunction();
}
function newFunction() {
    namespace N { }
}
```

**Actual behavior:**

```ts
function f() {
    newFunction(N);
}
function newFunction(N: any) {
    namespace N { }
}
```

**Comment by amcasey** [comment]
I'm curious about why it's doing that but, unless I'm mistaken, that's not even legal code.  Generally speaking, I don't think we make many guarantees about the behavior of refactorings and code fixes on non-compiling code.

**Comment by amcasey** [comment]
If you do it with a class instead (also illegal), you get `newFunction(C: typeof C)`. 😄

**Comment by amcasey** [comment]
The same thing happens for a nested function, which *is* legal.  I believe the issue is that `rangeContainsRange` is comparing the selection range to the *full* range of the declaration.  Since the selection does not contain the full range, we assume that it was declared elsewhere and try to pass it along.

**Comment by andy-ms** [comment]
Actually, namespaces are legal to appear anywhere a declaration would be. In that case they create a local variable, not a global variable.

**Comment by amcasey** [comment]
@andy-ms, that seems reasonable.  Is there a switch or something I have to set to suppress/disable TS1235 (a namespace declaration is only allowed in a namespace or module)?

**Comment by andy-ms** [comment]
That is strange, I was seeing no error yesterday. Probably my services were failing but vscode doesn't tell me.  I wonder why we have this restriction, since namespaces are legal inside of a module (not global) and the emit for a namespace inside a function looks fine.
