### ISSUE TITLE
Generic constraints are sometimes lost

### ISSUE THREAD

**Issue by kujon** [Microsoft/TypeScript#18552]
**TypeScript Version:**  2.4.2

**Code**

```ts
type A = {
    foo: number;
    bar: string;
};

class Component<T> {
    props: T;
    constructor(props: T) {
        this.props = props;
    }
    render(): Component<T> | null {
        return null;
    };
}

const exampleHOC = <T extends A>(
    WrappedComponent: Component<T>
) => {
    return class ExampleHOC extends Component<T> {
        render() {
            /** Rest types may only be created from object types.  */
            const { foo, ...rest } = this.props;

            return new Component(this.props);
        }
    }
};
```

**Expected behavior:**
The code above compiles.

**Actual behavior:**
`Rest types may only be created from object types.` error message is shown, which leads me to believe that at the time of destructuring the props, `T` doesn't have any constraints applied to it.

**Comment by mhegazy** [comment]
The type of `this.props` is `T` which is a genric type. rest/spread is not supported on higher order types yet. see https://github.com/Microsoft/TypeScript/issues/10727 and https://github.com/Microsoft/TypeScript/pull/13470

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
