### ISSUE TITLE
Regression in 2.5/2.6 indexing lookup types

### ISSUE THREAD

**Issue by magnushiie** [microsoft/TypeScript#18551]
**TypeScript Version:**  2.5.2 / 2.6.0-dev.20170916

**Code**

```ts
type Field<T> = {
  instance: T;
};
  
export type QuerySpec<D extends {[P in keyof D]: Field<any>}> = {[P in keyof D]: D[P]["instance"]};
export type QuerySpecBuggy<D extends {[P in keyof D]: Field<any>}> = {[P in keyof D]: D[P]["instanc"]};
```

**Expected behavior:**
Should error on `QuerySpecBuggy`. TS 2.4.2 gives:
```
test.ts(6,87): error TS2536: Type '"instanc"' cannot be used to index type 'D[P]'.
```

**Actual behavior:**
No error.

**Comment by magnushiie** [comment]
Adding the following lines:
```ts
export type Test = QuerySpec<{x: {instance: string}}>;
export type TestBuggy = QuerySpecBuggy<{x: {instance: string}}>;
```
the inferred types are:
```ts
type Test = {
    x: string;
}
type TestBuggy = {
    x: any;
}
```
as if Field<T> was extended to contain any other property. Note that even Field<any> cannot have an "instanc" property.

**Comment by magnushiie** [comment]
Funnily even 2.4 allows the buggy variant if it is further indexed by a random indexer:
```ts
export type QuerySpecBuggy2<D extends {[P in keyof D]: Field<any>}> = {[P in keyof D]: D[P]["instanc"]["x"]};
```
This is valid for all of 2.4/2.5/2.6.

**Comment by mhegazy** [comment]
The constraint provided `D extends {[P in keyof D]: Field<any>}` is recursive in nature, where `D` is constrained to mapped type on itself. 

I am assuming you wan to constrain the type to a map of `Field`s. if so then use `D extends { [x: string]: Field<any> }`, or `D extends Record<string, Field<any>>`.

The fix here possibly is to mark this recursive constraint as an error.

**Comment by magnushiie** [comment]
I think you are right, this recursion was not necessary in my use case, I was able to replace the constraint with `{[name: string]: Field<{} | undefined>}` everywhere (I don't like to use `any` if possible) without loss of type checking.

The error instead of silent translation to `any` would be nice here though.

**Comment by gabritto** [comment]
This issue seems to be fixed now: https://www.typescriptlang.org/play?ts=5.3.0-dev.20230928&ssl=4&ssc=1&pln=4&pc=3#code/C4TwDgpgBAYglhANgEwDwBUB8UC8UDeAUFFHAHYDOwAhmQMYQBcU6A3IQL7smEQAeYAPYAnYFFCQoARQCuEYSADKkOqgAiUfsAhlkFAgG0ACqTJQA1hBCCAZlDUBdZvCRpaITB2x58x0xatbeyd7YwcDACJyKloGCIcuXgERMQloWXklFQAhGQBzPJB1TT5tXX1fE3IA6ztHZwQUVHdPb0Mqs0ta4OY1MMjomnp4riA
