### ISSUE TITLE
RWC baselines are generated one directory too high

### ISSUE THREAD

**Issue by sandersn** [Microsoft/TypeScript#18561]
For example, with immview:
1. Use tsc-instrumented to generate a JSON: `cd immview && tsc`
2. Copy JSON file into cases/rwc.
3. Run RWC tests using runtests-parallel.
4. I expect baselines to show up in `baselines/rwc/reference/immview`

But actually only __globalErrors.errors.txt and __diagnosticSummary.errors.txt show up in `baselines/rwc/reference/immview`. Other baselines show up directly in `baselines/rwc/reference`

In my case, I expected to see

`baselines/rwc/reference/immview/home/nathansa/src/immview/src/combine.errors.txt`
but I actually saw
`baselines/rwc/reference/home/nathansa/src/immview/src/combine.errors.txt`

**Comment by mhegazy** [comment]
@weswigham can you take a look.

**Comment by sandersn** [comment]
Poking around, I'm guessing that the bug is either that harness.ts/runMultifileBaseline is called with the wrong basePath, or that when runMultifileBaseline calls localPath, localPath returns the wrong answer.

I'll debug tomorrow if @weswigham doesn't have a chance to look at it by then.
