### ISSUE TITLE
Type inference fails with immediate type guards

### ISSUE THREAD

**Issue by NaridaL** [Microsoft/TypeScript#18562]
**TypeScript Version:**  master / 2.6.0-dev20170914 / whatever the playground has currently
I searched for `immediate type guard` and `type guard inference` , I hope I didn't miss an existing issue.

The issue is that the type inference fails for overloads with type guards such as the one for Array.filter when the type guard is passed as an immediate value. See also https://github.com/Microsoft/TypeScript/issues/7657 The problem seems to be that TS infers the type of the argument `e` of the type guard from the type of the callback parameter of filter. In doing so, the return type of type guard is lost. If you specify the argument `e` of the type guard explicitly, it works as expected.

**Code**
```ts
// for ref the Array signature.
interface Array<T> {
    filter<S extends T>(callbackfn: (value: T, index: number, array: T[]) => value is S, thisArg?: any): S[];
}

declare const arr: (string | number)[]

// Property 'substring' does not exist on type 'string | number'.
arr.filter((e): e is string => 'string' == typeof e)[0].substring(0, 10);

arr.filter((e: any): e is string => 'string' == typeof e)[0].substring(0, 10); // ok

const isStringArrow = (e: any): e is string => 'string' == typeof e;
arr.filter(isStringArrow)[0].substring(0, 10); // ok

// Property 'substring' does not exist on type 'string | number'.
arr.filter(function (e): e is string { return 'string' == typeof e })[0].substring(0, 10);

// Property 'substring' does not exist on type 'string | number'. 
arr.filter(function (e: any): e is string { return 'string' == typeof e })[0]
    .substring(0, 10);

arr.filter(function (this: void, e: any): e is string { return 'string' == typeof e })[0]
    .substring(0, 10); // ok

const isString = function (e: any): e is string { return 'string' == typeof e }; 
arr.filter(isString)[0].substring(0, 10); // ok
```
[playground](https://www.typescriptlang.org/play/#src=declare%20const%20arr%3A%20(string%20%7C%20number)%5B%5D%0D%0A%0D%0A%2F%2F%20Property%20'substring'%20does%20not%20exist%20on%20type%20'string%20%7C%20number'.%0D%0Aarr.filter((e)%3A%20e%20is%20string%20%3D%3E%20'string'%20%3D%3D%20typeof%20e)%5B0%5D.substring(0%2C%2010)%3B%0D%0A%0D%0Aarr.filter((e%3A%20any)%3A%20e%20is%20string%20%3D%3E%20'string'%20%3D%3D%20typeof%20e)%5B0%5D.substring(0%2C%2010)%3B%20%2F%2F%20ok%0D%0A%0D%0Aconst%20isStringArrow%20%3D%20(e%3A%20any)%3A%20e%20is%20string%20%3D%3E%20'string'%20%3D%3D%20typeof%20e%3B%0D%0Aarr.filter(isStringArrow)%5B0%5D.substring(0%2C%2010)%3B%20%2F%2F%20ok%0D%0A%0D%0A%2F%2F%20Property%20'substring'%20does%20not%20exist%20on%20type%20'string%20%7C%20number'.%0D%0Aarr.filter(function%20(e)%3A%20e%20is%20string%20%7B%20return%20'string'%20%3D%3D%20typeof%20e%20%7D)%5B0%5D.substring(0%2C%2010)%3B%0D%0A%0D%0A%2F%2F%20Property%20'substring'%20does%20not%20exist%20on%20type%20'string%20%7C%20number'.%20%0D%0Aarr.filter(function%20(e%3A%20any)%3A%20e%20is%20string%20%7B%20return%20'string'%20%3D%3D%20typeof%20e%20%7D)%5B0%5D%0D%0A%20%20%20%20.substring(0%2C%2010)%3B%0D%0A%0D%0Aarr.filter(function%20(this%3A%20void%2C%20e%3A%20any)%3A%20e%20is%20string%20%7B%20return%20'string'%20%3D%3D%20typeof%20e%20%7D)%5B0%5D%0D%0A%20%20%20%20.substring(0%2C%2010)%3B%20%2F%2F%20ok%0D%0A%0D%0Aconst%20isString%20%3D%20function%20(e%3A%20any)%3A%20e%20is%20string%20%7B%20return%20'string'%20%3D%3D%20typeof%20e%20%7D%3B%20%0D%0Aarr.filter(isString)%5B0%5D.substring(0%2C%2010)%3B%20%2F%2F%20ok)

**Expected behavior:**
All cases should work.
**Actual behavior:**
See above.

**Comment by andy-ms** [comment]
Should wait on #17600 before working on this.

**Comment by dgreene1** [comment]
Since https://github.com/Microsoft/TypeScript/pull/17600 got merged, can we pick this ticket up again?

Please let me know how I could help.

Example of the workaround, which does not scale well:
```
// Still resolves to (string | undefined)[]
var result = ["hello", undefined].filter(x => x != null);

// I had to work harder, but I eventually got TypeScript to believe that it's a string[]
function isString(test: any): test is string{
    return typeof(test) === "string";
}
var annoyinglyAchievedResult = ["hello", undefined].filter(isString);
```

Many of us are just used to writing this like `!!x`

P.S. As always, thank you so much for the wonderful work you're all doing. :)

**Comment by emilio-martinez** [comment]
@andy-ms can this be picked up again? Filter functions under strictNullChecks are a pain to workaround at this point

**Comment by andy-ms** [comment]
Related: #10734

**Comment by mhegazy** [comment]
The examples in the OP should all now be working with https://github.com/Microsoft/TypeScript/issues/5101 fixed.

The examples in https://github.com/Microsoft/TypeScript/issues/18562#issuecomment-369060313 require the type guards to be automatically inferred, which is tracked by https://github.com/Microsoft/TypeScript/issues/16069
