### ISSUE TITLE
Type `any` overriding all other type definitions in a union type

### ISSUE THREAD

**Issue by bradzacher** [Microsoft/TypeScript#18568]
**TypeScript Version:**  2.5.2

**Code**

```ts
function testOne(arg : string | number | { foo: string } | any) { }
function testTwo(arg : 'foo' | 'bar' | string) { }
```

**Expected behavior:**
`testOne` will report that it allows types `string | number | { foo: string } | any`.
`testTwo` will report that it allows types `'foo' | 'bar' | string`

**Actual behavior:**
`testOne` reports that it allows type `any`.
`testTwo` reports that it allows type `string`.

-----

Sometimes you want to allow a variable to be a given type, a given structure, whilst also providing a general fallback `any` typing.
The problem is that typescript seems to collapse the types together into the most generic types possible.

Because of how typescript reports the variable types, editors like VSCode report the function arguments as `any` and `string` respectively, thus preventing any granular definitions/autocompletes.

I believe this could be resolved by something like an exclusive or operator (such as https://github.com/Microsoft/TypeScript/issues/14094), as long as the logic is coded such that any is always the last type to be checked.

**Comment by mhegazy** [comment]
a union with `any` will always be `any`. we relay on this in the implementation to optimize union type comparisons. 
for cases like this we recommend you use overloads.  

```ts
function testTwo(arg : 'foo' | 'bar');
function testTwo(string);
```

**Comment by bradzacher** [comment]
That would work for functions, but what about for things like object properties?

The reason thar I've run into this is because of the way react types its `styles` attribute. There are a lot of scenarios where the CSS spec allows exact keywords, as well as any value. Because typescript collapses the type to any, you lose autocomplete on the exact string values.

**Comment by mhegazy** [comment]
> The reason thar I've run into this is because of the way react types its styles attribute. There are a lot of scenarios where the CSS spec allows exact keywords, as well as any value. Because typescript collapses the type to any, you lose autocomplete on the exact string values.

I understand. but as i said we rely on some of these optimizations to be able to do comparisons between union types in a performant fashion.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
