### ISSUE TITLE
Complicated destructuring gives error

### ISSUE THREAD

**Issue by paulvanbrenk** [Microsoft/TypeScript#1856]
var complicatedObj = {
        arrayProp: [
            "Zapp",
            { second: "Brannigan" }
        ]
    };

    var { arrayProp: [first, { second }] } = complicatedObj;

I expected this to work, but I get the following error on the assignment:

`Type 'string | {second:string;}' has no property 'second' and no string index signature.`

The following does work:

`var { arrayProp: [first, second] } = complicatedObj;`

**Comment by DanielRosenwasser** [comment]
I think this might be by design because you haven't contextually typed `arrayProp`.

**Comment by DanielRosenwasser** [comment]
Still, this is a confusing error message.

**Comment by mhegazy** [comment]
That is by design. if you want that to work, you need to give arrayProp an explicit tuple type.
