### ISSUE TITLE
React with Typescript error

### ISSUE THREAD

**Issue by Suka1215** [Microsoft/TypeScript#18573]
I continue to get this error when I try to add props on a component. I cannot find the solution anf or work around. Is this a bug?

[ts] Property 'title' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<AppHeader> & Readonly<{ children?: ReactNode; }> &...'.

**TypeScript Version:**  2.5.7 

**Code**
```ts
import * as React from 'react';
import AppFooter from './Footer';
import AppHeader from './Header';

export default class Layout extends React.Component {
  render() {
    const title = 'Welcome Mark';
    return (
      <div>
        <AppHeader title={title}/>
        <AppFooter />
      </div>
    )
  }
}
```

**Comment by RyanCavanaugh** [comment]
This is not a support forum. If you think you've found a bug, please include a way to reproduce the bug. We don't have the definition of `AppHeader` so we have no way of knowing what might be going wrong with your code.
