### ISSUE TITLE
Generic using extends is not honored in constructor

### ISSUE THREAD

**Issue by delta62** [Microsoft/TypeScript#18587]
**TypeScript Version:**  2.5.2 / nightly (2.6.0-dev.20170919)

**Code**

```ts
interface IThing {
    foo: string;
}

class GenericClass<T extends IThing> {
    constructor() {
        this.useThing({
            foo: 'bar'
        });
    }

    protected useThing(thing: T) {
        console.log(thing.foo);
    }
}
```

**Expected behavior:**
The code compiles successfully, since at compile time we know that `{ foo: 'bar' }` is valid for any `T` that extends `IThing`.

**Actual behavior:**
The compiler fails in the call to `useThing` in the constructor with the following message:

```
error TS2345: Argument of type '{ foo: string; }' is not assignable to parameter of type 'T'.
```

**Comment by kitsonk** [comment]
The error message is a bit confusing, but essentially you are saying that `T` is a generic type that is bound to an instance of `GenericClass` which should be resolvable.  The way the class is written, `T` is not resolvable...  It really depends on what the generic really represents.  If it is truly resolvable at the use site, then you could write it this way:

```ts
interface IThing {
    foo: string;
}

class GenericClass {
    constructor() {
        this.useThing({
            foo: 'bar'
        });
    }

    protected useThing<T extends IThing>(thing: T) {
        console.log(thing.foo);
    }
}
```

If it does need to be resolvable at the instance level, you really need to allow TypeScript to be able to get concrete information at the instance creation to be able to resolve the type.  Something like:

```ts
interface IThing {
    foo: string;
}

class GenericClass<T extends IThing> {
    constructor(thing: T) {
        this.useThing(thing);
    }

    protected useThing(thing: T) {
        console.log(thing.foo);
    }
}
```

In both cases, TypeScript can determine what `T` is.

Of course, TypeScript is a structural type system, and outside of object literals, an interface specifies the "minimum" contract.  So there is no issue with doing something like this:

```ts
interface IThing {
    foo: string;
}

class GenericClass {
    constructor() {
        this.useThing({
            foo: 'bar'
        });
    }

    protected useThing(thing: IThing) {
        console.log(thing.foo);
    }
}
```

But again, it depends on what you really _need_ the generic type for.

**Comment by delta62** [comment]
Ah, I see what the issue here is. The compiler knows that `T` has the property `foo`, but `useThing` is specifically asking for `T`, not just an object that contains a property `foo`. The fact that only `foo` is used means that the function might as well just take an `IThing`. Thanks for your response!
