### ISSUE TITLE
Array generic type inference from initialization

### ISSUE THREAD

**Issue by NN---** [Microsoft/TypeScript#18589]
Simple code infers X as Array<int>

```ts
const X = [1, 2, 3];
```

When I want to use ReadonlyArray, I have to write the type.

```ts
const X : ReadonlyArray<number> = [1, 2, 3]; // Compiling
```

This can be workarounded by a function, but then it makes runtime overhead:

```ts
function asReadonlyArray<T>(x: T[]): ReadonlyArray<T> {
	return x;
}

const X = asReadonlyArray([1, 2, 3]); // typeof X = ReadonlyArray<int>
```

Compile-time workaround is to to use typeof on the first argument which doesn't work for primitives (Is it a known issue?)

```ts
const X: ReadonlyArray<typeof 1> = [1, 2, 3]; // Error !
```

```ts
const a = { q: 1 };
const b = { q: 2 };

const X: ReadonlyArray<typeof a> = [a, b]; // OK
```

I would like to get generic type inference in compile-time by writing just type:

```ts
const X : ReadonlyArray = [1, 2, 3]; // Infers ReadonlyArray<number>
```

P.S.
Perhaps some keyword is better, but this is out of scope I think.
```ts
const X = readonly [1,2,3];
```

**Comment by gcnew** [comment]
Why `typeof 1`? `1` is already a type, you don't need `typeof`.

```ts
const X: ReadonlyArray<1> = [1, 2, 3]; // OK, Type Error
```

**Comment by NN---** [comment]
@gcnew I wanted the same way as it works with complex types.
Anyway seems like it is not a good solution since I want to have a 'number' type and not '1'.

**Comment by mhegazy** [comment]
we have discussed a `readonly` expression that allows you to get a `readonly` version of expression. this applies to object literals, and in this case array.

the prerequisite here is a `readonly` type operator that knows how to generate a readonly version of a type, i.e. remove all mutating methods, e.g. `push`, `pop` and mark all props as `readonly`. having that would allow us to avoid having two different and distinct declarations for `Array`/`ReadonlyArray` and `Map`/`ReadonlyMap`, etc.. and `ReadonlyArray<T>` would just be an alias to `readonly T[]`.

that is tracked by https://github.com/Microsoft/TypeScript/issues/10725.

For completeness, every-time we look into this we get worried about the size of the change this would cause in user code, and the cost of introducing yet another `readonly` concept that is different from `const` , and `Readonly<T>`

**Comment by NN---** [comment]
@mhegazy If there was an inference for ReadOnly array, it would be sufficient for me.

As for readonly keyword, I agree a better name is needed.
const and readonly implies non-modifiable reference but doesn’t say anything about mutating the object.

**Comment by mhegazy** [comment]
> If there was an inference for ReadOnly array, it would be sufficient for me.

that would be a massive breaking change.

**Comment by NN---** [comment]
Typing [1,2] as ReadonlyArray<number> rather than Array<number> today is of course breaking change.
Are there any plans for inferring generic arguments like in this case ?

```ts
const X : ReadonlyArray = [1, 2, 3];
```

**Comment by mhegazy** [comment]
Inferring generic types ( `T` of `ReadonlyArray<T>`) is limited to call expressions. we do not have that functionality else where in the language. do not see why would this be any different.
