### ISSUE TITLE
Error in extracting files from angular

### ISSUE THREAD

**Issue by hnrindani** [Microsoft/TypeScript#18590]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

**Code**

```ts
//  import * as angular from 'angular';
```

**Expected behavior:** I should be able to import from angular

**Actual behavior:** But it imports from angular_mock. Where am I going wrong?

**Comment by kitsonk** [comment]
This is not a support forum.

Questions should be asked at [StackOverflow](http://stackoverflow.com/questions/ask?tags=typescript) or on [Gitter.im](https://gitter.im/Microsoft/TypeScript).

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
