### ISSUE TITLE
Undefined type guard fails in some cases when strictNullCheck enabled

### ISSUE THREAD

**Issue by RomanGotsiy** [Microsoft/TypeScript#18595]
**TypeScript Version:**  2.5.1-insiders.20170825

**Playground Link**: [https://www.typescriptlang.org/play/#src=...](https://www.typescriptlang.org/play/#src=type%20Test%20%3D%20%7B%0D%0A%20%20field%3F%3A%20string%3B%0D%0A%7D%0D%0Afunction%20test()%20%7B%0D%0A%20%20const%20obj%3A%20Test%20%3D%20%7B%20field%3A%20'hello'%20%7D%3B%0D%0A%0D%0A%20%20if%20(obj.field%20!%3D%3D%20undefined)%20%7B%0D%0A%0D%0A%20%20%20%20%20%2F%2F%20typescript%20complains%20obj.field%20is%20possibly%20undefined%0D%0A%0D%0A%20%20%20%20%5B%5D.forEach(num%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20console.log(obj.field.length)%0D%0A%20%20%20%20%7D)%3B%0D%0A%0D%0A%20%20%20%20setTimeout(()%20%3D%3E%20console.log(obj.field.length)%2C%20100)%3B%0D%0A%0D%0A%20%20%20%20const%20fn%20%3D%20()%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20console.log(obj.field.length)%20%2F%2F%20error%20here%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20%2F%2F%20but%20it%20doesn't%20complains%20in%20all%20the%20cases%20bellow%0D%0A%0D%0A%20%20%20%20(()%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20console.log(obj.field.length)%20%2F%2F%20ok%20here%0D%0A%20%20%20%20%7D)()%3B%20%2F%2F%20immidiatelly%20invocation%0D%0A%0D%0A%20%20%20%20console.log(obj.field.length)%3B%20%2F%2F%20ok%20here%0D%0A%0D%0A%20%20%20%20if%20(1%20%3D%3D%3D%201)%20%7B%0D%0A%20%20%20%20%20%20console.log(obj.field.length)%3B%20%2F%2F%20ok%20here%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20%0D%0A%20%20%7D%0D%0A%7D)
(need to enable `Options` > `strictNullChecks`)

**Code**

```ts
type Test = {
  field?: string;
}
function test() {
  const obj: Test = { field: 'hello' };

  if (obj.field !== undefined) {

     // typescript complains obj.field is possibly undefined

    [].forEach(num => {
      console.log(obj.field.length)
    });

    setTimeout(() => console.log(obj.field.length), 100);

    const fn = () => {
      console.log(obj.field.length) // error here
    }

    // but it doesn't complains in all the cases bellow

    (() => {
      console.log(obj.field.length) // ok here
    })(); // immidiatelly invocation

    console.log(obj.field.length); // ok here

    if (1 === 1) {
      console.log(obj.field.length); // ok here
    }
  }
}
```

**Expected behavior:**
TypeScript doesn't produce any errors

**Actual behavior:**
TypeScript produces `Object is possibly 'undefined'` error in the places marked with comments in the code above

**Comment by kitsonk** [comment]
Duplicate of #11498

Currently there is no way for CFA to be able to determine definitively that a callback occurs immediately/synchronously and therefore resets the guards.  The IIFE can be determined statically to be immediately invoked, therefore _works_ as expected.

**Comment by RomanGotsiy** [comment]
Hey, @kitsonk!
Thanks for the prompt and clear reply!

Closing in favour of #11498
