### ISSUE TITLE
Can't call array methods on type (A[] | B[])

### ISSUE THREAD

**Issue by testerez** [Microsoft/TypeScript#18602]
**TypeScript Version:**  2.5.2

**Code**

```ts
function test(items: string[] | number[]) {
  items.forEach(item => console.log(item));
}
```

**Expected behavior:**
no error

**Actual behavior:**

> Cannot invoke an expression whose type lacks a call signature. Type '((callbackfn: (value: string, index: number, array: string[]) => void, thisArg?: any) => void) | ...' has no compatible call signatures.

**Comment by RyanCavanaugh** [comment]
Duplicate #7294

**Comment by RyanCavanaugh** [comment]
Also #10620

**Comment by rdeneau** [comment]
It's not exactly the same but you could write to fix this issue:
```ts
type stringOrNumber = string | number;
function test(items: stringOrNumber[]) {
  items.forEach(item => console.log(item));
}
```

**Comment by kitsonk** [comment]
> circumvent this issue

It isn't really an issue, in that the compiler is doing what it is instructed to do, albeit it can be slightly confusing.  Also a type alias is not required:

```ts
function test(items: (string | number)[]) {
  items.forEach(item => console.log(item));
}
```

**Comment by testerez** [comment]
@rdeneau actually is't what I did :)
