### ISSUE TITLE
Support ES5-style inheritance with Object.create (Salsa)

### ISSUE THREAD

**Issue by PhaserEditor2D** [microsoft/TypeScript#18609]
**TypeScript Version:**  2.4.1

Salsa engine does not understand ES3 prototype inheritance.

**Code**

```js

function A() {
    
}

A.prototype.hello = function (){
};

function B() {
    A.call(this);
}

B.prototype = Object.create(A.prototype);
B.prototype.constructor = B;

var b = new B();
b.[request completions]

```

**Expected behavior:**

It should show the list of methods inherited from ``A``, like ``hello()``.

**Actual behavior:**

It does not show the methods from ``A``.

**Comment by DanielRosenwasser** [comment]
> ES3
> `Object.create`

[Hmmm.](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/create) 😜

**Comment by DanielRosenwasser** [comment]
As a matter of fact, we don't support the `@class` or `@extends` annotations either.

**Comment by boniatillo-com** [comment]
The support of `@class` and `@extends` could be a simpler solution and a workaround instead of "recognize" the ``Object.create`` pattern.

**Comment by andi23rosca** [comment]
Ran into this issue recently. Any updates?

**Comment by sandersn** [comment]
There are two pieces to this:

1. Recognising the pattern. You can look at the binder code like bindObjectDefinePropertyAssignment for an example. It's probably similar.
2. Making constructor functions inherit from other constructor functions, or classes. Constructor functions don't create real class types right now, so there's no way to have them inherit from classes. It's possible to make an ad-hoc fix, or wait on something like my change on the constructor-functions-as-classes branch.

Instead implementing `@extends` support would make (1) easy but (2) would be the same.

**Comment by RyanCavanaugh** [comment]
This doesn't seem common enough in modern JS to bother adding support for at this point.
