### ISSUE TITLE
Type for Promises + domain instance

### ISSUE THREAD

**Issue by ORESoftware** [Microsoft/TypeScript#18608]
Not sure where to report this. But I think a promise in Node.js may have a domain instance attached to it, especially if the promise is passed to `unhandledRejection` handler. See this screenshot:

![screenshot 2017-09-20 12 02 28](https://user-images.githubusercontent.com/11139560/30662397-c45d6c80-9dfb-11e7-8d27-76b2de12ff28.png)

It says `property 'domain' does not exist on type Promise<any>`...but I think it does, at least as an optional property.

**Comment by aluanhaddad** [comment]
it seems like this should be a PR submitted to `npm:@types/node` package on [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped).

Something like
```ts
interface Process {
    on("unhandledRejection", (r, p: Promise<{}> & {domain: Domaib}) => void): void;
}
```

**Comment by ORESoftware** [comment]
I feel validated

**Comment by ORESoftware** [comment]
@aluanhaddad how  do I submit a PR for just one package on DefinitelyTyped? They all go into the same issue bucket right? do I tag it with npm:@types/node?

**Comment by aluanhaddad** [comment]
The [README](https://github.com/DefinitelyTyped/DefinitelyTyped/README.md) explains everything. but to the specific question know the `npm:` prefix is not something you would use in your issue or pull request on DT. I have just have gotten into the habit of writing it.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Comment by ORESoftware** [comment]
Can we open issues that are particular to `@types/node`?
