### ISSUE TITLE
Generic function loses argument types after passing type to it

### ISSUE THREAD

**Issue by rezenvar** [Microsoft/TypeScript#18606]
**TypeScript Version:**  2.5.2 

Hello, there is some problem with generic function.
I have interface which describes function which takes 2 arguments and type to use it on second argument, but when i pass type to function declaration, arguments losing type checking and IntelliSense.

**Code**

```ts
import { Action } from 'redux';

// function interface 
// T - expected type of second argument
export interface IReducerHandlerFunction<S> {
	<T>(state : S, action : Action & T) : S;
}

export interface IReducerHandlerMap<S = any> {
	[name : string]	: IReducerHandlerFunction<S>;
}

export interface IReducerConfiguration {
	prefix? : string;
}

export const defineReducer = <S = any>(defaultState : S = {} as S, actionMap : IReducerHandlerMap<S>, confirguration = {}) => (state : S = defaultState, action : Action) => {
	if (action.type in actionMap) return actionMap[action.type](state, action);
	return state;
}

interface ISuper {
	test : number;
}


interface ITest {
	testField : number;
}

defineReducer<ISuper>({test: 123}, {
        // with type
	test<ITest>(state, action) {
		// state -> any 
                // action -> any
		return state
	},
       // implementation without explict type
        test2(state, action) {
	        // state -> ISuper
	        // action -> Action
		return state
	}
});


```

**Expected behavior:**
type of action argument become Action & ITest
type of state ISuper

**Actual behavior:**
if generic type passed to declaration
type of action argument -> any
type of state argument -> any

**Comment by mhegazy** [comment]
`ITest` here is a declaration of a new type parameter, and not an application to a type argument. functions with type parameters do not get contextual types.
