### ISSUE TITLE
Using decorators together with `ClientRect` type fails on Chrome v61.

### ISSUE THREAD

**Issue by muj-beg** [Microsoft/TypeScript#18615]
**TypeScript Version:**  2.5.2

**Code**
```
function someDecorator(target, key) {
}

class MyClass {
  @someDecorator
  field: ClientRect;
}
```

The transpiled output contains the following code:
```
__decorate([
    someDecorator,
    __metadata("design:type", ClientRect)
], Greeter.prototype, "field", void 0);
```

**Expected behavior:** 
Runs without error on Chrome v61+.

**Actual behavior:**
Running the above code in Chrome v61 fails with the error:  `Uncaught ReferenceError: ClientRect is not defined`.  

This is due to two related issues:
1) Chrome replaced `ClientRect` with `DOMRect`: https://groups.google.com/a/chromium.org/forum/#!msg/blink-reviews/vxvUqqj2Gnw/4sbTv97SBgAJ
2) `lib.d.ts` hasn't been updated to reflect the above change. https://github.com/Microsoft/TypeScript/issues/11085

**Comment by gbilodeau** [comment]
We observed the same behavior today.

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by muj-beg** [comment]
@mhegazy Submitted pull request: https://github.com/Microsoft/TSJS-lib-generator/pull/299.
However, the Travis CI build error seems related to the F# NuGet package download failure.  Not sure what to do about that.
