### ISSUE TITLE
Object.getOwnPropertyDescriptors is missing from ES2017 lib d.ts

### ISSUE THREAD

**Issue by xirzec** [Microsoft/TypeScript#18610]
**TypeScript Version:**  2.4.2

**Code**

```ts
Object.getOwnPropertyDescriptors({});
```

**Expected behavior:**

Compiles with --lib es2017

**Actual behavior:**

Doesn't compile, missing definitions

You can see it's missing from the lib file: https://github.com/Microsoft/TypeScript/blob/master/lib/lib.es2017.object.d.ts

Reference of the implementation:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertyDescriptors

**Comment by mhegazy** [comment]
`lib\*` is just the LKG that we use to bootstrap the compiler, it has not been updated in a while. 

the defintion for `getOwnPropertyDescriptors` should be in `typescript@next`. here is the defintion https://github.com/Microsoft/TypeScript/blob/4d2aa9bf2cef463df1cfea3b206eb3f04e1ca765/src/lib/es2017.object.d.ts#L30.

this was added by https://github.com/Microsoft/TypeScript/pull/18175
