### ISSUE TITLE
User-defined type guard failing for object properties in scope

### ISSUE THREAD

**Issue by domagojk** [Microsoft/TypeScript#18620]
**TypeScript Version:**  2.5.2

The issue is that object property loses type information if determined with user-defined type guard.
Apologies if this is a duplicate (I couldn't find related issue) or if I misunderstood how it should actually work.

**Code**

```ts
type Fish = 'Fish'

function isFish(pet): pet is Fish {
    return pet === 'Fish';
}


function fnWithError (obj: { pet: string }): Fish[] {
  if (!isFish(obj.pet)) {
    throw new Error('not a fish!')
  }

  // resolved that obj.pet is a 'Fish'

  return [1, 2, 3].map((num) => obj.pet)

  // ERROR
  // Type 'string' is not assignable to type 'Fish'
}

function withoutGuard (obj: { pet: Fish }): Fish[] {

  return [1, 2, 3].map((num) => obj.pet)

  // compiles successfully
}

function assigningPropToVar (obj: { pet: string }): Fish[] {
  if (!isFish(obj.pet)) {
    throw new Error('not a fish!')
  }

  // resolved that obj.pet is a 'Fish'

  // assigning obj.pet in variable 
  const pet = obj.pet

  return [1, 2, 3].map((num) => pet)

  // compiles successfully
}
```

**Expected behavior:**
`fnWithError` should compile

**Actual behavior:**
`fnWithError` fails to compile with an error:

> Type 'string' is not assignable to type 'Fish'

**Comment by RyanCavanaugh** [comment]
See #11498. Long story short we don't now that `map` executes immediately, thus we don't know that the condition you checked at the top of the function is still true by the time the callback executes. You can use a const instead since we know that won't change:
```ts
function fnWithError(obj: { pet: string }): Fish[] {
    const p = obj.pet;
    if (!isFish(p)) {
        throw new Error('not a fish!')
    }

    // OK
    return [1, 2, 3].map((num) => p)
}

```

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
