### ISSUE TITLE
Review distinctions between [] and undefined in the factory

### ISSUE THREAD

**Issue by amcasey** [microsoft/TypeScript#18624]
The motivating example was modifiers on a method declarations.  I passed an empty array of modifiers (since I built it up element-by-element and happened not to add any) and the emitter blew up the empty array had no position.  See https://github.com/Microsoft/TypeScript/pull/18617.

**Comment by amcasey** [comment]
FYI @mhegazy

**Comment by RyanCavanaugh** [comment]
Presuming this to be noncritical
