### ISSUE TITLE
API endpoint for get Type at hover

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#1862]
What api endpoint in the language service would I use for this kind of stuff:

![image](https://cloud.githubusercontent.com/assets/874898/5972643/21d860ba-a8b1-11e4-9899-474113827fae.png)

and 

![image](https://cloud.githubusercontent.com/assets/874898/5972644/2663613e-a8b1-11e4-9149-055babb31fcf.png)

**Comment by basarat** [comment]
Found it : https://github.com/TypeStrong/atom-typescript/commit/9b532ab4a85184e11e3ce2bacd4513a22183763a Thanks!

**Comment by DanielRosenwasser** [comment]
If you're looking for how VS gets the tooltip info, it's `getQuickInfoAtPosition` in the language service. You can look at the source to see how it accomplishes this if you're trying to accomplish something along the same lines..

If you simply want the type at a position, you can use `getTypeAtLocation` from the `TypeChecker`.

**Comment by DanielRosenwasser** [comment]
Darn it, beat me to it.
