### ISSUE TITLE
import fails with 'no default export'

### ISSUE THREAD

**Issue by Aqours** [Microsoft/TypeScript#18632]
**TypeScript Version:**  2.5.2 / nightly (2.6.x-dev)

Move from [Microsoft/TypeScript-React-Starter Issues-8](https://github.com/Microsoft/TypeScript-React-Starter/issues/8)

<blockquote>
This import works fine under babel:

```ts
import React from "react";
```

But under TypeScript it complains of:
(1,8): error TS1192: Module '"/Volumes/repos/tc-web-ts/node_modules//index"' has no default export.
</blockquote>

I have come across with the same issue.

**Code**

```ts
// a.js file
var d;
...
export default d;

// b.ts file
import RenameD from './a'; // error: Module a has no default export
```

**tsconfig.json**

```json
{
  "compilerOptions": {
    "allowJs": true,
    "sourceMap": true,
    "declaration": false,
    "skipLibCheck": true,
    "noImplicitAny": false,
    "strictNullChecks": false,
    "module": "es2015",
    "moduleResolution": "node",
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "dom",
      "es5",
      "scripthost",
      "es2015"
    ]
  },
  "include": [
    "src/**/*.ts"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

I can use `import * as RenameD from './a';` to avoid this issue, but some module resolution may has some problem when parsing this modules.(e.g: [google-closure-compiler](https://github.com/google/closure-compiler)、webpack(when using ts-loader to load ts files))

**Expected behavior:**
No error output.

**Actual behavior:**
 Module a has no default export

**Comment by aluanhaddad** [comment]
Does the code run correctly?
If it does, use the `--allowSyntheticDefaultImports` flag.

If it does not, see #16093.

**Comment by Aqours** [comment]
`allowSyntheticDefaultImports: true` works.
But why not fix this feature(bug)? I think it's a bug.

**Comment by kitsonk** [comment]
No.  A default import is different than a `*` import.  The concept didn't exist prior to the ES module specification, so `allowSyntheticDefaultImports` is specifically designed to solve that, but it is opt in, because it changes the behaviour in a potentially unexpected way.  You can consider the compiler flag a fix.

**Comment by Aqours** [comment]
```ts
// a.js
const A = { name: 'test' };
export default A;

// b.js
import * as B from './a';
console.log(B); // { default: {name: 'test'}, [otherVars] }

// c.js
import C from './a';
console.log(C); // { name: 'test' }
```

`A === B.default` and `A === C`.
This is tested in Chrome 61 Stable without using extra flag.
`import` and `export` behavior in TS&JS is unlikely in JS, sometimes it's confused.
`allowSyntheticDefaultImports` flag is not permanent solution.
Consider to resolve this issue thoroughly.

**Comment by kitsonk** [comment]
That is exactly the behaviour that is desired.  `allowSyntheticDefaultImports` is to be used with legacy module formats that do not support exporting default.  That is what the term _synthetic_ means and why changing the behaviour is under a compiler flag.
