### ISSUE TITLE
Generic array type is being recognized as number in array.push

### ISSUE THREAD

**Issue by aminpaks** [Microsoft/TypeScript#18640]
**TypeScript Version:**  2.5.2

**Code**

```ts
function mergeArrays<T>(first: T[], second: T[]): T[] {
  return first.push(...unique); // <-- [ts] Type 'number' is not assignable to type 'T[]'.
}
```

**Expected behavior:**
All available prototype methods of array should behave the same with generic types, and recognize the type of inputs.

**Actual behavior:**
Generic Array.prototype.push doesn't recognize the current type of array and assures with type number.

**Comment by Ghabriel** [comment]
The problem is not in the parameters (shouldn't "unique" be "second", by the way?) of push, it's in its return type. Array.prototype.push returns the new length of the array.

**Comment by aminpaks** [comment]
@Ghabriel totally agree. You're right 100%. My bad :(

**Comment by RyanCavanaugh** [comment]
`concat` is the function you're looking for

**Comment by aminpaks** [comment]
@RyanCavanaugh I already was using `concat` I had forgotten about the signature of `push` :|
