### ISSUE TITLE
Question: Symbol Binding for 'fake' node

### ISSUE THREAD

**Issue by fdecampredon** [Microsoft/TypeScript#1864]
I'm trying to implements the JSX support for typescript, I have something that 'more or less' works for the parsing type-checking and emitting phases, but I fail to understand how I can do proper symbol binding for that case (and if my problems really come from that):

a JSX element: 
```
<module.MyTagName ref="ref"  key="key" foo={bar}>Hello {name}</module.MyTagName>
```
should be the equivalent of : 
```typescript
{
    type : module.MyTagName;    //<== JSXElement tagName
    key : "key" // <== key attribute
    ref : "ref"   // <== ref attribute
    props : { 
      children: ['Hello', name], //<== child
      { foo: bar} // attributes !== (ref || key) 
    };       
 }
```
Like you can see we have to pretty much manipulate the symbol, and for some properties 'type', 'props', 'children', we don't really have a declaration for attaching the symbol.

Like I said I have somewhat acceptable result: 
```
({ type: Hello.world, key: "hello", ref: foo, props: { foo: "bar", callback: bar } });
>({ type: Hello.world, key: "hello", ref: foo, props: { foo: "bar", callback: bar } }) : { type: boolean; key: string; ref: () => any; props: { foo: string; callback: () => string; }; }
>{ type: Hello.world, key: "hello", ref: foo, props: { foo: "bar", callback: bar } } : { type: boolean; key: string; ref: () => any; props: { foo: string; callback: () => string; }; }
>type : boolean
>Hello.world : boolean
>Hello : typeof Hello
>world : boolean
>key : string
>ref : () => any
>foo : () => any
>props : { foo: string; callback: () => string; }
>{ foo: "bar", callback: bar } : { foo: string; callback: () => string; }
>foo : string
>callback : () => string
>bar : () => string
 
<Hello.world key="hello" ref={foo} foo="bar" callback={bar} />;
><Hello.world key="hello" ref={foo} foo="bar" callback={bar} /> : { type: boolean; key: string; ref: () => any; props: { foo: string; callback: () => string; }; }
>Hello : unknown
>world : unknown
>key : unknown
>ref : unknown
>foo : () => any
>foo : unknown
>callback : unknown
>bar : () => string
```
I have proper type resolution for the element itself, but the type for all the children of the element are not bound.

Questions: 
* Is the problem really comes from binding ?
* Should I create dummy Node that extends declaration just to attach the symbols at something ?
* Is there another way ?

**Comment by mhegazy** [comment]
I am not sure i understand the way you have it setup now. but just off the top of my head, i would assume you want to do that as a preprocessor transformation after you parse and before binding. I would say create a new "fake" node that has pos/length matching the original text when possible and 0 length when auto generated (e.g. in your example "type" would have length 0, where "module.MyTagName" would match your input pos and length). Then let the binder do its work to create the correct symbols. then from that point on, things should just proceed normally, and the emitted code should just be what you want.

in general the system amuses that everything is available at bind time and that there are no more symbol binding after that.

**Comment by mhegazy** [comment]
This is really interesting work. Would love to see it in action. Let me know if there are any API changes you need to ease your work.

**Comment by fdecampredon** [comment]
Ok thanks to you it seems going well, you can see my branch here https://github.com/fdecampredon/TypeScript/tree/jsx (work in progress)

**Comment by fdecampredon** [comment]
I'll close this issue since now everything is ok for me thanks for your help.
