### ISSUE TITLE
Literal type 1 | -1: small compile issue

### ISSUE THREAD

**Issue by Schaekels** [Microsoft/TypeScript#18645]
**TypeScript Version:**  2.4.0

**Code**
export class Test {
    private _toggleSort : 1 | -1 = 1;
    private toggleNumber() : 1 | -1{
        return this._toggleSort * -1;
    }
}

**Expected behavior:**

That it this code compiles

**Actual behavior:**

It doesn't compile

**Comment by mhegazy** [comment]
The compiler does not do literal type arithmetic. i.e. `-1`  + `1` is not the literal type `0`. operators like `*` will always result in `number`. you can add an explicit cast `this._toggleSort * -1 as 1 | -1`.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
