### ISSUE TITLE
TSC2417 - Incorrectly extending other class (which is not the case)

### ISSUE THREAD

**Issue by rdnscr** [Microsoft/TypeScript#18643]
**TypeScript Version:**  2.5.2

**Code**
```ts
@Injectable()
export class DefaultExceptionHandler extends ErrorHandler {

  constructor(protected notificationService: NotificationService) {
    super(false); // no rethrow of errors
  }
....
}

@Injectable()
export class MyExceptionHandler extends DefaultExceptionHandler {

  constructor(@Inject(dispatcher) private dispatcher: Subject<Action>, notificationService: NotificationService) {
    super(notificationService);
  }
....
}
```

**Expected behavior:**
This should work since it is inheritance as it is intended. It shoud be possible to have different constructor parameters to the class i extend from. 

This example was working with Typescript 2.4.2 and with TypeScript 2.5.2 it is broken.

**Actual behavior:**
```
ERROR in [at-loader] ./src/app/common/services/my-exception-handler.service.ts:7:14
    TS2417: Class static side 'typeof MyExceptionHandler' incorrectly extends base class static side 'typeof DefaultExceptionHandler'.
  Types of property 'ctorParameters' are incompatible.
    Type '() => ({ type: typeof Subject; decorators: { type: InjectDecorator; args: OpaqueToken[]; }[]; } |...' is not assignable to type '() => { typ
e: typeof NotificationService; }[]'.
      Type '({ type: typeof Subject; decorators: { type: InjectDecorator; args: OpaqueToken[]; }[]; } | { typ...' is not assignable to type '{ type: t
ypeof NotificationService; }[]'.
        Type '{ type: typeof Subject; decorators: { type: InjectDecorator; args: OpaqueToken[]; }[]; } | { type...' is not assignable to type '{ type:
 typeof NotificationService; }'.
          Type '{ type: typeof Subject; decorators: { type: InjectDecorator; args: OpaqueToken[]; }[]; }' is not assignable to type '{ type: typeof No
tificationService; }'.
            Types of property 'type' are incompatible.
              Type 'typeof Subject' is not assignable to type 'typeof NotificationService'.
                Property 'ctorParameters' is missing in type 'typeof Subject'.
```

**Comment by mhegazy** [comment]
The error talks about a static property `ctorParameters` which is not in your code sample. please provide a self-contained reproduction of the issue.

**Comment by rdnscr** [comment]
I found the issue. The problem is the AoT compiler of angular which will generate these static ctorParameters during his compilation cycle. The typescript compiler will start his work afterwards and then breaks with the exception above.
Reason behind that is, that both classes are annotated with the @Injectable decorator since they both can be directly registered to the angular dependency injection system and therefore the AoT compiler will generate this static variables in both cases. 

The only solution for this would be if typescript provides a possibility to ignore the check for statically variables, the AoT compiler of angular changes his behavior (i assume both of this changes will not happen) or if you derive from another angular service you use the decorator pattern instead of inheritance.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Comment by SinoBoeckmann** [comment]
**TypeScript Version: 2.6.2**

**Code**

```javascript
class SpecialClassName {
  public static breakout(): string {
    return '';
  };
};
class ExtendSpecialClassName extends SpecialClassName {
  public static breakout(title: string): string {
    return title;
  };
};

let title: string = ExtendSpecialClassName.breakout('Hi there');
console.log(name);
```

**Expected behavior:**

> This should work since it is inheritance as it is intended. It should be possible to have different constructor parameters to the class i extend from.

(Actually the same as @rdnscr mentioned before; now with a working example)

**Actual behavior:**
```
typescript SinoBoeckmann$ tsc index.ts 
index.ts(7,7): error TS2417: Class static side 'typeof ExtendSpecialClassName' incorrectly extends base class static side 'typeof SpecialClassName'.
  Types of property 'breakout' are incompatible.
    Type '(title: string) => string' is not assignable to type '() => string'.
```

**Comment by mhegazy** [comment]
@SinoBoeckmann please see https://github.com/Microsoft/TypeScript/issues/4628
