### ISSUE TITLE
AMD/UMD module name directive not preserved in declaration emit

### ISSUE THREAD

**Issue by alexeagle** [Microsoft/TypeScript#18648]
If a module declares its name, it should be require'd by that name. However, the module name doesn't appear in `.d.ts` outputs, so if the project is compiled as multiple programs, the `require` statements are wrong.

Example: if these files are compiled together:

`foo.ts`
```
/// <amd-module name="name_of_foo"/>
export const foo = 1;
```
`bar.ts`
```
import {foo} from './foo';
console.log(foo);
```

with ts@next (typescript@2.6.0-dev.20170921)

`./node_modules/.bin/tsc foo.ts bar.ts --module umd --declaration`

The require site in `bar.js` is correct:

`    var foo_1 = require("name_of_foo");`

However, the `foo.d.ts` file doesn't contain the directive, so if I compile the files separately instead:

```
./node_modules/.bin/tsc foo.ts --module umd --declaration; rm foo.ts; ./node_modules/.bin/tsc bar.ts --module umd --declaration
```

then the require site in `bar.js` no longer requires foo by its name

`var foo_1 = require("./foo");`

**Comment by alexeagle** [comment]
Working around this for TS < 2.6 by adding this in `CompilerHost#writeFile`
```
// Workaround https://github.com/Microsoft/TypeScript/issues/18648
    if (fileName.endsWith('.d.ts') &&
        sourceFiles &&
        sourceFiles.length > 0 &&
        sourceFiles[0].moduleName &&
        (this.options.module === ts.ModuleKind.AMD ||
        this.options.module === ts.ModuleKind.UMD)) {
      content = `/// <amd-module name="${sourceFiles[0].moduleName}" />\n${content}`;
    }
```

**Comment by weswigham** [comment]
Directive comments in general should be preserved in .d.ts emit.
