### ISSUE TITLE
Imports into index.d.ts breaks ts-check in js file

### ISSUE THREAD

**Issue by jcreamer898** [Microsoft/TypeScript#18655]
First off, LOVE the new `// @ts-check` behavior.

Just having one minor issue with it right now.

I have an `index.d.ts` file, and I was trying to import an interface from an external file into it, like....

```typescript
import {
  IExternal
} from "./interfaces";

interface IFoo {
  external: IExternal;
}
```

Then in my js file...

```js
// @ts-check

/**
 * @param {IFoo} external
 */
function doSomeFoo(external) {
  console.log(external)
}
```

When I have the `import` in the `index.d.ts` it tells me that `IFoo` is undefined in my js file. However, if I manually create an `IExternal` in the `index.d.ts`, everything  is ok. So, seems like importing into the `index.d.ts` is messed up some how.

**TypeScript Version:**  2.4.1

**Code**

https://github.com/jcreamer898/tscheckimporterror

**Expected behavior:**

**Actual behavior:**
http://d.pr/v/PYkkys

**Comment by mhegazy** [comment]
by adding the `import` in your `index.d.ts` you have switched it to a module. modules have their own scope and their declarations are not visible in the global scope.

if you want `IFoo ` to be visible in the global scope (without an import statement), use `declare global`, e.g.:

```ts
import {
  IExternal
} from "./interfaces";

declare global {
    interface IFoo {
        external: IExternal;
    }
}
```

**Comment by jcreamer898** [comment]
Ahhh, nice. I'll give that a try.

**Comment by jcreamer898** [comment]
That was in fact, the problem. Thanks!
