### ISSUE TITLE
Intellisense with non static imports/require

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#18656]
_From @thetutlage on September 21, 2017 17:22_

**Disclaimer**

1. I am not sure if this is the right repo to place this issue, so please guide me if not.
2. I searched stackoverflow and existing issues and found nothing for it.

I was trying to find a way to make `dynamic imports` or `non-static imports` to provide intellisense. For example

I have a file called `user.js` with following contents

```js
module.exports = function () {
  return {
    username: 'virk'
  }
}
```

And another file called `index.js` with following contents

```js
var userModule = './user'

const user = require(userModule)()
console.log(user)
```

When typing `user.` I get no intellisense, since the engine behind autocomplete may not have access to the `userModule` value and hence it fails.

## Hey that's not the right way?
Maybe you are right, but going there can be so many use cases where the require statements receives a dynamic value, which is part currently running application.

Also going forward, ES6 will have a [Loader](https://whatwg.github.io/loader/) API, where you can register modules or even can define a custom loader for a given application and I do think that intellisense will fail in that case too.

## No offense
The above points may have nothing to do with intellisense at all, since the design behind the entire system works on static analysis.

But the reason I created the issue, since I know that a `TSServer` runs inside a separate process to provide Typescript intellisense, which means there can be other ways too to use a loader which is part of a certain application.

Thanks 😄 

_Copied from original issue: Microsoft/vscode#34778_

**Comment by mhegazy** [comment]
The process of finding what file a module refers happens as a preprocessing step. at that time we do not know the types of variables.

One workaround is to give `user` a JSDoc comment that specifies its type.

**Comment by thetutlage** [comment]
@mhegazy Okay makes sense and what are your thoughts around the `Loader` API?

**Comment by thetutlage** [comment]
I am pretty much confused on how really the intellisense works. For example: I have some code that adds dynamic methods to a class prototype as follows.

#### user.js
```js
var properties = {
  age: 22,
  username: 'virk'
}

class User {
}

Object
  .keys(properties)
  .forEach((key) => {
    User.prototype[key] = properties[key]
  })

module.exports = User
```

Now when I try to use this module inside a different file, the intellisense doesn't work.

![screen shot 2017-09-22 at 12 58 33 pm](https://user-images.githubusercontent.com/1706381/30733726-dab4cdf2-9f95-11e7-883a-015be1ccc254.png)


## Wait wait

Whereas the same thing works with Express. So inside their router, they have defined some dynamic HTTP methods. https://github.com/expressjs/express/blob/master/lib/router/route.js#L193

And intellisense for all this works out of the box.

![screen shot 2017-09-22 at 12 57 12 pm](https://user-images.githubusercontent.com/1706381/30733750-f9764ae0-9f95-11e7-9a4a-a337f40db5bf.png)

**Comment by DanielRosenwasser** [comment]
This is because Express has `.d.ts` files written for it. `.d.ts` files are a static representation of what exists at runtime, and can be produced from TypeScript code or written manually for libraries that were not written in TS. Thanks to [Definitely Typed](https://github.com/DefinitelyTyped/DefinitelyTyped/), most major libraries have `.d.ts` files written for them.

Not everything can just be inferred - capturing precise behavior would require literally running your program. If you're ever getting good signature help on a function/method, it's likely because we're leveraging static information `.d.ts` files or from JSDoc when it's available.

**Comment by thetutlage** [comment]
Okay that makes sense

So for proper intellisense to work a project must be in typescript or have proper type definitions. Atlast Docblocks can be used to provide intellisense for whatever is possible

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
