### ISSUE TITLE
The compiler is too forgiving on interface implementation with union types

### ISSUE THREAD

**Issue by emmanueltouzery** [Microsoft/TypeScript#18658]
**TypeScript Version:**  2.6.0-dev.20170913

**Code**

```ts
interface MyInterface {
    myFunction(x: string|{field1:string,field2?:string}): string;
}

class MyClass implements MyInterface {
    myFunction(x: string): string { return ""; }
}
```

**Expected behavior:**
The code should not compile because `MyClass` does not in fact implement the exact interface `MyInterface`. It should also have to accept the union type on the parameter.

**Actual behavior:**
The code compiles.

**Comment by DanielRosenwasser** [comment]
Unfortunately this looks like a symptom of https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-function-parameters-bivariant

**Comment by emmanueltouzery** [comment]
I see, I guess I should close that bug then (next time I'll ask first on stackoverflow, sorry). That could be connected with https://github.com/Microsoft/TypeScript/issues/2000 -- maybe if an override keyword is present, the compiler could become more strict...
