### ISSUE TITLE
Question: Accessing modules living in different window object?

### ISSUE THREAD

**Issue by reezom** [Microsoft/TypeScript#1865]
What is a good/proper/recommended way to access modules in a different window object? 
For example, take the iframe scenario (assuming same domain) below:

```javascript
module Container {
    export function magic() { /*...*/ };    
}
module Frame {
    function doContainerMagic() {
        window.parent.Container.magic(); // COMPILER ERROR
    }
}
```
"Casting to a module" seems not possible. Would #420 (modules implementing interface) provide a possible solution?

**Comment by NoelAbrahams** [comment]
@reezom, if your code actually works then you probably only need a type assertion:

```typeScript
module Container {
    export function magic() { /*...*/ };    
}

interface iFrame extends Window {
	Container: typeof Container;
}

module Frame {
    function doContainerMagic() {
		
        (<iFrame>window.parent).Container.magic();
    }
}
```

**Comment by reezom** [comment]
@NoelAbrahams Thank you, that solves it. 
Having learned that modules have a type, I ended up with:

```javascript
module Container {
    export function magic() { /*...*/ };    
}

module Frame {
    function doContainerMagic() {
        (<typeof Container>window.parent["Container"]).magic();
    }
}
```

**Comment by NoelAbrahams** [comment]
Yes, that'll work, but may create problems one day when `--noimplicitany` is turned on. In fact there's  no need for the type assertion, because accessing `Container` via the bracket notation effectively renders the type to `any`:

```typescript
    function doContainerMagic() {
        window.parent["Container"].magic22();
    }
```
