### ISSUE TITLE
Unexpected Type Narrowing In Ternary Expression

### ISSUE THREAD

**Issue by sylvanaar** [Microsoft/TypeScript#18669]
**TypeScript Version:**  2.5.2 

Type is narrowed unexpectedly in else portion of ternary expression. In the example below the type is narrowed to string when it should be string | boolean.

**Code**

```ts
const value: string|boolean = false ? true : "false";
const bvalue = (value === "true" || value === true) ? true : (value === "false" || value /* type narrowed to string */ === false) ? false : undefined;
```

**Expected behavior:**
Should typecheck without error.

**Actual behavior:**
error TS2365: Operator '===' cannot be applied to types 'string' and 'boolean'.

**Comment by mhegazy** [comment]
the problem is the original type.. `value` is narrowed on the initialization to be `true | string`. so it can not be `false`.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
