### ISSUE TITLE
Wrong case generated for compiled files.

### ISSUE THREAD

**Issue by Stevenic** [Microsoft/TypeScript#18678]
**TypeScript Version:**  3.52 

**Issue**

Compiler will often generate wrong case for compiled files. I have a medium sized TS project that's building a Node module. When I compile I'll often get files generated that have the wrong case. I use camel case for all of my files so they should all start with a lower case letters. I currently have a file called "bot.ts" that when it compiles results in a generated file of "Bot.ts". The issue is this totally causes my library to break on Mac & Linux. :(

In the past I've seen this issue when I was importing a file somewhere using the wrong case. I've searched my project and every reference to it. There are zero instances of "Bot" so I have no explanation as to why the compiler is emitting the file with the wrong case. What's crazy is I can move some code around and the issue will fix itself but then eventually another file will change case.  I totally can't trust the output of the compiler at this point because I run my unit test on Windows and it ignores the file case. I have thousands of developers that depend on [my library](https://github.com/Microsoft/BotBuilder) so I HAVE to get the bottom of this issue.

**Comment by kitsonk** [comment]
There is no version of TypeScript named 3.52.

You need to provide a bit more information as well.  As the issue template explains, a self contained repo is required.  Sort of guess at what your environment is, and if you are just using `tsc` by itself is some sort of 🔮 no one here posses.

**Comment by RyanCavanaugh** [comment]
Turn on `--forceConsistentCasingInFileNames` and see if that helps

>  I currently have a file called "bot.ts" that when it compiles results in a generated file of "Bot.ts". 

???

```
C:\Throwaway\BotBuilder>dir /s bot.ts
 Volume in drive C is OSDisk
 Volume Serial Number is CCED-E58F
File Not Found
```

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Comment by ahaverty** [comment]
I've hit the same issue as @Stevenic 
- v6.11.1
- Typescript 2.6.1
- Visual Studio Code

My built .js files and .js.map in build folder are incorrectly cased, after accidentally naming the files uppercase, then converting to camelcase.
**I've tried:**

- Restarting IDE
- Killing tsc watch
- Looking around for a hidden file where tsc might be caching file names
- Deleting build folder
- Renaming the .ts files to something different (adding a '1' to the end) and resetting back to the camel case naming

It looks like @briefguo reproduction steps are similar to mine in this recent issue https://github.com/Microsoft/TypeScript/issues/7327#issuecomment-333003991

Running `tsc --forceConsistentCasingInFileNames`
**I get:**
`
error TS1149: File name '/censored/hex.ts' differs from already included file name '/censored/Hex.ts' only in casing.
`

**Comment by ahaverty** [comment]
I still had imports referencing the incorrectly cased files `import { Hex } from './Hex'` which weren't giving tslint any trouble. Fixing these imports to the correct casing, and removing the build folder + running tsc fixed the issue.
