### ISSUE TITLE
Only return class or type suggestions after new / implements / extends

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#18677]
**TypeScript Version:**  2.5.2

**Repo steps**
Trigger suggestions at the `|` in the following cases:

```ts
new |
```

```ts
class Foo extends |
```

```ts
class Foo implements |
```

**Expected behavior:**
Only suggestions for class like types are returned.

**Actual behavior:**
The standard suggestions are returned. This includes values like `__dirname` and others suggestions that result in a compiler error if actually used

On the VSCode side, I'm a little hesitant to enable https://github.com/Microsoft/vscode/issues/34792 or https://github.com/Microsoft/vscode/issues/34791 because of this issue

**Comment by RyanCavanaugh** [comment]
Agree for `implements`, but `extends` can be an arbitrary expression and there's no way to know if any given expression might resolve to an extendable thing

**Comment by mjbvz** [comment]
Make sense. Same with `new`

I still think we could filter out value type suggestions in these cases. The following code is valid for example:

```js
class F extends __dirname.constructor {  }
```

but usually suggesting value types is not useful

**Comment by mhegazy** [comment]
The current behavior seems correct to me. `new` and `extends` in a class can be followed with arbitrary expression, so any value is fair here. `implements` and `extends` in an interface can only be followed with a type. the completion filtering we did in 2.4 does that correctly.

Limiting to symbols that are declared as classes/functions is not correct; as you can have variables with function/constructor types. and checking for the type of entries (i.e. variables) before adding them to the completion list is expensive and we do not want to do that.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
