### ISSUE TITLE
Private variables in definition files

### ISSUE THREAD

**Issue by paztis** [Microsoft/TypeScript#1867]
When I produced definition files (.d.ts) for my projects, private variables of classes are also present.

Most of the time, I use internal libraries that require others definition files (jquery.d.ts for example), or definition files that are not present in lib.d.ts (Promises.d.ts and TouchEvent.d.ts for example).

But as I use private variables in my classes for wich the type is only defined in these definition files, my project generated definition file contains these types.

So without publish all the other .d.ts files with my project one, it is unusable.

Is there a way to manage it ? Or just remove the private variables to prevent these cases ?

Thanks

**Comment by RyanCavanaugh** [comment]
> But as I use private variables in my classes for wich the type is only defined in these definition files, my project generated definition file contains these types.

Can you clarify? When the compiler generates a .d.ts for a class, it doesn't put type annotations on private members, so this shouldn't be a problem.

**Comment by paztis** [comment]
Indeed, I had not noticed that they were not typed.
I must have some public variables referencing these types.

**Comment by georgehdd** [comment]
A year later: privates are still generated in d.ts. Why are they there ? what is their added values ?
This forces my class to be treated as a nominal type instead of structural type.

**Comment by RyanCavanaugh** [comment]
It's absolutely necessary to have privates in generated .d.ts files. Otherwise you could derive from that class, declare a private of your own, and unknowingly stomp on your base class's private variable value. That failure mode would be very, very difficult to debug.
