### ISSUE TITLE
Performance issue with union of string literal types

### ISSUE THREAD

**Issue by jamiewinder** [Microsoft/TypeScript#18680]
**TypeScript Version:**  2.5.2

I've been experiencing a significant sudden slowdown in my build time for a while, and I've finally isolated the cause to a short block of code which hopefully will reproduce the issue. 

The following code file takes me about 10-15 seconds to compile:

**Code**

```ts
import * as React from 'react';
import styled, { StyledComponentClass } from 'styled-components';

export type IButtonProps = React.HTMLProps<HTMLButtonElement> & {
    mode?: 'primary' | 'secondary';
};

export const Button = styled(({ mode, ...rest }: IButtonProps) => (
    <button {...rest} />
))``;

export const PrimaryButton = styled(Button).attrs({ mode: 'primary' })`
`;
```
(No special tsconfig, just defaults + `"jsx": "react"`. No special dependencies just `@types/react` and `styled-components`.)

It seems to be something to do with the line:
```ts
mode?: 'primary' | 'secondary'
```
As if I change the type of this to just `string`, it builds in about 1 second.

Hopefully this can be reproduced but it seems an odd one. If this is somehow local to me, is there any way I can self-diagnose performance issues with the compiler? (e.g. logging)

EDIT: I've just tried with typescript@next, and I don't get the same issue..?

EDIT 2: I should also add that it slows down the language service too; VS (and presumably others) fail to do intellisense, and my CPU usage goes through the roof.

**Comment by mhegazy** [comment]
> EDIT: I've just tried with typescript@next, and I don't get the same issue..?

We have made  a lot of perf/memory fixes over the past few weeks. these changes are in master (`typescript@next`) and were not in 2.5.2. 

Can you give `typescript@insiders` a try and let us know if it does address the perf issues?

**Comment by jamiewinder** [comment]
Yes, the 2.6 dev version doesn't appear to have this problem! Thanks!

**Comment by mhegazy** [comment]
can you also give `typescript@2.5.3-insiders.20170922` a test? this is what we intend to ship as `@2.5.3` next week.
