### ISSUE TITLE
formatter: allow custom switch-case indentation

### ISSUE THREAD

**Issue by andreineculau** [microsoft/TypeScript#18682]
**TypeScript Version:**  2.5.2

**Code**

Format the following

```ts
switch (foo) {
case 'bar':
  break;
}
```

**Expected behavior:**

Keep it the same.

**Actual behavior:**

`case` is indented.

```ts
switch (foo) {
  case 'bar':
    break;
}
```

This becomes more problematic when used with tslint or javascript code with eslint, because on different systems we can see one winning over the other randomly i.e. sometimes the case is indented, sometimes it's not (eslint rule says do not indent).

**Comment by vincenzovitale** [comment]
Hi guys,
any news on this?

**Comment by kenjisiu-ibmhk** [comment]
@andreineculau It has been almost half a year, is there any news on this? I suggest adding a setting (configurable in `settings.json`) for this, and making the default the new behavior (same indent level for `switch` and `case`, one more indent for statement in a `case`). Thanks!

**Comment by andreineculau** [comment]
I have no news. Running with a disabled tsformatter. The issue is marked with "awaiting more feedback" but not sure from who.

**Comment by MC-8** [comment]
I'm programming in C and I'm quite happy with how the autoformat formats the code (it's reasonably close to our coding standard, and MISRA guidelines). However, it is desired in my case that there are indents for switch case statements.

What I obtain now after pressing ALT+SHIFT+F:
![image](https://user-images.githubusercontent.com/30084738/38251235-cd7f9cf2-3748-11e8-96fb-9c56ccf05ef1.png)

What I would like:
![image](https://user-images.githubusercontent.com/30084738/38251394-3ba9b6e0-3749-11e8-90aa-b970a1f10009.png)

And, ideally, the "case" keywords should be the same color as "switch"'s.
Is that possible?

**Comment by Shana6** [comment]
I'd want a setting setup for this specific issue because of some cases of people wanting indent or not.
I'm one of the people who wants indenting like
![image](https://user-images.githubusercontent.com/32604996/43679549-e9ae0c82-97e3-11e8-8d75-0553be5d7d20.png)
instead of
![image](https://user-images.githubusercontent.com/32604996/43679529-ade07398-97e3-11e8-95a6-dd3e58cfd421.png)
since it is in every way less confusing for me to look at. I use Java in another IDE and Node.js with vscode and it'd be nice if I could see my switch case setup look like my Java ones (case is indented)
using 1.25.1

**Comment by dingcang** [comment]
hi guys, how is the progress

**Comment by sicet7** [comment]
would be awesome if this was made beucase i really like having the case and the break statements on the same indent level :-)
![Case and Break statements on same indent level](https://i.imgur.com/AFtEeWn.png?1)

**Comment by ricardolpd** [comment]
I guess this has a really low priority, as its annoying but not a big deal. Does anyone from the vscode have an expected release for this?

**Comment by xmedeko** [comment]
This is really a severe issue for me using autoformat in VS Code, so I cannot use autoformat due to this bug. And for me, one of the main tasks of IDE is to do code autoformat. So for me, it's a major failure of VS Code. All mature IDE's have configurable indentations.

**Comment by phamminhkhac** [comment]
any good news?

**Comment by IllanRULDACUNHA** [comment]
I'm also interested in the feature, to be able to configure the auto-indent for switchs/cases. I don't like the current behavior.

Any news on this, please?

**Comment by orielz** [comment]
any good news? very annoying issue

**Comment by charlie-kano** [comment]
this feature would be very helpful for my team!

**Comment by SoapyMan** [comment]
I kinda find flat annoying to eyes too so I prefer indented variant.

**Comment by SrBrahma** [comment]
There should be a setting for it. Shame that it hasn't been done yet. ESLint does it well.

**Comment by phamminhkhac** [comment]
4 years later:

**Comment by nfearnley-xello** [comment]
*cough*

**Comment by iqapps** [comment]
cough, cough

**Comment by itzmanish** [comment]
Almost 5 years later, same issue no fix 🙄.

**Comment by andrewbranch** [comment]
Are you volunteering? All the other “_N_ years” commenters have been pretty quiet since I marked it “Help Wanted.” I thought for sure somebody would have given this a shot by now. 😄

**Comment by donaldnevermore** [comment]
I'll have a try.

**Comment by donaldnevermore** [comment]
@andrewbranch Needs help here. The code worked, but I'm not sure if there are more test cases that can be added. I don't really know what is behind the `tests` folder. It's not like using a testing framework.

**Comment by xmedeko** [comment]
@a-pav I have created new issue for JavaScript https://github.com/microsoft/vscode/issues/235085 Please, vote for it if it still affects you.

**Comment by a-pav** [comment]
@xmedeko Sorry, (Edit: I removed my original comment since it became irrelevant by my later observation that follows.)

I noticed that auto-completions do not respect the settings I've made in `settings.json`, Like with these in place:
```
    "javascript.format.indentSwitchCase": false,
    "javascript.format.semicolons": "remove",
    "javascript.preferences.quoteStyle": "single",
```

`switch` case auto-completion is still indented, `log` still ends with `;` and so on.

I know that we can add custom snippets and make our necessary changes there, but couldn't vscode apply the user configurations to auto completions as well?

**Comment by xmedeko** [comment]
@a-pav It's strange if none of these settings are applied. Either you do something wrong (e.g. wrong settings file path), or it seems like a different VS Code bug. Mind that there are [workspace settings and user settings](https://code.visualstudio.com/docs/configure/settings) and the workspace settings overrides the user settings. Check how these settings appears in File > Preferences > Settings.

**Comment by a-pav** [comment]
@xmedeko I'm strictly talking about the auto-completions feature.

The mentioned settings are applied when I use **`editor.action.formatDocument`** command (or when I **paste a code snippet** from another source.) But, the settings are not applied when I use the auto-completion feature to spawn a full blown switch-case for example.

The aforementioned settings are placed in my user `settings.json` and this is what I get auto-completing on `switch` keyword in a `.js` file inside a brand new workspace:
```js
switch (key) {
	case value: // unexpected indentation
		
		break; // unexpected semicolon

	default:
		break;
}
```
Note that if I cut-paste this exact switch block or use the `formatDocument` command on the file, both the indentations and the semicolons are removed.

To add another example, auto-completing on `log` keyword also gives:
```js
console.log(); // unexpected semicolon
```

**Comment by xmedeko** [comment]
Ah, I see, I do not know much about [VS Code IntelliSense](https://code.visualstudio.com/docs/editing/intellisense) settings. It's possible to create own [code snippets](https://code.visualstudio.com/docs/editing/userdefinedsnippets) and use them in IntelliSense. But you are right the default IntelliSense should formatted according to your settings. Fill seaparate bug for it, I think it should be in [VSCode repo itself](https://github.com/microsoft/vscode/issues).
