### ISSUE TITLE
New Website Logo: Netdirect

### ISSUE THREAD

**Issue by Netdirectcz** [Microsoft/TypeScript#18684]
Please fill the following out:

- Name: NetDirect
- Homepage url: http://www.netdirect.cz/
- Brand Guidelines/Licensing: (or anything we need to know before using your logo)
- Logo: ![nd_logo](https://user-images.githubusercontent.com/32195960/30742672-73f102b6-9f9a-11e7-84d9-566d93f2d6a2.png)

> Example:
>
> Name: Microsoft
> Homepage url: https://microsoft.com
> Brand Guidelines/Licensing: https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks/usage/logo.aspx
> Logo: https://news.microsoft.com/microsoft-news-center-photos/msft_logo_rgb_c-gray/

**Comment by Netdirectcz** [comment]
Hello

**Comment by mhegazy** [comment]
Should be up in the next day or so.
