### ISSUE TITLE
__extend() failed to copy static getters

### ISSUE THREAD

**Issue by billccn** [Microsoft/TypeScript#1868]
`__extends()` currently use the normal property access syntax to copy static properties which means it will copy the result of the getter to the sub-class instead of the getter itself.

It should do something like this if ES5 is supported:

```
var FUN_PROTO_NAMES = Object.getOwnPropertyNames(Function);

export function copyStatic(from: Function, to: Function) {
    Object.getOwnPropertyNames(from).forEach(p => {
        if (FUN_PROTO_NAMES.indexOf(p) === -1) {
            Object.defineProperty(to, p, Object.getOwnPropertyDescriptor(from, p));
        }
    });
}
```

**Comment by danquirk** [comment]
This has been an issue for a long time: http://typescript.codeplex.com/workitem/2324

I'm not sure our reasoning has changed since then.

**Comment by yortus** [comment]
Also discussed more recently here: https://github.com/Microsoft/TypeScript/issues/1520

**Comment by danquirk** [comment]
Thanks, don't know why I couldn't find that.
