### ISSUE TITLE
Async/Await generated code failing in Node 8.*

### ISSUE THREAD

**Issue by grofit** [Microsoft/TypeScript#18681]
**TypeScript Version:**  2.5.2

I am facing an issue in node 8 where my async method is bombing with the error:

```
yield doSomethingThatRetunsPromise();
^^^^^

SyntaxError: Unexpected strict mode reserved word
```
After taking a look through it seems to be that all the working methods have the `__awaiter` added as  the method body wrapper, however this one does not. The only thing that appears to be different between this and other methods that get the `__awaiter` is that this contains an `await` without a response.

I am using Node 8 as platform I am running on, and I am compiling the ts with:

```json
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es2015",
    "sourceMap": true,
    "moduleResolution": "node",
    "noImplicitAny": false,
    "lib": ["es2015"]
  },
  "exclude": [
    "node_modules"
  ]
}
```

Here is an example bit of code that shows what happens:

**Example code**

```ts
private someExpressRoute = async (req: Request, res: Response) => {
	try
	{
		await doSomethingThatRetunsPromise();   // await but no return
		res.status(200).send();
	}
	catch(error)
	{
		res.status(500).send({ error: "Something went wrong" });
	}        
}
```

**Expected behavior:**

```js
this.someExpressRoute = (req, res) => __awaiter(this, void 0, void 0, function* () { // as awaiter
	try {
		yield doSomethingThatRetunsPromise();
		res.status(200).send();
	}
	catch (error) {
		res.status(500).send({ error: "Something went wrong" });
	}
});
```

**Actual behavior:**

```js
this.someExpressRoute = (req, res) => { // no awaiter
	try {
		yield doSomethingThatRetunsPromise();
		res.status(200).send();
	}
	catch (error) {
		res.status(500).send({ error: "Something went wrong" });
	}
};
```

I am not sure if the expected behaviour is correct as not entirely sure what generator syntax is valid, but as TS compiles without any errors I would assume the code should be fine, but the other methods with awaiter bit do not cause any problems.

**Comment by DanielRosenwasser** [comment]
Luckily you can work around this by targeting es2017 in the meantime - Node 7.6 has supported async await for a bit now.

**Comment by mhegazy** [comment]
@weswigham can you take a look

**Comment by weswigham** [comment]
I can;t seem to repro this with the following:
```ts
// @target: es2015
// @module: commonjs
declare const doSomethingThatRetunsPromise: any;
class Foo {
    private someExpressRoute = async (req: Request, res: {
        status(x: number): { send: Function };
    }) => {
        try
        {
            await doSomethingThatRetunsPromise(); // await but no return
            res.status(200).send();
        }
        catch(error)
        {
            res.status(500).send({ error: "Something went wrong" });
        }
    }
}
```
@grofit Does this still repro for you with `typesript@next`? If so, can I have some more context to figure out what's going on?

**Comment by mhegazy** [comment]
`--t es5` does it for me.

**Comment by mhegazy** [comment]
my bad. i can not reproduce this locally on latest either.

**Comment by grofit** [comment]
I was changing build config a lot so not entirely sure if it was es5 that was causing it, it seems fine at the moment and I am not sure if it was the await which caused it, but I have a version in the private npm repo with this problem, so TSC *has* output this at some point as I dont touch the dist folder (where it outputs to) but I cannot say for sure what caused it.

Thanks for looking though.
