### ISSUE TITLE
JSDoc type ...*? is treated incorrectly

### ISSUE THREAD

**Issue by sandersn** [Microsoft/TypeScript#18691]
I think that `...*?` is equivalent to the typescript type `any[] | null`. However, it results in the type `any[]`.

```js
// @checkJs: true
// @allowJs: true
// @strict: true
/**
 * @return {...*?}
 */
function f() {
    return null // fine, but should be an error? maybe?
}
```

**Expected behavior:**

I'm not actually sure what the correct behaviour is:
1. Parse error
2. any[] | null
3. `(any | null)[]`  (but this would mean that the prefix type parsed after the suffix type, which is incorrect).

And I'm not sure whether the error is in the parser or in `getTypeOfTypeNode`.

Also note that `...*=` doesn't parse at all, but this is less bad (I think?).

**Comment by DanielRosenwasser** [comment]
@dimvar any tips on what Closure does here?

**Comment by dimvar** [comment]
We treat it as a parse error. We only handle `...` for variable arguments, not elsewhere ([link](https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler#variable-parameters))

**Comment by DanielRosenwasser** [comment]
Thanks! Also sounds like you don't handle `A[]` which means you also don't have to handle ambiguities like `?A[]`, correct? We might have to figure it out, either from usage or decide it ourselves.

**Comment by dimvar** [comment]
Right, we don't handle the array syntax either.

**Comment by sandersn** [comment]
I'm going to close this because

1. I couldn't find any uses of `...*?` in our user test suite, although there were tons of `...*`, which we handle correctly.
2. Nobody else has requested it.
3. `...` is only allowed on params now anyway.
4. `...*=` is now allowed, and behaves the same as `...*?` -- which is the same as `...*`.
4. There's not much harm in not giving an error on the extra ?/=.
