### ISSUE TITLE
Give redeclaration errors on JSDoc @property declarations

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#18705]
```js
/// @ts-check

/**
 * @typedef Props
 * @property x {number}
 * @property x {string}
 */
```

This should be an error assuming that we move forward with #15852.

**Comment by mhegazy** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/15715

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
