### ISSUE TITLE
Parsing Bug

### ISSUE THREAD

**Issue by ccorcos** [Microsoft/TypeScript#18711]
**TypeScript Version:**  2.5.2

**Code**

The following code doesn't parse correctly and Typescript thinks f is trying to be a function. This is particularly annoying when Prettier formats my code this way...

```ts
const f: (x: any) => any

const x = (
	f([
		() => {
			return 1
		},
		() => {
			return 2
		}
	])
	.catch(error => {
		
	})
)
```

Example [here](https://www.typescriptlang.org/play/index.html#src=%2F%2F%20A%20generic%20function%20that%20returns%20the%20value%20of%20an%20object%0D%0Afunction%20f%3CT%3E(v%3A%20%7B%20value%3A%20T%20%7D)%3A%20T%20%7B%0D%0A%09return%20v.value%0D%0A%7D%0D%0A%0D%0A%2F%2F%20A%20function%20that%20takes%20inputs%20of%20different%20types%0D%0Afunction%20g(v%3A%20%7B%20value%3A%20%7B%20a%3A%20number%20%7D%20%7D%20%7C%20%7B%20value%3A%20%7B%20b%3A%20number%20%7D%20%7D)%20%7B%0D%0A%09return%20f(v)%0D%0A%7D%0D%0A%0D%0A%0D%0Aconst%20a%20%3D%20g(%7B%20value%3A%20%7B%20a%3A%201%20%7D%20%7D)%0D%0A%0D%0Aconst%20b%20%3D%20g(%7B%20value%3A%20%7B%20b%3A%201%20%7D%20%7D)%0D%0A#src=const%20f%3A%20(x%3A%20any)%20%3D%3E%20any%0D%0Aconst%20x%20%3D%20(%0D%0A%09f(%5B%0D%0A%09%09()%20%3D%3E%20%7B%0D%0A%09%09%09return%201%0D%0A%09%09%7D%2C%0D%0A%09%09()%20%3D%3E%20%7B%0D%0A%09%09%09return%202%0D%0A%09%09%7D%0D%0A%09%5D)%0D%0A)#src=const%20f%3A%20(x%3A%20any)%20%3D%3E%20any%0D%0Aconst%20x%20%3D%20(%0D%0A%09f(%5B%0D%0A%09%09()%20%3D%3E%20%7B%0D%0A%09%09%09return%201%0D%0A%09%09%7D%2C%0D%0A%09%09()%20%3D%3E%20%7B%0D%0A%09%09%09return%202%0D%0A%09%09%7D%0D%0A%09%5D)%0D%0A%09.catch(error%20%3D%3E%20%7B%0D%0A%09%09%0D%0A%09%7D)%0D%0A))

**Expected behavior:**

**Actual behavior:**

**Comment by ccorcos** [comment]
I should note that prettier 1.5 did this, not 1.7

**Comment by jwbay** [comment]
Slightly smaller repro [here](https://www.typescriptlang.org/play/index.html#src=(%0D%0A%20%20%20%20f(%5B%0D%0A%20%20%20%20%20%20%20%20()%20%3D%3E%20%7B%20%7D%2C%0D%0A%20%20%20%20%20%20%20%20()%20%3D%3E%20%7B%20%7D%0D%0A%20%20%20%20%5D)%0D%0A)). Interestingly removing the second or third line break can fix it
```ts
(
    f([
        () => { },
        () => { }
    ])
)
```

**Comment by DanielRosenwasser** [comment]
Can you try our nightlies (i.e. typescript@next)?

**Comment by ccorcos** [comment]
Sounds good to me!
