### ISSUE TITLE
Suggestion: Infer generic function type definition from explicit union types

### ISSUE THREAD

**Issue by ccorcos** [Microsoft/TypeScript#18710]
**TypeScript Version:**  2.5.2

**Code**

```ts
// A generic function that returns the value of an object
function f<T>(v: { value: T }): T {
	return v.value
}

// A function that takes specific input types and returns their value
function g(v: { value: { a: number } } | { value: { b: number } }) {
	return f(v)
}
```

The function `g` above returns a type error. This is quite inconvenient sometimes when I'm writing a logical function that takes some specific types (such as `g`) and calling a utility function (such as `f`). 

Furthermore, it would be nice if the types were inferred through as if `g` and `f` were equivalent.

```
const a = g({ value: { a: 1 } })
const b = g({ value: { b: 1 } })
```

Check it out [here](https://www.typescriptlang.org/play/index.html#src=%2F%2F%20A%20generic%20function%20that%20returns%20the%20value%20of%20an%20object%0D%0Afunction%20f%3CT%3E(v%3A%20%7B%20value%3A%20T%20%7D)%3A%20T%20%7B%0D%0A%09return%20v.value%0D%0A%7D%0D%0A%0D%0A%2F%2F%20A%20function%20that%20takes%20inputs%20of%20different%20types%0D%0Afunction%20g(v%3A%20%7B%20value%3A%20%7B%20a%3A%20number%20%7D%20%7D%20%7C%20%7B%20value%3A%20%7B%20b%3A%20number%20%7D%20%7D)%20%7B%0D%0A%09return%20f(v)%0D%0A%7D%0D%0A%0D%0A%0D%0Aconst%20a%20%3D%20g(%7B%20value%3A%20%7B%20a%3A%201%20%7D%20%7D)%0D%0A%0D%0Aconst%20b%20%3D%20g(%7B%20value%3A%20%7B%20b%3A%201%20%7D%20%7D)%0D%0A)

**Comment by DanielRosenwasser** [comment]
We try to avoid making inferences to union types because it often leads to incorrect code.

If you explicitly say what the shape of a `v` is via a constraint, TypeScript will be more forgiving. Give this a try:

```ts
// A generic function that returns the value of an object
function f<T extends { value: {} }>(v: T): T["value"] {
	return v.value
}

// A function that takes specific input types and returns their value
function g(v: { value: { a: number } } | { value: { b: number } }) {
	return f(v)
}
```

**Comment by ccorcos** [comment]
Interesting. Well I'm assuming you know better than me so I guess thats how it is haha 👍

**Comment by DanielRosenwasser** [comment]
I wouldn't put it that way, but it's more a set of tradeoffs that we've observed. 😃 

At some point we should add it to the FAQ.

**Comment by ccorcos** [comment]
Well if it gives you some perspective, I've run into this problem a few times now when working in a large codebase. This circumstance usually happens when the types `{ value: { a: number } }` and `{ value: { b: number } }` are large interfaces and only a subset of types in a larger union type. I'm working in my little corner of the world and create a function that works specifically for these two types. I run into this type issue and it requires me to refactor this function into a generic, but the interfaces are large including their overlap making it tedious and brittle to reiterate their structure again just for this one function. Does that make sense?
