### ISSUE TITLE
Declartion file generated by tsc missing import

### ISSUE THREAD

**Issue by jeremyoverman** [Microsoft/TypeScript#18723]
**TypeScript Version:**  2.5.2

**Code**

sprite.ts
```ts
import { MIME_PNG } from 'jimp';

export interface IDimensions {
    width: number;
    height: number;
}

export class Sprite {
    image: Jimp.Jimp;
    dimensions: IDimensions;
    
    constructor (img: Jimp.Jimp) {
        this.image = img;

        this.dimensions = {
            width: this.image.bitmap.width,
            height: this.image.bitmap.height
        }
    }

    getBuffer (): Promise<Buffer> {
        return new Promise((resolve, reject) => {
            return this.image.getBuffer(MIME_PNG, (err, buff) => {
                if (err) return reject(err);

                resolve(buff);
            });
        });
    }
}
```

sprite.d.ts
```
/// <reference types="node" />
export interface IDimensions {
    width: number;
    height: number;
}
export declare class Sprite {
    image: Jimp.Jimp;
    dimensions: IDimensions;
    constructor(img: Jimp.Jimp);
    getBuffer(): Promise<Buffer>;
}
```

**Expected behavior:**

When compiling `sprite.ts` using the command `tsc -d -p ./ --outdir dist/`, the `sprite.d.ts` should maintain the Jimp namespace as it were in the original `sprite.ts` file.

**Actual behavior:**

When importing this project into another file, `tsc` gives compiler errors complaining that `[ts] Cannot find namespace 'Jimp'`. Similarly, VSCode also shows the same error in the `sprite.d.ts` files when hovering over either `Jimp.Jimp` type.

**Comment by mhegazy** [comment]
in the declaration `image: Jimp.Jimp;`, `Jimp` is a global namespace. it is not imported from a module. A reference to a global name will not be replaced with a module import when generating the output.

you can instead write your import as `import * as Jimp from "jimp"` and use that instead.

**Comment by jeremyoverman** [comment]
That worked perfectly. Thank you for your time!
