### ISSUE TITLE
TypeScript/Salsa can't infer superclass type arguments

### ISSUE THREAD

**Issue by kasperpeulen** [Microsoft/TypeScript#18725]
To give some context, I use ES2015+ natively (targeting evergreen browsers) and JSDoc comment for enabling visual studio code features.

I think Typescript doesn't really support subclassing Arrays (maybe if you target ES2015+ it does?). But it would be nice if the typescript service understand that I'm here actually extending a array of `Break` objects. 

![image](https://user-images.githubusercontent.com/1035299/30784509-a0c8cd4c-a156-11e7-91ee-7e0ec91f91ac.png)

As you can see, in the constructor typescript still understand that breaks is of type `Break[]`, but in the rest of the class, typescript think that `this` extends `Array` instead of extending `Array<Break>`.

Anyway that I can tell typescript using JSDoc comments that I'm extending `Array<Break>`?

**Comment by DanielRosenwasser** [comment]
If you add

```js
/**
 * @augments {Break[]}
 */
```

right before the class, that should do it.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Comment by kasperpeulen** [comment]
@mhegazy I think it is actionable still. I now have to put jsdoca in the constructor and addig an @augments annotation, but I think that the @augments is redunant, and could be inferred from the constructor.

If you have `new Array(...breaks)` where the type of `breaks` is Array<Break> typescript can infer the type, so why wouldnt it infer the type of `this`, if you do `super(...breaks)` as in the screenshot above?
