### ISSUE TITLE
typescript react testing.

### ISSUE THREAD

**Issue by FDiskas** [Microsoft/TypeScript#18722]
**TypeScript Version:**  2.5.2

**Code**
https://github.com/nfq-eta/react-typescript/blob/6099865d118f885c99afd5e11afacadf73457ab8/src/components/tests/App.test.tsx#L27-L37

![https://i.imgur.com/rYzJao1.png](https://i.imgur.com/rYzJao1.png)

**Expected behavior:**
Should be no error

**Actual behavior:**
```[ts] Property 'handleClick' does not exist on type 'Component<any, any>'.```

**Comment by DanielRosenwasser** [comment]
If there is a problem here, we have no idea what it is.  Why do you feel that this is a TypeScript bug, and do you have a more minimal repro if so?

**Comment by jwbay** [comment]
A type assertion will get you what you want: `(wrapper.instance() as App).handleClick(`

As to why it's necessary, unfortunately the shallow wrapper can't know about your instance methods. JSX is a bit of a black hole for type information. The type of the expression `<App />` is completely disconnected from the type of `App`. So by the time we get to `.instance()` on the wrapper, the best the type definitions can do is tell you that there's probably stuff from the React.Component base class on there, but it doesn't know about anything else.

**Comment by FDiskas** [comment]
@jwbay - thanks for the grreeat explanaition. And for the suggested fix. Respect :speak_no_evil:

**Comment by DanielRosenwasser** [comment]
I apologize, but the influx of issues being filed we have means that we don't have the time to dive into every project's codebase. Our bandwidth is relatively limited so asking us to diagnose a whole project or learn Enzyme's API is a bit much.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
