### ISSUE TITLE
Incorrect function overloading regarding index types

### ISSUE THREAD

**Issue by Ghabriel** [Microsoft/TypeScript#18727]
**TypeScript Version:**  2.5.2 / Playground

**Code**

```ts
type StringMap<T> = {
    [index: string]: T
}

type NumericMap<T> = {
    [index: number]: T
};

type KeyValueCallback<K,V> = (key: K, value: V) => void;

function foreach<T>(map: StringMap<T>, callback: KeyValueCallback<string, T>): void;
function foreach<T>(map: NumericMap<T>, callback: KeyValueCallback<number, T>): void;

function foreach(map: any, callback: any): void {
    // Not relevant
}

let a = { "a": 42 };
let b = { 42: "a" };

foreach(a, function(key, value) {
    // Correct: key has type "string"
    console.log(key.substr(1));
});

foreach(b, function(key, value) {
    // Incorrect: key is also a string here
    console.log(key.toFixed(2));
});
```

**Expected behavior:**
`key` should be a `number` in the second call to `foreach`.

**Actual behavior:**
`key` is inferred to be a `string`.

Related question/suggestion: what I really would like to be able to do is something like:
```ts
type GenericMap<K extends string|number, T> = {
    [index: K]: T
}

function foreach<K extends string|number, V>(map: GenericMap<K,V>,
    callback: KeyValueCallback<K,V>): void {

    // Not relevant
}
```
Which currently fails because "An index signature parameter type must be 'string' or 'number'.", but other people probably already suggested something like this.

**Comment by DanielRosenwasser** [comment]
I would have said that the answer is to swap the overloads, but the problem is that `b` will also satisfy `StringMap<number>`. If you use explicit type annotations and swap the overloads it should work.

I'm not sure why this succeeds:

```ts
declare function forEach<T>(map: { [x: number]: string }, callback: (k: number, v: string) => void): void;

let a = { "a": 42 };
forEach(a, function(key, value) {
    // ...
});

```

**Comment by Ghabriel** [comment]
Yeah, I actually came across that odd behavior as well while trying to make my code work. It definitely looks like a bug.

As to your suggestion, do you mean something like this?
```ts
foreach(b, function(key: number, value) {
    console.log(key.toFixed(2));
});
```
This does indeed work, though it kinda defeats the purpose of the type inference...

**Comment by mhegazy** [comment]
The compiler will always infer to the string index signature, since number indexers is part of the domain of string.  consider using `ArrayLike` instead of `NumberMap`
