### ISSUE TITLE
DOM lib: `reportValidity` missing on `HTMLFormElement`

### ISSUE THREAD

**Issue by SimonSchick** [Microsoft/TypeScript#18733]
**TypeScript Version:**  2.5.2 /

**Code**

```ts
function handler(ev: Event) {
  ev.preventDefault();
  (<HTMLFormElement> ev.target).reportValidity(); /// << will be `any` due to index signature...
}
```

**Expected behavior:**

`reportValidity` is present on `HTMLFormElement`

**Actual behavior:**

It's not present.

See https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/reportValidity

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by SimonSchick** [comment]
I'll look into making one, just wanted to keep track of it first 😄
