### ISSUE TITLE
Property "Required", "Name", "Placeholder" in TextField are not supported in typescript 2.5.2

### ISSUE THREAD

**Issue by applelok** [Microsoft/TypeScript#18735]
**TypeScript Version:**  2.5.2 

**Code**

```ts
 <TextField 
      label='Site name: ' 
      required={ true }
      name='siteName'
      disabled={ this.state.isSiteLinkValidating }
      placeholder='Please input the site name here.'
      value={ this.state.siteName }
      onGetErrorMessage={ this._getSiteNameErrorMessage }
      onChanged={ this._handleSiteNameChange }
      validateOnLoad={ false }
 />

```

**Expected behavior:**
Property "Required", "name", "placeholder" should be supported in 2.5.2 version. Or is there any version that can support these property? 

**Actual behavior:**
Error occurred when running command "gulp serve". Also the * next to the field label and placeholder are disappeared in the webpart UI.
Error - typescript - src\webparts\sharepointRequestForm\components\SharepointRequestForm.tsx(516,12): error TS2339: Property 'required' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<TextField> & Readonly<{ children?: ReactNode; }> &...'.

**Comment by andy-ms** [comment]
This may be due to a change in `@types/react` rather than TypeScript? Was this working before for you?

**Comment by applelok** [comment]
Hi @andy-ms ,

Yes updated the @types/react from 0.14.46 to 15.0.38. It was working before update.

Thanks for your reminder, I have also submitted an [issue ](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/20020) in `@types/react.` 

Will close this issue directly.
