### ISSUE TITLE
ts-check Issue with inline style attributes on JSX component not assignable

### ISSUE THREAD

**Issue by jcreamer898** [Microsoft/TypeScript#18744]
**TypeScript Version:**  2.4.1

**Code**

```ts
// @ts-check
import * as React from "react";

const styles = {
  search: {
    position: "relative",
  }
}

const Foo = () => (
  <div style={styles.search}></div>
);

```

**Expected behavior:**
Everything should be 👌 

**Actual behavior:**
Getting a type error...

```
[js]
Type '{ style: { [x: string]: any; position: string; }; }' is not assignable to type 'DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>'.
  Type '{ style: { [x: string]: any; position: string; }; }' is not assignable to type 'HTMLAttributes<HTMLDivElement>'.
    Types of property 'style' are incompatible.
      Type '{ [x: string]: any; position: string; }' is not assignable to type 'CSSProperties'.
[js]
Type '{ style: { [x: string]: any; position: string; }; }' is not assignable to type 'DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>'.
  Type '{ style: { [x: string]: any; position: string; }; }' is not assignable to type 'HTMLAttributes<HTMLDivElement>'.
    Types of property 'style' are incompatible.
      Type '{ [x: string]: any; position: string; }' is not assignable to type 'CSSProperties'.
        Types of property 'position' are incompatible.
          Type 'string' is not assignable to type '"relative" | "initial" | "inherit" | "unset" | "static" | "absolute" | "fixed" | "sticky"'.
(property) search: {
    [x: string]: any;
    position: string;
}
```

**Comment by aluanhaddad** [comment]
This issue surfaces in typesTypeScript code as well and is unrelated to `@tz-check`.

The error stems from the fact that `position` is a mutable property of the `styles` local. because it is mutable, it is inferred as having type `string` instead of having a literal type.

**Comment by mhegazy** [comment]
This is not specific to `@ts-check` as @aluanhaddad noted. you can find similar discussion in https://github.com/Microsoft/TypeScript/issues/16389.

The recommendation here is to add a type annotation on your declaration to guide the compiler to inferring the literal types, e.g.:

```ts
/** @type {{search: React.CSSProperties}} */
const styles = {
    search: {
        position: "relative",
    }
}
```

**Comment by jcreamer898** [comment]
Ah, great, should I keep this open or close it then?

**Comment by mhegazy** [comment]
There are a few of elk of #16389 around. we have no plans on changing the design at this point. we already had multiple iterations on how literal types are inferred and the current design seems to be the best compromise we can reach.

**Comment by jcreamer898** [comment]
Sounds good. Closing!
