### ISSUE TITLE
CompilerOptions to preserve original semi-colon usage

### ISSUE THREAD

**Issue by yuit** [Microsoft/TypeScript#1874]
In the new compiler, we removed an options to allow/disallow automatic semi-colon insertion, so our new compiler emit JavaScript and insert semi-colon. This change affects our users who use Typescript compiler to do formatting work and relying on source-map because they would want our emitted result to preserve semi-colon (or lack of ones) in original source files.

**Comment by DanielRosenwasser** [comment]
I don't think this was publicly supported (i.e. not a breaking change as far as I'm concerned), nor do I think anyone's been missing it.

**Comment by DanielRosenwasser** [comment]
I wonder if anyone's actually been missing this.

**Comment by ahejlsberg** [comment]
I'm not sure I fully understand the scenario here. If we've gotten this far without it I can't imagine it is super important. Also, we don't track the absence or presence of semicolons in the ASTs, so there would be work and overhead associated with doing this.

**Comment by yuit** [comment]
The main users of this feature would be F12 team who uses our compiler for formatting. They are currently using old version of the compiler.

**Comment by thomasguillory** [comment]
Actually, preserving formatting would allow to more easily integrate typescript with a mainstream ES5/6 linter like [eslint](https://github.com/eslint/eslint), which supports pre/postprocessing.

Currently [tslint](https://github.com/palantir/tslint) seems to be the only linting option, and while it's good, it's a pity not to be able to benefit from the tools of the javascript community.

**Comment by mhegazy** [comment]
We have not had much feedback about the OP. 

Output Formatting is a different issue, that includes semicolon as well as other issues. we would need a clear and detailed proposal for what that entails to be able to asses that request; in general we have not accepted output formatting issues.
