### ISSUE TITLE
Regression Property does not exist on type 'T[keyof T]

### ISSUE THREAD

**Issue by magnushiie** [Microsoft/TypeScript#18746]
**TypeScript Version:**  2.5.2 / nightly (2.6.0-dev.20170923)

**Code**

```ts
interface SomeInterface {
  doSomething(): void;
}
class Container<T extends {[P in keyof T]: SomeInterface}> {
  method(value: T, prop: keyof T) {

    // succeeds
    const member: SomeInterface = value[prop];
    member.doSomething();

    // error TS2339: Property 'doSomething' does not exist on type 'T[keyof T]'.
    value[prop].doSomething();
  }
}
```

**Expected behavior:**
Compiles without errors. With 2.4 `value[prop]` was correctly inferred to be of type `SomeInterface`.

**Actual behavior:**
```
test.ts(12,17): error TS2339: Property 'doSomething' does not exist on type 'T[keyof T]'.
```

**Comment by mhegazy** [comment]
The constraint you are using does not make much sense to me really. I am guessing you meant `<T extends {[x:string]: SomeInterface}>` instead.

**Comment by magnushiie** [comment]
This is a cut-down example. In my real usage, SomeInterface is actually generic and P is used as part of an argument, e.g.: `{[P in keyof T]: Field<T[P]["exampleValue"]>}`. 

E.g.
```ts
type MessageFieldSpec<D extends {[P in keyof D]: Field<D[P]["exampleValue"]> }> =
  {[P in keyof D]: Field<D[P]["exampleValue"]> };

type MessageInstance<D extends MessageFieldSpec<D>> = {
  [P in keyof D]: D[P]["exampleValue"]
};

type SerializedMessageInstance<D extends MessageFieldSpec<D>> = {[P in keyof D]: string};
```

Even if it didn't make sense, the behavior above is clearly inconsistent.

**Comment by mhegazy** [comment]
looks fixed in latest.
