### ISSUE TITLE
Enums will not import via destructuring

### ISSUE THREAD

**Issue by dgreene1** [Microsoft/TypeScript#18748]
**TypeScript Version:**  2.5.2

**Code**

```ts
export enum myEnum {
     foo = "foo"
}
```

```ts
// index.ts
import * as someModuleWithEnums from './../someModuleWithEnums';
import {myEnum} from './../someModuleWithEnums';

console.log(someModuleWithEnums.myEnum); // prints out as an object with a foo property
console.log(myEnum); // undefined
```

**Expected behavior:**
Importing an enum via destructuring should not be undefined

**Actual behavior:**
Destructuring of an enum shows up as undefined, while using the `as` syntax actually imports the enum

**Note**: I tried to recreate this in plnkr, but I couldn't find an easy way to get typescript to work in plnkr

**Comment by mhegazy** [comment]
```sh
c:\test\18748>type a.ts
export enum myEnum {
     foo = "foo"
}
c:\test\18748>type b.ts
import * as someModuleWithEnums from './a';
import {myEnum} from './a';

console.log(someModuleWithEnums.myEnum); // prints out as an object with a foo property
console.log(myEnum); // undefined
c:\test\18748>tsc b.ts

c:\test\18748>tsc --v
Version 2.6.0-dev.20170923

c:\test\18748>node b.js
{ foo: 'foo' }
{ foo: 'foo' }

```

**Comment by dgreene1** [comment]
Can you explain what additional information you're looking for @mhegazy? Also, I noticed that you're using typescript 2.6.0-dev.20170923. I'm using the current stable, 2.5.2

**Comment by mhegazy** [comment]
```sh
c:\test\18748>
c:\test\18748>type a.ts
export enum myEnum {
     foo = "foo"
}
c:\test\18748>type b.ts
import * as someModuleWithEnums from './a';
import {myEnum} from './a';

console.log(someModuleWithEnums.myEnum); // prints out as an object with a foo property
console.log(myEnum); // undefined
c:\test\18748>tsc --v
Version 2.5.2

c:\test\18748>tsc b.ts a.ts

c:\test\18748>node b.js
{ foo: 'foo' }
{ foo: 'foo' }
```

**Comment by mhegazy** [comment]
> Can you explain what additional information you're looking for @mhegazy?

A **self-contained** reproduction of the issue.

**Comment by dgreene1** [comment]
> > Can you explain what additional information you're looking for @mhegazy?

> A self-contained reproduction of the issue.

jsFiddle doesn't allow me to link .ts files, and plunker is a real pain in the butt. The typescript playground website also does't allow me to link files via import...

so, I'm not sure where I can reproduce the issue. Can you recommend a jsFiddle alternative?

Otherwise, I can try to screencast this...? Look I'm trying my best.

**Comment by RyanCavanaugh** [comment]
@dgreene1 Above @mhegazy attempted to reproduce your problem by showing two files, compiling them, and running the output. You can do the same

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
