### ISSUE TITLE
Is Visual studio "Add as Link" supported?

### ISSUE THREAD

**Issue by BobFrGit** [Microsoft/TypeScript#18755]
Visual Studio 2017 
**Microsoft Visual Studio Professional 2017 
Version 15.3.5
VisualStudio.15.Release/15.3.5+26730.16
Microsoft .NET Framework
Version 4.7.02046
TypeScript   2.3.4.0
TypeScript tools for Visual Studio

I included a .ts file using "Add as Link" in visual studio. It worked fine in a simple node app.

**Expected behavior:**
It would act like local module and generate and .js file into the output directory with the appropriate module header.

Perhaps the problem is that "add as link" is simply not supported because it doesn't seem to be recognized by import either.

**Actual behavior:**
It does not generate a .js file to the build output directory.

**Comment by srini1978** [comment]
Any update on this ? is this an upcoming feature

**Comment by mhegazy** [comment]
In other project types, like C# for instance, adding as link just adds a note about the file in the project file. The build process for TS uses different configurations (e.g. tsconfig.json) and not the .csproj file like C#; and thus there is not a way to tell the TS compiler that this file is just a link to another file. 
Have you considered using symlinks with [`--preserveSymlinks`](https://www.typescriptlang.org/docs/handbook/compiler-options.html)?

**Comment by BobFrGit** [comment]
I see this thread has been revived. At this point I've switched to using Visual Studio Code.

But I am curious about -preserveSymLinks -- the documentation doesn't seem sufficient -- Is this about where to generate .js files ?

**Comment by mhegazy** [comment]
normally the symlink will be followed. with `--perserveSymLink` it will be considered as the file. so if you have a local sym link `./src/a.ts`, it will behave as if you have a copy of the linked file in `./src` with the name `a.ts`.
