### ISSUE TITLE
LanguageServerHost fileExists / readFile no longer optional?

### ISSUE THREAD

**Issue by tomv564** [Microsoft/TypeScript#18753]
**TypeScript Version:**  2.4.2, also in master

This issue was encountered when upgrading javascript-typescript-langserver from typescript 2.3.4 (see https://github.com/sourcegraph/javascript-typescript-langserver/pull/356)

**Code**

When implementing a LanguageServiceHost without implementing optional `fileExists` or `readFile`, the compilerHost instance silently skips `import` statements:
```ts
export class InMemoryLanguageServiceHost implements ts.LanguageServiceHost {
  // only required members implemented here..
}
```

The above implementation compiled without errors against 2.4.2, but all `import` statements in source files added to the language server failed to resolve, resulting in diagnostics, missing definitions, completions, etc.

**Expected behavior:**

Either:
* Compilation failure indicating that LanguageServiceHost is now incomplete
* Module resolver falls back to ModuleResolutionHost to access `fileExists` / `readFile`

**Actual behavior:**

Imports fail to resolve where they do exist, in `nodeModuleResolverWorker`, following the path:

```
nodeLoadModuleByRelativeName -> loadModuleFromFile
loadModuleFromFile ->  tryExtension -> tryFile -> state.host.fileExists
```

Debugger screenshot showing the issue at runtime at https://github.com/Microsoft/TypeScript/blob/21bbdd33c51f07a46663e9b50fff62e9c007c806/src/services/services.ts#L1166

<img width="983" alt="screen shot 2017-09-25 at 19 37 12" src="https://user-images.githubusercontent.com/4395832/30823982-65bae216-a22e-11e7-9a91-399150e11949.png">

The typings published at https://github.com/Microsoft/TypeScript/blob/master/lib/typescript.d.ts#L3764-L3765 show that the two members are still optional.

This dependency appears to have been introduced at: https://github.com/Microsoft/TypeScript/commit/2ec92b9c02ba6ac6b97d3fb5af830d0ece6dcd92

**Comment by mhegazy** [comment]
@andy-ms can you take a look.

**Comment by DanielRosenwasser** [comment]
Looks like a dupe of #16616

**Comment by tomv564** [comment]
Thanks for the quick update. A comment about why those members are optional in the published `typescript.d.ts` might be nice for future implementers?

I'm satisfied with the explanation, feel free to close!
