### ISSUE TITLE
Cannot find types in sub-project

### ISSUE THREAD

**Issue by Aqours** [Microsoft/TypeScript#18761]
**TypeScript Version:**  2.5.2

**Code**
```js
// [1]
// tsconfig.json
{
    "compilerOptions": {
      "allowJs": true,
      "sourceMap": true,
      "declaration": false,
      "skipLibCheck": true,
      "noImplicitAny": false,
      "strictNullChecks": false,
      "module": "es2015",
      "moduleResolution": "node",
      "target": "es5",
      "typeRoots": [
        "node_modules/@types"
      ],
      "lib": [
        "dom",
        "es5",
        "scripthost",
        "es2015"
      ]
    },
    "include": [
      "types/**/*.d.ts",
      "src/**/*.ts"
    ],
    "exclude": [
      "node_modules"
    ]
  }
```

```ts
// git-submodule/src/index.ts
Date.prototype.format = function () {
    return 90; // Just for demo
};
const date = new Date();
const format = date.format();
export default format;

// git-submodule/types/custom.d.ts
interface Date {
    format(): number;
}

// git-submodule/tsconfig.json // see above [1]

// src/index.ts
import Sub from '../git-submodule/src/index';

// src/tsconfig.json // see above [1]
```

then, run `tsc` in root directory.

**Expected behavior:**
No errors.

**Actual behavior:**
```
// errors
git-submodule/src/index.ts(1,16): error TS2339: Property 'format' does not exist on type 'Date'.
git-submodule/src/index.ts(6,21): error TS2339: Property 'format' does not exist on type 'Date'.
```

**Comment by andy-ms** [comment]
TypeScript won't look at the `tsconfig.json` for imported modules. So it won't know that in `git-submodule` you had a `tsconfig.json` that included the types.
If you need to expose types from a package, you should reference them from its `index` in some way, such as with `/// <reference path="./types/custom.d.ts" />.`
In this case, you could also not bother with putting types in a separate file and just do:
```ts
declare global {
    interface Date {
        format(): number;
    }
}
```

**Comment by Aqours** [comment]
@andy-ms 
It works great.

Furthermore, defined types of root project(e.g: `/// <reference path="./root-project.d.ts" />`) will expose to sub-project which can use those types in `root-project.d.ts` file even if sub-project does not define those types. And compiling code will not throw type error, it's unreasonable.
