### ISSUE TITLE
Define method descriptor using class prototype in Method Decorator not working

### ISSUE THREAD

**Issue by dev2geek** [Microsoft/TypeScript#18764]
**TypeScript Version:**  2.5.2

**Code**

```ts
function auditLogDecorator (target: any,
    methodName: string,
    descriptor?: PropertyDescriptor) {

    let originalFunction = target[methodName];

    let auditFunction = function () {
        console.log(`Audit log comes here for ${methodName} method. `);
        originalFunction.apply(this, arguments);
    }

    target[methodName] = auditFunction;
}

class Student {
    constructor(private name: string) {
    }

    @auditLogDecorator
    say(): void {
        console.log(this.name);
    }
}

const jack = new Student('jack');
jack.say();
```

**Expected behavior:**
> Audit log comes here for say method. 
> jack

**Actual behavior:**
> jack

**More**

By checking the compiled js code, it seems that the method  is reset at last. Is it by design or a bug?

```js
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
// ...
return c > 3 && r && Object.defineProperty(target, key, r), r;
}
```

BTW, I know it works if I define the method descriptor using `descriptor.value` as below. Would like to know it is a bug for not able to define it through prototype.

```ts
let originalFunction = descriptor.value;
descriptor.value = function () {
    console.log(`Audit log comes here for ${methodName} method. `);
    originalFunction.apply(this, arguments);
};
```

Thanks.

**Comment by mhegazy** [comment]
This behaves as designed. if a decorator function does not return anything, we want to reinstall the descriptor. 
A decorator is not supposed to change the target, it is always expected to return a descriptor so that further decorators in the chain can get to witness the change.

**Comment by dev2geek** [comment]
Thanks @mhegazy .

According to your input, Is the following implementation not recommended as well? 
Currently it works.

```ts
function auditLogDecorator (target: any,
    methodName: string,
    descriptor?: PropertyDescriptor) {

    let originalFunction = target[methodName];

    let originalFunction = descriptor.value;
    descriptor.value = function () {
        console.log(`Audit log comes here for ${methodName} method. `);
        originalFunction.apply(this, arguments);
    };
}
```

Can you offer some samples as best practices for changing the target method behavior?

**Comment by dev2geek** [comment]
@mhegazy

**Comment by kitsonk** [comment]
This is not a support forum.

Questions should be asked at [StackOverflow](http://stackoverflow.com/questions/ask?tags=typescript) or on [Gitter.im](https://gitter.im/Microsoft/TypeScript).

**Comment by mhegazy** [comment]
you need to return the descriptor for it to be applied.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
