### ISSUE TITLE
Different rules for function parameter compatibility when assignment is on a different line to variable declaration.

### ISSUE THREAD

**Issue by Steve-Fenton** [Microsoft/TypeScript#1877]
A function can choose to omit parameters defined in a signature, as shown by function ```a``` below. Callers of ```a``` must still supply arguments, but the function does not need to use them.

Despite this, if the same function is assigned later in the program, this no longer applies and the identical function is now not compatible, as shown with function ```b```.

```typescript
interface X {
	(source: number): boolean;
}

var a: X = function() { return true; }

var b: X;
// Why is this an error?
var b = function() { return true; }
```
Shouldn't both of these cases follow the same rules?

**Comment by RyanCavanaugh** [comment]
This is an error because duplicate definitions of the same variable must have the *exact* same type.

It's similar to if you had written
```ts
var x: Animal;
var x: Dog;
```

If you removed the `var` keyword from the last line, you wouldn't see an error.

**Comment by Steve-Fenton** [comment]
Sorry about that one... I spent too long staring at the right-hand side of the code to realise the problem was on the left! Thanks Ryan.
