### ISSUE TITLE
Declaration files generated without strictNullChecks are incorrect

### ISSUE THREAD

**Issue by kujon** [Microsoft/TypeScript#18773]
**TypeScript Version:**  2.4.2

**Code**

Lack of `--strictNullChecks` causes nulls to be stripped out of the type definitions early:
```ts
/**
 * Resolves to:
 * type A = string;
 */
type A = string | null;
```

We run into a problem, when a type definition has to be reduced, for the purposes of generating a declaration file:

Source:
```ts
type A = string | null;

export default null as A;
``` 

Definition:
```ts
declare const _default: string;
export default _default;
```

**Expected behaviour:**
I'd expect that, while the type information can be stripped out for the purposes of type checking, it should remain original in the declaration files.

A practical example of that would be writing a React library:

React type def:
```ts
// ...
type ReactNode = ReactChild | ReactFragment | boolean | null | undefined;
// ...
```

MyComponent.tsx
```ts
import * as React from 'react';

type MyProps = {
  someProp: React.ReactNode | SomethingElse;
};

// ...

export default someHOC(MyComponent) as React.ComponentType<MyProps>;
```

This will result in `null` and `undefined` being dropped from the definition. IMHO the choices made by a developer wrt the flavour of type checking they like, should not result in invalid type definitions.

**Actual behaviour:**
Described above.

**Comment by mhegazy** [comment]
Without `--strictNullChecks`, types all have `null | undefined` in their domain. the flag changes how the compiler sees types. the declaration emitter uses the type system to serialize types that are inferred, and without `--strictNullChecks`, the type meaning is different.

The declaration emitter honors any explicit declaration (not type assertions). so if you authored your file as:

```ts
export type A = string | null;
const d: A = null;
export default d;
```

you should get the desired result.

**Comment by kujon** [comment]
Could the compiler possibly edit a warning in case when `--strictNullChecks` are disabled and it's about to reduce a definition for the purposes of the definition file? I feel like it would be much better than silently generating an invalid file.

Also, thank you for the workaround.

**Comment by RyanCavanaugh** [comment]
By the time we're emitting the .d.ts file, the `null`ness of any given type is long gone. We'd basically have to pretend SNC was on as an entirely separate compile phase since it potentially changes any type result.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
