### ISSUE TITLE
Compilation errors when implementing interfaces with all optional methods

### ISSUE THREAD

**Issue by rzio** [Microsoft/TypeScript#18782]
**TypeScript Version:**  2.5.2

**Code**

```ts
export interface IFoo {
    foo?(arg?: any): void;
    bar?(): void;
}

export class Foo implements IFoo{
    public baz(){
        
    }
}
```

**Expected behavior:**
Compiles, since all methods in IFoo are optional, so none have to be on the implementing class.
**Actual behavior:**
```
test.ts(6,14): error TS2559: Type 'Foo' has no properties in common with type 'IFoo'.
```

**Comment by RyanCavanaugh** [comment]
Our experience was that literally everyone writing this thought they were doing this:
```ts
export class Foo implements IFoo {
    // Declared but not present
    foo?(arg?: any): void;
    // Declared but not present
    bar?(): void;

    public baz(){
        
    }
}
```
When in fact they were doing this:
```ts
export interface IFoo {
    foo?(arg?: any): void;
    bar?(): void;
}

// Removed because implements IFoo does literally nothing
export class Foo {
    public baz(){
        
    }
}
```

Problematically, a class in this scenario can derive from `Foo` and declare an incompatible `bar()` method:
```ts
export interface IFoo {
    foo?(arg?: any): void;
    bar?(): void;
}

export class Foo implements IFoo{
    public baz(){
        
    }
}
export class CoolFoo extends Foo {
  bar(required: string) { /* uh oh */ }
}
```
Probably what you should write is this:
```ts
export class Foo {
    public baz(){
        
    }
}
// Copy down members of IFoo into Foo
interface Foo extends IFoo { }
```
Which is unintuitive but a necessary consequence of what `implements` actually does

**Comment by RyanCavanaugh** [comment]
See also discussion in https://github.com/ag-grid/ag-grid/issues/1708#issuecomment-312780483

**Comment by rzio** [comment]
I've mitigated the issue by adding an empty implementation of on of the methods.
If this is a known issue - I'm closing this bug.
