### ISSUE TITLE
What is the best go-to grammar for matching TypeScript?

### ISSUE THREAD

**Issue by jpaulin** [Microsoft/TypeScript#18787]
Should I use ABNF, BNF or some other to currently capture the 
grammar of TypeScript variables?

I'm looking to scan and/or refactor code, and thus building small prototype for evaluating the code first, a'la "yardstick" project (in Github also). I'm not yet so much into refactoring, but the capture fascinates me.

So, looking for the best practice in interpreting TypeScript, with or without the TypeScript language service.

**Finding brittle UI definitions e-xample**

Given the tool-to-be, and a sample code snippet:
```
const styles = StyleSheet.create({
    enclosingView: {
        flex: 1,
        flexDirection: 'column',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
        height: '100%',
    }
```

The brittle-finder would find line 
backgroundColor: '#FFFFFF'

because defining white color in HEX is a kind of no-no; a "magic number", if you wish. Other style attributes in this example are fine, they are relative measures, or defined constants.

It sufficies if there's a proper documentation already lying around, just point me to that. Thanks!

**Comment by kitsonk** [comment]
I suspect the easiest way would be to look at [VSCode's extension for TypeScript](https://github.com/Microsoft/vscode/tree/master/extensions/typescript).

**Comment by DanielRosenwasser** [comment]
Check out

* https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API
* https://github.com/Microsoft/TypeScript/wiki/Using-the-Language-Service-API
* https://palantir.github.io/tslint/develop/custom-rules/
