### ISSUE TITLE
Cannot find @angular modules from node_modules folder

### ISSUE THREAD

**Issue by vainamov** [Microsoft/TypeScript#18789]
**TypeScript Version:**  2.5.3 / insiders (2.5.3-insiders.20170919)
**VS Code Version:**  1.17.0-insider

**Code**

```ts
import { Component } from '@angular/core';
```

**Expected behavior:**
TypeScript should find the module as long as the node_modules folder is on the same level as the tsconfig.json file.

**Actual behavior:**
The module can't be found. When however you reference the location relative to the file the module is found, so this works:

```ts
import { Component } from '../node_modules/@angular/core';
```

**Further Information**
The project is a basic Angular project created by the angular-cli. It worked until the latest VS Code Insiders update.

**Comment by kitsonk** [comment]
This is not a support forum.

Questions should be asked at [StackOverflow](http://stackoverflow.com/questions/ask?tags=typescript) or on [Gitter.im](https://gitter.im/Microsoft/TypeScript).

**Comment by vainamov** [comment]
> This is not a support forum.

Neither is this a question. It's a bug report. Other people have already reported similar issues which ended up being fixed, and this one started to appear with the latest insider version of TypeScript included in VS Code.

**Comment by DanielRosenwasser** [comment]
Make sure you're using one or both of the following:

- moduleResolution: node
- module: es2015

**Comment by vainamov** [comment]
@DanielRosenwasser `moduleResolution: node` is set.

**Comment by mhegazy** [comment]
Can you share a self-contained repro. 

also can you verify that it is not https://github.com/Microsoft/vscode/issues/34681

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
