### ISSUE TITLE
Select initializaion of optional properties in object literal

### ISSUE THREAD

**Issue by NN---** [Microsoft/TypeScript#18788]
Is there a way or planned way to make optional property initialization in one statement ?

```ts
interface A {
 x: number;
 y?: number;
}

function f(y: boolean): A {
  const a: A = { x: 1 };
  if (y) a.y = 2;
  return a;
}
```

P.S.
Couldn't find the same suggestion in issues.

**Comment by RyanCavanaugh** [comment]
No. Any such kind of syntax would be a new ES feature and should be taken up there.
