### ISSUE TITLE
[REQ] option to remove console.log on compile

### ISSUE THREAD

**Issue by dehghani-mehdi** [Microsoft/TypeScript#18785]
Hello,

Thank you for great __TypeScript__, it would be nice to have an option to remove `console.log`s from compiled `.js` file.

Thanks,
Mehdi

**Comment by kitsonk** [comment]
This would be counter to the TypeScript [design goal](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals#goals):

> 7. Preserve runtime behavior of all JavaScript code.

And also touches on [non-goal](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals#non-goals):

> 2. Aggressively optimize the runtime performance of programs. Instead, emit idiomatic JavaScript code that plays well with the performance characteristics of runtime platforms.

There are already tools, usually code-minifiers, that do a much better job of dealing with something like that.  We should use the tools as they are designed.

**Comment by dehghani-mehdi** [comment]
Thanks for the comment.

I use typescript in my asp.net applications, as you know asp.net has (let say) built-in system for optimization codes (incl. js), so I think replacing that with npm or gulp is not a good idea. (I mean NPM or Gulp are great, I use them a lot, but not for all kind of projects)

**Comment by kitsonk** [comment]
I didn't say anything about `npm` or `gulp`.

**Comment by RyanCavanaugh** [comment]
Lots of tools available that don't need a type system or complex downleveling to accomplish this; we're not trying to be a Swiss Army Knife
