### ISSUE TITLE
Bad formatting for codefix to change extends to implements

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#18794]
**TypeScript Version:**  nightly (2.6.0-dev.20170927)

See the fourslash test `codeFixChangeExtendsToImplementsAbstractModifier.ts` and `codeFixChangeExtendsToImplementsWithDecorator.ts`.

**Code**

```ts
abstract class A extends I1 implements I2 { }
```

**Expected behavior:**

```ts
abstract class A implements I1, I2 { }
```

**Actual behavior:**

```ts
abstract class A implements I1 , I2 { }
```

**Comment by amcasey** [comment]
When fixing this, be careful not to break `abstract class A extends I1 /*hello*/ implements I2 { }`.

**Comment by amcasey** [comment]
The comma is inserted as a direct replacement for the `implements` keyword.  This results in a related problem:

```ts
abstract class A
    extends I1 /*hello*/
    implements I2 { }
```

becomes

```ts
abstract class A
    extends I1 /*hello*/
    , I2 { }
```

**Comment by amcasey** [comment]
More generally,
```ts
interface I1 { }
interface I2 { }

class MyClass /*A*/ //B
    /*C*/ extends /*D*/ I1 /*E*/ //F
    /*G*/ implements /*H*/ I2 /*I*/ //J
{
}
```

should probably become
```ts
interface I1 { }
interface I2 { }

class MyClass /*A*/ //B
    /*C*/ implements /*D*/ I1, /*E*/ //F
    /*G*/ /*H*/ I2 /*I*/ //J
{
}
```
