### ISSUE TITLE
Minor formatting issue with lambda parameters

### ISSUE THREAD

**Issue by jamiewinder** [Microsoft/TypeScript#1879]
Just a minor niggle, but it looks like lambda parameters have a slight formatting issue when following a comma:

```typescript
button.on("click",() => {...});
```

^ Visual Studio seems to be removing the space between the comma and parentheses. My formatting options at set to retain these, and it works for all other parameter types.

**Comment by awerlang** [comment]
That's a regression starting 1.4,  I think.

**Comment by vladima** [comment]
This is a known issues that was already fixed in #929d359bdfb880339845cb88df0bb959a89a9220
Just checked the most recent bits, everything works as expected
![spacebeforeparen](https://cloud.githubusercontent.com/assets/8052307/6006008/e0547a06-aac3-11e4-8159-09c6256e4dd9.gif)
