### ISSUE TITLE
Type of generic parameter is not correctly inferred from other generic parameter

### ISSUE THREAD

**Issue by lumaxis** [Microsoft/TypeScript#18796]
**TypeScript Version:**  2.5.3

**Code**

I have some code that is similar to the sample below. The problem reproduces in this [Playground](http://www.typescriptlang.org/play/#src=interface%20AppAttributes%20%7B%0D%0A%0D%0A%7D%0D%0A%0D%0Ainterface%20AppInstance%20%7B%0D%0A%0D%0A%7D%0D%0A%0D%0Ainterface%20Model%3CTInstance%2C%20TAttributes%3E%20%7B%0D%0A%7D%0D%0A%0D%0Aclass%20Helper%20%7B%0D%0A%20%20%20%20doSomething%3CM%20extends%20Model%3CI%2C%20A%3E%2C%20I%2C%20A%3E(entityModel%3A%20M)%3A%20Promise%3CI%5B%5D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20...%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aconst%20helper%20%3D%20new%20Helper()%3B%0D%0Aconst%20appModel%3A%20Model%3CAppInstance%2C%20AppAttributes%3E%20%3D%20%7B%7D%3B%0D%0Aconst%20result%20%3D%20helper.doSomething(appModel)).

```ts
interface AppAttributes {
}

interface AppInstance {
}

interface Model<TInstance, TAttributes> {
}

class Helper {
    doSomething<M extends Model<I, A>, I, A>(entityModel: M): Promise<I[]> {
        ...
    }
}

const helper = new Helper();
const appModel: Model<AppInstance, AppAttributes> = {};
const result = helper.doSomething(appModel)
```

**Expected behavior:**

The type of `result` is correctly inferred as `Promise<AppInstance[]>`

**Actual behavior:**

The return type is inferred as `Promise<{}[]>`

**Comment by RyanCavanaugh** [comment]
You have too many type parameters for what you're doing. Use this:
```ts
class Helper {
    doSomething<I, A>(entityModel: Model<I, A>): Promise<I[]> {
		return <any>null;
    }
}

const helper = new Helper();
const appModel: Model<AppInstance, AppAttributes> = <any>{};
const result = helper.doSomething(appModel)
```

**Comment by lumaxis** [comment]
Duh, that works too of course 🙂 Thanks a bunch!

Do you think my original example _should_ be working, even of overtly complicated?

**Comment by RyanCavanaugh** [comment]
There's not a direct link from the constraint to the other type parameter -- trying to do that tends to make inference worse rather than better. Since all (or nearly all) of the cases where you would want that to happen can be rewritten in terms of no constraint, we think the current behavior is the best option.

**Comment by lumaxis** [comment]
Makes sense. Thanks again!
