### ISSUE TITLE
private propierties implementing a interface

### ISSUE THREAD

**Issue by jmarianodella** [Microsoft/TypeScript#18792]
**TypeScript Version:**  2.5.2  / nightly (2.5.0-dev.201xxxxx)

**Code**

```ts

interface iFoo {
 foo: string;
}

class Foo implements iFoo {
 private _foo: string;
 set foo (s: string){
  this._foo = s;
 }
 get foo():string{
  return this._foo;
 }
}

```

**Expected behavior:**
tsc should ignore private properties and match Foo with iFoo
**Actual behavior:**
tsc generates error because _foo doesn't exists in iFoo

**Comment by andy-ms** [comment]
I don't get any compile errors from your example.

**Comment by kitsonk** [comment]
Huh?!

```
$ tsc --version
Version 2.4.2
$ cat test.ts
interface iFoo {
 foo: string;
}

class Foo implements iFoo {
 private _foo: string;
 set foo (s: string){
  this._foo = s;
 }
 get foo():string{
  return this._foo;
 }
}

$ tsc test.ts --target es5
```

No errors output...  [Works fine in playground too](https://www.typescriptlang.org/play/#src=interface%20iFoo%20%7B%0A%20foo%3A%20string%3B%0A%7D%0A%0Aclass%20Foo%20implements%20iFoo%20%7B%0A%20private%20_foo%3A%20string%3B%0A%20set%20foo%20(s%3A%20string)%7B%0A%20%20this._foo%20%3D%20s%3B%0A%20%7D%0A%20get%20foo()%3Astring%7B%0A%20%20return%20this._foo%3B%0A%20%7D%0A%7D%0A).

**Comment by jmarianodella** [comment]
I tried again in my code, and it woks. I don't know what's happening (may be leprechaun at home) I tried it for hours and I get excecution errors. 

All find, thanks for your time, my mistake.
