### ISSUE TITLE
Quoted enum member names are treated as numeric

### ISSUE THREAD

**Issue by kourge** [Microsoft/TypeScript#18799]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

**Code**

```ts
enum FileType {
  'pdf',
  text,
  'png'
}
```

**Expected behavior:**
Syntax error. `'pdf'` is not an identifier.

**Actual behavior:**
Emits:
```js
var FileType;
(function (FileType) {
    FileType[FileType["pdf"] = 0] = "pdf";
    FileType[FileType["text"] = 1] = "text";
    FileType[FileType["png"] = 2] = "png";
})(FileType || (FileType = {}));
```

**Notes:**
This is strictly speaking a behavioral surprise. A few human expectations lead up to this becoming a problem:
1. Prior to native string enum support, it should be unsurprising that any computed enum value (not assigned with `=`) will result in some number value, since enums are numbers.
1. Between TypeScript 2.2 and 2.4, third-party libraries like [`typescript-string-enums`](https://github.com/dphilipson/typescript-string-enums) filled the void of not having native string enum support by taking advantage of inference and mapped types. They also offer shorthand syntax, e.g. `X = Enum('a', 'b')` expands to `X = Enum({a: 'a', b: 'b'})`, whose native equivalent is `enum X { a = 'a', b = 'b' }`.
1. Starting in TypeScript 2.4, if an enum value has a string initializer, then all its sibling values must follow suit, making the entire enum a string enum. Otherwise the enum becomes a number enum.

All of these combined produce the incorrect human perception that `enum X { 'a', 'b' }` is shorthand for `enum X { a = 'a', b = 'b' }`, even though it is in fact equivalent to `enum X { a, b }`.

**Comment by RyanCavanaugh** [comment]
In all contexts where a name is not also introduced as a bare identifier, property names may be quoted. This is consistent with JS and consistent with how members in other contexts are declared. Regardless of whether that was the best decision (I think it was but you can disagree), it'd be a breaking change to alter the behavior now.

**Comment by kourge** [comment]
That is a good point. Luckily this is something that is preventable through `tslint`! Thanks for the explanation on consistency with other JS constructs.
