### ISSUE TITLE
No type error when setting an unknown property of React component using the spread operator

### ISSUE THREAD

**Issue by green2k** [Microsoft/TypeScript#18801]
**TypeScript Version:**  2.5.3

**Code**

```ts
interface IFooProps {
  key: string
  value: number
}

interface IBarProps {
  key: string
  value: number
  something: any
}

const Foo = (props: IFooProps) => {
  return (
    <div />
  )
}

const barProps: IBarProps = {
  key: 'foo',
  value: 1,
  something: 'something'
}

const Test1 = () => {
  // I'm setting the `something` property which isn't defined in the `Foo` component (compile-time error). This is a correct behavior.
  return <Foo key={barProps.key} value={barProps.value} something={barProps.something} />
}

const Test2 = () => {
  // However, I can set the `something` property using the spread operator and the TypeScript compiler will not throw any error ---> Is this a bug?
  return <Foo {...barProps} />
}
```

**Expected behavior:**

- Test1 throws the `[ts] Property 'something' does not exist on type 'IntrinsicAttributes & IFooProps'` error. 
- Test2 throws the `[ts] Property 'something' does not exist on type 'IntrinsicAttributes & IFooProps'` error. 

**Actual behavior:**
- Test1 throws the `[ts] Property 'something' does not exist on type 'IntrinsicAttributes & IFooProps'` error. 
- Test2 throws no error.

**Comment by RyanCavanaugh** [comment]
This is the intended behavior. It's pretty common to spread in a bunch of props into a child that only needs a properly-typed subset of them, and it's very annoying to "pick off" the extra properties when you know they're going to be safely ignored. However, if you manually specify an attribute that doesn't exist, it's almost certain that you're accidently misspelling a real attribute's name, which is certain to be an error.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Comment by green2k** [comment]
Hm, I thought the primary purpose of using Typescript is to have strict type checking. However, if this is an intended behavior, I can't rely on that anymore - because Typescript allows me to set some non-defined properties, which may introduce (and actually introduces) some bugs in my application.
