### ISSUE TITLE
Feature Request: Explicit destructuring function types 

### ISSUE THREAD

**Issue by ccorcos** [Microsoft/TypeScript#18808]
**TypeScript Version:**  2.5.2

**Code**

Most of the time Typescript does a great job inferring types so its possible to write a higher-order function with generic types representing the inputs and outputs a function. For example:

```ts
// Infers the inputs and outputs of a function
function f<X, Y>(fn: (x: X) => Y): (x: X) => Y {
	return fn
}

function g(x: number): string {
	return x.toString()
}

// result has type (x: number) => string as we'd expect
const result = f(g)
```

However, sometimes Typescript does not infer types well, such as https://github.com/Microsoft/TypeScript/issues/18807. In cases such as this, how are we supposed to explicitly define the generics of the function `f`?

The obvious example is `f<number, string>(g)` but that can be very tedious, especially the input type definition for `g` isn't defined separately and exported or if the output type of `g` is inferred.

A solution to this problem would be some way of destructuring the type of a function so I can pass `typeof g` as the generic argument to `f` like the following:

```ts
function f<(x:X) => Y>(fn: (x:X) => Y): (x: X) => Y {
	return fn
}

f<typeof g>(g)
```

**Comment by DanielRosenwasser** [comment]
@rbuckton has been experimenting with some stuff here, but I don't think we have a formal writeup/proposal I can point to yet.

**Comment by ccorcos** [comment]
Ok. It just seems weird that we can explicitly do the same that that the compiler can infer...
