### ISSUE TITLE
Feature Request: Infer React generic class type with JSX

### ISSUE THREAD

**Issue by ccorcos** [Microsoft/TypeScript#18807]
**TypeScript Version:**  2.5.2

**Code**

In the following example, I have a generic component with generic props and it would be awesome if the type of the component was inferred when using JSX.

```ts
interface XProps<T> {
	x: T
	fn: (x: T) => void
}

class X<T> extends React.Component<XProps<T>, {}> {}

const x = (
	<X
		x={1}
		fn={x => {
			// x is not inferred as a number
		}}
	/>
)
```

**Comment by DanielRosenwasser** [comment]
Related is #6395. The thing is that this is actually sort of a higher order operation on types as well, so this is either very React-specific or difficult to do.

**Comment by ccorcos** [comment]
I see. I suppose we can follow along with the other issue though. Thanks!

**Comment by andrewbranch** [comment]
For cross-referencing completeness, it seems that this sort of does work now, except for the bug demonstrated in #22636.
