### ISSUE TITLE
Compile-on-save does not honour const enums when declaration is in an external file

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/TypeScript#1880]
Hi,

**TS**: 1.4

To reproduce.

* Create a TypeScript project in Visual Studio with "Compile on save" set to on.
* Add file `enums.d.ts` with code:

  ```TypeScript
 declare module enums {
    const enum Bar {
        one = 0,
        two = 1,
    }
}
 ```
* Add file `foo.ts` with code:

 ```TypeScript
 /// <reference path="enums.d.ts" />
 var foo = enums.Bar.one;
 ```
* Compile the project and check that the output `foo.js` is correct:

 ```JavaScript
/// <reference path="enums.d.ts" />
var foo = 0 /* one */;
```
* Now trigger compile-on-save by saving `foo.ts`. 
* The output in `foo.js` is now broken:

 ```JavaScript
/// <reference path="enums.d.ts" />
var foo = enums.Bar.one;
```

The following point is relevant: If the enum declaration is moved to `foo.ts` then things work correctly.

This is a significant issue because the code fails with a runtime error.

**Comment by Stompf** [comment]
I had the same problem, it seems to be fixed in master. See https://github.com/Microsoft/TypeScript/issues/1812 and comment https://github.com/Microsoft/TypeScript/issues/1812#issuecomment-71576781 of how to build latest

**Comment by NoelAbrahams** [comment]
@Stompf, yes, looks to be a duplicate. Thanks.
