### ISSUE TITLE
When tsconfig allowJs is true webpack tries to build in an infinite loop

### ISSUE THREAD

**Issue by druzza** [Microsoft/TypeScript#18818]
Hello there ;)

I did create a simple aspnet-core with react and redux using VS2017 template and I just tried to add the allowJs equals to true. And then, the webpack do not stop rebuilding consuming all free memory on my laptop.

I'm just trying to work with .tsx and .jsx together while porting the current jsx codebase to tsx.

**TypeScript Version:**  2.4.1

**tsconfig.json**

```ts
{
  "compilerOptions": {
    "allowJs": true,
    "baseUrl": ".",
    "module": "es2015",
    "moduleResolution": "node",
    "target": "es5",
    "jsx": "react",
    "experimentalDecorators": true,
    "sourceMap": true,
    "skipDefaultLibCheck": true,
    "strict": true,
    "lib": [ "es6", "dom" ],
    "types": [ "webpack-env" ]
  },
  "exclude": [
      "bin",
      "node_modules"
  ]
}

```

**How can I get rid of this problem?**

Thanks in advance!

**Comment by DanielRosenwasser** [comment]
I don't think this is related to us, but do look into your loader's documentation.

One potential option to note is [entryFileIsJs](https://github.com/TypeStrong/ts-loader/tree/a89212d9ce6f83a50f58771582e68258a491057c#entryfileisjs-boolean-defaultfalse) for ts-loader

**Comment by druzza** [comment]
Thank you, Daniel, for point out that.
