### ISSUE TITLE
Type inference does not work array of functions accepting callbacks

### ISSUE THREAD

**Issue by lukehoban** [Microsoft/TypeScript#1881]
The following example, inspired by the [async](https://github.com/caolan/async#seriestasks-callback) library, infers `{}` for `T` in the call to `series`.  I don't see why it should not be able to infer `string`.

```TypeScript
interface AsyncResultsCallback<T> { (err: Error, results: T[]): void; }
interface AsyncResultCallback<T> { (err: Error, result: T): void; }
interface AsyncFunction<T> { (callback: AsyncResultCallback<T>): void; }

declare function series<T>(tasks: AsyncFunction<T>[], callback?: AsyncResultsCallback<T>): void;

series([
    function (callback) {
        callback(null, 'one');
    },
    function (callback) {
        callback(null, 'two');
    },
],
// results should have type string[], but is inferred to be {}[]
function (err, results) { });
```

Alternative version without named function types:

```TypeScript
declare function series<T>(tasks: Array<(callback: (err: Error, result: T) => void) => void>, callback: (err: Error, results: T[]) => void): void;

series([
    function (callback) {
        callback(null, 'one');
    },
    function (callback) {
        callback(null, 'two');
    },
],
// results should have type string[], but is inferred to be {}[]
function (err, results) { });
```

**Comment by RyanCavanaugh** [comment]
It'd be a big leap to start analyzing function bodies to add additional inference sites for generic type inference.

**Comment by DanielRosenwasser** [comment]
Hey Luke, that would be because we don't infer from the usage - we only contextually type `callback` as an `AsyncResultCallback<T>`. Since there's no candidate for `T` when we infer type arguments, we resort to `{}`. This seems by design.

**Comment by lukehoban** [comment]
Yeah, that makes sense, my bad - I recall it has always been the case that inferentially checking function expression arguments causes type parameters to be fixed before the function expression is checked.  It's a shame, since typechecking the function body under the contextually inferred type would provide the right candidate for T.
