### ISSUE TITLE
No escape and unescape methods in lib.d.ts

### ISSUE THREAD

**Issue by k8w** [Microsoft/TypeScript#18813]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)
2.6.0-dev.20170926

**Code**

```ts
let a = escape('aaa');
unescape(a);
```

**Expected behavior:**
Compile succ

**Actual behavior:**
Compile error

**Comment by wrager** [comment]
> The escape() function (or unescape) was deprecated in JavaScript version 1.5. Use encodeURI() or encodeURIComponent() instead.

https://www.w3schools.com/jsref/jsref_escape.asp
https://www.w3schools.com/jsref/jsref_unescape.asp

**Comment by wbhob** [comment]
MDN actually lists escape and unescape as valid ESNext functions, FYI. Working on a PR

**Comment by mhegazy** [comment]
This behavior is intentional. Please see https://github.com/Microsoft/TypeScript/issues/8639#issuecomment-219834320.

You can always define:

```ts
declare function escape(s:string): string;
declare function unescape(s:string): string;
```

**Comment by k8w** [comment]
Have seen #8639 and find nothing about *deprecated* here.
[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/escape](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/escape)

**Comment by kitsonk** [comment]
*Copying comment from other thread*

@k8w those pages used to refer to it being deprecated, and it was.  It does not appear to be deprecated in the [current standard](https://tc39.github.io/ecma262/#sec-escape-string) though, and I can't find a specific reference to why the change was made. I suspect they were retained in the specification to not break code, but you shouldn't be using them for new code as they don't handle [Unicode URIs properly](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/unescape), and so IMO they are best to leave out and people can add them back in if they are supporting old code.

**Comment by mhegazy** [comment]
Please see comment in https://github.com/Microsoft/TypeScript/issues/8639#issuecomment-337660621

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Comment by wbhob** [comment]
My PR got merged! This issue has been fixed.
