### ISSUE TITLE
returning value directly from function differs from using a temporary variable

### ISSUE THREAD

**Issue by bronson** [Microsoft/TypeScript#18812]
**TypeScript Version:**  2.5.2

**Code**

```ts
type ClassifierPromise = Promise<string|boolean>      // parameter type
var ClassifierPromise: PromiseConstructor = Promise   // or new won't work

function works(): ClassifierPromise {
  return new ClassifierPromise((resolve,reject) => { })
}

function fails(): ClassifierPromise {
  let p = new ClassifierPromise((resolve,reject) => { })
  return p  // this line throws the error
}
```

**Expected behavior:**
Because the two functions should be equivalent, I'd expect them to compile identically: either both working, or both throwing the same error.

**Actual behavior:**
The `works()` function compiles without issue, but the `fails()` function prints:

```
tt.ts(10,3): error TS2322: Type 'Promise<{}>' is not assignable to type 'Promise<string | boolean>'.
  Type '{}' is not assignable to type 'string | boolean'.
    Type '{}' is not assignable to type 'false'.
```

Compiled with:

```
tsc --module es6 --target es6 --noImplicitReturns --strict --outDir /tmp
```

**Comment by DanielRosenwasser** [comment]
It's unfortunate, but this is working as intended right now.

This is because in `works`, the return expression is *contextually typed* from the return type annotation.

In `fails`, we don't propagate the type backwards or try to unify. `ClassifierPromise` has no candidates for type arguments when you `new` it up, so you end up with the declared type of `p` being `Promise<{}>`.

**Comment by bronson** [comment]
Ah, now that you say that, it does makes sense that type inference wouldn't swim that far back upstream.

Agreed, it would be very nice to attach the concrete type to the variable declaration.

Until then, I guess I need to add `as ClassifierPromise` to inject the correct types into the `new` clause?  TypeScript seems to think that this makes sense but I'm not sure if I'm just papering over a more fundamental problem here...

```ts
function fails(): ClassifierPromise {
  let p = new ClassifierPromise((resolve,reject) => { }) as ClassifierPromise
  return p  // this line throws the error
}
```

Huge thanks for your prompt reply!

**Comment by bronson** [comment]
Actually, there's no need for the ClassifierPromise variable if I'm asserting the type anyway.

```ts
  let p = new Promise((resolve,reject) => { }) as ClassifierPromise
```

Still not great but I can live with it.  :)  Closing this issue, thanks for restoring my sanity.

I guess this led to two potential feature requests...

* type inference should propagate all the way back to the variable declaration
* defining a concrete constructor should propagate to the objects created by the constructor

Happy to file an issue / discuss either of those further.
