### ISSUE TITLE
Make periodic pre-release builds available on npm

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#1882]
We should be making preview releases on npm available, preferably in an automated fashion.

As discussed a bit on #1818.

Seems like this should have the 1.5 milestone (but should begin prior to 1.5's release, as would be appropriate).

**Comment by RyanCavanaugh** [comment]
I believe the only outstanding question we had here was how to do this in a way that people who didn't specify a version number in their package.json didn't automatically upgrade to some possibly-unstable TypeScript build.

**Comment by Arnavion** [comment]
Assuming you'll use prerelease tags (eg `1.5.0-prerelease.2015.02.02.abcd`) npm will never choose this to install unless the requested version also contains a prerelease tag. See https://github.com/npm/node-semver#prerelease-tags for details.

Prerelease tags are also considered less than their corresponding release, so the above would be less than 1.5.0 when it's actually released. From the semver spec:

>1.0.0-alpha < 1.0.0-alpha.1 < 1.0.0-alpha.beta < 1.0.0-beta < 1.0.0-beta.2 < 1.0.0-beta.11 < 1.0.0-rc.1 < 1.0.0

Can you detail what version format you're going to use for the prereleases?

**Comment by danielearwicker** [comment]
:+1: very keen to have this!

**Comment by RyanCavanaugh** [comment]
Let's figure out what the right way to do this is.

**Comment by DanielRosenwasser** [comment]
This appears to be a duplicate of #964.
