### ISSUE TITLE
TypeScript中文网 文本错误

### ISSUE THREAD

**Issue by CyanGlory** [Microsoft/TypeScript#18835]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**Expected behavior:**
typscript中文网 > 文档 > 辅导教程 > javascript 迁移 > this没有隐式的any > 代码部分:
构造函数应写成了: constructor
**Actual behavior:**
构造函数实际写成了: constuctor, 少了一个 `r`

**Comment by CyanGlory** [comment]
附加 

1. Point 这个类的 distanceFromOrigin 方法中 `point: Point` 参数 并没有被使用.
2. getDistance 这个方法传入一个{ x: 0, y:0 }的字面量参数将会得到一个 
```
[ts]
Argument of type '{ x: number; y: number; }' is not assignable to parameter of type 'Point'.
  Property 'getDistance' is missing in type '{ x: number; y: number; }'.
```
建议修改成如下写法:
```js
Point.prototype.distanceFromOrigin = function(this: Point) {
  const point = new Point(0, 0);
  return this.getDistance(point);
}
```

**Comment by plantain-00** [comment]
This repository doesn't maintain the site, what you want is: http://bbs.tslang.cn/ , you can issue this there.

**Comment by CyanGlory** [comment]
thanks for your suggestion! 😁
