### ISSUE TITLE
Template literal can't use as enum member.

### ISSUE THREAD

**Issue by brn** [Microsoft/TypeScript#18837]
**TypeScript Version:**  2.6.0-dev.20170922

**Code**

```ts
const value = "foo";
enum Test {
  TEST = `${value}`
}
```

**Expected behavior:**

Compiled.

**Actual behavior:**

error TS2322: Type 'string' is not assignable to type 'Test'.

Is this intended design?
If that, I want to suggest constant template literal type inference as below. 
```ts
const value = 'a'
const test_1 = `${value}` // test_1's type is  'a'
const test_2 = `${value}/b` // test_2's type is  'a/b'

declare function getExternalValue(): string;
const externalValue = geEtxternalValue();
const test_3 = `${externalValue}/c` // test_3's type is 'string'.

enum Test {
  TEST_1 = test_1 // OK.
  TEST_2 = test_2 // OK.
  TEST_3 = test_3 // error TS2322: Type 'string' is not assignable to type 'Test'.
}
```

And if above suggestion is possible, I would like to propose concatenated string literal type inference like below.

```ts
const value = 'a'
const test_1 = value + '/b' // test_1's type is  'a/b'

declare function getExternalValue(): string;
const externalValue = geEtxternalValue();
const test_2 = externalValue + '/c` // test_2's type is 'string'.

enum Test {
  TEST_1 = test_1 // OK.
  TEST_2 = test_2 // error TS2322: Type 'string' is not assignable to type 'Test'.
}
```

**Comment by kitsonk** [comment]
Any computed values are not allow as values in an enum, so even variables with literal types are not allowed at the moment.  A string literal is a computed value.

I suspect the feedback will be that this is a lot work to implement with not that much value.  It would require:

* Allowing variables with single literal types of number or string as values in an enum.
* Changing the inference of string literals where the literal is composed of a finite number of literal types plus other random strings as a literal type (potentially including understanding the implicit coercion rules).

**Comment by brn** [comment]
@kitsonk 
I see...
I was thinking it's more easy job, but it seems actually it's hard.
Ok, If implements this proposal is easy it's worth to implements, but unworth if it's hard to implements.
I understood.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
