### ISSUE TITLE
Extract method not shown for selection with variables

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#18855]
From https://github.com/Microsoft/vscode/issues/35388

**TypeScript Version:**  2.6.0-dev20170929

**Code**
For the following code:

```ts
function foo() {
    const a = 'a'
    const ab = a + 'b';
    return ab + 'c';
}
```

Select  the lines:

```
    const a = 'a'
    const ab = a + 'b';
```

**Expected behavior:**
Extract method option is shown. Resulting after extract would look something like:

```ts
function foo() {
    const ab = newFunction()
    return ab + 'c';
}

function newFunction() {
    const a = 'a'
    return a + 'b';
}
```

**Actual behavior:**
No extract method refactoring is returned

**Comment by RyanCavanaugh** [comment]
@amcasey behavior tweak for you to consider

**Comment by amcasey** [comment]
The "error" preventing this from working now is `CannotExtractExportedEntity` in `checkForUsedDeclarations`.
