### ISSUE TITLE
Generics extending from class and interface

### ISSUE THREAD

**Issue by davetayls** [Microsoft/TypeScript#1885]
Given the following code where an interface `extends` a class I would expect specifying a Model which does not extend from that class `Model` to fail the compile.

```typescript
class Model {}
interface IHasImage extends Model {
  imageUrl: () => string; 
}
class ModelOther {}
class ModelImplButNotExtends {
  imageUrl():string {
	  return '';
  }	
}
class ModelCorrect extends Model {
  imageUrl():string {
	  return '';
  }		
}
class View<T extends IHasImage> {
	constructor(){
		this.model.imageUrl();
	}
	model:T;
}

// should fail
var other = new View<ModelOther>(); 
// should fail
var implementsButNotExtends = new View<ModelImplButNotExtends>();
// should succeed 
var both = new View<ModelCorrect>(); 
```

As you can see from the playground, the compilation doesn't fail for the line:

```typescript
27: var implementsButNotExtends = new View<ModelImplButNotExtends>();
```

![image](https://cloud.githubusercontent.com/assets/151695/6000310/4f30cfd2-aad4-11e4-8655-b43beb76a2b4.png)

**Comment by RyanCavanaugh** [comment]
TypeScript uses a structural type system, so empty types like `Model` are effectively wildcards in terms of assignability. If you add a member to `Model` you'll see an error.

**Comment by davetayls** [comment]
Ah, I see that makes sense ... thanks for the clarification
