### ISSUE TITLE
Suggestion: a better way to handle enums in generic functions

### ISSUE THREAD

**Issue by Ghabriel** [Microsoft/TypeScript#18869]
Currently, there's no "easy" way to write a generic function that takes an enum as input/generic parameter and returns one of its constants. Consider the following example, which shows a way to almost accomplish it:

```ts
enum Color {
    RED = "#FF0000",
    GREEN = "#00FF00",
    BLUE = "#0000FF"
}

declare function randomKey<T>(object: T): keyof T;

// One overload for numeric enums and one for string enums
function randomEnumValue<E extends {[P in keyof E]: number}>(enumObject: E): number;
function randomEnumValue<E extends {[P in keyof E]: string}>(enumObject: E): string;

function randomEnumValue(enumObject: any): any {
    return enumObject[randomKey(enumObject)];
}

declare function doSomethingWithColor(color: Color);

let color = <Color> randomEnumValue(Color);
doSomethingWithColor(color);
```

The problem with this approach is that every call to `randomEnumValue` requires a cast to the enum type (the code would compile if `Color` was a numeric enum but `color` would still be a `number`, not a `Color`). Also note that two overloads were required and the generic restriction `E extends {[P in keyof E]: number}` allows a lot of undesired types (i.e non-enums).

I suggest the following version:
```ts
function randomEnumValue<T, E extends enum<T>>(enumObject: typeof E): E {
    return enumObject[randomKey(enumObject)];
}
```

Here, `T` is the underlying type of the enum (currently, that means either `number` or `string`). `enum<T>` is a special type used to restrict a generic parameter to an enum of underlying type `T`. Also note that the parameter `enumObject` has type `typeof E`, which I think is currently not allowed and therefore is also part of my suggestion. That example would make it unnecessary to put a cast when calling that function, e.g

```ts
// calls randomEnumValue<string, Color>(enumObject: typeof Color): Color
let color = randomEnumValue(Color);
// color has type Color
```

Another possibility that crossed my mind is something like this:
```ts
function randomEnumValue<T, E extends enum<T>>(enumObject: E): EnumMember<E> {
    return enumObject[randomKey(enumObject)];
}
```

This might be easier to implement and I'm not sure which way would be preferable, but I feel like the overall idea of this suggestion would make enums better to manipulate.

**Comment by ahejlsberg** [comment]
It already works without any overloads:

```ts
enum Color {
    RED = "#FF0000",
    GREEN = "#00FF00",
    BLUE = "#0000FF"
}

declare function randomKey<T>(object: T): keyof T;

function randomEnumValue<T>(enumObject: T) {  // Inferred return type is T[keyof T]
    return enumObject[randomKey(enumObject)];
}

let color = randomEnumValue(Color);  // Inferred type is Color
```

The inferred return type for `randomEnumValue` is `T[keyof T]` which for an enum object is the enum type, precisely what you want. Of course it also works if you add a type annotation:

```ts
function randomEnumValue<T>(enumObject: T): T[keyof T] {
    return enumObject[randomKey(enumObject)];
}
```

**Comment by Ghabriel** [comment]
Thanks, totally forgot about T[keyof T]... I still think that it would be useful to restrict a function to only accept enums, but considering that your example works I can't really think of a good use case right now. If anyone can think of a good use case, feel free to reopen this issue.
