### ISSUE TITLE
Suggestion: Type predicates + union types (| false)

### ISSUE THREAD

**Issue by fread2281** [Microsoft/TypeScript#18870]
It would be nice to be able to write
```typescript
function filter<X, Y extends X>(list: X[], pred: (x: X) => (x is Y | false)): Y[] {
  let out = [];
  for (const k of list) {
    if (pred(k)) {out.push(k)}
  }
  return out
}
```

**Comment by DanielRosenwasser** [comment]
Can you elaborate on what that would mean?

**Comment by fread2281** [comment]
Nevermind, it looks like this is possible today. You can't do `let test: ((x: string) => x is "foo") = (x) => false;` which made me think that type predicates couldn't return false if the value might have the type, but ``function test(x: string): x is "foo" { return false;}` works.
