### ISSUE TITLE
tsc --watch unnecessarily crashes when package.json / tsconfig.json is being edited

### ISSUE THREAD

**Issue by ORESoftware** [Microsoft/TypeScript#18873]
I am on `tsc Version 2.3.4`

when for example tsconfig.json is being edited, and say I have an accidental trailing comma that I am about to remove but I save the file beforehand, there will be an a JSON error:

`error TS5014: Failed to parse file '/Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman-utils/tsconfig.json': Unexpected token ] in JSON at position 160.`

`tsc --watch` will crash when the is a JSON formating error.

instead maybe wait 10 seconds for the file to be changed again and then retry?

**Comment by mhegazy** [comment]
We recentelly rewrite the `tsc --watch` implementation. can you give `typescript@next` a try.

**Comment by mhegazy** [comment]
seems fixed in latest:

```sh
c:\test\18873>
tsc --w

10:41:19 - Compilation complete. Watching for file changes.

10:41:37 - File change detected. Starting incremental compilation...

tsconfig.json(5,1): error TS1005: '}' expected.
tsconfig.json(3,19): error TS5024: Compiler option 'target' requires a value of type string.
10:41:37 - Compilation complete. Watching for file changes.


10:41:52 - File change detected. Starting incremental compilation...


10:41:55 - Compilation complete. Watching for file changes.

```

**Comment by ORESoftware** [comment]
@RyanCavanaugh  you like that
