### ISSUE TITLE
Type signature for JSON.stringify does not include undefined in the return type

### ISSUE THREAD

**Issue by MazeChaZer** [microsoft/TypeScript#18879]
Although calling `JSON.stringify` may return undefined (as documented here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#Description), it is not included in the type signature provided with TypeScript.

**Comment by MazeChaZer** [comment]
This is also true for Edge:

> Values that do not have JSON representations, such as `undefined`, will not be converted.

https://docs.microsoft.com/en-us/scripting/javascript/reference/json-stringify-function-javascript

**Comment by mhegazy** [comment]
So we need a new overload for `stringify(value: undefined, .....): undefined;` ?

**Comment by MazeChaZer** [comment]
Thanks for the quick response!

That could work, please note that `JSON.stringify(function() {})` also results in `undefined`.
Perhaps I should explain why this was a problem for me: I wrote an error handling function that would display JSON data

```ts
function showError(value: any): string {
    const json = JSON.stringify(value);
    // ...
    // Later in the code, a string function was used
    const lines = json.split('/n');
    // This is where I got the runtime exception
}
```
Would the overload catch this possible runtime error?

Something that would definitly work for me is a union return type that includes `undefined`, like so
```ts
stringify(value: any /* space, replacer, ... */): string | undefined
```
But of course I don't know conventions or guidelines for the type annotations very well, so this might be too broad.

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by MazeChaZer** [comment]
👍 Will do

**Comment by bradleyayers** [comment]
I just discovered a production bug that this would have caught. Any updates on it @MazeChaZer?

**Comment by NN---** [comment]
@mhegazy I suggest having both return value string|undefined and additional overload for undefined|Function to catch issues at compile time.

**Comment by greyblake** [comment]
Any progress on this one? (I got my fingers burned with this today)

**Comment by polkovnikov-ph** [comment]
@RyanCavanaugh Can we triage this? There's no movement on the critical issue for 5 years.

**Comment by ronyhe** [comment]
Here's a PR for this issue: https://github.com/microsoft/TypeScript/pull/51897
This is my first attempt at contributing to the TS repo, advice and/or corrections would, of course, be welcome

**Comment by ronyhe** [comment]
> Here's a PR for this issue: #51897 This is my first attempt at contributing to the TS repo, advice and/or corrections would, of course, be welcome

Ready for review

**Comment by ronyhe** [comment]
Any updates?
@MartinJohns Is there anything I should be doing to advance this?

**Comment by ecyrbe** [comment]
@sandersn can you reopen this bug since the PR got reverted ?

**Comment by RyanCavanaugh** [comment]
Having tried this and [looked into it more](https://github.com/microsoft/TypeScript/issues/52296#issuecomment-1398071491), I don't think we're going to try this again. People can add this line to their project to opt into this behavior if they want it:
```ts
interface JSON { stringify(s: any): string | undefined; }
```
but if we add this today, there is no real way to opt back in to today's behavior.

However, if at some point we make a "stricter" version of the core lib, this would definitely be a change to consider in that feature

**Comment by DetachHead** [comment]
> if at some point we make a "stricter" version of the core lib,

is there an open issue for this?

**Comment by KotlinIsland** [comment]
This is resolved in ts-reset here: https://github.com/total-typescript/ts-reset/pull/21

**Comment by silverwind** [comment]
> [@sandersn](https://github.com/sandersn) can you reopen this bug since the PR got reverted ?

I agree, this should be reopened. Just because it "breaks code" is not a reason to not fix it.

**Comment by RyanCavanaugh** [comment]
https://github.com/Microsoft/TypeScript/wiki/FAQ#this-is-closed-but-should-be-open-or-vice-versa
