### ISSUE TITLE
Improve Object.{keys,values,entries} static method signatures

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#18874]
**TypeScript Version:**  master

**Code**

```diff
-    keys(o: {}): string[];
+    keys(o: any): string[];
-    values<T>(o: { [s: string]: T }): T[];
+    values<T>(o: { [s: string]: T } | { [n: number]: T }): T[];
-    entries<T>(o: { [s: string]: T }): [string, T][];
+    entries<T>(o: { [s: string]: T } | { [n: number]: T }): [string, T][];
```

**Comment by mhegazy** [comment]
`keys(o: any): string[];` allows for `keys(undefined)` and `keys(null)` which are runtime errors.

**Comment by mhegazy** [comment]
the other overloads seem reasonable.

**Comment by RyanCavanaugh** [comment]
Do we want `keys(o: object)` instead?

**Comment by mhegazy** [comment]
`Object.keys(1)` is `[]` ... so not sure if we want to allow that or not.

**Comment by RyanCavanaugh** [comment]
The spec *appears* to call that an error

> 15.2.3.14 Object.keys ( O )

> When the keys function is called with argument O, the following steps are taken:

> If the Type(O) is not Object, throw a TypeError exception.

But there's no error in Edge or Chrome. Checking with Brian

**Comment by RyanCavanaugh** [comment]
Apparently the 5.1 spec says to throw an error but the 6.0 spec specifies an implicit conversion to `object`. So I'd say disallow

**Comment by falsandtru** [comment]
Do you want this?

```ts
    keys(o: undefined | null): never;
    keys(o: any): string[];
```

**Comment by mhegazy** [comment]
> Do you want this?

No. this allows things like `var x: string[] = Object.keys(null);` to pass compilation, but fail at runtime.

**Comment by falsandtru** [comment]
I think we have no way to resolve that using current type system.

**Comment by mhegazy** [comment]
> I think we have no way to resolve that using current type system.

why is that? `keys(o: {}): string[]` seems to model the behavior correctly.

**Comment by falsandtru** [comment]
I didn't know that improved behavior of `{}`. Then the changes we need is only `values` and `entries` methods?

**Comment by falsandtru** [comment]
Fixed my PR.
