### ISSUE TITLE
Optional Type Bug

### ISSUE THREAD

**Issue by kgtkr** [Microsoft/TypeScript#18878]
**TypeScript Version:**  2.5.3

**Code**

```ts
//a is {x?:number}
const b = { ...a };
```

**Expected behavior:**
b is {x?:number}

**Actual behavior:**
b is {x?:number|undefined}

**Comment by aluanhaddad** [comment]
Optionality implies that a property may take the value `undefined`. The expanded form of the type of the property is a union that includes `undefined`.

**Comment by kgtkr** [comment]
Thanks
