### ISSUE TITLE
Proposal:partial generics

### ISSUE THREAD

**Issue by kgtkr** [Microsoft/TypeScript#18880]
I want to omit it when the compiler can type infer
# Example

```ts
Observable.of(1,2,'str')
  .filter<number|string,number>((x):x is number=>typeof x==='number');
```

# Partial generics

```ts
Observable.of(1,2,'str')
  .filter<*,number>((x):x is number=>typeof x==='number');
```

# More Better

```ts
Observable.of(1,2,'str')
  .filter<*,*>((x):x is number=>typeof x==='number');
```

**Comment by aluanhaddad** [comment]
I'm surprised you need to specify the types at all in these situations. I thought that API (if you are using RxJS) was fairly overloaded to infer unions. Any way you can get a lot of this with default generic parameters. if the Declaration is such that the consumer must regularly Supply explicit type arguments at the call site then the API needs to be heavily reworked.

**Comment by kgtkr** [comment]
Array#filter will also be better

# Example

```ts
[1,2,'str']
  .filter<number>((x):x is number=>typeof x==='number');
```

# Partial generics

```ts
[1,2,'str']
  .filter<*>((x):x is number=>typeof x==='number');
```

**Comment by kgtkr** [comment]
# rxjs

https://github.com/ReactiveX/rxjs/blob/master/src/operator/filter.ts#L6

```ts
export function filter<T, S extends T>(this: Observable<T>,
                                       predicate: (value: T, index: number) => value is S,
                                       thisArg?: any): Observable<S>;
```

**Comment by RyanCavanaugh** [comment]
Duplicate #10571 ?

**Comment by kgtkr** [comment]
OK.Thanks!
