### ISSUE TITLE
Don't exclude node_modules by default

### ISSUE THREAD

**Issue by jez9999** [Microsoft/TypeScript#18884]
There is a perfectly good use-case for transpiling a `node_modules` directory.  As far as I can tell, it's the only way you can `include` your own ES6 modules without using relative paths, which can be messy and hard to maintain.  So you setup a directory structure like this:

```
src /
    node_modules /
        modules /
            myModule.ts
    scripts /
        init.ts
```

And you want it to be transpiled by TypeScript into this:

```
dist /
    node_modules /
        modules /
            myModule.js
    scripts /
        init.js
```

This then allows you to refer to your module from any code under `src` (such as `init.js`) using:

`import myModule from "modules/myModule";`

... rather than having to use a relative path.  Because TypeScript and Node.js go up the directory tree looking for `node_modules` directories, they will find this one before the main NPM one, which should be at least a directory higher, in the project's root directory.

However, this all requires that TypeScript not ignore the `node_modules` directory that we've created in `src`.  Considering that developers will probably tell TypeScript to transpile stuff in a `src` directory anyway, it won't include the main NPM `node_modules` so I suggest that `node_modules` shouldn't be excluded by default, which would allow this scenario to work.

**Comment by andy-ms** [comment]
Packages written in TypeScript shouldn't be distributed just as TypeScript source code; then they couldn't be used by JavaScript users. They should instead be distributed as plain JS code with generated `.d.ts` files alongside for TypeScript consumers. This also avoids making consumers re-compile your library, since compile times are bad enough already. See the [--declaration](http://www.typescriptlang.org/docs/handbook/compiler-options.html) compiler option.
When a package is distributed this way there's no need to use relative paths; [module resolution](http://www.typescriptlang.org/docs/handbook/module-resolution.html) should find the correct `.d.ts` file for you.

**Comment by jez9999** [comment]
What do you mean by package?  When I say "module" I just mean a `.ts` file that has an `export` in it; no associated `package.json`.  They are just being used by my own other modules so distributing for "JavaScript users" doesn't really seem to apply.  I'm transpiling all my modules at the same time and I'm not publishing any of them to NPM.

**Comment by andy-ms** [comment]
OK, I didn't realize that it was just a directory that happened to be named `node_modules`.
You can turn on compilation for that with `"include": ["src", "src/node_modules"]`.
We wouldn't enable compilation of `node_modules` by default though, since that would be a breaking change for most users.

**Comment by jez9999** [comment]
Right - but is there a better way to achieve what I want to achieve?  Even you were fooled into thinking that was the `npm` node_modules directory which rather suggests it's not meant to be created for your own private ES6 modules?

**Comment by andy-ms** [comment]
The typical way is to use relative paths -- don't know why you find them hard to maintain?
You can also use the [`paths`](http://www.typescriptlang.org/docs/handbook/compiler-options.html) compiler option and configure your module loader to do whatever you want, but that's probably a more difficult option than using relative module paths.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
