### ISSUE TITLE
Formatter gets lost chaining functions as callbacks.

### ISSUE THREAD

**Issue by awerlang** [Microsoft/TypeScript#1888]
I have the following code:

```ts
    query(id: number) {
        return this.$http
            .get('/api/Entity/' + id)
            .then(function (data) {
            return data.data;     // (a)
        });                       // (b)
    }
```

When  I type the semi-colon at point (a), it gets correctly indented. When a type a semi-colon at point (b), both lines get 4 columns to the left, which is the same output when a format the whole document.

I must add it gets on my nerves.

Any way to avoid it? Tks

**Comment by SaschaNaz** [comment]
So, according to #2651, will a test be helpful for this?

**Comment by mhegazy** [comment]
Tests are always welcomed.
