### ISSUE TITLE
Why the type system does not support the use of property to select subtypes？

### ISSUE THREAD

**Issue by xiaocaibird** [Microsoft/TypeScript#18881]
Only support to use of "index".

```
type t = {
     a: {
        c: string
    },
    b: string
}

type a1 = t.a;  //error
type a2 = t['a'];  //ok
```

I must operate many times when I want rename "t['a']".
How to make it more convenient？

**Comment by andy-ms** [comment]
The problem with `type a1 = t.a` is that `t` might be merged with a namespace with an export named `a`.
But we should support typed indexed accesses in find-all-references.

**Comment by DanielRosenwasser** [comment]
Luckily we do the right thing now thanks to https://github.com/Microsoft/TypeScript/pull/17462

![indexedaccess](https://user-images.githubusercontent.com/972891/31096916-6775313a-a772-11e7-9042-e2d7429d060a.gif)

**Comment by xiaocaibird** [comment]
@andy-ms @DanielRosenwasser I see, thank you all

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
