### ISSUE TITLE
Hard-to-diagnose "Cannot find global type 'Symbol'." error

### ISSUE THREAD

**Issue by andy-ms** [microsoft/TypeScript#18893]
**TypeScript Version:**  nightly (2.6.0-dev.20170930)

**Code**

```ts
interface A {
    m(x: string): void;
}

declare class B {
    m(x: string | symbol): void;
}

declare class C extends B implements A {}
```

Compile with `--lib es5 --target es6`.

**Expected behavior:**

A useful error message, containing a location of the error, and a suggestion of how to fix it.
Alternately, no error, since this code is correct.

**Actual behavior:**

```
error TS2318: Cannot find global type 'Symbol'.
```

It looks like this will be hard to fix because the error happens in type comparison; but this error was very difficult to track down so it would be nice to get an error location.

**Comment by begincalendar** [comment]
I believe this is the stacktrace for the issue:
```
resolveNameHelper (checker.ts:1161)
resolveName (checker.ts:890)
getGlobalSymbol (checker.ts:7100)
getGlobalTypeSymbol (checker.ts:7095)
getGlobalType (checker.ts:7106)
getGlobalESSymbolType (checker.ts:7123)
getApparentType (checker.ts:6085)
getPropertiesOfType (checker.ts:5922)
isRelatedTo (checker.ts:8968)
eachTypeRelatedToType (checker.ts:9192)
isRelatedTo (checker.ts:8998)
compareSignaturesRelated (checker.ts:8589)
signatureRelatedTo (checker.ts:9720)
signaturesRelatedTo (checker.ts:9689)
structuredTypeRelatedTo (checker.ts:9460)
recursiveTypeRelatedTo (checker.ts:9300)
isRelatedTo (checker.ts:9025)
propertiesRelatedTo (checker.ts:9559)
structuredTypeRelatedTo (checker.ts:9458)
recursiveTypeRelatedTo (checker.ts:9300)
isRelatedTo (checker.ts:9025)
checkTypeRelatedTo (checker.ts:8853)
checkTypeAssignableTo (checker.ts:8502)
checkClassLikeDeclaration (checker.ts:21693)
checkClassDeclaration (checker.ts:21610)
checkSourceElement (checker.ts:22750)
forEach (core.ts:186)
checkSourceFileWorker (checker.ts:22841)
checkSourceFile (checker.ts:22815)
forEach (core.ts:186)
getDiagnosticsWorker (checker.ts:22917)
getDiagnostics (checker.ts:22880)
getEmitResolver (checker.ts:534)
emitWorker (program.ts:1162)
(anonymous) (program.ts:1115)
runWithCancellationToken (program.ts:1238)
emit (program.ts:1115)
compileFiles (harness.ts:1197)
(anonymous) (compilerRunner.ts:116)
```

I've just started looking at the TypeScript internals so I'm not yet sure how/why that whole path is taken, but I thought I should post the trace as a start (to help anyone else more experienced).

**Comment by begincalendar** [comment]
It appears as if type checking does not involve location `Node`s and hence I think it would be a lot of work to get an appropriate location into the error message.

That then only leaves the possibility of silencing the error.

If you take a look at __/src/compiler/checker.ts:6085__:

```
function getApparentType(type: Type): Type {                                     
    const t = type.flags & TypeFlags.TypeVariable ? getBaseConstraintOfType(type) || emptyObjectType : type;
    return t.flags & TypeFlags.Intersection ? getApparentTypeOfIntersectionType(<IntersectionType>t) :
        t.flags & TypeFlags.StringLike ? globalStringType :                      
        t.flags & TypeFlags.NumberLike ? globalNumberType :                      
        t.flags & TypeFlags.BooleanLike ? globalBooleanType :                    
        t.flags & TypeFlags.ESSymbol ? getGlobalESSymbolType(/*reportErrors*/ languageVersion >= ScriptTarget.ES2015) : // <-- Line 6085
        t.flags & TypeFlags.NonPrimitive ? emptyObjectType :                     
        t;                                                                       
}
```
...you can see that the check occurs when the target language is >= ES2015.

The only other usage of the `getGlobalESSymbolType` function is at __/src/compiler/checker.ts:8901__:
```
function tryElaborateErrorsForPrimitivesAndObjects(source: Type, target: Type) { 
    const sourceType = typeToString(source);                                     
    const targetType = typeToString(target);                                     
                                                                                 
    if ((globalStringType === source && stringType === target) ||                
        (globalNumberType === source && numberType === target) ||                
        (globalBooleanType === source && booleanType === target) ||              
        (getGlobalESSymbolType(/*reportErrors*/ false) === source && esSymbolType === target)) { // <-- Line 8901
        reportError(Diagnostics._0_is_a_primitive_but_1_is_a_wrapper_object_Prefer_using_0_when_possible, targetType, sourceType);
    }                                                                            
}
```
...and you can see that the argument for the `reportErrors` param is hard-coded (to be `false`).

So I think if we hard-code a `false` value for the call in the `getApparentType` function, it should fix this issue.

Doing so would result in all usages of the `getGlobalESSymbolType` function to use the same hard-coded value (i.e. `false`) for the `reportErrors` param. So I'm not sure if we also want to remove that param altogether.

**Comment by andy-ms** [comment]
@sandersn Could you take a look at this? This is deep in the bowels of `isRelatedTo`.

**Comment by mhegazy** [comment]
I thought the suggestion here is to just say something like `Cannot find global type 'Symbol'. consider adding '--lib es2015' to your compilation`.. and if so, the change would be limited to `getGlobalESSymbolType` and `getGlobalType` to have an elaboration passed in to add the note about the lib.

**Comment by sandersn** [comment]
@rbuckton pointed out that the lib-references feature that he's working on will allow node and other packages to cleanly avoid this error by referencing `--lib es6` even when tsconfig specifies `--lib es5`. In the meantime, though, we decided it's best to stop issuing this error entirely since it's so hard to debug when libraries (like node) are the ones causing the error.

**Comment by abuob** [comment]
Currently going through issues with the "Good first issue"-label, it seems this one is outdated?
The code given in the initial description compiles fine with `--lib es5 --target es6`, there is no error anymore?
