### ISSUE TITLE
baconjs out of memory

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#18890]
Go to `DefinitelyTyped/types/baconjs` and run `tsc`.

All I see is:
```
#
# Fatal error in , line 0
# API fatal error handler returned after process out of memory
#
```

CC @sandersn who has looked into errors like this.

**Comment by sandersn** [comment]
I'm still in the process of making a smaller repro, but the cause appears to be the `@augments` tag in this construction:

```ts

    class Event<A> {
        value():A;
        hasValue():boolean;
        isInitial():boolean;
        isNext():boolean;
        isError():boolean;
        isEnd():boolean;
    }

    /** @augments Bacon.Event */
    class Next<A> extends Event<A> {
        constructor(value:A);
        constructor(f:() => A);
    }
```

This is odd, because I thought the augments tag was ignored except in JS.

**Comment by andy-ms** [comment]
Could be #18914 ?

**Comment by sandersn** [comment]
Yeah, it's fixed after I pulled in your changes.
