### ISSUE TITLE
TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by Awk34** [Microsoft/TypeScript#18892]
**TypeScript Version:**  2.5.3

Trying to import a `primus.js` file generated by [Primus](https://github.com/primus/primus#client-library) throws the following error from Typescript (inside [awesome-typescript-loader](https://github.com/s-panferov/awesome-typescript-loader)):

```
TypeError: Cannot read property 'type' of undefined
  at parseTypedefTag (C:\example\node_modules\typescript\lib\typescript.js:17815:136)
  at parseTag (C:\example\node_modules\typescript\lib\typescript.js:17558:39)
...
```

Here's the code at that line:

```js
typedefTag.typeExpression = childTypeTag && !isObjectOrObjectArrayTypeReference(childTypeTag.typeExpression.type) ?
    childTypeTag.typeExpression :
    finishNode(jsdocTypeLiteral);
```

**Code**
I've attached my `primus.js`:
[primus.zip](https://github.com/Microsoft/TypeScript/files/1350098/primus.zip)

I believe this is where it's dying: 
```js
/**
 * @typedef ProtocolExtract
 * @type Object
 * @property {String} protocol Protocol matched in the URL, in lowercase.
 * @property {Boolean} slashes `true` if protocol is followed by "//", else `false`.
 * @property {String} rest Rest of the URL that is not part of the protocol.
 */
```

Rolling back to Typescript 2.5.2 doesn't give me this error.

**Comment by sandersn** [comment]
Fixed by #19013.
