### ISSUE TITLE
Please enable CodeLens for TypeScript files

### ISSUE THREAD

**Issue by NoelAbrahams** [microsoft/TypeScript#189]
Hi,

Code lens is a [new feature in Visual Studio 2013](http://msdn.microsoft.com/en-us/library/dn269218.aspx).

After working with this on a C# project, I have found it to be a tremendous productivity booster.

CodeLens provides information about references, unit tests, check-ins etc. I'm not sure how unit tests would be incorporated but simply being able to view the references to a class or method is in itself hugely useful.

Thanks.

**Comment by phmatray** [comment]
+1

**Comment by RobMoloney** [comment]
+1

**Comment by ctrlShiftBryan** [comment]
+1

**Comment by jmwnoble** [comment]
Absolutely +1

**Comment by ctrlShiftBryan** [comment]
+ 1

**Comment by OlegDokuka** [comment]
+1

**Comment by hi-q** [comment]
+1

**Comment by badre429** [comment]
+10

**Comment by techird** [comment]
+10086

**Comment by HardCodr** [comment]
+123123189238190542

**Comment by fedoranimus** [comment]
+1

**Comment by joelmdev** [comment]
+1

**Comment by badre429** [comment]
+1

**Comment by wildert** [comment]
+1

**Comment by Peter-Juhasz** [comment]
Any news about this one?

**Comment by stijnherreman** [comment]
The community could help with this, if there was a public CodeLens API. There's [a 3-year-old request on UserVoice](https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/5743423-provide-an-open-api-to-allow-us-to-extend-code-len) with 700 votes, but unfortunately [it doesn't have a high priority](https://twitter.com/timsneath/status/839974671780986880):

> I really wish I had better news, but this didn't make the cut for VS2017, I'm afraid. I know... :(

**Comment by GopherJ** [comment]
Any news on this? we are 2020 now

**Comment by Kingwl** [comment]
I'm not 100% sure but seems we already have codelens?

@DanielRosenwasser

**Comment by DanielRosenwasser** [comment]
I think @mjbvz can answer this better, but I'm guessing the CodeLens support you see today in VS Code uses a regex and then just requests references on the identifier that matches.

**Comment by Kingwl** [comment]
>**uses a regex** 

Well.... Difficult work....

**Comment by mjbvz** [comment]
Yes VS Code has supported this for quite a long time. I'm guess this issue is track support in VS through 

To implement the code lenses, VS Code uses  `navTree` to get the symbols in a file and then calls `references` for each interesting symbol in the current viewport

**Comment by joj** [comment]
Starting with Visual Studio 17.6 (to be released next month), Visual Studio also supports codelens for JavaScript and TypeScript :)
