### ISSUE TITLE
A bug where a `null` value is assigned when specifying a `null` type.

### ISSUE THREAD

**Issue by stegano** [Microsoft/TypeScript#18905]
**TypeScript Version:**  Version 2.6.0-dev.20170930

**Code**
```ts
let x : number | null;
let y : null | number;
let z : string | number | null;
```

**Expected behavior:**
```ts
let x;
let y;
let z;
```

**Actual behavior:**
```javascript
let x = null;
let y = null | number;
let z = null;
```
A bug where subsequent strings of type `null` are assigned as values.

**Comment by DanielRosenwasser** [comment]
Not seeing this?

```sh
$ cat foo.ts
let x : number | null;
let y : null | number;
let z : string | number | null;
$ tsc -v
Version 2.6.0-dev.20170930
$ tsc foo.ts
$ cat foo.js
var x;
var y;
var z;
```

**Comment by stegano** [comment]
@DanielRosenwasser 
Oops is my mistake, I checked again and found that I was running Typescript the built-in version(1.8.10) provided by IntelliJ.
Thanks!
