### ISSUE TITLE
Visual Studio showing errors for 1.4 new features

### ISSUE THREAD

**Issue by RichiCoder1** [Microsoft/TypeScript#1890]
I have TypeScript 1.4 installed and I'm attempting to use Union Types and type aliases. Both work perfectly when I compile them, but I'm getting red squiggles in VS13 itself.

I'm not the only one:
https://visualstudiogallery.msdn.microsoft.com/2d42d8dc-e085-45eb-a30b-3f7d50d55304

**Comment by RyanCavanaugh** [comment]
Pinging @billti and @paulvanbrenk to investigate

**Comment by paulvanbrenk** [comment]
You have a sample you can share?

**Comment by RichiCoder1** [comment]
in what way? For context, I just created a brand new d.ts and typed in these values:
```javascript
declare type Main = Window;
declare type MyType = string | number;

interface MyInterface {
    myProp: string | number;
}
```
But result in:
![2015-02-02 12_56_25-nextmove - microsoft visual studio](https://cloud.githubusercontent.com/assets/2391878/6006794/fb689aea-aada-11e4-96b4-bc688d9c7018.png)
despite:
![2015-02-02 12_56_45-nextmove - microsoft visual studio](https://cloud.githubusercontent.com/assets/2391878/6006797/026f917c-aadb-11e4-9d19-d39894065b08.png)
And I've confirmed the files are actually compiling.

**Comment by paulvanbrenk** [comment]
I don't repro this.. TypeScript should be showing in Programs and Features / Add Remove programs... 

What kind of project do you have, can you create a TypeScript HTML Application from the TypeScript node in the New Project dialog?

Can you confirm the version number of typescriptlanguageservice.dll in C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\CommonExtensions\Microsoft\TypeScript

**Comment by RichiCoder1** [comment]
TypeScriptLanguageService.dll [FileVersion]: 12.14.0.40115;
![2015-02-02 13_06_53-typescript - programs and features](https://cloud.githubusercontent.com/assets/2391878/6006972/6560d376-aadc-11e4-88f3-0142769b3821.png)

Creating project now. Will post with results.

**Comment by paulvanbrenk** [comment]
And what's the modified date on typescriptservices.js?

**Comment by RichiCoder1** [comment]
Same. 1/14/2015

**Comment by jbondc** [comment]
Do this:
```javascript
C:\Users\jbondc>where tsc
C:\Program Files\Microsoft SDKs\TypeScript\1.1\tsc.exe
C:\Program Files\Microsoft SDKs\TypeScript\1.1\tsc.js
C:\Program Files\Microsoft SDKs\TypeScript\1.0\tsc.exe
C:\Program Files\Microsoft SDKs\TypeScript\1.0\tsc.js
```
You'll need to update your system PATH to remove 'C:\Program Files\Microsoft SDKs\TypeScript\1.0\'

**Comment by RichiCoder1** [comment]
After I removed `'C:\Program Files\Microsoft SDKs\TypeScript\1.0\'` from the path:
```
C:\Users\Me>where tsc
C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.1\tsc.exe
C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.1\tsc.js
C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.4\tsc.exe
C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.4\tsc.js
```
The `1.0` tsc's where at the top previously.

**Comment by paulvanbrenk** [comment]
Any luck with the typescript project?

**Comment by RichiCoder1** [comment]
Created, built and modified a new typescript project with no issue.

**Comment by paulvanbrenk** [comment]
That's at least good news.. Can you create a new MVC 4 project which doesn't work? Or reduce down your current project so we can take a look?

**Comment by RichiCoder1** [comment]
Here's an example project: http://1drv.ms/1AkLpn4
Same symptoms.

**Comment by lokeshpeta** [comment]
do u by any chance use ReSharper?

**Comment by RichiCoder1** [comment]
ReSharper 8.2.

**Comment by lokeshpeta** [comment]
Can u suspend ReSharper and open that same file and check if u get that error?
I think ReSharper sits on top of TypeScript and ReSharper 8.2 doesn't know about TypeScript 1.4

**Comment by RichiCoder1** [comment]
Specifically disabling ReSharper's TypeScript language support did appear to resolve the issue. It looks like @lokeshpeta is correct.

**Comment by gwicksted** [comment]
Updating ReSharper fixed a similar issue for me.

**Comment by stevemansell** [comment]
Me too - thanks!
