### ISSUE TITLE
Nightly builds appear to have stopped building again

### ISSUE THREAD

**Issue by myitcv** [Microsoft/TypeScript#18906]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

`typescript@next`

**Code**

```
$ date
Tue  3 Oct 09:00:18 BST 2017
$ cd `mktemp -d`
$ npm install typescript@next
$ ./node_modules/.bin/tsc --version
Version 2.6.0-dev.20170930
```

More critically:

```
$ npm show typescript | grep 201710
```

**Expected behavior:**

A list of the nightly builds from October 2017.

**Actual behavior:**

No builds listed.

**Comment by weswigham** [comment]
We had a failing test during last night's publish (thus, we did not publish); should be fixed now, and we've released a new nightly. There was no publish on the 1st because it was a weekend with no changes to publish, though. ;)
