### ISSUE TITLE
Typescript should support babel like _interopRequireDefault

### ISSUE THREAD

**Issue by nojvek** [Microsoft/TypeScript#18901]
I understand this will most probably be closed as `won't fix`. I just spent half a day banging my head against typescript while babel would just work flawlessly. My usecase is very common.

## Problem 

```
import pick from 'lodash/pick';
pick({a: 1, b: 2,}, 'a');
```` 

Babel has no problem getting this to work because it adds a helper `_interopRequireDefault`

```
var _pick = __webpack_require__(/*! lodash/pick */ 204);
var _pick2 = _interopRequireDefault(_pick);
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

_pick2.default({a: 1, b: 2,}, 'a');

```

Typescript would emit something like

```
var _pick = __webpack_require__(/*! lodash/pick */ 204);

_pick.default({a: 1, b: 2,}, 'a');
```

Which would throw a runtime error. `TypeError: pick_1.default is not a function`

Lodash code in the module. Code like this very very common. Please please don't say "you should change the npm module to get it to work"

```
var pick = flatRest(function(object, paths) {
  return object == null ? {} : basePick(object, paths);
});

module.exports = pick;
```

### Use `const pick = require('pick')` ?

This is just super ugly when you want to only stick to `import` syntax. Mixing `require` and `import` looks very very hacky just because typescript doesn't play nice.

###  Use `import * as pick from 'lodash/pick`  ?

This doesn't work since pick is a function, TS expects it to be an object so it throws an error

`Module '"node_modules/@types/lodash/pick"' resolves to a non-module entity and cannot be imported using this construct.`

### Use babel transpiler after Typescript's emit

Seriously? Isn't the whole idea of Typescript that it should be able to transpile ESnext code and replace babel without any changes in code.

**Please please please please please please** add a `_interopRequireDefault` in the emit when importing es6 modules.

**Comment by RyanCavanaugh** [comment]
In the meantime may I suggest `import pick = require('pick');` ?

**Comment by nojvek** [comment]
Haha `[ts] Import assignment cannot be used when targeting ECMAScript 2015 modules. Consider using 'import * as ns from "mod"', 'import {a} from "mod"', 'import d from "mod"', or another module format instead.`

**Comment by RyanCavanaugh** [comment]
If you're just looking to desugar into `require` calls, why are you targeting ES6 rather than commonjs?

Not trying to argue, just figuring out the scenario

**Comment by nojvek** [comment]
Because all of our codebase is written in ES6. We're moving some of it to TS so we have a Hybrid of TS and JS files. .js is transpiled using babel and .ts using Typescript. However we can't allowJs:true or checkJs:true due to small issues like this. We'd love to be use typescript as both transpiler and typechecker but right now we're stuck.


@RyanCavanaugh I understand you've marked this as a suggestion. But is the Typescript team willing to take this change as a PR.

**Comment by RyanCavanaugh** [comment]
We have to make sure this is the right thing to do first. Once we've determined that is the case, we'd accept PRs immediately.

**Comment by mhegazy** [comment]
Should be covered by https://github.com/Microsoft/TypeScript/issues/16093

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
