### ISSUE TITLE
Quick info displays type parameter when type is known

### ISSUE THREAD

**Issue by andy-ms** [microsoft/TypeScript#18910]
**TypeScript Version:**  nightly (2.6.0-dev.20170930)

**Code**

```ts
/// <reference path='fourslash.ts' />

////interface I {
////    f(): string;
////}
////
////interface I<T = number> {
////    f(cb: (this: T) => void): this;
////}
////
////declare const x: I;
////x.f(function() {
////    /**/this;
////});

verify.quickInfoAt("", "number");
```

**Expected behavior:**

Test passes.

**Actual behavior:**

It shows `this: T = number` instead.
This bug appears to be caused by a combination of overloading, interface merging, and type parameter defaults. It causes the DefinitelyTyped tests for `angular` to be broken in `typescript@next`.

**Comment by RyanCavanaugh** [comment]
This works now
