### ISSUE TITLE
faulty errors for defaults in an object

### ISSUE THREAD

**Issue by veeramarni** [Microsoft/TypeScript#18932]
Looks like the following code is proper but tyepscript reports following error

**TypeScript Version:**  2.5.2 

**Code**

```ts
const color = ({ one, two, three='i know', four= null }) => {
console.log(one);
console.log(two);
console.log(three);
console.log(four);
}

color({one:1, two:2, three:3, four:4});

color({one:1, two:2});
```

**Expected behavior:**
![image](https://user-images.githubusercontent.com/3382355/31153599-0e1a8ad2-a870-11e7-8510-ed2489b1fe6a.png)

**Actual behavior:**

```
Argument of type '{ one: number; two: number; three: number; four: number; }' is not assignable to parameter of type '{ one: any; two: any; three?: string; four?: null; }'.
  Types of property 'three' are incompatible.
    Type 'number' is not assignable to type 'string'.
```

**Comment by mhegazy** [comment]
In the absence of a type annotation, the default is used to infer the type of the declaration. this is the same for non-destructuring parameters same applies, e.g. `function f(x= 2){} f("string") // Error`. Add an explicit type annotation on your parameter to give a more general type to your parameter.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
