### ISSUE TITLE
AST nodes missing properties if code does not compile

### ISSUE THREAD

**Issue by gscshoyru** [Microsoft/TypeScript#1893]
To get the sourceFile to walk for our linter, we're using ts.createProgram().getSourceFile() to get the AST for a given file -- since using ts.createSourceFile doesn't seem to attach the source file to all the child nodes, which causes code to fail if you call getChildren or getText on the node. However, if the read-in typescript code doesn't compile, for any reason, createProgram will _also_ not attach the source file to most of the nodes, resulting in the same errors. Is there a reason why the source file is not attached to all the nodes when the code does not compile? Can you guys fix this, please?

Thanks!

**Comment by DanielRosenwasser** [comment]
> Using ts.createSourceFile doesn't seem to attach the source file to all the child nodes

Sorry, could you explain what you mean here? Are you trying to get the source text from a given `Node` and then getting a crash?

**Comment by gscshoyru** [comment]
I'm trying to do various things on a given node -- among them get the children of a node (via getChildren or getChildAt) or get the text of a node (via getText) or get the position of a node (via getStart or getEnd) all of which gives a crash if the source file is not attached to the node. It's pretty clear from the error messages and a little bit of digging this is because they do this based on the source file, but the source file is not there.

**Comment by DanielRosenwasser** [comment]
So much of that functionality requires `parent` references to be bound so that we can reach up to the `SourceFile`; however, parent binding occurs in the binder, which is only triggered when using `createProgram`.

However, we know this is a pain point. Binding has some unnecessary overhead, and you shouldn't need to do it if all you want is a syntactic view of the code.. In the upcoming 0.5 version of the API, we've changed the signature of `createSourceFile`:

```TypeScript
function createSourceFile(filename: string, sourceText: string, languageVersion: ScriptTarget, setParentNodes = false): SourceFile
```

You'll be able to call `createSourceFile` with the `setParentNodes` flag set to `true` and get the desired behavior.

**Comment by gscshoyru** [comment]
Sure -- it's good to know that that functionality is coming in the next version of the API, thank you for that -- but this doesn't help with the fact that when we _do_ use createProgram (as we do now), but the file doesn't compile, it still won't attach parent nodes. Is there a way to fix/deal with that, at all?

**Comment by mhegazy** [comment]
We are looking into updating the API so that a call to getParent() would cause all parents to be linked correctly. i think is is a fair request to make. reopening.

**Comment by mhegazy** [comment]
@gscshoyru  you just need to call program.getTypeChecker(), this will force all parent pointers to be set as part of initializing the checker. the creating is not a lot of work, so you are not incurring much of additional costs here.

**Comment by gscshoyru** [comment]
Oh, goody, that seems to do the trick. Thanks!

**Comment by DanielRosenwasser** [comment]
Great, glad to hear it!

For the record, I don't know if we'd be able to lazily populate parent pointers in a clean way, so I'm not sure that's something we'll end up doing. We'll have to discuss it more.
