### ISSUE TITLE
index signature cannot be string or number

### ISSUE THREAD

**Issue by npenin** [Microsoft/TypeScript#18939]
**TypeScript Version:**  2.5.2

**Code**

```ts
var x: { [messageId: string | number]: any } = {};
```

**Expected behavior:**
No compilation error

**Actual behavior:**
`[ts] An index signature parameter type must be 'string' or 'number'.`

**Comment by aluanhaddad** [comment]
This is a duplicate of #13398

**Comment by npenin** [comment]
indeed, but the issue was closed without explanation

**Comment by mhegazy** [comment]
When indexing with a numeric value, the compiler checks the numeric indexer first, and then the string indexer if a numeric one is not defined. So an `string | number` indexer is just `string` indexer.

**Comment by npenin** [comment]
ok
