### ISSUE TITLE
LanguageServiceHost methods should allow for async returns

### ISSUE THREAD

**Issue by czb** [Microsoft/TypeScript#18949]
I think that `readDirectory`, `readFile`, `fileExists` etc. under `LanguageServiceHost ` interface should be async. 

You state that

```
LS host can optionally implement these methods to support completions for module specifiers.
Without these methods, only completions for ambient modules will be provided.
```

but since the functions are expected to be sync, it is not possible to use these where async is required. Now I am thinking of Monaco where it could easily implement async version of these functions by ajax calls against a server but since these functions are expected to be sync Monaco and other tools cannot make the full use of the LanguageServiceHost.

Is there any particular reason for the requirement that the functions must be sync instead of async?

I could easily imagine something like this:

```
export interface LanguageServiceHost {
    ...
   fileExists?(path: string): boolean | Promise<boolean>;
    ...
}
```

**Comment by mhegazy** [comment]
Please see https://github.com/Microsoft/TypeScript/issues/1857

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
