### ISSUE TITLE
Transpile to JS considering paths from tsconifg

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/TypeScript#18951]
For convenience to get rid of relative paths one may use:
```ts
import { sharedStuff } from '~/shared'
```

For this to work in tsconfig I have:
```
"baseUrl": ".",
    "paths": {
      "~/*": ["./*"]
    }
```

Transpired JS still have `require('~/shared')` and `node` will fail to find the module. Loaders like webpack has mechanics for this, but `node` as a standard runtime for JS AFAIN has not standardized/common approach to handle such paths correctly. 

So if TS uses `paths` for looking up of the modules, why for convenience not convert such paths to relative to module paths so `node` (and other loaders) could require it? This probably should be a compiler option.

What do you think? Am I missing something why it can not be implemented? Maybe some unsafe/irrelevant cases of paths mapping?

**Comment by mhegazy** [comment]
Please see https://github.com/Microsoft/TypeScript/issues/16640

**Comment by whitecolor** [comment]
Ok, I see, but there is was no strong reasoning why this should not be implemented. Yes, loaders can do it. But nodejs can not, would require to use some not standard way. Also, it would really simplify configuration because would be no need to configure loaders for this. And of course, this should be the optional feature, who want to live old way - always will.

I mean, TS could make a goodness for devs. I propose to think about it, maybe there are strong reasons not to do this, but maybe not.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
