### ISSUE TITLE
Nightly DirectoryWatcher watching and triggering .git directory

### ISSUE THREAD

**Issue by pocesar** [Microsoft/TypeScript#18961]
**TypeScript Version:**  2.6.0-dev.20171005

**Expected behavior:**

Watch only ts files

**Actual behavior:**

Running tsc -w with --diagnostics shows that DirectoryWatcher is watching other folders (including folders with huge minified JS files) and not only the ones specified in tsconfig.json. while using this with vscode, the HD usage is constant (windows 10 x64)

``` 
DirectoryWatcher recursive:: Trigger: G:/www/cim-typings/.git/index.lock PathInfo: G:/www
DirectoryWatcher recursive:: Elapsed: 0ms Trigger: G:/www/cim-typings/.git/index.lock PathInfo: G:/www
DirectoryWatcher recursive:: Trigger: G:/www/cim-typings/.git/index.lock PathInfo: G:/www
DirectoryWatcher recursive:: Elapsed: 0ms Trigger: G:/www/cim-typings/.git/index.lock PathInfo: G:/www
FileWatcher:: Trigger: g:/www/x/src/components/imoveis.tsx 1 PathInfo: g:/www/x/src/components/imoveis.tsx
FileWatcher:: Elapsed: 0ms Trigger: g:/www/x/src/components/imoveis.tsx 1 PathInfo: g:/www/x/src/components/imoveis.tsx

06:00:06 - File change detected. Starting incremental compilation.
```

**Comment by sheetalkamat** [comment]
I dont think the watcher invoked here is because of G:/www/cim-typings/.git/index.lock it is because of Trigger: g:/www/x/src/components/imoveis.tsx which seems to have changed.

**Comment by pocesar** [comment]
yes, that's the reason, but why is it watching the git folder unnecessarily?

**Comment by sheetalkamat** [comment]
@pocesar  it isn't watching git directory.. It is watching project root for file additions/subtractions/type root changes so that it can decide when to update the project eg. if there is npm install and some modules get added etc.

**Comment by pocesar** [comment]
but nothing changed the state of git, unless vscode is constantly triggering it?

**Comment by sheetalkamat** [comment]
@pocesar I am not sure who and why there was changes in the directory ```G:/www/cim-typings/.git``` but those changes would trigger the callback for the recursive watch on project root (which we do to handle the npm installs, types additions etc). But that callback ignores these files and doesn't act on these changes.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
