### ISSUE TITLE
Scanner does not reach end of file token under some circumstances

### ISSUE THREAD

**Issue by gscshoyru** [Microsoft/TypeScript#1896]
I haven't looked into this in full detail yet -- I have only the one example -- but if I have code of the form:
```typescript
var scanner = ts.createScanner(ts.ScriptTarget.ES5, false, sourceFile.text);
while (scanner.scan() !== ts.SyntaxKind.EndOfFileToken) {
    // do stuff here
}
```
but sourceFile.text is something that doesn't compile like just `var a=;` then the loop never exits, as the end of file token is never hit -- it just hits the semicolon token over and over again. Is this on purpose? Is there a more standard way to loop until you hit the last token? (I would assume checking if the previous start is the same as the current start, which is easy enough to do, but I'm not sure how intentional this is, regardless).

**Comment by DanielRosenwasser** [comment]
Woah, that doesn't seem like it could be right - I tried this out

```TypeScript
/// <reference path="bin/typescript.d.ts" />

import ts = require("typescript");
var sourceText = "var a=;";

var scanner = ts.createScanner(ts.ScriptTarget.ES5, false, sourceText);

while (true) {
	var token = scanner.scan();
	console.log("" + token + ": " + ts.SyntaxKind[token]);
	
	if (token === ts.SyntaxKind.EndOfFileToken) {
		break;
	}
}
```

```
> node .\bin\tsc.js .\scanSample.ts --module commonjs
scanSample.ts(10,48): error TS4085: Index expression arguments in 'const' enums must be of type 'string'.
```
(ignore the error)
```
node .\scanSample.js
96: VarKeyword
5: LastTriviaToken
63: Identifier
51: FirstAssignment
21: FirstOperator
1: EndOfFileToken
```

**Comment by gscshoyru** [comment]
...that is decidedly odd. That simple bit seems to work fine for me as well -- but my code is very clearly breaking here, and I'm not sure why. Let me investigate a bit.

**Comment by gscshoyru** [comment]
...nevermind. I figured out where I went wrong; it was something else. Sorry, and thanks!
