### ISSUE TITLE
Property newLine in tsconfig.json is ignored

### ISSUE THREAD

**Issue by molant** [Microsoft/TypeScript#18966]
**TypeScript Version:**  2.5.3
**Code**

This is my current `tsconfig.json` file:

```json
{
    "compilerOptions": {
        "alwaysStrict": true,
        "module": "commonjs",
        "sourceMap": true,
        "target": "esnext",
        "declaration": true,
        "lib": [
            "es2017",
            "esnext",
            "esnext.asynciterable",
            "dom",
            "dom.iterable"
        ]
    },
    "newLine": "LF",
    "exclude": [
        "node_modules"
    ],
    "include": [
        "scripts/**/*.ts",
        "src/**/*.ts",
        "tests/**/*.ts"
    ]
}
```

That I use to compile the project using `tsc --outDir dist`.

**Expected behavior:**

End of lines to be `LF` and not `CRLF` regardless of the OS.

**Actual behavior:**

End of lines still depend on the OS where the command is run.

I've tried updating my `tsconfig.json` to ` "newLine": "lf",` and the problem still reproduces.

If I compile using `tsc --outDir dist --newLine lf` I get the expected results.

Related issue in the wild: https://github.com/sonarwhal/sonar/pull/566

**Comment by mhegazy** [comment]
Should be under `"compilerOptions"` and not on the same level.

**Comment by molant** [comment]
Thanks!
