### ISSUE TITLE
Control flow with type guards forget previously computed props

### ISSUE THREAD

**Issue by timocov** [Microsoft/TypeScript#18962]
**TypeScript Version:**  2.5.3 / nightly (2.6.0-dev.20171005)

**Code**

```ts
interface Base {
	value?: string;
}

interface A extends Base {
	type: 'A';
	a: number;
}

interface B extends Base {
	type: 'B';
	b: string;
}

type Common = A | B;

declare var a: Common;

if (a.value !== undefined && a.type === 'A') {
	const str: string = a.value; // Error
}

if (a.type === 'A' && a.value !== undefined) {
	const str: string = a.value; // Ok
}
```

**Expected behavior:**
No errors.

**Actual behavior:**
```
error TS2322: Type 'string | undefined' is not assignable to type 'string'.
  Type 'undefined' is not assignable to type 'string'.
```

**Comment by mhegazy** [comment]
The first check narrows type of `a.value` to `string`, but the second check then narrows the type of `a` to `A`. Need to think of possible solutions here. It is possible to address this by fixing issues like https://github.com/Microsoft/TypeScript/issues/18840.
