### ISSUE TITLE
compiler hide errors in tsx files, if there is "import"

### ISSUE THREAD

**Issue by jack128** [Microsoft/TypeScript#18973]
**TypeScript Version:**  2.5.3

**Code**

1.tsx
```ts
import Test from "./2"

declare namespace JSX {
  interface IntrinsicElements {
    foo: { requiredProp: string; optionalProp?: number }
  }
}
class React {  static Render(a?: any, b?: any, c?: any) {} }

function xxxxx() {
  <foo />;
}
```
2.ts
```ts
export default class Test {}
```
command line
``` tsc 1.tsx --jsx react```

**Expected behavior:**
```error TS2322: Type '{}' is not assignable to type '{ requiredProp: string; optionalProp?: number; }'.
  Property 'requiredProp' is missing in type '{}'
```

**Actual behavior:**
compilation is success

**Note:**  
if I comment line 'import Test from "./2"', I get error as expected.

**Comment by mhegazy** [comment]
once a file has a top-level `import` or `export` it becomes a module. modules have their own scope. declarations within this module do not merge with declarations in the global scope.

Use `declare global` instead:

```ts
declare global {
  namespace JSX {
    interface IntrinsicElements {
      foo: { requiredProp: string; optionalProp?: number }
    }
  }
}
```

**Comment by jack128** [comment]
Oh, I see. Thanks.
