### ISSUE TITLE
Consistent Enum Default Export Syntax

### ISSUE THREAD

**Issue by drguildo** [Microsoft/TypeScript#18989]
It would be nice to have support for more consistent default export syntax when it comes to enums. I'm new to TypeScript so apologies if I'm missing something obvious but I can't see why

```ts
enum Foo {
  Bar, Baz
}
export default Foo;
```

should be fine when

```ts
default export Foo {
  Bar, Baz
}
```

isn't, when the latter syntax is allowed for things like classes and interfaces.

Like I say, I'm the opposite of a TypeScript expert but I can't see how adding support for the latter syntax would cause any problems and it would add a little bit more consistency and predictability which, all things being equal, are things that I, and I'm sure a lot of other people, value.

**Comment by RyanCavanaugh** [comment]
Duplicate of #3320

**Comment by drguildo** [comment]
In https://github.com/Microsoft/TypeScript/issues/3320#issuecomment-107241679 @danielrosenwasser states

> If you find yourself sorely missing this, you can suggest that we allow enums to be declared as default exports **as part of a separate issue**

which is what I'm doing.

**Comment by mhegazy** [comment]
I thought we are using https://github.com/Microsoft/TypeScript/issues/3792 to track all of these missing patterns, see https://github.com/Microsoft/TypeScript/issues/3792#issuecomment-303526468

**Comment by drguildo** [comment]
I wasn't aware of that bug. Sorry about the noise.
