### ISSUE TITLE
Await is allowed in object shorthand initializers in parameters

### ISSUE THREAD

**Issue by weswigham** [Microsoft/TypeScript#18981]
**TypeScript Version:**  2.5.1-insiders.20170825 (current playground version)

**Code**

```ts
async function foo({ foo = await import("bar") }) {
}
```

**Expected behavior:**
Error on `await import("bar")` as `foo = await import("bar")` is an error, so `{foo = await import("bar")}` should also be one.

**Actual behavior:**
No error, broken emit:
```ts
    function foo(_a) {
        var _b = _a.foo, foo = _b === void 0 ? yield new Promise(function (resolve_1, reject_1) { require(["bar"], resolve_1, reject_1); }) : _b;
        return __awaiter(this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                return [2 /*return*/];
            });
        });
    }
```

**Comment by Kovensky** [comment]
[Indeed](https://tc39.github.io/ecma262/#sec-async-function-definitions-static-semantics-early-errors): `It is a Syntax Error if FormalParameters Contains AwaitExpression is true.`
