### ISSUE TITLE
Conformance tests for updated language spec

### ISSUE THREAD

**Issue by danquirk** [Microsoft/TypeScript#1898]
Tracking the test work associated with the spec changes here https://github.com/Microsoft/TypeScript/pull/1878

* [x] Updates to parameter declarations (3.8.2.2).
* [x]  Spread elements in array literals (4.6).
* [x]  Updates to contextually typed function expressions (4.9.3).
* [x]  Destructuring assignments (4.17.1).
* [x]  Updates to contextually typed expressions (4.19).
* [x]  Updates to type guards (4.20).
* [x]  Destructuring variable declarations (5.1.2).
* [x]  Destructuring parameter declarations (6.4).
* [x]  Expanded constant enum expressions (9.2).
* [x]  const enum declarations (9.4).
* [x]  Updates to ambient enum declarations (12.1.4).
* [x]  Correction to ambient external module grammar (12.2).

**Comment by danquirk** [comment]
This should be taken care of before we ship these features.

**Comment by yuit** [comment]
PR# 2735, #2753, #2761, #2773, #2782, #2785, #2792

**Comment by DanielRosenwasser** [comment]
Updated the issue to have a task list. @yuit, feel free to check off whichever ones accepted (not pending) PRs have covered.

**Comment by yuit** [comment]
sweet. Thanks @DanielRosenwasser

**Comment by yuit** [comment]
There already exists conformance test for 12.2
