### ISSUE TITLE
"emitDecoratorMetadata" emits "Object" for "design:type" when type is inferred

### ISSUE THREAD

**Issue by Teq** [Microsoft/TypeScript#18995]
**TypeScript Version:**  2.5.3

**Code**

```ts
import 'reflect-metadata'; // v0.1.10

class Foo {
    @LogType public str1: string;
    @LogType public str2 = 'hello';
    @LogType public num1: number;
    @LogType public num2 = 10;
    @LogType public bool1: boolean;
    @LogType public bool2 = true;
}

function LogType(target: any, propertyKey: string) {
    const type = Reflect.getMetadata("design:type", target, propertyKey);
    console.log(type.name);
}

```

**tsconfig.json**
```
{
    "compilerOptions": {
        ...
        "target": "es6",
        "module": "commonjs",
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        ...
    }
}

```

**Expected behavior:**

```
String
String
Number
Number
Boolean
Boolean
```

**Actual behavior:**

```
String
Object
Number
Object
Boolean
Object
```

**Comment by weswigham** [comment]
I'm just going to point out that fixing this is, by definition, type directed emit.

**Comment by weswigham** [comment]
@rbuckton was of the opinion that we could add extra check specifically looking to serialize the type from the literal kind of an initializer; but that we won't actually go and lookup type information for the initializer, as that's foo far down the type-directed path (and leads to needing to include the type system in file dependency analysis).

**Comment by mhegazy** [comment]
looking at this again. this is behaving as intended. we only serialize explicit types. implicit types are not serialized. this is the only way to make scenarios like single-file transpile works.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
