### ISSUE TITLE
[Bug] Field 'browser' doesn't contain a valid alias configuration

### ISSUE THREAD

**Issue by luchillo17** [Microsoft/TypeScript#18993]
## I'm submitting a...
<pre><code>
[x] Bug report  
</code></pre>

## Current behavior
I get an error whenever i use certain specific interface as an Input type, here's the code:
```ts
// src/typings/types.d.
export interface Route {
  id: string; 
  toId: string; 
  fromId: string; 
  clientId: string; 
  organizationId: string; 
  name: string; 
  value: string; 
  isActive: boolean; 
  shippings: Shipping[]; 
  trackings: Tracking[]; 
  routeLines: RouteLine[]; 
  from: City; 
  to: City; 
  client: Client; 
  organization: Organization; 
  createdBy: User; 
  updatedBy: User; 
  version?: number; 
  createdAt: string; 
  updatedAt: string; 
}

// src/app/route-list/route-detail/route-line-list/route-line-list.component.ts
import { ControlPlace, Route, RouteLine } from '../../../../typings/types';

@Component({
  selector: 'app-route-line-list',
  templateUrl: './route-line-list.component.html',
  styleUrls: [ './route-line-list.component.scss' ]
})
export class RouteLineListComponent implements OnInit, OnDestroy {
  @Input() route: Route;
  @Input() controlPlaces: ControlPlace[];
```
**Error:** The error goes away when i change the `Route` interface in the `Input` to any, is funny that only happens with that specific interface, i can even use that interface in other parts of same component, seems like the error happens with `Inputs` here's the error:
![image](https://user-images.githubusercontent.com/9698639/31213518-aa320ee8-a96c-11e7-8c7b-b3e7c2c7174e.png)

## Expected behavior
To build normally.

## Minimal reproduction of the problem with instructions
Not sure how since that `types.d.ts` file was generated through `graphql-code-generator`.

## Environment

<pre><code>
Angular version: 4.4.4

Browser:
- [x] Chrome (desktop) version 61
 
For Tooling issues:
- Node version: 8.6.0, 7.x.x, 6.x.x  
- Platform: Ubuntu 17.04

</code></pre>
**TypeScript Version:**  2.5.3

**Original issue:** https://github.com/angular/angular/issues/19569#issuecomment-334770558

**Comment by andy-ms** [comment]
This doesn't look like the error message is coming from TypeScript. It looks like it's happening at runtime rather than compile time.
My guess as to why it only happens when `Route` is used instead of `any` is that you have some sort of runtime type information enabled, and without `: Route` the import will be elided as none of the imported identifiers are used as values.

**Comment by luchillo17** [comment]
Let's say i understand all you've said (most of it), yes the error is at runtime, but why it works when i change the extension from `.d.ts` to just `.ts`?

Beside they are all just interfaces, i get we can ask for `instanceof` when they are classes, but with interfaces what can i infer at runtime?

**Comment by andy-ms** [comment]
If you have a `.d.ts` file there is no output `.js` file, but for `.ts` there is. So if you import from a `.d.ts` file but there is somehow a runtime import, it will error at runtime because we didn't compile it to anything.

**Comment by luchillo17** [comment]
So importing all other interfaces but `Route` one is ok, but for some reason when importing `Route` it doesn't detect it as an interface so it doesn't remove the import for it's file, thus the runtime error?

Ok at least it's easy to work around by changing the file extension.

**Comment by andy-ms** [comment]
You'd have to check the output `.js` to be sure. I can't reproduce this on my machine since it's not a complete example.

**Comment by luchillo17** [comment]
Btw it's not a runtime error, i get it when building the source to dist folder.

**Comment by andy-ms** [comment]
The error still seems to be coming from outside of the TypeScript compiler, likely in a custom module loader.

**Comment by luchillo17** [comment]
Though the types are being generated, the project is new one, and the types are just exported interfaces, what feels weird to me is that the other interfaces work ok, it's only the `Route` one in an `@Input()` that breaks, it doesn't if i put it in a variable, and also that it fixes if i change the file's extension to just `.ts`.

For now since i work around by renaming it can be closed i guess.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
