### ISSUE TITLE
All but type T check and assignment of T is not working

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#18991]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

**Code**

```ts

interface A {
    a: string;
}

interface B {
    b: string;
}

function isA(x: any): x is A {
    return !!x.a;
} 

declare let anull: A | null;
if (anull == null) {
    anull = { a: ' ' } as A;
} 
anull.a; // No error because it's A

declare let ab: A | B;
if (!isA(ab)) {
    ab = { b: ' ' } as B;
}
ab.b // Error b does not exists on type A | B

```

**Expected behavior:**
`ab` to be of type `B`

**Actual behavior:**
`ab` to be of type ` A | B`

http://www.typescriptlang.org/play/#src=%0Ainterface%20A%20%7B%0A%20%20%20%20a%3A%20string%3B%0A%7D%0A%0Ainterface%20B%20%7B%0A%20%20%20%20b%3A%20string%3B%0A%7D%0A%0Afunction%20isA(x%3A%20any)%3A%20x%20is%20A%20%7B%0A%20%20%20%20return%20!!x.a%3B%0A%7D%20%0A%0Adeclare%20let%20anull%3A%20A%20%7C%20null%3B%0Aif%20(anull%20%3D%3D%20null)%20%7B%0A%20%20%20%20anull%20%3D%20%7B%20a%3A%20'%20'%20%7D%20as%20A%3B%0A%7D%20%0Aanull.a%3B%20%2F%2F%20No%20error%0A%0Adeclare%20let%20ab%3A%20A%20%7C%20B%3B%0Aif%20(!isA(ab))%20%7B%0A%20%20%20%20ab%20%3D%20%7B%20b%3A%20'%20'%20%7D%20as%20B%3B%0A%7D%0Aab.b%20%2F%2F%20Error%20b%20does%20not%20exists%20on%20type%20A%20%7C%C2%A0B%0A

**Comment by andy-ms** [comment]
If `ab` is originally of type `A`, then the `if (!isA(ab))` branch will do nothing, and `ab` will still be an `A` at the bottom.
No compile error if you remove the `!` in `!isA(ab)`.

**Comment by tinganho** [comment]
Sorry, the code I gave was wrong, here is the correct one:
```ts

interface A {
    a: string;
}

interface AB {
    a: string;
    b: string;
}

function isAB(x: any): x is AB {
    return typeof x.b === 'string';
} 

declare let ab: A | AB;
if (!isAB(ab)) {
    ab = { a: '', b: ' ' } as AB;
}
ab.b // Error b does not exists on type A | AB


```

**Comment by RyanCavanaugh** [comment]
The type `A | AB` is effectively the same as `A` because we remove subtypes from unions when they have a corresponding supertype in the same union.

**Comment by tinganho** [comment]
Is it intended when we assign a subtype, that we keep the super type?

Here is a simpler reproduce:
```ts

declare let ab: A | AB;
ab = { a: '', b: ' ' } as AB; // A | AB why?
ab.b // Error b does not exists on type A | AB
```

**Comment by andy-ms** [comment]
We only do control-flow based autocasts for unions, not for super/subtypes. The following *does* work:
```ts
declare let x: number | string;
x = 0;
2 * x;
```

**Comment by tinganho** [comment]
Thanks for the explanation
