### ISSUE TITLE
Suggestion: Support ES6 'let' and 'const' keyword

### ISSUE THREAD

**Issue by RyanCavanaugh** [microsoft/TypeScript#19]
https://people.mozilla.org/~jorendorff/es6-draft.html#sec-let-and-const-declarations

The only major implication here how we would treat `export const x = 4;` in the context of an internal module, as this basically introduces the concept of a `readonly` variable. See #12

**Comment by fdecampredon** [comment]
> This is something we are considering. There are problems imposed by the scoping of const and let; let and const are block scoped, meaning that in a loop every iteration has a fresh variable. You can not emulate this using var semantics, without introducing functions to create new scopes.

The case where you actually need a function to create a new scopes are pretty rare, could we not just error on those case ? I find it pretty domageable to not having let/const just for few cases.
see:  https://github.com/olov/defs/blob/master/loop-closures.md

**Comment by RyanCavanaugh** [comment]
> The case where you actually need a function to create a new scopes are pretty rare

I'm somewhat surprised by this statement and would like to see some data either way (in terms of use of `let` "in the wild"). My impression is that using `let` in a loop construct to avoid explicit closures is arguably the single most valuable thing `let` actually does, but I could be wrong. The other cases are nice to have IMO, but loop closures are incredibly convenient.

**Comment by fdecampredon** [comment]
> I'm somewhat surprised by this statement and would like to see some data either way (in terms of use of let "in the wild"). My impression is that using let in a loop construct to avoid explicit closures is arguably the single most valuable thing let actually does, but I could be wrong. The other cases are nice to have IMO, but loop closures are incredibly convenient.

From what I understand the only case where you need to emit a closure is when you capture the declared variable in something like a closure: 
```
var arr= []
for (let i = 0; i < 10; i ++) {
  arr.push(() => i)
}
```
Any other case can be solved with variable renaming and compiler check, sure it's an handy case, but there is a lot of other case that are valuable and not being able to take advantage of this feature just for this case seems unfortunate.
Especially `const` is quite useful, and not only for scopes properties.

**Comment by DanielRosenwasser** [comment]
I think a big part of what @RyanCavanaugh meant is that `let` actually gives you the "intuitive" semantics for these cases, which is why it was ever desirable in the first place.

**Comment by fdecampredon** [comment]
@DanielRosenwasser While I agree, I still would like to see all other features being transpiled to es5/3, maybe should I create a new issue ?
