### ISSUE TITLE
Intellisense should remember last selected item

### ISSUE THREAD

**Issue by NoelAbrahams** [microsoft/TypeScript#190]
Hi,

A small but useful feature provided by C# (possibly other languages as well) in Visual Studio is the ability to remember the last selected item and to highlight it in the list of available items.

![untitled](https://cloud.githubusercontent.com/assets/1106823/3663148/9c3d8fec-11d0-11e4-97bd-e1b718c072e5.png)

This generally leads to a productivity boost, because of the common need to work with a specific member or class multiple times.

**Comment by mhegazy** [comment]
This should behaving now as outlined in the OP in Visual Studio 2015.

**Comment by NoelAbrahams** [comment]
@mhegazy, this no longer works as of TS 2.0 Beta.

I believe it was working prior to that.

**Comment by NoelAbrahams** [comment]
@mhegazy, this is still not fixed. Should the label be "bug" because it is a regression?

**Comment by NoelAbrahams** [comment]
Right, so once again we had a working piece of functionality and then it gets broken and completely ignored.

I mean in my book a regression should always be marked as high priority.

This again is very disappointing.

**Comment by RyanCavanaugh** [comment]
This hasn't been collecting any additional feedback so I'm assuming it's either fixed or no one else notices
