### ISSUE TITLE
Discussion about displaying '*' before a generator function name in intellisense

### ISSUE THREAD

**Issue by Alphapage** [Microsoft/TypeScript#19009]
Hello,

Intellisense in playground doesn't display a star '`*`' before a generator function name.
It would be great to add this feature instead of searching if the result type of the function is `IterableIterator`.
I think it is more explicit and better visually.

Is it a limitation of tsserver or omitted in playground website ?

Thank you in advance for your opinion.

**Comment by mhegazy** [comment]
why is this different from `async` functions? 

both `async` and generators are implementation details. what matters is that the return type is `Promise` or `Iterable`. 

wheather the function is implemented as a generator or not, you can still iterate over its results.

**Comment by Alphapage** [comment]
Ok, but if I see `async` or `*` in quickinfo, then I know how to use the function quickly without searching for the result type.
Without those details, I think libraries will rename their functions like : `myFunctionAsync` or `myFunctionGenerator` to be more explicit.

**Comment by mhegazy** [comment]
but if the function is coming from a .d.ts, you do not know if it is `async` or a `generator`. all you know is that it returns either a `Promise` or an `Iterable`.

the `*` for generators, or `async` for async functions are just implementation detail, and does not imply how they should be used.
