### ISSUE TITLE
Strange incompatibility error on generic function

### ISSUE THREAD

**Issue by Ghabriel** [Microsoft/TypeScript#19010]
**TypeScript Version:**  2.5.2/playground

**Code**

```ts
declare function arrayOperation<T>(value: T[]): T[];

function foo<T>(value: T): T {
    if (value instanceof Array) {
        return arrayOperation(value);
    }
    return value;
}
```

**Expected behavior:**
Since the return type of `arrayOperation` is the same as its parameter type, I expect this to compile fine.

**Actual behavior:**
`Type 'any[]' is not assignable to type 'T'`

Note that `return <T> arrayOperation(value);` does not compile either. `return <T> <any> arrayOperation(value);` compiles but seems pretty hacky and ugly.

**Comment by andy-ms** [comment]
That would not be sound:
```ts
function arrayOperation<T>(value: T[]): T[] {
    return value.map(x => x);
}

function foo<T>(value: T): T {
    if (value instanceof Array) {
        return arrayOperation(value) as any as T;
    }
    return value;
}

class ArraySubclass extends Array {
    constructor(readonly someProp: string) {
        super();
    }
}

const a = foo(new ArraySubclass("blah"));
console.log(a.someProp.toUpperCase());
```

`arrayOperation` as typed doesn't necessarily return its input, it returns an array with the same element type.

If you instead use `declare function arrayOperation<T, A extends T[]>(value: A): A;`, then `foo` can compile without casts.

**Comment by Ghabriel** [comment]
Oh, I totally forgot that arrays can be subclassed... guess I have some refactoring to do.
Thanks for your help.
