### ISSUE TITLE
Is not assignable to parameter of type 'QueryFn'.

### ISSUE THREAD

**Issue by hakhuyen1997** [Microsoft/TypeScript#19016]
**TypeScript Version:**  2.5.3

**Code**
  getMessages(): FirebaseListObservable<ChatMessage[]> {
    // query to create our message feed binding
    return this.db.list('messages', {
      query: {
        limitToLast: 25,
        orderByKey: true
      }
    });
  }

**Expected behavior:**

**Actual behavior:**
ERROR in /Users/Desktop/base-chat/src/app/services/chat.service.ts (44,7): Argument of type '{ query: { limitToLast: number; orderByKey: boolean; }; }' is not assignable to parameter of type 'QueryFn'.
  Object literal may only specify known properties, and 'query' does not exist in type 'QueryFn'.

**Comment by lielvan** [comment]
Getting the same problem...

**Comment by aakanksha08** [comment]
I am also facing the same issue.
Please the suggest the solution asap.

**Comment by kitsonk** [comment]
This is not a support forum.

Questions should be asked at [StackOverflow](http://stackoverflow.com/questions/ask?tags=typescript) or on [Gitter.im](https://gitter.im/Microsoft/TypeScript).
