### ISSUE TITLE
Suggestion: error when immediate function expression which returns a value is assigned to function type with void return type

### ISSUE THREAD

**Issue by NaridaL** [Microsoft/TypeScript#19014]
This would be the analog of the error for additional properties in object literals for function return values.

**TypeScript Version:**  2.5.3 / nightly (2.6.0-dev.20171007)

**Code**

```ts
declare function voidCallback(cb: () => void)

// actual: no error
// expected: error: callback ignores return value 
voidCallback(() => 23)

const f = () => 45

// should still work:
voidCallback(f)

voidCallback(() => {
    // should still be allowed for flow control
    return
})
```

**Comment by mhegazy** [comment]
seems like a duplicate of https://github.com/Microsoft/TypeScript/issues/8240

**Comment by NaridaL** [comment]
Yeah they are similar, but if I'm not mistaken in this case returning a value is definitely useless (like for object literals) while those are describing more general cases of not using return values.

**Comment by RyanCavanaugh** [comment]
Consider if you had written `voidCallback(() => arr.push(10))`, which *does* return a value but is not wrong.

**Comment by NaridaL** [comment]
True, you'd have to write `() => { arr.push(10) }`
