### ISSUE TITLE
No type cast of mapped interface arguments

### ISSUE THREAD

**Issue by johnthecat** [Microsoft/TypeScript#19023]
My current task is writing typings for library, that makes all interface sync methods as async. I found how to cast method result, but I didn't found way to cast argument types.

**TypeScript Version:**  2.5.3
**Code**

```ts
interface Test {
    method(arg: number /* always 1 argument */): string;
}

type Promisify<T> = {
    [P in keyof T]: (/* cast arguments from T[P] somehow */) => Promise<P[T] /* don't know how it works, maybe it's a bug */>;
}

const test: Promisify<Test>;

test.method(256 /* no autocomplete */).then((data) => {
    console.log(
        data.charCodeAt(0); // works right
    );
});
```

**Expected behavior:**
User can get method argument types.

**Actual behavior:**
Typescript should have some special key for getting method arguments, 
something like `(args: argumentsof T[P])`.

**Comment by aluanhaddad** [comment]
This is not currently supported. Obviously it's very useful behavior and #6606 tracks adding it to the language. I'm not sure why it currently works for return types as the syntax doesn't make any sense. It may be a bug as you say.

**Comment by johnthecat** [comment]
@aluanhaddad Linked proposal looks good, but it’s exactly what I want. 
In my example with this proposal it should looks like
’’’ts
type Promisify<T> = {
    [K in keyof T]: (a: typeof P[T][“arguments”][0] /* wtf? */) => Promise<P[T]>
}
’’’

**Comment by mhegazy** [comment]
#6606  tracks getting the return type, i.e. `typeof P[T]()`
https://github.com/Microsoft/TypeScript/issues/12265 tracks the arguments part.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
