### ISSUE TITLE
doNotTrack property not present on Navigator

### ISSUE THREAD

**Issue by Vinnl** [Microsoft/TypeScript#19024]
**TypeScript Version:**  2.5.3

**Code**

```ts
if(navigator.doNotTrack.substr(0, 1) === '1') { }
```

**Expected behavior:**

No problems as long as the `lib` compiler option includes `dom`. I'm not sure if Working Drafts are sufficient to add it to the type definitions, but it's [implemented in most modern browsers](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/doNotTrack) and [according to MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/DNT#Reading_Do_Not_Track_status_from_JavaScript) is the property that should be checked for whether DoNotTrack is enabled.

**Actual behavior:**

`error TS2339: Property 'doNotTrack' does not exist on type 'Navigator'.`

**Comment by mhegazy** [comment]
Docs at https://www.w3.org/2011/tracking-protection/drafts/tracking-dnt.html#widl-Navigator-doNotTrack

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by Vinnl** [comment]
Thanks for the link, PR here: https://github.com/Microsoft/TSJS-lib-generator/pull/307
