### ISSUE TITLE
ES3, ES5 Generators (TS2318: Cannot find global type 'IterableIterator')

### ISSUE THREAD

**Issue by isc30** [Microsoft/TypeScript#19025]
Hi, changelog for typescript 2.3 specifies that generators are now available for ES3, ES5.
Seems like some interface is missing when targeting those.

**tsconfig.json:**
```
"target": "es5",
"downlevelIteration": true
```

**TypeScript Version:**  2.5.3
```ts
function* sequence()
{
    let i = 0;

    while (i < 20)
    {
        yield i++;
    }
}

const iterator = sequence();

let result: IteratorResult<number>;
while (!(result = iterator.next()).done)
{
    console.log(result.value);
}
```

**Expected behavior:**
compiles using fallback to array

**Actual behavior:**
error TS2318: Cannot find global type 'IterableIterator'

**Comment by aluanhaddad** [comment]
Try
```

"target": "es5",
"downlevelIteration": true,
"lib": ["esnext"]

**Comment by isc30** [comment]
Hi, same error occurs 😢

**Comment by mhegazy** [comment]
`"lib"` should be inside `"compilerOptions"` and not a sibling.

**Comment by isc30** [comment]
thanks a lot, it works 🥇
