### ISSUE TITLE
Failed check on function in if clause

### ISSUE THREAD

**Issue by huhuanming** [Microsoft/TypeScript#19026]
**TypeScript Version:**  2.5.3

**Code**

```ts
if (Math.floor(1.2), 2) {
   // do something
}
```

**Expected behavior:**

error TS2695: Left side of comma operator is unused and has no side effects.

**Actual behavior:**

![image](https://user-images.githubusercontent.com/5743863/31331268-43c930da-aca7-11e7-8de5-d1404dab5d8a.png)

Nothing happened.

But can get error like this.

![image](https://user-images.githubusercontent.com/5743863/31331292-56d4379c-aca7-11e7-8c1e-4e4a20cc968a.png)

**Comment by kitsonk** [comment]
There are limits to things like call flow analysis, and this would be one of them.  While it might be potentially a logic error, what is a real world use case where this would occur.  CFA comes at a cost, and if this is not a common logic error, it is unlikely for it to be added to the compiler.

**Comment by huhuanming** [comment]
but I really did take a very long time to find this error in real world.

As you can see, I just made a example.

**Comment by huhuanming** [comment]
And Why `if (1, 2` is error, but `if (Math.floor(1.2), 2)` can pass.

**Comment by kitsonk** [comment]
A simplified example is always good, but again, that is not very realistic or sensible code.  If you provided an example that was more realistic, then it might help identify how TypeScript could help in statically identifying issues.

There are trade-offs with CFA (see #9998).  This would require the ability to describe the return types of functions in truthy and un-truthy values to be evaluated at run time to produce the same error.  While `Math.floor()` is a built in function, the way TypeScript deals with it is like any other return, which is that it returns a `number` and when it does the analysis it cannot determine if that number will be `0` (falsey) or `!= 0` (truthy).

On the other hand, providing more than one statement to an `if ()` expression is likely a static error that TypeScript could detect... I am not really sure any construct like `if (foo, bar) { }` would ever be desirable, even if it is valid syntax.

**Comment by andy-ms** [comment]
This is unrelated to `if`.
```ts
Math.floor(1.2), 2;
1, 2;
```
Note that the error message says "and has no side effects". TypeScript doesn't track what functions has side effects, so this error will only happen for an expression that obviously has no side effects such as `null`.
You may be interested in palantir/tslint#3250.

**Comment by huhuanming** [comment]
Thx，I got it.
😄

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
