### ISSUE TITLE
Formatter: Indent of newline after statement should be based on last statement, not last line

### ISSUE THREAD

**Issue by ghost** [microsoft/TypeScript#19037]
**TypeScript Version:**  nightly (2.6.0-dev.20171007)

This appears to be a problem in VSCode but not in Visual Studio.

**Code**

```ts
Math.max(
    1,
    2,
    3);
```

**Expected behavior:**

Pressing 'enter' should take me back to the indentation of `Math.max`, which is the start of the previous statement.

**Actual behavior:**

Takes me to the indentation of `3`, which is the start of the previous line.

**Comment by mhegazy** [comment]
This seems to be specific to VSCode scenario. I do not see the same behavior in VS.
