### ISSUE TITLE
Creating namespace declarations via the compiler API?

### ISSUE THREAD

**Issue by ffMathy** [Microsoft/TypeScript#19030]
In the latest version (2.5), I can't seem to create namespace declarations. There is no `ts.createNamespaceDeclaration` available.

How come? Am I doing something wrong? I can't find any documentation on the matter.

**Comment by mhegazy** [comment]
https://github.com/Microsoft/TypeScript/blob/8a55baf9a3caf88c7e89e563ec51466644981df4/lib/typescript.d.ts#L3382 ?

**Comment by ffMathy** [comment]
I wrote it wrong... I meant namespace!

**Comment by mhegazy** [comment]
`namespace`s are just `modules` with `NodeFlags.Namespace` set on them. so you can just use `createModuleDeclaration`. 
I suppose we can add a createNamespaceDeclaration for ease of use.

**Comment by ffMathy** [comment]
That would be great, because currently that function requires me to resolve some node name? How can I get around that?

**Comment by mhegazy** [comment]
not sure i understand what you mean by resolve?

**Comment by ffMathy** [comment]
The signature is as follows: `function createModuleDeclaration(decorators: ReadonlyArray<Decorator> | undefined, modifiers: ReadonlyArray<Modifier> | undefined, name: ModuleName, body: ModuleBody | undefined, flags?: NodeFlags): ModuleDeclaration;`

It accepts a `name: ModuleName`. I can't figure out how to instantiate a module name, and `ts.resolveModuleName` seems to require a script service or something, which I don't have.

**Comment by weswigham** [comment]
In that context `ModuleName` is just a `Identifier` or `StringLiteral`, the `StringLiteral` case not being valid for namespaces. You just want to use `createIdentifier`.

**Comment by ffMathy** [comment]
I think the fact that a string literal is not allowed for namespaces emphasizes the need of a dedicated method for it.

**Comment by ffMathy** [comment]
I'm curious - how can I add a body to the module declaration? I have used `ts.createModuleBlock`, but it accepts a `ts.Statement` array, and I don't know how to convert a `ts.Node` to that.

**Comment by weswigham** [comment]
Certain kinds of nodes are themselves statements - interface declarations, for example.

**Comment by ffMathy** [comment]
Aha! Thank you.

**Comment by lnunno** [comment]
I just ran into this as well, is there a way to make this more obvious in the API?
