### ISSUE TITLE
Add Missing Import quick fix inserts import before comment

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#19042]
From: https://github.com/Microsoft/vscode/issues/35503

This is the same issue as https://github.com/Microsoft/TypeScript/issues/15515 but for comments specifically

**TypeScript Version:**  2.5.3.

**Code**

`a.ts`:
```ts
export class A {}
```

`b.ts`
```ts
/**
  * This b file
  */
export class B extends A {}
```

Trigger a quickfix on `A` in `B extends A` to add the missing import

**Expected behavior:**
Resulting code:

```ts
/**
  * This b file
  */
import { A } from "./a";
export class B extends A {}
```

**Actual behavior:**
Import is to the head of the file, before the comment

```ts
import { A } from "./a";

/**
  * This b file
  */

export class B extends A {}
```

**Comment by amcasey** [comment]
@weswigham didn't you recently work on where to insert imports?

**Comment by weswigham** [comment]
This is a heuristic. The comment
```ts
/**
  * This b file
  */
export class B extends A {}
```
could be considered attached to the class, or attached to the top of the file. Both are equally correct without anything signalling intent. We consider it attached to the class, as that seems to be more consistent, _plus_ we can offer an escape hatch by doing so: Pin your file-level comments as
```
/*!
  * This b file
  */
export class B extends A {}
```
(note the bang), and we should place imports underneath the comment.

**Comment by weswigham** [comment]
For reference, this issue is a request for the exact opposite of the behavior desired in #17318.

**Comment by Frikki** [comment]
The "bang" comment would be an acceptable approach, IMHO.

**Comment by amcasey** [comment]
It sounds like this is by design, unless @mjbvz has more concerns?

**Comment by mjbvz** [comment]
Nope. Looks `/*!` provided a workaround @Frikki's original issue too. I think you can close this issue
