### ISSUE TITLE
VisualStudio navigation in the comments

### ISSUE THREAD

**Issue by NN---** [Microsoft/TypeScript#1905]
I would like to see VS navigating by selecting 'Go To Definition' in the comments as well.

**Comment by mhegazy** [comment]
can you provide mode details here, is that for /// references or general comments? and if so are we talking about JSDoc or VSDocComments? and are we talking about type names in JSDOC for instance or just random strings?

**Comment by NN---** [comment]
From the regular comments.
For instance I have commented out some piece of code and I want to navigate to the function.
e.g.: //window.alert("A")
Currently I must uncomment the block and then I have the ability to jump to the declaration.

**Comment by DanielRosenwasser** [comment]
What would you propose we did for go-to-definition on each of the words in the following comment?

```TypeScript
/*
 * Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at ex augue.
 * Aliquam eget porttitor orci. Vivamus tempor lobortis lacus, sit amet convallis turpis efficitur nec.
 * Mauris auctor diam ut nisl malesuada ornare. Nam vel fermentum nibh, nec convallis nibh.
 * Vestibulum mattis et neque in hendrerit. Morbi consectetur sapien ac elit tincidunt, vel porta turpis tincidunt.
 * Proin sit amet porttitor orci. Fusce id risus tristique, consequat lorem at, sagittis nunc.
 * Nullam eu scelerisque felis. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
 * Aliquam erat volutpat. Quisque congue lacus neque, condimentum vulputate augue congue dapibus.
 * Vivamus sodales sit amet dui vel cursus.
 * Sed rhoncus porttitor est et posuere. Vivamus sodales, velit id laoreet elementum, mi nunc gravida nulla, id volutpat ante turpis vel nisi.
 */

**Comment by NoelAbrahams** [comment]
This is a rather strange request. Leaving sections of code commented out is a bad practice in the first place.

**Comment by NN---** [comment]
I didn't say that I leave commented out blocks in the code :)
During development I comment some blocks for testing and then I cannot navigate.

There are products that do it , for instance Visual Assist can navigate to the symbol in the comment for C++ language.

**Comment by mhegazy** [comment]
i am not sure this is something that is doable.. consider this:

/*
  function commentedOut() {
    var window = { ... } ;
    window.name;
  }
*/

I think code belongs in code, and comments belong in comments :)
