### ISSUE TITLE
New Website Logo: Stateless

### ISSUE THREAD

**Issue by claytonjschneider** [Microsoft/TypeScript#19054]
Please fill the following out:

- Name: Stateless
- Homepage url: https://www.bestateless.com/
- Brand Guidelines/Licensing: We have complete ownership of our logo
- Logo: 
![stateless-logo-black-w-green-symbol](https://user-images.githubusercontent.com/32654950/31361322-1e3f6ac8-ad10-11e7-8bbc-b573b040150b.png)

**Comment by EmmaRamirez** [comment]
Duplicate of #14424
