### ISSUE TITLE
Generic Type Inference Not Bounded Properly

### ISSUE THREAD

**Issue by arciisine** [Microsoft/TypeScript#19059]
**TypeScript Version:**  2.5.3

**Code**

```ts
interface Function {
  __id: string;
}

interface Cls<T = any> /* extends Function */ {
  new(...args: any[]): T;
  __id: string;
}

class Entity {
  static from<T>(this: Cls<T>, data: Partial<T>): T {
    return new this();
  }

  duration: number;
}

class Service {
  save<T>(cls: Cls<T>, obj: T): T {
    return obj;
  }
}

let res = new Service().save(Entity, Entity.from({ duration: 5 }));
/// res is type of {"duration": number}, not Entity

console.log(res.constructor.__id); // This is okay
console.log(Entity.__id); // This is also okay
```

**Expected behavior:**
```res``` should be a type of ```Entity```

**Actual behavior:**
```res``` is of type ```{ "duration": number }```

If I remove ```__id: string;```  from the ```Cls``` interface, the type resolution properly resolve to ```Entity```

**UPDATED: 2017-10-10**
Added the global declaration for ```__id``` to be on the function type, as it is in my local code.  The ```__id``` field on ```Cls``` should be redundant, but it is behaving differently.

**Comment by HerringtonDarkholme** [comment]
![screen shot 2017-10-10 at 4 13 28 pm](https://user-images.githubusercontent.com/2883231/31376002-04fe6eb6-ad69-11e7-96e0-09920cc9803a.png)

![screen shot 2017-10-10 at 4 14 18 pm](https://user-images.githubusercontent.com/2883231/31376034-2203b8ae-ad69-11e7-84ca-c426437eeacb.png)

Note in your interface `__id: string` is required in `Entity`. Adding a static property solves the problem.

**Comment by arciisine** [comment]
I'm trying to get a better minimal scenario.  In my local code I extend the Function typing to include __id as I add it to the class via transformer.

Realistically, if Entity isn't a valid Cls, the test should fail. 

Will update the code in a bit.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
