### ISSUE TITLE
lib.d.ts: Add Encoding Standard

### ISSUE THREAD

**Issue by saschanaz** [Microsoft/TypeScript#19062]
**TypeScript Version:** 2.5.x

**Code**

```ts
TextDecoder
```

**Expected behavior:** Type should exist

**Actual behavior:** It doesn't

Spec: https://encoding.spec.whatwg.org/

Matching PR: https://github.com/Microsoft/TSJS-lib-generator/pull/300

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by SaschaNaz** [comment]
Already here 😁 https://github.com/Microsoft/TSJS-lib-generator/pull/300

**Comment by saschanaz** [comment]
This has been fixed.

**Comment by mhegazy** [comment]
still need to port the changes from Microsoft/TSJS-lib-generator
