### ISSUE TITLE
Using Partial with enums stops type checking on computed properties

### ISSUE THREAD

**Issue by mkohlmyr** [Microsoft/TypeScript#19065]
**TypeScript Version:**  2.5.3

**Code**

```ts
enum Test {
  FOO = "foo"
}

interface TestObj {
  foo: string;
  bar: string;
}

function test(t: Partial<TestObj>) {

};

test({
  [Test.FOO]: 1,
  "bar": "baz",
});
```

**Expected behavior:**
I can see two possible expected or reasonable behaviours:
1. Behaviour could match what we get without Partials (`t: TestObj`) - meaning `Property 'foo' is missing in type '{ [x: string]: string; "bar": string; }'`.
2. Behaviour could match what we get without the enum (`["foo"]: 1`) - meaning `Types of property 'foo' are incompatible.`

**Actual behavior:**
Instead it appears we recognise `[Test.FOO]` as a known property of the `TestObj` interface, but we do not require the type of the value to match that specified within the interface.

**Comment by Gregroam** [comment]
This is being fixed in one of the milestones I believe

**Comment by mhegazy** [comment]
Should be fixed in latest..

```ts

c:\>type C:\test.ts
enum Test {
    FOO = "foo"
  }

  interface TestObj {
    foo: string;
    bar: string;
  }

  function test(t: Partial<TestObj>) {

  };

  test({
    [Test.FOO]: 1,
    "bar": "baz",
  });

c:\>tsc --v
Version 2.6.0-dev.20171011

c:\>tsc test.ts
test.ts(14,8): error TS2345: Argument of type '{ [Test.FOO]: number; "bar": string; }' is not assignable to parameter of type 'Partial<TestObj>'.
  Types of property 'foo' are incompatible.
    Type 'number' is not assignable to type 'string'.
```
