### ISSUE TITLE
No "'super' can only be referenced in a derived class." error when "interface ClassWithNoParent extends SomeInterface {}"

### ISSUE THREAD

**Issue by NaridaL** [Microsoft/TypeScript#19068]
**TypeScript Version:**  2.5.3 / nightly (2.6.0-dev.20171010)

**Code**

```ts
interface Foo extends Array<number> {}
class Foo {
    constructor() {
        super()
    }
}
```

**Expected behavior:**
`'super' can only be referenced in a derived class.`

**Actual behavior:**
no error

**Comment by begincalendar** [comment]
`InterfaceType.resolvedBaseTypes` is used for the check here:
https://github.com/Microsoft/TypeScript/blob/728d2a92ce2f3771ce726f4f6094eba094113ef9/src/compiler/checker.ts#L13030

`InterfaceType.resolvedBaseTypes` stores the base types for both the `class` and the `interface`, as can be seen here:
https://github.com/Microsoft/TypeScript/blob/728d2a92ce2f3771ce726f4f6094eba094113ef9/src/compiler/checker.ts#L27901-L27906

As far as I see, that means we need some means of differentiating between `class` base types vs. `interface` base types.

Does that sound right?

**Comment by DanielRosenwasser** [comment]
Yes, @Kingwl seems to have a PR out right now. Thank you both for digging into this!

**Comment by revurirams123** [comment]
Hi , I do have same scenario to call super with out any base class as given below , infact base class constructor should be called through decorator, but typescript is throwing an error "super' can only be referenced in a derived class"  please do let me know if its possible. 
 @Component
export default class HelloWorld {
   constructor() {
     super();
   }
 }
