### ISSUE TITLE
Asserting type errors in TypeScript declaration file tests.

### ISSUE THREAD

**Issue by cameron-martin** [Microsoft/TypeScript#19067]
When writing tests for TypeScript declaration files, I currently have not found a good way to assert that a certain line gives a type error. Flow has a way of achieving this, [explained here](https://medium.com/@gcanti/testing-flow-declaration-files-69915089fa68).

Does a similar feature exist for TypeScript that I just have not found yet or if not then could it be added?

**Comment by RyanCavanaugh** [comment]
https://github.com/Microsoft/dtslint#write-tests

**Comment by cameron-martin** [comment]
Oh thanks, never knew about this.
