### ISSUE TITLE
Extract local doesn't respect indentation settings

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#19061]
```ts
function foo(x) {
  let y = [|x ** (x ** x)|] * 2;
}
```

Set indentation to 2 spaces and extract a constant to the current scope.

Expected:

```ts
function foo(x) {
  const newLocal = x ** (x ** x);

  let y = newLocal * 2;
}

```

Actual:

```ts
function foo(x) {
    const newLocal = x ** (x ** x);

  let y = newLocal * 2;
}
```

**Comment by amcasey** [comment]
It sounds like the formatter is doing the wrong thing.  I'm pretty sure the refactoring doesn't specify anything about the indentation.  Sometimes, it keeps trivia in the wrong place, but that doesn't appear to be the case here.

**Comment by mhegazy** [comment]
@andy-ms can you take a look.

**Comment by andy-ms** [comment]
This is working for me in vscode insiders with `typescript@next` and `"editor.tabSize": 2,` in my user settings. @DanielRosenwasser how are you doing this?

**Comment by mhegazy** [comment]
closing for now. please reopen if you still see this on the latest server.
