### ISSUE TITLE
Bug in control flow analysis?

### ISSUE THREAD

**Issue by wysisoft** [Microsoft/TypeScript#19079]
is this a bug in control flow analysis? shouldn't typescript realize the type in this situation?

![image](https://user-images.githubusercontent.com/15177964/31410886-101d1e3c-adcd-11e7-8640-79d09afe1d73.png)

**Comment by andy-ms** [comment]
We don't infer a more specific type except in the case of unions.
```ts
class Animal {}
class Cat extends Animal { c: number; }
class Dog extends Animal { d: number; }

let x: Animal;
if (1) {
    x = new Cat();
    x; // Animal
}

let y: Cat | Dog;
if (1) {
    y = new Cat();
    y; // Cat
}
```

**Comment by mpawelski** [comment]
@wysisoft 
Actually if you omit the `any` type annotation and use `noImplicitAny` compiler flag, then inside your `if` block after assignment your variable will have type you assigned.

![image](https://user-images.githubusercontent.com/2056282/31523021-5590f34a-afb1-11e7-9fab-dc35f98ff96d.png)

[more info](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#improved-any-inference)

**Comment by wysisoft** [comment]
this seems like the answer to me
