### ISSUE TITLE
default class cannot be used in es5 target in IE8

### ISSUE THREAD

**Issue by k8w** [Microsoft/TypeScript#19096]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)
2.6.0-dev.20170926

**Code**

Test.ts
```ts
export default class Test{
    
}
```

index.ts
```ts
import Test from './Test';
var test = new Test;
```

tsconfig.json
```json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "strict": true
    }
}
```

**After compile**
index.js
```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Test_1 = require("./Test");
var test = new Test_1.default;  
```

**Problem**
``var test = new Test_1.default;``  This would get ERROR SCRIPT1010 in IE8

**Suggestion**
For ES5 target, it should be:
```ts
var test = new Test_1['default'];
```

**Comment by mhegazy** [comment]
use `--target ES3`

**Comment by k8w** [comment]
@mhegazy es5-shim works well on IE8, so why not add this feature to `--target ES5` ?

**Comment by RyanCavanaugh** [comment]
Because that's not what `--target` means. You can use the `lib` setting to "mix and match" API availability with supported runtime language features.
