### ISSUE TITLE
Handle absent 'crypto' as per nodejs docs

### ISSUE THREAD

**Issue by mihailik** [Microsoft/TypeScript#19100]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

TypeScript compiler relies on node's 'crypto' module unconditionally:

https://github.com/Microsoft/TypeScript/blob/6997e9b7316b081f8731d131139c7d7f1bba9092/src/compiler/sys.ts#L132

Whereas node's <a href="https://nodejs.org/api/crypto.html#crypto_determining_if_crypto_support_is_unavailable">documentation for crypto module</a> explicitly states:

<blockquote>
<h3>Determining if crypto support is unavailable</h3>
It is possible for Node.js to be built without including support for the crypto module. In such cases, calling require('crypto') will result in an error being thrown.

```javascript
let crypto;
try {
  crypto = require('crypto');
} catch (err) {
  console.log('crypto support is disabled!');
}
```
</blockquote>

That means on a reduced node environment the compiler crashes unnecessarily. By unnecessarily I mean the support for crypto is already optional in the compiler:

https://github.com/Microsoft/TypeScript/blob/6997e9b7316b081f8731d131139c7d7f1bba9092/src/compiler/sys.ts#L67

https://github.com/Microsoft/TypeScript/blob/d7269f1386bb1ad4351a6f6d5f749e89cb14c2b7/src/compiler/watch.ts#L635

https://github.com/Microsoft/TypeScript/blob/67a6a9477f90d61955f92fb33e7b11491dbd17a5/src/compiler/program.ts#L165

**Expected behavior:**

TSC to work without 'crypto'

**Actual behavior:**

TSC fails without 'crypto'

**Comment by mihailik** [comment]
Note that one place in the code actually does rely on `createHash` unconditionally. Which should be a bug, considering that it's declared as optional in `sys.ts` line 67 <a href="https://github.com/Microsoft/TypeScript/blob/6997e9b7316b081f8731d131139c7d7f1bba9092/src/compiler/sys.ts#L67">(see above).</a>

https://github.com/Microsoft/TypeScript/blob/a7fa187fb2ac58892593e8936ac728d61a57eacb/src/compiler/program.ts#L135

**Comment by mhegazy** [comment]
> That means on a reduced node environment the compiler crashes unnecessarily. 

Can you elaborate on what scenarios require node without crypto?

**Comment by mihailik** [comment]
@mhegazy two scenarios:
* running non-standard node in a resource- or security-constrained environment (see <a href="https://github.com/nodejs/node/pull/5611">node#5611</a> for their explicit support of this scenario)
* running in emulated environment (browserify, webpack etc.)

Here's a very relevant piece in node's <a href="https://github.com/nodejs/node/pull/5611/files#diff-a43208147d795be6dd3517c53226e37d">lib/internal/util.js L100:</a>
```javascript
const noCrypto = !process.versions.openssl;
exports.assertCrypto = function(exports) {
  if (noCrypto)
    throw new Error('Node.js is not compiled with openssl crypto support');
};
```

**Comment by DanielRosenwasser** [comment]
We're going to need some sort of hashing mechanism at some point, we should just use that as a fallback for `createHash`.

**Comment by rbuckton** [comment]
@danielrosenwasser: https://github.com/Microsoft/TypeScript/blob/vfs/src/harness/core.ts#L609

**Comment by rbuckton** [comment]
@danielrosenwasser: https://github.com/Microsoft/TypeScript/blob/vfs/src/harness/core.ts#L609
