### ISSUE TITLE
Import ... from code action/quick fix includes relative resolved symlinks/linked directories.

### ISSUE THREAD

**Issue by NaridaL** [Microsoft/TypeScript#19108]
**TypeScript Version:**  2.6.0-dev.20171010

**Code**
I'm not sure if this is by design or not, I can't think of a situation where it would be wanted currently...

```ts
// A/index.d.ts
export * from './out/index'
// A/out/index.d.ts 
export * from './NLA'
// A/out/NLA.d.ts
export type int = number
export const foo = 23

// B/node_modules/A -> C:/npm/node_modules/A -> A

// B/src/main.ts

import {foo} from 'A'

const n: int
// Import int from '../../B/out/index'
// Import int from '../../B/out/NLA'
// Add int to existing import declaration from 'A'
	
```

**Expected behavior:**
only `add int to existing import declaration`

**Actual behavior:**
^^

![screenshot 17](https://user-images.githubusercontent.com/10828874/31461736-ab546704-aeca-11e7-8865-2aa977e5974f.png)

(I'm not even sure what 'node_modules/...' is supposed to be...)

**Comment by mhegazy** [comment]
symlinks are resolved earlier in the process. at this point we only have the file names resolved to where the compiler read them. not sure what we can do here.

**Comment by NaridaL** [comment]
Does it make sense to limit the scope to tsconfig.json's dir for example? I can't imagine wanting to relatively import something outside B from inside B.

Alternatively, it should still be possible to figure out that 'A' also resolves to the relative paths and therefore ignore those?

**Comment by mhegazy** [comment]
i think we should not include anything from `*\node_modules\*` with relative paths.. regardless of how we reached them..

**Comment by NaridaL** [comment]
The node_modules path was incidental to the original issue... not entirely sure what caused that.

Would limiting relative paths to those inside baseUrl be an option?

**Comment by amcasey** [comment]
@mhegazy Do I understand correctly that the symlink behavior is by-design/won't-fix and this issue is now tracking the fact that we want to exclude relative paths containing `\node_modules\`?

**Comment by mhegazy** [comment]
that is correct.

**Comment by amcasey** [comment]
In the repro steps, `->` means "is a (directory) symlink to"?  I'm seeing "Add int to existing import..." and "Import int from ..\..\A".  Nothing about "node_modules".

**Comment by amcasey** [comment]
I'm wondering if this was affected/improved by 441daa4e190986b5d4ff7e5ea0caab40fe32eb40.

**Comment by amcasey** [comment]
@andy-ms Did you already fix this?

**Comment by andy-ms** [comment]
Possibly fixed by #20395.

**Comment by amcasey** [comment]
@NaridaL Are you still seeing the issue with the latest TS SDK?

**Comment by NaridaL** [comment]
@amcasey yeah -> was symlinks.

There doesn't seem to be any improvement:
![image](https://user-images.githubusercontent.com/10828874/35016810-8fd9f128-fb1a-11e7-9b4b-01544a73e0c6.png)

**Comment by amcasey** [comment]
@NaridaL Thanks for the update!  Your screenshot appears to have a somewhat richer environment than the repro steps above.  Is there something else I need to do to get into that state?

**Comment by NaridaL** [comment]
Yes, my repro was for my original issue, not @mhegazy's modified one ;-). I'll make a minimal repro for this case though...

**Comment by amcasey** [comment]
@NaridaL Have you had a chance to construct a repro?

**Comment by NaridaL** [comment]
@amcasey Sorry, I had originally tried without success; I gave it another go now.

 https://github.com/NaridaL/ts_import_fix 

You need to run init.cmd in the root dir to link the packages together. The issue occurs on `int` in `C/src/index.ts`.

**Comment by amcasey** [comment]
Thanks, @NaridaL!  I'm having a little trouble, but I don't think it's with your steps - the links `npm link` creates in the global `node_modules` are invalid, causing subsequent commands to fail.  I'm still investigating.

**Comment by amcasey** [comment]
To confirm, I'm seeing `Import 'int` from module "../../A/out"` and the (sensibly) desired fix is `Import 'int` from module "B"`?

**Comment by NaridaL** [comment]
@amcasey Circumventing npm's link and just symlinking them directly should work, if necessary.

I had originally tried to reproduce the error in 2.7.2 without success, because `getModuleSpecifiersForNewImport` used to only return the shortest path, which in my actual set up was the issue above, but wasn't in my very similar repro (?). 

In any case, the latest version suggests all possibilities so that makes it easier to reproduce...

Just in case, this is what it currently looks like here:
![image](https://user-images.githubusercontent.com/10828874/36689055-986dc89e-1b2e-11e8-906e-a9040873b814.png)
The desired outcome would be `import int from 'A'`

**Comment by NaridaL** [comment]
I've pushed a C/src/other.ts which uses another import from A. In that case A is suggested.

![image](https://user-images.githubusercontent.com/10828874/36689540-fb4fca56-1b2f-11e8-8440-bffa67e47f11.png)

As far as I'm concerned, neither of the relative imports makes sense, but maybe I'm missing something.

**Comment by NaridaL** [comment]
Also, if the import `import {foo} from 'A'` (currently in `C/src/other.ts`) is moved to `C/src/index.ts` *only* `Add int to existing import from 'A'` is shown. Does this discrepancy make sense?

**Comment by amcasey** [comment]
@NaridaL, I'm seeing different behavior, but I'll update my components and try again.

**Comment by amcasey** [comment]
Curiously, I'm seeing different code fixes between VS and VS Code (running the same version of TS Server).

VS
![image](https://user-images.githubusercontent.com/10508071/36879873-a38ff76c-1d7a-11e8-96a5-b030bd650279.png)

VS Code
![image](https://user-images.githubusercontent.com/10508071/36879877-a837d118-1d7a-11e8-8e16-8353c695b015.png)

**Comment by NaridaL** [comment]
Another thing: the auto-import when using CTRL+Space only shows the correct one:

![image](https://user-images.githubusercontent.com/10828874/37053258-ec16d79e-217b-11e8-8f32-e612eb8681d7.png)

Seems like the quick fix and the code suggestion should show the same thing.

**Comment by amcasey** [comment]
I don't see how the difference between VS and VS Code could arise from the command itself - they basically just return spans in different formats.  What's more interesting is that VS has configured projects for A, B, and C, whereas VS Code has only C.

**Comment by amcasey** [comment]
Okay, on my box VS and VS Code disagree about whether the drive letter is uppercase and that's why they're handling links differently.  Specifically, this check is case-sensitive:
https://github.com/Microsoft/TypeScript/blob/d2f6f6a0a48ef5a218eed1bc0e44236f2f5cbc30/src/services/codefixes/moduleSpecifiers.ts#L100

**Comment by amcasey** [comment]
@mhegazy tells me that we should be calling `LanguageServiceHost.getCanonicalFileName` before using `SourceFile.fileName` in a comparison.

**Comment by amcasey** [comment]
Filed https://github.com/Microsoft/TypeScript/issues/24308 for the discrepancy between VS and VS Code (arising from comparing different forms of the same path).

**Comment by amcasey** [comment]
So the work that remains for this issue is filtering out entries containing `node_modules`.  @andy-ms, @mhegazy was surprised that your recent change hadn't fixed this.  Would you mind taking a look?
