### ISSUE TITLE
Name collisions in intersection types should be of a union type

### ISSUE THREAD

**Issue by attatrol** [Microsoft/TypeScript#19102]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

**Code**

```ts
const x = Object.assign({}, {type: '42'}, { type: 42 });
let type = x.type;
type.substring(0); // runtime failure
```

**Expected behavior:**
Variable *type* should be ```number | string```.
**Actual behavior:**
It is ```number & string```.

In general we cannot presume that every function that produces intersections will also intersect any properties.

**Comment by mhegazy** [comment]
The use of intersection in `Object.assign` is an approximation. the correct behavior is that of spread, i.e. the type for the property in the last argument overrides those of the previous argument. that is tracked by https://github.com/Microsoft/TypeScript/issues/11100.
We first need higher-order spread operator to be added to the language, which is tracked by https://github.com/Microsoft/TypeScript/issues/10727

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
