### ISSUE TITLE
renameLocation doesn't seem to be working for extract local

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#19116]
**TypeScript Version:**  2.6.0-dev.20171011

**Code**

```ts
// blank line
const x = 0;
```

Highlight `0`. Select "Extract to constant in enclosing scope".

**Expected behavior:**

Get to rename the newly created local.

**Actual behavior:**

Rename location doesn't work. Tested with vscode insiders. It does work for extract function.

**Comment by amcasey** [comment]
I've been using it successfully in VS, but perhaps it's been working by accident.  I'll confirm.

**Comment by amcasey** [comment]
On my box, the cursor appears at the end of the reference to the new local.  That's weird, but still functional.

**Comment by amcasey** [comment]
And there's a `renameLocation` in the response.  I'll double check the math.

**Comment by amcasey** [comment]
I notice two interesting differences between the server logs for VS (works) and VS Code (doesn't work):
1) VS inserts `\r\n`, whereas VS Code inserts `\n`
2) VS returns a character position, whereas VS Code returns a line and offset.

It seems possible that either the `\r`s are removed after the location is computed, invalidating the math, or that the position/line-column conversion is incorrect.

**Comment by amcasey** [comment]
Note that this wouldn't affect Extract Function since it chooses the first occurrence of the new identifier (vs the last for Extract Constant).

**Comment by amcasey** [comment]
The positions are off by too much for line endings to be the issue.  I suspect that when we convert the character position to line-column, we're doing so with respect to the original text (i.e. without regard to the edits).

**Comment by amcasey** [comment]
Nope, the edits aren't passed to `positionToLineOffset` in `getEditsForRefactor`, so there's no way it could be computing positions in the updated text.  Has this ever worked in VS Code, even for Extract Function?

**Comment by DanielRosenwasser** [comment]
> Has this ever worked in VS Code, even for Extract Function

Nope, not for me. 😄

**Comment by DanielRosenwasser** [comment]
CC @mjbvz

**Comment by mjbvz** [comment]
Yes, renameLocation does work for extract function in VS Code:

![oct-12-2017 19-05-14](https://user-images.githubusercontent.com/12821956/31527168-56a50248-af80-11e7-9b9b-f982e62440ce.gif)

However I believe the extracted function will always come after the cursor in that case, which is not true for extract local. Could this difference have revealed an issue?

**Comment by amcasey** [comment]
@mjbvz I can't see the cursor in your GIF.  Did it move to be beginning of the new function call as it was supposed to?  If it landed somewhere else in the identifier, rename would still work, but only by accident.

**Comment by amcasey** [comment]
Also, the math is definitely different between Extract Function and Extract Constant, but I don't believe that's the issue because both work correctly in VS.  My best guess is still that the character offset to line/column conversion needs to account for the unapplied edits.

**Comment by mjbvz** [comment]
I believe VSCode's rename behavior automatically shifts the cursor to the end of the function name once accepted. If I cancel out of this dialog however, I see that we initially put the cursor at the start of the new method name: `|abc(..` in this case

**Comment by mjbvz** [comment]
Yes in that case we don't correctly trigger the rename. The rename location returned is:

```
 "renameLocation": {
        "line": 5,
        "offset": 3
    },
```
