### ISSUE TITLE
Import path quick suggestions - jsconfig aliases not recognised

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#19113]
_From @mudrz on October 10, 2017 7:58_

- VSCode Version: 1.17.0
- OS Version: macOS High Sierra 10.13

Reproduces without extensions: Yes

Doesn't work properly with aliases added in `jsconfig.json` https://code.visualstudio.com/docs/languages/jsconfig

Sample `jsconfig.json`
```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "ClientApp/*": ["./ClientApp/*"]
    }
  }
}
```
Expected behaviour
```js
import Something from 'ClientApp/...'
```
will pull path intellisense for folder `ClientApp`

Existing extension [path-intellisense](https://marketplace.visualstudio.com/items?itemName=christian-kohler.path-intellisense) for example can also be configured with aliases in `settings.json`
```json
"path-intellisense.mappings": {
    "ClientApp": "${workspaceRoot}/MvcProject/ClientApp",
  }
```

_Copied from original issue: Microsoft/vscode#35970_

**Comment by mjbvz** [comment]
Tested on TS 2.5.3 and latest TS 2.6.0 dev

I see `ClientApp/*` as a suggestion in this case:

```
Trace  - 2:35:20 PM] Response received: completions (15). Request took 4 ms. Success: true 
Result: [
    {
        "name": "ClientApp/*",
        "kind": "external module name",
        "kindModifiers": "",
        "sortText": "ClientApp/*",
        "replacementSpan": {
            "start": {
                "line": 1,
                "offset": 34
            },
            "end": {
                "line": 1,
                "offset": 34
            }
        }
    },
    {
        "name": "node",
        "kind": "external module name",
        "kindModifiers": "",
        "sortText": "node",
        "replacementSpan": {
            "start": {
                "line": 1,
                "offset": 34
            },
            "end": {
                "line": 1,
                "offset": 34
            }
        }
    },
    {
        "name": "node",
        "kind": "external module name",
        "kindModifiers": "",
        "sortText": "node",
        "replacementSpan": {
            "start": {
                "line": 1,
                "offset": 34
            },
            "end": {
                "line": 1,
                "offset": 34
            }
        }
    },
    {
        "name": "react",
        "kind": "external module name",
        "kindModifiers": "",
        "sortText": "react",
        "replacementSpan": {
            "start": {
                "line": 1,
                "offset": 34
            },
            "end": {
                "line": 1,
                "offset": 34
            }
        }
    },
    {
        "name": "react",
        "kind": "external module name",
        "kindModifiers": "",
        "sortText": "react",
        "replacementSpan": {
            "start": {
                "line": 1,
                "offset": 34
            },
            "end": {
                "line": 1,
                "offset": 34
            }
        }
    }
]
```

**Comment by mudrz** [comment]
I just checked, and this is what I get
<img width="637" alt="screen shot 2017-10-12 at 18 58 46" src="https://user-images.githubusercontent.com/9587050/31506194-70674d22-af7f-11e7-8b71-82650aef0b81.png">

I also noticed that object props Intellisense also doesn't work

Recreated the same project config here https://github.com/mudrz/jsconfig-tests

(This is TS 2.5.3, I haven't updated to TS 2.6 yet, I'll have some more time to test that in the following days)

**Comment by mudrz** [comment]
I just installed TS 2.6 and it fixes the performance issues I've had, **but not the aliases resolution**

Updated the test project also with 2.6

How do you get this response, can you share what `compilerOptions` are you using

```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "App/*": ["./ClientApp/*"]
    }
  },
  "include": ["**/*.js"]
}
```
<img width="504" alt="screen shot 2017-10-18 at 10 35 39" src="https://user-images.githubusercontent.com/9587050/31706033-33e6eeb4-b3f0-11e7-9880-b4a286fce69f.png">

**Comment by jtsom** [comment]
Not sure if anything is happening here, but this is still a big issue with latest VSCode Insiders (1.19-insiders), and Typescript@next:

![ts270dev](https://user-images.githubusercontent.com/13488/33940886-be5747fa-dfde-11e7-9eef-32e3f2ac52e2.PNG)

Even trying to not use the alias results in the same bad input (ie. trying to import from 'GLOBAL/..' gives the same incorrect list of suggestions)

**Comment by Zephir77167** [comment]
Hey, I provided a minimal reproduction repo on this (duplicate) issue: https://github.com/Microsoft/vscode/issues/39983

**Comment by jtsom** [comment]
The bigger issue is that even without using the path alias', VC Code has a problem if you try to do an import on an absolute path. Just try importing from 'app/ ..' and it'll show all sorts of incorrect things.

**Comment by fongandrew** [comment]
Same issue. In my case, TypeScript correctly understands the alias once the full path is set out and is able to pull exports from the file. But autocompletion on the file name returns the name of the alias itself -- e.g. if I have a path for `@alias/to/file`, typing `@alias/` presents `@alias/*` (note the duplication) as an autocomplete option rathe than `to/file`.
