### ISSUE TITLE
Path completions do not work with nested modules

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#19121]
From https://github.com/Microsoft/vscode/issues/24946

**TypeScript Version:**  2.6.0-dev.20171011

In a new project:

1. 
```bash
npm init -y
npm i xstream
```

2. Open a new js file:

```ts
import x from 'xstream/extra/'
```

3. Try triggering suggestions after the `extra/`

**Expected behavior:**
Show imports for files in the `xstream` module's `extra` directory

**Actual behavior:**
Generic module names are suggested

**Comment by Kovensky** [comment]
It seems that _folders_ are still correctly suggested (asking for completion after writing `import x from 'xstream/` will suggest the `extra/` folder, with the folder icon too), but asking for completion after the `extra/` shows generic names.
