### ISSUE TITLE
How to constraint parameters to be the same type?

### ISSUE THREAD

**Issue by ngolin** [microsoft/TypeScript#19123]
For the parameters `a` and `b` in function `foo(a, b)`, I want to achieve:
1. constraint `a` and `b` to be the same type;
2. `a` and `b` both can be `string` or `number`.

I have tried `foo(a: string | number, b: typeof a)`, but failed.

**Expected behaviour:**
```ts
function foo(a: string | number, b: typeof a /*string | number*/) {
  if (typeof a === 'string') {
    a;//string
    b;//string
  }
}
foo(0, 'b');//error
foo('a', 0);//error
```
**Actual behaviour:**
```ts
function foo(a: string | number, b: typeof a /*string | number*/) {
  if (typeof a === 'string') {
    a;//string
    b;//still string | number!
  }
}
foo(0, 'b');//no error!
foo('a', 0);//no error!
```
Is this supposed to be a bug? I mean, if it is working as intended, it should be done as `foo(a: string | number, b: string | number)`, not as `foo(a: string | number, b: typeof a)`.

What if `function foo<T extends string | number>(a: T, b: T)`, as @helmutschneider suggested? It seems to be more confusing:
```ts
function foo<T extends string | number>(a: T, b: T) {
  if (typeof a === 'string') {
    a;//T & string
    b;//T extends string | number
  }
}
foo(0, 'b');//error, not assignable to type of '0' !(not number)
foo('a', 0);//error, not assignable to type of '"a"' !(not string)
```

I blame the compiler, :))

**Comment by helmutschneider** [comment]
Use a generic parameter with constraints:
```typescript
function foo<T extends string | number>(a: T, b: T) {
  // do something
}
```

**Comment by ngolin** [comment]
@helmutschneider try it for yourself. You will be surprised.

**Comment by zuozijian3720** [comment]
why not:
```typescript
type Temp = number | string
function foo(a: Temp, b: Temp) {
  if (typeof a === 'string') {
  }
}
foo(1, '1')
foo('1', 1)
```

i think in
```typescript
```
when you

**Comment by zuozijian3720** [comment]
why not:
```typescript
type Temp = number | string

function foo(a: Temp, b: Temp) {
  if (typeof a === 'string') {
  }
}
foo(1, '1')
foo('1', 1)
```
i think in 
```typescript
function foo(a: string | number, b: typeof a /*string | number*/) {
  if (typeof a === 'string') {
    a;//string
    b;//string
  }
}
```
when foo(1,'1'),the first argument is a number,so typeof (first argument) is number

**Comment by ngolin** [comment]
What I want to achieve is, when `a` narrows down to `string`, `b` narrows down to `string`, too. So does when `a` is of `number` type, ensuring `a`'s and `b`'s types in sync.

**Comment by zuozijian3720** [comment]
```typescript
function foo<T= number | string>(a: T, b: T) {

}

foo(1, '1')// error Argument of type '"1"' is not assignable to parameter of type 'number'
```

**Comment by zuozijian3720** [comment]
@ngolin 
sorry,I understand the error
I think you're right
it's confusing

**Comment by ngolin** [comment]
@zuozijian3720 👍 I have no idea how the code could work. But it doesn't narrow as intended.
```ts
function foo<T= number | string>(a: T, b: T) {
  if (typeof a === 'string') {
    a;//T & string, but should be string
    b;//T= number | string, but string is expecting
  }
}
```

**Comment by aluanhaddad** [comment]
```ts
function foo<T extends string | number, U Extends T>(a: T, b: U) {} 
```
will give you an error at those call sites as you expect. however, changing the instantiation of a generic type based on the outcome of a type guard within the implementation of a function such that a test on one value modified the type of the other is not supported.

**Comment by ngolin** [comment]
@aluanhaddad as you mentioned, what I'm requesting has not supported. But I believe it would be beneficial to support it. So I thought this should be issued here.

**Comment by aluanhaddad** [comment]
sorry I didn't realize this was a feature request. my remarks assumed you were asking how to do something and that you thought it was a bug.

**Comment by RyanCavanaugh** [comment]
```ts
function foo(a: string, b: string): void;
function foo(a: number, b: number): void;
function foo(a: string | number, b: string | number): void {
  // ....
}
```
Or
```ts
function foo<T extends string>(a: T, b: T): void;
function foo<T extends number>(a: T, b: T): void;
function foo(a: string | number, b: string | number): void {
  // ....
}
```
If you want something more complex than that you'll have to be more specific about what it would be and how it should work (especially keeping breaking changes in mind)

**Comment by ngolin** [comment]
@RyanCavanaugh thanks for your reminding. I have a solid idea of what it would be and how it should work. And I'll take some time to do some research on how `typeof` is currently working so that I can properly composite my proposal. I believe this would not introduce any breaking changes.

**Comment by ngolin** [comment]
@aluanhaddad Oh, never mind. I'm not really good at coding, even not a coder, but TypeScript is my favourite language, so I have my opinions.

**Comment by RyanCavanaugh** [comment]
This is
```ts
function foo<T>(a: T & (string | number), b: T) {
  // do something
}
```
