### ISSUE TITLE
use `instanceof` with a interface got compilation error

### ISSUE THREAD

**Issue by rdkmaster** [Microsoft/TypeScript#19120]
**TypeScript Version:**  2.5.3

**Code**

```ts
export interface ISlicedTableData {
    origin: RawTableData;
}

if (tableData instanceof ISlicedTableData) { // <- compilation error here.

}
```

**Expected behavior:**
no compilation error, and ts checks `tableData` is a implementation of `ISlicedTableData` or not

**Actual behavior:**
```
compilation error:  'ISlicedTableData' only refers to a type, but is being used as a value here.
```

**Comment by Ghabriel** [comment]
Interfaces only exist at compile-time and are removed after compilation, so that code makes no sense at run-time.

**Comment by Ghabriel** [comment]
You can try using [type guards](https://www.typescriptlang.org/docs/handbook/advanced-types.html) for that.

**Comment by DanielRosenwasser** [comment]
https://stackoverflow.com/questions/46703364/why-does-instanceof-in-typescript-give-me-a-the-error-foo-only-refers-to-a/46703380#46703380
