### ISSUE TITLE
Not possible to `find-all-references` for `export default` of anonymous type

### ISSUE THREAD

**Issue by Kovensky** [Microsoft/TypeScript#19122]
**TypeScript Version:**  2.5.3

**Code**

```ts
export default function () {}
```

**Expected behavior:**

It is possible, somehow, to `Find all references` of the exported anonymous function declaration.

**Actual behavior:**

It is not possible to `Find all references` through any means other than temporarily giving the function declaration a name; or to import it from somewhere else and try to `Find all references` of the imported value.

This also affects anonymous classes and anonymous expression results.

---

In this case, the best case behavior would be that asking to `Find all references` of the `default` token in `export default` would find the references to the default export.

**Comment by mhegazy** [comment]
`default` should get you the references.. 

![animation](https://user-images.githubusercontent.com/8000722/31511246-00024016-af3c-11e7-873f-c1f12310a5ce.gif)

**Comment by Kovensky** [comment]
I happened to reproduce it now in my project but not with an anonymous function, but an anonymous expression.

Not possible to find all references:
```ts
export default connect(mapStateToProps, mapDispatchToProps)(Settings)
```

Possible to find all references by searching for references to `default`:
```ts
const x = connect(mapStateToProps, mapDispatchToProps)(Settings)
export { x as default }
```

Note that searching for references to the `x` variable does not report things that import it, even though it is an aliased live-binding export. Only looking for references to `default` return users of the component.

In either case, it's not possible to find them in any way with the `export default connect(...)(...)` expression.

This was tested with 2.5.3 as I have not been able to update to 2.6.0 yet.

**Comment by mhegazy** [comment]
I see. thanks for the repro. here is a simpler repro:

```ts
export default 1;
```
