### ISSUE TITLE
Emit variable declarations for imported members so debugging works as expected.

### ISSUE THREAD

**Issue by NaridaL** [Microsoft/TypeScript#19131]
**TypeScript Version:**  2.6.0-dev.20171010

I searched for `emit import debugging ` and `namespace import emit` but didn't find any appropriate issues.

**Code**

```ts
import { bar } from 'foo'

bar.blag = 23
debugger
```

**Expected behavior:**
```ts
define(["require", "exports", "foo"], function (require, exports, foo_1) {
    "use strict";
    var bar = foo_1.bar; // added line
    Object.defineProperty(exports, "__esModule", { value: true });
    foo_1.bar.blag = 23;
    debugger;
});
```

**Actual behavior:**
```ts
define(["require", "exports", "foo"], function (require, exports, foo_1) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    foo_1.bar.blag = 23;
    debugger;
});
```

The reason for this is that, when pausing on the debugger line and evaluating `bar` in the debugger REPL,  I expect it to work. Currently I get 'bar' not defined.
Note that this is the playground output; I'm currently having the same issue with the commonjs output.

Prepending `foo_1` isn't much of an issue here, but when selecting and evaluating entire expressions, having to modify anything is time consuming.

**Comment by mhegazy** [comment]
That does not match the ES6 module semanitcs. ES6 allows for live binding where multuple accesses to an import will get you the value at the access time. using a variable at the top means that you capture the value of the export. for instance:

```ts
// b.ts
export var x = 0;

export function inc() { x++; }

// a.ts
import { x, inc } from "./b";

console.log(x);
inc();
console.log(x);
inc();
console.log(x);
```

this should result in:

```
0
1
2
```

**Comment by NaridaL** [comment]
Well strictly speaking, the above code still accesses the namespace, the variable declaration would just be a debugging help. (Even if it isn't entirely semantically correct.) But I can understand if you don't want to add it...

I'll guess I'll have to stick to bundlers and hope they don't rename symbols too much.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
