### ISSUE TITLE
Object is possibly 'undefined' in JSDoc syntax

### ISSUE THREAD

**Issue by tenorok** [Microsoft/TypeScript#19140]
**Code**

In the next snippet of ts-code everything okay:

```ts
let info: { a?: number; b?: number; } = {
    a: 1,
    b: 2
};
console.log(info.a + 1);
```

But, when we doing the same in JSDoc syntax TypeScript throws error:
```js
/** @type {{ a?: number; b?: number; }} */
let info = {
    a: 1,
    b: 2
};
console.log(info.a + 1);
```

**Expected behavior:**

There should not be error.

**Actual behavior:**

```
index.js(6,13): error TS2532: Object is possibly 'undefined'.
```

**Comment by andy-ms** [comment]
You probably have different settings for `--strictNullChecks` for these two projects. I tested with `--strictNullChecks` on and there is an error in both versions.

**Comment by tenorok** [comment]
Ooops, indeed. Sorry please and thank you!

**Comment by tenorok** [comment]
@andy-ms but I have a question about this behavior.
In the example from description we can see that property `a` is explicitly defined in object `info`. Is error really expected?

**Comment by andy-ms** [comment]
When there's an explicit type annotation we will assume that the object might have been mutated to any of the values allowed by that annotation. E.g., you might do:

```ts
interface I { a?: number; b?: number; }
const info: I = {
    a: 1,
    b: 2
};
foo(info);
console.log(info.a + 1);

function foo(info: I) {
    info.a = undefined;
}
```

You might be interested in #9998.
