### ISSUE TITLE
Using the Compiler API's CompilerHost example no longer compiles

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Microsoft/TypeScript#19148]
When trying to copy & paste it into a new file, this error comes up on the `return` object:

```
'Type '{ fileExists: (fileName: string) => boolean; getCanonicalFileName: (fileName: string) => string; ...' is not assignable to type 'CompilerHost'.
  Property 'getDirectories' is missing in type '{ fileExists: (fileName: string) => boolean; getCanonicalFileName: (fileName: string) => string; ...'.'
```

Can the example please be updated with a working `getDirectories`?

**Comment by mhegazy** [comment]
The examples seem to be working now. might have been a break in the nightly drop.

**Comment by mhegazy** [comment]
never mind, was looking at the wrong sample.

**Comment by mhegazy** [comment]
should be fixed now.
