### ISSUE TITLE
Visual Studio plugins of TypeScript 2.6 RC doesn't seem deployed

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#19156]
https://www.microsoft.com/en-us/download/details.aspx?id=48593&751be11f-ede8-5a0c-058c-2ee190a24fa6=True

cc @mhegazy 

```
Releases
TypeScript 2.5.3 for Visual Studio 2015 — September 26, 2017 (release notes)[Download]
TypeScript 2.5.2 for Visual Studio 2015 — August 30, 2017 (release notes)[Download]
TypeScript 2.5.0 RC for Visual Studio 2015 — August 16, 2017 (release notes)[Download]
```

**Comment by mhegazy** [comment]
Should be updated now. we have had an issue in the past with the change taking a while to propagate to all servers, so i would give it a try in 12 hours or so.
