### ISSUE TITLE
Emit metadata with union constituents

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#19154]
Right now, when we emit meta data of one property that is defined as:

```ts
class A {
    @Property()
    p1: 's1' | 's2';
}
```
We emit the metadata as:

```ts
__metadata("design:type", String)
```

So, whoever is using this metadata cannot know the literal types of `p1`. A library author has to decorate the literal types `s1` and `s2` in order to access these literal types:

```ts
class A {
    @Property(strings: ['s1', 's2'])
    p1: 's1' | 's2';
}
```

Why don't we just emit it as an array instead?
```ts
__metadata("design:type", ['union', 's1', 's2'])
```

Related to:
#12703

**Comment by mhegazy** [comment]
The metadata provided are not meant to be a reflective runtime type system. you can find more discussion about this in #3060 and  #3628

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
