### ISSUE TITLE
Lib definition for isNaN wrong

### ISSUE THREAD

**Issue by eseliger** [Microsoft/TypeScript#19153]
**Code**

```ts
isNaN(0)
isNaN('120')
isNaN(new Date())
```

**Expected behavior:**
isNaN should also take `string` and `Date` and pretty much everything, probably `any`
See [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/isNaN#Examples) in the examples section

**Actual behavior:**
It only takes `number` https://github.com/Microsoft/TypeScript/blob/master/lib/lib.es5.d.ts#L53

**Comment by trotyl** [comment]
See https://github.com/Microsoft/TypeScript/pull/3947, https://github.com/Microsoft/TypeScript/issues/4002, https://github.com/Microsoft/TypeScript/pull/11414, https://github.com/Microsoft/TypeScript/issues/12302, https://github.com/Microsoft/TypeScript/issues/13227, https://github.com/Microsoft/TypeScript/issues/15173, https://github.com/Microsoft/TypeScript/issues/16427.

**Comment by RyanCavanaugh** [comment]
@eseliger please do read the instructions and search for existing issues before logging new ones

![image](https://user-images.githubusercontent.com/6685088/31624505-d41cf2a6-b257-11e7-98ae-6627e815be7a.png)
