### ISSUE TITLE
global variable for cached TemplateStringsArray is used for multiple call sites

### ISSUE THREAD

**Issue by ajafff** [Microsoft/TypeScript#19164]
**TypeScript Version:**  2.6.0-rc , 2.6.0-dev.20171013

**Code**

```ts
export function tag(parts: TemplateStringsArray, ...values: any[]) {
    return parts[0];
}
function foo() {
    console.log(tag`foo`); // var _a
    console.log(tag`foo2`); // var _b
}

function bar() {
    console.log(tag`bar`); // var _a, expected var _c
    console.log(tag`bar2`); // var _b, expected var _d
}

foo();
bar();
```

**Expected behavior:**
Logs
```
foo
foo2
bar
bar2
```

**Actual behavior:**
Logs
```
foo
foo2
foo
foo2
```

The TemplateStringsArray for ``tag`foo` `` uses the global variable `_a` for caching, because it is the first tagged template in it's scope.
Unfortunately the TemplateStringsArray for ``tag`bar` `` also uses the global variable `_a` for caching, because it is the first tagged template in it's scope.
Which template is cached depends only on the order of execution.

**Comment by DanielRosenwasser** [comment]
Thanks for reporting this! Should be fixed with our next nightly.
