### ISSUE TITLE
`Rename Symbol` on variable sourcing a return destructured object leads to compiler error

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#19173]
_From @greyepoxy on October 13, 2017 22:33_

- VSCode Version: Code 1.17.1 (1e9d36539b0ae51ac09b9d4673ebea4e447e5353, 2017-10-10T14:24:50.851Z)
- OS Version: Windows_NT x64 10.0.14393
- Typescript: 2.5.3
---
**Steps to Reproduce:**
1. I have the following typescript code
```ts
interface Result {
    a: number;
}

export function doThing(): Result {
    const a = 5 + 10;

    return {
        a
    };
}
```
2. Highlight `a` at its declaration in `const a` 
3. Hit F2 and rename the symbol to `b`

**Expected:**
1. A symbol rename to not lead to a compiler error
1. Something like the following:
```ts
export function doThing(): Result {
    const b = 5 + 10;

    return {
        a: b
    };
}
```

**Actual:**
```ts
export function doThing(): Result {
    const b = 5 + 10;

    return {
        b // <-- this has the error below
    };
}
```
severity: 'Error'
message: 'Type '{ b: number; }' is not assignable to type 'Result'.
  Object literal may only specify known properties, and 'b' does not exist in type 'Result'.'

Reproduces without extensions: Yes

_Copied from original issue: Microsoft/vscode#36252_

**Comment by mjbvz** [comment]
Possibly another case of #15787

**Comment by mhegazy** [comment]
Also another case of https://github.com/Microsoft/TypeScript/issues/14039

**Comment by mjbvz** [comment]
The safe rename is now the default (a way to revert to the old, unsafe behavior was added by #29238)
