### ISSUE TITLE
Cannot get intellisense when replacing a class from module

### ISSUE THREAD

**Issue by Alphapage** [Microsoft/TypeScript#19184]
**TypeScript Version:**  2.5.3

**Code**

```ts
// mod.d.ts
declare module 'm' {
  export class C {
    test(s: string): void
  }
  export function func(): void
}

// m.ts
///<reference path='./mod.d.ts'/>
import * as m from 'm'

const mo = m;
class mm extends m.C {
    test(s: string): void
    // test(): void
    test(s:string) { }

    test2() { }
}
mo.C = mm;

new mo.C().test2
```

**Expected behavior:**
test2 should be of type mm.test2
**Actual behavior:**
test2 throws a warning because it thinks it is of type mo.C instead of mm

Thank you in advance for your help.

**Comment by aluanhaddad** [comment]
A few things worth pointing out are it is invalid to modify a modules exports except from within the declaring module. Ideally, the type of the properties representing the export on the shadowing local constant reference would be `readonly`, and that you should not mix `/// <reference path=""/>` directives with `import ""` statements - they are entirely separate concepts and are largely incompatible.

Ideally `mo.C = mm;` would be a compilation error.

**Comment by mhegazy** [comment]
You need to declare an augentation along with assinging `mm` to `mo.C`. i.e.:

```ts
// m.ts
///<reference path='./mod.d.ts'/>
import * as m from 'm'

declare module "m" {
    interface C {
      test2(): void;
    }
}
const mo = m;
class mm extends m.C {
    test(s: string): void
    // test(): void
    test(s:string) { }

    test2() { }
}
mo.C = mm;

new mo.C().test2
```

**Comment by Alphapage** [comment]
Perfect. Thank you very much. That was exactly what I was trying to do, but now I'm fighting with the constructor I tried:
```
declare module "m" {
    interface C {
      constructor(s:string):C
      test2(): void;
    }
}
```
and 
```
declare module "m" {
    interface C {
      new(s:string):C
      test2(): void;
    }
}
```
without success. 
Is it a limitation to module augmentation ?
