### ISSUE TITLE
Narrowing is not invalidated when side effects occur outside of current scope

### ISSUE THREAD

**Issue by bgnx** [Microsoft/TypeScript#19209]
Why is there an error?

**TypeScript Version:**  2.6.0-dev.20171015

**Code**
```ts
enum SomeEnum {
    k1 = 1,
    k2 = 2,
    k3 = 3
}

class SomeClass {
    state: SomeEnum = SomeEnum.k1
    method() {
        if (this.state === SomeEnum.k1) {
            maybeUpdate();
            //error - [ts] Operator '===' cannot be applied to types 'SomeEnum.k1' and 'SomeEnum.k2'.
            if (this.state === SomeEnum.k2) {
                this.state = SomeEnum.k3
            }
        }
    }
}

const obj = new SomeClass();
obj.method();
function maybeUpdate() {
    if (Math.random() < 0.5) {
        obj.state = SomeEnum.k2;
    }
}
```

**Expected behavior:**
No error
**Actual behavior:**
wtf error

**Comment by ahejlsberg** [comment]
See #9998.

**Comment by bgnx** [comment]
Ok, how I can disable this optimistic behavior or disable CFA completely ? (I am really against a dirty hack of making temporary function to escape cfa in if statement)

**Comment by RyanCavanaugh** [comment]
There isn't a way to disable this behavior. You can use a type assertion, e.g. `if (<SomeEnum>this.state === SomeEnum.k2)`

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
