### ISSUE TITLE
Allow narrowing of discriminated unions at type level

### ISSUE THREAD

**Issue by dhruvrajvanshi** [Microsoft/TypeScript#19207]
Typescript currently supports narrowing of discriminated unions at value level.

For example,
```ts
type Action = {
    kind: "CASE_1";
    payload: number;
} | {
    kind: "CASE_2";
    payload: string;
}
...
```
So, if we have a value of type `Action`, we can
determine the type of the `payload` parameter based on the `kind` property.
```ts
const action: Action = ...;
if (action.kind === "CASE_1") {
    action.payload; // type inferred as number
} else if (action.kind === "CASE_2") {
    action.payload; // type inferred as string;
}
```
Now, since the compiler already has this information, it would be nice if we
could do this "narrowing" at the type level.

So, we should be able to have something like.
```ts
// not currently valid
type PayloadOf<Kind extends Action["kind"]> =
   Action["payload"] where { Action["kind"] is Kind }
```
Here, the where clause is adding a constraint to the `Action` type
that it's `kind` property is known to be the generic parameter `Kind`.

Hence,
```ts
type PayloadOfCase1 = PayloadOf<"CASE_1">;
```
will alias `PayloadOfCase1` to `number`.

**Use cases**
One specific use case I can think of is in redux, where "reducers" are
just functions that perform certain actions based on the `kind` of the action
received. They're essentially giant switch statements on `action.kind`.

If implemented, something like this
```ts
function reducer(state: State, action: Action): State {
    switch(action.type) {
    case "CASE_1": return case1Handler(state, action.payload);
    case "CASE_2": return case2Handler(state, action.payload);
    ...
    default: return state;
    }
}
```
Could be converted to this
```ts
const reducer = createReducer({
   "CASE_1": case1Handler,
   "CASE_2": case2Handler,
   ...
});
type Cases {
    [Kind in Action["kind"]]: PayloadOf<Kind>
}
function createReducer(cases: Partial<Cases>): Reducer {
    ...
}
```
without losing type safety.

**Comment by ahejlsberg** [comment]
You can actually do this without any new features:

```ts
type ActionMap = {
    "CASE_1": number;
    "CASE_2": string;
}

type ActionKind = keyof ActionMap;
type ActionPayload<K extends ActionKind> = ActionMap[K];
type ActionObject<K extends ActionKind> = { kind: K, payload: ActionPayload<K> };
type Action = { [P in ActionKind]: ActionObject<P> }[ActionKind];
```

**Comment by dhruvrajvanshi** [comment]
Yes that works! Thanks.
