### ISSUE TITLE
Wrong type interface: PaymentMethodData

### ISSUE THREAD

**Issue by 1000ch** [Microsoft/TypeScript#19200]
```typescript
interface PaymentMethodData {
    data?: any;
    supportedMethods?: string[];
}
```

should be

```typescript
interface PaymentMethodData {
    data?: any;
    supportedMethods?: string;
}
```

according to https://www.w3.org/TR/payment-request/#paymentmethoddata-dictionary.

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by 1000ch** [comment]
My mistake, should not drop old spec immediately.

```typescript
interface PaymentMethodData {
    data?: any;
    supportedMethods?: string | string[];
}
```

Fixed on https://github.com/Microsoft/TSJS-lib-generator/pull/320
