### ISSUE TITLE
Support Automatically bind `this` in Compiler Options

### ISSUE THREAD

**Issue by Attrash-Islam** [Microsoft/TypeScript#19214]
```ts
class Test {
   private myMouny:number;

  render(){
       this.myMouny = 0;
  }
}
```

**Expected behavior:**
`this` keyword in render always will point to Test class instance without the need to write .bind line for each function (Specially for React.js developers), and `this` in OOO always is the class instance, and being not is anti-pattern.

**Actual behavior:**
bind is not always, you need to write something like this for every function:
![ooo](https://user-images.githubusercontent.com/7091543/31618672-3f164d58-b29b-11e7-80c4-9f4e28357063.png)

I heard from someone that you don't want to do this to be back-compatible with JavaScript, so I hope you insert it into a new compilerConfiguration entry (default is false also :laughing: I don't mind)

Thanks for your great contribution. I love you all :heart:

**Comment by RyanCavanaugh** [comment]
See #3927, others. Instead of writing awkward `bind` calls you can just write your methods using arrow function initializers, e.g. `onSubmit = () => { ... }`

**Comment by Attrash-Islam** [comment]
But I heard that arrow function evaluate non-perfomant specially when being used in react render function..

I hope I made my point correct

**Comment by Attrash-Islam** [comment]
Beside that I can't use call super for your suggestion when using inhirtance

**Comment by andy-ms** [comment]
Yeah, writing every method as an arrow function might be a bad idea. You might be interested in the [no-unbound-method](https://palantir.github.io/tslint/rules/no-unbound-method) lint rule. That makes you perform the bind at the *use* rather than at the *definition*.

**Comment by RyanCavanaugh** [comment]
> But I heard that arrow function evaluate non-perfomant specially when being used in react render function..

This would also be the case if you automatically `bind`ed all methods.

In general you should only be having to use arrow functions in a few very specific places. Most JS libraries will give you the correct `this` context if used properly.

Either way, we don't change the behavior of existing JS code, so this isn't an option we'll be adding.

**Comment by Attrash-Islam** [comment]
Thanks @RyanCavanaugh :+1:
