### ISSUE TITLE
type narrowing for == operator.

### ISSUE THREAD

**Issue by vilic** [Microsoft/TypeScript#1922]
as typeof operator will always return a string, == should be safe and valid when narrowing types.

**Comment by RyanCavanaugh** [comment]
`typeof` always returns a string, but `==` performs coercions on the other operand as well.

````ts
var x = { valueOf: function() { return 'string'; } }
typeof 'blah' === x; // false
typeof 'blah' == x; // true
```

**Comment by vilic** [comment]
Though actually you won't use `typeof str == { valueOf: () => 'string' }` for type narrowing, nor will type narrowing support this form (other than string literal when using typeof), I think.
