### ISSUE TITLE
file.d.ts not loaded by tsserver if file.ts exists

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#19225]
From https://github.com/Microsoft/vscode/issues/36318#issuecomment-336954040

**TypeScript Version:**  2.6.0-dev.20171013

**Code**
`tsconfig.json`

```json
{
    "compilerOptions": {
    },
    "include": [
        "./src/**/*"
    ]
}
```

`src/file.ts`

```ts
foo
```

`src/file.d.ts`

```ts
declare var foo: number
```

**Expected behavior:**
`foo` in `file.ts` is picked up from `file.d.ts`. This is what happens if you rename `file.d.ts` to `other.d.ts`

**Actual behavior:**
`foo` is marked as undefined. It seems the `file.d.ts` is put into an inferred project separate from `file.ts`

**Comment by mhegazy** [comment]
`.ts` files have precedence over `.d.ts` files with the same name. the rational here is that `.d.ts` files are possible outputs of the compiler, and `.ts` are inputs. and inputs are closer to the "truth".

**Comment by jmathew** [comment]
Ah, that makes sense. 

The difficulty is that there is no feedback that my file is being ignored. 

To put it another way: I don't know how I would figure out that this is what was happening without raising an issue.

Is there some documentation I'm missing? Right now it seems like I supposed to know "in general" that `d.ts` files can be ignored if they look like compiler output. But I don't know where this has been documented. I would have guessed here: https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html. 

Aside from documentation, I think a message in the tsserver logs would be helpful as that's what I first did to try and figure out what was going on. Something like: `file.d.ts ignored in favor of file.ts. See <link to docs>`?

**Comment by mhegazy** [comment]
that is something that happens a lot, for instance when doing module resolution. keep in mind that by default the compiler emits the .js and .d.ts file next to the .ts file.

In general, it is not recommended to have files with the same name next to each other, unless one is the output of the other.

**Comment by jmathew** [comment]
I think the issue is I was thinking of the .d.ts file as a header file like an '.h' file in C instead of a compiler product. 

Thanks for resolving this.
