### ISSUE TITLE
React Native Animated typescript error

### ISSUE THREAD

**Issue by foobar8675** [Microsoft/TypeScript#19221]
**TypeScript Version:**   typescript@2.6.0-dev.20171015

**Code**
running react native , the following executes fine
```ts
  getCardStyle = () => {
    const rotate = this.position.x.interpolate({ <-- error
      inputRange: [-Layout.window.width * 1.5, 0, Layout.window.width * 1.5],
      outputRange: ['-120deg', '0deg', '120deg']
    })
    return {
      ...this.position.getLayout(),
      transform: [{ rotate }]
    }
  }
```

**Expected behavior:**
shouldn't be an error
**Actual behavior:**
getting an error saying 
```
file: 'file:///Users/matthewchung/Desktop/language/src/scenes/home/components/Deck.tsx'
severity: 'Error'
message: 'Property 'interpolate' does not exist on type 'Animated'.'
at: '65,36'
source: 'ts'
```
This is my first attempt with Typescript - and I am uncertain as to if this is a bug or if I am just doing something wrong.

**Comment by mhegazy** [comment]
You may have better chances of getting help posting this to StackOverflow. this is not really a support forum, it is a forum for tracking compiler bugs and language suggestions. if you believe you are running into a compiler bug, please give us a minimal self-contained reproduction, with a justification why you believe this is a bug.

**Comment by foobar8675** [comment]
thanks @mhegazy , i noticed i get the error when adding `"@types/react-native": "^0.49.2"` to my `package.json`.  would it be more appropriate to file an issue under https://github.com/DefinitelyTyped/DefinitelyTyped/issues ?

**Comment by mhegazy** [comment]
Sure. i am not an expert on react/react native, so i can not say if it is a lib issue or a definition file accuracy issue.

**Comment by foobar8675** [comment]
got it. thank you.
