### ISSUE TITLE
Omnibus fresh object subtype reduction / contextual type issue

### ISSUE THREAD

**Issue by RyanCavanaugh** [Microsoft/TypeScript#19236]
```ts
// Problem 1: Error spans are useless in contextually-typed array/object literal cases
type Kind = 'foo' | 'ball';
// Error is on declared identifier instead of bad element
const ka: Kind[] = [
    'foo', 'ball', 'xxxx', 'foo', 'ball'
];
// Error is on declared identifier instead of bad key
const ko: { [s: string]: Kind } = {
    'x': 'foo',
    'y': 'xxxx',
    'z': 'foo'
};

// Problem 2: Subtype reduction screwage in the presence of contextual type
type OK = { ok?: boolean };
// No error??
const o1: OK = '??' ? { ok: 'wat' } : { };

// Problem 3: Aliased subtype reduction screwage
const obj = '??' ? { ok: 'wat' } : {};
// No error??
const o2: OK = obj;
```

Hypotheses:
 * Computing a union type in the presence of a contextual type is a waste of time
   * If we do this, we can produce good error spans?
 * Unioning `{ x: T }` with a fresh `{ }` should produce `{ x?: T }`
 * Unioning a fresh object literal with `{ }` should do something special
 * Unioning fresh `{ x: number, y: number }` | `{ x: number }` should produce `{ x: number, y?: number}`

**Comment by aleksey-bykov** [comment]
pardon me, can we keep `{ x: T } |  {}` as it is: `{ x: T } | {}` ? or what is the way to encode an empty (no properties) object?

**Comment by ahejlsberg** [comment]
@aleksey-bykov The issue is that `{ x: T } | {}` is too weak. Anything is assignable to it because anything is assignable to `{}`. The idea is to instead infer the type `{ x: T? }` which says that *if* there is an `x` property it must be of type `T`.

**Comment by aleksey-bykov** [comment]
it's sad that there is no place for a true empty object `{}` which doesn't accept any properties

we use it as yet another unit type in addition to null and undefined and []

**Comment by aleksey-bykov** [comment]
so the problem here is the syntax `{}` is overloaded with semantics:
- `{}` should mean an object with no properties as it literally stands
- `{}` should mean a top type assignable from anything
we need a way to distinguish the two #12936
