### ISSUE TITLE
Duplicate 'annotate from JSDoc' suggestion'

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#19238]
![image](https://user-images.githubusercontent.com/972891/31641692-379a6884-b29b-11e7-9de1-a25c18ee5edc.png)

**Comment by sandersn** [comment]
Was this with `"strict": true` ? Where exactly was your cursor?

**Comment by sandersn** [comment]
1. Repros even with `noImplicitAny: false`, so it's not the codefix combined with refactor causing the duplication.
2. Doesn't repro on tide, which I believe uses a different method to get refactorings. (Or maybe just de-dupes them itself?)
3. Repros when the cursor is anywhere in the function.
4. Both entries work.
