### ISSUE TITLE
JSDoc function annotations  do not work on class property arrow method

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#19231]
From https://github.com/Microsoft/vscode/issues/36283

**TypeScript Version:**  2.6.0-dev.20171013

**Code**

For the JS:

```js
class Foo {
    /**
     * @param {string} x
     */
    bar = (x) => { };
}

const z = new Foo()
z.bar()
```

**Expected behavior:**
Type of `bar` is `(x: string): void`

**Actual behavior:**
Type of `bar` is `(x: any): void`

The following does seem to work:

```js
class Foo {

    bar =
        /**
        * @param {string} x
        */
        (x) => { };
}

const z = new Foo()
z.bar()
```

**Comment by Ciantic** [comment]
In case support for  this is done, it would be good if it supported functions that return function also:

```
    /**
     * On click opener
     * 
     * @param {number} index
     * @param {React.SyntheticEvent} e
     */
    onClickOpener = index => e => {
    }
```

**Comment by sandersn** [comment]
@Ciantic can you create a separate issue for that? It’s pretty ad-hoc but if the issue gets a lot of upvotes then we would consider it.

Do other jsdoc tools work with curried functions?

**Comment by Ciantic** [comment]
@sandersn I actually don't know, I just know it's common pattern in React when dealing with array of things. Example use case e.g. in here: https://medium.com/@machnicki/handle-events-in-react-with-arrow-functions-ede88184bbb

```handleKeyPress = (item) => (e) => {...}```
