### ISSUE TITLE
--noStrictGenericChecks isn't in the Microsoft.TypeScript.MSBuild@2.6.0.0-RC release

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Microsoft/TypeScript#19235]
Same issue as #17099, but with `strictFunctionChecks`/`$(TypeScriptStrictFunctionChecks)`. Is there somewhere in the release process that should be changed so the NuGet packages are always updated on RC?

**Comment by mhegazy** [comment]
The MSBuild properties happen in a different repo, and are not generic in nature. One option is to move to using tsconfig.json.

**Comment by JoshuaKGoldberg** [comment]
Unfortunately, my team is stuck with MSBuild 😦 

If there's public or internal documentation for how you perform releases, could you put a footnote about also including any updated properties in the MSBuild files? We're very excited to RC-test but this is a blocker.

**Comment by mhegazy** [comment]
We are sorry about that, will make sure this gets addressed next release.

**Comment by mhegazy** [comment]
should be available in the [nightly nuget package](https://github.com/Microsoft/TypeScript/wiki/Configuring-MSBuild-projects-to-use-NuGet#for-nightly-drops-httpswwwmygetorg) tonight.
