### ISSUE TITLE
Typescript cannot understand  objectA | objectB in same case

### ISSUE THREAD

**Issue by theGABS** [Microsoft/TypeScript#19246]
Some trouble happen in my project, I use lodash. 
I try reproduce minimal example without lodash.
**TypeScript Version:**  In my project 2.3.4 - then i try https://www.typescriptlang.org/play/

```
interface Dictionary<T> {
    [index: string]: T;
}

type ObjectOf<T> = { [index: string]: T }

const size: <T>(collection: Dictionary<T>) => number = (o) => {
    return 5
}

interface ISource {
  type: 'source'
  id: string
  weight: number
}

interface ICitation {
  type: 'citation'
  id: string
  willMoved: boolean
}

type IListCitation = ObjectOf<ICitation>
type IListSources = ObjectOf<ISource>

size({} as IListCitation | IListSources)
```

**Expected behavior: Typescript understand all correct** 

**Actual behavior: Typescript write error**

**Comment by jcalz** [comment]
I'm guessing your complaint is that `T` is not inferred to be the union type `ICitation | ISource` in the call to `size()`.  I assume this is a design limitation caused by the inherent tradeoff between catching errors and inferring wider types for generics.  Maybe there's a definitive issue somewhere that explains this, but I couldn't find it easily.

**Comment by mhegazy** [comment]
`ObjectOf<ICitation> | ObjectOf<ISource>` is not the same as `ObjectOf<ICitation | ISource>`.  Just like `Array<number> | Array<string>` is not the same as `Array<number | string>` . the compiler is warning you that it made two inferences and the types and none of them is a subtype of the other and thus can be reduced.

If you really want to use that type, consider passing it as an explicit type argument to the function.
```ts
size<ICitation|ISource>({} as IListCitation | IListSources)
```

**Comment by theGABS** [comment]
devil, its hard to understand, I understand it after hours... 
So, actually I think I should write to lodash types  that they should change size interface to something like 

`(collection: Dictionary<any>) => number`

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
