### ISSUE TITLE
Suggestion: addition of "Stringified<T>" type for JSON.stringify()

### ISSUE THREAD

**Issue by shirakaba** [Microsoft/TypeScript#19244]
It would be helpful if `JSON.stringify()` could be more specific about its return type than simply `string`. This would make it easier and safer to keep track of types. particularly in this real-world example of implementing Encrypted Media Extensions (EME).

**Code**

```ts
// https://www.w3.org/TR/encrypted-media/ : 9.1.3 License Request Format
export type LicenseRequest = {
    kids: string[];
    type: MediaKeySessionType;
}
export type LicenseObject = { keys: JsonWebKey[]; }

function generateEMELicense(licenseRequest: LicenseRequest, key: string): Stringified<LicenseObject> {
    let keyObj: JsonWebKey = {
        kty: "oct",
        alg: "A128KW",
        kid: licenseRequest.kids[0],
        k: key
    };

    return JSON.stringify({ keys: [keyObj] });
}

// Before this change, we could only type license simply as 'string'.
function updateMediaKeySession(mks: MediaKeySession, license: Stringified<LicenseObject>): Promise<void> {
    let encodedLicense: Uint8Array = new (window as any).TextEncoder().encode(license);
    return mks.update(encodedLicense);
}
```

**Comment by aluanhaddad** [comment]
`JSON.stringify` returns a value that is of type `string | undefined`. What would `Stringified<T>` look like and how would it restrict usage?

**Comment by shirakaba** [comment]
`Stringified<T>` would act for all purposes like a `string` outside of the context of `JSON.parse()`. However, it would narrow the output type of `JSON.parse()`. Sorry that I didn't make that clear in the initial post!

```ts
export type ObjWithFirstName = { firstName: string; };
let objWithFirstName: ObjWithFirstName = { firstName: "John" };
let objStr: Stringified<ObjWithFirstName> = JSON.stringify(objWithFirstName);

// No error, because Stringified<T> acts like a string, so inherits all the string methods.
objStr.split("{");
// No error, because JSON.parse() would narrow type from 'any' to ObjWithFirstName.
let firstName: string = JSON.parse(objStr).firstName;
// Error: property 'secondName' does not exist on type 'ObjWithFirstName'.
let secondName: string = JSON.parse(objStr).secondName;

// For both, no compile-time error. Will each throw SyntaxError at runtime upon JSON.parse().
let corruptStringified1: string = "]extra text[" + objStr;
let corruptStringified2: Stringified<ObjWithFirstName> = "]extra text[" + objStr;
```

**Comment by shirakaba** [comment]
> What would Stringified<T> look like?

I'm not sure how exactly the interface/implementation would look like (it's getting to the edge of my knowledge here), but based on my described behaviour, I hope someone can comment on whether this would be feasible to implement in any way; I'm open to input.

**Comment by Ghabriel** [comment]
I use the following helper type/functions in a project of mine to preserve JSON type-safety. Not sure if it's possible to adapt it to make it compatible with a standard string, but I'll leave it here, maybe it can inspire someone.

interface JSONData<T> {
	brand: T;
	data: string;
}

function toJSON<T>(obj: T): JSONData<T> {
	return {
		brand: <T> <any> null,
		data: JSON.stringify(obj)
	};
}

function fromJSON<T>(json: JSONData<T>): T {
	return JSON.parse(json.data);
}

**Comment by shadeglare** [comment]
You can define more restricted stringify/parse functions to keep tracking of serializable objects

```ts
interface Stringified<T> extends String {}

module JSONEx {
    export function parse<T>(raw: Stringified<T>): T {
        return JSON.parse(<string>raw);
    }

    export function stringify<T>(obj: T): Stringified<T> {
        return JSON.stringify(obj);
    }
}

let serialized = JSONEx.stringify({ x: 1, y: 2 });
let obj = JSONEx.parse(serialized);
```

**Comment by Ghabriel** [comment]
@shadeglare Your definition of `Stringified` doesn't really add much type safety since structural typing matches it to any other `Stringfied`. E.g
```typescript
let serialized = JSONEx.stringify({ x: 1, y: 2 });
let fake: typeof serialized = "hello";
let obj: Point = JSONEx.parse(serialized); // compiles
let obj2: Point = JSONEx.parse(fake); // also compiles
```
This example is a bit trivial but as the codebase gets bigger these kinds of bad assignments get more like to happen and then havoc ensues.

**Comment by Ghabriel** [comment]
A possible improvement that just came to my mind:
```typescript
// JSONData and toJSON unchanged

function fromJSON<T>(json: string): {};
function fromJSON<T>(json: JSONData<T>): T;
function fromJSON<T>(json: string | JSONData<T>): T {
    if (typeof json == "string") {
        return JSON.parse(json);
    }
    return JSON.parse(json.data);
}

interface Point {
    x: number;
    y: number;
}

let serialized = toJSON({ x: 1, y: 2 });
let obj = fromJSON(serialized); // OK: obj is {x: number, y: number}
let fake: typeof serialized = "hello"; // Error
let x = fromJSON("hello"); // OK: x is {}
```

**Comment by RyanCavanaugh** [comment]
`JSON.parse(JSON.stringify(x))` is *hardly* an identity function `T`.

You could accomplish this with a branding yourself if you were willing to take on that risk; I don't think we need anything special in the type system for it

**Comment by mhegazy** [comment]
you can emulate this today with mapped types, for instance,, 

```ts
// use space in the name to avoid the property showing in your completion list
type Stringified<T> = string & {
    [P in keyof T]: { "_ value": T[P] }
};

declare function parse<T>(text: Stringified<T>): T;
declare function stringify<T>(value: T): Stringified<T>;

export type ObjWithFirstName = { firstName: string; };
let objWithFirstName: ObjWithFirstName = { firstName: "John" };
let objStr = stringify(objWithFirstName);  //

// No error, because Stringified<T> acts like a string,  check
objStr.split("{");

// No error, because parse() would narrow type from 'any' to ObjWithFirstName. check
let firstName: string = parse(objStr).firstName;

// Error: property 'secondName' does not exist on type 'ObjWithFirstName'. check
let secondName: string = parse(objStr).secondName;

// any concat operations render it to string.. not sure there is a way in the type system to make this part work.
let corruptStringified1: string = "]extra text[" + objStr; 
let corruptStringified2 = "]extra text[" + objStr;
```

**Comment by mhegazy** [comment]
As @RyanCavanaugh noted, this is a very specialized scenario, and does not benefit the general population, you can always add your "taged" strings to parse and striginify.

**Comment by aleksey-bykov** [comment]
use tag types:

```typescript
declare global {
    class Stringified<T> { private ___stringified T; }
    interface JSON {
    //    stringify(value: any, replacer?: (key: string, value: any) => any, space?: string | number): string;
         stringify<T>(value: T, replacer?: (key: string, value: any) => any, space?: string | number): Stringified<T>;
    }
}
```

**Comment by shirakaba** [comment]
@aleksey-bykov Your `JSON.stringify()` interface is exactly what I need, however your `Stringifed<T>`, by not relating to the `string` primitive, does not facilitate string concatenation. Could you explain your reasoning behind adding the `___stringified: T` field?

@mhegazy Your mapped types solution works wonders. I don't understand what the `{ "_ value": T[P] }` type means, however. Is "_ value" a magic name of some sort? I don't see any usage like it in the TypeScript docs.

Here is what I've come to use, by combining mhegazy's `Stringified<T>` and aleksey-bykov's JSON interface:

```ts
export type LicenseObject = { keys: JsonWebKey[]; }
declare global {
    type Stringified<T> = string & {
        [P in keyof T]: { "_ value": T[P] }
    };
    interface JSON {
        //    stringify(value: any, replacer?: (key: string, value: any) => any, space?: string | number): string;
        stringify<T>(value: T, replacer?: (key: string, value: any) => any, space?: string | number): string & Stringified<T>;
        // parse(text: string, reviver?: (key: any, value: any) => any): any;
        parse<T>(text: Stringified<T>, reviver?: (key: any, value: any) => any): T;
    }
}
```

**Comment by mhegazy** [comment]
> @mhegazy Your mapped types solution works wonders. I don't understand what the { "_ value": T[P] } type means, however. Is "_ value" a magic name of some sort? I don't see any usage like it in the TypeScript docs.

no, it is a regular property. i just wanted to add a space in the name to filter it out of the completion list when you hit `o.`. (the language service filters out any thing that is not a valid identifier name, so something that starts with a `@` or a digit would do the same as well)

**Comment by shirakaba** [comment]
@mhegazy So `Stringified<T>` is the intersection of a string and an anonymous interface with the following behaviour, as far as I understand:

*Every property matching a key of `T` effectively maps to an object which has one field, named `"_ value"`, which is itself typed as `T[P]`.*

What exactly is this doing? Regardless of whether or not it shows up in the completion list, what is the purpose of `"_ value"` here?

**Comment by mhegazy** [comment]
`Stringified<T>` is a string, and a tagged object type. the `string` makes it behave like string for reading, the tagged object type makes it so that you can not assign anything to it unless it came from a a stringify from the same type.. so `Stringified<{a:number}>` is not assignable to `Stringified<{a:string}>`. it also allows you to infer the type back in `parse` and get your `T` back.

You could also have done this with a simple intersection, i.e. `string & T`, but that makes the type appear to have the properties of `T`, which is not correct at runtime; the `"_value"` prop, makes it so that the type  `T` is tucked under one property, and reduces the chance that you by mistake would do something like `stringified.a` and get away with it, you will have to write `stringified["_ value"]` which is less accessible.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
