### ISSUE TITLE
Problem with aliases

### ISSUE THREAD

**Issue by wgebczyk** [Microsoft/TypeScript#1924]
For following code:
```
module Aaa {
  export class Abc {
  }
}
module Bbb {
  type aAbc = Aaa.Abc;
  export class Xyz {
    constructor() {
      var c: aAbc = new aAbc();
      var d: any;
      if (d instanceof aAbc) {
        
      }
    }
  }
}
```

I'm getting:
...\file1.ts(11,25): error TS2304: Build: Cannot find name 'aAbc'.
...\file1.ts(13,24): error TS2304: Build: Cannot find name 'aAbc'.

I can use alias when declaring variable, but in ither places it seems to be ignored.
Is this by design? (if so, why?)

**Comment by RyanCavanaugh** [comment]
`type` only creates a *type* name; the expression `new aAbc()` refers to a *value*.

If you want both, use `import aAbc = Aaa.Abc` instead. That will get both the type and the value.

**Comment by wgebczyk** [comment]
OK, "new aAbc()" might refers to something else. but "aAbc" refers to "type aAbc = Aaa.Abc" and as per explanation "Type aliases are exactly the same as their original types; they are simply alternative names" this should work. In C# you can use that, so expectation is to have it working here too...

My understanding that if this is "alias" then it should work everywhere (like when before compilation using find&replace). Otherwise I do not understand reason of adding something like that to language...

**Comment by danquirk** [comment]
A TypeScript class introduces a type name and a value of that name (the constructor function), as this is essentially how JavaScript works. Expecting something to just work the same as C# is not realistic, there are very fundamental differences between the two.

**Comment by wgebczyk** [comment]
OK, but following your thoughts, the JS does not have "alias" thing. If you introduce new feature to language and use name for that feature that "collides" with existing feature of another language, you borrow also meaning of that name.

Honestly expecting to write:
var a: aAbc = new Aaa.Abc();
makes completely no sense from code readability.

Either remove those "semi aliases" or expand usage of them.

**Comment by danquirk** [comment]
_If you introduce new feature to language and use name for that feature that "collides" with existing feature of another language, you borrow also meaning of that name._

This is simply not the case. There are numerous examples of languages that have similar concepts with different meanings (generics in Java vs C#, differences in regular expression syntax between languages, symbols in ES6 vs Ruby, async in F# vs C#, etc). There are high level concepts that many languages want but whose specifics must work differently in each language for a variety of reasons. To expect a new language to use those concepts if and only if they can match exactly with some other completely different language is not realistic. 

JavaScript and C# simply have different semantics for precisely what a class means. You cannot do this in C#:

```cs
class MyClass { ... }
// elsewhere:
var cons = MyClass;
var c = new cons();
```

The declaration of ```MyClass``` does not introduce a value called ```MyClass```. And so C# gives you an error on this code like "MyClass is a 'type' but is used like a 'variable.' This is not how JavaScript works. JavaScript allows exactly this type of thing, which also means you need a way to differentiate between the type of the constructor function (the type of ```cons``` above) and the type of objects it creates (```c``` above). Classes are fundamentally different in the two languages, and so you will see differences emerge around other features that interact with them. ```import``` aliases allow you to create aliases that represent multiple kinds of things (ex a name that is both a type and a value). Type aliases do not allow this, but do let you alias union types and other things to a single, easy to use name.

**Comment by CyrusNajmabadi** [comment]
Hey @wgebczyk , i think you're misinterpreting this bit: "OK, "new aAbc()" might refers to something else. but "aAbc" refers to "type aAbc = Aaa.Abc" and as per explanation "Type aliases are exactly the same as their original types; they are simply alternative names" this should work."

The key part to note is " the same as their **original types**".   For something like ```class Abc``` there are actually two things created.  A **value** and a **type**.  A **type alias** only allows you to alias a **type**.  So, the quote up there is exactly correct.  The type alias is exactly the same as the **original type**.  But it is not the same as the **original type AND value**.

Type aliases give you an alias to a type.  And you can get a value alias with Javascript's built in 'var' feature.

**Comment by wgebczyk** [comment]
OK. I agree that from JS perspective that might be resonable. At same time you agree that "var a: aAbc = new Aaa.Abc();" is weird - defines type "aAbc" and initialize with "Aaa.Abc". (Lets skip for moment type inference as we can split this statement into 2 of them declaration and initialization). Readability of such constructs is lowered.

The question is - why we cannot expand aliases to be used in other places? The TypeScript team owns specification (grammar) and can allow usage only in those areas that will not introduce some possible conflicts?

**Comment by RyanCavanaugh** [comment]
>  At same time you agree that "var a: aAbc = new Aaa.Abc();" is weird 

It isn't. TypeScript is not C#. There is not a 1:1 correlation between things you can `new` and types.

> why we cannot expand aliases to be used in other places? 

There is already syntax for doing what you want. It's `import aAbc = Aaa.Abc;`. We don't need two ways of doing the same thing.

We have a very simple system here:
 * You want the value: use `var`
 * You want the type: use `type`
 * You want both: use `import`

This is like asking why we don't expand the definition of "unicycle" to include objects with two wheels. There's already a word for that, "bicycle", and the prefixes uni- and bi- have meanings.

**Comment by wgebczyk** [comment]
OK. You are right. The import would be sufficient and lets put alias for some obscure usages :)
Thank you!

**Comment by NN---** [comment]
@RyanCavanaugh I have searched for explanation and found it here.
The explanation should exist in the wiki.

For instance 
https://github.com/Microsoft/TypeScript/wiki/Modules
It is written: ". This is similar to using var, but also works on the type and namespace meanings of the imported symbol" 
It should be added also "similar to 'type' but, but also works on the value.".
