### ISSUE TITLE
2.6 takes a very long time to --watch on large projects

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Microsoft/TypeScript#19253]
**TypeScript Version:**  2.6.0-rc

**Code**

```shell
# Where tsconfig.json includes hundreds of .ts files (~400 on my smallest repro project)
tsc -w tsconfig.json
```

```json
{
    "compilerOptions": {
        "declaration": true,
        "experimentalDecorators": true,
        "jsx": "react",
        "noImplicitAny": true,
        "noImplicitReturns": true,
        "noImplicitThis": true,
        "noResolve": true,
        "pretty": true,
        "sourceMap": true,
        "target": "es5"
    },
    "include": [...]
}

```

**Expected behavior:**

After adding an unused public method to a class, it should eventually finish compilation.

**Actual behavior:**

After >10 minutes of waiting a few times, I've terminated the process. I've also tried reinstalling 2.6.0-rc.

Side note: on a smaller project of 28 items, with identical tsconfig settings (except that `strictNullChecks` is on), recompilation from adding an unused public method to a class went from ~1000ms average over 5 runs to 1500ms average (measured from the time TS outputs the `File_change_detected_Starting_incremental_compilation` diagnostic to the time it outputs the `Compilation_complete_Watching_for_file_changes` diagnostic).

The code isn't open source so I can't post it here, but I have emailed a few TypeScript team members instructions on how to get to it before (Office Sway).

**Comment by mhegazy** [comment]
@JoshuaKGoldberg can you share the project info with @sheetalkamat and myself?

**Comment by JoshuaKGoldberg** [comment]
Sure!

Also, sure enough, right after I posted this issue, two long-running watchers ended up in out-of-memory heap failures.

```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
```

**Comment by tolgaek** [comment]
I'm experiencing same error with v2.6.2. It only seems to happen after a file has changed

**Comment by aldendaniels** [comment]
Also experiencing this issue. Added comment to related issue #19662

**Comment by mhegazy** [comment]
@aldendaniels please file a new issue and give us more information to help diagnose the issue. ideally a sample project.
