### ISSUE TITLE
Refactorings for ES/CJS Interop

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#19261]
Given that we're committed to #16093 for the TypeScript 2.7 timeframe, we need to consider tooling for the following scenarios:

1. Convert `export =`-originating namespace imports to default-imports.
2. Convert `import = require` imports to default-imports

**Comment by mhegazy** [comment]
Related https://github.com/Microsoft/TypeScript/issues/19719
