### ISSUE TITLE
Common import/export refactorings are missing

### ISSUE THREAD

**Issue by bterlson** [Microsoft/TypeScript#19260]
There are two scenarios that come up for me all the time that presently don't have refactoring support:

1. Refactoring a named export into the default export and vice versa
2. Refactoring a bunch of explicit named imports into a namespace import and vice versa

**Commentary**:

I think both of these refactorings would be helpful and be used frequently. 1 is important to me because I can't decide on the shape of a module's exports until its export surface area is complete, and I switch between the two frequently during development.

2 is important to me when a module's named exports grow and grow and on the import side and I finally reach a point where I would like to move to a namespace import to avoid having to name every single import. This transformation is very painful to do by hand.

**Comment by amcasey** [comment]
@andy-ms I remember you implementing some import conversion refactorings.  Have some of these points already been addressed?

**Comment by andy-ms** [comment]
I haven't done either of the refactorings listed above. I did do a PR that converts from commonJS to ES6 modules (#19916), but the suggested refactorings would work entirely within ES6 modules already, so it's unrelated.
