### ISSUE TITLE
Use standardized names for locales in TS 2.6

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#19270]
**TypeScript Version:**  2.6.0-dev.2016

**Repo**

Try starting tsserver with `--locale de`

**Expected behavior:**
TS Server Loads german error messages

**Actual behavior:**
TSServer error. Instead you have to use `--locale deu`

I believe locale names should come from: https://msdn.microsoft.com/en-us/library/cc233982.aspx

For reference, here are the locales VS Code supports: https://code.visualstudio.com/docs/getstarted/locales

**Comment by mjbvz** [comment]
@mhegazy Not sure if these locale names have been exposed before or not in the API. If they have and we can't change them, I will add a mapping function in vscode

**Comment by mhegazy** [comment]
that is an oversight on my side. will fix it
