### ISSUE TITLE
Don't use smartquotes in localized error messages

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#19273]
**TypeScript Version:**  2.6.0-dev.2016

**Code**

```ts
// @ts-check
function foo() {
    var a = 1
    a = '123'
}
```

Start tsserver with `--local chs`

**Bug:**
Here's the error in english:

![screen shot 2017-10-17 at 3 36 48 pm](https://user-images.githubusercontent.com/12821956/31692998-1fba8dd2-b351-11e7-9726-446ff405954f.png)

and here's the localized one:

![screen shot 2017-10-17 at 3 36 29 pm](https://user-images.githubusercontent.com/12821956/31693006-2b9e938c-b351-11e7-9b21-25e612d98849.png)

Notice that this one replaces the single quote `'` with a double quote `"`. The double quotes are also  smart quotes instead of regular ascii double quotes, which is odd looking in this context. I'm not sure if this was by design

**Comment by mhegazy** [comment]
That is what the localizes for this language chose to put in there. we really have no control over that. @danyeh any thoughts here?

**Comment by danyeh** [comment]
@mjbvz @mhegazy , from pure linguistic perspective, these double quotes are right which match language style and usage. Does this break functionality or break intended meaning? If so, we can revert back to be same as English. Let us know.
@janbaltus @joinliu2016, we may need to change translation based on the answer.

**Comment by mhegazy** [comment]
> Does this break functionality or break intended meaning?

I do not think so. I beleive this is @mjbvz stylistic observation.

**Comment by mhegazy** [comment]
Just to be clear. @danyeh you know best. if you believe this is the right quote style for the language then there is nothing we need to change here.

**Comment by danyeh** [comment]
Then it is by design. For information, here is where to download language style guide. https://www.microsoft.com/en-us/language/StyleGuides

**Comment by mhegazy** [comment]
thanks!

**Comment by mjbvz** [comment]
Thanks for the additional info. My concern was that, in english at least, smartquotes are more for text. They are not used often in code and will break some languages if you try to use them in place of ascii double quotes
