### ISSUE TITLE
`getCurrentDirectory` is marked as optional on LanguageServiceHost, but absence is an error

### ISSUE THREAD

**Issue by weswigham** [Microsoft/TypeScript#19278]
`getCurrentDirectory` is optional on `LanguageServiceHost` (as it inherits from `GetEffectiveTypeRootsHost`, and it is optional there), but calling `createLanguageService` with a host which does not implement `getCurrentDirectory` throws `TypeError: host.getCurrentDirectory is not a function`.

**Comment by weswigham** [comment]
@mhegazy I don't think this is a breaking change. The change that made it optional was only comitted [yesterday](https://github.com/Microsoft/TypeScript/commit/d05443bb1d3c346fbef4c2468ff06b00041b688d).

**Comment by mhegazy** [comment]
oh, i see. i thought the fix was to change `GetEffectiveTypeRootsHost.getCurrentDirectory` which is an overkill here.. you are correct. let's get this in then.
