### ISSUE TITLE
aspnet: Compiling C# aspnet project runs TypeScript compiler for wwwroot what is redundant and error-prone

### ISSUE THREAD

**Issue by evil-shrike** [Microsoft/TypeScript#19271]
I encountered a strange behavior in aspnet project where wwwroot contains *.ts. 
Building project will run TS compiler which seems excessive and can lead to strange error. Please see details in this issue - https://github.com/aspnet/Home/issues/2243
At first I beamed aspnet msbuild targets but it seems that it's ts's "feature".

As the bottom line: please remove logic for running silently ts compiler as build step while compiling aspnet core project.

**Comment by mhegazy** [comment]
Add [`<TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>`](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Compiler%20Options%20in%20MSBuild.md) to your project, and that should disable the TS build all together.

**Comment by evil-shrike** [comment]
@mhegazy yes, it's suggested in the mentioned issue. But I believe compilation should be enabled not disabled.

**Comment by mhegazy** [comment]
> But I believe compilation should be enabled not disabled.

the targets is included, and a `TypeScriptCompile` item exists in the project; the targets serach for all TypeScriptCompile and if it found any, it will be compiled. 
so either, 1. do not include the targets file (this is up the ASPnet team, i have no control over who references the targets), 2. do not have any `TypeScriptCompile` items in your project, either by not including any .ts files, or by changing their content type to `Content`, or 3. disable the build using `TypeScriptCompileBlocked`.

Also for the record, this has been the behavior of TS/ASP.net for the last 5 years.

**Comment by evil-shrike** [comment]
I have no any Content items in csproj for *.ts or any other items inside wwwroot.
I have no any `TypeScriptCompile` properties either in csproj. 
It's a just a default csproj but with some *.ts copied to wwwroot, nothing more.

>do not include the targets file (this is up the ASPnet team, i have no control over who references the targets),

I didn't include any additional target files. Probably I don't quite understand what you mean here.

So let me repeat, it's a simple aspnet core project without any special settings for TS. But just because some *.ts were put inside wwwroot I got ts compiler running and got unexpected compilation errors. It's weird. I understand now how TS compilation can be disabled but I can't understand why it happens by default.

**Comment by mhegazy** [comment]
The ASP.net targets include the TypeScript targets file.. your project includes the ASP.net targets, and transitively include the TypeScript targets.

**Comment by evil-shrike** [comment]
Ок, I'll reopen issue in aspnet..

**Comment by mhegazy** [comment]
> I have no any TypeScriptCompile properties either in csproj.

This sounds like a bug in our targets file to me.. if you have no TypeScriptCompile items, and not tsconfig.json, the task should not run.

**Comment by mhegazy** [comment]
https://github.com/Microsoft/TypeScript/issues/18312 tracks fixing this.
