### ISSUE TITLE
Code fix descriptions are not localized

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#19274]
**TypeScript Version:**  2.6.0-dev.201xxxxx

**Code**

Start tsserver with `--locale chs`

In the code:

```ts
var a = 1 + 2
```

Select `1 + 2` and trigger code fixes

**Expected behavior:**
Code fix descriptions are localized

**Actual behavior:**
These are not localized currently:

![screen shot 2017-10-17 at 3 49 02 pm](https://user-images.githubusercontent.com/12821956/31693470-9fb24096-b353-11e7-84c5-670fdde2ecb7.png)

**Comment by mhegazy** [comment]
We [get the localized resources](https://github.com/Microsoft/TypeScript/search?q=LEGO%3A+&type=Commits&utf8=%E2%9C%93) after the message is added. so there is a period of time where not all messages are localized. Should be localized now.
