### ISSUE TITLE
Playground: run scripts in one tab

### ISSUE THREAD

**Issue by attatrol** [microsoft/TypeScript#19289]
When i press "Run" button in https://www.typescriptlang.org/play/ it runs my script in a new tab so i have no time to open Dev-Tools and intercept `debugger;` instructions. There should be an option to run scripts in one tab for convenience.

**Comment by mootari** [comment]
As a workaround run the following code in your console to rebind the Run button so that it executes the Javascript in your current window:
```javascript
document.getElementById('execute').onclick = function(){eval(monaco.editor.getModels()[1].getValue())}
```

**Comment by orta** [comment]
The new playground works like this by default 👍
