### ISSUE TITLE
Feature: migration tool to convert a full project from JSDoc to TypeScript strict

### ISSUE THREAD

**Issue by cyrilletuzi** [microsoft/TypeScript#19285]
Currently, to stay aligned with native JavaScript, you can migrate a JavaScript project to TypeScript just by switching to `.ts` files and everything should be OK (except if there are real errors).

But you're not in `strict` mode, which is what you want if you come to TypeScript.

Now that JSDoc is understood by TypeScript, and following #18747, it would help TypeScript adoption a lot to have a tool to refactor a full JavaScript project, correctly commented with JSDoc, to TypeScript (applying #18747 quickfix everywhere).

It could even include the conversion from `.js` to `.ts` extension.

It would mean we can automatically migrate from a JS project to real TypeScript (aka `strict` mode).

**Comment by kitsonk** [comment]
Sounds like a perfect idea for a wider community project that leverages the TypeScript language services and [compiler API](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API).  Building it into `tsc` doesn't feel in line with the [design goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals) IMO.

**Comment by sandersn** [comment]
:+1: We would love to see a separate tool that does this. Typescript may add individual features over time to make it easier, but I think a "js2ts" tool is the right design.

**Comment by mhegazy** [comment]
We have made sure that all our codefix/refactoring logic is in a detachable form the language service API*. so it should be possible to leverage all the refacorings logic to achieve a standalone conversion tool.

(*) i am sure we will find bugs once we try to use them in a different context, but these should all be fixable.

**Comment by DanielRosenwasser** [comment]
Related is #19255

**Comment by stereobooster** [comment]
I have idea for another tool (but related) generate type definitions from js code annotated with JSDoc, but type checked with TypeScript. Example puppeteer: they use ES7 + JSDoc + TypeScript as a a checker. Related: https://github.com/GoogleChrome/puppeteer/pull/1170

**Comment by mhegazy** [comment]
> I have idea for another tool (but related) generate type definitions from js code annotated with JSDoc, but type checked with TypeScript.

Looking for https://github.com/Microsoft/TypeScript/issues/7546 ?

**Comment by stereobooster** [comment]
@mhegazy  yes, thank you very much

**Comment by cyrilletuzi** [comment]
Closing this as it has been told as outside TS goals.

**Comment by mhegazy** [comment]
It is out of scope of the TypeScript project, but we like to keep the suggestion active; a community member can pick this one up and provide a tool that accomplish the task. we would be happy to help as needed.

**Comment by cyrilletuzi** [comment]
Closing this issue as TypeScript now knows how to convert jsdoc to types for a whole file at once.

**Comment by fungiboletus** [comment]
This issue appear on search engines when you look for that.

How can you convert a `.js` with JSDoc comments to a `.ts` file ? I cannot find how in the documentation. [It's recommended to rename the file and fix it manually](https://www.typescriptlang.org/docs/handbook/migrating-from-javascript.html#moving-to-typescript-files).

**Comment by karlhorky** [comment]
Yeah I would like to be able to do this too - I would like a codemod or similar to be able to transition from this:

```js
function add (/** @type {number} */ a, /** @type {number} */ b) {
```

...to this:

```ts
function add (a: number, b: number) {
```

...as well as supporting all other features of JSDoc (eg. `@typedef` -> type alias, `@template` -> generics, etc).

I assume such a converter / codemod exists somewhere, but I haven't been able to find it yet...

**Comment by danielo515** [comment]
If anyone ever finds such codemod, or builds it, please come back here and let us know

**Comment by whocaresk** [comment]
> If anyone ever finds such codemod, or builds it, please come back here and let us know

https://www.npmjs.com/package/ts-migrate-plugins    
this is probably what you're looking for

**Comment by karlhorky** [comment]
@whocaresk do you know how well this works? How many different sorts of JSDoc annotations can it convert to TS?

cc @edsrzf

**Comment by sandersn** [comment]
There's also https://github.com/microsoft/ts-fix, which should let you run the jsdoc-to-types codefix on your whole project at once.
