### ISSUE TITLE
Intermitent wrong output with module: system

### ISSUE THREAD

**Issue by pocesar** [Microsoft/TypeScript#19280]
**TypeScript Version:**  2.6.0-dev.20171017

**Expected behavior:**

Correctly named system module

**Actual behavior:**

Incorrectly named module

Sometimes, when using tsc in watch mode, the output `outFile` is wrong. sometimes it's like this:

```js
System.register("components/cidadao/event", ["react", "moment", "lodash"], function (exports_36, context_36) {
```
and sometimes it's like this:
```js
System.register("cim-user/src/components/cidadao/event", ["react", "moment", "lodash"], function (exports_36, context_36) {
```

I have no idea how to reproduce. But it started happening since 20171013

**Comment by mhegazy** [comment]
Any additional information would help

**Comment by pocesar** [comment]
I'm trying to reproduce, but it's really random. if I save the file quickly, both triggers will lead to different outputs

**Comment by pocesar** [comment]
It seems that If I have two projects with watch mode on, and one build triggers the build from another, it will randomly generate the wrong one. I have cim-shared-ui that is `npm linked` to my main project `cim-user`, and depending on the other that it's triggered, it generates the wrong output. 

`cim-user` has  `outFile` set to `dist/app.js` and `module: "system"` and `cim-shared-ui` has only `module: "system"`

**Comment by mhegazy** [comment]
Can u share the projects?

**Comment by pocesar** [comment]
can't share, but it seems that the first time tsc -w starts, it works. all the following compilations besides the first output the wrong module names

**Comment by sheetalkamat** [comment]
I am not able to tell if this is same as #19290 or something different.
When you compile your both projects without --w and build them with two different order, is the output file different. (that is first build project1, then project 2. What is the output file at this stage. Now build project2 first and then project1, what is the output? is it different?)

Can you create sample repro if you cant share your project expecually Without repro its really hard to guess what kind of edits and what kind of changes are triggering the recompile and hence emit

**Comment by mhegazy** [comment]
We believe  #19435 should address this issue. @pocesar can you give tomorrow's `typescript@next` a try?

**Comment by pocesar** [comment]
@mhegazy @sheetalkamat  seems to have been fixed as well!

**Comment by mhegazy** [comment]
thanks for confirming.
