### ISSUE TITLE
Type error in inbuilt @types/node/index.d.ts 

### ISSUE THREAD

**Issue by mikemaccana** [Microsoft/TypeScript#19293]
**TypeScript Version:**  2.6.0-dev.20171018

**Code**

     tsc --lib ES2017 .\packages\myapp-database\index.ts

**Expected behavior:**

Inbuilt types work.

**Actual behavior:**

     node_modules/@types/node/index.d.ts(48,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'process' must be of type 'any', but here has type 'Process'.

A user here is having the same issue, however TS folk asked this to be filed seperately: https://github.com/Microsoft/TypeScript/issues/9725#issuecomment-274226193

**Comment by andy-ms** [comment]
You probably have two declarations of this variable somewhere, could you look for the other one? Find-all-references should help.

**Comment by mikemaccana** [comment]
Hi Andy, thanks for the quick reply! The code in `node_modules/@types/node/index.d.ts` with the error is shipped with TS itself, and seems to be reporting an error in the node stdlib. 

I started using Typescript yesterday - how to I match the `@types` error to the node stdlib?

**Comment by andy-ms** [comment]
`@types/node` isn't shipped with TypeScript itself, it's a separate NPM package. I can't reproduce your error just by installing that. You are getting an error at *one* variable declaration for `process`, but there is probably another one somewhere in your project.

**Comment by mikemaccana** [comment]
I have: 

    ... 
    process = require('process'),
    ...
 
In my `.ts` code, and removing it stops the error from appearing. But that's just requiring the module. Why is typescrpt not letting me import node's `process` module as the sensible, well known name `process`?

**Comment by andy-ms** [comment]
If there's already a `process` global variable, you shouldn't assign to it again.
However, you can use a module-local variable, using `import process = require("process");`. This has the advantage of being typed as `require` is just a function `string => any` if it doesn't appear in an `import` declaration.

**Comment by andy-ms** [comment]
`process.ENV` is undefined, but `process` is defined as a global variable in a node environment.

**Comment by mikemaccana** [comment]
@andy-ms Ah my bad, it's `env` not `ENV` and I can see [it's there all the time](https://nodejs.org/api/process.html). I swear it had to be imported some time in the past, but oh well. I'll close this.

Are you saying I should replace CommonJS imports using `require` with `import`?

**Comment by andy-ms** [comment]
> Are you saying I should replace CommonJS imports using require with import?
Yes, change `const x = require("x")` to `import x = require("x")`.
If using multiple exports of a commonjs module you can even do e.g. `import { readFile, writeFile } from "fs";`.

**Comment by mikemaccana** [comment]
OK thanks. Sorry for wasting your time to what amounted to '`process` is inbuilt now'! 😊

**Comment by mikemaccana** [comment]
Is there an equivalent of the node 'require everything at once'?

    import x = require("x"),
       y = require("y")

**Comment by andy-ms** [comment]
Just use multiple `import` statements.
