### ISSUE TITLE
Proposal: Add concatenable enum

### ISSUE THREAD

**Issue by jj09** [Microsoft/TypeScript#1929]
It would be nice if we can have some way (maybe attribute) that will convert enum like that:
```enum MyEnum<flags> { First, Second, Third}```

to 
```enum MyEnum  { First = 1 << 0, Second = 1 << 1, Third = 1 << 2}```

And later on to JavaScript.

This will allow to concat flags like that:

```if(someVar === MyEnum.First|MyEnum.Third) {...```

**Comment by jbondc** [comment]
I'd propose to infer the 'bit-flag' increment based on the first member expression:
```
enum MyEnum {
     First = 1 << 0, // 1 
     Second, // 2
     Third, // 4
 }
enum MyEnumStartAtZero {
     Zero = 0 << 1
     One, // 1 
     Two, // 2
     Four, // 4
     SomethingElse = 32,
     Increment, // 64
   }
```
Implemented this here:
https://github.com/Microsoft/TypeScript/compare/master...jbondc:setTypes-v2#diff-c3ed224e4daa84352f7f1abcd23e8ccaR10842

Good use case for generators :wink:

**Comment by tinganho** [comment]
Very good proposal. Manually updating bit values is a headache. It also play nicer with version control solutions like git.

I also like the proposed sugar for the binary expression.

**Comment by RyanCavanaugh** [comment]
We don't want things to happen differently based on initializers - things should be predicable without knowing all the magic rules about the form of an initializing expression.

Given the relative frequency of bitmasks in JavaScript vs the many low-level languages that *don't* have this feature, this doesn't meet the complexity/gain trade-off bar.

**Comment by jbondc** [comment]
@RyanCavanaugh Alternative could be some use of generator function:
```
function *BitShift(enum: {lastValue: number}) {
     if (enum.lastValue <= 0) {
        yield ++enum.lastValue;
     }

     enum.lastValue = enum.lastValue << 1;
     yield enum.lastValue;
}

// whatever syntax seems appropriate here...
enum foo with BitShift {
  a, b, c, d   // 0, 1, 2, 4
}
```

**Comment by jj09** [comment]
What about taking advantage of decorators?

```
@concatenable
enum Flags {
  first,
  second,
  third
}

**Comment by jbondc** [comment]
@RyanCavanaugh About other languages:
http://blog.denevell.org/golang-constants-enums.html
https://splice.com/blog/iota-elegant-constants-golang/

**Comment by jbondc** [comment]
More similar to iota:
```
function *BitShift(enum: {lastValue: number}) {
     if (enum.lastValue <= 0) {
        yield ++enum.lastValue;
     }

     enum.lastValue = enum.lastValue << 1;
     yield enum.lastValue;
}
enum MyEnum {
     First = 1 << BitShift //  where [<<] [Identifier], Identifier must be generator function
     Second, // 2
     Third, // 4
 }
```
I'd also add there are no integers in JavaScript. So ya relative low frequency of bitmasks in JavaScript is expected?
