### ISSUE TITLE
tsc watch is compiling files out of the rootDir

### ISSUE THREAD

**Issue by pocesar** [Microsoft/TypeScript#19290]
**TypeScript Version:**  2.6.0-dev.20171018

**Expected behavior:**

tsc watch compiles only files stated in tsconfig.json

**Actual behavior:**

tsc watch is compiling `npm linked` projects using the current folder's tsconfig. my sub project is a commonjs, and my root folder is system. it's compiling my commonjs subproject as system

**Comment by kitsonk** [comment]
Again, if you are going to raise an issue, it is helpful to provide your `tsconfig.json` instead of people trying to guess what is in it.

**Comment by pocesar** [comment]
main project:

options.json
```json
{
  "compilerOptions": {
    "module": "system",
    "jsx": "react",
    "target": "es5",
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "newLine": "lf",
    "allowJs": false,
    "noImplicitAny": true,
    "strictFunctionTypes": false,
    "baseUrl": "./",
    "noEmitOnError": true,
    "sourceMap": true,
    "alwaysStrict": true,
    "inlineSourceMap": false,
    "paths": {
      "*": [
        "node_modules/@types/*"
      ]
    },
    "lib": [
      "dom",
      "es2015",
      "es5"
    ]
  }
}
```
base.json
```json
{
  "extends": "./options.json",
  "exclude": [
    "./node_modules",
    "./jspm_packages",
    "./dist"
  ],
  "include": [
    "./generic.d.ts",
    "src/*.ts",
    "src/*.tsx",
    "src/**/*.tsx",
    "src/**/*.ts"
  ]
}
```
tsconfig.json
```json
{
  "extends": "./base.json",
  "compilerOptions": {
    "rootDir": "src",
    "outFile": "dist/app.js"
  }
}
```
-----
sub-project:
```json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "noImplicitAny": true,
        "noEmitOnError": true,
        "removeComments": true,
        "sourceMap": false,
        "strict": true,
        "rootDir": "./",
        "declaration": true,
        "listEmittedFiles": false,
        "preserveConstEnums": true
    },
    "exclude": [
        "test.ts"
    ]
}
```

**Comment by sheetalkamat** [comment]
The files in sub project (included however) are going to be compile using its compiler options, and files in the tsconfig.json (all the files included in the program from wherever they are) are going to compile using those settings. So when you compile synchronously (without --w) you are controlling which one gets emitted when, but --watch is going to be asynchronous and the emit order is going to be unpredictable.

Having said that, without having some kind of repro (sample project and files being edited) its hard to figure out if this is as expected or some issue.

**Comment by pocesar** [comment]
using TS with npm link is getting harder and harder with each new release, honestly. it's a hot mess

**Comment by mhegazy** [comment]
We believe  #19435 should address this issue. @pocesar can you give tomorrow's `typescript@next` a try?

**Comment by pocesar** [comment]
will do @mhegazy

**Comment by pocesar** [comment]
so far so good, seems to have been fixed. if I find anything else, I'll reopen

**Comment by mhegazy** [comment]
thanks!
