### ISSUE TITLE
Pressing enter to simultaneously commit a completion item and format the line has only one undo stack entry

### ISSUE THREAD

**Issue by JsonFreeman** [Microsoft/TypeScript#1930]
Given the following code:
```ts
var doodle;
if (true) {

$
}
```
If you type `doo`, and then press enter to commit the completion item, it also formats. However, if you then undo the action, it not only undoes the formatting, it undoes the completion as well. I would expect to have to undo twice to get rid of the completion.
![completionformattingundo](https://cloud.githubusercontent.com/assets/8052525/6051570/31c2c22e-ac7e-11e4-8358-2ebfb7d215cd.gif)

**Comment by danquirk** [comment]
C# displays similar behavior, believe this is a Roslyn issue we've inherited.

**Comment by mhegazy** [comment]
@paulvanbrenk have a fix for this.

**Comment by paulvanbrenk** [comment]
@mhegazy I don't have a fix... the problem @JsonFreeman is seeing is that the commit and the format are part of the same 'undo' step.

**Comment by mhegazy** [comment]
Marking this one as external.
