### ISSUE TITLE
for..in over array of string enum type casts to string type

### ISSUE THREAD

**Issue by garbles** [Microsoft/TypeScript#19311]
**TypeScript Version:**  2.5.3

**Code**

[Playground example here](https://www.typescriptlang.org/play/index.html#src=enum%20Topping%20%7B%0D%0A%20%20Cheese%20%3D%20'cheese'%2C%0D%0A%20%20Olives%20%3D%20'olives'%2C%0D%0A%7D%0D%0A%0D%0Atype%20Pizza%20%3D%20%7B%0D%0A%20%20toppings%3A%20Topping%5B%5D%3B%0D%0A%7D%3B%0D%0A%0D%0Aconst%20pizza%20%3D%20%7B%0D%0A%20%20toppings%3A%20%5BTopping.Cheese%5D%0D%0A%7D%3B%0D%0A%0D%0Afunction%20calculateToppingPrice(topping%3A%20Topping)%3A%20number%20%7B%0D%0A%20%20%2F%2F%20...%20whatever%0D%0A%20%20%20%20return%200%3B%0D%0A%7D%0D%0A%0D%0Alet%20pizzaCost%20%3D%2010%3B%0D%0A%0D%0Afor%20(let%20topping%20in%20pizza.toppings)%20%7B%0D%0A%20%20pizzaCost%20%2B%3D%20calculateToppingPrice(topping)%3B%0D%0A%7D)

```ts
enum Topping {
  Cheese = 'cheese',
  Olives = 'olives',
}

type Pizza = {
  toppings: Topping[];
};

const pizza = {
  toppings: [Topping.Cheese]
};

function calculateToppingPrice(topping: Topping): number {
  // ... whatever
  return 0;
}

let pizzaCost = 10;

for (let topping in pizza.toppings) {
  // Argument of type 'string' is not assignable to parameter of type 'Topping'.
  pizzaCost += calculateToppingPrice(topping);
}
```

**Expected behavior:**

The let `topping` in the for..in loop is of type `Topping`

**Actual behavior:**

The let `topping` in the for..in loop is of type `string`

**Comment by DanielRosenwasser** [comment]
I think you meant to use a `for`-`of` loop. Thanks JavaScript...

**Comment by garbles** [comment]
@DanielRosenwasser ughuyghuhguh.... thank you
