### ISSUE TITLE
Make "." the default rootDir in tsconfig.json

### ISSUE THREAD

**Issue by RyanCavanaugh** [Microsoft/TypeScript#19318]
Per discussion with @mhegazy , we should consider making the default value of `rootDir` be `"."` if it's not specified in `tsconfig.json`. This most likely matches user intuition much closer than the current behavior (infer a root, which makes the structure of the outDir unpredictable) and lessens the burden for people moving to the upcoming project reference structure

**Comment by mhegazy** [comment]
This is a duplicate of https://github.com/Microsoft/TypeScript/issues/16563

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
