### ISSUE TITLE
recursive reference occured and I don't know how to describe this....

### ISSUE THREAD

**Issue by fc01** [Microsoft/TypeScript#19323]
```ts


const XXX1 = <T>(obj: { a: T, b: (v: any) => any }) => 1

class Test1 {

    // td is any <--------------------------  why ????????????????
    td = XXX1<string>(
        { a: 'aaa', b: v => this.state.x + 123 } //as any   <----------
    )

    // state is any <-------------------------- why ????????????????
    state = {
        td: this.td,
        x: 1,
        y: 2
    }
}



const XXX2 = (obj: { a: string, b: (v: any) => any }) => 1

class Test2 {

    //ok
    td = XXX2(
        { a: 'aaa', b: v => this.state.x + 123 }
    )

    //ok
    state = {
        td: this.td,
        x: 1,
        y: 2
    }
}
```

**Comment by DanielRosenwasser** [comment]
You can reduce this slightly.

```ts
function f<T>(obj: (v: any) => any) {
  return 100;
}

class Test1 {
    foo = f(v => this.bar.x + 123)

    bar = {
        foo: this.foo,
        x: 100
    }
}
```

I believe what is happening here is that you when we try to get the type of `td`, we need to check the call for `XXX2`. In that process, we need to make sure that the function `v => this.bar.x + 123` is assignable to `(v: any) => any`. This requires figuring out the type of `this.bar.x`, which requires us type-checking `this.bar`.

However, `this.bar` references `this.foo` in that object literal. TypeScript detects a circularity and by default we just give you the type `any`. Under `noImplicitAny`, TypeScript will detect the circularity and give you an error.

The only thing you can really do here is add a type annotation.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
