### ISSUE TITLE
Could not install typings files for JavaScript language features. Please ensure that NPM is installed or configure 'typescript.npm' in your user settings

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#19325]
_From @sharno on October 19, 2017 1:55_

- VSCode Version: 1.17.2
- OS Version: macOS 10.12.6

Steps to Reproduce:
1. Load a big JS project
2. open a file inside to edit

Checking the npm path, it's correct and even putting it manually gives the same error

checked the tsserver log, I found those errors:
```

Entry for package 'babel-loader' does not exist in local types registry - skipping...
Entry for package 'babel-polyfill' does not exist in local types registry - skipping...
Entry for package 'babel-preset-es2015' does not exist in local types registry - skipping...
Entry for package 'babel-preset-react' does not exist in local types registry - skipping...
Entry for package 'babel-preset-stage-0' does not exist in local types registry - skipping...
Entry for package 'babel-runtime' does not exist in local types registry - skipping...
Entry for package 'babel-eslint' does not exist in local types registry - skipping...
```

and the other file showed:
```
Info 38   [21:9:43.497] Received response: {"kind":"event::initializationFailed","message":"Command failed: \"/usr/local/bin/npm\" install --ignore-scripts types-registry"}
Info 39   [21:9:43.497] event: {"seq":0,"type":"event","event":"typesInstallerInitializationFailed","body":{"message":"Command failed: \"/usr/local/bin/npm\" install --ignore-scripts types-registry"}}
```
running these commands works from terminal but only after removing the quotations that are escaped

It's worth mentioning that I'm using Fish Shell but it's configured properly (I suppose)

Also this error appears only in this project

Reproduces without extensions: Yes

_Copied from original issue: Microsoft/vscode#36520_

**Comment by mjbvz** [comment]
_From @sharno on October 19, 2017 3:5_

Checked the path in VSCode's developer console and I found that `/usr/local/bin` is present there. Don't know why the command `\"/usr/local/bin/npm\" install --ignore-scripts types-registry`

**Comment by mjbvz** [comment]
@sharno Can you try upgrading to TypeScript 2.6 by following these instructions: https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions

I believe that @andy-ms added some additional logging for the typings installer that may help us track down what is going wrong

**Comment by sharno** [comment]
@mjbvz interestingly the issue totally disappears when I installed `typescript@next` (2.6) and configured VSCode to use it. VSCode stopped showing me the warning. It returns again though when I fall back to `typescript@latest` (2.5.3). Maybe it was a bug with (2.5.3)? 

found in the logs this when using (2.6)
```
Exec: npm install --ignore-scripts types-registry
    Succeeded. stdout:
    + types-registry@0.1.304
    updated 1 package in 0.817s
```

but still found those
```
Entry for package 'babel-loader' does not exist in local types registry - skipping...
Entry for package 'babel-polyfill' does not exist in local types registry - skipping...
Entry for package 'babel-preset-es2015' does not exist in local types registry - skipping...
Entry for package 'babel-preset-react' does not exist in local types registry - skipping...
Entry for package 'babel-preset-stage-0' does not exist in local types registry - skipping...
Entry for package 'babel-runtime' does not exist in local types registry - skipping...
...
```
and many other packages

**Comment by mhegazy** [comment]
closing for now. please reopen if you see the issue again on 2.6.
