### ISSUE TITLE
Test Case Issue

### ISSUE THREAD

**Issue by adnan1naeem** [Microsoft/TypeScript#19333]
I have the following test case in my project which is failling:
	

it('should have redux store in "ref"', () => {
	const App =BR.boot({renderApp:false});

			const component =TestUtils.renderIntoDocument (
				<App/>   //error at this point
			);
		 expect(BR.refs.store).toBeTruthy();
	 });

I am getting an error:
 Unterminated regular expression  >

**Comment by andy-ms** [comment]
Is it possible that you don't have JSX parsing enabled? (Try renaming the file to have a `.tsx` extension.)
Could you try to get a standalone repro of this error?

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
