### ISSUE TITLE
Allow enums as object literal keys

### ISSUE THREAD

**Issue by aminpaks** [Microsoft/TypeScript#19332]
**TypeScript Version:**  2.5.3

**Code**

```ts
enum SomeValues {
  first,
  second,
}

interface SomeInterface {
  [key: SomeValues]: string; // <-  An index signature parameter type must be 'string' or 'number'
}

```

**Expected behavior:**
Enums are made of either numbers or strings, they should be allowed in object literals keys.

**Actual behavior:**
An index signature parameter type must be 'string' or 'number'

**Comment by RyanCavanaugh** [comment]
Duplicate #13042

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
