### ISSUE TITLE
Cannot get expected intellisense when storing class in object

### ISSUE THREAD

**Issue by Alphapage** [Microsoft/TypeScript#19338]
**TypeScript Version:**  2.5.3

**Code**

```ts
//e.ts
class C{
    constructor(s:string){}
    test(){}
}
const c={C:C}
export {c,C}

//test.ts
import {c,C} from './e'
const c1:C=null;c1.test()
const c2:typeof c.C=null;c2.prototype.test() //problem
//expected: c2.test()  as c1.test()
// or:      const c2:c.C=null;c2.test() 
// or:      const c2:(typeof c).C=null;c2.test()
```

**Expected behavior:**
Intellisense is showing `prototype` to get access to test method for c2. I expect it to show as with c1.
**Actual behavior:**
Need to export/import the class to get typing without `prototype` which is unnecessary.

I don't want to export class C, only object c. Is there another way to achieve this ?
Thank you in advance for your help.

**Comment by andy-ms** [comment]
You declared `const c2: typeof c.C`.
`c` is on object `{C:C}`. So `typeof c.C` is just `typeof C` (the class).
The only object that's `typeof C` is `C` itself. So the only thing you could assign to `c2` (besides `null` if `--strictNullChecks` is not enabled) is `C` -- not an *instance* of `C` but the class itself.

**Comment by Alphapage** [comment]
I'm agree with you: `typeof c.C` is just `typeof C`, but I need it to be `C` not `typeof C`
So`(typeof c).C` is expected to get the correct intellisense behaviour I think.

**Comment by andy-ms** [comment]
Not sure what you're trying to do here, but you could do:
```ts
export namespace c {
    class C { ... }
}
```
That way `c.C` will have both a value and type meaning, so you could type a variable as `const c2: c.C`.

**Comment by Alphapage** [comment]
The problem is that I loose `const c={C:C}`. namespace is for typing and I want to add other properties to the object. Your workaround can't apply in my case because I will have to export two pieces of code instead of one as I was expecting.I don't understand why `(typeof c).C` is forbidden.

**Comment by andy-ms** [comment]
Because in `const c = { C: C }`, `c` is a value. A property of a value is always a value.
You can add other properties to a namespace too, just add more `export`s inside the body.
