### ISSUE TITLE
Add 'hasBOM' to SourceFile

### ISSUE THREAD

**Issue by jez9999** [Microsoft/TypeScript#19344]
It would be useful to me to know whether a source file has a BOM or not.  A boolean `hasBOM` on the `SourceFile` interface would be nice, and it should get set in `program.ts` and anywhere else a `SourceFile` is created.

The alternative would be to have a property similar to `text` that has the raw bytes of the source file in.  Unfortunately, `text` itself does not contain the BOM as it has been stripped out by `sys.readFile()` eg.

https://github.com/Microsoft/TypeScript/blob/master/src/compiler/program.ts#L95

As the charset has been passed in, the BOM is removed if it exists.

**Comment by jez9999** [comment]
The boolean would be equal to something like: `file.charCodeAt(0) === 0xFEFF`

**Comment by RyanCavanaugh** [comment]
What for?

**Comment by jez9999** [comment]
My particular use-case is to be able to check the existence of the BOM in a TSLint rule.

**Comment by j-oliveras** [comment]
You can do something like tslint encoding rule: https://github.com/palantir/tslint/blob/master/src/rules/encodingRule.ts

**Comment by jmlopez-rod** [comment]
@j-oliveras , he was trying to avoid having to read the file again since this has already been done by the compiler.

**Comment by mhegazy** [comment]
We used to traffic this information int he past not he sourceFile, and it was getting a bit tedious and error-prone. we have stopped that since TS 1.1, and do not think we have plans to put that back.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
