### ISSUE TITLE
Symbol-named properties get element-access completions

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#19349]
```ts
const c = Symbol();
let obj = { [Symbol.iterator]: 100 };
let a = obj['/**/']
```

Go to the `/**/` marker and request a completion.

**Expected**: No completions.
**Actual**: Completions for `__@iterator`!

Currently with #15473, this is exacerbated.

**Comment by mhegazy** [comment]
PRs welcomed.

**Comment by rbuckton** [comment]
I created a PR to fix this, since this is more noticeable with the dynamic names PR.
