### ISSUE TITLE
function overloads do not narrow types based on class

### ISSUE THREAD

**Issue by xealot** [Microsoft/TypeScript#19340]
**TypeScript Version:**  2.5.3

**Code**

I apologize if this is already an issue, I searched quite a bit but I'm not sure exactly what to look for.

```ts
export class Selector {
    constructor(public selector: string) { }
}

export class AllSelector {
    constructor(public selector: string) { }
}


export class FirePage {
    select(selector: Selector): string;
    select(selector: AllSelector): string[];
    select(selector: Selector | AllSelector): string | string[] {
        return true ? "thing" : ["thing"];
    }
}

const fp = new FirePage();

const metaTags = new AllSelector("meta");
const adsTargetRight = new Selector("#sideburn-right");

const many = fp.select(metaTags);
const one = fp.select(adsTargetRight);
```

[playground](https://www.typescriptlang.org/play/#src=export%20class%20Selector%20%7B%0D%0A%20%20%20%20constructor(public%20selector%3A%20string)%20%7B%20%7D%0D%0A%7D%0D%0A%0D%0Aexport%20class%20AllSelector%20%7B%0D%0A%20%20%20%20constructor(public%20selector%3A%20string)%20%7B%20%7D%0D%0A%7D%0D%0A%0D%0A%0D%0Aexport%20class%20FirePage%20%7B%0D%0A%20%20%20%20select(selector%3A%20Selector)%3A%20string%3B%0D%0A%20%20%20%20select(selector%3A%20AllSelector)%3A%20string%5B%5D%3B%0D%0A%20%20%20%20select(selector%3A%20Selector%20%7C%20AllSelector)%3A%20string%20%7C%20string%5B%5D%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20true%20%3F%20%22thing%22%20%3A%20%5B%22thing%22%5D%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aconst%20fp%20%3D%20new%20FirePage()%3B%0D%0A%0D%0Aconst%20metaTags%20%3D%20new%20AllSelector(%22meta%22)%3B%0D%0Aconst%20adsTargetRight%20%3D%20new%20Selector(%22%23sideburn-right%22)%3B%0D%0A%0D%0Aconst%20many%20%3D%20fp.select(metaTags)%3B%0D%0Aconst%20one%20%3D%20fp.select(adsTargetRight)%3B)

**Expected behavior:**

`many` should know it is of type `string[]` and `one` should know it is of type `string`

**Actual behavior:**

The type narrowing doesn't seem to occur in this case.

**Comment by andy-ms** [comment]
Isn't the problem just that this works?
```ts
export class Selector {
    constructor(public selector: string) { }
}

export class AllSelector {
    constructor(public selector: string) { }
}

const x: Selector = new AllSelector("");
```

Send your :+1: to #202.

**Comment by wayneseymour** [comment]
202?  Wow, that seems really old

**Comment by xealot** [comment]
You're absolutely right @andy-ms, if I vary the input parameters of the class it does indeed start to work. Super weird. Thanks for the insight on this though. I will send my 👍  to #202.
