### ISSUE TITLE
Improve wrong usage of `case` compile errors

### ISSUE THREAD

**Issue by ubershmekel** [microsoft/TypeScript#19352]
**TypeScript Version:**  2.6.0-dev.201xxxxx

**Code**
```
// This works
for (const cs of [1,2,3]) console.log(cs);

// This doesn't, but the compile error is cryptic
// Variable declaration expected.
// '=' expected.
for (const case of [1, 2, 3]) console.log(case);
```

**Expected behavior:**
Emit an error like `"case" clauses can only appear in a switch statement`

**Actual behavior:**
Emits these errors:
`Variable declaration expected.`
`'=' expected.`

**Comment by massimonewsuk** [comment]
I had this same error message just now and spent like 10 minutes trying to decipher it. It's not a very good error message at all.

It is also printed out for a simple line of code like this:
```
const case = "123";
```

Would be cool if it could say something like cannot use reserved keyword as variable name.

**Comment by DanielRosenwasser** [comment]
Thanks @JoshuaKGoldberg!
