### ISSUE TITLE
Document how to disable Automatic Type Acquisition (ATA)

### ISSUE THREAD

**Issue by mprobst** [microsoft/TypeScript#19369]
`tsserver` automatically reaches out to install type definitions. We'd like to disable this behaviour in our setup, so we can have reasonably reproducible builds and don't accidentally execute code off the internet.

PR #12373 suggests that a `tsconfig.json` entry `{"typeAcquisition": {"enable": false}}` might do the trick, but there are no docs on this.

**Comment by andy-ms** [comment]
ATA shouldn't happen on a TypeScript project anyway -- it sounds like that is what you are using since you mention a build. It is just for JS projects and should only affect the editing experience.
We should document that option though.

**Comment by jakebailey** [comment]
Just looking at old issues; this has been documented on the site for a while: https://www.typescriptlang.org/tsconfig#typeAcquisition
