### ISSUE TITLE
Failure to infer subtype of string despite perfect literal match

### ISSUE THREAD

**Issue by axefrog** [Microsoft/TypeScript#19363]
**TypeScript Version:**  2.6.0-insiders20171013 _and_ 2.5.3

**Code**

```ts
interface Foo  {
  '@type': 'foo/bar';
}

class Bar<T extends Foo> {
  constructor (public value: T) { }
}

function create<T extends Foo> (value: T): Bar<T> {
  return new Bar(value);
}

function main (): Bar<Foo> {
  const value = {
    '@type': 'foo/bar'
  };
  return create(value); // ERROR
}
```

**Expected behavior:**

No errors.

**Actual behavior:**

```
Argument of type '{ '@type': string; }' is not assignable to parameter of type 'Foo'.
  Types of property ''@type'' are incompatible.
    Type 'string' is not assignable to type '"foo/bar"'.
const value: {
    '@type': string;
}
```

Clearly I've hardcoded the correct literal. TypeScript should not be inferring that my hardcoded literal is any old string, and should recognize that it matches the string subtype described in the interface.

Interestingly, this works:

```ts
function main (): Bar<Foo> {
  return create({
    '@type': 'foo/bar'
  });
}
```

**Comment by mhegazy** [comment]
Please see https://github.com/Microsoft/TypeScript/issues/17363 and https://github.com/Microsoft/TypeScript/issues/17480

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
