### ISSUE TITLE
Show path intellisense for export from 

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#19365]
From https://github.com/Microsoft/vscode/issues/36547
**TypeScript Version:**  2.6.0-dev.20171013

**Code**

```ts
export {} from './' 
```

Trigger completions at the end of `./`

**Expected behavior:**
Returns same path intellisense as `import {} from './'`

**Actual behavior:**
No completions returned

```
}
[Trace  - 20:15:51] Sending request: completions (930). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/Users/matb/projects/san/index.ts",
    "line": 1,
    "offset": 19
}
[Trace  - 20:15:51] Response received: completions (930). Request took 1 ms. Success: true 
Result: []
```

**Comment by DanielRosenwasser** [comment]
Wait, is this not a duplicate of #19351?

**Comment by Kingwl** [comment]
seems a duplicate of 19351

**Comment by mjbvz** [comment]
Yep, closing as a duplicate of #19351
