### ISSUE TITLE
Make the `data` property of MessageEvent generic

### ISSUE THREAD

**Issue by j-f1** [microsoft/TypeScript#19370]
**TypeScript Version:**  2.5.1-insiders.20170825 (the one on the playground)

**Code**

https://github.com/desktop/desktop/blob/b6e26f7647e644daf8768245d1407540700d59cd/app/src/highlighter/index.ts#L112-L113

```ts
const myMessageHandler = (event: MessageEvent<MyDataType>) => {
  const data = event.data
}
```

**Expected behavior:**

`data` has the type `MyDataType`

**Actual behavior:**

- `Type 'MessageEvent' is not generic.`
- `data` has type `any` and must be cast to the appropriate type.

This could be fixed by updating `MessageEventInit`:

```ts
interface MessageEventInit<T = any> extends EventInit {
    lastEventId?: string;
    channel?: string;
    data?: T;
    origin?: string;
    ports?: MessagePort[];
    source?: Window;
}
```

and `MessageEvent`:

```ts
interface MessageEvent<T = any> extends Event {
    readonly data: T;
    readonly origin: string;
    readonly ports: any;
    readonly source: Window;
    initMessageEvent(typeArg: string, canBubbleArg: boolean, cancelableArg: boolean, dataArg: T, originArg: string, lastEventIdArg: string, sourceArg: Window): void;
}

declare var MessageEvent: {
    prototype: MessageEvent;
    new<T>(type: string, eventInitDict?: MessageEventInit<T>): MessageEvent<T>;
};
```

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

We also need to make sure that any change here to the lib passes  compilation with `--strict`.
