### ISSUE TITLE
The "TypeScript in 5 minutes" page should use "let" instead of "var"

### ISSUE THREAD

**Issue by Ghabriel** [Microsoft/TypeScript#19371]
The [TypeScript in 5 minutes](http://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes.html) page is a common way to get a first grasp about some key structures of TypeScript. However, all variable declarations in that page use `var` instead of `let`, which can lead developers to assume that it's the most appropriate way to declare a variable. I suggest that all instances of `var` are changed to `let`. 
Example code from that page:
```typescript
function greeter(person: string) {
    return "Hello, " + person;
}

var user = "Jane User";

document.body.innerHTML = greeter(user);
```

**Comment by mhegazy** [comment]
The source of the tutorial is in https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/tutorials/TypeScript%20in%205%20minutes.md. feel free to send a PR to update it.

**Comment by prateekgoel** [comment]
Can I submit a PR to this @mhegazy ?

**Comment by mhegazy** [comment]
PRs welcomed!

**Comment by prateekgoel** [comment]
Thanks. I am on it.
