### ISSUE TITLE
Improve ts.d documentation of Decomposition/Augmentation

### ISSUE THREAD

**Issue by gwicksted** [microsoft/TypeScript#19377]
Problem: it is complex to write a definition file for certain (very simplistic) js libs.

It is a weak point in the type definitions that, if not addressed by upcoming language features, should be more accessible in docs.

The concept of `Decomposition`/`Augmentation` **needs more visibility** in at least one of the [Documentation](https://www.typescriptlang.org/docs/handbook/declaration-files/deep-dive.html) pages since it's quite abstract.

Google usually links to the [Modules docs](https://www.typescriptlang.org/docs/handbook/modules.html) when looking up info related to `exports` or `ambient modules`.  Those docs are not that useful for authoring type definitions so it would be nice to **link to the deep dive**.

In #19372 @DanielRosenwasser offered a [really good link](https://github.com/joshtynjala/typescript-notes/blob/9b4ef98aa3298ccbaa6247047daae8bfd1fd1a11/Class-Decomposition.md) that I don't think is part of the official docs (**it should be a link** at the very least!)

Unfortunately the bottom of the link mentioned above returns a [404](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Writing%20Definition%20Files.md)

Example of a missing definition: `gulp` is quite popular and uses `pumpify` [npm](https://www.npmjs.com/package/pumpify) which uses this style of js.  Yet `pumpify` **does not have a DefinitelyTyped entry**.  Why not?  Sure, it's not used _that_ often but it likely has a lot to do with the difficulty of authoring the definition.

**Comment by RyanCavanaugh** [comment]
This doesn't seem actionable, nor a common complaint -- DT has 14,000+ contributors and nearly 7,000 types, so it can't be that hard to find a definition file for a library similar to the one being typed and crib from it.
