### ISSUE TITLE
Feature request: inference meta-analysis graph data

### ISSUE THREAD

**Issue by axefrog** [Microsoft/TypeScript#19383]
**TypeScript Version:**  2.5.3

I'm having an awful time trying to figure out why the complex interplay between various generic types and higher-order generic functions is producing certain inference failures, errors and mismatches to what I'm expecting. Beyond a certain level of complexity, trying to follow the trail to determine why TypeScript doesn't like a particular combination of things, or why it's inferring one type over another, becomes really, really frustrating, and I find myself spending more time fighting the type system than actually writing code.

Is there any way you could implement something that produces some kind of lazy directed graph data that can be explored to determine why TypeScript is making the inferences it is, and where expected inferences are failing? Something like this would not only be a huge help for developers, but would probably cut down on a lot of your support requests too, because people could simply look at the graph and pinpoint exactly where they're going wrong.

I imagine you'd just produce and update the data as code is modified, and tools and extensions in editors would do the job of visualising it and making it explorable while coding.

**Comment by andy-ms** [comment]
You could just add type declarations to avoid inference? You could take them away once you'd solved the problem if you prefer inference.

**Comment by axefrog** [comment]
>You could just add type declarations to avoid inference? You could take them away once you'd solved...

Your solution is fine for simple cases. Note that I said:

> complex interplay between various generic types and higher-order generic functions

**Comment by andy-ms** [comment]
Is there a particular case where you're unable to narrow an error down by providing more type annotations?

**Comment by mhegazy** [comment]
The request is rather vague. can you provide more context of the issue you are looking into?

**Comment by axefrog** [comment]
I'm not really interested in solving one specific issue. I'm dealing with complex composition scenarios between higher-order, sometimes-curried functions, with various combinations of typing features such as `keyof`, multiple generics that extend other types and which depend on sibling generics, and which return other functions with generiucs that depend on their higher-order counterparts, then passing those things to other functions with similar constraints, and it reaches a level of complexity that is very difficult to solve manually.

The request is about the fact that I'll see that TypeScript is making an unexpected inference somewhere, and it can be really, really difficult to figure out **why** that inference is being made.

The request boils down to this:

How could the TypeScript compiler expose better information to help developers figure out how TypeScript decided to infer a given type at a given point in the code? I am frequently frustrated with messages telling me it can't assign A to B, but no explanation message follows. Even when a message follows, sometimes it is such a complex description of the types involved, that deciphering the message is half the battle, and even then, developers still arrive at the question of _why_ a given inference was made. If we could see that types A through G were involved in the inference chain behind the currently-observed problem, and that at each step of the way there was a clear indication of what the inference logic was at that point, it'd make it a lot easier to solve our own problems without having to go online to ask for help - something that is often not even feasible given that problems of that sort of complexity are usually rather nuanced, and difficult to reproduce without including large amounts of source code.

**Comment by andy-ms** [comment]
@axefrog What do you think we should print in this situation?
```ts
const a = [0];
const b = a.map(x => x + "1"); // Dev thinks this is a number[] (accidental quotes)
const c = b.map(x => x + 2); // Dev thinks this is a number[]
const d = c.map(Math.abs); // Huh, error? Where'd it go wrong?
```
In this case the type of `d` is wrong because the type of `c` is wrong because the type of `b` is wrong. It don't think we'd want to print all of that out, so we just give you the error at `Math.abs` and assume that the inferred type of `c` is correct.

**Comment by axefrog** [comment]
In the original question, I wrote:

> I imagine you'd just produce and update the data as code is modified, and tools and extensions in editors would do the job of visualising it and making it explorable while coding.

You wouldn't display that yourself. You'd make the data available so that extensions and other tools could provide different ways of examining the data.

> ... It don't think we'd want to print all of that out, so we just give you the error ...

The first step is ALWAYS getting the data right. Make the data available, then let the community decide what to do with it.

**Comment by andy-ms** [comment]
It would be useful to have an API method that gives you the type arguments that were inferred at a callsite, which would help with [no-inferred-empty-object-type](https://palantir.github.io/tslint/rules/no-inferred-empty-object-type/). T

**Comment by axefrog** [comment]
> It would be useful to have an API method that gives you the type arguments that were inferred at a callsite, which would help with no-inferred-empty-object-type.

If that API allowed you to drill back through the type hierarchy to establish a model of "how did we get to this point", that would be *incredibly* useful! :-)

**Comment by RyanCavanaugh** [comment]
A simple log call inserted at the top of `checkExpression` would give you the raw data you could reprocess into a graph. As is, we don't store the data that you would need to get the type dependency graph

**Comment by axefrog** [comment]
> As is, we don't store the data that you would need to get the type dependency graph

What are the downsides of gathering that data to allow for better tooling?

**Comment by mhegazy** [comment]
> The request is about the fact that I'll see that TypeScript is making an unexpected inference somewhere, and it can be really, really difficult to figure out why that inference is being made.

can you share an example so that we are not talking about the abstract? i understand you are interested in a general solution, but it is hard to understand what you are talking about without an example.

> How could the TypeScript compiler expose better information to help developers figure out how TypeScript decided to infer a given type at a given point in the code? I

That is what quick info/hover is for in your IDE.

**Comment by axefrog** [comment]
@mhegazy I feel like I've covered these things already...

> I'm dealing with complex composition scenarios between higher-order, sometimes-curried functions, with various combinations of typing features such as keyof, multiple generics that extend other types and which depend on sibling generics, and which return other functions with generics that depend on their higher-order counterparts, then passing those things to other functions with similar constraints, and it reaches a level of complexity that is very difficult to solve manually.

> to go online to ask for help - something that is often not even feasible given that problems of that sort of complexity are usually rather nuanced, and difficult to reproduce without including large amounts of source code.

So... sure, I can give you an example, but how much of the codebase do you want me to reproduce? If I boil it down to a minimal example, you'll only see a simple example that appears to be easy to solve. If I paste a large amount of code, it'll be unreasonable to expect you to figure out what it's supposed to be doing.

> That is what quick info/hover is for in your IDE.

"quick info/hover" is pretty much the _opposite_ of what I'm suggesting.

Quoting myself:

> Is there any way you could implement something that produces some kind of lazy directed graph data that can be explored to determine why TypeScript is making the inferences it is, and where expected inferences are failing?

> If we could see that types A through G were involved in the inference chain behind the currently-observed problem, and that at each step of the way there was a clear indication of what the inference logic was at that point, it'd make it a lot easier to solve our own problems without having to go online to ask for help

> The first step is ALWAYS getting the data right. Make the data available, then let the community decide what to do with it.

Anyway, it was never my intention to come across as antagonistic, I just feel like everyone who sits in no-man's land between trying to bend the type system to its limits (given that variadic types, higher-kinded types, etc. don't seem to be getting any development traction, or at least are on the backburner pending further compiler groundwork), is kind of at a loss for adequate introspection data to figure out typing issues when complex composition scenarios are in play.

This request is basically useless to people doing simple, run-of-the-mill OO stuff. TypeScript is reasonably easy to wield in those cases, and your error messaging, hints and so forth cover those cases just fine. What is lacking is useful introspection data for anyone doing stuff with more of a functional approach. In those cases, there are deep composition hierarchies in play, and trying to figure out what's being inferred, and where, can be downright painful.

**Comment by axefrog** [comment]
I don't know how useful this is, but here's the current version of a `get` function I'm using. It's one place where I was experiencing a lot of pain.

```ts
import { DataRef, MaybeStream, Metadata, Producer, Resource, isResource } from '@@salix:core';
import { Stream, map, now, startMemoized, switchMap } from '@@salix:streams';
import { isObject, isUndefined } from '@frptools/core';

export type Getter<K extends keyof TMeta, TMeta extends Metadata> = Producer<TMeta[K], GetterMetadata<K, TMeta>>;

export interface GetterMetadata<K extends keyof TMeta, TMeta extends Metadata> extends Metadata<TMeta[K]> {
  '@type': 'sx:Resource/MetadataGetter';
  key: K;
  source: DataRef<TMeta>;
}

const jsonldContext = {
  source: 'sx:Resource/MetadataGetter/source',
  key: 'sx:Resource/MetadataGetter/key',
};

export function get<K extends keyof TMeta, TMeta extends Metadata> (key: K, source: DataRef<TMeta>, context: Resource): Getter<K, TMeta> {
  return context.create<GetterMetadata<K, TMeta>, TMeta[K]>(getter => ({
    '@context': jsonldContext,
    '@type': 'sx:Resource/MetadataGetter',
    'sx:value': startMemoized(emitValue, getter),
    key,
    source,
  }));
}

function emitValue<K extends keyof TMeta, TMeta extends Metadata> (getter: Getter<K, TMeta>): MaybeStream<TMeta[K]> {
  return switchMap<GetterMetadata<K, TMeta>, TMeta[K] | undefined>(emitProperty, getter.snapshot$);
}

function emitProperty<K extends keyof TMeta, TMeta extends Metadata<any, any>> (snapshot: GetterMetadata<K, TMeta>) {
  const { key, source } = snapshot;
  const stream: Stream<TMeta[K] | undefined> = isUndefined(source) ? now(void 0)
    : isResource(source) ? map(maybeProp<K, TMeta>(key), source.snapshot$)
    : isObject(source) ? now(source[key])
    : notImplemented('DataRef -> string (URI only)');
  return stream;
}

function maybeProp<T extends { [key: number]: T[typeof key] }> (key: number): (value: T | undefined) => T[typeof key] | undefined;
function maybeProp<K extends keyof T, T extends { [P in keyof T]: T[P] }> (key: K): (value: T | undefined) => T[K] | undefined;
function maybeProp (key: string | number) {
  return (value: any) => isUndefined(value) ? void 0 : value[key];
}
```

**Comment by RyanCavanaugh** [comment]
> What are the downsides of gathering that data to allow for better tooling?

Many of the objects we're creating here are short-lived. Keeping all the data around would be a large increase in memory pressure and would decrease performance, as well as decrease the maximum amount of code we can analyze in a 32-bit process at once (which is already a primary concern).

That's not to say we *can't* do it, it's just to say, we would need to understand the reasons for doing so and make sure that "providing the data" is the *right way to accomplish that task*.

> If I boil it down to a minimal example, you'll only see a simple example that appears to be easy to solve. If I paste a large amount of code, it'll be unreasonable to expect you to figure out what it's supposed to be doing.

Please don't assume bad faith or an unwillingness to engage. There's no need to self-sabotage the discussion. We work with small examples here all the time and we fully understand what it means for a small example to be representative of a larger codebase.

> The answer is, simply, data. The more data you expose to tool developers, the more the community can solve its own problems.

There are dozens of kinds of data being generated during the typechecking process and an infinite number of ways we could expose that data. Without specifying a *concrete task* (literally here is an input and here is the output I would like to see *or* here is a kind of thing I would like to derive from that data), we don't even know which kind of data you're looking for.

As an absurd example, you can already attach a debugger to the nodejs tsc process and take a heap dump, and now you "have the data", but I don't think that's what you're looking for. Certainly you want something more useful that is structured in a way that makes analysis easier than trawling through bytes in a binary dump. We need to understand what "useful" *would mean*.

**Comment by axefrog** [comment]
> Please don't assume bad faith or an unwillingness to engage.

I apologise, that wasn't my intent. Having just come off a half day of fighting the TypeScript compiler, I wanted to somehow convey a desire for something that could improve this experience for both myself and for others. Several responses prior to yours _appeared_ to be asking me to know what _specific_ problem I was trying to solve, and it felt like those responses missed my point, but I may of course have misinterpreted them.

There are two cases I'm talking about:

1. I'm trying to assign one thing to another, where the generics in both have at least semi-complex sets of constraints and hierarchies. The error message says that I can't make the assignment, but offers no explanation. This is a common experience for me.

2. I'm performing a transformation somewhere (same level of complexity as above), and the compiler is telling me that something is being inferred as one thing when I'm expecting another thing. Because the generics involved include a combination of different libraries, functions, interfaces and modules in general, tracking down the point in the inference chain where a divergence from what I expected occurred, proves to be really difficult. This is also a common occurrence for me.

This cropped up as I was discussing this with a friend whose workplace is currently porting their codebase over to TypeScript, and he'd been expressing a lot of the frustration I've experienced, and his workplace's codebase _also_ uses a lot of higher-order functions, constrained generics, composition and so forth. We were both noting how much time we sometimes spend trying to deal with the type system instead of iterating on the actual implementation.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
