### ISSUE TITLE
Partial<T> assignability error where T extends a compatible type

### ISSUE THREAD

**Issue by Ghabriel** [Microsoft/TypeScript#19388]
**TypeScript Version:**  2.5.3 / playground

**Code**

```ts
interface Vertex {
    name: string;
}

function create<T extends Vertex>(): void {
    let x: Partial<T> = {
        name: "A"
    };
}
```

**Expected behavior:**
The code should compile, since every T will have `name: string` in its definition.

**Actual behavior:**
`error TS2322: Type '{ name: "A"; }' is not assignable to type 'Partial<T>'.`

**Comment by RyanCavanaugh** [comment]
This is a correct error. `create<{ name: "B" }>()` is a legal call that the function body fails to fulfill correctly

**Comment by Ghabriel** [comment]
The same error occurs if I change the `Vertex` definition to:
```typescript
interface Vertex {
    name: "A";
}
```

In which case would the function fail with this definition?

**Comment by Ghabriel** [comment]
Found it: `create<{ name: null }>()`. Thanks, I'll close this issue.
