### ISSUE TITLE
`instanceof Error` typeguard not functioning

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#1938]
Wonder if this is something that should work. I think it should:

```ts
    try {
	     throw new Error('awesome');
    } catch (ex) {
        if (ex instanceof Error) {
     		console.log(ex.foo);  // compiles. Should be error
        }
    }
```

The reason is that `ex` is still of type `any`. I suspect its in the spec that `instanceof` guard will not work on type `any` (I haven't checked).

![image](https://cloud.githubusercontent.com/assets/874898/6055284/1d2c7896-ad50-11e4-84e8-b856de679a9a.png)

Would be great if we could have this though.

**Comment by RyanCavanaugh** [comment]
See #1425. We do not narrow values of type `any`.

The first version of type guards did narrow `any` values, but there was too much code in the wild that did stuff like

```ts
var x: any; // x is a string or an HTML element I know is an image
if(x instanceof HTMLElement) {
  x.width = 100;
}
```

**Comment by basarat** [comment]
@RyanCavanaugh sure its #1425 ?

**Comment by RyanCavanaugh** [comment]
Typo'd and updated, meant #1426
