### ISSUE TITLE
Referenced type variable incorrectly inferred as "{}" in function calls

### ISSUE THREAD

**Issue by Yona-Appletree** [Microsoft/TypeScript#19382]
**TypeScript Version:**  2.6.0-dev.201xxxxx

**Code**

```ts
// Fails:  error TS2339: Property 'a' does not exist on type '{}'.
infer({ thing: { a: 10 } }).a; 

// With explicit type parameters, it works
infer<{a:number}, Holder<{a: number}>>({ thing: { a: 10 } }).a; 

interface Holder<T> {
	thing: T;
}
function infer<T, H extends Holder<T>>(holder: H): T {
	return holder.thing;
}
```

**Expected behavior:**

The type parameter `T` should be inferred to be the type of `thing` in the instance of `Holder` passed to the function `infer()`.

Perhaps there is another way to get this type of inference to work? I'm building a builder-pattern class and really need this to correctly return the right types.

**Actual behavior:**

The type parameter, `T`, is inferred to be `{}` when calling `infer()`

**Comment by andy-ms** [comment]
You don't actually need `H` here.
```ts
function infer<T>(holder: Holder<T>): T {
	return holder.thing;
}
```

**Comment by Yona-Appletree** [comment]
Fair, though in my actual code I do need it. Slightly contrived, but closer to my actual use case:

```ts
const result = infer({ thing: { a: 10 } });
result.holder.thing += result.value.thing;

interface Holder<T> {
	thing: T;
}
function infer<T, H extends Holder<T>>(holder: H): { holder: H, value: T} {
	return { holder, value: holder.thing };
}
```

**Comment by andy-ms** [comment]
How about `function infer<T, H extends Holder<T>>(holder: H & Holder<T>): { holder: H, value: T} {`?

**Comment by Yona-Appletree** [comment]
@andy-ms Yeah, that's perfect, actually. Thanks. It seems to me that it shouldn't be necessary, but this is a great work around.

**Comment by andy-ms** [comment]
@sandersn Could we infer a more specific `T` here?

**Comment by gcanti** [comment]
Another option

```ts
function infer<H extends Holder<any>>(holder: H): { holder: H; value: H['thing'] } {
  return { holder, value: holder.thing }
}
```

**Comment by mhegazy** [comment]
you can define your function as: 
```ts
function infer<T, H extends Holder<T>>(holder: Holder<T> & H): T 
```

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.

**Comment by andy-ms** [comment]
@sandersn Could we infer a more specific `T` in the original example? It seems silly to add `& Holder<T>` when `H` already extends that.

**Comment by mhegazy** [comment]
constraints are not inference positions.. they are merely for checking constraints after an inference has occurred. 

Now, the general question is i want to capture a container type "and" the type it contains.. this is doable through one of two ways.. either, you infer the container type, and you access the element type using indexed access type, e.g.:
```ts
function infer<H extends Holder<any>>(holder: H): H['thing'];
```
or through making two inferences using intersection types, e.g.:

```ts
function infer<T, H extends Holder<T>>(holder: Holder<T> & H): T;
```
