### ISSUE TITLE
FunctionConstructor args array in lib.d.ts should be any[] instead of string[]

### ISSUE THREAD

**Issue by lmcarreiro** [Microsoft/TypeScript#19399]
```ts
interface FunctionConstructor {
    /**
      * Creates a new function.
      * @param args A list of arguments the function accepts.
      */
    new (...args: string[]): Function;
    (...args: string[]): Function;
    prototype: Function;
    name: string; // added
}
```

**Comment by andy-ms** [comment]
According to [mdn](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function) they must all be strings -- either a parameter name or the function text.

**Comment by kitsonk** [comment]
While the spec indicates that all the arguments are [coerced to string](https://tc39.github.io/ecma262/#sec-createdynamicfunction) it is that sort of implicit coercion that TypeScript attempts to avoid via the type system.

**Comment by DanielRosenwasser** [comment]
The most common use-case is `string`, so is there a use-case you have in mind that the current signature doesn't cover?

**Comment by lmcarreiro** [comment]
Sorry, I thought it was something else.
