### ISSUE TITLE
BUG: Goto Definiton (F12) "Object reference not set" when in another project

### ISSUE THREAD

**Issue by olmobrutall** [Microsoft/TypeScript#19391]
**TypeScript Version:**  2.5/2.6.0
**VisualStudio 15.4.1**

**Code**
```ts
import * as Navigator from "../../Framework/Signum.React/Scripts/Navigator"
```
Since the installation of VS 15.4.1 using Go To Definition in almost any reference (ES6 modules) throws a Object referencen ot set to an instance of an object. 

![image](https://user-images.githubusercontent.com/720953/31843444-3e21285e-b5f3-11e7-9147-362d6693a6fd.png)

I have not been able to reproduce the error in a small project, so here is the complete one: 

https://github.com/signumsoftware/southwind

and this is the tscondig.json:

```JSON
{
  "compilerOptions": {
    "target": "es5",
    "sourceMap": false,
    "module": "esnext",
    "moduleResolution": "node",
    "jsx": "react",
    "noEmit": true,
    "strict": true,
    "baseUrl": ".",
    "lib": [
      "es2017",
      "esnext",
      "dom"
    ]
  },
  "exclude": [ "node_modules" ]
}
```

**Comment by mhegazy** [comment]
I can not seem to reproduce this locally.. do you see this on all machines?

**Comment by olmobrutall** [comment]
True, clean clone from github solved the problem. 

Maybe some file in node_modules was making the problem.

Thanks for the quick answer!
