### ISSUE TITLE
Cannot invoke an expression whose type lacks a call signature when using a union of two types with compatible interfaces

### ISSUE THREAD

**Issue by foxbunny** [Microsoft/TypeScript#19409]
I have two types with compatible interfaces, of which one is generic (making both generic produces the same results, but at least one needs to be generic). The two types are then used to create a union type. A factory function is used to construct an object of either type depending on a condition.

**TypeScript Version:**  2.5.3

**Code**

```ts
type Foo<T = any> = Bar<T> | Baz;

type Bar<T> = {
    meth(x: T): number
}

type Baz = {
    meth(): number
}


const createBar = <T>(x): Bar<T> => ({
    meth(y) {
        return x + y;
    }
});


const createBaz = (): Baz => ({
    meth() {
        return 0;
    }
});

const createFoo = <T = any>(x): Foo<T> =>
    x >= 0
        ? createBar<T>(x)
        : createBaz();


const foo = createFoo<number>(12);

foo.meth<number>(-12);
```

**Expected behavior:**

The method call should be valid.

**Actual behavior:**

The compiler complains that it 'Cannot invoke an expression whose type lacks a call signature. Type '(() => number) | ((x: number) => number)' has no compatible call signatures.'. The method call only works if all type parameters are stripped out.

**Comment by pelotom** [comment]
It doesn't seem like generics have anything to do with it. You can get the same error with just

```ts
declare const foo: ((x: number) => number) | (() => number);

foo(-12);
```

**Comment by pelotom** [comment]
And the error seems valid, given that `() => number` is not a valid signature to pass an argument to:

```ts
declare const foo: () => number;

foo(-12);
^^^^^^^^ Expected 0 arguments, but got 1.
```

**Comment by RyanCavanaugh** [comment]
See #7294

**Comment by foxbunny** [comment]
@RyanCavanaugh Thanks for the link

@pelotom It won't work even if you add an argument to the second function.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
