### ISSUE TITLE
No TS 2.6 errors found in editor. 

### ISSUE THREAD

**Issue by olmobrutall** [Microsoft/TypeScript#19406]
**TypeScript Version:**  2.6.0-RC VS2017

After installing TS 2.6 RC for Visual Studio 2017 from [here](http://download.microsoft.com/download/7/0/A/70A6AC0E-8934-4396-A43E-445059F430EA/2.6.0-TS-release-dev14update3-20171007.2/TypeScript_SDK.exe) as recommended in the [blog](https://blogs.msdn.microsoft.com/typescript/2017/10/12/announcing-typescript-2-6-rc/), I can see new errors in the error panel. I'm using `--strict`. 

When I double-click in the error, however, no red marked in the editor is shown. What's worst, since most of the errors require some recursive explanation because they are produced by the contravariance changes, and in the error list you only get the first X characters, its quite hard to solve the problem. 

![image](https://user-images.githubusercontent.com/720953/31865145-f9fc32fe-b769-11e7-9f87-eaf77ccf184f.png)

The same happens in VS Code. Note that another 'normal' error, like `const a: string = 4;`, was correctly marked. 

![image](https://user-images.githubusercontent.com/720953/31865236-cc3ea3d6-b76b-11e7-8c7e-df0c85f42584.png)

**Comment by mhegazy** [comment]
The errors are from your build output, hence the "Build" prefix before errors. seems like your language service is either 1. not use the same version as your build, or 2. is using different configurations, e.g. no `--strict`. 

Can you share a sample project?

**Comment by olmobrutall** [comment]
Problem solved: 
![image](https://user-images.githubusercontent.com/720953/31874036-50123b68-b7c7-11e7-82c9-d301004f28e1.png)

I had the Regedit hack since a long time ago and I forgot it. 
![image](https://user-images.githubusercontent.com/720953/31874045-5e40e84c-b7c7-11e7-91e2-fddb2b8c6f40.png)

Sorry!

**Comment by mhegazy** [comment]
glad we got to the bottom of it.
