### ISSUE TITLE
Decorated type checked differently based on where they are used

### ISSUE THREAD

**Issue by pdeva** [Microsoft/TypeScript#19407]
This is related to [react-redux types give errors when used as decorators](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/20796#issuecomment-338497687)

**TypeScript Version:**  2.5.3

**Code**

```ts
import * as React from "react";
import {connect} from "react-redux";

interface IStore {
	myVar: any;
}

interface MyComponentProps {
	dispatch?: any;
	a;
}

function mapStateToProps(state: IStore) {
	return {
		a: state.myVar
	};
}

@connect(mapStateToProps)
export class MyComponent extends React.Component<any, any>
{
	constructor(props, context)
	{
		super(props, context);
	}

	render()
	{
		return (<div>
			<h2>Hello</h2>
		</div>);
	}
}
```

**Expected behavior:**
Should compile properly

**Actual behavior:**

Results in error:

```
MyComponent.tsx(19,1): error TS1238: Unable to resolve signature of class decorator when called as an expression.
  Type 'ComponentClass<Pick<any, never>> & { WrappedComponent: ComponentType<any>; }' is not assignable to type 'typeof MyComponent'.
    Type 'Component<Pick<any, never>, ComponentState>' is not assignable to type 'MyComponent'.
      Types of property 'render' are incompatible.
        Type '() => false | Element' is not assignable to type '() => Element'.
          Type 'false | Element' is not assignable to type 'Element'.
            Type 'false' is not assignable to type 'Element'.
```

However, when used like this, TypeScript compiles it fine:

```ts
export const x = connect(mapStateToProps)(MyComponent);
```

Why is type-checking different in both cases, when it should be the same?

**Comment by pelotom** [comment]
See #4881. TypeScript decorators are severely limited at the moment; a function can't be used as a decorator if it changes the type of the thing it's decorating.

**Comment by mhegazy** [comment]
A decorator can change the type as long as it is assignable to the original declaration. 
In this case `render` return type is inferred to be `Element` and not `false | Element`. The root cause of this issue really is https://github.com/Microsoft/TypeScript/issues/1373. The usual expectation is that `render` will inherit the return type of its base class, and not override it, but that is not the case(https://github.com/Microsoft/TypeScript/issues/1373 has more details).

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
