### ISSUE TITLE
Type alias as mapping key

### ISSUE THREAD

**Issue by Yamakaky** [Microsoft/TypeScript#19404]
**TypeScript Version:**  2.7.0-dev.20171021

**Code**

```ts
type Id = number

interface Mapping {
    [key: Id]: string,
}
```

**Expected behavior:**

Compiles correctly as `Id` is a `number`

**Actual behavior:**

`error TS1023: An index signature parameter type must be 'string' or 'number'.`

**Comment by jcalz** [comment]
Duplicate of #7374

**Comment by Yamakaky** [comment]
Oops, sorry
