### ISSUE TITLE
cannot read property 'delete' of undefined

### ISSUE THREAD

**Issue by ziqiDev** [Microsoft/TypeScript#19402]
**TypeScript Version:**  2.6.0-dev.201xxxxx

**Code**
import * as React from "react";
import $ = require("jquery");

export class Hello extends React.Component<{}, {}> {
public delete() {
    console.log("delete");
    $.ajax({
        type: "DELETE",
        url: "http://127.0.0.1:8080/delete",
        xhrFields: {withCredentials: true}
    }).done((data: any): void => {
        console.log("delete data:" + data);
    }).fail((jqXHR: any): void => {
        console.log("delete faildata: " + jqXHR.status);
    });
}

public save() {
    console.log("save");
    $.ajax({
        type: "POST",
        url: "http://127.0.0.1:8080/save",
        dataType: "text",
        crossDomain: true,
        xhrFields: {withCredentials: true}
    }).done((data: any): void => {
        console.log("data:" + data);
        {this.delete()}
    }).fail((jqXHR: any): void => {
        console.log(jqXHR);
        console.log("faildata: " + jqXHR.status);
    });
}
render() {
    return (
        <div>
            <button onClick={this.delete}>delete</button>
            <button onClick={this.save}>save</button>
        </div>
    );
}
}
```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**Expected behavior:**
it can call delete
**Actual behavior:**
Hello.tsx:36 Uncaught TypeError: Cannot read property 'delete' of undefined

**Comment by DanielRosenwasser** [comment]
The problem is likely that you're using `save` as a callback, but its `this` reference gets orphaned. That means when `save` gets run and it tries to call `delete` on `this`, it can't because `this` isn't defined.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
