### ISSUE TITLE
Add AbortController typings

### ISSUE THREAD

**Issue by coldhamix** [Microsoft/TypeScript#19418]
Abortable fetch is landed whatwg/fetch/pull/523, so AbortController, AbortSignal and fetch property in RequestInit should be added to the typescript library

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.
