### ISSUE TITLE
window.getMatchedCSSRules will be removed in chrome 63

### ISSUE THREAD

**Issue by HolgerJeromin** [microsoft/TypeScript#19414]
The webkit/blink only function will be removed in [chrome 63](https://developers.google.com/web/updates/2017/10/chrome-63-deprecations#remove_getmatchedcssrules) and probably in [webkit](https://bugs.webkit.org/show_bug.cgi?id=79653) in the future.

We could/should remove it in our types as well https://github.com/Microsoft/TypeScript/blob/ceba50750b7bd6c8cfc21a5886e6eb9de7f82a36/src/lib/dom.generated.d.ts#L13252

**Comment by mhegazy** [comment]
We normally do not remove things from the library that fast. so marking this as revisit.

**Comment by HolgerJeromin** [comment]
Fixed in the meantime...
