### ISSUE TITLE
Importing types with checked JS

### ISSUE THREAD

**Issue by azz** [Microsoft/TypeScript#19411]
**TypeScript Version:**  2.5.3

**Code**

In TypeScript, it is trivial to import a type from a package:

```ts
import { MyType } from "types-package";

function foo(bar: MyType) {}
```

However, with checked JS, as far as I can tell there's no way to achieve this. The following loosely demonstrates what I'm after.

```js
/**
 * @typedef {import { MyType } from "types-package"} {MyType}
 * @param {MyType} bar
 */
function foo(bar) {}
```

Note that:

1. `types-package` is a `.d.ts` only package, no runtime code.
2. The specific use case I am working with is a module that implements an interface on the exported functions. Consider a [VSCode extension](https://code.visualstudio.com/docs/extensions/example-hello-world#_generated-code), which exports an `activate` function, it is currently not possible to type the `context` parameter to that function if the extension is written in JS.

**Comment by azz** [comment]
I've found a workaround. If your types package has an `index.js` with the contents:

```js
module.exports = {};
```

Then you can import the types as usual and it works...

**Comment by mhegazy** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/14377

**Comment by azz** [comment]
Ah, thanks. Happy to close as a duplicate.

**Comment by azz** [comment]
The solution mentioned here would be perfect: https://github.com/Microsoft/TypeScript/issues/14377#issuecomment-332792964
