### ISSUE TITLE
Angular ngc compiler regression in typescript 2.6

### ISSUE THREAD

**Issue by sebek64** [Microsoft/TypeScript#19420]
**TypeScript Version:**  2.6.0-rc, 2.7.0-dev.20171021

I'm not sure if this problem is in Typescript or Angular. There is a regression introduced by https://github.com/Microsoft/TypeScript/pull/16364, which causes angular ngc compiler not to compile ngfactory files for external libraries located in node_modules (for example, ngx-bootstrap in my case). Ngc generates imports in this fashion in the typescript file:

```ts
import * as i2 from '../node_modules/ngx-bootstrap/alert/alert.component.ngfactory';
```

It is compiled into javascript as is, but alert.component.ngfactory is skipped in the compilation. Replacing the following part of node_modules/typescript/lib/typescript.js

```ts
isExternalLibraryImport: contains(parts, "node_modules")
```

with false fixes the problem for me.

I'll report this issue to Angular project if you decide that Typescript is correct here.

**Comment by alexeagle** [comment]
@tbosch is this a known issue? Looks like we rely on this typescript API when we determine which files are inside/outside the program and it's broken by 2.6.

**Comment by tbosch** [comment]
Right now, `ngc` only works with TS 2.4, we will extend our test coverage to TS 2.5 / TS 2.6 soon.

This is an issue with `ngc`, not with typescript itself.

**Comment by tbosch** [comment]
Actually, this is not a bug but a feature. You can produce all factories if you set your `rootDir` to contain the `node_modules`. I.e. `ngc` will only generate factories for files under `rootDir`.

**Comment by mhegazy** [comment]
thanks @tbosch!

**Comment by HuangHongRui** [comment]
Thanks~

**Comment by sebek64** [comment]
@tbosch Thank you for a hint, but the issue is different, maybe my original explanation was not clear enough. I'll try again.

The option rootDir affects for which directories ngc generates factories, but (I guess) not which factories (ts files) are compiled into javascript. All directories named node_modules are skipped. Thus, factories for external libraries are generated in the aot directory, but the files are subsequently not compiled into javascript.

I can demonstrate the problem completely without angular, just with plain tsc. I create a custom source directory structure, and create a directory somewhere inside named node_modules (not a good idea, but still should be valid). This directory is automatically skipped by tsc. The culprit is the code cited in the original post, i.e.,

```ts
isExternalLibraryImport: contains(parts, "node_modules")
```

When I replace it with "false", I get correct results. This line was changed between 2.5 and 2.6 by https://github.com/Microsoft/TypeScript/pull/16364.

**Comment by tbosch** [comment]
Ok, could you file separate issue then if this is unrelated to angular?

**Comment by sebek64** [comment]
@tbosch Well, I investigated the issue a bit further and I'm not sure it is is completely unrelated to angular. In fact, my observation from the previous post was a bit incorrect.

At first, the behavior for plain tsc changed between 2.4 and 2.5, not 2.5 and 2.6 as I thought. Whenever a directory named node_modules is found in the sources path, is is unconditionally skipped by 2.5, but not by 2.4. I'm not sure what was the original motivation for this change or  whether it is correct or wrong, but it is not something that affects my use-case.

The other problem is with angular ngc compiler. I know that it officially supports just 2.4, but it works fine here with 2.5. However, it does not work with 2.6 due to the change in src/compiler/moduleNameResolver.ts here https://github.com/Microsoft/TypeScript/pull/16364/commits/62cae8afc9ef902c4c72071808b651eceb64caea. When I manually revert the change of isExternalLibraryImport to false, angular ngc compiler works again for ngfactories generated in aot/node_modules. Maybe this change in Typescript is correct and angular should fix its call of TS compiler API. I don't understand the internals so well. If so, I'll report the bug to angular. But at the moment, it looks like Typescript is just breaking compatibility.

**Comment by sebek64** [comment]
@tbosch Ok, more clarification from me. This only affects angular 4.* and not the upcoming version 5, so maybe it is not as big issue as it seemed to me originally. New angular doesn't generate ngfactory typescript files at all on the filesystem, just compiled version of the factories. So I guess this bug might be closed. Sorry for the noise.
