### ISSUE TITLE
Feature Request: Infer types when using variable assignment with if-statements.

### ISSUE THREAD

**Issue by ccorcos** [Microsoft/TypeScript#19421]
**TypeScript Version:**  2.6.0-dev.201xxxxx

**Code**

```ts
function f(x: string | undefined) {
	if (x) {
		const l = x.length
	}
	const y = !!x
	if (y) {
                // type error with strictNullChecks on.
		const l = x.length
	}
	if (!!x) {
		const l = x.length
	}
}

```

**Expected behavior:**

I would expect this code to compile without errors by simply refactoring some conditions into variables.

**Actual behavior:**

Unless the entire condition lives inside the if statement, there will be a type error.

**Comment by ahejlsberg** [comment]
This is a design limitation. The control flow analyzer doesn't track what effects a particular value for one variable implies for *other* variables. See #12184 for a similar example.
