### ISSUE TITLE
Task List tokens are not honored

### ISSUE THREAD

**Issue by NN---** [Microsoft/TypeScript#1942]
Works well in C#, C++ and other languages but not in TypeScript VS integration:

```
// TODO: ABC
// HACK: CDE
```

Open Task List -> Comments, you see nothing.

**Comment by mhegazy** [comment]
Which version of VS are you using? VS 2013 or VS 2015? We have added this feature in VS 2015.

**Comment by NN---** [comment]
2013. Can you add it there?
I think it takes time until 2015 will be released.

**Comment by danquirk** [comment]
The 2015 language service is quite different, so unfortunately we won't be doing the work to go back and add this to VS2013.

**Comment by jbondc** [comment]
This is unfortunate :( Also still on VS 2013.

**Comment by Psvensso** [comment]
And removed again in VS2017.

**Comment by jimbarrett33** [comment]
This is closed but I can't figure out what this means for VS 2017 because Task List comments don't work for me in VS 2017. Are they supposed to work in VS 2017 like they did in VS 2015?

Is this a TypeScript language issue or VS 2017 issue?

Thanks.
