### ISSUE TITLE
strict function argument types

### ISSUE THREAD

**Issue by ccorcos** [Microsoft/TypeScript#19432]
**TypeScript Version:**  2.5.3

**Code**

```ts
interface X {
	x: number
}

interface Y {
	x: number
	y: number
}


function f(x: Y) { }

const g : (x: X) => void = f
```

**Expected behavior:**

I would expect `g` to have an error because f can get called without the necessary `y` property...

**Actual behavior:**

...but there isnt.

**Comment by ahejlsberg** [comment]
See #18654.

**Comment by ccorcos** [comment]
awesome! thanks. is this coming out with 2.6 or 2.7?

**Comment by ahejlsberg** [comment]
It's in the 2.6 release.

https://blogs.msdn.microsoft.com/typescript/2017/10/12/announcing-typescript-2-6-rc/
