### ISSUE TITLE
 An enum member cannot have a numeric name

### ISSUE THREAD

**Issue by JohannesBusch** [Microsoft/TypeScript#19438]
**TypeScript Version:**  2.5.3

**Code**
`export enum State {
  '01',
  '02',
  '02A',
  '03',
  '03A',
  '04',
  '05',
  '99',
}`

**Expected behavior:**
The Enum should compile without errors

**Actual behavior:**
An Error is thrown: ' An enum member cannot have a numeric name.'

If you change `'99'` to `'099'` the error goes away.

**Comment by RyanCavanaugh** [comment]
This is to prevent collisions in the reverse map. Note that quoted names and unquoted names behave the same in terms of object keys.
