### ISSUE TITLE
Add a d.ts for a React js component and compile successfully but the component run as undefined 

### ISSUE THREAD

**Issue by huangsav** [Microsoft/TypeScript#19443]
Could anyone help me to have a look? Here is my d.ts. Many thanks.
```ts
/// <reference types="react" />

declare namespace __ReactAvatarEditor{

    interface croppingRect {
        x: number,
        y: number,
        width: number,
        height: number
    }

    interface point {
        x: number,
        y: number
    }
    
    export interface AvatarEditorProps {
        scale?: number,
        rotate?: number,
        image?: any,
        border?: number | [number],
        borderRadius?: number,
        width?: number,
        height?: number,
        position?: point,
        color?: number[],
        style?: object,
        crossOrigin?: string,
        onDropFile?: any,
        onLoadFailure?: any,
        onLoadSuccess?: any,
        onImageReady?: any,
        onImageChange?: any,
        onMouseUp?: any,
        onMouseMove?: any,
        onPositionChange?: any,
        disableDrop?: boolean
    }
    export class AvatarEditor extends React.Component<AvatarEditorProps> {
    }
}

declare module "react-avatar-editor"{
    export import AvatarEditorProps = __ReactAvatarEditor.AvatarEditorProps;
    export import AvatarEditor = __ReactAvatarEditor.AvatarEditor;
}

declare module "react-avatar-editor/AvaterEditor"{
    export import AvatarEditor = __ReactAvatarEditor.AvatarEditor;
    export default AvatarEditor;
}
```

And use by this way:
![default](https://user-images.githubusercontent.com/15684776/31956335-afd0a63c-b91d-11e7-8104-a4e70075659d.png)

And here is the error:
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.

Check the render method of `DealPicModal`.

**Comment by mhegazy** [comment]
You might have better luck sharing this on StackOverflow. This is not a support forum, it is one for reporting compiler/language bugs and suggestions. 
If you believe you are running into a compiler bug, please share a minimal repro project that demonstrates the issue you are running into and why you believe this is a compiler bug and not a declaration file issue or library usage problem.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
