### ISSUE TITLE
lib.d.ts Make Object.keys generic

### ISSUE THREAD

**Issue by mohsen1** [Microsoft/TypeScript#19448]
**TypeScript Version:**  2.5

Currently `Object.keys` type is `keys<T>(o: {}): string[];` but instead it can be `keys<T = {}>(o: T): keyof T;` so  return type is a union of keys. 

Any reason this hasn't been done before? I can make a PR if this is an acceptable change

**Comment by mhegazy** [comment]
Please see https://github.com/Microsoft/TypeScript/issues/15627

**Comment by mohsen1** [comment]
This comment 
https://github.com/Microsoft/TypeScript/pull/12253#issuecomment-263132208

But I'm not convinced. We either have strong typing or not. if someone is depending on runtime data without statically declaring them it is their problem and can case the types to a wide type

/cc @ahejlsberg 

Closing as it is by design

**Comment by kitsonk** [comment]
> If someone is depending on runtime data without statically declaring them it is their problem.

At the moment, TypeScript does not differentiate between own keys and enumerable keys, both which are not covered by `Object.keys()`.  So there is a lot of ways, intentionally or unintentionally `Object.keys()` typed as suggested would give back _bad_ information.

For example, it breaksdown badly here:

```js
const foo = Object.create({ foo: 'string' });
Object.defineProperty(foo, 'bar', {
  value: 1
});

console.log(Object.keys(foo)); // []
console.log(foo.foo); // 'string'
console.log(foo.bar); // 1
```

Sounds like a bad 👣 🔫  to me...
