### ISSUE TITLE
JSDoc rest is incorrectly handled

### ISSUE THREAD

**Issue by mihailik** [Microsoft/TypeScript#19444]
**TypeScript Version:**  2.7.0-dev.20171024

**Code**

```ts
/** @param {...number} a */
function f(a) {
    console.log(arguments[0]);
}
f([1, 2]); // this should fail, but passes [[1]]
f(1, 2); // this should pass, but fails [[2]]
```

`node ./node_modules/typescript/lib/tsc.js multi.js --out multiout.js --allowjs --checkjs`

**Expected behavior:**

Fail at [[1]] pass at [[2]]

**Actual behavior:**

Passes [[1]], but fails at [[2]]:

`multi.js(6,3): error TS2345: Argument of type '1' is not assignable to parameter of type 'number[]'.`

Regression introduced at #18825

**Comment by mhegazy** [comment]
Given the example above, and looking at the [JSDoc documentation for @param](http://usejsdoc.org/tags-param.html#multiple-types-and-repeatable-parameters), seems that the correct behavior is that 
- `a` is of type `number`
- `f` has call signature: `f(...args: number[])`
