### ISSUE TITLE
Typescript suggesting snippets in imports

### ISSUE THREAD

**Issue by victorgarciaesgi** [Microsoft/TypeScript#19440]
How to disable Typescript snippets on Imports?

![image](https://user-images.githubusercontent.com/15092120/31940865-034407c2-b8c0-11e7-8982-bc8086091346.png)

**Comment by DanielRosenwasser** [comment]
This isn't a TypeScript problem, please don't use this issue tracker for questions.

To answer the question, it's `"editor.snippetSuggestions": "none"` in VS Code's editor settings

**Comment by DanielRosenwasser** [comment]
Misread the original question, please disregard the original answer.

I think this is probably an issue you want to file on VS Code, though I don't think there's a fine-grained way to disable this yet. @mjbvz

**Comment by victorgarciaesgi** [comment]
Ok I will forward this to Vs Code, thanks

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
