### ISSUE TITLE
Discussion about typeof navigation

### ISSUE THREAD

**Issue by Alphapage** [Microsoft/TypeScript#19441]
**TypeScript Version:**  2.5.3

**Code**

```ts
class C {
    constructor(s:string){}
    test(){}
}

const o={C:C}

let c:typeof o.C.prototype

let c2:C=new C('');

let c3:(typeof o).C;
```

**Expected behavior:**
`(typeof o).C` in `c3` produces an error.
For now, typeof can navigate to variable and properties only, not types.
It would be great to be able to continue navigate types after a variable casting. So, `(typeof o).C` and `typeof o.C.prototype` will produce the same type result.
I prefer `(typeof o).C` of course.
**Actual behavior:**
`let c3:(typeof o).C;` hates parenthesis

**Comment by ahejlsberg** [comment]
This is already possible:

```ts
let c3:(typeof o)["C"]["prototype"];
```

See #11929 for more details.

**Comment by Alphapage** [comment]
You learn me something, but that doesn't change the navigation: you need to relay on variable navigation.
What I am trying to achieve is to switch from `(typeof o)` variable/property navigation to type navigation, so  `let c:C` is the same as `let c:(typeof o).C` (this is what I call **_type navigation_**).

**Comment by ahejlsberg** [comment]
I'm afraid I don't understand what you're asking for. If `T` is a type, what exactly are the semantics you expect for a type `T.X`?

**Comment by DanielRosenwasser** [comment]
Additionally, if you want `(typeof o).C` to be equivalent to `(typeof o)["C"]`, that's not possible given the way the language currently uses `.` for looking up a type within a namespace.

**Comment by Alphapage** [comment]
Yes, I think it could only work for object properties type or module properties type.
@ahejlsberg if `T` is `typeof o`, then `T.C` is `C`, not `typeof o.C` (I'm sorry for the very bad explaination).
As soon as you ask `typeof o`, you enter in a type navigation, so `(typeof o).C` is the same type as `C`.
@DanielRosenwasser I understand the way the language is navigating to lookup a type, but I think this could be an advanced feature to think about.

**Comment by Alphapage** [comment]
Maybe this feature is confusing for users, so I close the request.
