### ISSUE TITLE
Without `--strictNullChecks`, accessing an array of string literal type returns empty string

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#19451]
**TypeScript Version:** 2.7.0-dev.20171024

**Code**

```ts
function first(x: Array<"a">): "a" {
    return x && x[0];
}
```

Test with `--strictNullChecks` off.

**Expected behavior:**

No error.

**Actual behavior:**

```
src/a.ts(2,5): error TS2322: Type '"" | "a"' is not assignable to type '"a"'.
  Type '""' is not assignable to type '"a"'.
```

**Comment by nealeu** [comment]
This appears to be something to do with use of &&.

With Typescript 2.8.3, I get 
```
TS2322: Type 'number | "" | null' is not assignable to type 'number | null'.
  Type '""' is not assignable to type 'number | null'.
```
when trying to compile:
```
function parseDate(optionalDate: string | null): number | null {
    return optionalDate && Date.parse(optionalDate);
} 
```

**Comment by mhegazy** [comment]
`--strictNullChecks` enables stricter behavior for logical operators. something we could not do in the non-`strictNullChecks` mode to avoid breaking changes to existing code.

**Comment by nealeu** [comment]
@mhegazy I've found this comment in the 2.0 release notes: 

> The && operator adds null and/or undefined to the type of the right operand depending on which are present in the type of the left operand, and the || operator removes both null and undefined from the type of the left operand in the resulting union type.

According to the example given, my code should not produce an error:

```
// Compiled with --strictNullChecks
interface Entity {
    name: string;
}
let x: Entity | null;
let s = x && x.name;  // s is of type string | null
let y = x || { name: "test" };  // y is of type Entity
```

**Comment by mhegazy** [comment]
@nealeu your issue is a diffrent issue from the OP.

your function:

```ts
function parseDate(optionalDate: string | null): number | null {
    return optionalDate && Date.parse(optionalDate);
} 
```

Shows a correct error. let me explain:

the first check is that `optionalDate` is truthy, if it is then you will return `number | null`. if it is not then you will return `optionalDate`.  A truthy check in JS considers an empty string to be `false`. so calling this function with  `parseDate("")` actually returns `""` and not `number | null`. and that is the error message..

I believe you wanted to implement it as:

```ts
function parseDate(optionalDate: string | null): number | null {
    return optionalDate?  Date.parse(optionalDate) : null;
} 
```

**Comment by nealeu** [comment]
@mhegazy Thanks for your generosity in fully explaining that.  It now makes perfect sense in that OMG! way that is Javascript.  This is why I tolerated JS and *love* TS!
