### ISSUE TITLE
Type alias = {} question

### ISSUE THREAD

**Issue by jbondc** [Microsoft/TypeScript#1945]
```javascript
type Json = {}

interface Data extends Json {
    foo: string
}
```
If a type is an alias for {}, should an interface be allowed to extend it?

**Comment by RyanCavanaugh** [comment]
No. Interfaces may only extend *named object types*. They can't extend *primitives* or *anonymous object types*.

In this case, `type Json = {}` should have been written as `interface Json { }` if the ability to extend from it was desired. It's rarely correct to use a type alias to define an alias for an object type.

See https://github.com/Microsoft/TypeScript/pull/957#issuecomment-60686871 (mostly that comment, but also ones above it) for an extended discussion of how `type Json = {}` was originally going to be disallowed for exactly this reason.

**Comment by jbondc** [comment]
Thanks, I'll read more of the discussion. As feedback, not intuitively grasping the difference with:
```javascript
interface JsonBase {}
type Json = JsonBase;
interface Data extends Json {
}

type Json2 = {};
interface Data2 extends Json2 {
}
```

**Comment by danquirk** [comment]
The latest copy of the language spec has some explanation of the difference between interfaces and type aliases:

3.9
Interface types have many similarities to type aliases for object type literals, but since interface types offer more capabilities they are generally preferred to type aliases. For example, the interface type
```ts
interface Point {
    x: number;
    y: number;
}
```
could be written as the type alias
```ts
type Point = {
    x: number;
    y: number;
};
```
However, doing so means the following capabilities are lost:
•	An interface can be named in an extends or implements clause, but a type alias for an object type literal cannot.
•	An interface can have multiple merged declarations, but a type alias for an object type literal cannot.
•	An interface can have type parameters, but a type alias for an object type literal cannot.

**Comment by jbondc** [comment]
That helps. Some part of me is still struggling partly for two reasons:
```javascript
type Item = {
     name: string;
     description: string;
}
interface ItemApi {
   items: Item[]
   addItem(Item)
}
type ItemApi2 = {
  items: Item[]
  addItem(Item) // why is this allowed?
}
```
1) Some part of me really wants a type alias to only describe simple/primitive and complex types, no methods. It only describes data, would distinguish it better from an interface.

2) Looking for a way to compose types from other types but not in a child/parent relationship.
http://haxe.org/manual/type-system-extensions.html

This one is harder :/ A more general story to composing things from other things (traits, mixins, etc...)

**Comment by jbondc** [comment]
Ahh and finally for (1):
```javascript
interface NameLookup = Dictionary<string, Person>;
interface Callback = (data: string) => void;
interface s = typeof SomeClass;
```
So you have an 'interface alias' for the structured types that have methods. Not sure how complex this is but seems more intuitive to me anyways.

**Comment by jbondc** [comment]
Have a patch here that shows how 'interface = ' could also be an alias:
https://github.com/jbondc/TypeScript/compare/type-alias

A bit more work involved in the checker & binder but doesn't seem so bad. Since parseTypeReference() is supported in both cases, we'd need to track if references contain 'methods' and not allow type alias to reference those.

e.g.
class Foo {}
interface Api = Foo; // allowed
type Bar = Foo; // not allowed

**Comment by jbondc** [comment]
So scratch some of those ideas. 
1) Keep type= alias as is but disallow { body }
2) Add interface= alias to express  {} or   { body }
```javascript
interface RefPoint = {
    x: number;
    y: number;
};

interface Point extends RefPoint {}
```

**Comment by danquirk** [comment]
I believe the re-opening of type definitions was one of the primary reasons to not re-use interface as is. It seems a bit subtle to say ```interface Foo {}``` means a type that can be re-opened but ```interface Foo = {}``` means it cannot be reopened. Then you also need to know that ```interface=``` is necessary for aliasing union types but not other things. Obviously the distinction between ```interface {}``` and ```type=``` isn't necessarily significantly clearer from an intuitive perspective, but the use of different keywords does clearly suggest different semantics in a way that relatively minor syntax changes do not. 

re: ItemApi2, it does look a little awkward but remember that the ```addItem``` syntax there is just sugar:

```ts
type ItemApi2 = {
    items: Item[];
    addItem: () => void;
}
```
and that doesn't look so strange.

One use case to remember is people often want to alias function types, but these are ultimately types with bodies. That is, this
```ts
type Callback = (data: string) => void;
```
seems nice to have (even more so if/when aliases allow generic parameters). People already used interfaces for this purpose (ex underscore/lodash.d.ts), but that necessarily allows your alias to be re-opened to include other members. In reality the type alias means:
```ts
type Callback = { (data: string): void; }
```
So if you don't allow types with bodies on the RHS then you can't alias function types. 

We definitely went back and forth on the whole thing for awhile, considering whether/if to re-use ```interface``` in some fashion (with or without = or something) or if a new keyword was necessary for clarity.

**Comment by jbondc** [comment]
Thanks for the comments, I updated the patch if you want to have to have a look.

```javascript
type a = {}
type b = { notallowed: boolean } //  Use 'interface b = {}' instead of 'type b = {}' to alias a structured

class Foo { }
module Bar {
	export class Foo {
		test(): string
	}
}

var e = new Foo;
interface c = {allowed: boolean}
interface d = {}
interface e = string // 'interface e =' can only reference a structured type.
interface f = typeof e; // ok
interface g = Bar.Foo;  // ok

class extendsG implements g {
	hello() {
		return "hello"
	}
	test() { return "test2" }
}
```
I'm not sure if this is better but I like the distinction between type vs. interface. What's interesting about it is 'extendsG' can actually implement any interface alias (pointing to class or interface).

**Comment by jbondc** [comment]
Couple of other notes, structures type are still allowed in unions:
```javascript
type b = a | { notallowed: boolean };
```
And technically you can still write:
```javascript
type z = Bar.Foo;

class extendsFoo implements z {
    hello() {
        return "hello"
    }
    test() { return "test2" }
}
```
But that could be disallowed in favor of the interface alias.

**Comment by mhegazy** [comment]
looks like there is no actions/information required from this issue at this point. closing.
