### ISSUE TITLE
Type inference should take advice from interfaces

### ISSUE THREAD

**Issue by ViKomprenas** [Microsoft/TypeScript#19454]
Bug? Suggestion? Oh well.

**TypeScript Version:**  2.7.0-dev.20171024

**Code**

```ts
interface OneOrTwo {
    ex: 1 | 2;
}

class Example implements OneOrTwo {
    ex = 1;
}
```

**Expected behavior:** The type of `Example#ex` is inferred to `1 | 2` and the example compiles.

**Actual behavior:** The type of `Example#ex` is inferred to `number`, which is not a subtype of `1 | 2`, so the example does not compile.

**Suggested solution?:** If a property of a class has its type inferred from a default value, and that type isn't compatible with all interfaces the class explicitly implements, try inferring the intersection of the types required by the interfaces. So:

```ts
interface OneOrTwo {
    ex: 1 | 2;
}

interface TwoOrThree {
    ex: 2 | 3;
}

class Example implements OneOrTwo, TwoOrThree {
    ex = 2; // should be inferred as type (1 | 2) & (2 | 3), i.e. 2
}
```

For simplicity, if that type doesn't work, the original type (`number` here) should be used in error messages. Maybe the message should be changed, even.

**Comment by RyanCavanaugh** [comment]
See #10570
