### ISSUE TITLE
[Suggestion] Access an object by key can always be undefined

### ISSUE THREAD

**Issue by lmcarreiro** [Microsoft/TypeScript#19478]
```ts
var x: { [key: string]: string } = {};
var y = x["somekey"]; //y type is string
```
Shouldn't `y` type be `string|undefined`? Or I need to be specific in `x`declaration and use `{ [key: string]: string|undefined }` instead of `{ [key: string]: string }`?

**Comment by RyanCavanaugh** [comment]
Duplicate #13778
