### ISSUE TITLE
error TS2339: Property 'control' does not exist on type 'HTMLLabelElement

### ISSUE THREAD

**Issue by soluml** [Microsoft/TypeScript#19477]
**TypeScript Version:**  2.5.2

**Code**

```ts
const label:HTMLLabelElement = (<HTMLLabelElement>document.querySelector('label'));
const input:HTMLInputElement = (<HTMLInputElement>label.control);
```

**Expected behavior:**
Work -> https://developer.mozilla.org/en-US/docs/Web/API/HTMLLabelElement
**Actual behavior:**
Error TS2339

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by soluml** [comment]
Done: https://github.com/Microsoft/TypeScript/pull/19498

**Comment by soluml** [comment]
New PR: https://github.com/Microsoft/TSJS-lib-generator/pull/314
