### ISSUE TITLE
JSDoc cannot resolve namespaces from required modules

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#19476]
**TypeScript Version:**  2.7.0-dev.201xxxxx

Follow up on https://github.com/Microsoft/TypeScript/issues/14056

**Code**
In a simple JS node project, with `index.js`:

```js
const stream = require('stream')

/**
 * @param {stream.Readable} stream
 */
function foo(stream) { ... }
```

**Expected behavior:**
`stream.Readable` is correctly resolved even though it is really used as value here

**Actual behavior:**
Error:  `'Cannot find namespace 'stream'.'`

**Comment by mhegazy** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/16489

**Comment by mjbvz** [comment]
Thanks @mhegazy! Closing as duplicate of #16489
