### ISSUE TITLE
'Github' typo on website

### ISSUE THREAD

**Issue by 0joshuaolson1** [Microsoft/TypeScript#19485]
Where is the website source code, anyway?

**Comment by mhegazy** [comment]
The website is in a private repo at the moment. where is the typo?

**Comment by 0joshuaolson1** [comment]
I don't remember where (sorry). I wouldn't be surprised if there are more - I could `grep` if it were public.

**Comment by DanielRosenwasser** [comment]
What typo?

**Comment by DanielRosenwasser** [comment]
Without knowing what the typo is, I'm not sure what to do. Feel free to follow up if you find it again.

**Comment by 0joshuaolson1** [comment]
@DanielRosenwasser Would it be a problem putting the website in a repo?

**Comment by DanielRosenwasser** [comment]
It's definitely something we want to do, but it's not something we have internal consensus on.

**Comment by 0joshuaolson1** [comment]
Then let's reopen this then.
