### ISSUE TITLE
Cannot invoke an expression whose type lacks a call signature (on function union)

### ISSUE THREAD

**Issue by unional** [Microsoft/TypeScript#19480]
tsc@2.5.3

```ts
// from lodash
declare function isFunction(func): func is ((...args: any[]) => any) | Function

if (isFunction(x)) {
  x('a') // TS2349
}
```

If I remove the union, it works:
```ts
declare function isFunction(func): func is ((...args: any[]) => any)

if (isFunction(x)) {
  x('a') // TS2349
}
```

**Comment by mhegazy** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/7294

**Comment by thorn0** [comment]
Even though, it's indeed a duplicate, I've been always wondering why `Function` and `(...args: any[]) => any` are two distinct types. Aren't they supposed to mean the same thing?

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
