### ISSUE TITLE
FR: Type Inference Operator | :=

### ISSUE THREAD

**Issue by iamclaytonray** [Microsoft/TypeScript#19499]
This may have been discussed already but I couldn't find an issue related, so I'm opening a new one. Is it possible to add a `:=` (type inference) operator to the spec? (I would be more than happy to attempt at helping if this FR gets a green light.)

It's a lot more concise than writing types everywhere but still gives you the same level of type checking/safety as before. Go heavily uses this methodology and I personally love it. Of course, this feature would only be helpful when you want to infer type ***and*** assign at the same time. Most of the time, this is the case anyway. I looked at the style guidelines and I am not sure if/how much this would break. I'll say that this is a job for the compiler and should compile natively into JS with no problem. Those are my naive thoughts but I really don't know. Sorry for not giving much to go on. If this feature is considered, I can come back and write a detailed explanation and maybe write some implementation.

**Comment by andy-ms** [comment]
Types will be inferred anyway.
```ts
const x = 0;
```
Hover over `x`. You should see `const x: 0`.

**Comment by mhegazy** [comment]
As noted by @andy-ms, the compiler will infer the type of a declaration from intializers if one exists, and explicit type annotation is not required. you can also use this with `--noImplicitAny` option, to flag locations where the compiler failed to infer a type, and an explicit type annotation was not specified.

**Comment by iamclaytonray** [comment]
Ahh, guess I should have looked first 😅

**Comment by iamclaytonray** [comment]
Feel free to close

**Comment by iamclaytonray** [comment]
I'll go ahead and close
