### ISSUE TITLE
insertSpaceBeforeTypeAnnotation

### ISSUE THREAD

**Issue by mastef** [Microsoft/TypeScript#19493]
Any chance this could be an option?

Similar behaviour to `insertSpaceAfterTypeAssertion`

`function RGBtoHSB( param1: Int, param2: Int, param3: Int )` would become
`function RGBtoHSB( param1 : Int, param2 : Int, param3 : Int )`

**Comment by mhegazy** [comment]
thanks @Kingwl !

**Comment by mastef** [comment]
Thank you!
