### ISSUE TITLE
Suggestion: int type

### ISSUE THREAD

**Issue by fdecampredon** [Microsoft/TypeScript#195]
Introducing `int` type could allows some  error to be caught at compile time (like trying to index an array with a float) and perhaps improve performance of outputted javascript, to obtains true `int`, TypeScript could systematically emit a cas with `|0` when a variable/parameter is an integer :

``` typescript
var i: int; 
var n: number;
var a: any = 1.2;
i = 1.1; // error;
i = n; // error
i = 3 / 4; // valid, type casted
i = a; // valid, type casted

var indexable: { [i: int]: bool } = {};
indexable[n] = true; // error
indexable[i] = true; // valid
indexable[i/2] = true; // valid, type casted
indexable[a] = true; // valid, type casted

function logInt(i: int) {
  console.log(i);
}
```

would emit

``` javascript
var n;
var i = i | 0;
var a = 1.2;
i = 1.1 // error;
i = n // error
i = (3 / 4 ) | 0; // valid, type casted
i = a | 0; // valid, type casted

var indexable= {};
indexable[n] = true; // error
indexable[i] = true; // valid
indexable[(i / 2) | 0] = true; // valid, type casted
indexable[a | 0] = true; // valid, type casted

function logInt(i: int) {
  i = i | 0;
  console.log(i);
}
```

There will perhaps be a problem with generic and method but I guess the compiler could in this case type cast when passing the parameter:

``` typescript
function add<T>(a: T,b: T): T {
  return a + b;
}  

var a = add(1, 2); // a is number value 3
var b = add<int>(1/2, 2); // b is int, value 2
var c = add(1/2, 2); // c is number, value 2.5
```

emit :

``` javascript
function add(a, b) {
  return a + b;
}
var a = add(1, 2); // a is number value 3
var b = add<int>((1/2)| 0, 2);
var c = add(1/2, 2); // c is number, value 2.5
```

also perhaps the compiler should always infer 'number' if there is not explicit type annotation

``` typescript
var n = 3 //number
var i: int  = 3 //int
```

**Comment by aholmes** [comment]
Another point for integer and float types are for writing definition files. When APIs call for specifically an int or a float, it is dishonest to claim that the type is a number.

**Comment by impinball** [comment]
And there are certain operations that only return 32-bit integers:

- `Math.fround`
- `Math.trunc`
- `Math.imul` (requires both arguments to be 32-bit integers)
- `Math.clz32`
- `Math.floor`
- `Math.sign`
- `x & y`
- `x | y`
- `x ^ y`
- `~x`
- The `length` property of nearly every builtin (every one pre-ES6)
- Any `enum` without numbers assigned
- All the `Date` instance methods that return numbers except `valueOf`and `getTime`
- Any method on any `SIMD` integer type that returns a number (except for `SIMD.int64x2`)
- `DataView.getInt*`
- Every entry in the integer typed arrays.

Others only produce 32-bit integers under certain circumstances:

- `Math.abs(int)`
- `Math.max(int...)`
- `Math.min(int...)`
- `+boolean`
- `-boolean`
- `-int`
- `+int`

And many of the core language APIs accept only integers (and coerce the ones that aren't):

- All the `Date` instance setters that accept numbers except `setTime`
- The entry setters on typed integer arrays
- Any method that requires a number type on SIMD integer types.
- Any lane-related argument in SIMD methods

As for numbers within the range 0 &le; |*x*| &lt; 2<sup>53</sup> ("safe" integers), add the following:

Always produce safe integers:

- `length` instance property on every built-in
- `ArrayBuffer.prototype.byteLength`
- Every `Date` class and instance method that returns a number
- `RegExp.prototype.lastIndex`
- `{Array,String}.prototype.indexOf`
- `{Array,String}.prototype.lastIndexOf`
- The numeric properties of `RegExp.prototype.exec` results
- The numeric instance properties of typed arrays.

Require safe integer arguments:

- Every `Date` class and instance method's numeric arguments
- Indices on every Array, TypedArray, and array-like object
- Array's, ArrayBuffer's, and each TypedArray's length argument
- `ArrayBuffer.prototype.slice`'s arguments

**Comment by ivogabe** [comment]
I've written a proposal in #4639. Big difference is that the emit is not based on type info (which means you can use it with `isolatedModules` and it fits better in the design goals of TS). It also introduces not only an `int` type, but also `uint` and fixed size integers (like `int8`, `uint16` but also other sizes like `int3` and `uint45`). Let me know what you think!

**Comment by rjmunro** [comment]
I'd vote for `int / int = number`, not `int / int = int` and then have to emit `(x / y) | 0` or something. I would follow python3 here not python2.

**Comment by Thaina** [comment]
Do we have function `roundToZero`? I mean `5/4` return 1 and `-5/4` return -1

Also I think the point is `int / int` could return number. But if it cast from number to int it should be rounded to zero

```typescript
var x = 5 / 4; // number 1.25
var y : int = 5 / 4; // int 1
var z = 5; // int 5
var w = x / 4; // number 1.25
```

**Comment by isiahmeadows** [comment]
@Thaina No, but the closest you could get to that would be either `(5/4)|0` or `Math.trunc(5/4)`.

**Comment by styfle** [comment]
If you are interested in integers, follow the [BigInt](https://github.com/Microsoft/TypeScript/issues/15096) proposal which is already **Stage 3** and could solve most of your integer use cases.

**Comment by isiahmeadows** [comment]
@styfle That'll require a separate type from this, because they would require infinite precision, and most DOM APIs would reject them until the WebIDL spec gets updated to accept BigInts where integers are expected. In addition, such integers can't be used with numbers, as the implicit ToNumber coercion would throw for them. (This is similar to how ToString throws for symbols.)

**Comment by tarcieri** [comment]
@isiahmeadows if you take a look at the writeup I did in this issue: https://github.com/Microsoft/TypeScript/issues/15096

...the BigInt proposal is useful for both fixed-width/wrapping and arbitrary precision types.

For example, you could map the following fixed-width types as follows using the given BigInt constructors:

* `int32`: `BigInt.asIntN(32, BigInt)`
* `uint32`: `BigInt.asUintN(32, BigInt)`
* `int64`: `BigInt.asIntN(64, BigInt)`
* `uint64`: `BigInt.asUintN(64, BigInt)`

My understanding is that these particular constructors are supposed to hint to the VM to use the correspondingly sized CPU architecture native integer types, but even if they don't, they should be semantically equivalent to the correspondingly sized wrapping integer types.

Also, Chrome just announced Intent to Ship for TC39 BigInts 🎉 

https://groups.google.com/forum/#!msg/v8-dev/x571Gr0khNo/y8Jk0_vSBAAJ

**Comment by isiahmeadows** [comment]
@tarcieri I'm familiar with that proposal. (I've also got a low need for BigInt, but that's a different deal.)

I'm still interested in a glorified `int32 <: number` for other reasons, since 32-bit machines still exist, and WebAssembly requires them for most integers (notably pointers). BigInts don't interest me *as* much, since I rarely deal with data that large in practice.

As for those constructors, I could see frequent use of `BigInt.as{Int,Uint}N(64, BigInt)` for some cases, but for 32-bit arithmetic, engines *also* have to validate the callee is static. It's also a bit more verbose than I'd like, although I could live with it.

**Comment by tarcieri** [comment]
I think there's a pretty natural mapping of those constructors to sized integer types, e.g.

```
let x: uint64 = 42;
```

with BigInt would compile down to:

```
let x = BigInt.asUintN(64, 42n);
```

I don't think it makes any sense to build any sort of integer type on number. JavaScript finally has native integers, and ones which will raise runtime exceptions if you attempt to perform arithmetic on a mixture of BigInts and numbers.

**Comment by tarcieri** [comment]
@errorx666 TypeScript could use the same literal syntax as JavaScript, but that's unnecessary when the compiler already has the type information

This is no different from almost every other statically typed language on earth, where you are free to write something to the effect of `let x: double = 0`, even though `0` is using the same literal syntax as integers

**Comment by isiahmeadows** [comment]
@tarcieri I've been cautious on suggesting any of that, since that kind of thing has been repeatedly shot down by the TS team. (They seem to prefer sugar to be syntactic, not type-based.)

**Comment by errorx666** [comment]
@tarcieri Suppose you have the type definition for `x` in a `.d.ts` file.  Suppose that `.d.ts` file is in third-party code.  Suppose therefore, then, that the type definition may change, without your knowledge or intent.

Should your compiled emit fundamentally change, without error or warning?

Suppose further that the change introduced some sort of bug.  How much of a nightmare would it be to ultimately trace that bug down to a change in a `.d.ts` file in an npm `@types` package?

**Comment by styfle** [comment]
@errorx666 That scenario can already happen with the following code:

## status.d.ts

```ts
declare module server {
	const enum Status {
		None,
		Pending,
		Approved,
	}
}
```

## main.ts

```ts
console.log(server.Status);
```

## main.js

```js
console.log(2);
```

**Comment by errorx666** [comment]
@styfle Fair point, but at least both possible emits evaluate to 2.

**Comment by tarcieri** [comment]
> I've been cautious on suggesting any of that, since that kind of thing has been repeatedly shot down by the TS team.

This may be too much syntax sugar to swallow, but the benefits outweigh the drawbacks, IMO. There is an opportunity here for TypeScript to model sized, typed integers in a way JavaScript VMs can understand, and also statically assert that programs are free of integer/number type confusion.

> Should your compiled emit fundamentally change, without error or warning?

So, again, for context: we're discussing integer literals.

Every statically typed language I can think of, even where they do support type suffixes/tags, will interpret untagged literals according to the type they're being bound to. So to answer your question: yes, for untagged integer literals, there shouldn't be an error or warning even though the type changed.

If you're worried about type confusion there, yes the tagged syntax should be supported to, and that should fail if a type changes from a BigInt to a number.

**Comment by tarcieri** [comment]
Looks like #15096 is on the TypeScript 3.0 roadmap: https://github.com/Microsoft/TypeScript/wiki/Roadmap#30-july-2018

**Comment by RyanCavanaugh** [comment]
We're still holding the line on type-directed emit. BigInt seems like a "close enough" fit for these use cases and doesn't require us inventing new expression-level syntax.

**Comment by ivogabe** [comment]
Agreed, adding other syntax or types for "double based integers" would only be confusing.

**Comment by trusktr** [comment]
Make it explicit:

```ts
let i:int = 7
i = 1.1; // error
i = 3 / 4; // error
i = Math.floor(3 / 4); // valid, might require a typedef update
i = (3 / 4) | 0; // valid
```

and don't do the automatic compile from `3 / 4` to `(3 / 4) | 0` so we don't break expectations of JS.

**Comment by trusktr** [comment]
> "double based integers" would only be confusing.

Just `int`, nothing more. We're in JS, not C. :)

**Comment by tenshikaito** [comment]
I want to know when we can use the int declaration symbol
