### ISSUE TITLE
Compiling TS with enum strings for 2-way mapping (the old way) causes invalid declaration file (but compiles ok).

### ISSUE THREAD

**Issue by rjamesnw** [Microsoft/TypeScript#19516]
I noticed something seems inconsistent.  I have a mapping that was working for mapping file types and extensions, which was VERY convenient, and allowed tracking them as proper types (other than string).  The .d.ts file is generated ok, without errors! However, if I take that declaration file and add it to another project it breaks.

**TypeScript Version:**  2.5 (that is the only version I have that was updated with VS 2017)

**Code**

```
enum FileTypesMap {
    FileTypeAExt = <any>".aext",
    FileTypeBExt = <any>".bext"
}
enum FileTypesMap {
    FileTypeCExt = <any>".cext",
    FileTypeDExt = <any>".dext"
}
```

**Expected behavior:**

file.d.ts output:
```
declare enum FileTypesMap {
    FileTypeAExt = <any>".aext",
    FileTypeBExt = <any>".bext"
}
declare enum FileTypesMap {
    FileTypeCExt = <any>".cext",
    FileTypeDExt = <any>".dext"
}
```
_(or similar, doesn't matter)_

**Actual behavior:**

file.d.ts output:
```
declare enum FileTypesMap {
    FileTypeAExt,
    FileTypeBExt,
}
declare enum FileTypesMap {
    FileTypeCExt,
    FileTypeDExt,
}
```
ERROR:  In an enum with multiple declarations, only one declaration can omit an initializer for its first enum element.

Yes, I am well aware of the issues of `enum { A = <any>'B', 'B' = <any>'A' }`, and that's besides the point.  If it compiles correctly, the d.ts file should also be proper - it should not be complaining about implementation stuff. ;)

I'm also aware of string enums, and that is also not the point of this code. The point is a mapping between a file type name and an extension (both ways).  There are other ways I'm sure, which is also not the point since this should work. Keep in mind this is part of a framework that also allows others to extend the file type names and extensions.  I imagine there are other ways, but if this way compiles, again, the declaration should not be complaining.

**Comment by mhegazy** [comment]
Do not use numeric enums to add strings. that is not a supported behavior.

Starting from TS 2.4, you can use [string enums](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#string-enums)

**Comment by mhegazy** [comment]
I should add that the "expected" behavior you list never worked.

**Comment by rjamesnw** [comment]
As I stated, I can use enums, which I already know. It compiles just fine, so it should be supported.  I don't see why declarations should be failing for something that compiles, which makes no sense at all.

**Comment by mhegazy** [comment]
> It compiles just fine

no. consider `FileTypesMap.FileTypeAExt.toFixed()`, this will fail at runtime with string.toFixed is not a funciton.

> so it should be supported.

no. it was not supported. we never claimed it was.


> If you don't want to support it, then make it fail at compile time

we do. you casted your way to `any`. same as `(<any>"string").toFixed()`; that one is not supported either.

**Comment by rjamesnw** [comment]
Yes, that will fail, of course, but I'm not using it that way, and as I said, it does not fail the way I put it (only the way you put it). ;)  What I mean is that I used it that way since last year+ (for strong typing before string enums) and it worked just fine - because I knew it wasn't a number!!! ;)  Anyhow, I didn't realize <any> was still treated as a number type (which makes sense) so I do get it.  It would be nice if we allowed some sort of string mapping this way, but I guess I'll have to use another work-around, as typical again.

**Comment by kitsonk** [comment]
> when you try to do stuff you know should work perfectly fine in JS

Enums are a TypeScript only construct... so no, it never worked perfectly fine in JS.

**Comment by rjamesnw** [comment]
Lol, I know that, give me some credit. :P I mean the JavaScript that gets output from the TypeScriot skim I can use to do what I want. I don’t need to use a TypeScript Emil when I can easily do THAT (output) manually.

**Comment by rjamesnw** [comment]
BTW I can appreciate (like C#) enums are numbers, but we do now have enum strings.  Dual mapping for strings would be a really neat feature (where appropriate [like file types and extensions above], and people should be warned to use it correctly), but it's just a thought.  I'd welcome at least the ability to add decorators to string enums to do this at least. ;)  Again, just my 2 cents - 'take it and go' (See Russle Peters). ;)

**Comment by RyanCavanaugh** [comment]
You can *trivially* construct the dual map yourself. There's no reason for TS to complicate itself with this.

**Comment by rjamesnw** [comment]
As I already mentioned, yes. ;)

**Comment by kitsonk** [comment]
And this is pretty!?

```ts
enum FileTypesMap {
    FileTypeAExt = <any>".aext",
    FileTypeBExt = <any>".bext"
}
```

🤷‍♂️

**Comment by rjamesnw** [comment]
I don't recall saying it was pretty at all.  ;)  Besides, do you have a better idea to accomplish the same 2-way mapping without it looking worse?

**Comment by kitsonk** [comment]
> I don't recall saying it was pretty at all. ;)

This issue is to restore a non-pretty unintentional side-effect.  With your last statement, your justification for dismissing the workaround wasn't pretty, therefore I concluded the unintentional side-effect feature you want support was pretty.

**Comment by rjamesnw** [comment]
No it wasn’t. The original intention was to make sure the d.ts stayed consistent to the successfully compile code. How it looks was not relevant to this at all. Also, I said “as pretty” which means other work-arounds are “more ugly”, and that was all. I think you missed my original point.  The fact you even said that shows you don’t like it either, which just further proves my point that it would be nice not use “any” at all and suppprt this in string enums instead somehow (both ways), but in the end there are “less pretty” work arounds, yes.
