### ISSUE TITLE
Add `sourceRange` to TS Server definition response

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#19518]
From https://github.com/Microsoft/vscode/issues/10037

**Problem**
For code such as:

```ts
import './a/b/c';
```

VS Code allows you to hover over the path and hold `cmd` to look up it's definition without pressing f12. This currently is shown as:

![screen shot 2017-10-26 at 6 47 36 pm](https://user-images.githubusercontent.com/12821956/32084474-29565fa4-ba7e-11e7-881f-f2f3d4a21868.png)

Note that only the `b` part of the path is being underlined as expected here. We would expect the entire path to be underlined since this is the symbol we are looking up

**Feature Request**
In order to highlight the entire path (`'./a/b/c`) we need additional information on the TS Server `definition` response that tells us the source range of the symbol. On possible way this could be implemented:

```ts
     interface Definition extends FileSpan {
       source?: FileSpan;
    }

    interface DefinitionResponse extends Response {
        body?: Definition[];
    }
```

This will repeat the same `source` across all returned definitions. Not sure if there is a better way to add the source information to the API in a backwards compatible way

**Comment by mhegazy** [comment]
is https://github.com/Microsoft/TypeScript/pull/19175 what u are looking for?

**Comment by mjbvz** [comment]
Yes that's it exactly. Glad to see someone is already looking into this
