### ISSUE TITLE
Indexes property with name constraint

### ISSUE THREAD

**Issue by NN---** [Microsoft/TypeScript#19523]
Similar concept to #6579 but more restricted.
I want to able to define type where it’s keys are open set but restricted.
For instance define type where all properties starts with prefix.

```ts
interface A{ 
 [prop: /^prefix/]: string;
}

I don’t really need regex syntax, but if possible it will be great.

**Comment by mhegazy** [comment]
Seems like this would be subsumed by https://github.com/Microsoft/TypeScript/issues/6579.
