### ISSUE TITLE
 no compile  error or warn, is it right ?? 

### ISSUE THREAD

**Issue by athinboy** [Microsoft/TypeScript#19521]
**TypeScript Version:**  2.5.3

**Code**

			if (!columnitem.printType) {
				columnitem.printType  == columnPrintType.Text;
			}

 no compile  error or warn, is it right ??

**Comment by mhegazy** [comment]
not sure what u mean. can u share more context?

**Comment by HerringtonDarkholme** [comment]
The op probably wants compiler to warn on wrong usage of `==` instead of `=`.

`columnitem.printType  == columnPrintType.Text;`

TSLint already has a `no-unused-expression` rule. 
https://palantir.github.io/tslint/rules/no-unused-expression/

**Comment by athinboy** [comment]
@mhegazy   

about:   columnitem.printType  == columnPrintType.Text;

I had input wrong "==" , it should be "=".
i expect compile error or compile warn.

**Comment by mhegazy** [comment]
it is a valid expression statement. https://palantir.github.io/tslint/rules/no-unused-expression/ would flag the statement appropriately as @HerringtonDarkholme noted.
