### ISSUE TITLE
Can TypeScript refer to an instance type over a namespace type?

### ISSUE THREAD

**Issue by jez9999** [Microsoft/TypeScript#19529]
I have a library whose `.d.ts` file defined something like:

```
declare class Logger extends EventEmitter {
    constructor();
    info(message: string);
    error(message: string);
}

declare namespace Logger {
    const INFO: number;
    const ERROR: number;
}

export = Logger;
```

I'm accessing it with `require()` and loading it in at runtime:

```
import LoggerType = require("mylogger");

...

let logger: typeof LoggerType;
try {
    logger = require("mylogger").createLogger(...);
}
catch (err) {
    ...
}

if (logger) {
    logger.info("hello world");
}
```

But this doesn't work because TypeScript doesn't see `logger` as an instance of `Logger` but as the namespace `Logger`.  Can it instead refer to the instance of `Logger` so `logger.info()` will not be a type violation?

**Comment by andy-ms** [comment]
`let logger: LoggerType;`
`typeof LoggerType` gives you the type of the module's export, which is a *class*. `LoggerType` gives you the type exported by the module, which is the type of *instances* of `Logger`.

**Comment by jez9999** [comment]
Thanks.
