### ISSUE TITLE
ES5 run-time for "extends" keyword incompatible with ES6

### ISSUE THREAD

**Issue by mindplay-dk** [Microsoft/TypeScript#19525]
The ES5 transpiled output from the Typescript compiler for the `extends` keyword isn't consistent with the current standard behavior of ES6 Javascript, and also isn't consistent with the way Typescript checks the types at compile-time.

**Code**

```ts
class List extends Array { }

alert(new List instanceof List);
```

[Try it on the playground](https://www.typescriptlang.org/play/#src=class%20List%20extends%20Array%20%7B%20%7D%0D%0A%0D%0Aalert(new%20List%20instanceof%20List)%3B) where the code is transpiled to ES5 by default.

**Expected behavior:**

An alert showing `true`.

**Actual behavior:**

An alert showing `false`.

**Comment by Kingwl** [comment]
seems generated code `return _super !== null && _super.apply(this, arguments) || this;` return a new Array

**Comment by aluanhaddad** [comment]
It is not currently viable to extend built-ins.

A potential solution is proposed in #15397

**Comment by HerringtonDarkholme** [comment]
https://github.com/Microsoft/TypeScript/wiki/FAQ#why-doesnt-extending-built-ins-like-error-array-and-map-work
