### ISSUE TITLE
Opening files in different order in IDE produces different errors

### ISSUE THREAD

**Issue by JsonFreeman** [Microsoft/TypeScript#1953]
0.ts:
```ts
///<reference path="1.ts"/>
///<reference path="2.ts"/>
var i: A | B;
var param: any;
i.foo(param); // May or may not produce an error
```
1.ts:
```ts
///<reference path="0.ts"/>
///<reference path="2.ts"/>
interface A {
    foo(): string;
}
```
2.ts:
```ts
///<reference path="0.ts"/>
///<reference path="1.ts"/>
interface B {
    foo(x?): string;
}
```
These three files form a clique because they all reference each other. If you start with none of these files open, and then open them, you may or may not get an error depending on the order that you open the files. Specifically, if you open file 0.ts or 1.ts first, you get an error. But if you open 2.ts first, you get no error.

This has to do with the nondeterministic order of types for union type collapsing.

This also means that the order the IDE calls getSemanticDiagnostics on the files is important, as it could lead to different outcomes. For compile-on-save, we call getSemanticDiagnostics on just the file we are saving. But in order to get a consistent outcome, we would have to call getSemanicDiagnostics on *all* the files in a canonical order, every time a file is saved. This means many files may have to be type checked before you can emit the file you've saved.

**Comment by JsonFreeman** [comment]
This could be fixed by adding a stricter subtype rule for optional parameters versus absent parameters

**Comment by mhegazy** [comment]
This should be fixed after the strict object literal changes

**Comment by DanielRosenwasser** [comment]
> This should be fixed after the strict object literal changes

What exactly is the reason for that?

**Comment by danquirk** [comment]
@DanielRosenwasser I believe because

_This has to do with the nondeterministic order of types for union type collapsing._

is no longer relevant as subtype reduction for union types was removed as part of the strict object literal changes. We should double check that this actually no longer repros though.

**Comment by JsonFreeman** [comment]
It isn't really because we eliminated subtype reduction in that change. We did in fact eliminate subtype reduction. But more importantly we eliminating the sorting of union constituents by type id. That was the source of the nondeterminism.
