### ISSUE TITLE
Union type as key works for `type` but not for `interface`

### ISSUE THREAD

**Issue by ccorcos** [Microsoft/TypeScript#19534]
**TypeScript Version:**  2.7.0-dev.201xxxxx

**Code**

```ts
type X = "a" | "b"

type A = {[x in X]: string} // no error

interface  B {[x in X]: string} // error
```

**Expected behavior:**

Its my understanding that type and interface are exactly the same thing.

**Actual behavior:**

**Comment by RyanCavanaugh** [comment]
They are not
