### ISSUE TITLE
Allow for indexable types other than `string` and `number`

### ISSUE THREAD

**Issue by aryzing** [Microsoft/TypeScript#19538]
Given the following definition of a user and a user map,

```ts
type UserId = string;

interface User {
  id: UserId;
  name: string;
  email: string;
}

interface UserMap {
  [id: string]: User;
}

let userMap: UserMap = {
  id0001: {
    id: 'id0001',
    name: 'person1',
    email: 'person1@example.com',
  },
};
```

We can insert another user into the map by using a variable of type `UserId`,

```ts
let anotherUserId: UserId = 'id0002';

userMap[anotherUserId] = {
  id: anotherUserId,
  name: 'person2',
  email: 'person2@example.com',
}
```

However, I was surprised to find out that the indexable type can't be defined using the UserId type,

```ts
interface UserMap {
  [id: UserId]: User // error!
}
```

I'm sure we would all appreciate the certainty of knowing that the value we're using as an index is of the proper type, to avoid situations like

```ts
let productId: ProductId = 'prod123'

userMap[productId] = {/*...*/}
```

Is this a viable feature to include in TypeScript?

**Comment by RyanCavanaugh** [comment]
See #7374 and its many linked duplicates
