### ISSUE TITLE
Soundness issue with Array.prototype.concat and arrays of arrays

### ISSUE THREAD

**Issue by andyfriesen** [microsoft/TypeScript#19535]
**TypeScript Version:**  2.7.0-dev.201xxxxx

**Code**

```ts
const foo: [number, string][] = [[1, 'one']];
console.log(foo.concat([2, 'two']));
```

**Expected behavior:**
Either `[[1, 'one'], [2, 'two']]` or a type error.

**Actual behavior:**
`[[1, 'one'], 2, 'two']`

**Comment by Ghabriel** [comment]
`a.concat(b)` pushes the elements of `b` to `a`, so the actual behavior is correct (also, what the functions _do_ at runtime is JavaScript-world, not TypeScript). Your expected behavior happens if you use `push` instead:
```ts
const foo: [number, string][] = [[1, 'one']];
foo.push([2, 'two']);
console.log(foo);
```

**Comment by andyfriesen** [comment]
This is absolutely true.

My concern primarily lies with the fact that it was so easy to violate type safety.  It would be nice if this showed up in the editor rather than something I had to debug at runtime.

**Comment by mhegazy** [comment]
One option is to change the definition of `concat` to be:

```ts
    concat<U>(...items: (T | ConcatArray<T>)[]): T extends ConcatArray<infer E> ? (E | T)[] : T[];
```

**Comment by mhegazy** [comment]
PRs welcomed

**Comment by Ghabriel** [comment]
I'm working on it, but I've encountered the following error after doing the change:
```ts
src/compiler/core.ts:840:42 - error TS2345: Argument of type 'SortedArray<T>' is not assignable to parameter of type 'ReadonlyArray<T>'.
  Types of property 'concat' are incompatible.
    Type '(...items: (T | ConcatArray<T>)[]) => T extends ConcatArray<infer E> ? (E | T)[] : T[]' is not assignable to type '(...items: (T | ConcatArray<T>)[]) => T extends ConcatArray<infer E> ? (E | T)[] : T[]'. Two different types with this name exist, but they are unrelated.
      Type 'T extends ConcatArray<infer E> ? (E | T)[] : T[]' is not assignable to type 'T extends ConcatArray<infer E> ? (E | T)[] : T[]'. Two different types with this name exist, but they are unrelated.

840         const insertIndex = binarySearch(array, insert, identity, compare);
                                             ~~~~~
```

...and a bunch of errors in the form `Argument of type 'T[]' is not assignable to parameter of type 'ReadonlyArray<T>'`. This seems to be a bug, right?

**Comment by mhegazy** [comment]
did you change the declaration of both Array and ReadonlyArray?

**Comment by andersk** [comment]
Another example:

```ts
const a: number[][] = [[1]].concat([[2]], [3])
// → [[1], [2], 3]
```

and a related issue with `flatMap`:

```ts
const b: number[][] = [true, false].flatMap<number[]>(x => x ? [1] : [[2]]);
// → [1, [2]]
```

**Comment by RyanCavanaugh** [comment]
Rolling up into #36554
