### ISSUE TITLE
reflect-metadata

### ISSUE THREAD

**Issue by fsx950223** [Microsoft/TypeScript#19530]
QUESTIONS: The result is Object when I use Reflect.getOwnMetadata to get the type defined by myself,it can only return built-in types?? 

**TypeScript Version:**  2.7.0-dev.201xxxxx

**Code**

```ts
const result = Reflect.getOwnMetadata("design:type", target, key);
```

**Expected behavior:**
Return type defined by myself 
**Actual behavior:**
Return Object

**Comment by mhegazy** [comment]
The metadata feature uses run time references to express types. so if you are using a class for instance, the constructor function will be the one used. For primitives, the boxed types are used, i.e. `number` becomes `Number`. for anything else, i.e. structural types, `Object` is used.

see relevant discussion in https://github.com/Microsoft/TypeScript/issues/3628

**Comment by fsx950223** [comment]
So ,the feature is useless
