### ISSUE TITLE
`Document.getElementById()` must return `Element`, not `HTMLElement`

### ISSUE THREAD

**Issue by inad9300** [Microsoft/TypeScript#19549]
SVG elements are also reachable through `document.getElementById()`, see https://developer.mozilla.org/en-US/docs/Web/API/Document/getElementById.

Other methods may need to be adjusted in the same way. Please, review them.

**Comment by mhegazy** [comment]
Related discussion in https://github.com/Microsoft/TypeScript/issues/4689

**Comment by inad9300** [comment]
I believe this can be closed in favour of #4689.
