### ISSUE TITLE
Compiler does not narrow tuples based on `length` property

### ISSUE THREAD

**Issue by eyyubovkamran** [Microsoft/TypeScript#19543]
**TypeScript Version:**  2.7.0-dev.201xxxxx

```ts 
type A = [string] | [string, number];

let x: A;
if(x.length > 1){
    let y: number = x[1];
}
```

**Expected behavior:**
Should compile successfully.

**Actual behavior:**
`error TS2322: Type 'string | number' is not assignable to type 'number'. `
`Type 'string' is not assignable to type 'number'.`

**Comment by RyanCavanaugh** [comment]
Hijacking this to represent the proposed literal `length` change proposed at the design meeting today

cc @DanielRosenwasser @ahejlsberg

**Comment by mhegazy** [comment]
related to https://github.com/Microsoft/TypeScript/issues/19536 and https://github.com/Microsoft/TypeScript/issues/19463

**Comment by mhegazy** [comment]
Using `>` as a discriminant is something we do not see much value in at the time being. but it should work with `===` assuming we go with proposal in https://github.com/Microsoft/TypeScript/pull/17765, which will give tuples an explicit length property with a literal type, and hence will allow `length` to act as a discriminant property.

**Comment by mhegazy** [comment]
Should be subsumed by #19463 and  #17765.

**Comment by sandersn** [comment]
Yes, narrowing with `===` works with #17765.
