### ISSUE TITLE
AllowJs - ts-check - Cannot find namespace

### ISSUE THREAD

**Issue by jantimon** [Microsoft/TypeScript#19547]
**Code**

`node_modules/@types/thirdParty/index.d.ts`
```ts
export = demo;
declare namespace demo {
  foo: number;
}
```

`main.js`
```ts
// @ts-check
/// <reference types="thirdParty" />
const x: demo.foo;
```

**Expected behavior:**

I should be able to use the type `foo` of `demo`.
The example from above would work if but only if the thirdParty plugin also exports its namespace:

```ts
export as namespace demo;
```

I couldn't find any docs on what exactly `export as namespace` does.  
Proably it would just add it to the global namespace which might not be the desired solution.

**Actual behavior:**

Without the exported namespace I receive error messages which are not helpful at all:

```
error TS2304: Cannot find name 'demo'
error TS2503: Cannot find namespace 'demo'
```

**Suggestion:**

Could we import everything which is exported from the index.d.ts file (like `export = demo`) to a name?
This would be useful for `--allowJs` checks where we can't import typings from another file.

```ts
// @ts-check
/// <reference types="thirdParty" name="thirdParty" />
```

**Comment by aluanhaddad** [comment]
What is the shape of the actual package at runtime?

If `demo` is available as a global then the declaration needs to be updated to add the `export as namespace demo` clause as you described.

If it isn't available globally, then you won't be able to use it without importing its value in which case you will have access to the types.

**Comment by jantimon** [comment]
In my hypothetical example `demo` won't be globally available.  
How would it be possible to import **types** from that thirdParty plugin into a `.js` file which is using `@ts-check`?

**Comment by aluanhaddad** [comment]
If it's not available globally than using reference types is not correct.
> How would it be possible to import types from that thirdParty plugin into a .js file which is using @ts-check ?

Different approaches are possible depending on how you load modules but let's say you're using CommonJS.

```js
var demo = require('demo');

/**
  * @param x {demo.SomeType}
  */
function f(x) {}
```

It's worth mentioning that there is a syntax error in the declaration in the OP so it will not work as written.

**Comment by aluanhaddad** [comment]
Sorry, it appears that doesn't work. I thought it was supposed to work.

**Comment by jantimon** [comment]
Unfortunate the oss ecosystem I am working on (webpack) still supports node 4 which is years away from ESM.. is there any other possible solution which doesn't require transpiling?

**Comment by aluanhaddad** [comment]
No, but if since are already using Webpack, you can just use the synthetic default form. Recent versions of Webpack perform the hoisting.

I do think this is a bug however.

**Comment by jantimon** [comment]
I am not using webpack but developing a webpack plugin

**Comment by aluanhaddad** [comment]
You could always use `tsc` to transpile your JavaScript 😉 it will remove the import since it is only used in type position when it runs, but at that point you might as well just use TypeScript directly.

**Comment by jantimon** [comment]
What might be a propper way to resolve this bug?
Is there anything I can do to fix it?

**Comment by DanielRosenwasser** [comment]
You can potentially import into a .d.ts file that globally augments the type space.

Also see

- #14377
- #16489

**Comment by aluanhaddad** [comment]
@DanielRosenwasser I'm just wondering if this is the intended behavior. 

Perhaps it's a naive assumption but it seems like this scenario could be enabled and would be more natural for reusing existing declaration files.

I realize that `import..require` has special semantics but does it have? Could `var..require` behave similarly in this context?

**Comment by DanielRosenwasser** [comment]
> I'm just wondering if this is the intended behavior.

No, I do think this should just work.

**Comment by jantimon** [comment]
Thanks for all the additional information @DanielRosenwasser - #16489 and #18460 are almost duplicates and it seems the feature was added to the typescript 2.7 milestone by @mhegazy
