### ISSUE TITLE
Allow people to add stuff to `tsconfig.json`

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#1955]
I understand that `tsconfig.json` is read only for the typescript compiler. But whenever you guys start reading / modifying => writing `tsconfig.json` files would be great if you preserve additional keys. This would allow potential stuff like `tslint` errors to live in `tsconfig.json`. 

Also I'm doing this : https://github.com/TypeStrong/atom-typescript/issues/56

**Comment by mhegazy** [comment]
This has been the intention for the tsconfig work from the get go. It is just a json file you can extend it the way you like. This is also why the options are on a special mode:compileroptions and not just on the root. Obviously you want to have a top node as well that holds all your configurations e.g linterOptions to minimize chances of others stepping on your configurations.

**Comment by danquirk** [comment]
Is something actually broken here?

**Comment by basarat** [comment]
> Is something actually broken here?

no this was a question. Thanks!

**Comment by basarat** [comment]
I am extending it with `format` : https://github.com/TypeStrong/atom-typescript/blob/master/docs/tsconfig.md#filesglob 

/cc @fdecampredon, @vvakame, @johnnyreilly, @ashwinr

**Comment by basarat** [comment]
@park9140

**Comment by johnnyreilly** [comment]
Thanks for the heads up @basarat

**Comment by basarat** [comment]
@mhegazy I see you are using https://github.com/Microsoft/TypeScript/blame/master/src/server/editorServices.ts#L262 `formatCodeOptions` so I will rename mine to match
