### ISSUE TITLE
Inconsistency between imports and assignments with type and item namespaces

### ISSUE THREAD

**Issue by chriskrycho** [Microsoft/TypeScript#19553]
**TypeScript Version:**  2.7.0-dev.201xxxxx

**Code**

Declaring module, `foo.ts`:

```ts
export class Duck { 
  speak() { console.log('quack'); }
}

export class Dog {
  speak() { console.log('bark'); }
}

export type Foo = Duck | Dog;
export default Foo;
```

In the consuming module, `bar.ts`, this is an error, "Duplicate identifier 'Foo'":

```ts
import Foo, * as Foo from 'foo';
```

But this is *not* an error:

```ts
import * as Foo from 'foo';
type Foo = Foo.Foo;
```

The same problem appears regardless of how the imports are structured, i.e. it is not a problem with *default* exports specifically, but the resolution of import names.

**Expected behavior:**

The two have the same semantics, so that you can import a *type* from another module and the module itself with the same name and use them side by side.

```ts
import Foo, * as Foo from 'foo';

const foo1: Foo = new Foo.Duck();
const foo2: Foo = new Foo.Dog();
```

**Actual behavior:**

They have *different* semantics, requiring you to type either a separate type assignment, `type Foo = Foo.Foo`, or repeat the name repeatedly `something: Foo.Foo`, or alias one of the imports.

(It's also surprising since it's one of the few places that the different namespaces for types and items doesn't seem to hold.)

## Motivation

If you're curious about why this matters, consider the API for [this library](https://github.com/chriskrycho/true-myth). It is very helpful to be able to do this:

```ts
import * as Maybe from 'true-myth/maybe';

const quux = Maybe.of(someVariable); // could be null, who knows?
```

However, it's also important to be able to define an item is a `Maybe` type:

```ts
import Maybe from 'true-myth/maybe';

function couldBeMissing(somethingImportant: Maybe<string>) {
  return somethingImportant.map(s => s.length);
}
```

To use the two together with `import * as`, you have to repeat the type:

```ts
import * as Maybe from 'true-myth/maybe';

function couldBeMissing(somethingImportant: Maybe.Maybe<string>) {
  return somethingImportant.map(s => s.length);
}

const result = couldBeMissing(Maybe.of('hello!'));
```

**Comment by aluanhaddad** [comment]
Can you leverage declaration merging?
```ts
// maybe.ts
export type Just<T> = T;
export type Nothing<T = {}> = void;

type Maybe<T> = Just<T> | Nothing<T>;
const Maybe = {
  of<T>(x: T): Maybe<T> {
    return x;
  }
};

export default Maybe;
```
```ts
// uses-maybe.ts
import Maybe from './maybe';

const maybe: Maybe<string> = Maybe.of('abc');
```

**Comment by chriskrycho** [comment]
Interesting thought—I'll have to give it a try. And in that case, given the current API structure, I might be able to do this, even:

```ts
// one example function, types as you suggested
const of<T> = (x?: T | null): Maybe<T> =>
  isVoid(x) ? nothing() : just(x);

export type Maybe<T> = Just<T> | Nothing<T>;
export const Maybe = {
  of,
  // etc.
};

export default Maybe;
```

**Comment by aluanhaddad** [comment]
I think it has to do with the meaning of `default` it implies a name in the value space, but I could be mistaken about that.

At least the workaround is actually easier to consume though.

**Comment by mhegazy** [comment]
Analyzing what a name means happens in an early pass in the compiler, during binding. at that time the compiler is only looking at one file and not the whole program. knowing what `Foo` refers to, and whether it can merge or not, is still not known. This is an implementation/design limitation at the moment.

**Comment by aluanhaddad** [comment]
Thanks for explaining :heart:

**Comment by chriskrycho** [comment]
Indeed, the explanation is appreciated. I'd love to see this change in the future, but understand—limited bandwidth, etc.
