### ISSUE TITLE
tsc --watch should emit appropriate message to stdout

### ISSUE THREAD

**Issue by ORESoftware** [Microsoft/TypeScript#19558]
Here to report a bug or deficiency in the `tsc -w` process -

I am currently using `tsc` version `2.3.4`

**Expected behavior:**

I would expect that `tsc -w` would emit the following upon compilation errors:

> Compilation complete with errors. Watching for file changes.

**Actual behavior:**

`tsc -w` always emits the following message regardless of whether there were compilations errors or not:

> Compilation complete. Watching for file changes.

`tsc` emits a message that does not suggest that there are errors. It seems to emit the same message regardless of whether there is an error or not. This makes it near impossible to create good tooling around tsc watch!

**Comment by DanielRosenwasser** [comment]
> This makes it near impossible to create good tooling around tsc watch!

I would ***highly recommend*** using the compiler API instead of parsing our output.

**Comment by ORESoftware** [comment]
This is for a library, I need to support users that are using `tsc -w` - I need to be able to hook into it.

**Comment by ORESoftware** [comment]
@DanielRosenwasser what I recommend - don't change anything without a new flag, so like this:

`tsc --watch --machine-readable-stdio`

with this `--machine-readable-stdio` flag set to true, then write information to stdout/stderr that is machine readable, that people can use to hook into `tsc -w`.

**Comment by mhegazy** [comment]
> This is for a library, I need to support users that are using tsc -w .... I need to be able to hook into it. But perhaps I can use the compiler API instead. No matter what, I need watching features + incremental builds. Parsing the stdout is easy, if you guys make sure it's standardized.

Consider using a tool like gulp for achieving this scenario.

**Comment by mhegazy** [comment]
Also i think this is just a duplicate of https://github.com/Microsoft/TypeScript/issues/16602

**Comment by ORESoftware** [comment]
@mhegazy this is for a library, I don't want to depend on Gulp for a library, I will move this to the other issue.
