### ISSUE TITLE
"locale" isn't respected in tsconfig.json

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#19566]
~~Create a project with a `tsconfig.json`, write some erroneous code, start compiling in `--watch` mode, and try changing the `locale `option around a bit. You'll see that the error messages don't actually get reflected to the currently specified language.~~

I thought this was a problem with `tsconfig.json` not getting its settings updated, but it's really just that it's not checked.

**Comment by mhegazy** [comment]
`--locale` is really a function of the process that is doing the compilation, either `tsc` or `tsserver`. the locale is loaded once during the process lifetime and is not changed during the execution. in that sense having it in the tsconfig.json is not right.

**Comment by mhegazy** [comment]
Pushed https://github.com/SchemaStore/schemastore/pull/362 to remove `--locale` from tsconfig.json help.

**Comment by falsandtru** [comment]
I'm very annoyed with force applying of your localization. I don't want to see any languages without English while at coding. Localized error messages don't have compatibility with non-localized on trouble shooting.

**Comment by mhegazy** [comment]
> I don't want to see any languages without English while at coding

No one is forcing anything on anybody.. English is the default. I am assuming you are using VSCode, and in this case, it uses your locale for the errors. if you want to opt-out of this behavior set `"typescript.locale": "en"` in your settings.

//cc @mjbvz
