### ISSUE TITLE
Issues building/testing clean clone in node v8.8.1 and coffeescript 2.0.2

### ISSUE THREAD

**Issue by pietersv** [Microsoft/TypeScript#19567]
On a clean clone of the project, `npm run prepublish` seemed to fail in with Coffeescript 2 on node v8.8.1 yielding the following error:
```
src/XMLStreamWriter.coffee:32:5: error: Can't reference 'this' before calling super in derived class constructors
    @stream = stream
```
This can be resolved by swapping lines 33 and 33 in the file `src/XMLStreamWriter.coffee` such that `super` appears first, so it appears as follows:

```coffee
  constructor: (stream, options) ->
    super options
    @stream = stream
```

After that, `npm run prepublish` succeeds, but `npm run test` failed due to:
```
xmlbuilder-js/test/basic/stringify.coffee:15:56: error: invalid escape sequence \u{000
    err () -> xml('test').node('node with invalid char \u{0000} in node name')
```

This can be resolved by commenting out lines 15-19 of `test/stringify.coffee` :
```
    err () -> xml('test').node('node with invalid char \u{0000} in node name')
    err () -> xml('test').node('node with invalid char \u{D800} in node name')
    err () -> xml('test').node('node with invalid char \u{DFFF} in node name')
    err () -> xml('test').node('node with invalid char \u{FFFE} in node name')
    err () -> xml('test').node('node with invalid char \u{FFFF} in node name')
```
After that all the rest seems to work fine and proceed as expected.

This might be due to changes in coffeescript handling of `super` (https://github.com/jashkenas/coffeescript/issues/4547)

**Comment by DanielRosenwasser** [comment]
I think this is the wrong repository?

**Comment by pietersv** [comment]
Yikes, sorry!
