### ISSUE TITLE
Why some unicode characters are duplicate in unicodeES5IdentifierStart in scanner?

### ISSUE THREAD

**Issue by ke-yu** [Microsoft/TypeScript#1956]
I'm just reading [scanner code](https://github.com/Microsoft/TypeScript/blob/master/src/compiler/scanner.ts) and find some unicode characters are duplicate in ``unicodeES5IdentifierStart`` array:

    var unicodeES5IdentifierStart = [170, 170, 181, 181, ..., 748, 748...

Any reason?

**Comment by DanielRosenwasser** [comment]
To double-check each time :wink:.

Maybe @mhegazy knows something we don't? If it shouldn't be there, we'd be willing to take a pull request.

**Comment by ahejlsberg** [comment]
The entries are pairwise min/max values for ranges of Unicode code points. So, 170 followed by 170 means the range starting at 170 and ending at 170--i.e. the single code point 170.

**Comment by DanielRosenwasser** [comment]
Thanks @ahejlsberg! We should probably add a comment.
