### ISSUE TITLE
Computed properties with "target = es5" and "modules = esnext" emits JS syntax errors

### ISSUE THREAD

**Issue by MadaraUchiha** [Microsoft/TypeScript#19574]
**TypeScript Version:**  2.7.0-dev.201xxxxx (and 2.5.3)

**Code**

tsconfig.json:
```json
{
  "target": "es5",
  "module": "esnext",
}
```

index.ts:
```ts
export default {
  ['foo']: 42
};
```

**Expected behavior:**
Code compiles to something like
```js
var _temp = {},
  _temp['foo'] = 42

export default _temp;
```

**Actual behavior:**
compiles to 
```js
export default _a = {},
    _a['foo'] = 42,
    _a;
var _a;
```

Which is invalid JS, causing Webpack to bork on it. 

From what I gather, `export default` has precedence over the comma operator, causing a syntax error.

**Proposed solution:**
Surround the emitted object with braces (even when the source object is not surrounded by braces) like so:
```js
export default (_a = {},
    _a['foo'] = 42,
    _a);
var _a;
```

**Workaround:**
Surrounding the object in the source with braces causes the emitted code to have braces as well, exactly as the proposed solution.

**Comment by drwatsno** [comment]
"tsc -w" generates code with this bug on 2.7.0-rc

**Comment by weswigham** [comment]
Just `-w` mode?
