### ISSUE TITLE
Collaboration with Google/Facebook

### ISSUE THREAD

**Issue by mihailik** [Microsoft/TypeScript#1958]
Looks like things have started to happen, look at the 'demo' and 'thanksLua' branches.

[thanksLua](https://github.com/Microsoft/TypeScript/compare/thanksLua)
[demo](https://github.com/Microsoft/TypeScript/compare/demo)

Is there anything TypeScript community should already know about the planning, ideas, clues and hints?

Many serious JS projects out there are considering higher-level options as we speak. Letting people peek into these secretive plans would help winning them at TypeScript side ;-)

**Comment by danquirk** [comment]
We don't have anything to announce at the moment. We've been in touch with a variety of typed JS projects and will continue to be, ex https://github.com/Microsoft/TypeScript/issues/986

**Comment by DanielRosenwasser** [comment]
> Looks like things have started to happen

Not sure what you mean, this is ES6 support which has been slated for a while now.
