### ISSUE TITLE
Document --locale compiler option

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#19582]
Our [documentation](https://www.typescriptlang.org/docs/handbook/compiler-options.html) does not list what the allowed values of this option are. It also doesn't show up in `tsc --help`. We should be able to infer the locale names from the generated directory names from `gulp localize`.

**Comment by mhegazy** [comment]
Also added to the wiki under https://github.com/Microsoft/TypeScript/wiki/Standalone-Server-(tsserver)
