### ISSUE TITLE
TypeScript doesn't see a new symlink in node_modules

### ISSUE THREAD

**Issue by zkochan** [Microsoft/TypeScript#19594]
**TypeScript Version:**  2.7.0-dev.20171029

TypeScript doesn't see a symlink inside `node_modules` when executed twice. The symlink is created after the first execution of typescript. It seems like some caching issue.

Code to reproduce is in this repo: https://github.com/pnpm/outdated/tree/experimenting. You have to install [pnpm](https://github.com/pnpm/pnpm) and run `pnpm install && npm test`. It will fail only the very first time. Next executions of `npm test` will work, even if the symlink (at `node_modules/@pnpm/outdated`) will be removed manually.

Fail can be seen in CI: https://travis-ci.org/pnpm/outdated/jobs/295085685#L521

I used ls `node_modules/@pnpm` to demonstrate that the symlink is there before `tsc` is executed.

**For some context.** I created a tool called [package-preview](https://github.com/zkochan/package-preview) which packs and installs locally the tested package before running tests. So unit tests are testing a real production-like version of the package.

When a project is written in typescript, package-preview will compile the project with typescript, pack it, install it in a different folder and symlink it to the project's node_modules. Then it calls typescript again, to run the tests, which import the "real thing", the pseudo-published package... (that is when typescript fails)

* * *

I see many caches in the typescript repo, is there some flag that I can use to make typescript ignore cache? Or is there a command to ignore it?

**Comment by andy-ms** [comment]
Running `tsc` on the command line twice shouldn't involve any caching. Are you sure that the file system content is the same both times you run it?

**Comment by zkochan** [comment]
The node_modules content differs. The first time I run it, there is no symlink in `node_modules/@pnpm/outdated`. The symlink is created before it is called the second time.

**Comment by andy-ms** [comment]
`tsc` shouldn't perform any writes to `node_modules`. It sounds like some other tool is creating the link. So if you run `tsc` twice in a row without intervening steps you should see the same result twice.

**Comment by zkochan** [comment]
Yes, another tool creates the symlink (the [package-preview](https://github.com/zkochan/package-preview))

First time tsc is called when the package is packed. The package is then unpacked in another directory and linked into `node_modules`. Then tsc is called second time to run the tests. The tests are importing the package by name (because the backage is symlinked into node_module by then)

**Comment by andy-ms** [comment]
It sounds like the error doesn't have anything to do with the number of times you run `tsc`. The result of `tsc` should be determined solely by the content of the file system at the time it is run. Based on that, you should be able to get a repro for this issue that consists only of creating some files (and symlinks) and then running `tsc`.

**Comment by zkochan** [comment]
Alright, I'll try to make a simpler example. Probably tomorrow.

**Comment by zkochan** [comment]
There is no issue in TypeScript. I thought `npm pack` runs prepublish scripts but it doesn't. So tsc was called only once, the second time, and `.d.ts.` files were not there. So the error was not because typescript did not see the symlink. It was because it did not find the `d.ts.` file.
