### ISSUE TITLE
After applying install module quick fix, errors are not refreshed

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#19597]
The errors are not  updated after the package is installed. the only way to get ride of the error is to reload the file, or edit the import.
![animation](https://user-images.githubusercontent.com/8000722/32201298-7c1c6c7a-bd93-11e7-8b7c-2d6dfb41cbb2.gif)

**Comment by andy-ms** [comment]
This appears to be the behavior when running `npm install` on the command line. If we fix that it should fix this. I think we should be watching `node_modules` to see if any new packages are installed.

**Comment by mhegazy** [comment]
@sheetalkamat thoughts about this issue?
