### ISSUE TITLE
Suggestion: Export some internal type checking helpers

### ISSUE THREAD

**Issue by raveclassic** [Microsoft/TypeScript#19602]
I'm trying to implement a [tslint](https://github.com/palantir/tslint) custom rule to manually force and check yield typings inside of generator-based sagas from [redux-saga](https://redux-saga.js.org). As the statuses of #2983 and similar issues are unknown it seems like custom rule is the only way for now.

So, at the moment I'm able to only force setting explicit type on the left side of yield expression:
```typescript
const timePeriod = yield select(FilterSelectors.timePeriod);
          ^^^ error from custom rule - value has implicit any type                      
```
The next step is to extract the types of the left and right sides of such yield and it's possible with public `TypeChecker#getTypeFromTypeNode`. 
Now when both types are available they could be checked for assignability with helpers under `// TYPE CHECKING` section in `compiler/checker.ts` in `createTypechecker` factory function (like `checkTypeAssignableTo`), but unfortunately they are isolated inside that factory.

Therefore I suggest exporting that helpers from `compiler/checker.ts` on the module-level (or under a namespace, or even as `TypeChecker` static fields), they will be very helpful for implementing such custom rules.

**Comment by mhegazy** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/9879

**Comment by raveclassic** [comment]
@mhegazy Thanks for the pointing! Closing

**Comment by cloudify** [comment]
@raveclassic and anybody else looking at type checking saga yield calls: I've create a very crude custom tslint rule [here](https://github.com/teamdigitale/italia-app/pull/185/files#diff-4f6d285e58ab32393eb1776d2bdb8bca), hope it helps. 

The rules checks that the return type of the function passed to `select` and `call` matches the type of the variable on the left side of the `yield` and the types are matched using the result of `typeToString`.

It's not perfect, but it works for my needs, hope it helps.

**Comment by raveclassic** [comment]
@cloudify Thanks! However we've dropped both redux and redux-saga and switched to rxjs completely.
