### ISSUE TITLE
Suggestion -- condsider making different syntaxKinds for object literal properties and class properties

### ISSUE THREAD

**Issue by gscshoyru** [Microsoft/TypeScript#1960]
In earlier versions of typescript, object literal properties and class properties were different syntax kinds. Now they are the same syntax kind -- property -- which caused this bug here: https://github.com/palantir/tslint/issues/292 for when we converted the rule to the new compiler. It would be easier if they were different, as they were before.

**Comment by mhegazy** [comment]
this should be fixed now.
