### ISSUE TITLE
Try-catch statements should be a target of noUnusedParameters

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#19601]
Should use the optional catch clause instead.

**TypeScript Version:**  master

**Code**

```ts
try {
}
catch (_) {
}
```

**Expected behavior:**

error

**Actual behavior:**

pass

**Comment by andy-ms** [comment]
Seems like a good idea but it would be a breaking change.

**Comment by mhegazy** [comment]
This is a breaking change. This check is a linter check in the first place, and we should not have added them. In the light of our [recent discussions about errors vs warnings](https://github.com/Microsoft/TypeScript/issues/19393) we should hold off on any of these changes.
