### ISSUE TITLE
Why is this interface being exported?

### ISSUE THREAD

**Issue by jez9999** [Microsoft/TypeScript#19604]
I added the `zmq` NPM module to my project, as well as its typings.  My program is able to access the `Socket` interface:

```
import * as zmq from "zmq";
let mySocket: zmq.Socket;
```

My question is: why does this work?  Looking at the definition file `zmq/index.d.ts`, this is the definition of `Socket`:

```
interface Socket extends EventEmitter {
    ...
}
```

The interface is not `export`ed, so why does my code get access?

**Comment by gcnew** [comment]
In a `d.ts` file everything is exported by default.

**Comment by jez9999** [comment]
So normally it would need an `export` in a `ts` file but `d.ts` is a special case?

**Comment by gcnew** [comment]
Sorry, I don't know the ins and outs of declaration files. There are different rules that apply depending on the type of exports - module, ambient, etc. I'll let someone more knowledgeable answer your question.

**Comment by gcnew** [comment]
Based on experimentation, it seems that all types are automatically exported, but you need at least one explicit `export` to turn the `d.ts` into a module exporting one.

**Comment by andy-ms** [comment]
We actually [lint](https://github.com/Microsoft/dtslint/blob/master/docs/strict-export-declare-modifiers.md) that type definitions should `export` explicitly but that package is not well linted.
