### ISSUE TITLE
Property decorator expression cannot access target property value

### ISSUE THREAD

**Issue by rolandjitsu** [Microsoft/TypeScript#19609]
**TypeScript Version:**  2.5.3

**Code**

```ts
class FooWithGet  {
    get host(): string {
        return this.options.host;
    }

    @GET('/test')
    bar: any;

    constructor(private options: any) {
        // this evaluates to the proper value
        console.log('HOST from ctor', this.host)
    }
}

export function GET(route: string): PropertyDecorator {
    return function (target: any, key: string | symbol): void {
        extendObject(target, key, {
            get(params?: any) {
                // this throws because in target.host, this.options is undefined
                console.log('HOST from decorator', target.host);
            }
        });
    };
}

export function extendObject(target: {[key: string]: any}, key: string | symbol, method: object): void {
    const value = target[key];
    if (typeof value === 'object' && value !== null) {
        Object.defineProperty(target, key, {
            configurable: false,
            enumerable: true,
            writable: false,
            value: Object.assign(value, method)
        });
    } else {
        Object.defineProperty(target, key, {
            configurable: false,
            enumerable: true,
            writable: false,
            value: method
        });
    }
}

const foo = new Foo({host: 'localhost'});

foo.bar.get();
```

**Expected behavior:**
The value of `target.host` in the decorator expression should evaluate to the proper value.

**Actual behavior:**
`this.options`, if used from the decorator, is always undefined.

Also see [pen](https://codepen.io/anon/pen/xPGpgY?editors=0010#0).

**Comment by rolandjitsu** [comment]
Funny thing is, if I log `console.log('from getter', JSON.stringify(this))` inside the `get host() { ... }`, I can actually see the value I expect, but as soon as I log `this.options`, I get `undefined`.

**Comment by mhegazy** [comment]
`target` is the target of your decoration, which is the class prototype, and not the instance.

You might have better luck sharing this on StackOverflow. This is not a support forum, it is one for reporting compiler/language bugs and suggestions. 
If you believe you are running into a compiler bug, please share a minimal repro project that demonstrates the issue you are running into and why you believe this is a compiler bug and not a declaration file issue or library usage problem.

**Comment by rolandjitsu** [comment]
@mhegazy if that is the case, then why is the following working:
```ts
const host = 'some test';

class FooAlt  {
    get host(): string {
        return host;
    }

    @GET('/test')
    bar: any;
}
```

**Comment by rolandjitsu** [comment]
@mhegazy after you pointed out that `target` is the prototype object, not the instance, I managed to find a way to access the instance values. But I'd still like an explanation why it behaves the way it does when returning a global constant from the getter.

**Comment by mhegazy** [comment]
`this` in JS functions behaves like a parameter, it is bound at call time. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this for more information.

**Comment by rolandjitsu** [comment]
@mhegazy sure. But in the decorator I call `target.host`, not `this.host`:
```ts
export function GET(route: string): PropertyDecorator {
    return function (target: any, key: string | symbol): void {
        extendObject(target, key, {
            get(params?: any) {
                console.log('HOST from decorator', target.host);
            }
        });
    };
}
```

And the class it's applied to:
```ts
const host = 'some test';

class FooAlt  {
    get host(): string {
        return host;
    }

    @GET('/test')
    bar: any;
}
```

So there is no `this` there. Also, `target`, as you mentioned, is `FooAlt.prototype`, so the reason I actually got the proper value by using the global constant is because `FooAlt.prototype.host` evaluates to the global const.

Anyway, I'm closing this as it is not an issue indeed.
