### ISSUE TITLE
TS: code actions not properly localized

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#19611]
_From @bpasero on October 31, 2017 13:47_

Testing: https://github.com/Microsoft/vscode/issues/37182

It looks like part of the message is still english:

![image](https://user-images.githubusercontent.com/900690/32226993-534a1fb0-be4a-11e7-843e-2401203b7b8c.png)

_Copied from original issue: Microsoft/vscode#37286_

**Comment by mjbvz** [comment]
@bpasero I'm assuming you are talking about the `inner function in function` part, correct? What would be a more natural translation for this?

**Comment by bpasero** [comment]
@mjbvz yeah, so from `Nach inner function in function 'activate' extrahieren` the `... inner function in function...` is literally not translated.

**Comment by mhegazy** [comment]
//cc @danyeh

**Comment by josefhosek** [comment]
#19610 Linguistic feedback provided in this issue.

**Comment by janbaltus** [comment]
Fix implemented
