### ISSUE TITLE
Can't create an enum with a member named Infinity

### ISSUE THREAD

**Issue by jmatthiesen** [Microsoft/TypeScript#1961]
I'm working on updating the WinRT.d.ts on DefinitelyTyped, for Windows Store app development, and ran into an issue trying to create this enum which comes from the Windows APIs:

```ts
            enum ManualFocusDistance {
                Infinity = 0,
                Hyperfocal = 1,
                Nearest = 2
            }
```

The error is for the Infinity member: "Error	TS2452	An enum member cannot have a numeric name."

I can see where the error message is technically correctly, but I can't find any workaround to fix this issue (I tried wrapping a string around the identifier with no luck).

**Comment by danquirk** [comment]
Not really sure there's anything we can do here with the enum codegen we have. You may need to just use a series of constants.

**Comment by DanielRosenwasser** [comment]
We've had so much trouble with this. The problem is that when indexing an enum with a number, you should expect to get a string (or `undefined`) back; with ManualFocusDistance[0/1], it's clear what's happening.

**Comment by RyanCavanaugh** [comment]
We could allow numeric names in const enums?

**Comment by DanielRosenwasser** [comment]
I was thinking this as well - it seems like a weird inconsistency, even if it does sound pragmatic.

**Comment by CyrusNajmabadi** [comment]
@RyanCavanaugh We could potentially do that.  But we already support a flag stating that const enums should be preserved in the final output.  So you'd then have a problem if you had a const enum with numerical names, and had this flag.  I'd prefer that we not go down this route.  

In this case, i think the best thing to do would be to not use an enum here.  Just have module with exported variables.  i.e. 

```typescript
declare module ManualFocusDistance {
    export var Infinity;
    export var ...
}
```

You won't get the constant value inlining.  But i think that's fine anyways as the inlining is simply a nice-to-have, and not necessary for all these winrt APIs.
