### ISSUE TITLE
Strange translation of extract quick fix in TS

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#19610]
_From @dbaeumer on October 31, 2017 13:55_

Testing #37182 

<img width="470" alt="capture" src="https://user-images.githubusercontent.com/1931590/32227295-480c35b0-be4b-11e7-8ebc-402e0b03a329.png">

Very hard to understand. Better would be:

- Als lokale Function von 'foo' extrahieren
- Als globale Function im Module extrahieren

_Copied from original issue: Microsoft/vscode#37292_

**Comment by mhegazy** [comment]
@danyeh how do you want to track this translation issue?

**Comment by johnliu2016** [comment]
Working on this issue, both menus are runtime and translation was done without more context, 3 resources found in relation.

Extract to {0} in {1}
Extract to {0} in {1} scope
Extract to {0} in enclosing scope

**Comment by josefhosek** [comment]
Linguistic feedback:

SRC: Extract to {0} in {1}
OLD: Nach {0} in {1} extrahieren
**TGT: Als {0} nach {1} extrahieren**

SRC:Extract to {0} in {1} scope
OLD: Nach {0} in {1}-Bereich extrahieren
**TGT: Als {0} in {1}-Bereich extrahieren**

SRC: Extract to {0} in enclosing scope
OLD: Nach {0} in einschließenden Bereich extrahieren
**TGT: Als {0} in einschließenden Bereich extrahieren**

I also suggest changing "inner function" to "lokale Funktion" (local function) and "outer function" to "globale Funktion" (global function) in the strings that fill the variables.

**Comment by janbaltus** [comment]
Issue implenented
