### ISSUE TITLE
API for adding diagnostics inside Custom Transformer

### ISSUE THREAD

**Issue by jimkyndemeyer** [Microsoft/TypeScript#19615]
**TypeScript Version:**  2.5.3

First of all, thank you for TypeScript and for adding the Custom Transformer API. It has unlocked a lot of interesting use cases.

I'd like to suggest an addition to the API: Being able to add diagnostics while visiting nodes inside a transformer.

It appears there may have been some initial work on this:

```typescript
    interface TransformationResult<T extends Node> {
        /** Gets the transformed source files. */
        transformed: T[];
        /** Gets diagnostics for the transformation. */
        diagnostics?: Diagnostic[];
}
```

However, looking at the source code, the diagnostics are optional and not returned: https://github.com/Microsoft/TypeScript/blob/e2141ad4694c3dc4d93388d5ee0d8bb0c7cbaa84/src/compiler/transformer.ts#L162-L167

And I've been unable to find a way to create and add diagnostics, e.g. based on the transformation context.

My specific use case is to transform GraphQL queries inside tagged template literals to their corresponding abstract syntax trees (represented as TS object literals).

The GraphQL query might fail to parse or contain errors such as referencing unknown fragments, so ideally I'd like to signal these errors to the developer and the build pipeline.

**Comment by mhegazy** [comment]
We do not believe diagnostics belong to transformation. We have found that these two processes are rather detachable; for instance, in an editor all you care about is errors, where as on the commandine you care about both, in a web transpilation scenario, you only need the transform and not the diagnostics. In short, splitting the two is the right thing to do, and allows API users to query for separately.
The API allows for querying the checker for errors, and i would add additional pass to add any required diagnostics after that. that should be separate from the transform process. you can make assumptions in the transform that the users have been notified about the errors through a different channel.

**Comment by jimkyndemeyer** [comment]
Thanks for the quick reply.

Can you clarify how you would implement this "additional pass" to signal the errors?

**Comment by mhegazy** [comment]
If you are transforming the output i am assuming you are using the compiler API; since tsc does not support custom transforms. So before calling `program.emit`, do a full walk on every file, and generate diagnostics, and display them along with the output of `program.getSemanticDiagnostics`

**Comment by jimkyndemeyer** [comment]
I'm not using the compiler API directly. The transformation is configured as part of Awesome TypeScript Loader for WebPack: https://github.com/s-panferov/awesome-typescript-loader/blob/cda6cb2d6863890b5bf426cf7d05011315c7d743/src/checker/runtime.ts#L170

So that's a no-go unfortunately, since I don't control that part of the emit phase: https://github.com/s-panferov/awesome-typescript-loader/blob/cda6cb2d6863890b5bf426cf7d05011315c7d743/src/checker/runtime.ts#L457-L458

Looking at the code for the TS emitter, diagnostics are managed very close to invoking the transformers: 
https://github.com/Microsoft/TypeScript/blob/7dfd6c7e20e7f73153fdc838d3a7a56b51f75123/src/compiler/emitter.ts#L82-L95

Would it really be a bad API design decision to allow the transformers to return a diagnostics collection that is concatenated onto the "emitterDiagnostics". It has the following benefits:

- WebPack build setups, like with Awesome TS loader, can be used out of the box to transform and report errors. This is a huge win in terms of reduced build-setup complexity for API consumers.
- There's no need to implement another pass, which costs performance. I'm trying to keep the incremental build delays with WebPack down for our developers.

Again, I'm new to the compiler API, so I might be biased by my use case here. But I do see this potential change as adding flexibility and supporting more powerful use cases, so  I hope you'll consider this.

Thanks for taking the time.

**Comment by mhegazy** [comment]
> I'm not using the compiler API directly. The transformation is configured as part of Awesome TypeScript Loader for WebPack

consider asking for a new feature from the loader.

> Looking at the code for the TS emitter, diagnostics are managed very close to invoking the transformers:

they are. they just have different lifespans. the basic concept here is you do not need to emit a program to know what errors it has.

> There's no need to implement another pass, which costs performance. I'm trying to keep the incremental build delays with WebPack down for our developers.

Your users in the IDE do not need to emit their program just to know they had a typo. think if you had to always emit the full program just to know that you had a syntax error.. that would make the IDE experience horrible.

**Comment by jimkyndemeyer** [comment]
Let me clarify the setup I'm looking for.

We already have an IntelliJ IDEA plugin that displays GraphQL errors as you type inside tagged template literals, but that's no guarantee that the project as a whole contains valid GraphQL.

I'm not trying to slow down the IDE experience by involving the emitter, I'm simply trying to ensure that our build fails on our CI server and in WebPack during development when there's invalid GraphQL somewhere in our TypeScript code inside a tagged template literal.

We can to do this today using Facebook's Babel Relay plugin, but are now looking for the same functionality with a TypeScript-only WebPack build pipeline.

What is the recommend way of dealing with this using TypeScript?

Thanks.

**Comment by mhegazy** [comment]
> We already have an IntelliJ IDEA plugin that displays GraphQL errors as you type inside tagged template literals, but that's no guarantee that the project as a whole contains valid GraphQL.

So you already have a way to query for errors in a file. why not add that in your build as a plugin? that will be a feature request for your build driver, in this case typescript loader. the loader is the one that queries for the semantic diagnostics from the compiler, and decides to fail the build. the typescript compiler (or tsc.js) is not involved in this process at all. the loader uses the API to get errors, and has full control to choose to fail the build or not. 
The loader calls your transform to do some work, it should call you to get errors as well.. but that is a hook they have to support.
internally you could decide to cache state to avoid doing the work twice, but that is an implementation detail.

Now for your question, why can not transforms return errors? cause that is architecturally not current. different users of the API care about different parts. instead of lumping them together, split them, and let each user choose what to do.. this is how we do it in the commandline compiler, tsc.js, https://github.com/Microsoft/TypeScript/blob/dcc1f1497f3f7c3552e97cbb5a419d52a3f9eaad/src/compiler/tsc.ts#L165-L186

first query for errors, show them, then get the output. I am not saying you can not have errors, you just have to split the errors from the process of generating outputs.

**Comment by jimkyndemeyer** [comment]
Thank you for the detailed replay. And for TypeScript :)

I will look into a solution based on your recommendations.
