### ISSUE TITLE
Chinese characters are repeated in localized diagnostics

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#19616]
```
> tsc --locale zh-CN --help
版版本本 2.6.1
语语法法: tsc [选选项项] [文文件件 ...]

示示例例: tsc hello.ts
    tsc --outFile file.js file.ts
    tsc @args.txt
```

**Comment by mhegazy** [comment]
Seems to be working fine for me on VSCode terminal though.. seems to be an issue specific to your terminal

**Comment by weswigham** [comment]
@mhegazy Same:
![image](https://user-images.githubusercontent.com/2932786/32248423-e3df4a3a-be42-11e7-970a-7c1b3a8bfed7.png)

**Comment by DanielRosenwasser** [comment]
It's a ConEmu bug https://github.com/Maximus5/ConEmu/issues/945
