### ISSUE TITLE
Property missing in type 'Readonly<any>'

### ISSUE THREAD

**Issue by ajaska** [Microsoft/TypeScript#19624]
**TypeScript Version:**  2.6.1, 2.7.0-dev.20171031
(verified working in 2.5.3)

**Code**

```ts
declare var anything: Readonly<any>
let x: Readonly<{ p: number }> // or let x: { p: number }
x = anything
```
(tested on TS Playground)

**Expected behavior:**
No errors

**Actual behavior:**
```
Type 'Readonly<any>' is not assignable to type 'Readonly<{ p: number; }>'.
Property 'p' is missing in type 'Readonly<any>'.
```

This is particularly painful because we are converting a JS/React codebase to typescript, so some prop types are declared as `any`, and thus become `Readonly<any>`

**Comment by mhegazy** [comment]
`Readonly` is a mapped type. it is a type transformation that happens on the input, in this case `any`. so `Readonly<any>` is equivalent to `{ readonly [x: string]: any };`. that is not assignable to `{readonly p: number}`, since this type has a required property `p`. Can you share more context, maybe there is something else we can do here to address the issues you are running into.

**Comment by ajaska** [comment]
Sure! Thanks for looking at this.

To give some context, we're using React with Redux, and have some containers (i.e. Redux state-injectors) that are Typescript and some wrapped components that are Javascript. We have a `.d.ts` definition file for the wrapped Javascript components, that declare the components as `React.Component<any, any>`.

Here's some copy-pastable sample code that works in the playground, and gives the error in 2.6.1 but not 2.5.3.

```ts
// react.ts
// Massively simplified version of react
class Component<P> {
    props: Readonly<P>;
    constructor(props?: P) {}
}
interface ComponentClass<P = {}> {
    new(props?: P, context?: any): Component<P>
}

// react-redux.ts
// Massively simplified version of redux-react's connect
declare var connect: (component: ComponentClass<OwnProps & StateProps>) => ComponentClass<OwnProps>;

// my-component.js
// Declaration of a Javascript "React" component, that hasn't been typed yet
class MyComponent extends Component<any> {};

// my-container.ts
// Uses react-redux's connect function
interface OwnProps {
    a: string
}
interface StateProps {
    b: number
}

let container = connect(MyComponent)
```

This results in the error:
```
TS2345: Argument of type 'typeof MyComponent' is not assignable to parameter of type 'ComponentClass<OwnProps & StateProps>'.
  Type 'MyComponent' is not assignable to type 'Component<OwnProps & StateProps>'.
    Types of property 'props' are incompatible.
      Type 'Readonly<any>' is not assignable to type 'Readonly<OwnProps & StateProps>'.
        Property 'a' is missing in type 'Readonly<any>'.
```

**Comment by SamuelBeliveau** [comment]
I had a similar issue and upgrading to a more recent react release (15.6) fixed it for me.
