### ISSUE TITLE
'Install xyz' QuickFix not properly translated

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#19626]
_From @chrmarti on October 31, 2017 22:1_

- VSCode Version: Code - Insiders 1.18.0-insider (8dfa696a1eb6ff67eb68925ddaa9e83d3c56b791, 2017-10-31T16:36:35.429Z)
- OS Version: Linux x64 3.13.0-108-generic
- Extensions: none
---

Testing #37182

Steps to Reproduce:

1. `code --locale=de`

![image](https://user-images.githubusercontent.com/9205389/32251009-5340f6e0-be4c-11e7-86d2-73365053dc8c.png)

_Copied from original issue: Microsoft/vscode#37352_

**Comment by mjbvz** [comment]
Tested with TS 2.6.1. Confirmed that TS error messages are in german but the fix itself is still in english

**Comment by mhegazy** [comment]
The name of this quickfix is not localizable at the moment. @andy-ms we need to make this text a diagnostic message so that it is localized.

**Comment by mhegazy** [comment]
We still need to wait on the localized messages for this to light up.
