### ISSUE TITLE
Do not see code actions to extract an expression to variable

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#19625]
_From @sandy081 on October 31, 2017 13:32_

Testing #37185

I have the following snippet

```javascript
// @ts-nocheck
var a = 1;
var b = 2;
var newLocal_0 = 3;
console.log(a + b * nwLocal);
```

I highlighted `a + b` and I do not see any code actions

_Copied from original issue: Microsoft/vscode#37281_

**Comment by mjbvz** [comment]
Tested with TS 2.6.1

My guess is that this has something to do with operator precedence. Change the `+` to a `*` does allow `a * b` to be extracted

**Comment by mhegazy** [comment]
> My guess is that this has something to do with operator precedence. Change the + to a * does allow a * b to be extracted

yup. the parser will parse this as a `( a + ( b * newLocal ) )`. just extracting `a + b` will give the expression a different meaning than what it has now.
