### ISSUE TITLE
npm bugs ng2-asp-core

### ISSUE THREAD

**Issue by Sami-L** [Microsoft/TypeScript#19627]
**npm bugs ng2-asp-core**

This is the first time I post here, so please feel free to correct me with my imperfections in the way of submitting and formatting ;)

While trying to compile my Angular project I got the following error:

> ERROR in ./node_modules/@angular/http/@angular/http.es5.js
> Module not found: Error: Can't resolve 'rxjs/operator/share' in 'C:\MyApp\node_modules\@angular\c
> ore\@angular'
>  @ ./node_modules/@angular/core/@angular/core.es5.js 9:0-44
>  @ ./ClientApp/main.ts
>  @ multi ./ClientApp/main.ts

**TypeScript Version:**  2.5.3

and here is the npm-debug log:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.10.10
3 info using node@v6.11.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle ng2-asp-core@0.0.0~prebuild: ng2-asp-core@0.0.0
6 silly lifecycle ng2-asp-core@0.0.0~prebuild: no script for prebuild, continuing
7 info lifecycle ng2-asp-core@0.0.0~build: ng2-asp-core@0.0.0
8 verbose lifecycle ng2-asp-core@0.0.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle ng2-asp-core@0.0.0~build: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;..............etc ......
10 verbose lifecycle ng2-asp-core@0.0.0~build: CWD: C:\MyApp
11 silly lifecycle ng2-asp-core@0.0.0~build: Args: [ '/d /s /c', 'webpack' ]
12 silly lifecycle ng2-asp-core@0.0.0~build: Returned: code: 2  signal: null
13 info lifecycle ng2-asp-core@0.0.0~build: Failed to exec build script
14 verbose stack Error: ng2-asp-core@0.0.0 build: `webpack`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:920:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
15 verbose pkgid ng2-asp-core@0.0.0
16 verbose cwd C:\MyApp
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
19 error node v6.11.3
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error ng2-asp-core@0.0.0 build: `webpack`
22 error Exit status 2
23 error Failed at the ng2-asp-core@0.0.0 build script 'webpack'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the ng2-asp-core package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs ng2-asp-core
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls ng2-asp-core
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

Any thoughts ?

**Comment by mhegazy** [comment]
you might have better luck posting this on StackOverFlow or on the angular issue tracker.

**Comment by Sami-L** [comment]
Thank you @mhegazy, do you mean I would have better luck if I move this post to angular/angular or StackOverflow ?

**Comment by mhegazy** [comment]
https://github.com/angular/angular/issues

**Comment by Sami-L** [comment]
@mhegazy submitted here[https://github.com/angular/angular/issues/20079](url)
