### ISSUE TITLE
Missing doc comments in completion in VS

### ISSUE THREAD

**Issue by amcasey** [Microsoft/TypeScript#19621]
It looks like https://github.com/Microsoft/TypeScript/pull/19496 (which appears to have shipped in 2.6.1) might have broken completion details in VS.  Since VS passes only a name, rather than a CompletionEntryIdentifier, the resulting CompletionEntryDetails contains an empty body.  The result is that (e.g.) doc comments are not shown for the selected item in the completion list.

**Comment by mhegazy** [comment]
@andy-ms we need to make sure the API works without a source field.

**Comment by andy-ms** [comment]
Should be fixed by #19687. @amcasey Can you confirm?

**Comment by amcasey** [comment]
I believe it will still be an issue for clients that set the new flag but don't pass a source, but I would argue that they're using the API incorrectly and the resulting behavior is acceptable.
