### ISSUE TITLE
Spread operator with minimal amount of work

### ISSUE THREAD

**Issue by NN---** [Microsoft/TypeScript#19637]
Spread operator assigns all properties from source object to the destination.
Is there a syntax to assign only relevant properties according to the type ?

Sample:
```ts
type B = { x:number; y: number; }

const a = {x:1,y:2,z:3};

const  b: B = {...a}; // b.z is also copied

// Ask to copy only 'B' properties
const b2: B = B{...a};
// Translates to
const b2 = { x:a.x, y:a.y }; // b.z is undefined
```

**Comment by andy-ms** [comment]
No, we don't do type-based emit. See the [design goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals). You'll have to define a `pick` function.
```ts
export function pick<T, K extends keyof T>(obj: T, keys: ReadonlyArray<K>): Pick<T, K> {
    const out: Pick<T, K> = {} as any;
    for (const key of keys) {
        out[key] = obj[key];
    }
    return out;
}
```

**Comment by NN---** [comment]
@andy-ms I can try with mapped types. The question was about language feature. Thanks.
