### ISSUE TITLE
enum compile error

### ISSUE THREAD

**Issue by athinboy** [Microsoft/TypeScript#19631]
**TypeScript Version:**  2.5.3

**Code**

	export enum DesignItemType {
		dataitem, 
		custom, 
		table, 
		column 
	}
	export class DesignItem {		 
		public templateiItemType: DesignItemType = DesignItemType.dataitem;

	}
	export class Column extends DesignItem {}
	export class Table extends DesignItem {}

			let designitem:DesignItem;
			let design_column:Column;
			let design_table:Table;			 

		        let item:any;

					designitem=JSON.parse( item);
					if(designitem.templateiItemType!=DesignItemType.column){
						design_column=JSON.parse( item);
					} else{
						if(designitem.templateiItemType == DesignItemType.table){
						     design_table=JSON.parse( item);
					        }else{
						      this.prt_item_list.push(designitem);
					        }
					
					} 

error TS2365: Operator '==' cannot be applied to types 'DesignItemType.column' and 'DesignItemType.table'.

          designitem = JSON.parse(item);
          if (designitem.templateiItemType != DesignItemType.column) {
            design_column = JSON.parse(item);
          }
          if (designitem.templateiItemType == DesignItemType.table) {
            design_table = JSON.parse(item);
          }
          this.prt_item_list.push(designitem);

compile ok!

**Comment by andy-ms** [comment]
The second `if` is inside an `else` block of `designitem.templateiItemType!=DesignItemType.column`. So inside the `else` block, `designitem.templateiItemType` is `DesignItemType.column`, otherwise control flow wouldn't reach that position. So testing `designitem.templateiItemType == DesignItemType.table` is correctly an error.
