### ISSUE TITLE
Storing Namespace in variable in typescript not working

### ISSUE THREAD

**Issue by Nanda-Nandan** [Microsoft/TypeScript#19647]
I have a typescript file which directly used Backbone. But I want to change it use own version of Backbone. export var ownBackbone :typeof Backbone = Backbone.noConflict();

export class UserContainerView extends ownBackbone .View {
public currentView;
public hasChanges;
collection: ownBackbone.Collection;
constructor(options: any) {
super();
this.collection = options.collection;
this.$el = options.el;
}

initialize(options: any) {
}

close() {
}
}

it throwing error at Build cant find name ownBackbone however the intellisense is not showing error while accessing ownBackbone.View

**Comment by andy-ms** [comment]
Could you provide a complete example?
It seems like the references to `ownBackbone` as a type should show as errors in the editor, because you declared a *variable* and not a namespace. In order to use types from backbone you should use the original Backbone definition; just make sure to only use it as a type and it won't actually be imported at runtime.

**Comment by Nanda-Nandan** [comment]
yes actually it is referencing backbone definition file for typescript .So typeof Backbone is not raising error.
If I am using Backbone in case of ownBackbone it is working fine
export class UserContainerView extends Backbone.View {
public currentView;
public hasChanges;
collection: Backbone.Collection;
constructor(options: any) {
super();
this.collection = options.collection;
this.$el = options.el;
}

initialize(options: any) {
}

close() {
}
}

the above code working fine 
but if i am storing in a variable like below with using type as any then it is raising error.

export var ownBackbone :any = Backbone;
export class UserContainerView extends ownBackbone .View {
public currentView;
public hasChanges;
}


Note:-Backbone is a  module  here
Backbone.d.ts:-

declare module Backbone {}
declare module "backbone" {
    export = Backbone;
}

**Comment by andy-ms** [comment]
The problem is that you can't do `collection: ownBackbone.Collection;` if `ownBackbone` is a `var`. A `var` can't have a type associated with it, only a namespace can. So when referencing a type you will still have to use `Backbone.Collection`.

**Comment by Nanda-Nandan** [comment]
Thanks,it worked fine,closing the issue
