### ISSUE TITLE
Can't use `is` type asserting function as predicate parameter

### ISSUE THREAD

**Issue by timm-gs** [Microsoft/TypeScript#19642]
**TypeScript Version:**  2.5.3 and 2.7.0-dev.20171101

**Code**

```ts
type T1 = { t: 1 };
type T2 = { t: 2 };

function isT1(x: any): x is T1 {
    return x.t === 1;
}

function isT2(x: any): x is T2 {
    return x.t === 2;
}

function f(p: typeof isT1 | typeof isT2) {
    
} 

f(isT1);
f(isT2); // fails
```

[Playground link](http://www.typescriptlang.org/play/#src=type%20T1%20%3D%20%7B%20t%3A%201%20%7D%3B%0D%0Atype%20T2%20%3D%20%7B%20t%3A%202%20%7D%3B%0D%0A%0D%0Afunction%20isT1(x%3A%20any)%3A%20x%20is%20T1%20%7B%0D%0A%20%20%20%20return%20x.t%20%3D%3D%3D%201%3B%0D%0A%7D%0D%0A%0D%0Afunction%20isT2(x%3A%20any)%3A%20x%20is%20T2%20%7B%0D%0A%20%20%20%20return%20x.t%20%3D%3D%3D%202%3B%0D%0A%7D%0D%0A%0D%0Afunction%20f(p%3A%20typeof%20isT1%20%7C%20typeof%20isT2)%20%7B%0D%0A%20%20%20%20%0D%0A%7D%20%0D%0A%0D%0Af(isT1)%3B%0D%0Af(isT2)%3B)

**Expected behavior:**
It compiles

**Actual behavior:**
 Fails to compile:

```
Argument of type '(x: any) => x is T2' is not assignable to parameter of type '(x: any) => x is T1'.
  Type predicate 'x is T2' is not assignable to 'x is T1'.
    Type 'T2' is not assignable to type 'T1'.
      Types of property 't' are incompatible.
        Type '2' is not assignable to type '1'
```

**Comment by andy-ms** [comment]
Duplicate of #17757
