### ISSUE TITLE
Type inference for lambda in ?: operator

### ISSUE THREAD

**Issue by NN---** [Microsoft/TypeScript#1964]
Will this scenario be supported in the future ?

```typescript
function f(x: string) {
	return x;
}

var q = true ? f : x => ""; // x is typed as 'any'

var w = true ? f : (x: string) => ""; // OK
```

**Comment by danquirk** [comment]
What scenario are you asking for exactly? That x is implicitly typed as string? By what rule? There's no reason to believe you intend for both sides of the conditional to have identical types.

**Comment by NN---** [comment]
Actually I am willing a more complicated type inference in TypeScript with this scenario supported.

**Comment by RyanCavanaugh** [comment]
This would be guessing, not inference.

There is already a contextual type applied from the ternary operator; having two potential contextual type sources would be very confusing.

**Comment by NN---** [comment]
Well, yes it would make things more complicated, but the code would require less typing. meaning simpler conversion from ES to TS.

**Comment by danquirk** [comment]
It's not about complication, it's about correctness. 

```ts
var q = something ? x => x + 1 : y => "hello " + y;
```
you want y typed as number because x is? There's simply no reason to believe that's the programmer's intention here. In fact there are very good reasons to believe y absolutely should not be the same type as x here.

**Comment by NN---** [comment]
In this case there is ambiguity and should be compiler error.

**Comment by danquirk** [comment]
It's not ambiguous, it's perfectly reasonable for someone to write JS/TS with different types coming out of different branches of a conditional. It can be represented fairly simply with either ```any``` or union types. We've had far more requests for features to model this kind of pattern (ex union types) than requests to disallow it without explicit type annotations.
