### ISSUE TITLE
Idea: Infer types / parameters from runtime (V8 debugger/inspector protocol)

### ISSUE THREAD

**Issue by niieani** [Microsoft/TypeScript#19641]
Given the new ["infer parameters from usage"](https://msdnshared.blob.core.windows.net/media/2017/10/inferFromUsageJSdoc2.mp4) functionality, it would seem doable to do something similar like "infer parameters from runtime/debugger", especially in environments like VSCode, which tightly integrate a debugger.

In runtime you get most of the information to generate pretty good types, at least for a start, so... why not? This would be a massive help in migrating JavaScript to TypeScript.

Also, V8 has just recently introduced `takeTypeProfile` to the inspector protocol, that could be used to leverage just that. There's an example usage here: https://github.com/fhinkel/type-profile.

**Comment by andy-ms** [comment]
https://github.com/Microsoft/dts-gen attempts to do something like this, although it doesn't integrate with the editor.

**Comment by mhegazy** [comment]
You can implement some of these features in a [language service plugin](https://github.com/Microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin) today. would love to see someone experiment with that.

**Comment by weswigham** [comment]
`dts-gen`'s functionality is now integrated into the compiler with #26588, so I think we've done this.
