### ISSUE TITLE
Passing functions as arguments and type checking

### ISSUE THREAD

**Issue by PFight** [Microsoft/TypeScript#19646]
**TypeScript Version:**  Version 2.7.0-dev.20171101

**Code**

[Code in playground]( https://www.typescriptlang.org/play/#src=interface%20A%20%7B%20a%3A%20number%3B%20%7D%0D%0Ainterface%20B%20extends%20A%20%7B%20b%3A%20string%3B%20%7D%3B%0D%0A%0D%0Ainterface%20Ctor%3CT%3E%20%7B%0D%0A%20%20new(p%3A%20T)%3A%20any%0D%0A%7D%0D%0Atype%20Func%3CT%3E%20%3D%20(p%3A%20T)%20%3D%3E%20void%3B%0D%0Atype%20FuncA%20%3D%20(p%3A%20A)%20%3D%3E%20void%3B%0D%0A%0D%0Afunction%20testCtor%3CT%3E(ctor%3A%20Ctor%3CT%3E)%20%7B%7D%0D%0Afunction%20testFunc%3CT%3E(func%3A%20Func%3CT%3E)%20%7B%7D%0D%0Afunction%20testFuncNoTpl(func%3A%20FuncA)%20%7B%7D%0D%0Aclass%20SomeClassB%20%7B%0D%0A%20%20constructor(hoi%3A%20B)%20%7B%20%20%7D%0D%0A%7D%0D%0Afunction%20SomeFuncB(p%3A%20B)%20%7B%7D%0D%0A%0D%0Alet%20a%3A%20A%3B%0D%0Anew%20SomeClassB(a)%3B%20%2F%2F%20OK%2C%20Error%20%22A%20is%20not%20assignable%20to%20B%22%0D%0AtestCtor%3CA%3E(SomeClassB)%3B%20%2F%2F%20No%20error%3F%0D%0ASomeFuncB(a)%3B%20%2F%2F%20OK%2C%20Error%20%22A%20is%20not%20assignable%20to%20B%22%20%0D%0AtestFunc%3CA%3E(SomeFuncB)%3B%20%2F%2F%20No%20error%3F%0D%0Alet%20func%3A%20Func%3CA%3E%20%3D%20SomeFuncB%3B%20%2F%2F%20No%20error%3F%0D%0AtestFuncNoTpl(SomeFuncB)%3B%20%2F%2F%20No%20error%3F%0D%0AtestFunc%3Cnumber%3E(SomeFuncB)%3B%20%2F%2F%20Ok%2C%20Error%20%22number%20is%20not%20assignable%20to%20B%22)

**Expected behavior:**

When function has not compatible type arguments, compiler should throw an error.

**Actual behavior:**

No error throwed in some cases.

**Comment by andy-ms** [comment]
Enabling `--strictFunctionTypes` should give you those errors.

**Comment by PFight** [comment]
Thanks, --strictFunctionTypes really brings the errors.
