### ISSUE TITLE
Enable quick info when hovering over `function` or `=>`

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#19653]
**TypeScript Version:**  2.7.0-dev.20171101

**Code**

```ts
foo(function() {});
foo(() => {});
```

**Expected behavior:**

We should be able to get quick info on the function without giving it a name.

**Actual behavior:**

Only way to get quick info is to add a name and hover over the name.

**Comment by mhegazy** [comment]
We should enable quickinfo on the `function` keyword, like we do with `default` today. possibly the `=>` in the case of a lambda.

**Comment by mhegazy** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/2736
