### ISSUE TITLE
lib.d.ts has a wrong definition of HeadersInit

### ISSUE THREAD

**Issue by timocov** [Microsoft/TypeScript#19656]
**TypeScript Version:**  2.6.1 (and 2.7.0-dev.20171101)

**Code**

https://www.typescriptlang.org/play/index.html#src=fetch(%27%2Fsome-url%27%2C%20%7B%20headers%3A%20%7B%20%27Some-Header-Name%27%3A%20%27Value%27%20%7D%20%7D)%3B

```ts
fetch('/some-url', { headers: { 'Some-Header-Name': 'Value' } });
```

**Expected behavior:**
No errors.

**Actual behavior:**
Error:
```
Object literal may only specify known properties, and ''Some-Header-Name'' does not exist in type 'Headers | string[][]'.
```

According [the spec](https://fetch.spec.whatwg.org/#requestinit) `RequestInit` may has `headers` prop as [`HeadersInit`](https://fetch.spec.whatwg.org/#typedefdef-headersinit) type which is
```ts
type HeadersInit = [string, string][] | { [key: string]: string };
```
But currently we have `Headers` instead of map object in [`RequestInit.headers`](https://github.com/Microsoft/TypeScript/blob/master/lib/lib.dom.d.ts#L796) (the code above works fine in all browsers (including Edge)).

Also [`HeadersInit`](https://github.com/Microsoft/TypeScript/blob/master/lib/lib.dom.d.ts#L14774) is not used in [`RequestInit`](https://github.com/Microsoft/TypeScript/blob/master/lib/lib.dom.d.ts#L792).

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by mikemonji** [comment]
Instead of:

fetch('/some-url', { headers: { 'Some-Header-Name': 'Value' } });

Try:

let headers: any = { headers: { 'Some-Header-Name': 'Value' } };

fetch('/some-url', headers);
