### ISSUE TITLE
Restarting server changes tabbing for open files

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/TypeScript#19652]
When I run the command: `TypeScript: Restart TS Server` any file that I have open it changes my tabs from `2` spaces to `4` spaces after I save the file.

**TypeScript Version:**  2.5.3

```ts
function abc123(){
  console.log('Hello World')
}
```

**Expected behavior:**

When restarting the server files that are open, the tabbing should not change when the file gets saved.

**Actual behavior:**

When restarting the server tabs get changed from `2` spaces to `4` spaces when the file gets saved.

I had to press save a few times here but still does this:

![reformat](https://user-images.githubusercontent.com/1571806/32283497-7eef1e92-bef2-11e7-8df5-9e90341d63d6.gif)

**Comment by andy-ms** [comment]
This sounds like a vscode issue. Are you saying that the file content is different after restarting?

**Comment by TheColorRed** [comment]
@andy-ms I added an animated gif

**Comment by andy-ms** [comment]
That's interesting... looks like there's a delay in between the restart and the formatting change.
TypeScript shouldn't be formatting your code on startup so something is up.
Could you try reproducing this with minimal vscode settings and no extensions installed?

**Comment by TheColorRed** [comment]
I just started VSCode: `code . --disable-extensions`

Then saved the same file, and it re-formatted this time on the first save (no delay).

**Comment by andy-ms** [comment]
You might have a setting to format on save? I didn't think restarting tsserver would save the file though.

**Comment by TheColorRed** [comment]
I commented out all settings except for `"editor.formatOnSave": true`, turning it off also reproduces the same effect.

![reformat2](https://user-images.githubusercontent.com/1571806/32284299-d5d8a9ba-bef4-11e7-9760-4070a3f81a42.gif)

**Comment by andy-ms** [comment]
Could you check vscode's spaces setting in the lower-right?

**Comment by TheColorRed** [comment]
It is set to `2`:

![screenshot](https://user-images.githubusercontent.com/1571806/32284468-544c371c-bef5-11e7-8326-1633bb35ebe3.png)

**Comment by andy-ms** [comment]
Huh.
Could you try using `typescript@next` and `code-insiders` and report the tsserver log? (`TypeScript Open TS Server Log`)

**Comment by andy-ms** [comment]
I did successfully reproduce this using `code` and its default installed version of TypeScript (`2.5.3`). But I couldn't reproduce with `code-insiders` and `typescript@next`.

**Comment by TheColorRed** [comment]
I wasn't able to reproduce using `code-insiders` and TypeScript `2.6.1`

**Comment by TheColorRed** [comment]
I also wasn't able to reproduce it using `code-insiders` and TypeScript `1.5.3`
