### ISSUE TITLE
RequestInit api change no longer compiles

### ISSUE THREAD

**Issue by vrachels** [Microsoft/TypeScript#19658]
using typescript 2.6.1

lib.dom.d.ts defines RequestInit with:
headers?: Headers | string[][];

(used to be 'any')

the headers as object option no longer works in ie fetch(file, { ... headers: { Accept: ....} })

see also #18073

**Comment by mhegazy** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/19656
