### ISSUE TITLE
TSServer outputs NPM warnings at startup

### ISSUE THREAD

**Issue by micbou** [Microsoft/TypeScript#19660]
Since TypeScript 2.6.1, TSServer outputs NPM warnings at startup (see actual behavior below). That's problematic since clients expect HTTP-like responses from TSServer stdout.

**TypeScript Version:**  2.7.0-dev.20171101

**Steps to reproduce**

```sh
npm -g install typescript@next
tsserver
```

**Expected behavior:**

No output.

**Actual behavior:**

The following lines are printed:
```
npm WARN 2.7 No description
npm WARN 2.7 No repository field.
npm WARN 2.7 No license field.
```

**Comment by andy-ms** [comment]
@micbou Check out `typescript@next` tomorrow and tell us if this is fixed for you.

**Comment by micbou** [comment]
I tried with TypeScript 2.7.0-dev.20171102 (I first deleted the `~/.cache/typescript` folder) and I am still getting the NPM warnings although the contents of `package.json` in `~/.cache/typescript/2.7` is
```json
{ "description": "", "repository": "", "license": "" }
```
