### ISSUE TITLE
JSDoc does not pick up type imported from foreign modules using require

### ISSUE THREAD

**Issue by KtorZ** [Microsoft/TypeScript#19678]
In the lights of #14056, the import of type defined by Classes seems to work fine from within a module (using local imports) but does not go beyond it. Therefore, where the following example works fine:

**TypeScript Versions:**  2.7.0-dev.20171102, 2.6.1

**Code**

*module: A, file: a.js*
```js
class Action { /* whatever */ }

module.exports = Action;
```
*module: A, file: b.js*
```js
const Action = require('./a');

/**
 * @param {Action} arg 
 */
function foo(arg) { /* whatever */ }
```
Here the type is picked up correctly in `b.js` and typescript works like a charm. However, if `A` is used as an installed dependency from another module:

*module B, file c.js*
```js
const Action = require('A/a');

/**
 * @param {Action} arg
 */
function bar(arg) { /* whatever */ }
```

**Actual behavior:**

Typescript complains with the following:

> error TS2304: Cannot find name 'Action'.

**Expected behavior:**

Is this an intended behavior or, should the type also be picked up? I don't see how and why using a module as a dependency should remove the initial behavior.

Thanks for the help :+1:

**Comment by andy-ms** [comment]
When it's from `node_modules` we probably aren't checking it at all, thus `Action` would just be a variable of type `any`. (You probably don't have `--noImplicitAny` set.)
Ideally the package `A` would have something on [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) to provide types.
You could also try increasing [`--maxNodeModuleJsDepth`](http://www.typescriptlang.org/docs/handbook/compiler-options.html) to pick up those files into the project, although that can slow build times.
