### ISSUE TITLE
Support `@const` JSDoc tag 

### ISSUE THREAD

**Issue by emilio-martinez** [microsoft/TypeScript#19672]
**TypeScript Version:** 2.5.3

**Code**

```ts
/**
 * @const {boolean} This constant is falsy
 */
export const MyFalsyConstant: boolean = false;
```

**Expected behavior:**

Type expression and comment should be separate for `@const` (http://usejsdoc.org/tags-constant.html) tags. See below for further explanation.

**Actual behavior:**

Parsing the above JSDoc (with help from tsutils which as far as I can see is just using Typescript parsing tools), I get the following node for the `@const` JSDoc tag.

```
NodeObject {
  pos: 1299,
  end: 1306,
  flags: 0,
  transformFlags: undefined,
  parent: 
   NodeObject {
     pos: 1292,
     end: 1368,
     flags: 0,
     transformFlags: undefined,
     parent: 
      NodeObject {
        pos: 1290,
        end: 1406,
        flags: 0,
        transformFlags: undefined,
        parent: [Object],
        kind: 208,
        decorators: undefined,
        modifiers: undefined,
        declarationList: [Object],
        jsDoc: [Object],
        _children: [Object] },
     kind: 275,
     tags: [ [Circular], [Object], pos: 1299, end: 1348 ],
     comment: undefined },
  kind: 276,
  atToken: TokenObject { pos: 1299, end: 1300, flags: 0, parent: undefined, kind: 57 },
  tagName: 
   IdentifierObject {
     pos: 1300,
     end: 1305,
     flags: 0,
     parent: undefined,
     escapedText: 'const' },
  comment: '{false} This constant is falsy' }
```

Destructuring the relevant `ts.JSDocTag` object (`const { typeExpression, comment } = tag`), I get the following:

```
typeExpression: `undefined`
comment: `{false} This constant is falsy`
```

My expectation would be for the type expression to be separate as outlined in http://usejsdoc.org/tags-constant.html

**Comment by mhegazy** [comment]
PRs welcomed.

**Comment by j-oliveras** [comment]
@mhegazy Maybe you want to add `help wanted` label to this issue (based on your previous comment).

**Comment by Kingwl** [comment]
I’d like to work on this.

**Comment by zachhardesty7** [comment]
has any progress been made on this issue? from what I can tell, it looks like #39768 was finished but closed.

**Comment by frank-dspeed** [comment]
This can be closed Typescript now Supports:

```js
export const CBLErrorDomainByCode = /** @type {const} */ ([, "LITE_CORE","POSIX","SQLITE","FLEECE","NETWORK","WEB_SOCKET"]);
```

**Comment by bjarkler** [comment]
I don't think this is fixed - can we reopen, @RyanCavanaugh? #39768 was closed without being merged, and the example in the previous comment uses the `@type` tag, not the `@const` tag which this issue is referring to.

**Comment by frank-dspeed** [comment]
@bjarkler i guess there is no real implementation ongoing with the @const JSDoc tag what now works is the so called typecasting to const so the same as in typescript with ``` as const ```

**Comment by GreenAsJade** [comment]
Note that the[ documentation for Typescript](https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html#unsupported-tags) points to this issue as being open on this tag.
