### ISSUE TITLE
Narrowed union types loosened within closures

### ISSUE THREAD

**Issue by myitcv** [Microsoft/TypeScript#19683]
_This could be a dup of #14748; they seem related_

**TypeScript Version:**  2.7.0-dev.20171102

**Code**

See in [playground](http://www.typescriptlang.org/play/index.html#src=class%20A%20%7B%20%0A%20%20%20%20name%3A%20string%3B%0A%7D%0Aclass%20B%20%7B%20%0A%20%20%20%20age%3A%20number%3B%0A%7D%0A%0Alet%20x%3A%20A%20%7C%20B%3B%0A%0Aif%20(x%20instanceof%20A)%20%7B%0A%20%20%20%20console.log(x.name)%3B%20%2F%2F%20ok%3A%20x%20has%20type%20A%0A%0A%20%20%20%20setTimeout(()%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20console.log(x.name)%3B%20%2F%2F%20**%20COMPILE%20ERROR%3A%20x%20has%20type%20A%20%7C%20B%20here%0A%20%20%20%20%7D)%3B%0A%7D%20else%20%7B%0A%20%20%20%20console.log(x.age)%3B%20%2F%2F%20ok%3A%20x%20has%20type%20B%20here%0A%0A%20%20%20%20setTimeout(()%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20console.log(x.age)%3B%20%2F%2F%20**%20COMPILE%20ERROR%3A%20x%20has%20type%20A%20%7C%20B%20here%0A%20%20%20%20%7D)%3B%0A%7D)

```ts
class A { 
    name: string;
}
class B { 
    age: number;
}

let x: A | B;

if (x instanceof A) {
    console.log(x.name); // ok: x has type A

    setTimeout(() => {
        console.log(x.name); // ** COMPILE ERROR: x has type A | B here
    });
} else {
    console.log(x.age); // ok: x has type B here

    setTimeout(() => {
        console.log(x.age); // ** COMPILE ERROR: x has type A | B here
    });
}
```

**Expected behavior:**

This should compile.

**Actual behavior:**

It does not compile

**Comment by andy-ms** [comment]
See #9998.
In this case I think the behavior is correct; `x` is mutable so it could be different by the time the timeout is called. You can fix this by using `const` instead of `let`.

**Comment by myitcv** [comment]
In my.situation (and indeed the repro) it is not possible for `x` to have been mutated, but I can see that in general case that's harder to work out definitively. Thanks for the `const` tip.
