### ISSUE TITLE
`PartialAll` or `PartialNested` proposal

### ISSUE THREAD

**Issue by leebenson** [Microsoft/TypeScript#19681]
I ran into a scenario today where an interface contained other/nested interfaces, and was being used as both an input and a return value.

On the way in, all data is optional. On the way out, all is required.

This is a perfect use case for `Partial`, but AFAIK, there's no built-in type that represents a _nested_ Partial, which is what I needed.

This is an easy fix, of course:

```ts
type PartialAll<T> = {
    [P in keyof T]?: PartialAll<T[P]>
};
```

Almost too simple to suggest it being a root type, perhaps, but since `Partial` is even simpler and has proven useful enough to include in TS proper, maybe there's some interest in nested root types?

e.g.

```ts
type ReadonlyAll<T> = {
    readonly [P in keyof T]: ReadonlyAll<T[P]>
}
```

**Note:**

Apologies if this relatively obvious feature has already been suggested/implemented/rejected. I read _Advanced Types_ in the docs prior to this and ran a search in both the PR and open issues for keywords like 'partial nested' and came up short.

**Comment by NN---** [comment]
There are already discussions about this.
Recursive readonly is a problem.
readonly number[] not equal to ReadonlyArray<number>

**Comment by aluanhaddad** [comment]
Yep, that's what flummoxed me with the typings for npm:deep-freeze.

We probably need filtered mapped types, which have been proposed, to get around it

**Comment by mhegazy** [comment]
Nested mapped types are expensive to validate. we would not want to have these in accessible in the default library. `Partial` seems to cover most scenarios, and you are welcome to define your own `PartialAll`. as for deep `Readonly` what @NN---  and @aluanhaddad noted is correct. we would rather address this with a type operator (https://github.com/Microsoft/TypeScript/issues/10725) or a conditional mapped type (https://github.com/Microsoft/TypeScript/issues/12424).

**Comment by niieani** [comment]
Here's a recursive readonly that follows inside Arrays: [Playground](https://www.typescriptlang.org/play/#src=type%20Example%20%3D%20%7B%0D%0A%20%20a%3A%20string%2C%0D%0A%20%20b%3A%20Array%3CExample%3E%2C%0D%0A%20%20c%3A%20number%2C%0D%0A%20%20d%3A%20Example%2C%0D%0A%7D%0D%0A%0D%0Adeclare%20var%20test%3A%20RecursiveReadonly%3CExample%3E%3B%0D%0A%2F%2F%20errors%20properly%3A%0D%0Atest.b%5B0%5D.b%5B0%5D.d.b%5B0%5D.a%20%3D%20''%0D%0Atest.b%5B0%5D.b%5B0%5D.d.b%5B0%5D.b%20%3D%20%5B%5D%0D%0Atest.b%5B0%5D.b%5B0%5D.d.b%5B0%5D.c%20%3D%203%0D%0Atest.b%5B0%5D.b%5B0%5D.d.b%5B0%5D.d%20%3D%20test%0D%0A%0D%0Adeclare%20var%20test2%3A%20RecursiveReadonly%3Cstring%3E%3B%0D%0Atest2%20%3D%20test2%20as%20string%0D%0A%0D%0Adeclare%20var%20test3%3A%20RecursiveReadonly%3Cnumber%3E%3B%0D%0Atest3%20%3D%20test3%20as%20number%0D%0A%0D%0Adeclare%20var%20test4%3A%20RecursiveReadonly%3CSet%3Cstring%3E%3E%3B%0D%0Atest4%20%3D%20test4%20as%20Set%3Cstring%3E%0D%0A%0D%0A%0D%0A%2F%2F%20definition%3A%0D%0Atype%20RecursiveReadonly%3CT%3E%20%3D%20If%3C%0D%0A%20%20IsArrayType%3CT%3E%2C%0D%0A%20%20MapArrayType%3CT%20%26%20List%3C%7B%7D%3E%3E%2C%0D%0A%20%20MapScalarOrObjectType%3CT%3E%0D%0A%3E%3B%0D%0A%0D%0Atype%20MapScalarOrObjectType%3CT%3E%20%3D%20If%3C%0D%0A%20%20IsScalarOrInstance%3CT%3E%2C%0D%0A%20%20T%2C%0D%0A%20%20MapObjectWithPossibleArrays%3CT%3E%0D%0A%3E%3B%0D%0A%0D%0Atype%20MapObjectWithPossibleArrays%3CT%3E%20%3D%20%7B%0D%0A%20%20readonly%20%5BP%20in%20keyof%20T%5D%3A%20If%3C%0D%0A%20%20%20%20IsArrayType%3CT%5BP%5D%3E%2C%0D%0A%20%20%20%20MapArrayType%3CT%5BP%5D%20%26%20List%3C%7B%7D%3E%3E%2C%0D%0A%20%20%20%20MapScalarOrObjectType%3CT%5BP%5D%3E%0D%0A%20%20%3E%0D%0A%7D%3B%0D%0A%0D%0Atype%20MapArrayType%3CArr%20extends%20List%3CT%3E%2C%20T%20%3D%20Arr%5B-1%5D%3E%20%3D%20Array%3C%0D%0A%20%20MapObjectWithPossibleArrays%3CT%3E%0D%0A%3E%3B%0D%0A%0D%0A%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%0D%0A%2F%2F%20generic%20utils%20(some%20from%20https%3A%2F%2Fgithub.com%2Ftycho01%2Ftypical%2F)%3A%0D%0Atype%20False%20%3D%20%220%22%3B%0D%0Atype%20True%20%3D%20%221%22%3B%0D%0Atype%20Bool%20%3D%20True%20%7C%20False%3B%0D%0Atype%20If%3CCond%20extends%20Bool%2C%20Then%2C%20Else%3E%20%3D%20%7B%201%3A%20Then%3B%200%3A%20Else%20%7D%5BCond%5D%3B%0D%0A%0D%0Atype%20Obj%3CT%3E%20%3D%20%7B%20%5Bk%3A%20string%5D%3A%20T%20%7D%3B%0D%0A%0D%0Atype%20And%3CA%20extends%20Bool%2C%20B%20extends%20Bool%3E%20%3D%20(%7B%201%3A%20%7B%201%3A%20%221%22%20%7D%20%26%20Obj%3C%220%22%3E%20%7D%20%26%20Obj%3C%0D%0A%20%20Obj%3C%220%22%3E%0D%0A%3E)%5BA%5D%5BB%5D%3B%0D%0A%0D%0Atype%20UnionHasKey%3CUnion%20extends%20string%2C%20K%20extends%20string%3E%20%3D%20(%7B%0D%0A%20%20%5BS%20in%20Union%5D%3A%20%221%22%0D%0A%7D%20%26%0D%0A%20%20Obj%3C%220%22%3E)%5BK%5D%3B%0D%0A%0D%0Atype%20Indeterminate%3CT%20extends%20string%3E%20%3D%20And%3C%0D%0A%20%20UnionHasKey%3CT%2C%20%220%22%3E%2C%0D%0A%20%20UnionHasKey%3CT%2C%20%221%22%3E%0D%0A%3E%3B%0D%0A%0D%0Atype%20Not%3CT%20extends%20Bool%3E%20%3D%20%7B%20%221%22%3A%20%220%22%3B%20%220%22%3A%20%221%22%20%7D%5BT%5D%3B%0D%0A%0D%0Atype%20Determinate%3CT%20extends%20Bool%3E%20%3D%20Not%3CIndeterminate%3CT%3E%3E%3B%0D%0A%0D%0Atype%20DefinitelyYes%3CT%20extends%20Bool%3E%20%3D%20And%3CT%2C%20Determinate%3CT%3E%3E%3B%0D%0A%0D%0Atype%20UnionContained%3CT%20extends%20string%2C%20U%20extends%20string%3E%20%3D%20DefinitelyYes%3C%0D%0A%20%20(%7B%20%5BP%20in%20U%5D%3A%20%221%22%20%7D%20%26%20Obj%3C%220%22%3E)%5BT%20%7C%20U%5D%0D%0A%3E%3B%0D%0A%0D%0Atype%20UnionEmpty%3CT%20extends%20string%3E%20%3D%20And%3C%0D%0A%20%20UnionContained%3CT%2C%20%22foo%22%3E%2C%0D%0A%20%20UnionContained%3CT%2C%20%22bar%22%3E%0D%0A%3E%3B%0D%0A%0D%0Atype%20UnionToObject%3CKeys%20extends%20string%3E%20%3D%20%7B%20%5BK%20in%20Keys%5D%3A%20K%20%7D%3B%0D%0A%0D%0Atype%20Keyed%3CT%3E%20%3D%20%7B%20%5BK%20in%20keyof%20T%5D%3A%20K%20%7D%3B%0D%0A%0D%0Atype%20KeyedSafe%3CT%3E%20%3D%20Keyed%3CT%3E%20%26%20Obj%3Cnever%3E%3B%0D%0A%0D%0Atype%20IntersectionUnions%3CBig%20extends%20string%2C%20Small%20extends%20string%3E%20%3D%20KeyedSafe%3C%0D%0A%20%20UnionToObject%3CSmall%3E%0D%0A%3E%5BBig%5D%3B%0D%0Atype%20UnionsOverlap%3CBig%20extends%20string%2C%20Small%20extends%20string%3E%20%3D%20Not%3C%0D%0A%20%20UnionEmpty%3CIntersectionUnions%3CBig%2C%20Small%3E%3E%0D%0A%3E%3B%0D%0A%0D%0Atype%20DiffUnion%3CT%20extends%20string%2C%20U%20extends%20string%3E%20%3D%20(%7B%20%5BP%20in%20T%5D%3A%20P%20%7D%20%26%0D%0A%20%20%7B%20%5BP%20in%20U%5D%3A%20never%20%7D%20%26%20%7B%20%5Bk%3A%20string%5D%3A%20never%20%7D)%5BT%5D%3B%0D%0A%0D%0Atype%20ObjectHasKey%3CO%20extends%20%7B%7D%2C%20K%20extends%20string%3E%20%3D%20UnionHasKey%3Ckeyof%20O%2C%20K%3E%3B%0D%0A%0D%0Atype%20ArrayPrototypeProperties%20%3D%20DiffUnion%3C%0D%0A%20%20keyof%20Array%3Cany%3E%2C%0D%0A%20%20%22toString%22%20%7C%20%22toLocaleString%22%0D%0A%3E%3B%0D%0Atype%20IsArrayType%3CT%3E%20%3D%20DefinitelyYes%3CObjectHasKey%3CT%2C%20ArrayPrototypeProperties%3E%3E%3B%0D%0A%0D%0A%2F**%0D%0A%20*%20false%20for%3A%20undefined%2C%20interfaces%0D%0A%20*%20true%20for%3A%20Array%2C%20boolean%2C%20number%2C%20string%2C%20Object%0D%0A%20*%2F%0D%0Atype%20IsScalarOrInstance%3CT%3E%20%3D%20ObjectHasKeySafe%3CT%2C%20%22valueOf%22%3E%3B%0D%0Atype%20ObjectHasKeySafe%3CO%2C%20K%20extends%20string%3E%20%3D%20UnionsOverlap%3Ckeyof%20O%2C%20K%3E%3B%0D%0A%0D%0Ainterface%20List%3CT%3E%20%7B%0D%0A%20%20readonly%20%5Bn%3A%20number%5D%3A%20T%3B%0D%0A%7D).
