### ISSUE TITLE
Empty constructors for TypedArrays are not allowed

### ISSUE THREAD

**Issue by ltetzlaff** [Microsoft/TypeScript#19680]
Typescript currently does not support empty constructors of TypedArrays, as in [mdn UInt8Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/UInt8Array), thx to [sindresorhus](https://github.com/sindresorhus/is/pull/28#discussion_r148431869) for pointing that out.

**TypeScript Version:**  2.7.0-dev.201xxxxx

**Code**

```ts
const x = new Uint8Array()
```

**Expected behavior:**
works
**Actual behavior:**
Error: Expected 1-3 arguments, but got 0.

**Comment by mhegazy** [comment]
This is an ES 2017 specific change, should go in a new file `src/lib/es2017.typedArrays.d.ts` and linked from https://github.com/Microsoft/TypeScript/blob/master/src/lib/es2017.d.ts.

**Comment by mhegazy** [comment]
PRs welcomed.

**Comment by mhegazy** [comment]
thanks @timocov!
