### ISSUE TITLE
Incorrect type inferred with early return 

### ISSUE THREAD

**Issue by Bibliofile** [Microsoft/TypeScript#19698]
When returning early from a function, types are not inferred correctly in functions defined later in the function. This occurs only with `strictNullChecks` turned on. [Playground](http://www.typescriptlang.org/play/#src=interface%20hasMethods%20%7B%0D%0A%20%20%20%20remove()%3A%20void%0D%0A%20%20%20%20getExports(key%3A%20string)%3A%20%7B%5Bkey%3A%20string%5D%3A%20any%7D%20%7C%20undefined%0D%0A%7D%0D%0A%0D%0Alet%20obj%3A%20hasMethods%20%3D%20%7B%0D%0A%20%20%20%20remove%3A%20()%20%3D%3E%20%7B%20%7D%2C%0D%0A%20%20%20%20getExports%3A%20()%20%3D%3E%20undefined%0D%0A%7D%0D%0A%0D%0A%3B(function%20()%20%7B%0D%0A%20%20%20%20let%20x%20%3D%20obj.getExports('test')%0D%0A%20%20%20%20if%20(!x)%20return%0D%0A%20%20%20%20%2F%2F%20No%20error%2C%20as%20expected%0D%0A%20%20%20%20x.test()%0D%0A%20%20%20%20%2F%2F%20Error%0D%0A%20%20%20%20obj.remove%20%3D%20()%20%3D%3E%20x.test()%0D%0A%7D())).

**TypeScript Version:**  typescript@2.6, typescript@2.7.0-dev.20171102

**Code**

```ts
interface hasMethods {
    remove(): void
    getExports(key: string): {[key: string]: any} | undefined
}

let obj: hasMethods = {
    remove: () => { },
    getExports: () => undefined
}

;(function () {
    let x = obj.getExports('test')
    if (!x) return
    // No error, as expected
    x.test()
    // Error, x might be undefined
    obj.remove = () => x.test()
}())
```

**Comment by andy-ms** [comment]
`x` is a mutable variable. Since `x` might be mutated at some point, we can't be sure that a reference to `x` in a callback will still have `x` defined.
In this case you're not actually mutating `x`, so use `const` instead.
