### ISSUE TITLE
Enum member used in computed property name leads to compile error when using outputted .d.ts file

### ISSUE THREAD

**Issue by dsherret** [Microsoft/TypeScript#19704]
**TypeScript Version:**  2.7.0-dev.20171102

**Code**

```ts
// test.ts
import * as ts from "typescript";

export const someVar = {
    [ts.SyntaxKind.SourceFile]: ""
};
```

Compile with: `tsc test.ts --declaration --module commonjs`

**Expected behavior:**

Expect the declaration file to export as it did in TS 2.5.3:

```typescript
export declare const someVar: {
    [key: number]: string;
};
```

...or at least throw a compile error when compiling with `--declaration`.

**Actual behavior:**

```typescript
export declare const someVar: {
    [ts.SyntaxKind.SourceFile]: string;
};
```

No compile error.

**Another example**

Here's another example that doesn't error with `--declaration`, even though I'm using a private name:

```typescript
// test.ts
enum MyEnum {
    member = 0
}

export const someVar = {
    [MyEnum.member]: ""
};

// output: test.d.ts (and no compile error)
export const someVar = {
    [MyEnum.member]: string
};
```

**Comment by weswigham** [comment]
This should be fixed in `master`, now that #15473 is merged.
