### ISSUE TITLE
suggestion:what about condition compile?

### ISSUE THREAD

**Issue by athinboy** [Microsoft/TypeScript#19705]
maybe it is mad idea!
i want  control whether to   insert  debug code like : window.console.info ,debugger!

**Comment by isiahmeadows** [comment]
@athinboy See #3538.

**Comment by DanielRosenwasser** [comment]
And #449 too - thanks @isiahmeadows!

Thanks for filing @athinboy, but please search the issue tracker in the future to make it easier for us to triage! 😃

**Comment by athinboy** [comment]
@DanielRosenwasser  thank!
