### ISSUE TITLE
Co-variant function return type check when assigning to a function that returns `void`

### ISSUE THREAD

**Issue by afroozeh** [Microsoft/TypeScript#19709]
**TypeScript Version:**  2.6.0

**Code**

```ts
interface A {
    a: number
}

let f: (n: number) => void;
let g: (n: number) => A;

f = g;
```

**Expected behavior:**
Error: Type 'A' is not assignable to type 'void'

**Actual behavior:**
No errors

I think typescript always checking return types of functions co-variantly. Is there an exception for functions with return type 'void'?

**Comment by ahejlsberg** [comment]
Yes, we explicitly have a rule that makes non-void returning function types assignable to void returning function types.

**Comment by afroozeh** [comment]
I think this behavior of TypeScript is OK for most cases since functions that take void-returning callbacks will not do anything with the return value. The only case that I find problematic is when passing an void-returning `async` callback to a function that accepts a void-returning callback, e.g.,`Array.forEach()`. A compiler warning would catch bugs about unhandled promises.

**Comment by RyanCavanaugh** [comment]
Addressed in FAQ https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-functions-returning-non-void-assignable-to-function-returning-void
