### ISSUE TITLE
pedEnd does not exist on type string	

### ISSUE THREAD

**Issue by BobFrGit** [Microsoft/TypeScript#19723]
**TypeScript Version:**  2.7.0-dev.201xxxxx

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**Expected behavior:**

**Actual behavior:**

**Comment by BobFrGit** [comment]
Turns out it was my error -- pedEnd isn't available unless I specify es2017. But it would be nice to have an error message saying "pedEnd" requires ES2017 or latter. (Even better if it could be transpiled)

**Comment by mhegazy** [comment]
The file with all declarations is not included unless you use `--lib ES2017`. It would be nice if we have a way to turn off/on declarations with a useful message, but that is not possible using the current architecture.
