### ISSUE TITLE
Specifying "types":[] does not disable automatic inclusion of @types packages

### ISSUE THREAD

**Issue by dennispg** [Microsoft/TypeScript#19720]
**TypeScript Version:**  2.6.1

**Code**
> tsconfig.json
```js
{
  "compilerOptions": {
    "types": [],
    "target": "es6",
    "module": "commonjs"
  }
}
```
> index.ts
```ts
import * as _ from 'lodash';
```

**Expected behavior:**
Documentation says (https://www.typescriptlang.org/docs/handbook/tsconfig-json.html):

> Specify  "types": [] to disable automatic inclusion of @types packages.

and

> Other packages under node_modules/@types/* will not be included.

**Actual behavior:**
All of my @types packages seem to get included anyways. 

I only came across this because I wanted to figure out how to add more packages in addition to my @types packages. Using `"types":["myspecialpackage"]` did just that, despite the documentation saying it shouldn't. Am I not understanding that correctly?

I'm not really complaining since I'm getting exactly what I wanted..

**Comment by andy-ms** [comment]
If you explicitly import something, we will perform module resolution to find what's imported. The `"types"` option only affects *automatic* inclusion, which is relevant for things like `@types/node` which declare globals.

**Comment by dennispg** [comment]
I see now, I just verified that is true. 

But how do I include a package which declares globals without making other packages under node_modules/@types/* be excluded?

**Comment by andy-ms** [comment]
If you don't want other packages in `node_modules/@types` excluded don't specify `"types": []`? Only use `"types"` if you want only a specific list of types included.

**Comment by dennispg** [comment]
I mean, I understand that.. My question was more specifically is there a way to include whatever is included by default plus some additions.. something like `"types":["node_modules/@types/*","additional-package-1","additional-package-2"]` or whatever. I'm assuming you're saying there is no way to do anything like that currently.

The workaround I am using now is to keep an `index.d.ts` with:
```ts
/// <reference types="additional-package-1" />
/// <reference types="additional-package-2" />
```

The `"types"` option just seemed like the correct place to maintain this. Is what I'm describing not a valid use case? For that matter, why would anyone ever need to be able to install but not include `@types` packages? That seems silly to me.

**Comment by andy-ms** [comment]
If `additional-package-1` is installed to `node_modules/@types` it should be included by default anyway.

> why would anyone ever need to be able to install but not include @types packages?

A dependency might have an `@types` dependency you don't want, or you might want to share a single `node_modules` between server-side and client-side code, but only the server-side code should access `@types/node`.

**Comment by dennispg** [comment]
Yes, obviously if `additional-package-1` were an `@types` package it have be included, the point is that it is not an `@types` package. It is a package that contains global declarations, and the question again is, can that use case be accommodated?

I know the docs at (https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html) say:
> `/// <reference types="..." />` declares a dependency on an `@types` package.

But my workaround to place the following in an `index.d.ts` file does make my globals available throughout and these are not `@types` packages.
```ts
/// <reference types="additional-package-1" />
/// <reference types="additional-package-2" />
```

**Comment by andy-ms** [comment]
If you want to automatically include all `@types` packages, and also manually include some others, your current approach is the correct one. The docs should be updated to note that `/// <reference types` can also reference things in `node_modules` but not `node_modules/@types`.
