### ISSUE TITLE
Compiler API `typeToTypeNode` returns uncheckable typeNode. 

### ISSUE THREAD

**Issue by tomatosource** [Microsoft/TypeScript#19740]
#### BUG: Compiler API `typeToTypeNode` returns uncheckable typeNode. 

Using the compiler API I can't see a way to get the element type from an array type `Type` object. 

Tyring something very naive like so:
```typescript
const type = checker.getTypeOfSymbolAtLocation(mySymbol, mySymbol.valueDeclaration!);
// type here is `User[]`
const typeNode = checker.typeToTypeNode(type);
if (ts.isArrayTypeNode(typeNode)) {
  const elementType = checker.getTypeFromTypeNode(typeNode.elementType);
  console.log(checker.typeToString(elementType)); // any :(
}
```
Incorrectly yields any. 

 From types:
```
 /** Note that the resulting nodes cannot be checked. */
        typeToTypeNode(type: Type, enclosingDeclaration?: Node, flags?: NodeBuilderFlags): TypeNode;
```

Seems like this is a known "issue", is there a work around I have overlooked?

**Comment by tomatosource** [comment]
For array, you can hack at type args to get them. Still an issue for union types though, where I would expect to be able to get the types[] element types.

**Comment by DanielRosenwasser** [comment]
`Array<T>` should be a type reference, so why not try looking at the `type.typeArguments[0]`?

**Comment by mhegazy** [comment]
`TypeToTypeNode` is only meant as a transfomraiton step. nodes generated after binding in general are not consumable by the checker.
