### ISSUE TITLE
Using 'this' in a function declaration based on a function type interface confuses type checking

### ISSUE THREAD

**Issue by nixxquality** [microsoft/TypeScript#19751]
Based on what I saw in [the documentation about Function Types](https://www.typescriptlang.org/docs/handbook/interfaces.html#function-types) I tried making an interface that used `this`. This has the possibility of confusing the type-checker.

**TypeScript Version:**  2.7.0-dev.20171104

**Code**

```ts
interface TestInterface {
    value: number;
}

interface FuncType {
    (this: TestInterface, n: number): number;
}

let foo: FuncType = function(n) {
    // typeof this is 'TestInterface'
    // typeof n is 'number'
    return this.value + n;
}

let bar: FuncType = function(this, n) {
    // typeof this is 'TestInterface'
    // typeof n is 'any'
    return this.value + n;
}
```

**Expected behavior:**
Type information should remain consistent.

**Actual behavior:**
As listed in the comment, the arguments after `this` lose their type information.

**Comment by nixxquality** [comment]
Nevermind, I wrote my test case incorrectly. I need to double-check where my errors came from.

**Comment by nixxquality** [comment]
I've updated my example to reflect my actual issue, which had me confused.
I'm not sure if this is an issue with the type checker or just an edge case you need to keep in mind.

**Comment by jakebailey** [comment]
Ancient issue, but this has been fixed for a very long time. [Playground Link](https://www.typescriptlang.org/play?ts=5.4.4#code/JYOwLgpgTgZghgYwgAgCoQM5gJLmvJZAbwChlzkA3OAGwFcIAuZEOgWwCNoBuEgXxIlQkWIhQAxOiASoAngAcUpCsgAUYABbAMzdFlwiCEADQtmrTtACU59lyi8BJGhDDIYAew-NJ0uYuQAXncpBDBgDxBVECtiMgoAegTkMAUIDxgUrQxkbWQAcj0cPFEkfPjyJJS0jJZcnPyLe3KVKFc6KBAs7QA6anoUAGoWXhUqlQnJ8gA9AH5+QRc3DjgoH1D-FGCYUPDI9WzTGLix5NTFWs08vMLMYsMxFsSzmsyum7gQWSfyNrAOrpXDB9WgMZDDECjZ5TGEUOb8IA)
