### ISSUE TITLE
Suggestion: Add an `auto_init_properties` flag, emitting error if default value cannot be determined

### ISSUE THREAD

**Issue by mgenware** [Microsoft/TypeScript#19750]
This is related to #8476. I'd suggest that, under some flags, instead of warning user of type safety caused by the default `undefined` value, give it a default value like C#, **if the default value can't be determined, emit an error.**

```typescript
// under a flag like `--auto_init_properties`
class Person {
  id: number; // auto initialized to 0
  name: string; // auto initialized to ""
  description: string|null; // auto initialized to null

  // **Compilation error: Can't determine default value for this prop, all properties must be initialized. **
  opt: string|number|Option; 

  // To fix this, user must specify an value, for example:
  opt: string|number|Option = 'abc';
  opt: string|number|Option = new Option();
}
```

In this way, all properties are actually **defined** in runtime:
```javascript
const obj = new Person();
for (const property in obj) {
  console.log(property);
}

// Output: id, name, description, opt
```

Also, we don't need to write boilerplate code to enforce strict type safety:
```javascript
class Person {
  constructor {
    this.id = 0;
    this.name = '';
    this.description = null;
    this.opt = new Option();
  }
}
```

**Comment by Ghabriel** [comment]
From the [TypeScript Design Goals page](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals), one of the non-goals of TS is to `Add or rely on run-time type information in programs, or emit different code based on the results of the type system,` which I believe applies to your suggestion.
