### ISSUE TITLE
Checking for overriding files when emit writer is not fs.writeFile

### ISSUE THREAD

**Issue by goloveychuk** [Microsoft/TypeScript#19755]
**TypeScript Version:**  2.4.2 (looked at master - nothing changed)

So:
1) while using `LanguageService` api (or even `Program` api), with calling `service.getEmitOutput` or `program.emit` (with some custom writer)
2) having `allowJs=true`
3) having empty `outputDir` and `suppressOutputPathCheck=false` compiler options

typescript produces error
```
Error: Cannot write file '/<somepath>/dist/utils.js' because it would overwrite input file.
      Adding a tsconfig.json file will help organize projects that contain both TypeScript and JavaScript files. Learn more at https://aka.ms/tsconfig.
```

But, for not `fs` writers, it shouln't raise error. 

Problem is in
https://github.com/Microsoft/TypeScript/blob/8d5b0529b2bb7650d471b4d64fd88061cde4707d/src/compiler/program.ts#L2203
which is called on `createProgram`.

Look like it doesn't happens for ts files since they change extensions from .ts to .js

I guess it wouln't be difficult to fix. E.g. to add 
```ts
interface CompilerHost {
    fileIsDuplicate(filepath): boolean
}
```
Or, maybe, we just should have overriden `suppressOutputPathCheck=true` while using compiler api?

**Comment by mhegazy** [comment]
Can you share more context here. the check is done in `createProgram` to ensure the output is always correct.. if you are wrapping the program, make sure to set `suppressOutputPathCheck`, otherwise, the error seems right to me.

**Comment by goloveychuk** [comment]
So more context. I'm using `LanguageService` Api. And I'm getting output here
https://github.com/goloveychuk/ts-jest/blob/master/src/compiler/compiler.ts#L134

So I'm emitting to string. But before that when I'm running `createLanguageService` which cals `createProgram` it runs some general checks, one of them is checking overriding of source files. But this check is irrelevant if further we will emit to string. 
If you're saying that overriding `suppressOutputPathCheck=true` is proper solution, then ok. I just thought that it's little wrong check in case of custom emit writer.

**Comment by mhegazy** [comment]
> it runs some general checks, one of them is checking for overriding of source files. But this check is irrelevant if further we will emit to string.

the compiler does not know that.. you can use `ts.transpileModule` if all you need is the string, and this function will set the flag to suppress the error. see https://github.com/Microsoft/TypeScript/blob/master/src/services/transpile.ts#L33-L34

> If you're saying that overriding suppressOutputPathCheck=true is proper solution, then ok. I just thought that it's little wrong check in case of custom emit writer.

again, the compiler has no way to know when you are building the program that you intend to write it to a string. The invariant here is you want to get all the errors in your editor without having to emit the code, and if the error was reported at emit time, that would not be possible. but reporting it early means you have no way to know the intend.. and for that, you use the flag.

hope that explains it.

**Comment by goloveychuk** [comment]
ok, thanks
