### ISSUE TITLE
Inference oddities with --strictFunctionTypes

### ISSUE THREAD

**Issue by pelotom** [Microsoft/TypeScript#19759]
**TypeScript Version:**  2.6.1

With `--strictFunctionTypes` enabled, this fails:

```ts
import { Subject, BehaviorSubject } from 'rxjs';

const subject: Subject<number | undefined> = new BehaviorSubject(undefined)
//    ^^^^^^^
// Type 'BehaviorSubject<undefined>' is not assignable to type 'Subject<number | undefined>'.
//   Types of property 'observers' are incompatible.
//     Type 'Observer<undefined>[]' is not assignable to type 'Observer<number | undefined>[]'.
//       Type 'Observer<undefined>' is not assignable to type 'Observer<number | undefined>'.
//         Type 'number | undefined' is not assignable to type 'undefined'.
//           Type 'number' is not assignable to type 'undefined'.
```

Ok, so `new BehaviorSubject(undefined)` is failing to be inferred from context as a `BehaviorSubject<number | undefined>`, not the end of the world. I should be able to fix it like this, right?

```ts
const initialValue: number | undefined = undefined
const subject: Subject<number | undefined> = new BehaviorSubject(initialValue)
```

Nope, same error! That's weird. But, this works:

```ts
declare const initialValue: number | undefined
const subject: Subject<number | undefined> = new BehaviorSubject(initialValue)
```

Whaaa? It's like TypeScript is taking advantage of knowledge it shouldn't have; namely that `initialValue` is really `undefined`, even though I told it that its type is `number | undefined`.

**Comment by DanielRosenwasser** [comment]
I'm not sure to what extent it would be desirable to use the *declared* type in that situation over the narrowed type. For example, let's take the opposite scenario, imagine that you tried creating a `BehaviorSubject` with something that was declared as `number | undefined`, but was already initialized with a `number`. That would likely lead to more pain than I think most users would anticipate.

I think the best workaround would be to specify explicit type arguments.

**Comment by pelotom** [comment]
But the type shouldn’t be narrowed. A variable of a certain type was declared and nothing has happened since then (e.g. checking if `=== undefined`) to narrow it. If inspect the type of the variable it _is_ `number | undefined`.

**Comment by pelotom** [comment]
I can certainly use an explicit type argument to work around this, it’s just disturbing that my mental model of the type system can’t make sense of this behavior.

**Comment by ahejlsberg** [comment]
I think the compiler is doing the right thing here. In both error cases, the compiler has correctly concluded that the argument to `BehaviorSubject` is a value of type `undefined`. In the first case it is self evident, and in second case the conclusion was based on control flow analysis. However, in the third case the compiler knows only the declared type so that is the narrowest type it can assume.

**Comment by pelotom** [comment]
@ahejlsberg that's interesting, it hadn't occurred to me that control flow analysis could affect the typing in this way. But then based on what you're saying I would expect this:

```ts
const b: boolean = true

if (b) {
  throw Error('oops')
}

const foo = 1
```

to be flagged on the last line with `Unreachable code detected`, just like this:

```ts
if (true) {
  throw Error('oops')
}

const foo = 1
```

However it's not... isn't the unreachable code detection powered by control flow analysis?

**Comment by pelotom** [comment]
Also, why does this apparently bypass the control flow analysis?

```ts
const subject: Subject<number | undefined> = new BehaviorSubject(undefined as number | undefined)
```

**Comment by ahejlsberg** [comment]
>> isn't the unreachable code detection powered by control flow analysis?

No, the unreachable code detection is purely based on the grammatical structure of the code. In fact, the reason we detect unreachable code in the `if (true) ...` example is because we recognize the literal `true` in the grammatical analysis.

>>> Also, why does this apparently bypass the control flow analysis?

Because you're explicitly overriding the control flow analyzer using a type assertion.
