### ISSUE TITLE
An index signature cannot be a union of strings

### ISSUE THREAD

**Issue by peaBerberian** [Microsoft/TypeScript#19768]
**TypeScript Version:**  2.7.0

**Code**

```ts
type FruitName = "apple"|"pear";
interface IFruitInventory {
  [key : FruitName] : number;
}
```

**Expected behavior:**
```ts
interface IFruitInventory {
  [key : FruitName] : number;
}
```
Should be equivalent to
```ts
interface IFruitInventory {
  apple? : number;
  pear? : number;
}
```

**Actual behavior:**
``Error : An index signature parameter type must be 'string' or 'number'`` when defining the _IFruitInventory_ interface.

It may be a duplicate, but I could not find another one with the same problem (most of the others I saw were about enums).

**Comment by pelotom** [comment]
The syntax you’re looking for is

```ts
type IFruitInventory = {
  [K in FruitName]: number
}
```

Or, if you want them to all be optional fields as you’ve indicated,

```ts
type IFruitInventory = {
  [K in FruitName]?: number
}
```

The first can also be expressed as `Record<FruitName, number>`, and the second by `Partial<Record<FruitName, number>>`.

**Comment by peaBerberian** [comment]
My bad, thanks a lot.
