### ISSUE TITLE
JSX fragments as properties

### ISSUE THREAD

**Issue by asfernandes** [Microsoft/TypeScript#19767]
**TypeScript Version:**  2.7.0-dev.20171104

I may be wrong, but in my understanding this case fall under description of #19249 but it's not covered.

```ts
function CompA(props: { x: JSX.Element }) {
	return <div />
}

function CompB(props: { x: JSX.Element }) {
	return <CompA x={<div /><div />} />	// JSX expressions must have one parent element
}

function CompC(props: { x: JSX.Element[] }) {
	return <div />
}

function CompD(props: { x: JSX.Element }) {
	return <CompC x={[<div /><div />]} />	// JSX expressions must have one parent element
}
```

I expect that error `JSX expressions must have one parent element` does not occur at least in one of these cases.

**Comment by uniqueiniquity** [comment]
I'm not sure I understand why either of these should not error. In both cases, you're trying to treat two sibling tags as a single JSX element, which should not hold. While the fragment syntax in #19249 replicates the behavior of an array, it does not actually compile to an array (or involve arrays in any way afaik). While I agree that error could be worded a little clearer, I disagree that it's nonsense; JSX expressions must have a single element that serves as a parent for all other elements contained therein.

**Comment by andy-ms** [comment]
@uniqueiniquity You mean "JSX expressions must have one **root** element?" There's no node with two parents, after all...

**Comment by uniqueiniquity** [comment]
Yes, that is exactly what I mean. Might be worth changing that message :)

**Comment by asfernandes** [comment]
More than one element can be passed to children, why not an attribute (parameter) would accept more than one in the same manner?

**Comment by uniqueiniquity** [comment]
The [specification for the JSX language](https://github.com/facebook/jsx/blob/master/README.md) makes a distinction between a set of children and a single element. I'm not sure why this decision was made, but the language is defined as such.

**Comment by uniqueiniquity** [comment]
To put it informally, a valid JSX expression is either a single fragment or a single element (which we type as JSX.Element anyway). The curly braces in the attribute must contain a valid expression, for which one option is a JSX expression.

**Comment by asfernandes** [comment]
FWIW, I mistyped my second example... I mean the code below (with a comma inside the array) and it does not generate error:

```ts
function CompC(props: { x: JSX.Element[] }) {
	return <div />
}

function CompD(props: { x: JSX.Element }) {
	return <CompC x={[<div />, <div />]} />
}
```

**Comment by uniqueiniquity** [comment]
Yes, that makes sense. That is the pattern that the new fragment syntax seeks to replace. Does this resolve your concern?

**Comment by asfernandes** [comment]
Well, I was expecting it working in the first way with fragments, but if you say I'm wrong, then ok...

**Comment by uniqueiniquity** [comment]
I think I see the confusion. You have to explicitly wrap those tags in `<>...</>`, it's not done implicitly.

**Comment by uniqueiniquity** [comment]
So 
```
function CompA(props: { x: JSX.Element }) {
	return <div />
}

function CompB(props: { x: JSX.Element }) {
	return <CompA x={<><div /><div /></>} />
}
```
should work.

**Comment by uniqueiniquity** [comment]
Also, @andy-ms, that second error message involving the comma has to do with how we parse this scenario in order to prevent the formatter from mangling it. See https://github.com/Microsoft/TypeScript/blob/d79c37cd191a5d10ad678f2a1379c6267e914bf2/src/compiler/parser.ts#L4020 for details.
