### ISSUE TITLE
Class 'AnotherProductService' incorrectly implements interface 'ProductService'.

### ISSUE THREAD

**Issue by dingziyang** [Microsoft/TypeScript#19761]
I create a project with angular/cli , when I try used service, I get an error.
-----

**TypeScript Version:**  2.4.2
**Angular CLI Version:** 1.5.0
**NPM Version:** 5.0.3
**Node.js Version:**  8.1.0
**OS Version:**  Winwods 10 Professional Edition x64
---------
**Code**

```ts
import { Injectable } from '@angular/core';
import { LoggerService } from './logger.service';


@Injectable()
export class ProductService {

  constructor(private logger: LoggerService) { }

  getProduct(): Product {
    this.logger.log('getProduct function');
    return new Product(0, 'iphone7', 5899, 'apple phone');
  }
}

export class Product {

  constructor(
    public id: number,
    public title: string,
    public price: number,
    public desc: string
  ) {

  }
}
```
-------------
```ts
import { Injectable } from '@angular/core';
import { Product, ProductService } from './product.service';

@Injectable()
export class AnotherProductService implements ProductService {

  getProduct(): Product {
    return new Product(1, 'sunsumg7', 4899, 'sunsumg phone');
  }

  constructor() { }

}
```
------------
```ts
import { Injectable } from '@angular/core';

@Injectable()
export class LoggerService {

  constructor() { }

  log(message: string) {
    console.log(message);
  }

}
```
----------------
```ts
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppComponent } from './app.component';
import { Product1Component } from './product1/product1.component';
import { ProductService } from './shared/product.service';
import { Product2Component } from './product2/product2.component';
import { LoggerService } from './shared/logger.service';

@NgModule({
  declarations: [
    AppComponent,
    Product1Component,
    Product2Component
  ],
  imports: [
    BrowserModule
  ],
  providers: [ProductService, LoggerService],
  bootstrap: [AppComponent]
})
export class AppModule { }
```
------

**Expected behavior:**
- If it is work, the Product where be get and show on the html.
--------------

**Actual behavior:**
- I get an error.
```
ERROR in src/app/shared/another-product.service.ts(5,14): error TS2420: Class 'AnotherProductService' incorrectly implements interface 'ProductService'.Property 'logger' is missing in type 'AnotherProductService'.

```

**Comment by andy-ms** [comment]
You probably meant `extends` instead of `implements`.

**Comment by dingziyang** [comment]
@andy-ms I understand what you main. Everything in interface must be public. 
But, I'm sure I use implements here. Because I downloaded a study video, the teacher is doing this and it's work. He also used Angular4 and TypeScript. 
**Oh! It drives me crazy!**

**Comment by andy-ms** [comment]
It is possible to "implement" a class -- but it means treating the class as an interface, so you'll have to create an implementation of every one of its members.
However, if the class you're implementing has a private member, it's impossible to implement.
```ts
class A {
	private x: number;
}
// Error: Types have separate declarations of a private property 'x'.
class B implements A {
	private x: number;
}
```

It's correct that we give you this error message, because if `B implements A`, you would expect to be able to assign a `B` to an `A`, but you can't assign anything to a class with a private member unless it's derived from that class via `extends`. So the error message should just tell you that instead of telling you to implement a property that you can't possibly implement.

In your case, if you really don't intend to use `extends`, you must define an interface and have both classes implement that.

**Comment by dingziyang** [comment]
@andy-ms Thanks for your help. In the next section, the teacher changed ```private``` to ```public```。
（＃－.－）

**Comment by andy-ms** [comment]
Moved the error message issue to #19793.
