### ISSUE TITLE
Object.keys and Object.entries should return correct index types

### ISSUE THREAD

**Issue by zakjan** [Microsoft/TypeScript#19765]
**TypeScript Version:**  2.6.1

**Code**

```ts
enum ItemType {
    A = "a",
    B = "b",
}
const obj: { [key in ItemType]: string } = { [ItemType.A]: "x", [ItemType.B]: "y" };

const keys = Object.keys(obj);
const entries = Object.entries(obj);
```

**Expected behavior:**
`keys` should have type `ItemType[]`
`entries` should have type `[ItemType, string][]`

**Actual behavior:**
`keys` has type `string[]`
`entries` has type `[string, string][]`

**Comment by jcalz** [comment]
One of many duplicates of #13254, I think.  I
