### ISSUE TITLE
how can i disable auto imports with completion?

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#19764]
i am glad so many people are happy with this new feature, but it ruins my productivity because i cannot find local types in my autocomplete popup anymore, because our codebase is over 2000 files which results in 1000000000 entries in the popup

**Comment by andy-ms** [comment]
I think vscode will add the ability to toggle this now that we've put it behind a flag. (#19687).

**Comment by andy-ms** [comment]
Microsoft/vscode#37711

**Comment by aleksey-bykov** [comment]
solution: https://github.com/Microsoft/vscode/issues/37711#issuecomment-342211216
