### ISSUE TITLE
Taking too much time with webpack dev server.

### ISSUE THREAD

**Issue by AbinayaSubbiah** [Microsoft/TypeScript#19760]
hi all i have the angular sample with webpack configuration. Previously i had typescript version @2.20 at that time got webpack build with in 5 mins. If i upgraded typescript package to 2.6.1 its taking near 15 mins to 20 mins to generate build. Could you please suggest me solution.

**Comment by hnrindani** [comment]
I faced similar issues and from my interactions over other portals, I learnt that any version above 2.4 has this similar issue. It takes too much of time to locate a file and call for the values. Also cache is an issue specifically for .5 and .6 versions. What I was suggested is to use 2.5 till the issues are resolved. The next version is expected to roll out in 15 days time and probably this burning issue would be resolved there.

**Comment by johnnyreilly** [comment]
Sorry - not heard anything about this. FWIW I'm working only on React projects at the moment - it's possible this is something Angular specific.

**Comment by johnnyreilly** [comment]
^ and my projects are compiling fine with webpack / ts 2.6 AFAIK
