### ISSUE TITLE
Duplicate accessors are emitted only once

### ISSUE THREAD

**Issue by JsonFreeman** [Microsoft/TypeScript#1977]
Not sure if this is a bug, but the following incorrect code:
```ts
class C {
    get foo() { return '' }
    get foo() { return '' }
}
```
produces the output:
```js
var C = (function () {
    function C() {
    }
    Object.defineProperty(C.prototype, "foo", {
        get: function () {
            return '';
        },
        enumerable: true,
        configurable: true
    });
    return C;
})();
```

The source code is a duplicate identifier error, but I would think we'd still emit the getter twice.

**Comment by DanielRosenwasser** [comment]
I was pretty split on this, but it seems like a bug.

From [the incompatibilities section of the draft](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-in-the-6th-edition):
> 12.2.5.1: In Edition 6, it is no longer an early error to have duplicate property names in Object Initializers.

So I think if this applies to accessors, we should either emit all or elide the one that won't be used.

Right now in my JS console, if I try the following:

```JavaScript
    var x = {};
    Object.defineProperty(x, "foo", {
        get: function () {
            return '';
        },
        get: function () {
            return 10;
        },           
        enumerable: true,
        configurable: true
    })
    console.log(x.foo)
```

I get `10` as an output.

**Comment by mhegazy** [comment]
There is already an error issued for this. i do not think we need to do anything extra at this point.
