### ISSUE TITLE
JSDoc @augments does not work with object literal type

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#19776]
**TypeScript Version:**  2.7.0-dev.201711029

**Code**
For the JS

```js
/**
 * @augments {{abc: string}}
 */
class Foo {
    constructor() {
    }
}

const o = new Foo()
o.abc;
```

**Expected behavior:**
`o.abc` is resolved from `@augments`. This works when using `@augments {MyOtherClass}`

**Actual behavior:**
`o.abc` has any type

**Comment by mhegazy** [comment]
what is allowed in `augments` is what is allowed in an `extends` clause. namely something with a constructor that returns an object..

**Comment by mjbvz** [comment]
Ok, make sense. Thank you for the explanation.

I ran into this while investigating this SO question: https://stackoverflow.com/questions/47089110/how-can-i-use-object-assignthis-foo-bar-and-have-vscode-intellisense-autocom/47102189 Not sure if you know of a clean way to achieve what the user was after
