### ISSUE TITLE
Type narrowed non-nullness lost in array method callback

### ISSUE THREAD

**Issue by aaronbeall** [Microsoft/TypeScript#19778]
**TypeScript Version:**  2.5.3

**Code**

```ts
declare const obj: { props?: string[] }

obj.props // string[] | undefined
if (obj.props) {
    obj.props // string[]
    obj.props.forEach(p =>
        obj.props // string[] | undefined <-- Expected string[]
    )
}
```

**Expected behavior:**
`obj.props` inside `forEach` callback to be `string[]`

**Actual behavior:**
`obj.props` inside `forEach` callback goes back to possibly undefined, leading to errors if not again type guarded

**Comment by mhegazy** [comment]
Please see https://github.com/Microsoft/TypeScript/issues/10982

**Comment by aaronbeall** [comment]
Thanks
