### ISSUE TITLE
Cannot read property 'end' of undefined at getFullWidth

### ISSUE THREAD

**Issue by shaunluttin** [Microsoft/TypeScript#19782]
**TypeScript Version:** Version 2.7.0-dev.20171104

**Code**

```ts
// index.ts
import Bar from "./bar";
const bar = new Bar();

// bar.ts
export default abstract class  { }
```

See: https://github.com/shaunluttin/reproduce-tsc-issue-19782

**Expected behavior:**

The compiler emits an error about instantiating an abstract class. 

**Actual behavior:**

```
PS C:\src> .\node_modules\.bin\tsc
C:\src\node_modules\typescript\lib\tsc.js:58287
                throw e;
                ^

TypeError: Cannot read property 'end' of undefined
    at getFullWidth (C:\src\node_modules\typescript\lib\tsc.js:5496:20)
    at Object.declarationNameToString (C:\src\node_modules\typescript\lib\tsc.js:5871:16)
    at resolveNewExpression (C:\src\node_modules\typescript\lib\tsc.js:32028:102)
    at resolveSignature (C:\src\node_modules\typescript\lib\tsc.js:32172:28)
    at getResolvedSignature (C:\src\node_modules\typescript\lib\tsc.js:32190:26)
    at checkCallExpression (C:\src\node_modules\typescript\lib\tsc.js:32233:29)
    at checkExpressionWorker (C:\src\node_modules\typescript\lib\tsc.js:33520:28)
    at checkExpression (C:\src\node_modules\typescript\lib\tsc.js:33463:42)
    at checkExpressionCached (C:\src\node_modules\typescript\lib\tsc.js:33375:38)
    at getTypeOfExpression (C:\src\node_modules\typescript\lib\tsc.js:33448:28)  
```

**Comment by mhegazy** [comment]
Can you share the source that triggered the exception?

**Comment by shaunluttin** [comment]
Hmm. It's closed source, so I would need to ask my employer. I am working on a repro.

**Comment by mhegazy** [comment]
If you would rather not share your project, you can fire the compiler under `node --inspect-brk node_modules/typescript/lib/tsc.js --p <tsconfig.json>` and at the location of the crash, in `checkCallExpression` on the stack, get call `getSourceFileOfNode(node)` and that should tell you the file where the compiler is crashing, and inspecting the `node` should give you the position and the call target, so you can narrow down the source of the crash, and hopefully be able to reduce the repro.

**Comment by shaunluttin** [comment]
We were not able to reproduce the error due to time constraints. Also, the error appears to have resolved itself magically. If it comes back, then we will submit an update. 

In the meantime, we can report that the error occurred on when important a specific NPM package that was built with TypeScript. That specific package, in addition to causing the aforementioned error, was also causing an error related to `forceConsistentCasingInFileNames`. 

Apologies for not being able to provide more information. :watch:

**Comment by shaunluttin** [comment]
We are only seeing this: 
```
PS C:\src> node --inspect-brk .\node_modules\typescript\lib\tsc.js -p .\tsconfig.json    
Debugger listening on ws://127.0.0.1:9229/5f8330c0-1d10-4330-bdba-10373920ddbc                             
For help see https://nodejs.org/en/docs/inspector                                                          
```
What further steps are necessary to inspect the `checkCallExpression`?

**Comment by shaunluttin** [comment]
The problem came from trying to instantiate an abstract class.

**Comment by shaunluttin** [comment]
Repro: https://github.com/shaunluttin/reproduce-tsc-issue-19782
