### ISSUE TITLE
Improve error message when `implements` is used instead of `extends`

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#19793]
**TypeScript Version:**  2.7.0-dev.201xxxxx

**Code**

```ts
class A {
	private x: number;
}

class B implements A {}
```

**Expected behavior:**

Begin the error message with `class 'B' is declared to implement class 'A'. Did you mean 'extends'?`. Then continue with the specific error message.

**Actual behavior:**

```
src/a.ts(5,7): error TS2420: Class 'B' incorrectly implements interface 'A'.
  Property 'x' is missing in type 'B'.
```
Not helpful on its own because we can't implement `x`. I figure 99% of the time one intends to extend a class rather than implement, so we should just show an additional message any time one class implements another and there's an error.

**Comment by charlespierce** [comment]
PR Opened to resolve this #19797

**Comment by DanielRosenwasser** [comment]
Thanks @charlespierce!
