### ISSUE TITLE
How does TS support webpack's extensions?

### ISSUE THREAD

**Issue by JounQin** [Microsoft/TypeScript#19796]
**TypeScript Version:**  2.6.1

**Code**

``` ts
{
  resolve: {
    extensions: ['.ts', '.vue', '.js']
  }
}
```

And I've set `paths` in my tsconfig.json.

``` json
{
  "paths": {
      "*": [
        "*.ts",
        "*.vue"
      ]
  }
}
```

**Expected behavior:**
``` ts
import Home from './views/Home'
```

**Actual behavior:**
I must write
``` ts
import Home from './views/Home.vue'
```
Otherwise typescript service of IntelliJ IDEA will report an error: `Error:(5, 17) TS2307:Cannot find module './views/Home'.`.

**Comment by mhegazy** [comment]
paths mapping do not affect relative paths. only non-relative ones. please see https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping.

The compiler does not rewrite module names at emit time. module names are considered resource identifiers and are not modified.. see https://github.com/Microsoft/TypeScript/issues/18971, #18951 and #16640

**Comment by JounQin** [comment]
@mhegazy So is there any workaround to support webpack extensions for now?

**Comment by DanielRosenwasser** [comment]
In a global file, you can write something like

```ts
declare module "*.vue" {
    import Vue from "vue";
    export default Vue;
}
```

**Comment by JounQin** [comment]
@DanielRosenwasser I've done that, my problem is that I want to remove `.vue` suffix when import `.vue` file.
