### ISSUE TITLE
TypeScript team lost the ability to maintain TSJS-lib-generator tools

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#19795]
As https://github.com/Microsoft/TSJS-lib-generator/pull/300, TypeScript team lost the ability to maintain TSJS-lib-generator tools **after the author of that repository left Microfoft.** TypeScript team must give more resource to maintain that right now.

@ahejlsberg @DanielRosenwasser @sandersn @RyanCavanaugh @rbuckton @weswigham @billti @andy-ms @sheetalkamat

**Comment by mhegazy** [comment]
There has been 22 commits to this repo in the last 5 days, and 40 commits in the last month.. see https://github.com/Microsoft/TSJS-lib-generator/commits/master.

The PR in is a significant change, and it is not a small change to review. if you would like to help simplify the validation process, or have a proposal please do..

**Comment by falsandtru** [comment]
It cannot be the reason that you don't maintain https://github.com/Microsoft/TSJS-lib-generator/pull/300. Are you still in vacation? At least you must show your mind to go ahead with the work. **Show your mind or progress in that PR.**

**Comment by mhegazy** [comment]
> It cannot be the reason that you don't maintain Microsoft/TSJS-lib-generator#300. Are you still in vacation? 

I am maintain it.. every day.. i commit, i review, and i merge.. do not believe me look at the history.

> At least you must show your mind to go ahead with the work. Show your mind or progress in that PR.

not sure what you mean by "showing my mind".. time is a finite resource.. and i do other things as well..

**Comment by DanielRosenwasser** [comment]
@falsandtru while I understand the frustration, like @mhegazy said, we have a lot of work and traffic coming in very day. If you're subscribed to events on our repository, you might be able to imagine the scope of addressing every thing. It might be easy to imagine, but Microsoft isn't just throwing 500 people to help out with this repo.

We do our best to prioritize work, but unfortunately we're not perfect at it. We hope you'll understand, and [lend a more respectful tone to us on the team](https://github.com/Microsoft/TypeScript/issues/17476#issuecomment-341422564) who have to address numerous other bugs and suggestions that are also valued by our userbase.

**Comment by kitsonk** [comment]
For reference the [Microsoft Code of Conduct](https://opensource.microsoft.com/codeofconduct/):

> **Be respectful:** We are a world-wide community of professionals, and we conduct ourselves professionally. Disagreement is no excuse for poor behavior and poor manners.

**Comment by falsandtru** [comment]
I mean you should reply Microsoft/TSJS-lib-generator#300 (also https://github.com/Microsoft/TSJS-lib-generator/pull/227). This large important PR has been left since May 2017 https://github.com/Microsoft/TSJS-lib-generator/pull/227#issuecomment-302742780 without any response. This is definitely bad. I requested the same thing at #17476. You don't respect his contribution? If not, you should give some response.

**Comment by kitsonk** [comment]
@falsandtru as a non-Microsoft related or affiliated person, who is a long term participant in the TypeScript community, I have to admit I find your behaviour very disappointing and border line rude and abusive.

Both the PR you mention are substantial PRs to the library, that could have significant impacts of downstream compatibility and breaking changes on everyone who uses TypeScript.  While the review process of Microsoft/TSJS-lib-generator#227 was slow, there was feedback, which of course caused the author to open Microsoft/TSJS-lib-generator#300.

You then refer to other points where you have made semi-abusive comments towards members of the core team, specifically calling members of the team lazy.  I find your abuse of hard working members of the TypeScript team offensive.  Please change your approach or I will feel compelled to report your behaviour as a violation of the code of conduct I mentioned above.  Bullying and abusing people is not the way to participate in a community.

**Comment by saschanaz** [comment]
First I also understand your frustration (as the PR is mine), but bad words are not good to accelerate the review speed. Good words will :smile:

And sorry for my own impatience at #300.

**Comment by saschanaz** [comment]
>if you would like to help simplify the validation process, or have a proposal please do..

What would be the best way for contributors to help validation? I can talk about the cause of CI failures, unexpected behaviors, etc. but nothing to do if LGTM.
