### ISSUE TITLE
Suggestion?: compiling in given standard.js format

### ISSUE THREAD

**Issue by papakai** [Microsoft/TypeScript#19803]
As I haven't found anything on that:

We are using `tsc` for transpiling our typescript files into the configured format, in our case it is ES6/2015 for node.js modules and ES5 for client-side modules for now. Even though tsc does this pretty well, it would be very great if it could consider to transpile considering a given .eslintrc / .eslintrc.js / et. al. file (or an option through tslint config file) to transpile in a more desired way like in standard.js

Currently we need an additional linting job to cover this through eslint. In addition a minification would also be great, but I already found this issue covering that:  https://github.com/Microsoft/TypeScript/issues/8

**Comment by kitsonk** [comment]
This feels like it would be a [non-goal of TypeScript](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals#non-goals):

> 4. Provide an end-to-end build pipeline. Instead, make the system extensible so that external tools can use the compiler for more complex build workflows.

TypeScript would always be doing a poorer job than some other tool, and even recently the core team have _regretted_ their decisions to introduce some errors that would traditionally be linting errors, versus sticking to it knitting of providing a strong typing system for JavaScript.

Other than _we would like_ is there a compelling reason why you are concerned about the linting of transpiled code?  Especially if you are also looking for minification, then linting seems totally illogical and irrelevant for transpiled code.

**Comment by papakai** [comment]
There's no compelling reason, just the point that we have a JS Style configuration and any generated JS Code should follow this. If this is not planned for TS, then ok - we keep our current build process.
Why is linting illogical and irrelavant for transpiled code in case we minify? I mean, we minify the transpiled file, but save it under another file name. This means we keep the transpiled and linted file. Maybe useful in case the linted file doesn't work as expected and we need to debug for the reason.

As said: It is not a problem for us to keep our build process as it is, I was just thinking about it could make sense to have tsc extended. if that's not desired, no problem.

**Comment by kitsonk** [comment]
> Maybe useful in case the minified file doesn't work as expected and we need to debug for the reason.

But again, linting it provides what value?  Also, if you are debugging transpiled or minified code, source maps are a far better more logical way to debug code.

> I was just thinking about it could make sense to have tsc extended. if that's not desired

I am just a man with his opinions, versus any core team member, just attempting to point out that TypeScript has some very clear design goals.  Given the amount of effort that would have to go into building and maintaining a feature such as this, my personal opinion is there are a lot better places for people to focus their efforts, especially, as you mention, there are already sufficient tools to meet your needs.

**Comment by papakai** [comment]
> But again, linting it provides what value? 
At least for readability as all files follow the same rules.

> I am just a man with his opinions ... just attempting to point out that TypeScript has some very clear design goals
All fine. I am personally not aware of these goals, so as said: ok to close because of that argumentation. We have our process which we keep using then. Just see this feature request then under pov of not knowing anything about the design goals and thus the idea for this came up.

Thanks for the feedback - very appriciated.
