### ISSUE TITLE
Incorrect sourcemap for comments in module function

### ISSUE THREAD

**Issue by NN---** [Microsoft/TypeScript#1980]
This works correctly, you cannot put a breakpoint on the comment:

```
function P() {
	// Test this
	var a = 1;
}
```

This is the sourcemap:

```
{"version":3,"file":"W.js","sourceRoot":"","sources":["W.ts"],"names":["P"],"mappings":"AAAA,SAAS,CAAC;IAETA,AADAA,YAAYA;QACRA,CAACA,GAAGA,CAACA,CAACA;AACXA,CAACA"}
```

While here you can put a breakpoint on the comment but cannot put on 'var a = 1' !

```typescript
module Q {
	function P() {
		// Test this
		var a = 1;
	}
}
```

Sourcemap:

```
{"version":3,"file":"W.js","sourceRoot":"","sources":["W.ts"],"names":["Q","Q.P"],"mappings":"AAAA,IAAO,CAAC,CAKP;AALD,WAAO,CAAC,EAAC,CAAC;IACTA,SAASA,CAACA;QAETC,AADAA,YAAYA;YACRA,CAACA,GAAGA,CAACA,CAACA;IACXA,CAACA;AACFD,CAACA,EALM,CAAC,KAAD,CAAC,QAKP"}
```

Checked in Google Chrome.

**Comment by richardbullin** [comment]
I'm finding that the sourcemaps from 1.4.1 are being generated incorrectly when I have a file with just a comment above a line without using a module.

In version 1.4.1 the below code with a breakpoint on 'var aNumber = 10;' does not get hit

    //
    var aNumber = 10;
    
    var aNumber2 = 1100;

The generated sourcemap is

    {"version":3,"file":"_CompiledJavaScript.js","sourceRoot":"","sources":["../TestMain.ts"],"names"   [],"mappings":"AACA,AADA,EAAE;IACE,OAAO,GAAG,EAAE,CAAC;AAEjB,IAAI,QAAQ,GAAG,EAAE,CAAC"}

Compared to the sourcemap for the same code generated from 1.0.1 which does allow the breakpoint to get hit

    {"version":3,"file":"_CompiledJavaScript.js","sourceRoot":"","sources":["../TestMain.ts"],"names":[],"mappings":"AAAA,EAAE;AACF,IAAI,OAAO,GAAG,EAAE;;AAEhB,IAAI,QAAQ,GAAG,EAAE"}

**Comment by mhegazy** [comment]
@yui, Sheetal had a fix for this a while back; so check #2014 first.

**Comment by jasonwilliams200OK** [comment]
Same here. I used http://murzwin.com/base64vlq.html to decode source-maps.

**Comment by DanielRosenwasser** [comment]
This should be fixed as of the pull from #2880.

**Comment by richardbullin** [comment]
I don't believe this is fixed? I updated to typescript 1.5.3 and the sourcemap generated from my previously listed code snippet in the comments above is exactly the same as versions 1.1.0-1, 1.3.0 and 1.4.1 and the breakpoints still do not get hit, for the same code the breakpoints only get hit in version 1.0.1 only, so it looks like a change between v1.0.1 and 1.1.0-1 generates the sourcemaps differently.

**Comment by NN---** [comment]
I agree.
The issue was not fixed with TypeScript 1.5.3.

**Comment by danquirk** [comment]
Re-opening for investigation.

**Comment by kitsonk** [comment]
This was resolved in 1.6 though via #4086 don't know if it is worth porting into 1.5.  I would try with TypeScript@next and see if it resolves the issue.  It did for my source map problems.

**Comment by NN---** [comment]
@kitsonk Personally I would like a fix in 1.5 since it can be released faster than 1.6 .

**Comment by mhegazy** [comment]
> Personally I would like a fix in 1.5 since it can be released faster than 1.6 .

There are no 1.5.* releases planned at this point. the next release is 1.6

**Comment by mhegazy** [comment]
This should be resolved in #4086  as @kitsonk mentioned. closing.

**Comment by jasonwilliams200OK** [comment]
> Personally I would like a fix in 1.5 since it can be released faster than 1.6 .

How about right now? Run:

```
npm install -g Microsoft/TypeScript
```

anytime to download, build and install the fresh package from this github repository.

See `npm install` documentation for its special behavior with github: https://docs.npmjs.com/cli/install

**Comment by NN---** [comment]
@jasonwilliams200OK I prefer stable build which comes with installer :)

**Comment by jasonwilliams200OK** [comment]
Uhh, in which case you will have to wait for next stable v1.6. Follow the progress here: https://github.com/Microsoft/TypeScript/milestones.
