### ISSUE TITLE
Proposal: specialize a polymorphic function by providing type argument(s) only

### ISSUE THREAD

**Issue by pelotom** [Microsoft/TypeScript#19818]
If you have a polymorphic function, it would be nice to be able to specialize it by just providing type argument(s):

```ts
declare const identity: <A>(x: A) => A;

const numId: identity<number>;
// numId: (x: number) => number
```

You can accomplish this in most (all?) cases by assigning to a variable of the appropriate type

```ts
declare const identity: <A>(x: A) => A;

const numId: (x: number) => number = identity;
```

but the type on the LHS may end up being arbitrarily larger than the simple input type you could've provided on the RHS.

**Comment by mhegazy** [comment]
seems like the same as  https://github.com/Microsoft/TypeScript/issues/15877

**Comment by pelotom** [comment]
@mhegazy as usual @mhegazy is the most effective search engine for duplicates 😜 Seriously though, I promise I'm looking for existing issues first!

**Comment by mhegazy** [comment]
github search is not really helpful.. you need to know what you are looking for in most cases.. it is just that i do this more often :D
