### ISSUE TITLE
Enum type deduction fails when checked in condition

### ISSUE THREAD

**Issue by OmarTawfik** [Microsoft/TypeScript#19827]
```typescript
enum language {
    english,
    french,
    german
}

function getter(): language | undefined {
    return undefined;
}

let l: language | undefined;
while ((l = getter()) && l !== language.english) {
}
```
[Link for live repro](https://www.typescriptlang.org/play/#src=enum%20language%20%7B%0D%0A%20%20%20%20english%2C%0D%0A%20%20%20%20french%2C%0D%0A%20%20%20%20german%0D%0A%7D%0D%0A%0D%0Afunction%20getter()%3A%20language%20%7C%20undefined%20%7B%0D%0A%20%20%20%20return%20undefined%3B%0D%0A%7D%0D%0A%0D%0Alet%20l%3A%20language%20%7C%20undefined%3B%0D%0Awhile%20((l%20%3D%20getter())%20%26%26%20l%20!%3D%3D%20language.english)%20%7B%0D%0A%0D%0A%7D#src=enum%20language%20%7B%0D%0A%20%20%20%20english%2C%0D%0A%20%20%20%20french%0D%0A%7D%0D%0A%0D%0Afunction%20getter()%3A%20language%20%7C%20undefined%20%7B%0D%0A%20%20%20%20return%20undefined%3B%0D%0A%7D%0D%0A%0D%0Alet%20l%3A%20language%20%7C%20undefined%3B%0D%0Awhile%20((l%20%3D%20getter())%20%26%26%20l%20!%3D%3D%20language.english)%20%7B%0D%0A%0D%0A%7D)

**Expected**: Code compiles fine.
**Actual**: Error: 'Operator '===' cannot be applied to types 'language.english and language.french and language.german.'

**Version**: latest npm `2.5.3` and current playground

**Comment by ahejlsberg** [comment]
The issue is that `language.english` has the numeric value 0, which is falsy and therefore never makes it past the `&&` operator. It works if you change your enum to:

```ts
enum language {
    english = 1,
    french,
    german
}
```
