### ISSUE TITLE
Exposing a class as type only in declaration file

### ISSUE THREAD

**Issue by roymiloh** [Microsoft/TypeScript#19822]
Hi,

I'm wondering if it's possible to expose an actual class, that has not exported in the public api (but via a `factory()`), as a type only via declaration files.

Here's a simple example:

__Module A__

```ts
export = ModuleA;

declare namespace ModuleA {
  abstract class SomeBase {
    protected abstract doSmth(): void;
    smth(): void;
  }
}
```

Its usage is straightforward:

```ts
import {SomeBase} from 'module-a';
```

__Module B__

```ts
import {SomeBase} from 'module-a';

declare const w: {
  factory(): ActualThing;
}

declare class ActualThing extends SomeBase {
  protected doSmth(): void;
  smthElse(): void;
}

export = w;
```

And its usage as follow:

```ts
import {factory} from 'module-b';

const actualThing = factory();
```

The problem emerges when I want to assign that `factory()` to an already declared variable or class property, for instance:

```ts
let actualThing: ?;

// later...

actualThing = factory();
```

Question is what I can put instead of `?`. I've been thinking on a workaround, but I'm not sure it's the best one:

__Module A__

```ts
export = ModuleA;

declare namespace ModuleA {
  interface ISomeBase {
    smth(): void;
  }

  abstract class SomeBase implements ISomeBase {
    protected abstract doSmth(): void;
    smth(): void;
  }
}
```

__Module B__

```ts
import {SomeBase, ISomeBase} from 'module-a';

declare const w: {
  factory(): ActualThing;
}

declare namespace w {
  export interface IActualThing extends ISomeBase {
    smthElse(): void;
  }
}

declare class ActualThing extends SomeBase implements IActualThing {
  protected doSmth(): void;
  smthElse(): void;
}

export = w;
```

So then I can:

```ts
import {factory, IActualThing} from 'module-b';

let actualThing: IActualThing = factory();
```

I'm not sure it's scalable tho. I'd like to have some way to expose those internal classes just for the sake of proper typing. Afaik, today it's just impossible.

**Comment by andy-ms** [comment]
If you want a function to not be usable at all as a value, only as a type, then use only an interface and don't bother declaring a class to implement it.

**Comment by mhegazy** [comment]
> The problem emerges when I want to assign that factory() to an already declared variable or class property

The language lacks a way to name the return type of a function or constructor. the best proposal we have so far for this is https://github.com/Microsoft/TypeScript/issues/6606.
