### ISSUE TITLE
Add TypeScriptCompile DependsOn Target to TypeScript Targets

### ISSUE THREAD

**Issue by daub815** [Microsoft/TypeScript#1982]
In the project that I was working on, we used a TextTransform to generate TypeScript classes from our C# classes.  However, I couldn't add the TextTransform Target before the TypeScriptCompile Target because the TypeScriptCompile Target didn't use another property to hook into.  It only was dependent on PreComputerTypeScriptFiles.  

It would be great if the next version provided that property.  If this repository provided that code, I could make the change myself, too.

**Comment by mhegazy** [comment]
Can you provide more details on what you would like to see? would beforeTarget be sufficient?

**Comment by daub815** [comment]
beforeTarget would be sufficient.  Actually, I forgot about using beforeTarget/afterTarget.  I've normally only seen something like this:

```xml
<PropertyGroup>
  <CompileTypeScriptDependsOn>
    $(CompileTypeScriptDependsOn);
   PreComputeCompileTypeScript;
 </CompileTypeScriptDependsOn>
</PropertyGroup>
<Target Name="CompileTypeScript" Condition="'$(BuildingProject)' != 'false'" DependsOnTargets="$(CompileTypeScriptDependsOn)" Inputs="@(TypeScriptCompile)" Outputs="@(GeneratedJavascript)">
    <VsTsc
      ToolPath="$(TscToolPath)"
      ToolExe="$(TscToolExe)"
      Configurations="$(TypeScriptBuildConfigurations)"
      FullPathsToFiles="@(TypeScriptCompile)"
      YieldDuringToolExecution="$(TscYieldDuringToolExecution)"
      OutFile="$(TypeScriptOutFile)"
      OutDir="$(TypeScriptOutDir)"
      ProjectDir="$(ProjectDir)"
      >
      <Output TaskParameter="GeneratedJavascript" ItemName="GeneratedJavascript" />
    </VsTsc>
  </Target>
```

I think in this case the BeforeTarget is sufficient as long as it runs before the PreComputeCompileTypeScript, which I think it does (see [link](http://blogs.msdn.com/b/msbuild/archive/2010/02/18/build-extensibility-with-net-framework-4.aspx) for more details).

**Comment by mhegazy** [comment]
@paulvanbrenk can u take a look.

**Comment by paulvanbrenk** [comment]
This should be in the final release of 1.5 for both Visual Studio 2013 and 2015.

**Comment by daub815** [comment]
Thanks.  I'll look for it when the final release comes out.
