### ISSUE TITLE
Union type method parameters in base class accepts incompatible types in subclass overrides

### ISSUE THREAD

**Issue by asmundg** [Microsoft/TypeScript#19832]
Using union types in base class method declarations allows override functions that only declare one of the union member types. This produces code that crashes at runtime, even with --strict.

**TypeScript Version:**  2.7.0-dev.20171108

**Code**

```ts
abstract class Base {
    abstract foo(arg: string | number): boolean
}

class C extends Base {
    foo(arg: string): boolean {
        return arg.startsWith("a")
    };
}

const a: Base = new C()
a.foo(1)
```

**Expected behavior:**

Should not compile.

**Actual behavior:**

Compiles and crashes at runtime.

**Comment by ahejlsberg** [comment]
See here for an explanation:

https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-function-parameters-bivariant

Also, see #18654.

**Comment by asmundg** [comment]
Aha, I had missed the part where `--strictFunctionTypes` does not apply to methods. I take it I should stay away from inheritance if I want contravariant parameter checking then.
