### ISSUE TITLE
wrong colorization of "...this." in VS2017

### ISSUE THREAD

**Issue by nippur72** [Microsoft/TypeScript#19834]
the text `...this` is colorized incorrectly in VS2017; in the following image `this` should be blue:

VS2017 CE v15.2 (r26430.13) / TypeScript 2.6:
![image](https://user-images.githubusercontent.com/2598443/32559813-58ef20b4-c4a8-11e7-9c4f-66366a40a7e0.png)

VSCode is okay:
![image](https://user-images.githubusercontent.com/2598443/32559918-99f3a58a-c4a8-11e7-8307-8fd4a5c4a00d.png)

**Comment by mhegazy** [comment]
Colorization issues are tracked under https://github.com/Microsoft/TypeScript-TmLanguage

Closing in favor of https://github.com/Microsoft/TypeScript-TmLanguage/issues/541
