### ISSUE TITLE
Backslash in Template Strings

### ISSUE THREAD

**Issue by tandyjames** [Microsoft/TypeScript#1984]
It's my understanding that the backslash in template strings has no special meaning:
http://www.2ality.com/2012/12/template-strings-xregexp.html

I'm seeing it still works as an escape character in 1.4.

**Comment by DanielRosenwasser** [comment]
[That's not what the draft spec seems to imply.](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-template-literal-lexical-components)

> * The TV of *TemplateCharacter* :: *SourceCharacter* but not one of `` ` `` or `\` or `$` or *LineTerminator* is the UTF-16Encoding (10.1.1) of the code point value of *SourceCharacter*.
> * The TV of *TemplateCharacter* :: `\` *EscapeSequence* is the SV of EscapeSequence.
> * The TV of *LineContinuation* :: `\` *LineTerminatorSequence* is the empty code unit sequence.

And in fact, if you download Firefox Developer Edition, you can try it out and you'll get a syntax error if you try out the string `` `\` ``.
