### ISSUE TITLE
Enum emit: reverse for minification

### ISSUE THREAD

**Issue by alexsasharegan** [Microsoft/TypeScript#19848]
**TypeScript Version:**  2.6.1

**Code**

A standard typescript enum looks as follows:

```ts
enum Example {
    SomethingVeryLong,
    SomethingVeryVerbose,
    SomethingSupercalifragilisticexpialidocious
}

// emit:
var Example;
(function (Example) {
    Example[Example["SomethingVeryLong"] = 0] = "SomethingVeryLong";
    Example[Example["SomethingVeryVerbose"] = 1] = "SomethingVeryVerbose";
    Example[Example["SomethingSupercalifragilisticexpialidocious"] = 2] = "SomethingSupercalifragilisticexpialidocious";
})(Example || (Example = {}));
```

**Expected behavior:**

Having the emitted code reverse the assignment could yield better minification. It's a micro-optimization perhaps, but I see no functionality difference whatsoever, so why not improve it?

```ts
var Example;
(function (Example) {
    Example[Example[0] = "SomethingVeryLong"] = 0;
    Example[Example[1] = "SomethingVeryVerbose"] = 1;
    Example[Example[2] = "SomethingSupercalifragilisticexpialidocious"] = 2;
})(Example || (Example = {}));

// minified:
var Example;!function(e){e[e[0]="SomethingVeryLong"]=0,e[e[1]="SomethingVeryVerbose"]=1,e[e[2]="SomethingSupercalifragilisticexpialidocious"]=2}(Example||(Example={}));
```

**Actual behavior:**

```ts
// emit:
var Example;
(function (Example) {
    Example[Example["SomethingVeryLong"] = 0] = "SomethingVeryLong";
    Example[Example["SomethingVeryVerbose"] = 1] = "SomethingVeryVerbose";
    Example[Example["SomethingSupercalifragilisticexpialidocious"] = 2] = "SomethingSupercalifragilisticexpialidocious";
})(Example || (Example = {}));

// minified:
var Example;!function(e){e[e.SomethingVeryLong=0]="SomethingVeryLong",e[e.SomethingVeryVerbose=1]="SomethingVeryVerbose",e[e.SomethingSupercalifragilisticexpialidocious=2]="SomethingSupercalifragilisticexpialidocious"}(Example||(Example={}));
```

**Comment by mhegazy** [comment]
Please see discussion in https://github.com/Microsoft/TypeScript/issues/2655

**Comment by evmar** [comment]
@mhegazy I think maybe you misunderstood, this is just about TS generating smaller code separately from any postprocessing step.  But it would fix #2655.

**Comment by mhegazy** [comment]
enum values can be expressions, and thus can have side effects.. this why the value is only listed once in the output.  we could specialize these and capture their value in a temp first, but that needs to be taken into consideration.

I believe #2655 tracks changing the emit for enums for use of minifiers, be it closure or uglify. this is just a modified proposal for that issue. we are still open to reconsider the enum emit, but we should keep the discussion in one issue.

**Comment by alexsasharegan** [comment]
It looks like the scope of this suggestion goes a little beyond my understanding. This was just an idea for improved minification since usually incrementing number values are more terse than string keys. Feel free to close this issue in preference to the previous ref.

FWIW, I wouldn't mind support for `enum BadForm { "Nobody should do this" }` being dropped entirely. In my mind, TypeScript exists to add structure to JavaScript, and since Enums aren't native javascript, adding this object key behavior doesn't seem to relevant but rather an implementation side effect.

**Comment by mhegazy** [comment]
> I wouldn't mind support for enum BadForm { "Nobody should do this" } being dropped entirely. In my mind, TypeScript exists to add structure to JavaScript, and since Enums aren't native javascript, 

Well.. we can not do that. we can not change feature behavior and break users at will..
