### ISSUE TITLE
applyCodeActionCommand should not require a file argument

### ISSUE THREAD

**Issue by amcasey** [Microsoft/TypeScript#19845]
The opaque command blob should be self-contained.

**Comment by amcasey** [comment]
FYI @andy-ms @mhegazy

**Comment by andy-ms** [comment]
We need some way of knowing what project to apply the command to. Currently we use `this.getFileAndProject(args)` (see `private applyCodeActionCommand` in `session.ts`), which uses the optional `project` argument but falls back to getting the project associated with `filename`.
We could remove `filename` and make `project` mandatory, but that would be a breaking change. We could alsomake both optional and demand that at least one be specified.

**Comment by amcasey** [comment]
@andy-ms Could we not include the file and/or project in the command itself, making it self-contained?

**Comment by mhegazy** [comment]
We can include the full file path in the command blob we send to the editor.
