### ISSUE TITLE
[typescript] Offer IntelliSense suggestions based on method parameter or local type

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#19855]
_From @rstarkov on November 7, 2017 12:25_

It would be useful if IntelliSense offered suggestions based on the expected type of the expression being edited. Consider the following examples:

    function Foo(thing: Namespace.Stuff.SomeClass) { ... }

    Foo(new |
            ^ here

    let x: Namespace.Stuff.SomeClass;
    x = new |
            ^ here

In these cases, "Namespace.Stuff.SomeClass" should be offered by IntelliSense at the indicated positions.

This behaviour would also be handy for enums: the enum type could be offered in the same contexts as above (without the `new` keyword obviously).

For enums there's another scenario where this would be handy, namely when I'm comparing an enum-typed local or parameter - IntelliSense should offer the enum type for autocompletion after I type the comparison operator.

_Copied from original issue: Microsoft/vscode#37771_

**Comment by mjbvz** [comment]
Moved over to TypeScript for further discussion

**Comment by mhegazy** [comment]
Made a related comment a few days ago in https://github.com/Microsoft/TypeScript/pull/16864#pullrequestreview-74953293
