### ISSUE TITLE
Homepage. Visual Studio Code icon change needed

### ISSUE THREAD

**Issue by GRiMe2D** [Microsoft/TypeScript#19866]
Visual Studio Code updated their logo to [blue again][1]. But homepage shows orange icon
![screen shot 2017-11-09 at 1 19 49 pm](https://user-images.githubusercontent.com/6705445/32600660-63ad6f3e-c551-11e7-9e91-8aeaa872009a.png)

[1]: https://code.visualstudio.com/updates/v1_18#_blue-logo-for-stable

**Comment by mhegazy** [comment]
should be updated now.
