### ISSUE TITLE
File reference error when using tsc -d

### ISSUE THREAD

**Issue by k8w** [Microsoft/TypeScript#19862]
**TypeScript Version:**  2.7.0-dev.201xxxxx
2.6.1
**Code**

|- index.ts
```ts
/// <reference path="global.d.ts" />
```

|-global.d.ts
```ts
declare type Test = {};
```

|-tsconfig.json
```json
{
  "compilerOptions": {
    "target": "es5",
    "outDir": "dist",
    "declaration": true
  }
}
```

**Expected behavior:**
Emit three file:
- dist/index.js
- dist/global.d.ts
- dist/index.d.ts

dist/index.d.ts:
```ts
/// <reference path="global.d.ts" />
```

**Actual behavior:**
- Only emit 2 files (no `global.d.ts`)
- reference path error:

dist/index.d.ts
```ts
/// <reference path="../global.d.ts" />
```

Should be `global.d.ts` rather than `../global.d.ts`

**Comment by mhegazy** [comment]
> Should not be `global.d.ts` rather than `../global.d.ts`

No. the compiler does not generate outputs for `.d.ts` files, so when it writes references, it references the place it read them from.

if you want that to be moved, make `global.d.ts` a `global.ts`

**Comment by k8w** [comment]
While `global.d.ts` is some global declaration such as
```ts
declare global {
  var Test: any;
}
```

So if I make it to `global.ts`, it would not works.

And I have set `declaration` to be `true` in `tsconfig.json`, why compiler not generate `.d.ts` ? My `index.ts` have a `index.d.ts` output.

**Comment by mhegazy** [comment]
> While global.d.ts is some global declaration such as
> So if I make it to global.ts, it would not works.

why? if the file is a module it should work.. make sure you have an `export {}` somewhere in the file.. otherwise you are already in the global scope, and you do not need `declare global` block.


> And I have set declaration to be true in tsconfig.json, why compiler not generate .d.ts ? My index.ts have a index.d.ts output.

cause a .d.ts is not a "source", you would not want every time you build you get a file called `lib.d.ts` in your output, or `node\index.d.ts`...
