### ISSUE TITLE
Question: Typescript preview window not working properly

### ISSUE THREAD

**Issue by DaClan008** [Microsoft/TypeScript#1986]
I have a project with the following typescript properties:
- Redirect JavaScript output to directory: Scripts
- Specify root directory of TypeScript files: Ts

There are several folders in the Ts folder and all ts files in the separate folders compile great.  I love the fact that for instance a ts file that is created in Ts/Functions gets compiled to Scripts/Functions.

PROBLEM:  if I open a .ts file that is placed in a subfolder of Ts the preview window is not working, with result given as "// Not compiled to disk".
ps.  The preview window works fine for ts files generated in the Ts folder itself.

Searching the internet, the closest issue is - https://github.com/madskristensen/WebEssentials2013/issues/1166 - with no real solution.

QUESION:  Is this standard behaviour or is this a bug that need fixing, or is there some work around?

I have already tried the last suggested approach on the above link without success (selecting "Automatically compile TypeScript files which are not part of a project") - this does not make sense in anyway as the typescript files gets generated.

This is not a major issue as much as an annoyance, and I can open up the js file next to the ts file though.  Am just curious if I am missing something.

**Comment by NoelAbrahams** [comment]
As far as I know the preview window is not supported by the TypeScript team. It used to be a web essentials feature.

IMO the preview window appears interesting when initially starting with TypeScript, but really does not serve a useful purpose thereafter. It is as useful as wanting to inspect IL when writing C# code.

**Comment by DaClan008** [comment]
Yes I agree it is not very useful per se, and as mentioned it is not a major issue, but an annoyance:
1.  It feels like something is broken either with the code.  In the past I believe if your js file did not compile due to some error, the preview window showed exactly the same message
2.  It feels like something is broken with VS or some component.  I.e. the option is there to view it in a preview window, then one would expect it to work?  This might be more my OCD side talking, but I'd prefer things to work correctly - that is if the feature is available.
3.  Yes I agree it was mostly interesting initially starting with TS, however I do find myself (however seldom) referring back to the js file.  Especially I guess when trouble shooting.  

As mentioned it is not a major issue not having it, it is more of an annoyance having a screen that sends "mixed signals".

My Question is really:
1.  if this is standard (which I guess from your answer it seems to be?), 
2.  if not is it a bug (which I guess from your answer if it is - it does not lie with TS?).  
3.  And finally if there is some workaround (which I guess their isn't, because the issue came in with TS taking the reigns from web essentials and it's no longer a feature TS is interested in supporting?)

**Comment by DanielRosenwasser** [comment]
I'm going to say this is a bug with Web Essentials and you can file an issue in [the appropriate repository](https://github.com/madskristensen/WebEssentials2013).

**Comment by danquirk** [comment]
We don't control Web Essentials, sounds like a fix needs to be made on their end.
