### ISSUE TITLE
"Extract" should be translated to "提取" instead of "解压缩"

### ISSUE THREAD

**Issue by johnliu2016** [Microsoft/TypeScript#19863]
Clone of https://github.com/Microsoft/vscode/issues/37879

**Comment by johnliu2016** [comment]
Issue happens in https://github.com/Microsoft/TypeScript/blob/master/src/loc/lcl/chs/diagnosticMessages/diagnosticMessages.generated.json.lcl#L3187

**Comment by johnliu2016** [comment]
Created internal tracking work item https://devdiv.visualstudio.com/DevDiv/Default/_workitems/edit/522187

**Comment by tycho01** [comment]
to add, 解压缩 is specifically about extracting compressed archives like zip files. seems there's 6 instances in that .lcl file.

**Comment by mhegazy** [comment]
//cc @danyeh

**Comment by lukaschal** [comment]
All occurrences translated as "提取" now.

**Comment by lukaschal** [comment]
Fixed. 

https://github.com/Microsoft/TypeScript/blob/master/src/loc/lcl/chs/diagnosticMessages/diagnosticMessages.generated.json.lcl
