### ISSUE TITLE
Auto-generated declarations file bug?

### ISSUE THREAD

**Issue by jamiewinder** [Microsoft/TypeScript#1987]
I'm trying to reference a generated declaration file, but it doesn't seem to be working how I'd expect. It looks a bit like a bug:

*modulea.ts*
```typescript
class ClassA
{
    public get id(): string
    {
        return "ClassA";
    }
}
export = ClassA;
```

*moduleb.ts*
```typescript
/// <reference path="modulea.d.ts" />
var a = new ClassA(); // Error - Cannot find name ClassA
```

The auto-generated declaration file for modulea.ts is:

*modulea.d.ts*
```typescript
declare class ClassA {
    id: string;
}
export = ClassA;
```

If I remove the export = ClassA line, then everything works just fine... until I save and it gets regenerated of course!

I'm aware that in this example I can use 'import ClassA = require("modulea");' but in my actual situation I just want to know the types (for reasons that I can explain if required)

**Comment by danquirk** [comment]
```export=``` makes modulea an external module, so you must import it for this to work. Note that if you import a module and only use its results in type position then the import will be elided to avoid the cost of loading the module at runtime for no reason. Ex:

a.ts:
```ts
import ClassA = require('moduleb');
var a: ClassA;
```
emits only this in a.js:
```ts
var a;
```
