### ISSUE TITLE
Can't cast array to array subtype

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#19873]
**TypeScript Version:**  2.7.0-dev.20171109

**Code**

```ts
interface I extends Array<number> { x: number }
const x = [] as I;
```

**Expected behavior:**

No error.

**Actual behavior:**

```
src/a.ts(2,11): error TS2352: Type 'never[]' cannot be converted to type 'I'.
  Property 'x' is missing in type 'never[]'.
```

**Comment by mhegazy** [comment]
The way type assertion works today is that it checks that at least one of the types is assignable to the other..  that usually means you can move up or down to a more specialized or less specialized type, (`I` => `number[]` 
 or `number[]` => `I`) but not side ways .

That said, @ahejlsberg is working on changing the comparable relationship to make it more permissive. by basically allowing all casts, unless we can prove that they are disjoint. that implies not checking non-shared propeortes, e.g. `x` in your example. so this should be allowed under the new proposal.
