### ISSUE TITLE
unexpected reference..types directive emitted when --types is not specified

### ISSUE THREAD

**Issue by aluanhaddad** [Microsoft/TypeScript#19874]
**TypeScript Version:**  2.7.0-dev.20171109

When generating declaration files that depend on `@types` that are imported in the source code as modules, the resulting `.d.ts` files contain both an `import dep = require("dep")` and a `/// <reference types="dep" /> directive unless the `--types` is explicitly specified with a value excluding `"dep"`.

Repro at https://github.com/aluanhaddad/typescript-issue-19874

**Code**
To reproduce first run
```shell
> tsc --init
> npm install --save minimist @types/minimist @types/node
```
then create `parse-args.ts`
```ts
import minimist = require('minimist');
import process = require('process');

export default function parseArgs(): minimist.ParsedArgs {
  return minimist(process.argv.slice(2));
}
```
and finally run
```shell
> tsc --declaration --project .\tsconfig.json
```

**Expected behavior:**
`parse-args.d.ts` contains
```ts
import minimist = require('minimist');
export default function parseArgs(): minimist.ParsedArgs;
```
**Actual behavior:**
`parse-args.d.ts` contains
```ts
/// <reference types="minimist" />
import minimist = require('minimist');
export default function parseArgs(): minimist.ParsedArgs;
```

The following, however, produces the expected output.

```shell
> tsc --declaration --project .\tsconfig.json --types node
```

**Remarks:**
There is a workaround, specifying `--types` explicitly, but I find the behavior surprising especially since `@types/minimist` only exposes itself using `export =`.

This implies that many declaration files needlessly emit both an `import` and a `/// <reference types="dep" />` which makes them incompatible with `--paths`.

**Comment by mhegazy** [comment]
Technically this is working as intended.. without `--types` all `@types` packages are added  to the context, regardless if you import them or not. At emit time, the `/// <reference types=... />` is written if anything in the output depends on something that came form an `@types` package in the input.

We could add an extra check to exclude modules that do not have any global augmentation since the only way to use these or witness their effects is through an import anyways.

PRs welcomed.

**Comment by aluanhaddad** [comment]
> We could add an extra check to exclude modules that do not have any global augmentation since the only way to use these or witness their effects is through an import anyways.

So just to clarify, is the  expectation that a declaration file that contains globally scoped declarations would always be referenced if any of its types are consumed? Does this apply to `declare global` blocks and ambient external modules as well?

**Comment by mhegazy** [comment]
> So just to clarify, is the expectation that a declaration file that contains globally scoped declarations would always be referenced if any of its types are consumed? Does this apply to declare global blocks and ambient external modules as well?

If any name used in the declaration file originated from a file under `@types` a `/// <refernece types=".." />` will be added to the output.

**Comment by aluanhaddad** [comment]
By name do you mean globally scoped name? I think I'm missing your point somehow...

**Comment by mhegazy** [comment]
name, meaning identifier. does not matter which scope it is in.
