### ISSUE TITLE
clashing HKT tag inferences glossed over

### ISSUE THREAD

**Issue by tycho01** [microsoft/TypeScript#19871]
Minimum repro based on https://github.com/gcanti/fp-ts/issues/204#issuecomment-343066911, also featuring @gcanti's HKT hack from https://github.com/Microsoft/TypeScript/issues/1213#issuecomment-338379577.

**TypeScript Version:** 2.6.1-insiders.20171019 (Playground)

**Code**
```ts
interface Applicative<F> {}

interface HKT<URI, A> {
  _URI: URI
}

interface Either<L, A> {
  _URI: 'Either'
}
let right: <L, A>(a: A) => Either<L, A>

interface Option<A> {
  _URI: 'Option'
}
let some: <A>(a: A) => Option<A>
let option: Applicative<'Option'>

// 'curried' version
declare function traverse1<F>(F: Applicative<F>): <A, B>(f: (a: A) => HKT<F, B>) => any
let x1 = traverse1(option)(a => some(a)) // HKT<"Option", number[]>
let x2 = traverse1(option)(a => right(a)) // error :)

// uncurried version
declare function traverse2<F, A, B>(F: Applicative<F>, f: (a: A) => HKT<F, B>): any
let x3 = traverse2(option, a => right(a)) // no error :(, HKT<"Option" | "Either">
```

**Expected behavior:** error, probably by intersecting the forward/backward inferences into `"Option" & "Either"` then realizing there is no valid intersection.

**Actual behavior:** forward and backward tag inferences are reconciliated as `"Option" | "Either"`, causing the `x3` to (erroneously) pass.

**Comment by SimonMeskens** [comment]
I wonder if this has been looked at yet

**Comment by RyanCavanaugh** [comment]
Picking the largest type among the inference candidates is foundational to the inference algorithm. You'd want #14829 to make the second reference to `F` be excluded from the candidate set.
