### ISSUE TITLE
Comparing == null does not work as type guard when explicitNullChecks is disabled

### ISSUE THREAD

**Issue by UselessPickles** [Microsoft/TypeScript#19876]
**TypeScript Version:**  2.6.1

**Code**

(with "strictNullChecks" disabled)

```ts
function foo(value: number | null | undefined): string | null | undefined {
    if (value == null) {
        return value;
    }

    return value.toString();
}
```

**Expected behavior:**
Compile without errors.

**Actual behavior:**
"Type 'number' is not assignable to 'string'" at the "return value" line

![screen shot 2017-11-09 at 1 35 34 pm](https://user-images.githubusercontent.com/22800095/32623082-f86d2352-c552-11e7-948a-a170688b7e6b.png)

Enabling "strictNullChecks" causes the code to compile without error, but I unfortunately cannot enable strictNullChecks in my project due to a 3rd party typescript library that was not designed with structNullChecks.

**Comment by UselessPickles** [comment]
To clarify, I would expect that double equal (==) comparison to null would act as a type guard that confirms to the compiler that the value must be either null or undefined. I would expect this regardless of whether "strictNullChecks" is enabled.

**Comment by aluanhaddad** [comment]
When `--strictNullChecks` is not enabled, every type implicitly includes `null` and `undefined`. Therefore, from a type level perspective, the function
```ts
declare function foo(value: number | null | undefined): string | null | undefined;
```
is equivalent to
```ts
declare function foo(value: number): string;
```
The only difference is that the former is more self-documenting.

**Comment by UselessPickles** [comment]
@mhegazy Could you explain how this is "working as intended"?

Inside the "if (value == null)", value is guaranteed to not be a number. It is guaranteed to be only null or undefined. null and undefined are both valid return types/values regardless of whether I explicitly list "| null | undefined" as return types, or if they are implied due to implicitNullChecks being disabled. S ohow is it "intended" that the compiler complains that "Type 'number' is not assignable to 'string'", when the value most certainly is not a number?

**Comment by mhegazy** [comment]
> When `--strictNullChecks` is not enabled, every type implicitly includes `null` and `undefined`.

**Comment by mhegazy** [comment]
see https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#null--and-undefined-aware-types for more details.

**Comment by UselessPickles** [comment]
I understand that every type implicitly includes null and undefined. How is that related to the compiler error I am experiencing?

I am returning "value" from within an if block that checks if "value == null". "value" is therefore guaranteed to be null or undefined - NOT a number. Why is the compiler complaining that number cannot be assigned to string?

The value I am returning is either null or undefined. The return type of the function allows both null and undefined. What is the problem?

**Comment by UselessPickles** [comment]
Maybe this will clarify my confusion. With "strictNullChecks" disabled, this code compiles:

```ts
function foo(value: number): string {
    if (value === null) {
        return null;
    }

    return value.toString();
}
```

But this code causes a compiler error:
```ts
function foo(value: number): string {
    if (value === null) {
        return value;
    }

    return value.toString();
}
```

Why is this "intended"? Shouldn't I expect that type guards should work?

**Comment by aluanhaddad** [comment]
To say that every type implicitly includes `null` and `undefined`, means that `null` and `undefined` are valid values of type `number` just like `1` and `2`.
So when `--strictNullChecks` is not enabled the following code will typecheck
```ts
const x: null = null;

const y: number = null;

foo(x);

foo(y);

declare function foo(x: number): void;
```
It typechecks because `null` _is_ a number.

**Comment by UselessPickles** [comment]
This sounds like you are providing insight into some technical implementation details that cause the behavior to be what I am experiencing, but it does not explain why this is the "intended" behavior.

To further the confusion, this causes a compiler error with strictNullChecks disabled:
```ts
function foo(value: number): string {
    if (value === null) { // not acting as a type guard
        // compiler still thinks "value" is of type "number" rather than type "null"
        return value;
    }

    return value.toString();
}
```

but this is perfectly valid:
```ts
function isNull(value: any): value is null {
    return value === null;
}

function foo(value: number): string {
    if (isNull(value)) { // custom type guard works as expected
        // Compiler knows that "value" is of type "null"; not a "number"
        return value;
    }

    return value.toString();
}

function bar(value: number): string {
    if (isNull(value)) {
        // Even with custom type guard forcing the compiler to understand "value"
        // is REALLY "null", it's still valid to pass as a number param to foo().
        // So why can't (value === null) work the same as isNull(value)
        return foo(value);
    }

    return value.toString();
}
```

This seems very inconsistent.

**Comment by UselessPickles** [comment]
@aluanhaddad @mhegazy  Please review my previous comment. I believe this most clearly demonstrates what I perceive as incorrect/inconsistent behavior. Is there an "intentional" reason that the behavior of "=== null" cannot be updated to produce the same outcome as my custom "isNull" typeguard in my previous example?

The behavior around my "isNull" custom type guard is exactly what I expected when using "=== null".

**Comment by aluanhaddad** [comment]
> This sounds like you are providing insight into some technical implementation details that cause the behavior to be what I am experiencing, but it does not explain why this is the "intended" behavior.

Actually, it's quite the opposite. What I was explaining was the conceptual reason for the behavior not the implementation.

Imagine `null` represents the empty set. For any set A, it is meaningless to check if the empty set is a subset of A as it is true by the definition of a set.

**Comment by UselessPickles** [comment]
That completely makes sense to me... however, it also seems completely irrelevant to the issue I am highlighting. Let's break this down simply into what I am seeing:

1. In strictNullChecks=false mode, null is implicitly a valid value for all data types.
2. Inside of the `if (value === null)` block, it is quite clear that the value is, in fact, null.
3. Given 1. and 2. above, it does not make sense that the compiler will not allow me to return the value as a string (which implicitly allows null as a value).  

If I return a literal null, there's no compiler error, because null is a valid value for string. So why can't I return my number "value" variable from within an if block that explicitly confirms that the value is null?

If I write my own custom type guard that explicitly tells compiler that the value is null, then I get the behavior I expect. Why does the built-in equality operator with a literal null value NOT tell the compiler that the value is null? It is a very direct and explicit test of whether the value is null.

I also noticed that the compiler does not complain at all if I try to access properties from within my `if (value === null)`. How could this possibly be "working as intended"?

```ts
function foo(value: number): string {
    if (value === null) { // not acting as a type guard
        // compiler lets me access properties of a null value.
        return value.toString(16);
    }

    return value.toString();
}
```

**Comment by RyanCavanaugh** [comment]
@UselessPickles based on your description, what you're missing is how pre-`strictNullChecks` checking works.

With SNC off, **there is no distinction about whether a value is null or not**. There's no distinctions, anywhere, about what `null` means, whether something has been determined to be `null` or not, or when something may or may not be `null`. It's just completely untracked; type guards checking for `null` do nothing.

**Comment by UselessPickles** [comment]
@RyanCavanaugh Thanks! The historical behavior helps make sense of this. However, none of the documentation I have found about "strictNullChecks" explains this. It is only described in terms of forcing you to explicitly specifying null/undefined types where null/undefined should be allowed.

I would now agree that "strictNullChecks=false" is "working as intended" in the "pre-strictNullChecks" era, but not "working as one would expect" in the "post-strictNullChecks" era.

A couple potential options:

- Improve documentation of "strictNullChecks" to more clearly explain this behavior (with historical context) when it is disabled. This is the simplest bare-minimum improvement that can be made if none of the following options are reasonable.
- Improve behavior of "strictNullChecks=false" to track type guards for null/undefined so that it works as one without historical knowledge would expect. On the surface, this seems like a mostly non-breaking change. The only breaking change I know of so far is my previous example, where the compiler would error on an obvious attempt to access properties of a value that is obviously null due to an explicit type guard.
- If retaining backward compatibility is important, maybe add a 3rd option so that users can choose between "old pre-strictNullChecks" behavior, reasonable/expected behavior for "strictNullCHecks=false", and, of course, current "strictNullChecks=true" behavior.

**Comment by RyanCavanaugh** [comment]
> On the surface, this seems like a mostly non-breaking change. The only breaking change I know of so far is my previous example, where the compiler would error on an obvious attempt to access properties of a value that is obviously null due to an explicit type guard.

The problem here is detailed in #9998 - we would break a decent amount of working non-SNC code that relies on distant side effects to invalidate a null guard
