### ISSUE TITLE
Autoimport does not respect TS re-export files

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#19888]
_From @artaommahe on November 9, 2017 11:25_

- VSCode Version: 1.18.0
- OS Version: Windows 10

Steps to Reproduce:
1. e.x. angular app, write `Component`
2. press enter for autocomplete/autoimport
3. see
```ts
import { Component } from "@angular/core/src/metadata/directives";
```

expected
```ts
import { Component } from "@angular/core";
```

Reproduces without extensions: Yes

_Copied from original issue: Microsoft/vscode#37926_

**Comment by mjbvz** [comment]
_From @artaommahe on November 9, 2017 11:28_

Cant repoduce it with in-project re-export files. Looks like it's wrong only for lib imports

**Comment by mjbvz** [comment]
Possibly another dup of #17705

**Comment by mhegazy** [comment]
seems like a duplicate of https://github.com/Microsoft/TypeScript/issues/19889 https://github.com/Microsoft/TypeScript/issues/19889 and https://github.com/Microsoft/TypeScript/issues/19922 and #17705
