### ISSUE TITLE
Const enum by-const-enum-reference value not elided in incremental build

### ISSUE THREAD

**Issue by jkieboom** [Microsoft/TypeScript#19898]
**TypeScript Version:** 2.7.0-dev.20171109

**Code**

```ts
// file1.ts
export const enum E1 {
  V = 1
}

// file2.ts
import { E1 } from "./file1";

export const enum E2 {
  V = E1.V
}

// file3.ts
import { E2 } from "./file2";

const v: E2 = E2.V;
```

**Expected behavior:**

The value of `v` in `file3` when compiled should always be `1`.

**Actual behavior:**

When running `tsc` in watch mode, when `file3` changes and is recompiled, the resulting javascript now contains `v = E2.V` instead of the constant `1`, and fails at runtime with an unknown reference.

**Comment by mhegazy** [comment]
@sheetalkamat can you take a look.. let's try to get a fix in 2.6.2 for this

**Comment by mhegazy** [comment]
@jkieboom  please give tomorrow's `typescript@next` a try and let us know if you are still running into issues.

**Comment by jkieboom** [comment]
I can confirm that `typescript@next` fixes the issue, thanks a lot for the very quick response!
