### ISSUE TITLE
Add a "Do's and Don'ts" hint to "Basic Types: Any -> Object"

### ISSUE THREAD

**Issue by ndresx** [microsoft/TypeScript#19908]
I find it a bit confusing that the "Any" section under ["Basic Types"](https://www.typescriptlang.org/docs/handbook/basic-types.html) is freely speaking about the `Object` type although it's recommended to not use it anymore. 

```js
let prettySure: Object = 4;
prettySure.toFixed(); // Error: Property 'toFixed' doesn't exist on type 'Object'.
```

Might be helpful to add a link to the ["Do's and Don'ts"](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html) page below the example which states that you should avoid using `Object` at all - if this makes sense.

**Comment by GuyKh** [comment]
On it
