### ISSUE TITLE
Type inference in generic type match with default type and optional key

### ISSUE THREAD

**Issue by hapood** [Microsoft/TypeScript#19903]
**TypeScript Version:**  2.6.1

**Code**

```ts
interface Box<B=number> {
  b?:B
}

function check<B>(x:Box<B>):B {
  return x.b as B
}

let a1 =check({b:"aaa"}); 
let a2 =check({}); 
```

**Expected behavior:**
a1 is string and a2 is number

**Actual behavior:**
a1 is string and a2 is {}

**Comment by andy-ms** [comment]
I thinhk this is intended behavior. If you want `check` to default to number you need to write `function check<B=number>...`.
