### ISSUE TITLE
Inlining Imports In Typescript

### ISSUE THREAD

**Issue by OguzDerin** [Microsoft/TypeScript#19905]
**TypeScript Version:**  2.6.1
## Problem
Inlining types like const enums make TypeScript viable for writing high-performance, single file JavaScript web apps. I have two files, one for index and one for worker but I want to share inlined enums and classes between two. I tried module export/imports but I could not find a way to inline my imports. I have tried outFile but it just generates wrappers that I could not disable. Is there a way to accomplish this right now? Thanks.
## Example
**TypeScript File**
```ts
import { CommonEnum, CommonClass } from "../common/common"

let usageOfImportedEnum = CommonEnum.MIN;

let usageOfImportedClass = new CommonClass();
```

**Expected behavior:**
```ts
"use strict";
class CommonClass {
    constructor() {
        console.log('Hi');
    }
}
let usageOfImportedEnum = 0 /* MIN */;
let usageOfImportedClass = new CommonClass();
```
**Actual behavior:**
```ts
define("common/common", ["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    class CommonClass {
        constructor() {
            console.log('Hi');
        }
    }
    exports.CommonClass = CommonClass;
});
define("index/index", ["require", "exports", "common/common"], function (require, exports, common_1) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    let usageOfImportedEnum = 0 /* MIN */;
    let usageOfImportedClass = new common_1.CommonClass();
});
```

**Comment by andy-ms** [comment]
See the [design goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).
There are already other tools that will bundle modules.
