### ISSUE TITLE
js auto-import bug

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#19919]
_From @dev-fang on November 9, 2017 18:9_

- VSCode Version: 1.18.0
- OS Version: Windows 10

Js auto import works well with  
 `export default class className {}`
doesn't work with
`class className{}`
`export default className`

Steps to Reproduce:
1. Create a file called test1.js
2. Type in 
`class Test1{}`
`export default className`
3. Create a file called test2.js
4. Type in new Test1, the auto import suggestion doesn't show up

Reproduces without extensions: Yes

_Copied from original issue: Microsoft/vscode#37974_

**Comment by mhegazy** [comment]
Worth noting that with https://github.com/Microsoft/TypeScript/pull/19883 in place, if the file name is the same as the class name (`className` in this example) it will work.

**Comment by DanielRosenwasser** [comment]
This also seems to be a bug with the quick fix as well.

**Comment by andy-ms** [comment]
Completions fixed by #20987. Import fix is #19115.
