### ISSUE TITLE
Type information is lost when using const enum as computed property

### ISSUE THREAD

**Issue by molinger** [Microsoft/TypeScript#19938]
**TypeScript Version:**  2.7.0-dev.20171110

**Code**

```ts
// tsc index.ts
interface ShapeDescriptor {
    roundness: 'pointy' | 'round';
}

const enum ShapeType {
    square = 'square',
    circle = 'circle'
}

type ShapeDescriptors = {
    [prop in ShapeType]: ShapeDescriptor;
};

const descriptors: ShapeDescriptors = {
    [ShapeType.square]: { roundness: 'pointy'},
    [ShapeType.circle]: { roundness: 'round' }
}
```

**Expected behavior:**
No errors

**Actual behavior:**
> tsc index.ts

>index.ts(14,7): error TS2322: Type '{ [ShapeType.square]: { roundness: string; }; [ShapeType.circle]: { >roundness: string; }; }' is not assignable to type 'ShapeDescriptors'.
>  Types of property 'square' are incompatible.
>    Type '{ roundness: string; }' is not assignable to type 'ShapeDescriptor'.
>      Types of property 'roundness' are incompatible.
>        Type 'string' is not assignable to type '"pointy" | "round"'.

**Other notes**
typescript@2.5.3 returns 'Property 'square' is missing in type '{ [x: string]: { roundness: string; }; }'.'
typescript@2.6.1 returns same error as typescript@next.

The following succeeds in typescript@next:
```ts
interface ShapeDescriptor {
    roundness: 'pointy' | 'round';
}

type ShapeType = 'square' | 'circle';

type ShapeDescriptors = {
    [prop in ShapeType]: ShapeDescriptor;
};

const descriptors: ShapeDescriptors = {
    ['square']: { roundness: 'pointy'},
    ['circle']: { roundness: 'round' }
}
```

**Comment by mhegazy** [comment]
Should be fixed in latest.
