### ISSUE TITLE
No way to createProgram from files with extensions other than typescript extensions (such as .vue).

### ISSUE THREAD

**Issue by prograhammer** [Microsoft/TypeScript#19936]
**TypeScript Version:**  latest

**Expected behavior:**
Ability to call `ts.createProgram` for typechecking on a file without a `.ts` extension. For example, a `.vue` file (the **vue** file would have been stripped down through webpack loader chain and contains only valid TypeScript in it by the time **createProgram** is called on it).

**Actual behavior:**
Doesn't work with .vue files. For example, `program.getSourceFile(fileName)` will return undefined on anything other than valid typescript extensions.

Ultimately my goal is to do my own linting on .vue files.

**Comment by mhegazy** [comment]
The compiler makes assumptions about file extensions in module resolution and in output generation.. this is why `createProgram` validates the extensions of input files.

if all you want is to lint, then you do not realy need a `Program`, all you need is a `SourceFile`, so consider using `createSourceFile` instead.

**Comment by prograhammer** [comment]
Some linting requires the typechecker so I can't go the route of just using createSourceFile. For single file components (.vue) is my only solution to pull out the TypeScript and put it into it's own file (.ts) and just import it into the .vue file then? This is unfortunate.

**Comment by sheetalkamat** [comment]
But ```createProgram``` does take ```CompilerHost``` as optional argument and you could specify that host to  with your specific ```getSourceFile``` and ```resolveModuleName``` to handle this. Would that not work?

**Comment by prograhammer** [comment]
Hmmm... ok @sheetalkamat maybe there is a solution there. Let me try that! I'll close this issue and report a new issue if I find TypeScript blocking me further. Thank you!
