### ISSUE TITLE
Use  `[Type]Constructor for HTMLElement type declarations

### ISSUE THREAD

**Issue by olivierr91** [microsoft/TypeScript#19949]
HTMLElement type declaration in lib.d.ts should be `HTMLElementConstructor` instead of `declare var HTMLElement`, so we can extend the type with static methods (`HTMLElement.myMethod = function() : {}`)

**Comment by orobert91** [comment]
I'd also add, why not do it for everything in lib.d.ts? I've encountered many other types (like XMLHttpRequest) that I can't extend due to their typing declarations.

**Comment by RyanCavanaugh** [comment]
There seems to be very little interest for this; declining.
