### ISSUE TITLE
TypeScript doesn't recognise Uint8ClampedArray

### ISSUE THREAD

**Issue by webbedspace** [Microsoft/TypeScript#1995]
```var a = new Uint8Array(7);``` works, ```var a = new Uint8ClampedArray(7);``` produces an error.

**Comment by webbedspace** [comment]
I've since learned that setting ES6 as the compile target causes it to work... however, since the other array sizes work, it's arguable that this is an unnecessary restriction.

**Comment by SaschaNaz** [comment]
I hope there is an option to force the compiler use ES6 declarations while still giving ES5 output. There are browsers that natively support, for example, `Promise`, without full ES6 syntax support.

**Comment by mhegazy** [comment]
@SaschaNaz you can always augment your program with additional types that you know would exist on your target system. for instance, if you know you are always running on an engine that supports promises, just add declarations for Promise<T> in your program. The idea is that the lib file reflects the baseline of engines supporting the target of the compilation (ES5 v.s. ES6)

**Comment by mhegazy** [comment]
Type definitions added to lib.es6.d.ts
