### ISSUE TITLE
Array typed as `never[]`even when assigned to `number[]`

### ISSUE THREAD

**Issue by ghost** [microsoft/TypeScript#19956]
**TypeScript Version:** 2.7.0-dev.20171112

**Code**

```ts
let xs: number[] | undefined;
function pushIfNotPresent() {
	if (xs) {
		return;
	}
	(xs = []).push(1);
}
```

**Expected behavior:**

No error.

**Actual behavior:**

`src/a.ts(6,17): error TS2345: Argument of type '1' is not assignable to parameter of type 'never'.`

**Comment by caesay** [comment]
This is expected I think: 

```ts
let xs: number[] | undefined;
function pushIfNotPresent() {
        // here the type of xs is "number[] | undefined"
	if (xs) {
		return;
	}
        // here the type of xs is "undefined".
	(xs = []).push(1);
}
```

The fact you've assigned `xs = []` is a runtime concern. You can't assign _anything_ to the type "undefined". That would be akin to doing this:

```
let x: undefined;
x = ""; // can't do this, string is not assignable to undefined
```

**Comment by kitsonk** [comment]
Just to point out that @andy-ms is part of the core team...

If [this works](https://www.typescriptlang.org/play/#src=let%20xs%3A%20number%5B%5D%20%7C%20undefined%3B%0Afunction%20pushIfNotPresent()%20%7B%0A%09if%20(xs)%20%7B%0A%09%09return%3B%0A%20%20%7D%0A%20%20xs%20%3D%20%5B%5D%3B%0A%20%20xs.push(1)%3B%0A%7D) (which it does under strict null checks) then the above should as well:

```ts
let xs: number[] | undefined;
function pushIfNotPresent() {
	if (xs) {
		return;
  }
  xs = [];
  xs.push(1);
}
```

**Comment by kitsonk** [comment]
Also...

> The fact you've assigned `xs = []` is a runtime concern. You can't assign anything to the type "undefined". That would be akin to doing this

Variables (`let` and `var`) types get widened and narrowed on assignment, because they are _variables_.  So the compiler assess if the right hand type is assignable to the left hand type and updates the CFA type at that position, until a further action subsequently changes that type.

**Comment by buola** [comment]
I guess the following is related:

`var a: number[];
var b = a = [];
a.push(1); //OK
b.push(1); //Error (Argument of type '1' is not assignable to parameter of type 'never'.)... should be ok`

**Expected behavior**

No error. Type of b is inferred as number[]

**Actual behavior**

Error because type of b is never[]

**Comment by RyanCavanaugh** [comment]
This isn't really a bug -- empty arrays do really have the type `never[]` and that is the correct behavior.
