### ISSUE TITLE
Suggestion: More narrow type for Math.sign

### ISSUE THREAD

**Issue by kreba** [Microsoft/TypeScript#19954]
The type for `Math.sign` is currently `(x: number): number` as seen in
https://github.com/Microsoft/TypeScript/blob/master/lib/lib.es6.d.ts#L4177

Its type could be `(x: number): -1 | 0 | 1` instead.

That would allow for more specific typing in app code without having to wrap `Math.sign`.

**Comment by aluanhaddad** [comment]
This would be great but
```ts
Math.sign(NaN) // NaN
typeof NaN // "number"
```
which poisons what would otherwise be quite elegant behavior.

**Comment by mhegazy** [comment]
discussed previously in https://github.com/Microsoft/TypeScript/issues/15356

**Comment by kreba** [comment]
Thank you for your immediate response!

I had never considered what happens with `NaN`. Now I understand why it's return type is currently `number`. 

I'll continue wrapping it for my comparators then.
