### ISSUE TITLE
ES6 Map callback parameter type-checking is wrong

### ISSUE THREAD

**Issue by webbedspace** [Microsoft/TypeScript#1996]
[See here](http://www.typescriptlang.org/Playground#src=var%20m%20%3D%20new%20Map%28%29%3B%0Am.set%281%2C2%29%0Am.forEach%28function%20%28value%2C%20key%29%20{%0A%20%20console.log%281%20%2F%20key%2C%201%20%2F%20value%29%3B%0A}%29%3B).
```
var m = new Map();
m.set(1,2)
m.forEach(function (value, key) {
  console.log(1 / key, 1 / value);
});
```
The `1 / key` and `1 / value` things each produce the error `The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.`

**Comment by danquirk** [comment]
The problem is that Map is a generic type but no information is provided upon construction about the types involved. So ```m```'s type is ```Map<{}, {}>``` which means ```value``` and ```key``` are each ```{}``` which is why you can't perform arithmetic on them. You'll need to provide type arguments to Map's constructor function:

```ts
var m = new Map<number, number>();
m.set(1,2)
m.forEach(function (value, key) {
  console.log(1 / key, 1 / value); // no error
});
```

**Comment by webbedspace** [comment]
Isn't TypeScript a "strict superset" of JavaScript, though? Or does it plan to diverge from ES6 for just this particular instance?

**Comment by RyanCavanaugh** [comment]
It's a syntactic superset; the compiler still emits JavaScript. Semantically, though, it is not (otherwise there wouldn't be much point).
