### ISSUE TITLE
Error constructing `C<T extends A>` with `T extends B` if `A` uses a `this` type

### ISSUE THREAD

**Issue by andy-ms** [microsoft/TypeScript#19961]
**TypeScript Version:**  2.7.0-dev.20171112

**Code**

```ts
class A {
	readonly self: this;
}
class B extends A {}

class C<T extends A> {
	t: T;
}

function broke<T extends B>(t: T): C<T> {
    const c = new C<T>(); // Error
    c.t = t;
    return c;
}

function works<T extends B>(t: T): C<T> {
    return { t };
}
```

**Expected behavior:**

No error.

**Actual behavior:**

```
src/a.ts(11,21): error TS2344: Type 'T' does not satisfy the constraint 'A'.
  Type 'B' is not assignable to type 'A'.
    Types of property 'self' are incompatible.
      Type 'B' is not assignable to type 'T'.
```

It *will* work if I change the signature to `broke<T extends A>` and run `broke<B>(new B())`, so logically it should also work with `broke<T extends B>`. `T extends B` is a stricter requirement than `T extends A` so if `T extends A` works, `T extends B` should work too.
There is also no error when using `C` as an interface instead of as a constructor.

**Comment by sandersn** [comment]
Note that adding a property to `B` doesn't make a difference, so it's not some weird equivalence of `A` and `B`.

**Comment by mttcr** [comment]
Another related example:
```ts

class Collection
{
    method(): this 
    {
        return this;
    }
}

class List extends Collection
{
}

class Test
{
    public static test<T extends List>( t: T ): T
    {
        let d = this.test2<T>( t );
        return d;
    }

    public static test2<U extends Collection>( u: U ): U
    {
        return u;
    }
}
```
```
Type 'T' does not satisfy the constraint 'Collection'.
  Type 'List' is not assignable to type 'Collection'.
    Types of property 'method' are incompatible.
      Type '() => List' is not assignable to type '() => T'.
        Type 'List' is not assignable to type 'T'.
``

**Comment by alyahmedaly** [comment]
@RyanCavanaugh any update on this or workaround :)

**Comment by mttcr** [comment]
Testing both snippets (andy-ms commented on 13 Nov 2017 •  mttcr commented on 4 Apr 2018) build without errors on 3.7.3 (since 2.9)
