### ISSUE TITLE
Triple-slash reference affects all files instead of just the one file that contains it.

### ISSUE THREAD

**Issue by qz2017** [Microsoft/TypeScript#19978]
**TypeScript Version:**  2.4.2

**Code**

```ts
/// <reference types="mocha" />
```

**Expected behavior:**
Types from mocha are only available to the test ts file that include this triple-slash reference.

**Actual behavior:**
Types from mocha are available to all the ts files in the project, including both prod code and test code.
This is unexpected. How do we prevent Mocha test types from accidentally getting into prod code?

**Comment by pgonzal** [comment]
We're having the same problem with [Jest](https://facebook.github.io/jest/), which declares even more ambient definitions than **mocha**:  If one unit test does `/// <reference types="mocha" />`, then all the product code can suddenly access these definitions.

**Comment by mhegazy** [comment]
`/// <reference types="mocha" />` is a global directive. it is an alias to `--types` in your tsconfig.json or on the commandline. 

What `mocha` does is it adds declarations to the global scope, and there is no way to tease out what a global means in one module and not the other..

My recommendation here is to have your tests in a separate compilation, and they would include `mocha`.

**Comment by pgonzal** [comment]
> My recommendation here is to have your tests in a separate compilation, and they would **include mocha**.

If we want VS Code IntelliSense for the unit tests, does that mean we need to create a separate **package.json** and/or **tsconfig.json** file?

@iclanton

**Comment by mhegazy** [comment]
`tsconfig.json` is all you need
