### ISSUE TITLE
Smart indentation doesn't respect indentation space settings to two spaces

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#19974]
```ts
switch (10) {/**/
}
````

Set indentation settings to two spaces. Then add a new line after the marker.

**Expected**: Cursor is placed two spaces into the next line.
**Actual**: Cursor is placed four spaces into the next line.

**Comment by andy-ms** [comment]
@DanielRosenwasser I'm having trouble reproducing this in vscode. You should show me this when you're available.

**Comment by DanielRosenwasser** [comment]
Looks like it's fixed now?

**Comment by andy-ms** [comment]
Vscode doesn't seem to be calling into tsserver for this so may be a change on their side.
