### ISSUE TITLE
@types auto install helper not showing up

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#19970]
_From @alan-agius4 on November 11, 2017 12:19_

- VSCode Version: 1.18.0
- OS Version: macOs Sierra 10.12.6

Steps to Reproduce:

1. Create a TypeScript file and insert `import * as cpx from "cpx"`
2. The @types auto installer helper is not showing up

Instead I get this message 
```
Could not find a declaration file for module 'cpx'. '/Users/alan/Documents/speedy-node-core/node_modules/cpx/lib/index.js' implicitly has an 'any' type.
  Try `npm install @types/cpx` if it exists or add a new declaration (.d.ts) file containing `declare module 'cpx'
```
I noticed that for example for `lodash` the auto installer works fine.

Reproduces without extensions: Yes

_Copied from original issue: Microsoft/vscode#38114_

**Comment by mjbvz** [comment]
@types/cpx is fairly new, so its possible the types-registry doesn't have it yet. Let me check on my machine

**Comment by mjbvz** [comment]
Yes with types-registry@0.1.306, I confirmed that there is no entry for cpx

**Comment by alan-agius4** [comment]
Indeed it seems like types-registery@1.306 is a couple if weeks old and the
latest @types are not included

Thanks you.

**Comment by andy-ms** [comment]
Looks like we've got the types-registry problems fixed.
