### ISSUE TITLE
tsc --watch gives diagnostic if file renamed

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#19989]
**TypeScript Version:**  2.7.0-dev.20171112
Tested on Linux Mint 18.

**Code**

Create a project with a `tsconfig.json` of just `{}` and an empty file `src/a.ts`.
Run `tsc --watch`.
Rename `a.ts` to `b.ts`.

**Expected behavior:**

No error.

**Actual behavior:**

`error TS6053: File '/home/andy/sample/ts/src/a.ts' not found.`

CC @sheetalkamat

**Comment by sheetalkamat** [comment]
@andy-ms can you please tryout drop from PR #21243 which adds multiple options using environment variables ```TSC_WATCHFILE``` and ```TSC_WATCHDIRECTORY```. The drop is built and shared at [localBuilt.zip](https://github.com/Microsoft/TypeScript/files/1665024/localBuilt.zip)

The different options are explained in https://github.com/Microsoft/TypeScript/pull/21243#issue-289420637 . Experience and feedback about these options is appreciated and would help us make decision on which strategy to go as default.

**Comment by andy-ms** [comment]
I tried it out and that fixes this issue with the default settings.
Could you add a warning if the option passed to `TSC_WATCHFILE` or `TSC_WATCHDIRECTORY` is invalid? Hard to tell if trying to set those is making any difference.
