### ISSUE TITLE
Impossible the load js from a `node_module` once types for it have been loaded

### ISSUE THREAD

**Issue by weswigham** [Microsoft/TypeScript#19998]
**TypeScript Version:**  2.7.0-dev.201xxxxx

**Code**

Self-contained repro [here](https://github.com/weswigham/node-modules-import-bug)

**Expected behavior:**
I can import the JS files of a module directly if I explicitly reference them.

**Actual behavior:**
Implicit any on a module not found error.

**Comment by mhegazy** [comment]
set ` --maxNodeModuleJsDepth` to `1`.

**Comment by weswigham** [comment]
Op, thanks, that'll do it.
