### ISSUE TITLE
Do not suggest @types installation for relative path with extension in node_modules

### ISSUE THREAD

**Issue by weswigham** [Microsoft/TypeScript#19996]
**TypeScript Version:**  2.7.0-dev.201xxxxx

**Code**

```ts
import discord_js_original_js = require("./node_modules/discord.js/src/index.js");
```

**Expected behavior:**
Ideally no error if the file is loaded, or 
```
index.ts(3,41): error TS7016: Could not find a declaration file for module './node_modules/discord.js/src/index.js'. 'E:/Github/TypeScript/tests/cases/user/discord.js/node_modules/discord.js/src/index.js' implicitly has an 'any' type.
```
If it's not found.

**Actual behavior:**
The above, plus:
```
  Try `npm install @types/./node_modules/discord.js/src/index.js` if it exists or add a new declaration (.d.ts) file containing `declare module './node_modules/discord.js/src/index.js';`
```
Both  `npm install @types/./node_modules/discord.js/src/index.js` and `declare module './node_modules/discord.js/src/index.js';` are nonfunctional nonsense and aught not to be suggested.

**Comment by xiongmao86** [comment]
I make index.ts:
```typescript
import discord_js_original_js = require("./node_modules/discord.js/src/index.js");
```
And build with `tsc index.ts` shows:
```
index.ts(1,41): error TS2307: Cannot find module './node_modules/discord.js/src/index.js'.
```
without and even with --noImplicitAny.

typescript version: Version 2.7.0-dev.20180111.

**Comment by nicknisi** [comment]
@xiongmao86  This is reproducible if you have discord.js installed. 

**package.json**
```json
  "dependencies": {
    "discord.js": "^11.2.1"
  }
```

TS will look for the types after finding the file and that's when you see the error described.

**Comment by xiongmao86** [comment]
reproducible with 
```json
"dependencies": {
  "discord.js": "^11.2.1"
}
```
and `npm install` and `tsc -noImplicitAny index.ts`.
Trying to figure out how to change now.
