### ISSUE TITLE
Type inference cannot properly infer type for object literal returned from function

### ISSUE THREAD

**Issue by aczekajski** [Microsoft/TypeScript#20008]
**TypeScript Version:**  2.6.0 and 2.7.0-dev.20171114

**Code**
```ts
declare namespace Module {
    class MyClass<T> {
        // template functions using Pick 
        foo<K extends keyof T>(o: Pick<T, K>): void;
        foo<K extends keyof T>(f: () => Pick<T, K>): void;

        // simple example without generics and Pick 
        bar(o: T): void;
        bar(f: () => T): void;  
    }
}

interface I {
    value: number;
}

class C extends Module.MyClass<I> {
    private fn() {
        this.foo({ nothing: 5 }); // ERROR | here it knows that "nothing" does not exist on I
        this.foo(() => ({ nothing: 5 })); // NO ERROR | but now it cannot infer that "nothing" does not exist on I
        this.foo<keyof I>(() => ({ nothing: 5 })); // ERROR | we explicitely provided a "keyof I" so K from line 6 is no longer inferred, and now it is able to say that the "value" property is missing, good 
        this.foo<keyof I>(() => ({ nothing: 5, value: 6 })); // NO ERROR | then we add missing "value" property to returned object and it still cannot see the additional "nothing", even though it was able to infer some information about the object

        // the same goes for the "bar" function, so it is not a problem of generics 
        this.bar({ nothing: 5 }); // ERROR | as desired
        this.bar(() => ({ nothing: 5 })); // ERROR | can see missing "value"
        this.bar(() => ({ nothing: 5, value: 6 })); // NO ERROR | cannot see unwanted "nothing"
    }
}
```
See the code in [TypeScript playground](https://www.typescriptlang.org/play/#src=declare%20namespace%20Module%20%7B%0D%0A%20%20%20%20class%20MyClass%3CT%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20template%20functions%20using%20Pick%20%0D%0A%20%20%20%20%20%20%20%20foo%3CK%20extends%20keyof%20T%3E(o%3A%20Pick%3CT%2C%20K%3E)%3A%20void%3B%0D%0A%20%20%20%20%20%20%20%20foo%3CK%20extends%20keyof%20T%3E(f%3A%20()%20%3D%3E%20Pick%3CT%2C%20K%3E)%3A%20void%3B%0D%0A%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20simple%20example%20without%20generics%20and%20Pick%20%0D%0A%20%20%20%20%20%20%20%20bar(o%3A%20T)%3A%20void%3B%0D%0A%20%20%20%20%20%20%20%20bar(f%3A%20()%20%3D%3E%20T)%3A%20void%3B%20%20%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Ainterface%20I%20%7B%0D%0A%20%20%20%20value%3A%20number%3B%0D%0A%7D%0D%0A%0D%0Aclass%20C%20extends%20Module.MyClass%3CI%3E%20%7B%0D%0A%20%20%20%20private%20fn()%20%7B%0D%0A%20%20%20%20%20%20%20%20this.foo(%7B%20nothing%3A%205%20%7D)%3B%20%2F%2F%20ERROR%20%7C%20here%20it%20knows%20that%20%22nothing%22%20does%20not%20exist%20on%20I%0D%0A%20%20%20%20%20%20%20%20this.foo(()%20%3D%3E%20(%7B%20nothing%3A%205%20%7D))%3B%20%2F%2F%20NO%20ERROR%20%7C%20but%20now%20it%20cannot%20infer%20that%20%22nothing%22%20does%20not%20exist%20on%20I%0D%0A%20%20%20%20%20%20%20%20this.foo%3Ckeyof%20I%3E(()%20%3D%3E%20(%7B%20nothing%3A%205%20%7D))%3B%20%2F%2F%20ERROR%20%7C%20we%20explicitely%20provided%20a%20%22keyof%20I%22%20so%20K%20from%20line%206%20is%20no%20longer%20inferred%2C%20and%20now%20it%20is%20able%20to%20say%20that%20the%20%22value%22%20property%20is%20missing%2C%20good%20%0D%0A%20%20%20%20%20%20%20%20this.foo%3Ckeyof%20I%3E(()%20%3D%3E%20(%7B%20nothing%3A%205%2C%20value%3A%206%20%7D))%3B%20%2F%2F%20NO%20ERROR%20%7C%20then%20we%20add%20missing%20%22value%22%20property%20to%20returned%20object%20and%20it%20still%20cannot%20see%20the%20additional%20%22nothing%22%2C%20even%20though%20it%20was%20able%20to%20infer%20some%20information%20about%20the%20object%0D%0A%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20the%20same%20goes%20for%20the%20%22bar%22%20function%2C%20so%20it%20is%20not%20a%20problem%20of%20generics%20%0D%0A%20%20%20%20%20%20%20%20this.bar(%7B%20nothing%3A%205%20%7D)%3B%20%2F%2F%20ERROR%20%7C%20as%20desired%0D%0A%20%20%20%20%20%20%20%20this.bar(()%20%3D%3E%20(%7B%20nothing%3A%205%20%7D))%3B%20%2F%2F%20ERROR%20%7C%20can%20see%20missing%20%22value%22%0D%0A%20%20%20%20%20%20%20%20this.bar(()%20%3D%3E%20(%7B%20nothing%3A%205%2C%20value%3A%206%20%7D))%3B%20%2F%2F%20NO%20ERROR%20%7C%20cannot%20see%20unwanted%20%22nothing%22%0D%0A%20%20%20%20%7D%0D%0A%7D).

**Expected behavior:**
Errors in all lines invoking `foo` and `bar` functions, saying that property `nothing` does not exist on type `I` or `Pick<I, /* something */>`.

**Actual behavior:**
TypeScript properly raises an error when `foo`/`bar` function gets an object literal that is incompatible with type `I`; It properly raises an error about property missing in object literal returned from function being passed to `foo`/`bar` when we explicitely specify which type we want to be returned, but cannot raise an error about `nothing` being incompatible with `I` when it's being returned from function (even with `<keyof I>` being explicitely specified for `foo`).

**Comment by RyanCavanaugh** [comment]
Duplicate #241 - the widening of the types of the function expressions' return values is what's causing this

**Comment by RyanCavanaugh** [comment]
See also #7547
