### ISSUE TITLE
allow type parameters on values other than classes and functions

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#20015]
i can do this:
```
function getter<T extends { value: U}, U>(data: T): U {
    return data.value;
}
```

but i cannot do this:
```
interface Accessor<T extends { value: U; }, U> {
    get(data: T): U;
    set(data: T, value: U): T;
}

const accessor: Accessor = { // <-- error, requires type arguments that i don't have yet
    get: data => data.value,
    set: (data, value) => ({ ... data, value })
}
```

i wish i could do something like this:
```
const accessor<T extends { value: U; }, U>: Accessor<T, U> = {
    get: data => data.value,
    set: (data, value) => ({ ... data, value })
}
```

consider allowing type parameters on values other than functions and classes

**Comment by mhegazy** [comment]
then how would `T` and `U` be known when `accessor` is used? do you have to specify `accessor<number, string>` or you imagine some sort of inference taking place? if so how?

**Comment by aleksey-bykov** [comment]
just in the exact same way as it is for functions:

1. yes, one way it to implicitly set them `accessor<string, number>.get(xxx)`
2. yes, another way is to let inference guess: `takeAccessor(accessor)`

**Comment by aleksey-bykov** [comment]
just like with the functions where type arguments are required on each call, the arguments for values need to be provided or inferred *at each reading*

so yes it needs to happen on every use

**Comment by aleksey-bykov** [comment]
in fact at the moment i use functions to do exactly that:

```
function alwaysAccesorOf<T, U>(): Accessor<T, U> {
   return {
      get: data => data.value,
      set: (data, value) => ({ ...data, value })
   };
}

alwaysAccessorOf<string, number>().get(xxx) // <-- i wish i could avoid a function call just
                                            // for the sake of providing type arguments
                                            // and simply do:

accessor<string, numbe>.get(xxx);
```

**Comment by aluanhaddad** [comment]
I run into this fairly often.

Related issues:
https://github.com/Microsoft/TypeScript/issues/19728
https://github.com/Microsoft/TypeScript/issues/17574

**Comment by mhegazy** [comment]
also related to https://github.com/Microsoft/TypeScript/issues/15877

**Comment by RyanCavanaugh** [comment]
Tracking at #17574
