### ISSUE TITLE
isValidSpreadType doesn't handle type parameter

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#20013]
**TypeScript Version:**  2.7.0-dev.20171114

**Code**

```ts
function shallowClone<T extends object>(x: T): T {
    return { ...x };
}
```

**Expected behavior:**

No error.

**Actual behavior:**

`src/a.ts(2,14): error TS2698: Spread types may only be created from object types.`

@sandersn

**Comment by sandersn** [comment]
This is by design:

1. `...T` is not assignable to `T`

```ts
class C {
  m() {
    return 'hi'
  }
}
shallowClone(new C()).m() // runtime error: 'm' is not a function
```

2. Typescript doesn't have a spread type because (1) makes it unusable for React without some constraint on `T`.
