### ISSUE TITLE
Compiler generates `yield` expression when target is `es5`.

### ISSUE THREAD

**Issue by acrazing** [Microsoft/TypeScript#20027]
TypeScript: 2.5.3

config:

```json
{
  "compilerOptions": {
    // ...
    "target": "es5"
  }
}
```

case:

```ts
interface Input {
    id?: string;
}

const _id = new Promise<string>((resolve) => resolve('_id'))

async function p1({ id = `id:${await _id}` }: Input = {}) {
    return id
}

async function p2({ id }: Input = {}) {
    id = id || `id:${await _id}`
    return id
}
```

generated code:

```js
var _id = new Promise(function (resolve) { return resolve('_id'); });
function p1(_a) {
    var _b = (_a === void 0 ? {} : _a).id, id = _b === void 0 ? "id:" + (yield _id) : _b;
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_c) {
            return [2 /*return*/, id];
        });
    });
}
function p2(_a) {
    var id = (_a === void 0 ? {} : _a).id;
    return __awaiter(this, void 0, void 0, function () {
        var _b, _c;
        return __generator(this, function (_d) {
            switch (_d.label) {
                case 0:
                    _b = id;
                    if (_b) return [3 /*break*/, 2];
                    _c = "id:";
                    return [4 /*yield*/, _id];
                case 1:
                    _b = _c + (_d.sent());
                    _d.label = 2;
                case 2:
                    id = _b;
                    return [2 /*return*/, id];
            }
        });
    });
}
```

Bug: the function `p1` compile result contains expression like

```js
var _b = (_a === void 0 ? {} : _a).id, id = _b === void 0 ? "id:" + (yield _id) : _b;
```

and the `yield` expression is not exists in es5.

[Playground](https://www.typescriptlang.org/play/index.html#src=interface%20Input%20%7B%0D%0A%20%20%20%20id%3F%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Aconst%20_id%20%3D%20new%20Promise%3Cstring%3E((resolve)%20%3D%3E%20resolve('_id'))%0D%0A%0D%0Aasync%20function%20p1(%7B%20id%20%3D%20%60id%3A%24%7Bawait%20_id%7D%60%20%7D%3A%20Input%20%3D%20%7B%7D)%20%7B%0D%0A%7D%0D%0A%0D%0Aasync%20function%20p2(%7B%20id%20%7D%3A%20Input%20%3D%20%7B%7D)%20%7B%0D%0A%20%20%20%20id%20%3D%20id%20%7C%7C%20await%20_id%0D%0A%7D%0D%0A#src=interface%20Input%20%7B%0D%0A%20%20%20%20id%3F%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Aconst%20_id%20%3D%20new%20Promise%3Cstring%3E((resolve)%20%3D%3E%20resolve('_id'))%0D%0A%0D%0Aasync%20function%20p1(%7B%20id%20%3D%20%60id%3A%24%7Bawait%20_id%7D%60%20%7D%3A%20Input%20%3D%20%7B%7D)%20%7B%0D%0A%20%20%20%20return%20id%0D%0A%7D%0D%0A%0D%0Aasync%20function%20p2(%7B%20id%20%7D%3A%20Input%20%3D%20%7B%7D)%20%7B%0D%0A%20%20%20%20id%20%3D%20id%20%7C%7C%20%60id%3A%24%7Bawait%20_id%7D%60%0D%0A%20%20%20%20return%20id%0D%0A%7D%0D%0A)

**Comment by weswigham** [comment]
Duplicate #18981; this should actually be a syntax error, and is why the emit is broken.
