### ISSUE TITLE
Improve testing for symbol that may reference this

### ISSUE THREAD

**Issue by andy-ms** [microsoft/TypeScript#20034]
**TypeScript Version:**  2.7.0-dev.20171115

See comments with text `// TODO: GH#20034` (added in #20036).

**Comment by mhegazy** [comment]
so what is the issue here?

**Comment by andy-ms** [comment]
The issue is that some node types are ignored, so we're being overly pessimistic. For example, anything with a getter is assumed to use a `this` type, just because we haven't handled that syntax kind yet.

**Comment by weswigham** [comment]
I can see no more references to #20034 in our codebase.
