### ISSUE TITLE
Unused assignment detection

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#20039]
**TypeScript Version:**  2.7.0-dev.201xxxxx

**Code**

```ts
function f() {
    let x = 0;
    console.log(x);
    x = 1;
}
```

The variable `x` is used, but the assignment `x = 1` is not used.
This might be good as a lint rule, but the compiler would first have to expose an API for control flow analysis to be used.

**Comment by mhegazy** [comment]
that is dead code detection in general. i would not want to go there :) at least not in the compiler proper.
