### ISSUE TITLE
Function overload do not pick up right case

### ISSUE THREAD

**Issue by honzabrecka** [Microsoft/TypeScript#20032]
**TypeScript Version:**  2.7.0-dev.201xxxxx

## Example 1

**Code**

```ts
interface Dict<T> {
  [key: string]: T
}

declare function filter<T>(fn: (value: T) => boolean): (x: Dict<T>) => Dict<T>;
declare function filter<T>(fn: (value: T) => boolean): (x: T[]) => T[];

declare function pipe<V0, T1>(fn0: (x0: V0) => T1): (x0: V0) => T1;
declare function pipe<V0, T1, T2>(fn0: (x0: V0) => T1, fn1: (x: T1) => T2): (x0: V0) => T2;

const x = pipe(filter((x: string) => true))

console.log(x(['foo']))
```

**Expected behavior:**

`x` is of type `(v: string[]) => string[]`

**Actual behavior:**

Argument of type 'string[]' is not assignable to parameter of type 'Dict<string>'.

## Example 2

**Code**

```ts
interface Dict<T> {
  [key: string]: T
}

declare function filter<T>(fn: (value: T) => boolean): (x: Dict<T>) => Dict<T>;
declare function filter<T>(fn: (value: T) => boolean): (x: T[]) => T[];

declare function pipe<V0, T1>(fn0: (x0: V0) => T1): (x0: V0) => T1;
declare function pipe<V0, T1, T2>(fn0: (x0: V0) => T1, fn1: (x: T1) => T2): (x0: V0) => T2;

// >>> specialized id, which should specify filter overload
const id = (x: string[]): string[] => x

const x = pipe(id, filter((x: string) => true))

console.log(x(['foo']))
```

**Expected behavior:**

`x` is of type `(v: string[]) => string[]`

**Actual behavior:**

Argument of type 'string[]' is not assignable to parameter of type 'Dict<string>'. Now failing on `filter`.

**Comment by DanielRosenwasser** [comment]
Your call to filter undergoes overload resolution based on its arguments, not on the type it will eventually flow into.

It doesn't really make sense in our type system for `filter` to have two overloads with identical parameter lists. What you probably want is for `filter` to return something which itself has overloads:

declare function filter<T>(fn: (value: T) => boolean): {
    (x: Dict<T>): Dict<T>;
    (x: T[]): T[];
}

**Comment by honzabrecka** [comment]
That does not work either. However, thanks.
