### ISSUE TITLE
Wrong type for enum string indexer

### ISSUE THREAD

**Issue by elicym** [Microsoft/TypeScript#20031]
enum MyEnum { a, b, c };
    let myStr = 'a'; //or let myStr = getSomeString();
    let myVar = MyEnum[myStr];

`myVar` should be of type `MyEnum`. Instead it's of type `any`. In `strict` mode, it actually produces an error `Element implicitly has an 'any' type because index expression is not of type 'number'.`

**Comment by RyanCavanaugh** [comment]
If you had written `"1"` instead of `"a"`, you'd get back a `string`, not a `number`

**Comment by elicym** [comment]
I know - but I wrote `'a'`, not `'1'`. If you add `console.log(myVar)` at the end (not in strict mode), it shows correctly `0`. Therefore `myVar` is of type `MyEnum` or perhaps `number`, not `any`.

**Comment by RyanCavanaugh** [comment]
We don't know that `myStr` isn't mutated elsewhere. If you use `const` to prevent that mutation, this does what you expect:
```ts
enum MyEnum { a, b, c };
const myStr = 'a';
let myVar = MyEnum[myStr]; // myVar: MyEnum
```

**Comment by elicym** [comment]
So then the type of `myVar` should be `MyEnum | undefined`. But not `any`.

**Comment by RyanCavanaugh** [comment]
If you had written `"1"` instead of `"a"`, you'd get back a `string`, not a `number`

**Comment by elicym** [comment]
Got it, thanks.
