### ISSUE TITLE
Configure module files available in Node.js global scope

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#20046]
_From @hubletkoresh on November 15, 2017 9:3_

I have an MVC application, with multiple local modules, one of which being models that I install to global scope to enable runtime cyclic references. Unfortunately it also means neither I, nor my team can get Intellisense support for them. It would be really awesome if we could, e.g. in `jsconfig.json` configure such files via for example a glob pattern.

- VSCode Version: 1.18.0
- OS Version: Windows 10 Pro N x64

Steps to Reproduce:

1. Create node.js project
2. Create folder named `models` in root
3. Put `ModelA.js`, `ModelB.js` and `index.js` to that folder
3. Models should have code similar to this
```
exports.model = class ModelA {
 constructor(){
 }

 amazingMethodA(){
    const b = new ModelB();
    b.methodIntellisenseWillNotSuggest();
 }
}
```
4. `index.js` should have code similar to this:
```
const ModelA = require('./ModelA').model;
const ModelB = require('./ModelB').model;

global['ModelA'] = ModelA;
global['ModelB'] = ModelB;

module.exports = { ModelA, ModelB };
```
What I would like is to declare somewhere that all files under folder `./models/**/*` are by default available in global scope and as such should be included in intellisense suggestions in any file defined as part of the project in my `jsconfig.json` `include`s. I know one can write typescript definitions for this, but it's seems like a lot of work for model files - we just would like simpl method suggestions with parameters. Our models have a lot of methods, since they use inheritance. Is it too big/niche feature?

Reproduces without extensions: Yes

_Copied from original issue: Microsoft/vscode#38395_

**Comment by mjbvz** [comment]
This is limitation of our IntelliSense. I believe that setting up a `d.ts` file is required in this case. 

One potential fix may be tracked by https://github.com/Microsoft/TypeScript/issues/15626

**Comment by megakoresh** [comment]
It doesn't seem possible to declare these `*.d.ts` files properly when you are not using Typescript. I tried declaring it like this:
```
const { User } = require('models');
interface global {
  User: User
}

declare var User: User
```
but since the model is an ES6 class, without any Typescript, it does not work.

**Comment by mhegazy** [comment]
Already tracked under https://github.com/Microsoft/TypeScript/issues/15626

**Comment by megakoresh** [comment]
#15626 Doesn't seem to be related precisely to this issue, as this has to do with vscode autocomplete and the solution decided in #15626 describes a JSDoc declaration for use with `//@ts-check` or `//@js-check`, unless I am misunderstanding something.

**Comment by mhegazy** [comment]
```ts
// declaration.d.ts
import {User} from 'models';

declare global {
  declare var User: User
}
```

**Comment by megakoresh** [comment]
I have done so, but it does not work when not using Typescript.

**Comment by mhegazy** [comment]
![animation](https://user-images.githubusercontent.com/8000722/33098126-1b1a9a0c-cec1-11e7-9fbe-98eaa903d69e.gif)

**Comment by megakoresh** [comment]
Like I already mentioned, I am not using Typescript, just vanilla Node.js, with commonjs module system.

**Comment by mhegazy** [comment]
> Like I already mentioned, I am not using Typescript, just vanilla Node.js, with commonjs module system.

you do not need to use TypeScript for VSCode to use the information from a .d.ts files. think of them as jsdoc in a separate file. as a matter of fact, all the help you get from libraries like `node` are coming from `.d.ts` files.

In the screen shot above, your syntax in the .d.ts file is not correct. you can see the red squiggles marking the error. try using the same syntax i provided earlier and let me know if still does not work.

**Comment by megakoresh** [comment]
I started with the syntax you provided, which didn't work for me, so I switched to the one I showed, which didn't work either. The red lines are because I didn't have `allowJS` set to true in `tsconfig.json`. When I renamed the file to `jsconfig.json` all red lines went away. Here is what it looks like with your syntax, if you don't believe me:
![vscode](https://user-images.githubusercontent.com/5512531/33307168-3c0ab23a-d41e-11e7-91c6-c8d831700165.PNG)
I tried reloading the window, restarting Typescript service as well as restarting vscode after changing the `.d.ts` file, it did not help, this simply does not work for me. Also - adding `const` in front of `User` declaration makes no difference either.

**Comment by mhegazy** [comment]
`User` is in the global scope, it shadows your use of `typeof User.model`. consider changing the names to be different, e.g.:

```ts
import * as _User from "./User";
declare global {
	const User : typeof _User.model;
}
```

**Comment by megakoresh** [comment]
Sorry for delay, I have done it. Tried with other models too:
```javascript
import * as _User from './User';
import * as _Answer from './Answer';

declare global {
  const User: typeof _User.model;
  const Answer: typeof _Answer.model;
}
```
No effect.

**Comment by mhegazy** [comment]
> but Intellisense is now very slow.

because you now include more files that the system has to grok and understand

> No effect.

because your `excludes` explicitly stated `"**/*.d.ts"` so whatever .d.ts file you added the definitions in was excluded. make sure to add the file you created to your includes, and leave your excludes the way they were.

**Comment by megakoresh** [comment]
Ah sorry for this confusion, I did, in fact, realise this mistake earlier, just was lazy and didn't copy the actual `jsconfig.json` I was using. Removing the `.d.ts` exclude does not resolve the problem, Intellisense ONLY works for me when I completely clear out all includes and excludes. This is the actual config I am using:
```json
{
  "compilerOptions": {
    "target": "es2017"
  },
  "include": [
      "middleware/**/*",
      "models/**/*",
      "database/**/*",
      "common/**/*",
      "client/scripts/**/*",
      "./*"
  ],
  "exclude": [
      "node_modules",
      "client/dist/**/*",
      "**/*.spec.ts"
  ]  
}
```
Sorry for the confusion!

**Comment by mhegazy** [comment]
I feel this is a configuration issue, and there is a limit to me remotely debugging the issue. if you have a project with the issue, i would be happy to take a look.

**Comment by megakoresh** [comment]
I do, in fact:
https://github.com/megakoresh/koa2-react

**Comment by mhegazy** [comment]
I am looking at latest master, and seems to be working.. what should i be testing?

![image](https://user-images.githubusercontent.com/8000722/33689557-ca2ed948-da94-11e7-9568-9f8515b3226b.png)

**Comment by megakoresh** [comment]
Umm, yeah it works for me now as well, even though I didn't change anything.
