### ISSUE TITLE
Validate key lookups in records

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/TypeScript#20040]
**TypeScript Version:**  2.6.1.

**Code**

When dealing with records, it is desirable that a key lookup using bracket notation will give a type error if the provided key is not valid, e.g.:

```ts
const record: Record<'foo', 'bar'> = { foo: 'bar' };

// Expected error, got none :-(
record['bar'];
```

It is possible to define a helper to enforce this validation:

``` ts
// Workaround: define helper

const getKeyInRecord = function<Key extends string, Value> (
  key: Key,
  record: Record<Key, Value>,
): Value {
  return record[key];
};

// Expected error, got error :-)
getKeyInRecord('bar', record);
```

Could we make this behaviour the default? Apologies if this is already tracked in another issue—difficult criteria to search for!

**Comment by andy-ms** [comment]
You just need `--noImplicitAny` set.

**Comment by OliverJAsh** [comment]
@andy-ms Aha, interesting. Thanks!

**Comment by OliverJAsh** [comment]
I'm only just realising that mapped types and index signatures are not the same thing, despite having very similar syntax. Mapped types look like index signatures, but they are completely separate.

When using bracket notation, the key could reference a property (defined via mapped type) or the index signature:

``` ts
{
    // Mapped type
    type M = { [key in 'foo' | 'bar']: number };
    const m: M = { foo: 1, bar: 1 };

    const invalidKey = 'invalidKey';
    const validKey = 'foo';
    
    // Error: Element implicitly has an 'any' type because type 'M' has no index signature.
    const a = m[invalidKey] // key references index signature
    const b = m[validKey] // key references property signature, defined via mapped type
}

{
    // Index signature
    type I = { [key: string]: number };
    const i: I = { foo: 1, bar: 1 };

    const invalidKey = 'invalidKey';
    const validKey = 'foo';
    
    const a = i[invalidKey] // key references index signature
    const b = i[validKey] // key references index signature
}
```

Thus, when `noImplicitAny` is disabled, keys which are defined as properties (e.g. via mapped type) are validated, however keys which use the index signature are not validated (index signature is implicitly any).

So the helper I defined above is useful for distinguishing between the two, forcing TypeScript to check that a given key is defined as a property.
