### ISSUE TITLE
VS2013 Plugin: missing intellisense for function signatures in small but complex project

### ISSUE THREAD

**Issue by jasonswearingen** [Microsoft/TypeScript#2004]
I have a fairly complex project, and notice that if I import one of my modules, it causes a large percentage of intellisense function signatures to stop working.  I can still navigate objects/classes/functions but do not see the signatures for a number of them.

for example:

```
"use strict";

import xlib = require("../xlib");

export import childProcess = require("child_process");

childProcess.spawn //typing this does not get .spawn() signature intellisense.
```

if I comment out ``` //import xlib = require("../xlib");``` then the .spawn() will start getting it's function signature intellisense properly.

I have reprod this on 1.4.   I am running Win8.1 x64 using VS 2013 Pro.  I have tried deleting temp files/.suo but still get the issue.

You can find a repro project (vNext.sln) here: https://drive.google.com/open?id=0BwZ2bMDOKaeDUF9BenNzTEdXZkk&authuser=0

the example (from above) is in ``` dev/corelib/node/process.ts ```

**Comment by jasons-novaleaf** [comment]
ok..  well I feel stupid, there was a runtime module import bug that causes a crash.   resolving this fixed the intellisense issue.  (comment out line 9 in ```dev/corelib/core/doublescore.ts```)

However, the issue (runtime failure) causes a dev-time, project-wide intellisense failure, so you may wish to report an error to the user.

**Comment by mhegazy** [comment]
@jasonswearingen can you give this a try with 1.5-beta?

**Comment by jasonswearingen** [comment]
Sorry my current environment is not in a state to re-reproduce the issue.  (Not working on typescript at the moment)

I gave a full repro including project/source so that the issue can reproduced.  If nobody actively fixed the issue probably it still exists.

**Comment by mhegazy** [comment]
I am sorry i have not had the chance to investigate this, i do not think this will change soon either. closing for now. please reopen if this still an issue.
