### ISSUE TITLE
Spec should not specify downlevel emit concretely

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#20056]
[In some places in the spec](https://github.com/Microsoft/TypeScript/blob/4b96edf72faf6f9b6b464e148c9c02eac96aa4bd/doc/spec.md#16-classes), things like class emit to ES5 are concretely specified. With multiple emit targets and the like, this should not be a concrete commitment, but rather, should use more open-ended language.

The examples may also need to be updated.

**Comment by RyanCavanaugh** [comment]
The spec is now an "archived" artifact and we won't be tracking defects against it anymore.
