### ISSUE TITLE
Incorrect IntelliSense if file encoding and d.ts is not UTF-8

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#20053]
_From @ocheretnyy on November 15, 2017 3:30_

- VSCode Version:1.18.0
- OS Version:Windows 7

Incorrect IntelliSense if file encoding and d.ts is not UTF-8. If d.ts file alredy opened when IntelliSense work correctly.

Steps to Reproduce:

1.  In user settings file set    "files.encoding": "windows1251",
2. Create  d.ts file (encoding = windows1251) with russian symbols:

declare namespace qt_workbench 
_{
    /** Add dock-window 
     * Добавить Dock-окно 
     */
    function add_window(widget : QWidget,title : string,width : number,height : number,is_visible : boolean);
}_
3. Create file and write:
_workbench .add_window()_
3. Move mouse on function add_window for IntelliSense 

![p](https://user-images.githubusercontent.com/17870990/32817248-49c43056-c9ef-11e7-99fa-58b77562bb21.png)

If workbench.d.ts file opened IntelliSense work correctly
![p-1](https://user-images.githubusercontent.com/17870990/32817315-8a76e648-c9ef-11e7-8c43-7dc9e0c0ca37.png)

Reproduces without extensions: Yes

_Copied from original issue: Microsoft/vscode#38373_

**Comment by mjbvz** [comment]
This works when the `d.ts` file is open because VS Code sends the correct text content of the file to the TS Server. When the `d.ts` file is no open, the TS Server reads the file directly from disk and cannot know the encoding.

Not sure what we can do about this. Any thoughts @mhegazy?

**Comment by ocheretnyy** [comment]
>When the d.ts file is no open, the TS Server reads the file directly from disk and cannot know the encoding.

May be the TS Server should use user encoding setting by default? (file settings.json, parameter "files.encoding")

**Comment by mhegazy** [comment]
This is not about user settings, but about the text APIs the server uses. The server uses the node APIs to read files. we do support UTF8, UTF16 BE and LE. other than that, the server can not read the files correctly.

if the file is open, the text comes from the editor, and convert it to utf8, which the server understands.

It is worth nothing that the compiler will not generate files that are not UTF8. so the .d.ts is manually generated, and for that i suggest using UTF8 or UTF16 with a BOM.

**Comment by ocheretnyy** [comment]
ok. Thanks for the info
