### ISSUE TITLE
getRegistration in ServiceWorkerContainer's optional parameter is missing from 2.6.1

### ISSUE THREAD

**Issue by keekun** [Microsoft/TypeScript#20065]
In 2.5.2, `getRegistration` has an optional parameter `clientURL?: USVString`, which is missing from 2.6.1.

According to MDN, this parameter is optional.

https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerContainer/getRegistration

Maybe a coding miss in this diff: https://github.com/Microsoft/TypeScript/pull/18774/files#diff-46fd87925e4552c166ec188712741c3fL9534

**TypeScript Version:**  2.6.1

**Code**

**Expected behavior:**

`clientURL` should be acceptable.

**Actual behavior:**

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by keekun** [comment]
I fixed it in Microsoft/TSJS-lib-generator.
Please check: https://github.com/Microsoft/TSJS-lib-generator/pull/323
