### ISSUE TITLE
Is it OK to add WebAssembly JS API types to lib.d.ts?

### ISSUE THREAD

**Issue by plantain-00** [Microsoft/TypeScript#20062]
Reasons:

1. current nodejs LTS 8.x support WebAssembly without flags

```
$ node
> WebAssembly.compile
[Function: compile]
```

2. Modern browsers except IE support WebAssembly without flags now (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly)

```
> WebAssembly
WebAssembly {compile: ƒ, validate: ƒ, instantiate: ƒ, compileStreaming: ƒ, instantiateStreaming: ƒ, …}
```

Other issue if this is OK: put WebAssembly types in `es5.d.ts` like `Math`, or a new file(name?)?

**Comment by RyanCavanaugh** [comment]
We don't put experimental features in the library. You can include the types definition from https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/webassembly-js-api/index.d.ts if you'd like to use the features before standardization
