### ISSUE TITLE
Show auto import suggestions even when local symbol with same name already exists?

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#20061]
From https://github.com/Microsoft/vscode/issues/37284

**Code**
In a simple project

```ts
// a.ts
export const abc = 123
```

```ts
// b.ts

const abc = 'do re mi'
abc + ab|
```

In `b.ts`, trigger suggestions at the end of `ab`

**Expected behavior:**
Local suggestion for `abc` is shown first. An auto import for `abc` from `a.ts` is also returned

**Actual behavior:**
Only local suggestion for `abc` is returned

---

Needs further discussion. Even if we have the proper sort-order for suggestions, this behavior could get in the way or hide other useful suggestions, especially on larger projects

**Comment by mhegazy** [comment]
This was a deliberate decision to avoid noise. it is unlikely that you have a local with the same as an exported module and you expect the non-local completion.. it is more likely that you want the local completion, and the completion list is littered with unrelated symbols.

We do allow globals and exported symbols to co-exist, but not locals.
