### ISSUE TITLE
On your page react & webpack there is link that does not exist anymore.

### ISSUE THREAD

**Issue by createdbyjurand** [microsoft/TypeScript#20067]
On your website:
https://www.typescriptlang.org/docs/handbook/react-&-webpack.html
there is a line with link:
"You can learn more about tsconfig.json files here."
leading to a page that does not exist anymore:
https://www.typescriptlang.org/docs/tsconfig-json.html
and when you click on it, you get:
"The resource you are looking for has been removed, had its name changed, or is temporarily unavailable."

**Comment by mhegazy** [comment]
The source of the tutorial is at https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/tutorials/React%20%26%20Webpack.md

when building the site, we move the tutorial up a level and that leaves relative paths broken. a possible fix here is to add an absolute reference to the tsconfig page. 

A PR would be appreciated.

**Comment by lilybarrett** [comment]
Is this issue still open/unaddressed?

**Comment by orta** [comment]
Nope, it's fixed 👍
