### ISSUE TITLE
Version 2.6.1 takes a long time to compile

### ISSUE THREAD

**Issue by ConnorsFan** [Microsoft/TypeScript#20070]
**TypeScript Version:**  2.6.1

**Code**
An Angular 4 application, using Webpack

**Expected behavior:**
To compile the code in less than 45 seconds, as is the case with Typescript 2.5.3 (and earlier versions)

**Actual behavior:**
Takes about 130 to 145 seconds to compile

**Comment by mhegazy** [comment]
Can you please share a repro project?
