### ISSUE TITLE
NodeTypingsInstaller.handleMessage should treat PackageInstalledResponse roughly the same as SetTypings

### ISSUE THREAD

**Issue by amcasey** [Microsoft/TypeScript#20084]
In particular, `PackageInstalledResponse` should probably be a `ProjectResponse` and `handleMessage` should call 

```ts
                    this.projectService.updateTypingsForProject(response);

                    if (this.socket) {
                        this.sendEvent(0, "setTypings", response);
                    }
```

I'll leave it to the implementer to decide whether the event name should be different - VS doesn't need to distinguish.

**Comment by mhegazy** [comment]
marking this as 2.6.3.
