### ISSUE TITLE
docCommentTemplate does not return newlines in empty template anymore

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#20089]
**TypeScript Version:**  2.7.0-dev.20171116

**Code**

```ts
function foo() { }
```

Trigger `docCommentTemplate` for foo.

**Expected behavior:**
Returns:

```ts
/**
 *
 */
```

**Actual behavior:**
Returns:

```ts
/** */
```

**Comment by andy-ms** [comment]
This was done intentionally in #19544.
You can always hit enter to get the old behavior, right?

**Comment by mjbvz** [comment]
Not with our current flow. We show document templates in our suggestion list currently. When you hit enter, we accept the suggestion and eat the enter key press

**Comment by mhegazy** [comment]
@mjbvz part of the change is allowing this to happen in multiple places as well; where in the past we only allowed it for certain declarations only. 
Is this an issue you can deal with on your side, or you need us to revert back to the old behavior?

**Comment by mjbvz** [comment]
We can add a workaround for this if needed. Instead of generating an empty comment though, could `docCommentTemplate` now return undefined in these cases though? That would let us fallback to the standard empty multiline doc template that we already use when calls to `docCommentTemplate` fail

**Comment by mhegazy** [comment]
> Instead of generating an empty comment though, could docCommentTemplate now return undefined in these cases though?

that is what it used to do, now it always returns an empty comment, unless the locaiton is an invalid comment location (e.g. string, JSX text, or another comment). 
so not sure i understand what you mean here.

**Comment by uniqueiniquity** [comment]
@mjbvz Just to clarify (regarding the new PR I just put up), the issue is not that we changed our default template from multiline to single line, but that we were too lax about where we considered a valid code location to insert a template?

**Comment by andy-ms** [comment]
If it matters, I've created an issue for allowing users to set options in services at #20619 -- that could include settings for comment templates such as whether to make them multiline.
