### ISSUE TITLE
Private symbol class properties treated as public

### ISSUE THREAD

**Issue by dpogue** [Microsoft/TypeScript#20080]
**TypeScript Version:**  2.7.0-dev.20171116

**Code**

```ts
const _data = Symbol('data');

export class User {
    private [_data] : any;
};
```

**Expected behavior:**
Compiles successfully.

**Actual behavior:**
TS4031: Public property '[_data]' of exported class has or is using private name '_data'.

The issue is that `[_data]` is not a public property, so it shouldn't care if it's using a private name because it's not meant to be visible outside of the User class.

**Comment by mhegazy** [comment]
some background in https://github.com/Microsoft/TypeScript/issues/19545#issuecomment-340490459. 

Today there is no way to write this file a .d.ts and not expose `_data`. that is basically what the error is telling you.

we can possibly fix this by adding an auto-generated `export {}` to the bottom of the generated .d.ts and not show the error.

**Comment by dpogue** [comment]
I think I was under the assumption that private properties don't get emitted to the .d.ts files. Is that not the case?

**Comment by mhegazy** [comment]
> I think I was under the assumption that private properties don't get emitted to the .d.ts files. Is that not the case?

They need to be emitted to the .d.ts to avoid derived classes creating members with he same name.

**Comment by DanielRosenwasser** [comment]
Two things:

1. The symbol is technically still accessible, it's just not possible to reference it directly.
2. Automatically exporting the symbol seems questionable.

**Comment by dpogue** [comment]
> They need to be emitted to the .d.ts to avoid derived classes creating members with he same name.

If the symbol isn't exported, it's literally unknowable, so you *can't* have the same name it in a derived class (which is, of course, our entire reason for not exporting it)

**Comment by mhegazy** [comment]
> If the symbol isn't exported, it's literally unknowable, so you can't have the same name it in a derived class (which is, of course, our entire reason for not exporting it)

There is some historical context why things work the way they do.. please see https://github.com/Microsoft/TypeScript/issues/19545#issuecomment-340490459 for more details.

**Comment by weswigham** [comment]
@dpogue I've opened a PR to elide the property like @mhegazy was talking about; but your original error in the OP is not the error you'd get from the declaration emit of that property - the error you've given occurs when a global `Symbol` type can't be found - do you have `lib: ["es6"]` included?

**Comment by dpogue** [comment]
I do have `lib: [..., "es2015.symbol", ...]` in my tsconfig.json
