### ISSUE TITLE
Without `--strictNullChecks`, `x && "a"`contributes a `""` type.

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#20090]
**TypeScript Version:**  2.7.0-dev.20171116

**Code**

```ts
function f(b: boolean): false | "a" {
	return b && "a";
}
```

**Expected behavior:**

No error. (Just like with `--strictNullChecks`.)

**Actual behavior:**

```ts
src/a.ts(2,2): error TS2322: Type '"" | "a"' is not assignable to type 'boolean | "a"'.
  Type '""' is not assignable to type 'boolean | "a"'.
```

**Comment by ahejlsberg** [comment]
This is working as intended for backwards compatibility reasons. Originally, the type of an `&&` operation was simply the type of the right hand operand and a lot of old code depends on that. With literal types we change the falsy left hand side value into a falsy value in the same domain as the right hand side to best approximate the original behavior.

In general, you see a true reflection of the run-time behavior only in `--strictNullChecks` mode.
