### ISSUE TITLE
bad parsing of parenthesized arrow function

### ISSUE THREAD

**Issue by ajafff** [Microsoft/TypeScript#20096]
**TypeScript Version:**  2.7.0-dev.20171117

**Code**

```ts
const sourceFile = ts.createSourceFile('test.ts', 'let foo = (async bar => bar);', ts.ScriptTarget.ES5);
const initializer = (sourceFile.statements[0] as ts.VariableStatement).declarationList.declarations[0].initializer!;
ts.SyntaxKind[initializer.kind]; // Expected ParenthesizedExpression, Actual: ArrowFunction
initializer.getText(); // output "(async bar => bar"
initializer.getChildren().map(token => token.getText()); // output ["(", "async bar", "=>", "bar"]
```

**Expected behavior:**
parses ArrowFunction inside ParenthesizedExpression

**Actual behavior:**
parses only ArrowFunction with wrong positions and weird tokens

**Comment by andy-ms** [comment]
Might have to do with the `ScriptTarget`?

**Comment by sandersn** [comment]
Looks like the faster arrow function parsing doesn't handle parenthesized async arrows. Should be reasonably simple to add.
