### ISSUE TITLE
Class without setter property incorrectly allowed to implement interface 

### ISSUE THREAD

**Issue by MastroLindus** [Microsoft/TypeScript#20093]
**TypeScript Version:**  reproduced on 2.7.0-dev,  and on 2.2.1

**Code**

```ts
interface A {
  readonly foo: string;
}

interface B {
  foo: string;
}

class C implements A,B {
  public get foo() { return "bla";}
}

const baz = (p: B) => p.foo = "blabla";

baz(new C());

```

**Expected behavior:**
-Compiler complains that C doesn't implement properly B since it has no setter (and now we have a proper way to define an interface with a readonly property as A shows).
-Compiler complains if you try to pass a C to function baz.

In general with or without the "implements" declaration, C should not be assignable to B if it doesn't implement a setter for foo.

**Actual behavior:**
No Compile Errors.
Runtime error when baz tries to set the foo property.

I am not really sure this is a bug or some design choice, but I would definitely expect the type system to catch this, especially since we have the "readonly" keyword to mark properties that cannot be set.

**Comment by mhegazy** [comment]
Please see https://github.com/Microsoft/TypeScript/issues/13347
