### ISSUE TITLE
Error message of spread arguments should be `got 0 or more`

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#20097]
**TypeScript Version:**  master

**Code**

```ts
declare function f(): void;
f(...[]);
```

**Expected behavior:**

```
$ node built/local/tsc.js index.ts
index.ts(2,1): error TS2556: Expected 0 arguments, but got 0 or more.
```

**Actual behavior:**

```
$ node built/local/tsc.js index.ts
index.ts(2,1): error TS2556: Expected 0 arguments, but got 1 or more.
```

**Comment by falsandtru** [comment]
Not correct.

**Comment by falsandtru** [comment]
This error is correct but its error message is not correct.

**Comment by kitsonk** [comment]
`Expected 0 arguments, but got 0 or more.` does not make grammatical sense.  While, after the spread, it results in no additional arguments, passing a spread argument, is _a_ argument, so the error it stands is grammatically correct.

**Comment by sandersn** [comment]
@falsandtru please read the explanation in #20097 — it is technically incorrect but easier to understand for the common case.
