### ISSUE TITLE
Add Support for BrowserList and Core-JS Polyfills Automatically

### ISSUE THREAD

**Issue by RehanSaeed** [Microsoft/TypeScript#20095]
Babel provides the [babel-preset-env](https://babeljs.io/docs/plugins/preset-env/) plugin which uses the [browserlist] syntax shown below to automatically add pollyfills from [core-js](https://github.com/zloirock/core-js). This looks at the browsers you want to support and automatically adds the required pollyfills.

```
>1%
Last 4 versions
```

I never want to have to think about which pollyfills I need to add, TypeScript should do this for you as it's a very common scenario and easily prone to error. TypeScript should support the browserlist format directly in the `tsconfig.json` file or in a separate `.browserlistrc` file.

**Comment by mhegazy** [comment]
that is what `--lib` do.. anything specifically you are missing?

**Comment by RehanSaeed** [comment]
The lib option does not polyfill anything. It simply tells TypeScript to assume that certain API's are available. Babel goes further than the `lib` option and automatically polyfills too.

**Comment by RehanSaeed** [comment]
Can this be reopened? This issue is marked as 'Need more info' which I've already supplied. I think I've layed out my proposal clearly.

**Comment by levenleven** [comment]
Would be nice to have auto polyfilled everything that is specified in `--lib` and used in code base

**Comment by kitsonk** [comment]
No it wouldn't...  There are many ways to provide functional polyfills and assuming one size fits all would be anti-pattern for TypeScript, as it is a syntactical compiler.  In particular it contravenes the following [non-goal](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals#non-goals):

> 6. Provide additional runtime functionality or libraries. Instead, use TypeScript to describe existing libraries.

Also it touches on this non-goal:

> 4. Provide an end-to-end build pipeline. Instead, make the system extensible so that external tools can use the compiler for more complex build workflows.

Which is entirely consistent with the approach of the language to this point.  TypeScript can be forced to assume some functionality is available (like `Promise` or `Symbol`) and use those, but does not provide any functional polyfills.

**Comment by RehanSaeed** [comment]
Babel is TypeScript's major competitor and provides this functionality as a separate package and even *recommends* using `babel-preset-env`. If you use Babel, you do not wake up at night in sweats thinking about polyfills.

TypeScript could add this functionality by providing a similar `typescript-preset-env` NPM package. As it stands, TypeScript developers working in the browser have to get deep into core-js and other pollyfills to get their work done. This is the one area where the grass on the Babel side is far greener.

**Comment by stereobooster** [comment]
> Babel is TypeScript's major competitor

I don't think so. Babel has no type system.

I suppose this is the official solution to the problem https://github.com/Microsoft/TypeScript-Babel-Starter

**Comment by RehanSaeed** [comment]
@stereobooster It doesn't matter that Babel doesn't have a type system. When a developer decides what front end language to use today, the chances are that they choose between Babel and TypeScript. Other languages come a distant third.

Thanks for the interesting link 🥇 , JS type checking is a half way house, you'll catch some errors but not all.

**Comment by Ciantic** [comment]
While this might be out of scope of TypeScript, I would like to chime in. I came here because I thought like this: 

Since TypeScript knows the types (and calls) it can infer the required polyfills. E.g. if user uses 

```[1,2,3,4].includes(3)```

TypeScript knows this, so it could add `includes` polyfill. Or mark it as required.

Maybe some other tool could then add all the required polyfills once the TypeScript has collected them.

However, I note that this could be implemented as a tool completely separate from TS.
