### ISSUE TITLE
Feature request: Generated code should follow the ts-lint rules defined in the project

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#20107]
_From @nseba on November 17, 2017 9:34_

It would be very useful if refactoring actions such as declare member variable, implement interface/abstract class etc. would take into account the relevant ts-lint rules. At a minimum the following rules can be enforced:
* `member-access` - add explicit `public | private` modifier to newly generated members
* `member-ordering` - add the members in their right place (for example public fields after existing public fields, methods after existing public methods etc.)
* `promise-function-async` - automatically add the `async` modifier.
* `quotemark` - use the right quotes/single quotes for automatic import declarations

As a small side note implementing abstract base class refactoring should also add automatically the `async` modifier if it exists on the abstract member.

_Copied from original issue: Microsoft/vscode#38603_

**Comment by andy-ms** [comment]
You could simply run the codefix then run tslint with `--fix`. Getting a rule like `member-ordering` to work with TypeScript's codefixes would require duplicating tslint's existing logic.
`quotemark` should be handled by #17750, although this uses existing imports instead of looking for a tslint config.

**Comment by RyanCavanaugh** [comment]
This should be handled by a tslint language server plugin; it can intercept the refactoring messages and change them to conform to whatever rules.

We have no ability to find the user's tslint settings and understand what they mean from the TS side.
