### ISSUE TITLE
Feature request: Change first letter case on compile to js

### ISSUE THREAD

**Issue by rhyous** [Microsoft/TypeScript#20101]
The ability to to have the first letter change case.

As a C# developer, I would like to code Typescript with the same alphabetical uppercase and lowercase rules that we use in C#.

Example:

I have this class in C#:

public class Person
{
    public string Name;
    public string Age;
    ToString() { return Name + ' ' + age; }
}

**Expected behavior:**

1. When coding in Typescript, the first letter is uppercase in properties, allowing a syntax inline with C#. However, in javascript, best practice is to have lowercase. So allow a flag that means that after compiling, the first letter of properties are lower case. This should be an optional flag.
2. If a developer added two properties where the only difference is the first letter case, and this feature flag is enabled, a compiler error occurs.
3. Include functions.

```
var Person = /** @class */ (function () {
    function Person() {
        this.string = Name;
        this.string = Age;
    }
    Person.prototype.toString = function () { return Name + ' ' + age; };
    return Person;
}());

```

**Actual behavior:**
If you use uppercase in Typescript, the compiled javascript is also uppercase.

**Comment by kitsonk** [comment]
TypeScript transforming any case of any variables is very dangerous.

Any desired conventions of case usage should be enforced by a linting tool, like tslint or eslint.

**Comment by andy-ms** [comment]
TypeScript is JavaScript -- JavaScript best practices are TypeScript best practices. We won't add any feature that changes your code into something with a different meaning. See the [design goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).
