### ISSUE TITLE
Feature request: add an option to clean outDir on transpilation

### ISSUE THREAD

**Issue by sveinburne** [Microsoft/TypeScript#20112]
**Scenario**: As a user, I would like to clean `compilerOptions.outDir` before transpiling. It is fairly understandable that it is not the default behavior since removing user data goes beyond the scope of a compiler responsibility. However, many users would find this very convenient during development process, notably: 
- when `--watch` mode on
- to systematically avoid "dead leaves", i.e. obsolete sources and definitions

Such a compiler option could be labeled `autoCleanOutDir` and have `boolean` type.

Related issues: #13722

**Comment by mhegazy** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/16057

**Comment by sveinburne** [comment]
I close in favor of #16057
