### ISSUE TITLE
Infer from usage should infer boolean

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#20116]
**TypeScript Version:**  2.7.0-dev.20171117

**Code**

```ts
function f(x) {
    return x ? 1 : 2;
}
```

**Expected behavior:**

Infers `x: boolean`.

**Actual behavior:**

No fix.

**Comment by mhegazy** [comment]
I think i tried this for a bit, and it was too restrictive in the general case.. The type of `x` is really `T | Falsy` where `Falsy` is `"" | false | 0 | undefined | null`, and `T` is `any`.. so `any` wins..

it getts annoying when you have somehing like:

```ts
function firstOrUndefined(x) {
    return x.length ? x[0] : undefined; 
}
```

giving `x` here type `{ length: boolean }` is not what you want.
