### ISSUE TITLE
Put enum markers at the beginning of the generated enum JS object

### ISSUE THREAD

**Issue by lmcarreiro** [Microsoft/TypeScript#20129]
I'm using the compiler API and I would like to get `SyntaxKind` names, I tried this:

```ts
let x = SyntaxKind.XXX1;
let xName = SyntaxKind[x];
```

But it doesn't work, because `SyntaxKind` is defined with markers, like this:

```ts
enum SyntaxKind {
  XXX1,
  XXX2,
  XXX3,

  Count,

  //markers
  FirstXXX = XXX1,
  LastXXX = XXX3,
}
```

In my example, `xName` would be `"FirstXXX"` instead of `"XXX1"`.

Move the markers to the beginning would get an error: `A member initializer in a enum declaration cannot reference members declared after it, including members defined in other enums.`

It would resolve changing the order in the genarated code for every enum option that is declared as `EnumOption = AnotherOption`:

```diff
var SyntaxKind;
(function (SyntaxKind) {
+    SyntaxKind[SyntaxKind["FirstXXX"] = 0] = "FirstXXX";
+    SyntaxKind[SyntaxKind["LastXXX"] = 2] = "LastXXX";
     SyntaxKind[SyntaxKind["XXX1"] = 0] = "XXX1";
     SyntaxKind[SyntaxKind["XXX2"] = 1] = "XXX2";
     SyntaxKind[SyntaxKind["XXX3"] = 2] = "XXX3";
     SyntaxKind[SyntaxKind["Count"] = 3] = "Count";
-    SyntaxKind[SyntaxKind["FirstXXX"] = 0] = "FirstXXX";
-    SyntaxKind[SyntaxKind["LastXXX"] = 2] = "LastXXX";
})(SyntaxKind || (SyntaxKind = {}));
```

**Comment by lmcarreiro** [comment]
Or keep the order, but avoid overriding previous values:

```diff
var SyntaxKind;
(function (SyntaxKind) {
     SyntaxKind[SyntaxKind["XXX1"] = 0] = "XXX1";
     SyntaxKind[SyntaxKind["XXX2"] = 1] = "XXX2";
     SyntaxKind[SyntaxKind["XXX3"] = 2] = "XXX3";
     SyntaxKind[SyntaxKind["Count"] = 3] = "Count";
-    SyntaxKind[SyntaxKind["FirstXXX"] = 0] = "FirstXXX";
-    SyntaxKind[SyntaxKind["LastXXX"] = 2] = "LastXXX";
+    SyntaxKind["FirstXXX"] = 0;
+    SyntaxKind["LastXXX"] = 2;
})(SyntaxKind || (SyntaxKind = {}));
```

**Comment by lmcarreiro** [comment]
I created a function (https://gist.github.com/lmcarreiro/3a2af88320025879317dce951bad0258) to map those markers names, but if new options are added, the `LastXXX` will change and the code will return the wrong kind name. It would be nice to have some built-in solution for this problem.

**Comment by mhegazy** [comment]
In hindsight we should have done that.. but I am afraid this would be a breaking change now to existing code bases. It will be a subtle one to figure out since the change in behavior will be silent.

**Comment by lmcarreiro** [comment]
But you could allow to define like this without errors:

```ts
enum SyntaxKind {
  FirstXXX = XXX1,
  LastXXX = XXX3,
  
  XXX1,
  XXX2,
  XXX3,

  Count,
}
```

**Comment by Proculopsis** [comment]
Here is a hideous workaround in the Playground:

https://goo.gl/psXTpk

**Comment by mhegazy** [comment]
> But you could allow to define like this without errors:

that is not the issue. the issue is the change in the default emit behavior silently. i do not think we can do that now.
Having ppl define their markers at the top seems like a fix worse than the original problem. most users will not do that, and there is not guarantee that they will not miss some enum members either.
