### ISSUE TITLE
[Requested Feature] Intersection types for enums

### ISSUE THREAD

**Issue by Right2Drive** [Microsoft/TypeScript#20136]
**TypeScript Version:**  2.6.1

**Code**

```ts
enum Fruit {
  APPLE = 'Apple',
}

enum Veggies {
  CARROT = 'Carrot',
}

type FruitAndVeggies
  = Fruit
  & Veggies;
```

**Requested behavior:**
An intersection type of Fruit & Veggies
ie the following:
```ts
type FruitAndVeggies = 'Apple' & 'Carrot';
```

**Actual behavior:**
```ts
type FruitAndVeggies = never
```

**Use Case**
Writing a Vue application with Typescript and using Vuex. I have used enums to enforce type strictness on the names of the mutations, actions and getters similar to the following:

```ts
export enum MutationTypes {
  SET_DRAWER_SHOWN = 'setDrawerShown',
}

const mutations = {
  [MutationTypes.SET_DRAWER_SHOWN] (state: AppState) {
    // ...
  },
};
```

Doing it this way however prevents me from using the `Mutations = Module1Mutations | Module2Mutations` type as an argument to commit mutations, if one of my `<module>Mutations` enums is empty (due to `commit(type: string)`. I have created a workaround, but this feature would be nice if other people are also interested in it. Also if anyone has an appropriate solution that I haven't though of suggestions are welcome :grin: 

Thanks for Typescript!

**Comment by andy-ms** [comment]
`'Apple' & 'Carrot'` is indeed `never` because no string can be equal to `'Apple'` but also be equal to `'Carrot'`. Could you provide a simpler example of what you're trying to do?

**Comment by Right2Drive** [comment]
Of course, having it explained that way makes my question seem dumb haha. Basically I have a situation like the following:
- 2 enums with string values
- A union type of both, which is essentially a union type of all the possible string values (correct me if I'm wrong)

The second that one of the enums is empty, the union type is no longer a union of strings, and therefore cannot be the parameter for a function requiring a string argument.

**Comment by andy-ms** [comment]
You *can* union string enums -- that uses the `|` type operator instead of `&`. But if an enum is empty we treat it as a number enum and not a string enum.

**Comment by Right2Drive** [comment]
Alright, will just continue with the current workaround, thanks!
