### ISSUE TITLE
instanceof doesn't work on non-any types

### ISSUE THREAD

**Issue by bluong** [Microsoft/TypeScript#2013]
Hey Typescript!

Our library is trying to fully incorporate the union type feature.  However when using it, when differentiate between the two types, it seems that the most natural way to determine the type through `instanceof`.  However, it seems that the compiler complains if a non-any is passed in as an argument.  Is this a bug or what's the best way to differentiate between the given union types

**Comment by danquirk** [comment]
Are you using unions of primitive types? You should use typeof for that. Otherwise instanceof should work in type guards for object types. Can you post the code you're having issue with?

**Comment by bluong** [comment]
Here's the code example
https://github.com/palantir/plottable/blob/removeDatasetUnion/src/components/plots/abstractPlot.ts#L329

Notice that I'm currently forced to any-cast the variable so that the instanceof usage can compile

**Comment by danquirk** [comment]
Your type guard syntax isn't quite right. You don't want to parenthesize arguments to typeof and instanceof or else it won't be recognized as type guard. This stripped down copy works without errors and no casts required:

```ts
class Dataset { data() {} }

function  removeDataset(datasetIdentifier: string | Dataset | any[]) {
  var key: string;
  if (typeof datasetIdentifier === "string") {
    key = datasetIdentifier;
  } else {
    var index = -1;
    if (datasetIdentifier instanceof Dataset) {
      var datasetArray = this.datasets();
      index = datasetArray.indexOf(datasetIdentifier);
    } else if (datasetIdentifier instanceof Array) {
      var dataArray = this.datasets().map(d => d.data());
      index = dataArray.indexOf(datasetIdentifier);
    }
    if (index !== -1) {
      key = this._datasetKeysInOrder[index];
    }

  }
}
```

**Comment by bluong** [comment]
I tried to change the code accordingly and I still get
"The left-hand side of an 'instanceof' expression must be of type 'any', an object type or a type parameter."

`
public removeDataset(datasetIdentifier: string | Dataset | any[]): AbstractPlot {
      var key: string;
      if (typeof(datasetIdentifier) === "string") {
        key = <string> datasetIdentifier;
      } else if (typeof (datasetIdentifier) === "object") {

        var index = -1;
        // HACKHACK: forced to any cast to use instanceof
        if (datasetIdentifier instanceof Dataset) {
          var datasetArray = this.datasets();
          index = datasetArray.indexOf(<Dataset> datasetIdentifier);
        } else if (datasetIdentifier instanceof Array) {
          var dataArray = this.datasets().map(d => d.data());
          index = dataArray.indexOf(<any[]> datasetIdentifier);
        }
        if (index !== -1) {
          key = this._datasetKeysInOrder[index];
        }

      }

      return this._removeDataset(key);
    }
`

**Comment by bluong** [comment]
Oh got it.  Thanks!
