### ISSUE TITLE
Compiler API - Type parameter constraint and default always undefined

### ISSUE THREAD

**Issue by dsherret** [Microsoft/TypeScript#20137]
**TypeScript Version:**  2.7.0-dev.2011118

**Code**

Test code:

```ts
let t: <T extends string = string>() => void;
```

Compiler code:

```ts
const type = ...; // get type of VariableDeclaration
const signature = type.getCallSignatures()[0]; 
const typeParam = signature.getTypeParameters()[0];
typeParam.constraint; // undefined
typeParam.default; // undefined
```

**Expected behavior:** A string type will be returned for both.

**Actual behavior:** Always returns undefined.

*typescript.d.ts* says the following:

```ts
interface TypeParameter extends TypeVariable {
    /** Retrieve using getConstraintFromTypeParameter */
    constraint: Type;
    default?: Type;
}
```

**Problems**
* Both properties are always undefined (from why I've tried).
* `getConstraintFromTypeParameter` does not exist anywhere in the compiler api.
* `constraint: Type` should have a question token.

**Workaround**
1. Get type's symbol.
2. Get symbol's type parameter declaration.
3. Get type via type checker from type parameter declaration's constraint and default nodes (if they exist).

**Comment by mhegazy** [comment]
We need to make these internal and instead expose `getDefault` and `getConstraint` on a `TypeObject`.

**Comment by dsherret** [comment]
Thanks guys!
