### ISSUE TITLE
Language Service identifying the wrong kind inside a <cast> after boolean operators

### ISSUE THREAD

**Issue by lmcarreiro** [Microsoft/TypeScript#20133]
**TypeScript Version:**  2.7.0-dev.20171118

**Code**

```ts
if (<number>SyntaxKind.FirstPunctuation <= <number>token.syntaxKind && <number>token.syntaxKind <= <number>SyntaxKind.LastPunctuation) {
//                                                                      ~~~~~~ wrong color
```

**Expected behavior:**
All types inside `<cast>` be identified as the same kind

**Actual behavior:**
The third one (after `&&`) are different than the others

I get the same behavior in VSCode and GitHub syntax highlight, so, I think that both uses the information provided by the Language Service API to decide which color each token/word will have.

**Comment by lmcarreiro** [comment]
It looks like it just happens after boolean operators:
```ts
  <number>1 && <number>2 & <number>3 | <number>4 + <number>5 ^ <number>6 && (<number>5)
//              ~~~~~~      ~~~~~~      ~~~~~~      ------      ~~~~~~        ------
//                                                  ok here, after '+'        ok here, after '('
```

**Comment by mhegazy** [comment]
Mind filing this under https://github.com/Microsoft/TypeScript-TmLanguage instead?

**Comment by lmcarreiro** [comment]
It will be handled at https://github.com/Microsoft/TypeScript-TmLanguage/issues/543
