### ISSUE TITLE
Compiler error with "namespace" and "module" names

### ISSUE THREAD

**Issue by Proculopsis** [Microsoft/TypeScript#20147]
The compiler generates an error if a "namespace" or "module" contains a keyword, eg:

namespace just.for.fun { } // generated JavaScript: "for (.fun; {}; );"

"for" is flagged as "Identifier expected."

Example in the Playground: https://goo.gl/8JYaUo

**Comment by Proculopsis** [comment]
...on reflection, this behaviour is expected but the error message is abstruse.

**Comment by andy-ms** [comment]
How about "non-keyword identifier expected"?

**Comment by Proculopsis** [comment]
Cool, thanks Andy.
