### ISSUE TITLE
Feature request: code blocks

### ISSUE THREAD

**Issue by lyonzy** [Microsoft/TypeScript#20145]
Hi,

I was wondering if it would be possible to have 'code blocks', basically that are the same as IIFEs, such as:

```
var data = {
    return "abc"
}

// compiles to:
var data = (function() {
    return "abc"
})();
```

This is a very simple example but it could be expanded to bigger and better things (like "async blocks"):

```
var data:number[] = [1,2,3]
var promises:Promise<any>[] = [];

// BEFORE
promises.push((async () => {
    var data = await doSomeLongOperation();
    thenDoSomethingWithTheResult(data);
})())

// (or this)
promises.push(doSomeLongOperation().then(() => thenDoSomethingWithTheResult()))

// AFTER
promises.push(async {
    var data = await doSomeLongOperation();
    thenDoSomethingWithTheResult(data);
})
```

So basically such an 'async block' would resolve to a promise, and be compiled to an IIFE.

Does that sound like something worth considering? Or have I missed any way in which this is already possible?

**Comment by lyonzy** [comment]
Actually it looks like blocks like this are already supported, only they don't evaluate to expressions. 

Is there any way (either using these blocks or otherwise) that we could simplify the IIFE pattern, particularly for async code?

**Comment by yortus** [comment]
This sounds like [`do` expressions](https://github.com/tc39/proposal-do-expressions), which are at Stage 1 in the TC39 process. If that gets to Stage 3, it will likely make its way to TypeScript.

The async version is an interesting extension which you may like to open an issue for on the `do` expression repo.

**Comment by lyonzy** [comment]
Interesting - it looks like there already is one:
https://github.com/tc39/proposal-do-expressions/issues/4

Anyway that's what I'm after - I'll leave it up to you folks whether you want to keep this issue open or close. Thanks for the info :)

**Comment by aluanhaddad** [comment]
Oddly, given,
```ts
var data = {
    return "abc"
}
```
tsc emits
```js
var data = {
    return: "abc"
}
```
which is valid JavaScript.

**Comment by andy-ms** [comment]
We'll wait for JavaScript to have a feature like this instead of implementing one on our own.
