### ISSUE TITLE
Unable to define SVG elements conflicting with HTML

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#20149]
**TypeScript Version:**  master

**Expected behavior:**

```ts
interface SVGElementTagNameMap {
    'a': SVGAElement;
}
interface ElementTagNameMap extends HTMLElementTagNameMap, SVGElementTagNameMap {
}
```

But deriving from both `HTMLElementTagNameMap` and `SVGElementTagNameMap` still throw an error by conflicts. To resolve this, `ElementTagNameMap` has to be defined using Diff type as follows.

```ts
interface ElementTagNameMap extends HTMLElementTagNameMap, Diff<SVGElementTagNameMap, HTMLElementTagNameMap> {
}

type Diff<T, U> = Pick<T, DiffKey<keyof T, keyof U>>;
type DiffKey<T extends string, U extends string> = (
  & { [P in T]: P; }
  & { [P in U]: never; }
  & { [x: string]: never; }
)[T];
```

However, defining `ElementTagNameMap` is originally wrong. It should be removed later.

**Actual behavior:**

```ts
interface ElementTagNameMap {
    'a': SVGAElement; // error, conflicts with 'a': HTMLAnchorElement;
}
```

related: #20134, #14783

**Comment by mhegazy** [comment]
We should not include `Diff` in the library.  For ones that conflict having them default to the HTMLElement seems like a reasonable compromise.

**Comment by falsandtru** [comment]
We can resolve this issue without Diff type by removing `ElementTagNameMap`: https://github.com/Microsoft/TSJS-lib-generator/pull/326
