### ISSUE TITLE
Closure arrow syntax with async iterables is broken

### ISSUE THREAD

**Issue by derolf** [Microsoft/TypeScript#20140]
**TypeScript Version:**  2.6.1

**Code**

```
class Test {
  async * bar() {
    const c = async * () => {
    };
    yield * c();
  } 
```
**Expected behavior:**

...: error TS1109: Expression expected.
...: error TS1005: ';' expected.

**Actual behavior:**

It should compile. It does compile if I use an inline function instead of arrow syntax.

**Comment by DanielRosenwasser** [comment]
[There's a stage 1 proposal for generator arrow functions](https://github.com/tc39/proposals/tree/267d16f9ec7640b5c89b20a851d94dffa711acee) in TC39, which I assume would encompass this, but right now this isn't valid syntax.
