### ISSUE TITLE
`ts.UnionOrIntersectionType` representation of unions flattens aliased unions

### ISSUE THREAD

**Issue by mprobst** [Microsoft/TypeScript#20156]
TypeScript's internal APIs flatten union types that contain aliases of other union types:

```typescript
type UnionType = string|number;
type UnionUnionType = UnionType|boolean;
```

With the code above, `getTypeAtLocation` of `UnionUnionType` gives a union type of `string|number|boolean`. That's generally speaking correct, but it makes writing tools such as https://github.com/angular/tsickle hard – if `UnionType` is declared in one module, and `UnionUnionType` in another, the expanded/flattened constituent types of the union type possible cannot be named at the use site, so they cannot be emitted in meaningful way.

This is caused by `addTypeToUnion` in `checker.ts` unwrapping aliases. An alternative to emitting based on `ts.Type` would be falling back to the syntactic form (`ts.TypeNode`), but that brings other drawbacks (in particular, the inability to make interesting queries about the types being emitted).

**Comment by mprobst** [comment]
Possibly related: #18754.

**Comment by ahejlsberg** [comment]
The type checker definitely relies on unions being flattened in a number of places and it would be non-trivial (and detrimental to performance) to change that.

Note that for object, union, and intersection types, we do record an `aliasSymbol` in the `Type` object whenever possible. When this property is non-undefined, it references the symbol of a type alias for the particular type, and `aliasTypeArguments` specify the type arguments for the alias, if any. For example, the `Type` object returned by `getTypeAtLocation` for `UnionUnionType` will link back to the symbol for the `UnionUnionType` type alias.

**Comment by mprobst** [comment]
I found `aliasSymbol`, and that works well for my `UnionType` above. The problem is with `UnionUnionType`.

How does TypeScript produce the correct type when creating a `.d.ts` file for such flattened union types?

**Comment by mhegazy** [comment]
In .d.ts emit, we use the node if present, and then we will use the `aliasSymbol` if present. otherwise it falls back to the expanded type. It is worth noting that the declaration emitter uses the same `typeToString`/`typeToTypeNode` APIs that are exposed on the checker.
