### ISSUE TITLE
Default arguments are undefined if the function is called before the value is defined.

### ISSUE THREAD

**Issue by geon** [Microsoft/TypeScript#20158]
**TypeScript Version:**  2.7.0-dev.20171118

**Code**

```ts
console.log(myFunction());

const myConstant = "";

function myFunction(myArgument: string = myConstant): string {
	return myArgument;
}
```

**Expected behavior:**
An error on line 1, telling me that `myConstant` is undefined.

**Actual behavior:**
It compiles. In Chrome, the resulting JS throws a runtime error, and in Node and `myFunction` returns `undefined`, even though the type says it should return a string.

**Comment by mhegazy** [comment]
There is a limit to checking the  compiler can do statically to model a dynamic language like JavaScript. We have chosen to error on the side of permissiveness in such scenarios, instead of being overly restrictive.

**Comment by jonaskello** [comment]
It seems this situation is not really allowed in JS either. That is at least what I gather from running from this experiment:

**test.js**
```js
console.log(myFunction());
const myConstant = "";
function myFunction(myArgument = myConstant) {
  return myArgument;
}
```

```bash
$ node --version
v8.6.0
$ node test.js
/Users/JonKel/code/pp/test.js:3
function myFunction(myArgument = myConstant) {
                                 ^

ReferenceError: myConstant is not defined
    at myFunction (/Users/JonKel/code/pp/test.js:3:34)
    at Object.<anonymous> (/Users/JonKel/code/pp/test.js:1:75)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:607:3
```

While JS throws an error in run-time, it would be nice if TS could catch this at compile time. Though I guess that would require some statical analysis that might be complicated to implement.

**Comment by jonaskello** [comment]
TS does not allow this simpler situation at compile time (while JS actually allows it):

**test.ts**
```
console.log(myConstant);
const myConstant = "";
```

```
$ tsc test.ts
test.ts(2,13): error TS2448: Block-scoped variable 'myConstant' used before its declaration.
```
Here is what happens when running `test.js` compiled from above.

```
$ node test.js
undefined
```
