### ISSUE TITLE
Suggestion: string | 'one' | 'two' — avoid collapsing to just string

### ISSUE THREAD

**Issue by mihailik** [Microsoft/TypeScript#20154]
```ts
type HTMLTag: 'div', 'span', 'table', 'h1' | string;
```

**Expected behavior:**
Keep full union+primitive type intact when reporting the type of `tag` argument. All compatibility, overloading, inference rules still apply as today, but richer type would be reported **to the tooling** and into the generated **declaration.d.ts**.

**Actual behavior:**
```ts
type HTMLTag: string;
```

Preserving this kind of 'trivia' can help documentation and provide better code completion in editors.

When you type in your code, IDE will use suggested union values for intellisense completion. But it still allows you to type an arbitrary string too, no complaining.

Also helps with documenting and hand-crafted `.d.ts` in DefinitelyTyped. You can specify known good values, but allow others as well.

**Comment by mhegazy** [comment]
if this is just an IDE feature, why not explore some comment instead?

**Comment by mihailik** [comment]
1) Easier to read, unambiguous
2) IDEs completions

Look at <a href="https://github.com/DefinitelyTyped/DefinitelyTyped/blob/ed43ece3e55c8b435298c99fc57971fd6bbc842d/types/codemirror/index.d.ts#L724">`mode` definition</a> in `CodeMirror` typings:

```ts
        /** string|object. The mode to use. When not given, this will default to the first mode that was loaded.
        It may be a string, which either simply names the mode or is a MIME type associated with the mode.
        Alternatively, it may be an object containing configuration options for the mode,
        with a name property that names the mode (for example {name: "javascript", json: true}). */
        mode?: any;
```

Bla bla bla, so many words people rarely read. Docs have their use, but would be much better:
```ts
        /** string|object. The mode to use. When not given, this will default to the first mode that was loaded.
        It may be a string, which either simply names the mode or is a MIME type associated with the mode.
        Alternatively, it may be an object containing configuration options for the mode,
        with a name property that names the mode (for example {name: "javascript", json: true}). */
        mode?: 'javascript' | 'html' | 'markdown' | 'clike' | string | {};
```

```ts
var editor = new CodeMirror(host, { mode: "|
                                           "javascript"  <-- completions
                                           "html"
                                           "markdown"
                                           "clike"
```

**Comment by mhegazy** [comment]
The compiler (and hence the language service), relies on flattening unions of that form. we get a lot of performance benefits when doing comparisons by eliminating unions that we know are equivalent to one of their constituents.. e.g. `string` in the case of `"a" | "b" | string`. 

If this is used in a function/method, consider using overloads instead.
