### ISSUE TITLE
'Go to definition' doesn't work if the module doesn't have 'import' or 'export' statements.

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#20163]
_From @yay on November 18, 2017 22:47_

- VSCode Version: 1.18.1
- OS Version: 10.12.6

Steps to Reproduce:

main.js
```
// importing for side effects
import './features/sets'; // Cmd-clicking on 'sets' makes no action.
```
./features/sets.js
```
let array = ['a', 'b', 'c', 'a'];
let set = new Set(array);
console.log(set);  // Set { 'a', 'b', 'c' }

// export {};     // uncomment to make the 'Go to definition' in main.js work
```

_Copied from original issue: Microsoft/vscode#38702_

**Comment by mhegazy** [comment]
this is currently a design limitation. the system knows about modules if they have a top-level import/export  (or require in a .js file). otherwise, the compiler does not parse at as a module, and does not treat it like one.
