### ISSUE TITLE
TS AutoImport deep vs shallow imports

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#20160]
_From @bradzacher on November 20, 2017 4:12_

I noticed that when doing an autoimport in TS, code seems to prefer deep imports over shallow ones.

I.e. when working with `graphql`, if you try and import `GraphQLString`, code places this import `import { GraphQLString } from 'graphql/type/scalars';` instead of using the import on the base package `import { GraphQLString } from 'graphql';`.

It would be good if code could detect this and prefer shallow imports where possible.
Esp with node module imports, because doing a deep import can technically be fragile (i.e. a module author may not intend you to import from one of the modules' internal folders).

_Copied from original issue: Microsoft/vscode#38744_

**Comment by mjbvz** [comment]
Possible duplicate of #19694

**Comment by mhegazy** [comment]
Should be working correctly in latest drop of TypeSript (`typescript@next`). VSCode ships with an older version of TypeScript. Please see [Using Newer TypeScript Versions](https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions) documentation for more details on updating your VSCode to use a different version of TypeScript.
