### ISSUE TITLE
TS AutoImport style config enhancement

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#20161]
_From @bradzacher on November 20, 2017 4:9_

I love the new TS autoimport, saves so much time having to manually type out imports, also getting auto complete for things not even in your file is amazing.

That being said, a few configuration options would be nice:
- Our style guide means no semicolons, but the code automatically adds one (so I have to cursor up to delete it).
- Additionally our style guide also calls for absolute imports to come before relative ones, but code just places it at the end (so I have to go and move it manually).

_Copied from original issue: Microsoft/vscode#38743_

**Comment by mjbvz** [comment]
Semicolon part tracked by #19882

**Comment by alextreppass** [comment]
Hi @mjbvz, will this also allow configuring autoimports to be absolute relative to baseUri, instead of fully relative (`../../...`)?

Related:
https://github.com/Microsoft/TypeScript/issues/21860

These two have been marked as closed / fixed, but it's not clear where the fix will be:
https://github.com/Microsoft/TypeScript/issues/22249
https://github.com/Microsoft/TypeScript/issues/20619

Thanks

**Comment by mjbvz** [comment]
Closing this as both of the issues have been addressed by the following VS Code settings:

- `javascript.format.semicolons` / `typescript.format.semicolons` for semicolons (auto imports also try to infer this now. 
- `javascript.preferences.importModuleSpecifier` / `typescript.preferences.importModuleSpecifier` for import style (relative vs absolute)

**Comment by matronator** [comment]
Uhm, I know this is closed, but I don't want to open a new issue as this is more of a question.

I'm having trouble getting the autoimport feature to include `./` at the start of the path for local imports. I tried changing all the settings mentioned above and more to all the possible options and I tried setting it with `jsconfig.json` - tried pretty much all the possible combinations of these settings - but I just can't get it to work.

The closest I got was the default setting, which made the import paths like this `import FML from '../components/FML'`, but I still have to manually put the `./` before each import path to change it to this `import FML from './../components/FML'` :( Can anyone help me please (if so, you can send me a mail to not clutter up this post)?
