### ISSUE TITLE
Generic Type Alias

### ISSUE THREAD

**Issue by Mudhoax** [Microsoft/TypeScript#2017]
I'd love to have the ability to be able to create generic type aliases.

At the moment we are using interfaces to reference our common function signatures.

    interface IGenericCallback<T> {
        <T>(val: T, index: number, arr: Array<T>): void;
    }

I'd love to be able to remove these interfaces and use something along the lines of:

    type GenericCallback<T> = <T>(val: T, index: number: arr: Array<T>): void;

Is this something that may be considered as a feature enhancement?

Regards,
Ian Munro

**Comment by donnut** [comment]
:+1:

**Comment by danielearwicker** [comment]
See #1616.
