### ISSUE TITLE
hyperlink of node_modules from .ts file to js modules without definition

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#20182]
_From @evollu on October 31, 2017 3:48_

- VSCode Version: 1.17.0
- OS Version: mac

Steps to Reproduce:

For example following code  `var Kafka = require('node-rdkafka');`. 
- When this code is in a js file, I can cmd+click to go to the index.js file in node_modules and hovering over shows definitions.
- When this code is in a ts file, nothing happens when I hover to click. tsc compiles without any complaint so tsconfig.json should be fine.
- I tried `import * as Kafka from 'node-rdkafka'` and it is the same behavior

here is tsconfig.json
```
{
    "compilerOptions": {
        "target": "es5",
        "lib": [
            "es2017"
        ],
        "outDir": ".dist",
        "sourceMap": true,
        "removeComments": false,
        "alwaysStrict": true
    }
}
```

Reproduces without extensions: Yes

_Copied from original issue: Microsoft/vscode#37203_

**Comment by mhegazy** [comment]
First, in a `.ts` file `var Kafka = require('node-rdkafka');` is a `var` declaration and `require` is just a function call. the compiler does not treat them any differently.. the correct syntax here is `import Kafka = require('node-rdkafka')` or `import * as Kafka from "node-rdkafka"`.

Second, in a .js file, an import to `node-rdkafka` will try to find a .d.ts for it, and it failed to find one, it will use the .js file from your `node_modules/node-rdkafka`. The `.js` file does not have type information, so it is not accurate to check against. In a.ts file the compiler is a bit stricter than in a .js file, and will **only** load a .d.ts file for `node_rdkafka`. consider adding a declaration file for it under https://github.com/DefinitelyTyped/DefinitelyTyped.

**Comment by evollu** [comment]
to answer one,  `var Kafka = require('node-rdkafka');` seems to be a valid nodejs syntax. will that cause any trouble in typescript?

to answer two, is there any reason why only load .d.ts file for .ts? Could there be a fallback behavior done through vscode?
only half of our dependencies have .d.ts file so it will be nice to have basic js feature from vscode.

**Comment by mhegazy** [comment]
> to answer one, var Kafka = require('node-rdkafka'); seems to be a valid nodejs syntax. will that cause any trouble in typescript?

TypeScript does not target node only, and since node has a specific semantics to what `require` means, it makes it hard to generate the code written to target node to say `ES6`. 
You can use the ES6 standard module system in TS. please see http://www.typescriptlang.org/docs/handbook/modules.html for more information.

**Comment by mhegazy** [comment]
> to answer two, is there any reason why only load .d.ts file for .ts? Could there be a fallback behavior done through vscode?

The process is lossy.. the .js file does not have types.. in a .ts file you are asking the compiler to check your code against a library.. it seems pointless to check it against something that it does not know what it is.

**Comment by mhegazy** [comment]
>only half of our dependencies have .d.ts file so it will be nice to have basic js feature from vscode. Today I have more type support when I write in .js rather than in .ts, which is kind of pushing me back to write plain js code

You do not need to write a full .d.ts file.. you can start with the minimum.. that would be something like:
```ts
declare module "node-rdkafka"; 
```

consider also using something like [dts-gen](https://github.com/Microsoft/dts-gen) to generate the files for you.. also keep in mind that this is a one-time investment, and after that all your code will correctly check against your dependencies.

**Comment by evollu** [comment]
I just realized my issue is ported to `typescript` github. I originally posted on `vscode`'s.
Yeah I agree typescript should keep the way it is.

I will try `dts-gen` thanks.
