### ISSUE TITLE
New Website Logo: Vingle

### ISSUE THREAD

**Issue by mooyoul** [Microsoft/TypeScript#20187]
Please fill the following out:

- Name: Vingle
- Homepage url: https://www.vingle.net
- Brand Guidelines/Licensing: 
Guideline: Not Available 
Licensing: Non-comercial use only
- Logo: (svg if possible, pngs over 500x200px with transparent backgrounds are also acceptable)
http://s0.vingle.net/Vingle_Wordmark_RGB_Original_03.png

Hi guys. first of all, thank you all contributors for making this awesome projects. It's really productive language for Web Platform!

Now, We are using Typescript as our primary development language.

We have about 50+ projects that written in Typescript (most of them are microservice projects. It's pretty good!). we've created [typescript based DynamoDB ORM](https://github.com/balmbees/dynamo-typeorm), [Web Framework for AWS Lambda](https://github.com/balmbees/corgi), [Microservice template](https://github.com/balmbees/lambda-microservice-template) and yeah, also we've contributed some non-typescript projects like [dynamoose](https://github.com/automategreen/dynamoose/pull/123) to help providing their's own type definitions.

**Comment by mhegazy** [comment]
Should be available the next time the site is published

**Comment by mooyoul** [comment]
@mhegazy Thanks! :)
