### ISSUE TITLE
valueOf can be imported from anywhere

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#20191]
so i have `valueOf` function defined in module `xxx.ts`
```ts
export function valueOf<T>(value: { value: T; }): T {
    return value.value;
}
```

then in file `yyy.ts` i am trying to do auto import and this is what i see:

![image](https://user-images.githubusercontent.com/937933/33073557-463293b4-ce91-11e7-925e-00ca6bebffd5.png)

**Comment by andy-ms** [comment]
It looks like if you write:
```ts
declare const x: number;
export = x;
```
we will treat `valueOf` as an export of that module.
Normally we would want to include methods on an `export = ` object, but maybe we should add an exception for primitives.

**Comment by aleksey-bykov** [comment]
you should not include methods because they need proper `this` object in order to work
