### ISSUE TITLE
Constant overload not working in classes

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#2020]
Compile the following test case:

class Bug {

	public foo(id:"special", value:number):void;
	public foo(id:string, value:any):void {
	}
}

You get:
bug.ts(3,2): error TS2382: Specialized overload signature is not assignable to any non-specialized signature.

Compiler version: message TS6029: Version 1.4.0.0

**Comment by RyanCavanaugh** [comment]
This is the correct behavior. The implementation signature is not part of the overload sets (it's effectively "invisible"); you need an overload that has `id: string` that is *not* the implementation signature.
