### ISSUE TITLE
Partial of interface and generic is not compiled

### ISSUE THREAD

**Issue by keenondrums** [Microsoft/TypeScript#20204]
**TypeScript Version:**  2.7.0-dev.20171121

**Code**
```ts
interface A {
    af: string
}
const a = <T extends {}>(): Partial<T & A> => ({ af: 'asfa' })
```
[Link to the playground](https://www.typescriptlang.org/play/#src=interface%20A%20%7B%0D%0A%20%20%20%20af%3A%20string%0D%0A%7D%0D%0A%0D%0Aconst%20a%20%3D%20%3CT%20extends%20%7B%7D%3E()%3A%20Partial%3CT%20%26%20A%3E%20%3D%3E%20(%7B%20af%3A%20'asfa'%20%7D))

**Expected behavior:**
Should compile

**Actual behavior:**
Compilation fails

**Comment by mhegazy** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/16356, and https://github.com/Microsoft/TypeScript/issues/19388. `T` is a generic type, and no assumption can be made about what type of `af` would be in `T` at the time it is instantiated..

**Comment by keenondrums** [comment]
@mhegazy what if we do something like this?
```
interface A {
    af: string
}
const a = <T extends { af?: string }>(): Partial<T & A> => ({ af: 'asfa' })
```
This way we know what type af is. Though it still does not work.

**Comment by mhegazy** [comment]
it still can be more specific than `string`.. e.g. `a<{ af: "a" }>()`.

**Comment by keenondrums** [comment]
@mhegazy yeah, that's true. Sorry for creating this duplicate.
