### ISSUE TITLE
keyof widening to string

### ISSUE THREAD

**Issue by dpogue** [microsoft/TypeScript#20200]
**TypeScript Version:**  Version 2.7.0-dev.20171118

**Code**

```ts
class Foo<DataType> {
    public set<K extends keyof DataType>(prop : K, value : DataType[K]) {
        this.update({[prop]: value}); // Error here
    }
  
    update(data: Partial<DataType>) {
        return Promise.resolve(this);
    }
}
```

**Expected behavior:**
Compile with no errors.

**Actual behavior:**
Argument of type `{ [x: string]: DataType[K]; }` is not assignable to parameter of type `Partial<DataType>`.

This is very similar (but maybe not identical) to #13948 and #15534

**Comment by mhegazy** [comment]
Please see https://github.com/Microsoft/TypeScript/issues/16687#issuecomment-327964702 for more details

**Comment by RyanCavanaugh** [comment]
TypeScript has no other way to represent the type of the value produced by `{[prop]: value}`. We'd need some proposal for an all-encompassing feature for representing that along with use cases and proposed behavior.
