### ISSUE TITLE
Feature: Option to have non-null assertion operator compile to a runtime exception.

### ISSUE THREAD

**Issue by MicahZoltu** [Microsoft/TypeScript#20217]
I often find myself interacting with third party JS libraries that are poorly documented.  Because of this, I often don't know whether a function may yield `null` or `undefined` as a result or when calling a callback.  Often, the best way to deal with this is to just check for null and throw an exception with something like `if (foo === undefined) throw new Error('Local variable foo was undefined.");`

However, this pattern starts to get really ugly when you are working with a lambda, like in `collection.map(x => { if (x === undefined) throw new Error('x is undefined.'); return x.bar; })`.  I would _much_ rather be able to just do `collection.map(x => x!.bar)` and have TypeScript compile the non-null assertion operator down to something that includes the aforementioned check.  This way, I get the nice concise syntax, yet I protect myself from all of the garbage that is out there on the NPM.

Note: I'm aware that this could be implemented as a helper function like `function assertNotNull<T>(x: T|undefined|null): T { ... }` and then do `collection.map(x => assertNotNull(x).bar)`.  However, TypeScript already has an operator that goes in that exact spot, is much more concise than any function I could come up with, and already _feels_ like it should have the behavior described here.

It should also be noted that I believe other languages with not-null assertion operators like Kotline actually do have a runtime check, which is why TypeScript's lack of check causes so much confusion for users.  Not only does it feel like the right thing for TS to do a runtime check, that is what other languages do.

**Comment by mhegazy** [comment]
It has been one of [our design goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals#goals) to avoid adding run time overhead. we have aspire for an erasable type system with no run time impact. There are many other opportunities today for runtime checks, but these all do not jive with the language design vectors. 

The null assertion operator was also introduced to remedy limitations in the control flow analysis the compiler does today, for instance a variable defined within a callback, or through a method/function invocation. it does not make sense for these to turn into runtime checks.

The solution today as you noted is to define your own `assertNotNull` function, and use it when needed. and not to overload the meaning of the `!` operator.

For that this request is currently out-of-scope.
