### ISSUE TITLE
Spreading a property of a property of an object removes narrowing from narrowed type

### ISSUE THREAD

**Issue by jchitel** [Microsoft/TypeScript#20216]
**TypeScript Version:**  2.7.0-dev.20171121

**Code**

```ts
type A = { [key: string]: {} };
interface B {
    a?: A;
}

function doSomething(b: B): any[] {
    if (b.a) {
        return Object.keys(b.a).map(k => ({ ...b.a[k] }));
    }
    return [];
}
```

**Expected behavior:**

I expect the above to check just fine without errors.

**Actual behavior:**

There is an error on the `b.a` with the spread operator: "error TS2532: Object is possibly 'undefined'."

I can work around the issue by changing it to this:

```ts
type A = { [key: string]: {} };
interface B {
    a?: A;
}

function doSomething(b: B): any[] {
    if (b.a) {
        const c = b.a;
        return Object.keys(b.a).map(k => ({ ...c[k] }));
    }
    return [];
}
```

The intermediate variable maintains the narrowed type, but `b.a` by itself does not. As far as I can tell, this specific scenario causes this:

- Type (`A`) has a property with a value with an object type.
- Type (`A`) is the type of a property of another type (`B`).
- Type is narrowed (using `if (b.a)`).
- Object property in `b.a` is spread into another object.

**Comment by mhegazy** [comment]
Please see https://github.com/Microsoft/TypeScript/issues/16928 for more details..

the compiler does not know if `b.a` would be changed when the function call happens.. consider declaring `a` as `readonly`.

**Comment by jchitel** [comment]
Ah, that makes a lot of sense. However, adding `readonly` doesn't fix the issue. I even tried changing the type of `b` to `Readonly<B>` and it still gives me the same error.

**Comment by mhegazy** [comment]
I think you are running into narrowing of properties defined by an index access.. that should be fixed in latest. give `typescript@next` a try.
