### ISSUE TITLE
Formatting mapped types: inconsistent number of spaces within braces

### ISSUE THREAD

**Issue by undeadcat** [Microsoft/TypeScript#20222]
**TypeScript Version:** 2.7.0-dev.20171122

**Code**
Reformat this using 'Format Document' in VS Code or in [playground](https://www.typescriptlang.org/play/#src=type%20One%3CT%3E%20%3D%20%7B%5BK%20in%20keyof%20T%5D%3A%20number%7D%0Atype%20Two%3CT%3E%20%3D%20%7B%20%20%20%20%5BK%20in%20keyof%20T%5D%3A%20number%20%20%20%20%20%7D%0A%0A%0Atype%20Four%3CT%3E%20%3D%20%7B%5BK%20in%20keyof%20T%5D%3A%20number%3B%7D%0Atype%20Three%3CT%3E%20%3D%20%7B%20%20%20%20%5BK%20in%20keyof%20T%5D%3A%20number%3B%20%20%20%20%20%7D%0A%0A%0Atype%20Obj1%20%3D%20%7Bfoo%3Anumber%7D%0Atype%20Obj2%20%3D%20%7B%20bar%3Anumber%20%7D):
```
type One<T> = {[K in keyof T]: number}
type Two<T> = {    [K in keyof T]: number     }

type Four<T> = {[K in keyof T]: number;}
type Three<T> = {    [K in keyof T]: number;     }

type Obj1 = {foo:number}
type Obj2 = { bar:number }
```

Notice that inside mapped types:
1) spaces after '{' are always removed
2) spaces before '}' depend on wether a semicolon is present - unchnanged if no semicolon, one space added if semicolon.

Compare this behavior with object types. 
Doesn't seem consistent that left and right sides behave differently, or that spacing depends on the presence of optional semicolon.

**Actual:**
```
type One<T> = {[K in keyof T]: number}
type Two<T> = {[K in keyof T]: number     }

type Four<T> = {[K in keyof T]: number; }
type Three<T> = {[K in keyof T]: number; }

type Obj1 = { foo: number }
type Obj2 = { bar: number }
```
**Expected:** A consistent number of spaces, 0 or 1 on both sides.

**Comment by mhegazy** [comment]
A PR would be appreciated.

**Comment by lmcarreiro** [comment]
I'm creating a VSCode plugin to format this:

```ts
type One <T> = { [K in keyof T]: number  }
type Two <TofType> = { [K in keyof TofType]: number  }
type Four <T> = { [K in keyof T]: number; }
type Three<T> = { [K in keyof T]: number; }
```

into this:
```ts
type One  <T      > = { [K in keyof T      ]: number  }
type Two  <TofType> = { [K in keyof TofType]: number  }
type Four <T      > = { [K in keyof T      ]: number; }
type Three<T      > = { [K in keyof T      ]: number; }
```

What would a 'Format Document' do in this case? It would mess up? If yes, could it be done in a way that doesn't mess it up?

**Comment by lankaapura** [comment]
@mhegazy  I have sent the PR https://github.com/Microsoft/TypeScript/pull/21712 to fix this issue.

@lmcarreiro space formatting related rules are defined as user configurable. Refer https://github.com/Microsoft/TypeScript/blob/master/src/services/formatting/rules.ts#L261. You might be able to override it from the plugin. Maybe @mhegazy  can confirm.

**Comment by mhegazy** [comment]
thanks @lankaapura !
