### ISSUE TITLE
Emit native ES6 classes with --target ES6

### ISSUE THREAD

**Issue by danquirk** [Microsoft/TypeScript#2022]
class A { foo: string; }
class B extends A { bar: string; }

compiling with --target ES6 currently still uses our own __extends and not ES6 classes.

**Comment by tarh** [comment]
If a class is located in an internal module, is it possible to generate an ES6 class?

**Comment by DanielRosenwasser** [comment]
@tarh classes are just expressions in ES6, so there shouldn't be a problem as far as I can tell.

**Comment by yuit** [comment]
The feature is implemented and pull into master
