### ISSUE TITLE
"Variable used before assignment" error after exhaustive conditional assignment

### ISSUE THREAD

**Issue by aaronbeall** [Microsoft/TypeScript#20231]
I'm sure this is already tracked somewhere but I couldn't find it.

**TypeScript Version:**  2.6

**Code**

With `strictNullChecks` enabled.

```ts
type Color = "red" | "blue";

declare const color: Color;

let value: string;
if (color == "red") value = "";
if (color == "blue") value = "";
value.toUpperCase() // Error: Variable 'value' is used before being assigned.
```

(Same behavior with `else` and `switch` syntax)

**Expected behavior:**

No error

**Actual behavior:**

> Error: Variable 'value' is used before being assigned.

**Comment by mhegazy** [comment]
exhaustive checks are limited to switch statements at the moment. doing this for `if` can be tricky in the general case.

**Comment by aaronbeall** [comment]
I actually started with a switch statement and got the same behavior, maybe I'm doing something wrong or else that's only supported in a newer version? If I use a `default` case (or a final `else` case) that throws then it works:

![img](http://g.recordit.co/WgtA18Qpfy.gif)

**Comment by aaronbeall** [comment]
@mhegazy Am I missing something or is this not working for switch statements?
