### ISSUE TITLE
Declaration file generated for destructuring elements is incorrect.

### ISSUE THREAD

**Issue by sheetalkamat** [Microsoft/TypeScript#2023]
Destructuing is not handled correctly (either object literal or array binding pattern) in during declaration emit.

Eg.
```TypeScript```
var { a, b } = { a: "10", b: 10 };
```

Generates
```TypeScript```
declare var { a, b }: any;
```

Expected:
```TypeScript```
declare var a: string,  b: number;
```

**Comment by yuit** [comment]
```
var a1 = [1, "hello"];
var [x] = a1;
var [x, y] = a1;
var [x, y, z] = a1
```
Generates
```
declare var [x]: any;
declare var [x, y]: any;
```
Expected:
```
declare var x: string|number;
declare var x: string|number, y:string|number;
```

**Comment by yuit** [comment]
This #2025 has fixed the issues
