### ISSUE TITLE
Make a plan to replace ElementTagNameMap with HTMLElementTagNameMap

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#20241]
`ElementTagNameMap` is deprecated now because that prevents extending `SVGElementTagNameMap` with some SVG elements conflicting with HTML such as SVGAElement. So TypeScript has to remove this annoying interface.

1. At DefinitelyTyped, Replace ElementTagNameMap with HTMLElementTagNameMap.
2. Remove ElementTagNameMap or leave it as just an alias of HTMLElementTagNameMap.

related: #20213

cc @weswigham

**Comment by falsandtru** [comment]
Step1: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21708

**Comment by mhegazy** [comment]
We are not removing `ElementTagNameMap`.. at least not in the near future. it breaks packages, and having the type in the library is harmless..
