### ISSUE TITLE
Allow custom ways to dynamically infer function return types

### ISSUE THREAD

**Issue by ronami** [Microsoft/TypeScript#20242]
Hey,

I'm using [monaco-editor](https://github.com/Microsoft/monaco-editor) to create my own custom IDE. I know `typescriptServices` is running in a web worker and provides intellisense. I want to be able to tell the intellisense engine to behave differently on some occasions. Something equivalent to Tern's [server plugin's: infer.registerFunction](http://ternjs.net/doc/manual.html#plugins).

My specific use-case is that I have a function that accepts a string and returns different types based on that string. I want to be able to tell the the intellisense engine, at runtime, that the return value for `$('button1')` is of type button.

Is there an API for this? Any workaround?

Thanks!

**Comment by mhegazy** [comment]
Looks like the same request as in https://github.com/Microsoft/TypeScript/issues/3136
