### ISSUE TITLE
Unable to use loop indexers with union index signatures in strict mode

### ISSUE THREAD

**Issue by MayaWolf** [Microsoft/TypeScript#20245]
**TypeScript Version:**  2.7.0-dev.20171123

**Code**

```ts
type Union = 'A' | 'B';
const test: {[key in Union]: string} = {A: 'a', B: 'b'};
for(const key in test) {
	test[key] = test[key] + 'a';
}
```

**Expected behavior:**
No error.

**Actual behavior:**
```
>tsc test.ts --strict
test.ts(4,2): error TS7017: Element implicitly has an 'any' type because type '{ A: string; B: string; }' has no index signature.
test.ts(4,14): error TS7017: Element implicitly has an 'any' type because type '{ A: string; B: string; }' has no index signature.
```

Sorry if this is an issue already; I couldn't find anything quite like this using the issue search or Google.
Basically I'd expect this to work without an error, as the entire point of using an index signature with a string union is to enforce type constraints, not lose them completely.
I get that this is likely because of the whole "keys are always strings at runtime" thing, but it effectively makes any object with a `[key in T]: V` constraint un-indexable in strict mode, and indexing is a big part of why you'd use a constraint like that in the first place.

**Comment by emcastro** [comment]
`{[key in Union]: string}` means “something which, for its keys in `Union`, contains strings”. It may have other keys, with different types. So `key in test` does not necessarily yield `Union` values.

Adding a type guard might be a solution to your problem:
```
type Union = 'A' | 'B';

function isUnion(key: string): key is Union {
  return key === 'A' || key === 'B'
}

const funkyData = {A: 'a', B: 'b', C: 42}
const test: {[key in Union]: string} = funkyData;
for(const key in test) {
  if (isUnion(key)) {
    test[key] = test[key] + 'a'; // does not apply to 'C'
  }
}
```

**Comment by MayaWolf** [comment]
If it's not intended to be an index signature, then why does it have the same syntax? That's not only confusing, it also makes it impossible to _also_ define an index signature for the type.
Not to mention that the `[key in T]: V` feature was somewhat 'advertised' as making more narrow index signatures possible, but considering what you just said, something like `[key: StringUnion]: V` seems to still be a missing feature, and one that would be insanely useful in a lot of places, like iterations.

**Comment by MayaWolf** [comment]
@mhegazy I'd request reopening this since it's not actually a question but an issue with how the `in` "index signature" works and/or is portrayed.

**Comment by RyanCavanaugh** [comment]
@MayaWolf we're not going to change the syntax at this point, and it's not a bug that the syntax doesn't do what you intuit it should do. I don't see anything actionable here
