### ISSUE TITLE
Generics use last rather than first matching overload

### ISSUE THREAD

**Issue by SamPruden** [Microsoft/TypeScript#20257]
**TypeScript Version:**  2.7.0-dev.20171124

**Code**

```ts
class Foo {
    bar(): 1;
    bar(): 2;
    bar(): number {
        return 1;
    }
}

interface WithBar<R> {
    bar(): R;
}

function test<R>(a: WithBar<R>): R {
    return a.bar();
}

const foo = new Foo();
const n1 = foo.bar(); // Has type 1
const n2 = test(foo); // Has type 2
```

**Expected behavior:**
`n1` and `n2` have the same type, namely `1`.

**Actual behavior:**
`n2` gets the incorrect type `2`. It seems that `R` is taken from the last matching overload, rather than the first.

I don't know if there's some detailed spec doc somewhere that I could use to confirm that this is a bug rather than a weird design, but it's definitely undesirable to me.

**Comment by mhegazy** [comment]
The assumption here is that the last signature is more general, and thus leads to better inferences.
