### ISSUE TITLE
Typing custom promises.  Advice please.

### ISSUE THREAD

**Issue by electricessence** [Microsoft/TypeScript#20251]
So the types surrounding promises has changed quite a bit over time and I've struggled to properly maintain my own promise lib and have it work happily with async/await and typing.

Since ```Promise<T>``` is an actual type in the lib, it apparently can't be used as an alias to represent a promise that is not the built in ES6 promise no?

I recently ran into:
```
TS2420: Class 'PromiseBase<T>' incorrectly implements interface 'Promise<T>'.
Property '[Symbol.toStringTag]' is missing in type 'PromiseBase<T>'
```

Where ```PromiseBase<T>``` is my base class for a variety of different promise types.
I can resolve this issue by simply adding the following to ```PromiseBase<T>```:
```ts
readonly [Symbol.toStringTag]: "Promise"; // Must be "Promise" and cannot be "PromiseBase".
```
Which I don't mind, but I feel it's not correct.

_Any thoughts on the right thing to do here?_  I think I have a solid promise lib, and want to keep using it.  But I have to name it something other than ```Promise``` for the compiler to be happy.

**Comment by electricessence** [comment]
For now I'm not adding ```Promise<T>``` to the implements list.

**Comment by mhegazy** [comment]
//CC @rbuckton

**Comment by mhegazy** [comment]
This change was introduced in https://github.com/Microsoft/TypeScript/pull/6361 to align with ES6 spec.

**Comment by mhegazy** [comment]
>Any thoughts on the right thing to do here? I think I have a solid promise lib, and want to keep using it. But I have to name it something other than Promise for the compiler to be happy.

A `Promise` as defined by ECMAScript has to have a `[Symbol.toStringTag]` whose value at runtime is `"promise"`. you get this definition when you include the lib definitions for `es2015.symbols.wellknown`. 
The compiler flags your type as an incompatible with the builtin `Promise` for that.  so either, you do not include the lib file that defines these additional properties, and your type will be assignable to `Promise`, or you add it to your type to mimic the behavior of `Promise` at runtime.

**Comment by electricessence** [comment]
So the answer is that the code must be different if you want to target >ES6... ???

**Comment by mhegazy** [comment]
This is about the definition of the type.. you can target ES6, just do not include the definitions in `--lib es2015.symbols.unknown`.

this is not different from implementing your own `Array` derived type, and having to provide matching overloads of `concate` for instance.
