### ISSUE TITLE
Suggestion: C# style class initializers 

### ISSUE THREAD

**Issue by Proculopsis** [Microsoft/TypeScript#20259]
Working hack in the Playground here:   https://goo.gl/nVyXxt

This has probably cropped up before but in the above sample the transpiler payload wouldn't be too high.
In any event, the initNoRedSquiggliesVersion might be of interest to the community

new trafficLight() {
        colourCaution = "Amber";
        colourGo = "Green";
        colourStop = "Red"
}

**Comment by DanielRosenwasser** [comment]
Hey @Proculopsis, thnaks for the suggestion. Unfortunately, this isn't something we'd consider add without ECMAScript itself first adding it.

Something you could instead do is use a class expression that subclasses the intended base class

```ts
let x = new class extends Foo {
    a = 10;
    b = 20;
    c = 30;
};
```

**Comment by Proculopsis** [comment]
Thank you very much for an excellent response Daniel and I prefer the culturally compatible correct solution.

I'm sure your example will help others, like myself, who were unaware of the 'new class extends ...' variant of 'let'.
