### ISSUE TITLE
Visual Studio 2017 IntelliSense show errors in @types folder even for unused modules

### ISSUE THREAD

**Issue by ArtemAvramenko** [microsoft/TypeScript#20253]
**TypeScript Version:**  2.3
**Visual Studio Version:**  15.4.4

When I open my solution, Typescript shows error in this file:
> C:\Users\USERNAME\AppData\Local\Microsoft\TypeScript\node_modules\@types\requirejs\index.d.ts	

I use NuGet to get all type definitions I need. How to stop use definitions from this folder for IntelliSense?

**Expected behavior:**

I do not use `requirejs` module, so I expect that IntelliSense does not show this error

**Actual behavior:**

I get error:
> Error	TS2403	(TS) Subsequent variable declarations must have the same type.  Variable 'require' must be of type 'NodeRequire', but here has type 'Require'.

**Comment by mhegazy** [comment]
Can you share your project?

**Comment by mhegazy** [comment]
//CC @billti

**Comment by ArtemAvramenko** [comment]
I cannot share my project, but I think the problem is caused by bug #14565

**Comment by billti** [comment]
@RyanCavanaugh any idea? I'm guessing something is including the Node.js definition for the global `require`, and something is includes the requirejs global definition for `require`.

Do you have JavaScript & TypeScript source files included directly in your project? Are you using a `tsconfig.json` file anywhere in the project?

**Comment by ArtemAvramenko** [comment]
> Do you have JavaScript & TypeScript source files included directly in your project?

Yes, this is the old MVC project.
> Are you using a tsconfig.json file anywhere in the project?

No, I'm not.

**Comment by RyanCavanaugh** [comment]
Closing due to lack of interest/activity - presumed fixed
