### ISSUE TITLE
Simplify/normalize intersections

### ISSUE THREAD

**Issue by pelotom** [Microsoft/TypeScript#20267]
Simply put, if `A <: B`, then `A & B` should normalize to `A`. For a motivating example, the way to define a non-nullable type operator is

```ts
type NonNullable<T> = T & {}
```

which makes sense because `{}` includes any value except `undefined` and `null`. It would be nice if types produced with this operator simplified appropriately, but currently you have for example

```ts
type X = NonNullable<number | undefined>
// currently: X = number & {}
// desired: X = number
```

or even wrose,

```ts
type Y = NonNullable<boolean | undefined>
// currently: X = (true & {}) | (false & {})
// desired: X = boolean
```

**Comment by mhegazy** [comment]
Do you have scenarios that would benefit from this change? if so can you elaborate?

**Comment by pelotom** [comment]
The scenario is inspecting large types assembled via type operators in hover info and trying to comprehend them. These types become practically unreadable when they have a bunch of unnecessary noise due to unreduced type expressions. Seeing `(true & {}) | (false & {})` instead of `boolean` is a great example; it’s very hard to make sense of the former when quickly scanning a type.

**Comment by JasonKleban** [comment]
#22930 is a scenario that would benefit from this change.

Is there any workaround to tell Typescript to do the extra work of reducing a type as it seems to do in some cases?  Like a new `Reduced<T>` conditional type?

**Comment by mhegazy** [comment]
The scenario in the OP should be covered by conditional types in 2.8.

**Comment by RyanCavanaugh** [comment]
Agree conditional types should solve this. Please log a new issue with scenarios if you have other cases you'd like to cover in depth. Thanks!
