### ISSUE TITLE
Feature request [compiler API]: expose project build logic to public API

### ISSUE THREAD

**Issue by sveinburne** [Microsoft/TypeScript#20265]
**Scenario** As a developer, I would like to use a very high level project compiler API for build purposes. It would be somehow symmetric to what `tsc` allows but in a programmatic way.
Although the [compiler API](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API) is public, the project logic for file resolution isn't (i.e. : how the `rootFileNames` are resolved before passed to `createProgram`).
I would like something simpler that would allow me to intercept a serialized `tsconfig` and alter its properties (that would somehow provide a workaround for #20110). I could also chose to merge default excludes by importing a symbol (would fix #20108 )

**Suggestion** Perhaps abstracting the `tsc` logic would allow two interfaces to be implemented: API and CLI. This new layer could be labeled "build".

<details>
<summary>Speculative API sample</summary>
<p>

``` typescript
import { createProject, createProgramFromProject, Project, DEFAULT_EXCLUDE } from '@typescript/build'

function tsConfigInterceptor (tsconfig: any) {
  return {
    ...tsconfig,
    exclude: ['lib', DEFAULT_EXCLUDE].concat(tsconfig.exclude ? tsconfig.exclude : [])
  }
}

const project: Project = createProject(process.cwd(), tsConfigInterceptor)
const program = createProgramFromProject(project)
program.emit()
```

</p>
</details>

<details>
<summary>New definitions</summary>
<p>

``` typescript

export type TsConfigInterceptor = (tsconfig: any)  => any

export const DEFAULT_EXCLUDE = Symbol('DEFAULT_EXCLUDE')

/**
* @param tsconfigPath Root dir where tsconfig.json exists or tsconfig file name
* @param [interceptor] A callback that received the object deserialized from tsconfig 
* file and returns a new one
*/
export function createProject(tsconfigPath: string, interceptor?: TsConfigInterceptor): Project {
  // ...
}

/**
* @param project The project from which a program shall be created
*/
export function createProgramFromProject (project: Project): Program {
  // ...
}
```

</p>
</details>

**Comment by mhegazy** [comment]
> Although the compiler API is public, the project logic for file resolution isn't (i.e. : how the rootFileNames are resolved before passed to createProgram).

All the tsconfig.json parsing function are public.. please see:
* [`findConfigFile`](https://github.com/Microsoft/TypeScript/blob/e934c305136ac3b8a980bfa089e18b301ce999e4/lib/typescript.d.ts#L3654) to locate an applicable tsconfig.json file
* [`parseJsonText`](https://github.com/Microsoft/TypeScript/blob/e934c305136ac3b8a980bfa089e18b301ce999e4/lib/typescript.d.ts#L3131) to parse the text into a JsonSourceFile
* [`parseJsonSourceFileConfigFileContent`](https://github.com/Microsoft/TypeScript/blob/e934c305136ac3b8a980bfa089e18b301ce999e4/lib/typescript.d.ts#L3724) to parse a json file and pass a set of overrides

Here is the part of the compiler that use these functions for reference: https://github.com/Microsoft/TypeScript/blob/e934c305136ac3b8a980bfa089e18b301ce999e4/src/compiler/watch.ts#L65-L91
