### ISSUE TITLE
Is there a way to approach Type Lamdas?

### ISSUE THREAD

**Issue by Brooooooklyn** [Microsoft/TypeScript#20269]
I have a function with Generic types and I want transfer it into another function with the same Generic types:

```ts
class Module {
  foo<T>(action$: Observable<T>): Observable<R>
  bar<T>(action$: Observable<T>): Observable<R>
}

interface ModuleActionProps<M extends Module> {
  [key in keyof M]: (payload T): R // need something here transform <T>(action$: Observable<T>): Observable<R> to (payload: T): R to ensure T and R is same here
}
```

**Comment by gcnew** [comment]
Do you mean the same _generic container_ type? If that's the case #1213 is tracking adding Higher Kinded Types.

E.g. someting like
```ts
interface ModuleActionProps<M extends Module, C> {
  [key in keyof M]: <T, R>(payload: C<T>): C<R> // `C` is the collection type
}
```

**Comment by Brooooooklyn** [comment]
uh... I don't know how to describe what I want in terms. 

I think this approach  could describe what I need:

```ts
type GetGenericType1<F extends <T, R>(action$: Observable<T>): Observable<R>> = T
```
```ts
type GetGenericType2<F extends <_, R>(action$: Observable<T>): Observable<R>> = R
```

```ts
interface ModuleActionProps<M extends Module, C> {
  [key in keyof M]: (payload: GetGenericType1<M[key]>):  GetGenericType2<M[key]> 
}
```

**Comment by Brooooooklyn** [comment]
maybe this question could be describe as [Type Lambdas](https://underscore.io/blog/posts/2016/12/05/type-lambdas.html)

**Comment by gcnew** [comment]
Take a look at #14400 and #6606. These suggestions propose type-first and expression-first type level application.

**Comment by mhegazy** [comment]
I think this should be covered by https://github.com/Microsoft/TypeScript/pull/21316

**Comment by tycho01** [comment]
6606 version: express type lambda `T => T` as `<T>(v: T) => T`.
