### ISSUE TITLE
Exporting imported types as a namespace

### ISSUE THREAD

**Issue by ORESoftware** [Microsoft/TypeScript#20273]
This question is a bit tricky and I fear I won't get an answer on StackOverflow:

the question is here:
https://stackoverflow.com/questions/47500855/exporting-imports-as-a-namespace-with-typescript

Essentially I want to group together various types from other files into one namespace X. So the types are not declared in namespace X, but they are later grouped into namespace X after the fact. Hopefully that makes sense.

A simple scenario would look like:

```typescript
import {p} from 'q';
import {foo} from 'bar';
import {zim} from 'zoom';

export namespace X {
    export p;             //  this syntax is not real, don't know what the right 
    export foo;           //  syntax is in actuality
    export zim;
}
```

we can sort of do this with a const:

```typescript
export const X = {
  p,
  foo,
  zim
}
```

but the problem is, for interfaces, I get the error:

> only refers to a type, but is being used as a value here.

**Comment by ORESoftware** [comment]
I found a related issue - https://github.com/Microsoft/TypeScript/issues/4529

Not sure if that's the most recent on this.

**Comment by poseidonCore** [comment]
You  can often get around this with notion like this:
```
import {p as _p} from 'q';
import {foo as _foo} from 'bar';
import {zim as _zim} from 'zoom';

export namespace X {
    export import p = _p;  
    export import foo = _foo;
    export import zim = _zim;
}
```

or

```
import * as Q from 'q';
import * as Bar from 'bar';
import * as Zoom from 'zoom';

export namespace X {
    export import p = Q.p;  
    export import foo = Bar.foo;
    export import zim = Zoom.zim;
}
```

**Comment by ORESoftware** [comment]
thanks yeah I get that error though "using as value, but only refers to a type", so I have to use the solution/answer that's in the StackOverflow link at the top.

**Comment by poseidonCore** [comment]
The notation that I used works for me with interfaces/types too.

Example

TestInterfaces.ts
```
export interface I {a:number};
export type T = number|string;
```

TestLibrary.ts
```
import * as TestInterfaces from "./TestInterfaces";

export namespace X {
	export import I = TestInterfaces.I;
	export import T = TestInterfaces.T;
}
```
 The problem exists if you try to do an aliased/selective import. The following will generate the error that you cite:

TestLibrary.ts
```
import {I as I2} from "./TestInterfaces";
import {T as T2} from "./TestInterfaces";

export namespace X2 {
	export import I = I2;
	export import T = T2;
}
```
An there is no pretty way to bundle these aliased interfaces/types unless you do something cumbersome like this:

TestLibrary.ts
```
import {I as I2} from "./TestInterfaces";
import {T as T2} from "./TestInterfaces";

export namespace X3 {
	export interface I extends I2 {};
	export type IAsType = I2;
	export type T = T2;
}
```

I agree that just having a convenient re-export notation like you have stated would be optimum.

**Comment by poseidonCore** [comment]
I also meant to say, if you want to keep the convenience of `export const` for re-exported objects/values, you can still conflate the namespace X after it with re-exported types/interfaces:

```
export const X = {
  p,
  foo,
  zim
}

export namespace X {
    export import someType = Q.someType;  
    export import SomeInterface = Bar.SomeInterface;
}
```

But it's still not pretty.

**Comment by ORESoftware** [comment]
I solved this problem with the accepted answer to this question:
https://stackoverflow.com/questions/47500855/exporting-imports-as-a-namespace-with-typescript
