### ISSUE TITLE
Feature request - Make a parameter required for callback function

### ISSUE THREAD

**Issue by ORESoftware** [Microsoft/TypeScript#20274]
This video shows the problem:

https://www.useloom.com/share/1a0f1e84083049ff8f745a3a1f17ac03

basically I have this

```js
v.run =  t => { return t.foo()};

run(() => {   
    //  this compiles
});

run(t => {   
    //  but I want to make the t parameter required!
});
```

the "plain" function satisfies the typings, but I want to make the parameter required, not optional. I can't really explain but it should be clear from the (rambling) video. Thanks.

**Comment by mhegazy** [comment]
have no parameters is semantically equivalent to having a parameter and ignoring its value at runtime. the later is not an indication of invalid code, and so is the earlier. a canonical example here is `map`.. most users never specify the second or third arguments. the caller has to always provide them just the same.

**Comment by ORESoftware** [comment]
Totally disagree on this one.

`Array.prototype.map = (x: Function, y?: thisArg)`

it does *not* look like this:

`Array.prototype.map = (x?: Function, y?: thisArg)`

if you don't pass the first argument, you are f*cked, because a `TypeError` is coming your way.

it is VERY important to tell the user that the first argument is required. Omitting an argument is a failure at runtime!!

**Comment by mhegazy** [comment]
```ts
run(function(t){
   // forget to use t
});
```
and 
```ts
run(function(){

});
```

are identification.. so you can tell them to make sure to use the argument in the docs  i guess..

**Comment by gcnew** [comment]
It would be more helpful if you post a snippet displaying the issue. The way I see it, the only code that needs such behaviour are functions that inspect `function.length` or do `toString()` hacks. Honestly, both of these are questionable practices.

**Comment by ORESoftware** [comment]
@gcnew if you use 

`[].map()`

you are going to get a TypeError because you failed to pass it a function

same with my code (I just improved it)

if you fail to pass `t`, then you will get a TypeError because t.foo() will get called, and t will be undefined.

This is the simplest stuff. How can we guarantee runtime safety if this is what we have?

**Comment by ORESoftware** [comment]
Ultimately this is the difference between arguments and parameters.

``` js
// here are arguments
foo(a,b,c);      // a,b,c are arguments

// here are parameters
t.foo = function(a,b,c){   // a, b, c are parameters

};
```

at least that's the nomenclature that I currently adhere to lol

so I want to make _parameters_ to be forced to be in place

**Comment by RyanCavanaugh** [comment]
It's in the FAQ and this has been covered many many times before. See #17868 for a recent recitation of this debate.

**Comment by ORESoftware** [comment]
@RyanCavanaugh  re: https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-functions-with-fewer-parameters-assignable-to-functions-that-take-more-parameters

I'd like see some option we can use to make functions with fewer parameters not assignable to functions that take more parameters

is that possible? A flag in tsconfig.json? dunno

**Comment by ORESoftware** [comment]
So it's working here:

![screenshot 2017-12-03 16 24 50](https://user-images.githubusercontent.com/11139560/33531766-9974c6fa-d846-11e7-9f59-80c37283ccef.png)

so I wonder why in my example it wasn't working? dunno
