### ISSUE TITLE
Find all refs/rename for mapped type symbols via Record

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/TypeScript#20272]
**TypeScript Version:**  2.6.1.

**Code**

Renaming `a` should rename both instances of `a` `T.a` and `O.a`, but it doesn't.

```ts
{
  type T = { a: number, b: string };
  type O = Record<keyof T, {}>;
  var t: T = { a: 1, b: "s" };
  var o: O = { a: 3 };
}
```

If we replace `Record` with its underlying implementation, renaming does work:

``` ts
{
  type T = { a: number, b: string };
  type O = { [key in keyof T]: {} };
  var t: T = { a: 1, b: "s" };
  var o: O = { a: 3 };
}
```

Related https://github.com/Microsoft/TypeScript/issues/12450

**Comment by mhegazy** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/11997

**Comment by OliverJAsh** [comment]
After reading that issue, I don't understand why this works when using mapped types and `keyof` directly, but not via the `Record` type alias which does exactly the same thing under the hood. 🤔

**Comment by OliverJAsh** [comment]
To re-iterate:

``` ts
// Renaming does work across mapped types
{
  type T = { a: number, b: string };
  type O = { [key in keyof T]: {} };
  var t: T = { a: 1, b: "s" };
  var o: O = { a: 3, b: 4 };
}
// Renaming does not work across mapped types
{
  type T = { a: number, b: string };
  type O = Record<keyof T, {}>;
  var t: T = { a: 1, b: "s" };
  var o: O = { a: 3, b: 4 };
}
// Renaming does not work across mapped types
{
  type T = { a: number, b: string };
  type MyRecord<T extends string, V> = { [key in T]: V }
  type O = MyRecord<keyof T, {}>;
  var t: T = { a: 1, b: "s" };
  var o: O = { a: 3, b: 4 };
}
```

**Comment by OliverJAsh** [comment]
@mhegazy Hey! Do you have any ideas why this issue appears to only occur when using `Record`, but not when using mapped types and `keyof` directly? See my example in the comment above.
