### ISSUE TITLE
TS plugins from local project not found in VS Code

### ISSUE THREAD

**Issue by calebegg** [Microsoft/TypeScript#20289]
As far as I can tell, this is basically the same bug as #15822, except in VS Code.

I tried following the steps in [the plugin guide](https://github.com/Microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin), but I get this error:

```
Info 16   [17:47:16.861] Failed to load module 'tscplugin': Error: Could not
resolve JS module 'sample-ts-plugin' starting at '/Applications/Visual Studio
Code.app/Contents/Resources/app/extensions/node_modules/node_modules'. Looked
in:
```

Followed by a long list of paths all starting with `/Applications/Visual Studio Code.app` (except the last few, like `/node_modules/sample-ts-plugin`)

**Comment by RyanCavanaugh** [comment]
Are you using the workspace version of TypeScript when this happens? In VS Code, plugins aren't loaded from the project folder unless you're also using the tsserver from the project folder.

To change, run the "TypeScript: Select TypeScript Version" and choose "Use Workspace Version", or click the version number between "TypeScript" and 😃 in the lower-right corner.

**Comment by calebegg** [comment]
Aha, I see. That would probably be useful to mention in the guide. I didn't even know that setting existed.

I have a PR now to add to the guide the fact that the plugin name can also be a relative path, which is what I'll probably do anyway since I'd like this to just work without having to tell peers to click around in editor settings.

**Comment by calebegg** [comment]
Added some better advice to my PR for the wiki.
