### ISSUE TITLE
Error with strictNullChecks when destructuring and renaming

### ISSUE THREAD

**Issue by erikbrinkman** [microsoft/TypeScript#20287]
**TypeScript Version:** 2.7.0-dev.20171126 and 2.6.2

**Code**
Similar to #9341, when destructuring and renaming, the bug resurfaces.

```ts
const a: { x?: number; } = { };
let y: number;
({ x:y = 1 } = a); // error TS2322: Type 'number | undefined' is not assignable to type 'number'.
```
```ts
const a: { x?: number; } = { };
let { x = 1 } = a; 
let y: number = x; // ok, x has type 'number'
```

**Expected behavior:**
No error

**Actual behavior:**
test.ts(3,6): error TS2322: Type 'number | undefined' is not assignable to type 'number'.
  Type 'undefined' is not assignable to type 'number'.

**Comment by jakebailey** [comment]
This was just recently fixed in 4.8 by #41042. I won't add a test; the one in the PR is effectively identical.
