### ISSUE TITLE
Type definition of CustomEvent constructor needs parameter(s).

### ISSUE THREAD

**Issue by takeohman** [Microsoft/TypeScript#2029]
Type definition of CustomEvent constructor needs at least one parameter.
(The constructor of Event class also needs one parameter, actually.)

Since the current definition has no parameter, I encountered an error when I run a generated JS code by 
Jasmine with node.

Following links are about CustomEvent class .
https://dom.spec.whatwg.org/#interface-customevent
https://developer.mozilla.org/en/docs/Web/API/CustomEvent

http://html5index.org/DOM%20-%20EventInit.html
http://html5index.org/DOM%20-%20CustomEventInit.html

I wrongly send a pull request #2007 on this issue.
Sorry about that.

**Comment by gdcohan** [comment]
It looks like the `Event` constructor has the same issue--should I file a separate ticket on that?

**Comment by mhegazy** [comment]
@zhanbos is working on an updated library typings. I believe this should be handled by his change. so stay tuned.

**Comment by mhegazy** [comment]
@zhanbos is working on an updated library typings. I believe this should be handled by his change. so stay tuned.

**Comment by gdcohan** [comment]
great--thanks!

**Comment by NekR** [comment]
Is it in 1.5 alpha already? Because I cannot instance CustomEvent or even Event, this does not works:
```javascript
new CustomEvent('test');
```

**Comment by mhegazy** [comment]
This was not in 1.5-alpha but should be in the next release. you can find the updated lib.d.ts in https://github.com/Microsoft/TypeScript/blob/release-1.5/bin/lib.dom.d.ts

**Comment by NekR** [comment]
Yep, thank you! I just wondered if it was already in alpha.

**Comment by NekR** [comment]
@mhegazy 

Hmm.. just updated to beta version now I cannot use ```DateView``` or invoke ```initCustomEvent``` on ```CustomEvent``` because it says what it's just ```Event```. I know I can download all these .d.ts files manually, but this does not seems right anyway.

**Comment by mhegazy** [comment]
@NekR sorry about that. The issue is fixed in master, but did not make it in time for the beta. see #2953 for more details. it should be fixed in the next release. As a work around for now, you can copy the definitions of DataView from https://github.com/Microsoft/TypeScript/blob/master/src/lib/extensions.d.ts#L48 locally.

**Comment by NekR** [comment]
@mhegazy I will copy it, thanks! But what about ```initCustomEvent```, is it fixed in master? I mean, for now of course I will use ```CustomEvent``` since it's now exists with correct definition, but there are environments which do not supports ```CustomEvent``` it requires ```initCustomEvent``` to be used.

**Comment by mhegazy** [comment]
I am not sure i understand the issue with CustomEvent, this works file for me:
```ts
var c: CustomEvent;
c.initCustomEvent("custom", true, false, undefined);
```

**Comment by NekR** [comment]
This:
```typescript
var event = document.createEvent('CustomEvent');
event.initCustomEvent('test', true, true, void 0);
this.node.dispatchEvent(event);
```
produces this error:
```error TS2339: Property 'initCustomEvent' does not exist on type 'Event'.```

This:
```typescript
var event:CustomEvent = document.createEvent('CustomEvent');
event.initCustomEvent('test', true, true, void 0);
this.node.dispatchEvent(event);
```
produces this error:
```error TS2322: Type 'Event' is not assignable to type 'CustomEvent'.
  Property 'detail' is missing in type 'Event'.```

And only casting works:
```typescript
var event = <CustomEvent>document.createEvent('CustomEvent');
event.initCustomEvent('test', true, true, void 0);
this.node.dispatchEvent(event);
```

**Comment by mhegazy** [comment]
Thanks @NekR. @zhengbli is fixing this now. we should have a working lib.d.ts for you to try soon. I have logged a different issue for is under #2975.
