### ISSUE TITLE
noImplicitReturns misidentifies generator return as function return when strictNullChecks is false

### ISSUE THREAD

**Issue by trxcllnt** [Microsoft/TypeScript#20299]
**TypeScript Version:** 2.6.1 -  2.7.0-dev.20171128

**Code:**
```ts
// index.ts
function* testGenerator() {
    if (Math.random() > 0.5) {
        return;
    }
    yield 'hello';
}

/* tsconfig.json
{
    "files": ["index.ts"],
    "compilerOptions": {
        "lib": ["esnext"], "target": "ESNEXT", "module": "es2015",
        "strictNullChecks": true,
        "noImplicitReturns": true
    }
}
*/
```

**Expected behavior:**

No errors due to the generator's early `return`, regardless of whether `strictNullChecks` is true or false.

**Actual behavior:**

* No errors when `strictNullChecks` is _true_
* The following error when `strictNullChecks` is _false_:
  ```index.ts(3,9): error TS7030: Not all code paths return a value.```

**Comment by mhegazy** [comment]
PRs welcomed!

**Comment by mhegazy** [comment]
thanks @Kingwl !

**Comment by trxcllnt** [comment]
@mhegazy @Kingwl thanks! I haven't tested, but this issue may affect async generators also. If so, would the fix in the PR will also fix them?

**Comment by Kingwl** [comment]
@trxcllnt sure
