### ISSUE TITLE
Enable `jake runtests t=` to match on unit test filenames

### ISSUE THREAD

**Issue by aozgaa** [microsoft/TypeScript#20290]
For instance
```
jake runtests t=tsserverProjectSystem
```
should run all tests from `src/harness/unittests/tsserverProjectSystem.ts`.

For unit tests, we can match on the description of the unit test.

We currently enable the matching above in unit-test files by prefixing the description of each unit test in that file, but without a consistent convention. For example, in [`tscWatchMode.ts`](https://github.com/Microsoft/TypeScript/blob/e934c305136ac3b8a980bfa089e18b301ce999e4/src/harness/unittests/tscWatchMode.ts#L169), each describe clause is prefixed with `"tsc-watch ... ` whereas smaller test files such as [`builder.ts`](https://github.com/Microsoft/TypeScript/blob/e934c305136ac3b8a980bfa089e18b301ce999e4/src/harness/unittests/builder.ts#L4) have one describe clause for all the tests in that file. Others, such as the `tsserverProjectSystem.ts`, don't have a common prefix at all.

Question: would it make sense to wrap all unit test files in an outermost "describe" with the filename at the root, or should we introduce some other mechanism to run unit tests only from a given file?

**Comment by RyanCavanaugh** [comment]
jake!
