### ISSUE TITLE
No autoimports after upgrading to TS 2.6.2

### ISSUE THREAD

**Issue by asvetliakov** [Microsoft/TypeScript#20304]
**TypeScript Version:**  2.6.2
**Code**

Before (2.6.1):
![screen shot 2017-11-28 at 19 48 52](https://user-images.githubusercontent.com/8881674/33338145-6e7bfa7e-d475-11e7-828b-8aba7582e875.png)

After (2.6.2, ```typescript@next```):
![screen shot 2017-11-28 at 19 49 48](https://user-images.githubusercontent.com/8881674/33338152-72f3a002-d475-11e7-8672-f485c768b42e.png)
(Only global completions shown, no external libraries import, no local project files imports)

The import codefix still works with 2.6.2. I've pretty large monorepo with multiple tsconfig and tsconfig paths. I'll try to get the repro, but any suggestions where should i start?

**Comment by asvetliakov** [comment]
Additional information:
vscode 1.18.1
macOS 10.13.1

If i build local TS version from tags/v2.6.2 and point tssdk in vscode to it - it works as expected.
If i point vscode to installed TS 2.6.2 in local node_modules - it doesn't work

**Comment by andy-ms** [comment]
This may have to do with whether you've visited those files yet -- try adding one import manually and see if other imports come up as fixes.

**Comment by asvetliakov** [comment]
@andy-ms Nope, it doesn't work even for additional imports in already imported file.

**Comment by asvetliakov** [comment]
Found the problem:
```
        "plugins": [
            {
                "name": "typescript-styled-plugin",
                "tags": [
                    "styled",
                    "css",
                    "extend",
                    "keyframes",
                    "injectGlobal",
                    "breakpoints"
                ]
            }
        ],
```
ping @mjbvz

**Comment by asvetliakov** [comment]
Sorry for noise

**Comment by andy-ms** [comment]
If you file an issue on vscode could you link to this one for reference?
