### ISSUE TITLE
TypeScript only picks the first type in a heterogenous array if the types in the array are unused inside themselves

### ISSUE THREAD

**Issue by michael8090** [Microsoft/TypeScript#20300]
**TypeScript Version:**  2.5.2 to 2.6.1

**Code**

```ts
interface D<T> {
    data: T;
}

interface D1<T> {
}

function make<T>() {
    return 1 as any as T;
}

// the type of a is (D<string> | D<number>)[], which is correct
const a = [make<D<string>>(), make<D<number>>()];
// the type of b is D1<string>[], which is incorrect
const b = [make<D1<string>>(), make<D1<number>>()];
```

**Expected behavior:**
the type of `b` should be `(D1<string> | D1<number>)[]`
**Actual behavior:**
the type of `b` is `D1<string>[]`

**Comment by mhegazy** [comment]
Please see https://github.com/Microsoft/TypeScript/wiki/FAQ#why-is-astring-assignable-to-anumber-for-interface-at-- and https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-all-types-assignable-to-empty-interfaces
