### ISSUE TITLE
Fix all in file for import fix

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#20315]
Issue tracking #14549 for the import fix case. This will be more difficult than others because we'll need to add code to keep track of the imports we're *about* to add so they can be combined.

**Comment by robyoder** [comment]
@andy-ms, in the description for PR #20338 you said that it "Does not fix" this issue, but GH only reads the `fix [issue]` piece of that and auto-closed this. Should this still be open?

**Comment by andy-ms** [comment]
d'oh, thanks.
