### ISSUE TITLE
AMD modules won't include .js imports in the bundle

### ISSUE THREAD

**Issue by arielweinberger** [Microsoft/TypeScript#20317]
**TypeScript Version:**  2.6.2

**Code**

**tsconfig.json:**
```ts
{
    "compilerOptions": {
        "module": "amd",
        "baseUrl": "./",
        "outFile": "output.js",
        "lib": ["es5", "es6", "es7", "dom"],
        "target": "es2015",
        "allowJs": true
    },
    "files": [
        "./index.ts"
    ]
}
```
**Application files:**
```ts
// FILE: ImportedClass.ts
// If you look into the rxjs node module, you will see that "Subject" is actually a .js file, hence rxjs/Subject.js is being imported.
import { Subject } from 'rxjs/Subject';

export class ImportedClass{
    ...
}

// FILE: index.ts
import { ImportedClass } from './ImportedClass.ts';
...
```

**Expected behavior:**
`rxjs/Subject` (a .js file if I understand correctly) will be present in the output file.

**Actual behavior:**
The imported `rxjs/Subject` file is not included in the bundle.

**However,** if instead I import `rxjs/src/Subject` (a .ts file), **it is present in the bundle**.

---

Either this is a bug, by design or there is some option that I am missing.

**Comment by mhegazy** [comment]
Files imported from `node_modules` are considered external code and not included with `allowjs`. that said; i do not think you want to check and transpile rxjs on every compile of your code, given that the compiler does not do any optimization/tree shaking for you.

**Comment by arielweinberger** [comment]
In my specific use case I have to do that. I am developing on an external platform that uses v8, and since it's running on clients' machines, my only way to import moduels is using SystemJS (AMD modules) for security reasons implemented by the developers of that platform.

So whenever I want to use a shared module that normally would just improt `rxjs/Subject` (using CommonJS, not a problem), it will fail when I use the same shared module in my small project that uses AMD modules.

So whether I want it or not, not really a problem. The question is - is there a workaround for this?

Thank you very much for your response @mhegazy!

**Comment by mhegazy** [comment]
I suggest you use a bundler like browserify or webpack for that. the compiler is not meant to handle these cases.

if you really want to consume the .js files, which i strongly recommend against, you can add them explicitly to your `include`/`files`.

**Comment by arielweinberger** [comment]
I will look into Webpack/Browserify. Thank you for the advice.
