### ISSUE TITLE
Need generic type to wrap returning types of methods in interface in generic type

### ISSUE THREAD

**Issue by holiber** [Microsoft/TypeScript#20323]
I have a pretty big desktop application with API described via TypeScript interfaces and almost all API methods are synchronous. Now I have to write a remote client for this application and I want to reuse the current API for it. One problem I have - the new API should be completely asynchronous. So I thinking about some generic type like `Async<T>` that will help me to do something like that:

```ts
// this is a synchronous API interface
interface ApplicationApi {
  startApp(): void;
  readFile(fileName): string; 
}

// create an asynchronous version
type AsyncApplicationAPI = Async<ApplicationApi>
```

Now I expect that `AsyncApplicationAPI ` should be equal:

```ts
interface AsyncApplicationApi {
  startApp(): Promise<void>;
  readFile(fileName): Promise<string>; 
}
```

Is it possible to do with the current TypeScript syntax like with `Partial<T>` type?

**Comment by mhegazy** [comment]
There is not a way currently to get a hold of the return type of a function or a constructor. https://github.com/Microsoft/TypeScript/issues/6606 is the best proposal we have so far for this issue.

**Comment by holiber** [comment]
Thanks!

**Comment by gcnew** [comment]
Another option would be using Higher Kinded Types - #1213:

```ts
interface ApplicationApi< R<*> > { // R is itself generic 
  startApp(): R<void>;
  readFile(fileName): R<string>; 
}

type Id<T> = T

type SyncApplicationAPI  = ApplicationApi<Id>
type AsyncApplicationAPI = ApplicationApi<Promise>
```

**Comment by holiber** [comment]
@gcnew this is an interesting idea. Unfortunately I unable to change the original API.

**Comment by gcnew** [comment]
#1213 is not implemented yet, so it's only in the realm of possibilities.

PS: For mapping to work, you'd have to capture and spread function's parameters (#5453) in addition to its return type (#6606).
