### ISSUE TITLE
Object.entries generic definition

### ISSUE THREAD

**Issue by ccorcos** [Microsoft/TypeScript#20322]
**TypeScript Version:**  2.6.2

Currently `Object.entries` isn't well typed and doesn't account for a union of strings as the keys of an object.

```ts
 interface Object {
  entries<X extends string,Y>(o: { [key in X]: Y }): [X, Y][];
}
```

**Comment by mhegazy** [comment]
Please see https://github.com/Microsoft/TypeScript/issues/19448 and https://github.com/Microsoft/TypeScript/issues/15627 and https://github.com/Microsoft/TypeScript/pull/12253#issuecomment-263132208

**Comment by ccorcos** [comment]
Ah. Thanks
