### ISSUE TITLE
fixAddMissingMember should create a constructor if not present

### ISSUE THREAD

**Issue by andy-ms** [microsoft/TypeScript#20331]
**TypeScript Version:**  2.7.0-dev.20171129

**Code**

**a.js**
```ts
class C {
    m() {
        this.x;
    }
}
```

**Expected behavior:**

Can fix the error by creating a constructor.

**Actual behavior:**

No codefix unless I manually add a constructor.

**Comment by mhegazy** [comment]
one issue here is creating a constructor to just get the type is a bit of an overkill.. it gets more interesting when you have a base class, now you have to create a forwarding constructor, ideally with the same number and names of parameters..

one alternative here is for us to support `@property` or `@member` on a class a a source of property declaration. https://github.com/Microsoft/TypeScript/issues/15715 tracks a similar scenario

**Comment by RyanCavanaugh** [comment]
This doesn't seem to come up often
