### ISSUE TITLE
jsdoc '@param {object}' resolved to type 'any'

### ISSUE THREAD

**Issue by artin-phares** [Microsoft/TypeScript#20337]
**TypeScript Version:**  2.7.0-dev.20171129

**Code**

`test.js`:  

```js
/**
 * @param {object} nonPrimitive
 */
function test(nonPrimitive) {}

test(1)
```

`tsc --noEmit --allowJs --checkJs test.js`

**Expected behavior:**
Error `Argument of type '1' is not assignable to parameter of type 'object'`  

**Actual behavior:**  
No errors.  

Type `object` in `.ts` files resolved to non-primitive type, but in `.js` - to `any`.

**Comment by mhegazy** [comment]
This is a design limitation. in JSDoc space users tend to use lower/upper case type names for primitives interchangeably, e.g. `Number` to mean `number` and similarly `Object` `object` to mean the top type.

you can define a new type alias `type nonPrimitive = object` in a .d.ts file, and use that instead.

**Comment by artin-phares** [comment]
ok, `jsdoc` does not care about case of type names.  
Then **(a)** why not force users to use `typescript` type names, and instead guess what type they mean by eg. `Object`?  

If for some reason we should not 'force' but 'guess' types, **(b)** why not default `@param {Object}` and `@param {object}` to `typescript`'s `object` (non-primitive) instead of `any`? I doubt users mean `any` when they use `object` / `Object` in `jsdoc`.

If for some reason we cannot default to `object` (non-primitive), **(c)** is any chance `typescript` can add `nonPrimitive` as one its default type as synonym of `object`? it looks like pain to reference that `.d.ts` in each module where I want to use non-primitive type.  

If none of above works, **(d)** does `@param {Object.<string, *>}` look like valid workaround? because it seems like cheapest one.

**Comment by mhegazy** [comment]
> I doubt users mean any when they use object / Object in jsdoc.

we have done some analysis on user code in the wild. we have found that mostly users mean the non-primitive `object` in input positions, but `any` in output positions. The type system currently does not support having the same type name mean different things based on its context, so `any` seemed the most permissive. it also is inline with other behaviors in a .js file that the compiler supports.

**Comment by mhegazy** [comment]
> If none of above works, (d) does @param {Object.<string, *>} look like valid workaround? because it seems like cheapest one.

this is tracked by https://github.com/Microsoft/TypeScript/issues/14376

**Comment by artin-phares** [comment]
> so any seemed the most permissive

Ok, but you ignored point **(a)** :smile:  

Why ts should be permissive in the first place? Why not force people to make right type annotations? They use `@return {object}` and mean `any`? Then let's force them to correctly state `@return {*}`.

> this is tracked by #14376

hm, I've already tried using `@param {Object.<string, *>}` and it works for me...

**Comment by mhegazy** [comment]
> Why ts should be permissive in the first place? Why not force people to make right type annotations? They use @return {object} and mean any? Then let's force them to correctly state @return {*}.

The whole inputs for reading types from comments is to help users with JS code bases. with that in mind we started with patterns users have already in their JS files. and most JSDoc out in the wild is liberal with what `object`/`Object`/`any` means, and most of them are liberal with casing for primitive types. 

So we chose to be more helpful.

**Comment by mhegazy** [comment]
>hm, I've already tried using @param {Object.<string, *>} and it works for me...

thanks. closed #14376 as fixed.

**Comment by artin-phares** [comment]
> and most JSDoc out in the wild is liberal with what object/Object/any means, and most of them are liberal with casing for primitive types.

Ok, but I though whole point of using `typescript` is to not be liberal to type uncertainty, and punish programmer for type failures ASAP.  

In my case, I've started with `typescript` especially to feel more type confident. If I needed language to be more type permissive/liberal, I would stay with `js` without any checks.

**Comment by mhegazy** [comment]
have you considered moving all the way to .ts files?

**Comment by artin-phares** [comment]
Yeah, considered 2 years ago when was starting the project. That time `typescript` transpiler did not have support of `async/await` and it was must-have feature I could not leave without. Although it has support  of `async/await` today, I do not have enough motivation to move to `typescript` for same reasons. Moving away from mainstream transpiler `babel` means slower adoption of all the nice little ecmascript improvements. Eg. today I cannot use short format of default export `export default from '...'` in `typescript`. I really would like `typescript` build on top of `babel` - do not transpile, just check types, strip all typings and pipe further to `babel` transpiler.

**Comment by mhegazy** [comment]
Babel7 supports TS, here is a sample: https://github.com/DanielRosenwasser/babel-typescript-sample
