### ISSUE TITLE
Building when path is a symbolic link doesn't work

### ISSUE THREAD

**Issue by jhudsoncedaron** [Microsoft/TypeScript#20332]
I have C:\users\jhudson\dev -> E:\git (to get the development arena onto the mirrored drives)

**Expected behavior:**

typescript doesn't care if there's a symbolic link in the path to the current directory or not

**Actual behavior:**

The failing code was in a stock knockout pulled from node_modules.

    declare module "knockout" { export = ko; }

would complain about duplicate symbol definition. We finally got the error to duplicate in Visual studio permitting us to notice what the problem was.

It imported C:\users\jhudson\dev\<solutionname>\src\<projectname>\node_modules\@types\knockout\index.d.ts and E:\git\<solutionname>\src\<projectname>\node_modules\@types\knockout\index.d.ts

Was thinking it was a problem with Visual Studio; discovered the problem will recur if a tsc command is issued from the command line from C:\users\jhudson\dev\<solutionname>\src\<projectname> but not 
E:\git\<solutionname>\src\<projectname>.

Reproduced with tsc 2.3 and 2.5.

The bug might be the documentation; --preserveSymlinks is required if the user's home directory has been moved to another disk via symbolic link (which is the only way to get home directories off the system drive on Windows) and therefore portable build projects must be prepared to have --preserveSymlinks turned on or exhibit machine dependent build failures.

**Comment by mhegazy** [comment]
I am really unable to piece together a repro from what you describe.. not sure where symlinks fit in this whole thing.

The only thing i can think of is you already have another definition of `knockout` in your project.. it could be in a local file, or it can be you have two dependencies that have two different versions of `@types/knockout`.  if it is the earlier, then remove that file from your compilation, if its the later, install a version of `@types/knockout` in your devdependencies, and that one should take priority.

**Comment by jhudsoncedaron** [comment]
I have a symbolic link above the build root. It included the same file twice resulting in it conflicting with itself.

Changing directory to use the symbolic link target rather than the symbolic link makes the build error go away.

**Comment by mhegazy** [comment]
does `--preserveSymlinks` solves the issue?

**Comment by jhudsoncedaron** [comment]
Ah, yes it does. Documentation fail. (The docs suggest it's for dealing with symbolic links within the project root that point out of it, which is not this case)
