### ISSUE TITLE
TS5055 Error. JS file would overwrite input file

### ISSUE THREAD

**Issue by Rasit1009** [Microsoft/TypeScript#20336]
Hey everyone, 

Due to the fact that this is my first angular Project I am facing some Problems.. This error you are seeing below is driving me nuts.. None of the Solutions mentioned in similar issues seemed to work.
 I need to compile a js file, so I added "allowJS" to my tsconfig. Ever since then this error occurs. 
There is also a way to compile correctly. Every time I delete a letter, do ng serve, add the letter again, then do ng serve, the file is compiling correctly. 

The Error shown in terminal: 
![terminal_error](https://user-images.githubusercontent.com/29611057/33395548-35294278-d546-11e7-8bd8-e25fc9993d85.PNG)
My tsconfig file
![tsconfig](https://user-images.githubusercontent.com/29611057/33394806-d1e7cce0-d543-11e7-851d-095219ef2427.PNG)
the angular-cli.json file
![angular-cli](https://user-images.githubusercontent.com/29611057/33394811-d4e77f58-d543-11e7-884a-35da55512957.PNG)

I'd be thankful for help!

**Comment by mhegazy** [comment]
Do you get the same error running `tsc --project <tsconfig.json>` ? if not seems like a bug in the angular CLI.

**Comment by Rasit1009** [comment]
I do get the same error.

**Comment by mhegazy** [comment]
can you share a repro?

**Comment by Rasit1009** [comment]
https://github.com/Rasit1009/TriForce.git 

the Folder I am referring to is "Landingpage"

**Comment by Rasit1009** [comment]
[https://github.com/Rasit1009/TriForce.git](url)

the Folder I am referring to is called "Landingpage"

**Comment by Rasit1009** [comment]
@mhegazy it is located in https://github.com/Rasit1009/TriForce

The Folder I am referring to is "Landingpage"

**Comment by mhegazy** [comment]
```ts
c:\test\20336\TriForce\Landingpage>git remote -v
origin  https://github.com/Rasit1009/TriForce.git (fetch)
origin  https://github.com/Rasit1009/TriForce.git (push)

c:\test\20336\TriForce\Landingpage>git status
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working tree clean

c:\test\20336\TriForce\Landingpage>tsc --v
Version 2.7.0-dev.20171122

c:\test\20336\TriForce\Landingpage>tsc --p tsconfig.json

c:\test\20336\TriForce\Landingpage>echo %ERRORLEVEL%
0
```

**Comment by Rasit1009** [comment]
@mhegazy so what do I have to do? 

By the way, thanks for your Patience, I really am a newbie in Angular

**Comment by mhegazy** [comment]
I think this is an agluar-cli issue. consider posting this on https://github.com/angular/angular/issues instead

**Comment by Rasit1009** [comment]
okay thanks!
