### ISSUE TITLE
Add an ES2018 Target and Lib

### ISSUE THREAD

**Issue by weswigham** [Microsoft/TypeScript#20342]
This should include any features we support which are slated for the 2018 spec release (currently stage 4 proposals), or things we think are likely to be in it (ie, promising stage 3 proposals).

**Comment by mhegazy** [comment]
PRs welcomed if someone wants to get to this before @weswigham does.

**Comment by benbraou** [comment]
I will provide a pull request for this. First contribution incoming ^^

**Comment by mhegazy** [comment]
thanks @benbraou!
