### ISSUE TITLE
[typedef] File.lastModified missing.

### ISSUE THREAD

**Issue by qm3ster** [Microsoft/TypeScript#20354]
The definition of a `File` instance is missing [the `.lastModified` property](https://developer.mozilla.org/en-US/docs/Web/API/File/lastModified), and only has the [depreciated `.lastModifiedDate` property](https://developer.mozilla.org/en-US/docs/Web/API/File/lastModifiedDate) instead.
The depreciated (but at least as widely available) property is also declared as `any` rather than `Date`.

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by mhegazy** [comment]
The xml file is not always up-to-date. we have a list of additions/deletions to the file. for this issue you will need to add a new entry in https://github.com/Microsoft/TSJS-lib-generator/blob/master/inputfiles/addedTypes.json for the new property.

**Comment by qm3ster** [comment]
1) And where should it go, at the end of the file?
2) Should I also include the Date in [inputfiles/overridingTypes.json](https://github.com/Microsoft/TSJS-lib-generator/blob/master/inputfiles/overridingTypes.json) in the same PR?

**Comment by mhegazy** [comment]
> And where should it go, at the end of the file?

that is usually what we have done. 

> Should I also include the Date in inputfiles/overridingTypes.json in the same PR?

sure.

**Comment by qm3ster** [comment]
It is done.

**Comment by mhegazy** [comment]
thanks @qm3ster!
