### ISSUE TITLE
Get union of all possible return types of a function

### ISSUE THREAD

**Issue by bcherny** [Microsoft/TypeScript#20350]
For example:

```ts
type F = () => number | string
type G = returnof F // number | string
```

If there is interest, I will write up a proposal.

Note that this is distinct from https://github.com/Microsoft/TypeScript/issues/6606, which gives a return type *given parameter types*.

**Comment by mhegazy** [comment]
I think the example should be 
```ts
type F = {
    (): number;
    (): string;
}
```

**Comment by bcherny** [comment]
You're right - your example shows more clearly that we're taking the union of all return types. In this example, `returnof` both my `F` and yours should give `number | string`.

**Comment by bcherny** [comment]
This is now done with `ReturnType` in https://github.com/Microsoft/TypeScript/pull/21847.
