### ISSUE TITLE
Equivalent of Flow's $ObjMap

### ISSUE THREAD

**Issue by bcherny** [microsoft/TypeScript#20352]
https://flow.org/en/docs/types/utilities/#toc-objmap

From Flow's docs:

> `ObjMap<T, F>` takes an object type `T`, and a function type `F`, and returns the object type obtained by mapping the type of each value in the object with the provided function type `F`. In other words, `$ObjMap` will call (at the type level) the given function type `F` for every property value type in `T`, and return the resulting object type from those calls.

We could probably implement this if/once https://github.com/Microsoft/TypeScript/issues/6606 is implemented:

```ts
type ObjMap<T extends object, F extends Function> = {
  [K in T]: typeof F(T[K])
}
```

Tracking this in a separate issue in case someone searches for TypeScript's equivalent of `$ObjMap`. Feel free to close this and fold into 6606 if you prefer!

**Comment by mhegazy** [comment]
related to https://github.com/Microsoft/TypeScript/issues/6606

**Comment by RyanCavanaugh** [comment]
We can do this with `ReturnType` now (minus overloading which I think needs to just switch to conditional types at this point for good type system support)

**Comment by lazytype** [comment]
@RyanCavanaugh Can we keep https://github.com/microsoft/TypeScript/issues/40179 open for the overloading case? (preemptively asking before it's potentially closed for the same reason as this one)
