### ISSUE TITLE
Suggestion: Module code generation UMD

### ISSUE THREAD

**Issue by codler** [Microsoft/TypeScript#2036]
Add a third variant `umd` ([Universal Module Definition](https://github.com/umdjs/umd)) in module flag on compiler.

    tsc --module umd

This way you can reuse your JS code in both Nodejs and Browser without needing to compile twice (amd and commonjs) and still be able to code modular style (import/export) in TS.

**Comment by danquirk** [comment]
We would need a better understanding of how many people are using this module style before doing the work to support it. Do you have any examples of large projects using this?

**Comment by codler** [comment]
Yes, many large projects are having there own style of umd. 
Example
* [jQuery](https://github.com/jquery/jquery) 
* [LESS.js](https://github.com/less/less.js) 
* [Underscore.js](https://github.com/jashkenas/underscore) 
* [D3.js](https://github.com/mbostock/d3) 
* [Leaflet](https://github.com/Leaflet/Leaflet) 
* [Backbone.js](https://github.com/jashkenas/backbone) 
* [Knockout](https://github.com/knockout/knockout)

**Comment by coreh** [comment]
~~6to5~~ Babel also supports emitting UMD code:

https://babeljs.io/docs/usage/modules/

**Comment by fdecampredon** [comment]
note that emitting true umd is quite problematic not only you have to grasp the names of modules for the *global case* (aka `'react'` becomes `React`) but you have to changes ALL the `require` call with something like `derequire` to prevents amd loader that parse `require` from breaking.

**Comment by csnover** [comment]
> note that emitting true umd is quite problematic not only you have to grasp the names of modules for the global case (aka 'react' becomes React) but

Eh?

> you have to changes ALL the require call with something like derequire to prevents amd loader that parse require from breaking.

No, this was a bug in a very old version of the UMD wrapper code, not intrinsic to UMD.

**Comment by fdecampredon** [comment]
> Eh? Are you meaning that in order to output a global object you normally need to specify a different variable name for it?

Yup exactly UMD also manage global object so you'll have to provide the module with 2 names.

**Comment by csnover** [comment]
> Yup exactly UMD also manages global objects so you'll have to provide the module with 2 names.

Maybe TS can get away with outputting a UMD lite format that is just CJS-or-AMD, since the compiler already will not let you export external modules if you don’t specify a module format? I think that’s really what people want anyway, just something that works with a browser module loader and works with the built-in Node.js loader, so we can get away from the stupidity of having to either load an AMD loader into Node.js to load AMD-format modules, or run Browserify to mostly-load CJS-format modules in a browser, or double compilation for each platform.

**Comment by pocesar** [comment]
nice timing. I'm having to create a manual header and footer on the compiled .js file that wraps the UMD header and the factory function at the bottom. (and add a module.exports hack, setting module to commonjs)

**Comment by mhegazy** [comment]
Thanks @csnover

**Comment by bryanforbes** [comment]
Will this be available in 1.5?

**Comment by mhegazy** [comment]
This is going to be available in 1.6

**Comment by blesh** [comment]
When is 1.6 alpha/beta coming? I'd really like this feature for the redevelopment of RxJS 3...

**Comment by mhegazy** [comment]
Correction it should be available in the next public release for 1.5; you can use the latest from master or release-1.5 as well.

**Comment by blesh** [comment]
@mhegazy ... so just `---module umd` ?

**Comment by mhegazy** [comment]
yup.

**Comment by Zorgatone** [comment]
Wow I just realized I can use UMD now :smile:
