### ISSUE TITLE
Union type merging

### ISSUE THREAD

**Issue by zakjan** [Microsoft/TypeScript#20366]
**TypeScript Version:**  2.6.2

**Code**

```ts
namespace Ns {
    export type ItemType = "A" | "B";
}

namespace Ns {
    export type ItemType = "A" | "B" | "C";
}
```

Usecase: extending exported union types from 3rd-party libraries with module augumentation

**Expected behavior:**

union type declarations are merged to `type ItemType = "A" | "B" | "C"`

**Actual behavior:**

`Duplicate identifier 'ItemType'.`

**Comment by mhegazy** [comment]
Type aliases do not merge. type aliases are not really types, they are aliases. the compiler flattens their name to what they reference. and in that sense merging is not possible. consider using string enums instead.

**Comment by zakjan** [comment]
Ok, thanks, I'll ask/make PR to the library to use enums.
