### ISSUE TITLE
Incorrect variable type when it is modified in anonymous function

### ISSUE THREAD

**Issue by TPReal** [Microsoft/TypeScript#20364]
**TypeScript Version:**  2.6

**Code**

```ts
let xx: 1 | 2 = 1;
const f = () => xx = 2;
f();
let yy = xx;
yy = 2;
```

**Expected behavior:**
Should compile. `xx` might be 1 or 2 at the `let yy` line, so `yy` should be of type `1 | 2`.

**Actual behavior:**
It doesn't see that it is possible (it is actually certain here, but it's irrelevant) for `xx` to have value `2`, so `yy` gets type `1`, and the last line fails.

Another example where last line fails but should not:
```ts
let xx: string | null = null;
[1].forEach(() => xx = "a");
let yy = xx;
yy = "a";
```

**Comment by mhegazy** [comment]
Please see https://github.com/Microsoft/TypeScript/issues/16928

**Comment by TPReal** [comment]
OK, so after some time spent with TS, this might be the first thing I think is really wrong about it. I _explicitly_ tell the compiler what is the type of `xx`, and instead of believing me, it makes a guess, and the guess is plain wrong.

And I have no way to safely recover from the mistake - I could write `let yy = xx as 1 | 2`, but this is unsafe because I could as well make an obviously wrong cast and the compiler won't complain, e.g. `let yy = xx as 3`.

**Comment by RyanCavanaugh** [comment]
@TPReal 
```ts
let xx = 1 as 1 | 2;
const f = () => xx = 2;
f();
let yy = xx;
yy = 2;
```
