### ISSUE TITLE
Implicit any for empty array literal in call

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#20377]
**TypeScript Version:**  2.7.0-dev.20171130

**Code**

Compile with `--noImplicitAny` but not with `--strictNullChecks`.

```ts
declare function id<T>(value: T): T;
function f() { return []; } // Error
function g() { return id([]); } // No error?

```

**Expected behavior:**

Both are errors.

**Actual behavior:**

Only the first is an error.

**Comment by mhegazy** [comment]
this is technically by design. the array literal is contextually typed by the generic type parameter. thought we end up inferring the type from the empty array, it is still stipulated by this function that you can pass it anything..

**Comment by andy-ms** [comment]
Possibly related: #21690
