### ISSUE TITLE
Suggestion: support ||= compound assignment

### ISSUE THREAD

**Issue by Xample** [Microsoft/TypeScript#20378]
Perhaps there is a good reason for this but I never understood why the compound assignment ||= is not part of js. This would be helpful to ensure a variable to be defined.

Given:
```ts
let a = {"key":"value"}
```

This would let us write:
```ts
a.key ||= "default";
a.anotherKey ||= "anotherDefault";
```
Instead of
```ts
a.key = a.key || "default";
a.anotherKey = a.anotherKey || "anotherDefault";

```

Of course we could have used
```ts
a = {...a, key:"default", anotherKey:"anotherDefault"}
```

But as a general case, this should work on any variable
```ts
let a;
a ||= "default";
```

instead of
```ts
let a;
a = a ||"default";
```

**Comment by DanielRosenwasser** [comment]
As much as I've personally wanted this, we really can't do this without it being added to ECMAScript itself, since adding syntactic features that aren't strictly on the type side doesn't fit into [our design goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).
