### ISSUE TITLE
`got n or more` with spread arguments

### ISSUE THREAD

**Issue by falsandtru** [microsoft/TypeScript#20372]
@sandersn Provide consistent messages?

**TypeScript Version:**  master

**Code**

```ts
declare function f(): void;
f(...[]);
declare function g(): void;
declare function g(a: void): void;
g(...[]);
declare function h(a: void): void;
declare function h(a: void): void;
h(...[]);
```

**Expected behavior:**

https://github.com/Microsoft/TypeScript/issues/20097#issuecomment-345296470

**Actual behavior:**

```
$ node built/local/tsc.js index.ts
index.ts(2,1): error TS2556: Expected 0 arguments, but got 1 or more.
index.ts(5,1): error TS2556: Expected 0-1 arguments, but got 0 or more.
index.ts(8,1): error TS2556: Expected 1 arguments, but got 0 or more.
```

**Comment by jakebailey** [comment]
All of thee calls are now legal as of #52845. [Playground Link](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEAzArgOzAFwJYHtVIAoBKALngDcctgBuAKEQIDoWBtAXSPtElgRXTY88AObEylat3DQ4SNJlz4xUCVWCkK6+mJZMOXOj1n8FQ-AAsCqrdU2TaRmX3mCl8KzYf3tdK3oMaIA)
