### ISSUE TITLE
__values helper: throw error if Symbol is not defined

### ISSUE THREAD

**Issue by AnmAtAnm** [microsoft/TypeScript#20394]
**TypeScript Version:**  2.6.2

**Code**

```ts
    console.log('Starting testForTypescriptIssue()');
    // Trivial generator function.
    const generatorFn = function*() {
      yield 1;
      yield 1;
      yield 1;
      yield 1;
    };
    console.log('  Created generator function.');

    // THIS WORKS!! TESTED BACK TO ANDROID 16.
    // Construct an iterator and iterate it.
    const iterator: Iterator<number> = generatorFn();
    var i1: IteratorResult<number> = iterator.next();
    while (!i1.done) {
      sum = sum + i1.value;
      i1 = iterator.next();
    }
    console.log('  Completed first loop: sum == ' + sum);

    // THIS IS AN INFINITE LOOP ON OLDER ANDROID BROWSERS...
    // Construct an iterable and iterate it.
    const iterable: Iterable<number> = generatorFn();
    console.log('  Created Iterator')
    for (var i2 of iterable) {
      sum += i2;
      console.log('  . sum = ' + sum); // Infinite
    }
    console.log('  Completed second loop: sum == ' + sum);  // Never runs.
```

Compiled with:

```
  "compilerOptions": {
      "target": "ES5",
      "lib": [
        "ES5",
        "ES2015.Generator",
        "ES2015.Iterable"
      ],
      "downlevelIteration": true
    }
```

Results in:

```js
    console.log('Starting testForTypescriptIssue()');
    // Trivial generator function.
    var generatorFn = function () {
        return __generator(this, function (_a) {
            switch (_a.label) {
                case 0: return [4 /*yield*/, 1];
                case 1:
                    _a.sent();
                    return [4 /*yield*/, 1];
                case 2:
                    _a.sent();
                    return [4 /*yield*/, 1];
                case 3:
                    _a.sent();
                    return [4 /*yield*/, 1];
                case 4:
                    _a.sent();
                    return [2 /*return*/];
            }
        });
    };
    console.log('  Created generator function.');
    // THIS WORKS!! TESTED BACK TO ANDROID 16.
    // Construct an iterator and iterate it.
    var iterator = generatorFn();
    var i1 = iterator.next();
    while (!i1.done) {
        sum = sum + i1.value;
        i1 = iterator.next();
    }
    console.log('  Completed first loop: sum == ' + sum);
    // THIS IS AN INFINITE LOOP ON OLDER ANDROID BROWSERS...
    // Construct an iterable and iterate it.
    var iterable = generatorFn();
    console.log('  Created Iterator');
    try {
        for (var iterable_2 = __values(iterable), iterable_2_1 = iterable_2.next(); !iterable_2_1.done; iterable_2_1 = iterable_2.next()) {
            var i2 = iterable_2_1.value;
            sum += i2;
            console.log('  . sum = ' + sum); // Infinite
        }
    }
    catch (e_3_1) { e_3 = { error: e_3_1 }; }
    finally {
        try {
            if (iterable_2_1 && !iterable_2_1.done && (_a = iterable_2.return)) _a.call(iterable_2);
        }
        finally { if (e_3) throw e_3.error; }
    }
    console.log('  Completed second loop: sum == ' + sum);  // Never runs.
```

**Expected behavior:**

The code should output four dots and complete, printing the sum.

**Actual behavior:**

On desktop Chrome and Android emulators APIs 22 and above, the code works as expected. The second loop's printed sums are 5 through 8, as expected.

On APIs 21 and below (>20%), the loop will never completes. The loop's printed sums are `undefined` because `i2` (from `iterable_2_1.value`) is undefined. `iterable_2_1.done` is always false.

**Proposed solution**

`iterable_2` is assigned this function from `__values(..)`

```
function () {
  if (o && i >= o.length) o = void 0;
  return { value: o && o[i++], done: !o };
}
```

In this case, `o` is `iterable`, which is not an array and is always defined: `{ values: undefined, done: false}`. Checking `o instanceof Array` first works:

```
var __values = (this && this.__values) || function (o) {
    var m = typeof Symbol === "function" && o[Symbol.iterator], i = 0;
    if (m) return m.call(o);
    if (o instanceof Array) {
        return {
            next: function () {
                if (o && i >= o.length) o = void 0;
                return { value: o && o[i++], done: !o };
            }
        };
    }
    // .next() of the Iterator protocol
    return (typeof o.next === "function") ? o : {done: true};
};
```

**Comment by mhegazy** [comment]
The iterator interface depends on `Symbol` polyfill. The emitted code assumes the existence of one (similar to `Promise` for async..await emit).

https://github.com/zloirock/core-js would be a possible candidate

**Comment by AnmAtAnm** [comment]
My understanding is the [Iterable protocol](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#The_iterable_protocol) depends on the Symbol.  The iterator itself should not. Function generators return `IterableIterator`s, and so should act as iterators in downlevel environments without Symbol.

This is the __values(..) I see from tsc:

```ts
var __values = (this && this.__values) || function (o) {
    var m = typeof Symbol === "function" && o[Symbol.iterator], i = 0;
    if (m) return m.call(o);
    return {
        next: function () {
            if (o && i >= o.length) o = void 0;
            return { value: o && o[i++], done: !o };
        }
    };
};
```

The code after `if (m) return m.call(o);` (where m is the iterator when there is a Symbol) implies there was an intention to solve this when Symbol was not there, such as my compiled case.

The fix above the is a trivial solution, looking for the iterator's `.next()` method.

**Comment by AnmAtAnm** [comment]
Okay.  I see my mistake.

Since the generator function returns an `IterableIterator`, the solution I proposed found the Iterator protocol. However, since I was attempting to use this in a `for( .. of ..)` loop, the expectation is an Iterable and should not expect the `.next()`.

It would be great if the downlevel could rewrite a `for..of` that receives a `IterableIterator` as a valid Iterator loop.  That would be sufficient.  Of course, my solution implicitly does that, at a minor cost to all `__value(..)` calls.  There is certainly a more local solution.

**Comment by mhegazy** [comment]
chatted with @rbuckton about this today, the helper should throw an exception to let you know it expects to find Symbol but did not find it. should help users look reach the solution faster.

**Comment by AnmAtAnm** [comment]
With respect to the `__values(..)` helper, sure. That sound fine to address any misuse of `for(item of myIterator)`.

However, for the narrower case of `for(item of myIterableIterator)`, it be really really nice if the downlevel compiler would recognize the loop pattern and rewrite it as an `Iterator` loop that doesn't depend on Symbol.  As my original suggested patch demonstrates, there is no technical reason why and ES5 can't run such code.

**Comment by rbuckton** [comment]
> However, for the narrower case of `for(item of myIterableIterator)`, it be really really nice if the `downlevelIteration` mode would recognize the loop pattern and rewrite it as an `Iterator` loop that doesn't depend on Symbol.

That would depend on type-directed emit which we generally try to avoid. There's no way to know at runtime that an object that has a `next` method is actually an iterator without type information that isn't available at runtime.

**Comment by AnmAtAnm** [comment]
I don't understand what you mean by "type-directed emit". Adapting the output by the compiler's type information?

If you know it is an `IterableIterator`, such as a return value from a function generator, then don't you know it has the `.next()` method because of the Iterator half of that class? (...assuming the object wasn't manually casted by the developer, which is kind of their own fault.)

From a user/developer perspective, it seems strange to support the `function*()` syntax without the `for( .. of .. )` equivalent when the downlevel browsers are technically capable of the behavior.

**Comment by rbuckton** [comment]
I don't think this is a change we want to make. Using `--downlevelIteration` essentially requires a usable `Symbol.iterator`, either natively or through a polyfill. We previously made a change that throws an error if `Symbol.iterator` is not found, and support creating a pseudo-iterator over array-likes (such as `Array`, `arguments`, typed arrays, and strings). If we were to naively wrap any object with a `.next` and treat it as if it were an iterable, that would go against the runtime semantics of ES6 that `--downlevelIteration` is attempting to emulate.

Basing whether to change `for..of` based on the _type_ of the iterator at compile time rather than what is known about its _value_ at runtime is also a change we do not want to make, as that is what is known as "Type Directed Emit", which is something we expressly want to avoid.

Basing whether to change `for..of` based on whether we can trace the source of the iterated value to a call to a generator is prohibitively complex in anything more than the most trivial of cases, and is not likely something we will invest in.

I'm closing this issue as there is nothing further we can do here. There are already two options that address this:

1. We now throw an error if the object is not array-like and `Symbol.iterator` cannot be found.
2. This error can be overcome by using a polyfill for `Symbol.iterator` (as mentioned earlier in the thread).
