### ISSUE TITLE
Proposal: import/export all TS files from a folder matching regular expression

### ISSUE THREAD

**Issue by antoine-pous** [Microsoft/TypeScript#20392]
Currently `import` on a directory search for index.(d.)ts(x), i would like to see a new way to import files from a directory without creating a definition file.

The idea is to use a regular expression to import/export what we need from a directory with a single line.

Here is an example with a definition file.

The current way:

```typescript
export * from "./file1";
export * from "./file2";
export * from "./file3";
// ...
```

The proposed way:
```
export * from "^.\/file\d+$";
```

This approach is basic, i think we could improve it.

**Comment by andy-ms** [comment]
We won't modify the semantics of ES modules -- see the [design goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).
