### ISSUE TITLE
typescript - Compilation error -   TS2339: Property 'jsonro' does not exist on type 'void | { jsonro: any; fileData: any; }'.   Property 'jsonro' does not exist on type 'void'.

### ISSUE THREAD

**Issue by anukonatala** [Microsoft/TypeScript#20397]
downloadFile(sid: number,userid: string) {
  let p = new Promise((resolve, reject) => {

    let cryptoService = this.cryptoService;
    let xhr: XMLHttpRequest = new XMLHttpRequest();
    let restURL = this.appURL + "/download";
    let body = new URLSearchParams();
    let input = { "sid": sid,"userid": userid};

    body.set('input', JSON.stringify(input));

    xhr.responseType = "arraybuffer";

    // listen for responses
    xhr.onreadystatechange = function() {
      if (xhr.readyState === 4) {
        let jsonro = JSON.parse(xhr.getResponseHeader("jsonro"));
        let jsonroResponse = JSON.parse(jsonro.Response);
        let hash = jsonroResponse.hash;

        let isValidFile = cryptoService.compareFileHash("SHA-256", xhr.response, hash);

        let blob = new Blob([xhr.response]);
        let responseArray = { "xhrheader": xhr.getResponseHeader("jsonro"), "blob": blob };
        if (isValidFile) resolve(responseArray);
        else reject("The file is not valid.");

      }
    }

    // set XHR settings and execute
    xhr.open('POST', restURL, true);
    xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
    xhr.setRequestHeader("Cache-Control", "no-cache");
    xhr.setRequestHeader("X-Requested-With", "XMLHttpRequest");
    xhr.send(body);
  });

  // return the promise
  return p.then( resp => {

    let jsonro = resp["xhrheader"];
    if (JSON.parse(jsonro).Error == "true") {
      this.sharedService.setError(JSON.parse(jsonro).Message);
    }

    return { jsonro: resp["xhrheader"], fileData: resp["blob"]} ;
  }).catch(err => this.handleError(err));
}

**Comment by andy-ms** [comment]
I don't see that error when trying to compile this example. Could you try to get a standalone repro for this issue?
