### ISSUE TITLE
Bad type inference of function overloads

### ISSUE THREAD

**Issue by gcnew** [Microsoft/TypeScript#20396]
**TypeScript Version:**  2.7.0-dev.20171110

**Code**

```ts
interface Leaf<T> {
    kind: 'leaf',
    data: T[]
}

interface Branch<T> {
    kind: 'branch',
    data: Trie<T>[]
}

type Trie<T> = Leaf<T> | Branch<T>

function mapTrie<T, U>(
    trie: Trie<T>,
    f: {
        (x: T): U,
        (x: Trie<T>): Trie<U>
    }
): Trie<U> {
    if (trie.kind === 'leaf') {
        return {
            kind: 'leaf',
            data: trie.data.map(f) // `f` should be inferred as `(x: T) => U`
                                   // works fine with explicit type param `map<U>(f)`
        };
    }

    return {
        kind: 'branch',
        data: trie.data.map(f)
    };
}
```

**Comment by mhegazy** [comment]
Please see https://github.com/Microsoft/TypeScript/issues/20257

**Comment by gcnew** [comment]
I think this issue is not a duplicate of #20257. While the underlying reason might be the same, in #20257 there is not definite clue which overload is the expected one. In this issue, however, proper inference can be made following the types of the paramaters.

What we know:

```ts
trie.data: T[]
expected mapper parameter: (x: T) => <some B>
provided mapper argument: ((x: T) => U) & ((x: Trie<T>) => Trie<U>)
```

We are looking for a `B` which can be deduced from `f`'s signature. The following two options are present:

- `(x: T) => <some B>` ~ `(x: T) => U)`
- `(x: T) => <some B>` ~ `(x: Trie<T>) => Trie<U>`

The first option yields the correct solution `B = U`. The second one is not solvable, as `Trie<T> !== T`, so it should be discarded. What actually happens is that the second option creeps in, although it does not satisfy the first parameter's type `x: T`.

**Comment by gcnew** [comment]
@mhegazy Does my last comment change your view on this issue?

**Comment by mhegazy** [comment]
do not think so..
