### ISSUE TITLE
Suggestion: data classes for structural data with default values

### ISSUE THREAD

**Issue by Lexanius** [Microsoft/TypeScript#20391]
After asking my validation question (https://stackoverflow.com/questions/47579148/why-is-a-dynamic-object-valid-to-set-to-a-class-in-typescript) and there no cool workaround, i try to request a feature.

## Data classes:
Classes with only public properties no function and a default constructor (maybe like java beans). It sould be to improve the interfaces to define default values.

```
data class Greeter {
  e: number;

  p: boolean = true;
}
```
### Reason: 
currently is this allowed:
```
const xxx2: Greeter = { e: 1, p: true };
```
But it will be better to convert this to: 
```
const xxx2: Greeter = new Greeter();
xxx2.e = 1;
xxx2.p = true; 
//or
const xx2: Greeter = Object.setPrototypeOf({ e: 1, p: true }, Greeter.prototype);
```
Better: this should be allowed too:
```
const xxx2: Greeter = { e: 1};
```
because Greeter has the `p` as default value.

### Improvement:
The usage will be on structured data, that needs to be classes because of default values and instanceof, without creating a long constructor.

### What to do:
Create a new subtype of classes: Data Class with the `data` keyword befor `class`.
The class should only hold data and be initiated, when it will create with the values from the interfaces. Default-Values could be ignored in the given interface.

### Full example
ts:
```
data class Greeter {
  e: number;

  p: boolean = true;
}

const xxx: Greeter = { e: 1 };
```
js:
```
var Greeter = /** @class */ (function () {
    function Greeter() {
        this.p = true;
    }
    return Greeter;
}());
var xxx = new Greeter();
xxx.e = 1;
```

Tank you and have i miss something?

Richard

**Comment by jcalz** [comment]
What's wrong with giving `Greeter` a [private member](https://www.typescriptlang.org/docs/handbook/type-compatibility.html#private-and-protected-members-in-classes) so you can only create it with the constructor?  That seems like a good solution for you and doesn't begin to get into the craziness involved in introducing new keywords or emitting different classes.

**Comment by Lexanius** [comment]
**Update that the suggestion is only for full public member class**

I see i miss something, the protected and private member.  So i fixed the text ,that only public member should be in the class. It sould be a improvement for the interfaces.

**Comment by andy-ms** [comment]
We won't add new features to JavaScript like this -- we just type-check what the language already supports. See the [design goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).
