### ISSUE TITLE
Use chalk instead of colors for console printing

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Microsoft/TypeScript#20390]
https://www.npmjs.com/package/colors
https://www.npmjs.com/package/chalk

Colors modifies the string prototype, which is dangerous. Chalk does not.

**Comment by mhegazy** [comment]
We do not want to add any dependencies to the typescript pacakge

**Comment by JoshuaKGoldberg** [comment]
@mhegazy By "instead" I mean "remove the `colors` dependency and replace it with `chalk`." Do you mean you don't want to add any _new_ dependencies or just don't want the dependency graph to get bigger?

**Comment by mhegazy** [comment]
We do not use `colors` for `--pretty`, it is a dev dependency for our test runner. so not sure if that is what you meant or you meant to use color/chalk in `--pretty`.. i might have miss understood.

**Comment by JoshuaKGoldberg** [comment]
I did mean the dev dependency, yes (sorry for not being clear).

**Comment by DanielRosenwasser** [comment]
As long as it doesn't change things drastically, I think we'd take a PR on this.

**Comment by tumulr** [comment]
Can I take this one?

**Comment by JoshuaKGoldberg** [comment]
There's a PR out already :(
