### ISSUE TITLE
Document process for adding new localized strings

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Microsoft/TypeScript#20418]
_Scenario: You'd like to add a new diagnostic message in the CLI, and don't know where to start._

From existing pull requests, it looks like it's as simple as adding an entry in `diagnosticMessages.json`.
* Is that is?
* What part(s) of the build process interact with that?
* What are the guidelines for doing so?
* How do those strings become localized (are pull requests or features blocked on external localization teams, and if so how long is the ETA for localization)?

**Comment by mhegazy** [comment]
Add the message to https://github.com/Microsoft/TypeScript/blob/master/src/compiler/diagnosticMessages.json, run `jake generate-diagnostics` and use the name of the generated message, that is it.

We have a script that will send the new strings added nightly to our loc team, and they will merge in the new localized strings independently. the time depends on multiple factors, but usually within a week or two the string should be localized in all languages. but you do not need to worry about this, I can take care of that. If a message is not localized in a specific language, the text will show in English.
