### ISSUE TITLE
Doc bug: tsconfig link is broken

### ISSUE THREAD

**Issue by NT-D** [Microsoft/TypeScript#20412]
In [React & Webpack tutorial](http://www.typescriptlang.org/docs/handbook/react-&-webpack.html), there is a link to tsconfig description. It doesn't work.

```
You can learn more about tsconfig.json files here.
```

**Expected behavior:**
It routes correct page.

**Actual behavior:**
It routes [this page](http://www.typescriptlang.org/docs/tsconfig-json.html) and shows `The resource you are looking for has been removed, had its name changed, or is temporarily unavailable`.

**Comment by mhegazy** [comment]
Seems to be the same as https://github.com/Microsoft/TypeScript-Handbook/issues/601
