### ISSUE TITLE
Incorrect "setSelectionRange()" type declarations

### ISSUE THREAD

**Issue by mariusschulz** [Microsoft/TypeScript#20419]
_lib.dom.d.ts_ currently has two different type declarations for the `setSelectionRange()` API for `HTMLInputElement` and `HTMLTextAreaElement`.

For `HTMLInputElement` ([permalink](https://github.com/Microsoft/TypeScript/blob/49a48ffd4d7ed76fa4033752d1d55a1ad31ab18a/lib/lib.dom.d.ts#L6982)):

```ts
setSelectionRange(start?: number, end?: number, direction?: string): void;
```

For `HTMLTextAreaElement` ([permalink](https://github.com/Microsoft/TypeScript/blob/49a48ffd4d7ed76fa4033752d1d55a1ad31ab18a/lib/lib.dom.d.ts#L5519)):

```ts
setSelectionRange(start: number, end: number): void;
```

However, both are wrong, if I'm not mistaken. According to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/setSelectionRange), the correct type declaration would be the following:

```ts
setSelectionRange(start: number, end: number, direction?: "forward" | "backward" | "none"): void;
```

Note that neither `start` nor `end` are optional. I also added a union of string literal types to type the (optional) `direction` parameter more precisely.

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by mariusschulz** [comment]
Alright, here's the PR: https://github.com/Microsoft/TypeScript/pull/20459
