### ISSUE TITLE
JSX output doesn't sanitize for Javascript keywords

### ISSUE THREAD

**Issue by rtpg** [Microsoft/TypeScript#20417]
**TypeScript Version:**  2.6.2 (also tested in `typescript@next`)

**Code**
(I've turned on `--jsx` and `--jsxFactory` as `DOMBuilder`)
 
```ts
function DOMBuilder(elt, attrs, contents){

}

export class Foo{

    buildDOMElt(){
        return <h3 class="a">Hi there </h3>;
    }
}
```

**Expected behavior:**
for the compiled Javascript return value to look something like 

```js
        return DOMBuilder("h3", { "class": "a" }, "Hi there ");
```

**Actual behavior:**
The output of the Javascript instead uses `class` directly as the dictionary key, but this is a reserved keyword.

```js
        return DOMBuilder("h3", { class: "a" }, "Hi there ");
```

**Comment by RyanCavanaugh** [comment]
Why is this a problem? It's legal syntax.
![image](https://user-images.githubusercontent.com/6685088/33531991-e86f1172-d849-11e7-9942-efcd744843b7.png)

**Comment by rtpg** [comment]
Sorry, I might have actually been a bit zealous here. My IDE was highlighting stuff oddly and I had tried just putting in the dictionary literal and it failed.

<img width="427" alt="image" src="https://user-images.githubusercontent.com/1408472/33532909-f59f98c0-d8e0-11e7-861a-f36bfcf80d52.png">

Looking into this a bit more, this might be properly handled by everything in my toolchain except my IDE.

**Comment by RyanCavanaugh** [comment]
Common confusion -- `{ class: "a" }` is a block statement rather than an object literal expression. `({class: "a"});` parses without error

**Comment by rtpg** [comment]
thanks for the clarification on this
