### ISSUE TITLE
feat(es2018): add definitions for new array methods (flatten, flatMap)

### ISSUE THREAD

**Issue by benbraou** [Microsoft/TypeScript#20410]
Array.prototype.flatMap and Array.prototype.flatten (https://github.com/tc39/proposal-flatMap) are now at [stage 3](https://tc39.github.io/proposal-flatMap/) 

This issue is created to handle the addition of the corresponding definitions.

This has been suggested by @mhegazy https://github.com/Microsoft/TypeScript/pull/20385#issuecomment-348713869

**Comment by benbraou** [comment]
I will provide a PR for this

**Comment by benbraou** [comment]
Array.prototype.flatten and Array.prototype.flatMap will be marked for the moment as esnext and not es2018.
After TC39 January meeting, it will be clearer whether this will make it to [es2018](https://github.com/tc39/proposals/blob/master/finished-proposals.md)

**Comment by mhegazy** [comment]
thanks @benbraou!
