### ISSUE TITLE
Remove TS{####} errors from --watch CLI

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Microsoft/TypeScript#20428]
After #20416, this is what the CLI will look like (and without it, it's the same but with fewer colors):
![image](https://user-images.githubusercontent.com/3335181/33522579-bf500760-d7a4-11e7-98c1-599605203164.png)

AFAIK the error codes like `TS2322` are really only used in Visual Studio, so folks using `--watch` wouldn't need them. Can we just remove them for being visual clutter?

**Comment by mhegazy** [comment]
This debate goes back to 1.1 time-frame, (see https://github.com/Microsoft/TypeScript/pull/694). I think we have agreed to keep them for now, as useless as they may be.
