### ISSUE TITLE
Type checking bug (Type 'null' cannot be used as an index type)

### ISSUE THREAD

**Issue by mbrodersen** [Microsoft/TypeScript#20434]
**TypeScript Version:**  2.5.3

**Code**

    if(columnIndex === null) return (_:number) => null;
    
    return (rowIndex:number) => table.rows[rowIndex].rowValues[columnIndex];

**Expected behavior:**

No type errors.

**Actual behavior:**

error TS2538: Type 'null' cannot be used as an index type.

(referring to the columnIndex variable captured by the lambda expression)

**Work around:**

The type error goes away if I instead do:

return (rowIndex:number) => table.rows[rowIndex].rowValues[columnIndex as number];

However that shouldn't be necessary.

**Comment by ahejlsberg** [comment]
You didn't post a full example, but I'm assuming `columnIndex` is a mutable variable (i.e. declared with `let` or `var`). If so, the compiler doesn't consider the guard against `null` to be in effect within the arrow function (because there could have been a subsequent assignment to `columnIndex` before the arrow function is called).

It should work if you declare `columnIndex` as `const`. See #8849 and #10357.

**Comment by mbrodersen** [comment]
Thanks for the quick reply Anders. Here is the complete example:

```
export function getTableColumnLookup(column:string, table:Types.Table | null): Types.TableColumnLookup
{
    if(table === null) return (_:number) => null;
    
    let columnIndex = getTableColumnIndex(column, table);
    
    if(columnIndex === null) return (_:number) => null;
    
    return (rowIndex:number) =>
    {
        if(rowIndex < 0 || rowIndex >= table.rows.length) return null;
        
        return table.rows[rowIndex].rowValues[columnIndex];
    }
}
```
Good point about columnIndex not being const. However the type checker could ideally still infer that columnIndex can not be accessed by anything than the lambda closure (and therefor can not possible be null), given that columnIndex is a primitive type (i.e. not a reference to an object), and the lambda is in a return statement (after which columnIndex goes out of scope). So I guess this is more of a "possible improvement to the type checker" issue then :-)
