### ISSUE TITLE
Emit only filtered declaration files

### ISSUE THREAD

**Issue by donaldpipowitch** [Microsoft/TypeScript#20436]
**TypeScript Version:**  2.7.0-dev.201xxxxx

**Code**

```ts
const result = createProgram(filePaths, options).emit(
  undefined, // targetSourceFile
  undefined, // writeFile
  undefined, // cancellationToken
  true // emitOnlyDtsFiles
);
```

See [here](https://github.com/donaldpipowitch/typescript-experiments/blob/master/tsc-create-declarations/src/index.ts).

**Expected behavior:**

There is a option to filter which files will be emitted.

**Actual behavior:**

Hi! I try to emit `.d.ts` in some cases. I have an edge case where I'd like to _not_ emit certain files. But it looks like the `emitOnlyDtsFiles` is all or nothing. Is there a way to filter certain `.d.ts` files _before_ they are written to the file system? I noticed there is a fifth param `CustomTransformers`... can this be used somehow to do this? I couldn't found an actual example for this.

```ts
    const result = createProgram(filePaths, options).emit(
      undefined, // targetSourceFile
      undefined, // writeFile
      undefined, // cancellationToken
      true, // emitOnlyDtsFiles
      {
        before: [
          context => {
            // Do something with `context.onEmitNode` here?
            return function transformSourceFile(node) {
              if (node.isDeclarationFile) {
                // Filter something here?
                return node;
              } else {
                return node;
              }
            };
          }
        ]
      }
    );
```

**Comment by mhegazy** [comment]
> files before they are written to the file system?

the compilerHost is what writes to disk. you can in your compilerHost decide what to write and what not to write.

> I noticed there is a fifth param CustomTransformers... can this be used somehow to do this? 

no. these are transforms

> is all or nothing. Is there a way to filter certain .d.ts `targetSourceFile` and you will get the `.d.ts` file that matches it. 

The emit is keyed off the source file. pass in

**Comment by donaldpipowitch** [comment]
Thank you @mhegazy for the hint. So this basically seems to work:

```ts
const host = createCompilerHost(options);
const { writeFile } = host;
host.writeFile = (
  fileName,
  data,
  writeByteOrderMark,
  onError,
  sourceFiles
) => {
  if (fileName.endsWith('unit.d.ts')) return;
  writeFile(fileName, data, writeByteOrderMark, onError, sourceFiles);
};
const result = createProgram(filePaths, options, host).emit(
  undefined, // targetSourceFile
  undefined, // writeFile
  undefined, // cancellationToken
  true // emitOnlyDtsFiles
);
```
