### ISSUE TITLE
type check for interface implementation is not strict enough

### ISSUE THREAD

**Issue by tommytroylin** [Microsoft/TypeScript#20439]
**TypeScript Version:**  2.7.0-dev.20171203

**Code**
compilerOptions `--strict`
part1
```ts
interface Foo {
  any(foo: string,  bar: string): void;
}

class Bar implements Foo {
  any(foo: string) {
    return foo;
  }
}
```
part2
```ts
interface Foo {
  any(foo: string): void;
}

class Bar implements Foo {
  any(foo: string, bar: string) {
    return foo + bar;
  }
}
```

**Expected behavior:**
both parts throw incompatible parameters for function `any`

**Actual behavior:**
part1 no error has been thrown
part2 throws the expected error

**Comment by RyanCavanaugh** [comment]
Duplicate #13463 and others, or see the FAQ https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-functions-with-fewer-parameters-assignable-to-functions-that-take-more-parameters
