### ISSUE TITLE
Array.from does not accept Iterable<T>|ArrayLike<T> argument

### ISSUE THREAD

**Issue by Kovensky** [Microsoft/TypeScript#20432]
**TypeScript Version:**  2.6.2

**Code**

```ts
function takeN<T> (n: number, input: Iterable<T>|ArrayLike<T>): [T[], T[]] {
  const array = Array.from(input)
  return [array.splice(0, n), array]
}

function takeNv2<T> (n: number, input: Iterable<T>|ArrayLike<T>): [T[], T[]] {
  const array = isIterable(input) ? Array.from(input) : Array.from(input)
  return [array.splice(0, n), array]

  function isIterable(arg: any): arg is Iterable<any> {
    return Symbol.iterator in arg
  }
}
```

[Playground link](https://www.typescriptlang.org/play/#src=function%20takeN%3CT%3E%20(n%3A%20number%2C%20input%3A%20Iterable%3CT%3E%7CArrayLike%3CT%3E)%3A%20%5BT%5B%5D%2C%20T%5B%5D%5D%20%7B%0D%0A%20%20const%20array%20%3D%20Array.from(input)%0D%0A%20%20return%20%5Barray.splice(0%2C%20n)%2C%20array%5D%0D%0A%7D%0D%0A%0D%0Afunction%20takeNv2%3CT%3E%20(n%3A%20number%2C%20input%3A%20Iterable%3CT%3E%7CArrayLike%3CT%3E)%3A%20%5BT%5B%5D%2C%20T%5B%5D%5D%20%7B%0D%0A%20%20const%20array%20%3D%20isIterable(input)%20%3F%20Array.from(input)%20%3A%20Array.from(input)%0D%0A%20%20return%20%5Barray.splice(0%2C%20n)%2C%20array%5D%0D%0A%0D%0A%20%20function%20isIterable(arg%3A%20any)%3A%20arg%20is%20Iterable%3Cany%3E%20%7B%0D%0A%20%20%20%20return%20Symbol.iterator%20in%20arg%0D%0A%20%20%7D%0D%0A%7D%0D%0A)

**Expected behavior:**

`takeN` to work

**Actual behavior:**

`takeN` raises an error on `Array.from`, because TypeScript does not accept that the input matches more than one overload.

This is either a compiler bug, or the declaration for `Array.from` needs an overload that accepts either.

**Comment by mhegazy** [comment]
The root cause is https://github.com/Microsoft/TypeScript/issues/14107.
We can work around this by adding an overload for `Array.from` to accept `ArrayLike<T> | Iterable<T>` instead of just `Iterable<T>`.

A similar bug report was https://github.com/Microsoft/TypeScript/issues/20215 for `Date` constructor.

**Comment by DanielRosenwasser** [comment]
Thanks @Kovensky!
