### ISSUE TITLE
Navigator.vibrate is not recognized by Lib.d.ts

### ISSUE THREAD

**Issue by tomy2105** [Microsoft/TypeScript#2044]
It is supported by many browsers (mobile) so should be included.
Specification can be found at: http://www.w3.org/TR/vibration/

**Comment by danquirk** [comment]
May need a new sub-part for lib.d.ts for stuff like this

**Comment by tomy2105** [comment]
I agree, did you mean something like... ?

interface Navigator extends ... (lots of others) ... NavigatorVibrate {
}

interface NavigatorVibrate {
     vibrate(pattern: number | number[]): boolean;
}
