### ISSUE TITLE
`new` instantiation with union type does not create a union typed object

### ISSUE THREAD

**Issue by andnp** [Microsoft/TypeScript#20443]
**TypeScript Version:**  2.6.2

**Code**

```ts
class c1 { }
class c2 { }

const e = {
    thing1: c1,
    thing2: c2
};

type keys = keyof typeof e;

// get a key with the type widened (in our case we don't know the string until runtime)
const key: keys = 'thing2' as keys;

// get the constructor
const cl = e[key];

// instantiate the class, should be type c1 | c2
const m = new cl();
```

typescript playground [here](https://www.typescriptlang.org/play/#src=class%20c1%20%7B%20%7D%0D%0Aclass%20c2%20%7B%20%7D%0D%0A%0D%0Aconst%20e%20%3D%20%7B%0D%0A%20%20%20%20t1%3A%20c1%2C%0D%0A%20%20%20%20t2%3A%20c2%0D%0A%7D%3B%0D%0A%0D%0Atype%20keys%20%3D%20keyof%20typeof%20e%3B%0D%0Aconst%20k%3A%20keys%20%3D%20't2'%20as%20keys%3B%0D%0A%0D%0Aconst%20cl%20%3D%20e%5Bk%5D%3B%0D%0Aconst%20m%20%3D%20new%20cl()%3B%0D%0A), had to shorten some strings to share it.

**Expected behavior:**

```ts
const m = new cl(); // => c1 | c2
```

**Actual behavior:**

```ts
const m = new cl(); // => c1
```

It appears that the types for `new` are `() => c1` here, where they should be the union: `() => c1 | c2`.

**Comment by andy-ms** [comment]
This seems to be fixed in `typescript@next`.

**Comment by andnp** [comment]
Merp, yup I agree. Apparently I had my VSCode typescript server not set up correctly when I tested `typescript@next`. Thanks for the help.
