### ISSUE TITLE
Removing JSDoc comments from d.ts files

### ISSUE THREAD

**Issue by pankleks** [Microsoft/TypeScript#20441]
I'm building my library with option to remove comments. At the same time I generate `d.ts` files for library.
Expectation is to remove comments from produced `js` files, and not from `d.ts`.

`js` is production file - I don't wan't comments there, `d.ts` is development - so JSDoc comment should not be removed even if remove comments flag is specified.

**Comment by mhegazy** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/14619

**Comment by mhegazy** [comment]
I think we should just change the behavior of `--removeComments` to exclude declarations.. I am sure some one will hate this behavior though :).

**Comment by pankleks** [comment]
I'm sure of that too ... :) 2 parameters?:) 
closing in favor of #14619
