### ISSUE TITLE
Change the type of a passed object to a function after function return (type predicate)

### ISSUE THREAD

**Issue by Viatorus** [Microsoft/TypeScript#20468]
**TypeScript Version:**  2.6.2

**Code**

```ts
interface A {
        name: string;
}

interface B extends A {
        id: number;
}

function change(a: A): a is B {
        a["id"] = 1;
        return true;
}

let foo = {
        name: "abc"
}

change(foo);

foo.id = 10; // doesn't work, but foo has changed!

if (change(foo)) {
        foo.id = 1; // Works like expected.
}
```

[Live example.](https://www.typescriptlang.org/play/#src=interface%20A%20%7B%0D%0A%20%20%20%20%20%20%20%20name%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20B%20extends%20A%20%7B%0D%0A%20%20%20%20%20%20%20%20id%3A%20number%3B%0D%0A%7D%0D%0A%0D%0Afunction%20change(a%3A%20A)%3A%20a%20is%20B%20%7B%0D%0A%20%20%20%20%20%20%20%20a%5B%22id%22%5D%20%3D%201%3B%0D%0A%20%20%20%20%20%20%20%20return%20true%3B%0D%0A%7D%0D%0A%0D%0Alet%20foo%20%3D%20%7B%0D%0A%20%20%20%20%20%20%20%20name%3A%20%22abc%22%0D%0A%7D%0D%0A%0D%0Achange(foo)%3B%0D%0A%0D%0Afoo.id%20%3D%2010%3B%0D%0A%0D%0Aif%20(change(foo))%20%7B%0D%0A%20%20%20%20%20%20%20%20foo.id%20%3D%201%3B%0D%0A%7D)

**Expected behavior:**

foo is type of B after call to change()

**Actual behavior:**

foo still is of type A

**Comment by aluanhaddad** [comment]
Type guards don't work in that manner. They are predicates. The impact they have on the type is contingent on their result. However, in the above code there's no way to know if the guard returned to true or false and therefore no way to know if the type of the variable was refined by the guard. If you wrap the call in an if statement or use it with the ternary operator you'll get the expected result

**Comment by RyanCavanaugh** [comment]
^

**Comment by Viatorus** [comment]
@aluanhaddad  I understand what you are saying.

But foo is not a type of A anymore (e.g. we delete the property name inside the function call) - without any condition.
This is for me a fault of the type system, isn't it?

```ts
interface A {
        name: string;
}

interface B {
        id: number;
}

function change(a: A): a is B {
        delete a["name"];
        a["id"] = 2
}

let foo = {
        name: "abc"
}

change(foo);

... foo.name  ... // bad!
... foo.id ... // good!
```

**Comment by aluanhaddad** [comment]
@Viatorus subjectively, I find that kind of code hard to reason about and unnecessarily convoluted.

There is a very simple alternative that expresses the very precise transformation of types involved while offering better readability by sticking more closely to the principal of least astonishment and by using language features for their intended purposes.

Consider:
```ts
interface A {
  name: string;
}

 // no return type annotation allows precise inference via ...
function change({name, ...rest}: A) {
   return {
       ...rest,
       id: 2
   };
}

const a: A = {
    name: 'abc'
};

const bLike = change(a);

console.log(bLike.id);   // OK
console.log(bLike.name); // Error
```

**Comment by Viatorus** [comment]
@aluanhaddad Yes, you are correct this would be a cleaner way. Thank you!

But my code above is 100% legal javascript code and currently not possible to be type safe with TypeScript.

Nevertheless, thank you for your thoughts. :)
