### ISSUE TITLE
Support for --target ES2018

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#20463]
As TC39 gets ready to finalize ES2018, we should allow pass through for some transformation now only enabled under `--target ESNext`, here is the list:

Disable transforms for:
* [ ] Rest/Spread Properties
* [ ] async generators/`for await ... of`

We also need some new lib definitions:
* [x] Promise finally (https://github.com/Microsoft/TypeScript/issues/20411)

The support for `--target ES2018` was added in https://github.com/Microsoft/TypeScript/pull/20385

**Comment by mhegazy** [comment]
// CC: @bterlson

**Comment by mhegazy** [comment]
// CC: @benbraou

**Comment by bterlson** [comment]
Just keep in mind that until a proposal shows up [here](https://github.com/tc39/proposals/blob/master/finished-proposals.md) it's not on the train for 2018.

**Comment by falsandtru** [comment]
@mhegazy optional catch binding is still stage 3 (https://github.com/tc39/proposals) and browserify can't compile it. This transform should be kept with es2018.

**Comment by DanielRosenwasser** [comment]
@falsandtru I've removed `* [ ] optional catch binding`

**Comment by falsandtru** [comment]
Thanks!

**Comment by mhegazy** [comment]
A PR would be appreciated. we need to split the transforms to their own file, and pipe the target flag through.

**Comment by mhegazy** [comment]
here is the PR that added ES2017 target, you can use it as a reference: https://github.com/Microsoft/TypeScript/pull/11407

**Comment by Kingwl** [comment]
and another feature: https://github.com/Microsoft/TypeScript/issues/20463 could(maybe) split too

**Comment by wolfy1339** [comment]
Now that ES2019 is around the corner, it would be a good time for this to be worked on, heck someone made a PR for ES2019 already.
