### ISSUE TITLE
Code duplication

### ISSUE THREAD

**Issue by shvabuk** [Microsoft/TypeScript#20473]
**TypeScript Version:**  2.7.0

Code duplication in file https://github.com/Microsoft/TypeScript/blob/master/lib/lib.webworker.d.ts
**Code**
```ts
declare function dispatchEvent(evt: Event): boolean;
```

**Actual:**
https://github.com/Microsoft/TypeScript/blob/master/lib/lib.webworker.d.ts#L1882
https://github.com/Microsoft/TypeScript/blob/master/lib/lib.webworker.d.ts#L1900

**Comment by Xavier-J-Ortiz** [comment]
Hey @shvabuk ! I'd like to pick this up. If that's ok.

It _looks_ pretty straight forward, but it would be my first PR to this project, or any open source project. Also will allow me to start to get familiar with the code base and grow from there.

**Comment by shvabuk** [comment]
@Xavier-J-Ortiz , ok. And I will write some tests.
Don`t forget to read #20481.

**Comment by Xavier-J-Ortiz** [comment]
@shvabuk - I'm going to let this one go. I checked the generator library, I think that there's some F# stuff there that is over my head.

I'll let someone else work on this. Sorry about that. :(

**Comment by shvabuk** [comment]
According to searchDuplicates script results https://gist.github.com/shvabuk/ad6b9974794dc7595c5832722df443fa more duplicates was found

> Duplication in file: lib/lib.dom.d.ts on lines: 776 & 14373 (ProgressEventInit)
> Duplication in file: lib/lib.dom.d.ts on lines: 3735 & 14684 (EXT_frag_depth)
> Duplication in file: lib/lib.d.ts on lines: 4874 & 18471 (ProgressEventInit)
> Duplication in file: lib/lib.d.ts on lines: 7833 & 18782 (EXT_frag_depth)
> Duplication in file: lib/lib.es2016.full.d.ts on lines: 779 & 14376 (ProgressEventInit)
> Duplication in file: lib/lib.es2016.full.d.ts on lines: 3738 & 14687 (EXT_frag_depth)
> Duplication in file: lib/lib.es2017.full.d.ts on lines: 784 & 14381 (ProgressEventInit)
> Duplication in file: lib/lib.es2017.full.d.ts on lines: 3743 & 14692 (EXT_frag_depth)
> Duplication in file: lib/lib.es2018.full.d.ts on lines: 778 & 14375 (ProgressEventInit)
> Duplication in file: lib/lib.es2018.full.d.ts on lines: 3737 & 14686 (EXT_frag_depth)
> Duplication in file: lib/lib.webworker.d.ts on lines: 1882 & 1900 (dispatchEvent)
> Duplication in file: lib/lib.esnext.full.d.ts on lines: 780 & 14377 (ProgressEventInit)
> Duplication in file: lib/lib.esnext.full.d.ts on lines: 3739 & 14688 (EXT_frag_depth)
> Duplication in file: lib/lib.es6.d.ts on lines: 6585 & 20182 (ProgressEventInit)
> Duplication in file: lib/lib.es6.d.ts on lines: 9544 & 20493 (EXT_frag_depth)

@RyanCavanaugh 
Looks like this issue may be closed and appropriate issue should be opened in https://github.com/Microsoft/TSJS-lib-generator .
May you give advise? May I add searchDuplicates script to tests? If yes, than in wich directory? It looks like generator (not compiler) issue.

**Comment by benbraou** [comment]
I will have free time to work on this issue (or the new one that @shvabuk may create) starting from Monday, 18th. But, if someone is willing to work on this before, please don't hesitate 😃

**Comment by benbraou** [comment]
I will be working on this issue. 
I will spend some time first familiarising myself with F#

**Comment by shvabuk** [comment]
Appropriate issue in JS-lib-generator repository created
https://github.com/Microsoft/TSJS-lib-generator/issues/347
