### ISSUE TITLE
No ability to add import module references in language server plugins 

### ISSUE THREAD

**Issue by prograhammer** [Microsoft/TypeScript#20487]
**TypeScript Version:**  latest
**Code**

![screencast](https://user-images.githubusercontent.com/4474660/33643625-dfce5b50-da05-11e7-949c-bacf37d9b074.gif)

**Expected behavior:**
When hover over module import statement the module should display.

**Actual behavior:**
I've successfully got the `.vue` module to be valid/resolved by proxying the `LanguageService.getProgram()` in my passthru [language service plugin](https://github.com/Microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin). However, when I hover over the `.vue` import statement it does not display the module in the popover. Also, when I type the imported class.property the auto-completion options on the properties don't show (even though the typechecker is correctly marking valid or invalid properties once I type them in fully).

How is this supposed to be done?

**Comment by mjbvz** [comment]
Also asked here: https://stackoverflow.com/questions/47725255/how-to-add-import-module-references-in-vscode-language-server-plugins

**Comment by mhegazy** [comment]
in your language service plugin you will need to handle completions for modules by adding the .vue module completions to the ones returned from the base LS.
