### ISSUE TITLE
Cannot access private property in intersection with union

### ISSUE THREAD

**Issue by tomb-pss** [Microsoft/TypeScript#20485]
**TypeScript Version:**  2.6.1

**Code**

```ts
interface A {
    a: string;
}

interface B {
    b: string;
}

class Foo {
    private bar: string;

    public static a(f: Foo & A) {
        console.log(f.bar);
    }

    public static b(f: Foo & B) {
        console.log(f.bar);
    }

    public static c(f: Foo & (A | B)) {
        console.log(f.bar); //Property 'bar' does not exist on type '(Foo & A) | (Foo & B)'.
    }

    public static d(f: Foo & (A | B)) {
        const x: Foo = f;
        console.log(x.bar);
    }
}
```

**Expected behavior:**
Foo.c() should compile successfully, allowing access to 'bar' property.

**Actual behavior:**
Foo.c() gives error "Property 'bar' does not exist on type '(Foo & A) | (Foo & B)'." even though all types in the union have Foo as part of their intersection. But, in Foo.d() it compiles just fine by first assigning 'f' to just a Foo type. Is this a bug or am I just misunderstanding something about how intersections work?

**Comment by mhegazy** [comment]
This is a design limitation, private members are not exposed on unions. protected (and to some extend private) properties have some involved rules about what they can be invoked on and where, and carrying this information around in a union type is not a simple task both conceptually and technically.
