### ISSUE TITLE
General indexer type

### ISSUE THREAD

**Issue by NN---** [microsoft/TypeScript#2049]
It is impossible to write generic type that represents key-value dictionary:

``` typescript
interface KeyValue<Key, Value> {
    [key: Key]: Value;
}
```

Key must be string or number, but generic constraints doesn't allow this.

``` typescript
interface KeyValue<Key extends string|number, Value> {
    [key: Key]: Value; // Still error
}
```

There is 'extends' but there is no 'is' to match exact type.
Something like "Key is string|number" or "Key: string|number" .

**Comment by DanielRosenwasser** [comment]
So for your example, I think what you're looking for is really the ability to index with a union type:

```TypeScript
interface Map<T> {
    [key: string | number]: T;
}
```

Which wasn't allowed when we first introduced union types, but for 1.5 you should have it through #1765.

**Comment by danquirk** [comment]
This wasn't a change we made, so re-opening this although it's not clear how useful it is.

**Comment by yjo** [comment]
+1, am wanting to do this now to write a type definition for Lodash's `_.mapKeys`

**Comment by RyanCavanaugh** [comment]
This needs more fleshing out. Currently number and string indexers have *very* different behavior; it's not at all obvious what the behavior of the "combined" key type would be. At a minimum we need to see what the desired behavior of this would be other than simply allowing its declaration to exist.

**Comment by aindlq** [comment]
At least it would be very useful to have the ability to use string literal union type as an indexer. As people have already pointed out in https://github.com/Microsoft/TypeScript/pull/5185#issuecomment-191208493

It is more limited than initial proposal, but added value will be tremendous.

**Comment by danielearwicker** [comment]
And now number literal union type as indexer!

**Comment by jovdb** [comment]
I also would like to have indexer with generics support:

```
interface IPerson<TPersonId extends string> {
    id: TPersonId;
    fullName: string;
}

interface IPersons {
    <TKey extends string>[key: TKey]: IPerson<TKey>;   // Made-up syntax
}
```
to represent: 
```
const persons: IPersons = {
    "a14578": {
        id: "a14578",
        fullName: "Jo Van den Berghe"
    } 
}
```

**Comment by weswigham** [comment]
The examples in this thread can be represented, today, with mapped types.
```ts
type KeyValue<Key extends string, Value> = {[K in Key]: Value};

interface IPerson<TPersonId extends string> {
    readonly id: TPersonId;
    fullName: string;
}
type IPersons<TKey extends string> = {[K in TKey]: IPerson<K>};
```

Is there still a feature request here?

**Comment by c69** [comment]
The problem with mapped types is that once you converted anything to type, you cannot use it as an interface, e.g.: no more `implements` for classes, and that's quite a bit trade-off.

I wonder if there are any ideological objections to allowing simple mapping syntax inside of interfaces.

```typescript
type AllWorks<T> = {
    [K in keyof T]: T[K]; // ok
}
interface DoesNotWork<T> {
    [K in keyof T]: T[K]; // would be great for this syntax to work inside of interfaces
}

```
While first one works as expected, second one gives the TS error: 

> [ts] A computed property name must be of type 'string', 'number', 'symbol', or 'any'.
> [ts] Member '[K in keyof' implicitly has an 'any' type.
> [ts] Cannot find name 'keyof'.

**Comment by kevupton** [comment]
I think what would be ideal is having generic types, but having the compiler validate the type when it is used. (for the key validation).

An example where a function returns: 
```typescript
{ [key : T[K]] : T }
```

Code:
```typescript
interface Type {
  [key: string]: any;
}

type ValueType<T extends object, K extends keyof T> = string | number;

export function arrayToObject<KeyType, T extends Type, K extends keyof T>(key: K, objects: T[]): {
  [key: T[K]]: T;
} {
  return Object.assign(
    {},
    ...objects.map(object => ({ [object[key]]: object }))
  );
}
```

Then when they use the method:
```typescript
interface Test {
  id: string;
  value: any;
}
const testArray: Test[] = [];
arrayToObject('id', testArray); // this should work because id is a string type and key accepts string.

interface Test2 {
  id: object;
  value: any;
}
const test2Array: Test2[] = [];
arrayToObject('id', test2Array); // this should fail because it recognises that `id` is an object. And you cannot have an `object` as a key.
```

**Comment by felixfbecker** [comment]
Is there an issue tracking the `is` contraint suggestion in the OP? I am trying to write a `propertyIsDefined` function like this:

```ts
export const isDefined = <T>(val: T): val is NonNullable<T> => val !== undefined && val !== null

export const propertyIsDefined = <T extends object, K extends keyof T>(key: K) =>
  (val: T): val is T & { [k in K]: NonNullable<T[k]> } => isDefined(val[key])
```

which works, but it is only type safe if `K` is a single string literal. If `K` is a union, this function is not type safe anymore, as it would mark _all_ properties in `K` as non-null, instead of _one of_ the properties in `K`. I would like to forbid passing in a union, `K` should be an exact element of `keyof T`, but `extends` allows to pass any subtype of `keyof T`.

**Comment by weswigham** [comment]
@felixbecker you just wanna decompose any input unions before you map, eg

```ts
export const propertyIsDefined = <T extends object, K extends keyof T>(key: K) =>
  (val: T): val is (K extends any ? T & { [k in K]: NonNullable<T[k]> } : never) => isDefined(val[key])
```

which should handle the input as union case like you'd like.

**Comment by RyanCavanaugh** [comment]
Discussion here has wandered quite a bit but the OP use case works now.
