### ISSUE TITLE
Union types of tuples and never[] incorrectly mutate into array types

### ISSUE THREAD

**Issue by falsandtru** [microsoft/TypeScript#20495]
**TypeScript Version:**  master

**Code**

```ts
const t1 = [0, ''] as [number, string] | undefined || [];
const [a1 = 0] = [0, ''] as [number, string] | undefined || [];
const t2 = [0, ''] as [number, string] | never[];
const [a2 = 0] = [0, ''] as [number, string] | never[];
```

Both types of `t1` and `t2` are the same type `[number, string] | never[]`. But the results of destructuring assignment is different. `a1` is `number` type but `a2` is `number | string` type. `a2` should also be `number` type.

**Comment by RyanCavanaugh** [comment]
`a2` is now `number` as expected
