### ISSUE TITLE
Type information gets lost with `_.findLast`

### ISSUE THREAD

**Issue by timm-gs** [Microsoft/TypeScript#20499]
I found the following when using Lodash's `findLast`. I am not sure how to better describe this, please feel free to update the title with the technically correct terminology.

**TypeScript Version:**  2.6.1
**Code**

[Playground](https://www.typescriptlang.org/play/index.html#src=%0D%0Ainterface%20ArrayLike%3CT%3E%20%7B%0D%0A%20%20%20%20readonly%20length%3A%20number%3B%0D%0A%20%20%20%20readonly%20%5Bn%3A%20number%5D%3A%20T%3B%0D%0A%7D%0D%0A%0D%0Atype%20ListIterator%3CT%2C%20TResult%3E%20%3D%20(value%3A%20T%2C%20index%3A%20number%2C%20collection%3A%20ArrayLike%3CT%3E)%20%3D%3E%20TResult%3B%0D%0A%0D%0Atype%20ListIterateeBoolean%3CT%3E%20%3D%20ListIterator%3CT%2C%20boolean%3E%3B%0D%0A%0D%0Afunction%20findLast%3CT%3E(%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20collection%3A%20ArrayLike%3CT%3E%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20predicate%3A%20ListIterator%3CT%2C%20boolean%3E%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20predicate%3A%20(T)%20%3D%3E%20boolean%2C%0D%0A)%3A%20T%20%7B%0D%0A%20%20%20%20throw%20new%20Error(%60%60)%20%20%20%0D%0A%7D%0D%0A%0D%0A%0D%0Atype%20XY%20%3D%20%7B%0D%0A%20%20%20%20x%3A%20number%2C%0D%0A%20%20%20%20y%3A%20number%2C%0D%0A%7D%0D%0A%0D%0Atype%20X%20%3D%20%7B%0D%0A%20%20%20%20x%3A%20number%0D%0A%7D%0D%0A%0D%0Afunction%20isGreater0(x%3A%20X)%20%7B%0D%0A%20%20%20%20return%20x.x%20%3E%200%3B%0D%0A%7D%0D%0A%0D%0Afunction%20xyLastXGreater0(xys%3A%20ReadonlyArray%3CXY%3E)%20%7B%0D%0A%20%20%20%20const%20res%20%3D%20findLast(xys%2C%20isGreater0)%3B%0D%0A%7D%0D%0A)

```ts

interface ArrayLike<T> {
    readonly length: number;
    readonly [n: number]: T;
}

type ListIterator<T, TResult> = (value: T, index: number, collection: ArrayLike<T>) => TResult;

type ListIterateeBoolean<T> = ListIterator<T, boolean>;

function findLast<T>(
            collection: ArrayLike<T>,
            predicate: ListIterator<T, boolean>,
            // predicate: (T) => boolean,
): T {
    throw new Error(``)   
}


type XY = {
    x: number,
    y: number,
}

type X = {
    x: number
}

function isGreater0(x: X) {
    return x.x > 0;
}

function xyLastXGreater0(xys: ReadonlyArray<XY>) {
    const res = findLast(xys, isGreater0);
}
```

**Expected behavior:**
I would expect `res` to be of type `XY`.

**Actual behavior:**
In the above example `res` is of type `X` with the above definition of the predicate. If you change the comment to use the "inline type" for the predicate, it will correctly be inferred to be of type `XY`.

(Please note that I have removed the `undefined` result case, as it's not relevant here)

**Comment by andy-ms** [comment]
It looks like with `--strictFunctionTypes` enabled we infer `XY` correctly. Don't see a reason why we couldn't do it without that flag. Tentatively marking as a bug.

**Comment by aluanhaddad** [comment]
This seems to already be working in the nightly.

**Comment by andy-ms** [comment]
@aluanhaddad It only works with `--strictFunctionTypes`.

**Comment by aluanhaddad** [comment]
Sorry I didn't realize I had that on.

**Comment by mhegazy** [comment]
Seems to be working in latest.

**Comment by mhegazy** [comment]
tried with `--strictFunctionTypes true`  and false.

**Comment by mhegazy** [comment]
Seems fixed in latest.
