### ISSUE TITLE
Windows Powershell tsc: Multiple Files not found 

### ISSUE THREAD

**Issue by pj035** [Microsoft/TypeScript#20493]
**TypeScript Version:**  2.7.0-dev.201xxxxx
Compiling multiple files in a directory from the command line with `tsc dir/*.ts` fails with a `file not found` error. 

PowerShell Version:
```PowerShell
$PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      15063  726
```

OS: Windows 10 Home 1703

**Code**

```PowerShell
mkdir test
cd test
echo "console.log('hi');" >> t1.ts
echo "console.log('hi');" >> t2.ts
cd ..
tsc test/*.ts
```

**Expected behavior:**
Compiler runs successfully and creates two .js files.

Note: This is working on a Ubuntu system, using bash and the same procedure as described above.

**Actual behavior:**
Compiler fails with `error TS6053: File 'test/*.ts' not found.`.

**Comment by j-oliveras** [comment]
Ubuntu shell/bash expands the `*` to all matched files. In your example the real call to tsc is like: `tsc test/t1.ts test/t2.ts`.

More info about [glob expansions](http://wiki.bash-hackers.org/syntax/expansion/globs).

This is more an issue for powershell than typescript.

**Comment by pj035** [comment]
I get your point. With the [PowerShell fork](https://github.com/PowerShell/PowerShell) it's working. Nevertheless I would like to provide a shell independent process. The best way for that should be to provide a tsconfig.
