### ISSUE TITLE
animationend and animationstart not in lib.dom.d.ts ?

### ISSUE THREAD

**Issue by ceymard** [microsoft/TypeScript#20494]
**TypeScript Version:**  2.6.2

It would seem that the `HTMLElementEventMap` does not have `animationstart` nor `animationend` yet there is an `AnimationEvent` type. Is this intentional ? The technology is starting to be pretty supported across browsers.

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by charlag** [comment]
I believe this is fixed now
https://github.com/microsoft/TypeScript/blob/189c2b9e4a4fc35f8a66c4796c0653229c71829d/lib/lib.dom.d.ts#L6378
`HTMLElementEventMap` extends `GlobalEventHandlersEventMap` which does indeed have `animationstart`/`animationend`

**Comment by jakebailey** [comment]
Just looking at old issues; yes, this is fixed as of #25944.
