### ISSUE TITLE
TypeScript compiler seems to be caught in infinite loop

### ISSUE THREAD

**Issue by couzic** [Microsoft/TypeScript#20492]
I created a repo to demonstrate the issue:
https://github.com/couzic/typescript-compiler-issue
(just run `npm install` and `tsc`)
I tried to make it as simple as possible, without flamboyant success...

**Expected behavior:**
A compiler error

**Actual behavior:**
The compiler seems to caught in an infinite loop, it does not return and one of the CPU cores is saturated.

Interestingly, when fixing the type error (as commented in line 26), the compiler works as expected.

**Comment by olivr70** [comment]
I am facing the same problem in big project I have been working on for months, and worked perfectly until last week. 
Is there a way to see which file in the project tsc is working in real time to get some hints of where to look at ?

**Comment by weswigham** [comment]
@couzic Your example doesn't hang using our 2.7 release (or `master` branch from github), so we've likely fixed it (the root cause was probably the same as a different hang bug).

@olivr70 does your issue still occur in 2.7? If so, can you share a reproduction?

**Comment by couzic** [comment]
@weswigham My problem is fixed, as far as I'm concerned you can close this issue.
Thanks !
