### ISSUE TITLE
createPrinter.printFile() should not remove empty lines

### ISSUE THREAD

**Issue by Maximaximum** [Microsoft/TypeScript#20506]
I'd expect `createPrinter.printFile()` to format the file, but **not** remove the empty lines inside the file. Empty lines are meaningful, because the developers often use an empty line to structure the code into identifiable blocks. For example, to separate the import declarations from the rest of the file.

**TypeScript Version:**  2.7.0-dev.20171206

**Code**

```ts
import { createPrinter, createSourceFile, ScriptTarget, NewLineKind } from 'typescript';
import * as fs from 'fs';

const file = createSourceFile('./output.ts', `
import    {smth} from 'dfsdf';
import {smth2} from 'dfsdf2';

foo();

`, ScriptTarget.Latest);

fs.writeFileSync(file.fileName, createPrinter().printFile(file));
```

**Expected behavior:**
`output.ts` should contain given text:
```
import { smth } from "dfsdf";
import { smth2 } from "dfsdf2";

foo();
```

**Actual behavior:**
`output.ts` contains given text:
```
import { smth } from "dfsdf";
import { smth2 } from "dfsdf2";
foo();
```

**Comment by RyanCavanaugh** [comment]
The operations from the printer are designed around emitting the .js file, where newlines shouldn't be significant. If you're wanting to *format* the file, use the formatting API. See https://github.com/vvakame/typescript-formatter/blob/master/lib/formatter.ts for an example

**Comment by Maximaximum** [comment]
Thanks, that seems to be exactly what we need! But it isn't an official Typescript team project? I thought that such functionality should be a part of Typescript itself

**Comment by RyanCavanaugh** [comment]
The thing I linked to is an example of how to use the TypeScript formatter API to accomplish the task of formatting a .ts file

**Comment by Maximaximum** [comment]
Yeah, now I see it. Thanks! I think we can close this question now.
