### ISSUE TITLE
Extract to method should preserve newlines

### ISSUE THREAD

**Issue by NoelAbrahams** [microsoft/TypeScript#20509]
**TypeScript Version:**  2.6.2

**Code**
![newlinebug](https://user-images.githubusercontent.com/1106823/33679266-2a08c22c-dab6-11e7-9f96-9e7202c2fd39.gif)

**Expected behavior:**
```ts
function newFunction() {

    const bar = 10;

    return bar + 1;
}
```
**Actual behavior:**
```ts
function newFunction() {
    const bar = 10;
    return bar + 1;
}
```

I also personally prefer a newline at the first position of the function body, but that is probably debatable.

**Comment by vladima** [comment]
related to #20506?

**Comment by Kingwl** [comment]
what should we do for this issue...
Refactorings context is only AST without linebreak...
or i missing something? help need

**Comment by RyanCavanaugh** [comment]
Works as requested now
