### ISSUE TITLE
projectOutput directory is not deleted in certain circumstances

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#2050]
Described here: https://github.com/Microsoft/TypeScript/pull/1589#issuecomment-74371441

> `jake runtests` executes mocha. Since the tests don't pass, mocha aborts. Because of that, the jake process aborts too, and the command to remove the temporary directory isn't executed. By running `jake runtests`, `jake baseline-accept`, `jake runtests`, `jake baseline-accept`, the directory will be deleted, because the tests pass the second time.

**Comment by mhegazy** [comment]
Yui's change to put the folder in the .gitignore should mitigate effects of this issue.
