### ISSUE TITLE
Spread syntax with extends object type parameters

### ISSUE THREAD

**Issue by ethanresnick** [Microsoft/TypeScript#20510]
**TypeScript Version:**  2.6.1

**Code**

```ts
function<T extends object>(it: T) {
    return { ...it };
}
```

**Expected behavior:**
No error

**Actual behavior:**
Error: Spread types may only be created from object types.

**Comment by sandersn** [comment]
`T` is a type parameter, which cannot be used to create a spread type. The `object` type constraint doesn't get around this rule.

If we ever add a first-class spread type this restriction will go away.
