### ISSUE TITLE
Parsing of TypeAliasDeclaration doesn't get its type

### ISSUE THREAD

**Issue by shobhitg** [Microsoft/TypeScript#20514]
The Typescript parser isn't actually parsing the type of `TypeAliasDeclaration`

Example:
```
export type IPv4CIDRBlock = string;
```

The parsing leads us to following function: https://github.com/Microsoft/TypeScript/blob/61094ec2ea8ec4707c5cfa7a8d2fc0d68ce5f2a8/src/compiler/parser.ts#L5689
```
        function parseTypeAliasDeclaration(fullStart, decorators, modifiers) {
            var node = createNode(231 /* TypeAliasDeclaration */, fullStart);
            node.decorators = decorators;
            node.modifiers = modifiers;
            parseExpected(138 /* TypeKeyword */);
            node.name = parseIdentifier();
            node.typeParameters = parseTypeParameters();
            parseExpected(58 /* EqualsToken */);
            node.type = parseType();
            parseSemicolon();
            return addJSDocComment(finishNode(node));
        }
```

Somewhere in there, it was expected to get `= string` portion parsed. But it seems that it fails.

**Comment by RyanCavanaugh** [comment]
Right here...
```ts
   node.type = parseType();
```

> But it seems that it fails.

Can you be more specific about what you mean by this? Certainly this code is correctly parsed.

**Comment by shobhitg** [comment]
I am not able to get the information that `IPv4CIDRBlock` is `string` type.

See screenshot (attached) of my dev tools:

![screenshot 2017-12-06 13 33 53](https://user-images.githubusercontent.com/440151/33686563-253304f0-da8a-11e7-8171-2903f0dc591c.png)

**Comment by RyanCavanaugh** [comment]
What **exactly** are you expecting to happen? The `node.type` object has `kind === SyntaxKind.StringKeyword`.

**Comment by shobhitg** [comment]
@RyanCavanaugh Oh, I didn't realize that `kind` property was indicating `StringKeyword`. Thanks for clarifying.
It seems this isn't a bug.
