### ISSUE TITLE
If you infer a type by calling a function, you can not infer the type.

### ISSUE THREAD

**Issue by WonbaeLee** [Microsoft/TypeScript#20529]
**angular Version:**  5.0.0
**TypeScript Version:**  2.4.2

**Code**
```ts
// My type reasoning function
export function isString (value: any): boolean {
  return (typeof value === 'string');
}

// using function
class Test {
  public testFunc (menuEl: string | ElementRef) {
    if (isString(menuEl)) {
      // Not using string function
    } else {
      // ....
    }
  }
}
```

**Expected behavior:**

I think TypeScript have to deduce types

**Actual behavior:**
[Typescript playground](https://www.typescriptlang.org/play/index.html#src=function%20isString(value%3A%20any)%3A%20boolean%20%7B%0D%0A%20%20return%20(typeof%20value%20%3D%3D%3D%20'string')%3B%0D%0A%7D%0D%0A%0D%0Aclass%20Test%20%7B%0D%0A%20%20public%20func(value%3A%20string%20%7C%20boolean)%20%7B%0D%0A%20%20%20%20if%20(isString(value))%20%7B%0D%0A%20%20%20%20%20%20console.log(value.split(''))%3B%0D%0A%20%20%20%20%7D%20else%20%7B%0D%0A%20%20%20%20%20%20%2F%2F%20...%0D%0A%20%20%20%20%7D%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Anew%20Test().func('Hello%2C%20Typescript'))

**Comment by ajafff** [comment]
The correct return type annotation does the trick:
```ts
export function isString (value: any): boolean {
  return (typeof value === 'string');
}
// change to
export function isString (value: any): value is string {
  return (typeof value === 'string');
}
```
