### ISSUE TITLE
d.ts export default with require

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#20526]
**TypeScript Version:**  2.7.0-dev.20171203

**Code**
For a the jsconfig:

```json
{
    "compilerOptions": {
        "target": "ES6",
        "module": "commonjs"
    },
    "exclude": [
        "node_modules",
        "**/node_modules/*"
    ]
}
```

In the js file:

```js
// @ts-check
const chalk = require('chalk')
chalk.yellow
```

**Expected behavior:**
No error. Code runs fine under node

**Actual behavior:**
Error on `chalk.yellow`. You have to change the code to `chalk.default.yellow`

Chalk provides its own typings here: https://github.com/chalk/chalk/blob/master/types/index.d.ts#L97

Not sure if there is a configuration option we can set in the `jsconfig` to make TS understand default exports with `require`

// cc @egamma

**Comment by mhegazy** [comment]
This seems like a declaration file issue. the file is declared such that it has one export `"default"`, where as the package at runtime seems to have the module object as a function with a property called `"default"`. the best way to achieve that is to author the declaration file to use `export = <id>`, where `id` is both a function and a namespace. The namespace should have a property `"default"` to correctly model the library.

**Comment by egamma** [comment]
@mhegazy this makes sense, once concern I have is that this is a common pattern in existing declaration files. I ran into this several times when I enabled 'checkJS'. Another example is the gulp-tslint declaration file. Rather than trying to migrate all the declaration files, could TS make this transformation behind the scenes?

```typescript
export interface PluginOptions {
    configuration?: any;
    formatter?: string | Function;
    formattersDirectory?: string;
    rulesDirectory?: string;
    tslint?: any;
    program?: any;
}
export interface ReportOptions {
    emitError?: boolean;
    reportLimit?: number;
    summarizeFailureOutput?: boolean;
}
export interface TslintFile {
    tslint: any;
    path: string;
    relative: string;
    contents: Buffer | any;
    isStream(): boolean;
    isNull(): boolean;
}
export interface TslintPlugin {
    (pluginOptions?: PluginOptions): any;
    report: (options?: ReportOptions) => any;
}
/**
 * Main plugin function
 * @param {PluginOptions} [pluginOptions] contains the options for gulp-tslint.
 * Optional.
 * @returns {any}
 */
declare const tslintPlugin: TslintPlugin;
export default tslintPlugin;
```
