### ISSUE TITLE
File resolution not falling back to index.ts file when the fieds typings or types exist on package.json

### ISSUE THREAD

**Issue by HitalloExiled** [Microsoft/TypeScript#20535]
I'm working on a project that has multiple directories, each with its own tsconfig.json and package.json resulting in separate but interdependent projects.

When compiling all projects with the --declaration false option everything happens fine.
But when I try to generate the declaration files I constantly encounter the error "Two different types with this name exist, but they are unrelated.".

Which forced me to choose between ts and d.ts in the same directory.

When I ran the tsc --listfiles command in one of the projects, I noticed that all the index files were being resolved for the d.ts files while the others were usually resolved to the ts files.

With --traceresolution I noticed the following behavior:

```bash
Loading module '@surface/enumerable' from 'node_modules' folder, target file type 'TypeScript'.
Found 'package.json' at 'F:/Projects/Surface/workbench/modules/source/@surface/collection/node_modules/@surface/enumerable/package.json'.
File 'F:/Projects/Surface/workbench/modules/source/@surface/collection/node_modules/@surface/enumerable.ts' does not exist.
File 'F:/Projects/Surface/workbench/modules/source/@surface/collection/node_modules/@surface/enumerable.tsx' does not exist.
File 'F:/Projects/Surface/workbench/modules/source/@surface/collection/node_modules/@surface/enumerable.d.ts' does not exist.
'package.json' does not have a 'typings' field.
'package.json' has' types' field 'index.d.ts' that references' F:/Projects/Surface/workbench/modules/source/@surface/collection/node_modules/@surface/enumerable/index.d.ts '.
File 'F:/Projects/Surface/workbench/modules/source/@surface/collection/node_modules/@surface/enumerable/index.d.ts' exist - use it as a name resolution result.
```

First the compiler tries to resolve the path provided along the ts, tsx, and d.ts extensions.

If it does not find, look in the package.json for the fields typings and types and if it finds, it resolves from them.

I believe the correct here would be, before trying to solve from the package.json, try to resolve to the index file of the path provided along the extensions ts, tsx, d.ts.

Note: It is possible to eliminate the error by removing the fields typings and types from package.json, but I have not yet analyzed the implications of this when publishing the modules.

**Steps to Reproduction:**

 Create two projects with the following structure

project-a/
|- index.d.ts
|- index.js
|- index.ts
|- non-index.d.ts
|- non-index.js
|- non-index.ts
|- tsconfig.json
|- package.json

project-b/
|- index.d.ts
|- index.js
|- index.ts
|- tsconfig.json
|- package.json

project-a/tsconfig.json
```json
{
  "compilerOptions": {
    "target": "es6",
    "declaration": true
  }
}
```

project-a/package.json
```json
{
    "name": "project-a",
    "version": "1.0.0",
    "description": "",
    "main": "index.js",
    "types": "index.d.ts",
    "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1"
    },
    "author": "",
    "license": "ISC"
}
```

```ts
//project-a/index
export function foo(): void {
    console.log("foo");
}
//project-a/non-index
export function bar(): void {
    console.log("bar");
}

//project-b/index
import { foo } from "../project-a";
import { bar } from "../project-a/non-index";

foo();
bar();
```

**Expected behavior:**
Always resolve to ts file when it exists.

**Actual behavior:**
Resolving to fields typings and types before trying to resolve to the index file of the provided path.

**Comment by mhegazy** [comment]
If you want it to resolve to the .ts file either set typing to `"types": "index"`, or do not set it.. i find it weird that in your own package you have a setting that you want the compiler to ignore.

**Comment by HitalloExiled** [comment]
Keeping this setup makes sense keeping in mind that when publishing the ts file will not be there. 

I just find it weird the compiler give priority to the d.ts if the ts file is next.
During development trying to consume these unpublished packages can be very annoying.

Although after removing the types fields I have not noticed any apparent problems.
