### ISSUE TITLE
Import path not checked when not importing any symbols

### ISSUE THREAD

**Issue by jamietre** [Microsoft/TypeScript#20534]
**Typescript version:** 2.6.1

**Code**

```ts
import foo from 'some/valid/module'
> no errors!

import foo from 'something/nonexistent'
> TS2307: Cannot find module 'something/nonexistent'

import 'something/nonexistent'
> no errors!
```

**Expected behavior:**

Import statements that don't import any symbols should be checked the same as any other.

**Actual behavior:**

If you don't import a symbol, the import target is not validated to resolve correctly.

tsconfig.json:
```
{
  "compilerOptions": {
    "jsx": "react",
    "moduleResolution": "node",
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "removeComments": true,
    "strictNullChecks": true,
    "target": "ES6"
  },
}
```

**Comment by RyanCavanaugh** [comment]
I can't find the issue because "import" + "error" = all the issues, but this is the intended behavior as per many requests from users to support scenarios such as importing CSS modules for their side effects without having to write empty declaration files for them

**Comment by jamietre** [comment]
So in order to support using `import` statements to resolve non-Typescript/non-Javascript files, any `import` statement that doesn't resolve and export from a module is essentially not checked at all?

This seems very counterintuitive. If you're importing CSS, then presumably some other (non-Typescript) compiler like Webpack is involved in the process and would handle dealing with the target in a way that's acceptable to the typescript compiler, such as removing it from the code that's passed to the TS compiler. If there wasn't another compiler involved, then the import would serve no purpose.

On the other hand, it's perfectly valid ES6 syntax to import JavaScript modules without importing any symbols in order to ensure (say) global dependencies or other bootstrapping is resolved. 

So the way it is now, basically, there's no confidence or checking offered by the TS compiler for such valid imports.

This should at the very least be a user-configurable compilation option. And even if we decide we aren't going to typecheck the static depdnency (e.g. since it's CSS), we should still at least ensure it exists!
