### ISSUE TITLE
Types from member function overloads in a base class/interface don't appear in child instances

### ISSUE THREAD

**Issue by kjin** [Microsoft/TypeScript#20548]
**TypeScript Version:**  2.7.0-dev.20171207

If I define some overloads of a function in a base class, and others (for the same function) in a derivative child class, TypeScript appears to ignore overloads of that function from the base class on objects that are instances of the child class.

This is behavior I observed in VS Code 1.18.1, but my guess is that it has to do specifically with TypeScript and not VS Code itself.

**Code**

In VS Code, type the following:

```js
interface BaseClass {
  do(task: string, callback: (...args: any[]) => void): void;
  do(task: 'get-number', callback: (arg: number) => void): void;
}

interface ChildClass extends BaseClass {
  do(task: string, callback: (...args: any[]) => void): void;
  do(task: 'get-string', callback: (arg: string) => void): void;
}

let a: ChildClass = {} as ChildClass;
```

**Expected behavior:**

Append the following code and observe that `arg` is a recognized as a `string`:

```js
a.do('get-string', (arg) => {}); // arg: string
```

**Actual behavior:**

Append the following code and observe that `arg` has no type information:

```js
a.do('get-number', (arg) => {}); // arg: any (number expected)
```

In addition, VS Code suggests `'get-string'` as an overload type for `task`, but not `'get-number'`.

**Additional Notes:**

To elaborate in a practical setting: I am trying to add a listener to an instance of Node's `http2.ClientHttp2Stream` for the `'trailers'` event. The `'trailers'` listener overload for `on` is defined in the base class `http2.Http2Stream` (see the [type definitions for node-core http2](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/85c17c4f49a8b4cf6b6282c376380e7cae20ff84/types/node/index.d.ts#L6160)). I expect the VS Code to recognize that the first argument in the listener callback is a `http2.IncomingHttpHeaders`, but it comes out as `any` instead.

**Comment by mhegazy** [comment]
Overload resolution in TS is order dependent. You will need to put the more specific signature at the top..
i.e.:
```ts
  do(task: 'get-string', callback: (arg: string) => void): void;
  do(task: string, callback: (...args: any[]) => void): void;
```

**Comment by kjin** [comment]
@mhegazy Thanks for the response, but that doesn't address the issue. Order dependency doesn't make a difference here -- the repro still happens when the signatures are reversed.

I think this is a legitimate issue in TS, can this at least be re-opened?

**Comment by kjin** [comment]
@mhegazy Bump? Or should I open a new issue?
