### ISSUE TITLE
progressBars with project test is broken

### ISSUE THREAD

**Issue by Kingwl** [Microsoft/TypeScript#20567]
**TypeScript Version:**  2.7.0-dev.201xxxxx

Sorry I do not know how to describe this, it did not follow the issue of the format  

<img width="1435" alt="1" src="https://user-images.githubusercontent.com/6831019/33750884-de5fc584-dc11-11e7-8d07-4704db4c8ed4.png">

**Comment by mhegazy** [comment]
I have seen that myself too.. @weswigham noticed that my console column length was different from the one the tests were reading..

**Comment by weswigham** [comment]
Whoa. Looks like your terminal emulator is reporting _way_ more columns to node than it actually has. Would you both be OK with an environment variable to override the output column width (so you can override the reported width)?

**Comment by Kingwl** [comment]
hi 
any progress here? 
This problem makes me crazy 😢  
and it slow down the test runner (perhaps
Recurring on windows / mac

**Comment by Kingwl** [comment]
seems it working fine in current
