### ISSUE TITLE
Missing implicit-any error on computed property in destructuring

### ISSUE THREAD

**Issue by mattmccutchen** [Microsoft/TypeScript#20566]
**TypeScript Version:**  current master (5e5b7706e55e3f416c0ee7bad0cdb1ecf5342b3f)

**Code**

```ts
// Compile with --noImplicitAny
function getSomePropertyName() {
  return "a";
}
function foo(s: string) {}
let {[getSomePropertyName()]: x} = {a: 4, b: 5};
foo(x);
```

**Expected behavior:**
Implicit-any error on `x`.

**Actual behavior:**
`x` has type `any` and can be passed to `foo` without error.

**Comment by mhegazy** [comment]
seems related to https://github.com/Microsoft/TypeScript/issues/20725

**Comment by mattmccutchen** [comment]
Duplicate of #20725
