### ISSUE TITLE
Typescript compiler doesn't fail when importing {} from a module that doesn't exist

### ISSUE THREAD

**Issue by ramaghanta** [Microsoft/TypeScript#20576]
TypeScript Version: **2.6.2 (tried with 2.7.0-dev.20171208)**

**Code**

`import {} from 'nothing';`

**Expected behavior:**
tsc should fail with an error "Cannot find module 'nothing'", just like what it does when we say
`import 'nothing';`
 or
`import {nothing} from 'nothing';`
or
`import * as nothing from 'nothing';`

**Actual behavior:**
Typescript compiler is successful without any error.

**Comment by RyanCavanaugh** [comment]
This has been the behavior since at least 1.8 so it's a bit of a scary breaking change... but it's definitely a bug that we're not treating it the same as `import "nothing";`. Decent good first PR if anyone's interested

**Comment by DanielRosenwasser** [comment]
Actually, `import "nothing"` also suffers from this problem. And this is a break for anyone who has ever used https://github.com/Microsoft/TypeScript-React-Starter in which users can `import "./Foo.css"`.

**Comment by mhegazy** [comment]
We have left these unchecked to allow for uses where the module is a non-code module, e.g. `.css`. Users do that to allow for bundles to bundle such assets with your code.

The rational here is we care about modules mainly for type purposes. if we are not garbing any types from the modules, there is no reason to error.

It gets even more complicated to get these right with things like loader extensions, where the module name is not a file name but rather a loader + file, e.g. `css!a.css`.

It is widely used out in the wild, and the break will be big. for instance, here is the sample we shared with users for react that uses this pattern: https://github.com/Microsoft/TypeScript-React-Starter/blob/master/src/App.tsx#L2
