### ISSUE TITLE
WeakMap keys require no primitive type constraint

### ISSUE THREAD

**Issue by srenault** [Microsoft/TypeScript#2057]
The type checker shouldn't accept this:

```javascript
var map = new WeakMap();
map.set('foo', 'bar');
```
A key must be of type "Object".

**Comment by danquirk** [comment]
The construct signature for WeakMap at the moment is:
```ts
new <K, V>(): WeakMap<K, V>;
```
which is why this is allowed. We don't currently have a way to specify that K must be an object type but not a primitive, but such a feature has been suggested in #1809.

**Comment by mhegazy** [comment]
We currently do not have a way to type that. if and when #1809 is available, we should revisit this bug.

**Comment by cpcallen** [comment]
Looks like #1809 is available.  Should this be revisited?  (Or if done in the mean time, have the Revisit tag removed?)
