### ISSUE TITLE
Parameter of indented method call should be indented relative to the `.`

### ISSUE THREAD

**Issue by kwall2004** [Microsoft/TypeScript#20577]
Actual
![image](https://user-images.githubusercontent.com/19229852/33774558-aa21b348-dc09-11e7-9418-50a052c4dd01.png)

Expected
![image](https://user-images.githubusercontent.com/19229852/33774597-c28b0aba-dc09-11e7-911c-44c7216cd3eb.png)

**Comment by andy-ms** [comment]
Simpler repro:
```ts
1
    .toFixed(
        2);
```
Should stay the same, but currently formats to:
```ts
1
    .toFixed(
    2);
```

**Comment by lankaapura** [comment]
Seems fixed by https://github.com/Microsoft/TypeScript/pull/21027. I've updated the existing test case and verified that issue is not there.
