### ISSUE TITLE
Import autocomplete suggests not exported types and interfaces

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#20584]
_From @klis87 on December 6, 2017 12:35_

- VSCode Version: 1.18.1
- OS Version: Linux

Steps to Reproduce:
1. Install `redux-saga-requests` library with `yarn add redux-saga-requests`
2. Start typing `import {} from 'redux-saga-requests'` and use autocomplete feature between `{}` with `ctrl + space`. You will see types and interfaces not exported in typings TypeScript file.

For example, I have a following in my `index.d.ts` file:
```typescript
interface ActionTypeModifier {
  (actionType: string): string;
}
```
but I can still see `ActionTypeModifier` hint. The problem is, that autocomplete is polluted with many internal types, which are not part of public API. Is it an expected behavior?

Reproduces without extensions: Yes

_Copied from original issue: Microsoft/vscode#39785_

**Comment by andy-ms** [comment]
The `export` keyword isn't necessary for something to be exported. All declaratinos in a declaration will be exported (the exception being when there is an `export =` somewhere).
If a type is truly internal, you can simply not include it in the declaration file. But in this case it looks like this is the return type of a public function, so it's not really internal...
If you really don't want that showing up in completions in an `import` declaration, you could move the "internal" types to another file and import from there. They may still show up as global completions, though.

**Comment by aluanhaddad** [comment]
@andy-ms I am specifically seeing this for all exports declared under [types/npm-ramda/src](https://github.com/types/npm-ramda/tree/dist/src)
E.g.
```ts
declare const groupWith;
export = groupWith;
```
auto imports for what are non-existent named exports are being suggested.
Should I open a separate issue or would it be best to track it here?
