### ISSUE TITLE
Give better error message on consecutive numeric separators

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#20585]
From https://github.com/Microsoft/TypeScript/pull/20324#discussion_r155889852, and contingent on #20324 first getting merged.

```ts
let x = 123__456;
```

Note the double underscores.

Actual: `Numeric separators are not allowed here.`

* `A numeric literal cannot contain multiple consecutive separators.`
* `Multiple consecutive numeric separators are not permitted.`

**Comment by harunurhan** [comment]
I'll take this one, if nobody else is working on it.
