### ISSUE TITLE
Private constructor incorrectly triggers --noUnusedLocals

### ISSUE THREAD

**Issue by gunsch** [Microsoft/TypeScript#20589]
**TypeScript Version:**  2.7.0-dev.20171208

**Code**
Compile the following with --noUnusedLocals

```ts
export class ServiceRegistry {
  private ServiceRegistry() {}
  public static get() { return new ServiceRegistry(); }
}
```

**Expected behavior:**
Code compiles.

**Actual behavior:**
../../../../../../tmp/blah.ts(2,11): error TS6133: 'ServiceRegistry' is declared but its value is never read.

If I change the constructor to "public", the code compiles.

**Comment by jwbay** [comment]
Unlike some other languages, JavaScript (and therefore TypeScript) does not use the class name as a constructor name, so what you've declared is a private method that never gets called by anything. Thus the error. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/constructor

**Comment by gunsch** [comment]
Whoa. I've been writing JavaScript/TS for years, and just totally blanked on this one. Thanks for the gentle correction and not making me feel like an idiot :)
