### ISSUE TITLE
Crash in CompileOnSave on Visual Studio 2015

### ISSUE THREAD

**Issue by vladima** [Microsoft/TypeScript#2058]
Repro:
1. create new TypeScript project (in VS 2015)
2. open .ts file, hit ctrl+s many times (this will invoke compile-on-save), make a few edits (add spaces) then keep saving the file. Eventually VS crashes.

**Comment by vladima** [comment]
Root cause is tracked by [CancellationToken is not correctly propagated downstream](https://github.com/dotnet/roslyn/issues/447)

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi, @vladima, this has been addressed in the Roslyn side. Let me know if you find any more issues.

**Comment by vladima** [comment]
verified that original problem is fixed in the latest bits
