### ISSUE TITLE
Redeclared members in inherited class are considered not initialized

### ISSUE THREAD

**Issue by stephanedr** [Microsoft/TypeScript#20581]
**TypeScript Version:**  2.7.0-dev.20171208

**Code**

```ts
interface Options {
    opt1: number;
}

class A {
    protected _options: Options;

    constructor(options: Options) {
        this._options = options;
    }
}

class B extends A {
    // Update _options' type in order to access opt2.
    protected _options: Options & { opt2: number }; // Property '_options' has no initializer and is not definitely assigned in the constructor.

    constructor(options: Options & { opt2: number }) {
        super(options);
        let a = this._options.opt2; // Property '_options' is used before being assigned.
    }
}
```

**Expected behavior:**
No error.

**Actual behavior:**
2 errors reported in comments.

I suppose TS considers `_options` as a new member of `B`, whereas it's just redeclared to be able to access `opt2`.
Unless I'm not using the right way to update the type of `_options`?

**Comment by RyanCavanaugh** [comment]
You've redeclared it with a more specific type. There's no reason to expect that the base class just happened to initialize the property with a correct value, so you need to initialize the value.

**Comment by stephanedr** [comment]
I thought/considered that redeclaring the type of a member was a kind of "permanent" type assertion, to avoid to type `(this._options as Options & { opt2: number }).opt2` each time I need to access `opt2`.
Though I can understand that TS doesn't consider this that way.

Note that `this._options = options` inside `B`'s constructor is not a clean option, as in my case (vs. the simple provided example) `this._options` may have been updated, compared to `options`, by `A`'s constructor.
Using `this._options = this["_options"]` solves the issue.
