### ISSUE TITLE
Curried interface functions only return single interface type

### ISSUE THREAD

**Issue by jon49** [Microsoft/TypeScript#2059]
As seen in the test code below the function `newTest` only accepts a `number` value, even though the `interface` says it should accept `number` or `number[]`

```ts
var _ = {
	curry: (fn: Function) => {return fn} 
}

interface Test {
	(val: string, num: number): string
	(val: string): (num: number) => string
}

var test = <Test> _.curry((val: string, num: number) => {})

interface Test2 {
	(val: string, num: number[]): any // {} with any properties
	(val: string): (num: number[]) => any
}

var test2 = <Test2> _.curry((val: string, num: number[]) => {})

interface Test3 extends Test, Test2 { }

var test3 = <Test3> _.curry((val: string, number: number | number[]) => {})

var newTest = test3('')
newTest([1, 2])  //fails
newTest(1)        //succeeds
```

**Comment by RyanCavanaugh** [comment]
You've explicitly type-asserted that `test` is of type `Test3`. There are no overloads of `Test3` that take a `string[]` as a first parameter.

**Comment by jon49** [comment]
I extend `Test` and `Test2` which accept a `string` not <strike>`string[]`</strike> as the first parameter and then accept a `number` or `number[]` as the second parameter. But TypeScript only accepts the first one, `number`.

**Comment by jon49** [comment]
`newTest` should have type `(num: number): string` or `(num: number[]): any`, but `newTest` only has type `(num: number): string`

**Comment by jon49** [comment]
@RyanCavanaugh I see the confusion now. I updated my original question to reflect the actual code. Sorry about that. Aargh!

**Comment by RyanCavanaugh** [comment]
Sorry, I misread the code as well.

The "flattened" version of `Test3` is this:
```ts
interface Test3 {
    (val: string, num: number): string
    (val: string): (num: number) => string
    (val: string, num: number[]): any // {} with any properties
    (val: string): (num: number[]) => any
}
```
The invocation of `test3('')` selects the first applicable overload, which returns `(num: number) => string`

There's no logic in the type system that says "If you see multiple matching overloads, union the return types". I'm not sure that that has any analog in the real world. We *always* use the rule that the first applicable overload is the one that gets used.

**Comment by jon49** [comment]
It doesn't make sense to only accept the first function return value since it hasn't been decided which function type is being used yet. It doesn't work with polymorphic, curried functions. Which is the real world, since I am programming this for a real application.

**Comment by jon49** [comment]
Just so you have an idea of how I'm using this code. I am parsing xml callbacks. I use the first argument to get the xml base to loop through the xml document. The second argument is the xml string. The third argument can be multiple values, if I just want the value from the xml document I pass a string, if I want a value as an object I pass an array with the object key string and the xml key, if I want multiple values I pass and array of arrays and return an object.

So, the first two values are the "settings" and I don't want to repeat it, so I curry the function. I then can access the xml document easily. JavaScript is a functional language, in addition to its object orientation. So, I think it would make for sense TypeScript to embrace more of its functional abilities. If we say that we only return the first rather than the union of types then we are poo, pooing JavaScripts functional and polymorphic sides.

**Comment by RyanCavanaugh** [comment]
I'm all for functional things, it's just that the type system has to have rules and it's really not clear that a rule that says "combine the overloads of multiple matching return values" is a good idea. A function only returns *one thing*; it doesn't make sense to say "This function will return one of two things based on things that happen later".

If you really want `Test3` to work that way, you'll have to write the overload set out yourself.

**Comment by jon49** [comment]
Yeah, that is what I ended up doing. I don't know all the internals of how TypeScript works and the hurdles it would have to overcome and headaches it would cause to make it work, so I'll just accept your answer, although, it is a bit frustrating to have to repeat myself over and over on the `interface` side, it doesn't seem intuitive to me.

In a sense the function is only returning one thing, an overloaded function. A function is one thing, yet it can have multiple types, in JavaScript at least. So, still not making sense to me why that would be a design decision we we are allowing polymorphic functions to begin with.
