### ISSUE TITLE
Import elided when the last use is a const enum

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#20598]
**TypeScript Version:**  2.7.0-dev.20171209

**Code**

**a.ts**
```ts
export function f(): void {}
export const enum E { None }
```

**b.ts**
```ts
import * as a from "./a";
a.f();
a.E.None;
```

**Expected behavior:**

Output imports `a` before using it.

**Actual behavior:**

**b.js**:
```js
a.f();
0 /* None */;
```

There is no error if I move `a.E.None;` before `a.f();`.

**Comment by andy-ms** [comment]
This worked in `2.7.0-dev.20171129` but was broken in `2.7.0-dev.20171130`.

**Comment by andy-ms** [comment]
@weswigham This was broken by #20320; verified that there was no bug in the previous commit.

**Comment by weswigham** [comment]
https://github.com/Microsoft/TypeScript/pull/20588 is already up with a fix
