### ISSUE TITLE
For..in loops with block scope incorrectly capture key when key type is number, but not string

### ISSUE THREAD

**Issue by darkf** [Microsoft/TypeScript#20594]
**TypeScript Version:**  2.7.0-dev.20171209

**Code**

```ts
// Change the type of id to `string` to see the correct behavior.
const objs: { [id: number]: string } = {
    1: "foo",
    2: "bar"
};

const fns: (() => string)[] = [];

for(const key in objs) {
    fns.push(() => objs[key]);
}

for(const fn of fns)
    console.log("> " + fn());

```

Compile with a target of ES3 or ES5.

**Expected behavior:**

This code should properly capture and copy `key` (as per block scope) and it should output to the terminal:

```
> foo
> bar
```

**Actual behavior:**

It incorrectly captures `key`, and instead gives up on transforming the loop entirely and uses a normal ES3 loop, and outputs:

```
> bar
> bar
```

However, if you change the type of the key (`id`) to string, it behaves correctly.

**Comment by RyanCavanaugh** [comment]
Regression from 2.6

**Comment by RyanCavanaugh** [comment]
@rbuckton I expected this to be a regression, but it seems this has never worked... am I missing something?

**Comment by rbuckton** [comment]
It seems like `for..in` does not perform the correct down-leveling for captured loop bodies:

```ts
declare const ar: string[];
declare const obj1: { [id: number]: string };
declare const obj2: { [id: string]: string };

// for..in number indexer
for(const key1 in obj1) {
    () => obj1[key1];
}

// for..in string indexer
for(const key2 in obj2) {
    () => obj2[key2];
}

// for..of
for (const s of ar) {
    () => s;
}
```

generates:

```js
// for..in number indexer
for (var key1 in obj1) {
    (function () { return obj1[key1]; });
}
// for..in string indexer
var _loop_1 = function (key2) {
    (function () { return obj2[key2]; });
};
for (var key2 in obj2) {
    _loop_1(key2);
}
// for..of
var _loop_2 = function (s) {
    (function () { return s; });
};
for (var _i = 0, ar_1 = ar; _i < ar_1.length; _i++) {
    var s = ar_1[_i];
    _loop_2(s);
}
```

**Comment by rbuckton** [comment]
It seems we are not checking the identifier `key1` above due to a shortcut for numeric property names in `checkIndexedAccess`, and as a result we never flag it as a block scoped variable.
