### ISSUE TITLE
Suggestion: Anonymous/Unnamed Modules

### ISSUE THREAD

**Issue by omidkrad** [microsoft/TypeScript#206]
> Suggestion moved over from [codeplex](https://typescript.codeplex.com/workitem/2424/).

I would like to suggest the following: Why not have anonymous/unnamed modules? The following code snippet totally makes sense for me to compile:

``` typescript
module {
  class Simple {

    constructor(public name: string) {}

    greet(who: string) {
      return "Greetings "+ who +", I'm "+ this.name +"!";
    }

    static main() {
      var s = new Simple('Flynn');
      console.log(s.greet("Program"));  
    }

  }

  Simple.main()
}
```

The generated code should be wrapped in a closure function and not cluttering the global scope.

``` typescript
(function () {

 // ...

})();
```

Also it would be nice to have a compiler option to put everything compiled in an anonymous module so that the global namespace is not cluttered.

The above snippet is with little modification from: https://gist.github.com/3916195

Thanks!

**Comment by NN---** [comment]
Just today I needed anonymous module and ended with __UniqueName__.

**Comment by svicalifornia** [comment]
@RyanCavanaugh What complexity does this add, really?

**Comment by danquirk** [comment]
This seems relevant to answer that: http://blogs.msdn.com/b/ericgu/archive/2004/01/12/57985.aspx

The issue is that it doesn't add much value on its own and it adds non-zero complexity that can't ever be removed.

**Comment by johnnyreilly** [comment]
Fascinating post @danquirk! - Thanks for sharing.

**Comment by rcollette** [comment]
@RyanCavanaugh - Have local types been implemented in 1.5-beta?   I'm trying 

```
(function(){
  class x{
    
  }
})()
```
And still getting `TS1129 statement expected.  class must be in a file or module context.

**Comment by danquirk** [comment]
@rcollette local types are not implemented at present. They're scheduled for 1.6: https://github.com/Microsoft/TypeScript/wiki/Roadmap

**Comment by jonathandturner** [comment]
Just to follow up - https://github.com/Microsoft/TypeScript/pull/3266, so this is now supported.

**Comment by johnnyreilly** [comment]
Awesome!

**Comment by omidkrad** [comment]
Fantastic!
