### ISSUE TITLE
Memory leak caused computer to restart. Opened projects no longer work.

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/TypeScript#20607]
**TypeScript Version:**  2.6.1
**Operating System:** Ubuntu 17.10 x64

I was browsing the internet, and all of a sudden a huge memory leak started to happen within a few seconds I could barely move the mouse. I had to do a hard restart (Hold the power button).

Once the computer restarted, the two projects I had open in `vscode`, no longer worked. Other projects that were not open still open and work properly.

I turned on verbose output and got this:

[tsserver.log](https://github.com/Microsoft/TypeScript/files/1546094/tsserver.log)
[ti-23536.log](https://github.com/Microsoft/TypeScript/files/1546095/ti-23536.log)

One thing I noticed is that it says no projects were found, but there are projects:

* src/client/tsconfig.json
* src/server/tsconfig.json

**Comment by TheColorRed** [comment]
I found the Issue:

1. Rename the `tsconfig.json` files to something else
2. Close the editor
3. Open the editor
4. Change the file names back to `tsconfig.json`

**Comment by TheColorRed** [comment]
This time I created a new file and the same issue started again. The above steps didn't work this time.

**Comment by TheColorRed** [comment]
I found out that my tsconfig.json file had an `include` path to an invalid location. Pointing to a proper location seemed to now fix the issue. 

If that was the root cause, there should be an error pointing that out, such as a decoration within the vscode editor...

**Comment by sheetalkamat** [comment]
@TheColorRed can you please share your tsconfig that referenced wrong file path. We have checks in place to not run into this exception, and have few tests as well for invalid input path locations in the tsconfig. Need more info to figure out what went wrong.

**Comment by TheColorRed** [comment]
This is the config that I am using. I don't know what the invalid include path was at the time of reporting this bug was though. I am going to assume it was `src/**/*.ts` though.

```json
{
  "compilerOptions": {
    "target": "es2017",
    "module": "commonjs",
    "removeComments": true,
    "strict": true,
    "outDir": "../../build",
    "noUnusedLocals": true,
    "noUnusedParameters": true
  },
  "include": [
    "**/*.ts"
  ]
}
```
