### ISSUE TITLE
unable to use npm package whose name ends with .ts for es2015 module system

### ISSUE THREAD

**Issue by emmanueltouzery** [Microsoft/TypeScript#20603]
**TypeScript Version:**  typescript@2.7.0-dev.20171209

**Code**

### index.ts
```ts
import * as preludets from "prelude.ts";
```

### package.json
```json
{
  "name": "dt",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "prelude.ts": "^0.4.4"
  }
}
```

### tsconfig.json
```json
{
  "compilerOptions": {
    "target": "esnext",
    "module": "es2015",
    "strict": true
  }
}
```

**Expected behavior:**

There is a package [prelude.ts](https://www.npmjs.com/package/prelude.ts) on npm (of which I'm the author), so this should work.

**Actual behavior:**

running `npm install && tsc` builds successfully if the module system is `commonjs`. However if the module system is `es2015` it fails with the error:

    index.ts(1,28): error TS2691: An import path cannot end with a '.ts' extension. Consider importing 'prelude' instead.

I would think that the `.ts` extension mean nothing to the underlying system (which should care only for `.js` and `.mjs` i guess?) and since npm accepts the package with a `.ts` postfix I guess typescript should allow it too, no matter the module system?
From my understanding typescript should first check whether there is a npm package by that name, and only check the form of the import if there is no such package?

**Comment by andy-ms** [comment]
Actually, the problem will happen for other packages (such as `abs`) with those settings.
You need to set [`"moduleResolution": "node"`](http://www.typescriptlang.org/docs/handbook/compiler-options.html).

**Comment by emmanueltouzery** [comment]
Hmm ok. I take it that npm package names ending with ".ts" are supported by typescript and not only for commonjs. Good to hear! Since you say the behaviour i saw is normal, i'm closing this bug. Thank you!
