### ISSUE TITLE
File sorting in virtual projects should respect numeric order

### ISSUE THREAD

**Issue by JsonFreeman** [Microsoft/TypeScript#2060]
If I have typescript files in a virutal project:
file1.ts, file2.ts, file10.ts

The solution explorer will order them in the following order
file1.ts
file10.ts
file2.ts

But it should use numeric ordering for the numeric part of the file name

**Comment by mhegazy** [comment]
The order is lexicographical similar to your file explorer on Windows. I would argue we should order them by reference to allow you some insight in the graph building process.

**Comment by JsonFreeman** [comment]
@CyrusNajmabadi has fixed this actually, on the VS side.
