### ISSUE TITLE
Support options in quick fixes/refactoring

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#20619]
We should support editor configuration of services behavior like we do for formatting.

Would fix:
* #18169
* #19019 (if there's no existing import to infer from)
* #19997
* We could prefer to create a namespace import instead of a named import for import completions and import fixes

**Comment by mjbvz** [comment]
As covered in #21768,  I see a lot of requests against VS Code for configuring quotes specifically. Cases where quotes should be configurable include:

- Imports
- Bracket accessors
- Implement interface / implement abstract class or method
- Others?

**Comment by mhegazy** [comment]
Should also address:

- https://github.com/Microsoft/TypeScript/issues/19882
- https://github.com/Microsoft/TypeScript/issues/18169
- https://github.com/Microsoft/TypeScript/issues/20161
- https://github.com/Microsoft/TypeScript/issues/18780
- https://github.com/Microsoft/TypeScript/issues/13270

**Comment by aleksey-bykov** [comment]
please add an option to always use absolute paths (relative to baseUri) for imports at completions, per: https://github.com/Microsoft/TypeScript/issues/21860

**Comment by srcspider** [comment]
+1

If possible I would like an option to NEVER even see the relative path suggestions; or spaghetti imports as I like to think of them.

**Comment by srcspider** [comment]
@mjbvz please add an option to omit the semicolon on import statements

**Comment by alextreppass** [comment]
Thanks - please consider https://github.com/Microsoft/TypeScript/issues/22249 to allow the old behaviour of full import paths (rather than `../../`...)

**Comment by aleksey-bykov** [comment]
how did it even come to mind to make relatives paths a default choice? what makes the design team think they are more convenient?

![Relative vs Absolute](https://user-images.githubusercontent.com/937933/36927959-4a213b20-1e4f-11e8-8ea6-d195b0587cb3.png)

**Comment by mhegazy** [comment]
With https://github.com/Microsoft/TypeScript/pull/22236 added, we can add a configuration. We would be happy to take a PR for this.

**Comment by srcspider** [comment]
@andy-ms why did you label this "Fixed"? What's the fix?

**Comment by mhegazy** [comment]
The fix went in https://github.com/Microsoft/TypeScript/pull/22236. It is scheduled to release in Typescript 2.8 (added to the road-map).

VSCode /VS still need to expose these settings in a way you can interact with. https://github.com/Microsoft/vscode/issues/45948 is a good issue to watch for VSCode.

**Comment by mhegazy** [comment]
For posterity, 
- Semicolon in quickfixes and refactorings tracked by https://github.com/Microsoft/TypeScript/issues/19882, https://github.com/Microsoft/TypeScript/issues/18780 and https://github.com/Microsoft/TypeScript/issues/20161
- Configure relative vs non-relative path in imports in quickfixes and completion tracked by  https://github.com/Microsoft/TypeScript/issues/21860 and https://github.com/Microsoft/TypeScript/issues/20161
- Additional arguments to npm for installing missing `@types` packages tracked by https://github.com/Microsoft/TypeScript/issues/19997
