### ISSUE TITLE
Undecipherable error at visitImportEqualsDeclaration

### ISSUE THREAD

**Issue by brian428** [Microsoft/TypeScript#20611]
**TypeScript Version:**  2.6.2

**Expected behavior:** If something is wrong, TS should give some information on what is causing the error.

**Actual behavior:** Using TypeScript 2.6.2 with an Angular 5 AoT build, I'm getting the following undecipherable error:
```
Error: Error: Debug Failure. False expression: import= for internal module references should be handled in an earlier transformer.
    at visitImportEqualsDeclaration (C:\Developer\Projects\BAH\medusa\ui\node_modules\typescript\lib\typescript.js:63184:22)
    at sourceElementVisitor (C:\Developer\Projects\BAH\medusa\ui\node_modules\typescript\lib\typescript.js:62959:28)
```

Obviously, I have no idea what this means, and I have no way to even start trying to determine what code might be causing this. This project built fine under Angular 4, so I assume it's related to moving to Angular 5. But again, since the error gives no context at all, I have no way to try and determine the cause. Could this be changed to output a file name, a dump of the relevant code...anything that would at least give some pointer to the cause of the error?

**Comment by DanielRosenwasser** [comment]
We understand the cause of the message (basically an import alias was either not rewritten in our emit pipeline, or was inappropriately generated by an earlier AST transform), but it's not clear if it's a problem with Angular's AOT emit or something about our transform API. I'll also note that Angular 5's supported TypeScript version is 2.4.2, so it might just be a matter of version incompatibility. 

One other thing I'll note is we can't do much without a minimal repro of the issue.

**Comment by brian428** [comment]
Thanks, Daniel. You may be right about the TS version. I'll see if I can try it with an older TS version. 

Ideally I'd also prefer to create a repro of the issue, but this is a 30,000+ line application, and with absolutely no clue of what the cause is, it's going to be extremely difficult to try and narrow it down to a repro case. Again, if the error gave _any_ indication of the source, I might be able to investigate further. But without some starting point, I'm not sure what I can do. So even if it's a TS version issue in this case, I'd still say it would be a good idea for errors like this to provide some additional context?
