### ISSUE TITLE
Inconsistent treatment of primitive values in Object type

### ISSUE THREAD

**Issue by TPReal** [Microsoft/TypeScript#20614]
**TypeScript Version:**  2.6

**Code**
```ts
const q: Object = 5;
if (typeof (q) !== 'object') {
    let w = q;
    w = 5;
}
```

**Expected behavior:**
Should compile.

**Actual behavior:**
Type `Object` means "anything that has properties", so numbers or strings or booleans are all assignable to `Object`. But at the same time it is assumed that `typeof(q)` is always `'object'`, which is wrong, as it can be `'string'` or `'boolean'` for example. The code above doesn't compile because `w` has inferred type `never`.

**Comment by kitsonk** [comment]
When ever you are explicit about a type, TypeScript trusts you know what you are doing.  When you eliminate the type `object` from the variable `q`, TypeScript eliminates those from the explicit type, and is left with nothing.  If you lie to TypeScript, TypeScript allows you to lie and then follows its rules from that point.

The type `Object` is a bad choice for a type in TypeScript anyways, as `object` is a better type.

**Comment by TPReal** [comment]
I agree in general with your statement about lying, but I don't agree that I lie in this example. A lie would be for example `const x: number = 'x' as any;`. Here I assign a number to variable of type `Object` without any casts or anything and it compiles, so my understanding is that this type is defined in such a way that it just accepts those values. In other words, `5` is a value of type `Object` apparently. So TypeScript's assumption that `typeof` a value of type `Object` is always `'object'` is incorrect.

So if I want a type that is _really any_, but without the behaviour of `any` that allows dereferencing any keys etc, I need to write `object | string | number | boolean | null | undefined` and maybe some more. I hoped to just use `Object | undefined | null` but apparently this fails in the way described above.

**Comment by andy-ms** [comment]
Yeah, there's a difference between `object` and `Object`. `object` includes primitives so we shouldn't be narrowing to `never` in this case:
```ts
function f(q: Object) {
    if (typeof (q) !== 'object') {
        q; // Not impossible! But TS thinks it is
    }
}
f(5); // No error
```

**Comment by mhegazy** [comment]
type of `w` in the OP is `never`. the error seems to make sense to me as well.

**Comment by andy-ms** [comment]
Is this a more convincing example?
```ts
function toString(a: {}) {
	return typeof a === "object" ? "[Object object]" : a.toString();
}
```
I would expect no compile error -- instead I get `src/a.ts(2,55): error TS2339: Property 'toString' does not exist on type 'never'.`.

**Comment by TPReal** [comment]
@mhegazy you are wrong. We have to agree on definitions. What is the definition of `Object`? I don't know what is the formal definition of this type, but it is easy to discover it: I can write `const q: number = 'a'` and read the compiler error to learn that `'a'` is not a number in TypeScript. Similarly, I can learn that `'a'` is not an `object`. And the same way I can learn that `'a'` _is_ an `Object`. I don't do any `as` casts or anything fishy, I just write `const q: Object = 'a'`, and this compiles, which _proves_ that `'a'` is of type `Object`, according to TypeScript's typing mechanics. That's fine. The same way I can learn that `5` or `true` are `Object`s.

So apparently, according to TypeScript, **type `Object` includes also numbers, strings and booleans, and also functions and objects**. Would you argue with this statement?

If you don't agree with the statement in bold then how can you explain that I can assign `5` to a variable of type `Object` without any compiler issues? Then _this_ needs to be fixed. But the fact that `5` is an `Object` is very clear, I can also write:
```
declare const q: 5;
const w: Object = q;
```

If you agree with the statement in bold then it is instantly obvious that `typeof a` (where `a: Object`) could have many values, not only `object`, and then reducing to `never` in my original example is wrong.

Again, as I say, we need to agree on definitions. And the definition of `Object` in TypeScript apparently includes not only `object`s, but also numbers, strings, functions and more. But not null or undefined. If you don't agree with this definition then tell me what is the correct one.

**Comment by RyanCavanaugh** [comment]
@TPReal the type of Object is plainly defined: It's any value that has the properties of Object, for example `hasOwnProperty`

![image](https://user-images.githubusercontent.com/6685088/38747869-2569ecfa-3f01-11e8-9e48-735c6dac784e.png)

The type of `object`, the lower-case type, is the type of non-primitives.

**Comment by RyanCavanaugh** [comment]
No. For example, `{ hasOwnProperty: 5 }` is `object` but isn't `Object`

**Comment by DanielRosenwasser** [comment]
Specifically, `object` is closer to

`{} - (number | string | boolean | symbol)`

**Comment by jack-williams** [comment]
Ryan's comment was actually completely clear, I just took for granted the fact it is possible to create an object that violates the property types of `Object`.

Does this mean that subtyping is not transitive?
- `number <: Object`
- `Object <: object`
- but not `number <: object`

**Comment by DanielRosenwasser** [comment]
>Does this mean that subtyping is not transitive?

Yup, exactly through your example.

**Comment by TPReal** [comment]
The analysis about how being a subtype is not transitive is interesting, but the original issue is still unresolved. Type `Object` or `{}` includes primitive types like `number` but type guard of `typeof` ignores this fact.
