### ISSUE TITLE
Intellisense doesn't suggest inherited members in classes when properties don't end with ';'

### ISSUE THREAD

**Issue by alexrock** [Microsoft/TypeScript#20627]
**TypeScript Version:**  2.7.0-dev.20171209

**Code**

```ts
class A {
    aa: number
    bb: string
}

class B extends A {
    aa = 0
    // <- Intellisense doesn't show inherited members when I press a key or ctrl-space
}
```

**Expected behavior:**
Show inherited members
**Actual behavior:**
Only shows inherited members if the previous line (a property) is terminated with `;`
Show globals

**Comment by RyanCavanaugh** [comment]
We don't know that the prior line isn't completed yet, so the correct completion context is still the initializing expression's. You could validly write a keyword like `instanceof` here, for example.

**Comment by alexrock** [comment]
@RyanCavanaugh - I understood, thanks.
