### ISSUE TITLE
Code Helper using ~100% CPU

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#20630]
_From @coreh on December 9, 2017 0:26_

- VSCode Version: 1.18.1
- OS Version: 10.12.6

I'm getting "Code Helper" stuck at ~100% CPU

<img width="815" alt="screen shot 2017-12-08 at 22 18 24" src="https://user-images.githubusercontent.com/418473/33790326-67568234-dc66-11e7-804a-17e67186907f.png">

```
ps a~ $ ps aux | grep 65462
coreh            65462 100.0  1.7  3492052 281544   ??  R     5:33PM 128:06.61 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/out/utils/electronForkStart.js /Users/coreh/Projects/zimboli/node_modules/typescript/lib/tsserver.js --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName /var/folders/m1/vk9trwwj3pz25vv0_jt7xtsc0000gn/T/vscode-tscancellation-da48568b3a6dd7891de0.sock* --locale en
```

Steps to Reproduce:

1. Use VS Code for a suficiently long time (say, several hours) on a large enough project.
2. A "Code Helper" process will start to use 100% CPU. Quitting VSCode does not terminate the Code Helper process, it needs to be killed from the Activity Monitor

Reproduces without extensions: _Probably_ not (?)
(It doesn't trigger immediately, or consistently, but rather after several hours using the App, and I haven't been able to conclude if it will not trigger without extensions. However the `ps` output seems to indicate that the offending file is `/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/out/utils/electronForkStart.js`, so it's the built in TypeScript extension?)

Thanks in advance!

_Copied from original issue: Microsoft/vscode#39949_

**Comment by mjbvz** [comment]
_From @bestvow on December 9, 2017 2:20_

igore files such as 
`/**/node_modules`

**Comment by mjbvz** [comment]
_From @coreh on December 11, 2017 12:0_

@bestvow Wouldn't that break type checks, autocomplete and "Jump to Definition" for the modules within `node_modules`?

**Comment by mjbvz** [comment]
_From @bestvow on December 11, 2017 13:36_

@coreh Would you like to show me your extensions?

**Comment by mjbvz** [comment]
@coreh Do you have a `jsconfig` or `tsconfig`? If so, can you please share it. 

Also, please try downloading [VS Code insiders](https://code.visualstudio.com/insiders/) and opening the workspace. Then, from the command line, run `code-insiders --status`. This should print some generic information about your workspace that can help us track down what is going wrong

**Comment by coreh** [comment]
Here's my `tsconfig.json`:

```json
{
    "compilerOptions": {
        "outDir": "./build/",
        "sourceMap": true,
        "module": "commonjs",
        "target": "es5",
        "jsx": "react",
        "allowJs": true,
        "moduleResolution": "node",
        "strictNullChecks": true,
        "noImplicitAny": true,
        "baseUrl": ".",
        "downlevelIteration": true,
        "lib": [
            "dom",
            "dom.iterable",
            "es2016"
        ],
        "paths": {
            "common": [
                "client/common"
            ],
            "common/native": [
                "client/common/native"
            ],
            "components": [
                "client/components"
            ],
            "pages": [
                "client/pages"
            ],
            "state": [
                "client/state"
            ],
            "static": [
                "static"
            ],
            "react-phone-number-input": [
                "types/react-phone-number-input"
            ],
            "@yfuks/react-native-action-sheet": [
                "types/react-native-action-sheet"
            ],
            "exenv": [
                "types/exenv"
            ],
            "accept-language-parser": [
                "types/accept-language-parser"
            ],
            "react-masonry-infinite": [
                "types/react-masonry-infinite"
            ],
            "react-gateway": [
                "types/react-gateway"
            ],
            "slugify": [
                "types/slugify"
            ]
        },
        "skipLibCheck": true,
        "newLine": "LF"
    }
}
```

As soon as I get back home I'll install Insiders and try running that command. I must run that with my project already open, correct?

**Comment by fulvaz** [comment]
Uninstalling the TSlint plugin may help.

Now i get a quiet and cool mac : )

**Comment by mhegazy** [comment]
seems like a tslint issue then. i suggest filing it against the tslint extension instead.
