### ISSUE TITLE
Typescript compiles not needed/required source

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/TypeScript#20632]
TS 2.6.2, there are three files in dir:

interface.ts:
```ts
    export interface Env {
    	x: string
    }
```
index.ts:
```ts
    import {Env} from './interface' // imports only interface
    
    const env: Env = {x: '1'}
    
    console.log(env.x)
```
tsconfig.json:
```json
    {
      "include": [
    	"index.ts"
      ]
    }
```

I do compilation: `tsc --outDir ./out`, in out dir I see:

    index.js
    inteface.js

(If I remove `import {Env} from './interface'` from `index`, I will see only `index.js`)

I wonder why TSC is compiling in JS `interface.js` if `index.ts` imported only interface from `interface.ts` it not JS CODE?

**Comment by RyanCavanaugh** [comment]
Consider the case where you previously had imperative code with side effects in `interface.ts`, built it, then removed all the non-interface code. The previous .js file would be "left behind", imported, and run. That would be bad.

**Comment by whitecolor** [comment]
Hm didn't think about code just running on import. Thanks.
