### ISSUE TITLE
Wrong signatures for optional arguments of Array.map

### ISSUE THREAD

**Issue by antishov** [Microsoft/TypeScript#20633]
**TypeScript Version:**  2.6.2

**Code**

```ts
const members = { 1: 'test', 2: 'second test' };

Object.keys(members)
    .map((key: number) => members[key]);
```

**Expected behavior:**
Code is valid: only the first argument of `map` function is used, which required.

**Actual behavior:**
Code invalid: tsl asks to define all arguments of `map` function (optional too: `index`, `array`).

**Comment by RyanCavanaugh** [comment]
The error is that `Object.keys` returns an array of strings (this is a true fact, try it) and you're passing a callback that accepts a number (`key`).
