### ISSUE TITLE
Cannot use index signature of default export from wildcard module

### ISSUE THREAD

**Issue by UselessPickles** [Microsoft/TypeScript#20637]
**TypeScript Version:**  2.6.2

**Code**

***json-module.d.ts***
```ts
// Allows json files to be imported as a module
declare module "*.json" {
    import {JSONObject} from "src/json";
    const value: JSONObject;
    export default value;
}
```

***json.ts***
```ts
/**
 * Type declarations and utilities for working with JSON-compatible data structures.
 * @module
 */

/**
 * Any primitive data type that is allowed in JSON.
 */
export type JSONPrimitive = string | number | boolean | null;

/**
 * Any value data type allowed in JSON (primitives, arrays, and objects).
 */
export type JSONValue = JSONPrimitive | JSONArray | JSONObject;

/**
 * An array of data types allowed in JSON.
 */
export interface JSONArray extends Array<JSONValue> {
}

/**
 * An object whose properties are of types allowed in JSON.
 */
export interface JSONObject {
    [name: string]: JSONValue;
}
```

Example usage:
```ts
import * as jsonData from "someFile.json";

// compiler error on the following line
const someValue = jsonData["aPropertyName"]; 
```

**Expected behavior:**
I should be able to use the imported value from my JSON file as a `JSONObject`, indexing into its properties without compiler errors.

**Actual behavior:**
Compiler error where I attempt to index into the properties of my JSONObject:
`error TS7017: Element implicitly has an 'any' type because type 'typeof "*.json"' has no index signature.`

**Comment by UselessPickles** [comment]
The following hack allows me to use the imported JSON as desired:

```ts
import * as jsonData_ from "someFile.json";

// Assigning the import to an explicitly typed const is fine; so the compiler understands here that
// the import value is of type JSONData.
const jsonData: JSONObject = jsonData_;

// Now this works without compiler errors.
const someValue = jsonData["aPropertyName"]; 
```

**Comment by Kovensky** [comment]
That is because, on your declaration, you were very specific that the only export is a `default` export. There is no index signature on ES Module exports.

You need to change your import from `import * as jsonData from` into `import jsonData from`.

**Comment by andy-ms** [comment]
Alternatively, use `export =` instead of `export default`, and `import jsonData = require("someFile.json")`.

**Comment by UselessPickles** [comment]
Thanks for the responses. It seems so obvious now that the way I'm importing `*`, but exporting a single default, is inconsistent.

But can anyone explain why my `jsonData` import in my example seems to have an identity crisis? Why does the compiler believe it *is* of type JSONObject (which has an index signature), but that it also does *not* have an index signature because of the way it was imported? In every other way that I use `jsonData`, it works as type JSONObject... as long as I don't try to use the index operator.

Regardless of the fact that I was doing it wrong, it still seems like there's an inconsistency in the behavior of my example.

**Comment by andy-ms** [comment]
The compiler doesn't actually believe that `jsonData` is of type `JSONObject`. If you write `const x = jsonData;` and hover over `x` you'll see it says `typeof jsonData`. If you try writing `jsonData.` you'll only get completions for `default`.
It is *assignable* to `JSONObject` though, because the type `{ default: JSONObject }` is assignable to `JSONObject` since every value in that type is a `JSONValue`.

**Comment by UselessPickles** [comment]
I figured it out!

The key was to start by looking at how webpack (what I'm using for module loading, etc.) generates modules for JSON files, declare my "*.json" module to match, and use an import style that matches. 

The built-in JSON loader for webpack creates a module in the form of:
```js
module.exports = {/* the JSON object from the file */};
```

To match the way the webpack loader generates the module, I declare my "*.json" module as:

```ts
declare module "*.json" {
    import {JSONObject} from "src/json";
    const value: JSONObject;
    export = value;
}
```

And then import JSON like this:
```ts
    import * as jsonData from "someFile.json";
```

I guess this is a good lesson that the structure of an external non-typescript module is what dictates how corresponding TS declarations must be defined, and therefore dictates how the module must be imported.

**Comment by UselessPickles** [comment]
@andy-ms 
> It is assignable to a JSONObject variable though, because the type { default: JSONObject } is assignable to JSONObject, since every property value in that type is a JSONValue.

Thanks for the clarification. I see now where I got confused :)

**Comment by UselessPickles** [comment]
Part of my confusion was that my initial setup was working correctly at runtime. Now I understand that it's because the style of my import matched the structure of the actual module that was being generated by webpack. It was only my TS declaration that didn't match, and was causing compile-time confusion under certain conditions. 

The fact that the incorrect TS declaration of the module combined with my import style to produce something that was *assignable* to JSONObject (unfortunate coincidence) was an additional red herring. The end result was that it seemed to "mostly work", unless I tried to directly use the import as a JSONObject.
