### ISSUE TITLE
Wrong signatures for the third arg of Array.map

### ISSUE THREAD

**Issue by antishov** [Microsoft/TypeScript#20634]
**TypeScript Version:**  2.6.2

**Code**

```ts
const members = { 1: true, 2: false };

Object.keys(members)
    .map((value: string, key: number, array: boolean[]) => members[value]);
```

**Expected behavior:**
Code is valid.

**Actual behavior:**
Code is invalid. As we can see on [MDN Array.map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map), the third argument of callback-function can be an array of any possible values, but with current signatures tsl returns an error, cause it expects that the third argument of callback will be an array of strings;
` TS2345: Argument of type '(key: number) => any' is not assignable to parameter of type '(value: string, index: number, array: string[]) => any'.
  Types of parameters 'key' and 'value' are incompatible.
    Type 'string' is not assignable to type 'number'.`

**Comment by RyanCavanaugh** [comment]
This is a correct error (though the error you've posted doesn't match the code you've posted?).

The `array` argument will *definitely* be an array of strings at runtime. It is *not* an array of `boolean`s or `number`s.
