### ISSUE TITLE
strict function type does not handle spread arguments

### ISSUE THREAD

**Issue by beckend** [Microsoft/TypeScript#20645]
**TypeScript Version:**  2.7.0-dev.20171212 and 2.6.2

**Code**

```ts
class TargetComponent {

  public one: any;
  public two: any;

  constructor(one: any, two: any) {
    this.one = one;
    this.two = two;
  }

}

class ComponentExt extends TargetComponent {

  constructor(...args: any[]) {
    // Expected 2 arguments, but got 0 or more.
    super(...args);
  }

}
```

**Expected behavior:**
No errors.

**Actual behavior:**
at Super => Expected 2 arguments, but got 0 or more.

**Comment by andy-ms** [comment]
This isn't a `--strictFunctionTypes` error.
It *will* work if the constructor were defined as `one?: any, two?: any`. The problem is that with an arbitrary array, we can't be sure it has isn't empty, so we can't know that both arguments are provided. See #15849.

**Comment by beckend** [comment]
Alright, you are saying this valid javascript is not accepted in typescript in strict mode? And also that it is a feature?

**Comment by RyanCavanaugh** [comment]
https://stackoverflow.com/questions/41750390/what-does-all-legal-javascript-is-legal-typescript-mean

**Comment by beckend** [comment]
The code was more of a demonstration, of course the point with that constructor was to make something happen, and in many cases you don't really need to care about the arguments and thus you use spread operator. The demonstration might as well be proxying two functions and it would produce the same error.

But so far I get that this is indeed intentional from typescript and this was actually a aware decision you made...which bring this issue to it's conclusion so you can close this at your discretion.
