### ISSUE TITLE
Consider annotations and compilation of .json files

### ISSUE THREAD

**Issue by NoelAbrahams** [microsoft/TypeScript#2064]
**Motivation**

The shape of JSON stored in files can be validated using [JSON schema](http://json-schema.org/). However, JSON schema cannot be used to ensure the stored JSON corresponds to a specific TypeScript interface.

Understandably, most JSON tends to be stored in databases. However, there are many cases where small documents are stored on the file system in order to permit quick editing. Two common examples are config and resource files. The JSON in these files is loaded at runtime and accessed by JavaScript code, thereby necessitating they correspond to specific TypeScript interfaces.

We have a small but significant use case for this scenario.

**Proposal**

Interface declarations file `user.d.ts` 

``` TypeScript
declare module user {

     interface Address {
           house: number;
           street: string;
    }

    interface User  {
          name: string;
          address:Address;
          age: number;
    }
}
```

TypeScript JSON file `user.json.ts`

``` typescript
/// <reference path="user.d.ts" />
user.User: {            <----------- Annotation
   "name": "Joe Bloggs", /*Comment*/    // Permit comments
   "address": {
       "house": "1", // Error: Number expected
       street: "London"  // Error: Names must be quoted
    },
   "age": 55     // Error: Missing comma
    "id": 101 // Error: Invalid property
}
```

Compiled output (after errors are corrected): File `user.json`

``` typescript
{
   "name": "Joe Bloggs",
   "address": {
       "house": 1
       "street": "London"
    },
   "age": 55    
}
```

**Comment by ahejlsberg** [comment]
This is an idea we've discussed before and I think it has a lot of merit. I would propose that the type name be specified as part of the `/// <reference/>` comment so that the core JSON syntax doesn't have to be extended. For example:
```typescript
/// <reference path="user.d.ts" type="user.User"/>
{
    "name": "Joe Bloggs",
    ...
}
```
A number of JSON processing tools already tolerate comments (but definitely wouldn't tolerate actual identifiers before the object literal).

**Comment by ahejlsberg** [comment]
I should clarify... The thing I find useful here is the type checking and associated IDE services such as statement completion. I'm less sure about producing "corrected" output.

**Comment by NoelAbrahams** [comment]
@ahejlsberg, no I meant "after the user has corrected the errors", not for the compiler to correct it.

If I understand you correctly, with the `/// <reference/>` option, just dropping that into an existing `.json` file would cause the compiler to include it in the compilation run.

This is cleaner than having to generate emit, but would require stripping out the `/// <reference/>` manually. Furthermore, one cannot simply `require` the file in node. 

```typescript
var json = require('user.json');  // SyntaxError: user.json:  Unexpected token /

```

I like the idea of adding the annotation in the `reference`, but would like `user.json.ts` to emit `user.json`.

**Comment by duanyao** [comment]
Currently I use type assertion syntax to enforce type check on a object literal:

```
<user.User>{
   "name": "Joe Bloggs",
   "address": {
       "house": 1,
       "street": "London",
    },
   "age": 55    
}
```
Is this what you want?

**Comment by NoelAbrahams** [comment]
@duanyao, that is not valid syntax in a `.json` file.

**Comment by duanyao** [comment]
After compilation, it is a valid json. You presented an example of `user.json.ts`, and was compiled to `user.json`. Did I miss something?

**Comment by NoelAbrahams** [comment]
Are you suggesting that as an alternative syntax? It's not clear from the statement "Is that what you want?"

The problem with the type assertion syntax is that here we are attempting to annotate JSON - not coerce it into something.

**Comment by duanyao** [comment]
No. I suggest that you write `.json.ts` files in TS (of cause), and compile them to `.json` files.

**Comment by NoelAbrahams** [comment]
In that case there is nothing new being suggested.

**Comment by duanyao** [comment]
Why need something new if existing tools can solve the problem? Or are there problems I overlooked?

**Comment by NoelAbrahams** [comment]
A JSON file is not equivalent to a JavaScript file. There is no top-level variable. That's probably what you're missing.

**Comment by duanyao** [comment]
Top-level variable is not the issue. I just tested tsc:

```javascript
<user.User>{
   "name": "Joe Bloggs",
   "address": {
       "house": 1,
       "street": "London",
    },
   "age": 55    
}
```

was compiled into

```javascript
{
    "name": "Joe Bloggs",
    "address": {
        "house": 1,
        "street": "London"
    },
    "age": 55
};
```
You see, the only problem is the trailing `;`. I think tsc can be improved to support a "json mode" to remove these artifact.

**Comment by NoelAbrahams** [comment]
That's interesting. But still won't do. JSON is a subset of JavaScript and things that are permissible in JavaScript is not valid JSON.

```
<any>{
   'name': 'Joe Bloggs', // e.g. single quotes
   'bar': () => 10
}
```

**Comment by duanyao** [comment]
These format issues should also be addressed by "json mode" of tsc. Data type issues like `() => 10` can be caught by the type assertion or "json mode".

**Comment by NoelAbrahams** [comment]
Like I said there is nothing new being suggested.

**Comment by NoelAbrahams** [comment]
@mhegazy, @RyanCavanaugh any chance of adding this to the discussion list?

**Comment by NoelAbrahams** [comment]
Hi, guys, is this on the radar?

**Comment by mhegazy** [comment]
We have not discussed this in a while. I believe we still need a detailed proposal of how this can be accomplished. 

One other issue that seems more appealing is https://github.com/Microsoft/TypeScript/issues/7071, this requires no annotation, it just allows the compiler to load these files and infer their types. you would get an error if you were to assign the contents of the file to a variable of an unmatching type. obviously this only works for node, so that might not be what you are looking for.

**Comment by NoelAbrahams** [comment]
@mhegazy, #7071 is a special case that unfortunately doesn't make things any better from our perspective.

The use-case I outlined is to do with loading JSON resources via HTTP and using them on a client application. We just want to ensure the types used in the client correspond to the JSON file stored on the server. I'd say this is a common requirement.

The only way I can think of to accomplish this at the moment is to have a new file type `foo.json.ts` and have the compiler emit `foo.json` as outlined above.

**Comment by RyanCavanaugh** [comment]
I think the use case here is well-handled by a few things now:
 * JSDoc type annotations in JS files
 * `import` of json "works" as "expected" now (with a smaller inference surface)
 * io-ts exists

Given lack of other feedback here, I don't see us proceeding anytime soon.
