### ISSUE TITLE
Generics: Function's template param inferred in unexpected way

### ISSUE THREAD

**Issue by UselessPickles** [Microsoft/TypeScript#20643]
**TypeScript Version:**  2.6.2

**Code**

```ts
// visitor interface for visiting possible values of a string literal type
type StringVisitor<S extends string> = {
    [P in S]: (value: P) => void;
}

function visitString<S extends string>(value: S, visitor: StringVisitor<S>): void {
    visitor[value](value);
}


// visitor interface for visiting possible values of a string literal type, or null/undefined
type NullableStringVisitor<S extends string> = {
    handleNullOrUndefined: (value: null | undefined) => void;
} & StringVisitor<S>

function visitNullableString<S extends string>(
    value: S | null | undefined, 
    visitor: NullableStringVisitor<S>
): void {
    if (value == null) {
        visitor.handleNullOrUndefined(value);
    } else {
        visitString(value, visitor);
    }
}

// example string literal type
type RGB = "red" | "green" | "blue";

function getRGBValue(): RGB | null {
    return "green";
}

// example shared handler used for multiple values in the RGB visitor implementation
function handleUnsupportedValue(value: RGB | null | undefined): void {
    alert('Unsupported value: ${value}');
}

visitNullableString(getRGBValue(), {
    // Compiler error caused here:
    // Types of property 'handleNullOrUndefined' are incompatible.
    // Type '(value: "red" | "green" | "blue" | null | undefined) => void' is not assignable 
    // to type '(value: "handleNullOrUndefined") => void'
    handleNullOrUndefined: handleUnsupportedValue,

    "red": handleUnsupportedValue,

    "green": () => {
        alert("green!");
    },

    "blue": () => {
        alert("blue!");
    }
});
```

**Expected behavior:**
In the call to `visitNullableString`, type `S` should be *directly* inferred from param `value` as `"red" | "green" | "blue"`, and the expected type of `handleNullOrUndefined` on `visitor` should be `(value: null | undefined) => void`, because `visitor` should be of type `NullableStringVisitor<"red" | "green" | "blue">`.

**Actual behavior:**
Type `S` is *indirectly* inferred from param `visitor` as `"red" | "green" | "blue" | "handleNullOrUndefined"`, based on the names of all properties in the visitor implementation. The compiler then complains about incompatible types on `handleNullOrUndefined`, because the implementation does not accept the string literal type `"handleNullOrUndefined"`.

**Workaround**
If I explicitly provide the template param, then it works as desired:
```ts
visitNullableString<RGB>(getRGBValue(), {
    // No compiler error
    handleNullOrUndefined: handleUnsupportedValue,

    "red": handleUnsupportedValue,

    "green": () => {
        alert("green!");
    },

    "blue": () => {
        alert("blue!");
    }
});
```

**Comment by aminpaks** [comment]
Not sure what you're trying to accomplish, but does [this help](http://www.typescriptlang.org/play/index.html#src=%2F%2F%20example%20string%20literal%20type%0D%0Atype%20RGB%20%3D%20%22red%22%20%7C%20%22green%22%20%7C%20%22blue%22%3B%0D%0A%0D%0A%0D%0A%2F%2F%20visitor%20interface%20for%20visiting%20possible%20values%20of%20a%20string%20literal%20type%0D%0Atype%20StringVisitor%3CS%20extends%20RGB%3E%20%3D%20%7B%0D%0A%20%20%20%20%5BP%20in%20S%5D%3A%20(value%3A%20P)%20%3D%3E%20void%3B%0D%0A%7D%0D%0A%0D%0Afunction%20visitString%3CS%20extends%20string%3E(value%3A%20S%2C%20visitor%3A%20StringVisitor%3CS%3E)%3A%20void%20%7B%0D%0A%20%20%20%20visitor%5Bvalue%5D(value)%3B%0D%0A%7D%0D%0A%0D%0A%0D%0A%2F%2F%20visitor%20interface%20for%20visiting%20possible%20values%20of%20a%20string%20literal%20type%2C%20or%20null%2Fundefined%0D%0Atype%20NullableStringVisitor%3CS%20extends%20RGB%3E%20%3D%20%7B%0D%0A%20%20%20%20handleNullOrUndefined%3A%20(value%3A%20null%20%7C%20undefined)%20%3D%3E%20void%3B%0D%0A%7D%20%26%20StringVisitor%3CS%3E%0D%0A%0D%0Afunction%20visitNullableString%3CS%20extends%20RGB%3E(%0D%0A%20%20%20%20value%3A%20S%20%7C%20null%20%7C%20undefined%2C%20%0D%0A%20%20%20%20visitor%3A%20NullableStringVisitor%3CS%3E%0D%0A)%3A%20void%20%7B%0D%0A%20%20%20%20if%20(value%20%3D%3D%20null)%20%7B%0D%0A%20%20%20%20%20%20%20%20visitor.handleNullOrUndefined(value)%3B%0D%0A%20%20%20%20%7D%20else%20%7B%0D%0A%20%20%20%20%20%20%20%20visitString(value%2C%20visitor)%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Afunction%20getRGBValue()%3A%20RGB%20%7C%20null%20%7B%0D%0A%20%20%20%20return%20%22green%22%3B%0D%0A%7D%0D%0A%0D%0A%2F%2F%20example%20shared%20handler%20used%20for%20multiple%20values%20in%20the%20RGB%20visitor%20implementation%0D%0Afunction%20handleUnsupportedValue(value%3A%20RGB%20%7C%20null%20%7C%20undefined)%3A%20void%20%7B%0D%0A%20%20%20%20alert('Unsupported%20value%3A%20%24%7Bvalue%7D')%3B%0D%0A%7D%0D%0A%0D%0AvisitNullableString(getRGBValue()%2C%20%7B%0D%0A%20%20%20%20%2F%2F%20Compiler%20error%20caused%20here%3A%0D%0A%20%20%20%20%2F%2F%20Types%20of%20property%20'handleNullOrUndefined'%20are%20incompatible.%0D%0A%20%20%20%20%2F%2F%20Type%20'(value%3A%20%22red%22%20%7C%20%22green%22%20%7C%20%22blue%22%20%7C%20null%20%7C%20undefined)%20%3D%3E%20void'%20is%20not%20assignable%20%0D%0A%20%20%20%20%2F%2F%20to%20type%20'(value%3A%20%22handleNullOrUndefined%22)%20%3D%3E%20void'%0D%0A%20%20%20%20handleNullOrUndefined%3A%20handleUnsupportedValue%2C%0D%0A%0D%0A%20%20%20%20%22red%22%3A%20handleUnsupportedValue%2C%0D%0A%0D%0A%20%20%20%20%22green%22%3A%20()%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20alert(%22green!%22)%3B%0D%0A%20%20%20%20%7D%2C%0D%0A%0D%0A%20%20%20%20%22blue%22%3A%20()%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20alert(%22blue!%22)%3B%0D%0A%20%20%20%20%7D%0D%0A%7D)%3B)?

**Comment by RyanCavanaugh** [comment]
This could be solved by either subtraction types (#4183), or noninferential type parameters (#14829). As is, this is the intended behavior because the intersection type is a lower-priority inference site than the object literal's.

**Comment by UselessPickles** [comment]
@RyanCavanaugh Could you provide an example of how I would use type subtraction to get the behavior I want? This is my initial guess:
```ts
function visitNullableString<S extends (string - "handleNullOrUndefined")>(
    value: S | null | undefined, 
    visitor: NullableStringVisitor<S>
): void
```

The non-inferred type parameter solution is more obvious:
```ts
function visitNullableString<S extends string>(
    value: S | null | undefined, 
    visitor: NullableStringVisitor<NoInfer<S>>
): void
```

**Comment by UselessPickles** [comment]
SOLUTION!!! (hack???)

```ts
type NoInfer<T> = T & {[K in keyof T]: T[K]};

function visitNullableString<S extends string>(
    value: S | null | undefined, 
    visitor: NullableStringVisitor<NoInfer<S>>
): void
```

Thanks to this comment for the `NoInfer<T>` implementation: https://github.com/Microsoft/TypeScript/issues/14829#issuecomment-322267089

**Comment by UselessPickles** [comment]
Follow up on the previous hack: it's good enough to give me something functional for now, but it would be much more useful if I could prevent inferring the type of `visitor` altogether, and instead force the type of `visitor` to be determined entirely based on the inferred type `S` from the `value` param:

```ts
function visitNullableString<S extends string>(
    value: S | null | undefined, 
    visitor: NoInfer<NullableStringVisitor<S>>
): void
```

However, the hack `NoInfer<T>` implementation from my previous comment is very limited in that it can only prevent inference on a particular usage of a template param that is used more than once in inferrable ways (in this case, type `S`).

This limitation is preventing me from overloading a single `visitString` method that handles different combinations of value types (`S`, `S | null`, `S | undefined`, `S | null | undefined`), and appropriately corresponding variations of `StringVisitor` types that include handler methods for `null` and/or `undefined`, based on whether the type of the `value` param includes `null` and/or `undefined`. 

Technically, I can overload the method as desired, and it works when correct params are passed in. But when incorrect params are passed in (visitor missing a handler for one of the string values, or for null/undefined), then the compiler error messages are very misleading because it ends up inferring the type of the `visitor` incorrectly, completely independent of the type of `value`, telling the developer that their visitor is missing a property that is unnecessary based on the type of `value`.

```ts
function visitString<S extends string>(
    value: S, 
    visitor: StringVisitor<NoInfer<S>>
): void;
function visitString<S extends string>(
    value: S | null | undefined, 
    // When a call to visitString is made with incompatible types for 'value' and visitor',
    // the compiler seems to always default to assuming this last overloaded signature
    // which can cause an error to complain about missing"handleNullOrUndefined"
    // property even when the value of `value` passed in can never be null/undefined
    visitor: NullableStringVisitor<NoInfer<S>> 
): void;
```

For now, the best I can reasonably do is a separate method for each combination of null/undefined. The result is helpful error messages when a visitor is not fully implemented with all necessary handlers, but the developer must explicitly choose the correct variation of `visitString` (e.g., `visitStringWithNull` vs `visitStringWithNullOrUndefined`, etc.) to match the type of the `value` they pass in.

[Here's a full example in the Playground with separate visit methods](https://www.typescriptlang.org/play/#src=type%20NoInfer%3CT%3E%20%3D%20T%20%26%20%7B%5BK%20in%20keyof%20T%5D%3A%20T%5BK%5D%7D%3B%0D%0A%0D%0A%2F%2F%20visitor%20interface%20for%20visiting%20possible%20values%20of%20a%20string%20literal%20type%0D%0Atype%20StringVisitor%3CR%2C%20S%20extends%20string%3E%20%3D%20%7B%0D%0A%20%20%20%20%5BP%20in%20S%5D%3A%20(value%3A%20P)%20%3D%3E%20R%3B%0D%0A%7D%3B%0D%0A%0D%0Atype%20StringVisitorWithNull%3CR%2C%20S%20extends%20string%3E%20%3D%20StringVisitor%3CR%2C%20S%3E%20%26%20%7B%0D%0A%20%20%20%20handleNull%3A%20(value%3A%20null)%20%3D%3E%20R%3B%0D%0A%7D%3B%0D%0A%0D%0Atype%20StringVisitorWithUndefined%3CR%2C%20S%20extends%20string%3E%20%3D%20StringVisitor%3CR%2C%20S%3E%20%26%20%7B%0D%0A%20%20%20%20handleUndefined%3A%20(value%3A%20undefined)%20%3D%3E%20R%3B%0D%0A%7D%3B%0D%0A%0D%0Atype%20StringVisitorWithNullAndUndefined%3CR%2C%20S%20extends%20string%3E%20%3D%0D%0A%20%20%20%20%26%20StringVisitorWithNull%3CR%2C%20S%3E%0D%0A%20%20%20%20%26%20StringVisitorWithUndefined%3CR%2C%20S%3E%3B%0D%0A%0D%0Atype%20StringVisitorWithNullOrUndefined%3CR%2C%20S%20extends%20string%3E%20%3D%20StringVisitor%3CR%2C%20S%3E%20%26%20%7B%0D%0A%20%20%20%20handleNullOrUndefined%3A%20(value%3A%20null%20%7C%20undefined)%20%3D%3E%20R%3B%0D%0A%7D%0D%0A%0D%0Afunction%20visitString%3CR%2C%20S%20extends%20string%3E(%0D%0A%20%20%20%20value%3A%20S%2C%0D%0A%20%20%20%20visitor%3A%20StringVisitor%3CR%2C%20NoInfer%3CS%3E%3E%0D%0A)%3A%20R%20%7B%0D%0A%20%20%20%20return%20visitor%5Bvalue%5D(value)%3B%0D%0A%7D%0D%0A%0D%0Afunction%20visitStringWithNull%3CR%2C%20S%20extends%20string%3E(%0D%0A%20%20%20%20value%3A%20S%20%7C%20null%2C%0D%0A%20%20%20%20visitor%3A%20StringVisitorWithNull%3CR%2C%20NoInfer%3CS%3E%3E%0D%0A)%3A%20R%20%7B%0D%0A%20%20%20%20if%20(value%20%3D%3D%3D%20null)%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20visitor.handleNull(value)%3B%0D%0A%20%20%20%20%7D%20else%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20visitString(value%2C%20visitor)%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Afunction%20visitStringWithUndefined%3CR%2C%20S%20extends%20string%3E(%0D%0A%20%20%20%20value%3A%20S%20%7C%20undefined%2C%0D%0A%20%20%20%20visitor%3A%20StringVisitorWithUndefined%3CR%2C%20NoInfer%3CS%3E%3E%0D%0A)%3A%20R%20%7B%0D%0A%20%20%20%20if%20(value%20%3D%3D%3D%20undefined)%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20visitor.handleUndefined(value)%3B%0D%0A%20%20%20%20%7D%20else%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20visitString(value%2C%20visitor)%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Afunction%20visitStringWithNullOrUndefined%3CR%2C%20S%20extends%20string%3E(%0D%0A%20%20%20%20value%3A%20S%20%7C%20null%20%7C%20undefined%2C%0D%0A%20%20%20%20visitor%3A%20StringVisitorWithNullOrUndefined%3CR%2C%20NoInfer%3CS%3E%3E%0D%0A)%3A%20R%20%7B%0D%0A%20%20%20%20if%20(value%20%3D%3D%20null)%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20visitor.handleNullOrUndefined(value)%3B%0D%0A%20%20%20%20%7D%20else%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20visitString(value%2C%20visitor)%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Afunction%20visitStringWithNullAndUndefined%3CR%2C%20S%20extends%20string%3E(%0D%0A%20%20%20%20value%3A%20S%20%7C%20null%20%7C%20undefined%2C%0D%0A%20%20%20%20visitor%3A%20StringVisitorWithNullAndUndefined%3CR%2C%20NoInfer%3CS%3E%3E%0D%0A)%3A%20R%20%7B%0D%0A%20%20%20%20if%20(value%20%3D%3D%3D%20null)%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20visitor.handleNull(value)%3B%0D%0A%20%20%20%20%7D%20else%20if%20(value%20%3D%3D%3D%20undefined)%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20visitor.handleUndefined(value)%3B%0D%0A%20%20%20%20%7D%20else%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20visitString(value%2C%20visitor)%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0A%0D%0A%2F%2F%20example%20string%20literal%20type%0D%0Atype%20RGB%20%3D%20%22red%22%20%7C%20%22green%22%20%7C%20%22blue%22%3B%0D%0A%0D%0Afunction%20getRGBValue()%3A%20RGB%20%7C%20undefined%20%7B%0D%0A%20%20%20%20return%20%22green%22%3B%0D%0A%7D%0D%0A%0D%0A%2F%2F%20example%20shared%20handler%20used%20for%20multiple%20values%20in%20the%20RGB%20visitor%20implementation%0D%0Afunction%20handleUnsupportedValue(value%3A%20RGB%20%7C%20null%20%7C%20undefined)%3A%20number%20%7B%0D%0A%20%20%20%20alert('Unsupported%20value%3A%20%24%7Bvalue%7D')%3B%0D%0A%20%20%20%20return%200%3B%0D%0A%7D%0D%0A%0D%0Aconst%20x%20%3D%20visitStringWithUndefined(getRGBValue()%2C%20%7B%0D%0A%20%20%20%20handleUndefined%3A%20handleUnsupportedValue%2C%0D%0A%0D%0A%20%20%20%20%22red%22%3A%20handleUnsupportedValue%2C%0D%0A%0D%0A%20%20%20%20%22green%22%3A%20()%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20alert(%22green!%22)%3B%0D%0A%20%20%20%20%20%20%20%20return%2010%3B%0D%0A%20%20%20%20%7D%2C%0D%0A%0D%0A%20%20%20%20%22blue%22%3A%20()%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20alert(%22blue!%22)%3B%0D%0A%20%20%20%20%20%20%20%20return%2042%3B%0D%0A%20%20%20%20%7D%0D%0A%7D)%3B%0D%0A%0D%0A%0D%0Aenum%20Direction%20%7B%0D%0A%20%20%20%20LTR%20%3D%20%22ltr%22%2C%0D%0A%20%20%20%20RTL%20%3D%20%22rtl%22%0D%0A%7D%0D%0A%0D%0Afunction%20getDirection()%3A%20Direction%20%7C%20null%20%7B%0D%0A%20%20%20%20return%20Direction.LTR%3B%0D%0A%7D%0D%0A%0D%0Aconst%20y%3A%20number%20%3D%20visitStringWithNull(getDirection()%2C%20%7B%0D%0A%20%20%20%20handleNull%3A%20()%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20return%200%3B%0D%0A%20%20%20%20%7D%2C%0D%0A%0D%0A%20%20%20%20%5BDirection.LTR%5D%3A%20()%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20return%202%3B%0D%0A%20%20%20%20%7D%2C%0D%0A%0D%0A%20%20%20%20%5BDirection.RTL%5D%3A%20()%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20return%205%0D%0A%20%20%20%20%7D%0D%0A%7D)%3B%0D%0A) (enable ALL compiler options). Let me know if you'd also like me to setup an example with my attempt to overload the `visitString` method, showing how the compiler errors are misleading compared to my intentions.

**Comment by UselessPickles** [comment]
Or maybe my new issue is more about function overloading rather than type param inference?

**Comment by UselessPickles** [comment]
Nevermind on my previous long comment. I've figured out that it's an issue with compile error reporting on overloaded functions. Creating a new issue...

**Comment by UselessPickles** [comment]
My final solution is to split things up so the compiler only has to deal with inferring/enforcing the type of one parameter at a time.

My original goal was to have a single overloaded method. Example:
```ts
function visitString<S extends string, R>(value: S, visitor: StringVisitor<S, R>): R;
function visitString<S extends string, R>(value: S | null, visitor: StringVisitorWithNull<S, R>): R;
```

The goal being that if a potentially null value is passed in, then a corresponding appropriate visitor that can handle null must be supplied.

This approach had 3 distinct issues:
* The undesired type inference described in this issue.
* The confusing compiler error when none of the overloaded signatures were applicable (#20697)
* The inability to allow the compiler to infer type `S` while explicitly providing type `R` to clearly specify intent for the return type (https://github.com/Microsoft/TypeScript/issues/10571#issuecomment-348675440)

In my final solution, the signature(s) of my method looks more like this:
```ts
declare function visitString<S extends string>(value: S, visitor): StringVisitee<S> ;
declare function visitString<S extends string>(value: S | null): StringVisiteeWithNull<S>;
```

And the `StringVisitee` classes are simple wrappers around the value to be visited, and provides a generic method that actually accepts the visitor:
```ts
declare class StringVisitee<S extends string> {
    public with<R>(visitor: StringVisitor<S, R>): R;
}
declare class StringVisiteeWithNull<S extends string> {
    public with<R>(visitor: StringVisitorWithNull<S, R>): R;
}
```

And the complete usage now looks like:
```ts
declare x: RGB;

visitString(x).with({
    "red": () => { alert("RED!"); },
    "green": () => { alert("GREEN!"); },
    "blue": () => { alert("BLUE!"); },
});
```

This solves all 3 problems I had:
* The `visitString` method now only has to infer the type of the `value` being visited (specifically, whether it can be null or not), which dictates the kind of `StringVisitee` returned, which in turn accepts only the correct kind of visitor to its `with` method - no inference on the visitor any more (except for the return type portion of it).
* If you pass a mismatch of params to `visitString` and `with`, it is now very clear that the type of `value` passed to `visitString` drives the type of `visitor` expected by the `with` method, so you get very clear error messages about what's wrong with your visitor. The visitor is now strictly enforced to have the `handleNull` method if, *and only if*, the type of `value` may be null.
* The `with` method has only one type param: the return type. So you can now explicitly provide the desired return type to help enforce correct implementations.

Example of explicit return type:
```ts
declare x: RGB;

const result = visitString(x).with<number>({
    "red": () => { 
        return 1; 
    },
    "green": () => { 
        return 2; 
    },
    "blue": () => { 
        // very clear compiler error that this method returns the wrong type
        return "WRONG!";
    },
});
```

I implemented a [full example in the playground](https://www.typescriptlang.org/play/#src=%2F%2F%20visitor%20interface%20for%20visiting%20possible%20values%20of%20a%20string%20literal%20type%0D%0Atype%20StringVisitor%3CR%2C%20S%20extends%20string%3E%20%3D%20%7B%0D%0A%20%20%20%20%5BP%20in%20S%5D%3A%20(value%3A%20P)%20%3D%3E%20R%3B%0D%0A%7D%3B%0D%0A%0D%0Atype%20StringVisitorWithNull%3CR%2C%20S%20extends%20string%3E%20%3D%20StringVisitor%3CR%2C%20S%3E%20%26%20%7B%0D%0A%20%20%20%20handleNull%3A%20(value%3A%20null)%20%3D%3E%20R%3B%0D%0A%7D%3B%0D%0A%0D%0Atype%20StringVisitorWithUndefined%3CR%2C%20S%20extends%20string%3E%20%3D%20StringVisitor%3CR%2C%20S%3E%20%26%20%7B%0D%0A%20%20%20%20handleUndefined%3A%20(value%3A%20undefined)%20%3D%3E%20R%3B%0D%0A%7D%3B%0D%0A%0D%0Atype%20StringVisitorWithNullAndUndefined%3CR%2C%20S%20extends%20string%3E%20%3D%0D%0A%20%20%20%20%26%20StringVisitorWithNull%3CR%2C%20S%3E%0D%0A%20%20%20%20%26%20StringVisitorWithUndefined%3CR%2C%20S%3E%3B%0D%0A%0D%0A%0D%0Adeclare%20class%20StringVisitee%3CS%20extends%20string%3E%20%7B%0D%0A%20%20%20%20public%20with%3CR%3E(visitor%3A%20StringVisitor%3CR%2C%20S%3E)%3A%20R%3B%0D%0A%7D%0D%0Adeclare%20class%20StringVisiteeWithNull%3CS%20extends%20string%3E%20%7B%0D%0A%20%20%20%20public%20with%3CR%3E(visitor%3A%20StringVisitorWithNull%3CR%2C%20S%3E)%3A%20R%3B%0D%0A%7D%0D%0Adeclare%20class%20StringVisiteeWithUndefined%3CS%20extends%20string%3E%20%7B%0D%0A%20%20%20%20public%20with%3CR%3E(visitor%3A%20StringVisitorWithUndefined%3CR%2C%20S%3E)%3A%20R%3B%0D%0A%7D%0D%0Aclass%20StringVisiteeWithNullAndUndefined%3CS%20extends%20string%3E%20%7B%0D%0A%20%20%20%20public%20constructor(private%20readonly%20value%3A%20S%20%7C%20null%20%7C%20undefined)%20%7B%20%7D%0D%0A%0D%0A%20%20%20%20public%20with%3CR%3E(visitor%3A%20StringVisitorWithNullAndUndefined%3CR%2C%20S%3E)%3A%20R%20%7B%0D%0A%20%20%20%20%20%20%20%20if%20(this.value%20%3D%3D%3D%20null)%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20visitor.handleNull(null)%3B%0D%0A%20%20%20%20%20%20%20%20%7D%20else%20if%20(this.value%20%3D%3D%3D%20undefined)%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20visitor.handleUndefined(undefined)%3B%0D%0A%20%20%20%20%20%20%20%20%7D%20else%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20(visitor%20as%20StringVisitor%3CR%2C%20S%3E)%5Bthis.value%5D(this.value)%3B%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0A%0D%0Afunction%20visitString%3CS%20extends%20string%3E(value%3A%20S)%3A%20StringVisitee%3CS%3E%3B%0D%0Afunction%20visitString%3CS%20extends%20string%3E(value%3A%20S%20%7C%20null)%3A%20StringVisiteeWithNull%3CS%3E%3B%0D%0Afunction%20visitString%3CS%20extends%20string%3E(value%3A%20S%20%7C%20undefined)%3A%20StringVisiteeWithUndefined%3CS%3E%3B%0D%0Afunction%20visitString%3CS%20extends%20string%3E(value%3A%20S%20%7C%20null%20%7C%20undefined)%3A%20StringVisiteeWithNullAndUndefined%3CS%3E%3B%0D%0Afunction%20visitString%3CS%20extends%20string%3E(value%3A%20S%20%7C%20null%20%7C%20undefined)%3A%20StringVisitee%3CS%3E%20%7C%20StringVisiteeWithNull%3CS%3E%20%7C%20StringVisiteeWithUndefined%3CS%3E%20%7B%0D%0A%20%20%20%20return%20new%20StringVisiteeWithNullAndUndefined%3CS%3E(value)%3B%0D%0A%7D%0D%0A%0D%0A%0D%0A%2F%2F%20example%20string%20literal%20type%0D%0Atype%20RGB%20%3D%20%22red%22%20%7C%20%22green%22%20%7C%20%22blue%22%3B%0D%0A%0D%0Afunction%20getRGBValue()%3A%20RGB%20%7C%20undefined%20%7C%20null%20%7B%0D%0A%20%20%20%20return%20null%3B%0D%0A%7D%0D%0A%0D%0A%2F%2F%20example%20shared%20handler%20used%20for%20multiple%20values%20in%20the%20RGB%20visitor%20implementation%0D%0Afunction%20handleUnsupportedValue(value%3A%20RGB%20%7C%20null%20%7C%20undefined)%3A%20number%20%7B%0D%0A%20%20%20%20alert(%60Unsupported%20value%3A%20%24%7Bvalue%7D%60)%3B%0D%0A%20%20%20%20return%20-1%3B%0D%0A%7D%0D%0A%0D%0Aconst%20x%20%3D%20visitString(getRGBValue()).with(%7B%0D%0A%20%20%20%20handleNull%3A%20handleUnsupportedValue%2C%0D%0A%0D%0A%20%20%20%20handleUndefined%3A%20handleUnsupportedValue%2C%0D%0A%0D%0A%20%20%20%20%22red%22%3A%20handleUnsupportedValue%2C%0D%0A%0D%0A%20%20%20%20%22green%22%3A%20()%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20alert(%22green!%22)%3B%0D%0A%20%20%20%20%20%20%20%20return%201%3B%0D%0A%20%20%20%20%7D%2C%0D%0A%0D%0A%20%20%20%20%22blue%22%3A%20()%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20alert(%22blue!%22)%3B%0D%0A%20%20%20%20%20%20%20%20return%202%3B%0D%0A%20%20%20%20%7D%0D%0A%7D)%3B%0D%0A%0D%0Aalert(%60x%3A%20%24%7Bx%7D%60)%3B%0D%0A%0D%0A%0D%0Aenum%20Direction%20%7B%0D%0A%20%20%20%20LTR%20%3D%20%22ltr%22%2C%0D%0A%20%20%20%20RTL%20%3D%20%22rtl%22%0D%0A%7D%0D%0A%0D%0Afunction%20getDirection()%3A%20Direction%20%7B%0D%0A%20%20%20%20return%20Direction.LTR%3B%0D%0A%7D%0D%0A%0D%0AvisitString(getDirection()).with(%7B%0D%0A%20%20%20%20%5BDirection.LTR%5D%3A%20()%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20alert(%22Left%20to%20right!%22)%3B%0D%0A%20%20%20%20%7D%2C%0D%0A%0D%0A%20%20%20%20%5BDirection.RTL%5D%3A%20()%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20alert(%22Right%20to%20left!%22)%3B%0D%0A%20%20%20%20%7D%0D%0A%7D)%3B%0D%0A) (must enable strictNullChecks!)

**Comment by UselessPickles** [comment]
In case anyone comes across this and is interested in this string visitor pattern I've been trying to create, I have now fully documented and tested it and put it on github: https://github.com/UselessPickles/ts-string-visitor

And published it as an npm package: https://www.npmjs.com/package/ts-string-visitor
