### ISSUE TITLE
Maximum call stack size exceeded error with window.atob

### ISSUE THREAD

**Issue by prettydiff** [Microsoft/TypeScript#20652]
I am attempting to convert the following file to TypeScript, but the highlighted line causes a the compiler to crash with a *Maximum call stack size exceeded* error.

https://github.com/prettydiff/prettydiff/blob/master/api/dom.js#L6932

I am 100% confident the window.atob method (or method plus that long string argument) is to blame as I can isolate the problem to that method.

The only @types file I have included so far is @ types/node and the reference *window* is just an undeclared global reference to the compiler.  My version of TS is **2.4.2**

You should be able to reproduce this error if you can bring the file down to an empty directory, rename the file extension to `.ts`, and run the compiler.

**Comment by RyanCavanaugh** [comment]
The problem here is the enormous string literal concat - it's represented internally as a binary tree so it's very, very deep.

**Comment by prettydiff** [comment]
Would it work better if it were a giant single string (no concat)?

**Comment by RyanCavanaugh** [comment]
Yep, that shouldn't be a problem.

**Comment by prettydiff** [comment]
Fixed by converting it to an array of strings.  In this case the data is just a static constant, data at rest, so there is no impact either way.  Late I may look into providing an abstraction later to solve for this in the TypeScript compiler now that I know what the problem is.
