### ISSUE TITLE
String literal types failing in waterline

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#20653]
See `DefinitelyTyped/types/waterline`; I added casts to get these to work, but ideally we could just write `"email"` instead of `"email" as "email"`.

**Comment by weswigham** [comment]
The `waterline` types contain
```ts
    export type BaseAttribute<T> = AttributeValidations & {
        type?: string;
        primaryKey?: boolean;
        unique?: boolean;
        required?: boolean;
        enum?: Array<T>;
        size?: number;
        columnName?: string;
        index?: boolean;
        defaultsTo?: T | DefaultsToFn<T>;
    }
    export type StringAttribute = BaseAttribute<string> & {
        type: "string";
    }
```

`string | "string"` is super likely to get simplified to `string` the type gets mapped over in any way (as only contextual type traversal is going to preserve that union right now). But all is not lost, the `waterline` types can be rewritten:
```ts
    export type BaseAttribute<T, TType extends string = string> = AttributeValidations & {
        type?: TType;
        primaryKey?: boolean;
        unique?: boolean;
        required?: boolean;
        enum?: Array<T>;
        size?: number;
        columnName?: string;
        index?: boolean;
        defaultsTo?: T | DefaultsToFn<T>;
    }
    export type StringAttribute = BaseAttribute<string, "string">;
```
IMO, the types are actually better defined this way (certainly more concise) so the types can be made to continue working, but looking into if we must preserve our behavior for these packages is still an issue.

**Comment by andy-ms** [comment]
That's an intersection, so shouldn't it be `string & "string"` not `string | "string"`?

**Comment by andy-ms** [comment]
You're probably right that it's better without the intersection types though.

**Comment by weswigham** [comment]
> That's an intersection, so shouldn't it be `string & "string"` not `string | "string"`?

I think because the field is optional in the original type you end up with an intersection applied over a union that then has redundant literals removed.

**Comment by weswigham** [comment]
Yep, definitely a bug caused by the intersection type. I know the issue and will have a fix up momentarily.
