### ISSUE TITLE
unhandledrejection event missing from WindowEventMap

### ISSUE THREAD

**Issue by robatwilliams** [Microsoft/TypeScript#20656]
**TypeScript Version:**  2.6.1

**Code**

```ts
window.addEventListener('unhandledrejection', event => {
  // event is of type Event
});

window.addEventListener('unhandledrejection', (event: PromiseRejectionEvent) => {
    /*
Argument of type '(event: PromiseRejectionEvent) => void' is not assignable to parameter of type 'EventListenerOrEventListenerObject'.
  Type '(event: PromiseRejectionEvent) => void' is not assignable to type 'EventListenerObject'.
    Property 'handleEvent' is missing in type '(event: PromiseRejectionEvent) => void'.
*/
});
```

**Expected behavior:**
Event listener for `unhandledrejection` should have event type `PromiseRejectionEvent`.

I believe an entry needs adding to `WindowEventMap` in `lib.dom.d.ts`.

**Actual behavior:**
Compiler error as shown in code sample above, when using strict mode.

**Workaround:**
Use declaration merging; create a typings file and include
```
interface WindowEventMap {
  'unhandledrejection': PromiseRejectionEvent;
}
```

**Comment by shobhitchittora** [comment]
Hi @RyanCavanaugh I'd like to take this up. Also would need some pointer to get started on this issue.

**Comment by robatwilliams** [comment]
`rejectionhandled` needs doing too

**Comment by benbraou** [comment]
@shobhitchittora I am also starting to contribute to TypeScript but I hope this will help:
From what I see, the change needs to be done in [TSJS-lib-generator](https://github.com/Microsoft/TSJS-lib-generator).
It seems that unhandledrejection/ rejectionhandled events are missing from Edge spec. So, they need to be manually added in addedTypes.json as new properties of WindowEventMap.
You might have to add some tweaks in TS.fsx though

**Comment by cameron-martin** [comment]
It looks like these are now added. See https://github.com/Microsoft/TSJS-lib-generator/blob/master/baselines/dom.generated.d.ts

**Comment by mhegazy** [comment]
thanks!
