### ISSUE TITLE
Definitions in lib.es6.d.ts are automatically included in Node programs

### ISSUE THREAD

**Issue by lindydonna** [Microsoft/TypeScript#20658]
**TypeScript Version:** 2.6.1

I used the variable `name` before it was defined, and was surprised to see it was not a compile/lint error.

**Code**

```ts
let x = name;
```

**package.json**
```json
{
    "name": "my-awesome-program",
    "version": "0.1",
    "main": "bin/index.js",
    "typings": "bin/index.d.ts",
    "scripts": {
        "build": "tsc"
    },
    "devDependencies": {
        "typescript": "^2.5.3"
    },
    "dependencies": {
        "@types/node": "^8.0.26"
    }
}
```

**Expected behavior:**

tsc or tslint tells me that `name` is undefined.

**Actual behavior:**

No errors in tsc, VS Code, or tslint. Get runtime Node error because `name` is undefined.

**Comment by andy-ms** [comment]
I don't think this is because of `@types/node`. You probably need to set your [`--lib`](https://www.typescriptlang.org/docs/handbook/compiler-options.html) option to not include "dom".

**Comment by lindydonna** [comment]
@andy-ms I'd like `dom` to be automatically excluded when it's a Node program. Ideally, also have this built into the VS Code tooling. Are you saying that I should be customizing `tsconfig.json` when it is Node?

**Comment by andy-ms** [comment]
Unfortunately, we don't have a good way of telling where a user is intending to run their code without explicitly specifying `"lib"`. Perhaps the default lib should have just been the ES spec without dom, but now we can't change that due to backwards-compatibility.

**Comment by lindydonna** [comment]
Thanks @andy-ms. Closing as resolved for my scenario
