### ISSUE TITLE
tsc copy filed not included it's parent dir after compiled with setting other dir exclued in tsconfig.json

### ISSUE THREAD

**Issue by Phinome** [Microsoft/TypeScript#20668]
`tsc 2.6.2`. there is source dir tree:

```
src/
├── client
│   └── client.tsx
├── server
│   ├── actions
│   ├── app.ts
├── shared
```

where `tsconfig.json` settings:
```json
{
...,
"outDir": "dist",
"exclude": [
    "./src/shared/**/*",
    "./src/client/**/*",
    "./src/server/*.tsx",
    "./src/server/**/*.tsx",
],
"include": [
    "./src/**/*"
  ]
}
```

exec `tsc -p tsconfig.json`, expected `dist dir tree`:
```
src/
├── server
│   ├── actions
│   ├── app.ts
```

in fact，it output:
```
dist
├── app.js
├── app.js.map
├── actions
```

but,  this's `tsconfig.json` is okay:
```json 
{
...,
"outDir": "dist",
"exclude": [
    "./src/shared/**/*",
],
"include": [
    "./src/**/*"
  ]
}
```

the output `dist dir  tree`:
```
dist
├── client
└── server
```

so, i am confused. that is a bug ?😷😷😷

Thanks.

**Comment by andy-ms** [comment]
Seems like a duplicate of #16563.
Normally we will find the common root directory of all the files that were included -- so if you only include files in `src/server` and compile to `dist`, we'll compile from `src/server` to `dist` and not add a `server` directory.
As mentioned in that issue, you can override this behavior by setting an explicit `"rootDir": "src"` in your `tsconfig.json`.

**Comment by Phinome** [comment]
Thanks.
