### ISSUE TITLE
Cannot assert `Partial<T>[keyof T]` not to be undefined using `!` (regression from 2.5)

### ISSUE THREAD

**Issue by mprobst** [Microsoft/TypeScript#20673]
**TypeScript Version:**  2.6.2

**Code**

See also [in the playground example here](https://www.typescriptlang.org/play/#src=%0D%0Afunction%20createComponent%3CT%3E(%0D%0A%20%20%20%20comp%3A%20T%2C%20inputs%3A%20Partial%3CT%3E%20%3D%20%7B%7D)%20%7B%0D%0A%20%20%20%20for%20(const%20key%20in%20inputs)%20%7B%0D%0A%20%20%20%20%20%20%20%20if%20(inputs.hasOwnProperty(key))%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20const%20partialVal%20%3D%20inputs%5Bkey%5D%3B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20const%20value%20%3D%20partialVal!%3B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20comp%5Bkey%5D%20%3D%20value%3B%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A).

```ts
function createComponent<T>(
    comp: T, inputs: Partial<T> = {}) {
    for (const key in inputs) {
        if (inputs.hasOwnProperty(key)) {
            const partialVal = inputs[key];
            const value = partialVal!;
            comp[key] = value;
        }
    }
}
```

**Expected behavior:**

`parialVal!` should strip the `|undefined` from value, and the assignment should succeed.

**Actual behavior:**

```
  Type 'T[keyof T] | undefined' is not assignable to type 'T[keyof T]'.
    Type 'undefined' is not assignable to type 'T[keyof T]'.
      Type 'undefined' is not assignable to type 'T[string]'.
        Type 'Partial<T>[keyof T]' is not assignable to type 'T[string]'.
          Type 'T[keyof T] | undefined' is not assignable to type 'T[string]'.
            Type 'undefined' is not assignable to type 'T[string]'.
```

**Comment by andy-ms** [comment]
I think this would essentially require us to have #14366 working so we could have a `NonNull<Partial<T>[keyof T]>` type.

**Comment by mprobst** [comment]
For the record, this used to succeed in 2.5, so this is a regression.

**Comment by andy-ms** [comment]
OK, I must be wrong about a NonNull type being needed.

**Comment by ahejlsberg** [comment]
This is caused by #18042. Previously we would immediate transform an indexed access applied to a mapped type `{ [P in keyof T]?: T[P] | undefined }[X]` into a simpler form `T[X] | undefined`, but we now defer that operation. For that reason the type appears to not include `undefined` and the `!` operator has no effect.

**Comment by mhegazy** [comment]
duplicate of  #14366
