### ISSUE TITLE
Feature Request: More infos about an import on hover

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#20685]
_From @aight8 on April 27, 2017 12:3_

- VSCode Version: all
- OS Version: all

![more-info](https://cloud.githubusercontent.com/assets/1138623/25482414/ff9f0d48-2b51-11e7-877f-8471156d6835.gif)

This issue is also typescript related.

If hovering a module it very nice if:
- If found: Found also which path is used finally - can be very helpful since the node module resolving strategy is complicated and long
- If not found: Show the paths in which it get searched for (a VERY big help!)

_Copied from original issue: Microsoft/vscode#25540_

**Comment by mjbvz** [comment]
Moving over to TypeScript repo to get feedback on these proposals

**Comment by RyanCavanaugh** [comment]
For a resolved module, there may be more than one file declaring it, but we could at least show one. Though you can already press F12 and just go there, which seems more useful anyway.

I can't imagine the tooltip on an unresolved module being short enough to be readable in a useful way.

**Comment by mjbvz** [comment]
Yes, given how verbose `traceResolution` can be, I'd say that surfacing the search paths would be overwhelming
