### ISSUE TITLE
Visual Studio not syntax highlighting with the new JavaScript language service

### ISSUE THREAD

**Issue by JCKodel** [Microsoft/TypeScript#20680]
I don't know why this has to be reported in TypeScript repository, but, whatever...

**Expected behavior:**
[ ] Enable the new JavaScript language service.
![image](https://user-images.githubusercontent.com/379339/33958211-edb103b4-e02a-11e7-853c-43e039e68e73.png)

**Actual behavior:**
[X] Enable thre new JavaScript language service.
![image](https://user-images.githubusercontent.com/379339/33958237-fc7986a0-e02a-11e7-8044-33c84965246d.png)

(Whenever this setting is changed inside VS, you need to close and reopen the .js)

**Comment by edwlee** [comment]
I'm experiencing the same issue with Visual Studio 2017 Version 15.4.4

**Comment by mhegazy** [comment]
does the file has a line with more than 10k characters?

**Comment by owen2** [comment]
I'm seeing this in 15.5.5. No lines with >10k characters. I also don't get any intellisense features unless I use the old language service.

**Comment by amcasey** [comment]
Thanks for the details @owen2!  (It would be great if @JCKodel and @edwlee could confirm that they're seeing the same.)

Do you happen to know which version of TypeScript you're using?  If you're not setting it explicitly, I find the easiest way to find out for sure is to find the `node.exe` process in Task Manager with `tsserver.js` in its command line (Command line being an optional column in Task Manager) - the path to that file will tell you everything you need to know.

In @JCKodel's original screenshots, the navigation bar (at the top left of the editor pane) shows that the JS file is in a project.  Are you seeing the same?  It would be strange to see that but not get IntelliSense.

**Comment by amcasey** [comment]
Aha, it sounds like there's an issue with TextMate caching in 15.5.*.  Can you try deleting `%localappdata%\Microsoft\VisualStudio\[instance]\TextMateCache`?

**Comment by JCKodel** [comment]
@amcasey  Visual Studio gave me a lot of issues (including the Aero quick menu stopped showing my last/pinned projects), so I had to reinstall Windows (you know, too much gargabe, uninstall always leave some trash behind, anyway... until Windows have a decent package manager (aka apt-get), we have to suffer the consequences if we want the Amazing-Visual-Studio-Sorry-VSCode-You-Are-No-Match)

Since then, I didn't have any issues regarding this anymore. Honestly, I did forget about this issue (I had to go to options right now to be sure I'm using the new language service).

So far, so good (note: I'm using js only, no typescript, using vue and framework7).

I have also figured out that the best kind of project to work with javascript is shared projects. It's not perfect (for instance: File Nesting plugin doesn't work), but at least, so far, it had no problems. Node folder is kept hidden, no bin/obj folder, Resharper works fine, etc. These screenshots are for the same kind of project, but inside a .net core asp.net project (but, again, even this project is working, AFAIK).

**Comment by amcasey** [comment]
@JCKodel thanks for the update!  We've definitely had cases where the TextMate extension needed to be repaired.  Maybe that was the issue you were seeing.  In any case, glad things are working now.

**Comment by owen2** [comment]
My project file specifies typescript 1.8, but we use gulp to compile/bundle everything. 

I did try deleting my textmate cache as @amcasey suggested and turned the new language service back on. I now see unhighlighted javascript.

**Comment by amcasey** [comment]
@owen2 is it just the highlighting that's giving you trouble or Intellisense too?  Is there anything in the Navigation Bars?

**Comment by owen2** [comment]
No intellisense, but I have stuff in the navigation bars.

**Comment by owen2** [comment]
Just noticed my "Visual Studio Extension for Textmate Grammars" extension was disabled. I think I disabled it when I had performance issues and disabled all extensions I didn't recognize.

**Comment by amcasey** [comment]
Actually, I don't believe the language service in VS 15.5 supports TS 1.8.  Can you try rolling forward to 2.1 (our current minimum) or 2.7 (our current release)?

**Comment by owen2** [comment]
Enabling that extension brought back all of the missing functionality. :)

**Comment by amcasey** [comment]
Disabling that extension would prevent colorization. :smile:

**Comment by amcasey** [comment]
I'll go ahead and close this issue then?

**Comment by owen2** [comment]
I'm good and it looks like @JCKodel isn't experiencing this anymore.

**Comment by amcasey** [comment]
Thanks!  @edwlee, please post an update if you're still having problems.
