### ISSUE TITLE
Narrow type after assertion?

### ISSUE THREAD

**Issue by aaronbeall** [Microsoft/TypeScript#20682]
**TypeScript Version:**  2.7.0-dev.201xxxxx

Would it be possible to treat an assertion like a type-guard and narrow the type within blocks that are "guarded" by an assertion?

For example:

**Code**

```ts
type Square = { size: number; }
type Circle = { radius: number; }
type Shape = Square | Circle;

declare const shape: Shape;
if ((shape as Circle).radius) {
  shape.radius // Error: Property 'radius' does not exist on type 'Square'
  (shape as Circle).radius // Ok, but seems redundant
}
```

But you could consider the `(shape as Circle).radius` like the user saying:
```ts
isCircle(shape) && shape.radius
// or at least
hasRadius(shape) && shape.radius
```

I realize that checking for a property is not considered good enough to narrow the type, but if the user has explicitly asserted the type it would be convenient if control flow could keep track of that in downstream code.

**Comment by RyanCavanaugh** [comment]
Same as #8655?

**Comment by aaronbeall** [comment]
@RyanCavanaugh Looks like the same desired behavior for a different use case (using an `assert()` function)...

**Comment by aaronbeall** [comment]
> I realize that checking for a property is not considered good enough to narrow the type

Oh, actually, I just saw that https://github.com/Microsoft/TypeScript/issues/10485 _"Treat `in` operator as type guard"_ just made the roadmap for 2.7! I think that gives me everything I wanted here?

```ts
if ("radius" in shape && .radius) {
  shape.radius // Ok
}
```
