### ISSUE TITLE
Import code fix hard to distinguish when module shares name with its export

### ISSUE THREAD

**Issue by andy-ms** [microsoft/TypeScript#20683]
**Code**

**a.ts**
```ts
export const a = 0;
export default function fun() {}
```

**b.ts**
```ts
a;
```

**Expected behavior:**

Get one import code fix for `export const a`.

**Actual behavior:**

Get two fixes, both with the description `Import 'a' from module "./a"`, but one's a default import and one's a named import.

**Comment by DanielRosenwasser** [comment]
I think we should actually provide two, but it should be clearer that one is a named import.

**Comment by RyanCavanaugh** [comment]
Doesn't seem to get encountered in practice
