### ISSUE TITLE
unknown compiler option lib 

### ISSUE THREAD

**Issue by nat124** [Microsoft/TypeScript#20692]
i am getting error when i build my project :unknown compiler option lib 
my ts config file is:
{
  "compilerOptions": {
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "module": "commonjs",
    "moduleResolution": "node",
    "lib": [ "es2015", "dom" ],
    "noImplicitAny": true,
    "sourceMap": true,
    "suppressImplicitAnyIndexErrors": true,
    "target": "es5"
  }
}
and m using typescript 2.0.0

**Comment by andy-ms** [comment]
First I would recommend using a newer version of TypeScript -- but even with `typescript@2.0.0` installed I get no error when compiling an empty file with that `tsconfig.json`. Could you try running `npm install typescript` and then `tsc` from the command line?
