### ISSUE TITLE
New Website Logo: HolidayCheck

### ISSUE THREAD

**Issue by screendriver** [Microsoft/TypeScript#20696]
Please fill the following out:

- Name: HolidayCheck
- Homepage url: https://www.holidaycheck.de
- Brand Guidelines/Licensing: http://styleguide.holidaycheck.com/d/nJqVg5BxRI9L/brand-guide     
- Logo: https://cdn.frontify.com/api/screen/thumbnail/DcHWTsC5v_RL2XZbfoNpUBIVowY3mzmFzC5U4VTzF5pIFW6tsHF7jeAzOTW0R1RSAhSJdzvVNEBU2apzgIvfdA/859

**Comment by mhegazy** [comment]
Should be available the next time the site is published
