### ISSUE TITLE
Use typeof with generic

### ISSUE THREAD

**Issue by donaldpipowitch** [Microsoft/TypeScript#20719]
**TypeScript Version:**  Current playground version (?)

**Code**

```ts
class GenericGroup<T> {
  items: Array<T> = [];
  constructor(name: string) {}
}

type CheckboxValues = string;
type CheckboxesGroup = new (name: string) => GenericGroup<CheckboxValues>;
const Checkboxes: CheckboxesGroup = GenericGroup;
const checkboxes = new Checkboxes('checkboxes');
checkboxes.items.map(item => item.toUpperCase());


type RadioValues = string;
type RadiosGroup = typeof GenericGroup<RadioValues>;
const Radios: RadiosGroup = GenericGroup;
const radios = new Radios('radios');
radios.items.map(item => item.toUpperCase());
```

[link](https://www.typescriptlang.org/play/index.html#src=class%20GenericGroup%3CT%3E%20%7B%0A%20%20items%3A%20Array%3CT%3E%20%3D%20%5B%5D%3B%0A%20%20constructor(name%3A%20string)%20%7B%7D%0A%7D%0A%0Atype%20CheckboxValues%20%3D%20string%3B%0Atype%20CheckboxesGroup%20%3D%20new%20(name%3A%20string)%20%3D%3E%20GenericGroup%3CCheckboxValues%3E%3B%0Aconst%20Checkboxes%3A%20CheckboxesGroup%20%3D%20GenericGroup%3B%0Aconst%20checkboxes%20%3D%20new%20Checkboxes('checkboxes')%3B%0Acheckboxes.items.map(item%20%3D%3E%20item.toUpperCase())%3B%0A%0A%0Atype%20RadioValues%20%3D%20string%3B%0Atype%20RadiosGroup%20%3D%20typeof%20GenericGroup%3CRadioValues%3E%3B%0Aconst%20Radios%3A%20RadiosGroup%20%3D%20GenericGroup%3B%0Aconst%20radios%20%3D%20new%20Radios('radios')%3B%0Aradios.items.map(item%20%3D%3E%20item.toUpperCase())%3B)

**Expected behavior:**

`typeof GenericGroup<RadioValues>;` is equivalent to `new (name: string) => GenericGroup<RadioValues>;`

**Actual behavior:**

Syntax error, because `typeof GenericGroup<RadioValues>;` is not supported.

**Motivation:**

In my use case I have a class with a generic (like `GenericGroup`) which _extends_ a class from a 3rd party lib. The class from the 3rd party lib uses multiple params in its constructor. When I alias my class with the filled generic I don't want to write the parameters for the 3rd party lib every time (as done with `new (name: string) => GenericGroup<CheckboxValues>;`) as I don't really maintain them.

(There seem to be multiple related issues, but I couldn't found an issue with exactly this problem.)

**Comment by superamadeus** [comment]
The 'typeof' operator is not meant to describe the constructor of a type, but rather the type of a value. SomeGeneric<T> is not a value, it is a type in and of itself. Any other interface/type (like the one defined below) will not work in this way either. 

```typescript
interface MyInterface {
    name: string;
}

let m: typeof MyInterface;
```

A solution to this is to define a generic type to describe constructors like Angular does:

```typescript 
export interface Type<T> extends Function { 
    new (...args: any[]): T; 
}
```
from ([angular/packages/core/src/type.ts](https://github.com/angular/angular/blob/master/packages/core/src/type.ts))

Usage example:

```typescript
type RadioValues = string;
type RadiosGroup = Type<GenericGroup<RadioValues>>;
const Radios: RadiosGroup = GenericGroup;
const radios = new Radios('radios');
radios.items.map(item => item.toUpperCase());
```

**Comment by RyanCavanaugh** [comment]
A subtle thing is that generic class constructor functions *are not contained in a generic type*. You can tell that because the type parameter is not in scope for static members! It "feels" like you have a type like this
```ts
interface GenericCtor<T> {
  new(x: string): InstanceType<T>;
}
```
but the real type is like this
```ts
interface GenericCtor {
  new<T>(x: string): InstanceType<T>;
}
```

**Comment by donaldpipowitch** [comment]
Thank you both. I need to wrap my head around this. In my case I extend from a 3rd party constructor (`React.Component`) so I need to figure out how to apply your feedback there. Thanks.
