### ISSUE TITLE
hope can support `export default exports;`

### ISSUE THREAD

**Issue by bluelovers** [Microsoft/TypeScript#20717]
hope can support `export default exports;`

and  option for auto import a module didn't has __esModule

```
import a from 'a';
import * as a from 'a';
```

**Comment by RyanCavanaugh** [comment]
You might be looking for `--allowSyntheticDefaultImports`; if you're not, this is not enough information for us to act on

**Comment by bluelovers** [comment]
i already set allowSyntheticDefaultImports

but this option didn't change transpile output code
i  mean like babel can make a hook for require auto import

a
```
exports = xxxx
```

can auto import by code
```
import a from 'a';
import * as a from 'a';
```

transpile something like this when use `import a from 'a';`
```
return (o.__esModule) ? o.default : o;
```

**Comment by weswigham** [comment]
@bluelovers I think you'd want to use https://github.com/Microsoft/TypeScript/pull/19675 once it's merged, if you're looking for the corresponding emit changes.

**Comment by bluelovers** [comment]
@weswigham thx

about `export default exports;`

a
```
export function str(s: string) { return s; }

export default exports;
```

b
```
import a from 'a';

a.str(123) // <=== this didn't trigge typecheck
```

**Comment by weswigham** [comment]
@bluelovers You shouldn't need syntax support for that; I think a circular reference should be fine.
```ts
import * as self from "./path/to/self";

export function str(s: string) { return s; }

export default self;
```

**Comment by bluelovers** [comment]
@weswigham magic!!
