### ISSUE TITLE
`git submodule update --init --recursive` has started failing for TypeScript

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#20712]
A command I use for byots. Started happening two days ago: 

* First Fail : https://travis-ci.org/basarat/byots/builds/315256347#L439
* Fail again : https://travis-ci.org/basarat/byots/builds/316174875#L443

Complete build history showing it used to work : https://travis-ci.org/basarat/byots/builds e.g. successful command in this build : https://travis-ci.org/basarat/byots/builds/314666216#L425 

Error message : `error: Server does not allow request for unadvertised object ed149eb0c787b1195a95b44105822c64bb6eb636`

:rose:

**Comment by mhegazy** [comment]
I am not sure what is causing this, or how we can fix it.. any ideas?

**Comment by basarat** [comment]
Nothing was needed at your end. I guess travis was having issues :rose: 

# For my record (anyone else that might experience it)
* There is an old issue in travis I found : https://github.com/travis-ci/travis-ci/issues/2950
* `git submodule sync` would fix it : https://github.com/AppImage/AppImageKit/issues/511#issuecomment-341885789
* But since `git submodule update --init --recursive` is run by travis I couldn't hook up the sync command to execute. 
* Tried deleting the sub module and adding it back (https://github.com/basarat/byots/commit/0ae526cb2c4a6ef16084c941fe074fb03ae397a4 / https://github.com/basarat/byots/commit/031cccb3d4cceba4bb9e2d2f8c789159eaca4b37) but that didn't work : https://travis-ci.org/basarat/byots/builds/327926413
* So I just released manually locally by running `quick.sh` (https://github.com/basarat/byots/blob/cc62668f4f0a3d3d3a823460c43561da55be05c2/quick.sh) / which is what I can use to deploy locally : https://github.com/basarat/byots/blob/cc62668f4f0a3d3d3a823460c43561da55be05c2/CONTRIBUTING.md#quickly and it worked 
* So I let travis try again by kicking off a build by deleting a file (which I have specifically for kicking a travis build) and it worked : https://travis-ci.org/basarat/byots/builds/327928196

As always thank you :heart: :rose:
