### ISSUE TITLE
isContextSensitive in the checker returns false for literals

### ISSUE THREAD

**Issue by amcasey** [Microsoft/TypeScript#20727]
For example, it should probably return true for `1` and `{ x: 1 }`.

We'd like to use this in the language service to make intelligent decisions about which extracted constants need type annotations.  The test `extractConstant_ContextualType` shows a case where the current behavior causes an incorrect decision to omit a type annotation.

**Comment by amcasey** [comment]
FYI @sandersn @weswigham

**Comment by sandersn** [comment]
Quick note about the problem we hit when changing it experimentally:

Arrow functions that are only context-sensitive in their return value (such as `() => 12` or `(_n: string) => "foo"`) are treated incorrectly in a number of ways. The worst was adding a this-parameter from the contextual type. I'm not sure if `isContextSensitive` should return false for these functions or if various code paths that use `isContextSensitive` need to be understand that they might now be operating on an arrow function.

@weswigham I think there might have been another issue with the change. Do you remember anything else?

**Comment by weswigham** [comment]
The way inference works, we use fixed non-contextual types from the first pass to apply contextual types to things in the second pass. When literals become context-sensitive, we no longer get any useful literal types to apply during the second pass, resulting in spurious inference failures. It feels like we need a special kind of context-sensitive for literals that behaves more like a 'contextually refined' type, where it can still contribute contextual information during the first pass, but can also be refined by contextual information in the second pass to handle this correctly without degrading existing inferences.

**Comment by ahejlsberg** [comment]
The `isContextSensitive` function really has nothing to do with literal types. As the comment on the function states: "Returns true if the given expression contains (at any level of nesting) a function or arrow expression that is subject to contextual typing." It's basically a helper function that is used to determine if we should assign contextual types to parameters without type annotations.

**Comment by ahejlsberg** [comment]
@amcasey I can't seem to find a test called `extractConstant_ContextualType` anywhere. Can you post the code here?

**Comment by amcasey** [comment]
@ahejlsberg It's here: https://github.com/Microsoft/TypeScript/blob/0477f91dbad209809363323042f34926d3a6e175/src/harness/unittests/extractConstants.ts#L267
