### ISSUE TITLE
Allow extending native built-in classes in downlevel compilation

### ISSUE THREAD

**Issue by justinfagnani** [microsoft/TypeScript#20723]
This has been covered in many closed issues, as far back as #1168, but there may be some new developments here that make a solution possible.

Babel has a PR in flight that enables extending native built-ins (including HTMLElement, which is my primary concern): https://github.com/babel/babel/pull/7020

The technique is to wrap the native class with a class whose constructor calls `Reflect.construct` if it exists, ensuring that `new.target` is set properly. Babel's solution tries to statically detect if any extendable built-ins are subclassed in order to trigger wrapping them. It would also be useful to manually configure built-ins to wrap.

This at least lets downlevel output work properly on environments with extendable native classes. In environments without the extendable native classes, polyfills (like the Custom Elements polyfill) can possibly add them.

**Comment by mhegazy** [comment]
Same request in https://github.com/Microsoft/TypeScript/issues/17825, https://github.com/Microsoft/TypeScript/issues/17088, and https://github.com/Microsoft/TypeScript/issues/15397

**Comment by RyanCavanaugh** [comment]
There are very few remaining ES5-only runtimes and the workarounds are well-documented here, so we're not going to invest further in this area.
