### ISSUE TITLE
Error: Class incorrectly extends base class... cannot assign type

### ISSUE THREAD

**Issue by omidkrad** [Microsoft/TypeScript#2073]
Please see comments:

```typescript
interface ObjectHash {
    [key: string]: any;
}

var hash: ObjectHash;

hash = {
	"key": "value"
}

declare class Model {
	defaults: ObjectHash;
}

class MyModel1 extends Model { // Okay
	defaults = hash;
}

class MyModel2 extends Model { // Why ERROR?!
	defaults = {
		"key": "value"
	};
}

class MyModel3 extends Model { // Okay
	defaults: ObjectHash = {
		"key": "value"
	};
}
```

**Comment by DanielRosenwasser** [comment]
I think this might be in discussion in #1373.

**Comment by omidkrad** [comment]
I think it's also a duplicate of #178. It caught me again! But I wanted to follow up on this suggestion:

> I think it would make sense and is more intuitive for contextual typing to apply when overriding a member of the base class. Same way that it works for assignments. Typing of the member on the base class provides the context.

Thanks!
