### ISSUE TITLE
tsconfig.json paths bug .

### ISSUE THREAD

**Issue by xcwen** [Microsoft/TypeScript#20734]
**localhost:~/test_ts$ tsc -v
Version 2.7.0-dev.20171206

**Code**
tsconfig.json
```json
{
  "compilerOptions": {
     "baseUrl": "./",
      "paths": {
          "Hello" : ["src/"]
      }
  }
}
```
src/a.ts
```ts
export default class A {
  message: string = 'Hello!'
}
```
src/b.ts
```ts
import A from 'Hello/a'
export default class B {
  message: string = 'Hello B!'
}
```
exec
```bash
tsc src/b.ts 
```
**Expected behavior:**
no wrong.
**Actual behavior:**
```bash
localhost:~/test_ts$ tsc src/b.ts 
src/b.ts(2,15): error TS2307: Cannot find module 'Hello/a'.
```
test code is here 
https://raw.githubusercontent.com/xcwen/site-lisp/master/test_ts.tar.gz

thank you :>

**Comment by RyanCavanaugh** [comment]
The path mapping you wrote means "*only" match the exact string `Hello`". If you want the behavior described above, you should write `"Hello/*": ["src/*"]`

**Comment by xcwen** [comment]
thank you . great !!!
