### ISSUE TITLE
TS doesn't allow to modify exported variable from a ES6 module

### ISSUE THREAD

**Issue by maximusk** [Microsoft/TypeScript#20746]
**TypeScript Version:**  2.5.2

**Code**

```
// counter.ts
export let c = 0;

// main.ts
import { c } from './counter';

c++;
```

**Expected behavior:**
Variable is modified

**Actual behavior:**
Error:(17, 9) TS2539: Cannot assign to 'c' because it is not a variable.

**Comment by RyanCavanaugh** [comment]
https://stackoverflow.com/questions/39289463/are-import-values-disconnected-from-their-export-values-still-read-only

**Comment by andy-ms** [comment]
Apparently we let you do `import counter = require("./counter"); counter.c++;`.

**Comment by maximusk** [comment]
@RyanCavanaugh , @andy-ms 

Thanks guys
