### ISSUE TITLE
Proposal: Add magic variables like PHP

### ISSUE THREAD

**Issue by acrazing** [Microsoft/TypeScript#20745]
The proposal is compile the global variables like `__CLASS__`, `__FUNCTION__`, `__PROPERTY__` to string according to the context.

For example:

```ts
class Foo {
  public bar() {
    console.log('calling %s::%s', __CLASS__, __FUNCTION__)
  }
}
```

will emit(ES6):

```js
class Foo {
  bar() {
    console.log('calling %s::%s', 'Foo', 'bar')
  }
}
```

This feature will avoid the variable name lossing when use mangle tools like closure compiler or uglifyjs.

Full list of magic variables:

```ts
/**
 * the class name, just accessible in class body
 */
declare const __CLASS__: string

/**
 * the function/method name, just accessible in function body
 */
declare const __FUNCTION__: string

/**
 * the namespace name, just accessible in namespace context
 */
declare const __NAMESPACE__: string
```

**Comment by DanielRosenwasser** [comment]
Unfortunately I think this is out of scope for us as it doesn't fit within the goals of what we're trying to achieve with TypeScript. If you're willing to use the compiler API's transform pipeline, that's one place you could emulate this behavior. Alternatively, you could run it using a separate build tool following TypeScript

**Comment by andy-ms** [comment]
`console.log('calling %s::%s', Foo.name, Foo.prototype.bar.name)`

**Comment by DanielRosenwasser** [comment]
There is also the proposed [`import.meta`](https://github.com/tc39/proposal-import-meta) meta-property.
