### ISSUE TITLE
New Website Logo: Jamendo

### ISSUE THREAD

**Issue by FabianLauer** [Microsoft/TypeScript#20751]
- **Name:** Jamendo
- **Homepage url:** https://www.jamendo.com
- **Brand Guidelines/Licensing:** Please see directory `Jamendo Music` in https://imgjam.com/press/jamendo-presskit.zip
- **Logo:** https://imgjam.com/jamendomusic/welcome/jamendo-music-logo.svg

**Comment by mhegazy** [comment]
Should be available the next time the site is published

**Comment by FabianLauer** [comment]
Thanks! :heart:
