### ISSUE TITLE
No `extends` keyword in IntelliSense for Javascript language mode.

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#20758]
_From @ravshansbox on December 17, 2017 8:42_

No `extends` keyword in IntelliSense for Javascript language mode.

_Copied from original issue: Microsoft/vscode#40371_

**Comment by mjbvz** [comment]
Confirmed that the `extends` keyword does not seem to be returned in cases like `class Foo |`

Same goes for `implements`

**Comment by ravshansbox** [comment]
Are you sure the issue is fixed? I've tested with v.2.7.1 and 'extends' still absent in IntelliSense.

**Comment by ravshansbox** [comment]
![image](https://user-images.githubusercontent.com/1499188/35683300-cc0f882e-0763-11e8-9c7c-ac859f23c012.png)
