### ISSUE TITLE
How to declare Object.observe?

### ISSUE THREAD

**Issue by mblinsitu** [Microsoft/TypeScript#2075]
I can't seem to find a proper declaration of Object.observe.

[StackOverflow](http://stackoverflow.com/questions/13847851/how-do-i-provide-missing-declarations-in-typescript) suggests this:

```
interface Object {
    observe(beingObserved: any, callback: (update: any) => any) : void;
}

Object.observe(o, observer);
```

but it generates the following error with tsc 1.4.1:
```
error TS2339: Property 'observe' does not exist on type 'ObjectConstructor'.
```

This makes sense since `observe` is a static property of the Object class, but since we cannot merge class declarations, I don't see how to declare it as such.

Of course I can use a type-unsafe workaround, but it's frustrating:
```
(<any>Object).observe(…)
```

Is there a better way?

**Comment by NN---** [comment]
You have to use the interface, not the variable:

```typescript
interface ObjectConstructor  {
  observe(beingObserved: any, callback: (update: any) => any) : void;
}
```

**Comment by mblinsitu** [comment]
Thanks, this works.
I though I had tried this and it didn't know about ObjectConstructor, but now it works.

It would be good to have it in the library though.

**Comment by danquirk** [comment]
Based on https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/observe it's not standardized or widely supported enough to put in lib.d.ts at this time.
