### ISSUE TITLE
[ts2.6 regression] TypeScript fails to infer overloaded function

### ISSUE THREAD

**Issue by mprobst** [Microsoft/TypeScript#20753]
**TypeScript Version:**  2.6.2

**Code**

```ts
class MyArray<T> {
  internalStorage: Array<T>;

  reduce<U>(
      callbackfn:
          (previousValue: U, currentValue: T, currentIndex: number,
           array: ReadonlyArray<T>) => U,
      initialValue: U): U;
  reduce(
      callbackfn:
          (previousValue: T, currentValue: T, currentIndex: number,
           array: T[]) => T,
      initialValue?: T): T {
    return this.internalStorage.reduce(callbackfn, initialValue);
  }
}
```

**Expected behavior:**

Compile! :-) At least it did, in TS 2.5.

Though this code might also just not be correct, given that the `<T>` version of `reduce` is not the union of all possible implementations. Still worth noting as a regression maybe?

**Actual behavior:**

```
error TS2322: Type 'T | undefined' is not assignable to type 'T'.
  Type 'undefined' is not assignable to type 'T'.
```

**Comment by RyanCavanaugh** [comment]
This function only has one overload; did you intend that? The implementation signature is not visible.

This is definitely not a correct implementation since it claims to always produce a `T` but will return `undefined` if `internalStorage` is `[]` and `initialValue` isn't provided.

**Comment by mprobst** [comment]
Don't blame me, this is just some code I found in our monorepo when trying to upgrade TS :-)

That being said, I think this is trying to just copy `Array.prototype.reduce`. That has three overloads:

```
    reduce(callbackfn: (previousValue: T, currentValue: T, currentIndex: number, array: T[]) => T): T;
    reduce(callbackfn: (previousValue: T, currentValue: T, currentIndex: number, array: T[]) => T, initialValue: T): T;
    reduce<U>(callbackfn: (previousValue: U, currentValue: T, currentIndex: number, array: T[]) => U, initialValue: U): U;
```

Which is not quite correct it seems:

```
> [].reduce((prev, curr) => {})
TypeError: Reduce of empty array with no initial value
```

**Comment by mhegazy** [comment]
Looks like this was caused by the change in https://github.com/Microsoft/TypeScript/issues/18986.
