### ISSUE TITLE
BUG,  Type is missing

### ISSUE THREAD

**Issue by xiaoxiaojx** [microsoft/TypeScript#20752]
# TypeScript Version: 2.6.2

## Code
> (I want to write a common method to bind this, as shown below)
```
export function autoBindMethods<T, K extends keyof T>(methods: K[], _this: T): void {
    methods.forEach(method => {
        if (typeof _this[method] === "function") {
            _this[method] = _this[method].bind(_this);
        }
    });
}
```
> (But did not pass the inspection, This error message does not have the property "bind" on type "T [K]". I think T[K] is missing the type, And I can't constrain the type of T[K]. So I can only write like this)
```
_this[method] = (_this[method] as any).bind(_this);
```
## Expected behavior:
> I want to know if there is a mechanism to restrict the type of T[K], Even if there is no, why can't passed inspection like this (typeof _this[method] === "function"), So I think this may be a type checking bug.

## Actual behavior:
> type “T[K]” does not have the property "bind"

**Comment by andy-ms** [comment]
You can accomplish what you want by constraining `T` to only contain functions at the given keys:
```ts
function autoBindMethods<K extends string>(methods: ReadonlyArray<K>, t: { [key in K]: Function }): void {
    for (const m of methods) {
        t[m] = t[m].bind(t);
    }
}
autoBindMethods(["a"], { a: 0 }); // Error: 'a' not a function
autoBindMethods(["a"], { a() {} }); // Works
```

That said, the following does seem like a bug:
```ts
declare const val: {};
if (typeof val === "number") {
    val.toExponential(); // Works
}
if (typeof val === "function") {
    val.call(); // Error: val is 'never'
}
```

**Comment by RyanCavanaugh** [comment]
Can also write
```ts
export function autoBindMethods<T, K extends keyof T>(methods: K[], _this: T): void {
    methods.forEach(method => {
        const m = _this[method];
        if (typeof m === "function") {
            _this[method] = m.bind(_this);
        }
    });
}
```

It's intended that narrowing doesn't apply to indexed accesses where the key is potentially mutable.
