### ISSUE TITLE
Clear message that .ts file is not included to project in VisualStudio

### ISSUE THREAD

**Issue by PFight** [microsoft/TypeScript#20764]
In VisualStudio 2017 Enterprise 15.3.5 when ts file is not included by tsconfig.json, it is dificult realise where is the problem. 

For example, I have next tsconfig.json:

    {
         "compilerOptions": {
             ...
            "experimentalDecorators": true,
         },
        "include": [
            "Content1/**/*.ts*"
        ]
    }

And I have ts file  in folder Content (not Content1). I open it in VisualStudio and see many strange errors:

![image](https://user-images.githubusercontent.com/198847/34128043-6aac0098-e450-11e7-9f5d-293de0b1eb93.png)

Intelllicesnse says that my tsconfig has no experimentalDecorators flag, but I look at config, and flag is there. It is dificult to understand, that my mistake was that current file is not under "include" pattern. 

It would be great if VisualSudio will hint, that file is not included by tsconfig somehow... I spent hours until understood the reason.

**Comment by mhegazy** [comment]
VSCode experimented with similar ideas and they ended up removing the hint. instead they added a command to go to the tsconfig.json that configures a given file, and fails if the file is not included in any. 

We are open to ideas to make this better though..

**Comment by PFight** [comment]
I think, core problem is difference between "project" in VS meaning, and "project" in TypeScript meaning. My file included in VS project, but not included in TS. The combo-box at the top-left indicates project, where file is located. For the normal ts files we have there hint like this:

![image](https://user-images.githubusercontent.com/198847/34842640-254a1406-f71d-11e7-96ed-f07f63525ffe.png)

So, there is expilicit reference, that file is in tsconfig project. So I suggest add similar hint for ts files, when they are not in project like this:

![image](https://user-images.githubusercontent.com/198847/34842777-8c611d92-f71d-11e7-98dc-a28ebcc5df9c.png)

**Comment by RyanCavanaugh** [comment]
We're working on improving this experience (stay tuned on the official VS channels) and are no longer tracking VS-specific issues in this repo.
