### ISSUE TITLE
Support for destructuring assignment without parentheses.

### ISSUE THREAD

**Issue by KostyaTretyak** [Microsoft/TypeScript#20761]
**TypeScript Version:**  2.7.0-dev.20171216

**Code**

```ts
let tokens: any, links: any;

{tokens, links} = {tokens: 'some', links: 'else'};
```

**Expected behavior:**

Works witout errors.

**Actual behavior:**

![typescript-errors](https://user-images.githubusercontent.com/2286306/34123703-0af1adc2-e439-11e7-8005-60322befdd8a.png)

**Description of errors from left to right:**

Error near setting `tokens`:
> Left side of comma operator is unused and has no side effects.

Error near the sign equals:
> Declaration or statement expected.

Error near propery `tokens`:
> Unused label.

Error near value `'some'`:
> ';' expected.

This code works without errors inside console Google Chrome v63.0.3239.108 and node v8.9.3.

**How now works with TypeScript**

This expression works if it is taken in parentheses, but more intuitively it is perceived without round parentheses:
```ts
let tokens: any, links: any;

({tokens, links} = {tokens: 'some', links: 'else'});
```

**Comment by RyanCavanaugh** [comment]
> This code works without errors inside console Google Chrome v63.0.3239.108 and node v8.9.3.

?

![image](https://user-images.githubusercontent.com/6685088/34125307-af459aa4-e3ea-11e7-988d-0a258cd575ed.png)

```
> var tokens, links;
undefined
> {tokens, links} = {tokens: 'some', links: 'else'};
...
```
Babel:
![image](https://user-images.githubusercontent.com/6685088/34125332-c9c305ce-e3ea-11e7-93f2-7227210f6c49.png)

**Comment by RyanCavanaugh** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment

![image](https://user-images.githubusercontent.com/6685088/34125487-3c09e238-e3eb-11e7-902f-0811b4ed7bc3.png)

**Comment by KostyaTretyak** [comment]
Hmm, without `;` works, but with it not works (node also):
![typescript-chrome](https://user-images.githubusercontent.com/2286306/34125834-44d5eace-e440-11e7-9cad-c401aa5cbf11.png)
