### ISSUE TITLE
typeof aClass is not a subtype of typeof Object

### ISSUE THREAD

**Issue by mblinsitu** [Microsoft/TypeScript#2077]
In [this discussion](http://typescript.codeplex.com/discussions/403602) it is stated that `typeof aDerivedClass` is a subtype of `typeof aBaseClass`.

However, it does not seem apply to `typeof Object`:

```
class A {…}
class B extends A {…}

function f(cls: typeof A) {…}
function g(cls: typeof Object) {…}

f(A); // OK
f(B); // OK
g(A); // Argument of type 'typeof A' is not assignable to parameter of type 'ObjectConstructor'.
g(B); //Argument of type 'typeof B' is not assignable to parameter of type 'ObjectConstructor'.
```

This does not seem consistent to me, since A derives from Object. 
Am I missing something?

**Comment by danquirk** [comment]
```Object``` in this case refers to this definition in lib.d.ts:
```ts
interface ObjectConstructor {
    new (value?: any): Object;
    (): any;
    (value: any): any;
    // other stuff
}
declare var Object: ObjectConstructor;
```
So you can see why A and B would not satisfy an argument of type ObjectConstructor. Just say:

```function g(cls: Object) {}```

**Comment by mblinsitu** [comment]
I understand the explanation, but I thought that 
```
class A { … }
```
was a shorthand for 
```
class A extends Object {…}
```
and therefore that `typeof Object` should be the type of all classes, in the same way that `typeof A` is the type of all classes that derive from `A` (including `A` itself).

While your solution works, `cls: Object` is a much larger type than what I want: it's the type of all objects (including classes) vs. the type of all classes (but not their instances). Indeed, `g({x:1})` is correct, typewise.

So is there a way to describe the type of all classes?
It seems that conflating the class and the constructor function under the same name creates some confusion here…

**Comment by danquirk** [comment]
If you only want a type that accepts constructor functions then you want something more like:
```ts
function g(cls: Function) {}
g(A); // ok
g(new A()) // error
```
This accepts non-constructor functions as well though. If you have a specific set of construct signatures in mind you can do something like:
```ts
class A { foo: string }
class B { constructor(x: number) {}}

function g(cls: new() => any)
function g(cls: new(x: string) => any) 
function g(cls: any) {}

g(A); // ok
g(B) // error
g(new A()); // error
```

**Comment by RyanCavanaugh** [comment]
`Object` is not a universal base type like it is in C#.

It is hopefully obvious that `typeof A` cannot be a subtype of `typeof Object` because `typeof A` is missing all the built-in members of `Object` like `keys` and `getPrototypeOf`.

**Comment by mblinsitu** [comment]
Thank you both for your answers. I am new to TypeScript, but have used JavaScript and a bunch of OO languages extensively. So I'm still wrapping my head around some things.

@danquirk: I guess I am not used to classes not being objects, i.e., instances of their metaclass as in Smalltalk, but simply constructor functions. Still, it feels unnatural that the hierarchy of class types (`typeof A`) does not have a root - or rather that the root does not seem to have a name.

@Ryan: While I understand that `Object` is not a base type of, e.g., numbers, it is a base type of all objects, isn't it? (Oh wait! see at the end of the message…) 
So if `typeof B` is a subtype of `typeof A` when `B` extends `A`, shouldn't `typeof A` be a subtype of `typeof Object`? 
As for built-in members of Object, such as `keys`, they should be considered static members of the `Object` class, in which case they would not be part of `typeof Object`.

I guess what I am challenging here is the way `Object` and `ObjectConstructor` are declared in TypeScript, which is not entirely consistent with how other classes are transpiled.

One last thing that confuses me:
```
var o: Object;
o = 2;
```
does not produce a type error. Why?

**Comment by RyanCavanaugh** [comment]
> So if typeof B is a subtype of typeof A when B extends A, shouldn't typeof A be a subtype of typeof Object? 

Classes do not implicitly extend from Object. `Object` the type is just another type for the most part, other than its role in apparent type (see the spec). `Object` the value is not special at all in TypeScript.

 > they should be considered static members of the Object class, in which case they would not be part of typeof Object.

`typeof Object` *means* "the static members of `Object`".

> [`o = 2`] does not produce a type error. Why?

Because the apparent type of `2` has all the members of `Object` (by definition). The behavior here is basically to emulate the fact that you can do things in JavaScript like `2..hasOwnProperty(...)` and have the primitive get automatically converted to their Object-typed equivalents.

You can think of the "root class" like this:
```ts
interface RootClass {
	new(...args: any[]): { constructor: {}; };
}

class A {
	constructor(x: string) {}
}

function takeClass(x: RootClass) { }

takeClass(A); // OK
takeClass({}); // Error
takeClass(4); // Error
```

**Comment by danquirk** [comment]
A class introduces a constructor function which is an object. That is how JavaScript works and how TypeScript must model it.

Object is the base type of all types, including numbers. 

The reason ```Object``` and ```ObjectConstructor``` are written as they are (along with the rest of lib.d.ts) rather than as a class is because classes in TypeScript cannot be re-opened while interfaces can. If you want to add new functionality to ```Object``` you can do so by saying:

```ts
interface Object {
    myNewCoreMethod(): number;
}
```
but you could not do this if Object were a class (there's an open suggestion to allow classes to be re-opened this way too).

**Comment by mblinsitu** [comment]
Thank you guys, this is most helpful. I will certainly use the definition of `RootClass`.

I hadn't realized that `2..hasOwnProperty(…)` was legal in plain JS.
That makes `Object` a weird dude indeed!

And yes, it would be great to be able to reopen classes…
