### ISSUE TITLE
Suggestion: First-class support for identifier types

### ISSUE THREAD

**Issue by Firehed** [Microsoft/TypeScript#20770]
Background: when working with relational data in a web application (e.g. client-side representation of entities in a SQL database), most entities will have one or more identifier values, in the form of primary and foreign keys. When declaring the types of these entities in Typescript, it would be really beneficial to be able to strictly define the different identifiers separately to prevent accidental swapping of values.

Proposal: the addition of some kind of built-in `Id<T>` type that is treated as type-equivalent for a given `T`, but not substitutable across different types of `T`.

In your type file, the goal is to do something like this:

```ts
declare type UserId = Id<User> // exact name/mechanics tbd
declare type GroupId = Id<Group>

declare interface User {
  id: UserId
  // ...
}
declare interface Group {
  id: GroupId
  // ...
}
declare interface Membership {
  userId: UserId
  groupId: GroupId
  // ...
}
```

Then, in your code, the following example would be a type error:
```ts
const user: User = { ... }
const group: Group = { ... }
const membership: Membership = {
  userId: user.id,
  groupId: user.id, // whoops! "Type Id<User> not assignable to type Id<Group>"
}
```

Current user-space options:

Simple type aliases for (typically server-generated) opaque identifiers don't do the job here, e.g. `type UserId = string`, since the aliases resolve to the same underlying type (a string, in this case). It looks pretty in your definitions and possibly your IDE, but the example above will not actually generate an error.

A more complex definition avoids the issue of interchangeability, but forces additional complexity throughout the application:
```ts
declare interface UserId {
  value: string
  type: 'user'
}
declare interface User {
  id: UserId
  // ...
}
// Note use of {id.value} instead of {id}
function getUserFromServer(id: UserId): User {
  // json = GET /user/{id.value}
  // return { id, ...json }
}
function persistUserToServer(user: User) {
  // POST /user/{user.id.value}
}
```

It's possible to hack it into something workable with [nominal typing](https://basarat.gitbooks.io/typescript/docs/tips/nominalTyping.html):
```ts
declare type Id<T> = string & { type: T }

declare type UserId = Id<'user'>
declare type GroupId = Id<'group'>
```

This approach works basically by lying to the compiler about the actual definition (in fact, this should resolve to a `Never` type I believe) and solving this at the edges with lots of type casting. It gets the job done, but feels clumsy and can result in unit testing especially being quite painful.

Having a built-in type that works mechanically similar without the hacks would help a lot when developing more complex software in TS. To be fair, this is not a solved problem in numerous other type-safe languages either (e.g. using a `typealias` declaration in Swift has exactly the same problem as `declare type SomeId = string`, but some [cleverness with generics](http://tom.lokhorst.eu/2017/07/strongly-typed-identifiers-in-swift) solves it properly)

So far as I'm aware, the only potential BC issue by doing this would be the introduction of a new type, which could collide with a user-defined type of the same name. Given the nature of the problem, I believe that most user who would be impacted by such a change would be minimally impacted since they are likely to be attempting to solve the problem in user-space.

I hope this is something you'll consider supporting in future versions of Typescript!

**Comment by ajafff** [comment]
Duplicate of #202?

**Comment by RyanCavanaugh** [comment]
I don't see any difference between this and the nominal typing issue; if there is, please clarify (otherwise close). Thanks!

**Comment by Firehed** [comment]
Agreed they're more or less identical - in fact [your comment](https://github.com/Microsoft/TypeScript/issues/202#issuecomment-329914167) in that thread covers basically this exact case. Thanks!
