### ISSUE TITLE
Tagged union inference in mapped type with generic key

### ISSUE THREAD

**Issue by felipeochoa** [Microsoft/TypeScript#20775]
**TypeScript Version:**  2.6.2; Playground

**Code**

```ts
interface T {
    a: { k: 'n', v: number },
    b: { k: 's', v: string },
}

function f<K extends 'a'|'b'>(t: T[K]) {
    if (t.k === 'n') {
        return t.v * 5;
    } else {
        return t.v.charCodeAt(0);
    }
}
```

**Expected behavior:** `t` should be narrowed so that the two clauses are accepted by the compiler

**Actual behavior:** `t.v` is typed as `string | number` in both branches.

This is similar to #17930, but this issue adds the generic `K` to the mix.

**Comment by DanielRosenwasser** [comment]
I don't think you need `K` in this example.

```ts
interface T {
    a: { k: 'n', v: number },
    b: { k: 's', v: string },
}

function f(t: T[keyof T]) {
    if (t.k === 'n') {
        return t.v * 5;
    } else {
        return t.v.charCodeAt(0);
    }
}
```

**Comment by felipeochoa** [comment]
I realize `K` is superfluous here, but this was an illustrative example. In the real case, I'm using mapped types to narrow multiple values simultaneously. The real function is more like:

```ts
function f<K extends 'a'|'b'>(k: K, t1: T1[K], t2: T2[K])
```
which I type that way to ensure T1 and T2 are compatible (i.e. correspond to the same union case).
