### ISSUE TITLE
Minor issue: ECMAScript regex literal flags can be unicode escapes but TS doesn't support this

### ISSUE THREAD

**Issue by zhuravlik** [Microsoft/TypeScript#20777]
Was playing around with regular expression literals in JavaScript, and noticed that TypeScript doesn't support [unicode escape sequences in position of regex flags](https://tc39.github.io/ecma262/#prod-RegularExpressionFlags). Of course, this is a very minor issue, but TypeScript is supposed to be a syntactic superset of ECMAScript.

Regex flags production is:
```
 RegularExpressionFlags ::
          RegularExpressionFlags IdentifierPart 
```

IdentifierPart production is:
```
IdentifierPart ::
          UnicodeIDContinue
          $
          _
          \UnicodeEscapeSequence
          <ZWNJ>
          <ZWJ>
```

**Code**

```ts
var z = /aa/\u0075;   // should be equivalent to '/aa/u'
```

**Expected behavior:**
Code is valid.

**Actual behavior:**
Code is non-compilable.

**Comment by DanielRosenwasser** [comment]
In general, we don't down-level compile regular expressions, but we should at least parse them.

**Comment by weswigham** [comment]
@DanielRosenwasser This isn't a downlevel issue, even, this is a parse issue. Reading _more_ of the spec than mentioned here, we _should parse it, [but](https://tc39.github.io/ecma262/#prod-RegularExpressionFlags):
```
11.8.5.1Static Semantics: Early Errors
RegularExpressionFlags::RegularExpressionFlagsIdentifierPart
It is a Syntax Error if IdentifierPart contains a Unicode escape sequence.
```
