### ISSUE TITLE
Building project requires redicolous amounts of memory

### ISSUE THREAD

**Issue by zlepper** [Microsoft/TypeScript#20778]
**TypeScript Version:**  2.6.2
Building with the next version atm crashes due to unknown jsdoc parameters. And the memory issue still seems to be happening in 2.7 either way, according to my joblist. 
**Node version:** v8.9.1, 6.12.2, 9.3.0

**Code**
I have no idea exactly what code causes this

**Expected behavior:**
I shouldn't need 8 GB of RAM dedicated to node to be able to compile

**Actual behavior:**
I need 8 GB dedicated to node. 

**Notes**
As far as I can see, this has to be caused by typescript. It happens in both our karma and webpack builds when using TS. `tsc` by itself crashes with out of memory. The project builds without issues when using vanilla js. 
A head snapshot can be found here: https://digieyez-my.sharepoint.com/personal/rhdh_digidom_dk/_layouts/15/guestaccess.aspx?docid=034a7567c511e484db9edcd37104d8465&authkey=AUaacCMahU7fQT3NGDm5rEk&e=79a3a76d24f44e1c92f04f7413aa2edf I sadly can't attach it to the issue, as it is too big, even when compressed.

**Comment by RyanCavanaugh** [comment]
Any way to reproduce this would be extraordinarily helpful. A heap snapshot investigation is going to take a long time. Can you email us a zip file?

**Comment by zlepper** [comment]
I will see if I can pull some strings (politics) so I can send the code. Would you need anything other than all the ts code (and package.json and all that)?

**Comment by RyanCavanaugh** [comment]
Nope, that should be sufficient. ryanca@microsoft.com ; we'll delete the files once we have a repro

**Comment by zlepper** [comment]
I have send you an email with the sources.

**Comment by RyanCavanaugh** [comment]
Got it, thanks! On holiday break for a few days but will check it out when I get back

**Comment by zlepper** [comment]
Have you been able to check anything?

**Comment by RyanCavanaugh** [comment]
@zlepper looking now. Apologies for the delay

**Comment by RyanCavanaugh** [comment]
I'm not able to repro the problem. Steps:
 1. Unzip the file
 2. Run `npm install`
 3. Run `tsc`

Result: Finishes in ~15 seconds, maxes out at 500 MB memory usage, issues errors about not being able to certain files because they'd overwrite existing files on disk

**Comment by zlepper** [comment]
So, nuking the `node_modules` folder for the millionth time, and then doing `npm install` again seems to finally have fixed the issue. Must have been some bad install of _something_
