### ISSUE TITLE
Abstract method implementation signatures aren't checked

### ISSUE THREAD

**Issue by dploeger** [Microsoft/TypeScript#20779]
**TypeScript Version:**  2.7.0-dev.201xxxxx

**Code**

```ts
abstract class Animal {
  protected abstract _getType(withRace: boolean): string
  public greet(): void {
  	console.log(this._getType(true))
  }
}

class Dog extends Animal {
  protected _getType(): string {
  	return 'Dog'
  }
}

let myDog = new Dog()
myDog.greet()
```

**Expected behavior:**

I'm not quite sure, but as the abstract method implementation Dog#_getType() has the wrong signature (doesn't match the abstract method interface in Animal) it should break the transpilation.

**Actual behavior:**

The code transpiles just fine.

**Comment by andy-ms** [comment]
It's allowed for a method in a subclass to have a broader type than the method in the super class.
The type `() => string` is a subtype of `(withRace: boolean) => string`, because you can pass an argument and it will just be ignored.

**Comment by dploeger** [comment]
Oh, okay. Thanks. That should be noted in the documentation then, because other languages (i.e. Java) do that differently and one could expect that. (At least I did 😄 )

**Comment by RyanCavanaugh** [comment]
https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-functions-with-fewer-parameters-assignable-to-functions-that-take-more-parameters

**Comment by dploeger** [comment]
Ahhh. Yes. Understood. Should've kept the Javascript background in mind. Thanks.
