### ISSUE TITLE
request to change order of import syntax

### ISSUE THREAD

**Issue by gregveres** [Microsoft/TypeScript#20773]
This isn't a bug and it should probably be sent to the javascript guys but I really don't know where to send javascript syntax requests....

I have been getting frustrated with import syntax.  With good tooling - like VS, the syntax is backwards. Rather than typing

`import { className } from "module_path";`
it would be much more efficient to have the syntax be:

`import "module_path" into { className}`

The reason for this is that at the time you are typing className, the system has no idea what classNames are available. It is only after you specify module_path, that the tooling can load the module and figure out what classNames are available. 

So I am suggesting that the import syntax be changed to better support developers now that we have good tooling with things like intellisense. The import into syntax seems just as readable and just as understandable as import from.

**Comment by andy-ms** [comment]
TypeScript can't change behavior of JavaScript -- see the [design goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).
I agree that the syntax is unfortunate, but a workaround is to type `import {} from "module_path";` and then move the cursor inside of `{}` and ask for completions.
Another way to do it is to simply start using `className` in the code and use a codefix to have TypeScript add the import for you -- this helps you avoid having to scroll all the way to the top of the file.

**Comment by gregveres** [comment]
Yea that is the answer I expected really. But as you say the syntax of javascript is unfortunate. 
typing import {} ... and then going back for the completions is exactly what I do and it is painful. :(

I hadn't thought to do the second work around. I will give that a try.
