### ISSUE TITLE
jsdoc failure in .ts file 

### ISSUE THREAD

**Issue by shynome** [Microsoft/TypeScript#20774]
**TypeScript Version:**  2.6.2
**VSCode Version:** 1.19.0

**Code**

```ts
/**
 * @param {string} nonPrimitive
 */
function test(nonPrimitive) {}

test(1)
```

**tsconfig.json**

```json
{
  "compilerOptions": {
    "checkJs": true,
    "allowJs": true,
    "target": "es5",
    "moduleResolution": "node",
    "module": "es2015",
    "strict": true,
    "noImplicitThis": true
  }
}
```

**Expected behavior:**
![image](https://user-images.githubusercontent.com/17316043/34138558-21981f9e-e4ab-11e7-8189-cce9ec69d382.png)

**Actual behavior:**
![image](https://user-images.githubusercontent.com/17316043/34138550-15400ffe-e4ab-11e7-93b5-65a024e5cb47.png)

**Comment by ajafff** [comment]
Since you can add type annotations in typescript, it does not use JSDoc for types. This is by design.
You need to use `nonPrimitive: string` instead.

IIRC there's a quickfix that converts JSDoc types to type annotations.

**Comment by shynome** [comment]
In some cases my project team can't use the compile tools , And now I have a problem in vue typescript component , in .ts file the vue component `this` type is right, but if I rename the ext `.ts` to `.js`, this vue component `this` type is any, I don't know why. 
Because typescript is a superset of javascript, so only write javascript is good, but I found I can't define type by jsdoc, it bothered me and make me write javascript without typescript help .
The git url is can report my problem

**Comment by shynome** [comment]
yeah, I find out jsdoc since begin is design for js not ts , so ts file can't use jsdoc to define type .
