### ISSUE TITLE
'window' is no longer tracked by intellisense as of 1.18

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#20783]
_From @realratchet on December 19, 2017 8:32_

I've been looking for someone to report this issue as of 1.18 release but 1.19 is already out and no one seems to notice. When assigning extra variables to '_window_' IntelliSense no longer picks up on it. This is an issue when trying to add something to global namespace.

I've been opting for using 1.17 until this is resolved. I could resolve this by changing the way code is structured however, that's not up to me and I'm stuck with this.

- VSCode Version: 1.18+
- OS Version: Debian Jessie

Steps to Reproduce:

```
// Example 1
import THREE from "three";
THREE.Object3D  // Works, but it's not part of global namespace.

// Example 2 (this is how code is set up)
window.THREE = window.THREE || require("three");
window.THREE.Object3D // Doesn't work

// Example 3
window.THREE2 = require("three");
window.THREE2.Object3D // Doesn't work.
```

Reproduces without extensions: Yes

_Copied from original issue: Microsoft/vscode#40498_

**Comment by mjbvz** [comment]
I don't recall `window.X = ...` assignments ever working (see #10868). Did they previously or did the typings for three.js perhaps change?

**Comment by RyanCavanaugh** [comment]
I don't think that's ever worked

**Comment by realratchet** [comment]
_code_1.17.2-1508162334_amd64.deb_ and prior had no such problems.
This problem appeared in _code_1.18.1-1510857349_amd64.deb_ and following releases with, 1.18 has IntelliSense improvements listed under key changes.

**Comment by mhegazy** [comment]
You can also add a .d.ts file to your project that declares `THREE` on your `Window`:

```ts
// global.d.ts

interface Window {
    THREE: typeof THREE;
}
```

**Comment by realratchet** [comment]
@mhegazy for a moment I was ecstatic because it worked, so I updated to 1.19 and it still failed in 1.19 despite working on 1.17

```
import THREE from "three"

interface Window {
    _THREE: typeof THREE;
}
                            // 1.17     1.19
THREE.AddEquation           // valid    valid
window._THREE.AddEquation   // valid    invalid
_THREE.AddEquation          // valid    invalid
```

**Comment by mhegazy** [comment]
it is working for me on latest. can you share your project, or some steps to get to the same state you are looking at?
