### ISSUE TITLE
Completion list for keyof T is empty when T is inferred

### ISSUE THREAD

**Issue by s-ve** [Microsoft/TypeScript#20782]
**TypeScript Version:**  2.7.0-dev.20171219

**Code**

```ts
function getProperty<T, K extends keyof T>(o: T, name: K): T[K] {
  return o[name];
}

const pizza = {
  size: 'xl',
  name: 'quattro stagioni'
};

getProperty(pizza, '{cursor}');
```

**Expected behavior:**
Completion list at `{cursor}` shows `size` and `name`

**Actual behavior:**
Completion list at `{cursor}` is empty

[Playground link](https://www.typescriptlang.org/play/#src=function%20getProperty%3CT%2C%20K%20extends%20keyof%20T%3E(o%3A%20T%2C%20name%3A%20K)%3A%20T%5BK%5D%20%7B%0D%0A%20%20return%20o%5Bname%5D%3B%0D%0A%7D%0D%0A%0D%0Aconst%20pizza%20%3D%20%7B%0D%0A%20%20size%3A%20'xl'%2C%0D%0A%20%20name%3A%20'quattro%20stagioni'%0D%0A%7D%0D%0A%0D%0AgetProperty(pizza%2C%20'')%3B)

**Comment by DanielRosenwasser** [comment]
Looks like a duplicate of #14812

**Comment by s-ve** [comment]
Closing in favor of #14812
