### ISSUE TITLE
Enum literal cannot contain concatenated string

### ISSUE THREAD

**Issue by evmar** [Microsoft/TypeScript#20784]
**TypeScript Version:**  2.7.0-dev.20171216 and older

**Code**

```ts
enum Test {
  A = "a very long string value, such that you want to make it " +
    "span multiple lines to meet some column limit"
}
```

**Expected behavior:**
Accepted.

**Actual behavior:**
`error TS2352: Type 'string' cannot be converted to type 'Test'.`

Adding some 'as Test' annotation didn't seem to work.

Workarounds:
- put it all on one very long line
- wrap in parens, add an "as any"

**Comment by DanielRosenwasser** [comment]
Out of curiosity, how are you currently planning on using the multiline enums? Something long enough that you hope nobody accidentally types it?

**Comment by evmar** [comment]
We have code that uses enums for collections of long string constants.  Not sure if it's the right use of enums though.

E.g. something like:

```
enum CompilerError {
  BAD_IMPORT: "bad import {}. try doing blah blah blah " +
    "or consult documentation at blah blah blah and so on"
}
```

Note that it's not exactly multiline (we want the resulting string to have no embedded newlines) so we can't use backticks for a multiline string.  We just have multiple lines with a + in the middle for code style reasons (column limit).

**Comment by rozzzly** [comment]
Enums are probably not the best suited for this. Here is what I would do.

```typescript

export type ERROR_ONE = 'ERROR_ONE';
export const ERROR_ONE: ERROR_ONE = 'ERROR_ONE';

export type ERROR_TWO = 'ERROR_TWO';
export const ERROR_TWO: ERROR_TWO = 'ERROR_TWO';

export type ERROR_IDs = (
    | ERROR_ONE
    | ERROR_TWO
);

export const ERROR_MESSAGES: { [E in ERROR_IDs]: string; } = {
    [ERROR_ONE]: 'long ERROR_ONE message',
    [ERROR_TWO]: 'long ERROR_TWO message'
};

function getMessage(errorID: ERROR_IDs): string {
      return ERROR_MESSAGES[errorID];
}

console.log(getMessage (ERROR_ONE)); // $> long ERROR_ONE message

```

Neat things:

You will get completions
```typescript
getMessage( ** here ** )
```

Plus, if you define add a new `ERROR` to `ERROR_IDs` but not `ERROR_MESSAGES`, the compiler will throw a fit.

**Comment by evmar** [comment]
There's lots of alternatives here but our users typically reach for enum as
the intuitive one. It's hard to convince people that repeating each
variable name seven times (like you do in your example) is worth it.

**Comment by rozzzly** [comment]
I agree. **But enums in TypeScript are kinda meh.** There have been like 100+ issues opened about enums, 
seeking for different functionality but they really haven't evolved much since they first debuted. 

Best suggestion I can give is to write a script (or snippet for your prefered IDE) to generate that boilerplate for you. @chriseppstein just made an interesting suggestion here: https://github.com/Microsoft/TypeScript/issues/20898#issuecomment-355362115 which could also be compatible with string literals and would bring that 7 down to a 3. Not ideal, but eh

**Comment by RyanCavanaugh** [comment]
Accepting PRs for this one. Should be reasonably straightforward as similar mechanics are already in place for numeric enum computations.

**Comment by mhegazy** [comment]
thanks @Kingwl!
