### ISSUE TITLE
Incorrect type inferred for 'this' in instance methods

### ISSUE THREAD

**Issue by Cakez0r** [Microsoft/TypeScript#2078]
Given a class

    class Foo {
        private baz: string;
    
        public bar() {
            var x = this;
        
            console.log(x.baz);
        }
    }

The compiler infers 'this' to be of type 'Foo' within the 'bar' function. However, the type of 'this' is not guaranteed to be 'Foo'.

Consider

    var y = new Foo();
    setTimeout(y.bar, 1000);

Given this possibility, should the type of 'this' within 'bar' be 'any' instead of 'Foo'?

**Comment by danquirk** [comment]
In practice the majority of the time people use ```this``` in a class they'll want it to be typed as ```Foo```. There're ways around this as you noted but it would be unfortunate to degrade the core class scenarios for that. There are a variety of improvements we are hoping to make to ```this``` typing one day though, see https://github.com/Microsoft/TypeScript/issues/513
