### ISSUE TITLE
IntelliSense/completions within comments

### ISSUE THREAD

**Issue by MaleDong** [Microsoft/TypeScript#208]
It would be better if you can add comment intellisense for TypeScript, let's say if I've defined a function below (Just a sample, please ignore the error syntaxes if I have)

```ts
function SayHello(word:string):void
{
   //Contents ignored
}
```
So when I type "/*" at the beginning of "function" and press Enter, I should get an intellisense list of parameters such as "word" to choose and write comments(just like what I can do in C# or VB.NET)

```ts
/*
function SayHello(word:string):void
{
   //Contents ignored
}
```
Any other ideas or suggestions?

**Comment by DanielRosenwasser** [comment]
We do have comment template generation now, and completion for JSDoc tag names such as `param` at the beginning of an `@`, but we still don't give parameter name completions for an existing comment.

**Comment by mhegazy** [comment]
![scafolding](https://cloud.githubusercontent.com/assets/8000722/10890184/6e7bd1c2-814b-11e5-974b-83bccbbfa0da.gif)

**Comment by DanielRosenwasser** [comment]
I'm reopening this. The original suggestion was to have actual completions for words, not to have a full comment completion. As I said,

> We do have comment template generation now

But this isn't the original suggestion. The suggestion was to have things like parameter names show up in your comments when above a function definition.

**Comment by mhegazy** [comment]
We already support completions for tag names after `@` and types between `{` and `}` in JS files. 

Please file other suggestions with more details. i core issue here has been addressed.
