### ISSUE TITLE
new object by constructor

### ISSUE THREAD

**Issue by pankleks** [Microsoft/TypeScript#2081]
I get following error:
<code>
TS2351	Cannot use 'new' with an expression whose type lacks a call or construct signature.
</code>

<code>
class A {
constructor() { ... }
refresh() { return new this.constructor; }
}
</code>

new this.constructor works in pure JS.

Thanks:)

**Comment by RyanCavanaugh** [comment]
The type of `constructor` is just `Function`, unfortunately. You can write this instead:
```ts
class A { constructor() {  } refresh() { return new (<typeof A>this.constructor); } } 
```
