### ISSUE TITLE
Iterating on a string enum

### ISSUE THREAD

**Issue by weeco** [Microsoft/TypeScript#20813]
Maybe it is a half question, but I think there is no good way to iterate on a string enum right now.  Please see this Stackoverflow question: https://stackoverflow.com/questions/47896885/iterate-on-string-enum .

Does not work:
```ts
export enum Locales {
  En = 'en',
  Fr = 'fr',
  De = 'de',
  Es = 'es',
  It = 'it',
  Nl = 'nl',
  No = 'no',
  Tr = 'tr',
}

for (const key of Object.keys(Locales)) {
  const locale: string = Locales[key]; // TS error: [ts] Element implicitly has an 'any' type because index expression is not of type 'number'.
  console.log(locale); // Should print 'en', 'fr' and so on
}
```

Am I missing something or is iterating on a string enum without losing type safety really circuitous?

**Comment by RyanCavanaugh** [comment]
`Object.keys` doesn't return `keyof T` (see many duplicates of this) so `key` is just an ordinary `string` as far as the type system is concerned.

You can use `for / in` and this works as expected:
```ts
for (const key in Locales) {
  const locale: string = Locales[key]; // No error
  console.log(locale); // Should print 'en', 'fr' and so on
}
``
Or use `Object.values` from the `es2017` lib target

**Comment by weeco** [comment]
I tried to avoid the for .. in loop as Microsoft's tslint forbids it. Should I disable it for this line? Using Object.values I still face the same error because of `key` (a string) being used as index:

> [ts] Element implicitly has an 'any' type because index expression is not of type 'number'.

**Comment by radoslawn-kainos** [comment]
Hi there. I stumbled upon this issue while looking for a way to verify that a value is a member of a given enum. But the solution given here becomes unreliable with namespaces. Consider this example:
```ts
import { expect } from 'chai'

enum FooBar {
  FOO = 'FOO',
  BAR = 'BAR'
}

namespace FooBar {
  export const somethingElse = 'bogus'
}

describe.only('string-based enum', () => {
  it('supports refining from a string value', () => {
    const a: string = 'FOO'
    const b: string = 'somethingElse'

    const test1: FooBar | undefined = FooBar[a]
    const test2: FooBar | undefined = FooBar[b]

    expect(test1).to.be.equal(FooBar.FOO)
    expect(test2).to.be.equal(undefined)
  })
})
```

Is there any good way to get around this?

**Comment by radekn** [comment]
Hi there. I stumbled upon this issue while looking for a way to verify that a value is a member of a given enum. But the solution given here becomes unreliable with namespaces. Consider this example:
```ts
import { expect } from 'chai'

enum FooBar {
  FOO = 'FOO',
  BAR = 'BAR'
}

namespace FooBar {
  export const somethingElse = 'bogus'
}

describe.only('string-based enum', () => {
  it('supports refining from a string value', () => {
    const a: string = 'FOO'
    const b: string = 'somethingElse'

    const test1: FooBar | undefined = FooBar[a]
    const test2: FooBar | undefined = FooBar[b]

    expect(test1).to.be.equal(FooBar.FOO)
    expect(test2).to.be.equal(undefined)
  })
})
```

Is there any good way to get around this?
