### ISSUE TITLE
String comparison

### ISSUE THREAD

**Issue by rockers7414** [Microsoft/TypeScript#20815]
**TypeScript Version:**  2.6.2

**Code**
```ts
const a = 'XD';
const b = (a === 'XD1' || a !== 'XD2');
```

**Expected behavior:**
The variable b should be the boolean.

**Actual behavior:**
The error I got is as below.
`Operator '!==' cannot be applied to types '"XD1"' and '"XD2"'.`

Online Example:
https://www.typescriptlang.org/play/#src=const%20a%20%3D%20'XD'%3B%0D%0Aconst%20b%20%3D%20(a%20%3D%3D%3D%20'XD1'%20%7C%7C%20a%20!%3D%3D%20'XD2')%3B

**Comment by RyanCavanaugh** [comment]
TypeScript can tell that `a` is *never* `XD1`. If you initialized `a` with something that wasn't known to be `XD`, you wouldn't see that error

**Comment by rockers7414** [comment]
@RyanCavanaugh 
Thanks for the prompt reply.
I expected the variable `b` should be a boolean, whatever the variable `a` is initialized with `XD` or something. In this example, `b` should be `true`.

**Comment by kitsonk** [comment]
One of the main purposes of TypeScript is to catch logic errors.  Even if the code works at runtime, TypeScript is identifying an illogical construct, which likely means there are other logic errors.  If for some reason you want to ignore TypeScript you can cast:

```ts
const a = 'XD';
const b = ((a as any) === 'XD1' || (a as any) !== 'XD2');
```

**Comment by RyanCavanaugh** [comment]
And `b` is indeed of type `boolean`.

**Comment by rockers7414** [comment]
This is my workaround.

```
const a = 'XD';
const b = (a === 'XD1'+'' || a !== 'XD2'+'');
```

**Comment by kitsonk** [comment]
Can you give any logical reason why you are assigning a value to a constant, then forcing the runtime to compare two things that will never be true to generate a boolean value of `true`?  Adding string concatenation to workaround TypeScript is even worse.

Why are you performing compiler abuse?

**Comment by kitsonk** [comment]
Well, no, if you assigned it to a variable (`var` or `let`) TypeScript [will not error](https://www.typescriptlang.org/play/#src=let%20a%20%3D%20'XD'%3B%0Aconst%20b%20%3D%20(a%20%3D%3D%3D%20'XD1'%20%7C%7C%20a%20!%3D%3D%20'XD2')%3B%0A):

```ts
let a = 'XD';
const b = (a === 'XD1' || a !== 'XD2');
```

It will only guard you against illogical comparisons when it can detect they are illogical.  If the variable is mutable, it will not enforce comparison checks.  So again, why are you working around the illogical code?

**Comment by rockers7414** [comment]
Yes, if I use let or the variable is mutable, it will be without the error.

But I don't understand what you mean the result of variable `b` is illogical if the variable `a` is assigned in runtime and `a` could be any string.

**Comment by rockers7414** [comment]
@kitsonk 
I think I got your point. Thanks for your reply.
