### ISSUE TITLE
Type Inference doesn't work correctly

### ISSUE THREAD

**Issue by foisonocean** [Microsoft/TypeScript#20816]
**TypeScript Version:**  2.6.2

**Code**
[live demo](https://www.typescriptlang.org/play/index.html#src=interface%20T%20%7B%0D%0A%20%20%20%20fn%3F%3A%20()%20%3D%3E%20void%3B%0D%0A%7D%0D%0A%0D%0Alet%20a%3A%20T%20%3D%20(function%20()%20%7B%20return%20%7B%7D%20%7D)()%3B%0D%0A%0D%0Alet%20b%3B%0D%0Aif%20(a.fn%20!%3D%20null)%20%7B%0D%0A%20%20%20%20b%20%3D%20()%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20a.fn()%3B%0D%0A%20%20%20%20%7D%3B%0D%0A%7D%20else%20%7B%0D%0A%20%20%20%20b%20%3D%20()%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20console.log('fn%20doesn%5C't%20exist')%3B%0D%0A%20%20%20%20%7D%3B%0D%0A%7D%0D%0Ab()%3B%0D%0A) (you need to turn on strict mode)
```ts
interface T {
    fn?: () => void;
}

let a: T = (function () { return {} })();

let b;
if (a.fn != null) {
    b = () => {
        a.fn();
    };
} else {
    b = () => {
        console.log('fn doesn\'t exist');
    };
}
b();
```

**Expected behavior:**
Should not be an error here.

**Actual behavior:**
![image](https://user-images.githubusercontent.com/15059605/34203411-f796c158-e5b5-11e7-9fbb-c4615282f46f.png)

**Comment by kitsonk** [comment]
Duplicate of #11498
