### ISSUE TITLE
TypeScript definition file support in VS?

### ISSUE THREAD

**Issue by MgSam** [Microsoft/TypeScript#20819]
This [blog post](https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/) from nearly a year and a half ago says better support for adding definition files from within Visual Studio is "coming soon". 

Are there any current plans to add a better way to get definition files into Visual Studio? I don't want to use NPM from the command line- that's the entire reason I'm using an IDE in the first place.

What I'd like to see is a browser with previews, version numbers, and autocomplete. 

(I know about Mads' "Package Installer" tool- it provides two deprecated ways of getting definition files and is sorely out of date)

Thanks.

**Comment by DanielRosenwasser** [comment]
The "coming soon" refers mainly to being able to resolve to `@types`-scoped packages, which is the primary way we expect users to consume declaration file packages, and Visual Studio does have that.

Currently we have a quick-fix for acquiring `.d.ts` files when `noImplicitAny` is on, but I don't know if that entirely meets your needs.

Out of curiosity, how do you currently get packages for regular JS dependencies? In other words, how do you go about getting the `.js` files you need?

**Comment by MgSam** [comment]
@DanielRosenwasser 
I get the JS files from Bower (though that is now deprecated too... sigh...). And relying on import statements for a quick fix is also problematic because it puts the part before the horse. I want the typings present first precisely so I can get completion when trying to type import statements.

And what about when `noImplicitAny` is off (which is the default)? The default behavior should be great, not confusing and error-prone.

A quick fix is not nearly as useful as actual UI to help find typings.
