### ISSUE TITLE
Definite assignment for exhaustive switch statements.

### ISSUE THREAD

**Issue by antialize** [Microsoft/TypeScript#20823]
Consider the following code

```ts
function test4(value: 1 | 2) {
    let x: string;
    switch (value) {
    case 1: x = "one"; break;
    case 2: x = "two"; break;
    }
    return x; //There is no path through the switch so x is alwayes assigned here.
}
```
**Expected behavior:**
The code should type check under --strict

**Actual behavior:**
Definite assignment does not realize that the switch is exhaustive and that all paths assign to x, so we get an error.

Checked with 2143a3f439aea887b2078e21e7585e4fa712f5fa

**Comment by DanielRosenwasser** [comment]
The problem is that definite assignment doesn't take types into account, it just works on the control flow graph. Adding a `default: throw new Error("...");` should do the trick though.

**Comment by andy-ms** [comment]
Internally we use (simplified) `default: throw assertNever(x);` with
```ts
function assertNever(member: never): never {
    throw new Error("Illegal value: " + member);
}
```

**Comment by antialize** [comment]
I use that as well. Note however that

```ts
function test4(value: 1 | 2) {
    let x: string;
    switch (value) {
    case 1: x = "one"; break;
    case 2: x = "two"; break;
    default: assertNever(value); break;
    }
    return x; //There is no path through the switch so x is alwayes assigned here.
}
```
Will not work due to #20822

**Comment by andy-ms** [comment]
Yeah, that's why you have to write `throw assertNever(value);` to indicate to control flow that it never returns.

**Comment by Kovensky** [comment]
not `return assertNever(value)`?

I do use a similar helper in my code, which I called `unreachable`.

**Comment by andy-ms** [comment]
The function's never going to finish evaluating either way, so it doesn't really matter whether you `return` or `throw` the result -- just a style preference.

**Comment by DanielRosenwasser** [comment]
Armchair perf speculation: `return` probably won't trigger a de-opt.

**Comment by methyl** [comment]
@andy-ms is this something you plan to tackle in the future?
