### ISSUE TITLE
Merged Interfaces with incompatible methods and properties should be an error

### ISSUE THREAD

**Issue by weswigham** [Microsoft/TypeScript#20826]
**TypeScript Version:**  2.7.0-dev.201xxxxx

**Code**

```ts
interface Foo {
    bold(): string;
}

interface Foo {
    bold: string;
}

var x: Foo;

const j = x.bold;
```

**Expected behavior:**
`j` is type `any`, TS issues an error on both declarations of `bold` because their type doesn't match.

**Actual behavior:**
No error, `j` is type `string`.

Please note, the `colors` DT package (and one other package) relies on our current buggy behavior here and will need to be fixed.

**Comment by DanielRosenwasser** [comment]
This is a regression that seems to have started in TypeScript 2.0. 1.8 is the last version that reported

```
error TS2300: Duplicate identifier 'bold'.
```

**Comment by weswigham** [comment]
The `bisect` result says this was an (unintended?) side-effect of https://github.com/Microsoft/TypeScript/pull/8696. cc @RyanCavanaugh wasn't the restriction only supposed to be relaxed if the declarations had the same types?

**Comment by RyanCavanaugh** [comment]
Correct, the intended behavior is that this would be an error due to the types not being identical
