### ISSUE TITLE
Class members that are non-optional or are not unioned with undefined don't require initialisation.

### ISSUE THREAD

**Issue by kujon** [Microsoft/TypeScript#20829]
**TypeScript Version:**  2.6.2 strict mode

Apologies if this is a duplicate, I wasn't able to find a relevant issue.

**Code**

```ts
class Foo {
    test: number;
}

const foo = new Foo();

foo.test; //> undefined
```

**Expected behavior:**
I'd expect the code above to blow up, because I've not assigned a value to the `test` member. The compiler could require me to do either of the following to address the issue (similarly to how e.g. Java behaves):

1. Initialise in place:
```ts
class Foo {
    test: number = 42;
}
```

2. Initialise in the constructor:
```ts
class Foo {
    test: number;
    constructor() {
        this.test = 42;
    }
}
```

**Actual behavior:**
The above code compiles.

**Comment by j-oliveras** [comment]
That will be one of the features of the next version. The pull request #20075 implement this. [Roadmap with 2.7 features](https://github.com/Microsoft/TypeScript/wiki/Roadmap#27-january-2018).

You can try this feature with `npm install -g typescript@next` ([more info about trying future versions](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Nightly%20Builds.md)).
