### ISSUE TITLE
Intellisense doesn't show information generated at runtime

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#20824]
_From @rosyatrandom on December 20, 2017 15:42_

- VSCode Version: 1.19
- OS Version: Ubuntu

```
const correct = n => n*2
let incorrect = [1, 2]
incorrect = s => s*2

correct
incorrect
```

On hover, code hints are:

- correct: `const correct: (n: any) => number`
- incorrect: `let incorrect: number[]`

The issue that's led me to report this is that I wish to construct objects at runtime, and have Intellisense show their contents correctly. As a trivial example:

```
const doSomethingCurried = a => b => {/* something with a, b */};
const doSomethingWith = Object.assign(
  {},
  ...['a', 'b', 'c'].map(
    v => ({ [v]: doSomethingCurried(v) })
  )
)
```

This should end up equivalent to:
```
const doSomethingWith = {
  a: doSomethingCurried('a'),
  b: doSomethingCurried('b'),
  c: doSomethingCurried('c')
}
```
So that, when typing `doSomething.`, the hint should show properties `a`, `b`, and `c`.

I can see how tricky this might be to look into :-/

_Copied from original issue: Microsoft/vscode#40585_

**Comment by mjbvz** [comment]
I believe your first example is expected. Using `//@ts-check` in the file for example will flag re-assinging a variable to a new type as an error

The `Object.assign` issue seems like it has a different cause

**Comment by andy-ms** [comment]
The editor doesn't actually run the program, it just analyzes it.
However, you can accomplish what you want by using a mapped type.
```
type T<K extends string> = Record<K, { greet(name: string): string; }>;
function makeObject<K extends string>(keys: ReadonlyArray<K>): T<K> {
    const out: T<K> = {} as any;
    for (const key of keys) {
        out[key] = { greet: (name) => `${key} greets ${name}` };
    }
    return out;
}

const obj = makeObject(["a", "b", "c"]);
console.log(obj.a.greet("Alice"));
```
