### ISSUE TITLE
JSDoc properties don't appear to be checked unless observed

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#20835]
`noImplicitAny` and `checkJs`, with this JS file:

```js
/**
 * @typedef Foo
 * @property bar
 */

/**
 * @param {Foo} inst
 */
function blah(inst) {
  return false;
}
```

This gives no error; however, as soon as you change the code to use `inst.bar` or `Foo['bar']`:

```js
/**
 * @typedef Foo
 * @property bar
 */

/**
 * @param {Foo} inst
 */
function blah(inst) {
  return inst.bar
}
```

then you'll get a `noImplicitAny` error messages. Is this working as intended?

**Comment by andy-ms** [comment]
Related to #20830
