### ISSUE TITLE
Accessing to object field does not prevent from Error - TS6133 error (declared but its value is never read)

### ISSUE THREAD

**Issue by ar41bald** [Microsoft/TypeScript#20841]
**TypeScript Version:**  2.6.2 and 2.7.0-dev.20171221

**Code**

```ts
let myComponent: MyComponent;
...
myComponent = TestBed.createComponent(MyComponent).componentInstance;
...
myComponent.detectChanges();
```

**Expected behavior:**
No errors
**Actual behavior:**
error TS6133: 'myComponent' is declared but its value is never read.

**Comment by andy-ms** [comment]
I can't reproduce that error with just that code, could you provide a complete example that fails on its own?

**Comment by ar41bald** [comment]
Thank you for the quick response.

It was my fault, sorry for disturbing.

During to reproducing this error by creating a short Plunk I found a bug in my code relates to this issue. So it was my mistake.

Thanks.
