### ISSUE TITLE
Currying pluck function causes compiler error

### ISSUE THREAD

**Issue by alsiola** [Microsoft/TypeScript#20848]
**TypeScript Version:**  2.7.0-dev.20171221

**Code**

```ts
const pluck = <T, K extends keyof T>(path: K, a: T): T[K] => a[path];

const curriedPluck = <T, K extends keyof T>(path: K) => (a: T): T[K] => a[path];

// Compiles, typed as number
const pluckResult = pluck("a", { a: 3 };

// Compiler error: Argument of type '"a"' is not assignable to parameter of type 'never'
const curriedPluckResult = pluck("a")({ a: 3 });
```

**Expected behavior:**
Both standard and curried function use will compile.

**Actual behavior:**
Curried version does not compile

**Comment by jwbay** [comment]
Looks like the parameters are used in the opposite order of their dependent relationship. When checking whether "a" is valid, it doesn't know what T is yet, so it doesn't know `keyof T` is either. If the parameters are flipped so the types are used 'in order' as far as dependent relationships, everything works.

```ts
const curriedPluck = <T, K extends keyof T>(a: T) => (path: K): T[K] => a[path];
const curriedPluckResult = curriedPluck({ a: 3 })("a"); // returns number
```

Just a guess, but some kind of lookahead *across function boundaries* would probably be necessary to be able to resolve the types 'backwards' here.

**Comment by alsiola** [comment]
I really wanted to keep the data-last argument order so it could be used in point-free chains, but I did get a working version in the end:

```ts
export const prop = <K extends string>(path: K) => <T>(a: { [k in K]: T }): T => a[path];
```

I guess it though that in the original non-compiling version, then `pluck("property")` would be typed to `(a: { property: T } ) => T`, and T would then be resolved when the returned function was called.  I assume that TS doesn't "carry-forward" unresolved generics across the function boundary, and if a generic argument needs to be declared, it must be on the function to which that argument is passed?

Anyway, thanks for your time and insight.

**Comment by DanielRosenwasser** [comment]
Try this

```ts
const curriedPluck = <K extends string>(path: K) => <T extends Record<K, any>>(a: T): T[K] => a[path];
```
