### ISSUE TITLE
TS2495: Type 'ArrayLike<T>' is not an array type or string type.

### ISSUE THREAD

**Issue by electricessence** [Microsoft/TypeScript#20852]
```ts
for(let x of <ArrayLike<T>>source) { }
```
Error: ```TS2495: Type 'ArrayLike<T>' is not an array type or string type.```

Why is this a thing?  A for loop using ```ArrayLike<T>``` as a source should work for any ES target.

TS 2.6.1

**Comment by Kovensky** [comment]
It definitely should _not_ work for any ES target. It may happen to work if you are using typescript with downlevel iteration disabled, but that is a deliberate spec violation in the name of compatibility with old, non-polyfilled browsers.

The right hand side of `for of` is not `ArrayLike`, it's `Iterable`.

**Comment by electricessence** [comment]
Isn't "ArrayLike" mean that it can be indexed, and that ```.length``` indicates the boundary of the indexes?
```for of``` should still be constructed normally and work normally without error.  Allow for some level of runtime failure.

**Comment by Kovensky** [comment]
yes, but `for of` does not care about `.length` or properties.

`for of` only cares about the `[Symbol.iterator]()` property, and that it returns an iterator. Actual `Array`s have a `[Symbol.iterator]()` that will return their elements in order; an arbitrary object that is `ArrayLike` potentially doesn't, such as the object I used in the TypeError screenshot.

**Comment by electricessence** [comment]
Sorry still trying to wrap my head around why this is a thing.

Since the underlying JS code will work, just as it does with an array.  So instead of an efficient `for` loop being generated under the hood, I now have to call `Array.from()`?

Maybe it's just my opinion, but this seems overly strict.  And I normally prefer strict. :|

**Comment by electricessence** [comment]
```ts
for(let x of <ArrayLike<T>>source) { }
```
Can you provide a type alternative to ArrayLike<T> that will work?  Given that source is potentially exactly that.  An integer indexed (readonly) object?

**Comment by DanielRosenwasser** [comment]
Looks like a duplicate of #2862.

**Comment by electricessence** [comment]
Seems dupe-enough, but I still feel left uneasy because `ArrayLike<T>` should be enough to treat it like an array. :/  So now I need to use what type instead?  `Iterable<T>`?  Which is still not correct if what I really want is a simple `for(var _i=0;...` underneath. :/
