### ISSUE TITLE
tsc generates invalid .d.ts file when the code has destructuring assignment

### ISSUE THREAD

**Issue by michael8090** [Microsoft/TypeScript#20855]
**TypeScript Version:**  2.6.2

**Code**

```ts
// a.ts
const a = {
    value: 1
};

// const value = a.value;
const { value } = a;
```

**Expected behavior:**

After compiled with `tsc a.ts -d`, it should get the following `.d.ts` content:
```ts
declare const value: number;
export { value };
```

**Actual behavior:**
It generates the following content:
```ts
export { value };
```
But if we use the commented line, instead of using destructing assignment, the behavior is correct.

**Comment by michael8090** [comment]
![image](https://user-images.githubusercontent.com/2306105/34285183-98afcd20-e712-11e7-9389-7139acdd2187.png)

**Comment by mhegazy** [comment]
should be fixed in `typescript@next`.
