### ISSUE TITLE
Update docs with regards to installing additional SDK version onto Visual Studio 2017

### ISSUE THREAD

**Issue by cveld** [Microsoft/TypeScript#20857]
We were having troubles getting SDK 2.2 working with Visual Studio 2017. Refer to StackOverflow post https://stackoverflow.com/questions/47928191/how-to-install-typescript-2-2-onto-visual-studio-2017

It would be great to see the docs updated with regards on on how to install an additional SDK version onto Visual Studio 2017. The best and only way to do this is apparently to use the installer and select the specific SDK as an additional component to be installed.

Apparently the separate downloads outside the installer floating around do not work correctly as Visual Studio then still takes the lib.es2015.d.ts file from the latest installed SDK instead of the selected one in the csproj or worse don't work at all.

Impacted pages:

* https://www.typescriptlang.org/#download-links
* https://github.com/Microsoft/TypeScript/wiki/Updating-TypeScript-in-Visual-Studio-2017
* https://www.microsoft.com/en-us/download/details.aspx?id=55258
* https://marketplace.visualstudio.com/items?itemName=TypeScriptTeam.TypeScript22forVisualStudio2015

Maybe others.

**Comment by DanielRosenwasser** [comment]
I'm not entirely certain what action item you're looking for regarding the pages, but this:

> Apparently the separate downloads outside the installer floating around do not work correctly as Visual Studio then **still takes the lib.es2015.d.ts file from the latest installed SDK instead of the selected one** in the csproj or worse don't work at all.

seems like a bug.

**Comment by minestarks** [comment]
We've fixed a multitude of bugs regarding how the TypeScript version / SDK is selected since this bug was opened and I can't repro the specific issue here. Please feel free to open a new issue if you're still seeing it.
