### ISSUE TITLE
Variable used as receiver of destructuring rest falsely marked as 'used before being assigned'

### ISSUE THREAD

**Issue by ajafff** [Microsoft/TypeScript#20860]
**TypeScript Version:**  2.7.0-dev.20171222, 2.6.2, playground

**Code**

```ts
// @strictNullChecks: true
let bar: {};
({ ...bar } = {});
```

**Expected behavior:**
No error: `bar` is the receiver. Since the AST is the same for rest and spread, there is probably just a condition missing.

**Actual behavior:**
Variable 'bar' is used before being assigned.

**Comment by mhegazy** [comment]
thanks @Kingwl
