### ISSUE TITLE
Add function length into type system

### ISSUE THREAD

**Issue by EliSnow** [Microsoft/TypeScript#20866]
Currently the type system does not account for the length property in function types. In unions, where the length of the functions vary, it could be used as a discriminated union.

Here is an example that would work under this proposal:
```ts
type fn1 = (a: string, b: number) => void;
type fn2 = (a: number) => void;

function a (fn: fn1 | fn2) {
    if (fn.length == 1) {
       fn(7);
    } else {
        fn("foo", 8);
    }
}
```

Of course the type system would have to follow the same rules for determining a function's length as specified in the ECMAScript standard and described in [this MDN description](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/length#Description).

Without this functionality I am not aware of a way, besides using a very specific user-defined type guard, for the type system to distinguish between the function types.

**Comment by jwbay** [comment]
Related: #18422
