### ISSUE TITLE
Union type treated as an intersection when assigned to a parameter.

### ISSUE THREAD

**Issue by Celleb** [Microsoft/TypeScript#20864]
#

**TypeScript Version:**  2.6.0

**Code**

```ts
export type Constructor = { new(...args: any[]): {} };

export interface BaseProvider {
    provide: Constructor | string;
}

export interface ClassProvider extends BaseProvider {
    useClass: Constructor;
}

export interface FactoryProvider extends BaseProvider {
    useFactory: Function;
}

export interface ValueProvider extends BaseProvider {
    useValue: any;
}

export type Provider = ClassProvider | ValueProvider | FactoryProvider;

export class Injector {
    registerSingleton(provider: Provider){
       // error here
        console.log(provider.useClass);
   }
}
```

**Expected behavior:**
I should be able to access the `useClass` property of provider without getting a Typescript error hint.
See comment in the code.

**Actual behavior:**
Gives a Typescript error hint: `useClass` does not exist on type `ValueProvider`.
See comment in the code.

**Comment by DanielRosenwasser** [comment]
The union type `ClassProvider | ValueProvider | FactoryProvider` implies a `Provider` describes values that could be any of `ClassProvider` or `ValueProvider` or `FactoryProvider`, so you're not guaranteed to have a property named `useClass` available at runtime.

**Comment by Celleb** [comment]
Noted, so I should basically use type assertion to avoid the issue.
