### ISSUE TITLE
High CPU usage from Node.exe: Javascript process in Visual studio

### ISSUE THREAD

**Issue by IronSean** [Microsoft/TypeScript#20865]
Note: This may be the wrong place for this, please let me know if so.

Expected Behavior
There is no Node.js or TypeScript in my app, so I would expect Node to not even be running. Or if it is running, to be using very few resources.

Actual Behavior
The Node.exe thread arbitrarily switches from low cpu usage to 80-100% usage of a Single Core for 10-15 seconds, spinning up laptop fans and using power.
`"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Web\External\x86\node.exe" --expose-gc "C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.3\tsserver.js" --cancellationPipeName \\.\pipe\tsserver-cancellation-12800 --useSingleInferredProject --locale en-US --typingSafeListLocation "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\TypeScript\typingSafeList.json" --allowLocalPluginLoads --eventPort 64462`

NTVS Version: 1.4.10918.1
Visual Studio Version: 15.4.4
Node.js Version: 8.9.7

Steps to Reproduce
Open Visual Studio
Run any .Net Application, debug it, stop debugging it, the node exe will be running in all cases.

The node.exe, based on what I've read online, seems to be running the Typscript language features
as disabling TypeScript support within Visual Studio will eliminate the CPU usage. I suspect it might be related to the Intellisense for Javascript and TypeScript, and especially hampered by the NuGet behaviour of importing both minified and full versions of JQuery and other libraries which that service then needs to fully parse and keep in memory to fuel Intellisense.

**Comment by DanielRosenwasser** [comment]
If you have any JavaScript running in your app, then TypeScript is providing the editing experience for your `.js` files. If you'd be willing to share your code, we'd be willing to sign an NDA.
