### ISSUE TITLE
API: noEmitOnErrors causes errors to be written twice

### ISSUE THREAD

**Issue by ivogabe** [Microsoft/TypeScript#20876]
When using the compiler API, errors are written twice when `noEmitOnError` is set. The emit diagnostics (`program.emit().diagnostics`) duplicates the pre emit errors. `tsc` fixes this by using `sortAndDeduplicateDiagnostics`, but this function is not publicly exposed so API consumers cannot use that.

Could this be exposed or could the emit diagnostics be implemented in such way that they do not duplicate the pre emit diagnostics? I'd prefer the latter.

In the example code below (from the TypeScript wiki), `ts.getPreEmitDiagnostics(program)` and `emitResult.diagnostics` both contain the same error.

See also ivogabe/gulp-typescript#543.

**TypeScript Version:**  2.7.0-dev.2017122

**Code**

`compiler.ts` (from https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API)
```ts
import * as ts from "typescript";

function compile(fileNames: string[], options: ts.CompilerOptions): void {
    let program = ts.createProgram(fileNames, options);
    let emitResult = program.emit();

    let allDiagnostics = ts.getPreEmitDiagnostics(program).concat(emitResult.diagnostics);

    allDiagnostics.forEach(diagnostic => {
        if (diagnostic.file) {
            let { line, character } = diagnostic.file.getLineAndCharacterOfPosition(diagnostic.start!);
            let message = ts.flattenDiagnosticMessageText(diagnostic.messageText, '\n');
            console.log(`${diagnostic.file.fileName} (${line + 1},${character + 1}): ${message}`);
        }
        else {
            console.log(`${ts.flattenDiagnosticMessageText(diagnostic.messageText, '\n')}`);
        }
    });

    let exitCode = emitResult.emitSkipped ? 1 : 0;
    console.log(`Process exiting with code '${exitCode}'.`);
    process.exit(exitCode);
}

compile(process.argv.slice(2), {
    noEmitOnError: true, noImplicitAny: true,
    target: ts.ScriptTarget.ES5, module: ts.ModuleKind.CommonJS
});
```

`foo.ts`
```ts
const foo: string = 1;
```

First compile `compiler.ts` with `tsc compiler.ts` and then run it with `node compiler foo.ts`.

**Expected behavior:**
```
foo.ts (1,7): Type '1' is not assignable to type 'string'.
```

**Actual behavior:**
```
foo.ts (1,7): Type '1' is not assignable to type 'string'.
foo.ts (1,7): Type '1' is not assignable to type 'string'.
```

**Comment by subramn** [comment]
I see the same behavior as well. . example mentioned below. i missed to add status in the object initialization.

Type '{ id: number; name: string; description: string; }[]' is not assignable to type 'Project[]'.
  Type '{ id: number; name: string; description: string; }' is not assignable to type 'Project'.
    Property 'status' is missing in type '{ id: number; name: string; description: string; }'.

**Comment by ivogabe** [comment]
@subramn That doesn't look related to this issue. The first and second line are not the same, notice the missing brackets `[]` on the second line. TypeScript is elaborating on the error there, first saying that some array is not assignable to some other array, which is caused by the fact that the element type of the first array is not assignable to the second, which is caused by the missing property.

**Comment by sheetalkamat** [comment]
```ts.getPreEmitDiagnostics``` is suppose to return you all the diagnostics before writing files and hence it returns global, options, syntactic, semantic and declaration diagnostics.

```program.emit``` is suppose to return diagnostics generated while emitting the files. So in case when ```noEmitOnError``` is ```false``` and ```declaration``` is ```true``` it would still include declaration diagnostics.
So even though we need to fix the errors reported in ```EmitResult```  with ```noEmitOnError```, you would still need to use ```sortAndDeduplicateDiagnostics``` to ensure that declaration diagnostics are deduplicated as well.
