### ISSUE TITLE
New Website Logo: LotusJS

### ISSUE THREAD

**Issue by doriansmiley** [Microsoft/TypeScript#20871]
Please fill the following out:

- Name: LotusJS
- Homepage url: https://www.lotusjs.org/
- Brand Guidelines/Licensing: don't crop, change colors, skew, or otherwise distort
- Logo: https://www.lotusjs.org/css/assets/LotusLogoForExport.svg

> Example:
>
> Name: Microsoft
> Homepage url: https://microsoft.com
> Brand Guidelines/Licensing: https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks/usage/logo.aspx
> Logo: https://news.microsoft.com/microsoft-news-center-photos/msft_logo_rgb_c-gray/

**Comment by mhegazy** [comment]
Should be available the next time the site is published
