### ISSUE TITLE
isTypeOfExpression is broken

### ISSUE THREAD

**Issue by tehwalris** [Microsoft/TypeScript#20875]
**TypeScript Version:**  2.6.2 
**Code**
```ts
import * as ts from 'typescript'

const testTypeOf = ts.createTypeOf(ts.createLiteral(""))
const testAwait = ts.createAwait(ts.createLiteral(""))

console.log(testTypeOf.kind, testAwait.kind) // 189, 191

console.log(ts.isTypeOfExpression(testTypeOf)) // Prints false, should be true
console.log(ts.isTypeOfExpression(testAwait)) // Prints true, should be false
```

**Expected behavior:**
`ts.isTypeofExpression` should return `true` (only) for `TypeOfExpression` nodes.

**Actual behavior:**
It returns `true` for `AwaitExpression` nodes instead.

**Reason**
The nodes both get created correctly (`TypeOfExpression` has kind `189` like it should), but the generated code for `isTypeOfExpression` uses the wrong number for `kind`: (from [`tsc.ts`](https://github.com/Microsoft/TypeScript/blob/release-2.6/lib/tsc.js), starting on line 9132)
```ts
    function isTypeOfExpression(node) {
        return node.kind === 191;
    }
    ts.isTypeOfExpression = isTypeOfExpression;
    function isVoidExpression(node) {
        return node.kind === 190;
    }
    ts.isVoidExpression = isVoidExpression;
    function isAwaitExpression(node) {
        return node.kind === 191;
    }
    ts.isAwaitExpression = isAwaitExpression;
```
Note that some code uses the correct `kind`:
```ts
    function createTypeOf(expression) {
        var node = createSynthesizedNode(189);
        node.expression = ts.parenthesizePrefixOperand(expression);
        return node;
    }
```
Note that this issue also exists on [master](https://github.com/Microsoft/TypeScript/tree/8118cc76295d5f3a1bb65bd97807d649ee0a5bc9), even though the numbers for `SyntaxKind` enum values have changed.

I couldn't find where this code gets generated, so I haven't been able to investigate further.

**Comment by magcius** [comment]
Bug appears to be here: https://github.com/Microsoft/TypeScript/blob/81fbe12c541d47ead85c7ae77c7eb3880b5eff68/src/compiler/utilities.ts#L4634-L4636

**Comment by DanielRosenwasser** [comment]
Since you've pinpointed the problem, we'd be open to a PR. 😃
