### ISSUE TITLE
New Website Logo: Silicon Publishing

### ISSUE THREAD

**Issue by doriansmiley** [Microsoft/TypeScript#20870]
Please fill the following out:

- Name: Silicon Publishing
- Homepage url: https://www.siliconpublishing.com/
- Brand Guidelines/Licensing: Do not crop, change colors, skew or otherwise distort
- Logo: https://www.lotusjs.org/css/assets/SPI_Logo.svg

**Comment by mhegazy** [comment]
Should be available the next time the site is published
