### ISSUE TITLE
strictNullChecks doesn't work with empty destructuring assignment

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#20873]
**TypeScript Version:**  2.7.0-dev.20171223

**Code**

```ts
const [] = null;
```

**Expected behavior:**

error

**Actual behavior:**

pass

**Comment by DanielRosenwasser** [comment]
We should reuse the `Object is possibly ____` messages and check for the RHS of any destructuring assignment. The following cases should error:

```ts
let { } = null;
({} = null);

let { } = undefined;
({} = undefined);

let { } = Math.random() ? {} : null;
({} = Math.random() ? {} : null);

let { } = Math.random() ? {} : undefined;
({} = Math.random() ? {} : undefined);

let { } = Math.random() ? null : undefined;
({} = Math.random() ? null : undefined);
```

**Comment by jack-williams** [comment]
Is anyone working on this? I'd be interested in having a go, but I don't want to impose if anyone is working on it already.
