### ISSUE TITLE
unexpect error throw when use the spread syntax on iterableObj

### ISSUE THREAD

**Issue by YuyangGong** [Microsoft/TypeScript#20885]
**TypeScript Version:**  2.7.0-dev

**Code**

```ts
[...document.querySelectorAll('div')]
```

**Expected behavior:**
should correct get the array of div nodes in page
**Actual behavior:**
throw error: 
Uncaught TypeError: document.querySelectorAll(...).slice is not a function
    at <anonymous>:1:34

**possible reason that cause this bug**
Typescript will transform the es6 code`[...document.querySelectorAll('div')]`  to es5 code as `document.querySelectorAll('div').slice()`, this cause the bug.
I use babel too, it will transfome `[...document.querySelectorAll('div')]`, to below
```javascript
function _toConsumableArray(arr) { if (Array.isArray(arr)) { for (var i = 0, arr2 = Array(arr.length); i < arr.length; i++) { arr2[i] = arr[i]; } return arr2; } else { return Array.from(arr); } }

[].concat(_toConsumableArray(document.querySelectorAll('div')));
```
Babel will not throw error, but TS will.

MORE　ABOUT the ... spread syntax: [spread syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator)

**Comment by DanielRosenwasser** [comment]
You'll need to use the `--downlevelIteration` flag.
