### ISSUE TITLE
[ts] Type '0' cannot be used to index type 'T'.

### ISSUE THREAD

**Issue by vhb56** [Microsoft/TypeScript#20881]
Everything seems to work, but i get this error on `propToQuery` param:
`[ts] Type '0' cannot be used to index type 'T'.`
But type checking works as i want it to work when i call this method(i can pass only string which is equal to keys of that array element).

```ts
 checkResponse<T>(response: { [p: string]: string }[] | T, propToQuery: keyof T[0],  error = ID_ERRORS.BACKEND)
  {
    if (response[0][propToQuery] === "ERROR") throw new Error(error);
    else return response as T;
  }
```

**Expected behavior:**
No error?

**Actual behavior:**
Visual Studio Code says there is an error.

**Comment by michaeljota** [comment]
How is the shape of T? Or how you would expect the shape of T? Cause, the shape I can infer as human is:
```typescript
interface IResponse extends Array<{ [key: string]: string }> {}
```
If that is, then you should mark your response as such.

```typescript
interface IResponse extends Array<{ [key: string]: string }> {

}

function checkResponse<T extends IResponse>(
    response: T,
    propToQuery: keyof T[0],
    error = ID_ERRORS.BACKEND
) {
    if (response[0][propToQuery] === "ERROR") throw new Error(error);
    else return response as T;
}
```

**Comment by DanielRosenwasser** [comment]
Yeah, `T` needs to be constrained to a type with a property named `0`, or have a numeric or string index signature.

**Comment by vhb56** [comment]
Thanks, now i understand, yep `T` is always an array of objects, but objects are also always different, 
if i don't want to create an interface, essentially in this specific case i can go even with this:
```
function checkResponse<T extends any[]>(
    response: T, 
    propToQuery: keyof T[0],  
    error = ID_ERRORS.BACKEND
) {
    if (response[0][propToQuery] === "ERROR") throw new Error(error);
    else return response as T;
}
```
