### ISSUE TITLE
Error in DestructuringVariableDeclaration production

### ISSUE THREAD

**Issue by danquirk** [Microsoft/TypeScript#2088]
5.1.2 Destructuring Variable Declarations describes the top level production for destructuring as

DestructuringVariableDeclaration:
BindingPattern   TypeAnnotationopt   Initialiser

But Initialiser is optional in certain cases like parameter binding patterns.

**Comment by ahejlsberg** [comment]
The DestructuringVariableDeclaration production is only for variables. Parameters are covered in section 3.8.2.2 and in that grammar the initializer is optional.
