### ISSUE TITLE
export default interface creates error it .d.ts file

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/TypeScript#20880]
**TypeScript Version:**  2.6.2
**TypeScript Next Version:**  2.7.0-dev.20171223

When defining an interface for a `default class` without the `default` keyword give an error. By adding the `default` keyword to the interface the error goes away. However when the declarations get created, there is an error in the `.d.ts` file.

**Code**

```ts
export default interface DataSet<I extends ModelItems> {
  [key: string]: any
}

export default class DataSet<I extends ModelItems> { }
```
This `.d.ts` file is generated:
```ts
export default interface;
export default class DataSet<I extends ModelItems> {
  // Snipped: properties and methods
}
```
This is the `.js` that is generated:
```js
exports.default = interface;
DataSet < I;
ModelItems > {
    [key]: string, any
};
class DataSet {
}
```
Which then produces this error:
> All declarations of '(Missing)' must have identical type parameters.

**Expected behavior:**

No error should be created in the `.d.ts` file

**Actual behavior:**

An error is generated in the `.d.ts` file

**Comment by weswigham** [comment]
Is there more to this issue (such as some specific compiler settings or more context)? This doesn't seem to repro on `master` or in 2.6.2 as described here
```ts
//// [exportDefaultInterfaceMerged.ts]
export default interface DataSet<I> {
    [key: string]: any
}

export default class DataSet<I> { }

//// [exportDefaultInterfaceMerged.js]
"use strict";
exports.__esModule = true;
var DataSet = /** @class */ (function () {
    function DataSet() {
    }
    return DataSet;
}());
exports["default"] = DataSet;


//// [exportDefaultInterfaceMerged.d.ts]
export default interface DataSet<I> {
    [key: string]: any;
}
export default class DataSet<I> {
}
```

**Comment by TheColorRed** [comment]
@weswigham these are the settings that I have set:

```json
{
  "compilerOptions": {
    "target": "es2015",
    "module": "commonjs",
    "removeComments": true,
    "strict": true,
    "outDir": "lib",
    "declaration": true,
    "declarationDir": "typings",
    "noUnusedLocals": true,
    "noUnusedParameters": true
  },
  "include": [
    "src/**/*.ts"
  ]
}
```

**Comment by TheColorRed** [comment]
When I make a smaller project it now doesn't do it... Maybe I am seeing a different issue...

**Comment by weswigham** [comment]
@TheColorRed Are you using any build tools besides `tsc` in your project? Are there more merged declarations in the offending file than what you initially listed here?

**Comment by TheColorRed** [comment]
I have since deleted the file, because I no longer need it, but this is what it contained:

https://github.com/TheColorRed/query-builder/blob/89c3d6132930abe6d75933a45d95410b86c74319/src/DataSet.ts

**Comment by weswigham** [comment]
Hm. I can't repro it with your project either.

**Comment by TheColorRed** [comment]
I did have an older version installed, but I am not sure if I updated it before or after this issue. I guess this can be closed for now...
