### ISSUE TITLE
New-Language-Service-in-Visual-Studio-15 breaks syntax highliting

### ISSUE THREAD

**Issue by yringler** [Microsoft/TypeScript#20895]
**Expected behavior:**
Syntax highlighting in visual studio 2017 should work.
If I disable the new JavaScript language service, it should stay disabled.
**Actual behavior:**
It doesn't.

I recall reading that this is becuause now visual studio scans all javascript files before showing syntax highlighting, and if we have npm plugins, there's millions of lines of javascript to scan.
The solution is to uncheck "Enable the new JavaScript language service" in settings, Text Editor -> Javscript/TypeScript -> Language Service.
Fine. The annoying thing is that it keeps on becoming enabled.

Technically, this isn't a typescript issue, but vs 2017 says to leave feedback at https://github.com/Microsoft/TypeScript/wiki/Using-the-New-Language-Service-in-Visual-Studio-15-Preview, and that url points here.

**Comment by DanielRosenwasser** [comment]
CC @bowdenk7 @billti 

Could you elaborate on specifically what "doesn't work" here? It sounds like there is potentially a bug (you disable the new JS LS, you commit your new settings, but then somehow that isn't getting respected), but it's not clear what issue you're running into with syntax highlighting.

> and if we have npm plugins, there's millions of lines of javascript to scan.

For the record, this can be configured using a `jsconfig.json` or `tsconfig.json` file.
