### ISSUE TITLE
interface union type casting creates invalid state

### ISSUE THREAD

**Issue by codemau5** [Microsoft/TypeScript#20896]
**TypeScript Version:**  2.6.2

**Code**
```ts
interface A1 {
    typeA: "A1";
    typeB: "B1";
}
interface A2 {
    typeA: "A2";
    typeB: "B2";
}
type AU = A1 | A2;

function foo(obj1: AU, obj2: AU): AU {
    const obj3: AU = <AU>{
        typeA: obj1.typeA,
        typeB: obj2.typeB
    };
    return obj3;
}

const a1: A1 = {
    "typeA": "A1",
    "typeB": "B1"
}
const a2: A2 = {
    "typeA": "A2",
    "typeB": "B2"
}

const a3: AU = foo(a1, a2);

console.log(a3.typeA, a3.typeB);
// A1 B2
```
a3 is of type AU, but is in an invalid state!!

**Expected behavior:**
if you would try to create such an object, you would normally get this error:
```ts
const au: AU = {
    typeA: "A1",
    typeB: "B2"
};
/*
Type '{ typeA: "A1"; typeB: "B2"; }' is not assignable to type 'AU'.
  Type '{ typeA: "A1"; typeB: "B2"; }' is not assignable to type 'A2'.
    Types of property 'typeA' are incompatible.
      Type '"A1"' is not assignable to type '"A2"'.
*/
```
**Actual behavior:**
unstable state!

**Comment by sylvanaar** [comment]
The problem is that you are using type `AU` as the parameters to `foo` where you do the assignment, so it is impossible to know if the assignment is truly valid.

Change `foo` to:

```
function foo(obj1: A1, obj2: A2): AU {
    const obj3: AU = <AU>{
        typeA: obj1.typeA,
        typeB: obj2.typeB
    };
    return obj3;
}
```

Basically, any claim that this is an issue boils down to one question:

Given:

`type Foo = "foo" | "bar"`

Is 1 variable of type Foo assignable to another of type Foo. I think the answer needs to be yes, so your sample behaves correctly.

**Comment by DanielRosenwasser** [comment]
> a3 is of type AU, but is in an invalid state!!

But you used a type assertion!


```ts
    //               this thing
    //               vvvv
    const obj3: AU = <AU>{
        typeA: obj1.typeA,
        typeB: obj2.typeB
    };
    return obj3;
```

You're basically telling the compiler "I know what I'm doing". While we try to have the type system do some basic checks before you can convince it, there's not a ton we can do here.

**Comment by DanielRosenwasser** [comment]
I realize you are basing this issue on a fix I suggested yesterday, but if you read up on the context that I gave, you'll see how this construct doesn't generalize past the case where on;y a single-property differs. My advice was to step around the type system for when you know better in that case.
