### ISSUE TITLE
Compiler flag for strict class comparison

### ISSUE THREAD

**Issue by tra1lblazer** [Microsoft/TypeScript#20897]
Consider the following code:
```
class First {
	public name: string;
	public age: number;
}

class Second {
	public name: string;
	public age: number;
}

let first: First = new Second(); //Works
```

So you can assign object of one type to the object of other type as long as their fields are identical. Similar code in e.g. C# would produce a compile-time error. Would be nice to have a flag that would allow similar behavior in Typescript.

**Comment by j-oliveras** [comment]
[Typescript use structural typing.](https://github.com/Microsoft/TypeScript/wiki/FAQ#what-is-structural-typing) Add some private property and will be an error.

**Comment by michaeljota** [comment]
> If it walks like a duck and it quacks like a duck, then it must be a duck.

TypeScript just check that the shape of the objects are the same, with the same name and the same types. If so, they are the same.

**Comment by RyanCavanaugh** [comment]
Duplicate #202
