### ISSUE TITLE
Suggestion: Generic Parameter Overloads

### ISSUE THREAD

**Issue by omidkrad** [Microsoft/TypeScript#209]
> Suggestion moved over from [codeplex](https://typescript.codeplex.com/workitem/2438/).

The suggestion is to allow generic parameter overloads like the following:

``` typescript
declare module Backbone {
    class Model{}
    class Events{}
    class ViewOptions<TModel extends Model> {}
    class Collection<TModel extends Model> {}

    // Generic parameter overload
    class View extends View<Backbone.Model>;
    class View<TModel extends Model> extends Events { // Don't take as duplicate identifier
        constructor(options?: ViewOptions<TModel>);
        model: TModel;
        collection: Collection<TModel>;
    }
}

// With Generics Parameter overloads, old non-generic consumer
// code works as before and does not need to change.
class MyView extends Backbone.View {
}
var myView = new MyView();
var model = myView.model; // model is of type Backbone.Model

// Can gradually introduce generic parameters to Views
class DerivedModel extends Backbone.Model { 
}
var myView2 = new Backbone.View<DerivedModel>();
var model2 = myView2.model; // model2 is of type DerivedModel
```

This is important because this would allow people to introduce generics in their library declarations without breaking large amounts of existing code for the consumers. We do this a lot in C#, and it is compatible with TypeScript design because it won't make any changes in the resulting javascript, and works pretty much like method overloads in TypeScript.

Related discussion: https://typescript.codeplex.com/discussions/452741

**Comment by RonPenton** [comment]
Any movement on this one? I've run into the situation where I want to do this:

```
    export interface Func<R> { (): R; }
    export interface Func<P, R> { (parameter: P): R; }
    export interface Func<P1, P2, R> { (parameter1: P1, parameter2: P2): R; }
    export interface Func<P1, P2, P3, R> { (parameter1: P1, parameter2: P2, parameter3: P3): R; }
    export interface Func<P1, P2, P3, P4, R> { (parameter1: P1, parameter2: P2, parameter3: P3, parameter4: P4): R; }

```

But Instead I have to define them like this:

```
    export interface Func0<R> { (): R; }
    export interface Func1<P, R> { (parameter: P): R; }
    export interface Func2<P1, P2, R> { (parameter1: P1, parameter2: P2): R; }
    export interface Func3<P1, P2, P3, R> { (parameter1: P1, parameter2: P2, parameter3: P3): R; }
    export interface Func4<P1, P2, P3, P4, R> { (parameter1: P1, parameter2: P2, parameter3: P3, parameter4: P4): R; }
```

It's not the end of the world, but it is pretty annoying.

**Comment by weswigham** [comment]
@RonPenton We added generic defaults in #13487 for TS 2.3, so yes - we implemented the equivalent alternative to this.

**Comment by lukas-zech-software** [comment]
@weswigham I don't see how defaults are solving the problem with @RonPenton's example

I tried this

```typescript
export interface Func<R=void> {  (): R; }
export interface Func<R=void, P1=void> {  (param1: P1): R; }
export interface Func<R=void, P1=void, P2=void> {  (param1: P1, param2: P2): R; }

const fn1: Func                          = () => {};
const fn2: Func<string>                  = () => '';
const fn3: Func<string, number>          = (param1: number) => '';
const fn4: Func<string, number, boolean> = (param1: number, param2: boolean) => '';

```

but the compiler complains at 
`fn3` with `TS2322:Type '(param1: number) => string' is not assignable to type 'Func<string, number, void>'.` 

and at

`fn4` with `TS2322:Type '(param1: number, param2: boolean) => string' is not assignable to type 'Func<string, number, boolean>'.` 


it seem like the compiler does not differ between the second and the third overload of `Func`

or am I doing something wrong here?

**Comment by lukas-zech-software** [comment]
the weird thing is, when I put all overloads in a single interface the compiler accepts `fn3` but still complains about  `fn4`

```typescript
export interface Func<R=void, P1=void, P2=void> {
  (param1: P1): R;
  (param1: P1, param2: P2): R;
}

const fn1: Func = () => {};
const fn2: Func<string>                  = () => '';
const fn3: Func<string, number>          = (param1: number) => '';
const fn4: Func<string, number, boolean> = (param1: number, param2: boolean) => ''; // error

```

**Comment by weswigham** [comment]
You should only need to have [one interface declaration](http://www.typescriptlang.org/play/#src=export%20interface%20Func%3CR%3Dvoid%2C%20P1%3Dnever%2C%20P2%3Dnever%3E%20%7B%20%20(param1%3A%20P1%2C%20param2%3A%20P2)%3A%20R%3B%20%7D%0D%0A%0D%0Aconst%20fn1%3A%20Func%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3D%20()%20%3D%3E%20%7B%7D%3B%0D%0Aconst%20fn2%3A%20Func%3Cstring%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3D%20()%20%3D%3E%20''%3B%0D%0Aconst%20fn3%3A%20Func%3Cstring%2C%20number%3E%20%20%20%20%20%20%20%20%20%20%3D%20(param1)%20%3D%3E%20''%3B%0D%0Aconst%20fn4%3A%20Func%3Cstring%2C%20number%2C%20boolean%3E%20%3D%20(param1%2C%20param2)%20%3D%3E%20''%3B):
```ts
export interface Func<R=void, P1=never, P2=never> {  (param1: P1, param2: P2): R; }

const fn1: Func                          = () => {};
const fn2: Func<string>                  = () => '';
const fn3: Func<string, number>          = (param1) => '';
const fn4: Func<string, number, boolean> = (param1, param2) => '';
```
The rest are just adding more call signatures, which will get resolved using overload resolution. If you add them; you need to make sure the "most specific" ones are added first, otherwise what you described can happen.

**Comment by lukas-zech-software** [comment]
There are some drawbacks with that solution:
All function now must provide 2 parameters.
```typescript
export interface Func<R=void, P1=never, P2=never> {  (param1: P1, param2: P2): R; }

const fn1: Func                          = () => {};
fn1(); // TS2554:Expected 2 arguments, but got 0.
```

If I make all parameters optional, then there is no type safety in calling the methods with all expected parameters ....


```typescript
export interface Func<R=void, P1=void, P2=void> {  (param1?: P1, param2?: P2): R; }

const fn1: Func                          = () => {};
const fn2: Func<string>                  = () => '';
const fn3: Func<string, number>          = (param1) => '';
const fn4: Func<string, number, boolean> = (param1, param2) => '';

fn1(); // fine
fn2(); // fine
fn3(); // should raise error but does not
fn4(); // should raise error but does not
```

**Comment by RonPenton** [comment]
@weswigham I don't believe that solves the issue. I tried to use default generic parameters like @lukas-zech-software did and ran into the same problems. The compiler expects parameters that don't exist.

Try out your code, you'll see that it doesn't work:

```
export interface Func<R=void, P1=never, P2=never> {  (param1: P1, param2: P2): R; }

const fn1: Func                          = () => {};
const fn2: Func<string>                  = () => '';
const fn3: Func<string, number>          = (param1) => '';
const fn4: Func<string, number, boolean> = (param1, param2) => '';

fn1();                  // Expected 2 arguments, but got 0.
const x = fn2();        // Expected 2 arguments, but got 0.
const y = fn3(123);     // Expected 2 arguments, but got 1.
const z = fn4(1, true); // This is the only one that works. 

```

**Comment by liminf** [comment]
I don't think default values work for the case I am interested in, either.  I'm trying to get generic parameter binding working.  Creators of a bindable would define the parameters that it accepts, and consumers would bind values for parameters through a "bind" call.  Once all parameters are bound then the bind method is no longer available and the call method becomes available.

This looks something like this

```
interface IBindable<RequiredParams if-non-empty-object> {
    bind : <ParamSet>(p : ParamSet) => IBindable<RequiredParams less params in ParamSet>;
}
interface IBindable<RequiredParams if-empty-object> {
    call: () => Result;
}
```
In some ways this is very much like the [classic C++ factorial template metaprogramming example](https://en.wikipedia.org/wiki/Template_metaprogramming)
