### ISSUE TITLE
lib.dom.d.ts missing Attribute list interface

### ISSUE THREAD

**Issue by prettydiff** [Microsoft/TypeScript#20903]
A DOM element has a property `attributes` that returns a node list of attributes on the given element.  Example:

```javascript
let attrs = document.getElementById('beautify').attributes;
attrs[0].name; // returns a string of this attribute name
attrs[0].value // returns a string of this attribute's value
attrs.length // returns a number indicating the number of attributes in the list
``` 

According to FireFox this node list is of type *NamedNodeMap*, which does exist in lib.dom.d.ts and does appear to describe attributes, but that interface is not familiar to me.  Essentially, the attributes node list contains a *length* property and objects of name/value pairs.  This can be quickly verified in a browser's console.

Since I could not find the appropriate definition in the DOM library I wrote my own:

```typescript
interface Attribute {
    name: string;
    value: string;
}
interface Attributes {
    [index: number]: Attribute;
    length: number;
}
```

**Comment by SalathielGenese** [comment]
Do comments have `attributes`? Let's see the inheritance chain :

A. [Element](http://devdocs.io/dom/element)
```ts
EventTarget <- Node <- Element
```
Now, `Element`s have `attributes` but [Comments](http://devdocs.io/dom/comment) follow a little different path :

```ts
EventTarget <- Node <- CharacterData <- Comment
```

As [this page](http://devdocs.io/dom/node) illustrates, not even `Node` has the `attributes` properties. So as far as you are working with `Node[]` or [`NodeList`](http://devdocs.io/dom/nodelist), of which `Comment` are part of (among others), you wont get `attributes` property as you expected.

**Comment by prettydiff** [comment]
When I apply *NamedNodeMap* at the type for an attribute list I can no longer reproduce the issue I was having in my code.  I am going to close this issue and reexamine what I was running into.

**Comment by SalathielGenese** [comment]
`NamedNodeMap` is the type of `element.attributes` : its elements (items) are each `Attr`. Why changing its type to its container's type? OK, let us know if you reproduce it.
