### ISSUE TITLE
Implement interface using subclass as method parameter

### ISSUE THREAD

**Issue by nieltg** [Microsoft/TypeScript#20904]
A class shouldn't be allowed to implement an interface using subclass as method parameter.

**TypeScript Version:**  2.7.0-dev.20171226

**Code**

```ts
class Animal {
  name: string
}

class Dog extends Animal {
  sayWoof () {
    console.log('woof')
  }
}

interface Shelter {
  put (animal: Animal): void  // put() accepts Animal.
}

class DogShelter implements Shelter {
  put (dog: Dog): void {      // Why is this possible?
    dog.sayWoof()
  }
}

function putToShelter (shelter: Shelter, animal: Animal) {
  shelter.put(animal)
}

let d = new DogShelter()

putToShelter(d, new Dog())
putToShelter(d, new Animal())
```

**Expected behavior:**
An error should be occurred because **Dog** is not compatible with **Animal**.  
**Dog** has **sayWoof** method. **Animal** doesn't have **sayWoof** method.

**Actual behavior:**
No compile-time error is occurred from this snippet, but runtime error is occurred.

```
$ node_modules/.bin/tsc a.ts
$ node a.js
woof
/mnt/c/Users/nieltg/Desktop/test/a.js:30
        dog.sayWoof();
            ^

TypeError: dog.sayWoof is not a function
```

**Comment by DanielRosenwasser** [comment]
https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-function-parameters-bivariant

For the record, this is not entirely true anymore with `--strictFunctionTypes`, but our decision was to continue comparing method parameters bivariantly because doing otherwise would have imposed too many breaks on existing code, and made it overly restrictive to model common patterns in JS as they exist today.

**Comment by nieltg** [comment]
@DanielRosenwasser 
Oh, sorry. I missed that one. Thank you for mentioning it.

**Comment by nieltg** [comment]
Hi @DanielRosenwasser,
Sorry for reopening this issue, but I've tried using `--strictFunctionTypes` but still, no compile-time error is occurred on my snippet.

I've also found that `--strictFunctionTypes` works on this case. (I append this code below on my snippet)

```
function varianceTest(dog: Dog) {
  dog.sayWoof()
}

let animal: (dog: Animal) => void = varianceTest
```

A compile-time error occurs for this case, but not for my previous case.

```
$ tsc a.ts --strict
a.ts(38,5): error TS2322: Type '(dog: Dog) => void' is not assignable to type '(dog: Animal) => void'.
  Types of parameters 'dog' and 'dog' are incompatible.
    Type 'Animal' is not assignable to type 'Dog'.
      Property 'sayWoof' is missing in type 'Animal'.
```

**Comment by gcnew** [comment]
You have to use a "function declaration" to get strict checking. Methods are compared bivariantly on purpose.

```ts
interface Shelter {
  // put (animal: Animal): void  // method
  put: (animal: Animal) => void  // function
}
```

**Comment by nieltg** [comment]
Oh, now I see.
Thank you, @gcnew, for your explanation.
