### ISSUE TITLE
Type definitions in node_modules leak and pollute other packages

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#20905]
@\types/node referenced by @\types/mocha doesn't affect the root project but it pollute other packages.

**TypeScript Version:**  2.7.0-dev.201xxxxx

**Code**

1. Clone https://github.com/falsandtru/pjax-api
1. Run `npm i`
1. Run `npm i @types/mocha@2.2.45`
1. Run `node_modules/.bin/tsc --noEmit -p tsconfig.json`

**Expected behavior:**

pass

**Actual behavior:**

```
node_modules/spica/throttle.ts(7,5): error TS2322: Type 'Timer' is not assignable to type 'number'.
node_modules/spica/throttle.ts(28,5): error TS2322: Type 'Timer' is not assignable to type 'number'.
```

**Comment by SalathielGenese** [comment]
In the [`tscnfig.json`](http://devdocs.io/typescript/handbook/tsconfig-json), exclude the `node_modules` directory :
```json
{
  "compilerOptions": {
    "module": "system",
    "noImplicitAny": true,
    "removeComments": true,
    "preserveConstEnums": true,
    "outFile": "../../built/local/tsc.js",
    "sourceMap": true
  },
  "include": [
    "src/**/*"
  ],
  "exclude": [
    "node_modules",
    "**/*.spec.ts"
  ]
}
```
