### ISSUE TITLE
keyof discrimination does not narrow down the type assertion

### ISSUE THREAD

**Issue by michaeljota** [Microsoft/TypeScript#20907]
**TypeScript Version:**  typescript@2.7.0-dev.20171226

**Code**

```ts
interface IExample {
  name: string;
  age: number;
}

const data: IExample[] = []
const sort = { direction: 'asc', active: 'name' };

data.sort((a, b) => {
  const { direction } = sort;
  const active = sort.active as keyof IExample;

  let order = 0;
  if (typeof a[active] === "string") {
    order = a[active].localeCompare(b[active]);
  } else if (typeof a[active] === "number") {
    order = a[active] < b[active] ? -1 : 1;
  }

  return direction === "asc" ? order : order * -1;
});
```
**Expected behavior:**
No errors. The `typeof a[active] === "string"` should narrow down the possible values of `active` to those that can receive a string value.

**Actual behavior:**
error TS2339: Property 'localeCompare' does not exist on type 'string | number'.
  Property 'localeCompare' does not exist on type 'number'.

**Comment by SalathielGenese** [comment]
It is not an issue because `const active` has the type `'name' | 'age'` and narrowing target `IExample['name'] | IExample['age']`.

You can fix your code by eitheir :

```ts
order = a[<"name">active].localeCompare(b[<"name">active]);
```

or :

```ts
    if ('name' === active)
    {
        order = a[active].localeCompare(b[active]);
    } else if ('age' === active)
    {
        order = a[active] < b[active] ? -1 : 1;
    }
```

**Comment by DanielRosenwasser** [comment]
We don't narrow on element access expressions. See #10530.

**Comment by michaeljota** [comment]
@SalathielGenese That code I set it up for example, but I can't know ahead the name of the property.

Anyway, I though it would be a duplicated, but it's hard to search an issue like this. Thanks you.

**Comment by michaeljota** [comment]
I will close this, but you should take another look at the PR implementation, because Typescript is becoming stricter all the time, and I think that's a good thing, but it needs to allow us to be stricter too.
