### ISSUE TITLE
Type guard does not affect variable inside a function

### ISSUE THREAD

**Issue by Mosho1** [Microsoft/TypeScript#20901]
**TypeScript Version:**  2.7.0-dev.201xxxxx

**Code**

```ts
function foo(o: number | number[]) {
    if (!Array.isArray(o)) {
        o = [o];
    }
    o.length;
    () => o.length;
}
```

**Expected behavior:**
No compile errors.

**Actual behavior:**
>   Property 'length' does not exist on type 'number'.

in `() => o.length`

**Comment by sylvanaar** [comment]
Note that it occurs with this code too:

```
function foo(o: number | number[]) {
	if (!Array.isArray(o)) {
		o = [o];
	} else {
		o.length;
		() => o.length; // error: Property 'length' does not exist on type 'number'.
	}
}
```

**Comment by SalathielGenese** [comment]
I think the TypeScript compiler is using the same scope rules for lambdas and functions. This' the only logical reason I see for this. I think that have to do with `Function Statement` and `Function  Expression` scope.

A function statement should behave that way because hoisting will make it available in foo top level, not like function expression (and lamdas are always).

**Comment by Mosho1** [comment]
@SalathielGenese it's a distilled demonstration of the issue, not my use-case. Your solution does not solve the problem because you are assuming the function needs to be called immediately. It may be passed to another function like `Array.prototype.map`. 

Yes, this should be the case for function statements, but not for function expressions and arrow functions.

**Comment by SalathielGenese** [comment]
@Mosho1, I attempted to :

1. Explain the reason of the issue,
2. Provide a workaround

Another workaround could be :
```ts
(o: number[]) => o.length
```

Still another :
```ts
() => (<number[]>o).length
```

All are work around to get the job done while the issue is being fixed.

**Comment by ahejlsberg** [comment]
This is working as intended. Type guards remain in effect across function boundaries only when the guarded variable(s) are considered constant. This is the case for `const` local variables and parameters that never occur as assignment targets in the function. See #10357.

**Comment by Mosho1** [comment]
I see. That makes sense, thanks!
