### ISSUE TITLE
Code action to remove unused declaration removes license comment

### ISSUE THREAD

**Issue by rictic** [microsoft/TypeScript#20902]
**TypeScript Version:**  2.7.0-dev.20171226

**Code**

```ts
/**
 * @license
 * Suppose this was the text of a copyright license.
 */

import {basename} from 'path';
```

Running with noUnusuedLocals gives a warning about `basename`. Typescript also provides a Code Action to remove the declaration for `basename`.

**Expected behavior:**

Applying the code action to remove the declaration only removes the import statement, it does not remove the license comment.

**Actual behavior:**

The import statement and the license comment are removed.

**Comment by rictic** [comment]
Two potential solutions:

* An empty line between the comment and the statement could be taken as an indication that the comment isn't attached to the statement, and so removing the statement would not remove the comment.

* A comment that contains the text `@license` could be taken as an indication that the comment should not be automatically deleted.

**Comment by rictic** [comment]
Related: https://github.com/Microsoft/TypeScript/issues/13411

**Comment by mhegazy** [comment]
PRs welcomed.

**Comment by weswigham** [comment]
> A comment that contains the text @license could be taken as an indication that the comment should not be automatically deleted.

We already generally consider a comment that starts the file and begins with `/*!` as "pinned" and should not be moved or deleted. We usually advise using this for licenses.

**Comment by RyanCavanaugh** [comment]
This works now
