### ISSUE TITLE
type narrowing bug

### ISSUE THREAD

**Issue by alt22247** [Microsoft/TypeScript#20913]
TypeScript Version: 2.6
```

class Test
{
    private property: string;

    private changeProperty(): void
    {
        this.property = "bar";
    }

    private TestFunc(): void
    {
        if (this.property != "foo")
            throw "bad";

        this.changeProperty();
        if (this.property == "bar") //compile error
            console.log("good");
    }
}

```
**Expected behavior:**
Compile should work

**Actual behavior:**
Compile error because Typescript believes this.property should be "foo" and comparing "foo" == "bar" is dumb. It didn't take in the fact that property got changed by the method call.

**Comment by jwbay** [comment]
Related: https://github.com/Microsoft/TypeScript/issues/9998
