### ISSUE TITLE
 Should there be a mistake here?

### ISSUE THREAD

**Issue by wabby** [Microsoft/TypeScript#20917]
#The source typescript code below here:

```
interface A{
    x?: number;
    y?: number;
}
function add(a:number, b:number){return a+b;}
const a:A={x:1};
const result = add(a.x,  a.y);
```
<br>

The above code can be compiled normally, When I execute the following code in the browser， the result is **NaN**，And the compile result is：

```
function add(a, b) { return a + b; }
var a = { x: 1 };
var result = add(a.x, a.y);
```
<br>
In  my opinion: **a.y** should be typeof **undefined**，Which 
is not match the second parameter type **b:number**， And  typescript compiler should prompt me wrong. **Does anyone know if I have any knowledge I do not mastered**？

**Comment by kitsonk** [comment]
Working as intended.

When compiled with `--strictNullChecks` you get the following error:

```
Argument of type 'number | undefined' is not assignable to parameter of type 'number'.
  Type 'undefined' is not assignable to type 'number'.
```

**Comment by wabby** [comment]
@kitsonk Get it！  Thanks very mach
