### ISSUE TITLE
ES6 Conversion error，

### ISSUE THREAD

**Issue by lwpersonal** [Microsoft/TypeScript#20916]
this is my code

`[...Array(10).keys()]`

The result is on the official website

`Array(10).keys().slice();`

But it is wrong

`Uncaught TypeError: Array(...).keys(...).slice is not a function
    at <anonymous>:1:18`

**Comment by RyanCavanaugh** [comment]
TypeScript doesn't polyfill methods - if you are running on a runtime without `Array#keys`, you need to provide the polyfill yourself

**Comment by j127** [comment]
Which runtime can run that ES5 output from Typescript? In Node v8.6.0, Firefox, and Chrome:

* `Array(10).keys()` works
* `[...Array(10).keys()]` works

but the transpiled ES5 output from the 2nd one there (`Array(10).keys().slice()`) causes `TypeError: Array(...).keys(...).slice is not a function` in Firefox, Chrome, and Node 8, even though the original ES6 does work.

**Comment by RyanCavanaugh** [comment]
@j127 that code is flagged as an error when targeting ES5
![image](https://user-images.githubusercontent.com/6685088/35816526-c96eca8c-0a4f-11e8-932a-11a887fbe0f8.png)

If you run with `--target ES5 --lib es6 --downlevelIteration`, which is the only way to have that code *not* issue a type error, then we emit a proper spread helper:
```
var __read = (this && this.__read) || function (o, n) {
    var m = typeof Symbol === "function" && o[Symbol.iterator];
    if (!m) return o;
    var i = m.call(o), r, ar = [], e;
    try {
        while ((n === void 0 || n-- > 0) && !(r = i.next()).done) ar.push(r.value);
    }
    catch (error) { e = { error: error }; }
    finally {
        try {
            if (r && !r.done && (m = i["return"])) m.call(i);
        }
        finally { if (e) throw e.error; }
    }
    return ar;
};
var __spread = (this && this.__spread) || function () {
    for (var ar = [], i = 0; i < arguments.length; i++) ar = ar.concat(__read(arguments[i]));
    return ar;
};
var p = __spread(Array(10).keys());
```

**Comment by j127** [comment]
Thanks. Isn't that still a bug though? (or at least undesired behavior) I have it set to output ES5 in my tsconfig file, and it's compiling working JavaScript to non-working JavaScript.

**Comment by RyanCavanaugh** [comment]
> Isn't that still a bug though?

If `target` is `es5` then we can't just emit the spread as-is, because spreads are not legal ES6. What do you propose we do differently?

**Comment by j127** [comment]
Sorry if I'm confused here. I'm not understanding why it would transpile code to `Array(10).keys().slice()`. Is there any ES5 interpreter that can run that code?

The output doesn't seem to match the target. If you're writing ES6/Typescript and transpiling to ES5, it seems like the transpired version should work in ES5 browsers. Node 9.5, Chrome 64, and Firefox 59 can't run that "ES5" snippet.

**Comment by RyanCavanaugh** [comment]
Under the constraints given, TS *can't* emit correct code, so it issues an error and tries to do the best it can.

What would you expect to be emitted instead?

**Comment by j127** [comment]
> What would you expect to be emitted instead?

I expect to write ES6 code and have it transpiled to code that runs in the most common ES5 interpreters. :) 

Right now, I'm writing valid ES6 and Typescript doesn't transpile it to working ES5. The exact output doesn't matter -- just that it runs.

I don't know the best way to do it, but this is one way that works:

```javascript
// ES6
[...Array(10).keys()]
// => [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 ]

// working ES5
Array.apply(null, Array(10)).map(function (_, idx) {return idx;});
// => [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 ]
```

**Comment by RyanCavanaugh** [comment]
> I expect to write ES6 code and have it transpiled to code that runs in the most common ES5 interpreters. :)

I think your expectation has to be "TypeScript emits code that runs in the specified runtime, **or issues an error when it can't**". TypeScript issued an error in this case; you can't expect code to work if TS has told you (in one way or another) that it can't emit correct code.

Your proposed emit **only** works for the exact special case of spreading `Array.keys`; there are many other iterator-returning functions that can't be turned into a `map` call.

**Comment by j127** [comment]
Thanks, I see the error now when running it from the command line. I missed it when compiling from VS Code. I only saw the broken output file, assuming that it was supposed to work. Sorry for my confusion.
