### ISSUE TITLE
Autoformat eats up characters with multiline strings

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#2091]
for [playground link](http://www.typescriptlang.org/Playground/#src=new%20Error(%60Failed%20to%20expand%20glob%3A%20%24%7BprojectSpec.filesGlob%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20at%20projectPath%20%3A%20%24%7BprojectFile%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20with%20error%3A%20%24%7Bex.message%7D%60))
```ts
new Error(`Failed to expand glob: ${projectSpec.filesGlob}
                at projectPath : ${projectFile}
                with error: ${ex.message}`)
```
Autoformat will make it:
```ts
new Error(`Failed to expand glob: ${projectSpec.filesGlob}
                projectFile}
                ex.message}`)
```
ouch. :heart:

**Comment by vladima** [comment]
Seems to be a known issue that was fixed in a6d374ee21359c9001f4de161929df1d90058060.
In the current master everything works as expected. Will add regression test for this scenario to capture current behavior

**Comment by vladima** [comment]
![formattingmultilinestringliterals](https://cloud.githubusercontent.com/assets/8052307/6282363/a0e4de06-b888-11e4-9d7b-4e688decaf7e.gif)

**Comment by vladima** [comment]
Feel free to reopen\create new issue if you can reproduce wrong behavior on the latest bits

**Comment by basarat** [comment]
:fist: :heart:
