### ISSUE TITLE
error TS5055: Cannot write file 'three.ts' because it would overwrite input file.

### ISSUE THREAD

**Issue by asweetonion** [Microsoft/TypeScript#20915]
I set the allowJs option to true and set the outDir option,but it doesn't work.
my tsconfig.json:
```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "allowJs": true,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ],
  }
}
```

**Comment by SalathielGenese** [comment]
Which TypeScript Compiler? What editor, what tools? Was the the file opened by another editor? Which one(s)?
--need-more-info

**Comment by asweetonion** [comment]
I use Webstorm to write my program, and my js file has been opened by nodepad ++

**Comment by mhegazy** [comment]
that means one of your files import or references a file in the output. use `--listFiles` to see what files the compiler is using as inputs.
