### ISSUE TITLE
Direct use await whitout async function

### ISSUE THREAD

**Issue by Hume83** [Microsoft/TypeScript#20923]
Hi, what possibilities exist to be able to use the await operator without the use of async?,
as it is currently done in javascript.

Example in actual javascript

const prom = new Promise((r)=> {r('Running whitout without async 🏄   
')});
await prom // Running whitout without async 🏄

Regards!

**Comment by ajafff** [comment]
> as it is currently done in javascript.

@Hume83 do you mean what the node repl or chrome console does? There is some special treatment for top level await.
In regular JavaScript and TypeScript this is not valid. You can try it yourself by saving the code snippet to a file and execute that file with node.

**Comment by Hume83** [comment]
You are right, excuse my ignorance, I have tried it fast in the console, it would be a really great feature, to avoid the unnecessary use of async function in some cases. Could this feature be available in the future of ECMAScript?
Thanks for your answer mate.
