### ISSUE TITLE
No string completions for indexed access types

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#20938]
```ts
interface Foo {
    hello: number;
    world: string;
}

let x: Foo['']
```

Try to request completions within the string literal.

**Expected**: completions for `hello` and `world`
**Actual**: no completions

**Comment by DanielRosenwasser** [comment]
@mariusschulz, you said you might be interested in working on this?

**Comment by Kingwl** [comment]
i'd like to working on this😂

**Comment by DanielRosenwasser** [comment]
Sorry, @mariusschulz DM'd me on Twitter. You've been doing an awesome job with the PRs though @Kingwl!
