### ISSUE TITLE
Element.prototype.attributes hasn't a iterator.

### ISSUE THREAD

**Issue by zaclummys** [Microsoft/TypeScript#20937]
**TypeScript Version:**  2.7.0-dev.20171229

**Code**
```ts
for (const attr of element.attributes) {
    console.log(attr);
}
```

**Expected behavior:**
It's expected Typescript run this code normally without errors/warnings.

**Actual behavior:**
Typescript says: "_Type must have a '[Symbol.iterator]()' method that returns an iterator._"

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by a-tarasyuk** [comment]
@zaclummys 

Based on spec

> Element.attributes - returns a NamedNodeMap object containing the assigned attributes of the corresponding HTML element.

`attributes` returns [`NamedNodeMap` ](https://dom.spec.whatwg.org/#namednodemap), this interface looks like this:

```WebIDL
interface NamedNodeMap {
  readonly attribute unsigned long length;
  getter Attr? item(unsigned long index);
  getter Attr? getNamedItem(DOMString qualifiedName);
  Attr? getNamedItemNS(DOMString? namespace, DOMString localName);
  [CEReactions] Attr? setNamedItem(Attr attr);
  [CEReactions] Attr? setNamedItemNS(Attr attr);
  [CEReactions] Attr removeNamedItem(DOMString qualifiedName);
  [CEReactions] Attr removeNamedItemNS(DOMString? namespace, DOMString localName);
};
```
`NamedNodeMap` does not containt property `iterable;` like [`DOMTokenList`](https://dom.spec.whatwg.org/#interface-domtokenlist). For this reason this example

```typescript
for (const attr of element.attributes) {
    console.log(attr);
}
```

causes error. 

@mhegazy Do we need to add `iterable` property to `attributes`? I think we need to follow the spec, and leave `NamedNodeMap` definition as it is defined in the spec.

**Comment by mhegazy** [comment]
There is nothing in the spec that indicates that this should be iterable.. but chrome and firefox seem to expose a `[Symbol.Iterator]` property on them, but not Edge. so not sure what is the right course of action here. we can file a spec bug against whatwg and see if being iterable is the intended behavior or not.

**Comment by a-tarasyuk** [comment]
@mhegazy Ok, Thanks, I'll try to contact someone from `whatwg` to discuss this issue.

**Comment by a-tarasyuk** [comment]
@mhegazy I've investigated this issue and seems that `TSJS-lib-generator` generates the right interface for `.attributes`.

`NamedNodeMap` has `.length` and `getter`, and based on the spec [_3.6.9. Common iterator behavior_](https://heycam.github.io/webidl/#es-iterators) - item `#2` - _an indexed property getter and an integer-typed length attribute_, interface should contain `[Symbol.Iterator]`. In [`dom.es6.generated#NamedNodeMap` ](https://github.com/Microsoft/TSJS-lib-generator/blob/master/baselines/dom.es6.generated.d.ts#L85) that interface exists, so `TSJS-lib-generator` correctly handles such properties. However, I could not found `NamedNodeMap` in `TypeScript/lib/*`. Maybe we need to add the latest changes from `TSJS-lib-generator` to `TypeScript`.
Seems that the interfate `NamedNodeMap` should be defined in [`lib.dom.iterable.d.ts`](https://github.com/Microsoft/TypeScript/blob/master/lib/lib.dom.iterable.d.ts) _(not sure)_, however, this file was updated ~6 months ago.

**Comment by a-tarasyuk** [comment]
@mhegazy Where should be defined 

```typescript
interface NamedNodeMap {
    [Symbol.iterator](): IterableIterator<Attr>
}
```

?

**Comment by mhegazy** [comment]
it is currently defined in https://github.com/Microsoft/TSJS-lib-generator/blob/master/baselines/dom.es6.generated.d.ts

The change needed is to use this file to replace https://github.com/Microsoft/TypeScript/blob/master/src/lib/dom.iterable.d.ts

So what is needed if you want to help out, 
- rename https://github.com/Microsoft/TSJS-lib-generator/blob/master/baselines/dom.es6.generated.d.ts to dom.iterable.d.ts
- add to  https://github.com/Microsoft/TSJS-lib-generator/blob/master/baselines/dom.es6.generated.d.ts missing declarations, e.g. `NodeList.entries`, `NodeList.values`, etc..
- add to  https://github.com/Microsoft/TSJS-lib-generator/blob/master/baselines/dom.es6.generated.d.ts the missing comments from https://github.com/Microsoft/TypeScript/blob/master/src/lib/dom.iterable.d.ts

**Comment by a-tarasyuk** [comment]
@mhegazy Yes, I want. 

> add to https://github.com/Microsoft/TSJS-lib-generator/blob/master/baselines/dom.es6.generated.d.ts missing declarations, e.g. NodeList.entries, NodeList.values, etc..

Directly to baseline or to [`addedTypes.json`](https://github.com/Microsoft/TSJS-lib-generator/blob/master/inputfiles/addedTypes.json)/[`overridingTypes.json`](https://github.com/Microsoft/TSJS-lib-generator/blob/master/inputfiles/overridingTypes.json) ?
