### ISSUE TITLE
Delegation as a safe alternative to mixins

### ISSUE THREAD

**Issue by dleppik** [Microsoft/TypeScript#20947]
# Problem

JavaScript libraries make heavy use of mixins, but TypeScript has no built-in type-safe way to combine objects. Furthermore, mixins are inherently dangerous because they expose internal details of the mixed object and make API changes dangerous.

# Proposed solution

Using the [delegation pattern](https://en.wikipedia.org/wiki/Delegation_pattern), a class may specify that methods are implemented by calling the same method on a specified property. Specifically the compiler produces proxy methods _for functions found in the declared type of the delegated property._

This does not result in literal mixins—**the delegated object is not modified**—but it provides equivalent functionality in many cases while adding a typesafe syntax. This also means that the changes in JavaScript are better contained: the delegating object (a.k.a. wrapper) is used where the wrapper's functionality is needed, whereas contexts which don't need them can be provided the wrapped (delegated) object.

The proposed syntax is similar to [Kotlin's](http://kotlinlang.org/docs/reference/delegation.html) `by` syntax.

```typescript
interface A {
    giveMeAString: () => string
}

class AImplementation implements A {
    giveMeAString() {
        return "String!";
    }

    giveMeSomethingNotInA() {
        return "The interface doesn't specify this!";
    }
}

class Wrapper implements A by a {
     constructor(private a: A) {}
     
     // Generated method
     // giveMeAString(): string {
     //     return this.a.giveMeAString();
     // }
}

const delegated = new AImplementation();
const delegating = new Wrapper(delegated);

expect(delegating.giveMeAString()).toEqual("String!");
expect(delegating.giveMeSomethingNotInA).toBeUndefined();
```

Classes, rather than interfaces, can be delegated as well using the `delegates` keyword. In this case, the compiler emits wrappers for all the delegated property's public methods that are known at compile time.

```typescript
class WrapperForAImplementation delegates AImplementation by a {
    constructor(private a: AImplementation) {}
    
     // Generated method
     // giveMeAString(): string {
     //     return this.a.giveMeAString();
     // }

     // Generated method
     // giveMeSomethingNotInA(): string {
     //     return this.a.giveMeSomethingNotInA();
     // }
} 

const delegating = new WrapperForAImplementation(new AImplementation());

expect(delegating.giveMeSomethingNotInA()).toEqual("The interface doesn't specify this!");
```

## Details

- Only a delegated property's _functions_ are delegated.
- This is delegation, not forwarding: `this` inside the delegated property refers to the delegated property.
- The wrapping class's methods *known at compile time* take priority; thus a delegating `toString()` function is not emitted.
- A class may delegate to many properties, so long as they do not conflict.

## Use case: extensions

Many JavaScript libraries, including jQuery, encourage extensions by modifying an object directly at runtime. Delegation is a safer way to do this, since updates to the wrapped class do not conflict with extensions.

### Dangers of mixins for extensions

Here is an example of the danger of mixins which is solved by delegation. In this case, delegation is also safer than inheritance. Consider version 1.0 of SomeThirdPartyAPI:

```typescript
export class SomeThirdPartyAPI {
    formatAsISO(date: Date): string {
        // ...
    }
}
```

The user discovers that dates are often provided as strings, so she writes her own convenience extension.

```typescript
// With delegation:
class MyExtendedAPI delegates SomeThirdPartyAPI by someThirdPartyAPI {
    constructor(private someThirdPartyAPI: SomeThirdPartyAPI) {}
    
    formatStringAsISO(dateString: string) {
        return this.formatAsISO(new Date(dateString));
    }
    
    // Implicit code generated by the compiler.
    //
    //formatAsISO(date: Date): string {
    //    return this.someThirdPartyAPI.formatAsISO(date);
    //}
}

// With mixins
interface MyExtension {
    formatStringAsISO(dateString: string): string
}

function extend(someThirdPartyApi: SomeThirdPartyAPI): SomeThirdPartyAPI & MyExtension {
    const result = <any> someThirdPartyApi;
    result.formatStringAsISO = (dateString: string) => someThirdPartyApi.formatAsISO(new Date(dateString));
    return result;
}
```

Problems happen when API developer also decides to implement the same method, but redefines the original method. Calling the mixin implementation now triggers an infinite loop. The delegation implementation does not have this problem, since the extension class's implementation is not referenced by the delegated object's `this`.

```typescript
// Version 1.0.1. No need to bump the major version number since we're only adding functionality, or is there?
export class SomeThirdPartyAPI {
    formatAsISO(date: Date | string): string {
        return (typeof date === 'string') ? this.formatStringAsISO(date) : this.formatDateAsISO(date);
    }
    
    formatStringAsISO(date: string): string {
        // ...
    }
    
    formatDateAsISO(date: Date): string {
        // ...
    }
}
```

## Use case: all-in-one API objects

Similar to extensions, delegation can also be used to wrap a multifaceted API inside a single object. Delegation is a safer way to do this than mixins, since each internal component has a separate namespace.
 
## Related

This has superficial similarity to #19151, but whereas that delegation proposal provides special access to one class via another, this is strictly for providing controlled functionality similar to mixins.

**Comment by DanielRosenwasser** [comment]
Hi @dleppik, thanks for writing this up! As much as I'd love to be able to just inherit methods via composition, I think there are two problems with this idea:

1. This feature appears to depend on type-driven emit. Adding a delegation seems to require the compiler to emit some code that creates members on the delegator.
2. It's not clear whether ECMAScript will eventually add its own support for this construct, which would be problematic if it had its own implementation.

These run contrary to our [Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals/):

> # Goals
> (6): Align with current and future ECMAScript proposals.
> # Non-goals
> (5): Add or rely on run-time type information in programs, or emit different code based on the results of the type system. Instead, encourage programming patterns that do not require run-time metadata.

So to be totally transparent, I don't think this is something we'll be able to proceed with at this time, but feel free to correct me if I've missed something.

**Comment by ogwh** [comment]
I've implemented this as a library. I was going to horde it but give me half an hour or so and I'll stick it in an NPM package and open source it. It works with iterators too. So you can make a class iterable by delegating to an iterable property.
