### ISSUE TITLE
Could add feature like $Call<F> in Flow?

### ISSUE THREAD

**Issue by huhuanming** [Microsoft/TypeScript#20942]
https://flow.org/en/docs/types/utilities/#toc-call

From Flow's docs:

> $Call<F> is a type that that represents the result of calling the given function type F. This is analogous to calling a function at runtime (or more specifically, it’s analogous to calling Function.prototype.call), but at the type level; this means that function type calls happens statically, i.e. not at runtime.

```ts
const mapStateToProps = (state: IStoreState) => ({
  users: state.users,
})

type ExtractReturnType = <R>(() => R) => R;
type IStateType = $Call<ExtractReturnType, mapStateToProps>
```

This makes perfect sense.

**Comment by HerringtonDarkholme** [comment]
https://github.com/Microsoft/TypeScript/issues/6606
