### ISSUE TITLE
typeof with template literal does not narrow union

### ISSUE THREAD

**Issue by canac** [Microsoft/TypeScript#20949]
**TypeScript Version:**  2.7.0-dev.20171230

**Code**

```ts
interface ProcessEnv {
  [key: string]: string | undefined;
}

const env: ProcessEnv = { FOO: 'bar' };
const envVar: string | undefined = env.FOO;
if (typeof envVar === `string`) {
  // error TS2532: Object is possibly 'undefined'.
  console.log(envVar.slice(0));
}
if (typeof envVar === 'string') {
  console.log(envVar.slice(0));
}
```

**Expected behavior:**
Should compile fine.

**Actual behavior:**
`error TS2532: Object is possibly 'undefined'.` ``typeof envVar === `string` `` does not narrow the `string | undefined` union down to `string`.

**Comment by canac** [comment]
@RyanCavanaugh After reading [this article](https://ponyfoo.com/articles/template-literals-strictly-better-strings) a while back, I became persuaded of template literals' superiority over normal single/double quoted strings and have been using them exclusively ever since.

**Comment by mhegazy** [comment]
thanks @Kingwl !
