### ISSUE TITLE
AMD module: file without import statements is not wrapped in a define function

### ISSUE THREAD

**Issue by ficristo** [Microsoft/TypeScript#20943]
When a file doesn't contain an `import` statement is not wrapped in a `define` function.

**TypeScript Version:**  2.6.2
tsconfig:
```json
{
    "compilerOptions": {
        "outDir": "./dist",
        "module": "amd",
        "moduleResolution": "classic",
        "rootDir": ".",
        "sourceMap": true,
        "target": "es6"
    }
}
```

**Code**

```ts
const foo = "bar";
```

**Expected behavior:**
The file should be wrapped in a `define` function.
```js
define(["require", "exports"], function (require, exports) {
    const foo = "bar";
});
```

**Actual behavior:**
The file is not wrapped in a `define` function.
```js
const foo = "bar";
```

**Comment by DanielRosenwasser** [comment]
TypeScript differentiates global files from modules through the presence of imports/exports. To get around this, add an `export {}` to your file. Changing the behavior unfortunately is a breaking change, but on the other hand, this is handy for when you want to have a single global `.ts` file for configuring your AMD loader.

**Comment by ficristo** [comment]
I think this behaviour is a bit unexpected (at least it is for me). Is it documented anywhere?
In some of my code I use a custom way to require other files, so this "hurts" me (since I could end up without any `import` statement).
If it is only about configuring AMD, it could be done with a js file and set allowJS to true. But it is only a thought.
Thanks for the tip about `export`.

**Comment by DanielRosenwasser** [comment]
> If it is only about configuring AMD, it could be done with a js file and set allowJS to true. But it is only a thought.

It's not actually the reason why we do it, it's just combination of historical necessity of supporting global files, and a lack of markers to signal whether a JS file is global or a module. Currently, Node.js is having the same issue, resorting to a new `.js` file extension.

**Comment by ficristo** [comment]
Yeah, I imagined things weren't so simple...
Could this documented somewhere? If it is already, could you point it to me? Thank you.
