### ISSUE TITLE
IntelliSense for type's nested keys

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/TypeScript#20944]
This doesn't work in latest insiders VSCode:

![image](https://user-images.githubusercontent.com/736697/34454376-fd845836-ed8b-11e7-939c-81bd42236529.png)

Should propose `prop`.

Usually, this refers to TS, not VSCode.

**Comment by mhegazy** [comment]
Actually duplicate of https://github.com/Microsoft/TypeScript/issues/20938

**Comment by whitecolor** [comment]
Sometimes it is not easy to find out if the issue already exists =)
