### ISSUE TITLE
[Isolated Modules] Compiler error when const enum exists in imported module definition

### ISSUE THREAD

**Issue by berickson1** [Microsoft/TypeScript#20954]
With the isolated modules flag on, I should be able to import any arbitrary external module without errors about using const enums improperly.

**TypeScript Version:**  2.7.0-dev.20171230

**Code**

```ts
import tsutils = require('tsutils');

export class Test {
    noop() {
    }
}
```
See: https://github.com/berickson1/Playground/blob/master/isolatedModuleError.ts

**Expected behavior:**
Compiles without error

**Actual behavior:**
Errors as below:

npm run build

> playground@1.0.0 build /src/Playground
> tsc

node_modules/tsutils/src/utils.d.ts(22,27): error TS1209: Ambient const enums are not allowed when the '--isolatedModules' flag is provided.
node_modules/tsutils/src/utils.d.ts(30,27): error TS1209: Ambient const enums are not allowed when the '--isolatedModules' flag is provided.

**Comment by HerringtonDarkholme** [comment]
Related https://github.com/Microsoft/TypeScript/issues/20703
