### ISSUE TITLE
Incorrect 'never' type inference in TypeScript 2.6

### ISSUE THREAD

**Issue by sharwell** [Microsoft/TypeScript#20952]
**TypeScript Version:**  2.6.2

**Code**

https://github.com/sharwell/antlr4ts/blob/c9a8ef86fbdfc7f027916b5b281dac322495ca55/src/atn/LL1Analyzer.ts#L251

**Expected behavior:**

When the line is reached, `t` has the type `Transition`.

**Actual behavior:**

When the line is reached, `t` has the inferred type `never`. We are forced to work around the issue by explicitly casting and reassigning the variable.

**Comment by HerringtonDarkholme** [comment]
Please patiently await TS2.7.  https://github.com/Microsoft/TypeScript/pull/19671

It is probably because your concrete class have structurally identical type with your abstract class.

**Comment by the8thavatar** [comment]
I also see this problem from TypeScript v2.5.2 onwards where it was ok in 2.4.1..
var existingSymbol: SASymbol,...
        nodes = canvas.getNodes();
        for (i = 0; i < nodes.length; i++) {
            existingSymbol = nodes[i] as SASymbol;
            if ((existingSymbol.isSASymbol || existingSymbol instanceof PlaceableText
                || existingSymbol instanceof DiagramNode || existingSymbol instanceof ShapeNode || existingSymbol instanceof SvgNode
                )
                ...)
It reports existingSymbol to be type never from this point: existingSymbol instanceof ShapeNode
.. but I can delete the preceding cases and it becomes the expected SASymbol type again.
