### ISSUE TITLE
DOM FileReader load event needs to be more specific

### ISSUE THREAD

**Issue by prettydiff** [microsoft/TypeScript#20958]
Looking at lib.dom.d.ts the FileReader event is:

```typescript
interface FileReader extends EventTarget, MSBaseReader {
    readonly error: DOMError;
    readAsArrayBuffer(blob: Blob): void;
    readAsBinaryString(blob: Blob): void;
    readAsDataURL(blob: Blob): void;
    readAsText(blob: Blob, encoding?: string): void;
    addEventListener<K extends keyof MSBaseReaderEventMap>(type: K, listener: (this: FileReader, ev: MSBaseReaderEventMap[K]) => any, useCapture?: boolean): void;
    addEventListener(type: string, listener: EventListenerOrEventListenerObject, useCapture?: boolean): void;
    removeEventListener<K extends keyof MSBaseReaderEventMap>(type: K, listener: (this: FileReader, ev: MSBaseReaderEventMap[K]) => any, useCapture?: boolean): void;
    removeEventListener(type: string, listener: EventListenerOrEventListenerObject, useCapture?: boolean): void;
}

declare var FileReader: {
    prototype: FileReader;
    new(): FileReader;
};
```

Its events are defined as `MSBaseReaderEventMap`:

```typescript
interface MSBaseReaderEventMap {
    "abort": Event;
    "error": ErrorEvent;
    "load": Event;
    "loadend": ProgressEvent;
    "loadstart": Event;
    "progress": ProgressEvent;
}
```

The load event is of generic event type `Event`, but that will not work for the FileReader object.  The load event contains the property `event.target` as do all events generically, but it **does not contain** the property `event.target.result`, which is where the FileReader's data will reside.

https://developer.mozilla.org/en-US/docs/Web/API/FileReader/onload

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

The lib files in this repo are autogenerated by a script in https://github.com/Microsoft/TSJS-lib-generator. changes like these need to be made to the generator instead.
