### ISSUE TITLE
TS 2.7 regression spreading any

### ISSUE THREAD

**Issue by ethanresnick** [Microsoft/TypeScript#20950]
**TypeScript Version:**  2.7.0-dev.20171230

**Code**

```ts
declare const fn: () => Promise<void>;

function a(args: any) {
    return fn(...args);
}
```

**Expected behavior:**
No errors, which seems to be the result in TS 2.6.

**Actual behavior:**
Error on the `fn(...args)` call: Expected 0 arguments, but got one or more.

**Comment by RyanCavanaugh** [comment]
@sandersn Expected, yes?

**Comment by sandersn** [comment]
Yes. I don't see a good reason for spreading anything into a function that takes no arguments.
