### ISSUE TITLE
Intellisense is not showing automatic imports

### ISSUE THREAD

**Issue by alexrock** [Microsoft/TypeScript#20951]
**TypeScript Version:**
2.6.2 - ok
2.7.0-dev.20171116 - ok
2.7.0-dev.20171117 - fail
next - fail

**Code**

package.json:
```json
{
    "name": "test",
    "version": "0.0.0",
    "dependencies": {
        "babylonjs": "^3.2.0-alpha0",
        "babylonjs-gui": "^3.2.0-alpha0"
    }
}
```

tsconfig.json:
```json
{
    "compilerOptions": {
        "target": "es5",
        "module": "es2015",
        "types": [
            "babylonjs",
            "babylonjs-gui"
        ]
    }
}
```

index.ts:
```ts
let button = new Button // Button is missing in completion list
```

**Expected behavior:**
Intellisense shows automatic imports
**Actual behavior:**
Doesn't show

**Comment by andy-ms** [comment]
A simpler example:

**b.ts**

```ts
declare namespace N {
    export const xxx = 0;
}

export = N;
```

**a.ts**
```ts
xx/**/
```

We don't give the completion for an export inside a namespace, although the import fix still works.

**Comment by alexrock** [comment]
I am still having problems here.

**b.d.ts**
```ts
declare namespace N {
	export const xxx: number
}

declare module 'n' {
	export = N
}
```

**c.d.ts**
```ts
declare namespace N.O {
	export const yyy: number
}

declare module 'n-o' {
	export = N.O
}
```

**a.ts**
```ts
xx/**/ // fail
yy/**/ // ok
```

Joining these definition files in just one file, everything works fine.
