### ISSUE TITLE
tsc --init issues

### ISSUE THREAD

**Issue by aaronbeall** [Microsoft/TypeScript#20961]
**TypeScript Version:**  2.6.2

**Code**

```
tsc --init
```

**Expected behavior:**

Includes all compiler options and valid values.

**Actual behavior:**

- Missing `forceConsistentCasingInFileNames`, `skipLibCheck`, `pretty`, `allowUnusedLabels`, `allowUnreachableCode`, `suppressImplicitAnyIndexErrors` options
- Comment for `lib` is `/* Specify library files to be included in the compilation:  */` (nothing after the colon)

**Comment by RyanCavanaugh** [comment]
The list of options provided by `tsc --init` is intended to be somewhat curated; we don't want people randomly turning on e.g. `suppressImplicitAnyIndexErrors` unless they have really thought about it.

**Comment by mhegazy** [comment]
So the list as it shows now is limited to what we have deemed worthy of inclusion. i personally do not see  `forceConsistentCasingInFileNames`, `skipLibCheck`, `allowUnusedLabels`, `allowUnreachableCode`, `suppressImplicitAnyIndexErrors`  as worthy. `pretty` might be worth it though..

so what is this bug tracking? including them all?(do not think this is a good idea) or just specific ones? (if so which)?

**Comment by aaronbeall** [comment]
> so what is this bug tracking?

There's also the comment for `lib` that currently says `/* Specify library files to be included in the compilation: */` -- I would think something should come after the colon, even if it isn't an exhaustive list?

Also, maybe it's just me but I was surprised there are so many options not listed in the generated config, I kind of thought it was all the options, though I can see why it isn't and shouldn't be -- would it be excessive to include a comment in there that there are additional compiler options?

**Comment by mhegazy** [comment]
> would it be excessive to include a comment in there that there are additional compiler options?

well.. part of it is that some of these options are not really used. we can not remove them for back compat purposes.. for instance `allowUnreachableCode`. our data shows this setting used in less than `0.01%` of the total sessions.. so the idea is why let everyone figure out their way through these options, if they are likely not going to use them.

to see all options supported by the compiler, try `tsc --help --all`

**Comment by mhegazy** [comment]
> There's also the comment for lib that currently says /* Specify library files to be included in the compilation: */ -- I would think something should come after the colon, even if it isn't an exhaustive list?

feel free to send a PR to remove the colon from the message

**Comment by nieltg** [comment]
> feel free to send a PR to remove the colon from the message

@mhegazy
Hi! I'm going to try fixing that.
