### ISSUE TITLE
get (or set) function shows description from *both* get and set function on hover

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#20966]
_From @kleinfreund on December 24, 2017 9:36_

- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:41:01.414Z)
- OS Version: Linux x64 4.13.0-21-generic
- Extensions: Extensions are disabled
---

Steps to Reproduce:

1. View the following code with language mode set to JavaScript

   ```js
   class Test {
     constructor() {
       this.value;
     }
   
     /** Getter text */
     get value() {
       return this.value;
     }
   
     /** Setter text */
     set value(value) {
       this.value = value;
     }
   }
   ```

2. Hover over the `value` getter (or setter) function

**Expected behavior**:

`Getter text` (or `Setter text`) appears in the box as the function description.

**Actual behavior**:

`Getter text Setter text` appears in the box as the function description.

_Copied from original issue: Microsoft/vscode#40775_

**Comment by mjbvz** [comment]
TS 2.7.0-insiders.20171214

Here's the TS server requests/responses:

```
[Trace  - 11:13:13 AM] Sending request: quickinfo (212). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/Users/matb/projects/san/x.ts",
    "line": 13,
    "offset": 14
}
[Trace  - 11:13:13 AM] Response received: quickinfo (212). Request took 3 ms. Success: true 
Result: {
    "kind": "property",
    "kindModifiers": "",
    "start": {
        "line": 13,
        "offset": 12
    },
    "end": {
        "line": 13,
        "offset": 17
    },
    "displayString": "(property) Test.value: any",
    "documentation": "Getter text \nSetter text ",
    "tags": []
}
```

**Comment by mhegazy** [comment]
The current behavior now is for symbols with multiple declarations we combine all the comments. this is to address cases where declarations merge.

We could try and filter the jsdoc based on whether the access to the symbol is a read or a write. that will require some rewiring.
