### ISSUE TITLE
Use Latitude and Longitude

### ISSUE THREAD

**Issue by karmen1974** [Microsoft/TypeScript#20960]
I need to do calculations from my current location.
I use the following code:

getLocation() {
  if (navigator.geolocation) {
    navigator.geolocation.getCurrentPosition(
      function(position) {
        alert(position.coords.latitude + ' ' + position.coords.longitude);
        this.lat = position.coords.latitude;
        this.lon = position.coords.longitude;
        alert(this.lat + ' ' + this.lon);
      },
      function errorCallback(error) {
        console.log('Geolocation error : code ' + error.code + ' - ' + error.message);
        alert('Une erreur est survenue durant la géolocalisation. Veuillez réessayer plus tard ou contacter le support.');
      },
      {
          maximumAge: Infinity,
          timeout: 5000
      }
  );
}
}

the first alert is ok. But...

The second alert produces the following error:
ERROR TypeError: Cannot set property 'lat' of null

lat and lon are global variables

**Comment by RyanCavanaugh** [comment]
This is an issue tracker, not a support forum. Please do not ask for help debugging your code here.

**Comment by karmen1974** [comment]
Y le parece poco el problema que tienen, que las variables globales no le funcionen????

**Comment by j-oliveras** [comment]
This fails at runtime, so you have a bug. Most likely, this is null.
