### ISSUE TITLE
keyof for arrays

### ISSUE THREAD

**Issue by bezreyhan** [Microsoft/TypeScript#20965]
**TypeScript Version:**  2.5.3

Would it be possible to have something like the `keyof ` operator for arrays? The operator would be able to access the values in the array.

**Code**
With object we can do the following:
```ts
const obj = {one: 1, two: 2}
type Prop = {
  [k in keyof typeof obj]?: string;
}
function test(p: Prop) {  
  return p;
}

test({three: '3'}) // throws an error
```

Could we do something like the following with arrays?

```ts
const arr = ['one', 'two'];
type Prop = {
    [k in valuesof arr]?: string;
  }
function test(p: Prop) {  
  return p;
}

test({three: '3'}) // throws an error
```

**Comment by DanielRosenwasser** [comment]
You can get `valuesof arr` with the indexed access type `(typeof arr)[number]`, but you'll get `string` instead of `"one" | "two"` without an explicit type annotation. #10195 would help there though.

**Comment by bezreyhan** [comment]
Thanks @DanielRosenwasser, #10195 would be helpful but ideally we would be able to do without indexed access types. What I was looking for was a way to express: "All keys in an object must be a value in an array".

**Comment by DanielRosenwasser** [comment]
You could always define a type alias for that, but you won't be able to get around using `typeof` in conjunction with it.

```ts
export type ValuesOf<T extends any[]>= T[number];

declare var x: ...;
type Foo = ValuesOf<typeof x>;
```

**Comment by bezreyhan** [comment]
That's interesting, I didn't think of that. I'll close out the ticket. Thanks!

**Comment by kpdonn** [comment]
@bezreyhan I came across this issue while searching around for something else. I don't know if this will be useful to you two months later but I think this will do essentially what you want as long as you don't need to save the array in a variable beforehand: 

```ts 
function functionGenerator<T extends string, U = { [K in T]?: string }> (keys: T[]): (p: U) => U {
  return (p: U) => p
}

const testFun = functionGenerator(['one', 'two'])

testFun({one: '1'}) // no error
testFun({two: '2'}) // no error
testFun({three: '3'}) // error as expected because 'three' is not a known property
```

If you do need the array in a variable, it looks like this will work:

```ts
function literalArray<T extends string>(array: T[]): T[] {
    return array
}

const arr = literalArray(['one', 'two'])

const testFun2 = functionGenerator(arr)
testFun2({one: '1'}) // no error
testFun2({two: '2'}) // no error
testFun2({ three: '3' }) // error as expected because 'three' is not a known property
```

Here is a link of those examples in the playground: [Link](https://www.typescriptlang.org/play/#src=function%20functionGenerator%3CT%20extends%20string%2C%20U%20%3D%20%7B%20%5BK%20in%20T%5D%3F%3A%20string%20%7D%3E%20(keys%3A%20T%5B%5D)%3A%20(p%3A%20U)%20%3D%3E%20U%20%7B%0A%20%20return%20(p%3A%20U)%20%3D%3E%20p%0A%7D%0A%0Aconst%20testFun%20%3D%20functionGenerator(%5B'one'%2C%20'two'%5D)%0A%0AtestFun(%7Bone%3A%20'1'%7D)%20%2F%2F%20no%20error%0AtestFun(%7Btwo%3A%20'2'%7D)%20%2F%2F%20no%20error%0AtestFun(%7B%20three%3A%20'3'%20%7D)%20%2F%2F%20error%20as%20expected%20because%20'three'%20is%20not%20a%20known%20property%0A%0A%0Afunction%20literalArray%3CT%20extends%20string%3E(array%3A%20T%5B%5D)%3A%20T%5B%5D%20%7B%0A%20%20%20%20return%20array%0A%7D%0A%0Aconst%20arr%20%3D%20literalArray(%5B'one'%2C%20'two'%5D)%0A%0Aconst%20testFun2%20%3D%20functionGenerator(arr)%0AtestFun2(%7Bone%3A%20'1'%7D)%20%2F%2F%20no%20error%0AtestFun2(%7Btwo%3A%20'2'%7D)%20%2F%2F%20no%20error%0AtestFun2(%7B%20three%3A%20'3'%20%7D)%20%2F%2F%20error%20as%20expected%20because%20'three'%20is%20not%20a%20known%20property)

**Comment by tomzaku** [comment]
@kpdonn  Thanks. But I have problem with this
``` js 
const functionGenerator = <T extends string, U = { [K in T]?: string }>(keys: T[]): U => {
  return keys.reduce((oldType: any, type) => ({ ...oldType, [type]: type }), {})
}
const data = ['one', 'two']
const testFun = functionGenerator(data)
testFun.one
testFun.three << also work

```

**Comment by nickmccurdy** [comment]
Using resolveJsonModule, would it be possible to get the type of an array from a JSON file without explicitly declaring the type of the JSON module and losing typechecking on its data?

**Comment by tpucci** [comment]
@kpdonn I find your solution very interesting.
Any idea how to have the same result with an array of object instead of an array of string ?
The following code passes typescript diagnostic. However, the last line should throw an error.

```ts
function functionGenerator<T extends {name: string}, U = { [K in T['name']]?: string }>(keys: T[]): (p: U) => U {
  return p => p;
}

const testFun = functionGenerator([{name: 'one'}, {name: 'two'}]);

testFun({ one: '1', two: '2' }); // no error
testFun({ two: '2' }); // no error
testFun({ three: '3' }); // error expected but type diagnostic passes
```

**Comment by tpucci** [comment]
> @kpdonn I find your solution very interesting.
Any idea how to have the same result with an array of object instead of an array of string ?
The following code passes typescript diagnostic. However, the last line should throw an error.

If anyone is interested, I found the solution of my [problem](https://github.com/Microsoft/TypeScript/issues/20965#issuecomment-488243223):
```ts
function functionGenerator<
  V extends string,
  T extends {name: V},
  U = { [K in T['name']]?: string }
>(keys: T[]): (p: U) => U {
  return p => p;
}

const testFun = functionGenerator([{name: 'one'}, {name: 'two'}]);

testFun({ one: '1', two: '2' }); // no error
testFun({ two: '2' }); // no error
testFun({ three: '3' }); // throws an error
```

**Comment by NickDubelman** [comment]
Is there anything wrong with doing the following:
`
export type Things = ReadonlyArray<{
    readonly fieldA: number
    readonly fieldB: string
    readonly fieldC: string
    ...other fields
}>

type Thing = Things[number]
`

When I do that, `type Thing` has the correct type. Obviously you wouldn't want to do this by default, but I find myself in the situation where I have something generating array types, but sometimes I want functions to take a single value of that array. The above syntax is kind of weird, but it seems to do the job?

**Comment by benneq** [comment]
Typescript 3.4 made things better:
```
const myArray = <const> ['foo', 'bar'];
type MyArray = typeof myArray[number];
```
👍

**Comment by Serrulien** [comment]
@benneq Thanks for that hint. I'm now able to make a type without having to create an `enum`

```typescript
const pages = <const> [
    {
        label: 'homepage',
        url: ''
    },
    {
        label: 'team',
        url: ''
    }
];

// resulting signature = function getUrl(label: "homepage" | "team"): void
function getUrl(label: (typeof pages[number])['label']) {}

getUrl('homepage') // ok
getUrl('team') // ok
getUrl('bad') // wrong

```

**Comment by bopfer** [comment]
Is there a way to do what @Serrulien [posted](https://github.com/Microsoft/TypeScript/issues/20965#issuecomment-510040954), but also with types defined for each object in the array? 

Something like:

```javascript
type Page = {
  label: string;
  url: string;
};
```

Then enforce that type of each object of the `const` array.  With an array of many elements, it would help to avoid type errors in any individual object.

**Comment by fabb** [comment]
That‘s easy, and you don‘t need `const` for it:
```
const pages: Page[] = [
    {
        label: 'homepage',
        url: ''
    },
    {
        label: 'team',
        url: ''
    }
]

**Comment by bopfer** [comment]
@fabb, right, but I wanted to combine that with something like this to have a type with all the valid labels:

```javascript
type Labels = (typeof pages[number])['label'];
```

Without the `const`, the type is just `string`

**Comment by fabb** [comment]
I guess you have to decide between your literal defining the type, or explicit typing without `const`.

**Comment by ORESoftware** [comment]
I am trying to use `keyof` like so:

```
type Events = [
  'repo:push',
  'pullrequest:unapproved',
  'pullrequest:approved',
  'pullrequest:updated',
  'pullrequest:rejected',
  'pullrequest:fulfilled',
  'pullrequest:created'
  ]


export interface InterosTag {
  [key: string]: {
    [key: keyof Events]: {   // but this does not work
      "jenkins-job": string,
      "deploy": boolean,
      "eks-key": string
    }
  }
}
```

any help appreciated

**Comment by fabb** [comment]
@ORESoftware look at @benneq‘s answer above.

**Comment by ORESoftware** [comment]
@falb i tried earlier today but it didnt work, how would I use it in the context of my code above?

**Comment by fabb** [comment]
@ORESoftware do it like this:
```
const events = ['repo:push', 'pullrequest:unapproved', 'pullrequest:created'] as const

export interface InterosTag {
    [key: string]: {
        [key in typeof events[number]]: {
            'jenkins-job': string
            deploy: boolean
            'eks-key': string
        }
    }
}
```

**Comment by ORESoftware** [comment]
@fabb ok that worked, I missed the `in` operator when I tried last time. The remaining problem is it forces me to have _all_ the keys present, not just a subset of the keys.

I fix that, I tried using:

```typescript
  type Events = typeof events[number];

    [key in Partial<Events>]: {
            'jenkins-job': string
            deploy: boolean
            'eks-key': string
        }
```

but `Partial` is not the right operator. I am looking for a subset of the array values.

**Comment by fabb** [comment]
@ORESoftware you are holding it wrong ;-)

```
type EventData = Partial<
    {
        [key in Events]: {
            'jenkins-job': string
            deploy: boolean
            'eks-key': string
        }
    }
>
```

**Comment by AshleyMcVeigh** [comment]
noob here, based on the suggestions here Im trying to write a helper function to check if an object has the required keys

```typescript

const requiredKeys = <const>[
    'key1',
    'key2',
    'key3'
];


function hasKeys(
  unknownObject: { [key: string]: any },
  requiredKeys: readonly string[]
): unknownObject is { [key in typeof requiredKeys[number]]: unknown } {
  return Object.keys(requiredKeys).every(
    required => unknownObject[required] !== undefined
  );
}
```

this works but unknownObject ends up being typed as `[x: string]: unknown;`, any ideas?

**Comment by benneq** [comment]
@AshleyMcVeigh This should do it:

```ts
function includes<T, U extends T>(arr: readonly U[], elem: T): elem is U {
    return arr.includes(elem as U);
}
```

**Comment by fabb** [comment]
@AshleyMcVeigh you are no noob if you write code like this. It's curious, if you extract `{ [key in typeof requiredKeys[number]]: unknown }` into a named type, it works as expected:
```
const requiredKeys = <const>[
    'key1',
    'key2',
    'key3'
];

type YAY = { [key in typeof requiredKeys[number]]: unknown }

function hasKeys(
  unknownObject: { [key: string]: any },
  requiredKeys: readonly string[]
): unknownObject is YAY {
  return Object.keys(requiredKeys).every(
    required => unknownObject[required] !== undefined
  );
}

const maybeYay: { [key: string]: any } = { key1: 1, key2: 2, key3: 3, otherKey: "other" }
if (hasKeys(maybeYay, requiredKeys)) {
    console.log(maybeYay.key1) // compiles fine
}
```

**Comment by AshleyMcVeigh** [comment]
that is interesting, seems as though typescript isn't quite smart enough to be able inspect the arguments type?

anyway thanks for your help @benneq  and @fabb

**Comment by AshleyMcVeigh** [comment]
So I was playing around and I figured it out.

```typescript
function objectHasKeys<T extends string>(
  unknownObject: { [key: string]: unknown },
  requiredKeys: readonly T[]
): unknownObject is { [Key in T]: unknown } {
  return requiredKeys.every(
    required => unknownObject[required] !== undefined
  );
}

function test(thing: { [key: string]: unknown }) {
  const required = <const>['A', 'B']
  if (!objectHasKeys(thing, required)) return
  thing // <-- this is typed as { A: unknown, B: unknown }
}
```

**Comment by daniel-nagy** [comment]
Is there a way to get a literal type from an iterative operation?

```typescript
function getValues<T>(object: T, keys: (keyof T)[]) {
  return keys.map((key) => object[key]);
}

const result = getValues({ "1": 1, "2": 2, "3": "three" }, ["1", "3"]);

typeof result; // (string | number)[]
```

I want the literal type of the result.

```typescript
typeof result; // [1, "three"]
```

I'd also like to create a generic type to represent this function

```typescript
type GetValues<T, K extends readonly (keyof T)[]> = {
  (object: T, keys: K): T[K[number]][];
};

// produces (1 | "three")[], instead of [1, "three"]
type Values = GetValues<{ "1": 1, "2": 2, "3": "three" }, ["1", "3"]>;
```

**Comment by AmirTugi** [comment]
This is the [release note](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html#const-assertions) with the relevant info about the solution (which @benneq mentioned)

**Comment by daniel-nagy** [comment]
Using `const` does not solve the problem for me.

```typescript
function getValues<T, K extends readonly (keyof T)[]>(
  object: T,
  keys: K
): T[K[number]][] {
  return keys.map(key => object[key]);
}

const result = getValues(
  { "1": 1, "2": 2, "3": "three" } as const,
  ["1", "3"] as const
);

typeof result; // produces (1 | "three")[], instead of [1, "three"]
```

I'm trying to get a literal type from an operation on a literal type. I think the issue is `K[number]` will return a union type which has no understanding of order.

**Comment by fabb** [comment]
@daniel-nagy `T[K[number]][]` results in an array, but you want a tuple. You can keep the tuple type when you take advantage of [mapped type support](https://github.com/Microsoft/TypeScript/pull/26063) used like this: `{ [P in keyof T]: X }` where `T` is the tuple. As far as I have understood, the `keyof T` is the tuple array index (since arrays in js are just objects with indexes as keys), and this syntax builds a new tuple with the same indexes.

All together this _nearly_ works as expected:
```
function getValues<T, K extends readonly (keyof T)[]>(object: T, keys: K): { [P in keyof K]: T[K[P]] } {
    return keys.map(key => object[key]) as any
}
```

While the result type is now correctly `[1, "three"]`, TypeScript shows an error: `Type 'K[P]' cannot be used to index type 'T'.`. I think this is a bug in TypeScript, maybe related to #21760. `@ts-ignore`? 😬

**Comment by fabb** [comment]
@daniel-nagy see the updated code with a workaround for the type error 👆

**Comment by 7kms** [comment]
in the latest ts "version": "3.9.6"
```ts
export const extraKeys = ['app', 'title', 'package', 'deeplink', 'url', 'logo', 'image', 'type'] as const;

export type Extra ={
  [key in typeof extraKeys[number]]: string;
};

```

**Comment by Sharcoux** [comment]
For a value, I found that I can use:

```typescript
const keys = ['app', 'title', 'package', 'deeplink', 'url', 'logo', 'image', 'type'] as const;
type Key = typeof keys[0]
```

**Comment by cstst** [comment]
For what I am doing, something like this is sufficient:

```typescript
type Prop<AcceptableKeys extends Array<string>> = {
  [key in AcceptableKeys[number]]: string;
};

function test(prop: Prop<["one", "two"]>) {
  return prop;
}

test({ three: "3" }); // throws an error
```

I specifically need this functionality for generating specific `APIGatewayProxyEventV2` types for lambda integrations:

```typescript
type Request<
  PathParameters extends Array<string>,
  QueryParameters extends Array<string>,
  Body extends Record<string, unknown>
> = {
  pathParameters: {
    [key in PathParameters[number]]: string;
  },
  queryStringParameters: {
    [key in QueryParameters[number]]: string;
  };
  body: Body;
};

type TestBody = {
  c: string;
};

type TestRequest = Request<["a"], ["b"], TestBody>;

const testOne: TestRequest = {
  pathParameters: { a: "foo" },
  queryStringParameters: { b: "bar" },
  body: { c: "baz" },
};
// No error

const testTwo: TestRequest = {
  pathParameters: { a: "foo" },
  queryStringParameters: { bee: "bar" }, // Throws an error
  body: { c: "baz" },
};
```

**Comment by Esporia** [comment]
For simple array, I do this (add "readonly type")
````ts
export type ValuesOf<T extends readonly any[]>= T[number];

export const ALL_BASIC_FUNCTIONS_NAMES = ["sub", "add", "div", "mul"] as const

````

**Comment by KrzysztofMadejski** [comment]
I use two approaches:
```typescript
// Option 1: If object stores different types
type SomeType = {
  a: number;
  b: string;
}

const typeVar: SomeType = {
    a: 10,
    b: 'string'
}

// used for typechecking
type SomeTypeKey = keyof SomeType;

// create an array to be used in runtime
// disadvantage is that properties need to be repeated
const keys: SomeTypeKey[] = ['a', 'b']; // type checked
let isValidKey = keys.includes('c' as SomeTypeKey)


// Option 2: start from keys array definition, in case all values have the same type

const myKeys = ['foo', 'bar'] as const; // as const does the magic
type MyKey = typeof myKeys[number]; // = 'foo' | 'bar'

type MyMap = Record<MyKey, string>;
type MyMap2 = { [key in MyKey]: string };
```

**Comment by isumix** [comment]
I just managed to make my function return a type checkable object:

``` lang-ts
const indexKeys = <K extends string>(keys: readonly K[]) => {
  type Result = Record<K, number>;

  const result: Result = {} as Result;

  const {length} = keys;

  for (let i = 0; i < length; i++) {
    const k = keys[i];

    result[k] = i;
  }

  return result;
};
```

Here the type checker will complain:

``` lang-ts
// Property 'zz' does not exist on type 'Result'.
const {aa, zz} = indexKeys(['aa', 'bb']); 
```

**Comment by paulwongx** [comment]
As mentioned above by @7kms this works to change an array into a type
```js
const arr= ['foo', 'bar'] as const;
const myVar:typeof arr[number] = "foo"

// Hovering over myVar shows: 
// const myVar: "foo" | "bar"
```
