### ISSUE TITLE
Generic type not being inferred from another generic type

### ISSUE THREAD

**Issue by nunocastromartins** [Microsoft/TypeScript#20963]
First of all, thank you for your work! 
I hope I'm not creating a duplicated issue; I browsed through the existent ones but couldn't find one that fits what I'm describing.

**TypeScript Version:**  2.7.0-dev.20171230

Note that the following is a simple example that showcases the issue I'm presenting. If requested, I may provide use-cases where this type of inference would be useful.

**Code**

```ts
class Test<T, A extends T[]> {
  constructor(public array: A) {}

  getFirstElement(): T | undefined {
    if (this.array.length > 0) {
      return this.array[0];
    }
  }
}

const test = new Test([42]);
const first: number | undefined = test.getFirstElement();
```

**Expected behavior:**
TS infers that `test` is of type `Test<number, number[]>`

**Actual behavior:**
TS infers that `test` is of type `Test<{}, number[]>`
Obviously, the compiler will output:
```
test.ts(12,7): error TS2322: Type '{}' is not assignable to type 'number'.
```

**Comment by RyanCavanaugh** [comment]
Constraints are not inference positions. By this, I mean that the clause `A extends T[]` *doesn't* tell the type system that it should infer `T`'s type from `A`.

If you *really* need two type parameters, you can change the constructor argument a little:
```ts
class Test<T, A extends T[]> {
  constructor(public array: A & { [n: number]: T }) {}

  getFirstElement(): T | undefined {
    if (this.array.length > 0) {
      return this.array[0];
    }
  }
}

const test = new Test([42]);
const first: number | undefined = test.getFirstElement();
```

More likely, you don't actually need `A`, and should just write:
```ts
class Test<T> {
  constructor(public array: T[]) {}

  getFirstElement(): T | undefined {
    if (this.array.length > 0) {
      return this.array[0];
    }
  }
}
```

**Comment by nunocastromartins** [comment]
Interesting. Thank you for your reply!

I do in fact need more than one type parameter; as I mentioned, my example was just a simple illustration of the kind of inference I was expecting.

Using your _workaround_ as inspiration I was able to solve my issue, effectively forcing the type checker to infer one type from the other so, from my side, I'd say the issue is closed.

However, may I ask _why_ doesn't the type system infer this by default?

**Comment by RyanCavanaugh** [comment]
Some comments in #17761 and #18871.

The shortest answer to "why" is because the default answer for making the inference algorithm more complex is "no". In addition to possible circularity problems and more complexity, it would also create some semantic crosstalk - currently inference and constraints are two separable processes and you can fully describe one without the other.

**Comment by nunocastromartins** [comment]
Thank you! :-)
