### ISSUE TITLE
Global var declarations not being autocompleted from ATA

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#20975]
_From @ferdaber on December 27, 2017 14:40_

It seems that the automatically-acquired types for Jest, which declares global variables and namespaces, are not working in autocomplete. I can confirm that the Jest types are downloaded into this directory ~/Library/Caches/typescript/2.6/node_modules/@types/jest/index.d.ts.

A snippet of the vars that are not being autocompleted:
```ts
declare var beforeAll: jest.Lifecycle;
declare var beforeEach: jest.Lifecycle;
declare var afterAll: jest.Lifecycle;
declare var afterEach: jest.Lifecycle;
declare var describe: jest.Describe;
declare var fdescribe: jest.Describe;
declare var xdescribe: jest.Describe;
declare var it: jest.It;
declare var fit: jest.It;
declare var xit: jest.It;
declare var test: jest.It;
declare var xtest: jest.It;
```

`describe` not working:
![image](https://user-images.githubusercontent.com/12239873/34384386-e5a0cd98-eae9-11e7-8f16-af349e056198.png)

- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:35:14.671Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.11.1
code-settings-sync|Sha|2.8.7
sort-lines|Tyr|1.4.1
copy-relative-path|ale|0.0.1
path-intellisense|chr|1.4.2
vscode-svgviewer|css|1.4.3
vscode-eslint|dba|1.4.3
gitlens|eam|7.1.0
prettier-vscode|esb|1.0.1
file-icons|fil|1.0.7
auto-close-tag|for|0.5.5
search-node-modules|jas|1.2.0
docthis|joe|0.6.0
vscode-styled-components|jpo|0.0.10
vscode-language-babel|mgm|0.0.10
vscode-less|mrm|0.6.3
vscode-scss|mrm|0.6.2
python|ms-|0.9.1
debugger-for-chrome|msj|4.0.0
typescript-hero|rbb|1.8.0
open-in-browser|tec|1.1.0
markdown-all-in-one|yzh|0.11.2

(2 theme extensions excluded)

---

Steps to Reproduce:

1. Add Jest as a dev dependency in package.json
2. Create a new JS module, and start typing in the jest globals (`describe`, `it`, etc...)

Reproduces without extensions: Yes

_Copied from original issue: Microsoft/vscode#40867_

**Comment by mjbvz** [comment]
_From @ferdaber on December 27, 2017 14:52_

I should note that this does work if I manually install `@types/jest` into my project's own node_modules directory.

**Comment by RyanCavanaugh** [comment]
We don't automatically stick everything from the ATA cache into your project (at best this is a huge slowdown, at worst it actively breaks everything). I thought we had code to scan the local package.json but it seems that didn't work in this case.

**Comment by mhegazy** [comment]
As @RyanCavanaugh noted not all files in the cache would be included in your intellisene. ATA tries to infer what packages are relevant to the current session from the project layout, e.g. looking at package.json and/or node_modules. trying the scenario you mentioned locally, i am able to get the completions. so do you have `jest` in your `node_modules`? is it in `pacakge.json`? where us your file compared to package.json and node_modules?

> I should note that this does work if I manually install @types/jest into my project's own node_modules directory.

You do not need to install `@types/jest`, just add it to the `"typeAquisition"` section in your tsconfig.json/jsconfig.json:

```json
{
    "compilerOptions": {
        "target": "es5"
    },
    "typeAcquisition": {
        "include": [
            "jest"
        ]
    }
}
```

**Comment by ferdaber** [comment]
Currently I have `jest` as a devDependency in `package.json`, it is also installed in `node_modules` in its usual place (`./node_modules/jest`). I would have assumed that ATA scans every package name in `devDependencies` and `dependencies` in my `package.json` and matches them with what's in the cache to load for Intellisense.

The `node_modules` directory is a direct descendant of my workspace root, as well as `package.json`, and I only have one folder/workspace open.

If I add `typeAcquisition` in my `jsconfig.json` will that exclude all other packages that are automatically acquired? i.e. will I lose the default behavior?

**Comment by mhegazy** [comment]
> I would have assumed that ATA scans every package name in devDependencies and dependencies in my package.json and matches them with what's in the cache to load for Intellisense.

that is what it does. and i am unable to reproduce that on latest. what version of VSCode are you using?

> If I add typeAcquisition in my jsconfig.json will that exclude all other packages that are automatically acquired? i.e. will I lose the default behavior?

no. it just adds to it.

**Comment by mhegazy** [comment]
also can you share your ata server log

**Comment by ferdaber** [comment]
Is there a way I can share it privately? I am dealing with proprietary code.

**Comment by mhegazy** [comment]
do you see it any project you create? or just one? if just one, can you try to recreate the folder structure in a clean project? if all that fails, feel free to email me the project, and i can debug further.

**Comment by ferdaber** [comment]
I can reproduce it in just a nearly-empty object.
[tsserver.log](https://github.com/Microsoft/TypeScript/files/1604896/tsserver.log)

Contents of `package.json`
```json
{
  "name": "@ferdaber/test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "jest": "^22.0.4"
  }
}
```

**Comment by mhegazy** [comment]
I will need the `ti***.log` file instead.

**Comment by mhegazy** [comment]
here is what i am seeing locally:

![animation](https://user-images.githubusercontent.com/8000722/34588326-39fa1d86-f161-11e7-8ba2-31e53be6d21e.gif)

**Comment by ferdaber** [comment]
How do I find the `ti***.log` file? Is there a setting I need to enable?

**Comment by ferdaber** [comment]
Here is the log and the gif. I also disabled all extensions and went to the default settings for everything.
[ti-97265.log](https://github.com/Microsoft/TypeScript/files/1605062/ti-97265.log)
![2018-01-04 17 28 17](https://user-images.githubusercontent.com/12239873/34588845-b601ff30-f174-11e7-83fb-2dda6cba437d.gif)

**Comment by mhegazy** [comment]
this log indicates that you have `jest` in your `"include"`. do you have a log without that.

**Comment by mhegazy** [comment]
why do you have an `index.ts`?

**Comment by ferdaber** [comment]
I was just testing it out to see if maybe it was just a problem with JS language modes, but I can confirm that it doesn't work in Typescript either. I will remove the `jsconfig.json` file.

**Comment by ferdaber** [comment]
![2018-01-04 17 48 58](https://user-images.githubusercontent.com/12239873/34589672-96eeaeb0-f177-11e7-9d5e-3ed8e2b1aa44.gif)
[ti-97990.log](https://github.com/Microsoft/TypeScript/files/1605112/ti-97990.log)

**Comment by mhegazy** [comment]
I can not get a repro for this on latest VSCode. please reopen if you are still running into issues.
