### ISSUE TITLE
Element.prototype.getAttributeNode has a non-nullable output type

### ISSUE THREAD

**Issue by zaclummys** [Microsoft/TypeScript#20977]
**TypeScript Version:**  2.7.0-dev.20171229

**Expected behavior:**
Element.prototype.getAttributeNode should have the following output type: **Attr | null**

**Actual behavior:**
Element.prototype.getAttributeNode has a non-nullable output type: **Attr**

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.
