### ISSUE TITLE
indexed type not accepted as on explicit type

### ISSUE THREAD

**Issue by unional** [Microsoft/TypeScript#20972]
```ts
interface X {
    [x: string]: any
}

let x: X

interface Foo {
    name: string
}

function foo(f: Foo) { }

// Argument of type 'X' is not assignable to parameter of type 'Foo'.
//  Property 'name' is missing in type 'X'.
foo(x)
```

http://www.typescriptlang.org/play/index.html#src=interface%20X%20%7B%0A%20%20%20%20%5Bx%3A%20string%5D%3A%20any%0A%7D%0A%0Alet%20x%3A%20X%0A%0Ainterface%20Foo%20%7B%0A%20%20%20%20name%3A%20string%0A%7D%0A%0Afunction%20foo(f%3A%20Foo)%20%7B%20%7D%0A%0Afoo(x)%0A

**Comment by unional** [comment]
Simplified example:

```ts
let x: { [x: string]: any }

function foo(f: { name: string }) { }

// Argument of type '{ [x: string]: any; }' is not assignable to parameter of type '{ name: string; }'.
//  Property 'name' is missing in type '{ [x: string]: any; }'.
foo(x)
```

**Comment by RyanCavanaugh** [comment]
Why would you *want* that to not be an error? `foo({ })` is clearly not a legal call even though `{ }` is a valid `X`

**Comment by unional** [comment]
That's true. An oversight of mine.

In the context I'm working on, I have a type:

```ts
interface CliArgs {
  _: any[]
  [x: string]: any
}
```
to model any arg input, so I was mentally mapping it as an `any` option bag and expect that to be consumable by any explicit interfaces.
