### ISSUE TITLE
Need better error messages for abstract function missmatch

### ISSUE THREAD

**Issue by HolgerJeromin** [Microsoft/TypeScript#20980]
**TypeScript Version:**  2.6.1.0

**Code (strict null check required)**

```ts
abstract class baseClass {
    public constructor() { }
    public abstract __parent: baseClass | null;
    public abstract getNumber(): number;
}

class childClass extends baseClass {
    public constructor() { super(); }

    protected numberOrUndefined: number | undefined;
    protected numbr: number;
    public getNumber() {
        return this.numberOrUndefined; // Works not. return type not matching base class!
        //return this.numbr; // Works. return type matching base class!
    }

    public __parent: childClass | null;
    public doStuff(co: baseClass) {
        co.__parent = this;
    }
}
```

**Expected behavior:**
The compiler should inform me that getNumber signature does not match the abstract signature.

**Actual behavior:**
test.ts(7,7): error TS2415: Build:Class 'childClass' incorrectly extends base class 'baseClass'.
test.ts(19,9): error TS2322: Build:Type 'this' is not assignable to type 'baseClass | null'.

I have > 120 abstract functions in my base class. Every change can break my childclass (good), but i have no idea what change i missed while refactoring.

**Comment by ikokostya** [comment]
> Expected behavior: The compiler should inform me that getNumber signature does not match the abstract signature.

It does (in simplified example):

```ts
abstract class baseClass {
    public abstract getNumber(): number;
}

class childClass extends baseClass {
    protected numberOrUndefined: number | undefined;
    public getNumber() { // return type not matching base class!
        return this.numberOrUndefined;
    }
}
```

```
Class 'childClass' incorrectly extends base class 'baseClass'.
  Types of property 'getNumber' are incompatible.
    Type '() => number | undefined' is not assignable to type '() => number'.
      Type 'number | undefined' is not assignable to type 'number'.
        Type 'undefined' is not assignable to type 'number'.
```

Looks like in your case `TypeScript` compiler informs about another error about `__parent` property.

**Comment by HolgerJeromin** [comment]
@ikokostya 
There is no error with __parent
I edited my post to make this clear. If the return value matches the parent signature the code compiles.

@RyanCavanaugh 
This is no question.

**Comment by ikokostya** [comment]
Maybe you forget enable `strictNullChecks` option in `tsconfig.json`? Check in [playground](http://www.typescriptlang.org/play/index.html#src=abstract%20class%20baseClass%20%7B%0D%0A%20%20%20%20public%20constructor()%20%7B%20%7D%0D%0A%20%20%20%20public%20abstract%20__parent%3A%20baseClass%20%7C%20null%3B%0D%0A%20%20%20%20public%20abstract%20getNumber()%3A%20number%3B%0D%0A%7D%0D%0A%0D%0Aclass%20childClass%20extends%20baseClass%20%7B%0D%0A%20%20%20%20public%20constructor()%20%7B%20super()%3B%20%7D%0D%0A%0D%0A%20%20%20%20protected%20numberOrUndefined%3A%20number%20%7C%20undefined%3B%0D%0A%20%20%20%20protected%20numbr%3A%20number%3B%0D%0A%20%20%20%20public%20getNumber()%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20this.numberOrUndefined%3B%20%2F%2F%20Works%20not.%20return%20type%20not%20matching%20base%20class!%0D%0A%20%20%20%20%20%20%20%20%2F%2Freturn%20this.numbr%3B%20%2F%2F%20Works.%20return%20type%20matching%20base%20class!%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20public%20__parent%3A%20childClass%20%7C%20null%3B%0D%0A%20%20%20%20public%20doStuff(co%3A%20baseClass)%20%7B%0D%0A%20%20%20%20%20%20%20%20co.__parent%20%3D%20this%3B%0D%0A%20%20%20%20%7D%0D%0A%7D)

**Comment by HolgerJeromin** [comment]
The playground has no strict null check active! 
If you deactivate `strictNullChecks` you are getting no errors in both versions.

**Comment by ikokostya** [comment]
> The playground has no strict null check active!

Enable it and you got error.

> If you deactivate strictNullChecks you are getting no errors in both versions.

Because without `strictNullChecks` type `undefined` is subtype of `T | undefined`. That's why assignment is allowed. See https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#--strictnullchecks for more information.

For desired behavior you should add option

```json
{
     "strictNullChecks": true
}
```
in your `tsconfig.json`.

**Comment by HolgerJeromin** [comment]
@ikokostya 
I think i know pretty well what strictNullCheck does. 

I repeat: 
The compiler should inform me that getNumber **signature** does not match the **abstract signature**.
Instead of that the compiler informs me, that the code "incorrectly extends base class", but this is not helpful.

**Comment by ikokostya** [comment]
I think it just complaints about fist error (in your case there are 2 errors). Just move declaration in abstract class on top:

```ts
public abstract getNumber(): number;
```
and your got error which you want - [playground link](http://www.typescriptlang.org/play/index.html#src=abstract%20class%20baseClass%20%7B%0D%0A%20%20%20%20public%20constructor()%20%7B%20%7D%0D%0A%20%20%20%20public%20abstract%20getNumber()%3A%20number%3B%0D%0A%20%20%20%20public%20abstract%20__parent%3A%20baseClass%20%7C%20null%3B%0D%0A%7D%0D%0A%0D%0Aclass%20childClass%20extends%20baseClass%20%7B%0D%0A%20%20%20%20public%20constructor()%20%7B%20super()%3B%20%7D%0D%0A%0D%0A%20%20%20%20protected%20numberOrUndefined%3A%20number%20%7C%20undefined%3B%0D%0A%20%20%20%20protected%20numbr%3A%20number%3B%0D%0A%20%20%20%20public%20getNumber()%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20this.numberOrUndefined%3B%20%2F%2F%20Works%20not.%20return%20type%20not%20matching%20base%20class!%0D%0A%20%20%20%20%20%20%20%20%2F%2Freturn%20this.numbr%3B%20%2F%2F%20Works.%20return%20type%20matching%20base%20class!%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20public%20__parent%3A%20childClass%20%7C%20null%3B%0D%0A%20%20%20%20public%20doStuff(co%3A%20baseClass)%20%7B%0D%0A%20%20%20%20%20%20%20%20co.__parent%20%3D%20this%3B%0D%0A%20%20%20%20%7D%0D%0A%7D) (need enable `strictNullChecks` in options)

**Comment by HolgerJeromin** [comment]
I only have one real error. 
The second error (__parent) is an subsequent error because the class could not be constructed.
Moving code is only possible when you know where the error is and not very optimal.

**Comment by RyanCavanaugh** [comment]
Here's the simplified repro that doesn't require strict null checks
```ts
class Base {
  n: Base | string;
  fn() {
    return 10;
  }
}
class Derived extends Base {
  n: Derived | string;
  fn() {
    return 10 as number | string;
  }
}
```
Error:
```
../../throwaway/clipboard.ts(7,7): error TS2415: Class 'Derived' incorrectly extends base class 'Base'.
  Types of property 'n' are incompatible.
    Type 'string | Derived' is not assignable to type 'string | Base'.
      Type 'Derived' is not assignable to type 'string | Base'.
        Type 'Derived' is not assignable to type 'Base'.
          Types of property 'n' are incompatible.
            Type 'string | Derived' is not assignable to type 'string | Base'.
              Type 'Derived' is not assignable to type 'string | Base'.
                Type 'Derived' is not assignable to type 'Base'.
```
Note that the error message doesn't mention `fn` even though it's what's actually at fault.

During computation of this error we need to not invoke circular reasoning - essentially we're saying
```
Class 'Derived' incorrectly extends base class 'Base'.
```
*because*
```
        Type 'Derived' is not assignable to type 'Base'.
```
