### ISSUE TITLE
Operator '===' cannot be applied to types x and y

### ISSUE THREAD

**Issue by dancespiele** [Microsoft/TypeScript#20982]
**TypeScript Version:**  Version 2.6.1

**Code**

```ts
export interface ConfigRouters {
    path: 'string',
    component: Component<any>;
    mode?: 'string';
    hash?: 'string';
    routers?: any;
}

export class Router {
    hash: string;
    mode: string; 
    constructor(configRoutes: ConfigRouters) {
        this.hash = configRoutes.hash ? configRoutes.hash : '#';
        this.mode = (configRoutes.hash || configRoutes.mode === 'hash' || 
            configRoutes.mode !== 'history') ?
                'hash' : 'history';
        }
}
```

**Expected behavior:**
It should compiler without errors
**Actual behavior:**
I get theses errors: 
`Operator '===' cannot be applied to types '"string | undefined"' and '"hash"'`
`Operator '!==' cannot be applied to types '"string | undefined"' and '"history"'`

**Comment by ikokostya** [comment]
Check existence of `configRoutes.mode` property 

```ts
configRoutes.mode !== undefined
```
before string comparison.

**Comment by dancespiele** [comment]
wow I didn't realize about string literal :), thank you
