### ISSUE TITLE
ATA not loading node types

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#20988]
_From @blinkspark on December 28, 2017 1:21_

- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:46:23.884Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
vscode-html-css|ecm|0.1.8
auto-close-tag|for|0.5.5
materialize-snippets|len|1.2.2
python|ms-|0.9.1
LiveServer|rit|3.0.2

---

Steps to Reproduce:

1.create a new folder and init with npm init
2.open whith code
3.reqire a node module
4.Intellisence not working (projects that already exists before I upgrade to this version works fine)
![codeissue](https://user-images.githubusercontent.com/3829294/34397341-5e8dfda4-ebb0-11e7-9247-c29a883e0eea.PNG)

Reproduces without extensions: Yes

_Copied from original issue: Microsoft/vscode#40879_

**Comment by mjbvz** [comment]
_From @blinkspark on January 1, 2018 5:52_

My workding directory is : "D:\Development\Node".
I installed a new module useing npm and the Intellisence of that module is ok
my node version is 9.3, I used to use 8.9, it was not works either
And this is my settting
![tim 20180101135204](https://user-images.githubusercontent.com/3829294/34465818-fbb885a2-eefa-11e7-844e-1f4dee0740fc.png)

**Comment by mjbvz** [comment]
_From @blinkspark on January 1, 2018 10:14_

I left vscode open for a long time(3 hours?) and it works fine now.
Is that the problem?

**Comment by mjbvz** [comment]
@blinkspark So it is working now? If not, can you please try manually installing the node typings by running `npm install --save-dev @types/node` in your workspace

**Comment by mjbvz** [comment]
_From @blinkspark on January 3, 2018 6:20_

Yeah, but it appears randomly,when I create a new project.
Install types/node solve this issue.
Seems vs code sometimes won't install typings automatically. 
@mjbvz do you need me to close this issue?

**Comment by mjbvz** [comment]
Moving over to TS since I've seen a few reported issues about picking up `@types/node`

**Comment by mhegazy** [comment]
I am unable to reproduce this locally on latest TS(`@next`) and VSCode (1.9.1). 

@blinkspark can you share your tsserver logs.

**Comment by blinkspark** [comment]
Sorry about not response for a while. I've been busy these days.
This issue appears randomly.  I will upload tsserver logs if it happens again.

**Comment by penggy** [comment]
This also happens to me.  Run npm install --save-dev @types/node works for me.

**Comment by mhegazy** [comment]
@penggy can you share more information.

**Comment by blinkspark** [comment]
I think this is a Internet issue (I'm not sure).
When create a new project and Internet is not stable, vscode will fail install node's typings, and will not install it again, until you install it manually or install a new module.
I can't reproduce the issue now, but I think this is the problem.

**Comment by mhegazy** [comment]
We use `npm` under the covers to install the packages. if `npm` failed in an unrecoverable way, i am not sire what can be done. 

can you share the state of the npm package for node when this issue happens?

**Comment by blinkspark** [comment]
I can reproduce this issue 100% now.
1. Reboot my computer
2. disconnect internet(or under a unreliable network)
3. create a new folder
4. open the folder by vscode
5. create a new js/ts file
Boom, it appears.
 I did not install any module, just opened a new folder. And this is my node and npm versions.
$ npm -v
5.5.1
$ node -v
v9.3.0
My console is git-bash.

I think this problem is caused by unreliable network. 
The issue might not a fatal error but, I think show a alert or show some message in status bar may be more friendly to rookie users.

**Comment by mhegazy** [comment]
I am still unable to repro this issue locally. please share typing installer logs from sessions where you experienced this issue.
