### ISSUE TITLE
Assigning a function that returns a non-void is compatible to a function that should return void.

### ISSUE THREAD

**Issue by benlakey** [Microsoft/TypeScript#20985]
Assigning a function that returns a non-void is compatible to a function that should return void.

**TypeScript Version:**  2.5.3, 2.6

**Code**

```ts
interface Foo {
    doThing(): void;
}

const foo: Foo = {
    doThing: () => 'cats'
}
```

Typescript playground example: 

https://www.typescriptlang.org/play/index.html#src=interface%20Foo%20%7B%0D%0A%20%20%20%20doThing()%3A%20void%3B%0D%0A%7D%0D%0A%0D%0Aconst%20foo%3A%20Foo%20%3D%20%7B%0D%0A%20%20%20%20doThing%3A%20()%20%3D%3E%20'cats'%0D%0A%7D

**Expected behavior:**

The types should be incompatible and produce an error.

**Actual behavior:**

The function that returns a string conforms to a function definition that is supposed to return void.

**Comment by jcalz** [comment]
[FAQ](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-functions-returning-non-void-assignable-to-function-returning-void)

**Comment by benlakey** [comment]
Thanks @jcalz. Closing
