### ISSUE TITLE
Union types confound interface implementation checks

### ISSUE THREAD

**Issue by bworline** [Microsoft/TypeScript#20983]
Why does this compile without error?

**TypeScript Version:**  2.6.1

**Code**

```ts
interface TestInterface {
  setName(name: string | Date): void;
  setAge(years: number | null | undefined): void;
}

// the next line should give build-time error:  
// Class 'TestClass' incorrectly implements interface 'TestInterface'.
class TestClass implements TestInterface { 
  setName(name: string) { // signature does not match interface
    if (name.slice(0, 1) === 'B') {
      console.log('Great name.');
    }
  }
  setAge(years: number) { // signature does not match interface
    console.log(years.toExponential());
  }
}

let x: TestInterface = new TestClass();
x.setName(new Date()); // causes runtime error
x.setAge(null); // causes runtime error
```

**Expected behavior:**
Should get a build-time error: Class 'TestClass' incorrectly implements interface 'TestInterface'.

**Actual behavior:**
No build-time error, and a run-time error later.

**Comment by ahejlsberg** [comment]
It compiles without error parameters of methods are checked *bivariantly*. If you change the interface declaration to use property syntax

```ts
interface TestInterface {
  setName: (name: string | Date) => void;
  setAge: (years: number | null | undefined) => void;
}
```

and compile with `--strictFunctionTypes` (or just `--strict`) you will see the expected errors. See #18654 for rationale and more information.

**Comment by bworline** [comment]
Thank you for the explanation and the work-around.  Much appreciated.

I do hope that you will continue to explore the stricter mode of --strictFunctionTypes that includes methods.  I'm sure that you can appreciate that co/contra/bi-variance is a complex topic that is best left to the compiler to figure out and tell me when I've made a mistake--meaning that most devs are not thinking about these nuances when coding.  My example was meant to demonstrate how easy it is to fall into this particular trap without realizing it and running into a run-time failure later.
