### ISSUE TITLE
Typescript incorrectly inferring type of generic argument

### ISSUE THREAD

**Issue by matt-tyler** [Microsoft/TypeScript#20997]
TypeScript Version: 2.6.2, 2.7.0-dev.20173001

**Reproduction of Issue **

[https://github.com/matt-tyler/typescript-issue-20997](https://github.com/matt-tyler/typescript-issue-20997)

**Expected behavior:**

Typescript selects the first matching function overload, which results in the type T being resolved to the type of the first parameter of the function signature

**Actual behavior:**

Typescript does not select the first matching function overload, which results in the type T being resolved the incorrect type.

**Details***
The AWS typescript definition file defines the following funtions in servicecatalog.d.ts 

```
  /**
   * Lists all portfolios in the catalog.
   */
  listPortfolios(params: ServiceCatalog.Types.ListPortfoliosInput, callback?: (err: AWSError, data: ServiceCatalog.Types.ListPortfoliosOutput) => void): Request<ServiceCatalog.Types.ListPortfoliosOutput, AWSError>;
  /**
   * Lists all portfolios in the catalog.
   */
  listPortfolios(callback?: (err: AWSError, data: ServiceCatalog.Types.ListPortfoliosOutput) => void): Request<ServiceCatalog.Types.ListPortfoliosOutput, AWSError>;
  
  listPrincipalsForPortfolio(params: ServiceCatalog.Types.ListPrincipalsForPortfolioInput, callback?: (err: AWSError, data: ServiceCatalog.Types.ListPrincipalsForPortfolioOutput) => void): Request<ServiceCatalog.Types.ListPrincipalsForPortfolioOutput, AWSError>;
  /**
   * Lists all principal ARNs associated with the specified portfolio.
   */
  listPrincipalsForPortfolio(callback?: (err: AWSError, data: ServiceCatalog.Types.ListPrincipalsForPortfolioOutput) => void): Request<ServiceCatalog.Types.ListPrincipalsForPortfolioOutput, AWSError>;
```

Several other functions that exist in the AWS-SDK are used to list various resources in a similar manner to these two functions.

I figured that I could define the following, so I wouldn't have to keep implementing the paging logic when I wanted to page out all the resources;

```
import * as AWS from 'aws-sdk'
import { isUndefined } from 'util'

export namespace Util {

  export interface PageableResponse {
    NextPageToken?: string
  }
  
  export interface PageableRequest {
    PageToken?: string
  }

  export type Callback<U> = (err: AWS.AWSError, data: U) => void

  export type Lister<T, U> = (
    params: T,
    callback?: Callback<U>
  ) => AWS.Request<U, AWS.AWSError>

  export async function All<T extends PageableRequest, U extends PageableResponse, V> (
    lister: Lister<T, U>,
    fn: (obj: U) => V[] | undefined,
    init?: T
  ): Promise<Array<V>> {
    const list = new Array<V[]>()
    let params: T
    if (isDefined(init)) {
      params = init
    }
    do {
      const response = (await lister(params).promise())
      list.push((fn(response) || []))
      params.PageToken = response.NextPageToken
    } while (!isUndefined(params.PageToken))
    return list.reduce((a, b) => a.concat(b), [])
  }

  export function isDefined<T> (x: T | undefined): x is T {
    return !isUndefined(x)
  }
}
```

This would enable me to do do something like the following, whilst maintaining the ability to typecheck the input and output arguments correctly;
```
const portfolioDetails = await Util.All(serviceCatalog.listPortfolios, r => r.PortfolioDetails)
```
or if there is another input argument required (typically for filtering);
```
const principals = await Util.All(serviceCatalog.listPrincipalsForPortfolio, r => r.Principals, { PortfolioId: '123' })
```

My only issue is that typescript seems to be determining the wrong function to use as the lister from the AWS type definition file. Essentially, T is being resolved to a type of 
`(err: AWSError, data: ServiceCatalog.Types.ListPortfoliosOutput) => void` instead of `ServiceCatalog.Types.ListPortfoliosInput` (it actually inteprets T as a PageableRequest, but if I remove the type constraint it resolves to the former). My understanding was that typescript would resolve the type to the first definition it found that matched (as explained here https://www.typescriptlang.org/docs/handbook/functions.html), but this doesn't seem to be the case in this instance. If I comment out the second definition, it resolves to the correct definition. I've tried a few different things in attempt to force it to resolve to the first definition (like specifying a callback function) but everything I've tried does not seem to work.

Typically the error is;
```
import-servicecatalog/ImportServiceCatalogCompliance.ts (61,51): Argument of type '{ (params: ListPrincipalsForPortfolioInput, callback?: ((err: AWSError, data: ListPrincipalsForPo...' is not assignable to parameter of type 'Lister<PageableRequest, ListPrincipalsForPortfolioOutput>'.
  Types of parameters 'params' and 'params' are incompatible.
    Type 'PageableRequest' is not assignable to type 'ListPrincipalsForPortfolioInput'.
      Property 'PortfolioId' is missing in type 'PageableRequest'.
```

Removing the extends constraint (eg All<T, U extends PageableResponse, V>) gives;

```
import-servicecatalog/ImportServiceCatalogCompliance.ts (61,115): Argument of type '{ PortfolioId: string; }' is not assignable to parameter of type '((err: AWSError, data: ListPrincipalsForPortfolioOutput) => void) | undefined'.
  Object literal may only specify known properties, and 'PortfolioId' does not exist in type '((err: AWSError, data: ListPrincipalsForPortfolioOutput) => void) | undefined'.
```

Whether or not the type constraint is added back, removing the second interface definition removes the compilation error. Intellisense in VS Code confirms that the correct type is determined for T.

**Comment by RyanCavanaugh** [comment]
Please reduce this down to a minimal repro so we can more readily address the issue

**Comment by matt-tyler** [comment]
Hi Ryan,

I've create a minimal reproduction of the issue at the following repository.

[https://github.com/matt-tyler/typescript-issue-20997](https://github.com/matt-tyler/typescript-issue-20997)

**Comment by RyanCavanaugh** [comment]
"minimal" refers to the size of the code needed to reproduce the issue. A minimal repro should be at most 20-30 lines with no external dependencies. The linked repo doesn't appear to be any smaller than the repro you posted

**Comment by aj-r** [comment]
@RyanCavanaugh I have a case in lodash where Typescript is also selecting the wrong overload. Not sure if it's related to @matt-tyler 's issue.

Here is some code that reproduces the issue:

```ts
const items: string | undefined = ["item1", "item2", undefined];
const filtered = _(items).filter((item): item is string => typeof item !== "undefined").value();
// Expected type string[] but got (string | undefined)[]

// However, the following all work as expected and result in a type of string[]:
const filtered1 = _.filter(items, (item): item is string => typeof item !== "undefined");

const filtered2 = _(items).filter<string | undefined, string>((item): item is string => typeof item !== "undefined").value();

const wrapper: _.LoDashImplicitWrapper<string[]> =  _(items).filter((item): item is string => typeof item !== "undefined");
const filtered3 = wrapper.value();
```

The correct overload is defined above the overload that is actually being used. And the correct overload clearly matches, based on my examples that do work correctly.

Interestingly, Visual Studio Code shows me the correct overload when I hover my mouse over the word "filter". But my variable still gets the wrong type.

Tested with `typescript@2.6.2` and `@types/lodash@4.14.93`. (Also tested in `typescript@2.4.1` and it still gets the wrong overload, so this is not a new bug).

**Comment by matt-tyler** [comment]
Updated the reproduction to remove external dependencies - because this is quite abstract I'm having difficulty reducing the number of lines of code though.
