### ISSUE TITLE
Generic constraint with type list

### ISSUE THREAD

**Issue by NN---** [Microsoft/TypeScript#2099]
It is a generalization of #2049 .
I would like to see generic specifying concrete types:

```typescript
// Can specify only A<number> or A<string>
interface A<T is number|string|Object> { }  

interface B<T is number|string> extends A<T> {} // number|string is subtype of number|string|Object .
```

**Comment by RyanCavanaugh** [comment]
In order to be considered, we need suggestions to have at least *some* motivating use cases, examples of desired usage, examples of things that would be / would not be errors and why, etc.. We don't have resources to ask clarifying questions teasing out what these things mean.

**Comment by NN---** [comment]
One of use cases is the following:

```typescript
interface KeyValueBase<K> {
  f(): K;
}

interface KeyValue<K is number|string, V> extends KeyValueBase<K> {
 [key: K]: V
}
```

The key type must be string or number , it is impossible to define this generic right now.
It can be possible to define it and use the type if the feature existed.

**Comment by DanielRosenwasser** [comment]
You could also use a type alias.

```TypeScript
type Key = number | string;

interface KeyValueBase<K> {
  f(): Key;
}

interface KeyValue extends KeyValueBase<K> {
 [key: Key]: V
}
```

**Comment by NN---** [comment]
@DanielRosenwasser It is not the same since I don't know the exact type.
Also the indexer is one of possible samples.

**Comment by litera** [comment]
Object indexer is the perfect example and use case for `is` genetic type parameter constraint. This hasn't been updated in a while. Is there any progress?

**Comment by litera** [comment]
@DanielRosenwasser And btw even when using type aliasing TSLint still throws an error.

**Comment by mhnewsuk** [comment]
One issue I had is with `Object.entries`, but the type definition for that was pretty simple:

```
interface ObjectConstructor {
    entries<TValue>(object: { [key: string]: TValue }): [string, TValue][];
    entries<TValue>(object: { [key: number]: TValue }): [string, TValue][];
}
```

I understand it won't work for everything (objects that aren't strictly used as maps), so it would probably be better to just have your own "wrapper function" around Object.entries, but I thought I'd mention it in case it helps anyone else who finds this issue.
