### ISSUE TITLE
ATA inclusion in JS projects should include bundled .d.ts files from NPM packages

### ISSUE THREAD

**Issue by RyanCavanaugh** [microsoft/TypeScript#20993]
https://developercommunity.visualstudio.com/content/problem/169330/vs-2017-javascript-intellisense-does-not-work.html

When we construct the program in a JS context we include stuff from `node_modules/@types`, but don't scan other `node_modules` to look for packages that have bundled .d.ts files, e.g. `axios`. This results in UMD globals being missing from the completion list.

**Comment by Postlagerkarte** [comment]
As workaround I copied over the types from the axios directoy into `node_modules/@types/axios` and was surprised that this didn't light up intelisense. Why is that? I also tried to copy the type definitons to the ata cache (AppData\Local\Microsoft\TypeScript\2.5\node_modules\@types) which also didn't help. Any other workaround until 2.8 is released?

**Comment by andreabbondanza** [comment]
Any news about the fix? Without the "reference mode" we are developing in blindly mode.

**Comment by RyanCavanaugh** [comment]
This seems like a bad idea at this point - not many global libraries in use, and too many libraries would get picked up
