### ISSUE TITLE
Variables initialized to null/undefined are not checked for "noImplicitAny" errors.

### ISSUE THREAD

**Issue by UselessPickles** [Microsoft/TypeScript#21015]
**TypeScript Version:**  2.6.2

**Code**
With 'noImplicitAny' option enabled...

```ts
// Type of 'something' and 'somethingElse' are implicitly 'any' here
let something = null;
let somethingElse = undefined;
```

**Expected behavior:**
A compiler error due to the implicit `any` type of `something` and `somethingElse`

**Actual behavior:**
No compiler error.

**Comment by UselessPickles** [comment]
This same issue applies to function parameters with a default value of null/undefined:

```ts
// Type of 'value' is implicitly 'any', but no compiler error.
function doSomething(value = null) {
    alert(value);
}
```

**Comment by mhegazy** [comment]
I am assuming you have `"noImplicitAny": true, "strictNullChecks": false`.

The compiler tries to "evolve" the types of your variables based on their usage. a no-implicit any error will be shown if the compiler can not tell for sure the type of the variable.. for instance if the variable is used in a function, since the compiler does not track when functions are called. here is an example:

```ts
// Type of 'something' and 'somethingElse' are implicitly 'any' here
let something = null;
let somethingElse = undefined;

something = 3;  // something is a number now

var n: number = something; //OK 

var s: string = something; //Error number is not assignable to string

function f() { 
    somethingElse;  // Now you get a noImplicitAny error
}
```

**Comment by UselessPickles** [comment]
@mhegazy 

No, I have `"strictNullChecks": true`.

I would expect the noImplicitAny error at `let something = null;` because that's where it is implicitly given it's `any` type.

The way that the type "evolves" throughout the code based on what values are assigned is cool, but when "noImplicitAny" is enabled, I want to be forced to specify the desired type at the declaration so that subsequent assignments are typechecked accordingly, rather than allow the var to adopt whatever union of types (potentially incorrect) happen to be assigned to it later.

**Comment by mhegazy** [comment]
> I would expect the noImplicitAny error at let something = null; because that's where it is implicitly given its any type.

The compiler can do better than that, it can see if it can tell the type from the use of the variable.

**Comment by mhegazy** [comment]
> so that subsequent assignments are typechecked accordingly,

they are type checked. they are checked against the type of the variable after its first assignment. the type `any` is never observed. if it is, an error is flagged.

**Comment by UselessPickles** [comment]
Here's an example where the current behavior leads me on a wild goose chase to figure out where I messed up:

```ts
function getSomething(conditional: boolean) {
    let something = null;

    if (conditional) {
        something = 10;
    } else {
        // This is where my real mistake is, assigning the wrong value/type to "something", but no error
        // here, and no implicit any error up where I declared "something"
        something = "hello";
    }

    return something;
}

const result = getSomething(true);

// Compiler error here complaining that type 'number | string' cannot be assigned to 'number'
// Requires tracing back through code to figure out why it is 'number | string' instead of 'number' 
// as I intended.
const roundedResult = Math.round(result);
```

This would have been immediately a non-issue if I got a "no implicit any" error at the declaration of "something". I would have then specified the type as `number | null`, and then I would have gotten an obvious error where I erroneously assigned a string to "something".

**Comment by RyanCavanaugh** [comment]
You still get in that state even if `noImplicitAny` worked differently:
```ts
function getSomething(conditional: boolean) {
    if (conditional) {
        return 10;
    } else {
        return "hello";
    }
}

const result = getSomething(true);
const roundedResult = Math.round(result);
```

**Comment by UselessPickles** [comment]
@RyanCavanaugh I think we're veering off-topic now by changing my example to not have `let something = null` in it. It was an example to show how that initialization would make more sense to fail with a "no implicit any" error.

The point I'm trying to make is that:
*  `let something = null` implicitly gives `something` a type of `any` (regardless of how the type may "evolve" later in the code due to various assignments, it's still implicitly `any` at the point of initialization).
* The "noImplicitAny" option is supposed to not allow implicit `any` types. 
* Therefore it's reasonable to expect `let something = null` should cause a "no implicit any" error.
* There are situations where, when initializing a variable to null/undefined without specifying a type for the variable, the current behavior makes it difficult to track down a mistake in the code, while a "no implicit any" error at the point of initialization would have prevented the mistake in the code (or  a compiler error would at least point directly to the mistake in the code).

**Comment by RyanCavanaugh** [comment]
What I'm saying is that the behavior that caused your problem is *not* the presence of an "implicit" `any`. The `any` type never actually manifests here, so there's no implicit `any` to error on. If you don't like the behavior of variables of initialized with `null` / `undefined`, it's probably more appropriate to write a lint rule to disallow them as that's more of a coding style issue.
