### ISSUE TITLE
Wrong global scope in web worker file

### ISSUE THREAD

**Issue by tra1lblazer** [Microsoft/TypeScript#21016]
**TypeScript Version:**  2.6.2

```Window``` has the following postMessage declaration:
```postMessage(message: any, targetOrigin: string, transfer?: any[]): void;```

```Worker``` on the other hand has different one:
```postMessage(message: any, transfer?: any[]): void;```

When you have some file, like ```worker.ts``` the global scope defaults to ```Window```, so when you write something like 

```
self.addEventListener('message', (e) =>
{
   postMessage('Hello from worker!'); 
});
```
it will fail to compile (because it wrongly assumes that ```this``` will be ```Window```). When on the other hand you write in ```worker.ts```
```
self.addEventListener('message', (e) =>
{
   postMessage('Hello from worker!', '*'); 
});
```
it will compile, but fail to execute, as it tries to execute the one from Worker and fails to convert '*' to sequence.
**Expected behavior:**
You can specify the global scope as clearly with Web Workers it's not Window any more.
**Actual behavior:**
Either compilation or execution fails.

**Comment by mhegazy** [comment]
> When you have some file, like worker.ts the global scope defaults to Window

are you using `--lib worker`?
