### ISSUE TITLE
Autos should display returned results of last function

### ISSUE THREAD

**Issue by paulvanbrenk** [microsoft/TypeScript#21017]
Copied from https://github.com/Microsoft/nodejstools/issues/1245

Currently autos window seems to be totally empty on NTVS _or any other TypeScript/JavaScript case_. In many languages usually it displays return values of last called functions and some autos/locals when you step over.

See this C++ sample screenshot
![image](https://user-images.githubusercontent.com/5273975/34590253-6fd7e088-f16a-11e7-8a79-92f5a691a237.png)

**Comment by RyanCavanaugh** [comment]
Closing due to lack of demand
