### ISSUE TITLE
Constructor definition with generics

### ISSUE THREAD

**Issue by HolgerJeromin** [Microsoft/TypeScript#21026]
**TypeScript Version:**  2.6.2

**Code**
```ts
class Animal {
    numLegs: number;
}
class Bee extends Animal { }
// from documentation
function createInstance<A extends Animal>(c: new () => A): A {
    return new c();
}
createInstance(Bee).numLegs;

// my code
function register(name: string, cnstr: { new <C extends Animal>(): C }): void {
  return;
}
register('myBee', Bee);
```

**Expected behavior:**
Should compile as 'Bee extends Animal' as seen in the `createInstance` call.
Can i change my `cnstr` definition to make that work?

**Actual behavior:**
Argument of type '`typeof Bee`' is not assignable to parameter of type '`new <C extends Animal>() => C`'.
  Type '`Bee`' is not assignable to type '`C`'.

**Comment by alexrock** [comment]
```ts
function register<C extends Animal>(name: string, cnstr: { new(): C }): void
```

**Comment by HolgerJeromin** [comment]
My real use case is more complex as i need to save the constructor. 
But there we have exactly the problem that after reusing the Animal constructor from cache
TS can not guarantee the subtype anymore. 

Thanks @alexrock for helping. :)
