### ISSUE TITLE
Support es7 exponation operator

### ISSUE THREAD

**Issue by fdecampredon** [Microsoft/TypeScript#2102]
https://github.com/rwaldron/exponentiation-operator I don't think it needs proposal. 
Few emitting examples : 
```javascript 
x**y 
Math.pow(x,y)

x **= y 
x = Math.pow(x, y);
```

**Comment by RyanCavanaugh** [comment]
Creating an `ES7` label :smile:

What happens if `Math` is shadowed in the current scope? Error?

**Comment by fdecampredon** [comment]
> What happens if Math is shadowed in the current scope? Error?

I guess, a more sophisticated solution could be to capture `pow` in some way before `Math` gets shadowed but it's not really necessary in my opinion. Shadowing `Math` is not so common....

**Comment by basarat** [comment]
> What happens if Math is shadowed in the current scope

error :+1:

**Comment by DanielRosenwasser** [comment]
I'm sure we could just perform [some appropriate tests to see if `Math.pow` is working correctly](http://xkcd.com/217/).

**Comment by fdecampredon** [comment]
@DanielRosenwasser you want to check if `Math.pow` return a fine result if `Math` has been shadowed ?

**Comment by DanielRosenwasser** [comment]
Sorry, you'll have to forgive me, that was a joke. I've amended my comment to clarify it.

**Comment by fdecampredon** [comment]
No that's me sorry, since my english is far from being perfect I often fail to understand what is a joke in some context ^^.

**Comment by danquirk** [comment]
We obviously want/will support this when the time comes but given how early it is in ES7's development process we'd rather close this and wait on locking down exactly what ES7 is doing. As we've always said, ending up misaligned with a future ES version is our worst case scenario. Although it may be quite likely this ends up in ES7 as currently spec'd the risk of that not being the case isn't enough to add this to TypeScript today given the relatively low value of this operator.

**Comment by RyanCavanaugh** [comment]
Once ES7 decides the exact syntax here (I could see `^^` or `**` happening) and whether or not it's exactly equivalent to `Math.pow`, we can revisit this to see about downlevel emit.
