### ISSUE TITLE
Quick fix at await to make current function async

### ISSUE THREAD

**Issue by jwbay** [Microsoft/TypeScript#21034]
**TypeScript Version:**  2.7.0-dev.201xxxxx

**Code**

```ts
function foo() {
  await/*1*/ bar();
}
```

**Expected behavior:**
At 1, offers a code action that converts the innermost function to async:

```ts
async function foo() {
  await bar();
}
```

**Actual behavior:**
Error at 1 with no quick fix offered

**Comment by mhegazy** [comment]
A PR for adding the new quick fix would be appreciated. should be a simple one to add.

**Comment by Mosho1** [comment]
I'd like to work on this, I think I have all I need (taking examples from the files in `src/services/codefixes`).

**Comment by mhegazy** [comment]
thanks @mohsen1 !
