### ISSUE TITLE
API: unable to get Symbol of destructuring shorthand initializer

### ISSUE THREAD

**Issue by ajafff** [Microsoft/TypeScript#21046]
**TypeScript Version:**  2.7.0-dev.20180106

**Code**

```ts
let a = '';
let b: string;
({b = /*1*/a} = {b: 'b'});
```

**Expected behavior:**
Hovering over `a` at `/*1*/` shows type `string`.
Calling `checker.getSymbolAtLocation(node)`, where `node` is the Identifier at `/*1*/`, returns the correct Symbol

**Actual behavior:**
Hovering over `a` shows type `any`
Calling `checker.getSymbolAtLocation(node)` returns `undefined`

The former seems to be a symptom caused by the latter.

Note that if I change it to `{b: b = a}` I get the correct result.

**Comment by DanielRosenwasser** [comment]
There's a couple of "what do I do for these semi-ambiguous syntaxes" helpers to help with `getSymbolAtLocation`:

```ts
        getSymbolsOfParameterPropertyDeclaration(parameter: ParameterDeclaration, parameterName: string): Symbol[];
        getShorthandAssignmentValueSymbol(location: Node): Symbol | undefined;
        getExportSpecifierLocalTargetSymbol(location: ExportSpecifier): Symbol | undefined;
        getExportSymbolOfSymbol(symbol: Symbol): Symbol;
        getPropertySymbolOfDestructuringAssignment(location: Identifier): Symbol | undefined;
```

I think you want `getShorthandAssignmentValueSymbol`.

**Comment by DanielRosenwasser** [comment]
Sorry, misread the issue, ignore my last comment.
