### ISSUE TITLE
Question: AST Walker: How can I get comments from ast

### ISSUE THREAD

**Issue by Jack-Works** [Microsoft/TypeScript#21049]
**TypeScript Version:**  2.6.0

I see there is no clear way to get comments from AST.

```typescript
/* tslint:disabled */
/* File: x.ts */
... codes
```

And I want to get `/* tslint:disabled */` (but no .getText() and find what is comment by myself)

`.forEachChild()` can't do this.

Any help? Thanks.

**Comment by ajafff** [comment]
TypeScript does not provide an easy way to get all comments. You need to scan before and after each token (note: some tokens are not in the AST) using `ts.getLeadingCommentRanges` and `ts.getTrailingCommentRanges`. You also need to make sure to not scan inside template strings, JSDoc or JSX text (if applicable).

My library `tsutils` provides some helper methods to deal with comments.
TSLint uses `tsutils.forEachComment` to iterate through all comments of the file.

But there is actually a faster way, if performance matters for your use case:
Use a regular expression to scan for everything that looks like the comment you want to find, for example: `/\/\* tslint:disable \*\//g`.
For every match of this regexp you use `tsutils.isPositionInComment` or `tsutils.getCommentAtPosition` to check if this is really a comment and not the content of a (template) string, JSX text or a comment inside a comment.
As an example you can look at the implementation of finding such disable comments in my own linter: https://github.com/ajafff/wotan/blob/d22eb11924daff2ec7f07ce09b77374469a71c97/src/line-switches.ts#L9-L16

On a related note: it's actually `tslint:disable`, not `tslint:disabled`

**Comment by Jack-Works** [comment]
Cool, I'll try tsutils!
