### ISSUE TITLE
Add supportedContentEncodings to PushManager 

### ISSUE THREAD

**Issue by gauntface** [Microsoft/TypeScript#21041]
The latest spec for PushManager defines `supportedContentEncodings` ([MDN has docs here](https://developer.mozilla.org/en-US/docs/Web/API/PushManager/supportedContentEncodings)). The current definition in TypeScript does not define this value. Secondly, TypeScript does not allow extending / merging of the definition because the global definition of PushManager is an instance of PushManager, instead of the Interface.

**TypeScript Version:**  2.6.2

**Code**

```ts
// Results in: Property 'supportedContentEncodings' does not exist on type '{ new (): PushManager; prototype: PushManager; }'.
console.log(PushManager.supportedContentEncodings);
```

```ts
interface PushManager {
  supportedContentEncodings?: string[];
}

// Results in: Property 'supportedContentEncodings' does not exist on type '{ new (): PushManager; prototype: PushManager; }'.
console.log(PushManager.supportedContentEncodings);
```

**Expected behavior:**
PushManager interface to match spec or allow merging of the interfaces.

**Actual behavior:**
PushManager doesn't merge the interface because PushManager is an instance. The definition being:

```ts
interface PushManager {
    getSubscription(): Promise<PushSubscription>;
    permissionState(options?: PushSubscriptionOptionsInit): Promise<PushPermissionState>;
    subscribe(options?: PushSubscriptionOptionsInit): Promise<PushSubscription>;
}

declare var PushManager: {
    prototype: PushManager;
    new(): PushManager;
};
```

I'm not sure why `declare var PushManager` is needed. As far as I'm aware, developers aren't able to create their own instance of a PushManager, they are provided an instances or access variables on the Interface.

I'm happy to attempt a PR to add `supportedContentEncodings` and remove the declaration if the above understanding seems valid.

**Comment by gauntface** [comment]
Note: Proposed changes would be: https://github.com/gauntface/TypeScript/commit/25c11d200354844df5ea128632b66d28588a7f70

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by jwbay** [comment]
In my Chrome console, `supportedContentEncodings` is on the constructor (the var declaration), not the instance (the interface):

```
> console.assert(!!PushManager.prototype.permissionState)
> undefined
> console.assert(!!PushManager.supportedContentEncodings)
> undefined
```

The fix should probably be
```diff
declare var PushManager: {
+   supportedContentEncodings?: string[];
    prototype: PushManager;
    new(): PushManager;
};
```

**Comment by a-tarasyuk** [comment]
@mhegazy I think this issue can be closed [`lib.d.ts#L14290`](https://github.com/Microsoft/TypeScript/blob/master/lib/lib.d.ts#L14290)

**Comment by mhegazy** [comment]
thanks @a-tarasyuk
