### ISSUE TITLE
spread operator in combination with Set reports error 'error TS2461: Type 'Set<string>' is not an array type.'

### ISSUE THREAD

**Issue by basti1253** [Microsoft/TypeScript#21058]
**Code**

```ts
let data: string[] = [];
data.push('foo');
data.push('foo');
data.push('bar');
data = [...new Set(data)];
```

**Expected behavior:**
`data = [...new Set(data)]` should match `data = Array.from(new Set(data));`
=> ```["foo", "bar"]```

**Actual behavior:**
typescript compilation error "error TS2461: Type 'Set<string>' is not an array type."

**Comment by basti1253** [comment]
additional information:
appears in typescript V2.6.2 & typescript@next

**Comment by ajafff** [comment]
To make spread work, you either need `"target": "ES6"` (or higher) or `"downlevelIteration": "true"` in the `compilerOptions` of your tsconfig.json

**Comment by basti1253** [comment]
This worked. Thank you very much for the hint.
