### ISSUE TITLE
infer any with strict: true

### ISSUE THREAD

**Issue by cevek** [Microsoft/TypeScript#21056]
**TypeScript Version:**  2.7.0-dev.20180107

**Code**

```ts
function factory<T>(Class: new () => T): T {
    return new Class();
}
class A<T> {
    val: T;
}
var a = factory(A);
a.val; // is any
```

**Expected behavior:**
`.val` is `{}`

**Actual behavior:**
`.val` is `any`

**Comment by cevek** [comment]
@RyanCavanaugh I've updated the code

**Comment by mhegazy** [comment]
![image](https://user-images.githubusercontent.com/8000722/34697864-fc1e5ab4-f489-11e7-9ee7-70759f7e49b3.png)

**Comment by cevek** [comment]
Oops, sorry, my bad, my VS Code uses old typescript lib
