### ISSUE TITLE
No Generic Type Missmatch

### ISSUE THREAD

**Issue by dkirchhof** [Microsoft/TypeScript#21051]
I know, there are many generic issues, but i wasn't able to find the right words, the right issue or the right stackoverflow thread. Well, i'm struggeling around with a basic generic problem.

**TypeScript Version:**  2.6.2

**Code**

```ts
class Generic<Type> { }
function test<T>(a: Generic<T>, b: Generic<T>) { }

test(new Generic<string>(), new Generic<number>()); // no error
test<number>(new Generic<string>(), new Generic<number>()); // no error
test<string>(new Generic<string>(), new Generic<number>()); // no error
```

**Expected behavior:**
IntelliSense or at least the compiler should tell me, that the generic types don't match each other

**Actual behavior:**
No warning or error will be shown.

**Comment by jwbay** [comment]
There are no references in Generic to Type that make the different instantiations incomparable to TypeScript's structural type system. Add a reference somewhere to see your expected errors. At least:

```ts
class Generic<Type> {
    private type: Type;
}
```

https://github.com/Microsoft/TypeScript/issues/202 tracks nominal typing support, if that's what you're after.

**Comment by dkirchhof** [comment]
Wow, didn't know, that this is necessary. Thanks
