### ISSUE TITLE
No autocompletion for Indexable Types

### ISSUE THREAD

**Issue by MarvinHannott** [Microsoft/TypeScript#21053]
**TypeScript Version:**  2.7.0-dev.201xxxxx

**Code**
There is no autocompletion for interfaces of Indexable Types:

```ts
interface I {
    [key: string]: {
        x: string,
        y: number,
    };
}

const x: I = {
    test: { x: "", y: 0 },
    test1: {x: "", y: 1},
};

x.?
```
But for simple Object Literals, there is autocompletion:

```ts
const y = {
    test: { x: "", y: 0 },
    test1: { x: "", y: 1 },
};

y.test = ...
```

**Expected behavior:**
There should be autocompletion either way.

**Actual behavior:**
Strangely, it only works for objects that don't have an type annotation for an Indexable Type.

**Comment by sylvanaar** [comment]
You declared the type of `x` to be `I` which means all we know about `x.` is that any valid property name string can go there. This is how it is supposed to work.

**Comment by MarvinHannott** [comment]
So there is no way I could get the keys through autocompletion?
