### ISSUE TITLE
Typescript type checking of JS - Can't reliably use @type to set type... strange bug

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#21082]
_From @David-Else on January 8, 2018 18:6_

- VSCode Version:  1.19.1
- OS Version: Fedora 27

Steps to Reproduce:

1. enable type checking in .js file with` // @ts-check`
2. paste this and hover over the variable `gender`

```js
/** @type {number} */
let gender;
```
It should correctly say 'number', now change to:

```js
/** @type {string} */
let gender;
```
It won't update, stays as a number. Now try:

```js
/** @type {number} */
var gender;
```
It should correctly change. It will now take going from let to var to actually select the correct type.

It's not just the hover over info that is broken, it really does get the type wrong and that makes the rest of the application generate linting errors everywhere.

Something seems badly broken, can't use type checking, which would be awesome.

Does this issue occur when all extensions are disabled?: Yes

_Copied from original issue: Microsoft/vscode#41306_

**Comment by mjbvz** [comment]
Confirmed in latest TypeScript 2.7-insiders-20180108 as well. The type info does not seem to be getting updated if you only edit the jsdoc

**Comment by andy-ms** [comment]
This seems to have to do with the fact that we're editing text in a comment. Adding an extra space between `let` and `gender` makes it update correctly.
