### ISSUE TITLE
Whitespace formatting between for and await

### ISSUE THREAD

**Issue by Mosho1** [Microsoft/TypeScript#21084]
**TypeScript Version:**  2.7.0-dev.20180108

**Code**

```ts
async function f() {
    for          await (const x of g()) {
        console.log(x);
    }
}
```

**Expected behavior:**

Should be formatted:

```ts
async function f() {
    for await (const x of g()) {
        console.log(x);
    }
}
```

**Actual behavior:**

No changes are made by the formatter.

**Comment by mhegazy** [comment]
PRs welcomed.

**Comment by esakkiraj** [comment]
@mhegazy Would like to take this up and work on it.

**Comment by mhegazy** [comment]
go for it.

**Comment by esakkiraj** [comment]
@mhegazy Hi. Need help in finding the formatter part of codebase.

**Comment by mhegazy** [comment]
Please see https://github.com/Microsoft/TypeScript/pull/21113 as an example.

**Comment by mhegazy** [comment]
Thanks @esakkiraj!
