### ISSUE TITLE
Issue with generic extension of object with index signature that returns functions

### ISSUE THREAD

**Issue by dontsave** [Microsoft/TypeScript#21096]
**TypeScript Version:**  2.7.0-dev.20180109

Hi. I ran into this issue trying to assign a class to a generic type that takes in T which extends an index signature type [s:string]:Function. The same issue happens with index sig [s:string]:new(..._)=>any

**Code**

```ts
class C {
}

type Test<T extends {[s:string]:Function}> = {};

const t:Test<{c:C}> = { //error
	c:C,
};

type Test2 = {
	[s:string]:Function
}

const f:Test2 = {c:C}; //fine
```

**Expected behavior:**
I should be able to assign {c:C} to the generic type

**Actual behavior:**

error: 

Error:(6, 14) TS2344: Type '{ c: C; }' does not satisfy the constraint '{ [s: string]: Function; }'.
  Property 'c' is incompatible with index signature.
    Type 'C' is not assignable to type 'Function'.
      Property 'apply' is missing in type 'C'.

**Comment by mhegazy** [comment]
i think you meant `Test<{c:typeof C}>` there. `C` refers to the instance type of `C`, `typeof C` refers to the type of the constructor function for `C`.

**Comment by dontsave** [comment]
Thanks yeah typeof does fix it. But I'm still a little confused why I don't have to use typeof in the second example where {c:C} is accepted as an object of type {[s:string]:Function}. If C is not evaluated as equivalent to the constructor new()=>any type then shouldn't it fail there too?

**Comment by dontsave** [comment]
that makes sense now thanks. Took a minute to wrap my head around.
