### ISSUE TITLE
Implementing generic methods with void

### ISSUE THREAD

**Issue by TimothyEarley** [Microsoft/TypeScript#21094]
**TypeScript Version:**  2.7.0-dev.201xxxxx

**Code**

```ts
interface A<T> {
  foo(t: T)
}

class B implements A<string> {
  foo() {}
}
```

**Expected behavior:**
Compiler error: Class 'B' incorrectly implements interface A<string>

**Actual behavior:**
No compiler error.
This also leads to this weird piece of code:
```ts
const b: A<string> = new B();
b.foo(); // compiler error -> wrong number of args
b.foo("bar"); // calls B.foo(), but what happens to the argument?

// but if we use the more concrete type:
const b2: B = new B();
b2.foo(); // now correct (calls B.foo())
b2.foo("bar"); // compiler error, as it should be
```

**Related:**
I assume this would be a semantically correct way of expressing the desired generics constraints
```ts
class B implements A<void> {
  foo() {}
}
```

**Comment by andy-ms** [comment]
In TypeScript a subclass doesn't have to exactly match the signatures of its parent class, it just has to be compatible. `foo(): void` is compatible with `foo(t: T): void` because it's allowed to not use a parameter.

**Comment by TimothyEarley** [comment]
Thank you for the quick answer. I now understand the technical reason for it, but I still find it very unintuitive.  Typescript already has a notion of non-optional parameters (in method calls), so I don't see why it couldn't be expanded to this case (maybe it breaks something else I'm not aware of?).
Anyway, I'll close this issue due to "works as designed".

**Comment by andy-ms** [comment]
A non-optional parameter must be *supplied* in a call. It doesn't have to be *declared* in an implementation. There's nothing type-unsafe about ignoring a parameter; but it is unsafe to not supply it because the implementation may expect it to be there. An example:
```ts
type T = (n: number) => void;
const f: T = n => {};
// Parameter does not need to be *declared* when *implementing* T
const f2: T = () => {};
// Argument must be *supplied* when *calling* a T
f(); // error
```

**Comment by TimothyEarley** [comment]
I understand that leaving out the parameter when declaring the method is type-safe.
It just seems less "programmer" safe, i.e. more prone to user error. Especially in my example where we write conflicting (but type-safe) definitions of what the class is supposed to be (string vs void).
I do agree with your example though, that would be a valid case for having the option of leaving out the parameter (although I prefer making it explicit with something like [underscores for unused parameters](https://kotlinlang.org/docs/reference/whatsnew11.html#underscores-for-unused-parameters)).
I guess enforcing declaration at some places (e.g. interfaces with concrete classes) and not at others (e.g. arrow functions) would be even more unintuitive, so the current solution in TypeScript is fine.
