### ISSUE TITLE
Properties named with const are not excluded from implicit indexers

### ISSUE THREAD

**Issue by zhuravlik** [Microsoft/TypeScript#21091]
**Code**

```ts
declare var prop1: string;
const prop2 = "p2";

var y = {
    [prop1]: 1,
    [prop2]: "a"
};

y.p3 // <-- has type string | number, but should be just number; because only 'p2' can be string
```

**Expected behavior:**
'p3' cannot have type 'string', so it should be just 'number'

**Actual behavior:**
'p3' has type 'string | number'

**Comment by ahejlsberg** [comment]
This is working as intended. When an object literal contains a computed property we infer an index signature with a union type of _all_ properties in the object literal. To implement the behavior you expect we would need the ability to describe the type of properties with any name (as indicated by type `string`) except a particular name (as indicated by type `"p2"`). That would add quite a bit of complexity that I don't think we want.

**Comment by zhuravlik** [comment]
Thanks a lot for the explanation.
