### ISSUE TITLE
Import and merge declaration is not working

### ISSUE THREAD

**Issue by nieltg** [Microsoft/TypeScript#21093]
Import and merge declaration is not working, nor is prohibited by the compiler.

**TypeScript Version:**  Version 2.7.0-dev.20180109

**Code**

```ts
declare module 'observe' {
  export namespace Trait {
    export interface Observable {
      observe (): void
    }
  }
}

declare module 'run' {
  import { Trait } from 'observe'
  export namespace Trait {         // No "symbol already defined" error,
    export interface Runnable {    // but it also doesn't merge.
      run (): void
    }
  }
  export class Dog implements Trait.Observable, Trait.Runnable {
    observe (): void
  }
}
```

**Expected behavior:**

Duplicate identifier error thrown by the compiler, or merge the definitions.
I prefer them to be merged so I can put definitions in multiple files.

**Actual behavior:**

TypeScript only recognize `Trait` from `observe` module. Namespaces themselves are not merged.

```
test.ts(16,55): error TS2694: Namespace ''observe'.Trait' has no exported member 'Runnable'.
```

**Comment by andy-ms** [comment]
In this case I think we should give you a duplicate-definition error, since the `export namespace Trait` inside `module 'run'` is different than the one in `module 'observe'`.
(The correct way to extend `'observe'.Trait` would be to write `declare module 'observe' { export namespace Trait { ... } }` a second time.)

**Comment by mhegazy** [comment]
This is a bug alright. the code does not do what most ppl think it would, and that is not ideal..

Having said that, we have had this behavior for over 4 years now, and users have code bases that use that. Adding the error is not going to change the behavior per se, it is just going to break the build for existing users. i would rather we leave this as won't fix for now.
