### ISSUE TITLE
composition of never

### ISSUE THREAD

**Issue by qballer** [Microsoft/TypeScript#21097]
tested with `typescript@2.7.0-dev.20180109`
**Code**

```ts
function never2(): never {
    throw 'never gonna give up'
}


function never1(): never {
    never2()
///conversation marker
}

function ninja(): never{
    process.exit(1)
}
```

**Expected behavior:**
never1 and ninja functions should compile without errors
I would also expect that any code after the marker will be considered unreachable code .

**Actual behavior:**
getting on both:
error TS2534: A function returning 'never' cannot have a reachable end point.

**Comment by mhegazy** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/10973.

change the function to use `return` as a workaround:

```ts
function never1(): never {
    return never2();
}
```

**Comment by qballer** [comment]
10x
