### ISSUE TITLE
CSS.escape is not supported

### ISSUE THREAD

**Issue by yukulele** [Microsoft/TypeScript#21090]
`CSS.escape` is not supported by `dom` lib
https://developer.mozilla.org/en-US/docs/Web/API/CSS/escape

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by mhegazy** [comment]
Fixed by https://github.com/Microsoft/TypeScript/pull/22381
