### ISSUE TITLE
Not to remove unused  import module ?

### ISSUE THREAD

**Issue by zD98** [Microsoft/TypeScript#21114]
**TypeScript Version:** 2.4.1

**Code**
```
// tsconfig.json
{
...
"jsx": "preserve",
...
}
```
```
// my preact Component
import {h, Component} from 'preact'
class C extends Component<any, any> {
    render(){
    // ...
    }
}
```
```
// after compiled
import { Component } from 'preact'
```
So it will throw an error, such as "h is not defined"

**Expected behavior:**
```
// after compiled
import {h, Component } from 'preact'
```
**Actual behavior:**
```
// after compiled
import {Component} from 'preact' 
```
**Related:**

**Comment by zD98** [comment]
Now I have to add a hard code. 
```
import {h as PreactH , Component} from 'preact'
const h = PreactH
```

**Comment by mhegazy** [comment]
Assuming you set `--jsxFactory h`, we should always preserve this import, and make sure `h` is defined in the output if you ever use a JSX element in this file.

**Comment by zD98** [comment]
@mhegazy thanks for the quick reply!
`--jsxFactory h` is ok in a pure TS + Preact project. However,  my project has React and Preact frameworks.

**Comment by mhegazy** [comment]
I do not think we can keep both.. the compiler has no way of knowing which one is used otherwise.

**Comment by mhegazy** [comment]
I was wrong about my original analysis. `h` is preserved if it is in the `--jsxFactory`. so this is not a bug. having both `React.createElement` and `h` in the same project is tracked by https://github.com/Microsoft/TypeScript/issues/15386 and https://github.com/Microsoft/TypeScript/issues/18131
