### ISSUE TITLE
Formatter inserts extra space between function call and array indexer

### ISSUE THREAD

**Issue by yume-chan** [Microsoft/TypeScript#21111]
**TypeScript Version:**  2.7.0-insiders.20180108

**Code**

```ts
function test() { return []; }
test()[0]
```

**Expected behavior:**

Keep as it.

**Actual behavior:**

```ts
function test() { return []; }
test() [0]
```

**Related:**

It's caused by #20615, after reverting it the problem is disappeared.

**Comment by mhegazy** [comment]
PRs welcomed.

**Comment by lankaapura** [comment]
I'd like to fix this one, any guidance where to start?

**Comment by yume-chan** [comment]
@lankaapura Thanks in advance.

You can check the problematic pull request (#20615) for reference. It reordered the formatting rules causes wrong rule to take priority.

Add new rules or edit existing rules to remove the extra space, then write a test for it.

**Comment by lankaapura** [comment]
Thanks @yume-chan 

I've sent my first PR to typescript project 😃

**Comment by mhegazy** [comment]
thanks @lankaapura !
