### ISSUE TITLE
Formatter inserts extra space for `(a | b)[]` types

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#21118]
**TypeScript Version:**  2.7.0-dev.20180108

**Code**

```ts
interface Foo { 
	bar: (string | number)[]
}
```

Run format

**Expected behavior:**
No change

**Actual behavior:**
Extra space inserted before `[]`

```ts
interface Foo {
	bar: (string | number) []
}
```

**Comment by mhegazy** [comment]
should be fixed by https://github.com/Microsoft/TypeScript/pull/21113
