### ISSUE TITLE
Make type unions work with generics

### ISSUE THREAD

**Issue by mertdeg2** [Microsoft/TypeScript#21120]
**TypeScript Version:** all

**Code**

```ts
type foo = string|number;

class Baz<T extends foo> {
  x: T = 'a';
}
```

**Expected behavior:**
I expected to be able to assign something to x. (As my coworkers explained to me) In this case, you can't assign anything to x, because "T extends foo" means T is subtype of foo (Not the other way around).

**Second Expected behavior:**
Given above, I think it would be nice if TS allowed something like:

```ts
type foo = string|number;

class Baz<foo extends T> {
  x: T = 'a';
}
```

Or maybe something like below (which i heard is supported in Java)?

```ts
type foo = string|number;

class Baz<foo super T> {
  x: T = 'a';
}
```

**Comment by mhegazy** [comment]
The first example is wrong as you already noted. `Baz<number>` is a valid instantiation, and thus `x: number = "a"` is invalid.
The second is tracked by https://github.com/Microsoft/TypeScript/issues/14520

**Comment by mertdeg2** [comment]
Thanks @mhegazy
