### ISSUE TITLE
Converting a generic index signature interface to a specific interface.

### ISSUE THREAD

**Issue by LucasPaganini** [Microsoft/TypeScript#21121]
**TypeScript Version:**  2.7.0-dev.201xxxxx

**Code**

```ts
interface GenericFields {
	[key: string]: boolean
}

interface SpecificFields {
	id?: boolean,
	name?: boolean
}

const fn = (fields: GenericFields) => {
	// Do something with the fields
}

const specificFields: SpecificFields = {
	id: true,
	name: false
}

const genericFields: GenericFields = {
	id: true,
	name: false
}

fn(specificFields) // works
fn(genericFields) // error
```

**Expected behavior:**

No error, typescript understands that every key in the SpecificFields maps to a boolean.

**Actual behavior:**

Error: Argument of type 'SpecificFields' is not assignable to parameter of type '{ [key: string]: boolean; }'. Index signature is missing in type 'SpecificFields'.

**Related:**

I haven't found anything, maybe I just wasn't searching the right way. I searched for "TypeScript Index signature errors" and "Index signature is missing in type", no luck so far.

I'm also using `typescript@next`.

**Comment by mhegazy** [comment]
Types are open in TS. So `SpecificFields` could be assigned a value that say has `other: string`. 
Type `GenericFields` has a stronger constraint, it says **all** properties has to be of type `boolean`.
