### ISSUE TITLE
Programmatic API?

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#2113]
I just wonder how or if I can use Typescript as a programmatic API? I mean taking Typescript code as input and outpouts Javascript,

**Comment by DanielRosenwasser** [comment]
Yes, as a matter of fact, you can use version 0.4 of [our compiler API](http://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API) (which is probably what you want) and [our language service API](http://github.com/Microsoft/TypeScript/wiki/Using-the-Language-Service-API) (more suited to building editor extensions).

Out of curiosity, is there anything you had specifically in mind?
