### ISSUE TITLE
TS2.7 produces illegal .d.ts files for objects with computed property names

### ISSUE THREAD

**Issue by mprobst** [Microsoft/TypeScript#21138]
**TypeScript Version:**  2.7.0-dev.20180110

**Code**

```ts
export const SOME_STRING = 'api-key';
export const DEFAULTS = {
  [SOME_STRING]: 'some value',
};
```

**Expected behavior:**

Produce a valid .d.ts file.

**Actual behavior:**

Produces:

```
export declare const SOME_STRING = "api-key";
export declare const DEFAULTS: {
    [SOME_STRING]: string;
};
```

The declaration of `[SOME_STRING]: string` gives `[ts] A computed property name in a type literal must directly refer to a built-in symbol.`

**Comment by mhegazy** [comment]
Just to clarify.. you mean illegal in previous versions of the compiler.

**Comment by mprobst** [comment]
You are right. The bug I was trying to pin down is rather that you cannot create a type from `DEFAULTS`:

```
import {DEFAULTS} from './decl';
type z = typeof DEFAULTS;  // z is {}
type keys = keyof z;  // keys is never
```

**Comment by mprobst** [comment]
This might be related to #13042?

**Comment by mhegazy** [comment]
> You are right. The bug I was trying to pin down is rather that you cannot create a type from `DEFAULTS`:
```
import {DEFAULTS} from './decl';
type z = typeof DEFAULTS;  // z is {}
type keys = keyof z;  // keys is never
```

I am not seeing this locally on `typescript@next`:

![image](https://user-images.githubusercontent.com/8000722/34888392-01948020-f77f-11e7-9a5e-7f08652d2df4.png)

**Comment by mprobst** [comment]
I can repro the issue with TS2.6, but indeed not typescript@next, so seems fixed already (and we'll have to work around it for the TS2.6 migration).
