### ISSUE TITLE
StrictPropertyInitialization does not understand calls to helpers

### ISSUE THREAD

**Issue by berickson1** [Microsoft/TypeScript#21132]
**TypeScript Version:**  2.7.0-dev.20180110

**Code**

```ts
export class Test {
    private _foo: string;
    constructor() {
        this._init();
    }

    private _init() {
        this._foo = 'test';
    }
}
```
https://github.com/berickson1/Playground/blob/master/strictPropertyInitError.ts

**Expected behavior:**
Code compiles with strict flags on

**Actual behavior:**
strictPropertyInitError.ts(4,13): error TS2564: Property '_foo' has no initializer and is not definitely assigned in the constructor.

**Comment by mhegazy** [comment]
The compiler does not analyze all calls from the constructor. for these, use definite assignment operator `!`. see https://github.com/Microsoft/TypeScript/pull/20166

**Comment by RyanCavanaugh** [comment]
See also long discussion of how this would be an expected effect #8476

**Comment by berickson1** [comment]
I understand that inheritance could make tracking calls from the constructor tricky if public methods were called.
Has there been any thought regarding just tracking private method calls for variable initialization?  We've done something similar to reset internal state of classes for unit testing. In this way we could do the following. 

```typescript
export class Test {
    private _foo: string;
    constructor() {
        this._init(); //<- follow this chain
        this.myMethod();<- don't follow this chain
    }

    private _init(override?: string) {
        this._foo = override || 'test';
    }
    
    public myMethod() {
        this._foo = 'bar'; // This isn't used to track strict property init
    }

    public resetState() {
        this._init('reset');
    }
}
```
