### ISSUE TITLE
unwanted automatic formatting on { in Visual Studio 2017 15.5

### ISSUE THREAD

**Issue by pjannesen** [Microsoft/TypeScript#21139]
Visual Studio 2017 15.5 introduced a unwanted automatic formatting on { and there is no way to disable it.

Under tools->Options->Text Editor->JavaScript.TypeScript->Formating->General there are 4 options:
-	Format completed line on Enter
-	Format completed statement on ;
-	Format completed block on }
-	Format on past.

I have all 4 options disabled. But Visual studio automatic formats when I press ‘{‘. 

This behavior is introduced with a recent update op visual studio and still exists in version 15.5.3
This is a very annoying bug for me. Pressing control Z after a { (undo formatting) and do a manual indentation.

**Comment by mhegazy** [comment]
I am not seeing this on local installations on latest. so seems this has already been fixed.
![animation](https://user-images.githubusercontent.com/8000722/34838954-ced17730-f6b4-11e7-9e30-ad3a8e0479db.gif)

**Comment by pjannesen** [comment]
The automatic formatting happens on a **open** brace. '{'  not on a **close** brace '}'

**Comment by pjannesen** [comment]
![vs15 5 reformat](https://user-images.githubusercontent.com/14162980/34840034-067a9d16-f704-11e7-808a-a6bc71eb6552.gif)

**Comment by mhegazy** [comment]
thanks for the clarifications, so it was added in https://github.com/Microsoft/TypeScript/pull/16657, but we never added a checkbox to disable it. we should fix that.

**Comment by billti** [comment]
A fix has been checked in for the next update of Visual Studio (15.7, not 15.8). It will go out in the second preview (it missed the first, which is due any day now). The option will show up as seen below.

![formatonopeningbrace](https://user-images.githubusercontent.com/993909/37306423-ed681806-25f4-11e8-9e02-fef6914d4587.png)
