### ISSUE TITLE
Find References on constructors

### ISSUE THREAD

**Issue by bpasero** [Microsoft/TypeScript#2114]
I dont find a way to "Find References" on a constructor of a class. Is this not supported?

**Comment by mhegazy** [comment]
It is not available currently. but seems like a good feature to add.

**Comment by DanielRosenwasser** [comment]
In the mean time, if I'm not mistaken (I'm not by a dev machine), you should be able to do FindAllRefs on the class name itself.

**Comment by bpasero** [comment]
Well, my intent is to find references of a call to a constructor :)

**Comment by bpasero** [comment]
Any update here? I constantly have to use text-find to make this happen...

**Comment by DanielRosenwasser** [comment]
Hey @bpasero we've got a lot on our hands now, so it's not at the top of our list, but we are accepting PRs from the community.

**Comment by aleksey-bykov** [comment]
`Alt + F12` in VS surprisingly works as expected
