### ISSUE TITLE
In a union, types with index signatures should contribute types to all properties

### ISSUE THREAD

**Issue by sandersn** [Microsoft/TypeScript#21141]
Currently, putting a type with nothing but a string index signature in a union prevents all properties from being accessible. Instead, the type should contribute its index type to all properties:

```ts
type U = { foo: { bar: true }, baz: true } | { [key: string]: string };
declare var u: U;
u.foo
u.baz
```

Currently, `foo` and `baz` are not found on `u`. But they should be present, and have types `{ bar: true } | string` and `true | string` respectively.

**Comment by RyanCavanaugh** [comment]
@sandersn let's give it a try
