### ISSUE TITLE
Format Document in VS2013 Update 4 breaks particular Typescript

### ISSUE THREAD

**Issue by John15213** [Microsoft/TypeScript#2115]
Hello

I'm not sure if the Typescript team manages the code that runs for formatting TypeScript in the Visual Studio editor (via Edit | Advanced | Format Document) or not, but if so see the link below.  For me, the code formatter is mangling some comments, breaking the code.   The connect item has attachments with the original before and after samples as zip files.  Thank You  

https://connect.microsoft.com/VisualStudio/Feedback/Details/1145387

Code before and after

/*  before  */

var f = function (j) {

	switch (j) {
		case 1:
				/* when current checkbox has focus, Firefox has changed check state already
				on SPACE bar press only
				IE does not have issue, use the CSS class
				input:focus[type=checkbox] (z-index = 31290)
				to determine whether checkbox has focus or not 
				*/
			break;
		case 2:
			break;

	}

}

/* after */

var f = function (j) {

	switch (j) {
		case 1:
			ent checkbox has focus, Firefox has changed check state already
			 press only
			have issue, use the CSS class
			type=checkbox] (z-index = 31290)
			 whether checkbox has focus or not 
						;
		case 2:
			break;

	}

}

**Comment by mhegazy** [comment]
@John15213 thanks for reporting the issue. I can not see the issue on the latest bits. what version of TypeScript are you using?

**Comment by John15213** [comment]
I am using 1.4,  The connect item I linked to has disappeared for me at least and cutting and pasting from my code snippet above as displayed in the browser doesn't reproduce either - but I can reproduce from my local files.  I imagine this means the exact formatting tab/spaces are important for reproducing.

**Comment by mhegazy** [comment]
yup that did it. i can see the issue now.
