### ISSUE TITLE
Assigning to an inherited setter in a class declaration clobbers the setter's type

### ISSUE THREAD

**Issue by voithos** [Microsoft/TypeScript#21153]
**TypeScript Version:**  typescript@next

**Code**

```ts
class Root {
  set prop(a: (string|number)[]) { /* Important setter code... */ }
}

class TypeClobberer extends Root {
  // `prop` is now number[], Argh!
  prop = [1, 2, 3];
}
class Broken extends TypeClobberer {
  prop = ['test'];
}

class NonTypeClobberer extends Root {
  // This works, though.
  constructor() {
    super();
    this.prop = [1, 2, 3];
  }
}
class NotBroken extends NonTypeClobberer {
  constructor() {
    super();
    this.prop = ['test'];
  }
}
```

**Expected behavior:**
The assignment to `prop` in `TypeClobberer` wouldn't change the property's type, since it's an inherited setter.

**Actual behavior:**
Does not compile, with the following error:

```
Class 'Broken' incorrectly extends base class 'TypeClobberer'.
  Types of property 'prop' are incompatible.
    Type 'string[]' is not assignable to type 'number[]'.
      Type 'string' is not assignable to type 'number'.
```

**Related:**

**Comment by Kovensky** [comment]
Actually, in ES terms, it _must_ change the property's type; class fields are created using DefineOwnProperty _specifically_ to not invoke any superclass setters.

What TS can do is enforce that the types must be compatible because of the superclass/subclass assignability rules.

**Comment by voithos** [comment]
Interesting! My mental model was that field assignments were basically just assignments at the beginning of the constructor. Thanks for the explanation.
