### ISSUE TITLE
Adding MapLike<T> to es5.d.ts

### ISSUE THREAD

**Issue by ryanmcdermott** [Microsoft/TypeScript#21151]
`MapLike<T>` is a very useful type and is used as an internal type in the compiler. It would be very helpful to expose this type, and as of the latest version of TS I used (2.6.2) I do not see it exposed. I've added a link below where it might be relevant to add this as a type, near `ArrayLike<T>`. What are everyone's thoughts about this?

https://github.com/Microsoft/TypeScript/blob/master/src/lib/es5.d.ts#L1301

**Comment by DanielRosenwasser** [comment]
I'm not super big on `MapLike` because ES2015's `Map` is, well, not `MapLike` which is confusing. I think there is a need for `ArrayLike` because there are certain places in ECMAScript where if something is not also an `Iterable`, there will be a fall-back to anything with a `length` property.

**Comment by Kovensky** [comment]
Wouldn't the ES5 equivalent be a `Record<string, T>`?

It is definitely *not* `Map`-like, but it's what people were using before `Map`.

**Comment by ryanmcdermott** [comment]
Thanks for the feedback! Given that, I'll close this issue
