### ISSUE TITLE
Salsa - Missing Intellisense and error with ts-check when 'express' packgage is installed but not used.

### ISSUE THREAD

**Issue by mpawelski** [Microsoft/TypeScript#21164]
**Vs Code Version**: 1.19.1
Tested on Linux and Windows.

I created simple folder with index.js and jconfig.json file:

_index.js_
```js
const http = require('http');

const hostname = '127.0.0.1';
const port = 3000;

const server = http.createServer((req, res) => {
  res.statusCode = 200;
  res.setHeader('Content-Type', 'text/plain');
  res.end('Hello World\n');
});

server.listen(port, hostname, () => {
  console.log(`Server running at http://${hostname}:${port}/`);
});
```
_jsonconfig.json_
```json
{
    "compilerOptions": {
        "target": "ES6",
        "module": "commonjs",
        "jsx": "preserve"
    },
    "exclude": [
        "node_modules",
        "**/node_modules/*"
    ]
}
```

Intellisense works here for imported modules:

![image](https://user-images.githubusercontent.com/2056282/34873389-4329c160-f795-11e7-926e-69f214ccac5e.png)

But when I install `express` library (by `npm install express -s`), the typeof imported module is `any`

![image](https://user-images.githubusercontent.com/2056282/34873406-5494825a-f795-11e7-8ef4-ee92cbe46e4f.png)

now when I add `// @ts-check` i get error 

![image](https://user-images.githubusercontent.com/2056282/34873524-a9056bd8-f795-11e7-93e9-25639c8b2308.png)

But it works again when I import "express"

![image](https://user-images.githubusercontent.com/2056282/34873559-dac19854-f795-11e7-8dcd-9af95c7b2a4d.png)

This was very confusing that I lost Intellisense (and got errors when used _checkJs:true_ in _jsconfig.json_) just by simply installing package.

**Comment by mpawelski** [comment]
I can reproduce it it reliably on 2 machines locally. Using latest VS Code (1.19.2).
Even without _jsconfig.json_, just create new folder, create package.json (npm init or yarn init)
```
C:\Users\Mariusz\Documents\_kodzenie\typescript> mkdir node_salsa_test1 | cd
C:\Users\Mariusz\Documents\_kodzenie\typescript\node_salsa_test1> yarn init
yarn init v1.3.2
question name (node_salsa_test1):
question version (1.0.0):
question description:
question entry point (index.js):
question repository url:
question author:
question license (MIT):
question private:
success Saved package.json
Done in 2.49s.
C:\Users\Mariusz\Documents\_kodzenie\typescript\node_salsa_test1> code .
```
add _index.js_ with this content:
```js
//@ts-check
const http = require('http');

const hostname = '127.0.0.1';
const port = 3000;

const server = http.createServer((req, res) => {
  res.statusCode = 200;
  res.setHeader('Content-Type', 'text/plain');
  res.end('Hello World\n');
});

server.listen(port, hostname, () => {
  console.log(`Server running at http://${hostname}:${port}/`);
});
```
and when you `yarn add express` Vs Code shows error
![image](https://user-images.githubusercontent.com/2056282/34889235-923fe896-f7cd-11e7-9b6a-7f29f269366b.png)

I don't see any logs in "Typescript" output in vs code,  only just that `[Info  - 19:19:02] Started TSServer`. Is it possible that Vs code doesn't show logs here when there are no ts files?

---
I put sample project on github. Maybe this will help to reproduce it. Run:
```sh
git clone https://github.com/mpawelski/typescript_issue_21164.git
cd typescript_issue_21164/
yarn
code .
```
And see if Vs Code shows errors. It does on my 2 machines. And when I uncomment `const express = require('express');` error goes away.

**Comment by mhegazy** [comment]
OK, thanks for the extra details.. i think this is the same issue as what https://github.com/Microsoft/TypeScript/pull/20844 is trying to handle..

the reason is both `require` and `"http"` are not defined when the file is loaded (since there is no file in the project that includes a definition for them), so you get the errors. when the file is open. shortly after, a background thread kicks in and looks through the project, and determines it needs `@types/node` to be included in the context, and when that happens the errors are re-validated, and they go away.

Obviously the experience is not ideal and we need to fix it. as a workaround, you can locally install `@types/node` and that should do the trick.

**Comment by mhegazy** [comment]
Should be covered by the proposal in https://github.com/Microsoft/TypeScript/issues/21933.
