### ISSUE TITLE
[proposal] allow to import JSON via ESM syntax

### ISSUE THREAD

**Issue by JounQin** [Microsoft/TypeScript#21160]
webpack@4 adds a new feature: allow to import JSON via ESM syntax, and add unused exports elimination for JSON modules.

https://github.com/webpack/webpack/issues/6244

Rollup seems to support this feature a long time ago.

What means tree shaking will also works for `.json` files, but for now it is not possible to use it in `.ts`, because we have to declare `*.json` module by ourselves like following:

```ts
declare module '*.json' {
  const content: any
  export = content
}
```

Then we must use `import * as json from './test.json'`, which will break json tree shaking.

It would be great if ts treats json as first class citizen like es module.

```ts
import { a } from './test.json'
```

**Comment by Kovensky** [comment]
`import * as json from './test.json'` by itself will not break json tree shaking, as long as the `json` namespace object does not escape.

The "tree shaking" itself just means that webpack will try to omit top level object keys that are not referenced, but it will not omit anything if the `default` export is used.

There also seems to be a problem where `import * as json from './test.json'; json.default === json` is true, but in an ES modules implementation that cannot be true.

**Comment by JounQin** [comment]
@Kovensky Thx for your explanation and I tried it, tree shaking really worked.
Although import JSON via ESM syntax would be great, but I'll close it for now.
