### ISSUE TITLE
Closure error TS2532

### ISSUE THREAD

**Issue by ViktorPegy** [Microsoft/TypeScript#21162]
**TypeScript Version:**  2.6.2 | 2.7.0-dev.20180112

**Code**

```ts
// test.ts
function foo(map: Map<string, string>) {
    let bar = map.get('key');
    if (!bar) {
        return;
    }

    let res1 = bar.repeat(3);

    let fun = () => {
        let res2 = bar.repeat(3);
    }
}
```

**Expected behavior:**
no errors

**Actual behavior:**
test.ts(11,20): error TS2532: Object is possibly 'undefined'.

**Comment by ahejlsberg** [comment]
This is working as intended. Type guards remain in effect across function boundaries only when the guarded variable(s) are considered constant. This is the case for `const` local variables and parameters that never occur as assignment targets in the function, so if you declare `bar` using `const` it works as you expect. See #10357.
