### ISSUE TITLE
New Website Logo: Dotin

### ISSUE THREAD

**Issue by MehranKH** [Microsoft/TypeScript#21178]
Please fill the following out:

- Name: Dotin
- Homepage url: http://www.dotin.ir/
- Logo: https://portal.dotin.ir/wp-content/uploads/2016/08/Gen.Dotin_.13940309.Ver1_.00.png

**Comment by DanielRosenwasser** [comment]
Thanks! This should go out on our next publish. For the record, your site's HTTPS certificate seems to have some problems!
