### ISSUE TITLE
Make high priority to function declaration overload with this argument

### ISSUE THREAD

**Issue by cevek** [Microsoft/TypeScript#21181]
**TypeScript Version:**  2.7.0

**Code**

```ts
declare function A(handler: any): void;
declare function A(this: {foo: number}, handler: any): void;
var y = { A: A };    
y.A(123); // no error
```

**Expected behavior:**
Error that is `y` is not `{foo: number}`
**Actual behavior:**
No error

**Comment by andy-ms** [comment]
You've declared two overloads on `A` -- when a function has multiple overloads that means it should work in either situation. This means that the first overload will always match, so long as you pass in exactly one argument, making the second overload unreachable.
If you want to allow `this` to be missing, but if present require `{ foo: number }`, you could write it like so:
```ts
declare function A(this: {foo: number} | void, handler: any): void;
A(1);
var y = { A: A };
y.A(123); // error
var z = { A, foo: 0 };
z.A(123); // no error
```

**Comment by cevek** [comment]
Yeah, I understand this, but there is no way to rewrite builtin lib.d.ts

**Comment by andy-ms** [comment]
Merging in declarations only ever adds functionality, so that's working as intended. You could make a PR changing that though.
