### ISSUE TITLE
Javascript Maps are treated as arrays under spread operation

### ISSUE THREAD

**Issue by alexluecke** [Microsoft/TypeScript#21186]
**TypeScript Version:**

Tested with version typescript@2.7.0-dev.20180113 and latest 2.6.2:

```typescript
const a = new Map<number, number>();
a.set(0, 0);
a.set(1, 1);

const b = new Map<number, number>();
b.set(2, 2);
b.set(3, 3);

const c = [...a, ...b]; // Type 'Map<number, number>' is not an array type.
```

Running `tsc` on the above code also produces:

```javascript
var a = new Map();
a.set(0, 0);
a.set(1, 1);
var b = new Map();
b.set(2, 2);
b.set(3, 3);
var c = a.concat(b);
```

**Expected behavior:**

Maps under spread operator are treated like Maps.

**Actual behavior:**

Maps are treated as arrays.

**Comment by ajafff** [comment]
Since you get a type error (`Type 'Map<number, number>' is not an array type.`) you cannot expect valid transpiled code.
Also note that you cannot spread Maps without `target` >= ES6 or `--downlevelIteration` enabled.

**Comment by alexluecke** [comment]
My tsconfig:

```
{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "lib": ["es6", "dom"],
    "strict": true
  }
}
```

Still get `'Map<number, number>' is not an array type.` when running `tsc`. When running with `--downlevelIteration` it produces the transpilation error:

` Type 'Map<number, number>' is not an array type or does not have a '[Symbol.iterator]()' method that returns an iterator.`

**Comment by alexluecke** [comment]
`tsc file.ts --lib es2015 --downlevelIteration` and `tsc file.ts --lib es6 --downlevelIteration` produces correct output. Closing.
