### ISSUE TITLE
better support for multi module monorepos

### ISSUE THREAD

**Issue by valotas** [Microsoft/TypeScript#21180]
In a [simple monorepo scenario](https://github.com/boennemann/alle) with let's say 2 modules:

```
./packages/node_modules/module1
./packages/node_modules/module1/tsconfig.json
./packages/node_modules/module2
./packages/node_modules/module2/tsconfig.json
tsconfig.json
```

I would like to transparently use `tsc -p .` or more importantly `tsc -w` in one of the modules or the root of the monorepo. While I can make the tsconfig.json inherit from tsconfig, I can not work around the `outDir`. If I run tsc on the root of the the repo I can compile but the code will get emitted under the outDir the my root folder.

Is there a way to have the outDir dynamically computed? I believe this is more a suggestion since I did not find anything regarding this at the moment.

**Comment by RyanCavanaugh** [comment]
#3469 is tracking work related to this scenario
