### ISSUE TITLE
possibility to pipe output without creating temp files

### ISSUE THREAD

**Issue by koutsenko** [Microsoft/TypeScript#2118]
Now compiler writes the output to disk only.
How can I compile .ts in memory?
I searched and found no results.

Thanks.

**Comment by danquirk** [comment]
Are you looking for the compiler API to do this? https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API 

Or is there some other scenario you have in mind?

**Comment by DanielRosenwasser** [comment]
This is currently an issue tracked by #1226.

**Comment by DanielRosenwasser** [comment]
In addition to @danquirk's response, if you are looking to do intermediate processing, you can use our compiler API, or utilize something like [typescript-simple](https://github.com/teppeis/typescript-simple) which also uses our API.

**Comment by koutsenko** [comment]
It's just for build script written on pure node js script without any grunt, gulp and other trendy odd stuff.
TS->JS compilation result isn't the build process endpoint.
I want optimize result (Google Closure Compiler in advanced mode), then minify it.
So, transient disk writes slowing down the process a bit.

Seems I need to use compiler API and write customized [CompilerHost](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#a-simple-transform-function).
Thanks for the answers and sorry for any inconveniences.

**Comment by DanielRosenwasser** [comment]
In that case, you'd probably be able to get away with creating a default compiler host and overwriting the `writeFile` function. It actually shouldn't be terribly difficult.
