### ISSUE TITLE
TypeScript doesn't believe NodeJS.Process is not undefined

### ISSUE THREAD

**Issue by Zarel** [Microsoft/TypeScript#21183]
**TypeScript Version:**  2.7.0-dev.20180113 (also tested with 2.6.2)

**Code**

`ts-testcase1.ts`

```ts
function handleProcess(process: NodeJS.Process) {
	process.send("hi");
}
```

`tsconfig.json`

```json
{
  "compilerOptions": {
    "strict": true,
    "types": ["node"]
  }
}
```

**Expected behavior:**

No error

**Actual behavior:**

```
ts-testcase1.ts(2,2): error TS2722: Cannot invoke an object which is possibly 'undefined'.
```

The interesting thing is, this appears to be specific to `NodeJS.Process`. When I replace it with `NodeJS.WritableStream` (and `process.send` with `stream.write`), the error goes away entirely.

I thought maybe it's because `process` is a global? But renaming `process` doesn't fix the error.

**Comment by mhegazy** [comment]
process.send is declared in `@types/node` as optional. and thus its type can be `undefined`. if this is incorrect, then it is a bug in the declaration file.

**Comment by Zarel** [comment]
Oh! My bad.

**Comment by Zarel** [comment]
My confusion was that I didn't realize it was `process.send` and not `process` that was possibly undefined.

**Comment by luckyScript** [comment]
I try `(<any> process).send` to solve this problem.
