### ISSUE TITLE
Readonly has issues with intersection types

### ISSUE THREAD

**Issue by johnfn** [Microsoft/TypeScript#21184]
**TypeScript Version:**  2.6.2

**Code**

```ts
class Foo<T, U> {
    thing(): Readonly<T> {
        return undefined as T;
    }

    erroringThing(): Readonly<T & U> {
        return undefined as T & U; // Type 'T & U' is not assignable to type 'Readonly<T & U>'.
    }
}
```

**Expected behavior:**
Both of these are error free.

**Actual behavior:**

` Type 'T & U' is not assignable to type 'Readonly<T & U>'.`

**Comment by mhegazy** [comment]
Should be fixed by https://github.com/Microsoft/TypeScript/pull/19564. give typescript@next a try.
