### ISSUE TITLE
Impossible to exclude original declaration file from module

### ISSUE THREAD

**Issue by metsawyr** [Microsoft/TypeScript#21189]
**TypeScript Version:**  2.6.2
It is impossible to exclude or override d.ts files that are located in root of npm module.

For instance I have dependency on module named *mymodule*.
It contains declaration file in ./node_modules/mymodule/index.d.ts which is poorly made.
I have custom written declaration for it in ./@types/mymodule/index.d.ts
There're defined typeRoots in compilerOptions in ./tsconfig.json

```
{
    "compilerOptions: {
        "typeRoots": [
            "node_modules/@types",
            "@types"
        ]
    }
}
```

Than I added next rows (options above remained):
```
{
    "compilerOptions: {
        "typeRoots": [
            "!node_modules/mymodule",
            "!node_modules"
        ]
    },
    "exclude": {
        "node_modules/mymodule/index.d.ts"
    }
}
```

**Expected behavior:**
mymodule/index.d.ts getting ignored by compiler

**Actual behavior:**
mymodule/index.d.ts overrides my custom definitions

**Comment by andy-ms** [comment]
`typeRoots` won't do what you want -- that is used to determine the set of global definitions that will be included by default. But once that set is determined, we will use regular module resolution to look up where they are.
`exclude` also won't do what you want -- that affects the set of files that are compiled, but won't prevent them from being imported.
You can change the behavior of module resolution by using [path mapping](http://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping):
```json
"compilerOptions": {
    ...
    "baseUrl": ".",
    "paths": {
      "mod": ["node_modules/@types/mod/index.d.ts"]
    }
}
```

**Comment by metsawyr** [comment]
Works just fine. Thank you.
