### ISSUE TITLE
Simple non-nullability detection for closure variables

### ISSUE THREAD

**Issue by yahiko00** [Microsoft/TypeScript#21195]
**Code**

```ts
function foo() {
    let icon = document.getElementById("icon");
    if (!icon) return;
    // From here, the local variable icon is defined and not null
    icon.addEventListener("click", () => {
        let bar = icon.id; // error TS2531: icon is possibly null
    }, true);
}
```

**Expected behavior:**
In the code above, the local variable `icon` cannot be null after the `if` statement, unless I miss something. Although there is a closure in the `addEventListener` call, and this is an asynchronous function, I fail to see how and when such a variable `icon` could be null since there is no other reference to this variable until the end of the function `foo`. I am wondering how difficult it would be to check the non-nullability of closure variables in such a simple case. This would prevent some useless errors/warnings and would avoid the usage of the `!` operator.

**Actual behavior:**
The compiler emits an error TS2531: Object [icon] is possibly null

**Comment by mhegazy** [comment]
declare `icon` as `const` instead. see https://github.com/Microsoft/TypeScript/issues/21162.

**Comment by yahiko00** [comment]
Alright, for my use case, this workaround is enough. Although, I suspect one could need to declare some variables (`let`) in some specific cases.

**Comment by waynebloss** [comment]
How about if `icon` is an argument of the function, e.g. `foo(icon: HTMLElement): void` ?
