### ISSUE TITLE
Proposal: compiler flag to don't emit outside roots

### ISSUE THREAD

**Issue by mmv** [Microsoft/TypeScript#21191]
Context
=======

Consider the case of a *solution* consisting of multiple *projects*. These projects usually have references between eachother. Some of them may be typescript projects, but often there'll be mixed content (eg: typescript + ASP.NET).

A typescript file in ProjectB may require a module from ProjectA by doing `import {...} from "ProjectA/module";` for runtime, even though on compile time the imported module will actually be imported from `../../../ProjectA/src/js/module`. Path mappings make this possible by declaring a mapping `{"ProjectA/*": "../../../ProjectA/src/js/"}`.

Using path mappings works well both for compiling and for editor experience. But compiling ProjectB will make tsc discover and compile the files from ProjectA, which will confuse a build system. This happens because on a build system that's aware of dependencies, compiling the solution results in:

* build ProjectA
  * compile all resources
  * bundle them in a dll/war
* build ProjectB
  * compile all resources (will also cause ProjectA typescript files to emit JS files)
  * bundle them in a dll/war

Now an incremental build with no changes would cause ProjectA to be compiled/bundled again (because the JS files were written after assembling) and ProjectB to be compiled/bundled again because its dependencies changed. Essentially this ends up breaking incremental builds.

There's a possible workaround which is to have ProjectA producing a `.d.ts` file and have ProjectB to reference that instead of the original sources. However this workaround breaks editor experience causing operations such as *Go To Definition* to find the generated declaration file rather than the original source.

Proposed solution
=================

A simple solution for this would be a `noEmitOutsideRoot` flag that would cause the compiler not to emit files outside specified `rootDir`s. Files would still be considered for the type checking phase, but would produce no `.js` files (nor `.d.ts` files if emit declaration is requested).

With such a flag, solution compilation could now be done with this sequence:

* build ProjectA
  * compile all resources
  * bundle them in a dll/war
* build ProjectB (with `--noEmitOutsideRoot` and `--rootDir ProjectB`)
  * compile all resources (finds ProjectA files through paths mapping but doesn't emit them because they're outside the root)
  * bundle them in a dll/war
 
Because ProjectB compilation would not cause JS files to be emitted in ProjectA anymore, incremental builds with no changes would behave as expected (ie: figure out there's no work to do).

**Comment by mhegazy** [comment]
So why not use a .d.ts for the referenced project?

**Comment by mmv** [comment]
Just as I described, using a `.d.ts` is a possible workaround, but it breaks the editing experience.

It is possible to have something like `dts-generator` to produce a `.d.ts` with a proper module namespace, etc., and have the consumer project to reference the `d.ts` file. However this breaks editor experience. Things such as *Go to Definition* will take you to the generated `.d.ts` file rather than the target code you intended. Changing something in the producer project requires a compilation of that project so that the effect can be seen on the editor for the consumer. That's different from the nearly instant feedback you have when all sources belong to the same project (or different projects in the same solution for languages like C#). Refactoring capabilities supported by the typescript compiler also offer a broken user experience under this workaround.

The ideal solution for the problem would be to have something like C# where a consumer project references an assembly but the IDE is smart enough to have things such as *Go to Definition* and on-the-fly error checking to use the original source files.

This proposal doesn't target such an ideal solution because having the compiler to understand the producer sources but not emit them seemed like a good compromise between value and solution simplicity.

**Comment by mhegazy** [comment]
> Just as I described, using a .d.ts is a possible workaround, but it breaks the editing experience.

I think this is the issue. the .d.ts should be the correct solution, and we should make the editing experience better. https://github.com/Microsoft/TypeScript/issues/3469 tracks doing just that.

**Comment by mmv** [comment]
My understanding of #3469 and the way its discussion is heading is a bit different. A more complex concept of project references is introduced, some restrictions are required (eg: generating the `.d.ts` files). The solution seems to be based on proposals that predate the `paths` setting and new module resolution strategies, so they are kind of overlapping in functionality.

In the end the solution described there gets hyped due to the argument that using `.d.ts` files will be much cheaper than walking through the producer's project source. However for ensuring smooth editing experience (eg: *Go to Definition* and *Find all usages*) the language service would still need to parse the producer's source code, so there would be no actual speed/memory gain. Such gains would only happen in the compiler, but I don't see that alone justifying the added complexity.

In the end this solution to limit the emitter seems more simple. It also plays well with the existing `paths` mapping setting.

**Comment by mhegazy** [comment]
> In the end this solution to limit the emitter seems more simple. It also plays well with the existing paths mapping setting.

true. but ideally you do not want you tools to slurp in all the sources from all your projects. that does not scale in terms of memory/perf that well.. 
keep in mind that most of the time spent in the compiler or in the language service is related to checking types. and these are directly dependent on the complexity of the expressions in the file. that is where .d.ts files come in, they are much smaller, no expressions, and thus less types generated, and less work for the compiler to do. they give you, a logical unit that you do not have to go the sources beyond, which is ideal for this situation.

**Comment by mmv** [comment]
Alright, given that #3469 should include an extra mile for making sure editor experience isn't broken I'll be closing this in its favor.

But since it might be a while until that proposal solidifies and becomes available, I'm leaving here a reference for an implementation of noEmitOutsideRoots (outsystems/typescript@70c236efcd6dbc5395461e4fac5bdf86449dbdee) that can be used to circumvent the problem described.

**Comment by qwabra** [comment]
in my situation help use `"types": []`
https://github.com/Microsoft/TypeScript/issues/21562
