### ISSUE TITLE
export { MyType } from 'module' causes error

### ISSUE THREAD

**Issue by pmunin** [Microsoft/TypeScript#21194]
**TypeScript Version:**  2.6.2

**Code**

```ts
//module1.ts
export type MyModule1Type = {
   prop1:string;
}

//module2.exportAll.ts
export * from './module1.ts'   
       //works fine

//module2.exportSelectedTypes.ts
export {MyModule1Type as MyModule2Type} from './module1.ts'
       //Cannot re-export a type when the '--isolatedModules' flag is provided


//module2.exportSelectedTypes.UglyWorkaround.ts
import {MyModule1Type} from './module1.ts'
export type MyModule2Type=MyModule1Type
       //works fine

```

**Expected behavior:**
module2.exportSelectedTypes.ts compiles successfully, so we don't have to use ugly workaround

**Actual behavior:**
module2.exportSelectedTypes.ts causes compilation error:
_Cannot re-export a type when the '--isolatedModules' flag is provided_

**Comment by andy-ms** [comment]
We can't compile `export {MyModule1Type as MyModule2Type} from './module1.ts'` without knowing whether `MyModule1Type` is a type. If it is, we compile to nothing. If it isn't, we compile to `exports.MyModule1Type = module1_1.MyModule2Type;`.
The `--isolatedModules` flag is intended to prevent writing code that can't be transpiled without information about other modules, so it's working as intended in this case.
