### ISSUE TITLE
Partial<T> types not working as expected, when extending another interface

### ISSUE THREAD

**Issue by jamespacileo** [Microsoft/TypeScript#21196]
**TypeScript Version:**  2.7.0-insiders.20180108

**Code**

```ts
interface Vehicle{
    wheels: number;
}

class Driver<T extends Vehicle>{
    car: Partial<T>;
    constructor(){
        this.car = {wheels: 4} 
        // Type '{ wheels: 4; }' is not assignable to type 'Partial<T>'.
        // (property) Driver<T extends Vehicle>.car: Partial<T>
    }
}
```

**Comment by jcalz** [comment]
So, this is one of many duplicates of #13442, and I imagine that this will be closed.

Someone may break out an example like:

```ts
interface TractorTrailer extends Vehicle {
  wheels: 18;
  cargo: string;
}

const theBandit = new Driver<TractorTrailer>();
theBandit.car.wheels // 4 at runtime, 18 at compile time... oops
```

But while we're here, could someone explain why *this* doesn't work?

```ts
function explainPlease<T extends Vehicle>() {
  const err1: Partial<T> = null! as { wheels: T['wheels'] }; // error
  const err2: Partial<T> = { wheels: void 0 }; // error
}
```

If I inspect `Partial<T>` I see that it has a property `wheels` of type `T['wheels'] | undefined`, and all properties are optional, so I'd expect the above to compile without warning.   Am I missing something, or is it just that the compiler doesn't actually try to check whether something is assignable to `Partial<T>`?

**Comment by Pmyl** [comment]
@jcalz your first example is broken anyway event without generics, it doesn't seems pertinent to this potential issue, look at this example:
```typescript
interface Vehicle {
    wheels: number;
}

class TractorTrailer implements Vehicle {
    wheels: 1;
}

const vehicle: Vehicle = new TractorTrailer();
vehicle.wheels = 20; // 20 at runtime, 1 at compile time... oops
```


Looking at the "Partial" issue I can see that some examples seems completely safe, look at this and please tell me if I'm wrong:
```typescript
interface Entity {
    id: string;
}

function aFunction<TItem extends Entity>(): void {
    const partialItem: Partial<TItem> = { id: '0' };
    // Type { id: "0"; } is not assignable to type Partial<TItem>
}

function anotherFunction<TItem extends Entity>(item: TItem): void {
    const partialItem: Partial<TItem> = item; // this works correctly
    item.id = "new";
    partialItem.id = "new"; // this works correctly
}
```



I know that TItem extends Entity (pseudo code)
`TItem extends Entity => { id: string; ...: any; }`
 and with Partial everything becomes optional (pseudo code)
`Partial<TItem> => { id?: string; ...?: any; }`
 so the "id" property should be there and everything else can be omitted (like I did), why the compiler is telling me that it's not assignable?
