### ISSUE TITLE
Filter keyword completions based on context

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/TypeScript#21200]
When using vscode, there are times when suggestions are poorly suggested.

Example (Pipe is the cursor):

```ts
export class MyClass {

  public myMethod() {
    |
  }

}
```

When I am at that location, the words `constructor` , `public`, `private`, etc. shouldn't be suggested. With the change of how vscode selects the best word, when I type `con` it suggests `console`, `constructor`, and others. Due to habit I see `console` on top of the list and press enter, however `constructor` gets inserted because of vscode suggestion logic (this gets annoying).

I feel that the best way around this would be to remove items from the suggestions if they are not valid within that scope at the cursors location.

**Comment by mhegazy** [comment]
Currently all our keyword completions are one group. they are either added or not. and they are always added for completions not following a `.`.

**Comment by mhegazy** [comment]
PRs welcomed for filtering the keyword completions based on the location.

**Comment by Kingwl** [comment]
@mhegazy actual there are some filter for keyword completions   
```
const enum KeywordCompletionFilters {
        None,
        ClassElementKeywords,           // Keywords at class keyword
        ConstructorParameterKeywords,   // Keywords at constructor parameter
    }
```  
should we extend this enum? or refactor it

**Comment by mhegazy** [comment]
This now very limited. we only use it to get completions inside a class. we will need to make it exclusive first, i.e. do not show `public` outside a class context. and add aditional ones, e.g. `catch`/`finally`, should only show after a `try`. `break`/`continue` should only show within a loop/switch.. etc.. 

//cc @sheetalkamat for thoughts on best approach here.

**Comment by sheetalkamat** [comment]
@mhegazy  yes, the keywords are currently only filtered from class, constructor parameter locations.. Note that they still have duplicates eg. if you have already typed public for the property , you would still get public as an option.
```
class c {
 public /*completion here will still contain public */
}
```

I think filtering at current level is better than not having any and can be easily added. eg, at statement scope do not add property declaration modifiers in the keyword as the issue suggests and can easily be extended by adding members to ```KeywordCompletionFilters``` and adding appropriate filters in ```getKeywordCompletions```.

We could start with adding filters to remove modifiers inside the block and so on and carve out more filters in next stage as @mhegazy  states. (catch and finally only if try, or break and continue only inside loop)

**Comment by mhegazy** [comment]
thanks @Kingwl
