### ISSUE TITLE
TypeScript intellisense: Suggest to prepend "this." if I typed the name of a class member

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#21202]
_From @Duckers on January 16, 2018 11:47_

> Apologies if this is the wrong repo for Intellisense suggestions, if so, please redirect me.

- VSCode Version: 1.19.1
- OS Version: MacOS 10.13

A very common scenario when writing TypeScript (coming from C#) is that I forget to prepend `this.` when I want to reference a member of the current class. My muscle memory also relies a lot on the intellisense to complete the names of members. This very often results in the code completer completing an identifier with a very unlikely option from the global namespace, instead of simply prepending `this.` to refer to a local member.

Example:

```ts
import { Post } from 'Server/Boost/Post'

export default class PostComponent {
    Options = {} as Post.Post

    get hasImage() {
        return Opt<caret here, pressing enter>
    }
}
```

This ends up completing as `HTMLOptionElement` or something similar, when `this.Options` would have been a much more probable intention.

_Copied from original issue: Microsoft/vscode#41668_

**Comment by mjbvz** [comment]
Interesting idea. Perhaps we can leverage the new `insertText` property on completion items for this

**Comment by mhegazy** [comment]
seems like a nice addition to the `insertText` support we have already.

**Comment by mhegazy** [comment]
@Duckers  thanks for the suggestion. should be in tomorrow's `typescript@next` if you want to take if for a spin.

**Comment by Duckers** [comment]
Fantastic! Thanks a lot :D
