### ISSUE TITLE
Generic type constraint not giving an error on array

### ISSUE THREAD

**Issue by alfaproject** [Microsoft/TypeScript#21211]
I was speaking with a friend just now about a PR he did (https://github.com/RobinBuschmann/sequelize-typescript/pull/268), and I'm a bit confused with the generic type constraint allowing the following code. To me, it sounds like a bug, but prove me otherwise.

**TypeScript Version:**  Playground

**Code**

```ts
class Model<M> { }

function $get<R extends Model<R>>() {
    const results: Array<R> = [];
    return results.length === 1 ? results[0] : results;
}

const one = $get<string>();
const many = $get<string[]>(); // string[] extends Model<string[]>
```

**Expected behavior:**
Compile error on `const many`. How can an array of anything extend a class? I know an array is an object but doesn't quite explain it because this object is very specific and not even array-like.

**Actual behavior:**
The compiler is happy about it.

**Comment by phxvyper** [comment]
Try compiling using the latest version of TSC locally.

I tested the following code:

```typescript
class Model<M> {
    something() {
        console.log("");
    }
}

function $get<R extends Model<R>>() {
    const results: R[] = [];
    return results.length === 1 ? results[0] : results;
}

const one = $get<string>();
const many = $get<string[]>();
```

and got the following errors:

```
error TS2344: Type 'string' does not satisfy the constraint 'Model<string>'.
error TS2344: Type 'string[]' does not satisfy the constraint 'Model<string[]>'.
```.

This may be a bug with Playground itself, or intended behaviour since playground is less strict about what it converts. Ill have to test with Playground.

**Comment by phxvyper** [comment]
Tested it on Playground and I do indeed get the same expected errors.

**Comment by alfaproject** [comment]
Indeed, this seems to fail:
```ts
class Model<M> {
    foo = 'bar';
}

function $get<R extends Model<R>>() {
    const results: Array<R> = [];
    return results.length === 1 ? results[0] : results;
}

const one = $get<Model<string>>();
const many = $get<Model<string>[]>();
```

I wonder how that worked for my friend then... Maybe I'm not modeling Sequelize properly to have a better example. ):

**Comment by Gerrit0** [comment]
The reason the original code sample works fine is because Typescript uses structural typing, not nominal typing. [See the docs](https://www.typescriptlang.org/docs/handbook/type-compatibility.html). 

When model is defined:

```ts
class Model<M> { }
```

It has no requirements that the object must meet to be considered a `Model<M>`. Consider:

```ts
class Model<M> { }

let a: Model<number> = 1
let b: Model<string> = 1
let c: Model<string> = { a: 1}
```

Until the `Model` class actually has members, declaring something to be of type `Model` does not benefit you at all.
