### ISSUE TITLE
Suggestion: automatically infer class method param type

### ISSUE THREAD

**Issue by tommytroylin** [Microsoft/TypeScript#21223]
consider this code snippet
```typescript
interface SomeClassType {
   name: string;
}

interface Plugin {
    apply(target: SomeClassType): void;
}

class SomePlugin implements Plugin {
    apply(target) { // [ts] Parameter 'target' implicitly has an 'any' type.
    }
}

class SomeOtherPlugin implements Plugin { // [ts] Class 'SomeOtherPlugin' incorrectly implements interface 'Plugin'.
    apply(target: string) {
    }
}
```

so the compiler knows exactly what type should param `target` to be.
but it can't be inferred.

add a simple type to that param should be ok.
but in some cases that `SomeClassType` is not exported directly at all.

can ts compiler infer that type from interface restrictions automatically？

Use case:
I'm writing a system which supports loading plugins. 
I would like to export a single `Plugin` type to help plugin coders. 

But it feels bad that
* I must export all my basic types used in params
* plugin coders should manually explicitly type them one by one  in the correct order

**Comment by MarvinHannott** [comment]
Maybe it isn't all that great if everything is just inferred. Especially in cases like that it could lead to errors because the inferred type might not be what you think it should be. Maybe you mistakenly implemented the wrong interface, maybe you made a mistake in the ancestor interface and wouldn't notice at the time of implementing. Moreover, types serve self-documentation. If I need to know what ```SomePlugin``` looks like, I don't want to jump to ```Plugin``` first.
These two points are actually my biggest issues with Flow-Type from Facebook.

**Comment by mhegazy** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/1373. more discussion in https://github.com/Microsoft/TypeScript/pull/10610 and in https://github.com/Microsoft/TypeScript/issues/3667

**Comment by tommytroylin** [comment]
@MarvinHannott  Not everything.
since we have interfaces that restrict class implementations, in most cases it should be good.
I agree with your point of view that this kind of inference could lead to errors. But on the other hand, duplicated type declarations are annoying. It goes worse when you have to import / export all of them.

maybe a `inherit` type may solve elegantly

@mhegazy  Thank you for the links. I 'll check them.
I've searched some issues but find nothing ... 
maybe because I miss `contextual` keyword...

**Comment by mhegazy** [comment]
nah.. these ones are hard to find.. I know them cause i look at them often.
