### ISSUE TITLE
Index signature should support Symbol

### ISSUE THREAD

**Issue by k8w** [Microsoft/TypeScript#21226]
**TypeScript Version:**  2.6.2

**Code**

```ts
interface Test{
    [key: Symbol]: string;
}
```

**Expected behavior:**
Compile success

**Actual behavior:**
> [ts] An index signature parameter type must be 'string' or 'number'.

**Comment by k8w** [comment]
Also,  Should `Symbol.for` support function and class types? 
as:
```ts
class Test{}
let symbol = Symbol.for(Test);
```

**Comment by mhegazy** [comment]
Should be already covered by https://github.com/Microsoft/TypeScript/issues/1863
