### ISSUE TITLE
CFA doesn't discriminate in this edgecase.

### ISSUE THREAD

**Issue by rozzzly** [Microsoft/TypeScript#21222]
Consider the following:
```typescript
export interface RGB {
    r: number;
    g: number;
    b: number;
}

export type AnsiColor = (
    | {
        mode: '3-bit';
        value: number;
    }
    | {
        mode: '8-bit';
        value: number;
    }
    | {
        mode: '24-bit';
        value: RGB;
    }
);

export function areEqualAnsiColors(a: AnsiColor, b: AnsiColor): boolean {
    if (a.mode === '24-bit' || b.mode === '24-bit') {
	    // short cut for `a.mode !== '24-bit' || b.mode !== '24-bit'`
        if (a.mode !== b.mode) return false; 
        else return (
			// the following type assertions should not be needed
            (a.value as RGB).r === (b.value as RGB).r
            && (a.value as RGB).g === (b.value as RGB).g
            && (a.value as RGB).b === (b.value as RGB).b
        );
    } else {
        let aVal: number = a.value;
        let bVal: number = b.value;
        return false;
    }
}
```

Ideally, CFA would catch this. I got the code to work by using the long form though,

---

I encountered this with `v2.7.0-dev.20171230` and whatever the playground runs.

---

While writing this, I thought to test the following: 

```typescript
type Foo = (
    | {
        a: string;
        test(): false;
    }
    | {
        b: number;
        test(): true;
    }
);

let foo: Foo;
if (foo.test()) {
    console.log(foo.b); // error here. 
}
```
So it looks like CFA can't use the return type as a discriminate which is unfortunate. I could see this one being a lot more involved to support, but it'd be cool if the team could put it on their ~~todo list~~ _**backlog slog**_ 😉

**Comment by mhegazy** [comment]
Control flow analysis does not track relationship between variables in this way. it only narrows to the types that match the comparison on the discriminant property. in the first `if` statement, all types in the union would survive; although what you want is to persevere a relationship between `a` and `b`, that you then guard on later on. this is currently out of scope for what the control flow analyzer is doing.
