### ISSUE TITLE
typescirpt 2.6.2 compile bug

### ISSUE THREAD

**Issue by lightszero** [Microsoft/TypeScript#21227]
compile error:

 testfun(value: number | ArrayBuffer | Uint8Array) {
            if (typeof value === "number")
            {

            }
            else if (value instanceof ArrayBuffer) {
                console.log("a");
            }
            else if (value instanceof Uint8Array) {
                console.log("b");
            }

        }

**Comment by RyanCavanaugh** [comment]
This doesn't show an error in the Playground. Can you be more specific about exactly how to reproduce this, and what the error you see is?
