### ISSUE TITLE
Handle ShebangTrivia in classifier

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#21236]
Currently, in `classifyLeadingTriviaAndGetTokenStart` in `classifier.ts`, we do nothing on a `ShebangTrivia`. It would be nice to add a `ClassificationType` for that.

**Comment by andy-ms** [comment]
Shebang seems to be highlighted in visual studio, but in a fourslash test we don't seem to be returning any classification for it. Was a workaround added to Visual Studio? @paulvanbrenk 
(IIRC vscode uses typescript.tmLanguage instead of classifier.)

```ts
/// <reference path="fourslash.ts"/>

// @Filename: file1.tsx
////#!/usr/bin/env node
////0

const c = classification;
verify.syntacticClassificationsAre(
    // ...should have shebang here...
    c.numericLiteral("0"),
);
```

**Comment by paulvanbrenk** [comment]
Visual Studio also uses tmLanguage… so not sure what the expectation for the test is here.

**Comment by mhegazy** [comment]
Does not seem to warrant a change at the time being. closing.
