### ISSUE TITLE
Constraints which are generic mapped types should have a constraint of the same mapping over their generic's constraint

### ISSUE THREAD

**Issue by weswigham** [microsoft/TypeScript#21249]
**Code**

```ts
function f<
    T extends { member: string },
    TParam extends Readonly<T>
>(param: TParam, mutableSet: T): TParam {
    const x: string = param.member;
    return param;
}
```

**Expected behavior:**
Code works

**Actual behavior:**
Property `member` does not exist on type `TParam`.

When you call `f`, you _must_ pass a first (and second) argument which provide a member named `member` (this is enforced), so it's common sense that within `f` you should always have access to the field of `TParam` named `member`. It _seems_ like the issue today is that when calculating a generic's constraint, we don't consider a mapped type's generics' constraints when calculating its constraint.

**Comment by jakebailey** [comment]
Just looking at old bugs; this one was fixed all the way back in https://github.com/microsoft/TypeScript/commit/eeabd527ca0f4e00deb16bb3ca0fee1fb57b1d08 as part of #26698.
