### ISSUE TITLE
Review `replaceNode`

### ISSUE THREAD

**Issue by andy-ms** [microsoft/TypeScript#21246]
This function should be checked that it properly handles leading and trailing trivia of the node.
We should probably use `replaceNode` instead of `replaceRange` in `fixUnusedIdentifier.ts`. See https://github.com/Microsoft/TypeScript/pull/21144#discussion_r161097891

**Comment by amcasey** [comment]
`extractSymbol.ts` also make heavy use of `replaceRange`.

**Comment by RyanCavanaugh** [comment]
Looks like we got them all
