### ISSUE TITLE
Missing SourceBuffer.textTrack in lib.dom.d.ts

### ISSUE THREAD

**Issue by jon-valliere** [Microsoft/TypeScript#21256]
Using TypeScript Version 2.6.1
Using Visual Studio Code Version 1.19.2 for MacOS

SourceBuffer has a property called textTrack which returns TextTrackList.  TextTrackList is properly defined and is referenced in MediaSource, but is missing from SourceBuffer. 

See https://developer.mozilla.org/en-US/docs/Web/API/SourceBuffer/textTracks

Therefore, textTrack needs to be added to the signature as follows.

```
interface SourceBuffer extends EventTarget {
    appendWindowEnd: number;
    appendWindowStart: number;
    readonly audioTracks: AudioTrackList;
    readonly buffered: TimeRanges;
    mode: AppendMode;
    timestampOffset: number;
    readonly updating: boolean;
    readonly videoTracks: VideoTrackList;
    readonly textTracks: TextTrackList;
    abort(): void;
    appendBuffer(data: ArrayBuffer | ArrayBufferView): void;
    appendStream(stream: MSStream, maxSize?: number): void;
    remove(start: number, end: number): void;
}
```

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by jon-valliere** [comment]
Pull Request https://github.com/Microsoft/TypeScript/pull/21314

**Comment by jon-valliere** [comment]
@mhegazy This: https://github.com/Microsoft/TSJS-lib-generator says that the input XML is generated by Microsoft Edge.  Therefore, how do we get a missing element added? 'textTracks' has been in IE since 11 and Chrome since 23 and appears in the initial definition of Media Source Extensions.

**Comment by mhegazy** [comment]
U should edit the json files instead. See https://github.com/Microsoft/TSJS-lib-generator/pull/345 for a reference
