### ISSUE TITLE
Don't publish lock files and mailmap to NPM

### ISSUE THREAD

**Issue by willnode** [Microsoft/TypeScript#21252]
**TypeScript Version:**  any

**Code**

N/A

**Expected behavior:** No `package-lock.json` and `yarn.lock` in my node_modules

**Actual behavior:** Yes, it is.

**Related:** 

`package-lock.json` and `yarn.lock` are included in npm package. It should not be included according to [here](https://docs.npmjs.com/files/package-lock.json) and [here](https://stackoverflow.com/questions/44546718/should-package-lock-json-also-be-published).

Also, I don't see the purpose of `.mailmap` also being published to npm.

**Comment by mhegazy** [comment]
thanks @HerringtonDarkholme!

**Comment by gcnew** [comment]
What about the suggestion to exclude `.mailmap` as well?

**Comment by mhegazy** [comment]
sure. a PR would be appreciated.
