### ISSUE TITLE
Misleading English message for error TS1046

### ISSUE THREAD

**Issue by dtgriscom** [microsoft/TypeScript#21251]
**TypeScript Version:**  2.0.10 (checked; message is the same on master branch)

**Code**

The following test.d.ts file:

    module test {
        export const test: number;
    }

when compiled, yields the following error message:

```error TS1046: A 'declare' modifier is required for a top level declaration in a .d.ts file.```

This is both misleading and just wrong, as the following test.d.ts file is legal:

    export const test: number;

**Expected behavior:**

The error message should not be misleading.

**Actual behavior:**

The error message is misleading. This led me on a wild goose chase trying to get my .d.ts file to compile, all the time using the apparently required `declare` statement, when the solution didn't have `declare` at all.

**Related:**

**Comment by lexcorp16** [comment]
Hi @DanielRosenwasser I would like to take a crack at this. This is my first attempt at contributing to open source and I will be glad if you could point me in the right directions

**Comment by mhegazy** [comment]
First we need a new message text proposal. 

For the change itself, all messages are stored in https://github.com/Microsoft/TypeScript/blob/master/src/compiler/diagnosticMessages.json, you will need to change it and change the reference site to it in https://raw.githubusercontent.com/Microsoft/TypeScript/master/src/compiler/checker.ts (search for `Diagnostics.A_declare_modifier_is_required_for_a_top_level_declaration_in_a_d_ts_file`).

**Comment by lexcorp16** [comment]
Thanks for getting back to me on this. Can I ask what the fix was for the issue you were having? I think that would make a suitable error message more apparent.

**Comment by DanielRosenwasser** [comment]
I think the fix is to provide an error message like

```
A top-level declaration must start with either a 'declare' or 'export' modifier in a .d.ts file.
```

**Comment by ely-alamillo** [comment]
@DanielRosenwasser  the fix for this would be to change [this](https://github.com/Microsoft/TypeScript/blob/master/src/compiler/diagnosticMessages.json#L142) to `op-level declarations in .d.ts files must start with either a 'declare' or 'export' modifier.` and then change the ref [here](https://raw.githubusercontent.com/Microsoft/TypeScript/master/src/compiler/checker.ts) to `Top-level_declarations_in_d_ts_files_must_start_with_either_a_declare_or_export_modifier` ?

**Comment by DanielRosenwasser** [comment]
Yes, after running `jake generate-diagnostics` (or `gulp generate-diagnostics`) that should work @ely-alamillo.

**Comment by nic-hartley** [comment]
Doesn't look like this is being put in; does anyone mind if I do? (@lexcorp16 @ely-alamillo @DanielRosenwasser especially, since y'all either claimed it or found the fix)

**Comment by ely-alamillo** [comment]
@nic-hartley I'm taking a shot at it over the weekend for hacktoberfest. If I don't have anything by 10/10 I would't mind you taking over it.

**Comment by nic-hartley** [comment]
@ely-alamillo Darn, there goes my plan for Hacktoberfest :)

But alright! Thanks for letting me know.

**Comment by ely-alamillo** [comment]
@DanielRosenwasser do these changes require for test to be adjusted ?

**Comment by ely-alamillo** [comment]
@DanielRosenwasser would you mind pointing me in the right direction as to why the build is failing.

**Comment by nayeemrmn** [comment]
@DanielRosenwasser This is fixed.
