### ISSUE TITLE
Update Interface Object (Javascript)

### ISSUE THREAD

**Issue by cwberick** [Microsoft/TypeScript#21263]
**Actual behavior:**
![bug-entries](https://user-images.githubusercontent.com/5774595/35093638-107f0e5c-fc2a-11e7-822d-7e71d3b7aff7.png)

**Related Issues:**
Update interface for Object (Javascript)

entries and values

**Comment by msokk** [comment]
`Object.entries` and `Object.values` are ES2017 features, which are not included in the default library files. You need to add `ES2017.object` under `lib` parameter in your typescript compiler options. https://www.typescriptlang.org/docs/handbook/compiler-options.html

**Comment by cwberick** [comment]
thanks....
