### ISSUE TITLE
WebSocket.send() has invalid parameter types

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/TypeScript#21266]
The `.d.ts` file shows the following for `WebSocket.send()`:

```ts
WebSocket.send(data: any) 
```

However, according to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket#send()) it should look something like this:

```ts
WebSocket.send(data: USVString | ArrayBuffer | Blob | ArrayBufferView)
```

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.
