### ISSUE TITLE
Review callers of getNewLineOrDefaultFromHost that don't pass format settings

### ISSUE THREAD

**Issue by amcasey** [microsoft/TypeScript#21289]
The parameter is optional to avoid breaking consumers, but internal callers should probably always pass format settings.

**Comment by weswigham** [comment]
The two major callers are in `services` - where `getNewLineOrDefaultFromHost` is used to implement `getNewLine` in the `CompilerHost` used to typecheck (no formatting options available AFAIK), and in `getDocCommentTemplateAtPosition` - the second one could probably use a formatting options passthru, but is a public `LanguageService` API defined to not take one (a public API we have zero test coverage or internal uses for btw). Audit complete, everything is probably fine as-is.
