### ISSUE TITLE
server/project: External files should be added to project root files map

### ISSUE THREAD

**Issue by kyliau** [microsoft/TypeScript#21280]
While testing the Angular language service using the plugin architecture, we encountered an issue where semantic errors are not shown on external Angular templates.

Adding the external files to the project `rootFilesMap` solved this issue. The proposed fix is [here](https://github.com/kyliau/TypeScript/pull/3).
Could you please comment whether this is the right approach?

Related issue: https://github.com/Microsoft/TypeScript/issues/20321

**Comment by mhegazy** [comment]
@RyanCavanaugh can you help @kyliau out on this issue

**Comment by RyanCavanaugh** [comment]
Not sure what this is and it seems like this must be resolved by now
