### ISSUE TITLE
Not inference type of subclass method's argument when --noimplicitAny.

### ISSUE THREAD

**Issue by GongT** [Microsoft/TypeScript#21293]
**TypeScript Version:**  2.7.0-dev.20180118

**Search Terms:** type inference, noimplicitAny

**Code**
```ts
interface ITest { a: number; }
abstract class Base {
	protected abstract handle(foo: ITest): void;
}
class Child extends Base {
	handle(bar) { }
}
```

**Expected behavior:**
argument `bar` will have infered type `ITest`

**Actual behavior:**
error TS7006: Parameter 'bar' implicitly has an 'any' type.

**Playground Link:** [Link](https://www.typescriptlang.org/play/#src=interface%20ITest%20%7B%0D%0A%09a%3A%20number%3B%0D%0A%7D%0D%0Ainterface%20ISuperTest%20extends%20ITest%7B%0D%0A%09b%3Astring%3B%0D%0A%7D%0D%0Aabstract%20class%20Base%20%7B%0D%0A%09protected%20abstract%20handle(foo%3A%20ITest)%3A%20void%3B%0D%0A%7D%0D%0Aclass%20Child%20extends%20Base%20%7B%0D%0A%09handle(bar%2F*%3AISuperTest*%2F)%20%7B%0D%0A%09%7D%0D%0A%7D)

----

I know the `bar` can have any type implements `ITest`, but the strange thing is:    
When I remove --noimplicitAny, tsserver will tell me `bar` has a `a` property. But with --noimplicitAny, tsserver can not tell me any thing but an error.

If bar can not have any other type do not implements `ITest`, why not infer `bar` as `ITest`?

**Comment by AngryPowman** [comment]
It's very helpful to me

**Comment by andy-ms** [comment]
> When I remove --noimplicitAny, tsserver will tell me bar has a a property.

Are you sure? When I tried this without `--noImplicitAny` it's just `any`, and there are no completions at all.

**Comment by RyanCavanaugh** [comment]
Duplicate #1373

**Comment by GongT** [comment]
@andy-ms 

OK, I found that WebStorm's auto completion are proveided by it's own "JavaScriptLanguage", not tsserver by typescript package.

When I use plain tsserver, bar is just `any`. no completions.
