### ISSUE TITLE
IntelliSense not recognizing prototype functions

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#21296]
_From @iArePJ on January 16, 2018 1:52_

- VSCode Version: 1.19.2
- OS Version: Windows 10

Steps to Reproduce:

1. Create a variable that is a function.
2. Try to call functions of that variable.
3. IntelliSense doesn't recognize parameters of function.

```Javascript
var Gameplay = function() {
}

Gameplay.prototype.test = function(param1,param2) {
}

var GAME = new Gameplay();
GAME.test(<the parameters are not recognized by VSCode>);
```

Does this issue occur when all extensions are disabled?: Yes

_Copied from original issue: Microsoft/vscode#41648_

**Comment by andy-ms** [comment]
This seems to be working in `typescript@next` in a JavaScript project -- I can get a completion for `test` and then get signature help with the parameter names.
It will *not* work in a TypeScript project -- you must use a class in TypeScript code.
