### ISSUE TITLE
Allow not clearing the console on recompiles in --pretty --watch mode

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Microsoft/TypeScript#21295]
Repeating @ogvolkov's comment:

> Is it possible to still have the old behavior behind the flag?
> We are using TypeScript as a part of the gulp file which also contains other tasks (e.g. minify, watch for style changes etc.), and clearing the screen on recompile eventually erases the history of other tasks completely.

**Comment by mhegazy** [comment]
I do not think we want to keep adding new flags.

**Comment by bdowning** [comment]
At least on linux with xterm the \x1Bc sequence used by this feature to clear the screen also rings the terminal bell, which gets quite maddening in short order.  I can also see how the clearing behavior would be frustrating when used in a non-interactive manner.  I would also appreciate a way for this to go away.

**Comment by roblav96** [comment]
@clarkdave You are my hero!!!

**Comment by esprehn** [comment]
We have the same problem. We have a monorepo and lots of tooling that runs 5+ instances of tsc concurrently for various projects. The new behavior breaks all our tools and gsed doesn't come with OS X. Can we get this behavior behind a flag?

**Comment by demisx** [comment]
Same problem here. We don't need tsc to have the screen cleared for us. We need consistent linear output as was before. Please make this configurable.

**Comment by TimonVS** [comment]
@clarkdave the command doesn't work on macOS. MacOS comes with sed but it unfortunately doesn't support the `-u` (unbuffered) flag, which makes it impossible to fix this issue. I really think that a fix for this issue should be included in TypeScript itself to make TS suitable for monorepos.

**Comment by demisx** [comment]
@TimonVS Works fine for me. Just install `gnu-sed` via `brew`.

**Comment by TimonVS** [comment]
@demisx Thanks, I was aware of that :). But that means that I have to force my whole team to install this on their computers. I'm lucky that all my co-workers use macOS (so everyone has the same setup), but I'd still argue that this should be solved by TypeScript itself.

**Comment by demisx** [comment]
@TimonVS Oh, yeah. No doubt! The `gnu-sed` is hopefully a temporary workaround that we can get rid of soon.

**Comment by JoshuaKGoldberg** [comment]
@TimonVS @demisx @clarkdave @roblav96 if it helps, I just published an NPM package `tsc-fancy` you can use as a drop-in replacement for `tsc` that includes a `--preserveConsoleOutput` flag. I've verified it works on Windows and it should on Linux/Mac too - would appreciate verification!

https://www.npmjs.com/package/tsc-fancy

Otherwise, I'm closing this issue since the TS team is against adding the flag in, and there are two workarounds (`sed` shenanigans and `tsc-fancy`).

**Comment by esprehn** [comment]
Can we reopen this or revert the watch change? Having to use tsc-fancy to hack around tsc's defaults being hostile to scripts isn't good.

**Comment by ogheorghies** [comment]
A portable workaround for scripts is: `tsc --watch | awk '{gsub(/\033c/,"") system("")}1`

To customize the actions to be taken when compilation succeeds or fails, such as clear or don't clear screen, say something, record metrics, you can use:

https://www.npmjs.com/package/tsc-do

**Comment by roblav96** [comment]
@mhegazy Multiple devs creating _hacky_ implementations of a simple compiler option. Don't you think it should just be added?

**Comment by evanjmg** [comment]
We need an option to prevent clearing. Who's idea was it to clear old logs?

**Comment by Tyriar** [comment]
I maintain the terminal in VS Code and I don't think it should clear either. This actually caused an issue in our tasks feature which I had to act on because it's not typical of a build tool and because of how the terminal works under Windows (redraws the screen more often than on Linux/macOS) https://github.com/Microsoft/vscode/issues/44192

There's a reason build tools don't normally touch the rest of the screen outside of rewriting the current line; preserving history, working better with tall terminals, helping users noticing when things change, etc. The change should be be reverted imo.

**Comment by mhegazy** [comment]
`--preserveWatchOutput` should address the issue. it should be available in `typescript@next` as of tonight.

**Comment by fbartho** [comment]
Is there any hope of getting this fixed in 2.7.3? I see it was added to 2.8 which has no due date and is only 35% done :(

**Comment by mhegazy** [comment]
2.8 RC should be out in 2 weeks. and 2.8.1 should be out in 4 weeks.

**Comment by hoegge** [comment]
This implementation is a mistake. `tsc --watch` should not clear the console by default. You could add an option that does enable clearing instead. Now people have to modify a lot of code, scripts and tools to add the `--preserveWatchOutput` option because of this useless breaking change. E.g. read the feedback from @Tyriar
