### ISSUE TITLE
Suggestion: Add a flag to forbid use of global symbols

### ISSUE THREAD

**Issue by shivanshu3** [Microsoft/TypeScript#21318]
The following code compiles in TypeScript but running the compiled output under Node.js results in an error:

```
> node foo.js
> ReferenceError: Person is not defined
```

Contents of foo.ts:

    let a: Person = new Person();

Contents of bar.ts:

    class Person {}

Contents of tsconfig.json:

```json
{
	"compilerOptions": {
		"target": "es5",
		"module": "commonjs",
		"strict": true
	}
}
```

My understanding is that since `bar.ts` doesn't have any imports or exports, it is not a module, so the `Person` class becomes global. This behavior makes sense in a browser, but not in a Node.js application. There should be a compiler flag which forbids this behavior and produces a `Cannot find name 'Person'` error.

**Comment by mhegazy** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/18232

**Comment by shivanshu3** [comment]
Thank you very much for finding this issue @mhegazy !
