### ISSUE TITLE
Importance of fixing indentation when lines start with semicolons

### ISSUE THREAD

**Issue by rightaway** [Microsoft/TypeScript#21322]
Issues like https://github.com/Microsoft/TypeScript/issues/10392 have been created many times and closed saying it's working as intended and that a workaround is to put the semicolon on the previous line, but this is leading to a terrible developer experience. Here's a trivial example

```js
const a = 1
;[1, 2].someFunction()
```

In this case, the second line can be cut and pasted anywhere standalone. But in the workaround that the maintainers are suggesting

```js
const a = 1;
[1, 2].someFunction()
```

If you move the second line, you need to remember to delete the semicolon in front of the old preceding line and add it to the new preceding line, which is 2 extra steps every time you change the line. Same happens if you add a line before it or delete the line before it.

Also the git diff will be messier and more verbose because multiple lines are touched when it could have been just one. 

This issue keeps getting closed as `Working as intended`, but the intention isn't right and it isn't working well. There are clearly many advantages of allowing this as an option, and it's been requested so many times that developers clearly find it important.

**Comment by aluanhaddad** [comment]
If you want to be resilient against copy and paste scenarios, which incidentally are morally equivalent to the concatenation techniques used by older build tools, you should not rely on ASI.

**Comment by rightaway** [comment]
In cases where a semicolon is necessary the developers requesting this feature of course know to include it manually. We're asking about allowing it to be inserted at the beginning of the offending line than at the end of the previous line, because of the many advantages of this approach as I described above.

**Comment by RyanCavanaugh** [comment]
We don't accept meta-bugs on how other bugs are triaged or prioritizations. Please leave comments on the original bugs.
