### ISSUE TITLE
Don't provide completions after `=` in JSX

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#21341]
**TypeScript Version:**  2.7.0-dev.20180122

**Code**

```ts
<div foo=
```

**Expected behavior:**

No completions. This is not a valid location for an identifier, only a string literal, jsx expression, or `{}`.

**Actual behavior:**

Get global completions.

**Comment by jwbay** [comment]
It would be awesome if completions worked here, but it wrapped the identifier in curlies for you when it inserts:
```tsx
<div foo=/* request completions, select a local onClick function and you get */
<div foo={onClick}
```

Just a thought 🤷‍♂️
