### ISSUE TITLE
Missig document.onvisibilitychange event handler

### ISSUE THREAD

**Issue by YuichiNukiyama** [Microsoft/TypeScript#21353]
**TypeScript Version:**  2.7.0

**Search Terms:** 
- onvisibilitychange
- visibilitychange

**Description**
onvisibilitychange event handler has already [recommended](https://www.w3.org/TR/page-visibility/#extensions-to-the-document-interface) and supported [IE](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API#Browser_compatibility) (see also https://github.com/Microsoft/TSJS-lib-generator/blob/master/inputfiles/browser.webidl.xml#L3331). But, TS don't support onvisibilitychange event handler.

**Expected behavior:**
Support document.onvisibilitychange event hundler

**Actual behavior:**
TS don't support visibility event.

**Comment by DCtheTall** [comment]
If no one else is currently taking this, I would like to give it a shot.

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.
