### ISSUE TITLE
How to convert react-native to Typescript? 

### ISSUE THREAD

**Issue by miskeen110** [Microsoft/TypeScript#21356]
The code which i want to convert is attached in the Link: The code is for the Slider API. Which will help me and millions of coming users which will use React-native for web (Typescript). Actually i am pretty new to react-native for web so i dont know much about react-native. Trying to code my app into React Native for web(Typescript)
[https://codepen.io/necolas/pen/WxkYpv/](url)

**Comment by andy-ms** [comment]
This isn't a help forum. TypeScript [supports](https://www.typescriptlang.org/docs/handbook/jsx.html) JSX syntax, and there exists `@types/react-native` to help you use that library. Past that you'll have to look at a react-native tutorial.
