### ISSUE TITLE
Generic type inference for <TClass, TInstance> not working

### ISSUE THREAD

**Issue by pmunin** [Microsoft/TypeScript#21365]
**Code**

```ts
class MyClass {
    myInstanceProp:number;
    static myClassProp:string;
}

//The following simple type inference works fine:

export function createClassInstance<TInstance>(_class: (new (...args) => TInstance), ...args: any[]): TInstance
{
    //return ...;
}

let instance1 = createClassInstance(MyClass);
let myProp = instance1.myInstanceProp;  //works fine and intellisense works


//Here is when the problem happens:

interface IClass<TClass, TInstance>
{
    myClass:TClass
    createInstance(...args):TInstance
}

export function getClass<TInstance, TClass extends new (...args) => TInstance>
    (componentClass: TClass):IClass<TClass, TInstance>
{
    ///return ...;
}


let classDescriptor = getClass(MyClass);
let staticProp = classDescriptor.myClass.myClassProp; //works fine and intellisense works
let instance2 = classDescriptor.createInstance();
let myProp2 = instance2.myInstanceProp; //error TS2339: Property 'myInstanceProp' does not exist on type '{}'


```

**Expected behavior:**
compiles successfully

**Actual behavior:**
Compilation error: **error TS2339: Property 'myInstanceProp' does not exist on type '{}'**

**Playground Link:**  
[Playground demo](https://www.typescriptlang.org/play/#src=class%20MyClass%20%7B%0D%0A%20%20%20%20myInstanceProp%3Anumber%3B%0D%0A%20%20%20%20static%20myClassProp%3Astring%3B%0D%0A%7D%0D%0A%0D%0Aexport%20function%20createClassInstance%3CTInstance%3E(_class%3A%20(new%20(...args)%20%3D%3E%20TInstance)%2C%20...args%3A%20any%5B%5D)%3A%20TInstance%0D%0A%7B%0D%0A%20%20%20%20return%20undefined%3B%0D%0A%7D%0D%0A%0D%0Alet%20instance1%20%3D%20createClassInstance(MyClass)%3B%0D%0Alet%20myProp%20%3D%20instance1.myInstanceProp%3B%20%20%2F%2Fworks%20fine%20and%20intellisense%20works%0D%0A%0D%0A%0D%0A%2F%2FHere%20is%20when%20the%20problem%20happens%3A%0D%0A%0D%0Ainterface%20IClass%3CTClass%2C%20TInstance%3E%0D%0A%7B%0D%0A%20%20%20%20myClass%3ATClass%0D%0A%20%20%20%20createInstance(...args)%3ATInstance%0D%0A%7D%0D%0A%0D%0Aexport%20function%20getClass%3CTInstance%2C%20TClass%20extends%20new%20(...args)%20%3D%3E%20TInstance%3E%0D%0A%20%20%20%20(componentClass%3A%20TClass)%3AIClass%3CTClass%2C%20TInstance%3E%0D%0A%7B%0D%0A%20%20%20%20return%20undefined%3B%0D%0A%7D%0D%0A%0D%0A%0D%0Alet%20classDescriptor%20%3D%20getClass(MyClass)%3B%0D%0Alet%20staticProp%20%3D%20classDescriptor.myClass.myClassProp%3B%20%2F%2Fworks%20fine%20and%20intellisense%20works%0D%0Alet%20instance2%20%3D%20classDescriptor.createInstance()%3B%0D%0Alet%20myProp2%20%3D%20instance2.myInstanceProp%3B%20%2F%2Ferror%20TS2339%3A%20Property%20'myInstanceProp'%20does%20not%20exist%20on%20type%20'%7B%7D'%0D%0A)

**Comment by andy-ms** [comment]
It looks like the problem is basically:
```ts
declare function f<Res, F extends (...args: any[]) => Res>(f: F): Res;
const x = f(() => 0); // x: {}, wanted x: number
```

**Comment by ahejlsberg** [comment]
This is working as intended. We only make inferences for type parameters that occur in the parameter list, and `Res` doesn't. In particular, constraints are not inference positions. Because we make no inferences for `Res` we end up with `{}`.

It works if you use an intersection type for the argument:

```ts
declare function f<Res, F extends (...args: any[]) => Res>(f: F & (...args: any[]) => Res)): Res;
```

Similar for the original example:

```ts
export function getClass<TInstance, TClass extends new (...args) => TInstance>
    (componentClass: TClass & (new (...args) => TInstance)): IClass<TClass, TInstance>
```

**Comment by pmunin** [comment]
@ahejlsberg it's confusing, but your workaround actually works, thank you! Hopefully one day typescript will get rid off this limitation.
