### ISSUE TITLE
Suggestion: Class friendships

### ISSUE THREAD

**Issue by markvandenbrink** [Microsoft/TypeScript#2136]
Are there any plans to incorporate the [friend](http://en.wikipedia.org/wiki/Friend_class) keyword in TypeScript to allow class friendships and improve class encapsulation? I know (real) mixins and abstract classes are on the roadmap for 2.0. But friend classes would be practical as well...

A friend class should have access to the `private` and `protected` members of the class in which it is declared as a friend. For example:

```typescript
class A friend B {
    private Message: string = "hello";
}

class B {
    private Message: string = "there";
    
    public Greeter(a: A): string {
        return a.Message + " " + this.Message;
    }
}
```

**Comment by danquirk** [comment]
We haven't heard many other requests for this. We only recently added ```protected``` and there've been a fair number of asks for something like C#'s ```internal``` both of which are a lot more common in usage than ```friend```. I wouldn't say we're likely to add this, certainly not in the near term unless there're some very compelling use cases that mesh with existing popular libraries.

**Comment by mhegazy** [comment]
marking as revisit. as @danquirk mentioned, https://github.com/Microsoft/TypeScript/issues/5228 is a better alternative here.
