### ISSUE TITLE
Quickinfo for contextually typed arrow function parameter can be incorrect

### ISSUE THREAD

**Issue by weswigham** [Microsoft/TypeScript#21382]
**TypeScript Version:**  2.7.0-dev.201xxxxx

**Search Terms:** 

**Code**

```ts
interface BaseProps<T> {
  initialValues: T;
  nextValues: (cur: T) => T;
}
declare class Component<P> { constructor(props: P); props: P; }
declare class GenericComponent<Props = {}, Values = object>
    extends Component<Props & BaseProps<Values>> {
  iv: Values;
}

new GenericComponent({ initialValues: 12, nextValues: val => 12 });
```

**Expected behavior:**
Hover over `val` - see `number`. (Also: type `val.` in the lambda body and trigger completions, get completions for numbers). Hover over `nextValues`, see `(val: number) => number`.

**Actual behavior:**
`val`'s quick info is `any` (compilation and errors show it is assigned the correct type during compilation, the quick info on `GenericComponent` is thankfully correct), has no completions (being `any`), and `nextValues` has a quickinfo type of `(cur: number) => number & (val: number) => number`, which is an intersection of two conspicuously identical signatures.

[**Playground Link**](http://www.typescriptlang.org/play/#src=interface%20BaseProps%3CT%3E%20%7B%0D%0A%20%20initialValues%3A%20T%3B%0D%0A%20%20nextValues%3A%20(cur%3A%20T)%20%3D%3E%20T%3B%0D%0A%7D%0D%0Adeclare%20class%20Component%3CP%3E%20%7B%20constructor(props%3A%20P)%3B%20props%3A%20P%3B%20%7D%0D%0Adeclare%20class%20GenericComponent%3CProps%20%3D%20%7B%7D%2C%20Values%20%3D%20object%3E%0D%0A%20%20%20%20extends%20Component%3CProps%20%26%20BaseProps%3CValues%3E%3E%20%7B%0D%0A%20%20iv%3A%20Values%3B%0D%0A%7D%0D%0A%0D%0Anew%20GenericComponent(%7B%20initialValues%3A%2012%2C%20nextValues%3A%20val%20%3D%3E%2012%20%7D)%3B%0D%0A) (Also, [here's a fourslash test](https://gist.github.com/weswigham/76716e64ccf18957da5842ffb5067dab) to start anyone working on this off)

Preliminary investigation (read: believing this bug was related to JSX before trying the same construct outside a JSX tag) led me to believe this has something to do with execution order, as inference statefully assigns types to symbols via `assignTypeToParameterAndFixTypeParameters`, meaning if inference happens it assigns a type to the symbol, whereas if that hasn't happened and there's no cached type from an inference triggered by a `check` call, quickinfo only finds the contextual type for the position. _However_ requesting errors (which does a full typecheck) prior to checking quickinfo doesn't hide the error (which would be expected if the issue depended on execution order), so I'm unsure what the underlying problem is. The correct types are returned at these positions for our `.types` baselines by `getTypeAtLocation`, which, in these cases, is just a roundabout way to say `getTypeOfSymbol` on the node's symbol, which is the same as `getTypeOfSymbolAtLocation` in these locations (which is what's used in services).

**Comment by sandersn** [comment]
Doesn’t sound like there is any order-dependent behaviour here (if I read your description right), so I guess it makes sense that the implementation wouldn’t have an order-dependent bug.

**Comment by weswigham** [comment]
Well, differing results between .types baselines and quickinfo can be caused by order dependence, but I don't think it's the case here, since guaranteeing a full typechecked before fetching quickinfo doesn't suppress the issue.
