### ISSUE TITLE
HTMLObjectElement has alt attribute only in Internet Explorer (and edge?)

### ISSUE THREAD

**Issue by HolgerJeromin** [Microsoft/TypeScript#21386]
**TypeScript Version:**  2.6.3

lib.dom.d.ts has alt attribute for HTMLObjectElement:
https://github.com/Microsoft/TypeScript/blob/5b5a00745997768fad7d3a4c98931af179fa277a/lib/lib.dom.d.ts#L5981-L5986

This is not in [HTML Standard](https://html.spec.whatwg.org/multipage/iframe-embed-object.html#the-object-element), Firefox or Chrome available.

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by benbraou** [comment]
@mhegazy I would like to work on this issue
