### ISSUE TITLE
Support nested type parameters

### ISSUE THREAD

**Issue by jameslong** [Microsoft/TypeScript#214]
E.g. you cannot have an interface and function which satisfy the types:

    interface InterfaceA<U>
    function<U extends InterfaceA<V>>(value: U): U 

This means you cannot make generic functions to handle derived types unless you are willing to lose the type information for the return value.

**Comment by Pajn** [comment]
>did you mean something like that?

I would expect so, this is something I would want too.
See https://j201.github.io/posts/2014-08-30-TypeScript-The-Bad-Parts.html#higher-kinded-types

**Comment by mhegazy** [comment]
Fixed by https://github.com/Microsoft/TypeScript/pull/5949
