### ISSUE TITLE
Use insertText to add string literal completions

### ISSUE THREAD

**Issue by andy-ms** [microsoft/TypeScript#21408]
**TypeScript Version:**  2.8.0-dev.20180125

**Code**

```ts
const x: "a" | "b" = /**/
```

**Expected behavior:**

Get `"a"` and `"b"` as completions (in addition to global symbols).

**Actual behavior:**

No useful completions.

Issue from https://github.com/Microsoft/TypeScript/pull/21372#issuecomment-359961118

**Comment by zardoy** [comment]
@RyanCavanaugh I guess it is not valid anymore?

https://www.typescriptlang.org/play?#code/MYewdgzgLgBAhgLhgcjsmBeFyg

https://github.com/microsoft/TypeScript/blob/6b43f8277494149c93a482eb1b12b09e9b42b869/src/services/completions.ts#L2908-L2910

**Comment by jakebailey** [comment]
Yeah, this has been supported since at least TS 3.0.
