### ISSUE TITLE
Is it possible to extend the compiler to generate custom modules without forking it?

### ISSUE THREAD

**Issue by Psidium** [Microsoft/TypeScript#21419]
Okay, let's say I use a framework that goes by the name of `openui5` (or maybe its private counterpart: `sapui5`).
In said framework, we can't use `let mod = require('a-module')`, nor `define('module', [ 'dep' ], function (dep) { return { myObject:0 }})`. We are forced to use the framework's type of declaration, which tries to follow the AMD pattern, but it is a little bit different: 
```javascript
sap.ui.define(["some/long/path/to/a/File"], function (File) {
  return File.extend("some.lomg.namespace");
});
```

My question is: is there a way to extend the Typescript compiler to be able to generate code like that?

I did went through https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API, but I only see usages of `ts.ModuleKind` as a compiler option, not as an extension (I might have let something go through, though).

One option would be to just prepend `sap.ui.` to the AMD generated code, but that does not seem like a scalable option to me haha 😄

**Comment by DanielRosenwasser** [comment]
You could always use the transformation pipeline. The `emit` method on `Program` instances has a signature like

```ts
emit(targetSourceFile?: SourceFile, writeFile?: WriteFileCallback, cancellationToken?: CancellationToken, emitOnlyDtsFiles?: boolean, customTransformers?: CustomTransformers): EmitResult;
```

`CustomerTransformers` is defined like so:

```ts
export interface CustomTransformers {
    /** Custom transformers to evaluate before built-in transformations. */
    before?: TransformerFactory<SourceFile>[];
    /** Custom transformers to evaluate after built-in transformations. */
    after?: TransformerFactory<SourceFile>[];
}
```

So you can provide a `before` transformer to customize the module emit as you and.

To be honest though, if you're not planning on having any other AMD-like library on the page, I'd do something like:

```ts
// require-shim.ts
function define(...args: any[]): any {
    sap.ui.define(...args);
}
```

**Comment by EisenbergEffect** [comment]
@DanielRosenwasser Is there any documentation on how to use the hook above?

**Comment by DanielRosenwasser** [comment]
Unfortunately I don't believe so, however, you can see some examples here:

* https://github.com/Microsoft/TypeScript/blob/02e79849ef7259a1985391d85faea1cd6d86c3d0/src/harness/unittests/customTransforms.ts
* https://github.com/Microsoft/TypeScript/blob/02e79849ef7259a1985391d85faea1cd6d86c3d0/src/harness/unittests/transform.ts

**Comment by EisenbergEffect** [comment]
Thanks!
