### ISSUE TITLE
unions with type never may not be working as expected

### ISSUE THREAD

**Issue by StrikeForceZero** [Microsoft/TypeScript#21411]
**TypeScript Version:**  2.8.0

**Search Terms:**  
unions with type `never` may not be working as expected

**Code**

```ts
// bare minimum example
declare const bar: never | string;

// no error, expecting: TS2339 length is not a property of type 'never | string'
bar.length;

// --------------------------------

// use case
function getTemplates(placeholderValues: { foo?: string; } = {}) {
    let templates = {
        get FOO(): never | string {
            throw new Error(`placeholder value 'foo' is required`);
        },
    };

    if (placeholderValues.foo) {
        templates = {
            ...templates,
            get FOO() {
                return `foo is: ${placeholderValues.foo}`;
            },
        };
    }

    return templates;
}


// no error, expecting: TS2339 length is not a property of type 'never | string'
getTemplates().FOO.length;
```

**Expected behavior:** 
expecting length is not a property of type 'never | string'

**Actual behavior:**
no error with `strict: true` in `tsconfig.json`

**Playground Link:** [view in Playground](https://www.typescriptlang.org/play/#src=%2F%2F%20bare%20minimum%20example%0D%0Adeclare%20const%20bar%3A%20never%20%7C%20string%3B%0D%0A%0D%0A%2F%2F%20no%20error%2C%20expect%20length%20is%20not%20a%20property%20of%20type%20'never%20%7C%20string'%3B%0D%0Abar.length%3B%0D%0A%0D%0A%0D%0A%2F%2F%20use%20case%0D%0Afunction%20getTemplates(placeholderValues%3A%20%7B%20foo%3F%3A%20string%3B%20%7D%20%3D%20%7B%7D)%20%7B%0D%0A%20%20%20%20let%20templates%20%3D%20%7B%0D%0A%20%20%20%20%20%20%20%20get%20FOO()%3A%20never%20%7C%20string%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20throw%20new%20Error(%60placeholder%20value%20'foo'%20is%20required%60)%3B%0D%0A%20%20%20%20%20%20%20%20%7D%2C%0D%0A%20%20%20%20%7D%3B%0D%0A%0D%0A%20%20%20%20if%20(placeholderValues.foo)%20%7B%0D%0A%20%20%20%20%20%20%20%20templates%20%3D%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20...templates%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20get%20FOO()%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20return%20%60foo%20is%3A%20%24%7BplaceholderValues.foo%7D%60%3B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0D%0A%20%20%20%20%20%20%20%20%7D%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20return%20templates%3B%0D%0A%7D%0D%0A%0D%0A%0D%0A%2F%2F%20no%20error%2C%20expect%20length%20is%20not%20a%20property%20of%20type%20'never%20%7C%20string'%3B%0D%0Aconst%20foo%20%3D%20getTemplates().FOO.length%3B)

**Related Issues:**

**Comment by andy-ms** [comment]
This is working as intended -- `never` is a subtype of all types including `string`, so `never | string` is just `string`. (Hover over `bar` and you'll see `const bar: string`).
That allows the following code to work:
```ts
function f(b: boolean) {
    const x = b ? (() => { throw new Error() })() : "";
    x.toLowerCase(); // This will always succeed if we get here!
}
```

**Comment by StrikeForceZero** [comment]
interesting, it does makes sense as it would have never have had the chance to access `length` on bar. I overlooked that.
