### ISSUE TITLE
Template string bug \u003 ?

### ISSUE THREAD

**Issue by jbondc** [Microsoft/TypeScript#2141]
```javascript
var foo = `["m",9536]`;
```
Emits
```javascript
var foo = "[\"m\",\u0039536]"; // ?
```
I came across this by pasting JSON into a template string. Whats '\u003' ?

**Comment by DanielRosenwasser** [comment]
Good news! That's actually `\u0039`, which is ASCII `9`, so this is technically not wrong.

Bad news: our escaping is broken for at least 7 characters. I'll have a fix out in a bit.

**Comment by jbondc** [comment]
:) Found fix in
core.ts
    var escapedCharsRegExp = /[\0-\x19\t\v\f\b\0\r\n\u2028\u2029\u0085]/g;

**Comment by DanielRosenwasser** [comment]
Yup, correcting it now.
