### ISSUE TITLE
Add compiler option to disallow assignment of compatible object to class

### ISSUE THREAD

**Issue by kevipapo1** [Microsoft/TypeScript#21418]
**TypeScript Version:**  2.6.2

**Search Terms:** object class assignment

**Code**

```ts
class FooClass {
    fooProperty: string;
}

class BarClass {
    barProperty: string;
}

type FooBarClass = FooClass | BarClass;

function getClassProperty(o: FooBarClass): string {
    if (o instanceof FooClass) {
        return o.fooProperty;
    }
    if (o instanceof BarClass) {
        return o.barProperty;
    }
    return ''; // This should never be reached
}

let foo: FooClass;
let bar: BarClass;

foo = new FooClass();
foo.fooProperty = 'fooValue';
getClassProperty(foo); // 'fooValue'

bar = new BarClass();
bar.barProperty = 'barValue';
getClassProperty(bar); // 'barValue'

foo = {fooProperty: 'fooValue'};
getClassProperty(foo); // ''

bar = {barProperty: 'barValue'};
getClassProperty(bar); // ''
```

The assignment of objects to `foo` and `bar` is successful because their structures match. However, using `instanceof` for the type check is not correct as `foo` and `bar` are an instance of the `Object` class, not their respective class.

It would be nice to have a compiler options that disallows this kind of assignment, even if the structures match.

I know there are alternate ways to determine the type of an object. In this case, you could see if `fooProperty` exists as a property. However, this is not as clear as using `instanceof`.

**Comment by andy-ms** [comment]
You can fix this by adding a private member to the class. See #202.
