### ISSUE TITLE
ForEachCallback key type incorrect

### ISSUE THREAD

**Issue by pelotom** [Microsoft/TypeScript#21420]
**TypeScript Version:**  2.7.0-dev.20180124

**Search Terms:** 

- `ForEachCallback`
- `BufferSource`

**Code**

```ts
const headers: Record<string, string> = {}
  
fetch('/').then(reply => reply.headers.forEach((key, val) => { headers[key] = val }))
```

**Expected behavior:**

Should have no type error.

**Actual behavior:**

Has a type error,

```
Type 'ArrayBuffer' cannot be used as an index type.
```

**Discussion**

This worked fine prior to 2.7, because the type of `ForEachCallback` in `lib.d.ts` was

```ts
interface ForEachCallback {
    (keyId: any, status: MediaKeyStatus): void;
}
```

Now it's changed to

```ts
interface ForEachCallback {
    (keyId: BufferSource, status: MediaKeyStatus): void;
}
```

But the `keyId` experimentally seems to be a `string`, not a `BufferSource`; entering this into the console of any major web browser results in "string" being printed some number of times.

```ts
fetch('/').then(reply => reply.headers.forEach((key, val) => console.log(typeof key)))
```

**Comment by mhegazy** [comment]
The [spec](https://fetch.spec.whatwg.org/#concept-header) seem to suggest that is not a string. that said, we can revert it to `any` to avoid unnecessary breaks in the time being.
