### ISSUE TITLE
[BUG] Typescript 2.6.2 incorrectly generates enum types in .d.ts 

### ISSUE THREAD

**Issue by Coord** [Microsoft/TypeScript#21429]
**TypeScript Version:**  2.6.2

**Search Terms:** 

enum
.d.ts
computed property name
type literal 
built-in symbol

**Code**

This is the typescript src that typescript is compiling (in a .ts file):

```javascript
export enum Code {
        UnknownError = 0,

        // Type errors
        ExpectedBoolean = 1,
        ExpectedNumber = 2,
        ...
}     
```
```javascript
export const Message = {
        [Code.UnknownError]: 'Unknown validation error.',

        [Code.ExpectedBoolean]: 'Value is not of the correct type: expected boolean.',
        [Code.ExpectedNumber]: 'Value is not of the correct type: expected number.',
        ...
}
```

**Expected behavior:**

In TypeScript 2.5.3, it is generated as 

```javascript
const Message: {
        [x: number]: string;
};
```

**Actual behavior:**

In TypeScript 2.6.2, it is generated as 

```javascript
const Message: {
        [Code.UnknownError]: string;
        [Code.ExpectedBoolean]: string;
        [Code.ExpectedNumber]: string;
        ...
}
```

This is incorrect because of this error: [ts] A computed property name in a type literal must directly refer to a built-in symbol.

**Playground Link:**  

**Related Issues:**

**Comment by mhegazy** [comment]
The syntax should be legal starting by TS 2.7.
