### ISSUE TITLE
Variable resolution in abstract classes

### ISSUE THREAD

**Issue by degardinn** [Microsoft/TypeScript#21428]
Hi,

While setting up a Linked List pattern, I've noticed that, when it comes to abstract classes, I can use a `as this['opt']` trick to resolve a variable with its actual type:

```
abstract class oAbstract {
    public opt: any;

    test() {
        // without the 'as this["opt"]', the opt at the bottom of the code would be type "any"
        return this.opt as this["opt"];    
    }
}

class oConcrete extends oAbstract {
    opt = { 'concreteOpt': true }
}

let opt = (new oConcrete).test();   // type: {'concreteOpt': boolean;}
```

It also seems to preserve the generics:

```
class Option<T> {
    constructor(public opt: T) {}

    getValue() {
        return this.opt;
    }
}

abstract class oAbstract2 {
    public opt: any;

    test() {
        return this.opt as this["opt"];
    }
}

class oConcrete2 extends oAbstract2 {
    opt = new Option("hop");
}

let o2 = new oConcrete2;
let opt2 = o2.test();  // Type: Option<string>
```

It's powerful, and actually saving my life, when I need accurate typings over classical OOP patterns such as linked lists, abstract factories, decorators and so on...

I why just wondering, since TS keeps the current type, why such a behavior is not the default. I can't think of a case when a developer would want a method from an object inheritance chain not to return the typings corresponding to the current variable. Are there side-effects to that?

**Comment by RyanCavanaugh** [comment]
`this`-bound types have fairly heavy performance implications as far as things go; this was briefly the default when we were writing `this` types and it was found that many partner codebases became unbearably slow to typecheck.

**Comment by degardinn** [comment]
It makes perfect sense. Thanks for the explanation.
