### ISSUE TITLE
SUGGESTION options for declare function return type

### ISSUE THREAD

**Issue by bluelovers** [Microsoft/TypeScript#21422]
**TypeScript Version:**  2.6.2

**Search Terms:** 

**Code**

```ts
export function getOptions(patterns?, options: IOptions = {})
{
	let ret: {
		patterns: string[];
		options: IOptions;
	};

	return ret;
}
```
we can get 
```ts
export declare function getOptions(patterns?: any, options?: IOptions): {
    patterns: string[];
    options: IOptions;
};
```

but when we add
```ts
export function getOptions(options: IOptions)
export function getOptions(patterns?: string[], options?: IOptions)
export function getOptions(patterns?, options: IOptions = {})
{
	let ret: {
		patterns: string[];
		options: IOptions;
	};

	return ret;
}
```

can we get a option for without add retturn type when we didn't set any return type on each declare function

make it auto follow return type

**Expected behavior:**

i hope return type is
```ts
{
    patterns: string[];
    options: IOptions;
}
```

```ts
export declare function getOptions(options: IOptions): {
    patterns: string[];
    options: IOptions;
};
export declare function getOptions(patterns?: string[], options?: IOptions): {
    patterns: string[];
    options: IOptions;
};
```

**Actual behavior:**

d.ts will become return `any`
```ts
export declare function getOptions(options: IOptions): any;
export declare function getOptions(patterns?: string[], options?: IOptions): any;
```

**Playground Link:**  

**Related Issues:**

**Comment by mhegazy** [comment]
the two scenarios are a bit different, at least from a design stand point. the first is just a simple function, where the return type is inferred from the body, that is straight forward. the second is about overloads. once an overload signature is added, the implementation signature is hidden. e.g.:

```ts
function f(a: number): void;
function f(a: number | string): void {   ... }
```

This function really has one signature, and it is `f(a: number)`. the other signature is "implementation", i.e. the compiler uses this signature to check that it matches all the other overloads, but does not expose it. 

For the implementation signature, inference from the body of the function still occurs, it is just that it is hidden.

Now to the suggestion for inferring the return types of overloads from that of the implementation signature; most of the time the differing return type is why you would define an overload in the first place.. and in these cases the implementation signature is too broad.. e.g.: 

```ts
function getShape(name: "circle", radius: number): Circle;
function getShape(name: "square", length: number): Square;
function getShape(name: string, radiusOrLength: number) {
    return name === "circle" ? new Circle() : new Square();
}
```

inferring `Circle | Square` is really not very useful here, and the user is better off writing it explicitly.

**Comment by bluelovers** [comment]
still hopw can have this

----

what i suggestion is

when **all** overwrite **didn't set** return type, make all overload return follow function's return type

```ts
function getShape(name: "circle", radius: number)
function getShape(name: "square", length: number)
function getShape(name: string, radiusOrLength: number) {
    return name === "circle" ? new Circle() : new Square();
}
```
=>
```ts
declare function getShape(name: "circle", radius: number): Circle | Square;
declare function getShape(name: "square", length: number): Circle | Square;
```

when **any** overwrite **has set** return type , then  same as current typescript do

```ts
function getShape(name: "circle", radius: number): Circle
function getShape(name: "square", length: number)
function getShape(name: string, radiusOrLength: number) {
    return name === "circle" ? new Circle() : new Square();
}
```
=>
```ts
declare function getShape(name: "circle", radius: number): Circle;
declare function getShape(name: "square", length: number): any;
```
