### ISSUE TITLE
Non-null assertion mutates constrained type parameters (regression)

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#21438]
**TypeScript Version:**  master

**Search Terms:** 

**Code**

```ts
function f<T extends undefined | object>(o: T): T {
  return o!;
}
```

from https://github.com/falsandtru/typed-dom/blob/9e20f121ba0cc98da343a63deddeaae819d4a716/src/dom/html.ts#L36-L41

An argument `o?: T` is `T | undefined` but `o!` isn't `T`.

**Expected behavior:**

pass

**Actual behavior:**

```
$ node built/local/tsc.js --noEmit --strictNullChecks index.ts
index.ts(2,3): error TS2322: Type 'object' is not assignable to type 'T'.
```

**Related Issues:**

#21369?

cc @ahejlsberg @weswigham

**Comment by ajafff** [comment]
According to https://github.com/Microsoft/TypeScript/issues/21317#issuecomment-359657955 this is intended.
