### ISSUE TITLE
narrowing is lost at creating literals

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#21436]
```typescript

interface A { isIt: true; text: string; }
interface B { isIt: false; value: number; }
type C = A | B;
const isIt = Math.random() > 0.5;
const c : C = isIt ? { isIt, text: 'hey' } : { isIt, value: 123 }; /* <-- expected to work, actual:
Type '{ isIt: boolean; text: string; } | { isIt: boolean; value: number; }' is not assignable to type 'C'.
  Type '{ isIt: boolean; text: string; }' is not assignable to type 'C'.
    Type '{ isIt: boolean; text: string; }' is not assignable to type 'B'.
      Property 'value' is missing in type '{ isIt: boolean; text: string; }'.
*/
```

the following works tho:

```typescript
const c : C = isIt ? { isIt: isIt, text: 'hey' } : { isIt: isIt, value: 123 };

```

**Comment by DanielRosenwasser** [comment]
It's extremely strange to me that quick info seems to narrow `isIt` to `true` in the true branch, but doesn't narrow at all in the false branch.

**Comment by jack-williams** [comment]
@DanielRosenwasser I believe you get the correct narrowing behavior with `strictNullChecks` enabled. With it disabled, a truthy `boolean` must be `true`, but a falsey one might be `null` or `undefined`.

**Comment by weswigham** [comment]
You get the same error with `strict: true`.

We have this comment written in the implementation for `isLiteralOfContextualType`:
```ts
                    // If the contextual type is a union containing both of the 'true' and 'false' types we
                    // don't consider it a literal context for boolean literals.
```
indicating that we're explicitly marking this scenario as not-a-place-for-literals right now.
@ahejlsberg Did you have a motivating case for the exception for booleans here?

**Comment by weswigham** [comment]
@ahejlsberg You left a comment inside `isLiteralOfContextualType` to the effect that this is intended:
```ts
                    // If the contextual type is a union containing both of the 'true' and 'false' types we
                    // don't consider it a literal context for boolean literals.
```
is there a motivating example for this, or can the exception for booleans be removed?

**Comment by ahejlsberg** [comment]
@weswigham As I recall it had to do with destructuring an object literal that specifies the value `true` for a property and at the same time specifices `false` as the destructuring default. You could try to remove it and see what baseline effects it has.
