### ISSUE TITLE
Specifying index in HTMLCollection returns Element not HTMLElement

### ISSUE THREAD

**Issue by devinjames** [Microsoft/TypeScript#21439]
If I am accessing an HTMLCollection, and try to use an index of the first child, TSC returns an error that the subsequent property I'm looking for is not a property of 'Element', because TSC believes it is an Element and not a HTMLElement

i.e.  In the following HTML:
```
<div id="container">
<div>child</div>
</div>
```

`document.getElementById('container').children[0].offsetTop`

Will fail, stating that "property 'offsetTop' does not exit on type 'Element'"

It looks that TSC believes that a HTMLCollection consists of Elements and not HTMLElements?

**Comment by RyanCavanaugh** [comment]
Per comments in the linked PR above, `children[0]` is not necessarily an `HTMLElement`
