### ISSUE TITLE
Split ActiveX interop definitions in scripthost.d.ts to separate file

### ISSUE THREAD

**Issue by zspitz** [Microsoft/TypeScript#21440]
**TypeScript Version:**  typescript@2.8.0-dev.20180127

**Search Terms:** 
scripthost.d.ts
wscript
activex
activexobject
hta
jscript

**Code**
When writing Typescript intended to be run under [`mshta.exe`](https://msdn.microsoft.com/en-us/library/ms536496(v=vs.85).aspx):
```ts
WScript.Echo(...
WScript.CreateObject(...
// or any other member of the global WScript object
```

**Expected behavior:**
Should not compile, because the `WScript` global object is not available under an HTA.

**Actual behavior:**
Compiles successfully

**Playground Link:** Not applicable

**Related Issues:**

**Further details**
`scripthost.d.ts` currently has two kinds of definitions:
* ActiveX object interop (`new ActiveXObject`, `SafeArray` etc); which are available under both WScript and HTA
* WScript global object, which is unavailable under HTA

My understanding is that the Typescript compiler no longer uses the CScript host, so perhaps everything in `scripthost.d.ts` should be moved to DefinitelyTyped. But as long as `scripthost.d.ts`is part of the `lib`, then it should accurately model both scenarios.

I propose a new file -- e.g. `jscript.d.ts` -- specifically for ActiveX object interop (but may also include other [JScript extensions](http://interoperability.blob.core.windows.net/web/MS-ES3EX/[MS-ES3EX]-170314.pdf) if needed). `scripthost.d.ts` should depend on this new file, if that's possible, to avoid breaking code that currently uses `"lib": ["scripthost"]`.

**Comment by zspitz** [comment]
@DanielRosenwasser Any news on this?

**Comment by zspitz** [comment]
@DanielRosenwasser Which is the better choice here: Move all of `scripthost.d.ts` to Definitely Typed? Or split the JScript extensions into another file?

**Comment by zspitz** [comment]
@mhegazy You mean leave the current version of `scripthost.d.ts` in [source](https://github.com/Microsoft/TypeScript/tree/master/src/lib); and create two definitions on DefinitelyTyped: One with the JScript extensions -- `jscript.d.ts` -- and another `scripthost.d.ts` with dependencies on `jscript.d.ts`? And deprecate the use of `scripthost` in the `libs` option in `tsconfig.json`?

**Comment by mhegazy** [comment]
> @mhegazy You mean leave the current version of scripthost.d.ts in source; and create two definitions on DefinitelyTyped: one with the JScript extensions -- jscript.d.ts -- and another scripthost.d.ts with dependencies on jscript.d.ts? 

yes.
