### ISSUE TITLE
Add ActiveXObject lookup type to scripthost.d.ts, for use by external factory methods (e.g. WScript.CreateObject)

### ISSUE THREAD

**Issue by zspitz** [Microsoft/TypeScript#21442]
**TypeScript Version:**  typescript@2.8.0-dev.20180127

**Search Terms:** 
scripthost.d.ts
wscript
activex
activexobject
jscript

**Code**

```ts
/// <reference types="activex-excel" />
const app = WScript.CreateObject('Excel.Application');
```

**Expected behavior:**
`app` should be typed as [`Excel.Application`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/activex-excel/index.d.ts#L3053)

**Actual behavior:**
Typed as `any`

**Further details**
Currently, ActiveX definitions define [a constructor overload on `ActiveXObject`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/activex-excel/index.d.ts#L9467):
```ts
interface ActiveXObject {
    //other members
    new<K extends keyof ActiveXObjectNameMap = any>(progid: K): ActiveXObjectNameMap[K];
}
```
that uses a [lookup type](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/activex-excel/index.d.ts#L9470) to map from strings to object types:
```ts
// from activex-excel
interface ActiveXObjectNameMap {
    'Excel.Application': Excel.Application;
    'Excel.Chart': Excel.Chart;
    'Excel.Sheet': Excel.Worksheet;
}
```
I propose that the lookup interface be defined in `scripthost.d.ts`, and the relevant WScript/ActiveXObject methods within `scripthost.d.ts` be typed to use the lookup:
```ts
interface ActiveXObjectNameMap {
}

interface WScript {
    CreateObject<K extends keyof ActiveXObjectNameMap = any>(strProgID: K, strPrefix?: string): ActiveXObjectNameMap[K];
    GetObject<K extends keyof ActiveXObjectNameMap = any>(strPathname: string, strProgID?: K, strPrefix?: string): ActiveXObjectNameMap[K]y;
}

interface ActiveXObject {
    new<K extends keyof ActiveXObjectNameMap = any>(progid: K): ActiveXObjectNameMap[K];
}
```
Thus each ActiveX definition file would only have to extend the lookup interface.

The lookup type could also be leveraged by other definition files that create ActiveX objects -- e.g. the [UNO `com.sun.star.bridge.oleautomation.Factory`](https://wiki.openoffice.org/wiki/Documentation/DevGuide/ProUNO/Bridge/The_Bridge_Services#Service:_com.sun.star.bridge.oleautomation.Factory)

One possible issue: there are currently no type definitions in `scripthost.d.ts` that are created via the string progid, so the lookup interface would be an empty interface. Probably would require a `// tslint:disable-line no-empty-interface`.

**Comment by zspitz** [comment]
One possible issue: there are currently no type definitions in `scripthost.d.ts` that are created via the string progid, so the lookup interface would be an empty interface. Other definition files would be able to add to the lookup interface. Is this a problem?

**Comment by zspitz** [comment]
@RyanCavanaugh What does the **Awaiting More Freedback** label mean in this context?

**Comment by zspitz** [comment]
@RyanCavanaugh Any news on this?

**Comment by mhegazy** [comment]
I am working on revamping the lib generation script  in https://github.com/Microsoft/TSJS-lib-generator, so you might want to hold off on changing it for a week or so.
