### ISSUE TITLE
Inconsistent type when indexing an optional or undefined property of a type.

### ISSUE THREAD

**Issue by ccorcos** [Microsoft/TypeScript#21448]
**TypeScript Version:**  2.7.0-dev.201xxxxx

**Search Terms:** 
- index optional type undefined
- optional type index
- undefined type property index 
- index property nonnullable
- strict type indexing nullable 

**Code**

```ts
type a = {a?: number}
type x = a["a"] // "number"

type b = {b: number | undefined}
type y = b["b"] // "number"
```

**Expected behavior:**
I expect both x and y to have a type of `number | undefined`.

**Actual behavior:**
Both are non-nullable types.

**Playground Link:**  https://www.typescriptlang.org/play/index.html#src=type%20a%20%3D%20%7Ba%3F%3A%20number%7D%0D%0Atype%20x%20%3D%20a%5B%22a%22%5D%20%2F%2F%20%22number%22%0D%0A%0D%0Atype%20b%20%3D%20%7Bb%3A%20number%20%7C%20undefined%7D%0D%0Atype%20y%20%3D%20b%5B%22b%22%5D%20%2F%2F%20%22number%22

**Related Issues:**
 
Couldn't find any -- hard to search for. The language for this stuff is so verbose to describe.

**Comment by jack-williams** [comment]
By default all types are 'nullable', so `number | undefined` gets normalised to just `number`. You get the expected behavior with the `strictNullChecks` option enabled.

```typscript
type TEST = number | undefined  // TEST = number by default

// with --strictNullChecks
type TEST2 = number | undefined // TEST2 = number | undefined
```

In **Playground**, try **Options** > **strictNullChecks**

**Comment by ccorcos** [comment]
Oh man, youre right. Strict nullchecks was off! sorry
