### ISSUE TITLE
Can we move to three digit version numbers `X.Y.Z`

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#2144]
http://semver.org/

1. Currently version in source file is `1.4.1.0` the version in package.json is `1.4.1` Can we reconcile these?
1. Also better if we move the `servicesVersion` (`0.4`) to the form `X.Y.Z`, so `0.4.0`.
1. If we need the additional `.0` can we use `-` i.e. `1.4.1-0`. This will make it consistent with the vast majority of projects out there. Again better if we are consistent in the source file / package.json

**Comment by DanielRosenwasser** [comment]
I think the format we use has something to do with part of our internal build process, but I don't know if we're necessarily wedded to it. @mhegazy and @JsonFreeman might be able to weigh in.

**Comment by mhegazy** [comment]
i think we can do the three digits and we can make them all match.

**Comment by paulvanbrenk** [comment]
As with everything... it depends Windows executables, assemblies, and installers all have 4 digits in their versions. Sticking to a consistent numbering schema across all of our components seems more convenient than arbitrarily moving some components to a 3 digit scheme, because other projects do that.

**Comment by JsonFreeman** [comment]
3 digits is fine with me. The version that tsc.js prints is not actually used anywhere by us. The only reason it would matter is if it breaks external customers who depend on the 4 digit version format.

**Comment by jasonwilliams200OK** [comment]
Semantic versioning is the proven winner.

It is not only about 3 digits, there are many other benefits of using semantic versioning.

You can have alpha, beta, rc as well like this:

2.0.0-alpha.1
2.0.0-beta.3
2.0.0-rc.2

(notice the alphabetic ordering also matters, for instance, rtm comes after rc)

Also, see how well it has served npm: https://docs.npmjs.com/misc/semver and whoever has embraced semver philosophy is sticking with it.

Explore and you will know more..

**Comment by nexussays** [comment]
+1

This is one of those seemingly insignificant things that has the potential to cause completely unexpected problems down the line. Just fix it and be done with it for all time.

**Comment by mhegazy** [comment]
The services version will be a bit tricky as it is used hard coded in VS, so we need to think of a way to phase it or, just add the extra digit next time we rev it.
