### ISSUE TITLE
WSH alias for WScript global object in `scripthost.d.ts`

### ISSUE THREAD

**Issue by zspitz** [Microsoft/TypeScript#21441]
**TypeScript Version:**  typescript@2.8.0-dev.20180127
**Search Terms:** scripthost.d.ts, wscript, WSH

**Code**

```ts
// "lib":["scripthost"]
WSH.Echo('message');
```

**Expected behavior:**
Should compile

**Actual behavior:**
Doesn't compile

**Further details**
When running scripts under CScript/WScript, the `WScript` global object is also aliased as WSH.

Currently, `scripthost.d.ts` defines `WScript` as a `declare`d `var`. I propose the following:
```ts
// define as pseudonominal type -- https://github.com/Microsoft/TypeScript/issues/17526
declare class WScriptGlobal {
    private constructor();
    private WScriptGlobal_typekey: WScriptGlobal;

    // all members currently under WScript

}
declare const WScript: WScriptGlobal;
declare const WSH: WScriptGlobal;
```

**Comment by DanielRosenwasser** [comment]
There's not much of a reason I can see to introduce a class. I think it'd be fine to just define it as

```ts
declare var WSH: typeof WScript;
```

or alternatively, move the current annotation to an interface and do something similar to what you mentioned.

```ts
interface WScriptGlobal {
    // ...
}

declare var WScript: WScriptGlobal;
declare var WSH: WScriptGlobal;
```

**Comment by zspitz** [comment]
@DanielRosenwasser What about `declare const` instead of `declare var`?
