### ISSUE TITLE
keyof becoming union of string literal in emitted type definitions

### ISSUE THREAD

**Issue by JakeGinnivan** [Microsoft/TypeScript#21445]
**TypeScript Version:**  2.6.2

**Search Terms:** 
type definition union string
type alias expansion

And a number of variations

**Code**
I am having a really hard time reproducing this outside of out my project, I am hoping someone may have an idea on what the issue may be related to to help me reproduce it. 

My goal is to have all my feature toggling infrastructure/code in a helper library, then use interface declaration merging to actually declare the features.

```ts
// In npm module
declare global  {
    namespace Etrigan {
        interface Features {
        }
    }
}
export type Feature = keyof Etrigan.Features

// In my code
declare global  {
    namespace Etrigan {
        interface Features {
            test: {}
        }
    }
}
export const isFeatureEnabled = (toggles: TogglesState, feature: Feature) => {
  ...
}
```

**Expected behavior:**
The d.ts file to contain:
`export const isFeatureEnabled = (toggles: TogglesState, feature: Feature) => boolean`

**Actual behavior:**
`export const isFeatureEnabled = (toggles: TogglesState, feature: 'test') => boolean`

Notice the keyof has been expanded into a string literal. If I add more keys, it becomes a union of string literals. I have many other usages in the type definitions which retain the type alias, but not this one for some reason...

I haven't been able to upgrade to `@next` yet due to a number of other checks which now fail, but any ideas which may help me product a working reproduction is welcome.

**Playground Link:**
n/a because the issue is in generated type definitions

**Related Issues:**
I can't find anything related to this issue.

**Comment by JakeGinnivan** [comment]
Just checked with 2.8.0-dev.20180127 and the issue still exists

**Comment by JakeGinnivan** [comment]
Another interesting fact. Changing

```
export const isFeatureEnabled = (toggles: TogglesState, feature: 'test') => {
...
}
```

to

```
export function isFeatureEnabled(toggles: TogglesState, feature: Feature) {
...
}
```

Does not have this issue

**Comment by mhegazy** [comment]
I am having hard time piecing together a local repro for this. can you share some self-contained sample we can try?
