### ISSUE TITLE
[Doc]TSS_Debug has been removed

### ISSUE THREAD

**Issue by shcant** [Microsoft/TypeScript#21454]
In [Debugging Language Service in VS Code](https://github.com/Microsoft/TypeScript/wiki/Debugging-Language-Service-in-VS-Code#debugging-tsserver-server-side), it seems that `TSS_Debug` has been removed by vscode but this doc still kept.

**Comment by RyanCavanaugh** [comment]
@mjbvz when did this happen? Intentional?

**Comment by mjbvz** [comment]
~6 months ago. I can add it back in
