### ISSUE TITLE
ElementTagNameMap has wrong case for camelCase SVG elements

### ISSUE THREAD

**Issue by HolgerJeromin** [Microsoft/TypeScript#21450]
**TypeScript Version:**  master

**Code**
```ts
var svgEle = document.createElementNS('http://www.w3.org/2000/svg', 'svg');
var linGrad = document.createElementNS('http://www.w3.org/2000/svg', 'linearGradient');
svgEle.appendChild(linGrad);

// typescript SVGLinearGradientElement, Browser null (Tested with Chrome and IE11)
var resultNull = svgEle.querySelector('lineargradient'); 

// typescript Element,  Browser SVGLinearGradientElement
var resultOk = svgEle.querySelector('linearGradient'); 
```

**Expected behavior:**
`.querySelector('linearGradient') `
should return a `SVGLinearGradientElement `

**Actual behavior:**
The `*TagNameMap` maps the wrong case to the `SvgElement` type
https://github.com/Microsoft/TypeScript/blob/02e79849ef7259a1985391d85faea1cd6d86c3d0/lib/lib.d.ts#L19129

Probably effected:
clipPath, componentTransferFunction, feBlend, feColorMatrix, feComponentTransfer, feComposite, feConvolveMatrix, feDiffuseLighting, feDisplacementMap, feDistantLight, feFlood, feFuncA, feFuncB, feFuncG, feFuncR, feGaussianBlur, feImage, feMerge, feMergeNode, feMorphology, feOffset, fePointLight, feSpecularLighting, feSpotLight, feTile, feTurbulence, foreignObject, linearGradient, radialGradient, textContent, textPath, textPositioning

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by variousauthors** [comment]
It appears that all of the entries in the `SVGElementTagNameMap` interface are lowercase, rather than camelcase. There is an issue regarding the camelcase svg tags in the w3c repo: https://github.com/w3c/svgwg/issues/161

It looks like the tagnames are case insensitive, so you can use `<linearGradient>` or `<lineargradient>` and it will be fine, but the methods are case sensitive?
