### ISSUE TITLE
Visual studio 2017 intellisense shows errors when tsc.exe compiles fine.

### ISSUE THREAD

**Issue by valeriob** [Microsoft/TypeScript#21451]
- visual studio 2017 15.5 or 15.6 preview
- Typescript 2.6.2
tsconfig.json with this path config : 
 "files": [
    "wwwroot/definition.d.ts",
  ],
  "include": [
    ""
  ],
  "exclude": [
    "node_modules",
    "wwwroot",
    "bin",
    "obj"
  ]

Opening a typescript file that references types defined on definition.d.ts it shows error : 
Error	TS2304	(TS) Cannot find name 'mynamespace'.

Looks like the files resolution of tsc.exe and intellisense are different.

**Comment by mhegazy** [comment]
We will need a self-contained repro project or steps to recreate the errors locally to be able to diagnose the issue.

**Comment by AlCalzone** [comment]
Is your VS using its own bundled version of TypeScript (which could be as ancient as 1.5) or the one from your project/a global one? That hidden "feature" already cost me a day or two.

**Comment by valeriob** [comment]
hi, @AlCalzone, how do i check that ? i added the nuget package Microsoft.TypeScript.MSBuild 2.6.2, i have no clue what vs intellisense is using.

**Comment by AlCalzone** [comment]
Not sure exactly, has been a while since I used the full-blown VS. Its hidden somewhere in the language options (or include paths), if I remember correctly.
