### ISSUE TITLE
Generic type parameters constraints are not constraining nested occurences

### ISSUE THREAD

**Issue by sztrzask** [Microsoft/TypeScript#21452]
**TypeScript Version:**  2.6.2

**Search Terms:** 
Generic, parameter, constraint
**Code**

```
//Given abstract generic class

interface IA { 
    id: string;
}

abstract class A<TA extends IA> { 
    abstract save(): TA
}

//Given that's class concerete implementation
interface IB extends IA { 
    name: string;
}

class B extends A<IB>
{ 
    save(): IB { 
        return null as any as IB;
    }
}


//How to enforce the "matching" types?
class C { 

    callSave<TClass extends A<TInterface>,
        TInterface extends IA>(): TInterface { 
        return null as any as TInterface;
        }
}

var c = new C();

//In C# that would fail
c.callSave<B, IA>();
```

**Expected behavior:**

Code does not compile

**Actual behavior:**

Code compiles

**Playground Link:**  
[link](http://www.typescriptlang.org/play/#src=%2F%2FGiven%20abstract%20generic%20class%0D%0A%0D%0Ainterface%20IA%20%7B%20%0D%0A%20%20%20%20id%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Aabstract%20class%20A%3CTA%20extends%20IA%3E%20%7B%20%0D%0A%20%20%20%20abstract%20save()%3A%20TA%0D%0A%7D%0D%0A%0D%0A%2F%2FGiven%20that's%20class%20concerete%20implementation%0D%0Ainterface%20IB%20extends%20IA%20%7B%20%0D%0A%20%20%20%20name%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Aclass%20B%20extends%20A%3CIB%3E%0D%0A%7B%20%0D%0A%20%20%20%20save()%3A%20IB%20%7B%20%0D%0A%20%20%20%20%20%20%20%20return%20null%20as%20any%20as%20IB%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0A%0D%0A%2F%2FHow%20to%20enforce%20the%20%22matching%22%20types%3F%0D%0Aclass%20C%20%7B%20%0D%0A%0D%0A%20%20%20%20callSave%3CTClass%20extends%20A%3CTInterface%3E%2C%0D%0A%20%20%20%20%20%20%20%20TInterface%20extends%20IA%3E()%3A%20TInterface%20%7B%20%0D%0A%20%20%20%20%20%20%20%20return%20null%20as%20any%20as%20TInterface%3B%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Avar%20c%20%3D%20new%20C()%3B%0D%0A%0D%0A%2F%2FIn%20C%23%20that%20would%20fail%0D%0Ac.callSave%3CB%2C%20IA%3E()%3B)
**Related Issues:**
https://github.com/Microsoft/TypeScript/issues/21249

**Comment by RyanCavanaugh** [comment]
There's nothing wrong with that call. `B` is a valid `A<IA>`, and `IA` is a valid `IA`.
