### ISSUE TITLE
Quick fix all showing up even if there is only one error

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#21458]
**Code**

```ts
class Foo {
    prop: number

    foo() { prop }
}
```

Using VS Code insiders, trigger quick fix on `prop` in `foo` 

**Expected behavior:**
Only a single code action is shown

**Actual behavior:**
The base code action and a `quick fix all` code action are shown. The latter doesn't make sense as there is only a single error in the file

@andy-ms Is this something we are supposed to handle on the VS Code side or should `getCombinedCodeFix` be smarter here?

**Comment by RyanCavanaugh** [comment]
Isn't this desirable? If you bound a key combination to `Quick fix all`, you wouldn't want it to not work when there was only 1 thing to do.

**Comment by mjbvz** [comment]
This is for our lightbulb context menu:

<img width="517" alt="screen shot 2018-01-29 at 11 59 56 am" src="https://user-images.githubusercontent.com/12821956/35531480-f81c839c-04eb-11e8-89fa-dbce3664ce26.png">

Having the extra entry doesn't make sense since there is only one error

**Comment by mjbvz** [comment]
Ok, I can make this change for VS Code 1.20. Just to make sure I understand: it is safe to assume that any diagnostic that only appears once in a file will not have a "fix all" action?

**Comment by andy-ms** [comment]
> it is safe to assume that any diagnostic that only appears once in a file will not have a "fix all" action?

I think we will always *provide* a fix-all action, but the action would only end up fixing one thing (since there is only one diagnostic).
But there's also the problem that a diagnostic *code* may appear only once, but there may be other diagnostic codes that would be part of the same fix...
