### ISSUE TITLE
--declaration compiler option breaks exporting mixins

### ISSUE THREAD

**Issue by jtlapp** [Microsoft/TypeScript#21465]
**TypeScript Version:**  2.6.2, 2.8.0-dev.20180127

**Search Terms:** export type-literals class expression declaration compiler option mixin mixins

**Code**

```ts
interface Constructor<C> { new (...args: any[]): C; }

function mixin<B extends Constructor<{}>>(Base: B) {
    class PrivateMixed extends Base {
        bar = 2;
    }
    return PrivateMixed;
}

class Unmixed {
    foo = 1;
}

// error TS4025: Exported variable 'Mixed' has or is using private name 'PrivateMixed'.
// error TS4025: Exported variable 'Mixed' has or is using private name 'Unmixed'.
// error TS4025: Exported variable 'Mixed' has or is using private name 'mixin'.
export const Mixed = mixin(Unmixed);
```

**Expected behavior:** Code should compile regardless of whether compiled with `declaration` option.

**Actual behavior:** Code compiles without errors without the `declaration` option, compiles with the above errors with the `declaration` option.

**Related Issues:** Appears to be an oversight of PR #15932.

**Comment by aluanhaddad** [comment]
@jtlapp you can work around the issue by returning a class expression instead of a local class e.g.
```ts
function mixin<B extends Constructor<{}>>(Base: B) {
  return class Mixed extends Base {
    bar = 2;
  };
}
```

**Comment by jtlapp** [comment]
Thanks @aluanhaddad. I started with that approach, as that's what's described everywhere on the net. But my framework has well outgrown it. Thing is, I'm not sure why I'd ever emit declaration files for Typescript. There must be a reason I put that switch in there!

**Comment by aluanhaddad** [comment]
You emit declaration files for consumers of the package, esp. if you do not publish the source.



Anyway, I don't understand how a project would  outgrow returning a class expression.

**Comment by jtlapp** [comment]
> I don't understand how a project would outgrow returning a class expression.

Thinking back, I'm able to use decorators on nested classes, but not on class expressions, and I'm able to declare nested classes abstract but cannot actually get abstract class expressions.

I also do some checks on the generated expression, prior to returning it, but I guess I could be writing `const Mixed = class extends Base {}`, so maybe I didn't need the approach for that.

**Comment by aluanhaddad** [comment]
Yeah decorators are definitely not going to work. I should have mentioned that. Elsewise the temp assignment you've shown above works.

**Comment by cspotcode** [comment]
This is breaking for me trying to write an abstract mixin.  I can't use the class expression workaround because class expressions can't be abstract.

```
export function Filter<C extends Ctor<any>>(ctor: Ctor<any>) {
    abstract class Filter extends ctor {
        abstract match(path: string): boolean;
        // other concrete methods, fields, constructor
    }
    return Filter;
}
```
