### ISSUE TITLE
Please update or remove outdated TypeScript Language Spec 1.8 from 2016

### ISSUE THREAD

**Issue by fmorriso** [Microsoft/TypeScript#21477]
Suggestion: please either update or remove the out-of-date language specification located at https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md

The one found at that location is dated January 2016 (it's January 2018 as I write this) for TypeScript version 1.8 (2.6.2 is the current release).

**Comment by RyanCavanaugh** [comment]
We're working on it https://github.com/Microsoft/TypeScript/issues?q=is%3Aissue+label%3ASpec

**Comment by fmorriso** [comment]
Gone, I suppose, are the days that real human beings monitored these issues, not some disemboweled "bot" that closes issues like this when it is clear to any rational human being that this issue is  not anywhere CLOSE to being resolved.

**Comment by RyanCavanaugh** [comment]
@fmorriso 👁 👁

**Comment by RyanCavanaugh** [comment]
You had 2 weeks to respond to this issue, but didn't. We don't keep bugs open which are simply of the form "Other open bugs exist". If there's a spec issue not being tracked by the spec bugs, you can open a new one.

Our issue tracker policy is that "open" issues should be actionable and specific. This one is neither, so it was closed.
