### ISSUE TITLE
Question, how to make a variable within declared module name

### ISSUE THREAD

**Issue by NN---** [Microsoft/TypeScript#2147]
I am writing a test and I have an issue.
The test runner doesn't have the global object I need since it is running in a different environment.
I want to create this object because strict mode complains otherwise, but TypeScript cannot do it.

I have declaration:
```typescript
declare module Q {
	function f(): string;
}
```

and usage
```typescript
var x = Q.f();
```

Now in my test I want to mock Q.f and create object of my own.
```typescript
var Q = { ... }
```
The TypeScript complains about multiple declarations.

There is a workaround to access the module through the global 'window' object in the code and then it is possible to test it.
```typescript
interface Window {
 Q: QInterface;
}

interface QInterface {
	function f(): string;
}

// the code
var x = !!window.Q ? window.Q.f() : "";
```

I would like to not use the workaround and find some solution without changing my code.
Thanks.

**Comment by DanielRosenwasser** [comment]
It sounds like describing your module with an interface will solve your problem.

```TypeScript
interface Q {
    f(): string;
}

var Q = {
    f() {
        return "Hello";
    }
}

var x = Q.f();
```

**Comment by mhegazy** [comment]
how about;

```TypeScript
declare var Q : {
    f(): string;
};
```

later on in your tests:

```TypeScript
var Q = {
    f() { .. }
}
```

**Comment by NN---** [comment]
@DanielRosenwasser I don't see how it solves it
@mhegazy It means that I must rewrite all the definition files that don't use 'var' .
Some of definitions files are in the following form:
```typescript
declare module A.B {
 function f(): I;
 interface I {}
}
declare module A.C {
 function g(): J;
 interface J {}
}
//2500 similar lines
```
Is there easy way to refactor it ?:)

**Comment by NN---** [comment]
If I could use modules as types specifiers then it would be easy to refactor the code for 'var' .

**Comment by mhegazy** [comment]
The probelm is that a module and var do not really merge. the var will override the value of the module, so this is why it is flagged as an error.

how about this:
```TypeScript
// declaration
declare module M {
    function f(): string;
}


// tests
module M { 
    M.f = ()=> "";
}
```

**Comment by NN---** [comment]
@mhegazy Great idea ! :)
Didn't think about just defining the module.
Thanks :)
