### ISSUE TITLE
Unusual behavior of the cast string to number

### ISSUE THREAD

**Issue by js2me** [Microsoft/TypeScript#21480]
Hi and sorry for  perhaps stupid question.
I found unusual behavior in casting from string to number value
![default](https://user-images.githubusercontent.com/16340911/35580008-2b6ed85e-05f9-11e8-98dd-e718b0dfa46d.png)
![2](https://user-images.githubusercontent.com/16340911/35580012-2e197596-05f9-11e8-86cb-421570380dbf.png)
Its normal?

**Comment by js2me** [comment]
Now I understand so that ```<number>value``` or ```value as number``` just compiled to ```value```
Its so sadly...

**Comment by mhegazy** [comment]
Type assertions (`<type> expr` or `expr as type`) are just that, assertions. you are telling the compiler you know what you are doing and asking it to trust you. there is no explicit conversions done at runtime..  see https://www.typescriptlang.org/docs/handbook/basic-types.html#type-assertions for more details.

consider using `+value` instead.

**Comment by js2me** [comment]
@mhegazy I already understood this, thank you for answer!
