### ISSUE TITLE
Allow local interface definition

### ISSUE THREAD

**Issue by NN---** [Microsoft/TypeScript#2148]
It is impossible to define local interface in the function, but you can do it in the module.

```typescript
module A {
  interface B{} // OK 
}

(function X() {
  interface Y { } // Error
})();
```

**Comment by RyanCavanaugh** [comment]
I thought we had a bug for block-level interfaces somewhere already?

Anyway some compelling examples would be useful. It's just as easy to write a var declaration with a given type and use `typeof x` to refer to that shape, since you're probably going to consume the type that way regardless?

**Comment by NN---** [comment]
Agree, 'typeof x' is possible workaround.
I should get used to it.
