### ISSUE TITLE
Support @this jsdoc tag

### ISSUE THREAD

**Issue by weswigham** [Microsoft/TypeScript#21488]
**TypeScript Version:**  2.7.0-dev.201xxxxx

We should support the jsdoc [@this tag](http://usejsdoc.org/tags-this.html) - without it it is difficult (impossible?) to assign a type to `this` within a function, as can be required when `strictFunctionTypes` is `true`.

**Code**

```ts
// @strict: true
// @allowJs: true
// @checkJs: true
// @filename: tests.ts
declare function isBig(x: any): x is { big: true };
// @filename: file.js
/**
 * @this {{}}
 */
function bigger() {
    if (isBig(this)) {
        this.big; // Expect property to exist
    }
}
```

**Expected behavior:**
No errors.

**Actual behavior:**
```
!!! error TS2683: 'this' implicitly has type 'any' because it does not have a type annotation.
```
on both `this` references in `bigger`.

**Comment by mhegazy** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/17197 ?

**Comment by weswigham** [comment]
Definitely. Apparently searching for `@this` instead of `this` doesn't make github search happy.
