### ISSUE TITLE
Syntax on githab does not work anywhere

### ISSUE THREAD

**Issue by splincode** [Microsoft/TypeScript#21482]
![image](https://user-images.githubusercontent.com/12021443/35581286-66f7457a-05fc-11e8-8711-e64dfac5f0b8.png)

Or: https://github.com/Angular-RU/angular-universal-starter/blob/master/src/test.ts
Syntax highlight not working

**Comment by DanielRosenwasser** [comment]
This seems to be a problem with GitHub, not with TypeScript.

**Comment by DanielRosenwasser** [comment]
Duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/563.
