### ISSUE TITLE
Install @types quick fix can erase node modules installed with yarn

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#21504]
**TypeScript Version:**  2.7.0-dev.20180127

**Search Terms:** 

- Install @types quick fix
- Yarn 

https://github.com/Microsoft/vscode/issues/42535

**Code**
1. In a new project:

2. 
    ```
    $ npm init -y
    $ yarn request lodash
    ```

3. In a ts file in the project:

    ```ts
    import * as r from 'request'
    ```

4. Trigger quick fix to install @types for `request`

**Expected behavior:**
Installs `@types/request`

**Actual behavior:**
Installs but also seems to erase other installed `node_modules`. See https://github.com/Microsoft/vscode/issues/42535

**Related Issues:**
- https://github.com/Microsoft/TypeScript/issues/19269

**Comment by octref** [comment]
@mjbvz Should be `yarn add request lodash`.

**Comment by mhegazy** [comment]
Currently the install action uses `npm install -D`. Yarn support is tracked by https://github.com/Microsoft/TypeScript/issues/19269
