### ISSUE TITLE
It is possible to change the type of the variable

### ISSUE THREAD

**Issue by AlexDEVpro** [Microsoft/TypeScript#21511]
**TypeScript Version:** 2.6.2

**Code:**
```
let stringVariable: string = 'some string';
alert(`typeof stringVariable: ${typeof stringVariable}`); // string.
//stringVariable = 33; // Type '33' is not assignable to type 'string'. Ok...
//stringVariable = 33 as string; // Type 'number' cannot be converted to type 'string'. Ok...
stringVariable = 33 as any; // Now stringVariable is number.
alert(`typeof stringVariable: ${typeof stringVariable}`); // number!
alert(`stringVariable + 11: ${stringVariable + 11}`); // 44
```

**Expected behavior:**
No possibility to change the type of the variable.

**Actual behavior:**
It is possible to change the type of the variable even in strict mode.

**Playground Link:**
[Playground](http://www.typescriptlang.org/play/index.html#src=let%20stringVariable%3A%20string%20%3D%20'some%20string'%3B%0Aalert(%60typeof%20stringVariable%3A%20%24%7Btypeof%20stringVariable%7D%60)%3B%20%2F%2F%20string.%0A%2F%2FstringVariable%20%3D%2033%3B%20%2F%2F%20Type%20'33'%20is%20not%20assignable%20to%20type%20'string'.%20Ok...%0A%2F%2FstringVariable%20%3D%2033%20as%20string%3B%20%2F%2F%20Type%20'number'%20cannot%20be%20converted%20to%20type%20'string'.%20Ok...%0AstringVariable%20%3D%2033%20as%20any%3B%20%2F%2F%20Now%20stringVariable%20is%20number.%0Aalert(%60typeof%20stringVariable%3A%20%24%7Btypeof%20stringVariable%7D%60)%3B%20%2F%2F%20number!%0Aalert(%60stringVariable%20%2B%2011%3A%20%24%7BstringVariable%20%2B%2011%7D%60)%3B%20%2F%2F%2044)

**Comment by RyanCavanaugh** [comment]
This is the intended behavior, not a bug we missed for 5 years...

**Comment by AlexDEVpro** [comment]
Ok, now I understand TypeScript better. It's new to me. Sorry, I was sure it shouldn't be possible but now I know it's not a bug. Thanks for pointing that out!
