### ISSUE TITLE
NPM global install wrong version

### ISSUE THREAD

**Issue by yairopro** [Microsoft/TypeScript#21510]
**Search Terms:** 
 npm global install version 1.0.3.0 

**Code**

```
npm install -g typescript 
// installs typescript...
tsc -v
Version 1.0.3.0
```

**Expected behavior:**
Install lastest stable version of typescript ([actually 2.6 according to the official website](https://www.typescriptlang.org)).

**Actual behavior:**
This command install the version 1.0.3.0.
[See full video here](https://youtu.be/3bgUHtzHB6A) (26 seconds, made at the time of this post).

**Related Issues:**
There's a [question about this on stackoverflow](https://stackoverflow.com/questions/39677437/how-to-update-typescript-to-latest-version-with-npm). But **I consider this problem as an issue as long as the official website says that `npm install -g typsecript` should install the 2.6 version** (see youtube video link above).

**Comment by j-oliveras** [comment]
If you are using Windows, try (from a console, this don't work with powershell):
`where tsc`
This command list all tsc files into path. The first one is the used calling `tsc -v`.

In may case this is the output:
```
C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\tsc.exe
C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\tsc.js
C:\Users\user\AppData\Roaming\npm\tsc
C:\Users\user\AppData\Roaming\npm\tsc.cmd
```

If your output is similar, then npm installs the latest version (currently 2.6.2), but the path uses the tsc from Microsoft SDKs.

**Comment by yairopro** [comment]
I've got the 2 first.
````
$ where tsc
C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\tsc.exe
C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\tsc.js
````

By the way, what are those directories?

**Comment by j-oliveras** [comment]
I think is the typescript installed by Visual Studio 2013 or some other SDK.

**Comment by yairopro** [comment]
I deleted `C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0` directory.
Now `tsc` command isn't found. **But now `npm install -g typescript` installed the correct version 2.6.2!**
And `where tsc` command find the correct directory of npm!

**Comment by RyanCavanaugh** [comment]
It hopefully goes without saying that we don't control the behavior of `npm install` either
