### ISSUE TITLE
Regression: Compiling simple React code, the generated d.ts file cannot be read back in by the compiler

### ISSUE THREAD

**Issue by mmorearty** [Microsoft/TypeScript#21520]
**TypeScript Version:**  2.8.0-dev.20180131

**Search Terms:** 
react
default
unexpected

**Code**

In this simple example, step one of the compilation is to compile `lib.ts`, generating `lib.js` and `lib.d.ts`. Step two is to compile `main.ts` along with the just-generated `lib.d.ts`.

The 2.7.1 compiler (and the `@next` compiler) encounter errors during step two, when reading the `lib.d.ts` file that just got generated a moment earlier. The 2.6.1 compiler does _not_ encounter errors.

lib.ts:

```ts
import * as React from "react";

export interface Props {
}

export default class MyComponent extends React.Component<Props, {}> {
    static create = React.createFactory(MyComponent);
}
```

main.ts:

```ts
// nothing to see here
```

package.json:

```json
{
  "name": "tsctest",
  "version": "1.0.0",
  "description": "demo of possible TypeScript 2.7.1 bug",
  "main": "index.js",
  "scripts": {
    "build": "tsc -d lib.ts && tsc main.ts lib.d.ts"
  },
  "keywords": [],
  "author": "Mike Morearty <mike@morearty.com>",
  "license": "ISC",
  "dependencies": {
    "@types/react": "16.0.36",
    "react": "16.2.0",
    "typescript": "2.7.1"
  }
}
```

Steps to reproduce:

* Put those three files in a dir together
* `npm install`
* `npm run build`

**Expected behavior:**

Successful compilation

**Actual behavior:**

```
lib.d.ts(6,50): error TS1005: '>' expected.
lib.d.ts(6,57): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
lib.d.ts(6,58): error TS1109: Expression expected.
lib.d.ts(7,1): error TS1128: Declaration or statement expected.
```

**Comment by mhegazy** [comment]
@weswigham can you please take a look.
