### ISSUE TITLE
Backslash in reference path causes Visual studio 2013 to drop js in wrong directory

### ISSUE THREAD

**Issue by glaborde** [Microsoft/TypeScript#2152]
Select Redirect Javascript output to directory.
Create ts with reference to another ts using backslash for path.
Build.Look for resulting javascript file in windows explorer.

**Comment by mhegazy** [comment]
I will need more information to be able to reproduce this issue locally. 

here is my setup:

output directory: "out"

```TypeScript
// file1.ts
var f1 = 1;
```

```TypeScript
// file2.ts
/// <reference path="c:\users\mhegazy\documents\visual studio 2015\Projects\TypeScriptHTMLApp3\TypeScriptHTMLApp3\file1.ts" />
var f2 = 2;
```

after build, i see out to include file1.js and file2.js

**Comment by glaborde** [comment]
Hello Mohamed,

sorry for not getting back sooner on this.
I spent a little more time to characterize this problem. We actually had
made two changes to try to fix this problem. One was the backslash. The
other was to move the ts file to the root of the project (which
incidentally is the fix that worked).

The problem is that the reference path is also the relative location to the
resulting js file.
For example, redirecting Javascript output to Resources, if I put my
typescripts in a sub directory (scripts\mystuff), the javascript drops
under: Resources\scripts\mystuff.

By putting the scripts on the root, the resulting javascript drops under
Resources as expected. Forward slash versus backslash doesn't affect this
behavior.

I am looking for a behavior where the compilation outputs are dropped in a
single location irrespective of the relative location of the typescripts.

What do you think?

Guy

**Comment by mhegazy** [comment]
The output folder structure is dependent on the "best common path" of the input. I think what you want is a --projectRoot or --commonSourcePath option to force the compiler to generate outputs to mirror a specific input folder structure.

**Comment by glaborde** [comment]
Hello Mohamed,

what I am looking for is a single output directory (Resources) in which all
the javascripts would be created. No sub directories. What you are
describing is I think the current behavior. The output directory is in
reality the root for the output and not the output directory.

Does that make sense?

Guy

**Comment by mhegazy** [comment]
when you call the compiler with --outDir outputDirectoryPath, it tries to miror the inpyt directory structure under outputDirectoryPath.
The trick here is to figure out the "root" of the input. so if you have this directory structure:
```
folder1
|- a.ts
|- folder2
   |- b.ts
   |-c.ts
```

calling the compiler with ` b.ts c.ts --outDir outputDirectoryPath

**Comment by mhegazy** [comment]
When you call the compiler with --outDir outputDirectoryPath, it tries to mirror the input directory structure under outputDirectoryPath.
The trick here is to figure out the "root" of the input. so if you have this directory structure:
```
folder1
|- a.ts
|- folder2
   |- b.ts
   |- c.ts
```

Calling the compiler with ` b.ts c.ts --outDir outputDirectoryPath`, will result in a common directory of `folder1\folder2` and in turn will generate this output folder structure:
```
outputDirectoryPath
|- b.ts
|- c.ts
```

adding a.ts to the input  ` a.ts b.ts c.ts --outDir outputDirectoryPath`, will result in a making the  common directory of `folder1` and in turn will generate this output folder structure:
```
outputDirectoryPath
|- a.ts
|- folder2
   |- b.ts
   |- c.ts
```

I think what you need, is a way to tell the compiler, regardless of my inputs, always consider `folder1` as my input root, and generate the output accordingly.

**Comment by licinioamendes** [comment]
Would be nice allowing [VS macros for build commands](https://msdn.microsoft.com/en-us/library/c02as0cs.aspx "MSDN Macros for Build Commands").

The result would be something like `$(ProjectDir)outputDirectoryPath` on textbox.

**Comment by mhegazy** [comment]
@licinioamendes i have logged #4109 to track that issue.

**Comment by mhegazy** [comment]
this is addressed by --rootDir: https://github.com/Microsoft/TypeScript/pull/2772
