### ISSUE TITLE
Type parameter defaults can't be used in conjunction with argument defaults

### ISSUE THREAD

**Issue by ViKomprenas** [Microsoft/TypeScript#21521]
**TypeScript Version:**  2.8.0-dev.20180131

**Search Terms:** generic default, parameter default, argument default, incompatible, conflict

**Code:**
```ts
function identity<T = number>(x: T = 4) {
    return x;
}
```

**Expected behavior:** This code compiles and runs as expected; if `T` is changed, 4 is no longer compatible and `x` becomes a required argument; if `x` is changed, `T` is inferred from it as it would be if `x` were required. (Maybe stating the explicit default type on `T` is also unnecessary? But this seems like behavior that should be explicitly opted into...)

**Actual behavior:** Compile-time error; 4 is not assignable to `T`.

**Playground Link:** http://demo.polr.me/y

**Comment by mhegazy** [comment]
The type parameter can always be specified independently.. i.e. this function can be called as `identity<string>()` the result here is assumed to be a `string`, thought it will be `4`.

**Comment by zaclummys** [comment]
If you are expecting only numeric values, use **T extends number** instead of **T = number**.

```ts
function identity<T extends number>(x: T = <T> 4) {
    return x;
}
```

**Comment by ViKomprenas** [comment]
As I noted, @mhegazy, the behavior I'd call intuitive is that if the type parameter is passed explicitly and the default argument isn't compatible with it, the argument becomes required. In any case, I'm not sure whether this is in bug or suggestion territory; feel free to treat it as either if you prefer.

It's worth noting that the real code I got this from is also intending the parameter to infer some verbose nested generics, so stating the generics' content explicitly, while possible, isn't common.
