### ISSUE TITLE
generics in interface definition of iterable data structures. 

### ISSUE THREAD

**Issue by VbifRkbvjd** [Microsoft/TypeScript#2153]
Example:
```javascript
interface AnySet<T> {
    [index:T]:boolean
}
```
will output  *"error TS1023: An index signature parameter type must be 'string' or 'number'"*, which is clearly  not an intended behaviour.

**Comment by mhegazy** [comment]
what other indexer types do you want to use?

**Comment by VbifRkbvjd** [comment]
Actually, I do not want to use other types instead of allowed string|number, but there should be a way to use them both.
Of course I may not specify type at all(using any), or dublicate every function,like
```javascript
set__concat_string_indexer
set__concat_number_indexer
set__remove_string_indexer
set__remove_number_indexer
e.t.c
```
But in my point of view it looks quite ugly.
In addition: this is not working as well: 
   { [index:number|string]:boolean}
Maybe it is not that important, but in my point of view this is the kind of good feauture.   
Thank you.

**Comment by mhegazy** [comment]
This is referenced in #1778.

**Comment by VbifRkbvjd** [comment]
I guess I should close it then
