### ISSUE TITLE
New Website Logo: Huiseoul

### ISSUE THREAD

**Issue by johnwook** [Microsoft/TypeScript#21530]
Please fill the following out:

- Name: Huiseoul
- Homepage url: www.huiseoul.com
- Brand Guidelines/Licensing: nothing
- Logo: https://user-images.githubusercontent.com/2437909/35667613-ae81e834-0771-11e8-840d-7b6ae3af8d1e.png

![image](https://user-images.githubusercontent.com/2437909/35667613-ae81e834-0771-11e8-840d-7b6ae3af8d1e.png)

**Comment by mhegazy** [comment]
Thanks. Added to the site. Should be live next week.
