### ISSUE TITLE
I got one issue  Don't  tell it is logic  error beacuse i have checked.

### ISSUE THREAD

**Issue by keerthivasan12** [Microsoft/TypeScript#21532]
import * as moment from 'moment-timezone';

export class DashboardComponent {

  chart:any=[];

  

constructor( ) {
  this.chart.push({'name': "Clock In",'series':[]})
  this.chart.push({'name': "Clock Out",'series':[]})
  this.chart.push({'name': "Hang Up",'series':[]})
  this.chart.push({'name': "Missed Check Out",'series':[]})
//Note:Don't assign manually this.chart and check beacause you won't get my problem 
for(let i=0;i<=4;i++)
{
  let _id:any={};
  for(let j=0;j<this.chart.length;j++)
  {
    _id.month=moment('2017-09-30 18:30:00').add(i+1, 'month').format("M")
    _id.year=moment('2017-09-30 18:30:00').add(i+1, 'month').format("YYYY")
    _id.name=moment('2017-09-30 18:30:00').add(i+1, 'month').format("MMM/YYYY")
    _id.value=0; 
    this.chart[j].series.push(_id);
  }
}
let databasedata:any=[{count:2,_id:{month:1,week:4,year:2018}}]

let me=this
  for(let i=0;i<(databasedata).length;i++)
  {
    let filter=databasedata[i];
    for(let j=0;j<(me.chart[0].series).length;j++)
    {
     if(me.chart[0].series[j].month==filter._id.month)
     {
        me.chart[0].series[j].value=<number>(filter.count);
     }

    }

   }     
}

// the chart will generate like this.

// this.chart=[{name: "Clock In",series:[
// {month: "10", year: "2017", name: "Oct/2017", value: 0},
// {month: "11", year: "2017", name: "Nov/2017", value: 0},
// {month: "12", year: "2017", name: "Dec/2017", value: 0},
// {month: "1", year: "2018", name: "Jan/2017", value: 0},
// {month: "2", year: "2018", name: "Feb/2017", value: 0}]},
// {name: "Clock Out",series:[
// {month: "10", year: "2017", name: "Oct/2017", value: 0},
// {month: "11", year: "2017", name: "Nov/2017", value: 0},
// {month: "12", year: "2017", name: "Dec/2017", value: 0},
// {month: "1", year: "2018", name: "Jan/2017", value: 0},
// {month: "2", year: "2018", name: "Feb/2017", value: 0}]},
// ]

// i am going to comapare and update value in 0th array this.chart[0]

// after loop i got 

// this.chart=[{name: "Clock In",series:[
// {month: "10", year: "2017", name: "Oct/2017", value: 0},
// {month: "11", year: "2017", name: "Nov/2017", value: 0},
// {month: "12", year: "2017", name: "Dec/2017", value: 0},
// {month: "1", year: "2018", name: "Jan/2017", value: 2},
// {month: "2", year: "2018", name: "Feb/2017", value: 0}]},
// {name: "Clock Out",series:[
// {month: "10", year: "2017", name: "Oct/2017", value: 0},
// {month: "11", year: "2017", name: "Nov/2017", value: 0},
// {month: "12", year: "2017", name: "Dec/2017", value: 0},
// {month: "1", year: "2018", name: "Jan/2017", value: 2},
// {month: "2", year: "2018", name: "Feb/2017", value: 0}]},
// ]

// expected result 

// this.chart=[{name: "Clock In",series:[
// {month: "10", year: "2017", name: "Oct/2017", value: 0},
// {month: "11", year: "2017", name: "Nov/2017", value: 0},
// {month: "12", year: "2017", name: "Dec/2017", value: 0},
// {month: "1", year: "2018", name: "Jan/2017", value: 2},
// {month: "2", year: "2018", name: "Feb/2017", value: 0}]},
// {name: "Clock Out",series:[
// {month: "10", year: "2017", name: "Oct/2017", value: 0},
// {month: "11", year: "2017", name: "Nov/2017", value: 0},
// {month: "12", year: "2017", name: "Dec/2017", value: 0},
// {month: "1", year: "2018", name: "Jan/2017", value: 0},
// {month: "2", year: "2018", name: "Feb/2017", value: 0}]},
// ]

//Note:Don't assign manually this.chart and check beacause you won't get my problem

**Comment by DickvdBrink** [comment]
I'm not sure what the problem is because it isn't obvious from the code you dumped in the post.  So you might want to edit it ;)

Also, I think it is more of a stackoverflow question - it looks more like a question about a library instead of a TypeScript issue?

**Comment by DickvdBrink** [comment]
Difficult to see with the current code formatting, but this isn't a a real TypeScript question and it is better suited for stackoverflow - http://stackoverflow.com/questions/tagged/typescript.

I can't really tell from the question what the problem is but I think you have placed the `let _id:any={};` on the wrong line. 
```
for(let i=0;i<=4;i++)
{
  let _id:any={}; // I think you wanted this in the loop
  for(let j=0;j<this.chart.length;j++)
  {
    // Should be placed here, I think  let _id:any={};
  
    _id.month=moment('2017-09-30 18:30:00').add(i+1, 'month').format("M")
    _id.year=moment('2017-09-30 18:30:00').add(i+1, 'month').format("YYYY")
    _id.name=moment('2017-09-30 18:30:00').add(i+1, 'month').format("MMM/YYYY")
    _id.value=0;
    this.chart[j].series.push(_id);
  }
}
```

**Comment by keerthivasan12** [comment]
sorry i was thought it is typescript reference  error
