### ISSUE TITLE
Support globs in tsconfig.json

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#2154]
Something along the lines of: 
```JSON
{
  "files" : [
    "folder1\\*.ts",
    "folder2\\**.ts"
  ]
}
```

open questions:
- Should it be in files or a separate property
- What is the expected --watch behavior
- Should we add excludes as well (e.g. includes: "*.ts", excludes: "*.d.ts");

**Comment by RichiCoder1** [comment]
Related/duplicate?: https://github.com/Microsoft/TypeScript/issues/1927

**Comment by mhegazy** [comment]
Thanks @RichiCoder1. closing.
