### ISSUE TITLE
esModuleInterop generates different code for "import foo" and "import { default as foo }"

### ISSUE THREAD

**Issue by gustavderdrache** [Microsoft/TypeScript#21541]
**TypeScript Version:**  2.7.1, 2.8.0-dev.20180201

**Search Terms:** default import, interop, esm

**Code**

```ts
import foo from './foo';
import { default as bar } from './bar';

console.log(foo, bar);
```

**Expected behavior:**

Both imports should generate the same `__importDefault(require(...))` calls.

**Actual behavior:**

Only the `import foo` syntax generates a synthetic default import. `import { default as foo }` does not. My understanding of the spec (it looks like the ["Import Forms Mappings to ImportEntry Records" table](https://tc39.github.io/ecma262/#table-40) in §15.2.1.16 is the most relevant citation) is that both of these should access the module's "default" property and thus trigger the same synthetic default import behavior.

```js
var foo_1 = __importDefault(require("./foo"));
var foo_2 = require("./bar"); // ???

console.log(foo["default"], bar["default"]);
```

**Playground Link:** N/A (The playground doesn't appear to be running 2.7 yet)

**Related Issues:** N/A (Couldn't find any)

**Other notes:**

This behavior is present in [Babel 6](https://babeljs.io/repl/#?babili=false&browsers=last%202%20versions%2C%20not%20IE%20%3C%2011&build=&builtIns=false&code_lz=JYWwDg9gTgLgBAMwhAjIqERwOQDoD0SE2A3AFCiSxwDecAJgKYICGArgDbwsDOiyAJjgBfdJhwEipMmQDGEAHY8IHRrg4QA5gAoiKADT8IAgJQkgA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&lineWrap=false&presets=latest%2Cenv&prettier=false&targets=&version=6.26.0&envVersion=1.6.2).

Babel 7, however, generates code in line with my expectations (see [`@babel/babel-helper-module-imports`](https://github.com/babel/babel/blob/v7.0.0-beta.39/packages/babel-helper-module-imports/src/import-builder.js#L65-L66):

```js
var _foo = _interopRequireDefault(require("./foo"));
var _bar = _interopRequireDefault(require("./bar"));

console.log(_foo.default, _bar.default);
```

The module [`@std/esm`](https://www.npmjs.com/package/@std/esm) generates the same code in both cases. I extracted this from the cached files it generated:

```js
let foo; _d40‍.w('./foo',[["default",function(v){foo=v}]]);
let bar; _d40‍.w('./bar',[["default",function(v){bar=v}]]);

console.log(foo, bar);
```

[Rollup](https://rollupjs.org/repl?version=0.55.3&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMGZvbyUyMGZyb20lMjAnZm9vJyUzQiU1Q25pbXBvcnQlMjAlN0IlMjBkZWZhdWx0JTIwYXMlMjBiYXIlMjAlN0QlMjBmcm9tJTIwJ2JhciclM0IlNUNuJTVDbmNvbnNvbGUubG9nKGZvbyUyQyUyMGJhciklM0IlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyY2pzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiUyMmJhciUyMiUzQSUyMmJhciUyMiUyQyUyMmZvbyUyMiUzQSUyMmZvbyUyMiU3RCUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=) generates a different default interop helper (it doesn't look for `__esModule`), but it agrees with Babel 7 and `@std/esm`:

```js
var foo = _interopDefault(require('foo'));
var bar = _interopDefault(require('bar'));

console.log(foo, bar);
```

Webpack also does the same thing, albeit with slightly more verbosity:

```js
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0__foo__ = __webpack_require__(1);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0__foo___default = __webpack_require__.n(__WEBPACK_IMPORTED_MODULE_0__foo__);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_1__bar__ = __webpack_require__(2);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_1__bar___default = __webpack_require__.n(__WEBPACK_IMPORTED_MODULE_1__bar__);

console.log(__WEBPACK_IMPORTED_MODULE_0__foo___default.a, __WEBPACK_IMPORTED_MODULE_1__bar___default.a);
```

**Comment by mhegazy** [comment]
this is really the intended design. but we should reconsider.
