### ISSUE TITLE
Can't extend CustomEvent in 2.7.1

### ISSUE THREAD

**Issue by yebrahim** [Microsoft/TypeScript#21549]
**Search Terms:** extend, CustomEvent, no base constructor

**Code**

```ts
class MyCustomEvent extends CustomEvent {
}
```

**Expected behavior:** I should be able to extend CustomEvent. This worked fine until 2.6.2.

**Actual behavior:** tsc errors out with: "No base constructor has the specified number of type arguments."

**Playground Link:** [Here](http://www.typescriptlang.org/play/index.html#src=class%20NotificationEvent%20extends%20CustomEvent%20%7B%0D%0A%7D).

**Comment by mhegazy** [comment]
It is not a generic type, you need to specify the type `CustomEvent<any>` should get you to where you were in the past.

**Comment by yebrahim** [comment]
I see. What does the type mean here though?

Also, should this be in the breaking changes in release notes? I couldn't find anything about CustomEvent.

**Comment by mhegazy** [comment]
yes. thanks, added it: https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#customevent-is-now-a-generic-type
