### ISSUE TITLE
2.7: strange code generated for calling base methods ((_a = _super.prototype.method).call.call)

### ISSUE THREAD

**Issue by evil-shrike** [Microsoft/TypeScript#21543]
After I recompile my project with TS 2.7.1 I notice pretty strange code in many (but not all) classes.

Before:
```js
    peObjectList.prototype.createCommands = function () {
        var that = this, commands = _super.prototype.createCommands.call(that);
        commands.SelectAll = new core.commands.BoundCommand(that.doSelectAll, that.canSelectAll, that);
        return commands;
    };
```
After:
```js
    peObjectList.prototype.createCommands = function () {
        var that = this, commands = (_a = _super.prototype.createCommands).call.call(_a, that);
        commands.SelectAll = new core.commands.BoundCommand(that.doSelectAll, that.canSelectAll, that);
        return commands;
        var _a;
    };
```

Original TS code:
```ts
protected createCommands(): lang.Map<ICommand> {
    let that = this,
        commands = super.createCommands.call(that);
    commands.SelectAll = new core.commands.BoundCommand(that.doSelectAll, that.canSelectAll, that);
    return commands;
}
```

May I ask why is it needed to call base methods via so strange construct (.call.call)?

I haven't found any info on this mentioned in release notes.

**Comment by rbuckton** [comment]
What version of TypeScript are you migrating from? It seems like this issue has existed for some time.

Also, you shouldn't need to write `commands = super.createCommands.call(that)` as you can just as easily write `commands = super.createCommands()` without needing your own `.call` indirection.

**Comment by evil-shrike** [comment]
@rbuckton I used 2.5.3 before

> Also, you shouldn't need to write commands = super.createCommands.call(that)

yeah, right, it's probably left from "before ts" era (js)
but sometimes the source of such code can be more reasonable:
```ts
unload() {
	super.unload.apply(this, arguments);
}
```

**Comment by rbuckton** [comment]
> ```
> unload() {
>   super.unload.apply(this, arguments);
> }
> ```

This is another case where there exists syntax that can help you:

```
unload(...args) {
  super.unload(...args);
}

// or

unload() {
  super.unload(...arguments);
}
```

For those cases we can do the transformation for you.

**Comment by evil-shrike** [comment]
ok, good

but this one - `super.unload(...arguments);` causes
Error:(224, 19) TS2461: Type 'IArguments' is not an array type.
