### ISSUE TITLE
[Salsa JSDoc] Using express types with require

### ISSUE THREAD

**Issue by ekulabuhov** [Microsoft/TypeScript#21551]
I'm trying to add types from 'express' module in nodejs code. I'm not using any compilers. Below are 3 different ways that I've tried with various levels of success. Is there a right way to do it?

**TypeScript Version:**  VSCode 1.19.3

**Search Terms:** 
Salsa, JSDoc, Express
**Code**
1. Require doesn't work as expected:
```ts
var express = require('express')

/**
 * 
 * @param {express.Request} req 
 * @param {express.Response} res 
 */
function routeHandler(req, res) {
    // req: any
    // res: any
}
```
2. Import is working as expected but not supported by nodejs natively:
```ts
import express from "express";

/**
 * 
 * @param {express.Request} req 
 * @param {express.Response} res 
 */
function routeHandler(req, res) {
    // req: express.Request
    // res: express.Response    
}
```
3. This is the only way I found to make it work. But making a call to express() is not without side effects. I would like to avoid that.
```ts
var express = require('express');
var { request, response } = express();

/**
 * 
 * @param {request} req 
 * @param {response} res 
 */
function routeHandler(req, res) {
    // req: Request
    // res: Response
}
```

**Expected behavior:**
Expecting require to work similarly to import.
**Actual behavior:**
Require is not importing the right types.
**Related Issues:**
https://github.com/Microsoft/TypeScript/issues/14377

**Comment by mhegazy** [comment]
Ideally all should work.

**Comment by DanielRosenwasser** [comment]
* I think that #22161 should fix (1).
* I believe (2) should work with `esModuleInterop` or `allowSyntheticDefaultImport` (which is on by default in VS Code.
* `request` and `response` aren't values at runtime, so I don't think (3) should work.
