### ISSUE TITLE
strictPropertyInitialization is not work at Playground

### ISSUE THREAD

**Issue by Kingwl** [Microsoft/TypeScript#21565]
seems not work at playground

**TypeScript Version:**  2.7.0-dev.201xxxxx

**Search Terms:** 

**Code**

**Expected behavior:**

**Actual behavior:**

**Playground Link:**  

https://www.typescriptlang.org/play/index.html#src=class%20TT%20%7B%0D%0A%0D%0A%7D%0D%0A%0D%0Aclass%20T%20%7B%0D%0A%20%20%20%20c%3A%20number%3B%0D%0A%20%20%20%20b%3A%20TT%3B%0D%0A%20%20%20%20a%3A%20string%3B%0D%0A%7D

**Related Issues:**

**Comment by mhegazy** [comment]
Make sure you refresh your playground. in the console window you should see `ts.version: 2.7.1-insiders.20180127`

**Comment by mhegazy** [comment]
I should add that it is working for me on this sample.

**Comment by Kingwl** [comment]
sorry about that
i disable my cache then it worked
