### ISSUE TITLE
Generic inference incorrect

### ISSUE THREAD

**Issue by charsleysa** [Microsoft/TypeScript#21571]
**TypeScript Version:**  2.7.1

**Search Terms:** inferred generic key type index

**Code**

```ts
interface IColumn<Row, Name extends keyof Row> {
    property?: Name;
    type?: Row[Name];
}

interface ITable<Row> {
    columns: Array<IColumn<Row, keyof Row>> | Array<keyof Row>;
}

declare function createTable<T>(definition: ITable<T>): T;

// Test1
const t1: { hello: string, goodbye: boolean } = createTable({
    columns: ['hello', 'goodbye']
});

// Test2
const t2: { hello: string, goodbye: boolean } = createTable({
    columns: [
        {
            property: 'hello'
        },
        {
            property: 'goodbye'
        }
    ]
});
```

**Expected behavior:**
Both `Test1` and `Test2` should correctly work with correct type inference on both sides.

**Actual behavior:**
Both `Test1` and `Test2` work correctly in TS2.6.2

In TS2.7.1 `Test1` works correctly but is missing type inference on right side (hovering over `createTable` produces:
```ts
function createTable<{
    hello: any;
    goodbye: any;
}>(definition: ITable<{
    hello: any;
    goodbye: any;
}>): {
    hello: any;
    goodbye: any;
}
```

In TS2.7.1 `Test2` does not work at all producing the following error:
```
[ts]
Argument of type '{ columns: ({ property: "hello"; } | { property: "goodbye"; })[]; }' is not assignable to parameter of type 'ITable<{ hello: any; }>'.
  Types of property 'columns' are incompatible.
    Type '({ property: "hello"; } | { property: "goodbye"; })[]' is not assignable to type 'IColumn<{ hello: any; }, "hello">[] | "hello"[]'.
      Type '({ property: "hello"; } | { property: "goodbye"; })[]' is not assignable to type '"hello"[]'.
        Type '{ property: "hello"; } | { property: "goodbye"; }' is not assignable to type '"hello"'.
          Type '{ property: "hello"; }' is not assignable to type '"hello"'.
```

**Playground Link:**  
http://www.typescriptlang.org/play/#src=interface%20IColumn%3CRow%2C%20Name%20extends%20keyof%20Row%3E%20%7B%0D%0A%20%20%20%20property%3F%3A%20Name%3B%0D%0A%20%20%20%20type%3F%3A%20Row%5BName%5D%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20ITable%3CRow%3E%20%7B%0D%0A%20%20%20%20columns%3A%20Array%3CIColumn%3CRow%2C%20keyof%20Row%3E%3E%20%7C%20Array%3Ckeyof%20Row%3E%3B%0D%0A%7D%0D%0A%0D%0Adeclare%20function%20createTable%3CT%3E(definition%3A%20ITable%3CT%3E)%3A%20T%3B%0D%0A%0D%0A%2F%2F%20Test1%0D%0Aconst%20t1%3A%20%7B%20hello%3A%20string%2C%20goodbye%3A%20boolean%20%7D%20%3D%20createTable(%7B%0D%0A%20%20%20%20columns%3A%20%5B'hello'%2C%20'goodbye'%5D%0D%0A%7D)%3B%0D%0A%0D%0A%2F%2F%20Test2%0D%0Aconst%20t2%3A%20%7B%20hello%3A%20string%2C%20goodbye%3A%20boolean%20%7D%20%3D%20createTable(%7B%0D%0A%20%20%20%20columns%3A%20%5B%0D%0A%20%20%20%20%20%20%20%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20property%3A%20'hello'%0D%0A%20%20%20%20%20%20%20%20%7D%2C%0D%0A%20%20%20%20%20%20%20%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20property%3A%20'goodbye'%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%5D%0D%0A%7D)%3B

**Related Issues:**
Possibly
https://github.com/Microsoft/TypeScript/issues/21553
https://github.com/Microsoft/TypeScript/issues/21529

**Comment by zaclummys** [comment]
@charsleysa,
Have you tried to get feedback in a specific forum? stackoverflow.com will give you better and faster feedback for your problem. Check there if it's just a code error.

**Comment by mhegazy** [comment]
Looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/21553

**Comment by charsleysa** [comment]
Current workaround for the issue is to not rely on the inference to build the type so `Test2` becomes

```ts
// Test2
const t2 = createTable<{ hello: string, goodbye: boolean }>({
    columns: [
        {
            property: 'hello'
        },
        {
            property: 'goodbye'
        }
    ]
});
```
