### ISSUE TITLE
Suggestion: Allow union in index signature if all members of union are string or number

### ISSUE THREAD

**Issue by drew-gross** [Microsoft/TypeScript#21570]
This code is currently not allowed:

```typescript
interface I {
    [index: 'a' | 'b']: number;
}
```

Probably because it's pretty much equivalent to this code:

```typescript
interface I {
    a: number;
    b: number;
}
```

However, if the union is actually a type argument, it's not equivalent:

```typescript
interface I<T> {
    [index: T]: number;
}
```

I think this would be useful. Potentially with some extra syntax to help clarify the api, something like:

```typescript
interface I<T: union> {
    [index: T]: number;
}
```

For my specific use case, I am implementing a parsing library, and wish to have an API like this:

```typescript
export type Parser<AstNodeName> = /* Some stuff involving AstNodeName */;

export interface Grammar<AstNodeName> {
    [index: AstNodeName]: Parser<AstNodeName>;
}
```

Which will be used like this:

```typescript
type AstNodes = 'plus' | 'minus';
const myGrammar: Grammar<AstNodes> = {
    'plus': (n: AstNodes) => doSomeStuff(n),
    'minus': (n: AstNodes) => doDifferentStuff(n),
}
```

**Comment by weswigham** [comment]
This is probably a duplicate of #2049, if I understand your request correctly.

**Comment by drew-gross** [comment]
Yep, I think it is.
