### ISSUE TITLE
Conversion to number using unary plus doesn't work properly with null

### ISSUE THREAD

**Issue by zaclummys** [Microsoft/TypeScript#21574]
**TypeScript Version:**  2.8.0-dev.20180202

**Code**

```ts
// Test 1
String(null);

// Test 2
Number(null);

// Test 3
'' + null;

// Test 4
+ null;
```

**Expected behavior:**
All tests must be ok.

**Actual behavior:**
Test 4 isn't ok. Typescript says: _Object is possibly 'null'._

**Playground Link:** https://www.typescriptlang.org/play/index.html#src=%2F%2F%20Test%201%0D%0AString(null)%3B%0D%0A%0D%0A%2F%2F%20Test%202%0D%0ANumber(null)%3B%0D%0A%0D%0A%2F%2F%20Test%203%0D%0A''%20%2B%20null%3B%0D%0A%0D%0A%2F%2F%20Test%204%0D%0A%2B%20null%3B

**Comment by mhegazy** [comment]
https://github.com/Microsoft/TypeScript/issues/7989 tracks the general operator interaction with nullable types.. but we chose to allow `string` + `null|undefined` to enable some debugging scenarios, see https://github.com/Microsoft/TypeScript/issues/7989#issuecomment-224775260

**Comment by andy-ms** [comment]
Related: #20131 -- although that case is requesting the compiler to be *more* strict.

**Comment by zaclummys** [comment]
@mhegazy,
if Typescript doesn't allow ``` + null```, why it's allowed to use ```Number(null)```?

**Comment by mhegazy** [comment]
I think i miss linked this issue to #7989. we should think about this one more time..

**Comment by RyanCavanaugh** [comment]
Related #20754

We like the behavior as-is, inconsistency notwithstanding
