### ISSUE TITLE
[Proposal] Initializer syntax for function types

### ISSUE THREAD

**Issue by AlCalzone** [Microsoft/TypeScript#21572]
Using function types, it's possible to define types for functions with additional properties tacked on, e.g.
```ts
interface fnWithProp {
    (abc: string): string;
    foo: number;
}
```
In order to initialize variables of those types, one currently has to jump through hoops because the naive attempt does not work:
```ts
// Error: 
// Type '(str: any) => any' is not assignable to type 'fnWithProp'.
// Property 'foo' is missing in type '(str: any) => any'.
var abc: fnWithProp = (str) => str;
abc.foo = 7;
```
By explicitly casting the function to the correct type, one can avoid the error, but now TypeScript never checks if foo is assigned (even with `strictPropertyInitialization = true`):
```ts
var abc = ((str) => str) as fnWithProp;
console.log(abc.foo); // undefined
```
A working version looks like this
```ts
var abc = Object.assign(((str) => str), {
    foo: 7,
});
```
but `abc` is now being inferred as the rather cryptic type `((str: any) => any) & { foo: number }`.

As an attempt to solve this problem, I propose an initializer syntax for these kinds of function types, which is similar to the object literal syntax:
```ts
var abc: fnWithProp = {
    (str) => {
        /* do something */
        return str;
    },
    foo: 7,
    /* optional: more properties */
};
```
or an alternative using the `this` keyword for the function body:
```ts
var abc: fnWithProp = {
    this: (str) => {
        /* do something */
        return str;
    },
    foo: 7,
    /* optional: more properties */
};
```

A usage example:
```ts
interface fnWithProp {
    (abc: number): number;
    foo: number;
}

function doSomething(transform: fnWithProp) { 
    return transform(transform.foo + 1);
}

doSomething({ this: (abc) => abc, foo: 7 });
```

**Comment by andy-ms** [comment]
This would fall out of scope of the [design goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals) since it would add new expression-level syntax. Besides, `const obj = { this: str => str };` is already valid syntax.

Anyway, you can combine the interface declaration with `Object.assign` with no problem:
```ts
interface fnWithProp {
    (abc: string): string;
    foo: number;
}
const o: fnWithProp = Object.assign(abc => abc.toUpperCase(), { foo: 1 });
```

**Comment by mhegazy** [comment]
The underlying issue is tracked by https://github.com/Microsoft/TypeScript/issues/15868. there is not an easy/ergonomic way in the language to create one of these functions that have properties. the best we have today is a function and namespace combo:

```ts
interface fnWithProp {
    (abc: string): string;
    foo: number;
}

function f(a: string) { return a; }
namespace f {
    export var foo: number;
}

var abc: fnWithProp = f;
```
