### ISSUE TITLE
Path completions for subdirectories not returned when using compilerOptions.path

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#21589]
**TypeScript Version:**  2.7.1

**Search Terms:** 
- Path intellisense
- Path completions

**Code**
```bash
$ git clone https://github.com/mjbvz/ts-issue-21582
```

1. For a js project:

```
jsconfig.json
src/
  index.js
  keeper.js
  animals/
      cat.js
```

With `jsconfig.json`:

```
{
	"compilerOptions": {
		"module": "commonjs",
		"target": "es2016",
		"baseUrl": ".",
		"paths": {
			"@zoo/*": ["./src/*"]
		}
	},
	"exclude": [
		"node_modules",
		"**/node_modules/*"
	]
}
```

2. In `src/index.js`, type: `import {} from '@zoo/an'`

3. Trigger path intellisense after `@zoo/an`

**Expected behavior:**
Returns a directory completion for `animals`

**Actual behavior:**
Only completions for `index.js` and `keeper.js` returned

**Related**
#21590

**Comment by andy-ms** [comment]
Should be fixed by #21633.
