### ISSUE TITLE
Shorthand property name with an initializer in object assignment pattern does not parse

### ISSUE THREAD

**Issue by JsonFreeman** [Microsoft/TypeScript#2158]
```ts
var x;
({ x = 0 } = { x: 0 });
```
The following does not parse, but it's allowed by section 12.14.5 of the ES6 spec. Specifically, we are failing to parse the production:
```
AssignmentProperty[Yield] :
     IdentifierReference[?Yield] Initializer[In,?Yield]opt
```

**Comment by ahejlsberg** [comment]
This is by design. The left hand side `{ x = 0 }` is required to be a valid object literal before it is re-interpreted as an object assignment pattern.
