### ISSUE TITLE
feature proposal| flagged enum

### ISSUE THREAD

**Issue by exx8** [Microsoft/TypeScript#21598]
In many programming languages flags are used to encode options via parameters to functions.
It provides a way to eliminate the need of multiple option parameters.
My suggestion is to have another feature called "flagged enum".
These special enums will have member that get  auto assign  to the power of 2.
Example:
`flaggedEnum AnimalFlags{HasClaws ,
CanFly 
,EatsFish ,
Endangered
}`

will be as to  call:

`enum AnimalFlags{
    HasClaws       = 1 << 0,
    CanFly         = 1 << 1,
    EatsFish       = 1 << 2,
    Endangered     = 1 << 3
}
`

the different that it will be made automatically of course.

Example of usage can be read here:

https://basarat.gitbooks.io/typescript/docs/enums.html#enums-as-flags

**Comment by RyanCavanaugh** [comment]
This doesn't seem to solve any problems that people aren't comfortably solving today with existing syntax. Not everything needs a sugared form.
