### ISSUE TITLE
playground using inheritance example doesn't run in Edge for some reason

### ISSUE THREAD

**Issue by pgmolloy** [Microsoft/TypeScript#21597]
**TypeScript Version:**  2.7.0-dev.201xxxxx

**Search Terms:** 

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**Expected behavior:**

**Actual behavior:**

**Playground Link:**  

**Related Issues:**

**Comment by DanielRosenwasser** [comment]
I'm not sure if I'm able to reproduce the issue, though I could've sworn I saw something similar the first time I tried.

![image](https://user-images.githubusercontent.com/972891/35765042-570a1d3c-0871-11e8-8ad6-dd5862bcfb2a.png)

Can others give this a shot?

**Comment by j-oliveras** [comment]
Seems it works (the dev-tools errors are not related to typescript):
![ts play edge](https://user-images.githubusercontent.com/15308683/35770815-066367f0-0923-11e8-8cd7-8e31b824f60d.png)

The code is:
```ts
class Greeter {
    greeting: string;
    constructor(message: string) {
        this.greeting = message;
    }
    greet() {
        return "Hello, " + this.greeting;
    }
}

class NewClass extends Greeter {
    constructor(message: string) {
        super("NewClass: " + message);
    }
}
```
