### ISSUE TITLE
Polymorphic this within inferred return types

### ISSUE THREAD

**Issue by jamesknelson** [Microsoft/TypeScript#21596]
**TypeScript Version:**  2.8.0-dev.20180202

**Search Terms:** 

- polymorphic this
- return type inference
- abstract

**Code**

```ts
abstract class Base<Output> {
    get subscriptions() {
        // This should infer its type from the implementation of `this.subscribe`,
        // in the subclass, but instead falls back to `any`.
        return this.subscribe()
    }

    abstract subscribe()

    abstract getOutput(): Output
}

class Component extends Base<{ foo: 1 }> {
    subscribe() {
        return {
            bar: 1
        }
    }

    getOutput() {
        return this.subscriptions
    }
}
```

**Expected behavior:**

This should fail, as the return type of `this.subscribed` within`getOutput()` can be inferred from the implementation of `subscribe`.

Additionally, it is known that the implementation of `subscribe` must come from `Component`, as `subscribe` is an abstract method in the base class.

**Actual behavior:**

It compiles without any warnings.

If the `subscriptions` getter is moved into the subclass, it fails as expected.

**Playground Link:** https://www.typescriptlang.org/play/#src=abstract%20class%20Base%3COutput%3E%20%7B%0D%0A%20%20%20%20get%20subscriptions()%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20this.subscribe()%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20abstract%20subscribe()%0D%0A%0D%0A%20%20%20%20abstract%20getOutput()%3A%20Output%0D%0A%7D%0D%0A%0D%0Aclass%20Component%20extends%20Base%3C%7B%20foo%3A%201%20%7D%3E%20%7B%0D%0A%20%20%20%20subscribe()%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20bar%3A%201%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20getOutput()%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20this.subscriptions%0D%0A%20%20%20%20%7D%0D%0A%7D

**Related Issues:**

None that I could find.

**Comment by DanielRosenwasser** [comment]
I think I see what you're trying to achieve, but in the base class, the type of `subscribe()` is `any`, so this is expected. Does `subscribe()` return a known type that will apply to all instances?

**Comment by jamesknelson** [comment]
Not really, `subscribe` in the subclass is expected to return a query object, from which a resulting type can be inferred, but each subclasses's queries are structured differently.

Would there be any way to mark that an abstract method's return should be inferred from the subclass, similar to how polymorphic `this` returns work?

**Comment by HerringtonDarkholme** [comment]
Does this mean you want automatic type parameter inference in subclass? 

I would argue this feature might be a breaking change. Narrowing implicit any of abstract return type in subclass might also introduce additional performance overhead without users' awareness.

From user's perspective, explicit inference annotation is preferrable. [`infer` type might help if it is expanded to regular type declaration](https://github.com/Microsoft/TypeScript/pull/21496#issuecomment-362861100). 



That said, I haven't seen many other languages do this. [Flow does it, but weirdly](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjGBDAzrsAQQB4AVAPjAG9UwwA7bAWwFMAuMU2sAcxYBcAcsxYAKAJTUwAJwEBXafTD8AFgEtcAOkaswAX1QHMOfGABCYFgA9+LegBMCJEJRp0dLMAF4wARgBMAMyG6ABu2NJg2N4MLEiEEtoiqOGRAEYx9HHmiR7o2JqqGgCSuACaAoT0cKos0gBi8AgA6ixq0vZZpsDAYBhwTAAOajAsuKhphXD1alYs9hOaddJw0uhZSGaJfEIiifzTs-NgPWAIbR1AA). 

For now I think adding another type parameter and explicit annotating is still the best choice.

**Comment by ahejlsberg** [comment]
Now that we have conditional types you can do the following:

```ts
type ReturnType<T> = T extends (...args: any[]) => infer R ? R : never;

abstract class Base {
    get subscriptions(): ReturnType<this["subscribe"]> {
        return this.subscribe();
    }
    abstract subscribe();
}

class Component extends Base {
    subscribe() {
        return {
            bar: 1
        };
    }
}

let x = new Component();
let y = x.subscriptions;  // { bar: number }
```

This works with `typescript@next`. We'll be adding the `ReturnType<T>` type to `lib.d.ts` before 2.8 is released.

**Comment by ahejlsberg** [comment]
You could argue that `this.subscribe()` should have an inferred type of `ReturnType<this["subscribe"]>`, but it isn't clear that you want this behavior by default. Plus it would be a breaking change. So I'm going to tag this as working as intended.

**Comment by jamesknelson** [comment]
These conditional and inferred types look amazing. Thanks for pointing them out!

@ahejlsberg your example *almost* works for me, but I'd also like to be able to access `this.subscriptions` within subclasses:

```typescript
type ReturnType<T> = T extends (...args: any[]) => infer R ? R : never;

abstract class Base {
    get subscriptions(): ReturnType<this["subscribe"]> {
        return this.subscribe();
    }
    abstract subscribe();
}

class Component extends Base {
    subscribe() {
        return {
            bar: 1
        };
    }

    render() {
        let subs = this.subscriptions
        let x = subs.bar // Property 'bar' does not exist on type 'ReturnType<this["subscribe"]>'
    }
}

let x = new Component();

// This works
let y = x.subscriptions;  // { bar: number }
```

Is this the expected behavior?
