### ISSUE TITLE
Union Type With Function Return of Sub-Union Type Gives Error

### ISSUE THREAD

**Issue by EToreo** [Microsoft/TypeScript#2160]
I honestly don't have the vocabulary to explain this correctly, so please bear with me...

The example provided is giving me an "error TS2349: Cannot invoke an expression whose type lacks a call signature." error. 

It is my understanding that the `TInstance` from `find(): PromiseT<TInstance>;` should be a union of A.Instance, B.Instance, and C.Instance... but does not appear to be - and therefor an error is being issued.  Is the error incorrect, or am I somehow violating the rules of Unions?

Any help is greatly appreciated,
-Eric

[Playground Example](http://www.typescriptlang.org/Playground#src=%0Amodule%20def%20%7B%0A%0A%20%20%20interface%20PromiseT%3CT%3E%7B%0A%20%20%20%20%20%20then(onFulfilled%3F%3A%20(result%3F%3A%20T)%20%3D%3E%20void)%3B%0A%20%20%20%7D%0A%0A%20%20%20export%20interface%20Model%3CTInstance%2C%20TPojo%3E%7B%0A%20%20%20%20%20%20find()%3A%20PromiseT%3CTInstance%3E%3B%0A%20%20%20%7D%0A%0A%20%20%20export%20interface%20Instance%3CTInstance%2C%20TPojo%3E%20%7B%0A%20%20%20%20%20%20Model%3A%20Model%3CTInstance%2C%20TPojo%3E%3B%0A%20%20%20%7D%0A%7D%0A%0Amodule%20A%0A%7B%0A%20%20%20export%20interface%20Pojo%0A%20%20%20%7B%0A%20%20%20%20%20%20Id%3F%3Anumber%3B%0A%09%20%20Word%3F%3A%20string%3B%0A%20%20%20%7D%0A%0A%20%20%20export%20interface%20Instance%20extends%20def.Instance%3CInstance%2C%20Pojo%3E%2C%20Pojo%20%7B%20%7D%0A%0A%20%20%20export%20interface%20Model%20extends%20def.Model%3CInstance%2C%20Pojo%3E%7B%0A%09%20%20%20customFunction()%20%3A%20void%3B%0A%20%20%20%7D%0A%7D%0A%0Amodule%20B%0A%7B%0A%20%20%20export%20interface%20Pojo%0A%20%20%20%7B%0A%20%20%20%20%20%20Id%3F%3Anumber%3B%0A%20%20%20%20%20%20%2F%2FClassId%3F%3Anumber%3B%0A%20%20%20%20%20%20AttributeId%3F%3Anumber%3B%0A%20%20%20%7D%0A%0A%20%20%20export%20interface%20Instance%20extends%20def.Instance%3CInstance%2C%20Pojo%3E%2C%20Pojo%20%7B%20%7D%0A%0A%20%20%20export%20interface%20Model%20extends%20def.Model%3CInstance%2C%20Pojo%3E%7B%0A%20%20%20%7D%0A%7D%0A%0Amodule%20C%0A%7B%0A%20%20%20export%20interface%20Pojo%0A%20%20%20%7B%0A%20%20%20%20%20%20Id%3F%3Anumber%3B%0A%20%20%20%20%20%20%2F%2FRangeMin%3F%3Anumber%3B%0A%20%20%20%20%20%20%2F%2FRangeMax%3F%3Anumber%3B%0A%20%20%20%20%20%20Overwritable%3F%3Aboolean%3B%0A%20%20%20%7D%0A%0A%20%20%20export%20interface%20Instance%20extends%20def.Instance%3CInstance%2C%20Pojo%3E%2C%20Pojo%20%7B%20%7D%0A%0A%20%20%20export%20interface%20Model%20extends%20def.Model%3CInstance%2C%20Pojo%3E%7B%0A%20%20%20%7D%0A%7D%0A%0Atype%20Union%20%3D%20A.Model%20%7C%20B.Model%20%7C%20C.Model%3B%0A%0Afunction%20breakIt(model%3A%20Union)%0A%7B%0A%20%20%20model.find().then((myModel)%20%3D%3E%0A%20%20%20%7B%0A%20%20%20%7D)%3B%0A%7D%0A%0Avar%20models%3A%20Array%3CUnion%3E%20%3D%20%5B%5D%3B%0A%0Amodels.forEach((model)%20%3D%3E%0A%7B%0A%20%20%20breakIt(model)%3B%0A%7D)%3B%0A)

**Comment by danquirk** [comment]
If you remove ```Pojo``` from the extends list then the error goes away.

**Comment by EToreo** [comment]
The `def` module is an extremely simplified version of sequelize.d.ts from https://github.com/borisyankov/DefinitelyTyped/blob/master/sequelize/sequelize.d.ts

So I can't take it away.  Even if I could, I am pretty sure it is vital to the typing of the returned objects from sequelize.

**Comment by EToreo** [comment]
Also, if you do remove the Pojo extend and then add a `customFunction2()` after line 43 then the error comes back.

**Comment by JsonFreeman** [comment]
This is by design according to the spec. The type returned by the find function is
```ts
PromiseT<A.Instance> | PromiseT<B.Instance> | PromiseT<C.Instance>
```
It is a union type, as you pointed out. Now ideally, this would be equivalent to
```ts
PromiseT<A.Instance | B.Instance | C.Instance>
```
because you would think that you can "factor out" the PromiseT, and put the union in the type argument. Sadly, we do not have this axiom in our language. Ideally, we would be able to see that PromiseT only uses its T once, and therefore it can be factored out.

Now look at section 3.10.1 of the spec, the bullet about apparent call signatures of a union type:
> If each type in U has apparent call signatures and the sets of apparent call signatures are identical ignoring return types, U has the same set of call signatures, but with return types that are unions of the return types of the respective apparent call signatures from each type in U.

Observe that the three constituents have call signatures that are not "identical ignoring return types", because they each use T and the T is different in each one. So this rule causes the call signature to be obliterated. This is related to #1442, but it's not clear what to do about it.

These two language limitations are related I think. Although I'm not sure what we can do about it.
