### ISSUE TITLE
【wiki】Constant-named properties example is incomplete

### ISSUE THREAD

**Issue by michaeljota** [Microsoft/TypeScript#21600]
**Expected behavior:**
```
export const SERIALIZE = Symbol("serialize-method-key");

export interface Serializable {
    [SERIALIZE](obj: {}): string;
}
```
**Actual behavior:**

export const SERIALIZE = Symbol("serialize-method-key");

export interface  { // Missing interface name
    [SERIALIZE](obj: {}): string;
}

**Comment by mhegazy** [comment]
Thanks!
