### ISSUE TITLE
Give detailed error message on `for-of` of iterators without downlevelIteration

### ISSUE THREAD

**Issue by weswigham** [Microsoft/TypeScript#21617]
When someone writes code like this:
```ts
const strSet: Set<string> = new Set()
strSet.add('Hello')
strSet.add('World')
for (const str of strSet) {
  console.log(str)
}
```
and gets the error
```
Type 'Set<string>' is not an array type of a string type.
```
we end up with a lot of people opening issues like #21601. We should improve this error message to be more helpful. If the target of the `for-of` is assignable to the iterator interface type (and that type is available), the error message should be changed to read something along the lines of:
```
Type 'Set<string>' is not an array type of a string type. Use compiler option '--downlevelIteration' to allow iterating of iterators.
```

**Comment by DanielRosenwasser** [comment]
Should it be "array type *or* a string type"?

**Comment by DanielRosenwasser** [comment]
Also, I'd generally avoid using the word "transpile" in error messages if possible.

**Comment by aluanhaddad** [comment]
The other missing piece here is not knowing that you need to specify things like `--lib dom.iterable` for it to work with node lists and such.

**Comment by isc30** [comment]
is someone doing this? I can take care

**Comment by mpsijm** [comment]
I'm currently fixing this issue. I seem to have the generating of the error working, after I have updated the tests, I'll open a PR.
