### ISSUE TITLE
[Bug] Type guarding fails.

### ISSUE THREAD

**Issue by zheeeng** [Microsoft/TypeScript#21623]
**TypeScript Version:**  2.6.2

**Code**

```ts
declare const o: {
    records?: string[]
}

const newRecords = o.records &&
    o.records.map((record, i) => record + (o.records.length === i) ? '' : ',')
```

**Expected behavior:**

`o.records` is safe to using `length` property.

**Actual behavior:**

warning: 
```
Object is possibly 'undefined'.
(property) records: string[] | undefined
```

**Playground Link:** 
[playground](http://www.typescriptlang.org/play/index.html#src=declare%20const%20o%3A%20%7B%0D%0A%20%20%20%20records%3F%3A%20string%5B%5D%0D%0A%7D%0D%0A%0D%0Aconst%20newRecords%20%3D%20o.records%20%26%26%0D%0A%20%20%20%20o.records.map((record%2C%20i)%20%3D%3E%20record%20%2B%20(o.records.length%20%3D%3D%3D%20i)%20%3F%20''%20%3A%20'%2C'))

Note: enable strict mode is required for reproducing.

**Related Issues:**

**Comment by aluanhaddad** [comment]
This is expected. It happens because the language doesn't know when the closure will be called.

There is a detailed explanation in https://github.com/Microsoft/TypeScript/issues/9998

**Comment by mhnewsuk** [comment]
This behaviour can be understood by looking at the following example:
```
declare const o: {
    records?: string[]
}

const newRecords = o.records &&
    o.records.map((record, i) => record + (o.records.length === i) ? '' : ',')

function foo(records: any[] | null) {
    if (records) {
        records.map((record, i) => record + (records.length === i) ? '' : ',')
    }
}
```

Then, keep in mind that properties on objects can change. The closure only has a reference to `o`, not `records`. You could have implemented `o.records` as a getter which deletes itself from `o` after the first time it has been evaluated. Then `o.records` would be undefined.

**Comment by mhnewsuk** [comment]
@RyanCavanaugh I don't think this is a bug. In the function `foo`, there is no way anything else could change records, so it's safe for the closure to rely on a type guard that executed before the closure was formed. In the author's original example, there are other things which could come into play, so it's not safe to rely on it.

**Comment by zheeeng** [comment]
@mhnewsuk If we have to consider mutation getter, many type analysis will be broken. Assuming o.records delete itself, the .map method is also unreliable like below:

[playground](http://www.typescriptlang.org/play/index.html#src=let%20o%3A%20%7B%20records%3F%3A%20string%5B%5D%20%7D%20%3D%20%7B%0D%0A%20%20%20%20get%20records()%20%7B%0D%0A%20%20%20%20%20%20%20%20delete%20o.records%0D%0A%20%20%20%20%20%20%20%20return%20%5B'42'%5D%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aconst%20newRecords%20%3D%20o.records%20%26%26%0D%0A%20%20%20%20o.records.map((record%2C%20i)%20%3D%3E%20record%20%2B%20(o.records.length%20%3D%3D%3D%20i)%20%3F%20''%20%3A%20'%2C'))

There is a runtime error.

**Comment by RyanCavanaugh** [comment]
The issue is not getters, the issue is that we don't know that the callback is immediately executed. An isomorphic example is this:
```ts
function mapLater(arr: any[], cb: (x: any) => void) {
    window.setTimeout(() => arr.map(cb), 100);
}

declare const o: {
    records?: string[]
}

if (o.records) {
    mapLater(o.records, () => o.records.length);
}
o.records = undefined;
```
which would crash

**Comment by mhnewsuk** [comment]
@zheeeng @RyanCavanaugh Yep I understand.

However, I was thinking more along the lines of:
```
if (x !== undefined) {
    // x is definitely not undefined
}
```
versus
```
if (x.a !== undefined) {
    // x.a might be undefined
}
```

**Comment by RyanCavanaugh** [comment]
If you captured `o.records` into a `const` then there'd be no error because we know it's not mutated later. See the linked issue above for much more details.
