### ISSUE TITLE
Suggestion: import & export * as name from module in one line

### ISSUE THREAD

**Issue by bluelovers** [Microsoft/TypeScript#21629]
**TypeScript Version:**  2.7.0-dev.201xxxxx

**Search Terms:** 

**Code**

hope can `export * as name from module`
without write

**when we wanna use path module too**

```ts
import * as path from 'path';
export { path };
```

**Expected behavior:**

```ts
export * as path from 'path';

path.join(__dirname, '123');
```

**Actual behavior:**

```ts
import * as path from 'path';
export { path };

path.join(__dirname, '123');
```

**Playground Link:**  

**Related Issues:**

**Comment by andy-ms** [comment]
This would fall out of scope of the [design goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals) since it would change the behavior of ES6 modules.

**Comment by DanielRosenwasser** [comment]
This was a proposal https://github.com/tc39/proposal-export-ns-from, but I don't see it on the active proposals page. Marking this as a duplicate of #4813.
