### ISSUE TITLE
lib.es2017.typedarrays.d.ts not found when using 2.7.1 via NuGet

### ISSUE THREAD

**Issue by BigForNothing** [Microsoft/TypeScript#21643]
**TypeScript Version:**  2.7.1 via NuGet

**Search Terms:** lib.es2017.typedarrays

**Code**

tsconfig.json: 
```json
"lib": [ "dom", "dom.iterable", "es2017" ]
```

**Expected behavior:**
Should compile file.
**Actual behavior:**
Severity	Code	Description	Project	File	Line	Suppression State
Error	TS6053	(TS) File 'xxx/packages/Microsoft.TypeScript.MSBuild.2.7.1/tools/tsc/lib.es2017.typedarrays.d.ts' not found.	

I've installed both Microsoft.TypeScript.Compiler and Microsoft.TypeScript.MSBuild via NuGet. Both versions are 2.7.1. Neither include `lib.es2017.typedarrays.d.ts`.

I checked `packages\Microsoft.TypeScript.MSBuild.2.7.1\tools\tsc` and `packages\Microsoft.TypeScript\.Compiler.2.7.1\tools` and neither include `lib.es2017.typedarrays.d.ts`.

**Comment by mhegazy** [comment]
Should be fixed in the next 2.7.2 release.
