### ISSUE TITLE
/// <reference types /> comment emitted for imported module

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#21642]
Run this:

```sh
git clone https://github.com/FormidableLabs/urql
cd urql
yarn
yarn build-types
cat ./types/components/client.d.ts
```

The first line contains a `/// <reference types="react" />` even though React is clearly imported.

**Expected**: No comment
**Actual**: Comment

**Comment by aluanhaddad** [comment]
Related to https://github.com/Microsoft/TypeScript/issues/19874?

**Comment by mhegazy** [comment]
thanks. indeed a duplicate.
