### ISSUE TITLE
Find-all-references fails with esModuleInterop

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#21641]
**TypeScript Version:**  master

**Code**

```ts
// @esModuleInterop: true

// @Filename: /abc.d.ts
////declare module "a" {
////    export const [|x|]: number;
////}

// @Filename: /b.ts
////import a from "a";
////a.[|x|];

verify.rangesReferenceEachOther();
```

@weswigham Any idea why the two `x` aren't the same symbol?

**Comment by weswigham** [comment]
`getTypeWithSyntheticDefaultImportType` uses `getSpreadType` where it can - I imagine this is because `getSpreadType` in `getNonReadonlySymbol` for a `const` explicitly creates new symbols for each member without setting `.target`. Maybe a simple fix?
