### ISSUE TITLE
White-space policy — editorconfig

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#2166]
I just tried to make a contribution to Typescript I just noticed a lot of white space issues in my git diff. Since I run an extension and set it to make windows's new lines in line endings and it also trim any spaces at the ending. I just noticed that the diff exploded for me.

Maybe you should add `.editorconfig` and `.gitattributes` files?

http://editorconfig.org/

**Comment by danquirk** [comment]
Strange, we actually had someone add .editorconfig for us in #961 but now I don't see it in our repo.

**Comment by DanielRosenwasser** [comment]
We reverted it along with a .gitattributes file because it wreaked a bit of havoc in our tests. If we have another .editorconfig file, it cannot affect the way any files within the `tests` directory are written by editors.

**Comment by tinganho** [comment]
@DanielRosenwasser does adding a directory path in `.editorconfig` solves that problem?

```
[src/**.ts, ]
indent_style = space
indent_size = 2
```

**Comment by DanielRosenwasser** [comment]
That would probably work fine, feel free to send a PR. I'd also account `.json` files (4 spaces as well) and for all files in `scripts` too.

**Comment by CyrusNajmabadi** [comment]
I'm fine with this, as long as it only affects editors, and does not affect how the source control system itself handles files as they go/in of source control
