### ISSUE TITLE
HTMLSlotElement is not suggested by querySelector(All) / createElement

### ISSUE THREAD

**Issue by e111077** [Microsoft/TypeScript#21669]
**TypeScript Version:**  2.7.0-dev.201xxxxx

**Search Terms:** slot querySelector HTMLSlotElement

**Code**

```ts
const slot: HTMLSlotElement = document.createElement('slot');
```

**Expected behavior:**
No Error

**Actual behavior:**
`Type 'HTMLElement' is not assignable to type 'HTMLSlotElement'. Property 'name' is missing in type 'HTMLElement'`

**Playground Link:**  
https://www.typescriptlang.org/play/#src=const%20slot%3A%20HTMLSlotElement%20%3D%20document.createElement('slot')%3B

**Related Issues:**
#8114

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.
