### ISSUE TITLE
interface  problem

### ISSUE THREAD

**Issue by spitWind** [Microsoft/TypeScript#21666]
**TypeScript Version:**  2.7.0-dev.201xxxxx

**Search Terms:** 

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**Expected behavior:interface can't Show

**Actual behavior:  Can not be marked as interface ; interface can't be  view 
**Playground Link:**  

**Related Issues: such as  @type/mongodb 
An object of type Collection; but Collection is a interface ; it  can't not be propmt

**Comment by spitWind** [comment]
This seems to be repaired

**Comment by spitWind** [comment]
Someone looked down on this issue http://cnodejs.org/topic/5a759ccb5e20f00d1427fec9#5a76f754cb27e8121481a332

**Comment by RyanCavanaugh** [comment]
Please provide a complete report when logging issues.
