### ISSUE TITLE
Class properties initialize sequence problem when inheritance 

### ISSUE THREAD

**Issue by ayman-alkom** [Microsoft/TypeScript#21668]
This problem only occurs on the constructor where the property take the default value always  from Up Model and not from the Sub Model

**Code**

```ts


class Model {
    
    idAttr: string = 'id';

    name: string;

    constructor(name: string) {
        this.name = name;
        console.log(this.name, this.idAttr);
    }

    getId() {
        console.log('getId: ', this.name, this.idAttr);
    }
}

class MongoModel extends Model {
    idAttr: string = '_id';
}


let model: Model = new Model('Model Object');
let mModel: MongoModel = new MongoModel('MongoModel Object');
model.getId();
mModel.getId();

```

**Expected behavior: console output** 

> Model Object id
> **MongoModel Object _id**
> getId:  Model Object id
> getId:  MongoModel Object _id

**Actual behavior: console output**

> Model Object id
> **MongoModel Object id**
> getId:  Model Object id
> getId:  MongoModel Object _id

**Playground Link:**  
[see typescriptlang.org/play ](https://www.typescriptlang.org/play/#src=%0D%0Aclass%20Model%20%7B%0D%0A%20%20%20%20%0D%0A%20%20%20%20idAttr%3A%20string%20%3D%20'id'%3B%0D%0A%0D%0A%20%20%20%20name%3A%20string%3B%0D%0A%0D%0A%20%20%20%20constructor(name%3A%20string)%20%7B%0D%0A%20%20%20%20%20%20%20%20this.name%20%3D%20name%3B%0D%0A%20%20%20%20%20%20%20%20console.log(this.name%2C%20this.idAttr)%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20getId()%20%7B%0D%0A%20%20%20%20%20%20%20%20console.log('getId%3A%20'%2C%20this.name%2C%20this.idAttr)%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aclass%20MongoModel%20extends%20Model%20%7B%0D%0A%20%20%20%20idAttr%3A%20string%20%3D%20'_id'%3B%0D%0A%7D%0D%0A%0D%0A%0D%0Alet%20model%3A%20Model%20%3D%20new%20Model('Model%20Object')%3B%0D%0Alet%20mModel%3A%20MongoModel%20%3D%20new%20MongoModel('MongoModel%20Object')%3B%0D%0Amodel.getId()%3B%0D%0AmModel.getId()%3B%0D%0A)
**Related Issues:**

**Comment by ayman-alkom** [comment]
I know we can solve this problem someway, but I wonder if this design have to work or not

**Comment by mhegazy** [comment]
This is the expected initialization order. the derived instance properties are not set untill the base class constructor has executed. see https://github.com/Microsoft/TypeScript/issues/1617

**Comment by RyanCavanaugh** [comment]
https://stackoverflow.com/questions/43595943/why-are-derived-class-property-values-not-seen-in-the-base-class-constructor

**Comment by ayman-alkom** [comment]
thanks for the replay
