### ISSUE TITLE
Format removes space between conditional and array destructure

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#21675]
From https://github.com/Microsoft/vscode/issues/42995

**TypeScript Version:**  2.8.0-insiders-2018

**Search Terms:** 
- Format
- array destructure 

**Code**

```js
let a,b;
if (true) [a, b] = [1, 2];
```

Run format

**Expected behavior:**
No change

**Actual behavior:**
Space removed between conditional and destructure

```js
let a,b;
if (true)[a, b] = [1, 2];
```

**Comment by mhegazy** [comment]
Looks like a missing rule. PRs welcomed.

**Comment by amitdey1987** [comment]
if this is up for grabs, can I take this up?

**Comment by mhegazy** [comment]
it is all yours.

**Comment by grubeeric** [comment]
@amitdey1987 - i'm sorry i didn't see you take this and opened #21859

**Comment by mhegazy** [comment]
thanks @grubeeric!
