### ISSUE TITLE
Having trouble using definitions from another file with JS and JSDoc

### ISSUE THREAD

**Issue by jcreamer898** [Microsoft/TypeScript#21678]
**TypeScript Version:**  2.6.2 from VSCode

**Search Terms:** 
augment globals jsdoc external file

**Code**

```ts
// globals.d.ts
declare global {
  type ListComponentProps = {
    /* .. */
  }
}

// list.jsx
/**
 * Renders a list of pois
 * @augments React.Component<ListComponentProps, ListComponentState>
 */
export default class ListComponent extends React.Component {
}
```

**Expected behavior:**
I want to have external types/interfaces so that in list.jsx, I don't have to do a bunch of @typedef comments.

**Actual behavior:**
Get an error that says... [ts] Augmentations for the global scope can only be directly nested in external modules or ambient module declarations.

As a side note... if I import something in `globals.d.ts`, that error goes away. So, just really trying to understand here what the appropriate way to have a file full of definitions that I can use in other components should be.

**Playground Link:**  

**Related Issues:**

**Comment by andy-ms** [comment]
You don't need to write `declare global` if your file is *already* global -- you could just start writing `type ListComponentProps` directly. If you add an import it stops being global, and then you *do* need `declare global`.

**Comment by jcreamer898** [comment]
Ok, strange, it didn't _seem_ to work when I didn't have the declare global, but I'll mess with it again.
