### ISSUE TITLE
Don't unnecessarily provide replacementSpan in path completions

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#21680]
Path completions often provide replacementSpan even when it is unnecessary since it's the current identifier that's being replaced.

**Comment by mhegazy** [comment]
Ideally the API would always provide a replacement span and save the host the work to recompute it. we just did not do that in the past cause we had a part in VS that knew how to compute the span. that said, i am not sure what is better now, leave it as is (i.e. do not return the span if it is an identifier, or return the span all the time, or just return it for string completions)..

**Comment by mhegazy** [comment]
//cc @mjbvz for feedback as well.

**Comment by mjbvz** [comment]
Yes I don't think removing the replacement span would cause any problems on our side but it also does not seem to hurt anything for us currently
