### ISSUE TITLE
Synchronous calls to nullable types should fail strictNullChecks

### ISSUE THREAD

**Issue by knpwrs** [Microsoft/TypeScript#21685]
**TypeScript Version:**  2.7.0-dev.201xxxxx

**Search Terms:** nullable synchronous strictNullChecks

**Code**

```ts
class Bar {
    methodA(fn) {
        console.log('Method A');
        fn();
    }
    methodB() {
        console.log('Method B');
    }
}

class Foo {
    api: null | Bar = new Bar();
    methodC() {
        if (this.api) {
            this.api.methodA(() => {
                this.api = null
            });
            this.api.methodB();
        }
    }
}

new Foo().methodC();
```

**Expected behavior:**

`this.api.methodB()` should fail type checks with `Object is possibly null`. The problem is that even when doing synchronous sequential calls any number of things can happen that null out `this.api`. Flow catches this and forces you to check every call to methods on `this.api` separately. A workaround I've used there is to do the following:

```js
const { api } = this;
if (api) {
  api.methodA(/* ... */);
  api.methodB();
}
```

In that case, even if `this.api` is nulled out, you still have a valid, non-null reference.

**Actual behavior:**

Typescript doesn't make any complaints, even with strict null checking turned on, and the code crashes at runtime.

**Playground Link:** https://www.typescriptlang.org/play/index.html#src=class%20Bar%20%7B%0D%0A%20%20%20%20methodA(fn)%20%7B%0D%0A%20%20%20%20%20%20%20%20console.log('Method%20A')%3B%0D%0A%20%20%20%20%20%20%20%20fn()%3B%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20methodB()%20%7B%0D%0A%20%20%20%20%20%20%20%20console.log('Method%20B')%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aclass%20Foo%20%7B%0D%0A%20%20%20%20api%3A%20null%20%7C%20Bar%20%3D%20null%3B%0D%0A%20%20%20%20methodC()%20%7B%0D%0A%20%20%20%20%20%20%20%20if%20(this.api)%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20this.api.methodA(()%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20this.api%20%3D%20null%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D)%3B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20this.api.methodB()%3B%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Anew%20Foo().methodC()%3B

**Related Issues:** None that I could find.

**Comment by RyanCavanaugh** [comment]
The false positive rate on this is extremely high, e.g. Flow considers this code an error:
```ts
function f(x: { y: number | string }) {
    if (typeof x.y === "number") {
        console.log("it's a number");
        x.y.toFixed(); // UNSAFE
    }
}
```
Since the vast majority of code is not self-hostile we consider this to be an acceptable trade-off. #11498 would fix the specific case where a callback is *visibly* creating side effects.

**Comment by RyanCavanaugh** [comment]
Also note that the `this.api = null` line is a red herring if comparing to Flow - it errors either way, yet fails to detect this error:
```ts
let m = 0;
mut();
f(m); // f observes x = 4

function mut() {
  m += 4;
}

declare function f(x: 0 | 1): void;
```

**Comment by knpwrs** [comment]
`this.api = null` isn't meant to be a practical example, it's just intended to make the problem extremely obvious. The root problem is that there is a series of events that can occur that would make `this.api` `null`.

Comparing to flow, just for the sake of a concrete example, the following is _not_ an error:

```js
if (this.api) {
  this.api.methodA();
}
```

But the following is:

```js
if (this.api) {
  this.api.methodA();
  this.api.methodB(); // Only this line causes an error
}
```

**Comment by RyanCavanaugh** [comment]
Right; we consider "Every function might mutate any possibly-referenced object" to be too strict to be a net positive, even though it's the conservatively sound assumption.

**Comment by knpwrs** [comment]
Well, the flag _is_ called _strict_ null checks. 😉
