### ISSUE TITLE
Debug Failure: no message - TS 2.7.1

### ISSUE THREAD

**Issue by deltakosh** [Microsoft/TypeScript#21701]
**Search Terms:** 
Debug failure, checkUnusedClassMembers 

**Code**

It is tough to provide code as the entire repo is failing and we have no error

![image](https://user-images.githubusercontent.com/1306056/35886556-4407d620-0b46-11e8-9715-2bd5dfab98b1.png)

**ts**
Please clone this repo: https://github.com/BabylonJS/Babylon.js
Go to /tools/gulp
npm install
gulp

**Expected behavior:**
Compiling should work

**Actual behavior:**
We are receiving a "Debug failure" error with no more detail. Same code works with TS 2.6.2

**Comment by mhegazy** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/21491. Fix should be available in `typescript@next` today and in the upcoming `typescript@2.7.2` release in the next 2 weeks.

For workarounds on 2.7.1, the crash is triggered by having `;` after a method or accessor declaration in a class body, removing these should avoid the crash. See https://github.com/Microsoft/TypeScript/issues/21491#issuecomment-362390885 for more details.

**Comment by deltakosh** [comment]
Sorry for the duplicate, was not able to find it (Should improve my search skills)
