### ISSUE TITLE
Formatting of conditional types

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#21716]
**TypeScript Version:**  2.7.0-dev.20180206

**Expected behavior:**

```ts
type Diff<T, U> = T extends U ? never : T;
```

**Actual behavior:**

```ts
type Diff<T, U> = T extends U?never: T;
```

**Related Issues:**

**Comment by mhegazy** [comment]
@lankaapura wanna pick up this one as well?

**Comment by lankaapura** [comment]
@mhegazy sure 👍

**Comment by lankaapura** [comment]
Created PR #21762, let me know if there any changes required.
