### ISSUE TITLE
Default enum value in param

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#2171]
I'm just wondering why there can't be a enum value as a default param value? 
```typescript
function(x: enumValue.X) {
  // do something
}
```

The error message I got is also a bit strange. Can't find name `enumValue`.

**Comment by danquirk** [comment]
You need to use ```=``` for default values. ```:``` is for type annotations which is why you're getting an error here, it's trying to find a type named enumValue.X, which doesn't exist. This works:

```ts
enum E {
	X
}
function foo(x = E.X) {
}
```
