### ISSUE TITLE
Cannot extend generic type with a mixin

### ISSUE THREAD

**Issue by dpogue** [Microsoft/TypeScript#21710]
There appears to be no way to extend a generic type using in a mixin-style pattern, because the type arguments cannot be passed through.

**TypeScript Version:**  2.7.1

**Search Terms:** base constructor, type arguments

**Code**

```ts
function subclass<T>(klasstype : T) : T {
  // This is our mixin, but for demo purposes just return the class
  return klasstype;
}

class DerivedPromise<T> extends subclass(Promise) { }
```

**Expected behavior:**
A class that extends Promise.

**Actual behavior:**
TS2508: No base constructor has the specified number of type arguments.

**Playground Link:**  
[Here](http://www.typescriptlang.org/play/index.html#src=function%20subclass%3CT%3E(klasstype%20%3A%20T)%20%3A%20T%20%7B%0A%20%20%2F%2F%20This%20is%20our%20mixin%2C%20but%20for%20demo%20purposes%20just%20return%20the%20class%0A%20%20return%20klasstype%3B%0A%7D%0A%0Aclass%20DerivedPromise%3CT%3E%20extends%20subclass(Promise)%20%7B%20%7D)

**Comment by DanielRosenwasser** [comment]
TypeScript takes what's called an *ExpressionWithTypeArguments* in an `extends` clause:

```ts
function subclass<T>(klasstype : T) : T {
  // This is our mixin, but for demo purposes just return the class
  return klasstype;
}

class DerivedPromise<T> extends subclass(Promise)<T> { }
```

**Comment by dpogue** [comment]
Thanks, that works perfectly, but is not what I would have expected the syntax to be
