### ISSUE TITLE
2.7.1 regression: method doesn't show up in intellisense

### ISSUE THREAD

**Issue by gcanti** [Microsoft/TypeScript#21711]
**TypeScript Version:**  2.7.1 and typescript@next (2.8.0-dev.20180206)

**Code**

```ts
declare class Klass<A> {
  readonly value: A
  constructor(value: A)
  f<B extends number>(this: Klass<B>): void
}

const x = new Klass(1). // <= `f` is not suggested by intellisense
```

**Expected behavior:**

`f` should be listed in intellisense as happens with typescript v2.6.2

**Actual behavior:**

`f` doesn't show up in intellisense

**Playground Link:** 

[Playground repro](https://www.typescriptlang.org/play/#src=declare%20class%20Klass%3CA%3E%20%7B%0D%0A%20%20readonly%20value%3A%20A%0D%0A%20%20constructor(value%3A%20A)%0D%0A%20%20f%3CB%20extends%20number%3E(this%3A%20Klass%3CB%3E)%3A%20void%0D%0A%7D%0D%0A%0D%0Aconst%20x%20%3D%20new%20Klass(1).%20%2F%2F%20%3C%3D%20%60f%60%20is%20not%20suggested%20by%20intellisense%0D%0A)

**Comment by DanielRosenwasser** [comment]
This is likely due to #20616.

**Comment by winterbe** [comment]
@DanielRosenwasser I've encountered a similar issue with the library [Sequency](https://github.com/winterbe/sequency). Code suggestions work fine in TS 2.6.1 but are incomplete in 2.7.1.

Please take a look at this declaration: https://github.com/winterbe/sequency/blob/master/src/Sequence.ts#L76-L91

Most operator functions are no longer available as suggestions. They all declare `this: Sequence<T>` via arguments (or with a more specific type parameter).

Tested in VSCode and Intellij IDEA (using typescript service): https://youtrack.jetbrains.com/issue/WEB-31141

# 2.6.1

![popup2](https://user-images.githubusercontent.com/485033/36194116-d0194752-1168-11e8-8129-16640e3c7b67.png)

# 2.7.1

![popup1](https://user-images.githubusercontent.com/485033/36194109-cbba755a-1168-11e8-878d-ae880d90f3a4.png)

<img width="646" alt="popup3" src="https://user-images.githubusercontent.com/485033/36194123-d42511e6-1168-11e8-9876-6e7f2022663b.png">

**Comment by sant123** [comment]
Any advance on this topic? https://github.com/Microsoft/vscode/issues/43489

Just asking 😝

**Comment by winterbe** [comment]
Yea, it seems all linked issues are closed without any further note. 🤷‍♂️

**Comment by andy-ms** [comment]
@winterbe Original repro now works.  Looked at `sequency` and I get a completion for `sequenceOf(1,2,3).firstOrNull` with no problem.

**Comment by sant123** [comment]
May you look for sequelize Typescript @andy-ms? findAll method doesn't show up on intellisense, but you can write it completely.

**Comment by andy-ms** [comment]
@sant Are you using `typescript@next` in your editor? I went to `DefinitelyTyped/types/sequelize/sequelize-tests.ts` and I get a completion for `User.findAll`.

**Comment by andy-ms** [comment]
Yes, try installing `typescript@next` and setting up your editor to use it. (vscode instructions [here](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions))

**Comment by sant123** [comment]
It's working! Thanks a lot @andy-ms 

![image](https://user-images.githubusercontent.com/7959437/37606335-403375f8-2b63-11e8-9748-5cdd1cbc7269.png)
