### ISSUE TITLE
[Suggestion] Display git sha1 with --extendedDiagnostics or / and --version

### ISSUE THREAD

**Issue by JulioJu** [microsoft/TypeScript#21715]
When we compile typescript from sources, we havn't any solution to know later exactly wich git version of TypeScript we use.

1. I believe it could be cool to display the TypeScript version when parameter `--extendedDiagnostics` is used. It could be cool, to know with wich version of TypeScript we make some tests when we track some TypeScript bugs, to avoid confusions and mistakes. For example it could be cool to use a field with the git sha1. It could be obtained by ` git rev-parse HEAD` when TypeScript it's compiled. 
2.  Some other projects provide this information with the `--version` parameter when the project is compiled from sources (not for officials releases). When we typing `--version` it shows the official version (for example 2.5.0, 2.6.1, etc) following by the short version of the sha1 (obtained by `git rev-parse --short HEAD`). For example (for non official releases) `--version` could display « v2.5.0-23493816a0 ».

**Comment by RyanCavanaugh** [comment]
This is in the npm package info and is available from git if you're working from source, so it seems like the two most common setups by far are already addressed. Doesn't seem to be much feedback here otherwise.
