### ISSUE TITLE
Contextual typing of spread elements

### ISSUE THREAD

**Issue by JsonFreeman** [Microsoft/TypeScript#2172]
The following gets contextually typed:
```ts
var x: ((p: string) => number)[] = [p => p.length];
```
But the following arguably should also be:
```ts
var x: ((p: string) => number)[] = [...[p => p.length]];
```
Same is true for calls:
```ts
function foo(...rest: ((p: string) => number)[]) {}
foo(p => p.length);
```
So we should do it for the following as well:
```ts
function foo(...rest: ((p: string) => number)[]) {}
foo(...[p => p.length]);
```

**Comment by RyanCavanaugh** [comment]
Supported on the grounds of consistency, but at the same time there's no reason to spread a bare literal, so what's the point?

**Comment by JsonFreeman** [comment]
Yeah that makes sense.
