### ISSUE TITLE
Export `with` as a property within declaration file

### ISSUE THREAD

**Issue by yardnsm** [Microsoft/TypeScript#21723]
I got a CommonJS module that exports a function by default. The function has a property named `with`, which is a reserved word in JavaScript. JavaScript allows this kind of usage (`with` as a property name), but unfortunately, I can't get it working in TS declaration file.

## Code
**a.js**
```javascript
module.exports = () => 1;
module.exports.with = (n: number) => 1 + n;
```

**a.d.ts**
```ts
export = GetNumber;

declare function GetNumber(): number;

declare namespace GetNumber {
	export function with(n: number): number;
}
```

**b.ts**
```ts
import * as getNumber from './a';

console.log(getNumber()); // => 1
console.log(getNumber.with(2)); // => 3
```

## Expected behavior:

Declaration should be valid for both `getNumber` and `getNumber.with`.

## Actual behavior:

Getting an error in compilation:
```
$ tsc a.d.ts
a.d.ts(6,19): error TS1003: Identifier expected.
a.d.ts(6,25): error TS1005: ')' expected.
a.d.ts(6,33): error TS1005: ';' expected.
a.d.ts(6,34): error TS1128: Declaration or statement expected.
```

**Comment by mhegazy** [comment]
use `export { ... as with }` instead:

```ts
export = GetNumber;

declare function GetNumber(): number;

declare namespace GetNumber {
    function _with(n: number): number;
    export { _with as with}
}
```

**Comment by yardnsm** [comment]
Awesome, it works!
Thanks :)
