### ISSUE TITLE
Type inference in conditional types misses the overloaded signatures

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#21745]
This is clearly wrong.

cc @ahejlsberg 

**TypeScript Version:**  2.7.0-dev.20180206

**Search Terms:** 

**Code**

```ts
type Call<T extends (...args: any[]) => any> = T extends (...args: any[]) => infer R ? R : never;
declare function f(a: number): number;
declare function f(a: string): string;

type A = Call<typeof f>;
```

**Expected behavior:**

`A` is `number | string`.

**Actual behavior:**

`A` is `string`.

**Playground Link:**  

**Related Issues:**

**Comment by ahejlsberg** [comment]
From the pull request (#21496):

> When inferring from a type with multiple call signatures (such as the type of an overloaded function), inferences are made from the last signature (which, presumably, is the most permissive catch-all case). It is not possible to perform overload resolution based on a list of argument types (this would require us to support typeof for arbitrary expressions, as suggested in #6606, or something similar).

So, this is a known limitation and would require us to implement something like #6606. But even if we do that, it would only work on zero-order types, i.e. we're not intending to implement *deferred* overload resolution for higher-order types.

**Comment by falsandtru** [comment]
I've forgotten that limitation, thanks.
