### ISSUE TITLE
Pick the best or available overloaded signatures in Conditional types

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#21742]
This is not a bug but compiler can be good as this?

**TypeScript Version:**  2.7.0-dev.20180206

**Search Terms:** 

**Code**

```ts
type Call<T extends () => any> = T extends (this: T) => infer R ? R : never;
type Cast<T> = Call<CastMap<T>>;
interface CastMap<T> extends AnyBaseToConsume<T> {
  (this: ThisType<true>): true;
  (this: ThisType<false>): false;
  (this: ThisType<boolean>): boolean;
  (this: ThisType<void>): void;
}

type A = Cast<true>;
```

**Expected behavior:**

`A` is `true` or `boolean` (as the result of `true | boolean`) or `boolean | void`.

In the case of `Cast<true>`, compiler shouldn't be able to infer `R` from `(this: ThisType<false>): false;` and `(this: ThisType<void>): void;`. They will never be callable. Compiler should omit them.

At least the compiler shouldn't pick the last one only, should pick the all overloaded signatures.

**Actual behavior:**

`A` is `void`.

**Playground Link:**  

**Related Issues:**

**Comment by mhegazy** [comment]
This is actually by design. inference in return type position is not meant to be an overload resolution process. it is not really supposed to be used with overloads.

**Comment by falsandtru** [comment]
Okay.
