### ISSUE TITLE
hope can overwrite interface prototype type

### ISSUE THREAD

**Issue by bluelovers** [Microsoft/TypeScript#21752]
**TypeScript Version:**  2.7.0-dev.201xxxxx

**Search Terms:** 

**Code**

hope can overwrite interface prototype type

old interface
```ts
export interface OptionsJSDOM
{
    virtualConsole?: VirtualConsole,
}
```

new sub interface
```ts
export interface NewOptionsJSDOM extends OptionsJSDOM
{
    virtualConsole?: VirtualConsole | boolean,
}
```

**Expected behavior:**

```ts
export interface NewOptionsJSDOM extends OptionsJSDOM
{
    // @ts-overwrite
    virtualConsole?: VirtualConsole | boolean,
}
```

**Actual behavior:**

**Playground Link:**  

**Related Issues:**

**Comment by mhegazy** [comment]
Please see https://github.com/Microsoft/TypeScript/issues/18762
