### ISSUE TITLE
Suggestion: errors based on control flow analysis

### ISSUE THREAD

**Issue by rolyp** [Microsoft/TypeScript#2176]
What, all this business with union types, indeed a veritable managerie of type-related tricks, and we can't make the basics work?

    function borked(): number {
        if (false)
            return 1;
    }

I know this will be flagged with the dreaded "By Design", because of some silly JavaScript use case that I can't imagine, but it's such an obviously wrong feature of the language that I can't help raising as an issue. (Apologies if it's a duplicate.)

**Comment by CyrusNajmabadi** [comment]
@rolyp "but it's such an obviously wrong feature of the language".  I don't believe there's any consensus that this is the case.

Note that @vladima has worked on some flow control language features to help surface this.  See https://github.com/Microsoft/TypeScript/pull/1287 for more details.

**Comment by danquirk** [comment]
As Cyrus notes, we're considering control flow analysis additions that would catch cases like this, but there are tradeoffs. I don't see an actual issue tracking this so I'll just rename this and Vlad's PR can be associated with it now.

**Comment by neilgalarneau** [comment]
Lots of us would want that code to cause an error.

I submitted #2316 which is more general than function borked() above, as a concrete sub-class of 'all errors that could be detected through control flow analysis'.

**Comment by RyanCavanaugh** [comment]
We want to revisit all these control flow things after 2.0 ships. It's a high-value area we want to invest in, but there's no room left in the schedule for something as large in scope as this.

**Comment by mhegazy** [comment]
This should be reported as an error now with `--noImplicitReturns`
