### ISSUE TITLE
Mapped inference types do not work as I understand

### ISSUE THREAD

**Issue by AlexStacker** [Microsoft/TypeScript#21765]
Directly show my code, the text description may not be clear. 
From the callback function used in the parameters

**TypeScript Version:**  2.6.2

**Code**

```ts
interface MapType { 
    a: {
        w: number;
        h: number;
    }
    b: {
        s: string;
        n: boolean;
    }
    q: {
        s: string;
        n: boolean;
    }
}

type NS<T, P extends keyof T> = {
    [U in keyof T[P]]: T[P][U] 
}

let n: NS<MapType, 'a' | 'b'>
n.s //Property 's' does not exist on type 'NS<M, "a" | "b">'.
let m: NS<MapType, 'a'>
m.h // (property) h: number
```

**Expected behavior:**
```ts
let n: NS<MapType, 'a' | 'b'>
n.s // string
n.n // boolean
n.w // number
n.h // number
```
**Actual behavior:**
```
let n: NS<MapType, 'a' | 'b'>
n.s //Property 's' does not exist on type 'NS<M, "a" | "b">'.
```

**Playground Link:**  

**Related Issues:**
I think this is very helpful to me,But did not solve my problem.
[17930](https://github.com/Microsoft/TypeScript/issues/17930)

**Comment by mhegazy** [comment]
I think you want `NS<MapType, "a"> & NS<MapType, "b">`

**Comment by mhegazy** [comment]
You might have better luck sharing this on StackOverflow. This is not a support forum, it is one for reporting compiler/language bugs and suggestions. 
If you believe you are running into a compiler bug, please share a minimal repro project that demonstrates the issue you are running into and why you believe this is a compiler bug and not a declaration file issue or library usage problem.

**Comment by AlexStacker** [comment]
Here's the code that can work:
```ts
  type NS<T, P extends keyof T> = {
    [U in keyof T]: T[P]
  }
```
but I want to get their flattened values because I have this code:
```ts
function getFieds({
    a: true,
    q: true
  }, function(res) {
    res.s // string
    res.n // boolean
    res.w // number
    res.h // number
  });
```
or
```ts
function getFieds(['a', 'q'], function(res) {
    res.s // string
    res.n // boolean
    res.w // number
    res.h // number
  });
```
The first argument's subkey is unknown. I need to write its declaration file for this js function.But I think this should also work it:
```ts
type NS<T, P extends keyof T> = {
    [U in keyof T[P]]: T[P][U] 
}
```
It typescript can solve such a problem?
