### ISSUE TITLE
Add explicit quote character format option

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#21768]
**Search Terms:** 
- Quote
- Format 
- Import
- Quick fix

**Problem**
There are now number of cases where TS generates code with quote characters:

- Imports
- Bracket completions
- Implement interface / abstract class

A recurring request against VS code is to make the quote type explicitly configurable, such as: always use double quotes or always use single quotes.

**Proposal**
Add a new format or configuration options for quote characters. This new setting would only apply to code generated by typescript. We would not change existing quotes in code

**Related Issues:**
- #13270
- #18169
- https://github.com/Microsoft/vscode/issues/43225
- https://github.com/Microsoft/vscode/issues/42691

**Comment by mhegazy** [comment]
I think this is a duplicate of https://github.com/Microsoft/TypeScript/issues/20619

**Comment by mjbvz** [comment]
Yes. I'm just raising this one on its own because I see it repeated so often. In addition to  #20619, can we please keep an issue open that specifically tracks configuring quotes

**Comment by mhegazy** [comment]
Can we just use #20619? we are planning on taking that one on this release..

**Comment by mjbvz** [comment]
Ok, glad to see this is scheduled for 2.8. I'll add a comment in #20619 there that makes it clear that configuring quotes is part of the feature
