### ISSUE TITLE
Type not inferred properly when functions are reduced iteretively

### ISSUE THREAD

**Issue by pulasthibandara** [Microsoft/TypeScript#21773]
**TypeScript Version:** 
2.7.0-@next

**Search Terms:** 
"infer reduced type",  "typescript compose functions"

**Code**

```ts
const addPropA = <T extends object>(obj: T) => Object.assign({}, obj, { a: 'a' })
const addPropB = <T extends object>(obj: T) => Object.assign({}, obj, { b: 'b' })

// this works: const constructed: { c: string; } & { b: string; } & { a: string; }
const constructed = addPropA(addPropB({ c: 'c' }))

// this doesnt infer the type properly: const reduced: { c: string; }
const reduced = [addPropA, addPropB].reduce((acc, fn) => fn(acc), { c: 'c' })
```

**Expected behavior:**
`const reduced: { c: string; } & { b: string; } & { a: string; }`

**Actual behavior:**
`const reduced: { c: string; }`

**Playground Link:**
[playground](https://www.typescriptlang.org/play/#src=const%20addPropA%20%3D%20%3CT%20extends%20object%3E(obj%3A%20T)%20%3D%3E%20Object.assign(%7B%7D%2C%20obj%2C%20%7B%20a%3A%20'a'%20%7D)%0D%0Aconst%20addPropB%20%3D%20%3CT%20extends%20object%3E(obj%3A%20T)%20%3D%3E%20Object.assign(%7B%7D%2C%20obj%2C%20%7B%20b%3A%20'b'%20%7D)%0D%0A%0D%0A%2F%2F%20this%20works%3A%20const%20constructed%3A%20%7B%20c%3A%20string%3B%20%7D%20%26%20%7B%20b%3A%20string%3B%20%7D%20%26%20%7B%20a%3A%20string%3B%20%7D%0D%0Aconst%20constructed%20%3D%20addPropA(addPropB(%7B%20c%3A%20'c'%20%7D))%0D%0A%0D%0A%2F%2F%20this%20doesnt%20infer%20the%20type%20properly%3A%20const%20reduced%3A%20%7B%20c%3A%20string%3B%20%7D%0D%0Aconst%20reduced%20%3D%20%5BaddPropA%2C%20addPropB%5D.reduce((acc%2C%20fn)%20%3D%3E%20fn(acc)%2C%20%7B%20c%3A%20'c'%20%7D)%0D%0A)

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
There's no reasonable way we could model this in the type system -- `addPropA` and `addPropB` *happen* to be order-insensitive but there's no way to observe this property of them at a distance, and the output type of any `f(g(h(i(x)))` sequence necessarily depends on the order of invocation. We'd have to have some way to tell apart `reduce` from `reduceRight` and describe their *ordering behavior* in the type system, which is really too heavy of a lift to consider given the other things still on our plate.
