### ISSUE TITLE
Supporting type `self` or something that can represents the current instance.

### ISSUE THREAD

**Issue by vilic** [Microsoft/TypeScript#2179]
When I am writing a declaration file, I found it really frustrating repeating the inherited method that returns the instance itself for a correct return type.

E.g. for animation library GSAP, many classes are inherited from class `Animation`, I have to repeat almost every method to update return type `Animation` to the current class.

```typescript
class Animation {
    chain(): Animation;
}

class TweenLite extends Animation {
    ownProperty: any;
    chain(): TweenLite;
}
```

It would be great if we may use some type like `self` to make this easier, like this:

```typescript
class Animation {
    chain(): self;
}

class TweenLite extends Animation {
    ownProperty: any;
}
```

**Comment by DanielRosenwasser** [comment]
Seems like a duplicate of #285.

**Comment by danquirk** [comment]
Also see #513
