### ISSUE TITLE
Provide an Add Reference feature for Visual Studio projects

### ISSUE THREAD

**Issue by NoelAbrahams** [microsoft/TypeScript#2180]
Hi,

The set-up we currently have for managing a large number of projects in Visual Studio is the following:
- Ensure each project generates a `.d.ts` file in an output directory.
- If project **A** depends on the types in project **B** then [create a project dependency](https://msdn.microsoft.com/en-us/library/et61xzb3.aspx) using the VS dialogue.
- In project **B** add file `_references.ts` and add the following snippet in order to import the types from project A:
  
  ``` xml
    /// <reference path='../projectA/output/typings.d.ts' />
  ```

This feature request is to provide an "Add Reference" dialogue that does the following:
- The dialogue is launched from the context menu for a project (i.e. right-click on project **B** and select "Add Reference")
- Permits selection of declaration files, e.g. `projectA/output/types.d.ts`.
- Once the item is selected the reference is added to a section in `.csproj`
  
  ``` xml
  <References>
    <Reference Include="typings">
        <HintPath>..\projectA\output</HintPath>
    </Reference>
  </References>
  ```
- The TypeScript compiler and language service use this reference exactly the same as if it were defined in `_references.ts`.

**Comment by Zoltu** [comment]
I have put together an interim solution (CC0 license in case Microsoft wants to add make it official or take it over).  The Readme.md has the details, but the short of it is that it is a NuGet package you can install that adds primitive support for adding references between Visual Studio TypeScript projects.

https://github.com/Zoltu/BuildTools.TypeScript.FromReferences

Feedback and Pull Requests welcome!

**Comment by RyanCavanaugh** [comment]
We ended up implementing #3469 which is largely in lieu of this
