### ISSUE TITLE
Lazy inference of generic types does not work properly

### ISSUE THREAD

**Issue by zaclummys** [Microsoft/TypeScript#21819]
**TypeScript Version:**  2.7.1

**Search Terms:** 

- lazy Inference
- generic types

**Code**

```ts
function getKey<T extends object, U extends keyof T> (key: U) {
    return function (obj: T) {
        return obj[key];
    };
}

getKey("foo")({ foo: 1 });
```

**Expected behavior:**
No errors.

**Actual behavior:**
Typescript says: _Argument of type '"foo"' is not assignable to parameter of type 'never'._

**Playground Link:** https://www.typescriptlang.org/play/index.html#src=function%20getKey%3CT%20extends%20object%2C%20U%20extends%20keyof%20T%3E%20(key%3A%20U)%20%7B%0D%0A%20%20%20%20return%20function%20(obj%3A%20T)%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20obj%5Bkey%5D%3B%0D%0A%20%20%20%20%7D%3B%0D%0A%7D%0D%0A%0D%0AgetKey(%22foo%22)(%7B%20foo%3A%201%20%7D)%3B

**Comment by mhegazy** [comment]
Constraints are not inference positions.. so no inferences are made for `T` here really..  the function should be instead:
```ts
function getKey<T> (key: keyof T)  ..
``
