### ISSUE TITLE
JsErrorScriptException (0x30001) "Debug Failure" upgrading to 2.7.1

### ISSUE THREAD

**Issue by marcomura** [Microsoft/TypeScript#21829]
Hello,
trying to upgrade the compiler from 2.6.2 to 2.7.1, tsc.exe is now crashing when compiling:

>Script failed with error: 'JsErrorScriptException (0x30001)'.
>Debug Failure.
>Error: Debug Failure.
>   at fail (Unknown script code:2341:13)
>   at checkUnusedClassMembers (Unknown script code:35757:29)
>   at checkUnusedIdentifiers (Unknown script code:35643:29)
>   at checkSourceFileWorker (Unknown script code:37913:21)
>   at checkSourceFile (Unknown script code:37891:13)
>   at getDiagnosticsWorker (Unknown script code:37945:17)
>   at getDiagnostics (Unknown script code:37934:17)
>   at Anonymous function (Unknown script code:59858:17)
>   at runWithCancellationToken (Unknown script code:59834:17)
>   at getSemanticDiagnosticsForFileNoCache (Unknown script code:59848:13)

I see there are a lot of other threads about this error, but I don't see any relevant with my scenario.
I believe something broke with the new tsc.exe.

What information can I provide to help you finding the root cause?
Please, contact me privately (marcomu) since I can't paste internal code.

Thanks,
Marco

**Comment by mhegazy** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/21491. Fix should be in `typescript@next` today and in the upcoming `typescript@2.7.2` expected in a week or so.

**Comment by marcomura** [comment]
Ah cool, I can confirm that without noUnusedLocals it builds fine.
Thanks!
