### ISSUE TITLE
focusin, focusout events missing from DocumentEventMap/HTMLElementEventMap

### ISSUE THREAD

**Issue by yseymour** [Microsoft/TypeScript#21822]
**TypeScript Version:**  2.8.0-dev.20180208

**Search Terms:**  focusin focusout

**Code**

```ts
document.addEventListener('focusin', (e:FocusEvent) => {});
```

**Expected behavior:**
Compiles in strict mode

**Actual behavior:**
```
focusin.ts(1,38): error TS2345: Argument of type '(e: FocusEvent) => void' is not assignable to parameter of type 'EventListenerOrEventListenerObject'.
  Type '(e: FocusEvent) => void' is not assignable to type 'EventListenerObject'.
    Property 'handleEvent' is missing in type '(e: FocusEvent) => void'.
```

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by lankaapura** [comment]
I've sent the PR https://github.com/Microsoft/TSJS-lib-generator/pull/369 for this. Let me know if there any issues.
