### ISSUE TITLE
PushManager getSubscription missing possible null return

### ISSUE THREAD

**Issue by arjunyel** [Microsoft/TypeScript#21821]
**TypeScript Version:**  2.8.0-dev.20180208

**Search Terms:** pushManager getSubscription() TSJS

**Code**

```ts
ServiceWorkerRegistration.pushManager.getSubscription().then((PushSubscription) => {
console.log(PushSubscription);
});

```

**Expected behavior:**

[Per the spec](https://w3c.github.io/push-api/#dom-pushmanager-getsubscription) getSubscription returns type PushSubscription or null.

**Actual behavior:**
getSubscription returns type PushSubscription

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.
