### ISSUE TITLE
'infer' type parameters declarations aren't printed in quick info.

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#21836]
Found by @weswigham 

```ts
type Alias<T> = T extends (infer U)[] ? U : never;
````

Request quick info on `Alias`.

**Expected**: `type Alias<T> = T extends (infer U)[] ? U : never`

**Actual**: `type Alias<T> = T extends U[] ? U : never`

**Comment by Kingwl** [comment]
seems already fixed, doesn't it?
![image](https://user-images.githubusercontent.com/6831019/49427512-79057000-f7de-11e8-8887-6ca383e40853.png)

**Comment by DanielRosenwasser** [comment]
Good catch!
