### ISSUE TITLE
Does typeguard work with expressions, i.e. ev.target?

### ISSUE THREAD

**Issue by TimKelly2** [Microsoft/TypeScript#2184]
A cast appears to work with the expression, ev.target.
```ts
         if(ev.target instanceof Node) {
             var n : Node = <Node>ev.target;
             n.appendChild(document.getElementById(data));
         }
```
A typeguard appears to work with the simple variable, t.
```ts
         var t = ev.target;
         if(t instanceof Node) {
             var n : Node = t;
             n.appendChild(document.getElementById(data));
         }
```
A typeguard appears to fail with an expression, ev.target or (ev.target).
```ts
         if(ev.target instanceof Node) {
             ev.target.appendChild(document.getElementById(data));
         }
```

**Comment by danquirk** [comment]
This is by design currently (the spec section on type guards only mentions narrowing variables and properties, not dotted names). We can consider augmenting the narrowing functionality but there are concerns about side effecting function calls.

**Comment by zspitz** [comment]
+1

**Comment by mhegazy** [comment]
closing in favor of https://github.com/Microsoft/TypeScript/issues/3812
