### ISSUE TITLE
JS keyword suggestions returned inside of JSX tag

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#21844]
From https://github.com/Microsoft/vscode/issues/42788

**TypeScript Version:**  2.8.0-insiders-20180206

**Search Terms:** 
- Jsx react
- Suggest, suggestions
- keywords

**Code**

```ts
class Foo {
    render() {
        <div   />
    }
}
```

Trigger suggestions inside of the `<div />` tag

**Bug:**
JS keyword suggestions are returned:

<img width="812" alt="screen shot 2018-02-09 at 2 17 17 pm" src="https://user-images.githubusercontent.com/12821956/36052794-013c1242-0da4-11e8-8e06-6fb34668efcf.png">

**Comment by in19farkt** [comment]
I have this problem appeared in version 2.7.2
