### ISSUE TITLE
Generic parameter inference for union type possibly incorrect

### ISSUE THREAD

**Issue by schotime** [Microsoft/TypeScript#21856]
**TypeScript Version:**  2.7.1

**Search Terms:** generic intersection

**Code**

```ts
class Chain<TInput> {
    val : TInput;
    constructor(val: TInput) {
        this.val = val;
    }
    pass<TOutput>(p: ((input: TInput) => TOutput)): Chain<TInput & TOutput> {
        return new Chain<TInput & TOutput>(Object.assign(this.val, p(this.val)));
    }
}

var chain = new Chain<{one: number}>({ one: 1 });
chain
    .pass(x => ({ two: 2 }))
    .pass((x: any): ({ three: number } | { four: number }) => (x.one == 2 ? { three: 3 } : { four: 4 }))
    .pass(x => x);
```

**Expected behavior:**
The parameter of the x in the last pass function should have the type below.

```ts
(parameter) x: ({
    one: number;
} & {
    two: number;
} & ({ 
    three: number;
} | { 
    four: number; 
})
)
```

**Actual behavior:**

```ts
(parameter) x: ({
one: number;
} & {
    two: number;
} & {
    three: number;
}) | ({
    one: number;
} & {
    two: number;
} & {
    four: number;
})
```

**Comment by jack-williams** [comment]
These types are equivalent. If you bind them to aliases and hover over them you'll see they get normalised to the same thing. For a shorter example:

```typescript
type W = { w: boolean };
type X = { x: 'number' };
type Y = { y: string };
type Z = { z: undefined };

type L = W & X & (Y | Z);
type R = (W & X & Y) | (W & X & Z);
```
Hover over L and you'll see the type written as R. Basically TypeScript is just applying the distributive law of intersection over union: [link](https://proofwiki.org/wiki/Intersection_Distributes_over_Union).

**Comment by schotime** [comment]
Appreciate the explanation. Clarified a lot and made me think about how i'm using it.
