### ISSUE TITLE
Cant use object's number keys with selection method

### ISSUE THREAD

**Issue by artaommahe** [Microsoft/TypeScript#21858]
**TypeScript Version:**  2.7.1

**Search Terms:** 

**Code**
```ts
class Store<T>
{
    public get<A extends keyof T, B extends keyof T[A]>(key1: A, key2: B): T[typeof key1][typeof key2]
    {
        return <any>void 0;
    }
}

export interface IUsersWordsLoadingState
{
    [ userId: number ]: { wordsets: { smth: boolean } };
}

let initialState: { loadingState: IUsersWordsLoadingState };
let store: Store<typeof initialState>;
store.get('loadingState', 0);
```
```
Argument of type '0' is not assignable to parameter of type 'never'.
```

**Expected behavior:**
- can use number keys in objects with selection method

**Actual behavior:**
- cant use number keys in objects with selection method

**Playground Link:**
https://stackblitz.com/edit/angular-uz9kxg?file=app%2Fapp.component.ts

**Comment by mhegazy** [comment]
Please see https://github.com/Microsoft/TypeScript/issues/13715
