### ISSUE TITLE
Declaring a var inside a loop with a let of the same name gives no error

### ISSUE THREAD

**Issue by JsonFreeman** [microsoft/TypeScript#2185]
``` ts
for (let v; ; ) { var v; }
for (let v in []) { var v; }
for (let v of []) { var v; }
```

These all should be errors per the ES6 spec sections 13.6.3.1 and 13.6.4.1:

It is a Syntax Error if any element of the BoundNames of LexicalDeclaration also occurs in the
VarDeclaredNames of Statement.

**Comment by mhegazy** [comment]
The var scope is not the for statement, it is the enclosing function. so i do not think this is an error

**Comment by JsonFreeman** [comment]
That's true, but the spec still says it's an error.

**Comment by mhegazy** [comment]
@bterlson is this really intended to be an error?

**Comment by bterlson** [comment]
Yes, generally speaking it is an error for a var decl to hoist past a lexical decl.

**Comment by JsonFreeman** [comment]
@bterlson, does that include blocks as well?
```ts
{
   let x;
   {
      var x;
   }
}
```

**Comment by bterlson** [comment]
@JsonFreeman Yes, believe this is covered by the static semantics in [13.1.1](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-block-static-semantics-early-errors).

**Comment by DanielRosenwasser** [comment]
Thanks @Andarist!

**Comment by Andarist** [comment]
Closing 4-digit issues feels good 🤣
