### ISSUE TITLE
Consider using the Nyan Cat Mocha reporter for Jake tests

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Microsoft/TypeScript#21852]
If it weren't 12:26 am, I probably wouldn't have the guts to request this feature.

https://mochajs.org/#nyan

Edit: tested locally by replacing `'mocha-fivemat-progress-reporter'` with `'nyan'` in `Jakefile.js`. Would recommend.

![image](https://user-images.githubusercontent.com/3335181/36060198-6b2627ba-0df9-11e8-9e43-c2a3f8975e83.png)

**Comment by mhegazy** [comment]
@CyrusNajmabadi wanted that, so we added the `r` flag for `jake runtests r=nayan`  :D
