### ISSUE TITLE
Safe subset of TypeScript -- For plugins/add-ons to TypeScript applications

### ISSUE THREAD

**Issue by shaagerup** [Microsoft/TypeScript#21865]
I am considering the scenario of letting the users a hosted application upload their own front-end plugins, and get them served together with the rest of the application. 

Today, frontend addons are usually realized by embedding Iframes (Zendesk uses this strategy AFAIK), or only making it possible if the application is self-hosted (Microsoft Sharepoint uses this strategy AFAIK).

Doing straight embedding of a user-provided code is of course a clear no-go in the JavaScript world, due to the risk of cross site scripting attacks. But what the code was first run through some kind of security audit -- then the model might be reasonable.

This would be a tedious and close to impossible thing with classical JavaScript, but with a TypeScript program which does not utilize 'any' type (explicitly or implicitly), and does only use a restricted set of imports, it might actually be feasible to make either an automatic or semi-automatic security audit of a plugin submission.

A project with similar goals is "Safe Haskell" (https://downloads.haskell.org/~ghc/7.8.4/docs/html/users_guide/safe-haskell.html) but I have not heard of any such thing in TypeScript.

Would it be a hard task to add a flag to tsc or tslint/tslint-immutable to enforce a safe subset of TypeScript. Or to tweak a static analysis tool like https://github.com/SonarSource/SonarTS to perform a trustable security audit of a TypeScript program, and what steps would this involve?

**Comment by saevarb** [comment]
I too am interested in this. I have looked at SonarTS but I am unsure if something like this would be within the scope of the intended use case of that tool. Hopefully one of the devs could outline the steps involved.

**Comment by andy-ms** [comment]
You may be interested in https://github.com/tc39/proposal-realms.

**Comment by mhegazy** [comment]
There are so many ways that a program can trick static analysis to gain access to unsafe APIs. It is not just about typed or untyped. 
Providing provably-secure-code guarantees is something that outside the scope of this project.

**Comment by shaagerup** [comment]
Great, thank you very much for your answers 👍 If you want, you can close this now, or we can let it stay open for a week, if maybe others have something to add.

I know **@saevarb** personally, and I know he needs a programming language-related project as part as his bachelor Computer Science degree, and I have suggested the investigation of this topic to him -- the creation of this issue is motivated by this. 

If you agree that there are no solutions out there right now, and nothing planned, maybe this could be investigated for a few months by Sævar.

If any one can help us elaborate more in depth with the following _"There are so many ways that a program can trick static analysis to gain access to unsafe APIs. It is not just about typed or untyped."_  that would be great -- then one could choose maybe one single subject for Sævars study activity.

**Comment by mhegazy** [comment]
```ts
callEval(this);

function callEval(o: object) {
     Object.getOwnPropertyDescriptor(o, "eval").value.call(undefined, "console.log('eval')");
}
```
there are no `any`s here, there are no unsafe casts, there are no direct use of unsafe functions like `eval`.. yet you can call eval. 

I do not think static analysis is worth while in this domain. every time you enforce a pattern a malicious actor can find another. ultimately you want whatever tool you write to be usable..
I think something along the lines of https://developers.google.com/caja/ or the realms proposal as noted by @andy-ms is more promising.

**Comment by andy-ms** [comment]
I'd like to point out that the above *does* use `any`, and the `https://palantir.github.io/tslint/rules/no-unsafe-any/` line rule correctly detects it. But @mhegazy is right that we don't catch everything.

**Comment by shaagerup** [comment]
Just an update -- We had a meeting today with Professor in practical & automatic proofs of software termination and correctness http://www.imada.sdu.dk/~petersk/ -- We will continue with the project for at least 3 months! Please post anything that can help us -- We will also keep you updated ;-) This is gonna be great!
