### ISSUE TITLE
esModuleInterop causes is not a constructor function type

### ISSUE THREAD

**Issue by corbinu** [microsoft/TypeScript#21872]
**TypeScript Version:**  2.7.1 and 2.8.0-dev.20180211

**Search Terms:** 
is not a constructor function type
is not a constructor function type esModuleInterop
is not a constructor function type module Interop

**Code**
I am using https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/hapi for typing hapi 17

It works fine until I enable the new esModuleInterop then suddenly I get this error
```

node_modules/@types/hapi/definitions/server/server.d.ts:45:29 - error TS2507: Type '{ default: Podium; registerEvent(events: Events[]): void; registerEvent(events: Events): void; re...' is not a constructor function type.

45 export class Server extends Podium {
```

**Expected behavior:**
I believe the definition file should either be valid or not regardless of if esModuleInterop is enabled or not

**Actual behavior:**
If the type definition is invalid code and then should error either way. If it is valid code then it should not error either way.

Also if I //@ts-ignore the error the code compiles and runs fine

**Comment by DanielRosenwasser** [comment]
[Since Podium is a CommonJS module that is declared with an `export =`, you need to import it with `import Podium = require("podium")` or `import Podium from "podium"`

**Comment by DanielRosenwasser** [comment]
I guess I misunderstood the request; you're saying we should not issue these errors within declaration files since it's sort of out of the user's control.

**Comment by corbinu** [comment]
Thanks I will also try to issue a PR to fix the declaration file. I was just super confused since it isn’t an error when module interop is off

**Comment by RyanCavanaugh** [comment]
It looks like this has been addressed. If not, please open a new issue with a self-contained repro so we can reassess. Thanks!
