### ISSUE TITLE
Salsa Intellisense for parameters of closures with javascript

### ISSUE THREAD

**Issue by HolgerJeromin** [Microsoft/TypeScript#21877]
**Version:**  VS2017

My TypeScript project produces a `.d.ts` file. Which is perfect for TS projects:

```ts
declare function myGlobal(param: string): string;
declare module myHmi {
    class foo {
        static myStatic(bar: string): string;
    }
}
```

But other teams are on JS and wants to use our nice typings. They have the .d.ts file inside the project. VS2017 detects it in the new JS Language Service (Salsa).

```js
var myHmi;
(function (myHmi) {
    // Here VS2017 knows myGlobal()
    // Here VS2017 detected myHmi as {}. So it has no knowledge of myHmi.foo.myStatic()

    main code...
})(myHmi || (myHmi = {}));

// Here VS2017 knows myGlobal()
// Here VS2017 knows myHmi.foo.myStatic()

```
Can we use a hint (jsdoc magic?) to tell VS that the inner myHmi is an extension of the outer myHmi?

**Comment by andy-ms** [comment]
The JS developers should *also* be able to use the `.d.ts` file instead of the compiled `.js`. Just give it the same name and put it next to the `.js` file.

**Comment by HolgerJeromin** [comment]
The JS developers are including their code into `myHmi` TS module infrastructure (as an extension). 
They do not code in compiled code but their JS code looks the same as TS transpiled output.

**Comment by andy-ms** [comment]
So your JS developers are manually writing code that looks like TS transpiled output?
If you omit `var myHmi` it will work...
```js
(function (myHmi) {
    myHmi.foo; // works

// @ts-ignore (cannot assign to myHmi because it is not a variable)
})(myHmi || (myHmi = {}));
```

**Comment by HolgerJeromin** [comment]
> So your JS developers are manually writing code that looks like TS transpiled output?

Yes. We want to elevate them eventually to Typescript. 

`})(myHmi || (myHmi = {}));`

This does not work in my complex code in VS 15.5.4, JS language service 2.0, TS Tools 15.5.11025.1
I need to have:
`})(myHmi);`

But this is working pretty good. 
Thanks for your help.
