### ISSUE TITLE
Regression (2.3.3 and greater): AMD declarations with outFile and mixin class generates extra invalid declarations

### ISSUE THREAD

**Issue by kamranayub** [Microsoft/TypeScript#21871]
When using the Mixin class pattern with 2.3.3 and above, the AMD declaration file (using `outFile`) generates an extra ambient declaration that causes the file to be invalid (which causes downstream issues to tools or library consumers).

**TypeScript Version:**  2.3.3 and above (tested with `next`)

**Search Terms:** "a declare modifier cannot be used"

**Code**

https://github.com/kamranayub/typescript-bug-amd-declaration-ambient

**Expected behavior:**

There should be no extra `declare` declaration on line 10 of `dist.amd.d.ts`

**Actual behavior:**

There is an invalid declaration added on line 10 of `dist.amd.d.ts`. This doesn't occur on versions prior to 2.3.3.

Error:

> A 'declare' modifier cannot be used in an already ambient context

**Playground Link:** See repo

We are using this pattern in a library with more code for the `Configurable` function but this is enough to reproduce the issue.

**Comment by weswigham** [comment]
This is fixed in `master` from what I can tell, and I've opened https://github.com/Microsoft/TypeScript/pull/22733 to add your test to our regression suite 😉

**Comment by kamranayub** [comment]
Thanks!
