### ISSUE TITLE
TypeScript 2.7 adds invalid BOM characters inside the output file content when emitBOM: true

### ISSUE THREAD

**Issue by volkanceylan** [Microsoft/TypeScript#21878]
**TypeScript Version:**  2.7.1

**Search Terms:** 
BOM, Extra Characters, TypeScript 2.7

**Code**

To reproduce this, just create a folder with single TS file (test.ts):
```ts
namespace Test {
    export class A {
    }
    
    export class B extends A {
    }
}
```
and this tsconfig.json:

```json
{
  "compileOnSave": true,
  "compilerOptions": {
    "preserveConstEnums": true,
    "experimentalDecorators": true,
    "declaration": true,
    "emitBOM": true,
    "sourceMap": true,
    "outFile": "output.js",
    "target": "es5",
  },
  "include": [
    "test.ts"
  ]
}
```

When you run "c:\Program Files (x86)\Microsoft SDKs\TypeScript\2.7\tsc.exe" in this folder, output.js looks like this:

```js
ï»¿var __extends = (this && this.__extends) || (function () {
    var extendStatics = Object.setPrototypeOf ||
        ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
        function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
var Test;
(function (Test) {
    var A = /** @class */ (function () {
        function A() {
        }
        return A;
    }());
    Test.A = A;
    var B = /** @class */ (function (_super) {
        __extends(B, _super);
        function B() {
            return _super !== null && _super.apply(this, arguments) || this;
        }
        return B;
    }(A));
    Test.B = B;
})(Test || (Test = {}));
//# sourceMappingURL=output.js.map
```

**Expected behavior:**

Output should only have one set of BOM characters, not double / invalid characters. 

When i compile with TypeScript 2.6 or earlier i get no such characters inside content.

**Actual behavior:**

Output.js file correctly has UTF-8 encoding, but also has invalid characters at the start of the file (invalid unicode characters, not BOM)

**Comment by volkanceylan** [comment]
Just a note that might help identifying the issue. Looking at TypeScript 2.7 source, writeFile method is declared like this:

```ts
var utf8ByteOrderMark = "\u00EF\u00BB\u00BF"
//...
         function writeFile(fileName, data, writeByteOrderMark) {
                if (writeByteOrderMark) {
                    data = utf8ByteOrderMark + data;
                }
```

And in 2.6:

```ts
         function writeFile(fileName, data, writeByteOrderMark) {
                if (writeByteOrderMark) {
                    data = "\uFEFF" + data;
                }
```

This is probably the change that causes the problem.

**Comment by volkanceylan** [comment]
This is introduced in commits ce29b4c36d04cc22b8b513b4ff1fc84e084f6628 and 2f941f33e238e5fb25e710cb74c35549cd694eb6

"\uFEFF" !== "\u00EF\u00BB\u00BF"

**Comment by volkanceylan** [comment]
And the relevant pull request: 

https://github.com/Microsoft/TypeScript/pull/19991

Here is more information on why "\uFEFF" is the BOM for all UTFs, and how it gets converted to bytes "EF BB BF" on output while writing a file in UTF-8:

https://stackoverflow.com/questions/17879198/adding-utf-8-bom-to-string-blob/27975629#27975629

**Comment by ahejlsberg** [comment]
@rbuckton Ron, can you take a look?
