### ISSUE TITLE
strictNullChecks not working for some piped functions 

### ISSUE THREAD

**Issue by ivan7237d** [Microsoft/TypeScript#21888]
**TypeScript Version:**  2.7.1

**Search Terms:** pipe strict strictNullChecks undefined

**Code**

```ts
const pipe = <A, B, C>(
  a: (x: A) => B, 
  b: (x: B) => C
) => (x: A) => b(a(x));

const a = (x: number): number | undefined => undefined;
const b = (x: number) => x + 1;

const y = pipe(a, b);
const z = pipe(a, x => b(x));
```

**Expected behavior:**
Both of the last two lines above, `const y = pipe(a, b);` and `const z = pipe(a, x => b(x));`, would produce errors, because `a` can return `undefined` and `b` only accepts non-undefined values as the argument.

**Actual behavior:**
Only the second line, `const z = pipe(a, x => b(x));`, produces an error ("Type 'undefined' is not assignable to type 'number'"). Types for both `y` and `z` are inferred as `(x: number) => number
`.

**Playground Link:**  
Make sure to enable strictNullChecks in options: https://www.typescriptlang.org/play/#src=%0D%0Aconst%20pipe%20%3D%20%3CA%2C%20B%2C%20C%3E(%0D%0A%20%20a%3A%20(x%3A%20A)%20%3D%3E%20B%2C%20%0D%0A%20%20b%3A%20(x%3A%20B)%20%3D%3E%20C%0D%0A)%20%3D%3E%20(x%3A%20A)%20%3D%3E%20b(a(x))%3B%0D%0A%0D%0Aconst%20a%20%3D%20(x%3A%20number)%3A%20number%20%7C%20undefined%20%3D%3E%20undefined%3B%0D%0Aconst%20b%20%3D%20(x%3A%20number)%20%3D%3E%20x%20%2B%201%3B%0D%0A%0D%0Aconst%20y%20%3D%20pipe(a%2C%20b)%3B%0D%0Aconst%20z%20%3D%20pipe(a%2C%20x%20%3D%3E%20b(x))%3B%0D%0A

**Comment by RyanCavanaugh** [comment]
This is due to function bivariance (see the FAQ). Turning on `strictFunctionTypes` (which you can do in the Playground) correctly detects the error.

**Comment by ivan7237d** [comment]
Thanks so much Ryan for clarifying this for me.
