### ISSUE TITLE
Provide spelling suggestion for indexed access

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#21882]
**TypeScript Version:**  2.8.0-dev.20180211

**Code**

```ts
interface I { foof: number };
declare const i: I;
i.foo;
i["foo"];
```

**Expected behavior:**

```ts
src/a.ts(3,3): error TS2551: Property 'foo' does not exist on type 'I'. Did you mean 'foof'?
src/a.ts(4,4): error TS2551: Property 'foo' does not exist on type 'I'. Did you mean 'foof'?
```

**Actual behavior:**

```ts
src/a.ts(3,3): error TS2551: Property 'foo' does not exist on type 'I'. Did you mean 'foof'?
src/a.ts(4,1): error TS7017: Element implicitly has an 'any' type because type 'I' has no index signature.
```

(Also be sure to watch out for  #21009 when implementing this -- `getSpellingSuggestionForName` would have to be updated to ignore symbol properties, otherwise we would suggest `Did you mean '__@foo@1234'?`.)

**Comment by mhegazy** [comment]
Similar suggestion to https://github.com/Microsoft/TypeScript/issues/21875
