### ISSUE TITLE
Map and Set objects should not be accessible by index

### ISSUE THREAD

**Issue by jamietre** [Microsoft/TypeScript#21881]
**TypeScript Version:**  2.7.1

**Search Terms:** 

Map Set (did not find any issues with Map and Set and subject)

**Code**

```
const myMap = new Map<string, string>();

const key = "x";

test = myMap[key];       // should fail
test = myMap.get(key);    // correct access method
```

**Expected behavior:**

Indexed access is disallowed to a `Map` or `Set` unless using an interface that extends the base type

**Actual behavior:**

This compiles fine and produces unexpected behavior. Because `Map` and `Set` are functionally very similar to traditional object maps, and in many cases may be used after refactoring old code that accesses object map values by index, this is a significant risk of erroneous usage that's not guarded against. Using indexer to access a `Set` or `Map` object should be explicitly disallowed by their default types.

**Playground Link:**  

Example [here](https://www.typescriptlang.org/play/#src=const%20myMap%20%3D%20new%20Map%3Cstring%2C%20string%3E()%3B%0D%0AmyMap.set('foo'%2C%20'bar')%3B%0D%0AmyMap.set('fizz'%2C%20'buzz')%3B%0D%0Aconst%20x%20%3D%20'fizz'%3B%0D%0A%0D%0Aconsole.log(%60foo%20%3D%20%24%7BmyMap.get('foo')%7D%60)%3B%0D%0Aconsole.log(%60fizz%20%3D%20%24%7BmyMap%5Bx%5D%7D%60)%3B%0D%0A%0D%0A%2F%2F%20foo%20%3D%20bar%0D%0A%2F%2F%20fizz%20%3D%20undefined)

**Comment by andy-ms** [comment]
That is an error with [`"noImplicitAny": true`](http://www.typescriptlang.org/docs/handbook/compiler-options.html) (or `"strict": true`) set in your tsconfig.

**Comment by jamietre** [comment]
Wow... you're right. I didn't notice we don't have `no-implicit-any` in this.. thank you!
