### ISSUE TITLE
Calling super from an overloaded constructor

### ISSUE THREAD

**Issue by westy92** [Microsoft/TypeScript#21906]
**TypeScript Version:**  2.8.0-dev.20180211
(Tested in the above version, but found in 2.7.1)

**Search Terms:** 
overload constructor super
super expected arguments got 0 or more.

**Code:**
```ts
class MyDate extends Date {

  public constructor();
  public constructor(vd: VarDate);
  public constructor(value: Date);
  public constructor(value: number);
  public constructor(value: string);
  public constructor(year: number, month: number, date?: number, hours?: number, minutes?: number, seconds?: number, ms?: number);
  public constructor(...args: any[]) {
    super(...args);
    // sublcass-specific code
  }

}
```

**Expected behavior:**
Code compiles without error.

**Actual behavior:**
Error: `Expected 0-7 arguments, but got 0 or more.`

**Playground Link:**  
FYI it seems a bit extreme that it just puts the source in the URL, but here it is:
https://www.typescriptlang.org/play/#src=class%20MyDate%20extends%20Date%20%7B%0D%0A%0D%0A%20%20public%20constructor()%3B%0D%0A%20%20public%20constructor(vd%3A%20VarDate)%3B%0D%0A%20%20public%20constructor(value%3A%20Date)%3B%0D%0A%20%20public%20constructor(value%3A%20number)%3B%0D%0A%20%20public%20constructor(value%3A%20string)%3B%0D%0A%20%20public%20constructor(year%3A%20number%2C%20month%3A%20number%2C%20date%3F%3A%20number%2C%20hours%3F%3A%20number%2C%20minutes%3F%3A%20number%2C%20seconds%3F%3A%20number%2C%20ms%3F%3A%20number)%3B%0D%0A%20%20public%20constructor(...args%3A%20any%5B%5D)%20%7B%0D%0A%20%20%20%20super(...args)%3B%0D%0A%20%20%20%20%2F%2F%20sublcass-specific%20code%0D%0A%20%20%7D%0D%0A%0D%0A%7D

**Related Issues:**
https://github.com/Microsoft/TypeScript/issues/1790
https://github.com/Microsoft/TypeScript/issues/11679

**Comment by RyanCavanaugh** [comment]
@sandersn any ideas on what to do here? My initial reaction was `(super as any)(...args)` but that doesn't compile for multiple reasons. I was also surprised `super(...(args as []);` didn't work

**Comment by westy92** [comment]
I tried this:
```ts
super();
Date.apply(this, args);
```

It compiles, but some unit tests are now failing. I'm not sure if the failures are related or not.

**Comment by westy92** [comment]
I also tried:
```ts
super(...(args.slice(0, 7)));
```
 No luck, but I didn't like that solution anyways.

**Comment by mhegazy** [comment]
assuming https://github.com/Microsoft/TypeScript/issues/4130 is fixed, you can cast to a tuple.  

Until then, `//@ts-ignore` is your best bet here.

**Comment by sandersn** [comment]
@westy92  I have most of #4130 fixed at the branch `spread-tuples` if you want to try it to see if it fixes your problem. I haven't had time to test it with generics, but you don't have that here.

**Comment by westy92** [comment]
@sandersn your branch works! :tada: 
In my `package.json`:
```json
    "typescript": "Microsoft/TypeScript#spread-tuples",
```

**Comment by westy92** [comment]
@sandersn I got the same error using your branch. Do I need to tweak my above code?

**Comment by sandersn** [comment]
Yes, you'll need to cast to a tuple of some length that is greater than the smallest date length, but I think even `[number]` would suffice. (`[]` isn't a valid tuple type in typescript even though it's understood and would be correct here).

You'll also need to build Typescript yourself and compile from `$typescript/built/local/tsc.js`. I didn't update the last-known-good bits yet, so an npm install won't suffice.
