### ISSUE TITLE
"export = <interface>" works for simple interfaces, but fails for nested interfaces

### ISSUE THREAD

**Issue by mihailik** [Microsoft/TypeScript#2190]
External module declaration allows specifying `export = <something>`

At the moment TypeScript allows `<something>` to be an interface. However, it can only be an interface in the top-level scope, not interface nested in an internal module.

Here's the sample code:

```typescript
declare module X {
  export interface Some { //  <-- this cannot be used
    value: string;
  }
}

interface X_Some { //   <-- this can
  value: string;
}


declare module "x" {
  //export = X.Some;
  //         ^ error TS1005: ';' expected.

  export = X_Some;
}
````

**Comment by mhegazy** [comment]
This is by desing, see spec [section 11.2.4] (https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#11.2.4):
>  ExportAssignment:
   export = Identifier ;

We could relax this restriction in the future. though i think your solution will be the new ES6 export syntax:

```TypeScript 
export default X.Some;
```
