### ISSUE TITLE
Internal Typo With JavaScript Intellisense

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#21905]
_From @Gisgar3 on February 12, 2018 21:39_

While working on a bot for Discord, I noticed that there was a typo in the Intellisense results for JavaScript. The below image shows the MessageBox with the typo: 
![bug1](https://user-images.githubusercontent.com/24739483/36120963-d6338758-1012-11e8-8bd4-bdad0ed0aaa3.PNG)  

Within the MessageBox, you can see that 'their' is misspelled as 'thier.' Simple mistake, but thought it was okay to make an issue for.

_Copied from original issue: Microsoft/vscode#43541_

**Comment by lankaapura** [comment]
Created PR #21914 for this.
