### ISSUE TITLE
New Website Logo: ProtoPie

### ISSUE THREAD

**Issue by HyunSeob** [Microsoft/TypeScript#21917]
Please fill the following out:
- Name: ProtoPie
- Homepage url: [https://www.protopie.io](https://www.protopie.io)
- Brand Guidelines/Licensing: -
- Logo: 
![protopie-icon-128](https://user-images.githubusercontent.com/6940487/36156383-2cec7746-111a-11e8-9a89-0e7e99d1f0fc.png)

**Comment by mhegazy** [comment]
Thanks. Added to the site. Should be live next week.
