### ISSUE TITLE
Duplicate type declarations won't be error

### ISSUE THREAD

**Issue by falsandtru** [microsoft/TypeScript#21913]
**TypeScript Version:**  2.7.0-dev.20180210

**Search Terms:** 

**Code**

```ts
export type A = 0;
type A = 0;
```

**Expected behavior:**

error

**Actual behavior:**

pass

**Playground Link:**  

**Related Issues:**

**Comment by mhegazy** [comment]
I am assuming that you intend this to no error iff the types are identical.

**Comment by falsandtru** [comment]
`A` is still `0` in the following code. So this duplicate code make no sense, just a bug.

```ts
export type A = 0;
type A = 1;
```

**Comment by falsandtru** [comment]
Why you don't fix this? This is certainly wrong.

**Comment by RyanCavanaugh** [comment]
This is fixed now
