### ISSUE TITLE
[suggestion] Directory Expansion for Module imports in Nodejs

### ISSUE THREAD

**Issue by DanyelMorales** [Microsoft/TypeScript#21918]
**TypeScript Version:**  2.7.1

**Search Terms:** 
path expansion, module expansion, path alias for  nodejs modules, path module resolution, 

**Expected behavior:**

Typescript should give an option to allow "directory expansion" for path alias defined in "tsconfig.json" and used in module importation.  it would be nice to have something like:

```
{
    "compilerOptions": {
          "expandImport":true,
	   "paths": {
			"@fooPath/*":["./path/to/manyfoos/*"]
            }
     }
}
```

TS Code:
`
import {Foo} from "@fooPath/MyFoo" `

Compilation:
`const Foo = require("path/to/manyfoos/MyFoo");`

**Actual behavior:**
```
{
    "compilerOptions": {
	   "paths": {
			"@fooPath/*":["./path/to/manyfoos/*"]
            }
     }
}
```

TS Code:
`
import {Foo} from "@fooPath/MyFoo" `

Compilation:
`const Foo = require("@fooPath/MyFoo");`

`Nodejs says: Error: Cannot find module '@fooPath/MyFoo'`

**Comment by andy-ms** [comment]
The [design goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals) don't include adding features that would change the meaning of your code.
I think what you want could be solved by setting `"baseUrl": "."` and creating an actual module `@fooPath/MyFoo` with `export * from `../../path/to/manyfoos/MyFoo`. (Although you have to do so again for each module in `manyfoos`.)
(Or, you could just put the module in `@foopath/MyFoo` in the first place.)

**Comment by DanyelMorales** [comment]
Oh! Thanks for the reply.

:)

2018-02-13 10:53 GMT-05:00 Andy <notifications@github.com>:

**Comment by soraping** [comment]
you can try [ws-ts](https://www.npmjs.com/package/ws-ts)
