### ISSUE TITLE
Syntax highlighting not working for TypeScript - Visual Studio 2017

### ISSUE THREAD

**Issue by Ruud-cb** [Microsoft/TypeScript#21915]
**TypeScript Version:**  2.3.2

**Search Terms:** Syntax highlighting visual studio 2017 v15.5.6 Net Core project witf tsconfig.json

**Code**
![image](https://user-images.githubusercontent.com/10037514/36145779-b006e07a-10b2-11e8-9287-3c78f79e54c8.png)

**Expected behavior:**
Expected normal highlighting...

**Actual behavior:**
No syntax highlighting...
The intellisense  is working (or resharper I am not sure) for giving suggestions during typing. It also correctly detects if a certain import is incorrect (path) and it does not compile when errors are present. So it truly is only about the highlighting.

**Related Issues:**
#20680
Tried deleting cache, didn't work, I could not find the "Visual Studio Extension for Textmate Grammars" extension to actually install it, probably only for visual studio code.
 #18130 
Visual studio 2017 Enterprise v15.5.6
I installed TS SDK 2.7.1
Typescript Tools for Visual Studio version 15.5.11025.1
Resharper 2017.3.2
#14523
Almost same findings as him, instead I use a student license. Currently not signed in inside visual studio, only into VSO git service.
I don't have a folder with "%userprofile%.vs\.... (yes I checked hidden files), so I also don't have the mentioned extension that could cause the problem.
#14422

Number one solution would be updating Typescript, but my computer at home does not have the issue.
Also tried to disable the Language Service (Options->Text Editor->JavaScript/TypeScript->Language Service) but that didn't help either. mentioned [here](https://developercommunity.visualstudio.com/content/problem/32425/javascript-syntax-highlighting-it-not-working.html)

**Comment by mhegazy** [comment]
Can you confirm that the "Visual Studio Extension for Textmate Grammars" extension is enabled?

**Comment by Ruud-cb** [comment]
Wauw,, my assumptions were incorrect. Googling this to download it only shows a VSCode version. Turns out it installs automatically with VS2017, yet it was disabled (WHY?), enabling it via Tools -> Extensions & Updates did the trick. Nice waste of time today...

**Comment by saliehendricks** [comment]
This saved me from hurting myself! Thanks for the tip. Enabling "Visual Studio Extension for Textmate Grammars" fixed my syntax highlighting woes
