### ISSUE TITLE
Readonly<T> problem with Typescript 2.7

### ISSUE THREAD

**Issue by wmoulin** [Microsoft/TypeScript#21920]
**TypeScript Version:**  2.7.1

**Search Terms:** 
Readonly<T>

**Code**
```ts

class SuperMyClass { 
    test: Readonly<Test>;
    constructor() {
        this.test = {a:"a", b: "b"};
    }
}

class MyClass extends SuperMyClass { 
    constructor() {
        super();
        this.test.a = ""; // don't work but KO, I'm in contructor 
                          // Error TS : Cannot assign to 'a' because it is a constant or a read - only property
        this.test = {a:"a", b: "b"}; // Work
    }
    aMethod(): void {
        this.test.a = ""; // don't work but OK, I'm not in contructor
    }
}


interface Test {
    a?: string;
    b?: string;
}

```

**Expected behavior:**

I want to initialize only props 'a' in the constructor of the child class. 

**Actual behavior:**
Error typescript:
Cannot assign to 'a' because it is a constant or a read - only property

**Playground Link:** 
https://www.typescriptlang.org/play/index.html#src=%0D%0Aclass%20SuperMyClass%20%7B%20%0D%0A%20%20%20%20test%3A%20Readonly%3CTest%3E%3B%0D%0A%20%20%20%20constructor()%20%7B%0D%0A%20%20%20%20%20%20%20%20this.test%20%3D%20%7Ba%3A%22a%22%2C%20b%3A%20%22b%22%7D%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aclass%20MyClass%20extends%20SuperMyClass%20%7B%20%0D%0A%20%20%20%20constructor()%20%7B%0D%0A%20%20%20%20%20%20%20%20super()%3B%0D%0A%20%20%20%20%20%20%20%20this.test.a%20%3D%20%22%22%3B%20%2F%2F%20don%27t%20work%20but%20KO%2C%20I%27m%20in%20contructor%20%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20Error%20TS%20%3A%20Cannot%20assign%20to%20%27a%27%20because%20it%20is%20a%20constant%20or%20a%20read%20-%20only%20property%0D%0A%20%20%20%20%20%20%20%20this.test%20%3D%20%7Ba%3A%22a%22%2C%20b%3A%20%22b%22%7D%3B%20%2F%2F%20Work%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20aMethod()%3A%20void%20%7B%0D%0A%20%20%20%20%20%20%20%20this.test.a%20%3D%20%22%22%3B%20%2F%2F%20don%27t%20work%20but%20OK%2C%20I%27m%20not%20in%20contructor%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0A%0D%0Ainterface%20Test%20%7B%0D%0A%20%20%20%20a%3F%3A%20string%3B%0D%0A%20%20%20%20b%3F%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Avar%20myClass%20%3D%20new%20MyClass()%3B%0D%0A%0D%0Aconsole.log(myClass.toString())%3B%20%2F%2FKenobi

**Related Issues:**

**Comment by andy-ms** [comment]
It would be a bad idea to allow that because we don't know that `test` is "owned" by the class containing it -- it could be a reference to an object elsewhere, and we don't want to allow you to mutate that external object via a `Readonly` reference. Consider this example:
```ts
interface Point { readonly x: number; readonly y: number };
const ORIGIN: Point = { x: 0, y: 0 };
class A { constructor(p: Point) {} }
class B extends A { constructor(p: Point) { super(p); p.x = 1; } }
new B(ORIGIN);
```

In order to ensure that the original object isn't modifier, but to avoid changing the values of other properties, you could use the spread operator: `this.test = { ...this.test, a:"" };`.
