### ISSUE TITLE
Suggestion: support function overloading in type annotation comments

### ISSUE THREAD

**Issue by douglas-treadwell** [Microsoft/TypeScript#21921]
I'm adding type annotations to a JS codebase, and one problematic case I've come across is that I cannot overload function signatures using comment-based annotations.

```js
/** @type {(flag: true) => integer;} */
/** @type {(flag: false) => string;} */
function getResult(asInteger) {
   // do stuff here
}
```

The workaround for now would be splitting the function into two functions, or type-casting at each use of the function.  So far my choice will be to split the function.

**Comment by goodmind** [comment]
Isn't this the same issue? https://github.com/Microsoft/TypeScript/issues/407

**Comment by mhegazy** [comment]
indeed. closing in favor of #407
