### ISSUE TITLE
TS6133: 'T' is declared but its value is never read

### ISSUE THREAD

**Issue by yortus** [Microsoft/TypeScript#21931]
**TypeScript Version:**  2.8.0-dev.20180213

**Search Terms:** 
- TS6133

**Code**

```ts
interface A<T> { T: T } // ERROR
//         ^^^ TS6133: 'T' is declared but its value is never read.

type B<T> = { T: T };   // OK
```

**Expected behavior:**
No errors.

**Actual behavior:**
TSC thinks the generic type `T` is unused in `interface A`, but it is used. Meanwhile the equivalent `type B` gets it right.

**Comment by andy-ms** [comment]
It looks like this actually does work in `typescript@2.8.0-dev.20180213` -- was broken in `typescript@2.7.1` though.

**Comment by yortus** [comment]
@andy-ms I'm definitely repro'ing this in `typescript@next`. Can you take another look please?

![ts6133](https://user-images.githubusercontent.com/1252361/36237014-5b3f3b40-1234-11e8-807e-e7da37731a65.png)

**Comment by andy-ms** [comment]
Oh, sorry, this was changed to `--noUnusedParameters` instead of `--noUnusedLocals` (#21167) so the error went away for me.
