### ISSUE TITLE
Unknown compiler option 'strictPropertyInitialization'

### ISSUE THREAD

**Issue by movedoa** [Microsoft/TypeScript#21938]
TypeScript 2.7.1
I have strict enabled but strictPropertyInitialization set to false.
This works as expected but outputs the error "error TS5023: Unknown compiler option 'strictPropertyInitialization'."

This is my tsconfig.json

```
{
   "compilerOptions": {
      "target": "es5",
      "module": "none",
      "moduleResolution": "Classic",
      "isolatedModules": false,
      "jsx": "preserve",
      "experimentalDecorators": false,
      "emitDecoratorMetadata": false,
      "declaration": false,
      "noImplicitUseStrict": false,
      "removeComments": true,
      "noLib": false,
      "preserveConstEnums": false,
      "suppressImplicitAnyIndexErrors": true,
      "noUnusedLocals": true,
      "noImplicitReturns": true,
      "noFallthroughCasesInSwitch": true,
      "outFile": "moveit/Monti/Monti.js",
      "strict": true,
      "noUnusedParameters": false,
      "forceConsistentCasingInFileNames": true,
      "strictPropertyInitialization": false
   },
   "filesGlob": [
      "moveit/Lib/jquery/jquery.d.ts",
      "moveit/Lib/Kendo/kendo.all.d.ts",
      "moveit/Monti/OeApi.d.ts",
      "**/*.ts"
   ],
   "exclude": [
      "node_modules",
      "typings/browser",
      "typings/browser.d.ts",
      "**/MontiLoader.ts",
      "**/Heartbeat.ts"
   ],
   "compileOnSave": true,
   "buildOnSave": true
}
```

**Comment by andy-ms** [comment]
I didn't get such an error when using that `tsconfig.json` with `typescript@2.7.1`. Are you sure that's the version you're using? You can check with `tsc --version`.

**Comment by movedoa** [comment]
ok, yes my bad, someone messed up the workspace configuration
Sorry for the hassle

**Comment by mislavzlatar** [comment]
I have same issue with tsc --version 2.7.1 please help!

**Comment by movedoa** [comment]
So you type tsc --version in the exact same console where you execute the compile command?

**Comment by mislavzlatar** [comment]
Yes, error happens when I run npm test. I had old tsc version and updated to 2.7, restarted vscode, error is still here. When I comment strictPropertyInitialization, tsc compiles

TSError: ⨯ Unable to compile TypeScript
Unknown compiler option 'strictPropertyInitialization'. (5023)

**Comment by andy-ms** [comment]
`npm test` will probably be using a local install of `typescript` instead of the globally installed one. Check what's in `node_modules/typescript/package.json`.

**Comment by mislavzlatar** [comment]
You are right I see in there   "_id": "typescript@2.6.2"

How to update local typescript?

Thanks

**Comment by andy-ms** [comment]
Update your `package.json` to require a newer TypeScript version, then `npm install`.

**Comment by mislavzlatar** [comment]
I am such a dummy..installed typescript globally but never did --save-dev. Thanks it's ok now :)

**Comment by kuncevic** [comment]
got that error with `2.6.2` and cant curretnly migreate to `2.7.x` does that option is `2.7` specific?
