### ISSUE TITLE
Type inference in conditional types doesn't respect constraints

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#21937]
cc @ahejlsberg 

**TypeScript Version:**  master

**Search Terms:** 

**Code**

```ts
type A<T extends string[]> = T extends Array<infer U> ? Record<U, {}> : never;
```

**Expected behavior:**

pass

**Actual behavior:**

```
$ node built/local/tsc.js --noEmit index.ts
index.ts(1,64): error TS2344: Type 'U' does not satisfy the constraint 'string'.
```

**Playground Link:**  

**Related Issues:**

**Comment by jcalz** [comment]
Related to #21729 ?

**Comment by DanielRosenwasser** [comment]
I'll let Anders decide if this is a dupe or not.

**Comment by falsandtru** [comment]
I think type parameter constraints and type narrowing by conditional types are different.

**Comment by ahejlsberg** [comment]
I'm going to call this working as intended. While it *might* be possible to transfer constraints when the checked type is a simple type variable, it's not clear how we could do it in the general case. Also, it's quite easy to manually add the constraint:

```ts
type A<T extends string[]> =
    T extends Array<infer U> ? U extends string ? Record<U, {}> : never : never;
```

Or, now that we have #22323:

```ts
type StringArray<T extends string> = T[];
type A<T extends string[]> = T extends StringArray<infer U> ? Record<U, {}> : never;
```
