### ISSUE TITLE
String Based Enum - Reverse Mapping Problem

### ISSUE THREAD

**Issue by kannanwisen** [Microsoft/TypeScript#21935]
My TypeScript Version is 2.7.1

1. enum Country{
2.     India = "INR",
3.     France = "EUR",
4.     USA = "USD",
5.     Germany = France
6. }
7. let vx : Country = Country.India;
8. console.log("vx is "+vx);
9. console.log("enum name is "+Country[vx]);

The output are as follows

vx is INR
enum name is undefined

In Line 9, the reverse mapping is not working for string based enum.

Thanks

Kannan Wisen

**Comment by j-oliveras** [comment]
String enums has no reverse mapping.

See last part of entry post of #15486.

**Comment by kannanwisen** [comment]
Thanks for your information

**Comment by marcelh-gh** [comment]
@RyanCavanaugh Hi! Could you please explain, why the TS team insists on string enums not having reverse mapping functionality? I have found lots of discussions about it but did not find the rationale behind the decision. Thanks a lot! Cheers, Marcel

**Comment by RyanCavanaugh** [comment]
If we provided the reverse map automatically (which, by the way, is not necessarily non-ambiguous!), then you'd have no way to distinguish keys from values unless there was a completely separate object created at runtime. It is trivial to write a function that constructs the reverse map if you want it; our goal is to emit as little code as possible so it makes sense to just emit the data you *need* (to keep code size down) and let you construct the reverse map on an as-needed basis.

**Comment by marcelh-gh** [comment]
@RyanCavanaugh That makes sense. Thanks a lot for the explanation! :-)
