### ISSUE TITLE
API: expose SourceFile#parseDiagnostics

### ISSUE THREAD

**Issue by ajafff** [Microsoft/TypeScript#21940]
**Search Terms:** parseDiagnostics

Currently there's no API to directly get the `parseDiagnostics` of a SourceFile.
The only possible solution is creating a Program with this SourceFile and call `program.getSyntacticDiagnostics(sourceFile)`...

This is especially painful when using `ts.parseJsonText` or `ts.readJsonConfigFile` where I need to check for parseDiagnostics.

Is there a reason this property is internal? Given that it's always set, I think it's safe to expose it.

---

Related question: why is `getJavaScriptSyntacticDiagnosticsForFile` declared in `program.ts` and not directly exposed directly? This function doesn't rely on Program, TypeChecker, Resolver, or Binder.
If I want all syntax errors of a JavaScript file, I need to create a Program first.

You could resolve both issues by just exposing `getSyntacticDiagnostics` as a function from `program.ts` (or moving it to a different file).

**Comment by DanielRosenwasser** [comment]
Thoughts @sheetalkamat and @mhegazy? In general, I want us to make it easier to use our API for single-file scenarios.

**Comment by mhegazy** [comment]
These APIs are intentionally hidden to limit our API surface area. the config diagnostics should be available now, do not think there is a need to open up more APIs.

**Comment by ajafff** [comment]
@mhegazy I understand your concerns about API surface. But is it really intended that I always need to create a Program to be able to retrieve parseDiagnostics and syntacticDiagnostics?

**Comment by mhegazy** [comment]
yes. in the future we could move some of the grammar checks out of the checker and into the binder for instance, and we would want these to be reported as syntactic for instance.. The API layering is rely intentional.
