### ISSUE TITLE
HTMLAnchorElement Missing Origin

### ISSUE THREAD

**Issue by ChrisTalman** [Microsoft/TypeScript#21943]
The [type definition](https://github.com/Microsoft/TypeScript/blob/master/lib/lib.d.ts#L8060) for `HTMLAnchorElement` seems to be missing the `origin` property which it should have [according to MDN](https://developer.mozilla.org/en-US/docs/Web/API/HTMLAnchorElement).

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.
