### ISSUE TITLE
Infer type guards from `instanceof` and other such expressions

### ISSUE THREAD

**Issue by chuckjaz** [Microsoft/TypeScript#21956]
Consider the following from [here](http://www.typescriptlang.org/play/index.html#src=class%20A%20%7B%0D%0A%20%20%20%20a%3A%20number%3B%0D%0A%7D%0D%0A%0D%0Aclass%20B%20%7B%0D%0A%20%20%20%20b%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Afunction%20isA(v%3A%20any)%3A%20v%20is%20A%20%7B%0D%0A%20%20%20%20return%20v%20instanceof%20A%3B%20%20%20%20%0D%0A%7D%0D%0A%0D%0Afunction%20isB(v%3A%20any)%3A%20v%20is%20B%20%7B%0D%0A%20%20%20%20return%20v%20instanceof%20B%3B%0D%0A%7D%0D%0A%0D%0Aconst%20asAndBs%20%3D%20%5Bnew%20A()%2C%20new%20B()%2C%20new%20A()%2C%20new%20B()%5D%3B%0D%0A%0D%0Aconst%20allAs%20%3D%20asAndBs.filter(isA)%3B%20%2F%2F%20A%5B%5D%0D%0Aconst%20allBs%20%3D%20asAndBs.filter(isB)%3B%20%2F%2F%20B%5B%5D%0D%0A%0D%0Aconst%20allAs2%20%3D%20asAndBs.filter(v%20%3D%3E%20v%20instanceof%20A)%3B%20%2F%2F%20(A%20%7C%20B)%5B%5D%0D%0Aconst%20allBs2%20%3D%20asAndBs.filter(b%20%3D%3E%20v%20instanceof%20B)%3B%20%2F%2F%20(A%20%7C%20B)%5B%5D%0D%0A):

```ts
const asAndBs = [new A(), new B(), new A(), new B()];
const allAs = asAndBs.filter(v => v instanceof A); 
```
The type of `allAs` is `(A | B)[]` where it would be more accurately typed as `A[]`. If a type-guard was used,

```ts
function isA(v: any): v is A {
    return v instanceof A;    
}

const allAs = asAndBs.filter(isA);
```

then the type would be `A[]` as expected. 

Getting the correct type from `filter` requires using the verbose form `filter(isA)` instead of the more terse form `filter(v => v instanceof A)`.

**Suggestion**

Infer a guard from lambdas that imply a type narrowing if used in an `if` statement.

For example,

```ts
const a = (v: any) => v instanceof Class;
```

would infer `a` to be of type `(v: any) => v is Class`.

```ts
const b = (v: any) => typeof v === 'string'
```

would infer `b` to be type `(v: any) => v is string`;

This would allow useful typing of:

```ts
const loweredStrings = someArray.filter(v => typeof v === 'string').map(v => v.toLower());
```

**Comment by jcalz** [comment]
One of many duplicates of #5101.  Did you try to search for related issues before posting this?

**Comment by chuckjaz** [comment]
I tried. My search foo is clearly lacking.

**Comment by jcalz** [comment]
Sure.  I only ask because the issue posting template asks you to list what search terms you used... well, I guess it says that specifically for bug reports as opposed to suggestions.  

I have this fantasy that one day we will find the [magic wording](https://github.com/Microsoft/TypeScript/issues/21199#issuecomment-358025610) that eliminates duplicate issues while still encouraging legitimate bug reports and suggestions.  But sadly it is only a dream.

**Comment by aluanhaddad** [comment]
@jcalz sophisticated lexical analysis should be employed by GitHub searches :)
