### ISSUE TITLE
It is a compile time error for constant enum expressions to be evaluated to NaN or Infinity. 

### ISSUE THREAD

**Issue by kannanwisen** [Microsoft/TypeScript#21959]
Hi,

The documentation says

It is a compile time error for constant enum expressions to be evaluated to NaN or Infinity.

But the below code does not throw any compile time error

```ts
enum FMixed {
    Data1 = 10 + 0.0 / 0.0,
    Data2 = 0 / 0,
    Data3 = 10 / 0.0
}

console.log("FMixed.Data1 is "+FMixed.Data1);
```
TypeScript Version is 2.7.1

**Comment by RyanCavanaugh** [comment]
> It is a compile time error for  ⭐️ **constant** ⭐️  enum expressions to be evaluated to NaN or Infinity

```ts
// no 'const' keyword...
enum FMixed {
```

**Comment by kannanwisen** [comment]
Better to disallow NaN and Infinity in enum member value
