### ISSUE TITLE
Generic is not inferred consistently when used as part of intersection type

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/TypeScript#21964]
**TypeScript Version:**  2.7.1

**Search Terms:** generic subtraction inference intersection

**Code**

Given a function that receives a parameter which is an intersection type of a generic and some interface, generic inference does not behave consistently.

```ts
type UserProp = { user: {} };
declare const myHoc: <PropsWithoutUser>(
    props: UserProp & PropsWithoutUser,
) => PropsWithoutUser;

{
    type MyPropsWithoutUser = { dog: {} };
    type MyProps = UserProp & MyPropsWithoutUser;

    const myProps: MyProps = { user: {}, dog: {} };
    // Correctly inferred as `MyPropsWithoutUser`, as expected
    const result = myHoc(myProps);
}

{
    const myProps: UserProp & { dog: {} } = { user: {}, dog: {} };
    // Correctly inferred as `MyPropsWithoutUser`, as expected
    const result = myHoc(myProps);
}

{
    const myProps = { user: {}, dog: {} };
    // Correctly inferred as `MyPropsWithoutUser`, as expected
    const result = myHoc<{ dog: {} }>(myProps);
}

{
    const myProps = { user: {}, dog: {} };
    // Expected `result` to be inferred as `{ dog: {} }`, but instead got `{ user: {}, dog: {} }`
    const result = myHoc(myProps);
}
```

**Comment by OliverJAsh** [comment]
My workaround is to work the opposite way and omit the property explicitly instead:

``` ts
import { ObjectOmit } from 'typelevel-ts';

type UserProp = { user: {} };

declare const myHoc2: <Props extends UserProp>(
  props: Props,
) => ObjectOmit<Props, 'user'>;

{
  const myProps = { user: {}, dog: {} };
  // Correctly inferred as `MyPropsWithoutUser`, as expected
  const result = myHoc2(myProps);
}
```

**Comment by OliverJAsh** [comment]
Actually that workaround isn't ideal because it's not as strict.

**Comment by OliverJAsh** [comment]
Any updates on this? I'm seeing the behaviour quite often, particularly when using React HOCs like React Router's `withRouter`.

**Comment by OliverJAsh** [comment]
Example of how this is causing issues: the typings for React Router's `withRouter` HOC had to workaround this issue https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21329/files#diff-bc5f906a3af0cde1a95a8a23cb993e96R107.

**Comment by mhegazy** [comment]
inference with intersection type is rather simple. if when inferring to `T & U` from `T' & U` it will indfer from `T'` to `T`, and that is that. in cases where inferring to `T & U` from `S`, it will infer from `S` to both `T` and `U`, and will not try to decompose `S` to not have members in `U`.

Not knowing much about the context, it seems you just want to make sure the output of `myHoc` does not contain `user`. and you can do something like that using `Pick` and `Exclude`:

```ts
declare const myHoc: <PropsWithoutUser>(
    props: PropsWithoutUser,
) => Pick<PropsWithoutUser, Exclude<keyof PropsWithoutUser, "user">>;
```

**Comment by OliverJAsh** [comment]
@mhegazy Thanks for the explanation. I'll use `ObjectOmit`/`Exclude` instead.
