### ISSUE TITLE
Union type of function and tuple does not work

### ISSUE THREAD

**Issue by manudwarf** [Microsoft/TypeScript#21963]
(please note: this is my first ticket on TypeScript, I did some search but I couldn't find any similar issue)

Typescript version: 2.7 (did not try earlier versions)

Consider the following code ([Playground](https://goo.gl/Btgh4S)):
```typescript
type TCriterion = (item: any) => boolean | [string, any];
type TCriterionTuple = [string, any];

const t1: TCriterion = (item) => true;           # Works ok
const t2: TCriterion = ['someNumber', 123];      # Throws an error, even though it is correct
const t3: TCriterionTuple = ['someNumber', 123]; # Works ok
```

The compiler accepts my type declaration, but rejects assigning a tuple that matches its definition.

Alternatively, this syntax:
```typescript
type TCriterion = [string, any] | (item: any) => boolean;
```
Completely fails in the compiler.

This solves the issue:
```typescript
type TCriterionTuple = [string, any];
type TCriterionCallback = (item: any) => boolean;
type TCriterion = TCriterionTuple | TCriterionCallback;
```

**Comment by jack-williams** [comment]
The union type is binding tighter than the function type. Try:

```ts
type TCriterion = ((item: any) => boolean) | [string, any];
```

**Comment by manudwarf** [comment]
Correct, thanks!

Apologies for the superfluous ticket, I'll close it.
