### ISSUE TITLE
Slow quickInfo for lodash

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#21968]
**TypeScript Version:**  2.8.0-dev.20180215

**Code**

(first `@types/lodash@4.14.102`)
```ts
import _ = require("lodash");
const x = _({} as any).pick(["x"])
x
```
* Hover over `x`, get quick info.
* Add a semicolon after `x` and hover over it again. It will take a second.

First noticed in https://github.com/DefinitelyTyped/DefinitelyTyped/issues/23344#issuecomment-363694438, thanks @wuyiw

**Comment by sheetalkamat** [comment]
This does not repro for me any more. 
![quickinfo](https://user-images.githubusercontent.com/8052792/39455162-f107376a-4c93-11e8-8586-ce49550f6057.gif)

**Comment by andy-ms** [comment]
Me neither.
