### ISSUE TITLE
Child property setter without getter does not work

### ISSUE THREAD

**Issue by floribon** [Microsoft/TypeScript#21980]
If a child class overrides a setter without the getter, getting the value does not work anymore.
Either removing the setter or adding a getter in the Child class fixes the issue.
A default getter returning super.value would make sense.

**TypeScript Version:**  2.7.2

**Search Terms:** 
setter getter inheritance

**Code**

```ts
class Parent {
  private _value: number;
  set value(v: number) {
    this._value = v;
  }
  get value() {
    return this._value;
  }
}

class Child extends Parent {
  set value(v) {
    super.value = v;
  }
}

var child = new Child();
child.value = 42;
alert('Child value: ' + child.value);
```

**Expected behavior:**
Child value: 42

**Actual behavior:**
Child value: undefined

**Playground Link:**
https://www.typescriptlang.org/play/#src=class%20Parent%20%7B%0D%0A%20%20private%20_value%3A%20number%3B%0D%0A%20%20set%20value(v%3A%20number)%20%7B%0D%0A%20%20%20%20this._value%20%3D%20v%3B%0D%0A%20%20%7D%0D%0A%20%20get%20value()%20%7B%0D%0A%20%20%20%20return%20this._value%3B%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Aclass%20Child%20extends%20Parent%20%7B%0D%0A%20%20set%20value(v)%20%7B%0D%0A%20%20%20%20super.value%20%3D%20v%3B%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Avar%20child%20%3D%20new%20Child()%3B%0D%0Achild.value%20%3D%2042%3B%0D%0Aalert('Child%20value%3A%20'%20%2B%20child.value)%3B

**Comment by RyanCavanaugh** [comment]
This is the defined ES6 class behavior. Try running a version without type annotations in your browser console.

**Comment by floribon** [comment]
Indeed, it's a strange behavior but not related to TypeScript, thanks.
