### ISSUE TITLE
ReturnType<ReturnType<>> in type alias results in never

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#21997]
**TypeScript Version:**  2.8.0-dev.20180216

**Search Terms:** ReturnType conditional type

**Code**

```ts
export {};
type ReturnType<T extends (...args: any[]) => any> = T extends (...args: any[]) => infer R ? R : any;
type ReturnTypeReturnType<T extends (...args: any[]) => (...args: any[]) => any> = ReturnType<ReturnType<T>>;
type Expected = ReturnType<ReturnType<() => () => "abcdef">>; // correctly `"abcdef"`
type Actual = ReturnTypeReturnType<() => () => "abcdef">; // `never`
const x: Actual = "abcdef"; // Error
```

**Expected behavior:**

`Actual` same as `Expected`.

**Actual behavior:**

`Actual` is `never`.

The issue may be fixed by changing the definition of `ReturnType` to be ` T extends (...args: any[]) => infer R ? R : never;`. Based on the rules in #21496 the behavior with `any` may be by design, but the global `ReturnType` definition currently uses `any`, so maybe the fix should be in `lib.d.ts`.

**Comment by falsandtru** [comment]
I think anyway `ReturnTypeReturnType<() => () => "abcdef">` shouldn't reach `any`. So we don't have to fix the `ReturnType` definition.

**Comment by mhegazy** [comment]
I can not reproduce this on latest.
