### ISSUE TITLE
[2.8.0-dev.20180216] Arguments with mixin type?

### ISSUE THREAD

**Issue by SamuraiJack** [Microsoft/TypeScript#21994]
```typescript
type Constructable<T = {}> = new (...args : any[]) => T

class Some {}

export const Mixin1 = (T : Constructable) => class OtherModel extends T {
    method1() {}
}

export const Mixin2 = (T : Constructable) => class DiffableModel extends T {
    method2() {}
}

class Test extends Mixin2(Mixin1(Some)) {
    some () {
        this.method1()
    }

}

let obj = new Test()

const func = (m : InstanceType<ReturnType<typeof Mixin1>>) => false;

func(obj) // fails here 

```
The code above does not compile. Any advise how to express this functionality in types?

The intention is to use mixins, and to declare an argument to the function, that is of type, that includes certain mixin. Now that works, but when passing a value, that implements a mixin, a call fails.

**Comment by SamuraiJack** [comment]
The goal is to emulate the haskell typeclasses.

It seems the problem is that `Test` class does not "understand" that it "inherit" from the "Mixin1". But it does know about the "Mixin2" though.

**Comment by andy-ms** [comment]
See https://blog.mariusschulz.com/2017/05/26/typescript-2-2-mixin-classes for an example -- the mixin functions need to be generic or else they just return `typeof OtherModel` and `typeof DiffableModel`.

**Comment by SamuraiJack** [comment]
No, thats not related, same thing:
```
type Constructable<T = {}> = new (...args : any[]) => T

class Some {}

function Mixin1<T extends Constructable>(T : Constructable) {
    return class OtherModel extends T {
        method1() {}
    }
}

function Mixin2<T extends Constructable>(T : Constructable) { 
    return class DiffableModel extends T {
        method2() {}
    }
}

class Test extends Mixin2(Mixin1(Some)) {
    some () {
        this.method1()
    }

}

let obj = new Test()

const func = (m : InstanceType<ReturnType<typeof Mixin1>>) => false;

func(obj)
```

**Comment by andy-ms** [comment]
You need to write `T: T` not `T: Constructable`.

**Comment by SamuraiJack** [comment]
Ah, indeed!

Thank you for the help!

**Comment by andy-ms** [comment]
Welcome. Also helped me discover an issue #21995.

**Comment by SamuraiJack** [comment]
Can you perhaps elaborate a bit on ```the mixin functions need to be generic or else they just return typeof OtherModel and typeof DiffableModel```? 

In my initial attempt it was:
```(Base : Constructable) => class OtherModel extends Base```

And correct way is
```function Mixin1<T extends Constructable>(Base : T) {```

The difference is quite subtle for me, `Base : T = Constructable` vs `Base : T extends Constructable`.

**Comment by andy-ms** [comment]
If `Base` is just `Constructable`, we don't know any thing about the particular type of `Base`. So, we don't know what methods a class inheriting from it will inherit. So you just get the methods defined in the mixin and no inherited methods.
But if you extend from `T`, once you fill in a particular value of `T`, we can correctly fill in the type of the class extending from it, so it will have both the methods of `T` and the methods of the mixin.

**Comment by SamuraiJack** [comment]
Ok, I see.

Now one more question if you don't mind. So this code works fine:
```typescript
type Constructable<T = {}> = new (...args : any[]) => T

class Some {}

function Mixin1<T extends Constructable>(Base : T) {
    return class OtherModel extends Base {
        method1() {}
    }
}

function Mixin2<T extends Constructable>(Base : T) {
    return class DiffableModel extends Base {
        method2() {}
    }
}

class Test extends Mixin2(Mixin1(Some)) {
    some () {
        this.method1()
    }

}

let obj = new Test()

const func = (m : InstanceType<ReturnType<typeof Mixin1>>) => false;

func(obj)
```

Now, I want to define an alias, like:
```typescript
export type Mixin<T> = InstanceType<ReturnType<T>>
```
But
```
error TS2344: Type 'T' does not satisfy the constraint '(...args: any[]) => any'
```
Trying 
```typescript
export type Mixin<T extends (...args:any[]) => any> = InstanceType<ReturnType<T>>
```
solves the above, but:

```typescript
const func1 = (m : Mixin<typeof Mixin1>) => false;

func1(obj)
```
fails with:
```
error TS2345: Argument of type 'Test' is not assignable to parameter of type 'never'.
```

**Comment by SamuraiJack** [comment]
I would expect the alias to behave more like a "macros"?

**Comment by andy-ms** [comment]
@SamuraiJack That looks like a bug: #21997. You can work around it with:
```ts
// Fixed, see https://github.com/Microsoft/TypeScript/issues/21997
type ReturnType<T extends (...args: any[]) => any> = T extends (...args: any[]) => infer R ? R : never;
type InstanceType<T extends new (...args: any[]) => any> = T extends new (...args: any[]) => infer R ? R : never;
export type Mixin<T extends (...args:any[]) => any> = InstanceType<ReturnType<T>>;
```

**Comment by SamuraiJack** [comment]
Thanks!
