### ISSUE TITLE
Incorrect output with C-style comments

### ISSUE THREAD

**Issue by NN---** [Microsoft/TypeScript#2200]
In the playground:
http://www.typescriptlang.org/Playground#src=/*%20abc%20*/%0Avar%20a%20=%201;%0A/**/

```typescript
/* abc */
var a = 1;
/**/
```
It produces
```javascript
/* abc */
var a = 1;
/* abc */
var a = 1;
 ```

**Comment by mhegazy** [comment]
looks like the same as #1714.
