### ISSUE TITLE
New Website Logo: RISE VISION PLC

### ISSUE THREAD

**Issue by jolie7** [Microsoft/TypeScript#22010]
Please fill the following out:

- Name: RISE VISION PLC
- Homepage url: https://rise.vision/
- Brand Guidelines/Licensing: N/A
- Logo: https://goo.gl/images/R1GysD
![rise logo text](https://user-images.githubusercontent.com/36559341/36338616-1e7178a6-13ef-11e8-9626-db7ca7e07aa4.png)

**Comment by jolie7** [comment]
RISE is one of the first blockchain projects written in TypeScript.

**Comment by jolie7** [comment]
You can check out our code conversion here: https://github.com/RiseVision/rise-node
We will be releasing our new website soon too, which will talk more about our use of TypeScript.

**Comment by mhegazy** [comment]
Thanks. Added to the site. Should be live next week.
