### ISSUE TITLE
JSX: TS1127 for <>#</>

### ISSUE THREAD

**Issue by uhyo** [Microsoft/TypeScript#22012]
**TypeScript Version:**  Version 2.8.0-dev.20180217

**Search Terms:** TS1127, jsx invalid character 

**Code**

```ts
const elm = (<>#</>);
```

**Expected behavior:**
Compile with no error.

**Actual behavior:**
`test.tsx(1,16): error TS1127: Invalid character.`

**Related Issues:** #4207

Thanks.

**Comment by radix** [comment]
I reproduced this with `<>#</>`, and also with emojis like `<>🙂</>`.

**Comment by radix** [comment]
also note that this seems to be specific to fragment syntax, since `<span>🙂</span>` works fine.
