### ISSUE TITLE
Collision when inferring numerical enum value

### ISSUE THREAD

**Issue by bcherny** [microsoft/TypeScript#22015]
**Search Terms:** enum, number, index

**Code**

```ts
enum Language {
  English,
  Spanish = 1,
  Russian,
  Mandarin = 2
}
```

**Expected behavior:**

TSC should either:

1. Infer `Russian`'s value as `3`, or
2. Throw `Enum member must have initializer.` on `Russian`.

I like (2).

**Actual behavior:**

TSC generates the following code (note the generated collision on `2`):

```ts
var Language;
(function (Language) {
    Language[Language["English"] = 0] = "English";
    Language[Language["Spanish"] = 1] = "Spanish";
    Language[Language["Russian"] = 2] = "Russian";
    Language[Language["Mandarin"] = 2] = "Mandarin";
})(Language || (Language = {}));
```

**Playground Link:** https://www.typescriptlang.org/play/index.html#src=enum%20Language%20%7B%0A%20%20English%2C%0A%20%20Spanish%20%3D%201%2C%0A%20%20Russian%2C%0A%20%20Mandarin%20%3D%202%0A%7D

**Comment by RyanCavanaugh** [comment]
Not going to take a breaking change on this
