### ISSUE TITLE
Feature suggestion: Report unused suppressions

### ISSUE THREAD

**Issue by AriaMinaei** [Microsoft/TypeScript#22021]
When using advanced types such as conditional types, I usually write a bunch of type tests to check for which conditions the annotations are supposed to pass/fail. Example:

![image](https://user-images.githubusercontent.com/593118/36350001-bec54bde-148f-11e8-88a7-9798dbfd5807.png)

As you see, every first statement checks for a condition that's supposed to pass, while every second statement checks for a condition that's correctly supposed to fail.

I'd ideally annotate those second statements with `// @ts-ignore`, except that if the expected type error doesn't happen, I wouldn't know about it. For example if the variable `derivative` is of type `any`, then the type annotations would obviously be wrong, but no errors would be shown.

I propose a compiler flag like `warnUnusedSuppressions: boolean` that would produce a lint error if a line is annotated with `// @ts-ignore` but doesn't contain type errors.

Related issues: #19139, #21602

**Comment by mhegazy** [comment]
This is not the intended use of `// @ts-ignore`. we advice that this feature be used sparingly, and I do not think we want to invest in expanding its support.

If this is a .d.ts file that you are testing, consider using https://github.com/Microsoft/dtslint, with `$ExpectType` assertions.

**Comment by AriaMinaei** [comment]
I see. Thanks for pointing to the correct solution!
