### ISSUE TITLE
Visual studio 2017 intellisense shows errors when tsc.exe compiles fine.

### ISSUE THREAD

**Issue by valeriob** [Microsoft/TypeScript#22031]
visual studio 2017 15.5 or 15.6 preview
Typescript 2.6.2
tsconfig.json with this path config :
```json
"files": [
    "wwwroot/definition.d.ts",
],
"include": [
    ""
],
"exclude": [
    "node_modules",
    "wwwroot",
    "bin",
    "obj"
]
```
Opening a typescript file that references types defined on definition.d.ts it shows error :
Error	TS2304	(TS) Cannot find name 'mynamespace'.

Looks like the files resolution of tsc.exe and intellisense are different.

Repro attached [TypescriptIntellisense.zip](https://github.com/Microsoft/TypeScript/files/1736349/TypescriptIntellisense.zip)

**Comment by mhegazy** [comment]
You only included file ` "wwwroot/definition.d.ts"`. the other file is not included in this compilation. when you build you are not building `index.ts` so you do not get the error, but when you open it in VS you get the error. Please see http://www.typescriptlang.org/docs/handbook/tsconfig-json.html for more details about tsconfig.json

**Comment by valeriob** [comment]
Thanks @mhegazy, i had to add 
"include": [
    "**/*"
]

i could not find in the documentation that if you miss the _file_ section then _include_ is default to **/* and if you just an empty _file_ section _include_ default will be empty 😄
