### ISSUE TITLE
Something is wrong with React typings

### ISSUE THREAD

**Issue by cevek** [Microsoft/TypeScript#22032]
**TypeScript Version:**  2.8.0-dev.20180217

**Code**

```ts
    var Foo!: React.ComponentClass<{a: number}>;
    var Bar: React.ComponentClass = Foo; // Type '{}' is not assignable to type '{ a: number; }'. 
```

**Expected behavior:**
No error

**Actual behavior:**
`Type '{}' is not assignable to type '{ a: number; }'. `

**Playground Link:**  

**Related Issues:**

**Comment by nmain** [comment]
TypeScript 2.7.1 gives the same error if `strictFunctionTypes` is on.  The error seems to be correct; the props type in a `React.ComponentClass` should be contravariant.

**Comment by DanielRosenwasser** [comment]
Providing a better error message is tracked at #21253.
