### ISSUE TITLE
Suggestion: Format markdown inside JSDoc comments.

### ISSUE THREAD

**Issue by NaridaL** [microsoft/TypeScript#22034]
**TypeScript Version:**  typescript@2.8.0-dev.20180217

**Search Terms:** `format jsdoc` `format markdown`

As markdown is used for formatting displayed docs in VS Code and other editors, it would be useful if the TSLS would also format the comments correctly:

**Code**

When formatting the following code in VS Code:
```ts
/**
 * This line is far too long and should be wrapped: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.
 * This line is part of the same paragraph as before and should not start on a separate line.
 *
 * This
 * sentence
 * is
 * spread
 * over
 * too
 * many
 * lines.
 *
   This line is not prefixed by `*`

 * ```
 * this code sample
 * should not be wrapped
 * ```
 */
function foo() { }
```

**Expected behavior:**

The jsdoc should be formatted as follows:
```ts
/**
 * This line is far too long and should be wrapped: Lorem ipsum dolor sit amet,
 * consectetur adipiscing elit, sed do eiusmod tempor incididunt. This line is
 * part of the same paragraph as before and should not start on a separate line.
 *
 * This sentence is spread over too many lines.
 *
 * This line is not prefixed by `*`
 *
 * ```
 * this code sample
 * should not be wrapped
 * ```
 */
function foo() { }
```
**Actual behavior:**
Nothing happens.

**Related Issues:**
https://github.com/Microsoft/TypeScript/issues/11500 About formatting jsdoc itself, while this is more about formatting the content.

**Comment by RyanCavanaugh** [comment]
There doesn't seem to be much demand for this, and messing with people's comments is very likely to upset them. This can be handled by an editor plugin if people are interested to have their comments formatted.
