### ISSUE TITLE
async/await can not be used in  class method definition(without method body)

### ISSUE THREAD

**Issue by vincedan** [Microsoft/TypeScript#22035]
`class BaseClass {
    async created: () => Promise<  string >;
}

BaseClass.prototype.created = () => {
    return await Promise.resolve("OK");
};`

Severity	Code	Description	Project	File	
Error	TS1042	'async' modifier cannot be used here.	TypeScript Virtual Projects	 
Error	TS2322	Type '() => string' is not assignable to type '() => Promise<string>'. Type 'string' is not assignable to type 'Promise<string>'.
Error	TS1308	'await' expression is only allowed within an async function.	TypeScript Virtual Projects

**Comment by vincedan** [comment]
can not change title... here "class method" is not meaning static method... my sample is not also... should be instance/prototype function(method), I guess, for static method of class should have the same issue.

**Comment by yume-chan** [comment]
Your usage is totally wrong.

The `created` member in your `BaseClass` class is a **field**, with type of `() => Promise<string>`, how can a field to be `async`?

The `async` keyword must be used with a function, like `async function doSomething() { /* ... */ }` or `async () => { /* ... */ }`

The `await` keyword can only be used within the body of an `async` function, like the examples above.

In addition, for an `async` function, the return type must be `Promise<T>`, but you only need to `return` a value of type `T`, the compiler/runtime will create a Promise to wrap your return value automatically.

One more thing, you should post your problem to StackOverflow if you don't really understand some feature or don't know why it doesn't work. The GitHub Issue Tracker should only be used when you are at least 90% sure that there is a bug in the project.

**Comment by vincedan** [comment]
thanks @yume-chan  for your reply.  I knew async keywords will wrap function return value as Promise<T> if it is not. here just a sample to demonstrate.  the key thing here is 

> "The async keyword must be used with a function, like async function doSomething() { /* ... */ } or async () => { /* ... */ }  The await keyword can only be used within the body of an async function, like the examples above."   if this is ms offically reply, I will close this issue (I reserve my opinion).

**Comment by vincedan** [comment]
thanks @andy-ms 's response.  if without this feature, I can only use promise-then pattern in concrete method.

**Comment by yume-chan** [comment]
Again, your opinion is totally **WRONG**.

`async` keyword and `Promise` are two **unrelated** things. A function returns a `Promise` doesn't mean it must be `async`.

----

The `async` and `await` keywords are syntactic sugar for using `Promise` without chaining `then()` calls.

``` js
async function doSomething() {
    await Promise.resolve("OK");
    alert("done");
}
```

Is semantically equals to

``` js
function doSomething() {
    Promise.resolve("OK").then(() => {
        alert("done");
    });
}
```

----

So as I have said above, your **field** `created` cannot be marked with `async` because it's not a function, and your value for `BaseClass.prototype.created` must be marked with `async` to use `await`.

``` js
class BaseClass {
    created: () => Promise<string>; // NO async here
}

BaseClass.prototype.created = async () => { // async HERE
    retrun await Promise.resolve("OK");
}
```

----

Or, you should just declare your function body in the class

``` js
class BaseClass {
    async created(): Promise<string> {
        retrun await Promise.resolve("OK");
    }
}
```

Which I have also said above. (Why don't you do this when you are already using `class`?)

**Comment by vincedan** [comment]
Hi, yume-chan , I guess you still don't understand my question.   [created] here is not a field. it is method with itself method signature...   I think I need to reopen this question. need  **senior stuff** to check it again.
I was wondered that I need to paste the source code.please check the following.
`class BaseClass {
    public async created(str: string) { };  //OK
    public created1: (str: string) => void; //OK
    public async created2: (str: string) => void; //Wrong TS1042:'async' modifier cannot be used here

}
BaseClass.prototype.created = async (str2) => {
    //OK
};
BaseClass.prototype.created1 = (str2) => {
    //OK
};
BaseClass.prototype.created2 = async (str2) => {
    //OK
};`

**Comment by yume-chan** [comment]
Please check ecma-262 chapter [14.6 Class Definitions](https://tc39.github.io/ecma262/#prod-ClassElement), if it's a method definition, it must follow the syntax defined in [14.3 Method Definitions](https://tc39.github.io/ecma262/#prod-MethodDefinition), which requires a parameter list and a method body. I cannot see both on your `created` field.

Class field is a TypeScript superset and a stage 3 proposal [tc39/proposal-class-fields](https://github.com/tc39/proposal-class-fields), your `created` field clearly fits with these definitions, with TypeScript access modifier and type declaration.

If you cannot read ecma-262, I think there is nothing more we can talk. I have unsubscribed this issue.

**Comment by yortus** [comment]
@vincedan if you want to declare a method, do it inline like @yume-chan showed:

```ts
class BaseClass {
    async created() {
        return await Promise.resolve("OK");
    }
}
```

If you want an instance property that is an async function, do it like this:
```ts
class BaseClass {
    created = async () => await Promise.resolve("OK");
}
```

If you are trying to create an abstract base class to implement in other classes, do it like this:
```ts
abstract class BaseClass {
    abstract created(): Promise<string>;
}

class DerivedClass extends BaseClass {
    async created() {
        return await Promise.resolve("OK");
    }
}
```

**Comment by vincedan** [comment]
@yortus  thanks. I need abstract interface defined here.  I wanna use typescript strong type Intellisense but without method body. the third solution give me another hint. thanks again.
