### ISSUE TITLE
Ambient declarations of mixins

### ISSUE THREAD

**Issue by merlinnot** [Microsoft/TypeScript#22045]
Declarations of mixins are not handled as expected by TypeScript compiler, I can't find a way to make it work manually either.

**Search Terms:**
- ambient mixin declaration
- type 'T & Constructor<T>' is not a constructor function type
- mixin type annotations

**Code**

One of the solutions I've tried (out of tens):

Declaration:
```ts
type Constructor<T = {}> = new (...args: any[]) => T;
function mixin<T extends Constructor<SomeClass>>(
  superClass: T,
): Constructor<T> & T;
```

Usage:
```ts
const anotherMixin = <T extends Constructor<SomeClass>>(
  superClass: T,
) =>
  class extends mixin(superClass) {}
```
**Expected behavior:**
I'd expect it to be possible to make ambient type declarations for mixins.

**Actual behavior:**
TypeScript compiler emits these declarations by copying all of the fields from parent classes.

There's no way to make a type declarations manually.

**Playground Link:**
Playground does not support emitting type declarations.

**Comment by DanielRosenwasser** [comment]
```ts
type Constructor<T = {}> = new (...args: any[]) => T;
function mixin<T extends Constructor<SomeClass>>(
  superClass: T,
): Constructor<T> & T;
```

here `T` is the original constructor type - I'm pretty sure you want to write something like `Constructor<MixedInstanceType> & T`

```ts
interface MixedInstance {
  yay: any;
}

declare function mixin<T extends Constructor<SomeClass>>(
    superClass: T,
): Constructor<MixedInstance> & T;
```

**Comment by DanielRosenwasser** [comment]
You can then write something like

```
interface AnotherMixinInstance {
  // ...
}

declare const anotherMixin: <T extends Constructor<SomeClass>>(ctor: T) =>  Constructor<AnotherMixinInstance> & Constructor<MixedInstance> & T;
```

**Comment by merlinnot** [comment]
Let me be more specific here, maybe I'm missing something:

I'm using a library which provides a mixin for classes extending `HTMLElement`, but there are no type declarations for this library. This mixin does not introduce any new props/methods, it's declaration could be empty.

I want to create another mixin which overrides some of the functionalities of the one from the library, it does not define any new props/methods neither.

So basically I have something like this:
`mixinFromLibrary.d.ts`
```ts
type Constructor<T = {}> = new (...args: any[]) => T;
function mixinFromLibrary<T extends Constructor<HTMLElement>>(
  superClass: T,
): Constructor<T> & T;
```

and my implementation, which is built on top of the one from the library:
```ts
const myMixin = <T extends Constructor<HTMLElement>>(superClass: T) =>
  class extends mixinFromLibrary(superClass) {}
```

By doing so I get `Type ... is not a constructor function type`. I'd like `class extends mixinFromLibrary(superClass)` to be equal (in terms of type) to class extends superClass.

**Comment by merlinnot** [comment]
Works in the latest version.

**Comment by merlinnot** [comment]
Actually it doesn't :(
