### ISSUE TITLE
Account type conflict

### ISSUE THREAD

**Issue by miltonbecker** [Microsoft/TypeScript#22057]
**TypeScript Version:**  
2.7.2 and 2.8.0-dev.20180220

**Search Terms:** 
type conflict name

**Code**

```ts
type Account = {
  identifier: string;
  scriptVersion: string;
  name: string;
};
```

**Expected behavior:**
Should let me set the type Account.

**Actual behavior:**
Tells me `Duplicate identifier 'Account'`.

I saw the type `Account` comes from `lib.esnext.full.d.ts` (or `lib.dom.d.ts` if you set lib: ["dom"] within tsconfig.json).

However, it's not related to any element/specification of DOM/esnext, is it?
So, shouldn't it be named more specifically in order to not conflict with other users codes (for example 'TSDomAccount')?

Also, I had set it as an interface before and it had merged the 2 interfaces with the same name automatically - which is to be expected as per Typescript specification - but does that mean I have to make sure my interfaces' names are unique?

Should we treat our types/interfaces names as CSS class names and add a hash to them? :(

I guess I'll never use interfaces anymore, only type aliases because at least I'll know whether my type is unique or not.

**Comment by andy-ms** [comment]
You can avoid name conflicts by putting your code in a module -- this happens automatically if the code contains any `import` or `export` statements. Some info is [here](https://www.typescriptlang.org/docs/handbook/modules.html).

**Comment by DanielRosenwasser** [comment]
Yup, if you want to avoid problems with the global scope, use modules instead.

**Comment by miltonbecker** [comment]
@andy-ms @DanielRosenwasser but then I'd have to import the type/interface in every file I want to use it, wouldn't I? 

Seems a bit unpractical, just like Flow.

And in any case, I really think you should rename `Account` to something else.

Because if you keep adding generic-named interfaces like that it might start interfering with someone else's code.

**Comment by mhegazy** [comment]
`Account` is part of the Web Authentication DOM APIs (though it is still experimental). if you are not interested in DOM, consider using `--lib es2015` this will get you the JS standard library for es2015 without the DOM.

**Comment by miltonbecker** [comment]
OK, thanks a lot for your input guys :) 

We've decided 2 things here in my team:

- We're not using Interfaces anymore. Type aliases make it easier to see its definition (by moving the cursor over them on vscode) and make sure we don't merge stuff unexpectedly 
- If we need to share some types among other files, we define them in a .d.ts file (as usual) but we set them within a `declare module` statement, so it's easier to import the types later and avoids any conflicts with the global scope

I'm closing this issue as it seems to be the desired behavior of TypeScript.
