### ISSUE TITLE
Can't use named string literal types

### ISSUE THREAD

**Issue by voliva** [Microsoft/TypeScript#22050]
**TypeScript Version:**  2.7.0

**Search Terms:** 
String literal types, string enum types

**Code**

```ts
interface BaseInterface {
    type: string;
    id: number;
}

/** Enum Case **/
enum EnumLiteralTypes {
    Foo = 'Foo',
    Bar = 'Bar'
}

interface FooEnumInterface extends BaseInterface {
    type: EnumLiteralTypes.Foo;
    foo: string
}
interface BarEnumInterface extends BaseInterface {
    type: EnumLiteralTypes.Bar;
    bar: string
}

type ResultingType = FooEnumInterface | BarEnumInterface;

let enumObject:ResultingType;
enumObject = {
    type: EnumLiteralTypes.Foo,
    id: 0,
    foo: 'foo',
    // bar: 'bar' // => Correctly shows error, type inference works fine.
};

/** Const Case **/
const FooLiteralType = 'Foo';
const BarLiteralType = 'Bar';

interface FooConstInterface extends BaseInterface {
    type: FooLiteralType; // Error: Cannot find name 'FooLiteralType'
    foo: string
}
```

**Expected behavior:**
`FooLiteralType` can be used as a string literal type, just like `EnumLiteralTypes.Foo` can.

**Actual behavior:**
When trying to use `FooLiteralType` as a literal string type, it shows the error `Cannot find name 'FooLiteralType'`

**Playground Link:**  

https://goo.gl/tKQ83F

**Comment by andy-ms** [comment]
`FooLiteralType` has only value meaning, but you can use `typeof FooLiteralType` to get it as a type.

**Comment by voliva** [comment]
That's a bit confusing, after all `const FooLiteralType` and `EnumLiteralTypes.Foo` are very similar: Both are string values that can't be changed. Why do they have different behaviours then?

I see that `typeof` can also be used in the case of enums, so I'll stick to that.

**Comment by andy-ms** [comment]
Using an `enum` creates both a type and a const with the same name. You could even emulate this with `type FooLiteralType = typeof FooLiteralType;`.
