### ISSUE TITLE
Implementing Type which resolves to generic emits an error, but still infers correctly

### ISSUE THREAD

**Issue by MadaraUchiha** [Microsoft/TypeScript#22054]
**TypeScript Version:**  2.7.2

**Search Terms:** 
typescript extend generic type
A class may only implement another class or interface.

**Code**

```ts
const actions = {
    foo(n: number) { },
    bar(s: string) { },
}

type Adaptor<T> = { [K in keyof T]: T[K] };

abstract class MobXAdaptor<T extends {}> implements Adaptor<T> {
    constructor(protected actions: T) { }
}

class MyMobxAdaptor2 extends MobXAdaptor<typeof actions> {
    foo(n: string) {
        return this.actions.foo(n);
    }

    bar() { }
}
```

**Expected behavior:**
One of: 
- Emit an error for `Adaptor<T>` not being an interface, and don't understand that `foo()` is not implemented correctly
- Implement `Adaptor<T>` correctly, and emit an error for `foo()` not being implemented correctly.

**Actual behavior:**
Error is emitted for both `Adaptor<T>` not being an interface, and `foo()` not being implemented correctly.

This implies that even though TypeScript emits an error, it does manage to use the generic correctly.

**Playground Link:**  
[Click me](https://www.typescriptlang.org/play/index.html#src=const%20actions%20%3D%20%7B%0D%0A%20%20%20%20foo(n%3A%20number)%20%7B%20%7D%2C%0D%0A%20%20%20%20bar(s%3A%20string)%20%7B%20%7D%2C%0D%0A%7D%0D%0A%0D%0Atype%20Adaptor%3CT%3E%20%3D%20T%3B%0D%0A%0D%0Aabstract%20class%20MobXAdaptor%3CT%20extends%20%7B%7D%3E%20implements%20Adaptor%3CT%3E%20%7B%0D%0A%20%20%20%20constructor(protected%20actions%3A%20T)%20%7B%20%7D%0D%0A%7D%0D%0A%0D%0Aclass%20MyMobxAdaptor2%20extends%20MobXAdaptor%3Ctypeof%20actions%3E%20%7B%0D%0A%20%20%20%20foo(n%3A%20string)%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20this.actions.foo(n)%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20bar()%20%7B%20%7D%0D%0A%7D)

**Related Issues:**
- https://github.com/Microsoft/TypeScript/issues/2225

---

Funny thing is, if I don't use `<T>` and instead use a realized type like `{foo: string}`, it doesn't complain about "A class may only implement another class or interface.", and still infers the type correctly in the extending class. 

There's an inconsistency here, and I'm not sure which of the conflicting errors is the semantically correct one.

**Comment by andy-ms** [comment]
I think this is working as intended. You can't implement a type parameter, so `foo` is just seen as a new method, not as an implementation of an interface. You can, however, have a property that is a type parameter, so we will still correctly give an error when using the `actions` property.
