### ISSUE TITLE
Delete TS files in VS2013 Update 4 with TS1.4 is very slow

### ISSUE THREAD

**Issue by zcxp** [Microsoft/TypeScript#2206]
Delete 50 ts files at same time in VS 2013 is so slow, and the VS window is no response.

![ts1 4](https://cloud.githubusercontent.com/assets/663400/6498765/d35da65e-c32a-11e4-90f4-3af05aa5ffc6.png)

I think TS service is handle the file changes one by one in the UI thread.

**Comment by mhegazy** [comment]
We have completely rewrote this part as we moved to VS2015 to fix this issue. Porting the change to VS2013 would be expensive at this point. so resolving this as won't fix.
