### ISSUE TITLE
Type inference for piped arrow functions

### ISSUE THREAD

**Issue by ivan7237d** [Microsoft/TypeScript#22081]
**TypeScript Version:**  2.7.1 (the issue occurs independently of whether the strict mode, including strictFunctionTypes, is turned on)

**Search Terms:** pipe, type inference, generic

**Code/actual behavior**:

```ts
const pipe = <A, B, C>(
  x: A,
  a: (x: A) => B, 
  b: (x: B) => C,
) => b(a(x));

// This just calls the function passed as argument. In
// other words, it's an identity function that takes
// an argument of a specific type (x: A) => B.
const call = <A, B>(f: (x: A) => B) => (x: A) => f(x)

// For this line, TS can't infer type of the last argument
// and addition produces error.
const a = pipe(1, x => x + 1, call(x => x + 1));
// But it successfully infers types for this line where
// the second argument is wrapped in call(...)
const b = pipe(1, call(x => x + 1), call(x => x + 1));
```

**Expected behavior:**
Typescript should be able to infer the types for the simpler one of the these two lines if it can infer them for the more complex one.

**Playground Link:** 
[Playground](https://www.typescriptlang.org/play/#src=const%20pipe%20%3D%20%3CA%2C%20B%2C%20C%3E(%0D%0A%20%20x%3A%20A%2C%0D%0A%20%20a%3A%20(x%3A%20A)%20%3D%3E%20B%2C%20%0D%0A%20%20b%3A%20(x%3A%20B)%20%3D%3E%20C%2C%0D%0A)%20%3D%3E%20b(a(x))%3B%0D%0A%0D%0A%2F%2F%20This%20just%20calls%20the%20function%20passed%20as%20argument.%20In%0D%0A%2F%2F%20other%20words%2C%20it's%20an%20identity%20function%20that%20takes%0D%0A%2F%2F%20an%20argument%20of%20a%20specific%20type%20(x%3A%20A)%20%3D%3E%20B.%0D%0Aconst%20call%20%3D%20%3CA%2C%20B%3E(f%3A%20(x%3A%20A)%20%3D%3E%20B)%20%3D%3E%20(x%3A%20A)%20%3D%3E%20f(x)%0D%0A%0D%0A%2F%2F%20For%20this%20line%2C%20TS%20can't%20infer%20type%20of%20the%20last%20argument%0D%0A%2F%2F%20and%20addition%20produces%20error.%0D%0Aconst%20a%20%3D%20pipe(1%2C%20x%20%3D%3E%20x%20%2B%201%2C%20call(x%20%3D%3E%20x%20%2B%201))%3B%0D%0A%2F%2F%20But%20it%20successfully%20infers%20types%20for%20this%20line%20where%0D%0A%2F%2F%20the%20second%20argument%20is%20wrapped%20in%20call(...)%0D%0Aconst%20b%20%3D%20pipe(1%2C%20call(x%20%3D%3E%20x%20%2B%201)%2C%20call(x%20%3D%3E%20x%20%2B%201))%3B%0D%0A)

**Related Issues:**
This issue originates from discussion here #22051.

**Comment by sylvanaar** [comment]
I really think this is the old problem about having 2 inference sites for the same type variable. Let me try to find the issue.

**Comment by ivan7237d** [comment]
@sylvanaar Interesting, thanks! 

Unfortunately that fix doesn't seem to work with strictFunctionTypes.

Another thing is it seems to me that the NoInfer feature is intended for cases when TypeScript can successfully infer the type on both of the sites, and you want to tell it to prefer one site over another, but not for the cases when it can infer the type on one site but can't infer it on the other site.

If it helps, this is what I think of as a typical use case for NoInfer:
```ts
const defaultValue = <T>(source: T, defaultValue: NoInfer<T>) =>
  source === undefined ? defaultValue : source;
type A = { a?: number };
// Typescript can infer the type from the second argument, but you don't
// want it to do it because then .a would be causing an error.
const f = (arg: A) => defaultValue(arg, {}).a;
```

**Comment by sylvanaar** [comment]
Just trying to explain to you what is happening. Inference is occurring at the site with the unbound type variables, so you end up inferring {} for B.

This only happens if you mix supplying functions with unbound type variables and functions without them as arguments for some reason.

`const a = pipe(1, x => x + 1, x => x + 1);` works just fine.

So you could say that maybe the algorithm should change to prefer inference from sites where there are no unbound type variables - though I don't know all the implications of that.

**Comment by ivan7237d** [comment]
@mhegazy Not sure if it's a good idea to close this issue — right now when you're using pipes, you often have to use a counterintuitive `call()` trick I described in this [stackoverflow answer](https://stackoverflow.com/questions/48786644/why-does-typescript-not-infer-types-for-some-piped-functions/49262055#49262055) to get type inference to work. And it's not a rare use case — in rxjs for example, it's very common to have pipes + arrow functions in code like `observable.pipe(source => merge(source, otherObservable))`.

**Comment by americanslon** [comment]
Any news on this? I just updated from angular 5 to 6, which entails rxjs v6+ and I have this issue all over my project. Surprised there aren't more complaints out there seeing how popular angular is.

**Comment by topaxi** [comment]
This is quite annoying and should not be closed.

**Comment by cartant** [comment]
My understanding is that @mhegazy is ["moving on to new adventures"](https://twitter.com/SeaRyanC/status/1026968774849835009). Should this be closed, @RyanCavanaugh ?

**Comment by RyanCavanaugh** [comment]
This is a limitation of the current inference algorithm. We don't have a good way to know that inference in this function is supposed to proceed left-to-right and that the inference needs to happen in two discrete steps (first resolving `B`, then `C`).

**Comment by RyanCavanaugh** [comment]
See also #25826
