### ISSUE TITLE
return not on same line as value returns undefined

### ISSUE THREAD

**Issue by bmiller1** [Microsoft/TypeScript#2208]
This returns true:
function getValue1(): boolean {
    return true || false;
}

This returns undefined:
function getValue2(): boolean {
    return 
    true || false;
}

**Comment by DanielRosenwasser** [comment]
This is as per JavaScript's quirky exceptions to its [ASI (automatic semicolon insertion) rules](http://www.ecma-international.org/ecma-262/5.1/#sec-7.9.1). Specifically, if you look at the grammar:

> *ReturnStatement* :
&nbsp;&nbsp;&nbsp;&nbsp;`return` ;
&nbsp;&nbsp;&nbsp;&nbsp;`return` <sub>[no *LineTerminator* here]</sub> *Expression* ;
