### ISSUE TITLE
ES2018 RegExp named capture groups not supported with esnext library

### ISSUE THREAD

**Issue by slikts** [Microsoft/TypeScript#22082]
**TypeScript Version:**  2.8.0-dev.20180221

**Search Terms:** RegExp named capture groups; [description](http://2ality.com/2017/05/regexp-named-capture-groups.html)

**Code**

```ts
'foo'.match(/(?<bar>foo)/)!.groups
```

**Expected behavior:**
It should compile with esnext (ES2018) library compiler option.

**Actual behavior:**
`Property 'groups' does not exist on type 'RegExpMatchArray'.`

**Playground Link:** 

**Related Issues:**

**Comment by slikts** [comment]
The fix seems to be as simple as:
```ts
interface RegExpMatchArray {
  groups: {
    [key: string]: string
  }
}
```

**Comment by mhegazy** [comment]
A PR would be appreciated. We will need a new file `src\lib\es2018.regexp.d.ts` with the new declaration, and then we will need that wired in `jakeFile.js`.

**Comment by mhegazy** [comment]
thanks @YuichiNukiyama !
