### ISSUE TITLE
signatureHelp returns outer function call signature when inside of object literals or arrays

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#22106]
From https://github.com/Microsoft/vscode/issues/44129#event-1485462419

**TypeScript Version:**  2.7.1

**Search Terms:** 
- signature help

**Code**

```ts
console.log({a: 1 })
```

Type `,` after `1` to trigger a signature help request

**Expected behavior:**
`signatureHelp` does not return anything at this point, or indicates that we are inside of an object

**Actual behavior:**
`signatureHelp` returns the signature help for `console.log`

**Playground Link:**  

**Related Issues:**

**Comment by andy-ms** [comment]
Basically a duplicate of #1150. We currently don't do any checking of whether we ought to provide signature help, we just climb out to the nearest signature (which is admittedly annoying).

**Comment by DanielRosenwasser** [comment]
Going to reopen this since I think strings are a separate case from object literals and the like.

**Comment by mhegazy** [comment]
Should be fixed in latest.
