### ISSUE TITLE
How to type-check the `pick` function?

### ISSUE THREAD

**Issue by cakoose** [Microsoft/TypeScript#22113]
I'm trying to use `Pick` to type a function like Lodash's `pick` ([docs](https://lodash.com/docs/4.17.4#pick)).

```typescript
declare function pick<T extends object, F extends keyof T> (obj: T, fields: F[]): Pick<T, F>;
```

(This is similar to what the DefinitelyTyped declaration does: [Lodash `pick` type declaration](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/ff2359e74ce1c539097e47dc586d49d348a94587/types/lodash/object/pick.d.ts#L19)).

This works in some cases, but is unsound because of the way union subtyping works:

```typescript
type Thing = {
    a: number,
    b: string,
    c: boolean,
};

function good(t1: Thing) {
    const t2 = pick(t1, ['a', 'b']);
    console.log(t2.a);
    console.log(t2.c);  // <-- compile-time error (good)
}

function bad1(t1: Thing) {
    const fields: ('a' | 'b' | 'c')[] = ['a', 'b'];  // union subtyping
    const t2 = pick(t1, fields);
    console.log(t2.a);
    console.log(t2.c);  // <-- no compile-time error, just runtime error (bad)
}

function bad2(t1: Thing) {
    const fields: 'a'[] = [];
    const t2 = pick(t1, fields);
    console.log(t2.a);  // <-- no compile-time error, just runtime error (bad)
}
```

We use a `pick`-like function a lot in our codebase -- when pulling records from the database, we pass in an array of the column names to retrieve.  It would be nice if there were a better way to type-check that code.

**Comment by DanielRosenwasser** [comment]
I honestly don't know how to prevent this under the current system. The behavior is undesirable, but it is working "as intended". You could instead say that `pick` returns a `Partial<Pick<T, F>>` because you don't definitely know whether a property is present.

**Comment by andy-ms** [comment]
You could also take `...args: F[]` and be careful to always call `pick` with manually written strings (and without an explicit type argument).

**Comment by cakoose** [comment]
Yeah, just to be clear, this typing for `pick` is somewhat usable in practice, but I recently realized that it's not type safe.

I just wanted to get this issue logged in case someone has ideas on how to improve the type system to handle this correctly.

**Comment by weswigham** [comment]
There's definitely a better way to type it for the non-array-of-fields case now:
```ts

// TODO: preserve optionality?
declare function pickSingle<T extends object, F extends keyof T> (obj: T, field: F): F extends keyof T ? {[K in F]: T[K]} : never;

let x: "a" | "b" = null as any;

const obj = {a: 42, b: ""};

const result = pickSingle(obj, x);
// {a: number} | {b: string}
```
you can update the array-argument form to be accurate insofar as it has both the least bounds and most bounds types:
```ts

type PickSingle<T extends object, F extends keyof T> = F extends keyof T ? {[K in F]: T[K]} : never;
declare function pick<T extends object, F extends keyof T>(obj: T, fields: F[]): PickSingle<T, F> | Pick<T, F>

const arr: ("x" | "y" | "z")[] = ["x", "y"]
const result2 = pick({x: 12, y: "", z: [12]}, arr);
// {x: number} | {y: string} | {x: number[]} | {x: number | y: string | z: number[]}
```

(Once recursive conditional types are in, you should be able to create the full powerset of possibilities)

But it's definitely not going to be an easy-to-use type (especially with no guaranteed discriminant on the result). You may just want to use `Partial<Pick<T, F>>` if you want more safety, and are willing to sacrifice precision somewhat, in most cases.
