### ISSUE TITLE
Automation methods don't have Function object members

### ISSUE THREAD

**Issue by zspitz** [Microsoft/TypeScript#22110]
**TypeScript Version:**  2.8.0-dev.20180222

**Search Terms:** 
callable

**Code**

```ts
WScript.Echo(WScript.Echo.apply);
```

**Expected behavior:**
Should not compile

**Actual behavior:**
Compiles

**Playground Link:** NA

**Further details**

When a method or a callable interface is defined in a Typescript definition, the (entirely valid) assumption is that it's returning a Javascript `Function` object, with all the associated methods / properties (`apply`, `bind`, `arguments` etc.).

However, Automation methods are not `Function` objects, and do not have these members. Trying to use them (as in the above code) will cause a runtime error:

> Microsoft JScript runtime error: Object doesn't support this property or method

**Comment by mhegazy** [comment]
This is really a design limitation. the language does not have a capability to define something that is callable but not a `Function`

**Comment by zspitz** [comment]
Included in this are types whose default property takes parameters. From the Typescript definition perspective, they are callable interfaces:

```
interface Field {
    ...
    Value: any;
}

interface Recordset {
    ...
    (FieldIndex: string | number): Field;
}

let rs: Recordset = new ActiveXObject('ADODB.Recordset');
WScript.Echo(rs('LastName').Value);
```
but the default property is certainly not a `Function` object:

```
// will throw an error
WScript.Echo(rs.apply);
```
