### ISSUE TITLE
Type narrowing doesn't work when accessing object properties via string literals

### ISSUE THREAD

**Issue by Vinnl** [Microsoft/TypeScript#22111]
**TypeScript Version:**  2.8.0-dev.20180222 and 2.7.1

**Search Terms:**  `type` `narrow` `object` `property` `string` `literal`

**Code**

```ts
interface PossiblyNull {
        couldBeNull: string | null;
}

function workOnPossiblyNull(a: PossiblyNull) {
        const notNull: string = (a.couldBeNull) ? a.couldBeNull : 'not null';
        const notNullEither: string = (a['couldBeNull']) ? a.couldBeNull : 'not null either';
}
```

**Expected behavior:** The above code to properly compile, even with `strictNullChecks` turned on. Although I understand that TypeScript often can't know what values will be inserted inside the square brackets, when the property name is a literal string, it would be nice if it could treat it the same way as it would had the property been accessed using dot notation. (Especially in the cases where the latter is not possible, i.e. when property names contain a dash.)

**Actual behavior:**

```
$ tsc test.ts --strict
test.ts(7,8): error TS2322: Type 'string | null' is not assignable to type 'string'.
  Type 'null' is not assignable to type 'string'.
error Command failed with exit code 2.
```

**Playground Link:** http://www.typescriptlang.org/play/index.html#src=interface%20PossiblyNull%20%7B%0A%20%20%20%20%20%20%20%20couldBeNull%3A%20string%20%7C%20null%3B%0A%7D%0A%0Afunction%20workOnPossiblyNull(a%3A%20PossiblyNull)%20%7B%0A%20%20%20%20%20%20%20%20const%20notNull%3A%20string%20%3D%20(a.couldBeNull)%20%3F%20a.couldBeNull%20%3A%20'not%20null'%3B%0A%20%20%20%20%20%20%20%20const%20notNullEither%3A%20string%20%3D%20(a%5B'couldBeNull'%5D)%20%3F%20a.couldBeNull%20%3A%20'not%20null%20either'%3B%0A%7D%0A

**Related Issues:**

I'm nervous that this has probably been reported elsewhere already, but I couldn't find it...

**Comment by sylvanaar** [comment]
Related: #10530

**Comment by DanielRosenwasser** [comment]
Thanks for finding the original @sylvanaar
