### ISSUE TITLE
Implement source maps for computed properties

### ISSUE THREAD

**Issue by JsonFreeman** [Microsoft/TypeScript#2212]
```ts
var v = {
    ["hello"]() {
        debugger;
    }
}
```

This is from tests\cases\conformance\es6\computedProperties\computedPropertyNamesSourceMap2_ES5.ts.

Right now we have unmapped spans in the emitted source map, so the debugger will jump into the .js file every time it encounters an unmapped span.

**Comment by DanielRosenwasser** [comment]
@JsonFreeman it looks like things are currently being generated correctly. Let's figure out whether this is still an issue when you return.

![image](https://cloud.githubusercontent.com/assets/972891/8414037/1013278e-1e63-11e5-95c1-5825cf21e642.png)

**Comment by JsonFreeman** [comment]
The final _a still looks unmapped in the picture you gave.

**Comment by DanielRosenwasser** [comment]
Ah I see what you'e saying. Let me get on that.

**Comment by mhegazy** [comment]
Should be working correctly in latest.
