### ISSUE TITLE
Source map spans are very awkward for destructuring

### ISSUE THREAD

**Issue by JsonFreeman** [Microsoft/TypeScript#2213]
```ts
var [a, b] = [1, 2];
({ 0: a, 1: b } = [1, 2]);
```

The source spans spans here are:
`[a, b] = [1, 2]`
`a, `
`b] = [1, 2]`
`{ 0: a, 1: b } = [1, 2]`
`a, 1: `
`b } = [1, 2]`

They should be divided differently.

In fact, for array destructuring with initializers, they do not work at all:
```ts
var [a = 0, b = 1] = [1, 2];
```
has unmapped spans.

**Comment by yuit** [comment]
I can't repo this when trying to debug  above code in Firefox debugger

**Comment by DanielRosenwasser** [comment]
@yuit can you confirm with this tool as well? http://sokra.github.io/source-map-visualization/

**Comment by yuit** [comment]
Here is the [link](http://sokra.github.io/source-map-visualization/#base64,dmFyIF9hID0gWzEsIDJdLCBhID0gX2FbMF0sIGIgPSBfYVsxXTsNCihfYiA9IFsxLCAyXSwgYSA9IF9iWzBdLCBiID0gX2JbMV0sIF9iKTsNCnZhciBfYjsNCi8vIyBzb3VyY2VNYXBwaW5nVVJMPTAuanMubWFw,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiMC5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIjAudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBQUEsSUFBSSxLQUFTLENBQUMsQ0FBQyxFQUFFLENBQUMsQ0FBQyxFQUFkLENBQUMsVUFBRSxDQUFDLFFBQVUsQ0FBQztBQUNwQixDQUFDLEtBQWlCLENBQUMsQ0FBQyxFQUFFLENBQUMsQ0FBQyxFQUFsQixDQUFDLFVBQUssQ0FBQyxZQUFXLENBQUMsQ0FBQyJ9,dmFyIFthLCBiXSA9IFsxLCAyXTsNCih7IDA6IGEsIDE6IGIgfSA9IFsxLCAyXSk7) It seems that the span is different in the visualizer than the one from @JsonFreeman (which I can repo on VS)
