### ISSUE TITLE
Union type is not narrowed after assignment

### ISSUE THREAD

**Issue by rsinohara** [Microsoft/TypeScript#22145]
**TypeScript Version:**  2.7.0-dev.201xxxxx

Still gives me the error

type after assignment
type detection after assignment
union type narrowing
union type assignment narrowing

**Code**

```ts
static myFunc(value: object | Date):void{
  value=new Date();
  let otherDate=new Date();
  value.setTime(otherDate.getTime); //Error here, cannot assign Date to Object|Date
}
```

**Expected behavior:**
In my opinion, this should not be an error. Date type should be narrowed.
I know I can add a guard, but having a type check right after an assignment doesn't make sense, and would require me to comment on it.

**Actual behavior:**
Error on the commented line.

**Comment by andy-ms** [comment]
I can't find the issue for it, but we currently can't narrow to subtypes. We *can* narrow a union such as `string | Date`. (ote that `Date` is an `object` but is not a `string`.)

**Comment by rsinohara** [comment]
Interesting. What is the proper workaround? Adding an instanceOf after the assignment?

**Comment by andy-ms** [comment]
I don't know any simple workaround. Depending on your situation, you might just be able to use separate variables, e.g.:
```ts
function myFunc(valueIn: object | Date): void {
  const value = valueIn instanceof Date ? valueIn : convertToDate(valueIn);
}
```
