### ISSUE TITLE
--strictFunctionTypes doesn't evaluate generics properly

### ISSUE THREAD

**Issue by jonchardy** [Microsoft/TypeScript#22147]
Running into an unexpected problem when trying to compile with --strictFunctionTypes. When a generic class has a property taking a function, trying to pass a generic using a subclass to a function that takes the superclass fails. This feels like a bug, but if I'm defining something incorrectly, let me know. See below.

**TypeScript Version:**  2.8.0-dev.20180223

**Search Terms:** strictFunctionTypes, generics

**Code**
```ts
class Pet {
  private _name: string;

  public constructor(name: string) {
    this._name = name;
  }
}

class Dog extends Pet {
  private _dogProp: string;

  public constructor(name: string) {
    super(name);
    this._dogProp = "dog-specific property";
  }
}

class List<T> {
  public arr: Array<T>;
  public predicate: (a: T) => boolean; // removing this allows for compilation

  constructor() {
    this.arr = [];
  }

  public add(val: T): void {
    if (val === null) return;
    this.arr.push(val);
  }
}

function dogListParamFunc(dogs: List<Dog>): List<Dog> {
  return petListParamFunc(dogs) as List<Dog>;
}

function petListParamFunc(pets: List<Pet>): List<Pet> {
  return pets;
}

const spot = new Dog("Spot");
const doglist = new List<Dog>();
doglist.add(spot);
dogListParamFunc(doglist);
```

**Expected behavior:** The compiler should recognize that `List<Dog>` can be passed to a function accepting `List<Pet>`, even given the `predicate `property.

**Actual behavior:** Compilation results in the following error:
```
tsc --strictFunctionTypes ./src/app.ts
src/app.ts(33,27): error TS2345: Argument of type 'List<Dog>' is not assignable to parameter of type 'List<Pet>'.
  Types of property 'predicate' are incompatible.
    Type '(a: Dog) => boolean' is not assignable to type '(a: Pet) => boolean'.
      Types of parameters 'a' and 'a' are incompatible.
        Type 'Pet' is not assignable to type 'Dog'.
```

Removing the `predicate` property allows for compilation with strictFunctionTypes turned on.

**Playground Link:** [Playground](https://www.typescriptlang.org/play/#src=class%20Pet%20%7B%0D%0A%20%20private%20_name%3A%20string%3B%0D%0A%0D%0A%20%20public%20constructor(name%3A%20string)%20%7B%0D%0A%20%20%20%20this._name%20%3D%20name%3B%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Aclass%20Dog%20extends%20Pet%20%7B%0D%0A%20%20private%20_dogProp%3A%20string%3B%0D%0A%0D%0A%20%20public%20constructor(name%3A%20string)%20%7B%0D%0A%20%20%20%20super(name)%3B%0D%0A%20%20%20%20this._dogProp%20%3D%20%22dog-specific%20property%22%3B%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Aclass%20List%3CT%3E%20%7B%0D%0A%20%20public%20arr%3A%20Array%3CT%3E%3B%0D%0A%20%20public%20predicate%3A%20(a%3A%20T)%20%3D%3E%20boolean%3B%20%2F%2F%20removing%20this%20allows%20for%20compilation%0D%0A%0D%0A%20%20constructor()%20%7B%0D%0A%20%20%20%20this.arr%20%3D%20%5B%5D%3B%0D%0A%20%20%7D%0D%0A%0D%0A%20%20public%20add(val%3A%20T)%3A%20void%20%7B%0D%0A%20%20%20%20if%20(val%20%3D%3D%3D%20null)%20return%3B%0D%0A%20%20%20%20this.arr.push(val)%3B%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Afunction%20dogListParamFunc(dogs%3A%20List%3CDog%3E)%3A%20List%3CDog%3E%20%7B%0D%0A%20%20return%20petListParamFunc(dogs)%20as%20List%3CDog%3E%3B%0D%0A%7D%0D%0A%0D%0Afunction%20petListParamFunc(pets%3A%20List%3CPet%3E)%3A%20List%3CPet%3E%20%7B%0D%0A%20%20return%20pets%3B%0D%0A%7D%0D%0A%0D%0Aconst%20spot%20%3D%20new%20Dog(%22Spot%22)%3B%0D%0Aconst%20doglist%20%3D%20new%20List%3CDog%3E()%3B%0D%0Adoglist.add(spot)%3B%0D%0AdogListParamFunc(doglist)%3B%0D%0A)

**Related Issues:**

**Comment by andy-ms** [comment]
Since `List` contains a predicate `(a: T) => boolean`, a `List<Dog>` is *not* a `List<Pet>`. If you have a `List<Pet>` you can call `list.predicate(pet)` for *any* pet, but a `List<Dog>` only supports `list.predicate(dog)`. That is, we allow you to write `doglist.predicate = dog => dog._dogProp.length === 2;`, so we had better only allow you to pass a `dog` in there.

You can fix the compile error by making `petListParamFunc` generic: 
```ts
function petListParamFunc<T extends Pet>(pets: List<T>): List<T> {
    const p: Pet = pets.arr[0]; // this still works
    return pets;
}
```

**Comment by jonchardy** [comment]
Ok, that makes sense. The actual case in our code is a bit more complex, maybe I should describe that. If this needs to be taken to stackoverflow, let me know...

Say instead of the functions above, we have the following:
```ts
...

function findDogs(dogs: List<Dog>): List<Dog> {
  return findPets(dogs, d => d instanceof Dog) as List<Dog>;
}

function findPets<T extends Pet>(pets: List<T>, pred?: (a: Pet) => boolean): List<T> {
  if (pred === undefined) pred = null;

  const pet1 = new Pet("Sassy");
  const pet2 = new Dog("Shadow");
  const arr: Pet[] = [pet1, pet2];

  for (let i = 0; i < arr.length; i++) {
    const p = arr[i];
    if (pred !== null && pred(p)) pets.add(p);
  }
  return pets;
}

const spot = new Dog("Chance");
const doglist = new List<Dog>();
doglist.add(spot);
findDogs(doglist);
```

So we know that `findDogs` is passing a `List<Dog>`, and we also know that `findPets` is only going to add more `Dog`s to that list due the the predicate being passed (this predicate is unrelated to the one on `List`). How can we inform the compiler of this knowledge since it doesn't know of the type guard in place to guarantee `Dog`s here?

**Comment by andy-ms** [comment]
If you're requiring `pred` to be a predicate that tells you whether a given pet is a `T`, we have a feature that's for exactly that situation:
```ts
function findPets<T extends Pet>(pets: List<T>, pred?: (a: Pet) => a is T): List<T> { ... }
```
Then in the caller you have to declare the predicate to be a type predicate:
```ts
function isDog(p: Pet): p is Dog {
    return p instanceof Dog;
}

function findDogs(dogs: List<Dog>): List<Dog> {
  return findPets(dogs, isDog);
}
```
More on type predicates [here](https://www.typescriptlang.org/docs/handbook/advanced-types.html).

**Comment by jonchardy** [comment]
Sorry, I should have mentioned this in my previous comment. We also want the flexibility to do things like finding four-legged Pets:

```ts
const fourLegs: List<Pet> = findPets(new List<Pet>(), (p) => { return p.legs === 4; });
```

The purpose of `findDogs` is really to provide a convenience function with proper typing, while `findPets` has more general usage. So in the predefined, convenience case of `findDogs`, we know what the predicate will be, but in other cases, it could be arbitrary.

**Comment by andy-ms** [comment]
In the `findDogs` case, the only reason `pets.add(p)` would be valid is if `pred` was a predicate that ensured `p` was a `T`. If you are putting in arbitrary predicates and `arr` contains arbitrary pets, you can't pass a `List<Dog>` to that function, because an arbitrary `Pet` might be added to it.

`findPets` has an internal `arr` with arbitrary pets and pushes them out to output parameter `pets`. So `pets` needs to be able to accept anything being added to it in the general case. I.e., you can't do this:

```ts
// This is obviously not type-safe
function pushSomeThings<T>(a: T[]) {
	a.push(0);
	a.push("");
}
```

You may have to provide two overloads, one taking a `List<T>` and `pred: (a: Pet) => a is T`, and another taking a `List<Pet>` and `pred: (a: Pet) => boolean`.
