### ISSUE TITLE
New website logo: JavaScript Obfuscator

### ISSUE THREAD

**Issue by sanex3339** [Microsoft/TypeScript#22155]
TypeScript one love:

Name: JavaScript Obfuscator
Homepage url: https://github.com/javascript-obfuscator/javascript-obfuscator or http://javascriptobfuscator.herokuapp.com
Brand Guidelines/Licensing: BSD-2-clause
Logo: https://github.com/javascript-obfuscator/javascript-obfuscator/blob/master/images/logo.png?raw=true
![JavaScript Obfuscator](https://github.com/javascript-obfuscator/javascript-obfuscator/blob/master/images/logo.png?raw=true)

**Comment by DanielRosenwasser** [comment]
This is going to make for quite the Friends of TypeScript logo.

**Comment by mhegazy** [comment]
Thanks. Added to the site. Should be live next week.
