### ISSUE TITLE
Selecting a case from a discriminated union using intersection does not work

### ISSUE THREAD

**Issue by rklaehn** [Microsoft/TypeScript#22154]
**TypeScript Version:**  2.7.0-dev.201xxxxx

**Search Terms:** 
discriminated union, narrowing, intersection

**Code**

```ts
type DU = { t: '1', a: 2 } | { t: '2', c: 3 }
type C1 = DU & { t: '1' }
declare const foo: C1
foo.a // <= does not compile
```

**Expected behavior:**
C1 should be inferred to `{ t: '1', a: 2 }`, so it should be clear that a can be accessed

**Actual behavior:**
C1 is inferred to  `({ t: "1"; a: 2; } & { t: "1"; }) | ({ t: "2"; c: 3; } & { t: "1"; })`

Note the impossible type `({ t: "2"; c: 3; } & { t: "1"; })` is not removed!

**Playground Link:**  
[link](http://www.typescriptlang.org/play/#src=type%20DU%20%3D%20%7B%20t%3A%20'1'%2C%20a%3A%202%20%7D%20%7C%20%7B%20t%3A%20'2'%2C%20c%3A%203%20%7D%0D%0Atype%20C1%20%3D%20DU%20%26%20%7B%20t%3A%20'1'%20%7D%0D%0Adeclare%20const%20foo%3A%20C1%0D%0Afoo.a)

**Related Issues:**

**Comment by DanielRosenwasser** [comment]
I believe we discussed this at #18339. Some of these intersection types are vacuous, but it is computationally intensive to try to discover which types are uninhabitable.
