### ISSUE TITLE
Consider making `"a" as "b"` a compile error

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#22150]
**TypeScript Version:**  2.8.0-dev.20180223

**Search Terms:** string literal type assertion

**Code**

```ts
"a" as "b"
```

**Expected behavior:**

Error: type "a" can not be converted to type "b".

**Actual behavior:**

No error.

**Related Issues:**  #10195, which would make it so that no one would need to write `"a" as "a"`.

**Comment by gcnew** [comment]
I proposed this a year ago. See #14156 and #14161.

**Comment by andy-ms** [comment]
D'oh, thanks.
