### ISSUE TITLE
All-optional-props object-type is assignable both to and from the primitive object type

### ISSUE THREAD

**Issue by weswigham** [Microsoft/TypeScript#22164]
**Code**

```ts
type ExtractExact<T, U> = T extends U ? U extends T ? never : T : T;
type SubtractObjectPrimitive<T> = ExtractExact<T, object>;
type MuddiedUnion = object | { x?: number } | { y?: number };
type PurifiedUnion = SubtractObjectPrimitive<MuddiedUnion>;
```

**Expected behavior:**
`PurifiedUnion` is `{ x?: number } | { y?: number }`

**Actual behavior:**
`PurifiedUnion` is `never`

I wanted to filter `object` out of a union because it behaved poorly in something else I was doing (mapping, namely), and then discovered that I could not.

While `{ y?: number }` should be assignable to `object`, `object` being assignable to `{ y?: number }` is.... slightly odd? It makes it look like `object` is the same as an all-optional type as far as conditional types are concerned, which is very difficult to work around.

**Comment by ahejlsberg** [comment]
This is working as intended. `object` and `{}` behave the same way in this case.
