### ISSUE TITLE
More aggressive "unused property" checks.

### ISSUE THREAD

**Issue by cakoose** [Microsoft/TypeScript#22163]
A common bug is to misspell an optional property name.  For example, let's say the property name is `b` but a programmer misspells it as `bb`:

```typescript
function f(x: { a: number, b?: boolean }) { }

function good() {
    f({ a: 1, bb: true });  // type error (good!)
}

function bad() {  // no type error (bad)
    const x = { a: 1, bb: true };
    f(x);
}
```

It would be nice if Typescript caught the bug in `bad`.  I think it's somewhat surprising that extracting an expression into a temporary variable results in Typescript missing a bug.

That said, I can see why the type checker might work this way.  When passing an object literal, there's only one use of that literal, so extra properties are definitely bugs.  With a variable, there may be many uses so you'd have to look at every use site before determining that there are extra properties.  For example:

```typescript
function unclear1() {
    const x = { a: 1, bb: true }
    f(x);
    console.log(x.bb);
}
```

Another slightly different case is where the type is explicitly declared:

```typescript
function unclear2(x: { a: number, bb: boolean }) {
    f(x);
}
```

**Comment by jcalz** [comment]
Are you just asking for exact types (#12936)?  Or is there something else going on here?

**Comment by cakoose** [comment]
Yes, exact types are another technique for catching this class of bugs.  However, my experience with exact types in Flow makes me believe they are the wrong solution.

I end up defining all my types as exact types, since I almost always want the stricter checking, but then switch it to non-exact if there is any use-site that needs width subtyping.  It's unfortunate that a single use site with width subtyping requires that I lose the extra strictness at all other use sites.

Perhaps exactness should be a *use*-site decision instead of a *definition*-site one:

```typescript
type T1 = {a: number};
type T2 = {a: number, b: string}

function f1(t1: T2): T1 {
    return t1;  // type error
}

function f2(t1: T2): T1 {
    return sub(t1);  // `sub` is a marker that enables width subtyping
}

function f3(t1: T2): T1 {
    return sub(t1, 'b');  // something more explicit, where you specify the fields you're dropping
}
```

Width subtyping might be rare enough that this extra bit of use-site syntax is a fair price to pay for the increase in overall strictness.

**Comment by RyanCavanaugh** [comment]
I agree with your comments on the generally bad ergonomics of exact types.

> Width subtyping might be rare enough 

The problem is that it's rare-ish for object literals, but extremely common for all other types. It'd (at best) extremely confusing to have different rules for types inferred from object literals vs types defined via other syntax, so the current compromise is at least a local maximum of general goodness. Imaging trying to explain that the type of `const x = { a: 1, bb: true }` is "almost but not quite but very close to" `{ a: number, bb: boolean }` - really not ideal.

**Comment by cakoose** [comment]
> It'd (at best) extremely confusing to have different rules for types inferred from object literals vs types defined via other syntax

Yeah, that's one way to conceptualize this particular check.  (I think Go does something similar for integer literals.)  But from that perspective, even the current object literal compromise sort of gives object literals a different type -- if the literal and the temporary variable `x` have the same type, why does the error message change?

Another way is to look at it as separate check for unused properties, perhaps similar to checks that detect dead code or unused values.  Is there an easy way to prototype this as a post-type-check linter pass?

**Comment by RyanCavanaugh** [comment]
A very simple but still-useful heuristic would be that any property name that appears in an object literal must have the same spelling as an identifier somewhere else in the program. That'd find bare typos like `lenth` but would miss trickier ones like `fileName` / `filename` where both spellings are prevalent.
