### ISSUE TITLE
Generic object type inference

### ISSUE THREAD

**Issue by Jomik** [Microsoft/TypeScript#22169]
**TypeScript Version:**  2.7.2

**Search Terms:** 
Generic object type inference
**Code**

```ts
class Foo<A> {
  constructor(private a: A) {}
}

type Bar<A extends object> = { [k in keyof A]: Foo<A[k]> };

class Baz<A extends object> {
  constructor(private b: Bar<A>) {}
}

const foo = new Baz({ a: new Foo<string>("foo") });
const bar = new Baz<{a: string}>({ a: new Foo<string>("bar") });
```

**Expected behavior:**
Expected `foo` to have type `Baz<{a: string}>`.

**Actual behavior:**
`foo` has type `Baz<{a: any}>`

**Playground Link:**  
[Typescript Playground](https://www.typescriptlang.org/play/#src=class%20Foo%3CA%3E%20%7B%0D%0A%20%20constructor(private%20a%3A%20A)%20%7B%7D%0D%0A%7D%0D%0A%0D%0Atype%20Bar%3CA%20extends%20object%3E%20%3D%20%7B%20%5Bk%20in%20keyof%20A%5D%3A%20Foo%3CA%5Bk%5D%3E%20%7D%3B%0D%0A%0D%0Aclass%20Baz%3CA%20extends%20object%3E%20%7B%0D%0A%20%20constructor(private%20b%3A%20Bar%3CA%3E)%20%7B%7D%0D%0A%7D%0D%0A%0D%0Aconst%20foo%20%3D%20new%20Baz(%7B%20a%3A%20new%20Foo%3Cstring%3E(%22foo%22)%20%7D)%3B%0D%0Aconst%20bar%20%3D%20new%20Baz%3C%7Ba%3A%20string%7D%3E(%7B%20a%3A%20new%20Foo%3Cstring%3E(%22bar%22)%20%7D)%3B)

**Related Issues:**

**Comment by Jomik** [comment]
Does seem to work with `2.8.0-dev.20180224`, however I feel like I had it working before version 2.7.2, so I was actually hoping it was an issue on my end, leaving this here for just a day or so..

**Comment by mhegazy** [comment]
Can not get a repro on latest.

![image](https://user-images.githubusercontent.com/8000722/37223177-8c743b00-2384-11e8-9b9e-461c1b22da2a.png)

**Comment by Jomik** [comment]
@mhegazy As I wrote in my comment, the issue wasn't on `v2.8.0-dev.20180224`, neither was it present on `v2.6.2`, that's why I wondered if we could get a hotfix for `v2.7.2`, since it was a bug introduced between `2.6` and `2.7`.

**Comment by mhegazy** [comment]
red the comment as it repros on 2.8, sorry about that. Looking at it again, seems the issue was just the serialization of the type.
