### ISSUE TITLE
tslib sometimes included for __importStar, sometimes not, breaks build (2.7.2)

### ISSUE THREAD

**Issue by aappddeevv** [Microsoft/TypeScript#22165]
I am still trying to understand when this does and does not happen but for a large set of .tsx files, only some of these have a tslib import included when a * import is include, sometimes not. This issue was addressed in 2.7.2 (#21560) and for some files, tslib *is* included properly with the config described below.

I have created this placeholder in case other people are still having this issue.

tsconfig.json includes the triple play:
```json
...
  "importHelpers": true,
  "noEmitHelpers": true,
  "esModuleInterop": true, // includes --allowSyntheticDefaultImports = true
...
  // my target is esnext to pass through as much as possible to babel
```
If I change noEmitHelpers=false (the default) then the import helpers are defined in the module that does include them per the problem above.

**Comment by mhegazy** [comment]
We will need some additional information for this issue to be actionable.

**Comment by aappddeevv** [comment]
I’ll try to produce it but the issue was a combination of some tsc flags
would produce inconsistent with regard to the presence of the import for
tslib.

**Comment by RoboPhred** [comment]
I encountered this as well using jsx: react.  I will try and cut a minimal reproduction from the project.  Most files had the import where required, but one did not and failed at runtime over _importStar.

In the mean time, I have had to disable noEmitHelpers.

**Comment by aappddeevv** [comment]
I disabled that as well to keep moving.

**Comment by aappddeevv** [comment]
I think it has something to do with the new interop flag.
