### ISSUE TITLE
Cryptic error message when using namespace

### ISSUE THREAD

**Issue by ericmorand** [microsoft/TypeScript#22168]
I want to split my library sources in multiple files but still have them all compiled into a single final library.

Here is my current source code:

a.ts

```
import {DateTime} from "luxon";

namespace MyLib {
    export class A{
        talk() {
            let dt = new DateTime();
            
            console.warn('Hello', dt);
        }
    }
}
```

b.ts

```
namespace MyLib {
    export class B extends MyLib.A {
    }
}
```

When i try to compile this, I receive the following error:

`src/b.ts(2,34): error TS2339: Property 'A' does not exist on type 'typeof MyLib'.`

Here is my tsconfig.json:

```
{
  "compilerOptions": {
    "target": "ES2017",
    "module": "AMD",
    "outDir": "./lib"
  },
  "include": [
    "src/**/*.ts"
  ]
}
```

I'm probably not using namespaces the right way and I'd be glad of someone can point me to the right direction. Right now, the documentation is extremely vague about namespaces and the error is cryptic at best.

**Comment by DanielRosenwasser** [comment]
Hey there, this issue tracker isn't meant to work as a support forum. These questions tend to be better suited for StackOverflow. You may want to open a question up there instead. Thanks!

**Comment by ericmorand** [comment]
Stackoverflow is a support forum. My question concerns a bug and an error message that only the developers of the project are able to understand and explain.

**Comment by DanielRosenwasser** [comment]
My apologies! I misread the post.

The reason you're running into this is that `a.ts` is a module , while `b.ts` is global code. 

With a module, contents aren't visible unless they're exported, and everything that's exported has to be explicitly imported. `b.ts` won't be able to see the contents of `a.ts` for that reason, but even if you import `MyLib` from `a.ts`, namespaces can't merge with imports or exports. That lack of merging behavior is part of why namespaces have limited value when using modules (see @RyanCavanaugh's StackOverflow answer [here](https://stackoverflow.com/questions/30357634/how-do-i-use-namespaces-with-typescript-external-modules) which explains this a bit using candy).

In general, we don't recommend mixing modules and namespaces. Modules are the primary mechanism for encapsulation nowadays. If you want a single flat library file, you may want to look at [a bundler like Rollup](https://github.com/rollup/rollup) which can give you a single API surface in several different formats.

**Comment by DanielRosenwasser** [comment]
As to what we can do here to provide a better error message, it's unclear how we could do a reasonable job to give better error messages without trying to dig through the whole world (e.g. "it's not in *this* `MyLib`, but could it be in *another* `MyLib`?")
