### ISSUE TITLE
Project still compiles even with noEmitOnError

### ISSUE THREAD

**Issue by wizofaus** [Microsoft/TypeScript#2216]
Hi,

I've set the noEmitOnError flag in my project file, and indeed TypeScript is not generating a js file if the .ts file contains errors, but I can't figure out how to get the project compilation to fail.
I tried adding a reference to the previously generated js file, and then deleting it, and sure enough this works - the first time. But once the js file has been generated once, if future compilations fail, the project build still succeeds. What am I missing?

Thanks
Dylan

**Comment by wizofaus** [comment]
Turns out this was due to the "Compile on save" option, which seems to ignore the noEmitOnError flag.
Without this it works fine, even without adding a reference to the js file into the project.

**Comment by mhegazy** [comment]
@CyrusNajmabadi i think you had a fix for this one?

**Comment by CyrusNajmabadi** [comment]
As of 85d71b28835db3601e14ea12e1fd31738aac8de7 we should no longer be emitting anything if you have noEmitOnErrors.  This will be true even for CompileOnSave.

**Comment by andremarcondesteixeira** [comment]
This is not fixed. I still see the issue in 2.8.1
