### ISSUE TITLE
Expose emitFiles in the public .d.ts

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#2217]
If you want to make modifications to a tree and emit that, you are required to write your own emitter as emitFiles is not exposed in the public .d.ts file. tools like: https://github.com/sitepen/dts-generator would not be able to leverage the compiler API.

**Comment by csnover** [comment]
Seems like `Program#emit` might work OK for our use case? Other things were removed entirely like `createEmitHostFromProgram` that were important to the old way, but if Program can do it directly, then we’re probably in good shape.

That said, there are some bugs in declaration emitting ES6 modules syntax (#2220 and #2221), so I’m waiting for those to be addressed before I can verify this.

**Comment by mhegazy** [comment]
since this is not needed any more, i will close it. @csnover please let us know if this is not the case.
