### ISSUE TITLE
Using a code fix applies a fix to file with same name, but different casing

### ISSUE THREAD

**Issue by jchitel** [Microsoft/TypeScript#22173]
**TypeScript Version:**  2.8.0-dev.20180213 (macOS)

**Search Terms:** code fix file case casing

**Code**

```ts
// No code, this is a tsserver issue
```

I have a file named `parser.ts`, and there used to be a file in the same directory called `Parser.ts`, but that file has since been deleted, removed from the git repo, quite simply gone. In `parser.ts`, I used a value from another module and went to go use a code fix to automatically import it.

**Expected behavior:**

Applying the code fix will add the import to the current file.

**Actual behavior:**

VS Code opens a new file in the same directory called `Parser.ts`, and applies the code fix there instead of `parser.ts`. However, while the contents of `parser.ts` have not changed, the line with the error no longer shows an error.

**Playground Link:** n/a (this is a tsserver issue)

**Related Issues:** n/a

**Additional info:** Here is the tsserver trace that points to where the problem comes from:

```
[Trace  - 19:12:49] Sending request: getCodeFixes (78). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/<path>/parser.ts",
    "startLine": 52,
    "startOffset": 37,
    "endLine": 52,
    "endOffset": 45,
    "errorCodes": [
        2304
    ]
}
[Trace  - 19:12:49] Response received: getCodeFixes (78). Request took 5 ms. Success: true 
Result: [
    {
        "description": "Import '<value>' from module \"~/<module>\"",
        "changes": [
            {
                "fileName": "/<path>/Parser.ts",
                "textChanges": [
                    {
                        "start": {
                            "line": 4,
                            "offset": 1
                        },
                        "end": {
                            "line": 4,
                            "offset": 1
                        },
                        "newText": "import { <value> } from '~/<module>';\n"
                    }
                ]
            }
        ]
    }
]
```

 The request to get code fixes is sent for `parser.ts`, but the response is for `Parser.ts`.

I have scrubbed the ~/Library/Application Support/Code/ directory, done a full grep of my entire computer for `"\bParser\.ts\b"` and come up with nothing. That file no longer exists on my computer, period, but tsserver seems to think that it does. I'm thinking this has to be some weird caching issue.

Aside from the fact that it seems to think that file still exists, I think there may be a separate issue with case insensitivity here. Even if that file *did* still exist (which it could on macOS's case sensitive file system), the code fix should be applied to the correct one.

**Comment by jchitel** [comment]
Seems like it may be related to https://github.com/Microsoft/vscode/issues/12448

**Comment by jchitel** [comment]
Ok, referencing this comment on that issue:

> i was too having issue of opening two copies of same file in an typescript project. finally was able to fix them by updating all imports in .ts file and references for directories in tsconfig.json, to match in case.

I had not yet refactored all of my other files to use the renamed file. They were still trying to import from `Parser.ts`. Doing a global replace on all of these to import from `parser` instead resolved this issue.

I believe that what is happening is that tsserver sees the references before reaching the actual file, and due to some incorrect case insensitive matching, the `Parser.ts` path ends up getting registered in a cache instead of the correct path. Thus any requests will resolve to the incorrect name instead.

I'm probably a bit off on that, but the problem is likely something similar to this. Regardless, this was a valid workaround.

**Comment by jchitel** [comment]
Linking this one as well: https://github.com/Microsoft/vscode/issues/40682

**Comment by andy-ms** [comment]
Related to #19329

**Comment by mhegazy** [comment]
> I had not yet refactored all of my other files to use the renamed file. They were still trying to import from Parser.ts. Doing a global replace on all of these to import from parser instead resolved this issue.

The compiler follows imports, `/// <references...` and looks at tsconfig.json entries to look for files. if the file is referenced in any of these instances using the lower case name, it will be used. consider using `--forceConsistentCasingInFileNames` to catch some of these issues.
