### ISSUE TITLE
QuickFix adds imports before copyright header

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Microsoft/TypeScript#22174]
**TypeScript Version:**  2.8.0-dev.20180220

**Search Terms:** quickfix copyright import comments jsdoc

**Code**

```typescript
/**
 * @copyright Microsoft Corporation. All rights reserved.
 */

// importedValue should offer a quick fix to import from "./file";
export const value = importedValue;
```

**Expected behavior:**

```typescript
/**
 * @copyright Microsoft Corporation. All rights reserved.
 */

import { importedValue } from "./file";

export const value = importedValue;
```

**Actual behavior:**

```typescript
import { importedValue } from "./file";

/**
 * @copyright Microsoft Corporation. All rights reserved.
 */

export const value = importedValue;
```

**Related Issues:** https://github.com/Microsoft/TypeScript/issues/17318

This is something like the opposite of 17318. 

IMO the solution here should be to put the imports after a `@copyright` header, but before the first jsdoc otherwise.

This is particularly juicy because of TSLint's [file-header](https://palantir.github.io/tslint/rules/file-header) auto-fixer. If you insert a new import with TS, it inserts it before the existing copyright; if you then save with a workspace setting that auto-fixes on save, you get a _second_ copyright header. Kind of funny.

**Comment by weswigham** [comment]
Start your copyright comment with `/*!` instead of `/**` and it should stay pinned to the top.

**Comment by JoshuaKGoldberg** [comment]
Looks like an issue with TSLint. Thanks!
