### ISSUE TITLE
tsc -w should not clear screen if I don't want it to

### ISSUE THREAD

**Issue by iffy** [Microsoft/TypeScript#22188]
Issue #13020 makes `tsc -w` always clear the screen.  This is annoying when:

- `tsc -w` is part of several processes being run in the same terminal
- I care about previous output.

**Expected behavior:**

`tsc -w` should not clear the screen before every compile if a certain additional flag is provided.

**Actual behavior:**

`tsc -w` always clears the screen before compilation.

**Related Issues:**

- #13020

**Comment by j-oliveras** [comment]
Duplicate or related to #21295.

**Comment by roblav96** [comment]
@mhegazy Just merge the https://github.com/Microsoft/TypeScript/pull/21303 @JoshuaKGoldberg

**Comment by mhegazy** [comment]
already tracked by  #21295.
