### ISSUE TITLE
No error about missed "declare" modifier for a top level class inside d.ts

### ISSUE THREAD

**Issue by bashor** [Microsoft/TypeScript#22187]
**TypeScript Version:**  2.7.2

**Search Terms:**  missed declare modifier for a top level class inside d.ts 

**Code**

de.d.ts
```ts
export class Foo {
}
```

test.ts
```ts
import { Foo } from "./de";
new Foo()
```

**Expected behavior:**
Compiler error, like:
`error TS1046: A 'declare' modifier is required for a top level declaration in a .d.ts file.`

**Actual behavior**
Code is compiled successfully

**Related Issues:**
#1940

**Comment by andy-ms** [comment]
Since it's in a module in a `.d.ts` file, `declare` is optional.

**Comment by bashor** [comment]
@andy-ms where can I read exact rules? Why the same rule is not applied to function?

**Comment by andy-ms** [comment]
We don't currently have an up-to-date spec, but any information would be here: http://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html

**Comment by bashor** [comment]
@andy-ms, thank you!

Honestly, I didn't find rules about when `declare` is required and when it's optional. But I've seen that all/most examples omit it when use `export` modifier.

**Comment by bashor** [comment]
@andy-ms so, should I or you close the issue?
