### ISSUE TITLE
Declare method refactor/quickfix should fill in proper parameter types

### ISSUE THREAD

**Issue by markusjohnsson** [Microsoft/TypeScript#22180]
The "declare method" quick fix should not declare all parameter (and return type) as `any`, but should instead enter the proper argument types:

```typescript
class A { 
}
var a = new A();
a.foo(123, "qwerty");
  ~~~ 
```
Declare method 'foo' should yield:

```typescript
class A {
    foo(arg0: number, arg1: string) {
        throw new Error("Method not implemented");
    }
}
``` 

Rather than the current behaviour of using `any` in all positions.

**Comment by markusjohnsson** [comment]
Also, it would be a good idea to use any available names in argument positions as parameter names.

Example:
```
class A { }
const x = 123;
const y = "asd";
const a = new A();
a.foo(x, y);  
```

"Declare method 'foo'" should use 'x' and 'y' as parameter names instead of 'arg0' and 'arg1':

```
class A {
    foo(x: number, y: string) {
        throw new Error("Method not implemented");
    }
}
```

**Comment by mhegazy** [comment]
@Kingwl something you would be interested in? we already have the inference code in https://github.com/Microsoft/TypeScript/blob/master/src/services/codefixes/inferFromUsage.ts, we will just need to extract it, and use it here.

**Comment by markusjohnsson** [comment]
I’ve actually got something to work myself, if you are accepting PRs, could clean it up tomorrow.

**Comment by mhegazy** [comment]
thanks @markusjohnsson!
