### ISSUE TITLE
Feature Request: Allow typeof with index types

### ISSUE THREAD

**Issue by SLaks** [Microsoft/TypeScript#22194]
Revised feature request:  Please allow `typeof` in mapped types:

Given a type like this:

```ts
type Enum<TEnum> = {
    [TName in keyof typeof TEnum]: TEnum[TName]
}
```

I want to write

```ts
type Schema<TObject> = {
    [TName in keyof TObject]: Enum<typeof (TObject[TName])>
}
```

This way, given the property declared as `foo: SomeEnum`, the mapped type would produce `foo: Enum<typeof SomeEnum>`, which would then match actual property `foo: SomeEnum`.

`TObject[TName]` is a value, so `typeof` should apply.  However, this currently gives a syntax error.
Removing the parentheses complains (correctly) that `TObject` itself is a type, not a value.

------

**TypeScript Version:**  2.7.0

**Search Terms:** typeof keyof generic

**Playground Link:**  
Minimal: http://www.typescriptlang.org/play/index.html#src=enum%20Color%20%7B%0D%0A%20%20%20%20Red%2C%20Green%2C%20Blue%0D%0A%7D%0D%0A%0D%0Atype%20Enum%3CTEnum%3E%20%3D%20%7B%0D%0A%20%20%20%20%5BTName%20in%20keyof%20TEnum%5D%3A%20TEnum%5BTName%5D%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20MyClass%20%7B%0D%0A%20%20%20%20color%3A%20Color%3B%0D%0A%7D%0D%0A%0D%0Aconst%20test%3A%20Enum%3Ctypeof%20(MyClass%5B'name'%5D)%20%3E%20%3D%20Color%3B%0D%0A

With motivating real-world example:
http://www.typescriptlang.org/play/index.html#src=enum%20Color%20%7B%0D%0A%20%20%20%20Red%2C%20Green%2C%20Blue%0D%0A%7D%0D%0A%0D%0Aenum%20Shape%20%7B%0D%0A%20%20%20%20Square%2C%20Circle%2C%20Triangle%0D%0A%7D%0D%0A%0D%0Atype%20Enum%3CTEnum%3E%20%3D%20%7B%0D%0A%20%20%20%20%5BTName%20in%20keyof%20TEnum%5D%3A%20TEnum%5BTName%5D%3B%0D%0A%7D%3B%0D%0A%0D%0A%2F%2F%20Simple%20sample%3A%0D%0Aconst%20test%3A%20Enum%3Ctypeof%20Shape%3E%20%3D%20Shape%3B%0D%0A%0D%0A%2F%2F%20Real-world%20sample%20usage%3A%0D%0Ainterface%20MyClass%20%7B%0D%0A%20%20%20%20name%3A%20Date%3B%0D%0A%20%20%20%20color%3A%20Color%3B%0D%0A%20%20%20%20shape%3A%20Shape%3B%0D%0A%7D%0D%0Atype%20Schema%3CT%3E%20%3D%20%7B%0D%0A%20%20%20%20%5BTName%20in%20keyof%20T%5D%3A%20(%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20For%20classes%3A%0D%0A%20%20%20%20%20%20%20%20%7B%20new()%3A%20T%5BTName%5D%20%7D%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20For%20enums%3A%0D%0A%20%20%20%20%20%20%20%20%7CEnum%3CT%5BTName%5D%3E%0D%0A%20%20%20%20)%0D%0A%7D%0D%0A%0D%0Aconst%20myClassSchema%3A%20Schema%3CMyClass%3E%20%3D%20%7B%0D%0A%20%20%20%20name%3A%20Date%2C%0D%0A%20%20%20%20color%3A%20Color%2C%0D%0A%20%20%20%20shape%3A%20Shape%2C%0D%0A%7D%3B

**Comment by s-ve** [comment]
I don't think that supporting `typeof TEnum` here would make much sense since `TEnum` can only refer to a type. `typeof` always expect a value as operand.

You can refactor your code like this :

``` ts
type Enum<TEnum> = {
    [TName in keyof TEnum]: TEnum[TName]
};

const test: Enum<typeof Color> = Color;
```

But then it would be equivalent to simply writing :

``` ts
const test = Color;
```

Could you maybe clarify the purpose of your `Enum` type ? 🙂

**Comment by andy-ms** [comment]
Got this working for *string enums* whose values are the same as their keys:

```ts
enum Color {
    Red = "Red", Green = "Green", Blue = "Blue",
}

enum Shape {
    Square = "Square", Circle = "Circle", Triangle = "Triangle",
}
type Enum<TEnum extends string> = {
    [TName in TEnum]: string;
};
const test: Enum<Shape> = Shape;

// Real-world sample usage:
interface MyClass {
    name: Date;
    color: Color;
    shape: Shape;
}
type SchemaForType<T> = T extends string ? Enum<T> : { new(): T }
type Schema<T> = {
    [TName in keyof T]: SchemaForType<T[TName]>
}
const myClassSchema: Schema<MyClass> = {
    name: Date,
    color: Color, // There is correctly a compile error if you write `color: Shape`!
    shape: Shape,
};
```

Unfortunately this does not work for normal number enums right now, because we can't put those in mapped types:
```ts
type Enum<TEnum extends number> = {
    [TName in TEnum]: string; // Error: TEnum is not a string type...
};
const test: Enum<Shape> = Shape;
```
Closest issue I can find for that is #22105

**Comment by SLaks** [comment]
@s-ve See the end of my playground link.

Basically, I want to use `Enum<T>` together with mapped types, to create a type that maps an object to its property types.
Something like

```ts
type Schema<TObject> = {
    [TName in keyof TObject]: Enum<TObject[TName]>
}

interface MyClass {
    color: Color;
}

const schema: Schema<MyClass> = {
    color: Color,
};
```

My feature request should actually be to allow `[TName in keyof TObject]: Enum<typeof (TObject[TName])>`, which is currently a syntax error.

**Comment by andy-ms** [comment]
@s-ve is correct that you can't get the `typeof` something that's already a type. This might be confusing since there is a type `Color` and a value `Color` that share the same name, but they're two different things. If we have `x: Color` there's no way to get access to the *value* `Color`. You can't use `typeof typeof x` since `typeof x` is a type, not a value. `typeof Color` works because we interpret `Color` as referring to the value and not the type.

**Comment by SLaks** [comment]
But `TObject[TName]` is a value, so `typeof` that should work.

**Comment by andy-ms** [comment]
No, `TObject[TName]` is the *type* of the property.

**Comment by SLaks** [comment]
@andy-ms Your solution only works when the enum values match their names (since you're using `TName in TEnum` instead of `keyof`).

**Comment by SLaks** [comment]
I see; I was misunderstanding how `typeof` works for enums.

Is there any way to access the static members of a type?

Can you add such a feature?

**Comment by andy-ms** [comment]
Just realized my example wouldn't work because `T extends string ? Enum<T> : { new(): T }` maps over the union `T`, so it just has to be `Enum<"Red"> | Enum<"Green"> | Enum<"Blue">`, while I wanted `Enum<"Red" | "Green" | "Blue">`. @sandersn Was there a workaround for that?

> Is there any way to access the static members of a type?

We don't have the notion of a static member of a type -- a type just describes instances. If you write `class C { static a() {} b() {} }`, the type `C` *just* describes `{ b(): void }` and has no reference to the static side of the class, which is described by a separate type `typeof C` (where `C` is the value, not the type).

**Comment by s-ve** [comment]
@SLaks
Sorry I didn't pay attention to your playground link, it makes more sense now !

@andy-ms 
This seems to do the trick :

``` ts
type ExtendsString<T extends string> = T;
type SchemaForType<T> = T extends ExtendsString<infer U> ? Enum<U> : { new(): T };
```

**Comment by mhegazy** [comment]
`[T] extends [string] ? ... ` will not distribute

**Comment by s-ve** [comment]
@mhegazy Unfortunately Typescript will not infer that `T` extends `string` in the conditional true branch.

I don't know if this is expected or not.

Related : #21870
