### ISSUE TITLE
Implement Getter and Setters for ES3 via compiler

### ISSUE THREAD

**Issue by SamuelEnglard** [Microsoft/TypeScript#2219]
The power of properties is great and sadly they don't exist in ES3. We do though have a compiler that could convert the property and all it's calls to get and set calls.

For naming I think simply appending _get or _set to the property's name would work. Then it's just a case of looking for all reads, replacing them with calls to property_get() and all sets with calls to property_set(value).

We have the calling information since we can do refactoring, so I'd think changing the usages to function calls could be done.

Thoughts?

**Comment by RyanCavanaugh** [comment]
Consider code like this:
```ts
interface Point {
  x: number;
  y: number;
}

function print(pt: Point) {
  console.log('x = ' + pt.x + ', y = ' + pt.y);
}

var a = { x: 3, y: 5 };
var b = {
  get x() { return 1; },
  get y() { return 2; }
};

var c = Math.random() > 0.5 ? a : b;
print(c);
```

**Comment by SamuelEnglard** [comment]
Why not

    function print(pt: Point) {
        console.log('x = ' + (pt.x || pt.x_get()) + ', y = ' + (pt.y || pt.get_y()));
    }
?

**Comment by RyanCavanaugh** [comment]
You're proposing that every single property access in a program be rewritten to something like that?

**Comment by SamuelEnglard** [comment]
Not every, only cases like the above where we don't know

**Comment by RyanCavanaugh** [comment]
The problem is that `print` may have been compiled in a separate compilation from `b`, so the compiler has no way of knowing that the function *won't* be invoked with some object that uses getters. So "the cases where we don't know" is actually equivalent to "every"

**Comment by SamuelEnglard** [comment]
Sadly yes, short of doing that for every property access (which I agree would be a bit much) my idea is dead.

**Comment by birbilis** [comment]
Compiled objects could have some annotation/metadata to declare their target Javascript (during compilation). So when you imported precompiled blackbox .ts code and compiled some code of yours using them the compiler would/should be able to know what semantics to use to talk to them, depending on their target and your target.

Also, if you specified ES3 target for example and you were using third-party precompiled modules compiled for ES5 it would be able to warn you against it.

Now if you mixed and matched several precompiled .ts of different targets at runtime it would be a problem, but could resolve that by suggesting the use of file-extensions of the style .es3.ts and .es5.ts that users could have optionally to be specific about target and avoid such mixups if they do such practice
