### ISSUE TITLE
Symbol properties with constructor value bad code generation regression 2.6 > 2.7

### ISSUE THREAD

**Issue by paulbatessonos** [Microsoft/TypeScript#22196]
**TypeScript Version:**  2.7.0-2.8.0-dev.20180224

**Search Terms:** 

- Symbol
- Symbol property 
- Symbol constructor

**Code**

```ts
const scope = Symbol('symbol')
const keys = {
    nameFunc: Symbol('function')
}

export class Test {
    // The presence of this causes a later cascade of symbol generation failure
    private readonly [scope] = {};

    [keys.nameFunc](): boolean {
        return true
    }
}
```

**Expected behavior:**

2.6 Generates the correct 

```javascript
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const scope = Symbol('symbol');
const keys = {
    nameFunc: Symbol('function')
};
class Test {
    constructor() {
        // The presence of this causes a later cascade of symbol generation failure
        this[scope] = {};
    }
    [keys.nameFunc]() {
        return true;
    }
}
exports.Test = Test;
//# sourceMappingURL=test.js.map
```

**Actual behavior:**

2.7 Generates the following

```javascript
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const scope = Symbol('symbol');
const keys = {
    nameFunc: Symbol('function')
};
class Test {
    constructor() {
        // The presence of this causes a later cascade of symbol generation failure
        this[_a] = {};
    }

    // HERE: Problem with the function declaration
    [_a = scope, keys.nameFunc]() {
        return true;
    }
}
exports.Test = Test;
var _a;
//# sourceMappingURL=test.js.map
```

**Playground Link:** 
[Playground](http://www.typescriptlang.org/play/#src=const%20scope%20%3D%20Symbol('symbol')%0D%0Aconst%20keys%20%3D%20%7B%0D%0A%20%20%20%20nameFunc%3A%20Symbol('function')%0D%0A%7D%0D%0A%0D%0Aexport%20class%20Test%20%7B%0D%0A%20%20%20%20%2F%2F%20The%20presence%20of%20this%20causes%20a%20later%20cascade%20of%20symbol%20generation%20failure%0D%0A%20%20%20%20private%20readonly%20%5Bscope%5D%20%3D%20%7B%7D%0D%0A%0D%0A%20%20%20%20async%20%5Bkeys.nameFunc%5D()%3A%20Promise%3CBoolean%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20true%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A)

**Related Issues:**

**Comment by weswigham** [comment]
What's the issue, specifically, in the `2.7` version's output? I'm not seeing how it obviously differs beyond more correct caching of the private `scope` symbol-property-name.

**Comment by paulbatessonos** [comment]
The constructor generates `this[_a] = {}`,  which is fine as long as `_a` is assigned prior to construction. However `_a` is attempted assignment in a function declaration `[_a = scope, keys.nameFunc]() { ...`.

2.7 and beyond generate this incorrect code. 2.6 generates the correct code in the **Expected** output.

**Comment by paulbatessonos** [comment]
As a further test, after the class declaration I immediately attempted calling the constructor function on `Test` and it was generated before the `var _a` declaration.

```ts
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const tslib_1 = require("tslib");
const scope = Symbol('symbol');
const keys = {
    nameFunc: Symbol('function')
};
class Test {
    constructor() {
        // The presence of this causes a later cascade of symbol generation failure
        this[_a] = {};
    }
    [_a = scope, keys.nameFunc]() {
        return tslib_1.__awaiter(this, void 0, void 0, function* () {
            return true;
        });
    }
}
exports.Test = Test;
new Test();
var _a;
//# sourceMappingURL=test.js.map
```

**Comment by weswigham** [comment]
`var _a` is hoisted. No matter where in scope it is declared, the name is available from the start of the scope.

**Comment by weswigham** [comment]
And it's definitely assigned prior to construction in your example, as class computed names are evaluated once when the class is first encountered. (And, in fact, is the first execution position after the class declaration itself)

**Comment by weswigham** [comment]
Tbqh, the only situation I can think of where this execution order could be a problem is when you circularly reference the class and construct it before its' names have executed, which should cause a TDZ violation when not downleveled, anyway (and we don't polyfill tdz errors, so the value being undefined is what you get). Is your original code much more complicated than what you've posted here?

**Comment by paulbatessonos** [comment]
Right, apologies, I was conflating the declaration and time of assignment (confusing statement - lets move past that).

The generated source, when run under Node.js 8.9.4 produces the following error:

```
    [_a = scope, keys.nameFunc]() {
               ^

SyntaxError: Unexpected token ,
```

**Comment by paulbatessonos** [comment]
If I use `private readonly scope = {}` (non-symbol) the generated code is fine. 

Alternatively if the function `[keys.nameFunc]()` is instead `aFunctionName()` the generated code is also fine.

It's a combination of using both generating very different code from either case.

**Comment by paulbatessonos** [comment]
In TS 2.6 we just `@ts-ignored` the warning on the declaration of `private readonly [scope]`. TS2.7 there is no warning for this syntax. 

Using one of the built-in Symbols like `Symbol.iterator` in place of `scope` produced the correct code. It's only when using a custom `Symbol`

**Comment by weswigham** [comment]
Looks like a parse error. I'm not at a PC to check right now, but if you wrap `_a = scope, keys.nameFunc` in parenthesis, does the syntax error go away? It may just be that our output isn't parenthesizing the expression appropriately.

**Comment by paulbatessonos** [comment]
Yep, that cinched it. `[(_a = scope, keys.funcName)]() { .. }` parses and can be executed.

**Comment by weswigham** [comment]
Righto, thanks. Looks like both our parser and emitter are more lax than they should be with respect to the expressions allowed in computed names.

**Comment by paulbatessonos** [comment]
Thanks for keeping up with the thread @weswigham.

**Comment by weswigham** [comment]
No problem.
