### ISSUE TITLE
New Website Logo: Airsquire

### ISSUE THREAD

**Issue by YouYue123** [Microsoft/TypeScript#22201]
Please fill the following out:

- Name: Airsquire
- Homepage url: https://www.airsquire.co/
- Brand Guidelines/Licensing: N/A
- Logo: https://airsquire.github.io/AirLanding/airsquire_logo.svg

![image](https://airsquire.github.io/AirLanding/airsquire_logo.svg)

**Comment by mhegazy** [comment]
Thanks. Added to the site. Should be live next week.
