### ISSUE TITLE
New Website Logo: Centra

### ISSUE THREAD

**Issue by karol-majewski** [Microsoft/TypeScript#22200]
- Name: Centra
- Homepage url: https://www.centra.com/
- Brand Guidelines/Licensing: N/A
- Logo: ![centra-logo-full-black](https://user-images.githubusercontent.com/20233319/36722834-e6a79ce4-1bae-11e8-842c-a92a64c1b84f.png)

**Comment by mhegazy** [comment]
Thanks. Added to the site. Should be live next week.

**Comment by karol-majewski** [comment]
@mhegazy Thank you! 🙇
