### ISSUE TITLE
Type inference for nested mapped types is broken in 2.8.0-dev.20180227

### ISSUE THREAD

**Issue by dhruvrajvanshi** [Microsoft/TypeScript#22219]
Trying to make type definitions for Joi library for validation of objects against a schema.
The following code snippet works fine in 2.6.2 but has wrong type inference in 2.8.0

**TypeScript Version:**  2.8.0-dev.20180227

**Search Terms:** 
Type inference bug 2.8, nested mapped types

**Code**

```ts
const Joi: JoiStatic = <any>{};

interface JoiStatic {
    string(): StringSchema<string | undefined>;
    object(): ObjectSchema<never>;
}
interface AnySchema<T> {
    readonly ___val: T | undefined;
};

type SchemaMap<T> = {
    [K in keyof T]: AnySchema<T[K]>;
};
interface ObjectSchema<T> extends AnySchema<T> {
    keys<U>(k: SchemaMap<U>): ObjectSchema<U>;
};
interface StringSchema<S extends string> extends AnySchema<S | undefined> {
    anythingThatUsesS(n: S): S;
};

const schema1 = Joi.object().keys({
    x: Joi.string(),
    y: Joi.object().keys({
        name: Joi.string()
    })
});

```

**Expected behavior:**
Type of schema1 should be inferred as this (2.6.2 does it correctly).

```ts
ObjectSchema<{
    x: string;
    y: {
        name: string;
    };
}>
```

**Actual behavior:**

```ts
ObjectSchema<{
    x: string;
    y: {
        name: any; // here's the problem
    };
}>
```
**Playground Link:**  
[This](https://www.typescriptlang.org/play/#src=const%20Joi%3A%20JoiStatic%20%3D%20%3Cany%3E%7B%7D%3B%0D%0A%0D%0Ainterface%20JoiStatic%20%7B%0D%0A%20%20%20%20string()%3A%20StringSchema%3Cstring%20%7C%20undefined%3E%3B%0D%0A%20%20%20%20object()%3A%20ObjectSchema%3Cnever%3E%3B%0D%0A%7D%0D%0Ainterface%20AnySchema%3CT%3E%20%7B%0D%0A%20%20%20%20readonly%20___val%3A%20T%20%7C%20undefined%3B%0D%0A%7D%3B%0D%0A%0D%0Atype%20SchemaMap%3CT%3E%20%3D%20%7B%0D%0A%20%20%20%20%5BK%20in%20keyof%20T%5D%3A%20AnySchema%3CT%5BK%5D%3E%3B%0D%0A%7D%3B%0D%0Ainterface%20ObjectSchema%3CT%3E%20extends%20AnySchema%3CT%3E%20%7B%0D%0A%20%20%20%20keys%3CU%3E(k%3A%20SchemaMap%3CU%3E)%3A%20ObjectSchema%3CU%3E%3B%0D%0A%7D%3B%0D%0Ainterface%20StringSchema%3CS%20extends%20string%3E%20extends%20AnySchema%3CS%20%7C%20undefined%3E%20%7B%0D%0A%20%20%20%20anythingThatUsesS(n%3A%20S)%3A%20S%3B%0D%0A%7D%3B%0D%0A%0D%0Aconst%20schema1%20%3D%20Joi.object().keys(%7B%0D%0A%20%20%20%20x%3A%20Joi.string()%2C%0D%0A%20%20%20%20y%3A%20Joi.object().keys(%7B%0D%0A%20%20%20%20%20%20%20%20name%3A%20Joi.string()%0D%0A%20%20%20%20%7D)%0D%0A%7D)%3B)

**Related Issues:**
Possibly this: #22169. Like #22169, this is worse on 2.7.2 but the difference is that unlike that one, this is only partially fixed in 2.8.0-dev.20180227

**Comment by jcalz** [comment]
Is this related to #14041?  I think this is just a bug in Intellisense.  If you examine the following
```ts
schema1.___val!.y.name // string
``` 
it is correctly recognized as a `string` as opposed to `any`.

**Comment by dhruvrajvanshi** [comment]
Indeed it is. Closing this.
