### ISSUE TITLE
Class decorators: missed opportunity to implement "contract checking"

### ISSUE THREAD

**Issue by ericmorand** [Microsoft/TypeScript#22227]
Hello TypeScript community,

In the process of removing all instanceof usage from my library, I have been considering using class decorators to implement _contract checking_ - there may be a better name but the idea is to be able to know at runtime that an instance implements a given contract.

This is (wrongly) done in PHP by checking if an instance implements a given interface but this is not an option in JavaScript. So I was thinking about using class decorators as contract holders to implement this with TypeScript.

For example, let's assume that I need to know that an object is safe to be output (i.e. it will not need to be escaped). I can write a class decorator that adds a isSafe property to the constructor of the class:

```typescript
function safeDecorator<T extends {new(...args:any[]):{}}>(constructor:T): any {
    return class extends constructor {
        isSafe = true;
    }
}

@safeDecorator
export class Foo {

}
```

Works as intended, every instance of Foo now also comes with the isSafe property.

Problems arise when I need to check that an instance is safe:

```typescript
let foo = new Foo();

if (foo.isSafe) {
}
```

This code returns a TS2339 error: `Property isSafe does not exist on type 'Foo'`

Having the compiler "noImplicitAny" option set to true, the following alternative throws a TS7017 error: 
`Element implicitely has an 'any' type[...]`:

```typescript
let foo = new Foo();

if (foo['isSafe']) {
}
```

I don't know if this must be considered a bug or if it normal because the compiler has no chance to know that the isSafe propery has been injected (after all, it happens at runtime) but I feel like this is a missed opportunity to great things. In there current state, class decorators are basically useless because all they can do is modifying already declared properties and that's it. All other attempt to modify the class further leads to compile errors.

Is there a way to hint the compiler about what the decorator actually do?

Should TypeScript natively support mixins, something between a Class and an Interface?

```typescript
mixin Safe {
    isSafe: boolean = true;
}

mixin Fancy {
    isFancy: boolean = true;
}

class Foo uses Safe, Fancy {
}

let foo = new Foo();

// foo has both isSafe and isFancy properties set to true
```

**Comment by andy-ms** [comment]
The [design goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals) would exclude adding a new kind of class to the language.
There is currently a [proposal](https://github.com/tc39/proposal-decorators) for adding decorators to the language (note that TypeScript's decorators are experimental and differ from the proposal).

You can declare members to exist in a class using this syntax:
```ts
interface IsSafe { isSafe: boolean; }

interface Foo extends IsSafe {}
class Foo {}

new Foo().isSafe; //compiles
```
So you can do whatever dynamic magic you need to inject the members from `isSafe` into the class.

**Comment by s-ve** [comment]
#4881 duplicate ?

**Comment by ericmorand** [comment]
@andy-ms, wow, how is that code working? Foo class is not explictely implementing Foo interface and still you're perfectly right, it compiles perfectly. 

Is this because both Foo interface and class share the same name?

About the rest of your ansyer, yes, I guess we should wait for the ESNext proposal to be finalized before moving further.

**Comment by ericmorand** [comment]
@s-ve, definitely. Sorry about this.

**Comment by s-ve** [comment]
@ericmorand 

> Is this because both Foo interface and class share the same name?

Yes, it's called declaration merging 🙂. There is an article about it [in the documentation](https://www.typescriptlang.org/docs/handbook/declaration-merging.html).
