### ISSUE TITLE
Incorrect type inference from parameter contraint in conditional types

### ISSUE THREAD

**Issue by s-ve** [Microsoft/TypeScript#22221]
**TypeScript Version:**
2.8.0-dev.201802213

**Search Terms:**
conditional, inference, constraint

**Code**
``` ts
type MustBeString<T extends string> = T;
type EnsureIsString<T> = T extends MustBeString<infer U> ? U : never;

type Test1 = EnsureIsString<'hello'>; //'hello'
type Test2 = EnsureIsString<42>; //42
```
**Expected behavior:**
`Test2` has type `never`

**Actual behavior:**
`Test2` has type `42`, even though typescript correctly infers that `U` must be a `string` in the conditional true branch.

**Playground Link:**
**Related issues:**
#21937 #21631

**Comment by jcalz** [comment]
Related to #21937?  (Please note that the issue template does ask you for search terms and related issues)

**Comment by s-ve** [comment]
@jcalz I just updated my issue to match the template

**Comment by mhegazy** [comment]
The constraint failure does not invalidate the inference really. do you have a use case where this is needed?

**Comment by s-ve** [comment]
@mhegazy 

What motivated me to report this is the fact that this construct can make Typescript ignore type constraints :

``` ts
type A<T extends string> = {
  [TKey in T]: string
};

type B<T extends string> = T;
type C<T> = T extends B<infer U> ? A<U> : never;
type D = C<boolean>; // Evaluated as A<boolean>, which shouldn't be valid
```

it also seems inconsistent to me since this code works as expected :

``` ts
type B<T extends string> = {a: T};
type C<T> = T extends B<infer U> ? A<U> : never;
type D = C<{a: boolean}>; // never, as expected
```

I don't know if it can be a problem in real world code though... I can't think of any use-case where an "Identity" type such as `B` would be useful in a conditional type...
