### ISSUE TITLE
"Rename Symbol" should not rename "this" in static method when rename class name

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#22223]
_From @Maroon1 on February 28, 2018 4:0_

The "this" is renamed also when we rename class name with "Rename Symbol".

eg:
```javascript
class Foo {
  static a() { }
  static fn() { this.a(); }
}
```
rename Foo to Bar, and result:
```javascript
class Bar {
  static a() { }
  static fn() { Bar.a(); // should not rename "this"! }
}
```

_Copied from original issue: Microsoft/vscode#44696_

**Comment by mjbvz** [comment]
_From @vscodebot[bot] on February 28, 2018 4:0_

(Experimental duplicate detection)
Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
- [Rename provider api should support renaming of the file (#10659)](https://www.github.com/Microsoft/vscode/issues/10659) 
- [Preview Rename Symbol (#9575)](https://www.github.com/Microsoft/vscode/issues/9575) 
- [Fix #39306 - allow tab to change file currently being renamed (#39437)](https://www.github.com/Microsoft/vscode/issues/39437)

**Comment by mjbvz** [comment]
Related to #5863?

**Comment by andy-ms** [comment]
Was broken by #20483, that should be avoided if we're renaming.
