### ISSUE TITLE
Allow bitwise test on `undefined`

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#22230]
**TypeScript Version:**  2.8.0-dev.20180228

**Search Terms:** undefined strictNullChecks bitwise and or

(ref: https://github.com/Microsoft/TypeScript/pull/22088#issuecomment-367531430)

**Code**

```ts
const enum Flags { A = 2 ** 1, B = 2 ** 2 }
function f(flags?: Flags) {
    if (flags & Flags.B) {
    }
}
```

**Expected behavior:**

No error. `&` and `|` work well on undefined values: `undefined | 2` is `2`, `undefined & 2` is `0`. Contrast with `undefined + 2` which is `NaN`.

**Actual behavior:**

```ts
src/a.ts(3,9): error TS2532: Object is possibly 'undefined'.
```

**Comment by RyanCavanaugh** [comment]
It's *possible* `0` and `undefined` are intended to have the same semantics in this function, but we really don't know. Arguably the signature should be `flags: Flags = 0` if that's the case
