### ISSUE TITLE
Import fix suggestions are traversing upwards after #21398

### ISSUE THREAD

**Issue by alextreppass** [Microsoft/TypeScript#22249]
**TypeScript Version:**  2.7.2

**Search Terms:** autoimport import fix relative paths baseUrl

**Code**

In our codebase, we have the compiler option `baseUrl` set to `./src`. We have no other path-related settings.

Given the following files:

- `src/some/path/to/consumer.ts`
- `src/some/other/path/util.ts`

When editing `consumer.ts` to import a member of `util.ts`, VSCode will suggest and import the following:

**Expected behavior:**

- Prior to #21398: `import { thing } from 'some/other/path/util';`

**Actual behavior:**

- After #21398: `import { thing } from '../../other/path/util';`

It looks like the change by @andy-ms was to fix #19920, but I am unable to configure `paths` and/or `rootDirs` in a way that brings back the old behaviour here.

Restrictions:
- I can't change the `baseUrl` to `"./"` as we don't want to see `src/` prepended to our imports
- We need the full path (just without `src/`) for easy grepping and refactoring

I've tested a revert of https://github.com/Microsoft/TypeScript/commit/d333d889c1d42a98deceb81545ac5a9a57448abe against current TypeScript master (https://github.com/Microsoft/TypeScript/commit/ec249f7f674d1663a5d031376d75efface967885 at the time of writing) and can confirm the old behaviour comes back.

If it's by design, any chance this logic could be tweaked to take into account some combination of `"baseUrl": "./src"` with `paths` and/or `rootDirs`? Or the behaviour made configurable via some other mechanism? 

Working with `../../../../`... in a large and fast-moving codebase is hard.

**Related Issues:**
https://github.com/Microsoft/TypeScript/issues/19920
https://github.com/Microsoft/vscode/issues/44699

Thanks

**Comment by mhegazy** [comment]
Related to #20619

**Comment by alextreppass** [comment]
May be a duplicate (or just related to) https://github.com/Microsoft/TypeScript/issues/21860
