### ISSUE TITLE
can't import a pure string file following the typescript Wiki

### ISSUE THREAD

**Issue by maiff** [Microsoft/TypeScript#22253]
[the wiki](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#wildcard-character-in-module-names)

I creat an Angular project with angular-cli (Version :5.2 )
mac OS
node version: 8.1.4
typescript version: 2.5.3
```
// tsconfig.app.json
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "baseUrl": "./",
    "module": "es2015",
    "types": []
  },
  "exclude": [
    "test.ts",
    "**/*.spec.ts"
  ]
}

```
```
//tsconfig.json
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  }
}

```
```
// typings.d.ts
/* SystemJS module definition */
declare var module: NodeModule;
interface NodeModule {
  id: string;
}

declare module "*!text" {
  const content: string;
  export default content;
}
// like wiki's do
```
```
// one file import
import fileContent from './xyz.txt!text';
// definitely have xyz.txt

console.log(fileContent)
```

but i get this error
![](http://7xpser.com1.z0.glb.clouddn.com//18-3-1/82961127.jpg)
```
// if you can't see the pic 
ERROR in ./src/app/app.component.ts
Module not found: Error: Can't resolve 'text' in '/Users/maiff/Workspace/Angular/my-app/src/app'
```

**Comment by s-ve** [comment]
It doesn't look like an error related to Typescript. May be you should ask this on the [angular-cli](https://github.com/angular/angular-cli/issues) issue tracker ?

Are you sure angular-cli can load plain text file using the format `*!text` ? You probably need to have an appropriate loader such as [raw-loader](https://github.com/webpack-contrib/raw-loader) installed in order to do that.

**Comment by maiff** [comment]
@s-ve Thanks! I injected a raw-loader into angular-cli and I solve it.
