### ISSUE TITLE
proposal:Type Safe Method Decorator

### ISSUE THREAD

**Issue by kgtkr** [Microsoft/TypeScript#22258]
example:`(x:number)=>void` only

```ts
class A{
  @d//OK
  f1(){}

  @d//OK
  f2(x:number){}

  @d//Error
  f3(x:string){}
}
```

**Comment by s-ve** [comment]
You can try this :

``` ts
type Fn = (x:number) =>void

function d<T, TProp extends string, TTarget extends {[TKey in TProp]: Fn }>(target: TTarget, propertyKey: TProp, descriptor: TypedPropertyDescriptor<T>) {

}

export class Foo {
    @d //OK
    test1() {
    }

    @d //OK
    test2(param: number) {        
    }

    @d //Compile error
    test3(x: string) {
    }
}
```
[Playground link](https://www.typescriptlang.org/play/#src=type%20Fn%20%3D%20(x%3Anumber)%20%3D%3Evoid%0A%0Afunction%20d%3CT%2C%20TProp%20extends%20string%2C%20TTarget%20extends%20%7B%5BTKey%20in%20TProp%5D%3A%20Fn%20%7D%3E(target%3A%20TTarget%2C%20propertyKey%3A%20TProp%2C%20descriptor%3A%20TypedPropertyDescriptor%3CT%3E)%20%7B%0A%0A%7D%0A%0Aexport%20class%20Foo%20%7B%0A%20%20%20%20%40d%20%2F%2FOK%0A%20%20%20%20test1()%20%7B%0A%20%20%20%20%7D%0A%0A%20%20%20%20%40d%20%2F%2FOK%0A%20%20%20%20test2(param%3A%20number)%20%7B%20%20%20%20%20%20%20%20%0A%20%20%20%20%7D%0A%0A%20%20%20%20%40d%20%2F%2FCompile%20error%0A%20%20%20%20test3(x%3A%20string)%20%7B%0A%20%20%20%20%7D%0A%7D)
