### ISSUE TITLE
`never` inference propagation should instead be bounded inference propagation

### ISSUE THREAD

**Issue by weswigham** [Microsoft/TypeScript#22277]
As when a propagated `never` is inferred at a contravariant position today, it continues propagating as `never` into that position which then limits the domain of the type, instead of the intended expansion of it. In effect, rather than propagating `never`, or `{}` directly, we should be propagating the appropriate bound for the position, which in contravariant positions is the opposite bound of the input bound (I think).

You can see this need in some of our RWC failures that started today - `PromiseLike`'s `.then` can no longer be inferred correctly against a `reject` parameter of type `() => void`.

**Comment by ahejlsberg** [comment]
Yeah, that's not good. The propagation is definitely appropriate for `any` types (since they're both top and bottom types), but I'm going to back it out again for `never` types. Things are fine without it, I mostly included it for completeness.
