### ISSUE TITLE
typing the single character { reformats the line this is type on, removing white space

### ISSUE THREAD

**Issue by erikeidt** [Microsoft/TypeScript#22271]
**TypeScript Version:**  2.5.3

(CyrusNajmabadi directed me here..) <br/> NOTE: this is a problem with editing/formatting in Visual Studio (15.5.7)

**Code**

```ts
function hello ( parameter: number ): void 
```
Enter the above into a .ts file in Visual Studio.  Type a single { at the end of this line.

**Expected behavior:**
function hello ( parameter: number ): void {

**Actual behavior:**
function hello( parameter: number ): void {

The space before the open ( is removed.  You have to type ctrl-z to remove it.
<br/>
There is no option to suppress this annoying behavior for javascript/typescript.
(There are options for C# but they do not affect this.)

**Playground Link:**  

**Related Issues:**
I found this related item: https://github.com/dotnet/roslyn/issues/4435 <br/>

**Comment by pjannesen** [comment]
This is already reported in [developercommunity.visualstudio.com] (https://developercommunity.visualstudio.com/content/problem/161986/vs-155-unwanted-automatic-formatting-on.html) and issue [21139](https://github.com/Microsoft/TypeScript/issues/21139)

There is a workaround by hacking tsserver.js in C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6
Visual Studio calls getFormattingEditsAfterKeystroke for formating. Make sure this function always returns []; This will disable all automatic reformats.

**Comment by billti** [comment]
This option has been added in VS and will ship in an upcoming release. (Details at https://github.com/Microsoft/TypeScript/issues/21139#issuecomment-372442640 ).
