### ISSUE TITLE
Or typing does not inherit array methods

### ISSUE THREAD

**Issue by bpasero** [Microsoft/TypeScript#2227]
I would like to do this:

```typescript
var foo:string[]|number[] = [];
foo.forEach((element) => {
	
});
```

In the playground I am getting an error that I cannot call forEach. 

Furthermore I would expect the "element" to be of type "string|number".

**Comment by RyanCavanaugh** [comment]
We don't "combine" function argument types in a union type -- it's not clear that's actually the correct behavior. `foo` could be of type `Array<string|number>` if that would be accurate.
