### ISSUE TITLE
Can't use keyof index for indexing intersection of Partial<T> and another type in generic class<T>.

### ISSUE THREAD

**Issue by Griffork** [Microsoft/TypeScript#22286]
**Bug**
I'm trying to use an object's key to index an intersection into a partial of an object and another object, but I'm getting an error. 
Note: this error only shows up in a generic class. Using plain types I was not able to replicate it.

**TypeScript Version:**
2.7.1-insiders.20180127 (playground)
2.3.1 (visual studio tools)
2.7.2 (command line)

**Search Terms:** 
Keyof, intersection, union, Partial, index, merge.

**Code**

``` Typescript
    interface Rum {
        "ho hum": string; 
    }

    interface Color {
        "blue": number;
    }

    class Thingy<T> {
        mything: Rum & Partial<T>;
        log(param: keyof T) {
            console.log(this.mything[param]); //ERROR!
        }
    }
```

**Expected behavior:**
No errors.

**Actual behavior:**
test.ts(13,25): error TS2536: Type 'keyof T' cannot be used to index type 'Rum & Partial<T>'.

[**Playground link**](https://www.typescriptlang.org/play/#src=%0D%0A%0D%0A%20%20%20%20interface%20Rum%20%7B%0D%0A%20%20%20%20%20%20%20%20%22ho%20hum%22%3A%20string%3B%20%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20interface%20Color%20%7B%0D%0A%20%20%20%20%20%20%20%20%22blue%22%3A%20number%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20class%20Thingy%3CT%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20mything%3A%20Rum%20%26%20Partial%3CT%3E%0D%0A%20%20%20%20%20%20%20%20log(param%3A%20keyof%20T)%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20console.log(this.mything%5Bparam%5D)%3B%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20)

**Comment by mhegazy** [comment]
Should be fixed by https://github.com/Microsoft/TypeScript/pull/22300

**Comment by Griffork** [comment]
@mhegazy does this mean that the best typing I'm going to get is `this.mything[param]: string | number`?

**Comment by mhegazy** [comment]
it is actually `(Rum & Partial<T>)[keyof T]`, which is generic, and not assignable to `string | number`, since `T` can have additional properties when it is instantiated.

**Comment by Griffork** [comment]
This is not fixed in the latest nightly: typescript@2.8.0-dev.20180308
Can we reopen this?
