### ISSUE TITLE
Check if tsc --watch is already running for a given directory/project

### ISSUE THREAD

**Issue by SuhairZain** [microsoft/TypeScript#22284]
This is both a question and a feature request. I did ask on [StackOverflow](https://stackoverflow.com/questions/48841711/is-there-a-way-to-check-if-a-tsc-watch-is-running-in-the-current-directory) about 2 weeks ago, but I didn't get any replies there, so asking here.

Our use case is that I'm running a React Native app written in TS and in addition to the RN Packager, we also have a `tsc --watch` running. For running the app, along with all the packagers and compilers, we have a build script. We can check if a RN Packager instance is already running by checking for response at a specific port. But in case of `tsc --watch`, I couldn't find such an option and everytime the script is run, we start a new `tsc --watch` instance.

Is there a way to check if a `tsc --watch` is already running for a given directory/project or to have a new instance fail if one is already running?

**Comment by DanielRosenwasser** [comment]
Right now there is not, but you can create a build script that will do this for you by creating a tempfile and seeing if it exists.

**Comment by SuhairZain** [comment]
@DanielRosenwasser I'm sorry, but my experience with bash and build scripts is fairly limited. When you say create a tempfile, you mean before I run `tsc --watch` from my script, create a temp file? And is there a reliable way to ensure that when the process is ended, the temp file will be deleted? If so, I think it can solve this issue.

**Comment by DanielRosenwasser** [comment]
I'm not a bash wizard myself either; however, I just found that @ORESoftware wrote [this handy tool](https://github.com/ORESoftware/quicklock#complicated-usage-with-nodejs) for what appears to be the same purpose.

Basically, you can associate it with your shell's process ID, and when your shell closes, you'll be able to run the script again.

**Comment by SuhairZain** [comment]
It does seem handy. I'll give it a try. Any chance that something like this will be a good addition to the tsc --watch process itself?

**Comment by ORESoftware** [comment]
you can use this tool I created for this same purpose:

https://github.com/ORESoftware/quicklock

install it with:
curl -o- https://raw.githubusercontent.com/oresoftware/quicklock/master/install.sh | bash

then you just can just like so:

ql_acquire_lock "$PWD" # equivalent to just ql_acquire_lock w/o an arg

you don't need to explicitly release the lock, it will be release when you kill the script.
So to be exact, what you are looking for are these 3 lines:

```bash
#!/usr/bin/env bash
ql_acquire_lock
tsc --watch
```

**Comment by SuhairZain** [comment]
@ORESoftware What about the node version? My build script is written in JS, so can I use a locally installed version of quicklock to achieve the same functionality? Any caveats I should be aware of?

**Comment by ORESoftware** [comment]
quicklock will be available in all shells and for all node versions, if you put quicklock in .bash_profile. quicklook is totally independent of node.js, you can any command below the ql_acquire_lock command, and it will block/exit if someone else is using the lock already.

**Comment by SuhairZain** [comment]
@ORESoftware Does it work on windows?

**Comment by ORESoftware** [comment]
It doesn't work on Windows yet, but I have a Windows machine at home and can get it working on Windows.

**Comment by SuhairZain** [comment]
That'd be great. Right now, we have people working on both macOS and Windows in our team and I can only use tools which work on both. Which is why I asked you about having quicklock as a local npm dependency, without any messing around with .bash_profile or such.

**Comment by DanielRosenwasser** [comment]
Y'know, I realize you're working with React Native. I know @alloy and @orta came up with a script to get TypeScript automatically hooked up with Metro so you wouldn't have to compile, but I can't seem to find the file anymore.

**Comment by orta** [comment]
Our custom code got merged into https://github.com/ds300/react-native-typescript-transformer

**Comment by RyanCavanaugh** [comment]
There doesn't seem to be too much demand for this, and would create a lot of additional complexity on our end to handle it.
