### ISSUE TITLE
Assignment to a narrowed union type variable makes it un-narrowed

### ISSUE THREAD

**Issue by duanyao** [Microsoft/TypeScript#2228]
tsc 1.4.1.0 fires error for the following code:

```js
var c: string[]|string = 'a';
if (typeof c === 'string') {
    c = 'b'; // this assignment makes type of c become string[]|string again.
    var s: string = c; // error: Type 'string | string[]' is not assignable to type 'string'. Type 'string[]' is not assignable to type 'string'.
}
```

**Comment by RyanCavanaugh** [comment]
Any assignment in the body of an `if` "turns off" narrowing. We don't want to do a bunch of reasoning about side effects (e.g. if that assignment occurs in a function expression, when would that assignment be considered to take effect?).

We might improve this with better flow analysis in the future, but this pattern doesn't seem to be too common in practice.

**Comment by NoelAbrahams** [comment]
This is somewhat surprising behaviour - having just stumbled upon it.
