### ISSUE TITLE
How to handle this when this is a function

### ISSUE THREAD

**Issue by dagda1** [Microsoft/TypeScript#22285]
I have created this [playground](https://www.typescriptlang.org/play/#src=export%20interface%20Extender%3CA%20extends%20%7B%20new%20(name%3A%20string)%3A%20A%20%7D%3E%20%7B%0D%0A%20%20instance%3A%20(constructor%3A%20%7B%20new()%20%7D%2C%20methods%3F%3A%20%7B%7D)%20%3D%3E%20void%3B%0D%0A%20%20for%3A%20(value%3A%20any)%20%3D%3E%20A%3B%0D%0A%20%20symbol%3A%20Symbol%3B%0D%0A%7D%0D%0A%0D%0Aexport%20function%20extend%3CA%20extends%20%7B%20new(name%3A%20string)%20%7D%3E(%0D%0A%20%20Class%3A%20A%0D%0A)%3A%20A%20%26%20Extender%3CA%3E%20%7B%0D%0A%20%20const%20name%20%3D%20Class.name%3B%0D%0A%20%20const%20Extended%20%3D%20%3CA%20%26%20Extender%3CA%3E%3EClass%3B%0D%0A%0D%0A%20%20let%20symbol%20%3D%20Symbol(name)%3B%0D%0A%0D%0A%20%20Extended.instance%20%3D%20function(constructor%2C%20methods)%20%7B%0D%0A%20%20%20%20constructor.prototype%5Bsymbol%5D%20%3D%20methods%3B%0D%0A%20%20%7D%3B%0D%0A%0D%0A%20%20Extended.symbol%20%3D%20symbol%3B%0D%0A%0D%0A%20%20Extended.for%20%3D%20function%20_for(value%3A%20any)%3A%20A%20%7B%0D%0A%20%20%20%20let%20i%20%3D%20value%5Bsymbol%5D%3B%0D%0A%0D%0A%20%20%20%20return%20i%3B%0D%0A%20%20%7D%3B%20%20%0D%0A%0D%0A%20%20const%20properties%20%3D%20getOwnPropertyDescriptors(Class.prototype)%3B%0D%0A%0D%0A%20%20%20%20Object.keys(properties)%0D%0A%20%20%20%20.filter(key%20%3D%3E%20key%20!%3D%20%22constructor%22)%0D%0A%20%20%20%20.forEach(key%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20Extended.prototype%5Bkey%5D%20%3D%20Extended.prototype%5Bkey%5D.bind(Extended.for)%3B%0D%0A%20%20%20%20%7D)%3B%0D%0A%0D%0A%20%20return%20Extended%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20Interface%3CA%3E%20%7B%0D%0A%20%20doSomething%3A%20(left%3A%20A%2C%20right%3A%20A)%20%3D%3E%20A%3B%0D%0A%7D%0D%0A%0D%0Aconst%20Implementation%20%3D%20extend(class%20Implementation%3CA%3E%20implements%20Interface%3CA%3E%20%7B%0D%0A%20%20doSomething(left%3A%20A%2C%20right%3A%20A)%20%7B%0D%0A%20%20%20%20let%20%7B%20doSomething%20%7D%20%3D%20this(left)%3B%0D%0A%0D%0A%20%20%20%20return%20doSomething(left%2C%20right)%3B%0D%0A%20%20%7D%0D%0A%7D)%3B%0D%0A%0D%0Aconst%20%7B%20doSomething%20%7D%20%3D%20Implementation.prototype%3B%0D%0A%0D%0AImplementation.instance(Object%2C%20%7B%0D%0A%20%20doSomething(o1%2C%20o2)%20%7B%0D%0A%20%20%20%20let%20properties%20%3D%20Object.assign(%7B%7D%2C%20propertiesOf(o1)%2C%20propertiesOf(o2))%3B%0D%0A%20%20%20%20return%20Object.create(getPrototypeOf(o1)%2C%20properties)%3B%0D%0A%20%20%7D%0D%0A%7D)%3B%0D%0A%0D%0Aconst%20n%20%3D%20doSomething(%7Bo%3A%201%7D%2C%20%7Bb%3A%202%7D)%3B) that shows the problem.

The code looks like this:

```
export interface Extender<A extends { new (name: string): A }> {
  instance: (constructor: { new() }, methods?: {}) => void;
  for: (value: any) => A;
  symbol: Symbol;
}

export function extend<A extends { new(name: string) }>(
  Class: A
): A & Extender<A> {
  const name = Class.name;
  const Extended = <A & Extender<A>>Class;

  let symbol = Symbol(name);

  Extended.instance = function(constructor, methods) {
    constructor.prototype[symbol] = methods;
  };

  Extended.symbol = symbol;

  Extended.for = function _for(value: any): A {
    let i = value[symbol];

    return i;
  };  

  const properties = getOwnPropertyDescriptors(Class.prototype);

    Object.keys(properties)
    .filter(key => key != "constructor")
    .forEach(key => {
      Extended.prototype[key] = Extended.prototype[key].bind(Extended.for);
    });

  return Extended;
}

interface Interface<A> {
  doSomething: (left: A, right: A) => A;
}

const Implementation = extend(class Implementation<A> implements Interface<A> {
  doSomething(left: A, right: A) {
    let { doSomething } = this(left);

    return doSomething(left, right);
  }
});

const { doSomething } = Implementation.prototype;

Implementation.instance(Object, {
  doSomething(o1, o2) {
    let properties = Object.assign({}, propertiesOf(o1), propertiesOf(o2));
    return Object.create(getPrototypeOf(o1), properties);
  }
});

doSomething({o: 1}, {b: 2});
```

How do I handle `this` on line 44 of the playground

`let { doSomething } = this(left);`

the call to `this` will return the specific `doSomething`.

At the moment I get the error, this lacks a callable signature.

If I add the false this param like this:

`doSomething(this: (a: A) => Implementation<A>, left: A, right: A) {`

And if I then export the function

`export {doSomething} = Implementation.prototype;`

And I then try to use the function:

`doSomething({o: 1}, {b: 2});` I get the error:

> The 'this' context of type 'void' is not assignable to method's 'this' of type '(a: any) => Implementation<any>'.

I realise this is quite contrived but is this too contrived for typescript?

**Comment by andy-ms** [comment]
In your example you grab `doSomething` directly off the prototype, so I think TypeScript is correctly giving you an error when it says `The 'this' context of type 'void' is not assignable to method's 'this' of type '(a: any) => Implementation`. Where would the callable `this` come from? Could you come up with an example that works in JavaScript at runtime first before trying to get it to type-check? Then try and come up with a minimal example that shows a problem with the types.

**Comment by dagda1** [comment]
@andy-ms 

Ok so here is a [jsfiddle](https://jsfiddle.net/dagda1/1zm60eL6/27/) of plain js and here is the code:

```
function extend(Class) {
  const name = Class.name;

  const symbol = Symbol(name);

  // callable `this` in Implementation.doSomething
  // `this` is an alias for Implementation.for
  Class.for = function _for(value) {
    return value[symbol];
  }

  Class.instance = function(constructor, methods) {
    constructor.prototype[symbol] = methods;
  }

  Class.symbol = symbol;

  const properties = Object.getOwnPropertyDescriptors(Class.prototype);

  Object.keys(properties)
    .filter(key => key !== 'constructor')
    .forEach(key => {
      // bind `for` so `this()` calls `Class.for` 
      Class.prototype[key] = Class.prototype[key].bind(Class.for)
    });

  return Class
}

const Adder = extend(
  class Adder {
    add(left, right) {
      const {
        add
      } = this(left);
      return add(left, right);
    }
  }
)

const {
  add
} = Adder.prototype;

Adder.instance(Number, {
  add(left, right) {
    return left + right;
  }
});

console.log(add(1, 2)); // 3

Adder.instance(String, {
  add(left, right) {
    return left.concat(right);
  }
});

console.log(add("1", "2")); // "12"
```

```Class.for``` is what is callable this code:

```
      const {
        add
      } = this(left);
```

This will return the correct `add` dependant if it is a `String` or a `Number`.

This is the code that makes `this` an alias to `Class.for`

```
  Object.keys(properties)
    .filter(key => key !== 'constructor')
    .forEach(key => {
      // bind for so `this()` calls `Class.for` 
      Class.prototype[key] = Class.prototype[key].bind(Class.for)
    });
```

So back to the typescript example:

it would be:

```
export interface Adder<A> {
  add(left: A, right: A) => A;
}

const Adder = extend(
  class Adder<A> {
     add(this: (a: A) => Adder<A>, left: A, right: A): A {
       const {add} = this(left);  // will call Class.for for the specific implementation
       
       return add(left, right);
     }
  }
);

export { add } = Adder.prototype;
```

So is this too exotic for typescript to recognise or can I somehow indicate that `{ add }` has this bound by the call in extend with the line `Class.prototype[key] = Class.prototype[key].bind(Class.for)`

**Comment by andy-ms** [comment]
Basically, to allow you to implement it that way, there would have to be a mapped type that iterates over all methods and removes the `this` parameter. That's not currently possible.
It is strange to write `class` and `this` where `this` will be bound to a static function.
Here's maybe another way to implement what you want:

```ts
class TypeClass<T> {
    readonly symbol: symbol;
    constructor(name: string) {
        this.symbol = Symbol.for(name);
    }

    /**
     * Must manually supply T<sometype> as the type argument because we don't have
     * https://github.com/Microsoft/TypeScript/issues/1213
     */
    instance<J extends T>(type: Function, implementation: J) {
        type.prototype[this.symbol] = implementation;
    }

    // Unfortunately we need to pass in the keys here. Or you could try and get them from the first call to `instance`.
    getImpls(keys: ReadonlyArray<keyof T>): T {
        const out = {} as T;
        for (const key of keys) {
            out[key] = this.getImpl(key);
        }
        return out;
    }

    getImpl<K extends keyof T>(name: K): T[K] {
        return ((left: any, ...args: any[]) => {
            const impl = left[this.symbol] as T;
            return (impl[name] as any)(left, ...args);
        }) as any as T[K]
    }
}

interface Add<T> {
    add(left: T, right: T): T;
}
const adder = new TypeClass<Add<{}>>("Add");
adder.instance<Add<number>>(Number, {
    add: (left, right => left + right,
});
adder.instance<Add<string>>(String, {
    add: left, right => left + right,
});

const { add } = adder.getImpls(["add"]);
console.log(add(1, 3));
console.log(add("1", "3"));
```

**Comment by dagda1** [comment]
This is really great but one thing but typescript does currently not support a symbol as an indexer:
```
type.prototype[this.symbol] = 
```

Is there a way to keep the compiler happy for this?

**Comment by dagda1** [comment]
@andy-ms this has been extremely helpful.  I'm going to close the issue but is it possible to explain this commented line:

```
    instance<J extends T>(type: Function, implementation: J) {
        type.prototype[this.symbol] = implementation;
    }
```

Why is it not just T that is the generic argument?

**Comment by andy-ms** [comment]
`T` is `Add<{}>`, but when you're implementing it you want a specific type like `Add<number>`.

**Comment by dagda1** [comment]
@andy-ms one problem with this is approach is that it expects the first argument to be the type argument, i.e. 
```
return ((left: any, ...args: any[]) => {
            const impl = left[this.symbol] as T;
```

but what if the type in question is not the first argument in question.  Generic types do not exist at runtime in typescript as I've no idea what that would compile to.

I guess I would need to pass something into the `instance` function to indicate what where to get the type from?

**Comment by andy-ms** [comment]
You won't be able to do something like have `sum([])` be `0` or `""` depending on whether you expect a number or string, without adding something else at runtime. Depending on what you're trying to accomplish you might want to store the impl for each type as a whole and pass that in like `sum(NumberAdd, [])`.
