### ISSUE TITLE
`return` incorrectly considered to be yielded

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#22298]
**TypeScript Version:** 2.8.0-dev.20180302

**Code**

```ts
function* f() {
    yield 0;
    return "";
}

for (const x of f()) {
    const n: number = x;
}
```

**Expected behavior:**

No error.

**Actual behavior:**

```
src/a.ts(7,11): error TS2322: Type '"" | 0' is not assignable to type 'number'.
  Type '""' is not assignable to type 'number'.
```

**Comment by DanielRosenwasser** [comment]
See https://github.com/Microsoft/TypeScript/pull/22299#issuecomment-370060063

> The feature is working as intended. The returned type becomes the value of an `IteratorResult` when `done` is `true`.

**Comment by andy-ms** [comment]
Actually, then shouldn't we do the reverse?
```ts
function* f(): IterableIterator<number> {
    return "";
}
```
Currently this is *not* an error, but if you removed the type annotation, the return type would be inferred as `IterableIterator<string>`.
