### ISSUE TITLE
Assert union types using property checking

### ISSUE THREAD

**Issue by vinz243** [Microsoft/TypeScript#22294]
**TypeScript Version:**  2.8.0-dev.20180302

**Search Terms:** Typescript type assert from properties checking

**Code**

```ts
export type FooOrBar = { foo: string } | { bar: string, foobar: string};

let stack: FooOrBar;

if (stack.bar) {
    const { bar, foobar } = stack;
    // ...
}
```

**Expected behavior:**

Typescript should determine that since we are checking if a property is present on an Union type, it can then cast it to the specific sub type 
```ts
{ 
  bar: string,
  foobar: string
}
```

**Actual behavior:**

```
export type FooOrBar = { foo: string } || { bar: string, foobar: string};

let stack: FooOrBar;

if (stack.bar) {
          ^^^

        Property 'bar' does not exist on type 'FooOrBar'.

        const { bar, foobar } = stack;
                ^^^  ^^^^^^

Type 'FooOrBar' has no property 'bar' and no string index signature.
Type 'FooOrBar' has no property 'foobar' and no string index signature.

}
```

**Playground Link:** [Here](https://www.typescriptlang.org/play/index.html#src=export%20type%20FooOrBar%20%3D%20%7B%20foo%3A%20string%20%7D%20%7C%20%7B%20bar%3A%20string%2C%20foobar%3A%20string%7D%3B%0D%0A%0D%0Alet%20stack%3A%20FooOrBar%3B%0D%0A%0D%0Aif%20(stack.bar)%20%7B%0D%0A%20%20%20%20const%20%7B%20bar%2C%20foobar%20%7D%20%3D%20stack%3B%0D%0A%20%20%20%20%2F%2F%20...%0D%0A%7D)
**Related Issues:**

I am aware you can cast it using `<>` or `as`, but it would be really convenient to guess, because this requires to name every possible type, which we all know takes a really long time per variable.

**Comment by andy-ms** [comment]
`if ("bar" in stack)` would work. We don't allow `if (stack.bar)` as a discriminant normally because types are open ended and `{ foo: "", bar: 0 }` might be assigned to a `FooOrBar`.

**Comment by vinz243** [comment]
Awesome, thanks!
