### ISSUE TITLE
Order of module imports causes reference location issues (possible language service caching related)

### ISSUE THREAD

**Issue by marlon-tucker** [Microsoft/TypeScript#22296]
**TypeScript Version:**  2.8.0-dev.20180302

**Search Terms:** module import, modules, 

**Code**
This isn't related to code as such, so I'll do my upmost to describe the problem.

I'm inside a `lerna` mono repo, with two sub projects, `ProjectA` and `ProjectB`. 

`ProjectA` has a dependency on `rxjs`, as does `ProjectB`. 

`ProjectB` has a dependency on `ProjectA` which `lerna` manages by using symlinks.

The problem is, in `ProjectB`, I have a file which does the following imports:

    import { Something } from 'ProjectA';
    import { Subject } from 'rxjs/Subject'
    import { Observable } from "rxjs/Observable";

In that file, there is a class which has a private variable which is a `Subject`, and it exposes it as a `Observable`. However, Typescript is complaining with the following error:

> Type '`Subject<ActionRequestResult<any>>`' is not assignable to type '`Observable<ActionRequestResult<any>>`'.
  Property 'source' is protected but type '`Observable<T>`' is not a class derived from '`Observable<T>`'.

After investigating, it turns out the two `rxjs` imports at the top of the file are actually being imported from two different locations. So even though `Subject` extends `Observable`, it is not the same `Observable` that is being imported and referenced in my file. 

I managed to resolve the issue by moving the `ProjectA` import to the end, as such:

    import { Subject } from 'rxjs/Subject';
    import { Observable } from "rxjs/Observable";
    import { Something } from 'ProjectA';

I suspect this is caused by a caching issue in the language service, as when it imports `ProjectA`, it walks the tree and finds that the class being imported also imports `rxjs/Subject`, so when I import it as well, it reuses the reference it already has.

**Expected behavior:**
`rxjs` is imported from the same location, regardless of what the previous imports have touched.

**Actual behavior:**
`Subject` is imported from `ProjectA`'s node_modules, while `Observable` is imported from `ProjectB`'s node_modules.

**Comment by mhegazy** [comment]
are you compiling with `--preserveSymlinks`?

**Comment by marlon-tucker** [comment]
No I wasn't aware of that compiler flag, I will have to experiment with it when I go to work on Monday though.

I'll report back.
