### ISSUE TITLE
Immediate keyof operation on intersection of generic mapped types incorrectly results in never type

### ISSUE THREAD

**Issue by kpdonn** [Microsoft/TypeScript#22291]
**TypeScript Version:**  2.8.0-dev.20180302

**Search Terms:** 
keyof, intersection, mapped type, generic, type parameter, never

**Code**

```ts
type Example1<T extends string, U extends string> = keyof (Record<T, any> & Record<U, any>)
type Result1 = Example1<'x', 'y'>
// Type of Result1 is never but it should be 'x' | 'y'


/**  The additional examples below are just for context */

type Result2 = keyof (Record<'x', any> & Record<'y', any>) 
// Type of Result2 is 'x' | 'y' as expected

type Example3<T extends string> = keyof (Record<T, any>)
type Result3 = Example3<'x' | 'y'>
// Type of Result3 is 'x' | 'y' as expected

type Example4<T extends string, U extends string> = (Record<T, any> & Record<U, any>)
type Result4 = keyof Example4<'x', 'y'>
// Type of Result4 is 'x' | 'y' as expected

type Example5<T, U> = keyof (T & U)
type Result5 = Example5<Record<'x', any>, Record<'y', any>>
// Type of Result5 is 'x' | 'y' as expected

```

**Expected behavior:**
`Result1` should have a type of `'x' | 'y'`

**Actual behavior:**
`Result1` has a type of `never`

**Playground Link:** 
[Link](https://www.typescriptlang.org/play/#src=type%20Example1%3CT%20extends%20string%2C%20U%20extends%20string%3E%20%3D%20keyof%20(Record%3CT%2C%20any%3E%20%26%20Record%3CU%2C%20any%3E)%0Atype%20Result1%20%3D%20Example1%3C'x'%2C%20'y'%3E%0A%2F%2F%20Type%20of%20Result1%20is%20never%20but%20it%20should%20be%20'x'%20%7C%20'y'%0A%0A%0A%2F**%20%20The%20additional%20examples%20below%20are%20just%20for%20context%20*%2F%0A%0Atype%20Result2%20%3D%20keyof%20(Record%3C'x'%2C%20any%3E%20%26%20Record%3C'y'%2C%20any%3E)%20%0A%2F%2F%20Type%20of%20Result2%20is%20'x'%20%7C%20'y'%20as%20expected%0A%0Atype%20Example3%3CT%20extends%20string%3E%20%3D%20keyof%20(Record%3CT%2C%20any%3E)%0Atype%20Result3%20%3D%20Example3%3C'x'%20%7C%20'y'%3E%0A%2F%2F%20Type%20of%20Result3%20is%20'x'%20%7C%20'y'%20as%20expected%0A%0Atype%20Example4%3CT%20extends%20string%2C%20U%20extends%20string%3E%20%3D%20(Record%3CT%2C%20any%3E%20%26%20Record%3CU%2C%20any%3E)%0Atype%20Result4%20%3D%20keyof%20Example4%3C'x'%2C%20'y'%3E%0A%2F%2F%20Type%20of%20Result4%20is%20'x'%20%7C%20'y'%20as%20expected%0A%0Atype%20Example5%3CT%2C%20U%3E%20%3D%20keyof%20(T%20%26%20U)%0Atype%20Result5%20%3D%20Example5%3CRecord%3C'x'%2C%20any%3E%2C%20Record%3C'y'%2C%20any%3E%3E%0A%2F%2F%20Type%20of%20Result5%20is%20'x'%20%7C%20'y'%20as%20expected%0A)

**Related Issues:**
Maybe #18538? I read through it but honestly I'm not clear on what is going on in that one so I can't say how related it is.

**Comment by ahejlsberg** [comment]
The issue here is that for generic types `A` and `B` we should consider `keyof (A & B)` to be equivalent to `keyof A | keyof B`. We currently don't implement that transformation. If we did, we would transform `keyof (Record<T, any> & Record<U, any>)` to `keyof Record<T, any> | keyof Record<U, any>`, which we already reduce to `T | U`, the desired result.
