### ISSUE TITLE
Can't declare local variables with dynamic(!) imported types 

### ISSUE THREAD

**Issue by STARSCrazy** [Microsoft/TypeScript#22293]
**Bug**
It isn't possible to declare a local variable with an **dynamic** imported class/type.

**TypeScript Version**:
2.7.1 (visual studio tools)

**Code**
```ts
//Module1.ts
export class Class1 {
}

//Module2.ts
export class Class2 {
	public async TestMethod() {
		const module1 = await import("./Module1");
		var instance = new module1.Class1(); //works fine: Variable has type 'Class1'' (implicitly typed)
		var variable1: module1.Class1; //doesn't work!!! Message: Cannot find namespace "module1"
	}
}
```

**Expected behavior:**
The code compiles without errors. It's allowed to declare a variable with an dynamic imported type, because it works with implicitly typed local variables and non-dynamic imported module types, too.

**Actual behavior:**
For the variable1 declaration: Cannot find namespace "module1"

**Comment by andy-ms** [comment]
You can just `import { Class1 as Class1Type } from "module1";` at the top, and as long as you don't use that `Class1Type` as a value, it won't be in the emitted code. Although it would be nicer if we let you write `import { type Class1 } from "module1";` and guaranteed that it wouldn't be used as a value.

**Comment by mhegazy** [comment]
`module1` is a value. a value does not have a type or namespace capabilities. this is one of the basic assumptions that the compiler makes about declarations.. see http://www.typescriptlang.org/docs/handbook/declaration-merging.html for more details.

I think the underlying issue of referring to a type from a module is tracked by 
https://github.com/Microsoft/TypeScript/issues/14844
