### ISSUE TITLE
lib.dom.d.ts v2.7.2 contains two reportValidity method definitions

### ISSUE THREAD

**Issue by MaceWindu** [Microsoft/TypeScript#22301]
**TypeScript Version:**  2.7.2

**Search Terms:** reportValidity

This commit https://github.com/Microsoft/TypeScript/commit/4c8b9796d904f87ffcc6e269f63380db7f2061cc introduced duplicate reportValidity method definition to lib.dom.d.ts.
BTW, is it ok for compiler be silent here?

**Comment by mhegazy** [comment]
> is it ok for compiler be silent here?

yes. as long as the two declarations are identical the compiler allows redeclaration. 

Should be fixed by https://github.com/Microsoft/TSJS-lib-generator/pull/383
