### ISSUE TITLE
Compare function type on OR `||`

### ISSUE THREAD

**Issue by streamich** [Microsoft/TypeScript#22303]
Let's say `noop` has the following signature:

```ts
noop: () => void;
```

This will be an error:

```js
(fn = noop) => {
    fn(abc); // Expected 0 args, received 1
};
```

This will not be an error:

```js
(fn) => {
    (fn || noop)(abc);
};
```

Should TypeScript type check two functions when separated by `||` operator?

**Comment by RyanCavanaugh** [comment]
There's no type provided for `fn`, so `fn` has type `any`, so `fn || noop` has type `any`, and it's legal to invoke `any` with one argument. There's not really anything in that chain of logic we would want to change.
