### ISSUE TITLE
`CodeFixAction` should have a unique identifier to identify its category

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#22307]
When an editor gets `CodeFixAction`, it does not know where it came from, i.e. which code fix or refactoring provided it. it would be helpful for debugging and telemetry to record this.

**Comment by andy-ms** [comment]
Fixed by #23350

**Comment by andy-ms** [comment]
Note: refactors already have a `name` property that can be used for telemetry. @mjbvz
