### ISSUE TITLE
No refactoring/quick-fix suggestions for annotating from JSDoc

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#22305]
```ts
/**
 * @param {number} x
 */
function f(x) {
    
}
```

I'm no longer getting the suggestion to infer the type of `x` from JSDoc. This made me look dumb at the 1ES booth ~2 weeks ago. 😄

**Comment by mhegazy** [comment]
It should be available as a suggessino now:

![image](https://user-images.githubusercontent.com/8000722/39331885-9405fe7a-495a-11e8-839d-4c76b4ea143a.png)
