### ISSUE TITLE
Node CLI

### ISSUE THREAD

**Issue by robertsundstrom** [Microsoft/TypeScript#2231]
The Babel (formerly e6to5) transpiler comes with a special CLI called "babel-node" that lets the user "run" EcmaScript 6 code without thinking about the compiler step. The program transforms the code automatically.

It essentially mimics the nodejs CLI. It also has some extra flags for experimental features and so on.

About this feature: https://babeljs.io/docs/usage/cli/

Would an equivalent "ts-node" be appropriate?

Requires a Require hook #2232;

**Comment by mhegazy** [comment]
The compiler does not support this mode out-of-the box. however, it is not that hard to implement, you can checkout this [example in the wiki](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#a-minimal-compiler) and add a call to eval on the output;  or use an existing package like [typestring](https://www.npmjs.com/package/typestring)

**Comment by stkb** [comment]
Funnily enough I was just looking for a package with this capability too. Was surprised no-one seemed to have written one yet.

It would be really nice if the tsc compiler did this out-of-the-box, like I believe the coffeescript compiler does too. Though there might be a few too many complications for the team to want to include it.

**Comment by mhegazy** [comment]
We did have a --run option in the 0.8/0.9 time frame but then removed it as it did not really belong with the rest of the compiler options. I think this is something that another package that consumes the compiler (tsc-node) would be ideal for.

**Comment by mhegazy** [comment]
with the [ts.transpile](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#a-simple-transform-function) function in place, it should be fairly simple to add a node CLI package. we would be open to taking a PR for this.

**Comment by danquirk** [comment]
Interested parties may want to check out this project https://github.com/blakeembrey/typescript-node

**Comment by DanielRosenwasser** [comment]
I'm going to close the issue. If anyone has any objections, feel free to comment and/or reopen. ts-node seems like a good option at this point.
