### ISSUE TITLE
Any number can be assigned to enum member type

### ISSUE THREAD

**Issue by rlz** [Microsoft/TypeScript#22311]
**Search Terms:**
enum assign number

**Code**

```ts
enum X {
  A, B
}

const x: X.A = 5;

const y: X.A = X.B;
```

**Expected behavior:**
2 errors: when assigning number literal and wrong enum member.

**Actual behavior:**
Typescript allows assigning any number to specific member type.

**Playground Link:**
http://bit.ly/2CZsUrK

**Comment by DanielRosenwasser** [comment]
I was *very close* to marking this as a duplicate (mostly with #6131 in mind, but also sort of #8020 - see https://github.com/Microsoft/TypeScript/issues/8020#issuecomment-208717449).

The key thing here is that we're working with an individual enum *member* type, *not* just an enum type.

**Comment by rlz** [comment]
Yes, I expected member type is `0` in this case, so I should be able to assign `0` but not `5`.

**Comment by RyanCavanaugh** [comment]
So we'd allow e.g. `const x: X.A = 5 + 0` but not `= 5` ?

**Comment by RyanCavanaugh** [comment]
> The key thing here is that we're working with an individual enum member type, not just an enum type.

The problem here is that `X` is just an alias for `X.A | X.B`, so any argument about assignability to `X.A` applies equally to assignability to `X`.

Given the back compat constraints and unlikelihood of finding a bug in userland, keeping the current behavior seems like the best choice of action.
