### ISSUE TITLE
Inconsistent formatting of parameters (regression)

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#22314]
**TypeScript Version:**  2.7.0-dev.201xxxxx

**Search Terms:** 

**Code**

```ts
[]
  .reduce(() =>
    0
  , 0);
```

**Expected behavior:**

Probably it was

```ts
[]
  .reduce(() =>
    0
    , 0);
```

**Actual behavior:**

When format all:

```ts
[]
  .reduce(() =>
    0
    , 0);
```

When format only the last line:

```ts
[]
  .reduce(() =>
    0
  , 0);
```

**Playground Link:**  

**Related Issues:**

**Comment by mhegazy** [comment]
I see the same formatting whether you format all or a single line. and in both cases, the output seems right to me..

**Comment by falsandtru** [comment]
Probably you didn't use the formatting of selected ranges. It is different from the formatting of document.

**Comment by falsandtru** [comment]
I can see this also on the Playground.
