### ISSUE TITLE
Update lib.dom.d.ts to include Node.isConnected

### ISSUE THREAD

**Issue by mlhaufe** [Microsoft/TypeScript#22322]
The property isConnected is not defined in the Node interface:

<https://github.com/Microsoft/TypeScript/blob/master/lib/lib.dom.d.ts#L8439>

References:

<https://developer.mozilla.org/en-US/docs/Web/API/Node/isConnected>
<https://dom.spec.whatwg.org/#dom-node-isconnected>

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.
