### ISSUE TITLE
New Website Logo: [noon]

### ISSUE THREAD

**Issue by zynchro** [Microsoft/TypeScript#22327]
Quite simply:

- Name: noon
- Homepage url: https://www.noon.com
- Brand Guidelines/Licensing: -
- Logo: 
[noon-logo.zip](https://github.com/Microsoft/TypeScript/files/1780616/noon-logo.zip)
(pick either english or arabic)

**Comment by mhegazy** [comment]
Thanks. Added to the site. Should be live next week.
