### ISSUE TITLE
Constraints applied by conditional types not considered when checking signatures

### ISSUE THREAD

**Issue by weswigham** [Microsoft/TypeScript#22347]
**Code**

```ts
declare function log(msg: string): void;
type EQString<T> = T extends string ? T : never;
function c<T>(x: T | string) {
    const y = x as EQString<T>; // assert stringiness
    return log(y);
}
```

**Expected behavior:**
No error.

**Actual behavior:**
```
[ts]
Argument of type 'EQString<T>' is not assignable to parameter of type 'string'.
  Type 'T' is not assignable to type 'string'
```
on `y`.

**Comment by ahejlsberg** [comment]
This is actually working as intended. The constraint added to `T` by the `T extends string` check is in effect *only* in the true branch of the conditional type. The `T` produced by `EqString<T>` is exactly the same `T` as was passed in and it doesn't have any new constraints. To get the desired effect you need to return an intersection type:

```ts
type EQString<T> = T extends string ? T & string : never;
```

**Comment by weswigham** [comment]
Hm. OK. That's not the greatest in the context of using conditionals for control flow narrowing, since it causes you to get intersections instead of constrained generics like you'd expect.

**Comment by kpdonn** [comment]
@weswigham You very well might already know this, but another way to get your example to work without the intersection is

```ts
declare function log(msg: string): void
type MustBeString<T extends string> = T
type EQString<T> = T extends MustBeString<infer U> ? U : never
function c<T>(x: T | string) {
  const y = x as EQString<T> // assert stringiness
  return log(y)
}
```

**Comment by weswigham** [comment]
It's a little verbose but it seems like it checks out.

**Comment by weswigham** [comment]
Erm, doesn't check out too well, in heavy use practice. It may give the result a new constraint on whatever you say, but it forgets its relationship with `T`, which is bad:
```ts
declare function log(msg: string): void
type MustBeString<T extends string> = T;
type EQString<T> = T extends MustBeString<infer U> ? U : never
function c<T>(x: T | string) {
  const y = x as EQString<T> // assert stringiness
  return useStringyT(y); /// Noooooooo

  function useStringyT(x: T & string) {
      return 0;
  }
}
```

**Comment by weswigham** [comment]
*sigh* just intersecting doesn't quite work either, since, for example, in concrete types `ModuleKind.None & number` doesn't simplify back to `ModuleKind.None`.

Replacing the constraint via an `infer` and _then_ intersecting the original `T` with the inference kinda works.
