### ISSUE TITLE
React Higher-Order Components: required props

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/TypeScript#22345]
**TypeScript Version:**  2.7.2

**Search Terms:** 
react hoc higher order component optional prop required

**Code**

I am trying to define a React Higher-Order Component (HOC) which requires the provided component argument to have a specific prop. My solution works, except if the component has the specified prop but marked as optional, TypeScript will throw a type error.

I want this HOC to allow components that have their `foo` prop marked as optional, but disallow components that don't have `foo` prop at all.

```ts
import { Component } from 'react';

type FooProp = {
    foo: string;
};

declare const requireFooProp: <Props extends FooProp>(
    composedComponent: Component<Props>,
) => Component<Props>;

declare const ComponentWithoutFooProp: Component<{}>;
declare const ComponentWithFooProp: Component<{ foo: string }>;
declare const ComponentWithMaybeFooProp: Component<{ foo?: string }>;

// Expect error, got error :-) (with `strictFunctionTypes`)
requireFooProp(ComponentWithoutFooProp);

// Expect no error, got no error :-)
requireFooProp(ComponentWithFooProp);

// Expect no error, but got error :-(
// Argument of type 'Component<{ foo?: string | undefined; }, {}>' is not assignable to parameter of type 'Component<FooProp, {}>'.
requireFooProp(ComponentWithMaybeFooProp);

```

I've also tried:

``` ts
declare const requireFooProp: <Props>(
    composedComponent: Component<Props & FooProp>,
) => Component<Props>;
```

… and I get the same results.

I think I understand why TypeScript behaves like this, however this seems like a common use case where the behaviour is not as desired. Is there an alternative type definition I can use, or is this something TypeScript will handle better in the future?

**Comment by OliverJAsh** [comment]
At the very core of the issue is this behaviour:

``` ts
declare function Component(foo?: string): void;

type ComponentWithFooProp = (foo: string) => void;

declare const requireFooProp: (fn: ComponentWithFooProp) => void;

// Expect error, but got none
requireFooProp(Component);
```

**Comment by OliverJAsh** [comment]
I think this is a simpler example which equally demonstrates the problem

``` ts
{
    type Component<Props> = (props: Props) => { props: Props };

    declare const MyComponentWithFooProp: Component<{ foo: string }>;
    declare const MyComponentWithMaybeFooProp: Component<{ foo?: string }>;
    declare const MyComponentWithoutFooProp: Component<{}>;

    type ComponentWithFooProp = Component<{ foo: string }>;

    declare const requireFooProp: (
        component: ComponentWithFooProp,
    ) => ComponentWithFooProp;

    // Expect no error, got no error :-)
    requireFooProp(MyComponentWithFooProp);

    // Expect no error, but got error :-(
    // Error: Type 'undefined' is not assignable to type 'string'
    requireFooProp(MyComponentWithMaybeFooProp);

    // Expect error, got error :-)
    requireFooProp(MyComponentWithoutFooProp);
}
```

**Comment by kpdonn** [comment]
I've played around with doing the same type of stuff and I had the exact same problems. I'm pretty sure there's two main issues you are running into: 

The first is that almost everywhere in your examples where you have `Component`, you really want `ComponentClass` or `StatelessComponent`. `Component` is basically an instance of a `ComponentClass`. See [JSX page](https://www.typescriptlang.org/docs/handbook/jsx.html) for more explanation. It took me a while to get them straight and know when to use which.

The second issue I'm almost positive you are running into is that you are thinking about your requirements for `requireFooProp` backwards, because I remember doing the same thing. The `ComponentClass`(or `StatelessComponent` if it's easier to think about) want to be passing to `requireFooProp` is basically a callback, and [callbacks are never required to actually do anything with the arguments they are passed](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-functions-with-fewer-parameters-assignable-to-functions-that-take-more-parameters).

So actually you want all 3 of your examples to be accepted with no errors. So your real problem is actually this part:

```ts
// Expect error, got error :-) (with `strictFunctionTypes`)
requireFooProp(ComponentWithoutFooProp);
```

You probably really don't want an error there. The only reason you are getting one is because of the definition React has for `ComponentClass` looks like this:

```ts
 interface ComponentClass<P = {}> {
        new (props: P, context?: any): Component<P, ComponentState>;
}
```

It's the `Component<P, ComponentState>` that causes the problem, because it's basically saying the output of your callback has to include those properties, even though in my experience you will never actually be working with the output `Component` in your own code. It just gets passed to React, which obviously is written in regular Javascript and doesn't know anything about the types anyway. 

In my code I've defined a type that looks like this to get around it:
```ts
declare type ReactComponentCreator<P> = (new (props: P) => React.Component<any>) | React.StatelessComponent<P>;
```

It might be useful to change the actual React types to something like that(`StatelessComponent` actually already has a definition like that), but I'm not sure if there are different use cases that do benefit from the current definition. 

Here is a full code block that I think is closer to what you are trying to do:

```ts
type FooProp = {
    foo: string;
};

type ReactComponentCreator<P> = (new (props: P) => React.Component<any>) | React.StatelessComponent<P>;

declare const requireFooProp: <Props extends FooProp>(
    composedComponent: ReactComponentCreator<Props>,
) => React.ComponentClass<Props>;

declare const ComponentWithFooProp: React.ComponentClass<{ foo: string }>;
declare const ComponentWithMaybeFooProp: React.ComponentClass<{ foo?: string }>;

// actual implementations do extend React.Component though
// which admittedly is confusing.
class ComponentWithoutFooProp extends React.Component<{}> {
  render() {
    return <div>ComponentWithoutFooProp</div>
  }
}

const WrappedWithoutFoo = requireFooProp(ComponentWithoutFooProp);
const Example1 = <WrappedWithoutFoo foo="the wrapper still requires the prop though"/>

const WrappedWithFoo = requireFooProp(ComponentWithFooProp);
const Example2 = <WrappedWithFoo foo="the wrapper still requires the prop though"/>

const WrappedWithMaybeFoo = requireFooProp(ComponentWithMaybeFooProp);
const Example3 = <WrappedWithMaybeFoo foo="the wrapper still requires the prop though"/>
```

**Comment by kpdonn** [comment]
Also what might help to make that second point make sense is to realize what you do want an error for instead is if a component requires a specific property that your decorator isn't going to provide it:

```ts
import * as React from 'react';

type ReactComponentCreator<P> = (new (props: P) => React.Component<any>) | React.StatelessComponent<P>;

function onlyProvidesFoo(ComposedComponent: ReactComponentCreator<FooProp>): React.SFC<FooProp> {
  return ({foo}) => <ComposedComponent foo={foo} />
}

class ComponentWithFooAndBarProps extends React.Component<{foo: string, bar:number}> {
  render() {
    return <div>{this.props.foo} {this.props.bar}</div>
  }
} 

// This will error in strict mode (although apparently it doesn't in non-strict)
const Mismatched = onlyProvidesFoo(ComponentWithFooAndBarProps)
```

**Comment by OliverJAsh** [comment]
@kpdonn Thanks for going into so much detail with your answer. Glad I'm not alone in this.

> The first is that almost everywhere in your examples where you have Component, you really want ComponentClass or StatelessComponent. Component is basically an instance of a ComponentClass. See JSX page for more explanation. It took me a while to get them straight and know when to use which.

Aha, you're right. I meant to use `ComponentType` which is a union of `ComponentClass | StatelessComponent`.

I think I understand the problem now, and how your `ReactComponentCreator` (a custom version of `ComponentType` which passes `any` as the prop type into `Component`) solves the problem :-)

However, I still get errors for stateless components. Try changing the component definitons to:

``` ts
declare const ComponentWithFooProp: React.StatelessComponent<{ foo: string }>;
declare const ComponentWithMaybeFooProp: React.StatelessComponent<{
    foo?: string;
}>;
declare const ComponentWithoutFooProp: React.StatelessComponent<{}>;
```

I think we could apply the same workaround by changing `ReactComponentCreator` to pass `any` as the prop type to `StatelessComponent`:

``` ts
type ReactComponentCreator<P> =
        | (new (props: P) => React.Component<any>)
        | React.StatelessComponent<any>;
```

However, I'm not sure if this has any downsides?

**Comment by OliverJAsh** [comment]
One downside of using `any` as the prop type generic for `StatelessComponent` is it means TypeScript is no longer able to infer the generic.

**Comment by OliverJAsh** [comment]
This could work:

``` ts
type ReactComponentCreator<P> =
        | (new (props: P) => React.Component<any>)
        | ((props: P & { children?: React.ReactNode }) => React.ReactElement<any> | null);
```

**Comment by OliverJAsh** [comment]
For some reason, your workaround fails if the HOC specifies any other props:

``` ts
{
    type FooProp = {
        foo: string;
    };

    type ReactComponentCreator<P> =
        | (new (props: P) => React.Component<any>)
        | React.StatelessComponent<any>;

    declare const requireFooProp: <Props extends FooProp>(
        composedComponent: ReactComponentCreator<Props>
    ) => React.ComponentClass<Props>;

    declare const ComponentWithFooProp: React.ComponentClass<{ foo: string; bar: string; }>;
    declare const ComponentWithMaybeFooProp: React.ComponentClass<{
        foo?: string; bar: string;
    }>;
    declare const ComponentWithoutFooProp: React.ComponentClass<{ bar: string; }>;

    const WrappedWithoutFoo = requireFooProp(ComponentWithoutFooProp);
    const Example1 = (
        <WrappedWithoutFoo foo="the wrapper still requires the prop though" />
    );

    const WrappedWithFoo = requireFooProp(ComponentWithFooProp);
    const Example2 = (
        <WrappedWithFoo foo="the wrapper still requires the prop though" />
    );

    const WrappedWithMaybeFoo = requireFooProp(ComponentWithMaybeFooProp);
    const Example3 = (
        <WrappedWithMaybeFoo foo="the wrapper still requires the prop though" />
    );
}
```

**Comment by kpdonn** [comment]
Yeah that's actually pretty surprising to me that it errors for something like 

```ts
declare const ComponentWithoutFooProp: React.StatelessComponent<{}>;
const WrappedWithoutFoo = requireFooProp(ComponentWithoutFooProp);
```

but I'm seeing the same thing. Not sure why it does that. It doesn't seem to happen though if you actually define a real implementation and don't actually specify `StatelessComponent`: 

```ts
const ComponentWithoutFooProp = () => <div>ComponentWithoutFooProp</div>
// now no error
const WrappedWithoutFoo = requireFooProp(ComponentWithoutFooProp); 
```
I'm guessing that's why I've never seen it before. Your workaround of 

```ts 
type ReactComponentCreator<P> =
        | (new (props: P) => React.Component<any>)
        | ((props: P & { children?: React.ReactNode }) => React.ReactElement<any> | null);
```

Seems to make both cases work though with no downsides that I'm aware of.

**Comment by OliverJAsh** [comment]
Here is a simpler example that demonstrates where we're up to:

``` ts
{
    type FooProp = {
        foo: string;
    };

    type Component<Props> = (props: Props) => { props: any };

    declare const MyComponentWithFooProp: Component<{ foo: string }>;
    declare const MyComponentWithMaybeFooProp: Component<{ foo?: string }>;
    declare const MyComponentWithoutFooProp: Component<{}>;

    declare const MyComponentWithFooAndBarProp: Component<{ foo: string; bar: string; }>;
    declare const MyComponentWithMaybeFooAndBarProp: Component<{ foo?: string; bar: string; }>;
    declare const MyComponentWithoutFooAndBarProp: Component<{ bar: string; }>;

    declare const requireFooProp: <Props extends FooProp>(
        component: Component<Props>,
    ) => Component<Props>;

    // No error :-)
    requireFooProp(MyComponentWithoutFooProp);

    // No error :-)
    requireFooProp(MyComponentWithFooProp);

    // No error :-)
    requireFooProp(MyComponentWithMaybeFooProp);

    // Error :-(
    requireFooProp(MyComponentWithoutFooAndBarProp);

    // No error :-)
    requireFooProp(MyComponentWithFooAndBarProp);

    // Error :-(
    requireFooProp(MyComponentWithMaybeFooAndBarProp);
}
```

**Comment by OliverJAsh** [comment]
> callbacks are never required to actually do anything with the arguments they are passed.

I had a read of https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-functions-with-fewer-parameters-assignable-to-functions-that-take-more-parameters and I'm not sure this applies in our case, as we are always providing the props parameter to the callback (composed component).

Perhaps the issue is that the object parameter is checked contravariantly when we want it to be checked covariantly? Consider:

``` ts
{
    function handler(props: { arg1: string }) {
        // ....
    }
    
    function doSomething(callback: (props: { arg1: string, arg2: number }) => void) {
        callback({ arg1: 'hello', arg2: 42 });
    }
    
    // Expected error, but got no error
    doSomething(handler);
}
```

This works (with `strictFunctionTypes`) because TypeScript checks if parameter `{ arg1: string, arg2: number }` is assignable to `{ arg1: string }`. However, we want to check the opposite: is `{ arg1: string }` assignable to `{ arg1: string, arg2: number }`?

``` ts
{
    declare let x: { arg1: string };
    declare let y: { arg1: string, arg2: number };
    // Contravariance. No error.
    x = y
    // Covariance. Error as expected
    y = x
}
```

My understanding of contravariance/covariance isn't great, so I could be completely wrong.

**Comment by kpdonn** [comment]
Re: Other props: It really depends on how you want the components to work. Here is one option that'd get rid of the errors but might not be the exact behavior you are looking for:

```ts
type FooProp = {
    foo: string;
};

type ReactComponentCreator<P> =
    | (new (props: P) => React.Component<any>)
    | React.StatelessComponent<any>;

declare const requireFooProp: <OtherProps>(
    composedComponent: ReactComponentCreator<FooProp & OtherProps >
) => React.ComponentClass<FooProp & OtherProps>;

declare const ComponentWithFooProp: React.ComponentClass<{ foo: string; bar: string; }>;
declare const ComponentWithMaybeFooProp: React.ComponentClass<{
    foo?: string; bar: string;
}>;
declare const ComponentWithoutFooProp: React.ComponentClass<{ bar: string; }>;

const WrappedWithoutFoo = requireFooProp(ComponentWithoutFooProp);
const Example1 = (
    <WrappedWithoutFoo foo="required here" bar="required here" />
);

const WrappedWithFoo = requireFooProp(ComponentWithFooProp);
const Example2 = (
    <WrappedWithFoo foo="required here" bar="required here" />
);

const WrappedWithMaybeFoo = requireFooProp(ComponentWithMaybeFooProp);
const Example3 = (
    <WrappedWithMaybeFoo foo="*still* required here" bar="required here" />
);
```

**Comment by kpdonn** [comment]
> I had a read of https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-functions-with-fewer-parameters-assignable-to-functions-that-take-more-parameters and I'm not sure this applies in our case, as we are always providing the props parameter to the callback (composed component).

Based on the samples you've posted here I'm confident it definitely applies to you. For example the snippet you posted:

>    ```ts
>    function handler(props: { arg1: string }) {
>        // ....
>    }  
>    function doSomething(callback: (props: { arg1: string, arg2: number }) => void) {
>        callback({ arg1: 'hello', arg2: 42 });
>    }  
>    // Expected error, but got no error
>    doSomething(handler);
>    ```

is still functionally identical to the one from the FAQ. The fact that in yours you have the parameters as properties on an object while in the original from the FAQ they were positional arguments makes no difference in my experience, Typescript is smart enough to handle them the same way.

With respect to React specifically you might find it helpful to write some code using [React without JSX](https://reactjs.org/docs/react-without-jsx.html) to get a clearer picture of what is going on behind the scenes.
