### ISSUE TITLE
codefix: Remove declaration for VarDeclarationList

### ISSUE THREAD

**Issue by Kingwl** [Microsoft/TypeScript#22352]
**TypeScript Version:**  2.7.0-dev.201xxxxx

**Code**

```ts
function f() {
   let a = 1, b = 2, c = 3;
}
```

**Expected behavior:**
```ts
function f() {
}
```
**Actual behavior:**
```ts
function f() {
    let ;
}
```
**Playground Link:**  

**Related Issues:**
#22330

**Comment by mhegazy** [comment]
PRs welcomed!
