### ISSUE TITLE
Daily nightly build publishing has stopped

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#22355]
Since typescript@2.8.0-dev.20180302

**Comment by weswigham** [comment]
Our internal VM that runs the publishes is _missing_. We've dispatched a search party to attempt to locate it; but in the mean time @DanielRosenwasser will you be publishing a nightly release?

**Comment by weswigham** [comment]
`npm info typescript` tells me that there's now a `2.8.0-dev.20180314` out; so we've fixed our build and started publishing nightlies again. 😄

**Comment by falsandtru** [comment]
@DanielRosenwasser @weswigham Can you check publishing system again? Stopped since 20180506.
