### ISSUE TITLE
Codefix to annotate with type from jsdoc reformats entire function

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#22358]
**TypeScript Version:**  2.8.0-dev.20180302

**Code**

```ts
/** @param {number} x */
function f(x) {
    return x+1;
}
```

**Expected behavior:**

```ts
/** @param {number} x */
function f(x: number) {
    return x+1;
}
```

**Actual behavior:**

```ts
/** @param {number} x */
function f(x: number) {
    return x + 1;
}
```

Inferring the type from usage does not have this problem, so we could probably reuse some code from there.

**Comment by mhegazy** [comment]
> Inferring the type from usage does not have this problem, so we could probably reuse some code from there.

inferring type from usage adds a text edit and does not use the change tracker, which is wrong really.. so i would not use it as a reference.

Maybe what we need is a new changeTracker method to add a leading comment.. we can use that in the disableJSDiagnostics as well.
