### ISSUE TITLE
Breaking change interpreting jquery promise types

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#22362]
**TypeScript Version:**  2.8.0-dev.20180302

**Code**

```ts
/// <reference types="jquery" /> // version 3.3.0
const t: JQuery.Promise2<string, Error, number, boolean, any, any> = {} as any;
$.when(t).then((a, b) => {
    const s: string = b; //should fail!
});
```

**Expected behavior:**

Error: `b` is `boolean`.

**Actual behavior:**

No error: `b` is `any`.

Has expected behavior in 2.8.0-dev.20180301, but behavior changed in 2.8.0-dev.20180302.
There are some additional error locations on DefinitelyTyped -- just run `dtslint --installAll` (to ensure you're using `typescript@next`), then `dtslint types jquery`. (The errors don't reproduce with just `tsc` because they come from `// $ExpectType` assertions.)

**Comment by andy-ms** [comment]
Looks like the change was in #22197, at commit https://github.com/Microsoft/TypeScript/commit/9c965aa691d4cc0721b77faa2eead4556bd58ed3

**Comment by RyanCavanaugh** [comment]
@andy-ms can you get to the root of this and see if it's something we need to fix on our side before 2.8 goes out?

**Comment by andy-ms** [comment]
Yep, it's a bug:
```ts
interface MyPromise<T, U> {
    then(cb: (t: T) => void): void;
    thenUnion(cb: (t: T | U) => void): this;
}

interface DoNothingAlias<T, U> extends MyPromise<T, U> { }

declare function shouldBeIdentity<T, U>(p: DoNothingAlias<T, U>): MyPromise<T, U>;

declare const p1: MyPromise<boolean, any>;
const p2 = shouldBeIdentity(p1);
p2.then(b => {
    const s: string = b; //should fail!
});
```

`p2` should be the same type as `p1`, but it's a `MyPromise<any, any>` instead.

**Comment by RyanCavanaugh** [comment]
Confirmed regression 2.7 -> 2.8. Worked in all prior releases

**Comment by sandersn** [comment]
Specifically, here is the breaking change, added at the very top of inferFromTypes.

```ts
if (source.flags & TypeFlags.Any) {
    // We are inferring from an 'any' type. We want to infer this type for every type parameter
    // referenced in the target type, so we record it as the propagation type and infer from the
    // target to itself. Then, as we find candidates we substitute the propagation type.
    const savePropagationType = propagationType;
    propagationType = source;
    inferFromTypes(target, target);
    propagationType = savePropagationType;
    return;
}
```

This propagationType is then used in place of the current source when it is available. This adds 'any' for all type parameter found in the structure of the target type.

**Comment by andy-ms** [comment]
For `declare const p1: MyPromise<boolean, number>;` I would expect `p2` to have the same type, but get `MyPromise<boolean, {}>` instead.
