### ISSUE TITLE
Un-necessary compile warning: TS2448, TS2454

### ISSUE THREAD

**Issue by Javascript-Ninja** [Microsoft/TypeScript#22370]
**TypeScript Version:**  2.7.2

**Search Terms:** TS2448, TS2454

**Code**

```ts
const route: {} = {
  path: 'string',
  childRoute: route, // <-- error here
};

```

**tsconfig.json:**
```json
{
  "compilerOptions": {
    "strict": true,
  }
}
```

**Expected behavior:**
assign `route` to `childRoute` and without errors.

**Actual behavior:**
error TS2448: Block-scoped variable 'childRoute' used before its declaration.
error TS2454: Variable 'childRoute' is used before being assigned.

**Playground Link:** [url](https://www.typescriptlang.org/play/#src=const%20route%3A%20%7B%7D%20%3D%20%7B%0D%0A%20%20path%3A%20'string'%2C%0D%0A%20%20childRoute%3A%20route%2C%0D%0A%7D%3B%0D%0A)

**Comment by DanielRosenwasser** [comment]
What is the compelling reason to write that code? `childRoute` is going to be `undefined`.

**Comment by DanielRosenwasser** [comment]
Actually, that's just a runtime error in ES2015 because `route` will be in a temporal dead zone.

**Comment by Javascript-Ninja** [comment]
This is the [use case](https://github.com/Javascript-Ninja/react-router-prop-types/blob/v1.0.0/src/index.ts#L46).

Thanks for the explanation! It's really a runtime error.
