### ISSUE TITLE
Add glob support in baseUrl for mono repos

### ISSUE THREAD

**Issue by foisonocean** [Microsoft/TypeScript#22371]
Is it possible to use glob in baseUrl? It's very convenient for mono repos.

**Comment by DanielRosenwasser** [comment]
It sounds like you want to

* inherit `paths` from a root `tsconfig.json` using the `extends` functionality.
* have the same textual `baseUrl` (e.g. `"./"`), but have it resolved relative to the current `tsconfig.json`.

Can you confirm that's the scenario you have in mind?

**Comment by foisonocean** [comment]
@DanielRosenwasser 
My project structure is like this:

```
|-- packages
    |-- a
        |-- tsconfig.json
    |-- b
        |-- tsconfig.json
    |-- c
        |-- tsconfig.json
```

And each tsconfig.json now have the same baseUrl: `./src`.
Because those tsconfig.json are exactly the same, now I want to only maintain one tsconfig.json in the root of the project like this:
```
|-- packages
    |-- a
    |-- b
    |-- c
|-- tsconfig.json
```
So I hope the baseUrl could accept a glob like this: `packages/*/src`.

**Comment by mhegazy** [comment]
Do not think globs is the right thing to do here. you can just set the baseUrl to `./`, then add Path mapping for the packages:

```ts
{
    "baseUrl": "./packages"
    "paths": {
        "a/*": ["a/src/*"],
        "b/*": ["b/src/*"],
        "c/*": ["c/src/*"]
    }
}
```
