### ISSUE TITLE
Strict mode - "Cannot invoke an object which is possibly 'undefined'" even if tested

### ISSUE THREAD

**Issue by arthurwhite** [Microsoft/TypeScript#22385]
**TypeScript version:** 
2.7.2

**Code** ([playground link](http://www.typescriptlang.org/play/#src=interface%20IWithOptionalMethod%20%7B%0D%0A%20%20%20%20om%3F()%3A%20any%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20IFoobar%20%7B%0D%0A%20%20%20%20bar%3A%20%7B%20%5Bindex%3A%20string%5D%3A%20IWithOptionalMethod%20%7D%3B%0D%0A%7D%0D%0A%0D%0Aconst%20foo%3A%20IFoobar%20%3D%20%7B%0D%0A%20%20%20%20bar%3A%20%7B%7D%2C%0D%0A%7D%3B%0D%0A%0D%0A%2F%2F%20FAILS%0D%0AObject.keys(foo.bar).forEach((key)%20%3D%3E%20%7B%0D%0A%20%20%20%20if%20(foo.bar%5Bkey%5D.om)%20%7B%0D%0A%20%20%20%20%20%20%20%20foo.bar%5Bkey%5D.om()%3B%20%2F%2F%20Cannot%20invoke%20an%20object%20which%20is%20possibly%20'undefined'.%0D%0A%20%20%20%20%7D%0D%0A%7D)%3B%0D%0A%0D%0A%2F%2F%20WORKS%0D%0AObject.keys(foo.bar).forEach((key)%20%3D%3E%20%7B%0D%0A%20%20%20%20let%20x%20%3D%20foo.bar%5Bkey%5D.om%3B%0D%0A%20%20%20%20if%20(x)%20%7B%0D%0A%20%20%20%20%20%20%20%20x()%3B%20%2F%2F%20OK%0D%0A%20%20%20%20%7D%0D%0A%7D)%3B%0D%0A), use *strictNullChecks*)**:**

```ts
interface IWithOptionalMethod {
    om?(): any;
}

interface IFoobar {
    bar: { [index: string]: IWithOptionalMethod };
}

const foo: IFoobar = {
    bar: {},
};

// FAILS
Object.keys(foo.bar).forEach((key) => {
    if (foo.bar[key].om) {
        foo.bar[key].om(); // Cannot invoke an object which is possibly 'undefined'.
    }
});

// WORKS
Object.keys(foo.bar).forEach((key) => {
    let x = foo.bar[key].om;
    if (x) {
        x(); // OK
    }
});

```

**Expected behavior:**
No warning: `foo.bar[key].om`is tested and cannot be `undefined` (unless I missed something).

**Actual behavior:**
Warning: `Cannot invoke an object which is possibly 'undefined'.`

**Comment by RyanCavanaugh** [comment]
Duplicate #10530
