### ISSUE TITLE
negated types via Not operator based on conditional types

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#22382]
there is no clear answer as to what extent the conditional types can be used to for modeling negated types,

- from what i [know](https://github.com/Microsoft/TypeScript/pull/22323#issuecomment-370897477) Not can be just something that flips the `extends` constraint: 
```
type Not<T, U> = T extends U ? never : T;
```

- it's not as clear when it comes to a complementary type to the given one `Not<U>` like in https://github.com/Microsoft/TypeScript/issues/22375

so can negated types (as described above) be modeled with conditional types or it takes some additional machinery?

**Comment by jack-williams** [comment]
By 'complementary type' do you mean something like: `Complement<T>` that returns the type of all values not in `T`?

**Comment by aleksey-bykov** [comment]
if you look at `Complement<T>` just as like a negated expression of T (not yet evaulated!) it would be much easier to wrap your head around it

**Comment by mhegazy** [comment]
I think some of the scenarios that would need negated types should be now possible with conditional types.. but it does not address all of them.. negated types is still a feature on its own that is not supported today, specially when it comes to reasoning about infinite sets, like `number - 0` and how that relates to narrowing.
Some of the things you can do today are adding constraints on type parameters to ensure they are not a specific type like #22375, or using intersection types e.g.:

```ts
type NotPromise<T> = T extends Promise<any> ? never : T;
function f<T>(a: ()=> T & NotPromise<T>) { }

f(() => { }); // OK
f(async () => { }); // Error
```

**Comment by DanielRosenwasser** [comment]
@aleksey-bykov, do you want me to mark this issue as a suggestion for negated types?

**Comment by aleksey-bykov** [comment]
closing in favor of any of the following:

- negated types #4196
- allow negated types + F-bounded mapped type #18280
- negating type constraints #7993
