### ISSUE TITLE
Incorrect "Salsa" intellisense snippet within TSX files

### ISSUE THREAD

**Issue by bladedeyna** [Microsoft/TypeScript#22402]
Apologies if this is the wrong area, I believe this bug relates to the new JavaScript "Salsa" Language Service that provides intellisense hints.
[ScreenCapture_08-03-2018 12.12.40.zip](https://github.com/Microsoft/TypeScript/files/1793106/ScreenCapture_08-03-2018.12.12.40.zip)

**TypeScript Version:**  2.5.3
**Visual Studio Version:** 2017 15.6.0

**Search Terms:** salsa, typescript, intellisense, console.log, cl

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**Expected behavior:**

- Open new tsx file in Visual Studio 2017 15.6.0
- Type a "div" element
- Type an attribute such as "classname" by typing "cl" and then pressing tab on the intellisense with "classname" highlighted
- classname is entered as the attribute

**Actual behavior:**
- console.log(); is entered instead

**Playground Link:**  

**Related Issues:**

**Comment by mhegazy** [comment]
We should not be showing snippits in jsx elements.

@amcasey another one like https://github.com/Microsoft/TypeScript/pull/22394.

**Comment by amcasey** [comment]
Snippets should only be inserted on the second tab.  We had a bug a while back that caused them to be inserted on the first tab.  If that's what you're seeing, you should update to a newer version of VS (the TS version shouldn't matter).

Having said that, double-tab after `cl` will expand the snippet, regardless of whether or not it appeared in the completion list.  It looks like we may have prevented that from happening from comments, but I'm not sure whether that took effect in 15.7 or in a preview of 15.8.

**Comment by amcasey** [comment]
Okay, looks like I disabled that effect in comments for 15.8.  I can try to cover TSX as well, but it would be a new server command and I'm not how worried we are about people accidentally double-tabbing in TSX tags.

Again, firing on single tab was a huge problem and has been fixed.

**Comment by amcasey** [comment]
@mhegazy bar check?

**Comment by bladedeyna** [comment]
Updating to 15.7 resolves this for me. Thanks very much for looking into this.

**Comment by amcasey** [comment]
Excellent!

**Comment by amcasey** [comment]
@mhegazy We'll leave the double-tab issue for another day?

**Comment by mhegazy** [comment]
i think so.. unless you have a solution in mind..

**Comment by amcasey** [comment]
One solution would be to add an is-in-jsx tag command.  I'm not sure how much value that would add.
