### ISSUE TITLE
[API] Add type to 'OutliningSpan' class

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#22419]
From https://github.com/Microsoft/vscode/issues/20802

**Search Terms:** 
- code folding
- outliningspans

**Problem**
Allow users to fold / hide blocks of imports such as :

```js
import {} from 'a';
import {} from 'b';
import {} from 'c';
```

**Proposal**
Add import blocks to the outliningSpans introduced in #22400. 

We should also consider marking import block spans in some way. This could be something like:

```js
interface OutliningSpan {
    ...

    type: 'import' | 'code'
}
```

Here's the vscode proposed folding API: https://github.com/Microsoft/vscode/blob/0c8e31f14a2c1d4c0c7ea75573caab39b171384b/src/vs/vscode.proposed.d.ts#L10

/cc @aeschli

**Comment by mjbvz** [comment]
Making this issue more generic to track adding a type to the `OutlingSpans` object. Proposed set of OutliningSpans types:

- `'import'` 
- `'comment'` - https://github.com/Microsoft/TypeScript/issues/22932
- `'region'` - https://github.com/Microsoft/vscode/issues/44530
- `'code'`

**Comment by mhegazy** [comment]
@mjbvz fix should be in the nightly tomorrow, and in the next insiders.
