### ISSUE TITLE
No excess property error for computed property

### ISSUE THREAD

**Issue by Mitko-Kerezov** [Microsoft/TypeScript#22427]
**TypeScript Version:**  2.8.0-dev.20180308

**Search Terms:** Interface, known property

**Code**

```ts
interface IDictionary<T> {
	[key: string]: T
}
interface ITestInterface {
	booleanMap?: IDictionary<boolean>;
	otherProperty: number;
}

const someArg: string = "testString";
const textObject: ITestInterface = {
	[someArg]: true,
	otherProperty: 5
}
```

**Expected behavior:**
An error because `ITestInterface` does not include a definition for `[key: string]: boolean`. A correct object implementing `ITestInterface` would be:
```ts
const textObject: ITestInterface = {
	booleanMap: {
		[someArg]: true
	},
	otherProperty: 5
}
```

I expected some sort of:
`error TS2322: Type '{ [someArg]: boolean; otherProperty: number; }' is not assignable to type 'ITestInterface'.
  Object literal may only specify known properties, and '[someArg]' does not exist in type 'ITestInterface'.`
error 
**Actual behavior:**
Transpiled successfully - no errors.

**Playground Link:** [Here](https://www.typescriptlang.org/play/#src=interface%20IDictionary%3CT%3E%20%7B%0D%0A%09%5Bkey%3A%20string%5D%3A%20T%0D%0A%7D%0D%0Ainterface%20ITestInterface%20%7B%0D%0A%09booleanMap%3F%3A%20IDictionary%3Cboolean%3E%3B%0D%0A%09otherProperty%3A%20number%3B%0D%0A%7D%0D%0A%0D%0Aconst%20someArg%3A%20string%20%3D%20%22testString%22%3B%0D%0Aconst%20textObject%3A%20ITestInterface%20%3D%20%7B%0D%0A%09%5BsomeArg%5D%3A%20true%2C%0D%0A%09otherProperty%3A%205%0D%0A%7D)

**Related Issues:** I'm not sure about any related issues

**Comment by mhegazy** [comment]
Should be working in latest.
