### ISSUE TITLE
Typo in emitDeclarationError for declarations

### ISSUE THREAD

**Issue by obany** [Microsoft/TypeScript#22425]
**TypeScript Version:**  2.7.2

**Search Terms:** emitDeclarationOnly

**Code**

https://github.com/Microsoft/TypeScript/blob/fa4619c5c17a6a592245069f416b91e2ea40c36d/src/compiler/program.ts#L2202-L2205

```ts
error TS5052: Option 'emitDeclarationOnly' cannot be specified without specifying option 'declarations'.
```

**Expected behavior:**
Should say
error TS5052: Option 'emitDeclarationOnly' cannot be specified without specifying option 'declaration'.

**Actual behavior:**
Says 'declarations'

**Comment by DanielRosenwasser** [comment]
We'd take a PR! Should be a matter of changing `diagnosticMessages.json`, updating the references, running the tests, and updating our test baselines' output (if we had any tests for this).

**Comment by obany** [comment]
PR Submitted https://github.com/Microsoft/TypeScript/pull/22444
