### ISSUE TITLE
Type like this not assignable to this type.

### ISSUE THREAD

**Issue by Griffork** [Microsoft/TypeScript#22426]
**TypeScript Version:**
Version 2.8.0-dev.20180302

**Search Terms:** 
type, this

**Simplest Code**

```ts
class Thing<T> {
    doot: this;
    dothing(newthing: Thing<T>) {
        this.doot = newthing;
    }
}
```

**Expected behavior:**
No error
**Actual behavior:**
Error Type 'Thing<T>' is not assignable to type 'this'.

**Note**
Since there is no 'typeof this' operator that I can use, I need to use this to represent types that have the same type as this.

[**Playground Link** ](https://www.typescriptlang.org/play/#src=%0D%0Aclass%20Thing%3CT%3E%20%7B%0D%0A%20%20%20%20doot%3A%20this%3B%0D%0A%20%20%20%20dothing(newthing%3A%20Thing%3CT%3E)%20%7B%0D%0A%20%20%20%20%20%20%20%20this.doot%20%3D%20newthing%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A)

[**Slimmed down real world example**](https://www.typescriptlang.org/play/#src=%0D%0Aexport%20class%20Leaf%3CValueType%2C%20ParentType%3E%20%7B%0D%0A%20%20%20%20Parent%3A%20ParentType%3B%0D%0A%20%20%20%20constructor(Parent%3A%20ParentType)%20%7B%0D%0A%20%20%20%20%20%20%20%20this.Parent%20%3D%20Parent%3B%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20up()%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20this.Parent%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aexport%20class%20Branch%3CObjectType%2C%20ParentType%3E%20%7B%0D%0A%20%20%20%20branches%3A%20any%3B%0D%0A%20%20%20%20Parent%3A%20ParentType%3B%0D%0A%0D%0A%20%20%20%20constructor(Parent%3A%20ParentType)%20%7B%0D%0A%20%20%20%20%20%20%20%20this.Parent%20%3D%20Parent%3B%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20setBranches(...args%3A%20(Branch%3Cany%2C%20this%3E%20%7C%20this%20%7C%20Leaf%3Cany%2C%20this%3E%20%7C%20Leaf%3Cany%2C%20ParentType%3E)%5B%5D)%20%7B%0D%0A%20%20%20%20%20%20%20%20this.branches.%24and%20%3D%20args%3B%0D%0A%20%20%20%20%20%20%20%20return%20this%3B%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20newBranch%3CK%20extends%20keyof%20ObjectType%3E(param%3A%20K)%20%7B%0D%0A%20%20%20%20%20%20%20%20var%20NewQuery%20%3D%20new%20Branch%3CObjectType%5BK%5D%2C%20this%3E(this)%3B%0D%0A%20%20%20%20%20%20%20%20this.branches%5Bparam%5D%20%3D%20NewQuery%3B%0D%0A%20%20%20%20%20%20%20%20return%20NewQuery%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%7D%0D%0A%0D%0A%0D%0A%2F%2FTODO%3A%20Figure%20out%20more%20descriptive%20names%20for%20the%20following%20intermediary%20types.%0D%0Atype%20ChildBranch%3CObjectType%3E%20%3D%20Branch%3CObjectType%2C%20Branch%3CObjectType%2C%20Trunk%3CObjectType%3E%3E%3E%3B%0D%0Atype%20ChildLeaf%3CObjectType%3E%20%3D%20Leaf%3Cany%2C%20Branch%3CObjectType%2C%20Trunk%3CObjectType%3E%3E%3E%3B%0D%0A%0D%0Aexport%20class%20Trunk%3CObjectType%3E%20%7B%0D%0A%20%20%20%20%2F%2FSub%20is%20our%20own%20operator%20for%20subobjects.%0D%0A%20%20%20%20trunk%3A%20Branch%3CObjectType%2C%20this%3E%20%3D%20new%20Branch%3CObjectType%2C%20this%3E(this)%3B%0D%0A%0D%0A%20%20%20%20setBranches(...args%3A%20(ChildBranch%3CObjectType%3E%20%7C%20ChildLeaf%3CObjectType%3E)%5B%5D)%20%7B%0D%0A%20%20%20%20%20%20%20%20var%20NewQuery%20%3D%20new%20Branch%3CObjectType%2C%20Branch%3CObjectType%2C%20this%3E%3E(this.trunk)%3B%0D%0A%20%20%20%20%20%20%20%20NewQuery.setBranches(...args)%3B%0D%0A%20%20%20%20%20%20%20%20return%20NewQuery%3B%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20newBranch%3CK%20extends%20keyof%20ObjectType%3E(param%3A%20K)%3A%20Branch%3CObjectType%5BK%5D%2C%20Branch%3CObjectType%2C%20this%3E%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20this.trunk.newBranch(param)%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Ainterface%20Test%20%7B%0D%0A%20%20%20%20a%3A%20number%3B%0D%0A%20%20%20%20b%3A%20string%3B%0D%0A%20%20%20%20c%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20d%3A%20number%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0A%0D%0Avar%20a%20%3D%20new%20Trunk%3CTest%3E()%3B%0D%0Avar%20b%20%3D%20a.trunk%3B%0D%0Avar%20c%20%3D%20a.setBranches(a.newBranch(%22c%22))%3B)

**Related Issues:**
[8164](https://github.com/Microsoft/TypeScript/issues/8164)

**Comment by andy-ms** [comment]
You just need to consistently use `this` in both places.
```ts
doot: this;
dothing(newthing: this) {
    this.doot = newthing;
}
```

The requirement is to prevent `this.doot` from referring to a `Thing` even when we're in a subclass and `this` should refer to the subclass.
```ts
class Thing {
    doot!: this;
    dothing(newthing: this) {
        this.doot = newthing as any; // There's a reason the cast is needed!
    }
}

class SubThing extends Thing {
    constructor(readonly foot: number) {};
}

const s = new SubThing();
s.dothing(new Thing());
console.log(typeof s.doot.foot === "number"); // Expected this to always be true!
```
