### ISSUE TITLE
Could not file 'should_not_exist.file' TS 2.7.2

### ISSUE THREAD

**Issue by marcomura** [Microsoft/TypeScript#22429]
I'm experiencing the same issue reported in this thread:
[https://github.com/Microsoft/TypeScript/issues/21670](https://github.com/Microsoft/TypeScript/issues/21670)

_D:\cxtcache\Microsoft.TypeScript.MSBuild.2.7.2\build\\..\tools\tsc\tsc.exe (TaskId:24)
Done executing task "VsTsc". (TaskId:24)
Added Item(s): GeneratedJavascript=should_not_exist.file
Done building target "PreComputeCompileTypeScript" in project "mapssdk.csproj".: (TargetId:40)
Target "PreComputeCompileTypeScriptWithTSConfig" skipped, due to false condition; ('@(ConfigFiles)' != '' AND '$(DesignTimeBuild)' != 'true') was evaluated as ('' != '' AND '' != 'true')._

It seems it's not fixed correctly in TS 2.7.2.

**Comment by marcomura** [comment]
Log sent :) thanks

**Comment by uniqueiniquity** [comment]
This is due to custom usage of the "GeneratedJavascript" item list. I don't recommend adding your own files to that.
