### ISSUE TITLE
Request:  Support Closure-style module syntax

### ISSUE THREAD

**Issue by zzo** [Microsoft/TypeScript#2244]
In addition to 'commonjs' and 'requirejs'-style module output styles please also support Closure library-style module syntax during transpilation.

http://docs.closure-library.googlecode.com/git/namespace_goog_module.html
https://plus.sandbox.google.com/+JohnLenzGoogle/posts/gZ7w2w5HQDk
https://docs.google.com/document/d/1SwVn2ajodVsAauhJoHOyQgr87bMzaK13ke2CpGorbUY/edit

**Comment by NoelAbrahams** [comment]
This has also been discussed in the context of minification  #8

**Comment by mhegazy** [comment]
looks like https://github.com/angular/sickle should do the trick.

**Comment by mhegazy** [comment]
Closure has more to it than the module system, e.g. property declarations, type annotations, casting, etc.. Closure is supporting ES6 modules, so invoking the TS compiler with --target ES6, along with a tool like [sickle](https://github.com/angular/sickle) should be the solution.
