### ISSUE TITLE
Javascript should allow you to extend any

### ISSUE THREAD

**Issue by sandersn** [Microsoft/TypeScript#22443]
```ts
// @noEmit: true
// @allowJs: true
// @checkJs: true
// @Filename: defaults.js
/** @type {any} */
var X
class Y extends X {
    constructor() {
        super()
    }
}
```

**Expected behavior:**
No error, or at least an error on X "Can't extend value of type any".

**Actual behavior:**
Error on `super()`, "Call target does not contain any signatures."

There are lots of anys floating around Javascript, so this should be allowed, even if it's not trivial. Maybe it should be allowed in Typescript too.

**Comment by mhegazy** [comment]
Related to https://github.com/Microsoft/TypeScript/issues/17032

**Comment by sandersn** [comment]
Affects webpack [in @mohsen1's addition of ts-check](https://github.com/mohsen1/webpack/tree/bd1c827c884d943f68bbbf00cd91003875ae0bb2).
