### ISSUE TITLE
Nightly builds not published to npm (starting 3/8/2017)

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#22455]
For any others who may file this, we're aware of the issue and will have it back up by next week. Thanks!

**Comment by sheetalkamat** [comment]
Merged PR #22450 and the failures were not reproed since then.

**Comment by weswigham** [comment]
@sheetalkamat I'm still seeing failures related to `watchDirectories` that are only repro'ing on the internal CI server? (But they do reliably repro there)
![image](https://user-images.githubusercontent.com/2932786/37371676-5e5fc936-26cd-11e8-937c-6c19255537ff.png)

**Comment by sheetalkamat** [comment]
verified that #22526 fixes this on CI server as well.
