### ISSUE TITLE
HTMLInputElement::files should not be a read-only property

### ISSUE THREAD

**Issue by sheley1998** [Microsoft/TypeScript#22463]
**TypeScript Version:**  2.7.1

**Search Terms:** 
HTMLInputElement

**Code**

```ts
const test = document.createElement('input');
test.type = 'file';
document.body.appendChild(test);

const test2 = document.createElement('input');
test2.type = 'file';
document.body.appendChild(test2);

test.addEventListener('change', ()=>{
    test2.files = test.files;
    console.log(test2.files);
});
```

**Expected behavior:**
above code should compile without error

**Actual behavior:**
error is thrown at "test2.files = test.files" because Typescript treats files as a read-only property.

**Playground Link:**  

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
Recent change; see https://github.com/whatwg/html/pull/2866

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.
