### ISSUE TITLE
DOMTokenList missing replace() function

### ISSUE THREAD

**Issue by lenovouser** [Microsoft/TypeScript#22466]
- [WHATWG](https://dom.spec.whatwg.org/#dom-domtokenlist-replace)
- [MDN](https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList/replace)

https://github.com/Microsoft/TypeScript/blob/be1c11581e43098bcb6747af50f43b39c762be39/src/lib/dom.generated.d.ts#L3282-L3291

**Code**

```ts
const span    = document.querySelector("span");
const classes = span.classList;

try {
    classes.replace("orange", "apple");
    span.textContent = classes.toString();
} catch(e) {
    span.textContent = e;
}
```

**Playground Link:** [typescriptlang.org/play](https://www.typescriptlang.org/play/index.html#src=const%20span%20%20%20%20%3D%20document.querySelector(%22span%22)%3B%0D%0Aconst%20classes%20%3D%20span.classList%3B%0D%0A%0D%0Atry%20%7B%0D%0A%20%20%20%20classes.replace(%22orange%22%2C%20%22apple%22)%3B%0D%0A%20%20%20%20span.textContent%20%3D%20classes.toString()%3B%0D%0A%7D%20catch(e)%20%7B%0D%0A%20%20%20%20span.textContent%20%3D%20e%3B%0D%0A%7D%0D%0A)

**Comment by bcherny** [comment]
@lenovouser This seems like an easy fix - can you just add it to https://github.com/Microsoft/TypeScript/blob/be1c11581e43098bcb6747af50f43b39c762be39/lib/lib.dom.d.ts#L3495 ?

**Comment by lenovouser** [comment]
@bcherny ah okay, thought the lib*.d.ts files were still generated from the Edge sources. Will do! 👍

**Comment by bcherny** [comment]
@lenovouser What "edge sources"? My suggestion might be wrong - I assumed they're hand-written.

**Comment by lenovouser** [comment]
@bcherny no you're right. Last time I checked the `lib.dom.d.ts` files were still generated from the Edge sources here [github.com/microsoft/ts-lib-generator](https://github.com/Microsoft/TSJS-lib-generator) but it seems like they now have two files, one `lib.dom.d.ts` and `dom.generated.d.ts`
