### ISSUE TITLE
Initializing `let` variables and exhaustiveness checking

### ISSUE THREAD

**Issue by rauschma** [Microsoft/TypeScript#22470]
```
let tagName;
switch (kind) {
  case ListKind.Ordered:
    tagName = 'ol';
    break;
  case ListKind.Unordered:
    tagName = 'ul';
    break;
  default:
    assertNever(kind);
}
```

* The inferred type of `tagName` is `string|undefined`, but should be `string`, AFAICT.
* Similarly: If I give `tagName` the type `string`, I get the error: “Variable 'tagName' is used before being assigned”.

**Comment by ajafff** [comment]
Control flow analysis does not know that `assertNever` never returns. You need to `return` or `throw assertNever(kind);` to end the control flow.

**Comment by rauschma** [comment]
That makes sense! Thanks!
