### ISSUE TITLE
Support import?

### ISSUE THREAD

**Issue by rentalhost** [Microsoft/TypeScript#2247]
I'm new on TypeScript, so sorry if it no make sense. But I like to know if to I import first I really need use the "reference" tag. If yes, why not have only a "import" or similar to do same, as a shortcut?

    import "myfile.ts";
    class Animal { ... }

Or:

    include "myfile.ts";

Or even omitting ".ts":

    import myfile;
    import path.to.myfile;
    import path with space.myfile; // or "path with space".myfile; or "path with space.myfile";

**Comment by mhegazy** [comment]
Are your using a module loader (e.g AMD or commonjs if you are writing a node app)? or will you be including this file as a script in your html?

**Comment by danquirk** [comment]
This page hopefully will make it somewhat clearer: https://github.com/Microsoft/TypeScript/wiki/Modules

We need to update it for ES6 style modules but they're roughly the same as external modules and distinct from internal modules in the same ways.
