### ISSUE TITLE
How to dynamically import componenents dynamically using import statements 

### ISSUE THREAD

**Issue by vittal288** [Microsoft/TypeScript#22482]
I have to load a component which has the same name called "MyComponent" but located in different folders physically(and the name of the component is "MyComponent) which has different behavior in each folder) and MyComponent component has to load based on the options which user selects in his previous screens ....

Suppose MyComponent is located in following folders 

OPTION ONE 

`..path1/path2/path3/my-component/my-component.component  `  and this component have to refer to my routing module import statement as shown below and path1,path2, and path2 are some dynamic values which user will select in his previous screens.

`import {MyComponent } from "..path1/path2/path3/my-component/my-component.component" `

NOTE: I am keeping the options which user select in his configuration screens as the same name to the folder name to ease my import statements.

OPTION TWO 

`..path4/path5/path6/my-component/my-component.component  `  and this component have to refer to my routing module import statement as shown below and path4,path5, and path6 are some dynamic values which user will select in his previous screens.

and import statement will look like below 

`import {MyComponent } from "..path4/path5/path5/my-component/my-component.component"`

since MyComponent is referred in my declaration array of RoutinModule but if you import above two components in one short compiler will throw an error that MyComponent is already imported,  so I have to import those import statement very dynamically based on user's selections.

Hope you understand my problem statement ...

Let me summarise the issue below like, I have to generate import statement dynamically ....

**Comment by andy-ms** [comment]
Importing dynamically can be tricky -- if performance is not a concern you could import both components up front and choose one later?
```ts
import { MyComponent as MyComponentA } from "./a";
import { MyComponent as MyComponentB } from "./b";
...
const MyComponent = condition ? MyComponentA : MyComponentB;
```
