### ISSUE TITLE
Infer that one value must be defined

### ISSUE THREAD

**Issue by jakearchibald** [Microsoft/TypeScript#22483]
Really sorry if this is a dupe. I tried looking, but couldn't find anything.

```ts
interface Blah { x: number; }

function demo(a?: Blah, b?: Blah): Blah {
    if (!a && !b) throw Error('One must be provided');
    return a || b;
}
```

The above fails with "Type 'Blah | undefined' is not assignable to type 'Blah'", but one of `a` or `b` must be defined at this point. Should this be inferred?

**Comment by jakearchibald** [comment]
REPL demo https://goo.gl/mTgDL1

**Comment by andy-ms** [comment]
I don't think there is any logic to handle multiple variables at once -- only one at a time. The else branch of `!a && !b` doesn't tell us anything about `a` alone, or `b` alone, so it doesn't narrow the type of either variable.
The code will compile if you use a single variable:
```ts
const res = a || b;
if (!res) throw Error('One must be provided');
return res;
```

**Comment by jakearchibald** [comment]
Ahh yes, that works, thank you!

Feel free to close, unless you think Typescript should have been able to track this.
