### ISSUE TITLE
Mapped types enumerating keys in `string` behave poorly

### ISSUE THREAD

**Issue by bterlson** [microsoft/TypeScript#22509]
**TypeScript Version:**  2.8.0-dev20180308
**Search Terms:** mapped types
**Code**

```ts
type Thing = {
    [K in string]: K
};

var thing: Thing = new Proxy({}, {
    get(_, k) {
        return k;
    }
});

let res = thing.x; // res should be of type 'x', but is string
```
[Playground Link](http://www.typescriptlang.org/play/index.html#src=type%20Thing%20%3D%20%7B%0D%0A%20%20%20%20%5BK%20in%20string%5D%3A%20K%0D%0A%7D%3B%0D%0A%0D%0Avar%20thing%3A%20Thing%20%3D%20new%20Proxy(%7B%7D%2C%20%7B%0D%0A%20%20%20%20get(_%2C%20k)%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20k%3B%0D%0A%20%20%20%20%7D%0D%0A%7D)%3B%0D%0A%0D%0Alet%20res%20%3D%20thing.x%3B%20%2F%2F%20res%20should%20be%20of%20type%20'x'%2C%20but%20is%20string)

Here I expect `string` to behave as if it were the union of all possible string literal types. The present semantics are identical to a string indexer. IMO if we don't want map types `K in string` to do anything interesting, then the syntax should be an error and we should require people to write the indexer. 

For what it's worth, ultimately I would love to type Allen's Apparatus for Method Extraction, roughly typed below:

```ts
type ExtractorThing = {
    [K in string]: <T>(base: T) => K extends keyof T ? T[K] : never;
}

var extract: ExtractorThing = new Proxy({}, {
    get(target, prop) {
        "use strict";
        return (base: any) => function(this: any, ...args: any[]) {
          return base[prop].apply(this || base, args); 
        }
    }
});

let obj = {
    x: 0,
    succ() {
        return ++this.x;
    },
    dec() {
        return --this.x;
    }
}

let succ = extract.succ(obj);
let dec = extract.dec(obj);

succ(); // 1
succ(); // 2
dec(); // 1
dec(); // 0
```

I would probably work towards putting a constraint on T such that you get a red squiggle if you pass an object without the proper method to extract, but hopefully this serves as a useful example.

**Comment by RyanCavanaugh** [comment]
Ping @ahejlsberg

**Comment by jack-williams** [comment]
That would be very cool! I guess it would be kind of like specifying a parameterised getter? (If that were a thing).

```ts
interface Thing {
  get <K extends string>(): <T>(base: T) => K extends keyof T ? T[K] : never;
}

**Comment by DanielRosenwasser** [comment]
Sort of. It might mean that string index signatures would need to boil down to something similar to the following call signatures

```ts
<K extends string>(x: K): *Type*
<K extends string>(x: K, value: *Type*): void;
```

But then what about numeric index signatures? You'd need a way to encode number-like strings:

```ts
<K extends number | (numeric string)>(x: K): *Type*
<K extends number | (numeric string)>(x: K, value: *Type*): void;
```

**Comment by jack-williams** [comment]
@DanielRosenwasser Yes I guess you would want these to be equivalent:
```ts
interface Idx<T> {
    [x: string]: T;
}

interface GetterSetter<T> {
  get <K extends string>(): T
  set <K extends string>(v: T): void;
}
```
I'm afraid my understanding of numeric indexers probably has many holes. Am I correct in thinking that the stickiness with number-like strings mostly arises when you have named properties? E.g.
```ts
interface NumGetSet<T> {
  get <K extends number>(): T
  set <K extends number>(v: T): void;
  "10": T;
}
let x!: NumGetSet<string>
let y = x["10"]; // wont have type string.
```
If the named property doesn't exists, then the key "10" is not treated specially as a number? 

Although, I don't know if you want want to replace numeric indexers necessarily. Perhaps it could just be limited to types that extend `string`?

**Comment by ahejlsberg** [comment]
This really is a request to add compiler support for ECMAScript proxy objects, i.e. compiler knowledge of the relationship between property access operations and the `get` and `set` proxy methods. It is simply not possible to model that with our current type system features (because nothing allows you to capture the literal type corresponding to the property name in a property access). This new feature would likely also include support for mapping call operations onto the `apply` and `construct` methods.

I do think this is entirely orthogonal to mapped types, and I think the current behavior of mapping over type `string` is correct and consistent.

**Comment by bterlson** [comment]
@ahejlsberg I think proxies are a bit of a red herring here. For example, something like the following is fairly common I think?

```ts
{
  [K in string]?: K extends '_data' ? DataType : DefaultType
}
```

It's like a type with an index signature but special properties don't have to be assignable to the index type.

I agree what I'm asking for is useful for the get trap side of proxies. I believe exotic get behavior is more common than exotic call behavior so this may even be a reasonable starting point for "proxy support".

I think I contest consistent, but I admit this is based on a surface-level understanding. I'll try to illustrate. Given the type `{ [K in 'a' | 'b']: K }`, it has three important behaviors:

1. A property is created for each member of `in`'s RHS.
2. The type of that property corresponds to the property name
3. All properties are are required

However, `{ [K in string]: K }`, a very similar construct, seems to only exhibit the first behavior but not the second or third.

**Comment by RyanCavanaugh** [comment]
This doesn't seem to be a common request and I haven't seen other problems that would be solved by addressing this

**Comment by eggers** [comment]
I have a use case now where this would be a helpful feature:

```typescript
type Item<T extends string> = {
  id: T;
};

export type ItemMap = {
  [id in string]: Item<id>;
};
const map: ItemMap = {};

const item = map['someid']; // type is Item<string> when it would be nice to be Item<'someid'>
```

**Comment by tlrobinson** [comment]
I would like a solution to this as well. I'm specifically interested in typing a `Proxy` for use in a [tRPC](https://trpc.io/)-like library that requires accurate typing to share types in the server and client, but  @eggers has another good use case, and I don't think something special for `Proxy` is necessary.

Maybe this is a little contrived but you could assert an `id` field matches the key in the map:

```typescript
type IdMap<Keys extends string> = { [K in Keys]?: { id: K }}
```

```typescript
const map: IdMap<string> = {}

map.foo = { id: "foo" }
map.foo = { id: "bar" } // does NOT error as I believe it should
```

If you're enable to enumerate the keys (I'm not in my actual use case) this does work as expected:

```typescript
const map: IdMap<"foo"|"bar"> = {}

map.foo = { id: "foo" }
map.foo = { id: "bar" } // does error
```
