### ISSUE TITLE
[loc][Query][TypeScript] Localizability of"0; 0; "FormatCompletedBlockOnLeftCurlyBrace"

### ISSUE THREAD

**Issue by PDostalek** [Microsoft/TypeScript#22503]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.
Please re-assign back to use in case you are not the right contact person or you can´t assign to a proper person.
Can you help please? 
Thanks!

Source:
Format _opened block on {
--

File Name:
LanguageService\TypeScriptLanguageService\bin\Release\localize\ENU\Microsoft.CodeAnalysis.TypeScript.EditorFeatures.dll
--

Resource ID:
0; "FormatCompletedBlockOnLeftCurlyBrace"

Query:
Is this a code except?Should we keep it in English or is it translatable?

**Comment by amcasey** [comment]
@aozgaa, do you know how we've handled these in the past?  I remember you saying there were some localization wrinkles for new settings checkboxes.  In the absence of other information, I'd say it should be handled the same as `Format closed block on }`.

**Comment by amcasey** [comment]
i.e. `FormatCompletedBlockOnLeftCurlyBrace` should be handled in the same way as `FormatCompletedBlockOnRightCurlyBrace`.

**Comment by mhegazy** [comment]
@PDostalek does this address your question?
