### ISSUE TITLE
Conditional types cause failure of substitution property of definitions

### ISSUE THREAD

**Issue by jcreedcmu** [Microsoft/TypeScript#22518]
By 'substitution property' I mean in this case that if I define
```ts
type Foo<T> = Bar<T, T>;
```
then I expect the expressions that have the type `Foo<T>` to be the same as those that have type `Bar<T, T>`, for any `T`. If this property is a non-goal --- if its violation is an expected consequence of distributive conditional types --- then feel free to close this issue.

**TypeScript Version:**  2.8.0-dev commit 0c6ef348ce1

**Search Terms:** conditional types, substitution

**Code**

```ts
type MyTypes = {
  'text': string;
  'bool': boolean;
};

type Datum<K, V> = { t: K, v: V };
type FromKeys<T, U> = T extends keyof U ? Datum<T, U[T]> : never;
type UnionMaker2<T, U> = FromKeys<keyof T, U>;
type UnionMaker<T> = UnionMaker2<T, T>;

const x1: UnionMaker2<MyTypes, MyTypes> = {t: 'text', v: 'string'};
const x2: UnionMaker2<MyTypes, MyTypes> = {t: 'bool', v: true};
// fails:
// const x3: UnionMaker2<MyTypes, MyTypes> = {t: 'text', v: true};

// however this succeeds?
const x4: UnionMaker<MyTypes> = {t: 'text', v: true};
```

**Expected behavior:**
Both `x3` and `x4` should fail to typecheck. I expect both `UnionMaker<MyTypes>` and `UnionMaker2<MyTypes, MyTypes>` to be
```ts
{t: 'text', v: string} | {t: 'bool', v : boolean}
``` 
And most of all I expect `UnionMaker<MyTypes>` in any event to be identical in behavior to `UnionMaker2<MyTypes, MyTypes>`, because of the definition of `UnionMaker`.

**Actual behavior:**
`x3` if uncommented yields
```
../a.ts(17,7): error TS2322: Type '{ t: "text"; v: boolean; }' is not assignable to type 'Datum<"float", number> | Datum<"text", string> | Datum<"bool", boolean> | Datum<"price", number> ...'.
  Type '{ t: "text"; v: boolean; }' is not assignable to type 'Datum<"text", string>'.
    Types of property 'v' are incompatible.
      Type 'boolean' is not assignable to type 'string'.
5:54:33 PM - Compilation complete. Watching for file changes.
```
but `x4` typechecks without error.

**Related:**
Conditional types PR https://github.com/Microsoft/TypeScript/pull/21316
Stackoverflow question which prompted this observation: https://stackoverflow.com/questions/43197523/can-an-indexed-type-map-be-expanded-into-a-discriminated-union/49266392#49266392

**Comment by jcreedcmu** [comment]
I just found https://github.com/Microsoft/TypeScript/issues/22302 after searching recent git commit history for 'conditional', seeing if that's related...

**Comment by jcreedcmu** [comment]
After looking at it, I'm not convinced it is relevant, but perhaps someone who knows the implementation of conditional types better can correct me if it is.

**Comment by RyanCavanaugh** [comment]
With `typescript@next` I see the expected failure on `x3` and `x4` ?

**Comment by jcreedcmu** [comment]
Apologies, I can repro the expected failure now. I didn't realize that `TypeScript/bin/tsc` from a fresh clone of the repo was merely LKG and not the same as the result from building or npm-installing @next. Should have read the docs more carefully! :)

**Comment by RyanCavanaugh** [comment]
No worries - thanks for trying it out!

**Comment by jcreedcmu** [comment]
Reciprocal thanks to the whole ts team for all their work. I am super excited about conditional types; they seem like a very expressive feature in combination with the other type-level operations already present.
