### ISSUE TITLE
Suggestion: a new postfix type annotation

### ISSUE THREAD

**Issue by xp44mm** [Microsoft/TypeScript#22529]
The native javascript syntax have extensively used a lot of punctuation , colon `:` comma `,` and semicolon `;` . so if typescript used also them,  in destructuring data type, in object literal,  typescript will get confused very often. and hardly to transpile.
i suggest that use postfix new exclusive annotation `[<>]` replace colon `:`.  for example:
### list 1
**Actual behavior:**
```typescript
let { a, b }: { a: string, b: number } = o;
```
**Expected behavior:**
```typescript
let { a[<string>], b [<number >]}= o;

//rename
let { a: newName1[<string>], b: newName2[<number>] } = o;
```

### list 2
**Actual behavior:**
```typescript
let o = {a:(<number[]>[]),b:3,}
```
**Expected behavior:**
```typescript
let o = {a:[][<number[]>],b:3,}
```

**Comment by RyanCavanaugh** [comment]
I don't think we want to just add duplicative syntax - there should be ideally one way to write any given type declaration. "Using up" syntax also removes our future options if want to add additional features to the type system later (which is basically a given).
