### ISSUE TITLE
Support tagged templates in ES5 and ES3

### ISSUE THREAD

**Issue by Alxandr** [Microsoft/TypeScript#2253]
Tagged templates are fairly easy to implement using ES5 and ES3, you simply turn the following:

```javascript
fn`Hello ${you}! You're looking ${adjective} today!`
```

into the following:

```javascript
fn(["Hello ", "! You're looking ", " today!"], you, adjective);
```

(sample taken from http://updates.html5rocks.com/2015/01/ES6-Template-Strings)

**Comment by ivogabe** [comment]
That has already been implemented in #1589. Note that the first argument of the downlevel call should have a raw property. We ended up with the following code:
```typescript
(_a = ["Hello ", "! You're looking ", " today!"], _a.raw = ["Hello ", "! You're looking ", " today!"], fn(_a, you, adjective));
var _a;
```

**Comment by Alxandr** [comment]
Oh, damn, github search by default only searched open issues :-/.

Babel does more or less the same thing, except it uses a generated helper (and also does some `Object.freeze` if the browser supports it). I just tested this on the playground on the typescriptlang website, but I guess it hasn't been released yet.

**Comment by filipstachura** [comment]
Incoming in 1.5 :)

**Comment by Alxandr** [comment]
Great. Thanks. Sorry for duplicate issue :).

**Comment by DanielRosenwasser** [comment]
No worries - as a note, we thought about `Object.freeze` but I guess we were leaning towards the extremes of either doing it as correctly as possible (with making a cache of template strings arrays) or as cleanly as possible with ES3 compat (the way it is currently slated for 1.5). I think that the way @ivogabe did it is clean, canonical, and understandable.

Just for documentation, the duplicate issue is #1590.
