### ISSUE TITLE
Indicate explicit index signatures in completion service

### ISSUE THREAD

**Issue by dorba** [Microsoft/TypeScript#22530]
**TypeScript Version:**  2.7.2
**Search Terms:** completion, index signature

Consider the following interface declaration:

```
interface Example {
  [key: string]: any;
  knownValue: any;
}
```

Only `knownValue` is provided as a suggestion.

![suggestions](https://user-images.githubusercontent.com/735501/37379489-ad18f492-2701-11e8-9ce3-a67922f1703f.PNG)

As an end user of a library, it's not apparent that it is not an error to use any other identifier. It would be nice to provide some sort of suggestion indicating that there is an index signature, along with the return type of the index signature.

**Comment by DanielRosenwasser** [comment]
We have the concept of a "completion builder" item which can be shown to the user when a position is considered a "new identifier location".

**Comment by DanielRosenwasser** [comment]
@mjbvz @amcasey we should probably discuss the experience here.

**Comment by DanielRosenwasser** [comment]
The VS Code side will need an update to support this, but we can support it in VS.
