### ISSUE TITLE
why export function set interface is error

### ISSUE THREAD

**Issue by LLLLLamHo** [Microsoft/TypeScript#22567]
**TypeScript Version:**  2.7.5-dev.2018.3.14

**Search Terms:** 
interface
**Code**

```ts


var glob = require( "glob" );

interface ConfigData { 
    include: number[],
    exclude: number[]
}

function getIncludefiles ( config: ConfigData ): any {

    let { include, exclude }: { include: number[], exclude: number[] } = config;
    let includeCheckFiles: number[] = [];
    let excludeCheckFiles: number[] = [];

    // 包含文件
    if ( include && include.length != 0 ) {
        for ( let i = 0; i < include.length; i++ ) {
            let files: number[] = glob.sync( include[ i ], { cwd: process.cwd() } );
            includeCheckFiles = includeCheckFiles.concat( files );
        }
    }
    //排除文件
    if ( exclude && exclude.length != 0 ) {
        for ( let i = 0; i < exclude.length; i++ ) {
            let files: number[] = glob.sync( exclude[ i ], { cwd: process.cwd() } );
            excludeCheckFiles = excludeCheckFiles.concat( files );
        }
    }
    //最终需要检测的文件
    if ( excludeCheckFiles && excludeCheckFiles.length > 0 ) {
        for ( let i = 0; i < excludeCheckFiles.length; i++ ) {
            let index: number = includeCheckFiles.indexOf( excludeCheckFiles[ i ] );
            if ( index != -1 ) {
                includeCheckFiles.splice( index, 1 );
            }
        }
    }

    return includeCheckFiles;
}


export = getIncludefiles;
```

**Expected behavior:**

no error

**Actual behavior:**

error TS4078: Parameter 'config' of exported function has or is using private name 'ConfigData'.
How should I set it up?

**Comment by andy-ms** [comment]
First, if possible it would be better to use a default export over `export =` (`export default function getIncludefiles(..) { ... }`). Then you can add `export` in front of the interface (`export interface ConfigData { ... }`) and they can be imported separately with `import getIncludefiles, { ConfigData } from "./module-path";`.

If you really want an `export =` you have to put the type in a namespace merged with the function:
```ts
namespace getIncludefiles {
    export interface ConfigData {
        include: number[],
        exclude: number[]
    }
}

function getIncludefiles ( config: getIncludefiles.ConfigData ): any { ... }
export = getIncludefiles;
```
Or you could write the type inline: `config: { include: number[], exclude: number[] }`

**Comment by LLLLLamHo** [comment]
I did exactly what you said, but I didn't have any hints in the editor.

before:
![image](https://user-images.githubusercontent.com/19260349/37459841-4a67c042-2884-11e8-9e19-6661adf5e12a.png)
after:
![image](https://user-images.githubusercontent.com/19260349/37459774-1ae6c5ca-2884-11e8-95b5-a7f10ea93163.png)


Am I still doing something wrong?

**Comment by andy-ms** [comment]
Those are both valid hints -- neither is wrong.

**Comment by LLLLLamHo** [comment]
@andy-ms Thank you very much for your patience.
