### ISSUE TITLE
"protected" modifier behavior not corresponding it's documentation

### ISSUE THREAD

**Issue by FlamesoFF** [Microsoft/TypeScript#22568]
**TypeScript Version:**  2.7.2

**Code**
```ts
class One{
    protected clear(){}
}

const one = new One();
one.clear();
```

**Expected behavior:**
In accordance with documentation of TS: 
> The protected modifier acts much like the private modifier with the exception that members declared protected can also be accessed by **instances** of deriving classes.

And with OOP declaration of the **instance**:
> In object-oriented programming (OOP), an instance is a concrete occurrence of any object, existing usually during the runtime of a computer program. An instance is a specific object built from a specific class. It is assigned to a reference variable that is used to access all of the instance's properties and methods. When you make a new instance the process is called instantiation and is typically done using the **new** keyword.

Method `one.clear()` should be called without problems.

**Actual behavior:**
> Property 'clear' is protected and only accessible within class 'One' and its subclasses.

**Comment by andy-ms** [comment]
You're right, this is a documentation error. We should just say "can also be accessed in deriving classes." Could you link to the documentation?

**Comment by DanielRosenwasser** [comment]
Thanks!
