### ISSUE TITLE
Auto import path Capitalization wrong

### ISSUE THREAD

**Issue by ste2425** [Microsoft/TypeScript#22566]
**Search Terms:** 

**Code**
With a module located at the following location:

```
.\ClientApp\src\app\components\dialogs\message-dialog\message-dialog.component.ts
```

Type that module class name in another module and allow TS to auto import it. Either use the little light bulb drop down, or press ALT + . to get the list of options.

TS for some reason capitalizes the word `dialogs`, and only that word in the import path. Change even a single character in the actual folder name and it no longer capitalizes it. 

**Expected behavior:**
The module should be imported with the import path being correct to the actual path on disc.

**Actual behavior:**
The module is imported, however the import path has the folder `dialogs` capitalized, so `Dialogs`

See attached image.

**Playground Link:** N/A

**Related Issues:**

![image](https://user-images.githubusercontent.com/8177767/37397580-dc289798-2773-11e8-818b-6edd174853b3.png)

![image](https://user-images.githubusercontent.com/8177767/37397666-16e0641a-2774-11e8-82e7-f8560ef48ccb.png)

**Comment by andy-ms** [comment]
Is it possible that you wrote `Dialogs` with a capital `D` anywhere in your app? TypeScript may not use the "real" capitalization on disk, but the first capitalization it sees used. Assuming you're on a case-insensitive OS where those would be considered the same file.
