### ISSUE TITLE
Compiler changing type causing a bug?

### ISSUE THREAD

**Issue by ccorcos** [Microsoft/TypeScript#22579]
**TypeScript Version:**  2.7.2

I'm sorry about this, but I cannot minimally reproduce this bug in a playground, but I'm quite sure it is a bug so I'm going to submit it anyways. I just upgraded to typescript 2.7.2 and I'm having an issue where the compiler is changing the types on me and causing an error.

![screen shot 2018-03-14 at 11 07 52 am](https://user-images.githubusercontent.com/1794527/37423135-52e1dd3a-277a-11e8-9177-b57d1097f4eb.png)

![screen shot 2018-03-14 at 11 25 28 am](https://user-images.githubusercontent.com/1794527/37423182-70dffb8c-277a-11e8-818f-ecafed2816d6.png)

**Comment by ccorcos** [comment]
I'm getting closer.

I have this helper function that has stricter types around lodash.

```ts
import * as _ from "lodash"

export const compact = function<T>(
	list: Array<T | undefined | null>
): Array<T> {
	return _.compact(list) as Array<T>
}
```

In the below example, I can return insertBlocks, but we're compacting it (probably legacy reasons) and that's whats causing the error.

![screen shot 2018-03-14 at 11 51 54 am](https://user-images.githubusercontent.com/1794527/37424617-228ebd3e-277e-11e8-8cc7-117cfc9d1959.png)

![screen shot 2018-03-14 at 11 53 04 am](https://user-images.githubusercontent.com/1794527/37424705-6895f572-277e-11e8-9ec1-6d22d80a6fe0.png)

I've been trying to [reproduce in a playground](http://www.typescriptlang.org/play/#src=%0D%0Atype%20X%3CY%3E%20%3D%20%7B%20x%3A%20Y%20%7D%0D%0A%0D%0Alet%20a%3A%20Array%3CX%3Cnumber%3E%3E%20%3D%20%5B%5D%0D%0A%0D%0Aexport%20const%20compact%20%3D%20function%3CT%3E(list%3A%20Array%3CT%20%7C%20undefined%20%7C%20null%3E)%3A%20Array%3CT%3E%20%7B%0D%0A%09return%20list.filter(item%20%3D%3E%20item%20!%3D%3D%20undefined%20%26%26%20item%20!%3D%3D%20null)%20as%20Array%3CT%3E%0D%0A%7D%0D%0A%0D%0Afunction%20f()%20%7B%0D%0A%20%20%20%20return%20%5B%5D%20as%20Array%3CX%3Cnumber%3E%3E%0D%0A%7D%0D%0A%0D%0Afunction%20g()%3A%20Array%3CX%3Cnumber%3E%3E%20%7B%0D%0A%20%20%20%20return%20compact(f())%0D%0A%7D%0D%0A%0D%0Aconst%20b%20%3D%20g()%0D%0A%0D%0Aa%20%3D%20b) but I can't.

P.S. I'm using strict nullchecks.

**Comment by andy-ms** [comment]
In case services is being unreliable here, you might want to add explicit type annotations on the `const` declarations to see if you get compile errors there.

**Comment by ccorcos** [comment]
Adding annotations does fix this issue. And it turns out that the `compact` function is superfluous so I've fixed the problem and moved on. However, this does seem like a bug with Typescript.

**Comment by andy-ms** [comment]
Yeah, it's a bug if hover doesn't give you the same type that you get at compile time. It would be great if you could find a reproducible example -- presumably removing one of the type annotations will cause the error to surface again.

**Comment by ccorcos** [comment]
Yeah, I can't recreate it in a playground sadly.

**Comment by andy-ms** [comment]
Are you sure your editor is using the same TS version as your compiler?

**Comment by ccorcos** [comment]
Yep, I have the VSCode config that points to the node_modules typescript.
Also, the compiler throws and error as well when I build. It’s not a
consistency issue. Typescript actually thinks it’s an error...
