### ISSUE TITLE
instanceof not working

### ISSUE THREAD

**Issue by felangel** [Microsoft/TypeScript#22585]
index.ts
```typescript
class HttpError extends Error {
    
}

console.log(new HttpError() instanceof HttpError);
```

transpiled with ```tsc index.ts```
run with ```node index.js```
output:
```sh
false
```
```sh
tsc -v 2.6.2
```
tsconfig.json
```json
{
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "declaration": true,
        "outDir": "./dist",
        "moduleResolution": "node",
        "noImplicitAny": true,
        "noUnusedLocals": true,
        "lib": ["es6", "dom"]
    }
}
```
expected output to be true

**Comment by ajafff** [comment]
https://github.com/Microsoft/TypeScript/wiki/FAQ#why-doesnt-extending-built-ins-like-error-array-and-map-work

**Comment by benedictchen** [comment]
This is truly awful...

**Comment by hasahmed** [comment]
@felangel You should reopen this. The workaround isn't a suitable fix.

**Comment by MetaiR** [comment]
I have the same problem here and it gave me a headache when I tried this after working around 3 hours at midnight :
```
class MissingError extends Error {
   constructor() {
        super('Missing Data');
        Object.setPrototypeOf(this, MissingDataError.prototype);
   }
}
console.log(new MissingError() instanceof MissingError) // false
```

**Comment by benedictchen** [comment]
I also experienced this extremely annoying issue.  Essentially the "fix"
was ensure that native classes are not transpiled.  This means to only
support ES2015, ES6 and above :-/

**Comment by wengkhing** [comment]
I was having this issue as well, but managed to solve it by removing the `lib` option and use the following configuration. I'm using the typescript 3.9.5
```
"compilerOptions": {
    "target": "ES2015",
    "module": "CommonJS"
  }
```

**Comment by kaylakantola** [comment]
> I have the same problem here and it gave me a headache when I tried this after working around 3 hours at midnight :
> 
> ```
> class MissingError extends Error {
>    constructor() {
>         super('Missing Data');
>         Object.setPrototypeOf(this, MissingError.prototype);
>    }
> }
> console.log(new MissingError() instanceof MissingError) // false
> ```

This just saved me after a day of misery. Thank you!

**Comment by TooManyDots** [comment]
Bug is still there, this shouldn't be closed.

**Comment by DanielMenke** [comment]
why is this closed?!

**Comment by handelcamilo** [comment]
Facing the same issue. Is there a possibility to reopen this issue?

**Comment by RyanCavanaugh** [comment]
This is addressed in the FAQ; please read it.
