### ISSUE TITLE
Feature request - export all module properties from another file

### ISSUE THREAD

**Issue by ORESoftware** [Microsoft/TypeScript#22589]
I have this question on SO:
https://stackoverflow.com/questions/49285018/create-container-module-export-as-x-from-y/49285273

I'd like to do this:

```js
// (imaginary syntax that I made up)
export * as Category from './category';
export * as Roles from './roles';
export * as FunctionalTeams from './functional-team';
export * as WorkSteams from'./workstream';
```

but I had to do this instead:

```js
import * as Cat from './category';
import * as R from './roles';
import * as FT from './functional-team';
import * as WS from'./workstream';

export const Category = Cat;
export const Roles = R;
export const FunctionalTeams = FT;
export const WorkStreams = WS;
```

the first style would be convenient, but not sure if it's on the cards.

**Comment by andy-ms** [comment]
See https://github.com/tc39/proposal-export-ns-from

**Comment by ORESoftware** [comment]
yes thanks it looks like this is the proposal for the feature request that I just madel

https://github.com/tc39/proposal-export-ns-from#proposed-addition

thx
