### ISSUE TITLE
TS fails to unify generics when calling a function whose type is a union of 2 types

### ISSUE THREAD

**Issue by bcherny** [Microsoft/TypeScript#22597]
**TypeScript Version:**  2.7.0-dev.201xxxxx

**Search Terms:**  generic, polymorphic, unify, call, function, assignable

**Code**

```ts
type Try<T> = Success<T> | Failure<T>

type Success<T> = {
  flatMap<U>(g: (value: T) => Try<U>): Try<U>
}

type Failure<T> = {
  flatMap<U>(g: (value: T) => Try<U>): Try<T>
}

let Try = <T>(f: () => T): Try<T> => {
  try {
    let result = f()
    return {
      flatMap: g => g(result)
    }
  } catch (e) {
    return {
      flatMap: g => Try(e)
    }
  }
}

let t0 = Try(() => 3)  // Try<number>
let t1 = Try(() => 4)  // Try<number>

// Error: Cannot invoke an expression whose type lacks a call signature. Type '(<U>(g: (value: number) => Try<U>) => Try<U>) | (<U>(g: (value: number) => Try<U>) => Try<number>)' has no compatible call signatures.
let t3 = t0.flatMap(_ => t1)
```

**Expected behavior:**

TS should infer that `U` is `number`, meaning the two signatures are compatible.

**Actual behavior:**

```
Error: Cannot invoke an expression whose type lacks a call signature. Type '(<U>(g: (value: number) => Try<U>) => Try<U>) | (<U>(g: (value: number) => Try<U>) => Try<number>)' has no compatible call signatures.
```

FWIW, Flow chokes on this code, but Scala figures it out fine:

```scala
import scala.util.{Try}
val t0 = Try(() => 3)
val t1 = Try(() => 4)
val t3 = t0.flatMap(_ => t1)
:t t3 // scala.util.Try[() => Int]
```

**Playground Link:**  

https://www.typescriptlang.org/play/index.html#src=type%20Try%3CT%3E%20%3D%20Success%3CT%3E%20%7C%20Failure%3CT%3E%0A%0Atype%20Success%3CT%3E%20%3D%20%7B%0A%20%20flatMap%3CU%3E(g%3A%20(value%3A%20T)%20%3D%3E%20Try%3CU%3E)%3A%20Try%3CU%3E%0A%7D%0A%0Atype%20Failure%3CT%3E%20%3D%20%7B%0A%20%20flatMap%3CU%3E(g%3A%20(value%3A%20T)%20%3D%3E%20Try%3CU%3E)%3A%20Try%3CT%3E%0A%7D%0A%0Alet%20Try%20%3D%20%3CT%3E(f%3A%20()%20%3D%3E%20T)%3A%20Try%3CT%3E%20%3D%3E%20%7B%0A%20%20try%20%7B%0A%20%20%20%20let%20result%20%3D%20f()%0A%20%20%20%20return%20%7B%0A%20%20%20%20%20%20flatMap%3A%20g%20%3D%3E%20g(result)%0A%20%20%20%20%7D%0A%20%20%7D%20catch%20(e)%20%7B%0A%20%20%20%20return%20%7B%0A%20%20%20%20%20%20flatMap%3A%20g%20%3D%3E%20Try(e)%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A%0Alet%20t0%20%3D%20Try(()%20%3D%3E%203)%20%20%2F%2F%20Try%3Cnumber%3E%0Alet%20t1%20%3D%20Try(()%20%3D%3E%204)%20%20%2F%2F%20Try%3Cnumber%3E%0A%0A%2F%2F%20Error%3A%20Cannot%20invoke%20an%20expression%20whose%20type%20lacks%20a%20call%20signature.%20Type%20'(%3CU%3E(g%3A%20(value%3A%20number)%20%3D%3E%20Try%3CU%3E)%20%3D%3E%20Try%3CU%3E)%20%7C%20(%3CU%3E(g%3A%20(value%3A%20number)%20%3D%3E%20Try%3CU%3E)%20%3D%3E%20Try%3Cnumber%3E)'%20has%20no%20compatible%20call%20signatures.%0Alet%20t3%20%3D%20t0.flatMap(_%20%3D%3E%20t1)%0A

**Comment by ahejlsberg** [comment]
This is effectively a duplicate of #7294. The rules we use for computing union type signatures are (from the `getUnionSignatures` function in `checker.ts`):

> The signatures of a union type are those signatures that are present in each of the constituent types. Generic signatures must match exactly, but non-generic signatures are allowed to have extra optional parameters and may differ in return types. When signatures differ in return types, the resulting return type is the union of the constituent return types.

Ideally, we'd process call operations on union types as independently evaluated calls on each constituent type, requiring that they all succeed and producing a union of all of the results. However, there are some architectural challenges that prevent us from doing so.

**Comment by bcherny** [comment]
Thanks for the quick response Anders. This would be really great to have to simulate Scala/Haskell style data constructors in TS, so we can express types like Option, Either, Try, and so on in an ergonomic way.

**Comment by bcherny** [comment]
FWIW, rewriting it as a class seems to work. However, because [errors are untyped](#13219) in TS, it's of limited utility:

```ts
abstract class Try<T> {
  protected constructor(protected value: T) { }
  abstract flatMap<U>(g: (value: T) => Try<U>): Try<T | U>
  abstract getOrElseWith<U>(g: (value: Error) => U): T | U
  static of<T>(f: () => T): Try<T> {
    try {
      return new Success(f())
    } catch (e) {
      return new Failure(e)
    }
  }
}

class Success<T> extends Try<T> {
  flatMap<U>(g: (value: T) => Success<U>): Success<U>
  flatMap<U extends Error>(g: (value: T) => Failure<U>): Failure<U>
  flatMap<U>(g: (value: T) => Try<U>): Try<U> {
    return g(this.value)
  }
  getOrElseWith() {
    return this.value
  }
}

class Failure<T extends Error> extends Try<T> {
  flatMap<U>(g: (value: T) => Success<U>): Failure<T>
  flatMap<U extends Error>(g: (value: T) => Failure<U>): Failure<T>
  flatMap<U>(g: (value: T) => Try<U>): Failure<T> {
    return this
  }
  getOrElseWith<U>(g: (value: Error) => U): U {
    return g(this.value)
  }
}

let t3 = Try
  .of(() => 3)
  .flatMap(_ => Try.of(() => 'hello'))
  .getOrElseWith(e => true)
```
