### ISSUE TITLE
Distribute conditional types over concrete unions

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#22595]
```ts
type Foo = (string | number | boolean) extends (infer T) ? T[] : never
```

**Expected**

`Foo` has the type `string[] | number[] | boolean[]`

**Actual**

`Foo` has the type `Array<string | boolean | number>`.

**Comment by DanielRosenwasser** [comment]
I guess you could always write a helper type like

```ts
type Foo<T> = T extends any ? T[] : never

type Bar = Foo<string | number | boolean>
```

**Comment by ahejlsberg** [comment]
We distribute over union types *only* during instantiation of conditional types where the leftmost type is a naked type parameter. It would quickly become very confusing to do it in other situations. For example:

```ts
type Strange<T> = (T | string) extends any ? T[] : never;
```

I'm not sure there is any rule by which we can distribute over unions *and* have users be able to reason about the meaning of `T` in that type.
