### ISSUE TITLE
function's union generic parameter cannot be infered from condition

### ISSUE THREAD

**Issue by zaaack** [Microsoft/TypeScript#22594]
**TypeScript Version:**  2.7.2

**Search Terms:** 

**Code**

```ts
type Props = {
    a: string
    b: number
}

function test<K extends keyof Props>(key: K, newVal: Props[K], oldVal: Props[K]) {
    if (key === 'a') { // K won't be inferred as 'a'
        shouldBeString(newVal)  // and this line would trigger an error
    } else if (key === 'b') {
        shouldBeNumber(newVal)
    }
}

function shouldBeString(v: string) {

}


function shouldBeNumber(v: string) {

}
```

**Expected behavior:**

Generic union should be infered.

**Actual behavior:**

Not

**Playground Link:**  [link](http://www.typescriptlang.org/play/index.html#src=type%20Props%20%3D%20%7B%0D%0A%20%20%20%20a%3A%20string%0D%0A%20%20%20%20b%3A%20number%0D%0A%7D%0D%0A%0D%0Afunction%20test%3CK%20extends%20keyof%20Props%3E(key%3A%20K%2C%20newVal%3A%20Props%5BK%5D%2C%20oldVal%3A%20Props%5BK%5D)%20%7B%0D%0A%20%20%20%20if%20(key%20%3D%3D%3D%20'a')%20%7B%0D%0A%20%20%20%20%20%20%20%20shouldBeString(newVal)%0D%0A%20%20%20%20%7D%20else%20if%20(key%20%3D%3D%3D%20'b')%20%7B%0D%0A%20%20%20%20%20%20%20%20shouldBeNumber(newVal)%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Afunction%20shouldBeString(v%3A%20string)%20%7B%0D%0A%0D%0A%7D%0D%0A%0D%0A%0D%0Afunction%20shouldBeNumber(v%3A%20string)%20%7B%0D%0A%0D%0A%7D)
**Related Issues:**

**Comment by RyanCavanaugh** [comment]
We don't currently have the ability to track relations from one type guard to another symbol. See also #12184

**Comment by zaaack** [comment]
@RyanCavanaugh Thanks for your fast reply! I see.
