### ISSUE TITLE
Type Definition for function.apply is wrong

### ISSUE THREAD

**Issue by tmkn** [Microsoft/TypeScript#22600]
**TypeScript Version:**  2.7.2

**Search Terms:** 
apply lib

**lib.es5.d.ts:**
**lib.es6.d.ts:**
```ts
apply(this: Function, thisArg: any, argArray?: any): any;
```
`argArray` actually accepts an array of arguments but since it's defined as any, you can pass in non array types which lead to a TypeError at runtime.

**Code**

```ts
const foo = (a) => alert(a);

try {
    foo.apply(foo, "not array");    //TypeError
}
catch(e) {
    alert(e);
}
foo.apply(foo, ["in array"]);    //ok
```

**Expected behavior:**
Compile Error since argument is not an array.
**Actual behavior:**
No compiletime error
Triggers `TypeError` at runtime
**Playground Link:**  
http://www.typescriptlang.org/play/index.html#src=const%20foo%20%3D%20(a)%20%3D%3E%20alert(a)%3B%0D%0A%0D%0Atry%20%7B%0D%0A%20%20%20%20foo.apply(foo%2C%20%22not%20array%22)%3B%20%20%20%20%2F%2FTypeError%0D%0A%7D%0D%0Acatch(e)%20%7B%0D%0A%20%20%20%20alert(e)%3B%0D%0A%7D%0D%0Afoo.apply(foo%2C%20%5B%22in%20array%22%5D)%3B%20%20%20%20%2F%2Fok

**Comment by DanielRosenwasser** [comment]
I mean, this is a breaking change, but I can't imagine what it breaks that wouldn't be helpful.
