### ISSUE TITLE
Create commonjs imports in importFixes

### ISSUE THREAD

**Issue by andy-ms** [microsoft/TypeScript#22602]
**TypeScript Version:**  master

**Code**

Currently `getCodeActionForNewImport` only creates ES6 and `import =` imports. This could be extended to create commonjs imports if we detect that we're in a commonjs file (file.commonJsModuleIndicator && !file.externalModuleIndicator)

Then, no longer exclude these files from getting external module completions in completions.ts.

**Comment by RyanCavanaugh** [comment]
Declining due to lack of activity/interest
