### ISSUE TITLE
Asp.Net Core 2.0 with VSO CI - tsc 2.6.2 error

### ISSUE THREAD

**Issue by AmanpreetSingh-GitHub** [microsoft/TypeScript#22601]
I have Asp.Net Core 2.0 solution with VSO CI build. During the build phase I am getting below error -

`node_modules\@types\react\index.d.ts(109,81): Error TS2344: Build:Type 'ChangeTargetHTMLAttributes<T>' does not satisfy the constraint 'DOMAttributes<T>'.`

Error snapshot -
![image](https://user-images.githubusercontent.com/16236053/37470168-efe5eb86-288c-11e8-8ac4-6c4ac53c4881.png)

I am using React 15.0 and my tsconfig.json content are -
`{
  "compilerOptions": {
    "baseUrl": ".",
    "module": "es2015",
    "moduleResolution": "node",
    "target": "es5",
    "jsx": "react",
    "sourceMap": true,
    "skipDefaultLibCheck": true,
    "strict": true,
    "types": [ "webpack-env" ],
    "noImplicitThis": false
  },
  "exclude": [
      "bin",
      "node_modules"
  ]
}`

**Comment by andy-ms** [comment]
Could you provide a code example that is failing?

**Comment by AmanpreetSingh-GitHub** [comment]
The same error can be replicated when I create a new Asp.Net Core 2.0 React project and run "tsc" command in the root folder. Does that work @andy-ms ?

**Comment by mhegazy** [comment]
What version of VS are you using? what version of TS? can you share a project?

**Comment by justin-capalbo** [comment]
I'm having the same issue in the Error List in visual studio for this project.  

https://github.com/justin-capalbo/Grocerist.Net

I created this project using Visual Studio with React selected for the ASP.NET Core Web Application template

**Comment by justin-capalbo** [comment]
I am having this issue in this project.

https://github.com/justin-capalbo/Grocerist.Net

- I used the `dotnet new react` template to create this project in VS2017 Community Version 15.7.2.
- Output of `dotnet --version`: **2.1.201**
- Version of TS in package.json: **2.4.1**
