### ISSUE TITLE
Is there any effective way of debugging enums?

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#2260]
I'm just trying out some parts of your compiler API.

And I'm traversing every node and trying to figure what there kind(`SyntaxKind`) is. If I do a console log I only get a number.

```
console.log(node.kind);
```

Is there any way I kind get the name of the enum value?

**Comment by CyrusNajmabadi** [comment]
In the console, write:  ts.SyntaxKind[node.kind]

             -- Cyrus

**Comment by tinganho** [comment]
@CyrusNajmabadi thanks.

**Comment by tinganho** [comment]
@CyrusNajmabadi Is there anyway I can debug without it throwing out the error message in the compiler:
```
A const enum member can only be accessed using a string literal
```

**Comment by urielha** [comment]
@tinganho I suppose this is not relevant anymore but FYI:
you can do as described here https://github.com/Microsoft/TypeScript/issues/1771#issuecomment-197206635
