### ISSUE TITLE
Add example of instance member initialization to TS Handbook

### ISSUE THREAD

**Issue by jacobq** [microsoft/TypeScript#22606]
In the TypeScript Handbook's "Classes" section, there are no examples (and I didn't see any explanation in the text either) of setting default/initial values for instance members. It appears that this is equivalent to assigning these values at the beginning of `constructor`, but it would be helpful (especially for newcomers like me) if the handbook had more information and an example showing this behavior. At first I thought perhaps it was standard ECMAScript, but it isn't. Evaluating the short statement `class MyClass { foo = 'bar'; }` in a modern browser and/or NodeJS results in `SyntaxError: Unexpected token =`

It works in TS though, for example, here's a modified version of the default "Playground" example:
```ts
class Greeter {
    nameOfPersonToGreet = '(unknown person)'; // <---- document this feature
    constructor(nameOfPersonToGreet?: string) {
        if (nameOfPersonToGreet)
            this.nameOfPersonToGreet = nameOfPersonToGreet;
    }
    greet() {
        return `Hello, ${this.nameOfPersonToGreet}`;
    }
}

let button = document.createElement('button');
button.textContent = "Say Hello";
button.onclick = function() {
    let greeter = new Greeter();
    alert(greeter.greet());
    let greeter2 = new Greeter('world');
    alert(greeter2.greet());
}

document.body.appendChild(button);
```

The closest thing I could find was the below [example from the "static properties" section](http://www.typescriptlang.org/docs/handbook/classes.html#static-properties). However, this obviously different from instance/non-static member initialization as it effects all instances.
```ts
class Grid {
    static origin = {x: 0, y: 0};
    calculateDistanceFromOrigin(point: {x: number; y: number;}) {
        let xDist = (point.x - Grid.origin.x);
        let yDist = (point.y - Grid.origin.y);
        return Math.sqrt(xDist * xDist + yDist * yDist) / this.scale;
    }
    constructor (public scale: number) { }
}
```

**Comment by RyanCavanaugh** [comment]
This is ES syntax now, so out of scope for mandatory introduction in the handbook
