### ISSUE TITLE
typesMapLocation not forwarded from Session to ProjectService

### ISSUE THREAD

**Issue by kyliau** [Microsoft/TypeScript#22607]
**TypeScript Version:**  2.8.0-dev.20180315

**Search Terms:** 
typesMapLocation

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```
Bring up tsserver with argument `--typesMapLocation /path/to/typesMap.json` and turn on logging.
Inspect the logs, and see that `Provided types map file "/path/to//typesMap.json" doesn't exist` even though the file is valid.

**Expected behavior:**
typesMap.json should be correctly located and error not shown in logs.

**Actual behavior:**
Error message about non-existent typeMaps.json shown in the logs.

**Playground Link:**  

**Related Issues:**

**Comment by sheetalkamat** [comment]
Assigned to @amcasey  since there is already PR #22776 for this that I just re-opened.
