### ISSUE TITLE
map return type

### ISSUE THREAD

**Issue by BetterCallSky** [Microsoft/TypeScript#22611]
I am trying to change the return type of a function using a new `infer` syntax.

Example:
```ts

type Convert<T> = T extends (
  arg1: infer A1,
  arg2: infer A2,
) => infer R
  ? (arg1: A1, arg2: A2) => { payload: R }
  : never;

type A = (a: number, b: number) => { a: number; b: number };
type B = Convert<A>

```

Argument names (`a`, `b`) cannot be inferred and type B has the signature:

```ts
type B = (arg1: number, arg2: number) => {
    payload: {
        a: number;
        b: number;
    };
}
```

Is it possible to use the same argument names? Or we must wait for variadic types #5453?

**TypeScript Version:**  2.80-dev.20180315

**Comment by RyanCavanaugh** [comment]
What's the desired behavior? Just for the parameter names to match?

**Comment by lsentkiewicz** [comment]
Correct.
If the autocomplete shows `arg1`, `arg2` etc. then it's hard to use such function.

**Comment by RyanCavanaugh** [comment]
You'd need variadic types or something isomorphic to it to maintain the argument names.

**Comment by BetterCallSky** [comment]
@RyanCavanaugh 
Any chance to reopen it?
Keeping the same argument names would be very useful when creating functions like `curry`.
