### ISSUE TITLE
Inferred type symbol in conditional type should be visible-but-banned in falsy arm

### ISSUE THREAD

**Issue by RyanCavanaugh** [Microsoft/TypeScript#22610]
Currently if you write
```ts
type C<T> = T extends infer U ? U : U;
//                                  ~ Cannot find name "U"
```
We give you an error because `U` is not in scope at all in the false arm.

This is a) confusing (`U` is right there!) and b) a landmine, because you might have an outer type of the same name
```ts
// Elsewhere
type U = string;
// ...
/// Not what I meant!
type C<T> = T extends infer U ? number : U;
```

We should keep `U` in scope in both cases and disallow its use with an explicit error message, e.g. (please bikeshed):

 > Inferred type parameter "U" is unmatched in this case and cannot be used

This should *not* block nesting of lexical scopes; i.e. this should still be legal because each `U` would shadow the outer expression's:
```ts
type C<T> = T extends Array<infer U> ? U :
            T extends Promise<infer U> ? U :
            never;
```

**Comment by RyanCavanaugh** [comment]
cc @ahejlsberg @DanielRosenwasser since we should 👍 / 👎 before release

**Comment by krryan** [comment]
Why keep `U` in scope in the falsy case at all? Why not allow the use of the outer `U`? Just for readability/least-surprise concerns? I can buy that but I'm wondering if I'm missing something more.

**Comment by RyanCavanaugh** [comment]
This one missed the boat
