### ISSUE TITLE
Less colour options in Visual Studio 2017 than in Visual Studio Code

### ISSUE THREAD

**Issue by Griffork** [Microsoft/TypeScript#22629]
**TypeScript Version:**  2.8.RC

**Issue**
In visual studio code you can colour different categories of keywords in different colours, which significantly improves readability:
![image](https://user-images.githubusercontent.com/3665998/37506073-5416cc10-293c-11e8-89db-db1a11273e3b.png)
![image](https://user-images.githubusercontent.com/3665998/37506081-5c241a52-293c-11e8-97ea-a8ec9ca6b85e.png)
In Visual Studio 2017 all of these colour options are under the same option (e.g. `TextEditor -> Keyword -> Foreground`). Having these different classes of keywords be the same colour makes things harder to read:
![image](https://user-images.githubusercontent.com/3665998/37506086-6199b708-293c-11e8-8747-22d20640d654.png)
![image](https://user-images.githubusercontent.com/3665998/37506095-68c497d2-293c-11e8-9f9d-eeface287e5a.png)

Additionally, in Visual Studio Code all types (including built-ins and Error) have the same colour, but in Visual Studio 2017 built-ins have the same colour as keywords, and Error has the same colour as variables (even though it should be the colour of a class or interface).

**Desired outcome**
Please make it possible to change the colours for different classes of keywords like in Visual Studio Code.

**Comment by RyanCavanaugh** [comment]
This isn't something we can address from the TypeScript side due to architectural limitations of how VS does things.
