### ISSUE TITLE
How is the import custom file type? 

### ISSUE THREAD

**Issue by Houfeng** [Microsoft/TypeScript#22627]
How is the import custom file type? 

such as:
```js
import xxx from './xxx.yql'
```

For the front-end project, the custom file type has been processed by webapck loader

Although it can be done
```js
const xxx = require('./xxx.yql')
```

Is that the only way to do that?

**Comment by andy-ms** [comment]
See [wildcard module declarations](https://www.typescriptlang.org/docs/handbook/modules.html)
