### ISSUE TITLE
In JS, any declaration with a non-primitive initializer should be a JS container

### ISSUE THREAD

**Issue by sandersn** [Microsoft/TypeScript#22637]
```ts
// @noEmit: true
// @allowJs: true
// @checkJs: true
// @Filename: a.js
// from clear-require
var clear = moduleId => 2
clear.all = () => 1
```

**Expected behavior:**
`all` is a property on `clear`, and has the type `() => number`.

**Actual behavior:**
Error: 'all' is not a property on 'clear'.

Maybe any top-level declaration with a non-primitive initialiser should create a container in Javascript, although that would be hard to verify in the binder.

**Comment by sandersn** [comment]
Another example, this time from a call expression:

```ts
// @noEmit: true
// @allowJs: true
// @checkJs: true
// @Filename: a.js
// from axios
function A(x) {
    this.x = x
}
function createInstance(defaultConfig) {
    return new A(defaultConfig.x);
}
var a = createInstance({ x: 1 })
a.all = function () { }
```

**Comment by mhegazy** [comment]
The first example is a bit weird given that `this` means something different here.

The second seems like a duplicate of https://github.com/Microsoft/TypeScript/issues/10868
