### ISSUE TITLE
Nodeback (error first callback) type support

### ISSUE THREAD

**Issue by massimonewsuk** [Microsoft/TypeScript#22634]
I appreciate this may not be easy to implement or support but it felt like a natural thing to do for me.

**Search Terms:** 
nodeback
error first callback

**Code**
```ts
type ErrorFirstCallback<T> = ((err: Error) => void) | ((err: null | undefined, result: T) => void)
type Result = {
    foo: string;
    bar: string;
}

function somethingAsync(callback: ErrorFirstCallback<Result>) {
}

function onFailure(error: Error) {
}

function onSuccess(result: Result) {
}

somethingAsync((err, result) => {
    if (err != null) {
        onFailure(err);
        onSuccess(result); // This should fail to compile
        return;
    }
    onSuccess(result);
})
```

**Expected behavior:**
I expect the line with the comment to fail to compile, because `result` should be undefined within the `if` block

**Actual behavior:**
The code compiles fine, and `err` is `never` inside the `if` block

**Playground Link:**
https://www.typescriptlang.org/play/#src=type%20ErrorFirstCallback%3CT%3E%20%3D%20((err%3A%20Error)%20%3D%3E%20void)%20%7C%20((err%3A%20null%20%7C%20undefined%2C%20result%3A%20T)%20%3D%3E%20void)%0D%0Atype%20Result%20%3D%20%7B%0D%0A%20%20%20%20foo%3A%20string%3B%0D%0A%20%20%20%20bar%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Afunction%20somethingAsync(callback%3A%20ErrorFirstCallback%3CResult%3E)%20%7B%0D%0A%7D%0D%0A%0D%0Afunction%20onFailure(error%3A%20Error)%20%7B%0D%0A%7D%0D%0A%0D%0Afunction%20onSuccess(result%3A%20Result)%20%7B%0D%0A%7D%0D%0A%0D%0AsomethingAsync((err%2C%20result)%20%3D%3E%20%7B%0D%0A%20%20%20%20if%20(err%20!%3D%20null)%20%7B%0D%0A%20%20%20%20%20%20%20%20onFailure(err)%3B%0D%0A%20%20%20%20%20%20%20%20onSuccess(result)%3B%20%2F%2F%20This%20should%20fail%20to%20compile%0D%0A%20%20%20%20%20%20%20%20return%3B%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20onSuccess(result)%3B%0D%0A%7D)

**Comment by RyanCavanaugh** [comment]
Many open issues already on having type guards on one variable change the type of another.
