### ISSUE TITLE
tsconfig cannot be specified along with an explicit list of files to compile - TS5042

### ISSUE THREAD

**Issue by ntabernero** [Microsoft/TypeScript#22649]
We are using Typescript for our operational project and have found it very useful.  However, we have some use cases where we need to compile one (or a few) source files along with most of the dependencies using the options encoded in tsconfig.  Sadly, using the command line options won't quite get us where we would like to be (notably the absence of either a "rootDirs" and/or "paths" command line options). 

We would like to be able to do "tsc -p <config> foo.ts" (or any equivalent workaround such as enabling "rootDirs" and "paths" as command line options).

**Comment by simonbuchan** [comment]
When I've wanted this, it's generally been either:
- I'm just trying to see what typescript is outputting for some file, a-la `babel` CLI, here the option to just output to stdout (with highlighting?) would be preferred
- I'm trying to set up some npm-script based "multi-project" build thing, where I have configs for various envs (e.g. browser, server, shared, spec, and e2e) for each I'm re-using. I've now settled on the other split, a tsconfig per project, and overriding the options for envs using CLI options. Being able to do something like "stack" configs on the CLI would be preferred.

**Comment by RyanCavanaugh** [comment]
Duping to #12958
