### ISSUE TITLE
Duplicate names in generated list of vars

### ISSUE THREAD

**Issue by hultqvist** [microsoft/TypeScript#22650]
**TypeScript Version:**  2.7.2

**Search Terms:** duplicate var declarations

**Code**

```ts
async function test(r: any) {
    if (r) {
        var a = new Error();
    }
    else if (r)
    {
        var a: Error;
    }
}
```

```json
{
  "compilerOptions": {
    "noEmitHelpers": true,
    "target": "es5",
    "lib": [ "es6" ]
  }
}

```

**Expected behavior:**
```
var a;

or

var a_1,a_2;
```

**Actual behavior:**
The line "var a,a;" has two variables with the same name.

````
function test(r) {
    return __awaiter(this, void 0, void 0, function () {
        var a, a;
        return __generator(this, function (_a) {
            if (r) {
                a = new Error();
            }
            else if (r) {
                a = void 0;
            }
            return [2 /*return*/];
        });
    });
}
````

**Playground Link:** [Link here](https://www.typescriptlang.org/play/#src=async%20function%20test(r%3A%20any)%20%7B%0D%0A%20%20%20%20if%20(r)%20%7B%0D%0A%20%20%20%20%20%20%20%20let%20a%20%3D%20new%20Error()%3B%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20else%20if%20(r)%0D%0A%20%20%20%20%7B%0D%0A%20%20%20%20%20%20%20%20let%20a%3A%20Error%3B%0D%0A%20%20%20%20%7D%0D%0A%7D)

**Related Issues:**

This output triggers errors for closure compiler, where it was first discovered.

**Comment by RyanCavanaugh** [comment]
Doesn't change runtime behavior but it'd be nice to not have it duplicated

**Comment by jMuzsik** [comment]
I'd like to work on this, is someone willing to point me in the right direction? Which file to look into, etc. ? Thanks!
