### ISSUE TITLE
Refresh definition file (d.ts) after build on linked project 

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#22656]
_From @moshfeu on March 14, 2018 7:54_

- VSCode Version: Version 1.21.0 (1.21.0)
- OS Version: OS X 10.11.6 (15G17023)

Steps to Reproduce:

1.  Open a project folder with link (`npm link`) to another local project.
2. The another project has `d.ts` file. So verify that you can go to definition of the project. (Click on <kbd>F12</kbd> on a function from the another project.  (You should be moved to the `d.ts` file in the `node_modules/another_project/dist/d.ts`)
3. Update the `d.ts` file (for example: change the code and let webpack to update the `d.ts`).

**Expected result:**

VScode will refresh its intellisense and errors detection. 

**Actual result**

It didn't. Even if I close and open the file. I need to close the vscode instance of my current project and open it again. Only then it count the updated `d.ts`.

Does this issue occur when all extensions are disabled?: Yes

Thanks!

_Copied from original issue: Microsoft/vscode#45738_

**Comment by mjbvz** [comment]
Repo:

1. `git clone https://github.com/mjbvz/vscode-issue-45738`
1. Open `b` and `a` in separate vs code windows
1. In b, run `npm link ../a`
1. In b, open `index.js`
1. In `a/index.d.ts`, change the type of `abc` to something other than string
1. Switch back to `b`

**Bug**
No update of errors in `b/index.js`

**Comment by sheetalkamat** [comment]
There is no "index.js" in b folder.. I tried that in index.ts and it seems to work correctly (I used latest master build (nightly wont be out yet))

**Comment by mjbvz** [comment]
Yes it should be `index.ts`. I'll try again once there is a new nightly out. Did you also test on MacOS?

**Comment by sheetalkamat** [comment]
No checked on windows.. Let me know if it repros on mac os and if possible tsserver log from both vscode sessions with verbose would be best.

**Comment by sheetalkamat** [comment]
@mjbvz were you able to repro this? Also i am assuming in step 5 the change is saved as without that the change wont be visible to other vscode window right?

**Comment by mjbvz** [comment]
Yes, the file has to be edited outside of the current vscode window too. The change is picked up when you open the `d.ts` file in vscode

**Comment by sheetalkamat** [comment]
@mjbvz yes i had tried that as well. @andy-ms tried this on linux as well. If you are able to repro this, please share the tsserver log from both the sessions. Thanks

**Comment by sheetalkamat** [comment]
Closing this since its no repro. Please reopen if you have repro and more info. Thanks.
