### ISSUE TITLE
tsserver shouldn't assume that npm is in the same directory as node

### ISSUE THREAD

**Issue by mirekdlugosz** [microsoft/TypeScript#22654]
Function `getDefaultNPMLocation` in `src/server/typingsInstaller/nodeTypingsInstaller.ts` is supposed to return path to `npm` binary, but it does so by assuming that `npm` is in the same directory as `node`. This is not always a case.

One example would be Debian proper, which has recent-ish Node (8.9.3 in unstable and 8.10.0 in experimental as of this writing), but hopelessly outdated npm (something from 2014). Since npm is pure JavaScript, it is possible to use Node from official repository, but npm from `npm i -g`.

At the very minimum, the function in question should verify that constructed path actually exists before returning it. If not, return just binary name and let operating system find it in `$PATH`.

**TypeScript Version:**  2.8.0-dev.20180316
**Search Terms:** npm location, npmlocation
**Code**

```sh
tsserver
```

**Expected behavior:**
tsserver is running without errors on STDOUT

**Actual behavior:**
```sh
Content-Length: 76

{"seq":0,"type":"event","event":"typingsInstallerPid","body":{"pid":31260}}
/bin/sh: 1: /usr/bin/npm: not found
```

It **seems** that server is running, although some functionality might be missing.

**Playground Link:** N/A

**Related Issues:** N/A

**Comment by mhegazy** [comment]
PRs welcomed.

**Comment by mhegazy** [comment]
One thing to note here. we already have an override `--npmLocation` to the server that can be passed using vscode's setting `"typescript.npm"`.

**Comment by RyanCavanaugh** [comment]
Either this has been resolved or is not a remotely common configuration
