### ISSUE TITLE
can get this to work

### ISSUE THREAD

**Issue by reachdevelopers** [Microsoft/TypeScript#22666]
code in question:
```
app.set("permission", {
    after: (res, next, authorizedStatus) => {
        if (authorizedStatus !== "authorized") {
            res.redirect("/login" || {});
        } else {
            next();
        }
    }
});
```

This is giving this errors when I build
`src/app.ts(52,13): error TS7006: Parameter 'res' implicitly has an 'any' type.`
`src/app.ts(52,18): error TS7006: Parameter 'next' implicitly has an 'any' type.`
`src/app.ts(52,24): error TS7006: Parameter 'authorizedStatus' implicitly has an 'any' type.`

**Comment by DanielRosenwasser** [comment]
Hey there, this issue tracker isn't meant to work as a support forum. These questions tend to be better suited for StackOverflow. You may want to open a question up there instead. Thanks!
