### ISSUE TITLE
Certificate just expired on https://www.typescriptlang.org/

### ISSUE THREAD

**Issue by fr6nco** [Microsoft/TypeScript#22667]
Looks like the certificate has just expired

**Comment by fr6nco** [comment]
https://imgur.com/a/uMYHF

**Comment by DanielRosenwasser** [comment]
Duplicate of #22663.

**Comment by RyanCavanaugh** [comment]
@DanielRosenwasser the site is down

🔔 

the

site

is


down

**Comment by DanielRosenwasser** [comment]
https://www.youtube.com/watch?v=ILVfzx5Pe-A
