### ISSUE TITLE
Default import syntax not working with multiple keys

### ISSUE THREAD

**Issue by rdsedmundo** [Microsoft/TypeScript#22678]
**TypeScript Version:**  2.7.2
**Code**

The default import syntax isn't working alongside another key of the module imported. This doesn't work:

```ts
import React, { Component } from 'react';

class App extends Component {}

export default App;
```

It throws:
```
Object prototype may only be an Object or null: undefined
```

He's complaining that the `extends` value passed to the operator is `undefined` (i.e `Component`), which can be confirmed adding a `console.log`:

```ts
import React, { Component } from 'react';

console.log(Component); // undefined
```

However, all those solutions below work, making `Component` to be defined:

```ts
import {
  default as React,
  Component
} from 'react';

console.log(Component); // defined

// or
import React from 'react';
import { Component } from 'react';

console.log(Component); // defined

// or
import React from 'react';

console.log(React.Component); // defined
```

**Expected behavior:** The default import syntax should work.
**Actual behavior:** Using the default import syntax makes the `Component` to be undefined, therefore throwing that error when I try to `extends` the `App` class.

**Playground Link:**
1- Clone this repository: https://github.com/rdsedmundo/react-boilerplate
2- Run `yarn && yarn dev`.
3- Access `localhost:3000`.
4- The error should appear in the console (the file with the error is at `src/components/App/index.tsx`).

I might be might be really missing something here, if yes, I apologize, but I couldn't understand why it isn't working, so I'm reporting this as a bug. There's a chance that this could be at the Webpack level, if yes, let me know so I could move this issue to there.

**Comment by RyanCavanaugh** [comment]
Duplicate of #21621. The TL;DR is that React should really set `__esModule`, or you need to disable `esModuleInterop` wherever in your buildchain that gets set.

**Comment by rdsedmundo** [comment]
Sorry for the duplicate, I really tried to search before but didn't encounter someone relating the same thing.

I'll close this one.

Thanks, Ryan.
