### ISSUE TITLE
MediaError missing message property

### ISSUE THREAD

**Issue by nikmartin** [Microsoft/TypeScript#22673]
https://github.com/Microsoft/TypeScript/blob/bb23e9601f5ea0b4fe1e97545ef01535fa18a23d/lib/lib.d.ts#L11664

According to spec The MediaError object should have a message:string property:

https://html.spec.whatwg.org/multipage/media.html#dom-mediaerror-message

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.
