### ISSUE TITLE
Declare method quickfix/codeaction should create method after current quick fix location

### ISSUE THREAD

**Issue by mattbierner** [Microsoft/TypeScript#22674]
**TypeScript Version:**  2.8.0-rc

**Search Terms:** 
- declare method
- quick fix
-  code action

**Code**

```ts
class Foo {
    a() {
        this.b()
    }
}
```

Trigger the `declare method 'b'` quickfix on `this.b()`

**Expected behavior:**
Method inserted after current location (or possible at end of class)

```ts
class Foo {
    a() {
        this.b()
    }
    b(): any {
        throw new Error("Method not implemented.");
    }
}
```

**Actual behavior:**
Method inserted at top of class:

```ts
class Foo {
    b(): any {
        throw new Error("Method not implemented.");
    }
    a() {
        this.b()
    }
}
```

**Comment by shirishp** [comment]
@mattbierner Can you please elaborate on why do you think the new method should be added after method which uses it?
IMHO, having method declaration after it's use doesn't feel right (similar to variables), unless it's a private method of course.

**Comment by mjbvz** [comment]
@shirishp A few reasons:

1. I'm mainly using this for private methods
1. I generally organize methods from highest level (public apis) to lowest level (implementation details). That way you see the highest level stuff and can drill into the implementation as needed
1. The current behavior puts the new method before everything in the class, including property declarations and the constructor.

**Comment by mhegazy** [comment]
thanks @vpukhanov
