### ISSUE TITLE
Erroneous "Spread types may only be created from object types"?

### ISSUE THREAD

**Issue by mindplay-dk** [Microsoft/TypeScript#22687]
I seem to be (incorrectly?) getting an error "Spread types may only be created from object types" for a case where the type in question is constrained as `object`.

[Example here](https://www.typescriptlang.org/play/index.html#src=interface%20TreeNode%3CT%20extends%20object%3E%20%7B%0D%0A%20%20%20%20id%3A%20number%0D%0A%20%20%20%20parent%3A%20TreeNode%3CT%3E%20%7C%20undefined%0D%0A%20%20%20%20children%3A%20TreeNode%3CT%3E%5B%5D%0D%0A%20%20%20%20data%3A%20T%0D%0A%7D%0D%0A%0D%0Ainterface%20Menu%20%7B%0D%0A%20%20%20%20title%3A%20string%0D%0A%20%20%20%20children%3A%20Menu%5B%5D%0D%0A%7D%0D%0A%0D%0Alet%20next_id%20%3D%200%3B%0D%0A%0D%0Ainterface%20Data%3CT%3E%20%7B%0D%0A%20%20%20%20children%3A%20T%5B%5D%0D%0A%7D%0D%0A%0D%0Afunction%20toTreeNode%3CT%20extends%20Data%3CT%3E%3E(data%3A%20T%2C%20parent%3F%3A%20TreeNode%3CT%3E)%3A%20TreeNode%3CT%3E%20%7B%0D%0A%20%20%20%20let%20node%3A%20TreeNode%3CT%3E%20%3D%20%7B%0D%0A%20%20%20%20%20%20%20%20id%3A%20next_id%2B%2B%2C%0D%0A%20%20%20%20%20%20%20%20parent%2C%0D%0A%20%20%20%20%20%20%20%20children%3A%20%5B%5D%2C%0D%0A%20%20%20%20%20%20%20%20data%0D%0A%20%20%20%20%7D%3B%0D%0A%0D%0A%20%20%20%20for%20(let%20child%20of%20data.children)%20%7B%0D%0A%20%20%20%20%20%20%20%20node.children.push(toTreeNode(child%2C%20node))%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20return%20node%3B%0D%0A%7D%0D%0A%0D%0Afunction%20toData%3CT%20extends%20object%3E(node%3A%20TreeNode%3CT%3E)%3A%20T%20%7B%0D%0A%20%20%20%20return%20%7B%0D%0A%20%20%20%20%20%20%20%20...node.data%2C%0D%0A%20%20%20%20%20%20%20%20children%3A%20node.children.map(toData)%0D%0A%20%20%20%20%7D%3B%0D%0A%7D%0D%0A%0D%0Alet%20menu%3A%20Menu%20%3D%20%7B%0D%0A%20%20%20%20title%3A%20%22Main%20Menu%22%2C%0D%0A%20%20%20%20children%3A%20%5B%0D%0A%20%20%20%20%20%20%20%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20title%3A%20%22Fruit%22%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20children%3A%20%5B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%20title%3A%20%22Apple%22%2C%20children%3A%20%5B%5D%20%7D%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%20title%3A%20%22Pear%22%2C%20children%3A%20%5B%5D%20%7D%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%20title%3A%20%22Orange%22%2C%20children%3A%20%5B%5D%20%7D%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%5D%0D%0A%20%20%20%20%20%20%20%20%7D%2C%0D%0A%20%20%20%20%20%20%20%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20title%3A%20%22Meat%22%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20children%3A%20%5B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%20title%3A%20%22Chicken%22%2C%20children%3A%20%5B%5D%20%7D%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%20title%3A%20%22Beef%22%2C%20children%3A%20%5B%5D%20%7D%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%5D%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%5D%0D%0A%7D%0D%0A%0D%0Alet%20tree%20%3D%20toTreeNode(menu)%3B%0D%0A%0D%0Aconsole.log(tree)%3B%0D%0A%0D%0Atree.children%5B0%5D.children.splice(1%2C%201)%3B%20%2F%2F%20delete%20Pear%0D%0A%0D%0Aconsole.log(toData(tree))%3B%0D%0A)

When I hover over the offending call site:

![image](https://user-images.githubusercontent.com/103348/37584723-e7cc3d7a-2b56-11e8-84d7-762f25d42581.png)

The `data` property is of a type `T` where `T extends object`, so why am I not allowed to spread it's properties to a new object?

The code works as intended, I just can't seem to figure out what's required to get rid of the error message. I could just cast it as `any` of course, but that seems dirty?

**Comment by ajafff** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/10727
Fix is proposed in #13288
