### ISSUE TITLE
Array#flatMap iterator cannot return readonly array

### ISSUE THREAD

**Issue by rhys-vdw** [Microsoft/TypeScript#22685]
You can see that `flatMap` is not properly defined [here](https://github.com/Microsoft/TypeScript/blob/c48662c891ce810f5627a0f6a8594049cccceeb5/lib/lib.esnext.array.d.ts#L33-L36)

Should be (I think) something like:

```ts
interface ReadonlyArray<T> {
    // ...
    flatMap<U, This = undefined> (
        callback: (this: This, value: T, index: number, array: ReadonlyArray<T>) => U|ReadonlyArray<U>,
        thisArg?: This
    ): U[]
```

So callback should accept `ReadonlyArray<U>` as its return type (main issue). Additionally I noticed that the `array` callback argument has the incorrect type of `T[]` which means it can be modified by the callback despite being readonly.

**Code**

Sorry I couldn't demonstrate this on Playground because `flatMap` was undefined, but I believe this demonstrates the problem:

```ts
interface Foo {
    bars: ReadonlyArray<number>
}

var foos: ReadonlyArray<Foo>

var result = foos.flatMap(foo => foo.bars) // Error: property "push" is missing in type `ReadonlyArray<number>`
```

My real example:

![image](https://user-images.githubusercontent.com/822105/37574556-d332e0c0-2b75-11e8-8999-170de3eb07f6.png)

**Expected behavior:**

flat maps readonly arrays, creating a new array and not modifying the input array.

**Actual behavior:**
Error because `ReadonlyArray<T>` doesn't have property `push`.

**Related Issues:**

Couldn't find any.

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.
