### ISSUE TITLE
Weird inheritance that is valid Typescript

### ISSUE THREAD

**Issue by Frikki** [Microsoft/TypeScript#22684]
**TypeScript Version:**  2.7.2

**Search Terms:** inheritance interface extends class

**Code**

```ts
interface Foo {
    foo: () => void
}

class Bar implements Foo {
    foo() {}
}

interface Baz extends Bar {}

class Qux implements Baz {
    foo() {
        return ''
    }
}
```

**Expected behavior:**

`Qux` implementation of `foo` should error because it returns a `string` instead of `void` as declared in `Foo`

**Actual behavior:**

Is valid TypeScript.

**Playground Link:** https://www.typescriptlang.org/play/index.html#src=interface%20Foo%20%7B%0D%0A%20%20%20%20foo%3A%20()%20%3D%3E%20void%0D%0A%7D%0D%0A%0D%0Aclass%20Bar%20implements%20Foo%20%7B%0D%0A%20%20%20%20foo()%20%7B%7D%0D%0A%7D%0D%0A%0D%0Ainterface%20Baz%20extends%20Bar%20%7B%7D%0D%0A%0D%0Aclass%20Qux%20implements%20Baz%20%7B%0D%0A%20%20%20%20foo()%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20''%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
Search the FAQ for "void": https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-functions-returning-non-void-assignable-to-function-returning-void

**Comment by Frikki** [comment]
I figured that the culprit is in `Foo` where `foo: () => void`. If `void` is changed to `undefined`, the code errors as expected.
