### ISSUE TITLE
Tests for validity of all generated *.d.ts in bin

### ISSUE THREAD

**Issue by mihailik** [Microsoft/TypeScript#2269]
Generated declaration files should at least be compilable with no errors (see issue #2268 for example).

The simplest pragmatic way is to run compiler on a dummy TS file and a corresponding file.d.ts. If it doesn't crash, it's a pass.

**Comment by danquirk** [comment]
Could call this a suggestion but I think it's just a bug that we're not doing this kind of validation.

**Comment by mhegazy** [comment]
We already have a test for typescript.d.ts see https://github.com/Microsoft/TypeScript/blob/master/tests/cases/compiler/APISample_compile.ts

@mihailik feel free to add a test for typescript_internal as well.

**Comment by mhegazy** [comment]
PR #2692 removes the _internal files.
