### ISSUE TITLE
Intellisense hangs / stops working

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#22695]
_From @twistedinferno on March 5, 2018 17:39_

- VSCode Version: 1.20.1
- OS Version: Windows 10 64bit

Steps to Reproduce:

1. Work on react native javascript code for a few hours
2. Intellisense stops working (the 'Loading' tooltip shows of the intellisense but nothing else)

![image](https://user-images.githubusercontent.com/4139336/36983852-5c5a8862-208b-11e8-8294-5ecedbfd7bce.png)

Does this issue occur when all extensions are disabled?: Yes/No (usually it takes three hours of programming to encounter the error...programming react native with vs code without React Native Tools is almost impossible so I have kept that enabled but disabled everything else)

_(the last time it happened I was importing a couple of new libraries...possibly unrelated though)_

_Copied from original issue: Microsoft/vscode#45073_

**Comment by mjbvz** [comment]
_From @twistedinferno on March 5, 2018 21:30_

_(the last time it happened I created a new file but I didn't import any new libraries...again possibly unrelated to the error)_

**Comment by mjbvz** [comment]
A few questions:

- Does this happen for all projects you open, or just one specifically?
- Have you set a custom `typescript.tsdk` value in your workspace or user settings?

Can you also please try collecting the TypeScript server logs:

1. Add `"typescript.tsserver.log": "verbose"` to your user settings and restart VSCode.
2. Reproduce the issue
3. Back in the `TypeScript` section of the output panel, look for a `TSServer exited` message. Right after that message there should now be the path to a log printed. Open that log directory and look in the `tsserver.log` file

Look for errors, stack traces, or other suspicious info near the end of the logs. If you can share the logs I can try looking through them to see what is going on

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by mjbvz** [comment]
_From @glauberfc on March 12, 2018 19:16_

I'm having the same problem. 

- Does this happen for all projects you open, or just one specifically? **Yes**
- Have you set a custom typescript.tsdk value in your workspace or user settings? **No**
- TypeScript server logs:
>[Info  - 4:11:43 PM] Using tsserver from: c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib
[Info  - 4:11:45 PM] TSServer log file: C:\Users\gferr\AppData\Roaming\Code\logs\20180312T161137\vscode.typescript-language-features_1\tsserver-log-5XNkj3\tsserver.log
[Info  - 4:11:45 PM] Forking TSServer
PATH: C:\Program Files (x86)\Common Files\Intel\Shared Files\cpp\bin\Intel64;C:\Python27\;C:\Python27\Scripts;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\ProgramData\chocolatey\bin;C:\Program Files\nodejs\;C:\Program Files\Java\jdk1.8.0_144\bin;C:\Android\android-sdk\tools;C:\Android\android-sdk\platform-tools;C:\Program Files (x86)\Yarn\bin;C:\Program Files\Git\cmd;C:\Users\gferr\AppData\Local\Microsoft\WindowsApps;C:\Users\gferr\AppData\Roaming\npm;C:\Users\gferr\AppData\Local\Yarn\bin;;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\Oracle\VirtualBox
[Info  - 4:11:45 PM] Started TSServer

**Comment by mjbvz** [comment]
_From @Wedvich on March 13, 2018 16:30_

This might be related to #43427 - adding `"typescript.quickSuggestionsForPaths": false` to my user settings worked for me as a temporary workaround.

**Comment by mjbvz** [comment]
_From @glauberfc on March 13, 2018 18:9_

[tsserver.log](https://github.com/Microsoft/vscode/files/1808126/tsserver.log)

**Comment by mjbvz** [comment]
@andy-ms I looked through the logs but nothing stood out. We've been seeing a few reports of "intellisense stops working" issues in the latest VS Code (using TS 2.7.2)

**Comment by andy-ms** [comment]
Looks like we may be updating the project too much -- probably related to #22624? @sheetalkamat 
(Also, I noticed there is 1 file open, but 559 files in the project -- we may be pulling in too much.)

@glauberfc @Wedvich Could you also test with `typescript@next`?

**Comment by Wedvich** [comment]
Sure, will try with that!

It might be circumstantial, but the problem was eliminated completely for me by setting `"typescript.quickSuggestionsForPaths": false` in my user config. I've had both the problem and the effect of that fix on two separate Win 10 and one OS X system now, all running the 1.21.0 version of VSCode.

**Comment by twistedinferno** [comment]
Hi


Does this happen for all projects you open, or just one specifically?
 - Yes, all projects, react native and react

Have you set a custom typescript.tsdk value in your workspace or user settings?
 - I don't use typescript

TypeScript server logs:
 - I don't use typescript

**Comment by Wedvich** [comment]
@twistedinferno Code uses TypeScript (more specifically TSServer) to provide the quick-info/completion, so I think what @andy-ms means is telling Code to use an upcoming version of TypeScript instead of the built-in one. That way we can test if the problems we have come from TypeScript itself, but have been fixed in the next version. Just do this:
1. run `npm i -g typescript@next`
2. Set `typescript.tsdk` in your user config to `C:\Program Files\nodejs\node_modules\typescript\lib` (or whatever path you have Node installed in if it's not the default).

Also, the `tsserver.log` contains the logs produced by TSServer in Code, so it could potentially provide diagnostic information about what's going wrong.

**Comment by twistedinferno** [comment]
Thanks Wedvich, my version of vs code updated to 1.21 and I have had just one instance of this bug since.  I'll keep an eye on things and update my version of typescript if it occurs again but it seems to be a lot more stable now.  I'll updated you again :-)

**Comment by byteskw** [comment]
me to, im using react native for my vscode, after 2 minutes - 10 minutes always infinite loading my intellisense vscode,

please fix this

**Comment by mhegazy** [comment]
@byteskw can you share your tsserver log?

**Comment by sheetalkamat** [comment]
@byteskw also can you try typescript@next as well. Having the logs with typescript@next will help us eliminate any issues that we have already fixed. Thanks.
