### ISSUE TITLE
Quick info shows uninstantiated type of signature when the arguments are incorrect

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#22699]
_From @yo1dog on March 15, 2018 20:25_

- VSCode Version: 1.21.1
- OS Version: 10.10.5

When using JSDocs to describe a function using `@template`, Intellisence does not correctly infer the template type if one or more of the given parameter values do not match the function's signature.

## Case 1
All given parameter values have types that match `doSomething`'s signature.

```javascript
/**
 * @template T
 * @param {T} item
 * @param {string} str
 * @return {T}
 */
function doSomething(item, str) {
  return item;
}

doSomething(Buffer.alloc(1), 'hello');
```

Intellisence output when hovering over `doSomething(...)`:
```
function doSomething<Buffer>(item: Buffer, str: string): Buffer
```

Works as expected. Intellisence knows the template type is `Buffer`.

## Case 2
A `number` is given for the `str` parameter instead of a `string`.

```javascript
/**
 * @template T
 * @param {T} item
 * @param {string} str
 * @return {T}
 */
function doSomething(item, str) {
  return item;
}

doSomething(Buffer.alloc(1), 123);
```

Intellisence output when hovering over `doSomething(...)`:
```
function doSomething<T>(item: T, str: string): T
```

Does not work as expected. Expected same result as Case 1.

_Copied from original issue: Microsoft/vscode#45913_

**Comment by sandersn** [comment]
This is how Typescript behaves today too:

```ts
declare function f<T>(item: T, s: string): T;
f(Buffer.alloc(1), 123);
```

Shows `f<T>(t: T, s: string): T`

If we change this, we should change it for both Typescript and Javascript.

**Comment by sandersn** [comment]
I like the current behaviour in Typescript, because it's a signal that I have an error in my program. However, I can understand that it would be unexpected in Javascript, where you don't think about types all the time.

**Comment by yo1dog** [comment]
Seems to me incorrect argument types and inferring templated types are two separate considerations. In TypeScript (and JavaScript if you enable type checking), incorrect argument types are already handled/reported, correct?

**Comment by mhegazy** [comment]
> Seems to me incorrect argument types and inferring templated types are two separate considerations.

they are not really. if a function has multiple overloads whether the inferred types match the constraints or not does matter. the general case here is that the compiler can not pick an overload correctly, and an error has been reported, it will not try to do partial inference/application for these, since really there is no reason to guarantee that whatever that partial application it makes is correct.

**Comment by yo1dog** [comment]
I think we are saying the same thing: It makes sense from a TypeScript point of view that you would have to solve the type mismatch error before you would expect intellisence to infer/work fully.

However, in JavaScript there is no type mismatch error. The result is intellisence showing the uninstantiated type without the context of the type mismatch which may not be obvious. Especially with the prevalence of loose/undefined duck-typing in JavaScript as mentioned by @sandersn.

As you explained, it makes sense that partial inference is not supported. The only solution I can think of is showing the reason why inference failed to give JavaScript users some context.

Thanks for considering.

**Comment by yo1dog** [comment]
This issue may be related?: #22655

**Comment by mhegazy** [comment]
if you are not trust the JSDoc signature about the second parameter `string`, why should you trust it about the first `T`? what if the second parameter was `string & T`? or `Array<T>` should `T` still be inferred from eh first argument? what if it was `T, string, U`, should `T` be inferred but not `U`, or not? what if the return type of the function was inferred from the code, and it depends on the type of the second parameter, should the return type still be `string`?
it is a guessing game when it is ok and when it is not. the compiler just says this is not right, and bails out. and i think this is a predictable behavior at least.

**Comment by yo1dog** [comment]
Indeed. I am not disagreeing with you. I am merely pointing out that users sometimes lack the context to understand why the type was unable to be inferred/why the compiler bailed and it may not always be obvious. Hence my suggestion to present the reason to the user. Not sure how feasible that is.
