### ISSUE TITLE
Navigator.getGamepads() can return array with null values. lib.es6.d.ts

### ISSUE THREAD

**Issue by oyvindjam** [Microsoft/TypeScript#22700]
**TypeScript Version:**  2.7.2

**Search Terms:** 
getGamepads, Gamepad, lib.es6.d.ts

**Description**
Returned array from navigator.getGamepads() can contain null values as specified in
https://www.w3.org/TR/gamepad/#navigator-interface-extension

Method is currently defined as getGamepads(): Gamepad[] in the Navigator interface,

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by a-tarasyuk** [comment]
@mhegazy Seems type for `getGamepads` methods is correct - [lib.es6.d.ts#L15167](https://github.com/Microsoft/TypeScript/blob/master/lib/lib.es6.d.ts#L15167). 

```typescript
getGamepads(): (Gamepad | null)[];
```

**Comment by mhegazy** [comment]
thanks. closing.
