### ISSUE TITLE
Renaming node_modules into existence doesn't invalidate module resolution in watch mode

### ISSUE THREAD

**Issue by RyanCavanaugh** [Microsoft/TypeScript#22712]
**TypeScript Version:** 2.8.0-dev.20180318

**Search Terms:** node_modules watch rename

**Code**

```ts
// a.ts
import * as q from 'qqq';

// node_modules2/@types/qqq/index.d.ts
export { }
```

Run `tsc -w a.ts`:
```
21:35:19 - Starting compilation in watch mode...
a.ts(1,20): error TS2307: Cannot find module 'qqq'.
21:35:21 - Compilation complete. Watching for file changes.
```
In another console, rename `node_modules2` to `node_modules`:
```
21:35:44 - File change detected. Starting incremental compilation...
a.ts(1,20): error TS2307: Cannot find module 'qqq'.
21:35:44 - Compilation complete. Watching for file changes.
```
Cancel tsc and run it again, no errors:
```
21:36:08 - Starting compilation in watch mode...
21:36:09 - Compilation complete. Watching for file changes.
```

Expected behavior: The triggered watch mode rebuild should find the new modules. This works for any subfolder of `node_modules` but not for the folder itself.

**Comment by RyanCavanaugh** [comment]
@sheetalkamat I can't find the codepath that makes the other cases work differently from this one. Pointers?

**Comment by sheetalkamat** [comment]
It is this line: https://github.com/Microsoft/TypeScript/blob/master/src/compiler/resolutionCache.ts#L591 we need to also check if the watch is invoked for node_modules or node_modules/@types directory itself in addition to if it is for fileOrDirectory in node_modules or node_modules/@types
