### ISSUE TITLE
Emit destructuring patterns in 'for...in' statements for ES3/5

### ISSUE THREAD

**Issue by JsonFreeman** [microsoft/TypeScript#2272]
The following is allowed by the ES6 grammar:

``` ts
for (var [a, b] in []) { }
```

This results in a type check error, because it doesn't make sense to destructure a string key. But it should still emit correctly downlevel. Right now we emit:

``` js
for (var _a = void 0, a = _a[0], b = _a[1] in []) { }
```

which is incorrect.

**Comment by mhegazy** [comment]
so what is the proposed emit?

**Comment by JsonFreeman** [comment]
Similar to 'for...of', but 'for...in'-ified:
```js
for (var _a in []) {
    var a = _a[0], b = _a[1];
}
```

**Comment by RyanCavanaugh** [comment]
Doesn't seem like anyone has noticed this
