### ISSUE TITLE
convert map/set into array using spread operator does not work in TS Playground

### ISSUE THREAD

**Issue by marcelh-gh** [Microsoft/TypeScript#22734]
This works for the compiler (V 2.7.2) but not in the Playground...

```
const testMap = new Map<String, String>();
const arrayFromMap = [...testMap];
```

`Array.from(testMap)` works fine in the Playground...

It is the same issue for sets.

**Comment by andy-ms** [comment]
That's because it has a low `--target` setting. We could consider adding that as an option in the UI.

**Comment by marcelh-gh** [comment]
adding target selection as an option in the UI would be awesome :-)

And while at it, maybe also display the currently used TS version in the UI...
