### ISSUE TITLE
Organize Imports removes aliased imports that are in use.

### ISSUE THREAD

**Issue by chriseppstein** [Microsoft/TypeScript#22743]
**TypeScript Version:**  2.8.0-rc, 2.8.0-insiders.20180320

**VS Code Version:**
```
Version 1.22.0-insider (1.22.0-insider)
5be9e9e7eef715539efd5341fdbc8ec5840cfc56

2018-03-20T06:06:11.908Z
```

**Search Terms:** organize import imports remove alias

**Code**

```ts
import { Type as TSType } from "typescript";

export function isTSType(v: any): v is TSType {
  return !!v;
}
```

**Expected behavior:**

Running "TypeScript: Organize Imports" in VS Code makes no change to the import statements.

**Actual behavior:**

The import statement is removed.

**Work around:**

Remove `as <ident>`from the import statement and the import statement is left untouched by the "Organize Imports" command.

**Comment by mjbvz** [comment]
@andy-ms Thank you for the quick turn around. Can we please get this in TypeScript 2.8.2 as well since the bug potentially breaks code?

**Comment by andy-ms** [comment]
@mjbvz See #22804

**Comment by iosdev-republicofapps** [comment]
Hi, I'm seeing this issue still in VSCode 1.23.1 and I'm not using either Typescript or aliases.  For example in simple code like:
```
// VSCode erroneously removes this import and breaks my app with "Can't find variable: reducer" errors.  Every time I add the import and save, VSCode removes the import (and it should NOT as the import is provably needed).
import reducer from "./firebaseApi";

const allReducers = combineReducers({
  // import needed
  reducer,
});
```
I can confirm that this has nothing to do with ESLint or Prettier and the only remedy is to set
```
  "editor.codeActionsOnSave": {
    "source.organizeImports": false
  },
```
However I want organizeImports on in general - this is the only file that it's screwing up.  Any way to turn it off for just this file?

Is there an ETA on a fix?

Thanks!

**Comment by no-stack-dub-sack** [comment]
:point_up: never mind, just saw your issue on that repo as well

**Comment by andy-ms** [comment]
@iosdev-republicofapps That seems to work with `typescript@next` -- if you want this fixed right away try [using a newer TypeScript version](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions).
