### ISSUE TITLE
Can't extend overloaded constructor signatures to classes

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#22756]
**TypeScript Version:**  master

**Search Terms:** 

**Code**

```ts
interface A {
  new <T extends void>(): B<T>;
  new <T>(): B<T>;
}
declare var B: A;
interface B<T> {
}
class C<T> extends B<T> { }
```

**Expected behavior:**

pass

**Actual behavior:**

```
$ node built/local/tsc.js --noEmit index.ts
index.ts(8,22): error TS2344: Type 'T' does not satisfy the constraint 'void'.
```

**Playground Link:**  

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
Does this code even make sense? It feels like a correct error - assuming an instantiated property `T`, a `B<void>` is not assignable from a `B<{}>`, the latter of which is the assumed constraint in the absence of a declared one.

**Comment by falsandtru** [comment]
This is needed for #19633 and https://github.com/Microsoft/TypeScript/pull/21867#issuecomment-374854242 but the current compiler can't make this signature as a class.
