### ISSUE TITLE
Auto-imports should not be offered in non-module files

### ISSUE THREAD

**Issue by RyanCavanaugh** [Microsoft/TypeScript#22750]
**Code**
```
> npm init -y
> tsc --init
> npm install @types/jquery
> npm install @types/express
> code a.ts
```
Type
```
$.ajax();
ss
```
**Actual behavior:**

![image](https://user-images.githubusercontent.com/6685088/37687179-bf159190-2c57-11e8-9c66-3869b2e3be62.png)

**Expected behavior:**

We shouldn't offer auto imports in a global file (i.e. until there's at least one other import). This was really confusing for me - I was working in the TS codebase, selected a function name that looked like what I wanted, then got a screenfull of compiler errors when I tried to build because I had inadvertently changed the containing file into a module (thus breaking everything). Because the import appeared off-screen at the top of the file I had no idea what even happened until I ran `git diff`.

**Comment by DanielRosenwasser** [comment]
True, but this is really subtle and kind of sucks for the first-time user experience if you just wanted to write a module...

**Comment by DanielRosenwasser** [comment]
Idea: if you don't have modules set, we shouldn't provide import suggestions. If you do have modules set, **but** you use a UMD global, don't provide import suggestions.

**Comment by Kovensky** [comment]
How do you tell if an UMD global is actually being used? A lot of DT modules have `export as namespace` in them even though one may not actually be loading them as UMD and may be bundling them with webpack (without ProvidePlugin) instead.
