### ISSUE TITLE
Incorrect Parse for accessors in classes

### ISSUE THREAD

**Issue by rbuckton** [Microsoft/TypeScript#22757]
This was brought up in TC39 today:

```ts
class C {
  get
  x() {}
}
```

In the above example, `x` should be parsed as an accessor, but we parse `get` as a field and `x() {}` as a method. There is no `[no LineTerminator here]` restriction in the [grammar](https://tc39.github.io/ecma262/#prod-MethodDefinition).

Related Productions:
```grammarkdown
ClassElement[Yield, Await]: 
    `static` MethodDefinition[?Yield, ?Await]

MethodDefinition[Yield, Await]:
    `get` PropertyName[?Yield, ?Await] `(` `)` `{` FunctionBody[~Yield, ~Await] `}`
    `set` PropertyName[?Yield, ?Await] `(` PropertySetParameterList `)` `{` FunctionBody[~Yield, ~Await] `}`
```

Playground: http://www.typescriptlang.org/play/index.html#src=class%20C%20%7B%0D%0A%20%20%20%20get%0D%0A%20%20%20%20x()%20%7B%20%7D%0D%0A%7D

**Comment by bakkot** [comment]
Same issue with "static" and "get", but notably _not_ `async`, which does have the `[no LineTerminator here]` restriction.
