### ISSUE TITLE
String literal types from `typeof` is reduced to `string` when passing through a generic function that "boxes" the type

### ISSUE THREAD

**Issue by gipsy-king** [Microsoft/TypeScript#22758]
**TypeScript Version:**  2.7.2

**Search Terms:** string literal, typeof, generic, structuring, boxing

**Code**

```ts
type StringLiteral = 'A' | 'B';
const map = (genders: StringLiteral[]): { gender: StringLiteral }[] =>
    genders.map(gender => ({ gender }));
// OK

const CONST_A = 'A';
const CONST_B = 'B';
type StringLiteralFromTypeof = typeof CONST_A | typeof CONST_B;

// StringLiteral and StringLiteralFromTypeof have the same type, when you hover them.

const map_typeof_no_generics_struct = (gender: StringLiteralFromTypeof): { gender: StringLiteralFromTypeof } =>
    ({ gender });
// OK if we struct (or "box") but don't pass through a generic function

const map_typeof_map_struct = (genders: StringLiteralFromTypeof[]): { gender: StringLiteralFromTypeof }[] =>
    genders.map(gender => ({ gender }));
// Error: inferred type is { gender: string }[]

const map_typeof_map_nonstruct = (genders: StringLiteralFromTypeof[]): StringLiteralFromTypeof[] =>
    genders.map(gender => gender);
// OK: if not structured into object or array, the type is inferred correctly

const identity = <T>(v: T) => v;
const map_typeof_any_generic = (gender: StringLiteralFromTypeof): { gender: StringLiteralFromTypeof } =>
    identity({ gender });
// Error: inferred type is { gender: string }[]

const map_typeof_any_generic_nonstruct = (gender: StringLiteralFromTypeof): StringLiteralFromTypeof =>
    identity(gender);
// OK: if not structured into object or array, the type is inferred correctly
```

**Expected behavior:**
A string literal type that was constructed from `typeof someVar | ...` should behave the same as a string literal type defined from string values `'val' | ...`.

**Actual behavior:**
When both passing through a generic function, AND structuring or "boxing" the type into an object or array, then the type is reduced to `string`.

**Playground Link:** [link to see inferred types](https://www.typescriptlang.org/play/index.html#src=type%20StringLiteral%20%3D%20'A'%20%7C%20'B'%3B%0Aconst%20map%20%3D%20(genders%3A%20StringLiteral%5B%5D)%3A%20%7B%20gender%3A%20StringLiteral%20%7D%5B%5D%20%3D%3E%0A%20%20%20%20genders.map(gender%20%3D%3E%20(%7B%20gender%20%7D))%3B%0A%2F%2F%20OK%0A%0Aconst%20CONST_A%20%3D%20'A'%3B%0Aconst%20CONST_B%20%3D%20'B'%3B%0Atype%20StringLiteralFromTypeof%20%3D%20typeof%20CONST_A%20%7C%20typeof%20CONST_B%3B%0A%0Aconst%20map_typeof_no_generics_struct%20%3D%20(gender%3A%20StringLiteralFromTypeof)%3A%20%7B%20gender%3A%20StringLiteralFromTypeof%20%7D%20%3D%3E%0A%20%20%20%20(%7B%20gender%20%7D)%3B%0A%2F%2F%20OK%20if%20we%20struct%20(or%20%22box%22)%20but%20don't%20pass%20through%20a%20generic%20function%0A%0Aconst%20map_typeof_map_struct%20%3D%20(genders%3A%20StringLiteralFromTypeof%5B%5D)%3A%20%7B%20gender%3A%20StringLiteralFromTypeof%20%7D%5B%5D%20%3D%3E%0A%20%20%20%20genders.map(gender%20%3D%3E%20(%7B%20gender%20%7D))%3B%0A%2F%2F%20Error%3A%20inferred%20type%20is%20%7B%20gender%3A%20string%20%7D%5B%5D%0A%0Aconst%20map_typeof_map_nonstruct%20%3D%20(genders%3A%20StringLiteralFromTypeof%5B%5D)%3A%20StringLiteralFromTypeof%5B%5D%20%3D%3E%0A%20%20%20%20genders.map(gender%20%3D%3E%20gender)%3B%0A%2F%2F%20OK%3A%20if%20not%20structured%20into%20object%20or%20array%2C%20the%20type%20is%20inferred%20correctly%0A%0Aconst%20identity%20%3D%20%3CT%3E(v%3A%20T)%20%3D%3E%20v%3B%0Aconst%20map_typeof_any_generic%20%3D%20(gender%3A%20StringLiteralFromTypeof)%3A%20%7B%20gender%3A%20StringLiteralFromTypeof%20%7D%20%3D%3E%0A%20%20%20%20identity(%7B%20gender%20%7D)%3B%0A%2F%2F%20Error%3A%20inferred%20type%20is%20%7B%20gender%3A%20string%20%7D%5B%5D%0A%0Aconst%20map_typeof_any_generic_nonstruct%20%3D%20(gender%3A%20StringLiteralFromTypeof)%3A%20StringLiteralFromTypeof%20%3D%3E%0A%20%20%20%20identity(gender)%3B%0A%2F%2F%20OK%3A%20if%20not%20structured%20into%20object%20or%20array%2C%20the%20type%20is%20inferred%20correctly%0A)

**Related Issues:**
unknown

**Comment by RyanCavanaugh** [comment]
`StringLiteral` and `StringLiteralFromTypeof` are not identical, even though they have the same display text. See #22211
