### ISSUE TITLE
Invalid declaration emit for conditional type with 'infer'

### ISSUE THREAD

**Issue by yortus** [Microsoft/TypeScript#22755]
**TypeScript Version:**  2.8.0-rc

**Search Terms:** "invalid declaration emit", "declaration infer"

**Code**

```ts
// ========== tsc input ==========
// index.ts
// @declaration: true
export declare function foo<T>(obj: T): T extends () => infer P ? P : never;
export function bar<T>(obj: T) {
    return foo(obj);
}

// ========== tsc output ==========
// index.d.ts
export declare function foo<T>(obj: T): T extends () => infer P ? P : never;
export declare function bar<T>(obj: T): T extends () => P ? P : never;
```

**Expected behavior:**
In the emitted declaration file, `foo` and `bar` should have equivalent return type annotations.

**Actual behavior:**
The return type annotation for `bar` is missing the `infer` keyword, making the declaration invalid. Any TypeScript project consuming this declaration file will produce the error `"Cannot find name 'P'"`.

**Related Issues:**
- #21836 is similar but relates to Quick Info. The sample code there produces a correct declaration emit however.
- #22368 says it fixes #21836, so maybe it fixes this too?

**Comment by yortus** [comment]
@weswigham would #22368 fix this?

**Comment by weswigham** [comment]
It might, by chance, because I introduced an actual `InferType` type kind in that PR so I could distinguish the infer location from the use locations for type parameter lists.

**Comment by DanielRosenwasser** [comment]
Let's get a fix specifically for this first if we can, and then use #22368 if that gets pulled in.
