### ISSUE TITLE
Ref inference doesn't work when passing a callback function

### ISSUE THREAD

**Issue by methyl** [Microsoft/TypeScript#22761]
Not sure if that's by design, but there's a difference in ref inference behavior:

**Code**
```ts
class Example extends Component {
  notWorkingRef = el => {
    // el is implicit any
  }
  render() {
    return <div>
      <div ref={el => {/* el is properly inferred here */}} />
      <div ref={this.notWorkingRef} />
    </div>
  }
```

**Expected behavior:**
It should infer `notWorkingRef` parameter properly.

**Comment by AlCalzone** [comment]
I don't think `el` in the funciton definition should be inferred by the usage of the function somewhere else.

Consider this case (where notWorkingRef is unused):
```ts
class Example extends Component {
  notWorkingRef = el => {
    // which type should el have?
  }
  render() {
    return <div></div>
  }
```
In your case, `notWorkingRef` would change its signature depending on if it gets called or not.

**Comment by RyanCavanaugh** [comment]
We don't do this style of inference.

**Comment by methyl** [comment]
Makes perfect sense, just wanted to be sure. Thanks a ton!
