### ISSUE TITLE
Decorators Loosing this Reference

### ISSUE THREAD

**Issue by xdougx** [Microsoft/TypeScript#22763]
Hello,

Im trying to build a decorator like this

```typescript
export function Relational<T>(target: any, propertyKey: string, descriptor: TypedPropertyDescriptor<T>) {
  const set = descriptor.set;
  descriptor.set = function (value: any) {
      const type = Reflect.getMetadata('design:type', target, propertyKey);
      set(new type(value));
  }
}
```

I have this class implemented:

```typescript
export class MyComponent {
  // some logic here
}

export class MyClass {
  private _kind;

  @Relational
  @Reflect.metadata('design:type', MyComponent)
  set kind(value: Component) {  this._kind = value; }
  get kind() { return this._kind; }
}

```

But when i run this code im getting this error:

```
TypeError: undefined is not an object (evaluating 'this._kind = value')
```

Using the debugger this is `undefined`, is this a expected behavior?

Im following a Decorator example on the cookbook.

**Comment by ajafff** [comment]
That's just how JavaScript `this` works. Either you call it as a method and get `this` set to the object the method was called on, or you call it as function and `this` is `undefined` or the global object.

You need to explicitly pass the `this`-reference to the setter:

```ts
set.call(this, new type(value));
```

**Comment by xdougx** [comment]
But if i just pass this on this `set.call(this, new type(value))`

`this` in this context is the `function` context, the function doesnt know what is _kind.

need to access the current instance of the object that im working in.

is that possible?

**Comment by ajafff** [comment]
your `function (value: any)` is assigned to the object instance. Therefore it has the correct `this` reference during execution.

Did you try my suggestion?

**Comment by AlCalzone** [comment]
> need to access the current instance of the object that im working in.

Does the `target` variable work? I think that one should reference the object you're working in.

**Comment by xdougx** [comment]
Hello again, i think i could do the decorators following your help

```
import "reflect-metadata";

export function Relational() {
  return function(target: Object, propertyKey: string, descriptor: PropertyDescriptor) {
    let type = Reflect.getMetadata("type", target, propertyKey);

    descriptor.get = function(this: any) {
      return this[`_${propertyKey}`];
    }

    descriptor.set = function(this: any, value: any) {
      this[`_${propertyKey}`] = new type(value);
    }
  }
}

export class Bar extends Base {
  public some: string;
}

export class Foo extends Base{
  private _bar: Bar;

  @Relational()
  @Reflect.metadata('type', Bar)
  set bar(b: any) {  }

}

```
I think that was what @ajafff was talking about the this on the function!

Thanks for the help guys!
