### ISSUE TITLE
`Type must have a '[Symbol.iterator]()' method` error for `...x` where `x: T[]` with `"target": "es2018"`.

### ISSUE THREAD

**Issue by earshinov** [Microsoft/TypeScript#22768]
**TypeScript Version:**  2.8.0-dev.20180321

**Search Terms:** Symbol.Iterator, compilerOptions, compilerOptions.lib, es6, es2018, default, lib

**Code**

```ts
(function() {
    var a = [4, 5, 6];
    var b = [1, 2, 3];
    a.push(...b);
})();
```

tsconfig.json:
```json
{
    "compilerOptions": {
        "target": "es2018"
    }
}
```

**Expected behavior:**
No errors

**Actual behavior:**
```
src/index.ts(4,15): error TS2488: Type must have a '[Symbol.iterator]()' method that returns an iterator.
```

No errors when compiled with `"target": "es6"` in `tsconfig.json`

**Playground Link:**
The issue is not reproducible in the playground as it does not take a `tsconfig`.

**Related Issues:**
None as far as I know.

**Comment by earshinov** [comment]
Presumably, the defaults for `lib` described on the [Compiler Options][] page do not work for `"es2018"`.  

When I explicitly configure `"lib": [ "dom", "es6", "dom.iterable", "scripthost" ]` in `tsconfig.json`, the code compiles without any errors.

[Compiler Options]: https://www.typescriptlang.org/docs/handbook/compiler-options.html

**Comment by DanielRosenwasser** [comment]
You'll want to use `--downlevelIteration`.

**Comment by mhegazy** [comment]
`--target es2018` is not supported yet. it is tracked by https://github.com/Microsoft/TypeScript/issues/20463.

So the closest you can get to this is `--target es2017 --lib es2018,dom,dom.iterable`

**Comment by earshinov** [comment]
@mhegazy Thank you for the information. I guess this ticket should be left open in order to check if everything works when `--es2018` support is complete.

**Comment by mhegazy** [comment]
We already have one issue tracking it in #20463. ideally we would keep one ticket per issue.

**Comment by earshinov** [comment]
OK, closing then. For now we switched to `es6` instead of `es2018`.
