### ISSUE TITLE
Pinned comments aren't always emitted

### ISSUE THREAD

**Issue by CyrusNajmabadi** [Microsoft/TypeScript#2277]
Javascript tooling convention is that ```/*!   */``` are kept when converting code (even if minifying/stripping comments).  We have some small support for this, but it's very incomplete.  Fixing this is a fairly trivial code change.  Specifically, we just need to fix out top level emit function to always emit pinned comments if they're there.  However, this will likely come with an unfortunate perf hit.  It means we will need to check all nodes to see if they have pinned comments.  

Note: this issue has been reported by externals (including F12).  I think we will need to fix this.  However, that does mean living with a emitter perf hit.

**Comment by DickvdBrink** [comment]
Also, see #1851 which is kinda the same
