### ISSUE TITLE
Wrong type validation?

### ISSUE THREAD

**Issue by pankleks** [Microsoft/TypeScript#22786]
```typescript
let state: "new" | "ready" = "new";

if (state !== "ready") {
}
```

`if` statement gives me `Operator '!==' cannot be applied to types '"new"' and '"ready"'.`

http://www.typescriptlang.org/play/#src=let%20state%3A%20%22new%22%20%7C%20%22ready%22%20%3D%20%22new%22%3B%0D%0A%0D%0Aif%20(state%20!%3D%3D%20%22ready%22)%20%7B%0D%0A%0D%0A%7D

TS 2.7.2

**Comment by jack-williams** [comment]
TypeScript see's the initialiser of `state` and determines its type to be `"new"`, not a union `"new" | "ready"`. In such a situation the inequality test is not-allowed.

If TypeScript does not know the initialiser then the code is accepted: 
```ts
let state!: "new" | "ready";

if (state !== "ready") {
}
```

**Comment by pankleks** [comment]
hmm ... but exact type is given explicitly so why TS gets type from initializing value?

**Comment by j-oliveras** [comment]
Typescript knows that you assigned a value and you don't change it. It just warns that the condition has no much sense because is always `true`.

The next example has no errors although the first `if` never change the value of `state`:
```ts
let state: "new" | "ready" = "new";

if (Math.random() > 2) {
    // Its impossible because random return values between zero (included) and one (excluded), but typescript don't know it.
    state = "ready";
}

if (state !== "ready") {

}
```

**Comment by pankleks** [comment]
ok but what about this (it gives an error):

```ts
let state: "new" | "ready" = "new";

foo();

if (state !== "ready") {
}

function foo() {
    state = "ready";
}
```

**Comment by andy-ms** [comment]
Can also use `"new" as "new" | "ready"` to really change the type of the expression.

**Comment by kpdonn** [comment]
@pankleks Check out #9998, they talk about your `foo()` example plus a whole lot of other scenarios in that issue.
