### ISSUE TITLE
New Website Logo: qmBase

### ISSUE THREAD

**Issue by dieckhoefer** [Microsoft/TypeScript#22783]
Please fill the following out:

- Name: qmBase
- Homepage url: http://www.qmbase.com
- Brand Guidelines/Licensing: http://www.qmbase.com/en/logo-usage/
- Logo: (svg if possible, pngs over 500x200px with transparent backgrounds are also acceptable)
![left_logo_qmbase_cmyk](https://user-images.githubusercontent.com/36725675/37758319-14ce1ba8-2db0-11e8-928e-63cc07c4c0ff.png)

> Example:
>
> Name: Microsoft
> Homepage url: https://microsoft.com
> Brand Guidelines/Licensing: https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks/usage/logo.aspx
> Logo: https://news.microsoft.com/microsoft-news-center-photos/msft_logo_rgb_c-gray/

**Comment by mhegazy** [comment]
Thanks. Added to the site. Should be live next week.
