### ISSUE TITLE
[2.8.0-rc] Mixins don't recognize static method from parent class

### ISSUE THREAD

**Issue by SamuraiJack** [Microsoft/TypeScript#22788]
When declaring a mixin, one can provide a "default" parent class to inherit from, using the type argument for the "Constructable" type. When this is done, TypeScript correctly finds the normal methods from the parent class, however it can not find the static methods: 

```typescript
export type Constructable<T = {}> = new (...args : any[]) => T

class Base {
    static someStaticMethod() : number {
        return 1
    }

    someInstanceMethod() : number {
        return 1
    }
}


const Mixin = <T extends Constructable<Base>>(base : T) => class Some1 extends base {
    static someStaticMethod () {
        return super.someStaticMethod() + 1   // !!! <----- compiler error here
    }

    someInstanceMethod () {
        return super.someInstanceMethod() + 1   // !!! <----- this compiles fine
    }
}

```

**Comment by SamuraiJack** [comment]
Hm.. Can you please provide an example how to do that?

**Comment by SamuraiJack** [comment]
The `export type Constructable<T = {}> = (new (...args : any[]) => T) & T` attempt does not seem to work..

**Comment by cspotcode** [comment]
@SamuraiJack In Mixin1, the constraint on `T` does not require `base` to have any static methods.  Therefore compiler error.

In Mixin2, you are calling `Mixin1` explicitly.  This means `Some1` extends from the return value of `Mixin1`, which implements the static method.  Your `T` constraint is not really involved.

**Comment by cspotcode** [comment]
@SamuraiJack 

> `T` is a constructor function of `Base`

Correct, and `Base` is a type that describes *instances* of a class, which means the type `T` does not contain any information about static methods.  So your generic constraint `Constructor<T>` doesn't make any guarantees about static methods.

There's a big difference between `Base` and `typeof Base`.

**Comment by SamuraiJack** [comment]
@cspotcode Ok, I think I understand it vaguely. Any idea how to express this static methods inheritance in types?

**Comment by cspotcode** [comment]
@SamuraiJack Does this work for you?

https://github.com/cspotcode/typescript-toolbelt/blob/master/mixins-with-static-methods.ts

https://github.com/Microsoft/TypeScript/issues/22431#issuecomment-376550388

**Comment by SamuraiJack** [comment]
@cspotcode Oh, looks interesting, thanks! It seems to work, the mixin declaration becomes a bit cluttered though.

**Comment by SamuraiJack** [comment]
@cspotcode Thanks for the inspiration, in fact, just changing the mixin's generic parameter to `typeof Base` seems to be enough:

```typescript
export type Constructable<T = {}> = new (...args : any[]) => T

class Base {
    constructor(...args : any[]) {
    }
    static someStaticMethod() : number {
        return 1
    }
    someInstanceMethod() : number {
        return 1
    }
}


const Mixin1 = <T extends typeof Base>(base : T) => class Some1 extends base {
    static someStaticMethod () : number {
        return 1
        // return super.someStaticMethod() + 1  
    }
    someInstanceMethod () {
        return super.someInstanceMethod() + 1
    }
}

const Mixin2 = <T extends typeof Base>(base : T) => class Some1 extends Mixin1<typeof Base>(base) {
    static someStaticMethod () {
        return super.someStaticMethod() + 1    
    }
    someInstanceMethod () {
        return super.someInstanceMethod() + 1
    }
}
```

In your example the `Foo` class is lacking of generic constructor `constructor(...args : any[])` that's why more magic is needed. It can also be reduced to:
```typescript
const MyMixin = <C extends typeof Foo>(Base: C) => class MyMixin extends (Base as typeof Foo) {
    static mixinStatic() {
        super.staticMethod()
    }
}

```

I guess, this should be a new "default" mixins declaration for the case, when one assumes some specific base class. Deserves a blog post :)

**Comment by SamuraiJack** [comment]
But, I've tried to apply the change `Constructable <-> typeof Base` on my existing codebase and it does not work well, probably because of #22824. Or at least it will require significant effort to cleanup all type errors. So I'll postpone the switch to the new notation until #22824 is resolved.

**Comment by cspotcode** [comment]
@samuraijack that's why my workaround uses two generic declarations and a nested function within the mixin function.  I believe it should workaround that issue, right?

But yeah it's more syntax.

**Comment by SamuraiJack** [comment]
Could not check, because it would have been too cumbersome to replace all mixins declarations (the `Constructable <-> typeof Base` change was merely a regexp search/replace) . Now waiting for #22824 for further experiments.
