### ISSUE TITLE
typescript@2.8.0-dev.20180322 shows no errors in VS Code

### ISSUE THREAD

**Issue by kpdonn** [Microsoft/TypeScript#22784]
**TypeScript Version:**  2.8.0-dev.20180322
**VS Code Version:** 1.21.1

Typescript does not seem to be sending VS Code information about compile errors in the latest build. I confirmed this after restarting VS Code and testing with a clean project. I'm reproducing it with just
```ts
const a: string = 123; // should have an error, none shows up in VS Code
```
but anything that should result in a compiler error reproduces it. Running `tsc` from the command line shows a compile error as expected so it's only in VS Code that it doesn't seem to work. It's also specific to today's release, `2.8.0-dev.20180321` from yesterday works as expected.

I created a gist of my VS Code logs from tsserver starting up with `typescript.tsserver.trace` set to `verbose`:

Here is the log where it doesn't work: [Link](https://gist.github.com/kpdonn/ea8ab27a890d44847c8e94c187a136dd#file-a-_-problem-log-typescript-2-8-0-dev-20180322)

For comparison here is the equivalent log from `2.8.0-dev.20180321` where it works: [Link](https://gist.github.com/kpdonn/ea8ab27a890d44847c8e94c187a136dd#file-z-_-good-log-typescript-2-8-0-dev-20180321)

**Comment by mhegazy** [comment]
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/22790, should be fixed by https://github.com/Microsoft/TypeScript/pull/22791

**Comment by kpdonn** [comment]
👍 That’s actually a duplicate of this but no difference 🙂
