### ISSUE TITLE
type assertion operator !

### ISSUE THREAD

**Issue by fonsecapontes** [Microsoft/TypeScript#22794]
**TypeScript Version:**  2.7.0

**Code**
let name: string | null
console.log(name!.charAt(0) + ' , welcome');

**Expected behavior:**
output: ', welcome'

**Actual behavior:**
Cannot read property 'charAt' of undefined

**Comment by mhegazy** [comment]
The null assertion operator does not have any runtime impact. it is similar to you casting to `<string>`.

**Comment by fonsecapontes** [comment]
I'm sorry, I forget the most important information, the operator ! rsrs

I edit the issue to `console.log(name!.charAt(0) + ' , welcome');`

**Comment by fonsecapontes** [comment]
If I undestanded correct, this works like null-conditional in c#, correct?

If the variable was null, it's ignored and the output are what be in after
