### ISSUE TITLE
Handbook section on typescriptlang.org is out of date

### ISSUE THREAD

**Issue by marcind** [Microsoft/TypeScript#2279]
Looks like http://typescriptlang.org/handbook is falling behind the additions to the language. I've been reviewing the additions on https://github.com/Microsoft/TypeScript/wiki/Roadmap and nothing that's been added in 1.3 or later is included.

The roadmap is a good starting place but the links to the feature pull requests are not a good resource to learn the features since the noise ratio related to the pull request review activity is too high.

To make things more confusing the github wiki for this project also has content from the handbook. Which version is authoritative?

Is there a way the content could be opened up to external contributions so the documentation gap could be closed?

**Comment by danquirk** [comment]
The whole wiki is here https://github.com/Microsoft/TypeScript-wiki for the purposes of providing contributions/updates. The handbook does need to be updated too.

**Comment by DanielRosenwasser** [comment]
The handbook can now receive PRs at https://github.com/Microsoft/TypeScript-Handbook

**Comment by danquirk** [comment]
And issues there are tracking the update work needed so I'll close this.
