### ISSUE TITLE
Casting to Partial<x> seems to be errorful

### ISSUE THREAD

**Issue by ORESoftware** [Microsoft/TypeScript#22806]
I have this:

```js
export interface HavenData {
  timeoutAmount: number;
  throwSync?: boolean;
  timeoutThrow: boolean;
  promiseThrow: boolean;
}

 const qs = {timeout: Math.ceil(30 * Math.random())} as Partial<HavenData>;
```

shouldn't that be an error since `timeout` is not a member of the `HavenData` interface? I am not seeing a problem in my IDE.

**Comment by DanielRosenwasser** [comment]
Type assertions are meant to be as lenient as possible, so excess property errors won't occur; that means you're almost always able to use a type assertion with something that's all-optional.

**Comment by DanielRosenwasser** [comment]
I feel like @RyanCavanaugh might have opinions about this though.

**Comment by ORESoftware** [comment]
I was thinking that this was like "F you, just do what I want":

```js
const qs = <Partial<HavenData>>{timeout: Math.ceil(30 * Math.random())};
```

but that this was more like "please complain if the cast will likely not work":

```js
const qs = {timeout: Math.ceil(30 * Math.random())} as Partial<HavenData>;
```

**Comment by DanielRosenwasser** [comment]
Nope, the two are semantically equivalent; `as` was introduced because of parsing problems related to JSX.

**Comment by RyanCavanaugh** [comment]
I'm vaguely surprised this isn't an error due to `Partial<T>` being a weak type. Did we carve out something specific that makes this work?

@DanielRosenwasser What is the proposal here?

**Comment by RyanCavanaugh** [comment]
@DanielRosenwasser ping on the above question
