### ISSUE TITLE
Conditional type evaluation is stopping at the first possible branch

### ISSUE THREAD

**Issue by zajrik** [Microsoft/TypeScript#22811]
**TypeScript Version:**  2.8.0-rc

**Search Terms:** conditional types

**Code**

```ts
export type RequestResponse<T> =
	T extends IGetRolesRequest ? IGetRolesResponse :
	T extends IGetSettingsRequest ? IGetSettingsResponse :
	T extends ISetSettingsRequest ? ISetSettingsResponse :
	T extends IHasPermsRequest ? IHasPermsResponse :
	object;
```

**Expected behavior:**
When given the appropriate request interface, the matching response interface should be the expected type.
For example: `RequestResponse<IGetSettingsRequest>` should return `IGetSettingsResponse`

**Actual behavior:**
Every interface given to `RequestResponse` is having the expected response type as `IGetRolesResponse`
Further evidenced here:
![image](https://user-images.githubusercontent.com/10369802/37800417-b51f1162-2df0-11e8-8b7c-f9e3ff2cfc0b.png)
![image](https://user-images.githubusercontent.com/10369802/37800508-fcfe9782-2df0-11e8-8eba-6d575e25141b.png)

**Comment by DanielRosenwasser** [comment]
What do your interfaces look like?

**Comment by zajrik** [comment]
Oh shoot, now that you mention it, most of them contain the same structure or at least one shared field, with the name only really existing for grokking purposes. I see now why this is not working. Thanks for the inadvertent hint.

**Comment by zajrik** [comment]
Wish we could do like
```ts
type Foo<T> = T is Bar ? Baz : Bar;
```
for absolute type conditions, rather than structural comparisons

**Comment by zajrik** [comment]
I was able to come up with a solution that still allows me to use conditional types to map my request interfaces to their associated response interface. By creating a base interface
```ts
export interface IRequest<T>
{
    identifier?: T;
}
```
I am able to then have each request interface contain a unique identifier, differentiating them structurally from the other interfaces, even if they technically contain all the same fields.
```ts
export interface IGetSettingsRequest extends IRequest<'IGetSettingsRequest'> { ... }
```

It's working great. 👌
