### ISSUE TITLE
Arrow functions require no line terminator before arrow `=>` token

### ISSUE THREAD

**Issue by caitp** [Microsoft/TypeScript#2282]
I just noticed this today while working on implementing rest parameters in arrow functions in v8. v8 and SpiderMonkey are both getting this wrong right now, but Traceur and Babel both get this right.

It's probably a pretty simple fix

**Comment by danquirk** [comment]
Do we need/want to enforce the same restriction in TypeScript or just ensure that the ES6 emit for arrow functions doesn't preserve such newlines? It would be a breaking change to disallow this now, we've been allowing this for ES5:

```ts
var x = () =>
	{}
```
emits
```js
var x = function () {
};
```

**Comment by caitp** [comment]
I should have clarified:

```js
var x = (a)
  => 1
```

should translate to:

```js
var x = (a);
  => 1; // syntax error, unexpected `=>`
```

**Comment by caitp** [comment]
I think it's unlikely anyone is using this syntax, since it's much harder to read, but if it breaks apps then it might not be worth fixing.

**Comment by DanielRosenwasser** [comment]
@CyrusNajmabadi and I just discussed this offline; apparently we've sort of known about this, but haven't committed to it since it's a breaking change.

That said, he and I would prefer to take the breaking change.
