### ISSUE TITLE
De-structuring arguments array generates invalid ES5 code

### ISSUE THREAD

**Issue by jdmnd** [Microsoft/TypeScript#22829]
**TypeScript Version:**  2.9.0-dev.20180323, 2.7.2

**Search Terms:** arguments.slice destructuring allowJs

**Code**
`test.js:`
```js
function f() {
        const [first, ...rest] = arguments;
}
```
```sh
$ mkdir out
$ tsc test.js --allowJs --outDir out/
```

**Expected behavior:**
ES5 code is generated where `arguments` is converted to an array, then sliced.

**Actual behavior:**
No errors or warnings.
`out/test.js:`
```js
function f() {
    var first = arguments[0], rest = arguments.slice(1);
}
```
Problem: `slice` is not a method on `arguments`.

**Playground Link:**  
http://www.typescriptlang.org/play/#src=function%20f()%20%7B%0D%0A%20%20%20%20const%20%5Bfirst%2C%20...rest%5D%20%3D%20arguments%3B%0D%0A%7D

**Related Issues:**
https://github.com/Microsoft/TypeScript/issues/3219

**Comment by andy-ms** [comment]
That's a compile error though - `Type 'IArguments' is not an array type.`

**Comment by jdmnd** [comment]
> That's a compile error though

Note however that this is compiled with the `allowJs` option, and that the input is valid javascript.

**Comment by andy-ms** [comment]
That's true, but we don't guarantee that transpilation will always work in the presence of compile errors. Similarly, `for (const key of new Map([["1", "2"]]).keys()) { console.log(key); }` will output nothing when transpiled, because you get a compile error `Type 'IterableIterator<string>' is not an array type or a string type.`.

**Comment by jdmnd** [comment]
> That's true, but we don't guarantee that transpilation will always work in the presence of compile errors.

I find that a little troubling if there are no warnings generated for js code. 

Thanks for your response nonetheless – I'll close given that this is apparently acceptable behaviour.
