### ISSUE TITLE
Parameterized type shouldn't "force" type widening

### ISSUE THREAD

**Issue by laughinghan** [Microsoft/TypeScript#22839]
**TypeScript Version:**  2.7

**Search Terms:** widening, parameterized, parameters, generic

**Code**

```ts
interface Face {
    type: 'face';
}
function foo<T>(x: T) {
    return x;
}



function works(): Face {
    return { type: 'face' };
}

function doesntWork(): Face {
    return foo({ type: 'face' });
    // ^ typechecker errors here with:
    // Type '{ type: string; }' is not assignable to type 'Face'.
    //   Types of property 'type' are incompatible.
    //     Type 'string' is not assignable to type '"face"'.
}

function workaround(): Face {
    return foo({ type: 'face' as 'face' });
}
```

**Expected behavior:**
`doesntWork()` should pass type-checking

**Actual behavior:**
Typechecker error in `doesntWork()`

[**Playground Link**](http://www.typescriptlang.org/play/#src=interface%20Face%20%7B%0D%0A%20%20%20%20type%3A%20'face'%3B%0D%0A%7D%0D%0Afunction%20foo%3CT%3E(x%3A%20T)%20%7B%0D%0A%20%20%20%20return%20x%3B%0D%0A%7D%0D%0A%0D%0A%0D%0A%0D%0Afunction%20works()%3A%20Face%20%7B%0D%0A%20%20%20%20return%20%7B%20type%3A%20'face'%20%7D%3B%0D%0A%7D%0D%0A%0D%0Afunction%20doesntWork()%3A%20Face%20%7B%0D%0A%20%20%20%20return%20foo(%7B%20type%3A%20'face'%20%7D)%3B%0D%0A%20%20%20%20%2F%2F%20%5E%20typechecker%20errors%20here%20with%3A%0D%0A%20%20%20%20%2F%2F%20Type%20'%7B%20type%3A%20string%3B%20%7D'%20is%20not%20assignable%20to%20type%20'Face'.%0D%0A%20%20%20%20%2F%2F%20%20%20Types%20of%20property%20'type'%20are%20incompatible.%0D%0A%20%20%20%20%2F%2F%20%20%20%20%20Type%20'string'%20is%20not%20assignable%20to%20type%20'%22face%22'.%0D%0A%7D%0D%0A%0D%0Afunction%20workaround()%3A%20Face%20%7B%0D%0A%20%20%20%20return%20foo(%7B%20type%3A%20'face'%20as%20'face'%20%7D)%3B%0D%0A%7D%0D%0A)

**Related Issues:**
None that I can find

**Comment by laughinghan** [comment]
(In my real-world use case I'm running into an analogous problem with an enum, but I assume type widening rules are the same between enums vs enum constant types and strings vs string literal types and this is a smaller, simpler example.)

**Comment by RyanCavanaugh** [comment]
There are more cases where doing this creates problems than there are cases where this would help.

In general we do not assume that identity transforms keep you in the same subtype within the primitives - too many functions violate this assumption and it's generally unsafe to assume a literal type for a literal value without additional evidence that it's really going to be treated in a way that maintains its literalness.

**Comment by laughinghan** [comment]
@RyanCavanaugh Wait no I think you're misunderstanding, the identity transform isn't important, the important thing is that `foo()` is known to return `T` and therefore if `T['type']` needs to be `'face'`, the object literal's `.type` should not be type-widened from `'face'` to `string`.

Here's an example where `foo()` returns `T` but **_isn't_** the identity transform:
```ts
interface Face {
    type: 'face';
}
function foo<T>(a: Array<T>): T {
    return a[0];
}



function works(): Face {
    return { type: 'face' };
}

function doesntWork(): Face {
    return foo([{ type: 'face' }]);
    // ^ typechecker errors here with:
    // Type '{ type: string; }' is not assignable to type 'Face'.
    //   Types of property 'type' are incompatible.
    //     Type 'string' is not assignable to type '"face"'.
}

function workaround(): Face {
    return foo([{ type: 'face' as 'face' }]);
}
```

[Playground Link](http://www.typescriptlang.org/play/#src=interface%20Face%20%7B%0D%0A%20%20%20%20type%3A%20'face'%3B%0D%0A%7D%0D%0Afunction%20foo%3CT%3E(a%3A%20Array%3CT%3E)%3A%20T%20%7B%0D%0A%20%20%20%20return%20a%5B0%5D%3B%0D%0A%7D%0D%0A%0D%0A%0D%0A%0D%0Afunction%20works()%3A%20Face%20%7B%0D%0A%20%20%20%20return%20%7B%20type%3A%20'face'%20%7D%3B%0D%0A%7D%0D%0A%0D%0Afunction%20doesntWork()%3A%20Face%20%7B%0D%0A%20%20%20%20return%20foo(%5B%7B%20type%3A%20'face'%20%7D%5D)%3B%0D%0A%20%20%20%20%2F%2F%20%5E%20typechecker%20errors%20here%20with%3A%0D%0A%20%20%20%20%2F%2F%20Type%20'%7B%20type%3A%20string%3B%20%7D'%20is%20not%20assignable%20to%20type%20'Face'.%0D%0A%20%20%20%20%2F%2F%20%20%20Types%20of%20property%20'type'%20are%20incompatible.%0D%0A%20%20%20%20%2F%2F%20%20%20%20%20Type%20'string'%20is%20not%20assignable%20to%20type%20'%22face%22'.%0D%0A%7D%0D%0A%0D%0Afunction%20workaround()%3A%20Face%20%7B%0D%0A%20%20%20%20return%20foo(%5B%7B%20type%3A%20'face'%20as%20'face'%20%7D%5D)%3B%0D%0A%7D%0D%0A)

**Comment by RyanCavanaugh** [comment]
It's the identity transform *over `T`*. A `T` goes in, a `T` goes out.

**Comment by laughinghan** [comment]
Huh, I guess I don't understand then. How could a function change a subtype while passing the typechecker, without typecasts?

**Comment by laughinghan** [comment]
Oh geez, this typechecks:
```ts
interface Thing {
    type: string;
}
interface Face {
    type: 'face';
}
function foo<T extends Thing>(x: T): T {
    x.type += 'lol';
    return x;
}

function test(): Face {
    return foo({ type: 'face' as 'face' });
}
```

I think I understand.
