### ISSUE TITLE
Declaration binding identifiers are not mapped to the generated binding location

### ISSUE THREAD

**Issue by loganfsmyth** [microsoft/TypeScript#22833]
**Search Terms:** 
source maps

**Code**

```ts
class AnotherThing {
  prop = 4;
}

function someFn() {
}
```

**Expected behavior:**

Source maps would map the `AnotherThing` identifier to the new binding identifier when the class is compiled, so it would reference the name in `var AnotherThing =`. Same for `someFn`.

**Actual behavior:**

The entire `class AnotherThing {` line is mapped to the entire first and second line output from TS. Same for the function header.

**Examples viewed in Sokra's source map visualization**

<img width="721" alt="screen shot 2018-03-21 at 5 23 32 pm" src="https://user-images.githubusercontent.com/132260/37846621-6bf6118e-2e8b-11e8-9bc1-cb079ee84e9f.png">

<img width="482" alt="screen shot 2018-03-23 at 9 05 10 am" src="https://user-images.githubusercontent.com/132260/37846808-0d755e48-2e8c-11e8-9aee-5676eeede427.png">

I'll also add that this is also confused by the fact that decoratored classes _do_ map the binding name, but map it to a very unhelpful location, as shown here:
<img width="716" alt="screen shot 2018-03-21 at 5 25 13 pm" src="https://user-images.githubusercontent.com/132260/37847074-d07d2402-2e8c-11e8-867f-f825780f273d.png">

**Related Issues:**
* #22834

**Comment by loganfsmyth** [comment]
Here's another case that is similar to the decorator example. I'd expect `ExportedOther` to map to the various use of the binding, but I'd expect `exports.ExportedOther = ExportedOther;` up to the `=` to map to the class declaration itself.

<img width="645" alt="screen shot 2018-04-23 at 2 52 38 pm" src="https://user-images.githubusercontent.com/132260/39155249-11d792ac-4706-11e8-95d4-ccc2767a1fd3.png">

whereas here you can see that the `export class` at the start of the declaration isn't tied to the `exports.ExportedOther = ` part of the code.
<img width="631" alt="screen shot 2018-04-23 at 2 52 57 pm" src="https://user-images.githubusercontent.com/132260/39155248-11bac794-4706-11e8-9644-64870bb13f54.png">

**Comment by RyanCavanaugh** [comment]
Possible this has been fixed, but if not, this doesn't seem to warrant additional work at this point since properties don't need to be downleveled anymore.
