### ISSUE TITLE
Hover on path doesn't show which part of path is broken when typo in path

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#22837]
_From @liesislukas on March 22, 2018 12:51_

- VSCode Version: Version 1.21.1 (1.21.1)
- OS Version: macOS 10.13.3 (17D102)

Steps to Reproduce:

NodeJS project.

Require a file:
`const foo = require('./../some/path/to/file/foo');`
If path is **all** correct i can hover on any path element and see content preview of final file + hovered path element is highlighted.

If the path is **not** all correct - I can't hover any path elements and get hint of which part of the path is bad.

e.g. there is a typo: `const foo = require('./../some/bad_path/to/file/foo');`

I expect to hover `..` and `some` words and see highlighted words meaning that folder is found.
I expect to hover on `bad_path` or any following elements and not see a highlighted word which means file/folder not found.

Does this issue occur when all extensions are disabled?: Yes

_Copied from original issue: Microsoft/vscode#46341_

**Comment by mjbvz** [comment]
Not sure if this is possible since there is not always a mapping between import paths and on disk paths (and there may be multiple ways to resolve the same import path).

Moved over to typescript to get more feedback

**Comment by andy-ms** [comment]
@DanielRosenwasser recently mentioned wanting spelling suggestions on paths. We don't have a mechanism for it currently though, but we could imagine an algorithm that takes parts off the end of the path until you get a directory that does exist, then offer spelling suggestions for the part that came after that.

**Comment by mjbvz** [comment]
Closing this due to lack of further user feedback of the past two years
