### ISSUE TITLE
Source maps for single-identifier arrows functions map the binding identifier to the whole function header 

### ISSUE THREAD

**Issue by loganfsmyth** [Microsoft/TypeScript#22834]
**Search Terms:** 
source maps

**Code**

```ts
const fn = (arg) => {
};
const fn2 = arg2 => {
};
```

**Expected behavior:**
Source maps should both map the argument binding identifier to the location of the new binding.

**Actual behavior:**
The arrow that doesn't have parens maps the `arg2` binding to the whole function header.
<img width="516" alt="screen shot 2018-03-21 at 5 30 45 pm" src="https://user-images.githubusercontent.com/132260/37847276-7dd70906-2e8d-11e8-83b1-6cbb04bcf4e5.png">
vs
<img width="522" alt="screen shot 2018-03-21 at 5 30 34 pm" src="https://user-images.githubusercontent.com/132260/37847265-78059466-2e8d-11e8-8ab7-2976d8927ad9.png">

**Related Issues:**
* #22833

**Comment by weswigham** [comment]
@loganfsmyth I assume you've filed this with some background - how do it her transpilers soucemap this? An extra position at the start of the first argument?

**Comment by weswigham** [comment]
Would you rather see sourcemaps like this?:
![image](https://user-images.githubusercontent.com/2932786/39009607-ef290346-43c0-11e8-81e5-6543464124df.png)

**Comment by loganfsmyth** [comment]
You know, I think I'll backpedal on this being an issue worth changing. I initially filed it because it happened to be something I noticed while exploring #22833 and hadn't put a ton of thought into it. Considering it more, I think this is more a somewhat frustrating limitation of sourcemaps in general rather than specifically something that Typescript should try to address. I'd be happy to close this.

**Comment by weswigham** [comment]
@loganfsmyth if it's not a problem, then, OK.

**Comment by loganfsmyth** [comment]
Alright, I'm going to close this. Sorry for the extra noise.
