### ISSUE TITLE
EmitFlags.NoLeadingComments is not propagated down to tokens

### ISSUE THREAD

**Issue by amcasey** [Microsoft/TypeScript#22831]
Background: I'm trying to emit an import declaration without its leading trivia (as part of OrganizeImports).  I can set the emit flag on the declaration and that's sufficient to prevent `emitNodeWithComments` from emitting the leading trivia.  However, `emitNodeWithNestedComments` emits the leading trivia anyway as part of `emitTokenWithComment(SyntaxKind.ImportKeyword` in `emitImportDeclaration`.

For context, here's the call stack:
```
emitImportDeclaration (src\compiler\emitter.ts:2136)
pipelineEmitUnspecified (src\compiler\emitter.ts:756)
pipelineEmitWithHint (src\compiler\emitter.ts:539)
pipelineEmitWithSourceMap (src\compiler\emitter.ts:529)
emitNodeWithNestedComments (src\compiler\comments.ts:191)
emitNodeWithSynthesizedComments (src\compiler\comments.ts:133)
emitNodeWithComments (src\compiler\comments.ts:95)
pipelineEmitWithComments (src\compiler\emitter.ts:517)
Writer.onEmitNode (src\services\textChanges.ts:743)
pipelineEmitWithNotification (src\compiler\emitter.ts:507)
print (src\compiler\emitter.ts:458)
writeNode (src\compiler\emitter.ts:404)
getNonformattedText (src\services\textChanges.ts:689)
getFormattedTextOfNode (src\services\textChanges.ts:665)
format (src\services\textChanges.ts:654)
(anonymous function) (src\services\textChanges.ts:656)
computeNewText (src\services\textChanges.ts:656)
(anonymous function) (src\services\textChanges.ts:643)
(anonymous function) (src\services\textChanges.ts:642)
getTextChangesFromChanges (src\services\textChanges.ts:633)
```

**Comment by amcasey** [comment]
@weswigham can probably more clearly articulate what *should* be happening.

**Comment by amcasey** [comment]
I'm going to hack around this problem to fix a group of OrganizeImport bugs, including #22731.  I'll tag the hack with the URL of this issue.

**Comment by weswigham** [comment]
Hmmmmmmmmmmmmmmmmmm, thinking on it more, the correct behavior is probably to move `emitTokenWithComment` into the comment emitter, then have it track both the context node, and weather anything has been written to indicate that the token's leading/trailing comments are not the node's (and also respect the flag on the node if they are). @rbuckton do you have preferences here?

**Comment by rbuckton** [comment]
I was looking at reducing the stack depth in another PR, which has changes how we emit comments for tokens (though I also need to address some performance issues before that can go in). It might be easier to indicate whether a token is the first or last token and have the comment emitter use that to check for the related EmitFlag on the context node.
