### ISSUE TITLE
VSCode calling node components in a non Node App

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#22846]
_From @netofd84 on March 8, 2018 16:6_

- VSCode Version: 1.21.0
- OS Version: Windows10

Steps to Reproduce:

1. By using SPTools in order to work with a SharePoint Folder I have noticed, by using fiddler, that vscode is trying to open bower_compoents, node_modules, bower.json, package.json, etc. When this application is only using simple javascript. The real problem is that it keeps going and never stops from making these calls to these files and folders. We got to the point that one of the server farms was so busy because of these multiple calls.

2. I have used the same vscode to build other applications outside of SharePoint but apparently the configuration for node and bower are still there, is there a way to disable this configuration and just work with plain javascript without calling these other elements?

Does this issue occur when all extensions are disabled?: Yes

_Copied from original issue: Microsoft/vscode#45313_

**Comment by mjbvz** [comment]
Can you please check when these requests are triggered. Try closing all editors and then reloading the workspace. Are the requests triggered then? When you open the first file? Some other time?

Trying to narrow down if this is the npm built-in extension or `workspaceStats.ts`.

**Comment by mjbvz** [comment]
_From @netofd84 on March 15, 2018 16:18_

These requests are being triggered only when I open a JS file, I don't even have ts files nor json files, and it happens on any folder, not only sharepoint folders, any remote folder that have js files within. It keeps looking for tsconfig.json, node_modules/, bower_components/.

As soon as open a js file and look at the code that's when it happens, if I look at the code of some HTML or css files everything is good, I feel like it's trying to run a compiler when I don't need it and it keeps trying and trying, it never stops.

![image](https://user-images.githubusercontent.com/3232676/37476176-e07e422a-284a-11e8-9c0f-6b9b1d7d0e54.png)

**Comment by mjbvz** [comment]
Thanks @netofd84 

We look for these files in order to provide intellisense. Even non-node app usually have a `node_modules` directory to manage their dependencies, and there's no way for us to tell that your js file is just a plain old js file without checking for the existence of these other files first. As you note though, checking continuously for these files seems like a bug.

**Comment by mhegazy** [comment]
This is automatic type acquisition in action. It tries to find all dependencies of your app, and tries to use folder names in `node_modules` to know what declaration files to download to help your intellesense experience.

We do disable many of these lockups on remote file systems, can you share more information to help us recreate the same issues you are running into? a sample project would be ideal.

**Comment by netofd84** [comment]
I just created a new separate folder within my remote server then I created a basic plain CSS, HTML and JS files without any content, and as soon as I open the js file, I can see how in fiddler VSCODE  starts generating all those calls... and it keeps going and going trying to find all those folders that don't exist in my remote server.

![image](https://user-images.githubusercontent.com/3232676/37986517-ab080daa-31c9-11e8-8104-5d219d8b1f15.png)


![image](https://user-images.githubusercontent.com/3232676/37986137-b90fad46-31c8-11e8-9093-1715d5111cb0.png)

Is there a way to tell VSCODE to not to look for those files and folders?

**Comment by mhegazy** [comment]
So the /test is mapped to a remote folder?

**Comment by netofd84** [comment]
YES, remote folder, empty files, no node related, just plain javascript, any idea why this is happening? I have used the same VSCODE to develop angular apps in my local machine, no remote server involved, but now that I'm in a remote server and just simple javascript.. this happens... 

Thanks

**Comment by mhegazy** [comment]
Add a jsconfig.json file to the root of your project, and set `files` property to your input (this avoids enumerating the directory to find all .js files) and set `enabled` to `false` for type acquisition (this should avoid reading node_modules contents to find types for you).

```ts
{
	"files": [ "./script.js" ],
	"typeAcquisition": {
		"enable": false
	}
}
```

**Comment by netofd84** [comment]
There is one problem, in my remote server, I'm not allow to put JSON files, just plain js, html and CSS files. any other approach?

I tried to do it in the User Preferences (_File>>Preferences>>Settings_) by putting this line

"typescript.disableAutomaticTypeAcquisition": true,

but not luck.

**Comment by mhegazy** [comment]
can you put it above your mapped directory?

**Comment by netofd84** [comment]
No, just HTML, JS and CSS files are allowed in my remote server.
