### ISSUE TITLE
Generics that extend an indexable interface cannot use {} as a default argument value

### ISSUE THREAD

**Issue by milesj** [Microsoft/TypeScript#22852]
**TypeScript Version:**  2.7.2 and 2.9.0-dev.20180323

**Search Terms:** "Type '{}' is not assignable", "Type '{}' is not assignable to type", "generics default args", "indexable default arg", "generics default value", "generics extends default args "

**Code**

```ts
interface Options {
  [key: string]: any;
}

// Generics that extend indexable options w/ default value of {}
class Foo<T extends Options> {
  options: T;

  constructor(options: T = {}) {
    this.options = options;
  }
}

// Generics that extend indexable options w/o default value
class Bar<T extends Options> {
  options: T;

  constructor(options: T) {
    this.options = options;
  }
}

// Generics that extend indexable options w/ an optional value that is spread into an object
class Baz<T extends Options> {
  options: T;

  constructor(options?: T) {
    this.options = { ...options };
  }
}

// No generics, uses indexable options directly
class Qux {
  options: Options;

  constructor(options: Options = {}) {
    this.options = options;
  }
}
```

**Expected behavior:**

`Foo` with generics that extend an indexable interface should be able to use `{}` as an argument's default value.

**Actual behavior:**

The `Foo` class fails with the following error "Type '{}' is not assignable to type 'T'", and `Baz` fails with "Spread types may only be created from object types.", but this one is expected, so I will focus on `Foo`.

Unless my understand is incorrect, the `Foo` example is equivalent to `Qux`, yet fails to validate. Seems some typing is lost when defined via generics.

**Playground Link:**

http://www.typescriptlang.org/play/#src=interface%20Options%20%7B%0D%0A%20%20%5Bkey%3A%20string%5D%3A%20any%3B%0D%0A%7D%0D%0A%0D%0A%2F%2F%20Generics%20that%20extend%20indexable%20options%20w%2F%20default%20value%20of%20%7B%7D%0D%0Aclass%20Foo%3CT%20extends%20Options%3E%20%7B%0D%0A%20%20options%3A%20T%3B%0D%0A%0D%0A%20%20constructor(options%3A%20T%20%3D%20%7B%7D)%20%7B%0D%0A%20%20%20%20this.options%20%3D%20options%3B%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0A%2F%2F%20Generics%20that%20extend%20indexable%20options%20w%2Fo%20default%20value%0D%0Aclass%20Bar%3CT%20extends%20Options%3E%20%7B%0D%0A%20%20options%3A%20T%3B%0D%0A%0D%0A%20%20constructor(options%3A%20T)%20%7B%0D%0A%20%20%20%20this.options%20%3D%20options%3B%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0A%2F%2F%20Generics%20that%20extend%20indexable%20options%20w%2F%20an%20optional%20value%20that%20is%20spread%20into%20an%20object%0D%0Aclass%20Baz%3CT%20extends%20Options%3E%20%7B%0D%0A%20%20options%3A%20T%3B%0D%0A%0D%0A%20%20constructor(options%3F%3A%20T)%20%7B%0D%0A%20%20%20%20this.options%20%3D%20%7B%20...options%20%7D%3B%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0A%2F%2F%20No%20generics%2C%20uses%20indexable%20options%20directly%0D%0Aclass%20Qux%20%7B%0D%0A%20%20options%3A%20Options%3B%0D%0A%0D%0A%20%20constructor(options%3A%20Options%20%3D%20%7B%7D)%20%7B%0D%0A%20%20%20%20this.options%20%3D%20options%3B%0D%0A%20%20%7D%0D%0A%7D%0D%0A

**Related Issues:**

**Comment by MartinJohns** [comment]
I don't think this is a bug, because interfaces with indexers can declare "known properties". Here's an example:

```
interface MyOptions extends Options {
  port: number;
  host: string;
}
```

The type `MyOptions` extends from `Options` (so it fulfills your type constraint), it has an indexer, but it also declares two properties that **must** be present. You can not construct `MyOptions` with the value `{}` because the two properties are missing.

**Comment by milesj** [comment]
Thanks for the feedback, I'll give the partial approach a try.
