### ISSUE TITLE
Extended alias syntax with "as"

### ISSUE THREAD

**Issue by ab34** [Microsoft/TypeScript#2285]
Typescript supports type aliases since 1.4. 

In order to achieve better abstraction patterns and to enhance tooling, it would be nice to have a more extended alias syntax in typescript.

One current issue of not having aliases for other typescript constructs, like modules and interfaces, is code fragmentation in the generated declaration files, as they often end up describing the same construct multiple times in one file, referenced by a common name.

For example, the typescript.d.ts declaration file contains 6 occurences of the same "typescript" module. Aliases could allow here to differentiate the different intended sections of the typescript module in the declaration file.

The "as" syntax already exists in ecmascript 6 for importing modules:
```javascript
import * as lib from 'lib';
```
We could extend this syntax for aliases in typescript, and this optional feature could enhance all nodes having the ability to be duplicated in code, like interfaces and modules, as well as type definitions, ambient declarations, exports and original javascript nodes.

typescript constructs:
```javascript
declare module "moduleName" as moduleAlias

module "moduleName" as moduleAlias

type typeName as typeAlias

interface interfaceName as interfaceAlias

```
javascript nodes:

```javascript

export class className as classAlias

class className as classAlias

function functionName() as functionAlias {};

let var1 as letAlias

var var2 as varAlias
```

The extended "as" syntax would not affect the resulting javascript code, it would only serve as a typescript abstraction.

**Comment by danquirk** [comment]
I think some more explicit motivating examples are required. You mention:

_For example, the typescript.d.ts declaration file contains 6 occurences of the same "typescript" module. Aliases could allow here to differentiate the different intended sections of the typescript module in the declaration file._

but it's not clear to me why you'd actually want to name these differently as they are all describing the same module. I'm not sure how tooling would be improved here either. 

What is the reason for aliasing a function or var? What was wrong with the original name that you can't just change the originally declared name to be more useful/descriptive?

**Comment by ab34** [comment]
Interesting questions, thanks for asking them, @danquirk.

Basically, as I understand them, the declaration files are there to help developers to understand the meaning and the internal workings of a codebase. As such, they provide information about types, interfaces and also may describe modules organizing the codebase.

The declaration files are consumed by tools or directly by developers in order to be more productive while using and integrating the "declared/described" codebase into their own projects.

As such, declaration files are metaprograms about the codebase. Aliases are metaprogramming concepts allowing to build abstractions from a codebase, to extract meaningful parts from it, to organize and classify the code by leveraging metaconcepts about the intents of the author.

In the case of tools consuming the declaration files, for example the typescript.d.ts file or any other, it can be helpful for such tools to be able to organize the modules present into the declaration by meaningful sections in accordance to the intent, the strategy or the design pattern adopted by the original author of the codebase.

That is, instead of blindly merging all the module declarations into one at runtime, or to rely onto parsing comments into the files, a more programmatic way to extract meaningful information from the declaration files would be to have the ability to extract some meaningful chunks of information from the nodes themselves, like through an alias, member of the node.

The same way, declaring aliases for functions, variables and other original nodes would allow metaprogramming tools to extract some meaningul information from the codebase in a programmatic way, and to build upon them new abstractions.

So what I presented as an alias here can be more complex, it can internally be a two-way mapping with another object referencing the original one. The main point here is the idea of giving more metaprogramming abilities to typescript tools for building more complex abstractions on top of the original codebase. 

The concept of alias is not set up in stone, in fact it was just a first draft thought towards this idea of a metaprogramming api, at least it was the intent of the suggestion. But I thought it was interesting to point out that aliases were already present into the es6 modules somehow, as well as in the typescript types though in different forms, the typescript aliases being a direct assignation, while the es6 module alias feels more like a metaprogramming syntax.

**Comment by ab34** [comment]
In fact there are so many concrete motivations to support the idea that it would be difficult to expose them all in a post, but for example, one of them could be about testing the codebase.

Aliasing a function or a variable would allow to assign or reference tests chunks directly into the codebase. Of course it would not be compiled into the resulting javascript code. But at compilation time all the info for testing could be paired into the code.

Tests assignation is just one example amongst a lot of different motivations for inlining metadata into the code though. One could see other practical motivations regarding to refactoring, formatting and other tasks.

**Comment by ab34** [comment]
Well I can perceive some other ways to achieve some metaprogramming needs without affecting the syntax of typescript. It involves using the internals of the compiler, but I guess it is the way to go for having some advanced functionality anyway.

Am closing the issue by now. Thanks.
