### ISSUE TITLE
Union type in JSX IntrinsicElements seems like a bug

### ISSUE THREAD

**Issue by mikeleonard** [Microsoft/TypeScript#22857]
```typescript
declare namespace JSX {
  interface IntrinsicElements {
    foo: { bar: boolean } | { baz: boolean };
  }
}

const one = <foo bar baz />; // ok
```

Hi. Is this a bug? I was expecting this to not compile but it does. 

In the IntrinsicElements interface the type for `foo` is defined as having a boolean attribute of `foo` **or** `baz` but it compiles when both are set.

I'm new to typescript so apologies if the issue is just my understanding of the type system.

**Comment by MartinJohns** [comment]
Union types are **or**, but not **xor**. **or** means **any** of the types is provided. If all are provided it's fine. **xor** means **one** of the types is provided, not more. Currently it's not directly supported to have a **xor** union type. See also #14094.

**Comment by mikeleonard** [comment]
Makes sense, thanks for the quick reply.
