### ISSUE TITLE
how to assign values to object with dynamic keys

### ISSUE THREAD

**Issue by sivahanuman** [Microsoft/TypeScript#22856]
Hi i don't know the key name , it can be anything and it can be any number each time so how to assign values to dynamic keys of object
for example 

obj["anything"] = anything;

**Comment by DanielRosenwasser** [comment]
Hey there, this issue tracker isn't meant to work as a support forum. These questions tend to be better suited for StackOverflow. You may want to open a question up there instead. Thanks!
