### ISSUE TITLE
document.body is the body element

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#22868]
https://html.spec.whatwg.org/multipage/dom.html#the-document-object

**TypeScript Version:**  master

**Search Terms:** 

**Code**

**Expected behavior:**

```ts
body: HTMLBodyElement;
```

**Actual behavior:**

```ts
body: HTMLElement;
```

**Playground Link:**  

**Related Issues:**

**Comment by nmain** [comment]
The spec that you've linked to doesn't seem to support your claim:
```[CEReactions] attribute HTMLElement? body;```

It types `document.body` as `HTMLElement` and not `HTMLBodyElement`

**Comment by mhegazy** [comment]
looking at [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Document/body#notes), seems like `body` is not always `HTMLBodyElement` either.
