### ISSUE TITLE
when site publish with vs2013 typescript plugin problem

### ISSUE THREAD

**Issue by sargin48** [Microsoft/TypeScript#2286]
Hi. 
I use VS2013 U4 and every plugin updated. I installed TS v.1.4 .

When i add x.ts  file to project and ctrl + s it export true x.js file. 

but x.js file not imported to your project because of when publish your project, there isn't x.js file. 
this file is missing. 

is this a bug or  ?

**Comment by paulvanbrenk** [comment]
What kind of project? And does it work when you do a full build?

**Comment by NoelAbrahams** [comment]
I think the request is for #297

**Comment by sargin48** [comment]
yes my problem is this.  same problem.
Thanks Paul. Thanks Noel :)
