### ISSUE TITLE
Allow option to omit empty JS and map files from output.

### ISSUE THREAD

**Issue by electricessence** [Microsoft/TypeScript#22864]
Files/modules that only contain interfaces, declarations, or type aliases (no real JS code) still produce `*.js` files.

One previous solution was to name all interface only files to `*.d.ts` and subsequently no JS file was generated, BUT neither is a copy of the `*.d.ts` file in the output directory.  Therefore a second task had to be added to copy these files.

Another solution would be to keep all files as `*.ts` but find and delete empty files but this is tedious and difficult if you have header comments and source maps.

Optimally, `*.ts` files that simply do not contain any usable/importable JS (totally empty except comments) should have the option to be omitted from output.

**Comment by jwbay** [comment]
There's some discussion about this in https://github.com/Microsoft/TypeScript/issues/10908.

**Comment by RyanCavanaugh** [comment]
We won't be adding this behavior; more complex build toolchains are widely available for customizing the exact emit policy.
