### ISSUE TITLE
variable name _this breaks in checkJs

### ISSUE THREAD

**Issue by mohsen1** [Microsoft/TypeScript#22866]
**TypeScript Version:**  2.7.2

**Search Terms:** 
`_this`
**Code**
Real world example 

https://github.com/webpack/webpack/blob/7f11210cffc58820b4cdd086934398306882c338/lib/Compilation.js#L454

**Expected behavior:**
No Error
**Actual behavior:**

```
TS2400: Expression resolves to variable declaration '_this' that compiler uses to capture 'this' reference.
```
**Playground Link:**  

**Related Issues:**
https://github.com/webpack/webpack/pull/6862

**Comment by mhegazy** [comment]
Here is a simplified repro:

```ts
// @ts-check

class Base { }

class C extends Base {
    constructor() {
        super();
    }

    foo() {
        let _this = this;
        
        () => {
            _this
        };
    }
    
}

```

**Comment by mhegazy** [comment]
@mohsen1 fix should be in tonight's `typescript@next`.
