### ISSUE TITLE
LS vs Compiler API: too many `getSourceFile`s?

### ISSUE THREAD

**Issue by clausreinke** [Microsoft/TypeScript#2287]
In `createLanguageService` (https://github.com/Microsoft/TypeScript/blob/master/src/services/services.ts#L2241), `createProgram` is called with a host that uses `getOrCreateSourceFile` for `getSourceFile`. 

This suggests that new files are to be created when new filenames are encountered.

However, `createProgram` always uses its own `getSourceFile` (https://github.com/Microsoft/TypeScript/blob/master/src/compiler/program.ts#L134), independent of whether or not a host parameter is present.

So, when language service methods call into `getValidSourceFile` (https://github.com/Microsoft/TypeScript/blob/master/src/services/services.ts#L2201), they use the wrong `getSourceFile` and throw instead of create.

**Comment by CyrusNajmabadi** [comment]
What scenario are you running into where you encounter this?

**Comment by clausreinke** [comment]
Adding a non-file-system source, then calling `getSyntacticDiagnostics` on the new file.

**Comment by mhegazy** [comment]
So your file does not have a .ts extension?
When getValidSourceFile is called, the assumption is that the file was added to the program. if you call getCompilerOptionsDiagnostics do you see an error about the file?

**Comment by clausreinke** [comment]
I don't have my computer at hand, but roughly:
- editor creates file (valid content and name), but doesn't save it
- file is added to LS host
- LS getSyntacticDiagnostics is called on file
- getVaildSourceFile throws

To me, the issue seems to be that the wrong getSourceFile is used (confirmed by logging the function). The getOrCreateSourceFile suggests that files could be added this late.

However, if the file is supposed to be added to program beforehand, i'd be looking at synchronizeHostData - which seems to compare host *cache* (not host) against program, so would not see the new file..

**Comment by mhegazy** [comment]
giving the file to the host does not mean it is part of the program. this is the same as on the commandline:
> tsc a.js b.ts
"a.js" is not part of that program though it was passed as a file. it will not be parsed, or type-checked.

For this case, you should see some errors about the file. if not, i will need to investigate. if the file is not a ts extension use the compiler option allowNonTsExtensions, thought this has implications on module resolution and loading.

**Comment by clausreinke** [comment]
adding the file to the host only makes it available, asking the LS about it should cause the LS to try and get it from the host, no?

I have no idea why you keep mentioning non-.ts files. I was talking about a .ts file that exists in memory only, and is to be added to the files the LS can operate on, after that LS has been created.

It would help if you could comment on the two anomalies i described (getSourceFile and synchronizeHostData) - if they are not anomalies, your explanation might help me to see how to achieve my use-case.

**Comment by mhegazy** [comment]
The communication with the host happens only when we are "constructing" the context. this is when we call synchronizeHostData, and thus the getOrCreateSourceFile. after that, we only consult the program for the files (getValidSourceFile) and if that is not there, we do not know what to do basically.

The non-ts is me doing psychic debugging :). It is likely that there is a bug we need to fix. if you can share some details on how to reproduce this i can definitely take a look. possible problems are slashes (we do normalize them on the compiler/LS side, which is not a great thing) or some canonical file name mismatch.

>It would help if you could comment on the two anomalies i described (getSourceFile and synchronizeHostData) - if they are not anomalies, your explanation might help me to see how to achieve my use-case.

There are multiple layers here, and each use the same name "getSourceFile" so hopefully i do not miss that up as i am going here:

### program 
A program is an immutable collection of files, once created it is not going to get a new file. it uses a map to store files ([filesByName]( https://github.com/Microsoft/TypeScript/blob/master/src/compiler/program.ts#L118)). As you call create program it will zip through the input files, and recursively visit their references, and imports and populate the filesByName list. any time it needs to get the SourceFile object (i.e. read a new file from disk) it will ask the host.getSourceFile ([here](https://github.com/Microsoft/TypeScript/blob/master/src/compiler/program.ts#L313)). It then stores that in filesByName. All calls to program.getSoruceFile from this point on will not do any resolution, query to the host, or reading from disk. if the file in the list, the program knows about it, if not, an error has been reported. at least this is the assumption.

### language service
The language service builds a program object on every change. this is done at the beginning of every call to the LS. first check there are no changes, and if there were any, ditch the old program object and create a new one. this is the [synchoronizeHostData](https://github.com/Microsoft/TypeScript/blob/master/src/services/services.ts#L2220). It first passes the list of files it got from the LSHost to the program; as it is building the program, the program would ask it for sourceFiles, and it either saw them before (from a previous program instance) then it either returns that or does incremental parsing and get a new sourceFile instance. if not, it goes back to the LSHost and asks it about it. if the host says i do not know this file (return undefined) it will pass that to the Program, and the program, will mark this file as missing (see [this](https://github.com/Microsoft/TypeScript/blob/master/src/services/services.ts#L2274)).

### getValidSourceFile
After a new program instance has been created, LS features want an AST to look at for the file. the asumption here is that the file has been parsed as part of building the program. getValidSoruceFile comes into play here ensuring that the assumption is true. so if you do something like getCompletionsAtPosition("file not part of the program.ts", 9), getValidSourceFile will complain.

**Comment by clausreinke** [comment]
Thanks. So, if I understand you correctly, it is no longer possible to add files to a running LS instance? 

Because I could not reproduce that use case using current APIs, I tried to explain my issue with descriptions of the code paths standing in the way.

**Comment by CyrusNajmabadi** [comment]
You can add files to a running LS instance.  When you make a call into the LS, then LS will immediately call back into you (the host) querying you about what your current set of files is, and what 'version' each of them are at.  If the set of files has changes (i.e. because you added a new file), then the LS will query you for the contents of that file and create a new program instance with that source file in it.

**Comment by clausreinke** [comment]
@CyrusNajmabadi that is exactly the issue i've described above: the LS compares the list of files in its *host cache* and program - it will find changes in existing files, but new files  do not make it from *host* to host cache (I think). Unless the host cache starts out with only root files and program construction adds at least one implied file, but then the file list comparison will always fail, even if nothing has changed.

**Comment by CyrusNajmabadi** [comment]
Sorry @clausreinke  I'm getting a bit confused.  You are correct in that the LS compares the list of files from its host cache and program.  I'm a bit more confused why you say "new files do not make it from host to host cache."  The first thing synchronizeHostData does is:

```ts
        function synchronizeHostData(): void {
            // Get a fresh cache of the host information
            var hostCache = new HostCache(host);
```

new HostCache then does this:

```ts
        constructor(private host: LanguageServiceHost) {
            // script id => script index
            this.fileNameToEntry = {};

            // Initialize the list with the root file names
            var rootFileNames = host.getScriptFileNames();
            for (var i = 0, n = rootFileNames.length; i < n; i++) {
                this.createEntry(rootFileNames[i]);
            }
```

So new files should make it from host to host cache as the very first thing we ask the host for is "what is your set of files".

**Comment by clausreinke** [comment]
Sorry @CyrusNajmabadi , i seem to be confused as well - i only just noticed that `programUpToDate` is local to `synchronizeHostData` (i thought it could not access the `hostCache` variable, and would be working on the old cache instead).

Ok, you've managed to exclude both of my suspects, and confirmed how this  should work - i'll report back when i've figured out why my LS usage is going wrong here.

**Comment by clausreinke** [comment]
how embarrassing: turned out to be entirely my own fault - too many sources of truth in my client code. The LS never asked my host about the new file itself, because it had already asked for the *list* of files, which had not been updated. Your explanations helped me to adjust my thinking sufficiently to find this bug, thanks!
