### ISSUE TITLE
Intersection type from `Function` and object literal type doesn't work

### ISSUE THREAD

**Issue by m93a** [Microsoft/TypeScript#22877]
**TypeScript Version:**  2.7.2

**Search Terms:** Function interface, object literal type, intersection, type alias

**Code**

```ts
type MyConstructorType = Function & {prototype: {foo: number}};
let bar = (function () { }) as MyConstructorType;
bar.prototype.foo();
```

or equivalent:

```ts
let bar = (function () { }) as Function & {prototype: {foo: number}};
bar.prototype.foo();
```

doesn't even depend on the order

```ts
let bar = (function () { }) as {prototype: {foo: number}} & Function;
bar.prototype.foo();
```

**Expected behavior:**
The function call `bar.prototype.foo()` should throw a compile time error, as `foo` is marked as a number.

**Actual behavior:**
The property `bar.prototype` is of type `any`, no matter the intersection type.

**Playground Link:** [here](http://www.typescriptlang.org/play/#src=type%20MyConstructorType%20%3D%20Function%20%26%20%7Bprototype%3A%20%7Bfoo%3A%20number%7D%7D%3B%0D%0Alet%20bar%20%3D%20(function%20()%20%7B%20%7D)%20as%20MyConstructorType%3B%0D%0Abar.prototype.foo()%3B%20%2F%2F%20should%20throw)

**Related Issues:** #17757

**Comment by andy-ms** [comment]
The problem is that `Function.prototype` is `any`, and intersecting with `any` doesn't narrow the type:
```ts
declare const x: { a: any } & { a: string };
x.a;
```

Unfortunately, I don't know a way to write a callable/constructable type that doesn't automatically get `prototype: any` added to it.

**Comment by RyanCavanaugh** [comment]
Would need subtraction types or spread types to represent this pattern

**Comment by m93a** [comment]
Ah, my bad, evidently I didn't read the docs properly. However it still seems pretty counter-intuitive and broken to me 🤔. From my (probably naïve) point of view, `any` is the widest type and the intersection of `any` and an arbitrary type `A` should always be `A`. What is the rationale behind the actual implementation? Why doesn't it obey the intuitive set-theory rules?

**Comment by andy-ms** [comment]
`any` isn't just a top type, it's an unsafe top/bottom type. `const x: any = 0;` and `const y: string = x` both work -- everything is assignable to `any` and `any` is assignable to everything.
