### ISSUE TITLE
Reuse type assertion syntax with literal and tuple values for its type assertion

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#22872]
This is very simple, clear, and easy syntax extension since this is reusing of verbose existing syntax. And it has no confusion neither semantic nor syntactic.

```ts
let b = true!; // type is true
let n = 0!; // type is 0
let s = 'a'!; // type is 'a'
let a = [0!]; // type is 0[]
let t = [0]!; // type is [number]
```

cc @sandersn @ahejlsberg

**Comment by yortus** [comment]
Looks the same as the suggestion in https://github.com/Microsoft/TypeScript/issues/10195#issuecomment-372864435.

**Comment by falsandtru** [comment]
Yep, but that issue is not opened for this syntax.

**Comment by yortus** [comment]
Sure, but since dicsussion is already going on there about this syntax, so you might want to at least reference it from this issue.

**Comment by falsandtru** [comment]
Of course; I've invited that discussion now.

**Comment by krryan** [comment]
Could you use it on inner types? As in,
```ts
let t = [0!]!; // type is [0]
```

**Comment by RyanCavanaugh** [comment]
Tracking at #10195. Please don't post solutions for other issues as standalone issues.
