### ISSUE TITLE
Question: is it intended?

### ISSUE THREAD

**Issue by Dzienny** [Microsoft/TypeScript#2288]
```typescript
class Company {
    constructor(public name: string) {
    }
}

class Employee {
    constructor(public name: string) {
    }
}

var array = new Array<Employee>();
array.push(new Company('Google')); // No error or warning.
```

I made a similar error and I was surprised that the VS didn't even render a warning. I use TypeScript version 1.4. Are there any plans to deal with it, or is it going to stay this way?

**Comment by danquirk** [comment]
This is by design. TypeScript uses structural typing to determine assignability. The name of a type is irrelevant, what matters is its shape. In this case your Company and Employee types are identical based on their shape, so they are assignable to one another. If they had a disjoint set of properties you would see the error you expect. This design is intended to enable common JavaScript/TypeScript patterns that mix named types (classes/interfaces) with unnamed types (object literals and function types).

**Comment by Dzienny** [comment]
I see and I suppose, in this case, it would be possible to have both - ie enable common JavaScript/TypeScript patterns and warn a programmer when appropriate. In the example there are two Typescript classes that probably have a different meaning/purpose and the compiler could notice it. The programmer would have to add explicit cast to get rid of the warning, example:
```typescript
array.push(<Employee>new Company('Google'));
```

**Comment by danquirk** [comment]
How does the compiler notice it? Only when the types are identical? Why should it be illegal to have 2 things that are shaped the same? What if they're not precisely identical?

```ts
interface Point {
    x: number;
    y: number
}

interface Point3D {
    x: number;
    y: number;
    z: number
}

var arr: Array<Point>;
var p3: Point3D;
arr.push(p3); // error? by what logic?
```

You can find a lot of discussion about this in #202

**Comment by Dzienny** [comment]
In case of TypeScript classes the compiler could look at their shape first, and then look at their name and scope. Then if the shape is different, it would produce the standard error "Type 'a' is not assignable to type 'b'; else if the name or scope are different, it would produce a warning about the missing cast.

In the given example, I would really prefer to have a warning and have to make a cast to get rid of it, since putting a 3d point into a 2d points array may indicate a potential error. The 3d point should probably be projected onto 2d space first, or maybe some other computation could be needed. Or maybe that is exactly what the author intended; a cast would make the intention clear. To me one of the main points of having type checks is to detect potential problems as early as possible and I believe this extra check would help.

**Comment by danquirk** [comment]
Your proposal is essentially to add a nominal check on top of structural checks. This simply isn't going to happen. It doesn't mesh with how people actually use JavaScript today and would be a massive breaking change. Yes there are patterns where structural typing does not give you the same safety as nominal typing. Conversely, there are patterns nominal typing does not allow, or makes extremely painful, which structural typing makes simple or possible at all. There are trade offs with each, but the domain in which TypeScript is in necessitates structural typing. We don't want to be in a situation where you constantly have to annotate and cast your object literals and other correct, working JavaScript code just to satisfy the compiler.
