### ISSUE TITLE
JSX element required prop that has default value

### ISSUE THREAD

**Issue by aaronbeall** [Microsoft/TypeScript#22881]
**TypeScript Version:**  2.9.0-dev.20180325

**Search Terms:** 

**Code**

```ts
import * as React from "react";

type Props = { 
  bar: number; 
}

class Foo extends React.Component<Props, {}> {
  static defaultProps = { bar: 1 }
  render() {
    return <p>{ this.props.bar.toFixed() }</p>
  }
}

const foo = <Foo /> // Error
```

**Expected behavior:**

No error, because `defaultProps` for `bar` is provided it is not required at `<Foo />` but is definitely assigned at `this.props.bar`.

**Actual behavior:**

Error on `<Foo />`:
```
error TS2322: Type '{}' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Foo> & Readonly<{ children?: ReactNode; }> & Reado...'.
  Type '{}' is not assignable to type 'Readonly<Props>'.
    Property 'bar' is missing in type '{}'.
```

I could mark `bar` as optional in `Props` to get rid of the above error but then I get this error on `this.props.bar.toFixed`:
```
error TS2532: Object is possibly 'undefined'.
```

The original code [works as expected in Flowtype](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuyYAhgM5gBKApiQMZFR5yZgBEetDbA3KqgQCe2amAAKzbBQC8YAN5hUYMACMSeAFxgAdgFdMK6nh6KAvvzoxyFAGJw4YagA8C1bQBMKNegQB0AYRZcbTcCAB4JOCkAGnlTAD55JTAyAhICdDowd2ooEl0YAkipMFkFNU0wAEYwc2VODyMACgBKJOV66gJdPG0wMOx4hQIAC3QyX2xJCYrfAjgbdCdqd1basOBB5PNzVDo4bVSwKHtS-rsHYHjUIA).

**Playground Link:**  (Not possible due to JSX syntax and React dependency)

**Related Issues:**
#17979
https://github.com/Microsoft/TypeScript/issues/14600#issuecomment-308362119

**Comment by RyanCavanaugh** [comment]
@weswigham ideas on non-hacky ways to address this?

**Comment by weswigham** [comment]
We could just resolve the factory call and type it correctly (with defaults and everything) if we had a higher order syntax for resolving calls that was overload aware (unlike conditional types, which are not).

**Comment by mhegazy** [comment]
This is not much different from PropTypes really.

**Comment by VincentLanglet** [comment]
Is there going to be an implemented solution to manage the default props ?
I don't understand if a plan exists...

**Comment by doureyd** [comment]
I'm also interested, as workaround I set my function as optional but I have to check if it exists before calling it.

**Comment by aaronbeall** [comment]
I haven't had a chance to try it out yet but it appears [TS 3.0 has solved this](https://blogs.msdn.microsoft.com/typescript/2018/07/30/announcing-typescript-3-0/#default-props-support)! So I'm closing my issue. Cheers.
