### ISSUE TITLE
How to detect semantic only blockers vs. emit blockers

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#2289]
Previously we had: 

success : `output.emitOutputStatus === ts.EmitReturnStatus.Succeeded;`
emitOnly: `!success && outputFiles.length`

Now `getEmitOutput` only returns :

```ts
interface EmitOutput {
    outputFiles: OutputFile[];
    emitSkipped: boolean;
}
```

With only `emitSkipped` we don't know if it was a *complete success* i.e. a semantically valid emit or just a bland best attempt emit.

**Comment by DanielRosenwasser** [comment]
Somewhat unfortunately, we don't have the distinction between syntactic and semantic errors in the compiler anymore.

**Comment by basarat** [comment]
found an alternative : https://github.com/TypeStrong/atom-typescript/commit/02622f9cb3516bf868781cdaebd55eb9ed4060ee#diff-578ff651be440fee29ecfe22d52e81a4L41

**Comment by basarat** [comment]
@DanielRosenwasser would be great if you can look at #2290
