### ISSUE TITLE
Using string enum as key in {[key]: Type} throws not an index signature

### ISSUE THREAD

**Issue by appsforartists** [Microsoft/TypeScript#22892]
**TypeScript Version:**  2.9.0-dev.20180325

**Search Terms:** string enum index signature cast

**Code**

```ts
enum Fruits {
    MANGO = 'MANGO',
    BANANA = 'BANANA',
}

type StringDict = { [key: string]: string };

function map(dict: StringDict, transform: (key: string, value: string) => void) {
    const result = {};

    for (const key of Object.keys(dict)) {
        result[key] = transform(key, dict[key]);
    }

    return result;
}

map(Fruits, (key, value) => {
    value.toLowerCase();
});


map(Fruits as StringDict, (key, value) => {
    value.toLowerCase();
});
```

**Expected behavior:**
Both `map` calls succeed, because a string enum is essentially a `{[key: string]: string}`.  I ought to be able to use it anywhere that needs something indexed by string (as long as the values are appropriate).

**Actual behavior:**
index.ts(14,5): error TS2345: Argument of type 'typeof Fruits' is not assignable to parameter of type 'StringDict'.
  Index signature is missing in type 'typeof Fruits'.
index.ts(19,5): error TS2352: Type 'typeof Fruits' cannot be converted to type 'StringDict'.
  Index signature is missing in type 'typeof Fruits'.

[**Playground Link**](
http://www.typescriptlang.org/play/#src=enum%20Fruits%20%7B%0D%0A%20%20%20%20MANGO%20%3D%20'MANGO'%2C%0D%0A%20%20%20%20BANANA%20%3D%20'BANANA'%2C%0D%0A%7D%0D%0A%0D%0Atype%20StringDict%20%3D%20%7B%20%5Bkey%3A%20string%5D%3A%20string%20%7D%3B%0D%0A%0D%0Afunction%20map(dict%3A%20StringDict%2C%20transform%3A%20(key%3A%20string%2C%20value%3A%20string)%20%3D%3E%20void)%20%7B%0D%0A%20%20%20%20const%20result%20%3D%20%7B%7D%3B%0D%0A%0D%0A%20%20%20%20for%20(const%20key%20of%20Object.keys(dict))%20%7B%0D%0A%20%20%20%20%20%20%20%20result%5Bkey%5D%20%3D%20transform(key%2C%20dict%5Bkey%5D)%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20return%20result%3B%0D%0A%7D%0D%0A%0D%0Amap(Fruits%2C%20(key%2C%20value)%20%3D%3E%20%7B%0D%0A%20%20%20%20value.toLowerCase()%3B%0D%0A%7D)%3B%0D%0A%0D%0A%0D%0Amap(Fruits%20as%20StringDict%2C%20(key%2C%20value)%20%3D%3E%20%7B%0D%0A%20%20%20%20value.toLowerCase()%3B%0D%0A%7D)%3B%0D%0A%0D%0A)

**Related Issues:**
#20011, #18029, #16760

**Comment by mhegazy** [comment]
`StringDict` has a stronger contract than `Fruits`, since `Fruits["someRandomString"]` is not `string`; and thus `Fruit` is not a `StringDict`.

the oposite is true as well, since the type of `Fruite.Mango` is a specific literal type `"MANGO"` that is not just any `string`.

For these two issues the type assertion `Fruits as StringDict` fails.

consider defining the function as `object` or as generic function in `K` where `K` is the keys of the object passed, both would allow you to call it on `Fruite`. e.g.:

```ts
function map(dict: object, transform: (key: string, value: string) => void) { ... }
```
or 
```ts
function map<K extends string>(dict: Record<K, string>, transform: (key: string, value: string) => void) { ... }
```

**Comment by appsforartists** [comment]
That's presuming I control the definition of `map`.  

I feel like I ought to be able to pass a string enum into a function that requires a `[string]: string` and it should work.  I understand your point about type theory, but it fails practically here.

Is the solution when I don't control map to do `map(myEnum as {} as {[key: string]: string}`?  Not only is that ugly, but it doesn't protect me in the case that someone changes the shape of the enum (e.g. adding a non-string value).

**Comment by mhegazy** [comment]
it is unsafe, since the index signature on the enum is really `string | undefined`. but i suppose we can bend the rules here the same way we do for object literals... worth discussing.

**Comment by appsforartists** [comment]
Thanks.

The index signature on `{a: 1, b: 2}` is also really `string|undefined`, so accepting a string enum's potential for an `undefined` key feels consistent with that.

**Comment by dardino** [comment]
Another case with standard enums:

```typescript

enum MyEnum {
    ValA = 0,
    ValB = 1,
}

type IEnumTpProp<R> = {[key in keyof typeof MyEnum]: R };

var X: IEnumTpProp<string> = {
    ValA: "text1",
    ValB: "text2",
    0: "error" // correct;
};

X[MyEnum.ValA] = "no error??"; // current: no error; expected: error
```

**Comment by mhegazy** [comment]
@dardino i am afraid this is a different issue. all objects can be indexed with strings/numbers and result in an `any` if not defined. it should be reported as an error under `--noImplicitAny`.

**Comment by RyanCavanaugh** [comment]
This would be super problematic because we always allow expressions of the form `expr.propname` if `expr` has a string index signature, so there would be effectively zero "typo protection" on `propname`. We don't want to be in the situation where removing or renaming a string enum key doesn't cause new errors to appear, or where misspelling a string enum key doesn't cause an error.

**Comment by royling** [comment]
This can now be easily done with the new template literal types introduced in 4.1:

```ts
enum X {
  A = 'a',
  B = 'b',
}

type ValueOfX = `${X}`

type Y = {
  [P in ValueOfX]: number;
}

let cc: Y = {
  a: 0,
  c: 1, // errors!
}
```
