### ISSUE TITLE
Struggling to get an emit failure with 1.5

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#2290]
Previously the following would fail to emit due to parsing errors: 

```ts
var foo = 123 123;
```
Now it does emit JS: 
```js
var foo = 123;
123;
```

What's more is that something crazy like: 
```ts
2nof234@#$@#$&3421834701234!@#$!&@#$"!H#@$LK!N@#LSOD*F&(O@#*$&@#$1)"YH!@#$(O*&!@#$)
```
does an js emit: 
```js
2;
nof234;
$;
$ & 3421834701234;
!;
$;
! & ;
$;
"!H#@$LK!N@#LSOD*F&(O@#*$&@#$1)";
YH;
!;
$(O *  & !, $);
```

Are you guys aware of *anything* that will block an emit now? I just want this for a test :heart: 

refs : https://github.com/TypeStrong/atom-typescript/pull/179

**Comment by danquirk** [comment]
Maybe relevant is #1527 and #1421

**Comment by mhegazy** [comment]
Previously we blocked emit in the face of early errors. it was getting a bit arbitrary what is early and what is not, in #1527 we have relaxed this restriction, and now we emit even with errors. 
You can always use the --noEmitOnError to avoid emit with errors.

**Comment by basarat** [comment]
> and now we emit even with errors

So with `noEmitOnError` switched off *we will always emit*? is my understanding correct

**Comment by mhegazy** [comment]
For JavaScript/source maps yes. we will always emit. for declarations, we currently have a check on errors. we are still talking about this part, whether to block declaration emit on errors (current behavior) or enable it as well.

**Comment by basarat** [comment]
Thank you. That answers all my queries :heart:
