### ISSUE TITLE
Should organize imports differentiate files and folders?

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#22911]
From https://github.com/Microsoft/vscode/issues/46684

**TypeScript Version:**  TypeScript 2.9dev20180327

**Search Terms:** 
- organize imports
**Code**
In a js file:
```js
import {x} from 'a/m'
import {y} from 'a/b/c'
import {z} from 'a/z/c'

console.log(x)
console.log(y)
console.log(z)
```

1. Run organize imports

**Current behavior:**
imports sorted to:

```js
import { y } from 'a/b/c';
import { x } from 'a/m';
import { z } from 'a/z/c';
```

**Question**
From https://github.com/Microsoft/vscode/issues/46684. Should organize imports differentiate between files `a/m` and folders `a/b/...` when sorting?

**Comment by mjbvz** [comment]
Sorting paths in string order feels like the expected behavior to me. Not sure what tooling for others languages does

**Comment by andy-ms** [comment]
VSCode itself prefers to sort directories before files:

![zga](https://user-images.githubusercontent.com/19274678/37987797-0e9bd15a-31b4-11e8-8b50-0ab55ae63646.jpg)

**Comment by mjbvz** [comment]
Yes I suspect that's where @jrieken is coming from. However all imports are 'files' in my opinion

**Comment by jrieken** [comment]
> However all imports are 'files' in my opinion

Obviously. But comparing `'a/b/...'` and `'a/m';` is comparing `b` (folder) with `m` (file). 

Looking add our sources, there is `vs/nls` and deep structures in `vs/base/common/...` ,`vs/platform/common/...`, `vs/workbench/node/..` and in most files the `vs/nls`-module has a special position in the imports and rarely mixed within other import.

**Comment by mjbvz** [comment]
Closing as there has not been further interest in this issue from the community
