### ISSUE TITLE
Organize imports always returns an edit, even when imports are already sorted

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#22912]
**TypeScript Version:**  2.9.0-dev.20180327

**Search Terms:** 
- Organize imports
- TSServer

**Code**
For the js:

```js
import { x } from 'x';

console.log(x)
```

Run organize imports command

**Expected behavior:**
An edit is only returned if the imports need to be organized

**Actual behavior:**
An edit is always returned, even if the imports are already sorted

```
[Trace  - 11:03:39 AM] Response received: organizeImports (69). Request took 3 ms. Success: true 
Result: [
    {
        "fileName": "/Users/matb/projects/zoo/src/sloth.js",
        "textChanges": [
            {
                "start": {
                    "line": 1,
                    "offset": 1
                },
                "end": {
                    "line": 2,
                    "offset": 1
                },
                "newText": "import { x } from 'x';\n"
            }
        ]
    }
]
```

**Comment by mhegazy** [comment]
I am assuming you want to avoid an additional save on the file?

**Comment by mhegazy** [comment]
@amcasey anything we can do here?

**Comment by amcasey** [comment]
Right now, we pretty much always synthesize new nodes, making comparison difficult.  Conceivably, we could be more aggressive about retaining unmodified nodes, making it possible (for us) to detect when no changes have occurred.

**Comment by mjbvz** [comment]
Returning a more minimal set of edits is important in cases where the edits aren't fully sorted as well: https://github.com/microsoft/vscode/issues/86851 

As it stands, VS Code can have difficulty maintaining cursor position when the entire edit block is replaced
