### ISSUE TITLE
Add folding for multi-line parameter lists

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#22915]
From https://github.com/Microsoft/vscode/issues/46656

**TypeScript Version:**  2.9.0-dev.20180327

**Search Terms:** 
- Folding
- outlining spans
- getoutliningspans

**Code**

```ts
function foo(
    x,
    y,
    z
) {
    
}
```

**Expected behavior:**
You can fold the parameter list

**Actual behavior:**
Only the function body can be folded:

```
Result: [
    {
        "textSpan": {
            "start": {
                "line": 5,
                "offset": 2
            },
            "end": {
                "line": 7,
                "offset": 2
            }
        },
        "hintSpan": {
            "start": {
                "line": 1,
                "offset": 1
            },
            "end": {
                "line": 7,
                "offset": 2
            }
        },
        "bannerText": "...",
        "autoCollapse": true
    }
]
```

**Playground Link:**  

**Related Issues:**

**Comment by mjbvz** [comment]
@mhegazy Related question: VS Code currently uses the textSpan, not the hint span. Should we be using the hintSpan fold folding instead? Using both?

**Comment by andy-ms** [comment]
We could just add two spans, one for the body and one for the whole function, if the parameter list stretches over multiple lines.
