### ISSUE TITLE
Check if element types of Promises contain a property when issuing a missing property error

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#22923]
```ts
function f(x: Promise<string>) {
  x.toLowerCase()
}
```
**Expected**: `Property 'toLowerCase' does not exist on type 'Promise<string>'. Did you forget to await the 'Promise<string>'?`

**Actual**: `Property 'toLowerCase' does not exist on type 'Promise<string>'.`

**Comment by mhegazy** [comment]
PRs welcomed. great first issue. will diffidently add value to our users.

**Comment by mhegazy** [comment]
The follow up to this issue is to add a quick fix to add the `await` keyword.
