### ISSUE TITLE
Any plugin for Light weight editor.

### ISSUE THREAD

**Issue by vinaymavi** [Microsoft/TypeScript#2293]
Any plugin for Light weight editor. Like **Sublime text** ,**Atom** or something for linux user.

**Comment by mhegazy** [comment]
@basarat can help you more with the [atom typescript plugin](https://github.com/TypeStrong/atom-typescript). 
There should be a sublime text sublime plugin coming out soon as well. stay tuned :)

**Comment by basarat** [comment]
@vinaymavi let us know if you have any issues with atom

**Comment by clausreinke** [comment]
There are vim, emacs, and sublime plugins based on https://github.com/clausreinke/typescript-tools

Master branch is a bit behind, as TS v1.5 has not reached stable/npm registry yet, but the testing_ts1.4 branch supports TS  v1.5.

**Comment by danquirk** [comment]
In addition to the other recommendations we have a pre-alpha version of a Sublime plugin in the repo here https://github.com/Microsoft/ngconf2015demo. Forgive the hacky acquisition process, would love to get more feedback on it as we move towards a real release for it. There're also a couple existing Sublime plugins you can find in Package Control.

**Comment by danquirk** [comment]
Now available https://packagecontrol.io/packages/TypeScript
