### ISSUE TITLE
TSServer: Way to identify a folding range as being for a comment 

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#22932]
From https://github.com/Microsoft/vscode/issues/46653

**Problem**
VS Code has folding commands that only fold comments. Right now using the `getOutliningSpans` API there is no easy way to tell if a span is for a comment.

**Proposal**
Similar to #22419, add `type` field on `OutliningSpan` that identifies that span as being a comment or for code

**Comment by mhegazy** [comment]
Seems like a duplicate of https://github.com/Microsoft/TypeScript/issues/22419
