### ISSUE TITLE
visual studio unwanted formatting, especially JavaScript/TypeScript

### ISSUE THREAD

**Issue by michaeladamkatz** [Microsoft/TypeScript#22937]
I see that

https://github.com/Microsoft/TypeScript/issues/21139

has been closed.

However, I believe the bug is more far reaching than indicated in that link. Even though I have all JavaScript/TypeScript auto formatting turned off, when I edit a .js file, the problems are not just that it formats when I type open brace. It often auto formats when I paste, and often when I just press return. Furthermore, this auto-formatting does not respect my formatting rules. For instance, I have a rule to put a space after open paren, but the auto-format does not put a space.

The behavior is somewhat inconsistent, and I wonder if it might be related to smart indenting -- that is, I wonder if whenever it thinks it needs to smart indent something it also applies default formatting rules. Like if I paste something that has the wrong indentation for its context, I wonder if that triggers it. Can't figure it out.

This is a major productivity killer for me.

**Comment by michaeladamkatz** [comment]
Believe me. I have ALL of the relevant boxes checked. In the two screens you show, I have all the boxes on the first of your screens unchecked, and I have all of the boxes on your second screen checked. Also, on the "New Lines" page, I have checked "Place open brackets on new line" for both functions and control blocks. I have looked over them many, many times. I have them all checked correctly for JavaScript/TypeScript, and I also tried (without luck) to find any of the more global language settings that might apply to all languages.

I also use C++ and the formatting (i.e., my choice to not have it auto-format anything) there seems to work correctly.

I reason I posted this bug is because the other bug I referenced only focused on the brace case. I have auto-formatting happening (somewhat randomly) when I paste, when I type braces, when I press the enter key, and even when I just modify text inside an expression. Not only is the auto-formatting happening when it shouldn't, but it is ignoring all of my checked formatting choices (spaces, newlines, etc.). I will look into making a movie to show you. In the meantime, it's behaving as if it's ignoring all of those auto-format check boxes, at least most of the time.

If it's relevant, the way I am editing these Javascript files is just to open Visual Studio (Community) 2017, and then drag and drop about 20 .js files into it, along with one .html file and one .css file. I mention this just in case there is some "project level" inferred setting that it could be using.

![image](https://user-images.githubusercontent.com/358023/38010058-29042c92-320c-11e8-93ae-3de7bd12c534.png)
![image](https://user-images.githubusercontent.com/358023/38010068-2fd699b0-320c-11e8-937c-d018f7e869d5.png)
![image](https://user-images.githubusercontent.com/358023/38010076-3d1a2f4c-320c-11e8-8858-6f8f96f6dcd8.png)

**Comment by mhegazy** [comment]
What version of VS are you using?

**Comment by mhegazy** [comment]
and what version of TS?

**Comment by michaeladamkatz** [comment]
![image](https://user-images.githubusercontent.com/358023/38010234-fec72ac8-320c-11e8-99da-4c0e4a2adf92.png)

**Comment by mhegazy** [comment]
Can you give 15.7 a try?

**Comment by michaeladamkatz** [comment]
Thanks. I couldn't find 15.7, but I upgraded to 15.6.4 and it seems to have fixed everything except for the auto-formatting on open brace, as described in https://github.com/Microsoft/TypeScript/issues/21139

Sorry I didn't think upgrading to 15.6.4 would fix it. I assumed because there were still auto-format issues in 15.7 all of these auto-format issues remained as well.
