### ISSUE TITLE
Clarify guidelines for specifying default values in JsDoc

### ISSUE THREAD

**Issue by zspitz** [Microsoft/TypeScript#22947]
**TypeScript Version:**  2.9.0-dev.20180328

**Search Terms:** 
`default`
`jsdoc`
`@param`

**Code**

```ts
// within a .d.ts file
interface Connection {
    /**
     * @param {string} [ConnectionString='']
     */
    Open(ConnectionString?: string): void;
}
```

**Expected behavior:**

Should compile successfully, without linting errors.

**Actual behavior:**

TSLint fails with:
> ERROR: 612:19  no-redundant-jsdoc-2  Type annotation in JSDoc is redundant in TypeScript code.

**More information**

According to the documentation [here](https://github.com/Microsoft/TypeScript/wiki/JsDoc-support-in-JavaScript), this is one of the ways in which a default parameter can be specified.

If I remove the type annotation:
```ts
interface Connection {
    /**
     * @param [ConnectionString='']
     */
    Open(ConnectionString?: string): void;
}
```
VS Code Intellisense doesn't display the default value,

I understand that this is probably a linting issue, or an issue with the VS Code extension, or both; but I think the first step is to define whether specifying the default value without a type annotation on the parameter is valid in Typescript, and proceed accordingly.

**Comment by mhegazy** [comment]
You are missing the param name in the comment. param comments are looked up using thier names, so if the name is not specified, it does not show up. e.g.:

```ts
interface Connection {
    /**
     * @param {string} ConnectionString [ConnectionString='']
     */
    Open(ConnectionString?: string): void;
}
```

It is worth nothing that the type portion is ignored any ways. and that the default section is not treated any differently than regular comments..

**Comment by zspitz** [comment]
@mhegazy After adding in the parameter name, as you described, I still get a dtslint warning **Type annotation in JSDoc is redundant in TypeScript code.**

I'm not sure if this is a bug in Typescript, in dtslint, or is this working as designed?

**Comment by mhegazy** [comment]
The wiki is about inferring types from JavaScript files, hence the page title. so the type is needed in these cases.

In a .ts file you do not need the type.

**Comment by zspitz** [comment]
@mhegazy Understood.
