### ISSUE TITLE
Conditional types don't distribute union types with property access

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#22945]
cc @ahejlsberg 

**TypeScript Version:**  2.7.0-dev.20180327

**Search Terms:** 

**Code**

```ts
type Id<T> = T;
type Z<T> = Id<T> extends true ? Id<T> : never;
type z = Z<boolean>;
type A<T extends any[]> = T[0] extends true ? T[0] : never;
type a = A<[boolean]>;
type B<T extends {}> = { [P in keyof T]: T[P] extends true ? T[P] : never }[keyof T];
type b = B<[boolean]>;
```

**Expected behavior:**

`z`, `a`, `b` is `true`.

**Actual behavior:**

`z` is `true` but `a`, `b` is `never`.

**Playground Link:**  

**Related Issues:**

**Comment by ahejlsberg** [comment]
The conditional type in `Z` is distributive, but the conditional types in `A` and `B` are not, so this is behaving as expected. Since type aliases are equivalent to writing the expansion inline, the checked type in `Z` is a naked type parameter and thus the conditional is distributive.

**Comment by falsandtru** [comment]
I see, thanks.
