### ISSUE TITLE
Missing `elementsFromPoint` method in Document.

### ISSUE THREAD

**Issue by beauceant** [Microsoft/TypeScript#22943]
**TypeScript Version:**  2.8.1

Compilation error on lines like:
```ts
const hover = document.elementsFromPoint/* <- imagine a wavy red underline here */
(args.currentPosition.x, args.currentPosition.y)
.find(e => dragger.dropTargets.indexOf(e) >= 0);
```

> Property `elementsFromPoint` does not exist on type `Document`. Did you mean `elementFromPoint`?

I actually didn't...
It seems to me that `elementsFromPoint` should still be there (it was on TypeScript 2.7.2).

I checked MDN about [DocumentOrShadowRoot mixin](https://developer.mozilla.org/en-US/docs/Web/API/DocumentOrShadowRoot) and [Methods included (in Document) from DocumentOrShadowRoot](https://developer.mozilla.org/en-US/docs/Web/API/Document#Methods_included_from_DocumentOrShadowRoot) for reference.

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by beauceant** [comment]
Thank you. I'm sorry I couldn't help.
