### ISSUE TITLE
delete property of Map, Set... on ES3 target

### ISSUE THREAD

**Issue by SergioMorchon** [Microsoft/TypeScript#2296]
At work we have an embedded old IE8 engine that Works with ES3, and we have made an implementation of the ES6 Map and Set. Those clases have a `delete` method, which name is the same as the `delete` keyword.
So the following typescript:

``` typescript
var a = new Map<string, string>();
a.set("a", "a");
a.delete("a");
```

produces somethind like:

``` JavaScript
var a = new Map();
a.set("a", "a");
a.delete("a");
```

But the _old IE8 engine_ throws an error because of the `delete` keyword. Could ES3 target of TypeScript generate an string accessor for cases like this?

``` JavaScript
a["delete"]("a");
```

Of course, the same casi would occur with "new" etc.

Thanks!!

**Comment by NN---** [comment]
It is not only 'delete' , other keywords have this problem in IE8.
For instance try: a.new() vs. a['new']().

**Comment by DickvdBrink** [comment]
This problem is also present on Android (2.3) for what it's worth it ;)

**Comment by billti** [comment]
Just added a note to the pull request worth repeating here...

"Actually, after discussing further this is a little more involved, due to the fact that ES3 has reserved words that are not reserved words in ES5 and later. Thus, a declaration such as "var abstract = 42;" should fail to emit in ES3, but is valid in ES5+. Will think further on this.."

**Comment by grofit** [comment]
Does it look like this will be fixed within TS 2.0?

**Comment by kitsonk** [comment]
Its milestone is set for TypeScript 2.1, so no.

**Comment by mhegazy** [comment]
PRs are welcomed.

**Comment by SergioMorchon** [comment]
I think you can close this issue, regarding [Adds ES5 to ES3 transformer for reserved words](https://github.com/Microsoft/TypeScript/pull/11652) PR.
