### ISSUE TITLE
TS2448 used before its declaration error for recursive function 

### ISSUE THREAD

**Issue by mohsen1** [Microsoft/TypeScript#22975]
**TypeScript Version:**  2.9

**Search Terms:** 
Control flow, recursive functions,  used before its declaration.

**Code**
Live in the wild 
https://github.com/webpack/webpack/blob/8498fc091e5375c7c41630723e8fa7916fcc1511/lib/util/cachedMerge.js#L1
```ts
const mergeCache = new WeakMap();

function cachedMerge(first, ...args) {
	if (args.length === 0) return first;
	if (args.length > 1) {
		return cachedMerge(first, cachedMerge(...args));
	}
	const second = args[0];
	let innerCache = mergeCache.get(first);
	if (innerCache === undefined) {
		innerCache = new WeakMap();
		mergeCache.set(first, innerCache);
	}
	const cachedMerge = innerCache.get(second);
	if (cachedMerge !== undefined) return cachedMerge;
	const newMerge = Object.assign({}, first, second);
	innerCache.set(second, newMerge);
	return newMerge;
};
```

**Expected behavior:**
No Error 
**Actual behavior:**
```

lib/util/cachedMerge.js:12:10 - error TS2448: Block-scoped variable 'cachedMerge' used before its declaration.

12      return cachedMerge(first, cachedMerge(...args));
               ~~~~~~~~~~~


lib/util/cachedMerge.js:12:29 - error TS2448: Block-scoped variable 'cachedMerge' used before its declaration.

12      return cachedMerge(first, cachedMerge(...args));
                                  ~~~~~~~~~~~
```

[**Playground Link**](http://www.typescriptlang.org/play/index.html#src=const%20mergeCache%20%3D%20new%20WeakMap()%3B%0A%0Afunction%20cachedMerge(first%2C%20...args)%20%7B%0A%09if%20(args.length%20%3D%3D%3D%200)%20return%20first%3B%0A%09if%20(args.length%20%3E%201)%20%7B%0A%09%09return%20cachedMerge(first%2C%20cachedMerge(...args))%3B%0A%09%7D%0A%09const%20second%20%3D%20args%5B0%5D%3B%0A%09let%20innerCache%20%3D%20mergeCache.get(first)%3B%0A%09if%20(innerCache%20%3D%3D%3D%20undefined)%20%7B%0A%09%09innerCache%20%3D%20new%20WeakMap()%3B%0A%09%09mergeCache.set(first%2C%20innerCache)%3B%0A%09%7D%0A%09const%20cachedMerge%20%3D%20innerCache.get(second)%3B%0A%09if%20(cachedMerge%20!%3D%3D%20undefined)%20return%20cachedMerge%3B%0A%09const%20newMerge%20%3D%20Object.assign(%7B%7D%2C%20first%2C%20second)%3B%0A%09innerCache.set(second%2C%20newMerge)%3B%0A%09return%20newMerge%3B%0A%7D%3B)

**Related Issues:**

**Comment by mhegazy** [comment]
that is a bug alright. but i would recommend changing the variable name to avoid the confusion.

**Comment by mohsen1** [comment]
@sandersn @DanielRosenwasser  This is the last item in todo list of migrating Webpack to use TypeScript 

https://github.com/webpack/webpack/pull/6862

**Comment by sandersn** [comment]
This error looks correct to me. If you ever run

```js
	if (args.length > 1) {
		return cachedMerge(first, cachedMerge(...args));
	}
```

It will be an error. If you try the original sample in Chrome, you get a TDZ error from the const. If you run it through babel first you get an error that you can't call `undefined`. (Babel generates a `var cacheMerged` with the default settings on the REPL, at least.)

**Comment by mhegazy** [comment]
looking at it again, it is not a compiler bug, it is an actual bug. this code will not execude if the  number of arguments is greater than 2.

![image](https://user-images.githubusercontent.com/8000722/38635994-dd5ca956-3d7b-11e8-8cc6-e30989a55be1.png)
