### ISSUE TITLE
Ability to extend static Event interface

### ISSUE THREAD

**Issue by Busyrev** [Microsoft/TypeScript#22978]
## This is discussion question about extending builtin d.ts in projects.

In my particular case I would like to extend Event static intreface to add some static fields to Event(for special runtime that extends browser runtime).
I have found no way to do it. But for Array there is a way to use declaration merging because ArrayConstructor is separate named interface.
Here is [example on playground](https://www.typescriptlang.org/play/#src=%2F%2F%20Adding%20some%20static%20fields%20to%20Event.%0D%0A%2F%2F%20Real%20case%20mutch%20more%20complicated%2C%20Event%20replaced%20with%20inheritor%2C%20with%20many%20static%20fields%0D%0A(Event%20as%20any)%5B'MY_FIELD'%5D%20%3D%2010%3B%20%2F%2F%20somewhere%20in%20outer%20js%20scope%0D%0A%0D%0A%2F%2Fdeclare%20var%20Event%3A%20typeof%20Event%20%26%20%7B%20readonly%20MY_FIELD%3A%20number%20%7D%20%2F%2F%20cant%20redeclare%20Event%0D%0A%2F%2F%20no%20way%20to%20extend%20typeof%20Event.%0D%0A%2F%2F%20no%20named%20interface%20to%20extend%0D%0A%0D%0A%2F%2F%20But%20for%20Array%2C%20it%20is%20possible%3A%0D%0A(Array%20as%20any)%5B'MY_FIELD'%5D%20%3D%2010%3B%20%2F%2F%20somewhere%20in%20outer%20js%20scope%0D%0A%0D%0Ainterface%20ArrayConstructor%20%7B%20%0D%0A%20%20%20%20readonly%20MY_FIELD%3A%20number%3B%0D%0A%7D%0D%0A%0D%0Aconsole.log(Array.MY_FIELD)%3B%0D%0A%0D%0A%2F%2F%20this%20works%20because%20ArrayConstructor%20is%20separate%20named%20interface%20in%20d.ts%2C%20that%20can%20be%20extended%20using%20declaration%20merging%0D%0A)

Tried it in https://github.com/Microsoft/TypeScript/pull/22946
@mhegazy thanks for answers in PR.

## Question in general:
Find a way how to make any definition extendable without forking builtin d.ts files and changing them manually.

**Comment by mhegazy** [comment]
The answer to the general question is to make them classes (https://github.com/Microsoft/TypeScript/issues/574). there are some wrinkles here about what that entails though, callable constructors, and un-instantiate-able classes..

**Comment by mhegazy** [comment]
Is it required to be on the global `Event`? can you declare a wrapper?

**Comment by Busyrev** [comment]
In my case there already redefined Event(and some another browser api classes) in global by outer js code. This event does everything that original event does and some more. I can`t simply extend Event, I should replace global Event defenition to more complicated defenition (declaration merging resolves issue as I showed in PR). I don`t know any way to declare additional static fields to something that declared as 'declare Class'. Of cource I can rename extended Event to another name, but code quality became awful. Mutch better is just add special defenitions to project and define extended functionality for already available types.

**Comment by Busyrev** [comment]
Decided to fork d.ts files to project and edit them, exlude from lib section in tsconfig.
