### ISSUE TITLE
Return statement where the return is on its own line doesn't transpile correctly.

### ISSUE THREAD

**Issue by kruegeGH** [Microsoft/TypeScript#2298]
I have typescript version 1.4.1.0 and have noticed that if I have a return statement that looks something like this in my TS file

return
"This is a really long so I had to put it in on it's own line to avoid horizontal scrolling.";

after it has been transpiled into the JS file the code ends up looking like this

return;
"This is a really long so I had to put it in on it's own line to avoid horizontal scrolling.";

This is obviously problematic because the intended return statement will never execute properly now that a semicolon has been added right after the return keyword treating any line after it as if it wasn't part of the return statement to begin with.

If this has already been reported somewhere I apologize for the duplicate posting but the search terms I used to find it didn't seem to bring up any result that referenced this problem.

**Comment by DickvdBrink** [comment]
Same as #2208 and #870

**Comment by kruegeGH** [comment]
Wow, yeah that is annoying.  Maybe someday an update will be made that just combines the return statement into one (since it's supposed to be one statement anyway) and then puts the semicolon at the end of that.

Thanks for the quick reply.  I'll go ahead and close this issue then since it seems to be the correct, albeit stupid, behavior.  :)
