### ISSUE TITLE
Suggestion: Adding CSS Typed OM to typescript's internal type definition

### ISSUE THREAD

**Issue by huy-nguyen** [Microsoft/TypeScript#22999]
The [CSS Typed OM level 1 spec](https://www.w3.org/TR/css-typed-om-1/) will be released in [Chrome 66](https://developers.google.com/web/updates/2018/03/cssom). According to the announcement, it's also currently being implemented by Firefox and has received positive signal from Edge. 

I'm asking if it is possible to add the new types to the internal type definitions (`lib.d.ts` files). I can make it a PR if approved.

**Comment by huy-nguyen** [comment]
Closing because of [`lib.d.ts` contribution guidelines](https://github.com/Microsoft/TSJS-lib-generator#when-should-a-dom-api-be-included-here).

**Comment by zheeeng** [comment]
Any working definition in DefinitelyTyped ?
