### ISSUE TITLE
T[K] should be never when T is never

### ISSUE THREAD

**Issue by kpdonn** [Microsoft/TypeScript#23005]
**TypeScript Version:**  2.9.0-dev.20180329

**Search Terms:** 
indexed access type, index type never

**Code**
```ts
type Example<T extends Record<'a', string>> = T['a']

type Result1 = Example<{ a: "x" } | { a: "y" }> // type of Result1 is "x" | "y"
type Result2 = Example<{ a: "x" }> // type of Result2 is  "x"
type Result3 = Example<never> // type of Result3 is any 
```

**Expected behavior:**
Type of `Result3` to be `never`

**Actual behavior:**
Type of `Result3` is `any`

**Playground Link:** 
[Link](https://www.typescriptlang.org/play/#src=type%20Example%3CT%20extends%20Record%3C'a'%2C%20string%3E%3E%20%3D%20T%5B'a'%5D%0D%0A%0D%0Atype%20Result1%20%3D%20Example%3C%7B%20a%3A%20%22x%22%20%7D%20%7C%20%7B%20a%3A%20%22y%22%20%7D%3E%20%2F%2F%20type%20of%20Result1%20is%20%22x%22%20%7C%20%22y%22%0D%0Atype%20Result2%20%3D%20Example%3C%7B%20a%3A%20%22x%22%20%7D%3E%20%2F%2F%20type%20of%20Result2%20is%20%20%22x%22%0D%0Atype%20Result3%20%3D%20Example%3Cnever%3E%20%2F%2F%20type%20of%20Result3%20is%20any%20)

**Workaround**
Now that #22042 is resolved this can be worked around with 
```ts
type Workaround<T extends Record<'a', string>> = T[(keyof T) & 'a']
type Result4 = Workaround<never> // type of Result4 is never in typescript@next
```

**Related Issues:**
Similar to #22042. That was about type of `T[K]` when `K` was `never` while this is about when `T` is `never`.

**Comment by agentcooper** [comment]
```typescript
type Example<T> = T extends Record<'a', string> ? T['a'] : never;
```
maybe?

**Comment by kpdonn** [comment]
That actually only works because of how conditional types work with type parameters. It distributes the condition over any unions, and `never` is treated as an empty union. So it actually isn't that `never` is failing the condition there, it's that the condition is never even tested.

You can see it more clearly with something like 

```ts
type Example2<T> = T extends Record<'a', string> ? true : false;
type Result2 = Example2<never> // never instead of either true or false
```
