### ISSUE TITLE
Narrowing a union from generic fails when union is not the first generic

### ISSUE THREAD

**Issue by luke-john** [Microsoft/TypeScript#23017]
**TypeScript Version:** 
* 2.9.0-dev.20180330
* 2.8.1
* 2.7.2

**Search Terms:** 
* generic order
* map index generic

**Code**

```ts
type Tags  = { foo: ''; bar: ''; baz: ''; }
type Tag = keyof Tags 

type GetTag<UsedTag extends keyof Tags> = keyof { [tag in UsedTag]: any } 

type DoThingVersionOne =
  <UsedTag extends Tag = Tag, Props = {}>(tag: UsedTag) => GetTag<UsedTag>

const doThingVersionOne: DoThingVersionOne = {} as any

const fooOne = doThingVersionOne('foo')                       // expected | type = "foo"
const fooOneITag = doThingVersionOne<'foo'>('foo')            // expected | type = "foo"
const fooBarITagIProps = doThingVersionOne<'foo', {}>('foo')  // expected | type = "foo"

type DoThingVersionTwo =
    <Props = {}, UsedTag extends Tag = Tag>(tag: UsedTag) => GetTag<UsedTag>

const doThingVersionTwo: DoThingVersionTwo = {} as any

const fooTwo = doThingVersionTwo('foo')                       // expected | type = "foo"
const fooTwoITag = doThingVersionTwo<{}>('foo')               // unexpected | type "foo" | "bar" | "baz" 
const fooTwoITagIProps = doThingVersionTwo<{}, 'foo'>('foo')  // expected | type "foo" 
```

**Expected behavior:**

The order of a generic does not effect it's behaviour when narrowing from a union.

**Actual behavior:**

The order of a generic does effect it's behaviour when narrowing from a union.

**Playground Link:** 

[Playground Reproduction](https://www.typescriptlang.org/play/index.html#src=type%20Tags%20%20%3D%20%7B%20foo%3A%20''%3B%20bar%3A%20''%3B%20baz%3A%20''%3B%20%7D%0D%0Atype%20Tag%20%3D%20keyof%20Tags%20%0D%0A%0D%0Atype%20GetTag%3CUsedTag%20extends%20keyof%20Tags%3E%20%3D%20keyof%20%7B%20%5Btag%20in%20UsedTag%5D%3A%20any%20%7D%20%0D%0A%0D%0Atype%20DoThingVersionOne%20%3D%0D%0A%20%20%3CUsedTag%20extends%20Tag%20%3D%20Tag%2C%20Props%20%3D%20%7B%7D%3E(tag%3A%20UsedTag)%20%3D%3E%20GetTag%3CUsedTag%3E%0D%0A%0D%0Aconst%20doThingVersionOne%3A%20DoThingVersionOne%20%3D%20%7B%7D%20as%20any%0D%0A%0D%0Aconst%20fooOne%20%3D%20doThingVersionOne('foo')%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20expected%20%7C%20type%20%3D%20%22foo%22%0D%0Aconst%20fooOneITag%20%3D%20doThingVersionOne%3C'foo'%3E('foo')%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20expected%20%7C%20type%20%3D%20%22foo%22%0D%0Aconst%20fooBarITagIProps%20%3D%20doThingVersionOne%3C'foo'%2C%20%7B%7D%3E('foo')%20%20%2F%2F%20expected%20%7C%20type%20%3D%20%22foo%22%0D%0A%0D%0Atype%20DoThingVersionTwo%20%3D%0D%0A%20%20%20%20%3CProps%20%3D%20%7B%7D%2C%20UsedTag%20extends%20Tag%20%3D%20Tag%3E(tag%3A%20UsedTag)%20%3D%3E%20GetTag%3CUsedTag%3E%0D%0A%0D%0Aconst%20doThingVersionTwo%3A%20DoThingVersionTwo%20%3D%20%7B%7D%20as%20any%0D%0A%0D%0Aconst%20fooTwo%20%3D%20doThingVersionTwo('foo')%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20expected%20%7C%20type%20%3D%20%22foo%22%0D%0Aconst%20fooTwoITag%20%3D%20doThingVersionTwo%3C%7B%7D%3E('foo')%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20unexpected%20%7C%20type%20%22foo%22%20%7C%20%22bar%22%20%7C%20%22baz%22%20%0D%0Aconst%20fooTwoITagIProps%20%3D%20doThingVersionTwo%3C%7B%7D%2C%20'foo'%3E('foo')%20%20%2F%2F%20expected%20%7C%20type%20%22foo%22%20%0D%0A)

**Related Issues:**
https://github.com/Microsoft/TypeScript/issues/17713
https://github.com/Microsoft/TypeScript/issues/21631
https://github.com/Microsoft/TypeScript/issues/12424

**Comment by jack-williams** [comment]
The order matters because of the default values you have and in the unexpected case you're partially instantiating the generics. The following two are equivalent and give the same result.

```ts
const fooTwoITagWithDefault = doThingVersionTwo<{}>('foo') //  "foo" | "bar" | "baz" 
const fooTwoITag = doThingVersionTwo<{}, Tag>('foo') //  "foo" | "bar" | "baz" 
```

I believe partial application of generics turns off inference for those that are omitted (they fall back to their default value).

**Comment by luke-john** [comment]
Ahh, right. I was thinking when providing generics, only the ones passed would be instantiated.

Happy to close this, thanks for your quick response and explanation.
