### ISSUE TITLE
Inconsistent behavior for typeof default with function and object literal default exports

### ISSUE THREAD

**Issue by ethanresnick** [Microsoft/TypeScript#23010]
**TypeScript Version:**  2.8.1

**Search Terms:** typeof default

**Code**

```ts
// a.ts
export default function () {
  return true;
}

export type X = typeof default;  // () => boolean

// b.ts
export default { a: true }
export type X = typeof default; // error, cannot find name default
```

**Expected behavior:**
In b.ts, type X = `{ a: boolean }`

My guess is that maybe this may be happening because of the `.name` property on functions, for which there's no object equivalent? But, regardless, I don't see why these cases shouldn't be treated equivalently.

**Actual behavior:**
Error in b.ts. See comment

**Playground Link:**
N/A because I can't put two default exports in the same playground

**Comment by mhegazy** [comment]
Both should be errors i would say. there should not be a name `default` visible in scope in either cases.

**Comment by ethanresnick** [comment]
I'd say both should be allowed... while there's no name `default` in either scope, it is useful to be able to reference the type of the default export, and there's no risk of conflict here with a different `default`, since `default` is a reserved word/invalid identifier name.

**Comment by mhegazy** [comment]
We have kept parity between value and type space, and that has served us well. do not see a reason to stop doing that.
