### ISSUE TITLE
Partial mapped types on constrained generics should allow object literals to specify only known keys

### ISSUE THREAD

**Issue by dhruvrajvanshi** [Microsoft/TypeScript#23015]
There's some odd behaviour with mapped types on generic types with extends constraints.

**TypeScript Version:**  2.9.0-dev.20180330

**Search Terms:** 
generic constraint 

**Code**

```ts
type Entity = {
  id: string;
};

function f<T extends Entity>() {
  const where: { [K in keyof T]?: T[K] } = {
    id: "asdf"
  }; // this throws type error
  where.id = "asdf"; // this is valid
}

```

**Expected behavior:**
No type error

**Actual behavior:**
Getting type error on first assignment: Type '{ id: "asdf"; }' is not assignable to type '{ [K in keyof T]?: T[K]; }'.

**Playground Link:**  

**Related Issues:**
None that I know of

The above code snippet throws a type error even though it is safe. Presumably, because only a subset of keys of T are known at this point, the compiler can't check if the given object literal contains all keys of T. However, the type is partial and skipping the unknown keys is perfectly safe. It would be nice if this could be detected and allowed or at least a better error be produced. I spent way too much time trying to figure out why this didn't work.

**Comment by RyanCavanaugh** [comment]
Duplicate #13442 and others
