### ISSUE TITLE
Conditional types don't narrow a type for mapped type index

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#23016]
cc @ahejlsberg 

**TypeScript Version:**  master

**Search Terms:** 

**Code**

```ts
type M<T> = [T] extends [string] ? { [i: T]: any; } : never;
type N<T> = [string] extends [T] ? { [i: T]: any; } : never;
type D<T> = T extends string ? { [P in T]: any; } : never;
type R<T> = T extends string ? Record<T, any> : never;
```

**Expected behavior:**

pass or error only with the first case, the second should be allowed at least; but type narrowing with the second case is not supported.

**Actual behavior:**

```
$ node built/local/tsc.js --noEmit index.ts
index.ts(1,39): error TS1337: An index signature parameter type cannot be a union type. Consider using a mapped object type instead.
index.ts(2,39): error TS1023: An index signature parameter type must be 'string' or 'number'.
```

**Playground Link:**  

**Related Issues:**

**Comment by jack-williams** [comment]
I'm not sure if this is to do with conditional types and narrowing, rather index signatures in general. All off the following have the same error as you link:

```ts
type A<T extends string> = { [i: T]: any; }
type B<T> = { [i: T & string]: any; }
type C = { [i: never]: any; }
```

**Comment by falsandtru** [comment]
I fixed my code. I think an error with `T extends string ? { [i: T]: any; } : never;` is correct but `[T] extends [string] ? { [i: T]: any; } : never;` is not.

**Comment by jack-williams** [comment]
When would you want an index signature for a `T` that is a subtype of `string`, but isn't actually just `string`? This would mean the following would have to be valid, when they currently are not:
```ts
type neverIndex = { [i: never]: any; }
type literalIndex = { [i: 'hello']: any; }
```

**Comment by falsandtru** [comment]
Then `[string] extends [T] ? { [i: T]: any; } : never;` should work.

**Comment by falsandtru** [comment]
Merge into #23019.
