### ISSUE TITLE
Enable the .js and .es file extensions for TypeScript files

### ISSUE THREAD

**Issue by robertsundstrom** [Microsoft/TypeScript#2302]
Enable the .js, .jsx, .es and .es6 file extensions for TS compiler file inputs and module imports. This is already supported by other transpilers, such as babel.

The feature would ideally be added as an option in the compiler. With .js together with .ts on by default, but .ts still being prefered.

This would cause the files with the enabled extensions to, just as .ts-files today, be processed (e.g. in and IDE), and transformed if the options so allow it.

One objection to this would be that this could potentially confuse scripts that are using TypeScript-specific features with scripts using official ES6 features. I don't personaly see this as an issue. It is up to the developers to come up with conventions in their own projects.

**Comment by dpen2000** [comment]
This would probably mean GitHub wouldn't be able to detect whether a repository is using javascript or typescript

**Comment by NoelAbrahams** [comment]
> This would cause the files with the enabled extensions to, just as .ts-files today, be processed (e.g. in and IDE), and transformed if the options so allow it.

What sort of processing are you suggestion for `.js` files?

**Comment by robertsundstrom** [comment]
@NoelAbrahams Treating them as TypeScript-files and selectively enabling certain features.

**Comment by CyrusNajmabadi** [comment]
@robertsundstrom  If you would like them to be treated as TypeScript files, why not rename them to .ts?

**Comment by NoelAbrahams** [comment]
I actually ran into a use-case today.

We have `moment.js` in a Visual Studio TypeScript project. This is the only JavaScript file in the project. The project has the options "combine output into a single file" and "no implcity any" set.

We want to include `moment.js` in the combined output file. 

I tried setting `Build Action:  TypeScriptCompile` on the properties page for `moment.js`, but got the error:

> moment.js' must have extension '.ts' or '.d.ts'

For the use-case above we cannot simply change the extension to `.ts` because `moment.js` is not annotated and will not compile under the `noimplicitany` flag.

**Comment by mhegazy** [comment]
@NoelAbrahams this is slightly different from the original proposal from @robertsundstrom , you want the compiler to read in .js files, write them to the output, but do not report any errors in them. is this accurate?

**Comment by NoelAbrahams** [comment]
@mhegazy, I would see it as an enhancement to the original request. The following would happen:

* `moment.js` would be parsed by the compiler and the compiler would report any syntax errors.
* `noimplicitany` would be ignored, since `.js` files won't have any type annotation in any case.
* The `.js` would be included in the output, hence all output options should be honoured, e.g. redirect-output-to-directory, combine-output-into-single-file.

**Comment by mhegazy** [comment]
What about other semantic errors, e.g.:

```ts 
var x = 2;
if (false) {
     x = "string":
}
```
or 
```ts
var x = 1;

var x = "";
```

should these be reported for moment.js?

**Comment by NoelAbrahams** [comment]
I think for most users the processing of `.js` files is going to be for dealing with very unusual requirements. 

We need to include `moment.js` in a project because non of the major CDN providers that we use (Google/Microsoft) currently host this library.

If people want the compiler to catch semantic errors then they should be writing TypeScript. I think for `.js` files only syntax errors should be reported.

**Comment by Raynos** [comment]
:+1:

I would also like to typecheck javascript files.

My use case is to use the typescript type checker but still author ES5 code that does not need to be compiled for someone to use it.

**Comment by ianfp** [comment]
+1 Being able to compile files with a .js extension using `tsc` would be very useful for people like me, who are exploring the possibility of migrating an existing Javascript project to TypeScript. I don't want to have to rename all of my .js files, and I certainly don't want to hack Typescript like [this guy suggests](http://elegantcode.com/2014/05/18/how-to-compile-plain-js-javascript-files-with-the-typescript-compiler/).

**Comment by kitsonk** [comment]
@ianfp it sounds like a totally different problem/subject in that you are looking for a JavaScript -> TypeScript migrator that helps you easily get on the right path of converting a code base from JavaScript to TypeScript.  Sounds like an interesting project...

**Comment by ianfp** [comment]
@kitsonk Perhaps I misunderstood what this issue is about... but yes, I'd basically like to replace [r.js](http://requirejs.org/docs/optimization.html) with `tsc` as my compiler and then start migrating the code from there. Perhaps this is not possible?

**Comment by forbesmyester** [comment]
I'd like to run TS as an extra to ESLint (sometimes) but also be able to benefit from some of the advanced type stuff you guys have available autocompletion in VIM.

**Comment by adidahiya** [comment]
@forbesmyester what do you mean by "as an extra to ESLint (sometimes)"? FYI https://github.com/palantir/tslint exists

**Comment by forbesmyester** [comment]
@adidahiya did not know about tslint, does it give the same results of mistakes that TypeScript itself seems to? In which case that part of the desire is no longer relevant, would still like to use it for the VIM omni completion / hints as they are really good. Requiring a .ts extension is annoying as it means that you need buy in from a whole team as apposed to just a single developer using it for some of the smaller (editor / linting) enhancements.

**Comment by ldminoc** [comment]
Sorry for being late to the conversation but I'm currently working on a project where it would be nice to have the original requested feature. Our project code base contains a mix of open source derivative code written in js (es5), es6 and TypeScript. It would be nice if TypeScript could be used to transpile es6 as well, rather than resorting to another transpiler such as babel to process the es6 source.

**Comment by redpsalm** [comment]
I am in the same situation and in fact waiting for this feature to move to VSC!

**Comment by anievagomez** [comment]
I have the same needs as ldminoc and robertsundstrum.

**Comment by mhegazy** [comment]
@anievagomez can you elaborate? do you have other es6 assets that you want the TS compiler to transpile,  or just es5 sources that you do not want to migrate but still want to code against?

**Comment by ldminoc** [comment]
@mhegazy,  it seems intuitive to me that any serious 'ambitious' application or enhancement to existing long-lived projects (incrementally transitioning to newer technology) would need both capabilities when considering adopting TypeScript, or face a massive uplifting exercise.

**Comment by mhegazy** [comment]
@ldminoc i am interested in building an intuition of what a .js file "mean" in a typescript context. is it a reference (e.g. library, sources from that you do not intend to migrate to ts) that you would code against, or a source (i.e. an ES6 JS file that you want transpiled and bundled with your other .ts file outputs).

**Comment by forbesmyester** [comment]
A .ts file can just mean a JavaScript file with some ES6 features and
TypeScript's amazing editor support for guessing types and function
metadata. In fact it could even just be the latter if the code is well
written ES6...

At the moment I'm not sure TypeScript is the right choice for a project,
but some form of ES6 is probably the way to go, forcing me to change all my
extensions is too big an ask at this point.

Matt

**Comment by kitsonk** [comment]
> forcing me to change all my extensions is too big an ask at this point

You are right...

```bash
find . -name "*.js" -exec bash -c 'mv "$1" "$(sed "s/\.js$/.ts/" <<< "$1")"' - '{}' \;
```

is too much to ask...  The whole project is doomed.

**Comment by forbesmyester** [comment]
I can write simple Bash too, that's not the issue.

Not all projects are single person project and some people __really__ hate
TypeScript. Also How do I ensure that I'm not breaking everybody's syntax
highlighting and plugins on whatever editors they're using?

It'd be nice if I could use TypeScript without anyone else being effective,
if I'm careful, at least for a short period.

Matt

**Comment by kitsonk** [comment]
> I can write simple Bash too, that's not the issue.

What is the issue then?  The assertion was "forcing me to change all my extensions is too big an ask at this point"... Why?

**Comment by forbesmyester** [comment]
Not all projects are single person project and some people __really__ hate
TypeScript. Also How do I ensure that I'm not breaking everybody's syntax
highlighting and plugins on whatever editors they're using?

Matt

**Comment by mhegazy** [comment]
@forbesmyester what you are looking for is #4793 then, correct? you want the TS developer experience (completion, highlighting, etc..) in an ES6 source file, without committing to using types, TS-specific-syntax, etc.. is this accurate?

**Comment by ldminoc** [comment]
@mhegazy, it would be yes to both:
1. es5 files treated as external modules, not requiring transpilation (but uplifted with typing support via .d.ts files)
2. es6 files (files using es6 features) requiring transpilation to specified --target

Both are bundled but that will be the responsibility of a third-party tool such as webpack, hth.

**Comment by mhegazy** [comment]
consuming .js and .jsx is now allowed using --allowJS (see https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#including-js-files-with---allowjs)
