### ISSUE TITLE
Field not set by constructor early enough

### ISSUE THREAD

**Issue by pankleks** [Microsoft/TypeScript#23020]
Is this correct behavior?

I was expecting `b` to be set by `foo2` constructor before executing overloaded `doStuff` function.

```ts
abstract class foo {
    constructor(protected a) {
        this.doStuff();
    }

    abstract doStuff()
}

class foo2 extends foo {
    constructor(a, protected b) {
        super(a);
    }

    doStuff() {
        if (this.b === undefined)
            alert("Boo!");
    }
}

new foo2(10, 20);
```
example here: [playground](http://www.typescriptlang.org/play/#src=abstract%20class%20foo%20%7B%0D%0A%20%20%20%20constructor(protected%20a)%20%7B%0D%0A%20%20%20%20%20%20%20%20this.doStuff()%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20abstract%20doStuff()%0D%0A%7D%0D%0A%0D%0Aclass%20foo2%20extends%20foo%20%7B%0D%0A%20%20%20%20constructor(a%2C%20protected%20b)%20%7B%0D%0A%20%20%20%20%20%20%20%20super(a)%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20doStuff()%20%7B%0D%0A%20%20%20%20%20%20%20%20if%20(this.b%20%3D%3D%3D%20undefined)%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20alert(%22Boo!%22)%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Anew%20foo2(10%2C%2020)%3B)

TS: 2.7.2

**Comment by andy-ms** [comment]
It's illegal to use `this` before calling the super constructor. So a superclass constructor generally shouldn't call virtual methods.

**Comment by pankleks** [comment]
ok thanks, could it be tested by TS?

**Comment by andy-ms** [comment]
I think that would be pretty hard to do in general, though you could avoid the problem completely by writing a lint rule that prevents a constructor from calling abstract methods.

**Comment by pankleks** [comment]
ok thanks:)
