### ISSUE TITLE
Conditional types don't work with passed never type

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#23022]
cc @ahejlsberg 

**TypeScript Version:**  2.7.0-dev.20180330

**Search Terms:** 

**Code**

```ts
type C<T, U> = T extends U ? true : false;
type A = never extends void ? true : false;
type B = C<never, void>;
```

**Expected behavior:**

`A` and `B` are `true`.

**Actual behavior:**

`A` is `true`, `B` is `never`.

**Playground Link:**  

**Related Issues:**

**Comment by jack-williams** [comment]
I believe this is working as intended: `C` is distributive but `A` is not. `C` is being distributed zero times as `never` is empty.

**Comment by falsandtru** [comment]
`A` is inlined `B`. Inlining must not make any different behavior.

**Comment by mhegazy** [comment]
> A is inlined B. Inlining must not make any different behavior.

not really. a type is distributed if it has a naked type parameter in the condition close. so 

```ts
type inline = number | string extends string ? true : false; // false

type deferred<T> = T extends string ? true : false;
type d = deferred<number | string>;  // boolean
```

The rational here that using a type parameter in the condition position is like a function on the input, and is expected to distribute, where as an actual union type is mean to be used as is.

**Comment by falsandtru** [comment]
I understood, this is not inlining. A passed union type is not determined as its exact union type yet. It also can be a subtype.

**Comment by falsandtru** [comment]
A workaround is evaluation by `never extends T`:

```ts
type C<T, U> = never extends T ? never extends U ? true : false : T extends U ? true : false;
type c1 = never extends void ? true : false; // true
type c2 = C<never, void>; // true
```

**Comment by falsandtru** [comment]
A workaround:

```ts
type C<T, U> = [T] extends [never] ? 1 : T extends U ? 1 : 0;
type a = C<never, void>; // 1
type b = C<never, never>; // 1
type c = C<boolean, true>; // 0 | 1
```
