### ISSUE TITLE
window.opener should not be readonly

### ISSUE THREAD

**Issue by lediur** [Microsoft/TypeScript#23032]
**TypeScript Version:**  2.8.1 (not present in 2.7.2)

**Search Terms:**  `opener` (found #10379, but this was back in 2.0 / 2016), `window readonly`, `set window opener to null typescript 2.8`

**Code**

```ts
const newWindow = window.open(url);
if (newWindow) {
  newWindow.opener = null;
}
```

**Expected behavior:**
`window.opener` should be assignable to `null` for security reasons (e.g. https://github.com/Microsoft/monaco-editor/issues/601). Setting the `noopener` window feature only works in modern browsers.

**Actual behavior:**
`window.opener` is declared as `readonly`. **This appears to be a 2.8 regression of #10379**

**Playground Link:**  [here](http://www.typescriptlang.org/play/#src=window.opener%20%3D%20null%3B)

**Related Issues:**
#10379

**Comment by mhegazy** [comment]
Should be fixed by Microsoft/TSJS-lib-generator#397. Fix should be included in 2.8.2 release.

**Comment by mhegazy** [comment]
reported earlier in https://github.com/Microsoft/TypeScript/issues/10379#issuecomment-376966533

**Comment by lediur** [comment]
Oops, I saw that yesterday but for some reason didn't see the last comment. Good to know! Thanks for following up.
