### ISSUE TITLE
union type does not work in classes/interfaces

### ISSUE THREAD

**Issue by babkenmes** [Microsoft/TypeScript#23031]
TypeScript Version: 2.4.2

> Have tryed in http://www.typescriptlang.org/play the error is the same

**Code**
```ts
class Action { 
    type: string;
    payload: number;
}

type ActionCreator = ((page:number)=>Action) | Action

class Filter {
    actionCreator: ActionCreator;
    subStore: string;
}
const x: ActionCreator = (page: number) => {
    return {
        type: "foo",
        payload: 1
    }
}
const y: Filter = {
    actionCreator: (page: number) => { return {
        type: "foo",
        payload: 1
    } },
    subStore:"foo"
}

y.actionCreator(5);
x(5);
```
For `y.actionCreator(5)` I get
> Cannot invoke an expression whose type lacks a call signature. Type 'ActionCreator' has no compatible call signatures.

**Expected behavior:** / **Actual behavior:**
As you can see it works for `x`, it should work the same way for the class/interface implementation.

[Playground Link](http://www.typescriptlang.org/play/#src=class%20Action%20%7B%20%0D%0A%20%20%20%20type%3A%20string%3B%0D%0A%20%20%20%20payload%3A%20number%3B%0D%0A%7D%0D%0A%0D%0Atype%20ActionCreator%20%3D%20((page%3Anumber)%3D%3EAction)%20%7C%20Action%0D%0A%0D%0Aclass%20Filter%20%7B%0D%0A%20%20%20%20actionCreator%3A%20ActionCreator%3B%0D%0A%20%20%20%20subStore%3A%20string%3B%0D%0A%7D%0D%0Aconst%20x%3A%20ActionCreator%20%3D%20(page%3A%20number)%20%3D%3E%20%7B%0D%0A%20%20%20%20return%20%7B%0D%0A%20%20%20%20%20%20%20%20type%3A%20%22foo%22%2C%0D%0A%20%20%20%20%20%20%20%20payload%3A%201%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0Aconst%20y%3A%20Filter%20%3D%20%7B%0D%0A%20%20%20%20actionCreator%3A%20(page%3A%20number)%20%3D%3E%20%7B%20return%20%7B%0D%0A%20%20%20%20%20%20%20%20type%3A%20%22foo%22%2C%0D%0A%20%20%20%20%20%20%20%20payload%3A%201%0D%0A%20%20%20%20%7D%20%7D%2C%0D%0A%20%20%20%20subStore%3A%22foo%22%0D%0A%7D%0D%0A%0D%0Ay.actionCreator(5)%3B%0D%0A%0D%0Ax(5).payload%3B%0D%0Ax(5).type%3B%0D%0A)

**Related Issues:**

**Comment by andy-ms** [comment]
The reason it works for `x` is that for a const the compiler ignores the type annotation and uses the real, non-union type. For properties in an object literal it doesn't do that, so `y` really is `Filter`, and `y.actionCreator` is a union type which might not be callable.

**Comment by babkenmes** [comment]
I am sorry I do not understand what means

>  for a const the compiler ignores the type annotation and uses the real, non-union type

because the result of calling `x` is of type `Action`

``` ts
x(5).payload;
x(5).type;
```
sorry the playground link was old I have updated it with the same code as in the issue.
[link](http://www.typescriptlang.org/play/#src=class%20Action%20%7B%20%0D%0A%20%20%20%20type%3A%20string%3B%0D%0A%20%20%20%20payload%3A%20number%3B%0D%0A%7D%0D%0A%0D%0Atype%20ActionCreator%20%3D%20((page%3Anumber)%3D%3EAction)%20%7C%20Action%0D%0A%0D%0Aclass%20Filter%20%7B%0D%0A%20%20%20%20actionCreator%3A%20ActionCreator%3B%0D%0A%20%20%20%20subStore%3A%20string%3B%0D%0A%7D%0D%0Aconst%20x%3A%20ActionCreator%20%3D%20(page%3A%20number)%20%3D%3E%20%7B%0D%0A%20%20%20%20return%20%7B%0D%0A%20%20%20%20%20%20%20%20type%3A%20%22foo%22%2C%0D%0A%20%20%20%20%20%20%20%20payload%3A%201%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0Aconst%20y%3A%20Filter%20%3D%20%7B%0D%0A%20%20%20%20actionCreator%3A%20(page%3A%20number)%20%3D%3E%20%7B%20return%20%7B%0D%0A%20%20%20%20%20%20%20%20type%3A%20%22foo%22%2C%0D%0A%20%20%20%20%20%20%20%20payload%3A%201%0D%0A%20%20%20%20%7D%20%7D%2C%0D%0A%20%20%20%20subStore%3A%22foo%22%0D%0A%7D%0D%0A%0D%0Ay.actionCreator(5)%3B%0D%0A%0D%0Ax(5).payload%3B%0D%0Ax(5).type%3B%0D%0A)

and if we have anither `z` of type `ActionCreator`

```ts
const z:ActionCreator = {
        type: "foo",
        payload: 1
}
z.payload;
z.type;
```

this also works as expected

**Comment by babkenmes** [comment]
Ok, I understand the problem now :godmode: 

It tracks the object, so if we do

```ts
let x: ActionCreator = (page: number) => {
    return {
        type: "foo",
        payload: 1
    }
}
x = {
    type: "foo",
    payload: 1
};
x(5).payload;  //Cannot invoke an expression whose type lacks a call signature. Type 'Action' has no compatible call signatures.
x.payload;    //OK
```
So as I understand it can not track objects so, it is disabled for some cases, but in some cases it can work not as intended for example`
```ts
const x = {
    foo: (page: number) => {
        return {
            type: "foo",
            payload: 1
        }
    }
};
x.foo(5).payload;
let z = { bar: x }; //OK here
function someFunc(data: { bar: { foo : ActionCreator} }) { 
    data.bar.foo = {  //OK here
        type: "bar",
        payload: 2
    }
}
someFunc(z);

console.log(x.foo(5)) //here compiler does not give any error but at run-time, x.foo is not a function
```
