### ISSUE TITLE
New option to remove spaces after Template Literals

### ISSUE THREAD

**Issue by miZyind** [Microsoft/TypeScript#23047]
**VSCode Version:**  1.21.1

**TypeScript Version:**  2.9.0-dev.20180401

**Search Terms:** "Template literals format", "Template strings format", "Tagged template literals format"

**Code:**

1. Declare a template literals function:
```ts
function aFunctionWhichReturnsAnotherTemplateLiterals() {
  return (templateStringsArr: TemplateStringsArray) => {
    console.log(templateStringsArr);
  };
}

aFunctionWhichReturnsAnotherTemplateLiterals()`123`;
```

2. Use VSCode auto format:
```ts
function aFunctionWhichReturnsAnotherTemplateLiterals() {
  return (templateStringsArr: TemplateStringsArray) => {
    console.log(templateStringsArr);
  };
}

aFunctionWhichReturnsAnotherTemplateLiterals() `123`; // <---  Why vscode add this extra space?
```

**In another situation:**

1. Styling components through [styled-component](https://www.styled-components.com/docs/basics#styling-any-components)
```ts
const StyledLink = styled(Link)`
  color: palevioletred;
  font-weight: bold;
`;
```

2. After auto format:
```ts
const StyledLink = styled(Link) ` // <--- This is kinda annoying :(
  color: palevioletred;
  font-weight: bold;
`;
```

**After I comment out this code, VSCode will not add the annoying space anymore!**
```js
// Line 76663 ~ 76665 in node_modules/typescript/lib/tsserver.js

rule("SpaceBetweenForAndAwaitKeyword", 88, 121, [isNonJsxSameLineTokenContext], 2),
// rule("SpaceBetweenStatements", [20, 81, 82, 73], anyToken, [isNonJsxSameLineTokenContext, isNonJsxElementOrFragmentContext, isNotForContext], 2),
rule("SpaceAfterTryFinally", [102, 87], 17, [isNonJsxSameLineTokenContext], 2),
```

**Playground Link:** [Link](https://www.typescriptlang.org/play/#src=function%20aFunctionWhichReturnsAnotherTemplateLiterals()%20%7B%0D%0A%20%20return%20(templateStringsArr%3A%20TemplateStringsArray)%20%3D%3E%20%7B%0D%0A%20%20%20%20console.log(templateStringsArr)%3B%0D%0A%20%20%7D%3B%0D%0A%7D%0D%0A%0D%0AaFunctionWhichReturnsAnotherTemplateLiterals()%60123%60%3B)

Maybe TS team can provide a new option for this situation?

**Comment by HerringtonDarkholme** [comment]
It should be a bug. Template literal isn't a separate statement.

**Comment by Ken703** [comment]
@mhegazy I believe I have a fix for this. Could you please add me as a collaborator so I'm able to push my changes up and open a PR?
