### ISSUE TITLE
CFA within guard functions conditions reset type if there is reassigning the value

### ISSUE THREAD

**Issue by cevek** [Microsoft/TypeScript#23044]
**TypeScript Version:**  2.9.0-dev.20180325

**Search Terms:** 

**Code**

```ts
interface A {a: number}
interface B extends A {b: number}
function isB(val: A): val is B {
    return true;
}
var a!: A;
if (isB(a)) {
   a = a;
   // or a = {} as B;
   a.b; // error, a is A
}
```

**Expected behavior:**

**Actual behavior:**

**Playground Link:** [link](https://www.typescriptlang.org/play/#src=interface%20A%20%7Ba%3A%20number%7D%0D%0Ainterface%20B%20extends%20A%20%7Bb%3A%20number%7D%0D%0Afunction%20isB(val%3A%20A)%3A%20val%20is%20B%20%7B%0D%0A%20%20%20%20return%20true%3B%0D%0A%7D%0D%0Avar%20a!%3A%20A%3B%0D%0Aif%20(isB(a))%20%7B%0D%0A%20%20%20a%20%3D%20a%3B%0D%0A%20%20%20%2F%2F%20a%20%3D%20%7B%7D%20as%20B%3B%0D%0A%20%20%20a.b%3B%20%2F%2F%20error%2C%20a%20is%20A%0D%0A%7D)

**Related Issues:**

**Comment by j-oliveras** [comment]
Related to #9998.

I think, this is the expected behavior.

**Comment by mhegazy** [comment]
Once an assignment occurs to the references all assumptions are dropped. the compiler can not guarantee at that point that the assumptions it made still hold. specially that it makes assumptions about property types as well.

**Comment by cevek** [comment]
Got it, close issue
