### ISSUE TITLE
TypeScript doesn't use BufferSource for WebCrypto

### ISSUE THREAD

**Issue by microshine** [Microsoft/TypeScript#23055]
**TypeScript Version:**  2.8.1

**Search Terms:** 
WebCrypto, Algorithm

**Problem**
TypeScript types in `lib.dom.d.ts` are different from w3.org WebCrypto API

WebCrypto API uses `BufferSource` for some algorithm parameters like `iv`, `counter`, `additional`, etc. and for crypto methods like `importKey`, `encrypt`, `sign`, etc.
https://www.w3.org/TR/WebCryptoAPI/#terminology
```
Promise<any> encrypt(AlgorithmIdentifier algorithm,
                       CryptoKey key,
                       BufferSource data);

dictionary AesCbcParams : Algorithm {
  // The initialization vector. MUST be 16 bytes.
  required BufferSource iv;
};
```
https://www.w3.org/TR/WebIDL-1/#common-BufferSource
```
typedef (ArrayBufferView or ArrayBuffer) BufferSource;
```
TypeScript v2.8.1 uses another types for it
```
digest(algorithm: string | Algorithm, data: Int8Array | Int16Array | Int32Array | Uint8Array | Uint16Array | Uint32Array | Uint8ClampedArray | Float32Array | Float64Array | DataView | ArrayBuffer): PromiseLike<ArrayBuffer>;
```

Finally `Int8Array | Int16Array | Int32Array | Uint8Array | Uint16Array | Uint32Array | Uint8ClampedArray | Float32Array | Float64Array | DataView | ArrayBuffer` is equal to `BufferSource` but `lib.dom.d.ts` was more readable with `BufferSource`

```
digest(algorithm: string | Algorithm, data: BufferSource): PromiseLike<ArrayBuffer>;
```

**Comment by microshine** [comment]
The similar problem for getRandomValues

WebCrypto API https://www.w3.org/TR/WebCryptoAPI/#crypto-interface
```
ArrayBufferView getRandomValues(ArrayBufferView array);
``` 

TypeScript uses `null` for `array`
```ts
getRandomValues(array: Int8Array | Int16Array | Int32Array | Uint8Array | Uint16Array | Uint32Array | Uint8ClampedArray | Float32Array | Float64Array | DataView | null): Int8Array | Int16Array | Int32Array | Uint8Array | Uint16Array | Uint32Array | Uint8ClampedArray | Float32Array | Float64Array | DataView | null;
```

**Comment by mhegazy** [comment]
We have updated the [input file](https://github.com/Microsoft/TSJS-lib-generator/blob/master/inputfiles/browser.webidl.preprocessed.json), and it does not have some of these type aliases.. I did report the issue to the owners of the json file, and hopefully it will be addressed next time around.
