### ISSUE TITLE
Enforcing Type of T in union type of generics

### ISSUE THREAD

**Issue by Roaders** [Microsoft/TypeScript#23054]
**TypeScript Version:**  2.8.1

**Search Terms:** 
union type, generics

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.

interface Option<T>{
    defaultValue?: T
}

interface StringOption<T = string> extends Option<T>{
    type: "string";
}

interface NumberOption<T = number> extends Option<T>{
    type: "number";
}

type TypedOption<T> = StringOption<T> |
    NumberOption<T>

// Good
const stringOption: StringOption = {
    type: "string",
    defaultValue: "string"
}

const numberOption: NumberOption = {
    type: "number",
    defaultValue: 234
}

//Correctly shows Error

const anotherStringOption: StringOption = {
    type: "number",
    defaultValue: "string"
}

//Bad - should not be possible
const sampleOption: TypedOption<string> = {
    type: "number",
    defaultValue: "hello"
}

```

**Expected behavior:**

The last Sample option should not be possible. The generic type is set to string so only `StringOption` should be a viable type. An error should be thrown in the same way that it is for `anotherStringOption`: "Type 'number' is not assignable to 'string'"

**Actual behavior:**

`sampleOption` is allowed and no compile error is thrown.

**Playground Link:**  
[Playground Link](http://www.typescriptlang.org/play/#src=%0D%0Ainterface%20Option%3CT%3E%7B%0D%0A%20%20%20%20defaultValue%3F%3A%20T%0D%0A%7D%0D%0A%0D%0Ainterface%20StringOption%3CT%20%3D%20string%3E%20extends%20Option%3CT%3E%7B%0D%0A%20%20%20%20type%3A%20%22string%22%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20NumberOption%3CT%20%3D%20number%3E%20extends%20Option%3CT%3E%7B%0D%0A%20%20%20%20type%3A%20%22number%22%3B%0D%0A%7D%0D%0A%0D%0Atype%20TypedOption%3CT%3E%20%3D%20StringOption%3CT%3E%20%7C%0D%0A%20%20%20%20NumberOption%3CT%3E%0D%0A%0D%0A%2F%2F%20Good%0D%0Aconst%20stringOption%3A%20StringOption%20%3D%20%7B%0D%0A%20%20%20%20type%3A%20%22string%22%2C%0D%0A%20%20%20%20defaultValue%3A%20%22string%22%0D%0A%7D%0D%0A%0D%0Aconst%20numberOption%3A%20NumberOption%20%3D%20%7B%0D%0A%20%20%20%20type%3A%20%22number%22%2C%0D%0A%20%20%20%20defaultValue%3A%20234%0D%0A%7D%0D%0A%0D%0A%2F%2FCorrectly%20shows%20Error%0D%0A%0D%0Aconst%20anotherStringOption%3A%20StringOption%20%3D%20%7B%0D%0A%20%20%20%20type%3A%20%22number%22%2C%0D%0A%20%20%20%20defaultValue%3A%20%22string%22%0D%0A%7D%0D%0A%0D%0A%2F%2FBad%20-%20should%20not%20be%20possible%0D%0Aconst%20sampleOption%3A%20TypedOption%3Cstring%3E%20%3D%20%7B%0D%0A%20%20%20%20type%3A%20%22number%22%2C%0D%0A%20%20%20%20defaultValue%3A%20%22hello%22%0D%0A%7D)

**Related Issues:**

**Comment by jcalz** [comment]
I think you might be confused about how [default type parameters](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-3.html#generic-parameter-defaults) work.  The declaration `interface NumberOption<T = number> {...}` does not mean that `T` must be `number`; it means that `T` will be `number` by default *unless explicitly specified*.  Therefore, `NumberOption<string>` is a perfectly acceptable type (albeit with a misleading name) equivalent to
```ts
{
    type: "number";
    defaultValue?: string | undefined;
}
```
and `sampleOption` is indeed compatible with it.   So TypeScript is behaving as it is intended to.

---

If you want to require that `T` is `string` for `StringOption` and `number` for `NumberOption`, you could do something like:

```ts
interface StringOption extends Option<string>{
    type: "string";
}

interface NumberOption extends Option<number>{
    type: "number";
}
```

Where `StringOption` and `NumberOption` are no longer generic.  And, assuming I understand the intent of `TypedOption<T>`, you could use [conditional types](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html#conditional-types) to switch based on `T` like this:
```ts
type TypedOption<T> = 
  T extends string ? StringOption : T extends number ? NumberOption : Option<T>
 ```
which you can verify:
```ts
declare const stringOption: TypedOption<string>; // inspects as StringOption
declare const numberOption: TypedOption<number>; // inspects as NumberOption
declare const objectOption: TypedOption<object>; // inspects as Option<object>
```
Of course you would need to consider what should happen with things like `TypedOption<'hello'>`, `TypedOption<string | number>`, et cetera, to decide if that `TypedOption<T>` definition is actually what you want.  Just letting you know that default type parameters are not the way to go here.  Good luck.

**Comment by Roaders** [comment]
Thanks for the reply. I was coming round to a conditional type solution as well. Closing.
