### ISSUE TITLE
Suggestion: Checked & Unchecked Exceptions

### ISSUE THREAD

**Issue by bennyn** [Microsoft/TypeScript#23060]
## Scenario

Node.js introduced a `UnhandledPromiseRejectionWarning` to make developers aware of handling promise rejections. In the future, promise rejections that are not handled will terminate the Node.js process which will stop applications from continuing to function.

## Solution

When using code, it's hard to say if that particular code throws an exception or not. That's why I suggest to implement a concept similar to checked exceptions in Java. Checked exceptions need to get handled by the programmer with a `try/catch` block or a `throws` clause. It would be great if TypeScript supports such a concept even for Promise-based code so that you can force developers to catch Promise rejections.

## Proposed Change

In the short term, it might be helpful if `tsc` detects whether a method is marked with [@throws](http://usejsdoc.org/tags-throws.html), so that the developer can be informed about error cases to handle when using such methods. This way, the change would not interfere with ES6 or ES7 syntax because it's limited to parsing comments in JavaScript.

### Code Sample

**provider.ts**

```ts
...

/**
 * Decode a serialized public key.
 * @param {CBOR.Decoder} decoder - Payload
 * @returns {PublicKey} Deserialized public key.
 * @throws {ConversionError}
 */
static decode(decoder: CBOR.Decoder): PublicKey {
  const nprops = decoder.object();
  for (let index = 0; index < nprops; index++) {
    switch (decoder.u8()) {
      case 0:
        this.pub_edward = new Uint8Array(decoder.bytes());
        break;
      default:
        decoder.skip();
    }
  }

  const pub_curve = ed2curve.convertPublicKey(this.pub_edward);
  if (pub_curve) {
    this.pub_curve = pub_curve;
    return this;
  }

  throw new ConversionError('Could not convert private key with ed2curve.');
}
```

**consumer.ts**

```ts
...
decode(decoder); // tsc will warn the developer when transpiling, because `decode` declares
                 // to throw a `ConversionError`, which is unhandled in `consumer.ts`
...
```

**Comment by mhegazy** [comment]
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/13219

**Comment by bennyn** [comment]
@mhegazy: You're right. Thanks for the hint. 

I will close my issue because #13219 is still open (keeping fingers crossed 🤞).
