### ISSUE TITLE
Mapped generic types lose index signature

### ISSUE THREAD

**Issue by tyrielv** [Microsoft/TypeScript#23080]
**TypeScript Version:**  2.9.0-dev.20180402

**Search Terms:** partial mapped types index signature enum

**Code**

```ts
enum Fruits {
    Mango = 0,
    Banana = 1
}

interface IFruitMetadata<T> {
    [Fruits.Mango]: T;
    [Fruits.Banana]: T;
}

const onSale1: IFruitMetadata<boolean> = {
    [Fruits.Mango]: true,
    [Fruits.Banana]: false
};

const onSale2: Partial<IFruitMetadata<boolean>> = {
    [Fruits.Banana]: true,
};

const onSale3: Pick<IFruitMetadata<boolean>, Fruits.Banana> = {
    [Fruits.Banana]: true,
};

onSale1[Fruits.Banana] = true;
onSale2[Fruits.Mango] = true;
onSale3[Fruits.Banana] = true;
```

**Expected behavior:**
No compile errors. This was the behavior in 2.7.2.
**Actual behavior:**
With noImplicitAny=true, the Partial and Pick versions of the type triggers error TS7017: Element implicitly has an 'any' type because type 'Partial<IFruitMetadata<boolean>>' has no index signature.
**Playground [Link](http://www.typescriptlang.org/play/#src=enum%20Fruits%20%7B%0D%0A%20%20%20%20Mango%20%3D%200%2C%0D%0A%20%20%20%20Banana%20%3D%201%0D%0A%7D%0D%0A%0D%0Ainterface%20IFruitMetadata%3CT%3E%20%7B%0D%0A%20%20%20%20%5BFruits.Mango%5D%3A%20T%3B%0D%0A%20%20%20%20%5BFruits.Banana%5D%3A%20T%3B%0D%0A%7D%0D%0A%0D%0Aconst%20onSale1%3A%20IFruitMetadata%3Cboolean%3E%20%3D%20%7B%0D%0A%20%20%20%20%5BFruits.Mango%5D%3A%20true%2C%0D%0A%20%20%20%20%5BFruits.Banana%5D%3A%20false%0D%0A%7D%3B%0D%0A%0D%0Aconst%20onSale2%3A%20Partial%3CIFruitMetadata%3Cboolean%3E%3E%20%3D%20%7B%0D%0A%20%20%20%20%5BFruits.Banana%5D%3A%20true%2C%0D%0A%7D%3B%0D%0A%0D%0Aconst%20onSale3%3A%20Pick%3CIFruitMetadata%3Cboolean%3E%2C%20Fruits.Banana%3E%20%3D%20%7B%0D%0A%20%20%20%20%5BFruits.Banana%5D%3A%20true%2C%0D%0A%7D%3B%0D%0A%0D%0AonSale1%5BFruits.Banana%5D%20%3D%20true%3B%0D%0AonSale2%5BFruits.Mango%5D%20%3D%20true%3B%0D%0AonSale3%5BFruits.Banana%5D%20%3D%20true%3B)** 

https://github.com/Microsoft/TypeScript/issues/22892 looks like it might be related.

**Comment by mhegazy** [comment]
@weswigham this should be fixed by https://github.com/Microsoft/TypeScript/pull/23090, correct?

**Comment by weswigham** [comment]
I think so? But @ahejlsberg was unenthused with that fix and was looking for a more holistic approach to the problems and inconsistencies we have in the `keyof` area in general. (Though I may have a revision that's a little closer to acceptable)

**Comment by mhegazy** [comment]
Spoke to @ahejlsberg, he has a different proposal for adding a new `indexof` operator. should address both issues.

**Comment by dardino** [comment]
Another example:

```typescript
enum MyEnum {
    ValA = 0,
    ValB = 1,
}

type IEnumTpProp<R> = {[key in keyof typeof MyEnum]: R };

var X: IEnumTpProp<string> = {
    ValA: "text1",
    ValB: "text2",
    0: "error" // expected: error;  current: error; //OK
};
```

X[MyEnum[MyEnum.ValA]] = "no error"; // current: no error; expected: no error // **OK**
X[MyEnum.ValA] = "no error??"; // current: no error; expected: error // **KO**

**Comment by mhegazy** [comment]
Sample described in OP should be fixed by https://github.com/Microsoft/TypeScript/pull/23592.

@dardino the behavior in your example is expected, since enums have a numeric index signature.
with #23592 you can write something like:

```ts
enum MyEnum {
    ValA = 0,
    ValB = 1,
}

type IEnumTpProp<R> = { [key in MyEnum]: R };

var X: IEnumTpProp<string> = {
    [MyEnum.ValA]: "text1",
    [MyEnum.ValB]: "text2",
    0 :""  //Error, duplicate entry
};
```
