### ISSUE TITLE
Using casting to set property's type is not friendly with React

### ISSUE THREAD

**Issue by ackvf** [Microsoft/TypeScript#23088]
**TypeScript Version:**  2.7.2

**Code**
```
class Example extends React.Component { // implicit <{}, {}>
  state = {
    toggle: false as boolean
  }

  toggle = () => {
    this.setState({toggle: !this.state.toggle}) // property toggle: boolean
    this.setState(state => ({toggle: !state.toggle})) // does not exist on type Readonly<{}>
  }
```

**Expected behavior:**
Expected is that the state in callback is correctly inferred.

**Actual behavior:**

`this.state.toggle` is of type `boolean`
`state` in a `setState` callback is of a different type

**Related Issues:**

https://stackoverflow.com/questions/12787781/type-definition-in-object-literal-in-typescript/12832404#12832404

**Comment by mhegazy** [comment]
I think the underlying issue here is in the react definition file. 

`setState` should be defined as:

```ts
    class Component<P, S> {

        setState<K extends keyof this["state"]>(
            state: ((prevState: Readonly<this["state"]>, props: P) => (Pick<this["state"], K> | this["state"] | null)) | (Pick<this["state"], K> | this["state"] | null),
            callback?: () => void
        ): void;

        state: Readonly<S>;
```

feel free to send a PR to Definitely typed for this and i will merge it.

**Comment by ackvf** [comment]
This indeed solved the issue https://github.com/DefinitelyTyped/DefinitelyTyped/pull/25055
