### ISSUE TITLE
TSX attribute autocompletes incorrectly

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#23099]
_From @roblourens on April 3, 2018 0:3_

```ts
class MyComponent extends React.Component<{ abc: number }> {
}

<MyComponent
    key="hi"
    
/>
```

- Cursor on the line after `key`
- ctrl+space
- Pick `abc`
- It inserts `abc` 👍 
- Delete that. Type `abc`
- Pick `abc` from the suggestion list
- It inserts `{abc}` 🐛 

Seems to only happen after another attribute which is why `key` is there

_Copied from original issue: Microsoft/vscode#47112_

**Comment by mjbvz** [comment]
In this case, the returned completion has the `insertText` `{abc}`:

```
 {
        "name": "abc",
        "kind": "JSX attribute",
        "kindModifiers": "",
        "sortText": "0",
        "insertText": "{abc}",
        "replacementSpan": {
            "start": {
                "line": 8,
                "offset": 5
            },
            "end": {
                "line": 8,
                "offset": 6
            }
        }
    },
```

**Comment by mhegazy** [comment]
@andy-ms can you please take a look for 2.8.2
