### ISSUE TITLE
Compile bug: for loop no braces & object destructuring with ...rest

### ISSUE THREAD

**Issue by jahooma** [Microsoft/TypeScript#23098]
This is a simple compile bug with several uncommon features:

```ts
let array = [{a: 0, b: 1}]
for (let { a, ...rest } of array)
    console.log(a)
```

**Expected behavior:**
Should output the complied for loop that calls console.log.
**Actual behavior:**
The console.log statement is omitted.

Basically, if there are no braces for the for loop, and the for loop uses object destructuring with a ...rest param, then the one line under the for loop is erroneously omitted. See demonstration at playground link below.

**Playground Link:** http://www.typescriptlang.org/play/#src=let%20array%20%3D%20%5B%7Ba%3A%200%2C%20b%3A%201%7D%5D%0D%0Afor%20(let%20%7B%20a%2C%20...rest%20%7D%20of%20array)%0D%0A%20%20%20%20console.log(a)

**Comment by mhegazy** [comment]
@weswigham can you take a look at this one for 2.8.2
