### ISSUE TITLE
selectionStart should not be nullable: TSJS-lib-generator regression in 2.8.x 

### ISSUE THREAD

**Issue by styfle** [Microsoft/TypeScript#23094]
**TypeScript Version:**  2.8.1

**Search Terms:** 
selectionStart, selectionEnd

**Code**

```ts
// Source code from https://github.com/styfle/copee
function fromElement(el: HTMLInputElement | HTMLTextAreaElement, preserveSelection?: boolean) {
    let start = 0;
    let end = 0;
    let success = false;

    if (preserveSelection) {
        start = el.selectionStart;
        end = el.selectionEnd;
    }

    el.select();

    try {
        success = document.execCommand('copy');
    } catch (err) {
        success = false;
    }

    if (preserveSelection) {
        el.setSelectionRange(start, end);
    }

    return success;
}
```

**Expected behavior:**
el.selectionStart and el.selectionEnd should return `number`

**Actual behavior:**
el.selectionStart and el.selectionEnd actually return `number | null`

**Playground Link:**
[Playground](https://www.typescriptlang.org/play/#src=%2F%2F%20Source%20code%20from%20https%3A%2F%2Fgithub.com%2Fstyfle%2Fcopee%0D%0Afunction%20fromElement(el%3A%20HTMLInputElement%20%7C%20HTMLTextAreaElement%2C%20preserveSelection%3F%3A%20boolean)%20%7B%0D%0A%20%20%20%20let%20start%20%3D%200%3B%0D%0A%20%20%20%20let%20end%20%3D%200%3B%0D%0A%20%20%20%20let%20success%20%3D%20false%3B%0D%0A%0D%0A%20%20%20%20if%20(preserveSelection)%20%7B%0D%0A%20%20%20%20%20%20%20%20start%20%3D%20el.selectionStart%3B%0D%0A%20%20%20%20%20%20%20%20end%20%3D%20el.selectionEnd%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20el.select()%3B%0D%0A%0D%0A%20%20%20%20try%20%7B%0D%0A%20%20%20%20%20%20%20%20success%20%3D%20document.execCommand('copy')%3B%0D%0A%20%20%20%20%7D%20catch%20(err)%20%7B%0D%0A%20%20%20%20%20%20%20%20success%20%3D%20false%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20if%20(preserveSelection)%20%7B%0D%0A%20%20%20%20%20%20%20%20el.setSelectionRange(start%2C%20end)%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20return%20success%3B%0D%0A%7D)

**Related Issues:**
#22381 , https://github.com/styfle/copee/pull/21

**Comment by mhegazy** [comment]
looking at the [spec](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#dom-textarea/input-selectionstart), seems like `null` is a possible value for selectionStart and selectionEnd.

**Comment by styfle** [comment]
@mhegazy Interesting. It looks like `type=text` is never null but `type=email` is null for example.

1. Is there a way to tell typescript that the `HTMLInputElement` is type=text?
2. Also, why did this change in TS 2.8? Was it just wrong the whole time?

**Comment by mhegazy** [comment]
> Is there a way to tell typescript that the HTMLInputElement is type=text?

Do not think there is a simple way to do this really.

> Also, why did this change in TS 2.8? 

We auto-generate the library from the webidl file from edge. see https://github.com/Microsoft/TSJS-lib-generator. We have taken an update to the file in 2.8. 

> Was it just wrong the whole time?

the input file can have bugs, and it can be wrong.. so yes.

**Comment by mhegazy** [comment]
if you are sure it is not `null`, you can use the null assertion operator `!`

**Comment by styfle** [comment]
Oh yeah, the null assertion operator is new.

But now that I think about it, the user may pass in an input element that I don't the type.

So I'll just [fallback to 0](https://github.com/styfle/copee/commit/407b017b7f87ff32a0cef74590b2cc1c598af030), just in case.

Thanks 👍
