### ISSUE TITLE
Proposal: Safe type assertion in expression

### ISSUE THREAD

**Issue by kgtkr** [Microsoft/TypeScript#23104]
# Background
Currently, it is impossible to add type ascription only to variable declaration.
Also, casting is not safe.
I want a way to safely add type ascription in the middle of the expression.

# Proposal
```ts
expression :: Type
```

# Example
```ts
//equal: const x:[number,string]=[1,"str"];
const x=[1,"str"]::[number,string];
```

```ts
declare const x: {};
const a: { p: number } = x;//err
const a = x as { p: number };//ok
const a = x :: { p: number };//err

```

**Comment by MartinJohns** [comment]
Could you expand a bit more on why you would want this? It just seems to be more syntax that needs to be maintained for a functionality that already exists and works.

**Comment by kgtkr** [comment]
example:

```ts
const obj={
  x:"abc"::"abc"|"xyz", 
  //more props
};
```

```ts
//verbose
const obj:{x:"abc"|"xyz",...}={
  x:"abc", 
  //more props
};
```

```ts
//unsafe
const obj={
  x:"abc" as "abc"|"xyz", 
  //more props
};
```

**Comment by krryan** [comment]
Not wild about the `::` syntax, but strongly support the idea.

**Comment by kgtkr** [comment]
I noticed that `::` and `esnext:bind-operator` became ambiguous
I have to find another syntax

https://github.com/tc39/proposal-bind-operator

**Comment by chinoto** [comment]
7481 was closed due to length. Continued at #47920. I figure this might help anyone who lands here get up to speed quicker.
