### ISSUE TITLE
document.readyState is not typed with literal type

### ISSUE THREAD

**Issue by NN---** [Microsoft/TypeScript#23107]
According to documentation: https://developer.mozilla.org/en-US/docs/Web/API/Document/readyState
The interface can be defined:

```ts
interface Document {
  readonly readyState: string;
}
```
==>
```ts
interface Document {
  readonly readyState: "loading" | "interactive" | "complete";
}
```

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by mhegazy** [comment]
thanks @a-tarasyuk!

**Comment by swevans** [comment]
Hm did this just introduce a bug?
This line of code now generates an error:
`
if (document.readyState === "complete" || document.readyState === "loaded" || document.readyState === "interactive") { /*some code*/}
`
error:
`
error TS2365: Operator '===' cannot be applied to types '"interactive" | "loading"' and '"loaded"'
`

Here is the definition for readyState in lib.es2016.full.d.ts:
`
    /**
     * Retrieves a value that indicates the current state of the object.
     */
    readonly readyState: string;
`

My Typescript version: 2.8.3
