### ISSUE TITLE
something wrong by `T extends U ? X : Y` ?

### ISSUE THREAD

**Issue by bluelovers** [Microsoft/TypeScript#23101]
**TypeScript Version:**  Version 2.9.0-dev.20180402

**nodejs Version:**  v9.10.1

ide: idea 2017.3.5

**Search Terms:** 

**Code**

i follow [release-notes/typescript-2-8.html](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html)

```ts
type TypeName<T> =
	T extends string ? "string" :
	T extends number ? "number" :
	T extends boolean ? "boolean" :
	T extends undefined ? "undefined" :
	T extends Function ? "function" :
	"object";

type AnyFunction = (...args: any[]) => any;
type ReturnType<T extends AnyFunction> = T extends (...args: any[]) => infer R ? R : never;
```

**Expected behavior:**

**Actual behavior:**

but this show message

![2018-04-03-12-33-51-1](https://user-images.githubusercontent.com/167966/38229530-c8707ad6-373b-11e8-8708-8696ac58ec7e.jpg)

**Playground Link:**  

**Related Issues:**

**Comment by MartinJohns** [comment]
Are you using tslint? I think I've seen this message with a tslint version that could not handle conditional types.

**Comment by Kovensky** [comment]
It's also possible that your IDE is not loading your project's typescript but using its own builtin typescript which would be older.
