### ISSUE TITLE
Inference issue in literal objects

### ISSUE THREAD

**Issue by pauliusrum** [Microsoft/TypeScript#23109]
I have noticed a problem with type inference of literal objects. Given example where alignment property should be of type "left" but it is string instead and it is not accepted by the given `printText` function when it is passed as a variable `params` but work when it is specified directly at the function invocation. Does this work as intended or is it a bug?

Tested with Typescript 2.8.

```typescript
type Alignment = "left" | "right" | "center"

const params = {
    alignment: "left"
}

function printText(text: string, options: { alignment: Alignment }) {
    console.log(text)
}

printText("Test", params) // Compile error
printText("Test", { ...params }) // Compile error
printText("Test", {alignment: "left"}) // Correct
```

**Comment by MartinJohns** [comment]
Working as intended: #20271
