### ISSUE TITLE
Playground share link contains angle brackets

### ISSUE THREAD

**Issue by MartinJohns** [microsoft/TypeScript#23106]
**Search Terms:** playground share brackets

**Code**

```ts
type GenericType<T> = T;
```

**Expected behavior:**
`<` character is URL encoded in the share link.

**Actual behavior:**
`<` character is not URL encoded in the share link.

**Playground Link:** https://www.typescriptlang.org/play/#src=type%20GenericType<T>%20%3D%20T%3B%0D%0A

The link above demonstrates the behavior. Github is not able to properly display the link due to the angle brackets. URL encoding the `<` character with `%3C` would resolve this issue.

**Comment by krryan** [comment]
The link actually eats the `<T>` entirely, it's not in your text (even as text), though it does cut off the hyperlinking.

For others, the link is `https://www.typescriptlang.org/play/#src=type%20GenericType%3CT%3E%20%3D%20T%3B%0D%0A`

**Comment by MartinJohns** [comment]
> it's not in your text (even as text)

Wow, I did not even notice that. It's GitHubs behavior on markdown. When I "edit" my post I can still see the `<T>` in the link.

**Comment by orta** [comment]
This is fixed with the new playground 👍
