### ISSUE TITLE
End comment marker removed when at end of file

### ISSUE THREAD

**Issue by dsparkplug** [Microsoft/TypeScript#2311]
TypeScript 1.4 compiler removes end comment marker at end of file. This causes "Uncaught SyntaxError: Unexpected token ILLEGAL" in Chrome.

__Example ts code:__

```
var str = "Hello, world!";
document.body.innerHTML = str;

/*
 
 hello, world

*/
```
__Note__ there is no new line at end of file after */

__Compiler output js:__
```
var str = "Hello, world!";
document.body.innerHTML = str;
/*
 
 hello, world

var str = "Hello, world!";
document.body.innerHTML = str;

/*
 
 hello, world
 
//# sourceMappingURL=helloworld.js.map
```

__Correct output after adding newline:__

```
var str = "Hello, world!";
document.body.innerHTML = str;
/*
 
 hello, world

*/
//# sourceMappingURL=helloworld.js.map
```

**Comment by mhegazy** [comment]
Looks like a dupe of #1714. The fix should be in master now.

**Comment by dsparkplug** [comment]
OK - thanks. Sorry I missed the dupe - it's way back in my search results.
