### ISSUE TITLE
Escaped double quotes in template string are not escaped again in generated code

### ISSUE THREAD

**Issue by KeyboardNerd** [Microsoft/TypeScript#23125]
**TypeScript Version:**  2.9.0-dev.20180403
Found on 2.8.1

**Search Terms:** 
template string, escape, json, json parse

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
let a = `{"key": "\"value\""}`
try {
    alert(JSON.parse(a));
} catch (error) {
    alert(error);
}
```

**Expected behavior:** 
By running the file, JSON should parse successfully and alert "[Object object]". 
Expected generated file.
```
var a = "{\"key\": \"\\\"value\\\"\"}";
try {
    alert(JSON.parse(a));
}
catch (error) {
    alert(error);
}
```
**Actual behavior:**
By running the file, JSON.parse failed and alert "SyntaxError: Unexpected token v in JSON at position 10"
Acutal generated file:
```
var a = "{\"key\": \"\"value\"\"}";
try {
    alert(JSON.parse(a));
}
catch (error) {
    alert(error);
}
```
**Playground Link:**  https://www.typescriptlang.org/play/index.html#src=let%20a%20%3D%20%60%7B%22key%22%3A%20%22%5C%22value%5C%22%22%7D%60%0D%0Atry%20%7B%0D%0A%20%20%20%20alert(JSON.parse(a))%3B%0D%0A%7D%20catch%20(error)%20%7B%0D%0A%20%20%20%20alert(error)%3B%0D%0A%7D%0D%0A

**Related Issues:**

**Comment by ajafff** [comment]
@KeyboardNerd You need to escape your backslashes if you want them to be preserved.

```js
`{"key": "\"value\""}` === `{"key": ""value""}` === "{\"key\": \"\"value\"\"}";

`{"key": "\\"value\\""}`=== "{\"key\": \"\\\"value\\\"\"}"
```

The original code wouldn't work as you expect. And so does the transpiled code.

**Comment by mhegazy** [comment]
![image](https://user-images.githubusercontent.com/8000722/38276010-93b8aa90-3748-11e8-8d00-1d4a99009103.png)
