### ISSUE TITLE
Concurrency as first-class citizen

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#2312]
I'm just interested if you got any plans of implementing concurrency to TypeScript?

**Comment by DanielRosenwasser** [comment]
> any plans of implementing concurrency

That can mean a lot of things - you mean like #1664?

**Comment by tinganho** [comment]
@DanielRosenwasser I was more meaning multi-threading, to be able to spawn processes directly without requiring any library.

**Comment by tinganho** [comment]
@DanielRosenwasser and also have an effective way of message passing. Ala go style.

```go
package main

import "fmt"

func main() {

    // Create a new channel with `make(chan val-type)`.
    // Channels are typed by the values they convey.
    messages := make(chan string)

    // _Send_ a value into a channel using the `channel <-`
    // syntax. Here we send `"ping"`  to the `messages`
    // channel we made above, from a new goroutine.
    go func() { messages <- "ping" }()

    // The `<-channel` syntax _receives_ a value from the
    // channel. Here we'll receive the `"ping"` message
    // we sent above and print it out.
    msg := <-messages
    fmt.Println(msg)
}

```

**Comment by tinganho** [comment]
This is how spider lang have implemented their channels http://spiderlang.org/#channels

**Comment by DanielRosenwasser** [comment]
See [my answer](https://github.com/Microsoft/TypeScript/issues/1686#issuecomment-70157788) on #1686.

In general, I don't think anything has changed since then. We don't really try to supply a facility to extend runtime capabilities, so things like that generally fall out of scope.
