### ISSUE TITLE
Unable to specify 'if T is optional' in a conditional Type

### ISSUE THREAD

**Issue by Roaders** [Microsoft/TypeScript#23126]
**TypeScript Version:**  2.8.1

**Search Terms:** 
condition types, unions, optional, undefined

**Code**

```ts
interface StringOption{
    type: "string";
}

interface NumberOption{
    type: "number";
}

interface ISampleObject {
    requiredParam: string,
    optionalParam?: number
}

type MappedOptions<T> = {
    readonly [P in keyof T]: T[P] extends undefined ? StringOption : NumberOption;
}

const mappedObject: MappedOptions<ISampleObject> = {
    requiredParam: {type: "number"},
    optionalParam: {type: "string"}
}
```

**Expected behavior:**

as `optionalParam` is optional you should be able to switch on that in conditional type so that when mapped `optionalParam` is of type `StringOption` and `requiredParam` is of type `NumberOption`.

**Actual behavior:**
both types are of type `NumberOption` as neither extend undefined. A syntax is needed to say that a type includes a type in a union I suppose and as far as I know this is not yet available.

**Playground Link:**
[Playground link](http://www.typescriptlang.org/play/#src=%0D%0Ainterface%20StringOption%7B%0D%0A%20%20%20%20type%3A%20%22string%22%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20NumberOption%7B%0D%0A%20%20%20%20type%3A%20%22number%22%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20ISampleObject%20%7B%0D%0A%20%20%20%20requiredParam%3A%20string%2C%0D%0A%20%20%20%20optionalParam%3F%3A%20number%0D%0A%7D%0D%0A%0D%0Atype%20MappedOptions%3CT%3E%20%3D%20%7B%0D%0A%20%20%20%20readonly%20%5BP%20in%20keyof%20T%5D%3A%20T%5BP%5D%20extends%20undefined%20%3F%20StringOption%20%3A%20NumberOption%3B%0D%0A%7D%0D%0A%0D%0Aconst%20mappedObject%3A%20MappedOptions%3CISampleObject%3E%20%3D%20%7B%0D%0A%20%20%20%20requiredParam%3A%20%7Btype%3A%20%22number%22%7D%2C%0D%0A%20%20%20%20optionalParam%3A%20%7Btype%3A%20%22string%22%7D%0D%0A%7D)

**Comment by mhegazy** [comment]
I guess you want `undefined extends T[P] ? NumberOption : StringOption`.

you can also remove the optionality later on using `-?`:

```ts
type MappedOptions<T> = {
    readonly [P in keyof T]-?: undefined extends T[P] ? NumberOption : StringOption
}
```

**Comment by Roaders** [comment]
I was just about to reply and say that still doesn't work but string null checks wasn't turned on.

Now does exactly what I want. Thanks

[Playground Link](http://www.typescriptlang.org/play/#src=%0D%0Ainterface%20StringOption%7B%0D%0A%20%20%20%20type%3A%20%22string%22%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20NumberOption%7B%0D%0A%20%20%20%20type%3A%20%22number%22%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20ISampleObject%20%7B%0D%0A%20%20%20%20requiredParam%3A%20string%2C%0D%0A%20%20%20%20optionalParam%3F%3A%20number%0D%0A%7D%0D%0A%0D%0Atype%20MappedOptions%3CT%3E%20%3D%20%7B%0D%0A%20%20%20%20readonly%20%5BP%20in%20keyof%20T%5D-%3F%3A%20undefined%20extends%20T%5BP%5D%20%3F%20StringOption%20%3A%20NumberOption%3B%0D%0A%7D%0D%0A%0D%0Aconst%20mappedObject%3A%20MappedOptions%3CISampleObject%3E%20%3D%20%7B%0D%0A%20%20%20%20requiredParam%3A%20%7Btype%3A%20%22number%22%7D%2C%0D%0A%20%20%20%20optionalParam%3A%20%7Btype%3A%20%22string%22%7D%0D%0A%7D)

**Comment by fcrick** [comment]
```
export type OptionalPropertyNames<T> = {
    [K in keyof T]-?: undefined extends T[K] ? K : never
}[keyof T];
export type RequiredPropertyNames<T> = {
    [K in keyof T]-?: undefined extends T[K] ? never : K
}[keyof T];
export type OptionalProperties<T> = Pick<T, OptionalPropertyNames<T>>
export type RequiredProperties<T> = Pick<T, RequiredPropertyNames<T>>
```
I arrived looking for these, and was able to piece it together based on the great information above.

**Comment by aleclarson** [comment]
Should `undefined extends` work outside mapped types? [See here](https://goo.gl/Ssg2ZG)

**Comment by samuelcastro** [comment]
I'm looking for a way to create optional prop conditionally, let's say, if prop `A` is defined make prop `B` optional, or if prop `B` is defined then prop `A` is optional, I'm wondering if this is the case of this solution and if so, how to use it?

**Comment by JamesJansson** [comment]
Thank you @aleclarson, testing whether a parameter is optional works well using 
`undefined extends T`
which can be used in a generic tuple quite nicely.

**Comment by jpitchardu** [comment]
Hi, I'm trying to find any docs on `-?` but I haven't been able to, does anybody know where to find them? Thanks
