### ISSUE TITLE
Omitting function return type and --noImplicitAny

### ISSUE THREAD

**Issue by rolyp** [Microsoft/TypeScript#2313]
Would it break lots of programs to have the following be an error when compiling with `--noImplicitAny`?

    function f () {
       return "hello"
    }

**Comment by NoelAbrahams** [comment]
Well, yes. How is this implicit `any`?

**Comment by DickvdBrink** [comment]
Maybe this is something for a linter. 
I think https://github.com/palantir/tslint typedef rule can do what you want. 
Doesn't really give an answer to this question but it might be a alternative :)

**Comment by rolyp** [comment]
@NoelAbrahams Maybe my intuition is wrong, but doesn't this only compile because it desugars to:

    function f (): any {
       return "hello"
    }

**Comment by NoelAbrahams** [comment]
The return type of a function is implied by the values it returns. So in this case it's `string`. It's not clear what errors would be caught by forcing annotation of the return value.

**Comment by rolyp** [comment]
@NoelAbrahams Ok, I see. Thanks. You can close this then.
