### ISSUE TITLE
Union type two interfaces (non-primitive unions)

### ISSUE THREAD

**Issue by TrySpace** [Microsoft/TypeScript#23142]
I doubt this is expected behaviour, but it might be that I'm missing something.

**Code**
Doing this:
```ts
interface One {
  one: string;
}

interface Two {
  two: string;
}

type Three = One | Two;

const what1: Three = { one: 'ok' };
const what2: Three = { two: 'ok' };

const good1 = what1.one;
const good2 = what2.two;

```
`good1` & `good2` are good.

But adding a property to One:
```ts
interface One {
  one: string;
  extra: number; // <-- New line
}

interface Two {
  two: string;
}

type Three = One | Two;

const what1: Three = { one: 'ok' }; // Error
const what2: Three = { two: 'ok' };

const good1 = what1.one; // Error
const good2 = what2.two;

```
Typescript will warn about both `what1` and `what1.one`, respectively:
```error
 TS2322: Type '{ one: string; }' is not assignable to type 'Three'.
  Type '{ one: string; }' is not assignable to type 'Two'.
    Property 'two' is missing in type '{ one: string; }'.
```
So instead of error for missing `extra` prop, it will error for it missing a type from a seemingly arbitrary type.

and
```
TS2339: Property 'one' does not exist on type 'Three'.
  Property 'one' does not exist on type 'Two'.
```
Here it looks like ts has coerced/figured out the type already.

**Playground Link:** 
[Just uncomment the line here](http://www.typescriptlang.org/play/#src=%0D%0Ainterface%20One%20%7B%0D%0A%20%20one%3A%20string%3B%0D%0A%20%20%2F%2F%20extra%3A%20number%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20Two%20%7B%0D%0A%20%20two%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Atype%20Three%20%3D%20One%20%7C%20Two%3B%0D%0A%0D%0Aconst%20what1%3A%20Three%20%3D%20%7B%20one%3A%20'ok'%20%7D%3B%0D%0Aconst%20what2%3A%20Three%20%3D%20%7B%20two%3A%20'ok'%20%7D%3B%0D%0A%0D%0Aconst%20good1%20%3D%20what1.one%3B%0D%0Aconst%20good2%20%3D%20what2.two%3B)

Trying to align them doesn't help:
[When I add the `extra` property to the second type](http://www.typescriptlang.org/play/#src=interface%20One%20%7B%0D%0A%20%20one%3A%20string%3B%0D%0A%20%20extra%3A%20number%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20Two%20%7B%0D%0A%20%20two%3A%20string%3B%0D%0A%20%20extra%3A%20number%3B%0D%0A%7D%0D%0A%0D%0Atype%20Three%20%3D%20One%20%7C%20Two%20%7C%20string%3B%0D%0A%0D%0Aconst%20what1%3A%20Three%20%3D%20%7B%20one%3A%20'ok'%20%7D%3B%0D%0Aconst%20what2%3A%20Three%20%3D%20%7B%20two%3A%20'ok'%20%7D%3B%0D%0A%0D%0Aconst%20good1%20%3D%20what1.one%3B%0D%0Aconst%20good2%20%3D%20what2.two%3B)

What fixes these issues is when I change it into an optional `extra?: string`: [here](http://www.typescriptlang.org/play/#src=interface%20One%20%7B%0D%0A%20%20one%3A%20string%3B%0D%0A%20%20extra%3F%3A%20number%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20Two%20%7B%0D%0A%20%20two%3A%20string%3B%0D%0A%20%20extra%3F%3A%20number%3B%0D%0A%7D%0D%0A%0D%0Atype%20Three%20%3D%20One%20%7C%20Two%0D%0A%0D%0Aconst%20what1%3A%20Three%20%3D%20%7B%20one%3A%20'ok'%20%7D%3B%0D%0Aconst%20what2%3A%20Three%20%3D%20%7B%20two%3A%20'ok'%20%7D%3B%0D%0A%0D%0Aconst%20good1%20%3D%20what1.one%3B%0D%0Aconst%20good2%20%3D%20what2.two%3B)

**Expected behavior:**
I would have expected it to behave like logical or, but adding new properties seems to break the union.
Invalid, but maybe something like this: `type Three = One? | Two?;` is what I actually expected?
I expected no error.

**Actual behavior:**
The union seems to behave as `&`.

If I do `foo: string | number`, I expect `foo` to accept either type. 
My guess is that with non-primitive types it doesn't work like that, since I couldn't literally merge an `object` with a `boolean`, so it merges the two interfaces, but somehow both are being reverse hypocritical, as in either are complaining about something the other is missing, while they have it themselves. And the order doesn't matter either, so they will always be incompatible whatever you try.
But that doesn't explain why it would work without the extra property, but different properties.

**Related Issues:**
https://github.com/Microsoft/TypeScript/issues/23031 The title seems to match my issue, but the errors are different. Although I have to say I've had that error before in relation to using two interfaces in union.

**Search Terms:** 
`type interfaces union`

**Comment by jack-williams** [comment]
This seems fine to me (unless I'm missing something). Do you expect there _not_ to be an error, or a different error?

+ `{ one: 'ok' }` is not assignable to type `One` (modified) because it doesn't have the property `extra`. 
+ `{ one: 'ok' }` is not assignable to type `Two` because it doesn't have the property `two`.

Therefore `{ one: 'ok' }` is not assignable to type `One | Two`, a.k.a. `Three`.

If the union behaved as intersection then you'r first example would error too.

**Comment by evmar** [comment]
When you write

```
const what1: Three = { one: 'ok' }; // Error
```

The compiler sees that it doesn't match either One or Two, and from there it can't know which one you were aiming for.  You'll frequently see this come up in more complex scenarios where there's a whole chain of aliases and interfaces and the compiler goes down the wrong arm of some intersection.

**Comment by TrySpace** [comment]
@evmar But why does the 2nd error occur? The property `.one` exists on type `One`, yet it errors.

**Comment by RyanCavanaugh** [comment]
Please use StackOverflow for questions. It is not the case that we've been shipping a buggy implementation of union types for several years.
