### ISSUE TITLE
Inferred Return Type includes property `bar?: undefined`

### ISSUE THREAD

**Issue by LucasSloan** [Microsoft/TypeScript#23144]
**TypeScript Version:**  2.7.2, 2.8

**Search Terms:** 
milestone 2.7.*, union
**Code**

```ts
function returnsTwoDifferentObjects(b: boolean) {
  if (b) {
    return {foo: ''};
  } else {
    return {foo: '', bar: ''};
  }
}
```

**Expected behavior:**
The return type of returnsTwoDifferentObjects is either `{foo: string}|{foo: string, bar: string}` or `{foo: string, bar?: string}`.

**Actual behavior:**
The return type of returnsTwoDifferentObjects is `{foo: string, bar?: undefined}|{foo: string, bar: string}`.  In TS 2.6.2, the return type was `{foo: string}|{foo: string, bar: string}`.  It seems very weird to have an object with an optional property whose only possible value is undefined, it's clear what's meant is that that property doesn't actually exist, in which case we already have the ability to omit the property.

**Playground Link:** [Playground](http://www.typescriptlang.org/play/#src=function%20returnsTwoDifferentObjects(b%3A%20boolean)%20%7B%0D%0A%20%20if%20(b)%20%7B%0D%0A%20%20%20%20return%20%7Bfoo%3A%20''%7D%3B%0D%0A%20%20%7D%20else%20%7B%0D%0A%20%20%20%20return%20%7Bfoo%3A%20''%2C%20bar%3A%20''%7D%3B%0D%0A%20%20%7D%0D%0A%7D%0D%0A)

**Comment by mhegazy** [comment]
The compiler normalizes objects created from string literals. This was added in TS 2.7, see https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#improved-type-inference-for-object-literals for more details.
