### ISSUE TITLE
Browser specific lib options

### ISSUE THREAD

**Issue by grimly** [Microsoft/TypeScript#23156]
**TypeScript Version:**  2.8.1

**Search Terms:** lib ie11 browser

**Related Issues:** #14308

Hello,

I am working and making sure my application works on IE11 as it is used within my company and by most of our clients but how often did I run into this sad issue of using some part of the JS lib and finding out it doesn't exist in IE11. I often can use polyfills (Promise) or alternatives (Map instead of Set).

I was wondering if browser specific librairies has been considered an option, at least for the Microsoft browsers.

This project being maintained by Microsoft, I would have expected to be able to use any IE and Edge version as a `lib` option. This would make clear what to use and not to use from ES5 and ES6 and some DOM definitions.

As an example, IE11 doesn't have `Promise` or many of the new `Array` methods, but has `WeakMap` and `MutationObserver`. We can't really say IE11 is ES5 or ES6 ready but some of it is available.

I think this "request" may also be filled by an external project since this was done for NodeJS in `@types/node`.

**Comment by mhegazy** [comment]
This issue has been referenced before in https://github.com/Microsoft/TypeScript/issues/6640 and https://github.com/Microsoft/TypeScript/issues/4692. 

Keep in mind that the library file is not special. it is a .d.ts file just like any, we have included it with the compiler for convenience. you can build your own that has less or more declarations, and the compiler will check against them.

The lib file is auto-generated and is not managed manually. we auto-generate it from Edge-spec. this is easy for us to maintain and keep up to-date. we have been working on generating it from the standard webidl files. see https://github.com/Microsoft/TypeScript/issues/3027.

We do not plan on maintain that list of all versions of browsers and their matching declarations, it is just too much work that we can not commit to.

There is no reason why you cannot fork the lib file and generate one for IE11, or IE10 or any specific version of a browser you are targeting. this is a simpler problem than having to maintain a library for a all versions of all browsers.

I think this is a duplicate of https://github.com/Microsoft/TypeScript/issues/19183 and https://github.com/Microsoft/TypeScript/issues/3027

**Comment by grimly** [comment]
Thank you for the response.

I will close since the answer is no but as I gave the nodejs example, it is doable by a third party.
