### ISSUE TITLE
TypeScript VsCode Refactoring Line Break is not Respected

### ISSUE THREAD

**Issue by MrDesjardins** [Microsoft/TypeScript#23151]
**TypeScript Version:**  2.8.1 (VsCode and the tsconfig.json)

**Search Terms:** refactoring, import, typescript

**Code**

```ts
import * as React from "react";
import { connect } from "react-redux";
```
From there, in VsCode, you will get "..." to suggest to refactor the React import. If you agree, the "react-redux" will get into the same line of react like this:
```ts
import React from "react";import { connect } from "react-redux";
```
![2018-04-04_10-53-28](https://user-images.githubusercontent.com/1014796/38336409-8edc33ec-3816-11e8-87e7-a1616b2473ad.gif)

**Expected behavior:** To keep the line break

**Actual behavior:** Change the line with the refactor of the import and bring the next line to the refactored one

**Playground Link:** https://twitter.com/mrdesjardins/status/981591251110707200

**Related Issues:**

**Comment by andy-ms** [comment]
Probably fixed by #22519. I could reproduce this in `typescript@2.8` but not in `typescript@next`.
