### ISSUE TITLE
make operators available for extensions of Number

### ISSUE THREAD

**Issue by JeWaVe** [Microsoft/TypeScript#2315]
Hello, 

I recently tried to extends Number to various interfaces (such as int, char, float, double, ...)
it works well until I try to apply operators on them: 

interface int extends Number {}
var a: int = 1;
var b: int = 2;
var c: int = a+b; // -> error

I don't completely understand why this is not supported.

The purpose would be to use those type information in an clang-like compiler from typescript to native code.

Is that a bug or not supported on purpose?

Thanks, 

Régis

**Comment by DickvdBrink** [comment]
You may want to use `type` in this case like below which I think should work correctly

    type int = number;
    var a: int = 1;
    var b: int = 2;
    var c: int = a+b;

**Comment by JeWaVe** [comment]
Thanks, 

is this instruction a typedef?

Will "a" have the "int" type attached or only number?

**Comment by DickvdBrink** [comment]
I believe it is called a `Type Aliases`. Effectively it just a copy with a different name and it is still a number;

So if you create a function which accepts a type alias called "int" it still accepts a number as it is actually the same thing.

**Comment by JeWaVe** [comment]
That's not exactly what I'd need. 
I'd rather see int as a specialization of number, and therefore it would be a different type.
but it's probably enough for what I'd like to do.
thanks!
