### ISSUE TITLE
Wrong circular reference error with conditional types in incremental type checking

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#23161]
@ahejlsberg I can still see the bug of #23100 you fixed, on IDE (VSCode).

**TypeScript Version:**  2.7.0-dev.20180405

repro:

1. clone https://github.com/falsandtru/spica/tree/repro/ts23161
1. run `npm i`
1. open `src/lib/type.ts`; you can see no error.
1. open `src/lib/type.test.ts` and remove `assert((): true => true as TEq<DeepExtractProp<AD, boolean>, AC>);`; this strangely makes an error.
1. open `src/lib/type.ts` again; you can see a new wrong circular reference error.

**Related Issues:** #23052

**Comment by mhegazy** [comment]
can you try `typescript@next` instead?

**Comment by falsandtru** [comment]
Done now, but not resolved. Can you repro?

**Comment by mhegazy** [comment]
nope.

**Comment by falsandtru** [comment]
what info do you want?

**Comment by mhegazy** [comment]
steps to reproduce the issue..

![image](https://user-images.githubusercontent.com/8000722/38379388-6866692c-38b5-11e8-9d90-1c34d6d5e8a7.png)

**Comment by falsandtru** [comment]
I mean what **more** info. Here is my error.

![repro](https://user-images.githubusercontent.com/3143368/38380146-d963d1fe-393d-11e8-8783-c32457139d98.png)

Your screenshot indicates you edited `type.ts`. Did you really check with original source code?
