### ISSUE TITLE
How to prevent top jsdoc comments from disappearing while compiling with --declaration flag

### ISSUE THREAD

**Issue by evil-shrike** [Microsoft/TypeScript#23164]
I'm compiling my lib for distributing , one of steps is adding banner at the top of each file. Something like this:
```js
/**
 * @overview MegaLib v1.36.0 - 2018-04-04 22:47 
 * @author SuperCompany
 * @version 1.2.3
 * @copyright 2018 SuperCompany
 * @license Private
 */
```

While adding banners I don't know what follows next and usually it's some import. So a file will look like this:
```ts
/**
 * @overview MegaLib v1.36.0 - 2018-04-04 22:47 
 * @author SuperCompany
 * @version 1.2.3
 * @copyright 2018 SuperCompany
 * @license Private
 */
import {MyClass1} from "script-comments-refs";
import {MyClass2} from "script-nocomments-norefs";
import {MyClass3} from "script-nocomments-refs";
export interface IndexLib { Class2: MyClass2, Class3: MyClass3 }
```

If I compile such file with `--declaration` the first import will be removed (as it doesn't contribute to module API):

`index.d.ts`:
```
import { MyClass2 } from "script-nocomments-norefs";
import { MyClass3 } from "script-nocomments-refs";
export interface IndexLib {
    Class2: MyClass2;
    Class3: MyClass3;
}
```
As you can see the banner disappears.
So it disappears for js output:
`index.js`:
```
define(["require", "exports"], function (require, exports) {
    "use strict";
    exports.__esModule = true;
});
//# sourceMappingURL=index.js.map
```

Is there any way to keep top jsdoc comments for all files in *.d.ts and *.js (besides adding a fake comments)?

**Comment by mhegazy** [comment]
A comment is attached to the declaration that follows it directly. if the declaration is not emitted, then the comment is not either.

A comment can be detached if it appears at the beginning of the file, and has a line break before the first declaration. detached comments are preserved in the output.. 

so simply make sure you have a new line after your comment and before the first `import`.

**Comment by evil-shrike** [comment]
Thanks. It does help for keeping comments in js, but not in .d.ts - there they are stripped out. 
It's not a big problem indeed (js is more important) but it'd be nice to have the same behavior for all .d.ts.

ts:
```ts
/**
 * @overview MegaLib v1.36.0 - 2018-04-04 22:47 
 * @author SuperCompany
 * @version 1.2.3
 * @copyright 2018 SuperCompany
 * @license Private
 */


import {MyClass1} from "script-comments-refs";
import {MyClass2} from "script-nocomments-norefs";
import {MyClass3} from "script-nocomments-refs";

export interface IndexLib { Class2: MyClass2, Class3: MyClass3 }
```

d.ts:
```ts
import { MyClass2 } from "script-nocomments-norefs";
import { MyClass3 } from "script-nocomments-refs";
export interface IndexLib {
    Class2: MyClass2;
    Class3: MyClass3;
}
```

**Comment by mhegazy** [comment]
Something else is going on.. here is what am seeing locally:

```shell
c:\test\23164>type a.ts
/**
 * @overview MegaLib v1.36.0 - 2018-04-04 22:47
 * @author SuperCompany
 * @version 1.2.3
 * @copyright 2018 SuperCompany
 * @license Private
 */


import {MyClass1} from "script-comments-refs";
import {MyClass2} from "script-nocomments-norefs";
import {MyClass3} from "script-nocomments-refs";

export interface IndexLib { Class2: number, Class3: number }

c:\test\23164>tsc --v
Version 2.9.0-dev.20180402

c:\test\23164>tsc --d

c:\test\23164>type a.js
"use strict";
/**
 * @overview MegaLib v1.36.0 - 2018-04-04 22:47
 * @author SuperCompany
 * @version 1.2.3
 * @copyright 2018 SuperCompany
 * @license Private
 */
Object.defineProperty(exports, "__esModule", { value: true });

c:\test\23164>type a.d.ts
/**
 * @overview MegaLib v1.36.0 - 2018-04-04 22:47
 * @author SuperCompany
 * @version 1.2.3
 * @copyright 2018 SuperCompany
 * @license Private
 */
export interface IndexLib {
    Class2: number;
    Class3: number;
}
```

**Comment by evil-shrike** [comment]
I've tried typescript@next and it works (in the same way as in your case).
Before I was using TS 2.6, 2.7 and 2.8 (no comments in d.ts), with 2.9 comments are emitted in d.ts.

**Comment by mhegazy** [comment]
thanks. we have rewritten the declaration emitter in 2.9, let me investigate more why it was not working before.

**Comment by mhegazy** [comment]
in 2.8 and before we only emitted detached comments if they were copywriter (start with `/*!`). now we are emitting them correctly all the time.
