### ISSUE TITLE
Compiler option `noEmitOnError` not working with tsc 2.8.1

### ISSUE THREAD

**Issue by andremarcondesteixeira** [Microsoft/TypeScript#23179]
# Steps to reproduce:
1. Create a new folder and name it whatever you want.
2. Enter the folder you just created
3. Inside the folder, create a file called `tsconfig.json`
4. Inside `tsconfig.json`, type in the following code:
``` json
{
    "compilerOptions": {
        "noEmitOnError": true
    }
}
```
5. Inside the same folder, create a file named `main.ts`
6. Type in the following code inside `main.ts`:
``` typescript
function log(message) {
    console.log(message)

const message: string = 'Hello World!'
message = 1

log(message)
```
7. Open a command line tool. The tools that I tried with were Git Bash and Windows Command Prompt (cmd)
8. Inside the command line tool, go inside the folder you created
9. run `tsc main.ts`

# Expected behavior:
No output javascript file would be generated.

# Actual behavior:
The compiler generates a file called `main.js`, while also trying to fix my syntax errors

# Environment
**Operating System**: Windows 10 Fall Creators Update
**Tools used**: Issue is happening using `Git Bash` and `CMD`
**tsc version**: 2.8.1

# Related Issues:
#2216 and #15249

**Comment by andremarcondesteixeira** [comment]
As a note: I Installed my typescript by using `npm i -g typescript`

**Comment by mhegazy** [comment]
> `run tsc main.ts`

that is the problem there.. running the compiler with a list of files does not pick the configurations from he config file.

so you either need to run it as:

```shell
tsc --p ./tsconfig.json
```

or 

```shell
tsc --noEmitOnError main.ts
```

**Comment by andremarcondesteixeira** [comment]
@mhegazy you're right. I didn't know about that --p option
