### ISSUE TITLE
Missing typings for URLSearchParams

### ISSUE THREAD

**Issue by philnova** [Microsoft/TypeScript#23174]
**Search Terms:** 

URLSearchParams

**Code**

const params = new URLSearchParams('?q=hello');
const keys = [...params.keys()]

**Expected behavior:**

(no error)

**Actual behavior:**

[ts] Property 'keys' does not exist on type 'URLSearchParams'

**Playground Link:**  

**Related Issues:**

**Comment by mhegazy** [comment]
Make sure you compiler with either:
`tsc --target es6`
or
`tsc --target es5 --lib es6,dom,dom.iterable --downlevelIteration`
