### ISSUE TITLE
Intellisense stops returning anything in js project

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#23183]
_From @andreasgruenh on April 5, 2018 16:35_

- VSCode Version: 1.21.1
- OS Version: Win 10 pro

Steps to Reproduce:

1. Initiate a create-react-app project (I cannot reproduce the error in a blank project)
2. Add a jsconfig.json with the content: `{}`
3. Open src/App.js
4. Hover and Intellisense (triggered by ctrl + space) should work
5. Create a new file "src/x.js"
6. Intellisense should still work
7. Type `import React from 'react';`
8. Test if intellisense is still working (if not, delete the file and go back to step 5 and use another filename)

After looping 3-6 times, the error occurs and Intellisense and hover information are broken and will only come back when the tsserver is restarted.

Does this issue occur when all extensions are disabled?: Yes

I uploaded the log when this occured here: https://gist.github.com/andreasgruenh/95dfe15dd23d3dfdb547db088199fdbd

Here is a gif of the reproduction: https://gfycat.com/LavishMasculineDuckbillplatypus
The Window has been reloaded directly before the start of the gif and the bug occurs after the 4th file has been created.

_Copied from original issue: Microsoft/vscode#47248_

**Comment by mjbvz** [comment]
Moving over to typescript repo for better visibility.

I see a `Error: No Project.` exception in the logs but am not sure if this is a symptom of the problem or could be the cause. There also seems to be a weird `c:/jsconfig.json` project being created

@andreasgruenh Can you please test this using the just released VS Code 1.22 as well

**Comment by sheetalkamat** [comment]
From the log it looks like the [getErr](https://gist.github.com/andreasgruenh/95dfe15dd23d3dfdb547db088199fdbd#file-tsserver-log-L2725) is sent after [closing the script info](https://gist.github.com/andreasgruenh/95dfe15dd23d3dfdb547db088199fdbd#file-tsserver-log-L2700). So the throw no project seems correct

**Comment by andreasgruenh** [comment]
Thanks for the quick response!

The error is still happening in 1.22.1 (this time after the second created file).
Recreated it with the newest version and --disable-extensions. Here are the logs: https://gist.github.com/andreasgruenh/c6c9a87131de87e60ed756f00c2ac881

**Comment by mikevaleriano** [comment]
I'm not seeing anything out of the ordinary in my logs, but this time intellisense is **completely** broken.

It was bad that it stopped after a while in the previous build, but now, right from the start, it doesn't have any suggestions for anything, with or without extensions enabled.

**Comment by lednhatkhanh** [comment]
Happens for me too, really annoying...

**Comment by sheetalkamat** [comment]
@andreasgruenh in https://gist.github.com/andreasgruenh/c6c9a87131de87e60ed756f00c2ac881 there is no Info 939 or anything beyond Info 759

**Comment by sheetalkamat** [comment]
@andreasgruenh Thanks, I got the logs. Will take a look.

**Comment by sheetalkamat** [comment]
@andreasgruenh can you please try out the next drop that gets release tonight to see if it helps with the issue. Thanks.

**Comment by mhegazy** [comment]
that is `typescript@next` published tomorrow. `typescript@2.9.0-dev.20180407` to be exact.

**Comment by andreasgruenh** [comment]
@sheetalkamat Your fix seems to work for me! Thank you so much for reacting so quickly!

**Comment by mhegazy** [comment]
Should be in 2.8.2 as well

**Comment by byteskw** [comment]
me to, im using react native for my vscode, after 2 minutes - 10 minutes always infinite loading my intellisense vscode,

please fix this

**Comment by mikevaleriano** [comment]
vscode 1.22.2 fixed all the issues I was having.

**Comment by byteskw** [comment]
what your problem, before your update to vscode 1.22.2? 
@mikevaleriano

**Comment by mikevaleriano** [comment]
@byteskw Intellisense would stop working after a few minutes. That was when 1..21 came out in February.

It was tolerable, but I had to use the Reload Window command often. Then 1.22 came in early March (it probably was 1.22.0) and Intellisense was completely broken out of the box - it wouldn't work with the TypeScript version it came with, or any other you could install elsewhere.

1.22.1 came a few days later without a proper solution, and I actually started looking back at atom for a while, but 1.22.2 was released a couple days ago and everything seems fixed.

I'm using the version it comes with it, 2.8.1. This leads me to believe there was never a problem with TypeScript to begin with, and it was a vscode issue that they finally handled.

**Comment by andreasgruenh** [comment]
@mikevaleriano These problems still occur to me on vscode 1.22.2. With TS 2.9, they seem to be fixed. The error on the TypeScript side should be fixed with TS 2.8.2 as @mhegazy said, so I'm waiting patiently for that one.
