### ISSUE TITLE
Consider not mentioning namespaces as much in the handbook

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [microsoft/TypeScript#23189]
When directing people to read the TypeScript handbook, it's necessary to caveat it with _"but skip anything with `namespace`s!"_. Can we just move those pages from the handbook into, say, the Declaration Files section? Docs should certainly exist for them, but it's distracting and misleading mentioning them as first-level constructs.

Perhaps they should also mention that they're discouraged at the top of the page?

**Comment by mhegazy** [comment]
> "but skip anything with namespaces!".

Not sure why. namespaces do have a use in the language just like classes and enums.

Moreover, a quick search on the handbook has namespaces only referenced in declarations section, namespace section. see https://github.com/Microsoft/TypeScript-Handbook/search?l=Markdown&p=1&q=namespace&type=

> them as first-level constructs.

we have no intention on deprecating or removing namespaces.. all the compiler is written using them. we have other users that depend on them as well.

**Comment by JoshuaKGoldberg** [comment]
> them as first-level constructs.

Oh, to disambiguate - I mean as a first-level construct _to learn_. Do most people who write TypeScript actually use them? Outside of TypeScript _(and TSLint, go figure)_, are they used more than rarely?

I'm under the impression the majority of newer TypeScript projects and newer JavaScript projects use AMD, CJS, or ES modules without the equivalent constructs for namespaces. Is that not the case?
If it is, it feels like too much unnecessary content to teach users as core need-to-know or should-know material in the handbook. 

Two proposals for actions to take:

1. Add a disclaimer to the top of the file that mentions ES modules as the preferred way to share code across files
2. Add a Miscellaneous section under Handbook and plop _Namespaces_ and _Modules and Namespaces_ there.
    * Perhaps _Mixins_ as well?

**Comment by JoshuaKGoldberg** [comment]
This has since been resolved with Orta's handbook work. 🎉
