### ISSUE TITLE
Cannot import property of external module

### ISSUE THREAD

**Issue by sccolbert** [Microsoft/TypeScript#2318]
With internal modules, one can do this:

```typescript
import MyType = mymodule.MyType
```

With external modules, this is a syntax error:

```typescript
import MyType = require('mymodule').MyType;
```

The solution is a second import statement:

```typescript
import mymodule = require('mymodule');
import MyType = mymodule.MyType;
```

A suggestion would be to allow a `require(...)` call to be followed by dotted property access.

**Comment by danquirk** [comment]
I suspect the guidance here is going to be to make use of whichever style of ES6 module import is best for your scenario and we'll avoid adding much functionality to our original external module style/syntax (in order to encourage people to use ES6 style module syntax).

**Comment by mhegazy** [comment]
With the new syntax, your example would be:
```ts
import {MyType} from "mymodule";
```
