### ISSUE TITLE
Recursive conditional types inconsistent behaviour

### ISSUE THREAD

**Issue by aczekajski** [Microsoft/TypeScript#23193]
**TypeScript Version:**  2.8.1

**Search Terms:** recursive conditional types

The documentation clearly states that _"Similar to union and intersection types, conditional types are not permitted to reference themselves recursively"_. If that's the case, why it's actually possible to write this:
```ts
type DeepRequired<T> =
   T extends {} ? {
      [K in keyof T]-?: DeepRequired<T[K]>;
   } : T;
```
but it's impossible to add an additional case for arrays to leave them untouched, like this:
```ts
type DeepRequired<T> =
   T extends any[] ? Array<DeepRequired<T[number]>> :
   T extends {} ? {
      [K in keyof T]-?: DeepRequired<T[K]>;
   } : T;
```

I think that either both should be an error or both should be allowed.

**Comment by mhegazy** [comment]
The error is generated iff the compiler is checking the type, and it finds itself recursing on the same type.

in the first example, the computation of the mapped type is deferred, so no need to refer to `DeepRequired` to understand what the type of it looks like. the compiler knows it is always going to be an object (generated from a mapped type).

in the second case, the compiler needs to check the constraints on `Array` to verify that `DeepRequired<T[number]>` is a valid type argument, and once it does that, it recurses on `DeepRequired` again.

you can break the recursive reference using an interface:

```ts
type DeepRequired<T> =
    T extends any[] ? DeepRequiredArray<T[number]> :
    T extends {} ? {
        [K in keyof T]-?: DeepRequired<T[K]>;
    } : T;

interface DeepRequiredArray<T> extends Array<DeepRequired<T>> { }
```
