### ISSUE TITLE
getSourceFile().moduleName is undefined

### ISSUE THREAD

**Issue by alan-agius4** [Microsoft/TypeScript#23195]
**TypeScript Version:**  2.8.1

**Code**

**index.ts**
```ts
it('should', () => "");
```

**checker.ts**
```ts
import * as ts from "typescript"

const program = ts.createProgram(["./index.ts"], { types: ["jasmine"] });
const sourceFile = program.getSourceFile("./index.ts");
const checker = program.getTypeChecker();

ts.forEachChild(sourceFile, checkNested);

function checkNested(node: ts.Node) {
  if (ts.isCallExpression(node)) {
    const signature = checker.getResolvedSignature(node);
    const file = signature.getDeclaration().getSourceFile();

    // file.fileName -> ​​​​​c:/git/testing-typescript/node_modules/@types/jasmine/index.d.ts​​​​​
    // file.moduleName -> ​​​​​undefined​​​​​
  }

  ts.forEachChild(node, checkNested);
}
```

**Expected behavior:**
I expected that the moduleName returned is not undefined but the moduleName of the source file.

My end goal here is that I want to know in which module the expression that I am using is defined in that case the Jasmine `it`. 

**Actual behavior:**
When I run checker.ts The filename is resolved and the moduleName is always undefined.

**Comment by ajafff** [comment]
You actually want to use `file.fileName`.

`moduleName` is something related to AMD modules. But that comment is not present in the generated declaration files.

**Comment by alan-agius4** [comment]
I noticed that there is `.getSourceFile().ambientModuleNames` which return the moduleName as expected example `jasmine` however this property is not typed.

**Comment by alan-agius4** [comment]
Is there anyway to get the moduleName ie: 'jasmine' in any other way?

**Comment by andy-ms** [comment]
@alan-agius4 That's not really easy since it requires going backwards from a module path to the way it was imported. You could construct a reverse mapping yourself by looping over the imports of each module and getting what they resolved to:
```ts
function add<K, V>(map: Map<K, V[]>, key: K, value: V): void {
    const values = map.get(key);
    if (values) values.push(value); else map.set(key, [value]);
}

function createReverseMap(program: ts.Program): Map<ts.SourceFile, string[]> {
    const checker = program.getTypeChecker();
    const map = new Map<ts.SourceFile, string[]>();
    for (const importer of program.getSourceFiles()) {
        for (const statement of importer.statements) {
            if (!ts.isImportDeclaration(statement) || !ts.isStringLiteral(statement.moduleSpecifier)) continue;
            const importedSym = checker.getSymbolAtLocation(statement.moduleSpecifier)!;
            for (const decl of importedSym.declarations!) {
                if (ts.isSourceFile(decl)) {
                    add(map, decl, statement.moduleSpecifier.text);
                }
            }
        }
    }
    return map;
}
```

If you're wondering how we synthesize imports for completions, see `function getNewImportInfos` in `importFixes.ts` in this repository, but that method's pretty complicated.

**Comment by alan-agius4** [comment]
Thanks @andy-ms for your response and help. I'll have a look at the mentioned implementation. Though my biggest problem was that I don't have `import` declarations as the module I am interested in is an ambient module.

I ended up doing something  along these lines;

```ts
function isJasmineModule(checker: Checker, node: ts.CallExpression): boolean {
  // get the `jasmine` module file path
  const jasmineModule = checker.typeChecker
    .getAmbientModules()
    .find(x => x.name.replace(/"/g, '') === 'jasmine');

  if (!jasmineModule) {
    return false;
  }
  const declarations = jasmineModule.getDeclarations();
  let jasmineModulePath = '';
  if (declarations && declarations.length) {
    jasmineModulePath = declarations[0].getSourceFile().fileName;
  }

  const signature = checker.typeChecker.getResolvedSignature(node);
  const file = signature.getDeclaration().getSourceFile();

  // math the file path of the `it` with that of `jasmine`
  return jasmineModulePath === file.fileName;
}
```
