### ISSUE TITLE
Debug Failure. Unhandled declaration kind!

### ISSUE THREAD

**Issue by deltakosh** [Microsoft/TypeScript#23194]
Hey
I found this closed issue: **https://github.com/Microsoft/TypeScript/issues/21928** but unfortunately I still have the same problem on 2.8.1

**TypeScript Version:**  2.8.1

**Search Terms:** Debug Failure. Unhandled declaration kind! 233

**Code**
It happens on Babylon.js project: 
* fork the project
* go to src and run tsc from the command line

**Related Issues:**
https://github.com/Microsoft/TypeScript/issues/21928

**Comment by deltakosh** [comment]
False alert :) deleting and recreating my folder works...Still weird but at least now it works!

**Comment by ssaket** [comment]
I tried deleting the node_modules but didn't work for me. When you said - deleting and recreating my folder works, did you delete the debug folder inside src ?

**Comment by deltakosh** [comment]
I removed the entire node modules folder
