### ISSUE TITLE
Got "Cannot read property 'kind' of undefined" in preparing build for production in ionic

### ISSUE THREAD

**Issue by rajanshahsa** [Microsoft/TypeScript#23196]
Hello,

I have typescript v2.8.1 install in my ionic project. Whenever I am executing 
```
ionic cordova build ios --prod
```
I am getting following error 

TypeError: Cannot read property 'kind' of undefined
    at declareSymbolAndAddToSymbolTable (/Users/rajan.shah/SA_Project/Project/xxxxx/SourceCode_ionic/node_modules/typescript/lib/typescript.js:21251:30)
    at bindPropertyOrMethodOrAccessor (/Users/rajan.shah/SA_Project/Project/xxxxx/SourceCode_ionic/node_modules/typescript/lib/typescript.js:22225:19)
    at bindWorker (/Users/rajan.shah/SA_Project/Project/xxxxx/SourceCode_ionic/node_modules/typescript/lib/typescript.js:21778:28)
    at bind (/Users/rajan.shah/SA_Project/Project/xxxxx/SourceCode_ionic/node_modules/typescript/lib/typescript.js:21627:13)
    at bindSourceFile (/Users/rajan.shah/SA_Project/Project/xxxxx/SourceCode_ionic/node_modules/typescript/lib/typescript.js:20036:17)
    at Object.bindSourceFile (/Users/rajan.shah/SA_Project/Project/xxxxx/SourceCode_ionic/node_modules/typescript/lib/typescript.js:19979:9)
    at initializeTypeChecker (/Users/rajan.shah/SA_Project/Project/xxxxxSourceCode_ionic/node_modules/typescript/lib/typescript.js:47371:20)
    at Object.createTypeChecker (/Users/rajan.shah/SA_Project/Project/xxxxx/SourceCode_ionic/node_modules/typescript/lib/typescript.js:24920:9)
    at Object.getTypeChecker (/Users/rajan.shah/SA_Project/Project/xxxxx/SourceCode_ionic/node_modules/typescript/lib/typescript.js:74466:79)
    at moduleNameResolvesToAmbientModuleInNonModifiedFile (/Users/rajan.shah/SA_Project/Project/xxxxx/SourceCode_ionic/node_modules/typescript/lib/typescript.js:74222:88)

This error comes only when I am trying to build for **production**, not for **development**.

**Comment by MarioPadilla** [comment]
Both **ionic build** with flag "**--prod**" or "**--aot**" fails. 

The same issue in [TSLint/issues/#3689](https://github.com/palantir/tslint/issues/3689)
In the worst case, you always can downgrade your typescript version.

**Comment by rajanshahsa** [comment]
@MarioPadilla I tried with v2.7 got the same error. Do you know which version it works fine?

**Comment by MarioPadilla** [comment]
@rajanshahsa try with v.2.6.2

**Comment by andy-ms** [comment]
@rajanshahsa Could you provide a reproducible example that consists of a TypeScript file and a `tsconfig.json` that fails when you run `tsc` on the command line?

**Comment by rajanshahsa** [comment]
@MarioPadilla 

I install v2.6.2. Now it gives a different error.

TypeError: compiler_1.isFormattedError is not a function
    at syntaxErrorToDiagnostics (/Users/rajan.shah/SA_Project/Project/XXXXXX/SourceCode_ionic/node_modules/@angular/compiler-cli/src/transformers/program.js:798:25)
    at AngularCompilerProgram._addStructuralDiagnostics (/Users/rajan.shah/SA_Project/Project/XXXXXX/SourceCode_ionic/node_modules/@angular/compiler-cli/src/transformers/program.js:485:49)
    at AngularCompilerProgram._createProgramOnError (/Users/rajan.shah/SA_Project/Project/XXXXXX/SourceCode_ionic/node_modules/@angular/compiler-cli/src/transformers/program.js:477:18)
    at /Users/rajan.shah/SA_Project/Project/XXXXXX/SourceCode_ionic/node_modules/@angular/compiler-cli/src/transformers/program.js:151:48

**Comment by rajanshahsa** [comment]
@andy-ms 


Here is my "tsconfig.json"

```

{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "dom",
      "es2015"
    ],
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "target": "es5"
  },
  "include": [
    "src/**/*.ts"
  ],
  "exclude": [
    "node_modules",
    "src/**/*.spec.ts",
    "src/**/__tests__/*.ts"
  ],
  "compileOnSave": false,
  "atom": {
    "rewriteTsconfig": false
  }
}
```

**Comment by ohrrkan** [comment]
Same issue. My tsconfig.json : 

`{
  "compilerOptions": {
    /* Basic Options */
    "target": "es5", /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', or 'ESNEXT'. */
    "module": "commonjs", /* Specify module code generation: 'commonjs', 'amd', 'system', 'umd', 'es2015', or 'ESNext'. */
    // "module": "es2015", /* Specify module code generation: 'commonjs', 'amd', 'system', 'umd', 'es2015', or 'ESNext'. */ 
    "lib": [
      "dom",
      "es2017"
    ], /* Specify lirary files to be included in the compilation:  */
    // "allowJs": true,                       /* Allow javascript files to be compiled. */
    // "checkJs": true,                       /* Report errors in .js files. */
    // "jsx": "preserve",                     /* Specify JSX code generation: 'preserve', 'react-native', or 'react'. */
    "declaration": false, /* Generates corresponding '.d.ts' file. */
    "sourceMap": true, /* Generates corresponding '.map' file. */
    // "outFile": "./",                       /* Concatenate and emit output to single file. */
    //"outDir": "./", /* Redirect output structure to the directory. */
    "rootDir": "./src", /* Specify the root directory of input files. Use to control the output directory structure with --outDir. */
    "removeComments": true, /* Do not emit comments to output. */
    // "noEmit": true,                        /* Do not emit outputs. */
    "importHelpers": true, /* Import emit helpers from 'tslib'. */
    // "downlevelIteration": true,            /* Provide full support for iterables in 'for-of', spread, and destructuring when targeting 'ES5' or 'ES3'. */
    // "isolatedModules": true,               /* Transpile each file as a separate module (similar to 'ts.transpileModule'). */
    /* Strict Type-Checking Options */
    "strict": true, /* Enable all strict type-checking options. */
    "skipLibCheck": true,
    "noImplicitAny": true, /* Raise error on expressions and declarations with an implied 'any' type. */
    "strictNullChecks": true, /* Enable strict null checks. */
    "noImplicitThis": true, /* Raise error on 'this' expressions with an implied 'any' type. */
    "alwaysStrict": true, /* Parse in strict mode and emit "use strict" for each source file. */
    /* Additional Checks */
    "noUnusedLocals": true, /* Report errors on unused locals. */
    "noUnusedParameters": true, /* Report errors on unused parameters. */
    "noImplicitReturns": true, /* Report error when not all code paths in function return a value. */
    "noFallthroughCasesInSwitch": true, /* Report errors for fallthrough cases in switch statement. */
    /* Module Resolution Options */
    "moduleResolution": "node", /* Specify module resolution strategy: 'node' (Node.js) or 'classic' (TypeScript pre-1.6). */
    // "baseUrl": "./",                       /* Base directory to resolve non-absolute module names. */
    // "paths": {},                           /* A series of entries which re-map imports to lookup locations relative to the 'baseUrl'. */
    // "rootDirs": [],                        /* List of root folders whose combined content represents the structure of the project at runtime. */
    "typeRoots": [
      "node_modules/@types"
    ], /* List of folders to include type definitions from. */
    // "types": [],                           /* Type declaration files to be included in compilation. */
    "allowSyntheticDefaultImports": true, /* Allow default imports from modules with no default export. This does not affect code emit, just typechecking. */
    /* Source Map Options */
    // "sourceRoot": "./",                    /* Specify the location where debugger should locate TypeScript files instead of source locations. */
    // "mapRoot": "./",                       /* Specify the location where debugger should locate map files instead of generated locations. */
    // "inlineSourceMap": true,               /* Emit a single file with source maps instead of having a separate file. */
    // "inlineSources": true,                 /* Emit the source alongside the sourcemaps within a single file; requires '--inlineSourceMap' or '--sourceMap' to be set. */
    /* Experimental Options */
    "experimentalDecorators": true, /* Enables experimental support for ES7 decorators. */
    "emitDecoratorMetadata": true /* Enables experimental support for emitting type metadata for decorators. */
    //  "module": "es2015",
  },
  "include": [
    "src/**/*.ts"
  ],
  "exclude": [
    "node_modules"
  ],
  "compileOnSave": false,
  "atom": {
    "rewriteTsconfig": false
  }
}
`

**Comment by rajanshahsa** [comment]
@andy-ms Did you get chance to look into this?

**Comment by andy-ms** [comment]
@rajanshahsa Could you provide TypeScript sample code that reproduces the issue?

**Comment by rajanshahsa** [comment]
@andy-ms 


```
 function declareSymbolAndAddToSymbolTable(node, symbolFlags, symbolExcludes) {
            switch (container.kind) {
                // Modules, source files, and classes need specialized handling for how their
                // members are declared (for example, a member of a class will go into a specific
                // symbol table depending on if it is static or not). We defer to specialized
                // handlers to take care of declaring these child members.
                case 237 /* ModuleDeclaration */:
                    return declareModuleMember(node, symbolFlags, symbolExcludes);
                case 272 /* SourceFile */:
                    return declareSourceFileMember(node, symbolFlags, symbolExcludes);
                case 203 /* ClassExpression */:
                case 233 /* ClassDeclaration */:
                    return declareClassMember(node, symbolFlags, symbolExcludes);
                case 236 /* EnumDeclaration */:
                    return declareSymbol(container.symbol.exports, container.symbol, node, symbolFlags, symbolExcludes);
                case 165 /* TypeLiteral */:
                case 283 /* JSDocTypeLiteral */:
                case 182 /* ObjectLiteralExpression */:
                case 234 /* InterfaceDeclaration */:
                case 261 /* JsxAttributes */:
                    // Interface/Object-types always have their children added to the 'members' of
                    // their container. They are only accessible through an instance of their
                    // container, and are never in scope otherwise (even inside the body of the
                    // object / type / interface declaring them). An exception is type parameters,
                    // which are in scope without qualification (similar to 'locals').
                    return declareSymbol(container.symbol.members, container.symbol, node, symbolFlags, symbolExcludes);
                case 162 /* FunctionType */:
                case 163 /* ConstructorType */:
                case 157 /* CallSignature */:
                case 158 /* ConstructSignature */:
                case 159 /* IndexSignature */:
                case 153 /* MethodDeclaration */:
                case 152 /* MethodSignature */:
                case 154 /* Constructor */:
                case 155 /* GetAccessor */:
                case 156 /* SetAccessor */:
                case 232 /* FunctionDeclaration */:
                case 190 /* FunctionExpression */:
                case 191 /* ArrowFunction */:
                case 280 /* JSDocFunctionType */:
                case 235 /* TypeAliasDeclaration */:
                case 176 /* MappedType */:
                    // All the children of these container types are never visible through another
                    // symbol (i.e. through another symbol's 'exports' or 'members').  Instead,
                    // they're only accessed 'lexically' (i.e. from code that exists underneath
                    // their container in the tree). To accomplish this, we simply add their declared
                    // symbol to the 'locals' of the container.  These symbols can then be found as
                    // the type checker walks up the containers, checking them for matching names.
                    return declareSymbol(container.locals, /*parent*/ undefined, node, symbolFlags, symbolExcludes);
            }
        }

```

**Comment by tangooncash** [comment]
I don't understand

**Comment by rajanshahsa** [comment]
@tangooncash 

This line cause error.

``` 
switch (container.kind) {
```

(/Users/rajan.shah/SA_Project/Project/xxxxx/SourceCode_ionic/node_modules/typescript/lib/typescript.js:21251:30)

**Comment by tangooncash** [comment]
What does case 237 mean and so on? Is that 237 dollars?

**Comment by rajanshahsa** [comment]
@tangooncash  Actually I don't know this is "typescript.js" file from typescript package module.

**Comment by andy-ms** [comment]
@rajanshahsa I meant, can you provide *your* code that reproduces the error -- a `.ts` file that when compiled will fail.
