### ISSUE TITLE
any[] inferred even with noImplicitAny

### ISSUE THREAD

**Issue by pelotom** [Microsoft/TypeScript#23192]
**TypeScript Version:**  2.7.2, 2.8.1

**Search Terms:** 

`any` `array` `noImplicitAny` `push`

**Code**

With `noImplicitAny` enabled, this

```ts
function foo() {
  const x = []
  x.push(3)
  return x
}
```

has no errors even though `x`, and therefore the return type of `foo`, are inferred to be `any[]`. Commenting out the `x.push(3)` results in the expected error,

```
Variable 'x' implicitly has type 'any[]' in some locations where its type cannot be determined.
```

[**Playground Link**](http://www.typescriptlang.org/play/#src=%2F%2F%20Error%2C%20as%20expected%0D%0Afunction%20bar()%20%7B%0D%0A%20%20const%20x%20%3D%20%5B%5D%0D%0A%20%20return%20x%0D%0A%7D%0D%0A%0D%0A%2F%2F%20No%20error%20even%20though%20there%20should%20be%0D%0Afunction%20foo()%20%7B%0D%0A%20%20const%20x%20%3D%20%5B%5D%0D%0A%20%20x.push(3)%0D%0A%20%20return%20x%0D%0A%7D)

**Comment by mhegazy** [comment]
The type of the array is inferred to be an "evolving array" type. it then becomes `number` after the first `x.push`.  `foo` should be returning `number []`.

If the type of `x` is witnessed before control flow can determine its type, and error is produced. e.g.:
```ts
// No error even though there should be
function foo() {
  const x = []
  x.push(3)
  return x;

  function f() { 
    x; // error, x is `any`.
  }
}
```

**Comment by mhegazy** [comment]
see https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#improved-any-inference for more details.

**Comment by pelotom** [comment]
Ah, my mistake, I could've sworn the return type was being inferred as `any[]`.
