### ISSUE TITLE
NonNullable type should remove void type

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#23205]
cc @ahejlsberg 

**TypeScript Version:**  2.7.0-dev.20180405

**Search Terms:** 

**Code**

```ts
type N = NonNullable<1 | void>;
```

**Expected behavior:**

N is `1`.

**Actual behavior:**

N is `1 | void`.

**Playground Link:**  

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
Consider
```ts
const f: () => void = () => 10;
const v = !!!false ? f() : "hello";
const t = NonNullable<v>; // t: string | void
```
Giving type `t` `string` would be incorrect.
