### ISSUE TITLE
Consider ({}).hasOwnProperty instead of Object.prototype.hasOwnProperty in __assign

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Microsoft/TypeScript#23208]
```javascript
var __assign = (this && this.__assign) || Object.assign || function(t) {
    for (var s, i = 1, n = arguments.length; i < n; i++) {
        s = arguments[i];
        for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p))
            t[p] = s[p];
    }
    return t;
};
```

`{}.hasOwnProperty` should be identical to `Object.prototype.hasOwnProperty`. A little bit less code.

```javascript
Object.prototype.hasOwnProperty = () => console.log("Ha!");
({}).hasOwnProperty(); // "Ha!"
```

**Comment by RyanCavanaugh** [comment]
It's a hard-to-measure performance trade-off to cause an object allocation for each property iterated by `__assign`. I'd defer to the current behavior since people can provide their own helper if they need those 11 bytes.

**Comment by JoshuaKGoldberg** [comment]
I would hope `{}.hasOwnProperty` gets optimized away... interesting question.
