### ISSUE TITLE
DateConstructor: number|string union lib.d.ts missing

### ISSUE THREAD

**Issue by HolgerJeromin** [Microsoft/TypeScript#23202]
**TypeScript Version:**  2.8.1 and master

**Search Terms:** DateConstructor Date VarDate

#21757 changed DateConstructor to use a union in lib.es5.d.ts and es2015.core.d.ts
for this type of code:
```ts
let date; string | number; const date = new Date(x);
```

But current (incl 2.8.1) lib.d.ts is missing this 
https://github.com/Microsoft/TypeScript/blob/2167b244414a83ccec18edc6d88434cf0ace7475/lib/lib.d.ts#L793-L796

One commit changed a file in /lib and another changed /src/lib. Seems to be the root problem.

**Related Issues:**
#21758  #20900

@alan-agius4

**Comment by alan-agius4** [comment]
Thanks for reporting this. I’ll do a fix soon.

**Comment by mhegazy** [comment]
thanks @HolgerJeromin

**Comment by HolgerJeromin** [comment]
@alan-agius4  i should have mention it in this issue :-)

**Comment by alan-agius4** [comment]
No worries, always glad to have more people doing contributions to open
source 😀
