### ISSUE TITLE
Allow property decorator to return `TypedPropertyDescriptor<T>` 

### ISSUE THREAD

**Issue by ShawnTalbert** [Microsoft/TypeScript#23210]
I'd like to suggest that a property decorator return type be widened to include `TypedPropertyDescriptor<T>` 

Currently the compiler complains that property decorators can only return `void` or `any` which means I can't get nice strong typing from my property decorators which return property descriptors. Similar to how `MethodDecorator` is declared in `lib.es6.d.ts`?

**Search Terms:** 
TypedPropertyDescriptor

**Comment by mhegazy** [comment]
but at runtime the decorator will not change the property.. so not sure what the return value is for.

**Comment by ShawnTalbert** [comment]
I may be misinterpreting the 'specs' for decorators, but both the older spec (which TS is based on?) and the [current one](https://github.com/tc39/proposal-decorators/blob/master/METAPROGRAMMING.md#field-decorator)(?) it seems valid that a property decorator can return a propertyDescriptor which will replace the underlying. 

I lean on that feature _heavily_ in my use of decorators.
