### ISSUE TITLE
Update Angular logo in quick start on typescriptlang.org

### ISSUE THREAD

**Issue by splincode** [Microsoft/TypeScript#23227]
Please update the logo of the official Angular

**Expected behavior:**

![image](https://user-images.githubusercontent.com/12021443/38439770-9a17d31a-39e7-11e8-9911-0b1abd8fd06b.png)

**Actual behavior:**

![](https://angular.io/assets/images/logos/angular/angular.svg)

**Comment by DanielRosenwasser** [comment]
Major facepalm 🤦‍♂️; this should be fixed on our next website update.

**Comment by splincode** [comment]
@DanielRosenwasser Did you close the task because you solved it?
