### ISSUE TITLE
Conditional types cannot infer args array

### ISSUE THREAD

**Issue by tyrielv** [Microsoft/TypeScript#23229]
**TypeScript Version:**  2.9.0-dev.20180406

**Search Terms:** 
conditional type infer array parameter 
**Code**

```ts
// This works
type PromisifyWithOneArg<T> = {
    [P in keyof T]?: T[P] extends (arg: infer R1) => infer R2 ? (args: R1) => Promise<R2> : T[P];
};
// This doesn't
type Promisify<T> = {
    [P in keyof T]?: T[P] extends (...args: infer R1) => infer R2 ? (...args: R1) => Promise<R2> : T[P];
};


```

**Expected behavior:**
These type definitions work, allowing definition of a generic type that makes all methods in an interface return promises, while preserving the type constraints of the arguments.
**Actual behavior:**
The ...args version is rejected. I either have to define N versions of the conditional type with different numbers of arguments, or lose type safety for the arguments.

**Playground [Link](https://www.typescriptlang.org/play/#src=type%20PromisifyWithOneArg%3CT%3E%20%3D%20%7B%0D%0A%20%20%20%20%5BP%20in%20keyof%20T%5D%3F%3A%20T%5BP%5D%20extends%20(arg%3A%20infer%20R1)%20%3D%3E%20infer%20R2%20%3F%20(args%3A%20R1)%20%3D%3E%20Promise%3CR2%3E%20%3A%20T%5BP%5D%3B%0D%0A%7D%3B%0D%0A%0D%0Atype%20Promisify%3CT%3E%20%3D%20%7B%0D%0A%20%20%20%20%5BP%20in%20keyof%20T%5D%3F%3A%20T%5BP%5D%20extends%20(...args%3A%20infer%20R1)%20%3D%3E%20infer%20R2%20%3F%20(...args%3A%20R1)%20%3D%3E%20Promise%3CR2%3E%20%3A%20T%5BP%5D%3B%0D%0A%7D%3B%0D%0A%0D%0A):**  

**Related Issues:**

**Comment by mhegazy** [comment]
rest parameters need to be of array type...

```ts
type Promisify<T> = {
    [P in keyof T]?: T[P] extends (...args: Array<infer R1>) => infer R2 ? (...args: R1[]) => Promise<R2> : T[P];
};
```

general issue of unifying parameters and arrays/tuples is https://github.com/Microsoft/TypeScript/issues/5453
