### ISSUE TITLE
Difficulties with building a library for distributing

### ISSUE THREAD

**Issue by evil-shrike** [Microsoft/TypeScript#23222]
I'm trying to compile a lib for distributing. I want my npm package with the library has the following structure:
```
├───dist
│     ├───lib/*.js + *.d.ts + *.js.map
│     └───modules/*.js + *.d.ts
├───src
│     ├───lib/*.ts
│     └───modules/*.ts
├───tsconfig.json
└───package.json
```
Inside `dist` I want runtime (*.js) script, declaration files for compiling user apps (*.d.ts) and source maps (*.js.map) for debugging that point to sources inside *.ts.
It seems legit structure, nothing fancy. 

I staged all source files into `dist/src` folder. The folder `dist` contains `package.json`, `tsconfig.json` - it's root for npm package that will be published.   

There're two strategies:
1. compile with `-d` inside `dist/src` then rename it to `dist/dist` and move *.ts from it into `dist/src`
2. compile with `-d` and `--outDir dist/dist` options

It turns out that both approaches have problems and don't allow to create a working package.

1. If I compile with `-d` inside `dist/src` then source maps (*.js.map) will have local links (`"file":"file.js", "sourceRoot":"","sources":["file.ts"]`). That means that if I move `*.ts` later from that folder it'll break source mapping for the lib in runtime. It seems that `sourceRoot` option could solve that issue - but it doesn't work as expected - see #23180 (TL;DR: I I set it that tsc put local absolute file paths inside *.js.map).
2. If I compile with `-d` and redirecting into other folder via `--outDir` then another issue arises: if a ts-file has a reference to a declaration besides it (`.d.ts`) then that reference will be changed in output folder.
For example, in `dist/src` I have `file.ts` with a reference to `.stud.d.ts`:
```ts
/// <reference path="./.stubs.d.ts" />
```
after compilation with `-d --outDir ./dist/dist` we'll have `dist/dist/file.d.ts` with the following reference:
```ts
/// <reference path="../src/lib/.stubs.d.ts" />
```
Oh my. This is a problem as I can't copy all *.d.ts from `dist/src` to `dist/dist` because such references become invalid. You may ask me why should I copy `*.d.ts` from `src` to `dist`. Well `dist/dist` should complete distributive and it should work without `dist/src` (which is optional and can be even removed in some cases)

So I can't understand how it suppose to work. How is it meant libraries should be built for distributing?

**Comment by mhegazy** [comment]
I do not think the first approach is ideal. as you said it messes up your source maps, though you should know about `--sourceRoot` for these cases.

The second is what i would recommend. to have a recommendation on the .d.ts issue, i need to know what are these .d.ts files represent? are they your code? external dependencies? are they from npm?

**Comment by evil-shrike** [comment]
> though you should know about --sourceRoot for these cases.

yes, but as I noted `--sourceRoot` puts local absolute path into js.map that make then useless

>i need to know what are these .d.ts files represent? are they your code? 

it's my code usually with `declare module` like
```ts
declare module "xhtmpl!*" {
	const m: HandlebarsTemplateDelegate;
	export = m;
}
```
or
```ts
declare module "core.ui" {
	export * from "ui/.ui";
	export import Dialog = require("lib/ui/Dialog");
}
```
that for example allows me to put Dialog class into `core.ui.Dialog`-
`lib/ui/Dialog.ts`:
```ts
...
core.ui.Dialog = Dialog;
export = Dialog;
```

>also why are you using /// <references to start with?

if I don't add `/// <references ` then client app will have to include all *.d.ts explicitly from the lib. 

>external dependencies? are they from npm?

there're references to vendor's typings as well which distributed inside libraries (not from `@types`) like:
```ts
/// <reference path="../../../vendor/fancytree/jquery.fancytree.dnd.d.ts" />
```

**Comment by mhegazy** [comment]
> yes, but as I noted --sourceRoot puts local absolute path into js.map that make then useless

that seems like a bug in tsconfig.json parsing. we should fix that. on the command-line it should be used verbatim, you can also use `file:///./src` to avoid it being resolved.

**Comment by mhegazy** [comment]
seems like the .d.ts file is something you are adding manually. then i would just not use `///<references` at all. have a static file in your output call it `entrypoint.d.ts` this file all it has is:

```ts
/// <reference path="./mygloabls.d.ts" />
export * from "./index";
```

the other option is to have that .d.ts file in your dist folder directly, and add the `/// <reference` to it in the dist folder.

**Comment by evil-shrike** [comment]
Do I understand correctly that you are suggesting remove all `/// <reference>` imports from all my *.ts/*.d.ts and put all of them into a single d.ts file, right?
It's far from ideal solution for me. As the lib is modular and every module contains its own references.
And anyway that "entrypoint" should be imported somewhere and at that place its path in reference will be changed on compiling.

It's not clear why tsc can't copy referenced .d.ts into outDir with other created d.ts. If a script imports d.ts via `///<reference>` that means it's needed, so why not to copy it along?

**Comment by mhegazy** [comment]
So .d.ts files are not considered sources. the compiler does not generate output for them. think of all your `@types` packages for instance.. 
The compiler does not copy references either.. again think of all your `@types\node` package, you do not want its contents copied to your dist folder just cause you used `require`.
Triple-slash -reference tags are pointers to existing files to include in your compilation, that is all.. we had them before `tsconfig.json` was introduced. it is similar to adding the .d.ts file in the `include` section of your tsconfig.json..
The only difference is that the compiler traffics it to the output, and thus it ensures that it writes your triple-slash-reference tags correctly to output.., consider use case where you have multiple components with a shared folder with .d.ts files. you want the output to still point to the correct shared folder after it is moved.
Looks to me that the best option here is to have your .d.ts files in your dist folder.. e.g. `dist\globals\fileA.d.ts` and reference this in your sources, the compiler will rewrite them in the output to have the correct paths.

**Comment by evil-shrike** [comment]
For the record.
I abandoned both approaches (`--sourceRoot` and `--outDir`). In the end I just compile everything in-place (in staged folder /dist/dist) where I get *.js, *.ts, *.d.ts, *.js.map then just move *.ts and *.js.map into sibling folder structure /dist/src. So the release package contains:
```
├───dist
│     ├───lib/*.js + *.d.ts
│     └───modules/*.js + *.d.ts
├───src
│     ├───lib/*.ts + *.d.ts + *.js.map
│     └───modules/*.ts + *.d.ts + *.js.map
├───tsconfig.json
└───package.json
```

Inside *.js I have local sourcemap references (like `//# sourceMappingURL=file1.js.map`). So if the lib's users want to debug TS they'll need to copy *.ts and *.js.map from `/src` subtree into server's "wwwroot".
