### ISSUE TITLE
Quick fix to install @types/node on import * as fs from 'fs';  

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#23224]
https://github.com/Microsoft/vscode/issues/47321

**TypeScript Version:**  2.9.0-dev.20180404

**Search Terms:** 
- `@types/node`
- Quick fix
- typings install

**Code**

In a new folder

1. `npm init -y`
1. `tsc --init`
1. `touch index.ts`
1. `index.ts`:

      ```ts
      import * as fs from 'fs'; 
      ```

**Expected behavior:**
Error show. Quick fix can be used to install `@types/node` in project

**Actual behavior:**
Error shown: `cannot find module fs`

**Playground Link:**  

**Related Issues:**

**Comment by mhegazy** [comment]
We have a list of node builtin modules in https://github.com/Microsoft/TypeScript/blob/master/src/services/jsTyping.ts#L42, we should do something similar for the quickfix.
