### ISSUE TITLE
Suggest type definition install command using yarn when applicable

### ISSUE THREAD

**Issue by astorije** [microsoft/TypeScript#23231]
**TypeScript Version:**  2.8.1

**Search Terms:** yarn, Could not find a declaration, if it exists

Apologies if this was discussed before, I looked through issues and PRs, could not find anything.

When a `yarn.lock` file is present in the project directory, instead of recommending:

```
TS7016: Could not find a declaration file for module 'node-pkg'. '/[...]/node_modules/node-pkg/[...]' implicitly has an 'any' type.
Try `npm install @types/node-pkg` if it exists or add a new declaration (.d.ts) file containing `declare module 'node-pkg';`
```

it would be nice if the suggested command could make use of `yarn add` instead:

```
TS7016: Could not find a declaration file for module 'node-pkg'. '/[...]/node_modules/node-pkg/[...]' implicitly has an 'any' type.
Try `yarn add @types/node-pkg` if it exists or add a new declaration (.d.ts) file containing `declare module 'node-pkg';`
```

**Comment by mhegazy** [comment]
Related to https://github.com/Microsoft/TypeScript/issues/19997

**Comment by RyanCavanaugh** [comment]
This doesn't seem to be bothering anyone
