### ISSUE TITLE
Conditional types cast `never[] | {}` as `{}`

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#23243]
cc @ahejlsberg 

**TypeScript Version:**  2.7.0-dev.20180406

**Search Terms:** 

**Code**

```ts
type TEq<T, U> = [T] extends [U] ? [U] extends [T] ? true : false : false;
type a = TEq<{}, never[]>; // false
type b = TEq<{}, never[] | {}>;
type Eq<T, U> = T extends U ? U extends T ? true : false : false;
type c = Eq<{}, never[] | {}>;
```

**Expected behavior:**

b is `false`, c is `boolean`.

**Actual behavior:**

b and c is `true`.

**Playground Link:**  

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
`never[] | {}` is the same as `{}` as far as the type system is concerned.

**Comment by falsandtru** [comment]
`never[] | {}` will be surely distributed to `{}` and `never[]`

```ts
type Split<T> = T extends never ? never : [T];
type a = Split<never[] | {}>; // [{}] | [never[]]
```

So `never[]` and `{}` must be evaluated individually, and its result is correctly `false` and `true`. Type compatibility is misdirection here.

```ts
type SplitEq<T> = T extends never ? never : [T, Eq<{}, T>];
type b = SplitEq<never[] | {}>; // [{}, ture] | [never[], false]
```

`Eq<{}, never[] | {}>` must be resolved as follows under the spec. It returns `boolean` correctly.

```ts
type c
  = ({} extends {} ? {} extends {} ? true : false : false)
  | (never[] extends {} ? {} extends never[] ? true : false : false); // boolean
```

So `Eq<{}, never[] | {}>` is `boolean`.

**Comment by ahejlsberg** [comment]
Given `[T, U]` as `[{}, never[] | {}]`, the result of `T extends U` is `true`, and the result of `U extends T` is `true` (because *every* type except `null` and `undefined` extends `{}).

**Comment by falsandtru** [comment]
@ahejlsberg You mean `Eq<{}, never[] | {}>` won't be resolved as follows? Why?

```ts
type c
  = ({} extends {} ? {} extends {} ? true : false : false)
  | (never[] extends {} ? {} extends never[] ? true : false : false); // boolean
```

**Comment by falsandtru** [comment]
Not correct, WIP.

**Comment by falsandtru** [comment]
I realized my previous resolution is wrong. `Eq<{}, never[] | {}>` will be resolved as follows. This result is actually `true`. I need to distribute `U` at first.

```ts
type c = {} extends {} | never[] ? ({} extends {} ? true : false) | (never[] extends {} ? true : false) : false; // true
```
