### ISSUE TITLE
Proposal:Better Type inference

### ISSUE THREAD

**Issue by kgtkr** [Microsoft/TypeScript#23244]
# Background
Control syntax is statement in TypeScript.
Also, with the policy of TypeScript you can not express statement as expressions.
https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals
This proposal can solve this problem a little.

# Proposal
```ts
//f:()=>number
//Infer x as number
let x;
try{
  x=f();
}catch{
  x=0;
}
```

This is contrary to policy
```ts
let x=try{
  f();
}catch{
  0;
}
```

**Comment by Pajn** [comment]
This would require something like [Hindley Milner](https://en.wikipedia.org/wiki/Hindley%E2%80%93Milner_type_system). While the type inference is improving for each release, it will only get so far without taking this step.

I'm super excited if Typescript were to do it, it would improve the safety of the language a lot and at the same time let us write a lot let explicit type specifications. It would however be very breaking, so I think it would need to be handled just like `strictNullChecks`

**Comment by alexrock** [comment]
It is possible since version 2.1 with `--noImplicitAny`.

After the try block in the example, `x` is typed as `number`.

```ts
// @noImplicitAny: true
declare const f: () => number

let x

try {
    x = f()
} catch {
    x = 0
}

x // number
```

**Comment by kgtkr** [comment]
@alexrock I did not know the specification.Thank you
Close this issue.
