### ISSUE TITLE
[Feature Request] "inherits" type restriction for classes

### ISSUE THREAD

**Issue by billba** [Microsoft/TypeScript#23249]
I am building a library where functionality is added by inheritance from a single abstract base class with overridable default methods, and objects are created with a factory function. In JavaScript it's all pretty simple:
```ts
class A {
    constructor() {
    }

    foo(x) {
    }

    bar(x) {
    }
}

class B extends A {
    foo(x) {
        console.log(x.length);
    }
}

class C extends B {
    bar(x) {
        console.log(x.replace("hello", "goodbye cruel"));
    }
}

function create(t, x) {
    const obj = new t();
    obj.foo(x);
    obj.bar(x);
    return obj;
}

const c = create(C, "hello world"); // "11", "goodbye cruel world"
```
Layering in TypeScript, we can see that the argument to `foo` and `bar` are generic:
```ts
abstract class A<X> {
    foo(x: X) {
    }

    bar(x: X) {
    }
}

class B extends A<string> {
    foo(x: string) {
         console.log(x.length);
    }
}

class C extends B {
    bar(x: string) {
        console.log(x.replace("hello", "goodbye cruel"));
    }
}
```
But there is no way to correctly type the `create` function, because TypeScript has no first-class concept of a class, nor the relationships between classes. So there's no way to detect:
```ts 
const c = create(C, false); // where are the angry red squiggles?
```
I propose an `inherits` type restriction which exposes TypeScript's knowledge of class inheritance:
```ts
function create <T inherits A<X>, X> (t: T, x: X) {
    const obj = new t();
    obj.foo(x);
    obj.bar(x);
    return obj;
}

const c = create(C, false); // angry red squiggles ftw
```
`inherits` in action:
```ts
<C inherits B>          // true
<C inherits A<X>, X>    // true; X === string
<C inherits A<string>>  // true
<C inherits A>          // false, since A has no default type for X
<B inherits A<X>, X>    // true, X === string
<B inherits A<string>>  // true
<B inherits A<boolean>> // false
```
(I can also imagine that `inherits` could be used in conditional types with type inference, but off the top of my head I haven't come up with a good use case)

In case it's relevant, the way I would actually use this feature is a lot closer to:
```ts
abstract class A {
    protected constructor() {
    }

    static create <T inherits A<X>, X> (
        this: T,
        x: X
    ) {
        obj = new this();
        obj.foo(x);
        return obj;
    }
}

C.create("hello world");
```
But I wanted to keep things simpler for the example :-)

**Comment by SimonSchick** [comment]
Am I missing something or are you basically asking for `extends` which already exists?

**Comment by billba** [comment]
@SimonSchick `extends` applies to class instances. What I am proposing applies to classes themselves.

**Comment by kpdonn** [comment]
I think you just need to extend constructor signatures.

```ts
abstract class A<X> {
    foo(x: X) {
    }

    bar(x: X) {
    }
}

class B extends A<string> {
    foo(x: string) {
         console.log(x.length);
    }
}

class C extends B {
    bar(x: string) {
        console.log(x.replace("hello", "goodbye cruel"));
    }
}

function create <T extends new() => A<X>, X> (t: T, x: X) {
    const obj = new t();
    obj.foo(x);
    obj.bar(x);
    return obj;
}

const c = create(C, false); // angry red squiggles ftw
const c2 = create(C, "mystring"); // no error
```
[Playground link](https://www.typescriptlang.org/play/#src=abstract%20class%20A%3CX%3E%20%7B%0D%0A%20%20%20%20foo(x%3A%20X)%20%7B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20bar(x%3A%20X)%20%7B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aclass%20B%20extends%20A%3Cstring%3E%20%7B%0D%0A%20%20%20%20foo(x%3A%20string)%20%7B%0D%0A%20%20%20%20%20%20%20%20%20console.log(x.length)%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aclass%20C%20extends%20B%20%7B%0D%0A%20%20%20%20bar(x%3A%20string)%20%7B%0D%0A%20%20%20%20%20%20%20%20console.log(x.replace(%22hello%22%2C%20%22goodbye%20cruel%22))%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0A%0D%0Afunction%20create%20%3CT%20extends%20new()%20%3D%3E%20A%3CX%3E%2C%20X%3E%20(t%3A%20T%2C%20x%3A%20X)%20%7B%0D%0A%20%20%20%20const%20obj%20%3D%20new%20t()%3B%0D%0A%20%20%20%20obj.foo(x)%3B%0D%0A%20%20%20%20obj.bar(x)%3B%0D%0A%20%20%20%20return%20obj%3B%0D%0A%7D%0D%0A%0D%0Aconst%20c%20%3D%20create(C%2C%20false)%3B%20%2F%2F%20angry%20red%20squiggles%20ftw%0D%0Aconst%20c2%20%3D%20create(C%2C%20%22mystring%22)%3B%20%2F%2F%20no%20error)

**Comment by billba** [comment]
@kpdonn thank you and this does solve my immediate problem, but it does not solve the broader issue. For instance, if `A` has `static foobar = "foobar"` it would not be visible to `create`.

**Comment by andy-ms** [comment]
@billba You could always use `t: typeof A` for a covariant class. Another option is to define:
```ts
interface AStatic {
    new(): A;
    foobar(): number;
}
```
You may also be interested in #14600.

**Comment by billba** [comment]
`typeof A` works for simple classes but not for generic classes (e.g. `typeof A<X>`), which is what motivates this request).

Your proposed interface gives me `Cannot use 'new' with an expression whose type lacks a call or construct signature` on the attempt to do `new t()`.

**Comment by andy-ms** [comment]
But it does have a construct signature, `new(): A`, so if you have `t: AStatic` you should be able to call `new t()`.

**Comment by billba** [comment]
Of course you're right. Turns out that this works if you do:
```ts
new(): A;
```
but does not work if you do:
```ts
new: () => A;
```
which makes perfect sense when I think about it.

So it's great there's a path forward, but it's nuts that I need to define this interface when the class already exists - DRY.

**Comment by billba** [comment]
To update this proposal, then:

**First**, I'd like to be able to directly apply class-based type restrictions to an argument without having to whip up a separate interface that duplicates the signatures of all the statics (most notably the constructor) on that class, because that's DRY and thus prone to human error, which kind of goes against the whole point of TypeScript.

```ts
class Foo {
    static myStaticMethod() {
        return "yes";
    }
}

function doThing <T inherits Foo> (t: T) {
    console.log(t.myStaticMethod());
}
```

**Second**, it would sometimes be nice to define such an interface as long as the class could do a `static` version of `implements`, e.g.

```ts
interface myStatics {
    myStaticMethod(): string;
}

class Foo implements static myStatics {
    static myStaticMethod() {
        return "yes";
    }
}

class Bar implements static myStatics {
    static myStaticMethod(x: number) {   // angry red squiggles ftw
        return "no";
    }
}

function doThing <T extends myStatics> (t: T) {
    console.log(t.myStaticMethod());
}

doThing(Foo);
doThing(Bar);                     // angry red squiggles ftw
```

**Comment by billba** [comment]
Just to bring up another issue with the current behavior, check out this common factory pattern:
```ts
interface AStatic {
    new(): A;
}
abstract class A {
    foo() {
    }

    protected constructor() {
    }

    static create <T extends AStatic> (this: T)
    ) {
        obj = new this();
        obj.foo();
        return obj;
    }
}

class B extends A {
    foo() {
        console.log("it's alive!");
    }
}

B.create("hello world"); // angry red squiggles: "Cannot assign a 'protected' constructor type to a 'public' constructor type."
```
The constructor is protected because I want `create` to be the only way to create an instance of A and its children. But because it is protected, it doesn't match the signature, and we fail. I am forced to leave the constructor public, which opens up misbehavior from folks who don't realize they aren't supposed to call it.

**Comment by andy-ms** [comment]
I think the latest example would be #5863
