### ISSUE TITLE
[Feature Request] Make Typescript type system a formal proposal to ES 

### ISSUE THREAD

**Issue by michaeljota** [microsoft/TypeScript#23242]
**Search Terms:** 

- "ecmascript-types"

**Expected behavior:**

There is a long time proposal to include a typing system into ES, name [ecmascript-types](https://github.com/sirisian/ecmascript-types) (link to [es-proposals](https://esdiscuss.org/topic/es8-proposal-optional-static-typing))

The original proposal have several comments regarding the status of Typescript type system in that time, this was like 3 years ago. Typescript type system have evolve, however, there is still one key thing missing, [Variadic types](https://github.com/Microsoft/TypeScript/issues/5453). It have been on the roadmap for a year I think. I know this is too big, and too complex, still I think Typescript team can help into that proposal, or create a new one entirely new. 

If you read the current proposal, there are a lot of sintaxis taken from Typescript, and a many issues where resolved with current Typescript implementations.

I would like to say a few things about this. I would like to see JavaScript with a proper type system. But I don't see this proposal harming Typescript, if anything, then Typescript would be a stricter super set of JavaScript, and would help the ES type system, adding new features before they could be considered into the language. 

**Actual behavior:**

There is no type system for ES

**Related Issues:**

[ecmascript-types](https://github.com/sirisian/ecmascript-types)

**Comment by RyanCavanaugh** [comment]
We're looking into other avenues here but I don't think static typing proper is ever coming to JS
