### ISSUE TITLE
Targeting es3 or es5 produces functions with incorrect `function.length` when using initializers

### ISSUE THREAD

**Issue by jwalton** [microsoft/TypeScript#23251]
**TypeScript Version:**  2.8.1

**Search Terms:**  function.length

**Code**

```ts
function fn(a,b,c=4) {}
console.log(fn.length);
```

**Expected behavior:**

[ECMAScript 2015 19.2.4.1](https://www.ecma-international.org/ecma-262/6.0/#sec-function-instances-length) states:

> The value of the length property is an integer that indicates the typical number of arguments expected by the function.

And [14.1.6](https://www.ecma-international.org/ecma-262/6.0/#sec-function-definitions-static-semantics-expectedargumentcount) states:

> The ExpectedArgumentCount of a FormalParameterList is the number of FormalParameters to the left of either the rest parameter or the first FormalParameter with an Initializer. A FormalParameter without an initializer is allowed after the first parameter with an initializer but such parameters are considered to be optional with undefined as their default value.

Since our function has 2 parameters to the left of the first parameter with an initializer, we expect `fn.length` to be 2.

**Actual behavior:**

(Using node 8.11.1)

```sh
$ tsc -t es3 test.ts && node test.js
3
$ tsc -t es5 test.ts && node test.js
3
$ tsc -t es6 test.ts && node test.js
2
```

Note that this program behaves differently based on which version of ECMAScript you are targeting!

Looking at the compiled output, it's easy to see the problem:

```js
// target es3
function fn(a, b, c) {
    if (c === void 0) { c = 4; }
}
console.log(fn.length);
```

```js
// target es6
function fn(a, b, c = 4) { }
console.log(fn.length);
```

Since the ES6 version keeps the initializer, the function length is correct in this case.  Compare the es3 version from tsc with the [output produced by babel](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=GYVwdgxgLglg9mABMMAKAhgGgEaYgXgBYBKRAbwF8AoCBAZzgBsBTAOkbgHNUV3mxOUABbEA3EA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=6.26.0&envVersion=), which gets this correct:

```js
// Compiled by babel
function fn(a, b) {
  var c = arguments.length > 2 && arguments[2] !== undefined ? arguments[2] : 4;
}
console.log(fn.length);
```

**Playground Link:** [link](https://www.typescriptlang.org/play/#src=function%20fn(a%2Cb%2Cc%3D4)%20%7B%7D%0D%0Aconsole.log(fn.length)%3B)

**Related Issues:**

**Comment by dbellizzi** [comment]
I came upon this issue while trying to use lodash `curry` and `partial` which end up returning a partially applied function when using typescript generated code in ES5 mode instead of executing the function with the default parameter.  This is due to the difference in function.length of the function passed to curry.

**Comment by RyanCavanaugh** [comment]
Ouch. Using the `arguments` array instead of a formal parameter usually has bad perf characteristics, and this would be a potential runtime breaking change for existing TypeScript codebases.

@DanielRosenwasser thoughts on actually fixing this?

**Comment by jwalton** [comment]
If you're worried about breaking changes in existing code, I'd point out that TS 3.x is right around the corner.  :)

**Comment by bywo** [comment]
Hey Typescript team, are you open to fixing this? I ran into this issue as well.

**Comment by RyanCavanaugh** [comment]
This seems too niche to bother trying to do anything about at this point. Inspecting `function#length` is a weird thing to do in the first place, the emit would be gnarly, and most people are on ES6+

**Comment by jwalton** [comment]
Yeah, this is maybe less important now than it was back when it was raised. :) Thanks!
