### ISSUE TITLE
The spelling quick fix for enums does not escape spaces

### ISSUE THREAD

**Issue by AlCalzone** [Microsoft/TypeScript#23256]
**TypeScript Version:**  2.9.0-dev.20180407

**Search Terms:** spelling quick fix space

**Code**
```ts
enum Foo {
    "Bar Baz" = 1,
}

declare function bar(foo: Foo): void;

bar(Foo.BarBaz); // error TS2551: Property 'BarBaz' does not exist on type 'typeof Foo'. Did you mean 'Bar Baz'?
```
The suggested quick fix (correctly) wants to change the spelling to `"Bar Baz"`.

**Expected behavior:**
```ts
bar(Foo["Bar Baz"]);
```
**Actual behavior:**
```ts
bar(Foo.Bar Baz);
```

**Comment by andy-ms** [comment]
This is working as expected for me with that TypeScript version, are you sure that's the version your editor is using? I verified that the bug existed in 2.7, but not in 2.9.0-dev.20180407 .

**Comment by AlCalzone** [comment]
You're right, somehow VSCode didn't pick up the correct version. The bug is present in 2.8.1, but not in 2.9.0-dev.20180409.
