### ISSUE TITLE
Intellisense stops working in VS Code 1.22 with TypeScript 2.8.1 on Ubuntu

### ISSUE THREAD

**Issue by jwulf** [Microsoft/TypeScript#23259]
**TypeScript Version:**  2.8.1

**Search Terms:** 
typesMap.json doesn't exist
intellisense broken
tsserver high CPU

**Code**
With VS Code 1.22, TypeScript 2.8.1, on Ubuntu Arty.

Intellisense breaks in my project. Installing TypeScript 2.7.2 in the project and telling VS Code to use that works.

Here's what tsserver.log contains when using the 2.8.1 included with VSCode 1.22:

```
Info 4    [9:48:28.442] Provided types map file "/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js/../typesMap.json" doesn't exist
```

**Comment by j-oliveras** [comment]
Duplicated or related to #23255?

**Comment by mhegazy** [comment]
Can you share your tsserver log please.

**Comment by mhegazy** [comment]
closing for now. please reopen if you have more information to share.
