### ISSUE TITLE
Import quickfix for "export const MyClass=class{}" broken

### ISSUE THREAD

**Issue by neoncom** [Microsoft/TypeScript#23252]
**TypeScript Version:**  2.8.1, VSCODE 1.22.1

**Search Terms:** 

**Code**

```ts
// file1

export const MyClass = class {}

// file2

const variable:MyClass;
```

if I mouseover MyClass in file2 and do CTRL-. (dot), nothing happens

however if i change file1 into

`export class MyClass {}`

it works.

so the problem is that the import quick fix does not recognize MyClass as a type in the first case 

i believe strongly  it worked in TS 2.7.1, hower does not in 2.8.1

**Expected behavior:**  VS suggests import on CTRL-. (dot)

**Actual behavior:** VS does not react on CTRL-. (dot)

**Playground Link:**  not possible, cannot import files there

**Related Issues:**

**Comment by andy-ms** [comment]
The following code is invalid:
```ts
const MyClass = class {};
declare const variable: MyClass;
```
Because when you use `const MyClass = class {};`, it has only value meaning and not type meaning. In order to use a class as a type it has to be declared using `class MyClass {}` and not `const MyClass = class {}`.

**Comment by andy-ms** [comment]
It's pretty hard to provide a type based on the result of a function -- the function won't evaluated until runtime, but we need types to be available at compile time. You could define an interface for what you expect it to return, and then have `export const MyComponent: { new(): MyInterface } = ...`.

**Comment by neoncom** [comment]
Hm, I don't understand. The type does exists. If a mouseover the const variable it shows me the type of the result.

The problem I and other users have is just that the import quick fix is broken in 2.8.1. I always have to import manually. And also not being able to use the class variable in a type position is just conceptually wrong and should be fixed, but I could care less about that right now :)

**Comment by andy-ms** [comment]
> If a mouseover the const variable it shows me the type of the result.

That shows you that `MyComponent` *has* a type, not that it *is* a type. It's impossible in general to make every class that exists at runtime be a type, unless we ran the program at compile time.
This isn't an import quickfix bug, because it's intentionally avoiding importing something that will result in a compile error.

**Comment by neoncom** [comment]
OK I understand now. Forget about variable type positions :)

But what about importing a react component in a react node position? Somehow the compiler can validate it when I use it at compile time perfectly, no problem. Then it should be able to quickfix import it too? Either way enabling the quickfix import here would really really be needed.

I am very sure it worked in 2.7.1. I will check that again though.

**Comment by andy-ms** [comment]
Can you find an example where the thing you want to import would not cause a compile error if imported?

**Comment by neoncom** [comment]
Sure.

a.tsx
```
import * as React from 'react';
import { ComponentB } from './b';

class ComponentA extends React.PureComponent {
    render() {
        return <ComponentB ownProperty={42} />
    }
}
```

b.tsx
```
import { MapStateToProps, connect, MapDispatchToProps } from "react-redux";
import * as React from 'react';

interface DummyReduxState {
    readonly dummyStateData: string;
}

export interface OwnProps {
    readonly ownProperty: number;
}

interface StateProps {
    readonly stateProperty: string;
}

interface DispatchProps {
    dispatchFunction(): void;
}

interface AllProps extends OwnProps, StateProps, DispatchProps {
}

const mapStateToProps: MapStateToProps<StateProps, OwnProps, DummyReduxState> = (state) => {
    return {
        stateProperty: state.dummyStateData
    }
}

const mapDispatchToProps: MapDispatchToProps<DispatchProps, OwnProps> = (dispatch) => {
    return {
        dispatchFunction() {
            console.log(42);
        }
    };
}

export const ComponentB = connect(mapStateToProps, mapDispatchToProps)(class extends React.Component<AllProps>{

    render() {
        return <div>Working...</div>
    }
})
```
That code has zero compile errors.

You can see that the inner class of ComponentB has many properties (=> AllProps interface). But that class is wrapped by react redux to form ComponentB.

ComponentB, as a result, has only 1 (!) possible prop, "ownProperty".

So when using ComponentB, it correct only allows that property "ownProperty" on the component (see file a.tsx).

The react-redux declaration file does an awesome job of subtracting the correct properties from the inner class to make that happen.

It's just that auto import doesn't work :(

**Comment by neoncom** [comment]
Proof it worked on 2.7.1. I wasn't wrong :)

![clipboard01](https://user-images.githubusercontent.com/35164488/38538982-734f1a84-3c96-11e8-88da-fe28112103b1.png)

**Comment by neoncom** [comment]
Another bug, related, but not the same (TS 2.8.1):

file a.tsx (Can quickfix first, but not second case)
![filea](https://user-images.githubusercontent.com/35164488/38579129-5d54db68-3d06-11e8-9b00-f1095d78893e.png)

file b.tsx
![fileb](https://user-images.githubusercontent.com/35164488/38579153-674c92fa-3d06-11e8-81e3-2ece9f513a0f.png)

**Comment by andy-ms** [comment]
@neoncom I tested the example from 3 posts up and it works today with `typescript@2.9.0-dev.20180410`. In that example you are using `ComponentB` in a value position, not a type position. If I remove `import { ComponentB } from './b';` click on `<ComponentB` I correctly get a codefix to add the import back.
