### ISSUE TITLE
Better playground

### ISSUE THREAD

**Issue by agentcooper** [microsoft/TypeScript#23266]
I've made a better playground for TypeScript: https://agentcooper.github.io/typescript-play/.

Differences from the original one:
- All strict compiler options turned on by default
- More available compiler options
- Ability to switch TypeScript version
- More space for code
- More examples
- Quicker sharing, URL updates as you type
- Shorter sharing URLs
- Open source :-)

I hope this can be helpful to other users.

**Comment by karlhorky** [comment]
Would the TypeScript team be open to making this into the official editor? It would help with a lot of these points, as well as other issues with the official Playground, such as https://github.com/microsoft/TypeScript/issues/32058

**Comment by orta** [comment]
Your timing really couldn't have been better actually, I got in touch with @agentcooper a weekend or two ago about getthing this up and running, and now this version is the default on https://www.typescriptlang.org/play/

**Comment by dragomirtitian** [comment]
@orta  Any chance to collapse the JS output ? I honestly don't usually care about the JS output. I test out that TS code snippets compile or run the code to see output. On the desktop where I have enough space it's not an issue but from my phone it's an issue.

**Comment by orta** [comment]
Yeah, eventually on my TODO, happy to take PRs doing to it to https://github.com/orta/typescript-play/tree/old-site-integration 

But I'll be starting work on the new TS website after this so probably won't got back to features on the playground until it's living on the new site

**Comment by karlhorky** [comment]
Really cool, looks great!

**Comment by karlhorky** [comment]
Really cool, looks great! 💯 Thanks!
