### ISSUE TITLE
Proposal: Add access modifiers on generic class parameters

### ISSUE THREAD

**Issue by EliSnow** [Microsoft/TypeScript#23267]
I have the following class:

```ts
class DeferredPromise<T = void, T2 = T> extends Promise<T> {
  public resolve: (value?: T2 | PromiseLike<T2>) => void;
  public reject: (reason?: any) => void;

  constructor(
    cb?: (resolve: (value?: T | PromiseLike<T>) => void, reject: (reason?: any) => void) => void
  ) {
    let resolve: this["resolve"] | undefined;
    let reject: this["reject"] | undefined;
    super((res, rej) => {
      if (cb) {
        cb(res, rej);
      }
      resolve = <any> res;
      reject = rej;
    });
    this.resolve = resolve!;
    this.reject = reject!;
  }

  public then <TResult1 = T, TResult2 = never> (
    onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null,
    onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null
  ) {
    const ret = <DeferredPromise<TResult1, T2>> <any> super.then(onfulfilled, onrejected);
    ret.resolve = this.resolve;
    ret.reject = this.reject;
    return ret;
  }
}
```

Essentially this creates a `Promise` which you can be `resolve` or `reject` outside of the constructor's callback function. Additionally any `DeferredPromise`s created by calling `then`/`catch` will inherit the `resolve` and `reject` methods from the base `DeferredPromise`.

I would like to be able to make the `T2` generic private so only the cast within `then` the method would work, but outside the class that parameter could not be specified.

**Example**

```ts
class DeferredPromise<T = void, private T2 = T> extends Promise<T> {
  ...

  public then <TResult1 = T, TResult2 = never> (
    onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null,
    onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null
  ) {
    // This would work
    const ret = <DeferredPromise<TResult1, T2>> <any> super.then(onfulfilled, onrejected);
    ...
  }
}

// Error: Generic parameter T2 is private
const d = new DeferredPromise<string, number>();
```

The `public`, `protected`, and `private` modifiers would work the same way they work for classes' properties with the default being implicitly `public`. `protected` and `private` would need to have a default explicitly provided or would default to `void`.

**Alternative**

As an alternative I could create a subclass extending `DeferredPromise` which only reveals the first generic parameter but that is undesirable because I'd be affecting run-time code in order to achieve a compile-time ends.

**Comment by andy-ms** [comment]
You could always make the constructor private:
```ts
static create<T>(cb?: (resolve: (value?: T | PromiseLike<T>) => void, reject: (reason?: any) => void) => void): DeferredPromise<T, T> {
return new DeferredPromise<T, T>(cb);
}

private constructor(cb?: (resolve: (value?: T | PromiseLike<T>) => void, reject: (reason?: any) => void) => void) { ... }
```

**Comment by EliSnow** [comment]
A private constructor with a static factory method could work, but just like creating a derived class, then I'm changing my run-time code (not to mention my API) in order to appease the type checker.

In answer to your question, once you create a `Promise` sub-class, when you call `super.then(...)` you get an instance of your derived class. In the case of `DeferredPromise` it wouldn't really make sense to be able to call `resolve()` directly on a derived promise as you'd only expect it to resolve when the base promise is resolved. Now, I could have `then` return a vanilla `Promise` then I'd have to manually handle the storing and resolving of all derived promises--but in my particular use case I want to store the derived promise but would like to resolve the original promise without storing an additional reference to it.

**Comment by mhegazy** [comment]
I am not sure what a private generic type parameter even mean in a structural type system..

You can achieve this by having an implementation class, and a public interface that hides the constructor signature you are using. you only export the public interface, and you keep your class implementation the way you like it.

**Comment by EliSnow** [comment]
@mhegazy, can you give me an example as it relates to this case? I'm having a hard time picturing what you mean.

**Comment by mhegazy** [comment]
is any type with the same structure assignable to your new type with a private generic type parameter? what if the type parameter is never witnessed in any property? what if it is? is it assignable to `any`? why and why not? can that type be used outside, can i write `typeof C["somethignOFTypeT2"]` outside the class?

**Comment by EliSnow** [comment]
> is any type with the same structure assignable to your new type with a private generic type parameter?

Good question. If yes, then the idea behind the private generic type parameter would only apply to the constructor. If no, you would not be able to cast to a subtype. So, I think yes would make the most sense.

> what if the type parameter is never witnessed in any property? what if it is?

It seems to me a generic type parameter would have three ways it could meaningfully be used: As a property, as a parameter in a method, or in the return type of a method. Maybe I'm missing something but if it's not used in one of those ways I'm not sure what it's purpose would be.

> is it assignable to any? why and why not?

Do you mean like `const d: any = new DeferredPromise<void>().then(() => "foo");`?

If that's what you're referring to, I'm not sure why not. Everything is assignable to `any`, no?

> can that type be used outside, can i write typeof C["somethignOFTypeT2"] outside the class?

Yes, because the private generic type parameter is only effectual for the constructor.


I think I figured out the interface solution you were talking about:
```ts
interface DeferredPromiseThen<T, T2> extends Promise<T> {
    resolve: (value?: T2 | PromiseLike<T2>) => void;
    reject: (reason?: any) => void;

    then <TResult1 = T, TResult2 = never>(
        onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null,
        onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null
    ): DeferredPromiseThen<TResult1, T2>;
}

class DeferredPromise<T = void> extends Promise<T> implements DeferredPromiseThen<T, T> {
  public resolve: (value?: T | PromiseLike<T>) => void;
  public reject: (reason?: any) => void;

  constructor (
    cb?: (resolve: (value?: T | PromiseLike<T>) => void, reject: (reason?: any) => void) => void
  ) {
    let resolve: this["resolve"] | undefined;
    let reject: this["reject"] | undefined;
    super((res, rej) => {
      if (cb) {
        cb(res, rej);
      }
      resolve = <any> res;
      reject = rej;
    });
    this.resolve = resolve!;
    this.reject = reject!;
  }

  public then <TResult1 = T, TResult2 = never> (
    onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null,
    onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null
  ) {
    const ret = <DeferredPromiseThen<TResult1, T>> <any> super.then(onfulfilled, onrejected);
    ret.resolve = this.resolve;
    ret.reject = this.reject;
    return ret;
  }
}
```

Thanks for helping me think this through @mhegazy!

Closing.
