### ISSUE TITLE
Suggestion: library files should expose interfaces in namespace

### ISSUE THREAD

**Issue by dawidgarus** [Microsoft/TypeScript#23265]
Interfaces defined lib.d.ts files are global. This creates a lot of namespace pollution, which is especially annoying since they have very common names, for example: `Account` in lib.dom.d.ts. If one defines his own `Account` interface, it's easy to forget to import it and `Account` from lib.dom.d.ts will be used instead. This kind of errors are hard to spot, sometimes they don't create any errors at all or create confusing errors like "Account cannot be assigned to Account".
I get why classes and variables should be declared as global in lib.d.ts, but there really is no reason why types and interfaces should be so. IMHO the best options would be put them in some namespace, for example: `lib.dom.Account`

**Comment by RyanCavanaugh** [comment]
We don't have a "too late" tag, but it's too late to break ~every TypeScript program in existence for cleanup purposes. `--noLib` is available if you want to supply a custom organized version of lib.d.ts

**Comment by dawidgarus** [comment]
It's possible to do it without breaking changes. For some time, lib.d.ts could export global interfaces (marked as deprecated) and a namespace. `legacyLib` option could be introduced - if set to `false`, global interfaces should not be available.
