### ISSUE TITLE
Interface 'AbstractExtendedWebDriver' cannot simultaneously extend types 'AbstractWebDriver' and 'ExtendedWebDriver'.

### ISSUE THREAD

**Issue by Ngugi1** [Microsoft/TypeScript#23261]
[at-loader] ./node_modules/protractor/built/browser.d.ts:15:18
    TS2320: Interface 'AbstractExtendedWebDriver' cannot simultaneously extend types 'AbstractWebDriver' and 'ExtendedWebDriver'.
  Named property 'actions' of types 'AbstractWebDriver' and 'ExtendedWebDriver' are not identical.

I am experiencing this issue when I try torun my angular project.

**Comment by jptinsman** [comment]
What was the issue @Ngugi1 ? I noticed you closed it. I am running into the same issue when trying to upgrade a large project from Angular 2 Universal to Angular 5 Universal
