### ISSUE TITLE
Add no-compile option to tsconfig

### ISSUE THREAD

**Issue by ivogabe** [Microsoft/TypeScript#2326]
Some users want to use the built-in compilation of their IDE, but some want to use grunt or gulp. If you want to use grunt or gulp for compilation, you need to disable compilation in your IDE. Since a big team can use multiple IDEs, I think this should be implemented in `tsconfig.json`.

Suggestion: Add a new option to `tsconfig.json` to disable the compilation in the IDE ("compile on save"), which defaults to false.

Example:
```json
{
    "disableCompileOnSave": true,
    "compilerOptions": {
        "module": "commonjs",
        "noImplicitAny": true
    },
    "files": [
        "foo.ts",
        "bar.ts"
    ]
}
```

If an IDE finds a config file with this option, it shouldn't compile the project, but it should give auto completions, type errors, etcetera. If a build tool sees this option it should ignore it, because you use an IDE always for writing, sometimes for building and you use a build system always for building.

**Comment by danquirk** [comment]
You mean full build not compile on save right? Compile on save is already toggleable in VS and using (or not using) --watch on the command line. It sounds like you want something similar to this https://github.com/Microsoft/TypeScript/issues/2294 but provided in tsconfig?

**Comment by ivogabe** [comment]
Yes, that's what I meant. It should be something like `disableIdeCompilation` or `disableCompilation` then.

**Comment by mhegazy** [comment]
Your IDE build is triggered by the msbuild targets in your project file. if you want to stop that, open your project file, and comment out the reference to Microsoft.TypeScript.Targets, and no build will occur. no need for a different file here :)

**Comment by ivogabe** [comment]
@mhegazy Unless someone else in your team uses another editor, like Atom. You can disable it in Atom, but defining it once in tsconfig would be better.

**Comment by ivogabe** [comment]
Related: TypeStrong/atom-typescript#175 and ivogabe/gulp-typescript#65

**Comment by johnnyreilly** [comment]
As I understand it this switch would support those users who are using Gulp or Grunt to do their TypeScript compilation and they don't want Visual Studio / atom-typescript / sublime etc to get involved in doing a build.

As @mhegazy says we can already cater for this in Visual Studio by tweaking the project file.

As regards atom-typescript etc I understand there's a [an agreement that we can extend the `tsconfig.json` file](https://github.com/TypeStrong/atom-typescript/blob/master/docs/tsconfig.md) already (as long as we don't conflict with existing settings.

That being the case I'm not sure this needs an **official** `tsconfig.json` flag (although I guess it'd be nicer?)  Is it enough if we just extend it unofficially?

@basarat - do you have a view on this?

**Comment by ivogabe** [comment]
@johnnyreilly That's a good summary. There is a big advantage for this to be official, since if it's official, all editors should support it. That makes it easier for these users: they can configure this option once and it will be disabled in all editors. That's very useful if you have a big team or an open source project.

**Comment by danquirk** [comment]
I'm inclined to agree. If enough people want this in enough different scenarios then there's value in just standardizing the name of the flag rather than having some people use ```noCompile``` and someone else use ```skipCompile``` and someone else use yet another option.

**Comment by basarat** [comment]
I recommend `compileOnSave` (default `true`). Atom-typescript already supports this as a package option, that you can even configure per project : https://github.com/TypeStrong/atom-typescript/blob/master/docs/packages.md#manage-your-projects 

:+1: on moving this into tsconfig.json. I'll do that. 

PS: Having a negative like `disable` in a variable name is a bad idea. Double negation is not easy for the human brain. `"disableCompileOnSave": false,`. I've done this myself too and sometimes it does make sense, so no judgement :heart:

**Comment by basarat** [comment]
https://github.com/TypeStrong/atom-typescript/blob/master/docs/tsconfig.md#compileonsave

**Comment by ivogabe** [comment]
@basarat I chose for `disable` since it can then default to false, and undefined is false-ish. But I can also life without `disable`. As pointed out by @danquirk compileOnSave might not be the right name for it, since that would mean that Visual Studio should only disable automatic compilation, not the compile button. I'd call it something like `ideCompilation`, or maybe better: `externalCompilation`, which defaults to false and doesn't have a double negotiation. `externalCompilation: true` would mean you're using Gulp, Grunt, Jake etcetera.

**Comment by basarat** [comment]
> @danquirk compileOnSave might not be the right name for it, since that would mean that Visual Studio should only disable automatic compilation, not the compile button

I specifically want to disable "compile" *OnSave*. For Atom-TypeScript build is an explicit option triggered by the user. If they don't trigger it, it doesn't happen. Compile on save is what happened as a side effect of saving and so it needed configuration. 

I guess you want to disable *all* IDE compile. That seems like a Visual Studio / exclude from MSBuild problem, not related to other other IDEs. At the very least don't see it as an option we need to read in Atom-TypeScript.

**Comment by basarat** [comment]
@ivogabe perhaps `compileOnBuild` for visual studio ?

**Comment by ivogabe** [comment]
@basarat Do you mean adding two different options to tsconfig.json? I think it would be better to make these two one, especially because many (all?) users want to enable them both, or disable them both. I think disabling a build option hidden in a submenu isn't a problem, since setting this option means you shouldn't compile TypeScript from an editor since a build system should do that.

**Comment by basarat** [comment]
> I think it would be better to make these two one, especially because many (all?) users want to enable them both

I agree. `ideBuild`? : disables compile on save and compile on build.

**Comment by nycdotnet** [comment]
I think `ideBuild`, `editorBuild`, or even `vsBuild` is a fine option name with the default being `true` for IDEs or Visual Studio in particular.  I wrote up "some" (probably too many) thoughts on this here https://github.com/Microsoft/TypeScript/issues/2294#issuecomment-86068211 , but the bottom line is that the ability to disable Visual Studio's TypeScript build functionality while retaining the ability to use the TypeScript build properties UI would be really useful.

**Comment by basarat** [comment]
I previously went with `compileOnSave` at root. https://github.com/TypeStrong/atom-typescript/blob/master/docs/tsconfig.md#compileonsave

After discussion with @Zoltu here https://github.com/TypeStrong/atom-typescript/issues/324 I'll be moving to :

```json
"ide": {
    "compileOnSave" : boolean
}
```

Please leave a comment if you disagree. Note that in my opinion `build` and `onsave` are different events.

**Comment by basarat** [comment]
After letting it sit in my brain I dislike my proposal. Perhaps for the user the option is important for gulp to read. Really it belongs in something like "atom" key and then the user should lookup what options are supported by their ide / build tool. 

At the moment I'll leave the options I have as they are. If I do something wonky (tsconfig for me has been fairly stable) I'll do it under atom from this point on.

**Comment by mhegazy** [comment]
Does not seem that there is an action item here per se. switching it to discussion from suggestion.

**Comment by paulvanbrenk** [comment]
For VS 2015 we have included the TypeScriptCompileBlocked msbuild element, this will block tsc from being invoked during a build.

**Comment by gyzerok** [comment]
Any progress on this? I'm using Atom and bundle my code with webpack.

**Comment by nycdotnet** [comment]
@gyzerok Atom-typescript has an unofficial extension to tsconfig.json for this: `compileOnSave`.

https://github.com/TypeStrong/atom-typescript/blob/master/docs/tsconfig.md#compileonsave

**Comment by gyzerok** [comment]
@nycdotnet thanks bro!

**Comment by johnnyreilly** [comment]
Hi @mhegazy, @danquirk,

I've recently switched to the workflow of writing TypeScript and emitting es6 whilst using Babel to perform the transpilation to es5. I do this using Webpack which runs in watch mode, compiling as I save files and rerunning my tests continually in an ncrunchy style.

In this context the editor/IDE triggering compilation makes no sense as it creates .js files which aren't used and clutter up the source directory.

Since I'm using atom-typescript I can rely on the `compileOnSave` flag to disable this which is fantastic. However, as @ivogabe has alluded to, because this is non standard it cannot be relied upon if another developer is working on the code and wants to use vscode / sublime / visual studio etc.  It won't prevent them from working on the project but it will mean they will either have to ignore the "clutter files" or they will have to find their own way to disable the build.

I think there would be some value in standardising this in the `tsconfig.json`. The name of the flag doesn't have to be `compileOnSave`  - it could be something else. But this would reduce friction as developers wish to use different editors / IDEs on a project and would minimise "editor lock-in".

What are your thoughts?

**Comment by mhegazy** [comment]
`compileOnSave` seems like a fine property name to standardize on. we are currently looking into #5287, and we will need a way to make this honored in VS. so +1 for `compileOnSave`.

**Comment by paulvanbrenk** [comment]
Sounds like something that would be more appropriate in something like `.editorconfig`? `tsconfig.json` is primarily designed to drive the compiler and compilation context... just my $0.02

**Comment by thomas-darling** [comment]
Just a quick comment on this - it looks like much of the conversation here is centered around enabling/disabling compile-on-save for all typescript in a project - i.e. on the use case where only one tsconfig.json exists in the project. However, that's not the only use case for this:

In my case, I have more than one tsconfig.json within a single Visual Studio project, with one specifying compile options for the app code, and another for compiling some custom tslint rules.
To avoid an overly complicated build setup, I would strongly prefer to only use gulp to compile my app code, while just relying on compile-on-save for other things, such as custom tslint rules or gulp tasks.

I just wanted to point out this use case, so it doesn't get lost in the conversation :-)

**Comment by mhegazy** [comment]
After discussing this with @paulvanbrenk, VS should honor the `compileOnSave` property in tsconfig if present.

**Comment by johnnyreilly** [comment]
Yay!

**Comment by paulvanbrenk** [comment]
`compileOnSave` should be in for 1.8 final, I checked it in.

**Comment by johnnyreilly** [comment]
I've been experiencing difficulties with it... See https://github.com/Microsoft/TypeScript/issues/6782

**Comment by netdragonboberb** [comment]
See also https://shauntm.com/notes/entries/231

**Comment by ofirgeller** [comment]
How about compile on save for just some files? my files should not be compiled on save as I use gulp to do that. but I actually write my gulpfile as a typescript file and I need that file to compile on save.

**Comment by mhegazy** [comment]
> How about compile on save for just some files? my files should not be compiled on save as I use gulp to do that. but I actually write my gulpfile as a typescript file and I need that file to compile on save.

have to tsconfig.json files, one at the root for your gulpFile, and one in a source directory for your sources. the top one allows compile on save, the other one does not.

regardless, i do not think you can rely on compile on save for your gulp file, as you want it to run on a CI server for instance that does not have an editor. consider using something like [`ts-node`](https://github.com/TypeStrong/ts-node) instead.
