### ISSUE TITLE
Suggestion: Organise Imports should sort by import name instead path

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#23279]
_From @PooperPig on April 8, 2018 22:16_

- VSCode Version: 1.22.1
- OS Version: Windows 10

Steps to Reproduce:

1. Press Alt-Shift-O
Does this issue occur when all extensions are disabled?: Yes

More of a suggestion than a bug...

When organising Imports, I don't really care where about the location of the import, it would be more sensible to sort by the names; When I'm looking through Imports, I'm usually looking for (for example) 'Constants' and not 'cs/editor/common/core.'...

When importing '* as zzz' it would be sensible to sort by the 'zzz' rather than the '*' or path imported from.

e.g. in the example shown in the release notes, the sorted results would be better (IMHO) as

```
{ Constants }
{ FontInfo }
* as nls
* as platform
{ ScrollbarVisibility }
{ USUAL_WORD_SEPARATORS }
* as zoom
```
as this makes it easier to find an import and makes more sense than using the location of a particular file as the sort order.

Also, the option to remove unused imports should maybe be an option rather than unavoidable behaviour?

_Copied from original issue: Microsoft/vscode#47447_

**Comment by mjbvz** [comment]
_From @vscodebot[bot] on April 8, 2018 22:16_

(Experimental duplicate detection)
Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
- [TypeScript and JavaScript organize imports  (#45108)](https://www.github.com/Microsoft/vscode/issues/45108)

**Comment by mjbvz** [comment]
Moving upstream to get more feedback.

I think the current behavior is the correct default. We can see if there is interest in possibly adding an option to change the sorting order

**Comment by indefinitelee** [comment]
Personally I'd prefer if the sort import and remove unused import behaviors were separated. But if that is not possible I think the order preferred by @PooperPig is best. 

Though it does not deal with the issue of where multiple named imports would be sorted, e.g.
`import {  RaisedButton, MenuItem, Dialog, Snackbar } from 'material-ui';`
I guess would be sorted under D, which I could live with. 

Lastly, an option to exempt a specific import from sorting would be nice. For example, I like having 
`import React, { Component } from 'react';` as the first in my import list, though maybe this can be accomplished by import groups?

**Comment by mjbvz** [comment]
Closing due to lack of further community interest/feedback over the past two years or so
