### ISSUE TITLE
noImplicitReturns control flow errors with explicit type guard checks

### ISSUE THREAD

**Issue by tomrav** [Microsoft/TypeScript#23271]
**TypeScript Version:**  2.8.1 & 2.9.0-dev.20180409

**Search Terms:** noImplicitReturns throw type guard 

**Code**

```ts
interface A { type: 'A' }
interface B { type: 'B' }

function isA(val: any): val is A { return val && val.type === 'A'}
function isB(val: any): val is B { return val && val.type === 'B'}

function getAOrThrow(val: A | B): A {
    if (isA(val)) { 
        return val; // val inferred to A
    } else if (isB(val)){ // val inferred to B
        throw new Error(); 
    }
    val // type inferred to never
}
```

**Expected behavior:**
Type check should pass without error.

**Actual behavior:**
Happens only with `noImplicitReturns` turned on.
`getAOrThrow` errors on its return value with `Function lacks ending return statement and return type does not include 'undefined'.`.
If I remove the second type guard call (`isB`) and just leave it as a catch-all else, there is no error.

**Playground Link:**  
Cannot reproduce in playground due to `noImplicitReturns` being turned off.

**Related Issues:**
Couldn't find any.

**Comment by tomrav** [comment]
Seems similar to #23281

**Comment by sledorze** [comment]
@tomrav Here's a playground with you example and 'noImplicitReturns' activated (in the 'Options' menu)

http://www.typescriptlang.org/play/#src=interface%20A%20%7B%20type%3A%20'A'%20%7D%0D%0Ainterface%20B%20%7B%20type%3A%20'B'%20%7D%0D%0A%0D%0Afunction%20isA(val%3A%20any)%3A%20val%20is%20A%20%7B%20return%20val%20%26%26%20val.type%20%3D%3D%3D%20'A'%7D%0D%0Afunction%20isB(val%3A%20any)%3A%20val%20is%20B%20%7B%20return%20val%20%26%26%20val.type%20%3D%3D%3D%20'B'%7D%0D%0A%0D%0Afunction%20getAOrThrow(val%3A%20A%20%7C%20B)%3A%20A%20%7B%0D%0A%20%20%20%20if%20(isA(val))%20%7B%20%0D%0A%20%20%20%20%20%20%20%20return%20val%3B%20%2F%2F%20val%20inferred%20to%20A%0D%0A%20%20%20%20%7D%20else%20if%20(isB(val))%7B%20%2F%2F%20val%20inferred%20to%20B%0D%0A%20%20%20%20%20%20%20%20throw%20new%20Error()%3B%20%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20val%20%2F%2F%20type%20inferred%20to%20never%0D%0A%7D

**Comment by tomrav** [comment]
Thanks for the tip, didn't know you can do that! 👍

**Comment by mhegazy** [comment]
Please see https://github.com/Microsoft/TypeScript/issues/17358, https://github.com/Microsoft/TypeScript/issues/20409, https://github.com/Microsoft/TypeScript/issues/10470 and https://github.com/Microsoft/TypeScript/issues/9655

**Comment by tomrav** [comment]
I see how you're approaching it now, I'll close the issue.
Thanks 👍
