### ISSUE TITLE
Feature Request / Proposal: constructor type guard

### ISSUE THREAD

**Issue by sheley1998** [microsoft/TypeScript#23274]
In most cases, constructor comparison is faster than instanceof and typeof, thus using it as type guard can improve performance. The code below demonstrates the desired behavior:

```ts
const el:HTMLElement = document.createElement('canvas');

if (el.constructor === HTMLCanvasElement) {
    //inside of this scope, el is parsed as an instance of HTMLCanvasElement
    el.getContext('2d');
}
```

**Comment by mhegazy** [comment]
related to https://github.com/Microsoft/TypeScript/issues/3841

**Comment by RyanCavanaugh** [comment]
Accepting PRs for a new kind of type guard (IOW one that specifically looks for this syntactic pattern). Note that the `false` arm here can't perform any narrowing of a union due to `constructor` checks not identifying subclasses.

**Comment by Kingwl** [comment]
i’d like to work on this :smile:

**Comment by austincummings** [comment]
Is this issue being worked? If not I'd like to try and add this.

**Comment by adam-arold** [comment]
Hey. Why was this closed? :(

**Comment by Kingwl** [comment]
Because #32774 is merged.

**Comment by ikonst** [comment]
The snippet in the issue doesn't work. @sandersn, can we reopen?

The only thing that works with #32774 is
```
const el: HTMLDivElement | HTMLCanvasElement = document.createElement(tagName);
if (el.constructor === HTMLCanvasElement) {
  //inside of this scope, el is parsed as an instance of HTMLCanvasElement
  el.getContext('2d');
}
```
