### ISSUE TITLE
2.8.2 needs to published to npm

### ISSUE THREAD

**Issue by kevcenteno** [Microsoft/TypeScript#23282]
**Expected behavior:**
2.8.2 is available via npm

**Actual behavior:**
2.8.2 isn't available via npm

**Comment by mhegazy** [comment]
2.8.2, the servicing release for TypeScript@2.8.1 has been renamed to 2.8.3, and the release date is pushed to next week. see https://github.com/Microsoft/TypeScript/milestone/68 for more info about what issue included.

**Comment by mhegazy** [comment]
to reiterate, we have no plans on shipping a 2.8.2 release on npm. 2.8.3 should be available next week though.

**Comment by kevcenteno** [comment]
@mhegazy Any updates on the 2.8.3 release?

**Comment by mhegazy** [comment]
`typescript@2.8.3` should be available on npm now. sorry for the delay.
