### ISSUE TITLE
Generic type constraint does not apply to rest parameters

### ISSUE THREAD

**Issue by sccolbert** [Microsoft/TypeScript#2328]
The following fails to compile even though T is constrained to an array type:

```typescript
function attach<T extends any[]>(cb: (...args: T) => void): void { }
```

```
A rest parameter must be of an array type.
(parameter) args: T extends any[]
```

**Comment by danquirk** [comment]
This is technically by design but it's a reasonable suggestion. We also don't allow subtypes of array without generics.

**Comment by RyanCavanaugh** [comment]
Spec section 3.8.2.2

**Comment by RyanCavanaugh** [comment]
This doesn't actually make sense.

The function should be rewritten this way:
```ts
function attach<T>(cb: (...args: T[]) => void): void { }
```

Any production that requires that you write `T` instead of `T[]` would require a lie, because the type of the rest arg is always going to be the basic `Array` type, not some subtype thereof. It would be especially dangerous to flow that type through.

**Comment by JoshuaKGoldberg** [comment]
@RyanCavanaugh what if the function is meant to be used like the following?

```ts
attach((age: number, name: string) => {
    console.log({ age, name });
});

// written explicitly:
attach<[number, string]>(/*... */);
```

Using the `...args: T[]` approach we would then have this typed as `(number | string)[]` instead of `[number, string]` right?

**Comment by RyanCavanaugh** [comment]
If that's the desired behavior you'd be better off writing some explicit overloads e.g. https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/underscore/underscore.d.ts#L1126

**Comment by ds300** [comment]
As a library author this makes me sad, since with overloading you lose the parameter name information. Plus it produces ugly inline documentation.

**Comment by YMIndustries** [comment]
I'd love to see this decision reconsidered. As I understand it, one of TypeScript's major design goals is to have a type system flexible enough to represent any common JavaScript design pattern. Rest parameters have been supported for years, and generics are a vital part of TypeScript, the fact that you can't use both together is unfortunate.

**Comment by theRobinator** [comment]
I'd also like to be able to use this feature. I'm building an abstract command pattern class that I'd like to do something like this for:
```
abstract class Command<T extends any[]> {
    public load(...args: T);
    public loadIfNeeded(...args: T);
    public clearAndReload(...args: T);
}
```

Requiring implementing classes to override every method in the abstract class just to provide a type definition is ugly. Implementing this issue's feature would solve this nicely.
