### ISSUE TITLE
Add flag to mark TS Server unused variable suggestion diagnostics

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#23288]
**TypeScript Version:**  2.9.0-dev.20180409

**Search Terms:** 
- suggestion diagnostics
- no unused
- tsserver 

**Request**
Follow up on #22361. Just tried it out in VS Code. Very cool to see this working but we will need a new a flag on suggestion diagnostic objects that identifies them as  being diagnostics for unused variables. I don't currently see any flags being returned by tsserver

**Comment by andy-ms** [comment]
We did add a `reportsUnnecessary` property to the diagnostic object.
