### ISSUE TITLE
CodeAction: convert lambda expression declaration to function 

### ISSUE THREAD

**Issue by Kingwl** [microsoft/TypeScript#23299]
**TypeScript Version:**  2.7.0-dev.201xxxxx

**Code**

```tsx
const a = (arg: number) => (
    <div>{arg}foo</div>
)
```

**Expected behavior:**

```tsx
function a (arg: number) {
  return (
    <div>{arg}foo</div>
  )
}

```

**Actual behavior:**
none

btw: also convert function to lambda expression

**Comment by Kingwl** [comment]
![image](https://user-images.githubusercontent.com/6831019/38655385-e0bd85e0-3e46-11e8-8021-3c8fb36a04ef.png)

from IDEA

**Comment by zaaack** [comment]
+1. Add braces is very useful, too.

**Comment by zuozijian3720** [comment]
+1. Add braces is very useful, too.

**Comment by AngryPowman** [comment]
Kingwl's proposals always help me a lot.

**Comment by vizee** [comment]
Kingwl's proposals always help AngryPowman a lot.

**Comment by whtsky** [comment]
I can't live without Kingwl's proposals.

**Comment by D0nGiovanni** [comment]
Hi

We're a team of two, currently on our bachelor thesis. We'd like to implement this issue. Estimated timeframe is about 2 weeks, at most 4 weeks. We're looking to do other refactorings and code fixes as well, but this would come first.

**Comment by Kingwl** [comment]
could bachelor thesis based on an open source project with Apache License 2.0?😂
I suggest you confirm it in advance.

**Comment by D0nGiovanni** [comment]
I don't know about other countries, but I don't see why it couldn't. It's approved anyway. We're already 3 weeks in. It's more of an engineering project than anything else. 
I looked it up anyway, because I was curious. I didn't find any restrictions regarding license.

But we're getting slightly off-topic here... :P

**Comment by D0nGiovanni** [comment]
I've got a question about reversing your example, @Kingwl. Of course, reversing an anonymous function makes sense. (More likely to go from right to left here)

```
foo(function (arg) { return <div>{arg}foo</div>; });
```
to
```
foo(arg => <div>{arg}foo</div>);
```

or even

```
foo(arg => <div>{arg}foo</div>);
```
to
```
foo(bar);
function bar (arg) {
  return <div>{arg}foo</div>; 
}
```
But what about named function to lambda? Is that actually a use-case? Afaik, Webstorm does not support this. Maybe for a good reason?

```
function a (arg: number) {
  return (
    <div>{arg}foo</div>
  )
}
```
to
```
const a = (arg: number) => (
    <div>{arg}foo</div>
)
```

Last question (for now): Do we also support lambda to method? Of course, we would have to check for class scope.

```
class kitty{
  someMethod(){
    foo(arg => <div>{arg}foo</div>);
  }
}
```
to
```
class kitty{
  someMethod(){
    foo(bar);
  }
  bar (arg) {
    return <div>{arg}foo</div>;
  }
}
```

**Comment by Kingwl** [comment]
`lambda to method` or the first case seems another refactor `extract to`(or combined more transform)


> But what about the named function to lambda? Is that actually a use-case? Afaik, 

if you want to edit, convert, or transform the parameter, but actually, add braces could cover the case

> Webstorm does not support this. Maybe for a good reason?
yes, such as 'Hoisting'

**Comment by D0nGiovanni** [comment]
You are right. They are different - and also already implemented.

So to clarify, there are only 2 cases that are in the scope of this refactor. Your example and this:

``foo(function (arg) { return <div>{arg}foo</div>; });`` <=> ``foo(arg => <div>{arg}foo</div>);``

**Comment by Kingwl** [comment]
Thanks！
