### ISSUE TITLE
Include WebRTC data channel stuff

### ISSUE THREAD

**Issue by TomasHubelbauer** [Microsoft/TypeScript#23300]
Please see Microsoft/TypeScript#23245 for context. This needs to update `src\lib\dom.generated.d.ts` so I'm opening a PR here instead of in the TypeScript repository. I will be working on this, but can't guarantee any deadlines/estimates, so anyone else is welcome to race me to PRing this.

**Comment by a-tarasyuk** [comment]
@TomasHubelbauer I've created PR. @mhegazy could you review it?

**Comment by TomasHubelbauer** [comment]
@a-tarasyuk can you please link it here?

**Comment by mhegazy** [comment]
Looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/23245 and should be fixed by https://github.com/Microsoft/TSJS-lib-generator/pull/424

**Comment by TomasHubelbauer** [comment]
I'm such a goof... I thought I opened this in the TSJS-lib-generator repo :-(
