### ISSUE TITLE
Subclass method throwing exception gives type error (wrong return type)

### ISSUE THREAD

**Issue by prendradjaja** [Microsoft/TypeScript#23309]
**TypeScript Version:**  2.7.2. Also reproduced on TS Playground 2018-04-10
**Search Terms:** exception subclass abstract, error subclass abstract

**Code:**
```ts
abstract class LifeForm {
    abstract getAge(): number;
}

class Dog extends LifeForm {
    private actualAge: number;
    getAge() {  // This is valid
        return 7 * this.actualAge;
    }
}

class Immortal extends LifeForm {
    getAge() {  // This gives a type error (below)
        throw Error("Immortals are ageless");
    }
}
```

**Expected behavior:** `Immortal` is a valid subclass of `LifeForm`.
**Actual behavior:** Error:

```
Property 'getAge' in type 'Immortal' is not assignable to the same property in base type 'LifeForm'.
  Type '() => void' is not assignable to type '() => number'.
    Type 'void' is not assignable to type 'number'.
```

I'm not sure if this is a bug or just misuse on my part. Even if it is a bug, it's easily worked around, as `Immortal2` below does work fine. But I suspect it's a bug, because `myFunc` below is analogous but also works fine.

```ts
class Immortal2 extends LifeForm {
    getAge(): number {
        throw Error("Immortals are ageless");
    }
}

let myFunc: () => number;

myFunc = () => {
    return 3;
};
myFunc = () => {
    throw Error("Invalid")
};
```

**Playground Link:** [link](https://www.typescriptlang.org/play/#src=abstract%20class%20LifeForm%20%7B%0A%20%20%20%20abstract%20getAge()%3A%20number%3B%0A%7D%0A%0Aclass%20Dog%20extends%20LifeForm%20%7B%0A%20%20%20%20private%20actualAge%3A%20number%3B%0A%20%20%20%20getAge()%20%7B%0A%20%20%20%20%20%20%20%20return%207%20*%20this.actualAge%3B%0A%20%20%20%20%7D%0A%7D%0A%0A%2F%2F%20Type%20error%3A%20Type%20'()%20%3D%3E%20void'%20is%20not%20assignable%20to%20type%20'()%20%3D%3E%20number'.%0A%2F%2F%20Is%20this%20a%20bug%3F%0Aclass%20Immortal%20extends%20LifeForm%20%7B%0A%20%20%20%20getAge()%20%7B%0A%20%20%20%20%20%20%20%20throw%20Error(%22Immortals%20are%20ageless%22)%3B%0A%20%20%20%20%7D%0A%7D%0A%0A%2F%2F%20Everything%20else%20is%20typed%20fine%2C%20as%20expected.%0Aclass%20Immortal2%20extends%20LifeForm%20%7B%0A%20%20%20%20getAge()%3A%20number%20%7B%0A%20%20%20%20%20%20%20%20throw%20Error(%22Immortals%20are%20ageless%22)%3B%0A%20%20%20%20%7D%0A%7D%0A%0Alet%20myFunc%3A%20()%20%3D%3E%20number%3B%0A%0AmyFunc%20%3D%20()%20%3D%3E%20%7B%0A%20%20%20%20return%203%3B%0A%7D%3B%0AmyFunc%20%3D%20()%20%3D%3E%20%7B%0A%20%20%20%20throw%20Error(%22Invalid%22)%0A%7D%3B)

**Comment by RyanCavanaugh** [comment]
This is an outcome of some historical decisions we can't change without causing a fairly large breaking change. The correct workaround is to add a type annotation:
```ts
class Immortal extends LifeForm {
    getAge(): never {
        throw Error("Immortals are ageless");
    }
}
```

**Comment by prendradjaja** [comment]
I see, thank you!
