### ISSUE TITLE
TLS certificate invalid for https://www.typescriptlang.org

### ISSUE THREAD

**Issue by caitp** [Microsoft/TypeScript#2331]
The wildcard domain for azurewebsites.net is not ideal for a custom domain

**Comment by mhegazy** [comment]
Pinging @jonathandturner for this one.

**Comment by jonathandturner** [comment]
Curious - what's the use case for using the TS website over https?

**Comment by danquirk** [comment]
I think folks just want everything on https these days.

**Comment by caitp** [comment]
Generally, being a good citizen of the web. It's always preferable to link to secure content, and who knows, might want to make use of features only available over secure connections, down the line.

**Comment by jasonwilliams200OK** [comment]
HTTPS is kind of viral these days. This is true.

https://nodejs.org/
https://npmjs.org/
https://iojs.org/

(http://www.nuget.org/ does not get redirected to https though, ahem and yet it is not as *hip* as npm..)

**Comment by mhegazy** [comment]
should be working now on https://www.typescriptlang.org/
