### ISSUE TITLE
Union inference works in only some cases

### ISSUE THREAD

**Issue by pelotom** [Microsoft/TypeScript#23312]
**TypeScript Version:**  2.8.1

**Search Terms:** 

union inference

**Code**

```ts
let result: string | number

// Works
const fromArray = <Z>(cases: Z[]): Z => cases[0];
result = fromArray(['a', 3]);

// Doesn't work
const fromTuple = <Z>(cases: [Z, Z]): Z => cases[0];
result = fromTuple(['a', 3]);

// Doesn't work
const fromVarargs = <Z>(...cases: Z[]): Z => cases[0];
result = fromVarargs('a', 3);

// Works
const fromStringIndex = <Z>(cases: { [k: string]: Z }): Z => cases.x;
result = fromStringIndex({ x: 'a', y: 3 });

// Doesn't work
const fromRecord = <Z>(cases: { [K in 'x' | 'y']: Z }): Z => cases.x;
result = fromRecord({ x: 'a', y: 3 });
```

**Expected behavior:**

All of these examples should work, with the type parameter `Z` being inferred as the union of the types of all values provided.

**Actual behavior:**

Only the array and string index cases work.

[**Playground Link**](http://www.typescriptlang.org/play/#src=let%20result%3A%20string%20%7C%20number%0D%0A%0D%0A%2F%2F%20Works%0D%0Aconst%20fromArray%20%3D%20%3CZ%3E(cases%3A%20Z%5B%5D)%3A%20Z%20%3D%3E%20cases%5B0%5D%3B%0D%0Aresult%20%3D%20fromArray(%5B'a'%2C%203%5D)%3B%0D%0A%0D%0A%2F%2F%20Doesn't%20work%0D%0Aconst%20fromTuple%20%3D%20%3CZ%3E(cases%3A%20%5BZ%2C%20Z%5D)%3A%20Z%20%3D%3E%20cases%5B0%5D%3B%0D%0Aresult%20%3D%20fromTuple(%5B'a'%2C%203%5D)%3B%0D%0A%0D%0A%2F%2F%20Doesn't%20work%0D%0Aconst%20fromVarargs%20%3D%20%3CZ%3E(...cases%3A%20Z%5B%5D)%3A%20Z%20%3D%3E%20cases%5B0%5D%3B%0D%0Aresult%20%3D%20fromVarargs('a'%2C%203)%3B%0D%0A%0D%0A%2F%2F%20Works%0D%0Aconst%20fromStringIndex%20%3D%20%3CZ%3E(cases%3A%20%7B%20%5Bk%3A%20string%5D%3A%20Z%20%7D)%3A%20Z%20%3D%3E%20cases.x%3B%0D%0Aresult%20%3D%20fromStringIndex(%7B%20x%3A%20'a'%2C%20y%3A%203%20%7D)%3B%0D%0A%0D%0A%2F%2F%20Doesn't%20work%0D%0Aconst%20fromRecord%20%3D%20%3CZ%3E(cases%3A%20%7B%20%5BK%20in%20'x'%20%7C%20'y'%5D%3A%20Z%20%7D)%3A%20Z%20%3D%3E%20cases.x%3B%0D%0Aresult%20%3D%20fromRecord(%7B%20x%3A%20'a'%2C%20y%3A%203%20%7D)%3B%0D%0A)

**Comment by RyanCavanaugh** [comment]
If you have exactly one place where `Z` occurs, then you have exactly one inference candidate, and we choose that candidate. There's not something else we even could do.

If you have more than one place where `Z` occurs, then you have multiple inference candidates, and we **intentionally** don't synthesize a union type. See https://github.com/Microsoft/TypeScript/issues/805#issuecomment-57740519 for an old and long discussion of why. The previous behavior here, inferring a different supertype-of-both (which people hated), was tracked by #360.

**Comment by pelotom** [comment]
> If you have more than one place where Z occurs, then you have multiple inference candidates; we **intentionally** don't synthesize a union type to construct a new type such that all candidates are satisfied.

Ok, but in some cases a union type _is_ being synthesized (the array and `string`-indexed objects). I could understand if it never worked, but the fact that it works in some specific cases is what's confusing to me.

**Comment by RyanCavanaugh** [comment]
More specifically, we don't synthesize union types *as part of inference*. In any place where the call succeeds, the type `(string | number)[]` is already present in one of the sourcing expressions. Comments inline:

```ts
let result: string | number

// Works
const fromArray = <Z>(cases: Z[]): Z => cases[0];
// The array literal has the type (string | number)[] - we didn't synthesize that during inference
result = fromArray(['a', 3]);

// Doesn't work
const fromTuple = <Z>(cases: [Z, Z]): Z => cases[0];
// Z gets two candidates: string, number
// The array literal's type is not observed during inference
result = fromTuple(['a', 3]);

// Doesn't work
const fromVarargs = <Z>(...cases: Z[]): Z => cases[0];
// Z gets two candidates: string, number
// The union type string | number doesn't exist anywhere
result = fromVarargs('a', 3);

// Works
const fromStringIndex = <Z>(cases: { [k: string]: Z }): Z => cases.x;
// The fresh object literal has an index signature to string|number
result = fromStringIndex({ x: 'a', y: 3 });

// Doesn't work
const fromRecord = <Z>(cases: { [K in 'x' | 'y']: Z }): Z => cases.x;
// Each property maps to a Z so we have two candidates: string, number
result = fromRecord({ x: 'a', y: 3 });
```

**Comment by pelotom** [comment]
I see, thanks for the explanation!
