### ISSUE TITLE
Object Literal + spread + public property

### ISSUE THREAD

**Issue by unional** [Microsoft/TypeScript#23329]
Sorry about the title. Can't think of a good way to describe the issue. Feel free to modify it.

Here is the issue:

```ts
class Foo {
    do() { }
}
class Boo extends Foo {
    public x: number
}
function foo(f: Foo) { return f }
const boo = new Boo()

// Argument of type '{ x: number; }' is not assignable to parameter of type 'Foo'.
//  Object literal may only specify known properties, and 'x' does not exist in type 'Foo'.
foo({ ...boo })
```

[playground link](http://www.typescriptlang.org/play/index.html#src=class%20Foo%20%7B%0D%0A%20%20%20%20do()%20%7B%20%7D%0D%0A%7D%0D%0A%0D%0Aclass%20Boo%20extends%20Foo%20%7B%0D%0A%20%20%20%20public%20x%3A%20number%0D%0A%7D%0D%0A%0D%0Afunction%20foo(f%3A%20Foo)%20%7B%20return%20f%20%7D%0D%0A%0D%0A%0D%0Aconst%20boo%20%3D%20new%20Boo()%0D%0A%0D%0Afoo(%7B%20...boo%20%7D)%0D%0A)

**Comment by andy-ms** [comment]
In addition to the extra property, spreading an object removes methods. So `foo({ ... new Foo() })` would also fail.
