### ISSUE TITLE
TypeScript has doubled in size since v2.0.0 - now 35 MB

### ISSUE THREAD

**Issue by styfle** [Microsoft/TypeScript#23339]
**Search Terms:** install size mb

**Expected behavior:**
I expected typescript to be relatively small since it has zero dependencies so there is no additional bloat from `package.json` or `README.md` files included with dependencies.

 [![install size](https://packagephobia.now.sh/badge?p=typescript@2.0.0)](https://packagephobia.now.sh/result?p=typescript@2.0.0) `typescript@2.0.0` is about 17 MB, not too bad.

**Actual behavior:**

[![install size](https://packagephobia.now.sh/badge?p=typescript@2.9.0-dev.20180411)](https://packagephobia.now.sh/result?p=typescript@2.9.0-dev.20180411) `typescript@2.9.0-dev.20180411` is about 35 MB - double the size in about 2 years 

I realize that there are no stated goals of install size, however it is worth considering because...how is TypeScript getting so big so fast? 😕 

This might inhibit new users from coming on board when their code base might be a few kB with plain JS and adding TS would make it 35 MB.

**Steps to reproduce**
```
mkdir ts2.0
cd ts2.0
npm init -y
npm install --save-dev typescript@2.0.0
cd ..
mkdir ts2.9
cd ts2.9
npm init -y
npm install --save-dev typescript@2.9.0-dev.20180411
cd ..
du -sh ts2.0 # 17M
du -sh ts2.9 # 35M
```

**Comment by DanielRosenwasser** [comment]
I agree - installs should be definitely be fast! But also keep in mind that 2 years is a long time, so we've done a lot outside of what was in 2.0 (e.g. infrastructure for our emit pipeline).

The TypeScript package's `lib` folder contains the following:

- 4.85MB of `lib.*.d.ts` files
- 0.87MB of `.d.ts` files relating to our API
- 2.20MB of localized versions of error messages used by the --locale flag

Then we have something like 24.8MB of `.js` files (this is all me trusting Windows Explorer btw 😃).

But you're right, on an individual basis, `tsc.js` [from 2.0](https://unpkg.com/typescript@2.0.0/lib/) is [about half of what we're producing now](https://unpkg.com/typescript@2.9.0-dev.20180411/lib/). This is exacerbated by the fact that the compiler's core code (e.g. type-checker etc.) are duplicated between outputs like `tsc.js` and `typescript.js`. So if the core compiler increased by 1.44MB, I believe we'd see something like a 7.2MB increase. If we used modules, we'd be able to share each file and avoid this duplication.

**Comment by styfle** [comment]
@DanielRosenwasser Thanks for the quick and detailed response!

The installs are pretty fast which is why it caught me off guard.

I noticed [typescript](https://packagephobia.now.sh/result?p=typescript@2.9.0-dev.20180411) is about the same size as [webpack-cli](https://packagephobia.now.sh/result?p=webpack-cli@2.0.14) but installs much faster, likely due to the fact that there are zero dependencies (I didn't measure install times and I'm not sure if npm caches results anyway).

> If we used modules, we'd be able to share each file and avoid this duplication.

By modules, you mean ES6 Modules? Something that node.js doesn't support yet?

I know that @jdalton wrote [esm](https://www.npmjs.com/package/esm) which might be worth including a few additional kB from the `esm` dependency if you can drastically decrease the output size.

I'm not sure how much collaboration there is between the TS team and the Chakra team or even if this is achievable.

**Comment by RyanCavanaugh** [comment]
Oops, totally invalid results. Didn't realize NPM changed behavior and started saving to package.json by default!

**Comment by styfle** [comment]
I have been doing some comparisons of popular tools in similar categories and I happen to really like TypeScript so I thought I would make note of it.

You can see some of the comparisons I've done here: https://github.com/styfle/packagephobia#demo

------

That being said, what is the quote "If we used modules, we'd be able to share each file and avoid this duplication" mean? Is this achievable in a TS 3.0.0 or some future release?

**Comment by mhegazy** [comment]
We have a change to reorganize the library in https://github.com/Microsoft/TypeScript/pull/15780. this should allow us to remove all duplication in the lib files. that said, I expect the lib file to increase in the next release as we are working on updating it and adding comments, so that might end up being a wash.

We should be able to remove some 6 MBs by combining the two targets tsserverlibarary.js and typescriptservices.js. this a breaking change, so we will have to phase it on two releases or so (i.e. combine the contents of the two files in one, but keep both copies in one release, then remove one copy in the next release.).

We can always minify our output. we have not had a reason to do this in the past.

> That being said, what is the quote "If we used modules, we'd be able to share each file and avoid this duplication" mean? Is this achievable in a TS 3.0.0 or some future release?

it is something we want to do, but no plans for the short term. that is where the majority of savings would come from. if we use modules, we should be able to cut the non-library part to 7 MBs or so.

**Comment by DanielRosenwasser** [comment]
> That being said, what is the quote "If we used modules, we'd be able to share each file and avoid this duplication" mean?

For context, today we don't use modules; each file in the Typescript compiler uses namespaces in the global scope, and is concatenated at the end.

> We can always minify our output. we have not had a reason to do this in the past.

For a Node project, I don't think this is worth it unless it'd just be about stripping out whitespace.

**Comment by styfle** [comment]
Thanks for all the information, I appreciate the dialog 👍 

I would like to point out that the latest [typescript@2.9.0-insiders.20180510](https://packagephobia.now.sh/result?p=typescript@2.9.0-insiders.20180510) has just doubled again
...now **76.8 MB**! 😮 

The spike was introduced in [typescript@2.9.0-dev.20180505](https://packagephobia.now.sh/result?p=typescript@2.9.0-dev.20180505)

Is this worrisome? At what point is TypeScript too big? 😕

**Comment by weswigham** [comment]
@mhegazy is the case of those files wrong in our npmignore? All we did was start to publish on 'nix.

**Comment by mhegazy** [comment]
the .d.ts files indicate a change in the build process, we should not be building `tsc.d.ts` in the first place.

**Comment by mhegazy** [comment]
`lib\diagnosticmessages.generated.json` should not be there either.

**Comment by mhegazy** [comment]
the `*.map` file means that `debug=true` was not set when the build was triggered.

**Comment by mhegazy** [comment]
looks like we are explictlly setting `setDebugMode` in the build.

**Comment by mhegazy** [comment]
nevermind, we set it to run the tests, and not for the publishing..

**Comment by mhegazy** [comment]
looks like the rouge files were added in #23844

**Comment by mhegazy** [comment]
`typescript@2.9.1-insiders.20180521` was just published, and we are back to 35 MB.

**Comment by styfle** [comment]
Thanks, I confirmed [![install size](https://packagephobia.now.sh/badge?p=typescript@2.9.1-insiders.20180521)](https://packagephobia.now.sh/result?p=typescript@2.9.1-insiders.20180521)

Also, I created #24282 to display this info in the README so it's more visible.

**Comment by styfle** [comment]
Also happened again in [typescript@3.1.0-dev.20180721](https://packagephobia.now.sh/result?p=typescript@3.1.0-dev.20180721)

| version  | install size  |
|---|---|
|3.1.0-dev.20180717| [![install size](https://packagephobia.now.sh/badge?p=typescript@3.1.0-dev.20180717)](https://packagephobia.now.sh/result?p=typescript@3.1.0-dev.20180717)  | 
| 3.1.0-dev.20180721 | [![install size](https://packagephobia.now.sh/badge?p=typescript@3.0.0-dev.20180630)](https://packagephobia.now.sh/result?p=typescript@3.1.0-dev.20180721) |

Surely this must be a bug, right?

**Comment by mhegazy** [comment]
@weswigham can u take a look.
