### ISSUE TITLE
Conditional type (ReturnType) not correctly infered when used to create an union from a Record type values

### ISSUE THREAD

**Issue by guillaume86** [Microsoft/TypeScript#23338]
**TypeScript Version:**  typescript@2.9.0-dev.20180411

**Search Terms:** 
deep return type
deep ReturnType
conditional return type

**Code**

```ts
type Fn = (...args: any[]) => any;
type SelfOrReturnType2Levels<T> = T extends Fn ?
    ReturnType<T> extends Fn ?
        ReturnType<ReturnType<T>> : 
        ReturnType<T> : 
    T;
type ReturnType2Levels<T extends Fn> = ReturnType<T> extends Fn ? ReturnType<ReturnType<T>> : ReturnType<T>;

const action1 = (age: number) => ({ age });
const action2 = (id: string) => (name: string) => ({ id, name });

//type payload1 = SelfOrReturnType2Levels<typeof action1>; // ok
//type payload2 = SelfOrReturnType2Levels<typeof action2>; // ok
//type ActionUnion<T extends Record<string, Fn>> = SelfOrReturnType2Levels<T[keyof T]>;
//const actions = { action1, action2 };
//type Action = ActionUnion<typeof actions> // ok

type payload1 = ReturnType2Levels<typeof action1>; // ok
type payload2 = ReturnType2Levels<typeof action2>; // ok
type ActionUnion<T extends Record<string, Fn>> = ReturnType2Levels<T[keyof T]>;
const actions = { action1, action2 };
type Action = ActionUnion<typeof actions> // ko
```

**Expected behavior:**
The type Action should be 
```ts
type Action = {
    age: number;
} | {
    id: string;
    name: string;
}
```
like it does in the commented case.

**Actual behavior:**
The type Action is
```ts
type Action = {
    age: number;
} | ((name: string) => {
    id: string;
    name: string;
})
```

**Playground Link:**  
http://www.typescriptlang.org/play/#src=type%20Fn%20%3D%20(...args%3A%20any%5B%5D)%20%3D%3E%20any%3B%0D%0Atype%20SelfOrReturnType2Levels%3CT%3E%20%3D%20T%20extends%20Fn%20%3F%0D%0A%20%20%20%20ReturnType%3CT%3E%20extends%20Fn%20%3F%0D%0A%20%20%20%20%20%20%20%20ReturnType%3CReturnType%3CT%3E%3E%20%3A%20%0D%0A%20%20%20%20%20%20%20%20ReturnType%3CT%3E%20%3A%20%0D%0A%20%20%20%20T%3B%0D%0Atype%20ReturnType2Levels%3CT%20extends%20Fn%3E%20%3D%20ReturnType%3CT%3E%20extends%20Fn%20%3F%20ReturnType%3CReturnType%3CT%3E%3E%20%3A%20ReturnType%3CT%3E%3B%0D%0A%2F%2F%20circular%20types%20not%20allowed%0D%0A%2F%2Ftype%20DeepReturnType%3CT%20extends%20Fn%3E%20%3D%20ReturnType%3CT%3E%20extends%20Fn%20%3F%20DeepReturnType%3C%3CReturnType%3CT%3E%3E%20%3A%20ReturnType%3CT%3E%3B%0D%0A%0D%0Aconst%20action1%20%3D%20(age%3A%20number)%20%3D%3E%20(%7B%20age%20%7D)%3B%0D%0Aconst%20action2%20%3D%20(id%3A%20string)%20%3D%3E%20(name%3A%20string)%20%3D%3E%20(%7B%20id%2C%20name%20%7D)%3B%0D%0A%0D%0A%2F%2Ftype%20payload1%20%3D%20SelfOrReturnType2Levels%3Ctypeof%20action1%3E%3B%20%2F%2F%20ok%0D%0A%2F%2Ftype%20payload2%20%3D%20SelfOrReturnType2Levels%3Ctypeof%20action2%3E%3B%20%2F%2F%20ok%0D%0A%2F%2Ftype%20ActionUnion%3CT%20extends%20Record%3Cstring%2C%20Fn%3E%3E%20%3D%20SelfOrReturnType2Levels%3CT%5Bkeyof%20T%5D%3E%3B%0D%0A%2F%2Fconst%20actions%20%3D%20%7B%20action1%2C%20action2%20%7D%3B%0D%0A%2F%2Ftype%20Action%20%3D%20ActionUnion%3Ctypeof%20actions%3E%20%2F%2F%20ok%0D%0A%0D%0Atype%20payload1%20%3D%20ReturnType2Levels%3Ctypeof%20action1%3E%3B%20%2F%2F%20ok%0D%0Atype%20payload2%20%3D%20ReturnType2Levels%3Ctypeof%20action2%3E%3B%20%2F%2F%20ok%0D%0Atype%20ActionUnion%3CT%20extends%20Record%3Cstring%2C%20Fn%3E%3E%20%3D%20ReturnType2Levels%3CT%5Bkeyof%20T%5D%3E%3B%0D%0Aconst%20actions%20%3D%20%7B%20action1%2C%20action2%20%7D%3B%0D%0Atype%20Action%20%3D%20ActionUnion%3Ctypeof%20actions%3E%20%2F%2F%20ko

**Comment by mhegazy** [comment]
A conditional type is distributive iff it is written using a naked type parameter.. in other words `type A<T> = T extends cond ? ture : flase` is distributive, but `type B<T> = ReturnType<T> extends cond ? true : false` is not.

you can write your type as a series of two references to ensure it is distributive. e.g.

```ts
type ReturnType2Levels<T extends Fn> = ReturnTypeOrSelf<ReturnType<T>>;
type ReturnTypeOrSelf<T> = T extends Fn ? ReturnType<T> : T;
```

**Comment by guillaume86** [comment]
Ha Ok thanks good to know. Should I just close the issue then ?
