### ISSUE TITLE
merge pull requests about formatting

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#23344]
https://github.com/Microsoft/TypeScript/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+format

**Comment by RyanCavanaugh** [comment]
We are aware we have a pull request backlog

**Comment by aleksey-bykov** [comment]
you might not be aware that you are still asking for help as far as formatting yet having your hands full and all the help you got is unactionable, this doesn't make sense: https://github.com/Microsoft/TypeScript/issues/3817#issuecomment-380594826
