### ISSUE TITLE
Question about AngularJS 2

### ISSUE THREAD

**Issue by zzm2q** [Microsoft/TypeScript#2334]
I read something from this article: http://blogs.msdn.com/b/typescript/archive/2015/03/05/angular-2-0-built-on-typescript.aspx.

I found there are two new syntax features in that typescript code:
1. annotations(very cool, i really like it)
2. keyword "import"

Is it true? if yes, which version of typescript the tow features would be included in?
Thanks.

**Comment by mhegazy** [comment]
This should be included in the next release: [TypeScript 1.5](https://github.com/Microsoft/TypeScript/wiki/Roadmap#15)

**Comment by zzm2q** [comment]
That's good news. i can't wait.

**Comment by AliMD** [comment]
:-1:

**Comment by DanielRosenwasser** [comment]
Thanks for your input @AliMD, we found it sufficiently constructive and will take it into consideration.
