### ISSUE TITLE
Code `Quill.import('mod');` makes TS think it needs to `import('mod')`

### ISSUE THREAD

**Issue by joscha** [Microsoft/TypeScript#23359]
The quill library has a static method called `import` on it's exported symbol, which is used like this:
```js
Quill.import('dependency');
```

These dependencies are not actually imports, they are [strings in a map](https://github.com/quilljs/quill/blob/df1d4e49a3ef6dddb2fc62dd3f5d843e464ae55e/core/quill.js#L27-L32). Unfortunately `ts.preProcessFile` thinks they are valid imports.
I tried fixing the issue, but there is some logic missing and I am unsure how to debug the test I added properly with me being able to look at the scanner state. Maybe someone can give me a hint on how to complete my fix in #23358, please?

**TypeScript Version:**  `master` (edcf08714515f2a9ff5cbe65f4e8c233c11582fa)

**Search Terms:** Quill, .import, static import, preprocessFiles

**Code**

```ts
Quill.import('delta');
```
see https://github.com/Microsoft/TypeScript/pull/23358/files#diff-fa5d406e8b31aa069cd80d9698ca0590R63

**Expected behavior:**
`Quill.import('delta');` is treated like any other code (a function call of the function `import` on a symbol `Quill`)

**Actual behavior:**
TS thinks this is a proper import a la `import('delta')`, ignoring the fact that there is a preceding `Quill.`.

**Playground Link:** See #23358

**Related Issues:**
 #23358

**Comment by mhegazy** [comment]
You are seeing an error on VS 2015? or this is an API issue? we have stopped using preprocessFile for a while now..

**Comment by joscha** [comment]
@mhegazy we are using the API for a typescript webpack loader, so we are seeing it when using that, but the root cause is the function itself. Apart from that I am unaware of any other product is affected.

**Comment by mhegazy** [comment]
thanks for the context. but why not just use the sourceFile?

**Comment by joscha** [comment]
> thanks for the context. but why not just use the sourceFile?

Sorry, I am not following? We need to transform the dependency information in something that webpack can understand, e.g. we have a snippet of code that looks like this:

```ts
const preProcessedFileInfo = ts.preProcessFile(content, true, true);
return preProcessedFileInfo.importedFiles.map(({ fileName }) => `require("${fileName}");`).join('\n');
```

**Comment by joscha** [comment]
> If you do parse (i.e. call createSourceFile or createProgram) then you have an AST, you can walk the AST to get the info you need.

I am sure we can, that's also what https://github.com/pahen/detective-typescript does for example, even without using the ts-provided AST. There are a lot of ways doing this, including a terrible regex or changing the code to `Quill['import']('mod')` (what we did in the meantime), but the way we have written the code is using the API `ts.preProcessFile`, because it did what we needed at the time. This API has a fault as outlined in the issue description. I would like to fix this fault, if possible and avoid rewriting a large chunk of some other component. I am happy to spend the time finding a fix, however the way this discussion is going right now, it feels as if you are suggesting to leave the API as-is and I should look elsewhere to fix my problem?
