### ISSUE TITLE
Salsa - IntelliSense based on JSDoc, @typedef -> @property -> {Function(Type): Type} not support

### ISSUE THREAD

**Issue by ZSkycat** [Microsoft/TypeScript#23356]
**TypeScript Version:**  

**Code**

```ts
/**
 * @typedef TestType
 * @property {Function(String): Boolean} createTestFunction
 */

/** @type {TestType} */
var t;

/** @type {Function(String): Boolean} */
var fn1;
```
`@property` does not support {Function(Type): Type}
`@type` support {Function(Type): Type}

**Expected behavior:**
```
type TestType = {
    createTestFunction: Function;
}
```

**Actual behavior:**
```
type TestType = {
    (Missing): Function;
}
```

**Comment by mhegazy** [comment]
I think you meant `function` and not `Function`. 

```ts
/**
 * @typedef TestType
 * @property {function(String): Boolean} createTestFunction
 */

/** @type {TestType} */
var t;

/** @type {function(String): Boolean} */
var fn1;

```
`Function` is a type name, and it already has a well defined meaning. 

The closure-compiler docs also refer to the lower-case `function`: https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler#function-type

**Comment by ZSkycat** [comment]
@mhegazy oh, i don't know 'Function' and 'function' are different 😂

should the wiki explain this?
https://github.com/Microsoft/TypeScript/wiki/JsDoc-support-in-JavaScript

**Comment by mhegazy** [comment]
it is:

> ````ts
>// Define function type
>/** @type {function(string, boolean): number} */
>var fn5;
