### ISSUE TITLE
Type annotations in lib.d.ts are not type safe

### ISSUE THREAD

**Issue by andrewvarga** [Microsoft/TypeScript#23353]
In lib.d.ts (TS 2.8.1) all the interfaces of WebGL objects like WebGLBuffer, WebGLTexture are empty, and so because of structural subtyping (duck typing), this code compiles without a problem:

```
let texture: WebGLTexture;
let buffer: WebGLBuffer = texture;
```

An external typing file I used for WebGL types solves this by adding dummyprops to these interfaces, which is a little hacky but works:
https://github.com/asgerf/dartify/blob/master/testcases/pixi/webgl.d.ts

I know this is intended behaviour for TypeScript  but I was wondering if there is a better way to enforce type safety in situations like this?

**Comment by mhegazy** [comment]
i think this is the same as https://github.com/Microsoft/TypeScript/issues/5855

**Comment by andrewvarga** [comment]
Indeed.
