### ISSUE TITLE
Allow static extensions to Set, Map and WeakMap

### ISSUE THREAD

**Issue by edevine** [Microsoft/TypeScript#2336]
I'd like to overload the E6 Collections constructor declarations to accept an optional parameter per the ECMA specifications. However, the lib.d.ts file declares the collection constructors with anonymous interfaces.

```ts
// Cannot extend a variable declaration
declare var Set: {
    new <T>(): Set<T>;
    prototype: Set<any>;
}

// Can extend the ArrayConstructor interface
declare var Array: ArrayConstructor;
```

**Suggestion**: add `SetConstructor`, `MapConstructor`, `WeakMapConstructor` interfaces to lib.d.ts.

**Comment by mhegazy** [comment]
This should be fixed in the latest 1.5 drop
