### ISSUE TITLE
MSBuild - Don't run VsTsc/recompile all files if no TypeScript files have been changed

### ISSUE THREAD

**Issue by chrisdieckhaus** [Microsoft/TypeScript#23367]
We have a .NET MVC project with a TypeScript front-end, using `tsc` to compile files during build. After investigation, it appears that nearly half of our build time is occuring due to the `CompileTypeScriptWithTSConfig` target, task `VsTsc`. 

**Expected behavior:**
If no typescript files have been updated, `VsTsc` should not be run, since there is no need to recompile all the changed files.

**Stretch expected behavior:**
If I update a TypeScript file and build, only that file should be recompiled, since no other files have changed (similar to the behavior of `tsc --watch`. After doing some searching, I think this might not be possible, but it's worth a shot.

**Actual behavior:**
On build, `VsTsc` is always called and all TypeScript files are recompiled, regardless of whether or not any of them have changed since last build.

**Search Terms:** 
msbuild, vstsc, incremental build, incremental compile, compile on build, visual studio

**Comment by mhegazy** [comment]
//cc @uniqueiniquity 

We have recently made changes to the tasks/targets to optimize this path. what version of TS are you using?

**Comment by chrisdieckhaus** [comment]
2.6.2. Has this been addressed in a later release?

**Comment by chrisdieckhaus** [comment]
Upgraded to 2.7.2 and that seems to have made a big improvement. Closing this issue.

**Comment by chrisdieckhaus** [comment]
So after updating to 2.7.2, our VsTsc compile time _has_ dropped, between 33-50% faster. That being said, VsTsc is still compiling files regardless of whether or not any ts files have actually been updated. Are there any plans to make VsTsc smart enough to skip compilation if nothing has changed?

**Comment by uniqueiniquity** [comment]
@chrisdieckhaus That's correct. When used in the `PreComputeCompileTypeScript(WithTSConfig)` scenario, we're not actually spending time compiling your files; we're only determining inputs and outputs as you noted.

**Comment by chrisdieckhaus** [comment]
Gotcha, that makes sense. Thanks!
