### ISSUE TITLE
Class instance + spread assignment allows wrong type guarantee

### ISSUE THREAD

**Issue by payload** [Microsoft/TypeScript#23363]
Consider this example:
```
let x = new RegExp('');
console.log(x);
x = { ...x };
console.log(x);
```
The spread operator in the object literal produces a new type different vom the RegExp type of x.
The bad thing happens when the type checker allows the assignment of this object to `x` of type RegExp.
For example x has non of the methods of RegExp afterwards.
I expect that the compiler rejects assigning a value of wrong type to x.

Compile it with `tsc --lib es6,dom foo.ts && node foo.js` and get the output:
```
/(?:)/
{}
```

[playground](http://www.typescriptlang.org/play/index.html#src=let%20x%20%3D%20new%20RegExp('')%3B%0D%0Aconsole.log(x)%3B%0D%0Ax%20%3D%20%7B%20...x%20%7D%3B%0D%0Aconsole.log(x)%3B%0D%0A%0D%0Aconst%20y%20%3D%20%7B%20...x%20%7D%3B%0D%0Aconsole.log(y.source)%3B)

**Comment by RyanCavanaugh** [comment]
See comments in https://github.com/Microsoft/TypeScript/issues/13148#issuecomment-270191398
