### ISSUE TITLE
Compile with -w doesn't rebuild all affected files

### ISSUE THREAD

**Issue by RyanMitchellWilson** [Microsoft/TypeScript#23365]
**TypeScript Version:**  2.8.1

**Search Terms:** 
- Typescript 2.8.1 watch not rebuilding all affected files
- tsc -w doesn't rebuild all files

**Code**

This is not an issue with any code, it is an issue with the compiler running in watch mode

**Expected behavior:**
I just updated to Typescript 2.8.1 and I have it installed globally. While running `tsc --pretty -w` I expect to get errors in all files where they occur when I change a file that should cause errors.

**Actual behavior:**
When I save a file that has anything exported, `tsc -w` will only rebuild the file that was saved. So if there are files elsewhere in the code that use those exported things, I will not be told of those new errors until I either go into that specific file with the issue and save it (even if there are no changes), or I cancel `tsc -w` and just run `tsc` it will then pick up the errors and display them. I should get all errors in all files that are caused by a change in one file. I just updated from Typescript 2.6 and never had this problem so it is something new with 2.8.1

**Playground Link:**
Not a code issue

**Related Issues:**

**Comment by mhegazy** [comment]
Can you share a sample project we can use to diagnose the issue?
