### ISSUE TITLE
`promise.then` type parameters are too lenient

### ISSUE THREAD

**Issue by Shingyx** [Microsoft/TypeScript#23364]
**TypeScript Version:**  2.9.0-dev.20180412

**Search Terms:** promise

**Code**

```ts
Promise.resolve(1).then<string>().then(x => x.slice(1));
```

**Expected behavior:**
Does not compile.

**Actual behavior:**
Compiles, and then results in an uncaught TypeError when executed.

**Playground Link:**  http://www.typescriptlang.org/play/#src=Promise.resolve(1).then%3Cstring%3E().then(x%20%3D%3E%20x.slice(1))%3B%0D%0A

**Related Issues:**
Couldn't really find any

I believe this is caused by some of the changes in <https://github.com/Microsoft/TypeScript/commit/8b9fa4ce7420fdf2f540300dc80fa91f5b89ea93> by replacing the four separate `.then` overloads (<https://github.com/Microsoft/TypeScript/commit/8b9fa4ce7420fdf2f540300dc80fa91f5b89ea93#diff-ca94294a2cb9f29f16a30f5d32e56c2eL55>) with just one that uses generic parameter defaults (<https://github.com/Microsoft/TypeScript/commit/8b9fa4ce7420fdf2f540300dc80fa91f5b89ea93#diff-dbd7748aef21cd49b7878047278b29f1R1346>). By only using inferred types, this is never an issue, but it may be good to fix anyway.

**Comment by rbuckton** [comment]
While its true this is incorrect, the biggest problem with the four separate overloads was that they behaved differently when in `--strictNullChecks` vs. not. The simplified single overload behaves much better in these scenarios, with the caveat that it is possible to represent the wrong type with an explicit type argument. 

This is not the only case though, as you can also pass a `Promise` as the type argument and get the wrong type, but the types seem to flow correctly as well, e.g.:

```ts
Promise.resolve().then<Promise<string>>(() => Promise.resolve("foo")).then(x => x);
```

In that example `x` is `Promise<string>`, not `string`. 

Unfortunately, this is likely the best we can do at this time without breaking other scenarios.
