### ISSUE TITLE
Make 'getDefinitions' in the server layer return 'lineText' just like in 'getReferences'

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#2337]
Since 'getDefinitions' can return multiple items just like 'getReferences', it would be helpful to use them in the same manner (i.e. showing the textual context in which they appear).

Thoughts @steveluc, @mhegazy, and @yuit?

**Comment by mhegazy** [comment]
sounds reasonable.

**Comment by DanielRosenwasser** [comment]
Also, we should consider renaming `getDefinitionAtPosition` to `getDefinitionsAtPosition`.

**Comment by mhegazy** [comment]
Is this still needed?
