### ISSUE TITLE
@template tag doesn't work in @typedefs

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#23385]
```ts
/**
 * @template {T}
 * @typedef {(x: T, y: T) => number} SetComparer
 */
```

**Expected**: `x` and `y` have type `T`
**Actual**: `x` any `y` have type `any`, and `T` is associated with whatever declaration follows the JSDoc comment...

For example the following

```ts
/**
 * @template {T}
 * @typedef {(x: T, y: T) => number} SetComparer
 */
class C {
}
```

makes `C` generic on `T`.

**Comment by TheLarkInn** [comment]
Tagging my self for watching this @TheLarkInn

**Comment by sandersn** [comment]
#23511 fixes your second example, which I believe is the one observed in webpack. It does not fix this example:

```js
/**
 * @template {V}
 * @typedef {(v: V) => V} Identity
 * @type Identity
 */
var id = t => t;
var x = id(1)
```

`id` gets the type `(v: V) => V` not `<V>(v: V) => V`, and therefore doesn't infer V=number and instantiate x as number.

**Comment by sandersn** [comment]
Never mind, this works.

```js
/**
 * @typedef {<V>(v: V) => V} Identity
 * @type Identity
 */
var id = t => t;
var x = id(1)
```
