### ISSUE TITLE
CPU usage 100% in Ubuntu 16.04

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#23389]
_From @critical on April 12, 2018 7:1_

Issue Type: <b>Bug</b>

Running VSCode I have 100% of CPU usage from ```electron_node electronForkStart.js tsserver.js``` process
Same behaviour starting with or without ```--disable-extentions``` flag

This is output from ```code --status```:

Version:          Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T00:24:49.616Z)
OS Version:       Linux x64 4.13.0-38-generic
CPUs:             Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 3499)
Memory (System):  15.58GB (2.90GB free)
Load (avg):       2, 2, 2
VM:               0%
Screen Reader:    no
Process Argv:     /usr/share/code/code --unity-launch

|CPU %|Mem MB|PID|Process|
|---|---|---|---|
|9|112|11324|code main|
|0|16|11328|zygote|
|16|239|11369|window (● Untitled-22 - Visual Studio Code)|
|11|80|11443|extensionHost|
|100|160|11472|electron_node electronForkStart.js tsserver.js|
|2|48|11476|electron_node typingsInstaller.js tsserver.js typesMap.js|
|4|80|11376|shared-process|
|2|64|11359|gpu-process|

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T00:24:49.616Z)
OS version: Linux x64 4.13.0-38-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 3500)|
|Load (avg)|2, 2, 1|
|Memory (System)|15.58GB (0.83GB free)|
|Process Argv|/usr/share/code/code --disable-extensions|
|Screen Reader|no|
|VM|0%|

</details>Extensions disabled

_Copied from original issue: Microsoft/vscode#47717_

**Comment by mjbvz** [comment]
@critical In the latest vscode insiders, can you please try collecting the typings installer logs to help us investigate this issue:

1. In VS Code: `"typescript.tsserver.log": "verbose"`
1. Restart vscode and reproduce the issue
1. In VS Code, run the `TypeScript: Open TS Server log` command
1 This should open a folder with a `ti-xxx.log` file in it. That is the typings installer log

If you can share that log file, I or someone on the TS team can try looking through them to see what is going on

⚠️Warning: The TypeScript log may include information from your workspace, including file paths and dependency  names. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by calinmarina** [comment]
I have the same issue on freshly installed vscode version... 
I enabled ```"typescript.tsserver.log": "verbose"``` and attached the logs here: [logs.tar.gz](https://github.com/Microsoft/TypeScript/files/1933956/logs.tar.gz)

It's apparently very easy to reproduce:
*Step 1.* Start VS Code
*Step 2.* Go to `Help` > `Interactive Playground`
*Step 3.* Try any of the snippets, I've reliably managed to get it to 100%+ CPU each time with: Hovering on `if` in `Refactoring via Extraction` section

Here's `--status` before *step 2*:
```bash
[calin@myThinkPad-T460s:~/.config/Code/logs] (00:53:53)
$code --status

Version:          Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:34:44.222Z)
OS Version:       Linux x64 4.13.0-38-generic
CPUs:             Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 3117)
Memory (System):  19.34GB (3.81GB free)
Load (avg):       1, 1, 1
VM:               0%
Screen Reader:    no
Process Argv:     /usr/share/code/code --unity-launch

CPU %	Mem MB	   PID	Process
    7	    99	 23021	code main
    0	    20	 23023	   zygote
   15	   257	 23064	     window (settings.json - Visual Studio Code)
    8	    59	 23130	       extensionHost
    4	    59	 23150	         electron_node jsonServerMain.js 
    3	    99	 23069	     shared-process
    3	    79	 23054	   gpu-process
```
... and after *step 3*:
```
[calin@myThinkPad-T460s:~/.config/Code/logs] (00:54:17)
$code --status

Version:          Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:34:44.222Z)
OS Version:       Linux x64 4.13.0-38-generic
CPUs:             Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 3248)
Memory (System):  19.34GB (3.36GB free)
Load (avg):       5, 2, 1
VM:               0%
Screen Reader:    no
Process Argv:     /usr/share/code/code --unity-launch

CPU %	Mem MB	   PID	Process
    5	    99	 23021	code main
    0	    20	 23023	   zygote
   12	   218	 23064	     window (Interactive Playground - Visual Studio Code)
    5	    79	 23130	       extensionHost
    2	    59	 23150	         electron_node jsonServerMain.js 
    3	    40	 23254	         electron_node cssServerMain.js 
    7	    59	 23255	         electron_node htmlServerMain.js 
  100	   337	 23256	         electron_node electronForkStart.js tsserver.js 
    2	    40	 23272	           electron_node typingsInstaller.js tsserver.js typesMap.js 
    2	    99	 23069	     shared-process
    3	   178	 23054	   gpu-process
```
OS details:
```
[calin@myThinkPad-T460s:~/.config/Code] (00:59:54)
$lsb_release -a
LSB Version:	core-9.20160110ubuntu5-amd64:core-9.20160110ubuntu5-noarch:security-9.20160110ubuntu5-amd64:security-9.20160110ubuntu5-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful
```

**Comment by sheetalkamat** [comment]
Please reopen this bug with detailed log and using typescript@next if issue repros. Thanks.
