### ISSUE TITLE
getOutliningSpans - Return spans for case bodies

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#23380]
From https://github.com/Microsoft/vscode/issues/47579

**TypeScript Version:**  2.9.0-dev.20180409

**Search Terms:** 
- getOutliningSpans
- fold / folding
- switch case

**Code**
For the code:

```ts
switch (1) {
    case 2:
        console.log(1)
        console.log(2)
        console.log(3)
        break;
}
```

1. Try folding the case

**Expected behavior:**
`getOutliningSpans` returns two ranges: one for the entire `switch` and one for the `case`

**Actual behavior:**
Only a single outlining span for the entire `switch` is returned:

```
Result: [
    {
        "textSpan": {
            "start": {
                "line": 1,
                "offset": 11
            },
            "end": {
                "line": 7,
                "offset": 2
            }
        },
        "hintSpan": {
            "start": {
                "line": 1,
                "offset": 12
            },
            "end": {
                "line": 7,
                "offset": 2
            }
        },
        "bannerText": "...",
        "autoCollapse": false
    }
]
```

**Comment by mulligandev** [comment]
Any update on this? It's quite tedious to navigate large switch case statements without being able to collapse cases.

**Comment by RyanCavanaugh** [comment]
1,573 other open suggestions at the moment

**Comment by mjbvz** [comment]
Expected folding:

```
switch (1) {
    case 1:
    case 2:
        1; -----| Fold 1
        2       |
        break;  |                   
        3; ---- |
    case 3:
        4; ---- | Fold 2
        5;      |
        break;- |
}
```

The folding should not the based on the `break`; everything between the cases would be considered a range
