### ISSUE TITLE
getOutliningSpans - Return spans for multiline template strings 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#23382]
From https://github.com/Microsoft/vscode/issues/47667

**TypeScript Version:**  2.9.0-dev.20180409

**Search Terms:** 
- getOutliningSpans
- fold / folding
- template string

**Code**
Try folding the code:

```ts
const x = `a
     multi
  line
string
`
```

**Request**
`getOutliningSpans`  should return a span for the multiline template string

**Comment by xgqfrms** [comment]
https://github.com/xgqfrms/vscode/issues/8

**Comment by xyzdata** [comment]
# OK

> javascriptreact

```js

    "[javascript]": {
        "editor.formatOnSave": false,
        "editor.formatOnPaste": false,
        "editor.renderWhitespace": "all",
        "editor.foldingStrategy": "indentation",
        // "editor.foldingStrategy": "auto"
        "editor.getOutliningSpans": ""
    },
    "[javascriptreact]": {
        "editor.formatOnSave": false,
        "editor.formatOnPaste": false,
        "editor.renderWhitespace": "all",
        "editor.foldingStrategy": "indentation"
    },

```

**Comment by huongdevvn** [comment]
- Go to Settings
- Search: `folding`
- Change **Folding Stategry** from `auto`  to `indentation`

<img width="512" alt="Screen Shot 2019-06-18 at 4 19 50 PM" src="https://user-images.githubusercontent.com/45929865/59669721-f0cc4280-91e4-11e9-9c70-84f7740b5bd4.png">


<img width="1051" alt="Screen Shot 2019-06-18 at 4 18 44 PM" src="https://user-images.githubusercontent.com/45929865/59669675-d98d5500-91e4-11e9-98c5-8dfd72be70cd.png">

**Comment by tysonmatanich** [comment]
Setting `"editor.foldingStrategy"="indentation"` is **not** an acceptable workaround for JSX development. Yes it enables folding of template strings, however at the expense of other unwanted results which are even worse.

In the case of the `div` below, it will fold the start tag instead of the entire element:
```jsx
- <div
    attr1="value"
    attr2="value"
  >
    <span>some content</span>
  </div>
```
Folding results in the following:
```jsx
+ <div
  >
    <span>some content</span>
  </div>
```
Instead of what is desired with `"editor.foldingStrategy"="auto"` :
```jsx
+  <div...
```
Shocked this still isn't fixed.

**Comment by DanielRosenwasser** [comment]
Thanks @Kingwl!

**Comment by serpenteagle** [comment]
> Setting `"editor.foldingStrategy"="indentation"` is **not** an acceptable workaround for JSX development. Yes it enables folding of template strings, however at the expense of other unwanted results which are even worse.
> 
> In the case of the `div` below, it will fold the start tag instead of the entire element:
> 
> ```js-jsx
> - <div
>     attr1="value"
>     attr2="value"
>   >
>     <span>some content</span>
>   </div>
> ```
> 
> Folding results in the following:
> 
> ```js-jsx
> + <div
>   >
>     <span>some content</span>
>   </div>
> ```
> 
> Instead of what is desired with `"editor.foldingStrategy"="auto"` :
> 
> ```js-jsx
> +  <div...
> ```
> 
> Shocked this still isn't fixed.

This.. Just add template literal folding to auto in JS/TS. It shouldn't be that hard...

**Comment by tettoffensive** [comment]
I'm confused as to whether there is a solution for this (that is not `"editor.foldingStrategy"="indentation"`). In my case I'm trying to find a way to fold blocks inside graphql-tag template literals:

```ts
const query = gql`
query myQuery(...) {
  user(id: $userId) {
    ...
  }
}
`;
```

**Comment by adrianpcloud** [comment]
@tettoffensive yo brother have you found a solution for folding js graphql queries?
