### ISSUE TITLE
Incorrect behaviour for class methods redefenition

### ISSUE THREAD

**Issue by awinogradov** [Microsoft/TypeScript#23394]
**Search Terms:**
class, methods

**Code**

Firstly, u can see this problem if you use a pattern of redefinition methods in children class which has a declared type of returning value.

```ts
class Base {
  method(): string {
    return 'mystring'
  }
}

class Children extends Base {
  method(): number {
    return 1;
  }
}
```

**Expected behavior:**
No errors, it's fully redefinition.

**Actual behavior:**
Error: Type 'number' is not assignable to type 'string'.

Secondly, u can see the same problem with the methods args.

```ts
class Base {
  method(arg: string) {
    return arg
  }
}

class Children extends Base {
  method(arg: number ) {
    return arg;
  }
}

// BUT

class Children2 extends Base {
  method(arg) { // <--- any
    return arg;
  }
}
```

**Expected behavior:**
No errors, it's fully redefinition.

**Actual behavior:**
Error: 
Types of parameters 'arg' and 'arg' are incompatible.
Type 'string' is not assignable to type 'number'.

**Comment by MartinJohns** [comment]
```
const instance: Base = new Children();
instance.method(????);
```

What would you pass? The type `Base` clearly states it accepts a `string`, but the actual instance overwrote the method accepting a `number`.

The behavior works as intended.

**Comment by awinogradov** [comment]
Thanks for the answer!

@MartinJohns I can agree with the first case of methods value because it can be called in different places of the base class. But I don't agree with the second case of arguments types. In the children class, all arguments of a redefined method have any type. But I can't declare another one type them. If I can't change it why it's not inherited by default?

**Comment by RyanCavanaugh** [comment]
Derived classes can accept wider types than their base types, as is described by substitutability. Please read the FAQ and/or ask questions on StackOverflow.
