### ISSUE TITLE
noUnsedLocals and aliased types used as function arguments bug

### ISSUE THREAD

**Issue by mohsen1** [Microsoft/TypeScript#23392]
**Search Terms:** 
Salsa, noUnsedLocals, import
**Code**

I could not simplify this to a smaller code. It is happening at webpack here:
https://github.com/mohsen1/webpack/blob/ddb4b9efa41e9605256ab3339d0da688035769cf/lib/Module.js#L14-L30

```ts
/** @typedef {typeof import("./Chunk")} Chunk */

/** @typedef {typeof import("./RequestShortener")} RequestShortener */

/** @typedef {(requestShortener: RequestShortener) => string} OptimizationBailoutFunction */

/** @type {OptimizationBailoutFunction} */
var fn = (a) => { return {} }

```

**Expected behavior:**
No Error 
**Actual behavior:**

Error

```
 error TS6133: 'RequestShortener' is declared but its value is never read.

16 /** @typedef {typeof import("./RequestShortener")} RequestShortener */
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

**Related Issues:**
https://github.com/webpack/webpack/pull/7033/

**Comment by mhegazy** [comment]
@weswigham can you take a look. not sure if we should even report these errors on jsdoc comment declarations

**Comment by weswigham** [comment]
@mhegazy I think the error is valuable (since it's a lint enabled by `noUnusedLocals` - it's optional and should be complete) - we just weren't visiting typedef types to mark visibility.
