### ISSUE TITLE
Constant cpu usage on windows caused by electron_node typingsInstaller.js tsserver.js typesMap.js

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#23390]
_From @zfeher on April 12, 2018 11:55_

- VSCode Version: 1.22.1
- OS Version: Windows 10 1709 16299.371

Steps to Reproduce:

This happens when I am opening our repo. I need to wait a while max 1-2 minutes and the process will be there and it will cause 10-17% constant cpu usage. My telemetry settings are turned off completely.

Opening an empty code instance doesn't produce this behavior.

The exported status: [vscode-status.txt](https://github.com/Microsoft/vscode/files/1902951/vscode-status.txt)

The command line of the process:
```
"C:\Program Files\Microsoft VS Code\Code.exe" "c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib/typingsInstaller.js" --globalTypingsCacheLocation C:/Users/zfeher/AppData/Local/Microsoft/TypeScript/2.8 --enableTelemetry --typesMapLocation "c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js/../typesMap.json" 
```

Does this issue occur when all extensions are disabled?: Yes

_Copied from original issue: Microsoft/vscode#47735_

**Comment by mjbvz** [comment]
@zfeher  In the latest vscode insiders, can you please try collecting the typings installer logs to help us investigate this issue:

1. In VS Code: `"typescript.tsserver.log": "verbose"`
1. Restart vscode and reproduce the issue
1. In VS Code, run the `TypeScript: Open TS Server log` command
1 This should open a folder with a `ti-xxx.log` file in it. That is the typings installer log

If you can share that log file, I or someone on the TS team can try looking through them to see what is going on

⚠️Warning: The TypeScript log may include information from your workspace, including file paths and dependency  names. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by zfeher** [comment]
@mjbvz here is the ti log (+ the ts server log as well) from the current insider version (here too I disabled the telemetry everything else is the default):

[ti-13372.log](https://1drv.ms/u/s!Amp7enGCua2jgQfMg8slE_oGilUX)
[tsserver.log](https://1drv.ms/u/s!Amp7enGCua2jgQiHqcwEmbHGnbx_)

**Comment by sheetalkamat** [comment]
From TI log it looks like typing installer is watching about 1200 locations of ```node_modules``` and ```bower_components``` and the watches using polling resulting in cpu usage.

**Comment by zfeher** [comment]
Hmmm that is interesting because `node_modules` is excluded by default as far as I know. Also I've tried to open the same repo with removing the `node_modules` and the issue still occured.

**Comment by mhegazy** [comment]
@sheetalkamat why are not we just using a folder watcher for all of these entries?

**Comment by zfeher** [comment]
Is this fix included in the current (2018-04-20T05:17:25.189Z) insider version? Because I checked this version and the issue still occurs. The log file changed a bit though.

[ti-16368.log](https://1drv.ms/u/s!Amp7enGCua2jgQoqvpGWGrGXcYEi)
[tsserver.log](https://1drv.ms/u/s!Amp7enGCua2jgQsP0NvsbSu1D9DN)

**Comment by sheetalkamat** [comment]
@zfeher Your logs shows you are using typescript@2.8.3 which doesn't include this fix. You want to try typescript@next

**Comment by zfeher** [comment]
@sheetalkamat thanks for pointing this out. Tried it again and the fix seem to be working. Thank you.
