### ISSUE TITLE
Refactoring: add braces to arrow function

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#23402]
Insightfully suggested in #23299 by @zaaack:

> +1. Add braces is very useful, too.

Then substantiated further by @zuozijian3720:

> +1. Add braces is very useful, too.

**Comment by shishiranshuman** [comment]
May I work on this issue?

**Comment by oliverjanik** [comment]
And remove?

**Comment by oliverjanik** [comment]
This is awesome!
