### ISSUE TITLE
Wrong auto imports (regression)

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#23410]
With Node 9.8.0.

cc @andy-ms 

**TypeScript Version:**  2.7.0-dev.20180414

**Search Terms:** 

**Code**

1. clone https://github.com/falsandtru/typed-dom
1. open index.ts
1. type `concat`

**Expected behavior:**

Suggest auto imports from `spica/concat`.

**Actual behavior:**

Suggest auto imports from `.`.

**Playground Link:**  

**Related Issues:** #23230?

**Comment by andy-ms** [comment]
This seems to work with `typescript@next`. I get auto imports from `spica/concat` and `spica/monad/sequence/member/static/concat`, but not from `.`.
My node version is `9.9.0` (though that shouldn't matter).

**Comment by falsandtru** [comment]
I'm using the same version (20180414) and updated Node to v9.11.1 on Win10, but not fixed yet. Did you check on Windows?

**Comment by falsandtru** [comment]
In https://github.com/falsandtru/securemark, wrong auto import source is `typed-dom`, not `.`.

**Comment by mhegazy** [comment]
@falsandtru can you give `typescript@next` tonight another try?

**Comment by falsandtru** [comment]
With typescript@2.9.0-dev.20180426, https://github.com/falsandtru/typed-dom is fixed but https://github.com/falsandtru/securemark is not.

**Comment by falsandtru** [comment]
@andy-ms Can you take a look at that?

**Comment by andy-ms** [comment]
@falsandtru Could you try again with `typescript@next` now that #23811 is in?
