### ISSUE TITLE
Promise.reject should be callable with no parameter

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#23416]
**TypeScript Version:**  master

**Search Terms:** 

**Code**

```ts
    reject(reason: any): Promise<never>;
    reject<T>(reason: any): Promise<T>;
    resolve<T>(value: T | PromiseLike<T>): Promise<T>;
    resolve(): Promise<void>;
```

**Expected behavior:**

```ts
    reject<T = never>(reason?: any): Promise<T>;
```

**Actual behavior:**

```ts
    reject(reason: any): Promise<never>;
    reject<T>(reason: any): Promise<T>;
```

**Playground Link:**  

**Related Issues:**

**Comment by MartinJohns** [comment]
Then it should really be `Promise<undefined>` instead, as that is the value you will actually get.

**Comment by rbuckton** [comment]
@MartinJohns actually, `never` is better as you will never actually get the value. We allow you to fill in a type explicitly, but we default to `never` for a number of other reasons as well, such as return type inference in async functions.

**Comment by rbuckton** [comment]
Why does `reason` need to be optional? Its true that if it is not provided the value `undefined` is used, but requiring the parameter avoids a common user footgun of "I forgot to fill in the reason". I'm not convinced this is a bug.

**Comment by falsandtru** [comment]
Calling Promise.reject without `reason` is allowed and basic usage. So optional `reason` is needed for compatibility with plain JS and reflecting the ES spec.

**Comment by rbuckton** [comment]
Also, the ES Spec defines the `length` of `Promise.reject` as `1`. There are a number of other places where the ES Spec allows more values than we do in TypeScript (such as the `p` argument for `Object.defineProperty`). The advantage we have with TypeScript is that we can leverage the type system to help users avoid common mistakes.

I would argue that it would be rare for someone to write `Promise.reject()` without providing a reason, as it significantly reduces your ability to differentiate why a promise was rejected. This is akin to `throw undefined`. We don't disallow `throw undefined` (just as we don't disallow `Promise.reject(undefined)`), though that is generally considered bad practice.

Is there a specific case you are running into that necessitates this definition (i.e. assignability, etc.)?

**Comment by falsandtru** [comment]
Just to make failure state.

```ts
Promise.resolve()
  .then(() => Promise.reject());
```

We don't always have a need for the details of the failure.

**Comment by falsandtru** [comment]
Another, can you also take a look #22772? This also make a parameter required in Promise constructor. The current Promise constructor is not type safe. I think you'll want this fix.

**Comment by rbuckton** [comment]
After a quick review it seems that we allow the reason to be elided in the `reject` callback passed as part of the `Promise` constructor.

**Comment by falsandtru** [comment]
Thanks for your review. Can we discuss it in #22772?

**Comment by falsandtru** [comment]
About https://github.com/Microsoft/TypeScript/issues/23416#issuecomment-382214858, Promise.resolve is also optional. If you are right, we have to fix Promise.resolve too. Do you want/mean it?

**Comment by rbuckton** [comment]
I'm not sure I understand? The definition for `Promise.resolve` seems fine. I have changed my opinion from https://github.com/Microsoft/TypeScript/issues/23416#issuecomment-382214858 with respect to `Promise.reject` only.

**Comment by falsandtru** [comment]
I mean `Promise.resolve` signature allow to call myself with no parameter. So if you don't allow to call `resolve`/`reject` method with no parameter, `resolve` has a larger problem than `reject`. However, this problem is not type level anyway. `Promise` interface doesn't have the failure value type. So I believe `reason` parameter should be checked by lint.

**Comment by rbuckton** [comment]
`Promise.resolve` already has an overload that allows it to be called without an argument.
