### ISSUE TITLE
Files starting with "Node" are not excludable

### ISSUE THREAD

**Issue by manuth** [Microsoft/TypeScript#23417]
**TypeScript Version:**  2.9.0-dev.20180414

**Search Terms:** glob patterns, glob patterns files starting with "Node"

**Code**
*tsconfig.json:*
```json
{
    "compilerOptions": {
        "target": "es6",
        "module": "commonjs",
        "sourceMap": true
    },
    "exclude": [
        "node_modules",
        "**/templates"
    ],
    "compileOnSave": true
}
```

**Expected behavior:**
All files inside any `templates`-folder should not be compiled.

**Actual behavior:**
All Files inside the `templates`-folder are excluded **but** files starting with `Node` (for instance `NodeContainer.ts`) are _not_ excluded and will be compiled by `tsc`.

**Comment by andy-ms** [comment]
Could you try to come up with a complete example? I tried reproducing this but `templates/NodeContainer.ts` was correctly not compiled.

**Comment by manuth** [comment]
Thanks for the fast reply

It's happening in my repo called [WSCPackageGenerator](https://github.com/manuth/WSCPackageGenerator). 
Node.ts and NodeContainer.ts located at /generator/app/templates/lib are getting compiled.

**Comment by manuth** [comment]
Aaaah understood
Sorry I haven't really noticed I m have this import-expression there...
It's actually not supposed to be here :sweat_smile:
