### ISSUE TITLE
During await, variables are wrongly assumed not to change

### ISSUE THREAD

**Issue by hvenev** [Microsoft/TypeScript#23411]
This happens using tsc 2.8.1 and 2.9.0-dev.20180414.

```ts
async function f() {
    let x: number = 0;
    if(x !== 0) throw new Error();

    await Promise.resolve().then(() => {
        x = 5;
    });

    if(x !== 5) throw new Error();
}

f().then(() => {
    console.log("Done");
});
```

```
$ tsc a.ts --target es2017 --lib es2017,dom
test.ts(9,8): error TS2365: Operator '!==' cannot be applied to types '0' and '5'.
```

Here `tsc` assumes that during the `await` the value `x` remains the same. During `await` statements, lots of things can happen (including execution of code entirely unrelated to the thing being awaited). Here is a more contrived example:

```ts
interface Datum {
    value: number;
}

const box: Datum = {value: 0};

function f1() {
    Promise.resolve().then(() => {
        box.value = 1;
    });
}

async function f2() {
    if(box.value !== 0) throw new Error();
    await Promise.resolve();
    if(box.value !== 1) throw new Error();
}

f1();
f2().then(() => {
    console.log("Done");
});
```

Both programs print `Done` when I run them using Node.js 8.11.0

**Comment by j-oliveras** [comment]
Duplicated or related to #9998.

**Comment by hvenev** [comment]
I think this is an instance of #9998, where the compiler is overly optimistic and assumes that `await` does nothing.

**Comment by DanielRosenwasser** [comment]
Thanks for spotting that out @j-oliveras
