### ISSUE TITLE
Watch mode sometimes watches files that aren't targeted for compilation, depending on installed packages

### ISSUE THREAD

**Issue by dguo** [Microsoft/TypeScript#23414]
**TypeScript Version:**  2.8.1

I also tried with `typescript@next`, but the issue persisted.

**Search Terms:** 
too many files watched in watch mode

**Code**
I created a [repo](https://github.com/dguo/tsc-watch-bug) that is as minimal as possible while still demonstrating the problem. Details are in the README.

**Expected behavior:**
When giving `tsc` specific files to compile, watch mode should only check for recompilation when those files are changed.

**Actual behavior:**
With the dependencies in the repo's `package.json`, watch mode recompiles when other files are changed, like `package.json`, a JS file in the top level directory, or a JS file within `node_modules`. This occurs even though none of the dependencies are used by the file that is targeted for compilation. Removing any of the dependencies fixes the problem.

**Playground Link:** N/A

**Related Issues:** #7211

Trying to debug this issue would have been easier if there was a way to get more insight into the `watch` mode. I don't think there's a way to get `tsc` to list which files are being watched or which file triggered a recompilation.

**Comment by mhegazy** [comment]
`@types` packages in your `typeRoot` are included by default. so every-time you do `npm install` a new compilation needs to be triggered. if you do not want these types to be added in your context use `--types` or `"types": []` in your tsconfig.json.

Also you can use `tsc --listFiles` to see what files were included in your compilation.

**Comment by dguo** [comment]
Thanks for the info. The issue I'm experiencing is more that the list of files in my compilation doesn't seem to match up with the list of files that are watched by `tsc`.

In my example repo, if I change `bar.js` in the top level directory, recompilation is triggered, even though `bar.js` doesn't show up in the output of `tsc --listFiles`. Even changing a JS file in `node_modules` triggers it, and the file is not in a `@types` package.

**Comment by mhegazy** [comment]
>  Even changing a JS file in node_modules triggers it, and the file is not in a @types package.

that is since we the `@types` are included automatically, so `node_modules` need to be watched.

In general watching more files should be OK, and watch implementation in 2.7 and later is optimized to only triggered needed work. Is there a specific scenario where you are seeing issues due to watchers?

**Comment by dguo** [comment]
It's not a huge deal. It's just mildly annoying to see the "File change detected" message whenever I change an unrelated file. I can understand why `node_modules` would have to be watched, but it doesn't make sense that `bar.js` is being watched as well. 

I'm also very curious about the root cause. I don't understand why removing a particular dependency would fix the issue in terms of `bar.js` being watched when it doesn't even import anything.

I understand that this doesn't seem like an important issue, but the behavior still seems like a small bug, given that the documentation for the watch flag says that it watches "input files", and the `tsconfig.json` in the repo does not include `bar.js`. I'm not very familiar with the intricacies of file watching, but I'd be concerned that watching irrelevant files can chew up system resources unnecessarily.

**Comment by mhegazy** [comment]
@sheetalkamat can you take a look.

**Comment by sheetalkamat** [comment]
Note that on most OS the file save is emitted as file remove and add hence the directory watchers are invoked. We are watching the root directory for any new modules additions. Your program has 263 files in it and we cap at 250 to go through each file to actually check if the added file is definitely changing the module resolution. And hence you see the program changed detected message. note the the new program creation will be faster in many cases compared to figuring out if the file added/removed is going to affect the module resolution.
```
DirectoryWatcher:: Triggered with c:/temp/tsc-watch-bug/bar.js:: WatchInfo: c:/temp/tsc-watch-bug 1 Failed lookup locations
Scheduling program update
Elapsed:: 1ms DirectoryWatcher:: Triggered with c:/temp/tsc-watch-bug/bar.js:: WatchInfo: c:/temp/tsc-watch-bug 1 Failed lookup locations
```

**Comment by dguo** [comment]
That is very enlightening. Thank you for looking into it, @sheetalkamat. I appreciate it.
