### ISSUE TITLE
Module Resolvation Problem

### ISSUE THREAD

**Issue by ismailbayram** [Microsoft/TypeScript#23421]
My export file in the core module
```
// Components
import Header from "./components/partials/Header";

const components = {
  partials: {
    Header
  }
};

export { components };
```

My App file in the project
```
import * as React from "react";

import { components.partials.Header } from "core/export";

export default class App extends React.Component {
  render() {
    return <Header classes="header test" />;
  }
}
```

So it occurs an error

But if I write like below, it works
```
// ....
import { components } from "core/export";
let Header = components.partials.Header;
```

But I want it to works like snippet on the top.

**Comment by DanielRosenwasser** [comment]
This is the way ECMAScript module syntax was specified, so it's not something TypeScript will be adding to the language. Named imports can only bring in *Identifier*s.
