### ISSUE TITLE
interface Node leakage

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#2342]
Seems like the interface Node is already defined somewhere before compiling the application code.

```typescript
interface Node {
	name: string
}

interface ExtendedNode extends Node {
	hello: string
}

function test(): ExtendedNode {
	return {
		name: 'Tingan',
		hello: 'hej'
	}
}
```

```
test.ts(11,10): error TS2322: Type '{ name: string; hello: string; }' is not assignable to type 'ExtendedNode'.
  Property 'nodeType' is missing in type '{ name: string; hello: string; }'.
```

http://www.typescriptlang.org/Playground#src=interface%20Node%20%7B%0D%0A%09name%3A%20string%0D%0A%7D%0D%0A%0D%0Ainterface%20ExtendedNode%20extends%20Node%20%7B%0D%0A%09hello%3A%20string%0D%0A%7D%0D%0A%0D%0Afunction%20test()%3A%20ExtendedNode%20%7B%0D%0A%09return%20%7B%0D%0A%09%09name%3A%20'hej'%2C%0D%0A%09%09hello%3A%20'nfei'%0D%0A%09%7D%0D%0A%7D%0D%0A

**Comment by CyrusNajmabadi** [comment]
'Node' is already defined in lib.d.ts.  

```ts
interface Node extends EventTarget {
    nodeType: number;
    previousSibling: Node;
```

**Comment by tinganho** [comment]
@CyrusNajmabadi  I guess `lib.d.ts` is included every time I compile. And I guess Node interface is referencing something in the HTML landscape? Why isn't it in `lib.dom.d.ts` ?

**Comment by basarat** [comment]
@tinganho It's also got stuff for strings , numbers etc
