### ISSUE TITLE
Suggestion: RegExp as Tuple

### ISSUE THREAD

**Issue by mhverbakel** [Microsoft/TypeScript#23425]
Hello all,

After running into https://github.com/Microsoft/TypeScript/issues/17053 I started thinking about a solution for this problem. I came up with the following proposal to improve `RegExp`  usage:
```ts
interface TypedRegExp<T> extends RegExp {
    exec(string: string): (T & { index: number; input: string; }) | null;
}
```
`TypedRegExp<T>` extends `RegExp`, so this is not a breaking change. However, either manually (by casting) or using inference (by compiler), `T` can be a tuple.

Example usage:
```ts
const regex = /(a)(b)?(c)/ as TypedRegExp<[string, string, string | undefined, string]>;
const [, a, b, c] = regex.exec("ac");
// a: string = "a"
// b: string | undefined = undefined
// c: string = "c"
```

**Advantages**
- Type inference on RegExp is nice, the current typing is very weak.
- It can be implemented as a non-breaking change.
- It resolves #17053

**Disadvantages**
- The tuple must always have a first value of `string`, as this contains the whole match, but there is no compiler constraint to express this.
- The tuple should only consist of `string` or `string | undefined`, but there is no compiler constraint to express this.

**Comment by mhverbakel** [comment]
I was wrong, the type inheritance should be the other way around. Every property should be on TypedRegExp, and then RegExp should inherit from that:

```ts
interface TypedRegExp<T extends (string | undefined)[]> {
    ....
}

interface RegExp extends TypedRegExp<string[]> { }
```

**Comment by mhegazy** [comment]
We have really stayed out of the regexp space, intentionally. The amount of work involved to get it typed correctelly is rather high (given that the compiler runs on es3 engines), and the value provided is rather small to warrant the investment.

**Comment by mhverbakel** [comment]
I can see how inferring RegExp types is a big investment, but - in my opinion - there are some quick wins:
* If the character `(` is not found, the type will automagically become `TypedRegExp<[string]>`, indicating there are no capture groups.
* If the string `)?` is found, the type will automagically become `TypedRegExp<(string | undefined)[]>`, indicating capture groups may be optional
* In all other cases, the type will be `TypedRegExp<string[]>` or `RegExp`, to indicate that there are no optional capture groups.

This is not the fully featured RegExp interpreter yet, but it at least gives you some checking against your regular expressions.

**Comment by mhegazy** [comment]
I am not arguing there is value in checking the regexp. i am saying the cost to implement and maintain a regexp analyzer on an engine that does not support all regexp features does not warrant the value added.
