### ISSUE TITLE
Consider combining the "Found X error(s)" and "Compilation" complete --pretty messages

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Microsoft/TypeScript#23424]
After dogfooding this feature for a couple of weeks, it's a little annoying having ~3 fewer lines of errors visible per screen. 

```text
[01:23:45] Found 3 errors.


[01:23:45] Compilation complete. Watching for file changes.
```

How about we combine them into one line?

```text
[01:23:45] Found 3 errors. Watching for file changes.
```

Mentioned but not implemented in https://github.com/Microsoft/TypeScript/pull/22254.

**Comment by mhegazy** [comment]
seems like a good idea. want to send a PR for it?
