### ISSUE TITLE
TS Server assumes editors work uniformly wrt file encoding and newlines.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [microsoft/TypeScript#2343]
Issue 1:

TS Server breaks text into lines using the ts.computeLineStarts function.  However, this function is intended for use only by the compiler to indicate what ecmascript believes a newline should be.  This view of what newlines are may or may not match what an Editor thinks a newline is. For example Ecmascript treats 0x2029 (paragraph separator) as a newline.  Different editors may not interpret that character in the same way.

This is problematic as the server API is Line/Column based.  So the server produces results that include line/character information _from the perspective of the server_ which may not correspond to actual lines/character from the perspective of the client.

For example, say the file contents are:

"foo`paragraph separator`bar`new line`quux".   TSServer will interpret this as two lines, whereas a client may only view it as a single line.  If TS server then reports an issue with the 'b' in 'bar' it will report the issue at "Line 2, column 1".  However, the client will intepret that as being an the line with 'quux'. 

This will affect all features that work with line/column information (effectively, nearly the entire API).  It is also a significant issue for features that mutate the buffer (like formatting).  If the client/server disagree on line endings, then corruption will occur when edits happen.

There are several ways to address this.  The way we deal with this right now in VS is to not ever use the server for line/char information.  Instead, we just let the client tell us what the file contents are, and we report all information with unambiguous information about positions in that file content.  The client then maps those positions to the line/chars that it represents the file as.

Ideally, we would do the same here.  Note: this should work fine for Sublime.  Sublime already has a 'point' based API, and is already able to map between 'points' and "rowcol" (in their parlance).

Issue 2:
In a similar manner to issue 1, the ts server uses the compiler reading functions to read files off disk.    This means we get the interpretation of the file that is produced by sys.readFile.   However, this may not match how the client has read the file.  The client may have interpreted the file a different manner (for example, how it handles BOM, or if it does things like converting newlines characters, etc.).   As such, the information the server returns about the file may not match how the client views the file.

As before, we don't have this issue in VS because we allow VS to provide the canonical representation of the file.  This would be the ideal way to deal with this for the server.  We should just let the client send us its representation of the file, and then use that from then on.  This should require very little overhead (pipes are fast enough to easily handle this), and should ensure a consistent representation across the client and server, preventing incorrect results and, mor importantly, data corruption.

**Comment by CyrusNajmabadi** [comment]
Note: we've investigated the situation for Sublime, Emacs and VI.  Each has a relevant API for mapping between a file character index to a line/col, and back again.

Sublime:
Character index to line and column: rowcol(point).
Line and column to character index: text_point(row, col).

Emacs:
Character index to line and column: 

(current) Character index: (point)

**Comment by mhegazy** [comment]
pinging @steveluc for this one.

**Comment by steveluc** [comment]
Thanks @CyrusNajmabadi.   Our plugins do use those APIs.  Emacs, for example, reports changes in terms of character offset and we use the Emacs API to convert those to line/offset. 

Although the issues you list above have not been encountered in practice, we will need to address them for editors that may have a different approach to line breaking.

Fixing this is on the roadmap, and as you point out the most likely fix is to communicate with editors in terms of character offset from the beginning of the buffer, and to ship the buffer always directly from the editor.

**Comment by CyrusNajmabadi** [comment]
@steveluc Sounds good!
