### ISSUE TITLE
Correctly resolving modules from packages that contain both JS and TS code

### ISSUE THREAD

**Issue by atrauzzi** [Microsoft/TypeScript#23431]
_I really want to apologize if this is a duplicate. There are so many ways to express our "wants" as users of such a popular library. I suppose this is the price of fame for you guys, but rest assured, I do my best to adopt any corrections to terminology that help my future searches be more efficient!_

---

I've been publishing packages using TS to quite good effect for some time now.  One thing I've been wondering about is whether there could be a way for me to overlap the module resolution.  This would be so that if TS code is available, the TS compiler would catch on and include the TS code provided, and if not, it would then fall back to the nodejs/npm/whatever package resolution rules.

So, that is to say, given the package above, where `src` in the [repository](https://github.com/atrauzzi/protoculture) contains `ts` and `lib` in the [package](https://www.npmjs.com/package/protoculture) contains [compiled](https://travis-ci.org/atrauzzi/protoculture) `js`, instead of having to write:

```typescript
import "protoculture/src/Shims";
// -or-
import "protoculture/lib/Shims";
```

To get the TypeScript version of the code, I'm wondering if it could be made so that I simply write:

```typescript
import "protoculture/Shims";
```

_(note, `src` is also available with the distributed package)_

This scenario would be interesting because in the case of this `Shims` file, it doesn't export anything and therefore can't be included in my `index.js` file.  But, in the case of consuming my own libraries, I know I'm using TypeScript and feel like as a result I should be able to consume the library "raw".

**Comment by mhegazy** [comment]
We do not recommend distributing the source. I am not talking about including the source in your npm package, i am talking about asking your users to include and transpile the sources of your application along with their own code. What we recommend is you compile your sources, publish a .d.ts and .js files.

**Comment by atrauzzi** [comment]
I guess my thought here is that if the project I'm consuming a package from is based on TypeScript, couldn't it benefit from any kind of optimizations by being able to link up the library to the initial build graph?

**Comment by mhegazy** [comment]
> couldn't it benefit from any kind of optimizations by being able to link up the library to the initial build graph?

No. the TS compiler does not do any optimizations, so there is no positive side to it. there is a negative side though; including the sources means 1. every user has to rebuild it along with their sources, so longer build times, 2. different configurations between your project and your users' projects means different errors/behaviors in your sources that your users have no way to fix, since it is not their source, and 3. your users have to use the same version of TS as you to avoid breaking their build.
