### ISSUE TITLE
Bake in Immutable.js into objects using readonly interfaces.

### ISSUE THREAD

**Issue by ericp96** [Microsoft/TypeScript#23436]
# Leverage the type system for "native-like" immutability with perf enhancements

## History
Many SPA frameworks rely on frequent equality checks to determine whether or not they should update.  These equality checks can lead to jank if not kept shallow.  As a result, many immutability is commonly being seen as a best practice.

Libraries such as Immutable.js provide the benefits of shallow equality checks while limiting overhead of deep copies through sharing object references via tries and the effective use of hashing.

## Proposal
Typescript has the ability to determine the type of an object, could prevent object mutation, could share the same object sharing and retrieval on deeply nested structures that existing libraries already have.

TypeScript could allow for the impementation of an interface, very much like `ReadOnly`, that would mark a class as being immutable:

```
class Dog implements Immutability {
    breed: string,
    legs: number[];
}

var bassetHound = new Dog(); // an immutable record
```

TypeScript could then polyfill optimizations for interacting and using this object:

Pretranspiled code:
```
bassetHound.breed = 'Basset Hound';
```
Would turn into:
```
tsUtil.set(bassetHound, 'breed', 'Basset Hound');
```
Where the breed property is set, and bassetHound is now a new object.

TypeScript would throw an error if an invalid attribute were being read or set:
```
bassetHound.earLength = 21; // throws an exception
```

Additional benefits could be leveraged through the invocation of functions on these structures:
```
bassetHound.legs.map(x => x).filter(x => x).map(x =>x)
```
Where map and filter can now be defined via typescript to yield the fastest possible performance.

**Comment by RyanCavanaugh** [comment]
TypeScript doesn't do features which require type-directed emit or change the semantics of existing JS constructs.
