### ISSUE TITLE
Methods are converted into properties (in Intellisense at least) when put through a type mapping.

### ISSUE THREAD

**Issue by JabX** [Microsoft/TypeScript#23450]
**TypeScript Version:**  2.8.1 (but it always has been like this)

**Search Terms:** Mapped types, Conditional types, methods, properties

**Code**
<img src="https://user-images.githubusercontent.com/3266897/38838836-59f5b722-41d8-11e8-8dec-8267fea3ad4b.png" height="200" />

**Expected behavior:**
The second tooltip displays `(method)`.
**Actual behavior:**
It displays `(property)`

Basically, everything that goes through a type mapping of some sort ends up as a property, regardless of that it was before. While this was more or less fine with simple mapped types, because they were used for simple things where you have a lot of control, I feel it's getting a bit out of hand with conditional types.

Like this:

<img src="https://user-images.githubusercontent.com/3266897/38839090-4cf03b46-41d9-11e8-9b14-6b2a31e898a4.png" height="250" />

I've written a simple mapping that transform a few properties into something else, and leaves alone all the others. Here, I've used it with some type that extends Array, and this is what I get.

I understand that it might not be always right to transform methods into methods, especially since methods can't be readonly or optional (thus my initial example is working as intended, but it was the simplest way I could find to showcase the issue). A "simple" fix could be to treat separately the case where a property/method goes unchanged through a mapping (like `{[P in keyof T]: T[P]}`), and in that case to copy the initial property/method over.

I'm saying this with no real knowledge of how the compiler works here, so maybe it's not so simple and the feature isn't worth the effort. But if it is, well that would be a nice thing to have :)

**Comment by mhegazy** [comment]
Is this issue just about how the methods show in the completion list/quick info, or are there other observable effects of the mapping operation?

**Comment by JabX** [comment]
I'm not sure if there are any other effects to this, but yes, my issue is only about the way the methods are shown in the completion list.

**Comment by mhegazy** [comment]
that seems like a simpler problem to fix. Today we use the symbol kind to decide whether it is a method or not, we can instead use the declaration. this way we can still go through mapping operations and mark them the same way..
