### ISSUE TITLE
@template tag is not visible in class body

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#23459]
Found playing with https://github.com/lukeed/tmp-cache

```ts
// @ts-check

/**
 * @template {T}
 */
class Foo {
    /**
     * 
     * @param {T} x 
     */
    foo(x) {	
    }
}
```

This will give the following error on `T` in the `@param` tag.

```
Cannot find name 'T'.
```

**Comment by sandersn** [comment]
`@template` just didn't work at all for classes. The fix is up at #23511.
