### ISSUE TITLE
Can't use typeof for an ambient external module type.

### ISSUE THREAD

**Issue by rotemdan** [Microsoft/TypeScript#2346]
I need to get type information for a CommonJS module that's dynamically (and sometimes conditionally) loaded within the scope of an internal module. Some background on why this is important (and the hoops I go through to work around this restriction today) here: https://github.com/Microsoft/TypeScript/issues/2327#issuecomment-78869985

(TL;DR: my current workaround is to transform the external module declaration file to an internal module declaration file, using several regular expressions, here's one I did for node.d.ts (with the RegExps I used in the comments): https://github.com/rotemdan/lzutf8.js/blob/master/LZUTF8/Library/Dependencies/node-internal.d.ts)

This works (with correct intellisense):
```ts
declare module InternalModule
{
	export var member: number;
}

module Test
{
	var internalModuleInstance: typeof InternalModule = SomeInternalModule;
}
```
But this:
```ts
declare module "ExternalModule"
{
	export var member: number;
}

module Test
{
	var externalModuleInstance: typeof ExternalModule = require("SomeExternalModule");
}
```
or even this:
```ts
declare module "ExternalModule"
{
	export var member: number;
}

var externalModuleInstance: typeof ExternalModule = require("SomeExternalModule");
```
Results in
```
Error: Cannot find name 'ExternalModule'
```

**Comment by rotemdan** [comment]
I found this in the handbook:
http://www.typescriptlang.org/Handbook#modules-optional-module-loading-and-other-advanced-loading-scenarios

It is claimed that ```import x = require("y")``` will not emit anything unless referenced in a value position. Well I assumed that using the keyword ```require``` would immediately translate to an actual call to ```require``` but apparently I was wrong? So quite unexpectedly:

ExternalModule.d.ts:
```ts
declare module "ExternalModule"
{
    export var member: number;
}
```
App.ts
```ts
import ExternalModule = require("ExternalModule");

module Test
{
      if (false)
          var externalModuleInstance: typeof ExternalModule = require("SomeExternalModule");
}
```
emits
```js
var Test;
(function (Test) {
    if (false)
        var externalModuleInstance = require("SomeExternalModule");
})(Test || (Test = {}));
```
Seems like the ```import``` can be used to only "import" the "type information" but if used directly it would import the module itself. I'm not sure how many TypeScript developers actually are aware of that as this is a quite ambiguous use of both the keyword ```import``` and ```require```.

**Comment by danquirk** [comment]
_Seems like import can be used to only import the type (when only use in a type position) but if used as a value would import the module itself. I'm not sure how many TypeScript developers are actually aware of this (perhaps this feature was added, or at least documented, only recently?) as this is quite an ambiguous use of both the keyword import and require._

You're definitely not the first to be bitten by this. It is subtle but there are good reasons for it. We've recently been talking about potential alternatives to make this scenario easier/clearer.

**Comment by rotemdan** [comment]
Hi, thanks for your reply! It's not every day that I discover a way to do something that I thought was impossible for literally years now.

I think the new ```type``` keyword could be an interesting candidate for an alternative syntax, which should be usable in any scope of the program (naturally, as this is just a type alias, it should work within modules, classes and functions), I think:
```ts
type ExternalModule = require("ExternalModule")
```
Is slightly clearer, but the ```require``` keyword is still confusing in this context. Another alternative is
```ts
type ExternalModule = module("ExternalModule")
```
or even clearer:
```ts
type ExternalModule = typeof module("ExternalModule")
```
or compromise with:
```ts
type ExternalModule = typeof require("ExternalModule")
```
or to be compatible with the new ES6 syntax perhaps typeof could accept a whole import expression (in all its varieties, including non-ES6 external modules) like this:
```ts
type T = typeof (import Greeter from "./greeter");
```
or even this:
```ts
type T = typeof (import defaultExport, { namedExport1, namedExport2, namedExport3 } from "./myModule")
```
I think this looks quite reasonable, and not too difficult to parse, and as a language specializing in typing, having the ability to apply ```typeof``` to complex expression would actually be quite natural (and powerful) thing to have. Perhaps TypeScript should even adopt the principal of allowing the developer to easily assign every possible known type to an arbitrary, unknown object including the type of any known interface class, enum, ambient external/internal module and ES6 module.

Anyway, whatever syntax is used, there's no need to rush to it. I'm interested what are the sort of alternative the designers are considering?
