### ISSUE TITLE
Member of merged string enum declaration incorrectly evaluates to undefined

### ISSUE THREAD

**Issue by tehsenaus** [Microsoft/TypeScript#23468]
**TypeScript Version:** 
2.9.0-dev.20180414

**Search Terms:**
string enum merge undefined

**Code**

test-module.ts:
```ts
export enum E {
	A = 'a',
}
```

test.ts:
```ts

import { E } from './test-module';

declare module './test-module' {
	export enum E {
		B = 'b',
	}
}

// A = a
console.log('A = %s', E.A);

// B = undefined
console.log('B = %s', E.B);

// Type error
// console.log('C = %s', E.C);

```

**Expected behavior:**
Throws a type error, or prints:
```
A = a
B = b
```

**Actual behavior:**
Prints:
```
A = a
B = undefined
```

**Playground Link:**
N/A

**Related Issues:**
N/A

**Comment by andy-ms** [comment]
`declare module './test-module'`: This is a `declare` -- it just declares things to exist, but it doesn't actually emit any code that would cause them to exist, instead the user is responsible for that.

**Comment by tehsenaus** [comment]
Thanks for the response.

This isn't clear from the docs, in fact I'd say the docs imply the opposite:

> ...value-creating declarations create values that are visible in the output JavaScript.

https://www.typescriptlang.org/docs/handbook/declaration-merging.html

**Comment by andy-ms** [comment]
@DanielRosenwasser thoughts?
