### ISSUE TITLE
React 16.3 getDerivedStateFromProps support

### ISSUE THREAD

**Issue by Kayomani** [Microsoft/TypeScript#23465]
In our application we use generics quite extensively for instance take the code:
```
export class Form<T> extends React.Component<IFormProps<T>, State> {

    componentWillReceiveProps(newProps: IFormProps<T>) {
        // snip
      }

}
```
In  React [16.3](https://reactjs.org/blog/2018/03/29/react-v-16-3.html) they are looking to change the API to:
```
export class Form<T> extends React.Component<IFormProps<T>, State> {

    static getDerivedStateFromProps(nextProps: IFormProps<T>, prevState: State) {

    }
```
This is pretty breaking as we can't reference the class generic from the static.  I don't know the technical reason why they are forcing us to use statics beyond perhaps performance?  I honestly see this is more of a react issue and having them not use static but I can see them just saying its a Typescript issue.

Are there any plans to support this generics in this way or any workarounds?

**Comment by Kayomani** [comment]
This isn't about the typings (I have the above) its about loss of support of generics:

![image](https://user-images.githubusercontent.com/16805327/38880278-3741f968-425d-11e8-8182-b528e4b8673c.png)

**Comment by Kayomani** [comment]
This is probably less of an issue than I thought so I'll close for now. It would be nice to share any restrictions on the class generic mind you.

**Comment by s-ve** [comment]
oops sorry I misread your issue.

You should be able to do this :

```ts
export class Form<T> extends React.Component<IFormProps<T>, State> {

    static getDerivedStateFromProps<U>(nextProps: IFormProps<U>, prevState: State) {

    }
```

But since you are not supposed to call `getDerivedStateFromProps` directly, you could use `any` instead

```ts
export class Form<T> extends React.Component<IFormProps<T>, State> {

    static getDerivedStateFromProps(nextProps: IFormProps<any>, prevState: State) {

    }
```
