### ISSUE TITLE
New Logo Proposal

### ISSUE THREAD

**Issue by LuigiBaute** [Microsoft/TypeScript#23482]
Hello! I would like to collaborate with this project by providing a _free_ new logo that suits with the project! Let me know if interested so we can get in touch! Cheers.

**Comment by DanielRosenwasser** [comment]
Thank you! We actually might be interested to hear about your ideas, though I don't think we can necessarily commit ourselves to anything. If you want to reach out and discuss it privately, my email address just uses my name in the format `FirstName.LastName [at] microsoft <dot> com`
