### ISSUE TITLE
Generic type comparison using Enums throws incompatible type errors

### ISSUE THREAD

**Issue by danielfigueiredo** [Microsoft/TypeScript#23483]
**TypeScript Version:**  2.8 (using typescript [playground](http://www.typescriptlang.org/play))

**Search Terms:** Enum, Generics, Typescript, Type alias

**Code** 

```ts
type Action<T, P = undefined, M = undefined> = { type: T, payload: P, meta: M };

enum MyActionType {
    MY_ACTION = 'MY_ACTION',
    TEST = 'TEST'
}

type MyAction = Action<MyActionType.MY_ACTION, string>;

const createAction = <T, P, M>(type: T, payload?: P, meta?: M): Action<T, P, M> => ({ type, payload, meta });

const createMyAction = (payload: string): MyAction =>
    createAction(MyActionType.MY_ACTION, payload);

```

**Expected behavior:**

No errors.

**Actual behavior:**

```
Type 'Action<MyActionType, string, undefined>' is not assignable to type 'Action<MyActionType.MY_ACTION, string, undefined>'.
  Types of property 'type' are incompatible.
    Type 'MyActionType' is not assignable to type 'MyActionType.MY_ACTION'.
```

Important to note that if `createAction` is updated to have T extending string, for example:

```ts
const createAction = <T extends string, P, M>(type: T, payload?: P, meta?: M): Action<T, P, M> => ({ type, payload, meta });
```
It works as expected.

**Playground Link:** [Link](http://www.typescriptlang.org/play/#src=type%20Action%3CT%2C%20P%20%3D%20undefined%2C%20M%20%3D%20undefined%3E%20%3D%20%7B%20type%3A%20T%2C%20payload%3A%20P%2C%20meta%3A%20M%20%7D%3B%0A%0Aenum%20MyActionType%20%7B%0A%20%20%20%20MY_ACTION%20%3D%20'MY_ACTION'%2C%0A%20%20%20%20TEST%20%3D%20'TEST'%0A%7D%0A%0Atype%20MyAction%20%3D%20Action%3CMyActionType.MY_ACTION%2C%20string%3E%3B%0A%0Aconst%20createAction%20%3D%20%3CT%2C%20P%2C%20M%3E(type%3A%20T%2C%20payload%3F%3A%20P%2C%20meta%3F%3A%20M)%3A%20Action%3CT%2C%20P%2C%20M%3E%20%3D%3E%20(%7B%20type%2C%20payload%2C%20meta%20%7D)%3B%0A%0Aconst%20createMyAction%20%3D%20(payload%3A%20string)%3A%20MyAction%20%3D%3E%0A%20%20%20%20createAction(MyActionType.MY_ACTION%2C%20payload)%3B)

**Related Issues:** Couldn't find anything related in existing open issues.

**Comment by mhegazy** [comment]
Literal types are not inferred automatically, as @andy-ms mentioned. you can *instruct* the compiler to infer literal types by adding a constraint on the type parameter, e.g.:

```ts
const createAction = <T extends MyActionType, P, M>(type: T, payload?: P, meta?: M): Action<T, P, M> => ({ type, payload, meta });
```

Will cause the compiler to infer the more specific type at the call site.

**Comment by danielfigueiredo** [comment]
Alright, that makes sense. I somehow thought this was supported already.

Thanks for the answers!
