### ISSUE TITLE
Enhance/Fix design metadata to handle constant/interface merge scenarios

### ISSUE THREAD

**Issue by EisenbergEffect** [Microsoft/TypeScript#23498]
There are some similar issues in the tracker, but I didn't find anything exactly like this. I'm not sure whether to call this a bug or a feature request. Let me explain. Let's say you have some code like this:

```typescript
const IFoo = Symbol('IFoo');
interface IFoo {
  bar();
}
```

TypeScript will treat `IFoo` as an interface when used as a type and as a constant when used as a value. It's pretty cool. However, when used with `emitDecoratorMetadata` in this example:

```typescript
export class Baz {
  constructor(foo: IFoo) {}
}
```

The emitted metadata includes `Object` instead of the symbol value `IFoo`. It seems that the compiler should handle this as it does other scenarios where it differentiates between value and interface and just emit the value into the metadata.

Seems like a bit of an oversight. If we could address this, it would open up some nice scenarios around dependency injection. The Aurelia community would sure benefit, and probably Angular as well. From studying the VS Code source, I can tell that they are hacking around this not working as well. So, at least three prominent projects with many developer customers would benefit.

Thoughts?

**Comment by pcan** [comment]
This issue has already been addressed in #3628, but, unfortunately, there is no progress at the moment 😞

**Comment by EisenbergEffect** [comment]
Just to be clear, I'm not asking for the compiler to generate an `IFoo` symbol at all. I'm only asking for the existing design metadata to use the correct value, since a value *already exists*. I'm happy to manually create the symbol.

**Comment by EisenbergEffect** [comment]
Cross-posted to the other thread as well. Thanks @pcan !

**Comment by EisenbergEffect** [comment]
Frankly, it is unfortunately, very unintuitive and quite surprising behavior ;( It's not a deal killer for me, but it goes on my list of, if TypeScript only...

Closing this in favor of the #3628.
