### ISSUE TITLE
Function assignment thru type definition product inconsistent compile messages (Version 1.4)

### ISSUE THREAD

**Issue by sixtram** [Microsoft/TypeScript#2349]
// The following function assignment don't product error messages when needed.

type t_cb = (p:number, q:number) => void;

function callback_1(): void {
}

function callback_2(p: number): void {
}

function callback_3(p: number, q: number): void {
}

function callback_4(p: number, q: number, r: number): void {
}

var cb: t_cb = null;

cb = callback_1; // doesn't product compile error
cb = callback_2; // doesn't product compile error
cb = callback_3; // doesn't product compile error

cb = callback_4; // compile error

**Comment by danquirk** [comment]
This is by design. JavaScript permits you to provide fewer arguments than are required in situations like this. In practice you can see why this isn't really that strange:

```ts
var cb: (a: number) => void;
// you want an error here for forgetting a parameter:
cb = () => { console.log('hi'); } 
// but then this is ok, no one forces you to actually use the argument anyway:
cb = (x: number) => { console.log('hi'); } 
```

You'll see many JavaScript APIs that take advantage of this property. Array.map takes an array and a callback to process it. The callback accepts 3 arguments, the current value, the index, and the array. Most often you don't need either the index or the array, and so you can simply call:
```[1,2,3].map(x => x * 2)```
rather than
```[1,2,3].map(x, i, arr => x * 2);```

**Comment by sixtram** [comment]
OP here. Meanwhile reading the docs I realized that this is by design, at the same while

`cb = callback_1;`

doesn't produce a compile error, calling callback_1 thru a

`cb();`

call will produce the following compile error "Supplied parameters do not match any signature of call target."

**Comment by danquirk** [comment]
The type of ```cb``` does not change dynamically based on what is assigned to it. It is still typed as a function that requires 2 arguments of type number, it just so happens that you've assigned an implementation of a function that won't use those numbers. Consider some conditions which cause you to pick between which implementation is used:

```ts
if(something) {
    cb = callback_1;
} else if (somethingElse) {
    cb = callback_2;
} else {
    cb = callback_3;
}
cb(1,2); // this would break if both arguments weren't still required
```
