### ISSUE TITLE
Potentially incorrect return type inference for enum types

### ISSUE THREAD

**Issue by michaelgeorgeattard** [Microsoft/TypeScript#23504]
Hi,

In the following case, why is type of `z` inferred as `Bar` instead of `Bar.Baz`?

```ts
enum Bar {
    Baz = "Baz",
    Abc = "Abc"
}

function foo() {
    return Bar.Baz;
}

const z = foo();
```

**Comment by MartinJohns** [comment]
Because `Bar.Baz` is not a type. It's an identifier for the value `"Baz"`, and the type is `Bar`.

**Comment by michaelgeorgeattard** [comment]
`Bar.Baz` should be a type too.

Also the below works:

```ts
enum Bar {
    Baz = "Baz",
    Abc = "Abc"
}

function foo(): Bar.Baz {
    return Bar.Baz;
}

const z = foo();
```

**Comment by andy-ms** [comment]
Duplicate of  #241

**Comment by RyanCavanaugh** [comment]
@andy-ms these are function declarations, not expressions
