### ISSUE TITLE
 Typescript Language service not finding symbolic linked (junction) npm module

### ISSUE THREAD

**Issue by linmodev** [Microsoft/TypeScript#23502]
**TypeScript Version:**  2.8.1
**OS Version:** macOS 10.13.3
**vscode:** 1.22.1

**Search Terms:**  npm link 

**Code**
1. A symbolic link (NTFS junction) to a library package in node_modules breaks code's intellisense ability to find the module, even though building from the command line works fine. This makes node dev a pain when developing a lib and consuming package and don't want to go through the publish / install loop

```ts
{
    "compilerOptions": {
        "module": "commonjs",
        "moduleResolution": "node",
        "sourceMap": true,
        "declaration": true,
        "rootDir": "src", 
        "outDir": "lib",
        "target": "es2015",
        "lib": [
            "dom",
            "es2016"
        ],
        "noImplicitAny": false
    },
  "include": [
    "src/**/*"
  ]
}
```

2. Create and compile another package consumer with a file that references the lib with an import {foo} from 'lib'

3. Copy the lib into the consumer's node_modules - as if it had been `npm install'ed

4. Look at the import line in code - all intellisense is good. lib is found

5. Delete node_modules\lib

6. Either manually link by adding a junction or use npm link ..\lib lib is navigable in the code file browser (on left)

7. Look at the import line in code - 'lib' has red squiggle and hover displays '[ts] Cannot find module 'lib'.'

I can supply all files if required, but the lib is just a single file with a single export and consuming code references it. basic stuff.

**Expected behavior:**
ts-server can find npm link module
**Actual behavior:**
ts-server can not find npm link module
**Playground Link:**  

**Related Issues:** https://github.com/Microsoft/vscode/issues/25312

**Comment by linmodev** [comment]
@RyanCavanaugh

**Comment by sheetalkamat** [comment]
@linmodev can you share the tsserver and ti log with the issue. 
1. In VS Code: "typescript.tsserver.log": "verbose"
   If possible can you also use typescript@next. ([using nightly build in vscode](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Nightly%20Builds.md#visual-studio-code))
2. Restart vscode and reproduce the issue
3. In VS Code, run the TypeScript: Open TS Server log command, Opened folder will have two files showing the type installer and tsserver log.

**Comment by linmodev** [comment]
The log file is too long. I save it in my github gist.
https://gist.github.com/linmodev/fbae4b4ed09d194c72e11164b6e300de
https://gist.github.com/linmodev/0425b2bd67b2e9c178b0cc70043937eb

**Comment by linmodev** [comment]
@sheetalkamat  I update my ts version. The problem still exsit .

**Comment by sheetalkamat** [comment]
@linmodev Thank you for the logs. I took a look at it and were able to tell much from the logs. 
From your log it looks like you are not using typescript@next ( [log link](https://gist.github.com/linmodev/fbae4b4ed09d194c72e11164b6e300de#file-tsserver-log-L2))
Also you do not have tsconfig.json and that means it will use inferred project with following options: 
```json
{"module":"commonjs","target":"es2016","jsx":"preserve","allowJs":true,"allowSyntheticDefaultImports":true,"allowNonTsExtensions":true}
```
Do you have tsconfig.json somewhere? Since you opened folder in vscode at ```/Users/xukunlong/Desktop/study-project/projectA``` thats the location tsconfig.json would be looked up till.
I couldnt tell much from the logs whats going on. Can you please add ```tsconfig.json``` in that folder and add ```traceResolution: true``` in your compiler options and get the log. That should indicate what are the location looked up and if and how the module resolution went wrong. Also please share the repro code and steps you took to create the folder structure. (It could be os dependent and hence asking for the log apart from the repro code and exact steps)

**Comment by linmodev** [comment]
@sheetalkamat 
Only a demo project of this, so I forget add the tsconfig file. It has no effect or response when add this file. 

![2018-04-20-09-18-09](http://p6fy6gb44.bkt.clouddn.com/2018-04-20-09-18-09.png)

The picture of above of  show the structure.
I upgraded ts according to your requirements and added tsconfig.
The below is new log.
https://gist.github.com/linmodev/9c18d5c2e6225c4d4f21af1c5f483056
https://gist.github.com/linmodev/df91ead87b517f39044176df9f9b8539

**Comment by sheetalkamat** [comment]
@mjbvz I looked at the [tsserver log](https://gist.github.com/linmodev/9c18d5c2e6225c4d4f21af1c5f483056) and it seems like there are two open requests for the same file? ([first open](https://gist.github.com/linmodev/9c18d5c2e6225c4d4f21af1c5f483056#file-tsserver-log-2-9-0-dev-20180418-L9), [second open](https://gist.github.com/linmodev/9c18d5c2e6225c4d4f21af1c5f483056#file-tsserver-log-2-9-0-dev-20180418-L157)) That breaks the asserts we have. Can you see what went wrong and why there are two open requests for same file ```/Users/xukunlong/Desktop/study-project/projectA/example/index.ts```

**Comment by sheetalkamat** [comment]
@mjbvz I dont have repro but only the tsserver log shared by @linmodev

**Comment by sheetalkamat** [comment]
@linmodev Can you please use vscode insiders build that @mjbvz suggested and see if the issue persists. If it does please provide tsserver and ti log as earlier for further investigation.
Thank you.

**Comment by linmodev** [comment]
@sheetalkamat The problem still exists. Is uploading logs too inefficient? I uploaded the file structure directly to this repository. Is that okay?
https://github.com/linmodev/reproduce.git

**Comment by sheetalkamat** [comment]
@linmodev The repo doesnt contain the node_modules folder or how you have setup the structure in node_modules. Can you please share that portion of steps as well.

Also please use latest nightly drop from typescript and see if the issue repros in [vscode insiders](https://code.visualstudio.com/insiders/) and with [typescript nightly drop](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Nightly%20Builds.md#visual-studio-code). 

You can also upload logs using 
1. With "typescript.tsserver.log": "verbose" enabled
2. Restart vscode insiders
3. Reproduce the problem
4. Run ```code-insiders --upload-logs``` on the command line and follow instructions
5. Share the log file ID

**Comment by linmodev** [comment]
The first step is to execute `npm install` and `npm link` in the current root directory.
The second step, execute `npm install` and `npm link projecta`  in the example directory

ID:1300198809

**Comment by varHarrie** [comment]
![image](https://user-images.githubusercontent.com/14304201/39856299-df0ee582-5461-11e8-8a87-982d3fa16424.png)
[ts-modules-test](https://github.com/Xceno/ts-modules-test) is a demo create by @Xceno.

**Comment by jingzhou123** [comment]
same issue. but I dont wanna use typescript@next. Wait you body to fix it

**Comment by linmodev** [comment]
@varHarrie  Thank you for your reminder, your example is also run by me here, but I seem to find the key to the problem from the difference between you and my example. My project structure is nested, but yours is parallel. @sheetalkamat  The problem seems to be here.

![image](https://user-images.githubusercontent.com/21982105/39975666-8d3e3ec0-5762-11e8-8ae2-58815d311307.png)

**Comment by sheetalkamat** [comment]
@linmodev The issue isnt about the module being in sibling or subdirectory. The issue is package.json containing main field that references anything but "index" where yours has "src/index.ts"
