### ISSUE TITLE
error:Property 'select' does not exist on type HTMLElement

### ISSUE THREAD

**Issue by johnzhu12** [Microsoft/TypeScript#23503]
‘
  function copy(){
      var Url=document.getElementById("Id");
      Url.select();     //error
      document.execCommand("Copy"); // browser copy
  }
’

as above. I'm trying to make a function to copy text in browser.but the error as title occurred
in typescript.
   the select() is valid  I think([link](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement)),since I can copy correctly when I use it in  a demo.
   my ts version is 2.8.1

**Comment by johnzhu12** [comment]
all right, thanks anyway

**Comment by crissty** [comment]
I also get this error in TypeScript

**Comment by johnzhu12** [comment]
@crissty  https://stackoverflow.com/questions/49911541/errorproperty-select-does-not-exist-on-type-htmlelement
      FYI
