### ISSUE TITLE
Plain type definition has different behaviors with the identical type which is converted from.

### ISSUE THREAD

**Issue by zheeeng** [Microsoft/TypeScript#23501]
Do not sure if I get a proper title to describe this issue, any one kind can help me titling.

**TypeScript Version:**  2.7.0-dev.201xxxxx
2.8.1

**Search Terms:** 
hard to find appropriate search terms

**Code**

```ts
type Omit<T, K> = Pick<T, Exclude<keyof T, K>>

type PartialFields<P, K extends keyof P> = Omit<P, K> & Partial<Pick<P, K>>

interface IdObj {
  <P>(o: P) : { [K in keyof P]: P[K] }
}

const idObj: IdObj = o => o

const idNum = (x: number) => x

function test<P extends { foo: number }>(
  p1: PartialFields<P, 'foo'>,
  p2: PartialFields<{ [K in keyof P]: P[K] }, 'foo'>,  // Isn't it's type identical with p1?
) {
  const f1 = p1.foo        || 42         // P["foo"]
  //  Isn't the type of  idObj(p1) should be identical with the type of p2
  const f2 = idObj(p1).foo || 42    // PartialFields<P, "foo">["foo"]
  // I think f3 should be the same type with f2
  const f3 = p2.foo        || 42        // { [K in keyof P]: P[K]; }["foo"]
  const f4 = idObj(p2).foo || 42   // PartialFields<P, "foo">["foo"]

  return idNum(f1) + idNum(f2) + idNum(f3) + idNum(f4)
}
```

**Expected behavior:**

1. `p1` and `p2` have the same type behaviors, `p2`'s type is identical with `idObj(p1)`
2. `f3`'type is identical with `f2`'s
3. `f1, `f2`, `f3`, `f4` all are inferred as number type, at least, are compatible with number type.

**Actual behavior:**

1. `f1` and `f3` is typed as `P['foo']`.
2. `f2` and `f4` is typed as `PartialFields<P, "foo">["foo"]`. 
I think
```
const f2 = idObj(p).foo || 42
const f4 = idObj(p).foo || 42
```
has ensured their types.
3. At `idNum(f2)`, TS warns: 
```
Argument of type 'PartialFields<P, "foo">["foo"]' is not assignable to parameter of type 'number'.
  Type 'P["foo"] | undefined' is not assignable to type 'number'.
    Type 'undefined' is not assignable to type 'number'.
``` 
4. At `idNum(f4)`, TS warns:
```
Argument of type 'PartialFields<{ [K in keyof P]: P[K]; }, "foo">["foo"]' is not assignable to parameter of type 'number'.
  Type '{ [K in keyof P]: P[K]; }["foo"] | undefined' is not assignable to type 'number'.
    Type 'undefined' is not assignable to type 'number'.
```
5. `f3` is valid to pasing to `idNum`, but `f2` not, it's weird.

**Playground Link:**  
[Playground](http://www.typescriptlang.org/play/index.html#src=type%20Omit%3CT%2C%20K%3E%20%3D%20Pick%3CT%2C%20Exclude%3Ckeyof%20T%2C%20K%3E%3E%0D%0A%0D%0Atype%20PartialFields%3CP%2C%20K%20extends%20keyof%20P%3E%20%3D%20Omit%3CP%2C%20K%3E%20%26%20Partial%3CPick%3CP%2C%20K%3E%3E%0D%0A%0D%0Ainterface%20IdObj%20%7B%0D%0A%20%20%3CP%3E(o%3A%20P)%20%3A%20%7B%20%5BK%20in%20keyof%20P%5D%3A%20P%5BK%5D%20%7D%0D%0A%7D%0D%0A%0D%0Aconst%20idObj%3A%20IdObj%20%3D%20o%20%3D%3E%20o%0D%0A%0D%0Aconst%20idNum%20%3D%20(x%3A%20number)%20%3D%3E%20x%0D%0A%0D%0Afunction%20test%3CP%20extends%20%7B%20foo%3A%20number%20%7D%3E(%0D%0A%20%20p1%3A%20PartialFields%3CP%2C%20'foo'%3E%2C%0D%0A%20%20p2%3A%20PartialFields%3C%7B%20%5BK%20in%20keyof%20P%5D%3A%20P%5BK%5D%20%7D%2C%20'foo'%3E%2C%0D%0A)%20%7B%0D%0A%20%20const%20f1%20%3D%20p1.foo%20%20%20%20%20%20%20%20%7C%7C%2042%0D%0A%20%20const%20f2%20%3D%20idObj(p1).foo%20%7C%7C%2042%0D%0A%20%20const%20f3%20%3D%20p2.foo%20%20%20%20%20%20%20%20%7C%7C%2042%0D%0A%20%20const%20f4%20%3D%20idObj(p2).foo%20%7C%7C%2042%0D%0A%0D%0A%20%20return%20idNum(f1)%20%2B%20idNum(f2)%20%2B%20idNum(f3)%20%2B%20idNum(f4)%0D%0A%7D%0D%0A)

**Related Issues:**

**Comment by DanielRosenwasser** [comment]
There are definitely places where TypeScript doesn't understand enough about the equivalencies between different higher order types, but is there a specific pattern you're trying to express?

**Comment by zheeeng** [comment]
Yes, the idObj has the similar shape of Readonly Advanced type. More specific, in React, p1 is the props are passed to a Component, p2 is the ‘this.props’ inside a Component which is wrapped with Readonly from the type of p1, ‘this.props.foo’ is unable to use as a number type but ‘props.foo’ could
