### ISSUE TITLE
JSDoc does not strip leading * inside markdown code block

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#23517]
**TypeScript Version:**  2.9.0-dev.20180418

**Search Terms:** 
- jsdoc
- example
- markdown

**Code**

```ts
/**
 * @example
 * ```
 * 1 + 2
 * ```
*/
export function foo() { }
```

Hover over `foo`

**Bug:**
The jsdoc content returned includes the leading ` * ` from the comment inside the code block:

```
[Trace  - 11:08:38 AM] Response received: quickinfo (13). Request took 2 ms. Success: true 
Result: {
    "kind": "function",
    "kindModifiers": "export",
    "start": {
        "line": 9,
        "offset": 17
    },
    "end": {
        "line": 9,
        "offset": 20
    },
    "displayString": "function foo(): void",
    "documentation": "",
    "tags": [
        {
            "name": "example",
            "text": "```\n * 1 + 2\n * ```"
        }
]
}
 ```

This is a regression from the current 2.8 builds

**Comment by mhegazy** [comment]
PRs welcomed.

**Comment by postspectacular** [comment]
I only noticed this change in behavior now after updating VSCode, but this definitely was still working correctly a couple of months ago. Also using standard (non-fenced / non-GFM) Markdown for code blocks still works correctly now. Maybe there was a change/replacement of the MD parser?

```ts
/**
 * This works as expected (w/o leading asterisks)
 *
 * @example
 *
 *    const foo = [...mapcat((x) => [x,x,x], [1,2,3])];
 *    // [[1,1,1], [2,2,2], [3,3,3]]
 */
```
