### ISSUE TITLE
Overly broad error span when function field not assignable to its annotation inside class

### ISSUE THREAD

**Issue by kpdonn** [Microsoft/TypeScript#23515]
**TypeScript Version:**  2.9.0-dev.20180414

**Search Terms:** 
class error span, not assignable to type

**Code**

```ts
type Values = 1 | 2 | 3 | 4 | 5 | 6

type FuncType = (arg: Values) => string

// turn on strictNullChecks
class Example {
  insideClass: FuncType = function(val) { // error span goes from here
    switch (val) {
      case 1:
        return "1";
      case 2:
        return "2";
      case 3:
        return "3"
      case 4:
        return "4"
      case 5:
        return "5"
      // forgot case 6
    }
  } // all the way to here
}

const outsideClass: FuncType = function(val) { // compare to errors only on this line in this case 
    switch (val) {
      case 1:
        return "1";
      case 2:
        return "2";
      case 3:
        return "3"
      case 4:
        return "4"
      case 5:
        return "5"
      // forgot case 6
    }
}
```

**Expected behavior:**
Error on `insideClass` field would look similar to one on `outsideClass` variable.

**Actual behavior:**
Error on `insideClass` spans the entire function implementation.

**Playground Link:** 
[Link](https://www.typescriptlang.org/play/#src=type%20Values%20%3D%201%20%7C%202%20%7C%203%20%7C%204%20%7C%205%20%7C%206%0D%0A%0D%0Atype%20FuncType%20%3D%20(arg%3A%20Values)%20%3D%3E%20string%0D%0A%0D%0A%2F%2F%20turn%20on%20strictNullChecks%0D%0Aclass%20Example%20%7B%0D%0A%20%20insideClass%3A%20FuncType%20%3D%20function(val)%20%7B%20%2F%2F%20error%20span%20goes%20from%20here%0D%0A%20%20%20%20switch%20(val)%20%7B%0D%0A%20%20%20%20%20%20case%201%3A%0D%0A%20%20%20%20%20%20%20%20return%20%221%22%3B%0D%0A%20%20%20%20%20%20case%202%3A%0D%0A%20%20%20%20%20%20%20%20return%20%222%22%3B%0D%0A%20%20%20%20%20%20case%203%3A%0D%0A%20%20%20%20%20%20%20%20return%20%223%22%0D%0A%20%20%20%20%20%20case%204%3A%0D%0A%20%20%20%20%20%20%20%20return%20%224%22%0D%0A%20%20%20%20%20%20case%205%3A%0D%0A%20%20%20%20%20%20%20%20return%20%225%22%0D%0A%20%20%20%20%20%20%2F%2F%20forgot%20case%206%0D%0A%20%20%20%20%7D%0D%0A%20%20%7D%20%2F%2F%20all%20the%20way%20to%20here%0D%0A%7D%0D%0A%0D%0Aconst%20outsideClass%3A%20FuncType%20%3D%20function(val)%20%7B%20%2F%2F%20compare%20to%20errors%20only%20on%20this%20line%20in%20this%20case%20%0D%0A%20%20%20%20switch%20(val)%20%7B%0D%0A%20%20%20%20%20%20case%201%3A%0D%0A%20%20%20%20%20%20%20%20return%20%221%22%3B%0D%0A%20%20%20%20%20%20case%202%3A%0D%0A%20%20%20%20%20%20%20%20return%20%222%22%3B%0D%0A%20%20%20%20%20%20case%203%3A%0D%0A%20%20%20%20%20%20%20%20return%20%223%22%0D%0A%20%20%20%20%20%20case%204%3A%0D%0A%20%20%20%20%20%20%20%20return%20%224%22%0D%0A%20%20%20%20%20%20case%205%3A%0D%0A%20%20%20%20%20%20%20%20return%20%225%22%0D%0A%20%20%20%20%20%20%2F%2F%20forgot%20case%206%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A) (Must turn on strictNullChecks to see error)

**Related Issues:**
Did not notice any duplicates when looking through [`Domain: Error Messages` tag](https://github.com/Microsoft/TypeScript/issues?q=is%3Aissue+label%3A%22Domain%3A+Error+Messages%22+is%3Aopen)

**Comment by DanielRosenwasser** [comment]
PRs are welcome! I'd think this would be easy enough to tackle.

**Comment by mhegazy** [comment]
@weswigham we should make sure that all errors on function expression nodes do not extend past the first line (if they are multi-line).
