### ISSUE TITLE
Use 'this.' insertText for static properties completions

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#23520]
From https://github.com/Microsoft/vscode/issues/48104

**TypeScript Version:**  2.9.0-dev.20180418

**Search Terms:** 
- quickfix
- code action
- static
- this

**Code**

```ts
class foo {
    static bar() { }

    static test() {
        
    }
}
```

1. Start typing `bar` in `test`

**Current behavior:**
`bar` is shown as a suggestion. Accepting it completes to `bar()` which produces an error

**Suggested behavior:**
Use the `insertText` completionItem property to make the entry for `bar` complete to `this.bar`, just like it would if these methods were not static

**Playground Link:**  

**Related Issues:**

**Comment by andy-ms** [comment]
This already works with completions, just not with the codefix.

**Comment by mjbvz** [comment]
Ok, I somehow missed the `insertText` property. There is a vs code bug around the `useCodeSnippetsOnMethodSuggest` setting and `insertText`. Closing this as a vscode issue

Sorry for the noise
