### ISSUE TITLE
Union type inference lost on assignment

### ISSUE THREAD

**Issue by amacleay** [Microsoft/TypeScript#23523]
**TypeScript Version:**  2.9.0-dev.20180418

**Search Terms:** union type strictnullchecks inference

**Code**

```ts
interface Person {
  name: string;                           
  address: {                              
    street?: string;
    city: string;                         
  };                                      
}                                         
                                          
declare function getPerson(): Person;     
                                          
function getMinimalAddress(): string {    
  const person = getPerson();             
  if (person.address.street) {            
    const address = person.address;
    return address.street; // ERROR on this line
  } else {                                
    return person.address.city;           
  }                                       
}
```

**Expected behavior:**
Passes type checker. Since `person.address.street` is either `null` or a string, and since there is a check on line 13 for `person.address.street` being truthy, we know that `address.street` is a string.

You can get the type checker to pass by omitting the reassignment:
```diff
--- broken.ts   2018-04-18 16:01:26.188724623 -0400                                 
+++ works.ts    2018-04-18 16:01:26.192724616 -0400                                 
@@ -11,8 +11,7 @@                         
 function getMinimalAddress(): string {   
   const person = getPerson();            
   if (person.address.street) {           
-    const address = person.address;      
-    return address.street;               
+    return person.address.street;        
   } else {                               
     return person.address.city;          
   }
```

**Actual behavior:**
```sh
$ tsc --strictnullChecks broken.ts 
broken.ts(15,5): error TS2322: Type 'string | undefined' is not assignable to type 'string'.
  Type 'undefined' is not assignable to type 'string'.
```
**Playground Link:** [playground link](http://www.typescriptlang.org/play/index.html#src=interface%20Person%20%7B%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%0D%0A%20%20name%3A%20string%3B%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%0D%0A%20%20address%3A%20%7B%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%0D%0A%20%20%20%20street%3F%3A%20string%3B%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%0D%0A%20%20%20%20city%3A%20string%3B%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%0D%0A%20%20%7D%3B%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%0D%0A%7D%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%0D%0A%0D%0Adeclare%20function%20getPerson()%3A%20Person%3B%20%20%20%20%20%0D%0A%0D%0Afunction%20getMinimalAddress()%3A%20string%20%7B%20%20%20%20%0D%0A%20%20const%20person%20%3D%20getPerson()%3B%20%20%20%20%20%20%20%20%20%20%20%20%20%0D%0A%20%20if%20(person.address.street)%20%7B%20%20%20%20%20%20%20%20%20%20%20%20%0D%0A%20%20%20%20const%20address%20%3D%20person.address%3B%20%20%20%20%20%20%20%0D%0A%20%20%20%20return%20address.street%3B%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%0D%0A%20%20%7D%20else%20%7B%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%0D%0A%20%20%20%20return%20person.address.city%3B%20%20%20%20%20%20%20%20%20%20%20%0D%0A%20%20%7D%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%0D%0A%7D)

**Related Issues:**
#22635
#16069

**Comment by RyanCavanaugh** [comment]
We track these guards based on the expressions used to test them; unfortunately the type checker is not implemented in a way that it actually understands that `address` and `person.address` are references to the same object. There's not a lot we can do here short of a wholesale rewrite of the type guard logic, which isn't really in the cards to fix something like this.
