### ISSUE TITLE
Union type inference lost in callback in `else if` clause

### ISSUE THREAD

**Issue by rhys-vdw** [Microsoft/TypeScript#23532]
**TypeScript Version:**  2.9.0-dev.20180418

**Search Terms:** 

infer callback lost null union

**Code**

My attempt at a minimal reproduction - someone could probably do better:

```ts
function takeString(s: string): string {
  return s
}

const x = {
   foo: Math.random() > 0.5 ? "hello" : null
}
if (x.foo === null) {
  console.log("bar")
} else if (["hello"].some(e => e === takeString(x.foo))) { // <-- error here
  console.log("foo")
}
```

**Expected behavior:**

No error

**Actual behavior:**

> Argument of type 'string | null' is not assignable to parameter of type 'string'.
  Type 'null' is not assignable to type 'string'.

**Playground Link:** [link](https://www.typescriptlang.org/play/index.html#src=function%20takeString(s%3A%20string)%3A%20string%20%7B%0A%20%20return%20s%0A%7D%0A%0Aconst%20x%20%3D%20%7B%0A%20%20%20foo%3A%20Math.random()%20%3E%200.5%20%3F%20%22hello%22%20%3A%20null%0A%7D%0Aif%20(x.foo%20%3D%3D%3D%20null)%20%7B%0A%20%20console.log(%22bar%22)%0A%7D%20else%20if%20(%5B%22hello%22%5D.some(e%20%3D%3E%20e%20%3D%3D%3D%20takeString(x.foo)))%20%7B%20%2F%2F%20%3C--%20error%20here%0A%20%20console.log(%22foo%22)%0A%7D)

**Related Issues:**

**Comment by MartinJohns** [comment]
It is working as intended, and the issue is the expression/lambda, not the else-if. The compiler has no guarantee that `.some()` will call your lambda immediately, so theoretically the value of `x.foo` could change in the meantime.

A solution would be to have an else block, then assign the correctly typed `x.foo` to a local const variable and pass that to the function.

https://github.com/Microsoft/TypeScript/issues/7719#issuecomment-202684512

**Comment by rhys-vdw** [comment]
Ah of course, thanks!

Although I should point out that this *also* fails [when the field is `readonly`](https://www.typescriptlang.org/play/index.html#src=function%20takeString(s%3A%20string)%3A%20string%20%7B%0A%20%20return%20s%0A%7D%0Ainterface%20X%20%7B%0A%20%20readonly%20foo%3A%20string%20%7C%20null%0A%7D%0Aconst%20x%3A%20X%20%3D%20%7B%0A%20%20%20foo%3A%20Math.random()%20%3E%200.5%20%3F%20%22hello%22%20%3A%20null%0A%7D%0Aif%20(x.foo%20%3D%3D%3D%20null)%20%7B%0A%20%20console.log(%22bar%22)%0A%7D%20else%20if%20(%5B%22hello%22%5D.some(e%20%3D%3E%20e%20%3D%3D%3D%20takeString(x.foo)))%20%7B%20%2F%2F%20%3C--%20error%20here%0A%20%20console.log(%22foo%22)%0A%7D). So perhaps there is room for improvement here?

**Comment by MartinJohns** [comment]
The `readonly` modifier is not part of the actual type of the `foo` property, unfortunately. The `readonly` modifier applies to the interface and declares that the property `foo` is read-only. As an unfortunate result you can just pass a `readonly` interface to a method accepting a mutable version and modify the object:

```
interface ReadonlyTest { readonly foo: string; }
interface MutableTest { foo: string; }

function mutateTest(test: MutableTest): void {
    test.foo = 'oh no!';
}

const readonlyTest: ReadonlyTest = { foo: 'bar' };
mutateTest(readonlyTest);
```

**Comment by RyanCavanaugh** [comment]
See #11498
