### ISSUE TITLE
Iterator.throw method return type is never

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#23536]
**TypeScript Version:**  2.7.0-dev.201xxxxx

**Search Terms:** 

**Code**

**Expected behavior:**

```ts
    throw?(e?: any): never;
```

**Actual behavior:**

```ts
    throw?(e?: any): IteratorResult<T>;
```

**Playground Link:**  

**Related Issues:**

**Comment by ajafff** [comment]
The iterator can catch the error and continue yielding values. So the types are correct.

**Comment by falsandtru** [comment]
The following code throws an exception. Can you show me an example?

```js
(function* () { yield })()[Symbol.iterator]().throw()
```

**Comment by ajafff** [comment]
note that in your example the generator is not started yet because you didn't call `.next()`. So the `yield` is never executed and the error cannot be caught.

Consider the following example:

```ts
const iterator = (function* () {
  try { yield 'foo'; } catch (e) { yield 'bar'; }
})()[Symbol.iterator]();
i.next(); // {value: 'foo', done: false}
i.throw(); // {value: 'bar', done: false}
```

**Comment by falsandtru** [comment]
It seems correct.
