### ISSUE TITLE
Completion insertText for static member should use class name or 'this'?

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#23539]
**TypeScript Version:**  master

**Code**

```ts
class C {
    static m() {
        /**/
    }
}
```

**Current behavior:**

Type `m`, get completion for `this.m`

**Potential behavior:**

Type `m`, get completion for `C.m`

@DanielRosenwasser @amcasey @mhegazy Opinions?

**Comment by mhegazy** [comment]
`this` is fine. the distinction is a subtle, and from our type system perspective they are both identical (Since `this` in a static context is not polymorphic). So my vote is to leave it as is.
