### ISSUE TITLE
Import causes incorrect Declaration Merge 

### ISSUE THREAD

**Issue by jt000** [Microsoft/TypeScript#23544]
**TypeScript Version:**  2.8.1

**Search Terms:** declaration merge import

**Code**
Full repro available at: https://github.com/jt000/typescriptdeclarationmerging

```ts
// MyOptions.ts
export interface MyOptions {
    foo(): void;
}
 
// _jquery.ts - Declaration merging w/ JQuery
import { MyOptions } from './MyOptions';

interface JQuery {
    doSomething(): void;
}
 
// Test.ts
function Test() {
    $('.myelement').doSomething();
}
```

**Expected behavior:** The function `doSomething()` should resolve as a member of JQuery.
**Actual behavior:** TSC returns an error that `doSomething()` is not a member of JQuery.

**Playground Link:** n/a (can't do multi-file examples in playground)

**Related Issues:**

**Comment by andy-ms** [comment]
When a module contains an import, declarations in it are no longer in global scope. You probably need `declare global { ... }` around `interface JQuery`.

**Comment by jt000** [comment]
You are correct. `declare global { ... }` worked like a charm. Thanks!

```ts
declare global {
    interface JQuery {
        DoesntWork(): void;
    }
}
```
