### ISSUE TITLE
Type guard separating object and Array - no index signature

### ISSUE THREAD

**Issue by Saegrov** [Microsoft/TypeScript#23549]
**TypeScript Version:**  
2.8.1, 2.9.0-dev.20180419

**Search Terms:** 
type guard
no index signature

**Code**
Needs noImplicitAny  set to `true`.
```ts
interface KeyValue {
    [key: string]: any
}

function isObjectNotArray(param: any[] | KeyValue): param is KeyValue {
  return typeof param == 'object' && !Array.isArray(param);
}

function printFoo(param: any[] | KeyValue) {
  if (isObjectNotArray(param)) {
    if (param['foo']) {
      console.log(param['foo']);
    }
  } else if(param.length > 0) {
    console.log(param[0])
  }
}

printFoo({ foo: 'foo' });
printFoo(['bar']);
```

**Expected behavior:**
The type guard to make this code valid and without compilation errors.

**Actual behavior:**
Compilation fails with error message:

> Element implicitly has an 'any' type because type 'any[] | KeyValue' has no index signature.

**Playground Link:**  
https://www.typescriptlang.org/play/#src=interface%20KeyValue%20%7B%0D%0A%20%20%20%20%5Bkey%3A%20string%5D%3A%20any%0D%0A%7D%0D%0A%0D%0Afunction%20isObjectNotArray(param%3A%20any%5B%5D%20%7C%20KeyValue)%3A%20param%20is%20KeyValue%20%7B%0D%0A%20%20return%20typeof%20param%20%3D%3D%20'object'%20%26%26%20!Array.isArray(param)%3B%0D%0A%7D%0D%0A%0D%0Afunction%20printFoo(param%3A%20any%5B%5D%20%7C%20KeyValue)%20%7B%0D%0A%20%20if%20(isObjectNotArray(param))%20%7B%0D%0A%20%20%20%20if%20(param%5B'foo'%5D)%20%7B%0D%0A%20%20%20%20%20%20console.log(param%5B'foo'%5D)%3B%0D%0A%20%20%20%20%7D%0D%0A%20%20%7D%20else%20if(param.length%20%3E%200)%20%7B%0D%0A%20%20%20%20console.log(param%5B0%5D)%0D%0A%20%20%7D%0D%0A%0D%0A%7D%0D%0A%0D%0AprintFoo(%7B%20foo%3A%20'foo'%20%7D)%3B%0D%0AprintFoo(%5B'bar'%5D)%3B

**Related Issues:**

**Comment by Saegrov** [comment]
Just after posting this issue i tried changing the `KeyVal` interface:

```ts
interface KeyValue {
    [key: string]: string
}
```

This makes all the compilation problems go away and makes my think that the problem is something with the implicit any? If that's the case the compilation error message is quite confusing.

**Playground Link:**
https://www.typescriptlang.org/play/#src=interface%20KeyValue%20%7B%0D%0A%20%20%20%20%5Bkey%3A%20string%5D%3A%20string%0D%0A%7D%0D%0A%0D%0Afunction%20isObjectNotArray(param%3A%20any%5B%5D%20%7C%20KeyValue)%3A%20param%20is%20KeyValue%20%7B%0D%0A%20%20return%20typeof%20param%20%3D%3D%20'object'%20%26%26%20!Array.isArray(param)%3B%0D%0A%7D%0D%0A%0D%0Afunction%20printFoo(param%3A%20any%5B%5D%20%7C%20KeyValue)%20%7B%0D%0A%20%20if%20(isObjectNotArray(param))%20%7B%0D%0A%20%20%20%20if%20(param%5B'foo'%5D)%20%7B%0D%0A%20%20%20%20%20%20console.log(param%5B'foo'%5D)%3B%0D%0A%20%20%20%20%7D%0D%0A%20%20%7D%20else%20if(param.length%20%3E%200)%20%7B%0D%0A%20%20%20%20console.log(param%5B0%5D)%0D%0A%20%20%7D%0D%0A%0D%0A%7D%0D%0A%0D%0AprintFoo(%7B%20foo%3A%20'foo'%20%7D)%3B%0D%0AprintFoo(%5B'bar'%5D)%3B

**Comment by RyanCavanaugh** [comment]
The problem is that (in the OP) `KeyValue` is a subtype of `any[]`. It's basically if you had written
```ts
var x: Cat | Animal;
if (isAnimal(x)) {
  // ...
} else {
  x.meow();
}
```
In the `else` branch here, `x` is `never` because the type guard *should* always return `true` given the input you're passing it

**Comment by Saegrov** [comment]
Thank you @RyanCavanaugh for the good analogy. That clears it up.

I guess what tripped me up is that the type of the key in an index signature doesn't really make any difference since Javascript calls `toString` on anything that gets used as an index. So the key is always a string.

To illustrate:



```ts
interface StringIndexSignature {
  [key: string]: any
}

interface NumberIndexSignature {
  [key: number]: any
}

function getFirstElement(obj: StringIndexSignature) {
  return obj[1];

}

let x: StringIndexSignature = { 1: 'abc' }
let y: NumberIndexSignature = ['000', '111']
let z: StringIndexSignature = ['000', '111']

console.log(getFirstElement(x));
console.log(getFirstElement(y));
console.log(getFirstElement(z));
```
