### ISSUE TITLE
Wrong suggestion for padStart in JS

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#23555]
_From @garyking on April 20, 2018 1:37_

It seems like the suggestion is wrong for `padStart` in JS? Definition is [here](https://github.com/Microsoft/TypeScript/blob/master/src/lib/es2017.string.d.ts)?

Shouldn't the first field be `length`? Per [docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padStart)

![padstart](https://user-images.githubusercontent.com/343940/39026219-d69980e0-4419-11e8-9f1d-c95a9324612e.png)

_Copied from original issue: Microsoft/vscode#48243_

**Comment by mhegazy** [comment]
I am not sure where you are getting this declaration form. if you share a project i can investigate more. but the declaration from `lib.es2017.string.d.ts` looks different, see https://github.com/Microsoft/TypeScript/blob/master/lib/lib.es2017.string.d.ts#L33

goto def on `padStart` and see where it is coming from, my guess it is one of your dependencies that override the definition. also make sure you have `"lib": ["es2017"]`  or `"lib": ["dom", "dom.iterable", "es2017"]` (if you are using the DOM)  in your `jsconfig.json`.

**Comment by garyking** [comment]
I just checked again, and `padStart` seems fine now. I'll re-open if it happens again.
