### ISSUE TITLE
Const Enum can not be use as index? 

### ISSUE THREAD

**Issue by xiaocaibird** [Microsoft/TypeScript#23557]
```
const enum enum1 {
    A, B, C
}

type T1 = {
    [enum1.A]: string,
    [enum1.B]: string,
    [enum1.C]: string,
    [3]: string,
    [4]: string
}

type T2 = Readonly<T1>;

function f(p1: T1, p2: T2) {
    p1[enum1.A];
    p2[enum1.A];   //Error

    p1[3];
    p2[3];
}
```

**Comment by RyanCavanaugh** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.
