### ISSUE TITLE
Resolution of JS files is not working as expected when using API

### ISSUE THREAD

**Issue by alan-agius4** [Microsoft/TypeScript#23564]
**TypeScript Version:**  2.8.3

**Search Terms:** 
index resolution 
resolution

**Code**

**index.js**
```ts
export * from "./test"
```

**test/index.js**
```ts
export const x = "hello";
```

Transpile code;
```ts
const ts = require("typescript");

const options = { module: ts.ModuleKind.AMD, target: ts.ScriptTarget.ES5, allowJs: true, outDir: "out" };
const host = ts.createCompilerHost(options);
const program = ts.createProgram(["index.js"], options, host);
program.emit();
```

**Expected behavior:**
both files get emitted and downleveled

**Actual behavior:**
`test/index.js` is not resolved and only the root `index.js` is being transpiled, when using the API to downlevel some JS files. If I change the export to `export * from "./test/index"` all files are being transpiled.

**Related Issues:**
https://github.com/dherges/ng-packagr/issues/784

**Comment by ajafff** [comment]
you can use `--traceResolution` to get detailed output about the module resolution.

You probably want to use `--moduleResolution node`.

option | type | default
--- | --- | ---
--moduleResolution | string | module === "AMD" or "System" or "ES6" ? "Classic" : "Node"

**Comment by alan-agius4** [comment]
`moduleResolution` cannot be specified in this case as there would be an exception 
`
Unexpected moduleResolution: node
`
