### ISSUE TITLE
Broken abstract readonly members in generated definitions

### ISSUE THREAD

**Issue by tsofist** [Microsoft/TypeScript#23560]
**TypeScript Version:**  2.8.3, 2.8.1, 2.7.2

**Code**

```ts
abstract class Base {
    protected abstract readonly readOnlyProperty: string;
}

class A extends Base {
    protected readonly readOnlyProperty = "A";
}
```

**Expected behavior (\*.d.ts):**
```ts
declare abstract class Base {
    protected abstract readonly readOnlyProperty: string;
    //---------^1-------^2
}
declare class A extends Base {
    protected readonly readOnlyProperty: string;
}
```

**Actual behavior (\*.d.ts):**

*2.8.3, 2.8.1, 2.7.2*
```ts
declare abstract class Base {
    protected readonly abstract readOnlyProperty: string;
    //---------^2-------^1
}
declare class A extends Base {
    protected readonly readOnlyProperty: string;
}
```

*2.9.0-dev.20180420* **works as expected**

But we expected these changes in 2.8.1 or 2.8.3 :(

**Comment by RyanCavanaugh** [comment]
Sorry to hear the fix didn't make it into the release you expected, but the 2.8 ship has more or less sailed. Unless more people are affected we generally don't ship additional point releases this far out.

**Comment by tsofist** [comment]
@RyanCavanaugh Thanks. We will wait 2.9 💗
