### ISSUE TITLE
API: getShorthandAssignmentValueSymbol in typescript@next returns 'false'

### ISSUE THREAD

**Issue by ajafff** [Microsoft/TypeScript#23562]
**TypeScript Version:**  2.9.0-dev.20180420

**Search Terms:** 

**Code**

```ts
// --strictNullChecks
// --noImplicitAny
export {};
({nonExistent});
```

**Expected behavior:**
`checker.getShorthandAssignmentValueSymbol(node)` where `node` is the Identifier `nonExistent` returns either a valid Symbol or undefined.

**Actual behavior:**
`checker.getShorthandAssignmentValueSymbol(node)` returns `false`
This seems to be a regression in the latest nightly.

**Playground Link:**  

**Related Issues:**

**Comment by mhegazy** [comment]
thanks @ajafff!
