### ISSUE TITLE
Discriminated switch on generic enum type not inferring correct type

### ISSUE THREAD

**Issue by vaskevich** [Microsoft/TypeScript#23578]
**TypeScript Version:**  2.9.0-dev.20180420

**Search Terms:** discriminated generic enum switch

**Code**

```ts
enum MyEnum {
  ONE = 'one',
  TWO = 'two',
}

interface TypeMap {
  [MyEnum.ONE]: number;
  [MyEnum.TWO]: string;
}

function doAction<T extends MyEnum>(type: T, value: TypeMap[T]): void {
  switch (type) {
    case MyEnum.ONE:
      console.log('type:', type, ', value:', value);
      break;
    case MyEnum.TWO:
      console.log('type:', type, ', value:', value);
      break;
    default:
      console.log('type:', type, ', value:', value);
      break;
  }
}
```

**Expected behavior:** the types of `type` would correspond to `MyEnum.ONE` / `MyEnum.TWO` depending on the `case`, and thus value would also get the expected type.

**Actual behavior:**: `type` is still `T extends MyEnum` even within the discriminated switch statement.

**Playground Link:** [TS Playground](https://www.typescriptlang.org/play/#src=enum%20MyEnum%20%7B%0D%0A%20%20ONE%20%3D%20'one'%2C%0D%0A%20%20TWO%20%3D%20'two'%2C%0D%0A%7D%0D%0A%0D%0Ainterface%20TypeMap%20%7B%0D%0A%20%20%5BMyEnum.ONE%5D%3A%20number%3B%0D%0A%20%20%5BMyEnum.TWO%5D%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Afunction%20doAction%3CT%20extends%20MyEnum%3E(type%3A%20T%2C%20value%3A%20TypeMap%5BT%5D)%3A%20void%20%7B%0D%0A%20%20switch%20(type)%20%7B%0D%0A%20%20%20%20case%20MyEnum.ONE%3A%0D%0A%20%20%20%20%20%20console.log('type%3A'%2C%20type%2C%20'%2C%20value%3A'%2C%20value)%3B%0D%0A%20%20%20%20%20%20break%3B%0D%0A%20%20%20%20case%20MyEnum.TWO%3A%0D%0A%20%20%20%20%20%20console.log('type%3A'%2C%20type%2C%20'%2C%20value%3A'%2C%20value)%3B%0D%0A%20%20%20%20%20%20break%3B%0D%0A%20%20%20%20default%3A%0D%0A%20%20%20%20%20%20console.log('type%3A'%2C%20type%2C%20'%2C%20value%3A'%2C%20value)%3B%0D%0A%20%20%20%20%20%20break%3B%0D%0A%20%20%7D%0D%0A%7D%0D%0A)

**Comment by jack-williams** [comment]
Related (I think):  #21483

**Comment by mhegazy** [comment]
`T extends MyEnum` is the right type. `T` is still generic, and in the presence of intersection type, a type can be manufactured that is more specific than `MyEnum` to instantiate your function with, e.g. `MyEnum.One & { tag: void }`

**Comment by vaskevich** [comment]
Thanks for getting back, that does make sense. How would you rewrite the code to support this scenario, though? I tried something like this:

```
function doAction(type: MyEnum, value: TypeMap[typeof type]): void {
  switch (type) {
    case MyEnum.ONE:
      console.log('type:', type, ', value:', value);
      break;
    case MyEnum.TWO:
      console.log('type:', type, ', value:', value);
      break;
    default:
      console.log('type:', type, ', value:', value);
      break;
  }
}
```

but of course, in this case `value` is just going the be the union of all the types of values in `TypeMap` (`number | string`), so that doesn't work. Would we need something like `T extendsExactlyAndNothingMore MyEnum`?

**Comment by mhegazy** [comment]
The generic type is the correct way to do it.. the type really should be `T extends MyEnum.One` and not `T extends MyEnum`. https://github.com/Microsoft/TypeScript/pull/22348 should address that.

**Comment by vaskevich** [comment]
As a workaround, the following seems to now work with 3.3 (referring to the original):

```ts
function doAction<T extends MyEnum>(type: T & MyEnum, value: TypeMap[T]): void {
```

The type within a switch case gets narrowed down to something like `T & MyEnum.ONE`.

**Comment by RyanCavanaugh** [comment]
Tracking at #22348
