### ISSUE TITLE
Suggestion: Expose internals of File Watching beyond simple notification

### ISSUE THREAD

**Issue by arciisine** [Microsoft/TypeScript#23582]
I am building a framework that tightly couples with Typescript, and it would be useful to be able to tap into the File watcher API.

Currently that functionality culminates in the public API of 

`ts.sys.watchDirectory(directory, callback?:(file:string)=>void, recursive?: boolean):FileWatcher`
`ts.sys.watchFile(file, callback?:(file:string)=>void, pollingInterval?: number):FileWatcher`, 

where `FileWatcher` is 
```
interface FileWatcher {
   close():void;
}
```
The API is very limited compared to the actual underlying functionality, especially given that `watchDirectory` does not indicate if the change is an add, remove or delete.

There are other libraries that do this, with `chokidar` being the forerunner with flexibility and configuration.  Unfortunately `chokidar` weighs in at a very heavy footprint (235 dependencies) due to all the various use cases that they support.

**Comment by mhegazy** [comment]
The file watcher APIs are mainly for our watch scenarios in --watch and in tsserver. they are not intended to be general watch APIs really, and we have no plans to support them as such. 
Can elaborate on what options/additions you need and how/if they tie into the TS main scenarios?

**Comment by arciisine** [comment]
My primary motivator for reaching out, is that it seems like what is currently internal, might work just as well, if not better, for quite a few people. This would be true regardless of whether or not they are using TypeScript.

With respect to the internal nature of the APIs, I think we are in agreement.  Exposing them as is, really doesn't fit in line with the project's goals apart form providing additional tooling.  Though I would say that I somewhat feel the same way about the existing `ts.sys.watchDirectory`.  

Ultimately, I'm thinking what may be best is for me to just repackage the current set of internal APIs (or some approximation there of) as a separate lib and use that.
