### ISSUE TITLE
Cannot infer generic types correctly in curried function

### ISSUE THREAD

**Issue by yenshih** [Microsoft/TypeScript#23581]
**TypeScript Version:**  2.8.1

**Code**

```ts
interface Obj {
    foo: {
        fun: string;
    };
    bar: {
        baz: number;
    };
}

const obj: Obj = {
    foo: {
        fun: '1',
    },
    bar: {
        baz: 2,
    },
};

const set = <S, KA extends keyof S = keyof S, KB extends keyof S[KA] = keyof S[KA]>
    (keyA: KA, keyB: KB, value: S[KA][KB]) =>
    (source: S) => source;

// [ts] Argument of type '"bar"' is not assignable to parameter of type 'never'.
set('bar', 'baz', 2)(obj);

// [ts] Argument of type '"baz"' is not assignable to parameter of type 'never'.
set<Obj>('bar', 'baz', 2)(obj);

// Infer generic types correctly. But why?
set<Obj, 'bar'>('bar', 'baz', 2)(obj);

```

**Expected behavior:**

Generic types `S`, `KA`, `KB` in `set` should be inferred correctly.

**Actual behavior:**

Failed to infer generic types.

**Playground Link:** 

[Reproduce Playground](https://www.typescriptlang.org/play/index.html#src=interface%20Obj%20%7B%0D%0A%20%20%20%20foo%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20fun%3A%20string%3B%0D%0A%20%20%20%20%7D%3B%0D%0A%20%20%20%20bar%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20baz%3A%20number%3B%0D%0A%20%20%20%20%7D%3B%0D%0A%7D%0D%0A%0D%0Aconst%20obj%3A%20Obj%20%3D%20%7B%0D%0A%20%20%20%20foo%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20fun%3A%20'1'%2C%0D%0A%20%20%20%20%7D%2C%0D%0A%20%20%20%20bar%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20baz%3A%202%2C%0D%0A%20%20%20%20%7D%2C%0D%0A%7D%3B%0D%0A%0D%0Aconst%20set%20%3D%20%3CS%2C%20KA%20extends%20keyof%20S%20%3D%20keyof%20S%2C%20KB%20extends%20keyof%20S%5BKA%5D%20%3D%20keyof%20S%5BKA%5D%3E%0D%0A%20%20%20%20(keyA%3A%20KA%2C%20keyB%3A%20KB%2C%20value%3A%20S%5BKA%5D%5BKB%5D)%20%3D%3E%0D%0A%20%20%20%20(source%3A%20S)%20%3D%3E%20source%3B%0D%0A%0D%0A%2F%2F%20%5Bts%5D%20Argument%20of%20type%20'%22bar%22'%20is%20not%20assignable%20to%20parameter%20of%20type%20'never'.%0D%0Aset('bar'%2C%20'baz'%2C%202)(obj)%3B%0D%0A%0D%0A%2F%2F%20%5Bts%5D%20Argument%20of%20type%20'%22baz%22'%20is%20not%20assignable%20to%20parameter%20of%20type%20'never'.%0D%0Aset%3CObj%3E('bar'%2C%20'baz'%2C%202)(obj)%3B%0D%0A%0D%0A%2F%2F%20Infer%20generic%20types%20correctly.%20But%20why%3F%0D%0Aset%3CObj%2C%20'bar'%3E('bar'%2C%20'baz'%2C%202)(obj)%3B%0D%0A)

**Comment by RyanCavanaugh** [comment]
Generic inference only occurs on one call at a time; there isn't a way to link two calls together and infer a unified set of generic type arguments from arguments to each call.

Is this a real library?

**Comment by yenshih** [comment]
@RyanCavanaugh Thanks for your response.
Actually it's not a real library. I was writing a set of immutable utilities and found this behavior.
I was wondering if you can tell me how to implement such type check in curried function?
I think `set<Obj>('bar', 'baz', 2)(obj);` may work, at least.

**Comment by jack-williams** [comment]
@yenshih Does this work?

```ts
const set = <KA extends string, KB extends string, V>
    (keyA: KA, keyB: KB, value: V) =>
    <S extends Record<KA,Record<KB,V>>> (source: S) => source;
```

**Comment by yenshih** [comment]
@jack-williams Wow, it works! Thank you so much!

**Comment by jack-williams** [comment]
@yenshih As Ryan said, inference happens on one call at a time. In your function all the generic parameters are on the outer function, so the inference is the same as if the function was partially applied:
```ts
set('bar', 'baz', 2)
```
You're basically asking TypeScript to infer the type of `S`, without ever having access to a value of type `S` to get an inference from. By the time you do the second application and pass in `obj` all the inference will have been done so it cannot help.
