### ISSUE TITLE
De-prioritize "./index" when picking auto-import path from within the same folder 

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#23598]
Consider a file structure as such:

```tree
|   tsconfig.json
|
\---src
        a.ts
        foo.ts
        index.ts
```

```ts
// src/index.ts

export * from "./foo";
```
```ts
// src/foo.ts

export const foo = 0;
```
in `a.ts`, completion for imported `foo` adds:

```ts
import { foo } from ".";

foo;
```

It seems that `.` or `./index` is the wrong choice here. most likely users want to get to the local implementation in the same folder.

on the other hand, an external library, you want the index instead.. e.g.:

```ts
import { Subject} from ""rxjs"";

```

and not
```ts
import { Subject} from ""rxjs/Subject"";
```
Related: https://github.com/Microsoft/TypeScript/issues/23410

**Comment by j-oliveras** [comment]
@mhegazy In the last two code blocks, the imports has double quotes.

**Comment by mhegazy** [comment]
@andy-ms can we also verify that rxjs case works as expected.
