### ISSUE TITLE
Class properties referencing the class get incorrect class value when using functions defined outside the class

### ISSUE THREAD

**Issue by wavebeem** [microsoft/TypeScript#23609]
**TypeScript Version:**  2.8.3
(also attempted with `typescript@next` at 2018-04-21 23:13:22 UTC)

**Search Terms:**

- "class properties"
- "class props"
- "class prop"
- the title of this issue

**Code**

```ts
function f() {
  return new A();
}

class A {
  static x = f();
}

console.log(A.x);
```

**Expected behavior:**

The function `f` should be able to access the correct value of `A` (a function), not `undefined`, when called inside a class property initializer.

It should work the same way as this code:

```ts
function f() {
  return new A();
}

class A {
  static x;
}

A.x = f();

console.log(A.x);
```

**Actual behavior:**

The class property initializer call to `f()` sees the value of `A` as `undefined` because `A` is assigned to the result of an IIFE which has not completed yet:

```js
function f() {
    return new A();
}
var A = /** @class */ (function () {
    function A() {
    }
    A.x = f();
    return A;
}());
console.log(A.x);
```

Compare with the Babel output for this code which is:

```js
"use strict";

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

function f() {
  return new A();
}

var A = function A() {
  _classCallCheck(this, A);
};

A.x = f();

console.log(A.x);
```

And references the correct value of `A` when `f()` is called.

**Playground Link:** https://www.typescriptlang.org/play/#src=function%20f()%20%7B%0A%20%20return%20new%20A()%3B%0A%7D%0A%0Aclass%20A%20%7B%0A%20%20static%20x%20%3D%20f()%3B%0A%7D%0A%0Aconsole.log(A.x)%3B

 

**Related Issues:**

Closest issues I could find were still not terribly related:

- https://github.com/Microsoft/TypeScript/issues/2457
- https://github.com/Microsoft/TypeScript/issues/2458

**Comment by rbuckton** [comment]
One option is to change our emit for class declarations to the following:

```js
var A = /** @class */ (function () {
    A = function A() {
    }
    A.x = f();
    return A;
}());
```

This would fill in the binding for `A` early (prior to the `return`). Another alternative would be:

```js
var A;
/** @class */ (function () {
    A = function A() {
    }
    A.x = f();
}());
```

**Comment by wavebeem** [comment]
Is it safe to drop the IIFE? Babel didn't use one in the example I was looking at

**Comment by rbuckton** [comment]
No, we use it to scope `_super` and to mark the class body (via `/** @class */`) that is used by typescript service consumers to do things like tree-shaking.

**Comment by wavebeem** [comment]
Gotcha. Thanks for the explanation.

**Comment by RyanCavanaugh** [comment]
https://github.com/microsoft/TypeScript/issues/23609#issuecomment-383687540 is correct; it's spec-compliant to throw in this code.
