### ISSUE TITLE
Incorrect "has no default export", yet code only works that way

### ISSUE THREAD

**Issue by mqudsi** [Microsoft/TypeScript#23605]
**TypeScript Version:**  2.9.0-dev.20180421

**Search Terms:** 

"has no default export"

**Code**

```bash
npm init -y
npm install handsontable
```

```ts
import Handsontable from "handsontable";

function foo() {
    var tableEditor = new Handsontable(document.getElementById("#div"), {});
}
```

Compiled  as

```bash
tsc --lib esnext,dom ts/TableEditor.ts
```

**Expected behavior:**

`tsc` errors out with the following:

```
error TS1192: Module '"/mnt/c/Users/Mahmoud/git/cpsa/cpsa/node_modules/handsontable/handsontable"' has no default export.
```

However, the following code is generated and works:

```javascript
var handsontable_1 = require("handsontable");
⋮
new handsontable_1["default"](...);
```

At the same time, using the following *appears* to work (tsc does not complain, and offers intellisense to indicate that the code is valid by suggesting the arguments for the constructor):

```ts
import * as Handsontable from "handsontable";

function foo() {
    var tableEditor = new Handsontable(document.getElementById("#div"), {});
}
```

generating the following:

```javascript
var Handsontable = require("handsontable");
⋮
new Handsontable(...)
```

and comes back with no errors. However, at runtime this code throws an exception in the browser `Handsontable is not a constructor`.

*Perhaps* the fact that in the "correct" case the imported type was named `Handsontable` and not renamed to `handsontable_1` or similar to avoid a clash is the reason why it doesn't work? Pure conjecture on my part.

**Comment by mqudsi** [comment]
Actually, this is weird. In the console, if I use `-m system` the error about "no default export" goes away. But in the editor (VS 15.7) with module set to SystemJS, that error remains.

**Comment by mqudsi** [comment]
@mhegazy thank you for your reply.

But why is the case where a runtime exception is thrown about `Handsontable is not a constructor' not generate an error at build time?

**Comment by mhegazy** [comment]
If you are using `--module system`, that implicitly tells the compiler to allow for synthetic default imports; that is the compiler knows what system will do at runtime and allows it. 

See https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#support-for-default-import-interop-with-systemjs
and https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#support-for-import-d-from-cjs-form-commonjs-modules-with---esmoduleinterop for mode details.

**Comment by mqudsi** [comment]
I actually wasn't using `--module system` until I was attempting to debug the error thrown (anyway, if I were using `--module system` I wouldn't have experienced the runtime error).
