### ISSUE TITLE
Don't throw away module resolution information

### ISSUE THREAD

**Issue by mqudsi** [Microsoft/TypeScript#23606]
In the process of compiling the typescript sources, `tsc` performs full module resolution of all internal and external imports. While the transpiled JavaScript is formulated in a way where all internal imports can be located in a standard way, the information on how to resolve external imports (via `noderesolution`) is tossed, and a 2nd library must be used to resolve those dependencies (node, SystemJS, etc.).

Can this information be preserved and saved in a machine-readable format so that given the import name (e.g. `@aspnet/signalr`), the exact path that `tsc` resolved it to can be obtained?

It seems like a huge waste to have `tsc` go through all this effort to track down down and resolve all these imports and then have to rely on another library to do that all over again at runtime.

**Comment by mhegazy** [comment]
Can you elaborate on how that information would be used? by what tool? do you have an existing scenario that would benefit from this?

**Comment by mqudsi** [comment]
I know TypeScript is not intended to be an end-to-end system, but exposing that information would make it possible to create a "lite" distribution creation utility that could extract dependencies from the local fs to `wwwroot` and resolve the the imports at runtime.

This wouldn't involve TS compromising on its design goals (it's still a 3rd party utility doing the external dependency management), but TS would provide some hints that would allow packaging/bundling to be significantly faster (no second pass and module resolution via another tool) and simpler (no need TS or JS parsing required).

**Comment by mhegazy** [comment]
The list would not be complete. TS does not look for `.css` or `.html` imports for instance, nor does it understand loaders , e.g. `json!./file.json`, also typescript allows for ambient module declarations to describe the shape of some of these modules, not sure how that would map here.. At the end of the day i think you need another tool to put your "bundle" together.

on any rate, if you have a specific usecase in mind, we would be happy to help. you can get the resolution information today in two ways, either `--traceResolution` or using the compiler API.
