### ISSUE TITLE
HTMLAnchorElement.Methods?

### ISSUE THREAD

**Issue by inad9300** [Microsoft/TypeScript#23608]
In the latest TypeScript version, `HTMLAnchorElement` seems to contain a new property called `Methods`, of type `string`, with no comment explaining what it is.

Since there is no information online about such property, I would say this is about some kind of parsing error, as if "Methods" were the title of the section of the document you parse to create the interfaces for HTML elements.

Please, clarify what this property is or, if it's indeed a mistake, remove it.

**Comment by mhegazy** [comment]
The file is auto generated from webidl from edge. the property is referenced [there](https://raw.githubusercontent.com/Microsoft/TSJS-lib-generator/master/inputfiles/browser.webidl.preprocessed.json). I could not find any reference to it in the spec, so seems like a bug to me, we should remove it.

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by inad9300** [comment]
May I ask an unrelated question regarding the HTML/DOM specs...? You might know this one. Why does no one mention the `style` property on the `HTMLElement` interface (nor on others)? And where does Edge, MDN and others take it from?

**Comment by inad9300** [comment]
This field is no longer present in the latest version.
