### ISSUE TITLE
failed reponse for 'ts.parseJsonConfigFileContent()'

### ISSUE THREAD

**Issue by mapleincode** [microsoft/TypeScript#23607]
I do this.
![image](https://user-images.githubusercontent.com/8831159/39087242-d73ab81c-45d0-11e8-8335-cc5d514a1399.png)

then it fail to reponse...

on my mbp with node v8.11.1.

I install node by nvm, and I reinstall node again and again,but no useful.

**Comment by mapleincode** [comment]
However, I can use this command on my linux system.
![image](https://user-images.githubusercontent.com/8831159/39087256-fca036fe-45d0-11e8-924e-400a72e75fa7.png)

But when I use single folder like`ts.parseJsonConfigFileContent({}, ts.sys,'/Users',{ target: 1, jsx: 1 },'/Users')`, the linux will not be reponse as same as mbp.

**Comment by mapleincode** [comment]
When I move the folder to other directory(like `/test/`), it will run quickly.Is there cached ? I had remove the cache in `~/Library/`.

**Comment by mapleincode** [comment]
Orz....
My home path is `/Users/maple/`
I move the project to `/Users/maple/projects/${project}`, it run.

**Comment by mapleincode** [comment]
```sh
git clone https://github.com/umijs/umi-dva-user-dashboard.git // an object use ts
sudo mv umi-dva-user-dashboard /Users
cd /Users && npm install && npm start
```

I do this in two ubuntu system, and they are fail to reponse both.

**Comment by yesmeck** [comment]
Looks like [`directoryOfCombinedPath`](https://github.com/Microsoft/TypeScript/blob/0179d974031e311cee4fe37a19e61b1c0a8800d7/src/compiler/commandLineParser.ts#L1451) resolves `/Users/maple/` to `/Users`, then `matchFileNames` will search the whole `/Users` dir.

**Comment by yesmeck** [comment]
Because of awesome-typescript-loader pass [pwd](https://github.com/s-panferov/awesome-typescript-loader/blob/ed5d1a3ac9653b6dd21e22cfd51e99e38c62c50a/src/paths-plugin.ts#L78) as `configFileName` to [parseJsonConfigFileContent](https://github.com/Microsoft/TypeScript/blob/0179d974031e311cee4fe37a19e61b1c0a8800d7/src/compiler/commandLineParser.ts#L1424). So if you put project under `/` or `/Users`, build will hang forever.

**Comment by yesmeck** [comment]
Not sure it's bug of TypeScript or awesome-typescript-loader.

cc @s-panferov

**Comment by RyanCavanaugh** [comment]
Hopefully this got figured out since we can't really do much with screenshots of API invocations.
