### ISSUE TITLE
Transpile HTML to Imperative TypeScript

### ISSUE THREAD

**Issue by resistdesign** [Microsoft/TypeScript#2360]
Convert declarative HTML templates to imperative TypeScript commands so you can do things like setup data binding logic/functions/watching from templates at compile time al la WPF/Flex.

**Comment by resistdesign** [comment]
I know, it's a mental request but hey, I thought I'd give it a shot! :)

**Comment by NoelAbrahams** [comment]
Do you have a code example?

**Comment by resistdesign** [comment]
### @NoelAbrahams Here's the basic idea: (pseudo-ish code)

#### MyComp.html:
```html
<div>
    <script>
        public label:String = 'My Comp!';
    </script>
    <button id="btn" label="{ valueObject.label }" />
</div>
```

#### Becomes MyComp.ts:
```typescript
class MyComp // extends HTMLElement (Maybe???)
{
	
	// Genrated Binding Accessor with events.
	protected _label;
	public get label():String
	{
		return this._label;
	}
	public set label( value:String )
	{
		this._label = value;
		this.dispatchEvent(new PropertyChangeEvent('label', value));
	}
	
	public btn:HTMLButtonElement;
	
	// Constructor.
	constructor(){
		this.onCreate();
	}
	
	// Imperative HTML with binding listeners.
	public onCreate(){
		this.btn = new HTMLButtonElement();
		this.addEventListener(PropertyChangeEvent.PROPERTY_CHANGE, function( event:PropertyChangeEvent ){
			if( event.propertyName === 'label' ){
				this.btn.label = this.label;
			}
		});
		this.appendChild( this.btn );
	}
	
}
```

**Comment by resistdesign** [comment]
@NoelAbrahams The Apache Flex compiler already does this kind of thing and is probably a good reference: http://flex.apache.org/dev-sourcecode.html

**Comment by robertknight** [comment]
This isn't something that is really the domain of the TypeScript compiler. React has JSX which is an XML-like syntax that desugars into a tree of JavaScript function calls - see http://facebook.github.io/react/docs/getting-started.html

**Comment by DanielRosenwasser** [comment]
If JSX interests you, @fdecampredon has a fork with JSX support called [jsx-typescript](https://github.com/fdecampredon/jsx-typescript). That said, this still may not be what you're looking for.

Unfortunately, as @robertknight said, this does largely seem out of scope for what we're trying to accomplish.
