### ISSUE TITLE
TS fails to refine mapped type case when switching on key

### ISSUE THREAD

**Issue by bcherny** [Microsoft/TypeScript#23616]
**TypeScript Version:**  2.8.3

**Search Terms:** mapped type, refine, infer, 

**Code**

```ts
type Messages = {
  a: { threadId: number, message: string }
  b: { userIds: number[] }
  c: { threadId: number, userId: number }
}

function a<K extends keyof Messages>(key: K, data: Messages[K]) {
  switch (key) {
    case 'a':
      // Is: Messages[K]
      // Should be: inferred as { threadId: number, message: string }
      console.log(data)
  }
}
```

**Expected behavior:**

After I prove to TS that `key` is `'a'`, TS should infer that `K` is `'a'` and `data` is `{ threadId: number, message: string }`.

**Actual behavior:**

TS fails to infer that `K` is `'a'`, and still believes that `key` is `keyof OutgoingMessages`.

[**Playground Link**](https://www.typescriptlang.org/play/index.html#src=type%20Messages%20%3D%20%7B%0A%20%20a%3A%20%7B%20threadId%3A%20number%2C%20message%3A%20string%20%7D%0A%20%20b%3A%20%7B%20userIds%3A%20number%5B%5D%20%7D%0A%20%20c%3A%20%7B%20threadId%3A%20number%2C%20userId%3A%20number%20%7D%0A%7D%0A%0Afunction%20a%3CK%20extends%20keyof%20Messages%3E(key%3A%20K%2C%20data%3A%20Messages%5BK%5D)%20%7B%0A%20%20switch%20(key)%20%7B%0A%20%20%20%20case%20'a'%3A%0A%20%20%20%20%20%20%2F%2F%20Is%3A%20Messages%5BK%5D%0A%20%20%20%20%20%20%2F%2F%20Should%20be%3A%20inferred%20as%20%7B%20threadId%3A%20number%2C%20message%3A%20string%20%7D%0A%20%20%20%20%20%20console.log(key%2C%20data)%0A%20%20%7D%0A%7D)

**Comment by ahejlsberg** [comment]
That wouldn't be type safe. Consider:

```ts
function foo(x: keyof Messages, m: Messages[keyof Messages]) {
    return a(x, m);
}
```

Here, x has type `"a" | "b" | "c"` and `m` has type `{ threadId: number, message: string } | { userIds: number[] } | { threadId: number, userId: number }`, but there is no assurance that `x` and `m` refer to the same variant. Effectively, what you're assuming to be true is true only when the type inferred for `K` is a unit type, but you can't really express that as a constraint.

**Comment by bcherny** [comment]
@ahejlsberg Thanks for the quick response, and not sure I understand. Your example is clearly unsafe, because as you said, there are two separate constraints. But in my example there is a single polymorphic type (`K`) that the types of `key` and `data` depend on; once `K` is known, shouldn't `Messages[K]` be known too? Sorry if it's a dumb question.

**Comment by DanielRosenwasser** [comment]
His example being an unsafe caller is exactly why your implementation can't reliably make assumptions about the relationship between `key` and `data`. Here's a simplified example:

```ts
const aOrB: "a" | "b" = Math.random() < 0.5 ? "a" | "b";


a(aOrB, { userIds: number[] });
```

Because your second parameter is of type `Messages[K]` and `K` gets instantiated as `"a" | "b"`, anything that's assignable to `Messages["a" | "b"]` (i.e. anything that'a assignable to `{ threadId: number, message: string } | { userIds: number[] }`) is fair game to pass in.

**Comment by bcherny** [comment]
@DanielRosenwasser Thanks for taking the time to explain. What I don't get is we know that `case 'a'` will only evaluate if `K is 'a'`, which implies that `data` has to be `Messages['a']` within that case. It sounds like you're saying that's right, but this kind of generic refinement only happens at the function level?

**Comment by ahejlsberg** [comment]
> What I don't get is we know that case 'a' will only evaluate if K is 'a', which implies that data has to be Messages['a'] within that case.

This is true only when `K` is an exact unit type (e.g. the literal type `"a"`). But `K` could be any subtype of `"a" | "b" | "c"` (such as `"a" | "b"`), which means that `key` could for example have the value `"a"` while `data` is a value of type `Messages["b"]`.

**Comment by bcherny** [comment]
@ahejlsberg @DanielRosenwasser Got it, makes sense. Thanks for taking the time to explain it!
