### ISSUE TITLE
Feature Request: strictier array and string using parenthesis modifiers

### ISSUE THREAD

**Issue by pocesar** [Microsoft/TypeScript#23617]
**TypeScript Version:**  2.7.0-dev.201xxxxx

**Search Terms:** string, array, length, modifier, strict

Some strictly typed languages can catch string / array overflows on compile time against hard coded values, and might help catching some bugs early on. Usually when creating public APIs, sooner or later, you have to implement a max length for either strings or array items, and while you can catch the error AFTER you've made the request, you would have been able to avoid it at the first place.
This helps with validation libraries as well, such as Joi, that can create highly dynamic object schemas.

**Code**

```ts
type LimitedString = string(3);

let limitedString: LimitedString = '1234' // error, LimitedString expects at most 3 characters
limitedString = '12' // would work (or not?)

type LimitedArray = Array(3)<{ something: string }>

let limitedArray: LimitedArray = [{ something: '' }, { something: '' }, { something: '' }, { something: '' }] // error, LimitedArray expects at most 3 members

type LookupStates = {
  [index: string(2)]: string
}

// This is useful when you have a normalized array or lookup table, for example
const states: LookupStates = {
  'KS': 'Kansas',
  'IA': 'Iowa'
}

states['IOWA'] // error
```

**Comment by j-oliveras** [comment]
Array case is already supported:
```ts
type LimitedArray = [{ something: string }, { something: string }, { something: string }];

let limitedArray: LimitedArray = [{ something: '' }, { something: '' }, { something: '' }, { something: '' }]
```

`limitedArray` has an error:
```
Type '[{ something: string; }, { something: string; }, { something: string; }, { something: string; }]' is not assignable to type '[{ something: string; }, { something: string; }, { something: string; }]'.
  Types of property 'length' are incompatible.
    Type '4' is not assignable to type '3'.
```

Is not the same the type `string[]` and `[string]` (the first is an array without limited length, the second is and array with only one string item).

For strings, exists a pull request by @weswigham experimenting with regex validated strings types: #21044.

**Comment by pocesar** [comment]
the only problem with both approaches is that either the regex guard than the tuple type have problems with documentation (and plus the verbosity). what if the array is 30 items long? how to show the "quickinfo" in an IDE for the regex guard type? you won't know the format until you read the typings file...

**Comment by mhegazy** [comment]
Do not think we should be mixing strings and arrays, there is really no reason why these scenarios should be combined.

Arrays with fixed length are handled to an extend with tuples since they now have fixed length (see https://github.com/Microsoft/TypeScript/pull/17765).  You can already today have a tuple-like type using `Array`. e.g. 
```ts
interface FixedLengthArray<T, L extends number> extends Array<T> { 
    "0": T;
    length: L;
}
let limitedArray: FixedLengthArray<E, 3> = [{ something: '' }, { something: '' }, { something: '' }, { something: '' }] // error, 4 is not assignable to 3
```

Strings should be handled with regex validated strings types: #21044 as noted by @j-oliveras.
