### ISSUE TITLE
Destructuring breaks tagged union case inference

### ISSUE THREAD

**Issue by bcherny** [Microsoft/TypeScript#23613]
**TypeScript Version:** 2.8.3

**Search Terms:**  union, destructure

**Code**

```ts
type Message =
    { type: 'sendMessageToThread', data: { threadId: number, message: string }}
  | { type: 'createThread', data: { userIds: number[] }}
  | { type: 'addUserToThread', data: { threadId: number, userId: number }}

// Good case
function a(message: Message) {
  switch (message.type) {
    case 'sendMessageToThread':
      console.log(message.data.threadId)
  }
}

// Bad case
function b({ type, data }: Message) {
  switch (type) {
    case 'sendMessageToThread':
      // Error: Property 'threadId' does not exist on type
      console.log(data.threadId)
  }
}
```

**Expected behavior:**

TS should infer which case the tagged union falls into regardless of whether or not the parameter is destructured. `data` should be inferred as `{ threadId: number, message: string }`.

**Actual behavior:**

`data` is inferred as the union of all `data` values in `Message`. 

[**Playground Link**](https://www.typescriptlang.org/play/index.html#src=type%20Message%20%3D%0A%20%20%20%20%7B%20type%3A%20'sendMessageToThread'%2C%20data%3A%20%7B%20threadId%3A%20number%2C%20message%3A%20string%20%7D%7D%0A%20%20%7C%20%7B%20type%3A%20'createThread'%2C%20data%3A%20%7B%20userIds%3A%20number%5B%5D%20%7D%20%7D%0A%20%20%7C%20%7B%20type%3A%20'addUserToThread'%2C%20data%3A%20%7B%20threadId%3A%20number%2C%20userId%3A%20number%20%7D%7D%0A%20%20%7C%20%7B%20type%3A%20'removeUserFromThread'%2C%20data%3A%20%7B%20threadId%3A%20number%2C%20userId%3A%20number%20%7D%20%7D%0A%0Afunction%20a(message%3A%20Message)%20%7B%0A%20%20switch%20(message.type)%20%7B%0A%20%20%20%20case%20'sendMessageToThread'%3A%0A%20%20%20%20%20%20console.log(message.data.threadId)%0A%20%20%7D%0A%7D%0A%0Afunction%20b(%7B%20type%2C%20data%20%7D%3A%20Message)%20%7B%0A%20%20switch%20(type)%20%7B%0A%20%20%20%20case%20'sendMessageToThread'%3A%0A%20%20%20%20%20%20%2F%2F%20Error%3A%20Property%20'threadId'%20does%20not%20exist%20on%20type%0A%20%20%20%20%20%20console.log(data.threadId)%0A%20%20%7D%0A%7D)

**Comment by bcherny** [comment]
Thanks for digging up those issues @mhegazy. This seems like a real issue, so I'm not sure why those were closed out. Maybe it's worth keeping one of them open to track the issue? This is pretty surprising behavior from a user's point of view.

**Comment by mhegazy** [comment]
I would merge this in https://github.com/Microsoft/TypeScript/issues/9998. these are design limitation for how control flow analysis is implemented.

**Comment by bcherny** [comment]
Sounds good to me.
