### ISSUE TITLE
Get a way to represent iterable types while keeping ES5 compatiblity

### ISSUE THREAD

**Issue by saschanaz** [Microsoft/TypeScript#23610]
**TypeScript Version:**  2.7.0-dev.201xxxxx

**Search Terms:** 

**Code**

```ts
// Some standard web interfaces or third-party libraries support Symbol.iterator

interface SomeStandardInterface {
  method(iterable: Iterable<number>): void; // Error, no Iterable on lib.es5.d.ts
}

interface SomeThirdPartyInterface {
  [Symbol.iterator](): IterableIterator<number>; // Error, no Symbol, no IterableIterator
}
```

**Expected behavior:** We should provide a clean way to write iterable types on ES5-compatible type definition files.

**Actual behavior:** No such way. Some [DefinitelyTyped definitions e.g. @types/node](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/index.d.ts) workaround this by defining Symbol.iterator and empty Iterable* interfaces.

**Related Issues:**

Microsoft/TSJS-lib-generator#419
#13031 
#19806

**Comment by mhegazy** [comment]
[Lib references](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Triple-Slash%20Directives.md#-reference-lib-) is meant to address these issues.. unfortunately there is not an easy easy way to conditionally define a declaration. it is either there or not. at least with lib references the management of these dependencies will not involve the user.

Possibly related to https://github.com/Microsoft/TypeScript/issues/2900
