### ISSUE TITLE
Shaping the future of Modules for TypeScript

### ISSUE THREAD

**Issue by unional** [microsoft/TypeScript#23614]
Just a loud and small reminder.

Is there someone from the TypeScript community participate in the active group of:

https://github.com/nodejs/modules

Would like to see whatever that team come up with will be aligned or usable with TypeScript. 🌷

**Comment by DanielRosenwasser** [comment]
@weswigham and I are participants.

**Comment by DanielRosenwasser** [comment]
Just to add: if you have any specific things in mind so that TypeScript and Node continue to play well together, let us know. 😃
