### ISSUE TITLE
Disallow non-null assertion to null itself

### ISSUE THREAD

**Issue by Hoishin** [Microsoft/TypeScript#23619]
**TypeScript Version:** 
Version 2.9.0-dev.20180422

**Search Terms:** 
"non-null assertion null"

**Code**

```ts
type Hoge = 'hoge';

const fuga: Hoge = 'hoge'; // it works, of course
const foo: Hoge = null; // error TS2322: Type 'null' is not assignable to type '"hoge"'
const bar: Hoge = null!; // wait, it works?
```

**Expected behavior:**
Throws error if non-null assertion operator is used with `null`

**Actual behavior:**
Non-null assertion operator is allowed to be used with `null`, and it is confusing.

**Playground Link:** 
https://www.typescriptlang.org/play/#src=type%20Hoge%20%3D%20'hoge'%3B%0D%0A%0D%0Aconst%20fuga%3A%20Hoge%20%3D%20'hoge'%3B%20%2F%2F%20it%20works%2C%20of%20course%0D%0Aconst%20foo%3A%20Hoge%20%3D%20null%3B%20%2F%2F%20error%20TS2322%3A%20Type%20'null'%20is%20not%20assignable%20to%20type%20'%22hoge%22'%0D%0Aconst%20bar%3A%20Hoge%20%3D%20null!%3B%20%2F%2F%20wait%2C%20it%20works%3F

**Related Issues:**
404

**Comment by RyanCavanaugh** [comment]
This is a useful pattern when you want to give something a fake initializer.

We certainly wouldn't issue a breaking change to ban something just because someone found it confusing.
