### ISSUE TITLE
Union types borked

### ISSUE THREAD

**Issue by rolyp** [Microsoft/TypeScript#2362]
class Empty {
       dummy (): void {
       }
    }

    type Behaviour = Empty | Empty
 
    var b: Behaviour = 'hello'

is apparently fine, although `Empty | Empty` should be the same type as `Empty`.

**Comment by ahejlsberg** [comment]
Not sure what problem you're seeing. I get the following error when I compile your example (using the compiler in master):
```
t.ts(8,5): error TS2322: Type 'string' is not assignable to type 'Empty'.
  Property 'dummy' is missing in type 'String'.
```
Are you not getting this error? Which version of the compiler are you using?

**Comment by rolyp** [comment]
Sorry about this. Must have made a mistake yesterday. I'll try to be more careful next time :)
