### ISSUE TITLE
Support new flags (2.9)

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#23627]
* [x] `--keyofStringsOnly` added in https://github.com/Microsoft/TypeScript/pull/23592
* [x] `--declarationMap` from https://github.com/Microsoft/TypeScript/pull/22658
* [x] `--resolveJsonModule` from https://github.com/Microsoft/TypeScript/pull/22167
* [x] New lib file added in https://github.com/Microsoft/TypeScript/pull/23785

See checklist for work needed: https://github.com/Microsoft/TypeScript/wiki/Release-Activities#new-compiler-option-added

**Comment by weswigham** [comment]
Also `--declarationMap`
