### ISSUE TITLE
Improve completions at `x <` (type arguments or less than)

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#23631]
**TypeScript Version:**  master

**Code**

```ts
x < /**/
```

**Expected behavior:**

If `x` is a number or string, get completions for values.
If `x` is a function, get completions for types.

**Actual behavior:**

Get completions for both.

**Comment by mhegazy** [comment]
I think this is more of signature help. we used to have this in TS 1.0, but never rewrote the feature. the idea is it treats `<` like `(` in a function call, and shows you the list of applicable type parameters. see commented out section inhttps://github.com/Microsoft/TypeScript/commit/102da2d80a83d340a8bbcdea3814c7f1b87dd944#diff-77414312b9c8809bd4ba9e31e0c5f940R8 for more context.

**Comment by andy-ms** [comment]
As noted by @sheetalkamat in https://github.com/Microsoft/TypeScript/pull/23632#discussion_r183839955 there is a function `isPossiblyTypeArgumentPosition` that should be able to handle this.

**Comment by andy-ms** [comment]
Signature help part done in #24138
