### ISSUE TITLE
Spread arguments length check doesn't work with function overloads

### ISSUE THREAD

**Issue by bowenni** [Microsoft/TypeScript#23637]
**TypeScript Version:**  2.9.0-dev.20180422

**Search Terms:** spread, overload

**Code**
```ts
function foo(): void;
function foo(...args: {}[]): void {}

function bar(...args: {}[]) {
  foo(...args);
}
```

**Expected behavior:**
No Errors.

**Actual behavior:**
`error TS2556: Expected 0 arguments, but got 1 or more.`
If I just swap the order of the declarations of function foo it works.

**Playground Link:**  
https://www.typescriptlang.org/play/#src=function%20foo()%3A%20void%3B%0D%0Afunction%20foo(...args%3A%20%7B%7D%5B%5D)%3A%20void%20%7B%7D%0D%0Afunction%20bar(...args%3A%20%7B%7D%5B%5D)%20%7B%0D%0A%20%20foo(...args)%3B%0D%0A%7D

**Related Issues:**
https://github.com/Microsoft/TypeScript/pull/20071 is the fix for excess spread operator check.
https://github.com/Microsoft/TypeScript/issues/21906 is very close to my issue, but not quite the same.

**Comment by bowenni** [comment]
Thanks for the quick reply! Adding a new overload solved the problem for me.

Would you consider `The implementation signature is not considered part of the overloads for the method` intended or bug? It feels counter intuitive that I have to explicitly declare a new overload even though I have an implementation already.

**Comment by AlCalzone** [comment]
Having the exposed overloads separate from the implementation allows to expose nice and cleanly typed overloads while having an ugly internal implementation signature that just exists to match all the “official” function signatures. 
So definitely a feature IMO
