### ISSUE TITLE
Iterator value is not an entry object, creating map

### ISSUE THREAD

**Issue by rolyp** [Microsoft/TypeScript#2363]
var m = new Map<number, number>([5, 6])

should be ill-typed. Fails at runtime with 

    Uncaught TypeError: Iterator value apply is not an entry object

Needs to be something like

    var m = new Map<number, number>([[5, 6]])

**Comment by danquirk** [comment]
The latest bits error on this code:
```
> type a.ts
var m = new Map<number, number>([5, 6])
> tsc a.ts
a.ts(1,9): error TS2346: Supplied parameters do not match any signature of call target.
```
