### ISSUE TITLE
Bug from #23592 - Type 'keyof U & K' does not satisfy the constraint 'string | number | symbol'

### ISSUE THREAD

**Issue by kpdonn** [Microsoft/TypeScript#23648]
**TypeScript Version:**  2.9.0-dev.20180424

**Search Terms:** 
keyof, intersection, conditional types

**Code**

```ts
type Example<T, U> = { [K in keyof T]: K extends keyof U ? UnexpectedError<K> : NoErrorHere<K> }

type UnexpectedError<T extends PropertyKey> = T
type NoErrorHere<T extends PropertyKey> = T
```

**Expected behavior:**
No errors. 

**Actual behavior:**
Error on `K` in `UnexpectedError<K>` with message 
```
Type 'keyof U & K' does not satisfy the constraint 'string | number | symbol'.
  Type 'keyof U & K' is not assignable to type 'symbol'.
```

**Playground Link:** 
[Link](https://www.typescriptlang.org/play/#src=type%20Example%3CT%2C%20U%3E%20%3D%20%7B%20%5BK%20in%20keyof%20T%5D%3A%20K%20extends%20keyof%20U%20%3F%20UnexpectedError%3CK%3E%20%3A%20NoErrorHere%3CK%3E%20%7D%0D%0A%0D%0Atype%20UnexpectedError%3CT%20extends%20PropertyKey%3E%20%3D%20T%0D%0Atype%20NoErrorHere%3CT%20extends%20PropertyKey%3E%20%3D%20T%0D%0A) (no error in playground)

**Related Issues:**
#23592

**Comment by ahejlsberg** [comment]
The issue here is that we don't lift constraints over intersection types. Here's a simpler repro:

```ts
function foo<T extends string | number, U extends string | number>(x: T & U) {
    let y: string | number = x;  // Error, but shouldn't be
}
```

We need to lift the individual constraints of `T` and `U` such that the intersection type `T & U` appears to have the constraint `string | number` (formed by intersecting the individual constraints of `T` and `U`).

**Comment by ahejlsberg** [comment]
The reason this shows up with #23592 is that we now have union type constraints for `keyof T`.

**Comment by ahejlsberg** [comment]
@mhegazy Do you recall if we already have an issue for this?

**Comment by mhegazy** [comment]
> @mhegazy Do you recall if we already have an issue for this?

do not think i have seen this one before.
