### ISSUE TITLE
Interface Crypto does not implement RandomSource, so Crypto.getRandomValues is not generic

### ISSUE THREAD

**Issue by ViceIce** [Microsoft/TypeScript#23646]
**TypeScript Version:**  2.8.3

**Search Terms:**

* getRandomValues

**Code**

```ts
crypto.getRandomValues(new Uint32Array(2)).join('')
```

**Expected behavior:**
Get a concated string of 2 random uint32.

**Actual behavior:**
Compiler error:
`Property 'join' does not exist on type 'Int8Array | Int16Array | Int32Array | Uint8Array | Uint16Array | Uint32Array | Uint8ClampedArray ...'.
  Property 'join' does not exist on type 'DataView'.`

Looks like Microsoft/TSJS-lib-generator#278 is not included or overwritten by someone.
I suggest to simply extend the `Crypto` interface from the `RandomSource` interface.

**Playground Link:**  

https://www.typescriptlang.org/play/#src=crypto.getRandomValues(new%20Uint32Array(2)).join('')

**Related Issues:**
#17610

**Comment by a-tarasyuk** [comment]
@ViceIce Based on spec - [Crypto#getRandomValues](https://www.w3.org/TR/WebCryptoAPI/#dfn-Crypto-method-getRandomValues), I think, we do not need to extend _Crypto interface from the RandomSource interface._

```WebIDL
ArrayBufferView getRandomValues(ArrayBufferView array);
```
`getRandomValues` returns `ArrayBufferView`

> [ArrayBufferView](https://developer.mozilla.org/en-US/docs/Web/API/ArrayBufferView) is a helper type representing any of the following JavaScript TypedArray types: Int8Array, Uint8Array, Uint8ClampedArray, Int16Array, Uint16Array, Int32Array, Uint32Array, Float32Array, Float64Array or DataView. This is a helper type to simplify the specification, it isn't an interface and there are no objects implementing it.
> [`typedef ArrayBufferView`](https://heycam.github.io/webidl/#ArrayBufferView)

`ArrayBufferView` [`interface`](https://github.com/Microsoft/TypeScript/blob/master/lib/lib.d.ts#L1431) defined like this

```typescript
interface ArrayBufferView {
    /**
      * The ArrayBuffer instance referenced by the array.
      */
    buffer: ArrayBufferLike;

    /**
      * The length in bytes of the array.
      */
    byteLength: number;

    /**
      * The offset in bytes of the array.
      */
    byteOffset: number;
}
```

As we can see, it is `interface` which does not have `join` method, but the spec says that `ArrayBufferView` - **is a helper type**, and I suppose that it should look like so

```typescript
type ArrayBufferView = Int8Array | Uint8Array | Uint8ClampedArray | Int16Array | Uint16Array | Int32Array | Uint32Array | Float32Array | Float64Array | DataView;
```
However, `DataView` also does not provide `.join` method. @mhegazy what do you think about this case?

**Comment by ViceIce** [comment]
At typescript 2.7 `Crypto` interface was defined at `lib.d.ts`:

```ts
interface Crypto extends Object, RandomSource {
    readonly subtle: SubtleCrypto;
}
interface RandomSource {
    getRandomValues<T extends Int8Array | Uint8ClampedArray | Uint8Array | Int16Array | Uint16Array | Int32Array | Uint32Array>(array: T): T;
}
```

With typescript 2.8 it has changed to

```ts
interface Crypto {
    readonly subtle: SubtleCrypto;
    getRandomValues(array: Int8Array | Int16Array | Int32Array | Uint8Array | Uint16Array | Uint32Array | Uint8ClampedArray | Float32Array | Float64Array | DataView | null): Int8Array | Int16Array | Int32Array | Uint8Array | Uint16Array | Uint32Array | Uint8ClampedArray | Float32Array | Float64Array | DataView | null;
}
```

This looks wrong to me.

**Comment by a-tarasyuk** [comment]
@ViceIce Seems that the latest changes follow the [**spec**](https://www.w3.org/TR/WebCryptoAPI/#dfn-Crypto) 

```WebIDL
[Exposed=(Window,Worker)]
interface Crypto {
  [SecureContext] readonly attribute SubtleCrypto subtle;
  ArrayBufferView getRandomValues(ArrayBufferView array);
};
```
`Crypto` does not extend `RandomSource`.

**Comment by ViceIce** [comment]
Ok, aggreed.

At https://www.w3.org/TR/WebCryptoAPI/#Crypto-method-getRandomValues step 4. it says, that it returns the given array.

So maybe we can make this method generic? Like before, but with the new types. So that the return value will be like the given type and not a multi type?

```ts
interface Crypto {
    readonly subtle: SubtleCrypto;
    type ArrayBufferView = Int8Array | Int16Array | Int32Array | Uint8Array | Uint16Array | Uint32Array | Uint8ClampedArray | Float32Array | Float64Array | DataView | null;
    getRandomValues<T extends ArrayBufferView = ArrayBufferView>(array: T): T;
}
```

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by mrowles** [comment]
I still cannot reference `crypto.getRandomValues` or straight `getRandomValues`, throws unknown library in NodeJS after compilation. Has anyone figured this out nicely?
