### ISSUE TITLE
Go to definition on derived class without constructor being new'd takes users to base constructor

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#23641]
```ts
abstract class X {
  constructor() {}
}
class Y extends X {}

function q() {
  return new Y();
          // ^ jump to definition goes to
          //   X's constructor
}
```

I think this should give two definition points: `X`'s constructor, and `Y`. This should happen regardless of whether `X` is abstract.

CC @wycats

**Comment by andy-ms** [comment]
Should we handle the following situation similarly?
```ts
function a() {}

const b = a;

b();
```
Currently we go to `a`, because we try to go to the signature at a call site, and only `a` has a signature.
