### ISSUE TITLE
Feature: C# style `this.` property initialization in constructor()

### ISSUE THREAD

**Issue by mindplay-dk** [Microsoft/TypeScript#2364]
I'm aware of the following syntax, where member declaration gets rolled into the constructor signature:

```Typescript
class Foo {
    constructor(public bar: string) {}
}
```

I would strongly prefer the C# style `this.` syntax, e.g.:

```Typescript
class Foo {
    public bar: string;

    constructor(this.bar) {}
}
```

As per the existing syntax, this would be effectively identical to:

```Typescript
class Foo {
    public bar: string;

    constructor(bar: string) {
        this.bar = bar;
    }
}
```

The current syntax is very compact - but it's too compact. I really don't like the way the compound declaration/initialization syntax hides a member declaration - I'd prefer a syntax that summarizes all my class members in one place. It also is not very source-control (or diff) friendly.

The argument type would be inferred from the member declaration.

**Comment by danquirk** [comment]
This kind of change doesn't add enough value given the cost. The current parameter property syntax works well for compact class declarations and we haven't really heard many complaints about it. If you prefer having an explicit list of members in a different place then the non-parameter property syntax only requires a few extra lines over your proposal.

**Comment by basarat** [comment]
>  It also is not very source-control (or diff) friendly.

You can put the arguments on multiple lines.

**Comment by basarat** [comment]
"Initialize from constructor. " tooling would be helpful.

**Comment by fletchsod-developer** [comment]
Well having "this" can help to see list of objects on the pop-up intellisense in Visual Studio.  Just sayiing.
