### ISSUE TITLE
Enhancement request - provide compile time "include" support

### ISSUE THREAD

**Issue by dmcweeney** [Microsoft/TypeScript#23654]
Hi,

Would love to have the ability to include a snippit of TS code at compile time, that gets converted to js and piped to the output file.

eg. 
include ".\..\Common\MyBusinessExtensions.ts"

The use case is for building stored procedures, triggers and udfs for Cosmos db. A good synopsis of the issues this would address is outlined here: https://benoitpatra.com/2016/07/09/programming-well-structured-javascript-stored-procedures-for-documentdb-with-typescript-and-systemjs/

I've tried the workaround suggested in the article and have had a lot of problems with it, thus the request here.

Thanks, Donal

**Comment by andy-ms** [comment]
Would this be identical to compiling it normally and using `fs.readFileSync("..\Common\MyBusinessExtensions.js")`?

**Comment by dmcweeney** [comment]
@andy-ms I'm not 100% sure, but 99% sure that it is not, as the SPs, triggers, udfs do not have access to an underlying filesystem, just a couple of context objects passed in by Cosmos db. And the SP needs to be encapsulated as a single function.
[]( https://docs.microsoft.com/en-us/azure/cosmos-db/programming#runtime-support

)

**Comment by andy-ms** [comment]
I'm not familiar with that database, but it sounds like you're saying you lack a module system and would rather `#include` files as in C.
Assuming all you need is to be able to get JS code that doesn't contain imports, this is actually supported by the `--outFile` option, or preferrably you could use imports in your TS and bundle the JS at the end using something like webpack or rollup.

**Comment by dmcweeney** [comment]
@andy-ms 
webpack and rollup effectively do what that sample in the original article did which is not ideal.
The --outfile option (as far as I know) just bundles all the ts output for a project into a single js file, which is not what is wanted either.

**Comment by andy-ms** [comment]
Could you try and explain what you want in a way that isn't dependent on any particular database?

**Comment by dmcweeney** [comment]
@andy-ms as requested... hope "what I want" is clear...

I need to build some single javascript functions that will run in a sandboxed environment, and that sandboxed environment does not provide any support for imports/modules/loaders. All the javascript needs to be packaged within a single function within a single file. Nested functions are supported.

TypeScript will allow me to do this today. 

However, I would like to achieve some level of code reusability by breaking out reusable functions into separate .ts files, so they can be compiled and tested independently, and shared among the functions that will get deployed.

What I am missing from TypeScript is the ability to include these functions inline at compile time, so the whole lot can be compiled as an standalone unit, and spewed out into a single js file. This ability would be akin to the old C preprocessor #include directive.

Take the following simple TS example:

Include file computeTax.ts in the includes folder:

```
export function computeTax( salary:number ): number
{
	// do something useful
	return salary * 0.99 ;
}
```
Stored procedure code in sp.ts

```
function myStoredProcedure( arg: string[] )
{
	doQuery({});

	function doQuery(options)
	{
		// do query code and compute tax
		var tax = computeTax( 100 ) ;
	}

	**TSMAGICINCLUDE** ".\..\includes\computeTax.ts"
}
```
The output sp.js is generated as follows:

```
function myStoredProcedure(arg) {
    doQuery({});
    function doQuery(options) {
        // do query code and compute tax
        var tax = computeTax(100);
    }
    
    // included inline from ".\..\includes\computeTax.ts"
    function computeTax(salary) {
        // do something useful
        return salary * 0.99;
    }
}
```
I hope this makes it clear.

Thanks, Donal

**Comment by andy-ms** [comment]
Well, you could do this:
**a.ts**
```ts
function myStoredProcedure(arg: number) {
    return computeTax(arg);
}
```
**b.ts**
```ts
// Note no 'export' keyword -- this is global.
function computeTax(salary: number): number {
    return salary * 0.99;
}
```
**tsconfig.json**
```json
{
    "compilerOptions": {
        "outFile": "bin/out.js"
    }
}
```

The `out.js` produced is:
```js
function myStoredProcedure(arg) {
    return computeTax(arg);
}
function computeTax(salary) {
    return salary * 0.99;
}
```

Now all you would have to do to make it a single function is to wrap it somehow:
```js
function main(...args) {
    return myStoredProcedure(...args);

    <<<<out.js here>>>
}
```

**Comment by dmcweeney** [comment]
@andy-ms Thanks for the input - I've actually hacked something together with gulp but there are some flaws in it. 
One of the problems with above solution is the tsconfig per folder - actually the outFile - if I want to create many different outfiles, I need a folder for each. And then we need the gulp script to do the wrapping.

It would be so nice and clean if the compiler did it for us, and was able to flag errors if export/import were used in the code!

**Comment by andy-ms** [comment]
> It would be so nice and clean if the compiler did it for us, and was able to flag errors if export/import were used in the code!

It does flag them:
```
src/a.ts:4:1 - error TS6131: Cannot compile modules using option 'outFile' unless the '--module' flag is 'amd' or 'system'.

4 export const x = 0;
```

If you're doing many builds you may want to avoid using `tsconfig` to set an outfile target and rely entirely on the build tool. It's still useful to store compiler options (like `"strict": true`) in the tsconfig though, since gives you errors in the editor. (Editors don't know about your build system, but do look for `tsconfig`.)

**Comment by dmcweeney** [comment]
@andy-ms thanks for the insights. We are using VS 2017 as editor and build system. Also using VSTS build tasks. So minimum amount of manual build maintenance is required.
I'm guessing this request can be closed...
