### ISSUE TITLE
Dedicated worker postMessage marked as depricated

### ISSUE THREAD

**Issue by efrancis** [Microsoft/TypeScript#23653]
**TypeScript Version:**  working with current github version, error introduce with commit of the 29th of March 2018 (79e5e79ef7724066889fbce97e9e6d6db4e746b5)

**Search Terms:** worker, postmessage, deprecated

**Issue**
files *lib.dom.d.ts* and *lib.webworker.d.ts* mark the method "postMessage" of the "Worker" interface as being deprecated.
As I cannot find any information to support the claim that postMessage is depricated, nor do I see any new alternative method that should be used instead, I believe that this @deprecated has been inserted in the wrong place.

**Playground Link:** Just basing myself on the files in the repository here, no link available

**Comment by mhegazy** [comment]
The file is auto-generated from the webidl definition of edge. they have marked it as deprecated, and that is why it shows up as such. we are moving to use the standard webidl where deprecated APIs will just not be added. so this should be fixed in the next release.

**Comment by mhegazy** [comment]
Meanwhile, PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.
