### ISSUE TITLE
Cannot map over intersection of `string` with string literal (e.g., `"a" & string`)

### ISSUE THREAD

**Issue by jcalz** [Microsoft/TypeScript#23651]
**TypeScript Version:**  2.9.0-dev.20180424 but reproducible as far back as I tested (2.7)

**Search Terms:** intersection, mapped, empty, string, literal

**Code**
```ts
type X = { [K in "a" & string]: 1 };
```
**Expected behavior:**
`X` should be equivalent to `{ a: 1 }`.

**Actual behavior:**
`X` is `{}`.

**Playground Link:** [link](https://www.typescriptlang.org/play//#src=type%20WitnessSame%3CT%20extends%20V%2C%20U%20extends%20T%2C%20V%3DU%3E%20%3D%20true%0D%0A%0D%0Atype%20Y%20%3D%20%7B%20%5BK%20in%20%22a%22%5D%3A%201%20%7D%0D%0Atype%20Okay%20%3D%20WitnessSame%3CY%2C%20%7B%20a%3A%201%20%7D%3E%20%2F%2F%20okay%0D%0A%0D%0Atype%20X%20%3D%20%7B%20%5BK%20in%20%22a%22%20%26%20string%5D%3A%201%20%7D%0D%0Atype%20NotOkay%20%3D%20WitnessSame%3CX%2C%20%7B%20a%3A%201%20%7D%3E%20%2F%2F%20error)

**Related Issues:**
maybe #12114 for mapped types in general
maybe #23592 for making me notice this
maybe #16386 because I always think everything would be fixed by absorption 
maybe #9410 although back then these things were treated as `never` everywhere

---

The recent #23592 change allowing mapping over `number` and `symbol` keys caused some of my existing code to break, and the obvious fix for some of them was to restrict those instances where I really expected `string`s from `keyof T` to `(keyof T) & string`.  But that doesn't work.  It looks like `"a" & string` gets treated like `never` inside of a mapped type key set, but like `"a"` everywhere else.  [Absorption](https://github.com/Microsoft/TypeScript/issues/16386) would fix this, but barring that, maybe some less aggressive simplification inside mapped types?

Workaround: Since TS2.8 it is possible to use [`Extract<T, U>`](https://github.com/Microsoft/TypeScript/blob/v2.8.2/lib/lib.d.ts#L1373-L1376) instead of  `T & U` in some instances.  In this case it can reduce the intersection before the mapping:  `type X = { [K in Extract<'a',string>]: 1 }` is equivalent to `{ a: 1 }` as expected.

**Comment by mhegazy** [comment]
intersections are not aggressively reduced at the moment. there are some reduction that takes place when the intersection is used in a union (e.g. intersection of two literals go to `never`). in general we should be doing supertype reduction on intersections.

**Comment by mhegazy** [comment]
we should add support for reducing `string|number|enum & literal`, `enum & number`

**Comment by mhegazy** [comment]
Same issue as https://github.com/Microsoft/TypeScript/issues/9410

**Comment by jcalz** [comment]
Is it the same issue?  It seems related, but that one looks like it's fixed...

**Comment by mhegazy** [comment]
Should be fiexed by https://github.com/Microsoft/TypeScript/pull/23751
