### ISSUE TITLE
Update documentation to mention that --strictNullChecks flag is necessary for --strictPropertyInitialization to have an effect 

### ISSUE THREAD

**Issue by loicraux** [Microsoft/TypeScript#23659]
**TypeScript Version:**
2.7.0 and above.

**Search Terms:** 
strictNullChecks strictPropertyInitialization

**Code**
```ts
class C {
    foo: number;
    bar = "hello";
    baz: boolean;

    constructor() {
        this.foo = 42;
    }
}
```

**Expected behavior:**
TS documentation should mention that `--strictNullChecks` flag is needed for `--strictPropertyInitialization` one to actually have an effect.
This would properly document the actual code change in this [commit](https://github.com/Microsoft/TypeScript/commit/8cbff0159df1792e7d3bd87946b99a4eed042e4c#diff-c3ed224e4daa84352f7f1abcd23e8cca) : 
![image](https://user-images.githubusercontent.com/3329077/39200931-d0c49416-47ed-11e8-991a-12fae9736230.png)
This was clearly mentionned in the [corresponding PR](https://github.com/Microsoft/TypeScript/pull/20075) description.
Also @mihailik [suggested that a warning could also be emitted](https://github.com/Microsoft/TypeScript/pull/20075#issuecomment-346058031). Has this been done?

**Actual behavior:**
This is mentioned nowhere in the documentation.
Documentation for `--strictPropertyInitialization` is _Ensure non-undefined class properties are initialized in the constructor._.
To determine if a class property is _non-undefined_, `--strictNullChecks` flag must be turned on.

**Playground Link:**
http://www.typescriptlang.org/play/#src=class%20C%20%7B%0D%0A%20%20%20%20foo%3A%20number%3B%0D%0A%20%20%20%20bar%20%3D%20%22hello%22%3B%0D%0A%20%20%20%20baz%3A%20boolean%20%7C%20undefined%3B%0D%0A%0D%0A%20%20%20%20constructor()%20%7B%0D%0A%20%20%20%20%20%20%20%20this.foo%20%3D%2042%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aconst%20foo%3A%20string%20%3D%20%22fdsf%22%3B

**Related Issues:**
I found no existing issue for updating the documentation about this.

**Comment by mhegazy** [comment]
A PR to warn for use of `--strictPropertyInitialization` with no `--strictNullChecks` would be welcomed.

**Comment by mhegazy** [comment]
Also a PR to update the docs would be welcomed, the handbook is at https://github.com/Microsoft/TypeScript-Handbook

**Comment by a-tarasyuk** [comment]
> A PR to warn for use of --strictPropertyInitialization with no --strictNullChecks would be welcomed

@mhegazy  I'll make PR for that case.
