### ISSUE TITLE
Allow narrowing generic parameters in conditional types

### ISSUE THREAD

**Issue by SimonMeskens** [Microsoft/TypeScript#23665]
```TypeScript
    type Lambda1 = () => number;
    type Lambda2 = <T>() => Array<T>;

    type Test1<T> = T extends <U>() => infer V ? V : never;

    type T1 = Test1<Lambda1>; // 'number'
    type T2 = Test1<Lambda2>; // '{}[]'

    type Test2<T, R> = T extends <U = R>() => infer V ? V : never;

    type T3 = Test2<Lambda1, string>; // 'number'
    type T4 = Test2<Lambda2, string>; // '{}[]'

    type Test3<T, R> = T extends <U extends R>() => infer V ? V : never;

    type T5 = Test3<Lambda1, string>; // 'number'
    type T6 = Test3<Lambda2, string>; // '{}[]'
```

I'd expect either or both T4 or T6 to be `string[]`. As it is, there seems to be no way to specify the generic type inside of a conditional. I think this is a proposal, but if there's an existing way to turn T4 or T6 into `string[]`, this can be closed, I don't think there is.

**Comment by SimonMeskens** [comment]
Yeah, this issue came out of experiments with HKTs. If I could get either Test2 or Test3 into the language, we would get proper type level pattern matching, which allows us to do lots of cool things, one of which is improving inference for HKTs, but also generic function application, abstract type constructors, etc.

**Comment by SimonMeskens** [comment]
@ahejlsberg I think this one is in your domain?

**Comment by SimonMeskens** [comment]
@mhegazy This isn't a question but a suggestion

**Comment by mhegazy** [comment]
The typescript type system is structural. so type parameters need to have a manifestation to be picked up by inference. i.e. used in a parameter type or in a return type for a function. if inference could not find any candidates, the upper bound is returned, which is `{}`.

In the case of `T4`, the compiler is trying to infer for `V` from `Lambda2`, it looks at the param list, to find any candidates for `T` and none are found, so `T` goes to `{}`, then instantiating `Lambda2` with `T = {}` gets us a return type of `{}[]` that is then used to as the inference for `V`.  same process happens in `T6`.

**Comment by SimonMeskens** [comment]
Okay, so here are some really odd behaviors to prove that it's not at all intuitive:
```ts
type Lambda1 = <U>(a: U) => U;
type Lambda2 = <U extends string>(a: U) => U;

type Test<T> = T extends <U extends "test">(a: U) => infer S
    ? S
    : string;

// OK
let a: Test<Lambda1> = "test"; // a: {}
let b: Test<Lambda1> = "some"; // b: {}

// Error: Type '"test"' is not assignable to type 'Test<Lambda2>'.
let c: Test<Lambda2> = "test"; // c: Test<Lambda2>
// Error: Type '"some"' is not assignable to type 'Test<Lambda2>'.
let d: Test<Lambda2> = "some"; // d: Test<Lambda2>
```

Expected behavior:
a, b, c and d are all of type `"test"` and b and d give an error that I can't assign '"some"' to type '"test"'

Actual behavior:
a and b are of type `{}` and allow me to assign "some"
c and d are of type `Test<Lambda2>` (whatever that means) and don't even allow me to pass in any string

So as it stands, I can't narrow type constraints, and I get really odd behavior when I try to.

**Comment by SimonMeskens** [comment]
I think I understand now why my suggestion is naive. The example above is just a bug.

Conditionals actually do something like this:
```ts
type Conditional<T extends <U extends "test">(a: U) => S, S = ReturnType<T>> = S;

type T = Conditional<Lambda2>;
```

Except they infer what S is above. So what would be necessary instead is for a proposal orthogonal to conditional types, like type level function application.
