### ISSUE TITLE
Can we define a new keyword for the upgraded `keyof` to avoid the breaking changes?

### ISSUE THREAD

**Issue by falsandtru** [microsoft/TypeScript#23666]
@ahejlsberg Such as `allkeyof`.

related: #23627, #23645

**Comment by ahejlsberg** [comment]
We considered that, but given (a) not much code is affected by the change, (b) it is significantly more complex to reason about *two* operators and their differences, and (c) all existing documentation only mentions the `keyof` operator, we feel it is better to just have `keyof` default to the new (and more desirable) behavior and provide a backwards compability switch (`--keyofStringsOnly`).

BTW, note that you can easily get the old behavior by using `Extract<keyof T, string>` where you previously used `keyof T`.
