### ISSUE TITLE
How to instantiate SVGLength / SVGAngle?

### ISSUE THREAD

**Issue by duncanmak** [microsoft/TypeScript#2367]
I came across this explanation from @RyanCavanaugh on StackOverflow, http://stackoverflow.com/questions/26220243/instantiating-new-htmlelement-in-typescript

It looks like `SVGLength` and `SVGAngle` also fit in this category. 

Is there something we can do so that these types can be instantiated? In JS today (Chrome 41), `new SVGLength()` throws an exception.

Idea: Perhaps this is a case where the 1.5 annotations can be used to offer some explanation for what to do.

**Comment by danquirk** [comment]
The right solution might be something as simple as marking the constructors private (#2341) or some other uncallable annotation

**Comment by RyanCavanaugh** [comment]
These classes can still be extended, so they need a public constructor. Seems like we're just not going to fix this one.
