### ISSUE TITLE
[loc][Query][TypeScript] Localizability of 0; "DisableSyntaxOnlyServerExplanation"

### ISSUE THREAD

**Issue by PDostalek** [Microsoft/TypeScript#23675]
**Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.
Please re-assign back to use in case you are not the right contact person or you can´t assign to a proper person.
Can you help please?
Thanks!**

Source:

Visual Studio launches an additional Node.js process to improve the responsiveness of operations that might otherwise cause typing delays. Checking this box prevents that and may result in reduced responsiveness.

File Name:

LanguageService\TypeScriptLanguageService\bin\Release\localize\ENU\Microsoft.CodeAnalysis.TypeScript.EditorFeatures.dll

Resource ID:
0; "DisableSyntaxOnlyServerExplanation"
-
Query:

We had difficulty understanding the last sentence.We understood that "Checking this box prevents from launching an additional Node.js process, and this may result in reduced responsiveness."Is this correct understanding?

**Comment by DanielRosenwasser** [comment]
That is correct.

**Comment by mhegazy** [comment]
//CC @amcasey

**Comment by PDostalek** [comment]
Thanks!
