### ISSUE TITLE
Index Signature Fails with Generics and Intersection Types

### ISSUE THREAD

**Issue by AnyhowStep** [Microsoft/TypeScript#23673]
**TypeScript Version:**  Version 2.9.0-dev.20180405

**Search Terms:**  extends generic intersection index

**Code**

```ts
type SomeType<T> = {
    [k in keyof T]: any;
};

function generic<Base, Derived extends SomeType<Base>>() {
    const derived: Derived = null as any;
    const test: { test: string } = null as any;
    const both: Derived & { test : string } = null as any;

    const works0: SomeType<Base> = derived;
    const works1: SomeType<Derived> = derived;
    const works2: SomeType<{ test: string }> = test;

    //This fails unexpectedly    
    const fails0: SomeType<Base & { test: string }> = both;
}

interface ConcreteBase {
    a: string,
    b: string,
}
interface ConcreteDerived {
    a: string,
    b: string,
    c: string,
}
const derived: ConcreteDerived = null as any;
const test: { test: string } = null as any;
const both: ConcreteDerived & { test : string } = null as any;

const works0: SomeType<ConcreteBase> = derived;
const works1: SomeType<ConcreteDerived> = derived;
const works2: SomeType<{ test: string }> = test;

const worksOutFine: SomeType<ConcreteBase & { test: string }> = both;
```

**Expected behavior:**

`fails0` in `generic()` should compile

**Actual behavior:**

`fails0` in `generic()` fails

**Playground Link:** [Link here](http://www.typescriptlang.org/play/#src=type%20SomeType%3CT%3E%20%3D%20%7B%0D%0A%20%20%20%20%5Bk%20in%20keyof%20T%5D%3A%20any%3B%0D%0A%7D%3B%0D%0A%0D%0Afunction%20deep%3CBase%2C%20Derived%20extends%20SomeType%3CBase%3E%3E()%20%7B%0D%0A%20%20%20%20const%20derived%3A%20Derived%20%3D%20null%20as%20any%3B%0D%0A%20%20%20%20const%20test%3A%20%7B%20test%3A%20string%20%7D%20%3D%20null%20as%20any%3B%0D%0A%20%20%20%20const%20both%3A%20Derived%20%26%20%7B%20test%20%3A%20string%20%7D%20%3D%20null%20as%20any%3B%0D%0A%0D%0A%20%20%20%20const%20works0%3A%20SomeType%3CBase%3E%20%3D%20derived%3B%0D%0A%20%20%20%20const%20works1%3A%20SomeType%3CDerived%3E%20%3D%20derived%3B%0D%0A%20%20%20%20const%20works2%3A%20SomeType%3C%7B%20test%3A%20string%20%7D%3E%20%3D%20test%3B%0D%0A%0D%0A%20%20%20%20%2F%2FThis%20fails%20unexpectedly%20%20%20%20%0D%0A%20%20%20%20const%20fails0%3A%20SomeType%3CBase%20%26%20%7B%20test%3A%20string%20%7D%3E%20%3D%20both%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20ConcreteBase%20%7B%0D%0A%20%20%20%20a%3A%20string%2C%0D%0A%20%20%20%20b%3A%20string%2C%0D%0A%7D%0D%0Ainterface%20ConcreteDerived%20%7B%0D%0A%20%20%20%20a%3A%20string%2C%0D%0A%20%20%20%20b%3A%20string%2C%0D%0A%20%20%20%20c%3A%20string%2C%0D%0A%7D%0D%0Aconst%20derived%3A%20ConcreteDerived%20%3D%20null%20as%20any%3B%0D%0Aconst%20test%3A%20%7B%20test%3A%20string%20%7D%20%3D%20null%20as%20any%3B%0D%0Aconst%20both%3A%20ConcreteDerived%20%26%20%7B%20test%20%3A%20string%20%7D%20%3D%20null%20as%20any%3B%0D%0A%0D%0Aconst%20works0%3A%20SomeType%3CConcreteBase%3E%20%3D%20derived%3B%0D%0Aconst%20works1%3A%20SomeType%3CConcreteDerived%3E%20%3D%20derived%3B%0D%0Aconst%20works2%3A%20SomeType%3C%7B%20test%3A%20string%20%7D%3E%20%3D%20test%3B%0D%0A%0D%0Aconst%20worksOutFine%3A%20SomeType%3CConcreteBase%20%26%20%7B%20test%3A%20string%20%7D%3E%20%3D%20both%3B)

Intuitively, to me, it should work out fine.

+ `Derived` has all the fields of `Base`; possibly more.
+ I added one extra field `test`.
+ `Derived` is assignable to `Base`
+ `Derived & { test: string }` should be assignable to `Base & { test: string }`

**Comment by weswigham** [comment]
So the way we break down intersections makes it impossible to recognize the equivalence here. We compare the intersection one member at a time and see if either member on their own is assignable to the `SomeType` intersection. `{test: string}` isn't assignable - it's not guaranteed to have `Base`'s props. `Derived` isn't assignable because it's missing `test` (`keyof Base | "test"` is not assignable to `keyof Derived`).

@ahejlsberg have we just been marking issues like this as a design limitation, or are we planning to do something about it?
