### ISSUE TITLE
Infer type of YieldExpression

### ISSUE THREAD

**Issue by s-coimbra21** [Microsoft/TypeScript#23677]
Currently yield expressions are always of type any. I've been using the [redux-saga](https://github.com/redux-saga/redux-saga/) library and this has made my typescript + redux-saga story as I have to manually type the result of every yield expression, this leads to a lot of errors.

What I'm looking to implement is basically something 
```ts
Effect<T1, T2>
```
where T1 is what is yielded and T2 is what should be passed back to the generator (the type of the YieldExpression), that is, some way to type what a generator is expecting to be passed (if any) when it yields something. 

Essentially, a type or perhaps even some new syntax that allows you to express `by yielding T1, this YieldExpression will now be of type T2>`.

For example, this could be possible:
```ts
const globalWorld = {...};

function select(fn: (state: World) => T): EffectDescriptor yields T {
  return {
    fn
  }
}

function* gen() {
  const thisWillBeAString = yield select(mySelectorThatReturnsAString);
}

function myRuntime(gen: IterableIterator<EffectDescriptor>) {
  while(true) {
    const effect = gen.next().value;
    const myString = effect.fn(globalWorld);
    gen.next(myString); // would give an error if you passed anything but a string
  }
}
```

**Comment by mhegazy** [comment]
Seems like another version of https://github.com/Microsoft/TypeScript/issues/2983 and https://github.com/Microsoft/TypeScript/issues/10509. Updating generator type is currently tracked by https://github.com/Microsoft/TypeScript/issues/11375 and https://github.com/Microsoft/TypeScript/issues/2983.

A generator type should have three type parameters, `TYield` (what it yeilds), `TReturn` (What it returns, when done is true) and `TNext` (input to `next` calls).
