### ISSUE TITLE
Visual Studio "TypeScript Build" project properties versus tsconfig.json

### ISSUE THREAD

**Issue by IanKemp** [Microsoft/TypeScript#23676]
If you have a C# project with TypeScript support enabled, and that project has a `tsconfig.json` file, navigating to to the "TypeScript Build" section of that project's properties results in a non-editable page with the message "One or more tsconfig.json files detected. Project properties are disabled.":

![image](https://user-images.githubusercontent.com/1726434/39236882-4347a87a-487a-11e8-9530-47c939d4f8ad.png)

The implication is that VS project properties for TS, and `tsconfig.json`, are mutually exclusive.

* Why is this? Why can't that properties page be populated from the values in the `tsconfig.json` if present **and there are no ancestor tsconfig files**?
* Is using `tsconfig.json` deprecated in favour of controlling the TypeScript configuration from Visual Studio?

**Comment by mhegazy** [comment]
> Why is this? Why can't that properties page be populated from the values in the tsconfig.json if present and there are no ancestor tsconfig files?

To enable that we need an editor that allows round-tripping from a json file, i.e. you edit the json file, ui changes, you edit the ui, the json file changes, including all required validations etc.. notice that the .json file is available for you to edit outside the property pages, but not the project file (.csproj) for instance. 
We, the typescript team, have limited engineering resources and have to prioritize our deliverables. JS developers are usually familiar with JSON files, and with the support of schema, we believe the experience is better than what a property page can offer. 

> Is using tsconfig.json deprecated in favour of controlling the TypeScript configuration from Visual Studio?

Both are supported. but we recommend using a `tsconfig.json` moving on. we are not updating the UI in the project property pages, so using `tsconfig.json` will give you a better experience.
