### ISSUE TITLE
static return might fail with switch statement

### ISSUE THREAD

**Issue by ORESoftware** [Microsoft/TypeScript#23670]
I have this:

```js
const onUpdate = function (v: string, o: any) : Promise<any> {
  
  const finalName = String(v || '').split('.')[1]; // collection name
  const _id = o && o.o2 && o.o2._id;
  let key;
  
  switch (finalName) {
    
    case 'categories':      
      return Category.findOne({_id}).exec().then(function (cat: any) {
         // ....
      });
    
    case 'acquisitions':
        return Acquisition.findOne({_id}).exec().then(function (acq: any) {
         // ...
      });
    
    case 'functionalTeams':
      return FunctionalGroup.findOne({_id}).exec().then(function (ft: any) {
           // ...
      });
    
    default:
      log.error('document collection did not match a pre-defined name');
      // nothing is returned here, but can TS check to see if it does/doesn't
  }
  
};
```

can TypeScript check to see if a Promise fails to be returned in the default or after the switch statement? Right now it's compiling even though a Promise is not returned in all cases.

**Comment by andy-ms** [comment]
You probably just need `--strictNullChecks` enabled.

**Comment by samartddf** [comment]
Issue

**Comment by MartinJohns** [comment]
Or alternatively `--noImplicitReturns`. Enabling `--strictNullChecks` is often very difficult to add in old code bases, but `--noImplicitReturns` is a no-brainer.

**Comment by ORESoftware** [comment]
ok understood, to move this in a more productive direction, is there a way to never allow null/undefined in the place of a defined value? In Java, all those NullPointerExceptions are caused by allowing null to exist.

**Comment by MartinJohns** [comment]
Yes... That is pretty much what `strictNullChecks` is for. And related to that the `strictPropertyInitialization` feature (works only together with `strictNullChecks`.

**Comment by ORESoftware** [comment]
@MartinJohns  thanks for the info...I still think `strictNullChecks` should be the default behavior, and that users should have to specifically set it to false, but nbd I guess
