### ISSUE TITLE
bug/feature: watch does not move/copy declaration files

### ISSUE THREAD

**Issue by ORESoftware** [Microsoft/TypeScript#23682]
As you can see from the screenshot, `tsc --watch` is not copying the *.d.ts files from lib to dist. I was expected bunion-types.d.ts to show up in the `dist` folder after transpilation.

<img width="728" alt="screenshot 2018-04-24 18 38 03" src="https://user-images.githubusercontent.com/11139560/39260001-ef906c2e-486c-11e8-865b-7965d2120b1a.png">

is there some way to configure `tsc --watch` so that it will copy the declaration files?

is there some way around this?

there screenshot shows my tsconfig.json file, showing that `outDir` is `dist`, and that it's only including the `lib` folder for source files.

**Comment by ORESoftware** [comment]
@mhegazy yeah, I figured out the .ts trick, but then the compiler produces both .js and .d.ts into `dist`.... and the .js file, being unnecessary/superfluous, triggers my OCD lol.

so your'e saying I should just manually copy the file after `tsc` runs?
the problem is if I am using `tsc --watch` then this is not so easy.

fml

**Comment by mhegazy** [comment]
> I figured out the .ts trick, but then the compiler produces both .js and .d.ts into dist.... and the .js file, being unnecessary/superfluous, triggers my OCD lol.

should it copy your `node_modules\@types\node\index.d.ts` to the output as well? what if you have a local overrides of some of these declarations files? what if you have multiple projects with each project including the .d.ts file from the other, should the final one include all the other .d.ts files? would you expect your c++ compiler to copy your header files around?
