### ISSUE TITLE
What is the detail logic of type assertion?

### ISSUE THREAD

**Issue by chinesedfan** [Microsoft/TypeScript#23698]
**TypeScript Version:**  2.8.1

**Search Terms:**  type assertion

**Code**

```ts
interface PM_MGEInfo {
    category: string;
    bid: string;
    cid?: string;
    labs?: { [key: string]: any };
}

function makeMgeInfo1(bid: string): PM_MGEInfo {
    return <PM_MGEInfo>{
        bid
    };
}

function makeMgeInfo2(bid: string): PM_MGEInfo {
    return <PM_MGEInfo>{
        bid,
        labs: {}
    };
}

function makeMgeInfo3(bid: string): PM_MGEInfo {
    return <PM_MGEInfo>{
        bid,
        // error TS2352: Type '{ labs: { poi_id: string; }; bid: string; }' cannot be converted to type 'PM_MGEInfo'.
        // Property 'category' is missing in type '{ labs: { poi_id: string; }; bid: string; }'.
        labs: {a: 1}
    };
}

```

**Expected behavior:**
The compiler always complains the missing of field `category`, or never. I know type assertion is not 100% safe, but am confused about its check logic. Can someone point out related codes for me? The ts code base is so complex.

**Actual behavior:**
Only `makeMgeInfo3` throws an error about the missing of field `category`.

**Playground Link:** [very long link](https://www.typescriptlang.org/play/index.html#src=interface%20PM_MGEInfo%20%7B%0D%0A%20%20%20%20category%3A%20string%3B%0D%0A%20%20%20%20bid%3A%20string%3B%0D%0A%20%20%20%20cid%3F%3A%20string%3B%0D%0A%20%20%20%20labs%3F%3A%20%7B%20%5Bkey%3A%20string%5D%3A%20any%20%7D%3B%0D%0A%7D%0D%0A%0D%0Afunction%20makeMgeInfo1(bid%3A%20string)%3A%20PM_MGEInfo%20%7B%0D%0A%20%20%20%20return%20%3CPM_MGEInfo%3E%7B%0D%0A%20%20%20%20%20%20%20%20bid%0D%0A%20%20%20%20%7D%3B%0D%0A%7D%0D%0A%0D%0Afunction%20makeMgeInfo2(bid%3A%20string)%3A%20PM_MGEInfo%20%7B%0D%0A%20%20%20%20return%20%3CPM_MGEInfo%3E%7B%0D%0A%20%20%20%20%20%20%20%20bid%2C%0D%0A%20%20%20%20%20%20%20%20labs%3A%20%7B%7D%0D%0A%20%20%20%20%7D%3B%0D%0A%7D%0D%0A%0D%0Afunction%20makeMgeInfo3(bid%3A%20string)%3A%20PM_MGEInfo%20%7B%0D%0A%20%20%20%20return%20%3CPM_MGEInfo%3E%7B%0D%0A%20%20%20%20%20%20%20%20bid%2C%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20error%20TS2352%3A%20Type%20'%7B%20labs%3A%20%7B%20poi_id%3A%20string%3B%20%7D%3B%20bid%3A%20string%3B%20%7D'%20cannot%20be%20converted%20to%20type%20'PM_MGEInfo'.%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20Property%20'category'%20is%20missing%20in%20type%20'%7B%20labs%3A%20%7B%20poi_id%3A%20string%3B%20%7D%3B%20bid%3A%20string%3B%20%7D'.%0D%0A%20%20%20%20%20%20%20%20labs%3A%20%7Ba%3A%201%7D%0D%0A%20%20%20%20%7D%3B%0D%0A%7D%0D%0A)

**Related Issues:**
I also asked on [stackoverflow](https://stackoverflow.com/questions/50015151/what-is-the-detail-logic-of-type-assertion-in-typescript), but got no satisfying answers.

**Comment by mhegazy** [comment]
Docs are at: https://www.typescriptlang.org/docs/handbook/basic-types.html#type-assertions

Basically the compiler is checking that the two types are somehow related, that is that one is assignable to the other. In this case neither is the case. In one way the object literal is missing a a required property category, in the other way missing required property labs.a

**Comment by chinesedfan** [comment]
> In this case neither is the case. In one way the object literal is missing a a required property category, in the other way missing required property labs.a

@mhegazy Can you explain a little more about why case 1&2 are no compilation errors? What's the difference between 1/2 and 3?

**Comment by mhegazy** [comment]
Cuase they are assignable in one direction.

**Comment by chinesedfan** [comment]
@mhegazy Sorry, I still understand. I think the 3 object literals are not **assignable** to `PM_MGEInfo`, due to the lack of property `category`. But why does the last case trigger the check?

If it is hard to explain, can you give me a link to the related TypeScript source codes?

**Comment by DanielRosenwasser** [comment]
There's a function in `src/compiler/checker.ts` called `checkAssertion`. I can't link it here because the file's too big.
