### ISSUE TITLE
concat calls do not inform type of auto arrays

### ISSUE THREAD

**Issue by sandersn** [Microsoft/TypeScript#23693]
```ts
function f() {
    let l = []
    l.push(1)
    l.push(false)
    return l.concat(['nope'])
}
```

**Expected behavior:**

`f: () => (number | string | boolean)[]` and no errors

**Actual behavior:**

`f: () => (number | boolean)[]` and "Type string is not assignable to number | boolean" on the concat call.

**Comment by mhegazy** [comment]
`concat` generates a new array. there is no reason why you would only concat values of the same type as your original array.. so using it as an inference site is questionable.
