### ISSUE TITLE
In JS, typedefs should be automatically exported

### ISSUE THREAD

**Issue by sandersn** [Microsoft/TypeScript#23692]
```js
// @Filename: module.js
/** @typedef {number} Num */
module.exports = { a: 1 }

// @Filename: use.js
/** @type {import("./module.js").Num} */
var n;
```

Expected:
Num is visible in use.js

Actual:
Num is not visible.

Note that the checker already has code to handle structures like this, so modules with `modules.exports=` should already almost work. Other kinds of modules may or may not.

The special-case merge code for `module.exports=` in the checker puts SymbolFlags.Value on all the symbols, which will be incorrect for this case, so that code will need to be updated.

**Comment by SergioMorchon** [comment]
This will hugely unlock TS usage to check JS codebases.
Imagine the following:

**models/a.js**

```javascript
const createSomething = ({some, thing}) => ({
    some: String(some),
    thing: String(thing),
});

/**
 * @typedef {ReturnType<typeof createSomething>} Something
 */

export const createA = ({something}) => ({
    something: createSomething(something),
});
```

**actions/a.js**

```javascript
/**
 * @typedef {ReturnType<typeof import('../models/a').createA>} A
 */
/**
 * @typedef {ReturnType<typeof import('../models/a').Something>} Something
 */

/**
 * @param {A[]} as
 * @param {Something} something
 */
export const getABySomething = (as, something) => {/* do stuff */};
```

I know the `A` part will with actual master code, and if I understand well, it should do in the future for the `typedef` of `Something`.
Would this work?

**Comment by sandersn** [comment]
Wouldn't the second typedef in actions/a.js be just `/** @typedef {import('../models/a').Something} Something */` ?

**Comment by SergioMorchon** [comment]
Wooops, that's right.

**Comment by sandersn** [comment]
@SergioMorchon Yes, it should work. Let me know if you have a chance to test it with typescript@next starting tomorrow.

**Comment by SergioMorchon** [comment]
It worked, @sandersn. Nice :D
Anyway, related to this, VSCode does shows 0 references in the sourced JSDoc, although a property rename with refactor action (F2) works fine across all usages that imported the exposed typedef.

**Comment by sandersn** [comment]
@SergioMorchon I filed #23863 to track that problem. I couldn't get rename to work either, but I wasn't using VS Code.
