### ISSUE TITLE
Function param with generic type are not recognized correctly

### ISSUE THREAD

**Issue by k8w** [Microsoft/TypeScript#23705]
**TypeScript Version:**  2.7.0-dev.201xxxxx
2.8.3

**Search Terms:** 

**Code**

```ts
class Protocol<T>{}

interface ReqTest {
    abcde: string;
}

const PtlTest = new Protocol<ReqTest>();

function request<T>(ptl: Protocol<T>, req: T) { }

request(PtlTest, {})
```

**Expected behavior:**
Compile error.
Because `request(PtlTest, {})`, param 2 `{}` not match `ReqTest`

**Actual behavior:**
Compile success

**Playground Link:**  

**Related Issues:**

**Comment by andy-ms** [comment]
You need an explicit type argument here, because `{}` is a valid inference. `PtlTest` validly a `Protocol<{}>` (`T` is never even used, so everything but `null` or `undefined` is a`Protocol<T>` for *any* `T`), and `{}` of course is a valid `{}`.

**Comment by k8w** [comment]
@andy-ms shouldn't `T` be infered from `PtlDemo`?
Actually it works well in previous TypeScript version.

**Comment by k8w** [comment]
@andy-ms shouldn't `T` be infered from `PtlDemo`?
Actually it works well in previous TypeScript version.

**Comment by andy-ms** [comment]
I don't see a compile error in any of `typescript@2.6`, `typescript@2.7`, `typescript@next`. `Protocol` is an empty type, so almost anything is assignable to it.

**Comment by k8w** [comment]
```ts
function test<T>(value1: T, value2: T) {
    return value2
}
test({ a: 1 }, {});
```

@andy-ms  Just see this.
It would compile error at `typescript@2.6`:
> error TS2345: Argument of type '{}' is not assignable to parameter of type '{ a: number; }'.
  Property 'a' is missing in type '{}'.
But compile succ at `typescript@2.8`

And it's strange that it works well if it is this:
```ts
function test<T>(value1: T, value2: T) {
    return value2
}
test(<{ a: number }>{ a: 1 }, {});
```

**Comment by andy-ms** [comment]
I'll tentatively mark this as a bug due to the inconsistency in:
```ts
declare function equal<T>(a: T, b: T): boolean;
equal("", 0); // Error
equal({ a: 1 }, { b: 2 }); // No error
```

**Comment by mhegazy** [comment]
See more about the rationals here in https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#improved-type-inference-for-object-literals
