### ISSUE TITLE
Unexpected behavoir when assigning an interface to a index signature

### ISSUE THREAD

**Issue by The00Devon** [Microsoft/TypeScript#23709]
**TypeScript Version:**  2.7.0-dev.201xxxxx

**Search Terms:** type assertion index signature interface

**Code**

```ts
interface IBool { 
    bool: boolean;
}
let varBool1:{bool:boolean} = {bool:true};
let varBool2:IBool = {bool:true};
let indexBool:{[index:string]:boolean};

indexBool = varBool1;

// Type 'IBool' is not assignable to type '{ [index: string]: boolean; }'.
// Index signature is missing in type 'IBool'.
indexBool = varBool2;
```

**Expected behavior:** varBool1 and varBool2 to act in the same way when being assigned to indexBool, as their types should be equivalent, and they compile and execute identically.

**Actual behavior:** varBool1 passes fine, whereas varBool2 flags an error.

**Playground Link:** [LINK](https://www.typescriptlang.org/play/#src=interface%20IBool%20%7B%20%0D%0A%20%20%20%20bool%3A%20boolean%3B%0D%0A%7D%0D%0Alet%20varBool1%3A%7Bbool%3Aboolean%7D%20%3D%20%7Bbool%3Atrue%7D%3B%0D%0Alet%20varBool2%3AIBool%20%3D%20%7Bbool%3Atrue%7D%3B%0D%0Alet%20indexBool%3A%7B%5Bindex%3Astring%5D%3Aboolean%7D%3B%0D%0A%0D%0AindexBool%20%3D%20varBool1%3B%0D%0A%0D%0A%2F%2FType%20'IBool'%20is%20not%20assignable%20to%20type%20'%7B%20%5Bindex%3A%20string%5D%3A%20boolean%3B%20%7D'.%0D%0A%2F%2F%20%20Index%20signature%20is%20missing%20in%20type%20'IBool'.%0D%0AindexBool%20%3D%20varBool2%3B%0D%0A%0D%0A%0D%0Alet%20button%20%3D%20document.createElement('button')%3B%0D%0Abutton.textContent%20%3D%20%22Say%20Hello%22%3B%0D%0Abutton.onclick%20%3D%20function()%20%7B%0D%0A%20%20%20%20alert(indexBool%5B'bool'%5D%3F%22Hello%22%3A%22Goodbye%22)%3B%0D%0A%7D%0D%0A%0D%0Adocument.body.appendChild(button)%3B)

**Related Issues:**

**Comment by mhegazy** [comment]
Types are open in TypeScript. so you can assign `{bool: true, somethingElese: string}` to `IBool`. An index signature on a type expects **all** properties to be of that type.
