### ISSUE TITLE
Invalid generic default type used with Partial on intersection

### ISSUE THREAD

**Issue by vthib** [Microsoft/TypeScript#23703]
**TypeScript Version:**  2.9.0-dev.20180426
**Search Terms:** Generic inference partial weak interface

I have come across a weird behavior of the generic inference when use with partial and default types.
The example is a bit convoluted but I have not managed to simplify it further:

**Code**

```ts
interface Base {
    b: number;
}
declare class Model<Param extends Base = Base> {
    constructor(attr: Partial<Param & { a: number; }>);
    bar(a: Param): any;
}

interface Foo extends Base {
    c?: number;
}
declare class FooModel<Param extends Foo = Foo> extends Model<Param> { }

/* TS2345: Argument of type '{ b: number; c: number }' is not assignable to parameter of type 'Partial<Base & { a: number; }>'.
 * Object literal may only specify known properties, and 'c' does not exist in type 'Partial<Base & { a: number; }>'.
 */
const m: Model = new FooModel({ b: 1, c: 1 });

const p: Model = new FooModel<Foo>({ b: 1, c: 1 }); /* ok */
const q: Model = new FooModel({ b: 1, c: 1 } as Foo); /* ok */
const r = new FooModel({ b: 1, c: 1 }); /* ok */
```

**Expected behavior:**

The _m_ assignment should compile, the default type for the generic of FooModel is Foo.

**Actual behavior:**

Does not compile, as shown in the error message, _Base_ is used as the generic type.
Additionally:
- Removing ``& { a: number}`` from the ``Partial`` solves the issue: If we try to compile ``
const m: Model = new FooModel({ bad: 2 });``, the error message shows ``Foo`` is used as the generic type.
- Removing the ``bar`` method solves the issue: idem, ``Foo`` is then used as the generic type.
- Removing the ``Partial`` solves the issue, idem.
- Making `c` non-optional fixes the issue, as does using Typescript 2.3. This seems to indicate that it is related to weak interfaces if I had to guess.

**Playground Link:**

[Playground Link](http://www.typescriptlang.org/play/#src=interface%20Base%20%7B%0D%0A%20%20%20%20b%3A%20number%3B%0D%0A%7D%0D%0Adeclare%20class%20Model%3CParam%20extends%20Base%20%3D%20Base%3E%20%7B%0D%0A%20%20%20%20constructor(attr%3A%20Partial%3CParam%20%26%20%7B%20a%3A%20string%20%7D%3E)%3B%0D%0A%20%20%20%20bar(a%3A%20Param)%3A%20any%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20Foo%20extends%20Base%20%7B%0D%0A%20%20%20%20c%3F%3A%20number%3B%0D%0A%7D%0D%0Adeclare%20class%20FooModel%3CParam%20extends%20Foo%20%3D%20Foo%3E%20extends%20Model%3CParam%3E%20%7B%20%7D%0D%0A%0D%0Aconst%20m%3A%20Model%20%3D%20new%20FooModel(%7B%20b%3A%201%2C%20c%3A%201%20%7D)%3B%0D%0A%0D%0Aconst%20p%3A%20Model%20%3D%20new%20FooModel%3CFoo%3E(%7B%20b%3A%201%2C%20c%3A%201%20%7D)%3B%20%2F*%20ok%20*%2F%0D%0Aconst%20q%3A%20Model%20%3D%20new%20FooModel(%7B%20%20b%3A%201%2C%20c%3A%201%20%7D%20as%20Foo)%3B%20%2F*%20ok%20*%2F%0D%0Aconst%20r%20%3D%20new%20FooModel(%7B%20b%3A%201%2C%20c%3A%201%20%7D)%3B%20%2F*%20ok%20*%2F)

**Comment by weswigham** [comment]
The really bad inference we draw here is a return type inference - we effectively infer from
```ts
type InstantiatedModelInstance = {
    bar(a: Base): any;
}
```
to
```ts
type UninstantiatedFooInstance<Param> = {
    bar(a: Param): any;
}
```
yielding an inference of `RetunType` priority for `Base -> Param`. We then actually get _no inference_ from the constructor, because `{ b: 1, c: 1 }` to `Partial<Param & { a: number; }>` becomes a mapped type constraint inference to `keyof Param | "a"` (keyof distribution over intersections is a recent change) and yields no inference (apparently we don't handle intersections of generics within mapped types particularly well when it comes to inference).

**Comment by weswigham** [comment]
I spoke with @ahejlsberg and at least for now, we're calling this a limitation of the inference engine, as we have no great way to draw a good inference for `Partial<Param & { a: number; }>` from `{ b: 1, c: 1 }` based on how we do mapped type inferences. _However_ in this specific instance, you can just rewrite the argument type as `Partial<Param> & { a?: number; }` to obviate the checker's confusion. Generally speaking, complex types used as mapped type constraints (like the parameter of `Partial`) are difficult for us to draw inferences for - it's best if you keep them as bare type parameters, then we can easily draw strong inferences.

**Comment by vthib** [comment]
Thanks for the explanations. Luckily this bug does not impact us too much. The example was simplified quite a bit so your suggestion might not be really possible, but I'll look into refactoring the code to avoid relying on such mapped types.
