### ISSUE TITLE
For...In Loop Converts keyof T to string

### ISSUE THREAD

**Issue by AnyhowStep** [Microsoft/TypeScript#23707]
**TypeScript Version:**  2.8.3, 2.9.0-dev.20180405

**Search Terms:** for in keyof string

**Code**

```ts
interface Something {
    a: string,
    b: number,
}

function doSomething<T extends Something> (obj : T, keys : (keyof T)[]) {
    //For some reason, `k` is resolved to `string`
    for (let k in keys) {
        //Type 'string' is not assignable to type 'keyof T'.
        //Type 'string' is not assignable to type '"a" | "b"'.
        const key : keyof T = k;
        console.log(obj[key]);
    }
}
```

**Expected behavior:**

`k` should be of type `keyof T`

**Actual behavior:**

`k` is `string`

**Playground Link:** [Link here](https://www.typescriptlang.org/play/#src=interface%20Something%20%7B%0D%0A%20%20%20%20a%3A%20string%2C%0D%0A%20%20%20%20b%3A%20number%2C%0D%0A%7D%0D%0A%0D%0Afunction%20doSomething%3CT%20extends%20Something%3E%20(obj%20%3A%20T%2C%20keys%20%3A%20(keyof%20T)%5B%5D)%20%7B%0D%0A%20%20%20%20for%20(let%20k%20in%20keys)%20%7B%0D%0A%20%20%20%20%20%20%20%20const%20key%20%3A%20keyof%20T%20%3D%20k%3B%0D%0A%20%20%20%20%20%20%20%20console.log(obj%5Bkey%5D)%3B%0D%0A%20%20%20%20%7D%0D%0A%7D)

**Related Issues:**

**Comment by andy-ms** [comment]
Try it in the node.js console:
```js
for (let k in ["a", "b", "c"]) console.log(typeof k, k)
```
Prints: `string 0`, `string 1`, `string 2`. A `for-in` lop loops over the *keys* of an object; to iterate over an array use a `for-of` loop.

**Comment by AnyhowStep** [comment]
Ugh, I knew I was forgetting something. My bad. I figured this out 12 seconds after you posted this. Sorry!
