### ISSUE TITLE
Enable custom transforms for declaration emit 

### ISSUE THREAD

**Issue by zerkalica** [Microsoft/TypeScript#23701]
I try to use absolute paths aliases for libraries. Output d.ts with aliased paths breaks type resolving, when package usesd as external package. Problem not resolved in typescript (see #18972).

Example:

my-lib/src/index.ts
```ts
export * from 'my-lib/some'
```

my-lib/dist/index.d.ts
```ts
export * from 'my-lib/some'
```

my-app.ts

```ts
 import some from 'my-lib'
 // ts does not check types here:
 some.bla-bla
```

I wrote [ts-transform-paths transfomer](https://github.com/zerkalica/zerollup/tree/master/packages/ts-transform-paths), which rewrites aliased import paths accordingly tsconfig baseUrl and paths.

With my trasformer my-lib/dist/index.d.ts
```ts
export * from './some'
```

It's works for npm packages and applications.

Problem:

Ts language service ``` service.getEmitOutput(key, true) ``` [ignores transformers](https://github.com/Microsoft/TypeScript/blob/5c94bef0e134ff26c4d03e8fe8190f8b2e760521/src/compiler/program.ts#L1191) in dts generation mode:

```ts
performance.mark("beforeEmit");
const transformers = emitOnlyDtsFiles ? [] : getTransformers(options, customTransformers);
```

In my [transformer chain helper](https://github.com/zerkalica/zerollup/blob/master/packages/ts-helpers/src/createTransformerChain.ts#L16) i use a emitFiles hack to keep some dts-related transformers. I use dts flag to indicate that plugin works for d.ts.

```ts
export interface CustomTransformer {
    dts?: boolean
    before?: ts.TransformerFactory<ts.SourceFile>
    after?: ts.TransformerFactory<ts.SourceFile>
}
```

May be add posibility to filter dts related trasformers in typescript if emitOnlyDtsFiles given?

Something like this:

```ts
performance.mark("beforeEmit");
const transformers = getTransformers(options, customTransformers, emitOnlyDtsFiles);
```

**Comment by alexeagle** [comment]
Angular needs this also for the Ivy renderer compiler to be a `ts.CustomTransformers`

Discussed with @mhegazy a proposal where we add a property named `afterDeclaration`:
```
interface CustomTransformers {
        /** Custom transformers to evaluate before built-in transformations on .js emit. */
        before?: TransformerFactory<SourceFile>[];
        /** Custom transformers to evaluate after built-in transformations on .js emit. */
        after?: TransformerFactory<SourceFile>[];
        /** Custom transformers to evaluate after built-in transformations on .d.ts emit. */
        afterDeclaration?: TransformerFactory<SourceFile>[];
    }
```
