### ISSUE TITLE
nested namespace issue in different files

### ISSUE THREAD

**Issue by CGQAQ** [Microsoft/TypeScript#23710]
**TypeScript Version:**  2.8.3

**Code**

a.ts
```ts
namespace N{
    import C = N.N2.C;
}
```

b.ts
```ts
namespace N.N2{
    export class C{}
}
```
It's will be ok, no error happens.

BUT!!!!!!!!!!!!!

a.ts add some importing code  out of namespace N, like this: 
```ts
import * as path from 'path';
namespace N{
    import C = N.N2.C;
}
```
it will report  TS2694: Namespace 'N' has no exported member 'N2'

when I try to moving import statement into namespace 'N', like this: 
```ts
namespace N{
    import * as path from 'path';
    import C = N.N2.C;
}
```

the TS2694: Namespace 'N' has no exported member 'N2' gone, and another like "TS1147: Import declarations in a namespace cannot reference a module." happen

**Comment by andy-ms** [comment]
When a file is a module, everything inside that file is in a module scope. So the `namespace N` appearing after an import is a local variable and unrelated to the global `N`.

**Comment by CGQAQ** [comment]
So  how do I use class C inside of file a.ts,  import from  seems not gonna work

**Comment by CGQAQ** [comment]
but I can't access global N,  I try to 
```ts
import * as path from 'path';
import GN = N;
namespace N{
    import C = GN.N2.C;
}
```
sitll have the same issue  TS2694: Namespace 'N' has no exported member 'N2'

**Comment by CGQAQ** [comment]
How can I use class 'c' in namespace 'N' of a.ts anyhow? or it's no way to do it?

**Comment by andy-ms** [comment]
The problem is that you declared a local `N` in `a.ts` that shadows the global `N`. Just avoid declaring `namespace N` in a local scope.

**Comment by CGQAQ** [comment]
But it's just nesting relation like c#, avoid this, I don't think we need namespace in the ts.

thank you for answering me, have a good day!
