### ISSUE TITLE
Incorrect narrowing of a type alias consisting of nominal types

### ISSUE THREAD

**Issue by danpantry** [Microsoft/TypeScript#23713]
**TypeScript Version:**  2.8.1

Whilst I understand the below code is not *completely* sound (insofar as refuting that a type is not Product does not mean it is necessarily of type Group), the method signatures clearly indicate that if `item` is not `Product` it must be `Group`.

While Group could be said to be assignable to Product if we were using type aliases (because of the shared fields), I'm under the impression that interfaces are nominally typed, making this unexpected behaviour.

I discovered this issue after removing a field from `Group` which is not in `Product`, which I think validates my assumption that this is only occurring because TypeScript is comparing the type structure - this shouldn't happen with interfaces because they are nominal types.

**Code**

```ts
export interface Product {
  id: string;
  name: string;
  teamId: string;
  isActive: boolean;
}

export interface Group {
  id: string
  name: string;
}

function isProduct(item: Product | Group | null): item is Product {
  return item && 'teamId' in item;
}

function isGroup(item: Product | Group | null): item is Group {
  return isProduct(item) === false;
}

function doSomething() {}

const item: Product | Group = {} as any;
const a = isGroup(item) ? doSomething() : item.name;
// compiler error; `item` is inferred to `never`

const a = isProduct(item) === false ? item.name : item.name
// not a compiler error. but `item` is not narrowed in either area (item.name is accessible from both sides of the ternary expression)
```

**Expected behavior:**
`item` is narrowed to `Group` within the else section of the ternary statement.

**Actual behavior:**
`item` is narrowed to `never` within the else section of the ternary statement.

**Playground Link:**
https://www.typescriptlang.org/play/#src=export%20interface%20Product%20%7B%0D%0A%20%20id%3A%20string%3B%0D%0A%20%20name%3A%20string%3B%0D%0A%20%20teamId%3A%20string%3B%0D%0A%20%20isActive%3A%20boolean%3B%0D%0A%7D%0D%0A%0D%0Aexport%20interface%20Group%20%7B%0D%0A%20%20id%3A%20string%0D%0A%20%20name%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Afunction%20isProduct(item%3A%20Product%20%7C%20Group%20%7C%20null)%3A%20item%20is%20Product%20%7B%0D%0A%20%20return%20item%20%26%26%20'teamId'%20in%20item%3B%0D%0A%7D%0D%0A%0D%0Afunction%20isGroup(item%3A%20Product%20%7C%20Group%20%7C%20null)%3A%20item%20is%20Group%20%7B%0D%0A%20%20return%20isProduct(item)%20%3D%3D%3D%20false%3B%0D%0A%7D%0D%0A%0D%0Afunction%20doSomething()%20%7B%7D%0D%0A%0D%0Aconst%20item%3A%20Product%20%7C%20Group%20%3D%20%7B%7D%20as%20any%3B%0D%0Aconst%20a%20%3D%20isGroup(item)%20%3F%20doSomething()%20%3A%20item.name%3B%20%2F%2F%20compiler%20error%3B%20%60item%60%20is%20inferred%20to%20%60never%60%0D%0A%0D%0Aconst%20a%20%3D%20isProduct(item)%20%3D%3D%3D%20false%20%3F%20item.name%20%3A%20doSomething()%20%2F%2F%20%60item%60%20is%20correctly%20narrowed%20to%20%60Group%60

**Comment by mhegazy** [comment]
Types in TypeScript are structural. if you assert that `item` is a `Group`, that means that it could be a `Product` as well.. and thus both are filtered from possible types of `item`, leaving you with `never`. The other way around works as you would expect since a `Product` is not a `Group`.

if the types are truly disjoint, define `Group` as:
```ts
export interface Group {
    id: string
    name: string;
    teamId?: undefined;
    isActive?: undefined;
}
```

**Comment by danpantry** [comment]
Ah, thanks, I'm not sure where I got the idea interface types were nominal
