### ISSUE TITLE
signature help of tagged template doesn't show instantiated signature

### ISSUE THREAD

**Issue by ajafff** [microsoft/TypeScript#23716]
**TypeScript Version:**  2.9.0-dev.20180426

**Search Terms:** 

**Code**

```ts
declare function tag<T>(string: TemplateStringsArray, ...values: T[]): void;

tag``;
tag`${1}`;
tag<number>``;
```

**Expected behavior:**

the following signature help when hovering over `tag`:

* `function tag<{}>(string: TemplateStringsArray, ...values: {}[]): void`
* `function tag<number>(string: TemplateStringsArray, ...values: number[]): void`
* `function tag<number>(string: TemplateStringsArray, ...values: number[]): void`

**Actual behavior:**

Signature help shows `function tag<T>(string: TemplateStringsArray, ...values: T[]): void` in all cases.

Signature help works as expected when calling `tag` directly using a CallExpression.

**Playground Link:** https://agentcooper.github.io/typescript-play/#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwygHMAeAFQD4AKAZwxi1SIC54yQBbAB2gxAGV6jIjQCCMGFACeAGngA6RQDcoEZCBqsyAbQC6ASlZKcWYAG4AUBcJEABrcs3bAEgDeARgC+D68RKpkDgAjEBgKezMgA

**Related Issues:**
#22873 same issue for JSX elements
#23492 PR for JSX elements

**Comment by mhegazy** [comment]
@DanielRosenwasser wanna take a look.

**Comment by DanielRosenwasser** [comment]
Funny thing I found was that

```ts
(foo)()
```

doesn't instantiate `foo` in quick info either, but maybe who cares

**Comment by DanielRosenwasser** [comment]
lol at Daniel from 4 months ago

**Comment by DanielRosenwasser** [comment]
Thanks @a-tarasyuk!
