### ISSUE TITLE
Export keyword function from module

### ISSUE THREAD

**Issue by NN---** [Microsoft/TypeScript#2372]
This doesn't work since you cannot make function by name 'delete'.
But module is an object, so it can have key named 'delete'.

```typescript
module a {
  export function delete() {}
}
```

This could be translated into

```js
var a;
(function (a) {
    function delete$() {
    }
    a.delete = delete$;
})(a || (a = {}));
```

**Comment by mhegazy** [comment]
how would function.name be handled in this proposal?

**Comment by NN---** [comment]
I see.
It is indeed a good question.
I thought about simple case without calling function in the module.
