### ISSUE TITLE
Exclude<any, undefined> does not silence --strictNullChecks

### ISSUE THREAD

**Issue by mqudsi** [Microsoft/TypeScript#23729]
It seems that option `--strictNullChecks` is not aware of `Exclude<any, undefined>` or `NonNullable<any>`.

**TypeScript Version:**  2.8.3

**Search Terms:** NonNullable, any, exclude, strictNullChecks

**Code**

```ts
function isSet(foo: any): foo is Exclude<any, undefined> {
    //return !!foo;
    return(<NonNullable<any>> foo) !== undefined;
}

class Bar {
    foo?: number;

    baz(): void {
        if (isSet(this.foo)) {
            this.foo += 7;
        }
    }
}
```

**Expected behavior:**
When compiled with `--strictNullChecks`, the above code should be legal as `isSet` is correctly decorated to indicate that `foo` cannot be undefined (or null in the case of `NonNullable<any>`).

**Actual behavior:**
An error is thrown on the line `this.foo += 7` with the message `Object is possibly 'undefined'`

**Playground Link:**  

https://www.typescriptlang.org/play/#src=function%20isSet(foo%3A%20any)%3A%20foo%20is%20Exclude%3Cany%2C%20undefined%3E%20%7B%0D%0A%20%20%20%20%2F%2Freturn%20!!foo%3B%0D%0A%20%20%20%20return(%3CNonNullable%3Cany%3E%3E%20foo)%20!%3D%3D%20undefined%3B%0D%0A%7D%0D%0A%0D%0Aclass%20Bar%20%7B%0D%0A%20%20%20%20foo%3F%3A%20number%3B%0D%0A%0D%0A%20%20%20%20baz()%3A%20void%20%7B%0D%0A%20%20%20%20%20%20%20%20if%20(isSet(this.foo))%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20this.foo%20%2B%3D%207%3B%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A

**Related Issues:**

**Comment by ahejlsberg** [comment]
The `Exclude<T, U>` type is used to filter union types, but it doesn't have the ability to "subtract" one type from another. So, `Exclude<any, undefined>` is simply `any`.

I suggest you write your `isSet` function as follows:

```ts
function isSet<T>(foo: T | undefined): foo is T {
    return foo !== undefined;
}
```

That has the intended effect.

**Comment by mqudsi** [comment]
Oh, I didn't realize it only acted on literally specified types! It's funny, I had another function

```ts
export function isValid<T>(foo: any): foo is NonNullable<T> {
    return isSet(foo as T);
}
```

but I didn't realize I could omit the `<T>` entirely in the function call if I wrote it out like that.

Thank you @ahejlsberg, that is exceedingly clever!
