### ISSUE TITLE
Can't define static properties with derived classes

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#23737]
**TypeScript Version:**  master

**Search Terms:** 

**Code**

```ts
class A {
  static readonly p1 = Symbol();
  static readonly p2 = Symbol();
  [A.p1]() {}
  [A.p2] = 0
}
class B extends Object {
  static readonly p1 = Symbol();
  static readonly p2 = Symbol();
  [B.p1]() {}
  [B.p2] = 0
}

```

**Expected behavior:**

pass

**Actual behavior:**

```
$ node built/local/tsc.js index.ts -t es6
index.ts:7:7 - error TS2506: 'B' is referenced directly or indirectly in its own base expression.

7 class B extends Object {
        ~
```

**Playground Link:**  

**Related Issues:** #23736

**Comment by HerringtonDarkholme** [comment]
I'd argue this works as intended.

```ts
class A {
    static method() {return 'myMehthod'}
    [A.method()]() { return '13'}
}
```

gives me `ReferenceError` in Chrome. 

Transpiling in Babel

```ts
class A {
  static  p1 = Symbol();
  [A.p1]() {}
}
```
gives me `Class "A" cannot be referenced in computed property keys`.

**Comment by falsandtru** [comment]
If you are right, TypeScript's type checking is originally wrong. According to the Chrome behavior, you seem correct. But is static class member already standardized? I feel it is not sure that we should respect that behavior. At least that behavior is not ideal as the polyfill of static properties using static methods. And probably it is avoidable undesired behavior.

**Comment by falsandtru** [comment]
And probably we should discuss it in #23736.
