### ISSUE TITLE
Passthrough require("jsfile") for commonjs

### ISSUE THREAD

**Issue by dbarbeau** [Microsoft/TypeScript#2373]
Hello Typescipters,

I'm using the `Q` library with its typings installed via `tsd`.
In a module I'm using
```typescript
/// <reference path="../typings/q/Q.d.ts"/>
// ...
```

compiled with
```bash
tsc -m commonjs --out test.js test.ts
tsc --version
message TS6029: Version 1.4.1.0
```
and would like `test.js` to contain a line like
```javascript
var Q = require("path/to/q"); // to be executed by nodejs
```
where `path/to/q` points to the javascript file and has nothing to do with `../typings/q/Q.d.ts`.
Using `import Q = require("path/to/q");` won't work as it probably expects a typescript module.
```bash
builder.ts(5,32): error TS2307: Cannot find external module './../bower_components/q/q'.
```

I haven't found how to achieve this without rolling out some hackish *ad-hoc* source markup/parse/replace. Have I overlooked something?

In a way I'm trying to "link" to the library code (in the C meaning) with node's `require` after having included the declarations (references to the `d.ts`).

If this is not currently possible, may I suggest a pass-through version of `require()` which kicks in when `-m commonjs` is used? Perhaps `js_require("blabla")` which would be emitted as node's `require("blabla")`. This would make it a lot easier to leverage other tools which analyze `require` statements.

Greetings

**Comment by DanielRosenwasser** [comment]
> Using `import Q = require("path/to/q");` won't work as it probably expects a typescript module.

The `import` keyword with a `require(...)` on the RHS works the same way as if you'd used a `var` except that it also brings in type information at compile time. What you can do in `test.js` is include both the `/// <reference path="../typings/q/Q.d.ts"/>` and then `import Q = require("path/to/q");`. Give it a try and let us know. If not, maybe there's some information I'm missing.

**Comment by dbarbeau** [comment]
Hi! And thanks!
I think you meant using `var` instead of `import`, because
```typescript
/// <reference path='typings/q/Q.d.ts'/>
import q = require("bower_components/q/q");
var deferred = Q.Promise(function(a,b,c){});
```
throws `error TS2307: Cannot find external module 'bower_components/q/q'` and no code is generated (the output file is blank) while
```typescript
/// <reference path='typings/q/Q.d.ts'/>
var q = require("bower_components/q/q");
var deferred = Q.Promise(function(a,b,c){});
```
throws `error TS2304: Cannot find name 'require'` and... the compiler does output the code I want :)
So it does work, though user feedback is a bit misleading!

Thanks again ;)

**Comment by dbarbeau** [comment]
I should have done a few more tests, because there is a catch:

```typescript
/// <reference path="typings/node/node.d.ts"/>
/// <reference path="typings/q/Q.d.ts"/>

var Q            = require("./../bower_components/q/q");   /* LINE X */
import path   = require("path"); /* LINE Y */

var qprom = Q.Promise(function(a,b,c){
    var dummy = path.join(__dirname, "yo");  /* LINE Z */
});
```
The reference tag will declare Q with the type information.
**LINE X** will declare another Q.

If you compile it like this, tsc 1.4.1.0 will emit no error, but also no code :)
Remove **LINE Y** and **LINE Z** and you'll get.

```bash
requiretest2.ts(4,5): error TS2300: Duplicate identifier 'Q'.
typings/q/Q.d.ts(10,18): error TS2300: Duplicate identifier 'Q'.
typings/q/Q.d.ts(14,18): error TS2300: Duplicate identifier 'Q'.
typings/q/Q.d.ts(16,16): error TS2300: Duplicate identifier 'Q'.
```

Seems reasonable enough, although the compiler does emit the code I want. 

Now, suppose that TS2300 didn't emit code (or that I simply want to avoid having errors in my code). I'd have to write my typescript code against the Q declared in the 'Q.d.ts' file, but this would conflict with the Q created on the `require(...)` line. So, I'd have to write `var smallq = require(...);` instead of **LINE X**, but then at runtime nodejs would complain that `Q` doesn't exist. Or I write against `smallq` and lose the benefit of types.

I'm in a deadlock :)

**Comment by danquirk** [comment]
You absolutely want to use ```import``` and not ```var```. Without ```import``` there is no type information associated with the ```Q``` you declared. You also just want to require the name as ```'q'``` and not the relative path. The last 3 lines of Q.d.ts are written to enable this pattern, similar to why you can require ```"path"``` like that from node.d.ts. This is how it should look:

```ts
/// <reference path="Q.d.ts"/>
import Q = require('q');

var aprom = Q.Promise((a,b,c) => {
    console.log('hi');
});
```
emits:
```
> tsc a.ts -m commonjs
> type a.js
/// <reference path="Q.d.ts"/>
var Q = require('q');
var aprom = Q.Promise(function (a, b, c) {
    console.log('hi');
});
```

**Comment by dbarbeau** [comment]
Thank you @DanielRosenwasser and @danquirk  for the clear instructions, I wasn't going the right way. Now, I just had one issue in that compiling that exact file (`a.ts`) with:
```bash
tsc a.ts -m commonjs --out a.js
```
(notice the --out flag) produced an empty `a.js`, whereas just omitting the `--out a.js` flag worked. I'm a bit confused, I'll need to check my installation, there's something fishy. Regarding the initial question I think it has been answered so this issue is closed.

###LAST MINUTE OMG
The `--out` doesn't do what I expected it to do!
```bash
> rm *.js
> tsc a.ts -m commonjs --out ahaha.js
> ls -l
total 8
-rw-rw-r--. 1 d d 136 16 mars  22:51 a.js
-rw-rw-r--. 1 d d 131 16 mars  22:40 a.ts
-rw-rw-r--. 1 d d   0 16 mars  22:51 ahaha.js
```
I was NOT expecting `a.js`, I thought the output would just end up in `ahaha.js`. So by specifiying that flag, I was overwriting tsc's output with a blank file. But why is it blank?
I'll need to check my basic assumptions of life (like does `gcc -o` behave like this?)... wow!

Thanks again!
Daniel

**Comment by danquirk** [comment]
You generally don't want to use --out with external modules like you have. The target file for --out only gets whatever is in the global namespace. This is good when you're concatenating multiple internal modules together but it doesn't support concatenating multiple files together into a single external module. So most of the time you'll get 1 js file per ts file and an empty file that you asked --out for. We have an issue logged somewhere around here to consider just making it an error if --out creates an empty file since other people also get confused by this behavior .
