### ISSUE TITLE
Transpiled async generators return a promise value

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#23731]
At least Chrome unwraps promise values. This makes a different runtime behavior.

**TypeScript Version:**  2.7.0-dev.201xxxxx

**Search Terms:** 

**Code**

```ts
(async function* () {yield Promise.resolve(0)})().next().then(console.log)
```

**Expected behavior:**

Outputs `{value: 0, done: false}`.

**Actual behavior:**

Outputs `{value: Promise, done: false}`.

**Playground Link:**  

**Related Issues:**

**Comment by Kovensky** [comment]
Related to https://github.com/Microsoft/TypeScript/issues/21115

**Comment by falsandtru** [comment]
Thanks, it seems to address the same issue.
