### ISSUE TITLE
Improve intellisense for functions like addEventListener

### ISSUE THREAD

**Issue by andrewiggins** [microsoft/TypeScript#23730]
**TypeScript Version:**  2.9.0-dev.20180426

**Search Terms:** 
* addEventListener intellisense
* generic function intellisense

**Code**

```ts
interface EventTypeMap {
    event1: string;
    event2: number;
}

declare function addEvent<K extends keyof EventTypeMap>(type: K, listener: (e: EventTypeMap[K]) => any): void

addEvent("event1", e => e.toLowerCase());
addEvent("event2", e => e.toFixed());
```

**Expected behavior:**
Would it be possible for the intellisense for the above function to provide discrete signatures for each possible value of the extended type (assuming it is a union or other applicable type that has discrete values), like the picture below? It would greatly simplify the wall of text now produced by the DOM addEventListener function (pictured further below).
 
![image](https://user-images.githubusercontent.com/459878/39337294-0717edf4-4971-11e8-8ec0-080fa4a202b9.png)

**Actual behavior:**
Currently the intellisense just displays the current function definition, expanding the "keyof" type to its discrete possible types.

![image](https://user-images.githubusercontent.com/459878/39337254-d47439c0-4970-11e8-9f22-8a756a18e52e.png)

![image](https://user-images.githubusercontent.com/459878/39337349-54952628-4971-11e8-8de6-f916a4fa1ea8.png)

Note: there isn't any problem once you specify a value for the `type` param. it does scope down the signature to the right one. The suggestion here is to do this upfront for all possible types and display these possible signatures in a list to the user so they are more comprehensible.

![image](https://user-images.githubusercontent.com/459878/39337650-eb911c2a-4972-11e8-8094-9f4b3855a877.png)

**Playground Link:**
http://www.typescriptlang.org/play/index.html#src=%2F%2F%20Event%20type%20to%20event%20interfaces%20map%0D%0Ainterface%20EventTypeMap%20%7B%0D%0A%20%20%20%20event1%3A%20string%3B%0D%0A%20%20%20%20event2%3A%20number%3B%0D%0A%7D%0D%0A%0D%0Adeclare%20function%20addEvent%3CK%20extends%20keyof%20EventTypeMap%3E(type%3A%20K%2C%20listener%3A%20(e%3A%20EventTypeMap%5BK%5D)%20%3D%3E%20any)%3A%20void%0D%0A%0D%0A%2F%2F%20Start%20typing%20%60addEvent(%60%20to%20see%20the%20intellisense%20%0D%0AaddEvent()%0D%0A

**Related Issues:**
None found.

**Comment by RyanCavanaugh** [comment]
The experience here is quite good now: The type stays collapsed as `keyof T`, and you get string literal completion for the possible values.
