### ISSUE TITLE
Different definition behavior for import vs require 

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#23742]
From https://github.com/Microsoft/vscode/issues/48820

**TypeScript Version:**  2.9.0-dev.20180427

**Search Terms:** 
- definition
- javascript

**Code**
For the project:
### `base.js`
```js
module.exports = class Base {
	constructor() {
		console.log( "base" );
	}
}
```

### `foo.js`
```js
const Base = require( "./base" );

class Foo extends Base {
	bar() {
		const base      = new Base();
		const BaseClass = Base;
	}
}
```

1. Run `go to definition` on `Base` in `new Base()` in `foo`

**Expected behavior:**
Goes to class `Base` in `bar.js`

**Actual behavior:**
Goes to `require`. If you use an import, we navigate to the class itself instead of to the import

**Comment by mhegazy** [comment]
Seems working in `typescript@next`. VSCode ships with an older version of TypeScript. Please see [Using Newer TypeScript Versions](https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions) documentation for more details on updating your VSCode to use a different version of TypeScript.

**Comment by mjbvz** [comment]
@mhegazy I still see this in 2.9.0-dev.20180427:

```
[Trace  - 14:52:29] Sending request: definition (171). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/Users/matb/projects/san/foo.js",
    "line": 5,
    "offset": 21
}
[Trace  - 14:52:29] Response received: definition (171). Request took 1 ms. Success: true 
Result: [
    {
        "file": "/Users/matb/projects/san/foo.js",
        "start": {
            "line": 2,
            "offset": 7
        },
        "end": {
            "line": 2,
            "offset": 11
        }
    }
]
```

**Comment by mhegazy** [comment]
this is what i see locally, what am i missing?

```txt
[Trace  - 3:08:51 PM] Sending request: definition (249). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "c:/test/23742/foo.js",
    "line": 5,
    "offset": 28
}
[Trace  - 3:08:51 PM] Response received: definition (249). Request took 5 ms. Success: true 
Result: [
    {
        "file": "c:/test/23742/base.js",
        "start": {
            "line": 2,
            "offset": 2
        },
        "end": {
            "line": 4,
            "offset": 3
        }
    }
]
```

**Comment by mhegazy** [comment]
I was looking at an older build. the behavior you are seeing is caused by https://github.com/Microsoft/TypeScript/pull/23657, where we are returning both declarations. i think in this case we should not return the alias.

**Comment by andy-ms** [comment]
I think @sandersn was working on making `const x = require("x")` an alias, similar to #23570?

**Comment by sandersn** [comment]
We should keep this bug open, because the next alias I planned to introduce was for `module.exports.C = class { }` (tracked by #23788), not for `const x = require('x')`.

**Comment by andy-ms** [comment]
Is this planned eventually though? If it's an alias this will just work without needing any special workaround in goToDefinition, which is probably not the only affected service.

**Comment by sandersn** [comment]
Um, I guess so? There's a large stack of bugs to do with Javascript and I plan to get to them all eventually. :) Right now this is planned for 2.9, but that may be too ambitious.
