### ISSUE TITLE
Better handling of `this` mismatches

### ISSUE THREAD

**Issue by mqudsi** [Microsoft/TypeScript#23749]
**TypeScript Version:**  2.8.3

**Search Terms:** this, intitle:this, this bind

```ts
function assert(expr: boolean, msg: string = "") {
	if (!expr) {
		console.log("assertion failed!");
		throw msg;
	}
}

class Foo {
	_bar: Bar;

	constructor() {
		this._bar = new Bar();
		this._bar.Callback = this.callback;
	}

	public run() {
		this._bar.Callback();
	}

	callback() {
		assert(!(this instanceof Bar), "\"this\" has unexpected type \"Bar\"");
		assert(this instanceof Foo, "\"this\" has unexpected type!");
		console.log("Test passed, \"this\" retains the expected type.");
	}
}

class Bar {
	public Callback: () => void;
	public run() {
		this.Callback();
	}
}

var f = new Foo();
f.run();
```

_I realize the current behavior is by-design, this is a suggestion/request-for-comment to improve type safety here._

**Expected behavior:**

The code above ([playground link](https://www.typescriptlang.org/play/#src=function%20assert(expr%3A%20boolean%2C%20msg%3A%20string%20%3D%20%22%22)%20%7B%0D%0A%09if%20(!expr)%20%7B%0D%0A%09%09console.log(%22assertion%20failed!%22)%3B%0D%0A%09%09throw%20msg%3B%0D%0A%09%7D%0D%0A%7D%0D%0A%0D%0Aclass%20Foo%20%7B%0D%0A%09_bar%3A%20Bar%3B%0D%0A%0D%0A%09constructor()%20%7B%0D%0A%09%09this._bar%20%3D%20new%20Bar()%3B%0D%0A%09%09this._bar.Callback%20%3D%20this.callback%3B%0D%0A%09%7D%0D%0A%0D%0A%09public%20run()%20%7B%0D%0A%09%09this._bar.Callback()%3B%0D%0A%09%7D%0D%0A%0D%0A%09callback()%20%7B%0D%0A%09%09assert(!(this%20instanceof%20Bar)%2C%20%22%5C%22this%5C%22%20has%20unexpected%20type%20%5C%22Bar%5C%22%22)%3B%0D%0A%09%09assert(this%20instanceof%20Foo%2C%20%22%5C%22this%5C%22%20has%20unexpected%20type!%22)%3B%0D%0A%09%09console.log(%22Test%20passed%2C%20%5C%22this%5C%22%20retains%20the%20expected%20type.%22)%3B%0D%0A%09%7D%0D%0A%7D%0D%0A%0D%0Aclass%20Bar%20%7B%0D%0A%09public%20Callback%3A%20()%20%3D%3E%20void%3B%0D%0A%09public%20run()%20%7B%0D%0A%09%09this.Callback()%3B%0D%0A%09%7D%0D%0A%7D%0D%0A%0D%0Avar%20f%20%3D%20new%20Foo()%3B%0D%0Af.run()%3B%0D%0A)) was written with the (incorrect/naive) assumption that at line 13 (`this._bar.Callback = this.callback;`) the function reference would be stored bound to the value of `this` at the time of execution of that line.

I understand why TypeScript can't ditch this horrible behavior and evaluate the code sanely for reasons of backwards compatibility when changing JS file extensions to .TS, but as this is a common type-safety issue, I feel like TS should take measures to mitigate the issue.

TypeScript should be able to catch the unsafe usage of `this` in the example above (it fails the assertions). 

Additionally, when typing `this.<TAB>`, the suggestions generated are for values based on the current scope instead of being `any` or something else, leading one to believe the code is correct.

Suggestions:

* Perhaps a `--strictThis` option generating an error when `this.xxx` is assigned to an object of a different type from the type of `this` in the current scope?
* A new keyword, e.g. `self`, the value of which binds to the current value of `this` that can be used instead.

**Actual behavior:**
The line `this._bar.Callback = this.callback;` does not resolve the value of `this` at the time it is invoked, leading to the failure of the assertion.

**Playground Link:** 
[Link](https://www.typescriptlang.org/play/#src=function%20assert(expr%3A%20boolean%2C%20msg%3A%20string%20%3D%20%22%22)%20%7B%0D%0A%09if%20(!expr)%20%7B%0D%0A%09%09console.log(%22assertion%20failed!%22)%3B%0D%0A%09%09throw%20msg%3B%0D%0A%09%7D%0D%0A%7D%0D%0A%0D%0Aclass%20Foo%20%7B%0D%0A%09_bar%3A%20Bar%3B%0D%0A%0D%0A%09constructor()%20%7B%0D%0A%09%09this._bar%20%3D%20new%20Bar()%3B%0D%0A%09%09this._bar.Callback%20%3D%20this.callback%3B%0D%0A%09%7D%0D%0A%0D%0A%09public%20run()%20%7B%0D%0A%09%09this._bar.Callback()%3B%0D%0A%09%7D%0D%0A%0D%0A%09callback()%20%7B%0D%0A%09%09assert(!(this%20instanceof%20Bar)%2C%20%22%5C%22this%5C%22%20has%20unexpected%20type%20%5C%22Bar%5C%22%22)%3B%0D%0A%09%09assert(this%20instanceof%20Foo%2C%20%22%5C%22this%5C%22%20has%20unexpected%20type!%22)%3B%0D%0A%09%09console.log(%22Test%20passed%2C%20%5C%22this%5C%22%20retains%20the%20expected%20type.%22)%3B%0D%0A%09%7D%0D%0A%7D%0D%0A%0D%0Aclass%20Bar%20%7B%0D%0A%09public%20Callback%3A%20()%20%3D%3E%20void%3B%0D%0A%09public%20run()%20%7B%0D%0A%09%09this.Callback()%3B%0D%0A%09%7D%0D%0A%7D%0D%0A%0D%0Avar%20f%20%3D%20new%20Foo()%3B%0D%0Af.run()%3B%0D%0A)

**Related Issues:**

**Comment by mhegazy** [comment]
duplicate of https://github.com/Microsoft/TypeScript/issues/10288

**Comment by mqudsi** [comment]
Thanks, Mohamed! If it's OK with you, I'll copy my comments there.
