### ISSUE TITLE
VS Code does not treat typescript dot files the way TSC command treats them

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#23750]
_From @KSXGitHub on April 23, 2018 10:13_

- VSCode Version: 1.22.2
- OS Version: Arch Linux

### Steps to Reproduce

1. Create `tsconfig.json`

```json
{
  "compilerOptions": {
     "target": "es2017",
     "module": "commonjs",
     "lib": ["es2017"]
  }
}
```

2. Create 2 files: `.dotfile.ts` (begin with a dot) and `normalfile.ts`

```typescript
Object.entries({})
```

### Expected behavior

There should be no problem

### Actual behavior

In `.dotfile.ts`, linter marks `entries` word with message `[ts] Property 'entries' does not exist on type 'ObjectConstructor'`.

Things are okay in `normalfile.ts`

### Screenshot

![screenshot from 2018-04-23 22-39-18](https://user-images.githubusercontent.com/11488886/39137305-76f66f0a-4747-11e8-926e-6a0a801cf71f.png)

_Copied from original issue: Microsoft/vscode#48385_

**Comment by mjbvz** [comment]
Yes this is by-design. In most cases you do not want dot files included in a project. 

To explicitly include dot files, try setting:

```json
{
    "compilerOptions": {
        "target": "es2017",
        "module": "commonjs",
        "lib": [
            "es2017"
        ]
    },
    "exclude": [
        "node_modules"
    ],
    "include": [
        "**/*.ts",
        "**/.*.ts"
    ]
}
```

**Comment by mjbvz** [comment]
_From @KSXGitHub on April 27, 2018 23:30_

@mjbvz Still, there's inconsistency: `tsc` cli treats them differently (allowing them). I wouldn't complain if its behavior was consistent. My point is VS Code should only tell user what `tsc` cli would tell.

**Comment by mjbvz** [comment]
@mhegazy Thoughts on @KSXGitHub's point about tsc and tsserver handling dot files differently?

**Comment by mhegazy** [comment]
not sure i follow what you mean by tsc allows them.. tsc does not pick up files starting with dots either unless you explicitly specify them in your tsconfig.json.. e.g.:

```shell
c:\test\23750>tree /F .
C:\TEST\23750
    .b.ts
    a.ts
    tsconfig-noInclude.json
    tsconfig-withInclude.json

c:\test\23750>type tsconfig-noInclude.json
{
    "compilerOptions": {
        "target": "es5"
    }
}

c:\test\23750>type tsconfig-withInclude.json
{
    "compilerOptions": {
        "target": "es5"
    },
    "include": [
        "**/*.ts",
        "**/.*.ts"
    ]
}

c:\test\23750>tsc --v
Version 2.8.3

c:\test\23750>tsc --p tsconfig-noInclude.json --listFiles
C:/Users/mhegazy/AppData/Roaming/npm/node_modules/typescript/lib/lib.d.ts
c:/test/23750/a.ts

c:\test\23750>tsc --p tsconfig-withInclude.json --listFiles
C:/Users/mhegazy/AppData/Roaming/npm/node_modules/typescript/lib/lib.d.ts
c:/test/23750/a.ts
c:/test/23750/.b.ts
```

**Comment by KSXGitHub** [comment]
OK, I double-checked, `tsc` ignores dot files. My bad. Sorry for that. This issue can be closed now.
