### ISSUE TITLE
functor in typescript with no higher kinded types

### ISSUE THREAD

**Issue by dagda1** [Microsoft/TypeScript#23758]
I am trying to define a functor in typescript.

In haskell the signature is this:
```
class Functor f where
  fmap :: (a -> b) -> f a -> f b
```
Where f, a and b are parametric types.

In typescript you do not have higher kinded types or in other words, a generic type cannot have a generic type argument.

What I would like to do is:
```
interface Functor<F> {
  map<A, B>(f: (a: A) => B, fa: F<A>): F<B>
}
```
But of course this is not possible.

My best (worst) attempt is this:
```
  export interface Functor<FA extends Object, A, FB extends Object, B> {
    map: (fn: (a: A) => B, fa: FA) => FB;
  }

  export const getArrayFunctor = <A, B>(): Functor<A[], A, B[], B> => {
    return {
      map: (fn, fa) => {
        return fa.map(fn);
      }
    };
  };
```
Is there a better way?

fp-ts and other use this approach but I think [this](https://github.com/gcanti/fp-ts/blob/master/docs/HKT.md) is too complicated for people with no experience that I want to explain this to.

**Comment by DanielRosenwasser** [comment]
Not that I know of, and #1213 tracks higher kinds.
