### ISSUE TITLE
Compiled async/await function is no longer with constructor named as 'AsyncFunction'

### ISSUE THREAD

**Issue by wenshiqi0** [microsoft/TypeScript#23757]
**TypeScript Version:**  2.8.1

**Code**

```ts
async function test() {
    return 'test';
}
```

**Compiled Code**

```js
function test() {
    return tslib_1.__awaiter(this, void 0, void 0, function* () {
        return 'test';
    }
}
```
**Expected behavior:**

Now I try to use `test.construtor.name` to confirm that this is a async function, but get 'Function' instead of 'AsyncFunction'.

**Actual behavior:**

`test.construtor.name` returns 'AsyncFunction'.

**Comment by j-oliveras** [comment]
The compiled code is a function not a async function, then is expected that it constructor is `Function`. If you compile with this `tsconfig.json`:
```json
{ "compilerOptions": { "target": "es2017" } }
```
(or with `"target": "esnext"`) and runs on environment that supports async functions (like node 8) it constructor is `AsyncFunction`.

I used this code (that is compiled without changes):
```ts
async function test() {
    return 'test';
}
console.log(test.constructor.name)
```

**Comment by RyanCavanaugh** [comment]
There's no way to fix this...
