### ISSUE TITLE
React custom DOM attributes

### ISSUE THREAD

**Issue by ClassicDarkChocolate** [Microsoft/TypeScript#23756]
According to https://reactjs.org/blog/2017/09/08/dom-attributes-in-react-16.html
How do I do this in typescript? Some common attribute like "referrerpolicy" is not defined in the definition.

**Comment by DanielRosenwasser** [comment]
Technically `DOMAttributes` should have an index signature on it:

```ts
    // ...
    [attributeName: string]: any;
```

But I don't know how desirable that is for the majority of users. Consider sending a PR for https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts to get a discussion going.

**Comment by mhegazy** [comment]
I do not think this is a good change. That will disable excess property checking for all users
