### ISSUE TITLE
Please document: JSX > IntrinsicClassAttributes

### ISSUE THREAD

**Issue by bcherny** [Microsoft/TypeScript#23767]
The JSX docs do a really great job of documenting the various hooks that TS uses to typecheck and compile JSX in a generic way.

However, there are a few types that are noticeably missing. Do these have special meaning, or are they just used by React internally? And if they do have special meaning, it would be really nice if we can document them:

- `JSX.Element`: The type of a value-based element class/function?
- `JSX.IntrinsicAttributes`: The attributes that are defined on every intrinsic class instance? (it looks like you can already express this using `JSX.IntrinsicElements` - is this just for convenience?)
- `JSX.IntrinsicClassAttributes`: Attributes that are defined on every intrinsic element's class?

**Comment by mhegazy** [comment]
@weswigham can you update https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/JSX.md page to add more details.
