### ISSUE TITLE
[Q] How to get error exitcode from tsc running from command line

### ISSUE THREAD

**Issue by evil-shrike** [Microsoft/TypeScript#23765]
Hi.

I'm writing a shell script that compiles my project with different TS versions (previously downloaded in a `typescript-installs` folder):
```
FOR /D %%f IN (.\typescript-installs\*) DO (
	echo Running TS from %%f
	call node "%%f\node_modules\typescript\bin\tsc"
	echo Exit Code is %errorlevel%
)
```
Unfortunately even if tsc reports errors `%errorlevel%` returns 0.
Is there any way to detect error exit code from `tsc`?
I want to fail my CI-build basing on failed errorcode.

**Comment by mhegazy** [comment]
Not sure what you mean by it is not reported.. here is what i see locally:

```shell
c:\test\23765>type a.ts
var x: number = true;

c:\test\23765>tsc --v
Version 2.8.3

c:\test\23765>tsc a.ts
a.ts(1,5): error TS2322: Type 'true' is not assignable to type 'number'.

c:\test\23765>echo Exit Code is %errorlevel%
Exit Code is 2
```

**Comment by evil-shrike** [comment]
Thanks, my bad. 
It was tricky errorlevel handling in FOR loops.
In FOR loops `%errorlevel%` is resolved before iterating actually happens.
This is correct code:
```
@echo off
setlocal enabledelayedexpansion
FOR /D %%f IN (.\typescript-installs\*) DO (
	echo Running TS from %%f
	call node "%%f\node_modules\typescript\bin\tsc"
	echo Exit Code is !errorlevel!
)
```
More info: https://stackoverflow.com/questions/3942265/errorlevel-in-a-for-loop-batch-windows
closing.
