### ISSUE TITLE
Allow to go from `Type` to initial `TypeAlias`

### ISSUE THREAD

**Issue by s-panferov** [Microsoft/TypeScript#23772]
Hello. Author of [awesome-typescript-loader](https://github.com/s-panferov/awesome-typescript-loader) here. I'm writing a next-gen documentation generator for TypeScript: [docscript](https://github.com/s-panferov/docscript) (based on modern TypeScript and ReactJS, and I'm planing to run something like https://docs.rs/) and it is mostly done, but I faced one thing that is very hard to overcome — type aliases.

Right now my global approach is to walk over top-level `Symbol`s of the project and then extract symbol types and walk and reflect them. I'm trying to avoid walking over syntax `Node`s, because this way I can avoid dealing with declaration merging and other nasty things. This approach works for everything except type aliases, because of early-expansion.

Example:

```typescript
type Alias = number
const a: Alias
```

In a compiled program `Type` of `a` will contain `number`, and do not contain any references to  `Alias`'s symbol and it's impossible to connect them at this stage.

Another complex example is from `@types/react` and involves indexed access:

```ts
type Validator<T> = { bivarianceHack(object: T, key: string, componentName: string, ...rest: any[]): Error | null }["bivarianceHack"];

type ValidationMap<T> = {[K in keyof T]?: Validator<T> };
                                             ^--- here I see `bivarianceHack` method 
                                                   as a type, because it was expanded 
                                                   from Validator<T> and then form indexed access
```

In this example it would be nice to be able to go back from `bivarianceHack` method up to initial `Validator<T>` type reference.

Im asking for some way to go from `Type` to `TypeAlias`'s Symbol. Is it possible right now somehow (except working with syntax nodes)? Is it possible to add the connection? Or you advice to switch to syntax-based approach and try to re-implement all declaration and type-merging logic by myself?

**Comment by mhegazy** [comment]
> Hello. Author of awesome-typescript-loader here. I'm writing a next-gen documentation generator for TypeScript: docscript (based on modern TypeScript and ReactJS, and I'm planing to run something like https://docs.rs/) and it is mostly done

Not related to the issue at hand, but there is a group working on a documentation generator in https://github.com/Microsoft/tsdoc. wounding if both projects can collaborate.

**Comment by mhegazy** [comment]
Type aliases are just that, aliases. they are expanded to the types they alias. The compiler has a limited capability to link unique types to aliases (`Type.aliasSymbol`), this used in error reporting. but the general problem, i am afraid is unresolved. given a type where did it originate is a question the compiler can not answer today. you can build a reverse map from types to aliases, and use that, or you can rely on nodes to serialize your types.

**Comment by s-panferov** [comment]
@mhegazy thanks for pointing out to `Type.aliasSymbol`, this can cover most common use-cases. And I'll probably try to communicate with https://github.com/Microsoft/tsdoc project, but right now I  see that they're working on own JSDoc dialect for typescript, this is a little bit different of what I'm doing.
