### ISSUE TITLE
Propery "x" does not exist in type "Y", but it actually exists.

### ISSUE THREAD

**Issue by FlamesoFF** [Microsoft/TypeScript#23775]
typescript: v2.8.1;
node: v8.11.1;

I got this compiler error in my VSCode:

**Code**

```ts
...
export type TAbstractHandler  = {
    type: TMessage;
    fn: Function;
}
...
let handler : TAbstractHandler;
handler.type; // OK
handler.fn(); // Propery "fn" does not exist in type "TAbstractHandler".
```

WTF?

**Comment by jamiewinder** [comment]
No error appears here:

https://www.typescriptlang.org/play/#src=export%20type%20TAbstractHandler%3CTMessage%3E%20%3D%20%7B%0D%0A%20%20%20%20type%3A%20TMessage%3B%0D%0A%20%20%20%20fn%3A%20Function%3B%0D%0A%7D%0D%0A%0D%0Alet%20handler%20%3A%20TAbstractHandler%3Cany%3E%3B%0D%0Ahandler.type%3B%20%2F%2F%20OK%0D%0Ahandler.fn()%3B%20%2F%2F%20OK

(I've assumed your type is abstract, but that shouldn't matter)

I think whatever is causing your error has been omitted from this example?

**Comment by FlamesoFF** [comment]
@jamiewinder Try ty paste this code in any IDE with the same TS version and you will see the error.
