### ISSUE TITLE
Nested conditional types don't work with never type (regression)

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#23779]
It had work until 20180429.

cc @ahejlsberg 

**TypeScript Version:**  2.9.0-dev.20180430

```
TypeScript error: src/type.test.ts(242,26): Error TS2322: Type 'false' is not assignable to type 'true'.
TypeScript error: src/type.test.ts(243,26): Error TS2322: Type 'false' is not assignable to type 'true'.
TypeScript error: src/type.test.ts(245,26): Error TS2322: Type 'false' is not assignable to type 'true'.
```

https://github.com/falsandtru/spica/blob/v0.0.167/src/type.test.ts#L239

This is the failure of removing properties which have never type.

https://github.com/falsandtru/spica/blob/v0.0.167/src/type.ts#L74

But that process is succeeded as follows.

https://github.com/falsandtru/spica/blob/v0.0.167/src/type.test.ts#L260

So it's failed only with that nested place.

**Comment by ahejlsberg** [comment]
Can you post a self contained smaller repro?

**Comment by falsandtru** [comment]
I'll try it later.

**Comment by falsandtru** [comment]
Moved to #23800
