### ISSUE TITLE
null literal and const null variable have different behaviour with strictNullChecks

### ISSUE THREAD

**Issue by RainingChain** [Microsoft/TypeScript#23771]
**TypeScript Version:**  2.8.1

**Search Terms:** null literal 

**Code**

```ts
//strictNullChecks:true
  const myNull:null = null;
  const objWithValMaybeNull:{val:number | null} = {val:1};
  const addOne = function(num:number){
    return num + 1;
  }
  if(objWithValMaybeNull.val !== null)
    addOne(objWithValMaybeNull.val);    //no error
  if(objWithValMaybeNull.val !== myNull)
    addOne(objWithValMaybeNull.val);    //error (Bug: shouldn't be an error)

  if(objWithValMaybeNull.val === null)
    addOne(objWithValMaybeNull.val);    //error
  if(objWithValMaybeNull.val === myNull)
    addOne(objWithValMaybeNull.val);    //no error (Bug: should be an error)
```

**Expected behavior:**
`addOne(objWithValMaybeNull.val);    //Shouldn't be an error`

**Actual behavior:**
`addOne(objWithValMaybeNull.val);    //Is an error`

**Playground Link:**  
strictNullChecks must be to true. (I can't believe the playground generated URL doesn't take into consideration the options. Especially considering its meant as a way to report issues...)

https://www.typescriptlang.org/play/index.html#src=%20%20const%20myNull%3Anull%20%3D%20null%3B%0D%0A%20%20const%20objWithValMaybeNull%3A%7Bval%3Anumber%20%7C%20null%7D%20%3D%20%7Bval%3A1%7D%3B%0D%0A%20%20const%20addOne%20%3D%20function(num%3Anumber)%7B%0D%0A%20%20%20%20return%20num%20%2B%201%3B%0D%0A%20%20%7D%0D%0A%20%20if(objWithValMaybeNull.val%20!%3D%3D%20null)%0D%0A%20%20%20%20addOne(objWithValMaybeNull.val)%3B%20%20%20%20%2F%2Fno%20error%0D%0A%20%20if(objWithValMaybeNull.val%20!%3D%3D%20myNull)%0D%0A%20%20%20%20addOne(objWithValMaybeNull.val)%3B%20%20%20%20%2F%2Ferror%20(Bug%3A%20shouldn't%20be%20an%20error)%0D%0A%0D%0A%20%20if(objWithValMaybeNull.val%20%3D%3D%3D%20null)%0D%0A%20%20%20%20addOne(objWithValMaybeNull.val)%3B%20%20%20%20%2F%2Ferror%0D%0A%20%20if(objWithValMaybeNull.val%20%3D%3D%3D%20myNull)%0D%0A%20%20%20%20addOne(objWithValMaybeNull.val)%3B%20%20%20%20%2F%2Fno%20error%20(Bug%3A%20should%20be%20an%20error)

**Related Issues:**

**Comment by Kingwl** [comment]
type guard cannot narrow null literal type (yet)

**Comment by andy-ms** [comment]
Another repro:
```ts
const myNull: null = null;

function f(x: number | null) {
    if(x === myNull) {
        const s: string = x; // Should be an error!
    }
}
```
