### ISSUE TITLE
Type narrowing doesn't work with mutable variables in closures

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#23776]
Includes arguments.

**TypeScript Version:**  2.9.0-dev.201xxxxx

**Search Terms:** 

**Code**

```ts
declare const a: {} | void;
if (a instanceof Object) a; // {}
if (a instanceof Object) () => a; // {}
declare let b: {} | void;
if (b instanceof Object) b; // {}
if (b instanceof Object) () => b;
```

**Expected behavior:**

```ts
if (b instanceof Object) () => b; // {}
```

**Actual behavior:**

```ts
if (b instanceof Object) () => b; // void | {}
```

**Playground Link:**  

**Related Issues:**

**Comment by falsandtru** [comment]
Seems like it also breaks colorization.

**Comment by andy-ms** [comment]
Duplicate of #9998
Could you explain the problem with colorization?

**Comment by falsandtru** [comment]
Indeed.

On the colorization, the last `return` keyword is white, should be blue.

```ts
    if (process instanceof Coroutine) return this.register(
      name,
      {
        init: state => state,
        main: (param, state) =>
          (process as Coroutine<R, R, P>)[Coroutine.port].send(param)
            .then<Supervisor.Process.Result<R, S>>(({ value: reply, done }) =>
              done
                ? void this.kill(name, undefined) ||
                  (process as Coroutine<R, R, P>).then<Supervisor.Process.Result<R, S>>(reply =>
                    [reply, state])
                : [reply, state,]),
        exit: reason => void process[Coroutine.terminator](reason),
      },
      state,
      reason);
    return super.register(name, process, state);
```

https://github.com/falsandtru/spica/blob/v0.0.167/src/supervisor.es2018.ts#L29

**Comment by andy-ms** [comment]
@falsandtru What editor? I see colorized `return` when pasting that example into vscode. (With or without the latest [grammar](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) installed.

**Comment by falsandtru** [comment]
Hm, I'm using VSCode v1.22.2 on Win10.

**Comment by andy-ms** [comment]
What's your color scheme?

**Comment by falsandtru** [comment]
Dark (Visual Studio).

**Comment by falsandtru** [comment]
Oh No! Please open and check https://github.com/falsandtru/spica/blob/v0.0.167/src/supervisor.es2018.ts#L29 via vscode!

**Comment by andy-ms** [comment]
Looks like the error is only present in vscode non-insiders without the latest grammar installed.

**Comment by falsandtru** [comment]
This is my screenshot.

![image](https://user-images.githubusercontent.com/3143368/39435936-9c6501f8-4cd7-11e8-9098-1dd2b2175c38.png)

**Comment by falsandtru** [comment]
> Looks like the error is only present in vscode non-insiders without the latest grammar installed.

I see, I wait for the next release. Currently, this is not a critical problem for me.

**Comment by andy-ms** [comment]
You can also open the extensions sidebar and search for "latest typescript and javascript grammar".

**Comment by falsandtru** [comment]
Resolved, thanks for letting me know!
