### ISSUE TITLE
Exclude does not properly work on type definitions using index signatures

### ISSUE THREAD

**Issue by HunderlineK** [Microsoft/TypeScript#23770]
**TypeScript Version:**  2.8.0

**Search Terms:** 

**Code**

```ts
import express from "express";

type Methods = "post" | "get" | "delete";

type MethodHandlers = Exclude<
  { [M in Methods]?: express.RequestHandler },
  { [M in Methods]?: undefined }
>;
```

**Expected behavior:**
`{ 'get': undefined }` should be an error

**Actual behavior:**
It will be okay

----

To be more precise, I believe merely `{ [M in Methods]?: express.RequestHandler }` should also imply that `{ 'get': undefined }`  is an error, but perhaps that is another issue.

**Comment by andy-ms** [comment]
What are you trying to accomplish here? If you just want to forbid `undefined` values, you could simply not make the properties optional in the first place:
```ts
type Methods = "a" | "b";
type MethodHandlers = { [M in Methods]: number };
const x: MethodHandlers = { a: 0, b: undefined }; // Error
```

**Comment by HunderlineK** [comment]
I want to make sure that at *one* value is present; that is, the object cannot be empty.

On a side note, I wonder if `{ [M in Methods]?: undefined }` is evaluated the same as `{}`

**Comment by andy-ms** [comment]
I don't think there's a way to write a type that allows `{ a, b }` or `{ a }` or `{ b }` but not `{}`. Note that `Exclude` does not implement [negative types]( #4196), it just takes members out of a union type.

**Comment by andy-ms** [comment]
> On a side note, I wonder if { [M in Methods]?: undefined } should be evaluated the same as {} and why it is evaluated differently

Everything is a subtype of `{}`, but `{ x: number }` is not a subtype of `{ x?: undefined }`, because in the latter `x` *must* be undefined if it exists, while `{}` places no restrictions on `x` at all.

**Comment by HunderlineK** [comment]
Thanks, I see how it works. I am not sure if that is consistent behaviour though: if we define `emtyObject: {} = {}`, we will not be able to add any property to it. So technically speaking, no object type should be able to extend `{}`

**Comment by andy-ms** [comment]
Well, it's an error *write* to a property that's not supposed to exist, but there's no error if an object happens to contain a property that isn't needed:

```ts
function f(o: { x: number }) {}
function g(o: { x: number, y: number }) { f(o); }
```

You've probably noticed that we give you an error here though:
```ts
const o: {x: number} = { x: 0, y: 0 };
```
That's an extra, non-type-error check since we figured you wouldn't add a property in an object literal that isn't included in the type.

**Comment by andy-ms** [comment]
@HunderlineK You can always beat the second error by using two variables:
```ts
const o_ = { x: 0, y: 0 }; // Error
const o: {x: number} = o_;
```
Not sure why you would want to though...

**Comment by mhegazy** [comment]
looks like another instance of https://github.com/Microsoft/TypeScript/issues/13195
