### ISSUE TITLE
No intellisense for required builtin node modules after installing @types/node

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#23780]
_From @shepelevstas on April 26, 2018 5:33_

Version 1.22.2
Commit 3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9
Date 2018-04-12T17:28:16.777Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture ia32

**To reproduce:**

_CMD_
```
md test
cd test
md src
npm init -y
npm i @types/node
tsc --init
code . --disable-extensions
```

_//tsconfig.json_
```
{
	// these are default
	"compilerOptions": {
		"target": "es5",
		"module": "commonjs",
		"strict": true,
		"esModuleInterop": true
	},
	// additional
	"files": [
		"./node_modules/@types/node/index.d.ts"
	],
	"include": [
		"src/**/*.ts"
	],
	"exclude": [
		"node_modules"
	]
}
```

_//src/index.ts_
```
const fs = require('fs')
var dirList = fs.| //<- **_NO INTELLISENSE_**
```

Or maybe I'm doing it wrong?

_Copied from original issue: Microsoft/vscode#48731_

**Comment by mjbvz** [comment]
_From @WangPengJu on April 28, 2018 9:52_

I also met this problem
https://github.com/Microsoft/vscode/issues/48883
https://github.com/Microsoft/vscode/issues/45584

**Comment by andy-ms** [comment]
See also #23711

**Comment by WangPengJu** [comment]
a.ts
```
import fs = require("fs");
namespace G {
    export let a = 0;
}
```
b.ts
```
G.a // error 
```
I want use namespace as global. not single module. but if use "import fs = require('fs')" in "a.ts",   "b.ts" can't use G.   if use "const fs = require("fs")", it's work.

"const fs = require("fs")" no  intellisense in vscode, webstorm have intellisense. it's confuse me.

**Comment by mhegazy** [comment]
A file can not be both a global script and a module. it is either one or the other.. `import .. = require(..)` only works for modules. if you are using namespaces, then you should do something like:

```ts
const fs: typeof import ("fs") = require("fs");
```

**Comment by mhegazy** [comment]
@weswigham do we have an issue for higher-order `import` types?

**Comment by weswigham** [comment]
I don't think one's actually been opened yet, no.

**Comment by mhegazy** [comment]
We should then. we should collect such use cases.

**Comment by WangPengJu** [comment]
```
const fs: typeof import ("fs") = require("fs");
```
![image](https://user-images.githubusercontent.com/9954852/39502747-8880e832-4df4-11e8-9a38-255ac7778558.png)
[ts] Cannot find name 'import'.
[ts] The left-hand side of an assignment expression must be a variable or a property access.

**Comment by weswigham** [comment]
@WangPengJu import types are only in the nightly right now, as we've yet to cut a release since adding them.

**Comment by WangPengJu** [comment]
ok. i can wait @weswigham
