### ISSUE TITLE
Type guard with strictNullChecks behaves differently based on block scope

### ISSUE THREAD

**Issue by ryanmcdermott** [Microsoft/TypeScript#23802]
**TypeScript Version:**  2.8.1

**Search Terms:** 
Type guard 

**Code**
```ts
/**
 * Errors are seen with strictNullChecks enabled
 **/
interface Baz {
    test: Function;
}

class Foo {
    bar: Baz | undefined;
    typeGuardCheck1() {
        if (!this.bar) {
            return;
        }

        // Works
        this.bar.test();

        const a = new Promise((resolve) => {
            // ERROR
            this.bar.test();
        });
    }

    typeGuardCheck2() {
        const bar = this.bar
        if (!bar) {
            return;
        }

        // Works
        bar.test();
        
        const a = new Promise((resolve) => {
           // Works 
           bar.test();
        });
    }
}

```

**Expected behavior:**
typeGuardCheck1 and typeGuardCheck2 in the playground link behave identically.

**Actual behavior:**
Given that we have `strictNullChecks` enabled, if we check a property on `this` and return early if it's undefined, and we try to access that property later on in a new scope (such as a function invoked on a `Promise` resolution), then the compiler throws an error. If we do the same thing but instead assign a local variable as a reference to the original property on `this`, the error is not seen. See the Playground link for an example.

**Playground Link:** 

Turn on `strictNullChecks`

https://www.typescriptlang.org/play/index.html#src=interface%20Baz%20%7B%0D%0A%20%20%20%20test%3A%20Function%3B%0D%0A%7D%0D%0A%0D%0Aclass%20Foo%20%7B%0D%0A%20%20%20%20bar%3A%20Baz%20%7C%20undefined%3B%0D%0A%20%20%20%20typeGuardCheck1()%20%7B%0D%0A%20%20%20%20%20%20%20%20if%20(!this.bar)%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20return%3B%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20%20%20%20%20this.bar.test()%3B%0D%0A%0D%0A%20%20%20%20%20%20%20%20const%20a%20%3D%20new%20Promise((resolve)%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20this.bar.test()%3B%0D%0A%20%20%20%20%20%20%20%20%7D)%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20typeGuardCheck2()%20%7B%0D%0A%20%20%20%20%20%20%20%20const%20bar%20%3D%20this.bar%0D%0A%20%20%20%20%20%20%20%20if%20(!bar)%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20return%3B%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20%20%20%20%20bar.test()%3B%0D%0A%20%20%20%20%20%20%20%20%0D%0A%20%20%20%20%20%20%20%20const%20a%20%3D%20new%20Promise((resolve)%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20bar.test()%3B%0D%0A%20%20%20%20%20%20%20%20%7D)%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
In general, there's no way to know that `this.bar` will still be *still* be defined by the time a given callback executes.

See also #11498

**Comment by ryanmcdermott** [comment]
Thanks Ryan! That makes sense
