### ISSUE TITLE
Smart indent for binding patterns is wrong

### ISSUE THREAD

**Issue by JsonFreeman** [Microsoft/TypeScript#2380]
Type either of the following and then press enter:
```ts
var [
```
```ts
var {
```

Expected: The cursor is indented.
Actual: The cursor is not indented.

**Comment by DanielRosenwasser** [comment]
As a heads up @vladima, I think my upcoming changes will take care of this

**Comment by vladima** [comment]
@DanielRosenwasser neat! Let me know if you need anything from me

**Comment by DanielRosenwasser** [comment]
All I can ask is to check the PR (#2385) ASAP so that we can get completions reviewed as well.
