### ISSUE TITLE
TypeScript shouldn't assume `{[name: string]: NonUndefinedType}` has no undefined properties

### ISSUE THREAD

**Issue by KSXGitHub** [Microsoft/TypeScript#23817]
**TypeScript Version:**  2.8.3

**Search Terms:**  object type undefined

**Code**

```ts
interface Foo {
    [_: string]: number
}

const foo: Foo = {}

// foo.abc is undefined, but TypeScript allows this
foo.abc.toString()
```

**Expected behavior:**

Object is possibly undefined

**Actual behavior:**

TypeScript allows it

**Playground Link:**   [link](https://goo.gl/VvVhXr)

**Related Issues:**

**Comment by MartinJohns** [comment]
This is a known issue and is unfortunately "as intended", see #9235, #13161, #12287, and #7140.

There's still an open proposal to add a compiler flag to automatically mark such indexers as `undefined`: 13778
