### ISSUE TITLE
String literal completions have a different kind in TS 2.9

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#23810]
**TypeScript Version:**  2.9.0-dev.201804030

**Search Terms:** 
- suggestions / completions
- string literal

**Code**

```ts
function foo(x: 'abc' | 'def') {
    console.log(x);
}

foo('')
```

Trigger completion inside the empty string literal in `foo('')`

**Expected behavior:**
In TS 2.8.3, the returned string literal completions have kind `"var"`

**Actual behavior:**
In TS 2., the returned string literal completions have kind `"type"`

**Comment by andy-ms** [comment]
Well, the completion comes from a string literal type, so this seems better? There's no "abc" variable, but there is an "abc" type.

**Comment by andy-ms** [comment]
@DanielRosenwasser @mhegazy thoughts?

**Comment by andy-ms** [comment]
On a related note, `ScriptElementKind.primitiveType` is unused. I presume this would be meant for quick info on `number`, where currently we provide no quick info.

**Comment by DanielRosenwasser** [comment]
I need to have some context on why it matters in an editor setting

**Comment by mjbvz** [comment]
We use the kind to determines the icon to show in the suggestions. The icon for `type`  looks strange when used for string completions

**Comment by mhegazy** [comment]
I think us marking it as a type is erroneous. like `type A = "a"; `  that should be a type, but we do not provide completions there any ways. but `foo("a")` should be a value and not a type.
