### ISSUE TITLE
Unit tests not running

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#23836]
**TypeScript Version:**  master

**Code**

Add this to `colorization.ts`:
```ts
it("Colorization_broken", () => {
    throw new Error();
});
```

And run `gulp runtests --t Colorization_broken`. (Or `gulp runtests` alone.)

**Expected behavior:**

Tests fail.

**Actual behavior:**

No test failures.

**Comment by deiga** [comment]
@andy-ms Is this still reproducible? On master it seems to work correctly

**Comment by andy-ms** [comment]
Can't reproduce any more.
