### ISSUE TITLE
[questions] is there any easy way to case a union type?

### ISSUE THREAD

**Issue by leozhao0709** [Microsoft/TypeScript#23853]
Hello, I had several situations that the variable is a type like `string | string[]` or `customerType | customerType[]`. 

When I have this type and want to pass it to a string or string[] value, I always get an error `Type 'string | string[]' is not assignable to type 'string[]'.
        Type 'string' is not assignable to type 'string[]'.`

I know this is because `string | string[]` is not compatible with `string[]`, but is there any easy way to cast `string | string[]` to `string[]`?

**Comment by RyanCavanaugh** [comment]
It looks like this is a question rather than a bug report. This issue tracker is for tracking bugs and active work on TypeScript *itself*, rather than a general forum for programmers using TypeScript to get help or ask questions.
