### ISSUE TITLE
Language Service API should allow to remove newline before interface declaration opening curly bracket

### ISSUE THREAD

**Issue by Maximaximum** [Microsoft/TypeScript#23859]
I'm using `typescript-formatter`, which says that any issues regarding TS formatting should be opened here.

It should be possible to convert
```
export interface AdminForDetails
{
  UserID: number;
  AdminFor: number;
  Hash: string;
}
```
to:
```
export interface AdminForDetails {
  UserID: number;
  AdminFor: number;
  Hash: string;
}
```

**Comment by mhegazy** [comment]
Do you have `placeOpenBraceOnNewLineForFunctions` option set to `true`? if so set it to `false`.

**Comment by Maximaximum** [comment]
I've set it to false, but nothing changes

**Comment by Maximaximum** [comment]
I'm sorry, It seems like the formatter was never actually run. Everything works now the way it's expected
