### ISSUE TITLE
use as after {}

### ISSUE THREAD

**Issue by calidion** [Microsoft/TypeScript#23855]
the ability to use `as` after {}

**Code**

```ts
import * as net from "net";
import {Socket} from 'net'
```

**Expected behavior:**

```ts
import {Socket} as net from 'net'
```

**Comment by andy-ms** [comment]
This is out of scope of the [design goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals) since it involves changing JavaScript's syntax.
