### ISSUE TITLE
Class mustn't be allowed to extends Interfaces, method (overriding, virtual) compile time ambiguity, unexpected runtime behaviour

### ISSUE THREAD

**Issue by wesleyolis** [Microsoft/TypeScript#23860]
**TypeScript Version:**  
2.8.3
"@types/node": "^9.6.6"

**Search Terms:** 
Class extends interface, method overriding failing, virtual methods failing.

**Description**
Classes shouldn't be allowed to extend interfaces, because then overriding and virtual methods behaviour that is associate with classes and the extend keyword fails, because the tsc will not generate the correct prototype javascript, because it see the base class as an interface and not a class.
'Class [ClassName] extends [InterfaceName]' shouldn't be allowed to avoid confusing when writing code at compile time, as it leads to case were one wants to override, extend methods with virtual methods.

An argument can be made about boundaries of prototype chain, that interfaces can always be copied
and that the prototype chain will not always be copied. So if one is extending framework, 3rd party library class, their is high likely hood that the prototype chain many not be that reliable, in which case want to expose classes as interfaces in the .d.ts files. 
Their are case were one would like for their library or framework to support hooking into their prototype chain, with guarantees for reliability that their be no funny business in background to your intend extension of the class. Possible for plain javascript libraries, static analysis, can generate a set of typetags, which ensure that prototype chain and manipulation of certain objects, provide these guaranties for intentional use in this way. Typescript should potentially look at a newkeyword 'proto class', which when types are generated that they can differential from interfaces and vars.. extra, that
the stricter behaviour required for handling of this class is adhered to everywhere and that their no violations of the stricter behaviour. Typescript should limit the class manipulations to stricter set of methods that have been verified, ratified, to requirements.

**Code**

```ts
interface Error
{
message: string;
}

// Classes shouldn't be allowed to extend interface only implement interfaces, this is the bug and leads to this confusion were generated @types/node or typings file is used, were classes can now extend interfaces, which is not true. 

class CustomError extends Error 
{
constructor(msg :string)
{
super(msg);
}

get message : string {
// This shouldn't be allowed and will fail at runtime and is a symptom of class being allowed to extend interfaces.
return "lazy evaluated";
}
}


///////

```

**Expected behavior:**

// expected behaviour, if the class was extending a class.
error.message // base;
(error as CustomError).message // lazy evaluated.

**Actual behavior:**

let error = CustomError("Base");
error.message // base;
(error as CustomError).message // base

**Comment by j-oliveras** [comment]
You have a compile error at `get message : string {` (`'(' expected.` at colon). Should be `get message(): string {`.

This example don't extends the interface Error, extends the built-in class Error. See: [Why doesn't extending built-ins like Error, Array, and Map work?](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-doesnt-extending-built-ins-like-error-array-and-map-work).

**Comment by andy-ms** [comment]
Like @j-oliveras said, what you actually extended was the *class* `Error` which is global. If you had named the interface `MyError`, you would *not* be allowed to extend it.
