### ISSUE TITLE
Suggestion: Refactor extract to type alias/typedef

### ISSUE THREAD

**Issue by mhegazy** [microsoft/TypeScript#23869]
**TypeScript Version:**  2.9.0-dev.201xxxxx

**Search Terms:**  Refactor, extract type, typedef

In a TypeScript file `Extract to type alias`:

```ts
var x: { a: number, b: string } = { .. };
```

would generate:
```ts
type newType = { a: number, b: string }
var x: newType = { .. };
```

In a JavaScript file `Extract to typedef`:

```js
/** @type {import("./c2").mytype} */
var x;
```

would generate:

```js
/** @typedef {import("./c2").mytype} newType */

/**@type {myType} */
var x;
```

gif courtesy of @DanielRosenwasser 

![extracttypealias](https://user-images.githubusercontent.com/972891/39857951-f2f1dc58-53e9-11e8-9762-1a6dc579de29.gif)

**Comment by Kingwl** [comment]
it's very helpful to me

**Comment by mhegazy** [comment]
@Kingwl is that something you would be interested to implement as well? we would accept a PR for this one.

**Comment by Kingwl** [comment]
sure，but it going to be late，my deadline is coming😂

**Comment by Kingwl** [comment]
something need to consider:  

1. option parameter?
2. rest parameter?
3. update all `CallExpression` ?

**Comment by mhegazy** [comment]
- For optional parameters I would strip off the `|undefined` from the type e.g. `function f(a? :number | undefined)` => ` type newType = number ; function f(a?: newType)`
- initializers need to be maintained, e.g. `function f(a : number | string = 0)` should be `type newType = number | string; function f(a: newType = 0)`
- rest parameters are fine, since you are extracting their type
- do not think you need to update call expressions..

I think you are confusing this feature with extract to named arguments. e.g. `function f(a: number, b:string)` => `function f({a, b}: {a: number, b:string})`. this one is tracked by https://github.com/Microsoft/TypeScript/issues/23552.

**Comment by Kingwl** [comment]
Yes, I confused the two feature (:sad) , this one looks like this is a relatively simple operation

**Comment by mhegazy** [comment]
dose not matter what name you pick really. it has to be unique. The new name will be the rename location for the refactoring, and thus the user will get to update it immateriality after the refactor is applied.

**Comment by mhegazy** [comment]
I suppose so.. any type node really should be extractable..

**Comment by RyanCavanaugh** [comment]
@Kingwl we were just wishing we had this 😉

**Comment by Kingwl** [comment]
I'll on it😂

**Comment by welkie** [comment]
The 3.4 release notes mention this issue for providing feedback about this feature were they to expand it to create a type for the new parameter object.

I feel like I nice convention would to be to tap into the name of the function and its class if the function is a method to arrive at the following convention: `FunctionNameOptions` OR `ClassNameMethodNameOptions`.

Example:

Before refactor:

```typescript
class Foo {
    bar(a: string, b: number) {
      console.log('bar');
    }
}
```

Refactored:

```typescript
interface FooBarOptions {
    a: string;
    b: number;
}

class Foo {
    bar(o: FooBarOptions) {
        console.log('bar');
    }
}
```

Instead of `Options`, the suffix could also be things like `Params`, `Args`, etc. Whatever the community thinks makes the most sense.

**Comment by DanielRosenwasser** [comment]
Thanks @kingwl!
