### ISSUE TITLE
Delay in `runtests-browser`

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#23877]
As of #20763, it's taking a lot longer to bring up `runtests-browser`. I've tested this in two parallel checkouts, one in #23875 and one in the commit prior to #20763 (24e58c3b54207b41d7bf922b6d9dcc2ff602a4a9).
First I ran `gulp runtests-browser` in both to ensure everything was built. Then running `gulp runtests-browser --test findAllRefs` in both:
* #20763: It takes about 30 seconds after the tab opens until I'm able to open the debugger.
* Prior commit: it takes only second until I can open the debugger.

There is also a delay when refreshing the window -- so If I missed something and have to restart, I have to wait 30 seconds to begin debugging again.

**Comment by andy-ms** [comment]
![unresponsive](https://user-images.githubusercontent.com/19274678/39715214-6d758340-51e1-11e8-916e-37ba4c7c3a19.jpg)

**Comment by mhegazy** [comment]
I am seeing that too locally after @rbuckton’s cfa change

**Comment by rbuckton** [comment]
I can take a look first thing tomorrow. I think it has something to do with caching.

**Comment by andy-ms** [comment]
I had exception breakpoints turned on and it also looks like we throw a lot of exceptions in vfs.ts on startup -- not sure if that's the cause though.

**Comment by sheetalkamat** [comment]
I have had trouble with lot of exceptions being thrown. Everytime i make some change, i need to go ahead and disable the breakpoints at those exception sites.
