### ISSUE TITLE
Array.from throws "Expected 1-3 arguments, but got 2."

### ISSUE THREAD

**Issue by bowenni** [Microsoft/TypeScript#23880]
**TypeScript Version:**  2.9.0-dev.20180502

**Search Terms:** 
Array.from

**Code**

```ts
Array.from<{}>([1], (num: number) => num);
```

**Expected behavior:**
No errors

**Actual behavior:**
`error TS2554: Expected 1-3 arguments, but got 2.`

**Playground Link:**  
https://www.typescriptlang.org/play/#src=Array.from%3C%7B%7D%3E(%5B%5D%2C%20()%20%3D%3E%20%7B%7D)%3B

**Related Issues:** 

CC @rkirov

**Comment by RyanCavanaugh** [comment]
Duplicate #19220; please put a little more effort into searching next time - you just had to put the error message into the search box or read the second page of search results for "Array.from"

![image](https://user-images.githubusercontent.com/6685088/39606277-7c46fc5a-4ee9-11e8-9819-7db17372141b.png)

**Comment by bowenni** [comment]
Sorry I thought this has something to do with Array.from type declarations and searched for Array.from

**Comment by RyanCavanaugh** [comment]
Actually not really a duplicate since what you were expecting was no error - but this is the intended behavior because you provided a generic type argument arity that didn't match with any normal argument arity

**Comment by bowenni** [comment]
Thanks Ryan. I see the problem now (got confused by the error message).
