### ISSUE TITLE
Declare a type with a JSON file instead of an interface

### ISSUE THREAD

**Issue by ORESoftware** [Microsoft/TypeScript#23895]
I have this question on SO:
https://stackoverflow.com/questions/50181254/static-typing-with-json-and-typescript?noredirect=1#comment87380729_50181254

Why can't we declare a TS type based on a .json file? Something like this:

```js
export type MyInterface = typeof 'path/to/json/file.json'
```

it seems like a no-brainer to me, but maybe I am stupid.

**Comment by RyanCavanaugh** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.
