### ISSUE TITLE
Using keyof with generic lost inner level types

### ISSUE THREAD

**Issue by xbtsw** [Microsoft/TypeScript#23896]
**TypeScript Version:**  2.9.0-dev.20180503, 2.8.3, 2.7.2

**Search Terms:** keyof generic inner

**Code**

```ts
function Test<S>(arg: { [K in keyof S]: S[K] }): S {
  const dummy = {} as S;
  return dummy;
}

// Or equivlently:
// function Test<S>(arg: S): { [K in keyof S]: S[K] } {
//   const dummy = {} as any;
//   return dummy;
// }

const test_inner: string = 'dummy';

// typeof test == { test_inner: string }
const test = Test({
  test_inner
});

// Actual: typeof test_outer == { test: { test_inner: any } }
// Expected: typeof test_outer == { test: { test_inner: string } }
const test_outer = Test({
  test
});

// Actual: typeof test_outmost == { test_outer: { test: any } }
// Expected: typeof test_outmost == { test_outer: { test: { test_inner: string } } }
const test_outmost = Test({
  test_outer
});
```

**Expected behavior:** Please see in-line in code example

**Actual behavior:** Please see in-line in code example

**Playground Link:**  [Playground link](https://www.typescriptlang.org/play/#src=function%20Test%3CS%3E(arg%3A%20%7B%20%5BK%20in%20keyof%20S%5D%3A%20S%5BK%5D%20%7D)%3A%20S%20%7B%0D%0A%20%20const%20dummy%20%3D%20%7B%7D%20as%20S%3B%0D%0A%20%20return%20dummy%3B%0D%0A%7D%0D%0A%0D%0A%2F%2F%20Or%20equivlently%3A%0D%0A%2F%2F%20function%20Test%3CS%3E(arg%3A%20S)%3A%20%7B%20%5BK%20in%20keyof%20S%5D%3A%20S%5BK%5D%20%7D%20%7B%0D%0A%2F%2F%20%20%20const%20dummy%20%3D%20%7B%7D%20as%20any%3B%0D%0A%2F%2F%20%20%20return%20dummy%3B%0D%0A%2F%2F%20%7D%0D%0A%0D%0Aconst%20test_inner%3A%20string%20%3D%20'dummy'%3B%0D%0A%0D%0A%2F%2F%20typeof%20test%20%3D%3D%20%7B%20test_inner%3A%20string%20%7D%0D%0Aconst%20test%20%3D%20Test(%7B%0D%0A%20%20test_inner%0D%0A%7D)%3B%0D%0A%0D%0A%2F%2F%20Actual%3A%20typeof%20test_outer%20%3D%3D%20%7B%20test%3A%20%7B%20test_inner%3A%20any%20%7D%20%7D%0D%0A%2F%2F%20Expected%3A%20typeof%20test_outer%20%3D%3D%20%7B%20test%3A%20%7B%20test_inner%3A%20string%20%7D%20%7D%0D%0Aconst%20test_outer%20%3D%20Test(%7B%0D%0A%20%20test%0D%0A%7D)%3B%0D%0A%0D%0A%2F%2F%20Actual%3A%20typeof%20test_outmost%20%3D%3D%20%7B%20test_outer%3A%20%7B%20test%3A%20any%20%7D%20%7D%0D%0A%2F%2F%20Expected%3A%20typeof%20test_outmost%20%3D%3D%20%7B%20test_outer%3A%20%7B%20test%3A%20%7B%20test_inner%3A%20string%20%7D%20%7D%20%7D%0D%0Aconst%20test_outmost%20%3D%20Test(%7B%0D%0A%20%20test_outer%0D%0A%7D)%3B%0D%0A)

**Related Issues:**  Didn't find anything similar

**Comment by RyanCavanaugh** [comment]
Tracking at #23897
