### ISSUE TITLE
Declare a type with a JSON file instead of an interface

### ISSUE THREAD

**Issue by ORESoftware** [Microsoft/TypeScript#23898]
## Search Terms

typescript json interface file

## Suggestion

I have this question on SO:
https://stackoverflow.com/questions/50181254/static-typing-with-json-and-typescript?noredirect=1#comment87380729_50181254

Why can't we declare a TS type based on a .json file? Something like this:

```js
export type MyInterface = typeof 'path/to/json/file.json'
```

it seems like a no-brainer to me, but maybe I am stupid.

## Use Cases

Keep things DRY. Use JSON files as interfaces.

## Examples

Done did.

## Checklist

My suggestion meets these guidelines:
 [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
 [x] This wouldn't change the runtime behavior of existing JavaScript code
 [x] This could be implemented without emitting different JS based on the types of the expressions
 [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by mhegazy** [comment]
You are in luck!  https://github.com/Microsoft/TypeScript/pull/22167 just got merged, and with `--resolveJsonModule` you can load the json object in your program and use its type..

with `import` types too you can capture that type in a type alias:

```ts
type schemaType = typeof import("./schema.json");
```

**Comment by ORESoftware** [comment]
nice that is cool, how do we know when the next `tsc` version will be published on NPM? is there some notification system?

**Comment by mhegazy** [comment]
It is published nightly around midnight PST

**Comment by ORESoftware** [comment]
@mhegazy one potential improvement!

tsc can now use .json files for types - but can `tsc` use json-schema files to determine generic types?

for example, say I have this JSON file:

```json
{
  "foo":"bar"
}
```

now, foo the interface for the above could be:

```
interface JSON {
  foo: "bar"
}

```
or it could be:

```
interface JSON {
  foo: string
}
```

which does `tsc` currently do? Could `tsc` be updated to handle json-schema from 
http://json-schema.org/

?

**Comment by ORESoftware** [comment]
@mhegazy what about importing json files and getting type info? If I do:

```typescript
import json = require('../../my.json')
```
and also use:

`"resolveJsonModule": true,` 

in my tsconfig.json. My project no longer compiles correctly. Is this a known problem? Should I file a new ticket?

**Comment by mhegazy** [comment]
>  Should I file a new ticket?

yes please.

**Comment by ORESoftware** [comment]
@mhegazy thanks, I filed the issue here: https://github.com/Microsoft/TypeScript/issues/25216
