### ISSUE TITLE
DeclarationDir needs to be handled in excludeSpecs if exclude is not specified

### ISSUE THREAD

**Issue by sheetalkamat** [Microsoft/TypeScript#23891]
**TypeScript Version:**  2.9.0-dev.201xxxxx

**Search Terms:** 

**Code**
Should ```declarationDir``` also be part of excludeSpec if exclude is not specifies in the tsconfig just like ```outDir```?

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**Expected behavior:**

**Actual behavior:**

**Playground Link:**  

**Related Issues:**

**Comment by a-tarasyuk** [comment]
@mhegazy I'll work on this issue if you don't mind

**Comment by mhegazy** [comment]
go for it.
