### ISSUE TITLE
JSDoc @template type parameters with commas don't parse nicely when contained in braces

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#23907]
While this doesn't work in Closure, we should at least issue an error here and parse it gracefully.

```js
/**
 * @template {T, U}
 * @typedef Morphism {(x: T) => U}
 */
```

**Comment by mhegazy** [comment]
Does not seem that there is any documentation about the `{T, U}` syntax. The only authoritative source i could find for this is the [closure compiler docs](https://github.com/google/closure-compiler/wiki/Generic-Types#multiple-template-types), and they use `@template T, U`

**Comment by DanielRosenwasser** [comment]
Correct, but we should not throw a hissy fit when users screw up the syntax.

**Comment by sandersn** [comment]
What is the expected vs actual error here? master (3.1) right now says `'}' expected` on the comma, which seems fine to me.
