### ISSUE TITLE
let renaming for es5 leaking to other objects

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#2390]
This: 
```ts
var error;
if(true){
    let foo = 123;
    error = {
        foo:123
    }
}
```
Is generating 
```ts
var error;
if (true) {
    var _foo = 123;
    error = {
        _foo: 123
    };
}
```

Notice `_foo` here: 
```js
error = {
     _foo: 123
};
```
Using the version on `2015-03-10` : https://github.com/TypeStrong/atom-typescript/blob/e4e8c5e8b02ef9885a655d495464e3f4803bb833/package.json#L34

**Comment by vladima** [comment]
Dupe of #2350 that was recently fixed.
Now emit for your code looks like
```typescript
var error;
if (true) {
    var foo = 123;
    error = {
        foo: 123
    };
}
```

**Comment by basarat** [comment]
Yup. Fixed :heart:
