### ISSUE TITLE
Populate inheritied properties and methods in completion list inside a child class

### ISSUE THREAD

**Issue by slinstj** [Microsoft/TypeScript#23913]
## Search Terms

I found this **closed** isse #7158 but the "problem" (feature) is not resolved (implemented) and the issue says it is. But we dont have this working right now.

## Suggestion

All information is on the cited issue but, to be short:  

If I have a `FatherClass` having a `public function doSomething($param1, $param2)`. So, when creating a `class ChildClass extends FatherClass` and trying to type `do[Ctrl + Space]` or only `[Ctrl + Space]` I hope it to show me the complete method and when I select it the function code block will be created to me.  

This is supported by PHPStorm, NetBeans, Sublime, Notepad (no, that one is not). 

## Why is this being reopen?
Because this: https://github.com/Microsoft/TypeScript/issues/7158#issuecomment-337070541

**Thank you!**

**Comment by DanielRosenwasser** [comment]
`public function doSomething` is not valid syntax in the body of a `class`. Do you have a minimal piece of code that exhibits the issue?

**Comment by slinstj** [comment]
So sorry, I was some hours (late on the night) looking for solutions for this problem in **VSCode**, not in TypeScript exactly. Not sure how I was brought to here after access so many links and repos.

BTW, `public function doSomething($param1, $param2)` is a valid syntax for PHP class' methods.
