### ISSUE TITLE
TypeScript debugging does not work when using Kerberos authentication. (workaround: include js and map in project)

### ISSUE THREAD

**Issue by realbart** [Microsoft/TypeScript#2391]
Some time ago Visual Studio started to exclude the generated .js and .map from projects by default. The update was far from gracefull, but we finally managed to update the different branches in source control.

However, since these files were excluded from projects, debug functionality for typescript (setting breakpoints and stepping through) stopped functioning. We assumed a fix would be released shortly, so we are currently managing by temporary including the files to our projects and exluding them again when checking in. Not an ideal situation.

Is this problem known? I couldn't find an existing bug.

**Comment by danquirk** [comment]
Is this #297? (see also #2286)

**Comment by realbart** [comment]
@danquirk @mhegazy  Sorry for responding so late. I glanced over your reply too quickly and did not realize action on my part was required.

This is not the same issue. 

If I debug on IIS Express, TypeScript debugging works as expected, whether I include the JavaScript or not. On local IIS everything also works, until I also enable security:

    <authentication>
        <anonymousAuthentication enabled="false" />
        <windowsAuthentication useKernelMode="false">
          <extendedProtection tokenChecking="None" />
          <providers>
            <clear />
            <add value="Negotiate:Kerberos" />
          </providers>
        </windowsAuthentication>
      </authentication>

As soon as I enable this TypeScript breakpoints stop responding. Bizarly, as soon as I also include the js and the map in my project, everything works again.

We need this setting. We're currently maintaining about 200 intranet applications using this setting. Disabling it locally leads to other problems going unnoticed later on.

---

About the issue you linked:
many people have opinions on whether the compiled js-files should be included into the solution. I do not, although it was a problem when we suddenly had to remove them from all of our projects when we upgraded our build server.
Ideally, the build server should not care. If the file is included, the included file is used. Otherwise, the ts is compiled. Unless the server is explicitly configured to always compile.
A bigger problem is different typescript version. If you trust the build server to compile the typescript, you should also be able to explicitly specify which compiler to use, just like you specifically specify what .net-ramework you target.

**Comment by danquirk** [comment]
Thanks for the follow up, we can dig in further.

**Comment by mhegazy** [comment]
The TypeScript debugger plugin does not work with authentication. the reason is it would need to understand all the different authentication models. The solution is to use --mapRoot to specify a different location (a local file path on the build machine) for the debugger to locate the map files, instead of asking the server about them.

**Comment by realbart** [comment]
Thanks, @mhegazy . I've been googling, but I couldn't find much info on the --maproot parameter. Could you please point me in the right direction for finding resources on how to configure this in Visual Studio?

Furthermore, I'm curious on why it DOES work if I include the js and map file in the solution. Do you know the technical reason behind that?

**Comment by mhegazy** [comment]
to set the --mapRoot, use your project property pages, and mark "specify root directory of source maps". note that this is a URL, so use file:/// for local path, or http:// for web servers.

![propertypages](https://cloud.githubusercontent.com/assets/8000722/6986566/3ebba5c0-d9f3-11e4-81d3-985e046c72f6.PNG)

What this does, is simply put it in the url in your js file.
![file](https://cloud.githubusercontent.com/assets/8000722/6986592/7d63ba92-d9f3-11e4-924a-51f37a6c6e28.PNG)
This tells the debugger to get get it from that location.

Note that this *does not* copy the .map files to that location, it just puts the location in the .js file. so you will need a publish step to copy them to that location.
