### ISSUE TITLE
Nested mapped types are inferred to be any

### ISSUE THREAD

**Issue by steffenvv** [Microsoft/TypeScript#23918]
I'm trying to have the compiler infer the type of a deeply nested object, while transforming the type with a mapped type at every level of nesting. But the inferred type seems to be resolved to any at a certain depth.

**TypeScript Version:**  2.9.0-dev.20180503

**Search Terms:** 

Infer
Nested
Mapped type
Any

**Code**

```ts
export interface Mapper<T> {
    map(value: T): T;
}

export type Mappers<T> = { [K in keyof T]: Mapper<T[K]> };

declare const stringMapper: Mapper<string>;

declare function combineMappers<T>(mappers: Mappers<T>): Mapper<T>;

export const t1 = combineMappers({
    a: stringMapper,
    b: stringMapper
});

export const t2 = combineMappers({
    c: t1
});

export type T1 = ReturnType<typeof t1.map>;
/* T1 = { a: string; b: string }
   
   as desired */

export type T2 = ReturnType<typeof t2.map>;
/* T2 = { c: { a: any; b: any } }
   
   but I would like it to be

        { c: { a: string; b: string } } */

export type T3 = { [K in keyof T2]: T2[K] };
/* T3 = { c: { a: string; b: string } }
   
   according to VS code tooltip, but in the corresponding
   tooltip in the .d.ts output, it still says any */
```

**Expected behavior:**

I want the compiler to be able to infer a deeply nested mapped type. 

**Actual behavior:**

The inferred type seems to be resolved to any at a certain depth. Sometimes, the VS code tooltips gives the correct type while the emitted .d.ts file does not.

**Playground Link:** [link](https://www.typescriptlang.org/play/index.html#src=export%20interface%20Mapper%3CT%3E%20%7B%0D%0A%20%20%20%20map(value%3A%20T)%3A%20T%3B%0D%0A%7D%0D%0A%0D%0Aexport%20type%20Mappers%3CT%3E%20%3D%20%7B%20%5BK%20in%20keyof%20T%5D%3A%20Mapper%3CT%5BK%5D%3E%20%7D%3B%0D%0A%0D%0Adeclare%20const%20stringMapper%3A%20Mapper%3Cstring%3E%3B%0D%0A%0D%0Adeclare%20function%20combineMappers%3CT%3E(mappers%3A%20Mappers%3CT%3E)%3A%20Mapper%3CT%3E%3B%0D%0A%0D%0Aexport%20const%20t1%20%3D%20combineMappers(%7B%0D%0A%20%20%20%20a%3A%20stringMapper%2C%0D%0A%20%20%20%20b%3A%20stringMapper%0D%0A%7D)%3B%0D%0A%0D%0Aexport%20const%20t2%20%3D%20combineMappers(%7B%0D%0A%20%20%20%20c%3A%20t1%0D%0A%7D)%3B%0D%0A%0D%0Aexport%20type%20T1%20%3D%20ReturnType%3Ctypeof%20t1.map%3E%3B%0D%0A%2F*%20T1%20%3D%20%7B%20a%3A%20string%3B%20b%3A%20string%20%7D%0D%0A%20%20%20%0D%0A%20%20%20as%20desired%20*%2F%0D%0A%0D%0Aexport%20type%20T2%20%3D%20ReturnType%3Ctypeof%20t2.map%3E%3B%0D%0A%2F*%20T2%20%3D%20%7B%20c%3A%20%7B%20a%3A%20any%3B%20b%3A%20any%20%7D%20%7D%0D%0A%20%20%20%0D%0A%20%20%20but%20I%20would%20like%20it%20to%20be%0D%0A%0D%0A%20%20%20%20%20%20%20%20%7B%20c%3A%20%7B%20a%3A%20string%3B%20b%3A%20string%20%7D%20%7D%20*%2F%0D%0A%0D%0Aexport%20type%20T3%20%3D%20%7B%20%5BK%20in%20keyof%20T2%5D%3A%20T2%5BK%5D%20%7D%3B%0D%0A%2F*%20T3%20%3D%20%7B%20c%3A%20%7B%20a%3A%20string%3B%20b%3A%20string%20%7D%20%7D%0D%0A%20%20%20%0D%0A%20%20%20according%20to%20VS%20code%20tooltip%2C%20but%20in%20the%20corresponding%0D%0A%20%20%20tooltip%20in%20the%20.d.ts%20output%2C%20it%20still%20says%20any%20*%2F%0D%0A)

**Related Issues:** Possibly #22715

**Comment by ahejlsberg** [comment]
The compiler is actually inferring the right type, but when producing the text representation of the type (e.g. for tool tips or declaration file emit) it stops after observing multiple levels of nesting of the same type in order to avoid what might be an infinitely nested type. It is a known design limitation. See also #23433.

**Comment by steffenvv** [comment]
I see! Thank you for the quick and enlightening response!

Do you have any ideas for workarounds to achieve the desired .d.ts output? In my real application I would really like to be able to export these types across package boundaries.

Would it be possible to work around the issue by adding some "uniqueness" at each level? What exactly triggers the suspicion that the type is infinitely recursive? Is it sufficient to encounter any parametrization of Mapper in the above example, or would it help to add another type parameter that's different at each level? (Not really sure how to achieve that, in any case...)

Alternatively, can we improve the type-to-text algorithm to "tolerate" potential recursion until it reaches a certain maximum depth? If you point me at the relevant code, I would be very willing to give it a shot.

**Comment by steffenvv** [comment]
Another thought/question. If the compiler succeeds in inferring a type from an initializer, will it then be definitely possible to display the type without endless recursion? If so, could we add a flag to the type to remember that it's safe to display? Or does "possible to infer" not imply "possible to display"? I feel like I might be missing some distinction here.

**Comment by AlexGalays** [comment]
Is there a workaround to help the text representation be useful then?
