### ISSUE TITLE
public methods node.getChildren or node.getChildCount throw exception on certain node types

### ISSUE THREAD

**Issue by cancerberoSgx** [Microsoft/TypeScript#23917]
**TypeScript Version:**  2.9.0-dev.201xxxxx

Tested with typescript@next

Searched for **getChildren** and **getChildCount**

**Code**

See 
[tsissue3.zip](https://github.com/Microsoft/TypeScript/files/1976600/tsissue3.zip).
 
(Impossible to do it in a snippet since I need to read a file with `ts.createProgram`)

The code for compiling a ts file was taken mostly from https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API)

**Expected behavior:**
executing the following commands should not throw error
```sh
npm i
node node_modules/typescript/bin/tsc 
node dist/issue1.js
```
(same using ts-node)

**Actual behavior:**
it throw exception when I call node.getChildren() and node is the class declaration : 

```sh
/home/sg/sources/typescript-parse-test1/tests/tsissue1/node_modules/typescript/lib/typescript.js:104147
        ts.scanner.setText((sourceFile || node.getSourceFile()).text);
```

Notes: 
as you can see in tsissue1.ts visiting children with `forEachChild`
 works fine but using `getChildren` or using  `getChildCount` and `getChildAt` throws exceptions. 
These three methods are public (in typescript.d.ts) so I expect that this simple example don't fail. Otherwise these shouldn't be public, or it should be documented under which conditions they should be called.

**Comment by cancerberoSgx** [comment]
Ignore this issue and close it, I was incorrectly creating the compilerHost, Sorry to bother you. 

This works: 
```ts

export function parse(sourcefile: string): ts.SourceFile | undefined {
  const tsConfigJson = ts.parseConfigFileTextToJson('./tsconfig.json', readFileSync('./tsconfig.json').toString())
  if(tsConfigJson.error){
    throw tsConfigJson.error
  }
  let {options, errors} = ts.convertCompilerOptionsFromJson(tsConfigJson.config.compilerOptions, '.')
  if(errors.length){
    throw errors
  }
  const compilerHost:ts.CompilerHost = {
    ...ts.createCompilerHost(options), 
    getSourceFile: (fileName, languageVersion)=>ts.createSourceFile(fileName, readFileSync(fileName).toString(), ts.ScriptTarget.Latest, true)
  }
  return ts.createProgram([sourcefile], options, compilerHost).getSourceFile(sourcefile);
}
```

**Comment by mhegazy** [comment]
@andy-ms can you take a look

**Comment by andy-ms** [comment]
The problem is that `ts.createProgram(...).getSourceFile()` doesn't bind parents by default. It's been that way since at least ts2.0. When you call `getChildCount()` without passing in a source file, we need to climb parents to get to it, but parents haven't been set.

The following works:
```ts
function visitNotWorking(sourceFile: SourceFile, visitor: (node:ts.Node)=>void) {
  visit(sourceFile);
  function visit(node: ts.Node) {
    visitor(node);
    for (const child of node.getChildren(sourceFile)) {
      visit(child);
    }
  }
}
```

By the way, `getChildCount()` and `getChildAt()` are a very silly API, all they do is `getChildren()` and read the array for you. Also, `getChildren()` scans for token nodes, while `forEachChild` only includes the nodes that have already been parsed, which excludes tokens.

**Comment by cancerberoSgx** [comment]
Thanks! This was really what I needed to know, if it is for me you can close this issue. 

I wonder if an  contribute with some jsdocs so this information is available to API consumers ? I noticed that AST jsdoc is kind of poor but there is lots of info that describe these kind of things that IMO could be very useful for consumers to understand this kind . Unfortunately this comments are not jsdoc and are not exposed in d.ts . I'm toking about comments that ni general describe what a method or enum does and not particularly describe any internal detail. Do you think if I contribute a PR in this project with toms jsdocs like these could be accepted ? Or do you have other plans ? Or are these APIs not mature enough to start defining these contracts yet ? Thanks again!

**Comment by andy-ms** [comment]
A PR would probably be accepted. We might also consider making `sourceFile` non-optional since it hurts performance to forget it, but that would be a breaking change.

**Comment by cancerberoSgx** [comment]
Thanks will do for things that IMO are hard to grasp and have no jsdocs. Thanks again!

**Comment by cancerberoSgx** [comment]
Hello Andy, I'm writing some JsDocs for Node and the question is: do the same apply to other Node methods that accept SourceFile as first parameter ? The question is regarding what you said about performance :

> consider making sourceFile non-optional since it hurts performance to forget it,

Other nodes methods that accept a SourceFile as first param are  getStart, getEnd, getWidth, getLeadingTriviaWidth, getText, getFullText, getFirstToken, etc ? ) Looking at the impl I guess so but since is reference jsdoc I would like to be sure. ) 

Also, perhaps more important, do you think this implementation detail should be documented ? 

Thanks

**Comment by andy-ms** [comment]
Yeah, any time something accepts a SourceFile optional parameter, it should probably be provided (unless you would have just written `node.getStart(node.getSourceFile())` which is equivalent to `node.getStart()`). IMO a comment that applies to that many methods should be put at the top rather than on each individual method.

**Comment by cancerberoSgx** [comment]
I still have a doubt though (sorry to bother but I think this must be very clear and is important)

>  Also, getChildren() scans for token nodes, while forEachChild only includes the nodes that have already been parsed, which excludes tokens.

My doubt is with the "have already been parsed". I think that alone is not enough for the apidocs. Doesn't matter if the document is 100% parsed, both method have different semantics.

Can I just say something like 

"getChildren() returns all children nodes, including tokens like braces, parenthesis, etc, while forEachChild will only visit children nodes that are relevant to the AST will only scans for token nodes, while forEachChild only includes the nodes that have already been parsed, which excludes tokens.
"getChland with the consistency with node.parent. I know how the behavior is now but I'm not 100% how to document it. Take for example the following:

```
  print('sourceFile.getChildren: \n')
  sourceFile.getChildren(sourceFile).forEach(c=>print(getKindName(c)+', '))
  print('\n\nsourceFile.forEachChild: \n'); 
  sourceFile.forEachChild((c)=>print(getKindName(c)+', '))
```

the output is: 

```
sourceFile.getChildren: 
SyntaxList, 
EndOfFileToken, 

sourceFile.forEachChild: 
ImportDeclaration, 
FunctionDeclaration, 
ClassDeclaration, 
```

as you can see I have one extra parent-ship level with getChildren (the SyntaxList). Also the prhase "have already been parsed" doesn't seems to apply here. Is not that some children are ignored, the semantic is different. 

Is this situation analog to what happen with trivia tokens regarding of distance between tokens in the text, but this time regarding parentship distance between tokens ? Can I say in the documentation something like "forEachChild will only include children getChildren will return 

I've noticed the same with other tokens like CloseBraceToken and with those I don't have problem since they doesnt add much information to the AST or don't have important impact, but in the case of the SyntaxListis differen, because, If I want to add 
property with thand with the fact that is not only simple "tokens" like "brackes" or "parens" but in particular forEachChild is always ignoring
