### ISSUE TITLE
tsserver shows 'No such file or directory' error for npm path

### ISSUE THREAD

**Issue by rhysd** [microsoft/TypeScript#23924]
**TypeScript Version:**  2.8.3

**Search Terms:** `npm "No such file or directory"`

**Code**

Run following command from terminal:

```sh
$ tsserver
```

**Expected behavior:**

`tsserver` starts without any errors or warnings.

**Actual behavior:**

Following error is shown in stderr:

```
/bin/sh: /usr/local/Cellar/node/9.4.0/bin/npm: No such file or directory
```

**Playground Link:** N/A

**Related Issues:** None

This is a problem related to detecting default `npm` path in `tsserver`. At least Node v9.4.0 does not install `npm` to the same directory as `node` command. It is installed in `/usr/local/lib/node_modules/npm` like other normal npm packages.

**Comment by fuzunspm** [comment]
same issue on my end, it tries to find npm in `[tsserver] /bin/sh: /opt/local/bin/npm: No such file or directory` but it's in `/usr/local/bin/npm`

**Comment by GwynethLlewelyn** [comment]
@rhysd from your error, I guess that you're using [HomeBrew](https://brew.sh/) on macOS.

In my case, I fixed things by simply symlinking `npm` inside `/usr/local/Cellar/node/X.Y.Z/bin/`, e.g.

`ln -s /usr/local/bin/npm /usr/local/Cellar/node/X.Y.Z/bin/npm`

If you do that, will it work for you?

**Comment by rhysd** [comment]
It should work. But making users to make symlink in system directories is not solution for this fix, I think.

**Comment by rhysd** [comment]
Better workaround is using `--npmLocation` argument. For example:

```
./node_modules/.bin/tsserver --npmLocation /usr/local/opt/node/libexec/bin/npm
```

This does not require to modify your package directories.

**Comment by GwynethLlewelyn** [comment]
@rhysd, sounds good to me! However, I have a question: `tsserver` is actually invoked directly by this extension, and there is no way of changing that. Is there a way to create a [tsconfig.json](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html) file with the `npmLocation`?

**Comment by rhysd** [comment]
AFAIK there is field in tsconfig.json. I think adding functionality to append command line options on starting tsserver to the extension would be solution.

**Comment by RyanCavanaugh** [comment]
If you have a nonstandard npm location you'll have to set the "npm location" user preference accordingly
