### ISSUE TITLE
`OneOf` type for interface without discriminators

### ISSUE THREAD

**Issue by realyze** [Microsoft/TypeScript#23928]
I have the following type
```
type OneOf<T, U> = { [P in keyof T]?: never } & U | { [P in keyof U]?: never } & T;
```

The idea is that I could use it when I have an interface that can have one combination of props or the other (e.g. `size: number` vs `horizontalSize: number; verticalSize: number`).

Now, I would think
```
const getSize = (props: Props) => typeof props.size === 'undefined` ? props.horizontalSize : props.size;
```
Would have type `number` but it actually has `number | undefined`.

Should TypeScript be able to determine that the other "branch" should be used (i.e., `size` is missing ergo `horizontalSize` must be defined)?

**Comment by mhegazy** [comment]
Not sure this type is what you want then. Looks like the type you are looking for is `{ size: number } | { horizontalSize: number; verticalSize: number; }`.

Since the union does not have a discriminant (i.e. a common property with a unit type that is different in each constituent), the only way to narrow it is using `in` operator:

```ts
declare var foo: { size: number } | { horizontalSize: number; verticalSize: number; };

"size" in foo ? foo.size : foo.horizontalSize;
```

**Comment by mhegazy** [comment]
You might have better luck sharing this on StackOverflow. This is not a support forum, it is one for reporting compiler/language bugs and suggestions. 
If you believe you are running into a compiler bug, please share a minimal repro project that demonstrates the issue you are running into and why you believe this is a compiler bug and not a declaration file issue or library usage problem.

**Comment by realyze** [comment]
@mhegazy Thanks for the tip! I didn't want to word the ticket as a bug because I wasn't sure whether that was expected TS behaviour or not; it definitely surprised me.

Using `in` works as a charm so I'll close this. Thanks again.

**Comment by realyze** [comment]
Actually, apologies for another ping, @mhegazy, but there _is_ a Typescript bug in here I think which surfaces when I use the `in` syntax:

```
type Foo = {
  size: number
} | {
  horizontalSize: number;
  verticalSize: number;
};

const bar: Foo = {
  size: 42,
  horizontalSize: 43,
  verticalSize: 44,
};
```

In the above I would think `bar` should report an error as `Foo` is not be allowed to have all three props defined. But it actually compiles fine.
