### ISSUE TITLE
Definition of Array.prototype.filter forces three variables as parameters

### ISSUE THREAD

**Issue by viniciusx** [Microsoft/TypeScript#2392]
This is the current definition in lib.d.ts: 
```typescript
filter(callbackfn: (value: T, index: number, array: T[]) => boolean, thisArg?: any): T[];
```
note that there is no optional parameters and in the JavaScript version of this function we are able to pass ONLY the current element to the callback.
so the definition should be:
```typescript
filter(callbackfn: (value: T, index?: number, array?: T[]) => boolean, thisArg?: any): T[];
```

That way, we'd be able to call this function just like we would in JavaScript: 
```javascript
[].filter(.....)
```

**Comment by RyanCavanaugh** [comment]
I encourage you to actually try this, as it does work without error. Functions with fewer parameters are assignable to functions with more parameters (as long as the types match) for exactly this reason.

```ts
var x = [1, 2];
var y = x.filter(a => a == 1); // No error
```

**Comment by viniciusx** [comment]
Nice, i didn't know this was a thing.
It's a nice alternative. Thanks!
