### ISSUE TITLE
Parameters not being enforced properly

### ISSUE THREAD

**Issue by jpike88** [Microsoft/TypeScript#23929]
**TypeScript Version:**  2.8.1

**Search Terms:** this rest parameters

**Code**

```ts

interface ApiMethods {
    [s: string]: ApiMethod;
}

type ApiMethod = {
    (this:ApiHandler, ...args: any[]): Promise<void>;
}

export default <ApiMethods>{
	thisMethodShouldBeOK,
        thisMethodShouldNotBeOK
}

async function thisMethodShouldBeOK(this:ApiHandler, query:string) {
}

async function thisMethodShouldNotBeOK(query:string) {
}


```

**Expected behavior:**

thisMethodShouldNotBeOK should be showing as an error, because it doesn't specify a type for this as the first parameter.

**Actual behavior:**

thisMethodShouldNotBeOK should be firing an error on compile, but it's not.

the 'this:ApiHander' parameter in the ApiMethod type is not being enforced properly.

**Comment by jpike88** [comment]
Is there a better pattern to achieve what I'm going for? What I'm trying to avoid is the polluting of parameters with some sort of 'context' parameter, 'this' acts as a context that will meet a certain structure in all async functions that conform to the ApiMethod interface.

**Comment by andy-ms** [comment]
> What I'm trying to avoid is the polluting of parameters with some sort of 'context' parameter

TypeScript will enforce that you provide `this` when it's required, but it doesn't enforce that it's *not* provided when you don't look at it.
This is analagous to a function taking `{ x: number }` not being guaranteed that the object won't have a `y` property.

**Comment by andy-ms** [comment]
To clarify, what you want to enforce is that all of the methods in `export default`  *must* take a `this` parameter, even if they don't need it?

**Comment by jpike88** [comment]
correct, they all must have this:ApiHandler present because ```this.callback(isError:boolean, payload:any)``` is always present, and fires an API response.

**Comment by andy-ms** [comment]
Well, I don't think there's a way to do that then. You can't enforce that a method must declare a parameter it doesn't use.

**Comment by andy-ms** [comment]
Don't know what to tell you -- there's no way to enforce that. `() => void` is a subtype of `(this: number) => void`, and you can't turn off subtyping (#12936).
