### ISSUE TITLE
Opposite type inference behavior on static type param vs class type param

### ISSUE THREAD

**Issue by shivawu** [Microsoft/TypeScript#23926]
**TypeScript Version:**  2.9.0-dev.20180506

**Search Terms:** conditional types, variance

**Code**

```ts
class Component<P, S> {
  props!: P;
  state!: S;
}

class Component1 extends Component<{ a: number }, {}> {}
class Component2 extends Component<{}, {}> {}

type Ctor<P, S> = {
  new (p: P): Component<P, S>;
};

interface Pass {
  itPasses: any;
}

interface Fail {
  itFails: any;
}

type Checked<N extends string, P, C> = Record<N, P> extends C ? Pass : Fail;

class AppRegistry<Comps> {
  static make(): AppRegistry<never> {
    return new AppRegistry();
  }

  views: Map<string, Ctor<any, any>> = new Map();

  private constructor() {}

  register<N extends string, P, S>(
    name: N,
    c: Ctor<P, S>,
  ): AppRegistry<Comps | Record<N, P>> {
    this.views.set(name, c);
    return this;
  }

  run<
    N extends string,
    P,
    R extends AppRegistry<Comps>,
    T extends Checked<N, P, Comps>
  >(this: R, name: N, props: P): T {
    console.error(name, props);
    return this as any;
  }
}

class AppRegistryStatic {
  static make(): never {
    return {} as never;
  }

  static register<R, N extends string, P, S>(
    r: R,
    name: N,
    c: Ctor<P, S>,
  ): R | Record<N, P> {
    console.warn(r, name, c);
    return r;
  }

  static run<N extends string, P, R, T extends Checked<N, P, R>>(
    r: R,
    name: N,
    props: P,
  ): T {
    console.error(r, name, props);
    return r as any;
  }
}

function assertPass(x: Pass): never {
  throw new Error('Unexpected object: ' + x);
}

export async function test() {
//  This works
//   const rr = AppRegistryStatic.make();
//   const r1 = AppRegistryStatic.register(rr, 'a', Component1);
//   const r2 = AppRegistryStatic.register(r1, 'b', Component2);
//   const r = AppRegistryStatic.run(r2, 'a', { a: 1 });
//  This does not
  const rr = AppRegistry.make();
  const r1 = rr.register('a', Component1);
  const r2 = r1.register('b', Component2);
  const r = r2.run('a', { a: 1 });
  assertPass(r);
}
```

**Expected behavior:**

`AppRegistry` should behave the same as `AppRegistryStatic`

**Actual behavior:**

They behave the opposite. `AppRegistryStatic` would infer `r` as `Pass` while `AppRegistry` infer `r` as `Fail`.

I'm not sure if this is actually a bug. If not, I'd be happy to learn why. Gut feeling says this is related to variance of the type params.

**Playground Link:** [playground](https://www.typescriptlang.org/play/#src=class%20Component%3CP%2C%20S%3E%20%7B%0D%0A%20%20props!%3A%20P%3B%0D%0A%20%20state!%3A%20S%3B%0D%0A%7D%0D%0A%0D%0Aclass%20Component1%20extends%20Component%3C%7B%20a%3A%20number%20%7D%2C%20%7B%7D%3E%20%7B%7D%0D%0Aclass%20Component2%20extends%20Component%3C%7B%7D%2C%20%7B%7D%3E%20%7B%7D%0D%0A%0D%0Atype%20Ctor%3CP%2C%20S%3E%20%3D%20%7B%0D%0A%20%20new%20(p%3A%20P)%3A%20Component%3CP%2C%20S%3E%3B%0D%0A%7D%3B%0D%0A%0D%0Ainterface%20Pass%20%7B%0D%0A%20%20itPasses%3A%20any%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20Fail%20%7B%0D%0A%20%20itFails%3A%20any%3B%0D%0A%7D%0D%0A%0D%0Atype%20Checked%3CN%20extends%20string%2C%20P%2C%20C%3E%20%3D%20Record%3CN%2C%20P%3E%20extends%20C%20%3F%20Pass%20%3A%20Fail%3B%0D%0A%0D%0Aclass%20AppRegistry%3CComps%3E%20%7B%0D%0A%20%20static%20make()%3A%20AppRegistry%3Cnever%3E%20%7B%0D%0A%20%20%20%20return%20new%20AppRegistry()%3B%0D%0A%20%20%7D%0D%0A%0D%0A%20%20views%3A%20Map%3Cstring%2C%20Ctor%3Cany%2C%20any%3E%3E%20%3D%20new%20Map()%3B%0D%0A%0D%0A%20%20private%20constructor()%20%7B%7D%0D%0A%0D%0A%20%20register%3CN%20extends%20string%2C%20P%2C%20S%3E(%0D%0A%20%20%20%20name%3A%20N%2C%0D%0A%20%20%20%20c%3A%20Ctor%3CP%2C%20S%3E%2C%0D%0A%20%20)%3A%20AppRegistry%3CComps%20%7C%20Record%3CN%2C%20P%3E%3E%20%7B%0D%0A%20%20%20%20this.views.set(name%2C%20c)%3B%0D%0A%20%20%20%20return%20this%3B%0D%0A%20%20%7D%0D%0A%0D%0A%20%20run%3C%0D%0A%20%20%20%20N%20extends%20string%2C%0D%0A%20%20%20%20P%2C%0D%0A%20%20%20%20R%20extends%20AppRegistry%3CComps%3E%2C%0D%0A%20%20%20%20T%20extends%20Checked%3CN%2C%20P%2C%20Comps%3E%0D%0A%20%20%3E(this%3A%20R%2C%20name%3A%20N%2C%20props%3A%20P)%3A%20T%20%7B%0D%0A%20%20%20%20console.error(name%2C%20props)%3B%0D%0A%20%20%20%20return%20this%20as%20any%3B%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Aclass%20AppRegistryStatic%20%7B%0D%0A%20%20static%20make()%3A%20never%20%7B%0D%0A%20%20%20%20return%20%7B%7D%20as%20never%3B%0D%0A%20%20%7D%0D%0A%0D%0A%20%20static%20register%3CR%2C%20N%20extends%20string%2C%20P%2C%20S%3E(%0D%0A%20%20%20%20r%3A%20R%2C%0D%0A%20%20%20%20name%3A%20N%2C%0D%0A%20%20%20%20c%3A%20Ctor%3CP%2C%20S%3E%2C%0D%0A%20%20)%3A%20R%20%7C%20Record%3CN%2C%20P%3E%20%7B%0D%0A%20%20%20%20console.warn(r%2C%20name%2C%20c)%3B%0D%0A%20%20%20%20return%20r%3B%0D%0A%20%20%7D%0D%0A%0D%0A%20%20static%20run%3CN%20extends%20string%2C%20P%2C%20R%2C%20T%20extends%20Checked%3CN%2C%20P%2C%20R%3E%3E(%0D%0A%20%20%20%20r%3A%20R%2C%0D%0A%20%20%20%20name%3A%20N%2C%0D%0A%20%20%20%20props%3A%20P%2C%0D%0A%20%20)%3A%20T%20%7B%0D%0A%20%20%20%20console.error(r%2C%20name%2C%20props)%3B%0D%0A%20%20%20%20return%20r%20as%20any%3B%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Afunction%20assertPass(x%3A%20Pass)%3A%20never%20%7B%0D%0A%20%20throw%20new%20Error('Unexpected%20object%3A%20'%20%2B%20x)%3B%0D%0A%7D%0D%0A%0D%0Aexport%20async%20function%20test()%20%7B%0D%0A%2F%2F%20%20%20const%20rr%20%3D%20AppRegistryStatic.make()%3B%0D%0A%2F%2F%20%20%20const%20r1%20%3D%20AppRegistryStatic.register(rr%2C%20'a'%2C%20Component1)%3B%0D%0A%2F%2F%20%20%20const%20r2%20%3D%20AppRegistryStatic.register(r1%2C%20'b'%2C%20Component2)%3B%0D%0A%2F%2F%20%20%20const%20r%20%3D%20AppRegistryStatic.run(r2%2C%20'a'%2C%20%7B%20a%3A%201%20%7D)%3B%0D%0A%20%20const%20rr%20%3D%20AppRegistry.make()%3B%0D%0A%20%20const%20r1%20%3D%20rr.register('a'%2C%20Component1)%3B%0D%0A%20%20const%20r2%20%3D%20r1.register('b'%2C%20Component2)%3B%0D%0A%20%20const%20r%20%3D%20r2.run('b'%2C%20%7B%7D)%3B%0D%0A%20%20assertPass(r)%3B%0D%0A%7D%0D%0A)

**Related Issues:**

**Comment by shivawu** [comment]
It's a long piece of code, I'll explain a bit more context.

I'm trying to write an AppRegistry class which the user would be able to register multiple React components with the props type with a name. When they **run** that component from the registry, the typechecker would help checking if the props type are correct.

In the example, if we run component `'a'` with `{ a: "a string" }`, it would fail typechecking.

The idea of mine is by leveraging union type. We construct a type like `R = { name1: Props1 } | { name2: Props2 }`. When we call `run`, we have to assert that the passed N (name) and P (props) align with `Record<N, P> extends R`. 

I haven't really found a way to add constraint to compound type parameters like a where clause, so I went with conditional types, which is
```
type Checked<N extends string, P, C> = Record<N, P> extends C ? Pass : Fail;
```

This would give an `Fail` (or `never`) when the condition is not met. It's not ideal in the sense that unless tsc have a way to assert a value is never `never`, we'll have to do things like `assertPass`.

I'd also like to learn if there's any better way, if appropriate, since I'm pretty new to TS. Thanks!

**Comment by gcanti** [comment]
> The idea of mine is by leveraging union type

You may want intersections instead.

I also added two nice features (statically checked)

- you can't register the same name twice
- you can't run an unknown name

```ts
class Component<P, S> {
  props!: P
  state!: S
}

type Ctor<P, S> = {
  new (p: P): Component<P, S>
}

type Components = { [key: string]: Ctor<any, any> }

type PropsOf<C extends Ctor<any, any>> = InstanceType<C>['props']

type NewCtor<N, M> = N extends keyof M ? never : Ctor<any, any>

class AppRegistry<M extends Components> {
  static make(): AppRegistry<{}> {
    return new AppRegistry()
  }
  private views: Map<string, Ctor<any, any>> = new Map()
  private constructor() {}
  register<N extends string, C extends NewCtor<N, M>>(name: N, c: C): AppRegistry<M & { [K in N]: C }> {
    this.views.set(name, c)
    return this as any
  }
  run<N extends keyof M, P extends PropsOf<M[N]>>(name: N, props: P): M[N] {
    return this.views.get(name) as any
  }
}

//
// usage
//

class Component1 extends Component<{ a: number }, {}> {}
class Component2 extends Component<{ b: string }, {}> {}

const r0 = AppRegistry.make()
const r1 = r0.register('a', Component1)
const r2 = r1.register('b', Component2)
r2.register('a', Component2) // static error, can't register a name twice

const x = r2.run('a', { a: 1 }) // ok
r2.run('a', { a: 'foo' }) // static error, wrong props
r2.run('c', { a: 'foo' }) // static error, unknown name
```

**Comment by shivawu** [comment]
@gcanti Thanks for replying! It's an awesome trick! 

I've actually considered using intersection types. The benefit is obvious, it reverses the constraint so that it can be naturally expressed in TS `R extends Record<N, P>`. The downside is that the internal logic is a bit weird, because it's unclear to me what `{ a: Pa } & { b: Pb }` mean... Maybe I'm confused :)

BTW, I believe the original approach also handles unknown name, since `{ c: P }` does not extend `{ a: P(a) } | { b: P(b) }`.

Despite of the approach, I think it's still interesting why `AppRegistry` and `AppRegistryStatic` behave differently, which definitely sounds fishy to me.

**Comment by RyanCavanaugh** [comment]
@shivawu we look at these things pretty heuristically because there are are a lot of incoming issues - if someone is new to TS and posts an entire screenful of code, 95% of the time it's a misunderstanding on their part. The issue tracker is for bugs; if you can reduce this to a small example that clearly demonstrates why it's a bug we will investigate, otherwise we do not have resources to explain the behavior of large code samples
