### ISSUE TITLE
auto import cleanup doesn't get triggered in open but not active tabs in VS code when i do save all

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#23932]
i do save all and cleanup only happens in the active tab/file

**Comment by mhegazy** [comment]
That is a VSCode feature. they call the organize imports on save. the server does not monitor save events. I would file this under https://github.com/Microsoft/vscode/issues instead.

**Comment by aleksey-bykov** [comment]
ok
