### ISSUE TITLE
Does not narrow variable type when checking "in" enum

### ISSUE THREAD

**Issue by samijaber** [Microsoft/TypeScript#23937]
**TypeScript Version:**  2.8.3

**Search Terms:** 
enum, "in", string equivalence, type narrowing

**Code**
```ts
enum SomeEnum {
    a = 'a',
    b = 'b',
    c = 'c'
};


const fn = (str: string) => {
    if (str in SomeEnum) {
        const enumVal = str;
    }
} 
```

**Expected behavior:**
`enumVal` to have type `SomeEnum`

**Actual behavior:**
`enumVal` has type `string`

**Playground Link:** https://www.typescriptlang.org/play/index.html#src=enum%20SomeEnum%20%7B%0D%0A%20%20%20%20a%20%3D%20'a'%2C%0D%0A%20%20%20%20b%20%3D%20'b'%2C%0D%0A%20%20%20%20c%20%3D%20'c'%0D%0A%7D%3B%0D%0A%0D%0A%0D%0Aconst%20fn%20%3D%20(str%3A%20string)%20%3D%3E%20%7B%0D%0A%20%20%20%20if%20(str%20in%20SomeEnum)%20%7B%0D%0A%20%20%20%20%20%20%20%20const%20enumVal%20%3D%20str%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%20

**Comment by RyanCavanaugh** [comment]
`in` tests the *keys* of an object but the type of an enum is formed from its `values`. String enums intentionally don't act differently depending on the values of their members, so the fact that `a` maps to `"a"` is not relevant here.

**Comment by samijaber** [comment]
Ah! You're right. A mistake on my part. 👍
