### ISSUE TITLE
TypeScript auto format indent error

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#23934]
_From @k8w on May 7, 2018 6:40_

- VSCode Version: 1.23.0-insiders
- OS Version: Win10

**Expect indent**
```ts
test({
    a: 1,
    b: 2
}, {
    a: 1,
    b: 2
});
```

**Actual indent** (after auto format):
```ts
test({
    a: 1,
    b: 2
}, {
        a: 1,
        b: 2
    });
```

_Copied from original issue: Microsoft/vscode#49337_

**Comment by mjbvz** [comment]
Similar looking to #19167. Not sure if this has the same root cause or not

**Comment by aleksey-bykov** [comment]
similar to https://github.com/Microsoft/TypeScript/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+format
