### ISSUE TITLE
import auto cleanup is too agressive to rexports

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#23930]
this
```
import { crash, crashOver, failWithAbstract, failWithArgumentNull, failWithNotImplemented, never, unexpectedKind, unexpected, crashBecause } from 'essentials/failing';
export { crash, crashOver, failWithAbstract, failWithArgumentNull, failWithNotImplemented, never, unexpectedKind, unexpected };
```

turns to this

```
import { crash, crashBecause } from 'essentials/failing';
export { crash, crashOver, failWithAbstract, failWithArgumentNull, failWithNotImplemented, never, unexpectedKind, unexpected };
```

proof

![image](https://user-images.githubusercontent.com/937933/39710861-05ba6652-51ec-11e8-921c-9d81d1c53f20.png)

**Comment by mhegazy** [comment]
Can you share more context? Organize imports should not change `exports`, only `imports`.

**Comment by aleksey-bykov** [comment]
auto cleanup erases the identifiers mentioned in export
so i wish exports were taken into accound during cleanups

**Comment by mhegazy** [comment]
What version of TS are you using? this sounds like https://github.com/Microsoft/TypeScript/issues/23308, which should be fixed in `typescript@next`.

**Comment by aleksey-bykov** [comment]
looks like it's fixed, sorry
