### ISSUE TITLE
No completion for import name bindings for imported module 

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#23939]
**TypeScript Version:**  2.9.0-dev.201xxxxx

**Search Terms:** 

**Code**

```ts
// b.ts

export var a: number, b: number, c: number;
```

```ts
// a.ts
import {  | } from "./b";

```

**Expected behavior:**

Completion list has `a`, `b` and `c`.

**Actual behavior:**

Completion list is empty

**Playground Link:**  

**Related Issues:**

**Comment by andy-ms** [comment]
@mhegazy It's working for me?

**Comment by mhegazy** [comment]
sorry about that. looks like a vscode change.. i do not even see the call to getCompletions on insiders.. @mjbvz any idea why that is the case? `ctrl+space` does not seem to call getCompeltions from the server...

![screen](https://user-images.githubusercontent.com/8000722/39729324-203afc0c-5210-11e8-969a-7bd41fe71403.gif)

**Comment by mjbvz** [comment]
Yes there is a bug in todays insiders for completions. Will be fixed in the next build
