### ISSUE TITLE
Add missing import quick fix should show for interface used in 'extends'

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#23945]
From https://github.com/Microsoft/vscode/issues/49407#issuecomment-387211027

**TypeScript Version:**  2.9.0-dev.20180506

**Search Terms:** 
- add missing import
- quick fix / code action

**Code**
1. For the project:

`a.ts`

```ts
export interface IFoo { }
```

`b.ts`:

```ts
class Bar extends IFoo {}
```

1. in `b.ts`, see error about missing `IFoo`

**Expected behavior:**
Quick fix to import `IFoo` is available 

**Actual behavior:**
No such import available.

Root cause is that `b.ts` uses `extends` instead of `implements`. However it may be better if we show the missing import quick fix in this case, even through it will result in an error. Otherwise it looks like TS cannot find the symbol `IFoo` anywhere

**Playground Link:**  

**Related Issues:**

**Comment by andy-ms** [comment]
The error is because importFixes checks that the potential import matches the current meaning -- and `extends` expects a value while `IFoo` is purely a type. We might consider removing that restriction if getting some fix is better than nothing.

**Comment by mhegazy** [comment]
this looks like it is working as intended. we remove the types in value positions to limit noise, and i think this has been a good thing overall. in this case, this is an invalid use of the `extends` clause, so i would not consider this the norm.
