### ISSUE TITLE
Provide completions in indexed access without quotes

### ISSUE THREAD

**Issue by Kingwl** [microsoft/TypeScript#23958]
**TypeScript Version:**  2.9.0-dev.201xxxxx

**Search Terms:** 

**Code**

```ts
declare const a: [number, number]

a['/*a*/']

a[/*b*/]

a./*c*/
```

**Expected behavior:**
a: 0 or 1
b: 0 or 1
c: nothing

**Actual behavior:**
a: 0 or 1
b: nothing
c: 0 or 1

**Playground Link:**  

**Related Issues:**

**Comment by andy-ms** [comment]
Currently `a[ /**/ ]` is just another expression position, so you get all completions from the scope. So if you have `const x = 0;` in scope, you might want a completion so you can write `a[x]`. But maybe we should also add `0` and `1` completions and give them priority.

**Comment by Kingwl** [comment]
and that we not support `tuple.index` ~Although rust has this syntax~

**Comment by RyanCavanaugh** [comment]
This doesn't seem worth adding code for - if you know it's an array, all you have to do is write the (single-digit) index; if you don't know it's an array, `0` and `1` show up in the completion list in supported editors.
