### ISSUE TITLE
type error when function argv with default value

### ISSUE THREAD

**Issue by bluelovers** [Microsoft/TypeScript#23959]
**TypeScript Version:**  2.9.0-dev.201xxxxx

**Search Terms:** 

**Code**

type error when function argv with default value

```ts
export enum IName
{
	aaa = 1
}

export function f<T extends typeof IName>(input: T = IName)
{
	
}
```

**Expected behavior:**

no error

**Actual behavior:**

```ts
Error:(10, 43) TS2322: Type 'typeof IName' is not assignable to type 'T'.
```

**Playground Link:**  

**Related Issues:**

**Comment by andy-ms** [comment]
This is a legitimate error. `T extends typeof IName` declares that `T` must be assignable to `typeof IName`. That doesn't imply that `typeof IName` must be assignable to `T`. An example:

```ts
interface I { x: number };
interface J extends I { y: number; }

function getT<T extends I>(input: T = { x: 0 }): T {
    return input;
}

const x = getT<J>();
x.y.toFixed(); // Will fail at runtime
```

**Comment by bluelovers** [comment]
@andy-ms so how i can fixed this without use `@ts-ignore` ?

**Comment by andy-ms** [comment]
What are you trying to accomplish?

**Comment by bluelovers** [comment]
something like this

https://github.com/bluelovers/regexp-support/blob/b574b936dff1921fef35111e64182d8bd1af0dcb/lib/pattern.ts#L101

https://github.com/bluelovers/regexp-support/blob/b574b936dff1921fef35111e64182d8bd1af0dcb/lib/index.ts#L143-L160

**Comment by andy-ms** [comment]
Sorry, could you try and simpilfy that and explain what it's trying to accomplish in an independent example?
