### ISSUE TITLE
Dynamic type definitions inside template not resolved properly

### ISSUE THREAD

**Issue by viswansh** [Microsoft/TypeScript#23967]
**TypeScript Version:**  2.8.0

**Search Terms:** 
dynamic types, mapped types, template typedef, 

**Code**
// snippet1
// doesnt work
function foo<T, R, F = (x: T) => R>(x: T): F {
    let fn: F;
    fn = (x: T) => <R>(<any>!!x);
    return fn;
}

//works
type F1<T, R> = (x: T) => R ;
function bar<T, R>(x: T): F1<T,R> {
    let fn: F1<T,R>;
    fn = (x: T) => <R>(<any>!!x);
    return fn;
}

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**Expected behavior:**

No compilation errors on snippet1

**Actual behavior:**

Compilation error 

**Playground Link:**  
https://www.typescriptlang.org/play/#src=%0D%0A%0D%0Afunction%20foo%3CT%2C%20R%2C%20F%20extends%20%7B%20(x%3A%20T)%3A%20R%20%7D%3E(x%3A%20T)%3A%20F%20%7B%0D%0A%20%20%20%20let%20fn%3A%20F%3B%0D%0A%20%20%20%20fn%20%3D%20(x%3A%20T)%20%3D%3E%20%3CR%3E(%3Cany%3E!!x)%3B%0D%0A%20%20%20%20return%20fn%3B%0D%0A%7D%0D%0A%0D%0Atype%20F1%3CT%2C%20R%3E%20%3D%20(x%3A%20T)%20%3D%3E%20R%20%3B%0D%0Afunction%20bar%3CT%2C%20R%3E(x%3A%20T)%3A%20F1%3CT%2CR%3E%20%7B%0D%0A%20%20%20%20let%20fn%3A%20F1%3CT%2CR%3E%3B%0D%0A%20%20%20%20fn%20%3D%20(x%3A%20T)%20%3D%3E%20%3CR%3E(%3Cany%3E!!x)%3B%0D%0A%20%20%20%20return%20fn%3B%0D%0A%7D%0D%0A

**Related Issues:**

**Comment by nmain** [comment]
As intended.  `F` could have other things on it besides that one call signature.  Consider the following:

https://www.typescriptlang.org/play/#src=%0D%0A%0D%0Afunction%20foo%3CT%2C%20R%2C%20F%20extends%20%7B%20(x%3A%20T)%3A%20R%20%7D%3E(x%3A%20T)%3A%20F%20%7B%0D%0A%20%20%20%20let%20fn%3A%20F%3B%0D%0A%20%20%20%20fn%20%3D%20(x%3A%20T)%20%3D%3E%20%3CR%3E(%3Cany%3E!!x)%3B%0D%0A%20%20%20%20return%20fn%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20Bof%20%7B%0D%0A%20%20%20%20(x%3A%20number)%3A%20boolean%3B%0D%0A%20%20%20%20isBaz%3A%20true%3B%0D%0A%7D%0D%0A%0D%0Aconst%20bof%20%3D%20foo%3Cnumber%2C%20boolean%2C%20Bof%3E(5)%3B%0D%0Aconsole.log(bof.isBaz)%3B%20%2F%2F%20should%20print%20%60true%60.%20%20prints%20%60undefined%60

**Comment by viswansh** [comment]
Even in your code

**Comment by nmain** [comment]
That's a slightly different example, but it fails for the same reason (and more).  When you say `F = (x: T) => R`, you're just saying that the default value for the `F` template argument if not otherwise provided is `(x: T) => R`.  `F` could be specified to be anything at all:

```
foo<number, boolean, string>(3)
```

What should this return?

If you do `F extends (x: T) => R = (x: T) => R` you're back to the original case and your code is unsound as my first example demonstrates.

**Comment by viswansh** [comment]
makes sense. Thanks
