### ISSUE TITLE
Class property with literal implementing interface with literal type has type error

### ISSUE THREAD

**Issue by ajcrites** [Microsoft/TypeScript#23963]
**TypeScript Version:** 2.9.0-dev.20180506

**Search Terms:**  interface, literal

**Code**

```ts
interface Couple {
  age: 29 | 32;
  name: 'Andrew' | 'Nicole';
}

class Andrew implements Couple {
  age = 32
  name = 'Andrew';
}
```

**Expected behavior:**
This should compile without issues. Note that this does not happen with variables assignments. The following works fine:

```ts
let age: 42;
age = 42;
```

**Actual behavior:**
> `Property 'age' in type 'Andrew' is not assignable to the same property in base type 'Couple'.
  Type 'number' is not assignable to type '29 | 32'.`
> `Property 'name' in type 'Andrew' is not assignable to the same property in base type 'Couple'.
  Type 'string' is not assignable to type '"Andrew" | "Nicole"'`

This will happen if implementing an interface or extending a class. TypeScript seems to think that the assigned type is different than the literal type or it skips this check. You can fix this by being explicit with the class property type, `age: 32 = 32` for example.

**Related Issues:** #23718

**Comment by andy-ms** [comment]
Getting a contextual type from an interface might be something worth implementing (though a more important use would be to allow omitting method parameter types). Can't find if we already have an issue for that.

For now there are 2 workarounds:
* `readonly age = 32;` means that the property's type isn't widened, so there's no error.
* `age: Couple["age"] = 32` has an explicit type definition, so the type isn't widened.

**Comment by mhegazy** [comment]
Similar issue to https://github.com/Microsoft/TypeScript/issues/10570.

One other thing to note is that `implements` only means "check this declaration is assignable to"; the compiler does not do anything special when you have an implements clause, i.e. types are not inherited, nor are declarations.
