### ISSUE TITLE
JSDoc generic function infers literal types

### ISSUE THREAD

**Issue by ajafff** [Microsoft/TypeScript#23969]
**TypeScript Version:**  2.9.0-dev.20180506

**Search Terms:** type parameter literal

**Code**

```ts
// @strictNullChecks: true
// @allowJs: true

// a.js
/** @type {<T>(param?: T) => T} */
export var fn;

// b.ts
import {fn} from './a';
const v = fn(1);
```

**Expected behavior:**
`v` is `number`, because TypeParameter inference widens literal types. At least that's what happens if I declare the same function type in TypeScript.

**Actual behavior:**
`v` is `1`. The TypeParameter is inferred as literal type

**Playground Link:** not possible in playground

**Related Issues:** 
There are a lot of issues that actually wish for this behavior...

**Comment by mhegazy** [comment]
That is not different from the same pattern in a `.ts` file:

```ts
declare var fn: <T>(param?: T) => T;
fn(1);
```
If the return type is the type parameter it is not widened. think of the identity function, you would not expect it to widen.

**Comment by ajafff** [comment]
You are absolutely right. I didn't know about the special handling of type parameters used as return type.
