### ISSUE TITLE
Auto-formatting a function call with a lambda parameter truncates space before parameter

### ISSUE THREAD

**Issue by ThomasMichon** [Microsoft/TypeScript#2398]
When I write an expression which invokes a function that accepts a function as a parameter, and I use lambda syntax for the function parameter, VS eliminates the space after the comma and before the lambda expression when it performs an auto-format.

What should be this:

```typescript
function test<T>(list: T[], predicate: (value: T) => boolean) {
    ...
}

test([1, 2, 3], (x: number) => x > 2);
```

becomes this:

```typescript
function test<T>(list: T[], predicate: (value: T) => boolean) {
    ...
}

test([1, 2, 3],(x: number) => x > 2);
```

Using function () syntax does not cause a truncation of the space.
There does not appear to be a formatting options regarding spacing between parameters, let alone for using lambda syntax.

This appears to have been introduced with VS 2015 CTP 5, as opposed to VS 2015 preview which behaved as expected.

**Comment by vladima** [comment]
This is a known issue that was already fixed in the latest bits and should be available once 1.5 is released.
