### ISSUE TITLE
Type definition of Array.prototype.filter is not fully correct

### ISSUE THREAD

**Issue by yenshih** [Microsoft/TypeScript#23990]
**TypeScript Version:**  2.8.3

**Code**

```ts
interface Obj {
}
const obj: Obj = {};
const xs: boolean[] = [false, true, true];
const ys: Array<Obj | null> = [null, obj, obj];


function identity(): undefined;
function identity<T>(x: T): T
function identity(...args: any[]): any {
    if (args.length) {
        return args[0];
    }
}

/**
 * Or import {identity} from 'lodash/fp';
 * 
 * Type definition of LodashIdentity is
 * 
 * interface LodashIdentity {
 *     (): undefined;
 *     <T>(value: T): T;
 * }
 */

xs.filter(identity).map(x => x /* x is still boolean */);
ys.filter(identity).map(y => y /* y is still Obj | null */);

```

**Expected behavior:**

`x` is inferred as `true`.
`y` is inferred as `Obj`.

**Actual behavior:**

`x` is still `boolean`.
`y` is still `Obj | null`.

**Playground Link:** [Reproduce](https://www.typescriptlang.org/play/index.html#src=interface%20Obj%20%7B%0D%0A%7D%0D%0Aconst%20obj%3A%20Obj%20%3D%20%7B%7D%3B%0D%0Aconst%20xs%3A%20boolean%5B%5D%20%3D%20%5Bfalse%2C%20true%2C%20true%5D%3B%0D%0Aconst%20ys%3A%20Array%3CObj%20%7C%20null%3E%20%3D%20%5Bnull%2C%20obj%2C%20obj%5D%3B%0D%0A%0D%0A%0D%0Afunction%20identity()%3A%20undefined%3B%0D%0Afunction%20identity%3CT%3E(x%3A%20T)%3A%20T%0D%0Afunction%20identity(...args%3A%20any%5B%5D)%3A%20any%20%7B%0D%0A%20%20%20%20if%20(args.length)%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20args%5B0%5D%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0A%2F**%0D%0A%20*%20Or%20import%20%7Bidentity%7D%20from%20'lodash%2Ffp'%3B%0D%0A%20*%20%0D%0A%20*%20Type%20definition%20of%20LodashIdentity%20is%0D%0A%20*%20%0D%0A%20*%20interface%20LodashIdentity%20%7B%0D%0A%20*%20%20%20%20%20()%3A%20undefined%3B%0D%0A%20*%20%20%20%20%20%3CT%3E(value%3A%20T)%3A%20T%3B%0D%0A%20*%20%7D%0D%0A%20*%2F%0D%0A%0D%0Axs.filter(identity).map(x%20%3D%3E%20x%20%2F*%20x%20is%20still%20boolean%20*%2F)%3B%0D%0Ays.filter(identity).map(y%20%3D%3E%20y%20%2F*%20y%20is%20still%20Obj%20%7C%20null%20*%2F)%3B%0D%0A)

**Comment by s-ve** [comment]
Possibly related : #7657, #2388, #5101, #10734

**Comment by RyanCavanaugh** [comment]
@yenshih please fill out the entire template (including search terms) for any future issues. Thanks!
