### ISSUE TITLE
Destructuring (ES6)

### ISSUE THREAD

**Issue by RyanCavanaugh** [Microsoft/TypeScript#240]
### Example
```ts
var [x,y] = myFun();
```

### Codegen
```js
var __a = myFun(); // fresh var __a
var x = __a[0];
var y = __a[1];
```

### Type annotations
```ts
// {x: myX} is a ES6 destructuring with renaming, this looks awkward
var {x: myX: number, y: myY: number} = myPoint();
// Moving type annotation to beside destructuring left hand side
var {x: myX, y: myY}: {x: ...; y: ...} = myPoint();
```

**Comment by ahejlsberg** [comment]
With #1878 the spec now documents our implementation of destructuring, modulo support for iterators. Keeping this bug open to track that.

**Comment by ahejlsberg** [comment]
Created #1900 to track work on iterators so we can close this issue.

**Comment by mpawelski** [comment]
Are there any plans to add type annotation to destructured variables?
I see there were some discussion in this thread.
I would be very useful for example for React stateless functions components.
Flow team is thinking about it to
https://github.com/facebook/flow/issues/235

**Comment by Arnavion** [comment]
@mpawelski It's a bit verbose to avoid clashing with renaming syntax but it's possible:

```typescript
var a: any;

var [x, y]: [string, number] = a; // x is string, y is number

var { w, z }: { w: string, z: number } = a; // w is string, z is number
```

**Comment by mpawelski** [comment]
@Arnavion well, I know you can do that, but you need to write each property name twice which is far from ideal, and the purpose of descructuring is just to make code more succinct and easier to read/write, it's just a syntatic sugar. If I need to write each property name twice then it's better for me to not use destructuring at all.

I really like @fdecampredon proposition
```
var {x: myX: number, y: myY: number} = myPoint(); // with renaming
var {x:: number, y:: number} = myPoint(); // without renaming
```
and wonder if Typescript team plan on adding something similar
