### ISSUE TITLE
SVG interfaces missing

### ISSUE THREAD

**Issue by inad9300** [microsoft/TypeScript#24001]
[SVG 1.1](https://www.w3.org/TR/SVG/eltindex.html) defines 80 elements. [SVG 2](https://www.w3.org/TR/SVG2/eltindex.html) defines 77. TypeScript has 61 interfaces for SVG elements, based on the type declarations for `createElementNS()`. Some examples of SVG interfaces missing in TypeScript (many of them are defined by both SVG versions):
- [SVGAnimateElement](https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimateElement)
- [SVGAnimateMotionElement](https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimateMotionElement)
- [SVGAnimateTransformElement](https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimateTransformElement)
- [SVGCursorElement](https://developer.mozilla.org/en-US/docs/Web/API/SVGCursorElement)
- [SVGMeshElement](https://developer.mozilla.org/en-US/docs/Web/API/SVGMeshElement)
- ...

Based on this, some questions:
- How reliable are TypeScript types?
- How reliable and updated are the sources that TypeScript uses to get its types?
- Does someone spend time verifying the results of the automatically generated typings?
- Are there any automated tests in place?
- Do you recommend the use of TypeScript's DOM-related typings in production?
- In particular for SVG, what is the source and how are the typings generated?

Overall, I would simply like to know if we are walking on a minefield, and if so to see this stated clearly somewhere.

In my experience, the support for JavaScript standard functions is great. I've never encountered a problem with them. It feels professional, complete, fully covered. With DOM-related declarations I feel the opposite is true - I don't stop finding problems and seeing bug reports. It simply feels like an unfinished job, and I'm very much afraid of making use of it or recommending it to anybody.

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by mhegazy** [comment]
For PRs, please see [examples](https://github.com/Microsoft/TSJS-lib-generator/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Asaschanaz+is%3Aclosed+Add+types).

**Comment by nd-02110114** [comment]
@mhegazy 
@RyanCavanaugh 

I fixed this issue! Please confirm 🙇

**Comment by inad9300** [comment]
Regardless of the technical aspect, I am still interested in getting some kind of answer to the questions above.
