### ISSUE TITLE
Randomly get current identifier as completion

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#24009]
To reproduce:

* Type `namespace `
* Type randomly. Every once in a while, the current text will be recommended as a completion. I've gotten this to reproduce with `const `also.

May be a vscode bug. @mjbvz Any idea how this could happen?

![werwke](https://user-images.githubusercontent.com/19274678/39842477-5e260cd2-539b-11e8-8b7a-aad00ef814e5.jpg)

**Comment by sheetalkamat** [comment]
Moved the issue to vscode since tsserver correctly returns no completion info.
