### ISSUE TITLE
Explicit typing of instance level property 

### ISSUE THREAD

**Issue by shamhub** [Microsoft/TypeScript#24005]
In the below code,
```

interface PersonDetail{
    name: String;
    age?: Number;
    gender?: String;
}

function Person(details: PersonDetail){
    this.name: String = details[0];  // doesn't allow explicit typing
    this.age: Number = details[1];
    this.gender: String = details[2];
}

let a = new Person({name: 'Name1'});
let b = new Person({name: 'Name2', age: 20});

```
How to explicitly type instance property(`this.name`) & variable `a`?

**Comment by andy-ms** [comment]
Write a class instead -- no good way to type a constructor function if not in JS code.
Also, you probably meant `string` not `String` and `number` not `Number` -- [tslint](https://github.com/palantir/tslint) can catch that kind of error.

**Comment by shamhub** [comment]
I meant `Number` javascript constructor but not `number` TS primitive type.

**Comment by andy-ms** [comment]
> I meant `Number` javascript constructor

When you're in an interface, you should specify the types of things, not any associated constructors. When you write `name: String`, you presumably it to be implemented as a primitive string like `{ name: "foo" }`, not an object like `{ name: new String("foo") }`.

**Comment by shamhub** [comment]
@andy-ms  In TypeScript, each member is public by default. Below code does not work

```
interface PersonDetail{
	name: string;
	age?: number;
	gender?: string;
}

class Person{
	name: string;
	age: number;
	gender: string;
	
	constructor(details: PersonDetail){
		this.name = details[0];
		this.age = details[1];
		this.gender = details[2];
	}
}

let a: Person = new Person({name: 'Name1'});
let b: Person = new Person({name: 'Name2', age: 20});

console.log(a.name); // gives undefined

```

**Comment by shamhub** [comment]
With associated constructors, below code works,
```

interface PersonDetail{
	name: String;
	age?: Number;
	gender?: String;
}

class Person{
	name: String;
	age: Number;
	gender: String;
	
	constructor(details: PersonDetail){
		this.name = details['name'];
		this.age = details['age'];
        this.gender = details['gender'];
	}
}

let a: Person = new Person({name: new String('Name1')});
let b: Person = new Person({name: new String('Name2'), age: new Number(20)});

console.log(b.name.valueOf());
console.log(a.name.valueOf());

```

**Comment by andy-ms** [comment]
If you really intend for the value to be a `new String()` and not a primitive, then `String` is the correct type to use. But most js code prefers the primitive version `string`.

**Comment by RyanCavanaugh** [comment]
You really really really Truly really do not want to use `Number`, `String`, etc.

See https://stackoverflow.com/questions/15487220/typescript-primitive-types-any-difference-between-the-types-number-and-numbe/15488171#15488171

and

https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html

**Comment by shamhub** [comment]
@RyanCavanaugh  Do's and dont's are not explaining well, for the reason to not use `Number`

**Comment by shamhub** [comment]
@andy-ms  Main reason I used wrapper objects, to make code look more OOP with TypeScript

**Comment by andy-ms** [comment]
@shamhub It's very uncommon in JavaScript to write `new Number()`. A `new Number()` can have properties, while a `number` is immutable. It doesn't make your code more object-oriented to write `new` everywhere -- c++, java, c# all have immutable stack-allocated numbers.

**Comment by shamhub** [comment]
Is it uncommon to write `new Number()` in TypeScript?

**Comment by andy-ms** [comment]
Yes, it's very uncommon. It has extra capabilities you don't need -- it's a hashtable and you can write to properties of it. If you're not using that feature (and you shouldn't), better not to give the impression that you are.

**Comment by shamhub** [comment]
@andy-ms Don't we use `Error()` JavaScript constructor as `new Error()`? For exceptions.

**Comment by andy-ms** [comment]
@shamhub See [mdn](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error) -- `Error()` and `new Error()` are the same thing.

**Comment by shamhub** [comment]
@andy-ms Agreed. But that is a different point. My query is arpund using `Error()` JavaScript constructor in TypeScript code, which you agree to use. What can't I use `Number` constructor?

**Comment by andy-ms** [comment]
@shamhub `Error()` and `new Error()` do the same thing, `Number()` and `new Number()` do different things. JS is complicated.
