### ISSUE TITLE
TypeScript needs structs, here's why

### ISSUE THREAD

**Issue by raffael** [Microsoft/TypeScript#24007]
## Search Terms

struct, immutable

## Suggestion

Adding support for structs.

## Use Cases

Right now, if you want to bundle multiple variables in one container, you have to use standard JavaScript objects, and you most probably want to define an interface that specifies the scheme of your data for the powerful typing system:

	interface Point {
		x: number;
		y: number;
	}

	interface Size {
		width: number;
		height: number;
	}

	interface Rect {
		origin: Point;
		size: Size;
	}

	let rect: Rect = { origin: { x: 10, y: 10 }, size: { width: 100, height: 100 } };

In this example, "rect" is a JavaScript objects, which is passed around by reference, not by value. These objects are mutable by any participant in the data-flow, which is dangerous and known to be the source of many programming errors. Particularly, this is a pitfall for newcomers, which are not used to how JavaScript works. Therefore, these objects need to be treated with caution, and require copying before being passed along, if external mutation needs to be prevented.

E.g., consider the following example, in which we create two "layers", with the second one having the same size, but being positioned differently:

	class Layer {
		drawingRect: Rect;
	}

	let layer = new Layer();
	layer.drawingRect = { origin: { x: 10, y: 10 }, size: { width: 100, height: 100 } };

	let secondLayer = new Layer();
	var drawingRect = layer.drawingRect;
	drawingRect.frame.origin = { x: 100, y: 100 };
	secondLayer.drawingRect = drawingRect;

This is a bug: We do not copy the drawingRect before modifying it, and therefore, when modifying the origin of the drawing rect for the second layer, we at the same time modify the origin of the first layer as well.

There are possible work-arounds already:
– Explicitly copy objects before mutating them. This is error-prone and can easily be forgotten.
– Define custom setters and getters (e.g., for the "drawingRect" of the "Layer" class of the previous example), in which you copy the property object before returning or storing it. This works better, but requires a lot of boilerplate code.

To fix this elegantly, though, what is really needed is proper support for structs, which are passed by value, instead of by reference. If "Rect" in the previous example was a struct, obtaining the drawingRect of the first layer would yield a new struct, with the same values, which then can be mutated without modifying the original struct. This is much safer, and to many developers, also more intuitive.

I understand that JavaScript has no native support for structs. This however should not be the excuse for why structs do not exist in TypeScript. I think the transpiler provides all the freedom needed to allow having proper struct support. E.g., the most straight-forward approach that comes to my mind, is to take care of the copying of the objects behind the curtains for the developer, whenever a struct is passed along to a new variable.

I imagine structs being defined as follows:

	struct Point {
		x: number;
		y: number;
	}

	struct Size {
		width: number;
		height: number;
	}

	struct Rect {
		origin: Point;
		size: Size;
	}

Thinking ahead, structs could designed to become very powerful data structures. Next to holding primitive values or other structs, they could also support computed values (e.g., think of a computed value "area" in "Rect", which is "width" times "height"), or static constants (e.g., "zero" in "Rect", which returns a Rect instance with zero dimensions).

## Checklist

My suggestion meets these guidelines:
 [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
 [x] This wouldn't change the runtime behavior of existing JavaScript code
 [ ] This could be implemented without emitting different JS based on the types of the expressions
 [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by andy-ms** [comment]
This would be out of scope of the [design goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals) since it involves type-directed emit.

**Comment by andy-ms** [comment]
>  I think the transpiler provides all the freedom needed to allow having proper struct support.

There's the problem -- the transpiler's job is to remove types, and transpile valid new javascript to valid old javascript. This request seems to be asking to add new features not present in any version of javascript. And the emit would depend on a type, that is `function f(r: Rect)` couldn't be emitted without knowing what `Rect` means.

**Comment by raffael** [comment]
Hi Andy,

Thanks for your comments!

> [...] and transpile valid new javascript to valid old javascript

You mean TypeScript into valid old JavaScript? I totally agree with this, — but I don't see how the justification to not add structs applies to structs, but doesn't apply to other features, that TypeScript has added in the past on top of existing JavaScript features.

Just like other language features of TypeScript, that aren't available in JavaScript (e.g., union types), `structs` could be added to the TypeScript language as well, which then would be tranformed into something that works with JavaScript. This could mean, e.g., to back TypeScript structs by native JavaScript objects, and to make sure that assigning a struct instance to a new variable, a copy actually is assigned, instead of the original.

> [...] This request seems to be asking to add new features not present in any version of javascript

Yes, but again, this wouldn't be the first time. See union types, or simple interfaces, which AFAIK do not exist in JavaScript.

I see `structs` as a very powerful and substantial, well established feature of many successful, existing languages, and would like to make sure that dismissing the idea of having them in TypeScript is really well considered.

**Comment by andy-ms** [comment]
> See union types, or simple interfaces

Those are *types* -- they aren't present at runtime. The whole point of typescript is to add types. But structs as you describe them would have runtime consequences, such as not being pass-by-reference.

**Comment by sledorze** [comment]
@raffael Union and Interfaces exist only at type level
