### ISSUE TITLE
Refactoring: Extract Type

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#24017]
# Background

I hate offhandedly writing a type out in one location that I'll need to cut/paste later.

# Proposal

Given a selected type segment, provide the ability to extract that type into

* an interface if given a type literal or
* a type alias otherwise

in any scope where each captured type is available.

Optionally, a parameterized type alias can be made available in scopes where captured types are not available.

![extracttypealias](https://user-images.githubusercontent.com/972891/39857951-f2f1dc58-53e9-11e8-9762-1a6dc579de29.gif)

**Comment by Kingwl** [comment]
👍 a useful feature

**Comment by mhegazy** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/23869

**Comment by DanielRosenwasser** [comment]
Mine is better.

**Comment by mhegazy** [comment]
mine now has the GIF 😛

**Comment by DanielRosenwasser** [comment]
Thief!
