### ISSUE TITLE
Can't use RegExp as computed property / index type

### ISSUE THREAD

**Issue by gakada** [Microsoft/TypeScript#24029]
**TypeScript Version:** 2.8.3

**Code**

```ts
const x = {
  [/(.+)\s+(.+)/]: true
}

console.log(x[/(.+)\s+(.+)/]) // true
```

**Expected behavior:** example compiling without errors and printing `true`. While it is not the only unsupported type, it was stated in other issues that supporting other types can lead to problems. Is it also the case for `RegExp`? It has special literals and well-defined (?) `toString` method, using those literals can be more convenient than using strings.

Another thing here, it is stated in the [spec](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md) (also on [official site](https://www.typescriptlang.org/) and [wikipedia](https://en.wikipedia.org/wiki/TypeScript#Compatibility_with_JavaScript)) that "Every JavaScript program is also a TypeScript program" ("TypeScript is a typed superset of JavaScript" and "TypeScript is a strict superset of ECMAScript 2015, which is itself a superset of ECMAScript 5, commonly referred to as JavaScript. As such, a JavaScript program is also a valid TypeScript program, and a TypeScript program can seamlessly consume JavaScript").

**Actual behavior:** compile error

```
TSError: ⨯ Unable to compile TypeScript
t.ts (2,3): A computed property name must be of type 'string', 'number', 'symbol', or 'any'. (2464)
t.ts (5,15): Type 'RegExp' cannot be used as an index type. (2538)
```

**Related Issues:** #1415

**Comment by gakada** [comment]
That is true, though my main use case / concern (partly caused by the "superset" statement) here is RegExp literals, as
```ts
  [/some regexp/]: ...
```
seems pretty well-defined.

Of course, I can do something like

```ts
  [s(/some regexp/)]: ...
```

but that is adjusting a valid and well-behaved JavaScript program.

**Comment by aaaaeinai** [comment]
Is this a possible generics work-around?
