### ISSUE TITLE
Duplicate identifier error in services for commonjs `module.exports.prop = `

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#24024]
**TypeScript Version:**  2.9.0-dev.20180510

**Code**

**a.js**
```js
module.exports = class C {};
module.exports.D = class D {};
```

**b.js**
```js
const a = require("./a");
```

Open the two tabs side-by-side in an editor. Initially there is no error, but when you make any edit (e.g., adding a newline) to `b.js`, then `module.exports.D` in `a.js` is marked with an error `Duplicate identifier 'D'.` (Making any edit to `a.js` will make it go away, but then editing `b.js` makes it come back...)

CC @sandersn

**Comment by sandersn** [comment]
Note that adding a third line in a.js, `var d = new D()`, causes a crash in `resolveName`, even from the command line. I'll file that as a separate bug.

**Comment by sandersn** [comment]
@andy-ms helped me find a repro that works from the command line. Put the require in the same file:

```js
var wat = require('./test')
module.exports = class C {}
module.exports.D = class D { }
```

Note that the require has to be first. My current hypothesis is that `getCommonJsExportEquals` creates a merged symbol which is `!==` the symbol for class D, thereby evading the check I added in #24466. I have a simpler fix that I will put up shortly.
