### ISSUE TITLE
JSDoc not recognized for default export expressions

### ISSUE THREAD

**Issue by errorx666** [Microsoft/TypeScript#24033]
**TypeScript Version:**  2.8.3

**Search Terms:** 
jsdoc default export expression type

**Code**

```js
import webpack from 'webpack';

//  works
/** @type {webpack.Configuration[]} */
const foo = [ {}, {} ]; // has correct type

/** @type {webpack.Configuration[]} */
export default [ {}, {} ]; // has wrong type

/** @export {webpack.Configuration[]} */
export default [ {}, {} ]; // has wrong type

/** @exports {webpack.Configuration[]} */
export default [ {}, {} ]; // has wrong type
```

**Expected behavior:**
JSDoc type information is used.

**Actual behavior:**
JSDoc type information is not used.

**Playground Link:** n/a

**Related Issues:** none

**Comment by IanMitchell** [comment]
Also impacted by this! I'm super new to TypeScript (only really use JSDoc within VS Code) but thought I'd poke around this issue a bit - I'm a little unsure of where to put an example test though. Is this the correct location / test style?

`TypeScript\tests\cases\conformance\jsdoc\jsdocTypeTagExport.ts`
```typescript
// @allowJS: true
// @suppressOutputPathCheck: true
// @strictNullChecks: true

// @filename: a.js
/** @type {(key: string) => string} */
export default (key) => key;

// @filename: b.ts
export default (key: string) => string;
```

**Comment by sandersn** [comment]
@IanMitchell You also need `// @checkJs: true` but otherwise you've got it.

**Comment by bySabi** [comment]
@mhegazy workaround works.
```
export default /** @type {webpack.Configuration[]} */([{}, {}]);  // OK
```

but the desired syntax does not
```
/** @type {webpack.Configuration[]} */
export default [{}, {}]); // Wrong
```

any Roadmap?

**Comment by Twiggeh** [comment]
Export default doesn't work again. In-lining the type doesn't fix it.
![export default broken](https://user-images.githubusercontent.com/23149166/98467056-8fd74d00-21d3-11eb-854a-33b92caff5a1.gif)

**Comment by RCVarley** [comment]
It's hitting me too.

![VSCode export default type issue](https://user-images.githubusercontent.com/20630026/101471511-4ea39b80-393f-11eb-9148-94326bd1bcec.gif)

**Comment by zanona** [comment]
I'm afraid this may still be an issue. Perhaps this issue has been closed prematurely?

**Comment by sandersn** [comment]
Please open a new issue; this one has been closed a long time now.

**Comment by MartinJohns** [comment]
I think this is related: #45233
