### ISSUE TITLE
Choose build's starting file(s) VSProject

### ISSUE THREAD

**Issue by Griffork** [Microsoft/TypeScript#2404]
We have a project with a number of "start" files for beginning building (the project contains a number of applications that have shared source code, each application has a file that is launched in the command line, or included in html files that is the "start" for the whole app). 
It would be nice to choose a number of "start" files that the compiler can crawl from when doing a build.

The particular use case for this is that we'd like to output a few different applications to single files that share common code and are all declared within the same project file (e.g. unit tests).

**Comment by NoelAbrahams** [comment]
> It would be nice to choose a number of "start" files that the compiler can crawl from when doing a build

Is this about specifying the file order for compilation in a Visual Studio project?

**Comment by basarat** [comment]
Use a reference.ts

**Comment by Griffork** [comment]
For example: Say I have the following folder structure:
```
Project
 | - app1.ts
 | - app2.ts
 | - shared
 |     | - sharedcode.ts
```
In a Typescript Visual Studio project when `Combine Javascript output into file` is selected, it will arbitrarily choose which file to start the compilation at (e.g. it might start at app1.ts, app2.ts or even sharedcode.ts). What I want to be able to do, is specify compile two output files, one starts from app1.ts and another starts from app2.ts.

**Comment by basarat** [comment]
>  it will arbitrarily choose which file to start the compilation at

If you have a reference.ts that reference.ts is the only thing that is passed to the compiler and the order is determined by the reference tags in reference.ts.

Will not help you for multiple targets though. You will need separate projects for that.

**Comment by Griffork** [comment]
That's why this is a feature request!
On 20/03/2015 12:21 PM, "Basarat Ali Syed" <notifications@github.com> wrote:
>>
>> it will arbitrarily choose which file to start the compilation at
>
> If you have a reference.ts that reference.ts is the only thing that is
passed to the compiler and the order is determined by the reference tags in
reference.ts.
>
> Will not help you for multiple targets though. You will need separate
projects for that.

**Comment by NoelAbrahams** [comment]
> You will need separate projects for that.

That would be the way to go.

A project is a logical unit. It doesn't make sense to have two applications in one project.

For this particular scenario there should be three projects: one for each app and one shared.

**Comment by Griffork** [comment]
We did it this way because it was easier than having 120 projects (40
"apps", 3 "units" per app).

**Comment by NoelAbrahams** [comment]
40 apps + 1 shared =  41 projects. We have more than that.

**Comment by Griffork** [comment]
40 "apps", each app relies on 3 separate programs that have to be compiled
into separate files that often also have common code that no other "app"
had (so their common code is located in each app's folder) and devs are
often working on more than one at once, that makes for a very clutted
solution file.

**Comment by NoelAbrahams** [comment]
>  common code that no other "app" had

That's not common, then.

How about

* Create a separate project for each of the 40 apps.
* Split the shared into say 5 -10 projects.

The shared projects should be grouped logically, e.g. utils, com, etc. Then ensure all the shared projects are built first using the project dependencies feature provided by VS. 

Each app project would reference the `.d.ts` produced by the shared projects - only the ones they want.

**Comment by Griffork** [comment]
Since I'm doing such a bad job at explaining my case, I'll give it another go.
I was using the word app incorrectly, but I don't have a better one. I'm now going to start referring to it as 'system'.
We have 40 'Systems', which each have a function. Each 'System' comprises of 3 programs which each run on different computers and communicate to each other to produce the desired result. In order for this to work we require 3 different output files:
file1.js which is run on computer1
file2.js which is run on computer2
file3.js which is run on computer3
And we need each of those three files to be generated for each of the 40 different 'Systems'. So you end up with:
System A:
 • file1
 • file2 
 • file3
System B:
 • file1
 • file2
 • file3
etc...
Before concatenation, the structure actually looks like:
- common code
- System A
   • System A Common Code
   • file1 code
   • file2 code
   • file3 code
- etc...

Does this highlight the problem better?

**Comment by mhegazy** [comment]
@Griffork i do not think i understand the issue. is this still a problem?

**Comment by Griffork** [comment]
Short answer: No.
We created some really big ugly work-around because this wasn't supported in typescript.

The main point was that code that was shared between server and client where the client is to be concatenated and the server isn't is not doable in typescript.
This is specifically a big issue because our launched files for server and client changed for every unit test (the test would run the necessary files in it's own environment). What we wanted is the ability to have a "test" version of the code compiled into each of the tests' directories so that they could be run standalone, one after the other.

Also I'm not working on that project at the moment.

**Comment by mhegazy** [comment]
Thanks. i will close this one then. I would appreciate it, when you have time of course,  if you give us a write-up with some more details on the solution you have built and what we need to change to enable a simpler workflow.
