### ISSUE TITLE
Correct usage of type, update docs

### ISSUE THREAD

**Issue by ghost** [microsoft/TypeScript#24057]
Docs needs to be updated.
https://www.typescriptlang.org/docs/handbook/basic-types.html

Which is the correct usage? Both works but one of them is wrapper.

let prettySure: Object = 4;
let prettySure: object = 4;

let prettySure: Number = 4;
let prettySure: number = 4;

let prettySure: String = "Four";
let prettySure: string = "four";

**// I wonder array type usage**
let prettySure: Array = ["Four"];
let prettySure: array = ["four"];

Guide:
https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html

![screen shot 2018-05-11 at 15 19 51](https://user-images.githubusercontent.com/1254613/39924021-cd0a2194-552e-11e8-85d1-6cc4a083d529.png)

**Comment by mhegazy** [comment]
Please see https://stackoverflow.com/questions/15487220/typescript-primitive-types-any-difference-between-the-types-number-and-numbe/15488171#15488171

and

https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html

**Comment by mhegazy** [comment]
You might have better luck sharing this on StackOverflow. This is not a support forum, it is one for reporting compiler/language bugs and suggestions. 
If you believe you are running into a compiler bug, please share a minimal repro project that demonstrates the issue you are running into and why you believe this is a compiler bug and not a declaration file issue or library usage problem.

**Comment by atilkan** [comment]
@mhegazy Look at the comments of the link you provided. I was there before and that is why i reported this. Second link is exactly the one i provided. 
Docs needs to be updated.

**Comment by mhegazy** [comment]
The text and the example in the file talks about `Object`.. and explains that it does not do what you think it does.. so you want to remove it all together, and replace it with `object`?

**Comment by RyanCavanaugh** [comment]
Some discussion of `object` is certainly warranted there now that it exists

**Comment by RyanCavanaugh** [comment]
Handbook is rewritten
