### ISSUE TITLE
MessagePort type definition is missing support for 'messageerror' event type

### ISSUE THREAD

**Issue by farooqu** [Microsoft/TypeScript#24059]
**TypeScript Version:**  2.9.0-dev.201xxxxx

**Search Terms:** MessagePort

The MessagePort spec says that the event handler types that must be supported by any implementation of MessagePort are 'message' and 'messageerror'.

The MessagePort type definition needs to have the 'messageerror' event type added since it is missing.

https://html.spec.whatwg.org/multipage/web-messaging.html#handler-messageport-onmessageerror

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.
