### ISSUE TITLE
Imported interface behaves differently from localy available interface

### ISSUE THREAD

**Issue by ackvf** [Microsoft/TypeScript#24065]
**TypeScript Version:**  2.9.0-dev.20180511

**Code**

```ts
// types.d.ts
export interface MyImportedItem {
  id: number
  another: string
  param1: string
}


// firebase.actions.ts

interface MyItem {
  id: number
  another: string
  param1: string
}

getFirebaseRef().push({ // error
  id,
  another: data.another,
  param: data.someValue,
  // param2: 'X',
} as MyItem)

getFirebaseRef().push({ // no error
  id,
  another: data.another,
  param: data.someValue,
  // param2: 'X',
} as MyImportedItem)

```
> Error:
> ```
> Type '{ id: any; another: any; param: any; }' cannot be converted to type 'MyItem'.
>       Property 'param1' is missing in type '{ id: any; another: any; param: any; }'.
>```

**Expected behavior:**
Expected is consistent behavior for local and imported interface.
Expected is that missing and invalid props are correctly reported by the IDE.

**Actual behavior:**

![image](https://user-images.githubusercontent.com/2313018/39939035-3b9ffffe-5555-11e8-9384-a7f3484cd128.png)

**Comment by RyanCavanaugh** [comment]
I see an error in your second call - there's a red squiggle on `id`

**Comment by ackvf** [comment]
That is unrelated, it's that id is not defined, I have just moved the code from bottom to top to make better screenshot. If I swapped `as MyItem` with `as MyImportedItem`, the error mentioned above would move as well.

**Comment by mhegazy** [comment]
Can u share a self contained repro for us to look at?

**Comment by ackvf** [comment]
The code already _is_ a self-contained repro of the issue...

**Comment by ackvf** [comment]
I take the issue back, I had `MyImportedItem` imported twice, not sure how that happened. Anyway, I have a question that is still related to what I said is an expected behavior: _I don't get errors when my object is not complete, but I **do** get error that a key is missing if I introduce another key that is not part of the interface._

No error
![image](https://user-images.githubusercontent.com/2313018/39961826-9bb38cbe-563e-11e8-87b6-002b257d2065.png)

Error `param1 is missing`
![image](https://user-images.githubusercontent.com/2313018/39961829-c4168f44-563e-11e8-86b2-8d06853c44a4.png)

<hr/>

Moreover, can somebody please explain to me why the const declaration here gives an error correctly, while using it with `as` in the push does not?
![image](https://user-images.githubusercontent.com/2313018/39961854-4e391354-563f-11e8-80be-6ab101993371.png)

Here I get that `param1 is missing` in the push.
![image](https://user-images.githubusercontent.com/2313018/39961864-b98355c0-563f-11e8-88d0-2b7eedb107b0.png)

<hr/>
I am using it like this so that I get hints for the object I am pushing.

![image](https://user-images.githubusercontent.com/2313018/39961905-ca228666-5640-11e8-9005-786ea0cdaaa9.png)


Is there a better approach to get hints but avoid declaring the object beforehand? Thank you

**Comment by ackvf** [comment]
Obviously, I cannot use this to specify that the object I am pushing is MyItem `getFirebaseRef().push({}: MyItem)`

Using type casting also -by nature- does something else than I want, so if there was something like type guards, that would be great

`getFirebaseRef().push({} is MyItem)`
-> now I get hints for object properties
-> now I get errors for missing and unknown properties

**Comment by RyanCavanaugh** [comment]
@ackvf #7481
