### ISSUE TITLE
Strict mode can't precede declaration reference

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#2407]
This code:
```
'use strict';
/// <reference path="typings/node/node.d.ts" />

import * as fs from 'fs'
```
produces this error:
```
test.ts(4,21): error TS2307: Cannot find external module 'fs'.`
```

But changing the `strict mode` line from preceding the declaration reference line to beneath it—won't produce any error.

**Comment by CyrusNajmabadi** [comment]
This is by design.  /// comment references must precede all code.

**Comment by tinganho** [comment]
@CyrusNajmabadi thanks
