### ISSUE TITLE
Docs: Difference between esnext, es6, es2015 module targets

### ISSUE THREAD

**Issue by bcherny** [microsoft/TypeScript#24082]
## Search Terms

esnext, es6, es2015, module, tsconfig, tsconfig.json, difference, document

## Suggestion

It would be great if this can be documented. On the face of it, the output for all three seems to be identical.

Related: It would also be nice to document why targeting `module: "none"` when your code is a module (ie. uses ES2015 imports/exports) generates CommonJS-compatible code instead of exporting to globals as "none" seems to imply.

**Comment by DanielRosenwasser** [comment]
To just answer the question, the difference is that `import()` expressions are understood in `esnext`, but not in `es2015` (and as of TypeScript 2.9, `import.meta` is only understood with `esnext`).

I guess you could possibly expect an `es2019` module target for both.

**Comment by mhegazy** [comment]
in addition to what @DanielRosenwasser mentioned, `esNext` is just a place holder for features that are on the standard track but is not in an official ES spec yet. e.g. `import.meta` and `import()` expressions. as TC39 adds these features to a versioned spec, we will add a new `--module ES20**` to reflect that. 

Also `es6 === es2015`.

**Comment by qm3ster** [comment]
Is there a place where I can see the list of https://github.com/tc39/proposals syntax supported?
(As opposed to module target or libs.d.ts?)

**Comment by zoltan-nz** [comment]
You can find all the libs and supported features in this folder: https://github.com/Microsoft/TypeScript/tree/master/lib

**Comment by gilamran** [comment]
The only place that I found for understanding TS support is [here](http://kangax.github.io/compat-table/esnext/#typescript3_2corejs3), but this table is misleading... "red" doesn't mean that TS doesn't support the feature, it means that it doesn't run on previous version of JavaScript... yea, misleading.

Can we create a similar solution for TS, but with real supported/unsupported table? (With relation to the `target`)

**Comment by ayqy** [comment]
Is there someone who can give a detail explanation for `module: "none"` ?
ref: [Difference between typescript module “None” and “CommonJS”](https://stackoverflow.com/questions/45803383/difference-between-typescript-module-none-and-commonjs)

**Comment by vegerot** [comment]
Is targeting `ESNext` or module `ESNext` stable for long term releases?  What if I want `import()` but also want stability?

**Comment by Mikilll94** [comment]
@vegerot 
Any answer to this question?

**Comment by vegerot** [comment]
I wish

**Comment by DanielRosenwasser** [comment]
If you're looking for stability, you may want to hold off on using `--target esnext` unless you're piping the output through another compiler that supports newer ESNext syntax like Babel.

**Comment by scarcoco** [comment]
tsconfig.json module options: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', 'es2020', or 'ESNext'，what's different of  'es2020', or 'ESNext'?

**Comment by stephen-dahl** [comment]
@scarcoco I am guessing from reading this that es2020 is when the import() and import.meta landed. I am just guessing though. ESNext is all the new features that have not been finalized yet. there may or may not be any difference between that and es2020 at the time of writing but in the future when more features are inevitably added to the module system ESNext would include those.

**Comment by thernstig** [comment]
Top-level await was included in ECMAScript 2022, see https://github.com/tc39/proposals/blob/main/finished-proposals.md

But there is no `"module": "ES2022"`, so one is forced to use `"module": "esnext"`. But `next` seems dangerous to me as in a few years from now it might mean new features we do not support yet due to not having upgraded Node.js.

It's not clear for me why there is no `ES2022` to support top-level await without having to resort to `next`.

**Comment by bennycode** [comment]
I recently noticed that [import assertions](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-5.html#import-assertions) are supported with [module](https://www.typescriptlang.org/tsconfig#module) `esnext` and `nodenext`, but not with `es2022` (tested with TypeScript 5.1.6). I assume that is because ESNext is continuously evolving but ES2022 is not?

@thernstig it looks like `"module": "es2022"` will allow you now to use top-level await (tested with TypeScript 5.1.6):

> Top-level ‘await’ expressions are only allowed when the ‘module’ option is set to ‘es2022’, ‘esnext’, ‘system’, or ‘nodenext’, and the ‘target’ option is set to ‘es2017’ or higher.

**Comment by RyanCavanaugh** [comment]
New module docs are live at https://www.typescriptlang.org/docs/handbook/2/modules.html

**Comment by catamphetamine** [comment]
> New module docs are live at https://www.typescriptlang.org/docs/handbook/2/modules.html

I'd suggest the following link: https://www.typescriptlang.org/tsconfig#module

**Comment by mrdulin** [comment]
I'd suggest this docs: https://www.typescriptlang.org/docs/handbook/modules/theory.html#the-module-output-format
