### ISSUE TITLE
Interesting behavior in case of 'null' and type 'object' 

### ISSUE THREAD

**Issue by smff** [Microsoft/TypeScript#24089]
function test(a: object = {}) {
    return a;
}
test(null);

**expected:** 
Argument of type 'null' is not assignable to parameter of type 'object'.

**actual:**
It works with no errors.

**playground**
http://www.typescriptlang.org/play/#src=function%20test(a%3A%20object%20%3D%20%7B%7D)%20%7B%0D%0A%20%20%20%20console.log(a)%3B%0D%0A%7D%0D%0Atest(null)%3B

Yes, I know that it is a "special behavior" (typeof null is Object) of JS, but come on.

**Comment by bcherny** [comment]
@smff You want to enable `strictNullChecks`. Once you do, you'll get an error:

```
Argument of type 'null' is not assignable to parameter of type 'object | undefined'.
```

See https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html

**Comment by smff** [comment]
@bcherny thank you, got it.
