### ISSUE TITLE
input file override crazytown

### ISSUE THREAD

**Issue by ORESoftware** [Microsoft/TypeScript#24092]
I have this config:

```json
{
  "compilerOptions": {
    "outDir":"dist",
    "allowJs": false,
    "pretty": true,
    "skipLibCheck": true,
    "declaration": true,
    "baseUrl": ".",
    "target": "es6",
    "module": "commonjs",
    "noImplicitAny": true,
    "removeComments": true,
    "allowUnreachableCode": true,
    "lib": [
      "es2015",
      "es2016",
      "es2017"
    ]
  },
  "compileOnSave": false,
  "include": [
    "src"
  ]
}
```

I keep getting this error:

> error TS5055: Cannot write file '/Users/alexamil/WebstormProjects/oresoftware/fly/dist/fly.d.ts' because it would overwrite input file.

It's driving me batty lol. `tsc` should know that the `dist` dir is the destination, so no input files should come from there, right? not only that, but the `include` is set to `src` in the config.

here are my versions:
```bash
nodejs version: v9.11.1
npm version: 5.6.0
typescript version: Version 2.8.3
```

**Comment by andy-ms** [comment]
You probably imported from `dist` at some point. Include doesn't specify the files to be included (Microsoft/TypeScript-Handbook#692), it specifies the *root* files.

**Comment by RyanCavanaugh** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.

**Comment by ORESoftware** [comment]
@andy-ms thanks for info, yeah, I think in my tests, I imported from `dist`. damn.
