### ISSUE TITLE
[JSDOC] rest parameter in @typedef function(any, ...any):any does not get handled correctly

### ISSUE THREAD

**Issue by mmis1000** [Microsoft/TypeScript#24095]
**TypeScript Version:**  2.8.3

**Search Terms:** 
JSDOC, rest, function
**Code**

```js
/**
 * @typedef {function(string, ...any):string} Callback
 */

/**
 * @type {Callback}
 */
var a;
```

**Expected behavior:**
a has the same type signature as
```ts
type Callback = (arg0: string, ...arg1:any[])=>string
var a: Callback;
```
**Actual behavior:**
a has the same type signature as
```ts
type Callback = (arg0: string, arg1:any)=>string
var a: Callback;
```
Although the @typedef got parsed without error, It seems the rest parameter keyword was ignored completely somehow
**Playground Link:**  

**Related Issues:**

**Comment by que-etc** [comment]
@mmis1000 Seems to work in `typescript@next` (2.9.0-dev.20180512)

**Comment by mmis1000** [comment]
🤔 Maybe it is fixed accidentally in one of the previous commits.
I didn't found any other issue about this
Just close this if it is no longer valid in next version
