### ISSUE TITLE
JSDoc typedef with ReturnType not found

### ISSUE THREAD

**Issue by SergioMorchon** [Microsoft/TypeScript#24093]
**TypeScript Version:**  2.9.0-dev.20180512

**Search Terms:** jsdoc, ReturnType, typedef, not found, javascript

**Code**

jsconfig.json:
```json
{
    "compilerOptions": {
        "checkJs": true
    }
}
```

index.js:
```javascript
/** @typedef {ReturnType<fn>} Four */

export const fn = () => ({four: 4});
```

**Expected behavior:**
Working fine with no errors and Four with the return type of `{four: number}`.
**Actual behavior:**
Errors:
1. `fn` not found
1. Variable `fn` used before declaration.

Well, they both makes no sense together, because one says *not found* and the other says _found but not in the expected order_.
Anyway, if I put the typedef comment after the function (at the end of the file) then TypeScript just **ignores** it, so It didn't work either.

**Comment by mhegazy** [comment]
There is no type called `fn`.. you meant `ReturnType<typeof fn>` which is `void`. 

Adding `// @ts-check` to the top of the file will should you what the compiler thinks of these comments

![image](https://user-images.githubusercontent.com/8000722/40010767-9e0ca05a-575a-11e8-8de0-0fd6e4a9708f.png)

**Comment by SergioMorchon** [comment]
Sorry, I meant `export const fn = () => ({four: 4});` (return a object).
Understood; I saw some old samples working seamelessly with and without `typeof`.
Thank you for the explanation @mhegazy , it worked!
I'll close this issue.
