### ISSUE TITLE
Strange result of the declaration file.

### ISSUE THREAD

**Issue by sty1iss** [Microsoft/TypeScript#24094]
typescript: ~2.7.2

**any.ts:**

	legend = (value) => {
		return typeof value === 'boolean' ?
			{
				'options.legend.display': value
			} :
			{
				'options.legned.display' : true,
				'options.legend.position': value
			};
	};
}

**any.d.ts**:

    legend: (value: any) => {
        'options.legend.display': boolean;
        options.legned.display?: undefined;
        options.legend.position?: undefined;
    } | {
        'options.legned.display': boolean;
        'options.legend.position': any;
        options.legend.display?: undefined;
    };

*.d.ts files occurred error

why compiler does not use quote?
am i used wrong syntax?
what is wrong?

**Comment by j-oliveras** [comment]
Already fixed?

With 2.8.3, this file:
**test.ts**
```ts
const legend = (value) => {
	return typeof value === 'boolean' ?
		{
			'options.legend.display': value
		} :
		{
			'options.legned.display' : true,
			'options.legend.position': value
		};
};
```
generates this *d.ts:
**test.d.ts**
```ts
declare const legend: (value: any) => {
    'options.legend.display': boolean;
    "options.legned.display"?: undefined;
    "options.legend.position"?: undefined;
} | {
    'options.legned.display': boolean;
    'options.legend.position': any;
    "options.legend.display"?: undefined;
};
```
Using this command line:
```tsc test.ts --declaration```

**Comment by sty1iss** [comment]
@j-oliveras thanks your comment.
I tried that version, but can't using at angular 6 CLI

is this bug of low version of typescript?

**Comment by mhegazy** [comment]
> is this bug of low version of typescript?

yes, should be fixed in latest. as a work around, give `legend` an explicit type annotation:
```ts
const legend: (value: any) => {
    'options.legend.display': boolean;
    "options.legned.display"?: undefined;
    "options.legend.position"?: undefined;
} | {
    'options.legned.display': boolean;
    'options.legend.position': any;
    "options.legend.display"?: undefined;
} = (value) => {
	return typeof value === 'boolean' ?
		{
			'options.legend.display': value
		} :
		{
			'options.legned.display' : true,
			'options.legend.position': value
		};
};
```
