### ISSUE TITLE
Disable looseness/enable strictness in JavaScript files with checkJS/ts-check

### ISSUE THREAD

**Issue by SergioMorchon** [Microsoft/TypeScript#24108]
With `typescript@2.9.0-dev.20180512`, given the following `index.ts` file:
```typescript
export const createModel = ({ name }) => ({
  name: String(name)
});

const m = createModel({name: 'some name'});
m.a = '';
```
shows an error for that `m.a = ''`, because there is no `a` property in the returned object. It says that `m` is of type:
```
{
    name: string;
}
```
All right there.

But now I rename it to `.js` (and with jsconfig allowJs etc.) and gives no errors, because it says that `m` is of type:
```
{
    [x: string]: any;
    name: string;
}
```
That `[x: string]: any;` makes this less strict, and impossible to track bugs due to variable shapes. It's kind of useless this way and forces us to write the shape in JSDoc, losing type inference.

How can I do JS to be equally strict as TS in this little sample? I see this like an error, I expect that if for TS the return type has no `[x: string]: any;`, JS shouldn't, too.

keywords: JavaScript strict returntype index any

**Comment by SergioMorchon** [comment]
In that case, I would like to be able to configure that. It could be available for both JS and TS in the same way that `noImplicitAny` does, for example.
We work with a large repo for a webapp, made with JS and JSDoc, but wanted to take advantage of TS strictness.
We also try to avoid duplication, so because we already have model creators (functional way) like:
```JavaScript
/** @typedef {ReturnType<typeof createModel> Model} */

export const createModel = ({name}) => ({name: String(name)});
```

We don't want to re-define the sape of the model with a JSDoc dedicated typedef, because we wuld have the same info both in JS code and in JSDoc.
But there comes the difference, where JSDoc explicit typedef with properties is stricter tan the infered return type of the model creator.

It would be **really nice** to have some compiler flag that enables us to work that strict way.

**Comment by weswigham** [comment]
Update to the OP: In `3.1` we made it so that if you have `noImplicitAny` on, JS objects no longer gain an implied `any` index signature. So I think this is solved.
