### ISSUE TITLE
User-defined type guards in block scopes

### ISSUE THREAD

**Issue by hsir** [Microsoft/TypeScript#24128]
## Search Terms

type guards, types

## Suggestion

Is there anyway to tell the compiler that a variable is guaranteed with the type T within a specific block scope, without generating any extra javascript codes?

## Use Cases

Some variables can have multiple type or type `any`. But sometimes developers are more confident about their types. Currently I have to use `typeof` or use a function of type `() => XXX is string` to guarantee the type, but these may generate extra javascript codes. 

Another solution is to save the variable with another variable that was explicitly declared with type T, like `const a: string = k as any as string`, and then use `a` instead of `k`. But this also generates extra javascript codes.

## Examples

```typescript

function incoming(thing: array | number): void {
  // thing is array or number
  if (checkSomething()) {
    guard thing is array {
      // thing is array
      console.log(thing.length)
    }
  } else {
    guard thing is number {
      // thing is number
      console.log(thing.toFixed())
    }
  }
}

```

## Checklist

My suggestion meets these guidelines:
- [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
- [x] This could be implemented without emitting different JS based on the types of the expressions
- [x] This wouldn't change the runtime behavior of existing JavaScript code
- [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by citycide** [comment]
There has to be something generated that checks the type in order to branch &mdash; how does your example work if there is no type checking generated?

As is, if you provide an array to this function `thing.toFixed()` will throw at runtime, and if you provide a number `thing.length` will be `undefined`.

**Comment by hsir** [comment]
It's just an example of code. Maybe I have a function outside called `check`, when `check()` returns true the param `thing` is guaranteed to be a number; when `check()` returns false the param `thing` is guaranteed to be a string.

I've updated the code above.

**Comment by RyanCavanaugh** [comment]
See #10421 for discussion of block-level type guards

**Comment by hsir** [comment]
@RyanCavanaugh Thank you. It would be great if the proposal being accepted.
