### ISSUE TITLE
Expose TypeScript preference in Visual Studio

### ISSUE THREAD

**Issue by markboyall** [Microsoft/TypeScript#24124]
## Search Terms

autocomplete absolute path

## Suggestion

When using autocomplete in VS, sometimes the plugin inserts relative paths instead of absolute paths. Add a setting so that it will always insert absolute paths.

## Use Cases

Our project has a firm rule to always use absolute paths as they make refactoring much easier. Currently we have a step in code review to check for accidental relative paths but it would be nice if this was not needed.

## Examples

When I open a new Typescript file in VS, I start to write a function, and one of the argument types has not been imported, so the autocomplete list comes up. When I pick an item from the list, if the setting is set, the automatically inserted import is guaranteed to be absolute.

Absolute here means "relative to project root" (relative to baseUrl would also work for me as we set that to project root).

## Checklist

My suggestion meets these guidelines:
 [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
 [x] This wouldn't change the runtime behavior of existing JavaScript code
 [x] This could be implemented without emitting different JS based on the types of the expressions
 [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by RyanCavanaugh** [comment]
An absolute path would be like `C:/foo/bar/something`. That's actually what you want?

**Comment by markboyall** [comment]
Absolute to the root of the project. Our tsconfig has `"baseUrl": "./",` so you could also interpret it as "always insert relative to the baseUrl" I guess.

**Comment by andy-ms** [comment]
We did add this option as `readonly importModuleSpecifierPreference?: "relative" | "non-relative";` in `UserPreferences`. Don't know if VS exposes this yet. @amcasey

**Comment by mhegazy** [comment]
The VSCode setting to configure that is `"typescript.preferences.importModuleSpecifier": "non-relative"`.

@amcasey how are these settings exposed in VS?

**Comment by amcasey** [comment]
@mhegazy They're not, AFAIK.  How would we pass the info to the server?  `configure`?

**Comment by mhegazy** [comment]
>  How would we pass the info to the server? configure?

yes.

We have a few of these now. and i suspect we will add more. ones that have been requested already and added to the user preferences:

- importModuleSpecifier => relative vs non-relative
- quotePreference => single vs double
- disableSuggestions => enabled vs disabled

**Comment by amcasey** [comment]
VS doesn't need disableSuggestions since it uses a pull model.  The others seem like they could be useful.  I assume we'd put them in the options dialog.

**Comment by amcasey** [comment]
@jessetrinity has this underway. :smile:

**Comment by labeled** [comment]
Is this available in Visual Studio yet? VS Code has this option and as a team we'd like to standardize on using the absolute path however some devs use Visual Studio and some use VS Code.

**Comment by amcasey** [comment]
@labeled The code has been checked in, but I don't believe it has shipped yet.

**Comment by jessetrinity** [comment]
Closing as this feature has been added in VS2019.
