### ISSUE TITLE
jsconfig.json - checkJs and exclude not working together nicely

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#24133]
_From @brownbl1 on May 15, 2018 14:52_

Issue Type: <b>Bug</b>

I have a jsconfig.json that looks like:
![image](https://user-images.githubusercontent.com/2136925/40063891-51923726-582c-11e8-8809-f0ace5c3ea4a.png)

My goal is to achieve the equivalent of adding `//ts-check` to all js files in my project. I also have some .jsx files I want to exclude, but even if I add the `**/*.jsx` pattern to the exclude section, I still get errors and squiggles in my jsx.
![image](https://user-images.githubusercontent.com/2136925/40064001-9d44b572-582c-11e8-9129-2648986056fd.png)

If I add `// @ts-nocheck` to this file, it removes all errors and squiggles.

But I know the exclude config section is doing _something_, because if I omit it I get many more errors that I didn't have otherwise.
![image](https://user-images.githubusercontent.com/2136925/40064199-0543ad9a-582d-11e8-8a0e-00f1f426b0d7.png)

So in summary, it seems that there is a bug here in that the exclude option does not function in quite the same way as `// @ts-nocheck`.

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.88GB (17.68GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\Users\benjamin.brown\Downloads\0000-ben-browns-test-spa.json|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
cake-vscode|cak|0.10.1
npm-intellisense|chr|1.3.0
xml|Dot|1.9.2
prettier-vscode|esb|1.3.1
gc-excelviewer|Gra|2.0.21
vscode-nuget-package-manager|jmr|1.1.6
graphql-for-vscode|kum|1.11.0
mssql|ms-|1.3.1
python|ms-|2018.4.0
csharp|ms-|1.15.1
PowerShell|ms-|1.7.0
vscode-icons|rob|7.23.0
vscode-coverage-gutters|rya|2.0.0
code-settings-sync|Sha|2.9.2
vscode-hexdump|sle|1.6.0
pdf|tom|0.2.0

(1 theme extensions excluded)

</details>

_Copied from original issue: Microsoft/vscode#49910_

**Comment by brownbl1** [comment]
@mjbvz Thanks!

**Comment by mhegazy** [comment]
You probably have an import/require that picks up the .jsx files. The `include`\`exclude` entries in the tsconfig/jsconfig files gives the compiler the set of root files. it then follows `import`/`require` statements to know the full list of files in the project. For more information see https://github.com/Microsoft/TypeScript/wiki/FAQ#why-is-a-file-in-the-exclude-list-still-picked-up-by-the-compiler

You can also use `// @ts-nocheck` at the top of the file to avoid checking it.

**Comment by brownbl1** [comment]
@mhegazy Thanks for the reply. Yes, that's correct. My jsx files are being referenced and compiled. I just assumed (perhaps incorrectly?) that adding `"**/*.jsx"` to the exclude list would make adding `// @ts-nocheck` to each file unnecessary. If this isn't correct, then I'd recommend it be added as an option if there is a reason not to apply the `exclude` list in this way. 

Does that make sense?

**Comment by mhegazy** [comment]
`include`/`exclude` lists the set of rootfiles. the compiler needs to load **all** your file dependents regardless to know what types to give your imports.

**Comment by brownbl1** [comment]
I see. So perhaps it would make more sense to have separate property like `checkJsExclude`. This would effectively apply `// @ts-nocheck` using an array of glob patterns. Does that make sense? Otherwise, turning on `checkJs` results in all sorts of issues.

**Comment by mhegazy** [comment]
if you want to check most of your files, but exclude a few, then use `--checkJs` in your tsconfig.json/tsconfig.json and add `// @ts-nocheck` in the files you want to ignore.

if you want to check a few files, and ignore the rest, then use `// @ts-check` for the files you want to check.

I am not sure we need to add yet another compiler option.

**Comment by brownbl1** [comment]
Understood.

**Comment by brownbl1** [comment]
Understood. Feel free to close this.

**Comment by aimergenge** [comment]
I have same problem. I have a file named `a.js` and I don't have any file that references the `a.js`. `a.js` is inserted in the html via `<script>`. I use `checkJs: true` to leverage power of ts but `a.js` has some code that won't pass the ts compiling so I use `exclude` to bypass it. However, it dosen't work, I still get errors from ts server.

**Comment by jkjustjoshing** [comment]
I have a JavaScript project with Jest testing that I want to enable `checkJs` on. I have `.spec.js` files next to my source files, and I need to ignore the Jest files since there are all sorts of type errors on them. 

The Jest files (which are excluded in `jsconfig.json` to no effect) import the source files, but not the other way around. Nothing that is being checked with `checkJs` should be importing the Jest files, so I don't see a reason why `exclude` shouldn't work for them.
