### ISSUE TITLE
Generate getter/setter for property already starting with  _

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#24155]
**TypeScript Version:**  2.9.0-dev.20180515

**Search Terms:** 
- refactor / refactoring
- generate get / getters, set / setters

**Code**

```ts
class Foo {
    private _prop: number
}
```

Run the `generate get and set accessors` refactoring on `_prop`

**Expected behavior:**
I think we should remove the `_` from the exposed property names in this case:

```ts
class Foo {
    private _prop: number;
    public get prop(): number {
        return this._prop;
    }
    public set prop(value: number) {
        this._prop = value;
    }
}
```

**Actual behavior:**
We tack on another `_` to the field and use `_prop` as the public names

```ts
class Foo {
    private __prop: number;
    public get _prop(): number {
        return this.__prop;
    }
    public set _prop(value: number) {
        this.__prop = value;
    }
}
```

**Comment by DanielRosenwasser** [comment]
Agreed, I think the behavior is a little backwards here.

**Comment by DanielRosenwasser** [comment]
CC @Kingwl 😄

**Comment by Kingwl** [comment]
@DanielRosenwasser maybe add another action called generate get and set accessors remove `_` ?

**Comment by DanielRosenwasser** [comment]
I think it's just a matter of doing the same thing for the code action, but in the case of an existing leading underscore, remove that from the name.
