### ISSUE TITLE
Discriminated parameters

### ISSUE THREAD

**Issue by KSXGitHub** [Microsoft/TypeScript#24159]
## Suggestion

In Node.js, there's some methods like `fs.readFile` that passes 2 parameters to callback function: `(err: Error | null, data: Buffer | null) => void`. If `err` is `null` then `data` is not `null` and vice versa. It would be extremely useful if we have some sort of discriminated parameters.

### As a callback

```typescript
// Callback function type which takes two sets of parameters
interface Callback<X, E = Error> { 
    (error: E): void
    (error: null, data: X): void
}

interface Buffer {}

declare function readFile(
    filename: string,
    callback: Callback<Buffer>
): void

// What I want to be able to do
readFile(
    'file.txt',
    (error, data) => { // TypeScript figures out parameters' type
        if (error === null) {
            const err: null = error
        } else {
            const err: Error = error
            const buf: Buffer = data
        }
    }
)
```

### As a function expression

```typescript
interface Fn<A, B> {
  (type: 'a', value: A): void
  (type: 'b', value: B): void
}

const fn: Fn<string, number> = (type, value) => {
  const T: 'a' | 'b' = type
  const X: string | number = value
  
  // TypeScript deduces types of `foo` and `bar` in each branch
  if (type === 'a') {
    const foo: 'a' = type
    const bar: string = value
  } else {
    const foo: 'b' = type
    const bar: number = value
  }
}
```

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by MartinJohns** [comment]
Isn't this already solved with function overloading?

**Comment by KSXGitHub** [comment]
@MartinJohns Please focus on `// What I want to be able to do`. The point is, I want TypeScript to be able to figure out type of `data` based on type/value of `error`.

**Comment by KSXGitHub** [comment]
Speaking of function overloading, TypeScript cannot does not deduce type of one parameter base on another parameter.

**Comment by mhegazy** [comment]
Looks like a duplicate/similar use case of https://github.com/Microsoft/TypeScript/issues/24085
