### ISSUE TITLE
WheelEvent constructor in lib.d.ts

### ISSUE THREAD

**Issue by bluong** [Microsoft/TypeScript#2416]
The WheelEvent constructor should be able to take in an initialized dictionary as described here
https://developer.mozilla.org/en-US/docs/Web/API/WheelEvent/WheelEvent

However, the lib.d.ts file does not have this constructor defined

**Comment by danquirk** [comment]
This part of lib.d.ts is automatically generated from IE's definitions and as you can see on that page IE doesn't support this, which is the cause here. We'll need to revisit this along with the other lib.d.ts bugs that are affected similarly.
