### ISSUE TITLE
Port lib files

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#24181]
@mhegazy No longer updated. Can you port and publish it to check it before the release of the next version? You've less than 2 weeks left before the release.

**Comment by mhegazy** [comment]
We are waiting on some legal issues to be resolved now that these are generated from whatwg/w3c which have their own licences..

**Comment by falsandtru** [comment]
So never reflects https://github.com/Microsoft/TSJS-lib-generator? Some fixes should be ported.

**Comment by mhegazy** [comment]
the current state bits in the master of https://github.com/Microsoft/TSJS-lib-generator is based on w3c and whatwg specs, and that needs some attribution before we use it.

We will not be porting anything until we have legal signoff on the generation process.

**Comment by falsandtru** [comment]
Any tracking issues about the legal issues?

**Comment by mhegazy** [comment]
i am afraid not. that is an internal MS process.

**Comment by falsandtru** [comment]
okay, thanks.
