### ISSUE TITLE
Unable to patch TypeScript class prototype without compiler errors

### ISSUE THREAD

**Issue by ashleydavis** [Microsoft/TypeScript#24189]
I've seen multiple other issues relating to this, I've been through them all and still can't solve the problem.

I'm trying to extend an interface and patch a class prototype that is defined in my TypeScript library [Data-Forge](https://github.com/data-forge/data-forge-ts). I can't seem to get past the compiler errors.

Maybe I'm just doing this wrong? Or there might be something wrong with TypeScript - a lot of other people seem to have trouble with this as well.

This is a really common technique for extending existing libraries in JavaScript and it would be a shame not to be able to use it in TypeScript. I really want to be able to write add-ons to Data-Forge and have them update the fluent API.

**TypeScript Version:**  2.5.2

**Search Terms:** TypeScript class extension, TypeScript prototype modification

**Code**

Minimal code example is available in this repo:
[https://github.com/ashleydavis/typescript-extension-test](https://github.com/ashleydavis/typescript-extension-test)

Example type script code here: https://github.com/ashleydavis/typescript-extension-test/tree/master/typescript

To run:
- Clone repo
- cd typescript
- npm install
- npm start

Equivalent JavaScript code here: 
https://github.com/ashleydavis/typescript-extension-test/tree/master/javascript

To run:
- Clone repo
- cd javascript
- npm install
- npm start

**Expected behavior:**

Should not have compile errors.

**Actual behavior:**

Has the following compile errors:

node_modules/data-forge/build/lib/dataframe.d.ts(869,22): error TS2420: Class 'DataFrame<IndexT, ValueT>' incorrectly implements interface 'IDataFrame<IndexT, ValueT>'.
  Property 'somePluginFunction' is missing in type 'DataFrame<IndexT, ValueT>'.
src/dataframe-plugin.ts(12,12): error TS2683: 'this' implicitly has type 'any' because it does not have a type annotation.
src/dataframe-plugin.ts(15,21): error TS2339: Property 'somePluginFunction' does not exist on type 'DataFrame<any, any>'.
src/index.ts(7,4): error TS2339: Property 'somePluginFunction' does not exist on type 'DataFrame<number, any>'.

**Comment by ashleydavis** [comment]
That worked. Thanks!

I don't really understand why though. IDataFrame is the interface and DataFrame is the class so it seems a bit weird to me. Can you explain why the class is modified instead of the interface?

Also not modifying the class (but not the interface) means that intellisense in VS Code is available for yhe class but not the interface, however I was easily able to fix by extending both the interface and the class as follows:

```ts
declare module "data-forge/build/lib/dataframe" {
    interface IDataFrame<IndexT, ValueT> {
        somePluginFunction (): IDataFrame<IndexT, ValueT>;
    }

    interface DataFrame<IndexT, ValueT> {
        somePluginFunction (): IDataFrame<IndexT, ValueT>;
    }
}
```

**Comment by andy-ms** [comment]
Yeah, extending an interface doesn't automatically make the class implement the new member.

**Comment by ashleydavis** [comment]
I'm still having a problem with this. While the initial help you gave me allowed me to get interface and class patching working within the same package, I have been unable to get this working across packages.

I've updated the example repo with the broken case: https://github.com/ashleydavis/typescript-extension-test

The library I'm patching is Data-Forge, installed via npm.

The patching is done via this code: [https://github.com/ashleydavis/typescript-extension-test/tree/master/typescript)](https://github.com/ashleydavis/typescript-extension-test/tree/master/typescript). 

It adds a new function to Data-Forge's `DataFrame` class called `somePluginFunction`.

It all works fine when I test it within [the same package](https://github.com/ashleydavis/typescript-extension-test/blob/master/typescript/src/index.ts).

But I can't get it work when the patching is done through an installed npm module.

As an example I published [the example code on npm](https://www.npmjs.com/package/typescript-extension-test). 

Then I created another example. This time I npm installed Data-Forge and typescript-extension-test.

The new and broken example can be found here:

[https://github.com/ashleydavis/typescript-extension-test/tree/master/example-package-usage](https://github.com/ashleydavis/typescript-extension-test/tree/master/example-package-usage)

**Comment by ashleydavis** [comment]
I've figured this out!

I needed to setup my dependencies as 'peer dependencies' in npm so that one package can patch another and be used by a 3rd package.

https://nodejs.org/en/blog/npm/peer-dependencies/
