### ISSUE TITLE
Type information lost after Pick on object with [key: string]: any;

### ISSUE THREAD

**Issue by evollu** [Microsoft/TypeScript#24185]
**TypeScript Version:**  2.8.3

**Search Terms:**  Pick

**Code**

```ts
type X = {
    [key: string]: any;
    x: string,
    y: string
}

type Y = Pick<X, keyof X>
```

**Expected behavior:** Y to be same as X

**Actual behavior:** Y = {[key: string]: any;}

**Playground Link:**  
https://www.typescriptlang.org/play/#src=type%20X%20%3D%20%7B%0D%0A%20%20%20%20%5Bkey%3A%20string%5D%3A%20any%3B%0D%0A%20%20%20%20x%3A%20string%2C%0D%0A%20%20%20%20y%3A%20string%0D%0A%7D%0D%0A%0D%0Atype%20Y%20%3D%20Pick%3CX%2C%20keyof%20X%3E
**Related Issues:** 
My use case is to make a required field optional in type X
```ts
type X = {
    [key: string]: any;
    x: string,
    y: string
    ....another 20 params
}

type Omit<T, K> = Pick<T, Exclude<keyof T, K>>; // this works for type without index type
type Y = Omit<X, "x"> & { x?: string}
// expect: x becomes optional and rest remain the same
// actual: y is removed
```

**Comment by evollu** [comment]
@Bnaya yes your solution works for my example. But this issue is causing a problem on Omit. I updated description with my original use case

**Comment by Bnaya** [comment]
Got it.
I've created this example to make it more clear
```ts
type X = {
    [key: string]: any;
    x: string;
    y: string;
}

type X3 = {
    x: string;
    y: string;
}

type Omit<T, TR extends keyof T> = {
    [K in Exclude<keyof T, TR>]: T[K];
};

/**
     Y2 = {
        [x: string]: any;
    }
 */
type Y2 = Omit<X, "x">;

/**
    type Y3 = { y: string; }
 */
type Y3 = Omit<X3, "x">;
```

https://www.typescriptlang.org/play/#src=type%20X%20%3D%20%7B%0D%0A%20%20%20%20%5Bkey%3A%20string%5D%3A%20any%3B%0D%0A%20%20%20%20x%3A%20string%3B%0D%0A%20%20%20%20y%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Atype%20X3%20%3D%20%7B%0D%0A%20%20%20%20x%3A%20string%3B%0D%0A%20%20%20%20y%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Atype%20Omit%3CT%2C%20TR%20extends%20keyof%20T%3E%20%3D%20%7B%0D%0A%20%20%20%20%5BK%20in%20Exclude%3Ckeyof%20T%2C%20TR%3E%5D%3A%20T%5BK%5D%3B%0D%0A%7D%3B%0D%0A%0D%0A%2F**%0D%0A%20%20%20%20%20Y2%20%3D%20%7B%0D%0A%20%20%20%20%20%20%20%20%5Bx%3A%20string%5D%3A%20any%3B%0D%0A%20%20%20%20%7D%0D%0A%20*%2F%0D%0Atype%20Y2%20%3D%20Omit%3CX%2C%20%22x%22%3E%3B%0D%0A%0D%0A%2F**%0D%0A%20%20%20%20type%20Y3%20%3D%20%7B%20y%3A%20string%3B%20%7D%0D%0A%20*%2F%0D%0Atype%20Y3%20%3D%20Omit%3CX3%2C%20%22x%22%3E%3B

**Comment by mhegazy** [comment]
The type has an index signature that allows it to have any string named property.. there are no way int eh language to define exclusion from infinite ranges, e.g. `string - "x"`.. that said, not sure what you expect from `Pick` rely..

**Comment by mhegazy** [comment]
`keyof X` is `string| number`. `string` subsumes all the other property names, "x"  and "y".

**Comment by mhegazy** [comment]
The compiler will try to keep the properties as long as it can, e.g. `Partial<X>` does have `x` and `y`. the issue is once you get `keyof`, which is a union, the `string` subsumes all the other property names, and you end up with only `string`. 
As i noted earlier, it does not make much sense to use operations like `Pick`, `Exclude` and `Omit` on a type like that. if you want to specify the types of properties other than `x`/`y` with the index signature, i think you are looking for https://github.com/Microsoft/TypeScript/issues/17867 instead.

**Comment by evollu** [comment]
will it make sense for `keyof` to return like `string|"x"|"y"` so the information will be kept?

my use case is to make one required field optional, which is common in React component with higher order components. The only solutions I can find is to use Extract which doesn't work here.
