### ISSUE TITLE
Arrow syntax support for accessor methods

### ISSUE THREAD

**Issue by Tom-Hudson** [Microsoft/TypeScript#24196]
## Search Terms
- get method arrow function
- set method arrow function
- accessor arrow functions

## Suggestion

It would be great if you could use an arrow function for an accessor method.

So instead of having to do this:
```typescript
class MyClass {
    settableProp: any;

    get accessorGetMethod() {
        return this.getMethod();
    }
 
    set accessorSetMethod(value: any) {
        this.setMethod(value);
    } 

    getMethod() {
        return this.settableProp;
    {

    setMethod(value: any) {
        this.settableProp = value;
    {
}
```

you can do this:
```typescript
class MyClass {
    settableProp: any;

    get accessorGetMethod = () = this.getMethod();
    set accessorSetMethod = value => this.setMethod(value);

    getMethod() {
        return this.settableProp;
    {

    setMethod(value: any) {
        this.settableProp = value;
    {
}
```

## Checklist

My suggestion meets these guidelines:
* [ ] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by andy-ms** [comment]
It's out of scope of the [design goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals) to change JavaScript as a language.
