### ISSUE TITLE
Unsupported file encoding

### ISSUE THREAD

**Issue by franksoong** [Microsoft/TypeScript#2420]
Hi, i have a typescript file which provide string translations for Italian in my solution, when i compile the solution, i got follow compile errors:

Severity	Code	Description	Project	File	Line
Error		Build: Cannot read file 'D:/workdir/devunits/song_cordova20150227_dev/src/cordova/scripts/app/I18N/it-IT/Strings.ts': Unsupported file encoding.

Env and Tools i used:
VS2015 CTP5 (incl. TS 1.4), Cordova project.

Here is the content of cordova/scripts/app/I18N/it-IT/Strings.ts: 

"use strict";
export var Strings = {
    MsgMarkUpShareFailed: "Impossibile condividere i markup in OneNote",
    Erase: "Cancella",
    TextForSelectJTFolder: "Selezionare la cartella JT suddivisa",
    Error_Printing: "Errore durante la stampa del modello",
    SharedFileNotFoundExceptionMessage: "Impossibile trovare il file richiesto in OneDrive. Verificare con gli utenti che condividono il file che siano state accordate le necessarie autorizzazioni.",
    Property_LastAuthor: "Ultimo autore",
    OpenInJT2Go: "Apri in JT2Go",
    ShowPMI: "Mostra PMI",
    Share: "Condividi",
    MsgBedDepth: "La  profondità deve essere maggiore di 0.",
    Cancel: "Annulla",
    Error_NonPositiveVolume: "Stampa interrotta. Il modello non ha un volume positivo",
    Dimensions: "Quote",
    DrillUp: "Drill up",
    MsgBedHeight: "L'altezza deve essere maggiore di 0.",
    Property: "Proprietà",
    Note: "Nota",
    MsgPLMXMLWasModified: "Il markup è stato modificato e deve essere salvato. Salvarlo ora?",
    Loading: "Caricamento",
    Created: "creato",
    Property_Parts: "Parti",
    OrientTo: "Orienta verso",
    DrillDown: "Drill down",
    Section: "Sezione: ",
    Samples: "Campioni",
    Print: "Stampa",
    Property_ProjectName: "Nome progetto",
    AlignToView: "Allinea a vista",
    TakeImage: "Scegli immagine",
    ToLast: "Vai all'ultimo",
    Property_Density: "Densità",
    DFS: "Simboli feature Datum",
    Default: "Predefinita",
    MsgPLMXMLNotMatchJTError: "Questo file plmxml non corrisponde al file jt attualmente aperto. Selezionare il file corretto e riportare.",
    MsgFailedCreateHomePage: "Errore durante la creazione della pagina iniziale.",
    Snapshot: "Istantanea",
    BedHeight: "Altezza (mm)",
    PinToStart: "Aggancia all'avvio",
    Property_Unit: "Unità",
    PrintBedDepth: "Profondità",
    SelectionColor: "Finestra dei colori",
    Home: "Pagina iniziale",
    Pan: "Sposta",
    Text: "Caricatore di testo",
    Property_DocumentNumber: "Nr. documento",
    MsgBedWidth: "Lo spessore deve essere maggiore di 0.",
    TextForSelectJT: "Selezionare un file JT",
    Properties: "Proprietà",
    DefaultMarkupItemDescription: "Commenti senza titolo",
    Property_TranslationDate: "Data conversione",
    FinishPrinting: "Dati inviati alla stampante 3D",
    FCF: "Fotogrammi controllo feature",
    Error_InvalidModel: "Stampa interrotta. Il modello non è definito correttamente",
    Property_Company: "Azienda",
    General: "Generale",
    PMIFilters: "Filtri PMI",
    MeasurementPoints: "Punti di misurazione",
    Save: "Salva",
    Open: "Apri",
    ChooseImage: "Scegli immagine",
    Property_NameOfSavingApplication: "Nome dell'applicazione da salvare",
    BedWidth: "Larghezza (mm)",
    Other: "Altro",
    OneDriveLoadMarkupExceptionMessage: "Errore durante l'apertura del markup da OneDrive",
    SettingLanguage: "Lingua",
    DatumTargets: "Destinazioni datum",
    SpotWelds: "Punti di unione",
    StartPrinting: "Stampa iniziata. L'operazione potrebbe richiedere alcuni minuti",
    HidePMI: "Nascondi PMI",
    ShareToOneNote: "Condividi in OneNote",
    Accept: "Accetta",
    Less: "Meno",
    More: "Altro",
    Property_CADSource: "Origine CAD",
    PMIPanelState: "Selezionare i tipi PMI da visualizzare",
    SelectAll: "Seleziona tutto",
    MsgGreaterThan: "{0} deve essere maggiore di 0.",
    ToggleCamera: "Attiva/Disattiva  videocamera",
    CollapseBar: "Comprimi barra",
    Normal: "Normale",
    DeleteView: "Elimina vista",
    Error_NonManifold: "Stampa interrotta. Il modello non è impermeabile",
    OneDriveAuthenticationExceptionMessage: "Errore durante il caricamento del file richiesto perché le credenziali di autenticazione presentano un'anomalia per quanto riguarda la connessione a OneDrive.",
    LanguageTag: "it-IT",
    Property_LastSaveDate: "Data ultimo salvataggio",
    Property_TriangleCount: "Numero di triangoli",
    AppDescription: "Un'applicazione di rendering 3D per la visualizzazione di file di formato JT.",
    View: "Vista",
    Property_Keywords: "Parole chiave",
    LoadFile: "Carica",
    EditDescription: "Modifica descrizione",
    ShowAllPMI: "Mostra tutte le informazioni PMI",
    BedDepth: "Spessore (mm)",
    Delete: "Elimina",
    Property_ApplicationName: "Nome applicazione",
    FullScreen: "Schermo intero",
    Error_LoadPart: "Impossibile aprire il file JT specificato",
    ModelView: "Vista modello",
    Fit: "Adatta",
    SharingStatus: "Condivisione",
    LoadingStatus: "Caricamento",
    RestoreDefaults: "Ripristina i default",
    ExceedPrintableAreaMessage: "Il modello supera l'area stampabile",
    HideAllPMI: "Nascondi tutte le informazioni PMI",
    Recent: "Recente",
    TextForSelectImage: "Seleziona un file di immagine",
    Error: "Errore",
    Property_Geometry: "Geometria",
    Locators: "Localizzatori",
    OneDriveLoginExceptionMessage: "Impossibile eseguire l'accesso a OneDrive",
    Property_Comments: "Commenti",
    Property_Category: "Categoria",
    Property_Attribute: "Attributo",
    Settings: "Impostazioni",
    Spin: "Rotazione",
    Hide: "Nascondi",
    Freehand: "A mano libera",
    PrintBedWidth: "Larghezza",
    Attribute: "Attributo",
    Property_TranslatorVersion: "Versione convertitore",
    Reset: "Ripristina",
    Options: "Opzioni",
    Surface: "Superficie",
    BackgroundColor: "Colore sfondo",
    ViewType: "Visualizza tipo",
    Property_VertexCount: "Numero di vertici",
    LoadFileExceptionMessage: "Si è verificato un errore durante il caricamento del file.",
    Status_Pinned_Success: "JT2Go è agganciato allo schermo iniziale",
    Property_Length: "Lunghezza",
    FontFamily: "Segoe UI",
    Property_Subject: "Oggetto",
    PMIColor: "Colore PMI",
    PartLoaderExceptionMessage: "Si è verificato un errore durante il caricamento del file JT specificato.",
    Property_Author: "Autore",
    MsgMarkUpShareSuccessed: "Markup condivisi correttamente in OneNote",
    ClearAll: "Cancella tutto",
    Property_OriginationDate: "Data di origine",
    OneDriveConnectionExceptionMessage: "Errore durante il caricamento del file richiesto causato dalla connessione OneDrive.",
    MsgExpectedNumber: "{0} deve essere un numero.",
    Part: "Parte",
    Status_Pinned_Failure: "Errore durante l'aggancio di JT2GO alla schermata iniziale",
    LiveCamera: "Videocamera live",
    Legal: "Legale",
    Property_Name: "Nome",
    Property_Width: "Larghezza",
    Discard: "Elimina",
    Decline: "Calo",
    MsgFailedCreateLicensePage: "Errore durante la creazione della pagina di licenze.",
    Geometry: "Geometria",
    ShowAllParts: "Mostra tutte le parti",
    Property_Material: "Materiale",
    ToFirst: "Vai al primo",
    ShatteredFolderIncorrectExceptionMessage: "Si è verificato un problema durante il caricamento della cartella suddivisa. Verificare di aver selezionato la cartella esatta.",
    PrivacyPolicy: "Criteri sulla privacy",
    PrintBedHeight: "Altezza",
    Property_Title: "Titolo",
    WaitingStatus: "Attesa",
    Background: "Sfondo",
    CoordinateSystems: "Sistemi di coordinate",
    Property_Height: "Altezza",
    Structure: "Struttura",
    DefaultMarkupItemDescriptionWithUserName: "Commenti di {0}",
    Default3DPrinter: "Stampante 3D predefinita",
    Help: "Guida"
}

**Comment by mhegazy** [comment]
The compiler does not support ANSI encoding, which i am guessing the encoding for this file. so you need to save the file in Unicode, to do that, in VS go to file\Advanced Save Options, select "Unicode (UTF-8 with Signature)" and hit ok. save your file and try again.

**Comment by franksoong** [comment]
this fix my issue, much thanks for the tips!!
