### ISSUE TITLE
Adding class to internal namespace?

### ISSUE THREAD

**Issue by Paxa** [Microsoft/TypeScript#24219]
I'm defining a class in namespace and want to extend it in other file, how can I do it?

**foo.d.ts**:
```ts
/// <reference types="node" />

import stream = require("stream");

declare module foo {
   class A { }
}
```

**foo_ext.d.ts**:
```ts
/// <reference path="./foo.d.ts" />

declare module foo {
  class A1 extends A { }
}
```

Result:
```
foo_ext.d.ts (4,20): Cannot find name 'A'.
```

**Comment by mhegazy** [comment]
Modules, i.e. files with at last one top-level `import`/`export`, have their own scope. `foo.d.ts::foo` is not visible outside this file, and thus you can not merge with it.

**Comment by Paxa** [comment]
Is it possible to use `import/export` and keep things easy? (it's very confusing behavior because changing require to import in nodejs doesn't have side effects, and we still able to set global variables via `global.foo = foo`)

Is it possible to add visible things in namespace when using `import/export`?

**Comment by mhegazy** [comment]
you can either put the declarartion in the global scope:

```ts
import stream = require("stream");

declare global {
    namespace foo {
          class A { }
    }
}
```

or export it and "augment" it later:

```ts
// foo.d.ts:
import stream = require("stream");

export declare module foo {
   class A { }
}
```

```ts
// foo_ext.d.ts:
declare module "foo" {
    namespace foo {
        class A1 extends A { }
    }
}

```

**Comment by RyanCavanaugh** [comment]
@Paxa see als ohttps://stackoverflow.com/questions/30357634/how-do-i-use-namespaces-with-typescript-external-modules

**Comment by Paxa** [comment]
Thank you @mhegazy it worked
