### ISSUE TITLE
Bad error message for enum initializers

### ISSUE THREAD

**Issue by orzFly** [microsoft/TypeScript#24210]
**TypeScript Version:**  typescript@2.9.0-dev.20180516

**Search Terms:** enum infinity, TS2553, enum undefined

<hr>

**Code 1**

```ts
enum TestEnum {
  "undefined" = undefined,
}
```

**Expected behavior:** No string valued member at all. Maybe the error message is wrong.

**Actual behavior:**
```
xxx.ts:2:17 - error TS2553: Computed values are not permitted in an enum with string valued members.

2   "undefined" = undefined,
                   ~~~~~~~~~
```
What does the 0 mean?
```js
var TestEnum;
(function (TestEnum) {
    TestEnum[TestEnum["undefined"] = 0] = "undefined";
})(TestEnum || (TestEnum = {}));
```
**Playground Link:** [here](https://www.typescriptlang.org/play/#src=enum%20TestEnum%20%7B%0D%0A%20%20%22undefined%22%20%3D%20undefined%2C%0D%0A%7D)

<hr>

**Code 2**

```ts
enum TestEnum {
  "undefined" = undefined,
  "NaN" = NaN,
  "Infinity" = Infinity,
  "-Infinity" = -Infinity,
}
```

**Expected behavior:** Maybe?
```js
var TestEnum;
(function (TestEnum) {
    TestEnum[TestEnum["undefined"] = undefined] = "undefined";
    TestEnum[TestEnum["NaN"] = NaN] = "NaN";
    TestEnum[TestEnum["Infinity"] = Infinity] = "Infinity";
    TestEnum[TestEnum["-Infinity"] = -Infinity] = "-Infinity";
})(TestEnum || (TestEnum = {}));
```

**Actual behavior:** No error at all!
So what's `TestEnum.undefined`, `TestEnum.NaN`, `TestEnum.Infinity`, `-TestEnum.Infinity`?
```js
var TestEnum;
(function (TestEnum) {
    TestEnum[TestEnum["undefined"] = TestEnum.undefined] = "undefined";
    TestEnum[TestEnum["NaN"] = TestEnum.NaN] = "NaN";
    TestEnum[TestEnum["Infinity"] = TestEnum.Infinity] = "Infinity";
    TestEnum[TestEnum["-Infinity"] = -TestEnum.Infinity] = "-Infinity";
})(TestEnum || (TestEnum = {}));
```

**Playground Link:** [here](https://www.typescriptlang.org/play/#src=enum%20TestEnum%20%7B%0D%0A%20%20%22undefined%22%20%3D%20undefined%2C%0D%0A%20%20%22NaN%22%20%3D%20NaN%2C%0D%0A%20%20%22Infinity%22%20%3D%20Infinity%2C%0D%0A%20%20%22-Infinity%22%20%3D%20-Infinity%2C%0D%0A%7D)

<hr>

**Related Issues:**
Issue #21959: "It is a compile time error for constant enum expressions to be evaluated to NaN or Infinity."
PR #22022: "disallow nan and infinity in enum member" is made for the previous issue

I think this is not duplicated as #21959 and #22022 are talking about making undefined/NaN/Infinity an error in const enum instead of making them generate correct code in non-const enum.

> We only want this error for const enums (enums with a const modifier, I mean), not all enums.
> - https://github.com/Microsoft/TypeScript/pull/22022#issuecomment-379013898

**Comment by DanielRosenwasser** [comment]
Yeah this is a terrible and broad error message when complex non-numeric expressions are used in initializers and it needs to be fixed.

**Comment by orzFly** [comment]
Note in the second code snippet:
```js
TestEnum[TestEnum["undefined"] = TestEnum.undefined] = "undefined";
```
`TestEnum.undefined` is wrong. It should be `undefined`

**Comment by JaimeRodriguez96** [comment]
Hi! Its fixed yet?

**Comment by aminpaks** [comment]
> Yeah this is a terrible and broad error message when complex non-numeric expressions are used in initializers and it needs to be fixed.

What should the fix look like?
I fixed it by making a new error as in "'null' or 'undefined' cannot be an enum value member", is that the behaviour that we would want?

**Comment by jakebailey** [comment]
After #50528 in TS 5.0, this bad error message is no longer present; the only error on the first code sample is:

> Property '"undefined"' is used before being assigned.(2565)

![image](https://github.com/microsoft/TypeScript/assets/5341706/332433ec-80e6-4f4a-a336-e0bd820b84c1)

Which makes sense, given it's self-referencing and the hover shows that.

TS 3.9 fixed the second example case; the correct error now appears.
