### ISSUE TITLE
How to manage dependencies with conflicting type declarations?

### ISSUE THREAD

**Issue by micahblu** [Microsoft/TypeScript#24229]
I have already posted this issue in [Stackoverflow](https://stackoverflow.com/questions/50261391/typescript-how-to-manage-dependencies-with-conflicting-type-declarations?noredirect=1#comment87541206_50261391) but no one has any idea apparently on how to address this. I would consider this a concern of the Typescript project since they should have some idea or opinion on how to prevent such issues:

I have the error: `Subsequent variable declarations must have the same type`

This is occurring because two of my dependencies, both of which I need; declare the same type.

**Jest** :`/node_modules/@types/jest/index.d.ts` => `declare var test: jest.`

**testcafe** `node_modules/testcafe//ts-defs/index.d.ts` => `declare var test: TestFn;`

My project is a react/redux project using webpack, babel and obviously Typescript.

The error occurs when I am running my dev server via `npm start` which uses `webpack-dev-server`. It also creates a problem when I run `jest` since it uses testcafe's version of the declared `Test` type.

How can this be resolved?

**Comment by RyanCavanaugh** [comment]
Exclude one or the other files from your compilation, or update the declaration files to not both claim to be stomping on the same global variable. That's it.

**Comment by RyanCavanaugh** [comment]
See also https://github.com/DevExpress/testcafe/issues/1537

**Comment by micahblu** [comment]
@RyanCavanaugh Thanks appreciate the testcafe issue reference. The issue though is that I don't have the files configured in my webpack configuration. It appears typescript is on its own accord looking at every dependency in my package.json, looking for declaration files and throwing errors on any type declaration collisions. What is really strange is that I even have in my .tsconfig:  `"exclude": [ "node_modules"]`? So to sum: neither Jest nor Testcafe are configured in the build process nor the dev configuration, they run independently and the thrown error occurs even when they're not even running?
