### ISSUE TITLE
Error list and quick info are not consistent with alias display behavior

### ISSUE THREAD

**Issue by JsonFreeman** [Microsoft/TypeScript#2423]
```ts
module M1 {
    export function foo(x: IFoo) { }
    export interface IFoo {
        x;
    }
}

module M2 {
    interface IFoo {
        y;
    }
    import alias = M1;
    var ifoo2: IFoo;
    alias.foo(ifoo2);
}
```

The call to alias.foo is an error. Hovering on the error shows me the following:
>Argument of type 'IFoo' is not assignable to parameter of type 'M1.IFoo'.
Property 'x' is missing in type 'IFoo'.

Note that the parameter type is called `M1.Foo`. However, hovering on `foo` in the expression `alias.foo(ifoo2)` shows me that the parameter type is `alias.IFoo`. So the parameter type in quick info is not consistent with the parameter type in the error.

![aliasinquickinfo](https://cloud.githubusercontent.com/assets/8052525/6723305/48bb56c6-cda3-11e4-9f6f-fb006bdcb6d5.gif)

**Comment by mhegazy** [comment]
Alias and M are senanomus, where ideally they should be the same, I am not sure this warrants a fix.

**Comment by JsonFreeman** [comment]
Okay
