### ISSUE TITLE
error TS2554: Expected 2-3 arguments, but got 1

### ISSUE THREAD

**Issue by shamhub** [Microsoft/TypeScript#24239]
With given `tsconfig.json`,

    {
       
        "compilerOptions": {
       
          "lib": ["es2015", "dom"]
        },
        "files": [
          "./project1/tstut.ts",
          "./project1/worker.ts"
    
        ]
      }

---------------------

For below worker code(`./project1/worker.ts`), 

```

    window.addEventListener('message', (e) => {
        // console.log(e)
        if(e.data === 'do some work'){
            console.log('Worker is about to start some work');
            let count: number =0;
            for(let i: number=0; i<1000; i++){
                count += i;
            }
            window.postMessage({message:count});
        }
    
    })
```

Instead of `self`, `window` object is used in TS worker code. JS allows syntax `self.postMessage({message: count})`

How to resolve below error for `postMessage()`?

`    Expecting 2-3 arguments, but got 1`

**Comment by shamhub** [comment]
@andy-ms  Code is on https://shamhub.github.io/   you can see webworker example there
Do I need to mention second argument as "https://shamhub.github.io/" or "https://shamhub.github.io/project1"?

**Comment by andy-ms** [comment]
I don't know, but it doesn't seem like this is a compiler bug, may be look for a help forum somewhere?

**Comment by Ajyress** [comment]
Hello,
I have got the exact same issue. The error appears on the line postMessage() call while compiling a WebWorker.ts file in Angular 6. There is no error on the browser side though, the WebWorker works as expected.
Any help would be appreciated. Regards

**Comment by shamhub** [comment]
https://stackoverflow.com/questions/50402004/error-ts2554-expected-2-3-arguments-but-got-1

**Comment by Bandito11** [comment]
It's 2019 and I still get the error. The compiler is confusing the one of the web worker object with the one of the window object.

**Comment by zzt1224** [comment]
2020, still.

**Comment by ibraheemhlaiyil** [comment]
May 2020, still.

**Comment by 2000Vlad** [comment]
June 2020 still get the error

**Comment by dullbananas** [comment]
July 2020, found this on google

**Comment by flyce** [comment]
Nov 2020, still

**Comment by olsen4930824** [comment]
2021 Feb still, Nice

**Comment by RyanCavanaugh** [comment]
Please read this https://stackoverflow.com/a/50420456/1704166 instead of noting the current date.
