### ISSUE TITLE
TS2339 errors in express-validator

### ISSUE THREAD

**Issue by teamzone** [Microsoft/TypeScript#2424]
Hello,

The compiler it producing errors such as this:

Error TS2339: Property 'checkBody' does not exist on type 'Request'

I have the typings referenced so i don't think this is the issue.  I notice that the typing file for express-validator does not contain this.  I'm not sure or don't know enough to be confident to change this.

This sort of error seems to be related to dynamically adding types.  The express validator does this to the request object.  I have some of my own code which does this as well to the node session type.  How can we tell the compiler that this is ok?

Regards,

Nick

**Comment by mhegazy** [comment]
I will need more information, preferably code snippet, of what you are trying to do.

**Comment by teamzone** [comment]
Does this help?

    post = (req: express.Request, res: express.Response) => {
    
        req.checkBody('password', 'Password is required').notEmpty();
        req.checkBody('password', 'Password length needs to be at least 8 characters').len(8);
        req.checkBody('email', 'Email is required').notEmpty();
        req.checkBody('email', 'Email does not appear to be valid').isEmail();

**Comment by DanielRosenwasser** [comment]
> I notice that the typing file for express-validator does not contain this.

That's probably the issue. I can confirm that [the typings for express-validator](https://github.com/borisyankov/DefinitelyTyped/blob/master/express-validator/express-validator.d.ts) don't contain checkBody whereas [the library itself does define it](https://github.com/ctavan/express-validator/blob/1fa03dadc39071317e1fa7cb51ff1cacb7c3c815/lib/express_validator.js#L183). You'll want to file an issue on [DefinitelyTyped](https://github.com/borisyankov/DefinitelyTyped).

> I'm not sure or don't know enough to be confident to change this.

Sounds like a great opportunity to learn. :smile:

**Comment by teamzone** [comment]
Ok sure I could do it.  What about my own dynamically added types e.g.

                req.session.authenticated = true;
                req.session.user = { email: email };

How do I tell typescript that it's Ok

**Comment by DanielRosenwasser** [comment]
So let me preface this by saying that I have no idea how the `express-validator` library is to be used. There seems to be nothing that actually uses *nor* produces the `RequestValidation` type, so I'm inclined to say that the library is especially wrong. I'll try to give some general advice from my understanding of `express` anyhow.
_____

By adding definitions of an interface, those definitions will *merge* and you can expand the number of properties that an interface describes. For example:

```TypeScript
module m {
	export interface I {
		a: number;
	}
}

module m {
	export interface I {
		b: string
	}
}

var x: m.I;
```

in this example, `x` has the fields `a` and `b`.

Similarly, you can extend the `Request` interface in `express` using declaration merging:

```TypeScript
/// <reference path="express.d.ts" />

declare module Express {
    export interface Session {
        authenticated: boolean;
        user: { email: string };
    }

    export interface Request {
        session: Session;
    }
} 
```

In fact, if you [look at the `express` typings themselves](https://github.com/borisyankov/DefinitelyTyped/blob/29ebb788d04c3acbb521ac1e69754a4bad9c5885/express/express.d.ts#L17), you'll see that this is what you're encouraged do to, and are encouraged to take a look at [an example of doing so in the method-override typings](https://github.com/borisyankov/DefinitelyTyped/blob/master/method-override/method-override.d.ts).

**Comment by teamzone** [comment]
Thanks for code sample Daniel.  I will try it out.

As for express-validator, that leaves me with a dilemma.  It's a popular library it seems.  Having a clean build is important as well and this sort of failure invites bad practice in this process if I end up ignoring it.  A slippery slope.

**Comment by danquirk** [comment]
Fix the library definitions so they're correct and your code has no errors. Then submit the fix to DefinitelyTyped. Everyone wins :)

**Comment by damienpontifex** [comment]
For those coming across this as I did, express-validator extends the express.Request with ValidatedRequest as such `export interface ValidatedRequest extends express.Request, RequestValidation`

Thus the express callback function parameters become `(req: ValidatedRequest, res: express.Response) ⇒ {`
