### ISSUE TITLE
error TS6133   ...  "is declared but its value is never read."

### ISSUE THREAD

**Issue by dgofman-equinix** [Microsoft/TypeScript#24249]
I am using D3 and all callback functions should receiving 3 parameters.
"ValueFn<GElement, Datum, void>"

I defined my event listeners as 

```
on("mouseover", (d: any, index: number, elems: SVGGElement[]): void => {
   d3.select(elems[index]);
}) 
```

When I compiling to JS file and running via LINT/JSHINT no errors, however by enabling in tsconfig.json 
"noUnusedParameters": true

I am getting errors: "error TS6133: 'd' is declared but its value is never read."

"d" is first argument you cannot avoid it. So, why TS compiler so crazy and cannot recognize it?

**Comment by andy-ms** [comment]
Prefix the parameter with an underscore, as in `_d`.

**Comment by massimonewsuk** [comment]
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#flag-unused-declarations-with---nounusedparameters-and---nounusedlocals

**Comment by dgofman-equinix** [comment]
Why do we need that?

**Comment by MartinJohns** [comment]
@dgofman-equinix You enable a feature that will error on unused parameters, then complain that it errors about unused parameters?

**Comment by RyanCavanaugh** [comment]
It's `--noUnusedParameters`, not `--noUnusedNonleadingParameters`. Lots of options available to you and it's not a bug that we literally do the thing the flag is called.

**Comment by RyanCavanaugh** [comment]
Prior discussion at #9458
