### ISSUE TITLE
Change type definition of Object.keys and for..in loop

### ISSUE THREAD

**Issue by Austaras** [Microsoft/TypeScript#24243]
## Search Terms

Object.keys, index signature

## Suggestion

Currently the definition of Object.keys in lib.d.ts is 

`keys(o: {}): string[];`

why not change to 

`keys<T extends Object>(o: T):  Array<keyof T>`

and accordingly change for ... in loop

## Use Cases

It is ridiculous that code like
`const a = {}`
`Object.keys(a).forEach(key => a[key])`
will raise a 'has no index signature' error

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by ducin** [comment]
Yep, that works out of the box:
```
const getKeys = <T extends {}>(o: T): Array<keyof T> => <Array<keyof T>>Object.keys(o)
var keys = getKeys({ first: "John", last: "Lennon" }) // => ("first" | "last")[]
```
