### ISSUE TITLE
The 'control' member is missing in definition of HTMLLabelElement in lib.es6.d.ts

### ISSUE THREAD

**Issue by maxzz** [Microsoft/TypeScript#24242]
According to definition on MDN [HTMLLabelElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLLabelElement/control) should have a member called 'control', but this definition is missing in lib.es6.d.ts.

**Comment by a-tarasyuk** [comment]
@maxzz It exists in [lib.dom.d.ts#L6460](https://github.com/Microsoft/TypeScript/blob/master/lib/lib.dom.d.ts#L6460)

```typescript

interface HTMLLabelElement extends HTMLElement {
    readonly control: HTMLInputElement | null;
    ....
}

```

**Comment by maxzz** [comment]
I think I faced this problem due to the Visual Studio version that I'm using. It's VS 2015 and the definitions are acquired from "Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TypeScript". So far, I'm simply casting element to type 'any' and getting access to the control member, but switching to VS 2017 will solve the problem.

Thanks,
