### ISSUE TITLE
Data type error

### ISSUE THREAD

**Issue by zfocus** [Microsoft/TypeScript#24246]
url :   http://localhost:4200/product/5

router:  { path: 'products/:id', component: ProductDetailComponent }

![image](https://user-images.githubusercontent.com/24307545/40227195-6634e50c-5ac0-11e8-894e-5317e571d0b8.png)

![image](https://user-images.githubusercontent.com/24307545/40227158-4d59171a-5ac0-11e8-8849-80fb28db6354.png)

**Comment by MartinJohns** [comment]
TypeScript only ensures type-safety at compile-time, but `console.log(typeof id);` returns the type as it is during compilation time. Somewhere in your code you have a mix-up on your types.

The `params` property of Angular (which you seem to use) has the following type: `{ [key: string]: any }`. `any` is a special type without any type-safety, the compiler can't ensure anything. `any` is implicitly assignable to any type, including `number`. When you use `any`, then you're responsible for ensuring that the types match what you expect. In this case `params['id']` returns a string at runtime, but you wrongly pass it to a function accepting a `number`.
