### ISSUE TITLE
Intellisense error when using clone function.

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#24253]
_From @MicahZoltu on May 18, 2018 15:0_

- VSCode Version: 1.23.1
- OS Version: Windows 10

Steps to Reproduce:
```
class Foo {
	clone() { return new Foo() }
}

class Bar {
	/** @param {Foo} foo */
	constructor(foo) {
		this.foo = foo
		this.foo = this.foo.clone()
	}
}
```

Intellisense thinks the type of `this.foo` is `any`.  If you remove the line `this.foo = this.foo.clone()` or change it to `this.foo = foo.clone()` intellisense correctly detects the type for `this.foo`.

I _suspect_ the issue is that when intellisense is doing its first pass to determine the type of `this.foo` it assumes `this.foo` is `any` during evaluation.  This results in it detecting that `this.foo` is being assigned to `any.clone()` which of course returns `any`.

Does this issue occur when all extensions are disabled?: Yes/No
Yes.

----

Workaround for future readers, you can annotate the type of `this.foo` explicitly with `/** @type Foo */`.

_Copied from original issue: Microsoft/vscode#50111_

**Comment by mjbvz** [comment]
_From @vscodebot[bot] on May 18, 2018 15:0_

(Experimental duplicate detection)
Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
- [onDebugInitialConfigurations activates very eager. (#39696)](https://www.github.com/Microsoft/vscode/issues/39696) 
- [No IntelliSense for default export of static member in TypeScript. (#46450)](https://www.github.com/Microsoft/vscode/issues/46450) 
- [Terminal: can't call `#sendText` with a long text (#38137)](https://www.github.com/Microsoft/vscode/issues/38137)

**Comment by mjbvz** [comment]
_From @MicahZoltu on May 18, 2018 15:2_

It would seem my choice of the variable name `foo` triggered the dupe bot.  Next time I'll use more obscure names.  😛

**Comment by mhegazy** [comment]
@MicahZoltu your analysis is correct. the compiler considers the assignments to `this.foo` as declarations. trying to figure out what the type of `this.foo` is, it ends up asking what the type of `this.foo.clone()` is, which in tern requires the type of `this.foo` again. the compiler breaks these cycles by using an `any` as the type.

you can add a type annotation on `this.foo` to help guide the compiler understand the intended type:
```ts
class Bar {
    /** @param {Foo} foo */
    constructor(foo) {
        /** @type {Foo} */
        this.foo = foo;
        this.foo = this.foo.clone();
