### ISSUE TITLE
JS Class expression with js-valued return type methods cause duplicated errors

### ISSUE THREAD

**Issue by weswigham** [Microsoft/TypeScript#24252]
Found in #24247

**TypeScript Version:**  2.9.0-dev.201xxxxx

**Search Terms:** 

**Code**

```ts
// @ts-check
var A = {};
A.B = {};
A.B.C = [
    {
        o: "no",
        y: 42
    }
];

A.Foo = class {
    /**
     * @returns {?A}
     */
    foo() {
        return A.B.C.find(x => !!x);
    }
}
```

**Expected behavior:**
![image](https://user-images.githubusercontent.com/2932786/40250880-89cb96fc-5a8c-11e8-93de-0d9008d63d22.png)

**Actual behavior:**
![image](https://user-images.githubusercontent.com/2932786/40250888-91409d56-5a8c-11e8-9cd9-a8fe2131033c.png)
(2 errors instead of 1 - one without elaboration)
In trying to edit this down further, I've found that removing the nested namespace on `B` seems to remove the bug, as does changing the return type of `foo` to not reference `A`, or changing from a class to an object literal for `A.Foo` - so it seems a great deal of things must be kept in place to reproduce this error.

**Comment by sandersn** [comment]
I can't get this to repro anymore, but the dupes are still in the chrome-devtools-frontend baselines. Looks like I might need to re-isolate this one.

**Comment by sandersn** [comment]
Here's a smaller repro:

```js
var A = {};
A.B = class {
    /**
     * @return {any[]}
     */
    m() {
        return {};
    }
};
```

**Comment by sandersn** [comment]
Could be that we're double-checking methods here. Anything with elaborations gets double errors:

```js
var A = {};
A.B = class {
    m() {
        /** @type {string[]} */
        var x = [];
        /** @type {number[]} */
        var y;
        y = x;
    }
};
```

From a quick debugging run-through, it looks like deferredNodes gets the same node pushed onto it twice.
