### ISSUE TITLE
enum.toString() shouldn't compile to {int}.toString()

### ISSUE THREAD

**Issue by wizofaus** [Microsoft/TypeScript#2425]
In C# I can get the string name of an enum just by doing, e.g. Color.Red.toString(). But in TypeScript this compiles to, e.g. 0.toString() which is almost certainly not what's intended.

**Comment by basarat** [comment]
Don't use toString : http://stackoverflow.com/a/17381004/390330

**Comment by wizofaus** [comment]
Yes but that assumes you have the js file holding the Enum loaded. My enum definitions are from a .d.ts file generated by another tool.

**Comment by basarat** [comment]
> .d.ts file generated by another tool

If its generated from a `.ts` file then the `.js` will contain the same semantics
