### ISSUE TITLE
Generics cause assignable check to fail

### ISSUE THREAD

**Issue by AnyhowStep** [Microsoft/TypeScript#24268]
**TypeScript Version:**  Version 2.9.0-dev.20180516

**Search Terms:** 

generic assignable fail

**Code**

```ts
type UnionNested<T> = {
    [k in keyof T]: {
        [n in keyof T[k]]: T[k][n]
    }[keyof T[k]]
}[keyof T];

declare const okay: {
    a: {
        field0: number
    },
    b: {
        field1: boolean;
    }
};
const okayUnionNested0: UnionNested<typeof okay> = 3;
const okayUnionNested1: UnionNested<typeof okay> = true;

const nonGeneric: UnionNested<{ c: { field2: string } }> = "test";

function generic<T extends { c: { field2: string } }>(t: T) {
    //Error: not asssignable
    const errorUnionNested: UnionNested<T> = "test";
}
```

**Expected behavior:**

Assignment should work.

**Actual behavior:**

```
Type '"test"' is not assignable to type '{ [k in keyof T]: { [n in keyof T[k]]: T[k][n]; }[keyof T[k]]; }[keyof T]'.
  Type '"test"' is not assignable to type '{ [n in keyof T[keyof T]]: T[keyof T][n]; }[keyof T[keyof T]]'.
    Type '"test"' is not assignable to type 'T[keyof T][keyof T[keyof T]]'.
```

**Playground Link:** [Here](http://www.typescriptlang.org/play/#src=type%20UnionNested%3CT%3E%20%3D%20%7B%0D%0A%20%20%20%20%5Bk%20in%20keyof%20T%5D%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20%5Bn%20in%20keyof%20T%5Bk%5D%5D%3A%20T%5Bk%5D%5Bn%5D%0D%0A%20%20%20%20%7D%5Bkeyof%20T%5Bk%5D%5D%0D%0A%7D%5Bkeyof%20T%5D%3B%0D%0A%0D%0Adeclare%20const%20okay%3A%20%7B%0D%0A%20%20%20%20a%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20field0%3A%20number%0D%0A%20%20%20%20%7D%2C%0D%0A%20%20%20%20b%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20field1%3A%20boolean%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%3B%0D%0Aconst%20okayUnionNested0%3A%20UnionNested%3Ctypeof%20okay%3E%20%3D%203%3B%0D%0Aconst%20okayUnionNested1%3A%20UnionNested%3Ctypeof%20okay%3E%20%3D%20true%3B%0D%0A%0D%0Aconst%20nonGeneric%3A%20UnionNested%3C%7B%20c%3A%20%7B%20field2%3A%20string%20%7D%20%7D%3E%20%3D%20%22test%22%3B%0D%0A%0D%0Afunction%20generic%3CT%20extends%20%7B%20c%3A%20%7B%20field2%3A%20string%20%7D%20%7D%3E(t%3A%20T)%20%7B%0D%0A%20%20%20%20const%20errorUnionNested%3A%20UnionNested%3CT%3E%20%3D%20%22test%22%3B%0D%0A%7D)

If this is intended behaviour, is there any way to accomplish what I want?
If it's a bug, is there a workaround (that doesn't involve `as any`)?

-----

```ts
type Union<T> = {
    [k in keyof T]: T[k]
}[keyof T];

declare const okay: {
    a: number,
    b: boolean
};
const okayUnion0: Union<typeof okay> = 3;
const okayUnion1: Union<typeof okay> = true;

const nonGeneric: Union<{ c: string }> = "test";

function generic<T extends { c: string }>(t: T) {
    //Error: not assignable
    const errorUnion: Union<T> = "test";
}
```

[Link](http://www.typescriptlang.org/play/#src=type%20Union%3CT%3E%20%3D%20%7B%0D%0A%20%20%20%20%5Bk%20in%20keyof%20T%5D%3A%20T%5Bk%5D%0D%0A%7D%5Bkeyof%20T%5D%3B%0D%0A%0D%0Adeclare%20const%20okay%3A%20%7B%0D%0A%20%20%20%20a%3A%20number%2C%0D%0A%20%20%20%20b%3A%20boolean%0D%0A%7D%3B%0D%0Aconst%20okayUnionNested0%3A%20Union%3Ctypeof%20okay%3E%20%3D%203%3B%0D%0Aconst%20okayUnionNested1%3A%20Union%3Ctypeof%20okay%3E%20%3D%20true%3B%0D%0A%0D%0Aconst%20nonGeneric%3A%20Union%3C%7B%20c%3A%20string%20%7D%3E%20%3D%20%22test%22%3B%0D%0A%0D%0Afunction%20generic%3CT%20extends%20%7B%20c%3A%20string%20%7D%3E(t%3A%20T)%20%7B%0D%0A%20%20%20%20const%20errorUnionNested%3A%20Union%3CT%3E%20%3D%20%22test%22%3B%0D%0A%7D)

**Comment by mhegazy** [comment]
The generic function can be instantiated with a type `{ c: { field2: "foo" } }`, and your assignment of `"test"` would be invalid in this case.

**Comment by AnyhowStep** [comment]
That makes sense. Thank you!
