### ISSUE TITLE
per file target

### ISSUE THREAD

**Issue by BobFrGit** [Microsoft/TypeScript#24272]
## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by mhegazy** [comment]
Assuming i understand the request, given the lack of context in this issue. having a per file target is not a common scenario, and you can always compile one file at a time, or at least group your files by target.

**Comment by BobFrGit** [comment]
No problem -- I thought I had deleted the request for the same reason. It seems that clearing the text and leaving the page doesn't result in deleting the request.
