### ISSUE TITLE
Inferred type depends on physical order of method overloads in code

### ISSUE THREAD

**Issue by Le0Michine** [Microsoft/TypeScript#24275]
**TypeScript Version:**  2.9.0-dev.20180519

**Search Terms:** 
infer, extract function parameter types, function wrapper

**Code**
gist https://gist.github.com/Le0Michine/395417fbf050ec8d8aca0721e32b575a

```ts
interface Param {
    name: string;
    id?: number;
}

interface Result {
    status: number;
}

type CallBack<T> = (result: T) => void;

interface OriginalApi1 {
    fn(cb?: CallBack<Result>): string;
    fn(p: Param, cb?: CallBack<Result>): string;
}

// Same as OriginalApi1 but with diffrent order of methods
interface OriginalApi2 {
    fn(p: Param, cb?: CallBack<Result>): string;
    fn(cb?: CallBack<Result>): string;
}

// Creates wrapper type which has methods with the same names as T returning Promise instead of using callbacks
type Wrapper<T> = { [K in keyof T]: T[K] extends (p: infer P1, cb?: (res: infer P2) => void) => infer R1 ? (p: P1) => Promise<P2> : never };
// Same as Wrapper, supposed to return never if P1 is a Function
type WrapperIgnoringOverloads<T> = { [K in keyof T]: T[K] extends (p: infer P1, cb?: (res: infer P2) => void) => infer R1 ? P1 extends Function ? never : (p: P1) => Promise<P2> : never };

let a: Wrapper<OriginalApi1>;
let b: Wrapper<OriginalApi2>;

a.fn({name: 'name'}); // OK,    (property) fn: (p: Param) => Promise<Result>
b.fn({name: 'name'}); // Error, (property) fn: (p: CallBack<Result>) => Promise<Result>

let c: WrapperIgnoringOverloads<OriginalApi1>;
let d: WrapperIgnoringOverloads<OriginalApi2>;

c.fn({name: 'name'}); // OK,    (property) fn: (p: Param) => Promise<Result>
d.fn({name: 'name'}); // Error, (property) fn: never
```

interfaces created specifically for this example, in my use case there is actually class declaration in a `*.d.ts` file, this is the reason why it doesn't look like this:

```ts
interface OriginalApi {
    fn(p?: Param, cb?: CallBack<Result>): string;
}
```

**Expected behavior:**
resulting type for `Wrapper<OriginalApi1>` and `Wrapper<OriginalApi2>` should be the same, as `OriginalApi1` and `OriginalApi2` are identical types

```ts
Wrapper<OriginalApi1> {
    fn: (p: Param) => Promise<string>
}
Wrapper<OriginalApi2> {
    fn: (p: Param) => Promise<string>
}
```

**Actual behavior:**

types `Wrapper<OriginalApi1>` and `Wrapper<OriginalApi2>` are different despite the fact that `OriginalApi1` and `OriginalApi2` are the same

```ts
Wrapper<OriginalApi1> {
    fn: (p: Param) => Promise<string>
}
Wrapper<OriginalApi2> {
    fn: (p: CallBack<Result>) => Promise<string>
}
```

**Playground Link:**  
[https://www.typescriptlang.org/play/#src=...](https://www.typescriptlang.org/play/#src=interface%20Param%20%7B%0D%0A%20%20%20%20name%3A%20string%3B%0D%0A%20%20%20%20id%3F%3A%20number%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20Result%20%7B%0D%0A%20%20%20%20status%3A%20number%3B%0D%0A%7D%0D%0A%0D%0Atype%20CallBack%3CT%3E%20%3D%20(result%3A%20T)%20%3D%3E%20void%3B%0D%0A%0D%0Ainterface%20OriginalApi1%20%7B%0D%0A%20%20%20%20fn(cb%3F%3A%20CallBack%3CResult%3E)%3A%20string%3B%0D%0A%20%20%20%20fn(p%3A%20Param%2C%20cb%3F%3A%20CallBack%3CResult%3E)%3A%20string%3B%0D%0A%7D%0D%0A%0D%0A%2F%2F%20Same%20as%20OriginalApi1%20but%20with%20diffrent%20order%20of%20methods%0D%0Ainterface%20OriginalApi2%20%7B%0D%0A%20%20%20%20fn(p%3A%20Param%2C%20cb%3F%3A%20CallBack%3CResult%3E)%3A%20string%3B%0D%0A%20%20%20%20fn(cb%3F%3A%20CallBack%3CResult%3E)%3A%20string%3B%0D%0A%7D%0D%0A%0D%0A%2F%2F%20Creates%20wrapper%20type%20which%20has%20methods%20with%20the%20same%20names%20as%20T%20returning%20Promise%20instead%20of%20using%20callbacks%0D%0Atype%20Wrapper%3CT%3E%20%3D%20%7B%20%5BK%20in%20keyof%20T%5D%3A%20T%5BK%5D%20extends%20(p%3A%20infer%20P1%2C%20cb%3F%3A%20(res%3A%20infer%20P2)%20%3D%3E%20void)%20%3D%3E%20infer%20R1%20%3F%20(p%3A%20P1)%20%3D%3E%20Promise%3CP2%3E%20%3A%20never%20%7D%3B%0D%0Atype%20WrapperIgnoringOverloads%3CT%3E%20%3D%20%7B%20%5BK%20in%20keyof%20T%5D%3A%20T%5BK%5D%20extends%20(p%3A%20infer%20P1%2C%20cb%3F%3A%20(res%3A%20infer%20P2)%20%3D%3E%20void)%20%3D%3E%20infer%20R1%20%3F%20P1%20extends%20Function%20%3F%20never%20%3A%20(p%3A%20P1)%20%3D%3E%20Promise%3CP2%3E%20%3A%20never%20%7D%3B%0D%0A%0D%0Alet%20a%3A%20Wrapper%3COriginalApi1%3E%3B%0D%0Alet%20b%3A%20Wrapper%3COriginalApi2%3E%3B%0D%0A%0D%0Aa.fn(%7Bname%3A%20'name'%7D)%3B%20%2F%2F%20OK%2C%20%20%20%20(property)%20fn%3A%20(p%3A%20Param)%20%3D%3E%20Promise%3CResult%3E%0D%0Ab.fn(%7Bname%3A%20'name'%7D)%3B%20%2F%2F%20Error%2C%20(property)%20fn%3A%20(p%3A%20CallBack%3CResult%3E)%20%3D%3E%20Promise%3CResult%3E%0D%0A%0D%0Alet%20c%3A%20WrapperIgnoringOverloads%3COriginalApi1%3E%3B%0D%0Alet%20d%3A%20WrapperIgnoringOverloads%3COriginalApi2%3E%3B%0D%0A%0D%0Ac.fn(%7Bname%3A%20'name'%7D)%3B%20%2F%2F%20OK%2C%20%20%20%20(property)%20fn%3A%20(p%3A%20Param)%20%3D%3E%20Promise%3CResult%3E%0D%0Ad.fn(%7Bname%3A%20'name'%7D)%3B%20%2F%2F%20Error%2C%20(property)%20fn%3A%20never)

**Related Issues:** 
no

**Comment by mhegazy** [comment]
`ReturnType` or the use of `infer` in a function parameter or return position does handle overloads. the last overload is used for inference as it is assumed to be the most general.

See more in https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#type-inference-in-conditional-types

**Comment by Le0Michine** [comment]
not sure

**Comment by Le0Michine** [comment]
Is there any way to workaround this limitation? Haven't seen this information about function overloading in other places and there is no any tsc Warning/Error so I'm not sure everybody using TypeScript considers this approach as a best practice.
Why TS can't choose proper overload taking into account parameters amount and types? Is it something what isn't going to be changed?

I see that it seems to be by design for `infer` keyword (still looks weird as there is no any Warning about that), so I reduced my example to the following snippet, it still looks confusing:
```ts
interface OriginalApi1 {
    fn(p: string): string;
    fn(p: number, p2: number): string;
}

// Same as OriginalApi1 but with diffrent order of methods
interface OriginalApi2 {
    fn(p: number): string;
    fn(p: string): string;
}

// Creates wrapper type which has methods accepting only string parameters
type Wrapper<T> = { [K in keyof T]: T[K] extends (p: infer P1) => any ? P1 extends string ? (p: P1) => P1 : never : never };

let a: Wrapper<OriginalApi1>;
let b: Wrapper<OriginalApi2>;

a.fn(); // Error,    (property) fn: never
b.fn('str'); // OK, (property) fn: (p: string) => string
```
[playground](https://www.typescriptlang.org/play/#src=interface%20OriginalApi1%20%7B%0D%0A%20%20%20%20fn(p%3A%20string)%3A%20string%3B%0D%0A%20%20%20%20fn(p%3A%20number)%3A%20string%3B%0D%0A%7D%0D%0A%0D%0A%2F%2F%20Same%20as%20OriginalApi1%20but%20with%20diffrent%20order%20of%20methods%0D%0Ainterface%20OriginalApi2%20%7B%0D%0A%20%20%20%20fn(p%3A%20number)%3A%20string%3B%0D%0A%20%20%20%20fn(p%3A%20string)%3A%20string%3B%0D%0A%7D%0D%0A%0D%0A%2F%2F%20Creates%20wrapper%20type%20which%20has%20methods%20accepting%20only%20string%20parameters%0D%0Atype%20Wrapper%3CT%3E%20%3D%20%7B%20%5BK%20in%20keyof%20T%5D%3A%20T%5BK%5D%20extends%20(p%3A%20infer%20P1)%20%3D%3E%20any%20%3F%20P1%20extends%20string%20%3F%20(p%3A%20P1)%20%3D%3E%20P1%20%3A%20never%20%3A%20never%20%7D%3B%0D%0A%0D%0Alet%20a%3A%20Wrapper%3COriginalApi1%3E%3B%0D%0Alet%20b%3A%20Wrapper%3COriginalApi2%3E%3B%0D%0A%0D%0Aa.fn()%3B%20%2F%2F%20Error%2C%20%20%20%20(property)%20fn%3A%20never%0D%0Ab.fn('str')%3B%20%2F%2F%20OK%2C%20(property)%20fn%3A%20(p%3A%20string)%20%3D%3E%20string%0D%0A)

I was trying to do something similar without `infer`, it would solve my issue, however, it doesn't work as well. In the next example I'm trying to filter functions by parameter type, it works well if there is no overloading and doesn't work at all with it

```ts
interface OriginalApi1 {
    fn1(p: string): string;
    fn1(p: number, p2: number): string;
    fn2(p: number, p2: number): string;
}

// Filters methods by parameter type
type Filter<T> = { [K in keyof T]: T[K] extends (p: string) => any ? T[K] : never }

let c: Filter<OriginalApi1>;

c.fn1('str'); // OK
c.fn1(23, 42); // OK, why? error expected
c.fn2(23, 42); // Error, (property) fn2: never, as expected
```
[playground](https://www.typescriptlang.org/play/#src=interface%20OriginalApi1%20%7B%0D%0A%20%20%20%20fn1(p%3A%20string)%3A%20string%3B%0D%0A%20%20%20%20fn1(p%3A%20number%2C%20p2%3A%20number)%3A%20string%3B%0D%0A%20%20%20%20fn2(p%3A%20number%2C%20p2%3A%20number)%3A%20string%3B%0D%0A%7D%0D%0A%0D%0A%2F%2F%20Filters%20methods%20by%20parameter%20type%0D%0Atype%20Filter%3CT%3E%20%3D%20%7B%20%5BK%20in%20keyof%20T%5D%3A%20T%5BK%5D%20extends%20(p%3A%20string)%20%3D%3E%20any%20%3F%20T%5BK%5D%20%3A%20never%20%7D%0D%0A%0D%0Alet%20c%3A%20Filter%3COriginalApi1%3E%3B%0D%0A%0D%0Ac.fn1('str')%3B%20%2F%2F%20OK%0D%0Ac.fn1(23%2C%2042)%3B%20%2F%2F%20OK%2C%20why%3F%20error%20expected%0D%0Ac.fn2(23%2C%2042)%3B%20%2F%2F%20Error%2C%20(property)%20fn2%3A%20never%2C%20as%20expected)

**Comment by mhegazy** [comment]
Overload resolution is currently a zero-order process, and is not deferred nor does it work on higher order types. see related discussion in https://github.com/microsoft/typescript/issues/6606#issuecomment-387180923
