### ISSUE TITLE
Fails to compile "x = 2 as number" when "as" starts a new line.

### ISSUE THREAD

**Issue by arielshaqed** [Microsoft/TypeScript#24284]
**TypeScript Version:**  typescript v2.9.0-dev.20180519

(Also with v2.8.3)

**Search Terms:** 
```
"as keyword" newline
"as keyword" whitespace
```

**Code**

Fails:
```ts
const x = 2
as number;
console.log(x);
```

Works:
```ts
const x = 2 as
number;
console.log(x);
```

**Expected behavior:**
Successful compilation (and output "`2`"...).

**Actual behavior:**
tsnode says:
```
...(2,4): ';' expected. (1005)
```

Playground puts wiggly red lines on everything, starting on first `as`.

**Playground Link:** https://www.typescriptlang.org/play/#src=const%20x%20%3D%202%0D%0A%20%20as%20number%3B%0D%0Aconsole.log(x)%3B%0D%0A

**Related Issues:** 
Couldn't find something similar (see search terms above).  It _looks_ related to the general weirdness associated with newlines in JavaScript.  The playground seems to support this, it shows this translation:
```js
x = 2;
as;
number;
console.log(x);
```

**Comment by j-oliveras** [comment]
This is because [automatic semicolon insertion](https://medium.com/@sendilkumarn/asi-do-you-need-it-in-javascript-6715c31625d1), so this is intended. The sample is parsed as:
```ts
const x = 2;
as number;
console.log(x);
```
but because `as` and `number` are not expected typescript shows errors (and try to do it's better to parse them).

**Comment by RyanCavanaugh** [comment]
Might be ASI concerns here, but I think we can safely parse an "as " from the next line?

**Comment by DanielRosenwasser** [comment]
No, this is the intended behavior: https://github.com/Microsoft/TypeScript/pull/3201#issuecomment-103295372
