### ISSUE TITLE
default types for destructuring function parameters should be optional

### ISSUE THREAD

**Issue by omarzion** [Microsoft/TypeScript#24281]
```
const blah({part, ...rest}) => console.log(part)
blah({});
```
this is valid JS and will output undefined, but is Illegal TS.

part defaults to `part: any`

should it not default to `part?: any` since it is possible for it to be optional?

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by mhegazy** [comment]
That is not any different from a non-destructured parameter list:

```ts
const foo= (part, ...rest) => console.log(part)
foo();
```

this is valid JS code and will output `undefined` at runtime. yet the TypeScript compiler flags it.

the rational here, in the absence of any indicator that the parameter is optional, it is expected to be there, in other words, the compiler thinks the omission is likely an error. 

you can indicates to the compiler your intention either using a default:

```ts
const foo = (part = "") => console.log(part)
foo();

const bar = ({ part = "" }) => console.log(part)
bar({});
```
or using an explicit type annotation:

```ts
const foo = (part?: any) => console.log(part);
foo();

const bar = ({ part }: { part?: any }) => console.log(part);
bar({});
```
