### ISSUE TITLE
Using interface and module.exports is breaking type definition

### ISSUE THREAD

**Issue by RomainLanz** [Microsoft/TypeScript#24285]
**TypeScript Version:**  2.9.0-dev.20180519

**Search Terms:** module.exports, interface

**Code**

Here's a repository to reproduce the issue: https://github.com/RomainLanz/ts-module-export-empty-typedef

**Expected behavior:**

The definition of `Config.ts` inside `types/Config.d.ts` shouldn't be "empty".

**Actual behavior:**

The definition of `Config.ts` has only `export {};`. 

**Note:** That it only occurs when we are using an interface over the `Config` class. Removing the interface will generate the definition without any issue.

**Comment by andy-ms** [comment]
You should be getting a compile error (I am):
```ts
src/Config.ts:8:1 - error TS2304: Cannot find name 'module'.

8 module.exports = Config
```

I get the same error even without `Config` implementing any interfaces.

**Comment by RomainLanz** [comment]
@andy-ms I don't since I have installed the type definition of node.

```bash
$ npm i -D @types/node
```

**Comment by andy-ms** [comment]
Well, in `@types/node`, that is just a property `exports: any` on a variable that TypeScript treats as a global. The typed syntax for this is `export = Config;`. We have a similar problem with people using `require()`, which is similarly untyped,  instead of `import`.

**Comment by andy-ms** [comment]
Note, I see no difference in `Config.d.ts` regardless of whether `@types/node` is installed or if the `implements Greet` is included.

**Comment by RomainLanz** [comment]
> The typed syntax for this is export = Config;

I tried this, but then the declaration file also had `export = Config` at his end and it seems to break the IntelliSense of VSCode. I don't know if it's TypeScript or VSCode fault.

```ts
import { Greet } from './Contracts';
declare class Config implements Greet {
    greet(): void;
}
export = Config; // No IntelliSense if I have this line.
```

> Note, I see no difference in Config.d.ts regardless of whether @types/node is installed or if implements Greet is included.

Installing `@types/node` removed the compiler' error `Cannot find name 'module'`.

**Comment by andy-ms** [comment]
> seems to break the IntelliSense of VSCode

Could you clarify what this means?

**Comment by RomainLanz** [comment]
Yes.

I have recorded a video to show exactly what's happening.
I have removed the interface in this example (it seems that IntelliSense isn't working at all when I use it).

![intellisense-export](https://user-images.githubusercontent.com/2793951/40383626-a371be74-5e01-11e8-8381-c62aba6a6e0a.gif)

**Comment by mhegazy** [comment]
the `export = Config` in your `.d.ts` file turns the file into a module. module have their own scope and declarations from them are not visible outside unless imported. think of node modules.

You can use:

```ts
/** @type {import("./types/Config")} */
const config = use();
```

**Comment by RomainLanz** [comment]
Thanks @mhegazy!

So that seems to work with and without the interface.

Is it planned to have a better syntax for future release?

**Comment by RomainLanz** [comment]
I don't understand why we cannot use the `/// <reference path="..." />` tag that import all definition inside the current file.

Having the code below isn't the best for developer experience.

```ts
/** @type {import("./types/Config")} */
const config = use();
```
