### ISSUE TITLE
Suggestion: Add support for jsdoc-based templates with constrains

### ISSUE THREAD

**Issue by jantimon** [Microsoft/TypeScript#24283]
## Search Terms

jsdoc template 

## Suggestion

This feature request is based on issue #1178.  
#1178 led to the implementation of `@template` and was closed afterwards.  

The current implementation does not allow to add constrains for a generic:  

[![add_support_for__template_jsdoc_ _issue__1178_ _microsoft_typescript](https://user-images.githubusercontent.com/4113649/40279248-718ff916-5c3f-11e8-8b57-386adeba7721.jpg)](https://github.com/Microsoft/TypeScript/issues/1178#issuecomment-349069754)

The [latest statement from google in 2015](https://github.com/google/closure-compiler/wiki/Generic-Types) was that they might add it also to the closure-compiler some day:

[![generic_types_ _google_closure-compiler_wiki](https://user-images.githubusercontent.com/4113649/40279244-5ae37f3a-5c3f-11e8-92b6-30fd8c5f6d7c.jpg)](https://github.com/google/closure-compiler/wiki/Generic-Types)

## Use Cases

For `//ts-check` projects it would be possible to use the full power of generics.

## Examples

![playground_ _typescript](https://user-images.githubusercontent.com/4113649/40284357-7ce3f174-5c8e-11e8-8049-94463b1c1b80.jpg)

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

[Stackoverflow: Is it possible to constrain a generic type defined in a jsDoc @template declaration? (May 2017)](
https://stackoverflow.com/questions/44080759/is-it-possible-to-constrain-a-generic-type-defined-in-a-jsdoc-template-declarat)

**Comment by mhegazy** [comment]
I think this should be:

```ts
/**
 * @template T {number}
 * @param a {T}
 */
function foo(a) { }
```

**Comment by brendankenny** [comment]
Definitely would be helpful. Right now we're using `/** @type {...} */` to use bounded generics in js (either defined inline or in an external `d.ts` file), but that has some serious drawbacks at the moment.

e.g. `@type` doesn't work on class methods, so we end up assigning the function to the prototype outside of the `class` body. Readability is also not a small concern (all crammed into that `@type` comment :), and being able to declare as regular `@param`s, etc would be fantastic.

Compatibility with future Closure support isn't super important to us, at least, as we use enough TS-specific features (`typeof`, indexed access) that we have to do a cleaning pass on the code before passing to Closure anyways. If the solution is reasonable (like the above suggestion), there's also no reason Closure can't adopt it anyways.

**Comment by sandersn** [comment]
#24600 has this change.
