### ISSUE TITLE
Wrong formatting with multiline type literals with `&` and `|`

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#24294]
**TypeScript Version:**  2.9.0-dev.201xxxxx

**Search Terms:** 

**Code**
Format the following:

```ts
type NumberOrString = {
    a: number
} & {
    b: string
};
```

**Expected behavior:**
```ts
type NumberOrString = {
    a: number
} & {
    b: string
};
```
**Actual behavior:**
```ts
type NumberOrString = {
    a: number
} & {
        b: string
    };
```
**Playground Link:**  

**Related Issues:**

**Comment by Kingwl** [comment]
This has troubled me for a long time

**Comment by mhegazy** [comment]
thanks @Kingwl for the quick fix.
