### ISSUE TITLE
Pushing to an array marks it as used

### ISSUE THREAD

**Issue by aboyton** [Microsoft/TypeScript#24309]
If I have the flag `noUnusedLocals` set to true then it would be great if TypeScript could somehow know that certain operations such as `push` only write to the array and thus should not mark it as used.

**TypeScript Version:**  2.8.1

**Search Terms:** `noUnusedLocals`

**Code**
With the flag `noUnusedLocals` set to true:

```ts
const foo = [1];
foo.push(2);
```

**Expected behavior:**
> 'foo' is declared but its value is never read.

**Actual behavior:**
No errors

For context, in my particular case I have an array of `subscriptions` from RxJS and then I want to make sure that I call `unsubscribe` on all of them later. If `noUnusedLocals` could detect if my array `subscriptions` was only ever written to then forgetting to loop over them and call `unsubscribe` would be a compile error. (Combining this with a lint rule like [on-watch](https://github.com/Gillespie59/eslint-plugin-angular/blob/master/docs/rules/on-watch.md) to ensure that subscriptions are saved into a variable works surprisingly well apart from the `push` marking an array as used.)

**Comment by mhegazy** [comment]
The general case is hard to implement.. think of `foo.bar()`, does this mean `foo` was used or not? without some understanding of what `bar` does, you can not tell.

**Comment by aboyton** [comment]
Definitely the generic case would be very hard to solve. Could you perhaps instead tag a function as write only and use that in the type checker?

**Comment by mhegazy** [comment]
Possibly. but i do not think we would add a new language construct just to get unused variable checks, the utility vs. complexity is rather low. 
i would recommend writing a tslint rule that flags arrays that are only used with `push`/`unshift`/`slice`.

**Comment by andy-ms** [comment]
You may be interested in palantir/tslint#3622

**Comment by aboyton** [comment]
Thanks for the help, I'll look into TSLint rules like the one that you mentioned. I personally think there's value in having the ability for the language to be able to say if a function reads or writes to a variable not just for this but also for covariance and contravariance, but I'm not going to pretend I'm an expert on this and I realise that it wouldn't be a small change to the language.
