### ISSUE TITLE
No error for invalid module augmentation in '.d.ts' file

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#24307]
**TypeScript Version:**  2.9.0-dev.20180519

**Code**

```ts
// @Filename: /a.d.ts
export {};
declare module "invalid" {}

// @Filename: /b.ts
export {};
declare module "invalid" {}
```

**Expected behavior:**

Error in both files.

**Actual behavior:**

Only error in `b.ts`.

**Comment by andy-ms** [comment]
There is a comment in `checker.ts`, `// do not validate names of augmentations that are defined in ambient context`.

**Comment by mhegazy** [comment]
thanks for the reference.. i vaguely remember this issue. i guess it is by design then.
