### ISSUE TITLE
jsconfig.json - checkJS option not recognized

### ISSUE THREAD

**Issue by arturdeveloper** [Microsoft/TypeScript#24301]
I am trying to follow this setup instructions for VS Code:
<https://code.visualstudio.com/docs/languages/javascript>
to enable type checking for all JavaScript files that are part of a jsconfig.json. My jsconfig.json file looks like this:

```json
{
  "compilerOptions": {
    "checkJs": true,
    "target": "ES5",
    "rootDir": "src",
    "outDir": "lib",
    "watch": true
  },
  "exclude": ["node_modules", "**/node_modules/*"],
  "include": ["./src"]
}
```

When runnning from command line with

```bash
tsc -p jsconfig.json
```

I get this error:

```bash
error TS5023: Unknown compiler option 'checkJs'.
```

Using `//@ts-check` at the top of individual files works as expected.

Additional info:
VS Code version: 1.23.1 d0182c3417d225529c6d5ad24b7572815d0de9ac x64
tsc version: Version 2.1.6

**Comment by mhegazy** [comment]
> tsc version: Version 2.1.6

That is your problem. `--checkJs` support started in [2.5](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#type-assertioncast-syntax-in-checkjsts-check-mode).

**Comment by arturdeveloper** [comment]
I was under impression that I was on the latest version after running
 `npm update -g typescript@latest` a few times, tried again with
 `npm install -g typescript@latest` and it updated to 2.8.3 which doesn't seem to work (doesn't create the output dir and files).

**Comment by mhegazy** [comment]
please share a self-contained repro to help us identify the issue.

**Comment by arturdeveloper** [comment]
Please check out this repository for the example
https://github.com/arturdeveloper/tsc_repro

**Comment by mhegazy** [comment]
A `jsconfig.json` has some *implicit* defaults that are not in a `tsconfig.json`. the rational is that these are used in a `.js` project in an IDE like VSCode/VS/SublimeText, etc.. One of these defaults is `"allowJs" : true`, and another is `"noEmit": false`. that is why you are not getting output generated, the compiler only runs in check mode..

my recommendation here is to either use `tsconfig.json`, add `"allowJs": true`, or add `"noEmit": false` in your `jsconfig.json`

**Comment by arturdeveloper** [comment]
Thanks, it works now. The above mentioned setup instructions probably need to be updated with this info. It isn't apparent that with the default settings no output is produced.
https://code.visualstudio.com/docs/languages/javascript#_use-the-typescript-compiler
