### ISSUE TITLE
lib.dom.d.ts is missing IDBObjectStore.openKeyCursor()

### ISSUE THREAD

**Issue by oliverjanik** [Microsoft/TypeScript#24313]
Version: 2.8.3

https://developer.mozilla.org/en-US/docs/Web/API/IDBObjectStore/openKeyCursor

**Comment by mhegazy** [comment]
This is fixed in https://github.com/Microsoft/TSJS-lib-generator, see https://github.com/Microsoft/TSJS-lib-generator/blob/00b699f01f3787b2fbe8a28af9e4fdc3828253e0/baselines/dom.generated.d.ts#L8820
