### ISSUE TITLE
Show 'move to a new file' refactoring on symbol names

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#24327]
## Search Terms
- move to file
- refactoring

## Suggestion
For a file:

```ts
class Abc {}
class Xyz {}
```

The `move to a new file` refactoring only shows up if you select the entire declaration, i.e. `class Abc {}` or `class Xyz {}`

I propose that we also show it if the requested range is on the symbol name, such as inside `Abc` or inside `Xyz`

## Use Cases
This will improve discoverability of the feature and help with dealing with large classes or function that do not fit on the screen

**Comment by mhegazy** [comment]
@andy-ms i think we should do here what we have done in https://github.com/Microsoft/TypeScript/pull/24187 and include the declaration if the declaration name is part of the selection.
