### ISSUE TITLE
'arguments' object not supported by findAllRefs/getOccurrences

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#2432]
``` TypeScript
function foo() {
    arguments;

    arguments;
}
```

_Expected_: Find all refs on either `arguments` will give you both of the above. Get occurrences will highlight both.

_Actual_: No highlighting, no references found.

**Comment by Andarist** [comment]
This works OK today, the issue can be closed. cc @jakebailey
