### ISSUE TITLE
Importing non-exported types

### ISSUE THREAD

**Issue by Leandros** [Microsoft/TypeScript#24322]
## Search Terms

importing types, access private types, import non exported types

## Suggestion

Consider the following example:

**types.ts:**

```
export interface AnimalProps {
  name: string;
  age: number;
}
export type Callback = (params: AnimalProps) => boolean;
```

**animal.ts:**
```
import { AnimalProps, Callback } from './types';

export class Animal {
  protected props: AnimalProps;
  constructor(props: AnimalProps) {
    this.props = props;
  }
  getProps(cb: Callback) {
    cb(this.props);
  }
}
```

**index.ts:**
```
import { Animal } from './animal';

function main() {
  const props/* : AnimalProps */ = { name: 'Linda', age: 8 };
  const animal: Animal = new Animal(props);
  console.log('animal:', animal);
}
main();
```

You can see that the `props` variable in `main` is untyped, and only type checked at the end, when actually passed to the constructor of `Animal`. 
I can't expose the `AnimalProps` to another module, since I have no way of accessing the type, due to a missing export in 'animal.ts'.
I'd have to re-declare the `AnimalProps` inside `index.ts` and expose this. While this is simple in this example, it's more complex and often impossible in real-world projects, where `animal.ts` is, for example, the `index.ts` of a node module, hence `types.ts` not being available (example: https://github.com/prismagraphql/graphql-yoga/tree/master/src). 

## Use Cases

Correctly propagating the types throughout a code base, without having to do double the work to redefine all types.

## Examples

See the above example. I encountered the case when trying to create a new `GraphQLServerLambda`, and wanting to expose the `LambdaProps` of it's constructor.

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by andy-ms** [comment]
You can always:
* Declare `export { AnimalProps } from "./types";` in `animal.ts` and import that.
* Just import from "./types" in `index.ts`.

**Comment by jcready** [comment]
As a workaround you can extract the `LambdaProps` type from the exported `GraphQLServerLambda` class:

```ts
type ConstructorArg1<T> = T extends new (first: infer U, ...rest: any[]) => any ? U : undefined;
export type LambdaProps = ConstructorArg1<typeof GraphQLServerLambda>;
```

**Comment by Leandros** [comment]
@andy-ms While that works in the little example I created, it doesn't work in the real-world example of graphql-yoga, where I'd have to change the library to export the types. 

@jcready Oh. wow. That seems to work, but I'd really see a less mouthful solution to the problem.
If I compare TypeScript with other, commonly used languages, like C, it's odd for me that types which are used in the public API of a class / module aren't readily available. In C, unless it's an opaque type (pointer to some struct, created with a factory function), all types are available and can (and often must) be used.

**Comment by RyanCavanaugh** [comment]
@Leandros What are you proposing be changed/added?

**Comment by Leandros** [comment]
To keep backwards compatibility, and not break existing code, I'd propose adding the equivalent of a normal import, but for types. Something along the lines of:

```
import types from './animal';
```

Syntax up for discussion, I'm not up to speed whether `types` is a reserved keyword (and or can be used as reserved in this context). Should probably also respect namespaces and decomposition, and not just dump all the types into the global scope.
This would import the publicly accessible types of the specified module. In my little animal example, this would export the `AnimalProps` and `Callback` type.

**Comment by andy-ms** [comment]
There is already a re-export syntax `export * from "./animal";`, although that re-exports values too.

> it doesn't work in the real-world example of graphql-yoga, where I'd have to change the library to export the types.

If the library is importing the types from somewhere, can't you just cut out the middle-man and import the types from wherever it imported them from?

**Comment by Leandros** [comment]
The re-export syntax only exports what's already been exported, hence wouldn't work it in my example (unless I'm misunderstanding it).

Yes, that's the current solution I'm using. However, what would I do if the types were declared in the same module, but not exported? Than I'd be presented with the original problem again.

**Comment by Leandros** [comment]
Alright. Thanks for the explanation. Makes sense, not exported types should be treated as the equivalent to an opaque type in other languages.
