### ISSUE TITLE
Display references using richer hierarchy

### ISSUE THREAD

**Issue by JsonFreeman** [Microsoft/TypeScript#2434]
Roslyn supports a hierarchical view of references. So whereas today a set of references is displayed as a flat list, it would be nice if they were grouped by which particular declarations they referencing. So in the following example, there would be 3 groups:

```ts
interface I {
    foo; // group 1
}

class C implements I {
    foo; // group 2
}

var i: I;
i.foo; // group 1
(new C).foo; // group 2

function fun(): I {
    var foo; // group 3
    return { foo }; // group 3
}
```

This will give us some nice structure in the reference set. It also means we never have to worry about overwhelming the user because they can just zoom in on the references for a particular definition.

**Comment by CyrusNajmabadi** [comment]
You should see this behavior with the latest VS2015 bits.
