### ISSUE TITLE
go-to-type-definition, and find-all-refs not working for `import.meta`

### ISSUE THREAD

**Issue by mhegazy** [microsoft/TypeScript#24353]
**TypeScript Version:**  2.9.0-dev.201xxxxx

**Search Terms:** 

**Code**

```ts
import.meta; 
```

**Expected behavior:**

- go-to-def should fail
- go-to-type-def should jump to `ImportMeta` in lib.es5.d.ts
- find-all-refs / occurrences should highlight all references of import.meta
- rename should fail

**Actual behavior:**

- go-to-type-def fails
- find-all-refs / occurrences fails

**Playground Link:**  

**Related Issues:**

**Comment by willbw** [comment]
@mhegazy Can I have a crack at this one?

**Comment by mhegazy** [comment]
go for it.

**Comment by rdosanjh** [comment]
@willbw are you still working on this? If not i would like to have a go.

**Comment by willbw** [comment]
Go for it!


On 1 October 2018 at 5:58:28 am, Raj Dosanjh (notifications@github.com) wrote:

@willbw are you still working on this? If not i would like to have a go.
