### ISSUE TITLE
Find references does not go through shorthand properties

### ISSUE THREAD

**Issue by JsonFreeman** [Microsoft/TypeScript#2435]
```ts
interface I {
    foo;
}

function fun(): I {
    var foo; // not shown
    return { foo };
}

fun().foo; // find refs on foo
```

The var should be listed as one of the references.

**Comment by yuit** [comment]
This seems to be similar issue with #1507

**Comment by JsonFreeman** [comment]
Indeed it is. I don't see a conceptual difference. Sorry for the redundant bug. You can close it, and just add this case as a test for the other bug.

**Comment by yuit** [comment]
Thanks @JsonFreeman! a :cookie: point for you :)
