### ISSUE TITLE
Refactor for convert string key to identifier for enum or object literal if they could convert

### ISSUE THREAD

**Issue by Kingwl** [Microsoft/TypeScript#24351]
## Suggestion

convert string key to identifier if they could convert

## Use Cases

always have some legacy code or some string copied from a json need convert to a Enum  

it can run expect but it is ugly

## Examples

```ts

export enum AttackType {
  'sql_injection', 'xss', 'csrf' // ... etc
}

```

to 

```ts

export enum AttackType {
  sql_injection, xss, csrf // ... etc
}

```

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by mhegazy** [comment]
this looks like a linter error/quick fix to me. e.g. https://palantir.github.io/tslint/rules/object-literal-key-quotes/
