### ISSUE TITLE
Go to definition does not go through shorthand properties

### ISSUE THREAD

**Issue by JsonFreeman** [Microsoft/TypeScript#2436]
```ts
interface I {
    foo; // This is the only current result
}

function fun(): I {
    var foo; // This should also be a result
    return { foo };
}

fun().foo; // go to def on foo
```

The var should be shown as a definition.

**Comment by mhegazy** [comment]
I do not see why this is the case but not this:
```ts
interface I {
    foo; 
}

class C {
   foo: string;
   bar: number;
}
function getI() : I {
    return new C();
}

var x: I = {foo : 0 };
var y = getI();

y.foo;
x.foo;
```

in both cases, the only thing we know about foo is it is the one from interface I. it is possible that they come from a different place, but that is a job for find all references.

**Comment by JsonFreeman** [comment]
It would certainly not be straightforward to fix, as it would require not just understanding that the function call returns an I, but diving into the return expression to figure out where that thing came from.
