### ISSUE TITLE
Inconsistency in types after type inference

### ISSUE THREAD

**Issue by DeTeam** [microsoft/TypeScript#24369]
I'm currently working on providing a nice API in a library where users will be providing implementations of a particular interface. Interface's methods are meant to be executed async in a particular order. Result of calling one method will be transformed in an known way and passed to the next method.

In order to not force my users typing signatures again and again for every part of the process in type parameters, I wanted to benefit from type inference and not to have specify types at all, while still having proper type checking.

Example below illustrates the intention.

While trying things out — faced some inconsistencies in typescript (or VS Code?) which IMHO worth reporting.

**TypeScript Version:**  2.9.0-dev.201xxxxx
**Search Terms:**  "inference"

**Code**

```ts
type F<X> = [X];
type G<Y> = [Y];
interface IProcess<X, Y> {
  start(): X;
  process<XX = X>(opt: F<XX>): Y;
  finish(opt: G<Y>): void;
}
function foo<X, Y>(desc: IProcess<X, Y>): void {
  const x = desc.start();
  const y = desc.process([x]);
  desc.finish([y]);
}
foo({
  start() {
    return {
      name: "Joe"
    };
  },
  process([x]) {
    return x.name;
  },
  finish([x]) {
    console.log(x);
  }
});
```

**Expected behavior:**

In `process` function `x.name` would be of a type `string`

**Actual behavior:**

* `Property 'name' does not exist on type 'XX'.`
* Even though: `var x: XX = { name: string }`

![types](https://user-images.githubusercontent.com/72801/40473581-d9db1690-5f3c-11e8-822a-06cad6e31e91.gif)

**Playground Link:** [playground link](http://www.typescriptlang.org/play/#src=type%20F%3CX%3E%20%3D%20%5BX%5D%3B%0D%0Atype%20G%3CY%3E%20%3D%20%5BY%5D%3B%0D%0Ainterface%20IProcess%3CX%2C%20Y%3E%20%7B%0D%0A%20%20start()%3A%20X%3B%0D%0A%20%20process%3CXX%20%3D%20X%3E(opt%3A%20F%3CXX%3E)%3A%20Y%3B%0D%0A%20%20finish(opt%3A%20G%3CY%3E)%3A%20void%3B%0D%0A%7D%0D%0Afunction%20foo%3CX%2C%20Y%3E(desc%3A%20IProcess%3CX%2C%20Y%3E)%3A%20void%20%7B%0D%0A%20%20const%20x%20%3D%20desc.start()%3B%0D%0A%20%20const%20y%20%3D%20desc.process(%5Bx%5D)%3B%0D%0A%20%20desc.finish(%5By%5D)%3B%0D%0A%7D%0D%0Afoo(%7B%0D%0A%20%20start()%20%7B%0D%0A%20%20%20%20return%20%7B%0D%0A%20%20%20%20%20%20name%3A%20%22Joe%22%0D%0A%20%20%20%20%7D%3B%0D%0A%20%20%7D%2C%0D%0A%20%20process(%5Bx%5D)%20%7B%0D%0A%20%20%20%20return%20x.name%3B%0D%0A%20%20%7D%2C%0D%0A%20%20finish(%5Bx%5D)%20%7B%0D%0A%20%20%20%20console.log(x)%3B%0D%0A%20%20%7D%0D%0A%7D)%3B%0D%0A)

**Related Issues:**  didn't find any

**Comment by DanielRosenwasser** [comment]
Your interface says that the `start` method on an `IProcess` is generic, which really says that it works *regardless of the type of `XX`*. I'm really not sure why `process` needs to be generic, but I suspect that you're trying to solve the failure of inference in this situation:

```ts
interface IProcess<X, Y> {
  start(): X;
  process(opt: [X]): Y;
  finish(opt: [Y]): void;
}

function foo<X, Y>(desc: IProcess<X, Y>): void {
  const x = desc.start();
  const y = desc.process([x]);
  desc.finish([y]);
}

foo({
  start() {
    return {
      name: "Joe"
    };
  },
  process([x]) {
    return x.name;
  },
  finish([x]) {
    console.log(x);
  }
});
```

Here, `foo` fails to find inferences for `X` and `Y`. I think there might be a limitation in our inference here, but it's pretty undesirable.

**Comment by mhegazy** [comment]
We do not treat method signatures as contextually sensitive.. i am not quite sure if this was a deliberate choice or a bug.. 

so this works as expected:

```ts
foo({
    start: () => {
        return {
            name: "Joe"
        };
    },
    process: ([x]) => {
        return x.name;
    },
    finish: ([x]) => {
        console.log(x);
    }
});
```

The error on `name` as noted by @DanielRosenwasser is correct, since `process` is generic function, and it can be called with anything that is not related to `X`.. I would make not make it generic really. but if you must, then add a constraint:

```ts
 process<XX extends X = X>(opt: F<XX>): Y;
```

**Comment by weswigham** [comment]
> The error on name as noted by @DanielRosenwasser is correct, since process is generic function, and it can be called with anything that is not related to X.. I would make not make it generic really. but if you must, then add a constraint:

Nonsense! Inference for `XX` will fail, since the param `[x]`is unannotated, meaning it'll fall back to its default, `X`, which we _do_ have an inference for (from the first method), which has a `name` member (making the method implementation valid).

**Comment by DeTeam** [comment]
Thanks for your comments.

@DanielRosenwasser 

> I'm really not sure why `process` needs to be generic

> I suspect that you're trying to solve the failure of inference in this situation:

Thinking what would be the best way to rephrase my use-case from the ticket description.. I want users of my lib not to have to specify types while getting benefits of type inference OR confirm here that such expectations of inference in typescript should not be there :)

I'm expecting more advance inference based on: little knowledge of how inference works in TS, previous experience working with haskell.

@mhegazy 

> We do not treat method signatures as contextually sensitive.. i am not quite sure if this was a deliberate choice or a bug..

This is exactly what I was looking for in the docs but didn't manage to find 🤔 

@weswigham 

> Inference for `XX` should fail

This would solve the inconsistency issue, 👍

**Comment by MartinJohns** [comment]
> This is exactly what I was looking for in the docs but didn't manage to find

Another case where having a specification for TypeScript would be helpful. 🤔

**Comment by DanielRosenwasser** [comment]
> We do not treat method signatures as contextually sensitive

I'm pretty sure we do:

```ts
        function isContextSensitiveFunctionOrObjectLiteralMethod(func: Node): func is FunctionExpression | ArrowFunction | MethodDeclaration {
            return (isInJavaScriptFile(func) && isFunctionDeclaration(func) || isFunctionExpressionOrArrowFunction(func) || isObjectLiteralMethod(func)) &&
                isContextSensitiveFunctionLikeDeclaration(func);
        }
```

> Nonsense! Inference for `XX` should fail, since the param `[x]`is unannotated, meaning it should fall back to its default, `X`, which we _do_ have an inference for (from the first method), which has a `name` member (theoretically making the method implementation valid).

I'm wondering if this is an instance where in which "pulling" on the type of `XX` in the body of `process`, inference prematurely fixes it to `{}`.

**Comment by RyanCavanaugh** [comment]
Tagging this as design limitation unless @weswigham or @ahejlsberg has ideas about a targeted fix. In general we are not great at inference that requires knowing which order things needs to happen in.

Or we wait for #30134
