### ISSUE TITLE
TS2526: A 'this' type is available only in a non-static member of a class or interface.

### ISSUE THREAD

**Issue by BTOdell** [Microsoft/TypeScript#24364]
**TypeScript Version:**  2.9.0-dev.20180519

**Search Terms:** 
TS2526

**Code**

```ts
private readonly eventMap: { [type: number]: new() => MyGenericObject<this> };
```

**Expected behavior:**
No compile error.

**Actual behavior:**
TS2526: A 'this' type is available only in a non-static member of a class or interface.

**Playground Link:**
http://www.typescriptlang.org/play/#src=%2F%2F%20This%20doesn't%20work%0D%0A%0D%0Aexport%20class%20ErrorClass%20%7B%0D%0A%20%20%20%20private%20readonly%20eventMap%3A%20%7B%20%5Btype%3A%20number%5D%3A%20new%20()%20%3D%3E%20MyEvent%3Cthis%3E%20%7D%3B%0D%0A%7D%0D%0Aexport%20class%20MyEvent%3CT%3E%20%7B%20%7D%0D%0A%0D%0A%2F%2F%20But%20using%20a%20type%20alias%20does%3F%0D%0A%0D%0Atype%20MyTypeAlias%3CT%3E%20%3D%20%7B%20%5Btype%3A%20number%5D%3A%20new%20()%20%3D%3E%20T%20%7D%3B%0D%0A%0D%0Aexport%20class%20ErrorClassWorkaround%20%7B%0D%0A%20%20%20%20private%20readonly%20eventMap%3A%20MyTypeAlias%3CMyEvent%3Cthis%3E%3E%3B%0D%0A%7D

**Comment by mhegazy** [comment]
`this` references the containing type, in this case the object type literal. your solution of defining a type alias is correct.

**Comment by BTOdell** [comment]
Ah ha! Thanks.
