### ISSUE TITLE
Intermediate Variable assigment break inference

### ISSUE THREAD

**Issue by rulonder** [Microsoft/TypeScript#24376]
**TypeScript Version:**  2.8.3

**Search Terms:** 
Variable Union
**Code**

```ts
// A *self-contained* demonstration of the problem follows...
enum Types {
    A = "A",
    B = "B",
}

type ActionA = {type:Types.A,id:number}
type ActionB = {type:Types.B,code:number}

type Actions = ActionA | ActionB

function returnActionCode(action:Actions){
    switch (action.type) {
        case Types.A:
            return action.id   
        default:
            action.code;
    }
}

// assigning a intermediate variable breaks the flow analysis
function returnActionCodeFail(action:Actions){
    const type = action.type
    switch (type) {
        case Types.A:
            return action.id   // Property 'id' does not exist on type 'Actions'. Property 'id' does not exist on type 'ActionB'.
        default:
            action.code; // Property 'code' does not exist on type 'Actions'. Property 'code' does not exist on type 'ActionA'.
    }
}
```

**Expected behavior:**

Both functions should compile as they are equivalent

**Actual behavior:**
Only the first one is valid, Both are actually equal and should be valid, seems that having an intermediate variable assignment breaks the type inference.
**Playground Link:** 
[Playgorund Link](http://www.typescriptlang.org/play/index.html#src=enum%20Types%20%7B%0D%0A%20%20%20%20A%20%3D%20%22A%22%2C%0D%0A%20%20%20%20B%20%3D%20%22B%22%2C%0D%0A%7D%0D%0A%0D%0Atype%20ActionA%20%3D%20%7Btype%3ATypes.A%2Cid%3Anumber%7D%0D%0Atype%20ActionB%20%3D%20%7Btype%3ATypes.B%2Ccode%3Anumber%7D%0D%0A%0D%0Atype%20Actions%20%3D%20ActionA%20%7C%20ActionB%0D%0A%0D%0Afunction%20returnActionCode(action%3AActions)%7B%0D%0A%20%20%20%20switch%20(action.type)%20%7B%0D%0A%20%20%20%20%20%20%20%20case%20Types.A%3A%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20action.id%20%20%20%0D%0A%20%20%20%20%20%20%20%20default%3A%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20action.code%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0A%2F%2F%20assigning%20a%20intermediate%20variable%20breaks%20the%20flow%20analysis%0D%0Afunction%20returnActionCodeFail(action%3AActions)%7B%0D%0A%20%20%20%20const%20type%20%3D%20action.type%0D%0A%20%20%20%20switch%20(type)%20%7B%0D%0A%20%20%20%20%20%20%20%20case%20Types.A%3A%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20action.id%20%20%20%2F%2F%20Property%20'id'%20does%20not%20exist%20on%20type%20'Actions'.%20Property%20'id'%20does%20not%20exist%20on%20type%20'ActionB'.%0D%0A%20%20%20%20%20%20%20%20default%3A%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20action.code%3B%20%2F%2F%20Property%20'code'%20does%20not%20exist%20on%20type%20'Actions'.%20Property%20'code'%20does%20not%20exist%20on%20type%20'ActionA'.%0D%0A%20%20%20%20%7D%0D%0A%7D)
**Related Issues:**
22093

**Comment by RyanCavanaugh** [comment]
Logged before / basically the same as #22341 - we don't do narrowing based on indirect references to discriminants
