### ISSUE TITLE
Missing properties: document.pointerLockElement and MouseEvent.movement

### ISSUE THREAD

**Issue by JJura** [Microsoft/TypeScript#2437]
Hello.

I stumbled across some problems with missing properties when implementing webGL camera movement.

Those listed below are not declared in lib.d.ts file:
- document.pointerLockElement
- MouseEvent.movementX
- MouseEvent.movementY

Can we please have this fixed in the upcoming releases?

**Comment by danquirk** [comment]
I assume this has the same problems as our usual .d.ts issues where we're relying on IE's definitions to generate the typings file.

**Comment by jasonwilliams200OK** [comment]
Maybe relying on W3C or Mozilla's data-source would make much more sense (even Mozilla's experimental features are on a par with or W3 upcoming standards).
