### ISSUE TITLE
specify output formatting options

### ISSUE THREAD

**Issue by sclausen** [Microsoft/TypeScript#2438]
It would be great, if you could also control the indentation etc. of the output javascript files.

**Comment by danquirk** [comment]
What kind of controls do you want that make the output formatting distinct from your TypeScript settings? Can you give an example of some TS -> JS you'd perform this kind of operation on.

**Comment by sclausen** [comment]
Similar to the formatCodeOptions for TypeScript it would be great to define a formatter config file for output settings such as indentSize, tabSize, newLineCharacter or convertTabsToSpaces

**Comment by danquirk** [comment]
Under what conditions do you actually want your JS arrow functions indented to a different level than when they were in TS? Or when would you want tabs in your JS but spaces in your TS?

**Comment by sclausen** [comment]
No, I don't want the output formatting different than the TS formatting.
It would be great if the were equal, but the aren't. When I compile for example TS with two spaces as a tab it will output to JS with four spaces as a tab.

``` typescript
function identity<T>(arg: T): T {
  return arg;
}
```
`tsc test.ts`
``` javascript
function identity(arg) {
    return arg;
}
```

**Comment by RyanCavanaugh** [comment]
There are many good JavaScript formatting tools available that have more options than you can shake a stick at; I would recommend chaining one of them in to your build pipeline. It'd be pointless for us to re-implement those when the vast majority of the time any human-readable JS is "good enough".
