### ISSUE TITLE
Indexed types inference with generics looses type

### ISSUE THREAD

**Issue by Psidium** [Microsoft/TypeScript#24398]
**TypeScript Version:**  commit 64642bb5c33878ed9b481f29b3ec626a675d2d74 (`master` at the time of writing)

**Search Terms:**  Inference Indexed

**Code**

```ts
function getAllValuesOfObject<T>(obj: { [index: string]: T }): T[] {
    return Object.keys(obj).map((key) => obj[key]);
}

const ordinals: { [i: number]: string } = {
    1: "first",
    2: "second"
};

// `values` has inferred type `{}[]` when it should have `string[]`;
const values = getAllValuesOfObject(ordinals);

// Error: Property 'split' does not exist on type '{}'.
values[0].split("i");
```

**Expected behavior:** variable `values` to have type `string[]`

**Actual behavior:** variable `values` gets type `{}[]`

**Playground Link:** [Playground](https://www.typescriptlang.org/play/index.html#src=function%20getAllValuesOfObject%3CT%3E(obj%3A%20%7B%20%5Bindex%3A%20string%5D%3A%20T%20%7D)%3A%20T%5B%5D%20%7B%0D%0A%20%20%20%20return%20Object.keys(obj).map((key)%20%3D%3E%20obj%5Bkey%5D)%3B%0D%0A%7D%0D%0A%0D%0Aconst%20ordinals%3A%20%7B%20%5Bi%3A%20number%5D%3A%20string%20%7D%20%3D%20%7B%0D%0A%20%20%20%201%3A%20%22first%22%2C%0D%0A%20%20%20%202%3A%20%22second%22%0D%0A%7D%3B%0D%0A%0D%0A%2F%2F%20%60values%60%20has%20inferred%20type%20%60%7B%7D%5B%5D%60%20when%20it%20should%20have%20%60string%5B%5D%60%3B%0D%0Aconst%20values%20%3D%20getAllValuesOfObject(ordinals)%3B%0D%0A%0D%0A%2F%2F%20Error%3A%20Property%20'split'%20does%20not%20exist%20on%20type%20'%7B%7D'.%0D%0Avalues%5B0%5D.split(%22i%22)%3B)

I don't know exactly what shoud happen.

On one hand, in Javascript, when encountering a non-string key in an object accessor, the engine calls `toString()` on the key to create the key that will be used to access the value at that key (This is even stated on the Typescript deep-dive book, I think).

On the other hand, a `number` is not a `string`...

So either I get an error when trying to pass a `{[o: number]: string }` to `{[i: string]: T }` or the resulting object is of the type I specificed on the `T` side.

Also, it seems to be related to the type mismatch between the two possible indexer types: `string` and `number`. If the `index` on either types change to the same type as the other, the issue dissapears.

Do you think this would be an easy bug to fix? I'd like to give it a go if you point me where I'd have to start looking (only played with transformers so far, though).

**Comment by mhegazy** [comment]
All indexers at run-time are actually strings. . the inference for `[x:string]: T` not inferring from `[x: number]: U` is intentional; you would not want an array to pass for a map-like. chances are this is a bug.
