### ISSUE TITLE
Missing sub-type resolution in suggestion popup

### ISSUE THREAD

**Issue by ackvf** [microsoft/TypeScript#24408]
**TypeScript Version:**  
discovered in `2.9.0-dev.20180511` and `2.7.2`

I discovered https://github.com/Microsoft/TypeScript/issues/24409 while trying to reproduce this in `typescript@3.0.0`.

**Code**
```ts
// x.ts
import { Enum } from '~/types'

type ObjectFromEnum<T, R extends string = Enum> = {
  [S in R]: T
}

export const SYMBOLS: ObjectFromEnum| // <- cursor for ctrl+space hints here

// types.d.ts
export type Enum = 'a' | 'b' | 'c'
export type EnumX = 'd' | 'e' | 'f'
export type ObjectFromEnumX<T, R extends string = EnumX> = {
  [S in R]: T
}
```

**Expected behavior:**
Expected is that referenced types are resolved for both local and external _(not yet imported)_ types.
In this case for external type `ObjectFromEnumX`, `EnumX = 'd' | 'e' | 'f'`
![image](https://user-images.githubusercontent.com/2313018/40550020-43948e16-6039-11e8-8636-f0d978cc4707.png)

**Actual behavior:**
Type `Enum` is not resolved for locally available type.
![image](https://user-images.githubusercontent.com/2313018/40550031-4d738f0e-6039-11e8-92d4-9d873bcba30d.png)

"Locally available" applies for imported types as well. The `EnumX` resolution is missing again once `ObjectFromEnumX` is imported.
![image](https://user-images.githubusercontent.com/2313018/40551535-8bf91632-603d-11e8-98a0-3bbd3a60f699.png)

**Comment by RyanCavanaugh** [comment]
Either behavior is correct here; this isn't a bug.

**Comment by ackvf** [comment]
@RyanCavanaugh Thank you for getting back to it.

I see that it now behaves differently.

Both of the types are written just as `... R extends string = Enum ...` and `... R extends string = EnumX ...`
![image](https://github.com/microsoft/TypeScript/assets/2313018/f7f61c59-5e62-4870-80f2-51e22ed5c291)
![image](https://github.com/microsoft/TypeScript/assets/2313018/1d598e05-820d-4da2-8478-8a34f29cfcd8)

Before,
- when the type `ObjectFromEnumX` was **not imported** at the time the intellisense for `ObjectFromEnumX` was invoked, it would resolve to `... R extends string = "d" | "e" | "f" ...`, which was useful.
- when peeking into the intellisense for `ObjectFromEnum`, having the `Enum` imported in the file, it would resolve to just `... R extends string = Enum ...`
- After also doing `import { Enum, ObjectFromEnumX } from '~/types'`, the intellisense for `ObjectFromEnumX` would then change from `"d" | "e" | "f"` to just `... R extends string = Enum ...`.

That was kind of puzzling bac then, but today the behavior is different, so this ticket is indeed not needed any more.
