### ISSUE TITLE
Publish daily build please

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#24405]
Stopped since 20180522. I want to check #24391. BTW, why daily build is so unstable?

cc @mhegazy @DanielRosenwasser

**Comment by mhegazy** [comment]
@weswigham can you take a look.

**Comment by weswigham** [comment]
Our nightly publish started failing on compile since we merged the strict null checks pr. The `configurePrerelease` script appears to not be strict-compatable XD

**Comment by weswigham** [comment]
Our build is no longer broken and we have nightlies again. 😉

**Comment by weswigham** [comment]
We did a major refactoring of the compiler at the start of the week and are aware that we haven't published a nightly since. We should hopefully have enough things back in order to publish again today.
