### ISSUE TITLE
Use another overload signature's documented info if exact one's info is missing

### ISSUE THREAD

**Issue by falsandtru** [microsoft/TypeScript#24414]
**TypeScript Version:**  3.0.0-dev.20180522

**Search Terms:** 

**Code**

```ts
/**
 * A
 */
function f(a: 0): void;
function f(a: number): void;
function f(a: number) {
}
f(1);
```

**Expected behavior:**

`f(1)` has documented info `A`.

**Actual behavior:**

`f(1)` has no documented info.

**Playground Link:**  

**Related Issues:**

**Comment by mhegazy** [comment]
PRs welcomed.

**Comment by ajafff** [comment]
This needs a little more thought than the opening post describes:
Does it only use the description or tags as well? 
Should it only look at other signatures if the current signature has no jsdoc comment at all? 
How should `@param` tags of other signatures be handled?
This may be kind of a braking change if it also uses `@deprecated` tag of another signature.

**Comment by sandersn** [comment]
Duplicate of #407
