### ISSUE TITLE
Implement stage 3 syntax for private fields, methods, getters, and setters

### ISSUE THREAD

**Issue by jhpratt** [Microsoft/TypeScript#24418]
## Suggestion

Compatibility with the following TC39 proposals (both are currently stage 3)

* [Private fields](https://github.com/tc39/proposal-class-fields)
* [Private methods](https://github.com/tc39/proposal-private-methods)

The only thing that could really be debated on the TS side of things is if it should emit `#field` or treat it identically to the existing TS `private` keyword.

## Use Cases

See TC39's discussion. This is solely for compatibility with multiple stage 3 proposals.

## Examples

Stealing an example from the second link above, sans type declarations (that is irrelevant here).

```javascript
class Counter extends HTMLElement {
  #xValue = 0;

  get #x() { return #xValue; }
  set #x(value) {
    this.#xValue = value; 
    window.requestAnimationFrame(this.#render.bind(this));
  }

  #clicked() {
    this.#x++;
  }

  constructor() {
    super();
    this.onclick = this.#clicked.bind(this);
  }

  connectedCallback() { this.#render(); }

  #render() {
    this.textContent = this.#x.toString();
  }
}
```

Should be treated as the equivalent to

```typescript
class Counter extends HTMLElement {
  private xValue = 0;

  get x() { return this.xValue; }
  set x(value) {
    this.xValue = value; 
    window.requestAnimationFrame(this.render.bind(this));
  }

  private clicked() {
    this.x++;
  }

  constructor() {
    super();
    this.onclick = this.clicked.bind(this);
  }

  connectedCallback() { this.render(); }

  render() {
    this.textContent = this.x.toString();
  }
}
```

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by mhegazy** [comment]
Duplicate https://github.com/Microsoft/TypeScript/issues/9950

**Comment by jhpratt** [comment]
That's specific to only private fields, so not a complete duplicate. Much of the comments are complaints about the syntax, which is simply the wrong place for such discussion. 

Leaving open for the private methods if nothing else.

**Comment by mhegazy** [comment]
We are using #9950 to track the whole proposal. Feel free to add a comment to it.

We also are following the discussions in TC39 regarding all the new class proposals.
