### ISSUE TITLE
Degenerated Union Type

### ISSUE THREAD

**Issue by kzaher** [Microsoft/TypeScript#24412]
**TypeScript Version:**  3.0.0-dev.20180522, 2.8.3

**Search Terms:** 
degenerated union type

**Code**

```ts
export type Cases = {
  kind: 'A'
} /*| {
  kind: 'B'
}*/;

function unhandledCase(never: never) {
  return never;
}

function testFunction(instance: Cases) {
  switch (instance.kind) {
    case 'A':
      return instance;
    /* case 'B':
      return instance;*/
    default:
      return unhandledCase(instance);
  }
}
```

**Expected behavior:**

I expect no compile errors. If one uncomments the commented parts, the code compiles perfectly.

```ts
export type Cases = {
  kind: 'A'
} | {
  kind: 'B'
};

function unhandledCase(never: never) {
  return never;
}

function testFunction(instance: Cases) {
  switch (instance.kind) {
    case 'A':
      return instance;
    case 'B':
      return instance;
    default:
      return unhandledCase(instance);
  }
}
```

**Actual behavior:**

I get a compile time error
```
{
	"resource": "index.ts",
	"owner": "typescript",
	"code": "2345",
	"severity": 8,
	"message": "Argument of type 'Cases' is not assignable to parameter of type 'never'.",
	"source": "ts",
	"startLineNumber": 18,
	"startColumn": 28,
	"endLineNumber": 18,
	"endColumn": 36
}
```

**Playground Link:**  

[PlaygroundLink](http://www.typescriptlang.org/play/index.html#src=%2F%2F%20uncomment%20the%20commented%20parts%20and%20it%20will%20work%0D%0A%0D%0Aexport%20type%20Cases%20%3D%20%7B%0D%0A%20%20kind%3A%20'A'%0D%0A%7D%20%2F*%7C%20%7B%0D%0A%20%20kind%3A%20'B'%0D%0A%7D*%2F%3B%0D%0A%0D%0Afunction%20unhandledCase(never%3A%20never)%20%7B%0D%0A%20%20return%20never%3B%0D%0A%7D%0D%0A%0D%0Afunction%20testFunction(instance%3A%20Cases)%20%7B%0D%0A%20%20switch%20(instance.kind)%20%7B%0D%0A%20%20%20%20case%20'A'%3A%0D%0A%20%20%20%20%20%20return%20instance%3B%0D%0A%20%20%20%20%2F%2F%20case%20'B'%3A%0D%0A%20%20%20%20%2F%2F%20%20%20return%20instance%3B%0D%0A%20%20%20%20default%3A%0D%0A%20%20%20%20%20%20return%20unhandledCase(instance)%3B%0D%0A%20%20%7D%0D%0A%7D)

**Related Issues:** 
¯\\\_(ツ)\_/¯

**Comment by mhegazy** [comment]
narrowing only works on values that are declared to have union types. this saves the compiler a whole additional set of computations that are not needed.

**Comment by mhegazy** [comment]
Add a type assertion for `instance` to `never`?
