### ISSUE TITLE
Source maps seems not to work at destructuring statements

### ISSUE THREAD

**Issue by adrienboulle** [microsoft/TypeScript#24419]
**TypeScript Version:**  3.0.0-dev.20180522

**Search Terms:** 
source maps destructuring

**Code**

```ts
const { uid: modalId } = this.open({
  context: {
    onSubmit: () => {
      console.log('in onSubmit');
    },
  },
});
```

**Expected behavior:**
sources map should make it possible to add breakpoints at `console.log('in onSubmit');`
(works in vanilla js)

**Actual behavior:**
Breakpoints are not possible
![image](https://user-images.githubusercontent.com/14262895/40561677-54494c36-605e-11e8-99f7-acf6de844e25.png)

**Comment by andy-ms** [comment]
#23346 would have changed this, wonder if that would affect it. @rbuckton

**Comment by adrienboulle** [comment]
@andy-ms still here in 3.1.0-dev.20180830

**Comment by adrienboulle** [comment]
@andy-ms still here in 3.3.0-dev.20190105
I don't know what is your status about this issue but as a full time typescript user, this issue mean that we just can't use destructuring in some cases.
