### ISSUE TITLE
Generic class method with `this` parameter hinders intellisense

### ISSUE THREAD

**Issue by AnyhowStep** [Microsoft/TypeScript#24424]
**TypeScript Version:**  Version 2.9.0-dev.20180516

**Search Terms:** generic this parameter auto-complete

**Code**

```ts
class C<T0, T1> {
    
    constructor(
        public t0: T0,
        public t1: T1
    ) {
        
    }
    execute(this: C<T0, number>) {
        console.log("hi")
    }
}
const c = new C(1, 2);
c.execute(); //Runs, no errors, but not in auto-complete

class D<T0, T1> {
    
    constructor(
        public t0: T0,
        public t1: T1
    ) {
        
    }
    execute(this: C<any, number>) {
        console.log("hi")
    }
}

const d = new D(1, 2);
d.execute(); //In auto-complete
```

**Expected behavior:**

`c.execute()` should show up in intellisense.

If it is a valid method call and the types match, it seems like it should appear.

**Actual behavior:**

`c.execute` does not show up in intellisense, but can be called safely.

**Playground Link:**[Here](http://www.typescriptlang.org/play/#src=class%20C%3CT0%2C%20T1%3E%20%7B%0D%0A%20%20%20%20%0D%0A%20%20%20%20constructor(%0D%0A%20%20%20%20%20%20%20%20public%20t0%3A%20T0%2C%0D%0A%20%20%20%20%20%20%20%20public%20t1%3A%20T1%0D%0A%20%20%20%20)%20%7B%0D%0A%20%20%20%20%20%20%20%20%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20execute(this%3A%20C%3CT0%2C%20number%3E)%20%7B%0D%0A%20%20%20%20%20%20%20%20console.log(%22hi%22)%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0Aconst%20c%20%3D%20new%20C(1%2C%202)%3B%0D%0Ac.execute()%3B%20%2F%2FRuns%2C%20no%20errors%2C%20but%20not%20in%20auto-complete%0D%0A%0D%0Aclass%20D%3CT0%2C%20T1%3E%20%7B%0D%0A%20%20%20%20%0D%0A%20%20%20%20constructor(%0D%0A%20%20%20%20%20%20%20%20public%20t0%3A%20T0%2C%0D%0A%20%20%20%20%20%20%20%20public%20t1%3A%20T1%0D%0A%20%20%20%20)%20%7B%0D%0A%20%20%20%20%20%20%20%20%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20execute(this%3A%20C%3Cany%2C%20number%3E)%20%7B%0D%0A%20%20%20%20%20%20%20%20console.log(%22hi%22)%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aconst%20d%20%3D%20new%20D(1%2C%202)%3B%0D%0Ad.execute()%3B%20%2F%2FIn%20auto-complete)

**Comment by andy-ms** [comment]
This works for me in ` typescript@2.9.0-dev.20180516` and in the playground. Maybe you need to set [`typescript.tsdk`](https://code.visualstudio.com/Docs/languages/typescript)?
