### ISSUE TITLE
Consolidating the two most popular JavaScript type systems

### ISSUE THREAD

**Issue by NameFILIP** [Microsoft/TypeScript#24421]
It might not be easy, but I believe it would be beneficial for everyone in JS community to have a path of consolidating the two type systems. Please see https://github.com/tc39/ecma262/issues/45

**Comment by RyanCavanaugh** [comment]
TypeScript and Flow (I'm assuming this is the other one you're referring to, although there are other JS-based typed languages) have reasonably different aims, design goals, and approaches. Clearly TS isn't perfect or FB wouldn't have funded Flow, and clearly Flow isn't perfect or everyone would use TS, and it's a good thing that people are able choose from a variety of type systems depending on their preferences and applications.

We've worked with Flow on some things in the past and will continue to collaborate where it makes sense. "Consolidation" would just be the production of [a third language](https://xkcd.com/927/).
