### ISSUE TITLE
Conditional type incorrectly resolves when used recursively with mapped type

### ISSUE THREAD

**Issue by minedeljkovic** [Microsoft/TypeScript#24433]
**TypeScript Version:** 
Playground

**Search Terms:** 
Recursive Conditional Mapped

**Code**

```ts
type NumberOptions = { value: number }
type StringOptions = { value: string }
type ObjectOptions<O> = { fields: { [K in keyof O]: MapToOptions<K> } }

type MapToOptions<X> =
    X extends number ? NumberOptions :
    X extends string ? StringOptions :
    X extends {} ? ObjectOptions<X> :
    never

const optObj1: MapToOptions<{ name: string, age: number }> = {
    fields: {
        name: { value: '' },
        age: { value: 1 }
    },
};
```

**Expected behavior:**
`fields` field in optObj1 should be resolved to { name: StringOptions, age: NumberOptions }

**Actual behavior:**
`fields` field in optObj1 resolves to { name: StringOptions, age: StringOptions }

**Playground Link:**
https://www.typescriptlang.org/play/index.html#src=type%20NumberOptions%20%3D%20%7B%20value%3A%20number%20%7D%0D%0Atype%20StringOptions%20%3D%20%7B%20value%3A%20string%20%7D%0D%0Atype%20ObjectOptions%3CO%3E%20%3D%20%7B%20fields%3A%20%7B%20%5BK%20in%20keyof%20O%5D%3A%20MapToOptions%3CK%3E%20%7D%20%7D%0D%0A%0D%0Atype%20MapToOptions%3CX%3E%20%3D%0D%0A%20%20%20%20X%20extends%20number%20%3F%20NumberOptions%20%3A%0D%0A%20%20%20%20X%20extends%20string%20%3F%20StringOptions%20%3A%0D%0A%20%20%20%20X%20extends%20%7B%7D%20%3F%20ObjectOptions%3CX%3E%20%3A%0D%0A%20%20%20%20never%0D%0A%0D%0Aconst%20optObj1%3A%20MapToOptions%3C%7B%20name%3A%20string%2C%20age%3A%20number%20%7D%3E%20%3D%20%7B%0D%0A%20%20%20%20fields%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20name%3A%20%7B%20value%3A%20''%20%7D%2C%0D%0A%20%20%20%20%20%20%20%20age%3A%20%7B%20value%3A%201%20%7D%0D%0A%20%20%20%20%7D%2C%0D%0A%7D%3B%0D%0A

**Related Issues:**
Couldn't find

**Comment by sledorze** [comment]
@minedeljkovic 

Corrected version here:
https://www.typescriptlang.org/play/index.html#src=type%20NumberOptions%20%3D%20%7B%20value%3A%20number%20%7D%0D%0Atype%20StringOptions%20%3D%20%7B%20value%3A%20string%20%7D%0D%0Atype%20ObjectOptions%3CO%3E%20%3D%20%7B%20fields%3A%20%7B%20%5BK%20in%20keyof%20O%5D%3A%20MapToOptions%3CO%5BK%5D%3E%20%7D%20%7D%0D%0A%0D%0Atype%20MapToOptions%3CX%3E%20%3D%0D%0A%20%20%20%20X%20extends%20number%20%3F%20NumberOptions%20%3A%0D%0A%20%20%20%20X%20extends%20string%20%3F%20StringOptions%20%3A%0D%0A%20%20%20%20X%20extends%20%7B%7D%20%3F%20ObjectOptions%3CX%3E%20%3A%0D%0A%20%20%20%20never%0D%0A%0D%0Aconst%20optObj1%3A%20MapToOptions%3C%7B%20name%3A%20string%2C%20age%3A%20number%20%7D%3E%20%3D%20%7B%0D%0A%20%20%20%20fields%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20name%3A%20%7B%20value%3A%20''%20%7D%2C%0D%0A%20%20%20%20%20%20%20%20age%3A%20%7B%20value%3A%201%20%7D%0D%0A%20%20%20%20%7D%2C%0D%0A%7D%3B%0D%0A

**Comment by minedeljkovic** [comment]
Of course, thanks @sledorze , my bad
