### ISSUE TITLE
Import declarations seems to break `namespace` compilation

### ISSUE THREAD

**Issue by nikkatalnikov** [Microsoft/TypeScript#24432]
**TypeScript Version:**  2.8.1

**Search Terms:** 
namespace
import
**Code**

```ts
import { Moment } from 'moment'

declare namespace Models {
  export interface ITimeFrame {
    [key: string]: Array<{
      foo: number
      start: Moment
      end: Moment
    }>
  }
}
```

**Expected behavior:**
Compiles fine

**Actual behavior:**
Webstorm spits out an error.

```
**/service.ts
Error:(12, 17) TS2503: Cannot find namespace 'Models'.
Error:(30, 30) TS2503: Cannot find namespace 'Models'.
Error:(99, 11) TS2503: Cannot find namespace 'Models'.
Error:(100, 6) TS2503: Cannot find namespace 'Models'.
Error:(119, 11) TS2503: Cannot find namespace 'Models'.
Error:(120, 6) TS2503: Cannot find namespace 'Models'.
Error:(146, 11) TS2503: Cannot find namespace 'Models'.
Error:(146, 56) TS2503: Cannot find namespace 'Models'.
Error:(147, 6) TS2503: Cannot find namespace 'Models'.
```

once `import` declaration and       
```
start: Moment
end: Moment
```

are removed, it compiles fine.

also, even `import` declaration by itself, without  
```
start: Moment
end: Moment
```

breaks compilation with the same result.

tsconfig:

```
{
  "compilerOptions": {
    "target": "es2015",
    "module": "commonjs",
    "noImplicitAny": false,
    "alwaysStrict": true,
    "strictNullChecks": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true
  },
  "exclude":[
    "node_modules",
    "./src/**/*.spec.ts"
  ]
}
```

**Comment by nikkatalnikov** [comment]
@mhegazy 
why the issue has been closed?

**Comment by mhegazy** [comment]
Modules (i.e. a file with a top lever `import` or `export`) introduce their own scope.

**Comment by nikkatalnikov** [comment]
ok, so, how can i use imported type in interface declaration? only without `namespace` pragma?

**Comment by mhegazy** [comment]
https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#import-types

**Comment by nikkatalnikov** [comment]
your example is not helpful at all, `import` is not possible due to error msg:

`Error:(136, 3) TS1036: Statements are not allowed in ambient contexts.`

**Comment by nikkatalnikov** [comment]
Apparently, the problem was in moment.js itself

https://github.com/moment/moment/issues/3680#issuecomment-317701571

creating moment.shim.d.ts:
```
import * as moment from 'moment'
export as namespace moment
export = moment
```

and then declaring 

```
  export interface ITimeFrame {
    foo: number
    bar: string
    start: moment.Moment
    end: moment.Moment
  }
```

works fine.
