### ISSUE TITLE
Typescript server should support passing format options on format request

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#2443]
Refers to the code in src/server

Current format options can either globally configured are defined via an open call. Since formatting options can change dynamically (auto detected) or changed without open/closing a file the protocol should support sending them. The TS language service already support formatting options in the corresponding methods.

**Comment by dbaeumer** [comment]
If this is something the server would accept I will work on a pull request.

**Comment by steveluc** [comment]
@dbaeumer the server has a configure message that can set format options tabSize and indentSize (it takes an optional file name so that the options can be applied to single files).  If you need additional formatting options, we'd welcome a pull request that adds them as optional fields to the configure request.

**Comment by steveluc** [comment]
Adding the formatting options as an optional object parameter to the formatting request messages would also be fine.

**Comment by dbaeumer** [comment]
@steveluc opened pull request #2468. Forgot to use automatic linking,,,

The pull request only adds format options to the format requests. I am happy to work on adding the options to configure and open requests as well but wanted to get your opinion on whether we should add an options property to those and deprecate tabSize and indentSize or whether you want to list them individually.

I also fixed a problem with indentation correction and tabs. This revealed when using convertTabsToSpace set to false.

**Comment by dbaeumer** [comment]
Closing. Got fixed via #2489
