### ISSUE TITLE
Compiler API (language service) becomes incredibly slow when `noEmitOnError = true`

### ISSUE THREAD

**Issue by AlCalzone** [Microsoft/TypeScript#24444]
**TypeScript Version:**  3.0.0-dev.20180526

**Search Terms:** compiler api noEmitOnError

I'm building an in-memory version of the TypeScript compiler using the language service API. This allows to compile and generate declarations for files that never reach the hard disk. While debugging another issue, I found that setting `noEmitOnError` to `true` drastically increases compile times with minor changes to the compiled sources.
I'm not 100% sure that the problem doesn't come from me misusing the API, so forgive me if this is actually not an issue in TypeScript.

**Code**
This is too much for a short repro, so I created a repro repo here: 
https://github.com/AlCalzone/virtual-tsc/tree/ts-repro
To reproduce, `npm install` and then `npm test`. The project will run a few simple compilations using the language service API. It contains two identical test cases, where one has `noEmitOnError = true` and the other one `false`.

Both test cases correctly compile correct code and both catch syntax errors.

**Expected behavior:**
Similar results for both.

**Actual behavior:**
```
  compiler API repro =>
    √ noEmitOnError = false (2265ms)
    √ noEmitOnError = true (13794ms)
  2 passing (16s)
```

**Related Issues:** none found

**Comment by RyanCavanaugh** [comment]
Didn't see anything obviously wrong with the way things were being called.

It'd be great if you could identify when this regressed

**Comment by AlCalzone** [comment]
TS 2.7.2:
```
  compiler API repro =>
    √ noEmitOnError = false (2021ms)
    √ noEmitOnError = true (13184ms)
```

TS 2.6.2:
```
  compiler API repro =>
    √ noEmitOnError = false (1580ms)
    √ noEmitOnError = true (10238ms)
```

TS 2.5.3:
```
  compiler API repro =>
    √ noEmitOnError = false (1526ms)
    √ noEmitOnError = true (7848ms)
```

TS 2.4.2:
(with different signature of `ServiceHost.readDirectory`)
```
  compiler API repro =>
    √ noEmitOnError = false (1546ms)
    √ noEmitOnError = true (7726ms)
```

TS 2.3.4:
```
  compiler API repro =>
    √ noEmitOnError = false (1538ms)
    √ noEmitOnError = true (7241ms)
```

TS 2.2.2:
```
  compiler API repro =>
    √ noEmitOnError = false (1049ms)
    √ noEmitOnError = true (3772ms)
```

TS 2.1.6:
```
  compiler API repro =>
    √ noEmitOnError = false (1063ms)
    √ noEmitOnError = true (3530ms)
```

TS 2.0 doesn't work.

**Comment by sheetalkamat** [comment]
The time spent in ```noEmitOnError``` is in calculation of declaration diagnostics which isn't done if noEmitOnError is false. 
In the test, declaration = true for compiler options ([link](https://github.com/AlCalzone/virtual-tsc/blob/ts-repro/src/server.ts#L24)) is set and that's the reason you are seeing this.

**Comment by AlCalzone** [comment]
What exactly do you mean by "declaration diagnostics"? 
Since I do need the declarations, is there a better way to detect that the compilation had errors than setting `noEmitOnError` to true and spending an extra 10 seconds?

I still find it weird that the time needed for that almost doubled from 2.5 to 2.7. Also when I try to reproduce the test manually using the `tsc` CLI, both settings for `noEmitOnError` take roughly 2 seconds.
