### ISSUE TITLE
overload interface property perform confused

### ISSUE THREAD

**Issue by yangdonglai** [Microsoft/TypeScript#24441]
**TypeScript Version:**  2.8.3

**Search Terms:** 

**Code**

```ts
interface Overload {
  id: 'jack' | 'mary' 
}

// what i use now 
interface OverloadWithAny extends Overload {
   id:'jack' | 'mary' | 'ross' | any
}

// expect the bellow succeed
interface OverloadDirectly extends Overload {
  id: 'jack' | 'mary' | 'ross'
}
```

**Expected behavior:**

overload  directly succeed

**Actual behavior:**
overload only succeed when add  `any` type 

**Playground Link:** [link](http://www.typescriptlang.org/play/index.html#src=interface%20Overload%20%7B%0D%0A%20%20id%3A%20'jack'%20%7C%20'mary'%20%0D%0A%7D%0D%0A%0D%0A%2F%2F%20what%20i%20use%20now%20%0D%0Ainterface%20OverloadWithAny%20extends%20Overload%20%7B%0D%0A%20%20%20id%3A'jack'%20%7C%20'mary'%20%7C%20'ross'%20%7C%20any%0D%0A%7D%0D%0A%0D%0A%2F%2F%20expect%20the%20bellow%20succeed%0D%0Ainterface%20OverloadDirectly%20extends%20Overload%20%7B%0D%0A%20%20id%3A%20'jack'%20%7C%20'mary'%20%7C%20'ross'%0D%0A%7D%0D%0A%0D%0A)

**Related Issues:** 

**remark:** it is confused.Is overload property directly failed  is a bug? Or is overload with `any` type succeed is a bug?

**Comment by MartinJohns** [comment]
How would you expect this to work? `OverloadDirectly` must be compatible to `Overload`, but when `OverloadDirectly` has `'ross'` as an `id` it's not compatible anymore.

```
const abc: OverloadDirectly = { id: 'ross' };
const def: Overload = abc; // OverloadDirectly inherits from Overload so an assignment should work, but suddenly Overload.id has an invalid value.
```

**Comment by yangdonglai** [comment]
@MartinJohns yes, it is what I want to get. Add  a valid value for the `id` property.

this come because  I inherits  a  module base on a third part module which already has a  `@types/XX` declaration . I want extend a declaration module for mine base on the base module's declaration module. That is why i want to add another value for the `id` property.

Besides, is there a official method that  make 'ross' right for 'id' property. And is the overloadWithAny  a bug?

**Comment by MartinJohns** [comment]
You can not add a new possible type to `id` if you want to stay compatible with `Overload`. If compatibility is not necessary (meaning a value of your new type can't be passed as an argument to a method accepting `Overload`), then you could create some magic type using conditional types that represents a new type with your `id` addition.

**Comment by yangdonglai** [comment]
Indeed,  for my situation, compatibility is necessary。My custom type need pass to a third module Class.method which accept `Overload `。

So, I guess I still need to use the `OverloadWithAny` method.

But what I am still confused is whether this method is actually a  syntax bug of Typescript.

**Comment by yangdonglai** [comment]
Anyway, thank you for help @MartinJohns

**Comment by RyanCavanaugh** [comment]
Not a bug
