### ISSUE TITLE
Incorrect type refinement to `null` with `strictNullCheck`

### ISSUE THREAD

**Issue by nunocastromartins** [Microsoft/TypeScript#24445]
**TypeScript Version:**  2.8.3 (currently can't test on a more recent version, sorry)

**Search Terms:** Wrong type inference; invalid type refinement; type becomes `null`

**Code**
```ts
let x: string | null = null;

['some element'].forEach(() => {
  x = 'some value';
});

x; // Has type `null`
```

**Expected behavior:**
At the end, `x` should have type `string | null`.

**Actual behavior:**
At the end, `x` has type `null`.

**Playground Link:** [Here](http://www.typescriptlang.org/play/index.html#src=let%20x%3A%20string%20%7C%20null%20%3D%20null%3B%0D%0A%0D%0A%5B'some%20element'%5D.forEach(()%20%3D%3E%20%7B%0D%0A%20%20x%20%3D%20'some%20value'%3B%0D%0A%7D)%3B%0D%0A%0D%0Ax%3B%20%2F%2F%20Has%20type%20%60null%60) (requires `strictNullChecks`)

**Related Issues:**
I didn't find any; hope it's not a duplicate.

**Comment by nunocastromartins** [comment]
Also interesting (link [here](http://www.typescriptlang.org/play/index.html#src=let%20x%3A%20string%20%7C%20undefined%20%3D%20undefined%3B%0D%0A%0D%0A%5B'some%20element'%5D.forEach(()%20%3D%3E%20%7B%0D%0A%20%20x%20%3D%20'some%20value'%3B%0D%0A%7D)%3B%0D%0A%0D%0Ax%3B%20%2F%2F%20Has%20type%20%60undefined%60)):
```ts
let x: string | undefined = undefined;

['some element'].forEach(() => {
  x = 'some value';
});

x; // Has type `undefined`
```
but (link [here](http://www.typescriptlang.org/play/index.html#src=let%20x%3A%20string%20%7C%20undefined%3B%0D%0A%0D%0A%5B'some%20element'%5D.forEach(()%20%3D%3E%20%7B%0D%0A%20%20x%20%3D%20'some%20value'%3B%0D%0A%7D)%3B%0D%0A%0D%0Ax%3B%20%2F%2F%20Has%20type%20%60undefined%60)):
```ts
let x: string | undefined;

['some element'].forEach(() => {
  x = 'some value';
});

x; // Has type `string | undefined` has expected
```

**Comment by j-oliveras** [comment]
Duplicate of #11498 and #9998.

**Comment by nunocastromartins** [comment]
I'll close the issue but I still believe that this is a bug and not a _trade-off_: when I declare a type, if TS doesn't know if the inner function will or not be executed, it should assume the worse and not refine the type. Those are my two cents on the issue but I'm sure there are other intricacies.

Either way, thank you for your work and for referencing the original issues. I apologise for the added noise.
