### ISSUE TITLE
Conditional says type extends base type, but cannot use as base type

### ISSUE THREAD

**Issue by AnyhowStep** [microsoft/TypeScript#24456]
**TypeScript Version:**  2.9.0-dev.20180516

**Search Terms:** conditional type, base, cannot be used to index

### Example 1

**Code**

```ts
interface Item {
    field : number
}
type TryGetFieldValue<T, K extends string> = (
    K extends keyof T ?
        (
            T[K] extends Item ?
                //Expected:
                //Should work, T[K] extends Item.
                //So, it should have `field`
                //Actual:
                //Type '"field"' cannot be used to index type 'T[K]'.
                T[K]["field"] :
                never
        ) :
        never
);

//`x` is of type `4`, as expected
type x = TryGetFieldValue<
    {
        test: { field : 4 }
    },
    "test"
>
```

**Expected behavior:**

`T[K]["field"]` should work because `T[K] extends Item`

**Actual behavior:**

`Type '"field"' cannot be used to index type 'T[K]'.`

**Playground Link:** [Example 1](http://www.typescriptlang.org/play/#src=interface%20Item%20%7B%0D%0A%20%20%20%20field%20%3A%20number%0D%0A%7D%0D%0Atype%20TryGetFieldValue%3CT%2C%20K%20extends%20string%3E%20%3D%20(%0D%0A%20%20%20%20K%20extends%20keyof%20T%20%3F%0D%0A%20%20%20%20%20%20%20%20(%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20T%5BK%5D%20extends%20Item%20%3F%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2FExpected%3A%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2FShould%20work%2C%20T%5BK%5D%20extends%20Item.%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2FSo%2C%20it%20should%20have%20%60field%60%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2FActual%3A%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2FType%20'%22field%22'%20cannot%20be%20used%20to%20index%20type%20'T%5BK%5D'.%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20T%5BK%5D%5B%22field%22%5D%20%3A%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20never%0D%0A%20%20%20%20%20%20%20%20)%20%3A%0D%0A%20%20%20%20%20%20%20%20never%0D%0A)%3B%0D%0A%0D%0A%2F%2F%60x%60%20is%20of%20type%20%604%60%2C%20as%20expected%0D%0Atype%20x%20%3D%20TryGetFieldValue%3C%0D%0A%20%20%20%20%7B%0D%0A%20%20%20%20%20%20%20%20test%3A%20%7B%20field%20%3A%204%20%7D%0D%0A%20%20%20%20%7D%2C%0D%0A%20%20%20%20%22test%22%0D%0A%3E)

### Example 2

**Code**

```ts
interface Item {
    field : number
}
type TypeOfField<T extends Item> = T["field"];

type TryGetFieldValue<T, K extends string> = (
    K extends keyof T ?
        (
            T[K] extends Item ?
                //Expected:
                //Should work, T[K] extends Item.
                //Actual:
                //Type 'T[K]' does not satisfy the constraint 'Item'.
                TypeOfField<T[K]> :
                never
        ) :
        never
);

//`x` is of type `4`, as expected
type x = TryGetFieldValue<
    {
        test: { field : 4 }
    },
    "test"
>
```

**Expected behavior:**

`TypeOfField<T[K]>` should work because `T[K] extends Item`

**Actual behavior:**

`Type 'T[K]' does not satisfy the constraint 'Item'.`

**Playground Link:** [Example 2](http://www.typescriptlang.org/play/#src=interface%20Item%20%7B%0D%0A%20%20%20%20field%20%3A%20number%0D%0A%7D%0D%0Atype%20TypeOfField%3CT%20extends%20Item%3E%20%3D%20T%5B%22field%22%5D%3B%0D%0A%0D%0Atype%20TryGetFieldValue%3CT%2C%20K%20extends%20string%3E%20%3D%20(%0D%0A%20%20%20%20K%20extends%20keyof%20T%20%3F%0D%0A%20%20%20%20%20%20%20%20(%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20T%5BK%5D%20extends%20Item%20%3F%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2FExpected%3A%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2FShould%20work%2C%20T%5BK%5D%20extends%20Item.%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2FActual%3A%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2FType%20'T%5BK%5D'%20does%20not%20satisfy%20the%20constraint%20'Item'.%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20TypeOfField%3CT%5BK%5D%3E%20%3A%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20never%0D%0A%20%20%20%20%20%20%20%20)%20%3A%0D%0A%20%20%20%20%20%20%20%20never%0D%0A)%3B%0D%0A%0D%0A%2F%2F%60x%60%20is%20of%20type%20%604%60%2C%20as%20expected%0D%0Atype%20x%20%3D%20TryGetFieldValue%3C%0D%0A%20%20%20%20%7B%0D%0A%20%20%20%20%20%20%20%20test%3A%20%7B%20field%20%3A%204%20%7D%0D%0A%20%20%20%20%7D%2C%0D%0A%20%20%20%20%22test%22%0D%0A%3E)

**Related Issues:**

**Comment by mhegazy** [comment]
A generic type is narrowed only in a distributive conditional type, you can refactor your code to use a type alias: 

```ts
type FieldOf<T> = T extends Item ?
    T["field"] :
    never;

type TryGetFieldValue<T, K extends string> = (
    K extends keyof T ? FieldOf<T[K]> : never
);
```

See https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#distributive-conditional-types for some details about distributive conditional types.
