### ISSUE TITLE
Ramda

### ISSUE THREAD

**Issue by geomen888** [Microsoft/TypeScript#24455]
**TypeScript Version:**  3.0.0-dev.20180526

**Search Terms:** 

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**Expected behavior:**
node_modules/@types/ramda/src/$operation.d.ts:15:54 - error TS2344: Type 'keyof T' does not satisfy the constraint 'string'.
  Type 'string | number | symbol' is not assignable to type 'string'.
    Type 'number' is not assignable to type 'string'.

15 export type Omit<T, K extends string> = Pick<T, Diff<keyof T, K>>;
                                                        ~~~~~~~


node_modules/@types/ramda/src/$operation.d.ts:17:35 - error TS2344: Type 'keyof U' does not satisfy the constraint 'string'.
  Type 'string | number | symbol' is not assignable to type 'string'.
    Type 'number' is not assignable to type 'string'.

17 export type Merge<T, U> = Omit<T, keyof U> & U;
                                     ~~~~~~~

node_modules/@types/ramda/src/dissoc.d.ts:59:69 - error TS2344: Type 'K' does not satisfy the constraint 'string'.
  Type 'keyof T' is not assignable to type 'string'.
    Type 'string | number | symbol' is not assignable to type 'string'.
      Type 'number' is not assignable to type 'string'.

59 type dissoc_keyof_11<T extends object, K extends keyof T> = Omit<T, K>;
                                                                       ~

node_modules/@types/ramda/src/mergeWith.d.ts:76:39 - error TS2344: Type 'keyof U' does not satisfy the constraint 'string'.
  Type 'string | number | symbol' is not assignable to type 'string'.
    Type 'number' is not assignable to type 'string'.

76 type mergeWith_111<T, U, W> = Omit<T, keyof U> & Omit<U, keyof T> & Record<Same<keyof T, keyof U>, W>;
                                         ~~~~~~~


node_modules/@types/ramda/src/mergeWith.d.ts:76:58 - error TS2344: Type 'keyof T' does not satisfy the constraint 'string'.
  Type 'string | number | symbol' is not assignable to type 'string'.
    Type 'number' is not assignable to type 'string'.

76 type mergeWith_111<T, U, W> = Omit<T, keyof U> & Omit<U, keyof T> & Record<Same<keyof T, keyof U>, W>;
                                                            ~~~~~~~

node_modules/@types/ramda/src/mergeWith.d.ts:76:81 - error TS2344: Type 'keyof T' does not satisfy the constraint 'string'.

76 type mergeWith_111<T, U, W> = Omit<T, keyof U> & Omit<U, keyof T> & Record<Same<keyof T, keyof U>, W>;
                                                                                   ~~~~~~~


node_modules/@types/ramda/src/mergeWithKey.d.ts:78:42 - error TS2344: Type 'keyof U' does not satisfy the constraint 'string'.
  Type 'string | number | symbol' is not assignable to type 'string'.
    Type 'number' is not assignable to type 'string'.

78 type mergeWithKey_111<T, U, W> = Omit<T, keyof U> & Omit<U, keyof T> & Record<Same<keyof T, keyof U>, W>;
                                            ~~~~~~~

node_modules/@types/ramda/src/mergeWithKey.d.ts:78:61 - error TS2344: Type 'keyof T' does not satisfy the constraint 'string'.
  Type 'string | number | symbol' is not assignable to type 'string'.
    Type 'number' is not assignable to type 'string'.

78 type mergeWithKey_111<T, U, W> = Omit<T, keyof U> & Omit<U, keyof T> & Record<Same<keyof T, keyof U>, W>;
                                                               ~~~~~~~


node_modules/@types/ramda/src/mergeWithKey.d.ts:78:84 - error TS2344: Type 'keyof T' does not satisfy the constraint 'string'.

78 type mergeWithKey_111<T, U, W> = Omit<T, keyof U> & Omit<U, keyof T> & Record<Same<keyof T, keyof U>, W>;
                                                                                      ~~~~~~~

node_modules/@types/ramda/src/omit.d.ts:59:52 - error TS2344: Type 'K' does not satisfy the constraint 'string'.
  Type 'keyof T' is not assignable to type 'string'.
    Type 'string | number | symbol' is not assignable to type 'string'.
      Type 'number' is not assignable to type 'string'.

59 type omit_keyof_11<T, K extends keyof T> = Omit<T, K>;
                                                      ~

node_modules/@types/ramda/src/pickBy.d.ts:25:81 - error TS2344: Type 'keyof U' does not satisfy the constraint 'string'.
  Type 'string | number | symbol' is not assignable to type 'string'.
    Type 'number' is not assignable to type 'string'.

25     <T extends {}, U extends Dictionary<T>>(fn: KeyedObjectMorphism<T, boolean, keyof U>): pickBy_10<T, U>;
                                                                                   ~~~~~~~


node_modules/@types/ramda/src/pickBy.d.ts:27:104 - error TS2344: Type 'keyof U' does not satisfy the constraint 'string'.
  Type 'string | number | symbol' is not assignable to type 'string'.
    Type 'number' is not assignable to type 'string'.

27     <$SEL extends "11">(): <T extends {}, U extends Dictionary<T>>(fn: KeyedObjectMorphism<T, boolean, keyof U>, object: U) => pickBy_11<T, U>;
                                                                                                          ~~~~~~~

node_modules/@types/ramda/src/pickBy.d.ts:29:103 - error TS2344: Type 'keyof U' does not satisfy the constraint 'string'.
  Type 'string | number | symbol' is not assignable to type 'string'.
    Type 'number' is not assignable to type 'string'.

29     <$SEL extends "1">(): <T extends {}, U extends Dictionary<T>>(fn: KeyedObjectMorphism<T, boolean, keyof U>) => pickBy_10<T, U>;
                                                                                                         ~~~~~~~


node_modules/@types/ramda/src/pickBy.d.ts:30:81 - error TS2344: Type 'keyof U' does not satisfy the constraint 'string'.
  Type 'string | number | symbol' is not assignable to type 'string'.
    Type 'number' is not assignable to type 'string'.

30     <T extends {}, U extends Dictionary<T>>(fn: KeyedObjectMorphism<T, boolean, keyof U>, object: U): pickBy_11<T, U>;
                                                                                   ~~~~~~~

node_modules/@types/ramda/src/pickBy.d.ts:36:42 - error TS2344: Type 'keyof U' does not satisfy the constraint 'string'.
  Type 'string | number | symbol' is not assignable to type 'string'.
    Type 'number' is not assignable to type 'string'.

36     (fn: KeyedObjectMorphism<T, boolean, keyof U>): pickBy_11<T, U>;
                                            ~~~~~~~


npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! aep-server@1.0.0 compile: `tsc -p ./tsconfig.json`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the aep-server@1.0.0 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/geo/.npm/_logs/2018-05-29T14_09_05_459Z-debug.log
error Command failed with exit code 2.

**Actual behavior:**

**Playground Link:** <!-- A link to a TypeScript Playground "Share" link which demonstrates this behavior --> 

**Related Issues:** <!-- Did you find other bugs that looked similar? -->

**Comment by AlCalzone** [comment]
https://blogs.msdn.microsoft.com/typescript/2018/05/16/announcing-typescript-2-9-rc/
> TypeScript 2.9 changes the behavior of keyof to factor in both unique symbols as well as numeric literal types. As such, the above example now compiles as expected. keyof Thing now boils down to the type "foo" | "bar" | typeof baz.
> Unfortunately this is a breaking change for any usage where users believed that for any type T, keyof T would always be assignable to a string. Because symbol- and numeric-named properties invalidate this assumption, we expect some minor breaks which we believe to be easy to catch. In such cases, there are several possible workarounds.
