### ISSUE TITLE
[RFC] compiler options for just a file rather than for a project

### ISSUE THREAD

**Issue by xialvjun** [Microsoft/TypeScript#24452]
## Suggestion

```ts
/// esModuleInterop=true
/// allowSyntheticDefaultImports=true
import A from 'a';
```

and more important:
```ts
// this is a .d.ts file
/// esModuleInterop=true
/// allowSyntheticDefaultImports=true
import A from 'a';
export declare class B extends A { xxx };
```

## Motivation

https://github.com/Microsoft/TypeScript/issues/22321#issuecomment-392736683

```ts
// a.ts --- in fact, a.ts is a commonjs module, we write a.d.ts for it
export = class A {}

// b.ts
// b.ts is another typescript project with a standalone 'tsconfig.json'. 
// We want 'b.ts' support tree shaking, so we set 
// {"esModuleInterop":true,"allowSyntheticDefaultImports":true,"module":"esnext"}
import A from 'a';
export class B extends A {};
```

**But project just depends on `b.ts` still need to set `{"esModuleInterop":true,"allowSyntheticDefaultImports":true,"module": 'esnext'}`, that's ridiculous.**

It should (`'<-' means depends on`):
1. if `project P <- (b.ts + a.d.ts)`, `tsconfig.json` in `P` should be `{"esModuleInterop":true,"allowSyntheticDefaultImports":true,"module":"esnext"}`;
2. if `project P <- b.ts <- a.d.ts`, `tsconfig.json` in `P` needn't to be `{"esModuleInterop":true,"allowSyntheticDefaultImports":true,"module":"esnext"}`;

## Essential

In fact, `esModuleInterop` and `allowSyntheticDefaultImports` is a part of the **Type System**, it should be included in **.d.ts**.

**Comment by xialvjun** [comment]
1. esModuleInterop and allowSyntheticDefaultImports are about imports and not exports.
> `imports` has no difference with `exports` in this case, like:

```ts
// a declaration file: b.d.ts
import A from 'a';
export declare class B extends A {}
``` 

> type B depends on A, and B is exported, so A is exported too. And typeof A depends on `esModuleInterop` and `allowSyntheticDefaultImports`

2. not sure what "module": "esnext" is doing in this whole discussion
> it's just a use case in https://github.com/Microsoft/TypeScript/issues/22321#issuecomment-392736683
```ts
// a.d.ts
declare class A {}
export = A

// b.d.ts --- `compilerOptions.module` must be `commonjs` which will make `b.ts` and projects depend on `b.ts` hard for tree shaking
import A = require('a');
export declare class B extends A {}

// b.d.ts --- `compilerOptions.module` can be `esXXXX`, then `b.ts` and projects `P <- b.ts <- a.ts` will be good for tree shaking, even though `P <- (b.ts + a.ts)` is not good for tree shaking.
/// esModuleInterop=true
/// allowSyntheticDefaultImports=true
import A from 'a';
export declare class B extends A {}
```

**Comment by mhegazy** [comment]
> imports has no difference with exports in this case, like:

not sure i understand this statement..

I am not sure i understand what is the issue you are running into, what is the expected behavior and what you are seeing instead.

**Comment by xialvjun** [comment]
**what i do**
```ts
// a.d.ts ---- it's a normal commonjs project, with .d.ts in it.
declare class A {};
export = A;

// b.ts ---- it's a typescript project whit module=commonjs, and it's allowSyntheticDefaultImports=true && esModuleInterop=true
import A from 'a';
export class B extends A {};

// c.ts ---- it's a normal typescript project with module=es6 for tree shaking, and it's allowSyntheticDefaultImports and esModuleInterop are default to false
import { B } from 'b';
export class C extends B {};
```

**expected behavior**
`c.ts` compiles ok.

**what you are seeing instead**
`node_modules/b/index.d.ts(1,8): error TS1192: Module '"/Users/xialvjun/test/c/node_modules/a/index"' has no default export.`

**how to avoid this error in current typescript version**
set `c.ts`'s `tsconfig.compilerOption.allowSyntheticDefaultImports = true`. 
> But `c.ts` doesn't know `a.ts`, `c.ts` just care about `b.ts`, so it's not right to ask `c.ts` to change its tsconfig.

**Comment by mhegazy** [comment]
do not set `allowSyntheticDefaultImports` unless you are running under `--module system`. this flag does not change anything in the output.

what you need is `esInterop`. and again that has nothing to do with exports, this should be used on the importing file. it tells the compiler let me treat a `CJS` module as an `ES6` module.

**Comment by xialvjun** [comment]
In the case described in above comment https://github.com/Microsoft/TypeScript/issues/24452#issuecomment-393482771

if `c.ts`'s tsconfig is:
```json
{
  "compilerOptions": {
    "declaration": true,
    "moduleResolution": "node",
    "module": "es6",
    "target": "es5"
  }
}
```
> error TS1192: Module '"/Users/xialvjun/test/c/node_modules/a/index"' has no default export.

if it's:
```json
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "declaration": true,
    "moduleResolution": "node",
    "module": "es6",
    "target": "es5"
  }
}
```
> it compiles ok.

if it's:
```json
{
  "compilerOptions": {
    "declaration": true,
    "esModuleInterop": true,
    "moduleResolution": "node",
    "module": "es6",
    "target": "es5"
  }
}
```
> the same error as first one: error TS1192: Module '"/Users/xialvjun/test/c/node_modules/a/index"' has no default export.  Even though in http://www.typescriptlang.org/docs/handbook/compiler-options.html, it says `--esModuleInterop enable --allowSyntheticDefaultImports for typesystem compatibility`

**typescript version: v2.8.4**

Even though `allowSyntheticDefaultImports=true` make it compiles, I don't want every down stream projects (down stream projects mean projects depend on `c.ts`) must set `allowSyntheticDefaultImports=true`.

**Comment by mhegazy** [comment]
first you can not use `export =` with `--module es6`. you can do that with` 
Second, you need to know what module target the package you are consuming.. ES6 and CJS are two different module targets, they do not interpenetrate currently at runtime.. 
Third, do not use `--allowSyntheticDefaultImports` unless you are using a module loader like `System` or you are passing your code to another transpiler like `babel`. even if it makes the error goes away, it is not going to work at runtime..

Finally, just set `--esModuleInterop` for all your modules, and you should be fine.

**Comment by xialvjun** [comment]
**do not use--allowSyntheticDefaultImportsunless you are using a module loader likeSystemor you are passing your code to another transpiler likebabel`**
> yeah, I know it. with module=es6 and allowSyntheticDefaultImportsunless=true, then things maybe wrong. But I use webpack/parcel, they can handle it. I just need typescript to tell me the right type of those objects.

Please have a look this project: [c.zip](https://github.com/Microsoft/TypeScript/files/2061206/c.zip)

```bash
➜  c tree
.
├── dist
│   └── index.js
├── index.d.ts
├── index.js
├── index.ts
├── node_modules
│   ├── a
│   │   ├── index.d.ts
│   │   ├── index.js
│   │   └── package.json
│   └── b
│       ├── dist
│       │   └── index.js
│       ├── index.d.ts
│       ├── index.js
│       ├── index.ts
│       ├── package.json
│       └── tsconfig.json
├── package.json
└── tsconfig.json

5 directories, 15 files
```

**do not `yarn` or `npm install`, just global install `parcel rimraf typescript`, and run `npm run build` in `c` and `c/node_modules/b`**

```bash
➜  c tsc --version
Version 2.9.1
➜  c parcel --version
1.7.1
```

**pay attention in `c/node_modules/b/tsconfig.json` and `c/tsconfig.json`**

**Comment by xialvjun** [comment]
@mhegazy typescript 3.0 `tsconfig.references` field do the same thing as this feature request... And this feature request do it more generally. I do hope you guys can think about it.
