### ISSUE TITLE
More resilient docCommentTemplate API

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#24468]
## Search Terms
- docCommentTemplate

## Problem
The `docCommentTemplate` api currently does not work well if the user has already started typing a comment. For example, no template is returned if `docCommentTemplate`  is called at the `|` in these cases:

```ts
/**|
function foo() { }
```

```ts
/**| */
function foo() { }
```

```ts
/|
function foo() { }
```

VS Code works around this by  making sure the document is always in a good state before requesting the template. This however is a two step process which causes problems in the live share scenario

## Suggestion
Modify `docCommentTemplate` or introduce a replacement can better handle generating templates in  partially typed comments. 

If we do look into a new API, this would also be a good opportunity to update `docCommentTemplate` so that it returns a real snippet or at least some structured template data that editors can convert into a snippet

**Comment by mhegazy** [comment]
The conclusion here is that we will allow a template request to be fulfilled in an empty comment. VSCode will close the comment before sending the request.
