### ISSUE TITLE
type incorrectly resolves when used recursively

### ISSUE THREAD

**Issue by fastspeeed** [Microsoft/TypeScript#24478]
```
export type RCssSelector<Selecotor extends string, Property> = {
    [name in Selecotor]?: Property & RCssSelector<Selecotor, Property>;
};
export type RCss<Selecotor extends string, Property> = Property & RCssSelector<Selecotor, Property>;
export type t2 = RCss<'hover', { color?: string }>;
/**
 * check error
 */
export const a1: t2 = { hover: { f: 1 } };
/**
 * check correct
 */
export const a2: t2 = { hover: { color: 'red', f: 1 } };
```
My question is why a2 is correct
```
export const a2: t2 = { hover: { color: 'red', f: 1 } };
```

**Comment by mhegazy** [comment]
As the error message indicates:
> Type '{ hover: { f: number; }; }' is not assignable to type 'RCss<"hover", { color?: string; }>'.
>  Type '{ hover: { f: number; }; }' is not assignable to type 'RCssSelector<"hover", { color?: string; }>'.
>    Types of property 'hover' are incompatible.
>      Type '{ f: number; }' has no properties in common with type 'RCss<"hover", { color?: string; }>'.

**Comment by mhegazy** [comment]
You might have better luck sharing this on StackOverflow. This is not a support forum, it is one for reporting compiler/language bugs and suggestions. 
If you believe you are running into a compiler bug, please share a minimal repro project that demonstrates the issue you are running into and why you believe this is a compiler bug and not a declaration file issue or library usage problem.
