### ISSUE TITLE
JSDoc: unable to define an optional method on base class

### ISSUE THREAD

**Issue by zombie** [Microsoft/TypeScript#24470]
**TypeScript Version:**  2.8.3

We have a base "abstract" (this is plain JS) class that defines an `ExtensionAPI` which extensions need to extend to provide the implementation.  Some of the methods (like `startup`) are optional, and if not present, we can delay initializing the extensions on startup.

Typescript check complains that the base class doesn't have such methods, and the best solution I could figure out is to add a property to the `ExtensionAPI.prototype` and properly `@type` it, but that throws with error **TS2425**.

**Code**

```js

class ExtensionAPI {
  run(file) {
    //
  }
}

/** @type {function(string): void} */
ExtensionAPI.prototype.startup = null;

///

class Linter extends ExtensionAPI {
  startup(file) {
    //
  }
  run(file) {
    //
  }
}

///

/** 
 * @param {ExtensionAPI[]} extensions
 */
function init(extensions, file) {
  for (let ext of extensions) {
    if (ext.startup) {
      ext.startup(file);
    }
  }  
}

init([new Linter()], "Utitled1");
```
Typecheck using:
```
tsc --allowjs --checkjs --noemit extensions.js
```

**Actual behavior:**
```
error TS2425: Class 'ExtensionAPI' defines instance member property 'startup', but extended class 'Linter' defines it as instance member function.
```

**Comment by mhegazy** [comment]
I think this is related to https://github.com/Microsoft/TypeScript/issues/22896, and https://github.com/Microsoft/TypeScript/issues/24467. I would say my proposal in https://github.com/Microsoft/TypeScript/issues/22896#issuecomment-376983621 should address the underlying use case.

**Comment by zombie** [comment]
Yes, that indeed sounds like a better solution, as long as it covers the above use case and doesn't throw "Class 'ExtensionAPI' defines instance member property 'startup', but extended class 'Linter' defines it as instance member function." (I'm not even sure _when_ that error would be useful).

Hopefully that issue gets a milestone soon.

**Comment by sandersn** [comment]
@zombie Can you try this on 3.0 or newer? I don't get the error there.

**Comment by zombie** [comment]
Doesn't error anymore, thanks.
