### ISSUE TITLE
Three ways to generate a name in the compiler

### ISSUE THREAD

**Issue by JsonFreeman** [Microsoft/TypeScript#2447]
Right now, we have two ways of generating a name in the compiler:

1. `createTempVariable` in the emitter
2. `generateUniqueName` in utilities.

The second one can further be split into two callers:

1. `getGeneratedNamesForSourceFile` in the checker
2. `generateUniqueNameForLocation` in the emitter

We also have 3 ways to track whether a name is unique, and both methods of generating a name do all of these:

1. NodeLinks.generatedNames tracks the names generated for a file, and considers them all used.
2. `tempCount` in `createTempVariable` keeps track of a different set of names per file by using a counter
3. The ScopeFrame stack in the emitter keeps track of names per scope (lastFrame, currentScopeNames, etc)

All of these things need to be consolidated. There are some desirable qualities we want the solution to have:

1. Only one way for callers to make a unique name in the compiler.
2. This way should support the case where the caller prefers some ideal base name to use, and the case where any old name will do.
3. We need to decide whether uniqueness should be tracked per file or per scope, and treat uniqueness that way consistently throughout the compiler.

**Comment by basarat** [comment]
I haven't looked at the code. Hope no one is using Random 🌹

**Comment by vladima** [comment]
Should be addressed by #2471
