### ISSUE TITLE
'Used before declaration' errors are not caught when using commonjs/es6 modules.

### ISSUE THREAD

**Issue by laszlopandy** [microsoft/TypeScript#24486]
**TypeScript Version:**  3.0.0-dev.20180530

**Search Terms:** circular dependencies checking, circular imports, unused before declaration

**Code**
```ts
// == A.ts ==
import { C } from './C';
export class A extends C {}

// == C.ts ==
import { A } from './A';
export class C {
    static makeA() { return new A(); }
}

// == index.ts ==
// move A.ts import above C.ts to compile & run without errors
import { C } from './C';
import { A } from './A';

console.log(new A());
console.log(new C());
console.log(C.makeA());
```
**tsconfig**
```json
{
  "compilerOptions": {
    "target": "ES5",
    "module": "commonjs",
    "outDir": "./dist",
  },
  "files": [
    "./index.ts"
  ]
}
```

**Expected behavior:**
Error: `A.ts:2:17 - error TS2449: Class 'C' used before its declaration.`

**Actual behavior:**
No error given; undefined at runtime:
```
$ node ./dist/index.js
dist/A.js:7
        extendStatics(d, b);
        ^
TypeError: Object prototype may only be an Object or null: undefined
...
```

When using `"module": "commonjs"` or `"module": "es6"`, circular imports which will result in undefined at runtime will not be caught by TypeScript with "used before its declaration".

However when using outFile in conjunction with triple-slash references, the error is caught correctly:
```ts
// == A.ts ==
/// <reference path="C.ts" />
class A extends C {}

// == C.ts ==
/// <reference path="./A.ts" />
class C {
    static makeA() { return new A(); }
}

// == index.ts ==
// move A.ts reference above C.ts to compile without errors
/// <reference path="./C.ts" />
/// <reference path="./A.ts" />

console.log(new A());
console.log(new C());
console.log(C.makeA());
```
**tsconfig**
```json
{
  "compilerOptions": {
    "target": "ES6",
    "outFile": "./dist/out.js",
    "types": []
  },
  "files": [
    "./index.ts"
  ]
}
```
```
$ tsc
A.ts:2:17 - error TS2449: Class 'C' used before its declaration.

2 class A extends C {}
                  ~
```

**Personal context**
In our TypeScript projects we have been using outFile for years. We are trying to move to using commonjs or es6 modules (with a separate bundler) because the es6 import syntax is the future and the only way to import most npm modules. So it was surprising for us that the more modern import syntax is not able to prevent these errors that are caught when using outFile.

**Related Issues:**
https://github.com/Microsoft/TypeScript/issues/21327
https://github.com/Microsoft/TypeScript/issues/17308

**Comment by mhegazy** [comment]
The compiler does not check for circular dependency errors. see https://github.com/Microsoft/TypeScript/issues/14469 and https://github.com/Microsoft/TypeScript/pull/21780.

the compiler also does not do build a call graph for every function you use to understand if it possibly will trigger a use of uninitialized variable. the compiler only checks for things that are guaranteed to fail. 

e.g.:

```ts
var x;
x.toString();  // Error

function f() {
     x.toString(); // noError
}
```

**Comment by encse** [comment]
In the second example the compiler is checking the files along the `reference path` and figures out that `C` is used before it was declared, it generates an error. Good job.

Now, the first example is analogous to the second one, the only difference is that we have `import` statements instead of `reference path`-s. 

I think the same check that catches the error in the second example could find it in the first one as well. It doesn't seem to be fundamentally different to me.

**Comment by laszlopandy** [comment]
@mhegazy Can you explain why you think this is a design limitation? 
Regarding you comment, I don't think this issue is the same as the ones you linked. 
 * I don't want TypeScript from allowing circular dependencies. If you reverse the order of the import in `index.ts` the whole program works and that is a good thing.
 * I also know TypeScript cannot determine if usages inside functions will be valid. The error that TypeScript should detect here is one that it can already detect when using `outFile`: a top-level static reference in the line `export class A extends C {}`. This is something which is guaranteed to fail.

**Comment by mhegazy** [comment]
using outFile, the compiler just treats the files like a single file, puts them all atop of each other and does the analysis.. that is similar to a single file. once you have imports, then now the compiler needs to know if the reference form this import, ends somehow to import the same module.. that is circular reference checking on a reference level. that is something the compiler does not do.
