### ISSUE TITLE
Default value of a function is not assignable to a generic extending Array

### ISSUE THREAD

**Issue by keenondrums** [Microsoft/TypeScript#24480]
**TypeScript Version:**  3.0.0-dev.20180526

**Search Terms:** 
* https://github.com/Microsoft/TypeScript/issues?utf8=%E2%9C%93&q=generics+arrays+default+value
* https://github.com/Microsoft/TypeScript/issues?utf8=%E2%9C%93&q=never%5B%5D+is+not+assignable+to+generic
*https://github.com/Microsoft/TypeScript/issues?utf8=%E2%9C%93&q=any%5B%5D+is+not+assignable+to+generic

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
const a = <T extends any[] = never[]>(b: T = []) => b // fails

const a = <T extends any[] = never[]>(b: T) => b
a([]) // works
```

**Expected behavior:**
First example should give no compilation error

**Actual behavior:**
First example gives a compilation error

**Playground Link:**  
http://www.typescriptlang.org/play/#src=const%20a%20%3D%20%3CT%20extends%20any%5B%5D%20%3D%20never%5B%5D%3E(b%3A%20T%20%3D%20%5B%5D)%20%3D%3E%20b%0A%0Aconst%20a1%20%3D%20%3CT%20extends%20any%5B%5D%3D%20never%5B%5D%3E(b%3A%20T)%20%3D%3E%20b%0Aa1(%5B%5D)

**Related Issues:**

**Comment by mhegazy** [comment]
Please see https://github.com/Microsoft/TypeScript/issues/23718
