### ISSUE TITLE
implement proposal-Symbol-description ( stage 3)

### ISSUE THREAD

**Issue by Kingwl** [microsoft/TypeScript#24484]
## Suggestion
https://github.com/tc39/proposal-Symbol-description

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by mhegazy** [comment]
PRs welcomed. we will need a new lib file `lib.esnext.symbol.d.ts` .
