### ISSUE TITLE
Microsoft.TypeScript.MSBuild. Error MSB6001: Invalid command line switch for "tsc.exe". Illegal characters in path.

### ISSUE THREAD

**Issue by IlyaBiryukov** [Microsoft/TypeScript#24489]
**TypeScript Version:**
Microsoft.TypeScript.MSBuild NuGet package version 2.8.3 
ts.exe version 2.8.3. 

**Search Terms:** 
error MSB6001: Invalid command line switch for "tsc.exe". Illegal characters in path.

**Repro:**
I have a .NET 4.6 VS SDK project that references `Microsoft.TypeScript.MSBuild` NuGet package version 2.8.3. The project has several `<TypeScriptCompile>` items. It also has a custom target to include .js files generated by ts into vsix:
```xml
<Target Name="AddTsToContent" AfterTargets="CompileTypeScript" Condition="'$(BuildingProject)' != 'false'">
    <ItemGroup>
      <Content Include="@(GeneratedJavascript)">
        <IncludeInVSIX>true</IncludeInVSIX>
        <VSIXSubPath>WebView</VSIXSubPath>
      </Content>
     </ItemGroup>
</Target>
```

After upgrading VS to `27703.2022.d15.7`, building the project starts failing with this error:
```
PreComputeCompileTypeScript:
  c:\src\WhackWhackTerminal\packages\Microsoft.TypeScript.MSBuild.2.8.3\build\\..\tools\tsc\tsc.exe
  --module AMD 
  --outDir "bin\Debug\js" 
  --sourcemap 
  --target ES5 
  --moduleResolution Node 
  --noEmitOnError 
--listEmittedFiles "c:\src\WhackWhackTerminal\Microsoft.VisualStudio.Terminal\WebView\ts\external.d.ts" 
"c:\src\WhackWhackTerminal\Microsoft.VisualStudio.Terminal\WebView\ts\main.ts"
"c:\src\WhackWhackTerminal\Microsoft.VisualStudio.Terminal\WebView\ts\TerminalLinkMatcher.ts"
"c:\src\WhackWhackTerminal\Microsoft.VisualStudio.Terminal\WebView\ts\TermView.ts"
"c:\src\WhackWhackTerminal\Microsoft.VisualStudio.Terminal\WebView\ts\VsEventManager.ts"

c:\src\WhackWhackTerminal\packages\Microsoft.TypeScript.MSBuild.2.8.3\tools\Microsoft.TypeScript.targets(360,5): 
error MSB6001: Invalid command line switch for "tsc.exe". Illegal characters in path.
[c:\src\WhackWhackTerminal\Microsoft.VisualStudio.Terminal\Microsoft.VisualStudio.Terminal.csproj]

Done Building Project "c:\src\WhackWhackTerminal\Microsoft.VisualStudio.Terminal\Microsoft.VisualStudio.Terminal.csproj" (default targets) -- FAILED.
```
I tried executing the same command line as the build did, and it succeeds.

**Expected behavior:**
Build does not fail

**Related Issues:** 
https://stackoverflow.com/questions/39318408/typescript-2-0-tsc-exe-code-1-error-after-upgrade?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

**Comment by IlyaBiryukov** [comment]
[msbuild.binlog.zip](https://github.com/Microsoft/TypeScript/files/2054717/msbuild.binlog.zip)
MSBuild log is attached.

**Comment by uniqueiniquity** [comment]
@IlyaBiryukov I'm sorry for the trouble this is giving you. Let me look into this and I will get back to you as soon as I can.

**Comment by uniqueiniquity** [comment]
@IlyaBiryukov I'm not able to repro this with Visual Studio version 15.7.3 and Microsoft.TypeScript.MSBuild version 2.8.4. Are you still seeing the same issue?

**Comment by IlyaBiryukov** [comment]
@uniqueiniquity Yep, I can still see it where I saw it first. Though when I cloned the same repo into a different place and applied the same changes, I could not repro the issue, so I'm not blocked.

**Comment by uniqueiniquity** [comment]
@IlyaBiryukov are you still able to repro this in the original location? I can't repro on 15.7.4 even when matching your command line exactly.

**Comment by IlyaBiryukov** [comment]
Yep, still can repro it. Feel free to drop by if you want to debug.

**Comment by uniqueiniquity** [comment]
After investigation, turned out to be a corrupted log file (tsc.out).
Deleting and regenerating the log file fixed the issue.

**Comment by nekoyoubi** [comment]
I have no idea where that file would be, but I just had a crash that is giving me the exact same message after changing nothing with my MSBuild or TypeScript configurations. Could anyone tell me where I might be able to find that tsc.out file? Thanks so much in advance.

**Comment by uniqueiniquity** [comment]
Hi @nekoyoubi, it'll probably be under <your project root>\obj\<configuration>. If you provide more details about your project type, I can be more specific, but I think you'll be able to find it pretty easily under there. Note that if you're using tsconfig.json to configure TS it'll have a slightly different name, but will still start with Tsc and end with .out.

**Comment by nekoyoubi** [comment]
Thanks a ton, @uniqueiniquity. I decided to just let a file search run overnight, and it found the file no problem. I deleted the \obj\ entirely and rebuilt, got a permissions error on ASP.NET temp files (which I thought was really odd), restarted VS as admin on a hunch. All's good now. Thanks much for getting back on this though.
