### ISSUE TITLE
Mis-parsing of variables named `enum`

### ISSUE THREAD

**Issue by kitsonk** [microsoft/TypeScript#24482]
**TypeScript Version:**  2.8.3

**Search Terms:** 
- enum variable name

**Code**

```ts
interface Foo {
    enum: string;
}

function bar({ enum }: Foo) {
    if (enum) {
        //
    }
}
```

**Expected behavior:**

Code compiles without issue.

**Actual behavior:**

Error at 5: `Enum declarations can only merge with namespace or other enum declarations.`
Error at 5: `':' expected.`
Error at 6: `Enum declarations can only merge with namespace or other enum declarations.`
Error at 6: `Expression expected.`
Error at 6: `Identifier expected.`

**Playground Link:**
[Playground](https://www.typescriptlang.org/play/#src=interface%20Foo%20%7B%0D%0A%20%20%20%20enum%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Afunction%20bar(%7B%20enum%20%7D%3A%20Foo)%20%7B%0D%0A%20%20%20%20if%20(enum)%20%7B%0D%0A%20%20%20%20%20%20%20%20%2F%2F%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A)

**Comment by andy-ms** [comment]
`function bar({ enum }) {}` doesn't work in the node.js console either.

**Comment by RyanCavanaugh** [comment]
Illegal code but we should issue a better parse error here

**Comment by Kingwl** [comment]
related #11648

**Comment by RyanCavanaugh** [comment]
Doesn't seem like this happens very often
