### ISSUE TITLE
Update Imports On File Move: does not persist file extension

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#24493]
_From @misolori on May 30, 2018 15:22_

Issue Type: <b>Bug</b>

https://github.com/Microsoft/vscode/issues/50488

**Example**
![ezgif com-gif-maker 9](https://user-images.githubusercontent.com/35271042/40729782-0cbf686e-63e2-11e8-9211-f5632c97e3ef.gif)

**Resulting error**
![image](https://user-images.githubusercontent.com/35271042/40729816-1bff9a7e-63e2-11e8-805d-bc384369b92e.png)

When moving a js file while using the "Update Imports On File Move" setting and the import has the file extension explicitly set, the auto update will strip out the ".js" extension. This causes issues with the js file referencing it as it needs the extension name.

VS Code version: Code - Insiders 1.24.0-insider (bfd155e6039f64d2795c6b514a029ebd01a33527, 2018-05-29T06:13:09.810Z)
OS version: Darwin x64 17.5.0

_Copied from original issue: Microsoft/vscode#50804_

**Comment by mjbvz** [comment]
I can repo the extension getting removed but not the part where the file is not resolved afterwards or the error in the console.

@misolori Were you just using the default`jsconfig.json`?

---

Perhaps instead of preserving the extension, there should be another preference about adding file extensions to import paths?

**Comment by misolori** [comment]
@mjbvz yes to using the default `jsconfig.json`. Regarding the console error, I was using the browser-sync module with node. I also [found a similar issue](https://stackoverflow.com/a/44481876) posted on SO that reflects the problem I ran into. This repros in Chrome + Safari, adding the extension to the import eliminates the issue.
