### ISSUE TITLE
Feature: update JSDoc blocks upon refactoring

### ISSUE THREAD

**Issue by mindplay-dk** [Microsoft/TypeScript#2452]
Example:

```
/**
 * @param who who to greet
 */
function hello(who: string) {
    return `Hello, ${who}`;
}
```

Renaming the `who` argument currently does not update the `@param who` annotation, which is then left as incorrect and no longer works.

That's just one example - it would be nice if JSDoc blocks were automatically corrected everywhere.

**Comment by DanielRosenwasser** [comment]
@CyrusNajmabadi, shouldn't this be supported in #816?

**Comment by CyrusNajmabadi** [comment]
It should def work.  Though, it's unrelated to rename in comments/strings.  Things like @param should be updated even if you do *not* have that rename option set.

**Comment by mindplay-dk** [comment]
Checked again - doesn't work on the Playground or with [atom-typescript](https://atom.io/packages/atom-typescript) as of right now.

**Comment by DanielRosenwasser** [comment]
Well it's supported in our API, and Visual Studio has it built in. We can give @jrieken a heads up that this is desired for the playground/Monaco, but you'll have to file an issue for atom-typescript (pinging @basarat too).

**Comment by basarat** [comment]
> it's supported by our API

Set renameInComments to true : https://github.com/TypeStrong/atom-typescript/blob/master/lib/main/lang/projectService.ts#L584 ?

How reliable is it ?  

Should I set renameInStrings to true as well?

**Comment by danquirk** [comment]
This isn't working in the recent VS build I have installed.

**Comment by mhegazy** [comment]
> How reliable is it ?

it should always change the, if not then that is a bug. however, in VS we expose it as an option on every rename. i am not sure about changing all instances of the text "name" if i change my person.name  
![renamedev14](https://cloud.githubusercontent.com/assets/8000722/6790996/f0193a8c-d168-11e4-9446-5bc4a1743241.PNG)

**Comment by jrieken** [comment]
We have looked into this for 1.4 but saw some issues with it finding too many matches in all sorts of comments. @mhegazy - I wonder if this has been improved with 1.5?

**Comment by mhegazy** [comment]
The feature is literally searching in comments and string tokens. so if the lexeme you are searching for does exist in a lot of comments/string literals, you will get a lot of matches.

I believe what would be ideal is first class support for JSDoc comments. but that would be a new feature.

**Comment by mindplay-dk** [comment]
> I believe what would be ideal is first class support for JSDoc comments. but that would be a new feature.

Entirely new? JSDoc is parsed already for e.g. comments on parameters.

**Comment by mhegazy** [comment]
that is correct. we currently only parse it to get quick info. we will need to parse it into a tree, associate parameters jsdoc definition with their matching param declaration, and wire it into find all refs logic. it is not a lot of work, but I still see it as a feature-level change

**Comment by mindplay-dk** [comment]
I suppose you'd have to figure out how to handle conflicting type-declarations too? JSDoc is often hand-written with no checking, so they could conflict with declaration files and inline annotations.

**Comment by mhegazy** [comment]
Currently we do not allow types, but in a proper support, you would want to allow it and make it an error, since the type annotation is already captured in code.

**Comment by DanielRosenwasser** [comment]
Weird repro where comments don't *all* get updated:

```TypeScript
/*
 *  Commenting f
 */

// f

function /** f */ f() { /*f*/ // f
    
    // f
    /*
    
    f */
    // f fff
    return 100;
    /*f*/
    /*f*/
}
/*f*/
// f

export default /*2*/f;
// f
var x: typeof /*3*/f;

var y = /*4*/f();
// f
/* f */
namespace /*5*/f { // f
    // f
/* f */
    var local = 100;
}

/*f*/
```

**Comment by DanielRosenwasser** [comment]
Pinging @aozgaa, you might be interested in any work that goes on here.

**Comment by thorn0** [comment]
Probably a separate issue, but would be also nice to get an (optional) compiler error if parameter names in the comments and the code don't match:
```
/**
 * @param foo who to greet
 */
function hello(who: string) {
    return `Hello, ${who}`;
}
```

**Comment by Kovensky** [comment]
@thorn0 https://github.com/gajus/eslint-plugin-jsdoc#check-param-names sounds like a good alternative for now
