### ISSUE TITLE
esnext Array `flatten` should be `flat`

### ISSUE THREAD

**Issue by sambostock** [Microsoft/TypeScript#24526]
The esnext type declarations for `Array` should be updated, as per the [updated proposal](https://github.com/tc39/proposal-flatMap). `flatten` has been renamed to `flat`.

**TypeScript Version:**  3.0.0-dev.201xxxxx

**Search Terms:** 
- `flat flatten`

**Expected behaviour:**

Types should be declared for `flat` on `Array`.

**Actual behaviour:**

Types are declared for `flatten` on `Array`.

**Related Issues:** 

- https://github.com/Microsoft/TypeScript/pull/20431

**Comment by mhegazy** [comment]
thanks @sambostock!
