### ISSUE TITLE
Add completions for closing tag name 

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#24532]
**TypeScript Version:**  3.0.0-dev.201xxxxx

**Search Terms:** 

**Code**

```ts
var x = <Comp> <|  // Completion here
```

**Expected behavior:**

The list should contain `/Comp>`.

**Actual behavior:**

No completion list

**Playground Link:**  

**Related Issues:**  https://github.com/Microsoft/TypeScript/issues/20811

**Comment by andy-ms** [comment]
Don't think this is necessary now that we have #24543; we also already have a completion *after* `/` is typed, so this would only save a single character, that you would probably have to type anyway to select the completion out of the list.
