### ISSUE TITLE
ECMA 2018 regex support

### ISSUE THREAD

**Issue by Geobert** [Microsoft/TypeScript#24531]
## Search Terms

ECMA 2018
lookbehind
regex

## Suggestion

Support ECMA 2018 javascript regex

## Use Cases

In order to have lookbehind (`(?<=)` and `(?<!)`)  support 

## Checklist

My suggestion meets these guidelines:
* [x ] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x ] This wouldn't change the runtime behavior of existing JavaScript code
* [x ] This could be implemented without emitting different JS based on the types of the expressions
* [ x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by mhegazy** [comment]
Not sure what is the details of the request here. TypeScript does not do any processing or checking on regular expressions, and they are all deferred to the host. so [`var x = /(?<=\1(.))/;` is already valid TS regular expression](http://www.typescriptlang.org/play/index.html#src=var%20x%20%3D%20%2F(%3F%3C%3D%5C1(.))%2F%3B).
The compiler does not do any down leveling either for these features, that includes Unicode, and named capture groups.

See https://github.com/Microsoft/TypeScript/issues/21290 for related discussion

**Comment by Geobert** [comment]
I've asked for this on VSCode repo and they told me to ask here. So you're saying that extensions in vscode can use lookbehind already?

**Comment by mhegazy** [comment]
so you want ti use lookbehind in VSCode regexp search box? or in your own .js code?

**Comment by Geobert** [comment]
I tried to use lookbehind with https://github.com/DomiR/vscode-regreplace and it didn't work

**Comment by mhegazy** [comment]
I think this is an issue that should go back to VSCode then. TypeScript drives the language service for JS and TS, which is not what we are talking about here.

**Comment by octref** [comment]
We use ripgrep and seems no: https://github.com/BurntSushi/ripgrep/issues/188
