### ISSUE TITLE
getSemanticDiagnostics() returns an undefined "diagnostic" for definition files

### ISSUE THREAD

**Issue by derekcicerone** [Microsoft/TypeScript#2454]
I just updated to the latest master (1.5) language services code and I noticed that calling getSemanticDiagnostics() for a definition (.d.ts) file is returning an undefined "diagnostic". Seems like a possible regression unless I shouldn't be calling that function for definition files perhaps?

**Comment by DanielRosenwasser** [comment]
Hey @derekcicerone, I don't suppose you'd be able to supply us with a file to reproduce the issue, would you?

**Comment by derekcicerone** [comment]
I'm seeing it on all definition files actually. For example:
https://github.com/borisyankov/DefinitelyTyped/blob/master/underscore/underscore.d.ts

**Comment by CyrusNajmabadi** [comment]
Could you be more specific as to how you're doing this?  Do you have a specific piece of repro code that demonstrates the issue?

"Seems like a possible regression unless I shouldn't be calling that function for definition files perhaps?"

Calling getSemanticDaignostics on a .d.ts file should be fine.

**Comment by derekcicerone** [comment]
Sure, its from the Eclipse plug-in:
https://github.com/palantir/eclipse-typescript/blob/develop/com.palantir.typescript/bridge/src/languageEndpoint.ts#L109

**Comment by DanielRosenwasser** [comment]
Unable to repro on our side. I'll give eclipse-typescript a try.

**Comment by derekcicerone** [comment]
Ah bummer. Ok, lemme know - I can try to set up something more specific if needed - its a bit hard to repro these issues because the bridge requires a few commands to be passed in to reproduce things.

**Comment by DanielRosenwasser** [comment]
I'm using the develop site specified on your wiki (http://eclipse-update.palantir.com/eclipse-typescript-develop/) and I'm not getting any crashes; should I be? Additionally, what do you use to debug bridge.js?

**Comment by derekcicerone** [comment]
I usually debug by running Eclipse directly. I can still reproduce the issue with the latest source code. I'll just put in a workaround :(

**Comment by mhegazy** [comment]
@derekcicerone  Can you share the TS code that gives you the undefined diagnostic message?

**Comment by derekcicerone** [comment]
Its at the top:
https://github.com/borisyankov/DefinitelyTyped/blob/master/underscore/underscore.d.ts

I see this for all .d.ts files.

**Comment by CyrusNajmabadi** [comment]
Could you set a breakpoint for when an undefined diagnostic is added to the diagnostics collection?

**Comment by mhegazy** [comment]
utilities.ts, set a breakpoint in createDiagnosticCollection.add

**Comment by derekcicerone** [comment]
Hmm, trying that now but it seems to be getting hit an awful lot (like at least 40 times so far).

**Comment by derekcicerone** [comment]
Ok, debugging and I found that the variable "declarationDiagnostics" is resolving to undefined in services.ts:
let declarationDiagnostics = program.getDeclarationDiagnostics(targetSourceFile);

**Comment by derekcicerone** [comment]
Ok, I think I found the bug:
```
function getDeclarationDiagnosticsForFile(sourceFile: SourceFile): Diagnostic[] {
            if (!isDeclarationFile(sourceFile)) {
                let resolver = getDiagnosticsProducingTypeChecker().getEmitResolver(sourceFile);
                // Don't actually write any files since we're just getting diagnostics.
                var writeFile: WriteFileCallback = () => { };
                return ts.getDeclarationDiagnostics(getEmitHost(writeFile), resolver, sourceFile);
            }
        }
```

This returns undefined for declaration files.

**Comment by mhegazy** [comment]
ahh. i see. thanks for the help. We need to change getDeclarationDiagnosticsForFile to always return an empty array, or just check before we concat. we should be able to fix this shortly.

**Comment by CyrusNajmabadi** [comment]
ahh. i see. 

I thought you meant you got an array that had 'undefined' values in it.  Not that the entire result is undefined.

It's by design that any LS API return 'undefined'.  Code consuming the LS API should be resilient to that.

**Comment by derekcicerone** [comment]
It doesn't return undefined - it returns an array which contains undefined due to this code:
```
function getSemanticDiagnostics(fileName: string) {
            synchronizeHostData();

            let targetSourceFile = getValidSourceFile(fileName);

            // Only perform the action per file regardless of '-out' flag as LanguageServiceHost is expected to call this function per file.
            // Therefore only get diagnostics for given file.

            let semanticDiagnostics = program.getSemanticDiagnostics(targetSourceFile);
            if (!program.getCompilerOptions().declaration) {
                return semanticDiagnostics;
            }

            // If '-d' is enabled, check for emitter error. One example of emitter error is export class implements non-export interface
            let declarationDiagnostics = program.getDeclarationDiagnostics(targetSourceFile);
            return semanticDiagnostics.concat(declarationDiagnostics);
        }
```

The concat at the end puts the undefined result into an array.

**Comment by CyrusNajmabadi** [comment]
Ah, i see.  Great catch.  I can whip up a fix for that soon.  Thanks!

**Comment by derekcicerone** [comment]
Awesome, thanks!
