### ISSUE TITLE
resolveJsonModule conflict with sourceMap

### ISSUE THREAD

**Issue by GlenCFL** [Microsoft/TypeScript#24546]
**TypeScript Version:** 2.9.1 and 3.0.0-dev.20180531

**Search Terms:** 

JSON
resolveJsonModule
sourceMap

**Code**

A JSON file at "src/test.json":
```json
{
  "value": 42
}
```

Both `resolveJsonModule` and `sourceMap` enabled within a `tsconfig.json` file at `./`:
```json
{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "outDir": "./out",
    "lib": [
      "es2016"
    ],
    "sourceMap": true,
    "rootDir": "src",
  },
  "include": [
    "src/**/*.ts"
  ]
}
```

A TypeScript file at `./src/main.ts` that utilizes this JSON file:
```ts
import test from "./test.json";

console.log(test.value);
```

**Expected behavior:**

1. The outputted JSON file at `./out/test.json` should have the following contents:

```json
{
  "value": 42
}
```

2. The source map file at `./out/test.json.map` should not exist.

**Actual behavior:**

1. The outputted file at `./out/test.json` has a comment indicating the source map at the bottom:

```json
{
  "value": 42
}
//# sourceMappingURL=test.json.map
```

2. The source map file at `./out/test.json.map` exists.

**Playground Link:** N/A.

**Related Issues:** #24530 and #24514

**Comment by mhegazy** [comment]
@sheetalkamat can u take a look

**Comment by a-tarasyuk** [comment]
I think that happens, because there is no filter for `.json` files, and both `.ts`, `.json` have valid `sourceMapFilePath` - [`compiler/emitter.ts#L53`](https://github.com/Microsoft/TypeScript/blob/master/src/compiler/emitter.ts#L53), however, `json` files should not have `sourceMap`

```typescript
const sourceMapFilePath = getSourceMapFilePath(jsFilePath, options);
```
