### ISSUE TITLE
Bad error message for `import *`-ing an `export=`

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#24542]
```ts
// ./b.ts
function foo() {
}
export = foo;
```

```ts
// ./a.ts
import * as b from "./b";
b;
```

```json5
// tsconfig.json
{
    "compilerOptions": {
        "moduleResolution": "node",
        "outDir": "lib"
    },
    "include": [
        "./a.ts"
    ]
}
```

**Expected**:

```
ECMAScript imports can only reference an 'export =' declaration with the 'esModuleInterop' flag enabled and by using default imports.
```

**Actual:**

```
Module '"./b"' resolves to a non-module entity and cannot be imported using this construct.
```

**Comment by a-tarasyuk** [comment]
@DanielRosenwasser @RyanCavanaugh As I see this issue is not resolved yet. Some time ago I created PR, I can reopen it, just need to someone review changes which were added there. Does make sense to reopen the previous PR?

**Comment by RyanCavanaugh** [comment]
@a-tarasyuk sorry for the delay/confusion on the last one; yes a fresh PR would be appreciated. Thanks!

**Comment by a-tarasyuk** [comment]
@RyanCavanaugh ok, thanks, I'll reopen PR.

**Comment by a-tarasyuk** [comment]
@RyanCavanaugh reopened. will wait for the feedback. thanks in advance.

**Comment by a-tarasyuk** [comment]
@DanielRosenwasser @RyanCavanaugh reopened. Could you review PR?

**Comment by a-tarasyuk** [comment]
@DanielRosenwasser should I close PR, or it still actual?
