### ISSUE TITLE
Support dynamic import modules from CDN

### ISSUE THREAD

**Issue by qlqllu** [Microsoft/TypeScript#24550]
ES dynamic import support import a module from CDN like this: 
```
import('https://abc.com/a.js')
```
However, TS will report this line as an error: can't find the module.

Is there a plan to support this feature?

**Comment by mhegazy** [comment]
Add an ambient module declaration for it. See https://www.typescriptlang.org/docs/handbook/modules.html#ambient-modules for more details.

**Comment by miguel-leon** [comment]
Hi,
I would also like to do this. But I don't understand how. Could you give a little more insight?
Thanks

**Comment by abdulkareemnalband** [comment]
@mhegazy  can you provide an example

**Comment by kazuma1989** [comment]
my-declarations.d.ts

```ts
declare module "https://*"
```

This makes any `import("https://xxx")` available. It resolves as `any` type.  Make sure the `my-declarations.d.ts` is referenced via `/// <reference />` comment or included by tsconfig.json `includes` field.

Or you can also write specific definitions like:

```ts
declare module "https://abc.com/a.js" {
  // specific definitions here
  // export const bar: string
}
```
