### ISSUE TITLE
union-ed interfaces raises TS2339 on non-common properties

### ISSUE THREAD

**Issue by coderfox** [Microsoft/TypeScript#24553]
**TypeScript Version:** 3.0.0-dev.20180531

**Search Terms:** 

- union type property TS2339
- union type property not exist
- union interface TS2339
- union interface not exist

**Code**

```ts
interface A {
    foo: string;
}
interface B {
    bar: string;
}
const x = (p: A | B) => {
    if (p.foo !== undefined) {
        // p is interface A
    }
}
const y = (p: A | B) => {
    if (p.bar !== undefined) {
        // p is interface B
    }
}
```

**Expected behavior:**

compiles successfully

**Actual behavior:**

```
test.ts:8:11 - error TS2339: Property 'foo' does not exist on type 'A | B'.
  Property 'foo' does not exist on type 'B'.
8     if (p.foo !== undefined) {
            ~~~
test.ts:13:11 - error TS2339: Property 'bar' does not exist on type 'A | B'.
  Property 'bar' does not exist on type 'A'.
13     if (p.bar !== undefined) {
             ~~~
```

**Playground Link:**  

[Playground](http://www.typescriptlang.org/play/#src=interface%20A%20%7B%0D%0A%20%20%20%20foo%3A%20string%3B%0D%0A%7D%0D%0Ainterface%20B%20%7B%0D%0A%20%20%20%20bar%3A%20string%3B%0D%0A%7D%0D%0Aconst%20x%20%3D%20(p%3A%20A%20%7C%20B)%20%3D%3E%20%7B%0D%0A%20%20%20%20if%20(p.foo%20!%3D%3D%20undefined)%20%7B%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20p%20is%20interface%20A%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0Aconst%20y%20%3D%20(p%3A%20A%20%7C%20B)%20%3D%3E%20%7B%0D%0A%20%20%20%20if%20(p.bar%20!%3D%3D%20undefined)%20%7B%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20p%20is%20interface%20B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A)

**Related Issues:** 

no

**Notes:**

Line 8 can be replaced into `if ((<any>p).foo !== undefined) {` which does not raise compile error.

**Comment by andy-ms** [comment]
This is working as intended -- you can't normally access a property that isn't specified in at least one interface. There are two options:
1) Specify the property in both interfaces:
```ts
interface A {
    foo: string;
    bar?: undefined;
}
interface B {
    foo?: undefined;
    bar: string;
}
function f(ab: A | B) {
    ab.foo; // OK
}
```
This ensures that nothing with a `foo` property is assignable to `B`.

2) Use `"in"`:
```
function f(ab: A | B) {
    if ("foo" in ab) {
        ab.foo; // OK
    }
}
```
This is unsound (as a `B` could have a `foo` property we don't know about) but may be more convenient if you don't want to change the interface definitions.

**Comment by coderfox** [comment]
Thanks for the workaround!
