### ISSUE TITLE
jest not importable in TS2.9

### ISSUE THREAD

**Issue by Kovensky** [Microsoft/TypeScript#24552]
**TypeScript Version:**  2.9.1

**Search Terms:** import not a module

**Code**

```ts
import {} from 'jest'
```

**Expected behavior:**

File should import the global definitions from `@types/jest`.

**Actual behavior:**

File `.../@types/jest/index.d.ts` is not a module.

---

I tried working around it by using `/// <reference types='jest'/>` instead, but the `<reference/>` _itself_ is throwing a "file is not a module" error.

**Comment by Kingwl** [comment]
this is a break change and you should update the code to `import 'jest'`

**Comment by Kingwl** [comment]
wow, seems the changelogs missing this https://github.com/Microsoft/TypeScript/pull/20671
/cc @DanielRosenwasser

**Comment by Kovensky** [comment]
This is a module that _does_ exist, it just isn't an ES module with ES exports.

This syntax is there specifically to not import any values from it and thus import only its global type declarations.

Sounds like a fix for a bug unintentionally caused another bug.

**Comment by Kovensky** [comment]
Even if this is intended to be a breaking change, there still needs to be _some_ way to load jest's globals definitions in some files but not other files, without actually requiring the `jest` npm package at runtime. Jest tests are often colocated so you can't just make a separate `tsconfig.json` with a different `types` list.

**Comment by mhegazy** [comment]
I would like to get more details about this issue. why is `import * as jest from "jest"` not sufficient?

**Comment by Kovensky** [comment]
That creates an unused binding, which is an error with `--noUnusedLocals`

**Comment by mhegazy** [comment]
@andy-ms we should add `_` to disable unused errors for imports as well.

**Comment by mhegazy** [comment]
Looks like for this case, we should just relax the unused errors if the name of the import starts with `_`.

**Comment by weswigham** [comment]
> The point of importing {} from 'jest' is to import the globals that the 'jest' module declares (describe, test, expect, jest, etc) without actually emitting a require('jest') on the compiler output or forcing those globals to also be made available to non-test code that is in the same folder.

Couldn't you use a
```ts
/// <reference types="jest" />
```
comment instead? Or is the declaration file not compatible with a lib reference directive?

**Comment by Kovensky** [comment]
The problem is _exactly_ that even the `/// <reference types="jest" />` is throwing an error saying that "jest is not a module".

**Comment by weswigham** [comment]
..._wot_. Is there more here? If I just make a new project, make a `file.ts` with
```ts
/// <reference types="jest" />
export {}
````
then `npm i --no-save @types/jest` and `tsc ./file.ts` I don't see any errors.

Also, FYI `@types/jest` is _definitely not_ a module (meaning the ref should be what works). It's all global type definitions.

**Comment by Kovensky** [comment]
It also seems I could no longer reproduce this when I tried. I now think that the error I was getting even when I tried replacing the import with a triple-slash reference might have been a watch mode issue, or a webpack loader issue, or a tsservice issue.

Doing a clean build with the triple-slash reference worked with 2.9.1.

**Comment by DanielRosenwasser** [comment]
What happens when you add `/// <reference types="jest" />` to the top of your file (which is the intended fix)?

**Comment by jasonrhodes** [comment]
I mentioned that in my comment. Nothing happens, even if I restart the TS server.

**Comment by weswigham** [comment]
Because it's not a module. Don't us an `import` statement, use a triple-slash types reference instead.

**Comment by jasonrhodes** [comment]
From my original comment:

>If I try to omit the import, there are red lines under each use of Mock. Adding the triple slash reference does nothing, even after restarting TS. import 'jest' does nothing as well.

**Comment by weswigham** [comment]
> If I try to omit the import, there are red lines under each use of Mock

You need to reference it as [`jest.Mock`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jest/index.d.ts#L765) in the global scope.
