### ISSUE TITLE
Can we give better error messages on invoked accessors?

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#24554]
Context https://twitter.com/basarat/status/1002410514704547840?s=19

**Comment by donaldpipowitch** [comment]
Man I like the passion to immediately convert some feedback on Twitter into a GitHub issue. What I really like in cases like this is _"Did you mean...?"_ types of error feedback (showing the same surrounding code from the user, but modified). I personally also like "Read more" links in cases like this, which potentially contain unfamiliar terms.

It could look like this.

```
You can't invoke `locations()`, because it has the type `string[]` which has no compatible call signature.

Did you mean to just use `locations` like this? 

  3 | // other code for context...
  4 | this.signUpService.locations;
  5 | // other code for context

Visit https://www.typescriptlang.org/e/missing-call-signature for more details about this error.
```

And a page like https://www.typescriptlang.org/e/missing-call-signature could list some examples which throw this error and explain terms like _"invoke"_ , _"call signature"_ and so on.

But just some ideas 👋😊

**Comment by maccoda** [comment]
I would like to start having a look into this one. It is my contribution so may need some assistance navigating 😄

**Comment by jtbandes** [comment]
Hi @DanielRosenwasser, I've submitted a PR to improve this (#37800) — is there any procedure I should follow to get it reviewed?

**Comment by orta** [comment]
Thanks @jtbandes! 

During the beta period the TypeScript team end up particularly busy with bugs, as your PR is a feature we're likely to come around to it post 3.9 launch (unless someone can quickly get through the PR) - so for now, this is great and it's on us to do the next step 👍

**Comment by jtbandes** [comment]
Thanks!

**Comment by DanielRosenwasser** [comment]
Small nit: the issue isn't exactly considered a feature, but @orta's right - most of the team is heads down trying to get work done [in time for 3.9](https://github.com/microsoft/TypeScript/issues/37198). I did leave some feedback on the PR.

**Comment by DanielRosenwasser** [comment]
Thanks @jtbandes!
