### ISSUE TITLE
Document predefined types

### ISSUE THREAD

**Issue by mjomble** [Microsoft/TypeScript#24558]
## Search Terms

predefined, document, partial

## Suggestion

TypeScript provides several predefined types that can be very useful, such as `Partial<T>`, `Required<T>`, etc.
It might be a good idea to have a separate page in the documentation that lists all of them.

## Use Cases

These types are currently not very easily discoverable for new users.
A few are mentioned in the documentation under more generic topics and new ones are mentioned in "What's new in this version" posts.
They can be looked up in the declaration files, but a lot of future users likely won't know to go looking for them and will end up reinventing the wheel.

## Examples

Flow documentation has a page like this called [Utility Types](https://flow.org/en/docs/types/utilities/)

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by mhegazy** [comment]
A PR to https://github.com/Microsoft/TypeScript-Handbook would be appreciated.

**Comment by chrissantos1995** [comment]
Great idea 👍 -- I opened an issue (https://github.com/Microsoft/TypeScript-Handbook/issues/798) in the Handbook repo to track this effort (assuming we want to track this issue in the same repo that the PR will be submitted to)

**Comment by posva** [comment]
This can be closed now that the page exists at https://www.typescriptlang.org/docs/handbook/utility-types.html

**Comment by mjomble** [comment]
Indeed. There's still no link to the page, but that's being tracked in a different issue: https://github.com/Microsoft/TypeScript-Handbook/issues/994
