### ISSUE TITLE
Shorter output of import()

### ISSUE THREAD

**Issue by KSXGitHub** [Microsoft/TypeScript#24559]
## Suggestion

I'm glad that TypeScript 2.9 finally support `import()` function call, however, I think it can be improved.

TypeScript currently emits this code for `import('./lib')`:

```javascript
Promise.resolve().then(() => __importStar(require('./lib')))
```

which is longer and more verbose than this:

```javascript
Promise.resolve(__importStar(require('./lib'))
```

I also created a test repo: https://github.com/KSXGitHub/typescript-async-import.git

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by MartinJohns** [comment]
These two versions don't behave identical. In the first version, if either `__importStar` or `require` throw an error, then you end up with a rejected promise. But in the second version the `Error` will affect the importing function directly.

**Comment by KSXGitHub** [comment]
Makes sense. Thanks for clarify.

**Comment by KSXGitHub** [comment]
@MartinJohns How about this?

```javascript
new Promise(r => r(__importStar(require('./lib'))))
```

Slightly shorter.
