### ISSUE TITLE
Typescript Audio() object not taking NodeRequire as parameter

### ISSUE THREAD

**Issue by phiboi** [Microsoft/TypeScript#24569]
**TypeScript Version:**  2.9.2

**Search Terms:**  HTMLAudioElement, Audio, NodeRequire

**Expected behavior:** Depending on the file loader that the front-end framework uses, the HTMLAudioElement (new Audio() ) should be able to take a NodeRequire as a parameter to load the media file.

In some frameworks with different file-loader (or url-loader) configuration, audio will work without a NodeRequire object:

```ts
htmlaudio = new Audio('./assets/song.mp3');
```
However, this is the way it has to be in React and Vue CLI 3 (without any custom configuration):
```ts
htmlaudio = new Audio(require('./assets/song.mp3'));
```

**Actual behavior:**
So, putting this logic in Typescript, this will work without a type error:
```ts
const htmlaudio: HTMLAudioElement = new Audio(require('./assets/song.mp3'));
htmlaudio.play();
```
However, if the parameter is explicitly declared to be type NodeRequire, the code will still work but will flag a type error:
```ts
const audio: NodeRequire = require('./assets/song.mp3');
const htmlaudio: HTMLAudioElement = new Audio(audio);
htmlaudio.play();
```
>Argument of type 'NodeRequire' is not assignable to parameter of type 'string | undefined'.
>Type 'NodeRequire' is not assignable to type 'string'.

I can work around this by setting const audio to type any, but it's still an inconvenience that might need to be fixed.

**Comment by mhegazy** [comment]
NodeRequire is a function. Do not think this type annotation is correct.

**Comment by phiboi** [comment]
Uhh, no, NodeRequireFunction is an interface too.

```ts
interface NodeRequireFunction {
    /* tslint:disable-next-line:callable-types */
    (id: string): any;
}
```

**Comment by jcready** [comment]
@phiboi that **is** an interface for a function.

```js
const test: NodeRequireFunction = (id) => id;
```

**Comment by phiboi** [comment]
Why are we still arguing whether it is a function or not? As long as the function implements the interface (not the interface extends the function), it can be taken as an object because after all a lambda is an object. The problem I'm trying to tell is that HTMLAudioElement *does* take NodeRequire as a parameter.

```ts
const htmlaudio: HTMLAudioElement = new Audio(require('./assets/song.mp3'));
htmlaudio.play();
```

This code works, but it's giving a type error, and it needs to be updated. If you're familiar with typescript React or typescript Vue, you'll know this is a problem.

**Comment by AlCalzone** [comment]
> `const audio: NodeRequire = require('./assets/song.mp3');`

I agree with the others that this type is wrong. `require` is of type `NodeRequire`, however its return value `require('path/to/something')` - which you are using here - is not.
