### ISSUE TITLE
ES6 classes with statics need to be renamed

### ISSUE THREAD

**Issue by JsonFreeman** [Microsoft/TypeScript#2457]
This is in reference to https://github.com/Microsoft/TypeScript/commit/bd4d7fc9eedfb905313b173e284eddf95350e7dc#commitcomment-10328068

When targeting ES6, we emit the static properties of a class after the class itself. However, given the double binding semantics for classes, those statics will not be visible inside the class.

The following source code will not work:
```ts
class C {
    static prop = "hello";
    sayHello() {
        console.log(C.prop); // C does not have prop over here
    }
}
```

Instead we need to emit something like:
```ts
let C = (function() {
  let _C = class C {
    sayHello() {
      console.log(_C.prop); // Now prop exists
    }
  }
  _C.prop = "hello";
  return _C;
})();
```

**Comment by mhegazy** [comment]
I do not see how this is an issue. the comment is about replacing the binding for the class, e.g:
```ts
class C {
   sayHello() { C; // local C}
}

C = class B {

}

C // this is global C which is really class B
```

The example you have, you have two bindings, but both point to the same symbol. we have not changed that, we are just adding a property. so both should be able to see the effect.

If i understand the issue correctelly, i think is is not a bug.

**Comment by JsonFreeman** [comment]
Oh I see what you mean. Yeah I think you are right.
