### ISSUE TITLE
TS2.9 - export {default} syntax not working

### ISSUE THREAD

**Issue by uncleramsay** [Microsoft/TypeScript#24575]
**TypeScript Version:**  2.9.1 (tested with typescript@next)

**Search Terms:** 
default export
lacks call construct signature

**Code**

`file1.ts`
```ts
export default class Component {
  constructor() {
    console.log('instantiated');
  }
}
```

`file2.ts`
```ts
export {default} from './file1';
```

`file3.ts`
```ts
import Component from './file2';
const component = new Component();
```

**Expected behavior:**
Running file3 will print to console

**Actual behavior:**
Compiler error: `error TS2351: Cannot use 'new' with an expression whose type lacks a call or construct signature.`

I noticed this can be fixed by changing `file2.ts` to:

```ts
import Component from './file1';
export default Component;
```

Or by changing `file3.ts` to:

```ts
import {default as Component} from './file2';
...
```

I believe I'm correct in saying that the `export {default}` syntax is in the ES6 spec, so I think this should work. Apologies if I missed something.

**Comment by weswigham** [comment]
Duplicates #24528

**Comment by mhegazy** [comment]
The fix should be in `typescript@next` today, and should be in `2.9.2` in two weeks.
