### ISSUE TITLE
Unnecessary `| undefined` in signature help with optional parameter

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#24586]
**TypeScript Version:** 3.0.0-dev.20180601

**Code**

```ts
/// <reference path='fourslash.ts' />
// @strictNullChecks: true

////function f(x?: number): void {}
////f(/**/)

verify.signatureHelp({ marker: [""], text: "f(x?: number): void" });
```

**Expected behavior:**

Test passes.

**Actual behavior:**

Signature help is `f(x?: number | undefined): void`.

**Comment by mhegazy** [comment]
This is consistent with other places int he type system.. e.g. quick info on optional properties.

the type does include `undefined` in it.
