### ISSUE TITLE
Well-typed JSON imports with `"module": "es2015"`

### ISSUE THREAD

**Issue by domoritz** [Microsoft/TypeScript#24588]
**TypeScript Version:**  2.9 and 3.0-dev

**Code**

I'm trying to use `resolveJsonModule` with `"module": "es2015"`.

```json
{
    "compilerOptions": {
        "module": "es2015",
        "resolveJsonModule": true,
        "esModuleInterop": true,
        "outDir": "lib",
        "moduleResolution": "node"
    }
}
```

```ts
import settings from "./settings.json";  // error
```

`settings.json`:

```json
{
    "dry": false,
    "debug": false
}
```

**Actual behavior:**

```
a.ts:1:8 - error TS1192: Module '"/private/tmp/json/settings"' has no default export.

1 import settings from "./settings.json";
         ~~~~~~~~


error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by weswigham** [comment]
Have you tried using `esModuleInterop`? We don't support `default`s for non-actually-esm-defaults without a flag (either that one or `allowSyntheticDefaultImports`, if the runtime behavior is handled by another tool).

**Comment by domoritz** [comment]
@weswigham `"esModuleInterop": true,` is laready set to true in my `tsconfig.json` above. I also tried setting it to `false`.

**Comment by weswigham** [comment]
@sheetalkamat does `allowSyntheticDefaultImports` not affect json modules right now?

**Comment by domoritz** [comment]
Oh, setting `allowSyntheticDefaultImports` to `true` seems to fix this. Should this be the default?

**Comment by weswigham** [comment]
No. `import jsonObject from "./something.json"` by default compiles to (roughly):
```ts
const jsonObect_1 = require("./something.json");
const jsonObject = jsonObect_1.default;
```
it's important to note that that straight up will not work like you hope. `esModuleInterop` changes the emit, so instead of a straight `require`, we emit an interop helper that will make the `default` available.

**Comment by domoritz** [comment]
So this is a bug?

**Comment by weswigham** [comment]
Mmmmm no, but it is confusing. `esModuleInterop` only fully implies `allowSyntheticDefaultImports` when we actually emit the helpers ourselves - so when `module` is `commonjs`, `amd`, `umd`, or `system`. (There are no import helpers emitted for `es2015` modules, since the imports don't get transpiled.)

**Comment by domoritz** [comment]
Hmm, that seems to make using typescript with rollup less attractive. I would like to output `es2015` but then none of the JSON imports will work because rollup assumes that I am using a default import (and it looks for `module.default`). What's the recommended setup of compiling bundles with Typescript and Rollup?

**Comment by weswigham** [comment]
Just set `allowSyntheticDefaultImports: true`. Roll-up is doing the emit work for you.

**Comment by domoritz** [comment]
I see. I have to see what's going wrong in https://github.com/vega/vega-lite/pull/3839 then. Thanks for your help.

**Comment by domoritz** [comment]
Do you want to close this issue or is there something to improve about the error message?
