### ISSUE TITLE
RequestInit does not support URLSearchParams (when dom.iterable is included as a library)

### ISSUE THREAD

**Issue by yellowjello** [Microsoft/TypeScript#24581]
**TypeScript Version:**  typescript@next

**Search Terms:** RequestInit, URLSearchParams

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
const params = new URLSearchParams();
const options: RequestInit = {
    method: 'POST',
    body: params
};
```

**Expected behavior:**
It should pass type-checking because URLSearchParams is a valid object for RequestInit body according to the fetch API spec: https://fetch.spec.whatwg.org/#bodyinit

**Actual behavior:**
TypeScript complains that URLSearchParams is not appropriate. Looking at lib.dom.d.ts, it appears that URLSearchParams is missing from the list of types allowed to be in RequestInit body, but the weird thing is, if I do not include dom.iterable as part of libs, TypeScript is happy, so there might be another bug going on besides the type definition problem.

**Playground Link:**  http://www.typescriptlang.org/play/#src=const%20params%20%3D%20new%20URLSearchParams()%3B%0D%0Aconst%20options%3A%20RequestInit%20%3D%20%7B%0D%0A%20%20%20%20method%3A%20'POST'%2C%0D%0A%20%20%20%20body%3A%20params%0D%0A%7D%3B

**Related Issues:**

**Comment by mhegazy** [comment]
Should be fixed https://github.com/Microsoft/TSJS-lib-generator
