### ISSUE TITLE
ES6 clodules need to be renamed

### ISSUE THREAD

**Issue by JsonFreeman** [Microsoft/TypeScript#2458]
Closely related to #2457 and also in reference to https://github.com/Microsoft/TypeScript/commit/bd4d7fc9eedfb905313b173e284eddf95350e7dc#commitcomment-10328068

A class merging with a module will not work in ES6, because you will end up redeclaring a class and a var (the var is what we emit for the module) in the same scope, which will cause a runtime error. So a class merging with a module needs to be renamed in a similar way as #2457, except as a var instead of a let.

**Comment by mhegazy** [comment]
Currently a clodules defined as:
```ts
class foo {
    static y = "s";
}

module foo {
    export var x = 0;
}
```

is emitted as:

```js
class foo {
}
foo.y = "s";
var foo;                       // Redefinition of class foo
(function (foo) {
    foo.x = 0;
})(foo || (foo = {}));
```

Since we do not allow clodules to span multiple files, all what we need to do is remove the additional var declaration for foo.

**Comment by JsonFreeman** [comment]
What if the class portion is ambient and in a different file? Then I think we still need to remove the var, no?

**Comment by mhegazy** [comment]
i believe class has let semantics in ES6, and I believe redefining a let in a different file is ok. I need to go read the spec again to be sure though.

**Comment by JsonFreeman** [comment]
That would be very strange if a let and var in two different files are okay

**Comment by rbuckton** [comment]
@JsonFreeman After reviewing the spec, you are correct. According to [15.1.8](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-globaldeclarationinstantiation), step 6:

> 6\. For each *name* in *varNames*, do
> &emsp;a\. If *envRec*.[HasLexicalDeclaration](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-haslexicaldeclaration)(*name*) is **true**, throw a **SyntaxError** exception.

So if script **A** has a lexically declared name `a` from a `let` declaration, and script **B** has a var declared name `a` from a `var` declaration, this would result in a **SyntaxError** at runtime.

We could elide the `var` declaration for a module if we know that the declared name was a lexically declared name in the current scope. However, if we do this across files we could end up with different emit when performing single-file-transpile.

**Comment by rbuckton** [comment]
> However, if we do this across files we could end up with different emit when performing single-file-transpile.

We make it an error to do this anyways, so I don't think it matters what we do here. I would say we emit the `var` if the class is defined in another source file.

**Comment by JsonFreeman** [comment]
It is only an error if the class declaration is not ambient

**Comment by rbuckton** [comment]
Would you elide the `var` in both cases then?

**Comment by JsonFreeman** [comment]
Yes I think so
