### ISSUE TITLE
Rename Array.prototype.flatten to flat

### ISSUE THREAD

**Issue by bterlson** [Microsoft/TypeScript#24580]
In lib.esnext.array.d.ts, Array and ReadOnlyArray's flatten needs to be renamed to flat the consensus name as of the May TC39 meeting.

**Comment by j-oliveras** [comment]
Duplicate and already solved: #24526.

**Comment by bterlson** [comment]
@j-oliveras aha thank you! I thought I remembered seeing something but search turned up dry.
