### ISSUE TITLE
Mark unused properties inside of unused class?

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#24597]
From https://github.com/Microsoft/vscode/issues/50640

**TypeScript Version:**  3.0.0-dev.20180601

**Search Terms:** 
- unused

**Code**

```ts
export const abc= 123 

class Foo {
    foo() { }
}  
```

**Current Behavior**
Only `Foo` is currently marked as unused

**Question**
Should `Foo.foo` also be marked as unused?

**Comment by RyanCavanaugh** [comment]
A public method on an exported class will always be assumed to be used outside the current compilation unit and thus not be an error. So issuing an error here would just be a pile-on; doesn't seem desirable
