### ISSUE TITLE
Duplicate identifier with d.ts

### ISSUE THREAD

**Issue by ruslanmogilevskiy** [Microsoft/TypeScript#2459]
I have two projects and each of them has https://github.com/borisyankov/DefinitelyTyped/blob/master/requirejs/require.d.ts file included. While compiling them with TS 1.4 I got 55 errors of "Duplicate identifier '[member_name]'".
How I can eliminate this issue or at least switch it to a warning? Hope it is not by design.

**Comment by basarat** [comment]
You're compiling them separately right?

**Comment by ruslanmogilevskiy** [comment]
Did some investigations. It is one project fails. 
It has one require.d.ts included in some folder (some other nuget package depends on this file and its location) and another require.d.ts included into another project folder (didn`t catch this earlier because appeared that tsc load referenced d.ts files even if are not included into the project).
So, unfortunately I have two copies of the same d.ts in the same project. Can these errors be remove somehow or should I think over keeping only one d.ts file?

**Comment by basarat** [comment]
You can have only one require.d.ts in a single project. That is by design.
