### ISSUE TITLE
Import types in d.ts files contain relative paths to node_modules

### ISSUE THREAD

**Issue by jwbay** [Microsoft/TypeScript#24599]
**TypeScript Version:** 3.0.0-dev.20180601

**Search Terms:** declaration import types

**Code**
src/one/two/export.ts:
```ts
import * as CSS from 'csstype';
export const use = (f: CSS.Properties['fontWeight']) => f;
```

src/one/two/consumer.ts:
```ts
import { use } from "./export";
export const asdf = use ;
```
**Expected behavior:**
consumer.d.ts has something like
```ts
export declare const asdf: (f: import("csstype/index").FontWeightProperty) => import("csstype/index").FontWeightProperty;
```

**Actual behavior:**
It has relative paths to node_modules, based on the source file's location at compile time. This places an assumption on the location of the d.ts file when it's consumed externally.

```ts
export declare const asdf: (f: import("../../../node_modules/csstype/index").FontWeightProperty) => import("../../../node_modules/csstype/index").FontWeightProperty;
```

**Playground Link:** N/A

**Related Issues:** #24556, but csstype does specify a types key in package.json

**Comment by zsgalusz** [comment]
I can reproduce this issue in 2.9.1, it's a major blocker for us in upgrading to TS2.9.

**Comment by mhegazy** [comment]
@epeli can you give `typescript@next` a try?

**Comment by weswigham** [comment]
@mhegazy we still haven't published a nightly this week.

**Comment by epeli** [comment]
Sure. Can you ping me when it's out so I can test it?

**Comment by osdiab** [comment]
I too am seeing this problem; my imports in the declarations are going all the way to my filesystem root. I think this might have something to do with the `baseUrl` config, pretty sure it shouldn't apply here because this is a relative path but it seems to impact what gets outputted (unless I'm misunderstanding the use case of `baseUrl`).

There's a nested dependency in my code, where I have this import:

```
// File: src/routes/listOperations.ts
import { createApiRoute } from "../";
export const listOperations() = createApiRoute<ListOperationsEndpoint>( //... );

// File: src/routes/index.ts"
import { ApiContext } from "../app";
export const createApiRoute<Endpoint extends ApiEndpoint> = (ctx: ApiContext<ApiEndpoint["authenticated"]>): Promise<void> => //...

// File src/app.ts
export type AuthenticatedContext = // ...
export type UnauthenticatedContext = // ...
export type ApiContext<Authenticated extends boolean> = Authenticated ? AuthenticatedContext : UnauthenticatedContext
```

If `baseUrl` is not present, then I get this output:

```
// File: build/routes/listOperations.d.ts
export declare const listOperations: (operations: CollectionReference) => (ctx: import("../../../../../../../../Users/omar/code/raha/raha-api/src/app").UnauthenticatedContext) => Promise<void>;
```

Not what I expect! I would expect it to be `../../app`.

Then, if I set `baseUrl: "./"` in `tsconfig.json` I get:

```
export declare const listOperations: (operations: CollectionReference) => (ctx: import("src/app").UnauthenticatedContext) => Promise<void>;
```

Yeah, shouldn't be an absolute path now, since I have no `paths` entry in `tsconfig`. Pretty sure `baseUrl` shouldn't be affecting this since this is not an absolute path...

**Comment by weswigham** [comment]
@osdiab do you see the same thing with `typescript@next`?

**Comment by osdiab** [comment]
Yes, on typescript@^3.0.0-dev20180616

**Comment by osdiab** [comment]
Yes, on typescript@3.0.0-dev20180616

**Comment by weswigham** [comment]
What're all the rest of your tsconfig options (outDir, rootDir, etc), and are there any symlinks in your project?

**Comment by osdiab** [comment]
No symlinks, here’s the tsconfig:

```
{
"compilerOptions": {
"target": "es2015",
"module": "esnext",
"moduleResolution": "node",
"lib": ["es2018"],
"sourceMap": true,
"outDir": "./dist",
"rootDir": "./src",
"strict": true,
"noImplicitAny": true,
"declaration": true
},
"exclude": ["node_modules", "dist"]
}
```

**Comment by epeli** [comment]
If you need something to reproduce this with you can use my [redux-stack](https://github.com/epeli/redux-stack) lib. There is no `baseUrl` used in this project.

```
git clone git@github.com:epeli/redux-stack.git
cd redux-stack
git checkout 21879cfb8bb35a6fed4fcb62cf3cd3d2eaf1935a # current master at the time of writing
npm install
npm install typescript@next # get 3.0 dev version
./node_modules/.bin/tsc
```

and checkout the type imports in `typings/src/configure-store.d.ts`. With `3.0.0-dev.20180616` they are like `../../../../../Users/esamatti/code/redux-stack/node_modules/redux`.

**Comment by abettadapur** [comment]
I am also seeing this issue.

![image](https://user-images.githubusercontent.com/2415669/41546940-ce5fd3d2-72d3-11e8-95f3-b80bef109055.png)

We have a custom build process that copies the build files to a slightly different directory structure than the source code, so this relative path is incorrect.

**Comment by jods4** [comment]
Got biten by this.

I have a function whose return type is implicit and lives in another file my project.

When compiling with `-d` I get following output:

Typescript 2.9.1:
```
readonly scope: import("./scope").Scope;
```
Typescript 2.9.2:
```
readonly scope: import("../../../../../../Code/x/packages/lib/src/templating/scope").Scope;
```

**This is a very bad regression!**

2.9.1 worked well enough, because it stayed inside my declarations folder.
2.9.2 pulls in the `src` folder, which brings all my `.ts` lib sources into consuming projects and everything breaks hard.

**Comment by kohlmannj** [comment]
Sorry to say that this will keep me on TypeScript v2.8.4 for an internal library I'm building.

I've been working with TS v2.9.x in a so-called `main-project`, which depends on certain types from an NPM-installed module `interface-spec`. 

<details><summary><strong>More About This Internal Project</strong></summary>

```js
// package.json looks something like this...
{
  "name": "main-project",
  "devDependencies": {
    "interface-spec": "git+https://github.com/org/interface-spec.git#semver:^2.0.0-alpha.0",
    // ...
  }
  // ...
}
```

The folder structure is like this:

- `node_modules`
  - `interface-spec`
- `package.json`
- `src`
  - `index.ts` (imports and implicitly references types from `interface-spec`)
  - More source files
- `tsconfig.json`
- `tsconfig.dts.json`
- `tslint.json`

Finally, `interface-spec` contains type definitions created using [Protobuf.js](https://github.com/dcodeIO/protobuf.js#pbts-for-typescript), which can generate TypeScript definitions for Protobuf messages and services using the provided `pbts` command.

—
</details>
<br>

Types from `interface-spec` are being turned into `import()` statements with relative paths by TS v2.9.x when emitting declarations for `main-project`. (I suspect) the paths should be absolute.

For example, an `import()` like this was emitted by v2.9.1:

```ts
import("../node_modules/interface-spec/dist/index").google.protobuf.Empty
```

Here's one from v2.9.2:

```ts
import("../../../../../../Users/kohlmannj/Sites/main-project/node_modules/interface-spec").google.protobuf.Empty
```

Note that the path from TS v2.9.2 at least ends in `interface-spec`, but it just just be `import('interface-spec')`; that's what I'd type if I were manually writing this `import()` statement, anyway.

Here are the two tsconfig files I'm using:

<details><summary><strong>tsconfig.json</strong></summary>

```json
{
  "compilerOptions": {
    "target": "esnext",
    "module": "commonjs",
    "allowJs": true,
    "checkJs": true,
    "jsx": "preserve",
    "sourceMap": true,
    
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "alwaysStrict": true,

    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,

    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,

    "experimentalDecorators": true,
  },
  "exclude": [
    "**/__old__/**",
    "**/__wip__/**",
    "**/lib/**",
    "**/dist/**",
    "./scripts/**",
    "**/webpack.config.js"
  ]
}
```
</details>
<br />

<details><summary><strong>tsconfig.dts.json</strong></summary>

```json
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "noEmit": false,
    "allowJs": false,
    "checkJs": false,
    "declaration": true,
    "declarationMap": true
  },
  "exclude": [
    "**/__mocks__/**/*",
    "**/__stories__/**/*",
    "**/__stubs__/**/*",
    "**/__tests__/**/*",
    "**/__old__/**",
    "**/__wip__/**",
    "**/lib/**",
    "**/dist/**",
    "./scripts/**",
    "**/webpack.config.js"
  ]
}
```
</details>
<br />

The command I'm using to generate type definitions is:

```bash
$ tsc -p ./tsconfig.dts.json --emitDeclarationOnly --outDir ./lib
```

Hope this helps, sorry I cannot share the project/s directly.

**Comment by nyrkovalex** [comment]
We are also affected by this issue.
So far we've narrowed the repoduction scope a bit. It is reproduced on Windows when there's an uppercased letter somewhere in project path.

Here is a reproduction repository https://github.com/nyrkovalex/ts-import-bug
It contains two identical folders — one containing uppercased letters in its name and another one with lowercased letters only.

The bug is repeatably reproduced inside uppercased folder and cannot be reproduced inside the lowercased one.

**Comment by weswigham** [comment]
@nyrkovalex thanks for the simple repro! Case sensitivity propagation was the issue, as it turns out. #25110 is up with a fix, and I'll see if we can get it into the next `2.9` release, too.

**Comment by nyrkovalex** [comment]
@weswigham Thank you, glad to see that pull request, hope it makes it to the next release. We'll stay tuned.

**Comment by mhegazy** [comment]
The fix should be in tomorrow's `typescript@next`. please give it a quick test and let us know if you are still seeing issues.

**Comment by tyler-johnson** [comment]
Hello, I am bit confused as this issue seems to be tracking two different problems.

1. paths to node_modules are showing up as relative paths `./node_modules/package` instead of just `package`
2. paths are going back to root, `../../../Users/user/package/file` instead of just `./file`

So does #25110 solve both or just the 2nd issue?

**Comment by mhegazy** [comment]
@tyler-johnson please give `typescript@next` a try tonight, and if you are still seeing issues please file a new ticket with more details.

**Comment by nyrkovalex** [comment]
@mhegazy I can confirm excessive `../../../` path generation is fixed in `typescript@3.0.0-dev.20180630`.

**Comment by goloveychuk** [comment]
I still see 
```ts
export declare const fetchFilterCategories: ({ entityType, entityId }: any) => import("node_modules/axios").AxiosPromise<any>;
```
to reproduce: 
```ts
import Axios from 'axios'

export const fetchFilterCategories = ({ entityType, entityId }: any) => {
    return Axios.get(`sd`);
};
```

Also have such references
```ts
/// <reference path="../node_modules/@types/lodash/common/common.d.ts" />
/// <reference path="../node_modules/@types/lodash/common/array.d.ts" />
/// <reference path="../node_modules/@types/lodash/common/collection.d.ts" />
/// <reference path="../node_modules/@types/lodash/common/date.d.ts" />
/// <reference path="../node_modules/@types/lodash/common/function.d.ts" />
/// <reference path="../node_modules/@types/lodash/common/lang.d.ts" />
/// <reference path="../node_modules/@types/lodash/common/math.d.ts" />
/// <reference path="../node_modules/@types/lodash/common/number.d.ts" />
/// <reference path="../node_modules/@types/lodash/common/object.d.ts" />
/// <reference path="../node_modules/@types/lodash/common/seq.d.ts" />
/// <reference path="../node_modules/@types/lodash/common/string.d.ts" />
/// <reference path="../node_modules/@types/lodash/common/util.d.ts" />
```
compile to reproduce:
```ts
import {mapValues} from 'lodash';
export const mapDispatchToProps = mapValues
```
ts version: `Version 3.0.0-dev.20180630`

**Comment by andy-ms** [comment]
Should be fixed by #25364, please open a new issue if you see any `../../node_modules`-like paths in `typescript@next`.

**Comment by weswigham** [comment]
`typescript@next` _tomorrow_ for anyone watching the thread.

**Comment by epeli** [comment]
`3.0.0-dev.20180705` seems to have fixed this, thank you!

**Comment by OliverJAsh** [comment]
Is there any chance of getting this out into a 2.9 patch release, so we don't have to wait for v3 (which some of us might not be able to upgrade to immediately)?

We've just upgraded to 2.9 and then stumbled into this which is a bit of a pain.

**Comment by mhegazy** [comment]
3.0 should be available next week.

**Comment by chriskrycho** [comment]
3.0 arriving soon is great, but allow me to second @OliverJAsh's request for a backport to the 2.9 series; I have a library that this broke and would strongly prefer _not_ to have to set a minimum requirement of 3.0 for people consuming its types.

**Comment by akosyakov** [comment]
I still see https://github.com/Microsoft/TypeScript/issues/24599#issuecomment-401852343 for tsx files with next typescript.
