### ISSUE TITLE
compile fail when import types with decorator

### ISSUE THREAD

**Issue by zhang740** [Microsoft/TypeScript#24619]
**TypeScript Version:**  3.0.0-dev.20180602

**Search Terms:** 
import types with decorator

**Code**

```ts
export class A {
  @test
  b: import('./b').B
}

// tsconfig.json:
{
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    ...
}
```

**Expected behavior:**
- compile success
- the `design:type` of property `b` is `B`.

**Actual behavior:**

when `tsc` output:
```shell
Error: Debug Failure. Unexpected node.
Node 179 was unexpected.
```

**Playground Link:** 
N/A

**Related Issues:** 
N/A

**Comment by mhegazy** [comment]
First we should not fail, second the resulting type would be `Object` at runtime.
