### ISSUE TITLE
operator === cannot be applied to types false and true

### ISSUE THREAD

**Issue by zerkms** [Microsoft/TypeScript#24621]
**TypeScript Version:**  3.0.0-dev.201xxxxx

**Search Terms:** 

**Code**
```ts
var a = false;

if (a === true) {
    console.log('foo')
}
```

**Expected behavior:**
Given typescript is a **superset** of JS it must compile

**Actual behavior:**
It fails with the `operator === cannot be applied to types false and true`

**Playground Link:**  
https://www.typescriptlang.org/play/#src=var%20a%20%3D%20false%3B%0D%0A%0D%0Aif%20(a%20%3D%3D%3D%20true)%20%7B%0D%0A%20%20%20%20console.log('foo')%0D%0A%7D

**Related Issues:** 
It was at least reported at https://github.com/Microsoft/TypeScript/issues/11178 but for some reason the original poster has closed it

**Comment by Zzzen** [comment]
```javascript
var a = 1;
a = "1"
```
is valid js code, and yet it should not compile.

**Comment by zerkms** [comment]
Then the main page with its

> TypeScript is a typed superset of JavaScript that compiles to plain JavaScript.

and documentation should be corrected correspondingly?

**Comment by mhegazy** [comment]
> Given typescript is a superset of JS it must compile

it does. the compiler will generate JavaScript fro your input that is identical. Compiler errors do not stop the generation of output. the compiler will however warn you about possible issues. that applies to almost all errors in TS.

**Comment by zerkms** [comment]
> Compiler errors do not stop the generation of output

unless `--noEmitOnError` is used.

But I see the point, thanks.
