### ISSUE TITLE
Question about refactors in TS compiler API, and how to debug language server

### ISSUE THREAD

**Issue by Jack-Works** [Microsoft/TypeScript#24623]
I'm currently working on a refactor in language service. But I found something strange. It seemed `getAvailableActions` doesn't get called.

1. Add a file to `src/services/refactors/` and registers it like any other refactors.
2. My code like below.

```typescript
registerRefactor(refactorName, {
        getAvailableActions({
            host, file,
            ...context
        }: RefactorContext): ApplicableRefactorInfo[] | undefined {
            host.log!("getAvailableActions get called");
            return;
        },
        getEditsForAction(context: RefactorContext, actionName: string): RefactorEditInfo | undefined {
            return;
        }
    });
```

3. Then I compile it. My code has been compiled in built/local/typescriptServices.js
```typescript
/** @internal */
var ts;
(function (ts) {
    var refactor;
    (function (refactor) {
.........
```

4. I start a vscode. Select "Use the workspace version"
```json
{
  "typescript.tsdk": "../Typescript/built/local"
}
```
5. I select a piece of code in a .ts file. Then right click, select "Refactor..."
6. VSCode shows
![image](https://user-images.githubusercontent.com/5390719/40878115-e3cc253e-66be-11e8-8e19-b078db933d5c.png)

![image](https://user-images.githubusercontent.com/5390719/40878121-fbc60948-66be-11e8-90d4-0e76aed96d98.png)

If `host.log` is `undefined`, there should be a `TypeError`; Otherwise, it should give me a log. Or log() does not log to the OUTPUT panel in vscode?
So I have a question, how can I debug my code? Thanks.

VSCode version: 1.23.1 (Stable)
Typescript version: master (3.0.0)

**Comment by andy-ms** [comment]
If you're writing a new refactor, it's much better to write a fourslash test for it than to test in an IDE. See `tests/cases/fourslash/refactorConvertImport_useDefault.ts` for an example.

(To answer your question directly, logs don't go to the output panel, they go to the tsserver log -- you need to set `"typescript.tsserver.log": "verbose",` in the vscode settings, then use the "Open TS Server Log" command while editing a `.ts` file.)

**Comment by Jack-Works** [comment]
Oh thanks, and I have get another question, how can I get the AST of the selected range? (Like I selected the whole ClassDeclaration)

Do I have to resolve the identifier token where the selected start points to, then resolve where the token is defined in the current SourceFile? (I see other refactors are likely doing this)
Thanks

**Comment by andy-ms** [comment]
There is a function `getParentNodeInSpan` that should get you the biggest node that fits in the highlighted span. Using `convertImport` as an example again, see `getImportToConvert`.
