### ISSUE TITLE
keyof does not include well known symbols

### ISSUE THREAD

**Issue by mgroenhoff** [microsoft/TypeScript#24622]
**TypeScript Version:**  2.9.1

**Search Terms:** 
keyof well known symbol

**Code**

```ts
const s = Symbol("s");

interface I {
    n: number;
    [s]: string;
    [Symbol.iterator](): IterableIterator<[string, string]>;
}

type K = keyof I;
type T = I[K];
```

**Expected behavior:**
```ts
type K = keyof I; // type K = typeof s | "n" | typeof Symbol.iterator
type T = I[K]; // type T = string | number | () => IterableIterator<[string, string]>
```

**Actual behavior:**
```ts
type K = keyof I; // type K = typeof s | "n"
type T = I[K]; // type T = string | number
```

**Comment by weswigham** [comment]
@mhegazy we're going to need an LKG post-lib references to stage this change. We probably also want to have a forked copy of the node `@types` definitions which uses lib references for our own build until we ship the feature and can push the change to DT.

**Comment by weswigham** [comment]
@RyanCavanaugh if we want this in 3.1, we need to look into taking #24738

**Comment by bluenote10** [comment]
This feature would significantly simplify writing generic wrappers needed in [Solid](https://github.com/ryansolid/solid). See [this SO question](https://stackoverflow.com/q/57100616/1804173) for an explanation of the use case in Solid. Looking forward to a release.

CC @ryansolid

**Comment by jcalz** [comment]
Another [relevant SO question](https://stackoverflow.com/questions/58800315/why-typescript-omit-pick-erase-symbols).  

Could we remove the "fixed" tag from this issue since it means the same thing as the less-confusing "fix available"?
