### ISSUE TITLE
Option `resolveJsonModule` not generated via tsc --init

### ISSUE THREAD

**Issue by yahiko00** [Microsoft/TypeScript#24631]
**TypeScript Version:**  3.0.0-dev.20180602

**Search Terms:** 
resolveJsonModule

**Expected behavior:**
The option `resolveJsonModule` should be in the tsconfig.json generated by the command `tsc --init`.

**Actual behavior:**
The option `resolveJsonModule` is not in the tsconfig.json generated by the command `tsc --init`.

**Comment by a-tarasyuk** [comment]
@yahiko00 

[`resolveJsonModule`](https://github.com/Microsoft/TypeScript/blob/d671c7ae9611dc49d4fadbd1c06652df967c81fc/src/compiler/commandLineParser.ts#L513
) is an advanced option, it will be added to `tsconfig.json` only if you explicitly set it, for instance

```schell
tsc --init --resolveJsonModule
```

**tsconfig.json**
```json
{ 
    compilerOptions: {
       ....
       /* Advanced Options */
       "resolveJsonModule": true                 /* Include modules imported with '.json' extension */
     }
}
```

**Comment by yahiko00** [comment]
I was not really aware of this "advanced option" behavior.
