### ISSUE TITLE
Understand css classes

### ISSUE THREAD

**Issue by olmobrutall** [Microsoft/TypeScript#24635]
## Search Terms
css classes

## Suggestion
I know that Typescript is about javascript, but most of the javascript made today is for writing web sites, and while there is a lot of tooling for javascript (like Typescript) and for css (like Less and Sass), the integration between the two has no tooling at all. 

in MyComponent.css
```css
.my-class .my-other-class{
  border-color: red
}
```

in MyComponent.tsx
```tsx
import { myClass, myOtherClass } from './MyComponent.css'

return (
<div className={myClass}>
   <div className={myOtherClass}>
   </div>
</div>
);
```

This code will be compiled to: 

```tsx
import from './MyComponent.css'
const myClass = "my-class";
const myOtherClass = "my-other-class";
```
## Use Cases

* Strongly-typed class names
* Find all references on class names
* Unused class names
* Rename class names. 

Of course, you need to have some simple css parser (maybe less/sass too...) inside typescript, and the editors will need to call ts language services for some of the features (Find all references) but the benefits for the web developers will be HUGE. 

## Checklist
My suggestion meets these guidelines:
* [X] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by kitsonk** [comment]
This is best suited for external tooling, like [typed-css-modules](https://www.npmjs.com/package/typed-css-modules) which generates a `.d.ts` for CSS Modules and then you can author code as you would like.  You still need to run it in an environment where the CSS module get properly loaded.  There are tools and plugins for webpack that can accomplish this.

In my opinion, exotic modules which don't have an agreed standard for loading shouldn't be included in the core of TypeScript, and there is sufficient tooling to accomplish this.

**Comment by olmobrutall** [comment]
Good enough, I’ll give typed-css-modules a try. It’s one dependency more and another file watcher, but solves the problem of supporting less and sass

**Comment by MartinJohns** [comment]
@kitsonk I honestly don't think this is much different from importing JSON. With the JSON import feature a specific format is assumed too.

**Comment by kitsonk** [comment]
> I honestly don't think this is much different from importing JSON. With the JSON import feature a specific format is assumed too.

@MartinJohns it is quite different IMO.  Node.js imports and automatically parses files via `require('something.json')`. I am not aware of any browser or runtime environment that automatically parses CSS into a usable, typable object structure in JavaScript.
