### ISSUE TITLE
Destructuring assignment doesn't check assignability

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#24634]
A value being destructed by `[]` must be iterable.
A value being destructed by `{}` must be non-nullable.

**TypeScript Version:**  master

**Search Terms:** 

**Code**

```ts
const [] = {}; // should be error
const {} = undefined; // error correctly
(([]) => 0)({}); // should be error
(({}) => 0)(undefined); // should be error
```

**Expected behavior:**

**Actual behavior:**

**Playground Link:**  

**Related Issues:**

**Comment by Kingwl** [comment]
> A value being destructed by {} must be non-nullable.

what about `const { length } = []`

**Comment by Kingwl** [comment]
```ts
function foo({}: undefined) {
    return 0
}
function bar([]: {}) {
    return 0
}

```

**Comment by Kingwl** [comment]
https://github.com/Microsoft/TypeScript/issues/20873
