### ISSUE TITLE
Private members being emitted to definition file

### ISSUE THREAD

**Issue by mtraynham** [Microsoft/TypeScript#2463]
If they are supposed to be emitted, they are un-typed.

Seen in 1.4.1 and master.

Example:

Test.ts:
```
class Test {
    private static BAR: string = 'BAR';
    private _foo: string = 'foo';
}
export = Test;
```

`tsc -d --target ES5 --module commonjs Test.ts`

Test.d.ts:
```
declare class Test {
    private static BAR;
    private _foo;
}
export = Test;
```

**Comment by mtraynham** [comment]
This was found when overloading a superclasses' setter/getter.

Throws error:
`Class 'SubClass' incorrectly extends base class 'SuperClass'.
  Types have separate declarations of a private property '_foo'.`

Parent project:
```
class ObjectA {
    public value: any;
}
class SuperClass {
    private _foo: ObjectA;
    public get foo(): ObjectA {
         return _foo;
    }
}
```
Parent defintiion:
```
declare class ObjectA {
    private value: any;
}
declare class SuperClass {
    private _foo;
    public foo: ObjectA;
}
```

Child project:
```
class ObjectB extends ObjectA {
    public value2: any;
}
class SubClass {
    private _foo: ObjectB;
    public get foo(): ObjectB {
         return _foo;
    }
}

**Comment by ahejlsberg** [comment]
This is by design, see #1532.

**Comment by mtraynham** [comment]
Interesting.  Thanks for the link. I couldn't seem to find an issue that related.
