### ISSUE TITLE
Add interace for imported json type

### ISSUE THREAD

**Issue by weeco** [Microsoft/TypeScript#24644]
## Search Terms

imported json interface
json interface
reference json type

## Suggestion

My favourite 2.9 feature is the possibility to import JSON files with typesafety without defining an interface on my own. However I am now lacking the possibilty to reference the interface of the imported JSON file.

**Example:**
```ts
import raritiesJson from '../../assets/rarities.json';
raritiesJson.forEach((rarity: INeedANamedInterfaceHere) => {
  console.log(rarity.name);
});
```

Can you add a possibilty to reference the interface of the imported JSON file?

## Use Cases

Whenever you want to explicitly reference the type of the imported JSON (see the given example) you would again need to create your own interface.

## Examples

```ts
import { raritiesJson, interface as IRaritiesJson } from '../../assets/rarities.json';
raritiesJson.forEach((rarity: IRaritiesJson) => {
  console.log(rarity.name);
});
```

## Checklist

My suggestion meets these guidelines:
* [X] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by kitsonk** [comment]
What you are looking for is the `typeof` operator.  It extracts the type information from any variable:

```ts
type IRaritiesJson = typeof raritiesJson;
```

**Comment by weeco** [comment]
@kitsonk Thanks a ton!

**Comment by weeco** [comment]
@kitsonk How would I get the type of a single object in a given object array though? Imagine that JSON input, how could I reference the type of a single object in that array?

```
[{
		"a": 1,
		"b": 2
	},
	{
		"a": 4,
		"b": 6
	}
]
```

raritiesJson.forEach((rarity: IRarity) => {
  console.log(rarity.name);
});

**Comment by kitsonk** [comment]
@weeco try:

```ts
const IRaritiesJson = typeof raritiesJson[0];
```
