### ISSUE TITLE
VS 2013: Generated JS files should be added to _references.js so Intellisense works from JS files

### ISSUE THREAD

**Issue by BrandonLive** [microsoft/TypeScript#2464]
Short version: Generated JS files should be added to _references.js so that IntelliSense and related IDE features work as expected from JS files in projects that mix TS and JS code.

Longer version:
I've started converting some core files of my project to TypeScript. This has gone well so far, but one thing that really disappointed me was that I lost IntelliSense for the types/classes and globals/modules/namespaces that are defined in those files when working with them from our large codebase of plain JS files.

I found that the reason for this is that the generated JS files are not part of the project, and thus not synced into _references.js by VS automatically. Adding them to the project fixes this, but pollutes my repo and Solution Explorer (since they aren't identified as dependent and turned into a subtree). Manually adding them to _references.js enables IntelliSense and related functionality to work as expected. However, I think this should really be the default behavior. Eventually I'd really like to see some _better_ IntelliSense and other IDE features in this scenario (leveraging the additional type information that the TypeScript file has). But for now I think the valuable low-hanging fruit is to fix _references.js sync for the generated JS files.

**Comment by RyanCavanaugh** [comment]
This hasn't gotten any other feedback, so deciding against
