### ISSUE TITLE
TS emits error when try to assign interface to index signature

### ISSUE THREAD

**Issue by Ailrun** [Microsoft/TypeScript#24662]
**TypeScript Version:** 2.8.4, 2.9.1 (I believe this is the version for Playground)

**Search Terms:** Interface, Index signature, Assignment

**Code**

```ts
interface X {
    readonly a: number;
}

type Y = {
    readonly a: number;
}

type K = {
    [key: string]: number;
}

declare const x: X;
declare const y: Y;

const k0: K = x;
const k1: K = y;
```

**Expected behavior:**
If `{ readonly a: number } <: K`, both succeed,
If not, both fail.

**Actual behavior:**
`k0` succeeds, `k1` fails.

**Playground Link:** https://www.typescriptlang.org/play/index.html#src=interface%20X%20%7B%0D%0A%20%20%20%20readonly%20a%3A%20number%3B%0D%0A%7D%0D%0A%0D%0Atype%20Y%20%3D%20%7B%0D%0A%20%20%20%20readonly%20a%3A%20number%3B%0D%0A%7D%0D%0A%0D%0Atype%20K%20%3D%20%7B%0D%0A%20%20%20%20%5Bkey%3A%20string%5D%3A%20number%3B%0D%0A%7D%0D%0A%0D%0Adeclare%20const%20x%3A%20X%3B%0D%0Adeclare%20const%20y%3A%20Y%3B%0D%0A%0D%0Aconst%20k0%3A%20K%20%3D%20x%3B%0D%0Aconst%20k1%3A%20K%20%3D%20y%3B%0D%0A

**Related Issues:**

**Comment by mhegazy** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/14951

**Comment by Ailrun** [comment]
@mhegazy Oh, I miss it. Thank you!

**Comment by Ailrun** [comment]
@mhegazy Wait, it looks like the issue did not mention about difference between `interface` and `type`. Could you point the comment mention it?

**Comment by mhegazy** [comment]
Sorry, a search snafu.. here is the correct issue: https://github.com/Microsoft/TypeScript/issues/15300

**Comment by Ailrun** [comment]
@mhegazy Allright, that's the original issue. I close this.
