### ISSUE TITLE
'call on undefined' error when calling super from overwritten property function

### ISSUE THREAD

**Issue by gricey432** [Microsoft/TypeScript#24678]
**TypeScript Version:**  2.8.3, also whichever version powers playground

**Search Terms:** 
Super function method property access cannot read property call of undefined

**Code**

```ts
class A {
    public myFunc = () => {
        return 'a';
    };
}

class B extends A {
    public myFunc = () => {
        return super.myFunc();
    };
}

const b = new B();
console.log(b.myFunc());
```

**Expected behavior:**
Either:
- Prints 'a' to console (may not be possible based on related issues below?)
- Compile time error

**Actual behavior:**
Successfully builds into JS which then fails at runtime
```
Uncaught TypeError: Cannot read property 'call' of undefined
    at B._this.myFunc (<anonymous>:24:44)
    at <anonymous>:31:15
    at HTMLButtonElement.excuteButton.onclick (https://www.typescriptlang.org/play/playground.js:247)
```

**Playground Link:** [Link](https://www.typescriptlang.org/play/#src=class%20A%20%7B%0D%0A%20%20%20%20public%20myFunc%20%3D%20()%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20'a'%3B%0D%0A%20%20%20%20%7D%3B%0D%0A%7D%0D%0A%0D%0Aclass%20B%20extends%20A%20%7B%0D%0A%20%20%20%20public%20myFunc%20%3D%20()%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20super.myFunc()%3B%0D%0A%20%20%20%20%7D%3B%0D%0A%7D%0D%0A%0D%0Aconst%20b%20%3D%20new%20B()%3B%0D%0Aconsole.log(b.myFunc())%3B%0D%0A)

**Related Issues:**
#4465 and #338 seem related though they focus on getters and setters

**Comment by DanielRosenwasser** [comment]
Seems appropriate. This is (more or less) the following equivalent code without class properties:

```ts
class A {
    constructor() {
        this.myFunc = () => {
            return 'a';
        };
    }
}

class B extends A {
    constructor() {
        super();
        this.myFunc = () => {
            return super.myFunc();
        };
    }
}

const b = new B();
console.log(b.myFunc());
```

and this will error in any runtime I've tried.

**Comment by andy-ms** [comment]
I tested with `typescript@2.8.3` and I still get a compile time error:
```
src/a.ts(9,22): error TS2340: Only public and protected methods of the base class are accessible via the 'super' keyword.
```

**Comment by zhonghanwen** [comment]
Don't use =>,  you can write: 
```ts
class A {
    public myFunc ()  {
        return 'a';
    };
}

class B extends A {
    public myFunc ()  {
        return super.myFunc();
    };
}

const b = new B();
console.log(b.myFunc());
```
