### ISSUE TITLE
Incorrect arg type infer when function doesn't have the arg

### ISSUE THREAD

**Issue by 19majkel94** [Microsoft/TypeScript#24683]
**TypeScript Version:** 3.0.0-dev.20180605

**Search Terms:** 
- infer arg
- infer arg type 
- arg type object 

**Code**

```ts
type GetArgType<TFn> = TFn extends (arg: infer TArg) => any ? TArg : -1;

function noArg() { }
function withArg(arg: number) { }

type noArgType = GetArgType<typeof noArg>;
type withArgType = GetArgType<typeof withArg>;
```

**Expected behavior:**
expected `noArgType` to equals `never`

**Actual behavior:**
`noArgType` equals `{}`

**Playground Link:**  
http://www.typescriptlang.org/play/#src=type%20GetArgType<TFn>%20%3D%20TFn%20extends%20(arg%3A%20infer%20TArg)%20%3D>%20any%20%3F%20TArg%20%3A%20-1%3B%0D%0A%0D%0Afunction%20noArg()%20%7B%20%7D%0D%0Afunction%20withArg(arg%3A%20number)%20%7B%20%7D%0D%0A%0D%0Atype%20noArgType%20%3D%20GetArgType<typeof%20noArg>%3B%0D%0Atype%20withArgType%20%3D%20GetArgType<typeof%20withArg>%3B%0D%0A

**Comment by AlCalzone** [comment]
Not sure if the behavior in the OP is a bug but this works:

```ts
type GetArgType<TFn> =
    TFn extends () => any ? never :
    TFn extends (arg: infer TArg, ...rest: any[]) => any ? TArg :
    -1;

function noArg() { }
function withArg(arg: number) { }
function with2Args(arg1: number, arg2: string) { }

type noArgType = GetArgType<typeof noArg>; // never
type withArgType = GetArgType<typeof withArg>; // number
type with2ArgsType = GetArgType<typeof with2Args>; // number
```

**Comment by MartinJohns** [comment]
Working as intended: #23105

**Comment by 19majkel94** [comment]
@MartinJohns Thanks for the link. So I will go straight to the main case as it's "working".

The case is related to [rematch](https://github.com/rematch/rematch) lib. We have an object with a `reducers` field that should be in this type:
```ts
export type ModelReducers<S = any> = {
  [key: string]: (state: S, payload: any, meta?: any) => S,
}
```
But to build the type of `dispatch` object, we need to extract the types using this thing:
```ts
export type ExtractRematchDispatcherFromReducer<R> =
  R extends () => any ? RematchDispatcher<void, void> :
  R extends (state: infer S) => infer S ? RematchDispatcher<void, void> :
  R extends (state: infer S, payload: infer P) => infer S ? RematchDispatcher<P, void> :
  R extends (state: infer S, payload: infer P, meta: infer M) => infer S ? RematchDispatcher<P, M> :
  RematchDispatcher<any, any>
```

And the problem is that when someone use default for `payload` arg, e.g.:
```ts
increment(state, payload: number = 0) {
  return state + payload;
},
```
The whole expression evaluates to the case with `RematchDispatcher<void, void>` so you can't call `dispatch.counter.increment(1)`, only `dispatch.counter.increment()`.

**Comment by AlCalzone** [comment]
I see... basically optional parameters are treated as non-existing. Seems unintuitive.
