### ISSUE TITLE
transpilation doesn't handle multiple prologue directives

### ISSUE THREAD

**Issue by ajafff** [Microsoft/TypeScript#24689]
**TypeScript Version:**  3.0.0-dev.20180605

**Search Terms:** 

**Code**

```ts
// this is obviously a bogus function just to have a minimal repro
function test(p: any) {
    'use strong';
    'use strict';
    p = {prop: p} = p;
}
```

**Expected behavior:**

```js
function test(p) {
    'use strong';
    'use strict';
    var _a;
    p = (_a = p, p = _a.prop, _a);
}
```

**Actual behavior:**

```js
function test(p) {
    'use strong';
    var _a;
    'use strict';
    p = (_a = p, p = _a.prop, _a);
}
```

The transpiled code has different semantics, because `'use strict'` is no longer treated as directive.

I don't know if this also affects other transformers that add statements.

Note that TypeScript correctly detects the `'use strict'` directive and would correctly complain about octal literals.

**Playground Link:**  

**Related Issues:** 
#24582
https://github.com/Microsoft/TypeScript/pull/24386#discussion_r190794788

**Comment by mhegazy** [comment]
A PR would be appreciated.
