### ISSUE TITLE
error TS1183: An implementation cannot be declared in ambient contexts.

### ISSUE THREAD

**Issue by siva563** [Microsoft/TypeScript#24681]
Using angular 6 Project I am getting below error:

`error TS1183: An implementation cannot be declared in ambient contexts.`

Below Error I was facing could you someone help me 👍 

`ERROR in node_modules/rxjs/internal/Observable.d.ts(14,35): error TS1183: An implementation cannot be declared in ambient contexts.`

**Comment by andy-ms** [comment]
Could you provide the code example that's failing for you? The latest `rxjs` has a comment on line 14 or `internal/Observable.d.ts`.

**Comment by Samhot** [comment]
I have the same problem, my Typescript version is 2.7.2 and i'm using Angular 6, does anyone have any solution ?

**Comment by andy-ms** [comment]
@rxjs could you provide an example project that reproduces the error?

**Comment by Samhot** [comment]
It's complicate to provide an example it's not a specific code which doesn't works, I just use Observables in many components... It worked well till this afternoon, since the build is impossible

**Comment by Samhot** [comment]
May be it could help https://stackoverflow.com/questions/37448491/angular-2-typescript-an-implementation-cannot-be-declared-in-ambient-contexts

**Comment by gruby-murzyn** [comment]
Hej simple solution is `npm install rxjs`

**Comment by AsimanQedirov** [comment]
...\node_modules\@angular\core\src\linker\element_ref.d.ts ERROR -> 1183 An implementation cannot be declared in ambient contexts 
and what i must do?

**Comment by Muralidhar-Rathod** [comment]
node_modules/@ionic/angular/dist/providers/platform.d.ts(10,46): error TS1183: An implementation cannot be declared in ambient contexts.
above error showing in project  please i need help

**Comment by pranavrajojha** [comment]
I have the same issue and here is the code where I am getting it.

`registerBackButtonAction(arg0: () => void, arg1: number) {
    throw new Error("Method not implemented.");
  }
  exitApp() {
    throw new Error("Method not implemented.");
  }`

**Comment by karosLi** [comment]
I have same issue in d.ts file.

error: Initializers are not allowed in ambient contexts.

```
declare namespace SportDataErrorCode1 {
  var lDEFAULT_PREFETCH_SIZE: number = 100;
}
```

**Comment by BiletskiyDmitriy** [comment]
In my case it happened when I was trying to add implementation to definition file(some-file.d.ts)
