### ISSUE TITLE
Conditional types of callables distribute union types in an unhelpful way.

### ISSUE THREAD

**Issue by MrJohz** [Microsoft/TypeScript#24686]
**TypeScript Version:**  3.0.0-dev.20180605

**Search Terms:** union of callables, union of functions, conditional types

**Code**

```ts
type MyResponse =
	| string
	| number

type SENTINEL = { __varargs_hack_sentinel: '__varargs_hack_sentinel' };

type Callback<Param=SENTINEL> =
    Param extends SENTINEL ? () => void
    : (param: Param) => void

const testFunction = (onClose: Callback<MyResponse>) => {
    return onClose('test')  // <-- ERROR OCCURS HERE
}
```

**Expected behavior:**
`onClose` should have type `(arg: string | number) => void`.  It should be possible to call it with both `string` and `number` parameters.

**Actual behavior:**
`onClose` has type `(arg: string) => void | (arg: number) => void`.  It is not possible to call it with any parameters, as union types are not callable.

I'm using conditional types to create a sort of generic function vararg-y thing.  Essentially, the `Callback` type can be used to describe a no-args function (`Callback`), or a one-arg function (`Callback<ArgType>`), and can be extended to as many arguments as you like.  I've done this because I'm writing React code, and a lot of prop definitions will include callbacks.  By defining something similar to the `Callback` type here, I save myself a bit of faff every time my prop definition includes one or more callback-like properties.  By using conditional types, I don't need to worry about creating a separate `CallbackN` type for each number of arguments that I want to pass to the callback.

My aim in this bit of code is to create a callback that can accept a parameter in a union of types - here, either a `string` or a `number`.  However, because conditional types are distributive, the two types are distributed separately, and the type is transformed into a union of two different callbacks.  This type then cannot be called, because unions of callables are not themselves callable.

Ideally for me, when the conditional type expression distributes union types, it should be cleverer about handling unions in callables (either not distributing them, or "inverting" the distribution to `(a: A) => void & (b: B) => void`); or unions of callables with compatible signatures should be callable; or there would be better documentation of this issue.

**Playground Link:** [here](http://www.typescriptlang.org/play/#src=type%20MyResponse%20%3D%0D%0A%09%7C%20string%0D%0A%09%7C%20number%0D%0A%0D%0Atype%20SENTINEL%20%3D%20%7B%20__varargs_hack_sentinel%3A%20'__varargs_hack_sentinel'%20%7D%3B%0D%0A%0D%0Atype%20Callback%3CParam%3DSENTINEL%3E%20%3D%0D%0A%20%20%20%20Param%20extends%20SENTINEL%20%3F%20()%20%3D%3E%20void%0D%0A%20%20%20%20%3A%20(param%3A%20Param)%20%3D%3E%20void%0D%0A%0D%0Aconst%20testFunction%20%3D%20(onClose%3A%20Callback%3CMyResponse%3E)%20%3D%3E%20%7B%0D%0A%20%20%20%20return%20onClose('test')%0D%0A%7D%0D%0A%0D%0Atype%20ManualCallback%3CT%3E%20%3D%0D%0A%20%20%20%20(param%3A%20T)%20%3D%3E%20void%0D%0A%0D%0Aconst%20testWithManualCallback%20%3D%20(onClose%3A%20ManualCallback%3CMyResponse%3E)%20%3D%3E%20%7B%0D%0A%20%20%20%20return%20onClose('test')%3B%0D%0A%7D%0D%0A)

**Comment by mhegazy** [comment]
The underlying issue here is that union signatures are not callable.. that is tracked by https://github.com/Microsoft/TypeScript/issues/7294

For the details on why it is a union, `Callback` is a distributive conditional types on `Param`. i.e. if the type is instantiated with a union type, the result is the union of applying the conditional types on every constituent. you can find more about distributive conditional types at: https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#distributive-conditional-types.

To prevent the type from distributing you could define it as:

```ts
type Callback<Param=SENTINEL> =
    [Param] extends [SENTINEL] ? () => void
    : (param: Param) => void
```

**Comment by MrJohz** [comment]
Thanks, that's a very neat way of preventing the type from distributing!  That fixes my particular problem, and given you've already got #7294, I'll just close this.
