### ISSUE TITLE
XMLHttpRequest.send method parameter must be nullable (regression)

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#24717]
https://xhr.spec.whatwg.org/#the-send()-method

**TypeScript Version:**  master

**Search Terms:** 

**Code**

**Expected behavior:**

```ts
    send(body?: Document | BodyInit | null): void;
```

**Actual behavior:**

```ts
    send(body?: Document | BodyInit): void;
```

**Playground Link:**  

**Related Issues:**

**Comment by falsandtru** [comment]
Is this should be fixed by the fix of generator?

**Comment by mhegazy** [comment]
> Should this be fixed by the fix of generator?

yes please. the [idl](https://github.com/Microsoft/TSJS-lib-generator/blob/master/inputfiles/idl/XMLHttpRequest.widl#L47) file seems to be parsed fine.. seems like conversion to json is missing the null.

**Comment by mhegazy** [comment]
A PR would be appreciated
