### ISSUE TITLE
Inconsistent Promise resolve signature

### ISSUE THREAD

**Issue by KSXGitHub** [Microsoft/TypeScript#24718]
In TypeScript, `await promise` where `promise: Promise<T>` always returns `T` but `resolve` function accepts `undefined`. This may lead to subtle bug.

I hereby suggest to remove question mark (`?`) from `resolve`'s parameter.

---

**TypeScript Version:**  2.9

**Search Terms:** 

**Code**

```ts
async function test() {
    const promise = new Promise<number>(resolve => {
            resolve(undefined) // This should be forbidden, since undefined isn't number
    })

    const value: number = await promise // The promise resolves undefined but value is a number
}
```

**Expected behavior:** Error

**Actual behavior:** No errors

**Playground Link:**   [link](https://www.typescriptlang.org/play/#src=async%20function%20test()%20%7B%0A%20%20%20%20const%20promise%20%3D%20new%20Promise%3Cnumber%3E(resolve%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20resolve(undefined)%20%2F%2F%20This%20should%20be%20forbidden%2C%20since%20undefined%20isn't%20number%0A%20%20%20%20%7D)%0A%0A%20%20%20%20const%20value%3A%20number%20%3D%20await%20promise%20%2F%2F%20The%20promise%20resolves%20undefined%20but%20value%20is%20a%20number%0A%7D%0A)

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
@rbuckton I assume this is here for a reason, can you explain?

**Comment by mhegazy** [comment]
Please see https://github.com/Microsoft/TypeScript/issues/22040
