### ISSUE TITLE
context is `undefined` in arrow function after `await` statement, when object uses bracket notation for keys (regression)

### ISSUE THREAD

**Issue by iaroslavshvets** [Microsoft/TypeScript#24722]
**TypeScript Version:**  2.9.1

**Search Terms:** 
async, await, context
**Code**

```ts
class A {
  b = async () => {
    await Promise.resolve()

    const obj = {
      ['a']: () => {
        console.log(this) //undefined
      }
    }

    obj['a']();
  }; 
}

const a = new A();

a.b();
```

**Expected behavior:**
this equals to the instance of class A

**Actual behavior:**
this equal to undefined. Commenting out the line with `await` resolves the issue, or not using bracket notation for the object key.

**Playground Link:**  
http://www.typescriptlang.org/play/#src=class%20A%20%7B%0D%0A%20%20b%20%3D%20async%20()%20%3D%3E%20%7B%0D%0A%20%20%20%20await%20Promise.resolve()%0D%0A%0D%0A%20%20%20%20const%20obj%20%3D%20%7B%0D%0A%20%20%20%20%20%20%5B'a'%5D%3A%20()%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20console.log(this)%0D%0A%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20obj%5B'a'%5D()%3B%0D%0A%20%20%7D%3B%20%0D%0A%7D%0D%0A%0D%0Aconst%20a%20%3D%20new%20A()%3B%0D%0A%0D%0Aa.b()%3B

**Related Issues:**

**Comment by andy-ms** [comment]
Works with `--target es6`, broken with `--target es5 --lib es6`.
