### ISSUE TITLE
Plan for `_reference.ts` in tsconfig.json

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#2472]
refs : https://github.com/TypeStrong/atom-typescript/issues/206 

For the people that use `--out` they will need some way to easily specify the ordering of files (in some place other than `files`) like they do in visual studio using `_reference.ts`. 

I don't use (or like `--out`, since its something that's better done by external build tools), but I thought I'd bring it up still.

**Comment by mhegazy** [comment]
so you can still use a separate file containing all references be it your _references.ts or index.ts  and reference it in the files section in your tsconfig. or you can just use files.

Another alternative is for us to add _references.ts support with tsconfig, similar to that in VS, i.e. by pushing the _references.ts to the top. but i wounder if this is needed given that the order in the "files" list in tsconfig is honered.

**Comment by basarat** [comment]
`files` it is then. If I get the time, I'll test it and document it :heart:

**Comment by ahejlsberg** [comment]
Yes, it is definitely the intent for `files` to serve this purpose.
