### ISSUE TITLE
codefix for new method should include asterisk for generator functions

### ISSUE THREAD

**Issue by krk** [Microsoft/TypeScript#24728]
## Search Terms
asterisk, addMethodDeclaration

## Suggestion

When a new method is created that is used by a `yield *` expression, generated method should have an asterisk before its name.

## Use Cases

VSCode would create generator functions when the `addMissingMember` codefix is applied to an invocation inside a `YieldExpression`.

## Examples

New method created by vscode for this block:

```ts
class A {
  private *a() {
    yield* this.abc();
  }
}
```

is:

```ts
abc(): any {
  throw new Error("Method not implemented.");
}
```

and while it is apparent that return type should be changed, it is not obvious to convert the new `abc` funciton to a generator function such as:

```ts
*abc(): any {
  throw new Error("Method not implemented.");
}
```

## Checklist

My suggestion meets these guidelines:
* [X] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by Fatehsandhu** [comment]
@RyanCavanaugh Can I take this, please?
Thanks

**Comment by mhegazy** [comment]
thanks @krk!
