### ISSUE TITLE
Generic method override and type OR not giving the correct type

### ISSUE THREAD

**Issue by rrousselGit** [Microsoft/TypeScript#24721]
Still reproducible with  3.0.0-dev.201xxxxx

**Search Terms:** 

**Code**

```ts
import { Observable } from "rxjs";
import { first } from "rxjs/operators";

var foo: Observable<number> | Observable<string> | Observable<boolean>;

foo.pipe(first());
```

with the typing of the `pipe` function is 

```ts
    pipe(): Observable<T>;
    pipe<A>(op1: OperatorFunction<T, A>): Observable<A>;
    pipe<A, B>(op1: OperatorFunction<T, A>, op2: OperatorFunction<A, B>): Observable<B>;
    pipe<A, B, C>(op1: OperatorFunction<T, A>, op2: OperatorFunction<A, B>, op3: OperatorFunction<B, C>): Observable<C>;
    pipe<A, B, C, D>(op1: OperatorFunction<T, A>, op2: OperatorFunction<A, B>, op3: OperatorFunction<B, C>, op4: OperatorFunction<C, D>): Observable<D>;
    pipe<A, B, C, D, E>(op1: OperatorFunction<T, A>, op2: OperatorFunction<A, B>, op3: OperatorFunction<B, C>, op4: OperatorFunction<C, D>, op5: OperatorFunction<D, E>): Observable<E>;
    pipe<A, B, C, D, E, F>(op1: OperatorFunction<T, A>, op2: OperatorFunction<A, B>, op3: OperatorFunction<B, C>, op4: OperatorFunction<C, D>, op5: OperatorFunction<D, E>, op6: OperatorFunction<E, F>): Observable<F>;
    pipe<A, B, C, D, E, F, G>(op1: OperatorFunction<T, A>, op2: OperatorFunction<A, B>, op3: OperatorFunction<B, C>, op4: OperatorFunction<C, D>, op5: OperatorFunction<D, E>, op6: OperatorFunction<E, F>, op7: OperatorFunction<F, G>): Observable<G>;
    pipe<A, B, C, D, E, F, G, H>(op1: OperatorFunction<T, A>, op2: OperatorFunction<A, B>, op3: OperatorFunction<B, C>, op4: OperatorFunction<C, D>, op5: OperatorFunction<D, E>, op6: OperatorFunction<E, F>, op7: OperatorFunction<F, G>, op8: OperatorFunction<G, H>): Observable<H>;
    pipe<A, B, C, D, E, F, G, H, I>(op1: OperatorFunction<T, A>, op2: OperatorFunction<A, B>, op3: OperatorFunction<B, C>, op4: OperatorFunction<C, D>, op5: OperatorFunction<D, E>, op6: OperatorFunction<E, F>, op7: OperatorFunction<F, G>, op8: OperatorFunction<G, H>, op9: OperatorFunction<H, I>): Observable<I>;
    pipe<R>(...operations: OperatorFunction<T, R>[]): Observable<R>;
```

Which gives `Expected 0 arguments, but got 1` on the last line and shouldn't.

And then I tried to reproduced it without rxjs dependency :

```ts
type Operator<T = {}, S = {}> = (foo: Foo<T>) => Foo<S>;

class Foo<T> {
    pipe(): Foo<T>;
    pipe<A, B>(obj: Operator<T, A>, obj2: Operator<A, B>): Foo<B>;
    pipe<A>(obj: Operator<T, A>): Foo<A>;
    pipe(...obj: Operator[]): Foo<any> {
        return new Foo();
    }
}

var foo: Foo<string> | Foo<number> | Foo<boolean>;

// f and bar are inferred as string instead of string|number|boolean
const f = foo.pipe((bar) => bar);
```

There's no error this time. But the `bar` variable from the `pipe` callback in infered as `string` instead of `string | number | boolean` and therefore the result is invalid too.

**Playground Link:**  

http://www.typescriptlang.org/play/#src=type%20Operator%3CT%20%3D%20%7B%7D%2C%20S%20%3D%20%7B%7D%3E%20%3D%20(foo%3A%20Foo%3CT%3E)%20%3D%3E%20Foo%3CS%3E%3B%0D%0A%0D%0Aclass%20Foo%3CT%3E%20%7B%0D%0A%20%20%20%20pipe()%3A%20Foo%3CT%3E%3B%0D%0A%20%20%20%20pipe%3CA%2C%20B%3E(obj%3A%20Operator%3CT%2C%20A%3E%2C%20obj2%3A%20Operator%3CA%2C%20B%3E)%3A%20Foo%3CB%3E%3B%0D%0A%20%20%20%20pipe%3CA%3E(obj%3A%20Operator%3CT%2C%20A%3E)%3A%20Foo%3CA%3E%3B%0D%0A%20%20%20%20pipe(...obj%3A%20Operator%5B%5D)%3A%20Foo%3Cany%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20new%20Foo()%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Avar%20foo%3A%20Foo%3Cstring%3E%20%7C%20Foo%3Cnumber%3E%20%7C%20Foo%3Cboolean%3E%3B%0D%0A%0D%0A%2F%2F%20f%20and%20bar%20are%20inferred%20as%20string%20instead%20of%20string%7Cnumber%7Cboolean%0D%0Aconst%20f%20%3D%20foo.pipe((bar)%20%3D%3E%20bar)%3B

**Comment by RyanCavanaugh** [comment]
Please provide a standalone repro that reproduces the undesired behavior

**Comment by rrousselGit** [comment]
Isn't the playground link enough ? I mean we can clearly see in the playground that the variables on the last line are inferred incorrectly.

**Comment by RyanCavanaugh** [comment]
@rrousselGit sorry, we usually assume that the Playground link contents are the same as the code posted in the bug report. Looking at it now.

**Comment by RyanCavanaugh** [comment]
`Foo` does not manifest `T` (its self-instantiation "doesn't count" because it's recursive). If you actually have `Foo` vary over `T` then the call to `pipe` is illegal; see #7294

See https://github.com/Microsoft/TypeScript/wiki/FAQ#why-is-astring-assignable-to-anumber-for-interface-at--
