### ISSUE TITLE
Throwing Error from separate function

### ISSUE THREAD

**Issue by KhramtsovMaksim** [Microsoft/TypeScript#24723]
**TypeScript Version:**  2.9.1

**Search Terms:** throw, Error, callback

**Code**

```ts
// --strict
function onError(error: Error): never {
	throw error;
}

const numbers: number[] = [1, 2, 3];

function getAllowedNumberOrThrow1(n: number): number | never {
	const nFromArray = numbers.find(num => num === n);

	if (nFromArray === undefined) {
		onError(new Error(`There is no ${n} in [${numbers.join(", ")}]`));
	}

	/*
	Type 'number | undefined' is not assignable to type 'number'.
	Type 'undefined' is not assignable to type 'number'.
	*/
	return nFromArray;
}


function getAllowedNumberOrThrow2(n: number): number | never {
	const nFromArray = numbers.find(num => num === n);

	if (nFromArray === undefined) {
		throw new Error(`There is no ${n} in [${numbers.join(", ")}]`);
	}

	// OK
	return nFromArray;
}
```
If the error throwing is encapsulated in a separate function on the program (`onError`), the compiler does not understand that the execution thread is terminated at the place of calling this function `onError` in `--strict` mode

**Expected behavior:** compiler do type check right way

**Actual behavior:** compiler ignore result of `onError`

**Playground Link:** http://www.typescriptlang.org/play/index.html#src=function%20onError(error%3A%20Error)%3A%20never%20%7B%0D%0A%09throw%20error%3B%0D%0A%7D%0D%0A%0D%0Aconst%20numbers%3A%20number%5B%5D%20%3D%20%5B1%2C%202%2C%203%5D%3B%0D%0A%0D%0Afunction%20getAllowedNumberOrThrow1(n%3A%20number)%3A%20number%20%7C%20never%20%7B%0D%0A%09const%20nFromArray%20%3D%20numbers.find(num%20%3D%3E%20num%20%3D%3D%3D%20n)%3B%0D%0A%0D%0A%09if%20(nFromArray%20%3D%3D%3D%20undefined)%20%7B%0D%0A%09%09onError(new%20Error(%60There%20is%20no%20%24%7Bn%7D%20in%20%5B%24%7Bnumbers.join(%22%2C%20%22)%7D%5D%60))%3B%0D%0A%09%7D%0D%0A%0D%0A%09%2F*%0D%0A%09Type%C2%A0'number%C2%A0%7C%C2%A0undefined'%C2%A0is%C2%A0not%C2%A0assignable%C2%A0to%C2%A0type%C2%A0'number'.%0D%0A%09Type%C2%A0'undefined'%C2%A0is%C2%A0not%C2%A0assignable%C2%A0to%C2%A0type%C2%A0'number'.%0D%0A%09*%2F%0D%0A%09return%20nFromArray%3B%0D%0A%7D%0D%0A%0D%0A%0D%0Afunction%20getAllowedNumberOrThrow2(n%3A%20number)%3A%20number%20%7C%20never%20%7B%0D%0A%09const%20nFromArray%20%3D%20numbers.find(num%20%3D%3E%20num%20%3D%3D%3D%20n)%3B%0D%0A%0D%0A%09if%20(nFromArray%20%3D%3D%3D%20undefined)%20%7B%0D%0A%09%09throw%20new%20Error(%60There%20is%20no%20%24%7Bn%7D%20in%20%5B%24%7Bnumbers.join(%22%2C%20%22)%7D%5D%60)%3B%0D%0A%09%7D%0D%0A%0D%0A%09%2F%2F%20OK%0D%0A%09return%20nFromArray%3B%0D%0A%7D

**Comment by andy-ms** [comment]
Control flow analysis doesn't consider the types of things, just the AST. This is the same underlying limitation behind #8655.

**Comment by jack-williams** [comment]
When I've come across similar problems I add a `return`, though this might be a non-solution for you.

```ts
function throwError(error: Error): never {
	throw error;
}

const numbers: number[] = [1, 2, 3];

function getAllowedNumberOrThrow1(n: number): number | never {
	const nFromArray = numbers.find(num => num === n);
	if (nFromArray === undefined) {
		return throwError(new Error(`There is no ${n} in [${numbers.join(", ")}]`));
	}
	return nFromArray;
}
```

**Comment by KhramtsovMaksim** [comment]
@jack-williams, thank you. Work for me, but looks not well)

**Comment by bermanboris** [comment]
Please reopen this.
