### ISSUE TITLE
`in` type guards does not work on unions of primitive types

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#24736]
**TypeScript Version:**  3.0.0-dev.201xxxxx

**Search Terms:** 

**Code**

```ts

var x: number | Promise<number>;
if ("then" in x) {  // Error: The right-hand side of an 'in' expression must be of type 'any', an object type or a type parameter.
}

var xx: { a: string } | Promise<number>;
if ("then" in xx) { // OK

}
```

**Expected behavior:**

Both narrowing statements should work

**Actual behavior:**

Only the second works

**Playground Link:**  

**Related Issues:**

**Comment by weswigham** [comment]
I think the error is correct:
![image](https://user-images.githubusercontent.com/2932786/41070735-4fa5a0ae-69a9-11e8-81cf-13fc7b4f8c33.png)

**Comment by mhegazy** [comment]
sorry about the spam then..

**Comment by Rivera09** [comment]
![image](https://user-images.githubusercontent.com/30569489/174198411-b753cfa1-71a6-4673-93dc-70f6e77691af.png)
I this case it seems like a bug to me :/

**Comment by Rivera09** [comment]
![image](https://user-images.githubusercontent.com/30569489/174198520-1e24c787-bd6d-49b8-acb5-1ff8119af146.png)
in this case it seems like a bug to me :/

**Comment by senyaak** [comment]
> in this case it seems like a bug to me :/

its not a bug. You should check first `typeof data === 'object'` and then use `in`, because if `data` would be `number` or `boolean`, the code will throw exception `Cannot use '' operator to search for '' in ''`(Warning! if you have had `null` type, you should check first `data !== null` ;) 
at the end ull have 
```ts
//...
      if (typeof data === 'object' && "id" in data) {
//...
```
