### ISSUE TITLE
Unioned functions resolve to only a single type as result of invocation

### ISSUE THREAD

**Issue by dclowd9901** [Microsoft/TypeScript#24735]
**TypeScript Version:**  2.9.1

**Search Terms:** 

**Code**

```ts
type Foo = (() => object)
type Bar<T> = (() => Promise<T>)
type Bat<T> = Foo | Bar<T>;

const a: Bat<string> = () => new Promise((res, rej) => { res('yay') });

const b = a();

if (!b.then) { // Error: Property 'then' does not exist on type object
  throw new Error();
}

b.then(() => { console.log('do something else'); }); // Error: Property 'then' does not exist on type object
```

**Expected behavior:**

Should be able to at least rule out one of the cases. Result of calling a unioned function type should be a union of functions' return types.

**Actual behavior:**

Errors are thrown even on typechecking. Inspecting return type of `a` will show that only `object` is a possible returned value, rather than the union type.

**Playground Link:**  

http://www.typescriptlang.org/play/#src=type%20Foo%20%3D%20(()%20%3D%3E%20object)%0D%0Atype%20Bar%3CT%3E%20%3D%20(()%20%3D%3E%20Promise%3CT%3E)%0D%0Atype%20Bat%3CT%3E%20%3D%20Foo%20%7C%20Bar%3CT%3E%3B%0D%0A%0D%0Aconst%20a%3A%20Bat%3Cstring%3E%20%3D%20()%20%3D%3E%20new%20Promise((res%2C%20rej)%20%3D%3E%20%7B%20res('yay')%20%7D)%3B%0D%0A%0D%0Aconst%20b%20%3D%20a()%3B%0D%0A%0D%0Ab.then(()%20%3D%3E%20%7B%20console.log('do%20something%20else')%3B%20%7D)%3B

**Related Issues:** 

**Workaround**
Rewriting code to accommodate shortcoming:

```ts
type Foo<T> = (() => object | Promise<T>)

const a: Foo<string> = () => new Promise((res, rej) => { res('yay') });

const b = a();

if (!b.then) {
  throw new Error();
}

b.then(() => { console.log('do something else'); }); 
```

**Comment by mhegazy** [comment]
`a()` returns `object | Promise<string>` but a `Promise<string>` is also an `object`, so the union collapses to `object`. On the next line a variable of type `object` does not have a `then` property.
