### ISSUE TITLE
How to fix TS7016 : Typedef not found 404

### ISSUE THREAD

**Issue by theapache64** [Microsoft/TypeScript#24745]
I am new in react, and I've been doing a project with `Flow`. Last night i met `TypeScript`. It's awesome. I've decided to migrate to `TypeScript` from `Flow` and have been converting my `.js/.jsx` files to `.ts/.tsx`. I've installed type definitions for `react, redux etc`. But i can't find type definition for a library called `react-native-material-color`. It's not a famous library and am getting below error. How can i fix the error ?  

![image](https://user-images.githubusercontent.com/9678279/41087480-71f6364e-6a5a-11e8-8ed1-493dda8ca1e5.png)

**Comment by theapache64** [comment]
I've asked in `SO` no response. So i asked here. Create that file in project root dir ?  or under `node_modules/@types`?

**Comment by j-oliveras** [comment]
Put it inside your project dir.
