### ISSUE TITLE
Type inference issue when using generic function and generic constraint

### ISSUE THREAD

**Issue by ulrichb** [microsoft/TypeScript#24747]
**TypeScript Version:**  3.0.0-dev.20180607 and 2.9.1

**Search Terms:** type inference generic constraint function callback accessor

**Code**

```ts
type GenericFunc<TA, TB> = (x: TA) => TB;

class GenericFuncHolder<TA, TB> {
    constructor(readonly func: GenericFunc<TA, TB>) { }
}

function wrap<TA, TB>(func: GenericFunc<TA, TB>) { return new GenericFuncHolder(func); }

class X { readonly xProperty = "xProperty"; }

class Y<TX> { readonly x: TX | undefined; readonly yProperty = "yProperty"; }
class YDerived<TX> extends Y<TX> { readonly yDerivedProperty = "yDerivedProperty"; }

class GenericTarget<TX, TY> {

    constructor(readonly x: TX, readonly y: TY) { }

    holderParams<TX2, TY2 extends Y<TX2>>(
        holderX: GenericFuncHolder<TX, TX2>, holderY: GenericFuncHolder<TY, TY2>,
        use: (x: TX2, y: TY2) => void,
    ) {
        use(holderX.func(this.x), holderY.func(this.y));
    }

    funcParamsWithoutConstraint<TX2, TY2>(
        funcX: GenericFunc<TX, TX2>, funcY: GenericFunc<TY, TY2>,
        use: (x: TX2, y: TY2) => void,
    ) {
        use(wrap(funcX).func(this.x), wrap(funcY).func(this.y));
    }

    funcParamsWithConstraint_BAD<TX2, TY2 extends Y<TX2>>(
        funcX: GenericFunc<TX, TX2>, funcY: GenericFunc<TY, TY2>,
        use: (x: TX2, y: TY2) => void,
    ) {
        use(wrap(funcX).func(this.x), wrap(funcY).func(this.y));
    }
}


const genericClassTarget = new GenericTarget (new X(), new Y<X>());

// Type inference works when having the constraint but using `wrap()` on the call site:
genericClassTarget.holderParams(wrap(x => new X()), wrap(y => new YDerived<X>()),
    (x2, y2) => console.log(x2.xProperty, y2.yDerivedProperty));

// Type inference works without the `TY2` constraint:
genericClassTarget.funcParamsWithoutConstraint(x => new X(), y => new YDerived<X>(),
    (x2, y2) => console.log(x2.xProperty, y2.yDerivedProperty));

// Type inference doesn't work, TSC emits "TS2339: Property 'xProperty' does not exist on type '{}'"
genericClassTarget.funcParamsWithConstraint_BAD(x => new X(), y => new YDerived<X>(),
    (x2, y2) => console.log(x2.xProperty, y2.yDerivedProperty));

```
(Sorry for the long repro, it's the simplified version of a production issue and the inference issue seems to be a very special case.)

**Expected behavior:**
Type inference works for `funcParamsWithConstraint_BAD` as it works for `holderParams` and `funcParamsWithoutConstraint`. It seems that the generic constraint of `TY2` narrows `TX2` to `{}`, but this works when using `wrap()` on the call site. Which is the reason, why I would expect `funcParamsWithConstraint_BAD` to work just fine.

**Actual behavior:**
"TS2339: Property 'xProperty' does not exist on type '{}'" in the last line.

**Playground Link:** [Playground Link](https://www.typescriptlang.org/play/#src=type%20GenericFunc%3CTA%2C%20TB%3E%20%3D%20(x%3A%20TA)%20%3D%3E%20TB%3B%0D%0A%0D%0Aclass%20GenericFuncHolder%3CTA%2C%20TB%3E%20%7B%0D%0A%20%20%20%20readonly%20func%3A%20GenericFunc%3CTA%2C%20TB%3E%3B%0D%0A%0D%0A%20%20%20%20constructor(func%3A%20GenericFunc%3CTA%2C%20TB%3E)%20%7B%0D%0A%20%20%20%20%20%20%20%20this.func%20%3D%20func%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Afunction%20wrap%3CTA%2C%20TB%3E(func%3A%20GenericFunc%3CTA%2C%20TB%3E)%20%7B%0D%0A%20%20%20%20return%20new%20GenericFuncHolder(func)%3B%0D%0A%7D%0D%0A%0D%0Aclass%20X%20%7B%20readonly%20xProperty%20%3D%20%22xProperty%22%3B%20%7D%0D%0A%0D%0Aclass%20Y%3CTX%3E%20%7B%20readonly%20x%3A%20TX%20%7C%20undefined%3B%20readonly%20yProperty%20%3D%20%22yProperty%22%3B%20%7D%0D%0Aclass%20YDerived%3CTX%3E%20extends%20Y%3CTX%3E%20%7B%20readonly%20yDerivedProperty%20%3D%20%22yDerivedProperty%22%3B%20%7D%0D%0A%0D%0Aclass%20GenericTarget%3CTX%2C%20TY%3E%20%7B%0D%0A%0D%0A%20%20%20%20constructor(readonly%20x%3A%20TX%2C%20readonly%20y%3A%20TY)%20%7B%20%7D%0D%0A%0D%0A%20%20%20%20holderParams%3CTX2%2C%20TY2%20extends%20Y%3CTX2%3E%3E(%0D%0A%20%20%20%20%20%20%20%20holderX%3A%20GenericFuncHolder%3CTX%2C%20TX2%3E%2C%20holderY%3A%20GenericFuncHolder%3CTY%2C%20TY2%3E%2C%0D%0A%20%20%20%20%20%20%20%20use%3A%20(x%3A%20TX2%2C%20y%3A%20TY2)%20%3D%3E%20void%2C%0D%0A%20%20%20%20)%20%7B%0D%0A%20%20%20%20%20%20%20%20use(holderX.func(this.x)%2C%20holderY.func(this.y))%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20funcParamsWithoutConstraint%3CTX2%2C%20TY2%3E(%0D%0A%20%20%20%20%20%20%20%20funcX%3A%20GenericFunc%3CTX%2C%20TX2%3E%2C%20funcY%3A%20GenericFunc%3CTY%2C%20TY2%3E%2C%0D%0A%20%20%20%20%20%20%20%20use%3A%20(x%3A%20TX2%2C%20y%3A%20TY2)%20%3D%3E%20void%2C%0D%0A%20%20%20%20)%20%7B%0D%0A%20%20%20%20%20%20%20%20use(wrap(funcX).func(this.x)%2C%20wrap(funcY).func(this.y))%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20funcParamsWithConstraint_BAD%3CTX2%2C%20TY2%20extends%20Y%3CTX2%3E%3E(%0D%0A%20%20%20%20%20%20%20%20funcX%3A%20GenericFunc%3CTX%2C%20TX2%3E%2C%20funcY%3A%20GenericFunc%3CTY%2C%20TY2%3E%2C%0D%0A%20%20%20%20%20%20%20%20use%3A%20(x%3A%20TX2%2C%20y%3A%20TY2)%20%3D%3E%20void%2C%0D%0A%20%20%20%20)%20%7B%0D%0A%20%20%20%20%20%20%20%20use(wrap(funcX).func(this.x)%2C%20wrap(funcY).func(this.y))%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0A%0D%0Aconst%20genericClassTarget%20%3D%20new%20GenericTarget%20(new%20X()%2C%20new%20Y%3CX%3E())%3B%0D%0A%0D%0A%2F%2F%20Type%20inference%20works%20when%20having%20the%20constraint%20but%20using%20%60wrap()%60%20on%20the%20call%20site%3A%0D%0AgenericClassTarget.holderParams(wrap(x%20%3D%3E%20new%20X())%2C%20wrap(y%20%3D%3E%20new%20YDerived%3CX%3E())%2C%0D%0A%20%20%20%20(x2%2C%20y2)%20%3D%3E%20console.log(x2.xProperty%2C%20y2.yDerivedProperty))%3B%0D%0A%0D%0A%2F%2F%20Type%20inference%20works%20without%20the%20%60TY2%60%20constraint%3A%0D%0AgenericClassTarget.funcParamsWithoutConstraint(x%20%3D%3E%20new%20X()%2C%20y%20%3D%3E%20new%20YDerived%3CX%3E()%2C%0D%0A%20%20%20%20(x2%2C%20y2)%20%3D%3E%20console.log(x2.xProperty%2C%20y2.yDerivedProperty))%3B%0D%0A%0D%0A%2F%2F%20Type%20inference%20doesn't%20work%2C%20TSC%20emits%20%22TS2339%3A%20Property%20'xProperty'%20does%20not%20exist%20on%20type%20'%7B%7D'%22%0D%0AgenericClassTarget.funcParamsWithConstraint_BAD(x%20%3D%3E%20new%20X()%2C%20y%20%3D%3E%20new%20YDerived%3CX%3E()%2C%0D%0A%20%20%20%20(x2%2C%20y2)%20%3D%3E%20console.log(x2.xProperty%2C%20y2.yDerivedProperty))%3B%0D%0A)

*EDIT:* Extended repro to make it more realistic.

**Comment by RyanCavanaugh** [comment]
`TY2` in `_BAD` isn't doing anything. The signature should be written as:

    funcParamsWithConstraint_BAD<TX2>(
        funcX: GenericFunc<TX, TX2>, funcY: GenericFunc<TY, Y<TX2>>,
        useX2: (x: TX2) => void,
    ) {
        wrap(funcX); wrap(funcY);
    }

This works as expected.

**Comment by ulrichb** [comment]
@RyanCavanaugh Also added `YDerived` to better motivate the `TY2`.

**Comment by ulrichb** [comment]
@RyanCavanaugh Any news on this? 

I have now a second but much easier sample using a conditional type instead of a generic constraint:

```TS
type GenericFunc<TA, TB> = (x: TA) => TB;

class GenericFuncHolder<TA, TB> {
    readonly func: GenericFunc<TA, TB>;

    constructor(func: GenericFunc<TA, TB>) {
        this.func = func;
    }
}

function wrap<TA, TB>(func: GenericFunc<TA, TB>) {
    return new GenericFuncHolder(func);
}

//

export type PropertyToTypeName<TProperty> =
    TProperty extends string | undefined ? "text" :
        TProperty extends number | undefined ? "number" :
            never;

function withFunc<TProperty>(
    func: GenericFunc<string, TProperty>, typeName: PropertyToTypeName<TProperty>) {
    console.log('func points to', typeName);
}

function withHolder<TProperty>(
    holder: GenericFuncHolder<string, TProperty>, typeName: PropertyToTypeName<TProperty>) {
    console.log('holder points to', typeName);
}


withHolder(wrap(x => x.length), "number"); // works fine

// emits TS2345: Argument of type '"number"' is not assignable to parameter of type 'never'
withFunc(x => x.length, "number");

```

... like in the sample above the problem is that in the `withFunc`-case `TProperty` infers to `{}` which you can see when adding `TProperty extends {} ? "[is empty object]"` to the conditional type.

**Comment by RyanCavanaugh** [comment]
I feel like I'm missing something, because this example really shouldn't error, but has since 2.8
```ts
type TypeName<T> = T extends number ? "number" : "something else";
function fn<T>(func: (x: string) => T, p: TypeName<T>): void { }
// Error
fn(x => x.length, "number");
```

**Comment by RyanCavanaugh** [comment]
The sample above now produces a crash in the LS in the Playground...
