### ISSUE TITLE
Remove unused quick fix removes single line comments

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#24758]
**TypeScript Version:**  3.0.0-dev.20180607

**Search Terms:** 
- Quick fix 
- Remove unused declaration
- comment 

**Code**
1. For the code: 

```ts
// a comment

const unused = 1;

export const x = 1;
```

2. Run the `remove declaration` quick fix on `unused`

**Expected behavior:**
Only `const unused = 1;` removed

**Actual behavior:**
The leading comment is also unused.

In this case, I think we should only remove js docs style comments or `// @ts-ignore` comments

**Related Issues:** 
- #20902

**Comment by mhegazy** [comment]
Comments preceding a declaration are considered attached to it. so when a declaration is removed, the attached comments will be removed as well.

**Comment by mjbvz** [comment]
I'm not sure this should apply to `//` comments, except for special ones like `// @ts-ignore`. If do keep the current behavior however, can we make sure the comment immediately  precedes the declaration it is attached to?

**Comment by AlCalzone** [comment]
I just stumbled upon this when the quick fix also removed my tslint annotations at the start of the file:

```ts
// tslint:disable:no-console
// tslint:disable:no-unused-expression
// tslint:disable:variable-name

import { assert, expect } from "chai";

const { a, used, _module, and, some, other, unused, modules } = require("./anotherModule");

// v--- all good down there ---v
```
I ran a quick fix to remove unused declarations on the line with `require`. `assert` and `expect` weren't used in that test file. The quick fix removed that import too, along with the entire comment block!

**Result:**
```ts
const { a, used, _module } = require("./anotherModule");

// v--- bunch of tslint errors down there ---v
```

As a result the test file was riddled with tslint errors. In this particular case I don't believe its actually working as intended.

cc @mhegazy @mjbvz

**Comment by dialex** [comment]
> Comments preceding a declaration are considered attached to it. so when a declaration is removed, the attached comments will be removed as well.

That's not 100% true. In my case I had a **comment as a section**, and I want to keep it there: 

```js
// Selectors
const used1 = "#id"
const unused2 = ".class"
const used3 = "body ul p.something"
```
