### ISSUE TITLE
Preference for including file extension on auto imports

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#24779]
## Search Terms

- Auto imports 
- Preferences 
- File extensions

## Suggestion

From https://github.com/Microsoft/vscode/issues/51259

Add a preference to include file extensions on auto import paths.

## Use Cases

File extensions are required when working with browsers.

## Examples
`a.js`:

```js
export const abc = 123;
```

`b.js`
```js
abc|
```

Trigger auto import on `abc` in `b.js` to get:

```js
import { abc } from './a.js'

abc
```

**Comment by andrewbranch** [comment]
This has actually existed in TS since #26177, but was never added to typescript-language-features. I just tried it and confirmed it works. From conversation in #28288, though, it sounds like we should maybe consider setting `.js` endings as the default for JS projects? @mjbvz @DanielRosenwasser thoughts?

**Comment by wsmd** [comment]
(Question related to #90405) Is there an existing configuration that can achieve the same behavior for autosuggest when typing the import statement manually?

For example:

```json
{
  "javascript.preferences.importModuleSpecifierEnding": "js",
}
```

```js
import { someFunction } from './|';
                                ^ when picking a file from autosuggest here,
                                  the file extension seems to always be omitted
```

**Comment by andrewbranch** [comment]
I can’t immediately think of a reason why we shouldn’t respect that same setting for module specifier completions. @wsmd would you mind opening a new bug for this?

**Comment by wsmd** [comment]
Thanks @andrewbranch! Will do! I think it would be nice to have `importModuleSpecifierEnding` applies for both auto-imports and manual import suggestions 👍
