### ISSUE TITLE
Typescript separate formatting rules for anonymous functions / lambdas

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#24777]
_From @vrachels on June 7, 2018 22:23_

Requesting additional functionality to differentiate the formatting between anonymous and named functions.
ie: "typescript.format.placeOpenBraceOnNewLineForAnonymousFunctions": boolean
or: "typescript.format.placeOpenBraceOnNewLineForInlineFunctions": boolean

similarly, having a separate indentation pattern would be ideal.
the main gripe is that with new line for functions = true, the anonymous/inline functions end up looking something like:
```
foo()
{
    array.forEach(() =>
    {
       // bar
    });
}
```
while my preferred is more like one of:
```
fooWithInlineNewLineFalse()
{
    array.forEach(() => {
        // bar
    }
}
fooWithInlineIndent()
{
    array.forEach(() =>
        {
            // bar
        }
}
fooWithBoth()
{
    array.forEach(() => {
            // bar
        }
}
```

Before posting, my researched showed that switch/case indenting has similar outstanding issues as well, but nothing related to this particular area.

I don't see any way for vscode to customize either situation.  Pointers to an extension that supports such things would be happily appreciated.

_Copied from original issue: Microsoft/vscode#51395_

**Comment by mjbvz** [comment]
Moving upstream to see if there is any additional interest. More advanced formatting options like this may be better left to an extension

**Comment by heroboy** [comment]
this this this https://github.com/Microsoft/TypeScript/issues/9124

**Comment by mjbvz** [comment]
Closing due to lack of further community feedback / interest
