### ISSUE TITLE
Remove unused parameter leaves trailing comma in destructured array parameter 

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#24788]
From https://github.com/Microsoft/vscode/issues/51417

**TypeScript Version:**  3.0.0-dev.20180607

**Search Terms:** 
- Remove unused variable / parameter
- quick fix

**Code**
1. For the code:

```ts
const a = ([x, y]) => x;
```

2. Run the  `remove unused` quick fix on `y`

**Expected behavior:**

```ts
const a = ([x]) => x;
```

**Actual behavior:**
Extra comma after `a`:

```ts
const a = ([x, y]) => x;
```

**Playground Link:**  

**Related Issues:**

**Comment by alexfung888** [comment]
I believe you mean:

**Actual behavior:**
Extra comma after a:

`const a = ([x,]) => x;`

**Comment by mhegazy** [comment]
last element in an array binding pattern should remove the comma.. ones in the middle should not.
