### ISSUE TITLE
Apply interface to part of object literal

### ISSUE THREAD

**Issue by TedDriggs** [microsoft/TypeScript#24780]
## Search Terms
* object literal type merge
* interface object literal

## Suggestion
I'd like to export a const that is forced to adhere to an interface for the fields that interface declares, but with the other fields keeping the types inferred from the literal object.

## Use Cases
This would allow constraining the type of an object literal while keeping the code DRY by avoiding interface declarations that could be inferred from usage.

## Examples

```typescript
/**
 * A static container for `T` which exposes all fields of `T`.
 */
export interface Fields<T> {
    FIELDS: (keyof T)[];
    // THIS IS NECESSARY TO PREVENT ERRORS TODAY, BUT STRIPS TYPES FOR OTHER PROPERTIES OF LITERAL
    [x: string]: any;
}

export interface Filter {
    name: string;
    author: string;
    id: number;
}

export type FilterProperties = Pick<
    Filter,
    | 'name'
    | 'author'
>;

export const FilterProperties: Fields<FilterProperties> = {
    FIELDS: [
        'name',
        'author',
    ],
    pick: <T extends FilterProperties>(value: T): FilterProperties =>
        pick(value, FilterProperties.FIELDS),
};

FilterProperties.pick({ name: 'Hello', author: 'World', id: 1 }).___;
// ^ I'd like this to complete with "name" and "author", but currently it is an `any`
```

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by mhegazy** [comment]
I am guessing you need the interface for the literal type for `FIELDS`. and for that, why not just define it as:
```ts

export const FilterProperties=  {
    FIELDS: [
        'name',
        'author',
    ] as Array<keyof FilterProperties>,
    pick: <T extends FilterProperties>(value: T): FilterProperties =>
        pick(value, FilterProperties.FIELDS),
};
```

**Comment by TedDriggs** [comment]
That doesn't produce an error in the case that `FIELDS` gets out of sync with `FilterProperties`, which is what I was trying to achieve.

**Comment by TedDriggs** [comment]
@mhegazy I've found a workaround for this where I moved the declaration of `FIELDS` into a generic function. I then spread the return value of that function into the declared const, which gives me the desired compile-time declaration and usage safety.

That said, I still wish there was a way to say "this const implements/extends interface `Foo`, but is allowed to have additional fields whose types are inferred"

**Comment by RyanCavanaugh** [comment]
This use case tracked at #7481
