### ISSUE TITLE
tsserver support for multiple tsconfig projects in the same folder

### ISSUE THREAD

**Issue by dgoldstein0** [Microsoft/TypeScript#24786]
## Search Terms

multiple projects tsconfig tsserver

## Suggestion

Currently, typescript editor integrations tend to assume that there is at most one typescript project in a folder - the one matching the tsconfig.json file found in that folder.  It would be useful if tsconfig could evolve to support multiple tsconfigs in a single folder - with a way for tsserver to discover which config applies to a particular file.

## Use Cases

Medium to large projects often get a lot of benefits from being split up into smaller libraries, as tooling can then be added to manage these libraries - such as drawing a higher-level dependency graph and building test and deploy tooling on top of that.  In particular, Dropbox has been using Bazel for this purpose, which has provided us a shared build system and has enabled us to build caching layers, development tooling, and selective testing.

However, we would like to avoid writing our own editor integrations; we currently lean on various of-the-shelf editor integrations, which are all powered by tsserver.  So we are planning to use our bazel BUILD files, which specify the library structure of our code, to generate corresponding tsconfig.json files which will then power our editors.  This is looking especially plausible with the upcoming Typescript 3 release, which is planning to include the "composite projects" feature; with this, we should be able to mirror all of our bazel deps into generated tsconfig files.

Except, that typescript plugins generally can't support multiple libraries being located in the same folder; whereas with bazel, such thing is perfectly legal, and often desirable - e.g. you may mix your tests in with your code, perhaps as `*.test.ts` files, and then have one library of `glob(["*.ts"], exclude=["*.test.ts"])` and make your tests use `glob(["*.test.ts"])`; or you could have a separate library of test utils that you mark as testonly=True (bazel's way of saying, only allow other test-only or test code to use this); or you could have two libraries with different visibilities, where one has the public interface to the package and broad visibility, and the other is all the implementation details, with restrictive visibility to prevent direct usage from other packages.  Or perhaps the most common use case: splitting code into libraries while improving the code organization - as it's unfortunately common for poorly organized projects to evolve poor code organization over time, and a library structure may be imposed later; in which case having multiple libraries in the same folder is common.

Of course using bazel is not a requirement here; any sort of system for splitting codebases into libraries (e.g. other build systems) could benefit from this support.

## Examples

tsconfig.json
```
{
  "projects": [
    "./tsconfig_lib1.json",
    "./tsconfig_lib2.json",
    "./tsconfig_tests.json",
  ]
}
```

and then each of the other tsconfig files could specify which `files` it applies to.  E.g.

./tsconfig_lib1.json
```
{
  "compilerOptions: ...
  "files": ["a.ts", "b.ts"],
}
```

./tsconfig_lib2.json
```
{
  "compilerOptions: ...
  "files": ["c.ts", "d.ts"],
}
```

And then when tsserver needs to give autocompletions, type errors, etc. on a.ts, it can see from tsconfig.json that it needs to search several project files, and it'll end up finding that a.ts is part of tsconfig_lib1 and use the settings in that file to do any necessary work.

In general it's possible for multiple tsconfig files to reference overlapping sets of files; this should probably be treated as an error, which can be surfaced as an error message from tsserver.

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by mhegazy** [comment]
looks like this should be covered by the work being done in https://github.com/Microsoft/TypeScript/issues/3469

**Comment by dgoldstein0** [comment]
is it?  From that thread, it's not clear to me if they are working on support for "at most one project per folder, with dependencies on other projects" or if they include the multiple projects in a single folder case.

I would be happy for this to be included as a feature of composite projects.
