### ISSUE TITLE
Regression in 2.9+: conditional type inferring empty object

### ISSUE THREAD

**Issue by jamesknelson** [Microsoft/TypeScript#24784]
**TypeScript Version:**  3.0.0-dev.20180607

**Search Terms:** 

conditional inference empty infer extends mapped

**Code**

```ts
type Combine<C, Prop extends string> = {
  [Key in keyof C]: (
    C[Key] extends { [X in Prop]: infer Just } ? Just :
    C[Key] extends { [X in Prop]?: infer Maybe } ? (Maybe | undefined) :
    undefined
  )
}

type Test = {
  x: {
    test?: boolean,
  },
  y: {
    test?: boolean,
  },
}

type Combined = Combine<Test, 'test'>

let combined: Combined

// Type '{}' is not assignable to type 'boolean'.
let flag: boolean = combined.x
```

**Expected behavior:**

Should compile, as the type of `combined.x` should be boolean.

**Actual behavior:**

In 2.9+, fails with "Type '{}' is not assignable to type 'boolean'."

In 2.8.1, compiles without error.

**Playground Link:**  

[Playground link](https://www.typescriptlang.org/play/index.html#src=type%20Combine%3CC%2C%20Prop%20extends%20string%3E%20%3D%20%7B%0D%0A%20%20%5BKey%20in%20keyof%20C%5D%3A%20(%0D%0A%20%20%20%20C%5BKey%5D%20extends%20%7B%20%5BX%20in%20Prop%5D%3A%20infer%20Just%20%7D%20%3F%20Just%20%3A%0D%0A%20%20%20%20C%5BKey%5D%20extends%20%7B%20%5BX%20in%20Prop%5D%3F%3A%20infer%20Maybe%20%7D%20%3F%20(Maybe%20%7C%20undefined)%20%3A%0D%0A%20%20%20%20undefined%0D%0A%20%20)%0D%0A%7D%0D%0A%0D%0Atype%20Test%20%3D%20%7B%0D%0A%20%20x%3A%20%7B%0D%0A%20%20%20%20test%3F%3A%20boolean%2C%0D%0A%20%20%7D%2C%0D%0A%20%20y%3A%20%7B%0D%0A%20%20%20%20test%3F%3A%20boolean%2C%0D%0A%20%20%7D%2C%0D%0A%7D%0D%0A%0D%0Atype%20Combined%20%3D%20Combine%3CTest%2C%20'test'%3E%0D%0A%0D%0Alet%20combined%3A%20Combined%0D%0A%0D%0A%2F%2F%20Type%20'%7B%7D'%20is%20not%20assignable%20to%20type%20'boolean'.%0D%0Alet%20flag%3A%20boolean%20%3D%20combined.x)

**Related Issues:** 

- https://github.com/Microsoft/TypeScript/issues/24640

**Comment by RyanCavanaugh** [comment]
This got fixed in 3.2
