### ISSUE TITLE
Yielding promise from async generator is breaking change in TS 2.9

### ISSUE THREAD

**Issue by edvinv** [Microsoft/TypeScript#24787]
Yielding promise from async generator behaves differently in TS 2.8 and TS 2.9, and this should be mentioned in Breaking changes wiki section.

```typescript
async function* g() {
	yield Promise.resolve(10);
}
g().next().then(v => console.log(v.value));


// TS 2.8
>> 10
// TS 2.9
>>
>> Promise { resolved }
```

**Comment by mhegazy** [comment]
Should be fixed in `typescript@next` as of today and in `typescript@2.9.2` next week.
