### ISSUE TITLE
Suggestion: Type-guarded method subsets

### ISSUE THREAD

**Issue by Artazor** [Microsoft/TypeScript#2478]
Since we don't have an ability to reference formal generic parameters in the same generic parameter section, I'd be happy with simpler yet powerful solution: type-guarded method subsets in interfaces and classes.

Let's consider the following example:

```TypeScript
class Something<T> {
     value: T;
     constructor(value: T) {
         this.value = value;
     }

     replace(x: T): T { // Common method
            var tmp = this.value;
            this.value = x;
            return tmp;
     }

     ?<Item> (Item[] = T) {  // Type destructuring (!)
           push(item: Item): void {
                this.value.push(item); // here this.value has type Item[] 
           }
           pop(): Item {
                return this.value.pop();
           }
     }

     ?<T1,T2> ([T1,T2] = T) { // Another destructuring
          immutableSwap(): Something<[T2,T1]> {
               return new Something([this.value[1], this.value[0]]);
          }
     }

     ? (T extends Runnable) { // Narrowing
          run() {
              this.value.run();
          }
     }

      ?<X> (T extends DropTarget<X>) { // Extracting formals from other generics (***)
          drop(x: X) {
               this.value.accept(x);
          }
     }
}
```

Here 
* All guarded members share the same namespace with non-guarded and always are compiled into output code.
* We can introduce new formal types in `?<T1,T2,...>( TypeMatchingExpression ) { Members* }` that can be referenced in guarded blocks
* The main difference between proposed feature and self-referring bound generics is that here you can instantiate a class with any actual generic type. After choosing an actual type parameters, some methods become available/unavailable. It means that we have an additional "type-refinement" phase after the normal type inference is completed (that could be postponed until the member access / autocomplete performed)

I believe this semantics would be a great counterpart for the in-method type guards. I think that it is a powerful extension to the type system and better matches the dynamic behavior of the javascript.

I don't see any obstacles to implementing this behavior and would be happy to design a detailed proposal / implement it if the community will accept the idea.

@ahejlsberg, community - any thoughts?

(the idea itself has arisen when struggling with writing a fine-typed definition for the new version of the Bluebird promise library (to submit 3.0.0 when it will be released it into @DefinitelyTyped))

**UPD:**  replaced initial `if` with `?` to remove a syntactical ambiguity

**Comment by Artazor** [comment]
Does anybody understand what is being proposed? Or it is too complex to be usable?

**Comment by RyanCavanaugh** [comment]
Some examples of actually calling in to `Something` would be very helpful in letting people understand this more quickly. It's not clear what the intended shape of its public surface area is.

**Comment by spion** [comment]
Example:

`Promise#spread` should only be available on Promise<Array<T>>, not on all Promise<T>. Its possible to  restrict this for an external function, but unfortunately not possible for a method.

**Comment by Artazor** [comment]
@spion Exactly! and the type guard `?<Item = T[]> {  /* Methods only for Promise<Array<Item>> */ }` will allow staticaly expose these methods/signatures only for `Promise<Array<Item>>`.

**Comment by Artazor** [comment]
Let's consider an example we want to be correctly statically typed

```TypeScript

Promise.resolve(123).then(function(x){
	return [x, "A"];
}).spread(function(a,b){ 
	return Promise.resolve([a, a+1, b.length]);
}).spread(function(x,y,z){ 
	return x + y + z;
}).then(function(a){ 
	return a.toExponential().split("e");
}).spread(function(...args){ 
	return args.map((x) => x.length).join(":")
}).then(function(x){
	window.alert(x.toUpperCase()) // should output "4:2"
})
```

We don't want to see `.spread` on `Promise.resolve(123)`, though we do on the `Promise.resolve([1,2,3])`.

I understand that we can achieve desired behavior partially by introducing the following declarations:

```TypeScript
interface Promise<T> { /*...*/ }
interface Promise2<T1, T2> extends Promise<[T1,T2]> { /*...*/ }
interface Promise3<T1, T2, T3> extends Promise<[T1,T2,T3]> { /*...*/ }
interface PromiseArray<Item> extends Promise<Array<Item>> { /*...*/ }
```
* **Actual Declarations with working example [moved to TypeScript playground](http://www.typescriptlang.org/Playground#src=%2F%2F%20You%20can%20run%20this%20example%20by%20clicking%20%22run%22%0Aif%20(typeof%20Promise%20!%3D%3D%20%22function%22)%20%7B%0A%09throw%20new%20Error(%22This%20example%20relies%20on%20global%20Promise%22)%3B%0A%7D%0A%0A%2F%2F%20spread%20method%20polyfill%0Athis.Promise.prototype.spread%20%3D%20function(fn)%7B%0A%09return%20this.then(function(r)%7B%0A%09%09var%20self%20%3D%20this%3B%0A%09%09return%20Promise.all(r).then(function(array)%7B%0A%09%09%09return%20fn.apply(self%2C%20array)%3B%0A%09%09%7D)%0A%09%7D)%3B%0A%7D%0A%0A%2F%2F%20The%20following%20example%20is%20CORRECTLY%20(!)%20typed.%0A%2F%2F%20you%20can%20chek%20it%20by%20examining%20autocomplete%20items%0A%0APromise.resolve(123).then(function(x)%7B%0A%09return%20%5Bx%2C%20%22A%22%5D%3B%0A%7D).spread(function(a%2Cb)%7B%20%0A%09return%20Promise.resolve(%5Ba%2C%20a%2B1%2C%20b.length%5D)%3B%0A%7D).spread(function(x%2Cy%2Cz)%7B%20%0A%09return%20x%20%2B%20y%20%2B%20z%3B%0A%7D).then(function(a)%7B%20%0A%09return%20a.toExponential().split(%22e%22)%3B%0A%7D).spread(function(...args)%7B%20%0A%09return%20args.map((x)%20%3D%3E%20x.length).join(%22%3A%22)%0A%7D).then(function(x)%7B%0A%09window.alert(x.toUpperCase())%20%2F%2F%20should%20output%20%224%3A2%22%0A%7D)%0A%0A%0A%2F%2F%20Declarations%0A%0Ainterface%20Promise%3CT%3E%20%7B%0A%09then%3CU1%2CU2%2CU3%3E(fn%3A%20(r%3A%20T)%20%3D%3E%20%5BU1%7CPromise%3CU1%3E%2C%20U2%7CPromise%3CU2%3E%2C%20U3%7CPromise%3CU3%3E%5D%7CPromise%3C%5BU1%7CPromise%3CU1%3E%2C%20U2%7CPromise%3CU2%3E%2C%20U3%7CPromise%3CU3%3E%5D%3E)%3A%20Promise3%3CU1%2CU2%2CU3%3E%0A%09then%3CU1%2CU2%3E(fn%3A%20(r%3A%20T)%20%3D%3E%20%5BU1%7CPromise%3CU1%3E%2C%20U2%7CPromise%3CU2%3E%5D%7CPromise%3C%5BU1%7CPromise%3CU1%3E%2C%20U2%7CPromise%3CU2%3E%5D%3E)%3A%20Promise2%3CU1%2CU2%3E%0A%09then%3CI%3E(fn%3A%20(r%3AT)%20%3D%3E%20(I%7CPromise%3CI%3E)%5B%5D%7CPromise%3C(I%7CPromise%3CI%3E)%5B%5D%3E)%3A%20PromiseArray%3CI%3E%3B%0A%09then%3CU%3E(fn%3A%20(r%3AT)%20%3D%3E%20U%7CPromise%3CU%3E)%3A%20Promise%3CU%3E%3B%0A%7D%0A%0Ainterface%20Promise2%3CT1%2C%20T2%3E%20extends%20Promise%3C%5BT1%2C%20T2%5D%3E%7B%0A%09spread%3CU1%2CU2%2CU3%3E(fn%3A%20(a%3A%20T1%2C%20b%3A%20T2)%20%3D%3E%20%5BU1%7CPromise%3CU1%3E%2C%20U2%7CPromise%3CU2%3E%2C%20U3%7CPromise%3CU3%3E%5D%7CPromise%3C%5BU1%7CPromise%3CU1%3E%2C%20U2%7CPromise%3CU2%3E%2C%20U3%7CPromise%3CU3%3E%5D%3E)%3A%20Promise3%3CU1%2CU2%2CU3%3E%0A%09spread%3CU1%2CU2%3E(fn%3A%20(a%3A%20T1%2C%20b%3A%20T2)%20%3D%3E%20%5BU1%7CPromise%3CU1%3E%2C%20U2%7CPromise%3CU2%3E%5D%7CPromise%3C%5BU1%7CPromise%3CU1%3E%2C%20U2%7CPromise%3CU2%3E%5D%3E)%3A%20Promise2%3CU1%2CU2%3E%0A%09spread%3CJ%3E(u%3A%20(a%3A%20T1%2C%20b%3A%20T2)%20%3D%3E%20(J%7CPromise%3CJ%3E)%5B%5D%7CPromise%3C(J%7CPromise%3CJ%3E)%5B%5D%3E)%3A%20PromiseArray%3CJ%3E%0A%09spread%3CU%3E(u%3A%20(a%3A%20T1%2C%20b%3A%20T2)%20%3D%3E%20U%7CPromise%3CU%3E)%3A%20Promise%3CU%3E%0A%7D%0A%0Ainterface%20Promise3%3CT1%2C%20T2%2C%20T3%3E%20extends%20Promise%3C%5BT1%2C%20T2%2C%20T3%5D%3E%7B%0A%09spread%3CU1%2CU2%2CU3%3E(fn%3A%20(a%3A%20T1%2C%20b%3A%20T2%2C%20c%3A%20T3)%20%3D%3E%20%5BU1%7CPromise%3CU1%3E%2C%20U2%7CPromise%3CU2%3E%2C%20U3%7CPromise%3CU3%3E%5D%7CPromise%3C%5BU1%7CPromise%3CU1%3E%2C%20U2%7CPromise%3CU2%3E%2C%20U3%7CPromise%3CU3%3E%5D%3E)%3A%20Promise3%3CU1%2CU2%2CU3%3E%0A%09spread%3CU1%2CU2%3E(fn%3A%20(a%3A%20T1%2C%20b%3A%20T2%2C%20c%3A%20T3)%20%3D%3E%20%5BU1%7CPromise%3CU1%3E%2C%20U2%7CPromise%3CU2%3E%5D%7CPromise%3C%5BU1%7CPromise%3CU1%3E%2C%20U2%7CPromise%3CU2%3E%5D%3E)%3A%20Promise2%3CU1%2CU2%3E%0A%09spread%3CJ%3E(u%3A%20(a%3A%20T1%2C%20b%3A%20T2%2C%20c%3A%20T3)%20%3D%3E%20(J%7CPromise%3CJ%3E)%5B%5D%7CPromise%3C(J%7CPromise%3CJ%3E)%5B%5D%3E)%3A%20PromiseArray%3CJ%3E%0A%09spread%3CU%3E(u%3A%20(a%3A%20T1%2C%20b%3A%20T2%2C%20c%3A%20T3)%20%3D%3E%20U%7CPromise%3CU%3E)%3A%20Promise%3CU%3E%0A%7D%0A%0Ainterface%20PromiseArray%3CI%3E%20extends%20Promise%3CArray%3CI%3E%3E%20%7B%0A%09spread%3CU1%2CU2%2CU3%3E(u%3A%20(...args%3A%20I%5B%5D)%20%3D%3E%20%5BU1%7CPromise%3CU1%3E%2C%20U2%7CPromise%3CU2%3E%2C%20U3%7CPromise%3CU3%3E%5D%7CPromise%3C%5BU1%7CPromise%3CU1%3E%2C%20U2%7CPromise%3CU2%3E%2C%20U3%7CPromise%3CU3%3E%5D%3E)%3A%20Promise3%3CU1%2CU2%2CU3%3E%0A%09spread%3CU1%2CU2%3E(u%3A%20(...args%3A%20I%5B%5D)%20%3D%3E%20%5BU1%7CPromise%3CU1%3E%2C%20U2%7CPromise%3CU2%3E%5D%7CPromise%3C%5BU1%7CPromise%3CU1%3E%2C%20U2%7CPromise%3CU2%3E%5D%3E)%3A%20Promise2%3CU1%2CU2%3E%0A%09spread%3CJ%3E(u%3A%20(...args%3A%20I%5B%5D)%20%3D%3E%20(J%7CPromise%3CJ%3E)%5B%5D%7CPromise%3C(J%7CPromise%3CJ%3E)%5B%5D%3E)%3A%20PromiseArray%3CJ%3E%0A%09spread%3CU%3E(u%3A%20(...args%3A%20I%5B%5D)%20%3D%3E%20U%7CPromise%3CU%3E)%3A%20Promise%3CU%3E%0A%7D%0A%0Adeclare%20module%20Promise%20%7B%0A%09function%20all%3CU1%2CU2%2CU3%3E(value%3A%20%5BU1%7CPromise%3CU1%3E%2C%20U2%7CPromise%3CU2%3E%2C%20U3%7CPromise%3CU3%3E%5D%7CPromise%3C%5BU1%7CPromise%3CU1%3E%2C%20U2%7CPromise%3CU2%3E%2C%20U3%7CPromise%3CU3%3E%5D%3E)%3A%20Promise3%3CU1%2CU2%2CU3%3E%0A%09function%20all%3CU1%2CU2%3E(value%3A%20%5BU1%7CPromise%3CU1%3E%2C%20U2%7CPromise%3CU2%3E%5D%7CPromise%3C%5BU1%7CPromise%3CU1%3E%2C%20U2%7CPromise%3CU2%3E%5D%3E)%3A%20Promise2%3CU1%2CU2%3E%0A%09function%20all%3CI%3E(value%3A%20(I%7CPromise%3CI%3E)%5B%5D%7CPromise%3C(I%7CPromise%3CI%3E)%5B%5D%3E)%3A%20PromiseArray%3CI%3E%3B%0A%0A%09function%20resolve%3CU1%2CU2%2CU3%3E(value%3A%20%5BU1%2CU2%2CU3%5D%7CPromise%3C%5BU1%2CU2%2CU3%5D%3E)%3A%20Promise3%3CU1%2CU2%2CU3%3E%0A%09function%20resolve%3CU1%2CU2%3E(value%3A%20%5BU1%2CU2%5D%7CPromise%3C%5BU1%2CU2%5D%3E)%3A%20Promise2%3CU1%2CU2%3E%0A%09function%20resolve%3CI%3E(value%3A%20I%5B%5D%7CPromise%3CI%5B%5D%3E)%3A%20PromiseArray%3CI%3E%3B%0A%09function%20resolve%3CU%3E(value%3A%20U%7CPromise%3CU%3E)%3A%20Promise%3CU%3E%3B%0A%7D%0A%0A)**

In our own library (.d.ts) we can make all signatures coherent and aware of such variants. Nevertheless, if we will obtain Promise<Array<T>> from the type-inference in *user's code* then `.spread()` method will not be available.

```TypeScript
function myResolve<T>(value: T): Promise<T> {
     return Promise.resolve(value);
}

Promise.resolve([1,2,3]).spread(function(a,b,c){ ... }) // ok
myResolve([1,2,3]).spread(function(a,b,c){...}) // will fail (without the proposed feature)
```

Implementation of **static type-destucturing guards** (the proposed name of the feature) will allow to overcome this problem.

**Comment by Artazor** [comment]
@spion, can you review my approach for typing Promises (example in playground above)?

**Comment by spion** [comment]
Yeah, with union types its actually feasible to do this now. Without them the number of overloads would be prohibitive.

In any case, `Promise#spread` will become unnecessary once we get destructuring arguments; it can then be replaced by `promise.then([a1, a2] => ...)`

**Comment by RyanCavanaugh** [comment]
Discussed at the design backlog meeting. This seems too complex for the problem it's solving; the promise typing problem is somewhat of an isolated case. Ideally that could be addressed by something less complex - maybe generic type arity overloading, maybe something else.
