### ISSUE TITLE
A function gets a different return type depending on where it is executed. Why?

### ISSUE THREAD

**Issue by sebinsua** [Microsoft/TypeScript#24782]
Surely the type of `value` should be the same as `value2`? Why isn't this case? Is there an issue created for this already? Are there any sensible workarounds?

```ts
const lazyValues = {
  'a': () => 50,
  'b': () => '100',
  'c': () => true
}

type Keys = keyof typeof lazyValues;

function getValue__badtypes<K extends Keys>(name: K) {
  const lazyValue = lazyValues[name];
  return lazyValue();
}

function getValue__goodtypes<K extends Keys>(name: K) {
  const lazyValue = lazyValues[name];
  return lazyValue;
}

async function main() {
  const value = getValue__badtypes('a'); // string | number | boolean
  const value2 = getValue__goodtypes('a')(); // number
}
```

*This was tested on TypeScript **v2.9.1***.

**Comment by andy-ms** [comment]
I think this is a limitation of type inference. It's possible to give `getValue__badtypes` a good type, but requires an explicit cast.
```ts
function getValue__badtypes<K extends Keys>(name: K): ReturnType<(typeof lazyValues)[K]> {
    const lazyValue = lazyValues[name];
    return lazyValue() as ReturnType<typeof lazyValue>;
}
```

Unfortunately we currently don't recognize `f()` as being assignable to `ReturnType<typeof f>`, and we don't infer that as a type either.

**Comment by mhegazy** [comment]
Overload resolution is only done at zero-order and not on generic types. in other words, they are not deferred until instantiation happens like index access. we will need a new concept of call types to be able to handle things like that.

**Comment by sebinsua** [comment]
Thanks so much for both of your answers (both a workaround and some context on the issue). I noticed #6606 is closed? Is this a feature which is in any roadmap?

Also, in general, I do not know how to come up with workarounds for problems like this, and it is very hard to search for solutions to problems in the type-system - because everything we talk about is so abstract. Does anybody know any way of searching for stuff like this, or any documentation of workarounds which people might need to use during day-to-day development?

**Comment by mhegazy** [comment]
> Is this a feature which is in any roadmap?

not at the time being. see https://github.com/Microsoft/TypeScript/issues/6606#issuecomment-387186188 for more details.

**Comment by mhegazy** [comment]
> Also, in general, I do not know how to come up with workarounds for problems like this, and it is very hard to search for solutions to problems in the type-system because everything we talk about is so abstract. Does anybody know any way of searching for stuff like this, or any documentation of workarounds which people might need to use during day-to-day development?

I hope there are not that many of these issues that need workrounds on day-to-day basis. 

If you just have a question on how something can/should be done, StackOverflow is the right place. if you believe it is a compiler bug, or a language limitation feel free to post your issues on this forum. Try to search for similar issues first, but we can always help find related issues as well.
