### ISSUE TITLE
comment on new line after `return` adds unwanted semicolon

### ISSUE THREAD

**Issue by donnut** [Microsoft/TypeScript#2479]
```typescript
function bar() {
    return /* this is comment */ 5;
}

function foo() {
    return
        // this is comment
        5;
}
```
Results in:
```javascript
function bar() {
    return 5;
}
function foo() {
    return;
    // this is comment
    5;
}
```
After the last return an semicolon is inserted, which is wrong. In the language specs I haven't found a restriction on the use of comments in expressions.
I'm using the master of today

**Comment by nycdotnet** [comment]
This is actually technically correct.  The automatic semicolon insertion "feature" that is built-in to JavaScript actually puts that semicolon there regardless of whether you've typed it.  Calling foo() returns undefined.
