### ISSUE TITLE
Unwanted `Object is possibly 'undefined'`

### ISSUE THREAD

**Issue by leighman** [Microsoft/TypeScript#24794]
**TypeScript Version:**  2.9.1

**Search Terms:**  "possibly undefined"

**Code**

```ts
type Keys1 = "gb" | "za"
type NextKeys1 = Keys1 | "1"

type Keys2 = "gb" | "za"
type NextKeys2 = Keys2

type Manager<CK extends string, NK extends string> = {
  new: Exclude<NK, CK> extends never ? undefined : {
    indices: Array<Exclude<NK, CK>>
  }
}

const user: Manager<Keys1, NextKeys1> = {
  new: {
    indices: ["1"],
  }
}

const post: Manager<Keys2, NextKeys2> = {
  new: undefined
}

const foo = user.new ? user.new.indices : []
const blah = post.new ? post.new.indices : []
```

**Expected behavior:**

This sample is less complicated than the real-world one but shows the same issue. I am iterating over an object of these managers. The `new` field will regularly change between `undefined` and some object. When the `new` property on all managers is `undefined`, I would expect typescript to ignore the error because I am explicitly handling the cases in the ternary (or possibly warn me about dead code).

**Actual behavior:**

Typescript warns that `post.new` is possibly undefined in the true path of the ternary.

**Playground Link:**  

https://fabiandev.github.io/typescript-playground/#JTdCJTIyZWRpdG9yJTIyJTNBJTIydHlwZSUyMEtleXMxJTIwJTNEJTIwJTVDJTIyZ2IlNUMlMjIlMjAlN0MlMjAlNUMlMjJ6YSU1QyUyMiU1Q250eXBlJTIwTmV4dEtleXMxJTIwJTNEJTIwS2V5czElMjAlN0MlMjAlNUMlMjIxJTVDJTIyJTVDbiU1Q250eXBlJTIwS2V5czIlMjAlM0QlMjAlNUMlMjJnYiU1QyUyMiUyMCU3QyUyMCU1QyUyMnphJTVDJTIyJTVDbnR5cGUlMjBOZXh0S2V5czIlMjAlM0QlMjBLZXlzMiU1Q24lNUNudHlwZSUyME1hbmFnZXIlM0NDSyUyMGV4dGVuZHMlMjBzdHJpbmclMkMlMjBOSyUyMGV4dGVuZHMlMjBzdHJpbmclM0UlMjAlM0QlMjAlN0IlNUNuJTIwJTIwbmV3JTNBJTIwRXhjbHVkZSUzQ05LJTJDJTIwQ0slM0UlMjBleHRlbmRzJTIwbmV2ZXIlMjAlM0YlMjB1bmRlZmluZWQlMjAlM0ElMjAlN0IlNUNuJTIwJTIwJTIwJTIwaW5kaWNlcyUzQSUyMEFycmF5JTNDRXhjbHVkZSUzQ05LJTJDJTIwQ0slM0UlM0UlNUNuJTIwJTIwJTdEJTVDbiU3RCU1Q24lNUNuY29uc3QlMjB1c2VyJTNBJTIwTWFuYWdlciUzQ0tleXMxJTJDJTIwTmV4dEtleXMxJTNFJTIwJTNEJTIwJTdCJTVDbiUyMCUyMG5ldyUzQSUyMCU3QiU1Q24lMjAlMjAlMjAlMjBpbmRpY2VzJTNBJTIwJTVCJTVDJTIyMSU1QyUyMiU1RCUyQyU1Q24lMjAlMjAlN0QlNUNuJTdEJTVDbiU1Q25jb25zdCUyMHBvc3QlM0ElMjBNYW5hZ2VyJTNDS2V5czIlMkMlMjBOZXh0S2V5czIlM0UlMjAlM0QlMjAlN0IlNUNuJTIwJTIwbmV3JTNBJTIwdW5kZWZpbmVkJTVDbiU3RCU1Q24lNUNuY29uc3QlMjBmb28lMjAlM0QlMjB1c2VyLm5ldyUyMCUzRiUyMHVzZXIubmV3LmluZGljZXMlMjAlM0ElMjAlNUIlNUQlNUNuY29uc3QlMjBibGFoJTIwJTNEJTIwcG9zdC5uZXclMjAlM0YlMjBwb3N0Lm5ldy5pbmRpY2VzJTIwJTNBJTIwJTVCJTVEJTIyJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmNvbXBpbGVyT3B0aW9ucyUyMiUzQSU3QiUyMm5vSW1wbGljaXRBbnklMjIlM0F0cnVlJTJDJTIyc3RyaWN0TnVsbENoZWNrcyUyMiUzQXRydWUlMkMlMjJub0ltcGxpY2l0UmV0dXJucyUyMiUzQXRydWUlMkMlMjJub0ltcGxpY2l0VGhpcyUyMiUzQXRydWUlMkMlMjJyZW1vdmVDb21tZW50cyUyMiUzQWZhbHNlJTJDJTIyZXhwZXJpbWVudGFsRGVjb3JhdG9ycyUyMiUzQWZhbHNlJTJDJTIyZW1pdERlY29yYXRvck1ldGFkYXRhJTIyJTNBZmFsc2UlMkMlMjJhbGxvd05vblRzRXh0ZW5zaW9ucyUyMiUzQXRydWUlMkMlMjJ0YXJnZXQlMjIlM0ExJTdEJTJDJTIyd2luZG93T3B0aW9ucyUyMiUzQSU3QiUyMmNvbnNvbGUlMjIlM0F0cnVlJTdEJTdEJTdE

**Related Issues:**

**Comment by mhegazy** [comment]
The type of `post.new` is undefined.. since `Exclude<Keys2, NextKeys2>` is `never`. so the compiler does not know how to narrow `undefined` after the check for `psot.new`; there is not other type it can give the property. so it keeps its type `undefined`.
