### ISSUE TITLE
union type object export error when used, but there is no problem when used within the module

### ISSUE THREAD

**Issue by BearGS** [Microsoft/TypeScript#24796]
**TypeScript Version:** 2.9.1

**Code**
```ts
// a.ts
interface Fish {
  swim();
  layEggs();
}

interface Bird {
  fly();
  layEggs();
}

const a: Fish | Bird = {
  layEggs () {},
  swim () {},
}

a.swim() // correct

export default a
```
```ts
// b.ts
import animal from './a'

a.swim() // report error: Property 'swim' does not exist on type 'Fish | Bird'.
```

**Expected behavior:**
it should pass typescript type check

**Actual behavior:**
In `b.ts`, `a.swim()`report error: Property 'swim' does not exist on type 'Fish | Bird'.

**Comment by RyanCavanaugh** [comment]
The call is allowed in `a` because we can tell from flow control analysis that it's currently a `Fish`. That logic doesn't apply from `b`.
