### ISSUE TITLE
Exclude doesn't work with extended generics

### ISSUE THREAD

**Issue by niba** [Microsoft/TypeScript#24791]
**TypeScript Version:**  2.9.1, 3.0.0-dev.20180608

**Search Terms:** 
keyof generics extend exclude
**Code**

```ts
type Omit<T, K> = Pick<T, Exclude<keyof T, K>>;

interface RequiredFields {
    requiredField: string;
    requiredField2: string;
}

// works
interface MyInterface extends RequiredFields { }

type ExcludeTest = Exclude<MyInterface, "">; 
type Fields = Omit<MyInterface, "">;
const test = (props: Fields) => {
    const { requiredField } = props;
}

// doesnt work

const generator = <T extends RequiredFields>() => {
    type ExcludeTest = Exclude<T, "">; // wrong 
    type PickTest = Pick<T, "requiredField">;

    type Fields = Omit<T, "">;
    const tmp = (props: Fields) => {
        const {  } = props; // requiredField doesnt exist
    }
    return tmp;
}
```

**Expected behavior:**

Props in generator should have RequiredFields fields.

**Actual behavior:**

Props are empty.

**Playground Link:**  [Link](https://www.typescriptlang.org/play/#src=type%20Omit%3CT%2C%20K%3E%20%3D%20Pick%3CT%2C%20Exclude%3Ckeyof%20T%2C%20K%3E%3E%3B%0D%0A%0D%0Ainterface%20RequiredFields%20%7B%0D%0A%20%20%20%20requiredField%3A%20string%3B%0D%0A%20%20%20%20requiredField2%3A%20string%3B%0D%0A%7D%0D%0A%0D%0A%2F%2F%20works%0D%0Ainterface%20MyInterface%20extends%20RequiredFields%20%7B%20%7D%0D%0A%0D%0Atype%20ExcludeTest%20%3D%20Exclude%3CMyInterface%2C%20%22%22%3E%3B%20%0D%0Atype%20Fields%20%3D%20Omit%3CMyInterface%2C%20%22%22%3E%3B%0D%0Aconst%20test%20%3D%20(props%3A%20Fields)%20%3D%3E%20%7B%0D%0A%20%20%20%20const%20%7B%20requiredField%20%7D%20%3D%20props%3B%0D%0A%7D%0D%0A%0D%0A%2F%2F%20doesnt%20work%0D%0A%0D%0Aconst%20generator%20%3D%20%3CT%20extends%20RequiredFields%3E()%20%3D%3E%20%7B%0D%0A%20%20%20%20type%20ExcludeTest%20%3D%20Exclude%3CT%2C%20%22%22%3E%3B%20%2F%2F%20wrong%20%0D%0A%20%20%20%20type%20PickTest%20%3D%20Pick%3CT%2C%20%22requiredField%22%3E%3B%0D%0A%0D%0A%20%20%20%20type%20Fields%20%3D%20Omit%3CT%2C%20%22%22%3E%3B%0D%0A%20%20%20%20const%20tmp%20%3D%20(props%3A%20Fields)%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20const%20%7B%20%20%7D%20%3D%20props%3B%20%2F%2F%20requiredField%20doesnt%20exist%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20return%20tmp%3B%0D%0A%7D%0D%0A)
**Related Issues:** 
#21941 #21862. 
The issues are closed but the bug is still here

**Comment by niba** [comment]
Duplicate of #21941 #21862.

**Comment by poseidonCore** [comment]
I get a similar issue with 

```
// A basic record:
class R { 
    s: string;
    n: number;
    b: boolean;
}

// A field definition:
class F<IR extends R = R> { 
    name: keyof IR;
    type: "string" | "number" | "boolean";
}

// A function that operates over a record, taking either a field definition or a field name:
function doThis<IR extends R>(options:{
    fieldName?: string;
    field?: F<IR>
}) { 
    var fieldName: string = options.fieldName || options.field.name; // -> ERROR quoted below.

    //...
}
```
ERROR:
> Type 'string | keyof IR' is not assignable to type 'string'.
  Type 'keyof IR' is not assignable to type 'string'.
    Type 'string | number | symbol' is not assignable to type 'string'.
      Type 'number' is not assignable to type 'string'.

If I allow TS to infer the type of `fieldName`, then it has this type `string | keyof IR`, but this is not an extension of string, which can be shown by trying to use a string method like `fieldName.length`, which gives an error.

This worked fine in TS2.8, but the algorithm for comprehending `keyof` seems to be going awry.

This issue can be circumvented by using 
```
class F<IR extends R = R> { 
    name: Exclude<keyof IR, number | symbol>;
    type: "string" | "number" | "boolean";
}
```
instead, but my worry is that based on the stated new `keyof` algorithm, should I really have to put in that filter given that `keyof IR extends R = R` would normally imply that in this situation, there are only string keys anyway in IR?

I understand that there might be a later class S that extends R and includes keys that are numbers|symbols, and could be used for `IR`, but that does not seem like a practical rational for this algorithm widening.

... Perhaps I am missing something ...

When I put in these `Exclude` circumventions, there seems to be a cascade of knock-on issues throughout my solution. I have had to revert to TS2.8 to avoid this.

Thanks

**Comment by tanglebones** [comment]
I've run into a similar case on `typescript@3.0.0-dev.20180609`:

[Playground Link](https://www.typescriptlang.org/play/#src=function%20bindp%3CT%20extends%20object%2C%20P%20extends%20object%2C%20R%3E(%0D%0A%20%20f%3A%20(T)%20%3D%3E%20R%2C%0D%0A%20%20p%3A%20P%0D%0A)%3A%0D%0A%20%20(q%3A%20Exclude%3CT%2C%20P%3E)%20%3D%3E%20R%20%7B%0D%0A%20%20return%20function%20(q%3A%20Exclude%3CT%2C%20P%3E)%3A%20R%20%7B%0D%0A%20%20%20%20const%20args%3A%20T%20%3D%20%3CT%3E%7B...%3Cobject%3Eq%2C%20...%3Cobject%3Ep%7D%3B%20%2F%2F%20casts%20shouldn't%20be%20required%20here%3F%0D%0A%20%20%20%20return%20f(args)%3B%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Afunction%20f(%7Ba%2C%20b%7D%3A%20%7B%20a%3A%20string%2C%20b%3A%20number%20%7D)%3A%20string%20%7B%0D%0A%20%20return%20a%20%2B%20b%3B%0D%0A%7D%0D%0A%0D%0Aconst%20g%20%3D%20bindp(f%2C%20%7Ba%3A%20%22a%22%7D)%3B%0D%0A%0D%0Aconsole.log(g(%7Bb%3A1%7D))%3B%20%2F%2F%20-%3E%20%22a1%22%0D%0Aconsole.log(g(%7B%7D))%3B%20%2F%2F%20should%20be%20an%20compile%20error%3F%0D%0A)

```
function bindp<T extends object, P extends object, R>(
  f: (T) => R,
  p: P
):
  (q: Exclude<T, P>) => R {
  return function (q: Exclude<T, P>): R {
    const args: T = <T>{...<object>q, ...<object>p}; // casts shouldn't be required here?
    return f(args);
  }
}

function f({a, b}: { a: string, b: number }): string {
  return a + b;
}

const g = bindp(f, {a: "a"});

console.log(g({b:1})); // -> "a1"
console.log(g({})); // should be an compile error?

```

**Comment by mhegazy** [comment]
Seems to be the same as https://github.com/Microsoft/TypeScript/issues/22137 and should be addressed by https://github.com/Microsoft/TypeScript/pull/22348

**Comment by MastroLindus** [comment]
I have a related case that worked perfectly in typescript 3.1 (or at least wasn't giving errors), and stopped working from typescript 3.2 onwards (including latest 3.4 beta).
This is an example for a higher order function that takes a React component as input, and returns a component that take the same props as the first one, minus a few props that get injected from the React context.

`type ContextProps = {contextProp1: string, contextProp2: string};

type GetOutputProps<T extends Partial<ContextProps>> = Pick<T, Exclude<keyof T, keyof ContextProps>>;

export function contextPropInjector<InputProps extends Partial<ContextProps>>(Component: React.ComponentType<InputProps>): React.ComponentType<GetOutputProps<InputProps>> {
  return (props: GetOutputProps<InputProps>) => <myContext.Consumer>
    {(contextProps: ContextProps) => <Component {...props} {...contextProps} />}
  </myContext.Consumer>;
}
`

The error is that {...props, ...contextProps} is not assignable to InputProps, when it should be.
I use Partial in the example, but it still doesn't work when using the non-partial type.

**Comment by jack-williams** [comment]
@tanglebones You need to write your example like this:
```ts
type Omit<T, K> = Pick<T, Exclude<keyof T, K>>;

function bindp<T extends P, P extends object, R>(
  f: (arg: T) => R,
  p: P
):
  (q: Omit<T,keyof P>) => R {
  return function (q: Omit<T,keyof P>): R {
    const args: T = <T>{...q, ...p};
    return f(args);
  }
}
```

**Comment by weswigham** [comment]
![fixgif](https://user-images.githubusercontent.com/2932786/54390521-e8052700-465f-11e9-8a8a-1d28949ea843.gif)

Issue described by the OP seems to be fixed - we did update generic mapped type constraints to be more correct a bit ago.
