### ISSUE TITLE
No errors, if a function returns wrong `Partial`.

### ISSUE THREAD

**Issue by RubaXa** [Microsoft/TypeScript#24795]
**TypeScript Version:**  2.9.1-insiders.20180525
**Search Terms:** function retrurns Partial
**Code**

```ts
type Data = {
    name: string
    value: string;
}

function test(fn: () => Partial<Data>) {
}

 // (1) Correct behavior  
const obj: Partial<Data> = {
    name: 'foo',
    unknownProp: 'ok',     //     <--- Type is not assignable to type 'Partial<Data>'
};

// (2) Correct behavior
test(() => ({
    unknownProp: 'ok',     //     <--- Type is not assignable to type 'Partial<Data>'
}));

// (3) Incorrect behavior (!!!)
test(() => ({
    name: 'foo',
    unknownProp: 'wrong',  //     <--- No errors
}));
```

**Expected behavior:**
In 3rd example must be the error: `Type { name: string; unknownProp: string; } is not assignable to type 'Partial<Data>'`

**Actual behavior:**
No errors

**Playground Link:** http://www.typescriptlang.org/play/#src=type%20Data%20%3D%20%7B%0D%0A%20%20%20%20name%3A%20string%0D%0A%20%20%20%20value%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Afunction%20test(fn%3A%20()%20%3D%3E%20Partial%3CData%3E)%20%7B%0D%0A%7D%0D%0A%0D%0A%20%2F%2F%20(1)%20Correct%20behavior%20%20%0D%0Aconst%20obj%3A%20Partial%3CData%3E%20%3D%20%7B%0D%0A%20%20%20%20name%3A%20'foo'%2C%0D%0A%20%20%20%20unknownProp%3A%20'ok'%2C%20%2F%2F%20Error%3A%20Type%20is%20not%20assignable%20to%20type%20'Partial%3CData%3E'%0D%0A%7D%3B%0D%0A%0D%0A%2F%2F%20(2)%20Correct%20behavior%0D%0Atest(()%20%3D%3E%20(%7B%0D%0A%20%20%20%20unknownProp%3A%20'ok'%2C%20%2F%2F%20Error%3A%20Type%20is%20not%20assignable%20to%20type%20'Partial%3CData%3E'%0D%0A%7D))%3B%0D%0A%0D%0A%2F%2F%20(3)%20Incorrect%20behavior%20(!!!)%0D%0Atest(()%20%3D%3E%20(%7B%0D%0A%20%20%20%20name%3A%20'foo'%2C%0D%0A%20%20%20%20unknownProp%3A%20'wrong'%2C%20%2F%2F%20No%20errors%0D%0A%7D))%3B%0D%0A

**Comment by MartinJohns** [comment]
The behaviour is as intended. The return-type of your fat-arrow function is inferred because you don't specify a return type yourself. So the return type is `{ name: string, unknownProp: string }`. The result of that function call is then passed to your `test` method and it asserts if the types are compatible.

You could fix this by being explicit with the return type of your fat-arrow function: `(): Partial<Data> => ({ ... })`.

A good rule-of-thumb is to always explicitly annotating the type when creating an object literal.

**Comment by RubaXa** [comment]
@MartinJohns :( It's very sad and more like the bug than the feature, especially given the case number 2.

**Comment by RubaXa** [comment]
Just describing types is not an option, it's easier for me to refactor code to like this:
```ts
type Data = {
    name: string
    value: string;
}

function test(fn: (apply: (patch: Partial<Data>) => void) => void) { /* ... */}

// (2) Correct behavior
test((apply) => apply({
    unknownProp: 'ok',
}));

// (3) Correct behavior [FIXED]
test((apply) => apply({
    name: 'foo',
    unknownProp: 'wrong',
}));
```
