### ISSUE TITLE
Cannot redeclare type in global module

### ISSUE THREAD

**Issue by cevek** [Microsoft/TypeScript#24793]
**TypeScript Version:**   2.9.1

**Code**

```ts
//a.ts
export const a = {a: 1};
declare global {
   type glob = typeof a; // Duplicate identifier
}
//b.ts
export const b = {b: 1};
declare global {
   type glob = typeof b; // Duplicate identifier
}
```
But this code works with interfaces 
```ts
//a.ts
export const a = {a: 1};
declare global {
   interface glob { a: number }
}
//b.ts
export const b = {b: 1};
declare global {
   interface glob { b: number }
}
```

**Expected behavior:**
No error

**Actual behavior:**
Duplicate identifier error

**Comment by mhegazy** [comment]
Interfaces merge, i.e. they are open ended and merging is additive. type aliases are closed, so they do not merge. 

https://github.com/Microsoft/TypeScript/issues/21913 tracks allowing re-declaration of identical type aliases.
