### ISSUE TITLE
An arrow function with no arguments should not be assignable to a function type that takes arguments

### ISSUE THREAD

**Issue by bogdan-zaharia-hs** [Microsoft/TypeScript#24792]
**TypeScript Version:**  3.0.0-dev.20180608

**Search Terms:** arrow functions, no arguments, not assignable

**Code**

```ts
type MyFn = (a: number) => boolean;
const fn: MyFn = () => true;
```

**Expected behavior:**
The `fn` declaration should yield a compile error, because it does not take any argument, and it must take a `number` (which is not optional).

**Actual behavior:**
The code compiles.

**Playground Link:**  
[TypeScript Playground link](https://www.typescriptlang.org/play/#src=type%20MyFn%20%3D%20(a%3A%20number)%20%3D%3E%20boolean%3B%0D%0Aconst%20fn%3A%20MyFn%20%3D%20()%20%3D%3E%20true%3B%0D%0A
)
**Related Issues:** 
None that I found.

**Comment by kitsonk** [comment]
This is covered in the FAQ [Why are functions with fewer parameters assignable to functions that take more parameters?](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-functions-with-fewer-parameters-assignable-to-functions-that-take-more-parameters)

**Comment by bogdan-zaharia-hs** [comment]
> This is covered in the FAQ

Thanks for the answer, I didn't find it before (should have also searched for "parameters").

**Comment by RyanCavanaugh** [comment]
It's also in the **Common "Bugs" That Aren't Bugs** list
