### ISSUE TITLE
Way to tell TS that a JavaScript variable really is used somewhere

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#24790]
From https://github.com/Microsoft/vscode/issues/51405

**Feature request**
For JavaScript, add a way to mark that a variable that appears unused is used somewhere. For example it may be used within a template that TS cannot analyze

 Not sure if `@ts-ignore` should suppress unused too. It currently has no effect:

<img width="257" alt="screen shot 2018-06-08 at 1 39 49 am" src="https://user-images.githubusercontent.com/12821956/41148064-e0799e64-6abc-11e8-89ba-c2e1500beea5.png">

**Comment by parzh** [comment]
@andy-ms What about AngularJS? There are cases when you have a variable in the controller, which is used indirectly in the scope:

```html
<!-- my-thing.component.html -->
<div>{{ $ctrl.property }}</div>
```

```ts
// my-thing.component.ts
class MyThing {
  public property = 42; // marked as unused, but is really used in the view
}
```

**Comment by andy-ms** [comment]
@parzh Are you sure there isn't some other tool marking that as unused? TypeScript should never mark anything public as unused.

**Comment by parzh** [comment]
@andy-ms Oh, I actually didn't test it. Sorry for the confusion 😔
I just meant that there are cases where it might actually be useful to indicate explicitly that a locally scoped entity is used, even if it appears as unused. A lot of those are related to frameworks with view separated from controller (like AngularJS), but unfortunately  I gave a bad example.

**Comment by andy-ms** [comment]
As far as I can tell, there's no case where unused detection has a false positive (other than something erroneously marked `private`) -- let me know if you find a counterexample.
