### ISSUE TITLE
Removing '@noLib' in fourslash test makes diagnostics disappear

### ISSUE THREAD

**Issue by andy-ms** [microsoft/TypeScript#24806]
**TypeScript Version:** master

**Code**

See `codeFixUnusedIdentifier_deleteWrite.ts` (as of #24805) and remove `// @noLib: true`.

**Expected behavior:**

Test still passes.

**Actual behavior:**

Test fails, because the call to `program.getSemanticDiagnostics` in `eachDiagnostic` returns nothing.

**Comment by jakebailey** [comment]
This test oddity was fixed in #36808.
