### ISSUE TITLE
Your thoughts on deno?

### ISSUE THREAD

**Issue by borekb** [microsoft/TypeScript#24804]
Ok, it's Friday, hopefully a bit of OT is acceptable :)

I just watched [this fascinating talk by Ryan Dahl](https://www.youtube.com/watch?v=M3BM9TB-8yA), the original creator of Node.js, on 10 things he regrets about Node.js. He also discusses [deno](https://github.com/ry/deno/), "a secure TypeScript runtime on V8" prototype.

Some quotes I found interesting:

- "Inside the V8 itself, you have the TypeScript compiler, built into this whole executable." [19m45s](https://youtu.be/M3BM9TB-8yA?t=19m45s)
- "I love TypeScript. It is the best thing." [19m53s](https://youtu.be/M3BM9TB-8yA?t=19m53s)
- "I want this thing [deno] to do TypeScript, because I like it." [20m53s](https://youtu.be/M3BM9TB-8yA?t=20m53s)
- "At the moment, its startup time is quite slow, it's like at one second which is completely unacceptable. However, I'm working on using V8 snapshots to snapshot the entire compiler, and plus other optimizations, and I'm fairly confident that it can be improved greatly." [22m47s](https://youtu.be/M3BM9TB-8yA?t=22m47s)

I'm not at all technical enough to understand everything he's doing inside V8 but it sure sounds exciting. What do you guys think?

**Comment by DanielRosenwasser** [comment]
We were pretty happy to hear that Ryan likes TypeScript, especially since he's been such a huge part of the JavaScript community. We've recently been in touch with him to hear some more about the direction, but we think it's exciting to see where deno goes since there's a lot of space for innovation. Wherever it does end up, we'd be happy to see how we can help 😄.

**Comment by dmayerdesign** [comment]
I am SO psyched about deno, and hearing Dahl say he loves TypeScript was super validating to me as a TS lover. I'm super curious to see how deno might influence the future of TypeScript (e.g. will there ever be a future in which TS compiles directly to bytecode?).

**Comment by aphix** [comment]
FWIW, Deno has decided to remove all TypeScript for internal code: https://github.com/denoland/deno/pull/4750

**Comment by lbguilherme** [comment]
@aphix From the document you linked:

>Update June 10 2020:  I saw that this design doc was being discussed more widely. Most people don't have the context to understand this narrow technical document - it is only applicable to a very particular, very technical situation in the internals of Deno. This is not at all a reflection on the usefulness of TypeScript in general. It's not a discussion about any publicly visible interface in Deno. Deno, of course, will support TypeScript forever. A website or server written in TypeScript is a very very different type of program than Deno - maybe much more so than novice programmers can appreciate - little of Deno is written in TypeScript. The target audience is the 5 to 10 people who work on this particular internal system. Please don't draw any broader conclusions.
