### ISSUE TITLE
VSCode thinks there are 2 definitions of a React Component

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#24809]
_From @mdo5004 on June 8, 2018 14:47_

VSCode thinks there are 2 definitions of a React Component

This issue was brought up recently but without sufficient info. Here is a minimal reproduction example:

- VSCode Version: 1.24.0
- OS Version: MacOS High Sierra 10.13.4 (17E202)

Steps to Reproduce:

1. Create a React app
```bash
$ create-react-app my-bug-example
$ code my-bug-example
```
2. Change src/App.js to 

```
import React, { Component } from 'react';

class App extends Component {
  render() {
    return (
      <div className="App">
      <MyComponent />
      </div>
    );
  }
}

export default App;

class MyComponent extends Component {
  render(){
    return <MySingleComponent text="Instance 1" />
  }
}

class MySingleComponent extends Component {
  render(){
    return <p>{text}</p>
  }
}

```
3. CMD + hover on `<MySingleComponent text="Instance 1" />`

<img width="518" alt="screen shot 2018-06-08 at 10 33 09 am" src="https://user-images.githubusercontent.com/12416969/41164179-88c8ed18-6b08-11e8-9619-8e1f5d093f59.png">

4. CMD + click on `<MySingleComponent text="Instance 1" />`

<img width="471" alt="screen shot 2018-06-08 at 10 33 26 am" src="https://user-images.githubusercontent.com/12416969/41164182-8b65331a-6b08-11e8-98ab-975f5e18e2ff.png">

Does this issue occur when all extensions are disabled?: **Yes**

_Copied from original issue: Microsoft/vscode#51459_

**Comment by mjbvz** [comment]
_From @vscodebot[bot] on June 8, 2018 14:47_

(Experimental duplicate detection)
Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
- [See current component in react (#29017)](https://www.github.com/Microsoft/vscode/issues/29017) 
- [where i can find react component example (#51051)](https://www.github.com/Microsoft/vscode/issues/51051)

**Comment by mjbvz** [comment]
Tested on 3.0 20180608

The incorrect definition is coming from our automatically acquired types for react:

<img width="765" alt="screen shot 2018-06-08 at 1 29 49 pm" src="https://user-images.githubusercontent.com/12821956/41179595-112a66b6-6b20-11e8-8b5d-7174ca97c4d5.png">

**Comment by slsriehl** [comment]
I'm getting something similar working on Nodejs, and it appears to affect **all anonymous functions in JavaScript**, ES5 or arrow, whether imported or not.

VSCode: 1.24.0

OS: MacOS High Sierra 10.13.5

Still broken with all extensions & preferences disabled: **yes**

Here's the imported object/method:

...cases.js
`const objects = {
    reduceVersion: (foo, bar) => {
        return ...
     }
}

module.exports = objects;`

**Case 1: Require just this method**

...one.js
`
const reduceVersion = require('../../../transforms/models/read/cases').reduceVersion;

const operation = (req, res) => {
    ...
   let version = reduceVersion(...);
}
`
cmd + hover says "Click to show 2 definitions".

cmd + click on the call "reduceVersion" in function "operation" gives the 2 definitions error on the const assigned to the import & shows the two versions as the import expression & the definition imported:

![screen shot 2018-06-11 at 4 07 09 pm](https://user-images.githubusercontent.com/15839167/41257251-c99efe50-6d91-11e8-8897-4e74835e6021.png)



**Case 2: Require the whole method object and call method with dot notation**

...one.js
`
const readCases = require('../../../transforms/models/read/cases');

const operation = (req, res) => {
    ...
   let version = readCases.reduceVersion(...);
}
`

cmd + hover says "Click to show 2 definitions".

cmd + click on the call "cases.reduceVersion" in function "operation" gives the 2 definitions error at the key holding the definition (no duplicate key exists):

![screen shot 2018-06-11 at 4 10 51 pm](https://user-images.githubusercontent.com/15839167/41257353-26e402e0-6d92-11e8-8a48-e1af5ace525c.png)



**Case 3: Define anonymous function (arrow OR ES5) assigned to a variable without import (with let, const, or var)**

`
const reduceVersion = (foo, bar) => {
    return foo;
}

//OR

var reduceVersion = function (foo, bar) {
   return foo;
}

//...etc

const operation = (req, res) => {
    ...
   let version = reduceVersion(...);
}
`

cmd + hover says "Click to show 2 definitions".

cmd + click:

![screen shot 2018-06-11 at 4 29 24 pm](https://user-images.githubusercontent.com/15839167/41258107-b2f4ae5e-6d94-11e8-93d5-3feeefa1fe33.png)


**Case 4:  ES5 named function (WORKS)**

`
function reduceVersion(foo, bar) {
    return foo;
}

const operation = (req, res) => {
    ...
   let version = reduceVersion(...);
}
`

cmd + hover doesn't say 2 definitions

cmd + click jumps to definition

**Comment by mhegazy** [comment]
@andy-ms does #24995 address this issue?

**Comment by andy-ms** [comment]
No, but the fix is related. #25382

**Comment by daweilv** [comment]
Does it fixed? Which ts version should I download? @andy-ms 
I've just try to download `npm install -g typescript@3.0.0-rc`,`typescript@3.0.1-insiders.20180713` 
 and `typescript@next`, neither of them work.

**Comment by daweilv** [comment]
Sorry , It does work! I changed VS Code default ts path with my own. [via](https://stackoverflow.com/questions/39668731/what-typescript-version-is-visual-studio-code-using-how-to-update-it).
Thank you so much!🎉🎉🎉

**Comment by davnicwil** [comment]
This appears to still happen, **latest** TS `3.6.3`, **latest** VSCode `1.38.1`

Quick repro, create a new `tsx` file with this content:

```
import React from 'react'

const Thing: React.FC<{ text: string }> = (props) => <div>{props.text}</div>

const HelloWorld = () => <Thing text="hello world" />
```

When I cmd+click on `<Thing` I expect the cursor to go to the definition `const Thing`

Instead, this happens:

![image](https://user-images.githubusercontent.com/9915841/65244423-65639580-dae2-11e9-84d8-7d735f55df9c.png)

Basically the definitions seems to want to go to the type def for `React.FC` from `node_modules/@types/react`. 

I never, under any circumstance, want this behaviour when cmd clicking the JSX component. I want to go to the definition of that component. If I want to go to the type def, I'll cmd+click on `React.FC`

Is this behaviour intentional, or is it a bug? Can it be configured? Will it be changed in future so it can be?

Please if you have a minute, just a simple no, no, no answer would be fine. Just want to know as it's a source of frustration for ages using VSCode with react & typescript and if it won't go away, I'd rather just know rather than always googling to see how to fix it :-)

**Comment by gaspard** [comment]
Still happening here with TS 3.5.3, using React.FC....

Sample code...

```ts
export const Transport: React.FunctionComponent<TransportProps> = ({}) => {
}
```

In another jsx file:

```html
<Transport />
```

![image](https://user-images.githubusercontent.com/21707/66643500-1f9c7780-ec1f-11e9-9ccd-d23b7ac0aa97.png)

**Comment by rotero** [comment]
Also still happening on NodeJS on latest version of VSCode (1.39.2) on Mac (10.14.6). Examples not only as mentioned by slsriehl but also happening using Object.prototype function annotation

**Comment by mz8i** [comment]
Happening to me too in relation to a component of type React.FunctionalComponent - VSCode thinks there are two definitions upon ctrl-clicking `<Foo />` and uses Peek Definition instead of Go To File, which is definitely undesirable in this case.
VSCode 1.39.2 on Ubuntu 19.04.

**Comment by or2008** [comment]
have the same issue with React.FC,
@davnicwil  did you manage to fix that? maybe it is a good idea to open a new issue?

**Comment by davnicwil** [comment]
@or2008 No, still not fixed.

I think this one should just be re-opened to be honest. The thread has context and it seems the problem described originally is still present (or was perhaps re-introduced?) despite it being closed.

**Comment by agos** [comment]
had the same happen today with 3.7.4. For other people using Visual Studio code and not liking the change, a workaround is to change two settings: Editor › Goto Location: Multiple Definitions (`editor.gotoLocation.multipleDefinitions`) and Editor › Goto Location: Multiple Type Definitions (`editor.gotoLocation.multipleTypeDefinitions`), setting both of them to `'goto'`

**Comment by RyanCavanaugh** [comment]
I'm going to leave this closed. Please open a new issue with a concrete way to reproduce the issue and we'll be happy to take a look. Thanks!

**Comment by davnicwil** [comment]
@RyanCavanaugh amazing, thanks - will [this comment](https://github.com/microsoft/TypeScript/issues/24809#issuecomment-533112361) suffice if I just copy/paste it to a new issue?

It'd be so great to get this looked at & fixed! I'm actually pretty surprised there isn't more noise about this one as it's honestly pretty annoying pretty often if you're using React + TS + VSCode

**Comment by moshfeu** [comment]
This issue is still happening in

```
Version: 1.43.2
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:34:57.037Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0
```

**Comment by davnicwil** [comment]
@RyanCavanaugh ☝️ I've created a new issue for this with a concrete way to reproduce, as requested. Cheers.
