### ISSUE TITLE
TypeScript 2.9.x incorrectly emits relative imports for symbolically linked dependencies (lerna)

### ISSUE THREAD

**Issue by raymondfeng** [Microsoft/TypeScript#24829]
**TypeScript Version:**  2.9.x

2.8.x works fine. It starts to break with TypeScript 2.9.x. It's not fixed by the latest build (typescript@next).

**Search Terms:** 

import symbolic link lerna

**Code**

https://github.com/strongloop/loopback-next/blob/master/packages/core/src/keys.ts

**keys.ts**
```ts
import {Application, ControllerClass} from './application';

export const CONTROLLER_CLASS = BindingKey.create<ControllerClass>(
    'controller.current.ctor',
  );
```
Please note the `ControllerClass` is a type alias re-exported from another module `@loopback/next` which is symbolically linked to `@loopback/core` by `lerna`.

**application.ts**
```ts
import {Context, Binding, BindingScope, Constructor} from '@loopback/context';
export type ControllerClass = Constructor<any>;
```

**Expected behavior:**

TypeScript 2.8.x style:
**keys.d.ts** (emitted by tsc)
```ts
const CONTROLLER_CLASS: BindingKey<new (...args: any[]) => any>;
```
Or

```ts
import {Constructor} from '@loopback/context';

const CONTROLLER_CLASS: BindingKey<Constructor<any>>;
```

**Actual behavior:**

```ts
const CONTROLLER_CLASS: BindingKey<import("../../context/src/value-promise").Constructor<any>>;
```

Please note the relative link is only valid at development time. Once it's published as a npm module, the `import` cannot be resolved.

**Playground Link:**  

**Related Issues:** 

https://github.com/strongloop/loopback-next/issues/1405

**Comment by ajafff** [comment]
This is also a problem for me when using the new feature to adjust imports after renaming a file.

**Comment by mhegazy** [comment]
@weswigham can you take a look

**Comment by raymondfeng** [comment]
I just tried 2.9.2 release and the issue is NOT fixed but getting worse:

See https://github.com/Microsoft/TypeScript/pull/24874#issuecomment-397075614

**Comment by alan-agius4** [comment]
Is there update on this? I see that it has been merged but with TS 2.9.2 I still have the same issue

**Comment by lukaszczernal** [comment]
I understand that Typescript 2 will not be fixed. We should all update to third version. Right?

**Comment by weswigham** [comment]
Our team only maintainsmonce version of the compiler actively, so yes.
