### ISSUE TITLE
Commit completions on punctuation not working

### ISSUE THREAD

**Issue by danquirk** [Microsoft/TypeScript#2482]
With CTP6 we're not getting completion results committed via period, parens, etc. Not sure when/how this regressed.

**Comment by paulvanbrenk** [comment]
This still works in the RTM branch, not sure why/how/if this regressed in CTP6, but I don't think we can do anything for CTP6 at this point.

**Comment by danquirk** [comment]
Do we have a test somewhere to ensure it doesn't regress again?

**Comment by paulvanbrenk** [comment]
This works as expected in 1.5
