### ISSUE TITLE
Extended Numeric Literals

### ISSUE THREAD

**Issue by MaxGraey** [microsoft/TypeScript#24828]
## Search Terms
- extended-numeric-literals
- extended numeric literals

## Suggestion

Support [tc39/proposal-extended-numeric-literals (Stage 1)](https://github.com/tc39/proposal-extended-numeric-literals)

## Use Cases
For represent lengths in pixels, inches, degrees, radians, seconds and other units without calling specifically conversion methods in runtime (if this possible).
```ts
const time = 100s // transforms to `100,000` ms
const angle = 180° // transforms to `3.1415926536` radians
```

## Examples
```ts
function deg(value: number): number {
   return value * (Math.PI / 180);
}

function °(value: number): number {
   return deg(value);
}

function _f32(value: number): number {
  return Math.fround(value);
}

function _u32(value: number): number {
  return value >>> 0;
}

function px(value: number): string {
  return `${ value }px`;
}

var angle = 30deg; // transforms to `0.5235987756`
const angle2 = 180°; // transforms to `pi` (`3.1415926536`)
let count = 1_000_000_u32;
var float32 = 1.0_f32;
canvas.style.width = 512px; // transforms to "512px" string
```

Also related to #15096

**Comment by Shinigami92** [comment]
I think that would be a great feature, but also that it could cause confusion for newbies who would read code from teammates

**Comment by Kingwl** [comment]
I don't think this will reach stage-3 in the near future (3-5 years) 
~and it is ugliness~

**Comment by MaxGraey** [comment]
This is already used with the arrival of __BigInt__. And with success has taken hold in such modern languages ​​as like Rust, Ruby, Swift

**Comment by Shinigami92** [comment]
@MaxGraey So I think that this feature is related to Javascript, not Typescript

**Comment by MaxGraey** [comment]
If this will land in JavaScript it should support by Typescript as well, isn't it? String templating has been pretty useful feature. Extended numeric literals just like templating but for numbers

**Comment by Shinigami92** [comment]
> If this will land in JavaScript it should support by Typescript as well, isn't it?

@MaxGraey Yes it is

**Comment by RyanCavanaugh** [comment]
Closing since there's nothing for us to do but wait for TC39
