### ISSUE TITLE
Property-based nominal types by private/protected modifier are a problem especially with package API exposing

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#24822]
We can't get structural compatibility from the separate packages when private/protected modifier is used. We should remove it or provide a workaround.

cc @ahejlsberg 

related: #202

**Comment by mhegazy** [comment]
That is what private properties are.. they are nominal. if your package supports multiple versions interacting together, then it should not have `private` members on its public API, instead it should expose a set of interfaces.
