### ISSUE TITLE
VS Code prompt error `not exist attribute` use vue tsx

### ISSUE THREAD

**Issue by JJJYY** [Microsoft/TypeScript#24830]
![error tips](https://user-images.githubusercontent.com/32628989/41193911-09258ef6-6c46-11e8-8ff7-19becccd6685.jpg)

VS Code ts version `2.9.1`

this error means `type "..." not exist attribute "element"`

when I change ts version to `2.8.4`(my workspace version), the error disappear

I change ts version to `next`, has error too.  

so, what's the problem? VS Code, ts or my mistake

Thanks for your time!

**Comment by DanielRosenwasser** [comment]
Could you give a complete and self-contained reproduction of the issue you're running into? It'll be hard to diagnose the problem otherwise.
