### ISSUE TITLE
Handbook typo: "emitDeclarationsOnly" should be "emitDeclarationOnly"

### ISSUE THREAD

**Issue by alangpierce** [Microsoft/TypeScript#24837]
The TypeScript 2.8 release notes in the handbook reference a flag called `--emitDeclarationsOnly`: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html

It should actually be `--emitDeclarationOnly`, as documented e.g. here: https://www.typescriptlang.org/docs/handbook/compiler-options.html

**Comment by DanielRosenwasser** [comment]
Fixed at https://github.com/Microsoft/TypeScript-Handbook/commit/9400bf4fba955c2b75fae6b8f223efa6d5b93a19, will be fixed on the next website update.

**Comment by alangpierce** [comment]
Thanks!
