### ISSUE TITLE
error TS2559: Type '{ referrerPolicy: string; }' has no properties in common with type 'DetailedHTMLProps<ImgHTMLAttributes<HTMLImageElement>, HTMLImageElement>'.

### ISSUE THREAD

**Issue by hardfist** [Microsoft/TypeScript#24835]
**TypeScript Version:**  3.0.0-dev.20180609

**Search Terms:** 

**Code**

```ts
function Test() {
  return <img referrerPolicy="never" />;
}

```

**Expected behavior:**

**Actual behavior:**

**Playground Link:**  

**Related Issues:**

**Comment by JJJYY** [comment]
Maybe we have same problem:joy: #24830

**Comment by mhegazy** [comment]
You might have better luck sharing this on StackOverflow. This is not a support forum, it is one for reporting compiler/language bugs and suggestions. 
If you believe you are running into a compiler bug, please share a minimal repro project that demonstrates the issue you are running into and why you believe this is a compiler bug and not a declaration file issue or library usage problem.
