### ISSUE TITLE
Give a better error message for using import() as a type

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#24839]
We fixed #24172 but the error message we give is still not great.

https://twitter.com/yankeeinlondon/status/1005564400697135104?s=19

Adding a suggestion like "Did you mean 'typeof import(...)'?" would be way better.

**Comment by a-tarasyuk** [comment]
@mhegazy Oh, I didn't notice the previous PR which was opened 20 days ago. I'll close my PR.
