### ISSUE TITLE
incorrect type inference in simple statement

### ISSUE THREAD

**Issue by cancerberoSgx** [Microsoft/TypeScript#24831]
```typescript
const something = Date.now() === 0 ? 'a string' : undefined
```
Expected behavior:  `something` inferred apparent type should be `'a string' | undefined`

Actual behavior:  `something` inferred apparent type is `'a string'`

I'm able to reproduce this in latest / master version of TypeScript. Also in 2.9.1

Here is a working example:

https://www.typescriptlang.org/play/#src=const%20something%20%3D%20Date.now()%20%3D%3D%3D%200%20%3F%20'a%20string'%20%3A%20undefined%0D%0Aconsole.log(something)%3B

I tried to help TypeScript by putting parenthesis around expressions but that won't help.

Also notice that `Date.now()` declaration is: 
```
now(): number;
```

Note: The problem seems to be with `undefined` since the following works OK:

```typescript
const something = Date.now() === 0 ? 'a string' : 123
```

**Comment by ajafff** [comment]
Do you have strictNullChecks enabled?

**Comment by cancerberoSgx** [comment]
Oh that was it. I'm very sorry for the noise and the confusion. Closing this.
