### ISSUE TITLE
Assign defaults to generic types in lib.d.ts

### ISSUE THREAD

**Issue by andrewlowndes** [microsoft/TypeScript#24834]
## Search Terms

array, generic, default

## Suggestion

Assign a default generic type to built-in types that require generics. More specifically the Array type. 

Modify `lib.d.ts` and change existing definitions that use generics from:
```typescript
interface Array<T> {
...
}
```

To:
```typescript
interface Array<T = any> {
...
}
```

## Use Cases

Will allow people more flexibility with how much type information they want to provide in their project and to more easily and loosely match high level types without validating child types.

## Examples

Can then do the following without needing to care about the generic type:
```typescript
type ArrayKeys = keyof Array;
```

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by DanielRosenwasser** [comment]
I'm not so sure `Array` buys you a lot over `any[]` - but I could certainly see savings in `Map` or `Set`. The problem is that once you're really authoring in TypeScript, I don't think you ever *want* this sort of behavior if you leave off the type arguments. So how does a user *avoid* this when they forget type arguments?

**Comment by mhegazy** [comment]
We have discussed this in the past, and felt that if you, in a type position, take the type to write `Array`, you might as well tell us what type it is, or just use `Array<any>`.

**Comment by andrewlowndes** [comment]
I wanted to make this suggestion to set the convention for always defaulting generic types where a default can be defined. Is the general feel that strict typing should always be preferred?

**Comment by mhegazy** [comment]
These types are not inferred. these types that are explicitly specified. so why would some one take the time to write `Array` for type safety vs than the implicit `any`, but yet they do not want to write what is the element type..

**Comment by mhegazy** [comment]
on the flip side, if this is allowed, users will feel compelled to have a lint rule that says you can not specify `Array` without a type.. 
I believe having these options that make users needing to choose a way among multiple equivalents (similar to semicolon or no semicolon, const vs let, etc..) is a language designer mistake.

**Comment by RyanCavanaugh** [comment]
There doesn't seem to be much user demand for this, and we'd certainly upset a lot of people who didn't like infectious `any`s creeping in. Splitting the lib by option is very problematic so I don't think we'll be taking this up.
