### ISSUE TITLE
Inconsistent use of import()-type in signature help

### ISSUE THREAD

**Issue by ajafff** [Microsoft/TypeScript#24848]
**TypeScript Version:**  3.0.0-dev.20180609

**Search Terms:** import type

**Code**

```ts
import {getWrappedNodeAtPosition} from 'tsutils';
getWrappedNodeAtPosition(/*1*/
```

**Expected behavior:**

Expected the following signature help, because it used to to show that in previous versions.

```ts
getWrappedNodeAtPosition(wrap: NodeWrap, pos: number): NodeWrap | undefined
```

Otherwise I would expect the use of the `import()`-type to be consistent and to also be used in the return type.

**Actual behavior:**

After typing the opening paren (at `/*1*/`), the following signature help is shown:

```ts
getWrappedNodeAtPosition(wrap: import("/Users/klaus/code/wotan/node_modules/tsutils/util/convert-ast").NodeWrap, pos: number): NodeWrap | undefined
```
**Playground Link:**  

**Related Issues:**

**Comment by mhegazy** [comment]
@weswigham, i thought we are not using import types at all in signature help/quick info..

**Comment by weswigham** [comment]
Y'know, I thought so, too, but looks like nope:
![image](https://user-images.githubusercontent.com/2932786/41260236-73ffd48e-6d8b-11e8-94df-cbe2d35d5e7b.png)
It's missing the `UseAliasDefinedOutsideCurrentScope` flag.

Will have a change up in a jiffy.
