### ISSUE TITLE
Default import syntax doesn't work, but { default as } does.

### ISSUE THREAD

**Issue by rdsedmundo** [Microsoft/TypeScript#24847]
Hello, look at the following please:

This results in a compile error:
```ts
import API from 'apifn';

// TS2351: Cannot use 'new' with an expression whose type lacks a call or construct signature.
export default new API('https://google.com', []);
```

This works:
```ts
import { default as API } from 'apifn';

export default new API('https://google.com', []);
```

Both `allowSyntheticDefaultImports` and  `esModuleInterop` are set to true here.

I can't understand how those syntaxes are different, as I believe the default import syntax is part of the TC39 standard already or isn't it? Asking because this works perfectly with Babel. Only when I'm with projects with TypeScript that this confusion with `default` starts to happen.

The `apifn` package is a small package developed by myself. It uses TypeScript for generating ES5+Common JS.

**Related Issues:** #21621 (I originally posted there, but it was informed that they aren't related)

**Comment by Kovensky** [comment]
This sounds like the problem and workaround I identified in https://github.com/Microsoft/TypeScript/issues/24528#issuecomment-393738210. Maybe it's fixed in @next.

**Comment by rdsedmundo** [comment]
Indeed they look related. I'll try with the `@next` version and let you know the results.

**Comment by rdsedmundo** [comment]
Yes, it's fixed by `typescript@next`.

Thank you.
