### ISSUE TITLE
javascript bug about object literals

### ISSUE THREAD

**Issue by xp44mm** [Microsoft/TypeScript#24849]
i find  that run the next code will throw error: 
```javascript
let a = { b }
```
the error is:
```
Uncaught ReferenceError: b is not defined
```
i think that the prevous code equals to:
```javascript
let a = { 'b':b }
```
just only `undefined` next to point sign `.` it throw error:
```
Uncaught TypeError: Cannot read property 'xx' of undefined
```
calling `undefined` itself don't thow any error. so instead throw error, the `a` should equal to:
```javascript
a === {'b':undefined}
```

do you agree with me?

**Comment by andy-ms** [comment]
If you didn't define `b`, it's valid to get a ReferenceError when trying to access `b`. Since that's the normal behavior of JavaScript, it's not a TypeScript bug.

**Comment by RyanCavanaugh** [comment]
Also please follow the template
