### ISSUE TITLE
Support simple check in `if` for discriminated unions with `true`/`false` discriminant

### ISSUE THREAD

**Issue by WiseBird** [Microsoft/TypeScript#24843]
## Search Terms

discriminated true false if

## Use Cases

Having discriminated union with `true`/`false` discriminant:
```
interface Square {
    kind: true;
    size: number;
}
interface Rectangle {
    kind: false;
    width: number;
    height: number;
}

type Shape = Square | Rectangle;
```

we can treat them differently using verbose comparison in `if`:
```
let s: Shape = null;

if (s.kind === true) {
    console.log(s.size);
} else {
    console.log(s.height);
}
```

With simple check:
```
let s: Shape = null;

if (s.kind) {
    console.log(s.size);
} else {
    console.log(s.height);
}
```
ts doesn't recognize `Rectangle` in `else` branch: `Property 'height' does not exist on type 'Square'`

## Examples

Would be nice to be able to do simple `if(s.kind)` check.

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by MartinJohns** [comment]
This works already if you enable `strictNullChecks`. If you don't enable `strictNullChecks`, then you need to explicitly check for `false` in your `else` block (aka `else if (s.kind === false)`, because the value can be `undefined` and `null` too.

**Comment by WiseBird** [comment]
But this former check works without `strictNullChecks`:
```
if (s.kind === true) {
    console.log(s.size);
} else {
    console.log(s.height);
}
```
here too in `else` the value can be `undefined` or `null`.

**Comment by DanielRosenwasser** [comment]
I think this is a duplicate of #10564.

**Comment by WiseBird** [comment]
Duplicate
