### ISSUE TITLE
Bug in enum comparison inside block

### ISSUE THREAD

**Issue by jcziviani** [Microsoft/TypeScript#24844]
There is a compiler error in the following code:

```Typescript

enum TokenTypes
{
    Symbol,
    Comma
}

class Tokenizer
{
    tokenType:TokenTypes = TokenTypes.Symbol;
    
    getNextToken()
    {
           this.tokenType = TokenTypes.Comma;
    }

    methodWithError()
    {
        if (this.tokenType != TokenTypes.Symbol)
        {
            return;
        }
        this.getNextToken();

        // bug in the next line
        // error message: "Operator '==' cannot be applied to types 'TokenTypes.Symbol' and 'TokenTypes.Comma'.
        if (this.tokenType == TokenTypes.Comma ) 
        {
            // do something
        }
    }
}
```
This error is happening probably because compiler "thinks" that `tokenizer.tokenType` still is `TokenTypes.Symbol` in the code after return. But the line `this.getNextToken();` changes the token type, so there is an evaluation error in the compiler.

**Comment by RyanCavanaugh** [comment]
Duplicate #9998

**Comment by jcziviani** [comment]
Not being "pessimistic" and not allowing an object modifying is own state, is dumb IMHO. 
I was converting a code from C#, that allows this common sense behavior as almost all mainstream programming languages. Anyway, I changed to code to not use this. Thanks.
