### ISSUE TITLE
Incorrect indexed type display (any)

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/TypeScript#24842]
This is simple DeepPick implementation, type works (shows erros) but displayes incorrect type `{a: any}`, while it should something like `{a: {b: {d: string}}}`

![image](https://user-images.githubusercontent.com/736697/41201649-d7b7b59e-6cd4-11e8-8c0c-b4d06d45d822.png)

```ts
type Obj = {
  a: {
    c: {
      x: string
      y: string
    },
    b: {
      e: string,
      d: string
    }
  },
  b: {
    c: string
  }
}


type DeepPick<T extends { [K in string | symbol | number]: any }, M > =
  M extends 1
  ? T
  : { [P in keyof M]: DeepPick<T[P], M[P]> }




type X = DeepPick<Obj, { a: { b: { d: 1 } } }>

const x: X = {  
  b: {c: '1'},
  a: {
    b: {
      d: 'x'
    }
  }
}
```

TS 2.9.1

**Comment by mhegazy** [comment]
As you noted, this is a display only issue. the type is resolved correctly. mapped type inferences are deferred to handle recursive types. when the compiler is displaying the properties of a type that has been inferred from a mapped type, it does not know how far to go, it is possibly infinite, so it uses `any`.

**Comment by whitecolor** [comment]
Ok, I get it it think.
