### ISSUE TITLE
Wrong documentation displayed in tooltip for union of interface and function in VSCode

### ISSUE THREAD

**Issue by Duckers** [microsoft/TypeScript#24841]
A common pattern in my code is to have an interface with a name `Foo` and a function `Foo` to construct an object that matches interface. Due to this bug its hard for the user to see the right documentation when consuming these entities.

**TypeScript Version:**  2.8.1 (as this is a bug that only manifests in the IDE, I'm not sure how to test on latest dev version)

**Search Terms:** "intellisense", "interface and function", "wrong documentation"

**Code**

```ts
/** This is documentation for the function */
function Foo(): Foo {
    return { foo: "foo" }
}

/** This is documentation for the interface */
interface Foo {
    foo: "foo"
}

const f: Foo = Foo()
```

**Expected behavior:** When hovering `: Foo` in VSCode, I expect to see the documentation for the interface.

**Actual behavior:** The documentation for the function is displayed.

**Playground Link:**  

**Related Issues:**

**Comment by j-oliveras** [comment]
I tested with versions `2.9.1` and `3.0.0-dev.20180609` and I can reproduce the issue with both.

@Duckers [Use dev builds](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Nightly%20Builds.md).

**Comment by mhegazy** [comment]
PRs welcomed. we will need to filter the documentation on declarations based on the meaning of the reference node.

**Comment by Duckers** [comment]
As a lot of libraries (including mine) now probably have a bug-dependency here (as I keep moving docs that should be on the interface, to the function), for backwards compatibility we should probably display the function docs when no interface docs is available. Alternatively, always display a union of the docs, similar to how it shows a union of the entities.

**Comment by Duckers** [comment]
On second thought;

When using the pattern of having an `interface Foo` and a `function Foo` to construct an object that matches the interface, the docs for those two entities are usually very interconnected. If they are treated as completely separate entities, we tend to end up having to duplicate information between them. 

Hence, displaying a union (e.g. docs for both entities) is probably the most pragmatic solution as it allows us to specify information in one place, and have it displayed in all relevant contexts.

**Comment by RyanCavanaugh** [comment]
We now show both as requested
