### ISSUE TITLE
Regression of arrow function in async function

### ISSUE THREAD

**Issue by chinesedfan** [Microsoft/TypeScript#24858]
**TypeScript Version:** 
2.9.1

**Search Terms:** 
arrow function, async function, this binding

**Code**

```ts
async function f() {
    let a, b;
    [a, b] = await f2();

    const f3 = () => {
        this.x = 3;
    };
}

function f2() {
    return [1, 2];
}
```

**Expected behavior:**

`_this` is existed in the closure, like compiled by ts@2.8.1,

```
function f() {
    return __awaiter(this, void 0, void 0, function () {
        var _this = this;
        var a, b, f3, _a;
        return __generator(this, function (_b) {
            switch (_b.label) {
                case 0: return [4 /*yield*/, f2()];
                case 1:
                    _a = _b.sent(), a = _a[0], b = _a[1];
                    f3 = function () {
                        _this.x = 3;
                    };
                    return [2 /*return*/];
            }
        });
    });
}
```

**Actual behavior:**

`_this` is only existed in `case 0`.

```
function f() {
    return __awaiter(this, void 0, void 0, function () {
        var _a, a, b, f3;
        return __generator(this, function (_b) {
            switch (_b.label) {
                case 0:
                    var _this = this;
                    return [4 /*yield*/, f2()];
                case 1:
                    _a = _b.sent(), a = _a[0], b = _a[1];
                    f3 = function () {
                        _this.x = 3;
                    };
                    return [2 /*return*/];
            }
        });
    });
}
```

**Playground Link:**  

[Click me](https://www.typescriptlang.org/play/index.html#src=async%20function%20f()%20%7B%0D%0A%20%20%20%20let%20a%2C%20b%3B%0D%0A%20%20%20%20%5Ba%2C%20b%5D%20%3D%20await%20f2()%3B%0D%0A%0D%0A%20%20%20%20const%20f3%20%3D%20()%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20this.x%20%3D%203%3B%0D%0A%20%20%20%20%7D%3B%0D%0A%7D%0D%0A%0D%0Afunction%20f2()%20%7B%0D%0A%20%20%20%20return%20%5B1%2C%202%5D%3B%0D%0A%7D).

**Related Issues:** 

None.

**Comment by andy-ms** [comment]
May have been fixed by #24768 -- could you try with `typescript@next`?

**Comment by mhegazy** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/24722. Fix should be in `typescript@next` today, and in `typescript@2.9.2` in a few days.

**Comment by chinesedfan** [comment]
Solved by ts@next. Thanks!
