### ISSUE TITLE
We need a typescript interpreter

### ISSUE THREAD

**Issue by DricHao** [Microsoft/TypeScript#24855]
We need an interpreter or engine that natively supports ts

**Comment by j-oliveras** [comment]
Something like [Deno](https://github.com/ry/deno)?

**Comment by DricHao** [comment]
@j-oliveras no,when deno is running, in addition to starting a v8,and you need to start a TS compiler.Escape ts to js.So, we need a natively supported TS engine to avoid that.sorry for my english

**Comment by anurbol** [comment]
@DricHao you are looking for https://github.com/TypeStrong/ts-node

**Comment by RyanCavanaugh** [comment]
Hard to believe it, but it's been proposed before #10380

**Comment by DricHao** [comment]
@anurbol oh thank you guy!

**Comment by mcarbonneaux** [comment]
We need typescript support directly in browser to avoid the need to compile typescript in js before use....

**Comment by anurbol** [comment]
@mcarbonneaux we'd need a time machine for that, I guess :)

**Comment by mcarbonneaux** [comment]
why not ? why developp this type of language and not integrate it in browser ? why not update Chakra engine to support typescript ?

**Comment by leonidax** [comment]
I also agree that typescript should eventually replace JavaScript
