### ISSUE TITLE
Assertion refines to `never` when not intended

### ISSUE THREAD

**Issue by jeffijoe** [Microsoft/TypeScript#24853]
**TypeScript Version:**  2.9.1

**Search Terms:** type refinement assertion

**Code**

```ts
export interface Type {
    name: string;
}

export interface FunctionParameter {
    name: string;
    type: Type;
}

export interface FunctionType extends Type {
    functionName: string;
    returnType: Type;
    parameters: Array<FunctionParameter>;
}

export interface ListType extends Type {
    elementType: Type;
}

export interface TypeDefinition extends Type {
    type: Type;
}

export interface ShapeType extends Type {
    propertySignatures: Map<string, PropertySignature>;
}

export interface PropertySignature {
    name: string;
    type: Type;
    optional: boolean;
    readonly: boolean;
}

export interface TypeReference extends Type {
}

export interface OptionalType extends Type {
    type: Type;
}

export declare const isListType: (ty: Type | null) => ty is ListType;
export declare const isFunctionType: (ty: Type | null) => ty is FunctionType;
export declare const isShapeType: (ty: Type | null) => ty is ShapeType;
export declare const isOptionalType: (ty: Type | null) => ty is OptionalType;
export declare const isTypeReference: (ty: Type | null) => ty is TypeReference;
export declare const isTypeDefinition: (ty: Type | null) => ty is TypeDefinition;

export function getDefaultValueForType(
  type: Type | undefined | null
): any {
  if (!type) {
    return null
  }


  if (isTypeReference(type)) {
    return getDefaultValueForType(type)
  }

  if (isTypeDefinition(type)) {
    return getDefaultValueForType(type)
  }

  if (isListType(type)) {
    return []
  }

  if (isShapeType(type)) {
    const result: any = {}
    type.propertySignatures.forEach(prop => {
      result[prop.name] = getDefaultValueForType(prop.type)
    })
    return result
  }

  return null
}
```

**Expected behavior:**

It should type check and refine the `type` correctly.

**Actual behavior:**

`type` gets refined to `never`.

**Playground Link:** https://www.typescriptlang.org/play/index.html#src=export%20interface%20Type%20%7B%0D%0A%20%20%20%20name%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Aexport%20interface%20FunctionParameter%20%7B%0D%0A%20%20%20%20name%3A%20string%3B%0D%0A%20%20%20%20type%3A%20Type%3B%0D%0A%7D%0D%0A%0D%0Aexport%20interface%20FunctionType%20extends%20Type%20%7B%0D%0A%20%20%20%20functionName%3A%20string%3B%0D%0A%20%20%20%20returnType%3A%20Type%3B%0D%0A%20%20%20%20parameters%3A%20Array%3CFunctionParameter%3E%3B%0D%0A%7D%0D%0A%0D%0Aexport%20interface%20ListType%20extends%20Type%20%7B%0D%0A%20%20%20%20elementType%3A%20Type%3B%0D%0A%7D%0D%0A%0D%0Aexport%20interface%20TypeDefinition%20extends%20Type%20%7B%0D%0A%20%20%20%20type%3A%20Type%3B%0D%0A%7D%0D%0A%0D%0Aexport%20interface%20ShapeType%20extends%20Type%20%7B%0D%0A%20%20%20%20propertySignatures%3A%20Map%3Cstring%2C%20PropertySignature%3E%3B%0D%0A%7D%0D%0A%0D%0Aexport%20interface%20PropertySignature%20%7B%0D%0A%20%20%20%20name%3A%20string%3B%0D%0A%20%20%20%20type%3A%20Type%3B%0D%0A%20%20%20%20optional%3A%20boolean%3B%0D%0A%20%20%20%20readonly%3A%20boolean%3B%0D%0A%7D%0D%0A%0D%0Aexport%20interface%20TypeReference%20extends%20Type%20%7B%0D%0A%7D%0D%0A%0D%0Aexport%20interface%20OptionalType%20extends%20Type%20%7B%0D%0A%20%20%20%20type%3A%20Type%3B%0D%0A%7D%0D%0A%0D%0Aexport%20declare%20const%20isListType%3A%20(ty%3A%20Type%20%7C%20null)%20%3D%3E%20ty%20is%20ListType%3B%0D%0Aexport%20declare%20const%20isFunctionType%3A%20(ty%3A%20Type%20%7C%20null)%20%3D%3E%20ty%20is%20FunctionType%3B%0D%0Aexport%20declare%20const%20isShapeType%3A%20(ty%3A%20Type%20%7C%20null)%20%3D%3E%20ty%20is%20ShapeType%3B%0D%0Aexport%20declare%20const%20isOptionalType%3A%20(ty%3A%20Type%20%7C%20null)%20%3D%3E%20ty%20is%20OptionalType%3B%0D%0Aexport%20declare%20const%20isTypeReference%3A%20(ty%3A%20Type%20%7C%20null)%20%3D%3E%20ty%20is%20TypeReference%3B%0D%0Aexport%20declare%20const%20isTypeDefinition%3A%20(ty%3A%20Type%20%7C%20null)%20%3D%3E%20ty%20is%20TypeDefinition%3B%0D%0A%0D%0Aexport%20function%20getDefaultValueForType(%0D%0A%20%20type%3A%20Type%20%7C%20undefined%20%7C%20null%0D%0A)%3A%20any%20%7B%0D%0A%20%20if%20(!type)%20%7B%0D%0A%20%20%20%20return%20null%0D%0A%20%20%7D%0D%0A%0D%0A%0D%0A%20%20if%20(isTypeReference(type))%20%7B%0D%0A%20%20%20%20return%20getDefaultValueForType(type)%0D%0A%20%20%7D%0D%0A%0D%0A%20%20if%20(isTypeDefinition(type))%20%7B%0D%0A%20%20%20%20return%20getDefaultValueForType(type)%0D%0A%20%20%7D%0D%0A%0D%0A%20%20if%20(isListType(type))%20%7B%0D%0A%20%20%20%20return%20%5B%5D%0D%0A%20%20%7D%0D%0A%0D%0A%20%20if%20(isShapeType(type))%20%7B%0D%0A%20%20%20%20const%20result%3A%20any%20%3D%20%7B%7D%0D%0A%20%20%20%20type.propertySignatures.forEach(prop%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20result%5Bprop.name%5D%20%3D%20getDefaultValueForType(prop.type)%0D%0A%20%20%20%20%7D)%0D%0A%20%20%20%20return%20result%0D%0A%20%20%7D%0D%0A%0D%0A%20%20return%20null%0D%0A%7D%0D%0A

**Comment by MartinJohns** [comment]
The interface `TypeReference` is absolutely equal to `Type`, because it does not provide any property. So when the TypeScript compiler encounters a type-guard that checks for `TypeReference`, it automatically is also a type-guard for `Type` - as those two types are identically.

So after the `if (isTypeDefinition(type)) { return ...; }` check the only logical conclusion is `never`.

Don't have empty interfaces in TypeScript. :-)

**Comment by jeffijoe** [comment]
Oooooh, yeah that does actually make sense! However I did remove a few props for brevity, and `Type` has a `flags` field which determines what it actually is, despite it now having more properties. The `is` functions checks those flags. Guess I just need to reorder my checks.

Not sure if this is something the TS team wants to revisit, so I'll leave it up to them to determine if this should be closed or not. 😄
