### ISSUE TITLE
getNavigationBarItems for entire project

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#2486]
i.e for the entire program, not just a single file. Is there such a function already?

**Comment by mhegazy** [comment]
getNavigateToItems with no searchValue should give you something closer. this is what we use in VS for Ctrl+, to find named declarations throughout the project. 

if you want to show something like class hierarchy, or something a la VS progression view, then you need to add a new function that does something similar to getNavigateToItems more than getNaviagationBarItems. I think we would be interested in taking a feature like this in the LS interface, assuming this is what you have in mind.

A distinction to make is that getNaviagationBarItems is purely syntactic and operates on a file level, if you want to do some sort of aggregation of global hierarchy, you want to do something along the lines of getNavigateToItems that would walk the global symbol table, and drill in from there.

let us know what you have in mind, also pinging @CyrusNajmabadi for this issue.

**Comment by basarat** [comment]
Cool. NavigateToItems is probably what I was looking for. I'm not concerned about a global hierarchy ❤️

**Comment by CyrusNajmabadi** [comment]
I'm not exactly sure what you're asking for.  Can you help explain what purpose this would serve?  How would this feature manifest itself to the user?

Thanks!

**Comment by basarat** [comment]
> getNavigateToItems with no searchValue should give you something closer. 

It give me an empty array : `[]`

`var items = languageService.getNavigateToItems('');`

**Comment by CyrusNajmabadi** [comment]
What are you trying to accomplish?  Thanks.

**Comment by basarat** [comment]
conversation continued in #2500
