### ISSUE TITLE
Goto-definition combined with .d.ts.map file produces location past the end of the file

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#24866]
**TypeScript Version:**  master

**Code**

See the test "tsserverProjectSystem project references" "goToDefinition" added in #24867.

CC @weswigham

**Comment by andy-ms** [comment]
That's the sourcemap that `tsc` generated when I tried it out. Would be nice if there were a way to programatically generate `a.d.ts` and `a.d.ts.map` inside the test instead of hardcoding.

**Comment by weswigham** [comment]
There is! Some of the declaration map tests make use of it.

**Comment by weswigham** [comment]
I'm going to hazard a guess that #24886 fixed this.

**Comment by andy-ms** [comment]
Since we're using the feature now, you can reproduce the error by clicking on any `skipTrivia` in `textChanges.ts`.

**Comment by weswigham** [comment]
> I'm going to hazard a guess that #24886 fixed this.

And we haven't done an lkg but only use light to build, so the change can't be seen in our own project yet.

**Comment by andy-ms** [comment]
Hi @weswigham, could you provide the location of the test helper that will generate a map?

**Comment by weswigham** [comment]
[This fourslash test does it](https://github.com/Microsoft/TypeScript/pull/22658/files#diff-e5786acfc5596fa6bf5617c9cd8bd204)

**Comment by andy-ms** [comment]
@weswigham Updated #24867 but it looks like the declaration emit hasn't changed in the master branch. Also, while working on that I've noticed that goto-definition doesn't always go to the right file either -- for example, in `tsserverProjectSystem.ts`, clicking on `ProjectService` in `server.ProjectService` takes me to `scriptVersionCache.ts` instead of `editorServices.ts`.

**Comment by weswigham** [comment]
@andy-ms So it's worth noting that while we "fixed" your test, it's still entirely possible for us to return a position outside the bounds of a file for the end of a span we return (though probably much less likely now, since every identifier is actually sourcemapped). Do we need to guard against that anywhere?

**Comment by andy-ms** [comment]
We do call `scriptInfo.positionToLineOffset` on the result, but I don't see any asserts in there -- so we'll just return an out-of-bounds location to the editor, which should be able to handle it without crashing.
