### ISSUE TITLE
"Generate 'get' and 'set' accessors" refactor triggers on whitespace

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#24880]
**TypeScript Version:**  3.0.0-dev.20180609

**Code**

```ts
class A {
    p = 0;
}
```

Highlight any space between `{` and `p`.

**Expected behavior:**

No refactor.

**Actual behavior:**

Refactor is suggested.

Note `refactorConvertToGetAccessAndSetAccess35.ts` was meant to test for this, but `verify.not.refactorAvailable();` without a name provided will always pass because it compares refactor names to `undefined`.

**Comment by mhegazy** [comment]
@Kingwl wanna take on this one?

**Comment by andy-ms** [comment]
I've added a `verity.refactorsAvailable` function in #24878 which asserts the list of names of refactors available, rather than asserting that a particular name isn't present (which would trivially pass if you mistyped the name)

**Comment by Kingwl** [comment]
sorry about that, my deadline is coming and i have not enough time to handle that
