### ISSUE TITLE
Go-to-definition on declarations in `session.ts` jumps to `breakpoints.ts`

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#24884]
Using the latest of `master`:

1. Open up `src/server/session.ts`
2. Go to definition on `getSignatureHelpItems`

**Expected**: Jumps to `src/services/services.ts` or `src/services/signatureHelp.ts`
**Actual**: Jumps to `src/services/breakpoints.ts`

**Comment by weswigham** [comment]
Fixed by #24886
