### ISSUE TITLE
Override interfaces by declaration files to omit unexpected nominal types

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#24885]
In the following case, A and B should have the same type. So they don't have any nominal type.

```ts
// lib.d.ts
export class A {
  m
}
export class B {
  m
}
// lib.ts
export class A {
  private a
  m
}
export class B {
  private b
  m
}
// index.ts
import { A, B } from './lib';

const o: A = new B(); // should make no error
```

resolve: #24822
related: #202

**Comment by mhegazy** [comment]
how is this issue different from https://github.com/Microsoft/TypeScript/issues/24822?

**Comment by mhegazy** [comment]
Also two files with `lib.d.ts` and `lib.ts` already means that the compiler picks `lib.ts` and ignores `lib.d.ts`.

**Comment by falsandtru** [comment]
#24822 is a general problem presentation about unexpected nominal types. This issue works as an actual solution for unexpected nominal types.

I mean the compiler uses `lib.ts` for code emitting and uses `lib.d.ts` for type checking. So `lib.ts` will be ignored in type checking. Besides, the compiler should also validate the types of them.

**Comment by mhegazy** [comment]
> I mean the compiler uses lib.ts for code emitting and uses lib.d.ts for type checking.

that is not how it works.

**Comment by falsandtru** [comment]
I'm not sure what you want. can you show me an example?

**Comment by mhegazy** [comment]
I am saying this is not how the compiler thinks of files today. a file is a self contained entity, not a container of partial declarations that is augmented by another file with the same name.. 

The point goes back to nominal types are nominal. i.e. they are assignable only from themselves, and nothing else.. adding a `private` or `protected` property to a class makes it nominal. if that is not what you want, and you allow your API users to pass you structurally equivalent objects that did not originate from the same declaration, then `private` or `protected` are not needed. if however you have implementation details that are encoded in your private properties, then it is not safe to allow a structural comparison between your class instances, and regular objects..
