### ISSUE TITLE
Types of property 'render' are incompatible.

### ISSUE THREAD

**Issue by cutoz** [Microsoft/TypeScript#24898]
Hey, so I am using ReactQuill as a component, but I am facing this error while using Typescript. Any suggestions for mitigation 

JSX element type 'ReactQuill' is not a constructor function for JSX elements.
  Types of property 'render' are incompatible.
    Type '() => ReactNode' is not assignable to type '{ (): false | Element | null; (): ReactNode; }'.
      Type 'ReactNode' is not assignable to type 'false | Element | null'.
        Type 'undefined' is not assignable to type 'false | Element | null'.

**Comment by mhegazy** [comment]
You might have better luck sharing this on StackOverflow. This is not a support forum, it is one for reporting compiler/language bugs and suggestions. 
If you believe you are running into a compiler bug, please share a minimal repro project that demonstrates the issue you are running into and why you believe this is a compiler bug and not a declaration file issue or library usage problem.
