### ISSUE TITLE
Samples licensing

### ISSUE THREAD

**Issue by JeWaVe** [Microsoft/TypeScript#24899]
[Typescript samples from playground](http://www.typescriptlang.org/play/index.html) don't expose any license.txt

Are they considered public domain, or do they have the same license (apache) as the entire typescript compiler?

**Comment by mhegazy** [comment]
The website and its samples are not open sourced at the moment.

https://github.com/Microsoft/TypeScriptSamples should be available under Apache 2.0. so are the samples available under https://github.com/Microsoft/TypeScript-Handbook

**Comment by JeWaVe** [comment]
Ok. In the meantime, how (if possible) can I use the ray tracing sample (migrated to c#) as an example on how to migrate c# code to GPU using our (third party) product?

**Comment by mhegazy** [comment]
One option is to add a PR to https://github.com/Microsoft/TypeScriptSamples with the sample from the playground, thus incorporating it under the project licence. then you can use it from there.
