### ISSUE TITLE
Should unused detection mark variables only used in other unused functions as unused? 

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#24894]
From https://github.com/Microsoft/vscode/issues/51460#issuecomment-396331433

**TypeScript Version:**  3.0.0-dev.20180608

**Search Terms:** 
- Unused

**Code**
Look at the unused variables for the code:

```ts
export const _ = 1;

function a() { }

function b() { a() }
```

**Expected behavior:**
Both `a` and `b` are unused since `a` is only used from `b`

**Actual behavior:**
Only `b` is explicitly marked as unused.

**Comment by mhegazy** [comment]
A textbook implementation of dead code analysis requires repeating until reaching a fixed point where no more dead code is found. this is unfortunately hard to implement in the current system. we can easily detect the first level of unused names though.

**Comment by parzh** [comment]
@mjbvz IMO, in the given snippet, `a` is correctly considered being used by `b`. And `b` is indeed unused. So it is okay (to me) to have such "levels" of unused entities, when you have to delete unused declarations several times in a row.
