### ISSUE TITLE
Support folder rename in getEditsForFileRename

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#24904]
Renaming a folder should cause a rename to all files in the project that are part of the folder.

**Comment by mjbvz** [comment]
@mhegazy Has this been pushed back from 2.9.2, or this bug tracking a different feature?

**Comment by mhegazy** [comment]
there are two parts, 1. changing the folder part of the a file name, that should be working in 2.9.2, but you are still expected to send a file name to the server, 2. sending a folder name directly to the server and the server changing all the files included (that is what this issue is tracking).

**Comment by mjbvz** [comment]
Ok. That makes sense. Thank you for the clarification

I'll make sure VS Code is ready for the 2.9.2 part of this

**Comment by andy-ms** [comment]
Fixed by #25052
