### ISSUE TITLE
tsconfig.json purpose?

### ISSUE THREAD

**Issue by ToddThomson** [Microsoft/TypeScript#2492]
Question: tsconfig.json appears to be a reasonable way to specify a compilation context. Why isn't it available from the command line? ( tsc -c tsconfig.json ). I would like to be able to use tsconfig.json within a build system ( gulp based ) rather than it be a build system.

**Comment by mhegazy** [comment]
On the command line you can run:
> tsc -p <Directory path of tsconfig.json>

or just call tsc with no file arguments in a directory with tsconfig.json in it
> tsc

you can configure your build systems to call tsc with -p. @ivogabe might be able to help you better here.

**Comment by ToddThomson** [comment]
Thank-you.
And thank-you to the team!
