### ISSUE TITLE
Recusive/Nested type capturing using generic types, stop with 'any', when generating .d.ts or vscode display

### ISSUE THREAD

**Issue by wesleyolis** [Microsoft/TypeScript#24928]
**TypeScript Version:**  typescript@next

Type recursion engine fails to continue intersect types, just returns any, seem to give up.
This has been confirm by checkout the output generated in a .d.ts file.
The compiler in a single compiler instance is able to validate the typings recursively and correctly it doesn't fall over.

Suspect the same function for generating a friendly vscode type display version is being used for .d.ts file generation as well. Would always prefer the long versions in vscode type display hints always, you will see the benefits soon..
**Code**

```ts

export interface Base {
    nest() : this;
}

export interface Wrapper<T> {
    nest<T>(obj : T) : this & {extract : T}
}

export const wrapper = <T>(value: T) => ({}) as Wrapper<T>

export const nesting = {
    a : wrapper(1).nest({
        b : wrapper('2').nest({
            c: wrapper(3).nest({
                d: wrapper('4').nest({
                    e: wrapper(5).nest({
                        f: wrapper('6')
                    })
                })
            })
        })
    })
}


type nestingType = typeof nesting
```

**Expected behavior:**

```ts
export declare const wrapper: <T>(value: T) => Wrapper<T>;
export declare const nesting: {
    a: Wrapper<number> & {
        extract: {
            b: Wrapper<string> & {
                extract : {
                    c : Wrapper<number> & {
                        extract : {
                            d : Wrapper<string> & {
                                extract : {
                                    e : Wrapper<number> & {
                                        extract : {
                                            f : Wrapper<string>
                                        };
                                    };
                                };
                            };
                        };
                    };
                };
            };
        };
    };
};
```

**Actual behavior:**
```ts
export declare const wrapper: <T>(value: T) => Wrapper<T>;
export declare const nesting: {
    a: Wrapper<number> & {
        extract: {
            b: Wrapper<string> & any;
        };
    };
};
```

**Comment by mhegazy** [comment]
The compiler does not know how to serialize infinite types. Note that types can not be known ahead of types if they are recursive or not.. type relationships proceed in an on-demand fashion. So the type serialize keeps a stack of seen types to avoid running into infinite loops, and it cuts the loop with the use of `any`. your type looks a lot like an infinite recursive type, though it is not.
 
> Suspect the same function for generating a friendly vscode type display version is being used for .d.ts file generation as well. 

this is correct.

**Comment by wesleyolis** [comment]
@mhegazy Even if I am going to have to fix it myself!
You really don't understand the power that this unleashes!! If we had to share our work with you!
The only down fall is that d.ts file, should exhaust the type definition, otherwise the typing become useless in other projects.

As I understand d.ts serialize uses use the same function as for vscode would, which is the problem.
"Suspect the same function for generating a friendly vscode type display version is being used for .d.ts file generation as well. this is correct."

This really is a simplified example to demonstrate the problem. Typically it cuts the the loop as you call it, even if the recursion is not a unique tree, in our eyes, the type structures are definitely not running into itself again. If what you say is true, then if I were to intersect a unique identifier into this example, the behavior should change. I do that to morrow with this same simplistic example to demonstrate the problem.

When you say that the type serialize keeps a stack of seen types to avoid running into infinite loops and it cuts the loop with the use of any..  How many other places does this happen, were types can be cut?
is their any design documentation and architectural documentation for the compiler, that I can get myself upto speed with the inner works and technical side of things. As if I were to read ISO specification for C/C++.

Would you be able to point me to the correct file, relative path, were I should find the code responsible for this functionality? I have a local copy of the ts compiler source, I would like to take a look at it.
Then one other questions, which path to scratch into for internal workings of typing system AST processing for intersections and unions and compound operators for void, never, any..

**Comment by mhegazy** [comment]
> is their any design documentation and architectural documentation for the compiler, that I can get myself upto speed with the inner works and technical side of things. 

Please see https://github.com/Microsoft/TypeScript/wiki/Architectural-Overview and https://github.com/Microsoft/TypeScript/wiki/Contributing-to-TypeScript

> Would you be able to point me to the correct file, relative path, were I should find the code responsible for this functionality?

This is not a "bug" that we are looking for a PR to fix. the compiler is behaving as designed. it is just happens to be a limitation to our design approach at the time being.

**Comment by wesleyolis** [comment]
This is probably not a bad thing to work against: https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#3

**Comment by wesleyolis** [comment]
Thanx, Will start going thought the documents., I have a couple of additional ideas around literals and enhanced validation, I would like to look at implementing. Then also for the purposes of what I think I called EventSource programming language structures for UI, with little framework ontop. Trying to find my document on it..

**Comment by wesleyolis** [comment]
@mhegazy If you understanding were this is going, then probably a good thing for you to check out this as well, because its also venturing down this path, probably reveal the bigger picture of use cases.

[https://github.com/Microsoft/TypeScript/issues/24517](https://github.com/Microsoft/TypeScript/issues/24517)

[https://github.com/Microsoft/TypeScript/issues/24852](https://github.com/Microsoft/TypeScript/issues/24852)
