### ISSUE TITLE
Property 'permissions' does not exist on type 'Navigator'

### ISSUE THREAD

**Issue by dwekat** [Microsoft/TypeScript#24923]
**TypeScript Version:** 
2.7.2

**Search Terms:** 
Property 'permissions' does not exist on type 'Navigator'

**Code**

```ts
const perm = navigator.permissions;
    perm.query({name: 'geolocation'})
      .then(permissionStatus => {
        console.log('geolocation permission state is ', permissionStatus.state);
        permissionStatus.onchange = () => {
          console.log('geolocation permission state has changed');
        };
      });
```

**Expected behavior:**
`navigator.permissions` should be defined
**Actual behavior:**
`navigator.permissions` does not exist.

**Playground Link:**  
https://goo.gl/5ckgwD

**Related Issues:** 
#16246

**Comment by jwalton** [comment]
`npm install --save-dev @types/w3c-permissions`, for those looking for a work-around.

**Comment by saschanaz** [comment]
Recently the TS team have merged several draft-status web features into lib.d.ts because future migration to lib.d.ts from DefinitelyTyped packages can be annoying. Read more at https://github.com/Microsoft/TypeScript/issues/18480#issuecomment-341202123 for the previous discussion.

In this case, IMO it can be added to lib.d.ts as the official spec exists and two major vendors provide their implementations.

**Comment by vargavince91** [comment]
We also created types for the `permissions` API and submitted to [`DefinitelyTyped`](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/navigator-permissions) repository. We used the [MDN Permissions](https://developer.mozilla.org/en-US/docs/Web/API/Permissions) page to add documentation using TSDoc. You can check the [examples](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/navigator-permissions/navigator-permissions-tests.ts), if not clear how it works

You can check it on [`npm`](https://www.npmjs.com/package/@types/navigator-permissions) and install it as dev dependency by:

```
$ npm install --save-dev @types/navigator-permissions
```

Feedback is welcome.

**Comment by romain-faust** [comment]
@vargavince91 very good job !
There is only one thing that I want to point out. As stated [here](https://developer.mozilla.org/en-US/docs/Web/API/Permissions/revoke#Parameters), the `revoke` descriptor does not accept the same names as the `query` one does.

*Query :* `'accelerometer', 'accessibility-events', 'ambient-light-sensor', 'background-sync', 'camera'​, 'clipboard-read', 'clipboard-write', 'geolocation', 'gyroscope', 'magnetometer', 'microphone', 'midi', 'notifications', 'payment-handler', 'persistent-storage', 'push'`

*Revoke :* `'geolocation', 'midi', 'notifications', 'push'`

**Comment by vargavince91** [comment]
Oh thank you for pointing this out, I'm going to submit a merge request today with the fixes

**Comment by bennyn** [comment]
> We also created types for the permissions API and submitted to DefinitelyTyped repository. We used the MDN Permissions page to add documentation using TSDoc.

@vargavince91 Super nice that you wrote types for it! Do you may also have types for [navigator.clipboard](https://developers.google.com/web/updates/2018/03/clipboardapi)?

**Comment by ProtocolNebula** [comment]
I have the same problem, but in some computers (maybe fault of node version) don't recognize the `@types`, so, additionally to that, I casted to any:

```ts
return (navigator as any).permissions.query({
  name: 'geolocation'
}).then((permission) => {
    console.log(permission);
});
```

**Comment by audiolion** [comment]
@saschanaz or @sandersn I see that these types were updated in the generator, but I dont see them in master

https://github.com/Microsoft/TypeScript/blob/9509a54e66034c7ae723051a3c79afaa9084046e/lib/lib.dom.d.ts#L10506

am I looking in the wrong place? have they not been released yet?

**Comment by sandersn** [comment]
@audiolion Take a look in src/lib/dom.generated.d.ts instead. lib/ has the built library files in it, generated by running --LKG if I remember correctly.

**Comment by audiolion** [comment]
@sandersn sorry for the naïveté, but I dont see src/lib/dom.generated.d.ts in this repo, I see it in the TSJS-lib-generator one, I thought it somehow got translated over here by running the generator? hah. I guess my main issue is that using typescript 3.4.5 (current latest), I cant seem to find those new `Navigator.permission` types that were merged into the TSJS repo 28 days ago.

**Comment by dartess** [comment]
for googling: `Navigator.permission` types in `typescript@3.5.3` works fine
