### ISSUE TITLE
 Error: Debug Failure. Unhandled declaration kind! 233

### ISSUE THREAD

**Issue by ssaket** [Microsoft/TypeScript#24924]
I am using gulp to debug the babylonjs project.

**TypeScript Version:** 2.8.4
**Operating system:**  High Sierra 10.12.3
**Node Version**  v8.11.2
**npm Version** 5.6.0

First few lines of stack trace-
 Error: Debug Failure. Unhandled declaration kind! 233
    at getTypeOfVariableOrParameterOrProperty (/Users/***/Projects/Babylon.js/Tools/Gulp/node_modules/typescript/lib/tsc.js:23916:30)
    at getTypeOfSymbol (/Users/**/Projects/Babylon.js/Tools/Gulp/node_modules/typescript/lib/tsc.js:24078:24)
    at checkClassLikeDeclaration (/Users/**/Projects/Babylon.js/Tools/Gulp/node_modules/typescript/lib/tsc.js:38320:30)

Found one similar issue[https://github.com/Microsoft/TypeScript/issues/23194,](url) but it didn't help me.

**Comment by mhegazy** [comment]
Can you share the sources that cause this issue? can you also give it a try using `typescript@next`.

You can also launch the compiler under node inspector, assuming you have node v7 or later

```sh
node --inspect --debug-brk node_modules\typescript\lib\tsc.js --p <path to your tsconfig.json>
```

in chrome go to `chrome://inspect`.  let the process run, when it breaks, there should be `getTypeOfVariableOrParameterOrProperty` on the stack. Look up the value of `ts.getSourceFileOfNode(symbol.valueDeclaration).fileName` in your watch window, this should tell you which file is causing the issue. you can also dump the `diagnostic` object that is the argument of the function.

**Comment by ssaket** [comment]
Hi @mhegazy,  Thanks for the help.
It seems this file is causing the issue 

> /Users/xx/Projects/Babylon.js/src/Debug/babylon.axesViewer.ts (though it's a very small file and I couldn't find anything unusual )

I have attached the diagnostic object dump (couldn't convert it to json because of it's circular nature), in case any reference is needed. 

How should I resolve this ? being a newbie, any help in much appreciated :)

[symbol_dumb.txt](https://github.com/Microsoft/TypeScript/files/2101334/symbol_dumb.txt)

**Comment by mhegazy** [comment]
Now that you know the file that is causing the issue, can you build a smaller repro using that file?

**Comment by ssaket** [comment]
like how ? using only that file?

**Comment by mhegazy** [comment]
you probally need more, but the file and its dependents are a good place to start.

**Comment by ssaket** [comment]
I tried to run watch without this file. But it threw an error for the next ts file in the directory `("/Users/saketsaurabh/Projects/Babylon.js/src/Debug/babylon.boneAxesViewer.ts")`
I can be repro by using gulp watch or gulp run, which basically calls -
```js
gulp.task("srcTscWatch", function () {
    // Reuse The TSC CLI from gulp to enable -w.
    process.argv[2] = "-w";
    process.argv[3] = "-p";
    process.argv[4] = "../../src/tsconfig.json";
    require("./node_modules/typescript/lib/tsc.js");
});```

**Comment by ssaket** [comment]
Now I feel it's not the issue with the Babylon files.

**Comment by mhegazy** [comment]
Can you share the project?

**Comment by ssaket** [comment]
[https://github.com/BabylonJS/Babylon.js/](url) - I cloned it from here. 
Build details - [https://github.com/BabylonJS/Babylon.js/blob/master/contributing.md](url)

Thanks again :)

**Comment by mhegazy** [comment]
I ran tsc on https://github.com/BabylonJS/Babylon.js/tree/master/src and so no issues.. what am i missing?

**Comment by mhegazy** [comment]
both for `typesctipt@2.8.4` and `typescript@2.9.2`

**Comment by ssaket** [comment]
Sorry, In my previous comment I said I cloned it, but actually I forked it. A similar issue -https://github.com/Microsoft/TypeScript/issues/23194 to repro error.
