### ISSUE TITLE
[ts] Duplicate function implementation

### ISSUE THREAD

**Issue by dpindusa** [Microsoft/TypeScript#24925]
Steps to Reproduce:
1) Create 1.ts file (Code as mentioned below)
2) Create 2.ts file (Code as mentioned below)
3) Create tsconfig.json using tsc -init. (This step is not mandatory)
4) Observer red underline under the function name 

**VS Code Version:** 1.24.0
**TypeScript Version:**  2.3.4
**OS Version:** Windows 8.1 Enterprise

**Search Terms:** TypeScript Visual Studio Code [ts] Duplicate function implementation

**Code**

```ts
//1.ts File
function test(){
    console.log("File 1 Error");
}

//2.ts File
function test(){
    console.log("File 2 Error");
}
```

**Expected behavior:**

**Actual behavior:**

**Related Issues:** [#10804](https://github.com/Microsoft/TypeScript/issues/10804)
![file1](https://user-images.githubusercontent.com/40237092/41354179-ec021594-6f3b-11e8-8071-75cece7f1acb.jpg)
![file2](https://user-images.githubusercontent.com/40237092/41354189-f192b374-6f3b-11e8-8f3d-f9bd91979b33.jpg)
![error](https://user-images.githubusercontent.com/40237092/41354193-f621f45e-6f3b-11e8-84fd-4d2854edf8bc.jpg)

**Comment by RyanCavanaugh** [comment]
These functions are in the global scope and only one of them can exist at a time.

**Comment by xgqfrms** [comment]
@brikou Thanks a lot!

**Comment by pengtaoa** [comment]
good

**Comment by MuhammadAbdullah54321** [comment]
This gives error in the console that 
"Uncaught ReferenceError: exports is not defined"

**Comment by davschne** [comment]
Well, the suggested solution works _if_ I'm using ES modules, but what about when I'm dealing with CommonJS modules? The same error occurs, but there doesn't appear to be a way to fix it. If I add `export {};` I get `SyntaxError: Unexpected token 'export'` when trying to run the generated JS in Node. My sense is that when using `"module": "commonjs"` in `tsconfig.json`, such checks should be disabled. @RyanCavanaugh, thoughts?
