### ISSUE TITLE
tsc 2.9.1 : doesn't understand /** @typedef { import('./types').Foo } Foo */

### ISSUE THREAD

**Issue by nojvek** [Microsoft/TypeScript#24921]
**TypeScript Version:**  2.9.1

**Search Terms:** typedef import, js import

I really wish there was better documentation around this. Took a lot of random googling and reading to even figure out the weird syntax. How is someone even supposed to import multiple types from same .d.ts file?

I was so hopeful that this would work but after a lot of head bashing I still can't get tsc, js files and .d.ts files to play well together 😢 . Its almost 1am, but something so simple shouldn't be complex, should it?

**Code**

types.d.ts
```js
export interface Foo {
  str: string;
}
```

main.js
```js
  /** @typedef { import('./types').Foo } Foo */

  /**
   * @param {Foo} foo
   */
  function hello(foo) {}
```

tsconfig.json
```
{
  "compilerOptions": {
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "alwaysStrict": false,
    "esModuleInterop": true,
    "lib": ["es2017", "dom"],
    "noFallthroughCasesInSwitch": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "pretty": true,
    "sourceMap": true,
    "types" : ["node"],
    "target": "es6"
  }
}
```

**Expected behavior:**

It correctly understands type `Foo`

**Actual behavior:**

`[ts] cannot find name 'Foo'`

in the typedef it shows a red squiggly and complains about

`[ts] '}' expected.` 
near `import(`

**Comment by AlCalzone** [comment]
Works for me:
![unbenannt](https://user-images.githubusercontent.com/17641229/41349087-084fc5ac-6f0f-11e8-8503-a6caafa99c5a.png)

Are you sure your VSCode is using the correct version of the TS compiler?

**Comment by nojvek** [comment]
So after waking up I seem to have found some new avenues.

1. re-installed typescript on my lib so package.json points to `"typescript": "^2.9.1",`
2. re-installed typescript globally on my machine, realized nvm installed it to `/Users/me/.nvm/versions/node/v8.9.2/lib/node_modules/typescript` rather than `/usr/local/lib/node_modules/typescript`
3. removed  `/usr/local/lib/node_modules` entirely, to stop any command resolution confusion
4. Changed vscode settings to use a custom typescript lib `"typescript.tsdk": "/Users/me/.nvm/versions/node/v8.9.2/lib/node_modules/typescript/lib",`
5. Restart vscode (this was important)

That seems to make everything work nicely 😃. Some failures in importing default lib.d.ts  but that's another issue.

Closing this.
