### ISSUE TITLE
Type guards on bound generic parameters don't compile

### ISSUE THREAD

**Issue by spion** [Microsoft/TypeScript#24935]
Seems like type guards on bound generic parameters don't compile - the compiler doesn't take the constraint into account.

**TypeScript Version:**  2.9

**Search Terms:** 

generic type guard

**Code**

```ts
function isOne<T extends 1 | 2 | 3>(t: T): t is 1 { return t === 1; }
```

**Expected behavior:**

Compiles without errors

**Actual behavior:**

```
A type predicate's type must be assignable to its parameter's type.
  Type '1' is not assignable to type 'T'.
```

**Playground Link:**  

http://www.typescriptlang.org/play/#src=function%20isOne%3CT%20extends%201%20%7C%202%20%7C%203%3E(t%3A%20T)%3A%20t%20is%201%20%7B%20return%20t%20%3D%3D%3D%201%3B%20%7D

**Related Issues:** 

Could not tell

**Comment by RyanCavanaugh** [comment]
What is the intent of `T` here? It's unnecessary

**Comment by spion** [comment]
Here is an example that is slightly less (but still quite) contrived (not the original code, but not a minimal nonsensical test case either):

```typescript

type Widget = { value: number; }
const MyWidget: Widget = { value: 1 }

type Joojoo = { value: string }
const MyJoojoo: Joojoo = { value: '1' }

const AllWidgets = { MyWidget };
const AllJoojoos = { MyJoojoo };

enum ThingTypes {
  Widget = 1,
  Joojoo = 2
}


type IdOf<T extends ThingTypes> = 
T extends ThingTypes.Widget
    ? keyof typeof AllWidgets
    : T extends ThingTypes.Joojoo ? keyof typeof AllJoojoos : never

class Thing<T extends ThingTypes> {
  thingType: T;
  thingId: IdOf<T>;
}

function isWidget(t:Thing<any>): t is Thing<ThingTypes.Widget> {
  return t.thingType === ThingTypes.Widget;
}

function isJoojoo(t: Thing<any>): t is Thing<ThingTypes.Joojoo> {
  return t.thingType === ThingTypes.Joojoo;
}

  
function valueOf<T extends ThingTypes>(self: Thing<T>): T extends ThingTypes.Widget
    ? typeof AllWidgets[keyof typeof AllWidgets]
  : T extends ThingTypes.Joojoo ? typeof AllJoojoos[keyof typeof AllJoojoos] : never {
      
    if (isWidget(self)) {
      let tid = self.thingId;
      return AllWidgets[self.thingId];
    } else if (isJoojoo(self)) {
      return AllJoojoos[self.thingId];
    } else {
      throw new Error('What is this?')
    }
}
declare let v: Thing<ThingTypes.Widget>

let x = valueOf(v)

```

Since the guard can't narrow over the type parameter, it complains that the indexer type is wrong.

**Comment by spion** [comment]
The most minimal example is

```

enum ThingTypes {
  Widget = 1,
  Joojoo = 2
}

class Thing<T extends ThingTypes> {
  thingType: T;
  thingData: string;
}

function isWidget<T extends ThingTypes>(t:Thing<T>): t is Thing<ThingTypes.Widget> {
  return t.thingType === ThingTypes.Widget;
}

function isJoojoo<T extends ThingTypes>(t: Thing<T>): t is Thing<ThingTypes.Joojoo> {
  return t.thingType === ThingTypes.Joojoo;
}
```

But that can be worked around using `any` - however the above full example demonstrates that workaround is not perfect

**Comment by weswigham** [comment]
@spion You want to write
```ts
function isOne<T extends 1 | 2 | 3>(t: T): t is (T&1) { return t === 1; } // note the intersection
```
this way your argument retains its relationship with `T`, but is also known to be a `1`.

**Comment by spion** [comment]
@weswigham the more complex example in the middle explains why that doesn't always work - I really don't want to keep the `T` because the conditional type IdOf<> wont be able to extract the right set of string keys so I can index into `AllWidgets` with it.

**Comment by mhegazy** [comment]
With the new example, you still have not answered @RyanCavanaugh question:
> What is the intent of `T` here? It's unnecessary

I would have written the type guard as:

```ts
function isWidget(t: Thing<ThingTypes>): t is Thing<ThingTypes.Widget> {
    return t.thingType === ThingTypes.Widget;
}
```

**Comment by spion** [comment]
@mhegazy See the conditional type in my second comment:

```typescript
type IdOf<T extends ThingTypes> = 
T extends ThingTypes.Widget
    ? keyof typeof AllWidgets
    : T extends ThingTypes.Joojoo ? keyof typeof AllJoojoos : never
```

I believe a type variable is required there, so in that case the type guard you wrote will keep the `T` around and the conditional type wont be able to resolve the union-of-keys type.

**Comment by spion** [comment]
BTW for me personally this "bug" is really is low priorty now (needs a very specific interaction of all of type guards, conditional types and mapped types to reproduce, and we found a workaround) so feel free to ignore it. I am still a little curious to know whether there is any good reason to forbid a type guard from removing the type variable.
