### ISSUE TITLE
#2487 __extends

### ISSUE THREAD

**Issue by streamich** [Microsoft/TypeScript#2493]
Can you please reconsider #2487 issue again. Otherwise, TypeScript is currently unusable for web projects.

**Comment by RyanCavanaugh** [comment]
We are always taking things under consideration. Please wait more than 30 minutes for us to respond to comments on issues.

**Comment by danquirk** [comment]
There is no need to log a separate issue here. #2487 was closed because as mentioned in there the same request is already covered in an open issue #2009.
