### ISSUE TITLE
Aggressive completion makes it difficult to type function types.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [Microsoft/TypeScript#2494]
![builder](https://cloud.githubusercontent.com/assets/4564579/6836093/6a65960c-d2fc-11e4-976e-49b522bff7df.gif)

Note that i'm just trying to write ```(a: string) =>``` but i get 'a' completing out to some value.  We need a builder here.

**Comment by paulvanbrenk** [comment]
Fixed with PR #2979
