### ISSUE TITLE
Support type guarding on 'never' field

### ISSUE THREAD

**Issue by zheeeng** [Microsoft/TypeScript#24949]
## Search Terms

type guard, never, never type, in operator, in type guard

## Suggestion

At present, we can't use 'in' operator for type guarding. Wish we have this feature.

## Use Cases

```typescript
type A = {
    foo: never,
    bar: number,
}

type B = {
    foo: string,
    bar: string,
}


function test(p: A | B) {
    if ('foo' in p) {
       // expect p to be type B
    } else {
        // expect p to be type A
    }
}

type A2 = {
    foo: number,
    bar: number,
}

type OmitFoo<T> = T & { foo: never }

function test(p: OmitFoo<A2> | B) {
    if ('foo' in p) {
       // expect p to be type B
    } else {
        // expect p to be type OmitFoo<A2>
    }
}
```

function test(p: A | B) {
    if ('foo' in p) {
       // expect p to be type B
    } else {
        // expect p to be type A
    }
}

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by mhegazy** [comment]
Setting a property to `never` does not remove it from the type. it still exists. the `in` narrowing wil still find it.

I would say this usecase should use `Pick` and `Exclude`:

```ts
type OmitFoo<T> = Pick<T, Exclude<keyof T, "foo">>
```

**Comment by zheeeng** [comment]
@mhegazy Actually I'm looking a way to get the exact type from a union type:

I found that https://github.com/Microsoft/TypeScript/issues/12936#issuecomment-393202175
```typescript
type AllKeys<U> = U extends any ? keyof U : never
type ExclusifyUnion<U> = [U] extends [infer V] ?
 V extends any ? 
 (V & {[P in Exclude<AllKeys<U>, keyof V>]?: never}) 
 : never : never
```

and https://github.com/Microsoft/TypeScript/issues/14094#issuecomment-373782604
```typescript
type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };
type XOR<T, U> = (T | U) extends object ? (Without<T, U> & U) | (Without<U, T> & T) : T | U;

type NameOnly = { is: "NameOnly", name: string };
type FirstAndLastName = { is: "FirstAndLastName", firstname: string; lastname: string };
type Person = XOR<NameOnly, FirstAndLastName>;
```

are much close to what I want. But, I can use 'in' operator on them. Coz them don't remove the 'never' type.
