### ISSUE TITLE
Allow function declarations to declare that they implement an interface

### ISSUE THREAD

**Issue by dotproto** [Microsoft/TypeScript#24942]
## Search Terms

* function interface
* function type
* function implements
* function declaration implements
* function declaration interface
*  function declaration type
* "function declaration" implements
* "function declaration" interface
* "function declaration" type
* generic function implements
* function signature implements

## Suggestion

Allow static function declarations to implement an interface.

## Use Cases

I have a decorator that accepts a function with a well known generic signature, but there's currently no way to indicate that a function implements that signature.

### Problem

At the moment the way the documentation, articles, and other issues on this repo have recommended declaring the function's signature is with a function expression such as:

```
interface ResponseTransformer<T, B = any> {
  (method: string, url: string, body: B): T;
}
let myTransformer: ResponseTransformer<string[]> = (a, b, c) => {
  return [];
} 
```

Unfortunately, following this suggestions will cause the Angular AOT compiler to error with a message like

```
ERROR A(B,C): Error during template compile of 'D'
  Function expressions are not supported in decorators in 'E'
    'E' contains the error at F(G,H)
      Consider changing the function expression into an exported function.
```

### Solution

In order to address this problem, I'd like to suggest mirroring the class implements syntax for functions. I'm not a type system expert by any means, but I believe this would be symmetric with existing class syntax and therefore predictable for TypeScript users.

```
function functionName(/* … */) implements TARGET_INTERFACE {}
```

To the best of my knowledge this could co-exist with current TypeScript function features such as generic arguments.

```
interface Interface<T> {
  (first: T, second: string, third: number[])
}
function functionName<T>(arg1: T, arg2: string, arg3: number[]) implements Interface<T>: T {
  return new IntefaceFactory(arg2, arg3);
}
```

This may also address the difficulty of modeling traditional JavaScript ES3-style constructor functions in TypeScript.

## Examples

Continuing the original example, we could declare the transformer function by adding the cast

```
interface ResponseTransformer<T, B = any> {
  (method: string, url: string, body: B): T;
}
function myTransformer(a, b, c) implements ResponseTransformer<string[]> {
  return ['we did it!'];
}
```

## Checklist

(To the best of my knowledge) my suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. new expression-level syntax)
    * __It may be? I'm not sure.__

**Comment by mhegazy** [comment]
As @ajafff noted, the example in the is valid. the types will flow from context to your lambda.

**Comment by DanielRosenwasser** [comment]
I think the error message is a red herring - it's frustrating that declaring a decorator requires using different function syntax than I'm used to:

```ts
let lazy: PropertyDecorator = () => {
    throw new Error("not implemented");
}

// vs.

function lazy() implements PropertyDecorator 
    throw new Error("not implemented");
}
```

**Comment by dotproto** [comment]
@ajafff Updated to reflect that this error is thrown by the Angular AOT compiler.

@mhegazy I didn't meant to suggest that function expressions are invalid TypeScript. Expressions are great for a lot of use cases, but I don't think it invalidates the utility of being able to type a function declaration. As @DanielRosenwasser said, its frustrating that I have to contort my JavaScript rather than being able to add type information to a widely used existing pattern.

**Comment by mhegazy** [comment]
The `implements` clause in an structural type system is rather redundant. All uses are validated checker regardless of the use of `implement`. Also `implements` does not contextually type the declaration, so you literally get no value out of that other than the checking of assignablity. now combine that with how there is no natural place syntactically to add an `implements` clause on a function declaration. Overall, i think the use of an interface and a function expression is superior pattern to an `implements` pattern both in terms of value (contextual types) and readability (syntax).
