### ISSUE TITLE
[loc][Query][TypeScript] Localizability of 0; "A_non_dry_build_would_build_project_0_6357"

### ISSUE THREAD

**Issue by PDostalek** [Microsoft/TypeScript#24948]
**Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.
Please re-assign back to use in case you are not the right contact person or you can´t assign to a proper person.
Can you help please?
Thanks!**

**Source**:
A non-dry build would build project '{0}'

**File Name**:
bin\Release\localize\ENU\diagnosticMessages.generated.json

**Resource ID:**
0; "A_non_dry_build_would_build_project_0_6357"

**Query**:
What is the meaning of "non-dry" here? Is the build simply not using the DRY principle as defined here ?

**Source** **Term**: DRY
**Definition**: The principle of software development that aims at reducing repetition of information of all kinds.

**Comment by mhegazy** [comment]
dry refers to the flag `--dry`. the flag tells the compiler to not make any changes to the files on disk, but list all the operations it would have done.

**Comment by PDostalek** [comment]
Should be "non-dry" in this source translated or is related as a code to this flag?

**Comment by mhegazy** [comment]
> Should be "non-dry" in this source translated or is related as a code to this flag?

yes. `dry` is `--dry`. and i would expect it to stay `"dry"` in translated message.

**Comment by mhegazy** [comment]
Would you like us to the text of the English message to ease the translation?

**Comment by PDostalek** [comment]
No other changes are needed. Thanks for your effort.

**Comment by PDostalek** [comment]
Another Q: Could you please provide more context about the first and second build in this sentence ?

**Comment by mhegazy** [comment]
Not sure what you mean by "build". 

if you are refering the to the placeholder `{0}`, this it is the project name, which is a file name

**Comment by PDostalek** [comment]
Is "second build" in "A non-dry build would **build** project '{0}' " meant as build = create or make ? We assume yes

**Comment by mhegazy** [comment]
correct.

**Comment by PDostalek** [comment]
Thanks
