### ISSUE TITLE
How TypeScript team debugs typescript compiler code? 

### ISSUE THREAD

**Issue by brightcr** [Microsoft/TypeScript#24943]
I am asking question here - to get insights from TypeScript team, how you are debugging TS source files?

I am just started with understanding TS code, I want to understand different stages of compiler and how data structures are generated, the architecture wiki is great for overview, but I want to get more depth into code, so that If I want to contribute, I can do it confidently.

This is how I am approaching:
I am using ts-node to set breakpoint on sample TS file, however, it is referring to "node_modules\typescript\lib\typescript.js", but, however, unable to put breakpoint in TS source files.
I see below is minimal entry point to call TS compiler as below, here I am passing sample ts file in fileNames:
``` js
 let program = ts.createProgram(fileNames, options);
 let emitResult = program.emit();
```

I am more of interested how to debug code, what tools you are using, how you are setting breakpoints and looking into values at runtime?

**Comment by meritozh** [comment]
Do you enable source map?

**Comment by brightcr** [comment]
Thanks for providing commands. However, I am still struggling to set up. Below is my launch.json file:
```json
 {
      "name": "Attach to TS Server",
      "type": "node",
      "request": "launch",
      "protocol": "inspector",
      "port": 5859,
      "sourceMaps": true,
      "outFiles": ["${workspaceFolder}\\built\\local"],
      "runtimeArgs": ["--inspect=5859"],
      "args": ["Sample.ts"],
      "program": "${workspaceFolder}\\built\\local\\tsc.js"
  }
```
I have added Sample.ts in same typescript cloned repo folder and started debugger in VS Code from that folder. No breakpoints are hit but file is compile to Sample.js. The port is set using `$env:TSS_DEBUG = 5859`. Also, `jake local` has generated map files.

It would be helpful if you can provide more details.

**Comment by DanielRosenwasser** [comment]
Try this one:

```json
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceFolder}/built/local/tsc.js",
            "args": [
                "C:/foo.ts",
                "--skipLibCheck",
                "--noLib"
            ],
            "sourceMaps": true,
            "protocol": "inspector"
```

or if you're using nvs:

```json
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceFolder}/built/local/tsc.js",
            "args": [
                "C:/foo.ts",
                "--skipLibCheck",
                "--noLib"
            ],
            "sourceMaps": true,
            "protocol": "inspector",
            "runtimeArgs": [ "10.0" ],
            "windows": {
                "runtimeExecutable": "nvs.cmd"
            },
            "osx": {
                "runtimeExecutable": "nvs"
            },
            "linux": {
                "runtimeExecutable": "nvs"
            }
```

**Comment by brightcr** [comment]
This still doesn't work - getting below error in debug console:

> SourceMaps.getMapForGeneratedPath: exception while processing path: C:\TypeScript\built\local\tsc.js, sourcemap: tsc.js.map
> TypeError: Cannot read property 'map' of undefined

Looking into  [sourceMapFactory.ts](https://github.com/Microsoft/vscode-chrome-debug-core/blob/6608d00d04a9a9b08edcf86c97e4febdafbfbeab/src/sourceMaps/sourceMapFactory.ts#L50) and [SourceMap.ts](https://github.com/Microsoft/vscode-chrome-debug-core/blob/6608d00d04a9a9b08edcf86c97e4febdafbfbeab/src/sourceMaps/sourceMap.ts#L103) - it is accessing - sources from JSON, however, the typescript generates map file for tsc in **sections based alternate mapping format**. The VS Code doesn't support this format.
