### ISSUE TITLE
Missing iframe.srcdoc?

### ISSUE THREAD

**Issue by yebrahim** [Microsoft/TypeScript#24956]
## Search Terms

iframe srcdoc

## Suggestion

Define the attribute `srcdoc` on `HTMLIFrameElement`.

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by mhegazy** [comment]
Spec reference: https://html.spec.whatwg.org/multipage/iframe-embed-object.html#the-iframe-element

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by mhegazy** [comment]
We should add https://html.spec.whatwg.org/multipage/iframe-embed-object.html to the list of supported spec files in https://github.com/Microsoft/TSJS-lib-generator

**Comment by yebrahim** [comment]
I can see the attribute is already here: https://github.com/Microsoft/TSJS-lib-generator/blob/8d94cce5b62d8fee618eb3b6c0311aab1f26f450/inputfiles/addedTypes.json#L715

Is this not the right place?

**Comment by mhegazy** [comment]
ah if it is there, then we are good. sorry did not check earlier.
