### ISSUE TITLE
Allow globbing in path mapping

### ISSUE THREAD

**Issue by jas99** [Microsoft/TypeScript#24954]
Please refer to this issue.

https://github.com/dividab/tsconfig-paths/issues/47#issuecomment-397235681

Globing is can't be not in tsconfig paths, its very usefull.

Thx

**Comment by DanielRosenwasser** [comment]
Could you elaborate a little on the use-case you had in mind? Seems like that could be a potentially expensive operation that doesn't really reflect what might happen at runtime.

**Comment by jas99** [comment]
```
"paths": {
      "@ent/*": [
        "server/src/entities/**/*"
      ]
    }
```

Hmm.. I don't know about it being too expensive, its recursive list of .ts[x] files in a folder and not anything else. The only issue I see might be name conflict; in my usecase entities will have unique name in folder structure anyways. You in order to solve this you can set convention that the first filename wins.

For e.g

`import {Person} from '@ent/Person'`
This will recursively find first person file in `server/src/entities` folder.

Thx

**Comment by mhegazy** [comment]
Path mapping is meant to mimic a module loader runtime behavior. what module loader that does this fuzzy search at runtime to locate the module?
