### ISSUE TITLE
Named destructured imports.

### ISSUE THREAD

**Issue by superamadeus** [Microsoft/TypeScript#24962]
## Search Terms

- named import group
- import as named
- import into object

## Suggestion

Allow import destructuring into a local namespace.

```typescript
// Today: import an entire module into a local namespace.
import * as StringUtils from "./utils/string";

const asCamelCase = StringUtils.toCamelCase("what up doc"); 
const asSnakeCase = StringUtils.toSnakeCase("what up doc");

/* ------ */

// Desired: import desired components into a local namespace.
import { toCamelCase } as StringUtils from "./utils.string";

const asCamelCase = StringUtils.toCamelCase("what up doc"); 
const asSnakeCase = StringUtils.toSnakeCase("what up doc"); 
// ^ error: property toSnakeCase does not exist on type 'typeof StringUtils'

``` 

## Use Cases

Modules may export names which are collision-prone or only make sense in context. It would be useful to import them into a namespace to prevent collisions without needing to alias each name explicitly. 

## Examples

```typescript
// before 
import { 
    fromEvent as observableFromEvent, 
    timer as observableTimer,
    race as observableRace 
} from "rxjs";

// after
import { fromEvent, timer, race } as createObservable from "rxjs";
```

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] (?) This could be implemented without emitting different JS based on the types of the expressions
* [ ] (?) This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by andy-ms** [comment]
This is out of scope of the [design goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals) since it involves adding new expression-level JavaScript.

**Comment by superamadeus** [comment]
@andy-ms gotcha. Should I close this then?

**Comment by andy-ms** [comment]
Yes, thanks.

**Comment by superamadeus** [comment]
No, thank you.
