### ISSUE TITLE
API includes internal functions

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#24966]
https://github.com/Microsoft/TypeScript/blob/a56b272d3891916a8debe36087fe7563bbade164/tests/baselines/reference/api/tsserverlibrary.d.ts#L10612 currently includes `function getParentNodeInSpan`, but in `src/services/utilities.ts`, that function appears in an `/* @internal */` namespace, so it shouldn't appear in the API. (There hasn't been a publish yet this week so I don't know if it would appear in the published API.)

I checked in the commit before #24850 (c34a6d9d12ff0bb9e8f5894d35edfdbb9886bd13) and the function was not present then. The file was also only 8604 lines, while now it has 14161 lines. CC @RyanCavanaugh

**Comment by weswigham** [comment]
@andy-ms AFAIK @RyanCavanaugh is aware of the problem and has a fix in #24938.

**Comment by mhegazy** [comment]
@weswigham can you take a look. we need a temporary fix for 3.0.1.

**Comment by weswigham** [comment]
@mhegazy I think this was fixed by @rbuckton in #25556.
