### ISSUE TITLE
Conditional types expand variants

### ISSUE THREAD

**Issue by ppham27** [Microsoft/TypeScript#24969]
**TypeScript Version:**  3.0.0-dev.20180609

**Search Terms:** conditional types, type inference, union, boolean

**Code**

```ts
type Wrap<V = undefined> = V extends {} ? {value: V} : {};
type BooleanWrap = Wrap<boolean>;
const coinFlip: BooleanWrap = { value: Math.random() > 0.5 };
```

**Expected behavior:** The assignment to `coinFlip` should work.

**Actual behavior:** I get the compiler error:

```
index.ts:3:7 - error TS2322: Type '{ value: boolean; }' is not assignable to type '{ value: false; } | { value: true; }'.
  Type '{ value: boolean; }' is not assignable to type '{ value: true; }'.
    Types of property 'value' are incompatible.
      Type 'boolean' is not assignable to type 'true'.

3 const coinFlip: BooleanWrap = { value: Math.random() > 0.5 };
```

The type of `BooleanWrap` should ideally be resolved to `{ value: boolean; }`, but it is resolved to `{ value: false; } | { value: true; }`. The same thing happens with any type union. 

**Playground Link:** https://www.typescriptlang.org/play/index.html#src=type%20Wrap%3CV%20%3D%20undefined%3E%20%3D%20V%20extends%20%7B%7D%20%3F%20%7Bvalue%3A%20V%7D%20%3A%20%7B%7D%3B%0Atype%20BooleanWrap%20%3D%20Wrap%3Cboolean%3E%3B%0Aconst%20coinFlip%3A%20BooleanWrap%20%3D%20%7B%20value%3A%20Math.random()%20%3E%200.5%20%7D%3B

**Related Issues:**  https://github.com/Microsoft/TypeScript/issues/24085

**Comment by weswigham** [comment]
@ppham27 
```ts
type Wrap<V = undefined> = [V] extends [{}] ? {value: V} : {};
type BooleanWrap = Wrap<boolean>;
const coinFlip: BooleanWrap = { value: Math.random() > 0.5 };
```
conditional types are distributive by default. To disable that, simply make the checked type not-a-bare-type-parameter, as above.

**Comment by RyanCavanaugh** [comment]
@weswigham beat me by seconds. We should seed a StackOverflow question on this

**Comment by ppham27** [comment]
This works for me. Thanks! Sorry for the bother. Is there some documentation that I'm missing about the bracket notation?

**Comment by RyanCavanaugh** [comment]
It's just the usual tuple syntax; any other wrapping of the type parameter would work, e.g. `{ foo: V }`

**Comment by RyanCavanaugh** [comment]
Oh and I should add, all types extend `{}`, you almost certainly wanted to use `object` there

**Comment by ppham27** [comment]
As an aside, I had to negate the predicate:

```
type Wrap<V = undefined> = [V] extends [undefined] ? {} : {value: V} ;
```

`[V] extends [{}]` evaluates to `true` when `V = undefined`.
