### ISSUE TITLE
"emitDeclarationOnly" + "stripInternal" produces empty *.d.ts files

### ISSUE THREAD

**Issue by Olian04** [Microsoft/TypeScript#24972]
**TypeScript Version:**  3.0.0-dev.20180609

**Search Terms:** 
typescript emitDeclarationOnly and stripInternal produces empty typings

**Code**

Create 2 ts modules, one where everything being exported is marked as "internal".
```ts
/** demo.ts */
import { bar } from './demo_internal';
export function foo() {}

/** demo_internal.ts */
// @internal
export function bar() {}
```

Setup `tsconfig.json`.
```json
{
  "compilerOptions": {
    "declaration": true,
    "emitDeclarationOnly": true,
    "stripInternal": true
  }
}
```

Run `tsc`

**Expected behavior:**

One file should be generated.
```ts
/** demo.d.ts */
export declare function foo(): void;
```

**Actual behavior:**

Two files are generated.
```ts
/** demo.d.ts */
export declare function foo(): void;

/** demo_internal.d.ts */
export {};
```

**Gist Link:** https://gist.github.com/Olian04/ce2409c449f39ca5e8bc04e0bd7e483c

**Comment by alex-titarenko** [comment]
The problem here is that VS Code will show those empty declarations while you are typing even those there is nothing to import from them and it clutters the list of what you can import. Is there any workaround?
