### ISSUE TITLE
JSX element type '${Component}' does not have any construct or call signatures. Typescript 2.9.2

### ISSUE THREAD

**Issue by dagda1** [Microsoft/TypeScript#24988]
I have the same problem as #24893.  I am using typescript 2.9.2.

I am trying to use `@types/react-document-title` .

Their definition file is:

```
// Type definitions for react-document-title 2.0
// Project: https://github.com/gaearon/react-document-title
// Definitions by: Cleve Littlefield <https://github.com/cleverguy25>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped
// TypeScript Version: 2.6

import * as React from 'react';

interface DocumentTitleProps {
    title: string;
}

declare class DocumentTitle extends React.Component<DocumentTitleProps, any> {
}

export default DocumentTitle;
```

When I try and import it like this:
```
import * as DocumentTitle from 'react-document-title';
```
 I get the typescript dreaded error:

> JSX element type 'DocumentTitle' does not have any construct or call signatures.

When I import like this:

```
import DocumentTitle from 'react-document-title';
```

typescript is happy but the page does not render because `DocumentTitle` is undefined with the import declared like that.

This is of course does work `const DocumentTitle = require('react-document-title');`

My tsconfig.json is this:
```
{
  "extends": "../../common/frontend-common/typescript/tsconfig.base.json",
  "compilerOptions": {
    "baseUrl": ".",
    "outDir": "./dist",
    "rootDir": "./src",
    "jsx": "react",
    "paths": {
      "react": ["node_modules/@types/react"]
    },
    "lib": ["dom", "es2015", "es5", "es6"],
    "noImplicitAny": true
  },
  "include": ["src/**/*.ts", "src/**/*.tsx"],
  "exclude": ["node_modules", "build", "src/**/*.test.tsx", "src/**/*.test.ts", "src/test/**/*", "src/features/**/*"]
}
```

which references a `tsconfig.base.json`:

```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "sourceMap": true,
    "types": ["node", "jest"],
    "jsx": "react",
    "skipLibCheck": true,
    "typeRoots": ["../node_modules", "./types"],
    "lib": ["dom", "es2015", "es5", "es6"],
    "noUnusedLocals": true,
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true
  }
}
```

I've tried `allowSyntheticDefaultImports` true and same deal

**Comment by Kovensky** [comment]
That is an incorrect type definition. It should be `export = DocumentTitle`.

https://github.com/gaearon/react-document-title/blob/master/index.js#L37

**Comment by dagda1** [comment]
If you make that change I then get the error message:

> [ts] Module '"/Users/paul.cowan/projects/ds/common/frontend-types/react-document-title/index"' resolves to a non-module entity and cannot be imported using this construct

I am absolutely lost with trying to create your own modules and how to reference them from multiple packages.  There has to be a simpler way than this

After much trial and error I stumbled across this:

```
   "baseUrl": ".",
    "paths": {
      "*": ["../../common/frontend-types/*"]
    },
```

Now I can't even reference the types.  So I would say this is not closed.

**Comment by dagda1** [comment]
ANd I have a similar issue with this:

```
export interface CookiesHook {
  onSet<T>(name: string, value: T | null | undefined, options?: CookieOptions): void;
  onRemove(name: string, options?: CookieOptions): void;
}

export interface CookiesHook {
  onSet<T>(name: string, value: T | null | undefined, options?: CookieOptions): void;
  onRemove(name: string, options?: CookieOptions): void;
}

export interface CookieOptions {
  path?: string;
  expires?: Date;
  maxAge?: number;
  domain?: string;
  secure?: boolean;
  httpOnly?: boolean;
}

export interface CookieParseOptions {
  doNotParse?: boolean;
}

export default class Cookies {
  constructor(cookieHeader?: string | object | null, hooks?: CookiesHook[]);
  get<T>(name: string, options?: CookieOptions): T | null | undefined;
  set<T>(name: string, value: T | null | undefined, options?: CookieOptions): void;
  remove(name: string, options?: CookieOptions): void;
  parseCookies(cookies?: string | object | null): Map<any, any>;
  isParsingCookie(value: string | null | undefined, doNotParse: boolean | null | undefined): boolean;
  readCookie<T>(value: string | null | undefined, options?: CookieParseOptions): T | null | undefined;
}
```

Which gives 

 Cannot use 'new' with an expression whose type lacks a call or construct signature.

When referenced like this: ` Cannot use 'new' with an expression whose type lacks a call or construct signature.`

This is so complex for something that should not be.

**Comment by dagda1** [comment]
I've lost the whole day to this, it is so difficult.

**Comment by dagda1** [comment]
@Kovensky can you reopen this please.
