### ISSUE TITLE
Update import on file rename sometimes drops trailing ";

### ISSUE THREAD

**Issue by AlCalzone** [Microsoft/TypeScript#24985]
**TypeScript Version:**  2.9.2

**Search Terms:** update import file rename

Sometimes when auto-updating imports on file move, the trailing `";` from the import statement gets lost.
I'm not entirely sure what triggers this bug as most of the time things work just fine. But I've had several instances of this today.

**Code**

```ts
// file dir1/file1.ts
import { foo } from "../dir2/file2.ts";

// file dir2/file2.ts
export const foo = "foo";
```
Move `file1.ts` to `dir2` and accept the automatic import update VSCode offers.

**Expected behavior:**
`file1.ts` becomes
```ts
import { foo } from "./file2.ts";
```

**Actual behavior:**
Sometimes, `file1.ts` becomes
```ts
import { foo } from "./file2.ts
```

**Comment by mhegazy** [comment]
> Sometimes when auto-updating imports on file move,

Can you give us more details about the when this happens? ca you share the server log from a session where that occurred?

**Comment by mhegazy** [comment]
You can upload logs using 
1. With "typescript.tsserver.log": "verbose" enabled
2. Restart vscode or vscode insiders
3. Reproduce the problem
4. Run ```code --upload-logs``` on the command line (or ```code-insiders --upload-logs``` if using vscode insiders) and follow instructions
5. Share the log file ID

**Comment by AlCalzone** [comment]
Will do

**Comment by AlCalzone** [comment]
Cannot reproduce the issue anymore - seems to have been a temporary glitch. Closing for now...
