### ISSUE TITLE
Unable to store and reuse result of user defined type guard function

### ISSUE THREAD

**Issue by rssfrncs** [Microsoft/TypeScript#24983]
**TypeScript Version:** 2.9.1

**Search Terms:** caching type guard result

**Code**

```typescript
type TChildrenFunc = () => string;
type TChildren = TChildrenFunc | string;

function isFunction(render: TChildren): render is TChildrenFunc {
  return typeof render === "function";
}

// render is of type TChildren
const cacheResult = isFunction(render);

// errors below
const test = cacheResult ? render() : render;
```

**Expected behavior:**

Same as in-lining the type guard call.

**Actual behavior:**

TypeScript is unable to infer the correct type.

**Playground Link:** https://codesandbox.io/s/30v146k811 Check `Hello.tsx`

**Related Issues:** Nope.

**Comment by hraban** [comment]
I just came here to post a similar bug:

```ts
function twostep(x: symbol | string) {
    const isSymbol = typeof x === "symbol";
    if (!isSymbol) {
        console.log(`Type of x is still string | symbol here: ${x}`);
    }
}

function onestep(x: symbol | string) {
    if (typeof x !== "symbol") {
        console.log(`Type of x is now just string: ${x}`);
    }
}
```

[playground](https://www.typescriptlang.org/play/index.html#src=function%20twostep(x%3A%20symbol%20%7C%20string)%20%7B%0D%0A%20%20%20%20const%20isSymbol%20%3D%20typeof%20x%20%3D%3D%3D%20%22symbol%22%3B%0D%0A%20%20%20%20if%20(!isSymbol)%20%7B%0D%0A%20%20%20%20%20%20%20%20console.log(%60Type%20of%20x%20is%20still%20string%20%7C%20symbol%20here%3A%20%24%7Bx%7D%60)%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Afunction%20onestep(x%3A%20symbol%20%7C%20string)%20%7B%0D%0A%20%20%20%20if%20(typeof%20x%20!%3D%3D%20%22symbol%22)%20%7B%0D%0A%20%20%20%20%20%20%20%20console.log(%60Type%20of%20x%20is%20now%20just%20string%3A%20%24%7Bx%7D%60)%3B%0D%0A%20%20%20%20%7D%0D%0A%7D)

**Comment by mhegazy** [comment]
Looks like a duplicate of #24865
