### ISSUE TITLE
Have better story for overriding JSX/HTML DetailedHTMLProps

### ISSUE THREAD

**Issue by natew** [Microsoft/TypeScript#24981]
## Search Terms

glamor css prop jsx DetailedHTMLProps

## Suggestion

From [this issue](https://github.com/threepointone/glamor/issues/283).

Currently this:

![image](https://user-images.githubusercontent.com/12100/41452085-fc72b714-7024-11e8-9eb6-eab67c228eae.png)

is preventing me from converting a huge amount of files to `.ts`.

There should be an easier way to allow extending the type here without having to add an import to every file. I think I could have a forked react-dom type lib perhaps? But not sure. That also seems a little intensive.

Similarly, we have a custom renderer that allows many different tag names. You end up with huge errors around all the custom tag names.

Not sure the best solution, but would like to RFC.

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by mhegazy** [comment]
It is hard for me to piece together what the issue is from this request. there is not a clear description of the problem nor samples. Please provide more details, or follow the issue template.

**Comment by natew** [comment]
The rest of the template wasn't relevant to this issue.

**Problem**:

I can't (or don't know how to) add a valid property to DetailedHTMLProps for JSX in a single global place, I have to instead modify tsconfig.json to change the `jsxFactory` and the import that everywhere, meaning I have to change every file with an extra import.

**Solution**:

My question is, is there a way to extend DetailedHTMLProps that TS uses for JSX so I can add a `css` prop without having to modify every file? Preferably just once in the root somewhere.

I am new to TS, so I may just not understand this is possible.

**Comment by mhegazy** [comment]
And why is the solution in the issue not sufficient?

```ts
import * as React from "react";

declare module 'react' {
  interface HTMLAttributes<T> {
    css?: any
  }

  interface SVGAttributes<T> {
    css?: any
  }
}

```

**Comment by mhegazy** [comment]
In general, for such requests, you might have better luck sharing this on StackOverflow. This is not a support forum, it is one for reporting compiler/language bugs and suggestions. 
If you believe you are running into a compiler bug, please share a minimal repro project that demonstrates the issue you are running into and why you believe this is a compiler bug and not a declaration file issue or library usage problem.

**Comment by mhegazy** [comment]
> the solution requires modifying every file that uses jsx to use a different createElement factory no?

global augmentations only need to exist once. the factory in this case is just a red haring. see my reply in https://github.com/Microsoft/TypeScript/issues/24981#issuecomment-398582319

**Comment by natew** [comment]
Thanks a lot, that’s great.
