### ISSUE TITLE
Late-bound names appear to function differently based on declaration style

### ISSUE THREAD

**Issue by weswigham** [Microsoft/TypeScript#25009]
![strange-type-changes](https://user-images.githubusercontent.com/2932786/41491898-a88912c4-70b0-11e8-82bf-cb32978672c5.gif)

If I have a const, it takes on a literal type, which it should then reuse in the input/non-mutable positions. However if I _cast_ the literal assigned to the const (to the same thing!) the literal type is _also_ preserved in the mutable location, which is odd.

**Comment by ajafff** [comment]
I think this is expected, because the assertion makes it a non-widening type.

**Comment by weswigham** [comment]
So the interesting thing if you're OK with that is really that if you try the same thing with a unique symbol it doesn't work the same way.

**Comment by mhegazy** [comment]
this looks right to me.  i do agree with @ajafff's comments.
