### ISSUE TITLE
Support argument/parameter naming in Function types

### ISSUE THREAD

**Issue by nemoDreamer** [Microsoft/TypeScript#25006]
## Search Terms

`function`, `type`, `argument`, `parameter`, `name`, `jsdoc`, `google closure`, `TS1005`

## Suggestion

Ability to use jsDoc/Google Closure-style documentation of function type argument names:

```ts
/**
 * @returns {function(param1:string, param2:{key1:boolean, key2:number}):Object} - Argument names.
 */
function fn(){}
```

According to https://github.com/Microsoft/TypeScript/wiki/JSDoc-support-in-JavaScript, you currently support these:

```ts
/** @returns {function(string, boolean): number} */
function fn(){};
```

```ts
/** @returns {{a: string, b: number}} - May use '@returns' as well as '@return' */
function fn(){}
```

And even:

```ts
/**
 * A parameter can be a class constructor.
 *
 * @param {{new(...args: any[]): object}} C - The class to register
 */
function registerClass(C) {}
```

**But** not named arguments. 😢 

## Use Cases

I'd like to explicitly document the return of my factory function in jsDoc (without resorting to `@typedef`) while at the same time being able to use TypeScript in its tag-based form.

## Examples

```ts
/**
 * @returns {function(param1:string, param2:{key1:boolean, key2:number}):Object} - Argument names.
 */
function fn(){}
```

This gives me the following errors:

```
packages/utils-doc-markdown/__fixtures__/StatefulComponent.jsx:73:32 - error TS1005: ',' expected.
73      * @return {function(param1: string, param2: {key1: boolean, key2: number}): Object} A Function.
                                  ~

packages/utils-doc-markdown/__fixtures__/StatefulComponent.jsx:73:48 - error TS1005: ',' expected.
73      * @return {function(param1: string, param2: {key1: boolean, key2: number}): Object} A Function.
                                                  ~
```

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax) _don't know?_

**Comment by DanielRosenwasser** [comment]
How would you feel about using the following syntax instead which works today?

```ts
/**
 * @returns {(param1: string, param2: {key1: boolean, key2: number}) => Object}
 */
```

**Comment by nemoDreamer** [comment]
Yup, that works for TypeScript, but we couldn't use that, as it's not valid JSDoc, so our documentation generation fails. 😢 

Btw: is the problem that we should be using TypeScript instead to generate our documentation, and leave JSDoc behind?

**Comment by sandersn** [comment]
This is a good suggestion for the closure authors. (Or maybe jsdoc authors?) Typescript tries to support whatever those de facto standards do, but we try not to innovate unless there's no good alternative (see our recent extension of the `@template` tag to support constraints). Here, I think the standard `@callback` and closure function signatures, plus the non-standard Typescript signatures, are all close enough that we don't want to be the ones extending jsdoc.

By the way, what documentation generator do you use? It might be worthwhile to make it understand Typescript type syntax, at least some of it.

**Comment by nemoDreamer** [comment]
Makes sense, @sandersn , thanks!
I'm using doctrine (https://eslint.org/doctrine/demo/) to parse JSDoc blocks, and it does support that format, even though the Google Closure docs don't explicitly mention it: https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler#type-expressions

JSDoc3 apparently also supports all Google Closure type expressions.
