### ISSUE TITLE
languageService.getNavigateToItems('') gives 0 items

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#2500]
Based on https://github.com/Microsoft/TypeScript/issues/2486#issuecomment-86114260 I expected it to give me *all* the navigable items in the languageService. 

Test : 
```ts
var items = languageService.getNavigateToItems('');
console.log(items); // []
```

/cc @mhegazy

**Comment by basarat** [comment]
I've monkey patched this : https://github.com/Microsoft/TypeScript/blob/master/src/services/navigateTo.ts#L19

to be true all the time for now.

**Comment by basarat** [comment]
I've made (monkey patched) this : https://github.com/Microsoft/TypeScript/blob/master/src/services/navigateTo.ts#L19 to always be true for now i.e. `matches = true` 

Only till there is an api provided for it :heart:

**Comment by basarat** [comment]
That didn't work out so well. I need more control. Can we get this function exported in future `getNodeKind` : https://github.com/Microsoft/TypeScript/blob/8610a881c33d66a5776a1ce97cf6f474eddd1d89/src/services/services.ts#L2136-L2172

**Comment by basarat** [comment]
This is what I was trying to build : 
![image](https://cloud.githubusercontent.com/assets/874898/6841596/d825963a-d3e0-11e4-8b7a-e9e80daefd21.png)

I'll try and share the code once I've cleaned it up a bit

**Comment by CyrusNajmabadi** [comment]
Why not just use getNavigationBarItems on each file in the project?  What would this new API provide?

**Comment by basarat** [comment]
> Why not just use getNavigationBarItems on each file in the projec

Exactly that. I'll give that a go.
