### ISSUE TITLE
Object type not assignable to equivalent value of mapped type

### ISSUE THREAD

**Issue by ethanroday** [microsoft/TypeScript#25010]
**Code**

```ts
// Pack<{ a: number }> is { a: { value: number } }
type Pack<T> = { [K in keyof T]: { value: T[K] } };

function patch<T, K extends keyof T>(obj: Partial<Pack<T>>, key: K, value: T[K]) {
    obj[key] = { value }; // error: Type '{ value: T[K]; }' is not assignable to type 'Pack<T>[K]'.
}
```

Example usage of `patch()`:
```ts
type SomeType = {
  a: number, b: string
};

const obj: Partial<Pack<SomeType>> = {
    a: { value: 1 }
}

patch(obj, 'b', 'foo'); // desired outcome is for obj.b to equal 'foo'
```

**Expected behavior:**

Definition of `patch()` function should be fine, and calling should produce the desired outcome.

**Actual behavior:**

`patch()` function fails to compile with error `Type '{ value: T[K]; }' is not assignable to type 'Pack<T>[K]'` even though `{ value: T[K] }` does appear to be assignable to `Pack<T>[K]`:

```ts
function getPack<T, K extends keyof T>(obj: T, key: K): Pack<T>[K]  {
    const value = obj[key]; // T[K]
    return { value }; // { value: T[K]; }
}
```

**Playground Link:** 
Additional examples here: https://bit.ly/2le5qZq

**Comment by ethanroday** [comment]
@DanielRosenwasser I'm not sure I totally understand. So then why does `Pack<T>` (rather than `Partial<Pack<T>>`) work as expected? What's an example of a situation where the expected behavior I outlined above would be incorrect?

**Comment by DanielRosenwasser** [comment]
Okay, a couple of things:

First, this works the way you want under `strictNullChecks` which is odd. I don't know why that is off the bat.

Second, really neither should work. Seems like actually that's the bug.

Third,

> What's an example of a situation where the expected behavior I outlined above would be incorrect?

```ts
interface Container<T> { value: T };
type Pack<T> = { [K in keyof T]: Container<T[K]> }

function patch<T, K extends keyof T>(obj: Partial<Pack<T>>, key: K, value: T[K]) {
    obj[key] = { value };
}


let boxCollection = {
    foo: {
        value: 100,
        shapeType: "cube",
    },
    bar: {
        value: 200,
        shapeType: "sphere",
    }
};

patch(boxCollection, "foo", 100);

// Crash!
boxCollection.foo.shapeType.toLowerCase();
```

**Comment by ethanroday** [comment]
Thanks for the example - very helpful. If I understand correctly, the issue is that you can't just blindly assign something to `obj[key]` because the type of `obj[key]` may be more derived than `Box<T>`. Not to muddy the waters, then, but shouldn't the following work just fine?

```ts
function patch<T, K extends keyof T>(obj: Partial<Pack<T>>, key: K, value: T[K]) {
    obj[key].value = value; // Error: Property 'value' does not exist on type 'Partial<Pack<T>>[K]'.
}
```

**Comment by ethanroday** [comment]
@DanielRosenwasser any ideas here?

**Comment by ahejlsberg** [comment]
Closing as the original example is no longer an error.
