### ISSUE TITLE
Organize imports: exclude files via settings

### ISSUE THREAD

**Issue by no-stack-dub-sack** [Microsoft/TypeScript#25017]
## Search Terms

Organize Imports 
Exclude Organize Imports
Disable Organize Imports

## Suggestion
 It would be excellent if we had the ability to disable organize imports on a per-file basis as part of the feature's settings, e.g. : 

```json
"editor.codeActionsOnSave": {
    "source.organizeImports": true,
    "source.organizeImports.exclude": [
        "**/index.ts",
        "src/components/MyComponent.ts"
    ]
},
```
## Use Cases
Organize imports on save is an excellent time-saving feature, however in some rare cases, imports may need to be in a specific order for a specific file. For example, loading 3rd party CSS assets which conflict with one another in the right order in the root component of an angular or react app (which is one of my particular use-cases).

Currently, since I'm trying to maintain consistent standards throughout my project, I am keeping organize imports on, however, every time I modify a couple of particular files, I need to go to settings, turn it off, save, then turn it back on. It seems like this may be an edge use-case, since I don't see any one else suggesting this (searched open and closed issues, sorry if I missed something), but I'm sure others could also find it useful.

Thanks for considering my comments!

## Examples
This:
```js
import 'this-should-come-first.css';
import 'this-needs-to-be-loaded-last.css';
```
Sorts to this, even though the former condition needs to be true to preserve the correct styles:
```js
import 'this-needs-to-be-loaded-last.css';
import 'this-should-come-first.css';
```

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by no-stack-dub-sack** [comment]
:point_up: just realized this probably belongs in VSCode repo

**Comment by dlecan** [comment]
@no-stack-dub-sack did you report this need to VSCode repo? Thank you

**Comment by no-stack-dub-sack** [comment]
@dlecan yeah, after closing this, I immediately opened it in the correct repo [here](https://github.com/Microsoft/vscode/issues/52087), it was marked dupe, even though it was a bit different than the issue it was marked a dupe of. I pointed this out but unfortunately it didn't gain any traction 🤷‍♂️ .
