### ISSUE TITLE
getEditsForFileRename: changes package import of symlinked package to relative path

### ISSUE THREAD

**Issue by ajafff** [Microsoft/TypeScript#25029]
**TypeScript Version:**  3.0.0-dev.20180616

**Search Terms:** rename, relative

**Repro**

* clone https://github.com/fimbullinter/wotan
* `yarn`
  * creates symlinks for each `packages/<name>` as `node_modules/@fimbul/<name>`
* open in VSCode
* rename `packages/wotan/index.ts` to `packages/wotan/index1.ts` (simply append "1" to the name)
* accept automatic update of imports

**Expected behavior:**

No edits, file stays unchanged

**Actual behavior:**

In the first line `export * from '@fimbul/ymir';` is changed to `export * from '../ymir/src';`

**Playground Link:**  

**Related Issues:**

#24961
#25026

**Comment by arciisine** [comment]
I'm experiencing a similar issue, with referencing `.ts` files from `node_modules`.  When I accept automatic update of imports, files that are wholly unrelated are being modified in `node_modules`, and rewritten from the form `./src/file.ts` to `@scope/package/src/file.ts`.

**Comment by andy-ms** [comment]
Fixed by #25074
