### ISSUE TITLE
Typescript not understand Promise than catch logic

### ISSUE THREAD

**Issue by vforv** [Microsoft/TypeScript#25022]
```
    "typescript": "^2.7.2",
    "typescript-eslint-parser": "^14.0.0",
```

If I have promise like this:

```
export default function to<T>(promise: Promise<T>) {
    return promise
        .then((data: T) => {
            return { error: undefined, data };
        })
        .catch((error: Error) => {
            return { error, data: undefined };
        });
}

```
And after that I add async await with this logic:

```
public someMethod() {
const { error, data } = await to<SomeType>(SOME PROMISE HERE);

if(error) {
  return;
}

// HERE I WILL NOT BE ABLE TO GET SomeType because Typescript still recognise data as type:
// undefined | SomeType
data.
}
```

Maybe this is some bug with IDE I don't know. I am usigin Visual Code.

**Comment by DanielRosenwasser** [comment]
TypeScript doesn't have a way to correlate the types of `error` and `data` once you've destructured them into independent variables.

Otherwise, being able to discriminate on `undefined` or `null` on a property of an object is an open issue: #24479

**Comment by vforv** [comment]
That is bad because I need to hack data variable like this: `(data as Website[])` to make it work

**Comment by kitsonk** [comment]
I think @DanielRosenwasser might have looked at it a bit too quickly... What you have written int TypeScript could easily be [improved to accomplish your intent](https://www.typescriptlang.org/play/#src=export%20interface%20ToReturn%3CT%3E%20%7B%0D%0A%20%20%20%20error%3A%20Error%20%7C%20undefined%3B%0D%0A%20%20%20%20data%3A%20T%20%7C%20undefined%3B%0D%0A%7D%0D%0A%0D%0Aexport%20default%20function%20to%3CT%3E(promise%3A%20Promise%3CT%3E)%3A%20Promise%3CToReturn%3CT%3E%3E%20%7B%0D%0A%20%20%20%20return%20promise%0D%0A%20%20%20%20%20%20%20%20.then((data%3A%20T)%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20%7B%20error%3A%20undefined%2C%20data%20%7D%3B%0D%0A%20%20%20%20%20%20%20%20%7D)%0D%0A%20%20%20%20%20%20%20%20.catch((error%3A%20Error)%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20%7B%20error%2C%20data%3A%20undefined%20%7D%3B%0D%0A%20%20%20%20%20%20%20%20%7D)%3B%0D%0A%7D%0D%0A%0D%0Aasync%20function%20someMethod()%20%7B%0D%0A%20%20%20%20const%20%7B%20error%2C%20data%20%7D%20%3D%20await%20to(Promise.resolve('foo'))%3B%0D%0A%0D%0A%20%20%20%20if(error)%20%7B%0D%0A%20%20%20%20%20%20%20%20return%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20data%3B%20%2F%2F%20typeof%20string%0D%0A%7D%0D%0A):

```ts
export interface ToReturn<T> {
    error: Error | undefined;
    data: T | undefined;
}

export default function to<T>(promise: Promise<T>): Promise<ToReturn<T>> {
    return promise
        .then((data: T) => {
            return { error: undefined, data };
        })
        .catch((error: Error) => {
            return { error, data: undefined };
        });
}

async function someMethod() {
    const { error, data } = await to(Promise.resolve('foo'));

    if(error) {
        return;
    }

    data; // typeof string
}
```

These sort of basic questions are best asked on StackOverflow or Gitter though.

**Comment by kitsonk** [comment]
Actually, @DanielRosenwasser is right, though I am not entirely sure you wanted/needed what Daniel was suggesting.  While it is mildly inconvenient, you can still access the type.  Your original code was still _flawed_ though in representing the return of the function.  Here is a slightly better [example](https://www.typescriptlang.org/play/#src=export%20type%20ToReturn%3CT%3E%20%3D%20%7B%0D%0A%20%20%20%20error%3A%20Error%3B%0D%0A%20%20%20%20data%3A%20undefined%3B%0D%0A%7D%20%7C%20%7B%0D%0A%20%20%20%20error%3A%20undefined%3B%0D%0A%20%20%20%20data%3A%20T%0D%0A%7D%3B%0D%0A%0D%0Aexport%20default%20function%20to%3CT%3E(promise%3A%20Promise%3CT%3E)%3A%20Promise%3CToReturn%3CT%3E%3E%20%7B%0D%0A%20%20%20%20return%20promise%0D%0A%20%20%20%20%20%20%20%20.then((data%3A%20T)%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20%7B%20error%3A%20undefined%2C%20data%20%7D%3B%0D%0A%20%20%20%20%20%20%20%20%7D)%0D%0A%20%20%20%20%20%20%20%20.catch((error%3A%20Error)%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20%7B%20error%2C%20data%3A%20undefined%20%7D%3B%0D%0A%20%20%20%20%20%20%20%20%7D)%3B%0D%0A%7D%0D%0A%0D%0Aasync%20function%20someMethod()%20%7B%0D%0A%20%20%20%20const%20%7B%20error%2C%20data%20%7D%20%3D%20await%20to(Promise.resolve('foo'))%3B%0D%0A%0D%0A%20%20%20%20if%20(error)%20%7B%0D%0A%20%20%20%20%20%20%20%20return%3B%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20%0D%0A%20%20%20%20data%3B%20%2F%2F%20typeof%20string%20%7C%20undefined%0D%0A%0D%0A%20%20%20%20if%20(data)%20%7B%0D%0A%20%20%20%20%20%20%20%20data%3B%20%2F%2F%20string%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A) which expresses what Daniel was talking about when run under `--strictNullChecks`:

```ts
export type ToReturn<T> = {
    error: Error;
    data: undefined;
} | {
    error: undefined;
    data: T
};

export default function to<T>(promise: Promise<T>): Promise<ToReturn<T>> {
    return promise
        .then((data: T) => {
            return { error: undefined, data };
        })
        .catch((error: Error) => {
            return { error, data: undefined };
        });
}

async function someMethod() {
    const { error, data } = await to(Promise.resolve('foo'));

    if (error) {
        return;
    }
    
    data; // typeof string | undefined

    if (data) {
        data; // string
    }
}
```

**Comment by vforv** [comment]
Yes, in this part

```
if (error) {
        return;
}
    
data; // typeof string | undefined
```
data should be just string but not string | undefined
