### ISSUE TITLE
union optimization

### ISSUE THREAD

**Issue by amir-arad** [Microsoft/TypeScript#25037]
I'm using union type expression to express the result of merging two objects. however it's being optimized in a way that changes (over-eager?) type inference behavior.

**TypeScript Version:**  
3.0.0-dev.20180616 , 2.9.1-insiders.20180525

**Search Terms:** 
union optimization inference merge

**Code**
I've tried to simplify it as much as I can while still keeping some 'real-world' relevance.
```ts
type Argument<T> =  {
    [P in keyof T]: T[P]; // in the real use case it's `[P in keyof T]: SomeType<T[P]>`
};
class Context<T> {
    constructor(private arg: Argument<T>) {
    }
    get<T1 extends keyof T>(key: T1): T[T1]{
        return this.arg[key]; // in the real use case it's `this.arg[key].something()`
    }
}
declare function merge2<T1, T2>(arg1: Argument<T1>, arg2: Argument<T2>): Argument<T1 | T2>;
let a = merge2({foo: { foobar: true }}, {foo: { foobar: 4 }});
const res = new Context(a).get('foo').foobar;
```

**Expected behavior:**
I expect this code to compile, and res to be of type `number | boolean` 

**Actual behavior:**
Compilation fails . 
using a custom union type expression works, however:
```ts
// replaces T1 | T2 expression in the type of merge2's result
type Union<T1, T2> = {
    [P in keyof (T1| T2)]: P extends keyof T1 ? P extends keyof T2 ? T1[P] | T2[P]: T1[P] : P extends keyof T2 ? T2[P] : never;
}
```

**Playground Link:**
[the bug](http://www.typescriptlang.org/play/#src=type%20Argument%3CT%3E%20%3D%20%20%7B%0D%0A%20%20%20%20%5BP%20in%20keyof%20T%5D%3A%20T%5BP%5D%3B%20%2F%2F%20in%20the%20real%20use%20case%20it's%20%60%5BP%20in%20keyof%20T%5D%3A%20SomeType%3CT%5BP%5D%3E%60%0D%0A%7D%3B%0D%0Aclass%20Context%3CT%3E%20%7B%0D%0A%20%20%20%20constructor(private%20arg%3A%20Argument%3CT%3E)%20%7B%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20get%3CT1%20extends%20keyof%20T%3E(key%3A%20T1)%3A%20T%5BT1%5D%7B%0D%0A%20%20%20%20%20%20%20%20return%20this.arg%5Bkey%5D%3B%20%2F%2F%20in%20the%20real%20use%20case%20it's%20%60this.arg%5Bkey%5D.something()%60%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0Adeclare%20function%20merge2%3CT1%2C%20T2%3E(arg1%3A%20Argument%3CT1%3E%2C%20arg2%3A%20Argument%3CT2%3E)%3A%20Argument%3CT1%20%7C%20T2%3E%3B%0D%0A%0D%0Alet%20a%20%3D%20merge2(%7Bfoo%3A%20%7B%20foobar%3A%20true%20%7D%7D%2C%20%7Bfoo%3A%20%7B%20foobar%3A%204%20%7D%7D)%3B%0D%0Aconst%20res%20%3D%20new%20Context(a).get('foo').foobar%3B%0D%0A%0D%0A%2F%2F%20try%20this%20type%20instead%20of%20T1%20%7C%20T2%20%3A%20%0D%0A%2F%2F%20declare%20function%20merge2%3CT1%2C%20T2%3E(arg1%3A%20Argument%3CT1%3E%2C%20arg2%3A%20Argument%3CT2%3E)%3A%20Argument%3CUnion%3CT1%2C%20T2%3E%3B%0D%0Atype%20Union%3CT1%2C%20T2%3E%20%3D%20%7B%0D%0A%20%20%20%20%5BP%20in%20keyof%20(T1%7C%20T2)%5D%3A%20P%20extends%20keyof%20T1%20%3F%20P%20extends%20keyof%20T2%20%3F%20T1%5BP%5D%20%7C%20T2%5BP%5D%3A%20T1%5BP%5D%20%3A%20P%20extends%20keyof%20T2%20%3F%20T2%5BP%5D%20%3A%20never%3B%0D%0A%7D%0D%0A)

**Related Issues:** 
#18043

**Comment by mhegazy** [comment]
I think the union type you had there is not correct.. `Argument<T1 | T2>` should be `Argument<T1> | Argument<T2>` since you can not have a transformation on the union, but rather a union of the transformations.

That said. the behavior of failing inference if it comes up with non-matching candidates is something that we thought about changing, but did not seem like the right move. you can find more discussion and reasoning in https://github.com/Microsoft/TypeScript/issues/20339 and https://github.com/Microsoft/TypeScript/issues/19596.
