### ISSUE TITLE
renameFile command updates imports with case insensitive paths

### ISSUE THREAD

**Issue by donaldpipowitch** [Microsoft/TypeScript#25036]
**TypeScript Version:**  2.9.2

**Search Terms:** renameFile, case, import, path, refactor

**Code**

```ts
// file: ./Foo/foo.ts
export const foo = 1;
```

```ts
// file: ./index.ts
import { foo } from './Foo/foo';
```
* move `./Foo/foo.ts` for example into `./test` directory

**Expected behavior:**

`./index.ts` should be: 

```ts
import { foo } from './test/Foo/foo';
```

**Actual behavior:**

`./index.ts` is be: 

```ts
import { foo } from './test/foo/foo'; // lower cased
```

**Related Issues:** 

I saw https://github.com/Microsoft/TypeScript/issues/21736 which speaks about a `--forceConsistentCasingInFileNames` flag as well as a TSServer option `useCaseSensitiveFileNames`. Not sure if these options can be applied here.

---

Tested on Mac with case insensitive file system. (Lower cases my imports, breaks CI.)

**Comment by j-oliveras** [comment]
Duplicate of #24968?

**Comment by donaldpipowitch** [comment]
Thanks!
