### ISSUE TITLE
custom declaration for nested import with

### ISSUE THREAD

**Issue by dagda1** [Microsoft/TypeScript#25035]
I have asked this [question on stackoverflow](https://stackoverflow.com/questions/50878234/custom-declaration-for-nested-import-with-typescript) but no response so I am asking it here and I cannot find an explanation for this anywhere in the docs.

I have created a declaration file for [redux-api](https://github.com/lexich/redux-api) because none currently exists.

    declare function reduxApi(config: ReduxApiConfiguration): reduxApi.ReduxApiInstance;
    
    declare namespace reduxApi {
      // rest
    }
    
    export = reduxApi;

But it also has an import like this:

    import * as adapterFetch from 'redux-api/lib/adapters/fetch';

How do I create an import for this?

I have tried this:

    declare module 'redux-api/lib/adapters/fetch' {
      export default ReduxApiFetchAdapter;
    }

But it is not picked up.

  [1]: https://github.com/lexich/redux-api

**Comment by andy-ms** [comment]
`import *` is a namespace import; `export default` is a default export. The two work differently -- this is a JS feature so you could look for information on JavaScript. Here's an example: http://exploringjs.com/es6/ch_modules.html
