### ISSUE TITLE
[REGRESSION] Unable to compile TypeScript since 2.9.2

### ISSUE THREAD

**Issue by jvanoostveen** [Microsoft/TypeScript#25034]
**TypeScript Version:**  2.9.2 & 3.0.0-dev.20180616

**Search Terms:** Unable to compile TypeScript, generics, complex return type

**Code**
```ts
export let returnConstant = <T>(arg: T): (() => T) => () => arg;
```

**Expected behavior:**
The provided TypeScript code should compile.

**Actual behavior:**
The TypeScript code does not compile.
In TypeScript 2.9.1, this worked fine.
Since TypeScript 2.9.2 (including 3.0.0-dev.20180616), this will provide a TSError / Unable to compile TypeScript:

```
Error:(1, 30) TS2304: Cannot find name 'T'.
Error:(1, 33) TS2304: Cannot find name 'arg'.
Error:(1, 61) TS2304: Cannot find name 'arg'.
Error:(1, 36) TS1005: ')' expected.
Error:(1, 39) TS1005: ',' expected.
Error:(1, 40) TS1134: Variable declaration expected.
Error:(1, 42) TS1134: Variable declaration expected.
Error:(1, 52) TS1005: ';' expected.
```

**Playground Link:**  Sorry, but the playground has an outdated TypeScript version.

**Related Issues:**

**Comment by Erikvv** [comment]
This would be the equivalent using function syntax
```
export function returnConstant<T>(arg: T): () => T {
    return () => arg;
}
```

There's lots of other ways to work around it as well.

**Comment by gavinpc-mindgrub** [comment]
I just found this as well.  Here are a few more repro variants.  I don't see a pattern in what triggers it.

```typescript
/*
This is all OK in 2.9.1 but gives a slew of errors in 3.0.0-dev.20180630, like:

    7: ')' expected.
    7: Variable declaration expected.
    7: ';' expected.
    7: Declaration or statement expected.
    7: '(' expected.
    7: ')' expected.
    8: Identifier expected.
etc

*/

// 11 errors
export const repeatedly = <T>(fn: () => T): (() => IterableIterator<T>) =>
  function*() {
    while (true) yield fn();
  };

// 10 errors
export const repeatedly1 = <T>(fn): (() => IterableIterator<T>) =>
  function*() {
    while (true) yield fn();
  };

// Ok
export const repeatedly2 = <T>(fn: () => T): Function =>
  function*() {
    while (true) yield fn();
  };

// 9 errors
export const repeatedly3 = <T>(fn: () => T): (() => T) =>
  function() {
    return fn();
  };

// 8 errors
export const repeatedly4 = <T>(fn: () => T): (() => T) => () => {
  return fn();
};

// 8 errors
export const repeatedly5 = <T>(fn: () => T): (() => T) => () => fn();

// Ok
export const repeatedly6 = (fn: () => any): (() => any) => () => fn();

// 6 errors
export const repeatedly7 = (fn): (() => any) => () => fn();

// Ok
export const repeatedly8 = (fn: Function): (() => any) => () => fn();
```

**Comment by gavinpc-mindgrub** [comment]
Based on a `git bisect` (using the above test file), the offending revision appears to be 735a46f838e620.

**Comment by gavinpc-mindgrub** [comment]
On further investigation, reverting [this line](https://github.com/Microsoft/TypeScript/commit/735a46f838e620e1ecbf59f8a5d2727178d56eb8#diff-ead24f0f0f59c0ea9c1c511052e8884bL2466) fixes the regression, but breaks the new tests that were added in the revision.

```
-                return signature.type !== undefined;
+                if (typeHasArrowFunctionBlockingParseError(signature.type)) return false;
```

That's about as far as I can go with it before taking a vacation to study the parser.

**Comment by mhegazy** [comment]
@andy-ms can you take a look as well.

**Comment by mhegazy** [comment]
@jvanoostveen, @Erikvv and @gavinpc-mindgrub can you give `typescript@next` a test tomorrow and let us know if you are still running into issues?

**Comment by gavinpc-mindgrub** [comment]
Yes, that compiles in version `3.0.0-dev.20180704`.

Thanks @mhegazy and  @andy-ms!

**Comment by jvanoostveen** [comment]
Seems to be in working order again! Thanks.
