### ISSUE TITLE
Enum duplicates

### ISSUE THREAD

**Issue by kostyandrew** [Microsoft/TypeScript#25044]
**TypeScript Version:**  3.0.0-dev.201xxxxx

**Search Terms:** 
enum duplicate 
**Code**

```ts
enum Color {Red = 2, Green = 0, Blue, Yellow}
let color: Color = Color.Red;

let colorName: string = Color[color];
document.write(colorName); 
```
Generate: 
```js
var Color;
(function (Color) {
    Color[Color["Red"] = 2] = "Red";
    Color[Color["Green"] = 0] = "Green";
    Color[Color["Blue"] = 1] = "Blue";
    Color[Color["Yellow"] = 2] = "Yellow";
})(Color || (Color = {}));
var color = Color.Red;
var colorName = Color[color];
document.write(colorName);
```
**Expected behavior:**
```Red```
**Actual behavior:**
```Yellow```
**Playground Link:**  
[Playground](https://www.typescriptlang.org/play/index.html#src=enum%20Color%20%7BRed%20%3D%202%2C%20Green%20%3D%200%2C%20Blue%2C%20Yellow%7D%0D%0Alet%20color%3A%20Color%20%3D%20Color.Red%3B%0D%0A%0D%0Alet%20colorName%3A%20string%20%3D%20Color%5Bcolor%5D%3B%0D%0Adocument.write(colorName)%3B%20)
**Related Issues:**

**Comment by RyanCavanaugh** [comment]
Last in wins when there are duplicate values in an enum
