### ISSUE TITLE
Type Guards do not reflect on related types

### ISSUE THREAD

**Issue by lingz** [Microsoft/TypeScript#25040]
**TypeScript Version:** 2.8

**Code**

```ts
type Identity<T> = T;

function test(
  x: 'a' | 'b',
  y: Identity<typeof x>,
) {
  if (x === 'a') {
    const z = y;
  }
}
```

**Expected behavior:**
`x` has type `a`
`z` has type `a`

**Actual behavior:**
`x` has type `a`
`z` has type `a | b`

**Comment by MartinJohns** [comment]
`typeof x` is `'a' | 'b'`, so `y` can either be `'a'` or `'b'`, independently of the value of `x`.

**Comment by j-oliveras** [comment]
You can use function overloads (if you want that the two parameters has the same type):
```ts
type Identity<T> = T;

function test(x: 'a', y: Identity<typeof x>);
function test(x: 'b', y: Identity<typeof x>);
function test(
  x: 'a' | 'b',
  y: Identity<typeof x>,
) {
  if (x === 'a') {
    const z = y;
  }
}
```
[See at playground](https://www.typescriptlang.org/play/#src=type%20Identity%3CT%3E%20%3D%20T%3B%0D%0A%0D%0Afunction%20test(x%3A%20'a'%2C%20y%3A%20Identity%3Ctypeof%20x%3E)%3B%0D%0Afunction%20test(x%3A%20'b'%2C%20y%3A%20Identity%3Ctypeof%20x%3E)%3B%0D%0Afunction%20test(%0D%0A%20%20x%3A%20'a'%20%7C%20'b'%2C%0D%0A%20%20y%3A%20Identity%3Ctypeof%20x%3E%2C%0D%0A)%20%7B%0D%0A%20%20if%20(x%20%3D%3D%3D%20'a')%20%7B%0D%0A%20%20%20%20const%20z%20%3D%20y%3B%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Atest('a'%2C%20'a')%3B%0D%0Atest('b'%2C%20'b')%3B%0D%0A%0D%0A%0D%0Atest('b'%2C%20'a')%3B%0D%0Atest('a'%2C%20'b')%3B%0D%0A).

**Comment by MartinJohns** [comment]
@j-oliveras But that won't fix his issue that `z` is still `'a' | 'b'`, and not the actual type of `y`. Tho this sounds like a very constructed case. Perhaps he can shed some light on his actual use-case.

**Comment by lingz** [comment]
I'm trying to understand if there is a way to constrain a function arguments with some relation, i.e. having the same type. For example, what if I want a function that takes two arguments of the same type:

```typescript
f<T>(a: T, b: T)
```

Within the implementation, narrowing does not work with generics at all #25039. So we need to write it without generics, but it seems that there is no way to express this relation without using generics?

**Comment by jcready** [comment]
This would require dependent types which is not something that TypeScript offers.
