### ISSUE TITLE
Incorrect getEditsForFileRename with npm linked module

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#25059]
From https://github.com/Microsoft/vscode/issues/52022

**TypeScript Version:**  3.0.0-dev.20180616

**Search Terms:** 

**Code**
1. `git clone https://github.com/mjbvz/ts-update-paths-npm-link-bug`
1. `npm install`
1. Open project in VS Code
1. Open file `d.ts`
1. Rename `d.ts` to `a.ts`

**Expected behavior:**
No edits returned from `getEditsForFileRename `

**Actual behavior:**
`getEditsForFileRename` changes the import for `import { abc } from "sub";` to `import { abc } from "./sub/src/types"`

```
[Trace  - 2:34:49 PM] Response received: getEditsForFileRename (52). Request took 8 ms. Success: true 
Result: [
    {
        "fileName": "/Users/matb/projects/san/a.js",
        "textChanges": [
            {
                "start": {
                    "line": 3,
                    "offset": 22
                },
                "end": {
                    "line": 3,
                    "offset": 25
                },
                "newText": "./sub/src/types"
            }
        ]
    }
]
```
**Playground Link:**  

**Related Issues:**

**Comment by tomergev** [comment]
This is a horrible bug

**Comment by andy-ms** [comment]
@tomergev Should be fixed in `typescript@next`.
