### ISSUE TITLE
Bug? Closure arguments not checked for variable number of arguments

### ISSUE THREAD

**Issue by mindplay-dk** [Microsoft/TypeScript#2506]
Example:

```
class Biff {}
class Bang {}

interface Callback {
	(...biffs: Biff[]);
}

function foo(callback: Callback) {
	callback(new Biff(), new Biff());
}

foo((x: Biff, y: Bang) => console.log('whoa'));

foo((z: string, n: number) => console.log('huh'));
```

The closures passed as arguments in the two calls at the end, do not appear to get type-checked.

It's pretty plain that these closures will not be invoked with suitable arguments, yet the code appears to compile with no complaints.

How come this doesn't get type-checked?

**Comment by ivogabe** [comment]
Types are checked, but TypeScript has a structural type system. That means that some value is assignable to a type if it has (at least) all the properties of that type. Thus an object that has at least 0 properties is assignable to `Biff`. Every object has at least 0 properties, so the type `Biff` is basically equal to `any`. If you change Biff to:
```typescript
class Biff {
  someProperty: number;
}
```
You will get errors.

**Comment by mindplay-dk** [comment]
Right, so even `string` and `number`

**Comment by mindplay-dk** [comment]
Right, so even `string` and `number` are assignable to a type with an empty interface - yeah, I forget that's how this works and get confused sometimes because the type system *syntax* is so similar to other languages where this is not the case. Thanks!
