### ISSUE TITLE
Stale errors in watch mode

### ISSUE THREAD

**Issue by andreasgruenh** [Microsoft/TypeScript#25068]
Hello everyone!
I'm not quite sure that this is really a bug or if I am missing a simple configuration option but I googled for 1.5 hours and came up with nothing:

**TypeScript Version:**  3.0.0-dev.20180619

**Search Terms:**  Stale error, watch mode, saved file, closed file

**Code**

File a.ts: 
```ts
import test from './b';

test(4, 5);
```

File b.ts:
```ts
function test(x: number, y: number) {
  return x + y / 5;
}

export default test;
```

tsconfig.json:
```json
{
  "compilerOptions": {
    "module": "commonjs",
    "noEmit": true,
    "strict": true,
    "watch": true
  }
}
```

**Expected behavior:**
When running `tsc` on console, everything is fine. When one of the parameter types in `b.ts` is changed to `string`, the running compiler (in watch mode) should now show an error, becuase `test` is called with 2 numbers.

**Actual behavior:**
Errors only show up when compiler is restarted or when a.ts is saved.

**Playground Link:** https://github.com/andreasgruenh/typescript-watch

**Related Issues:** #21325 sounds similar but was fixed according to comments.

**Comment by mhegazy** [comment]
I am not seeing this on `typescript@next`. do you get the stale errors consistently? what version are you using?

**Comment by andreasgruenh** [comment]
I'm using the version that was installed with @next this morning (as stated in the initial post). Don't know if this matters, but I'm on Windows 10 and it doesn't matter what program I use to save files (vscode/np++/notepad)

When I omit the noEmit flag, the files are getting updated, but the error is not.

**Comment by mhegazy** [comment]
I think there is something else going on.. here is what i am seeing...

![screen](https://user-images.githubusercontent.com/8000722/41614623-d6938302-73ad-11e8-8624-af42d7f9a1ce.gif)

do you have other @types in your node_modules?

**Comment by andreasgruenh** [comment]
This is really weird... This is what I'm seeing:
![tsc-watch](https://user-images.githubusercontent.com/12122390/41615009-6db0985a-73fa-11e8-8e06-c1db9446517c.gif)
Note that the timestamps in the watch output get updated.
You can also see, that the project is empty. 

One addition: I addded ./node_modules/.bin to my path, so the tsc call from console starts the cli from inside node_modules

**Comment by andreasgruenh** [comment]
Oh wow, update: When updating the second parameter, it is working. When updating the first, it's not.
