### ISSUE TITLE
calculateDecodedMaps needs to be faster

### ISSUE THREAD

**Issue by RyanCavanaugh** [Microsoft/TypeScript#25063]
**TypeScript Version:** master

**Search Terms:** calculateDecodedMaps setupSourceEntry getRelativePathToDirectoryOrUrl

**Code**

Profile the compilation of `tsc` when running `lib\tsc.js -b -f src\tsc`

Result:
![image](https://user-images.githubusercontent.com/6685088/41565278-e3231234-730a-11e8-9a8a-be832379767b.png)

`setupSourceEntry` is now the hot path for overall emit of `tsc.js` - looks like too much path computation happening here as well. I wasn't sure the best fix here without doing more investigation

**Expected behavior:** Should be relatively fast

**Actual behavior:** Takes a long time

**Playground Link:** N/A

**Related Issues:**

**Comment by weswigham** [comment]
@RyanCavanaugh you already fixed this in #25048

**Comment by RyanCavanaugh** [comment]
@weswigham FWIW I think it could still be faster 🚀
