### ISSUE TITLE
Add Intl.NumberFormat.formatToParts types

### ISSUE THREAD

**Issue by Dangoo** [Microsoft/TypeScript#25069]
## Search Terms

- Intl
- Intl.NumberFormat
- Intl.NumberFormat.formatToParts
- formatToParts

(searched wiki, FAQ, issues, and the code)

## Suggestion

I'd like to add `Intl.NumberFormat.formatToParts` method and its return types as stated here at [TC39](https://github.com/tc39/proposal-intl-formatToParts). The proposal is on stage 4 and describes the `formatToParts` for `Intl.NumberFormat` and `Intl. DateTimeFormat`. The last one already got implemented by @donaldpipowitch  in #15369, but for `Intl.NumberFormats` types are still missing.
The code would be pretty close to the `DateTimeFormat` implementation except for the `*FormatPartTypes` following [ECMA402](https://tc39.github.io/ecma402/#sec-partitionnumberpattern)

## Use Cases

For use cases and examples please see [TC39/Intl formatToParts](https://github.com/tc39/proposal-intl-formatToParts).

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. new expression-level syntax)

Are you open for a pull request?
And would you prefer it to extend either
- the existing one for `Intl.DateTime` in [lib/es2017.intl.d.ts](https://github.com/Microsoft/TypeScript/blob/master/src/lib/es2017.intl.d.ts)
- the base interface of `Intl.NumberFormat` in [lib/es5.d.ts:4060](https://github.com/Microsoft/TypeScript/blob/master/src/lib/es5.d.ts#L4060)?

**Comment by mhegazy** [comment]
I would add this in a new file `src\lib\esnext.intl.d.ts`

**Comment by mhegazy** [comment]
PRs welcomed!

**Comment by ashi009** [comment]
`bigint` is forgotten in #25075.
