### ISSUE TITLE
Typescript server: bad formatting for formatonkey if convertTabsToSpaces === false

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#2507]
Configure the format options so that convertTabsToSpaces = false.

Type <enter> to insert a new line behind an indented }

Observe: the new line has tabs and spaces. The cursor sits between.

**Comment by mhegazy** [comment]
@dbaeumer can you send a PR

**Comment by dbaeumer** [comment]
PR #2687 opened
