### ISSUE TITLE
Playground does not see static members in self-static calls

### ISSUE THREAD

**Issue by v-stein** [Microsoft/TypeScript#25071]
**TypeScript Version:**  2.9 (Typescript playground)

**Search Terms:** 
- access self static members
- can't see static members
- non static call of static function

**Code**

```ts
class SomeClass {
    static: Function;
    
    constructor ( ) {
        this.static = this.constructor;
    }

    static function someStaticFunc () :string {
        return "some text";
    }
}

let someVar = new SomeClass();
let myText = someVar.static.someStaticFunc();
```

**Expected behavior:**
The playground should not show the `someVar.static.someStaticFunc` call as an error. It may be considered a bad design, but this is something that works.

**Actual behavior:**
The playground is underlining the virtual static call in red to show it as an error but is actually working fine when executing.

**Playground Link:** [Playground link](http://www.typescriptlang.org/play/#src=class%20Base%20%7B%0D%0A%20%20%20%20_static%3A%20Function%3B%0D%0A%0D%0A%20%20%20%20constructor()%20%7B%0D%0A%20%20%20%20%20%20%20%20this._static%20%3D%20this.constructor%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aclass%20Child%20extends%20Base%20%7B%0D%0A%20%20%20%20constructor()%20%7B%0D%0A%20%20%20%20%20%20%20%20super()%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20static%20doSomething()%20%3Avoid%20%7B%0D%0A%20%20%20%20%20%20%20%20alert(%22I'm%20doing%20something.%22)%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Alet%20foo%20%3D%20new%20Child()%3B%0D%0Afoo._static.doSomething()%3B)

**Comment by AlCalzone** [comment]
The error is `someStaticFunc` does not exist on type `Function` which is technically correct. If you give it the correct type (`typeof SomeClass`), your example works:
```ts
class SomeClass {
    _static: typeof SomeClass;
    
    constructor ( ) {
        this._static = this.constructor as typeof SomeClass;
    }

    static someStaticFunc(): string {
        return "some text";
    }
}

let someVar = new SomeClass();
let myText = someVar._static.someStaticFunc();
```

**Comment by v-stein** [comment]
So if we have a class `B` that inherits from `SomeClass`, we won't be able to call `B._static.someBFunction`, am I right?

**Comment by AlCalzone** [comment]
It works if you override the `_ static` variable in B:
```ts
class SomeClass {
    _static: typeof SomeClass;
    
    constructor ( ) {
        this._static = this.constructor as typeof SomeClass;
    }

    static someStaticFunc(): "some text" {
        return "some text";
    }
}

class B extends SomeClass {
    _static: typeof B;

    static someBFunc(): "foo" {
        return "foo";
    }
}

let someVar = new B();
let myText = someVar._static.someStaticFunc(); // "some text"
let myText2 = someVar._static.someBFunc(); // "foo"
```
