### ISSUE TITLE
No "this is any" error when using noImplicitThis.

### ISSUE THREAD

**Issue by mpawelski** [Microsoft/TypeScript#25076]
**TypeScript Version:**  Version 2.9.2
and
**TypeScript Version:**  Version 3.0.0-dev.20180619

*tsconfig.json*
{
  "compilerOptions": {
    "target": "es5",
    "module": "none",
    "strict": true,
    "noImplicitThis": true,
  }
}
**Code**

```ts
function funcWithAnyParam(arg: any): any {
    arg.callback();
}

var objTest2 = {
  method1(){
      console.log('method1');
  },
  func() {
    funcWithAnyParam({
      callback: function() {
        this.method1();
      }
    });
  }
};

objTest2.func();
```

**Expected behavior:**
Error that `this` in callback function is `any` (*"'this' implicitly has type 'any' because it does not have a type annotation."*)
(showing me that I might made error and that I probably should use lambda function in this case)

**Actual behavior:**
No compile error and actual runtime error because I didn't noticed the bug (`this` doesn't mean what I thought it meant)

**Comment by mhegazy** [comment]
the type of this can be set by the context. e.g.:

```ts
function f(o: Record<string, (this: number) => void>) { }

f({ f() { this.toExponential; /* OK */ } });
```

if the function parameter is declared as `any`. this is an explicit indication to the compiler that it can be any thing, including a function with a `this` parameter with type `any`.

**Comment by andy-ms** [comment]
@mhegazy That seems inconsistent because the following *does* have a compile error:
```ts
funcWithAnyParam(function() {
    this.method1();
});
```

**Comment by andy-ms** [comment]
Also, if you write:
```ts
funcWithAnyParam({
    callback: function(x) {
        this.method1(x);
    }
});
```

It's inconsistent to provide an implicit-any error for `x` but not `this`.

**Comment by mhegazy** [comment]
The first example seems like an error for me. i would not expect that to be flagged as an invalid use of `this`.
The second example introduces a declaration for `x` so that is a fair place to show the error.

**Comment by andy-ms** [comment]
Should this issue be marked as a bug in the opposite direction then?

**Comment by mpawelski** [comment]
> if the function parameter is declared as any. this is an explicit indication to the compiler that it can be any thing, including a function with a this parameter with type any.

@mhegazy Is it really? 
I mean It's obvious that you can pass anything, but for me the fact that it makes _noImplicitThis_ not working is not obvious. Isn't the whole point of this flag to show you error when this kind of situations happens?

Also @andy-ms gave great examples where it works if function is not nested in property and that _noImplicitAny_ works as I would expect it to work.
So for me it looks like obvious bug.

---

I'll just add that I found it in real code when I was changing from JS to TS and had some code that sometimes used `this` or sometimes used variable that `this` was assigned to before (like `_that`).
Because I use _noImplicitThis_ I thought it's save to make all this code consistent and change it to use `this` and lambda functions. Knowing that I would get error if I forget to change anonymous function to lambda (thanks to _noImplicitThis_ ).

Now _noImplicitThis_ seems much less reliable.

**Comment by mhegazy** [comment]
> I mean It's obvious that you can pass anything, but for me the fact that it makes noImplicitThis not working is not obvious. Isn't the whole point of this flag to show you error when this kind of situations happens?

`any` has always been the way to shut up the compiler and tell it "i know what i am doing". `this` is context dependent really. and if the caller tells you they accept `any` parameter, why would the use of `this` be illegal.. what value does this error add to the user of the library.. if anything the fix should be on the library side to not ask for such loose type for its parameters.

**Comment by mhegazy** [comment]
> Now noImplicitThis seems much less reliable.

`any` is a big hole.. if you have `any`s in your code, you should be aware that no checking is taking place. this is not specific to `--noImplicitThis` or `--srictNullChecks`

**Comment by mhegazy** [comment]
> Should this issue be marked as a bug in the opposite direction then?

sure. feel free to log a bug for the other use case..

**Comment by andy-ms** [comment]
Created #25526

**Comment by cScarlson** [comment]
I am having the **opposite problem**:

// tsconfig.json
```json
{
  "compilerOptions": {
    "noImplicitThis": false
  }
}
```

Still get an error from:
```javascript
function f() { this }
```

How come `noImplicitThis` doesn't work for enabling *or* disabling the feature? Sounds like the compiler might just not even be looking at it at all.

**Comment by DryJhin** [comment]
I have the same problem like CScarlson 

    function debounce(func: any, wait: number, immediate: Boolean = false) {
        let timeout: number | undefined;

        return function () {
            var context = this,
                args = arguments;

            var later = function () {
                timeout = undefined;

                if (!immediate) {
                    func.apply(context, args);
                }
            };

            var callNow = immediate && !timeout;
            window.clearTimeout(timeout);
            timeout = window.setTimeout(later, wait);

            if (callNow) {
                func.apply(context, args);
            }
        };
    }

**Comment by DryJhin** [comment]
cScarlson it works after clearing cache, had the same issue like you after multiple tries worked...
