### ISSUE TITLE
MSBuild .props includes extraneous backslash

### ISSUE THREAD

**Issue by lukethenuke** [Microsoft/TypeScript#25088]
*I could not find the msbuild task in this repo (or any other repo where it might be stored), so I am sorry if this is logged in the wrong project.*

The MSBuild props file contains entries like this `$(MSBuildThisFileDirectory)\` but the `MSBuildThisFileDirectory` property [already includes the backslash for you](https://msdn.microsoft.com/en-us/library/ms164309.aspx). In most cases this works since windows seems to read a path like C:\dir\\\myfile just fine, but when using a UNC path like \\\resource\dir\\\myfile then msbuild will choke on the double backslash before myfile.

**Workaround:** Edit the .props file and remove the backslash after `$(MSBuildThisFileDirectory)`

**TypeScript Version:** Irrelevant

**Search Terms:** msbuild unc, msbuild could not be loaded

**Code**
N/A

**Expected behavior:**
MSBuild builds the project successfully

**Actual behavior:**
MSBuild crashes with the error: 
`
The "TypeScript.Tasks.CheckFileSystemCaseSensitive" task could not be loaded from the assembly \\[SHORTENED]\packages\Microsoft.TypeScript.MSBuild.2.6.5\build\\..\tools\net45\TypeScript.Tasks.dll. Could not load file or assembly 'file://\\[SHORTENED]\packages\Microsoft.TypeScript.MSBuild.2.6.5\build\\..\tools\net45\TypeScript.Tasks.dll' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
`
*Notice the double backslash in the file paths after build.*

**Playground Link:** N/A

**Related Issues:** There was some issues that could be related, but did not touch the path problem.

**Comment by mhegazy** [comment]
@uniqueiniquity can you take a look

**Comment by uniqueiniquity** [comment]
Looking now.

**Comment by uniqueiniquity** [comment]
@lukethenuke I have submitted a fix for this issue for TS 3.0. Thanks for your feedback!
