### ISSUE TITLE
Self-referential jsdoc type aliases don't resolve at end of file

### ISSUE THREAD

**Issue by sandersn** [Microsoft/TypeScript#25098]
```js
/** @type {Ref2} */
var r2
/**
 * @typedef {Second} Ref2
 * @typedef {{ b: string }} Second
 */
```

**Expected behavior:**
No error, and r2 has type `{ b: string }`.

**Actual behavior:**
"Can't resolve 'Second'."

This only happens when the comment (or set of comments) is at the end of the file. The error happens regardless of order. If the file has some other error in it (eg some other reference to a type that doesn't exist like `@type {Foo}`, then the error doesn't appear.

**Comment by brendankenny** [comment]
@sandersn do you think this is something for the near future or should I be moving our typedefs up in their files for now?

We want to update to `typescript@next` to be able to use the new `@template` constraints, but from previous PRs on typedefs/exports it seems like this might be wrapped up in some of the less tractable parts of parsing jsdocs, so no worries if it's going to require more than a little time.

To add to the issue
- changing the example from
`@typedef {Second} Ref2`
into
`@typedef {exports.Second} Ref2`
also fixes the error (though obviously not what you want to do :)

- Might be a separate issue, but *some* types of code after the typedefs, like an if statement or a for loop (or even just a semicolon) changes the error to `Cannot find name 'Ref2'`, regardless of what comes after that (so, even if at the top of a file).
  ```js
  /** @type {Ref2} */ // [ts] Cannot find name 'Ref2'.
  var r2
  /**
   * @typedef {Second} Ref2
   * @typedef {{ b: string }} Second
   */

  ;
  // any code you want
  ```

**Comment by sandersn** [comment]
@brendankenny I plan to fix this in the next few days. I'm not sure what's happening, though, so it might be a complex fix.

**Comment by sandersn** [comment]
@brendankenny You found a different issue. Typedefs are not bound except when they occur before statements that we expect to have jsdoc -- specifically Class/Function/ExpressionStatement and a few others. I'll file a separate issue because this bug appears to be fixed on master.

**Comment by sandersn** [comment]
@brendankenny I opened #25252 to track the holes in binding jsdoc.
