### ISSUE TITLE
FR: const enum for Web Built-in APIs WebSocket and so on

### ISSUE THREAD

**Issue by Jack-Works** [Microsoft/TypeScript#25090]
## Search Terms
ready state constant websocket const enum

## Suggestion
Ref: https://developer.mozilla.org/en-US/docs/Web/API/WebSocket
Add a ReadyState `const enum` below as `WebSocket.ReadyState` or `WebSocketReadyState`

```typescript
const enum WebSocketReadyState {
    /** The connection is not yet open. */
    CONNECTING = 0
    /** The connection is open and ready to communicate. */
    OPEN = 1
    /** The connection is in the process of closing. */
    CLOSING = 2
    /** The connection is closed or couldn't be opened. */
    CLOSED = 3
}
```
Then make this change on interface WebSocket
```diff
-     readonly readyState: number;
+    readonly readyState: WebSocketReadyState;
```

Or for future compatibility, 
```diff
-     readonly readyState: number;
+    readonly readyState: WebSocketReadyState | number;
```

## Use Cases
```typescript
ws.readyState === WebSocketReadyState.OPEN && ws.send(...)
```

## -
This should be a const enum to prevent user write code like `WebsocketReadyState[ws.readyState] === "OPEN"`

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

And so on for other WebAPIs as well.
If Typescript team is interested but not keen on this request, maybe I can do a little bit for this request.

**Comment by mhegazy** [comment]
Const enums do not work in single file transpilation mode. the library, and for that matter any .d.ts file should not use const enums.

**Comment by Jack-Works** [comment]
Hmm maybe add a compile error in this case?

Or, change the declaration to readyState: 0 | 1 | 2 | 3 with JSX comments on it?

**Comment by Jack-Works** [comment]
But without document there is not quite a lot meaning for the magic number 0 1 2 3

**Comment by mhegazy** [comment]
That is another feature we will need to support, showing documentation on literal types, which i am not sure I see how we can go about supporting it..

but meanwhile, you can add a comment on the property itself, i.e. `readyState`

**Comment by Jack-Works** [comment]
But in lib.d.ts we cannot provide Intl string for developers

**Comment by Jack-Works** [comment]
Yeah, I mean internationalization. If it is not a problem, that will be fine.

So is there any plan about show jsdoc on literal value? Or is it even possible? (For those, maybe only add check for directly comparison of Union of Literal type and literal value, like `.readyState === 1`?)

**Comment by mhegazy** [comment]
> So is there any plan about show jsdoc on literal value?

no. but we could think of it.

> Or is it even possible? 

it is gonna be a bit interesting to add these, since all literal types with the same text point to the same internal type object. 

> For those, maybe only add check for directly comparison of Union of Literal type and literal value

not sure i understand.

**Comment by Jack-Works** [comment]
I'm meaning by this:

If resolved ==, ===, !=, !==, check the left hand side, if it reference to the type T that is a Union type with jsx comments on each union member, that is literal for the other side, while typing a corresponding literal, we give a hint.

```typescript
x as WebSocketStatus === // while I type 0 here, typescript hint "Connecting" refer to the type /** Connecting */ 0
```

For assignment, that's the same
```typescript
var x: WebsocketStatus = // here
```

**Comment by mhegazy** [comment]
The problem is not when to ask for the comment, the problem is that we can not find the location where the type was first written..

**Comment by Jack-Works** [comment]
![image](https://user-images.githubusercontent.com/5390719/42199270-2cfcbb2e-7ec0-11e8-843c-4a19f99d54b9.png)
Can we bind JSDoc comments to `NumbericLiteral` or `StringLiteral` as a child of `LiteralType`?

**Comment by mhegazy** [comment]
> Can we bind JSDoc comments to NumbericLiteral or StringLiteral as a child of LiteralType?

yes, but that means that every `"0"` in a compilation is a different type, so the caching the compiler does internally to speed up type comparison would not work.

**Comment by Jack-Works** [comment]
Well... Then can we bind the jsdoc to the type WebsocketStatus while it firstly get resolved? Extract jsdoc in the type union and set it on the whole parent type?

`A: /** a */ "0" | /** b */ "1"`
Then we bind `{ literalJsDoc: { 0: "a", 1: "b" }}` to type A

**Comment by Jack-Works** [comment]
Hmm can we invent or find a way, to notate the type in the jsdoc, and read it in completion?
