### ISSUE TITLE
Feature request: first-class labels for extensible rows / koka

### ISSUE THREAD

**Issue by Ziriax** [Microsoft/TypeScript#2509]
It would be very nice have real extensible row polymorphism in Typescript, that also works with generics.

So having type constructions that allow adding and removing 'keys' aka labels.

I tried adding labels using interfaces, but that does not work, since you cannot extend from a generic type?

```
interface IWithName<T> extends T {
   name: string
}
```

See Microsoft's research language Koka and also this old  [paper](http://research.microsoft.com/pubs/64501/fclabels.pdf), both from Daan Leijen

**Comment by jonathandturner** [comment]
I'm a fan of row polymorphism.  I actually tried to get this in about six months ago.  

Unfortunately, this would mean the type checker would always have to delay type checking interface bodies, and instead stamp them out individually and check them at each unique instantiation.  This is pretty inefficient.  Separate type checking, where you can reason about the body of the interface separate from its eventual instantiation, is much preferred.

**Comment by Ziriax** [comment]
Thanks for the fast reply.

That's too bad, since "runtime row polymorphism" happens a lot in Javascript (by its dynamic nature), and we currently can't model that generically in Typescript IMO.

**Comment by danquirk** [comment]
We have this logged already somewhere but I need to find it before I close this as a dupe.

**Comment by danquirk** [comment]
#2225
