### ISSUE TITLE
Visual Studio 2017 ignore tsconfig.json baseUrl, unable share node_modules with multiple projects

### ISSUE THREAD

**Issue by DanielS4n** [Microsoft/TypeScript#25093]
**TypeScript Version:**  2.9

**Search Terms:** 

**Code**
For reproduce the behavior is very simple, create folder with package.json and install @ angular modules.. then create net core 2.1 library project in other folder and create simple Test.ts:
```ts
import {
    OnInit
} from '@ angular/core';
```
Add simple  tsconfig.json:
```json
{
  "compileOnSave": true,
  "compilerOptions": {
    "module": "system",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "target": "es5",
    "sourceMap": true,
    "baseUrl": "{folder/node_modules}",
     "paths": {
            "@ angular/*": [ "@ angular/*" ]
       }
  }
}
```

The VS intellisense not recognize @ angular/core

**Expected behavior:**
Unable set the baseURL in any manner (VS proj property group, tsconfig.json) different from default {projectdir}/node_modules

**Actual behavior:**

**Playground Link:**  

**Related Issues:** 
whereas the @angular module alone is over 100Mb is quite stupid to have to download the package for each project!

**Comment by mhegazy** [comment]
also you do not need `baseUrl` and `paths`.
