### ISSUE TITLE
Is this a regression in control flow-based type analysis for `--strictNullChecks`?

### ISSUE THREAD

**Issue by seanpoulter** [Microsoft/TypeScript#25109]
**TypeScript Version:**  2.9.2

**Search Terms:**  typeof undefined guard property strictnullchecks

**Code**

With `--strictNullChecks`:
```ts
const obj: { [key: string]: string | undefined } = {}

const withAssignment = (key: string): string | null => {
    const value = obj[key];
    return typeof value === 'undefined'
        ? null
        : value;  
}

const withTernary = (key: string): string | null =>
    return typeof obj[key] === 'undefined'
        ? null
        : obj[key];
// Type 'string | null | undefined' is not assignable to type 'string | null'.
// Type 'undefined' is not assignable to type 'string | null'.

const withIf = (key: string): string | null => {
    if (typeof obj[key] === 'undefined') {
        return null;
    } else {
        return obj[key];
        // Type 'string | undefined' is not assignable to type 'string | null'.
        // Type 'undefined' is not assignable to type 'string | null'.
    }
}
```

**Expected behavior:**
- Just like the [example in the docs](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#control-flow-based-type-analysis) but with an `undefined` instead of a `string`. 
- No error.
- No additional explicit check.
- The property does not change in this simple statement so the type assertion should be OK.

**Actual behavior:** 😓   
![untitled](https://user-images.githubusercontent.com/2585460/41686588-9c0b1e06-74b2-11e8-827d-fac214c01262.png)

**Playground Link:** 
[http://www.typescriptlang.org/play/#src=...](http://www.typescriptlang.org/play/#src=const%20obj%3A%20%7B%20%5Bkey%3A%20string%5D%3A%20string%20%7C%20undefined%20%7D%20%3D%20%7B%7D%0D%0A%0D%0Aconst%20withAssignment%20%3D%20(key%3A%20string)%3A%20string%20%7C%20null%20%3D%3E%20%7B%0D%0A%20%20%20%20const%20value%20%3D%20obj%5Bkey%5D%3B%0D%0A%20%20%20%20return%20typeof%20value%20%3D%3D%3D%20'undefined'%0D%0A%20%20%20%20%20%20%20%20%3F%20null%0D%0A%20%20%20%20%20%20%20%20%3A%20value%3B%20%20%0D%0A%7D%0D%0A%0D%0Aconst%20withIf%20%3D%20(key%3A%20string)%3A%20string%20%7C%20null%20%3D%3E%20%7B%0D%0A%20%20%20%20if%20(typeof%20obj%5Bkey%5D%20%3D%3D%3D%20'undefined')%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20null%3B%0D%0A%20%20%20%20%7D%20else%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20obj%5Bkey%5D%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aconst%20err%20%3D%20(key%3A%20string)%3A%20string%20%7C%20null%20%3D%3E%0D%0A%20%20%20%20return%20typeof%20obj%5Bkey%5D%20%3D%3D%3D%20'undefined'%0D%0A%20%20%20%20%20%20%20%20%3F%20null%0D%0A%20%20%20%20%20%20%20%20%3A%20obj%5Bkey%5D%3B%0D%0A)

**Related Issues:** 
* https://github.com/Microsoft/TypeScript/issues/12600
* https://github.com/Microsoft/TypeScript/issues/12457

**Comment by RyanCavanaugh** [comment]
See #11483 / #10530

**Comment by seanpoulter** [comment]
Thanks for the speedy reply @RyanCavanaugh. Since this is the same as #11483, how is it different than the [docs on control flow based type analysis](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#control-flow-based-type-analysis)? Does that performance hit come from checking if the property access/getter modifies the object?

I'd like to propose two actions:

1. Can we add this to the docs and how do we get that going? This should be as accessible and well documented as the CFA docs for `typeof x === 'string`. No one else should have to waste their time with this.

2. In [#11483 you said](https://github.com/Microsoft/TypeScript/issues/11483#issuecomment-257436774): 
    > Since it should almost always be possible to write const j = list[i] instead, this shouldn't be too burdensome.

    That wouldn't pass code review in the large functional-inspired React/Redux repo I with. Is there any way to opt-in to this check?

**Comment by RyanCavanaugh** [comment]
> how is it different than the docs on control flow based type analysis? Does that performance hit come from checking if the property access/getter modifies the object?

The difference is `x.y` vs `x[expr]`.

Notice that CFA works perfectly fine when the keys are static, e.g. `if (a.b.c.d) { a.b.c.d.toString() }` is OK. The issue is when the key is computed (`obj[key]`) because now we go from a static lookup of variables + properties we already know about to an infinite matrix of `obj` vs `key`, plus the associated cost of determining whether or not `key` has been mutated between accesses.

1. We'd take a doc PR to improve that (maybe a section about arrays / indexed access?) - https://github.com/Microsoft/TypeScript-Handbook

2. `obj[key]!` will remove `null` / `undefined` from the type
