### ISSUE TITLE
extends enhancements, to allow differentiate between nominal and structural

### ISSUE THREAD

**Issue by wesleyolis** [Microsoft/TypeScript#25116]
However this way below more explicitly in communicating what asking, that a certain property existing,
because interface are structural, it looks advertising use interface name, doesn't mean much here.
May it would be good to read for those coming from nominal typing back ground to read, 'structural extends' or 'nominal extends', say as to not make mistakes a few times.. when working mainly with interfaces were their typically no members or properties and wanting to do type extraction or enhancement. It may actually be of benefit here to differentiate the two because unless one is prepare to wrap every single class in a wrapper, one is not able to use decision logic to enhance other models classes simple.
Think of wanting to write a method to extra the AttributesValues = Value1 | Value2 | Value3 | Value4
from amazon type definitions. so that they can be suggested as keys.
RecordOptional<Attributes, string>, but to do this at a global level one wants to write a method along the lines of this, relative give take extends keyword.

```.ts
type EnhanceAmazonType<T> = {
    [K in keyof T] : T[K] extends {AttributesValues: any, Value: string}
    ? RecordOptional<T[K]['AttributesValues'], string> : extends {} ? 
    EnhanceAmazonType<T[K]> : T[K]

}
```

Target specific class interface name with a nominal type guarantee, that their be no conflict, in structurally writing an incorrect classes type for 3rd party modules, that one would like not want to recursively re-write definitions for.

```.ts
type EnhanceAmazonType<T> = {
    [K in keyof T] : T[K] nominally extends ServerType
    ? RecordOptional<T[K]['AttributesValues'], string> : extends {} ?
    EnhanceAmazonType<T{K} : T[K]
}
```

A whole bunch more examples can be found on this post, showing all the issues that can arise in support for different feature enhancement, on which this is subset problem.
[https://github.com/Microsoft/TypeScript/issues/24852](https://github.com/Microsoft/TypeScript/issues/24852)

## Checklist

My suggestion meets these guidelines:
* [X ] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [X ] This wouldn't change the runtime behavior of existing JavaScript code
* [X ] This could be implemented without emitting different JS based on the types of the expressions
* [X ] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by mhegazy** [comment]
We are tracking all nominal type suggestions under https://github.com/Microsoft/TypeScript/issues/202.

**Comment by wesleyolis** [comment]
@mhegazy Thanx, I join that thread in future..
