### ISSUE TITLE
Add type checking and refactoring support for example code (e.g. in JSDocs)

### ISSUE THREAD

**Issue by Duckers** [microsoft/TypeScript#25121]
## Search Terms

`example` `code` `inline` `refactor`

## Suggestion

Often when I create a documented language entity, I want to include example code to show how the entity is used in practice. This example is often inlined in the JSDoc as indented code blocks. This is unfortunate, because it makes the example very prone to getting out of date when the code is refactored later, as there is no type checking on this code, and refactoring tools don't "see" the code, so this can go unnoticed into production.

My suggestion is to add an opt-in switch to allow the code in such blocks to be seen by the type checker and refactoring tools, giving warnings (or errors?) when the example code no longer "works" as it stands.

Pseudo-example:
```TS
/** This is a nice function that multiplies two numbers.

    It is used like this:

    @ts_check
        multiply(4, 2)
    
    It will return product of the two values.
*/
function multiply(a: number, b: number) { return a*b}
```

So if I later refactor this function to have a different name, for example, either the refactoring tool will also change the example code, or at least I will get a compiler warning.

Sometimes we want to write examples that assumes some ambient symbol that we do not want to show up in the generated documentation. This can be done with e.g. a separate section for this that is included by the type checker, but not emitted in the output.

```TS
/** This is a nice function that multiplies two numbers.

    It is used like this:

    @ts_check_preamble
        declare const my_favorite_number: number;
    @ts_check
        multiply(4, my_favorite_number)
    
    It will return product of the two values.
*/
function multiply(a: number, b: number) { return a*b}
```

## Use Cases

* Make it easy to keep example code up to date when refactoring

## Checklist

My suggestion meets these guidelines:
* [*] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [*] This wouldn't change the runtime behavior of existing JavaScript code
* [*] This could be implemented without emitting different JS based on the types of the expressions
* [*] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by Duckers** [comment]
Bonus: It would also be great if `@ts_check` blocks (and another unchecked version, simply `@ts` perhaps?) were syntax highlighted in a blend of comment colors and real code colors, and intellisense worked inside `@ts_checked` blocks while writing the example.

**Comment by RyanCavanaugh** [comment]
Have seen very little other demand for this and it would likely be enormously complex to implement (thinking about the scoping and control flow rules to apply here already makes my head hurt), so this doesn't seem to fit with our priorities right now.
