### ISSUE TITLE
Allow "Declare property" quick fix for enums

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#25129]
_From @gbbarroso on June 21, 2018 1:29_

The same way there's a "declare property" suggestion for classes when you use quick fix, there should be one for enums as well. Often you just want to create a new constant for an existing enum and you don't even care about the order / value, having this quick fix would save a trip back to the file containing the enum declaration.

To be clear, that's what I'm talking about:

![image](https://user-images.githubusercontent.com/11339504/41692866-f5318f6c-74d8-11e8-916e-b99742993ec7.png)

_Copied from original issue: Microsoft/vscode#52528_

**Comment by mhegazy** [comment]
PRs welcomed. should be a simple change.

**Comment by mhegazy** [comment]
//cc: @Kingwl

**Comment by Kingwl** [comment]
should i add that into add missing member fix?

**Comment by andy-ms** [comment]
In my opinion it loks like it would be easier as a separate fix. But could go either way.
