### ISSUE TITLE
Type checker for navTree (Outline)

### ISSUE THREAD

**Issue by ackvf** [Microsoft/TypeScript#25126]
## Search Terms
- navtree
- primitive type, string, number, boolean
- method, function, property, arrow

## Suggestion

Color coded icons in Outline view for different types.

![image](https://user-images.githubusercontent.com/2313018/41459342-a191ae94-7089-11e8-9ca9-92d1ebac1f7f.png)

## Use Cases

This change is for convenience and better experience.
It also possibly implements https://github.com/Microsoft/TypeScript/issues/25062 - to differentiate between properties and function properties (arrows).

## Examples

Example in the image above.

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by mhegazy** [comment]
The feature is currently syntactic only. that means no type information is used.
The reason some of these features are syntactic only is getting **all** types is a potentially a very expensive process, specially if you do this after every edit. 
The file can be arbitrarily big, the types of the declarations are not always explicitly defined, but are inferred from expressions, and computing the type of every property/variable/parameter would not scale.

**Comment by ackvf** [comment]
Would it also be a problem for explicitly typed properties only?

**Comment by mhegazy** [comment]
first they could be type references to other types. second, we should be consistent, and not treat some properties different from others.
