### ISSUE TITLE
getEditsForFileRename converts imports to relative paths

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#25132]
From https://github.com/Microsoft/vscode/issues/52630

**TypeScript Version:**  3.0.0-dev.20180619

**Search Terms:** 
- getEditsForFileRename
- imports

**Code**
For a TS project:

`tsconfig.json`
```json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es2016",
        "jsx": "preserve",
        "baseUrl": ".",
    },
    "exclude": [
        "node_modules",
        "**/node_modules/*"
    ]
}
```

`sub/a.ts`
```ts
export const a = 1;
```

`sub/index.ts`:
```ts
import { a } from 'sub/a';
console.log(a);
```

1. In VS Code, rename `sub/index.ts` to `sub/index2.ts`
1. Select option to update imports

**Expected behavior:**
No edits returned from `getEditsForFileRename` in this case

**Actual behavior:**
Edits returned from `getEditsForFileRename` convert `sub/index.ts`to use relative paths:

```ts
import { a } from './a';
console.log(a);
```

**Related Issues:** 
- #25029

**Comment by arackaf** [comment]
@mjbvz - I see this case is marked as closed / fixed, but the behavior persists in VS Code version 1.25.1, which Code tells me is up to date - I'm running TS 2.9.2.

Did this fix just not make it into the July releases of Code?

**Comment by arackaf** [comment]
Ah gotcha - look forward to that - thanks!
