### ISSUE TITLE
Single line preservation doesn't work for array and object literals

### ISSUE THREAD

**Issue by ahejlsberg** [Microsoft/TypeScript#2513]
We used to keep single line array and object literals on a single line in the emitted output. This appears to have broken recently. Looks like it is related to the new `preserveNewLines` experimental flag. Without this experimental flag, array and object literals are always generated on multiple lines.

**Comment by CyrusNajmabadi** [comment]
Correct, from talking to mohamed, it's been a stated implicit or explicit goal to preserve formatting when emitting.  We had taken an ad-hoc approach in several places, but there was no unifying design indicating what behavior we should have.  As such, all the code to preserve formatting was put behind an experimental flag.  It's something you can opt into, but we're effectively stating that it's not supported, and you'll only be getting a best-effort basis feature.

**Comment by mhegazy** [comment]
My original comment was about #2255. We have been capturing more and more of the token information into the AST to enable emit formatting. On other occasions we have rejected bugs that deal with output formatting, including persevering new lines, semicolons, indentation, comments between tokens ...etc.. now this is inconsistent. either we do not care about whitspaces in output we we do. if we do not, we should just remove all the token info from the tree like PropertyAccessExpression.dotToken, ConditionalExpression.questionToken, ConditionalExpression.colonToken, YieldExpression.asteriskToken,  (and the not part of this discussion though similar ArrowFunction.equalsGreaterThanToken).

**Comment by ahejlsberg** [comment]
I agree with @mhegazy. If we're going to change our approach we need an all up plan instead of little piecemeal changes. But right now I'd like us to back out the `-preserveNewLines` changes and revert to the original code.

**Comment by CyrusNajmabadi** [comment]
Line preservation for array and object literals is back again.  The work to put this behind a -preserveNewLines flag has been backed out.

Note: There is no clear guidance as to where or when we will be attempting line preservation.  I would recommend producing some rules on this, or going with the simpler approach of not preserving lines at all.
