### ISSUE TITLE
`tsserverlibrary.js` needs to be kept up-to-date in the LKG

### ISSUE THREAD

**Issue by weswigham** [Microsoft/TypeScript#25131]
We don't use it internally, but we ship it so consumers can package their own `tsserver` for whatever environment suits them (ie, browser extension). We have [had issues opened before](https://github.com/Microsoft/TypeScript/issues/17894) when we've outright broken it, so it being out-of-date is also likely an issue. (Specifically, if that old issue is any indication, we'll break webstorm by not updating it or removing it)

**Comment by mhegazy** [comment]
@RyanCavanaugh can you take a look.

**Comment by weswigham** [comment]
Please note, its declaration file also needs the `stripInternal` treatment, or we expose our internals in _its_ API (and we are right now, which isn't great).

**Comment by mhegazy** [comment]
Already tracked by https://github.com/Microsoft/TypeScript/issues/24966
