### ISSUE TITLE
Strict typing for object spread in higher order function.

### ISSUE THREAD

**Issue by ccorcos** [Microsoft/TypeScript#25142]
**TypeScript Version:**  2.9.2
**Search Terms:**  strict object literal higher order function object spread
**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**Expected behavior:**

```ts
type A = { x: number, y: number }

const x: A = { x: 1, y: 2 }

const y: A = {...x, b: 10} // Error ✅

function hoc(fn: (a: A) => A) { }

hoc(a => ({a: 1, y: 2, b: 10})) // Error ✅

hoc(a => ({ ...a, b: 10 })) // No Error ❌
```

**Actual behavior:**

I would expect the `hoc(a => ({ ...a, b: 10 }))` to throw an error. 

**Playground Link:** [playground](http://www.typescriptlang.org/play/#src=type%20A%20%3D%20%7B%20x%3A%20number%2C%20y%3A%20number%20%7D%0D%0A%0D%0Aconst%20x%3A%20A%20%3D%20%7B%20x%3A%201%2C%20y%3A%202%20%7D%0D%0A%0D%0Aconst%20y%3A%20A%20%3D%20%7B...x%2C%20b%3A%2010%7D%20%2F%2F%20Error%20%E2%9C%85%0D%0A%0D%0Afunction%20hoc(fn%3A%20(a%3A%20A)%20%3D%3E%20A)%20%7B%20%7D%0D%0A%0D%0Ahoc(a%20%3D%3E%20(%7Ba%3A%201%2C%20y%3A%202%2C%20b%3A%2010%7D))%20%2F%2F%20Error%20%E2%9C%85%0D%0A%0D%0Ahoc(a%20%3D%3E%20(%7B%20...a%2C%20b%3A%2010%20%7D))%20%2F%2F%20No%20Error%20%E2%9D%8C%0D%0A)

**Comment by mhegazy** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/12632

**Comment by ccorcos** [comment]
Thanks!
