### ISSUE TITLE
Include TypeChecker in TransformationContext so that custom transformers can use type information

### ISSUE THREAD

**Issue by kimamula** [Microsoft/TypeScript#25147]
## Search Terms

customTransformers, custom transformers

## Suggestion

Though there are several module bundler plugins that support custom transformers, such as [ts-loader](https://github.com/TypeStrong/ts-loader), [awesome-typescript-loader](https://github.com/s-panferov/awesome-typescript-loader), [parcel-plugin-typescript](https://github.com/fathyb/parcel-plugin-typescript), [rollup-plugin-typescript2](https://github.com/ezolenko/rollup-plugin-typescript2), currently some of them cannot accept custom transformers that require `TypeChecker`.
Including `TypeChecker` in `TransformationContext` resolves this issue.

## Use Cases

ts-loader, for example, currently supports custom transformers by providing [`getCustomTransformers`](https://github.com/TypeStrong/ts-loader#getcustomtransformers-----before-transformerfactory-after-transformerfactory--) option whose type is `() => { before?: TransformerFactory[]; after?: TransformerFactory[]; }`.
It is not possible to use custom transformers that require `TypeChecker` such as [ts-transformer-keys](https://github.com/kimamula/ts-transformer-keys) (it actually requires `Program` but can be rewritten so that it only requires `TypeChecker`) with ts-loader.

Though awesome-typescript-loader and rollup-plugin-typescript2 supports such custom transformers 
by passing `Program` or `LanguageService`, respectively, to the callback corresponding to  `getCustomTransformers` in ts-loader, I found that it is difficult to modify ts-loader's code so that it can also pass `Program` or `LanguageService` (or `TypeChecker`) to the callback.

## Examples

Using ts-transformer-keys with ts-loader as described above.

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
  * Depends on the behavior of custom transformers to use, but at least TypeScript itself does not need to emit different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by mhegazy** [comment]
The type checker is intentionally separated from the transformation process. the rational is that two processed do not need to be serialized. e.g. to get the errors in your editor, you do not need to transform the code, and to transform a single file (`ts.transformModule`) you do not need to type check the whole project.

That said, you can capture the checker from the compiler API. i do not recommend making any type-directed emit transforms though.

**Comment by kimamula** [comment]
As TypeScript does not provide a functionality to emit JS based on the types of the expressions, implementing custom transformers that depend on `TypeChecker` is the only way for developers to achieve that functionality.
Therefore, I believe this is one of the most common use cases of custom transformers. Angular also implements and uses such custom transformers.
Providing `TypeChecker` as a property of `TransformationContext` is helpful to use such custom transformers.

**Comment by gfx** [comment]
I'd like this issue to be re-opened.

Custom transformers with TypeChecker give us the power to extend the TypeScript language itself.

**Comment by dsherret** [comment]
How would this be implemented properly? Isn't it possible for the type checker to be out of date due to other transformations?

For example, doing this in a transform outputs `number` both times:

```ts
console.log(typeChecker.typeToString(typeChecker.getTypeAtLocation(declaration))); // number
ts.updateVariableDeclaration(declaration, declaration.name, ts.createTypeReferenceNode("Date", undefined), undefined);
console.log(typeChecker.typeToString(typeChecker.getTypeAtLocation(declaration))); // number
```

**Comment by nonara** [comment]
@dsherret Absolutely right. The current design passes one sourcefile at a time into a transformer function chain, which means it would require a redesign to process each sourcefile in the project into one transformer with a new Program instance per each transformer.

This wouldn't be a difficult change to make, however I'm wondering about the expense of creating a Program instance. It seems to me that ts.transform() isn't creating a Program instance at all. (Can anyone confirm?) I assume this design choice is largely performance related, as not all transformers will use a TypeChecker, so recreating one each time would be unnecessarily expensive.

What could work would be to change the transform process from the one file at a time in a transformer chain to each file in the bundle passing to one transformer before moving to the next. This coupled with passing the current state of transformed SourceFiles to the context should allow the transformer to selectively create a CompilerHost which feeds the updated files to a new Program instance which would have an up to date TypeChecker.

Considering that there are many cases where people do use typechecking during transform, I do think it could be a valid change without breaking anything or slowing down the process. It would also be a very simple change. I will likely be adding something like this to ts-patch.

That said, would a PR with the proposed changes be considered? I'd be happy to submit one for review!
