### ISSUE TITLE
Potential bug in complex self-referencing type

### ISSUE THREAD

**Issue by babakness** [Microsoft/TypeScript#25143]
Hello,

The below implementation of the `makeTrouble` method will slow Typescript IDEs down to a crawl and result in what I believe is the wrong type being calculated. If in this example all references and uses of `makeTrouble` are commented out, the buggy sluggishness goes away and the all is fine. Basically everything works except the last type of `foo3` should be `Maybe<number>` not `Maybe<Maybe<number>>`

Here is the relevant code

**Code**

```typescript
const Maybe = {
    of: <A>(a: A): Maybe<A> => {
    return isNully(a) ? new Just(a) : nothing
  }
}

// classes
class Just<A> { 
    readonly _A!: A
    constructor(readonly value: A) {}
    fold<B>(whenNothing: B, whenJust: (a: A) => B): B {
        return whenJust(this.value)
    }
    map<B>(fn: (a: A) => B): Maybe<B> {
        return Maybe.of(fn(this.value))
    }
    makeTrouble<B>(fn: (a: A) => B): Maybe<B> {
        return flatten(Maybe.of(fn(this.value)))
    }
}
class Nothing<A> { 
    readonly _A!: A
    static value: Maybe<never> = new Nothing()
    private constructor( ) { }
    fold<B>(whenNothing: B, whenJust: (a: A) => B): B {
        return whenNothing
    }
    map<B>(fn: (a: A) => B): Maybe<B> {
        return nothing
    }
    makeTrouble<B>(fn: (a: A) => B): Maybe<B> {
        return nothing
    }
}

// types
export type Maybe<A> = Nothing<A> | Just<A>

export type IsNestedMaybe<T> = T extends Maybe<Maybe<any>> ? 'T' : 'F'
  
export type Flatten<T extends Maybe<any>> = {
    T: Flatten<T['_A']>
    F: T
}[IsNestedMaybe<T>]


// values
const nothing = Nothing.value

// functions
const isNully = a => a === undefined || a === null || ( typeof a === 'number' && isNaN( a ) )
const isMaybe = <A>( obj : Maybe<A> | any ): obj is Maybe<A>  => {
  return ( obj instanceof Just )
}

function flatten<T extends Maybe<any>>(x: T): Flatten<T> {
    return x.fold(x, a => {
      if (isMaybe(a)) {
        return flatten(a)
      }
      return x
    })
}

export const head = <A>( arr : A[] ) => arr[ 0 ]
export const safeHead = <A>(as: Array<A>): Maybe<A> => {
  return isNully(as) ? nothing : new Just(head(as))
}

// Example 1 -- everything works

const foo1 = Maybe.of([1, 2, 3])
    .map(safeHead)
// foo1 :: Maybe<Maybe<number>>
const foo2 = flatten( foo1 )
// foo2 :: Maybe<number>

// Example 2 -- wat?

const foo3 = Maybe.of([1, 2, 3])
    .makeTrouble(safeHead)
// foo3 :: Maybe<Maybe<number>>  
// expecting Maybe<number>
```

**Expected behavior:**

No slow downs, no bugs and `foo2` in Example-2 above to be:

`foo3 :: Maybe<number>`

**Actual behavior:**

So long as the `makeTrouble` lives, this code is super buggy and slow. Wrong type returned

`foo3 :: Maybe<Maybe<number>>`

**Playground Link:**  

problem link: (slow editor when making changes, try coding on this page to see what I mean)
https://tinyurl.com/y87msluv

remove `makeTrouble` and everything works smoothly, see link:
https://tinyurl.com/y922gowu

**Related Issues:** 

No idea

**Comment by RyanCavanaugh** [comment]
Is this the smallest possible repro?

**Comment by babakness** [comment]
Given the need to show where it works and where it fails, its very close to being the smallest.

**Comment by mhegazy** [comment]
The type seems right to me. `makeTrouble` wraps the return type of its parameter in a `Maybe`. `safeHead` returns a `Maybe<number>` given a `number[]`. so seems right that the final type is `Maybe<Maybe<number>>`.

Did you mean to define `makeTrouble` argument to return `Maybe<B>` instead of just `B`?

```ts
    makeTrouble<B>(fn: (a: A) => Maybe<B>): Maybe<B> {
        return flatten(Maybe.of(fn(this.value)))
    }
```
