### ISSUE TITLE
Should prepended project references be recursive?

### ISSUE THREAD

**Issue by RyanCavanaugh** [microsoft/TypeScript#25164]
After restructuring the `src` folder for project references, we followed the simple rule that we *wouldn't* generated concatenated outputs for "non-terminal" (e.g. library only / non-entry-point) projects. Concatenation only occurs for "endpoint" projects - `tsc`, `tsserver`, etc; i.e. those that produce a runnable program where it would make no sense to tack on additional code after these critical top-level statements. This is good for build speed because changing a variable name in `checker` only requires rewriting of its own output file plus the output files of  the endpoint projects (`tsc`, `tsserver`, etc).

The downside is that the endpoint tsconfig files look really goofy because they have to explicitly list out all their dependencies. It's also a maintainability problem because the *ordering* of those dependencies matters and doesn't get enforced by any mechanism.

The proposal was that "prending should be recursive". This is intuitive. Let's consider some examples

```
Legend
⇗ ⇑ ⇖ prepending reference
↗ ↑ ↖  non-prepending reference
```

First up, a straightforward project:
```
C
↑
B
⇑
A
```
The current behavior is that `A` emits a file containing `B A`.
It seems like we want the file `C B A`! To get `C B A`, the `A` config file now instead has to explicitly list `A` as a dependency, and has to list it above `B` to guarantee that the program will work.

Dependencies imply thinking about a diamond graph, of course:
```
   D
 ↗  ↖
B    C
 ⇖ ⇗
  A
```
The desired output is `D B C A` and we can easily construct that ordering.

What about this case?
```
   D
 ⇗  ⇖
B    C
 ⇖ ⇗
  A
```
B produces `D B` and C produces `D C`, so there's no way for `A` to produce anything other than `D B D C A`, which is not likely to load correctly due to the duplication of `D`.

We generally believe this to be an error - the graph is "fixed" by making new targets B2 and C2:
```
     ⇗ D ⇖
   ⇗ ↗  ↖ ⇖
 ⇗  B    C  ⇖
B2⇗  ⇖ ⇗  ⇖C2
      A
```

What about this graph?
```
  Q
↗  ↖
X   Y
⇑   ⇑
B   C
```
According to the "prepend should be recursive" principle, the outputs of `B` and `C` are "supposed" to be `Q X B` and `Q Y C`...

but consider dependencies of `B` and `C`:
```
  Q
↗  ↖
X   Y
⇑   ⇑
B   C
⇖ ⇗
 A
```
Now `A` has no valid output... but `B` and `C` aren't taking prepending references on `Q` on purpose.

The "fixed" version of the graph leaves us back where we started, because the new project B2 would have to explictly list `Q`, `X`, and `B` as its prepended inputs.

**Comment by RyanCavanaugh** [comment]
@mhegazy @ahejlsberg I'm leaning toward keeping references the way they are. Given that both options lead to situations where you have to re-list dependencies, being able to look at a config file and know exactly what its output will be seems like a better option?

**Comment by billti** [comment]
Your statement after the first example; "`the A config file now instead has to explicitly list A as a dependency`" meant to finish with `list C as a dependency`, right?

Also, I don't think the B2/C2 graph fixes that issue, as building A still doesn't include D. (A would probably want to reference B2/C. Or just leave B as a prepending reference).

In general though, I agree. The current solution, while not ideal, seems to have less foot-guns. Though of course having to repeat configuration is multiple places is a foot-gun of its own. In practice, would these diamond patterns likely occur? Or would they be rare enough we could live with the danger level, and most dependencies would be a straight-line superset (e.g. tsc contains most of the compiler source, then typescriptServices references tsc and a few additional files, then tsserver references typescriptServices and a few additional files, etc...)
