### ISSUE TITLE
need export relative external module from ambient module decl.

### ISSUE THREAD

**Issue by cmichaelgraham** [Microsoft/TypeScript#2516]
I am trying to facilitate use of TypeScript with ES6-based modular set of github repos.  I am struggling with this pattern:

![ambient module situation](https://cloud.githubusercontent.com/assets/10272832/6855838/469991a4-d3c1-11e4-8781-46f7342bb503.jpg)

typescript compiler wont allow `export declaration in an ambient external module declaration that references an external module through relative external module name`

the repos use `systemjs` and `jspm` to resolve `aurelia-metadata`.  i want to use ambient module declarations to expose the types from `aurelia-metadata`

what i'm trying to achieve is effectively the same as copying the contents of `origin.d.ts`, `resource-type.d.ts`, and `metadata.d.ts` into the ambient module declaration in `aurelia.d.ts`.

note that `./metadata/index.js` basically publishes the public interface through its exports, and that is precisely what i want to expose in the ambient module declaration

**Comment by mhegazy** [comment]
silly question, what is the problem with calling the module "metadata/index" instead of "./metadata/index"?

The problem is given this definition:
```ts
declare module "aurelia-metadata" {
     export * from "./metadata/index"
}
```
that it is not clear were the "./" is relative too. is it relative to the current file (.d.ts) the referencing .ts file? or something else?

**Comment by cmichaelgraham** [comment]
will that work if the contents of ./metadata/index.js are as shown above?

**Comment by cmichaelgraham** [comment]
i could surrender and manually copy the info from the compiler-generated origin.d.ts, resource-type.d.ts, and metadata.d.ts into the ambient module declaration, but have been trying to find a way to just expose what is exported in index.d.ts, as that is the public api for the module in the repo.

the issue with the manual approach is that there are already 20+ libraries, they will continue to grow, and if updating the api can't be done using the compiler, i will be forever tracking the changes in the repos and updating the api manually.

**Comment by basarat** [comment]
Assuming you have: 

```ts
declare module 'aurelia/origin' {
    export class Origin {
    }
}
```
You can import / reexport it as: 
```ts
/// <reference path="./origin/origin.d.ts"/>
declare module 'aurelia' {
    export * from 'aurelia/origin';
}
```

--- 

Verified from usage: 
```ts
/// <reference path="./aurelia"/>

import {Origin as Origin1} from "aurelia/origin";
import {Origin as Origin2} from "aurelia";
```

# In short

Tell me *exactly* the TS you want to write i.e. the Usage and then we can come up with a definition for it. :heart:

**Comment by basarat** [comment]
@cmichaelgraham note that my files exist online for your testing https://github.com/TypeStrong/atom-typescript-examples/tree/master/externalModulesDefinition

**Comment by cmichaelgraham** [comment]
i will perform additional validation today, but your guidance made it possible to build the .d.ts files using gulp-typescript and then incorporate the results into ambient module declarations shown [here](https://github.com/cmichaelgraham/aurelia-typescript/tree/master/aurelia-ts-lib/aurelia-ts/output-gulp)

i am VERY grateful for your help !!! :smile:

**Comment by cmichaelgraham** [comment]
For any interested parties, here is a public github repo that illustrates the working compiler results.  Thanks to @basarat for the guidance !!

# [aurelia-ts-lib](https://github.com/cmichaelgraham/aurelia-ts-port)

> a spike to attempt to port aurelia code into typescript

The process is to take the ES6 Aurelia source code, maintain a local copy here for comparison when porting across new code changes:
[aurelia repo source code](https://github.com/cmichaelgraham/aurelia-ts-port/tree/master/aurelia-latest)

Using the source from above, the next step in the process is to create equivalent, matching typescript source code by copying `.js` files and renaming them `.ts` extension, making small edits to make the typescript compiler happy, and as an added bonus, adding typescript type annotations for the public api:
[aurelia repo typescript-converted source code](https://github.com/cmichaelgraham/aurelia-ts-port/tree/master/aurelia-ts)

The (gulp-based) build process then compiles the typescript aurelia source code, creating the `.d.ts` files that consist of only the type definitions.  In addition, the `.js` files in ES6 format are created also.  These files can hopefully be used by `babel compiler` to produce ES6 modules in `register` format.
[build output](https://github.com/cmichaelgraham/aurelia-ts-port/tree/master/aurelia-ts/output-gulp)

## clone and build

1. clone this repo
2. run `git bash` shell, change to the main folder
3. change to `aurelia-ts` folder
4. run `npm install`
5. change to `node_modules/typescript` folder
8. run `npm install`
9. run `npm install -g jake` (if you haven't already)
10. run `jake local`
11. run `jake LKG`
12. change back to `aurelia-ts` folder
13. run `gulp build`

you should now see folders in the `output-gulp` folder.  each of these folders should contain `.d.ts` and `.js` files from the build.

## process steps - to add aurelia repos (or add new files):

1. run `./get-latest.sh`
    > this is a `git bash` script to help keep the aurelia-latest up to date

  1. clones aurelia repos into `aurelia-latest-repos`
  2. copies `src` folder from each repo into corresponding folder in `aurelia-latest`
3. manually copy `.js` files from `aurelia-latest` into `aurelia-ts` (rename each to `.ts`)
4. update `gulpfile.js`
5. if it is a new repo, add the <repo>.d.ts file in `output-gulp`

**Comment by mhegazy** [comment]
thanks @cmichaelgraham for sharing. I would be interested to know how did the conversion process go? what are the issues you ran into?

**Comment by cmichaelgraham** [comment]
I struggled a bit figuring out the right combination of files and configuration settings.  The TypeScript 1.5 compiler is beautiful, in my opinion.  The ES6 code syntax ports over very well.  It would also probably be helpful to have some guidance on what `.d.ts` files provide with the TypeScript repo should be used in various situations.  Some sort of mapping from types to `.d.ts` files.  I had some issues figuring out where ES6 Promises might be defined.

Overall, this is right on target.

I do think some tooling would be useful - if I could say: "generate an ambient `.d.ts` file for `metadata/index`, for example, and it would round up the types an place them in a single ambient module definition (including comments).  Right now it is spread out over several `.d.ts` files, but it does work as is.

**Comment by mhegazy** [comment]
thanks @cmichaelgraham for the feedback. i have created issue #2568 to track the single declaration file generation.

**Comment by basarat** [comment]
@cmichaelgraham FWIW atom-typescript now has integrated `dts-generator` and all it needs is the path to your `package.json`. It takes care of the rest for your *automatically* : https://github.com/Microsoft/TypeScript/issues/2829  

Both *exporting* and *importing* should **just work** :tm: .
