### ISSUE TITLE
extending imported abstract classes fails at execution time

### ISSUE THREAD

**Issue by cancerberoSgx** [Microsoft/TypeScript#25173]
I'm attaching a very simple example you can execute it both with `ts-node src/index.ts` or with `tsc && cd dist && node src/index.js`

[tsissue12.zip](https://github.com/Microsoft/TypeScript/files/2130102/tsissue12.zip)

Expected behavior:execute successful
Actual behavior: Error : `TypeError: Class extends value undefined is not a constructor or null`

I'm using typescript@next and `strict: true`

**I think this is an issue because, if instead of extending from an imported abstract class I extend without importing it it won't fail.**

**Comment by cancerberoSgx** [comment]
OK this is not an issue, sorry, I'm closing it. My error was using commonsjs for module and moduleResolution and importing the class at the top of the file so I didn't give time to the dependency to run the declaration. Using other moduleResolution like AMD or moving the import to the bottom solve it. Sorry for the noise

**Comment by juancancela** [comment]
@cancerberoSgx  Thanks! really helpful

**Comment by electrotype** [comment]
Similar error for me. I splitted one the problematic file into two and it worked. Indeed retlated to import order.
