### ISSUE TITLE
Report error on labeled functions and generator functions

### ISSUE THREAD

**Issue by ajafff** [Microsoft/TypeScript#25183]
**TypeScript Version:**  2.9.2, 3.0.0-dev.20180621

**Search Terms:** label function

**Code**

```ts
// @target: ES2017
label: function fn() {}
label: function* gen() {}
```

**Expected behavior:**

Error on the labeled generator function.
Error on the labeled function in strict mode.

Starting with ES2015 this is a syntax error.
http://www.ecma-international.org/ecma-262/6.0/#sec-labelled-function-declarations

**Actual behavior:**

No error. Since v3.0.0 `Unused label` errors are only reported as suggestion diagnostics, therefore there is no error at all.

**Playground Link:** https://agentcooper.github.io/typescript-play/?allowUnusedLabels=true#code/DYQwRgpsBcAEBmBXAdgYwC4EsD2yHIAoBKWAbwF8AoUSGBFDHZAKlgHMJCTTLY-YAnpigATANyVyQA

**Related Issues:**

**Comment by mhegazy** [comment]
PRs welcomed.
