### ISSUE TITLE
How to get rid of "Exported variable has or is using name from external module but cannot be named" errors when I want to heavily rely on type inference

### ISSUE THREAD

**Issue by pleerock** [Microsoft/TypeScript#25188]
One of the most annoying error I face when I want to rely on type inference and have all beauty of TypeScript...

Currently [TypeORM](https://github.com/typeorm/typeorm) use classes and decorators to create a representation of a database schema for a model. I would like to introduce a new, more JavaScript-ish API and define a schema creation interface this way:

```ts
export const Post = createEntity({
    columns: {
        id: {
            type: Number
            // other id-column related properties...
        },
        title: {
            type: String
        },
        text: {
            type: String
        },
        author: {
            firstName: {
                type: String
            },
            lastName: {
                type: String
            },
            age: {
                type: Number
            }
        }
    }
});

const post: typeof Post = {
    id: 1,
    title: "Hello",
    text: "wow",
    author: {
        firstName: "yo",
        lastName: "wow",
        age: 30
    }
};
```

And I just started to implement `createEntity` function and did it this way:

```ts

export type ColumnOptions<T> = {
    type: StringConstructor | BooleanConstructor | NumberConstructor | DateConstructor;
};

export type EntitySchemaColumnOptions<T> = {
    [key: string]: ColumnOptions<T> | EntitySchemaColumnOptions<T>;
};

export type EntitySchemaOptions<T> = {
    columns: EntitySchemaColumnOptions<T>;
};

export type InferredEntityType<T extends EntitySchemaColumnOptions<T>> = {
    [P in keyof T]:
        T[P] extends {
            type: StringConstructor | BooleanConstructor | NumberConstructor | DateConstructor;
        } ?
            T[P]["type"] extends StringConstructor ? string :
            T[P]["type"] extends BooleanConstructor ? boolean :
            T[P]["type"] extends NumberConstructor ? number :
            T[P]["type"] extends DateConstructor ? Date :
            never
        : T[P] extends EntitySchemaColumnOptions<T> ? InferredEntityType<T[P]> : never;

};

export function createEntity<O extends EntitySchemaOptions<T>, T>(options: O): InferredEntityType<O["columns"]> {
    // todo 
}
```

but having this annoying `Error:(3, 14) TS4023: Exported variable 'Post' has or is using name 'InferredEntityType' from external module "x" but cannot be named.` error.

Definitely I don't want to specify any types for entity schema explicitly. Can someone please help me to find a solution to this issue?

**Comment by nsh-core** [comment]
why would you not want to define types on an entity? This is one of most easily understandable benefits of typed java script, you have an entity that is going to be stored in a database that is heavily type oriented. If you want to use a javascript API why not use API and not typescript?

**Comment by mhegazy** [comment]
This should be working in TS 2.9 and later using `import` types.
