### ISSUE TITLE
create an instance from class extends null is allowed but it should not

### ISSUE THREAD

**Issue by Kingwl** [Microsoft/TypeScript#25187]
**TypeScript Version:**  3.0.0-dev.201xxxxx

**Search Terms:** 

**Code**

```ts
class A extends null { }

new A()
```

**Expected behavior:**

Uncaught TypeError: Super constructor null of A is not a constructor

**Actual behavior:**

everything is ok

**Playground Link:**  

https://www.typescriptlang.org/play/index.html#src=class%20A%20extends%20null%20%7B%20%7D

**Related Issues:**

**Comment by mhegazy** [comment]
This looks like a bug in the runtime. An ES2015 class can extend `null`.

See spec definiton of evaluating `null` heritage clauses: https://www.ecma-international.org/ecma-262/6.0/#sec-runtime-semantics-classdefinitionevaluation
And MDN docs: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/extends#Extending_null

**Comment by Kingwl** [comment]
https://github.com/tc39/ecma262/issues/1036
