### ISSUE TITLE
Decorator `design:type` emit fails to resolve TypeVariable objects

### ISSUE THREAD

**Issue by mprobst** [Microsoft/TypeScript#25189]
**TypeScript Version:**  3.0.0-dev.201xxxxx (current master)

**Search Terms:** decorator design:types variable undeclared

**Code**

```ts
// @experimentalDecorators: true
// @emitDecoratorMetadata: true

// Unused, but could collide with the named type argument below.
class TypeVariable {}

export class C<TypeVariable = string> {
  @Decorate
  member: TypeVariable;
}
```

**Expected behavior:**

Emit something like:

```js
// Unused, but could collide with the named type argument below.
var TypeVariable = /** @class */ (function () {
    function TypeVariable() {
    }
    return TypeVariable;
}());
var C = /** @class */ (function () {
    function C() {
    }
    __decorate([
        Decorate,
        __metadata("design:type", Object)
    ], C.prototype, "member");
    return C;
}());
exports.C = C;
```

**Actual behavior:**

```js
// Unused, but could collide with the named type argument below.
var TypeVariable = /** @class */ (function () {
    function TypeVariable() {
    }
    return TypeVariable;
}());
var C = /** @class */ (function () {
    function C() {
    }
    __decorate([
        Decorate,
        __metadata("design:type", TypeVariable)
    ], C.prototype, "member");
    return C;
}());
exports.C = C;
```

**Playground Link:**

Does not reproduce on the playground, possibly introduced in TS 2.9.2?

http://www.typescriptlang.org/play/#src=%2F%2F%20%40experimentalDecorators%3A%20true%0D%0A%2F%2F%20%40emitDecoratorMetadata%3A%20true%0D%0A%0D%0A%2F%2F%20Unused%2C%20but%20could%20collide%20with%20the%20named%20type%20argument%20below.%0D%0Aclass%20TypeVariable%20%7B%7D%0D%0A%0D%0Aexport%20class%20C%3CTypeVariable%20%3D%20string%3E%20%7B%0D%0A%20%20%40Decorate%0D%0A%20%20member!%3A%20TypeVariable%3B%0D%0A%7D%0D%0A

**Comment by mhegazy** [comment]
Fixed by https://github.com/Microsoft/TypeScript/pull/25190#pullrequestreview-132204405
