### ISSUE TITLE
Code fixes for syntax errors

### ISSUE THREAD

**Issue by andy-ms** [microsoft/TypeScript#25201]
**TypeScript Version:**  3.0.0-dev.20180623

**Code**

```ts
const o = { a: 1; b: 2 };
```

**Expected behavior:**

Get a quick fix to replace `;` with `,`.

**Actual behavior:**

No fix. Similar for `{ a: 1 b: 2 }`.

**Comment by mhegazy** [comment]
The problem with these is that we will have to add parsing support for these patterns to be able to fix them. so there is a limited set of patterns that we can support.

That said, we should be able to support he missing `,` errors listed above.

**Comment by akoserwal** [comment]
@mhegazy: I would like to work on this issue.  Please, can you help me with some starting pointers?

**Comment by MEXdave1997** [comment]
@akoserwal are you still working on this? I wouldn't mind helping out in finding this out.

**Comment by akoserwal** [comment]
@MEXdave1997: Initially, I spend some time, I couldn't find any starting pointers. I would like to continue on this with your help.

**Comment by andy-ms** [comment]
Code fixes go in the `codefixes` folder -- don't think changes to the parser will be needed for this as long as the diagnostic it produces is usable for a code fix.
See `fixForgottenThisPropertyAccess.ts` for a simple example.

**Comment by adeniszczyc** [comment]
Going to take a look at continuing the work of @akoserwal on this issue now
