### ISSUE TITLE
TSServer: snippet completions

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#25207]
Provide a generic, cross editor snippet type that can be used to express complex text insertion operations. At a minimum, these snippets should include placeholder values and indicate where the cursor should end up.

For example, snippets could fill in function call arguments with placeholders. If the user completes `ad` to `add` here:

```js
function add(x, y) { return x + y; }

ad|
```

The inserted snippet would be:

```js
function add(x, y) { return x + y; }

add(«x», «y»)
```

Where  the user can tab from the placeholder values `«x»` to `«y».`

**Use Cases**
- Method completions (currently implemented manually by VSCode under `useCodeSnippetsOnMethodSuggest`)
- React completions — https://github.com/Microsoft/vscode/issues/48562
- Js doc template completions
- implement overridden method

**Why is this needed**
Snippets speed up coding and provide additional hints while writing code. VS Code already tries to convert TS's existing response types to snippets but fails to handle many edge cases. In order to improve reliability and support more advanced used cases such as https://github.com/Microsoft/vscode/issues/48562, I believe that TS needs to start generating these snippets directly

**Comment by mjbvz** [comment]
I imagine that the snippet type could  similar to `SymbolDisplayPart`. Just a quick sketch:

```ts
interface Snippet {
    parts: SnippetPart[];
}

type SnippetPart = SnippetText | SnippetPlaceholder;

interface SnippetText {
    kind: 'text'
    text: string
}

interface SnippetPlaceholder {
    kind: 'placeholder'
    text: string
}
```

For completions, the snippet could be new optional additional field on `CompletionEntry`. That way we don't break clients that do not support snippets.

**Comment by mjbvz** [comment]
Another possible use case that we discussed: refactorings such as extract constant. We currently implement this by triggering a rename after the extraction but a snippet could be a better fit. Example:

```js
const three = 1 + 2;
```

Run extract constant on `2`. This could generate a placeholder that is duplicated twice in the file:

```j
const «newLocal» = 2
const three = 1 + «newLocal»;
```

Typing would update both locations

(Note that VS Code's api would not support this currently since the placeholders are at unconnected locations in the file)

**Comment by mhegazy** [comment]
> Typing would update both locations

but is not that what rename does today?

**Comment by mjbvz** [comment]
Another possible use case: generate complete method signature when overriding a method in a subclass https://github.com/Microsoft/vscode/issues/46038

**Comment by bpasero** [comment]
Inspiration from Eclipse. Notice how the one tab stop for the method name is even linked!

![recording](https://user-images.githubusercontent.com/900690/81471872-8b19e800-91f4-11ea-9743-fd1cb36bb864.gif)

**Comment by mjbvz** [comment]
Yes I'll can close this since these already snuck in :)
