### ISSUE TITLE
Using "resolveJsonModule: true" causes drastic compilation error

### ISSUE THREAD

**Issue by ORESoftware** [Microsoft/TypeScript#25216]
I am on: `Version 2.9.1`

So I have this project, with `lib` and `dist` and `"outDir":"dist"` and `"include": ["lib"]` ...
that means the only thing that ends up in dist, should be what's in lib, right?

https://github.com/ORESoftware/npm-link-up

This project has a single straightforward tsconfig.json file.

How to replicate the problem :

> 1. git clone https://github.com/ORESoftware/npm-link-up.git
> 2. rm -rf dist
> 3. tsc 
> 4. dist should have some 20+ files in it. These files are the correct files.
> 5. rm -rf dist
> 6. change  `"resolveJsonModule": false`, to  `"resolveJsonModule": true`
> 7. tsc
> 8. now dist should have about 3 files in it.   These files are the *incorrect* files.

I would assume that  `"resolveJsonModule": true` would not do that much except allow you to do:

```js
import json = require('../../my.file.json');
const jsonType = typeof json;
```

I don't see why it should have such a drastic affect on what goes from lib into dist.

**Comment by mhegazy** [comment]
when you use `"resolveJsonModule": true` you are telling the compiler to include the `.json` files imported from your `.ts` files as part of your project. the files will be emitted to the output, just like all your `.ts`/`.tsx` files. 

The addition of new files not under `lib` results in the output folder structure changing.. see more details about this in https://github.com/Microsoft/TypeScript/wiki/FAQ#why-does---outdir-moves-output-after-adding-a-new-file
