### ISSUE TITLE
factory: getLeftmostExpression needs to handle more kinds

### ISSUE THREAD

**Issue by ajafff** [Microsoft/TypeScript#25223]
**TypeScript Version:**  3.0.0-dev.20180621

**Search Terms:** 

**Code**

```ts
import * as ts from 'typescript';
const n = ts.createStatement(ts.createAsExpression(ts.createObjectLiteral(), ts.createTypeReferenceNode('any', undefined)));
ts.createPrinter().printNode(ts.EmitHint.Unspecified, n, ts.createSourceFile('dummy.ts', '', ts.ScriptTarget.Latest));
```

**Expected behavior:**

`({} as any);`

The same applies to `NonNullExpression`.

**Actual behavior:**

Invalid code, this is a syntax error: `{} as any;`

**Comment by mhegazy** [comment]
PRs welcomed.

**Comment by DanielRosenwasser** [comment]
I'm surprised we're even making transformations with the printer. Are you sure you're not running this through a transform first?

**Comment by ajafff** [comment]
@DanielRosenwasser the printer doesn't do anything special here. It's the factory function (in this case `createStatement`) that adds parentheses if necessary. Except for the example above where no parens are added.

Instead of using the printer, one could also just use `isParenthesizedExpression(n.expression)`

**Comment by DanielRosenwasser** [comment]
Gotcha, thanks!
