### ISSUE TITLE
Add Program.isSourceFileDefaultLibrary to public API

### ISSUE THREAD

**Issue by timocov** [Microsoft/TypeScript#25225]
## Search Terms

API, Program

## Suggestion

Is there a chance to add `isSourceFileDefaultLibrary` to `Program`s API?

For now, it is marked as `@internal` and this method is removed from declaration file https://github.com/Microsoft/TypeScript/blob/70975cd08f48497f3ae6538ff69bf50cac23706b/src/compiler/types.ts#L2777

## Use Cases

I working on https://github.com/timocov/dts-bundle-generator and there I need to know what files are default lib files. I need to know it to skip these files from preparing. It seems that is the right way to detect it, but it is not public.

If there is another way to check that some file is default lib file - please let me know.

Related to https://github.com/timocov/dts-bundle-generator/issues/39.

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by timocov** [comment]
@ajafff In my case, I need to know only if a file is default lib file, but anyway thanks for the additional information!

**Comment by ajafff** [comment]
In that case you could simply compare to `ts.getDefaultLibFilePath(program.getCompilerOptions())`

**Comment by timocov** [comment]
It seems that `ts.getDefaultLibFilePath(program.getCompilerOptions())` returns only one default lib file - `lib.d.ts`, but I need to check every lib file (e.g. `lib.es2015.d.ts` or `lib.es2017.d.ts`).

**Comment by timocov** [comment]
I guess there is some misunderstanding - I need to filter all lib files (I thought it called "default lib files"). `Program.isSourceFileDefaultLibrary` does exactly what I need and I believe any other solution is not entirely correct because only compiler knows what is default library file and what is not.

Of course, we can create one more solution (with checking the path of the file or something else), but compiler knows it already, so why I need to do its work?  🙂

**Comment by timocov** [comment]
> You might want to do the path comparison yourself:

But in this case, we'll filter `typescript.d.ts` file and this is not what I want to.

> is probably not what you are looking for

Why not? As far as I understand it checks that file is `lib.xxx.d.ts` file, doesn't it?

https://github.com/Microsoft/TypeScript/blob/bd97e12f760773aac87d62159fa26ea1474a2337/src/compiler/program.ts#L1291-L1309

**Comment by mhegazy** [comment]
A PR would be appreciated.
