### ISSUE TITLE
factory: doesn't always parenthesise 'yield'

### ISSUE THREAD

**Issue by ajafff** [microsoft/TypeScript#25224]
**TypeScript Version:**  3.0.0-dev.20180621

**Search Terms:** 

**Code**

```ts
import * as ts from 'typescript';

/* 1 */
let n = ts.createBinary(ts.createIdentifier('foo'), ts.SyntaxKind.AsteriskAsteriskToken, ts.createYield());
ts.createPrinter().printNode(ts.EmitHint.Unspecified, n, ts.createSourceFile('dummy.ts', '', ts.ScriptTarget.Latest));

/* 2 */
n = ts.createAsExpression(ts.createYield(), ts.createTypeReferenceNode('T'));
ts.createPrinter().printNode(ts.EmitHint.Unspecified, n, ts.createSourceFile('dummy.ts', '', ts.ScriptTarget.Latest));

```

**Expected behavior:**

1: `foo ** (yield)`
Note that this works as expected when using `AmpersandAmpersandToken`.

2: `(yield) as T`
Note that this works when using `TypeAssertionExpression`

**Actual behavior:**

Invalid code, this is a syntax error:

1: `foo ** yield`
2: `yield as T`

**Comment by mhegazy** [comment]
Not sure why you expect the factory to do this work. i think you should explicitly parenthesize.

**Comment by mhegazy** [comment]
never mind, we should parenthesize. PRs welcomed.

**Comment by RyanCavanaugh** [comment]
The API is significantly different now; please open a new issue if this is still a problem.
