### ISSUE TITLE
When using async-await on a function has an inferred type Promise<SomeType>, no compile errors. 

### ISSUE THREAD

**Issue by galziv** [Microsoft/TypeScript#25227]
**Code**

```ts
interface User {
  id: string;
  name: string;
}

interface UsersMap {
  [userId: string]: User;
}

(async function () {

  function someFuncInferred() {
    return new Promise(resolve => {
      const map: UsersMap = {};
      resolve(map);
    })
  }

  function someFunc(): Promise<UsersMap> {
    return new Promise(resolve => {
      const map: UsersMap = {};
      resolve(map);
    })
  }

  const inferredUser = await someFuncInferred();
  inferredUser["id"] = 123; // no error!

  const explicitUser = await someFunc();
  explicitUser["id"] = 123 // Type '123' is not assignable to type IActiveUser


}());
```

**Expected behavior:**
error when type has a mismatch as in the explicit return type

**Actual behavior:**
no error on compile

**Playground Link:** 
http://www.typescriptlang.org/play/index.html#src=interface%20User%20%7B%0D%0A%20%20id%3A%20string%3B%0D%0A%20%20name%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20UsersMap%20%7B%0D%0A%20%20%5BuserId%3A%20string%5D%3A%20User%3B%0D%0A%7D%0D%0A%0D%0A(async%20function%20()%20%7B%0D%0A%0D%0A%20%20async%20function%20someFuncInferred()%20%7B%0D%0A%20%20%20%20const%20map%3A%20UsersMap%20%3D%20%7B%7D%3B%0D%0A%20%20%20%20return%20map%3B%0D%0A%20%20%7D%0D%0A%0D%0A%20%20function%20someFunc()%3A%20Promise%3CUsersMap%3E%20%7B%0D%0A%20%20%20%20return%20new%20Promise(resolve%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20const%20map%3A%20UsersMap%20%3D%20%7B%7D%3B%0D%0A%20%20%20%20%20%20resolve(map)%3B%0D%0A%20%20%20%20%7D)%0D%0A%20%20%7D%0D%0A%0D%0A%20%20const%20inferredUser%20%3D%20await%20someFuncInferred()%3B%0D%0A%20%20inferredUser%5B%22id%22%5D%20%3D%20123%3B%20%2F%2F%20no%20error!%0D%0A%0D%0A%20%20const%20explicitUser%20%3D%20await%20someFunc()%3B%0D%0A%20%20explicitUser%5B%22id%22%5D%20%3D%20123%20%2F%2F%20Type%20'123'%20is%20not%20assignable%20to%20type%20IActiveUser%0D%0A%0D%0A%0D%0A%7D())%3B

**Comment by MartinJohns** [comment]
You should probably mention what TypeScript version you're using, because in the Playground link it results as expected in a compilation error.

**Comment by mhegazy** [comment]
The return type of `someFuncInferred` is inferred to be `Promise<{}>` since `resolve` has not type to infer from nor a contextual type. 

This makes the type of `inferredUser`: `{}`. All JS objects are indexable, so the type of `inferredUser["id"]` is `any` which is assignable from `123`.

You should see an error under `--noImplicitAny` for `inferredUser["id"]`.
