### ISSUE TITLE
factory: createExpressionStatement is internal

### ISSUE THREAD

**Issue by ajafff** [Microsoft/TypeScript#25220]
## Search Terms

`createExpressionStatement`

## Suggestion

expose `createExpressionStatement` for API users

**Comment by ajafff** [comment]
I just noticed that there is a `createStatement` which creates an `ExpressionStatement`. This is actually consistent with the inconsistencies of all the other factory functions.
Maybe the misnamed functions should be deprecated in favour of functions with a better name.

**Comment by mhegazy** [comment]
PRs welcomed.

**Comment by mhegazy** [comment]
I would expose both with a comment.
