### ISSUE TITLE
Don't suggest abstract classes for new expression 

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#25234]
_From @wehrstedt on June 26, 2018 8:51_

- VSCode Version: 1.24.1
- OS Version: Windows 10 1803

Steps to Reproduce:

1. Create an abstract class
```ts
abstract class abc {} 
```
2. Type in ```new <ctrl + space>``` => The abstract class will be suggested. If you accept the proposal, you will get an an error (abstract classes can't be instantiated)

Does this issue occur when all extensions are disabled?: Yes

_Copied from original issue: Microsoft/vscode#52878_

**Comment by mhegazy** [comment]
This is acctually working as intended. the filter for completions are not filtered, nor should they. the recommended completion however is filtered based oin the context. so for instance:

````ts
class B {
}
var b: B = new | // B should show as the selected completions
```
where as it will not in :
```ts
abstract class B {
}
var b: B = new | // B is not selected
```

**Comment by RyanCavanaugh** [comment]
We also don't know ahead of time that you're not trying to `new` a static member of `B`, so filtering it entirely would be bad
