### ISSUE TITLE
problem with type guards

### ISSUE THREAD

**Issue by lucamorelli** [Microsoft/TypeScript#2523]
Hi, I have this code

```
var test: number | string;
test = corrente.censimentoId;
if (typeof test === "number") {
    this.editedRecord = test;
}

if (typeof corrente.censimentoId === "number") {
    this.editedRecord = test;
}
```
**corrente.censimentoId** is defined **number | string** and **this.editedRecord** is defined as number: the first type guard works fine and I'm not able to to the assignment, the second one gives me this error.

![untitled](https://cloud.githubusercontent.com/assets/127777/6866700/4b7798c8-d47b-11e4-9a45-fdb7ef7ee857.png)

Am I doing something wrong?

**Comment by zhuravlikjb** [comment]
Type guards work only for local variable and parameter references, they don't work for expressions.

>Type guards are particular expression patterns involving the 'typeof' and 'instanceof' operators that cause the types of **variables** or **parameters** to be narrowed to more specific types

See the [spec](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#4.20).

**Comment by lucamorelli** [comment]
ok, thanks
