### ISSUE TITLE
Obsolete 'isRegExp' and several non-mentioned well-known symbols in lib.es6.d.ts

### ISSUE THREAD

**Issue by zhuravlikjb** [Microsoft/TypeScript#2524]
https://people.mozilla.org/~jorendorff/es6-draft.html#sec-well-known-symbols

1) `isRegExp` doesn't exist anymore
2) no mention for `match`, `replace`, `search`, `species`, `split` now

**Comment by mhegazy** [comment]
Forgot to mention that PRs are always welcomed:)

**Comment by DanielRosenwasser** [comment]
Not sure whether there's been a change in what you've mentioned, but I see `match`, `replace`, `search`, `species`, and `split` [are currently still there](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-well-known-symbols).

![image](https://cloud.githubusercontent.com/assets/972891/7074929/0c41b962-deb3-11e4-824c-8fbcd96e5ef6.png)

If you look at [Revision 29 from Dec. 6](https://github.com/rwaldron/tc39-notes/blob/7870dfb25eb8db48ea30f8c51597139451d95bff/es6/2015-01/jan2015-allen-slides.pdf):

> - Symbols `@@match`, `@@replace`, `@@search`, `@@split`, replace the corresponding string property names in `RegExp` prototype
  - Eliminate `@@isRegExp`and `Symbol.isRegExp`.

**Comment by mhegazy** [comment]
@DanielRosenwasser i think you are looking at an old version of the spec. here is the latest draft:
http://wiki.ecmascript.org/lib/exe/fetch.php?id=harmony%3Aspecification_drafts&cache=cache&media=harmony:ecma-262_edition_6_04-03-15-releasecandidate4.pdf

**Comment by DanielRosenwasser** [comment]
I'm still seeing it:

![image](https://cloud.githubusercontent.com/assets/972891/7076313/65b001e8-debd-11e4-906b-f34579d810eb.png)
