### ISSUE TITLE
Show signature help for contextual callback

### ISSUE THREAD

**Issue by ackvf** [Microsoft/TypeScript#25265]
**TypeScript Version:**  `2.9.2` and `3.0.0-dev.20180626`

**Search Terms:** 
jsx props intellisense

**Code**

```ts
import Table from 'antd/lib/table'
//...
render() {
  return (
    <Table.Column render={(){/*<- cursor between braces*/}}/>
  )
}
```

**Expected behavior:**

Expected is that intellisense for the inserted brace of an arrow gives correct param types.

_node_modules\antd\lib\table\interface.d.ts_
`render?: (text: any, record: T, index: number) => React.ReactNode;`

![image](https://user-images.githubusercontent.com/2313018/41970460-40e40ca0-7a0b-11e8-9a67-2e7b208defe4.png)

**Actual behavior:**

![image](https://user-images.githubusercontent.com/2313018/41970204-3c49d3d8-7a0a-11e8-88e4-b3e7f183d884.png)

**Playground Link:** 

https://github.com/ackvf/typescript-repro/tree/render-prop

**Related Issues:** 
https://github.com/Microsoft/TypeScript/issues/25266

**Comment by andy-ms** [comment]
I think the same situation occurs without JSX:
```ts
interface Props {
    render: (n: number) => void;
}
declare function foo(props: Props): void;
foo({ render: /**/ });
```

Delete the `/**/` and type `(`. SIgnature help will show `foo(props: Props): void`. It doesn't show the signature of the callback you're supposed to provide. Isn't that the same issue as the above?

**Comment by ackvf** [comment]
Yes @andy-ms , I guess the expected and exhibited behavior in your example is the same.
When you invoke the intellisense inside the brace `foo({/*here*/})` it does provide a hint `render: (n: number) => void`, but not when invoked inside the `render` as in your example.

**Comment by andy-ms** [comment]
Another case from #13304:

```ts
interface I {
    m(x: number): void;
}
declare function f(i: I): void;
f({ m() {} });
```

Between the `()` in `m()`, we should get the signature of `m`, not the signature of `f`.
