### ISSUE TITLE
Disable insert semicolon for import statement

### ISSUE THREAD

**Issue by chemzqm** [Microsoft/TypeScript#25267]
Many people don't use semicolon for typescript, so please consider make it possible to disable the insert semicolon feature.

## Search Terms

* semicolon
* FormatCodeSettings
* EditorSettings

## Suggestion

Add a field `insertSemicolonAfterImport` to `FormatCodeSettings` field.

## Use Cases

Currently auto import feature and organized imports feature of typescript would have semicolon inserted automatically, and can not be disabled.

## Examples

When `insertSemicolonAfterImport` is false, no semicolon should be inserted after import.

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by andy-ms** [comment]
Duplicate of #19882
