### ISSUE TITLE
Allow tsconfig to be a module, not only json

### ISSUE THREAD

**Issue by just-boris** [Microsoft/TypeScript#25271]
## Search Terms

* tsconfig js
* tsconfig as module
* tsconfig javasctipt

I have found a related question here: https://github.com/Microsoft/TypeScript/issues/9876#issuecomment-242383719. But that was not anyhow replied or addressed. So I have opened this issue.

## Suggestion

Allow `tsconfig` file to be an executable module, not only static JSON

## Use Cases

1. When I have a non-trivial project structure and I want to use `path.join(__dirname, 'path/to/file')` to generate dynamic paths
2. I have multiple projects and I would like to share the common configuration, but also I need to have a custom merging logic `extends` property doesn't work. Same also was asked there: https://github.com/Microsoft/TypeScript/issues/9876#issuecomment-242383719
3. I have configuration for other tools, (webpack, for example), and I would like to share some constants between two tools

Also there is similar features in other tools:

* [babel.config.js](https://babeljs.io/docs/en/next/babelconfigjs)
* [.eslintrc.js](https://eslint.org/docs/user-guide/configuring#configuration-file-formats)
* There is also [cosmicconfig](https://github.com/davidtheclark/cosmiconfig) package, that provides such functionality.

## Examples

***tsconfig.js***

```js
const path = require('path');
const {rootDir, commonExcludes} = require('./constants');

module.exports = {
  "exclude": commonExcludes,
  "files": [
    path.join(rootDir, 'path/to/file')
  ]
}
```

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by just-boris** [comment]
As a hacky solution for now I can generate `tsconfig.json` in runtime:

```js
const config = {/*dynamically generated config*/};
require('fs').writeFileSync('tsconfig.json', JSON.stringify(config));
```

This works for compilation, but doesn't work for editors, because they do not see actual file.

**Comment by mhegazy** [comment]
The config file is meant to be statically understood by different tools, some of them have no capability nor need to execute JavaScript. for more dynamic modifications we recommend using a build tool e.g. gulp/jake/grunt/broccoli/etc.., or directly using the compiler API.

**Comment by just-boris** [comment]
Got that, will have to stick with my workaround. 

At least there is an issue now, that someone can upvote. Thank you for taking your time!

**Comment by trusktr** [comment]
@mhegazy Do you have examples of such tools that need to statically analyze `tsconfig.json`?

I too am running into this problem, as I want to share my configuration across projects. This sort of stuff becomes easier when we get dynamic abilities.

**Comment by trusktr** [comment]
And also, if I'm not using those such tools that statically analyze tsconfig, then why can't I choose to use a JS module instead? I don't care if some tool won't be able to statically analyze my tsconfig... because I'm not using those tools...

**Comment by trusktr** [comment]
When trying to share tsconfig (and other build scripts and configs) across projects, this gets in the way in some cases if I can't use `process.cwd()` or similar to set certain paths.

**Comment by RyanCavanaugh** [comment]
>  Do you have examples of such tools that need to statically analyze tsconfig.json?

TypeScript *itself*, Visual Studio, Visual Studio Code, etc...

**Comment by DarthVitalus** [comment]
> > Do you have examples of such tools that need to statically analyze tsconfig.json?
> 
> TypeScript _itself_, Visual Studio, Visual Studio Code, etc...

Does these tools analyze js config files like webpack.config.js or babel.config.js?
WebStorm does (without passing params by default, but still)

**Comment by kenotron** [comment]
This seems to be a missed opportunity for flexibility for typescript. All those tools should be able to execute a bit of JS and have it report the config much like every other build tool config in the JS ecosystem like webpack.config.js, jest.config.js, gulp (gulpfile.js), babel (https://new.babeljs.io/docs/en/next/babelconfigjs.html). It seems like getting the config from a module is one `require` away.

**Comment by rasenplanscher** [comment]
For anybody still interested in this feature: https://www.npmjs.com/package/tsconfig.js

**Comment by dl748** [comment]
Personally I'd like to see them use the node-interpret package to determine how to load the configuration file.  I'd LOVE to be able to create a dynamic configuration file IN typescript by creating a tsconfig.ts (like webpack does webpack.config.js) and node-ts runs the module

**Comment by rasenplanscher** [comment]
@dl748 
Sounds interesting. A quick web search

**Comment by rasenplanscher** [comment]
@dl748 
Sounds interesting. If you'd like to see that in `tsconfig.js`, please open an issue there: https://github.com/rasenplanscher/tsconfig.js/issues/new

I wanted to look into this just now. A quick search the mentioned node-interpret package yielded https://github.com/gulpjs/interpret, which doesn't seem right. Please include a useful reference if you open an issue.

**Comment by dl748** [comment]
@rasenplanscher 
That is correct, it is apart of the gulpjs project but it doesn't require gulp.

See https://webpack.js.org/configuration/configuration-languages/

**Comment by rasenplanscher** [comment]
`tsconfig.js` v2 is now on npm and includes `interpret`-based transpilation 🥳🎉

@dl748 
Thanks for the info!

**Comment by dl748** [comment]
> 
> 
> `tsconfig.js` v2 is now on npm and includes `interpret`-based transpilation 🥳🎉
> 
> @dl748
> Thanks for the info!

You should add to the documentation though, that if loading other extensions like coffee or typescript, you need to make sure the required loader (e.g. coffeescript for .coffee and ts-node for .ts)

**Comment by rasenplanscher** [comment]
Good point, done 👍

**Comment by ryall** [comment]
I really see little harm in allowing dynamic configs and letting the editor decide which to use. No one is saying remove `tsconfig.json` support, so there's no breaking changes. ESLint is also an editor-compatible tool that allows dynamic imports. Right now, TS is literally the only tool I cannot configure dynamically, and it's quite frustrating, resorting to me having to use hacky methods like generating the file dynamically, which doesn't work well with editors.

**Comment by rasenplanscher** [comment]
@ryall 
Have you tried [tsconfig.js](https://www.npmjs.com/package/tsconfig.js)? If that produces issues with your editor, please [open an issue there](https://github.com/rasenplanscher/tsconfig.js/issues/new).

**Comment by ryall** [comment]
@rasenplanscher I have my own similar implementation, however that's not really the point. I think dynamic config should be part of the core architecture rather than an external library.

**Comment by lionel-bijaoui** [comment]
Since it has been almost 4 year since this issue was brought up, can we reopen the issue ? 
If ESLint is able to do it, I don't see why Typescript would be unable. 

When faced with more complex projects, the ability to define `compilerOptions.paths` dynamically is **needed**.

Can we please at least give it a shot?
Thanks

**Comment by AprilArcus** [comment]
In my monorepo, I would like to be able to dynamically derive [project references](https://www.typescriptlang.org/docs/handbook/project-references.html) from the namespaced dependencies enumerated in my `package.json`, so that `package.json` can be the single store of truth for each workspace's dependency graph.

**Comment by TowhidKashem** [comment]
My `eslintrc.js` file is full of comments RE why each rule was chosen or what it does. It would be great to be able to do the same in a `tsconfig.js` file as well. For things like obscure config rules it really helps to be able to leave comments!
