### ISSUE TITLE
Path IntelliSense for jsdoc imports types

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#25275]
https://github.com/Microsoft/vscode/issues/53093

**TypeScript Version:**  3.0.0-dev.20180626

**Search Terms:** 
- jsdoc
- import expression
- suggestions / intellisense

**Code**
For a project:

`a.ts`
```ts
export type T = number
```

`b.js`
```js
/**
 * @param {import('./')} x
 */
function foo(x) {
}
```

1. Try trigger path intellisense after the `./`

**Expected behavior:**
Path suggestions returned. This is what happens if you use import types in a ts file

![screen shot 2018-06-27 at 10 04 32 am](https://user-images.githubusercontent.com/12821956/41988834-30a0d44a-79f2-11e8-95b4-45915656a3dd.png)

**Actual behavior:**
No completions returned

![screen shot 2018-06-27 at 10 04 40 am](https://user-images.githubusercontent.com/12821956/41988764-ffb20cfa-79f1-11e8-85fb-665f00c417de.png)

**Comment by andy-ms** [comment]
This seems to be working for me already in `typescript@next`.

**Comment by mjbvz** [comment]
Looks like we return these suggestions but fail to render them properly in VS Code? I'll take a look on our side

**Comment by mjbvz** [comment]
Never mind! On an old version. All seems to be working in 3.0.1
