### ISSUE TITLE
TSServer should expose getOccurrencesAtPosition

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#2527]
If this is something you would take I am willing to provide a pull request

**Comment by mhegazy** [comment]
PRs always welcomed :)

**Comment by dbaeumer** [comment]
Closing. This got implemented by someone else :-)

**Comment by DanielRosenwasser** [comment]
@dbaeumer we may be exposing a new API (`getDocumentHighlights`), so I'd wait off on taking a *hard* dependency until #2682 is settled on.
