### ISSUE TITLE
Define an enum as the cartesian product of two enums. Is it possible?

### ISSUE THREAD

**Issue by alexandro81** [Microsoft/TypeScript#25272]
Hi,
I was wondering if the type system allows to achieve the following.

Say I have two enums, `ReportType` and `AggregateBy`:

```
enum ReportType = {
  ContentSummary,
  VideoUsage
}

enum AggregateBy {
   Day,
   Month
}
```
I'd like to be able to create a third enum obtained as the cartesian product of those two.
The result would be:

```
{
   ContentSummaryDay
   ContentSummaryMonth,
   VideoUsageDay,
   VideoUsageMonth
}
```

**Comment by andy-ms** [comment]
Not automatically, but you could use `interface ReportAndAggregate { report: ReportType; aggregate: AggregateBy; }`, which is sometimes called a "product type" and whose set of possible values is the cartesian product of those two enums.

**Comment by andy-ms** [comment]
`interface Product<T, U> { first: T, second: U }`, or just `[T, U]`, would work for that, but I think it's less readable than using a named interface.
