### ISSUE TITLE
checkJs: true bug for paths from node_modules

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#25280]
_From @lukaszpolowczyk on March 5, 2018 11:38_

#- VSCode Version:1.20.1

Steps to Reproduce:

1. Set checkJs: true in jsconfig.json
2. NOT install jquery
3. In *.js file write:
`import $ from 'jquery';`
4. VSCode does not underline the name of the module.
5. Intellisense does not suggest jquery path.

jQuery is dependence of another module.
vscode not underline each modules from package-lock.json but should.

Same situation, with *.ts file:
1. default config
2. NOT install jquery
3. In *.ts file write:
`import $ from 'jquery';`
4. VSCode underline the name of the module.
5. Intellisense does not suggest jquery path.

Does this issue occur when all extensions are disabled?: Yes

_Copied from original issue: Microsoft/vscode#45051_

**Comment by mjbvz** [comment]
_From @vscodebot[bot] on March 5, 2018 11:38_

(Experimental duplicate detection)
Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
- [\[javascript\] suggest class and id from html when writing jquery (#28165)](https://www.github.com/Microsoft/vscode/issues/28165)

**Comment by mjbvz** [comment]
_From @lukaszpolowczyk on March 5, 2018 11:44_

@mjbvz #28165 is about something else.

**Comment by mjbvz** [comment]
Verified in 3.0.0-insiders20180626

This is caused by automatic typings acquisition downloading the jquery types. Not sure exactly how we should handle this case. Maybe error if grabbing an import that only comes from the ATA cache?

**Comment by mhegazy** [comment]
I am not seeing this locally.. @mjbvz can you elaborate on repro:

![screen2](https://user-images.githubusercontent.com/8000722/42118403-b7d5619e-7bb7-11e8-8031-83a79e336dde.gif)

**Comment by sheetalkamat** [comment]
@mhegazy I think the issue here is that there I no error on import $ from 'jquery' when jquery is not installed. (since its resolved from the automatic type acquisition)

**Comment by mhegazy** [comment]
> I  think the issue here is that there I no error on import $ from 'jquery' when jquery is not installed. (since its resolved from the automatic type acquisition)

if that is the case, then this is working as intended. add a `tsconfig.json` or disable ` "typeAcquisition": { "enable": false }` in your `jsconfig.json`

**Comment by look997** [comment]
@sheetalkamat 
> I think the issue here is that there I no error on import $ from 'jquery' when jquery is not installed. (since its resolved from the automatic type acquisition)

You wrote the truth.
This is when the other package has a dependency: jquery.

**Comment by lukaszpolowczyk** [comment]
@sheetalkamat

>    I think the issue here is that there I no error on import $ from 'jquery' when jquery is not installed. (since its resolved from the automatic type acquisition)

You wrote the truth.
This is when the other package has a dependency: jquery.
