### ISSUE TITLE
rest parameter not inferred as tuple from contextual type

### ISSUE THREAD

**Issue by ajafff** [Microsoft/TypeScript#25289]
**TypeScript Version:**  3.0.0-dev.20180628

**Search Terms:** 

**Code**

```ts
declare function take(cb: (a: number, b: string) => void): void;

/*1*/ (function foo(...rest){}(1, ''));
/*2*/ take(function(...rest){});
```

**Expected behavior:**

In both functions `rest` should be inferred as `[number, string]`.

**Actual behavior:**

1: `rest` in IIFE is inferred as `(string | number)[]`.
2: `rest` is inferred as `any[]` and emits implicit any error.

**Related Issues:**

**Comment by ahejlsberg** [comment]
Agreed, we should infer a tuple type in both cases above.
