### ISSUE TITLE
TSServer should protect itself from crashed parent

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#2529]
Especially under *nix OSes we saw orphan child processes. Our out of process stuff protects itselfs using the following mechanism:
- we send the parent process id to the server using a configure command
- the server checks from time to time if the parent is still alive. If not it exists itself.

Let me know what you think.

**Comment by basarat** [comment]
If using IPC check "connected" https://github.com/TypeStrong/atom-typescript/blob/master/lib/worker/lib/workerLib.ts#L261

**Comment by mjbvz** [comment]
Closing as I have not see recent reports of orphaned child tsserver processes
