### ISSUE TITLE
[bug/generics]: Class Generics doesn't flow properly to subclass generics

### ISSUE THREAD

**Issue by Hotell** [Microsoft/TypeScript#25296]
**TypeScript Version:**  2.9.2 + `{strict:true}`

**Search Terms:** 
jsx generics, class generics

I wanna create React generic component. but the generic annotations flow doesn't work properly/is acting strange 

**Code**

There are various issues with generics flow:

#### 1. When I define Props member, which is type of function via property, following throws error:

![image](https://user-images.githubusercontent.com/1223799/42048758-7ccd9a2a-7b04-11e8-823b-885ca1e73db6.png)

```
[ts]
Argument of type 'Readonly<{ children?: ReactNode; }> & Readonly<Props<T>>' is not assignable to parameter of type 'Props<{}>'.
  Types of property 'onSelect' are incompatible.
    Type '(item: T, event?: SyntheticEvent<HTMLElement> | undefined) => void' is not assignable to type '(item: {}, event?: SyntheticEvent<HTMLElement> | undefined) => void'.
      Types of parameters 'item' and 'item' are incompatible.
        Type '{}' is not assignable to type 'T'.
```

but if i change it to "method" definition, error is gone

![image](https://user-images.githubusercontent.com/1223799/42048906-cc0f633e-7b04-11e8-9cd5-6f44144ffad0.png)

#### 2. Generics default values doesn't flow properly:

![image](https://user-images.githubusercontent.com/1223799/42049683-f292726a-7b06-11e8-8545-c43e7c162ca8.png)

throws 

![image](https://user-images.githubusercontent.com/1223799/42049691-fd3600ec-7b06-11e8-9f2b-3840d45576e7.png)

`T = {}` is not propagated correctly to Props<T> and because of that we have those errors.

What partially helps is to constraining generic to `string` in this case, but event with that it won't flow to our Props<T>['onSelect']

![image](https://user-images.githubusercontent.com/1223799/42049836-891cafe8-7b07-11e8-9ff1-5b3b045bddf1.png)

throws:

![image](https://user-images.githubusercontent.com/1223799/42049851-90ee308e-7b07-11e8-8742-4a7d2fba0865.png)

finally what fixes the issue is to cast value propagated to `onSelect` to our `T`

![image](https://user-images.githubusercontent.com/1223799/42049881-ade11224-7b07-11e8-8332-e3ec64f46193.png)

**Expected behavior:**

class generics should properly flow to subclasses generics

```tsx
type Props<T extends string = string> = {
  items: T[]
  name: string
  onSelect(item: T, event?: SyntheticEvent<HTMLElement>): void
}
export class Select<T extends string = string> extends Component<Props<T>> {
  private readonly handleChange = (event: React.FormEvent<HTMLInputElement>) => {
    const { value, name } = event.currentTarget
    const isValueValid = this.props.items.find((item) => item === value)

    if (isValueValid) {
      this.props.onSelect(value)
    }
  }
}
```

**Comment by mhegazy** [comment]
The first issue seems like the right behavior, your `createListId` expects a `Props<{}>` (because of the default type parameter), which uses the `T` in a contravarient position, and since `{}` is not assignable to `T`, you get the error.

The second case, i only see one error on `this.props.onSelect(value)` which seems right to me as well, you can not assign `string` to `T extends string`

**Comment by mhegazy** [comment]
> its T extends string = string which is string by default. is this "error" valid ? I'm little confused with this. The confusion may be even higher because VSCode doesn't show that our T(string) generic was properly applied on Props.

default type is of no consequence here. `T` is generic, i.e. it can be a more specific type than its base constraint. e,g, `"foo" | "bar"` and assigning a `string` to that is not allowed.

**Comment by Hotell** [comment]
>  default type is of no consequence here. T is generic, i.e. it can be a more specific type than its base constraint. e,g, "foo" | "bar" and assigning a string to that is not allowed.

AHA ! right !

so with that solved what about the strange behaviour in 1):

```diff
type Props<T extends string = string> = {
  items: T[]
  name: string
// error
-  onSelect: (item: T, event?: SyntheticEvent<HTMLElement>) => void
// no error
+  onSelect(item: T, event?: SyntheticEvent<HTMLElement>): void
}
```

thanks !

**Comment by mhegazy** [comment]
`--strcitFunctionTypes` enforces stronger type checks when comparing function types, but does not apply to methods. see https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#strict-function-types

**Comment by Hotell** [comment]
Oh wow ! Didn't know that this applies also for ambient definitions ! Thanks so much for making things clear , much appreciated. Closing now 👌✌️
