### ISSUE TITLE
Incorrect extract function when variable with var in for loop is extracted

### ISSUE THREAD

**Issue by drake7707** [microsoft/TypeScript#25292]
**TypeScript Version:**  2.9.2 in Visual studio code

**Search Terms:** extract function var loop

**Code**

```ts
function test(data: any) {
    for (var month = 0; month < data.incomeTransactions.length; month++) {

    }

    // extract this to global scope
    for (var month = 0; month < data.costTransactions.length; month++) {

    }
}
```

**Expected behavior:**
Refactoring should not try to return the same variable twice, which now results in an error. This only happens with the 'var' scope, defining the month in the for loops with 'let' is fine.

**Actual behavior:**
![](https://i.imgur.com/bQI3sqK.gif)

**Comment by RyanCavanaugh** [comment]
We no longer offer refactor on this due to the multiple definitions of `month`
