### ISSUE TITLE
Better hints for 'cannot find name' errors

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#25309]
Discussed at #25306

We found that for "Cannot find name" errors, certain identifiers were fairly frequent:

> `require`, `map`, `buffer`, `describe`, `$`, `asyncIterator`, `process`, `symbol`, `module`, `promise`

We're thinking that we can elaborate beyond the usual error message.

* `$` => Suggest jQuery
* `describe` => Did you mean to have types for mocha, jest, etc.?
* `process`, `require`, `module` => Suggest including Node types
* `Symbol`, `Promise`, `Map`, `Set`, `WeakMap`, `WeakSet`, `Iterator`, `AsyncIterator` => User needs to set a different `lib` or `target`.

**Comment by DanielRosenwasser** [comment]
@bterlson @rbuckton @bowdenk7 any other suggestions?

**Comment by DanielRosenwasser** [comment]
There's also `lib: dom` in some circumstance https://twitter.com/_brotzky/status/1016915341694255104?s=19

**Comment by mhegazy** [comment]
@weswigham it will be nice to try to get this in sooner than 3.1 if we can.

**Comment by rbuckton** [comment]
Possibly some common NodeJS imports: `EventEmitter`, `Readable`, `Writable`, `fs` (add a namespace import for "fs" module), `path` (namespace import for "path" module). 

In the vein of `path` and `fs`, possibly suggestions for module names we can detect. For example, if you have the "vinyl" package and reference `vinyl` without an import, we could suggest the namespace import. 

For things like `EventEmitter`, if we know that type exists in a module not imported, we could suggest the import (similar to how we already have a quick fix).
