### ISSUE TITLE
TSServer: navto command should be supported without a file

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/TypeScript#2530]
Currently the file is only used to detect the virtual project. Now that we have tsconfig.json support we can use the language service bound to a tsconfig.json file to find navto items. I would propose the following handling in case of the absense of a file:
- no tsconfig project. Command return no content message
- all projects are tsconfig project: return the nav to items (filter duplicates)
- there is a mix: the response contains a flag indicating that the result might be incomplete.

**Comment by mhegazy** [comment]
I find it strange that you would get results from all projects even if you have a file open which points you to a single project. Can you explain the scenario you want to enable?

I think we have a related issue (#2531), if that fixed, given a file you would be getting all results from related projects, but not unrelated. would that satisfy your scenario?

**Comment by dbaeumer** [comment]
If I think about a workspace with n components I would have a tsconfig.json file per component. Now if I want to navigate in that workspace I would like to see a list of all navto items accross all components. For me that is comparable to a VS solution having n projects where project === tsconfig.json

**Comment by dbaeumer** [comment]
So to answer your question: no.

I would still like to see a mode where I can see all items.

**Comment by mhegazy** [comment]
mmm. this is interesting, i think this is the a good scenario to support; but how would you make this not noisy in the general case? imagine a few files open, each with a few .d.ts files, now you get navigate to results, and you get a lot of results that may or may not be what you are looking for.

**Comment by steveluc** [comment]
I think the only way to make this not confusing is to have some way of expressing project relationships.  So far we have chosen not to do this, leaving that level of specification to project systems such as grunt and gulp.

I agree with Mohamed this is a good scenario and we should support it in some way.  We could have two different commands in Sublime, one that just searches through every open project and one that searches only the projects that include the current file.   This could be supported in the protocol, as Dirk suggests, by making the file optional.

Either way, I think this would be more helpful and less confusing if we implement a way to explore the set of currently active projects, as Mohamed has previously suggested.

Steve

**Comment by dbaeumer** [comment]
I gave it some more thoughts and simply providing now file will not do the trick. It will force the TS service to search for all tsconfig.json files and open them. And that might not be what the user wants.

So if a workspace has more than one tsconfig.json file I think we need something like a tsglobal.json file which describes the valid tsconfig.json files and there dependencies. The TS service could then open the tsglobal.json file and act appropriately.

And I like the idea of being able to explore the set of active projects. It would help the user to understand the behavior of some global actions better.

**Comment by DanielRosenwasser** [comment]
There seems to be some context we've lost in the history of this discussion. Can we get some clarity on the file that we're discussing? What is the scenario and the specific operation that's occurring?

**Comment by dbaeumer** [comment]
If I remember correctly this is about workspace symbols which always needs a file input as well. If you have a workspace with n projects this never allowed you to list all symbols from all projects. But I have no idea if this is still true :-)

**Comment by bpasero** [comment]
Please fix this 👍

**Comment by sandersn** [comment]
So: navto needs to have an option to find symbols across all projects, as defined by project references? Or is there something additional needed?

I don't know the navto code or the project references code, so I don't have an idea yet of how hard this will be.

**Comment by dbaeumer** [comment]
Yes that is correct.

**Comment by sandersn** [comment]
Looking at this, it seems that navto currently returns symbols from the current file's project and any dependencies. But it doesn't return symbols from dependent projects. That is for projects `Base -> Derived`, in Base, you only get Base's symbols, but in Derived, you get the symbols of both.

If all the symbols are already available and are being filtered by file, then it might not be to skip the filtering and return all of them. I'll go find the navto implementation and see.

**Comment by sandersn** [comment]
Development is happening on the branch navto-covers-all-projects. It's pretty hacky right now, and extremely slow on Typescript itself.

(Note that I'm using emacs, which makes a synchronous call to get the navto list, so it's probably better in Code.)
