### ISSUE TITLE
getEditsForFileRename missing change

### ISSUE THREAD

**Issue by amcasey** [Microsoft/TypeScript#25327]
Repro

Folder1/tsconfig.json
```json
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es6",
    "lib": ["es6"],
    "sourceMap": true
  },
  "exclude": [
    "node_modules"
  ],
  "files": [
    "../Folder1/file1.ts",
    "../Folder1/file2.ts"
  ]
}
```
Folder2/file1.ts
```ts
import "./file1";
export const cd = 1;
```
Folder2/file2.ts
```ts
import { cd } from "./file1";
const d = cd;
```

Move file2.ts from Folder2 to Folder1.

Expected: tsconfig and file2 are updated
Actual: only tsconfig is updated

**Comment by andy-ms** [comment]
The following test passes:
```ts
/// <reference path='fourslash.ts' />

// @Filename: /Folder2/file1.ts
////import "./file1";
////export const cd = 1;

// @Filename: /Folder2/file2.ts
////import { cd } from "./file1";
////const d = cd;

// @Filename: /tsconfig.json
////{
////  "compilerOptions": {
////    "module": "commonjs",
////    "target": "es6",
////    "lib": ["es6"],
////    "sourceMap": true
////  },
////  "exclude": [
////    "node_modules"
////  ],
////  "files": [
////    "../NewFolder9/app9.ts",
////    "../NewFolder9/TypeScript2.ts"
////  ]
////}

verify.getEditsForFileRename({
    oldPath: "/Folder2/file2.ts",
    newPath: "/Folder1/file2.ts",
    newFileContents: {
        "/Folder2/file2.ts":
`import { cd } from "../Folder2/file1";
const d = cd;`,
    },
});
```

Maybe you pasted the wrong `tsconfig.json`? That seems to reference unrelated files.

**Comment by andy-ms** [comment]
On second thought, maybe this is an error that would only come up in a session with multiple projects. So we should fix #25420 before investigating further.

**Comment by andy-ms** [comment]
@mjbvz Testing this again and I don't see `getEditsFromFileRename` being called in `tsserver.log`. It does get called if I rename `file1.ts` to `fileX.ts`, but not if I drag `file2.ts` from `Folder2` to `Folder1`.

**Comment by amcasey** [comment]
FWIW, my repro was in VS.

**Comment by andy-ms** [comment]
@amcasey Could you try to get a `tsserver.log` from Visual Studio?

**Comment by amcasey** [comment]
Should be no problem.

**Comment by amcasey** [comment]
[gh25327.zip](https://github.com/Microsoft/TypeScript/files/2178559/gh25327.zip)

**Comment by andy-ms** [comment]
Actually, this looks like the same cause as #25536. The `tsconfig.json` is in `Folder1`, but the files are in `Folder2`. Looking at the logs, `file2.ts` is in an inferred project.
