### ISSUE TITLE
Language Service doesn't show object property name suggestions for type with computed property names

### ISSUE THREAD

**Issue by Voronar** [microsoft/TypeScript#25323]
**TypeScript Version:**  2.9.x

**Search Terms:**
Language Service API, Autocomplete

**Code**

```ts
// 2.9.x - NOT WORKING autocomplete for enumKeyObject
// 2.8.x - WORKING BOTH

enum Keys {
    First = 'first',
    Second = 'second',
    Third = 'third',
}

type EnumKeyObject = {
    [Keys.First]: {
        [Keys.Second]: {
            [Keys.Third]: boolean;
        }
    }
}

type StringKeyObject = {
    first: {
        second: {
            third: boolean;
        }
    }
}

const enumKeyObject: EnumKeyObject = {
    first: {
        second: {
            third: true,
        }
    }
}
const stringKeyObject: StringKeyObject = {
    first: {
        second: {
            third: true,
        }
    }
}

enumKeyObject // autocomplete via '.' press NOT WORKING
stringKeyObject // autocomplete via '.' press WORKING
```

**Expected behavior:**
Autocomplete for computed name properties (`enumKeyObject` variable).

**Actual behavior:**
Autocomplete for computed name properties not working like in earlier version of TypeScript (ex. 2.8.1).

**Playground Link:**
[TypeScript 2.8 playground](https://agentcooper.github.io/typescript-play/?ts=2.8.1#code/PTAEBcGdQJgOgBwCgkFMB2BXAtqA0qgJ7QDeSoFoAYgJYBOk4oAvKAOQBm9jbANOZQDKqAMYB7dABMW7SKImS+AigBUAFvWms24DXUX8AvinCEADqlABRLNgKEA8gCMAVqKasylUAG17kOFoGcABdAC5QL29KPyIA4XEpcMjlaO9Y4jh1TWSnMTEAG1QAQ3QAblTvYyqkYyRTC1BBcDoadABze2c3EQ8U7y5giKi0uUTJYcq0iD0J0DzCkvKpimrKYzrExlAMHC7XdwibPaJu9xkR0EHGSenQMYVbu8pdTQiWzFR+O7XV2qQtkxGK0OvseuAIs0QZ1TgdehdUtcIf1pg8pE9njM3hA6J9vtNfqANihdnZYeDQCBQMVMOAxOJsGYiuBLAA3GjFdhwNigMx0VCQaAAdQcACU8ABJAByAHEkMC2jDHHCmFSaXSGUzUCzQOzOWxubz+YLQCLxdK5UA)

[TypeScript 2.9 playground](https://agentcooper.github.io/typescript-play/#code/PTAEBcGdQJgOgJwCgkFMB2BXAtqA0qgJ7QDeSoFoAYgJYBOk4oAvKAOQBm9jbANOZQDKqAMYB7dABMW7SKImS+AigBUAFvWms24DXUX8AvinCEADqlABRLNgKEA8gCMAVqKasylUAG17kOFoGcABdAC5QL29KPyIA4XEpcMjlaO9Y4jh1TWSnMTEAG1QAQ3QAblTvYyqkYyRTC1BBcDoadABze2c3EQ8U7y5giKi0uUTJYcq0iD0J0DzCkvKpimrKYzrExlAMHC7XdwibPaJu9xkR0EHGSenQMYVbu8pdTQiWzFR+O7XV2qQtkxGK0OvseuAIs0QZ1TgdehdUtcIf1pg8pE9njM3hA6J9vtNfqANihdnZYeDQCBQMVMOAxOJsGYiuBLAA3GjFdhwNigMx0VCQaAAdQcACU8ABJAByAHFeKAJAVCKB2ZyfGw2CEkMC2jDHHCmFSaXSGUzUCyVRyuTy+QLhWLJbKkEA)

**Comment by RyanCavanaugh** [comment]
> Actually, you do get completion for enumKeyObject in our nightly for Keys

This behavior is at least defensible (if you're using a string enum, you presumably want to use the symbol names over the values). Moving to Dormant.
