### ISSUE TITLE
Error importing typeorm

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#25332]
_From @WangPengJu on June 29, 2018 7:30_

typescript version: 2.9.1

1. create new project
2. npm install typeorm --save
3. write code
```typescript
    namespace Test {
        export let fs: typeof import("fs");
        export let typeorm: typeof import("typeorm");
    }
```
"fs" is ok, but "typeorm" is wrong.
error: can not find module "typeorm".

ps: "typeorm" has index.d.ts in root dir

_Copied from original issue: Microsoft/vscode#53305_

**Comment by mjbvz** [comment]
_From @WangPengJu on June 29, 2018 7:34_

just IntelliSense,
don't need run code.

**Comment by mjbvz** [comment]
Tested in TS 3.0.0-dev-20180629. Unclear to me if this is a problem with `typeorm` which doesn't have an `types` entry  in its `package.json`

**Comment by mhegazy** [comment]
Can not seem to get this to repro locally..

![image](https://user-images.githubusercontent.com/8000722/42119936-682a172e-7bc7-11e8-88a6-34c2bb8ed747.png)

**Comment by WangPengJu** [comment]
i found how to Reproduce
tsconfig:
{
    "compilerOptions": {
        "module": "amd",
        "target": "es5",
    },
    "files": [
        "a.ts"
    ]
}

when module is "amd"

**Comment by DanielRosenwasser** [comment]
You probably need to use `"moduleResolution": "node"`.

**Comment by WangPengJu** [comment]
it's work, thx @DanielRosenwasser
