### ISSUE TITLE
tsc --build mode: "<package> is up to date with its dependencies", but it isn't

### ISSUE THREAD

**Issue by yortus** [Microsoft/TypeScript#25337]
**TypeScript Version:**  3.0.0-dev.20180630

**Search Terms:** 
build mode, up to date, incremental

**Steps to Reproduce**

Set up @RyanCavanaugh's [`learn-a` sample repo](https://github.com/RyanCavanaugh/learn-a) as per his [instructions](https://github.com/RyanCavanaugh/learn-a#setting-up-this-repo). Run `tsc -b packages --verbose` to see everything gets built the first time. Now change line 1 in `pkg1/src/index.ts` to `import {} from "./foo";` and save it. Run `tsc -b packages --verbose` again.

**Expected behavior:**

`pkg2` now fails to build.

**Actual behavior:**

The compiler reports `Project 'packages/pkg2/tsconfig.json' is up to date with .d.ts files from its dependencies`, and skips building it, even though we changed `pkg1` source in a way that breaks `pkg2`. If using VSCode, you can see the red squiggle in `pkg2/src/index.ts`.

**Related Issues:**

Originally reported in https://github.com/Microsoft/TypeScript/issues/3469#issuecomment-401251508.

**Comment by RyanCavanaugh** [comment]
Thanks @yortus
