### ISSUE TITLE
tsc --build mode: tsc crashes in situation involving global module augmentations

### ISSUE THREAD

**Issue by yortus** [Microsoft/TypeScript#25339]
**TypeScript Version:**  3.0.0-dev.20180630

**Search Terms:** 
build mode, crash

**Steps to Reproduce:**

Set up @RyanCavanaugh's [`learn-a` sample repo](https://github.com/RyanCavanaugh/learn-a) as per his [instructions](https://github.com/RyanCavanaugh/learn-a#setting-up-this-repo). Now run `lerna add @types/multer` to add `multer` typings to all three packages. Run `tsc -b packages --force`to confirm it still builds fine. Now add the following line to `pkg1/src/index.ts`:

```ts
export {Options} from 'multer';
```

Run `tsc -b packages --force` again.

**Expected behavior:**

Builds successfully.

**Actual behavior:**

`tsc` crashes due to a violated assertion. I looked briefly at the stack trace and assertion, and it seems to be something to do with the global augmentation of the `Express` namespace.

**Related Issues:**

Originally reported in https://github.com/Microsoft/TypeScript/issues/3469#issuecomment-401251508.

**Comment by RyanCavanaugh** [comment]
@sandersn super interesting - this hits the `target !== source` assert added to `mergeSymbolTable` despite not having any .js files. Doesn't seem to be related to `--build` (can repro this under normal `tsc -p` once upstreams are built)
