### ISSUE TITLE
Output warnings with differently colored squigglies in --pretty --watch

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Microsoft/TypeScript#25334]
## Search Terms

warning green squiggly red

## Suggestion

In pretty watch mode right now, red squigglies are always red squigglies.

![image](https://user-images.githubusercontent.com/3335181/42120412-7749e466-7bcf-11e8-9f16-546a160b2313.png)

However, in code, editors are able to receive info from the TS language server that it's a warning:

![image](https://user-images.githubusercontent.com/3335181/42120316-45ef61b2-7bce-11e8-9b2c-1307e95b1f89.png)

It'd be nice if the CLI would also use the green squiggly color.

## Use Cases

Doing so would be a little clearer for users as to what's an _error_ ("I did something wrong!") verses a warning ("I could improve this"). I've been scared a few times about files being broken when it was just an unused import.

## Examples

Visual proposal:

![image](https://user-images.githubusercontent.com/3335181/42120455-fbdbd36a-7bcf-11e8-943f-4371d3e7b1ff.png)

Alternately, we could try or to match VS Code:

![image](https://user-images.githubusercontent.com/3335181/42120405-573b7b6c-7bcf-11e8-9399-87ce8cc7f3c0.png)

...but I'm leaning towards yellow, as "green" tends to imply everything being acceptable.

Either way, +1 to outputting "warning" on warnings.

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by DanielRosenwasser** [comment]
The issue you're seeing is that what you believe is a warning is actually an error in the compiler, and as #13408 discusses, we're not going to be pursuing warnings any time soon.
