### ISSUE TITLE
Error for missing await in conditional

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#25330]
**TypeScript Version:**  3.0.0-dev.20180626

**Search Terms:** 
- await
- conditional
- diagnostics

**Code**

```ts
async function foo(): Promise<boolean> {
    return false;
}

async function bar(): Promise<string> {
    if (foo()) {
        return 'true';
    }
    return 'false';
}
```

**Expected behavior:**
A warning or error or suggestion is generated in the `if` conditional since it will always be true. The user almost certainly intended to await the result of `foo` instead.

Possibly also have a quick fix to add the await

**Actual behavior:**
No errors or warnings. Code does unexpected things

**Comment by mhegazy** [comment]
This is in the realm of linter work, but i suppose we can make an exception here since this code will never work anyways..

**Comment by dpinol** [comment]
After the work done in TS3.6 "Improved UX Around Promises" this shouldn't be difficult to implement right?

**Comment by Bellybutn278** [comment]
> This is in the realm of linter work, but i suppose we can make an exception here since this code will never work anyways..

Umm....I wonder if you are wondering why you said this now huh man. Oof
