### ISSUE TITLE
Invalid left hand side of assignment

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#2534]
Broken in the last six days. The following was and is okay: 

```ts
var foo = function(){}
foo = function(){}
```

However as soon as you split the two into external modules 
i.e. `mod1.ts` 
```ts
export var foo = function(){}
```
`mod2.ts`
```ts
import mod1 = require('./mod1'); 
mod1.foo = function(){}; // Error : Invalid left hand side of assignment
```

**Comment by mhegazy** [comment]
that is caused by #2476. foo in `import {foo} from "mod"` should be immutable, but i do not think ns.foo in `import * as ns from "mod"` should be.

**Comment by vladima** [comment]
I've checked ES6 spec - all bindings that are created for imported names are immutable so all cases below should be illegal:
```ts
import * as ns, {foo} from 'foo'
import d from 'foo'

ns.a = 1;
foo = 1;
d = 1;
```
