### ISSUE TITLE
Instance property is not a "block-scoped variable"

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#25356]
```ts
class Foo {
    b = this.a
    a = 10
}
```

**Expected**: `Property 'a' is used before its initialization.`
**Actual**: `Block-scoped variable 'a' used before its declaration.`

**Comment by mhegazy** [comment]
PRs welcomed.

**Comment by mhegazy** [comment]
thanks @a-tarasyuk !
