### ISSUE TITLE
 Circular dependency detected:

### ISSUE THREAD

**Issue by maifs** [Microsoft/TypeScript#25353]
**Search Terms:**  
Circular dependency detected:

### Bug Report 
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```
### Area
- [ devkit] 

### Versions
node --v10.4.0
and npm -- 6.1.0
Windows (10). 

### Repro steps

Create two services using typescript in angular cli 6.
1). endpoint-factory.service.ts
2). auth.service.ts
Now develop some functions in both files.
Use first file functions in second file and than use second file functions in first file.
You will get the exact exception.

### The log given by the failure
ng build

Date: 2018-07-01T17:34:59.296Z
Hash: cec4cd2f4bc6d8d1c5cf
Time: 23786ms
chunk {main} main.js, main.js.map (main) 597 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 275 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 5.22 kB [entry] [rendered]
chunk {scripts} scripts.js, scripts.js.map (scripts) 371 kB  [rendered]
chunk {styles} styles.js, styles.js.map (styles) 344 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 7.22 MB [initial] [rendered]

WARNING in Circular dependency detected:
src\app\services\auth.service.ts -> src\app\services\endpoint-factory.service.ts -> src\app\services\auth.service.ts

WARNING in Circular dependency detected:
src\app\services\endpoint-factory.service.ts -> src\app\services\auth.service.ts -> src\app\services\endpoint-factory.service.ts

--- console exception

Uncaught Error: Can't resolve all parameters for AppComponent: ([object Object], [object Object], ?, [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object]).
    at syntaxError (compiler.js:178)
    at CompileMetadataResolver._getDependenciesMetadata (compiler.js:10134)
    at CompileMetadataResolver._getTypeMetadata (compiler.js:10030)
    at CompileMetadataResolver.getNonNormalizedDirectiveMetadata (compiler.js:9659)
    at CompileMetadataResolver._getEntryComponentMetadata (compiler.js:10229)
    at entryComponents.push.bootstrapComponents.map.type (compiler.js:9897)
    at Array.map (<anonymous>)
    at CompileMetadataResolver.getNgModuleMetadata (compiler.js:9897)
    at JitCompiler._loadModules (compiler.js:21156)
    at JitCompiler._compileModuleAndComponents (compiler.js:21139)

### Desired functionality
I want to see the same functionality like in angular 5. In angular cli 1.7, there was no issue but when i upgraded my source code to angular cli 6 then i am getting the above exception.

### Mention any other details that might be useful
[https://github.com/emonney/QuickApp](url)

I upgraded this repository to angular cli 6.

**Comment by MartinJohns** [comment]
Perhaps this is more suited in the Angular repository? It doesn't look like a TypeScript issue. Nothing in the stacktrace or output indicates so.

**Comment by mhegazy** [comment]
Please see https://github.com/Microsoft/TypeScript/issues/14469
