### ISSUE TITLE
tsserver fails with "Cannot read property 'path' of undefined"

### ISSUE THREAD

**Issue by scriby** [Microsoft/TypeScript#25351]
**TypeScript Version:**  2.9.2
(I am pretty sure this still repros against latest as the affected code is the same. The way Google has things setup makes it hard to test against the latest version.)

**Search Terms:** Cannot read property 'path' of undefined

**Stack**:
TypeError: Cannot read property 'path' of undefined
    at ProjectService.updateNonInferredProjectFiles (.../node_modules/typescript/v2_9_2/lib/tsserver.js:95205:43)
    at ProjectService.addFilesToNonInferredProjectAndUpdateGraph (.../node_modules/typescript/v2_9_2/lib/tsserver.js:95154:22)
    at ProjectService.createConfiguredProject (.../node_modules/typescript/v2_9_2/lib/tsserver.js:95172:22)
    at ProjectService.openClientFileWithNormalizedPath (.../node_modules/typescript/v2_9_2/lib/tsserver.js:95566:44)
    at IOSession.Session.openClientFile (.../node_modules/typescript/v2_9_2/lib/tsserver.js:97028:37)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (.../node_modules/typescript/v2_9_2/lib/tsserver.js:96199:31)
    at .../node_modules/typescript/v2_9_2/lib/tsserver.js:97699:88

The offending line is https://github.com/Microsoft/TypeScript/blob/878bf80a48716e80063919fad1c83d54259b1cb0/src/server/editorServices.ts#L1578.

scriptInfo is undefined as it is returned here: https://github.com/Microsoft/TypeScript/blob/a1746d4cfe357ce8f38619e46578f817dfc03f9c/src/server/editorServices.ts#L1861

Even just looking at those two lines it's pretty clear that updateNonInferredProjectFiles should handle undefined coming back from getOrCreateScriptInfoNotOpenedByClientForNormalizedPath.

In my particular case where this exception is being triggered, a build tool at Google is leaving behind a .d.ts symlink that points to a file which no longer exists. This .d.ts file is referenced directly in the "files" array in the tsconfig.json.

I didn't do enough experimenting to know whether it's sufficient to trigger this issue by simply referencing a file that doesn't exist in the tsconfig files array, or whether having a symlink pointing to a file that doesn't exist is required.

The user-facing result of this exception is that for some files vscode will find lots of problems that don't exist (such as underlining modules it can't find or that experimental decorators aren't enabled).

I'm working around it for now by adding `if (!scriptInfo) continue;` before the `scriptInfo.path` reference. I haven't noticed any issues running with this change.

Thanks for taking a look!

Chris

**Comment by mhegazy** [comment]
You can upload logs using 
1. With "typescript.tsserver.log": "verbose" enabled
2. Restart vscode or vscode insiders
3. Reproduce the problem
4. Run ```code --upload-logs``` on the command line (or ```code-insiders --upload-logs``` if using vscode insiders) and follow instructions
5. Share the log file ID

**Comment by scriby** [comment]
This error shows up in the tsserver's log (using export TSS_LOG=\'-level verbose -file /tmp/tss.log\'). Based on my understanding this log isn't returned to vs code (at least nowhere I've seen). I'm using a tsserver on a remote machine so I'm not sure if vs code would have access to this log to upload it.

I already triaged the bug though, maybe someone can just try to repro using the symlink like I described...

**Comment by sheetalkamat** [comment]
@scriby i cannot repro the issue you mentioned. Also you shouldnt be hitting this given 
https://github.com/Microsoft/TypeScript/blob/878bf80a48716e80063919fad1c83d54259b1cb0/src/server/editorServices.ts#L1565
where it checks if file is not present on the disk and handles that case.
tsserver log would be the only way we can decode this.  Please try getting us the log to be able to investigate this further.

**Comment by sheetalkamat** [comment]
Since we haven't heard about this yet, closing it. We can open it when we have more info
