### ISSUE TITLE
Incorrect type check in Index Signatures

### ISSUE THREAD

**Issue by foisonocean** [Microsoft/TypeScript#25360]
**TypeScript Version:**  2.9

**Search Terms:** 

**Code**

```ts
interface T1 {
    test?: (a: number, b: string) => number;

    [i: string]: any;
}

interface T2 {
    test?: {
        [name: string]: (a: number, b: string) => number;
    };

    [i: string]: {
        [name: string]: any;
    };
}
```

**Expected behavior:**
both `T1` and `T2` should pass type check

**Actual behavior:**
only `T1` passed type check, `T2` didn't

**Playground Link:**  
https://www.typescriptlang.org/play/index.html#src=interface%20T1%20%7B%0D%0A%20%20%20%20test%3F%3A%20(a%3A%20number%2C%20b%3A%20string)%20%3D%3E%20number%3B%0D%0A%0D%0A%20%20%20%20%5Bi%3A%20string%5D%3A%20any%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20T2%20%7B%0D%0A%20%20%20%20test%3F%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20%5Bname%3A%20string%5D%3A%20(a%3A%20number%2C%20b%3A%20string)%20%3D%3E%20number%3B%0D%0A%20%20%20%20%7D%3B%0D%0A%0D%0A%20%20%20%20%5Bi%3A%20string%5D%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20%5Bname%3A%20string%5D%3A%20any%3B%0D%0A%20%20%20%20%7D%3B%0D%0A%7D%0D%0A

**Related Issues:**

**Comment by mhegazy** [comment]
`T2` should be defined as:

```ts
interface T2 {
    test?: {
        [name: string]: (a: number, b: string) => number;
    };

    [i: string]: {
        [name: string]: any;
    } | undefined;
}
```

**Comment by jcready** [comment]
Or just keep the same indexer from `T1`

```ts
interface T2 {
    test?: {
        [name: string]: (a: number, b: string) => number;
    };

    [i: string]: any;
}
```
