### ISSUE TITLE
List of reserved keywords

### ISSUE THREAD

**Issue by chinhodado** [Microsoft/TypeScript#2536]
Is there a list of reserved keywords for Typescript somewhere? I have looked around and couldn't find it, even in the [language specification](http://www.typescriptlang.org/Content/TypeScript%20Language%20Specification.pdf).

**Comment by DanielRosenwasser** [comment]
While you could refer to the ES6 spec to figure out [a partial list](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-reserved-words), it might be better to [go directly to the code](https://github.com/Microsoft/TypeScript/blob/fad889283e710ee947e8412e173d2c050107a3c1/src/compiler/types.ts#L276). Perhaps it would be better to keep a complete list as part of the TS spec.

Based on the code, I ripped this out:

Reserved Words  | Strict Mode Reserved Words    | Contextual Keywords   |
----------------|-------------------------------|-----------------------|
`break`         | `as`                          | `any`                 |
`case`          | `implements`                  | `boolean`             |
`catch`         | `interface`                   | `constructor`         |
`class`         | `let`                         | `declare`             |
`const`         | `package`                     | `get`                 |
`continue`      | `private`                     | `module`              |
`debugger`      | `protected`                   | `require`             |
`default`       | `public`                      | `number`              |
`delete`        | `static`                      | `set`                 |
`do`            | `yield`                       | `string`              |
`else`          | `symbol`                      |                       |
`enum`          | `type`                        |                       |
`export`        | `from`                        |                       |
`extends`       | `of`                          |                       |
`false`         |                               |                       |
`finally`       |                               |                       |
`for`           |                               |                       |
`function`      |                               |                       |
`if`            |                               |                       |
`import`        |                               |                       |
`in`            |                               |                       |
`instanceof`    |                               |                       |
`new`           |                               |                       |
`null`          |                               |                       |
`return`        |                               |                       |
`super`         |                               |                       |
`switch`        |                               |                       |
`this`          |                               |                       |
`throw`         |                               |                       |
`true`          |                               |                       |
`try`           |                               |                       |
`typeof`        |                               |                       |
`var`           |                               |                       |
`void`          |                               |                       |
`while`         |                               |                       |
`with`          |                               |                       |


And if you want to just copy more easily:

Reserved Words |
----------------
`break` |
`case` |
`catch` |
`class` |
`const` |
`continue` |
`debugger` |
`default` |
`delete` |
`do` |
`else` |
`enum` |
`export` |
`extends` |
`false` |
`finally` |
`for` |
`function` |
`if` |
`import` |
`in` |
`instanceof` |
`new` |
`null` |
`return` |
`super` |
`switch` |
`this` |
`throw` |
`true` |
`try` |
`typeof` |
`var` |
`void` |
`while` |
`with` |

Strict Mode Reserved Words |
-----------------
`as` |
`implements` |
`interface` |
`let` |
`package` |
`private` |
`protected` |
`public` |
`static` |
`yield` |


Contextual Keywords |
------------------
`any` |
`boolean` |
`constructor` |
`declare` |
`get` |
`module` |
`require` |
`number` |
`set` |
`string` |
`symbol` |
`type` |
`from` |
`of` |

**Comment by DanielRosenwasser** [comment]
Also `namespace`, maybe `async` and `await` eventually.

**Comment by mhegazy** [comment]
@DanielRosenwasser looks like this should have a wiki page

**Comment by crissdev** [comment]
[I tried a few of reserve words](http://www.typescriptlang.org/Playground#src=let%20of%20%3D%20'yeap'%3B%0D%0Aalert(of)%3B%0D%0A%0D%0Alet%20async%20%3D%20'yeap'%3B%0D%0Aalert(async)%3B%0D%0A)  mentioned here on the [Typescript Playground](http://www.typescriptlang.org/Playground) and didn't encounter any issues. IMO, the keywords should match at least those for ES6. For the later I have a list here https://github.com/crissdev/is-keyword-js/blob/master/index.js which is a list created from MDN site.

**Comment by zspitz** [comment]
@chinhodado @crissdev See also [PR to create keywords page in the Typescript Handbook](Microsoft/Typescript-Handbook#344).
