### ISSUE TITLE
Are `Array.from()` and `Array.of()` typed correctly?

### ISSUE THREAD

**Issue by rauschma** [Microsoft/TypeScript#25365]
The following type signature looks wrong:

```ts
interface ArrayConstructor {
  from<T>(arrayLike: ArrayLike<T>): T[];
}
```

In plain JS, the class determines the type of the result:

```text
> SubclassOfArray.from(someIterable) instanceof SubclassOfArray
true
```

So maybe it should be typed like this?

```ts
interface ArrayConstructor<T> {
  from(arrayLike: ArrayLike<T>): T[];
}
```

Similar: `Array.of()`

**Comment by RyanCavanaugh** [comment]
`ArrayConstructor` is the type of the global value `Array`, which certainly does produce an `Array` when called on `.from`. If someone else is using `ArrayConstructor` to represent some other type, they'd need to modify it appropriately

**Comment by rauschma** [comment]
Ah, my bad. I wasn’t thinking clearly: I thought the constructor would pass on its type parameter to static members, too. Not true.

But this is still an issue:

```ts
class Sub<T> extends Array<T> {
}
const s = Sub.from([1, 2]);
// Inferred:  s: number[]
// Should be: s: Sub<number>
```

But I don’t think it can be solved with the current type system. You’d need:

```ts
from<T>(arrayLike: ArrayLike<T>): this<T>;
```

**Comment by RyanCavanaugh** [comment]
Yep, see #5863
