### ISSUE TITLE
auto-suggest the name of argument based off the name of the parameter

### ISSUE THREAD

**Issue by zpdDG4gta8XKpMCd** [microsoft/TypeScript#25371]
## Search Terms

https://github.com/Microsoft/TypeScript/issues?utf8=%E2%9C%93&q=is%3Aissue+suggest+name+argument+parameter+

## Suggestion

far not always when calling a function you have all arguments ready, sometimes during quick and dirty bootstrap i just need to provide a list of whatever arguments that a function needs, and then work towards making sense of these arguments, for such cases it would be helpful if typescript auto-suggest the names of yet to be defined arguments based off the names of the parameters

## Examples

```ts
declare function foo(one: number, another: string): boolean;
foo(
 // ^ carret is here, `one` is expected as an auto-suggestion 
```

**Comment by DanielRosenwasser** [comment]
We'd recently talked about scaffolding out all the arguments as soon as someone completes on `foo` itself, or as soon as you enter a `(` key. Any thoughts here?

**Comment by mhegazy** [comment]
See https://github.com/Microsoft/TypeScript/issues/25207

**Comment by aleksey-bykov** [comment]
just like you do with the props names of an object: `Ctrl + Space` brings up the names, pretty much the same way i wish i could get *the existing list* but *with the name of the argument on the top*.

**Comment by RyanCavanaugh** [comment]
Doesn't seem to be a common suggestion
