### ISSUE TITLE
Type Inference cannot work with inheritance of generic types

### ISSUE THREAD

**Issue by sid-ihycq** [Microsoft/TypeScript#25389]
```
class X<T> {}
get<T>(x: X<T>) :T {	return <T> {};	}
let x= new X<number>();
let z = get(x);
```
It's ok, this 'z' has right type inference as **number**.

Then， I need to define a new class which extends X: 
```
class Y extends X<number> { ... }
let y = new Y();
let z = get(y);
```

In my VSCode, this 'z' seemed to be class **any** but not **number**。
It's realy very useful to me if the inference is fine under this condition。

**Comment by mhegazy** [comment]
Please see https://github.com/Microsoft/TypeScript/wiki/FAQ#why-doesnt-type-inference-work-on-this-interface-interface-foot---

**Comment by sid-ihycq** [comment]
@mhegazy thanks very much, you really did me a big favor.
