### ISSUE TITLE
Block on other signature help triggers

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#25393]
#24915 implemented trigger characters for signature help, but only blocked signature help inside of a string.

As @mhegazy mentioned in https://github.com/Microsoft/TypeScript/pull/24915#discussion_r199650123, we still need to block character triggers:

* In parenthesized expressions
* In comments
* In JSX text
* On commas outside of argument lists

**Comment by mhegazy** [comment]
@DanielRosenwasser u promised to get this in shortly after #24915
