### ISSUE TITLE
Typescript doesnt recognize class's prop (as binded method) as event listener

### ISSUE THREAD

**Issue by budarin** [Microsoft/TypeScript#25395]
I'm sorry, but I've not found any and have not any answer on stacoverflow

**TypeScript Version:**  3.0.0-dev.201xxxxx
reproduced with typescript@next

**Search Terms:** 
noone answer on [stackoverflow](https://stackoverflow.com/questions/51125472/how-to-avoid-a-error-while-declaring-event-handler-as-classs-property-with-arro)

**Code**

```ts
class MouseCoordinates extends React.Component {
    componentDidMount() {
        document.addEventListener('mousemove', this.handleMouseMove);
    }

    handleMouseMove = (event: MouseEvent): void => {
       // console.log(event)
    };
}
```
**Expected behavior:**
no error.

**Actual behavior:**
error at ```this.handleMouseMove```

> 
> Argument of type '(event: MouseEvent<HTMLElement>) => void' is not assignable to parameter of type 'EventListenerOrEventListenerObject'.
>   Type '(event: MouseEvent<HTMLElement>) => void' is not assignable to type 'EventListenerObject'.
>     Property 'handleEvent' is missing in type '(event: MouseEvent<HTMLElement>) => void'.

**Playground Link:**  
[link](http://www.typescriptlang.org/play/index.html#src=import%20React%2C%20%7B%20MouseEvent%20%7D%20from%20'react'%3B%0D%0A%0D%0Aclass%20MouseCoordinates%20extends%20React.Component%20%7B%0D%0A%20%20%20%20componentDidMount()%20%7B%0D%0A%20%20%20%20%20%20%20%20document.addEventListener('mousemove'%2C%20this.handleMouseMove)%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20handleMouseMove%20%3D%20(event%3A%20MouseEvent)%3A%20void%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%2F%2F%20console.log(event)%0D%0A%20%20%20%20%7D%3B%0D%0A%7D)
but there is no sense due to playground does not import any library 

**Related Issues:**

**Comment by MartinJohns** [comment]
`MouseEvent` doesn't seem to be generic: https://github.com/Microsoft/TypeScript/blob/master/lib/lib.dom.d.ts#L10088

So where did oyu get `MouseEvent<HTMLElement>` from?

**Comment by budarin** [comment]
I got it from one of example, but making it not general doesnt solve the problem - typescript treat ```handleMouseMove``` as an object ```EventListenerOrEventListenerObject```

**Comment by nmain** [comment]
`document.addEventListener` is a native DOM method.  It has nothing at all to do with React.  You're trying to use `React.MouseEvent` with it.  The two are unrelated.  The proper type is the `MouseEvent` from the built in DOM lib typings.  (The playground link makes this more clear, as it includes the `import { MouseEvent } from 'react'` line that you've omitted from the code sample here).

As a React user, I reccommend always referring to React types with the `React.` qualifier and not importing the individual types directly, especially when you're using React and DOM types in the same file; it helps avoid confusion like this.

**Comment by budarin** [comment]
@nmain 
thanks for the explanation!

```React.MouseEvent``` was imported by VSCode not by me, so I decided it knows what to do
