### ISSUE TITLE
undefined namespace property will compile to "error" code since typescript v2.9.1

### ISSUE THREAD

**Issue by linxiaowu66** [Microsoft/TypeScript#25391]
Hi guys,
   A "error" will be happened when there is have a undefined namespace property, for example, I have such a namespace definition, but lack of some property:

```
export namespace com {
     export namespace alibaba {
         export namespace constant{
             export interface Constant{}
         }
     } 
}
```

above example  I am forgetting to define a namespace `test` and the interface `demo`.

Then I use the v2.9.1 to compile this segment code:

```
function A(a: com.alibaba.test.demo) {}
```

Ts will generate the "error" code,

```
var _a, _b, _c, _d, _e, _f, _g, _h, _j, _k, _l;
function A([typeof (_e = ((_c = ((_d = (typeof com !== "undefined" && com).alibaba) && _d).test) && _c).demo)) === "function" && _e || Object)
```

the above code can not run.

I test other versions, only the version which > 2.9.0 will compile to this style.

< 2.9.1, eg, 2.9.0, will compile to :

```
function A(Object)
```

Any guys who know this compile rule is based on which feature, I read the changeLog but can not find any change which is related to this.

Thanks in advance.

**Comment by DanielRosenwasser** [comment]
It doesn't seem like you're giving us something we can compile that has the same issue; for example, [running in our code playground](http://www.typescriptlang.org/play/index.html#src=export%20namespace%20com%20%7B%0D%0A%20%20%20%20%20export%20namespace%20alibaba%20%7B%0D%0A%20%20%20%20%20%20%20%20%20export%20namespace%20constant%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20export%20interface%20Constant%7B%7D%0D%0A%20%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%20%7D%20%0D%0A%7D%0D%0A%0D%0Afunction%20A(a%3A%20com.alibaba.test.demo)%20%7B%7D) doesn't seem to exhibit the problem you're running into.

What compiler options are you running, and do you have something closer to the original code you wrote?

**Comment by linxiaowu66** [comment]
@DanielRosenwasser 
 
`tsconfig.json` as fowllowing:

```
{
  "compilerOptions": {
    "target": "es6",
    "lib": ["es6"],
    "typeRoots": ["./types", "node_modules/@types"],
    "outDir": "./dist",
    "sourceMap": true,
    "module": "commonjs",
    "moduleResolution": "node",
    "isolatedModules": false,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "noImplicitAny": true,
    "preserveConstEnums": true,
    "suppressImplicitAnyIndexErrors": true,
    "allowJs": true,
    "baseUrl": ".",
    "paths": {
      "ali-oss": ["./types/ali-oss.d.ts"]
    }
  },
  "include": ["lib"]
}
```

**Comment by linxiaowu66** [comment]
@DanielRosenwasser 
original code is more complex, the main problem is why the ts will compile  a value which type is not defined to such this  format: `typeof (_e = ((_c = ((_d = (typeof com !== "undefined" && com).alibaba) && _d).test) && _c).demo)) === "function" && _e`

How can i switch off this feature if the function is feature

**Comment by linxiaowu66** [comment]
@DanielRosenwasser 

I create a repo for this problem,  https://github.com/linxiaowu66/typescript-issue-25391

In the dist/index.js, you can find the code I mentioned above.

Thanks a lot
