### ISSUE TITLE
Object property wrongly claimed to be undefined when using Object.defineProperty

### ISSUE THREAD

**Issue by ditiem** [Microsoft/TypeScript#25394]
**TypeScript Version:**  2.9.1

**Search Terms:** 
defineProperty
wrongly undefined
undefined

**Code**

```
type hash =
{
  [key:string]: any
  _original_values?: {}
}

let ret : hash = { } ;

if ( ret._original_values === undefined )
     Object.defineProperty( ret
                       , '_original_values'
                      , { enumerable: false
                        , value: { } } ) ;

const key = 1, value = 2 ;
ret._original_values[ key ] = value ;

```

**Expected behavior:**
It should not say the message: Object is possibly 'undefined'.

**Actual behavior:**
It does say it

**Playground Link:** 
http://www.typescriptlang.org/play/#src=type%20hash%20%3D%0D%0A%7B%0D%0A%20%20%5Bkey%3Astring%5D%3A%20any%0D%0A%20%20_original_values%3F%3A%20%7B%7D%0D%0A%7D%0D%0A%0D%0Alet%20ret%20%3A%20hash%20%3D%20%7B%20%7D%20%3B%0D%0A%0D%0Aif%20(%20ret._original_values%20%3D%3D%3D%20undefined%20)%0D%0A%20%20%20%20%20Object.defineProperty(%20ret%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2C%20'_original_values'%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2C%20%7B%20enumerable%3A%20false%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2C%20value%3A%20%7B%20%7D%20%7D%20)%20%3B%0D%0A%0D%0Aconst%20key%20%3D%201%2C%20value%20%3D%202%20%3B%0D%0Aret._original_values%5B%20key%20%5D%20%3D%20value%20%3B%0D%0A

**Related Issues:** 
No

**Comment by andy-ms** [comment]
Control flow analysis only recognizes direct assignments, not assignments via a funciton like `Object.defineProperty` or `Object.assign`. In a case like this you'll have to use `ret._original_values!` to assert that it's not undefined.

**Comment by ditiem** [comment]
Thank you a lot @andy-ms for the explanation. I imagined the first part of the message, I filed the "bug" for documentation or at least as a wish-feature for future references.

Kind of new with typescript, I did not know about the exclamation operator. Thank you for the tip!
