### ISSUE TITLE
Incomplete function return type

### ISSUE THREAD

**Issue by shokkobon** [Microsoft/TypeScript#25404]
**TypeScript Version:**  2.9.2

**Search Terms:**  Union

**Code**

```ts
const short = () => ({ key: false })

const large = () => ({ key: true, data: "Something else" })

const noUnion = (sh: boolean) => {
  if (sh) return short()
  return large()
}

// noUnion type:
//
// const noUnion: (sh: boolean) => {
//   key: boolean;
// }

const withUnion = (sh: boolean) => {
  if (sh) return short()
  return { key: true, data: "Something else" }
}

// withUnion type:
//
// const withUnion: (sh: boolean) => {
//   key: boolean;
// } | {
//   key: boolean;
//   data: string;
// }

// withUnion and noUnion should have the same type
```

**Expected behavior:**
Return type of noUnion function should be `{ key: boolean; } | { key: boolean; data: string; }`

**Actual behavior:**
noUnion return type is `{ key: boolean; }`

**Playground Link:**  
https://www.typescriptlang.org/play/index.html#src=const%20short%20%3D%20()%20%3D%3E%20(%7B%20key%3A%20false%20%7D)%0D%0A%0D%0Aconst%20large%20%3D%20()%20%3D%3E%20(%7B%20key%3A%20true%2C%20data%3A%20%22Something%20else%22%20%7D)%0D%0A%0D%0Aconst%20noUnion%20%3D%20(sh%3A%20boolean)%20%3D%3E%20%7B%0D%0A%20%20if%20(sh)%20return%20short()%0D%0A%20%20return%20large()%0D%0A%7D%0D%0A%0D%0A%2F%2F%20noUnion%20type%3A%0D%0A%2F%2F%0D%0A%2F%2F%20const%20noUnion%3A%20(sh%3A%20boolean)%20%3D%3E%20%7B%0D%0A%2F%2F%20%20%20key%3A%20boolean%3B%0D%0A%2F%2F%20%7D%0D%0A%0D%0Aconst%20withUnion%20%3D%20(sh%3A%20boolean)%20%3D%3E%20%7B%0D%0A%20%20if%20(sh)%20return%20short()%0D%0A%20%20return%20%7B%20key%3A%20true%2C%20data%3A%20%22Something%20else%22%20%7D%0D%0A%7D%0D%0A%0D%0A%2F%2F%20withUnion%20type%3A%0D%0A%2F%2F%0D%0A%2F%2F%20const%20withUnion%3A%20(sh%3A%20boolean)%20%3D%3E%20%7B%0D%0A%2F%2F%20%20%20key%3A%20boolean%3B%0D%0A%2F%2F%20%7D%20%7C%20%7B%0D%0A%2F%2F%20%20%20key%3A%20boolean%3B%0D%0A%2F%2F%20%20%20data%3A%20string%3B%0D%0A%2F%2F%20%7D%0D%0A%0D%0A%2F%2F%20withUnion%20and%20noUnion%20should%20have%20the%20same%20type

**Related Issues:** 
https://github.com/Microsoft/TypeScript/issues/25321

**Comment by RyanCavanaugh** [comment]
You should write
```ts
const short = () => ({ key: false as false })
const large = () => ({ key: true as true, data: "Something else" })
```
if you intend `key` to be a literal discriminator.

The collapsing of `{ key: boolean; } | { key: boolean; data: string; }` to `{ key: boolean; }` can happen at any point due to subtype reduction; sometimes this *won't* happen but it's generally not safe to rely on that.
