### ISSUE TITLE
Mapping record values

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/TypeScript#25407]
## Search Terms

map object record values mapvalues

## Suggestion

Using helpers such as Lodash's `mapValues`, I can map over an object type.

This mapping will preserve the record keys in the resulting object type.

However, the value type of each key in the resulting object type is a union of all values for all given keys, when I want the value type to be tied to the specific key (e.g. given a callback of type `<T, K extends keyof T, TResult>(value: T[K], key: K) => TResult`).

For reference, here is `mapValues` as it exists today:

``` ts
interface LoDashStatic {
    mapValues<T extends object, TResult>(
        obj: T,
        callback: (t: T[keyof T], key: keyof T) => TResult,
    ): { [P in keyof T]: TResult };
}

declare const _: LoDashStatic;
```

Given:

``` ts
type Route = 'foo' | 'bar';

const routeProps = {
    foo: { fooProp: 1 },
    bar: { barProp: 1 },
};

const getRouteProps = <R extends Route>(r: R) => routeProps[r];

const routePaths = {
    foo: '/foo',
    bar: '/bar',
};
```

When I use `mapValues` over `routePaths`, the resulting object type is not as desired.

``` ts
/*
Actual type
{
    foo: {
        path: string;
        props: {
            fooProp: number;
        } | {
            barProp: number;
        };
    };
    bar: {
        path: string;
        props: {
            fooProp: number;
        } | {
            barProp: number;
        };
    };
}

Desired type
{
    foo: {
        path: string;
        props: {
            fooProp: number;
        };
    };
    bar: {
        path: string;
        props: {
            barProp: number;
        };
    };
}
*/
const routes = _.mapValues(routePaths, (path, route) => ({ path, props: getRouteProps(route) }));
```

Are there any potential TS features which would enable this?

## Checklist

My suggestion meets these guidelines:
* [ ] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by mhegazy** [comment]
This looks like call types request. Adding call types is tracked by  https://github.com/Microsoft/TypeScript/issues/6606
