### ISSUE TITLE
Enable possibility of strong typing on ActiveXObject via specialized overloads

### ISSUE THREAD

**Issue by zspitz** [Microsoft/TypeScript#2541]
If I've defined an interface corresponding to an Automation object:

```typescript    
module Scripting {
    interface FileSystemObject {
        BuildPath(Path: string,Name: string): string
        FileExists(FileSpec: string): boolean
        //other members ...
    }
}
```
it should be possible to get the type as said interface, using type inference and specialized overloads:

```typescript
var fso = new ActiveXObject('Scripting.FileSystemObject');
```

This could be done by having `ActiveXObject` implement a named interface in `lib.d.ts`:

```typescript
interface ActiveXObject {
    new (s: string): any;
}
declare var ActiveXObject: ActiveXObject;
```

Then, other modules could add the additional specialized overloads:

```typescript
interface ActiveXObject {
    new (s: 'Scripting.FileSystemObject'): Scripting.FileSystemObject;
}
```

**Comment by nycdotnet** [comment]
This is a great idea.

**Comment by mhegazy** [comment]
+1. 
PR's are welcomed.

**Comment by zspitz** [comment]
@nycdotnet I've added a [PR to DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/9868) for Scripting Runtime and WIA, which uses this.

**Comment by zspitz** [comment]
@nycdotnet The tool I am using to generate these libraries is now [on Github](https://github.com/zspitz/ts-activex-gen).
