### ISSUE TITLE
Feature Request: Deduce types after function predicate declaration.

### ISSUE THREAD

**Issue by babakness** [Microsoft/TypeScript#25412]
Hello, 

There should be away to abstract the type of a value after some predicate function is narrowed the scope of possible type. Example:

```typescript
export type EntryKey<A> = A extends [infer KEY,infer VALUE] ? KEY : undefined
export type EntryValue<A> = A extends [infer KEY,infer VALUE] ? VALUE : undefined
class X<A>{

  filterEntryValueType<K extends EntryKey<A>, V extends EntryValue<A>, VT extends V, B extends [K,VT]>( predicate: (a: V) => a is VT ): X<B> {

}

const foo = new X([ ['a',100], ['b','two hundred'] ] )
foo.filterEntryValueType( (a): a is a number => typeof a === 'number' )

// [string, number | string ]
```

However, if we do this instead

```ts
filterEntryValueType<K extends EntryKey<A>, V extends EntryValue<A>, VT extends V>( predicate: (a: V) => a is VT ): X<[K,VT]> {

```

We get the correct result

```ts
//[string,number]
```

There should be a way to abstract `[K,VT]` into `B` after understanding what `predicate` does to `VT`

**Comment by mhegazy** [comment]
I really do not understand what `EntryKey` is mean to do, and why not just have a `K, V` as type parameters on your class `X` or method `filterEntryValueType`. what is `B`? where is supposed to be infered from? what is that method trying to do ..

if i think of a filter method, i woudl write it as:

```ts
class X<K, V>{
    constructor(list: [K, V][]) { }
    filterEntryValueType<V2 extends V>(_predicate: (a: any) => a is V2): Transduce<[K, V2]> {
        return [] as any;
    }
}
```

**Comment by babakness** [comment]
The form `[K,V][]`; that is only a special case of what `<A>` can be. I've updated my example, the method returns `X<[K,V]>` the original only complicates the example.

**Comment by babakness** [comment]
Maybe I'm not explaining it well...

It would be great to refer to `[K,V2]` from a single symbol, ie, `B`; that `B` is evaluated in the right most reference with information that came before it and not just when it was declared.

**Comment by mhegazy** [comment]
> It would be great to refer to [K,V2] from a single symbol,

you can, the problem is two folds, first there is no place to infer `B` from in your example. and second, constraints are not inference position, they are only used to report errors.
