### ISSUE TITLE
JSDoc /** @type */ tags don't check return types

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#25424]
```ts
// @ts-check

/** @type {(x: number, y: number, z: number) => string} */
function foo(x, y, z) {
    return 100;
}
```

**Expected**: Error.
**Actual**: No error.

**Comment by sandersn** [comment]
Note: doesn't repro for function expressions:

```js
var foo = function (...
// or
var bar = (...
```

**Comment by sandersn** [comment]
`getJSDocReturnType` only looks at `@return` tags, it doesn't check `@type` tags to see whether their type node has a return type. Seems easy to fix.
