### ISSUE TITLE
Provide a better error message when "async" is mistyped?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [microsoft/TypeScript#25429]
## Search Terms

error message async function 

## Suggestion

When I mistype `async` as something like `asdync`, the error messages are quite unhelpful. It would be nice to have "did you mean async?" suggestions, as when we mistype a variable name. Perhaps if the edit distance from this particular keyword is small?

If this idea is a good one, it might make sense to expand it to `public`, `protected`, etc.

## Use Cases

This is a common thing for me, sadly. I assume new users have this problem as well.

## Examples

```typescript
asdync foo() { }

class Foo {
    private asdync bar() { }
}
```

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by DanielRosenwasser** [comment]
Thank you @JoshuaKGoldberg
