### ISSUE TITLE
Type is not inferred, but it could/should be

### ISSUE THREAD

**Issue by ORESoftware** [Microsoft/TypeScript#25428]
I have a situation where a type should be inferred, but it's not.

I am on:
Version 2.9.1

**Search Terms:** 
type inference interface

**Code**

```ts
export interface LockObj {
  lockholders: { [key: string]: { pid: number, ws: net.Socket, uuid: string } }, 
}

 export interface LockHash {
  [key: string]: LockObj
}

 export class Broker {

   locks: LockHash;

   someMethod(){

   const locks = this.locks;

   // ... 

   const lckTemp = locks[key] = {
        // ...
        lockholders: {},
       // ...
      };

      lckTemp.lockholders[uuid] = {ws, uuid, pid};   // here is where the error shows
  }
}
  
```

**Expected behavior:**

I would expect that tsc could infer that `lckTemp.lockholders` would be of type 
{ [key: string]: { pid: number, ws: net.Socket, uuid: string } }

**Actual behavior:**
Instead, it can't seem to infer the type.

Here is a screenshot:

![screenshot from 2018-07-03 23-31-24](https://user-images.githubusercontent.com/11139560/42260475-6d1fea56-7f19-11e8-989b-2232aec1c55f.png)

**Comment by RyanCavanaugh** [comment]
@ORESoftware please provide a repro we can run in the Playground for these issues; it's very annoying for us to guess at what various types in your program might be

**Comment by RyanCavanaugh** [comment]
Anyway the issue here is that the type of an assignment expression is the type of the right operand, not the left operand:
```ts
   const lckTemp = locks[key] = {
        // ...
        lockholders: {},
       // ...
      } /* as LockObj; */
```
A "solution" here is to use the left operand type instead, but this causes other problems:
```ts
var a: Animal;
const c: Cat = a = new Cat(); // Should be OK
```

We also experimented with inferring index signatures into object literals that were contextually-typed by index signatures, but this had other undesirable effects that I don't recall at the time.

**Comment by ORESoftware** [comment]
@RyanCavanaugh  thanks, I tried to provide all the type info, which types were missing?

**Comment by RyanCavanaugh** [comment]
@ORESoftware [See red lines here](http://www.typescriptlang.org/play/#src=export%20interface%20LockObj%20%7B%0D%0A%20%20lockholders%3A%20%7B%20%5Bkey%3A%20string%5D%3A%20%7B%20pid%3A%20number%2C%20ws%3A%20net.Socket%2C%20uuid%3A%20string%20%7D%20%7D%2C%20%0D%0A%7D%0D%0A%0D%0A%20export%20interface%20LockHash%20%7B%0D%0A%20%20%5Bkey%3A%20string%5D%3A%20LockObj%0D%0A%7D%0D%0A%0D%0A%20export%20class%20Broker%20%7B%0D%0A%0D%0A%20%20%20locks%3A%20LockHash%3B%0D%0A%0D%0A%20%20%20someMethod()%7B%0D%0A%0D%0A%20%20%20const%20locks%20%3D%20this.locks%3B%0D%0A%0D%0A%20%20%20%2F%2F%20...%20%0D%0A%0D%0A%20%20%20const%20lckTemp%20%3D%20locks%5Bkey%5D%20%3D%20%7B%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20...%0D%0A%20%20%20%20%20%20%20%20lockholders%3A%20%7B%7D%2C%0D%0A%20%20%20%20%20%20%20%2F%2F%20...%0D%0A%20%20%20%20%20%20%7D%3B%0D%0A%0D%0A%20%20%20%20%20%20lckTemp.lockholders%5Buuid%5D%20%3D%20%7Bws%2C%20uuid%2C%20pid%7D%3B%20%20%20%2F%2F%20here%20is%20where%20the%20error%20shows%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0A%20%20)

**Comment by ORESoftware** [comment]
Got it, yeah those types probably don't matter for this one, that's why I didn't include them, but this is better for you (all red squigglies are gone in the playground):

```js
export interface LockObj {
  lockholders: { [key: string]: { pid: number, uuid: string } }, 
}

 export interface LockHash {
  [key: string]: LockObj
}

const key = '';
const uuid = '';
const pid = 2;

 export class Broker {

   locks: LockHash;

   someMethod(){

   const locks = this.locks;

   // ... 

   const lckTemp = locks[key] = {
        // ...
        lockholders: {},
       // ...
      };

      lckTemp.lockholders[uuid] = {uuid, pid};   // here is where the error shows
  }
}
```
