### ISSUE TITLE
Provide a means to declare that all keys of an interface or string union must be in a statically declared array

### ISSUE THREAD

**Issue by leighman** [microsoft/TypeScript#25431]
## Suggestion

It is common to need a list of all possible values of a string union or all keys of an interface at runtime. These are usually declared statically in the file so it would be nice to be able to check at compile that all keys are listed.
I understand that there is no desire for typescript to produce runtime values but it would be useful to be able to annotate statically.

## Use Cases

```
type PostType = "GENERAL" | "TIP" | "QUESTION"

const allPostTypes: Array<PostType> = [
  "GENERAL",
  "TIP",
]
```
`allPostTypes` here will currently typecheck.

It is currently possible to write something like
```
export const allKeysOfType = <T = never>(
  o: Record<keyof T, null>,
): Array<keyof T> => Object.keys(o)
```
but it requires a different implementation for string unions and it allows you to not provide `T` in which case it will be inferred wrongly.

## Examples

Assuming some new syntax `total [` for total array. There's probably a better way.

```
type Foo = "a" | "b"

const allKeysOfFoo: Array<Foo> = total [
  "a",
] // error: missing value "b" in total array

const allKeysOfFoo = total ["a", "b"] // error: unable to infer type for total Array

const allKeysOfFoo: Array<Foo> = total ["a", "b"] // compiles

interface Blah {
  name: string
}

const allKeysOfBlah: Array<keyof Blah> = total ["name"] // compiles
```

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by RyanCavanaugh** [comment]
The scenario here can be straightforwardly accomplished by inverting which declaration is in charge of the canonical set:
```ts
const allPostTypes = [
  "GENERAL",
  "TIP",
  "QUESTION"
] as const;
type PostType = (typeof allPostTypes)[number];
```

I can't think of another reason to need the `total` operator, so adding a new kind of type when a different solution is already available isn't likely to happen.
