### ISSUE TITLE
__assign polyfill can be easily overwrited

### ISSUE THREAD

**Issue by CristhianParra** [Microsoft/TypeScript#25438]
When ts compiles object deconstruction, it creates a helper function (__assign) that can be overwrited

**Code**

```ts
const a = { A: 1 }
const b = { B: 2 }
const c = { ...a, ...b }

const __assign = () => 'Overwrite'

const d = { ...a, ...b }

console.log(c)
console.log(d)
```

**Expected behavior:**
{ A: 1, B: 2 }
{ A: 1, B: 2 }

**Actual behavior:**
{ A: 1, B: 2 }
10

**Playground Link:** 
http://www.typescriptlang.org/play/#src=const%20a%20%3D%20%7B%20A%3A%201%20%7D%0D%0Aconst%20b%20%3D%20%7B%20B%3A%202%20%7D%0D%0Aconst%20c%20%3D%20%7B%20...a%2C%20...b%20%7D%0D%0A%0D%0Aconst%20__assign%20%3D%20()%20%3D%3E%20'Overwrite'%0D%0A%0D%0Aconst%20d%20%3D%20%7B%20...a%2C%20...b%20%7D%0D%0A%0D%0Aconsole.log(c)%0D%0Aconsole.log(d)

**Comment by RyanCavanaugh** [comment]
This is so that you can provide your own (hopefully non-malicious) version of `__assign` in case you don't like the semantics of the built-in helper.
