### ISSUE TITLE
Failure to infer parameter type

### ISSUE THREAD

**Issue by pelotom** [Microsoft/TypeScript#25444]
**TypeScript Version:**  3.0.0-dev.20180704

**Search Terms:** parameter inference

For context, I'm trying to provide accurate typings for a JS library ([Material UI](https://github.com/mui-org/material-ui/pull/11731)). What follows is an extreme simplification of the problem, dealing with functions rather than components:

**Code**

```ts
const foo = <A>(f: (x: A) => void, x: A) => f(x);

foo(
  (x: (n: number) => void) => x(42),
  n => console.log(n)
);
```

**Expected behavior:**

Should infer the type of the `n` parameter of the second argument as `number`.

**Actual behavior:**

Infers `n: any`, which rightly fails when `noImplicitAny` is enabled. However the compiler clearly knows what the type of the `n` parameter should be... if it's annotated incorrectly, e.g.

```ts
(n: string) => console.log(n)
```

then we get an error saying 

```
Argument of type '(x: (n: number) => void) => void' is not assignable to parameter of type '(x: (n: string) => void) => void'.
  Types of parameters 'x' and 'x' are incompatible.
    Types of parameters 'n' and 'n' are incompatible.
      Type 'number' is not assignable to type 'string'.
```

**[Playground Link](http://www.typescriptlang.org/play/#src=const%20foo%20%3D%20%3CA%3E(f%3A%20(x%3A%20A)%20%3D%3E%20void%2C%20x%3A%20A)%20%3D%3E%20f(x)%3B%0A%0Afoo(%0A%20%20(x%3A%20(n%3A%20number)%20%3D%3E%20void)%20%3D%3E%20x(42)%2C%0A%20%20n%20%3D%3E%20console.log(n)%0A)%3B)**

**Comment by mhegazy** [comment]
What is happening here is to infere the type of `P`, the compiler needs to know the type of `bar` and to know that it needs an inference for `P`, which at this point is not available. 

You can explicitly specify the type argument to the call:
```ts
foo<{ bar(x: number): void }>({
    f(p) { },
    bar(x) { },
});
```

**Comment by mhegazy** [comment]
Conditional types do not contribute to inferences.
