### ISSUE TITLE
Cannot find doc on tsc --in myfile.es6 --out myfile.js

### ISSUE THREAD

**Issue by kevinpas** [Microsoft/TypeScript#2544]
I cannot find any comments on this anywhere on the internet.

I prefer to name my es6 files something other than *.ts

Thanks,  Maybe some version in the future.

**Comment by DanielRosenwasser** [comment]
To clarify, are you asking about compiling files with a `.js` extension? Our compiler currently doesn't support this. Is there any specific reason you feel averse to using the `.ts` extension? Are there any downsides to doing so?

**Comment by kevinpas** [comment]
I'm sorry, that was pretty dense on my part.

I want to name my files *.es6 (but the extension should be irrelevant).

Maybe something like this:  tsc --in myfile.es6 --out myfile.js

As programs like typescript and babel mature they will complement each.  And as newer versions of ECMAscript come out I could use *.es7, *.es6 on the same line...

But I can always preprocess my files if I want to rename them.

**Comment by kevinpas** [comment]
Thanks, that pretty much confirms what I was thinking.

TypeScript works great, I'll be using it regularly.

**Comment by DanielRosenwasser** [comment]
Glad to hear it, hope it isn't too much trouble. We're very much committed to conforming closely to ES6 and as it becomes more concrete, ES7, so ideally you shouldn't ever need to feel concerned about which edition of ECMAScript since TypeScript will support it.
