### ISSUE TITLE
Infrastructure: internal declarations added to tsserverlibrary.d.ts

### ISSUE THREAD

**Issue by ajafff** [Microsoft/TypeScript#25440]
I noticed this in https://github.com/Microsoft/TypeScript/pull/25439#pullrequestreview-134455964 after adding a function to an `@internal` namespace. The baseline changed so that means these declarations are also published to npm.

**Comment by mhegazy** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/24966
