### ISSUE TITLE
Type Guard on Field does not Narrow Type of Object

### ISSUE THREAD

**Issue by AnyhowStep** [Microsoft/TypeScript#25447]
**TypeScript Version:**  3.0.0-dev.20180602

**Search Terms:** field type guard narrow

**Code**

```ts
interface A {
  f?: number;
  bar: string; 
}

interface B {
  f: number; 
}
declare const x: A | B;
if (x.f == undefined) {
  //Expected:
  //'x' is narrowed to type 'A'
  //Actual:
  //Property 'bar' does not exist on type 'A | B'.
  //Property 'bar' does not exist on type 'B'.
  console.log(x.bar);
} 
```

**Expected behavior:**

'x' is narrowed to type 'A'

**Actual behavior:**

```
Property 'bar' does not exist on type 'A | B'.
Property 'bar' does not exist on type 'B'.
```

**Playground Link:** [Here](http://www.typescriptlang.org/play/#src=interface%20A%20%7B%0D%0A%20%20f%3F%3A%20number%3B%0D%0A%20%20bar%3A%20string%3B%20%0D%0A%7D%0D%0A%0D%0Ainterface%20B%20%7B%0D%0A%20%20f%3A%20number%3B%20%0D%0A%7D%0D%0Adeclare%20const%20x%3A%20A%20%7C%20B%3B%0D%0Aif%20(x.f%20%3D%3D%20undefined)%20%7B%0D%0A%20%20%2F%2FExpected%3A%0D%0A%20%20%2F%2F'x'%20is%20narrowed%20to%20type%20'A'%0D%0A%20%20%2F%2FActual%3A%0D%0A%20%20%2F%2FProperty%20'bar'%20does%20not%20exist%20on%20type%20'A%20%7C%20B'.%0D%0A%20%20%2F%2FProperty%20'bar'%20does%20not%20exist%20on%20type%20'B'.%0D%0A%20%20console.log(x.bar)%3B%0D%0A%7D%20)

**Comment by mhegazy** [comment]
This is in the vein of https://github.com/Microsoft/TypeScript/issues/24193, with `undefined` instead of `null`. I would recommend adding this use case to https://github.com/Microsoft/TypeScript/issues/24193
