### ISSUE TITLE
Const Enum undefined when imported from remote npm package in create-react-app project

### ISSUE THREAD

**Issue by stephenkiers** [Microsoft/TypeScript#25441]
**TypeScript Version:**  3.0.0-dev.20180704

**Search Terms:** enum, npm, yarn, import, create react app

**Reproduction Github Repository**
https://github.com/stephenkiers/TypescriptRepo1

**Remote Package Code**
```ts
export const enum TEST {
    MAJOR = "major",
    MINOR = "minor"
}
```
**Target Package Code**
```ts
type IFoo = {
    type: TEST.MINOR|TEST.MAJOR;
    name: string;
};
const foo: IFoo = {
    type: TEST.MINOR,
    name: "Full Name"
};
console.log(foo.type === TEST.MINOR ? foo.name : "World")
```

**Expected behavior:**
Target Package should print `Full Name`

**Actual behavior:**
`TEST` is undefined, so there is `Uncaught TypeError: Cannot read property 'MINOR' of undefined`

**Playground Link:** 
Cannot recreate in playground, but made public github repo and youtube video
- https://github.com/stephenkiers/TypescriptRepo1
- https://www.youtube.com/watch?v=c5uUSzFjiFM

**Related Issues:** *not really, but here are some possible similar issues*
- https://github.com/babel/babel/issues/6805
- https://github.com/TypeStrong/ts-node/issues/515 
    - I added "preserveConstEnums" to .tsconfig to no avail
- https://stackoverflow.com/questions/47418124/enum-type-not-defined-at-runtime

**Comment by AlCalzone** [comment]
Why does it need to be a const enum? From the docs:

> Const enums can only use constant enum expressions and unlike regular enums **they are completely removed during compilation**. Const enum members are inlined at use sites.

As such, this code 
```ts
namespace foo {
    export const enum TEST {
        MAJOR = "major",
        MINOR = "minor"
    }
}

const bar = foo.TEST.MAJOR;
```
gets transpiled to 
```js
var bar = "major" /* MAJOR */;
```

If you remove the `const` modifier from the enum, you get what you expect:
```js
var foo;
(function (foo) {
    var TEST;
    (function (TEST) {
        TEST["MAJOR"] = "major";
        TEST["MINOR"] = "minor";
    })(TEST = foo.TEST || (foo.TEST = {}));
})(foo || (foo = {}));
var bar = foo.TEST.MAJOR;
```

**Comment by stephenkiers** [comment]
The reason we used `const enum` is we wanted the code inlined at runtime; and it worked when the code was within the same repo. The issue, as it turns out, is that the `create-react-app-typescript` project does not compile code in `/node_modules/` properly. 

I will look into fixing that, to see if I can get this working properly.

As it seems that the issue is not typescript, I am closing this issue for now.

thanks
