### ISSUE TITLE
Union Types  check not properly for a object assignment expression

### ISSUE THREAD

**Issue by ufolux** [Microsoft/TypeScript#25449]
**TypeScript Version:**  2.8.1

**Search Terms:** 
Union Types

**Code**

```ts
type obj = {
    a: 'a' | 'b' | 'c'
}

let a = { a: 'c' }

let b: obj = a
```

**Expected behavior:**

Shouldn't have any problem here

**Actual behavior:**

Error:

```
Type '{ a: string; }' is not assignable to type 'obj'.
  Types of property 'a' are incompatible.
    Type 'string' is not assignable to type '"a" | "b" | "c"'.
```

but if I replace `let b: obj = a` expression to `let b: obj =  { a: 'c' }`, it will work.

ps: I met this problem on TSX style property

**Playground Link:**  

And a playground link [here](https://www.typescriptlang.org/play/index.html#src=type%20obj%20%3D%20%7B%0D%0A%20%20%20%20a%3A%20'a'%20%7C%20'b'%20%7C%20'c'%0D%0A%7D%0D%0A%0D%0Alet%20a%20%3D%20%7B%20a%3A%20'c'%20%7D%0D%0A%0D%0Alet%20b%3A%20obj%20%3D%20a%0D%0A%0D%0A)

**Comment by Hoishin** [comment]
It seems the root problem isn’t the type checks in assignment, but type inference.
There is no way to tell you the assignment is valid when `a`’s type is `{a: string}`.

**Comment by ufolux** [comment]
@Hoishin How can I tell the compiler `position` is a union type in this situation?

```jsx
// UI file
...
render() {
     <View style={styles.header}/>
}
const styles = StyleSheet.create(styleObj)
...

// style file
...
export styleObj = {
    header: {
          position: 'absolute'
    }
}
...

```

For some reason, I need to construct my style object by assigning the value to a variable and then pass the variable to style property of JSX. Just like the type of `position` property is an union type. The error will occur at this situation.  Do u have any idea about this?

**Comment by RyanCavanaugh** [comment]
Consider code like this:

```ts
type obj = {
    a: 'a' | 'b' | 'c'
}

let a = { a: 'c' }

let b: obj = a
mut(d);
console.log(a.a); // not 'a' 'b' or 'c'

function mut(x: {a: string}) {
  x.a = 'd';
}
```

We should issue an error *somewhere* in this program because it's unsound. Maybe the "best" location is somewhere else, but i.e. issuing the error in the call to `mut` implies a completely different type inference system.

**Comment by ufolux** [comment]
@Hoishin Thanks，it works😁
