### ISSUE TITLE
perfectdrugstore

### ISSUE THREAD

**Issue by StevenBlakley** [Microsoft/TypeScript#25450]
**TypeScript Version:**  3.0.0-dev.201xxxxx

**Search Terms:** 

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**Expected behavior:**

**Actual behavior:**

**Playground Link:**  

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
![image](https://user-images.githubusercontent.com/6685088/42336092-6a6fd248-8037-11e8-9346-a933cb649a5f.png)
