### ISSUE TITLE
Incorrect variance in checking functions in jsx

### ISSUE THREAD

**Issue by goloveychuk** [Microsoft/TypeScript#25451]
**TypeScript Version:**  2.9.2,  3.0.0-dev.20180705

**Search Terms:** 

**Code**

```ts

import * as React from 'react'

interface A {
    b: string
}

interface B extends A {
    c: string
}

interface Props {
    cb(val: A): void
}

const Comp: React.SFC<Props> = () => null

function cb(val: B) {
    console.log(val.c)
}

const a = <Comp cb={cb}/> // no error

let f: Props['cb'] 
let f2: (val: A) => void

f = cb // no error

f2 = cb // error

```

**Expected behavior:**
Errors in all places
**Actual behavior:**
No error in jsx and when using `Props['cb']`
**Playground Link:**  

**Related Issues:**

**Comment by rkovalyov** [comment]
👍

**Comment by RyanCavanaugh** [comment]
Have you turned on `strictFunctionTypes` ?

**Comment by goloveychuk** [comment]
@RyanCavanaugh yes, forgot to mention: `strict: true` enabled

**Comment by RyanCavanaugh** [comment]
Ah, right - even under `strictFunctionTypes`, methods declared with "method syntax" are checked bivariantly. Change the definition to this and you should see an error:
```ts
interface Props {
    cb: (val: A) => void
}
```

**Comment by goloveychuk** [comment]
so this is expected behavior, and, basically, to make things safe, all methods in component Props should be declared with property syntax? Maybe it should be mentioned in docs with bold font (or maybe I missed that)

**Comment by RyanCavanaugh** [comment]
It's a trade-off because many common props patterns are unsound due to a lack of `writeonly` modifier, e.g.:
```ts
interface BaseProps {
  onSomething(me: BaseObj): void;
}

// elsewhere
interface DerivedProps extends BaseProps {
  onSomething(me: DerivedObj): void;
}
```
This is unsound against a call to `onSomething(base)` on an `BaseProps`-aliased reference to a `DerivedProps`, but in practice this never happens so no one cares.
