### ISSUE TITLE
noErrorTruncation property is in the TypeScript Handbook Compiler Options but missing from the TypeScript Schema

### ISSUE THREAD

**Issue by ltfschoen** [microsoft/TypeScript#25453]
**TypeScript Version:**  3.0.0-dev.201xxxxx
N/A

**Search Terms:** 
noErrorTruncation

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```
N/A

**Expected behavior:**
`noErrorTruncation` property should be included in the TypeScript Schema

**Actual behavior:**
The TypeScript Schema http://json.schemastore.org/tsconfig that's referred to at the link provided here: https://www.typescriptlang.org/docs/handbook/tsconfig-json.html does not contain the property `noErrorTruncation`, yet `noErrorTruncation` is listed as an available flag in the TypeScript Compiler Options here https://www.typescriptlang.org/docs/handbook/compiler-options.html

**Playground Link:**  
N/A

**Related Issues:** 
N/A

**Comment by jakebailey** [comment]
Fixed via the linked https://github.com/SchemaStore/schemastore/pull/485.
