### ISSUE TITLE
Read-only properties not handled correctly

### ISSUE THREAD

**Issue by waywardmonkeys** [Microsoft/TypeScript#2545]
If I have this TypeScript:

````typescript
class A {
  private read_: boolean = false;

  public get read (): boolean {
    return this.read_;
  }
};

var a = new A();
a.read = true;
console.log(a.read);
````

It generates this JavaScript, when compiled with ``tsc --target es5 setter.ts``:

````javascript
var A = (function () {
    function A() {
        this.read_ = false;
    }
    Object.defineProperty(A.prototype, "read", {
        get: function () {
            return this.read_;
        },
        enumerable: true,
        configurable: true
    });
    return A;
})();
;
var a = new A();
a.read = true;
console.log(a.read);
````

When executed, it produces:

````
false
````

I would have expected ``tsc`` to warn or error about writing to a property that is read-only.

**Comment by waywardmonkeys** [comment]
I accidentally pasted a slightly outdated version of the TypeScript. I have updated the issue with the correct TypeScript code.

**Comment by danquirk** [comment]
The type system is not aware of readonly-ness at the moment. See #12
