### ISSUE TITLE
TS allows to import invalid json files with resolveJsonModule enabled

### ISSUE THREAD

**Issue by que-etc** [Microsoft/TypeScript#25452]
**TypeScript Version:** 3.0.0-dev.20180705

**Search Terms:**
- json
- invalid
- resolveJsonModule

**Code**

**invalid-file.json**
```json
{
    foo: function () {}   
}
```

**usage.ts**
```ts
import data from './invalid-file.json';

data.foo();
```

**Expected behavior:** 
TS throws an error when importing an invalid json file.

**Actual behavior:**
No errors were thrown.

**Comment by sheetalkamat** [comment]
The errors are reported.
```
c:\temp\test2>node c:\temp\29\node_modules\typescript\lib\tsc.js --resolveJsonModule usage.ts
invalid-file.json:2:5 - error TS1327: String literal with double quotes expected.

2     foo: function () {}
      ~~~


invalid-file.json:2:10 - error TS1328: Property value can only be string literal, numeric literal, 'true', 'false', 'null', object literal or array literal.

2     foo: function () {}
           ~~~~~~~~

```

**Comment by que-etc** [comment]
Hm, for some reason errors don't show up in the editor (VSCode) when viewing the `usage.ts` file.

**Comment by sheetalkamat** [comment]
Errors are reported in json file not in usage.ts

**Comment by que-etc** [comment]
Yeah, I see now.

I just expected it to show something like `File "{{}}" is not a valid json.` near the import statement.

**Comment by sheetalkamat** [comment]
yeah but if there are errors in the module it doesnt report errors on import location
```typescript
//c.ts
export fuinction foo3() {
}

// usage.ts
import data from './invalid-file.json';
import data2 from './c';

data.foo();
```

The result is:
```
c:\temp\test2>node c:\TypeScript\built\local\tsc.js --resolveJsonModule usage.ts
c.ts:2:1 - error TS1128: Declaration or statement expected.

2 export fuinction foo3() {
  ~~~~~~

c.ts:2:18 - error TS1005: ';' expected.

2 export fuinction foo3() {
                   ~~~~

c.ts:2:25 - error TS1005: ';' expected.

2 export fuinction foo3() {
                          ~

invalid-file.json:2:5 - error TS1327: String literal with double quotes expected.

2     foo: function () {}
      ~~~

invalid-file.json:2:10 - error TS1328: Property value can only be string literal, numeric literal, 'true', 'false', 'null', object literal or array literal.

2     foo: function () {}
           ~~~~~~~~
```

**Comment by mhegazy** [comment]
> Hm, for some reason errors don't show up in the editor (VSCode) 

VSCode does not know that it can ask tsserver for the errors in the json file and this it never queries for these errors, and never show them. the errors will be visible on the command-line.

@mjbvz what is the best solution here?

Also cc @amcasey since VS has a similar problem.

**Comment by mjbvz** [comment]
For VS Code, if you the json language service will show errors once you open that invalid file. Do you mean showing for the json file when you are still in the ts file?

**Comment by amcasey** [comment]
In VS, the JS LS won't ask the server for errors in JSON files because it isn't the handler for those files.  However, the JSON LS should report syntax errors in JSON.  I'll confirm.

**Comment by amcasey** [comment]
I see errors in the JSON file, but I'm also getting an error in the ts file: `"message":"Cannot find module './invalid-file.json'.","start":17,"length":21,"category":"error","code":2307`
@mhegazy ?
