### ISSUE TITLE
Autoimport works incorrect for some node_modules

### ISSUE THREAD

**Issue by cevek** [Microsoft/TypeScript#25465]
**TypeScript Version:**  3.0.0-dev.20180626

**Search Terms:** 

**Code**
After autoimport: 
```ts
import { Field } from '../../node_modules/typegql/types';
```

<img width="614" alt="screen 2018-07-06 01 34 35" src="https://user-images.githubusercontent.com/3171573/42346682-e866b628-80bc-11e8-8f59-e7d10c63b0cd.png">

**Comment by mhegazy** [comment]
Can you try `typescript@next` today and report back?

Also can you share your tsserver log for issues you file in the future. the log helps us diagnose these issues, without it, we will need a repro project/steps to reproduce locally.

You can upload logs using 
1. With "typescript.tsserver.log": "verbose" enabled
2. Restart vscode or vscode insiders
3. Reproduce the problem
4. Run ```code --upload-logs``` on the command line (or ```code-insiders --upload-logs``` if using vscode insiders) and follow instructions
5. Share the log file ID

**Comment by cevek** [comment]
Well, in the latest version works well

**Comment by mhegazy** [comment]
thanks!
