### ISSUE TITLE
Move refactoring is working very buggy

### ISSUE THREAD

**Issue by cevek** [Microsoft/TypeScript#25462]
After some refactoring it mess with files

Video reproduce: https://monosnap.com/file/SQoYp2jHxzUTvFBcTeMqjKBotCFhAl

**TypeScript Version:**  3.0.0-dev.20180626

**Comment by RyanCavanaugh** [comment]
@andy-ms @amcasey says you have a dupe for this one

**Comment by amcasey** [comment]
I thought it might be https://github.com/Microsoft/TypeScript/issues/25327.

**Comment by mhegazy** [comment]
Can you please share your tsserver log?

**Comment by cevek** [comment]
[tsserver.log.zip](https://github.com/Microsoft/TypeScript/files/2170403/tsserver.log.zip)

**Comment by andy-ms** [comment]
@cevek It looks like you're testing this out on a sample project `foo`, so would you mind sharing it? (Can't tell `tsconfig.json` from the video)

**Comment by cevek** [comment]
Yeah sure 
[test.zip](https://github.com/Microsoft/TypeScript/files/2180189/test.zip)

**Comment by andy-ms** [comment]
I think this is failing for the same reason as Microsoft/vscode#53681. `a.ts` doesn't contain the string `export` so no update happens. @mjbvz In the next vscode insiders release, `getEditsForFileRename` should be called unconditionally as long as the TypeScript version isn't 2.9, right?

**Comment by mjbvz** [comment]
Yes
