### ISSUE TITLE
After discard all changes in git tsserver is still working with old deleted files

### ISSUE THREAD

**Issue by cevek** [Microsoft/TypeScript#25467]
**TypeScript Version:**  3.0.0-dev.20180626

![fat ts deleted from disk deleted from disk nutrition 2018-07-06 02-24-56](https://user-images.githubusercontent.com/3171573/42348700-e142105c-80c3-11e8-83c1-2104c075d45b.jpg)

**Comment by RyanCavanaugh** [comment]
Please provide repro steps

**Comment by cevek** [comment]
```
mkdir test
cd test
git init 
tsc --init
mkdir foo
echo 'import {b} from "./b"; const  a = b + k' >foo/a.ts
echo 'export const b = 1' >foo/b.ts
git add .
git commit -m 'Init'
```
Next in the video: https://monosnap.com/file/E1r9UbNpoM4tjCGIrck9Aoa3tpHfuW

**Comment by sheetalkamat** [comment]
This seems like a vscode issue. Moving it to that repo with the findings from the investigation
