### ISSUE TITLE
Add typings for PerformancePaintTiming

### ISSUE THREAD

**Issue by bfrost2893** [Microsoft/TypeScript#25461]
**TypeScript Version:**  3.0.0-dev.201xxxxx

**Search Terms:** paint, timing, performance types

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.

const paintEntryList = window.performance.getEntriesByType('paint');

paintEntryList.forEach((paintEntry: PerformancePaintTiming) => {
  console.log(paintEntry.name, paintEntry.startTime);
});
```

**Expected behavior:**

`PerformancePaintTiming` is defined, since it has a [spec](https://www.w3.org/TR/paint-timing/) and [MDN documentation available](https://developer.mozilla.org/en-US/docs/Web/API/PerformancePaintTiming).

**Actual behavior:**

`PerformancePaintTiming` is not defined and I need to locally polyfill. Definitions exist for `PerformanceNavigationTiming` and `PerformanceResourceTiming`.

**Comment by RyanCavanaugh** [comment]
We don't include experimental browser APIs in the shipped DOM .d.ts. Once this is standardized we will add it.

**Comment by bfrost2893** [comment]
Thanks for the response @RyanCavanaugh. Closing the issue.
