### ISSUE TITLE
Literal type `false` unexpectedly widens into type `boolean`

### ISSUE THREAD

**Issue by cliffkoh** [Microsoft/TypeScript#25474]
**TypeScript Version:**  3.0.0-dev.20180705

**Search Terms:** false/true loosened/expanded/loses specificity into boolean

**Code**

```ts
type Foo = FooBase | FooArray;
type FooBase = string | false;
type FooArray = FooBase[];

declare let foo1: Foo;
declare let foo2: Foo;
foo1 = [...Array.isArray(foo2) ? foo2 : [foo2]];
```

**Expected behavior:**
No error.. In the else clause, `[foo2]`, it retains `string | false` so `Array<string | false>`. Logically since everything is taking place in the typings layer, `foo2` should still be strongly bounded to `false` and will never be `true`.

**Actual behavior:**
Errors. In the else clause, `[foo2]`, it expanded/loosened to `string | boolean` so `Array<string | boolean>`.

```
tmp.ts:7:1 - error TS2322: Type '(string | boolean)[]' is not assignable to type 'Foo'.
  Type '(string | boolean)[]' is not assignable to type 'FooBase[]'.
    Type 'string | boolean' is not assignable to type 'FooBase'.
      Type 'true' is not assignable to type 'FooBase'.

7 foo1 = [...Array.isArray(foo2) ? foo2 : [foo2]];
  ~~~~
```

**Playground Link:** [Link](https://www.typescriptlang.org/play/#src=type%20Foo%20%3D%20FooBase%20%7C%20FooArray%3B%0D%0Atype%20FooBase%20%3D%20string%20%7C%20false%3B%0D%0Atype%20FooArray%20%3D%20FooBase%5B%5D%3B%0D%0A%0D%0Adeclare%20let%20foo1%3A%20Foo%3B%0D%0Adeclare%20let%20foo2%3A%20Foo%3B%0D%0Afoo1%20%3D%20%5B...Array.isArray(foo2)%20%3F%20foo2%20%3A%20%5Bfoo2%5D%5D%3B%0D%0A)

**Related Issues:**

**Comment by pedro-pedrosa** [comment]
Possibly related to this:

```ts
function trySomething(x: number) {
    if (x < 0) {
        return {
            result: false,
            message: 'Negative numbers not allowed'
        };
    }
    return {
        result: true,
    };
}

const a = trySomething(-1);
console.log(a.result ? 'Success' : `Error: ${a.message}`);
```

The return type of `trySomething` is `{ result: boolean; message: string; } | { result: boolean; message?: undefined; }` while it should be `{ result: false; message: string; } | { result: true; message?: undefined; }`

If I use `strictNullChecks` and try to use `a.message` I will get an error saying it's possibly undefined.

[Playground link](http://typescriptlang.org/play/#src=function%20trySomething(x%3A%20number)%20%7B%0D%0A%20%20%20%20if%20(x%20<%200)%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20result%3A%20false%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20message%3A%20'Negative%20numbers%20not%20allowed'%0D%0A%20%20%20%20%20%20%20%20%7D%3B%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20return%20%7B%0D%0A%20%20%20%20%20%20%20%20result%3A%20true%2C%0D%0A%20%20%20%20%7D%3B%0D%0A%7D%0D%0A%0D%0Aconst%20a%20%3D%20trySomething(-1)%3B%0D%0Aconsole.log(a.result%20%3F%20'Success'%20%3A%20%60Error%3A%20%24%7Ba.message%7D%60)%3B)

**Comment by Ghabriel** [comment]
@pedro-pedrosa I don't think it's related, TS always widens literals like that unless you do something like this, which [works](http://www.typescriptlang.org/play/#src=function%20trySomething(x%3A%20number)%20%7B%0D%0A%20%20%20%20if%20(x%20%3C%200)%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20result%3A%20false%20as%20false%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20message%3A%20'Negative%20numbers%20not%20allowed'%0D%0A%20%20%20%20%20%20%20%20%7D%3B%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20return%20%7B%0D%0A%20%20%20%20%20%20%20%20result%3A%20true%20as%20true%2C%0D%0A%20%20%20%20%7D%3B%0D%0A%7D%0D%0A%0D%0Aconst%20a%20%3D%20trySomething(-1)%3B%0D%0Aconsole.log(a.result%20%3F%20'Success'%20%3A%20%60Error%3A%20%24%7Ba.message%7D%60)%3B):
```ts
function trySomething(x: number) {
    if (x < 0) {
        return {
            result: false as false,
            message: 'Negative numbers not allowed'
        };
    }
    return {
        result: true as true,
    };
}

const a = trySomething(-1);
console.log(a.result ? 'Success' : `Error: ${a.message}`);
```

**Comment by pedro-pedrosa** [comment]
Okay that probably makes some sense, typescript probably doesn't want to make the type too strict as users of the function may want to write values to the return value of the function.

**Comment by cliffkoh** [comment]
Note that there isn't a bug with string literal types, only false/true into boolean

```
type Foo = FooBase | FooArray;
type FooBase = 'blah' | 'mah';
type FooArray = FooBase[];

declare let foo1: Foo;
declare let foo2: Foo;
foo1 = [...Array.isArray(foo2) ? foo2 : [foo2]];
```

This works. type of `[foo2]` in the conditional does not get widened into `string | string`.

**Comment by ahejlsberg** [comment]
This is an issue resulting from two separate factors:

* We have non-widening forms of the string and numeric literal types (#11126), but the `true` and `false` literal types and enum literal types are always considered widening.
* Spread expressions aren't considered to have a contextual type.

Because the array literal `[foo2]` occurs in a spread expression it isn't contextually typed by `FooBase` (the type of `foo1`) and therefore the `string | false` type is widened to `string | boolean`. This very similar assignment has no issues because the contextual type propagates appropriately:

```ts
declare let fa: Foo[];
declare let foo2: Foo;
fa = Array.isArray(foo2) ? foo2 : [foo2];
```

To fix this issue we need to propagate contextual types into spread expressions.

**Comment by CS-Jfilmer** [comment]
Sorry, I feel like the answers I need are in this / #22596 but I can't grok it for the life of me

	function x<Arg1, Arg2 extends (Arg1 extends true ? string[] : string)>(arg2IsArray: Arg1, arg2: Arg2){
	}
	
	x(true, 'string') // no error
	x(true, ['string']) // no error
	
	x(true as true, 'string') // error
	x(true as true, ['string']) // no error

Is it that "true" means "boolean" if used in certain contexts to support

	const x = true // x is a boolean not literally "true"?

But I just tried that and ts seems to think that x is just true not a boolean, idk. Anyway is there anyway to have the above example work without having to use `true as true`?
