### ISSUE TITLE
warn about conflicts at renaming

### ISSUE THREAD

**Issue by zpdDG4gta8XKpMCd** [microsoft/TypeScript#25478]
## Search Terms

https://github.com/Microsoft/TypeScript/issues?utf8=%E2%9C%93&q=is%3Aissue+rename+conflict

## Suggestion

renaming doesn't account for possible conflict which can be either good or bad, but in any case it should be a conscious decision of a developer, so please in case of conflicts shoot out a warning

**Comment by RyanCavanaugh** [comment]
Doesn't seem like anyone noticed
