### ISSUE TITLE
If call doesn’t resolve to an overload signature, issue a better error when the implementation would work

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#25488]
```ts
interface Foo { hello: string };

function bar1(...foos: Foo[]) {
    bar2(...foos);
}

function bar2(foo1: Foo);
function bar2(foo1: Foo, foo2: Foo);
function bar2(...foos: Foo[]) {
    return;
}
```

Here we provide an error message like

```
Expected 1-2 arguments, but got 0 or more.
```

I just spoke to three engineers who had no indication of what was actually going wrong. We should

* Inform the user that implementation signatures aren't part of the overload set, and that they should consider making the overload an implementation signature
* Provide a quick fix to do so.

**Comment by RyanCavanaugh** [comment]
I'm worried this will be misleading in a lot of cases

**Comment by DanielRosenwasser** [comment]
I agree, but we should run it on user tests and the RWC.

**Comment by DanielRosenwasser** [comment]
Turns out this is a duplicate of #4797. Two Dans can't be wrong.
