### ISSUE TITLE
JSDocs @typedef {typeof import()} doesn't work with @ts-check pragma (throws "not a module")

### ISSUE THREAD

**Issue by donaldpipowitch** [Microsoft/TypeScript#25480]
**TypeScript Version:**  3.0.0-dev.201xxxxx and 2.9.2

**Search Terms:** 

- JSDoc
- typedef
- import
- ts-check

**Code**

Having `jest` and `@types/jest` installed this snippet...

```ts
/** @typedef {typeof import('jest')} */

/** @type jest.ProjectConfig */
const config = {
  collectCoverage: true,
  coverageReporters: ['text'],
  transform: {
    '^.+\\.(ts?|tsx?)$': '<rootDir>/node_modules/ts-jest/preprocessor.js'
  },
  testRegex: '(/tests/.*)\\.unit\\.(ts?|tsx?)$',
  testPathIgnorePatterns: ['/node_modules/', '/tests/helper/'],
  moduleFileExtensions: ['ts', 'tsx', 'json', 'js']
};

module.exports = config;
```

...seems to correctly use `ProjectConfig`. But when I add `// @ts-check` in the first line I get an error.

**Expected behavior:**

No error. Just more type checks. (E.g. `// @ts-check` I could set `collectCoverage: 'foo'` without an error.)

**Actual behavior:**

`/** @typedef {typeof import('jest')} */`: `File '../node_ modules/@types/jest/index.d.ts' is not a module.`

**Related Issues:** 

- For the general importing (without `// @ts-check`): https://github.com/Microsoft/TypeScript/issues/14377

**Comment by mhegazy** [comment]
the file `@types/jest/index.d.ts` is not a module. that can be a .d.ts error that can be fixed by sending a PR to DT. `jest` is defined as a global namespace.

**Comment by donaldpipowitch** [comment]
Thank you for the fast response!

**Comment by donaldpipowitch** [comment]
Looks like I need to write this:

```ts
// @ts-check

/** @type {jest.InitialOptions} */
const config = {};

module.exports = config;
```

This already works.
