### ISSUE TITLE
Compile error reporter fails to give message

### ISSUE THREAD

**Issue by alexeagle** [Microsoft/TypeScript#2549]
With compiler at HEAD, I often see missing messages in diagnostics. I can provide a minimal repro if you need.
```
angular2/src/facade/collection.es6(18,73): 2345 [object Object]
...
angular2/src/facade/lang.es6(204,12): 2322 [object Object]
```

**Comment by alexeagle** [comment]
Sorry, this is with compiler at HEAD

**Comment by mhegazy** [comment]
@alexeagle I will need some more details.

**Comment by alexeagle** [comment]
I couldn't make a repro with tsc, so the cause must be gulp-typescript plugin, which is producing the error messages.

Sure enough,
https://github.com/ivogabe/gulp-typescript/blob/master/lib/project.ts#L268
does string concat on the messageText of a diagnostic from the compiler, but in my bad case the compiler sometimes puts an object rather than a string in that property, eg:
```
{ file:
   { pos: 0,
     end: 6464,
     text: 

     ...
   
  start: 4548,
  length: 118,
  code: 2322,
  category: 1,
  messageText:
   { messageText: 'Type \'{ multiple: RegExp; single: RegExp; }\' is not assignable to type \'RegExp\'.',
     category: 1,
     code: 2322,
     next:
      { messageText: 'Property \'exec\' is missing in type \'{ multiple: RegExp; single: RegExp; }\'.',
        category: 1,
        code: 2324,
        next: undefined } } }
```

will file the bug there
