### ISSUE TITLE
Smarter case selection for overloaded functions

### ISSUE THREAD

**Issue by bcherny** [Microsoft/TypeScript#25497]
Please close if this has been asked before - I didn't find anything via search.

## Search Terms

Function, overload, multiple signature, discriminate, union

## Suggestion

TypeScript should take advantage of refinement to infer which case of an overload we're in.

## Use Cases

This would improve the ergonomics of using overloaded function call signatures, and make implementing overloaded functions less tedious.

## Examples

```ts
type Reservation = void

type Reserve = {
  (from: Date, to: Date, destination: string): Reservation // 1
  (from: Date, destination: string): Reservation // 2
}

let reserve: Reserve = (from: Date, toOrDestination: Date | string, destination?: string) => {
  if (toOrDestination instanceof Date) {
     destination.toUpperCase() // TSC should infer we're in case 1, so destination must be a string
  }
}
```

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
  * It might catch real errors
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

## Related

- https://github.com/Microsoft/TypeScript/issues/25352
- https://github.com/Microsoft/TypeScript/issues/23616

**Comment by RyanCavanaugh** [comment]
Looks like #14515 ?

**Comment by bcherny** [comment]
Dup of #14515.
