### ISSUE TITLE
Non-intuitive behavior of literal type inference

### ISSUE THREAD

**Issue by user471** [Microsoft/TypeScript#25502]
For example `foo1` and `foo2` have type `"foo"`, so when I look at this code
```
var x = foo1
var y = foo2
```
I expect that `x` and `y` have type `"foo"` as well, but
```
const foo1: "foo" = "foo"
const foo2 = "foo"
var x = foo1
var y = foo2
```
`x` has type `"foo"` and `y` has type `"string"`

**Comment by cqww** [comment]
const foo1:”foo” means to declare foo1 has type foo. 
const foo2 = “foo” means “foo” is a string, so foo2 has default type string.
focus on “:”

**Comment by kitsonk** [comment]
`var` imply re-assignability... if the type was narrowed to the literal type, then you could not reassign values.  Where it is safe to assume with `const`, where re-assignment cannot occur and primitive values cannot be changed that the narrower literal type is valid.  It is actually intuitive from my perspective.

**Comment by user471** [comment]
>const foo2 = “foo” means “foo” is a string, so foo2 has default type string.

`foo2` has type `"foo"` you can check it here http://www.typescriptlang.org/play/#src=const%20foo1%3A%20%22foo%22%20%3D%20%22foo%22%0Aconst%20foo2%20%3D%20%22foo%22%0Avar%20x%20%3D%20foo1%0Avar%20y%20%3D%20foo2

**Comment by user471** [comment]
>var imply re-assignability... 

Problem is not with `var` but with these two lines 
```
const foo1: "foo" = "foo" 
const foo2 = "foo"
```
They have different behavior but I think they should have the same

**Comment by ajafff** [comment]
An explicit literal type annotation creates a non-widening type. If you search the PRs for "widening" you will find the pull requests that introduced this with a good explanation.

**Comment by user471** [comment]
@ajafff Now I understand why it's non-intuitive. 
There are two kinds of literal type widening and non-wideninig, but compiler doesn't show this information. 
Maybe `foo1` or `foo2` could have an additional type information like 
`foo1` has type `"foo" non-widening` or `foo2` has type `"foo" widening`

**Comment by krryan** [comment]
I, for one, have never found the widening useful and consider the arcane rules behind when it does and doesn't happen just a source of annoyance and confusion.

**Comment by RyanCavanaugh** [comment]
We didn't just invent the concept of non-widening types to make our lives harder and your lives more confusing 😉 - extremely common patterns in code get broken (in both directions) without the distinction.
