### ISSUE TITLE
Missing comma to the end of esModuleInterop property on tsconfig.json

### ISSUE THREAD

**Issue by Narven** [microsoft/TypeScript#25514]
When generating the `tsconfig.json` using `tsc --init`, it contains `"esModuleInterop": true` without a comma in the end. Is not a huge problem till when you enable any of the configurations that come after `"esModuleInterop": true`.

Still not a huge bug. But it can be annoying if you using a external tool to parse and enable the tsconfig.json.

Tested with `typescript@next` and `typescript@2.9.2`, and I think it's been there for a while now.

**Expected behavior:**
```
"esModuleInterop": true,
```

**Actual behavior:**
```
"esModuleInterop": true
```

Url for default tempalte: https://gist.github.com/Narven/8d4cff1b9e2bdd7a0b86d35c09b8b4a6

**Comment by RyanCavanaugh** [comment]
Specifically going to block out an hour for the whole team to bikeshed this one 😆

**Comment by RyanCavanaugh** [comment]
This doesn't seem to have bothered anyone else, and I'm sure others would find it distasteful
