### ISSUE TITLE
StrictNullChecks seems to fail for re-initialized arguments

### ISSUE THREAD

**Issue by ORESoftware** [Microsoft/TypeScript#25512]
I have the following code:

```js
export const stdMarker = '@json-stdio';
export const stdEventName = '@json-stdio-event';

export const createParser = function (marker?: string, eventName?: string) {

  marker = marker || stdMarker;
  eventName = eventName || stdEventName;

  let lastLineData = '';

  const strm = new stream.Transform({

    objectMode: true,

    transform(chunk: any, encoding: string, cb: Function) {

      let data = String(chunk);
      if (lastLineData) {
        data = lastLineData + data;
      }

      let lines = data.split('\n');
      lastLineData = lines.splice(lines.length - 1, 1)[0];

      lines.forEach(l => {
        try {
          // l might be an empty string; ignore if so
          l && this.push(JSON.parse(l));
        }
        catch (err) {
          // noop
        }
      });

      cb();

    },

    flush(cb: Function) {
      if (lastLineData) {
        try {
          this.push(JSON.parse(lastLineData));
        }
        catch (err) {
          // noop
        }
      }
      lastLineData = '';
      cb();
    }
  });

  strm.on('data', function (d: ParsedObject) {
    if (d && d[marker] === true) {
      strm.emit(eventName, d);
    }
  });

  return strm;

};
```

If I turn on strictNullChecks to true in my tsconfig, I get an error on these lines:

```js
    if (d && d[marker] === true) {
      strm.emit(eventName, d);
    }
```

It gives me these two errors:

![screenshot from 2018-07-08 22-51-51](https://user-images.githubusercontent.com/11139560/42432860-8d0fa5cc-8301-11e8-8e52-54583fe37fc6.png)

![screenshot from 2018-07-08 22-51-42](https://user-images.githubusercontent.com/11139560/42432862-90bb02ac-8301-11e8-96d2-71cdef9fccef.png)

These errors seems unnecessary, given these two lines:

```js
  marker = marker || stdMarker;
  eventName = eventName || stdEventName;
```

how can I remedy?

**Comment by DanielRosenwasser** [comment]
My understanding is that because you're using `marker` in a function expression, the type-checker always falls back to the original declared type because it doesn't know when the function will be called.

> how can I remedy?

Easiest way is to use default initializers:

```ts
export const createParser = function (marker = stdMarker, eventName = stdEventName) {
    // ....
}
```

Only issue is they have subtle differences from `||` in case you ever pass in an empty string.

**Comment by MartinJohns** [comment]
`marker` and `eventName` are both mutable variables. They could be changed between the assignment within the function and the invocation of your callbacks. There are several issues regarding this in this repository, so this is a duplicate.

A workaround could be to explicitly create new `const` variables, e.g. `const newMarker = marker || stdMarker`.

**Comment by ORESoftware** [comment]
got it, thanks for your help, I can work with that

**Comment by ORESoftware** [comment]
Well, here is the thing, since they are strings, and being passed in the function, and inside the function they aren't being mutated, I was think TS would know that they are constant.

**Comment by AlCalzone** [comment]
Correct me if I'm wrong, but I think the underlying assumption is that TS cannot know if the variables are mutated between the end of your `createParser` function and the invocation of the `on("data")` callback.
