### ISSUE TITLE
composite: true leads to inconsistent TSServer state

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#25528]
```ts
// src/client/index.ts
import { shared } from/**/

export function client() {
    shared()
}
```

```json5
// src/client/tsconfig.json
{
    "compilerOptions": {
        "strict": true,
        "module": "esnext",
        "moduleResolution": "node",
        "outDir": "../../lib/foo",
        "composite": true
    }
}
```

```ts
// src/shared/index.ts
export function shared() {

}
```

From `/**/`, insert

```
 "../shared"
```

Now erase all the following text:

```
 from "../shared"
```

Now enter the following text:

```
 from "
```

Now request completions. You'll get completions for `client` and `shared` (which is unexpected).

Complete on `shared`

Notice the error messages don't correspond with the actual buffer text.

**Comment by RyanCavanaugh** [comment]
Very likely the same root cause as #25527 - once program creation fails, everything is 🤷‍♂️ 💀 💣

**Comment by mhegazy** [comment]
Please reopen if you are still seeing this on latest.
