### ISSUE TITLE
getEditsForFileRename missing change 2

### ISSUE THREAD

**Issue by amcasey** [Microsoft/TypeScript#25536]
Config/tsconfig.json
```json
{
  "files": [
    "../Script/file1.js",
    "../Script/file2.js"
  ]
}
```

Script/file1.js
```js
import "./file1";
export const c = 1;
```

Script/file2.js
```js
import { c } from "./file1";
c;
```

In VS, rename file1.js to file3.js.

Expected: All three files are updated
Actual: file2.js is not updated

Expected: file3.js is in the configured project Config/tsconfig.json
Actual: file3.js is in Miscellaneous Files (i.e. the inferred project) and closing and re-opening it doesn't help

**Comment by amcasey** [comment]
Probably related to #25327.

**Comment by andy-ms** [comment]
Since `tsconfig.json` is in a separate directory, we never find it when looking for a config for `file1.js` (we only look in parent directories). If we don't have a config we only know about files that have been opened so far. That means if you haven't opened `file2.js` yet, we don't know about it and don't update it. I've tested and it works if I open `file2.js` before doing the rename.

**Comment by andy-ms** [comment]
Marking as a design limitation since we would have to search the whole file system looking for `tsconfig.json`s.

**Comment by amcasey** [comment]
Oops, I totally forgot to mention the file states.  Yes, tsconfig.json and file1.js were open, file2.js was closed.  Having file1.js and the tsconfig.json file open doesn't help?

**Comment by andy-ms** [comment]
I don't think opening a `tsconfig.json` file in the editor normally affects tsserver -- vscode doesn't seem to send an `open` event. @sheetalkamat might know more.

**Comment by sheetalkamat** [comment]
@andy-ms is right. json files arent opened through tsserver and for ts/js files the config files are looked only in ancestor directories.

**Comment by amcasey** [comment]
But the configured project is open, isn't it?  Because file1.ts is open?  Would it make sense to also search open projects?

**Comment by andy-ms** [comment]
There won't be a configured project if the config file isn't found, it will just be an inferred project.

**Comment by amcasey** [comment]
I moved the tsconfig into the same folder as the scripts (and updated the paths accordingly), but the closed file (file2.js) is still not updated.

**Comment by amcasey** [comment]
Does the folder containing the tsconfig have to be a strict ancestor?

**Comment by amcasey** [comment]
I tried the same thing in VS Code 1.25.0-insider (26eb2a9af5827d71e1f65096c0ce712c5ad2740d) and only file1.js was updated (not tsconfig.json or file2.js).

**Comment by amcasey** [comment]
I tried again with the tsconfig in a parent directory and then again without a `files` property.  At the moment, I'm unable to find a case where a closed file in a configured project is updated based on a file rename.

**Comment by mhegazy** [comment]
@andy-ms can you take a look at the closed file case @amcasey mentioned?

**Comment by amcasey** [comment]
Oops, I switched from ts to js without thinking about it and forgot to add `allowJs` - that's why the closed file wasn't being updated.

**Comment by amcasey** [comment]
Question: should tsconfig.json warn when the `files` list contains files that won't be compiled?

**Comment by amcasey** [comment]
@andy-ms, the possibly related "deleted files" issue was filed as https://github.com/Microsoft/vscode/issues/53466.
