### ISSUE TITLE
`const x = require("m")` should create an alias symbol

### ISSUE THREAD

**Issue by andy-ms** [microsoft/TypeScript#25533]
**TypeScript Version:**  3.0.0-dev.20180707

**Code**

```ts
/// <reference path='fourslash.ts'/>

// @allowJs: true

// @Filename: /a.js
////function [|{| "isWriteAccess": true, "isDefinition": true |}x|]() {};
////module.exports = [|x|];

// @Filename: /b.js
////const [|x|] = require("./a");
////[|x|];

const [r0, r1, r2, r3] = test.ranges();
verify.referenceGroups(r2, [/*todo*/]);
```

**Expected behavior:**

`x` in `const x` is an alias of the `x` in `function x() {}`, so all references are found.

**Actual behavior:**

`x` is a variable that happens to be the same type as the other `x`. Only references in `b.js` are found.

**Comment by sandersn** [comment]
The in-file type of commonjs modules is usually wrong, so I'll have to fix bugs related to that before aliasing will really make sense. I will look at #25621 first.

**Comment by andy-ms** [comment]
The test from the original post still isn't returning results in `a.ts`.

**Comment by sandersn** [comment]
Turns out github didn't recognise that the "fix #xxxx" syntax occurred in a conditional clause and unconditionally closed this issue. :) Thanks for re-opening.

**Comment by sandersn** [comment]
Note that the type of `module.exports` inside a module is now correctly checked, which unblocks fixing this issue.
