### ISSUE TITLE
[loc][Query][TypeScript] Localizability of 0; "LintClosedFiles"

### ISSUE THREAD

**Issue by PDostalek** [Microsoft/TypeScript#25544]
**Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.
Please re-assign back to use in case you are not the right contact person or you can´t assign to a proper person.
Can you help please?
Thanks!**

**Source:**
_Lint all files included in project, even closed files

**File Name:**
LanguageService\TypeScriptLanguageService\bin\Release\localize\ENU\Microsoft.CodeAnalysis.TypeScript.EditorFeatures.dll

**Resource ID:**
0; "LintClosedFiles"

**Query:**
Should the "Lint" read as "List"?

**Comment by mhegazy** [comment]
"lint" here refers to a linting tool such as eslint (https://eslint.org/).

A linter is a code analysis tool that flags style issues that are not checked by the compiler. More at https://en.wikipedia.org/wiki/Lint_(software)

**Comment by PDostalek** [comment]
Thanks for confirmation.
