### ISSUE TITLE
Proposal, async, await, promise, holistic, language improvement tweak, with idea of were Javascript, TypeScript, nodeJS, c# have and are heading, to simplify things

### ISSUE THREAD

**Issue by wesleyolis** [Microsoft/TypeScript#25554]
Hi,

I feel that it would be a good thing that typescript be aware of this proposal that will affect both typescript and javascript in the future as they may want to contribute at a technical level to any insight they may have, because this has been done with a focus on the bigger picture of all languages, however, small the little roll they play.

https://github.com/tc39/ecma262/issues/1258

Document:

https://docs.google.com/document/d/1QigfqvlM2vMNl-4szjuPj9tFXIQle2zsbrsnze9bAIU/edit?usp=sharing

**Comment by kitsonk** [comment]
TypeScript, currently, does not consider implementing anything until it is [Stage 3](https://tc39.github.io/process-document/).  For clarity of the issues here, it would be well advised to not even raise it until it is Stage 1 in my opinion.  There are a lot of ideas and the TC39 process is a good process to ensure that people focus on the ones that have a level of consensus.

**Comment by wesleyolis** [comment]
@mhegazy HI, If you could please just keep this in mind, because this has a little bit of bleed with latest development, which would now affect typescript.

@kitsonk Yet to have any feedback or mailing list feed back from TC39, still blocked, so have submitted to the next closes thing I could find to create a record on github issues of TC39.


### Change E: Async Pattern

One grip, the introduce of the async keyword modifier, should not enforce a default promise or task library to be used(shim), but on a library implementation that means a certain interface requirement be met. Which means the ecosystem is still open innovation as provide async, await conforming implementation for the return type of promise or task that implements the behaviour interface. We also can import multiple different async library versions and they can all work together in the same file, with no issues. This means the way in which we deal with async type code with await, async approach, is also future proofed any other similar patterns to which async await lend themselves to, were may be more specialized threading functionality developed.

This interface is to be implemented by a promise library, which once imported,
will register this function with the async harnus provided by typescript.
Typescript must support multiple harnus implementations.
Async hardnus life cycle only exist for the period that it is imported.
Typescript, will iterate all registered implementations of AsyncPatternBase to find the appropriate matching AsycBase type implementation, implementation functions to call.

// This interface is the contract behaviour that each promise library would be required to implement at minimum, to work with async pattern.
```.ts
Interface AsyncBase
{
New : ..
Then :
Catch :
Callback :
Resolve :	// internal
Cancel :	// ability to terminate.
Convert : 	// convert a promise from another library, circular reference, warning
}
```
// wire up the async pattern behaviour for each library to be registered with the async pattern harnus.
```.ts
Interface AsyncPatternBase<T extends AsyncBase>
{
	readableSufficForFunctionContainingAsyncWorkLoad : string
	readableSuffixForAsyncReturn: string
	async: : <T>(fun : () => T) => Wrapper<T>
await : <T>(Wrapper<T>) => T 
}
```
