### ISSUE TITLE
Inline lambda spacing incorrect.

### ISSUE THREAD

**Issue by JoshMcCullough** [Microsoft/TypeScript#2555]
Take this example:

    myFunction("something", (x, y) => { ... });

When the line is edited and then auto-formatted, the space before the lambda is removed, and this is the result:

    myFunction("something",(x, y) => { ... });
                           ^ -- missing space!

Hard to tell, and petty, but that missing space is driving me crazy as I strive for well organized, easy to read code.  :+1:

**Comment by mhegazy** [comment]
This is fixed in the latest drop from master.

**Comment by JoshMcCullough** [comment]
Great, thanks.
