### ISSUE TITLE
auto-suggest a constant holding a literal value of an expected literal type

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#25553]
```ts
type X: 'x';
const x: X = 'x';
type Y: 'y';
const y: Y = 'y';
type Z = X | Y;
declare const z: Z;
switch (z) {
    case 
      // ^ caret is here
}
```

after pressing Ctrl + Space it would be nice to see these suggestions: `x`, `y`, `'x'`, '`y'`

**Comment by mhegazy** [comment]
`"x"` and `"y"` should already be in the list, see:

![image](https://user-images.githubusercontent.com/8000722/42540753-90656ff0-8454-11e8-8ee9-925b8f421dcd.png)

`x` and `y` (and `z`) is a bit of a stretch. to show them in the completion list the compiler will need to resolve the type of every name visible in the current scope, and compare it to the type from the contextual type at this location. that is a lot of work, and we have a short window to show completions (<= 200ms).
