### ISSUE TITLE
Differentiate between two type aliases.

### ISSUE THREAD

**Issue by bluong** [Microsoft/TypeScript#2556]
Let's say I declared the following types

type Foo;
type FooGenerator = () => Foo;
type FooGeneratorGenerator = () => FooGenerator;

Is there any way to differentiate between FooGenerator and FooGeneratorGenerator?  (If I were to replace Foo with string or so, I can make a differentiation between the first and the second one using typeof it seems, but I still cannot find a difference between the second and third forms)

Note that my use case does have arguments inside the types, but I removed them for simplicity

**Comment by mhegazy** [comment]
I am not sure i understand the question.

> type Foo;

this is syntactically invalid. you need a right hand-side for this alias declaration to be meaningful.

> type FooGenerator = () => Foo;

FooGenerator is a function that takes no arguments and returns a Foo

> type FooGeneratorGenerator = () => FooGenerator;

FooGeneratorGenerator  is a function that takes no arguments and returns a function.

Not sure what you want to do here. can you explain the problem?

**Comment by bluong** [comment]
> type Foo;
I'm just using this to declare some arbitrary type.  If `Foo` was string, then this example would still be valid.

type StringGenerator = () => string;
type StringGeneratorGenerator = () => StringGenerator;

**Comment by mhegazy** [comment]
What do you mean by " differentiate between FooGenerator and FooGeneratorGenerator?"

**Comment by DanielRosenwasser** [comment]
TypeScript traditionally doesn't encode any type information at runtime, and since JavaScript doesn't have this facility, it's not the easiest; that said, it's not the hardest.

```TypeScript
```

**Comment by basarat** [comment]
@bluong I think you are asking: 

```ts
type Foo = any;
type FooGenerator = () => Foo;
type FooGeneratorGenerator = () => FooGenerator;

var foo: Foo;
var fooGenerator: FooGenerator; 
var fooGeneratorGenerator: FooGeneratorGenerator;

// Are they the same or different?
fooGenerator = fooGeneratorGenerator = fooGenerator;
```

Provide a code sample that *doesn't work and should* or *does work and shouldn't*.

**Comment by DanielRosenwasser** [comment]
@bluong it sounds like you're dealing with a value that can be of either type `StringGenerator` or `StringGeneratorGenerator`, and you need to be able to appropriately use it depending on which it is. If this isn't the case, please let me know.

TypeScript traditionally doesn't encode any type information at runtime, and since JavaScript doesn't have any introspection beyond telling you if something is a function, it's not the easiest; that said, here's a super unorthodox way to do it:

```TypeScript
enum FunctionKind {
    StringGenerator
    StringGeneratorGenerator
}

interface Function {
    kind?: FunctionKind 
}

function tagFunction<T>(f: T, tag: FunctionKind): T {
    f.kind = tag;
    return f;
}


type StringGenerator = () => string;
function stringGenerator(f: () => string) {
    return tagFunction(f, FunctionKind.StringGenerator);
}

type StringGeneratorGenerator = () => StringGenerator;
function stringGeneratorGenerator(f: () => StringGenerator) {
    return tagFunction(f, FunctionKind.StringGeneratorGenerator);
}
```

**Comment by danquirk** [comment]
As we have a structural type system the answer is no, you cannot differentiate based on the alias names if they're identical in structure. A more concrete example might be helpful to understand exactly what you're trying to do though, it's possible there's a better option.
