### ISSUE TITLE
Use keyof with namespaces

### ISSUE THREAD

**Issue by tomitrescak** [Microsoft/TypeScript#25574]
## Search Terms

keyof
namespace

## Suggestion

I would like to access all keys from a namespace. This was discussed in #16472 but not result there.

I have a list of types in a file with all database types.
Now I want to design a type safe resolver which has a current shape:

```ts
import * as Types from './types';

// Types has all the database types, e.g.
// Notification, User ...

export type Resolver<T> = {
  [R in keyof Types]: { // fail
    [P in keyof T]: (parent: T, args: any, ctx: Types.Context, info: Types.GraphQLResolveInfo) => any
  }
};

export const resolver: Resolver<Types.Notification> = {
  Notification: {
    text: (parent, _args, ctx, info) => {
      ...
    }
  }
};
```

## Use Cases

Creation of type safe resolver for graphql.

## Examples

Above

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by mhegazy** [comment]
Did you mean `R in keyof typeof Types`?

**Comment by tomitrescak** [comment]
I tried that before, but that returns just one string to me.

Note that almost all exports from types.ts are interfaces.

**Comment by mhegazy** [comment]
that it for you. `keyof` are the keys of a value that exist at runtime. Types (interfaces and type aliases) do not exist at runtime, so they are not "keys". only values have keys.

**Comment by tomitrescak** [comment]
@mhegazy that's so sad to hear ... I know there was a discussion to have `import type` syntax, but I guess that line of development is dead.

**Comment by franciscomerdot** [comment]
Hi there,

@mhegazy there is not a way to add this feature to typescript?, that's very useful, in that way we can implement constrained behaviour based on interfaces re-exporting from a single file/module, normally I constraint my data with interfaces and not with classes.
