### ISSUE TITLE
Duplicated amd-module directives in tsc output when using outfile

### ISSUE THREAD

**Issue by bandersongit** [Microsoft/TypeScript#25588]
**TypeScript Version:**  3.0.0-dev.201xxxxx

**Search Terms:** 
duplicate amd module declarations
outFile produces duplicate module declarations

**Code**

tsconfig.json
```
{
    "compilerOptions":
    {
      "target": "es5",
      "module": "amd",
      "outFile": "build/index.js",
      "declaration" : true,
      "allowJs": false,
      "stripInternal": true,
      "emitDeclarationOnly": true
    },
    "include": [
      "src/SomeModule.ts"
    ]
}
```
SomeModule.ts
```ts
/// <amd-module name="mynamespace::SomeModule" />
export class SillyClass {
    private readonly _foo: string;
    constructor() {
        this._foo = "bar";
    }
}
```

after running tsc -p tsconfig.json, the generated typings file looks like this

build/index.d.ts (contains duplicated <amd-module> declaration)
```ts
/// <amd-module name="mynamespace::SomeModule" />
/// <amd-module name="mynamespace::SomeModule" />
declare module "mynamespace::SomeModule" {
    export class SillyClass {
        private readonly _foo;
        constructor();
    }
}
```

**Expected behavior:**
build/index.d.ts should look like
```ts
/// <amd-module name="mynamespace::SomeModule" />
declare module "mynamespace::SomeModule" {
    export class SillyClass {
        private readonly _foo;
        constructor();
    }
}
```

**Actual behavior:**
build/index.d.ts looks like 
```ts
/// <amd-module name="mynamespace::SomeModule" />
/// <amd-module name="mynamespace::SomeModule" />
declare module "mynamespace::SomeModule" {
    export class SillyClass {
        private readonly _foo;
        constructor();
    }
}
```

**Github example**  
https://github.com/bandersongit/typescript-duplicate-amd-module-name-issue/tree/master

**Comment by tylerfurtwangler** [comment]
This is easy to reproduce and stopped working after build 2.8.4.  Any release after this build exhibits this behavior and prevents the amd name directive from working with outfile.  

Uploaded project can be built with tsc and generates invalid d.ts files as well as a rogue /// <amd-module name"" /> directive in the resulting js.

Is this a verified issue and any update on a fix (the milestone keeps getting pushed back but looks to have been introduced in 2.9)?

Potential PR that seems likely to have introduced this:
* https://github.com/Microsoft/TypeScript/pull/22740

[amdModuleExample.zip](https://github.com/Microsoft/TypeScript/files/2567685/amdModuleExample.zip)
