### ISSUE TITLE
JS type argument defaulting should give implicit 'any' error

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#25609]
**TypeScript Version:**  3.0.0-dev.20180711

**Code**

**tsconfig.json**
```json
{
    "compilerOptions": {
        "strict": true,
        "allowJs": true,
        "checkJs": true
    }
}
```

**a.js**
```js
/**
 * @template T
 * @return {T}
 */
function f() { return x; }
const x = f();
```

**Expected behavior:**

Error somewhere that `x` is implicitly `any`.

**Actual behavior:**

No error.

**Comment by sandersn** [comment]
This isn't caused by the circular reference. It's the implicit defaulting of type arguments to any in JS. `T` can't be inferred since there aren't any parameters or contextual types, it defaults to `any`. We need to add an implicit any error manually.

**Comment by sandersn** [comment]
Here's a non-circular repro:

```js
/** @type {any} */
const y = 1
/**
 * @template T
 * @return {T}
 */
function f() { return y; }
const x = f();
```

**Comment by sandersn** [comment]
There would be no way to fix this error right now, so I don't think it makes sense to add it. We can revisit later if we need a JS syntax for type arguments.
