### ISSUE TITLE
Allow annotations inside the head of a `for...in` statement

### ISSUE THREAD

**Issue by pretodor** [Microsoft/TypeScript#25605]
Unlike `element` in `for (let element of iterable) {}` and `error` in `try {} catch (error) {}` where `element` and `error` are determined at run-time, `key` in `for (let key in object) {}` is already known to be a string at compile-time.

I propose we accept an annotation for `key`. In other words, the following syntax should be valid:

```
for (let key: string in object) {}
```

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by mhegazy** [comment]
`string` is not accurate here the correct type is `Extract<string, typeof obj>`. Given that the possible types allowed here are limited, allowing an explicit type annotation seems more noise than value.

Please see https://github.com/Microsoft/TypeScript/issues/3500 for related discussion.
