### ISSUE TITLE
Allow declaring expected type of custom unique symbol properties

### ISSUE THREAD

**Issue by shicks** [Microsoft/TypeScript#25601]
## Search Terms

unique symbol property expected type declare global interface object

## Suggestion

A typical use for custom unique symbols exported from a library is to allow clients to add properties or methods to their own classes with that symbol as the key.  In many cases, there is a specific expected type signature for this method, and the library code will expect that any property it finds conforms to this type.  But TS seems to have no way of actually enforcing this.  We can define an interface so that clients can *opt in* to checking, but it should be possible to give an error even if the interface is not explicitly extended.  A straightforward way to do this would be to allow declaring extensions to some sort of global "Object" interface, something like

```ts
const TO_DEBUG_STRING: unique symbol = Symbol();
declare global {
  interface Object {
    [TO_DEBUG_STRING]?: () => string
  }
}
class Foo {
  [TO_DEBUG_STRING]() { return 42; } // want an error here!
}
```

It would be prudent to restrict this to only optional properties on unique symbols, which should (by convention, at least) be owned/exported by the module in which the declaration appears.

The above syntax is valid, but fails to detect that Foo.prototype[TO_DEBUG_STRING] is of the wrong type.

## Use Cases

All existing well-known symbols already fit this pattern:

```ts
declare global {
  interface Object {
    [Symbol.iterator]?: () => Iterator<any>
    readonly [Symbol.species]?: {new(...args: any[]): any}
    [Symbol.split]?: (str: string, limit?: number) => any
    // ...
  }
}
```

Beyond this, it fits very well with the intended purpose of symbols as extension points, and provides much more confidence that any object containing a given symbol property will actually have the right value type, since as long as TS checked the definition, it's guaranteed to be correct.

Certain interfaces, such as Iterable, still make sense, of course.

As far as I can tell, lib.es2015.symbol.wellknown.d.ts already declares these sorts of properties on the built-in types, but it appears to be for declaring that they exist, rather than enforcing the type that they must be on subclasses (and `Object` is notably absent).

Additionally, it reduces the need to assert the type that comes out of accessing the symbol on an arbitrary object:

```ts
function f(x: {}|undefined) {
  const splitter: Function|undefined = x && x[Symbol.split];
}
```

This currently fails to type check, but if we were confident that any assignments to this symbol were type checked on the way in, then it's possible it could actually pass type checking as-is.

EDIT: Added an extra use case about reduce type assertions.

**Comment by mhegazy** [comment]
Declarations on `Object` are not explicitly checked for two main reasons, 1. it is not a recommended practice to depend on changes to global objects in general, and more importantly 2. the compiler makes assumptions about types, and including/checking `Object` members on everything complicates the process significantly, and given that 99.9% of our users do not need that seems like an overkill.

For the outlined scenarios, i would have a type `Splitable`:

```ts
type Splitable = {
    [Symbol.split]?: (str: string, limit?: number) => any
}

function f(x: Splitable | undefined) {
  const splitter: Function|undefined = x && x[Symbol.split];
}

f({}); // OK
f({ [Symbol.split]: 3}); // Error
```

**Comment by shicks** [comment]
The suggested `Splitable` is in fact how it's done currently in the `d.ts` files, but the point is that this is not how symbols are used in practice.  A common use case is that functions accept *any* object (hence `{}`) and do something different if the symbol is present.  So the signature for `f` would, in practice, need to be `function f(x: Splitable | {})`, which is no different from `function f(x: {})`, in that if you pass something that has the wrong type of value on `[Symbol.split]`, it will still match the `{}` option, but then the implementation needs to blindly assume that the value is the correct type, leading to not just unchecked, but totally uncheckable, runtime errors.

Maybe extending `Object` isn't the way to do this, but for (some definition of) well-known symbols, it really should be possible to make it an error to somehow associate a type with the symbol and make it an error to assign any other type to that property on any object.
