### ISSUE TITLE
Explicit spesifiying generic type parameters, while remain should be infer from function parameters

### ISSUE THREAD

**Issue by wesleyolis** [Microsoft/TypeScript#25603]
Expect that the remaining generic type parameters that are not explicitly set, should be inferred from the function parameters.

```.ts
const testsCallBack = {
	test : function (callback : (err : any, result : string) => void)
}

function Prom<R extends any, M extends keyof O = any, O extends {} = any>(object : O, method : M) : void

const sftpWrapper = Prom<ssh2.SFTPWrapper>(testsCallBack, 'test'); // I would expect that the typing engine should infer the remain generics that are not explicitly set.

const sftpWrapper = Prom<ssh2.SFTPWrapper>(testsCallBack, 'tet');// Compiler Error
const sftpWrapper = Prom(ssh2, 'fastGet');// returns a good implementation of the types library
```

Also see post regarding top type unknown, which could also fix this problem, basically comes down to this being a type infer issues/bug in my opion.

https://github.com/Microsoft/TypeScript/pull/24439

**Comment by AlCalzone** [comment]
I think you're looking for https://github.com/Microsoft/TypeScript/pull/23696

**Comment by wesleyolis** [comment]
Their is alot in that post, 
@AlCalzone Their is alot in that post, but basically the typing engine inferring an empty {} for the function call below, cause these to function to also be identical, were the more stricter one is chosen over the less stricter one based on parameters.

Typically I envisage this to be order thing, were one would typically choose the least constraining function call when the type system was to intersect the function type signature.
This is typically not what we want when we wanting to return different return type signature based on input signature, we wan the return type signature to be choose from the function call signature, that has the stricts constrains that match.

What are you toughts regarding that.

```.ts
const testsCallBack = {
	test : function (callback : (err : any, result : string) => void)
}

function Prom<R>(object : {}, method : string) : () => Bluebird<R>
function Prom<O extends {}>(object : O, method : keyof O) : Bluebird<Extract<O>>

const sftpWrapper = Prom(testsCallBack, 'test');

```

**Comment by wesleyolis** [comment]
Looks like I will have to check the next release versions, to see if it is all resolved..
I think the part of concern would be the return type and finding the most restrictive match to return the return type to use.
