### ISSUE TITLE
Emit Use Strict Directive when transpiling ES6 classes and modules

### ISSUE THREAD

**Issue by ajafff** [Microsoft/TypeScript#25617]
## Search Terms

use strict

## Suggestion

Consider emitting `'use strict'` when downleveling ES6 classes and modules. These are strict by default, but the emitted code doesn't contain a Use Strict Directive (unless `alwaysStrict` is enabled). That changes the runtime semantics of the transpiled code.

## Use Cases

```ts
export {};
function foo(param: string) {
  arguments[0] = 'foo';
  console.log(param);
}
foo('bar');
```

https://agentcooper.github.io/typescript-play/?alwaysStrict=false&target=1#code/KYDwDg9gTgLgBAbwL4G4BQAzArgOwMYwCWEOcGEEAFGAIZQ0C2AXHAM4xSE4DmAlImjhw63LA2A4YrANoAGALpwAvHADk5CKvRC8JVhAA2wAHQGI3anUa90STBUqqARnVU2gA

The above code prints `'bar'` when targeting ES6 or above and prints `'foo'` when targeting ES5 and below.

There are other semantic differences like accessing `arguments.callee`, assigning readonly properties, deleting non-configurable properties, ...

I don't know if this is a bug or a feature request. Is this even worth the effort since `--alwaysStrict` is part of `--strict`?

**Comment by mhegazy** [comment]
The behavior here was intentional to avoid breaking existing users. that is why we have added the `--alwaysStrict` flag to let users opt-in. the flag is enabled under `--strict`. and i do not think we have plans on adding `use strict` for users who opted out from `--strict`.

**Comment by ajafff** [comment]
> The behavior here was intentional to avoid breaking existing users.

@mhegazy then what exactly is `--noImplicitUseStrict` for? Looking at the docs I would think the compiler always emits `'use strict'` for ES6 modules and that option can be enabled for backwards compatibility.

**Comment by mhegazy** [comment]
We have stopped recommending `noImplicitUseStrict` at this point. this was an opt-out flag when we started emitting modules with a `"use strict"`.

**Comment by ajafff** [comment]
Got it, thanks.
