### ISSUE TITLE
High CPU usage (tsserver and typingsInstaller)

### ISSUE THREAD

**Issue by robbiespeed** [Microsoft/TypeScript#25629]
**TypeScript Version:**  2.9.2
- VSCode Version: 1.25.0
- OS: Fedora 28

**Search Terms:** 
High cpu, files in excluded folder being watched 

**Steps to reproduce**

Open vscode in an ember-cli project and run `ember s` to build and watch for changes. CPU usage of tsserver and typingsInstaller both jump up to 100% and remain there. typingsInstaller remains open even after vs code is closed, until the process is forcefully killed. 

jsconfig.json:
```
{
  "compilerOptions": {
    "noEmit": true,
    "moduleResolution": "node",
    "lib": [
      "es2018"
    ],
    "target": "es2018",
    "baseUrl": ".",
    "paths": {
      "dugo-web/*": ["app/*"],
      "npm:dugo-lib": ["node_modules/dugo-lib"]
    }
  },
  "include": [
    "app"
  ],
  "exclude": [
    "public",
    "tests",
    "vendor",
    "node_modules",
    "tmp",
    "dist",
    ".git"
  ],
  "compileOnSave": false
}
```

[tsserver.log](https://gist.github.com/robbiespeed/7e226684729a9c81fcbf78d5ea4ea51b#file-tsserver-log)
[ti-19009.log](https://gist.github.com/robbiespeed/7e226684729a9c81fcbf78d5ea4ea51b#file-ti-19009-log)
[ti-18559.log](https://gist.github.com/robbiespeed/7e226684729a9c81fcbf78d5ea4ea51b#file-ti-18559-log)
[ti-18084.log](https://gist.github.com/robbiespeed/7e226684729a9c81fcbf78d5ea4ea51b#file-ti-18084-log)

It's odd to me that although 'tmp' is excluded it is still being watched

**Related Issues:** 
https://github.com/Microsoft/TypeScript/issues/23390
https://github.com/Microsoft/TypeScript/issues/18263

**Comment by sheetalkamat** [comment]
Hi can you try out drop from #25811 to see if you see improvement. Thank you.

**Comment by robbiespeed** [comment]
@sheetalkamat Thank you. I just had a chance to test it out, and it looks like the fix works
