### ISSUE TITLE
Conditional types shortcircuit incorrectly when using mapped types in the condition

### ISSUE THREAD

**Issue by Nimelrian** [Microsoft/TypeScript#25635]
**TypeScript Version:**  3.0.0-dev.20180712

**Search Terms:** conditional Types, shortcircuit, shortcircuiting 

**Code**

```ts
type StripOptionalFromProperties<T> = { [K in keyof T]-?: T[K] };
type MapPropsToString<T> = { [K in keyof T]: string };

type Foo<T> = T extends { val: string } ? true : false;

type FooWithMapped<T> = StripOptionalFromProperties<T> extends { val: string } ? true : false;
type FooWithMapped2<T> = MapPropsToString<T> extends { val: string } ? true : false;

type Bar = { val?: string };
type Bar2 = { val: number };

type MappedBar = StripOptionalFromProperties<Bar>; // { val: string }
type MappedBar2 = MapPropsToString<Bar2>; // { val: string }

type Result1 = Foo<MappedBar> // true - correct
type Result2 = Foo<MappedBar2> // true - correct

type Result3 = FooWithMapped<Bar> // false - wrong!
type Result4 = FooWithMapped2<Bar2> // false - wrong!
```

**Expected behavior:**
All `ResultX` types should be `true`

**Actual behavior:**
`Result3` and `Result4` are `false`
When checking the type of `FooWithMapped` or `FooWithMapped2` it shortcurcuits both to `false`:
![image](https://user-images.githubusercontent.com/8960836/42680795-56782b96-8686-11e8-986a-0a18a18cc820.png)

**Playground Link:**  
https://goo.gl/hgx57H

**Comment by mhegazy** [comment]
We probably should defer the evaluation if the checkType is a mapped type whose type parameter is itself a instantiable...

**Comment by RyanCavanaugh** [comment]
These are now `true` as expected
