### ISSUE TITLE
Release process?

### ISSUE THREAD

**Issue by ffMathy** [Microsoft/TypeScript#25639]
For how long will a release be in RC state before it is released? When will packages be available on NPM? And when it is released, when will it also be released on typescriptlang.org? And from there, when is it typically available for use in the playground?

What I am trying to highlight here is that I think it's important answering these questions somewhere publically in this repository (in the Wiki perhaps), but I haven't been able to find anything regarding it.

**Comment by qcz** [comment]
https://blogs.msdn.microsoft.com/typescript/2017/03/27/typescripts-new-release-cadence/

**Comment by mhegazy** [comment]
> For how long will a release be in RC state before it is released? 

We release the last week of the month. so `typesript@3.0.1` will be released the week of 7/30. The RC is out 2-3 weeks before the final release.

> When will packages be available on NPM? 

`typescript@rc` is already available. `typescript@3.0.1` will be available when we release. see earlier for details.

> when will it also be released on typescriptlang.org

not sure what that means. but we update the playground on the website the same day we release the final release. we do not update for the RC.

>  And from there, when is it typically available for use in the playground?

see above.

> What I am trying to highlight here is that I think it's important answering these questions somewhere publically in this repository (in the Wiki perhaps), but I haven't been able to find anything regarding it.

As @qcz referenced, this is available on our blog: https://blogs.msdn.microsoft.com/typescript/2017/03/27/typescripts-new-release-cadence/
