### ISSUE TITLE
Incorrect overload is used for composed function inside `pipe`

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/TypeScript#25637]
**TypeScript Version:**  2.9.2

**Search Terms:** generic function pipe contextual type wrong overload

**Code**

These examples are stripped down versions of Node's `parse` function in the `querystring` module and Lodash's `values` and `fromPairs` functions.

These are issues we ran into when trying to use these functions with a `pipe` function.

```ts
declare function pipe<A, B, C>(ab: (a: A) => B, bc: (b: B) => C): (a: A) => C;

{
    type ParsedUrlQuery = { [index: string]: string };
    declare function parsedUrlQueryString(str: string): ParsedUrlQuery;
    declare function parsedUrlQueryString<T extends {}>(str: string): T;

    declare const stringToString: (s: string) => string;

    // $ExpectType (a: string) => ParsedUrlQuery
    // but got (a: string) => {}
    // Note: if we comment out the last overload for `parsedUrlQueryString`, we get the expected
    // type.
    const fn = pipe(
        stringToString,
        parsedUrlQueryString,
    );
}

{
    declare function values<T>(object: { [index: string]: T } | null | undefined): T[];
    declare function values<T extends object>(object: T | null | undefined): Array<T[keyof T]>;
    declare function values(object: any): any[];

    declare const stringDictToStringDict: (
        sd: { [index: string]: string },
    ) => { [index: string]: string };

    // $ExpectType (a: { [index: string]: string; }) => string[]
    // but got (a: { [index: string]: string; }) => any[]
    // Note: if we comment out the last two overloads for `values`, we get the expected type.
    const fn = pipe(
        stringDictToStringDict,
        values,
    );
}

{
    declare function fromPairs<T>(pairs: [string, T][] | null | undefined): { [index: string]: T };
    declare function fromPairs(pairs: any[][] | null | undefined): { [index: string]: any };

    // $ExpectType (a: {}) => { [index: string]: number; }
    // but got (a: {}) => { [index: string]: any; }
    // Note: if we comment out the last overload for `fromPairs`, we get the expected type.
    const fn = pipe(
        ({  }: {}): [string, number][] => [['foo', 1]],
        fromPairs,
    );
}
```

**Comment by dardino** [comment]
Hi, I have a similar problem:

[Playground](http://www.typescriptlang.org/play/index.html#src=%0D%0Afunction%20a(value%3A%20any%2C%20replacer%3F%3A%20(string%20%7C%20number)%5B%5D%20%7C%20null%2C%20space%3F%3A%20string%20%7C%20number)%3A%20string%3B%0D%0Afunction%20a(value%3A%20any%2C%20replacer%3F%3A%20((k%3A%20string%2C%20v%3A%20any)%20%3D%3E%20any)%20%7C%20null%2C%20space%3F%3A%20string%20%7C%20number)%3A%20string%3B%0D%0Afunction%20a(value%3A%20any%2C%20replacer%3F%3A%20((k%3A%20string%2C%20v%3A%20any)%20%3D%3E%20any)%20%7C%20(string%20%7C%20number)%5B%5D%20%7C%20null%2C%20space%3F%3A%20string%20%7C%20number)%3A%20string%20%7B%0D%0A%20%20%20%20return%20%22%22%3B%0D%0A%7D%0D%0A%0D%0Avar%20b%20%3D%20(value%3A%20any%2C%20replacer%3F%3A%20((k%3A%20string%2C%20v%3A%20any)%20%3D%3E%20any)%20%7C%20(string%7Cnumber)%5B%5D%20%7C%20null%2C%20space%3F%3A%20string%20%7C%20number)%3A%20string%20%3D%3E%20%7B%0D%0A%20%20%20%20if%20(replacer%20instanceof%20Array%20%7C%7C%20typeof%20replacer%20%3D%3D%3D%20%22function%22)%0D%0A%20%20%20%20%20%20%20%20return%20a(value%2C%20replacer%2C%20space)%3B%0D%0A%7D%0D%0A)

```typescript
function a(value: any, replacer?: (string | number)[] | null, space?: string | number): string;
function a(value: any, replacer?: ((k: string, v: any) => any) | null, space?: string | number): string;
function a(value: any, replacer?: ((k: string, v: any) => any) | (string | number)[] | null, space?: string | number): string {
    return "";
}

var b = (value: any, replacer?: ((k: string, v: any) => any) | (string|number)[] | null, space?: string | number): string => {
    if (replacer instanceof Array || typeof replacer === "function")
        return a(value, replacer, space); // Why ERROR ??? a supports all overloads
}
```

**Comment by OliverJAsh** [comment]
Hey @mhegazy, any idea if this is a bug or design limitation? Hopefully my examples demonstrate the frequency of this issue.

**Comment by mhegazy** [comment]
In @dardino's example the overloads do not include the implementation signature, so there is no overload that accepts `(string | number)[] | ((k: string, v: any) => any)`, only ones that accept `(string | number)[] | null or `((k: string, v: any) => any) | null`.

**Comment by mhegazy** [comment]
In the OP:
first set of overloads, the second overload of `parsedUrlQueryString` seems meaningless. removing it should cause the compiler to infer the right type.
Second and third sets, not sure what is going on, need to debug to figure it out

**Comment by OliverJAsh** [comment]
I simplified the `parsedUrlQueryString` overloads to demonstrate and isolate the issue—the full example does require that overload.

**Comment by dardino** [comment]
> In @dardino's example the overloads do not include the implementation signature, so there is no overload that accepts (string | number)[] | ((k: string, v: any) => any), only ones that accept (string | number)[] | null or((k: string, v: any) => any) | null`.

@mhegazy Sure, but i think this is a bit limiting thing.
in fact I can write this to compile correctly: (that is very heavy)

```typescript
var b = (value: any, replacer?: ((k: string, v: any) => any) | (string|number)[] | null, space?: string | number): string => {
    if (replacer instanceof Array)
        return a(value, replacer, space);
    if (typeof replacer === "function")
        return a(value, replacer, space);
}
```
I believe that is possible to make this assumption:
If all available overloads of a method can be called with current parameters types because they are compatible then the compiler can accept the call without errors:

```typescript
class C1 { P1: string; }
class C2 { P2: string; }
class C3 { P3: string; }

function a(value: C1 | null): string;
function a(value: C2 | null): string;
function a(value: C1 | C2 | null): string {
    return "";
}

var c = (value?: C1 | C2 | C3 | null | undefined): string => {
    if (value instanceof C1 || value instanceof C2)        
        return a(value); // C1 | C2  --> not null or undefined, there is no reasons to give an error...
        // is a(C1) a valid call? YES
        // is a(C2) a valid call? YES
        // why error? 
    return value ? value.P3 : "";
}

var b = (value?: C1 | C2 | C3 | null | undefined): string => {
    if (value instanceof C1) return a(value);  // C1
    if (value instanceof C2) return a(value);  // C2
    return value ? value.P3 : "";
}
```

**Comment by OliverJAsh** [comment]
@dardino This issue is concerning overloads when used with a `pipe` function, which doesn't appear to be the case with your issue. Perhaps you could open a new issue to avoid conflating the issue being tracked here?

**Comment by dardino** [comment]
ok

**Comment by weswigham** [comment]
Ref https://github.com/DefinitelyTyped/DefinitelyTyped/pull/28592 which seems to have been motivated by this.

**Comment by OliverJAsh** [comment]
Revisiting this. I believe the issue can be narrowed down to:

``` ts
{
    // https://github.com/Microsoft/TypeScript/issues/25637

    declare const pipe: {
        <A, B, C>(ab: (a: A) => B, bc: (b: B) => C): (a: A) => C;
    };

    declare const myFn: {
        (p: string): string;
        (p: any): number;
    };

    // Expected type: `(a: string) => string`
    // Actual type: `(a: string) => number`
    // Note: if we comment out the last overload for `myFn`, we get the expected
    // type.
    const fn = pipe(
        (s: string) => s,
        myFn,
    );
}
```

Any ideas @weswigham? Does this help?

**Comment by RyanCavanaugh** [comment]
This is definitely #10957 - overloads aren't considered during generic inference

**Comment by jack-williams** [comment]
You may rest now bot.
