### ISSUE TITLE
map with rest tuple missing length

### ISSUE THREAD

**Issue by Kingwl** [Microsoft/TypeScript#25632]
**TypeScript Version:**  3.0.0-dev.201xxxxx

**Search Terms:** 
tuple, rest, map

**Code**
```ts
declare const a: [number, ...number[]]
const b = a.map(x => x.toString()) // b: string[]
```

**Expected behavior:**
b is `[string, ...string[]]`
**Actual behavior:**
b is `string[]`
**Playground Link:**  

**Related Issues:**

**Comment by mhegazy** [comment]
The `map` declaration relies on the underlying array type, which in this case is `number`. to change that we will need first a new base type for tuples, and some way to construct these tuples from in the return type of `map`.
