### ISSUE TITLE
an object instance does not instanceof it's class

### ISSUE THREAD

**Issue by molihub** [Microsoft/TypeScript#25640]
**TypeScript Version:**  2.9.2

**Search Terms:** 
instanceof 

**Code**
```ts
class MyError extends Error {
    name: string;
    constructor() {
        super();
        this.name = "MyError";
    }
}
// MyError.prototype = new Error();

const m = new MyError();
if (m instanceof MyError) {
    console.info("OK.");
}
else {
    console.error("Error.");
}

// console.log(m instanceof MyError, m instanceof Error);
// console.log(
//     "\n1", MyError.toString(),
//     "\n2", MyError.prototype,
//     "\n3", MyError.prototype.__proto__,
//     "\n4", m.toString(),
//     "\n5", Object.getPrototypeOf(m),
// );
```

**Expected behavior:**
output: OK.

**Actual behavior:**
output: Error.

**Comment by MartinJohns** [comment]
Your implementation is incorrect.

https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#extending-built-ins-like-error-array-and-map-may-no-longer-work

**Comment by molihub** [comment]
Althoght I think that is really not a good design because of anti-OOP，but anyhow, it's not a bug, I think .
Thank you for your quickly answer!

**Comment by RyanCavanaugh** [comment]
It's also in the ✨ [FAQ](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-doesnt-extending-built-ins-like-error-array-and-map-work) ✨
