### ISSUE TITLE
Call Typescript Compiler from C#

### ISSUE THREAD

**Issue by mike-ward** [Microsoft/TypeScript#2565]
Create nuget module to invokeTypescript compiler in C# to compile Typscript code specified in C# strings.

**Comment by RyanCavanaugh** [comment]
Someone else can do this.

**Comment by mike-ward** [comment]
Um...

I would have expected something like:

                var scType = Type.GetTypeFromProgID("MSScriptControl.ScriptControl.1");
                dynamic sc = Activator.CreateInstance(scType);
                sc.Language = "JavaScript";
                sc.AddCode(tsc.js.text);

to work. But it doesn't. Guess that, "Someone else" has his work cut out for him.

**Comment by DanielRosenwasser** [comment]
Not really. It's not entirely trivial, but it's decently easy to use Chakra/JsRT [with the following resource](https://msdn.microsoft.com/en-us/library/dn249673%28v=vs.94%29.aspx). You can check out the C# version of the [sample app](https://code.msdn.microsoft.com/JavaScript-Runtime-Hosting-d3a13880) which is Apache 2.0 licensed.

**Comment by DanielRosenwasser** [comment]
Also you can use [Edge.js](http://janczuk.github.io/edge)

**Comment by DickvdBrink** [comment]
I did something like that here: https://github.com/DickvdBrink/TypeScriptSyntaxVisualizer/blob/master/TypeScriptSyntaxVisualizer/TypeScript/TypeScriptContext.cs
Note: It is really old and won't work with the latest TS anymore

**Comment by mike-ward** [comment]
OK, just to close the loop on this one, I got this working by removing the last line in tsc.js where is invokes the command line processling.

I then created the following JS code:

    var tsc = function(input) {
      var opts = {};
      var host = ts.createCompilerHost(opts);

      var output = '';
      host.writeFile = function (filename, text) { output += text; };
      host.getSourceFile = function() { return ts.createSourceFile('textsource', input, 0, '0'); }
      host.getDefaultLibFilename = function () { return ''; }
      host.getCurrentDirectory = function () { return '/' }
      host.useCaseSensitiveFileNames = function () { return false; }
      host.getCanonicalFileName = function (text) { return text; }
      host.getNewLine = function () { return '\n'; }

      var prog = ts.createProgram(['textsource'], opts, host);
      prog.getDiagnostics();
      var checker = prog.getTypeChecker(true);
      checker.emitFiles();
      return output;
    }

    var typescriptout = tsc(typescriptin);

and finally the C# code to invoke it:

        public static string Compile(string text)
        {
            try
            {
                var engine = new Engine();
                engine.SetValue("typescriptin", text);
                engine.Execute(Resources.TypeScript);
                engine.Execute(Resources.tsc);
                var js = engine.GetValue("typescriptout").AsString();
                return js;
            }
            catch (Exception e)
            {
                return e.Message;
            }
        }

I'm sure I missed a few things but there you have it. It of course relies on knowing something about the inner workings which means it will likely break in the next version. Maybe a method could be added in some future version that takes strings instead of files?

**Comment by mhegazy** [comment]
I would highly recommend using the compiler API for these scenarios instead of just replacing strings in the compiler.

here is how to use the compiler API: https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API

And starting from next release, you should have a new API for string -> string transformation for modules, see issue #2499 for more details.

**Comment by mike-ward** [comment]
Awesome. Just what I needed.
