### ISSUE TITLE
Return completions for @memberof instead of for @memberOf

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#25653]
_From @maschmid-MSFT on July 13, 2018 16:43_

Issue Type: <b>Bug</b>

When writing code documentation I noticed an anomaly. If I start typing @member then autosuggest gives me the option of @memberOf (notice the capital O). However, if I type with a lowercase O as in "@memberof" then syntax highlighting highlights similar to how @param or other documentation fields are highlighted. "@memberOf" is not highlighted leading me to believe it is incorrect but that it is what autosuggest is suggesting.

-maschmid

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz (12 x 3592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.90GB (18.35GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.3.1
gitlens|eam|8.4.1
tslint|eg2|1.0.33
beautify|Hoo|1.3.2
csharp|ms-|1.15.2
PowerShell|ms-|1.8.1
debugger-for-chrome|msj|4.8.0
material-icon-theme|PKi|3.5.1
vscode-icons|rob|7.24.0

(1 theme extensions excluded)

</details>

_Copied from original issue: Microsoft/vscode#54268_

**Comment by mjbvz** [comment]
_From @vscodebot[bot] on July 13, 2018 16:43_

(Experimental duplicate detection)
Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
- [Outline JSDoc @memberOf tag support (#53717)](https://www.github.com/Microsoft/vscode/issues/53717)

**Comment by mjbvz** [comment]
_From @maschmid-MSFT on July 13, 2018 16:44_

somehow the memberOf directives were changed to lowercase in the bug report.

**Comment by mjbvz** [comment]
Request here is to suggest `@memberof` instead of `@memberOf`. JSDoc seems to use `@memberof`

**Comment by mhegazy** [comment]
PRs welcomed. 

The change should be as simple as changing `memberOf` to `memberof` in https://github.com/Microsoft/TypeScript/blob/47e513e1517b4d7e96c4a31448189fea4d9534ab/src/services/jsDoc.ts#L49

**Comment by mhegazy** [comment]
extra points for look at other ones like `hideConstructor` and `fileOverview`

**Comment by j-oliveras** [comment]
I doing it.
