### ISSUE TITLE
Visual Studio 2015 + compileOnSave + outFile + multiple tsconfig = only one tsconfig compiled on save

### ISSUE THREAD

**Issue by wnbittle** [microsoft/TypeScript#25655]
I have a standard MVC project in Visual Studio 2015 Update 3 with TypeScript 2.8.3 installed.  My project has two tsconfig files that include different subsets of the TypeScript files in my project.  They both use outFile to concat their respective scripts (to out1.js and out2.js for example).

When I have compileOnSave set, only one of the tsconfigs are compiled when I save a .ts file.  If I do a manual build or rebuild on the project both are compiled.  The one that is compiled when I save a .ts file seems to be the first tsconfig found in a path-sorted file listing.

My file structure is as follows:
/common/...
/out1/tsconfig.json
/out2/tsconfig.json

Both out1/tsconfig.json and out2/tsconfig.json have an includes for /common/**/*.  Both tsconfigs have  "compileOnSave": true.  In this case only out1 is compiled when I save a .ts file.

This is really annoying because when I run the MVC project in debug mode I cannot do a build, but if I need to change a file that's only included in out2.js, I have to stop debugging, build, then start again.  I may be wrong, but I'm sure this worked before.  It's not clear to me whether outFile has anything to do with this issue.

**TypeScript Version:**
2.8.3

**Search Terms:** 
CompileOnSave
outFile

**Code**

**Expected behavior:**
Both tsconfig files would be compiled on save of a .ts file in the project.

**Actual behavior:**
Only one is compiled.

**Playground Link:**  

**Related Issues:** 
#3645

**Comment by mhegazy** [comment]
it is likely that will not be able to fix this for VS 2015. but we should ensure that we are doing the right thing for VS 2017.

**Comment by mhegazy** [comment]
Looking at VS 2017, seems like we do not have this bug. we do correctly query for all projects that this file is part of.

**Comment by wnbittle** [comment]
Thanks for the quick feedback.  Any ideas for a workaround?

**Comment by RyanCavanaugh** [comment]
Closing due to lack of other feedback  - either this has been fixed or is too rare of a scenario
