### ISSUE TITLE
Jsdoc error at jakefile

### ISSUE THREAD

**Issue by j-oliveras** [Microsoft/TypeScript#25657]
While doing #25656 I see that jakefile has an error at https://github.com/Microsoft/TypeScript/blob/47e513e1517b4d7e96c4a31448189fea4d9534ab/Jakefile.js#L504
because that function has three needed parameters. See jsdoc at implementation (the third is not optional):
https://github.com/Microsoft/TypeScript/blob/47e513e1517b4d7e96c4a31448189fea4d9534ab/Jakefile.js#L816-L839

The implementation treats the third parameter as optional, but the only call to this function don't use it.
Is better remove the third parameter or make it optional?

CC @RyanCavanaugh since you changed this code the last time.

**Comment by mhegazy** [comment]
`extraContent` should be optional. thanks!

**Comment by mhegazy** [comment]
thanks @j-oliveras !
