### ISSUE TITLE
tsc: command not found

### ISSUE THREAD

**Issue by jorgeherrera9103** [Microsoft/TypeScript#25666]
# tsc: command not found

I reinstalled the Node.js and TS but doesn't work

- - - 

C:\>npm install -g typescript
C:\Users\jorge.herrera\AppData\Local\npm\tsserver -> C:\Users\jorge.herrera\AppData\Local\npm\node_modules\typescript\bin\tsserver
C:\Users\jorge.herrera\AppData\Local\npm\tsc -> C:\Users\jorge.herrera\AppData\Local\npm\node_modules\typescript\bin\tsc
+ typescript@2.9.2
updated 1 package in 1.772s

C:\>tsc --version
"tsc" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

- - -

**Comment by DanielRosenwasser** [comment]
Make sure `C:\Users\jorge.herrera\AppData\Local\npm\` is on your account's `PATH` environment variable.

**Comment by jorgeherrera9103** [comment]
Hi bro, 

I don't have te npm there

C:\Users\Jorge\AppData\Local

What can I do?

Thanks a lot.

**Comment by DanielRosenwasser** [comment]
Not totally sure, but it sounds like there's something wrong with npm. Otherwise, we really can't investigate, as this doesn't sound TypeScript-specific.

**Comment by jorgeherrera9103** [comment]
I'll find that it's something wrong with the PATH, but I don't know, I'm continue to try it.

Thanks a lot.

**Comment by dazinator** [comment]
I am seeing the same issue.

> C:\Users\Daz>npm install -g typescript
C:\Users\Daz\AppData\Roaming\npm\tsc -> C:\Users\Daz\AppData\Roaming\npm\node_modules\typescript\bin\tsc
C:\Users\Daz\AppData\Roaming\npm\tsserver -> C:\Users\Daz\AppData\Roaming\npm\node_modules\typescript\bin\tsserver
C:\Users\Daz\AppData\Roaming\npm
`-- typescript@3.1.1


> C:\Users\Daz>tsc
'tsc' is not recognized as an internal or external command,
operable program or batch file.

On my Path:

![image](https://user-images.githubusercontent.com/3176632/46248243-ebd52200-c40e-11e8-8315-8ee2595968de.png)

I can see `tsc` in that directory:

![image](https://user-images.githubusercontent.com/3176632/46248250-060f0000-c40f-11e8-8ab7-da25e7b1fa55.png)

**Comment by dazinator** [comment]
Assume this is a node / npm issue, will try updating / reinstalling node / npm

**Comment by dazinator** [comment]
The version of node I had installed was quite old. I installed the latest version, and then ran into this whilst trying to install `typescript`: https://github.com/npm/npmlog/issues/48

So I uninstalled `node` completely, deleted all `node_modules` folders, then installed the latest version of node. I was then able to successfully install typescript globally, and run tsc from command line.

**Comment by seanparsons** [comment]
I just had this and bulldozing `node_modules` and reinstalling "fixed" it.

**Comment by FadiAlzoubi** [comment]
Thank you, I had the same problem. it is working by running tsc.cmd file inside the path of C:\Users\yourUsername\AppData\Roaming\npm

**Comment by Mufeez** [comment]
it worked after adding ,C:\Users\muhammad.ahmed\AppData\Roaming\npm to as "path"  to user variables

**Comment by cal3432** [comment]
Have you tried running tsc via npx?

EG:

`npx tsc version`
instead of
`tsc version`

this worked for me

**Comment by Agboolafeyikemi** [comment]
npx tsc version works for me as well

**Comment by DanielRosenwasser** [comment]
You all may want to look into a tool called [Volta](https://get.volta.sh/) if you'd like to just be able to type in `tsc`.

**Comment by Hoxtygen** [comment]
I had the same problem, restarting the machine doesn't help. uninstalling and reinstalling the latest version  (14.8.0) of node did the trick.

**Comment by JoseLuis21** [comment]
> funcionó después de agregar, C:\Users\muhammad.ahmed\AppData\Roaming\npm como "ruta" a las variables de usuario

Me funciono de la misma forma Añadiendo a las variables path de windows la ruta de npm
