### ISSUE TITLE
"Go to definition" not working with `declarationMap` and projects references

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/TypeScript#25662]
**TypeScript Version:**  3.0.0-rc

**Search Terms:** 

**Code**

[Full reproduction case](https://github.com/OliverJAsh/typescript-3-client-server-shared)

```
src
├── client
│   ├── main.ts
│   └── tsconfig.json
└── shared
    ├── main.ts
    └── tsconfig.json
```

``` ts
// src/client/main.ts
import { foo } from '../shared/main';

console.log({ foo })
```

``` json
// src/client/tsconfig.json
{
    "compilerOptions": {
        // Needed for project references.
        "composite": true,
        "declaration": true,

        // Other options...
        "outDir": "../../lib/client",
        "strict": true, "module": "esnext", "moduleResolution": "node",
    },
    "references": [
        { "path": "../shared" }
    ]
}
```

``` ts
// src/shared/main.ts
export const foo = 1;
```

``` json
// src/shared/tsconfig.json
{
    "compilerOptions": {
        // Needed for project references.
        "composite": true,
        "declaration": true,
        "declarationMap": true,

        // Other options...
        "outDir": "../../lib/shared",
        "strict": true, "module": "esnext", "moduleResolution": "node",
    }
}
```

- Run `tsc --build ./src/client/`
- Configure VSCode TypeScript version to use workspace, and reload VSCode

**Expected behavior:**
"Go to definition" should work for `foo` identifier in `src/client/main.ts`.

**Actual behavior:**
"Go to definition" does not work for `foo` identifier in `src/client/main.ts`.

![image](https://user-images.githubusercontent.com/921609/42723499-b4c10382-8756-11e8-8588-421898ac92a8.png)

**Comment by weswigham** [comment]
Having looked at the other issue, I think this is a dupe of #25792 - or rather, #25792 is a dupe of this, but I looked into #25792 first. 😛  In any case, I should have a fix promptly.

**Comment by OliverJAsh** [comment]
@weswigham I just tested this with 3.0.1 and I can still reproduce. Any ideas? Can we re-open?

**Comment by mhegazy** [comment]
@weswigham can you take a look.

**Comment by AnyhowStep** [comment]
On 3.0.1, have this issue, too.

**Comment by OliverJAsh** [comment]
Can we re-open this issue whilst it is investigated again?

**Comment by Soul-Master** [comment]
I just tried declarationMap option in TypeScript 3.0.1. But it doesn't work both in VS 2017 15.8.0 Preview 5.0/VS Code 1.26.0

https://github.com/Soul-Master/typescript3-composite-project/tree/declarationMap

**In VS Code 1.26.0**

![image](https://user-images.githubusercontent.com/442046/44097707-9cfd2bc0-a008-11e8-9b6c-3729d9fde2c9.png)

![image](https://user-images.githubusercontent.com/442046/44097738-ad794e20-a008-11e8-9e21-0832bd8a32ac.png)

**In VS 2017 15.8.0 Preview 5.0**

![image](https://user-images.githubusercontent.com/442046/44097793-cd1b20e6-a008-11e8-98dd-08f8223f4057.png)

![image](https://user-images.githubusercontent.com/442046/44097847-ebe66ae4-a008-11e8-85db-3387f6ea7144.png)

**Comment by OliverJAsh** [comment]
@weswigham This is not fixed. Just tested with TS 3.0.3.

Full repro: https://github.com/OliverJAsh/typescript-3-client-server-shared

**Comment by OliverJAsh** [comment]
Please can we re-open this issue? /cc @weswigham @mhegazy 

(Sorry to pester here but I think this needs attention, as it's a very basic use case.)

**Comment by weswigham** [comment]
@OliverJAsh your repro seems to be fixed in the latest versions of TS (I'm pretty sure we've had a continuous stream of improvements to this area since 3.0).

**Comment by OliverJAsh** [comment]
Just tested, it works! Thanks 🎉
