### ISSUE TITLE
tsc generates JS files with wrong case (Windows)

### ISSUE THREAD

**Issue by jeffsaremi** [Microsoft/TypeScript#25678]
tsc Version 2.9.2
Windows 10

ts file name: `AbcClass.ts`
js file name: `ABCClass.js`

amazingly it is the letters 2 and 3 which are always messed up. for instance if everything was upper case it would have made more sense.

the flag `--forceConsistentCasingInFileNames` has no effect in correcting this.

**Comment by mhegazy** [comment]
The compiler does not look up the names on disk. there is an `import`, `/// <reference path=".." />`, a reference to the file in `"files"`/`"include"` in your tsconfig.json or on the command line that uses the invalid casing. 

`--forceConsistentCasingInFileNames` only checks that you did not write the file case differently in at least two places, but it does not check the file case on disk.

**Comment by jeffsaremi** [comment]
I disagree. In my `tsconfig.json` I only have a files section which has the name of the most high-level file/the entry point. I do not name any other files anywhere else.
Then I have the `import `lines which are with proper case. File `ABCClass.*` does not exist anywhere prior to invocation of tsc.

**Comment by mhegazy** [comment]
Can you share a repo project?

**Comment by jeffsaremi** [comment]
never mind. it was one of the imports that had the wrong casing! closing this
