### ISSUE TITLE
Typescript 3 --build ignores baseUrl

### ISSUE THREAD

**Issue by marcos-diaz** [Microsoft/TypeScript#25682]
**TypeScript Version:** 3.0.0-rc

**Search Terms:** baseUrl

**Code**

```
{
  "compilerOptions": {
    "baseUrl": "./src",
    ...
  }
}
```

`tsc --build tsconfig.json`

**Expected behavior:**
Now that Typescript 3.0 compiler claims to be a also a simple project builder, I would expect compiled output to resolve absolute imports to itself based on `baseUrl` setting. 

**Actual behavior:**
It still outputs unresolved require paths.

**Comment by mhegazy** [comment]
Can you share more details?

**Comment by marcos-diaz** [comment]
I can try, just imagine you have a project/module called `fancylib`, you possibly have a bunch of top level files at root level in your project, and a folder `src` with the actual code of the lib.

Then in the lib some files will reference other files, the easy way is to do relative imports, for example in `fancyness.ts` you would do `import {Magic} from './utils'`, but some people argue that doing relative imports is a bad practice, that makes refactors harder, etc... so they would like to do absolute imports better, as `import {Magic} from 'fancylib/utils'` or simply `import {Magic} from 'utils'`.

This was only possible with Webpack/Gulp or other build systems, by using the tsconfig setting `baseUrl`, but was not possible with TSC since it **WAS** not a build tool, just a compiler, so it ignored `baseUrl`.

But **now TSC is actually also a basic build tool**, so is a reasonable expectation that if someone does `import {Magic} from 'fancylib/utils'` in a project/module called _fancylib_, with `tsc --build ...`, then TSC should output JS as `const Magic = require("<baseUrl>/utils")`

**Comment by mhegazy** [comment]
is this the same as https://github.com/Microsoft/TypeScript/issues/25613?

**Comment by marcos-diaz** [comment]
I don't think is the same
