### ISSUE TITLE
`transpileOnly` should get minimum type vs value classification of imported/re-exported identifiers.

### ISSUE THREAD

**Issue by JasonKleban** [Microsoft/TypeScript#25696]
## Search Terms

transpileOnly webpack interface emit omit "export not found"

## Suggestion

There should be a transpilation mode that does minimal type calculus to know whether an imported identifier should be emitted or not.  I hope that such a mode can be only negligibly slower than the current `transpileOnly`.

## Use Cases

`transpileOnly` is used by webpack and fork-ts-checker-webpack-plugin to speed up build times and still maintaining type safety.

Unfortunately, (as explained well in https://github.com/TypeStrong/ts-loader#loader-options)

> If you enable this option, webpack 4 will give you "export not found" warnings any time you re-export a type. ...  The reason this happens is that when typescript doesn't do a full type check, it does not have enough information to determine whether an imported name is a type or not, so when the name is then exported, typescript has no choice but to emit the export.

The recommendation is to suppress the warnings, but this seems sloppy and still gives inconsistent output compared to fully type-checked builds.

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions **(not in the way this question is intended)**
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by mhegazy** [comment]
Not sure i see what is the request here.

**Comment by jwbay** [comment]
I think the ask is for a middle ground between transpileOnly and a full type-check such that TS can remove re-exported types in files during fast compilation.

**Comment by mhegazy** [comment]
The two modes where the compiler works in are:
1. whole project compilation, where all files are available, the compiler can poke on disk to resolve modules, its expected to find every type it needs or else it is an error
2. transpileModule, given a string containing TypeScript syntax, strip out the TS syntax and generate JS string matching the original

That said, there is not really a "middle" ground. the compiler does not have information to be able to know what an export is. Re-exporting a type should be an error under `--isolatedModules` (does not seem to be the case, filed https://github.com/Microsoft/TypeScript/issues/25705 to track fixing it).

**Comment by JasonKleban** [comment]
@jwbay - yes that's correct.  The middle-ground you mention is the request.

I don't understand how `--isolatedModules` is relevant.  It wouldn't be a solution to disallow reexporting of types - we do this legitimately.

The forked typecheck step should not have a consequence of emitting different code than the integrated typecheck.

**Comment by mhegazy** [comment]
> I don't understand how --isolatedModules is relevant.

`--islatedModules` tells the compiler to check the **whole project** and make sure it is *"safe"* to emit it one file at a time.

>  we do this legitimately.

Only if you are generating the whole program at once. if you are emitting one file at a time, it is not allowed. 

> The forked typecheck step should not have a consequence of emitting different code than the integrated typecheck.

i agree.

**Comment by JasonKleban** [comment]
> i agree.

🤨 Does that mean you're convinced?  I'm not sure of the outcome of this conversation at the moment.

**Comment by mhegazy** [comment]
I agree that the output of one process should be the same as the other. that is why we have added this mode with `--isolatedModules` to ensure you are aware of that.

There are constructs that are not emit-able in the single-file-transpile mode. e.g. namespaces, const enums, and type reexports. you should be aware of these limitations and make your decisions on what mode to use based on that.

**Comment by mhegazy** [comment]
I have stated the issue details in https://github.com/Microsoft/TypeScript/issues/25696#issuecomment-405401719. 

As it stands, there are parts of the language that are not safe to emit in single-file-transpilation mode. these parts are flagged as errors under `--isolatedModules`. if you opt-out of using these parts, then you can emit the program in a single shot (using `tsc`) or one file at a time (using `transpileModule`) consistently.

We are happy to discuss proposals on how to implement a system that allows for single-file transpilation and correctly transpile these constructs if you have ideas.
