### ISSUE TITLE
Wrong german translation for "non-dry build"

### ISSUE THREAD

**Issue by AlCalzone** [Microsoft/TypeScript#25713]
As found in https://github.com/Microsoft/TypeScript/pull/25470

https://github.com/Microsoft/TypeScript/blob/204ce175ddeff414455b34e9718532edfba8358b/lib/de/diagnosticMessages.generated.json#L52
https://github.com/Microsoft/TypeScript/blob/204ce175ddeff414455b34e9718532edfba8358b/lib/de/diagnosticMessages.generated.json#L53
I believe the german translation here is wrong. "mit dem Flag" means "with the flag", while the other translations seem to mean "without the flag", which whould be translated as "ohne das Flag".

**Comment by mhegazy** [comment]
@PDostalek can you take a look.

**Comment by PDostalek** [comment]
Thanks for letting me know. I´ll discuss this with the translator.

**Comment by PDostalek** [comment]
@mhegazy  Translations are now changed. Wait until will be visible..

**Comment by mhegazy** [comment]
thanks!
