### ISSUE TITLE
Configure non-polling watcher from tsconfig.json

### ISSUE THREAD

**Issue by lauripiisang** [Microsoft/TypeScript#25715]
## Search Terms

TSC_NONPOLLING_WATCHER , nonpolling, tsconfig

## Suggestion

I'd like to be able to configure tsc polling/nonpolling approach from tsconfig.json, instead of being limited to environment variables.

### Acceptance Criteria
 - TSC_NONPOLLING_WATCHER should be configurable from tsconfig.json
 - The additional env vars introduced in https://github.com/Microsoft/TypeScript/pull/21243 configurable from tsconfig.json
 - environment variables override tsconfig behavior (questionable, matter of preference, maybe they should be deprecated instead over some time)
 - documentation for tsconfig updated accordingly

This feature should be documented, so people know to use it, as it has true performance advantage for some scenarios, e.g.: in docker, even with delegated volumes, on macOs the tsc watcher by default eats 8-10% of CPU just watching files. With TSC_NONPOLLING_WATCHER

## Use Cases

Having a central typescript-based framework, with projects based on it, we would like for the users to be able to easily override polling behavior, due to having different environment or issues arising, while retaining the ability to have non polling behavior as the default.

## Examples

```json:tsconfig.json
{
  "compilerOptions": {
    "watch": {
      "useNonPollingWatcher": true,
      "watchFile": "...",
      "watchDirectory": "..."
    }
}
```

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by mhegazy** [comment]
@sheetalkamat can you add docs for these variables for users to be able to discover and test them.

**Comment by lauripiisang** [comment]
Why was this closed? Documentation is merely the first step!

**Comment by mhegazy** [comment]
These settings are global and not per-project. for instance, tsserver uses the same settings, and the server can be handling multiple open projects at the same time. thus, tsconfig is not the correct place to host these configuration options.
