### ISSUE TITLE
[V 2.9+] Using the new JSON import functionality fails in class constructor, returns undefined

### ISSUE THREAD

**Issue by jhalborg** [Microsoft/TypeScript#25712]
**TypeScript Version:**  ^3.0.0-dev.20180712

**Search Terms:**
typescript 2.9 json import constructor

**Code**

`config.ts`
```ts
import devConfig from '../config.dev.json';
import prodConfig from '../config.prod.json';

type ConfigType = typeof devConfig | typeof prodConfig;

class Config {
  private environmentConfig: ConfigType = devConfig;

  private someApi = {
    baseUrl: this.environmentConfig.someApi.baseUrl,
    apiKey: this.environmentConfig.someApi.apiKey,
  };

  constructor() {
    const isProduction = process.env && process.env.NODE_ENV === 'prod';
    const config = isProduction ? prodConfig : devConfig;
    this.environmentConfig = config;
  }

  public get someApiBaseUrl(): string {
    return this.someApi.baseUrl;
  }
}

export const appConfig = new Config();
```

`config.[env].json`
```json
{
  "someApi": {
    "baseUrl": "http://google.com",
    "apiKey": "asd123"
  }
}
```

Relevant parts of `tsconfig.json`
```json
{
  "compilerOptions": {
    "target":
      "es5",
    "module":
      "commonjs",
    "lib": ["esnext", "dom"],
    "moduleResolution":
      "node",
    "resolveJsonModule": true
  },
}

```

**Expected behavior:**
Using `appConfig` works, and returns expected values

**Actual behavior:**
Throws `TypeError`, saying `Cannot read property 'someApi' of undefined`. It seems that, for some reason, using the new import of `.json` files is delayed or async, as they are `undefined` when using them in the constructor of the class. 

**Workaround** 
Use the new JSON import functionality for types, and revert to `require` statements for importing the values

```ts
import devConfigTyped from '../config.dev.json';
import prodConfigTyped from '../config.prod.json';

// tslint:disable:no-require-imports
// tslint:disable:no-var-requires
const devConfig = require('../config.dev.json');
const prodConfig = require('../config.prod.json');

type ConfigType = typeof devConfigTyped | typeof prodConfigTyped;

class Config {
  private environmentConfig: ConfigType = devConfig;

  private someApi = {
    baseUrl: this.environmentConfig.someApi.baseUrl,
    apiKey: this.environmentConfig.someApi.apiKey,
  };


  constructor() {
    const isProduction = process.env && process.env.NODE_ENV === 'prod';
    const config = isProduction ? prodConfig : devConfig;

    this.environmentConfig = config;
  }
  ...
}

export const appConfig = new Config();
```

**Comment by andy-ms** [comment]
Despite the name, `TypeError` isn't a compile-time type error, it's a runtime value error. The error probably has to do with the module loader you're compiling to.

Do you happen to have `allowSyntheticDefaultImports` set? That's a declaration that your module loader supports using a default import syntax, but on node that would just try getting the `default` property out of the JSON object, which would be giving you `undefined`. You might try using `esModuleInterop` instead.

**Comment by jhalborg** [comment]
I see, thank you! I'll have a look, but it seems to be a good option.
