### ISSUE TITLE
configFileDiag not returning errors for missing project reference path

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#25741]
**TypeScript Version:**  3.0.1-insider.20180713

**Search Terms:**
- tsconfig
- configFileDiag
- tsserver

**Code**
Create a simple tsconfig that references a non-existant project path:

```ts
{
    "references": [
        {
            "path": "./no-such-tsconfig.json"
        }
    ]
}
```

Save the file and see a `configFileDiag` response from tsserver

**Expected behavior:**
`configFileDiag` returns a diagnostic for the invalid path

**Actual behavior:**
No diagnostics are returned

Let me know if there is another way we are supposed to be getting diagnostics for config file issues. 

**Related Issues:** 
- #10384

**Comment by mhegazy** [comment]
@sheetalkamat should not this be in ConfigFileDiagnosticEvent instead? VSCode does not use any of the sync APIs and nor should they. I think we either need to send the errors back in the event or in the getErr command.
