### ISSUE TITLE
Original Type definition not navigable anymore when a type is augmented locally

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#25742]
_From @lorthirk on March 29, 2018 8:5_

Issue Type: <b>Feature Request</b>

I needed to augment a type coming from an external module (namely `@uirouter/angularjs` so that an interfaces could have an optional parameter, otherwise I was receiving an error from the TypeScript compiler. So I went for my augmentation in a file:

```
import { Ng1StateDeclaration, Ng1ViewDeclaration, _Ng1StateDeclaration, StateProvider } from "@uirouter/angularjs";

declare module "@uirouter/angularjs" {
  interface Ng1StateDeclaration extends _Ng1StateDeclaration, Ng1ViewDeclaration {
    breadcrumb?: string;
  }

  class StateProvider {
    state(name: string, definition: Ng1StateDeclaration): StateProvider;
  }
}

```

The augmentation works fine, so that now the method call that has an Ng1StateDeclaration as parameter accepts an optional property `breadcrumb`:

```
import * as uiRouter from "@uirouter/angularjs";

$stateProvider: uiRouter.StateProvider;

$stateProvider.state("app.roles", {
  breadcrumb: "Roles",
  url: "/roles",
  views: {
    "view@state": {
      template: require("./views/roles-list.html"),
      controller: "RolesListCtrl as vm"
    }
  }
})
```

However, now if I cmd+click on `Ng1StateDeclaration` or `StateProvider.state()` anywhere in my code (both in the `type.extentions.ts` file and in the files that calls the method) I always get redirected to the symbols in `type.extentions.ts`, and I have no other ways to open the original type declarations.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:39:09.335Z)
OS version: Darwin x64 17.4.0

Steps to reproduce:

1. Create a new file TypeScript file to augment an interface exported in another module, using [TypeScript Declaration Merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html)
2. Go To / Show definition (or cmd+click on Mac)

Expected outcome: Both the original declaration and the augmented one are shown, or at least a dialog letting me choose which one to show

Current outcome: only the augmentation is showing, thus preventing me to check the original definition

_Copied from original issue: Microsoft/vscode#46910_

**Comment by mjbvz** [comment]
Tested on TypeScript 3.1.0-dev-20180713

I believe the expectation is:

* For the `Ng1StateDeclaration` interface, show both the extended version and the original for `go to definition`

* For the `state` function, show the overloads from the original `d.ts` along with the new version. (I'm not as sure if is actually the expected behavior when it comes to overloads in interfaces actually)

**Comment by mhegazy** [comment]
> For the state function, show the overloads from the original d.ts along with the new version. (I'm not as sure if is actually the expected behavior when it comes to overloads in interfaces actually)

Go-to-def on a call expression will take you to the overload that matches the call. you have added a new overload and that is what the compiler uses to resolve your call. use find all references instead.

**Comment by mhegazy** [comment]
The issue here is a bit subtle. You can only "augment" the source of the declaration. what the declarations in the OP are doing is shadowing rather than augmenting..
so you are declaring a class `StateProvider` that is shadowing the original `StateProvider`. to augment `StateProvider`, first you need to augment the source of that declaration:  `"@uirouter/angularjs/lib/StateProvider"`, and second it has to be an interface (since a class can not be redeclared). same for `Ng1StateDeclaration`.


i.e.:

```ts
import { Ng1StateDeclaration} from "@uirouter/angularjs";

declare module "@uirouter/angularjs/lib/interface" { 
    interface Ng1StateDeclaration {
        breadcrumb?: string;
    }
}

declare module "@uirouter/angularjs/lib/StateProvider" {
    interface StateProvider {
        state(name: string, definition: Ng1StateDeclaration): StateProvider;
    }
}
```
