### ISSUE TITLE
Incorrect assignment to variable of union type

### ISSUE THREAD

**Issue by timocov** [Microsoft/TypeScript#25756]
**TypeScript Version:**  2.9.2, 3.0.0-rc, 3.1.0-dev.20180717

**Search Terms:** union types

**Code**

```ts
interface DisabledInterface {
	enabled: false;
}

interface EnabledInterfaceOne {
	enabled: true;
	type: 'fixed';
}

interface EnabledInterfaceTwo {
	enabled: true;
	type: 'percent';
}

type CommonType = DisabledInterface | EnabledInterfaceOne | EnabledInterfaceTwo;

const a: CommonType = { enabled: false, type: 'fixed' };
```

**Expected behavior:**

Error on assignment to `a` const.

**Actual behavior:**

No errors.

**Playground Link:** [link](https://www.typescriptlang.org/play/index.html#src=interface%20DisabledInterface%20%7B%0D%0A%09enabled%3A%20false%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20EnabledInterfaceOne%20%7B%0D%0A%09enabled%3A%20true%3B%0D%0A%09type%3A%20'fixed'%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20EnabledInterfaceTwo%20%7B%0D%0A%09enabled%3A%20true%3B%0D%0A%09type%3A%20'percent'%3B%0D%0A%7D%0D%0A%0D%0Atype%20CommonType%20%3D%20DisabledInterface%20%7C%20EnabledInterfaceOne%20%7C%20EnabledInterfaceTwo%3B%0D%0A%0D%0Aconst%20a%3A%20CommonType%20%3D%20%7B%20enabled%3A%20false%2C%20type%3A%20'fixed'%20%7D%3B%0D%0A)

**Comment by Nipheris** [comment]
The interesting part is when we modify the `DisabledInterface` to the following:
```
interface DisabledInterface {
	enabled: false;
	type: undefined;
}
```
the compilation fails as expected. Maybe it is related to #10586 in some way?

**Comment by jack-williams** [comment]
I think this is to do with excess property checking on unions which only works for tagged unions. In your example the field `enabled` is not a discriminant for the union (because `EnabledInterfaceOne` and `EnabledInterfaceTwo` share the property). As there is no discriminant excess property checking gets disabled. The follow works:

```ts
interface DisabledInterface {
	enabled: false;
}

interface EnabledInterfaceOne {
	enabled: true;
	type: 'fixed';
}

type CommonType = DisabledInterface | EnabledInterfaceOne

const a: CommonType = { enabled: false, type: 'fixed' }; // error
```

because `enabled` is now a correct discriminant so excess property checking gets turned on.

The reason @Nipheris's example works is because it's an ill-typed property, not an excess one.

**Comment by RikkiGibson** [comment]
I believe I've found another instance of the same behavior in a relatively simple case:

```ts
interface Foo1 {
    prop1: string;
}

interface Foo2 {
    prop1: string;
    prop2: string;
    prop3: string;
}

type Foo = Foo1 | Foo2;

// expected an error but no error was reported
const foo: Foo = {
    prop1: "something",
    prop2: "hello"
}
```
I would expect TypeScript to either require that I specify `prop1` or specify all of `prop1`, `prop2`, and `prop3`. Is this by design?
