### ISSUE TITLE
No inference for this parameter of function.

### ISSUE THREAD

**Issue by zamb3zi** [Microsoft/TypeScript#25757]
**TypeScript Version:**  2.9.1-insiders.20180525

**Search Terms:** infer function this

**Code**

```ts
type A = { foo: number };
function f(this: A) { return this.foo }
type This<T> = T extends (this: infer U, ...args: any[]) => any ? U : any;
let tt: This<typeof f>;
tt.foo; // error: property 'foo' does not exist on type '{}'
```

**Expected behavior:**

The pattern works fine for inferring any other argument types or the return type (as in `ReturnType<T>`) but fails to infer the `this` type of the function.

`This<typeof f>` should be `A`.

**Actual behavior:**

`This<typeof f>` is `{}`.

**Playground Link:** [Playground](https://www.typescriptlang.org/play/index.html#src=type%20A%20%3D%20%7B%20foo%3A%20number%20%7D%3B%0D%0Afunction%20f(this%3A%20A)%20%7B%20return%20this.foo%20%7D%0D%0Atype%20This%3CT%3E%20%3D%20T%20extends%20(this%3A%20infer%20U%2C%20...args%3A%20any%5B%5D)%20%3D%3E%20any%20%3F%20U%20%3A%20any%3B%0D%0Alet%20tt%3A%20This%3Ctypeof%20f%3E%3B%0D%0Att.foo%3B%20%2F%2F%20error%3A%20property%20'foo'%20does%20not%20exist%20on%20type%20'%7B%7D')

**Comment by sandersn** [comment]
Here's a smaller repro that shows that the failure is to match `this: infer U`:

```ts
type Check<T> = T extends (this: infer U, ...args: any[]) => any ? string : unknown;
type ShouldBeString = Check<(this: number) => void>;
```

**Comment by sandersn** [comment]
Actually, we don't do this-parameter inference *at all*, so here's an even simpler repro:

```ts
declare function f<T>(g: (this: T) => void): T
declare function h(this: number): void;
f(h)
```
