### ISSUE TITLE
quick fix for function only contains one jsx element and have not the return statement

### ISSUE THREAD

**Issue by Kingwl** [microsoft/TypeScript#25751]
## Search Terms
quickfix, jsx, function

## Suggestion
quick fix for function only contains one jsx element and have not the return statement

## Use Cases

the pattern of a function with block body that only have one jsx element without return statement  
that seems a error
could we provide a quickfix for that?

## Examples
```ts

items.map(x => {
  <div>123</div>
})

```

to 

```ts

items.map(x => (
  <div>123</div>
))

```

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by DanielRosenwasser** [comment]
Great idea. It doesn't even have to be limited to JSX. I'm not sure how we'd plum it but there are two fixes I'd have in mind:

1. For any block body containing a single *ExpressionStatement* whose expression's type matches the expected type, suggest the following:
  * Add a `return` statement.
  * Remove block body braces.
  * Replace braces with parentheses.
2. For any block body containing only a labeled *ExpressionStatement*, check to see if the expected type contains a property with the same name as the label, and if so, suggest
  * Wrap this block with parentheses.

**Comment by Kingwl** [comment]
should that a quickfix? maybe ref is more suitable

**Comment by Kingwl** [comment]
need some help:
how could i know type are related in quick fix without `isTypeRelatedTo`😢

**Comment by DanielRosenwasser** [comment]
Thanks @Kingwl!
