### ISSUE TITLE
When relating object literal types to unions, avoid elaborating on Array/ReadonlyArray

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#25750]
From @arackaf:

![image](https://user-images.githubusercontent.com/972891/42858529-ee23763c-8a03-11e8-92f5-911f31adaf55.png)

Notice that when comparing an object literal against `MutationSubscription | MutationSubscription[]`, it picked the last branch which is bad.

Kind of like #24776, but here if the type originates from an object literal (or from JSX attributes?), we should avoid matching against `Array` or `ReadonlyArray`

**Comment by arackaf** [comment]
Thanks for adding this.  But it seems that even when running this same code, but without type annotations, VS Code similarly freezes up, and plugins stop responding. But what’s interesting is that this problem ONLY happens (both against typings, and with un-typed code) when the run method pictured is an in-line fat arrow.

If you set it to a variable defined elsewhere, or null, or a method syntax function, it works fine.  But Code hates having a fat arrow in that specific position.

**Comment by DanielRosenwasser** [comment]
This was just me noticing you're getting a bad error. ;)

**Comment by DanielRosenwasser** [comment]
Separately from the problem you're seeing, we're just giving a bad error message.

**Comment by arackaf** [comment]
Sorry to add so much spam to this issue.  It seems even deleting my typings file completely, still causes this JSX to lock VS Code up, with it falsely reporting an error for a good 30 or so seconds.  It happens as soon as, and only when I, put the arrow function there.

I confirmed the typings were gone, and VS Code was in fact reporting these members as `any`.  I'm a bit hesitant to publish this library with TSC hating it so much :)

Has the cause of this been found yet?  Is there anything I can do to help reproduce it?

/cc @mhegazy 

![image](https://user-images.githubusercontent.com/11261266/42909207-eef896aa-8aa8-11e8-980b-98c5fe8428c7.png)

**Comment by DanielRosenwasser** [comment]
It's going to take some time to investigate the problem that you were running into without a minimal repro. This issue really is only about giving a better error message in specific cases (which you can see an example of in #25752).

>  I'm a bit hesitant to publish this library with TSC hating it so much :)

Yeah, I would recommend not publishing with `.d.ts` in the meantime then if it's going to cause users a lot of pain.
