### ISSUE TITLE
Class attribute declaration in function parameter

### ISSUE THREAD

**Issue by simonferndriger** [Microsoft/TypeScript#25767]
This expression from the Angular tutorial made me think:

      deleteHero (hero: Hero | number): Observable<Hero> {
          const id = typeof hero === 'number' ? hero : hero.id;
          ...

All we want is a number, which can come from two sources. But why do we have to declare this separation two times (one time in the function parameter, another time reading the actual value)? Needless to say that in case of two different objects with different namings for the attribute (e.g. hero: Hero | list: List) will complicate this (e.g. when we are looking for either hero.id or list.position).

How about declaring everything already in the function parameter like this?

    deleteHero (id: Hero.id | List.position | number): Observable<Hero> {
	 // now we can directly use "id" here already
          ...

**Comment by andy-ms** [comment]
That would fall outside the scope of the [design goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals) since it involves generating code based on type information.

**Comment by simonferndriger** [comment]
OK, thanks!
