### ISSUE TITLE
Function overloads for function expressions

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/TypeScript#25761]
**TypeScript Version:**  2.9.2

**Search Terms:**

**Code** function overload expression

Related https://github.com/Microsoft/TypeScript/issues/16731

I have this TypeScript code which uses overloads on a function declaration. This code works as expected.

``` ts
    function identity(x: string): string;
    function identity(x: number): number;
    function identity(x: string | number): string | number {
        return x;
    }

    const a = identity('foo') // string
    const b = identity(1) // number
    const c = identity({}) // type error (expected)
```

I am trying to achieve the equivalent of the above using function expressions instead of function declarations, however I get a type error:

``` ts
    /* Type '(x: string | number) => string | number' is not assignable to type '{ (x: string): string; (x: number): number; }'.
        Type 'string | number' is not assignable to type 'string'.
            Type 'number' is not assignable to type 'string' */
    const identity: {
        (x: string): string;
        (x: number): number;
    } = (x: string | number): string | number => x;
```

How I can achieve the same effect of overloading the function but with function expressions?

Usage of function declarations vs expressions is a matter of preference. Ideally we would be able to achieve the same behaviour using either techniques.

- Is this possible?
- Is the above behaviour a bug?

**Comment by mhegazy** [comment]
> Is this possible?

no.

> Is the above behavior a bug?

No. this is behaving as intended. there is a stronger relationship between overloads and an implementation signature that allows us to relax some of the rules.

**Comment by OliverJAsh** [comment]
Interesting, so it's not possible to achieve the same behaviour we see with the function declaration but using the function expression syntax? That's a shame. I guess we'll have to stick to function declarations for functions which require overloads.
