### ISSUE TITLE
Partial<T> make only some properties optional

### ISSUE THREAD

**Issue by whu-iss-jack** [Microsoft/TypeScript#25760]
## Use Cases

current `Partial<T>` will make all properties of `T` optional
I want to specify only some properties of `T` optional  
## Examples

```ts
interface Message {
    mid: number;
    content: string;
}

interface MessageOptional {
   mid?: number;
   content: string;
}

const message: Message = assembleMessage({ content: 'hello' })

function assembleMessage(message: MessageOptional) : Message{
    const mid =  ... // generate mid somehow
    message.mid = mid
    return message
} 
```
it's very often sometimes we want to omit some properties of an object and later supplement it.
currently typescript has concepts like `Intersection`、`Union`， how about `Complement`?
## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by 0x414c** [comment]
You can use existing `Partial` and `Exclude` to implement an approach like this:
```ts
type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;
type WithOptional<T, K extends keyof T> = Omit<T, K> & Partial<Pick<T, K>>;

interface Foo {
    foo: string;
    bar: number;
    baz: boolean;
}
// { foo?: string; bar: number; baz?: boolean; }
type OptionalFoo = WithOptional<Foo, 'foo' | 'baz'>;

const createFoo = (base: OptionalFoo): Foo => {
  return { foo: 'foo', baz: true, ...base };
};
const optionalFoo: OptionalFoo = { foo: '???', bar: 2 };
const fullFoo = createFoo(optionalFoo); // { foo: '???', bar: 2, baz: true }
```

**Comment by whu-iss-jack** [comment]
@0x414c 
thanks anyway, I hope `Omit` and `WithOptional` can be added to lib.d.ts in the future cause it's really a very common need.
yet there's another problem with `keyof a Union type`
```ts
interface MessageA {
   mid: number;
   type: number;
   text: string;
}

interface MessageB {
   mid: number;
   type: number;
   url: string;
}
type Message = MessageA | MessageB

type Keys = keyof Message    //    'mid' | 'type'

/**
*  {
*       mid?: number;
*       type: number; 
*  }
*/
type OptionalMessage = WithOptional<Message, 'uid'> 

// what I really what :
type OptionalMessageNeed = WithOptional<MessageA, 'uid'> | WithOptional<MessageB, 'uid'> 
```

**Comment by whu-iss-jack** [comment]
I just got a solution. 
```ts
type AllKeyOf<T> = T extends never ? never : keyof T

type Omit<T, K> = { [P in Exclude<keyof T, K>]: T[P] }

type Optional<T, K> = { [P in Extract<keyof T, K>]?: T[P] }

type WithOptional<T, K extends AllKeyOf<T>> = T extends never ? never : Omit<T, K> & Optional<T, K>

/**
  {
       mid?: number;
       type: number;
       text?: string; 
  }
| {
       mid?: number;
       type: number;
       url: string;
  }    
*/
type a = WithOptional<Message, 'mid' | 'text'>
```

**Comment by kacluk123** [comment]
Guys those solutions are unredable. I think it's better to create separate interface.

**Comment by gr2m** [comment]
This works for me

```ts
type Optional<T, K extends keyof T> = T extends never
  ? never
  : Omit<T, K> & Partial<T>;
```

[Playground link](https://www.typescriptlang.org/play/#code/C4TwDgpgBA8mwEsD2A7AhgGwDwBUA0UA0lBAB7AQoAmAzlANYQhIBmUOAfFALzsnmVaUFBABuEAE4BYAFBQoAfmFjJs+QC5YAWwTBcBQlwBkUAApoJiTLg4BuWbNCR2EGsB5QA3mqgskSTTcJBBQAc3s5KAAjC0DgYLCI+RiALziE8J8qNBSFdJDMmQBfCKdoHFdgAEYPOERUawq3AgAiPyQWu1kAY1Q3KAo3Ks0m6o9vSJiJTQByGbwfVNmZ2SLHcHLKgCZa+GR0bFHWqZaoAB8oFtTOiN6UfsHgLZHt8Z925dXZIA)

**Comment by SrBrahma** [comment]
> This works for me
> 
> ```ts
> type Optional<T, K extends keyof T> = Omit<T, K> & Partial<T>;
> ```
> 
> [Playground link](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=1&pc=63#code/C4TwDgpgBA8mwEsD2A7AhgGwDwBUA0UA0lBAB7AQoAmAzlANYQhIBmUOAfFALywC2CYLgKEuAMigAFNACdEmXBwDcAWABQ60JHYQawHlADe6qFBZIkALih6ZCFAHNVa0wCNZ12-acmo7gF6ewHaOzqZUaP4A-EEhPmoAvs5a0Di6wACMBnCIqAppegQAROZIRcrqAMaoelAUehnWBZkGxi5+HlAA5F14vgHWPeoJmuCp6QBM2fDI6NjNxe4yRVAAPlBFAeXO1Si19cATTZOtvqWDXcPqQA)

This is really good. However, is there a way to keep the keys ordered as the original type?

**Comment by rattrayalex** [comment]
[`type-fest` has `SetOptional`](https://github.com/sindresorhus/type-fest#utilities)

**Comment by tresorama** [comment]
In case you need to ensurethat `All prop are optional but some of those are required` this worked for me (Thanks to @gr2m for the starting point.)

```ts
// All props are required but some are optional
type Optional<T, K extends keyof T> = Omit<T, K> & Partial<T>;

type Test = {
  foo: string;
  bar: string;
  baz: string;
  daz?: string;
};
type Test1 = Optional<Test, "foo">;
const test1: Test1 = {
  bar: '',
  baz: ''
}
type Test2 = Optional<Test, "bar" | "baz">;
const test2: Test2 = {
  foo: ''
}


// All prop are optional but some of those are required
type PartialWithRequired<T, K extends keyof T> = Pick<T, K> & Partial<T>;

type Test3 = PartialWithRequired<Test, 'bar' | 'foo'>;
const test3:Test3 = {
  bar: '',
  foo: ''
}
```

[Playground](https://www.typescriptlang.org/play?#code/LAKA9GAECCA2uQA4CcD2iDOkCGyCmk+AjgK4CW+AJpAEYkAukGqAtgbgevWagHbaxQ9AJ6ICAeUTc+AgDwAVADSQA0pDwAPenl6UsAazzDUAM0jyAfJAC8kcSzL0FylVYBkkAAq5ucywG5QIVECeTwMRlsAb1BISBNUVAAuJnpkMl4Ac0CQOJpcFIj0rJy87AAvQrSM7NjISgqAfiri2pAAXxyRMXNw+gBGGzspHn5YBT7lACIE1CmLHIBjPgjIbQj+lLCNoZjc2gLIAHIjxTr8yuOj0Hbgnu36ACYhyWkxiYjp-OQpyAAfSBTC7zJYrRjrJ5bPrPaJ1WYpE43IIgUAQGDwJBoRA4fCQLijAS0BhMVicMz0AAWqAw7FxxHIVDuBG8yF8sAA6o4KQAlPCkCh4SjOVTqLQ6PSQQzGMyWIaeMiLfTC1yQDwstkKBbI7qhPoAZjlPjIAk5lN5-KoH3oyiO3yO-2OsyOWpAy14qwheqSDwNsP23wRpzhiUDSJAQA)

**Comment by techieshark** [comment]
@tresorama it seems that since type `Test` already requires all properties but one (`daz?`), the code provided works.

But if starting out with optional properties and we want to actually make them required, we can also use the Required<> utility. Here's this:

```ts

type Test = {
  foo?: string;
  bar?: string;
  baz: string;
};

// All prop are optional but some of those are required -- NOTE! doesn't work, see Test1.
type PartialWithRequired<T, K extends keyof T> = Pick<T, K> & Partial<T>;

type Test1 = PartialWithRequired<Test, 'foo'|'bar'>;
// @ts-expect-error since `Pick` from `PartialWithRequired` does NOT mark an optional parameter like 'foo' or 'bar' as required
const test1:Test1 = {}

// Actually works:
type PartialExceptTheseRequired<T, K extends keyof T> = Pick<Required<T>, K> & Partial<T>

type Test2 = PartialExceptTheseRequired<Test, 'foo'|'bar'>
const test2:Test2 = {}
// ^ it errors, which we want, since we are now requiring foo and bar but haven't set them.

```

[Playground](https://www.typescriptlang.org/play?#code/LAKALgngDgpgBAFRgZzHAvHA3qOcBmA9oQPwBccqATgJYB2A5gNy5wBGAhleZWLYyxB5OALwrV6zUAF9BoAPTy4AQQA2quFCqEocLvB1gahOhw1sArmmSEAtgfxwwAC0LJ4+uFRgBHCzW8AEzgAWhC4ADkAeQQAUQBCOEDCFDoAcjQAd0IqAGsAGkoYeCRUAEYAOlBIWDgABS4jMwB1GhcAJV9-IIAeBEKAaTgYAA8wGDpA5DhcmAhCRwQAPgx6mgBjXL7BlYAyesaaMz6luXBoEpQwMtWGqibVVo6ugJhAvqvCtKJCNIAfNKcKhpU4KJQAATAyBCo1g6zAMKo2iolHo63gAAM6htchiCNpbHAsYcWm1nJ0-K9AnjkihIjE4LYuLk9HQ4IZjKYNFAuBx7OMUaoaLM4N9iGl2SjAVwJRxpt5KUFQOsTKgnFcymRStdVlhpKAwSp4RYzKoIHBsnlkGRqhcDvcjqpYiN0VAwAhnCgYBTum9tnAhqNxpNprN5osVphsZsej6qScdnB9ncHicDedatqAEy3ElOl0wN0er1x3rar4-f7S4FLZWqtDjVBZrVXHOYPWGgB6cDawyROWQhUyzg2zgt8EyHDoYEKyDRE483jgdEImS8L34DAIxFZwSB7CscGcHAAbhMMkUG57bFUQEA)

**Comment by tresorama** [comment]
@techieshark Fantastic!
I didn't know `Required`
