### ISSUE TITLE
Go-to-definition on tagged union property should filter down to known union case

### ISSUE THREAD

**Issue by RikkiGibson** [Microsoft/TypeScript#25774]
**TypeScript Version:**  2.9.1
Issue produced using vscode 1.25.1 which appears to depend on 2.9.1

**Search Terms:**
tagged union, go to definition

**Code**

```ts
type Animal = Cat | Dog;

interface Cat {
  animaltype: "Cat",
  color: string,
  friendly: boolean;
};

interface Dog {
  animaltype: "Dog",
  color: string,
  likesToFetch: boolean;
}

const cat: Animal = {
  animaltype: "Cat",
  color: "brown",
  friendly: true
};
```

**Expected behavior:**
Go-to-definition on the `color` property goes to the definition on `Cat` instead of showing definitions for both Cat and Dog.

**Actual behavior:**
Go-to-definition shows candidate definitions in both the `Cat` and `Dog` interfaces.

**Playground Link:**  https://www.typescriptlang.org/play/#src=type%20Animal%20%3D%20Cat%20%7C%20Dog%3B%0D%0A%0D%0Ainterface%20Cat%20%7B%0D%0A%20%20animaltype%3A%20%22Cat%22%2C%0D%0A%20%20color%3A%20string%2C%0D%0A%20%20friendly%3A%20boolean%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20Dog%20%7B%0D%0A%20%20animaltype%3A%20%22Dog%22%2C%0D%0A%20%20color%3A%20string%2C%0D%0A%20%20likesToFetch%3A%20boolean%3B%0D%0A%7D%0D%0A%0D%0Aconst%20cat%3A%20Animal%20%3D%20%7B%0D%0A%20%20animaltype%3A%20%22Cat%22%2C%0D%0A%20%20color%3A%20%22brown%22%2C%0D%0A%20%20friendly%3A%20true%0D%0A%7D%3B

**Related Issues:**

**Comment by mhegazy** [comment]
QuickInfo needs to do the same as well. Assuming you have multiple jsdoc comments for `color` on both `Dog` or `Cat`, the compiler should be smart enough to only pick one or the other based on the discriminant property type.
