### ISSUE TITLE
Support overriding the closure scope around a function

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Microsoft/TypeScript#25772]
## Search Terms

function local scope closure new stringified

## Suggestion

Add an optional `this.scope: ` parameter for `function`s similar to `this: `.

A function's `this.scope` would indicate which variables it has access to from an outside closure.
The function would _not_ have access to the variables visible in the closure around it.
It would instead have access to variables that are members of the specified `this.scope` as if it were wrapped in a [`with`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/with) statement _(but without `with`'s horrifying ambiguities)_.

```typescript
function executeScript(this.scope: typeof window): void;
```

## Use Cases

Some popular libraries stringify functions and execute them in other contexts.
These functions appear to be defined inline with their calling code, but are in practice used as syntax-verified strings.
They do not have access to variables available in the surrounding closures.

For example, [`selenium-webdriver`](https://github.com/SeleniumHQ/selenium/tree/master/javascript/node/selenium-webdriver)'s `WebDriver` provides an `executeScript` method that stringifies a single string or function input and passes to it any arguments.

```typescript
import { WebDriver } from "selenium-webdriver";

let driver: WebDriver = new WebDriver(/* ... */);
```

It's easy to not realize the function has no access to the calling closure:

```typescript
let value = "value";

// Equivalent to: driver.executeScript("() => { console.log(value); } ");
driver.executeScript(() => {
    // Uncaught ReferenceError: value is not defined
    console.log(value);
});
```

...while a corrected form of that code today requires an awkwardly renamed parameter:

```typescript
let value = "value";

driver.executeScript(
    (innerValue: string) => {
        // Uncaught ReferenceError: value is not defined
        console.log(value);
    },
    value);
```

There's no way in TypeScript to represent that a function _loses_ access to the containing closure.

## Examples

If we change the type signature of `executeScript` from this<small>*</small>:

```typescript
type ExecuteScript = <TReturn, ...TParams extends any[]>(
    script: string | (...params: TParams),
    ...params: TParams,
) => Promise<TReturn>;
```

...to add a `this.scope: Window`:

```typescript
type ExecuteScript = <TReturn, ...TParams extends any[]>(
    this.scope: Window,
    script: string | (...params: TParams),
    ...params: TParams,
) => Promise<TReturn>;
```

...then the incorrect `value` usage will have its error flagged:

```typescript
let value = "value";

driver.executeScript(() => {
    // [TypeScript] Cannot find name 'value' in inner scope of type 'Window'.
    console.log(value);
});
```

...and the correct `value` usage can safely allow the otherwise ambiguous name:

```typescript
let value = "value";

driver.executeScript(
    (value /* : string */) => {
        console.log(value);
    },
    value);
```

<small>_*Pretending `@types/selenium-webdriver` has been preemptively updated for [generic rest parameters](https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#generic-rest-parameters)..._</small>

### Errata

Directly using `scope:` would be cleaner but cause ambiguities with parameters named `scope`.

This proposal does _not_ have the problems associated with `with` statements. `with` triggers browser-specific behavior fluctuations based on what's available on an object. `this.scope` is well-defined, purely within the type system, and therefore deterministic.

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by mhegazy** [comment]
We have explicitly made `with` blocks errors in TS. This issue is the first i have seen for use of `with` statements in TS in the past 5 years (and we have had a lot of issues 😃).  So i am inclined to say this is out of scope unless you have another scenario in mind.

**Comment by andy-ms** [comment]
As an example, all of our fourslash tests run with access to a scope that they aren't lexically inside of, by using `eval`. We get around this by putting them in their own files, in a different project with phony global variable declarations. But that workaround would be pretty inconvenient for a one-off function.
