### ISSUE TITLE
unexpected generated export with semicolon

### ISSUE THREAD

**Issue by yeliex** [Microsoft/TypeScript#25786]
**TypeScript Version:**  2.9.2

**Search Terms:**

**Code**

```ts
export namespace Types {
    export interface Interface {
        name: string
    };
}

export default class Test {
    constructor(props:Types.Interface) {
    }
}
```

**Expected behavior:**
tsc output:
```js
export default class Test {
    constructor(props) {
    }
}
```
**Actual behavior:**
tsc output:
```js
export var Types;
(function (Types) {
    ;
})(Types || (Types = {}));
export default class Test {
    constructor(props) {
    }
}
```
**Why export Types with semicolon in namespace? It should be ignored**

**Comment by andy-ms** [comment]
There is an extra `;` after `interface Interface`, so we parse an `EmptyStatement` there. We then emit a corresponding `EmptyStatement` in the output.
tslint's [semiclon](https://palantir.github.io/tslint/rules/semicolon/) rule can detect this.

**Comment by yeliex** [comment]
@andy-ms Is this a bug? the extra simicolon should be ignored or throw an exception when compile

**Comment by andy-ms** [comment]
Believe it or not, `;;;` is legal JavaScript and thus legal TypeScript. A tool like tslint is better to warn about excessive semicolons like that.
