### ISSUE TITLE
Compiling a type-only module generates an unnecessary js file

### ISSUE THREAD

**Issue by AlCalzone** [Microsoft/TypeScript#25788]
**TypeScript Version:**  2.9.2

**Search Terms:** type only unnecessary empty js file 

When writing a type-only module with no runtime code at all. I would expect no js-file to be generated.

**Code**
```ts
export type Foo = true;
```

**Expected behavior:**
Only .d.ts file is generated, no .js file

**Actual behavior:**
.js file is generated with the following content:
```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
```

**Playground Link:** https://www.typescriptlang.org/play/#src=export%20type%20Foo%20%3D%20true%3B

**Related Issues:** none found

**Comment by j-oliveras** [comment]
Duplicated of #15097 and #10908?
