### ISSUE TITLE
Incorrect parameter name "label" for FileReader.readAsText

### ISSUE THREAD

**Issue by blixt** [Microsoft/TypeScript#25797]
**TypeScript Version:**  3.1.0-dev.20180717

**Search Terms:** FileReader readAsText

**Code**

```ts
// This is a documentation related issue only, so no code.
```

**Expected behavior:**

```
FileReader.readAsText(blob[, encoding])
```

See MDN documentation: https://developer.mozilla.org/en-US/docs/Web/API/FileReader/readAsText

**Actual behavior:**

```
FileReader.readAsText(blob[, label])
```

**Playground Link:** 

N/A

**Related Issues:** 

N/A

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.
