### ISSUE TITLE
VS 201x and VS Code are not able to find real source with declarationMaps

### ISSUE THREAD

**Issue by HolgerJeromin** [Microsoft/TypeScript#25792]
**TypeScript Version:**  Version 3.0.0-dev and 2.9

**Search Terms:**
goto definition F12

**Code structure**
BaseControl/source.ts
BaseControl/tsconfig.json
ButtonControl/source.ts
ButtonControl/tsconfig.json with `"include": [ "../BaseClass/Source.d.ts"]`

When I use in `ButtonControl` stuff from the `BaseControl `the code compiles and all Intellisense works. 
But using "Goto Definition" F12 shows a small popup window: "No definition found for..."
Without using `declarationMap:true` F12 jumps to the `Source.d.ts` file.

Attached is a minimal example for VS Code
[ts_navigation.zip](https://github.com/Microsoft/TypeScript/files/2209446/ts_navigation.zip)

**Related Issues:**
Related to #25322 but this is typescript only (no gulp-sourcemaps involved)
@weswigham

**Comment by mhegazy** [comment]
@weswigham can you take a look.
