### ISSUE TITLE
`typeof` should error when checking for unsupported types

### ISSUE THREAD

**Issue by milesj** [Microsoft/TypeScript#25805]
## Search Terms

typeof, typeof check, typeof guard, typeof exhaust

## Suggestion

As it currently stands, `typeof` is used for guarding/refinement, but does not check the inverse -- that the expression being evaluated is part of the variable's type (for example, within a union).

## Use Cases

No direct use case, but is extremely helpful in revealing unintended bugs. I recently ran into this in production when I changed a type from `boolean | undefined` to `boolean`, and TS didn't error.

## Examples

```
type Foo = boolean | string;

const foo: Foo = 'abc';

if (typeof foo === 'number') {
  // Should error as "number" isn't part of the union
}
```

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by RyanCavanaugh** [comment]
We've considered this before and rejected it - need to find the original

**Comment by RyanCavanaugh** [comment]
#9506 - this is the intended behavior

**Comment by RyanCavanaugh** [comment]
#16314 was the one I was thinking of

**Comment by milesj** [comment]
Ah a bit unfortunate, but thanks for the response!
