### ISSUE TITLE
Way to use transformations API while preserving whitespace in emitted TS?

### ISSUE THREAD

**Issue by cyungmann** [Microsoft/TypeScript#25801]
Is there a way to use the transformations API to transform a TS file and then emit it, all while preserving existing whitespace/formatting in the file? If I do something like the following, all blank lines get removed (I believe the pretty printer does this?):

```
const result = ts.transform(file, [transformerFactory]);
const newFile = result.transformed[0];

if (ts.isSourceFile(newFile)) {
    const newContent = printer.printFile(newFile);
    ts.sys.writeFile(newFile.fileName, newContent);
}
```

If I do `newFile.getText()` or `newFile.getFullText()`, the resulting string does not include any of the changes from my transformation.

My ultimate goal is to rewrite a bunch of imports of the form `import { foo } from '../../Enum/foo';` to `import { foo } from '../../Enum/enums'`. It'd be nice to coalesce all the imports from the same file as well, but first things first :D

P.S. I hope this is an appropriate forum for this question. It looked like questions are disallowed **with the exception** of questions about the compiler API.

Thanks,
Chris

**Comment by mhegazy** [comment]
> Is there a way to use the transformations API to transform a TS file and then emit it, all while preserving existing whitespace/formatting in the file? 

White space is not maintained. so no. but for formatting we have some logic that we use in quick fixes/refactorings to transform the tree, then reformat the changes to fit. this part is not exposed on the public API, but we can expose it if needed. see https://github.com/Microsoft/TypeScript/blob/master/src/services/textChanges.ts

> If I do newFile.getText() or newFile.getFullText(), the resulting string does not include any of the changes from my transformation.

The transformation does not change the text of the original tree. the original tree stays intact. to get the text you need to print the new tree using the printer.
