### ISSUE TITLE
Contextual type inference fails in surprising case 

### ISSUE THREAD

**Issue by bterlson** [Microsoft/TypeScript#25814]
**TypeScript Version:**  3.1.0-dev.20180719
**Code**

```ts
type R = {
  a: (x: number) => void;
  b: (x: string) => void;
};

type O = {
  on<P extends keyof R>(x: P, callback: R[P]): void;
};

declare var x: O;
x.on('a', a => {}); // not contextually typed.
```
**Expected behavior:**
Contextually type a to number.

**Actual behavior:**
A is not contextually typed, while signature help gives the correct answer.

**Playground Link:** [here](http://www.typescriptlang.org/play/index.html#src=type%20R%20=%20{%0D%0A%20%20a:%20(x:%20number)=%3Evoid%0D%0A%20%20b:%20(x:%20string)=%3Evoid%0D%0A}%0D%0Atype%20O%20=%20{%0D%0A%20%20on%3CP%20extends%20keyof%20R%3E(x:%20P,%20cb:%20R[P]):%20void;%0D%0A}%0D%0Adeclare%20var%20x:%20O%0D%0Ax.on('a',%20a=%3E{})%20//%20why%20no%20contextual%20typing?%20signature%20help%20gives%20correct%20answer)

**Comment by ahejlsberg** [comment]
This is working as intended (but you could argue a design limitation). We only contextually type function expression parameters when the parameter type is known to be a function type _before instantiation_. In your example, we would have to fix `P` following inference for the first argument and then `P` during inference for the second argument, but we don't do that currently. I suppose you could argue we should if _all_ properties addressable by `R[P]` are function types, but that would be a new feature.

**Comment by ahejlsberg** [comment]
BTW, it works if you write it like this (because inference now knows the contextual type is a function type):

```ts
type R = {
  a: number;
  b: string;
};

type O = {
  on<P extends keyof R>(x: P, callback: (x: R[P]) => void): void;
};

declare var x: O;
x.on('a', a => {}); // Contextually typed.
```

**Comment by bterlson** [comment]
I see @ahejlsberg, thanks. Consider this a feature request then 😊

Thank you so much for pointing out it works if the callback is "obviously" a function type, I think I can make this work for my scenario with the following tweak to the OP:

```ts
type R = {
  a: (x: number) => void;
  b: (x: string) => void;
};

type O = {
  on<P extends keyof R>(x: P, callback: (...args: Params<R[P]>) => void): void;
};

type Params<F> = F extends (... args: infer T) => any ? T : never;

declare var x: O;
x.on('a', a => {}); // yay is contextually typed now!
```
