### ISSUE TITLE
Visibility rules changes in 2.9 not clearly stated in release notes.

### ISSUE THREAD

**Issue by tomkur** [Microsoft/TypeScript#25829]
**TypeScript Version:**  2.9.2

**Search Terms:**
visibility rules

**Code**
https://github.com/tomkur/ts-test
Steps to reproduce:
1) git clone https://github.com/tomkur/ts-test.git
2) cd ts-test
3) npm i
4) ./node_modules/typescript/bin/tsc --declaration hello.ts hello2.ts

**Expected behavior:**
Does not compile.

**Actual behavior:**
With TS 2.9 it compiles, whether with 2.8 it doesn't. The release notes for 2.9 seem to mention vaguely about "Relaxing declaration emit visiblity rules", but they don't mention these use-cases. It's cool that it works, but was this an intentional change? The declaration files now include the non-exported interfaces:
```ts
hello.d.ts
interface Foo {
    bar: string;
}
export declare const foo: Foo;
export {};

hello2.d.ts
declare class Foo {
    readonly bar: string;
    constructor(bar: string);
}
export declare const foo: Foo;
export {};
```
**Playground Link:**
N/A

**Related Issues:**
No

**Comment by mhegazy** [comment]
> but was this an intentional change?

yes.

>  The declaration files now include the non-exported interfaces

That would have been an error in the past. with TS 2.9 the compiler will emit them though they are not exported using the `export {}` trick to ensure a. no visibility errors are emitted, and b. no new declarations are exposed that should hae not.

In the examples above, the declarations for interface `Foo` and class `Foo` are not exported as intended. you can always export them in the `.ts` file.
