### ISSUE TITLE
arrow function gets incorrect type when followed by async function

### ISSUE THREAD

**Issue by wichert** [Microsoft/TypeScript#25821]
**TypeScript Version:**  3.1.0-dev.20180717 and 2.9.2

**Search Terms:** lambda arrow-function expression-type async

**Code**

I am trying to compile this code with `tsc -t ES2017`:

```ts
const isAMatch = (url: string): boolean => /cdn/.test(url)

(async () => {
console.log(isAMatch('foo'))
})()
```

This fails with an error:

```
 error TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'Boolean' has no compatible call signatures.

  1 const isAMatch = (url: string): boolean => /cdn/.test(url)
                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  2 
    
... 
  4 console.log(isAMatch('foo'))
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  5 })()
    ~~

```

Rewriting the arrow function to be a normal function is a workaround:

```ts
function isAMatch(url: string): boolean {
  return /cdn.*curve.*inject\/curvetips.js/.test(url)
}

(async () => {
console.log(isAMatch('foo'))
})()
```

But weirdly enough inserting an empty dummy function *also* fixes the compile error:

```ts
const isAMatch = (url: string): boolean => /cdn/.test(url)

function dummy() { }

(async () => {
console.log(isAMatch('foo'))
})()
```

I can not reproduce this error in the playground.

**Comment by kitsonk** [comment]
This is an ASI issue.  TypeScript is doing the best it can with invalid code.

What you have written gets parsed as:

```ts
const isAMatch = (url: string): boolean => /cdn/.test(url)(async () => {
console.log(isAMatch('foo'))
})()
```

Which you clearly did not intend.  You can verify that, is this JavaScript works:

```js
const isAMatch = (url) => /cdn/.test(url);

(async () => {
console.log(isAMatch('foo'))
})()
```

Whiles this doesn't:

```js
const isAMatch = (url) => /cdn/.test(url)

(async () => {
console.log(isAMatch('foo'))
})()
```

Semicolons in JavaScript are optional, except when they aren't! 😱

**Comment by wichert** [comment]
ah wow.. that makes perfect sense now that you point that out. I wonder if this mistake is common enough to add something like "perhaps you need to add a semicolon" to the compile error message.

**Comment by kitsonk** [comment]
> I wonder if this mistake is common enough to add something like "perhaps you need to add a semicolon" to the compile error message.

The problem is that it is ambiguous at best, which is why depending on ASI will eventually cause you problems.  How is TypeScript or JavaScript supposed to know that you weren't trying to invoke a function call that returns a function which you were invoking which returns a function which you were trying to invoke?   The best TypeScript can do is say "hey, something doesn't work right here, you are invoking something that can't be invoked, what were you really trying to do?"
