### ISSUE TITLE
Allowing the combination of extend and overloading with literals

### ISSUE THREAD

**Issue by johan-gorter** [Microsoft/TypeScript#25828]
## Search Terms

typescript interface extend overload

## Suggestion

Make the type system more powerful by allowing the combination of extend, overloading and literals as shown in the example.

## Use Cases

I currently have an inmemory data store that I want to describe in a strongly typed maner, see the example below.

## Examples

My current interface definition is error-prone to maintain due to its repetitive nature:

```ts
export interface DesignerProjections {
  Entity: { [instanceId: string]: EntityProjection };
  get(entityKey: 'Entity', instanceId: InstanceId<EntityProjection>): EntityProjection;
  getAll(entityKey: 'Entity'): {key: InstanceId<EntityProjection>, value: EntityProjection}[];

  Field: { [instanceId: string]: FieldProjection };
  get(entityKey: 'Field', instanceId: InstanceId<FieldProjection>): FieldProjection;
  getAll(entityKey: 'Field'): {key: InstanceId<FieldProjection>, value: FieldProjection}[];

  Attribute: { [instanceId: string]: AttributeProjection };
  get(entityKey: 'Attribute', instanceId: InstanceId<AttributeProjection>): AttributeProjection;
  getAll(entityKey: 'Attribute'): {key: InstanceId<AttributeProjection>, value: AttributeProjection}[];

  Relation: { [instanceId: string]: RelationProjection };
  get(entityKey: 'Relation', instanceId: InstanceId<RelationProjection>): RelationProjection;
  getAll(entityKey: 'Relation'): {key: InstanceId<RelationProjection>, value: RelationProjection}[];
}
```

This would be my suggestion how this can be improved, but this does not work due to multiple errors:

```ts
export type EntityKey = 'Entity' | 'Attribute';

export interface Part<K extends EntityKey, P extends DesignerProjection> {
  [K]: {[instanceId: string] : P}
  get(entityKey: K, instanceId: InstanceId<P>): P;
  getAll(): void
}

export interface DesignerProjections extends 
  Part<'Entity', EntityProjection>, 
  Part<'Attribute', AttributeProjection> {}
```

## Note
Compliments on getting the type system as powerful as it is today! Consider this to be a suggestion on how to improve it even more.

## Checklist

My suggestion meets these guidelines:
* [V] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [V] This wouldn't change the runtime behavior of existing JavaScript code
* [V] This could be implemented without emitting different JS based on the types of the expressions
* [V] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by andy-ms** [comment]
It looks like the situation basically simplifies to this?
```ts
interface Convert<A, B> {
    convert(a: A): B;
}

interface I extends Convert<number, string>, Convert<string, number> {} // Currently an error

declare const i: I;
i.convert(0); // string
i.convert(""); // number
```

Note that `export type I = Convert<number, string> & Convert<string, number>;` works, although `&` is unsafe and allows you to declare impossible things like `Convert<number, string> & Convert<number, boolean>`.

**Comment by ahejlsberg** [comment]
I don't think anything new is needed here. You can write it like this using existing features:

```ts
interface ProjectionByKey {
    Entity: EntityProjection;
    Field: FieldProjection;
    Attribute: AttributeProjection;
    Relation: RelationProjection;
}

type EntityKey = keyof ProjectionByKey;

type BaseProjections = {
    [P in EntityKey]: { [instanceId: string]: ProjectionByKey[P] }
}

export interface DesignerProjections extends BaseProjections {
    get<K extends EntityKey>(entityKey: K, instanceId: InstanceId<K>): ProjectionByKey[K];
    getAll<K extends EntityKey>(entityKey: K): { key: InstanceId<K>, value: ProjectionByKey[K] }[];
}
```

**Comment by johan-gorter** [comment]
Thanks @ahejlsberg for the answer, it works like a charm! (I had to replace `instanceId: InstanceId<K>` with `instanceId: InstanceId<ProjectionByKey[K]>`, but thats all)

Sorry about the late reply, I hope being on vacation is a valid excuse.
