### ISSUE TITLE
This condition will always return 'false' since the types have no overlap. Again.

### ISSUE THREAD

**Issue by Busyrev** [Microsoft/TypeScript#25830]
**TypeScript Version:**  3.1.0-dev.20180717
Error:  This condition will always return 'false' since the types '"work1"' and '"work2"' have no overlap.
Error:  Type '"work2"' is not comparable to type '"work1"'.
**TypeScript Version:**  2.9.2
Error:  Operator '==' cannot be applied to types '"work1"' and '"work2"'.
Error:  Type '"work2"' is not comparable to type '"work1"'.

**Search Terms:** 
Operator '==' cannot be applied to types 
This condition will always return 'false' since the types have no overlap.
Type is not comparable to type.
**Code**

```
function doWorkIf(work: 'work1' | 'work2'): void { 
    work = 'work1'; // made this for debug purpose and TS alerts error
    if (work == 'work1') {
        // do something
    }
    if (work == 'work2') { // YEA typescript, I know what I do, why you alert me??
        
        // do something
    }
}

function doWorkCase(work: 'work1' | 'work2'): void { 
    work = 'work1'; // made this for debug purpose and TS alerts error
    switch (work) { 
        case 'work1':
                // do something
            break;
        case 'work2':
                // do something
            break;
    }
}
```

**Expected behavior:**
no error
**Actual behavior:**
error
**Playground Link:** [link](https://www.typescriptlang.org/play/#src=function%20doWorkIf(work%3A%20'work1'%20%7C%20'work2')%3A%20void%20%7B%20%0D%0A%20%20%20%20work%20%3D%20'work1'%3B%20%2F%2F%20made%20this%20for%20debug%20purpose%20and%20TS%20alerts%20error%0D%0A%20%20%20%20if%20(work%20%3D%3D%20'work1')%20%7B%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20do%20something%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20if%20(work%20%3D%3D%20'work2')%20%7B%20%2F%2F%20YEA%20typescript%2C%20I%20know%20what%20I%20do%2C%20why%20you%20alert%20me%3F%3F%0D%0A%20%20%20%20%20%20%20%20%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20do%20something%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Afunction%20doWorkCase(work%3A%20'work1'%20%7C%20'work2')%3A%20void%20%7B%20%0D%0A%20%20%20%20work%20%3D%20'work1'%3B%20%2F%2F%20made%20this%20for%20debug%20purpose%20and%20TS%20alerts%20error%0D%0A%20%20%20%20switch%20(work)%20%7B%20%0D%0A%20%20%20%20%20%20%20%20case%20'work1'%3A%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20do%20something%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20break%3B%0D%0A%20%20%20%20%20%20%20%20case%20'work2'%3A%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20do%20something%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20break%3B%0D%0A%20%20%20%20%7D%0D%0A%7D)

**Related Issues:** https://github.com/Microsoft/TypeScript/issues/25642

Sorry, but it's me again. Why I have to write ugly code removing typing info (```work = 'work1' as any; ``` fixes the issue) to make my **correct** code work? I already specified allowUnreachableCode option to true. Why TS alerts me? This kind of alerts should be an linting rules, or may be configurable feature. I read https://github.com/Microsoft/TypeScript/issues/25642#issuecomment-404929935. I think all we shoult think about alerting correct code. It's really bad idea. Yea, I have to throw this [error detection]((https://github.com/Busyrev/TypeScript/blob/publicChecker/src/compiler/program.ts#L1524)) away in my own fork, but I am not always use the fork, its made for special puprose. I love typescript, and using it from 1.3 but this feature is really makes me angry. 

### Now constructive proposals:

- Create additional compiler option, like allowUnreachableCode to disable it.
- Move this error to ESLint or TSLint.
- Disable this error detection while allowUnreachableCode is set to true.
- Totally throw away this featue.
- Improve it with nominal types detection, and make this error detection safe for correct code.

Any kind of solution will be much better than now. May be there is another ways to solve it... Sorry, I'm really angry. Typescript is the best thing that happens in web, and I want to make it better.

**Comment by andy-ms** [comment]
You could write `if ((true)) work = 'work1';` which is generally useful for removing control-flow information.

**Comment by Busyrev** [comment]
Yea, there is many ways to fool compiler. And I have no claims to flow analysys. This is only issue about comparing things that TypeScript thinks uncomparable.

**Comment by modiract** [comment]
The fix for me was:

```
        const name = "test";
        const title = browser.executeScript(`return "test"`).toString(); //change the variable to string.
        return title === name; //returns true
```

**Comment by alvarosanmartinh** [comment]
In my case the error was triggered by:

`*ngIf="fooArray.length === 0"`

so i modified it to be:

`*ngIf="fooArray.length < 1"`

Makes no sense to me, but it works.
