### ISSUE TITLE
Functions in default parameters should have separate scope

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#2584]
``` TypeScript
function f()
    return (function(a= () => typeof b === "undefined") {
      var b = 1;
      return a();
    }());
}

console.log()
```

Expected: `true`
Actual: `false`

**Comment by RyanCavanaugh** [comment]
We'll need to rename the inner `b` on emit?

**Comment by mhegazy** [comment]
i think we have a few options:
1. always evaluate the initializes in there own scope
2. wrap the body of the function in a different scope
3. detect cases like that and make them an error, but still evaluate initializes in the function scope
4. do nothing

I think the least we can do, is when resolving names in initializes do them outside the function scope, so the above example would be an error assuming there is no global 'b' defined.

**Comment by falsandtru** [comment]
Why this serious difference is not fixed such a long time?

**Comment by falsandtru** [comment]
At least if you fix the type inference of this, Babel can be used to resolve transpile bug.

**Comment by Andarist** [comment]
This one still isn't fixed. Since the reported code is not complete, I'll re-post the correct one that can be used as a test case:
```ts
// @target: es5

function f() {
    return (function(a= () => typeof b === "undefined") {
      var b = 1;
      return a();
    }());
}

console.log(f())
```

**Comment by RyanCavanaugh** [comment]
It's been 9 years, no one has sent a PR in that time, and compiling to ES5 at this point is pretty rare. Doesn't seem to merit more consideration.
