### ISSUE TITLE
Should import completions win over member completions?

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#25845]
```ts
// ./bar.ts
export function blah() {
}
```

```ts
// ./foo.ts
export class C {
    blah() {
    }

    bar() {
        /**/
    }
}
```

Type in `blah` - completions include both the export as well as the method. A question with @wycats came up as to which should come first.

## Arguments for the `this.` completion

Locality is likely the strong argument here.

## Arguments for the import

For a lot of users, the fact that `blah` wasn't prefixed with `this.` means you didn't intend to use a member function.

**Comment by mhegazy** [comment]
//cc @andy-ms

**Comment by andy-ms** [comment]
I would vote for `this.` -- the fact that you didn't type `this.` just means that you're lazy, not that you don't intend to use the method.

**Comment by RyanCavanaugh** [comment]
I have never seen someone actually care 🙃
