### ISSUE TITLE
An error in document. Type 'null' is not assignable to type 'void'

### ISSUE THREAD

**Issue by kai712** [Microsoft/TypeScript#25857]
I found an error in the basic type section of the document
"Declaring variables of type void is not useful because you can only assign undefined or null to them"
However,the viod type cannot be assigned null

**Comment by MartinJohns** [comment]
It can, if you have `strictNullChecks` disabled: https://www.typescriptlang.org/play/#src=const%20foo%3A%20void%20%3D%20null%3B

**Comment by kitsonk** [comment]
What you also quote is that only `null` and `undefined` can be assigned to `void`, where as it makes no statements about `void` being assignable to anything, including `null`, but `null` is not assignable to `void` under `--strictNullChecks`.

How is this causing an issue?  Also as stated, it would be great if you could reference the document.

**Comment by kai712** [comment]
ok，thanks
