### ISSUE TITLE
Types are not imported properly for packages that use exports.default.

### ISSUE THREAD

**Issue by zavr-1** [Microsoft/TypeScript#25854]
**TypeScript Version:**  3.1.0-dev

**Search Terms:** type export default

**Code** and **Actual Behaviour**

### `tt.js`
```js
/**
 * Run this function
 * @param {string} t
 */
export default function testFunction(t) {
  return t
}
```

### `t.js`
```js
import t from './tt'

t
```

<table><thead><th>Screenshot</th><th>Result</th></thead><tr><td>

![test](https://user-images.githubusercontent.com/21156791/43032322-dd9f6f28-8cab-11e8-995a-b6e414fac7e7.png)
</td><td>The preview shows correctly.</td></tr></table>

### `tt.js` (compiled w/ babel)
```js
Object.defineProperty(exports, '__esModule', {
  value: true,
})
exports.default = testFunction

/**
 * Run this function
 * @param {string} t
 */
function testFunction(t) {
  return t
}
```

### `t.js`
```js
import testFunction from './tt'

testFunction(
```

<table><thead><th>Screenshots</th><th>Result</th></thead><tr><td>

![test](https://user-images.githubusercontent.com/21156791/43032389-82f8e7b4-8cad-11e8-88f7-08a0e998c268.png)

![test](https://user-images.githubusercontent.com/21156791/43032384-546713bc-8cad-11e8-9c74-4061ee55e218.png)

</td><td>

There's no description on hover, but it comes up when starting to type arguments. But this is **only because** it's got the same name so VS Code looks up by the name. Proof: if function is not exported, it will still show description. Therefore, same as case 3.</td></tr></table>

### `tt.js` (compiled w/ babel)
```js
Object.defineProperty(exports, '__esModule', {
  value: true,
})
exports.default = testFunction

/**
 * Run this function
 * @param {string} t
 */
function testFunction(t) {
  return t
}
```

### `t.js`
```js
import t from './tt'

t(
```

<table><thead><th>Screenshots</th><th>Result</th></thead><tr><td>

![test](https://user-images.githubusercontent.com/21156791/43032410-0bd00d74-8cae-11e8-8b41-741e06f7c263.png)

![test](https://user-images.githubusercontent.com/21156791/43032421-3287dd8e-8cae-11e8-8b88-4c1f69221117.png)

</td><td>There's no description on hover, it does not come up when starting to type.</td></tr></table>

**Expected behavior:** Should always work as scenario 1.

So it basically means that all modules transpiled with babel must be `import`ed using their original name? And even then it's only because it has got the same name. 

Consider having 2 files:

### tt.js
```js
exports.default = testFunction

/**
 * Run this function (test 1)
 * @param {string} t1
 */
function testFunction(t1) {
  return t1
}
```
and
### tt2.js
```js
exports.default = testFunction

/**
 * Run this function (test 2)
 * @param {string} t2
 */
function testFunction(t2) {
  return t2
}
```

and a file in which I want to use them:

### t.js
```js
import testFunction from './tt'
import testFunction2 from './tt2'

/** @type {typeof import('./tt2')} */
testFunction2()
```

I won't be able to ever see type of `testFunction2` even using `typeof {import}`? Unless I do `module.exports = testFunction` in `tt2.js` which Babel never does (and there's no setting for it). I think TypeScript should parse `exports.default = ` in the same way as `module.exports = ` as `babel@5` did export then this way, whereas `babel@6` doesn't. 

https://github.com/59naga/babel-plugin-add-module-exports#readme

I can't even use the above plugin because even though it adds `module.exports = exports.default;` VS Code does not assign the type to `module.exports`.

**Comment by andy-ms** [comment]
@zavr-1 This seems to be working for me.

![exports_default](https://user-images.githubusercontent.com/19274678/43292997-dcfc8520-90ec-11e8-92ba-4c9142ccf9bf.jpg)

**Comment by zavr-1** [comment]
@andy-ms doesn't work for me in the insiders on mac 

Version 1.26.0-insider (1.26.0-insider)

![screen shot 2018-08-02 at 22 59 14](https://user-images.githubusercontent.com/21156791/43613574-c848f422-96a7-11e8-8f2e-10e4215eef7b.png)

**Comment by andy-ms** [comment]
@zavr-1 So what do you see when hovering over `g`? It's not clear what's not working in that picture.

**Comment by andy-ms** [comment]
OK, reproduced this bug. It happens because `--allowSyntheticDefaultImports` is on by default in inferred projects.

```
/// <reference path='fourslash.ts'/>

// @allowJs: true
// @allowSyntheticDefaultImports: true

// @Filename: /a.js
////exports.default = f;
/////**
//// * Run this function
//// * @param {string} t
//// */
////function f(t) {}

// @Filename: /b.js
////import f from "./a"
/////**/f

verify.quickInfoAt("", "?", "Run this function"); // No documentation
```

@weswigham Could you take a look?

**Comment by weswigham** [comment]
`import f from "./a"` refers to the entire module of `a.js` and _not_ its default. There's no `__esModule` marker, so that's correct, too.

**Comment by weswigham** [comment]
For reference, if you edit the output to have an `__esModule` marker that we can find, it behaves like you would like:
```ts
/// <reference path='fourslash.ts'/>

// @allowJs: true
// @allowSyntheticDefaultImports: true

// @Filename: /a.js
////exports.__esModule = true;
////exports.default = f;
/////**
//// * Run this function
//// * @param {string} t
//// */
////function f(t) {}

// @Filename: /b.js
////import f from "./a"
/////**/f

verify.quickInfoAt("", `(alias) (property) f: (t: string) => void
import f`, "Run this function"); // Passes
```

**Comment by weswigham** [comment]
We should _probably_ recognize
```ts
Object.defineProperty(exports, 'name', {...});
```
at the top level of a file as a special assignment, since our emit when targeting es5 and babel's current default emit now use such a call for the marker over a straight assignment.

@sandersn You know how doable this is?

**Comment by weswigham** [comment]
@zavr-1 As a workaround, if you use babel with the `loose` preset, you can get it to emit the marker in a form we can understand. (Specifically only loose for `babel-plugin-transform-es2015-modules-commonjs` is required to get the output to change)

**Comment by zavr-1** [comment]
@weswigham alright thanks, the `loose` option did the trick! it also works for `babel-plugin-transform-modules-commonjs` which I guess is the same thing as `babel-plugin-transform-es2015-modules-commonjs`.

**Comment by sandersn** [comment]
@weswigham I have seen this pattern around and agree that it would be useful to have. I can't tell from this discussion whether it needs a new issue to track it or not. Do you think so? If so, we should change the title to say exactly that.

Adding the pattern is not *too* difficult, but a lot more wordy than existing patterns. You'd have to

1. Put a special case in the binder when binding call expressions, probably, to check for `expression: Object.defineProperty, parameters[0] = exports, parameters[1] = StringLiteral`. You then need to decide where to mark the declaration for consumption in the checker. Probably on `exports`?
2. Put some special-case code in the checker to retrieve the type of `exports.name`. `checkCallExpression` should already do the right thing as far as error checking.

I would note that roundtripping our emit is not a goal and I am tempted to make it a non-goal. I'm not convinced roundtripping Babel's emit should be a goal either, but humans also write this pattern, so I'd class it as Nice to Have right now.

**Comment by weswigham** [comment]
We can make this issue track it - we probably need to edit the title and the OP a bit to make the left not burried in the comments, however.

**Comment by zavr-1** [comment]
@weswigham it doesn't actually work even if you set `loose` and define `exports.__esModule = true`. At least not in the insiders.

**Comment by weswigham** [comment]
Hm. In our test harness, this:
```ts
/// <reference path='fourslash.ts'/>

// @allowJs: true
// @allowSyntheticDefaultImports: true

// @Filename: /a.js
////exports.__esModule = true;
////exports.default = f;
/////**
//// * Run this function
//// * @param {string} t
//// */
////function f(t) {}

// @Filename: /b.js
////import q from "./a"
/////**/q

verify.quickInfoAt("", `(alias) (property) q: (t: string) => void
import q`, "Run this function"); // Passes
```
Still works fine (though I've only checked on latest `master` TS, so it may have been recently fixed)? @andy-ms know anything?

**Comment by weswigham** [comment]
Ahhh @zavr-1 your example seems to be missing an actual assignment to `exports.__esModule`
