### ISSUE TITLE
Recursive Mapped Conditional Type inferring top-level children to `any`

### ISSUE THREAD

**Issue by osdiab** [Microsoft/TypeScript#25860]
**TypeScript Version:**  3.1.0-dev.20180721

**Search Terms:** any recursive mapped conditional inference

**Code**

```ts
    interface MyNumbers {
      cool: {
        mysteriouslySo: number;
        comfortablySo: number;
      };
      scary: {
        ominouslySo: number;
      };
    }
    
    type MapLeaves<OldShape, NewLeaf> = OldShape extends {}
      ? { [k in keyof OldShape]: MapLeaves<OldShape[k], NewLeaf> }
      : NewLeaf;
    
    // This is inferring as { cool: any, scary: any }, not what I expected!
    type MyStrings = MapLeaves<MyNumbers, string>;
```

**Expected behavior:**

I'm not sure if I'm misusing recursive mapped conditional types here, but I expected MyStrings to be 

```ts
    interface MyNumbers {
      cool: {
        mysteriouslySo: string;
        comfortablySo: string;
      };
      scary: {
        ominouslySo: string;
      };
    }
```

**Actual behavior:**
It's inferred as 

```ts
{ cool: any, scary: any }
```

**Playground Link:**
[Link](https://www.typescriptlang.org/play/index.html#src=%20%20%20%20interface%20MyNumbers%20%7B%0D%0A%20%20%20%20%20%20cool%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20mysteriouslySo%3A%20number%3B%0D%0A%20%20%20%20%20%20%20%20comfortablySo%3A%20number%3B%0D%0A%20%20%20%20%20%20%7D%3B%0D%0A%20%20%20%20%20%20scary%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20ominouslySo%3A%20number%3B%0D%0A%20%20%20%20%20%20%7D%3B%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20%0D%0A%20%20%20%20type%20MapLeaves%3COldShape%2C%20NewLeaf%3E%20%3D%20OldShape%20extends%20%7B%7D%0D%0A%20%20%20%20%20%20%3F%20%7B%20%5Bk%20in%20keyof%20OldShape%5D%3A%20MapLeaves%3COldShape%5Bk%5D%2C%20NewLeaf%3E%20%7D%0D%0A%20%20%20%20%20%20%3A%20NewLeaf%3B%0D%0A%20%20%20%20%0D%0A%20%20%20%20%2F%2F%20This%20is%20inferring%20as%20%7B%20cool%3A%20any%2C%20scary%3A%20any%20%7D%2C%20not%20what%20I%20expected!%0D%0A%20%20%20%20type%20MyStrings%20%3D%20MapLeaves%3CMyNumbers%2C%20string%3E%3B)

**Comment by ahejlsberg** [comment]
Duplicate of #23897. The types are actually computed correctly, but our type display logic doesn't currently descend into recursive mapped types because they could potentially be infinite.

```ts
type MapLeaves<OldShape, NewLeaf> = OldShape extends object
  ? { [k in keyof OldShape]: MapLeaves<OldShape[k], NewLeaf> }
  : NewLeaf;

type ShouldBeString = MapLeaves<MyNumbers, string>["cool"]["comfortablySo"];
```

Here, `ShouldBeString` is indeed of type `string`. By the way, note that I had to change `{}` to `object` in your conditional type. The `{}` type is actually a supertype of every type but `null` or `undefined`, whereas `object` is a supertype of only objects (and not primitive types).

**Comment by osdiab** [comment]
Ah, interesting. Sounds like displaying it with some kind of ellipsis or placeholder type would be more ideal. I'll post to that issue.
