### ISSUE TITLE
tsc --build with rootDir and outDir is compiling files within a project in alphabetical order, breaking imports

### ISSUE THREAD

**Issue by rosslovas** [Microsoft/TypeScript#25864]
**TypeScript Version:**  3.1.0-dev.20180721

**Search Terms:** tsc build project reference rootDir outDir 

**Code**

Brief summary: When `rootDir` and `outDir` are involved as well as a project reference, source files within an individual project that has a dependency project would be compiled in alphabetical order. The consequence is that an `A.ts` that imports from `B.ts` will fail with `Output file '.../B.d.ts' has not been built from source file '.../B.ts'` but if I rename `A.ts` to `C.ts` everything works, as does removing the project reference or not using root/outDir.

The setup is hard to fully convey through text so here's a zip: [repro.zip](https://github.com/Microsoft/TypeScript/files/2217912/repro.zip). `npm install` then `npm run build` to trigger the issue.

**Expected behavior:**  Compiles both `main` and `other` projects successfully regardless of the names of the source files.

**Actual behavior:**

```error TS6305: Output file '.../B.d.ts' has not been built from source file '.../B.ts'.```

**Comment by hwillson** [comment]
I was just hit by this as well - exact same issue, and the reproduction is bang on what I'm seeing. Let me know if there's anything I can do to help expedite this (PR, tests, another repro, test a beta, etc.). Thanks!

**Comment by resynth1943** [comment]
This is broken. Again.

**Comment by theseyi** [comment]
This is broken in 3.7.5

**Comment by deeptowncitizen** [comment]
the same in 3.7.2

**Comment by sparebytes** [comment]
Upgrading from 3.7.5 to 3.8.3 solved it for me.

**Comment by sparebytes** [comment]
I had the same problem but it stopped when I took care of the following. (I'm on v3.8.3 btw).

- If I ever deleted the outDir I also deleted the generated `.tsbuildinfo` file too.
  - To exacerbate the situation, the `.tsbuildinfo` files were created where I would not expect, not in the same folder where the tsconfig.json lives. I didn't catch it because it was gitignored. Regardless, manually setting the "tsBuildInfoFile" compiler option on all my tsconfig files solved that issue.
- Set the `paths` compilerOption to the emitted files of any dependencies.

My tsconfigs look like this:
```json
{
  "compilerOptions": {
    "rootDir": "./src",
    "outDir": "./dist/lib",
    "composite": true,
    "baseUrl": "../",
    "paths": {
      "my-dependency": [
        "./my-dependency/dist/lib/index"
      ],
      "my-dependency/*": [
        "./my-dependency/dist/lib/index/*"
      ]
    },
    "tsBuildInfoFile": "tsconfig.tsbuildinfo"
  },
  "include": ["src"],
  "exclude": [
    "**/*.test.ts",
    "**/*.test.tsx"
  ],
  "references": [
    {
      "path": "../my-dependency/tsconfig.json"
    }
  ]
}
```

**Comment by desmap** [comment]
I am on `3.9.3` and the bug is still there... @sheetalkamat 

This breaks the project references feature and makes it entirely unusable.

**Comment by sheetalkamat** [comment]
@desmap  you would need to open new issue with exact repro steps to be able to investigate this. The repro in this issue seems to be working correctly.

**Comment by joelday** [comment]
@sheetalkamat Unfortunately I'm not in a position to set up a repro project, but in my case, this is happening when the build script is running within a docker image build. I assume it has to do with the way the output file is compared with an existing tsbuildinfo file that has been copied or volume mounted. That's speculative, so I'll try to get an exact answer once I solve the issue.

**Comment by fabiancook** [comment]
https://github.com/microsoft/TypeScript/issues/25864#issuecomment-596217193 

Can a resolution of this to be not to use tsbuildinfo if the outDir doesn't exist?
