### ISSUE TITLE
Intellisense is showing "no suggestions" .

### ISSUE THREAD

**Issue by yln99517** [Microsoft/TypeScript#25862]
Here is the example code and playground file [Playground](http://www.typescriptlang.org/play/#src=interface%20%20Foo%20%7B%0D%0A%09x%3A%20number%3B%0D%0A%09y%3A%20string%3B%0D%0A%7D%0D%0Ainterface%20Bar%20%7B%0D%0A%09a%3A%20boolean%2C%0D%0A%09b%3A%20number%2C%0D%0A%09z%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20FooBar%20%7B%0D%0A%09%22foo%22%3A%20Foo%2C%0D%0A%09%22bar%22%3A%20Bar%0D%0A%7D%0D%0A%0D%0Adeclare%20function%20test%3CK%20extends%20keyof%20FooBar%2C%20J%20extends%20keyof%20FooBar%5BK%5D%3E(i%3A%20K%2C%20l%3A%20J)%3B%0D%0Atest(%22bar%22%2C%20%22%22))
```typescript
interface  Foo {
	x: number;
	y: string;
}
interface Bar {
	a: boolean,
	b: number,
	z: string;
}

interface FooBar {
	"foo": Foo,
	"bar": Bar
}

declare function test<K extends keyof FooBar, J extends keyof FooBar[K]>(i: K, l: J);
test("foo", "")
```

After typing "," popover message showing all the possible values of "foo". But when we start typing second parameter "No suggestion" message is appearing. Is there any other syntax to achieve this? How to get intellisense for second parameter?

**Comment by DanielRosenwasser** [comment]
Duplicate of #20782, #14812, and ultimately #14772. :sad:

**Comment by yln99517** [comment]
OK, Closing the Issue.
