### ISSUE TITLE
Incorrect emit for computed accessors in object literals in ES3/ES5

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#2586]
For each property, we emit something like

```JavaScript
_a[c] = Object.defineProperty({ enumerable: /* ...... */ })
```

rather than actually passing `_a` and `c` into `Object.defineProperty`.

**Comment by mhegazy** [comment]
@DanielRosenwasser do we have a test for this already?

**Comment by DanielRosenwasser** [comment]
@mhegazy should have been fixed by the PR but I should add the test from the compat table that pointed this out.
