### ISSUE TITLE
Type '{}' cannot be used as an index type

### ISSUE THREAD

**Issue by jeffsaremi** [Microsoft/TypeScript#25872]
Typescript version 2.9.2
Running in vscode 1.25.1
Windows 10

I have this code which runs perfectly in Javascript but errors out in TypeScript:

Search Terms:
index,type

Code:

```
let a = {};
let b = { name:"key"};
a.b = { value: "some value" };
for (let key in a) {
    console.log(a[key]); // Error in TypeScript; Successful execution in JavaScript!
}
```
Actual behavior:
I should be able to use any object as the key in an object

Playground Link:
none

Related Issues:
none that I can think of

**Comment by jeffsaremi** [comment]
Yes a.b would also be marked as error.

**Comment by jeffsaremi** [comment]
Could you re-label this so someone could look into it? thanks

**Comment by mhegazy** [comment]
Give a an explicit type.

**Comment by jeffsaremi** [comment]
Oh ok. that's not too bad. closing this then.

**Comment by jeffsaremi** [comment]
I am re-opening this issue. There is a very annoying behavior implemented here.
If I create a specific type such as "`MyKey`" I not only cannot use it in ` a[mykey]` but I can't use in a phrase like "`if(mykey in a)`" either.
Please fix this.

**Comment by jeffsaremi** [comment]
Closing this. More appropriate way is to use WeakMap.
