### ISSUE TITLE
Assignability of functions with a rest parameter of an empty tuple possibly incorrect

### ISSUE THREAD

**Issue by bterlson** [Microsoft/TypeScript#25871]
**TypeScript Version:**  3.1.0-dev.20180722
**Code**

```ts
declare var f1: (... args: any[]) => void;

declare var f2: () => void;
declare var f3: (...args: []) => void;
declare var f4: (a: never) => void;

f1 = f2; // ok
f1 = f3; // error
f1 = f4; // error
```

**Expected behavior:**
I want to create function types that are assignable to f1 using tuple types ala f3. I expected f3 to behave more like f2 than f4.

**Actual behavior:**
f3 cannot be assigned to f2.

But adding any type into f3's args tuple makes the error go away.

**Comment by mhegazy** [comment]
Just to be clear, this issue is about missing error for:

```ts
declare var f3: (...args: [number]) => void;

f1 = f3;
```

**Comment by ahejlsberg** [comment]
@mhegazy In your example, `f1 = f6` isn't and shouldn't be an error. Any parameter list should be assignable to `(...args: any[]) => xxx`.

**Comment by mhegazy** [comment]
yes. you are right. we allow that though it is unsafe :)
