### ISSUE TITLE
Better error messages for converting symbols to strings

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#25870]
Starting

```ts
declare let x: symbol;

// [ts] Type 'symbol' cannot be converted to type 'string'.
`${x}`;

// [ts] The '+' operator cannot be applied to type 'symbol'.
"" + x;
```

I believe with TypeScript 2.9, we started erroring on the former operation (#22251). When upgrading to 2.9 with @wycats, we got these error messages and it became clear that for most users it wouldn't immediately be obvious why this was an error.

@wycats had the recommendation that we suggest using `String(x)`:

```ts
Type 'symbol' cannot be converted to type 'string'. Consider wrapping this expression in 'String(...)'.
```

**Comment by mhegazy** [comment]
Related to the change in https://github.com/Microsoft/TypeScript/pull/25541

**Comment by DanielRosenwasser** [comment]
Thanks @mattmccutchen!
