### ISSUE TITLE
Need to cast string as string literal

### ISSUE THREAD

**Issue by Akxe** [microsoft/TypeScript#25889]
**TypeScript Version:**  3.1.0-dev.201xxxxx

**Search Terms:**
string as string, cast string as string, cast string as string literal
I am sorry, I have no idea on how to search for it, enlighten me, if you know. 

**Code**

```ts
interface Iperiod {
	id: number | 'current';
	name: string;
}

function usePeriods(periods: Iperiod[]) {
	return periods;
}

usePeriods(['now', 'then'].map((name, index) => {
	if (name == 'now') {
		return {
			name,
			id: 'current',
		}
	}
	
	return {
		name,
		id: index,
	}
}));
```

**Expected behavior:**
It should work, as `id` can be `number | 'current'`.

**Actual behavior:**
Error string is not assignable to 'current'.

**Playground Link:** 
[link](http://www.typescriptlang.org/play/#src=interface%20Iperiod%20%7B%0D%0A%09id%3A%20number%20%7C%20'current'%3B%0D%0A%09name%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Afunction%20usePeriods(periods%3A%20Iperiod%5B%5D)%20%7B%0D%0A%09return%20periods%3B%0D%0A%7D%0D%0A%0D%0AusePeriods(%5B'now'%2C%20'then'%5D.map(name%20%3D%3E%20%7B%0D%0A%09if%20(name%20%3D%3D%20'now')%20%7B%0D%0A%09%09return%20%7B%0D%0A%09%09%09name%2C%0D%0A%09%09%09id%3A%20'current'%20as%20'current'%2C%0D%0A%09%09%7D%0D%0A%09%7D%0D%0A%09%0D%0A%09return%20%7B%0D%0A%09%09name%2C%0D%0A%09%09id%3A%201%2C%0D%0A%09%7D%0D%0A%7D))%3B%0D%0A)

**Related Issues:** 
No, but I suppose a few.

**Comment by j-oliveras** [comment]
If you declares the return type of the lambda it works:
```ts
interface Iperiod {
	id: number | 'current';
	name: string;
}

function usePeriods(periods: Iperiod[]) {
	return periods;
}

usePeriods(['now', 'then'].map((name, index): Iperiod => {
	if (name == 'now') {
		return {
			name,
			id: 'current',
		}
	}
	
	return {
		name,
		id: index,
	}
}));
```

I think is a duplicate.

**Comment by Akxe** [comment]
If I cast it like so it works: 
```
return {
	name,
	id: 'current' as 'current',
}
```
, but damn, it feels dumb...

**Comment by andy-ms** [comment]
There are actually a few reasons why you should ensure an object literal has a contextual type -- it helps avoid misspelling optional properties and gets you literal types. (See palantir/tslint#2581)

**Comment by Akxe** [comment]
@j-oliveras But the `usePeriods` function requires `Iperiod[]`, therefor this information should be passed down to the map method return type, don't you think?

**Comment by andy-ms** [comment]
Created an issue to improve error reporting here: #26413

**Comment by Akxe** [comment]
Could you please elaborate mor on how this helps "avoid misspelling optional properties and gets you literal types"? If this should be sometime closed it should bet a proper explanation of what is that big benefit that we have to cast string literal to string literals.

**Comment by andy-ms** [comment]
The "it" in that sentence reverse to "has a contextual type", which comes from giving a type annotation to the object. That also prevents you from needing to cast string literals.

```ts
interface I {
    kind: "a" | "b",
    optional?: number
}
declare function f(i: I): void;

// No contextual type
const i0 = { kind: "a" };
f(i0); // fails

const i1 = { kind: "a" as "a", optinal: 3 };
f(i1); // No compile error, but "optional" not specified as intended

f({ kind: "a", optional: 3 }); // Perfect!
f({ kind: "a", optinal: 3 }); // Compiler catches "optinal" spelling error
```

**Comment by Akxe** [comment]
I still have hard time understanding it. Or at least to me it is almost like
``` ts
f({ kind: "a", optinal: 3 });
f({ kind: "a" as "a", optinal: 3 });
```

I don't see why, if the string literal is in returned object is treated differently from one constructed in parameter.

**Comment by RyanCavanaugh** [comment]
@Akxe the effective question is, let's say you write this
```ts
const obj = { kind: "a" };
obj.kind = "b";
```
Is this code valid?

When you write an expression, TS has to guess what the domain you intended was. We use the same inference for determining how it's legal to use the object both for read and for writes -- `obj.kind` is inferred to be `string` unless specified otherwise, which means that the assignment of `"b"` is legal *but* that we aren't guaranteeing it's always `"a"` (thus the error).

**Comment by Akxe** [comment]
I get that point, but consider this
``` ts
interface I {
    code: 'mapped',
    name: string,
}

const a: I[] = ['a', 'b'].map(name => ({
    original: 'mapped',
    name,
}));
```
Here the error is definitely unnecessary, as `original` will be always of type `'mapped'`.

**Comment by andy-ms** [comment]
@Akxe That's a bug: #11152

**Comment by DominicTobias** [comment]
`'something' as 'something'` seems incredibly dumb and pointless. TS should simply error if they didn't pass one of the string literals defined. I don't want my users to have to import a certain type they should just be able to pass a string that is type checked

**Comment by IlyaSemenov** [comment]
Note: `'something' as const` is a bit less dumb but works the same.

**Comment by pstephenwille** [comment]
Was there a reason this was closed?  I seemed to have missed it.
