### ISSUE TITLE
Warn on impossible type predicate

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#25882]
**TypeScript Version:**  3.1.0-dev.20180721

**Code**

```ts
declare function isString(x: unknown): x is string;
function f(x: number): number {
    return isString(x) ? x : x;
}
```

**Expected behavior:**

Error at `isString(x)`: a `number` is never a `string`.

**Actual behavior:**

No error.

This is relevant in the TypeScript codebase because we might write dead code due to using a type predicate that should never happen, such as calling `isBinaryExpression` on a `Statement`.

**Comment by ajafff** [comment]
What's the difference to https://github.com/Microsoft/TypeScript/issues/25316?

**Comment by andy-ms** [comment]
None.
