### ISSUE TITLE
AbortSignal.abort does not accept `() => void` while it should

### ISSUE THREAD

**Issue by zerkms** [Microsoft/TypeScript#25887]
**TypeScript Version:** 2.9.2

**Search Terms:** AbortSignal AbortController

**Code**

```ts
const controller = new AbortController();
controller.signal.onabort(() => {});
```

**Expected behavior:**
It should compile

**Actual behavior:**
`AbortSignal.onabort` typing fails

**Playground Link:** 
https://www.typescriptlang.org/play/index.html#src=const%20controller%20%3D%20new%20AbortController()%3B%0A%0Acontroller.signal.onabort(()%20%3D%3E%20%7B%7D)%3B

**Related Issues:** 
https://github.com/Microsoft/TypeScript/issues/19418

**Comment by mhegazy** [comment]
I think you meant:

```ts
controller.signal.onabort = () => { }; 
```

**Comment by zerkms** [comment]
Oh gosh :-S
