### ISSUE TITLE
Languages service issue with definition files?

### ISSUE THREAD

**Issue by cleverguy25** [Microsoft/TypeScript#2590]
I am trying to create something in TypeScript that uses the D3 library.  I have the latest d3.d.ts (1.7.0) and I have a small file like this:

    /// <reference path="typings/d3/d3.d.ts" />
    class TimeMultipleSeriesLineChart {
         xScale = d3.time.scale();
    }

The issue is that it compiles fine, intellisense works fine, but the language editor thinks it is an external module and wants to import it (see the screenshot).
![d3](https://cloud.githubusercontent.com/assets/5375521/6958165/0204dbba-d8bd-11e4-9090-db7ec20c0e77.png)

**Comment by CyrusNajmabadi** [comment]
This does not appear the TypeScript language service provided by MS.  Are you perhaps using a plugin like resharper?

**Comment by cleverguy25** [comment]
I am using resharper, but I disable all intellisense for it, just in case.  Also the d3 is red, wouldn't that be the typescript language service?

**Comment by CyrusNajmabadi** [comment]
Unfortunately, no.   The TypeScript language service does not color anything red.  It also does not use 'alt enter' for any shortcut key.  Finally, no language service features include a popup with a 'question mark' icon that looks like that. 

If you disable resharper (and any other plugins) entirely, do you still experience this issue?

**Comment by CyrusNajmabadi** [comment]
Based on this image: https://www.jetbrains.com/resharper/features/screenshots/90/ts_cut_paste.png
It does look like the above would be from resharper.
