### ISSUE TITLE
Doc comment has trailing space

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#25916]
**TypeScript Version:**  master

**Code**

```ts
/// <reference path='fourslash.ts'/>

// @Filename: quickInfoJsDocTags.ts
/////** Doc */
////const /**/x = 0;

verify.quickInfoAt("", "const x: 0", "Doc");
```

**Expected behavior:**

Test passes.

**Actual behavior:**

Test fails. Doc comment is actually `"Doc "`.

**Comment by tschaub** [comment]
I'm interested in helping out with the JSDoc support in TypeScript.  Let me know if #26029 looks like a reasonable approach to this issue.  Thanks!

**Comment by andy-ms** [comment]
Related: #21123

**Comment by mhegazy** [comment]
thanks @tschaub!
