### ISSUE TITLE
some wrong with 

### ISSUE THREAD

**Issue by netren** [microsoft/TypeScript#25921]
**TypeScript Version:**  2.9.2

**Search Terms:**

**Code**

```ts
class AReq {
    a: number;

}
class ARsp {
    aa: number;
}

class BReq {
    a: number;
    b: number;
}
class BRsp {
    bb: number;
}

type CType<T> = T extends AReq ? ARsp :
        T extends BReq ? BRsp : "object";

function doCReturn<T>(a : T) : CType<T> {
    return null;
}

function doSth() {
    let aRsp: ARsp = doCReturn(new AReq());
    let bRsp: BRsp = doCReturn(new BReq());
    console.log(bRsp.bb)
}
```

**Expected behavior:**
 it would compile normal
**Actual behavior:**
ERROR in D:\prj\tt\minigame\protogen\IGameProto.ts(26,9)
      TS2322: Type 'ARsp' is not assignable to type 'BRsp'.
  Property 'bb' is missing in type 'ARsp'.

i think it would be check the type in each properties not the actual type,and when i change the sequence
like type CType<T> = 
        T extends BReq ? BRsp : T extends AReq ? ARsp : "object";
it would be normal.
**Playground Link:** 

**Related Issues:**

**Comment by j-oliveras** [comment]
At declaration of `CType` the extends are [compared structurally](https://github.com/Microsoft/TypeScript/wiki/FAQ#what-is-structural-typing). The type `BReq` _structurally_ extends the `AReq` (has an `a: number` field). The computed return type of second call of `doCReturn` is `ARsp`.

Swapping the branches of `CType` solve the issue.
```ts
type CType<T> = T extends BReq ? BRsp :
	T extends AReq ? ARsp : "object";
```
You can also solve this adding a private field to class `AReq`.
```ts
class AReq {
    a: number;
    private p: any;
}
```

**Comment by netren** [comment]
i see the compared structurally,but has any other idea to solve this.
use private member look like  strangly.
