### ISSUE TITLE
ES6 import * alias missing in autocomplete

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#2592]
e.g I should see `bas` here : 

![image](https://cloud.githubusercontent.com/assets/874898/6959426/863be958-d964-11e4-934e-506afda5031f.png)

TIP: bas is valid as members autocomplete fine : 
![image](https://cloud.githubusercontent.com/assets/874898/6959434/91daa254-d964-11e4-88fc-21c525a491f2.png)

**Comment by mhegazy** [comment]
Can you try the latest from master? 
![capture1](https://cloud.githubusercontent.com/assets/8000722/6968184/93fb0b96-d919-11e4-8392-aa31ee79ff90.PNG)
![capture2](https://cloud.githubusercontent.com/assets/8000722/6968187/95dd8768-d919-11e4-884d-cc6f911e58cb.PNG)

**Comment by basarat** [comment]
Yup. Thanks :rose: 

![image](https://cloud.githubusercontent.com/assets/874898/6976910/73457a5a-d9fd-11e4-964b-970db556f79b.png)
