### ISSUE TITLE
playground is not aligned

### ISSUE THREAD

**Issue by Kingwl** [microsoft/TypeScript#25920]
**TypeScript Version:**  3.1.0-dev.201xxxxx

**Search Terms:**
website, playground 
**Code**
![1111](https://user-images.githubusercontent.com/6831019/43188539-e82c0a68-9026-11e8-9977-19dcf5867c9a.png)

😉

**Comment by orta** [comment]
There's a new playground now, so this bug is conceptually "fixed"
