### ISSUE TITLE
[loc][Query][TypeScript] Localizability of 0; "OrganizeImportsFailureMessage" 

### ISSUE THREAD

**Issue by PDostalek** [Microsoft/TypeScript#25924]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.
Please re-assign back to use in case you are not the right contact person or you can´t assign to a proper person.
Can you help please?
Thanks!

Source:
Failed to organize imports

File Name:
LanguageService\TypeScriptLanguageService\bin\Release\localize\ENU\Microsoft.CodeAnalysis.TypeScript.EditorFeatures.dll

Resource ID:
0; "OrganizeImportsFailureMessage"

Query:
Does it refer to "Import statements"?

**Comment by mhegazy** [comment]
> Does it refer to "Import statements"?

yes.

**Comment by PDostalek** [comment]
Thanks for confirming.
