### ISSUE TITLE
Strange inference for function parameters of intersection type

### ISSUE THREAD

**Issue by arma-gast** [Microsoft/TypeScript#25929]
**Search Terms:**
intersection function parameters react component

**Code**

```ts
interface T1 {
  required1: string;
}

interface T2 {
  required2: string;
}

const f1: (param: T1 & T2) => void = () => undefined;
const f2: (param: T1) => void = f1; // (1)
```

**Expected behavior:**
Error in line (1).

**Actual behavior:**
No errors.

It should be impossible to assign a function to a variable or constant of function type with narrower parameter types, while reverse assignment should be possible.

**Comment by mattmccutchen** [comment]
It's allowed to convert a function to a type that has more parameters, since the extra parameters will just get ignored when the function is called.  See the [handbook](https://www.typescriptlang.org/docs/handbook/type-compatibility.html#comparing-two-functions).

**Comment by arma-gast** [comment]
Thats correct. But example shows case where f2 has narrower parameter type. It allows you to call it with `{ required1: "some string" }` while f1 requires field "required2".

**Comment by andy-ms** [comment]
That code does have an error with `--strictFunctionTypes` turned on.

**Comment by arma-gast** [comment]
Arrgh!.. Did not know about this option. Thank you!
