### ISSUE TITLE
Property type guards don't narrow type of the object the property belongs to

### ISSUE THREAD

**Issue by thorn0** [Microsoft/TypeScript#25930]
**TypeScript Version:**  2.9.1-insiders.20180525 (playground), 3.0.0-rc

**Search Terms:**

property type guards, undefined checks

**Code**

```ts
function myFunction(params: {
    a: Date,
    b?: Date
}) {
    if (params.b) {
        myFunctionInternal(params)
    }
}

function myFunctionInternal(params: {
    a: Date,
    b: Date
}) {}
```

**Expected behavior:**

should compile

**Actual behavior:**

Error: `Argument of type '{ a: Date; b?: Date | undefined; }' is not assignable to parameter of type '{ a: Date; b: Date; }'.`

**Playground Link:** 

[click me](https://www.typescriptlang.org/play/index.html#src=function%20myFunction(params%3A%20%7B%0D%0A%20%20%20%20a%3A%20Date%2C%0D%0A%20%20%20%20b%3F%3A%20Date%0D%0A%7D)%20%7B%0D%0A%20%20%20%20if%20(params.b)%20%7B%0D%0A%20%20%20%20%20%20%20%20myFunctionInternal(params)%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Afunction%20myFunctionInternal(params%3A%20%7B%0D%0A%20%20%20%20a%3A%20Date%2C%0D%0A%20%20%20%20b%3A%20Date%0D%0A%7D)%20%7B%0D%0A%0D%0A%7D)

**Comment by mhegazy** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/25631 and https://github.com/Microsoft/TypeScript/issues/18758
