### ISSUE TITLE
Question: Lookup external module names

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#2593]
I already provide a decent experience for relative paths https://github.com/TypeStrong/atom-typescript#relative-paths 

Want to expand it to also list the available external module declarations. But struggling to find the different between these two types: 

```ts
declare module foo{
}
```
vs
```
declare module 'foo'{
}
```
Is there some LS API I could use to just get `'foo'` and not `foo`? 

Note: I have access to `program` so if its not possible using LS feel free to guide me a bit toward the `program` based solution :rose: 

refs :https://github.com/TypeStrong/atom-typescript/issues/230

**Comment by basarat** [comment]
What I've look at : they both seem to be `SyntaxKind.ModuleDeclaration`

**Comment by mhegazy** [comment]
yes. the external module have a name that is SyntaxKind.StringLiteral. so the check would be 
1. in Ambient context
2. name of the module is stringLiteral

I had a PR (#2173) that did external module name completions, this might be helpful.

**Comment by basarat** [comment]
PR helped a lot. Thanks :heart: 

```ts
export function getExternalModuleNames(program: Program): string[] {
    var entries: string[] = [];

    program.getSourceFiles().forEach(sourceFile => {

        // Look for ambient external module declarations
        forEachChild(sourceFile, child => {
            if (child.kind === SyntaxKind.ModuleDeclaration && (<ModuleDeclaration>child).name.kind === SyntaxKind.StringLiteral) {
                entries.push((<ModuleDeclaration>child).name.text);
            }
        });
    });

    return entries;
}
```
