### ISSUE TITLE
Go-to-type is not useful for function

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#25933]
**TypeScript Version:**  3.1.0-dev.20180725

**Search Terms:**

**Code**

```ts
interface I { x: number; }
function f(): I { return { x: 0 }; }

f();
```

Go-to-type on `f()`.

**Expected behavior:**

Takes me to `I`.

**Actual behavior:**

Takes me to `f` -- same as go-to-definition.

Contrast with this Kotlin code:

```kt
class C(val x: Int)

fun f() = C(0)

fun main() {
    f()
}
```

where go-to-declaration on `f()` takes me to the definition, but go-to-type takes me to `C`.

**Comment by mhegazy** [comment]
With this proposal function expressions and arrow functions that have a contextual type will have ambiguous behavior, should they go to the contextual type or the return type.

**Comment by andy-ms** [comment]
Presume you're talking about the following case -- then I think we should go to `T` and not `I`. (Since one can easily get to `I` from `T` but not the other way around.)
```ts
interface I { x: number; }
type T = (i: I) => I;
const f: T = i => ({ x: i.x + 1 });
f({ x: 0 });
```
