### ISSUE TITLE
Refactor to convert variable to destructuring

### ISSUE THREAD

**Issue by andy-ms** [microsoft/TypeScript#25946]
**TypeScript Version:**  3.1.0-dev.20180721

**Code**

```ts
function f() { return { x: 0, y: 1, z: 2 }; }
const p = f();
p.x;
p.y;
p.z;
```

**Expected behavior:**

After:
```ts
function f() { return { x: 0, y: 1, z: 2 }; }
const { x, y, z } = f();
x;
y;
z;
```

Note: I think it should generate `{ x, y, z }` even if they're not all currently used (meaning, it should use every property declared in the return type of `f`). That way it's useful to perform this refactor immediately after writing the call to `f()`, before the result has been used.

**Actual behavior:**

No such refactor.

**Comment by DanielRosenwasser** [comment]
You probably want to be a little more careful here due to aliasing and assignment to `p.x`, `p.y`, or `p.z`.

**Comment by andy-ms** [comment]
If there's an assignment, we should probably not do the refactor -- `let { x } = o; x = 2;` does *not* mutate `o` as some might expect.

**Comment by RyanCavanaugh** [comment]
Declining due to low volume of feedback

**Comment by OliverJAsh** [comment]
The [Abracadabra extension](https://github.com/nicoespeon/abracadabra) has tried to provide this refactoring [but they've struggled to do it performantly](https://github.com/nicoespeon/abracadabra/issues/416)—so I think there is definitely an appetite for this refactoring.
