### ISSUE TITLE
Do we need a --jsx flag set when --noEmit is on?

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#25941]
From https://twitter.com/drosenwasser/status/1022241336009715712

When using some sort of JSX syntax on a new project, we often get an error like

```
Cannot use JSX unless the '--jsx' flag is provided.
```

However, do we need this set in projects that have `noEmit` set? Given that some users will be interested in Babel

# Pros

* Marginally simpler setup for Babel users.

# Cons

* Makes it marginally harder to move off of Babel if desired.

**Comment by mhegazy** [comment]
The main issue for `--jsx` in general is module resolution. we use `--jsx` as a queue to look for `.tsx` and `.jsx` files. if we are ok with that, then we could just make it on all the time, and default to `"React"`. the experience will be better this way for both JS and TS users.

**Comment by RyanCavanaugh** [comment]
The default is now `preserve` so this is moot
