### ISSUE TITLE
Weird type resolution from this['state'] -or- How to properly override library's type definition

### ISSUE THREAD

**Issue by ackvf** [Microsoft/TypeScript#25967]
**TypeScript Version:**  3.1.0-dev.20180726

**Description:**
After a rejected pull-request to DefinitelyTyped [[react] Update type inference for setState #25055](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/25055) for `setState` inference from `this['state']` rather than from the `S` generic in `Component<P, S>,
I kept using a modified version of the definition file locally. It was satisfying, but recently, when I updated my project dependencies and my changes were reverted, I started using a module augmentation instead. Now while attempting to create a simplified demo of the _weird type resolution from this['state']_, I realised that the augmentation is not as perfect as my previous solution and _may_ be the source of this.

> Question 1: Is there something wrong in the findings below?
> repro [here](https://github.com/ackvf/typescript-repro/tree/type-augmentation)

> Question 2: How to properly **override** the original `setState` signature and only use the one I provided?

**Code**

```ts
class App extends React.Component {
  public state: {
    num: number
    records: {}
  } = {
    num: 0,
    records: {},
  }

  public mergeIntoState = () => {
    const _records = {} // tslint:disable-line:variable-name

    ;['a', 'b', 'c'].forEach(el => {
      _records[el] = {}
    })


    // issue 1

    this.setState(({num}) => ({num: num + 1})) // var num: this['state']['num']
    this.setState(({num}) => ({num: num + ''})) // var num: any
    //            ({any})  => ({string: any + string})

    
    // issue 2

    this.setState(({records}) => ({records: {..._records, ...records}})) // Spread types may only be created from object types.
    this.setState(({records}) => ({records: {..._records, ...(records as this['state']['records'])}})) // Spread types may only be created from object types.
    //            ({any})     => ({any:     {...{},       ...(any     as  (property) records: {} )}})
    this.setState(({records}) => ({records: {..._records, ...(records as {})}})) // this is ok
    //            ({this["state"]["records"]})
  }

  public render() {
    return null
  }
}

export default App


// for simplicity, a significantly reduced signature
declare module 'React' {
  interface Component { // tslint:disable-line:interface-name
    setState<K extends keyof T, T = this['state']>(
        state: (
          (prevState: Readonly<T>) => (Pick<T, K> | T | null)
        )
    ): void
  }
}
```

**Actual behavior:**
Type inference for `num` of type `any` instead of `number`.
Type inference for `records` of type `any` instead of `this['state']['records']` == `{}`.
Error `Spread types may only be created from object types.` on `records`.

Casting `records as this['state']['records']` seemingly not working even though `this['state']['records']` seems to be resolved properly for some other occurrences of `records`. _(In the image below, type is correctly `records: {}`, but the error remains.)_
![image](https://user-images.githubusercontent.com/2313018/43263226-ee8576d0-90e2-11e8-931d-b4c6c2d2e493.png)

In the animation below:
1. type is `this["state"]["num"]`
2. modify the key
3. type is `any`
![prop-type-changes](https://user-images.githubusercontent.com/2313018/43262459-798bc4bc-90e0-11e8-8f6d-71c3892397c4.png)

**Expected behavior:**
Type of `num` is `number`.
Type of `records` is properly an object that can be spread.
Casting to `this['state']['records']` works the same way as to `{}`
Type information is not lost after a change. _(the animation above)_

**Playground Link:** 

https://github.com/ackvf/typescript-repro/tree/type-augmentation

**Related Issues:**

**Comment by mhegazy** [comment]
This is not really about module augmentation. this is about overload resolution.. All what augmentation does is it adds an additional overload at the top of the list. in the first case where your handler returned a number, the first overload of `setState` was picked (the one you provided), in the second case, that overload failed to resolve, so the compiler proceeded to the other one where it `this["state"]` is `{}` from the default parameter to `React.Component`. this one passes and lets you assign `{num: string}` to `{}` at it should.

So you either need to have just one overload for `setState` (i.e. fork the react declaration file and modify ti locally, then add a path-mapping to it), or pass in your `State` in the `extends` clause:

```ts
class App extends React.Component<{}, App["state"]> { 
..
}
```

As for the other errors, that is tracked by https://github.com/Microsoft/TypeScript/issues/10727.
