### ISSUE TITLE
Weird behavior when together use type alias and extends

### ISSUE THREAD

**Issue by galenjiang** [microsoft/TypeScript#25960]
code:
```
type T = "a" | "b" | "c" | "x"
type U = "x" | "y" | "z" | "a"

type a = T extends U ? never : T;  //type a = "a" | "b" | "c" | "x"

type b = Exclude<T, U>              // type b = "b" | "c"
```
question:

Exclude is defined by < T extends U ? never : T>

type a: T and U act like a whole type
type b: T ,U took in to type Exclude, the behavior was changed, T treated like using the operator "in" to spread T, U just like a whole type

Is there any document or achieve to describe this.

forgive my poor English.

**Comment by AlCalzone** [comment]
I didn't understand at first and tried it myself on the playground:
```ts
type T = "a" | "b" | "c" | "x"
type U = "x" | "y" | "z" | "a"

type Ext<R> = R extends U ? never : R;
type T1 = Ext<T>; // "b" | "c"
type T2 = T extends U ? never : T; // "a" | "b" | "c" | "x"
```
Although `T1` and `T2` seem to describe the same type, they don't.

**Comment by mattmccutchen** [comment]
You've discovered [distributive conditional types](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html#distributive-conditional-types).  I agree that the difference in behavior when a type alias is inlined is weird (ideally there would have been a dedicated syntax to mark distributive conditional types), but it's intended.

**Comment by AlCalzone** [comment]
So basically `T1` is equal to
```ts
Ext<"a"> | Ext<"b"> | Ext<"c"> | Ext<"x">
=> ("a" extends U ? never : "a") | ... | ("x" extends U ? never : "x")
=> "b" | "c"
```
but `T2` is equal to
```ts
("a" | "b" | "c" | "x") extends U ? never : ("a" | "b" | "c" | "x") 
=> "a" | "b" | "c" | "x"
```
because the latter does not go through a generic type alias?

To be fair, the relevant part in the docs could be clearer regarding this distinction. In general that part its very hard to understand and could almost be written in chinese :rofl:

**Comment by winhillsen** [comment]
> ideally there would have been a dedicated syntax to mark distributive conditional types

@mattmccutchen would I be reading this correctly to imply that putting a generic with union parameter inside a condition currently _forces_ the union to distribute over the generic? Does there happen to be a plan allowing for us to opt-out of this behavior?

**Comment by mattmccutchen** [comment]
> would I be reading this correctly to imply that putting a generic with union parameter inside a condition currently forces the union to distribute over the generic?

Yes.

> Does there happen to be a plan allowing for us to opt-out of this behavior?

Wrap the type parameter and the test type in a tuple type:
```ts
type Weird<T> = [T] extends [string] 
    ? WithString<T> 
    : T;
```
I think I've seen this documented somewhere, but I can't find it now.  Anyway, it belongs in the handbook entry for conditional types.

**Comment by AlCalzone** [comment]
> Wrap the type parameter and the test type in a tuple type

Oh, wow... Yeah that definitely belongs in the docs!

**Comment by mc-petry** [comment]
Same weird [behavior](https://www.typescriptlang.org/play/#src=type%20Factory<T%20%3D%20undefined>%20%3D%20T%20extends%20undefined%0D%0A%20%20%3F%20()%20%3D>%20void%0D%0A%20%20%3A%20(value%3A%20T)%20%3D>%20void%0D%0A%0D%0Alet%20withArgsSimple%3A%20Factory<%7B%20data%3A%20string%20%7D>%0D%0Alet%20withArgsComplex%3A%20Factory<%7B%20data%3A%20string%20%7D%20%7C%20%7B%20value%3A%20string%20%7D>%0D%0A%0D%0AwithArgsSimple(%7B%20data%3A%20""%20%7D)%0D%0AwithArgsComplex(%7B%20data%3A%20""%20%7D)):

```ts
type Factory<T = undefined> = T extends undefined
  ? () => void
  : (value: T) => void

let withArgsSimple: Factory<{ data: string }>
let withArgsComplex: Factory<{ data: string } | { value: string }>

withArgsSimple({ data: "" }) // Ok
withArgsComplex({ data: "" }) // Error
```
