### ISSUE TITLE
function type inference doesn't work reliably with generic function wrappers

### ISSUE THREAD

**Issue by helios1138** [Microsoft/TypeScript#25972]
```js
// correctly inferred as (arg: number) => number
const func = (arg: number) => arg * 2

const wrap = <T>(fn: T): T => fn

// correctly inferred as (arg: number) => number
const funcWrappedImplicitType = wrap<typeof func>(func)

// incorrectly inferred as (arg: number) => any
const funcWrapped = wrap(func)
```

I would expect that `funcWrapped` either would not be inferred at all or to be inferred fully. Currently it's kinda inferred half-way.

**Comment by mhegazy** [comment]
This is not what is see on the [playground](http://www.typescriptlang.org/play/index.html#src=%2F%2F%20correctly%20inferred%20as%20(arg%3A%20number)%20%3D%3E%20number%0Aconst%20func%20%3D%20(arg%3A%20number)%20%3D%3E%20arg%20*%202%0A%0Aconst%20wrap%20%3D%20%3CT%3E(fn%3A%20T)%3A%20T%20%3D%3E%20fn%0A%0A%2F%2F%20correctly%20inferred%20as%20(arg%3A%20number)%20%3D%3E%20number%0Aconst%20funcWrappedImplicitType%20%3D%20wrap%3Ctypeof%20func%3E(func)%0A%0A%2F%2F%20incorrectly%20inferred%20as%20(arg%3A%20number)%20%3D%3E%20any%0Aconst%20funcWrapped%20%3D%20wrap(func)). something else is going on, can you share more context.

**Comment by helios1138** [comment]
@mhegazy you are right, it appears that this is not a typescript issue
