### ISSUE TITLE
import is typed and triggers an error even with all typings disabled

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#25986]
_From @Janne252 on July 26, 2018 12:32_

 

- VSCode Version: 1.25.1
- OS Version: Windows 10 Pro 64-bit

Steps to Reproduce:

1. Create an empty directory and open it in VS Code
2. Create `tsconfig.json` with the following content:
```js
{
    "compilerOptions": {
        "noLib": true,
        "types": [],
        "typeRoots": []
    },
    "include": [
        "./**/*.ts"
    ],
}
```
3. Create a new TypeScript file with the following content:
```typescript
import();
```
4. Note how the `import();` statement refers to dynamic import (unexpected behavior).  Type in `require();` and see how it results in "Cannot find name 'require'" (expected behavior)
![image](https://user-images.githubusercontent.com/4705573/43262092-9e401766-90e7-11e8-86aa-50d48403315b.png)

If you use `//@ts-ignore`, an error will be reported about the missing Promise type:
![image](https://user-images.githubusercontent.com/4705573/43262337-7355fbdc-90e8-11e8-9225-06563f6a6e24.png)

### Workaround
If you use `//@ts-ignore` AND declare a type for the Promise, the error disappears (VS Code forces Promise to have at least one type parameter, which sounds like import & Promise typing requirements are hardcoded)
![image](https://user-images.githubusercontent.com/4705573/43262428-c140ed48-90e8-11e8-8a56-a1f8a7505dfe.png)

Even with the declared type for Promise `//@ts-ignore` is still required, otherwise VS Code checks if the module exists:
![image](https://user-images.githubusercontent.com/4705573/43262501-fc19cae8-90e8-11e8-8b42-0d759824390c.png)

Does this issue occur when all extensions are disabled?: Yes

_Copied from original issue: Microsoft/vscode#55142_

**Comment by mjbvz** [comment]
This is the expected behavior since `import()` is an [import expression](https://blog.mariusschulz.com/2018/01/14/typescript-2-4-dynamic-import-expressions). Did you mean to write `import 'foo'`?

**Comment by Janne252** [comment]
Does this mean it's not possible to create a TypeScript environment using `tsconfig.json` that doesn't have `import` statement "available"/checked/typed? 

My current usecase is rather obscure and relies on another transpiler: [TypeScriptToLua](https://github.com/Perryvw/TypescriptToLua). I'm using it to transpile TypeScript into lua that is then consumed as a scripting language for a game, that happens to use `import()` as its script loading function. It obviously conflicts with TypeScript's `import()`.

For that reason I'm looking for a way of using `tsconfig.json` to disable the type checking of `import()` but it appears that it's a core part of TypeScript and "always there"?

**Comment by kitsonk** [comment]
TypeScript is JavaScript, JavaScript/ECMAScript has reserved the keyword `import` since [JavaScript 1.0](https://www.ecma-international.org/publications/files/ECMA-ST-ARCH/ECMA-262,%201st%20edition,%20June%201997.pdf), so no, it is invalid to use `import` for anything else.  That is essentially like trying to redefine `function` to mean something else.

**Comment by Janne252** [comment]
@kitsonk Thanks for clearing that up!
