### ISSUE TITLE
Importing `import React, { Component } from 'react'` gives runtime warning

### ISSUE THREAD

**Issue by ibezkrovnyi** [Microsoft/TypeScript#25985]
**TypeScript Version:**
* 2.9.2
* 3.1.0-dev.20180726:

**Search Terms:**
React.PropTypes, Warning: Accessing PropTypes

**Code:**
tsconfig.json
```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true
  }
}
```
index.ts
```ts
import React, { Component } from 'react';
console.log(React as any, Component as any);
```

**Expected behavior:**
```ts
"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
var react_1 = require("react");
var react_1_default = __importDefault(react_1);
console.log(react_1_default.default, react_1.Component);
```

**Actual behavior:**
```ts
"use strict";
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (Object.hasOwnProperty.call(mod, k)) result[k] = mod[k];
    result["default"] = mod;
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
var react_1 = __importStar(require("react"));
console.log(react_1.default, react_1.Component);
```

Which gives following message in console
`Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs`

It is React.PropTypes deprecation message in getter.

Unfortunately we cannot upgrade to React 16 and not all scripts can be updated to allow warnings in tests (which itself is not a good idea).

> before posting this issue I used google.com and github's TypeScript/issues and TypeScipt/search. 

**Playground Link:**
https://agentcooper.github.io/typescript-play/?esModuleInterop=true&target=1#code/JYWwDg9gTgLgBAJQKYEMDGMA0cDecDCE4EAdkifAL5wBmURcA5FKhowNwBQapAzhABskAOgEQA5gApk6eCl5wUJAJ7ZCxMhUUKlygJTsgA

**Related Issues:**
The only similar problem I found is for Flow: https://github.com/facebook/flow/issues/4673

**Comment by ibezkrovnyi** [comment]
While in the following cases TypeScript there is no deprecation warning:

#### import React from 'react'
```ts
"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
var react_1 = __importDefault(require("react"));
console.log(react_1.default, react_1.default.Component);
```

#### import { Component } from 'react';
```ts
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var react_1 = require("react");
console.log(react_1.Component);
```

**Comment by weswigham** [comment]
Similar to https://github.com/babel/babel/issues/5705 , "fixing" this requires copying setters and getters without invoking them in the helper.

**Comment by ibezkrovnyi** [comment]
#### __importStar implementation:
* in [TypeScript/blob/master/src/compiler/transformers/module/module.ts](https://github.com/Microsoft/TypeScript/blob/d590d5bd0c4eeb034e18f31fb8683e295dd6666f/src/compiler/transformers/module/module.ts#L1810)
* in [tslib/tslib.js](https://github.com/Microsoft/tslib/blob/9dd9aa322c893e5e0b3f1609b1126314ccf37bbb/tslib.js#L215)

So, I assume it should be fixed in the same way as it was implemented [here](https://github.com/babel/babel/pull/6850/files), but taking into account `target: es3` compiler option.

If yes - do you accept PRs on this issue?
