### ISSUE TITLE
Index type should work with properties that are not always defined

### ISSUE THREAD

**Issue by MastroLindus** [microsoft/TypeScript#25997]
**TypeScript Version:**  3.1.0-dev.20180726

```ts
const test = {"prop1": {alwaysDefined: 1, notAlwaysDefined: 2}, "prop2": {alwaysDefined: 3}};
type Test = typeof test;
type Keys = keyof Test;
type IndexType<T extends Keys> = Test[T]["alwaysDefined"]; // allowed
type IndexType<T extends Keys> = Test[T]["notAlwaysDefined"]; // not allowed
```

**Expected behavior:**
The second type using notAlwaysDefined is allowed, and is resolved to number | undefined
**Actual behavior:**
You get an error on the type declared with notAlwaysDefined.

However you don't get an error if you specify notAlwaysDefined: undefined for prop2, and the type is correctly inferred. But if you have a lot of properties where only a few have notAlwaysDefined present, it is a cumbersome workaround to manually specify it explicitely as undefined everywhere.

**Comment by mhegazy** [comment]
```ts
type IndexType<T extends Keys> = Test[T] extends { notAlwaysDefined: infer U } ? U : never; 
```

**Comment by MastroLindus** [comment]
The fact that the type is expressible with conditional types is a good thing, however I would argue that the index operator should still behave as described in my first post.
