### ISSUE TITLE
proposal-object-from-entries

### ISSUE THREAD

**Issue by Kingwl** [Microsoft/TypeScript#25999]
## Search Terms
esnext, proposal, stage-3

## Suggestion
https://github.com/tc39/proposal-object-from-entries#proposal

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by mhegazy** [comment]
PRs welcomed.

**Comment by ljharb** [comment]
This proposal is now stage 4, in ES2019.
