### ISSUE TITLE
Debugging in a Windows 8 Store app?

### ISSUE THREAD

**Issue by chrisaswain** [Microsoft/TypeScript#2600]
Is it possible to debug (set breakpoints, step, etc.) in a Visual Studio 2012 Windows 8 Store app using TypeScript?  I can't get VS to recognize the breakpoints I set in my TypeScript files so I can't debug.

**Comment by mhegazy** [comment]
It should be possible. it is possible that you are running into bugs as well. We have not looked at VS2012 in over a year now.

**Comment by mhegazy** [comment]
closing this issue for now, please reopen if there further details needed.
