### ISSUE TITLE
Ubuntu - File to import not found or unreadable

### ISSUE THREAD

**Issue by paulbrittain** [microsoft/TypeScript#26009]
Hello all,

I've been working to figure out a solution to my Typescript problem on-and-off for a couple of weeks. I have tried all stackoverflow and forum answers I could find but my Typescript has difficulty traversing the source files linking imports.
```
TS2307: Cannot find module '../../rendering/components/..until file in question'.

Module build failed:
@import "./resizedImagePreview/resizedImagePreview.scss";
^
File to import not found or unreadable:
```

Error like the one above are many. I've tried multiple Typescript versions, types versions, and specified the ModuleResolution strategy in the tsconfig.json file. This project compiles fine on Windows 10.

This is an error on the following Ubuntu:

Description: Ubuntu 18.04 LTS
Release: 18.04
Codename: bionic

**Comment by andy-ms** [comment]
That doesn't look like a TypeScript error message, are you sure this isn't coming from some other part of your build system? `@import` isn't TypeScript syntax either.

**Comment by paulbrittain** [comment]
@andy-ms error TS2307: Cannot find module '../../rendering/components/..*until file in question*'.

**Comment by andy-ms** [comment]
@paulbrittain Was the error in a `.ts` file? Could you post a complete example that reproduces the error?

**Comment by paulbrittain** [comment]
@andy-ms It's a .tx file, an they're interfaces that are being imported by a .ts file. I'm not sure I can post a complete example.. I can try

**Comment by mhegazy** [comment]
You might have better luck sharing this on StackOverflow. This is not a support forum, it is one for reporting compiler/language bugs and suggestions. 
If you believe you are running into a compiler bug, please share a minimal repro project that demonstrates the issue you are running into and why you believe this is a compiler bug and not a declaration file issue or library usage problem.

**Comment by paulbrittain** [comment]
It's clear to me that it's a Typescript module resolution issue with Ubuntu 18.04 so you can treat this as a bug report. As for a minimal repro project I can try if I have time but irregardless the issue is there. Thanks

**Comment by RyanCavanaugh** [comment]
Doesn't seem like anyone else ran into this
