### ISSUE TITLE
resolveJsonModule with `--module es2015`

### ISSUE THREAD

**Issue by domoritz** [Microsoft/TypeScript#26020]
## Related Issues

#25755, #24588

## Examples

I'm using Typescript with rollup with https://github.com/rollup/rollup-plugin-json and with TS 2.9 everything worked fine. TS 3 disables JSON modules with everything other than commonjs modules. Could this be changed for es2015 modules?

**Comment by mhegazy** [comment]
Looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/25755

**Comment by domoritz** [comment]
I filed a separate issue (and linked to the original one) since the other issue talks about amd.

**Comment by ZSkycat** [comment]
`--module esnext`
I use webpack and I also have this requirement.
This change is too strange.

**Comment by kitsonk** [comment]
@gamedevsam the workaround would be to target CommonJS in the `tsconfig.json` but whatever your build pipeline/bundler is that handles JSON, to ensure that it emits the TypeScript in the module format you prefer.

**Comment by domoritz** [comment]
This is fixed in master.
