### ISSUE TITLE
Update imports on file move rewrites `./index` to '.'

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#26028]
From https://github.com/Microsoft/vscode/issues/54981#issuecomment-408448682

**TypeScript Version:**  3.1.0-dev.20180726

**Search Terms:**
- update imports 
- getEditsForFileRename

**Code**
For a project

`index.ts`
```ts
export const foo = 123
```

`foo.ts`
```ts
import { foo } from './index';
```

1. In VScode, Rename `foo.ts` to `bar.ts`
1. Confirm that you want to update import paths

**Expected behavior:**
No edits returned from `getEditsForFileRename`

**Actual behavior:**
An edit is returned that rewrites `foo.ts` to:

```ts
import { foo } from '.';
```

**Comment by andy-ms** [comment]
We could add this as a new `UserPreferences` property: `readonly importIndexPreference: "omitIndex" | "includeIndex";`.

**Comment by mhegazy** [comment]
What should the default be?

**Comment by mjbvz** [comment]
My expectation as a user is that we don't touch the import in this case. If it's `'./index'` leave it as `'./index'` and if its `'.'` leave it as `'.'`

**Comment by jdforsythe** [comment]
@andy-ms @mhegazy I think it should be: `readonly importIndexPreference: "omitIndex" | "includeIndex" | "noChange";`

where "noChange" is the default. Then users could *opt in* to always or never include index, but the default is to not change existing imports.
