### ISSUE TITLE
Intermediate newlines+asterisks prevent `@param` from applying

### ISSUE THREAD

**Issue by sandersn** [Microsoft/TypeScript#26027]
```js
/** @param 
 * {string} x
 * @param {number}
 * y
 */
function f(x,y) {
}
```

**Expected behavior:**
`x: string` and `y: number`

**Actual behavior:**
`x: any` and `y: any`.

Note that if you remove the asterisks but not the lines, it works as expected.

```js
/** @param 
  {string} x
 * @param {number}
  y
 */
function f(x,y) {
}
```

**Comment by tschaub** [comment]
@sandersn I put up an initial stab at this in #26067.   Let me know if someone else is already tackling this (or you'd like to handle it differently).
