### ISSUE TITLE
Equal type generates wrong import for *.d.ts

### ISSUE THREAD

**Issue by Jefiozie** [Microsoft/TypeScript#26039]
**TypeScript Version:**  2.4.2
When using two the same type(s) in different namespaces the resolving of the path is not correct.
To see te example I have made a repo so you can look at the code: [example repo](
https://github.com/Jefiozie/enum-problem)

The types are present in  [addAdministrationItemCommand.ts](https://github.com/Jefiozie/enum-problem/blob/e3e9c01beb3139e8ba7eb84963a20b9d24178fb5/model/addAdministrationItemCommand.ts#L21) and [changeAdministrationItemCommand.ts](https://github.com/Jefiozie/enum-problem/blob/e3e9c01beb3139e8ba7eb84963a20b9d24178fb5/model/changeAdministrationItemCommand.ts#L21)

The problem can bee seen [here](https://github.com/Jefiozie/enum-problem/blob/e3e9c01beb3139e8ba7eb84963a20b9d24178fb5/dist/model/changeAdministrationItemCommand.d.ts#L22)

`typescript@next` didn't help
 
Repo is avaliable for reproduction. 

Thanks!

**Comment by mhegazy** [comment]
The output seems right to me. what specifically about the `.d.ts` that you do not want to see?

**Comment by Jefiozie** [comment]
The path is to 'model/addAdministrationItemCommand' but it is already in the folder 'model'. That is not what I expected. It should be to the 'addAdministrationItemCommand'.

**Comment by Jefiozie** [comment]
Do I need to specify a baseurl? To resolve this? 

I still cant figure out why this is happening.

**Comment by mhegazy** [comment]
if you do not want it absolute then specify `baseUrl`, if you want it to be relative, then do not.

**Comment by Jefiozie** [comment]
Can you explain what you need from me to get this issue solved? Do you need a result of what I'm expecting? 

Thanks

**Comment by RyanCavanaugh** [comment]
@Jefiozie how were those .d.ts files generated? I don't see a tsconfig.json in that repo

**Comment by Jefiozie** [comment]
Hi @RyanCavanaugh, this is because we use the default tsconfig provided by ng-packgr. I believe this is the one that is being used [tsconfig](https://github.com/dherges/ng-packagr/blob/master/src/lib/ts/conf/tsconfig.ngc.json).

**Comment by Jefiozie** [comment]
@RyanCavanaugh do you want me to add a custom one to test stuff? If so just let me know I will update the repo.

**Comment by RyanCavanaugh** [comment]
@Jefiozie we can't investigate bugs that require external build tools. If you can provide a standalone repro, we can take a look

**Comment by Jefiozie** [comment]
Hi @RyanCavanaugh after your comment I had a look at the typescript version that was installed in the `node_modules` folder. For some reason (I still can't figure out why) was `next: 3.1.0-dev.20180808` installed.

After changing this to the correct one `^2.4.2`  everything was correct again. 

Thanks for the help; closing this issue as it is local problem.
