### ISSUE TITLE
tsc does not recognize a second overload of the API call

### ISSUE THREAD

**Issue by jeffsaremi** [Microsoft/TypeScript#26035]
```
vscode: 1.25.1
tsc: 2.9.2
```

I have a call like this in my code:
```
    gl.texImage2D(gl.TEXTURE_2D,
      0,             // Level of detail.
      this.format.internalFormat,
      width,
      height,
      0,             // Always 0 in OpenGL ES.
      this.format.format,
      this.format.datatype,
      null);
```

This call is erroring out saying that `“Expected 6 arguments. Got 9”`
If I press F12 on the function it takes me to libdom.t.ts:

```
texImage2D(target: number, level: number, internalformat: number, width: number, height: number, border: number, format: number, type: number, pixels: ArrayBufferView | null): void;
texImage2D(target: number, level: number, internalformat: number, format: number, type: number, pixels: ImageBitmap | ImageData | HTMLVideoElement | HTMLImageElement | HTMLCanvasElement): void;

```
where 2 versions of the same function exist. But the IntelliSense and tsc do not recognize the 2nd one.
There are quite a few instances of similar calls which are also erroring out.

**Comment by DanielRosenwasser** [comment]
Can you provide a minimal repro, and have you given this a shot [with `typescript@next`](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Nightly%20Builds.md#updating-your-ide-to-use-the-nightly-builds)?

**Comment by jeffsaremi** [comment]
Thank you so much Daniel. `typescript@next` resulted in a lot of installation errors. however I got this:
```
tsc -v
Version 3.1.0-dev.20180728
```
after the install.
And my problem went away after making a change to vscode settings as suggested above!

**Comment by jeffsaremi** [comment]
I just wanted to leave a comment saying that the same file kept on compiling properly in another workspace folder on the same machine with the same version of tsc. That is definitely very weird. I went through the settings in tsconfig and package.json and I could not find anything that could have triggered this behavior.

**Comment by jeffsaremi** [comment]
I am reopening this. After I did an `"npm install -g npm`" and re-installing `typescript@next` the issue came back.
I tried to create a repro package for you. I copied the problematic file along with the `package.json` and `tsconfig.json` to another folder for prep. However when I run tsc on that folder no issues are reported at all.
Going back to my original folder and running `tsc` I still get:

```
lib/backends/webgl/gl_context.ts:98:5 - error TS2554: Expected 6 arguments, but got 9.

 98     gl.texImage2D(
        ~~~~~~~~~~~~~~
 99         gl.TEXTURE_2D,
    ~~~~~~~~~~~~~~~~~~~~~~
...
102         0,  // Always 0 in OpenGL ES.
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
103         this.format.format, this.format.datatype, null);
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

lib/backends/webgl/gl_context.ts:119:5 - error TS2554: Expected 7 arguments, but got 9.

119     gl.texSubImage2D(
        ~~~~~~~~~~~~~~~~~
120         gl.TEXTURE_2D,
    ~~~~~~~~~~~~~~~~~~~~~~
...
124         width, height, this.format.format, this.format.datatype,
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
125         buffer as ArrayBufferView);
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

**Comment by jeffsaremi** [comment]
I'm re-openning this. It never really goes away. Only for short periods of time and then i come back.

**Comment by mhegazy** [comment]
@jeffsaremi we will need a *self-contained reproduction* of the issue to be able to diagnose the issue.

**Comment by jeffsaremi** [comment]
Ok I think we can close this. The issue has already been identified (see the link below) and is caused by incompatible signature in `@types/webgl2` 

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15994/commits/5b6ca83b4ba20588ca2bddc6e8b6b425bc4da70a
