### ISSUE TITLE
auto-import prefers package import over relative path

### ISSUE THREAD

**Issue by ajafff** [Microsoft/TypeScript#26044]
This is a follow-up on #25279, because one of the cases was not fixed (or regressed since then?)

**TypeScript Version:**  3.1.0-dev.20180728

**Search Terms:**

**Code**

* clone https://github.com/fimbullinter/wotan
* `yarn`
  * creates a symlink `node_modules/@fimbul/<name>` for each `packages/<name>`
* create a new file `packages/mimir/src/test.ts`
* type `isAsyncFunction` and use auto-import from the completion list or quickfix

**Expected behavior:**

```ts
import { isAsyncFunction } from "./utils";

isAsyncFunction
```

**Actual behavior:**

```ts
import { isAsyncFunction } from "@fimbul/mimir/src/utils";

isAsyncFunction
```

**Related Issues:** 
#25279

**Comment by andy-ms** [comment]
Seems to be fixed by #25834.
