### ISSUE TITLE
Warn if an object property is not initialized

### ISSUE THREAD

**Issue by jeffsaremi** [Microsoft/TypeScript#26040]
In the absence of a default initializer for Objects I'd like to suggest the following:
Warn if some properties are not initialized after the object is created and before it is used/returned:

Example:

```
class MyClass {
  a: any;
  b: any;
}
function f(): MyClass {
  const m = new MyClass();
  m.a = "value";
  return m;  // There should be a warning or error that I have not initialized b yet
}
```

Of course a more appropriate way to initialize would be:

```
class MyClass {
  a: any;
  b: any;
}
function f(): MyClass {
  return new MyClass() {
      a:"value"
   };  // There should be a warning or error that I have not initialized b yet
}
```

**Comment by mhegazy** [comment]
First use `--strict`. Second `any` tells the compiler that `undefined` is a valid type of this value. use a more specific type like `string`.

**Comment by mhegazy** [comment]
In general such issues be better posted on StackOverflow. This is not a support forum, it is one for reporting compiler/language bugs and suggestions. 

http://www.typescriptlang.org/docs/home.html is also a good resource for learning more about TypeScript.

**Comment by jeffsaremi** [comment]
Thank you. I didn't this was already taken care of by using --strictPropertyInitialization
