### ISSUE TITLE
Type inference fails when combining union types and overloading

### ISSUE THREAD

**Issue by chibicode** [Microsoft/TypeScript#26052]
**TypeScript Version:**  3.1.0-dev.20180728

**Search Terms:** 

- "Overload signature is not compatible with function implementation"
- Union types
- Overloading
- Type inference

**Code**

Suppose we have the following types:

```ts
interface FruitContainer {
  fruit: AppleOrOrange
}

interface Apple {
  appleName: string
}

interface Orange {
  orangeName: string
}

type AppleOrOrange = Apple | Orange
```

The following code works without any problem:

```ts
function foo(x: string): FruitContainer {
  return {
    fruit: {
      appleName: x
    }
  }
}
```

However, if you run this code - basically the same thing as `foo` but does function overloading:

```ts
function bar(x: string): FruitContainer
function bar(x: any) {
  if (typeof x === 'string') {
    return {
      fruit: {
        appleName: x
      }
    }
  }
  return false
}
```

- **Expected behavior:** Code compiles fine without any errors
- **Actual behavior:** Error: "Overload signature is not compatible with function implementation." on `bar`

**Workarounds**

This is strange, because if you change `FruitContainer` to

```ts
interface FruitContainer {
  value: Apple /* Instead of AppleOrOrange */
}
```

Then it won't be a problem.

Or, if you change the last return to

```ts
return null /* Instead of false */
```

Then it won't be a problem.

Or, if you use type assertion:

```ts
return {
  fruit: {
    appleName: x
  }
} as FruitContainer
```

Then it won't be a problem. But why is this necessary, when it was not necessary when there was no overloading?

**Playground Link:** [Link](https://www.typescriptlang.org/play/#src=interface%20FruitContainer%20%7B%0D%0A%20%20fruit%3A%20AppleOrOrange%0D%0A%7D%0D%0A%0D%0Ainterface%20Apple%20%7B%0D%0A%20%20appleName%3A%20string%0D%0A%7D%0D%0A%0D%0Ainterface%20Orange%20%7B%0D%0A%20%20orangeName%3A%20string%0D%0A%7D%0D%0A%0D%0Atype%20AppleOrOrange%20%3D%20Apple%20%7C%20Orange%0D%0A%0D%0Afunction%20foo(x%3A%20string)%3A%20FruitContainer%20%7B%0D%0A%20%20return%20%7B%0D%0A%20%20%20%20fruit%3A%20%7B%0D%0A%20%20%20%20%20%20appleName%3A%20x%0D%0A%20%20%20%20%7D%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Afunction%20bar(x%3A%20string)%3A%20FruitContainer%0D%0Afunction%20bar(x%3A%20any)%20%7B%0D%0A%20%20if%20(typeof%20x%20%3D%3D%3D%20'string')%20%7B%0D%0A%20%20%20%20return%20%7B%0D%0A%20%20%20%20%20%20fruit%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20appleName%3A%20x%0D%0A%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%7D%0D%0A%20%20%7D%0D%0A%20%20return%20false%0D%0A%7D%0D%0A)

**Related Issues:** Couldn't find any

**Comment by DanielRosenwasser** [comment]
Overloads (unsafely) have their return types compared bidirectionally with the implementation because otherwise you'd almost always have to use `any` for the implementation.

You're effectively trying to relate `Container<Apple> | false` to `Container<Apple | Orange>`, but neither is assignable to the other. So TypeScript is correctly erroring.

> 
> Or, if you change the last return to
> 
> ```ts
> return null /* Instead of false */
> ```
> 
> Then it won't be a problem. Not sure why.

Try turning on `strictNullChecks` and you'll get the right behavior.

**Comment by chibicode** [comment]
@DanielRosenwasser 

> Overloads (unsafely) have their return types compared bidirectionally with the implementation 

I didn't realize this. Thanks for the explanation and sorry for false reporting.
