### ISSUE TITLE
[docs] Which refinements carry over to new scopes?

### ISSUE THREAD

**Issue by bcherny** [Microsoft/TypeScript#26053]
`T | null | undefined` -> `T` refinements don't carry over between function scopes:

```ts
type Dialog = {
  id?: string
}

function closeDialog(dialog: Dialog) {
  if (!dialog.id) {
    return
  }
  setTimeout(() =>
    removeFromDOM(
      dialog,
      document.getElementById(dialog.id!)! // Note the assertion: dialog.id!
    )
  )
}

function removeFromDOM(dialog: Dialog, element: Element) {
  element.parentNode!.removeChild(element)
  delete dialog.id
}
```

But union case selections do carry over:

```ts
type VisibleDialog = { id: string }
type DestroyedDialog = {}

type Dialog = VisibleDialog | DestroyedDialog

function closeDialog(dialog: Dialog) {
  if (!('id' in dialog)) {
    return
  }
  setTimeout(() =>
    removeFromDOM(
      dialog,
      document.getElementById(dialog.id)! // Note no assertion: dialog.id
    )
  )
}
```

Why is that? What's the guiding principle here - is it that nullability refinements aren't preserved between function scopes, but all other refinements are?

**Comment by kitsonk** [comment]
This is all part of #9998.

In the first one, it is impossible for TypeScript to determine outside of the scope of the function, if there will be mutations to `dialog` that might change the value of `.id`, therefore it is reset within the scope of the enclosing function.

For the second one, TypeScript can statically determine that no code can change the value of `dialog`.  Even if some variable reassignment happens outside of the scope of `closeDialog` it will not impact the reference of `dialog` inside the scope of its function or unclosing functions, so it can be positive that the type narrowing is valid within the scope of the enclosed function.

**Comment by bcherny** [comment]
@kitsonk Thanks for the response! So in (2), after the `if (!('id' in dialog))` refinement, TS knows that `dialog` must be a `VisibleDialog`, and if something deleted its `id`, that would be a type error.

**Comment by kitsonk** [comment]
> TS knows that dialog must be a `VisibleDialog`

Correct and it knows that no one is performing a re-assignment to `dialog`, so it can _trust_ that narrowing will always be valid within the scope of the function in (2).  TS _always_ assumes that mutations on values will be type safe, so in this particular instance it isn't specifically considering it.

If you reassign `dialog` at any point, you can see that TypeScript will [reset the narrowed type](https://www.typescriptlang.org/play/#src=declare%20const%20removeFromDOM%3A%20any%3B%0D%0A%0D%0Atype%20VisibleDialog%20%3D%20%7B%20id%3A%20string%20%7D%0D%0Atype%20DestroyedDialog%20%3D%20%7B%7D%0D%0A%0D%0Atype%20Dialog%20%3D%20VisibleDialog%20%7C%20DestroyedDialog%0D%0A%0D%0Afunction%20closeDialog(dialog%3A%20Dialog)%20%7B%0D%0A%20%20%20%20if%20(!('id'%20in%20dialog))%20%7B%0D%0A%20%20%20%20%20%20%20%20return%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20setTimeout(()%20%3D%3E%0D%0A%20%20%20%20%20%20%20%20removeFromDOM(%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20dialog%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20document.getElementById(dialog.id)!%20%2F%2F%20Note%20no%20assertion%3A%20dialog.id%0D%0A%20%20%20%20%20%20%20%20)%0D%0A%20%20%20%20)%0D%0A%20%20%20%20dialog%20%3D%20%7B%7D%3B%0D%0A%7D%0D%0A):

```ts
declare const removeFromDOM: any;

type VisibleDialog = { id: string }
type DestroyedDialog = {}

type Dialog = VisibleDialog | DestroyedDialog

function closeDialog(dialog: Dialog) {
    if (!('id' in dialog)) {
        return
    }
    setTimeout(() =>
        removeFromDOM(
            dialog,
            document.getElementById(dialog.id)! // Error as `dialog` is now `Dialog`
        )
    )
    dialog = {};
}
```
