### ISSUE TITLE
Ability to raise type checking error using something like a `typeerror` type.

### ISSUE THREAD

**Issue by vilic** [Microsoft/TypeScript#26055]
## Search Terms

typeerror type, user-defined type checking

## Suggestion

Conditional type brings a useful method for composing types, but there are many scenarios that conditional type works while losing type safety. It would be nice to have a special type like `typeerror` to notify the compiler of incorrect types:

```ts
let foo: typeerror;
    ^^^ error

let bar: {yo: string; ha: typeerror};
    ^^^ error
```

## Examples

```ts
interface Foo {
  yo: string;
  ha: number;
  pia: boolean;
};

type Bar = {
  [K in keyof Foo]:
    Foo[K] extends string ? string[] :
    Foo[K] extends number ? number :
    typeerror;
};
```

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by DanielRosenwasser** [comment]
This has come up, but the biggest question is really just a matter of where and how to give the error when the type appears in an arbitrarily complex type.

**Comment by mattmccutchen** [comment]
Looks like a duplicate of #23689.

**Comment by vilic** [comment]
@mattmccutchen Thanks for referring.
