### ISSUE TITLE
[Feature request] Stricter keyword than `extends` for generics restricting excessive keys. Maybe `is`? 

### ISSUE THREAD

**Issue by joonhocho** [Microsoft/TypeScript#26051]
## Search Terms

exact, generic, strict, keyword 

## Suggestion

I wish there is a way to enforce exact shape (same keys: no excessive keys allowed) of generic type.
new keyword `is` maybe?

## Use Cases

Eliminate cases where excessive keys are supplied to generic object parameter and cause uncaught bugs.

## Examples

```typescript
const mapProperties = <
  T extends { [key: string]: any },
  U extends { [K in keyof T]: (v: T[K]) => any }
>(
  obj: T,
  mappers: U
): { [K in keyof T]: ReturnType<U[K]> } => {
  const res = {};
  Object.keys(mappers).forEach((key) => {
    res[key] = mappers[key](obj[key]);
  });
  return res;
};

// data to be transformed
const data = {
  a: 1,
  // b: 0, // used to exist but removed later
};

// in another file...
const mapper = {
  a: String,
  b: Boolean // not wanted anymore but forgot to remvoe
}

const res = mapProperties (data, mapper) // not throwing type error even if there is `b` in mapper and not in data.
// res = {
//   a: '1',
//   b: false // unwanted bug
// }

By using generics, res inherits return type from mapper 
```

### With new keyword
```typescript
const mapProperties = <
  T extends { [key: string]: any },
  U is { [K in keyof T]: (v: T[K]) => any } // enforces exact keys
>(
  obj: T,
  mappers: U
) ...

mapProperties ({a: 1}, {a: String, b: Boolean}) // error because `b` does not exist in T.
```

## Checklist

My suggestion meets these guidelines:
* [ x ] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [ x ] This wouldn't change the runtime behavior of existing JavaScript code
* [ x ] This could be implemented without emitting different JS based on the types of the expressions
* [ x ] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by joonhocho** [comment]
@mattmccutchen It works for simple case, but it dosen't when the data has optional key.
For example,
interface Data {
  a: number
  b?: string
}

**Comment by wkrueger** [comment]
There's a hack for that, you may google "exact types". Copied from another issue:

```ts
export type Exactify<T, X extends T> = T &
  { [K in keyof X]: K extends keyof T ? X[K] : never }
``

**Comment by joonhocho** [comment]
@wkrueger I don't see how it can be applied to the above case. Could you explain?

**Comment by wkrueger** [comment]
Let's say you want no extra keys in U

```ts
//original
const mapProperties = <
  T extends { [key: string]: any },
  U extends { [K in keyof T]: (v: T[K]) => any }
>(
  obj: T,
  mappers: U
) { } 

//changed
type Exactify<T, X extends T> = T &
  { [K in keyof X]: K extends keyof T ? X[K] : never }

const mapProperties = <
  T extends { [key: string]: any },
  U extends Exactify<{ [K in keyof T]: (v: T[K]) => any }, U>
>(
  obj: T,
  mappers: U
) { } 
```

From https://github.com/Microsoft/TypeScript/issues/12936#issuecomment-368244671

**Comment by joonhocho** [comment]
@wkrueger 
So I've tried your code and the following code compiles without error even though it should complain for missing 'c' in mapper functions.

```

// changed
type Exactify<T, X extends T> = T &
  { [K in keyof X]: K extends keyof T ? X[K] : never };

const mapProperties = <
  T extends { [key: string]: any },
  U extends Exactify<{ [K in keyof T]: (v: T[K]) => any }, U>
>(
  obj: T,
  mappers: U
): {
  [K in keyof U]: U[K] extends (a: any) => any ? ReturnType<U[K]> : never
} => {
  const res = {};
  Object.keys(mappers).forEach((key) => {
    res[key] = mappers[key](obj[key]);
  });
  return res as any;
};

const before: { a?: number; b: number; c?: string } = { b: 1 };
const after = mapProperties(before, {
  a: (x?: number): string => (x && x.toString()) || '',
  b: (x?: number): boolean => !!x,
  // c: missing => should throw an error, but doesn't
});

```

**Comment by RyanCavanaugh** [comment]
#14829 tracks a way to use type parameters without creating inference sites for them, which would be one approach.
#14520 tracks bounding generics from below rather than above, which may be an acceptable approach but probably not.

In general we're very unlikely to add features that completely eliminate subtyping and try to enforce an "exact" relationship - `mapper` in the OP should always be able to stand in for an object with fewer properties. Trying to nail down a definition of "the *same* type, not a subtype" is a trap because it prevents us from making new useful distinctions within extant type domains later on.

**Comment by gen1lee** [comment]
@RyanCavanaugh so why do you think that bug with new keys in the state is ok?

```
const changeState = <TState, TChanges extends Record<keyof TState, TState[keyof TState]>>(
  state: TState,
  changes: TChanges
) => {
  return {
    ...state,
    ...changes,
  }
}

changeState(
  { a: 1 },
  {
    b: 2, // should show error here because it is new key, but it doesn't
    a: 1,
  }
)
```

**Comment by Gentlee** [comment]
[@RyanCavanaugh](https://github.com/RyanCavanaugh) so why do you think that bug with new keys in the state is ok?

```
const changeState = <TState, TChanges extends Record<keyof TState, TState[keyof TState]>>(
  state: TState,
  changes: TChanges
) => {
  return {
    ...state,
    ...changes,
  }
}

changeState(
  { a: 1 },
  {
    b: 2, // should show error here because it is new key, but it doesn't
    a: 1,
  }
)
```

**Comment by gen1lee** [comment]
> There's a hack for that, you may google "exact types". (Copied from another issue) use that in your `extends` clause.
> 
> ```ts
> export type Exactify<T, X extends T> = T &
>   { [K in keyof X]: K extends keyof T ? X[K] : never }
> ```

Thanks, that helps, but unfortunately it produces a very strange error message that hardly anyone understands except who wrote that code.

**Comment by Gentlee** [comment]
> There's a hack for that, you may google "exact types". (Copied from another issue) use that in your `extends` clause.
> 
> ```ts
> export type Exactify<T, X extends T> = T &
>   { [K in keyof X]: K extends keyof T ? X[K] : never }
> ```

That helps, but unfortunately it produces a very strange error message that hardly anyone understands except who wrote that code.
