### ISSUE TITLE
TS 3.0-rc project references to ancestor folders breaks module dependency ordering.

### ISSUE THREAD

**Issue by WearyMonkey** [Microsoft/TypeScript#26054]
When a project contains a reference to project in a ancestor folder, includes source files must be listed in dependency order.

**TypeScript Version:**  3.0-rc, 3.0.1-insiders.20180726, and 3.1.0-dev 

**Search Terms:**

3.0 project references

**Code**

```json
{
  "compilerOptions": {
    "composite": true,
    "declaration": true

  },
  "references": [
    { "path": ".." }
  ],
  "files": [
    "./imports.ts",
    "./exports.ts"
  ]
}
```

Where `imports.ts` is:

```t
import { foo } from './exports';
```

and `exports.ts` is:
```ts
export const foo = 'foo';
```

**Expected behavior:**

Compilation succeeds.

**Actual behavior:**

```
error TS6305: Output file '/Users/toby/dev/ts3_bug/proj1/proj2/exports.d.ts' has not been built from source file '/Users/toby/dev/ts3_bug/proj1/proj2/exports.ts'.
```

Changing the order of files to:
```
  "files": [
    "./exports.ts",
    "./imports.ts"
  ]
```

Succeeds.

**Github project Link:** 

https://github.com/WearyMonkey/ts3-file-order-bug

**Related Issues:** 

https://github.com/Microsoft/TypeScript/issues/25600#issuecomment-408588841

**Comment by tommedema** [comment]
This seems crucial. Reading https://blogs.msdn.microsoft.com/typescript/2018/07/30/announcing-typescript-3-0/#project-references it says the the main purpose of references is build ordering; which actually appears to be broken? This issue was reported 1 month ago but supposedly with no progress.
