### ISSUE TITLE
Detected Circular import references of re-export

### ISSUE THREAD

**Issue by wesleyolis** [Microsoft/TypeScript#26059]
Hi,

This happens in typescript 2.8.6, if you havn't fixed anything like it I would assume the same issues I had a few days back, has not been fixed, I just didn't have time to craft a tests case then and its taken too much time now, so just going to describe the high level problem, which it then will be rather obvious.

I ran into a runtime crash of my javascript, with variables that were null and debuggers that were not working with vscode. Ended up swapping debuggers and everything, then due to the complexity of the code, most things are misleading, so I had to comment out lines of .js code, to find the file in which the problem occurred, try catch injection into the js , will trashing the maps, so debug the js file, didn't help must either. After some extensive narrowing down, I deduce that their was a circular reference import, typescript allow a file to be imported from a top level, from a lower level, which then resulted in 
variables from the file root that are exported and and used at top level, to be undefined because of loading issues, that crashes in not apparently clear.

Typescript needs to detect circular reference includes and generate compiler warnings.
I used the VSCode, Intellisense for suggested imports, in which I think imported from my top level root file, that index every below in the tree file structure for re-export as a library. I went ok cool, vscode say I can, then whyn't.. lets just do that. Their no problems in compiling the code, until runtime, in which the a variable became undefined, and their were a whole bunch of misleading symptoms.

Later this all came to back to bit, when everything came together in the larger project of code.

So please ensure that typescript can detect circular import references, because of export variables in the root of files, which then subtle becoming undefined due to the stitching of import order at runtime, causing many other symptoms and miss leading problems. If VSCode or myself was the one at fault, how every it would happen back then.. Their some reason I went ok cool, fine, mabye even because ts compiled with no errors, I just keep importing the top level, file, as no longer issues, as  it was saving me time writing code. Until runtime came along.

This should be enough to understand the reason for wanting the compiler to detect circular references.

Kind Regards,

Wesley Oliver

**Comment by kitsonk** [comment]
> Typescript needs to detect circular reference includes and generate compiler warnings.

Circular dependencies between modules are supported by pretty much every module loader and bundler, so circular module references, sadly are not something that TypeScript can just error on.  They are a major 👣🔫, but they are reality.

**Comment by mhegazy** [comment]
You can find related discussion in https://github.com/Microsoft/TypeScript/pull/21780 as well.
