### ISSUE TITLE
type narrowing in cases, when switch-ing on boolean and cases are type guards

### ISSUE THREAD

**Issue by alex-okrushko** [Microsoft/TypeScript#26069]
**TypeScript Version:**  3.1.0-dev.201xxxxx

**Search Terms:**
type narrowing, switch, type guards

**Code**

```ts
class A {
    readonly type: 'a';
    propA: string;
}

class B {
    readonly type: 'b';
    propB: string;
}

class C {
    readonly type: 'c';
    propB: string;
}

function isActionType<T extends A|B|C>(
    action: A|B|C, actionType: string): action is T {
  return action.type === actionType;
}

function reducer(action: A | B | C) { 
    switch (true) { 
        case isActionType<A>(action, 'a'): { 
            action.propA; // <-- Property 'propA' does not exist on type 'A | B | C'
        } 
    }

    if (isActionType<A>(action, 'a')) { 
        action.propA; // <-- Works, no problem here. (property) A.propA: string
    }
}

function reducerTwo(action: A | B | C) {
    switch (action.type) {
        case 'a': {
            action.propA; // Works here as well: (parameter) action: A
        }
    }
}
```

**Expected behavior:**
Switching on boolean when type guards are in case statements should work. This would be similar to `if` statement.

```ts
switch (true) {
  case typeGuard(action): {...}
}
```

**Actual behavior:**
type guards in cases do not narrow the type.

**Playground Link:** 
[PLAYGROUND LINK](https://www.typescriptlang.org/play/#src=class%20A%20%7B%0D%0A%20%20%20%20readonly%20type%3A%20'a'%3B%0D%0A%20%20%20%20propA%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Aclass%20B%20%7B%0D%0A%20%20%20%20readonly%20type%3A%20'b'%3B%0D%0A%20%20%20%20propB%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Aclass%20C%20%7B%0D%0A%20%20%20%20readonly%20type%3A%20'c'%3B%0D%0A%20%20%20%20propB%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Afunction%20isActionType%3CT%20extends%20A%7CB%7CC%3E(%0D%0A%20%20%20%20action%3A%20A%7CB%7CC%2C%20actionType%3A%20string)%3A%20action%20is%20T%20%7B%0D%0A%20%20return%20action.type%20%3D%3D%3D%20actionType%3B%0D%0A%7D%0D%0A%0D%0Afunction%20reducer(action%3A%20A%20%7C%20B%20%7C%20C)%20%7B%20%0D%0A%20%20%20%20switch%20(true)%20%7B%20%0D%0A%20%20%20%20%20%20%20%20case%20isActionType%3CA%3E(action%2C%20'a')%3A%20%7B%20%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20action.propA%3B%20%2F%2F%20%3C--%20Property%20'propA'%20does%20not%20exist%20on%20type%20'A%20%7C%20B%20%7C%20C'%0D%0A%20%20%20%20%20%20%20%20%7D%20%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20if%20(isActionType%3CA%3E(action%2C%20'a'))%20%7B%20%0D%0A%20%20%20%20%20%20%20%20action.propA%3B%20%2F%2F%20%3C--%20Works%2C%20no%20problem%20here.%20(property)%20A.propA%3A%20string%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Afunction%20reducerTwo(action%3A%20A%20%7C%20B%20%7C%20C)%20%7B%0D%0A%20%20%20%20switch%20(action.type)%20%7B%0D%0A%20%20%20%20%20%20%20%20case%20'a'%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20action.propA%3B%20%2F%2F%20Works%20here%20as%20well%3A%20(parameter)%20action%3A%20A%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%7D%0D%0A%7D)

**Related Issues:** 
Couldn't find any

Not sure if this is a feature request or a bug.

**Comment by RyanCavanaugh** [comment]
See #16887 and its linked issues

**Comment by alex-okrushko** [comment]
@RyanCavanaugh, thank you. I found a bunch of switch and type narrowing, but I guess I was looking by the wrong search terms.

> Not a common enough pattern to support

WIth `strictFunctionTypes` flag we can no longer lie to the reducer about the Action type union that is passed to it, so we are actively looking for the alternative of the typical `switch(action.type)`. A bunch of `if`s works, but I think `switch` bring more structure to the code.

What would it take to reevaluate if this pattern is common enough?
