### ISSUE TITLE
Reduce typescript's bundler 

### ISSUE THREAD

**Issue by unimonkiez** [microsoft/TypeScript#26071]
This is more of a cry to help than a real issue. 

Are there any plans to reduce typescript's build system?   

I see there's new code splitting functionality in TS3.0, and there are more features like that from previous versions where typescript just do too much. 

I already have a working build system with webpack / parcel, when working with typescript I find myself needing to define everything twice, once for my bundler and once for typescript... It's annoying. 

I've seen that ts been added to babel 7, which helps a bit with adding some other transformations for my ts and tsx files, but still way too much duplicate configuration (and tsconfig being a json file makes it even harder to share code with my bundler!!)

Thanks in advance

**Comment by DanielRosenwasser** [comment]
@bterlson answered this question [on reddit](https://www.reddit.com/r/javascript/comments/935ow9/announcing_typescript_30/e3bitee/). I think there's been a misunderstanding regarding what project references does, which is that it allows other tools to build TypeScript code efficiently once you've decided to organize code into multiple projects.

**Comment by omerman** [comment]
@unimonkiez I feel your pain!

I also feel that if Typescript configuration could be read from JS file, the code would be cleaner and better reused.
If we take as an example Babel, Eslint or any other commonly used dev tool, you'll be able to define the configuration using a dynamic executable file, a JS file, and not just a static JSON file.
