### ISSUE TITLE
Tuple transformation: tuple type lost after mapping

### ISSUE THREAD

**Issue by devjourney5** [Microsoft/TypeScript#26072]
Following transformation on tuple loses tuple information:

```ts
function pack(args: [...any[]]) {
  return args.map(a => String(a))
}
var tuple: [number, number] = [5, 5]
var packed = pack(tuple) // string[]
```
**Expected behavior:**
`packed` is of type `[string, string]`

**Actual behavior:**
`packed` is of type `string[]`

How can preserve tuple length and element types after transforming it via function, _assuming I dont know length of tuple at design time_?

**Comment by mattmccutchen** [comment]
Currently you can't.  See #25947 for the suggestion and a current workaround.
