### ISSUE TITLE
Export declaration conflicts with exported declaration of 'Buffer'

### ISSUE THREAD

**Issue by nicemaker** [Microsoft/TypeScript#26086]
Installed an older project on my new Ubuntu, of course got some compile errors after updating typescript and most i could revolve by changing my code. But this one I don't know how to get rid of:

Error
```
node_modules/@types/node/index.d.ts:995:14 - error TS2484: Export declaration conflicts with exported declaration of 'Buffer'.
```

typescript: 3.0.1
node: 10.7.0

ts-config:
```javascript
{
    "compilerOptions": {
        "outDir": "./dist/",        // path to output directory
        "sourceMap": true,          // allow sourcemap support
        "module": "commonjs",
        "noImplicitAny": false,
        "strictNullChecks": true,   // enable strict null checks as a best practice
        "target": "esnext",            // specify ECMAScript target version
        "allowJs": true,            // allow a partial TypeScript and JavaScript codebase
        "baseUrl": ".",
        "lib":["esnext","esnext.asynciterable"],
        "paths": {
            "*": [
                "node_modules/*",
                "src/types/*"
            ]
        }
    },
    "exclude": [
      "node_modules"
    ],
    "include": [
        "./src/**/*",
        "./src/page/data",
        "./src/**/mustache",
    ]
}
```

**Comment by mhegazy** [comment]
I can not get this error locally just using latest `@types\node`. Can you share more context? If i were to guess there is another `@types` package that you are using that is augmenting the declarations in `@types/node`.

**Comment by smcatala** [comment]
same issue here.
the `@types/node` declaration seems to conflict with that from the `buffer` module that `browserify` uses.
not yet sure what to do about it.

**Comment by mhegazy** [comment]
@smcatala can you share more information about your setup. i can not reproduce this with `@types/node` + `@types/browserify`

**Comment by smcatala** [comment]
sure: `browserify` transpiles the source could using the `tsify` plugin. `@types/browserify` is not installed.

`browserify` depends on `buffer@^5.0.2`, which does not include the type declarations, but `npm` typically installs `5.2.0` instead (semver compatible), which does:
a type declaration file was [added](https://github.com/feross/buffer/commit/056b770c528a1d28913bda62431d644b60083616) to the buffer module in its latest version `v5.2.0`

according to VScode, in line 977 of `@types/node/index.d.ts` (`var BuffType: typeof Buffer`), `Buffer` refers to both the definition from that file as well as that from the `buffer/index.d.ts` file.

**Comment by alexanderatallah** [comment]
Having this same problem. To repro, try installing "buffer" and also "@types/buffer". Is there any way to hide a module declaration from the main repo?

**Comment by smcatala** [comment]
a potential workaround for this issue if your project is using `package-lock.json` is to `npm install buffer@5.1.0`. this works here, but I guess it depends on which modules in your project depend on which version of `buffer`...

**Comment by mhegazy** [comment]
thanks for the info. i can reproduce this locally now.

this is a bug in the declaration file of `buffer`. using ambient module declarations (`declare module "buffer"`) adds the declaration in the global namespace, which then merges with existing declarations for the global node module `"buffer"`, and hence the error.

the declaration file in buffer should rather use the module syntax:

```ts
export class Buffer extends Uint8Array  {
    ...
}
```
instead of:

```ts
declare module 'buffer' {
    export class Buffer extends Uint8Array {
        ....
    }
}
```

I would recommend filing this issue under https://github.com/feross/buffer/issues instead.

**Comment by mhegazy** [comment]
To override the declaration of `buffer`, you can add a local file with the contents of `node_modules\buffer\index.d.ts` with the changes suggessted in my erlier comment, then add a `"paths"` mapping entry for it in your tsconfig.jon:

```ts
{
    "compilerOptions": {
        ...
        "baseUrl": "./",
        "paths": { "buffer" : ["./buffer-override.d.ts"] }
    }
}
```

**Comment by mhegazy** [comment]
Looks like this is already tracked by https://github.com/feross/buffer/issues/213

**Comment by nicemaker** [comment]
Thanks a lot everyone for the fast response, its my second project with TS so that was beyond my understanding.

**Comment by mrwillis** [comment]
Sorry for the slight hijack but I'm having trouble using this in an `includes`, `excludes` context. @mhegazy I followed your suggestion exactly but when I try to specify files manually, I run into trouble with `Cannot find name 'Buffer` in some dependent libraries.. Here is my `tsconfig.json`:

```
{
  "compilerOptions": {
    "target": "es2016",
    "module": "commonjs",
    "lib": ["es2015"],
    "declaration": true,
    "outDir": "./dist",                
    "strict": true,
    "baseUrl": "./",                 
    "paths": {
      "buffer": ["./types/buffer-override.d.ts"]
    },                           
    "typeRoots": [
      "node_modules/ethers/dist/types",
      "node_modules/@0xproject/typescript-typings/types"
    ],
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
  },
  "include": [
    "types/**/*",
    "utils/**/*",
  ],
  "exclude": [
    "test/**/*",
    "node_modules"
  ]
}
```
My `buffer-override.d.ts` is located in `types/buffer-override.d.ts` as in `paths`. If I remove the `includes` and `excludes` sections, there are no issues, but I want to remove my `/test` folder from the output files. 

Any ideas? :confused:
