### ISSUE TITLE
TypeScript has yet to allow full extent of functional programming

### ISSUE THREAD

**Issue by KSXGitHub** [Microsoft/TypeScript#26080]
## Search Terms

multiple rest element

## Suggestion

With the latest release (3.0), there's supposedly no more need of overloading FP functions, but the need remains, for TypeScript has yet to allow **multiple rest elements** within one tuple type.

### What it should look like

All of this should be valid:

```typescript
type Foo = [A, ...B, C]
type Bar = [...A, ...B, C, D]
type Baz = [...A, ...B]
```

### Partial Function

```typescript
const partial =
  <A extends any[], B extends any[], R>(fn: (...args: [...A, ...B]) => R, tail: B) =>
    (...head: A) => fn(...head, ...tail)

const fn1 = (a, b, c, d) => [a, b, c, d]
const fn2 = partial(fn1, ['a', 'b'])
const r = fn2('c', 'd') // ['a', 'b', 'c', 'd']
```

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by mattmccutchen** [comment]
Looks like a duplicate of #5453 to me.

**Comment by KSXGitHub** [comment]
@mattmccutchen Thanks, #5453 offers more. Closing this.
