### ISSUE TITLE
Unclear what is transpiled and what must be polyfilled

### ISSUE THREAD

**Issue by SaphuA** [microsoft/TypeScript#26087]
## Search Terms

polyfill, transpile

## Suggestion

We are targeting es5 in our project and have included the following libs:
`es5, es2015.collection, es2015.promise, dom, scripthost`

What I do not understand is how I am supposed to know if `Promises` (defined in es2015.promise) must be polyfilled, but that `ReadonlySet` (defined in es2015.collection) is transpiled to proper es5. This will only become clear during runtime and that is exactly what we're trying to avoid when using TypeScript.

My suggestion / question is if it is possible to make it clear when adding libs when it is required to polyfill them and when it is not.

**Comment by RyanCavanaugh** [comment]
*Syntax* is always "polyfilled". For example, TS will emit the `extends` helper if you use class inheritance.

*Functions and values* are never polyfilled. We will not provide an implementation for `Promise` or `ReadonlySet` or any other top-level value or property thereof.
