### ISSUE TITLE
document.createElement('dialog') should not return HTMLElement as type

### ISSUE THREAD

**Issue by Akxe** [Microsoft/TypeScript#26081]
**TypeScript Version:**  2.9.2, 3.0.1

**Search Terms:**
createElement dialog
**Code**

```ts
const dialog: HTMLDialogElement = document.createElement('dialog');
```

**Expected behavior:**
No error...

**Actual behavior:**
Type 'HTMLElement' is not assignable to type 'HTMLDialogElement'.

**Playground Link:** 
http://www.typescriptlang.org/play/#src=const%20dialog%3A%20HTMLDialogElement%20%3D%20document.createElement('dialog')%3B

**Related Issues:** 
Few about adding dialog element definition.

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.
