### ISSUE TITLE
JavaScript IntelliSense Should Recognize DefineProperty

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#26082]
_From @johnnykahalawai on July 30, 2018 19:19_

Issue Type: <b>Feature Request</b>

Hi -

Often when working with JavaScript an object i.e. class is extended with Object.defineProperty

Reference: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty

Unfortunately, Visual Studio's IntelliSense cannot make this connection so the GoTo Definition feature does not work.

FWIW, JetBrain's products e.g. WebStorm and IntelliJ does support this feature.

Thanks in advance,

Johnny

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 17.7.0

_Copied from original issue: Microsoft/vscode#55390_

**Comment by mjbvz** [comment]
Likely duplicate of Duplicate of #6651

**Comment by johnnykahalawai** [comment]
@mjbvz --

Not exactly.  More like this:

`
        function Person(name) {
          this.name = name;
        }

        Person.prototype.describe = function () {
          return "Person called " + this.name;
        };

        Object.defineProperty(Person.prototype, "firstInitial", {
            writable: false,
            value: function () {
              return this.name && this.name.substr(0, 1);
            }
        });

        var p = new Person("Johnny");

`

**Comment by mhegazy** [comment]
@johnnykahalawai they are the same issue. the type system does not recognize calls to `Object.defineProperty` as declarations of new properties regardless of their target.  #6651 tracks adding that support.

**Comment by johnnykahalawai** [comment]
Hi @mhegazy -

I see.  One man's opinion here but without defineProperty support salsa is missing the cilantro.

Aloha,

Johnny

**Comment by AbdelrahmanHafez** [comment]
Another example would be:

```js
// add.js

function add (x, y) {
  return x + y;
}

module.exports = add;
```




Example 1 (adding getter directly to the object):
```js
// index.js

const o = {
  get add () {
    return require('./add');
  }
};

const sum = o.add(2, 3); // 5
```

In example 1, Intellisense recognizes the add function from `add.js`, and knows its parameters, etc.

![screenshot_7](https://user-images.githubusercontent.com/19984935/46231545-99432980-c36c-11e8-8bd7-a076f1a28f7d.jpg)




Example 2 (adding getter via defineProperty):
```js
// index.js

const o = {};

Object.defineProperty(o, 'add', {
  get: function () {
    return require('./add');
  }
});

const sum = o.add(2, 3); // 5
```

In example 2, Intellisense fails to recognize the function and mistakenly expects the function to return a promise.

![screenshot_882](https://user-images.githubusercontent.com/19984935/46231585-c98ac800-c36c-11e8-885e-8134d8924468.jpg)

I am working on a utility that would allow the developers to have cleaner, aesthetic imports, where this feature is necessary to be useful for the developers who will use it.
