### ISSUE TITLE
Class decorator parameters

### ISSUE THREAD

**Issue by jamiewinder** [Microsoft/TypeScript#2609]
I'm fairly sure I have the syntax right:

```javascript
@ClassDecoratorTest("Test")
class Test
{
}

function ClassDecorationTest(target, name)
{
}
```

But this won't compile. I get the following error on the @ClassDecorator line:

error TS2346: Supplied parameters do not match any signature of call target.

**Comment by gappsby** [comment]
This code works. It will log "Test" to the console.
```typescript
@ClassDecoratorTest("Test")
class Test {
}

function ClassDecoratorTest(str) {
    return function (target): void {
        target['d_value'] = str;
        return target;
    }
}

console.log(Test['d_value']);
```

When passing arguments you have to return a function with the correct format. `tsc` helps you with it, if you provide a wrong signature, it will tell you what you've done wrong.

**Comment by jamiewinder** [comment]
Perfect, thanks.
