### ISSUE TITLE
Better errors for indexing gettable/settable values

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#26098]
@sandersn found a case where, upon turning on `noImplicitAny` in Puppeteer, we issued the following error on a `Map`:

```
Element implicitly has an 'any' type because type 'Map<string, Function>' has no index signature.
```

We should give a more specialized error message in cases where there is no index signature, but the value has a method `get` that takes a `string`, or when 

```
Element implicitly has an 'any' type because type '{0}' has no index signature. Did you mean to call '{1}'?
```

**Comment by sandersn** [comment]
@collin5 I would start by searching for the error message that you want to replace. Spaces are replaced by underscores in the code. Then add a case above that uses `getTypeOfPropertyOfType`, `getSingleCallSignature`, `getMinArgumentCount` and `getTypeAtPosition` to look for a method named get with a single string string parameter.

**Comment by collin5** [comment]
@sandersn Thank you! Will open a PR for this shortly.

**Comment by DanielRosenwasser** [comment]
Thanks @collin5!

**Comment by collin5** [comment]
You're most welcome.
