### ISSUE TITLE
allow linking local files in markdown of jsdocs

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#26094]
## Search Terms

https://github.com/Microsoft/TypeScript/issues?utf8=%E2%9C%93&q=is%3Aissue+link+markdown

## Suggestion

make markdown links to the local files work

## Use Cases

navigating to local files by clicking links displayed in jsdocs

## Examples

```ts
/** [see also](./another-file.ts) */
class MyClass {
}
```

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by RyanCavanaugh** [comment]
We don't control how editors do linking / clicking - you'd have to take this up with each individual editor.
