### ISSUE TITLE
display local images linked in markdown of jdocs

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#26092]
## Search Terms
https://github.com/Microsoft/TypeScript/issues?utf8=%E2%9C%93&q=is%3Aissue+images+markdown

## Suggestion

display **local** images if they are linked in markdown inside jsdoc comments

## Use Cases

viewing images in inline documentation

## Examples

```ts
// global images work
/** this is how it works ![Image of Yaktocat](https://octodex.github.com/images/yaktocat.png)
 */
class MyClass {
}
```
![image](https://user-images.githubusercontent.com/937933/43473941-7310ae12-94bf-11e8-90f7-e3aee4b503e7.png)

```ts
// local images do NOT work
/** this is how it works ![Hey](../../my-image.png)
 */
class MyClass {
}

```
## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by RyanCavanaugh** [comment]
😕

**Comment by aleksey-bykov** [comment]
updated
