### ISSUE TITLE
Type alias circular reference does not error and causes implicit any

### ISSUE THREAD

**Issue by skovy** [Microsoft/TypeScript#26104]
**TypeScript Version:**  
- `typescript@next`
- `typescript@2.9.2`

**Search Terms:**
- `circular reference`
- `circular reference returntype`
- `Type alias circularly references itself returntype`
- `Type alias circularly references itself implicit any`

**Code**
```ts
type A = ReturnType<A>;
//  ^^^ Type alias 'A' circularly references itself.

interface Input {
  a: number;
  b: number;
}

type R = ReturnType<typeof mul>;
function mul(input: Input): R {
  return input.a * input.b;
}
// ^^^ Return value of `mul` is now `any` because of the circular reference
```

**Expected behavior:**
Expected error: `Type alias 'R' circularly references itself.` (identical to `A`: `Type alias 'A' circularly references itself.`)

**Actual behavior:**
Only error: `Type alias 'A' circularly references itself.` (nothing about `R` or `mul` and the circular type reference)

**Reasoning:**
In this example, the `mul` function is simple but we use this for functions that can return complex objects (deeply nested) that already have explicit types. We then pass type `R` to other generics to provide type safety. This pattern works well, until we accidentally circular reference type `R` as in the above example. It's easy to miss and continue using because type `R` is now `any` so we (almost) never run into type errors as a result of this. 

**[Playground Link](https://www.typescriptlang.org/play/index.html#src=type%20A%20%3D%20ReturnType%3CA%3E%3B%0D%0A%2F%2F%20%20%5E%5E%5E%20Type%20alias%20'A'%20circularly%20references%20itself.%0D%0A%0D%0Ainterface%20Input%20%7B%0D%0A%20%20a%3A%20number%3B%0D%0A%20%20b%3A%20number%3B%0D%0A%7D%0D%0A%0D%0Atype%20R%20%3D%20ReturnType%3Ctypeof%20mul%3E%3B%0D%0Afunction%20mul(input%3A%20Input)%3A%20R%20%7B%0D%0A%20%20return%20input.a%20*%20input.b%3B%0D%0A%7D%0D%0A%2F%2F%20%5E%5E%5E%20Return%20value%20of%20%60mul%60%20is%20now%20%60any%60%20because%20of%20the%20circular%20reference)**

**Potentially Related Issues:**
- https://github.com/Microsoft/TypeScript/issues/25609

**Comment by andy-ms** [comment]
Reproduces without the parameter:
```ts
type R = ReturnType<typeof f>;
function f(): R { return 0; }
```
