### ISSUE TITLE
[w] TS2339: Property 'scaleNonUniform' does not exist on type 'DOMMatrix'.

### ISSUE THREAD

**Issue by 1984weed** [Microsoft/TypeScript#26111]
Hi guys. I love this project and use a lot. and Congrats on releasing version 3 !

I updated TypeScript version from 2.8.3 to 3.0.1. After that ts compiler becomes to return an error like this code.

```
const svgNs = "http://www.w3.org/2000/svg"
const xlink = "http://www.w3.org/1999/xlink";
const svg = <SVGSVGElement>document.createElementNS(svgNs, "svg");
svg.setAttribute("xmlns", svgNs);
svg.setAttribute("xmlns:xlink", xlink);

svg.createSVGMatrix().scaleNonUniform([], []) <- error
```

I think createSVGMatrix returned SVGMatrix in previous version. but current version looks weird because this part in [lib.dom.ts](https://github.com/Microsoft/TypeScript/blob/master/lib/lib.dom.d.ts#L13393) returns SVGMatrix. 

Does anyone know the reason? is this a bug?

Thank you.

**Comment by nmain** [comment]
Related https://github.com/w3c/fxtf-drafts/issues/214

**Comment by 1984weed** [comment]
OK. I understood

**Comment by saschanaz** [comment]
A PR has been opened for the spec side. https://github.com/w3c/fxtf-drafts/pull/318

Note that the change encourages any new codes to use `scale()` instead of legacy `scaleNonUniform()`.

**Comment by 1984weed** [comment]
`scale()` is completely different from `scaleNonUniform()`.... 
but now I cast any to use scaleNoneUniform
