### ISSUE TITLE
Call to function returning non-nullable `T` with contextual type `U | undefined` should infer `T = U`

### ISSUE THREAD

**Issue by mattmccutchen** [Microsoft/TypeScript#26119]
## Search Terms

infer undefined constraint null return contextual type strictNullChecks

Conceivably related: #16943

## Suggestion

With `strictNullChecks`, when calling a function whose return type is a type variable `T` with a non-nullable constraint, and the contextual type includes `null` and/or `undefined`, TypeScript should generate an inference for `T` of the non-nullable part of the contextual type.  Currently, I am getting no inference at all.

Minimal example (with `strictNullChecks`):
```ts
function getValue<R extends {}>(): R {
    throw new Error("not implemented");
}

function acceptValue(value?: number) { }
// Currently: Error: Argument of type '{}' is not assignable to parameter of type 'number'.
// With suggestion: No error.
acceptValue(getValue());
```
[Playground](https://www.typescriptlang.org/play/#src=function%20getValue%3CR%20extends%20%7B%7D%3E()%3A%20R%20%7B%0D%0A%20%20%20%20throw%20new%20Error(%22not%20implemented%22)%3B%0D%0A%7D%0D%0A%0D%0Afunction%20acceptValue(value%3F%3A%20number)%20%7B%20%7D%0D%0A%2F%2F%20Currently%3A%20Error%3A%20Argument%20of%20type%20'%7B%7D'%20is%20not%20assignable%20to%20parameter%20of%20type%20'number'.%0D%0A%2F%2F%20With%20suggestion%3A%20No%20error.%0D%0AacceptValue(getValue())%3B)

## Use Cases

This came up when I attempted to enable `strictNullChecks` on [this code](https://bitbucket.org/espalier-spreadsheet/espalier/src/92db1f2c379b0035eb4dcb6bf3f745c8ef15cb82/src/apps/layout-test/server/layout-test-procedures.ts?at=master&fileviewer=file-view-default#layout-test-procedures.ts-74).  `spanStyles` is an optional property of the contextual type, the return type of `PA` is a type variable with a non-nullable constraint, and it's not possible to infer the return type from the arguments to `PA`, so I got an error.  The error is easily worked around by specifying the type argument to `PA`.

## Examples

I think the suggestion is sufficiently specific that it doesn't need more examples.

## Checklist

My suggestion meets these guidelines:
* [ ] This wouldn't be a breaking change in existing TypeScript / JavaScript code _(Hopefully not, but one can never be sure with changes to the type system.)_ 
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by andy-ms** [comment]
This happens with any union:
```ts
declare function acceptValue(value: number | string): void;
declare function getValue<T extends number | boolean>(): T;
acceptValue(getValue());
```

`getValue`'s type parameter could be inferred as `number` since that satisfies both constraints. But instead `number | boolean` is inferred and there's a compile error.

**Comment by RyanCavanaugh** [comment]
ref #16072

**Comment by RyanCavanaugh** [comment]
As Andy identified this doesn't really have to do with `null` / `undefined`. But it is pretty weird that *expanding* the set of values a function can take would cause it to start erroring.

When we have an "outside" inference candidate (in this case, the contextual type that related to the return type), the right thing to do would be do intersect (*set* intersection, not `&`) the constraint for that type variable and the candidate type. We could do this (efficiently) for bare union types but synthesizing a proper set-intersection of two arbitrary types isn't something we're set up to do AFAIK.

**Comment by RyanCavanaugh** [comment]
Discussed a bunch... TL;DR the declaration `function getValue<R extends {}>(): R` should really have been illegal from the get-go and the patching we've done to make these declarations not be intrinsically painful are really just patches. So while it's super odd to have a function *start* failing when its parameter is optional, it's not really observable unless you start with a generic declaration that shouldn't exist in the first place.

Logged #26129

**Comment by mattmccutchen** [comment]
That was just a minimal example.  Here's an example where the function is implementable but the variable still can't be inferred from its arguments but only from the return type:
```ts
enum Axis { ROW = "row", COL = "col" };

function getMappedType<R extends { [A in Axis]: unknown }>(
  row: R[Axis.ROW], col: R[Axis.COL]): R | Pick<R, Axis> { 
  return { [Axis.ROW]: row, [Axis.COL]: col};
}

function acceptMappedType(mappedType?: {[A in Axis]: number}) { }
acceptMappedType(getMappedType(42, 43));
```
[Playground](https://www.typescriptlang.org/play/#src=enum%20Axis%20%7B%20ROW%20%3D%20%22row%22%2C%20COL%20%3D%20%22col%22%20%7D%3B%0D%0A%0D%0Afunction%20getMappedType%3CR%20extends%20%7B%20%5BA%20in%20Axis%5D%3A%20unknown%20%7D%3E(%0D%0A%20%20row%3A%20R%5BAxis.ROW%5D%2C%20col%3A%20R%5BAxis.COL%5D)%3A%20R%20%7C%20Pick%3CR%2C%20Axis%3E%20%7B%20%0D%0A%20%20return%20%7B%20%5BAxis.ROW%5D%3A%20row%2C%20%5BAxis.COL%5D%3A%20col%7D%3B%0D%0A%7D%0D%0A%0D%0Afunction%20acceptMappedType(mappedType%3F%3A%20%7B%5BA%20in%20Axis%5D%3A%20number%7D)%20%7B%20%7D%0D%0AacceptMappedType(getMappedType(42%2C%2043))%3B) (remember to enable strictNullChecks)

This is from my [spreadsheet project](https://bitbucket.org/espalier-spreadsheet/espalier) that is pushing mapped types to the limit to keep track of row vs. column IDs (see also #25879).
