### ISSUE TITLE
Inconsistent errors on "export declare const" vs "export declare let"

### ISSUE THREAD

**Issue by evmar** [Microsoft/TypeScript#26118]
**TypeScript Version:**  typescript@3.1.0-dev.20180801

**Search Terms:**
"export declare" "declare export" const ambient

**Code**

```ts
export declare const x = 3;
export declare let y = 3;
```

**Expected behavior:**
Both lines are errors, or both lines are allowed.

**Actual behavior:**
Only second line is an error.

```
demo.ts:2:22 - error TS1039: Initializers are not allowed in ambient contexts.

2 export declare let y = 3;
```

**Playground Link:**
https://www.typescriptlang.org/play/#src=export%20declare%20const%20x%20%3D%203%3B%0D%0Aexport%20declare%20let%20y%20%3D%203%3B%0D%0A

**Related Issues:** 
https://github.com/Microsoft/TypeScript/issues/8015 is the closest maybe.

**Comment by RyanCavanaugh** [comment]
Initializers should not be allowed in ambient contexts

**Comment by collin5** [comment]
I would like to give a try at this.

**Comment by weswigham** [comment]
@RyanCavanaugh We allow constant initializers in ambient contexts. In fact, we preferably emit them in declarations - `declare const a = 43` is preferred over `declare const a: 43`.

**Comment by RyanCavanaugh** [comment]
@weswigham this stopped being an error in 2.1 so I'm trying to figure out if we did that on purpose or not. It seems really weird but maybe it was some intentional fall-out of literal types

**Comment by RyanCavanaugh** [comment]
Clearly intentional - done in #11126
