### ISSUE TITLE
[Proposal] String conversion should be checked

### ISSUE THREAD

**Issue by Shinigami92** [Microsoft/TypeScript#26126]
## Search Terms

- as
- conversion
- type

## Suggestion

Show an error like: `Type 'abc' cannot be converted to type '"def"'.`

## Use Cases

Protection of functional parameters

## Examples

```ts
1 as 'def' // Type 'number' cannot be converted to type '"def"'.
'1' as number // Type 'string' cannot be converted to type 'number'.
true as string // Type 'boolean' cannot be converted to type 'string'.

'abc' as 'def' // working????
```

```ts
function f(x: 'abc' | 'def'): void {
	switch (x) {
		case 'abc':
			doSomething();
			break;
		case 'def':
			doSomethingElse();
			break;
	}
}

f('ghi' as 'abc'); // working o_o
```
## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by Shinigami92** [comment]
I found this: [src/compiler/diagnosticMessages.json#L1199](https://github.com/Microsoft/TypeScript/blob/master/src/compiler/diagnosticMessages.json#L1199)
If someone can point me where to start, I'm happy to do a PR

**Comment by RyanCavanaugh** [comment]
See #14156

**Comment by Shinigami92** [comment]
I did not find that because the issue was already closed, sorry for that

Should this also 'Working as Intended' in `compilerOptions.strict = true`
Is finding a solution to the problem difficult and hard to solve?

Then I think I will open an issue at TSLint

---

We now have the following (closed) issues:

- #14156
- #14161
- #22150

Will this never fixed because of a design guideline?

**Comment by RyanCavanaugh** [comment]
"Fixed" implies defect and we currently don't consider this a defect. I think we've discussed it twice with the same outcome. I can't promise nothing will ever change, but if we keep re-discussing every closed issue hoping for a different result, we will not have time to do any actual other thing.
