### ISSUE TITLE
Support inferring module specifier to allow custom import function 

### ISSUE THREAD

**Issue by mohsen1** [microsoft/TypeScript#26139]
## Search Terms
Modules, `import()`, Module Specifier, Module Namespace

## Suggestion

Support inferring module specifier passed to type import function (`import()` in type name space) to allow custom import function. 

## Use Cases

if I have a function that wraps `require`, it's impossible to declare types for it:

```js
function myRequire(moduleSpecifier) {
  return require(moduleSpecifer);
}
```

Ideally I would like to declare types for a function like that as following:

```ts
declare function myRequire(moduleSpecifier: string): import(moduleSpecifier);
```

## Use Cases 

* Custom require functions are very common, specially for testing where they do mocking
* Jest mock functions can take advantage of this 

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by AlCalzone** [comment]
It's not entirely impossible, but doesn't look nice either (and you have to duplicate the import specifier):
```ts
function load<T>(stuff: string): T {
	return require(stuff) as T;
}

const foo = load<typeof import("./index")>("./index");
```

**Comment by mohsen1** [comment]
@AlCalzone That's what we're doing currently but repeating the module specifier and all that extra syntax is why I opened this issue. 

/cc  @DanielRosenwasser

**Comment by andy-ms** [comment]
This issue would be hard to fix the way the compiler is designed currently, since it means we would have to load in new files while type-checking. Currently we can get the full set of imports just by parsing.
