### ISSUE TITLE
Configure compiler less strict [Question]

### ISSUE THREAD

**Issue by timoweiss** [Microsoft/TypeScript#2613]
I'm currently writing a webserver application using hapijs (nodejs). I have a bunch of plugins which I want to write in Typescript. A Hapijs plugin needs a function called `register()` and an attributes function property with a name and version:

```javascript
register(server, options, next) {
}
register.attributes = {
    name: 'plugin',
    version: '0.1.0'
};
```
When I want to compile this code, I always get
```
lib/plugins/plugin.ts(2,5): 2300 Duplicate identifier 'register'.
lib/plugins/plugin.ts(8,12): 2300 Duplicate identifier 'register'.
```
I don't know the specs very well but I'm wondering whether it should be allowed or not?
Edit: [hapijs plugin docs](http://hapijs.com/api#plugins)

**Comment by tarh** [comment]
With a [hybrid type](http://www.typescriptlang.org/Handbook#interfaces-hybrid-types)?

**Comment by timoweiss** [comment]
Thanks for the reply.
If I got it right, then I would do something like this:
```javascript
export interface IRegister {
    (server, options, next): void;
    attributes:any;
}
```
And in the class:
```javascript
export default
class UserPlugin {
    register: IRegister;
    //...
}
```
Running this sample still results in the same errors.

**Comment by tarh** [comment]
Can you show the code in plugin.ts(2,5) and (8,12)?

**Comment by timoweiss** [comment]
Sure:

```javascript
//2
register:Register;
//5
register = (server, options, next) => {
```

**Comment by timoweiss** [comment]
Note: I'm using the fat arrow notation to fix `this`.

**Comment by tarh** [comment]
Why not using `var`?

	var register: IRegister;

**Comment by timoweiss** [comment]
yeah, he code is inside a class.

**Comment by tarh** [comment]
I can not guess the context, you do not show enough code.

**Comment by timoweiss** [comment]
Jep, sry. Here is a complete file:
```javascript
export interface IRegister {
    (server, options, next): void;
    attributes:any;
}

export default
class Plugin {
    register:IRegister;
    constructor() {
        this.register.attributes = {
            name: 'plugin',
            version: '0.1.0'
        };
    }
    register = (server, options, next) => {
        server.bind(this);
        this._register(server, options);
        next();
    };
    private _register(server, options) {
        // Register
        return 'register';
    }
}
```
This is the repository:
https://github.com/premily/hapi-typescript-plugin/

**Comment by tarh** [comment]
export interface IRegister {
	    (server, options, next): void;
	    attributes?:any;
	}
	
	class Plugin {
	    constructor() {
	        this.register.attributes = {
	            name: 'plugin',
	            version: '0.1.0'
	        };
	    }
	    register:IRegister = (server, options, next) => {
	        server.bind(this);
	        this._register(server, options);
	        next();
	    };
	    private _register(server, options) {
	        // Register
	        return 'register';
	    }
	}

Next time, think to StackOverflow rather than wanting to change the compiler to the first compile error. ;)

**Comment by timoweiss** [comment]
many thanks! hm, yeah right. Throwing an error did not seem to me as a feature when declaring a function and function attributes :)
Thanks!
