### ISSUE TITLE
Type 'Promise<number>' is not assignable to type 'Promise<void>'

### ISSUE THREAD

**Issue by zombie** [Microsoft/TypeScript#26134]
**TypeScript Version:**  3.0.1

**Code**

```ts
async function abortMessage() {
    return 3;
}

async function processMessage(abort) {
    let waitFor = Promise.resolve();
    if (abort) {
        waitFor = abortMessage();
    }
    // ..
    await waitFor;
    // ...
}
```

**Expected behavior:**
`waitFor` variable starts with the type `Promise<void>`, and is never accessed in any way that would violate the type system.  Assigning a `Promise<number>` value to it should be accepted just it is with functions -- you can assign a function of type `() => number` to a variable of type `() => void`, since the type checker guarantees that the return value is never used the wrong way ([playground link](https://www.typescriptlang.org/play/?#src=%0D%0Alet%20x%3A%20()%20%3D%3E%20void%3B%0D%0Alet%20y%3A%20()%20%3D%3E%20number%3B%0D%0A%0D%0Ax%20%3D%20y%3B%0D%0A)). 

**Actual behavior:**

    Type 'Promise<number>' is not assignable to type 'Promise<void>'

**Playground Link:** [here](https://www.typescriptlang.org/play/?#src=%0D%0Aasync%20function%20abortMessage()%20%7B%0D%0A%20%20%20%20return%203%3B%0D%0A%7D%0D%0A%0D%0Aasync%20function%20processMessage(abort)%20%7B%0D%0A%20%20%20%20let%20waitFor%20%3D%20Promise.resolve()%3B%0D%0A%20%20%20%20if%20(abort)%20%7B%0D%0A%20%20%20%20%20%20%20%20waitFor%20%3D%20abortMessage()%3B%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20%2F%2F%20..%0D%0A%20%20%20%20await%20waitFor%3B%0D%0A%20%20%20%20%2F%2F%20...%0D%0A%7D%0D%0A%0D%0A)

**Comment by RyanCavanaugh** [comment]
Duplicate #12871
