### ISSUE TITLE
Array.includes not recognized

### ISSUE THREAD

**Issue by ffxsam** [Microsoft/TypeScript#26144]
**TypeScript Version:**  2.9.2

**Search Terms:**
"array includes"

**Code**

```ts
const blah: string[] = ['hi', 'bye'];
const inc = blah.includes('hi');
```

**Expected behavior:**
TS should know what `Array.includes` is by now.

**Actual behavior:**
TS complains that `.includes` doesn't exist on an array.

**Playground Link:** 
Playground is currently broken.

**Related Issues:** 
https://github.com/Microsoft/TypeScript/issues/12678
https://github.com/Microsoft/TypeScript/issues/12848

**tsconfig.json**
```json
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "strict": true,
    "skipLibCheck": true,
    "allowSyntheticDefaultImports": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "jsx": "preserve",
    "importHelpers": true,
    "moduleResolution": "node",
    "esModuleInterop": true,
    "sourceMap": true,
    "baseUrl": ".",
    "types": [
      "node",
      "jest",
      "webpack",
      "webpack-env",
      "webpack",
      "webpack-env"
    ],
    "paths": {
      "@/*": ["src/*"]
    },
    "lib": ["es2015", "dom", "dom.iterable", "scripthost"]
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.tsx",
    "src/**/*.vue",
    "tests/**/*.ts",
    "tests/**/*.tsx"
  ],
  "exclude": ["node_modules"]
}
```

**Comment by RyanCavanaugh** [comment]
> `"lib": ["es2015", "dom", "dom.iterable", "scripthost"]`

This line says "I only want lib definitions for ES2015, the dom, iterable, and scripthost", in other words, "Don't show me APIs from post-ES2015, such as Array#includes".

If you want APIs from post-ES2015, of which Array#includes is one, you can specify that:

> `"lib": ["es2015", "esnext", "dom", "dom.iterable", "scripthost"]`
