### ISSUE TITLE
--build --watch does not generate compilation ended message

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#26147]
From https://github.com/Microsoft/vscode/issues/55560

**TypeScript Version:**  typescript@3.1.0-dev.20180802

**Search Terms:**
- build
- watch

**Steps**
Run `tsc --build . --watch` in a directory with a tsconfig

**Expected behavior:**
When compilation finishes, a message printed to indicate that TS is now watching. `tsc --p . --watch` for example outputs: 

```
 Found 1 error. Watching for file changes.
```

**Actual behavior:**
Nothing printed. 

VS Code relies on the message to understand when TS is actively re-compiling

**Playground Link:** 

**Related Issues:**

**Comment by blink1073** [comment]
Hi @mhegazy, what is the expected milestone for this?  The [jupyterlab](https://github.com/jupyterlab/jupyterlab) project is blocked to upgrading to 3.0 by this issue.  Cheers!

**Comment by afshin** [comment]
Hi @RyanCavanaugh, thanks for updating the milestone so we can plan better around this. Do you know if the bug fix for this will be backported to 3.0 as well?

**Comment by mjbvz** [comment]
@RyanCavanaugh VS Code would really like this fixed a 3.0.2. This is important enough that we'd like to get it fixed in our next release instead of in a month and a half with vscode 1.28

**Comment by RyanCavanaugh** [comment]
Didn't realize other programs were reading watch mode output to determine their own behavior 🤕 

@sheetalkamat can you base this fix off the 3.0 branch so we can backport more easily?
