### ISSUE TITLE
Inconsistent type widening behavior with readonly object declaration in function call

### ISSUE THREAD

**Issue by kube** [Microsoft/TypeScript#26158]
**TypeScript Version:** 3.0.1

## Search Terms

- readonly
- literal type
- object prop
- inference
- type widening

## Code

TypeScript currently behaves inconsistently when declaring a `readonly` object directly in a function call.

```ts
const readonlyNamedProp = <
  T extends { hello: string }
>(input: Readonly<T>) => input

const readonlyObject = <
  T extends {}
>(input: Readonly<T>) => input
```

## Expected behavior
```ts
const a = readonlyNamedProp({ hello: 'World' })
type A = typeof a // { readonly hello: 'World' }

const b = readonlyObject({ hello: 'World' })
type B = typeof b // { readonly hello: 'World' }
```

## Actual behavior
```ts
const a = readonlyNamedProp({ hello: 'World' })
type A = typeof a // { readonly hello: 'World' }

const b = readonlyObject({ hello: 'World' })
type B = typeof b // { readonly hello: string }
```

## Example usage

I'm willing to use this on a Runtime Type Check library (still dirty code):

https://github.com/kube/structype

**[Current rework](https://github.com/kube/structype/blob/f0084ac03326eec7e07f7bfd8ea639d56fe73d87/src/Type.ts)**

```ts
const Animal = Type({
  kind: 'animal',
  age: Number,
  name: String
})

if (Animal.test(someObj)) {
  someObj.kind // 'animal' at runtime, but string statically
}

```

Workaround is to wrap `kind` in a function call, which adds unnecessary verbosity:

```ts
const Animal = Type({
  kind: Type('animal'),
  age: Number,
  name: String
})
```

****

[Playground Link](https://www.typescriptlang.org/play/#src=const%20readonlyNamedProp%20%3D%20%3C%0D%0A%20%20T%20extends%20%7B%20hello%3A%20string%20%7D%0D%0A%3E(input%3A%20Readonly%3CT%3E)%20%3D%3E%20input%0D%0A%0D%0Aconst%20readonlyObject%20%3D%20%3C%0D%0A%20%20T%20extends%20%7B%7D%0D%0A%3E(input%3A%20Readonly%3CT%3E)%20%3D%3E%20input%0D%0A%0D%0A%0D%0Aconst%20a%20%3D%20readonlyNamedProp(%7B%20hello%3A%20'World'%20%7D)%0D%0Atype%20A%20%3D%20typeof%20a%0D%0A%0D%0Aconst%20b%20%3D%20readonlyObject(%7B%20hello%3A%20'World'%20%7D)%0D%0Atype%20B%20%3D%20typeof%20b)

## Related Issues

https://github.com/Microsoft/TypeScript/issues/10195
https://github.com/Microsoft/TypeScript/issues/14194
https://github.com/Microsoft/TypeScript/issues/20195

**Comment by ahejlsberg** [comment]
This is working as intended. In `readonlyNamedProp`, the argument is contextually typed by `{ hello: string }` (the constraint of `T`) which is taken as an indication that you want to infer a literal type for the `hello` property (i.e. some type that is a subtype of `string`). However, in `readonlyObject` there is no constraint and therefore no contextual type for the `hello` property, and since we're inferring for a mutable location we widen type `'World'` to `string`.

**Comment by kube** [comment]
Ok I understand in case `T extends {}`.
But if `T extends { [key: string]: string }`, shouldn't the `hello` prop type be narrowed to `'World'`?

```ts
const readonlyObject = <
  T extends { [key: string]: string }
>(input: Readonly<T>) => input

const b = readonlyObject({ hello: 'World' })
type B = typeof b.hello // string
```

[Playground link](https://www.typescriptlang.org/play/#src=const%20readonlyNamedProp%20%3D%20%3C%0D%0A%20%20T%20extends%20%7B%20hello%3A%20string%20%7D%0D%0A%3E(input%3A%20Readonly%3CT%3E)%20%3D%3E%20input%0D%0A%0D%0Aconst%20readonlyObject%20%3D%20%3C%0D%0A%20%20T%20extends%20%7B%20%5Bkey%3A%20string%5D%3A%20string%20%7D%0D%0A%3E(input%3A%20Readonly%3CT%3E)%20%3D%3E%20input%0D%0A%0D%0A%0D%0Aconst%20a%20%3D%20readonlyNamedProp(%7B%20hello%3A%20'World'%20%7D)%0D%0Atype%20A%20%3D%20typeof%20a.hello%0D%0A%0D%0Aconst%20b%20%3D%20readonlyObject(%7B%20hello%3A%20'World'%20%7D)%0D%0Atype%20B%20%3D%20typeof%20b.hello)
