### ISSUE TITLE
Extending global Function interface breaks instanceof Type Guard

### ISSUE THREAD

**Issue by kobiburnley** [Microsoft/TypeScript#26159]
**TypeScript Version:**  3.1.0-dev.201xxxxx

**Search Terms:**
global Function interface
instanceof
Type Guard

**Code**

```ts
declare global {
  interface Function {
    now(): string;
  }
}

Function.prototype.now = function () {
  return "now"
}

class X {
  static now() {
    return {}
  }

  why() {

  }
}

class Y {

}

console.log(X.now()) // works as expected
console.log(Y.now()) // works as expected

export const x: X | number = Math.random() > 0.5 ? new X() : 1

if (x instanceof X) {
  x.why() // should compile
}
```

**Expected behavior:**
Code compiles

**Actual behavior:**
Compilation failed 
"Property 'why' does not exist on type 'number'."

**Playground Link:** [Playground](https://www.typescriptlang.org/play/#src=declare%20global%20%7B%0A%20%20interface%20Function%20%7B%0A%20%20%20%20now()%3A%20string%3B%0A%20%20%7D%0A%7D%0A%0AFunction.prototype.now%20%3D%20function%20()%20%7B%0A%20%20return%20%22now%22%0A%7D%0A%0Aclass%20X%20%7B%0A%20%20static%20now()%20%7B%0A%20%20%20%20return%20%7B%7D%0A%20%20%7D%0A%0A%20%20why()%20%7B%0A%0A%20%20%7D%0A%7D%0A%0Aclass%20Y%20%7B%0A%0A%7D%0A%0Aconsole.log(X.now())%20%2F%2F%20works%20as%20expected%0Aconsole.log(Y.now())%20%2F%2F%20works%20as%20expected%0A%0Aexport%20const%20x%3A%20X%20%7C%20number%20%3D%20Math.random()%20%3E%200.5%20%3F%20new%20X()%20%3A%201%0A%0Aif%20(x%20instanceof%20X)%20%7B%0A%20%20x.why()%20%2F%2F%20should%20compile%0A%7D%0A)

**Related Issues:** 
https://github.com/Microsoft/TypeScript/issues/7271

**Comment by andy-ms** [comment]
The problem has something to do with `class X` having `now()` with a different return type than `Function`. So `const f: Function = X;` would fail, so we may not be letting `instanceof` work.

**Comment by kobiburnley** [comment]
@andy-ms You're right, I forgot to emphasize on this. It happens on Classes that their statics fields override some added properties to the Function interface.

But this works as expected though:
```TypeScript
console.log(X.now()) // works as expected
console.log(Y.now()) // works as expected
```
