### ISSUE TITLE
Mixed ":" and "="

### ISSUE THREAD

**Issue by korenevskiy** [Microsoft/TypeScript#2615]
Then can get confused, by ":" denotes the type, and then after ":" denotes an internal variable.  That definition is written with a "=", and then definition write by ":".
Why not make all definition through "="?  A type done through ":"!
And everywhere all mixed up. The real significance of these signs are constantly changing their meaning.  
function foo({ from, to = 10 }) {}//definition variable  "="
foo({ from: 1, to: 5 });//definition variable  ":"
let { first: f, last: l } = { first: 'Jane', last: 'Doe' }; //definition variable ":" and "="
let { a: x = 1 } = { a: undefined }; //definition variable  ":" and "="
function greetClient({name, height: howTall}) {} //definition variable  new name ":"

**Comment by basarat** [comment]
Notes: 
* It gets easier with time. 
* Its JavaScript's fault, not TypeScript's

Definitely will not happen.

**Comment by RyanCavanaugh** [comment]
What basarat said. This is just JavaScript syntax.

**Comment by korenevskiy** [comment]
But the basis of the same after 6 EcmaScript will TypeScript?
And now JavaScript is stupid syntax.
An Example
var item = { 		//definition variable  "="
	name: "one", //definition variable ":" 
	title: [{name: "people", desc: "Red"}, //definition variable ":"
		 {name: "people", desc: "Yelow"} //definition variable ":"
	]};
funcrion Func ($f : newNameVar){  //definition variable  NEW NAME VARIABLE
}

**Comment by RyanCavanaugh** [comment]
I'm not sure what you're proposing we do (unless someone has a time machine that can take us back to 1995 and change JavaScript, in which case let's do more than just tweak the syntax!)

Everywhere `:` or `=` appears in the grammar, the other symbol already has another meaning.

**Comment by korenevskiy** [comment]
It's different.
The point is not that the assignment has several characters.
More Bad. The fact that the mark of certain functions vary between the values. Meaning of signs constantly changing ":" and "=".

**Comment by korenevskiy** [comment]
But We ought to do better and to correct mistakes of the past.
But EcmaScript will be made of TopeSkript.
Imagine that the "+" and "-" change of  idea depending on the context.

**Comment by danquirk** [comment]
A programming language is not an iPhone app. We cannot simply say 'this thing now means something different, go fix your millions of lines of existing code to work again' and expect people to keep upgrading to new versions of TypeScript. Every programming language has some decisions which with hindsight would've been made differently, but the cost of changing them after the fact is enormous.

EcmaScript is not made of TypeScript. We contribute to the discussions on EcmaScript but we do not define the future of EcmaScript, and even if we did, we would not change this syntax and break every piece of existing JavaScript code out there. 

While the inconsistency here is not necessarily ideal it's actually pretty difficult to accidentally use them incorrectly with TypeScript. 
```ts
var item2: { x: 1; } // meant to say item2=, got an error
var item3 = {x = 1 } // meant to say x: 1, got an error
```

**Comment by korenevskiy** [comment]
Of course, you're right.
But to apply the recommendations At least in Autoinltelisence VisualStudio can.
and at the level of code analysis in VS.
How strict rules with switch on typization in VS.
