### ISSUE TITLE
Discriminated union doesn't work right with type guard

### ISSUE THREAD

**Issue by nmain** [Microsoft/TypeScript#26165]
**TypeScript Version:**  `typescript@3.1.0-dev.20180802`

**Search Terms:**
discriminated union
type guard

**Code**
Requires `"strictNullChecks": true`

```ts
interface Good {
  success: true;
  response: any;
}
interface Bad {
  success: false;
  error: any;
}
type Maybe = Good | Bad;
function isMaybe(obj: any): obj is Maybe {
  return typeof obj.success === "boolean";
}

function foo(obj: any) {
  if (isMaybe(obj)) {
    if (obj.success) {
      console.log(obj.response); // Property 'response' does not exist on type 'Bad'
    } else {
      console.log(obj.error); // Property 'error' does not exist on type 'Good'
    }
  }
}

function bar(obj: any) {
  if (isMaybe(obj)) {
    const maybe = obj;
    if (maybe.success) {
      console.log(maybe.response); // works
    } else {
      console.log(maybe.error); // works
    }
  }
}
```

**Expected behavior:**
No errors

**Actual behavior:**
Discriminated union doesn't seem to work in `foo`.  It works in `bar`, though.

**Playground Link:** 
https://www.typescriptlang.org/play/#src=interface%20Good%20%7B%0D%0A%20%20success%3A%20true%3B%0D%0A%20%20response%3A%20any%3B%0D%0A%7D%0D%0Ainterface%20Bad%20%7B%0D%0A%20%20success%3A%20false%3B%0D%0A%20%20error%3A%20any%3B%0D%0A%7D%0D%0Atype%20Maybe%20%3D%20Good%20%7C%20Bad%3B%0D%0Afunction%20isMaybe(obj%3A%20any)%3A%20obj%20is%20Maybe%20%7B%0D%0A%20%20return%20typeof%20obj.success%20%3D%3D%3D%20%22boolean%22%3B%0D%0A%7D%0D%0A%0D%0Afunction%20foo(obj%3A%20any)%20%7B%0D%0A%20%20if%20(isMaybe(obj))%20%7B%0D%0A%20%20%20%20if%20(obj.success)%20%7B%0D%0A%20%20%20%20%20%20console.log(obj.response)%3B%20%2F%2F%20Property%20'response'%20does%20not%20exist%20on%20type%20'Bad'%0D%0A%20%20%20%20%7D%20else%20%7B%0D%0A%20%20%20%20%20%20console.log(obj.error)%3B%20%2F%2F%20Property%20'error'%20does%20not%20exist%20on%20type%20'Good'%0D%0A%20%20%20%20%7D%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Afunction%20bar(obj%3A%20any)%20%7B%0D%0A%20%20if%20(isMaybe(obj))%20%7B%0D%0A%20%20%20%20const%20maybe%20%3D%20obj%3B%0D%0A%20%20%20%20if%20(maybe.success)%20%7B%0D%0A%20%20%20%20%20%20console.log(maybe.response)%3B%20%2F%2F%20works%0D%0A%20%20%20%20%7D%20else%20%7B%0D%0A%20%20%20%20%20%20console.log(maybe.error)%3B%20%2F%2F%20works%0D%0A%20%20%20%20%7D%0D%0A%20%20%7D%0D%0A%7D%0D%0A

**Related Issues:** 
Didn't find anything that seemed very similar.

**Comment by ahejlsberg** [comment]
This is a duplicate of #13962.

**Comment by nmain** [comment]
Thanks for looking into this.  I was not aware of this limitation on discriminated unions.
