### ISSUE TITLE
Type Intersection and Union Work with One Operand; Intended?

### ISSUE THREAD

**Issue by AnyhowStep** [Microsoft/TypeScript#26167]
**TypeScript Version:**  3.0.1

**Search Terms:** type intersection union one operand

**Code**

```ts
//No errors (Which is weird to me)
type b = & boolean;
type s = | string;

//Error: Type expected (Which makes sense)
type n = number &;
```

I made a typo in my code yesterday and had something like the above.
I only realized it today, but was surprised to see that this works.

**Expected behavior:**
An error about how type intersection and union should have two operands, or that I was missing a left-operand.

**Actual behavior:**
Compiles.
`b` correctly inferred as `boolean` type.
`s` correctly inferred as `string` type.

**Playground Link:** [here](http://www.typescriptlang.org/play/#src=%2F%2FNo%20errors%0D%0Atype%20b%20%3D%20%26%20boolean%3B%0D%0Atype%20s%20%3D%20%7C%20string%3B%0D%0A%0D%0A%2F%2FType%20expected%20(Which%20makes%20sense)%0D%0Atype%20n%20%3D%20number%20%26%3B)

-----

I guess I don't really have a problem with this being allowed but it just looks wrong.

**Comment by RyanCavanaugh** [comment]
@DanielRosenwasser seems like this should be an error anyway though?

**Comment by DanielRosenwasser** [comment]
If you've written auto-generated code ([and I have](https://unpkg.com/@octokit/rest@15.9.5/index.d.ts)) it's actually pretty handy. So I know that'd break `@octokit/rest`. 😄

**Comment by RyanCavanaugh** [comment]
Sounds like you should be using `dts-dom`!

**Comment by AnyhowStep** [comment]
Hmm, I guess it isn't *that* harmful. And it looks like it's already seen use...
