### ISSUE TITLE
Mapped tuple types don't infer as arrays in generics

### ISSUE THREAD

**Issue by jscheiny** [Microsoft/TypeScript#26163]
**TypeScript Version:**  3.1.0-dev.20180802

**Search Terms:**

Mapped tuple type generic infer array

**Code**

```ts
type Element<T> = T extends Array<infer U> ? U : never;
type Mapped<T> = { [K in keyof T]: T[K] };

type F<T> = Element<Mapped<T>>;
type R1 = F<[string, number, boolean]>; // never
type R2 = Element<Mapped<[string, number, boolean]>>; // string | number | boolean
```

**Expected behavior:**

The type of `R1` should be `string | number | boolean`.

**Actual behavior:**

The type of `R1` is `never`.

**Comment by jcalz** [comment]
Yeah, this has bitten me too... 

```ts
declare function acceptArray(arr: any[]): void;
declare function mapArray<T extends any[]>(arr: T): {[K in keyof T]: T[K]};
function acceptMappedArray<T extends any[]>(arr: T) {
  acceptArray(mapArray(arr)); // error! 
}
```

**Comment by jscheiny** [comment]
I just got a chance to try this out, and it works well insituation where the generic type parameter is unconstrained however adding a constraint to this seems to mess things up as below:

```ts
type Element<T> = T extends Array<infer U> ? U : never;
type Mapped<T> = { [K in keyof T]: T[K] };

type Unconstrained<T> = Element<Mapped<T>>;
type T1 = Unconstrained<[string, number, boolean]>; // string | number | boolean

type Constrained<T extends any[]> = Element<Mapped<T>>;
type T2 = Constrained<[string, number, boolean]>; // any
```

In this case, `Constrained<T>` seems to always return `any` despite its only difference from `Unconstrained<T>` being the `extends any[]` clause. It seems that the type of the constraint is important as can be seen below:

```ts
type Unconstrained<T> = Element<Mapped<T>>;
type T1 = Unconstrained<[1, 2, 3]>; // 1 | 2 | 3

type Constrained<T extends number[]> = Element<Mapped<T>>;
type T2 = Constrained<[1, 2, 3]>; // number
```

Should I re-open this ticket or file a new one?

**Comment by ahejlsberg** [comment]
Yes, appears we still have an issue. I will reopen.

**Comment by jack-williams** [comment]
Should the following have also been fixed, or is there another issue at play here?

```ts
type ID<T extends any[]> = { [P in keyof T]: T[P] };

interface Test<U extends any[]> {
    (...args: ID<U>): number // A rest parameter must be of an array type. [2370]
}
```

**Comment by ahejlsberg** [comment]
@jack-williams The example above works with #26676.
