### ISSUE TITLE
Project references failed to pick up new file without a clean rebuild

### ISSUE THREAD

**Issue by sandersn** [Microsoft/TypeScript#26168]
**Search Terms:**

project references new file

**Steps**

1. Clone typescript repo and build (with `jake`? with `jake runtests-parallel`? not sure how much is required, but jake probably suffices)
2. Create new file: src/compiler/f.ts with contents

```ts
namespace ts {
    export function one() { return 1 }
}
```
3. Add f.ts to src/compiler/tsconfig.json
4. Add a reference to `one` in createTypeChecker in checker.ts:

```ts
one();
```

5. Build with `jake`.

**Expected behavior:**
No build errors.

**Actual behavior:**
Build of `tsc` succeeds, but build of `typescriptServices` fails:

```
$ jake
node lib/tsc.js -b src
node built/local/tsc.js -b built/local/typescriptServices.tsconfig.json
src/compiler/checker.ts:430:35 - error TS2552: Cannot find name 'one'.

430         one();
            ~~~

```

Running `jake clean` before `jake` fixes the problem.

**Comment by weswigham** [comment]
Note: This is unrelated to project references. It is simply that our generated services tsconfig is not updated/regenerated when a new file is added to (or removed from) a component tsconfig.

**Comment by RyanCavanaugh** [comment]
Not even clear if this still repros

**Comment by weswigham** [comment]
I think it still does, maybe? IDK - if @sheetalkamat already removed the secondary builds for `@internal` declarations with here recent work, then it might not, since we wouldn't be generating configs anymore.

**Comment by sheetalkamat** [comment]
`@internal` special builds are already removed so we do not generate those tsconfig files anymore

**Comment by weswigham** [comment]
Neato, I don't think this should be able to repro anymore then.
