### ISSUE TITLE
Error in catch clause should be unknown

### ISSUE THREAD

**Issue by felixfbecker** [microsoft/TypeScript#26174]
## Search Terms

catch unknown type

## Suggestion

Today I had another situation where I would have wanted https://github.com/Microsoft/TypeScript/issues/13219, but a less complex feature that would have prevented the bug as well would have been if the error in `catch` clauses had the new `unknown` type instead of `any`, forcing me to narrow it down before accessing properties.

Ideally this would be the same for the `Promise` rejection type.

## Use Cases

Making error handling more type safe. Currently `any` prevents type narrowing.

## Examples

This is a real world example of a bug:
```ts
    let pipeline: Pipeline
    try {
        ;({ body: pipeline } = await buildkiteClient.post('organizations/sourcegraph/pipelines', {
            body: buildkitePipeline,
            json: true,
        }))
    } catch (err) {
        if (
            err.error &&
            Array.isArray(err.error.errors) &&
            err.errors[0] &&
            err.errors[0].field === 'name' &&
            err.errors[0].code === 'already_exists'
        ) {
            console.log(`Buildkite pipeline ${repoName} already exists, skipping creation`)
            pipeline = await buildkiteClient.get(`organizations/sourcegraph/pipelines/${repoName}`)
        } else {
            throw err
        }
    }
```
Very easy to miss in code review - it should have been `err.error.errors`. This is an error returned by a real API.

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code (with a flag)
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by mhegazy** [comment]
This is only possible if #25720, #10715, #25172, and #21732 are implemented. otherwise it is a massive breaking change.

**Comment by donaldpipowitch** [comment]
I'd love to see this as well. I just made a PR to get this for Reacts `componentDidCatch` (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30068), because it would have prevented a real world bug in our code and looked for an equivalent issue for the native `try/catch`.

**Comment by mqliutie** [comment]
Hi all, How can I fix this error ?
Type 'unknown' is not assignable to type 'DataResType'

```
type DataResType = {
	data: Array<string>,
	success: boolean
}

const result: DataResType = await request({
    url: 'getSomeData',
    data: {page: 1, pageSize: 10}
}).catch(e => {
    return {
        success: false,
    };
});
if(result.success){
	// do sth
}
```

**Comment by falsandtru** [comment]
I want to enable this change by a compiler option. Or want to declare only unknown type like `catch (reason: unknow) { }`.

**Comment by gerardolima** [comment]
I believe the *default* inferred type for  `catch (err) { }` should be `unknown`, which it _is_, instead of `any` which is unsafe and highly discouraged. `unknown` is safer and provides better semantics; I really don't understand why this is not the default for tsc.

**Comment by wbt** [comment]
It appears this has been implemented and should likely be closed.
https://devblogs.microsoft.com/typescript/announcing-typescript-4-4-beta/#use-unknown-catch-variables
