### ISSUE TITLE
ts3 Property 'children' is missing in type, i'm not asking for any child (without children, no child) when using static defaultProps

### ISSUE THREAD

**Issue by jwallet** [Microsoft/TypeScript#26189]
- TypeScript Version:  3.0.1
- tslint 5.11
- react 16.4.1

**Search Terms:** ts3, react, stateful component, without child, no child, declare props stateful component without child, ts asking for children prop but not asked by my component, interface extends React.Prop<JSX.Element> works (old way) but not type Props

using my compo this way
`<MyCompo propTestOne={ModeEnum.Form} /> // error [ts] `
```
[ts]
Type '{ defaultMode: EditModeEnum; }' is not assignable to type '{ children: ReactNode; }'.
  Property 'children' is missing in type '{ defaultMode: EditModeEnum; }'.
````

this used to work
```
export enum EditModeEnum { Form = 0,Text }

type Props = Readonly <{ defaultMode: EditModeEnum; }>;
type State = Readonly <{ activeMode: EditModeEnum; }>;

export default class MyCompo extends React.PureComponent<Props, State> {
  public static defaultProps: Partial<Props> = {
    defaultMode: EditModeEnum.Form
  };

  public state: State = {
    activeMode: this.props.defaultMode
  };
// ...
}
```

now only this works, using extends React.Props (even if it's old way to do it and deprecated)
```
interface IProps extends React.Props<MyCompo> { defaultMode: EditModeEnum}
interface IState { activeMode: EditModeEnum}

export default class MyCompo extends React.PureComponent<IProps, IState> {
// ...
}
```

if i add myself `children: React.ReactNode` in my props, the error will disappear but my test will fail using enzyme/shallow, looks like something is wrong here but can't put my finger on it.

**Expected behavior:** don't ask for child if the component does not have it inside the props or use it in the render `this.props.children`

**Actual behavior:** TS wants children prop to be defined for all components, this looks weird to make it work : `<MyComponent><span /></MyComponent>`

**Comment by jwallet** [comment]
i updated my question to include the real prop (i thought it was not related to their type) but actually using Enum in prop leads to this error.. looks like [ts] feels enum looks like children prop

**Comment by jwallet** [comment]
looks like the error does not appear after removing `defaultProps`

**Comment by jwallet** [comment]
```

**Comment by jwallet** [comment]
```

**Comment by jwallet** [comment]
this is the solution to have a component with non-required props `defaultProps`

```
type Props = Readonly<{
 // any forced props goes here
}> &
  Partial<IDefaultProps>;

interface IDefaultProps {
  defaultMode: EditModeEnum.Form;
// any other non-required props here
}

type State = Readonly<{
  activeMode: EditModeEnum;
}>;

export class EditModeSwitch extends React.Component<Props, State> {
  public state: State = {
    activeMode: this.props.defaultMode || EditModeEnum.Form
  };
```

**Comment by weswigham** [comment]
Mmmm the new react.d.ts conditional needs to specially handle children - or rather, the `children` that the react .d.ts mixes in needs to be optional, since they won't always exist, nor are they intended to be required!

**Comment by weswigham** [comment]
Actually, hold on - what `react` .d.ts version are you using? The one on DT doesn't support library managed props yet, so `defaultProps` shouldn't be capable of affecting anything.

**Comment by weswigham** [comment]
Yeah, I can't reproduce this in a fresh project on 3.0.1 with the latest react `.d.ts`es and this code:
```ts
import React = require("react");

export enum EditModeEnum { Form = 0,Text }

type Props = Readonly <{ defaultMode: EditModeEnum; }>;
type State = Readonly <{ activeMode: EditModeEnum; }>;

export default class MyCompo extends React.PureComponent<Props, State> {
  public static defaultProps: Partial<Props> = {
    defaultMode: EditModeEnum.Form
  };

  public state: State = {
    activeMode: this.props.defaultMode
  };
// ...
}

const use = <MyCompo defaultMode={EditModeEnum.Form} />;
```
- what exact versions of everything are you using? (TS and @types/react)

**Comment by jwallet** [comment]
Ok im gonna try this on monday

**Comment by jwallet** [comment]
ok so if `defaultMode` has a default prop that means it's not required, so this still does not work `<My Compo />` with ts saying it's missing children prop

**Comment by jwallet** [comment]
found out someone added a fix for redux-form because typescript was not using redux-form wrapper props and was asking to be defined. so until redux-form fixes it, we have to keep this fix. but this fix was the one also asking for children when defaultProps was defined in a component... we will try to fix it on our side but this was coming from our side, sorry.

**Comment by jwallet** [comment]
so we made the fix with redux-form
