### ISSUE TITLE
Type Intersection on null now produces null

### ISSUE THREAD

**Issue by arackaf** [Microsoft/TypeScript#26191]
**TypeScript Version:**  3.1.0-dev.201xxxxx

**Search Terms:**

N/A

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.

type T = { a: number } & null;

```

**Expected behavior:**

T will be `{ a: number }`

**Actual behavior:**

It's null.

I've searched the 3.0 releases and breaking changes, and found absolutely nothing.  Is this in fact a breaking change that just wasn't listed? 

**Playground Link:** 

N/A

**Related Issues:** 

N/A

**Comment by RyanCavanaugh** [comment]
@ahejlsberg regression from 2.9 -> 3.0

**Comment by ahejlsberg** [comment]
This is actually working as intended.

When `--strictNullChecks` is off, `null` and `undefined` are considered subtypes of *every* type. In 3.0 we're better at reducing unions and intersections, and an intersection `T & null` or `T & undefined` for some object type `T` now reduces to just `null` or `undefined`. This is exactly similar to how `T | null` or `T | undefined` reduces to just `T`.

When `--strictNullChecks` is on, `null` and `undefined` are distinct types, so `T & null` is really the same as `never` (i.e. a type with no possible values). For a variety of reasons (e.g. error reporting and contextual typing) we are less aggressive about reducing away intersections of disjoint types, but we will indeed reduce away `T & null` when it is put into a union type.

The upshot of all of this is that `T & null` and `T & undefined` are really not meaningful types, and I would avoid using them.

**Comment by arackaf** [comment]
Thank you for the response @ahejlsberg!  Much appreciated. 

> The upshot of all of this is that T & null and T & undefined are really not meaningful types, and I would avoid using them.

Indeed - this came up because we had some code expecting a generic type T, which would do something like `T & React.htmlAttributes` and since T did NOT have a default type specified, people would specify `<null`> when they didn't need to add anything new into `React.htmlAttributes`.

Solution is to simply give `T` a default type of `{}`.

**Comment by DanielRosenwasser** [comment]
Sorry about the break though! I just documented it now [on the wiki](https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#intersecting-with-nullundefined-reduces-to-nullundefined-outside-of-strictnullchecks) and I'll try to add it to the blog post. I'd suggest `unknown` over `{}` though.
