### ISSUE TITLE
esModuleInterop does not implicitly enable allowSyntheticDefaultImports

### ISSUE THREAD

**Issue by ffxsam** [Microsoft/TypeScript#26193]
**TypeScript Version:**  2.9.x and 3.x

**Search Terms:**
esmoduleinterop
esmoduleinterop allowsyntheticdefaultimports

**Expected behavior:**
Enabling `esModuleInterop` should also implicitly enable `allowSyntheticDefaultImports`, according to https://www.typescriptlang.org/docs/handbook/compiler-options.html

**Actual behavior:**
This is not the case, as per this issue: https://github.com/vuejs/vue-cli/issues/2062

**Comment by DanielRosenwasser** [comment]
What are your thoughts here @weswigham?

**Comment by weswigham** [comment]
It does but only if targeting a module < es6, since that's all we control the emit behavior for. It's a weak justification, though - I can see changing it.

**Comment by ffxsam** [comment]
Hey @DanielRosenwasser, I saw your other comment about the docs being wrong. So this is a toss-up. Whatever you guys think makes the most sense.

**Comment by kellycampbell** [comment]
The case of this I just ran into with both 3.0.1 and 2.9.2 has `"target": "es5"` and `"esModuleInterop": "true"` in the tsconfig. The import that was failing until I also enabled `allowSyntheticDefaultImports` was:

```
import React from 'react';
```

**Comment by RyanCavanaugh** [comment]
Would appreciate a PR for this!

**Comment by NMinhNguyen** [comment]
@RyanCavanaugh Per the contributing guide,

> If you've submitted a PR for a bug, please post a comment in the bug to avoid duplication of effort.

I've submitted PR #26866.

@DanielRosenwasser I might have to submit another PR reverting https://github.com/Microsoft/TypeScript-Handbook/commit/8e974c814d44381ed05a3b6203894e0f9e39d552 if/when my PR lands.
