### ISSUE TITLE
ArgumentType?

### ISSUE THREAD

**Issue by mmahalwy** [Microsoft/TypeScript#26196]
Similar to how TS has `ReturnType`, is it possible to have `ArgumentType`? Or an example of how to extract a function's arguments and specify a different return type?

Example, due to `redux-pack` changing this action to a promise
```
export function createMyPackActionWithArgs(arg1: string, arg2?: string) {
  return { type: MY_PACK_ACTION, promise: fetchMyData() };
}
```

This technically returns a `Promise` when in component but an `Object` when reducer.

**Comment by MartinJohns** [comment]
Just look at how `ReturnType` is defined or at conditional types in general.

    type FirstArgument<T extends Function> = T extends (arg: infer R) => any ? R : never;
    function foo(n: number) { }
    type FirstArgOfFoo = FirstArgument<typeof foo>;

**Comment by mmahalwy** [comment]
@MartinJohns what if you want to infer all the args?

**Comment by rsolomon** [comment]
Looks like this does what is needed, but is only supported in 3.0:

```
type ArgumentTypes<T> = T extends (...args: infer U) => infer R ? U : never;
type ReplaceReturnType<T, TNewReturn> = (...a: ArgumentTypes<T>) => TNewReturn;
```

**Comment by mmahalwy** [comment]
@rsolomon, that's a bummer :( can't jump to 3.0 yet :(

**Comment by alvis** [comment]
@RyanCavanaugh I'd suggest it as a feature request, not a question.`ArgumentTypes` is a useful helper type which I use often in my work. Can we add it into the library as `ReturnType`?
