### ISSUE TITLE
Option to retain type information in objects (instanceof with interfaces)

### ISSUE THREAD

**Issue by jaw** [Microsoft/TypeScript#26205]
I know TS is designed to throw away type information during compilation.

However, it would be really useful in larger applications to have the _option_ to retain it.

**Pros:**

- instanceof would then work with interfaces.
- Code completion could then work properly: 

Currently one has to access members of a class like 

`myClass{"someProperty"} = ...; `

where I would rather go 
```
if (myClass instanceof somePropertyInterface) 
  myClass.someProperty = ...;
```

**Cons:**

- Performance and memory footprint would suffer, as every object would have to have an array of objects in it.

**Meta:**
This would be an optional flag, disabled by default.

**Comment by RyanCavanaugh** [comment]
See #1549 or many other suggestions to the same effect
