### ISSUE TITLE
v1.5.0-alpha hides parseCommandLine

### ISSUE THREAD

**Issue by clausreinke** [Microsoft/TypeScript#2620]
To give users of my LS API client/server the same commandline interface they are used to from tsc, I have been using `parseCommandLine`, but quite recently, and sadly affecting `v1.5.0-alpha`, this has been marked `@internal` and is no longer available.

Could you please re-expose this? Ironically, as far as I can tell, the culprit seems to have been a patch that was meant to expose more functions:
```
commit 18d8fedbf52a02af0700f653f499a2e79fb479d3
Author: Mohamed Hegazy <mhegazy@microsoft.com>
Date:   Tue Mar 31 10:52:21 2015 -0700

    Expose readConfigFile and parseConfigFile
```

My users are getting impatient with me depending on the github version of TS, and now I can't offer them use the new npm alpha:-(

**Comment by clausreinke** [comment]
I can work around (e.g. by using `["parseCommandLine"]` for now.

Btw, what is the story wrt `@internal` and `*_internal.d.ts`? I'm already referencing `typescript_internal.d.ts` - should the function appear there?

**Comment by mhegazy** [comment]
You should not take a dependency on `typescript_internal.d.ts`; we have added the @internal change and we will remove typescript_internal.d.ts file.

**Comment by mhegazy** [comment]
@clausreinke what are you using this call for? can it be replaced by using tsconfig.json?

**Comment by clausreinke** [comment]
As mentioned above, the idea is to keep the experience similar to that for `tsc`: users can, for most smaller projects, give commandline options or, for longer-term projects, provide a tsconfig.json, or override the latter with the former.

In terms of editor experience, it is nice that one can restart the server with different options, without having to create or modify a tsconfig.json; though, once I support reloading tsconfig.json in a running server, there'll be a conflict because commandline options are supposed to take precedence.

**Comment by clausreinke** [comment]
> You should not take a dependency on  typescript_internal.d.ts ; we have added the @internal change and we will remove typescript_internal.d.ts file.

:-(((( There is quite a lot of useful functionality I reuse via typescript_internal.d.ts - here is a quick re-build failure of my project with the reference removed:
```
node node_modules/typescript/bin/tsc.js tss.ts -target ES5 -m commonjs --noEmitOnError -outDir bin 2>&1 | tee build.log
harness.ts(31,20): error TS2339: Property 'createTextChangeRange' does not exist on type 'typeof "typescript"'.

harness.ts(31,45): error TS2339: Property 'createTextSpan' does not exist on type 'typeof "typescript"'.

harness.ts(47,18): error TS2339: Property 'createTextChangeRange' does not exist on type 'typeof "typescript"'.

harness.ts(47,44): error TS2339: Property 'createTextSpanFromBounds' does not exist on type 'typeof "typescript"'.

harness.ts(58,23): error TS2339: Property 'unchangedTextChangeRange' does not exist on type 'typeof "typescript"'.

harness.ts(65,19): error TS2339: Property 'collapseTextChangeRangesAcrossMultipleVersions' does not exist on type 'typeof "typescript"'.

tss.ts(81,12): error TS2339: Property 'sys' does not exist on type 'typeof "typescript"'.

tss.ts(82,32): error TS2339: Property 'sys' does not exist on type 'typeof "typescript"'.

tss.ts(174,14): error TS2339: Property 'isRootedDiskPath' does not exist on type 'typeof "typescript"'.

tss.ts(177,31): error TS2339: Property 'combinePaths' does not exist on type 'typeof "typescript"'.

tss.ts(181,27): error TS2339: Property 'sys' does not exist on type 'typeof "typescript"'.

tss.ts(253,38): error TS2339: Property 'sys' does not exist on type 'typeof "typescript"'.

tss.ts(255,45): error TS2339: Property 'getDefaultLibFileName' does not exist on type 'typeof "typescript"'.

tss.ts(385,76): error TS2339: Property 'textSpanEnd' does not exist on type 'typeof "typescript"'.

tss.ts(413,75): error TS2339: Property 'textSpanEnd' does not exist on type 'typeof "typescript"'.

tss.ts(601,16): error TS2339: Property 'sys' does not exist on type 'typeof "typescript"'.

tss.ts(658,23): error TS2339: Property 'normalizePath' does not exist on type 'typeof "typescript"'.

tss.ts(658,40): error TS2339: Property 'sys' does not exist on type 'typeof "typescript"'.

tss.ts(662,13): error TS2339: Property 'sys' does not exist on type 'typeof "typescript"'.

tss.ts(664,26): error TS2339: Property 'getDirectoryPath' does not exist on type 'typeof "typescript"'.

tss.ts(680,45): error TS2339: Property 'sys' does not exist on type 'typeof "typescript"'.

tss.ts(693,19): error TS2339: Property 'normalizePath' does not exist on type 'typeof "typescript"'.

tss.ts(693,36): error TS2339: Property 'combinePaths' does not exist on type 'typeof "typescript"'.

tss.ts(712,59): error TS2339: Property 'getDirectoryPath' does not exist on type 'typeof "typescript"'.

tss.ts(720,18): error TS2339: Property 'extend' does not exist on type 'typeof "typescript"'.

tss.ts(724,16): error TS2339: Property 'extend' does not exist on type 'typeof "typescript"'.

test ! -s build.log
```
I seem to recall that helper functions to compensate API changes often appear in `internal`, and letting TS figure out the platform `sys` setup is also useful.

**Comment by mhegazy** [comment]
thanks @clausreinke for the list. i think my PR is not sufficient. We will go through the list and expose APIs that are not strictly internal implementation details. should have an update by the end of the week.

**Comment by basarat** [comment]
Fwiw I depend on internal as well

**Comment by mhegazy** [comment]
ts.sys should be exposed with #2692. we have talked about things like extend, clone, and hasProperty, and we feel these are not related to the language perse and should not be on the API. 

We are open to exposing utlities like createTextSpanFromBounds and getDefaultLibFileName, but i will do these in a different change.

@basarat can you let us know what internal APIs you depend on?

**Comment by basarat** [comment]
> can you let us know what internal APIs you depend on?

Sorry, I double checked. I guess I am not anymore :heart:

**Comment by clausreinke** [comment]
Thanks. Though I've got this "down the rabbit hole"-feeling again, like so often in these last few years (computeLineStarts, computePositionOfLineAndCharacter, ...). I really wish someone would take your new toy away!-) Or at least use some form of `@deprecated` before switching to `@internal`.

Perhaps if you forced yourself to document all API changes (including suggestions about how to use the modified API to implement old API uses) in one place, things might be less tiresome (such as frequent renamings, moves, +1/-1, property vs getter and back, etc. - refactoring is fun, but has to slow down when external APIs are involved)? Otherwise, I miss such changes until the branch is merged *and* the LKG is updated, by which time it becomes hard to reconstruct your intentions behind the changes.

**Comment by mhegazy** [comment]
I am sorry for the trouble. We have been keeping track of API breaking changes in https://github.com/Microsoft/TypeScript/wiki/API-Breaking-Changes ; if there are ones that were missed  please let us know and we will document them if they were intentional and revert the change if they were not.

As for the _internal.d.ts issues, that was never meant to be part of the public API, hence the "_internal" suffix. We did not document this in any of the samples (see https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API). We are sorry for any confusion, and for 1.5 we have removed it to make sure we there are not any confusion about what is public in the future.

This is our second release with the API, and we do not intend to make any big changes at the point, but there were a lot of clean up we had to do as we got feedback on the API from 1.4. We appreciate your patience as you transition from 1.4 to 1.5 and we will make sure the next transition is much smother.

I have exposed some of the APIs you mentioned above in #2730. please let me know if i missed any and will look into exposing them.

**Comment by basarat** [comment]
https://github.com/Microsoft/TypeScript/wiki/API-Breaking-Changes :sugar: :heart:

**Comment by clausreinke** [comment]
I understand:-) I've been supporting typescript-tools since Nov 2012 (basis for Vim/Emacs/Sublime plugins almost as long), so I've been working with "internal" APIs most of the time, and have been exposed to much of the back-and-forth... I'll close this issue once I've converted my code.

The final thing I'm looking at is lineMaps (in ScriptInfos and position-to-line/col conversions), which you are trying to hide now. Guess I'll have to use SourceFiles in favour of ScriptInfos, which needs some restructuring.

There is an Atom-feed for wiki updates https://github.com/Microsoft/TypeScript/wiki.atom , but it isn't all that good (missing page titles).

**Comment by clausreinke** [comment]
Thanks again.

**Comment by clausreinke** [comment]
oops, should I have waited for the branch merge?

**Comment by sebilasse** [comment]
@mhegazy 
> I have exposed some of the APIs you mentioned above in #2730. please let me know if i missed any and will look into exposing them.

Just updated [typhen](https://github.com/shiwano/typhen/issues/1) and currently I'm not able to use the official API because the following are missing (I think they are useful for each project converting TS interfaces to more 'extensive' schemas, e.g. JSON schema as in my case) ::

- ts.IntrinsicType
- ts.ResolvedType

**Comment by mhegazy** [comment]
why do you need ResolvedType? this is meant to be an internal implantation detail, and can not be relied on as a public supported API.

**Comment by alexeagle** [comment]
I don't see a resolution on the thread specifically about the OP `parseCommandLine` which Angular also uses in some places. We need to customize the compiler and would like to expose a `tsc`-identical command line API. Can it be non-`@internal` ?

**Comment by alexeagle** [comment]
ping @mhegazy can we send a PR to export `parseCommandLine`?

**Comment by evmar** [comment]
For context, we have a command that wraps tsc and wants to replicate its behavior of command-line flags and tsconfig.json parsing.  See code at https://github.com/angular/tsickle/blob/f411ab125356c7e74c1213834942a93aa4538dfd/src/main.ts#L74

**Comment by alexeagle** [comment]
Ping!
