### ISSUE TITLE
Object Intersection Type with Optional Field Assignable when Unexpected

### ISSUE THREAD

**Issue by AnyhowStep** [Microsoft/TypeScript#26207]
**TypeScript Version:**  3.0.1

**Search Terms:** intersection, optional field, assignable

**Code**

```ts
//--strictNullChecks turned on

//`optional? : number`
type ObjT = {
    required: string,
    optional?: number,
};

//`optional? : number`
type IntersectionT = (
    { required: string } &
    { optional?: number }
);

declare const objT: ObjT;
declare const intersectionT: IntersectionT;

//`optional? : boolean`
type OptionalBoolean = {
    required: string,
    optional? : boolean,
}

//Makes sense
//Type 'number' is not assignable to
//type 'boolean | undefined'.
const failsAsExpected: OptionalBoolean = objT; 

//Expected to fail,
//Does not fail.
//Should fail because
//`optional? : number` and`optional? : boolean`
//are different types
const doesNotFail: OptionalBoolean = intersectionT; 
//doesNotFail.optional is now of type `boolean|undefined`
//when the original variable is of type `number|undefined`
```

**Expected behavior:**

`IntersectionT` should behave like `ObjT` and not be assignable to `OptionalBoolean`

I've always used the `&` operator, with object types as operands, in generics and whatnot when I needed to "combine" objects.

I've never used `&` and expected the above to happen.

So, I was pretty confused when code was compiling and executing.

I feel like allowing this to happen can cause really subtle bugs with larger code bases.

**Actual behavior:**

`IntersectionT` is assignable to `OptionalBoolean`

**Playground Link:** [here](http://www.typescriptlang.org/play/#src=%2F%2F--strictNullChecks%20turned%20on%0A%0A%2F%2F%60optional%3F%20%3A%20number%60%0Atype%20ObjT%20%3D%20%7B%0A%20%20%20%20required%3A%20string%2C%0A%20%20%20%20optional%3F%3A%20number%2C%0A%7D%3B%0A%0A%2F%2F%60optional%3F%20%3A%20number%60%0Atype%20IntersectionT%20%3D%20(%0A%20%20%20%20%7B%20required%3A%20string%20%7D%20%26%0A%20%20%20%20%7B%20optional%3F%3A%20number%20%7D%0A)%3B%0A%0Adeclare%20const%20objT%3A%20ObjT%3B%0Adeclare%20const%20intersectionT%3A%20IntersectionT%3B%0A%0A%2F%2F%60optional%3F%20%3A%20boolean%60%0Atype%20OptionalBoolean%20%3D%20%7B%0A%20%20%20%20required%3A%20string%2C%0A%20%20%20%20optional%3F%20%3A%20boolean%2C%0A%7D%0A%0A%2F%2FMakes%20sense%0A%2F%2FType%20'number'%20is%20not%20assignable%20to%0A%2F%2Ftype%20'boolean%20%7C%20undefined'.%0Aconst%20failsAsExpected%3A%20OptionalBoolean%20%3D%20objT%3B%20%0A%0A%2F%2FExpected%20to%20fail%2C%0A%2F%2FDoes%20not%20fail.%0A%2F%2FShould%20fail%20because%0A%2F%2F%60optional%3F%20%3A%20number%60%20and%60optional%3F%20%3A%20boolean%60%0A%2F%2Fare%20different%20types%0Aconst%20doesNotFail%3A%20OptionalBoolean%20%3D%20intersectionT%3B%20%0A%2F%2FdoesNotFail.optional%20is%20now%20of%20type%20%60boolean%7Cundefined%60%0A%2F%2Fwhen%20the%20original%20variable%20is%20of%20type%20%60number%7Cundefined%60)

**Comment by AnyhowStep** [comment]
For my case, I just have to go through my code base and do the following,

*Old code*:

```ts
type CalculateRequiredFields<T> = /*Special code*/
type CalculateOptionalFields<T> = /*Special code*/
type ToObject<T> = {
    {
        [name in CalculateRequiredFields<T>] : T[name]
    } &
    {
        [name in CalculateOptionalFields<T>]? : T[name]
    }
};
```

*New code*:

```ts
type CalculateRequiredFields<T> = /*Special code*/
type CalculateOptionalFields<T> = /*Special code*/
//This will give something like `{ required : string } & { optional? : number }`
type _ToObject<T> = {
    {
        [name in CalculateRequiredFields<T>] : T[name]
    } &
    {
        [name in CalculateOptionalFields<T>]? : T[name]
    }
};
//This will give something like `{ required : string, optional? : number }`
type ToObject<T> = {
    [name in keyof _ToObject<T>] : T[name]
};
```

**Comment by RyanCavanaugh** [comment]
One rule of intersection types is that the type `T & U` is *always* assignable to `T`. So the type `{ required: string } & { optional?: number }` is assignable to `ObjT` because the `{ required: string }` is.

The rule isn't really negotiable in terms of core behavior - the *entire point* of intersection types is for them to behave like that for scenarios like mixins. The question is just then where do we *intentionally introduce inconsistencies* between `&` when it applies to type parameters `T` and `U` and when it applies to non-generic types.

Currently the answer is "Introduce no new inconsistencies" because there's never really a valid reason to write an intersection type between two object types. You could have just written it as two properties, or
```ts
type Optional = { optional?: number };
type RequiredProp = { required: string };
interface IntersectionT extends Optional, RequiredProp { }
```

**Comment by AnyhowStep** [comment]
The example I had above didn't use generics but my use case was more like,

```
declare function genericFoo<T, U> (t:T, u:U) : (T&U);
const a = genericFoo(/*args*/); //inferred type is IntersectionT
/*Snip*/
const b : OptionalBoolean = a; //assignable when shouldn't be

//Or,
function bar () : OptionalBoolean {
    /*Snip*/
    return genericFoo(/*args*/); //inferred type is IntersectionT and returns fine when it shouldn't
}
```

But I do see why having `T&U` isn't good when both are object types; like when both T and U share field names with different types...

Slightly off topic, the type declaration for `Object. assign<>()` also returns an intersection type which also leads to the same potential problems.

Thanks for clarifying!

**Comment by buola** [comment]
> Currently the answer is "Introduce no new inconsistencies" because there's never really a valid reason to write an intersection type between two object types. You could have just written it as two properties, or
> 
> ```ts
> type Optional = { optional?: number };
> type RequiredProp = { required: string };
> interface IntersectionT extends Optional, RequiredProp { }
> ```

While it's true that an intersection between object types is never really necessary, it's unfortunately the type returned by functions like Object.assign, so the following (obviously incorrect) code is valid:

```ts
var x: { a?: number, b: number } = Object.assign({ a: 'aaa'}, { b: 3 });
```

Would it be possible to change the return type of Object.assign in some way to avoid the problem?

While trying to find the simplest example of this problem, I saw that the following code actually complains about the type of 'a':

```ts
var y: { a?: number } = Object.assign({ a: 'aaa'}, { b: 3 });
```

I don't really understand the reason why this produces an error while the previous one doesn't
