### ISSUE TITLE
esnext.asynciterable.d.ts should be es2018.asynciterable.d.ts

### ISSUE THREAD

**Issue by saschanaz** [Microsoft/TypeScript#26218]
https://github.com/Microsoft/TypeScript/blob/9706f1729e9c41c9af901c279367dec0ab1093d1/src/lib/esnext.d.ts

```ts
/// <reference lib="es2018" />
/// <reference lib="esnext.asynciterable" />
/// <reference lib="esnext.array" />
/// <reference lib="esnext.symbol" />
/// <reference lib="esnext.intl" />
```

Currently Symbol.asyncIterator is in esnext but it should be in [es2018](https://github.com/tc39/proposals/blob/master/finished-proposals.md).

**Comment by DanielRosenwasser** [comment]
PRs welcome; just give a heads up if you decide to take a swing at this.

**Comment by saschanaz** [comment]
Opened #26220.
