### ISSUE TITLE
Type 'null' is not assignable to type 'boolean | undefined' when using optional

### ISSUE THREAD

**Issue by alan-agius4** [Microsoft/TypeScript#26214]
**TypeScript Version:**  3.0.1

**Search Terms:**
null checks
Type 'null' is not assignable

**Code**

```ts
interface Foo {
    prop?: boolean;
}

const bar: Foo = {
    prop: null
};
```
I am not sure, if it's working as expected with `TypeScript 3`, but I didn't find any reference of this change.

With `strictNullChecks`, when having an optional property and one assigns a `null` it now emits an error.

I tried asking on `gitter`, but no one confirmed if it's a bug or not.

**Expected behavior:**
no error.

**Actual behavior:**
```
Type 'null' is not assignable to type 'boolean | undefined'
```

**Comment by MartinJohns** [comment]
`null` is a different type and value from `boolean` and `undefined`. `undefined === null` would also result to `false`. So if you want this to run without an error, you have two options:

- Assign `undefined`, not `null`, because the type says it accepts either `boolean` or `undefined`.
- Change the type to include `null`, e.g. `boolean | undefined | null` (or `prop?: boolean | null`).

**Comment by alan-agius4** [comment]
Thanks for your response. I know that null is different from undefined. But in Typescript 2.9 in this particular usecase they were treated the same.

My question is, is this a bug or the change is intentional and undocumented?

**Comment by MartinJohns** [comment]
This results in absolutely the same behavior in TypeScript 2.9.1, 2.8.4, 2.7.1, 2.6.2, 2.5.3 and 2.4.2.

Can you provide a minimal test case that reproduces the behavior as you claim it to be?

Most likely you're thinking of a project where `strictNullChecks` are disabled, in which case neither `undefined` nor `null` are considered types and they're interchangeably when assigning.

**Comment by RyanCavanaugh** [comment]
This hasn't changed recently and the error is expected under strictNullChecks

**Comment by ollydixon** [comment]
Hey, just some input; this looks like a bug.

If we use optional it should be considered null | undefined.

We shouldn't need to write out 

``var?: string | null;``

In my opinion that feels very wrong.

It should be

`var?: string;`

And that should work for

`var: z.string().nullable(),`

**Comment by MartinJohns** [comment]
This is still not a bug. `undefined` and `null` are different values, and with `strictNullChecks` enabled different types. Optional properties **only** refer to `undefined`.

**Comment by ollydixon** [comment]
@MartinJohns sorry I was commenting on the wrong library 🙈
