### ISSUE TITLE
findRenameLocations returns no results with this setup in ts 3.0

### ISSUE THREAD

**Issue by dsherret** [Microsoft/TypeScript#26211]
**TypeScript Version:**  3.1.0-dev.20180804, 3.0.1

**Search Terms:** findRenameLocations, rename

**Code**

Perhaps there's something wrong with this setup, but it works in TS < 3.0.1.

```ts
import * as ts from "typescript";

const testFilePath = "/file.ts";
const testFileText = "function myFunction() {} const reference = myFunction;";

const options: ts.CompilerOptions = { target: ts.ScriptTarget.ES5 };
let version = 0;
const languageServiceHost: ts.LanguageServiceHost = {
    getCompilationSettings: () => options,
    getDefaultLibFileName: () => "",
    getScriptFileNames: () => [testFilePath],
    getScriptVersion: fileName => {
        if (fileName !== testFilePath)
            throw new Error();
        return (version++).toString();
    },
    getScriptSnapshot: fileName => {
        if (fileName !== testFilePath)
            throw new Error();
        return ts.ScriptSnapshot.fromString(testFileText);
    },
    getCurrentDirectory: () => "/",
    useCaseSensitiveFileNames: () => true,
    readFile: (path, encoding) => {
        if (path !== testFilePath)
            throw new Error();
        return testFileText;
    },
    fileExists: fileName => fileName === testFilePath,
    directoryExists: dirName => dirName === "/"
};

const languageService = ts.createLanguageService(languageServiceHost);

const sourceFile = ts.createSourceFile(testFilePath, testFileText, ts.ScriptTarget.Latest, true);
const identifier = sourceFile.forEachChild(child => {
    if (ts.isFunctionDeclaration(child))
        return child.name!;
})!;

console.log(identifier.getText());
console.log(languageService.findRenameLocations(testFilePath, identifier.getStart(), false, false));
```

**Expected output:**

As in TS 2.9.1 and previous versions:

```
myFunction
[ { fileName: '/file.ts',
    textSpan: { start: 9, length: 10 },
    isWriteAccess: true,
    isDefinition: true,
    isInString: undefined },
  { fileName: '/file.ts',
    textSpan: { start: 43, length: 10 },
    isWriteAccess: false,
    isDefinition: false,
    isInString: undefined } ]
```

**Actual output:**

```
myFunction
[]
```

**Comment by dsherret** [comment]
By the way, it's been returning no results in every scenario and setup I've tried so far (not too many). It would be nice to know if there's a workaround for this in the meantime...

**Comment by DanielRosenwasser** [comment]
@andy-ms can you investigate what's going wrong here?

**Comment by DanielRosenwasser** [comment]
By the way, some of the code above is unused (e.g. `compilerHost`). Maybe this can be minimized.

**Comment by dsherret** [comment]
@DanielRosenwasser updated. I removed the `ts.createProgram` statement before posting and didn't notice `compilerHost` wasn't used after that.

**Comment by dsherret** [comment]
I figured it out. It's because of the incrementing version in `getScriptVersion()`. Works when I change that to be a constant. I was being lazy when implementing that originally (which was just making it work... then never looked at it again). I'll change it to just be an incrementing value per source file that only gets updated when the source file changes.

@DanielRosenwasser given that people probably shouldn't do what I was doing here, I would say this is a bug on my end.

**Comment by DanielRosenwasser** [comment]
I do wonder why that would change things though.

**Comment by dsherret** [comment]
Yeah me too. Not a big deal though and doing what I mentioned above resolved my problem. I'm going to close this as I doubt this affects anyone else.
