### ISSUE TITLE
Add missing member fix should work for missing function

### ISSUE THREAD

**Issue by andy-ms** [microsoft/TypeScript#26217]
**TypeScript Version:**  3.1.0-dev.20180804

**Code**

```ts
class C {}
new C().m();

f();

namespace N { export const x = 0; }
N.f();

import * as m from "./mod";
m.f();
```

**Expected behavior:**

Codefix for both `m()` and for every `f()`.

**Actual behavior:**

Codefix for only `m()`.

**Comment by a-tarasyuk** [comment]
I think, the following examples more related to defining a functions, not to missing members (`fixAddMissingMember`).

```ts
f();

namespace N { export const x = 0; }
N.f();

import * as m from "./mod";
m.f();
```

Do we need to extend `fixAddMissingMember` or need to define a new QF? It seems a bit strange to define functions with `Add_all_missing_members`. 

/cc @DanielRosenwasser @RyanCavanaugh

**Comment by lukaszpolowczyk** [comment]
Duplicate of my issue:
https://github.com/microsoft/vscode/issues/44837

My issue was closed as "* out-of-scope", and here someone is doing it (almost completely).

@mjbvz I am glad that this has been realized.
But maybe the original needs to be marked?
