### ISSUE TITLE
Question : Dependency Diagram from `SourceFile`s

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#2621]
I am trying to create a dependency diagram https://github.com/TypeStrong/atom-typescript/issues/234 However `sourceFile.referencedFiles` doesn't seem to point to `imported` files. 

Is there some other property I should be looking at or will I need to go back to `ts.preProcessFile` / `preProcessedFileInfo.importedFiles`

**Comment by mhegazy** [comment]
The imports are available in the AST. you just need to walk the tree. see how createProgram does it [here](https://github.com/Microsoft/TypeScript/blob/master/src/compiler/program.ts#L402).

**Comment by ToddThomson** [comment]
It would be useful/beneficial if the parser generated this information ( importedFiles ) and saved it off to SourceFile. I'm experimenting with a tsconfig.json extended for bundling and this would help ( although I do realize that I can always walk the AST to get the information ).

**Comment by mhegazy** [comment]
They are on the AST already. I believe the proposal is to add a helper that returns the top level imports in a file.

**Comment by ToddThomson** [comment]
@mhegazy . From my review of createProgram(), I can see that the source file dependency chain is traversed. However, It appears that at each level the dependencies are not saved to refFile ( Can you please confirm this ).
If this is the case then I would ask that as the source file dependencies are traversed a property in SourceFile ( refFile ) be used to store the ( ImportedFiles ) dependencies.

**Comment by mhegazy** [comment]
createProgram is collecting all files in a program by walking ///references and imports. it is not what @basarat was asking for, I just sited it for the logic of finding imports in a file.

given a SourceFile, the information about files it *directly* (triple-slash references and imports) reference are always in the tree. they are just handled differently.

for triple-slash references:
```ts
var references = sourceFile.referencedFiles;
```

for imports:
```ts
function getImports(searchNode: ts.Node, importedModules: string[]) {
    ts.forEachChild(searchNode, node => {
        // Vist top-level import nodes
        if (node.kind === ts.SyntaxKind.ImportDeclaration || node.kind === ts.SyntaxKind.ImportEqualsDeclaration || node.kind === ts.SyntaxKind.ExportDeclaration) {
            let moduleNameExpr = getExternalModuleName(node);
            // if they have a name, that is a string, i.e. not alias defition `import x = y`
            if (moduleNameExpr && moduleNameExpr.kind === ts.SyntaxKind.StringLiteral) {
                importedModules.push((<ts.LiteralExpression>moduleNameExpr).text);
            }
        }
        else if (node.kind === ts.SyntaxKind.ModuleDeclaration && (<ts.ModuleDeclaration>node).name.kind === ts.SyntaxKind.StringLiteral) {
            // Ambient module declaration
            getImports((<ts.ModuleDeclaration>node).body, importedModules);
        }
    });
}

function getExternalModuleName(node: ts.Node): ts.Expression {
    if (node.kind === ts.SyntaxKind.ImportDeclaration) {
        return (<ts.ImportDeclaration>node).moduleSpecifier;
    }
    if (node.kind === ts.SyntaxKind.ImportEqualsDeclaration) {
        let reference = (<ts.ImportEqualsDeclaration>node).moduleReference;
        if (reference.kind === ts.SyntaxKind.ExternalModuleReference) {
            return (<ts.ExternalModuleReference>reference).expression;
        }
    }
    if (node.kind === ts.SyntaxKind.ExportDeclaration) {
        return (<ts.ExportDeclaration>node).moduleSpecifier;
    }
}
```

Please note that in both cases, these are just text, i.e. module names, and file names. they are not resolved to an actual module symbol, and they are not resolved to a full file path, and may or may not exist on disk. I would need to know more about the scenario you are trying to achieve to be able to better help you.

@ToddThomson, If i understood correctly, a helper function that given a source file will give you the list of module imports should meet your needs. is this accurate?

**Comment by ToddThomson** [comment]
@mhegazy I'm not interested in the names of the module imports. I want the whole source file dependency tree for a given source file. This is currently done in createProgram(). Unfortunately ( from my read of the source code ) the information is not stored as you find and process dependent source files. Since you already do all the work in createProgram(), it is hardly any additional code to keep an array of top level dependent files ( of type SourceFile ).for each source file.
The reason I need this is to be able to bundle modules at compile time. I realize that this could be done further down in the build pipeline, but I want to have the option of driving bundling from the tsconfig.json file.

**Comment by basarat** [comment]
This can be closed from my side. Thanks :rose:

**Comment by ToddThomson** [comment]
@mhegazy I wrote a quick Dependency Walker class based on a subset of ts.program to verify I could get the desired top level ts.SourceFile dependencies for a given source file.
Within ts.processImportedModules() all you need to do is capture the returned SourceFile from findModuleSourceFile() and then push it to a (new) property ( ImportedFiles perhaps ) of the current file. 
This additional property of ts.SourceFile would be consistent with ts.SourceFile.ReferencedFiles .
What do you think?

**Comment by mhegazy** [comment]
The program would not be the right place for that. The program does a pre-process step to figure out *possible* import dependencies. Imports can be to ambient module declarations coming for .d.ts. Note that a missing dependency in this phase is not considered an error (vs. triple-slash reference). The actual dependency check will happen later on when we resolve the module import in the checker (see resolveExternalModuleName).

This difference is why we do not keep them in a list at parse/pre-process time. I think this can be a utility function that lives off the checker though.

**Comment by ToddThomson** [comment]
@mhegazy  - along the lines of  - checker = { ..., getImportsOfModule: getImportsOfModuleAsArray } . checker is not something I've used yet. How would I go about accessing this possible function for a given source file?
Is this something that could be part of the 1.5 release?
I have a working dependency walker based off the ts.program code which provides me with an array of  dependent SourceFiles so I can move forward with what I've got now.

**Comment by mhegazy** [comment]
here is an example that would priint the modules imported from a file:

```ts
import * as ts from "typescript";

function getExternalModuleName(node: ts.Node): ts.Expression {
    if (node.kind === ts.SyntaxKind.ImportDeclaration) {
        return (<ts.ImportDeclaration>node).moduleSpecifier;
    }
    if (node.kind === ts.SyntaxKind.ImportEqualsDeclaration) {
        let reference = (<ts.ImportEqualsDeclaration>node).moduleReference;
        if (reference.kind === ts.SyntaxKind.ExternalModuleReference) {
            return (<ts.ExternalModuleReference>reference).expression;
        }
    }
    if (node.kind === ts.SyntaxKind.ExportDeclaration) {
        return (<ts.ExportDeclaration>node).moduleSpecifier;
    }
}

function getDependencies(sourceFile: ts.SourceFile, checker: ts.TypeChecker) {
    let output: ts.Symbol[] = [];
    ts.forEachChild(sourceFile, node => {
        // Vist top-level import nodes
        if (node.kind === ts.SyntaxKind.ImportDeclaration || node.kind === ts.SyntaxKind.ImportEqualsDeclaration || node.kind === ts.SyntaxKind.ExportDeclaration) {
            let moduleNameExpr = getExternalModuleName(node);
            // if they have a name, that is a string, i.e. not alias defition `import x = y`
            if (moduleNameExpr && moduleNameExpr.kind === ts.SyntaxKind.StringLiteral) {
                // Ask the checker about the "symbol: for this module name
                // it would be undefined if the module was not found (i.e. error)
                let moduleSymbol = checker.getSymbolAtLocation(moduleNameExpr);
                if (moduleSymbol) {
                    output.push(moduleSymbol);
                }
            }
        }
    });
    return output;
}

let fileNames = process.argv.slice(2);
var program = ts.createProgram(fileNames, { module: ts.ModuleKind.CommonJS });
program.getSourceFiles().forEach(sourceFile => {
    console.log(`Imported sourceFiles for ${sourceFile.fileName }:`);
    getDependencies(sourceFile, program.getTypeChecker()).forEach(importSymbol => {
        // Now that you have a symbol, get the declaration to find out which
        // source file it is comming from.
        let declaration = importSymbol.getDeclarations()[0];

        // This might be helpful if you are doing bundelling, you would want to
        // know if this comming from a .d.ts e.g. `declare module "typescript`
        // or a real source file (.ts).
        let isCodeModule = declaration.kind === ts.SyntaxKind.SourceFile &&
            !(declaration.flags & ts.NodeFlags.DeclarationFile);

        console.log(`   + ${ declaration.getSourceFile().fileName }  (isCodeModule = ${isCodeModule})`);
    });
});
```

hope that helps.

**Comment by ToddThomson** [comment]
@mhegazy Thank-you. I appreciate your time and guidance.
Essentially the difference between processImportedModules() in program and your getDependencies() above is that getDependencies() utilizes checker.getSymbolAtLocation rather than host.getSourceFile().
There doesn't seem to be much difference, but I guess I don't have do my own error checking and there is additional information by obtaining symbol. I'll rewrite my dependency walker based on using checker.
Many thanks to the team on the outstanding 1.5 release!

**Comment by mhegazy** [comment]
thank you @ToddThomson. glad that helped.

**Comment by joaompneves** [comment]
I did a simple node CLI that is able to capture the dependencies between typescript modules and also produce a UML diagram from the modules and classes.
Check out [here](https://github.com/joaompneves/tsviz).
Any contributions are welcome.
