### ISSUE TITLE
Parse/Generate call signature with keeping argument name

### ISSUE THREAD

**Issue by whatasoda** [microsoft/TypeScript#26225]
I want to do like this.
![image](https://user-images.githubusercontent.com/20302152/43710868-dd8e2404-99ab-11e8-83af-128db9aa3a0f.png)

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by AlCalzone** [comment]
This would be very helpful when combined with #26190 as we could fix the problem that the inferred parameter names are off by one there.

**Comment by ahejlsberg** [comment]
Seems to me this can be accomplished using `ReturnType<T>` (added to lib.d.ts in 3.0) and the `Parameters<T>` type I suggest here https://github.com/Microsoft/TypeScript/pull/24897#issuecomment-397463626. The only one thing we don't support is extracting the parameter names, but that doesn't appear to be significant in the example.

**Comment by jedmao** [comment]
@ahejlsberg the `Parameters<T>` type doesn't preserve the original argument names or TSDoc comments. I think what @whatasoda wants is very similar to the new feature request I just created #30351.
