### ISSUE TITLE
If the `await` statement is not used in `async function`, the user can be prompted to remove the `async` modifier.

### ISSUE THREAD

**Issue by u3u** [Microsoft/TypeScript#26222]
## Search Terms

- async function
- async / await

## Suggestion

If the `await` statement is not used in `async function`, the user can be prompted to remove the `async` modifier. This can reduce unnecessary compilation and file size.

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by AlCalzone** [comment]
I believe this is a duplicate of https://github.com/Microsoft/TypeScript/issues/22024
Sadly there does not seem much love for a rule like this (https://github.com/fimbullinter/wotan/issues/80 or https://github.com/eslint/eslint/issues/10000) although it can lead to runtime erros like in my case.

**Comment by j-oliveras** [comment]
Without async, can not be the same:
```ts
function testNoAsync() {
    if (Math.random() < 0.5) throw new Error();

    return Promise.reject(2);
}

async function testAsync() {
    if (Math.random() < 0.5) throw new Error();

    return Promise.reject(2);
}

function test() {
    try {
        testNoAsync().
            catch(() => { }); // This catch the reject
    } catch (err) {
        // This catch the throw
    }

    testAsync().
        catch(() => { }); // This catch both (throw and reject)
}
```
[At playground](https://www.typescriptlang.org/play/#src=function%20testNoAsync()%20%7B%0D%0A%20%20%20%20if%20(Math.random()%20%3C%200.5)%20throw%20new%20Error()%3B%0D%0A%0D%0A%20%20%20%20return%20Promise.reject(2)%3B%0D%0A%7D%0D%0A%0D%0Aasync%20function%20testAsync()%20%7B%0D%0A%20%20%20%20if%20(Math.random()%20%3C%200.5)%20throw%20new%20Error()%3B%0D%0A%0D%0A%20%20%20%20return%20Promise.reject(2)%3B%0D%0A%7D%0D%0A%0D%0Afunction%20test()%20%7B%0D%0A%20%20%20%20try%20%7B%0D%0A%20%20%20%20%20%20%20%20testNoAsync().%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20catch(()%20%3D%3E%20%7B%20%7D)%3B%20%2F%2F%20This%20only%20catch%20the%20reject%0D%0A%20%20%20%20%7D%20catch%20(err)%20%7B%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20This%20catch%20the%20throw%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20testAsync().%0D%0A%20%20%20%20%20%20%20%20catch(()%20%3D%3E%20%7B%20%7D)%3B%20%2F%2F%20This%20catch%20both%20(throw%20and%20reject)%0D%0A%7D).
