### ISSUE TITLE
TS5071 error fires when using mode="esnext", but builds were fine before 3.0.1

### ISSUE THREAD

**Issue by jpike88** [Microsoft/TypeScript#26224]
**TypeScript Version:**  3.0.1

**Search Terms:**
TS5071

**Code**

https://github.com/Microsoft/TypeScript/blob/d8cbe34a051a64d39f55f4e46e18ac404aac922e/src/compiler/diagnosticMessages.json#L2887

**Expected behavior:**
This should work fine with mode="esnext" just like it always did.

**Actual behavior:**
I've been using the following tsconfig.json file with zero issues before upgrading to 3.0:

`{
  "compileOnSave": true,
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "sourceMap": true,
    "declaration": true,
    "declarationDir": "../decl",
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "noUnusedLocals": true,
    "resolveJsonModule": true,
    "noUnusedParameters": true,
    "skipLibCheck":true,
    "outDir":"../dist/",
    "typeRoots" : ["../node_modules/@types"]
  },
  "exclude":["../node_modules/@types/"]
}
`
Now this error message is firing, but the resolution and import of json files work fine when module is set to esnext. Switching mode to commonjs breaks my import syntax, modules are missing left right and center.

@sheetalkamat, could you help give insight on this?

**Comment by 19majkel94** [comment]
I have the same problem - this error is not listed in breaking changes:
https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes

So I think it should be changed as TS 2.9.1 worked well with `resolveJsonModule` using `esnext` and webpack.

**Comment by sheetalkamat** [comment]
--resolveJsonModule is supported only when using nodejs module resolution and emit is commonjs. In other systems json module is not supported natively without any plugins and hence the error. The check for emit was missing earlier rather than intentional allowing it (so your code was always error but we missed on reporting errors on it before)

**Comment by jpike88** [comment]
@sheetalkamat  If my code functioned correctly before this error check was implemented, didn't it technically already support it before this error check existed? Theres nothing funky with my code, it's standard esnext syntax with _allowSyntheticDefaultImports_ enabled. Why should I be forced to downgrade to commonjs (it's a downgrade as far as I'm concerned) when it was working perfectly fine before?

**Comment by wizardnet972** [comment]
@sheetalkamat, any idea how to resolve my json file without the extension? i'm using vscode+typescript.
`import jsonData from './file'`. but I got this error: ` [ts] Cannot find module './file'`.

`resolveJsonModule` is true in my tsconfig..

**Comment by sheetalkamat** [comment]
You have to explicitly use .json in the module specifier to be able to resolve to a json module. We have this constraint so that the json files don't get included without intentionally choosing to for those specific module specifiers

**Comment by wizardnet972** [comment]
I see. @sheetalkamat thank you :)
