### ISSUE TITLE
Using inferred return type of function as argument to same function breaks type inference

### ISSUE THREAD

**Issue by AnyhowStep** [Microsoft/TypeScript#26228]
**TypeScript Version:**  3.0.1

**Search Terms:** return type inference

**Code**

My specific instance of this problem can be found [here](https://github.com/AnyhowStep/schema-decorator/blob/f5a3d13aed658ab4771be8751a59ab20f783cbe6/src/main/schema.ts)
Scroll to the very bottom to see a comment about it.

I couldn't figure out a minimal example but it looks like,

```ts
const result1 = foo(/*arg*/); //Inferred type is correct
const result2 = foo(result1); //Inferred type is wrong; shows `any`
```

However, if I explicitly declare the type of `result1`, it works,

```ts
const result1 : number = foo(/*arg*/); //Explicitly declared
const result2 = foo(result1); //Inferred type is correct
```

Or, if I do this very weird thing,

```ts
//Both foo1<>() and foo2<>() are the same, I just copy pasted foo<>() and renamed
declare function foo1</*Complicated Type*/> (/*Params*/) : /*Complicated Type*/;
declare function foo2</*Complicated Type*/> (/*Params*/) : /*Complicated Type*/;

const result1 = foo1(/*arg*/); //Inferred type is correct
const result2 = foo2(result1); //Inferred type is correct
```

Trying a type alias fails,

```ts
declare function foo</*Complicated Type*/> (/*Params*/) : /*Complicated Type*/;
type FooDelegate = </*Complicated Type*/>(/*Params*/) => /*Complicated Type*/;

const foo1 : FooDelegate = foo;
const foo2 : FooDelegate = foo;

const result1 = foo1(/*arg*/); //Inferred type is correct
const result2 = foo2(result1); //Inferred type is wrong; shows any
```

But this also works,

```ts
declare function foo</*Complicated Type*/> (/*Params*/) : /*Complicated Type*/;

const foo1 : </*Complicated Type*/>(/*Params*/) => /*Complicated Type*/ = foo;
const foo2 : </*Complicated Type*/>(/*Params*/) => /*Complicated Type*/ = foo;

const result1 = foo1(/*arg*/); //Inferred type is correct
const result2 = foo2(result1); //Inferred type is correct
```

It seems like if I rely on return type inference, I have to copy-paste the function type, and cannot re-use a previous declaration.

So, if I wanted to nest the results 4 times, I'd need `foo1, foo2, foo3, foo4`

Right now, I just either declare the return-type explicitly, every time the function is used, or I don't use the function at all.

**Expected behavior:**

Inferred type to not have `any`

**Actual behavior:**

Inferred type contains `any`

**Comment by RyanCavanaugh** [comment]
Can you boil this down to a standalone example? Just trimming down things from the linked file until there's nothing that doesn't need to be there should be enough. Thanks!

**Comment by AnyhowStep** [comment]
It took me forever, but I finally found a minimal example,

```ts
type AssertDelegate<T> = (name: string, mixed: unknown) => T;
class Field<NameT extends string, AssertT extends AssertDelegate<any>> {
    constructor(
        readonly name: NameT,
        readonly assertDelegate : AssertT
    ) {}
}
type TypeOf<FieldT extends Field<any, any>> = (
    ReturnType<FieldT["assertDelegate"]>
);
declare function schema<FieldT extends Field<any, any>> (fields : FieldT) : (
    AssertDelegate<{
        [k in FieldT["name"]] : TypeOf<FieldT>
    }>
);

declare const assertBoolean: AssertDelegate<boolean>;
const obj = schema(
    new Field("z", assertBoolean)
);
const objField = new Field("obj", obj);
//Incorrect;
//AssertDelegate<{ obj: any; }>
const actualTypeOfNested = schema(
    objField
);

//OK;
//(name: string, mixed: unknown) => { obj: { z: boolean; }; }
//Or,
//AssertDelegate<{ obj: { z: boolean; }; }>
type expectedTypeOfNested = AssertDelegate<{
    [k in typeof objField["name"]] : TypeOf<typeof objField>
}>

//COPY PASTE of schema<>()
declare function schema2<FieldT extends Field<any, any>> (fields : FieldT) : (
    AssertDelegate<{
        [k in FieldT["name"]] : TypeOf<FieldT>
    }>
);
//OK;
//AssertDelegate<{ obj: { z: boolean; }; }>
//WTF?
const actualTypeOfNested2 = schema2(
    objField
);

//I swear there is some kind of short-circuiting happening here.
//Oh, you are trying to call `foo(foo(/*arg*/))`?
//I'm too lazy, I'll just say the return type is `any`.
//But if you copy-paste and make it,
//`foo2(foo(/*arg*/))`,
//TS goes, "Oh, okay, it's extra work but I'll do it properly"
```

[TS Playground link](http://www.typescriptlang.org/play/#src=type%20AssertDelegate%3CT%3E%20%3D%20(name%3A%20string%2C%20mixed%3A%20unknown)%20%3D%3E%20T%3B%0Aclass%20Field%3CNameT%20extends%20string%2C%20AssertT%20extends%20AssertDelegate%3Cany%3E%3E%20%7B%0A%20%20%20%20constructor(%0A%20%20%20%20%20%20%20%20readonly%20name%3A%20NameT%2C%0A%20%20%20%20%20%20%20%20readonly%20assertDelegate%20%3A%20AssertT%0A%20%20%20%20)%20%7B%7D%0A%7D%0Atype%20TypeOf%3CFieldT%20extends%20Field%3Cany%2C%20any%3E%3E%20%3D%20(%0A%20%20%20%20ReturnType%3CFieldT%5B%22assertDelegate%22%5D%3E%0A)%3B%0Adeclare%20function%20schema%3CFieldT%20extends%20Field%3Cany%2C%20any%3E%3E%20(fields%20%3A%20FieldT)%20%3A%20(%0A%20%20%20%20AssertDelegate%3C%7B%0A%20%20%20%20%20%20%20%20%5Bk%20in%20FieldT%5B%22name%22%5D%5D%20%3A%20TypeOf%3CFieldT%3E%0A%20%20%20%20%7D%3E%0A)%3B%0A%0Adeclare%20const%20assertBoolean%3A%20AssertDelegate%3Cboolean%3E%3B%0Aconst%20obj%20%3D%20schema(%0A%20%20%20%20new%20Field(%22z%22%2C%20assertBoolean)%0A)%3B%0Aconst%20objField%20%3D%20new%20Field(%22obj%22%2C%20obj)%3B%0A%2F%2FIncorrect%3B%0A%2F%2FAssertDelegate%3C%7B%20obj%3A%20any%3B%20%7D%3E%0Aconst%20actualTypeOfNested%20%3D%20schema(%0A%20%20%20%20objField%0A)%3B%0A%0A%2F%2FOK%3B%0A%2F%2F(name%3A%20string%2C%20mixed%3A%20unknown)%20%3D%3E%20%7B%20obj%3A%20%7B%20z%3A%20boolean%3B%20%7D%3B%20%7D%0A%2F%2FOr%2C%0A%2F%2FAssertDelegate%3C%7B%20obj%3A%20%7B%20z%3A%20boolean%3B%20%7D%3B%20%7D%3E%0Atype%20expectedTypeOfNested%20%3D%20AssertDelegate%3C%7B%0A%20%20%20%20%5Bk%20in%20typeof%20objField%5B%22name%22%5D%5D%20%3A%20TypeOf%3Ctypeof%20objField%3E%0A%7D%3E%0A%0A%2F%2FCOPY%20PASTE%20of%20schema%3C%3E()%0Adeclare%20function%20schema2%3CFieldT%20extends%20Field%3Cany%2C%20any%3E%3E%20(fields%20%3A%20FieldT)%20%3A%20(%0A%20%20%20%20AssertDelegate%3C%7B%0A%20%20%20%20%20%20%20%20%5Bk%20in%20FieldT%5B%22name%22%5D%5D%20%3A%20TypeOf%3CFieldT%3E%0A%20%20%20%20%7D%3E%0A)%3B%0A%2F%2FOK%3B%0A%2F%2FAssertDelegate%3C%7B%20obj%3A%20%7B%20z%3A%20boolean%3B%20%7D%3B%20%7D%3E%0A%2F%2FWTF%3F%0Aconst%20actualTypeOfNested2%20%3D%20schema2(%0A%20%20%20%20objField%0A)%3B%0A%0A%2F%2FI%20swear%20there%20is%20some%20kind%20of%20short-circuiting%20happening%20here.%0A%2F%2FOh%2C%20you%20are%20trying%20to%20call%20%60foo(foo(%2F*arg*%2F))%60%3F%0A%2F%2FI'm%20too%20lazy%2C%20I'll%20just%20say%20the%20return%20type%20is%20%60any%60.%0A%2F%2FBut%20if%20you%20copy-paste%20and%20make%20it%2C%0A%2F%2F%60foo2(foo(%2F*arg*%2F))%60%2C%0A%2F%2FTS%20goes%2C%20%22Oh%2C%20okay%2C%20it's%20extra%20work%20but%20I'll%20do%20it%20properly%22)

**Comment by AnyhowStep** [comment]
I just played with it a bit more.

```ts
declare function schema<T> (value : T) : (
    {
        field : T
    }
);

declare const b: boolean;
//OK;
//Inferred { field : boolean }
const obj = schema(b);
//Incorrect;
//Inferred { field : any }
//Expected { field : { field : boolean } }
const actualTypeOfNested = schema(obj);

//Gives an error, as expected,
//Type 'boolean' is not assignable to type 'number'
const n: number = actualTypeOfNested.field.field;
//OK
const b2: boolean = actualTypeOfNested.field.field;

//Gives an error, as expected,
//Type 'boolean' is not assignable to type 'number'
const notAssignable: { field: { field: number } } = actualTypeOfNested;
//OK
const assignable: { field: { field: boolean } } = actualTypeOfNested;
```

[TS Playground link](http://www.typescriptlang.org/play/#src=declare%20function%20schema%3CT%3E%20(value%20%3A%20T)%20%3A%20(%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20field%20%3A%20T%0A%20%20%20%20%7D%0A)%3B%0A%0Adeclare%20const%20b%3A%20boolean%3B%0A%2F%2FOK%3B%0A%2F%2FInferred%20%7B%20field%20%3A%20boolean%20%7D%0Aconst%20obj%20%3D%20schema(b)%3B%0A%2F%2FIncorrect%3B%0A%2F%2FInferred%20%7B%20field%20%3A%20any%20%7D%0A%2F%2FExpected%20%7B%20field%20%3A%20%7B%20field%20%3A%20boolean%20%7D%20%7D%0Aconst%20actualTypeOfNested%20%3D%20schema(obj)%3B%0A%0A%2F%2FGives%20an%20error%2C%20as%20expected%2C%0A%2F%2FType%20'boolean'%20is%20not%20assignable%20to%20type%20'number'%0Aconst%20n%3A%20number%20%3D%20actualTypeOfNested.field.field%3B%0A%2F%2FOK%0Aconst%20b2%3A%20boolean%20%3D%20actualTypeOfNested.field.field%3B%0A%0A%2F%2FGives%20an%20error%2C%20as%20expected%2C%0A%2F%2FType%20'boolean'%20is%20not%20assignable%20to%20type%20'number'%0Aconst%20notAssignable%3A%20%7B%20field%3A%20%7B%20field%3A%20number%20%7D%20%7D%20%3D%20actualTypeOfNested%3B%0A%2F%2FOK%0Aconst%20assignable%3A%20%7B%20field%3A%20%7B%20field%3A%20boolean%20%7D%20%7D%20%3D%20actualTypeOfNested%3B%0A)

So, it looks like the tooltip that gives the type inference is short-circuiting or something and just giving `any`. But the actual type checking still goes all the way.

So, it seems like it's somewhat related to https://github.com/Microsoft/TypeScript/issues/26238

In TS 3.0.1 with VS code, all of a sudden, the tooltip that's supposed to give the inferred type is truncating text, and it looks like it also gives `any` with nested calls to the same function.

Is there any way I can get it to just display the full type truthfully, without it truncating, or giving up and displaying `any`? It's kind of a productivity killer when I have to second-guess the tools. They're telling me it's one thing but I check and it's another.

**Comment by RyanCavanaugh** [comment]
> Is there any way I can get it to just display the full type truthfully, without it truncating, or giving up and displaying any?

Fix bugs in the compiler 😉

**Comment by AnyhowStep** [comment]
I've tried to look at the source code a few times, cursory glances only, and it just goes over my head. Hopefully I can figure this all out at some point.
