### ISSUE TITLE
Auto completion for numeric literals as generic type arguments selects unwanted items

### ISSUE THREAD

**Issue by AlCalzone** [Microsoft/TypeScript#26230]
**TypeScript Version:**  3.1.0-dev.20180802

**Search Terms:** numeric literal auto completion 

**Code**

```ts
type Foo<T, U> = T | U;
type Bar = Foo</* cursor here */
```
At the highlighted cursor location, type `1,`

**Expected behavior:**
```ts
type Foo<T, U> = T | U;
type Bar = Foo<1,
```
**Actual behavior:**
```ts
import { SSL_OP_NO_TLSv1_1 } from "constants";
// ^-- somewhere... over the rainbow

// v-- miles below:
type Foo<T, U> = T | U;
type Bar = Foo<SSL_OP_NO_TLSv1_1,
```

**Related Issues:** none

**Comment by AlCalzone** [comment]
> What editor are you using?

VSCode in the newest non-insider version.

**Comment by andy-ms** [comment]
I'm having some trouble getting the correction to happen in vscode, but I've noticed these things can sometimes depend on state. Pinging @mjbvz -- I think vscode should accept numbers as valid and not correct them.

**Comment by AlCalzone** [comment]
For what its worth, I can reproduce it reliably:

1. clone https://github.com/AlCalzone/shared-utils/
2. open src/types.ts, go to the end
3. do the steps I posted in the OP

**Comment by andy-ms** [comment]
@mjbvz Could you take a look?

**Comment by mjbvz** [comment]
Should be fixed in the next vs code insiders when triggering intellisense in cases like `T<1|`. We still show this suggestions if you trigger intellisense for `T<|` and then type `1`. This is consistent with how VS Code's intellisense filtering works

**Comment by AlCalzone** [comment]
@mjbvz This sounds like the case I described in the OP will stay as-is? Meaning if there can be an auto-import for `SSL_OP_NO_TLSv1_1` and similar and I want to use 1 as a literal type for a generic, it will auto-complete the constant.
