### ISSUE TITLE
proposal:rest infer

### ISSUE THREAD

**Issue by kgtkr** [Microsoft/TypeScript#26246]
## Search Terms
Generics

## Suggestion
Decomposition of tuple type

## Examples
```ts
type Hoge<T extends any[]> = T extends [infer X, ...infer XS] ? X | Hoge<XS> : never;
```

There is a problem of #14174 

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by JakeTunaley** [comment]
For anyone who needs a workaround for this today, you can use function types and [TypeScript 3.0 rest tuples](tuples-in-rest-parameters-and-spread-expressions):

```ts
type Tail<T extends any[]> = ((...args: T) => any) extends ((head: any, ...tail: infer U) => any) ? U : never;
```

**Comment by kgtkr** [comment]
I did not know how to solve it

Is this correct?
```ts
type ToObj<T extends any[]> = ((...args: T) => any) extends ((head: infer X, ...tail: infer XS) => any) ? { x: X, xs: ToObj<XS> } : [];
type Foo = ToObj<[1, 2, 3, 4, 5]>;//{x: 1;xs: any;}
```

**Comment by AlCalzone** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/25719 ?

**Comment by RyanCavanaugh** [comment]
It's not clear what problem you're trying to solve here. The suggestion template has many more fields and it'd be great if you could fill them in completely -- just showing some syntax you'd expect to work doesn't give us enough context on what you'd like to happen, how you'd expect it to work, or reasons why this would be a good addition to the language. Thanks!

**Comment by kgtkr** [comment]
Close this issue because it is a duplicate
