### ISSUE TITLE
Issues with getting the typings correctly

### ISSUE THREAD

**Issue by pikax** [Microsoft/TypeScript#26252]
**TypeScript Version:**  3.1.0-dev.20180807

**Search Terms:**
Extend functions 
Generic
Auto-complete
Template

**Code**

```ts
type MapFuncs<T, Key extends keyof T = keyof T> = { [K in Key]: Funcs<T[K]> };

type Funcs<T> = 
    T extends ()=> infer R ? R :
    T extends (...args: any[]) => infer R ? T : //  1 or more arguments 
    T;

interface PocFuncType {
    n: number,
    c: () => number;
    x:  (s: string) => number;
}

const f: MapFuncs<PocFuncType> = {} as any;

f.c; // returns number as expected
f.n; // returns number as expected
f.x; // return function as expected 

// is working as expected, but if we try to use it, it doesnt resolve the type correctly
type MyType<T> = {
    computed?: MapFuncs<T>
};

// factory
function create<T>(options?: MyType<T>){
    return null;
}

// it works we set the type
create<Partial<PocFuncType>>({
    computed: {
        c: 1,

        x(s) {
            if(!this.c){
                return 0
            }
            return this.c;
        },
    }
})

// it sets the {computed?: mapFuncs<any>}
create({
    // doesn't pick up the correct types, is setting as any
    computed:{
        data(){
            return 1;
        },
        dataReturn (){
            return this.data; // data is any, it should be number
        }

    }
})


create<Partial<PocFuncType>>({
    computed: {
        c: 1,

         x(s) {
            if(!this.c){
                return 0
            }
            return this.r; // invalid prop r, doesn't exist
        },
    }
})

```

**Expected behavior:**
`this.data` in `dataReturn()` should be interpreted as `number` based on the `Funcs<T>` type.

`return this.r; ` should throw an error **Cannot find name 'r'**

**Actual behavior:**
`this.data` is interpreted different depending on the IDE (not sure if this is typescript compiler issue)
- Playground : `this` is any
- Visual Studio Code: `this` is resolve correctly but the props are all any making not as usefull
- Webstorm: just ignores `Funcs<T>` 

`return this.r` compiler doesn't complain about it, even if it doesn't exist on the type.

**Playground Link:** 
[playground](https://www.typescriptlang.org/play/index.html#src=type%20MapFuncs%3CT%2C%20Key%20extends%20keyof%20T%20%3D%20keyof%20T%3E%20%3D%20%7B%20%5BK%20in%20Key%5D%3A%20Funcs%3CT%5BK%5D%3E%20%7D%3B%0D%0A%0D%0Atype%20Funcs%3CT%3E%20%3D%20%0D%0A%20%20%20%20T%20extends%20()%3D%3E%20infer%20R%20%3F%20R%20%3A%0D%0A%20%20%20%20T%20extends%20(...args%3A%20any%5B%5D)%20%3D%3E%20infer%20R%20%3F%20T%20%3A%20%2F%2F%20%201%20or%20more%20arguments%20%0D%0A%20%20%20%20T%3B%0D%0A%0D%0Ainterface%20PocFuncType%20%7B%0D%0A%20%20%20%20n%3A%20number%2C%0D%0A%20%20%20%20c%3A%20()%20%3D%3E%20number%3B%0D%0A%20%20%20%20x%3A%20%20(s%3A%20string)%20%3D%3E%20number%3B%0D%0A%7D%0D%0A%0D%0Aconst%20f%3A%20MapFuncs%3CPocFuncType%3E%20%3D%20%7B%7D%20as%20any%3B%0D%0A%0D%0Af.c%3B%20%2F%2F%20returns%20number%20as%20expected%0D%0Af.n%3B%20%2F%2F%20returns%20number%20as%20expected%0D%0Af.x%3B%20%2F%2F%20return%20function%20as%20expected%20%0D%0A%0D%0A%2F%2F%20is%20working%20as%20expected%2C%20but%20if%20we%20try%20to%20use%20it%2C%20it%20doesnt%20resolve%20the%20type%20correctly%0D%0Atype%20MyType%3CT%3E%20%3D%20%7B%0D%0A%20%20%20%20computed%3F%3A%20MapFuncs%3CT%3E%0D%0A%7D%3B%0D%0A%0D%0A%2F%2F%20factory%0D%0Afunction%20create%3CT%3E(options%3F%3A%20MyType%3CT%3E)%7B%0D%0A%20%20%20%20return%20null%3B%0D%0A%7D%0D%0A%0D%0A%2F%2F%20it%20works%20we%20set%20the%20type%0D%0Acreate%3CPartial%3CPocFuncType%3E%3E(%7B%0D%0A%20%20%20%20computed%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20c%3A%201%2C%0D%0A%0D%0A%20%20%20%20%20%20%20%20x(s)%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20if(!this.c)%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20return%200%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20this.c%3B%0D%0A%20%20%20%20%20%20%20%20%7D%2C%0D%0A%20%20%20%20%7D%0D%0A%7D)%0D%0A%0D%0A%2F%2F%20it%20sets%20the%20%7Bcomputed%3F%3A%20mapFuncs%3Cany%3E%7D%0D%0Acreate(%7B%0D%0A%20%20%20%20%2F%2F%20doesn't%20pick%20up%20the%20correct%20types%2C%20is%20setting%20as%20any%0D%0A%20%20%20%20computed%3A%7B%0D%0A%20%20%20%20%20%20%20%20data()%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20return%201%3B%0D%0A%20%20%20%20%20%20%20%20%7D%2C%0D%0A%20%20%20%20%20%20%20%20dataReturn%20()%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20this.data%3B%20%2F%2F%20data%20is%20any%2C%20it%20should%20be%20number%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20%7D%0D%0A%7D)%0D%0A%0D%0A%0D%0Acreate%3CPartial%3CPocFuncType%3E%3E(%7B%0D%0A%20%20%20%20computed%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20c%3A%201%2C%0D%0A%0D%0A%20%20%20%20%20%20%20%20%20x(s)%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20if(!this.c)%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20return%200%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20this.r%3B%20%2F%2F%20invalid%20prop%20r%2C%20doesn't%20exist%0D%0A%20%20%20%20%20%20%20%20%7D%2C%0D%0A%20%20%20%20%7D%0D%0A%7D)%0D%0A%0D%0A)

**Related Issues:**

**Comment by andy-ms** [comment]
In a simplified test case:
```ts
type MapFuncs<T> = { [K in keyof T]: Funcs<T[K]> };
type Funcs<T> = T extends () => infer R ? R : T;

declare function create<T>(options?: MapFuncs<T>): T;

create({
    data() { return 1; },
    dataReturn() { return this.data * 2; },
});
```
What do you expect the inferred type argument for the `create` call to be? We can't use `{ data(): number, dataReturn(): number }` because `Funcs<T>` will turn that into just `number`.

**Comment by pikax** [comment]
> What do you expect the inferred type argument for the create call to be?
I expect `Funcs<T>` to convert the methods to be the result type if is a method without arguments: `{ data: number, dataReturn: number}`

on the case of: 
```ts 
create({
    data() { return 1; },
    dataReturn() { return this.data * 2; },
    calculate(a: number, b: number){
      return a+b;
   }
});

// expect: { data: number, dataReturn: number, calculate: (a: number, b:number)=>number }
```

A practical example of this is VueJs when using `Vue.extend(options?)`


Other thing is the compiler doesn't throw error:
```ts
create({
    data() { return  this.empty; }, // empty doesn't exist nor is defined
});
```

**Comment by andy-ms** [comment]
@pikax You probably don't have `"strict": true` set in your tsconfig, so `this` is allowed to be `any`.

Based on what you're saying it sounds like you have the parameter and return type reversed? You also need to set `ThisType` if `this` is the type of the returned object and not the type of the parameter object.
```ts
type MapFuncs<T> = { [K in keyof T]: Funcs<T[K]> };
type Funcs<T> = T extends () => infer R ? R : T;

declare function create<T>(options?: T & ThisType<MapFuncs<T>>): MapFuncs<T>;

const x = create({
    data() { return 1; },
    dataReturn(): number { return this.data * 2; },
});
x.data * x.dataReturn; // works
```

**Comment by pikax** [comment]
> @pikax You probably don't have "strict": true set in your tsconfig, so this is allowed to be any.
Sorry, forget using `tsc index.ts` doesn't use the tsconfig

That seems to be work, thank you, is there any documentation for `ThisType` and other interfaces?

**Comment by andy-ms** [comment]
Microsoft/TypeScript-Handbook#649
