### ISSUE TITLE
Inference inconsistency with string keys

### ISSUE THREAD

**Issue by yortus** [Microsoft/TypeScript#26257]
**TypeScript Version:**  3.1.0-dev.20180807

**Search Terms:**
string index inference, string key inference

**Code**

```ts
const SYM = Symbol();
type StringProps1<T> = T extends {[x: string]: infer U} ? U : never;
type StringProps2<T> = T extends {[K in Extract<keyof T, string>]: infer U} ? U : never;

type T1 = StringProps1<{a: 'aaa', [SYM]: 'sym'}>;   // T1 = 'aaa' | 'sym'
type T2 = StringProps2<{a: 'aaa', [SYM]: 'sym'}>;   // T2 = 'aaa'
```

**Expected behavior:**
I expected `StringProps1` and `StringProps2` to mean the same thing (infer from just the string keys).

Accordingly, `T1` and `T2` would both inferred as `'aaa'`, both excluding the symbol key.

**Actual behavior:**

`T2` excludes the symbol key as expected, but `T1` includes it, as shown in the code comments.

Even if `StringProps1` and `StringProps2` did have subtly different meanings, it doesn't seem logical to include the `[SYM]: 'sym'` as part of the string indexer, since it doesn't belong there.

**Related Issues:**

This is a simpler repro of #26183, although that issue shows its nothing specific to conditional types. It seems to be just how string indexers work with type inference.

The search terms above brought up #25065 and #24560, but they don't look like the same issue.

**Comment by ahejlsberg** [comment]
This is working as intended. A string index signature places a constraint on _every_ property of a type, regardless of what kind of name it has. I agree the name "string index signature" is a bit unfortunate as it affects properties that might have numeric or symbol names, but the name predates our support for those kinds of names. It would definitely be a breaking change to modify our behavior here.

**Comment by yortus** [comment]
Oh right. I just assumed the strings and symbols were separated out as part of #23592 (and the breaking change taken there).

So what about this third variation, is it also working as intended?
```ts
const SYM = Symbol();
type StringProps3<T> = T extends {[K in string]: infer U} ? U : never;
type T3 = StringProps3<{a: 'aaa', [SYM]: 'sym'}>;   // T2 = 'aaa' | 'sym'
```

The `K` in that mapped type is also picking up the symbol key, so `K in string` is including non-string values.

**Comment by yortus** [comment]
For context, the following code is a cut-down repro of what I'm trying to do, but I can't figure out what's going on with the compiler. [Playground link.](http://www.typescriptlang.org/play/index.html#src=%2F%2F%20function%20foo%20takes%20an%20'options'%20object%20that%20can%20have%3A%0D%0A%2F%2F%20(a)%20any%20number%20of%20string%20keys%20whose%20values%20are%20unary%20functions%20(infer%20the%20arg%20and%20return%20types)%0D%0A%2F%2F%20(b)%20an%20optional%20'directive'%20unique%20symbol%20key%20with%20a%20unrelated%20type%20(infer%20the%20directive's%20type)%0D%0Adeclare%20function%20foo%3CTArg%2C%20TRet%2C%20TDir%3E(opts%3A%20Options%3CTArg%2C%20TRet%2C%20TDir%3E)%3A%20void%3B%0D%0Aconst%20directive%20%3D%20Symbol('a%20special%20unique%20symbol')%3B%0D%0Atype%20Options%3CTArg%2C%20TRet%2C%20TDir%3E%20%3D%20%7B%5Bx%20in%20string%5D%3A%20(arg%3A%20TArg)%20%3D%3E%20TRet%7D%20%26%20%7B%5Bdirective%5D%3F%3A%20TDir%7D%3B%0D%0A%0D%0A%2F%2F%20OK%20-%20infers%20TArg%20%3D%20number%2C%20TRet%20%3D%20number%2C%20TDir%20%3D%20(x%3A%20string)%20%3D%3E%20string%0D%0Alet%20p1%20%3D%20foo(%7B%0D%0A%20%20%20%20addOne%3A%20(x%3A%20number)%20%3D%3E%20x%20%2B%201%2C%0D%0A%20%20%20%20double%3A%20(x%3A%20number)%20%3D%3E%20x%20%2B%20x%2C%0D%0A%20%20%20%20%5Bdirective%5D%3A%20(x%3A%20string)%20%3D%3E%20'str'%2C%0D%0A%7D)%3B%0D%0A%0D%0A%2F%2F%20OK%20-%20infers%20TArg%20%3D%20number%2C%20TRet%20%3D%20number%2C%20TDir%20%3D%20(x%3A%20string)%20%3D%3E%20string%0D%0Alet%20p2%20%3D%20foo(%7B%0D%0A%20%20%20%20addOne%3A%20(x%3A%20number)%20%3D%3E%20x%20%2B%201%2C%0D%0A%20%20%20%20%5Bdirective%5D%3A%20(x%3A%20string)%20%3D%3E%20'str'%2C%20%20%2F%2F%20move%20up%20one%20place%2C%20OK%0D%0A%20%20%20%20double%3A%20(x%3A%20number)%20%3D%3E%20x%20%2B%20x%2C%0D%0A%7D)%3B%0D%0A%0D%0A%2F%2F%20~~~ERROR~~~%20-%20...%20prop%20'addOne'%20incompatible%20with%20index%20signature%0D%0A%2F%2F%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20...%20'x'%20and%20'arg'%20are%20incompatible%0D%0A%2F%2F%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20...%20'string'%20not%20assignable%20to%20'number'%0D%0Alet%20p3%20%3D%20foo(%7B%0D%0A%20%20%20%20%5Bdirective%5D%3A%20(x%3A%20string)%20%3D%3E%20'str'%2C%20%20%2F%2F%20move%20up%20one%20place%2C%20BOOM%0D%0A%20%20%20%20addOne%3A%20(x%3A%20number)%20%3D%3E%20x%20%2B%201%2C%0D%0A%20%20%20%20double%3A%20(x%3A%20number)%20%3D%3E%20x%20%2B%20x%2C%0D%0A%7D)%3B%0D%0A%0D%0A%2F%2F%20OK%20-%20infers%20TArg%20%3D%20number%2C%20TRet%20%3D%20number%2C%20TDir%20%3D%20string%0D%0Alet%20p4%20%3D%20foo(%7B%0D%0A%20%20%20%20%5Bdirective%5D%3A%20'str'%2C%0D%0A%20%20%20%20addOne%3A%20(x%3A%20number)%20%3D%3E%20x%20%2B%201%2C%0D%0A%20%20%20%20double%3A%20(x%3A%20number)%20%3D%3E%20x%20%2B%20x%2C%0D%0A%7D)%3B%0D%0A)

In particular:
- in `p3` (which errors), the compiler seems to be including the symbol key in the string index signature, and errors because it can't reconcile the different function types.
- but `p1` and `p2` are the same as `p3`, just the key order changes, and now the compiler has no error and infers everything correctly
- but `p4` is just like `p3` except the directive is not a function type, and now the compiler has no error and infers everything correctly. Works with a bunch of other `TDir` types too, just not functions.

```ts
// function foo takes an 'options' object that can have:
// (a) any number of string keys whose values are unary functions (infer the arg and return types)
// (b) an optional 'directive' unique symbol key with a unrelated type (infer the directive's type)
declare function foo<TArg, TRet, TDir>(opts: Options<TArg, TRet, TDir>): void;
const directive = Symbol('a special unique symbol');
type Options<TArg, TRet, TDir> = {[x in string]: (arg: TArg) => TRet} & {[directive]?: TDir};

// OK - infers TArg = number, TRet = number, TDir = (x: string) => string
let p1 = foo({
    addOne: (x: number) => x + 1,
    double: (x: number) => x + x,
    [directive]: (x: string) => 'str',
});

// OK - infers TArg = number, TRet = number, TDir = (x: string) => string
let p2 = foo({
    addOne: (x: number) => x + 1,
    [directive]: (x: string) => 'str',  // move up one place, OK
    double: (x: number) => x + x,
});

// ~~~ERROR~~~ - ... prop 'addOne' incompatible with index signature
//               ... 'x' and 'arg' are incompatible
//               ... 'string' not assignable to 'number'
let p3 = foo({
    [directive]: (x: string) => 'str',  // move up one place, BOOM
    addOne: (x: number) => x + 1,
    double: (x: number) => x + x,
});

// OK - infers TArg = number, TRet = number, TDir = string
let p4 = foo({
    [directive]: 'str',
    addOne: (x: number) => x + 1,
    double: (x: number) => x + x,
});
```

**Comment by yortus** [comment]
Closing since it's working as intended. I opened a separate issue (#26470) for the code in the preceding comment.
