### ISSUE TITLE
Proposal: add support for static code block in class.

### ISSUE THREAD

**Issue by DongShelton** [Microsoft/TypeScript#26254]
## Search Terms
`is:issue is:open label:Suggestion static `
## Suggestion
Add support for static code block in class, which means this code block would execute after the class has been defined automatically, and it also would gets called only once no matter how many instance of this class be created. (Such like Java static code block) 
## Use Cases
It could be used for the class initialization. For example, I want to write a component class that has some initial status.
```typescript
class Trigger extends React.Component<TriggerProps, TriggerState> {
  private static container: HTMLElement;

  static {
    const e = document.createElement('div');
    Trigger.container = e;
    document.body.appendChild(e);

    window.addEventListener('resize', (e: Event) => {
      /* do something */
    });

    window.addEventListener('click', (e: MouseEvent) => {
      /* do something */
    });
  }

  ... ...
}
```

But now I have to write this to support that feature.
```typescript
import { once } from 'lodash-decorators';

class Trigger extends React.Component<TriggerProps, TriggerState> {
  private static container: HTMLElement;
  
  /* This decorator would let this function would gets called only once */
  @once()
  static init() {
    const e = document.createElement('div');
    Trigger.container = e;
    document.body.appendChild(e);

    window.addEventListener('resize', (e: Event) => {
      /* do something */
    });

    window.addEventListener('click', (e: MouseEvent) => {
      /* do something */
    });
  }

  ... ...
}

Trigger.init();
```

## Examples
This feature like Java static code block, it is used for class initilization and it could not be called manually.
```typescript
class Person {
  static {
    console.log('static');
  }

  constructor() {
    console.log('init');
  }
}

const x = new Person();
const y = new Person();
```
It would log like this:
```
static
init
init
```

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by AlCalzone** [comment]
I guess you have to wait for https://github.com/tc39/proposal-class-static-block to move to stage 3 before anything is done here. As the champion is a developer here, I guess this will be added once its ready.
