### ISSUE TITLE
Questionable Semicolon Behavior

### ISSUE THREAD

**Issue by aryeh-looker** [Microsoft/TypeScript#26269]
**TypeScript Version:**  3.1.0-dev.201xxxxx

**Search Terms:** semicolon semicolons

**Code**

```ts
(ctrl as any).a = 'a'
(ctrl as any).b = 'b'
```

**Expected behavior:**

Emit this:

```
ctrl.a = 'a';
ctrl.b = 'b';
```

**Actual behavior:**

Emits this:

```
ctrl.a = 'a'(ctrl).b = 'b';
```

**Playground Link:** https://www.typescriptlang.org/play/#src=(ctrl%20as%20any).a%20%3D%20'a'%0D%0A(ctrl%20as%20any).b%20%3D%20'b'

**Related Issues:** None found

**Comment by andy-ms** [comment]
That's the behavior of JavaScript:
```js
const ctrl = 0;
(ctrl).a = 'a'
(ctrl).b = 'b'
```
Produces: `TypeError: "a" is not a function`
