### ISSUE TITLE
TypeScript v3.0.1 not following symlinks for local modules

### ISSUE THREAD

**Issue by jonathancreamer-eb** [microsoft/TypeScript#26264]
**TypeScript Version:**  3.1.0-dev.201xxxxx

**Search Terms:**
npm scoped, symlink, projects

**Code**
A picture of mysetup is here...

![](https://d.pr/i/M5yPLk+)

**Expected behavior:**
I am trying to use the new project references feature, although I'm not sure if this is a problem related to that new feature or not.

Essentially, I have `@jcreamer898/package-one` which takes a dependency on `@jcreamer898/package-two` and `@jcreamer898/package-three`. 

You can see in my screenshot above that, for whatever reason it's like typescript won't follow the symlink correctly because it says it can't find `@jcreamer898/package-two` or three...

![](https://d.pr/i/TYZ8Wc+)

**Actual behavior:**
TypeScript should follow symlinks even for scoped modules.

**Playground Link:** 
I have a sample github repo here https://github.com/jcreamer898/ts-dependencies

**Related Issues:**

**Comment by andy-ms** [comment]
The following works for me?
```sh
git clone https://github.com/jcreamer898/ts-dependencies.git
cd ts-dependencies/packages/project-three
tsc
cd ../project-two
tsc
cd ../project-one
npm install
tsc
```

**Comment by jonathancreamer-eb** [comment]
I was trying to use the new `tsc --build` command. Maybe it's just not possible yet with my setup?

**Comment by andy-ms** [comment]
Did you remember `npm install` in each subdirectory?

**Comment by jonathancreamer-eb** [comment]
Gah, just dawned on me that the builds are outputting to `dist/src`!

![](https://d.pr/i/wsqaKz+)

I'm still trying to wrap my mind around how I can use this `tsc --build` thing in a monorepo setup. It seems like such a useful tool!

**Comment by jonathancreamer-eb** [comment]
I'm guessing a big problem I have is, `references` does NOT mean, hey, build this one thing before you build the other things?

**Comment by andy-ms** [comment]
@RyanCavanaugh would know more about our plans to document the `--build` option. I don't think building would ever include doing an `npm install` though.
The outputting to `dist/src` may be because you have [`rootDir`](https://www.typescriptlang.org/docs/handbook/compiler-options.html) set.

**Comment by jonathancreamer-eb** [comment]
Yea I don't think it should do an npm install either. I think I might have just misunderstood or misused the project stuff. I think I tried to shoehorn it into a structure it's not meant to have. Which would be the mono-repo type of project where everything in `packages/*` could exist on its own. I'm also probably being too biased by my experience with Lerna. It might be worth it for me to change my approach to better line up with what project references are trying to accomplish and go from there.

**Comment by RyanCavanaugh** [comment]
> I'm guessing a big problem I have is, references does NOT mean, hey, build this one thing before you build the other things?

Running `tsc --build` on a project with references should build the referenced projects work. I think we have one or two bugs in the area that might be causing the build order to be wrong.

Have you reviewed the sample repo at https://www.github.com/RyanCavanaugh/learn-a ? It uses lerna and project references with symlinks; may be worth looking over to line up similarities and differences with what you have.
