### ISSUE TITLE
Partial with 

### ISSUE THREAD

**Issue by jdforsythe** [Microsoft/TypeScript#26272]
**TypeScript Version:**  2.9.2

**Search Terms:** partial, spread, optional, required

**Code**

[TS Playground](https://www.typescriptlang.org/play/#src=interface%20Foo%20%7B%0D%0A%20%20bar%3A%20string%3B%0D%0A%20%20name%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Aconst%20common%3A%20Partial%3CFoo%3E%20%3D%20%7B%20bar%3A%20'foobar'%20%7D%3B%0D%0A%0D%0Aconst%20foos%3A%20Foo%5B%5D%20%3D%20%5B%0D%0A%20%20%7B%20...common%2C%20name%3A%20'one'%20%7D%2C%0D%0A%20%20%7B%20...common%2C%20name%3A%20'two'%20%7D%2C%0D%0A%5D%3B%0D%0A%0D%0Aconst%20foosTwo%3A%20Foo%5B%5D%20%3D%20%5B%0D%0A%20%20%7B%20...%3CFoo%3Ecommon%2C%20name%3A%20'one'%20%7D%2C%0D%0A%20%20%7B%20...%3CFoo%3Ecommon%2C%20name%3A%20'two'%20%7D%2C%0D%0A%5D%3B)

```ts
interface Foo {
  bar: string;
  name: string;
}

const common: Partial<Foo> = { bar: 'foobar' };
const foos: Foo[] = [
  { ...common, name: 'one' },
  { ...common, name: 'two' },
]; // error

const foosTwo: Foo[] = [
  { ...<Foo>common, name: 'one' },
  { ...<Foo>common, name: 'two' },
]; // type coercion works 
```

**Expected behavior:**

Typescript knows all the properties are provided and there are no errors

**Actual behavior:**

```
[ts]
Type '{ name: string; bar?: string; }[]' is not assignable to type 'Foo[]'.
  Type '{ name: string; bar?: string; }' is not assignable to type 'Foo'.
    Property 'bar' is optional in type '{ name: string; bar?: string; }' but required in type 'Foo'.
```

This error **does not occur** when assigning to a class property instead of a `const`:

[TS Playground](https://www.typescriptlang.org/play/#src=interface%20Foo%20%7B%0D%0A%20%20bar%3A%20string%3B%0D%0A%20%20name%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Aconst%20common%3A%20Partial%3CFoo%3E%20%3D%20%7B%20bar%3A%20'foobar'%20%7D%3B%0D%0A%0D%0Aclass%20SomeClass%20%7B%0D%0A%20%20private%20foos%3A%20Foo%5B%5D%3B%0D%0A%0D%0A%20%20constructor(f)%20%7B%0D%0A%20%20%20%20this.foos%20%3D%20f%3B%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Aconst%20fs%20%3D%20new%20SomeClass(%5B%0D%0A%20%20%7B%20...common%2C%20name%3A%20'one'%20%7D%2C%0D%0A%20%20%7B%20...common%2C%20name%3A%20'two'%20%7D%2C%0D%0A%5D)%3B%0D%0A)

```ts
class FooFactory {
  private foos: Foo[];

  constructor(foos) {
    this.foos = f;
  }
}

const common: Partial<Foo> = { bar: 'foobar' };

const fs = new FooFactory([
  { ...common, name: 'one' },
  { ...common, name: 'two' },
]); // no error
```

**Playground Link:** 

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
```ts
const common: Partial<Foo> = { bar: 'foobar' };
            ~~~~~~~~~~~~~~
```
When you write a type annotation for a variable declaration, TypeScript validates that the initializer conforms to that type, but otherwise discards information about the initializer. So we later here:
```ts
const foos: Foo[] = [
  { ...common, name: 'one' },
  { ...common, name: 'two' },
]; // error
```
TS doesn't know that you didn't specify `name` and not `bar` in `common`.

You can simply remove that type information to make the error go away.

In the class example, the constructor takes a parameter of type `any` so naturally there is no error.

See #26064 for discussion of syntax that would allow simultaneous in-place type validation without losing inference information from the initializer.
