### ISSUE TITLE
In JS, JS containers can't be augmented across files

### ISSUE THREAD

**Issue by sandersn** [Microsoft/TypeScript#26276]
```js
// @Filename: file1.js
var Ns = {}
Ns.x
// @Filename: file2.js
Ns.x = 1
```

**Expected behavior:**
No errors. Ns.x should be declared in file2 and resolvable in file1.

**Actual behavior:**
Errors on both `Ns.x`: 'x' not found on '{}'.

**Comment by RyanCavanaugh** [comment]
Doesn't seem like anyone's hitting this
