### ISSUE TITLE
tsconfig.json parsing errors aren't helpful

### ISSUE THREAD

**Issue by custarddog** [Microsoft/TypeScript#2627]
create a tsconfig.json file with a typo in it (invalid json)
run tsc
error TS6050: Unable to open file 'tsconfig.json'.

If I can't spot the typo I have to paste it into a json validator to find it. Can it give a nice error, eg., Sublime gives "Unexpected character, expected a comma or closing bracket in Packages\User\Preferences.sublime-settings:56:2"

**Comment by mhegazy** [comment]
[readConfigFile](https://github.com/Microsoft/TypeScript/blob/master/src/compiler/commandLineParser.ts#L276) currently uses undefined return value to signal either an non-existent file or an malformed one. We will need to change that, and show the error message from the exception thrown by JSON.parse

**Comment by DickvdBrink** [comment]
What do you prefer here? Just propagate the error message with a throw statement? So the consumers should try/catch themselves or do you prefer an object with a error (if any) and a result?

**Comment by mhegazy** [comment]
The only parallel i could think of is `CompilerHost.getSourceFile`, it takes an optional onError property that would report the error. so may be that is a better way to go.

**Comment by Acaspita** [comment]
+1

**Comment by paulvanbrenk** [comment]
One thing to note is that the intrinsic JSON object doesn't give the most useful information at this time.

**Comment by mhegazy** [comment]
> JSON.parse("{ a : true }" 

gives me 

> SyntaxError: Unexpected token a

Which is significantly better than silently skipping the file.

**Comment by paulvanbrenk** [comment]
It's better, but not having the line/col is a pretty big limitation.

**Comment by mhegazy** [comment]
I think if we want to be fancy, we can parse it ourselves :D, in theory you can use the scanner/parser. not sure if the cost justifies the value though.

**Comment by paulvanbrenk** [comment]
Well we would be able to give the line/col for the file references, this would help us give better errors for those at a later stage.

**Comment by NaridaL** [comment]
@mhegazy This can be closed, parsing it with ts's parser is what happens now afaik.


    export function parseConfigFileTextToJson(fileName: string, jsonText: string): { config?: any; error?: Diagnostic } {
        const jsonSourceFile = parseJsonText(fileName, jsonText);
