### ISSUE TITLE
In JS, bad error message for missing type argument in param tag

### ISSUE THREAD

**Issue by sandersn** [Microsoft/TypeScript#26285]
```js
/** @template T */
class CC {
    /** @param {T} t */
    constructor(t) {
    }
}
/** @param {CC} cc */
function foo(cc) {
}
```

**Expected behavior:**
Error, something like "Expected 1 type arguments, got 0".

**Actual behavior:**
Expected CC<T> type arguments; provide these with an '@extends' tag.

The error message has 3 problems:

1. The error message is intended for classes only (`class DD extends CC { ... }`)
1. The type isn't quoted.
2. The expected number of type arguments isn't given.

I think the fix is two-fold:

1. For parameters, go back to the normal error message.
2. For classes, give the number of expected type arguments instead of the class name, which is already given. Reading the code, I'm almost certain this is a bug in which the code chooses between multiple messages and then passes them all the same arguments.

**Comment by joma74** [comment]
My case
```
// App.js
/** @type {import("vue").ComponentOptions} */
let vueComponentOptions = {
}
```
gives
> [ts] Expected ComponentOptions<V, Data, Methods, Computed, PropsDef, Props>-1 type arguments; provide these with an '@extends' tag.

which eventually may be the same issue.

**Comment by sandersn** [comment]
This is now fixed.
