### ISSUE TITLE
mixin properties not checked

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#26286]
**TypeScript Version:**  master (as of #26283)

**Code**

```js
/**
 * @template {new (...args: any[]) => any} T
 * @param {T} SuperClass
 */
function myMixin(SuperClass) {
    return class extends SuperClass {
        method() { return 0; }
    }
};

class Base {}
const Mixed = myMixin(Base);

const instance = new Mixed();
instance.method(); // Correctly typed in signature help
instance.meshod(); // But not checked
```

Run with `allowJs`, `checkJs`, and `strict`.

**Expected behavior:**

Error at `meshod`.

**Actual behavior:**

No error.

**Comment by sandersn** [comment]
This is true of Typescript as well:

```ts
function mix<T extends new (...args: any[]) => any>(S: T) {
    return class extends S {
        f() { return 0; }
    }
};

class Base {}
const Mixed = mix(Base);

export const m = new Mixed();
m.f(); // Correctly typed in signature help
m.j(); // should error here, but doesn't
```

**Comment by andy-ms** [comment]
Looks like it has to do with the type `T` extends returning `any` -- though I think the actual `T` ought to (but isn't) used instead of its constraint when outside of `mix`?

**Comment by sandersn** [comment]
Well, the reason that you see the apparent type of T is that the any comes from `class extends S`. S has type T, whose apparent type has a constructor with return type any, which is equivalent to extending any. That’s what allows you to access any property on m.

**Comment by andy-ms** [comment]
I think the problem then is that we force the user to write `any` in that position rather than `unknown`, which is an error (`Base constructor return type 'unknown' is not a class or interface type.`)

**Comment by michaeljota** [comment]
I though about using `InstanceType` in the return, that actually makes sense, although the code does throw when expected, it also throws extending `S`

```ts
function mix<T extends new (...args: any[]) => InstanceType<T>>(S: T) {
    return class extends S { // Throws: Base constructor return type 'InstanceType<T>' is not a class or interface type.
        f() { return 0; }
    }
};

class Base {}
const Mixed = mix(Base);

export const m = new Mixed();
m.f(); // Correctly typed in signature help
m.j(); // Throws: Property 'j' does not exist on type 'mix<typeof Base>.(Anonymous class) & Base'.
```

Maybe I'm using `InstanceType` poorly, but I think this should be the way to go.
