### ISSUE TITLE
Compiler API: Support String sources

### ISSUE THREAD

**Issue by inakianduaga** [Microsoft/TypeScript#26291]
## Search Terms

compiler api, in-memory AST

## Suggestion

Possibility of parsing AST from string instead of file reference. File-based approach doesn't work well in the browser

## Use Cases

This is in the context of writing React Storybook examples where I want to display on a web UI certain pieces of the TypeScript codebase. It's easy to read source files as text via webpack `raw-loader`, but currently not easy to AST-parse those sources to be able to extract say a type or a certain React component definition from the whole file (since there is no filesystem on the web).

With the current compiler API, the only possible solution (which I haven't managed to get working, but probably could given enough time), would be to use webpack `val-loader` to generate the AST transformation at compile time so the bundled code that runs on the browser doesn't need to. But it's overly complicated 

## Examples

```ts
import * as ts from typescript

val someSourceCodeAsString: string = `

//...

type MyType = {
  foo: string
}

const bar = () => 'bar'

//...
`

const source: ts.SourceString = ts.createSourceString(someSourceCodeAsString, ts.ScriptTarget.ES2016)

```

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by AlCalzone** [comment]
Maybe you can provide a "virtual" file system like I did here: https://github.com/AlCalzone/virtual-tsc/blob/master/src/virtual-fs.ts

**Comment by ajafff** [comment]
You pass a string to `ts.createSourceFile`. It doesn't matter where that string came from so you don't need any file system access.

**Comment by RyanCavanaugh** [comment]
Between providing the source text up front to `createSourceFile` as @ajafff mentions, and the possibility of providing your own host, this is already extremely well-supported.

**Comment by inakianduaga** [comment]
> You pass a string to ts.createSourceFile. It doesn't matter where that string came from so you don't need any file system access.

You're correct (this is the approach used by [typescript-parser](https://github.com/buehler/node-typescript-parser/blob/develop/src/TypescriptParser.ts#L58) for example), however under the hood TS will call node `fs` for filesystem operations, which fails on a standard browser environment. 

So I guess the rephrased question would be: **Is there a straightforward way to use the ts compiler api within a browser environment**.

In the meantime I got it to work on the browser using [memfs](https://github.com/streamich/memfs) but it feels like a hack (similar to @AlCalzone suggestion). 

I will reimplement the functionality as a *custom typescript transformer* because it runs at compile time so I can consume the API without workarounds.

> this is already extremely well-supported

So I'm fine closing the issue but it doesn't feel that way. Granted the use-case is probably an edge case but probably interesting as people develop more complex tools on the browser.

>  the possibility of providing your own host
@RyanCavanaugh Can you provide a link/expand on this? Not sure what you mean. Thanks

**Comment by AlCalzone** [comment]
The own host thing is what I do in the repo I linked you.

**Comment by inakianduaga** [comment]
@RyanCavanaugh thanks for the explanation. Looks like I need to read / learn more and all the pieces are already in place (perhaps the [Typescript Compiler API docs](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API) could use a couple of links).

I'll close this, thanks for the super quick feedback, unbelievable considering there are 2713 other open issues to take care of.

**Comment by 10229428** [comment]
> > Is there a straightforward way to use the ts compiler api within a browser environment.
> 
> @inakianduaga certainly; the TypeScript Playground does this. There are other playgrounds as well that do this. https://github.com/agentcooper/typescript-play is a particularly good one; this repo links a bunch of other websites which all host the compiler in a browser for various uses.
> 
> > the possibility of providing your own host
> 
> When you call `createProgram` you provide a `CompilerHost`. The host serves as an intermediary between the TS API and any would-be underlying file system operations.
> 
> Our own test harness also does a bunch of non-filesystem-based API usage; in fact you can run the TypeScript unit tests in a browser.

private createProgram(code: string) {
        const options = {};
        const file: File = {fileName: 'no_extension', content: code};

        console.log('sys: ', this.typescript.sys);

        const compilerHost = this.typescript.createCompilerHost(options);
        compilerHost.getSourceFile = (fileName: string) => {
            file.sourceFile = file.sourceFile || this.typescript.createSourceFile(fileName, file.content, this.typescript.ScriptTarget.ES2015, true);
            return file.sourceFile;
        };
        const program = this.typescript.createProgram([file.fileName], options, compilerHost);
    }

I want to use createProgram to compile ts source code to js in browser. But when I call 'createCompilerHost' to create my own host, I find that 'this.typescript.sys' is undefined. 'this.typescript' is the typescript instance.

**Comment by sstchur** [comment]
Is there a way to create a program from source and then create a TypeChecker from that program?  None of the examples in this thread (nor in any of the linked githubs) seem to do that, specifically.

createProgram takes `rootNames` (a string array), in which case, it seems like you have to pass a physical file to it in order to create a program. Or it takes `CreateCompilerOptions`, but that is just a wrapper around `rootNames` and `compilerOptions` so it doesn't really help.

Yes, you can create a SourceFile, and that works.  And you can traverse it, as in:
```typescript
ts.forEachFile(mySourceFile, visit)
```

But that sourceFile isn't connected in any way to a "program" and inside the visit function, when you get access to the node, you can't call `checker.getTypeAtLocation(node)` without a checker.

I can manage to conjure up a checker independently, but it won't work.  It just results in Types like:

`TypeObject { flags: 1, id: 4, intrinsicName: 'error', objectFlags: 0 }`

**Comment by sstchur** [comment]
> Is there a way to create a program from source and then create a TypeChecker from that program? None of the examples in this thread (nor in any of the linked githubs) seem to do that, specifically.
> 
> createProgram takes `rootNames` (a string array), in which case, it seems like you have to pass a physical file to it in order to create a program. Or it takes `CreateCompilerOptions`, but that is just a wrapper around `rootNames` and `compilerOptions` so it doesn't really help.
> 
> Yes, you can create a SourceFile, and that works. And you can traverse it, as in:
> 
> ```ts
> ts.forEachFile(mySourceFile, visit)
> ```
> 
> But that sourceFile isn't connected in any way to a "program" and inside the visit function, when you get access to the node, you can't call `checker.getTypeAtLocation(node)` without a checker.
> 
> I can manage to conjure up a checker independently, but it won't work. It just results in Types like:
> 
> `TypeObject { flags: 1, id: 4, intrinsicName: 'error', objectFlags: 0 }`
> 
> Here's a snippet that illustrates the goal (to create a program from source and be able to type check it) and the issue:
> 
> ```ts
> const program = ts.createProgram([''], { alwaysStrict: true, noEmitOnError: true, skipLibCheck: true, strict: true });
> const checker = program.getTypeChecker();
> 
> const source = 'let p: null;'
> const sourceFile = ts.createSourceFile('doesnotmatter', source, ts.ScriptTarget.ES2015);
> ts.forEachChild(sourceFile, visit);
> function visit(node) {
>   if (ts.isVariableDeclaration(node)) {
>       const t = checker.getTypeAtLocation(node);
>       /*** doesn't work -- t will end up as TypeObject { flags: 1, id: 4, intrinsicName: 'error', objectFlags: 0 } ***/
>     }
>     ts.forEachChild(node, visit);
>   }
> ```

Finally found an example that help and posting it here for the benefit of others.  Looks like the trick is that you have a basically fake a compilerHost so that its `getSourceFile` method returns your sourceFile:  https://learning-notes.mistermicheels.com/javascript/typescript/compiler-api/
