### ISSUE TITLE
Aliasing a type from an existing identifier (variable or constant)

### ISSUE THREAD

**Issue by yahiko00** [Microsoft/TypeScript#26293]
## Search Terms

type alias typeof instanceof like

## Suggestion

It could be convenient to be able to refer to a type from an existing identifier (variable or constant)

## Use Cases

This is not always relevant or practical to create a user-defined type with the keyword type of interface, when such a type is not reused that often.

But we could want to express the fact that a variable has the same type as another one.

In such a case, this could be convenient to be able to say "I want a variable `y` having the same type as variable `x`".

## Examples

```ts
let products: Map<string, number>;

let items: like products;
```

Above, the `items` has the same type as `products`.
I used a new keyword `like`, but this could be something else.

## Checklist

My suggestion meets these guidelines:
* [X] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by AlCalzone** [comment]
You're looking for `typeof`:
```ts
let products: Map<string, number>;
let items: typeof products; // Map<string, number>
```

https://www.typescriptlang.org/play/#src=let%20products%3A%20Map%3Cstring%2C%20number%3E%3B%0D%0Alet%20items%3A%20typeof%20products%3B

**Comment by yahiko00** [comment]
I should have done something wrong when I tried this with `typeof`... But that's what I was looking for.
