### ISSUE TITLE
Importing a library enables global @types resolution

### ISSUE THREAD

**Issue by ekulabuhov** [Microsoft/TypeScript#26309]
**TypeScript Version:**  3.1.0-dev.20180808

**Search Terms:** `@types`, namespace, mapbox-gl

**Code**

Setup:
1. mkdir tsc-test && cd tsc-test
2. tsc --init
3. Open tsconfig.json and uncomment `types: []` to disable automatic type resolution
4. npm init -y
5. npm i @types/mapbox-gl -D

Open in vscode, and create index.ts:

```ts
mapboxgl.accessToken = 'x';	// Error: Cannot find name 'mapboxgl'
```

Change it to import a class from a library:

```ts
import { Marker } from 'mapbox-gl';
mapboxgl.accessToken = 'x';	// Error is gone, mapboxgl is now a namespace
```

**Expected behavior:**
Error to be still present

**Actual behavior:**
Error is gone

**Playground Link:** N/A

**Related Issues:** N/A

**Comment by weswigham** [comment]
This would be because the `mapbox-gl` type definitions [unconditionally make a global namespace](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mapbox-gl/index.d.ts#L9), rather than using a UMD `export mapboxgl as namespace;` declaration.

**Comment by mikew** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27978 has caused issues in our app. I'm not sure if there in @types/mapbox-gl, react-mapbox-gl, or TypeScript, but the combination of all 3 is causing grief.

With just @types/mapbox-gl installed, I'm able to reference an interface from their namespace anywhere, without importing. But when I install react-mapbox-gl, an issue pops up: https://github.com/alex3165/react-mapbox-gl/issues/631

[react-mapbox-gl does reopen the namespace](https://github.com/alex3165/react-mapbox-gl/blob/762a7971f08a6c6cfc577bf49517cde5fd770fb2/src/map.tsx#L111-L118), maybe that's the issue?

Why it's such a problem for us is our apps features may come with a `types.d.ts` file with interfaces that can be accessed throughout the app. With this regression, we now need to add an `import` in our `.d.ts` files, which means TypeScript doesn't make included interfaces available throughout the app anymore.

**Comment by weswigham** [comment]
> react-mapbox-gl does reopen the namespace, maybe that's the issue?

Probably! If should probably merge with the module and not the UMD global, since the UMD global is kinda like a fake-redirect-thing (although the merge not failing/erroring may still be a bug).

I'd update [this](https://github.com/alex3165/react-mapbox-gl/blob/762a7971f08a6c6cfc577bf49517cde5fd770fb2/src/map.tsx#L111-L118) to read:
```ts
declare "mapbox-gl" {
    export interface MapboxOptions {
      failIfMajorPerformanceCaveat?: boolean;
      transformRequest?: RequestTransformFunction;
    }
}
```
instead.

**Comment by mikew** [comment]
Yeah I figured it could be kept local to react-mapbox-gl, I'll test over the weekend and try sending a PR.
