### ISSUE TITLE
Mention about HTML Tag Types in the documentation ( Handbook )

### ISSUE THREAD

**Issue by Praveen-Rai** [microsoft/TypeScript#26304]
Hello there, today i've tried TypeScript for the first time and in my view apart from the Basic datatypes that TypeScript provide, it also has datatype for each of HTML Element (Tag) which is damn cool. But the issue is that we don't highlight them on the docs. 

I am referring to : https://www.typescriptlang.org/docs/handbook/basic-types.html ( That also at the home readme of this project with the title TypeScript Handbook ). I strongly feel that support for HTML Tag types must be highlighted at this page.

**Comment by RyanCavanaugh** [comment]
HTML/DOM info doesn't really belong on that page, but we could have a separate handbook page for working with the DOM with some general advice.

**Comment by Praveen-Rai** [comment]
@RyanCavanaugh If at all you add HTML/DOM types on another page, then make sure that you mention the link on the DataTypes Page. For me as a first timer i am really excited to see a Type appearing for the HTML element and i am sure others will love it too. Though i just learned that those are in-built interfaces. But that doesn't matter, i was writing a function where the Form element is being passed as a parameter, and i am more than happy to see HTMLFormElement in my VS suggestion. 

As a layman i take it as HTMLFormElement  is a type in-built in TypeScript and when i put '.' operator next to the parameter i get the Form Element Properties and Methods. I found this superb and feel that others might also feel the same way, so we must mention somehow that we support HTML element types as a DataType with xyz limitations or whatever. 

Hope u understand what i am trying to say.

**Comment by RyanCavanaugh** [comment]
This doesn't seem to be a thing that needs documentation
