### ISSUE TITLE
[Bug]tsc does not finish

### ISSUE THREAD

**Issue by kgtkr** [microsoft/TypeScript#26314]
**TypeScript Version:**  3.0.1/3.1.0-dev.20180808

**Search Terms:**

**Code**

```ts
type Head<T> = T extends [infer P, ...any[]] ? P : never;
type Tail<L extends any[]> = ((...x: L) => void) extends ((h: any, ...rest: infer T) => void) ? T : never

type Last<T extends any[]> = {
    0: never,
    1: Head<T>,
    2: Last<Tail<T>>,
}[T extends [] ? 0 : T extends [any] ? 1 : 2];

type Reverse<L extends any[], X extends any[]=[]> = {
    1: X, 0: Reverse<Tail<L>, Cons<Head<L>, X>>
}[L extends [] ? 1 : 0]

type Fn<R extends any[]> = (...args: R) => void
type Fn1<H, T extends any[]> = (h: H, ...args: T) => void
type Cons<H, T extends any[]> = Fn1<H, T> extends Fn<infer R> ? R : []

type Zip<A extends any[], B extends any[], R extends any[]=[]> = {
    0: Reverse<R>,
    1: Zip<Tail<A>, Tail<B>, Cons<[Head<A>, Head<B>], R>>
}[A extends [] ? 0 : B extends [] ? 0 : 1];

type ShiftZip<T extends any[]> = Zip<T, Tail<T>>;

type Tuple2Fn<T> = T extends [infer A, infer B] ? (x: A) => B : never;

type _Pipe<T extends any[], R extends any[]=[]> = {
    0: Reverse<R>,
    1: _Pipe<Tail<T>, Cons<Tuple2Fn<Head<T>>, R>>
}[T extends [] ? 0 : 1];

type Pipe<T extends any[]>=_Pipe<ShiftZip<T>>;

declare function pipe<T extends any[]>(...f: Pipe<T>): (x: Head<T>) => Last<T>;
```

**Expected behavior:**
tsc finish

**Actual behavior:**
tsc does not finish

**Playground Link:** 

**Related Issues:** 
#24897

**Comment by kgtkr** [comment]
tsserverのクラッシュは何度も発生しました
しかしそのようなコードもtscを使えば正常にコンパイルすることが出来ましたし、tsserverを再起動すれば復活します
しかしこのコードはtscでもコンパイル出来ませんし、tsserverを再起動しても復活しません
tscの詳しい内部を知らないので #26155 と関連している問題かは分かりません

Tsserver crash occurred many times
However, such code could be successfully compiled using tsc, restarting tsserver will restore
However, this code can not be compiled with tsc, nor is it restored by restarting tsserver
I do not know the detailed internal of tsc so I do not know if it is related to # 26155

**Comment by RyanCavanaugh** [comment]
See comments in #25942 - we don't have any near-term ideas for detecting non-terminating type computations nor good ideas on how to issue useful diagnostics for them.

**Comment by RyanCavanaugh** [comment]
This quickly errors now.

halting problem: solved
