### ISSUE TITLE
Typescript doesn't enforce abstract method arguments in the derived class

### ISSUE THREAD

**Issue by jagadishg** [Microsoft/TypeScript#26324]
```
abstract class A {
    public abstract display(name: string): void; 
}

class B extends A {
    public display(): void {
    }   
}
```

The above code compiles successfully in typescript.

But why doesn't typescript compiler throw an error as class B does not properly implement (name argument is missing) the abstract method display from abstract class A?

Is this an expected behavior?

**Comment by nmain** [comment]
This sort of behavior is covered in the FAQ.  I'm not sure if this exact case appears in there, but https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-functions-with-fewer-parameters-assignable-to-functions-that-take-more-parameters is a similar situation.
