### ISSUE TITLE
TypeScript_SDK.exe installed for VS2017 preview if both release and preview versions installed

### ISSUE THREAD

**Issue by MaceWindu** [Microsoft/TypeScript#26326]
I have Visual Studio 2017 15.7.6 and 15.8.0 Preview 5.0 installed.

I was migrating existing project to TS3.0 and noticed TypeScript_SDK.exe installed TS3.0 support for preview version of Visual Studio instead of release version (where I need it). I would expect installer to ask which VS versions should be updated or at least install for all of them.

VS 2017 15.7.6:
![image](https://user-images.githubusercontent.com/1099238/43907062-fdb1fcf6-9bf4-11e8-9393-cf318a5cb677.png)

VS 2017 Preview (you can notice that 2.9 was also installed here):
![image](https://user-images.githubusercontent.com/1099238/43907148-2548da14-9bf5-11e8-9821-e6de2e00ded4.png)

BTW, this [page](https://github.com/Microsoft/TypeScript/wiki/Updating-TypeScript-in-Visual-Studio-2017) shows TypeScript project properties, but [there is no TypeScript project](https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/31368127-create-a-javascript-project-type) template in VS2017.

**Comment by MaceWindu** [comment]
Not sure how typescript support integrated with visual studio - maybe it is only issue with installerm because when I edit tsconfig, I see that new options, added by 3.0, already supported by intellisense in release version of VS.

Still, cannot check project properties window have 2.9 and 3.0 in dropdown, as I have no idea how to access this page.

**Comment by minestarks** [comment]
Currently the SDK installer installs for all Visual Studio 2017 instances, so this behavior is by design. You should have gotten 3.0 in all your VS instances.

Unfortunately, the VS setup UI will not add an entry for anything you may have installed using the standalone TypeScript installer, so that may be confusing.
