### ISSUE TITLE
invoking methods on numbers

### ISSUE THREAD

**Issue by TimKelly2** [Microsoft/TypeScript#2632]
The rules for numeric constants do not follow the same rules for numeric variables. I don't know if this is an error, or just an oddity.  

test1 and test4 behave as expected. Numbers are converted to strings.

test2 does not compile without spaces. 

test3 does compile, but strips the spaces.  This is not a valid javascript without the space.  It would be valid with the space.

The Typescript compiles to this javascript.

Typescript:
```ts
  var i:number = 1;
  var test1 = i.toString();  
 
  // var test2 = 2.toString(); // compiler error
  var test3 = 3 .toString(); // runtime error
  var test4 = new Number(4).toString();
```
JavaScript:
```js
var i = 1;
var test1 = i.toString();
// var test2 = 2.toString(); // compiler error
var test3 = 3.toString(); // runtime error
var test4 = new Number(4).toString();
```

**Comment by RyanCavanaugh** [comment]
Summary:
test1 is the correct behavior
test2 is the correct behavior (the right thing to write is 2..toString())
**test3 is a bug**
test4 is the correct behavior

**Comment by TimKelly2** [comment]
Thank you for your quick answer.  I am interested in test2, and looking at ECMA 262 version 5.1.  

A period may be considered a punctuator (7.7) or a part of a numeric literal (7.8.3).  I do not see a statement in the spec that says which has precedence when there is an ambiguity.  Does it matter when one interpretation is an error and the other is not?

Consider a variation on the second test which succeeds where test 2 failed:
    var test2b = 2["toString"]();
This compiles to:
    var test2b = 2["toString"]();

Property Accessors in 11.2.1 describes bracket notation. Dot notation is "identical in its behavior".
How do you resolve test 2b and not 2? ( apologies to Shakespeare)

**Comment by TimKelly2** [comment]
This works also.
var test2 = 2\["toString"\]\(\);

**Comment by RyanCavanaugh** [comment]
11.2.1 describes behavior, not syntax.

The key section is 7:

 > The source text is scanned from left to right, repeatedly taking the longest possible sequence of characters as the next input element.

A trailing dot is an allowed production of `DecimalLiteral`, so the sequence `2.` is greedily interpreted as a `DecimalLiteral`

**Comment by CyrusNajmabadi** [comment]
Note: this is due to the following lexical grammar rule:

```
DecimalLiteral ::
    DecimalIntegerLiteral . DecimalDigits_opt ExponentPart_opt
````

Because of that rule, along with the relevant part of the spec that Ryan quoted, it follows that "2.toString()" is scanned into the following input elements
```
2.
toString
(
)
```

There is no grammar production that can handle that sequence of input elements.   Changing to "2..toString()" produces this sequence of input elements.

```
2.
.
toString
(
)
```

This is properly handled during parsing as the invocation ```()``` of a property-access-expression ```2. . toString```
