### ISSUE TITLE
No error accessing private property with indexed access

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#26328]
**TypeScript Version:**  3.1.0-dev.20180809

**Code**

```ts
class A { private n!: number; }
const a = new A();
const nameN = "n";
const n = a[nameN];
```

**Expected behavior:**

Error at `a[nameN]` just like for `a.n`.

**Actual behavior:**

No error.

**Comment by RyanCavanaugh** [comment]
This is an intended allowed bypass; see https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#413-property-access which outlines accessibility rules for `a.x` but not `a["x"]`
