### ISSUE TITLE
Object spread should not exclude setter-only properties

### ISSUE THREAD

**Issue by ajafff** [Microsoft/TypeScript#26337]
**TypeScript Version:**  3.1.0-dev.20180808

**Search Terms:**

**Code**

```ts
const obj = {
    foo: 1,
    ...{set bar(v: number) {}}
};
```

**Expected behavior:**

`obj` is inferred as `{foo: number, bar: undefined}`.
Spreading a setter-only property uses `undefined` as the property's value.
Likewise the following evaluates to `true`:

```js
({
    foo: 1,
    ...{set foo(v) {}}
}).foo === undefined;
```

**Actual behavior:**

`obj` is inferred as `{foo: number}`.

**Playground Link:** https://agentcooper.github.io/typescript-play/#code/MYewdgzgLgBCBGArGBeGBvAUDHMBmIIAXDAIwA02uAdLehAKazwCGATgBQBuJYArgFt4DNgEoMAXwmYJAbkxA

**Related Issues:** 
#11596
#21759
#17793

**Comment by ajafff** [comment]
This might be unnecessary if #26338 lands. The special handling of setter-only properties could then be removed completely

**Comment by sandersn** [comment]
From the type-level perspective:

A set-only property on the rhs introduces a property of type undefined that does *not* union with the same property's type from the lhs.
