### ISSUE TITLE
VSCode never offers a (shorter) relative import path when the module matches compilerOptions.paths

### ISSUE THREAD

**Issue by richardszalay** [Microsoft/TypeScript#26348]
Issue Type: <b>Bug</b>

The `typescript.preferences.importModuleSpecifier` setting states that using `auto` will "infer the shortest path type". However, when a compilerOptions.paths value matches the import, only a full path is offered even if it is longer than the relative one. Oddly, this appears to the be opposite of #25876

(What would actually be nice is to configure the number of parent directories / `../` before preferring an absolute path)

1. Set the workpace `typescript.preferences.importModuleSpecifier` setting to `auto`

2. Add `typescript@3.0.1` and configure the workspace to use it

2. Create the following structure:

```
tsconfig.ts
src/
  features/
    feature1/
      file1.ts
      file2.ts
```

```json
// tsconfig.ts
{
  "compilerOptions": {
    "baseUrl": "src",
    "paths": {
      "features/*": ["features/*"]
    }
}
```

```ts
// file2.ts
export interface ExportedInterface {
}
```

2. In `file1.ts`, reference `ExportedInterface` and use the "Quick Fix" to add an import.

Expected:

`import { ExportedInterface } from './file2'`

Actual:

`import { ExportedInterface } from './features/feature/file2'`

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:11.471Z)
OS version: Windows_NT ia32 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (5.70GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe .|
|Screen Reader|no|
|VM|0%|

</details>

**Related Issues:** 

#25876 appears to be the opposite (?)

**Comment by andy-ms** [comment]
Should be fixed by #25803.
