### ISSUE TITLE
TypeScript 3.0 docs "What's new" -- Rest parameters with tuple types

### ISSUE THREAD

**Issue by walrus95** [Microsoft/TypeScript#26342]
Hey TypeScript people! This may just be a documentation issue, but the [release notes](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-0.html) for TypeScript 3.0 state the following:

```
The following two declarations are equivalent:
declare function foo(...args: [number, string, boolean]): void;
declare function foo(args_0: number, args_1: string, args_2: boolean): void;
```

However, this does not seem to be true. Using the [TypeScript PlayGround](https://www.typescriptlang.org/play/), the following TypeScript:

```
function foo(...args: [number, string, boolean]): void {
    console.log(args[0]);
}

foo(4, "4", true);
```

Actually compiles to:

```
function foo() {
    var args = [];
    for (var _i = 0; _i < arguments.length; _i++) {
        args[_i] = arguments[_i];
    }
    console.log(args[0]);
}
foo(4, "4", true);
```

So, I think you may need to update your docs! Or am I just missing something obvious here?! Or does your PlayGround need an upgrade?

**Comment by weswigham** [comment]
We mean equivalent type-system-wise - the emit for rest parameters is, as always, specific to rest parameters.

**Comment by RyanCavanaugh** [comment]
There's no emit for `declare function`.

**Comment by walrus95** [comment]
I'm guessing "emit" must be compiler terminology. I'm just a user of the language, and know nothing about its implementation. All I know is that when I use the fancy new syntax for rest parameters with tuple types, there exists no variables named `args_0`, `args_1`, or `args_2` within the body of my function. Do you see how somebody could get that impression from reading the documentation as written? Therefore, I would suggest that the documentation be clarified to indicated that within the body of such a function, the arguments in question would actually be `args[0]`, `args[1]`, and `args[2]`.

![scumbag-engineering-professor](https://user-images.githubusercontent.com/32824014/43959378-96ee77dc-9c7c-11e8-9f1f-7dfb9e47a188.jpg)

**Comment by AlCalzone** [comment]
The key point is: 

> The following two **declarations** are equivalent

A declaration is not an implementation. For the caller of your function, the function signatures are effectively the same, because you call them with a number, a string and a boolean.

**Comment by walrus95** [comment]
@AlCalzone I agree with you. Closing out the issue.
