### ISSUE TITLE
Proposal: --strictToString - stricter toString() checks

### ISSUE THREAD

**Issue by tmkn** [Microsoft/TypeScript#26357]
## Search Terms
toString

## Suggestion
I would like TypeScript to warn against cases where `toString()` would yield the infamous `[object Object]`.

## Use Cases
- Prevent unintentional errors caused by `[object Object]`
- Non JS developers might feel compelled to use `toString()` for complex types

While TypeScript already prevents this common error:
```typescript
let uri = { uri: "abc" };
let dictionary = {};

dictionary[uri] = "foo"; //Type '{ uri: string; }' cannot be used as an index type.
```
it doesn't guard against something like this:
```typescript
let uri1 = { uri: "uri1" };
let uri2 = { uri: "uri2" };

if (uri1.toString() == uri2.toString()) {
    //always true since runtime comparison is "[object Object]" == "[object Object]"
}
```

## Examples
Basically highlight if `toString()` is called on a non primitive type which does not have a custom implementation.
```typescript
let a1 = true;
a1.toString(); //ok -> "true"

let a2 = 1;
a2.toString(); //ok -> "1"

let a3 = "label";
a3.toString(); //ok -> "label"

let a4 = {};
a4.toString(); //error -> Error Meaningless [object Object]

let a5 = { toString: function () { return "custom impl"; } }
a5.toString(); //ok -> "custom impl"

class Foo {
    toString() { return "custom impl" }
}
let a6 = new Foo();
a6.toString(); //ok -> "custom impl"

class Bar { };
let a7 = new Bar();
a7.toString(); //error -> Error Meaningless [object Object]

let a8 = Symbol("test");
a8.toString(); //ok -> "Symbol(test)"

let a9 = function () { };
a9.toString(); //ok -> "function () { }"
```

## Checklist

My suggestion meets these guidelines:
* [ ] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by jcready** [comment]
You'd also have to prevent `String({})` to accomplish your goal.

**Comment by RyanCavanaugh** [comment]
This can be done today by removing `toString` from lib.d.ts's definition of `Object`.

Designing an entire commandline flag around one function's particular return value isn't a very good complexity tradeoff. The implicit cases where `toString` gets invoked are much more pernicious and is something we do have open suggestions on.

**Comment by rjmunro** [comment]
> This can be done today by removing toString from lib.d.ts's definition of Object.

@RyanCavanaugh How do I do that in practise?

I just spent a day struggling to find out where the un-awaited promise was in some code that was emitting `[object Promise]` instead of some text. It turned out I had done `data = await fse.readFile(filename).toString();`. The fix is `data = (await fse.readFile(filename)).toString();`. This strongly feels like the kind of bug typescript should catch - it catches most other cases of not awaiting a promise.
