### ISSUE TITLE
Why did I restore the traditional mode?

### ISSUE THREAD

**Issue by JHeLiu** [Microsoft/TypeScript#26351]
Why did I restore the traditional mode, the next time I open VS 2017, it opens to me by default, I don't want this new mode, because it will cause the JS file written by my own local project to not prompt, which is annoying, or you can use the new The language service, also prompt me the function of the JS file in the local project? Is there such a solution?

**Comment by RyanCavanaugh** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.
