### ISSUE TITLE
Subtype of all subtype of specific type

### ISSUE THREAD

**Issue by Ailrun** [Microsoft/TypeScript#26354]
## Search Term
Subtype

## Suggestion

As far as I know, the only existing type that is subtype of some class of types is bottom type, i.e., subtype of *all type*.
However, with `strictFunctionTypes`, one would need something like following.
```ts
interface Monad<T> {
  chain<U>(f: (arg: T) => Monad<U>): Monad<U>;
}
class Specific<T> implements Monad<T> {
  chain<U>(f: (arg: T) => Specific<U>): Specific<U>;
}
```
This does not work since `Monad<T>` in the type of `chain` is in contravariant position, since it requires `Specific<T>` to be a supertype of `Monad<T>`. If there is `SubtypeOf<T>`, which is the subtype of all types those are subtype of `T`, we can do
```ts
interface Monad<T> {
  chain<U>(f: (arg: T) => SubtypeOf<Monad<U>>): Monad<U>;
}
class Specific<T> implements Monad<T> {
  chain<U>(f: (arg: T) => Specific<U>): Specific<U>;
}
```
since `SubtypeOf<Monad<T>>` is subtype of `Specific<T>`.
This also should not allow following, since `{ chain: string }` is not a subtype (or a supertype) of `Monad<U>`.
```ts
class NotAllowed<T> implements Monad<T> {
  chain<U>(f: (arg: T) => { chain: string }): Monad<T>
}
```

## Use Cases

When you want to make an interface for all type that satisfy some specific restriction.

## Examples

```ts
interface Monad<T> {
  chain<U>(f: (arg: T) => SubtypeOf<Monad<U>>): Monad<U>;
}
class Specific<T> implements Monad<T> {
  chain<U>(f: (arg: T) => Specific<U>): Specific<U>;
}
```

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by AlCalzone** [comment]
I'm not sure if I understand correctly, but when I try your code on https://agentcooper.github.io/typescript-play with `strictFunctionTypes`, the implementation in `Specific<T>` is fine, while the one on `NotAllowed<T>` shows an error for wrong types.

**Comment by Ailrun** [comment]
@AlCalzone Thank you for your comment! I notice that the problem occurs for more specific case only. Following will emit an error.
```ts
type Ap<T> = <U>(wf: Applicative<(arg: T) => U>) => Applicative<U>;

interface Applicative<T> {
    ap: Ap<T>;
}

interface Monad<T> extends Applicative<T> {}

declare class Specific<T> implements Monad<T> {
    ap<U>(f: Specific<(arg: T) => U>): Specific<U>;
    chain<U>(f: (arg: T) => Specific<U>): Specific<U>;
}
```
[Playground URL](https://goo.gl/vp2Vx1)

The error also is not emitted when I use `ap<U>(wf: Applicative<(arg: T) => U>): Applicative<U>` instead of `Ap<T>`.

**Comment by Ailrun** [comment]
I will open a bug report instead of feature request. (Is it even a bug?)
