### ISSUE TITLE
'esnext.array' doesn't enable access to Array.prototype.flat()

### ISSUE THREAD

**Issue by AbakumovAlexandr** [microsoft/TypeScript#26361]
**TypeScript Version:**  3.1.0-dev.201xxxxx

**Search Terms:** esnext, esnext.array, Array.prototype.flat()

**Code**

```
// greeter.ts

function greeter(persons: string[]) {
    return "Hello, " + persons.flat().join();
}

var user: string[] = ["Jane User"];

document.body.innerHTML = greeter(user);


// tsconfig.json
{
  "files": [
    "greeter.ts"
  ],
  "compilerOptions": {
    "target": "esnext",
    "lib": [
      "es2017",
      "esnext.array",
      "dom"
    ]
  }
}
```

**Expected behavior:**
Should compile successfully. According to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat), it's an experimental API supported by multiple browsers already.

**Actual behavior:**
Compilation error:

>     greeter.ts:2:32 - error TS2339: Property 'flat' does not exist on type 'string[]'.
> 
>     2 return "Hello, " + persons.flat().join(); ~~~~

**[Playground Link](https://www.typescriptlang.org/play/#src=function%20greeter(persons%3A%20string%5B%5D)%20%7B%0D%0A%20%20%20%20return%20%22Hello%2C%20%22%20%2B%20persons.flat().join()%3B%0D%0A%7D%0D%0A%0D%0Avar%20user%3A%20string%5B%5D%20%3D%20%5B%22Jane%20User%22%5D%3B%0D%0A%0D%0Adocument.body.innerHTML%20%3D%20greeter(user)%3B%0D%0A)**

**Comment by kitsonk** [comment]
`.flat` is specified in `lib.esnext.array.d.ts`:

https://github.com/Microsoft/TypeScript/blob/ef7997cb73ce46081cbfebc0edd2a0295ba30c33/lib/lib.esnext.array.d.ts#L152-L222

It feels like something else is going on.  It won't work in the playground because it doesn't support changing things like the libs and target.

**Comment by kitsonk** [comment]
Your `tsconfig.json` doesn't contain any `files` or `include` properties.  How are you compiling `greeter.ts`?  At the moment, the config file would not apply to the `greeter.ts` in something like Visual Studio code.

**Comment by AbakumovAlexandr** [comment]
@kitsonk , yes, I've made sure `flat()` is there in `lib.esnext.array.d.ts` before creating this.

I compiled it with `tsc greeter.ts` hoping that `tsc` would pick up `tsconfig.json`. I've just tried again with `files` section added (see updated initial post) and the error is the same.

**Comment by kitsonk** [comment]
@AbakumovAlexandr try `tsc -p .` instead...

**Comment by AbakumovAlexandr** [comment]
@kitsonk just tried `tsc -p tsconfig.json` with the same error. Does it work for you?

**Comment by kitsonk** [comment]
```
$ tsc --version
Version 3.0.1
$ tsc -p .
```

No errors output, `greeter.js` that is emitted:

```js
function greeter(persons) {
    return "Hello, " + persons.flat().join();
}
var user = ["Jane User"];
document.body.innerHTML = greeter(user);
```

I even with `typescript@next`:

```
$ tsc --version
Version 3.1.0-dev.20180810
$ tsc -p .
```

Again, no errors... 🤷‍♂️

**Comment by RyanCavanaugh** [comment]
@AbakumovAlexandr what's the output of `tsc -v` ?

**Comment by AbakumovAlexandr** [comment]
@kitsonk I think I've figured out the source of the issue thanks to the feedback from your side!

I've switched local TypeScript versions only, while my global stays 2.9.2. So it's always compliled with TS 2.9.2. But in 2.9.2, `flat()` was called `flatten()`. That's why it couldn't find it.

Unfortunately, `tsc` doesn't prints its version to the console leaving a room for confusion. If you, guys, feel like you'd like to implement it, let me know and I'll create a different issue for that.

**Comment by AbakumovAlexandr** [comment]
@RyanCavanaugh see my above comment, please.

**Comment by kitsonk** [comment]
It does print to the console with `--version` and most compilers are implicitly silent.

**Comment by AbakumovAlexandr** [comment]
@Favna Thank you for reporting this! This is really interesting. Since I don't think the order of `lib`s should matter, this also could be a clue for TS team to figure the issue out.

**Comment by Favna** [comment]
@ernie-h please read my solution above

**Comment by ernie-h** [comment]
@Favna I've tried loading the lib configs in your order as well, but that does not work for me.

**Comment by Favna** [comment]
@ernie-h I've got 2 more ideas then

1. What is your NodeJS version (node -v)? I know for a fact that on runkit.com `array.prototype.flat` is not available in Node 10 LTS, but it is when setting it to Node 11 Current. So if you have lower, consider upgrading. If you use Linux or MacOS you could consider using NVM so you can switch back easily if that's not the resolution.

Note that I personally use Node 11. 

2. Here is an exact copy of my tsconfig, maybe you need to configure other settings, such as the `moduleResolution` to `node`

```json
{
	"compilerOptions": {
		"outDir": "dist/",
		"rootDir": "./src",
		"forceConsistentCasingInFileNames": true,
		"esModuleInterop": true,
		"lib": ["esnext.array", "es2018", "dom"],
		"target": "es6",
		"module": "commonjs",
		"moduleResolution": "node",
		"newLine": "lf",
		"noFallthroughCasesInSwitch": true,
		"noImplicitAny": true,
		"noImplicitReturns": true,
		"noImplicitThis": true,
		"noUnusedLocals": true,
		"removeComments": true,
		"resolveJsonModule": true
	},
	"include": ["src/**/*.ts"],
	"exclude": ["node_modules", "dist", "src/**/*.js"]
}
```

**Comment by MaxfieldLewin** [comment]
Updating to Node 11 also resolved this issue for me. The ordering of items in `lib` does not seem to have an effect, nor does `moduleResolution`.

**Comment by Favna** [comment]
Ye Node 11 is the reason why it works as it has the feature internally (and also the fact that the newer V8 engine it has supports it). I think on that note this issue can pretty much be closed. Maybe the feature will eventually be backported to LTS (V10 at time of writing) but that is far outside the scope of this issue.

**Comment by kikar** [comment]
I'm having a similar problem, it looks like TS is not transpiling the `.flat()` method to previous versions of node, like it would do for `async/await` for example.

Node: v10.16.0
Typescript: v3.5.2
```json
{
  "compilerOptions": {
    "incremental": true,
    "target": "es2018",
    "module": "commonjs",
    "lib": ["esnext"],
    "strict": true,
    "moduleResolution": "node",
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true
  }
}
```
```ts
const flatArr = [[1], [2]].flat().join(',');
console.log(flatArr);
```

To compile, I'm running the command `npx tsc -p .`

The output is:
```js
"use strict";
const flatArr = [[1], [2]].flat().join(',');
console.log(flatArr);
```

The output is wrong because in the target (es2018), Array.prototype.flat does not exists.

**Comment by RyanCavanaugh** [comment]
TypeScript has never downleveled method calls to built-in APIs

**Comment by kikar** [comment]
Thank you for your reply Ryan.
I find this a bit confusing, how does TS decide what to transpile and what not to?
Like decorators, async/await yes, but built in APIs no? Is it documented anywhere?

**Comment by kitsonk** [comment]
TypeScript transpiles language syntax, not functionality.  `async`/`await` is language syntax, `Array.prototype.flat()` is functionality.  Items described in a type library (`lib`) are not transpiled.

Even with syntax there are certain caveats, like `--downlevelIteration` is behind a flag, because it requires that other functionality needs to be polyfilled in environments where it is targeted, which TypeScript won't provide.

**Comment by DominicTobias** [comment]
How can I get this error to go away since I'm fine with not supporting IE and don't want TS to bloat my bundle with any polyfills? (I'm assuming that's what lib does even though it's not exactly clear from the docs)

**Comment by RyanCavanaugh** [comment]
>  don't want TS to bloat my bundle with any polyfills

TypeScript never generates polyfills, so you don't need to do anything

**Comment by DominicTobias** [comment]
> > don't want TS to bloat my bundle with any polyfills
> 
> TypeScript never generates polyfills, so you don't need to do anything

Ohhhh I see, good to know 👌
