### ISSUE TITLE
lib.dom.d.ts includes bad IE11 defn's

### ISSUE THREAD

**Issue by alexeagle** [Microsoft/TypeScript#2636]
The section 
IE11 ECMAScript Extensions
(https://github.com/Microsoft/TypeScript/blob/master/bin/lib.dom.d.ts#L636)
contains eg.
```
declare var Map: {
    new <K, V>(): Map<K, V>;
    prototype: Map<any, any>;
}
```

But the spec says that Map should have a copy constructor:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map

This causes compile errors for projects which use that constructor. (eg. Angular)

**Comment by mhegazy** [comment]
Fixed in #2739
