### ISSUE TITLE
Narrowed type of variable isn't obtained by aliases of the variable

### ISSUE THREAD

**Issue by sandersn** [Microsoft/TypeScript#26372]
```js
function f() {}
f.p = { x: "" };
const p = f.p;
if (1 + 1 < 2) {
    f.p = { x: 0 };
}
f.p.x = 0;
p.x.toUpperCase(); // No compile error, crash at runtime
```

**Expected behavior:**

Error on `p.x.toUpperCase()`

**Actual behavior:**
No error.

**Comment by sandersn** [comment]
Unfortunately, this bug repros with any variable:

```ts
var ex: { x: string } | { x: number } = { x: "" }
const p = ex
if (1 + 1 < 2) {
    ex = { x: 0 }
}
ex.x = 0
p.x.toUpperCase();
```

**Comment by sandersn** [comment]
@ahejlsberg I believe this bug exposes a design limitation of the control flow algorithm that we don't intend to fix. Can you confirm?

**Comment by RyanCavanaugh** [comment]
Aliasing effects are definitely missed
