### ISSUE TITLE
JS: Allows illegal assignment to function properties

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#26371]
**TypeScript Version:**  3.1.0-dev.20180810

**Code**

```ts
const f = () => 0;
f.call = 0;
useF(f);

/** @param {() => number} f */
function useF(f) {
    f.call(null);
}
```

**Expected behavior:**

Error on assigning `f.call` since that would change the type.
On this topic, `f.length` should be readonly.

**Actual behavior:**

No error (at compile time).

**Comment by sandersn** [comment]
This is not a JS problem; the same hole exists in TS:

```ts
declare const f: { () => number, length: string, call: number };
function useF(f: () => number) {
  f.call(f.length)
}
```

I opened https://github.com/Microsoft/TypeScript/issues/29449 to track that hole, although it's been there forever, so I don't know if it's worth fixing.
