### ISSUE TITLE
Incorrectly inferred type from conditional return type (and superfluous type annotation)

### ISSUE THREAD

**Issue by theseyi** [Microsoft/TypeScript#26383]
**TypeScript Version:**  3.0.1 && 3.0.1-insiders.20180726

**Search Terms:** conditional types keyof return 

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
interface IKey {
  aKey: string;
}

type CondType<T> = T extends undefined ? string : T extends Extract<keyof IKey, 'string'> ? number : never;

function CondTest<T>(arg?: T): CondType<T> {
  if (typeof arg === 'string' && ({ aKey: ''}).hasOwnProperty(arg)) {
    return 1;
  }

  return 'string';
}

const x = CondTest<'aKey'>('aKey'); // never :expected number
const y = CondTest<undefined>(); // string
```

**Expected behavior:**
- variable t to be inferred type `number`
- also, why is there a need to explicitly annotate the generic type in the function invocation?
**Actual behavior:**
- variable t is of inferred type `never`

**Playground Link:** 
https://www.typescriptlang.org/play/index.html#src=interface%20IKey%20%7B%0A%20%20aKey%3A%20string%3B%0A%7D%0A%0Atype%20CondType%3CT%3E%20%3D%20T%20extends%20undefined%20%3F%20string%20%3A%20T%20extends%20Extract%3Ckeyof%20IKey%2C%20'string'%3E%20%3F%20number%20%3A%20never%3B%0A%0Afunction%20CondTest%3CT%3E(arg%3F%3A%20T)%3A%20CondType%3CT%3E%20%7B%0A%20%20if%20(typeof%20arg%20%3D%3D%3D%20'string'%20%26%26%20(%7B%20aKey%3A%20''%7D).hasOwnProperty(arg))%20%7B%0A%20%20%20%20return%201%3B%20%2F%2F%20Type%20'1'%20is%20not%20assignable%20to%20type%20'CondType%3CT%3E'.%0A%20%20%7D%0A%0A%20%20return%20'1'%3B%20%2F%2FType%20'%221%22'%20is%20not%20assignable%20to%20type%20'CondType%3CT%3E'.%0A%7D%0A%0Aconst%20t%20%3D%20CondTest%3C'aKey'%3E('aKey')%3B%20%2F%2F%20type%20is%20never%20%3Aexpected%20number%0Aconst%20y%20%3D%20CondTest%3Cundefined%3E()%3B%20%2F%2F%20string%20%3Aexpected%20string
**Related Issues:**

**Comment by RyanCavanaugh** [comment]
I think you want
```ts
type CondType<T> = T extends undefined ? string : T extends Extract<keyof IKey, T> ? number : never;
```

TS currently doesn't infer whether the control flow of a function correctly matches a conditional type, nor could it in this case due to the right operand of `&&` in the `if`. You'll need to use a type assertion in both return statements

**Comment by theseyi** [comment]
```ts
interface IKey {
  aKey: string;
}

type CondType<T> = T extends undefined ? string : T extends Extract<keyof IKey, T> ? number : never;

function CondTest<T extends undefined | string>(arg?: T): CondType<T> {
  if (typeof arg === 'string' && ({ aKey: ''}).hasOwnProperty(arg)) {
    return <CondType<T>>1;
  }

  return <CondType<T>>'1';
}

const t = CondTest('aKey'); // OK, number :expected number


const y = CondTest(); //? never :expected string
const z = CondTest(void 0); //? string | number :expected string
```

Thanks for your response @mattmccutchen , yes that's what I meant, pasted the incorrect permutation, however, in the updated version above and here ([playground](https://www.typescriptlang.org/play/index.html#src=interface%20IKey%20%7B%0A%20%20aKey%3A%20string%3B%0A%7D%0A%0Atype%20CondType%3CT%3E%20%3D%20T%20extends%20undefined%20%3F%20string%20%3A%20T%20extends%20Extract%3Ckeyof%20IKey%2C%20T%3E%20%3F%20number%20%3A%20never%3B%0A%0Afunction%20CondTest%3CT%20extends%20undefined%20%7C%20string%3E(arg%3F%3A%20T)%3A%20CondType%3CT%3E%20%7B%0A%20%20if%20(typeof%20arg%20%3D%3D%3D%20'string'%20%26%26%20(%7B%20aKey%3A%20''%7D).hasOwnProperty(arg))%20%7B%0A%20%20%20%20return%20%3CCondType%3CT%3E%3E1%3B%0A%20%20%7D%0A%0A%20%20return%20%3CCondType%3CT%3E%3E'1'%3B%0A%7D%0A%0Aconst%20t%20%3D%20CondTest('aKey')%3B%20%2F%2F%20OK%2C%20number%20%3Aexpected%20number%0A%0A%0Aconst%20y%20%3D%20CondTest()%3B%20%2F%2F%3F%20never%20%3Aexpected%20string%0Aconst%20z%20%3D%20CondTest(void%200)%3B%20%2F%2F%3F%20string%20%7C%20number%20%3Aexpected%20string)), supplying a string argument is OK. However, it seems `undefined` needs to be explicitly supplied to get a union type, even though a literal string is expected for `const z`, also `const y` is never? I'm assuming this is because an actual value is not supplied?

@RyanCavanaugh thanks for the inference clarification

**Comment by mattmccutchen** [comment]
@theseyi After enabling `strictNullChecks`, I get the results you say you expect.

**Comment by theseyi** [comment]
thank you @mattmccutchen cheers
