### ISSUE TITLE
Conditional type instantiates all branches for all types in a union

### ISSUE THREAD

**Issue by WorldSEnder** [Microsoft/TypeScript#26387]
**TypeScript Version:**  3.0.1

**Search Terms:** conditional types, union, branching

```ts
const Marker = Symbol("GenericArgumentSymbol");
interface FooType { [Marker]: string }

type BranchingDecision<T> = {
    1: T extends FooType ? number : string,
    2: T,
}[T extends FooType ? 1 : 2];

type Problematic = BranchingDecision<FooType | void>;
```

**Expected behavior:**
- `Problematic = number | void`
- The FooType part of the union should infer `number` via branch 1, the void part infers `void` via branch 2 resulting in a union of 2 types.

**Actual behavior:**
- `Problematic = number | string | FooType | void`
- It seems that both branches 1 and 2 are instantiated for both FooType and void, resulting in a union of 4 types.

[**Playground Link** ](http://www.typescriptlang.org/play/#src=const%20Marker%20%3D%20Symbol(%22GenericArgumentSymbol%22)%3B%0Ainterface%20FooType%20%7B%20%5BMarker%5D%3A%20string%20%7D%0A%0Atype%20BranchingDecision%3CT%3E%20%3D%20%7B%0A%20%20%20%201%3A%20T%20extends%20FooType%20%3F%20number%20%3A%20string%2C%0A%20%20%20%202%3A%20T%2C%0A%7D%5BT%20extends%20FooType%20%3F%201%20%3A%202%5D%3B%0A%0Atype%20Problematic%20%3D%20BranchingDecision%3CFooType%20%7C%20void%3E%3B)

**Related Issues:**

**Comment by mattmccutchen** [comment]
I believe this is working as intended.  Unions are not decomposed until you hit a distributive conditional type, and each conditional type is evaluated independently; I don't see what other behavior would be sane in general.  To get the behavior you want, you should write this:
```ts
const Marker = Symbol("GenericArgumentSymbol");
interface FooType { [Marker]: string }

type BranchingDecision<T> = T extends infer U ? {
    1: U extends FooType ? number : string,
    2: U,
}[U extends FooType ? 1 : 2] : never;

type Problematic = BranchingDecision<FooType | void>;
```

**Comment by WorldSEnder** [comment]
Okay, I believe I understand now. `T extends infer U` will actually trigger distributive behaviour. The first time I read it, `extends infer` felt like just introducing an alias but it seems to do a bit more.

A bit unintuitive maybe but in hindside it makes sense. In the original code, even though the branch is distributed the `T` inside is still the union type.
