### ISSUE TITLE
Node JS Intellisense - requested ability to ignore variables in `require` paths allowing jsconfig to complete the intellisense link

### ISSUE THREAD

**Issue by peterfox1** [microsoft/TypeScript#26388]
**Search Terms:**

Node intellisense require not working with variable in the path "no definition found" even with a jsconfig file

**Code**

Example code is also committed here: https://github.com/peterfox1/vscode-require-bug

Config file not necessary, but it's an example of a typical use-case in a larger project with many directories since it simplifies all the require calls to be consistent regardless of the file location.
/config.js
```js
global.__base = __dirname + '/';
```

/classes/MyClass.js
```js
class MyClass {
	sayHello() {
		console.log('hello');
	}
}
module.exports = MyClass;
```

*example of where the issue happens:*
/example.js
```js
//require('config.js');

var __base = './';	// shows that it's not related to it being a global variable.

const MyClass = require(__base + 'classes/MyClass.js');	// If `__base + ` was just ignored, then the jsconfig would allow intellisense to work

var myClass = new MyClass();
myClass.sayHello();	// Intellisense: "No definition found for "sayHello"
```

*If the include was parsed as "require('classes/MyClass.js');" then it will work fine with the following jsconfig*
/jsconfig.json
```
{
	"compilerOptions": {
		"target": "ES6",
		"baseUrl": "."
	}
}
```

**Expected behavior:**

Any variables in the require call to be ignored/striped out when being parsed for intellisense:
E.g. It should read `require(__base + 'classes/MyClass.js');` as if it's `require('classes/MyClass.js');` which will make the intellisense work due to the jsconfig.json file.

**Actual behavior:**

Intellisense will not link up to the required class/module.

**Related Issues:** 
The following issue is very similar, but they are using a variable for the entire require which couldn't be solved easily.
https://github.com/Microsoft/TypeScript/issues/18656

**Comment by andy-ms** [comment]
If we simply skipped `__base` without verifying its value, some people might complain when we give them a module that doesn't actually match what they load at runtime...

It is possible to have a genuine global import while still having simple string literal module specifiers --  `ln -s ../src node_modules/self`. Then you can import `src/foo.js` with `"self/foo"` regardless of where the import is coming from. In bigger projects, a tool like lerna would also allow you to structure your code as packages which can import from each other with non-relative syntax.

**Comment by peterfox1** [comment]
Hm yeah, I agree that it would introduce a chance that an incorrect module could be matched and in those scenarios it could seem unusual why it's matched them - but they would be quite specific cases since the string portion must still result in a valid path.

The cases for mismatching I can foresee could be something like this, where you define the file as a variable and part of the path is read as the module if it has no slashes:
`require(path + 'tests' + testfile);` becomes `require('tests');` 

Or if you are including a file from another directory via variable but there happens to be one in the same directory as your current file:
`require(path + 'config.js');` becomes `require('config.js');` 

The primary issue at this time is that there's no way to configure the editor to auto-complete in this setup without structuring an application in a particular way, whereas other editors offer the ability to auto-complete purely based on class names regardless of the require. I also tried JSDoc types but jsconfig seems to ignore files using `module.exports / export default`.

Thanks for your insight into lerna or using symbolic links, I will look into these for future applications. This can primarily be an issue for work on projects that are already setup this way or where it could be awkward to create a number of changes or sym links just for the editor.

**Comment by RyanCavanaugh** [comment]
This doesn't seem to be a very common scenario based on the lack of feedback here. Declining.
