### ISSUE TITLE
allow parent of shadowed variable type to be inferred, perhaps with operator

### ISSUE THREAD

**Issue by ORESoftware** [Microsoft/TypeScript#26385]
Here comes the nuance, get ready for it. I have this scenario:

```js
export type Task = (cb: EVCb<any>) => void;
const q = async.queue<Task, any>((task, cb) => task(cb), 1);

export const getGitRepoPath = function (dir: string, remote: string, cb: EVCb<GitRepoPath>) {
  
  q.push(cb => {
    
    const k = cp.spawn('bash');
    
    const result = <GitRepoPath>{
      exitCode: null as number,
      path: ''
    };
    
    const cmd = `cd "${dir}" && git rev-parse --show-toplevel`;
    k.stdin.end(cmd);
    
    k.once('exit', code => {
      cb(code, result);
    });
    
  }, cb);
  
};
```

To achieve better type safety, what I could do is this:

```js
export type Task = (cb: EVCb<any>) => void;
const q = async.queue<Task, any>((task, cb) => task(cb), 1);

export const getGitRepoPath = function (dir: string, remote: string, cb: EVCb<GitRepoPath>) {
  
  q.push((cb: EVCb<GitRepoPath>)  => {   // <<<  duplicate the type declaration
    
    const k = cp.spawn('bash');
   // ....
    k.once('exit', code => {
      cb(code, result);
    });
    
  }, cb);
  
};
```

but what would be _more convenient_ is using _typeof_ like this:

```js
export type Task = (cb: EVCb<any>) => void;
const q = async.queue<Task, any>((task, cb) => task(cb), 1);

export const getGitRepoPath = function (dir: string, remote: string, cb: EVCb<GitRepoPath>) {
  
  q.push((cb: typeof cb)  => {   // <<< use typeof, instead of duplicating the type declaration
    
    const k = cp.spawn('bash');
   // ....
    k.once('exit', code => {
      cb(code, result);
    });
    
  }, cb);
  
};
```

the problem with using `typeof cb` is that it's self-referential to the immediate cb variable, instead of the parent scope. _But actually, it SHOULD refer to the parent scope not the immediate scope, because why would a declared variable type ever refer to itself? It wouldn't right?_

Here is the error I get:

![screenshot from 2018-08-10 23-23-49](https://user-images.githubusercontent.com/11139560/43988909-803f4444-9cf4-11e8-8da1-623afd9cdb67.png)

So what I am suggesting is maybe an operator that refers it to the parent scope:

```js
export type Task = (cb: EVCb<any>) => void;
const q = async.queue<Task, any>((task, cb) => task(cb), 1);

export const getGitRepoPath = function (dir: string, remote: string, cb: EVCb<GitRepoPath>) {
  
  q.push((cb: typeof ^cb)  => {   // use a made-up operator ^
    
    const k = cp.spawn('bash');
   // ....
    k.once('exit', code => {
      cb(code, result);
    });
    
  }, cb);
  
};
```

or whatever. Hopefully you get it.

**Comment by andy-ms** [comment]
You shouldn't need to provide *any* explicit type to `cb` if you have `noImplicitAny` enabled and `q` is well typed.

**Comment by andy-ms** [comment]
So the suggestion is for `x: typeof x` to always refer to an outer scope since the local `x` will always be an error?

**Comment by RyanCavanaugh** [comment]
There are probably a dozen different workarounds you could use here instead. We don't need new syntax or a bunch of confusing extra logic in name resolution to provide another different workaround.

**Comment by ORESoftware** [comment]
yup just an idea
