### ISSUE TITLE
Recognize 'constructor' as a special property when classes implement interfaces

### ISSUE THREAD

**Issue by pretodor** [Microsoft/TypeScript#26398]
In this code snippet:

```typescript
interface C1Constructor {
    new (): C1Instance<C1Constructor>;

    // Static properties ...
}
interface C2Constructor {
    new (): C2Instance<C2Constructor>;

    // Static properties ...
}

interface C1Instance<Constructor> {
    constructor: Constructor;

    // Instance properties ...

    // Prototype properties ...
}
interface C2Instance<Constructor> extends C1Instance<Constructor> {
    // Instance properties ...

    // Prototype properties ...
}

class C1 implements C1Instance<C1Constructor> {}
class C2 extends C1 implements C2Instance<C2Constructor> {}
```
currently errors are thrown in the last 2 lines.[1][2]

I propose that TypeScript recognizes 'constructor' as a special property when classes implement interfaces so that the above code will be valid.

The benefit of this will be that we will be able to check both the instance and static side of a class against interfaces.

---

[1]
> [ts]
> Class 'C1' incorrectly implements interface 'C1Instance<C1Constructor>'.
> Types of property 'constructor' are incompatible.
> Type 'Function' is not assignable to type 'C1Constructor'.
> Type 'Function' provides no match for the signature 'new (): C1Instance<C1Constructor>'.

[2]
> [ts]
> Class 'C2' incorrectly implements interface 'C2Instance<C2Constructor>'.
> Types of property 'constructor' are incompatible.
> Type 'Function' is not assignable to type 'C2Constructor'.
> Type 'Function' provides no match for the signature 'new (): C2Instance<C2Constructor>'.

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by pretodor** [comment]
I would like to point out it is currently possible to check the instance and static side of a class against interfaces via a different approach:

```typescript
interface C1Instance {
    // Instance properties ...

    // Prototype properties ...
}
interface C2Instance extends C1Instance {
    // Instance properties ...

    // Prototype properties ...
}

interface C1Constructor {
    new (): C1Instance;

    // Static properties ...
}
interface C2Constructor {
    new (): C2Instance;

    // Static properties ...
}

type C1 = C1Instance;
let C1: C1Constructor = class {};

type C2 = C2Instance;
let C2: C2Constructor = class extends C1 {};

let c1: C1 = new C1();
let c2: C2 = new C2();
```

**Comment by RyanCavanaugh** [comment]
Duplicate #1263 ?

**Comment by andy-ms** [comment]
Which links to #420 which is presumably still accepting PRs
