### ISSUE TITLE
Symbol properties lose type info by inheritance

### ISSUE THREAD

**Issue by olivr70** [Microsoft/TypeScript#26393]
**TypeScript Version:**  3.1.0-dev.20180807

**Search Terms:** Symbol indexers

**Code**
``` Typescript
// noImplicitAny enabled

const myLenSym = Symbol("myLen");

interface Indexable {
  [myLenSym]?:number;
}

function f(some:Indexable) {
  return some[myLenSym];
}

class IndexableImpl implements Indexable {
}

function f2(some: IndexableImpl) {
  some[myLenSym] = 10; // => compile error : Element implictely has any type
  return some[myLenSym]; // => compile error : Element implictely has any type
}
```

**Expected behavior:**
It should compile, as defining a Symbol property requires an index notation, although the class itself is not indexed

**Actual behavior:**
When noImplicitAny is enabled, comiler emits a "Element implictely has any type because ElementImpl has no indexed signature

**Playground Link:**[https://www.typescriptlang.org/play/...](https://www.typescriptlang.org/play/#src=const%20myLenSym%20%3D%20Symbol(%22myLen%22)%3B%0D%0A%0D%0Ainterface%20Indexable%20%7B%0D%0A%20%20%5BmyLenSym%5D%3F%3Anumber%3B%0D%0A%7D%0D%0A%0D%0Afunction%20f(some%3AIndexable)%20%7B%0D%0A%20%20return%20some%5BmyLenSym%5D%3B%0D%0A%7D%0D%0A%0D%0Aclass%20IndexableImpl%20implements%20Indexable%20%7B%0D%0A%7D%0D%0A%0D%0Afunction%20f2(some%3A%20IndexableImpl)%20%7B%0D%0A%20%20some%5BmyLenSym%5D%20%3D%2010%3B%0D%0A%20%20return%20some%5BmyLenSym%5D%3B%0D%0A%7D%0D%0A)

**Related Issues:** 
- #1863 Allow indexing with symbols

**Comment by mattmccutchen** [comment]
This is nothing specific to symbol properties:
```ts
interface Indexable {
  a?: number;
}

function f(some:Indexable) {
  return some.a;
}

class IndexableImpl implements Indexable {
}

function f2(some: IndexableImpl) {
  some.a = 10;  // error
  return some.a;  // error
}
```
When a class implements an interface, that does not automatically give it the members of the interface; it has to redeclare them if it wants them.  Failure to redeclare a required member is an error, while an optional member that is not redeclared is just lost.  See #340 for more information.  I believe this is working as intended.

**Comment by olivr70** [comment]
Yes you're right. 

I misinterpreted the error message.

Thanks
