### ISSUE TITLE
Dot Function for better pretty code.

### ISSUE THREAD

**Issue by dudubs** [Microsoft/TypeScript#26396]
The syntax:
`
type User = {name,age...};
let users: User[] = [...]

let names = users.map(.name) // inplace users.map(user=>user.map...)
let usersWithX = users.filter(.name.indexOf('X')>0) // inspect users.filter(user=>user...)
`

**Comment by andy-ms** [comment]
This is out of scope of the [design goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals) since it involves changing JavaScript's syntax.
