### ISSUE TITLE
Enhance DOM API completion by sourcing descriptions from MDN

### ISSUE THREAD

**Issue by octref** [Microsoft/TypeScript#26404]
At VS Code, we has been sourcing data from MDN to get up-to-date documentation and compatibility info. One example is: https://code.visualstudio.com/updates/v1_25#_new-css-pseudo-selectors-and-pseudo-elements-from-mdn, and more details are at:
- https://github.com/Microsoft/vscode-css-languageservice/issues/68
- https://github.com/mdn/data/issues/199

While chatting with @atopal last week, we thought it would be a great idea to make TypeScript source some documentation from MDN for a better auto-completion experience for JS/TS developers. For example, here is how DOM auto-completion looks like today:

![image](https://user-images.githubusercontent.com/4033249/44014573-822e8c54-9e81-11e8-9f10-1ce80d9acc31.png)

The problem is that `lib.dom.d.ts` does not contain description for probably 95% of the items. Users would be at a loss to know what each API offers and how to use them.

MDN currently offers an API to pull description for a specific endpoint. For example, this is the JSON API for `DOMParser`: https://developer.mozilla.org/en-US/docs/Web/API/DOMParser$json

The `summary` field is (once we remove the HTML and extract text): 

> The DOMParser interface provides the ability to parse XML or HTML source code from a string into a DOM Document.

It would be great if TypeScript could query MDN for each API without description and put the descriptions into `lib.dom.d.ts`, so that users could get much better auto-completion for DOM API.

From MDN side, they are also working on making MDN data more easily accessible by tooling: See https://discourse.mozilla.org/t/proposal-including-css-short-descriptions-in-mdn-data/30500.

/cc @atopal

**Comment by RyanCavanaugh** [comment]
This would be pretty sweet. Accepting PRs on the TSJS lib generator repo for something that does this.

**Comment by sandersn** [comment]
This is done now.
