### ISSUE TITLE
JSON file imported from node_modules included in build output

### ISSUE THREAD

**Issue by Hilzu** [Microsoft/TypeScript#26402]
**TypeScript Version:** 3.0.1 and 3.1.0-dev.20180810

**Search Terms:** resolveJsonModule json node_modules

**Code**

```ts
import draft04Schema from "ajv/lib/refs/json-schema-draft-04.json";
```

```json
{
  "compilerOptions": {
    "declaration": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "module": "CommonJS",
    "moduleResolution": "node",
    "noEmitOnError": true,
    "target": "ES2015",
    "strict": true,
    "outDir": "dist",
    "resolveJsonModule": false,
    "baseUrl": ".",
    "paths": {
      "*": ["node_modules/*", "src/types/*"]
    }
  },
  "include": ["src/**/*"]
}
```

**Expected behavior:**

The compiler outputs a file requiring `ajv/lib/refs/json-schema-draft-04.json`.

**Actual behavior:**

The compiler includes `json-schema-draft-04.json` in the build output but the module using it requires it from node_modules.

The json file is not being output with Typescript 2.9.2 using the same `tsconfig.json`.

The `resolveJsonModule` option doesn't seem to affect the output.

**Playground Link:** 

**Related Issues:**

**Comment by sheetalkamat** [comment]
Please provide complete repro steps, with where the ts file requiring json is located and json files locations as well. Note that in your compiler options specified above, `resolveJsonModule` is `false` so json import wont be resolved.

**Comment by Hilzu** [comment]
Here's a complete project that exhibits this issue and builds with 2.9.2 and 3.0.1: https://github.com/Hilzu/ts-import-json. 3.0.1 doesn't seem to need the module declaration for the external json file regardless of the `resolveJsonModule` setting.

The JSON file that I'm importing is part of the `ajv` npm package. Its full path in the project directory is `node_modules/ajv/lib/refs/json-schema-draft-04.json`.

Running the `build` script in the project copies the file under the `dist/` folder which is the build output folder. It creates a directory structure with `node_modules/` and `src/` folders. It seems strange that the file is copied because the compiled `index.js` file doesn't even use the file. It imports it directly from the npm package.

Running the same build with Typescript 2.9.2 instead of 3.0.1 doesn't copy the file and the output directory just has the compiled files from `src/`.
