### ISSUE TITLE
MessageEventSource.postMessage has no compatible call signatures

### ISSUE THREAD

**Issue by marcomura** [Microsoft/TypeScript#26403]
**TypeScript Version:**  3.0.0

``
Build:Cannot invoke an expression whose type lacks a call signature. Type '((message: any, targetOrigin: string, transfer?: any[]) => void) | ((message: any, transfer?: any...' has no compatible call signatures.
``

**Comment by mattmccutchen** [comment]
Looks intentional to me.  Before you can post a message to a MessageEventSource, you need to know whether it is a Window (which requires a targetOrigin parameter) or a MessagePort or ServiceWorker (which does not accept a targetOrigin parameter).

**Comment by RyanCavanaugh** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.

**Comment by marcomura** [comment]
What else do you need? A repro? The message has all the information you need

**Comment by lepture** [comment]
@marcomura it seems that you need to detect the `event.source` before using it. The `event.source` is type of `MessageEventSource`, while:

```
type MessageEventSource = WindowProxy | MessagePort | ServiceWorker;
// and
type WindowProxy = Window;
```

The solution could be:

```js
if (event.source instanceof Window) {
  event.source.postMessage('message', 'origin')
}
```

**Comment by neekey** [comment]
@lepture `event.source instanceof Window` will return false for me. You should probably use:

```
!(e.source instanceof MessagePort) && !(e.source instanceof ServiceWorker)
```

**Comment by yuyang545262477** [comment]
another resolve:
` (<Window>event.source).postMessage('message', 'origin')`

**Comment by Bloodsucker** [comment]
I believe there's a still a problem in here since neither of the proposed solutions works in all cases.

The solution of using:

```typescript
if (event.source instanceof Window) {
  event.source.postMessage('message', 'origin')
}
```

Does not work in all cases. Specifically if the source object is wrapped (Window != WindowProxy).

The suggestion of using:
```typescript
if( !(e.source instanceof MessagePort) && !(e.source instanceof ServiceWorker) ) {
     event.source.postMessage('message', 'origin')
}
```

Does not work if the browsers does not support MessagePort or ServiceWorker. Which are all at this moment. The code will just crash.

Checking if these classes exist with:
```typescript
if (
    (typeof MessagePort != 'undefined' && e.source instanceof MessagePort) ||
    (typeof ServiceWorker != 'undefined' && e.source instanceof ServiceWorker)
)
    return;
event.source.postMessage('message', 'origin')
```
But the Typescript static compiler complains and does not allow the compilation.

The only option is force casting the type

```typescript
(<Window>event.source).postMessage('message', 'origin')
```
but that's playing with fire.

Any suggestion on what to do from here?

**Comment by Cecil0o0** [comment]
```js
if (event.source instanceof WindowClient) {
  event.source.postMessage('message');
}
```

It works for me!

**Comment by KashubaK** [comment]
Not entirely sure if this is the right direction, but to extend on @Bloodsucker's ideas:

```typescript
export function messageEventSourceIsWindow(source: MessageEventSource): source is Window {
  return (
    (!('MessagePort' in window) || !(source instanceof MessagePort)) &&
    (!('ServiceWorker' in window) || !(source instanceof ServiceWorker)) &&
    !!source.postMessage
  );
}

window.addEventListener('message', (e) => {
  if (!messageEventSourceIsWindow(e.source)) return;
  
  e.source.postMessage('Hello world!');
});
```

One could improve this by adding better assertions in the `messageEventSourceIsWindow` to further ensure that `source` is a proper `Window`, but I only really cared about `postMessage`, so.

**Comment by Pyrolistical** [comment]
I ran into this today when attempting to postMessage from an iframe to the parent.

`event.source.postMessage(message, event.origin, [someBuffer])` had a type error because typescript doesn't know to use 3 param Window.postMessage or 2 param MessagePort.postMessage.

Fortunately for me since I am in an iframe, I can simply use `window.parent.postMessage(message, event.origin, [someBuffer])` to avoid this issue.

**Comment by nikitakot** [comment]
There is also a `postMessage(message: any, options?: WindowPostMessageOptions): void;` declaration which seems to work in Chrome for both `Window | MessageEventSource` types.

**Comment by mujtabaidrees94** [comment]
> I ran into this today when attempting to postMessage from an iframe to the parent.
> 
> `event.source.postMessage(message, event.origin, [someBuffer])` had a type error because typescript doesn't know to use 3 param Window.postMessage or 2 param MessagePort.postMessage.
> 
> Fortunately for me since I am in an iframe, I can simply use `window.parent.postMessage(message, event.origin, [someBuffer])` to avoid this issue.

This saved my life, Thanks :)
