### ISSUE TITLE
Intersection breaks generic key field inference

### ISSUE THREAD

**Issue by jeremybparagon** [Microsoft/TypeScript#26409]
**TypeScript Version:**  3.1.0-dev.20180810

**Code**

```ts
const f = <T extends { [K0 in K]: string; } & { cool: string; }, K extends keyof T>(t: T, k: K) =>
{
  const s: string = t[k];
};
```

**Expected behavior:**  Successful compilation

**Actual behavior:**  I get the following error:
```
error TS2322: Type 'T[K]' is not assignable to type 'string'.

     const s: string = t[k];
           ~
```

**Playground Link:** [Link](https://www.typescriptlang.org/play/#src=const%20f%20%3D%20<T%20extends%20%7B%20%5BK0%20in%20K%5D%3A%20string%3B%20%7D%20%26%20%7B%20cool%3A%20string%3B%20%7D%2C%20K%20extends%20keyof%20T>(t%3A%20T%2C%20k%3A%20K)%20%3D>%0D%0A%7B%0D%0A%20%20const%20s%3A%20string%20%3D%20t%5Bk%5D%3B%0D%0A%7D%3B%0D%0A)

**Additional Notes:**  This compiles successfully ([link](https://www.typescriptlang.org/play/#src=const%20f%20%3D%20<T%20extends%20%7B%20%5BK0%20in%20K%5D%3A%20string%3B%20%7D%20%26%20%7B%20cool%3A%20string%3B%20%7D%2C%20K%20extends%20keyof%20T>(t%3A%20T%2C%20k%3A%20K)%20%3D>%0D%0A%7B%0D%0A%20%20const%20s%3A%20string%20%3D%20t%5B'cool'%5D%3B%0D%0A%7D%3B%0D%0A)):
```ts
const f = <T extends { [K0 in K]: string; } & { cool: string; }, K extends keyof T>(t: T, k: K) =>
{
  const s: string = t['cool'];
};
```
as does this ([link](https://www.typescriptlang.org/play/#src=const%20f%20%3D%20<T%20extends%20%7B%20%5BK0%20in%20K%5D%3A%20string%3B%20%7D%2C%20K%20extends%20keyof%20T>(t%3A%20T%2C%20k%3A%20K)%20%3D>%0D%0A%7B%0D%0A%20%20const%20s%3A%20string%20%3D%20t%5Bk%5D%3B%0D%0A%7D%3B%0D%0A)):
```ts
const f = <T extends { [K0 in K]: string; }, K extends keyof T>(t: T, k: K) =>
{
  const s: string = t[k];
};
```

**Comment by ahejlsberg** [comment]
The issue here is that we're not examining all constraints of indexed access types in type relations, rather we jump straight to base constraints.

In exploring the issue I also discovered that this errors where it shouldn't:

```ts
const f = <T extends { [P in K | "cool"]: string; }, K extends keyof T>(t: T, k: K) =>
{
    const s: string = t[k];
    t.cool;  // Error, but shouldn't be
};
```

I'll put up a PR with a fix shortly.

**Comment by aleclarson** [comment]
The OP's playground is failing again. [link](https://www.typescriptlang.org/play/#src=const%20f%20%3D%20%3CT%20extends%20%7B%20%5BK0%20in%20K%5D%3A%20string%3B%20%7D%20%26%20%7B%20cool%3A%20string%3B%20%7D%2C%20K%20extends%20keyof%20T%3E(t%3A%20T%2C%20k%3A%20K)%20%3D%3E%0D%0A%7B%0D%0A%20%20const%20s%3A%20string%20%3D%20t%5Bk%5D%3B%0D%0A%7D%3B%0D%0A)
