### ISSUE TITLE
Loading of static members in memory

### ISSUE THREAD

**Issue by bharukaRupesh** [microsoft/TypeScript#26406]
Hi,
I am using static members(properties and methods) in my typescript code. However, I have a question with respect to memory like ```when are static members loaded in memory?``` **at the time of compilation or each time we access them in our code?**

**Comment by andy-ms** [comment]
This is a JavaScript question, not a TypeScript question, so this isn't the best place to ask.

Anyway, static properties are initialized when the class is declared, even if the class is never accessed.
```ts
function sideEffect() {
    console.log("hi");
    return 0;
}
class C {
    static x = sideEffect();
}
```

The program prints "hi" even though `C` is never accessed.

**Comment by bharukaRupesh** [comment]
Thanks @andy-ms for your kind response.

**Comment by andy-ms** [comment]
@bharukaRupesh It should work. Are you sure you set it before trying to access it?

**Comment by bharukaRupesh** [comment]
Yeah, I am setting the value before I use it before I use it as below,

```
setSomeValue( );                //calling a method to set the value
console.log(XYZClass.someVar);  //accessing the value but getting 'undefined'
```

Note: 
1. ```setSomeValue( );``` is a ```non-static method``` in which I am setting up the value of ```static field```

2. I am using typescript class which contains this setSomeValue( ); method but I am calling this method from other spec file as I am using protractor framework to write the automation tests.

**Comment by andy-ms** [comment]
Can you try and come up with a short example that you can post that doesn't use external frameworks?
