### ISSUE TITLE
Rest arguments don't work with mapped types

### ISSUE THREAD

**Issue by ikokostya** [Microsoft/TypeScript#26414]
**TypeScript Version:**  `3.1.0`, `3.1.0-dev.20180810`

**Search Terms:**

mapped types, rest parameters

**Code**

```ts
interface A {
    emit(event: string, ...args: any[]): boolean;
}

type Args<F> = F extends (...args: infer A) => void ? A : never;

type EventMap = Record<string, Function>;

interface B<M extends EventMap> extends A {
    emit<Event extends keyof M>(event: Event, ...args: Args<M[Event]>): boolean;
}
```

**Expected behavior:**

No errors.

**Actual behavior:**

Compile error:

```
t.ts:9:11 - error TS2430: Interface 'B<M>' incorrectly extends interface 'A'.
  Types of property 'emit' are incompatible.
    Type '<Event extends keyof M>(event: Event, ...args: Args<M[Event]>) => boolean' is not assignable to type '(event: string, ...args: any[]) => boolean'.

9 interface B<M extends EventMap> extends A {
     
```

If I add any overload for `emit` function error is gone, e.g.:

```diff
interface A {
    emit(event: string, ...args: any[]): boolean;
}

type Args<F> = F extends (...args: infer A) => void ? A : never;

type EventMap = Record<string, Function>;

interface B<M extends EventMap> extends A {
    emit<Event extends keyof M>(event: Event, ...args: Args<M[Event]>): boolean;
+   emit(event: 'foo'): boolean;
}
```

**Playground Link:**  [link](http://www.typescriptlang.org/play/index.html#src=interface%20A%20%7B%0A%20%20%20%20emit(event%3A%20string%2C%20...args%3A%20any%5B%5D)%3A%20boolean%3B%0A%7D%0A%0Atype%20Args%3CF%3E%20%3D%20F%20extends%20(...args%3A%20infer%20A)%20%3D%3E%20void%20%3F%20A%20%3A%20never%3B%0A%0Atype%20EventMap%20%3D%20Record%3Cstring%2C%20Function%3E%3B%0A%0Ainterface%20B%3CM%20extends%20EventMap%3E%20extends%20A%20%7B%0A%20%20%20%20emit%3CEvent%20extends%20keyof%20M%3E(event%3A%20Event%2C%20...args%3A%20Args%3CM%5BEvent%5D%3E)%3A%20boolean%3B%0A%7D%0A)

**Related Issues:**

**Comment by ikokostya** [comment]
> A claims that e.g. emit("foo", 10, '"z") is a valid call for any A, but this is clearly not a valid call for any B

Yes, but `B` is not used in the example. Error happens in place of extending. In the following example `emit("foo", 10, '"z")` is not a valid call for any `C`

```ts
interface A {
    emit(event: string, ...args: any[]): boolean;
}

interface C extends A {
    emit(event: 'foo'): boolean;
}

declare let c: C;
c.emit("foo", 10, '"z"'); // error: Expected 1 arguments, but got 3
```

Also, as I mention in description, compilation is **successful** if to add *any* other overload for `emit` method:

```ts
interface A {
    emit(event: string, ...args: any[]): boolean;
}

type Args<F> = F extends (...args: infer A) => void ? A : never;

type EventMap = Record<string, Function>;

interface B<M extends EventMap> extends A {
    emit<Event extends keyof M>(event: Event, ...args: Args<M[Event]>): boolean;
    emit(event: 'foo'): boolean; // <-- add this
}
```

or if provide argument for `Args` type explicitly:

```ts
interface A {
    emit(event: string, ...args: any[]): boolean;
}

type Args<F> = F extends (...args: infer A) => void ? A : never;

type EventMap = Record<string, Function>;

interface B<M extends EventMap> extends A {
    emit<Event extends keyof M>(event: Event, ...args: Args<(x: number) => void>): boolean;
}
```

**Comment by ikokostya** [comment]
If change declaration of `EventMap` type to

```ts
type EventMap = Record<string, (...args: any[]) => void>;
```

then most common type for interface `B`

```ts
interface B<M extends EventMap> extends A {
    emit<Event extends keyof M>(event: Event, ...args: Args<M[Event]>): boolean;
}
```

is

```ts
interface C extends A {
    emit(event: string, ...args: Args<(...args: any[]) => void>): boolean;
}
```

But latest interface compiles without error: [playground link](http://www.typescriptlang.org/play/index.html#src=interface%20A%20%7B%0A%20%20%20%20emit(event%3A%20string%2C%20...args%3A%20any%5B%5D)%3A%20boolean%3B%0A%7D%0A%0Atype%20Args%3CF%3E%20%3D%20F%20extends%20(...args%3A%20infer%20A)%20%3D%3E%20void%20%3F%20A%20%3A%20never%3B%0A%0Atype%20EventMap%20%3D%20Record%3Cstring%2C%20(...args%3A%20any%5B%5D)%20%3D%3E%20void%3E%3B%0A%0Ainterface%20C%20extends%20A%20%7B%0A%20%20%20%20emit(event%3A%20string%2C%20...args%3A%20Args%3C(...args%3A%20any%5B%5D)%20%3D%3E%20void%3E)%3A%20boolean%3B%0A%7D)

**Comment by AlCalzone** [comment]
> But why compilation is successful if to add other overload for emit method?

Because 
```ts
emit(event: 'foo'): boolean; // <-- add this
```
is compatible with the declaration in A:
```ts
emit(event: string, ...args: any[]): boolean;
```
In that case, `args` is `[]`, in other words no parameters.

**Comment by ikokostya** [comment]
@AlCalzone  Why original declaration of `emit` becomes compatible in this case?

**Comment by ikokostya** [comment]
@RyanCavanaugh Could you explain behavior from https://github.com/Microsoft/TypeScript/issues/26414#issuecomment-412691346 ?
