### ISSUE TITLE
Expose `getOutputJavaScriptFileName` from tsbuild

### ISSUE THREAD

**Issue by andrewbranch** [microsoft/TypeScript#26410]
## Suggestion

As discussed with @RyanCavanaugh in https://github.com/TypeStrong/ts-loader/issues/815, export the currently internal function `getOutputJavaScriptFileName` from `src/compiler/tsbuild.ts`: https://github.com/Microsoft/TypeScript/blob/fe387cc7f0739256337771e62398a565fbcf82c1/src/compiler/tsbuild.ts#L291-L297

For symmetry, maybe it would make sense also to export `getOutputDeclarationFileName` and possibly `getOutputFileNames`, but those aren’t needed immediately.

## Use Cases

TL;DR: support https://github.com/TypeStrong/ts-loader/issues/815 without duplicating logic from the TS compiler.

When using `program.getSourceFile()` on a `*.ts` file that's part of a project reference, the result describes the `*.d.ts` file built by the composite project (if it’s built). Because there are several compiler options which change where files get emitted (e.g. `declarationDir`), it’s not quite trivial to figure out where the corresponding `*.js` file is. In the issue linked above, we need to read that plain JavaScript file into Webpack in order to take advantage of the fact that project references have already been built.

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

---

I'm happy to make the accompanying PR if it sounds good to you all. Since the function will become public, should there be a unit test added for it, or does coverage by existing tsbuild tests suffice?

**Comment by ajafff** [comment]
> it would make sense also to export `getOutputDeclarationFileName` and possibly `getOutputFileNames`

I need those functions to exclude outputs of referenced projects from linting.

**Comment by benmccann** [comment]
`getOutputFileNames` is currently exposed, but does not seem to work properly. It causes issues in the Rollup plugin, which tries to use it (https://github.com/rollup/plugins/issues/287#issuecomment-674552597, https://github.com/rollup/plugins/issues/287#issuecomment-736315536)

**Comment by RyanCavanaugh** [comment]
@benmccann can you please log a separate issue with steps to reproduce, and we can take a look? Thanks!

**Comment by andrewbranch** [comment]
FWIW the original motivation of this issue is no longer relevant, as other new APIs handled project references support in ts-loader more holistically. I think it would be ok to close this.
