### ISSUE TITLE
TypeError: Cannot read property 'set' of undefined

### ISSUE THREAD

**Issue by diubick** [microsoft/TypeScript#26435]
**TypeScript Version:**  3.1.0-dev.201xxxxx

**Search Terms:**

**Code**
[TypeScript/lib/tsc.js]()
```ts
       function trackReferencedAmbientModule(node, symbol) {
            var directives = resolver.getTypeReferenceDirectivesForSymbol(symbol, 67108863);
            if (ts.length(directives)) {
                return recordTypeReferenceDirectivesIfNecessary(directives);
            }
            var container = ts.getSourceFileOfNode(node);
            refs.set("" + ts.getOriginalNodeId(container), container);
        }
```

**Expected behavior:**
 compile project is fine, but cannot create definition file `*.d.ts` for this
**Actual behavior:**
  variable `refs` is not defined (line 61116), becouse refs has no implemintation, but if I set it to `refs=ts.createMap();` (line 61094) everything is ok.

**Playground Link:** 

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
How do you reproduce this behavior?
