### ISSUE TITLE
function interface?

### ISSUE THREAD

**Issue by spitWind** [Microsoft/TypeScript#26436]
THE ISSUE TRACKER IS NOT FOR QUESTIONS.

DO NOT CREATE A NEW ISSUE TO ASK A QUESTION.

IF YOU ARE HAVING PROBLEMS WITH YOUR TYPESCRIPT CODE, DO NOT ASK A QUESTION HERE.

Tens of thousands of TypeScript questions have been asked and answered on StackOverflow; see https://stackoverflow.com/questions/tagged/typescript . You can ask questions there or on other websites.

The only exception is if you have a question about *the TypeScript compiler API itself*. Please post a complete example of what you're trying to do and precisely describe what your question is.

```
interface lengthwise{
  length: number;
}
interface MyFunction<ResTp,ThisTp,ParmaTp>{
  (this:ThisTp,...arg:ParmaTp[]):ResTp;
}
function helpCall<R1,T1,P1>(arg:MyFunction<R1,T1,P1>):MyFunction<R1,T1,P1>{//传入什么类型，返回什么类型
// return T;
  // arguments
  return ;
}
let w=helpCall((w:String)=>{})

w.call//?
w.apply//?
w.bind
```
how to fill it

**Comment by AlCalzone** [comment]
> DO NOT CREATE A NEW ISSUE TO ASK A QUESTION.

> how to fill it

This looks like a question.

**Comment by RyanCavanaugh** [comment]
The template is for *other* people to read, I guess.
