### ISSUE TITLE
Generic type changes from default to {} (unknown) when constructor receives parameter.

### ISSUE THREAD

**Issue by vtulin** [microsoft/TypeScript#26442]
**TypeScript Version:**  3.0.0-dev.201xxxxx

**Search Terms:** 
Generic type changes from default to {} (unknown) when constructor receives argument.

**Code**
```ts
export interface ITest {

  prop1: string;

  prop2: string;

}

export class Test<T = ITest> implements ITest {

  public prop1: string;

  public prop2: string;

  constructor(_props?: T) {
    const psKey = Object.keys(_props);
    for (let sKey of psKey) {
      this[sKey] = _props[sKey];
    }
  }

}

let a = new Test();
```

**Expected behavior:**
Should suggest default generic type argument while creating object with arguments.
Check snapshots below.

**Actual behavior:**
```ts
let a = new Test();
```
[Shows correct generic type while constructor without arguments](https://imgur.com/a/EtiYW4a)
```ts
let a = new Test({
});
```
[Shows {} type while constructor with arguments](https://imgur.com/a/h4MMr8r)

**Playground Link:**  
Not applicable.

**Related Issues:**

**Comment by DanielRosenwasser** [comment]
Generic defaults are selected when there are no candidates to infer a type argument. In this case, the type system infers the type `{}` from the object literal. Is there a reason why this makes a difference to you though?

**Comment by vtulin** [comment]
@DanielRosenwasser the difference is that `{}` allows to input whatever you want, no strict type, no validation, no intelisense.

**Comment by vtulin** [comment]
I find out that when I made `<T extends ITest = ITest>` constructor typed input works, but this workaround is not applicable everywhere.
