### ISSUE TITLE
Allow providing a class' generic type in expression: `typeof MyClass<T>.prototype.myFunction`.

### ISSUE THREAD

**Issue by d-ph** [microsoft/TypeScript#26456]
## Search Terms

typeof generic method in generic class

## Suggestion

In case of a generic method in a generic class, allow to provide the class' generic type when using `typeof` operator. Please don't try to understand the previous sentence and instead go straight to the following section.

## Use Cases

I need this to define Bluebird's Promise methods on the global `interface Promise` without copying and pasting. However, the requested feature seems like something that could have a broader use.

Current behaviour of `typeof` correctly takes the type of a generic method, however it defaults the type of generic class to `any`, which leads to a compilation error.

An example of current behaviour (a stripped-down version of a problem tracked by https://github.com/DefinitelyTyped/DefinitelyTyped/issues/28081):
```typescript
type IterableItem<R> = R extends Iterable<infer U> ? U : never;
type Resolvable<R> = R | PromiseLike<R>;
type IterateFunction<T, R> = (item: T, index: number, arrayLength: number) => Resolvable<R>;

declare class Bluebird<R> {
    map<U>(
        mapper: IterateFunction<IterableItem<R>, U>
    ): Bluebird<R extends Iterable<any> ? U[] : never>;
}

interface Promise<T> {
    map: typeof Bluebird.prototype.map;
}

declare var promise: Promise<number>;

promise.map((n: number) => false);
```
When `strict: true` is used for compilation (or specifically: `strictFunctionTypes: true`), then the last line produces an error:
```
error TS2345: Argument of type '(n: number) => boolean' is not assignable to parameter of type 'IterateFunction<{}, boolean>'.
  Types of parameters 'n' and 'item' are incompatible.
    Type '{}' is not assignable to type 'number'.
```
TypeScript expects type `{}` for `item`, because the generic type `<R>` is lost when `typeof Bluebird.prototype.map` is used. See the following screenshot:
![image](https://user-images.githubusercontent.com/4347095/44122317-3d77a2ee-a01b-11e8-9179-bce1dd9f7c78.png)

The current behaviour can be reproduced in TypeScript playground: [link](https://www.typescriptlang.org/play/index.html#src=type%20IterableItem%3CR%3E%20%3D%20R%20extends%20Iterable%3Cinfer%20U%3E%20%3F%20U%20%3A%20never%3B%0Atype%20Resolvable%3CR%3E%20%3D%20R%20%7C%20PromiseLike%3CR%3E%3B%0Atype%20IterateFunction%3CT%2C%20R%3E%20%3D%20(item%3A%20T%2C%20index%3A%20number%2C%20arrayLength%3A%20number)%20%3D%3E%20Resolvable%3CR%3E%3B%0A%0Adeclare%20class%20Bluebird%3CR%3E%20%7B%0A%20%20%20%20map%3CU%3E(%0A%20%20%20%20%20%20%20%20mapper%3A%20IterateFunction%3CIterableItem%3CR%3E%2C%20U%3E%0A%20%20%20%20)%3A%20Bluebird%3CR%20extends%20Iterable%3Cany%3E%20%3F%20U%5B%5D%20%3A%20never%3E%3B%0A%7D%0A%0Ainterface%20Promise%3CT%3E%20%7B%0A%20%20%20%20map%3A%20typeof%20Bluebird.prototype.map%3B%0A%7D%0A%0Adeclare%20var%20promise%3A%20Promise%3Cnumber%3E%3B%0A%0Apromise.map((n%3A%20number)%20%3D%3E%20false)%3B) (but you need to enable the `strictFunctionTypes` option)

## Examples

The new feature would allow devs to write the following:
```typescript
interface Promise<T> {
    map: typeof Bluebird<T>.prototype.map;
}
```
This would tell TypeScript to use the Promise's T generic type as Bluebird's R generic type (instead of defaulting to `any`).

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

Thank you.

**Comment by aaronjensen** [comment]
We appear to perhaps be able to get what we want by doing:

```ts
type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>
interface Promise<T> extends Omit<Bluebird<T>, 'then' | 'catch' | 'finally'> {}
```

(we could use `Pick` as well), but by doing so I still run into variance issues. `Bluebird<any>` are not assignable to `Promise<string>`:

[See repro](https://www.typescriptlang.org/play/index.html#src=type%20Resolvable%3CR%3E%20%3D%20R%20%7C%20PromiseLike%3CR%3E%3B%0Atype%20Omit%3CT%2C%20K%20extends%20keyof%20T%3E%20%3D%20Pick%3CT%2C%20Exclude%3Ckeyof%20T%2C%20K%3E%3E%0A%0Adeclare%20class%20Bluebird%3CR%3E%20%7B%0A%20%20call%3CU%20extends%20keyof%20R%3E(propertyName%3A%20U%2C%20...args%3A%20any%5B%5D)%3A%20Bluebird%3CR%5BU%5D%20extends%20(...args%3A%20any%5B%5D)%20%3D%3E%20any%20%3F%20ReturnType%3CR%5BU%5D%3E%20%3A%20never%3E%3B%0A%20%20then%3CU%3E(onFulfill%3F%3A%20(value%3A%20R)%20%3D%3E%20Resolvable%3CU%3E%2C%20onReject%3F%3A%20(error%3A%20any)%20%3D%3E%20Resolvable%3CU%3E)%3A%20Bluebird%3CU%3E%3B%20%2F%2F%20For%20simpler%20signature%20help.%0A%20%20then%3CTResult1%20%3D%20R%2C%20TResult2%20%3D%20never%3E(%0A%20%20%20%20%20%20onfulfilled%3F%3A%20((value%3A%20R)%20%3D%3E%20Resolvable%3CTResult1%3E)%20%7C%20null%2C%0A%20%20%20%20%20%20onrejected%3F%3A%20((reason%3A%20any)%20%3D%3E%20Resolvable%3CTResult2%3E)%20%7C%20null%0A%20%20%20%20)%3A%20Bluebird%3CTResult1%20%7C%20TResult2%3E%3B%0A%20%20catch(onReject%3A%20(error%3A%20any)%20%3D%3E%20Resolvable%3CR%3E)%3A%20Bluebird%3CR%3E%3B%0A%20%20catch%3CU%3E(onReject%3A%20((error%3A%20any)%20%3D%3E%20Resolvable%3CU%3E)%20%7C%20undefined%20%7C%20null)%3A%20Bluebird%3CU%20%7C%20R%3E%3B%0A%20%20readonly%20%5BSymbol.toStringTag%5D%3A%20%22Promise%22%0A%7D%0A%0Ainterface%20Promise%3CT%3E%20extends%20Omit%3CBluebird%3CT%3E%2C%20'then'%20%7C%20'catch'%3E%20%7B%0A%7D%0A%0Adeclare%20const%20b%3A%20Bluebird%3Cany%3E%0Aconst%20b2%3A%20Bluebird%3Cstring%3E%20%3D%20b%0Aconst%20p%3A%20Promise%3Cstring%3E%20%3D%20b%0A)

**Comment by RyanCavanaugh** [comment]
Like this?
```ts
interface Promise<T> {
    map: Bluebird<T>["map"];
}
```
Produces no errors in the Playground

**Comment by aaronjensen** [comment]
Ah, of course. Thank you. Though, it still has the same issue with not being able to assign a `Bluebird<any>` to a `Promise<string>`:

[repro](https://www.typescriptlang.org/play/index.html#src=type%20Resolvable%3CR%3E%20%3D%20R%20%7C%20PromiseLike%3CR%3E%3B%0Atype%20Omit%3CT%2C%20K%20extends%20keyof%20T%3E%20%3D%20Pick%3CT%2C%20Exclude%3Ckeyof%20T%2C%20K%3E%3E%0A%0Adeclare%20class%20Bluebird%3CR%3E%20%7B%0A%20%20call%3CU%20extends%20keyof%20R%3E(propertyName%3A%20U%2C%20...args%3A%20any%5B%5D)%3A%20Bluebird%3CR%5BU%5D%20extends%20(...args%3A%20any%5B%5D)%20%3D%3E%20any%20%3F%20ReturnType%3CR%5BU%5D%3E%20%3A%20never%3E%3B%0A%20%20then%3CU%3E(onFulfill%3F%3A%20(value%3A%20R)%20%3D%3E%20Resolvable%3CU%3E%2C%20onReject%3F%3A%20(error%3A%20any)%20%3D%3E%20Resolvable%3CU%3E)%3A%20Bluebird%3CU%3E%3B%20%2F%2F%20For%20simpler%20signature%20help.%0A%20%20then%3CTResult1%20%3D%20R%2C%20TResult2%20%3D%20never%3E(%0A%20%20%20%20%20%20onfulfilled%3F%3A%20((value%3A%20R)%20%3D%3E%20Resolvable%3CTResult1%3E)%20%7C%20null%2C%0A%20%20%20%20%20%20onrejected%3F%3A%20((reason%3A%20any)%20%3D%3E%20Resolvable%3CTResult2%3E)%20%7C%20null%0A%20%20%20%20)%3A%20Bluebird%3CTResult1%20%7C%20TResult2%3E%3B%0A%20%20catch(onReject%3A%20(error%3A%20any)%20%3D%3E%20Resolvable%3CR%3E)%3A%20Bluebird%3CR%3E%3B%0A%20%20catch%3CU%3E(onReject%3A%20((error%3A%20any)%20%3D%3E%20Resolvable%3CU%3E)%20%7C%20undefined%20%7C%20null)%3A%20Bluebird%3CU%20%7C%20R%3E%3B%0A%20%20readonly%20%5BSymbol.toStringTag%5D%3A%20%22Promise%22%0A%7D%0A%0Ainterface%20Promise%3CT%3E%20%7B%0A%20%20call%3A%20Bluebird%3CT%3E%5B%22call%22%5D%3B%0A%7D%0A%0Adeclare%20const%20b%3A%20Bluebird%3Cany%3E%0Aconst%20b2%3A%20Bluebird%3Cstring%3E%20%3D%20b%0Aconst%20p%3A%20Promise%3Cstring%3E%20%3D%20b%0A)

<details>
<summary>Code</summary>
```ts
type Resolvable<R> = R | PromiseLike<R>;

declare class Bluebird<R> {
  call<U extends keyof R>(propertyName: U, ...args: any[]): Bluebird<R[U] extends (...args: any[]) => any ? ReturnType<R[U]> : never>;
  then<U>(onFulfill?: (value: R) => Resolvable<U>, onReject?: (error: any) => Resolvable<U>): Bluebird<U>; // For simpler signature help.
  then<TResult1 = R, TResult2 = never>(
      onfulfilled?: ((value: R) => Resolvable<TResult1>) | null,
      onrejected?: ((reason: any) => Resolvable<TResult2>) | null
    ): Bluebird<TResult1 | TResult2>;
  catch(onReject: (error: any) => Resolvable<R>): Bluebird<R>;
  catch<U>(onReject: ((error: any) => Resolvable<U>) | undefined | null): Bluebird<U | R>;
  readonly [Symbol.toStringTag]: "Promise"
}

interface Promise<T> {
  call: Bluebird<T>["call"];
}

declare const b: Bluebird<any>
const b2: Bluebird<string> = b
const p: Promise<string> = b
```
</details>

Should I file that as a separate issue or is it an existing issue somewhere?

**Comment by RyanCavanaugh** [comment]
Sounds like the core problem has been addressed. The assignability of ` =call: Bluebird<T>["call"];` is unfortunately a bit of of a design limitation due to the interaction of `R` in Bluebird's definition with its `call` property.
