### ISSUE TITLE
Instance property mutated in instance function assumed to be always null

### ISSUE THREAD

**Issue by heydenberk** [Microsoft/TypeScript#26454]
**TypeScript Version:**  3.1.0-dev.201xxxxx

**Search Terms:** type 'never'. setState componentDidMount async ajax promise then

**Code**

```ts
import React from "react";

interface StateType {
  data: { name: string } | null
}

class TestComponent extends React.Component<{}, StateType> {

  state = {
    data: null
  };

  componentDidMount() {
    this.setState({ data: { name: "Hariette" } });
  }

  render() {
    const { data } = this.state;
    let name = "world";
    if (data !== null) {
      name = data.name;
    }
    return <div>Hello, {name}</div>;
  }

}

export { TestComponent };
```

**Expected behavior:**
The code compiles and "Hello, Hariette" displays on a subsequent render.

**Actual behavior:**
```
error TS2339: Property 'name' does not exist on type 'never'.
22       name = data.name;
```

**Playground Link:** _omitted because of the react/JSX_

**Related Issues:** no

**Comment by DanielRosenwasser** [comment]
The initializer on the derived class is unfortunately independent of the base class's property type for `state`. You'll need an explicit annotation

```tsx
import React from "react";

interface StateType {
  data: { name: string } | null
}

class TestComponent extends React.Component<{}> {

  state: StateType = {
    data: null
  };

  componentDidMount() {
    this.setState({ data: { name: "Hariette" } });
  }

  render() {
    const { data } = this.state;
    let name = "world";
    if (data !== null) {
      name = data.name;
    }
    return <div>Hello, {name}</div>;
  }

}

export { TestComponent };
```

**Comment by RyanCavanaugh** [comment]
See also #10570

**Comment by heydenberk** [comment]
Thanks @DanielRosenwasser and @RyanCavanaugh. I'm happy to close this one in favor of #10570. I didn't come across it in my search, so I'll give some thought as to whether there's something to be done to make the other issue more discoverable in the specific way it manifested for me.

**Comment by RyanCavanaugh** [comment]
It's a hard issue for *us* to find; no worries 😉
