### ISSUE TITLE
May be a bug in type guards

### ISSUE THREAD

**Issue by AlexStacker** [Microsoft/TypeScript#26463]
**TypeScript Version:**  3.0.1

**Search Terms:**
type guards

**Code**
This is the sample code. I am going to print an http request value in the click event and output msg based on the returned code, but it is not successful.

```ts
interface StatusOK {
  code: 1;
  msg: string;
}

interface StatusNotOK {
  code: -1;
}

type Status = StatusOK | StatusNotOK;

let rst: Status = {code: 1, msg: 'OK'}

if (rst.code === 1) {
  console.log(rst.msg); // ok

  let element = document.getElementById('code');
  if(element) {
    element.addEventListener('click', function(){
        console.log(rst.msg); // Property 'msg' does not exist on type 'Status'.
                              // Property 'msg' does not exist on type 'StatusNotOK'.
    })
  }
}
```
I look forward to prompt the correct type

**Expected behavior:**
The results are the type of output an error.

**Actual behavior:**
Property 'msg' does not exist on type 'Status'.
  Property 'msg' does not exist on type 'StatusNotOK'.

**Playground Link:**
https://agentcooper.github.io/typescript-play/#code/JYOwLgpgTgZghgYwgAgMpjmArgZwPIDSyA3gFDLIID2AJhAFzICMA3OcgLY4DmjOYUUNzYBfUqVCRYiFOky4AclTCES7anUYBaVqTGkwATwAOsjNhzIAvGnO5VAH1vycSlQTakANhDDIo-IxyFtYkGgzMADScPIwA5IRx+sAwyAAUAWAAdOHWVjZMAJRqFNQgOFQ+WV5U3Bn8WVzchZ4UPn4QPhwQ4KE0VAhY3eBZ3L4Aol09YABChgCSNGlx4XEt7ClpnRDDYMVkFBTbu1lwNDTjAG7TADLA-D3QywhewAgA1nHRMFggCGDAKggNKFA6HcFlCpVGp1TKNHjrcEiQrsMQiIA

**Related Issues:** 
https://github.com/Microsoft/TypeScript/issues/2214

**Comment by mattmccutchen** [comment]
Working as intended; see #8541 for more information.

**Comment by RyanCavanaugh** [comment]
See also #9998 for extended discussion of types of guarded expressions in callbacks
