### ISSUE TITLE
FileReader, e.target.result (result - indefined)

### ISSUE THREAD

**Issue by bezrukovyura** [Microsoft/TypeScript#26466]
**
var reader = new FileReader();
        reader.onload = e => {
          var content = e.target.result;
          var base64 = content.split(",")[1];
          file.base64Data = base64;
          input.remove();
          deferred.resolve(file);
        }
**

e.target.result 
result - indefined

**Comment by RyanCavanaugh** [comment]
That is indeed code.

Please follow the template.
