### ISSUE TITLE
Implicit declaration merging can lead to wrong type information

### ISSUE THREAD

**Issue by pvolok** [Microsoft/TypeScript#26469]
## Search Terms

override global type
bypass declaration merging

## Suggestion

_I'm still new to TypeScript, so I might misunderstand something._

TypeScript does implicit [declaration merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html). That can potentially lead to wrong type information.

Take a look at this example:

```ts
interface Request {
  myField: string,
}

declare const req: Request;

req.body; // Global `Request` has this field, so it's not an error. Surprisingly.
```

That is almost exact problem I faced and which made me very confused. As far as I understand, namespaces could help to solve this problem, but not everyone is using namespaces. I could rename my `Request` interface, but the collision can happen later again if an interface with the same name appears in any included type libs. In the best case that would result in a type error, in the worst case TypeScript would miss an actual type error.

One workaround might be not to use interfaces and use Flow-style object type declarations:

```ts
type Request = { // Error: Duplicate identifier `Request`.
};
```

Here at least we would know about name collision. But AFAIK `interface` and `type` declarations are not the same, so this could lead to other issues.

## Checklist

My suggestion meets these guidelines:
* [ ] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by mattmccutchen** [comment]
Are you suggesting a change to TypeScript?  I don't see any obvious change to TypeScript that would be reasonable at this point and would help.  The best way to avoid the problem you describe is probably to put interface definitions in ES6 modules instead of making them global.

**Comment by pvolok** [comment]
Ideally merging would be explicit:

```ts
augment interface Request {
  myField: string;
}

declare const req: Request;

req.myField; // Exists
req.body; // Exists
```

```ts
interface Request { // Shadows global `Request` just like js values
  myField: string;
}

declare const req: Request;

req.myField; // Exists
req.body; // Doesn't exist!
```

This would be more consistent with how javascript deals with values.

I totally understand that that would be a breaking change. But features like strict null checks were introduced before (with flags). It would be more difficult here because all the lib definitions that use declaration merging would break.

On the other hand, implicit merging limits type safety guarantees that typescript could've provided otherwise.

---

> The best way to avoid the problem you describe is probably to put interface definitions in ES6 modules instead of making them global.

Are you suggesting not including `dom` into libs in tsconfig and then having something like this?

```ts
import {Request as DOMRequest} from 'dom';

interface Request {}

// here can use both without collisions
```

That would work. Though by default all users (like me) wouldn't be protected from their types being accidentally modified by included libs.

---

This behavior reminds me of monkey patching in javascript. It works most of the time, but when it breaks: it's hard to spot.

Having said that, I don't feel competent to propose solution as I'm not familiar with the typescript team's policy regarding breaking changes and type safety. If I understand correctly, unlike Flow, TypeScript's main goal is to provide code assist tools (as opposed to type safety guarantees). If that's true, I'm not sure if this issues is considered important.

**Comment by mattmccutchen** [comment]
> Are you suggesting not including `dom` into libs in tsconfig and then having something like this?

If your code is in a module (or a namespace for that matter, as you mentioned) and you define a `Request` interface, your interface should shadow the DOM one instead of augmenting it.  Let me know if this is not working.

**Comment by RyanCavanaugh** [comment]
>  If I understand correctly, unlike Flow, TypeScript's main goal is to provide code assist tools (as opposed to type safety guarantees).

This isn't an accurate accounting of the situation. Both Flow and TypeScript make trade-offs between soundness and usability in order to build type systems that can actually be used. We explicitly acknowledge this fact in our design goals, but that doesn't mean that type safety isn't our first goal; it just means we're honest it. There are many cases where TypeScript makes *more* guarantees in terms of safety than Flow does, and other cases where Flow's safety is stricter. TypeScript's default decision is still to make things typesafe and we only choose not to when the resulting behavior would be considered unusable in practice.

In terms of merging, this is the intended behavior. We don't plan to boil the ocean and break every existing user of this behavior. With modern modules, declaring things in the global scope should be increasingly rare.

**Comment by pvolok** [comment]
@mattmccutchen Oh, I didn't realize that files without imports/exports are not treated as modules. When I added an import, it shadowed global `Request` as expected. Sorry for reporting incorrect issue.
