### ISSUE TITLE
And expression inferrs wrong type.

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#26468]
**TypeScript Version:**  3.1.0-dev.201xxxxx

**Search Terms:**

**Code**

```ts
let b: boolean;
let s: string;

let x = b && s;
```

**Expected behavior:**

The inferred type of x is boolean | string;

**Actual behavior:**

The inferred type of x is string;

**Playground Link:** 

https://www.typescriptlang.org/play/#src=let%20b%3A%20boolean%3B%0D%0Alet%20s%3A%20string%3B%0D%0A%0D%0Alet%20x%20%3D%20b%20%26%26%20s%3B

**Related Issues:**

**Comment by AlCalzone** [comment]
Since the type of `x` seems to take the value of `b` into account, should the type even be `string`?
```ts
let b: boolean;
let s: string;

let x1 = b && s; // string, (which should it be? x1 is undefined)

b = true;
let x2 = b && s; // string

b = false;
let x3 = b && s; // boolean
```

**Comment by markusjohnsson** [comment]
With `strictNullChecks`, you will get `string | boolean`.

**Comment by RyanCavanaugh** [comment]
@ahejlsberg in non-SNC we should really be keeping the left operand type in the result when it's a primitive

**Comment by ahejlsberg** [comment]
We've discussed fixing this before, but decided against it because of the breaking change. Do we feel differently about this now?

In general, if you care about precise types you really should be using `--strictNullChecks` (where we type this correctly).

**Comment by RyanCavanaugh** [comment]
I don't recall that discussion. We could check RWC for impact - seems like we'd reveal a ton of subtle bugs

**Comment by RyanCavanaugh** [comment]
RWC results were nothing but false positives. Doesn't seem worth breaking at this point.
