### ISSUE TITLE
doc outdated in Type Inference -> Contextual Type -> example

### ISSUE THREAD

**Issue by deepkolos** [Microsoft/TypeScript#26472]
https://www.typescriptlang.org/docs/handbook/type-inference.html

mouseEvent has property button now

```js
window.onmousedown = function(mouseEvent) {
    console.log(mouseEvent.button);  //<- Error
};
```

![https://s1.ax1x.com/2018/08/15/PRwGuT.png](https://s1.ax1x.com/2018/08/15/PRwGuT.png)

**Comment by GuyKh** [comment]
I'm on it
