### ISSUE TITLE
Calculation w.r.t dates result in error.

### ISSUE THREAD

**Issue by sandeepkalra** [Microsoft/TypeScript#2647]
function f()
{
   var today: Date = new Date(),
        yesterday: Date = new Date(),
        tomorrow: Date = new Date(),
        tomorrow_in_ms: number = 0;

    today.setHours(0, 0, 0, 0);
    tomorrow.setHours(0, 0, 0, 0);
    yesterday.setHours(0, 0, 0, 0);

    tomorrow.setDate(tomorrow.getDate() + 1);
    yesterday.setDate(yesterday.getDate() - 1);

    tomorrow_in_ms = tomorrow - today; // from today till midnight
}

 results in error: 
" The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type "

**Comment by billccn** [comment]
This is actually one of the great features of TypeScript... I.e. `Date + Date` and `Date - Date` are now both illegal. Just add `.getTime()` to both operands. This makes the code clearer and restores the symmetry between the operators.

**Comment by sandeepkalra** [comment]
Thanks!

**Comment by DanielRosenwasser** [comment]
As @billccn said, this is intentional. You can use `tomorrow.getTime() - today.getTime()` or even `+tomorrow - +today`
