### ISSUE TITLE
In JS, prototype assignment isn't recognised in an IIFE

### ISSUE THREAD

**Issue by sandersn** [Microsoft/TypeScript#26476]
We might decide this is by design, but I suspect an awful lot of code in chrome-devtools-frontend relies on it working.

```js
(function() {
    var s = new StringStream('xxxxxxxxxxxxxxxxxxxxxxxx')
    s.backUp(1) // error here
    /** @constructor @param {string} string */
    function StringStream(string) {
    }
    StringStream.prototype = {
        /** @param {number} n */
        backUp: function(n) {this.pos -= n;},
    };
}())
```

**Expected behavior:**
No error on s.backUp

**Actual behavior:**
'StringStream' has no property 'backUp'.

**Comment by RyanCavanaugh** [comment]
@sandersn doesn't this code crash?

**Comment by DanielRosenwasser** [comment]
It will crash at runtime; ideally you could give a use-before-def error in this scenario. But if the method's used later on, it's totally okay.

**Comment by sandersn** [comment]
This no longer has an error.
