### ISSUE TITLE
Inline field initializers should be better documented

### ISSUE THREAD

**Issue by jasonbaker** [microsoft/TypeScript#26477]
One thing about typescript that I like is that it allows inline field initializers that can access fields defined in the constructor. [For example](https://www.typescriptlang.org/play/#src=class%20T%20%7B%0D%0A%20%20%20%20foo%20%3D%20this.bar%3B%0D%0A%0D%0A%20%20%20%20constructor(private%20readonly%20bar%3A%20string)%20%7B%20%7D%0D%0A%7D):

```typescript
class T {
    foo = this.bar;

    constructor(private readonly bar: string) { }
}
```

This ability doesn't seem to be documented anywhere that I can find, and it frequently throws people off the first time they see it. It would really be handy if this were better documented.

**Comment by jasonbaker** [comment]
As a side note, I'd add that I'm not really sure exactly what to call this functionality. Is "inline field initializer" the proper term?

**Comment by andy-ms** [comment]
It's documented under "Parameter properties" in the [handbook](https://www.typescriptlang.org/docs/handbook/classes.html).

**Comment by jasonbaker** [comment]
Parameter properties are. But being able to use a parameter property in a field initializer is not.

**Comment by andy-ms** [comment]
Parameter properties are properties, so they can be used in places a property can -- don't think that needs specific documentation.

**Comment by jasonbaker** [comment]
I feel like we're getting a little bit tied up on the parameter property thing. What I feel the documentation could be more clear about is how constructors are generated. Like consider the following snippet of code:

```
class T {
    foo = this.bar;
    baz: string;

    constructor(private readonly bar: string) { 
        this.baz = this.foo
    }
}
```

This generates the following constructor:

```
function T(bar) {
        this.bar = bar;
        this.foo = this.bar;
        this.baz = this.foo;
    }
```

I don't find it obvious that the constructor is defined as being (as far as I can tell):

1. Parameter properties
2. Inline field initializers
3. Constructor code

I think this could be better documented.
