### ISSUE TITLE
Official behavior of the keyof operator

### ISSUE THREAD

**Issue by djrichey** [microsoft/TypeScript#26478]
First, I apologize if this is not an appropriate question for this forum. However, I am looking for official, authoritative information about the behavior of the `keyof` operator and the only TypeScript language spec I'm finding is considerably out of date and doesn't mention `keyof` at all.

I realize that there is a "--keyofStringsOnly" compiler flag which affects the behavior of `keyof`. However, for the rest of this post, assume that that flag is not enabled.

Through experimentation, I have discovered that the result of the `keyof` operator applied to a class type excludes the keys of all non-public members of that class. I have found that it will include the keys all of the type's *public* members, including members with `number` or `symbol` keys. Further, I have found that the result will include the index type of the type to which `keyof` is applied if that type has an index signature. Finally, I have found that if the type has a function call signature, the `keyof` result does not incorporate that function call signature, presumably, because it has no way to do so. For reference, here is a (shortened) link to a sample in the TypeScript Playground page which demonstrates my findings: https://bit.ly/2MN7J1y

My question is, is this an accurate description of the behavior `keyof`? If so, is that the intended, official behavior? In other words, if I write code assuming that behavior, how reliable would those assumptions be in the long run? If not, what details about the behavior of `keyof` did I miss or get wrong or how might those details be prone to change?

To provide some context, for the purpose of creating reasonably type safe mocks in tests, I want to be able to automatically generate a type which represents the public subset of some given class which may have non-public members. Here is the construct which I am considering:
  `type PublicInterfaceOf<T> = {
      [P in keyof T]: T[P]
  };`

Empirically, I have found that that construct meets my needs. However, whether it really, reliably does what I think depends greatly on the behavior of `keyof`

Thanks in advance.

**Comment by RyanCavanaugh** [comment]
There's an introductory explanation in #11929

Your write-up sounds accurate to me; I don't see anything wrong though there may be additional aspects not covered by it.

Any change in this area would generally be a breaking change so we'd not do that without a good reason.
