### ISSUE TITLE
Intuitive != expected != actual behaviour when combining string and symbol keys

### ISSUE THREAD

**Issue by yortus** [microsoft/TypeScript#26470]
**TypeScript Version:**  3.1.0-dev.20180813

**Search Terms:** string index inference, string key inference

**Code**

```ts
// function foo takes an 'options' object that can have:
// (a) any number of string keys whose values are unary functions
// (b) an optional 'directive' unique symbol key with a unrelated type
const directive = Symbol('directive');
declare function foo<TArg, TRet, TDir>(options:
    {[x in string]: (arg: TArg) => TRet}    // all the string keys are unary functions
    & {[directive]?: TDir}                  // there is an optional 'directive' symbol key
): void;

// CASE 1
// ~~~ERROR~~~ - ... prop 'addOne' incompatible with index signature
//               ... 'x' and 'arg' are incompatible
//               ... 'string' not assignable to 'number'
let case1 = foo({
    [directive]: (x: string) => 'str',
    addOne: (x: number) => x + 1,
    double: (x: number) => x + x,
});

// CASE 2: identical to case 1 except for order of properties
// Compiles OK - infers TArg = number, TRet = number, TDir = (x: string) => string
let case2 = foo({
    addOne: (x: number) => x + 1,
    double: (x: number) => x + x,
    [directive]: (x: string) => 'str',
});

// CASE 3: identical to case 1 except for type of directive
// Compiles OK - infers TArg = number, TRet = number, TDir = string
let case3 = foo({
    [directive]: 'str',
    addOne: (x: number) => x + 1,
    double: (x: number) => x + x,
});
```

**Intuitive expected behaviour:**

All three cases compile without errors, with the string and symbol keys typed separately, since the type declaration clearly distinguishes the string keys from the symbol one.

**Expected behavior according to https://github.com/Microsoft/TypeScript/issues/26257#issuecomment-411896593:**

That comment suggests that all three cases should fail to compile, since the string index signature covers all symbol keys too, so any symbol key would have to conform to the string index signature, and they don't conform in any of the three cases in the code above.

**Actual behavior:**

Case 1 fails to compile, but Case 2 and 3 compile fine and in fact do type the string and symbol keys separately as intended by `foo`'s definition.

**Playground Link:** [here](http://www.typescriptlang.org/play/index.html#src=%2F%2F%20function%20foo%20takes%20an%20'options'%20object%20that%20can%20have%3A%0D%0A%2F%2F%20(a)%20any%20number%20of%20string%20keys%20whose%20values%20are%20unary%20functions%0D%0A%2F%2F%20(b)%20an%20optional%20'directive'%20unique%20symbol%20key%20with%20a%20unrelated%20type%0D%0Aconst%20directive%20%3D%20Symbol('directive')%3B%0D%0Adeclare%20function%20foo%3CTArg%2C%20TRet%2C%20TDir%3E(options%3A%0D%0A%20%20%20%20%7B%5Bx%20in%20string%5D%3A%20(arg%3A%20TArg)%20%3D%3E%20TRet%7D%20%20%20%20%2F%2F%20all%20the%20string%20keys%20are%20unary%20functions%0D%0A%20%20%20%20%26%20%7B%5Bdirective%5D%3F%3A%20TDir%7D%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20there%20is%20an%20optional%20'directive'%20symbol%20key%0D%0A)%3A%20void%3B%0D%0A%0D%0A%2F%2F%20CASE%201%0D%0A%2F%2F%20~~~ERROR~~~%20-%20...%20prop%20'addOne'%20incompatible%20with%20index%20signature%0D%0A%2F%2F%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20...%20'x'%20and%20'arg'%20are%20incompatible%0D%0A%2F%2F%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20...%20'string'%20not%20assignable%20to%20'number'%0D%0Alet%20case1%20%3D%20foo(%7B%0D%0A%20%20%20%20%5Bdirective%5D%3A%20(x%3A%20string)%20%3D%3E%20'str'%2C%0D%0A%20%20%20%20addOne%3A%20(x%3A%20number)%20%3D%3E%20x%20%2B%201%2C%0D%0A%20%20%20%20double%3A%20(x%3A%20number)%20%3D%3E%20x%20%2B%20x%2C%0D%0A%7D)%3B%0D%0A%0D%0A%2F%2F%20CASE%202%3A%20identical%20to%20case%201%20except%20for%20order%20of%20properties%0D%0A%2F%2F%20Compiles%20OK%20-%20infers%20TArg%20%3D%20number%2C%20TRet%20%3D%20number%2C%20TDir%20%3D%20(x%3A%20string)%20%3D%3E%20string%0D%0Alet%20case2%20%3D%20foo(%7B%0D%0A%20%20%20%20addOne%3A%20(x%3A%20number)%20%3D%3E%20x%20%2B%201%2C%0D%0A%20%20%20%20double%3A%20(x%3A%20number)%20%3D%3E%20x%20%2B%20x%2C%0D%0A%20%20%20%20%5Bdirective%5D%3A%20(x%3A%20string)%20%3D%3E%20'str'%2C%0D%0A%7D)%3B%0D%0A%0D%0A%0D%0A%2F%2F%20CASE%203%3A%20identical%20to%20case%201%20except%20for%20type%20of%20directive%0D%0A%2F%2F%20Compiles%20OK%20-%20infers%20TArg%20%3D%20number%2C%20TRet%20%3D%20number%2C%20TDir%20%3D%20string%0D%0Alet%20case3%20%3D%20foo(%7B%0D%0A%20%20%20%20%5Bdirective%5D%3A%20'str'%2C%0D%0A%20%20%20%20addOne%3A%20(x%3A%20number)%20%3D%3E%20x%20%2B%201%2C%0D%0A%20%20%20%20double%3A%20(x%3A%20number)%20%3D%3E%20x%20%2B%20x%2C%0D%0A%7D)%3B%0D%0A)

**Related Issues:**
Taken directly from https://github.com/Microsoft/TypeScript/issues/26257#issuecomment-411957368. But the issue containing that comment is marked as 'working as intended' so I thought it would be better to open a new issue for this specific case.

**Comment by yortus** [comment]
Another small example from #26257:

If `{[x: string]: T}` is intended to apply to *all* keys (i.e., strings, symbols and numbers), then shouldn't the following fail to compile, since the symbol key doesn't conform to the string index signature?

```ts
const SYM = Symbol();
declare function foo(obj: {[x: string]: number}): void;
foo({a: 1, [SYM]: 'sym'});  // Compiles fine
```

**Comment by yortus** [comment]
@RyanCavanaugh would you mind triaging this issue please?

**Comment by yortus** [comment]
Thanks @RyanCavanaugh. Can we clarify what the bug is here exactly? Is it that the string index seems to include symbol keys under certain conditions, or is it that the string index *doesn't* include symbol keys under certain conditions?

**Comment by yortus** [comment]
I see. If it turns out that symbols must conform to string indexes, then I hope some consideration is given to how to declare things like `foo` where we want to type string and symbol keys separately.

**Comment by weswigham** [comment]
3.2 is a no at this point, given it's size, I'd guess. I'm still pushing for it, though. It's just hard to convince the relevant parties that it is both the correct fix (easy) and worth the change (hard). This issue and the others linked in the fix don't make the best case for a change of that size, so it's slow going.

**Comment by yortus** [comment]
OK. Well the PR has a much broader scope of changes that what this issue raises. Would a more limited change have more chance of making progress - eg just stop string indexes from constraining symbol keys? The other changes could possibly be approached later if there is demand.

**Comment by weswigham** [comment]
So that's not really the issue here. The issue is that mapped types have a concept of mapping `symbol` keys, but no representation to map them into - so when we do inference, we end up discarding information (which is why the order matters). You _need_ symbol index signatures to fix this.

**Comment by weswigham** [comment]
> Your PR has quite a few upvotes. If it fixes known issues (like this one) and otherwise has little obvious impact, I guess there must be some other reason why the PR is facing resistance? Does it break anything or slow down the compiler or preclude other future features under consideration?

Just complexity. Index signatures are currently represented trivially internally, while  my change fleshes them out a bit more and makes them kroe generic.

**Comment by yortus** [comment]
> You need symbol index signatures to fix this.

You wouldn't need them to fix *this* issue though, right? I thought the problem here is *not* the lack of symbol index info. Rather, it's just that individual symbol properties are currently required to conform to string indexes when logically they shouldn't be.

**Comment by yortus** [comment]
Also @weswigham you mention this is a problem with mapped types, but the currently behaviour manifests with no mapped types anywhere, eg tsc acts the same if we change `foo` in the OP to:

```ts
declare function foo<TArg, TRet, TDir>(options:
    {[x: string]: (arg: TArg) => TRet}    // NB string indexer, not mapped type
    & {[directive]?: TDir}         
): void;
```

I don't know if the compiler treats that as a mapped type internally, but at least on the surface it appears to be an issue with string index signatures.

**Comment by yortus** [comment]
CC/ @rbuckton (since you made #21217).

**Comment by MattMcFarland** [comment]
What's the status on this?  Is there anything holding it up right now?
