### ISSUE TITLE
noUnusedParameters in an interface method implementation signature

### ISSUE THREAD

**Issue by TomasHubelbauer** [Microsoft/TypeScript#26480]
**TypeScript Version:**  2.9.2

**Search Terms:** ["noUnusedParameters interface"](https://github.com/Microsoft/TypeScript/issues?utf8=%E2%9C%93&q=is%3Aissue+noUnusedParameters+interface), doesn't look like it's there.

**Code**

```ts
class MyCompletionItemProvider implements vscode.CompletionItemProvider {
    public async provideCompletionItems(document: TextDocument, position: Position, token: CancellationToken, context: CompletionContext) {
…
```

**Expected behavior:** `token` doesn't get marked as unused. I mean, it is, but I cannot remove it, because then I would no longer be correctly implementing `CompletionItemProvider`.

**Actual behavior:** `token` does get marked as unused and with `noUnusedParameters` errors.

**Playground Link:** 

**Related Issues:** Not sure.

**Comment by sheetalkamat** [comment]
you can rename token as _token and the error will go away

**Comment by sheetalkamat** [comment]
There is quick fix to add underscore.
![image](https://user-images.githubusercontent.com/8052792/44170585-a80ba080-a08c-11e8-8c01-296d3a63beeb.png)

**Comment by TomasHubelbauer** [comment]
Apologies, I missed it.
