### ISSUE TITLE
Possible conflict with vscode-tslint in 3.0.1?

### ISSUE THREAD

**Issue by Jessidhia** [microsoft/TypeScript#26488]
**TypeScript Version:**  3.0.1

**Search Terms:** problems, diagnostics, tslint

**Code**

I have no idea what causes this.

The example screenshot in "Actual behavior" was caused after writing a trailing whitespace (!) in a valid file.

**Expected behavior:**

Diagnostics should show up in the Problem window.

**Actual behavior:**

![image](https://user-images.githubusercontent.com/73085/44199023-f6e53300-a17d-11e8-8b06-e386693d6e53.png)

The Problems listing is broken and shows crazy unrelated or non-existing diagnostics. Clicking on any of them does nothing. Correcting the trailing whitespace is enough to cause all messages to go away, but actual errors are not ever listed. Automatic import insertion is also broken.

---

This seems to only happen when vscode-tslint is enabled. Disabling vscode-tslint makes everything seemingly work correctly. I'm not sure if this is a vscode, tslint, vscode-tslint or typescript bug.

**Related issues:** https://github.com/Microsoft/TypeScript/issues/25487 is _sometimes_ printed in the tslint debug log.

**Comment by RyanCavanaugh** [comment]
My default would be to blame this on the extension. Can you give us a precise set of repro steps + exact list of what you have installed?

**Comment by Kovensky** [comment]
It seems I got a similar issue in another project even with `tslint` disabled; this time I think because of `eslint` warnings. Write a trailing whitespace, which should cause a lint warning, get a bunch of nonsense back.

VSCode 1.26.0, TypeScript 3.0.1, eslint plugin v1.4.12. I could reproduce this in a `.js` file from https://github.com/xivanalysis/xivanalysis.

**Comment by jtsom** [comment]
I'm seeing similar issues using an Angular application. Using VS Code Insider (Version 1.30.0-insider (1.30.0-insider))'s Typescript version (3.2.0-rc),and the Typescript TSLint Plugin (0.1.0)  I see: 

<img width="486" alt="image" src="https://user-images.githubusercontent.com/13488/48674027-09bd2a00-eb16-11e8-98fb-dd0506c8a84a.png">
 
If I switch to the Angular apps version of Typescript (3.1.6) the error goes away.

**Comment by RyanCavanaugh** [comment]
It seems like this has been fixed or was specific to something on OP's machine at the time
