### ISSUE TITLE
infer array type afterwards when implicitAny

### ISSUE THREAD

**Issue by cevek** [Microsoft/TypeScript#2648]
I think it would be nice to try to guess the type of generic after calling the constructor

```javascript
var arr = [];
arr.push(123);
arr.push("string"); // should be an error
```

```javascript
class Bar<T>{
  foo: T;
}
var bar = new Bar();
bar.foo = "string";
bar.foo = 123; // no error occurred
```

**Comment by billccn** [comment]
The questions is how far should the compiler go and what should a developer's expectation be when reading the initial variable declaration? (E.g. there's always the halting problem.)

(You second code snippet feels like a design loophole to me. You should have been warned about initializing the instance without the type variable.)

**Comment by RyanCavanaugh** [comment]
As mentioned, it's really a problem of where you stop. `arr` could just as arguably be `Array<string|number>`. Sometimes it's better to have no opinion than a bad one.
