### ISSUE TITLE
Can't check in conditional type if a generic type is assignable to another generic type with a hierarchy between them

### ISSUE THREAD

**Issue by bengry** [microsoft/TypeScript#26495]
**TypeScript Version:**  3.1.0-dev.20180813

**Search Terms:**
- Conditional types
- generic conditional types
- conditional types extends
- conditional types inheritance

**Code**

```ts
interface Wrapper<T> {
    data: T;
}

function getWrapper<TParent, TChild extends TParent>(parent: TParent, child?: TChild): TParent extends TChild ? Wrapper<TChild> : Wrapper<TParent> {
    if (child) {
        return {
            data: child
        } as Wrapper<TChild>; // [ts] Type 'Wrapper<TChild>' is not assignable to type 'TParent extends TChild ? Wrapper<TChild> : Wrapper<TParent>'.
    }

    return {
        data: parent
    } as Wrapper<TParent>; // [ts] Type 'Wrapper<TParent>' is not assignable to type 'TParent extends TChild ? Wrapper<TChild> : Wrapper<TParent>'.
}

interface Person {
    name: string;
}

interface EmployeePerson extends Person {
    department: string;
}

const p: Person = {
    name: 'john'
};

const e: EmployeePerson = {
    name: 'john',
    department: 'sales'
};

const personWrapper = getWrapper(p);
const employeeWrapper = getWrapper(p, e).data.department // return type inferred to `Person` - [ts] Property 'department' does not exist on type 'Person'.
```

**Expected behavior:**
1. Both types `Wrapper<TChild>` and `Wrapper<TParent>` should be assignable to `TParent extends TChild ? Wrapper<TChild> : Wrapper<TParent>`.
2. When passing a `Person` as the first argument and an `EmployeePerson` as the second argument, get a `Wrapper<EmployeePerson>` back.

**Actual behavior:**
1. They are not assignable:
  1.1. `Type 'Wrapper<TParent>' is not assignable to type 'TParent extends TChild ? Wrapper<TChild> : Wrapper<TParent>'.`
  1.2. `Type 'Wrapper<TParent>' is not assignable to type 'TParent extends TChild ? Wrapper<TChild> : Wrapper<TParent>'.`
2. Get an `EmployeePerson` back when passing a second argument.

**Playground Link:** [https://www.typescriptlang.org/play/index.html#src=interface%20Wrapper%3CT%3E%20%7B%0D%0A%20%20%20%20data%3A%20T%3B%0D%0A%7D%0D%0A%0D%0Afunction%20getWrapper%3CTParent%2C%20TChild%20extends%20TParent%3E(parent%3A%20TParent%2C%20child%3F%3A%20TChild)%3A%20TParent%20extends%20TChild%20%3F%20Wrapper%3CTChild%3E%20%3A%20Wrapper%3CTParent%3E%20%7B%0D%0A%20%20%20%20if%20(child)%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20data%3A%20child%0D%0A%20%20%20%20%20%20%20%20%7D%20as%20Wrapper%3CTChild%3E%3B%20%2F%2F%20%5Bts%5D%20Type%20'Wrapper%3CTChild%3E'%20is%20not%20assignable%20to%20type%20'TParent%20extends%20TChild%20%3F%20Wrapper%3CTChild%3E%20%3A%20Wrapper%3CTParent%3E'.%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20return%20%7B%0D%0A%20%20%20%20%20%20%20%20data%3A%20parent%0D%0A%20%20%20%20%7D%20as%20Wrapper%3CTParent%3E%3B%20%2F%2F%20%5Bts%5D%20Type%20'Wrapper%3CTParent%3E'%20is%20not%20assignable%20to%20type%20'TParent%20extends%20TChild%20%3F%20Wrapper%3CTChild%3E%20%3A%20Wrapper%3CTParent%3E'.%0D%0A%7D%0D%0A%0D%0Ainterface%20Person%20%7B%0D%0A%20%20%20%20name%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20EmployeePerson%20extends%20Person%20%7B%0D%0A%20%20%20%20department%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Aconst%20p%3A%20Person%20%3D%20%7B%0D%0A%20%20%20%20name%3A%20'john'%0D%0A%7D%3B%0D%0A%0D%0Aconst%20e%3A%20EmployeePerson%20%3D%20%7B%0D%0A%20%20%20%20name%3A%20'john'%2C%0D%0A%20%20%20%20department%3A%20'sales'%0D%0A%7D%3B%0D%0A%0D%0Aconst%20personWrapper%20%3D%20getWrapper(p)%3B%0D%0Aconst%20employeeWrapper%20%3D%20getWrapper(p%2C%20e).data.department%20%2F%2F%20return%20type%20inferred%20to%20%60Person%60%20-%20%5Bts%5D%20Property%20'department'%20does%20not%20exist%20on%20type%20'Person'.%0D%0A](https://www.typescriptlang.org/play/index.html#src=interface%20Wrapper%3CT%3E%20%7B%0D%0A%20%20%20%20data%3A%20T%3B%0D%0A%7D%0D%0A%0D%0Afunction%20getWrapper%3CTParent%2C%20TChild%20extends%20TParent%3E(parent%3A%20TParent%2C%20child%3F%3A%20TChild)%3A%20TParent%20extends%20TChild%20%3F%20Wrapper%3CTChild%3E%20%3A%20Wrapper%3CTParent%3E%20%7B%0D%0A%20%20%20%20if%20(child)%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20data%3A%20child%0D%0A%20%20%20%20%20%20%20%20%7D%20as%20Wrapper%3CTChild%3E%3B%20%2F%2F%20%5Bts%5D%20Type%20'Wrapper%3CTChild%3E'%20is%20not%20assignable%20to%20type%20'TParent%20extends%20TChild%20%3F%20Wrapper%3CTChild%3E%20%3A%20Wrapper%3CTParent%3E'.%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20return%20%7B%0D%0A%20%20%20%20%20%20%20%20data%3A%20parent%0D%0A%20%20%20%20%7D%20as%20Wrapper%3CTParent%3E%3B%20%2F%2F%20%5Bts%5D%20Type%20'Wrapper%3CTParent%3E'%20is%20not%20assignable%20to%20type%20'TParent%20extends%20TChild%20%3F%20Wrapper%3CTChild%3E%20%3A%20Wrapper%3CTParent%3E'.%0D%0A%7D%0D%0A%0D%0Ainterface%20Person%20%7B%0D%0A%20%20%20%20name%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20EmployeePerson%20extends%20Person%20%7B%0D%0A%20%20%20%20department%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Aconst%20p%3A%20Person%20%3D%20%7B%0D%0A%20%20%20%20name%3A%20'john'%0D%0A%7D%3B%0D%0A%0D%0Aconst%20e%3A%20EmployeePerson%20%3D%20%7B%0D%0A%20%20%20%20name%3A%20'john'%2C%0D%0A%20%20%20%20department%3A%20'sales'%0D%0A%7D%3B%0D%0A%0D%0Aconst%20personWrapper%20%3D%20getWrapper(p)%3B%0D%0Aconst%20employeeWrapper%20%3D%20getWrapper(p%2C%20e).data.department%20%2F%2F%20return%20type%20inferred%20to%20%60Person%60%20-%20%5Bts%5D%20Property%20'department'%20does%20not%20exist%20on%20type%20'Person'.%0D%0A)

**Related Issues:** 
No

**Comment by RyanCavanaugh** [comment]
Re (1), a type is only assignable to a conditional type if it's assignable to both of its possible outputs. TS can't yet verify *whether* `TParent extends TChild` in a particular location in the function, so you need to use a type assertion because the conversion is not sound by default.

Re (2), this is what you wrote -- `Person extends EmployeePerson` (the instantiation in question) is `false`. Swap the clauses if you meant the opposite.

**Comment by bengry** [comment]
@RyanCavanaugh 
Re (1) That's why I added the typecasting in both `return` statements, what type assertion can I use (and where) to make this work?
Re (2) Right - what I'm trying to check is essentially if `TParent` === `TChild`. `TChild extends TParent` by the generic constraint in the function. In the return type to check if one type is equal to another I do the opposite: `TParent extends TChild`, which is only true if `TParent` == `TChild` (given the aforementioned constraint). Am I missing something?
