### ISSUE TITLE
Generic parameters constrained to unions of tuples are not inferred correctly in rest parameter positions

### ISSUE THREAD

**Issue by jcalz** [Microsoft/TypeScript#26491]
**TypeScript Version:**  3.1.0-dev.20180813

**Search Terms:** 
Tuple rest generic union

**Code**
```ts
declare function hmm<A extends [] | [number, string]>(...args: A): void;
hmm(); // okay, A = []
hmm(1, "s"); // okay, A = [1, "s"]
hmm("what"); // no error?  A = [] | [number, string] ?
```

**Expected behavior:**
Error on `hmm("what")`.  `A` should be inferred as `[string]`, which does not extend `[] | [number, string]`.

**Actual behavior:**
No error on `hmm("what")`.  Apparently `A` is inferred as the constraint type `[] | [number, string]` despite that not matching the actual argument type.

**Playground Link:** 
[Link](https://www.typescriptlang.org/play//#src=declare%20function%20hmm%3CA%20extends%20%5B%5D%20%7C%20%5Bnumber%2C%20string%5D%3E%28...args%3A%20A%29%3A%20void%3B%0A%0Ahmm%28%29%3B%20%2F%2F%20okay%2C%20A%20%3D%20%5B%5D%0Ahmm%281%2C%20%22s%22%29%3B%20%2F%2F%20okay%2C%20A%20%3D%20%5B1%2C%20%22s%22%5D%0Ahmm%28%22what%22%29%3B%20%2F%2F%20no%20error%3F%20%20A%20%3D%20%5B%5D%20%7C%20%5Bnumber%2C%20string%5D%20%3F)

**Related Issues:**
#24897: introduction of tuples into rest/spread expressions
#26110: similar issue with bad or weird inference behavior on rest arguments

**Comment by RyanCavanaugh** [comment]
@ahejlsberg I'm probably missing something here but this seems bad
