### ISSUE TITLE
Default function parameters fail with generics

### ISSUE THREAD

**Issue by adam-stanek** [Microsoft/TypeScript#26492]
Providing default values for function parameters with generic type doesn't seem to honor generic constraints.

**TypeScript Version:**
- 3.0.1
- 3.1.0-dev.20180813

**Search Terms:**
default parameter generic 

**Code**

```ts
function test<T extends string>(str: T = 'some default'): void {}
```

**Expected behavior:**

Code passes. `'some default'` should be a valid value for `T` because it extends `string`.

**Actual behavior:**

Type check fails with TS2322:`Type '"some default"' is not assignable to type 'T'.`

**Playground Link:** https://www.typescriptlang.org/play/#src=function%20test%3CT%20extends%20string%3E(str%3A%20T%20%3D%20'some%20default')%3A%20void%20%7B%7D%0D%0A

**Comment by MartinJohns** [comment]
The type `'foo'` extends `string` too, but it's not compatible with `'some default'`.

**Comment by RyanCavanaugh** [comment]
Specifically the call `test<"foo">()` causes the function to be ill-typed.

**Comment by adam-stanek** [comment]
You are right. Thanks for clarification.

**Comment by trusktr** [comment]
I don't see why TypeScript couldn't just throw an error in the case of `test<"foo">()`. It is totally obvious that `'some default' is not assignable to 'foo'`, and that could totally be a type error. It could check the default arg just like with any user-supplied arg.

I know, this needs updates to how declaration files are outputted. It needs to support default args.
