### ISSUE TITLE
no implicit any when indexing never

### ISSUE THREAD

**Issue by sandersn** [Microsoft/TypeScript#26493]
```ts
// @noImplicitAny: true
function f(l: never, x: any) {
  var x = l[0] // should be implicit any error here, but 'non-matching redeclaration type' instead
  x.length  // and no error here, but 'length' not found on 'never' instead
}
```

**Expected behavior:**
With noImplicitAny on, you should get a noImplicitAny error and `x: any`. With it off, you should just get `x: any`.

**Actual behavior:**
`x: never` and you get an error on the next line that 'length' does not exist on type 'never'.

On master, but not 3.1 as of 2018/07/17

**Comment by ahejlsberg** [comment]
This is an intended effect of #26340. We definitely want `T[K]` to be `never` when `T` is `never`.
