### ISSUE TITLE
<reference lib="..." /> directives aren't included in output declaration files

### ISSUE THREAD

**Issue by RikkiGibson** [Microsoft/TypeScript#26497]
**TypeScript Version:**  3.1.0-dev.20180813

**Search Terms:**
reference lib directive type declarations

**Code**

```ts
/// <reference lib="dom" />

interface ElementHolder {
  elem: HTMLElement;
}
```

**Expected behavior:**
When running `tsc test.ts --declaration`, a declaration file equivalent to the below is emitted.
```ts
/// <reference lib="dom" />

interface ElementHolder {
  elem: HTMLElement;
}
```

**Actual behavior:**
The following declaration is emitted.

```ts
interface ElementHolder {
  elem: HTMLElement;
}
```
**Playground Link:** 
N/A because Playground does not emit .d.ts files

**Related Issues:** 
Did not find any similar looking bugs

**Comment by RyanCavanaugh** [comment]
@weswigham can you elaborate on the lib directive emit rules?

**Comment by weswigham** [comment]
I'd ask @rbuckton actually - I'm not aware of what the lub reference declaration emit rules are, if we even have any.

**Comment by rbuckton** [comment]
We probably should be emitting these to the declaration file as well.

**Comment by RikkiGibson** [comment]
Thank you!
