### ISSUE TITLE
Suggestion: static constructors

### ISSUE THREAD

**Issue by omidkrad** [microsoft/TypeScript#265]
A **static constructor** is a function that is run only once when the class is loaded. It can be used to initialize static class members and maybe as entry point to the application.

Suggested syntax is:

``` typescript
class MyClass {
    static initialized = false;

    static constructor() {
        MyClass.initialized = true;
    }
}

alert(MyClass.initialized);
```

That would be same as the following:

``` typescript
class MyClass {
    static initialized = false;

    static __ctor = (() => {
        MyClass.initialized = true;
    })();
}

alert(MyClass.initialized);
```

Except that `__ctor` does not need to be assigned to the class in the output code, and only needs to be invoked in an anonymous function. Also compiler can check that no more than one static constructor is defined in a class.

**Update:** Since this generates an Immediately-Invoked Function Expression (IIFE), compiler should make sure to move it to the end of the class definition in the output JavaScript.

TypeScript:

``` typescript
class MyClass {
    static constructor() {
        MyClass.initialized = true;
    }

    static initialized = false;
}
```

Expected JavaScript output:

``` javascript
var MyClass = (function () {
    function MyClass() {
    }
    MyClass.initialized = false;

    // run last
    (function () {
        MyClass.initialized = true;
    })();
    return MyClass;
})();
```

Note that body of the static constructor is moved to the bottom and invoked.

> Related suggestion in codeplex: [Please add static constructors to classes](https://typescript.codeplex.com/workitem/862)

**Comment by JoshMcCullough** [comment]
:+1: Please do! However, a potential workaround would be:

    class MyClass {
        private static isInitialized: boolean = false;
    
        public static init() {
            if (!MyClass.isInitialized) {
                // Initialize things...
            }
            
            MyClass.isInitialized = true;
        }
    }
    
    MyClass.init();

**Comment by nin-jin** [comment]
Developers, please, read about D language, where most problems with OOP are solved. For inspiration.

Why i can not use "this" in "static" context? IMHO, "this" must point to current class (not to superclass).

**Comment by danquirk** [comment]
@nin-jin You can use ```this``` in ```static``` member functions and accessors, just not member initializers. 

Note that in any comparison to other languages you need to consider the somewhat unique constraints TypeScript operates with (as a superset of JavaScript and emitting clean, idiomatic JavaScript with minimal or no strange rewriting). Were we designing in a green field with only our own thoughts the language would look very different :)

**Comment by felixfbecker** [comment]
But what about inheritance?
```ts
class A {
  private options: {hello: number}
  static constructor() {
    console.log('called')
    this.options = {hello: 123}
  }
}

class B extends A {
}
```
I would expect _called_ to be logged twice.

**Comment by PascalSenn** [comment]
@felixfbecker  Every static property is bind to the class. It cannot be inherited. So the static constructor should also follow this pattern to ensure a equal behavior.

**Comment by felixfbecker** [comment]
@PascalSenn static properties _are_ inherited in ES6 and TypeScript.

**Comment by PascalSenn** [comment]
@felixfbecker Thats new for me. Didnt know that. C# doesnt support it, so i thought Typescript neither.

**Comment by felixfbecker** [comment]
@PascalSenn you can even do it in ES5:
```js
function SuperClass {}
SuperClass.staticProperty = 123;
function SubClass {}
Object.setPrototypeOf(SubClass, SuperClass);
```

**Comment by mark-norgate** [comment]
@RyanCavanaugh I don't think the merged module solution is anywhere near an approximation to static constructor. It is still required that you call the static member whether you use merged modules or not. A static constructor would initialise automatically.

**Comment by rjamesnw** [comment]
It's too bad generic type references were dropped in static functions.  I was using some static constructor style methods on some classes (similar to JoshMcCullough's post above) and now it's all broken.  The only workaround was to convert the private static constructor methods to private instance methods and call them instead via the prototype from another static constructor method. I didn't want to duplicate my class generic signature on my static method as well, that's just getting too silly.

**Comment by Alphapage** [comment]
Hello,

I hope Typescript will implement static constructors like this:
https://github.com/sirisian/ecmascript-static-constructor/issues/1

It would solve "function properties" typing problem too: https://stackoverflow.com/questions/12766528/build-a-function-object-with-properties-in-typescript

**Comment by rjamesnw** [comment]
TypeScript supports many coming ES6+ changes today, best it can, and targeting such code will output code like this `class MyClass { }` - which works in non-IE browsers. ;) However, what you are suggesting, to support 'MyClass()' is an error, since currently, ES6 introduces a new non-invokable function type (for classes).  The minute someone targets ES6+, their code would fail. ;)

**Comment by gmurray81** [comment]
I'm not sure of the exact mechanics of some of the tree shakers out there, but won't some of these strategies disrupt the tree shakers? Calling a static method on the Type as a separate action outside of the class's IIFE (in ES5) may be seen as a reference to the type? Or containing some side effect that may not be possible to omit? Presumably being able to wrap some code inside of the class's ES5 iffe would been seen as more atomic with the definition of the type?

**Comment by nin-jin** [comment]
@gmurray81 tree shaking is partial workaround of autoloaders absence. Better to use bundler that supports autoloading. [MAM](https://github.com/eigenmethod/mam) in example.

**Comment by gmurray81** [comment]
@nin-jin even if you could just persuade everyone to use different technology in their projects to avoid a problem (some of us need to write library code for others to consume) there would still be an argument that it should be easy to make the creation/calling of the static cons atomic with the class creation.

It seems like shoving an IIFE on the last defined static property of a type, as suggested above, might be the closest you can come with the syntax as it stands. It's a little ugly, though, comparatively.
