### ISSUE TITLE
TSServer incorrectly works on linux

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#26508]
Can you try to repro this issue on linux?

**TypeScript Version:**  3.1.0-dev.20180810

**Search Terms:**

**Code**

1. Clone and install https://github.com/falsandtru/securemark.
1. Open that project folder on VSCode.
1. Open markdown.d.ts file.
1. On win10, no error. On linux (ubuntu), some type errors.

Note that the compiler supports empty tuples and tsserver certainly uses that compiler as follows:

```
[Info  - 19:28:02] Using tsserver from: /home/xxx/development/securemark/node_modules/typescript/lib
``` 

Additionally, CI tests on travis has not failed. So the problems happen only on tsserver, won't happen in compiling.

**Expected behavior:**

No error.

**Actual behavior:**

Error only on windows. Oddly, this error doesn't seem to happen with https://github.com/falsandtru/spica.

```
A tuple type element list cannot be empty.
```

**Playground Link:** 

**Related Issues:**

**Comment by sheetalkamat** [comment]
@andy-ms can you try and see if this repros on Linux.

**Comment by andy-ms** [comment]
Don't see the type errors on linux using `typescript@next`. *Did* see errors using `typescript@2.9`.
@falsandtru This probably has to do with the installed TypeScript version -- check `/home/xxx/development/securemark/node_modules/typescript/package.json` for the "version" field to see if it's up-to-date.

**Comment by falsandtru** [comment]
Sorry, I did run `npm i` to update dependencies but it didn't work because ubuntu's npm version is too old.
