### ISSUE TITLE
navigator.mimeTypes type definition problem in lib.es2016.full.d.ts

### ISSUE THREAD

**Issue by doggy8088** [microsoft/TypeScript#26502]
**TypeScript Version:**  3.1.0-dev.20180813

**Search Terms:** navigator.mimeTypes

**Code**

```ts
http://www.typescriptlang.org/play/index.html#src=var%20a%3A%20Plugin%20%3D%20navigator.mimeTypes%5B0%5D%0D%0Avar%20b%3A%20MimeType%20%3D%20a%5B0%5D%3B%0D%0A%0D%0Aconsole.log(b.type)
```

**Expected behavior:**

I expected `MimeTypeArray` object which contains a list of MimeType objects representing the MIME types recognized by the browser.   This one is right in TypeScript.

Reference: [NavigatorPlugins.mimeTypes - Web APIs | MDN](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorPlugins/mimeTypes)

When I get an array item in the `navigator.mimeTypes`, such as `navigator.mimeTypes[0]`.  TypeScript should reference to `MimeType`, but it reference to a `Plugin` type and then `Plugin`'s reference is also different from MDN docs.

![image](https://user-images.githubusercontent.com/88981/44250618-990d2580-a227-11e8-903c-560c29aa86ad.png)

**Actual behavior:**

![image](https://user-images.githubusercontent.com/88981/44250381-a83fa380-a226-11e8-9564-4734217970a7.png)

![image](https://user-images.githubusercontent.com/88981/44250390-b261a200-a226-11e8-968f-19516aef8a57.png)

![image](https://user-images.githubusercontent.com/88981/44250400-bf7e9100-a226-11e8-882f-3a6cc35ec076.png)

**Playground Link:** 
http://www.typescriptlang.org/play/index.html#src=var%20a%20%3D%20navigator.mimeTypes%5B0%5D%3B%0D%0Avar%20b%20%3D%20a%5B0%5D%3B%0D%0A%0D%0Aconsole.log(b.type)%3B%0D%0A%0D%0A%0D%0A

**Related Issues:** 
N/A

**Comment by jakebailey** [comment]
Just looking at ancient issues; this was fixed in #32335.
