### ISSUE TITLE
ignore scope for type searching

### ISSUE THREAD

**Issue by farfromrefug** [microsoft/TypeScript#26506]
I am starting to have a lot of "forks" for existing packages that I need to maintain either in public npm fork  scope like ```@farfromrefug/noble```  or in custom registry (verdaccio) like ```@mycompany/noble```

The issue is when those packages don't come with typings and you need ```@typings```. Using scope make it so that TS does not now that you need ```@types/noble``` for ```@farfromrefug/noble```

So it would very useful to have tsconfig option to "ignore" some scopes for typings resolution.
I get that you would not want that for scopes like ```@angular``` but for some custom scopes that would be very useful.

**Comment by andy-ms** [comment]
You could set up a [path mapping](https://www.typescriptlang.org/docs/handbook/module-resolution.html) for this purpose, e.g. to import from "@my/cors" instead of "@koa/cors":
```json
"baseUrl": ".",
"paths": {
    "@my/cors": ["node_modules/@types/koa__cors/index.d.ts"],
},
```

**Comment by farfromrefug** [comment]
@andy-ms that does not look really good :s plus it s kind of a pain to maintain...

**Comment by farfromrefug** [comment]
@andy-ms this became even more important for us as we started to use private registry even more.
Right now if want to maintain a private fork of ```noble``` for example I create the package as ```noble``` in our private repo. We do that because we want ```@types/noble``` to work.
Now to have this to work we need to change npm default registry to our own, or our noble won't be seen.
But doing this is quite heavy for a private registry (running on a private local server). Big projects with a lot of npm deps seem to ask a lot from a registry.

The best solution would be use our registry only for a scope in .npmrc.
But that would mean that we would use ```@mycomp/noble``` and not ```noble```. But then no typings.

I really hope this feature could make it into typescript.  This would also help a lot for people using public fork packages.
