### ISSUE TITLE
Object literal not recognized as namespace

### ISSUE THREAD

**Issue by texastoland** [Microsoft/TypeScript#26505]
**TypeScript Version:**  3.1.0xxxxx

**Search Terms:**

`namespace empty object literal` and `https://github.com/Microsoft/TypeScript/tree/master/tests/cases`

**Code**

```ts
var ns = {};     // recognized as a declaration for a namespace `ns`
ns.constant = 1; // recognized as a declaration for var `constant`
// ^^^^^^^^ <- Property 'constant' does not exist on type '{}'.
```

**Expected behavior:**

> TypeScript 2.8 adds support for understanding more namespace patterns in `.js` files. Empty object literals declarations on top level, just like functions and classes, are now recognized as as namespace declarations in JavaScript.

[Release notes (source)](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html#better-handling-for-namespace-patterns-in-js-files)

**Actual behavior:**

Compile error.

**Playground Link:** 

[Playground](https://www.typescriptlang.org/play/index.html#src=var%20ns%20%3D%20%7B%7D%3B%20%20%20%20%20%2F%2F%20recognized%20as%20a%20declaration%20for%20a%20namespace%20%60ns%60%0D%0Ans.constant%20%3D%201%3B%20%2F%2F%20recognized%20as%20a%20declaration%20for%20var%20%60constant%60%0D%0A)

**Related Issues:** 

I'm migrating a codebase and tried a few minor variations unsuccessfully.

**Comment by texastoland** [comment]
> patterns in `.js` files

Ugh just realized I converted my file to `.ts`. Is this specific to working with the pragma?

**Comment by AlCalzone** [comment]
Yes, this is specific to JavaScript. In TypeScript you should declare the intended type of your variables beforehand. One exception will come for function types:
https://github.com/Microsoft/TypeScript/pull/26368
