### ISSUE TITLE
Can we stop Google from sabotaging ts?

### ISSUE THREAD

**Issue by lonewarrior556** [Microsoft/TypeScript#26507]
![image](https://user-images.githubusercontent.com/4774405/44258652-cd74e780-a20f-11e8-85bd-a52f77953e59.png)

**Comment by RyanCavanaugh** [comment]
I believe what everyone needs to do is make links like [TS Playground](http://www.typescriptlang.org/play/) to increase our page rank for this search term?

Go forth, followers, and spread the news!

**Comment by asborisov** [comment]
@lonewarrior556 It should be OK if you type `typescript playground`

**Comment by DanielRosenwasser** [comment]
Linking this to #13055 just to find this more easily.

Also, tags: playground search page rank pagerank meta tags metatags seo nsfw
