### ISSUE TITLE
API: expose getTypeOfArrayLiteralOrObjectLiteralDestructuringAssignment

### ISSUE THREAD

**Issue by ajafff** [microsoft/TypeScript#26509]
I'd like to be able to inspect the type of a destructuring assignment. Currently there is only `getPropertySymbolOfDestructuringAssignment` which only works with identifiers and only gets the symbol of one property. I need the whole destructured type.

A custom implementation would need to duplicate a lot code to correctly handle iteration protocol.

**Comment by RyanCavanaugh** [comment]
@rbuckton @ahejlsberg any objections?

**Comment by rbuckton** [comment]
Perhaps we should expose it with a name that is less of a mouthful? Something like `getTypeOfDestructuringAssignment` or `getTypeOfAssignmentPattern`.
