### ISSUE TITLE
API: how to get Symbol of anonymous class?

### ISSUE THREAD

**Issue by ajafff** [Microsoft/TypeScript#26511]
**TypeScript Version:**  3.1.0-dev.20180813

**Search Terms:**

**Code**

```ts
declare let node: ts.ClassExpression; // (class {})
checker.getSymbolAtLocation(node); // undefined;
```

**Expected behavior:**
`getSymbolAtLocation` returns the symbol of the class.

**Actual behavior:**
For named ClassLikeDeclarations I can use `getSymbolAtLocation(node.name)` but that will obviously not work if there is no name.

My current workaround is `ts.getTypeAtLocation(node).symbol!`.

Why doesn't `getSymbolAtLocation` simply return `node.symbol` if none of the conditions match?

In addition there is some special handling of `FunctionKeyword` to get the symbol of anonymous functions. Could something similar be implemented for `ClassKeyword`?

**Comment by sandersn** [comment]
@ajafff I added special handling of `ClassKeyword` in #26636. I'm not sure that's what you are asking for, however. It's fine for language service use, since users can't directly specify a ClassExpression, only a ClassKeyword. I don't know if it suffices for your needs, however.
