### ISSUE TITLE
Wrong type casting on function parameters

### ISSUE THREAD

**Issue by voliva** [Microsoft/TypeScript#26514]
**TypeScript Version:**  3.1.0

**Search Terms:** type function parameters

**Code**

```ts
interface Base {
    base: string;
}
interface Foo extends Base {
    foo: string;
}
interface Bar extends Base {
    bar: string;
}

const myFoo: Foo = {
    base: 'base',
    foo: 'foo'
}
const myBar: Bar = {
    base: 'base',
    bar: 'bar'
}
const myBase: Base = myBar;

const fooFn: (foo: Foo) => number = (foo: Foo) => foo.foo.length;
const myBaseFn: (base: Base) => number = fooFn;

fooFn(myFoo); // OK
fooFn(myBase); // Err, Thar's right => 'foo' is missing in Base
myBaseFn(myBase); // OK, But that's wrong! => Will cause an exception on runtime

// It shouldn't let me assign fooFn to type (base: Base) => string in the first place, because 'Base' is not assignable to 'Foo', like in this example

const myBaseFoo: Foo = myBase; // Err, That's right => Base is not asignable to Foo
```

**Expected behavior:**
It shouldn't let assigning the function `fooFn: (foo: Foo) => number` to the type `(base: Base) => number`, because `Base` is not assignable to `Foo`.

**Actual behavior:**
It does

**Playground Link:** 
https://www.typescriptlang.org/play/#src=interface%20Base%20%7B%0D%0A%20%20%20%20base%3A%20string%3B%0D%0A%7D%0D%0Ainterface%20Foo%20extends%20Base%20%7B%0D%0A%20%20%20%20foo%3A%20string%3B%0D%0A%7D%0D%0Ainterface%20Bar%20extends%20Base%20%7B%0D%0A%20%20%20%20bar%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Aconst%20myFoo%3A%20Foo%20%3D%20%7B%0D%0A%20%20%20%20base%3A%20'base'%2C%0D%0A%20%20%20%20foo%3A%20'foo'%0D%0A%7D%0D%0Aconst%20myBar%3A%20Bar%20%3D%20%7B%0D%0A%20%20%20%20base%3A%20'base'%2C%0D%0A%20%20%20%20bar%3A%20'bar'%0D%0A%7D%0D%0Aconst%20myBase%3A%20Base%20%3D%20myBar%3B%0D%0A%0D%0Aconst%20fooFn%3A%20(foo%3A%20Foo)%20%3D%3E%20number%20%3D%20(foo%3A%20Foo)%20%3D%3E%20foo.foo.length%3B%0D%0Aconst%20myBaseFn%3A%20(base%3A%20Base)%20%3D%3E%20number%20%3D%20fooFn%3B%0D%0A%0D%0AfooFn(myFoo)%3B%20%2F%2F%20OK%0D%0AfooFn(myBase)%3B%20%2F%2F%20Err%2C%20Thar's%20right%20%3D%3E%20'foo'%20is%20missing%20in%20Base%0D%0AmyBaseFn(myBase)%3B%20%2F%2F%20OK%2C%20But%20that's%20wrong!%20%3D%3E%20Will%20cause%20an%20exception%20on%20runtime%0D%0A%0D%0A%2F%2F%20It%20shouldn't%20let%20me%20assign%20fooFn%20to%20type%20(base%3A%20Base)%20%3D%3E%20string%20in%20the%20first%20place%2C%20because%20'Base'%20is%20not%20assignable%20to%20'Foo'%2C%20like%20in%20this%20example%0D%0A%0D%0Aconst%20myBaseFoo%3A%20Foo%20%3D%20myBase%3B%20%2F%2F%20Err%2C%20That's%20right%20%3D%3E%20Base%20is%20not%20asignable%20to%20Foo

**Comment by RyanCavanaugh** [comment]
Turn on `strictFunctionTypes` and/or read the FAQ entry on parameter bivariance

**Comment by voliva** [comment]
Thank you very much, that's exactly it. Sorry about that!
