### ISSUE TITLE
tsc --build --watch does not watch wild card directories correctly

### ISSUE THREAD

**Issue by sheetalkamat** [Microsoft/TypeScript#26524]
`updateWatchingWildcardDirectories` is normally used for single project and it mutates map to have new watch directories, Since we have single `existingWatchersForWildcards` among all projects this is incorrect and not watching wild card directories correctly.
https://github.com/Microsoft/TypeScript/blob/master/src/compiler/tsbuild.ts#L569

**Comment by RyanCavanaugh** [comment]
@sheetalkamat feel free to bring this into 3.1 milestone if you have time
