### ISSUE TITLE
Compile error since 3.1.0-dev.20180817

### ISSUE THREAD

**Issue by Flarna** [microsoft/TypeScript#26521]
**TypeScript Version:**  3.1.0-dev.20180817

**Search Terms:**
3.1.0-dev.20180817
20180817

**Code**

```ts
interface Foo {
  (a: string, b: string): string
}

interface FooI {
  [name: string]: number;
}

interface Bar extends Foo {
  p?: FooI;
}

const x: Bar = (a, b) => { return a + b }
x.p = {}
```

**Expected behavior:**
No compile error like in typescript 3.0.1 or 3.1.0-dev.20180813

**Actual behavior:**
Compile error:
```
test.ts:13:7 - error TS2322: Type '{ (a: string, b: string): string; p: {}; }' is not assignable to type 'Bar'.
  Types of property 'p' are incompatible.
    Type '{}' is not assignable to type 'FooI'.
      Index signature is missing in type '{}'.

13 const x: Bar = (a, b) => { return a + b }
```
**Playground Link:** 

**Related Issues:** 
CI error at DT: e.g. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/28204

**Comment by sandersn** [comment]
Looks like `x.p` is being treated as one of the new expando properties and not getting the contextual type from `Bar.p`.
