### ISSUE TITLE
Propagate Never Types to Parents

### ISSUE THREAD

**Issue by jeremyBanks** [Microsoft/TypeScript#26537]
## Search Terms

[never type inference](https://github.com/Microsoft/TypeScript/issues?utf8=%E2%9C%93&q=is%3Aissue+never+type+inference), [never parent](https://github.com/Microsoft/TypeScript/issues?utf8=%E2%9C%93&q=is%3Aissue+never+parent), [never property](https://github.com/Microsoft/TypeScript/issues?utf8=%E2%9C%93&q=is%3Aissue+never+property), [never narrowing](https://github.com/Microsoft/TypeScript/issues?utf8=%E2%9C%93&q=is%3Aissue+never+narrowing+)

## Suggestion

TypeScript's type system helpfully eliminates `never` patterns from unions. This could be even more helpful if it were able to infer that types containing `never` types can not exist at runtime, and must themselves also be `never`. 

Any types which contain a not-null, not-undefined, not-unioned value of the `never` type would themselves be reduced to a `never` type, since they can also never exist.

This applies when `never` is used as a property value, array type, or tuple value...

- `{x: never, y: number}` becomes `never`
- `never[]` becomes `never`
- `(never, 1)` becomes `never`

but not when `never` is used as a return value, or part of a union...

- `() => never` is unchanged 
- `(never) => void` is unchanged
- `never|String` already becomes `String`

Would this be a reasonable transformation to perform?

This is inspired by [part of this never type handling proposal for Rust](http://smallcultfollowing.com/babysteps/blog/2018/08/13/never-patterns-exhaustive-matching-and-uninhabited-types-oh-my/#implications-for-safe-code).

## Example

Consider using a generic `Result<T, U>` type, which contains a value of type `T` in case of success or one of type `U` in case of failure. If we need to return a `Result`, but know that no error can occur for our implementation, we might use the type `Result<String, never>`.

If we use an untagged union, TypeScript recognizes that the error case can never occur and knows we can safely treat it as the success type.

```typescript
type Result<T, U> = T | U;

const s1 = "hello" as Result<String, Error>;
s1.slice();
// Property 'slice' does not exist on type 'Result<String, Error>'.
//   Property 'slice' does not exist on type 'Error'.

const s2 = "hello" as Result<String, never>;
s2.slice();
// "hello"
```

However, if we used a tagged union instead, TypeScript can't eliminate the failure type:

```typescript
type Result<T, U> = {ok: T} | {err: U};

const s1 = {ok: "hello"} as Result<String, Error>;
s1.ok.slice();
// Property 'ok' does not exist on type 'Result<String, Error>'.  
//   Property 'ok' does not exist on type '{ err: Error; }'.

const s2 = {ok: "hello"} as Result<String, never>;
s2.ok.slice();
// Property 'ok' does not exist on type 'Result<String, never>'.  
//   Property 'ok' does not exist on type '{ err: never; }'.
```

If the `never` type were propagated up in  `{ err: never }`, the compiler could eliminate it from the union and recognize that this code was safe.

## Compatibility

Code that operates on structures containing never values could start raising new errors. For example, the following currently [compiles without error](https://www.typescriptlang.org/play/index.html#src=declare%20const%20never%3A%20never%3B%0D%0A%0D%0Aconst%20p%20%3D%20%7Bx%3A%20never%2C%20y%3A%200%7D%0D%0Aconst%20q%20%3D%20p.y%3B%0D%0Aconsole.log(p)%3B%0D%0A), but after this change it would raise an error:

```rust
declare const never: never;
const p = {x: never, y: 0}
const q = p.y;
// Property 'y' does not exist on type '{x: never, y: 0}'.
//   Property 'y' does not exist on type 'never'.
```

Such code is necessarily already dead, so this case shouldn't be very common.

The change wouldn't introduce errors in generic code that just might be populated with `never`, like the motivating example above.

## Checklist

My suggestion meets these guidelines:
* [ ] This wouldn't be a breaking change in existing TypeScript / JavaScript code
  - This **is** a breaking change for some existing TypeScript code, but it might only affect dead code.
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by ahejlsberg** [comment]
We've considered this before and in principle you're right, types containing `never` constituents could themselves be considered `never`. However, in order to realize that a type has `never` constituents we would need to _eagerly_ enumerate all constituents (and, recursively, _their_ constituents), but that isn't possible for types that are infinite and generally runs counter to lazy evaluation (the deep enabler of the structural type system).

Have you considered using a conditional type to express the missing error case?

```ts
type Result<T, U> = { ok: T } | (U extends never ? never : { err: U });
```

I think this gives you what you're looking for.

**Comment by jeremyBanks** [comment]
Thanks for the explanation and suggestion. Conditional types should be more than sufficient.

**Comment by RyanCavanaugh** [comment]
We also had concerns about "debuggability" if we eagerly collapsed `never`-containing types, since it'd be impossible to figure out *which* property had caused the `never` to appear.
