### ISSUE TITLE
API - DocumentRegistry - sourceFile.scriptTarget can possibly be undefined

### ISSUE THREAD

**Issue by dsherret** [Microsoft/TypeScript#26535]
Low priority issue, but the following is possible which can lead to errors when using the compiler API.

**TypeScript Version:**  3.1.0-dev.20180818

**Search Terms:** DocumentRegistry, languageVersion undefined

**Code**

```ts
import * as ts from "typescript";

const registry = ts.createDocumentRegistry();
const sourceFile = registry.acquireDocument("/file.ts", {}, ts.ScriptSnapshot.fromString(""), "1");

console.log(sourceFile.languageVersion); // undefined, but languageVersion is not nullable
```

Caused by the non-null assertion [here](https://github.com/Microsoft/TypeScript/blob/e53e56cf8212e45d0ebdd6affe462d161c7e0dc5/src/services/documentRegistry.ts#L202).

**Expected behavior:** Not sure. Probably it should default to `ScriptTarget.Latest` or the compiler options should pass through the function that sets the default values.

**Actual behavior:** `languageVersion` is undefined because it was not set on the compiler options.

**Related issues:** Maybe #18217 covers this already.

**Comment by RyanCavanaugh** [comment]
@sheetalkamat @rbuckton opinions on expected behavior?

**Comment by sheetalkamat** [comment]
I think we need to change https://github.com/Microsoft/TypeScript/blob/master/src/services/documentRegistry.ts#L187 to 
```typescript
const scriptTarget = scriptKind === ScriptKind.JSON ? ScriptTarget.JSON : compilationSettings.target ||  ScriptTarget.ES5;
```

**Comment by dsherret** [comment]
@sheetalkamat thanks! Opened a PR with ES5.

I took a look around the code and it defaults to ES3 in program.ts though. Maybe we should do the same here?

**Comment by sheetalkamat** [comment]
Language service defaults to ES5 while tsc defaults to ES3
