### ISSUE TITLE
Better support for indexing object literal aka switch as expression

### ISSUE THREAD

**Issue by phaux** [Microsoft/TypeScript#26539]
## Search Terms

object literal indexing, switch expression

## Suggestion

Given the following programming pattern:

```js
const parseFunc = {
  ".json": s => JSON.parse(s),
  ".cson": s => CSON.parse(s),
  ".toml": s => TOML.parse(s),
}[fileExt]
if (parseFunc) return parseFunc(str)
```

I would expect this to work without the "object doesn't have index signature" error. It would probably require special casing the `{…}[var]` syntax, so that it returns an union of the object value types + undefined.

## Use Cases

Basically a switch statement but as an expression.

## Checklist

My suggestion meets these guidelines:
* [ ] (dunno) This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by AnyhowStep** [comment]
Doesn't this already work?

```ts
declare const CSON: { parse: (str: string) => any };
declare const TOML: { parse: (str: string) => any };

function foo(fileExt: ".json" | ".cson" | ".toml", str: string) {
    const parseFunc = {
        ".json": JSON.parse,
        ".cson": CSON.parse,
        ".toml": TOML.parse,
    }[fileExt]
    if (parseFunc) return parseFunc(str);
}
```

[TS Playground link](http://www.typescriptlang.org/play/#src=declare%20const%20CSON%3A%20%7B%20parse%3A%20(str%3A%20string)%20%3D%3E%20any%20%7D%3B%0Adeclare%20const%20TOML%3A%20%7B%20parse%3A%20(str%3A%20string)%20%3D%3E%20any%20%7D%3B%0A%0Afunction%20foo(fileExt%3A%20%22.json%22%20%7C%20%22.cson%22%20%7C%20%22.toml%22%2C%20str%3A%20string)%20%7B%0A%20%20%20%20const%20parseFunc%20%3D%20%7B%0A%20%20%20%20%20%20%20%20%22.json%22%3A%20JSON.parse%2C%0A%20%20%20%20%20%20%20%20%22.cson%22%3A%20CSON.parse%2C%0A%20%20%20%20%20%20%20%20%22.toml%22%3A%20TOML.parse%2C%0A%20%20%20%20%7D%5BfileExt%5D%0A%20%20%20%20if%20(parseFunc)%20return%20parseFunc(str)%3B%0A%7D)

**Comment by andy-ms** [comment]
I'm guessing for you `fileExt` is `string`, and you're assuming that `parseFunc` will be undefined if `fileExt` is not one of ".json", ".cson", or ".toml"? That won't be typesafe because the access looks for `Object.prototype` which could contain things of arbitrary type -- if `fileExt` were "constructor" you would get confusing errors later.

**Comment by phaux** [comment]
The thing about prototypes is a valid point. I guess the only way is to use IIFE + regular switch. This works:
```ts
const parse = (() => {
  switch (ext) {
    case '.json': return JSON.parse
    case '.toml': return TOML.parse
    default: throw Error(`Invalid file extension "${ext}"`)
  }
})()
```
