### ISSUE TITLE
"Go to definition" doesn't work on static methods inside JS-class

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#26544]
_From @Friksel on August 16, 2018 8:55_

- VSCode Version: 1.26.0
- OS Version: Windows 10

Steps to Reproduce:

1. Have a class with calls to a static method:
```js
export default class Main {
    constructor() {
        const btns = document.querySelectorAll('.test-btn');
        if (btns) {
            btns.forEach((btn) => {
                btn.addEventListener('mousedown', this.constructor.onButtonMousedown);
            });
        }
    }

    static onButtonMousedown(e) {
        console.log('hit', e.currentTarget);
    }
}
```
2. Put mousecursor on `this.constructor.onButtonMousedown` and hit F12 (go to definition) --> nothing happens except for a tooltip popping up saying there is no definion found. 

Does this issue occur when all extensions are disabled?: Yes (checked with all extensions off)

_Copied from original issue: Microsoft/vscode#56546_

**Comment by RyanCavanaugh** [comment]
See #3841 - `constructor` is not strongly typed

**Comment by Friksel** [comment]
@RyanCavanaugh you seem to refer to my question as if I'm talking about Typescript, but I'm not. The question and my code is in Javascript

**Comment by RyanCavanaugh** [comment]
@Friksel JS Intellisense is powered by the same type system, and the type system is what's used to determine where navigation should take you. If/when we address #3841, this issue would be fixed at the same time.

**Comment by Friksel** [comment]
@RyanCavanaugh Alright, I understand. thanks.
