### ISSUE TITLE
import() returns different type from actual type

### ISSUE THREAD

**Issue by timocov** [Microsoft/TypeScript#26543]
**TypeScript Version:**  3.0.1, 3.1.0-dev.20180818

**Search Terms:** dynamic imports, import-type

**Steps to reproduce**

1. `npm install hammerjs @types/hammerjs typescript@next`
1. `./node_modules/.bin/tsc --init`
1. `touch index.ts`
1. Insert the following code in `index.ts`:
    ```ts
    export function loadHammer(): Promise<typeof import('hammerjs')> {
        return import('hammerjs');
    }
    ```
1. `./node_modules/.bin/tsc --noEmit --lib es2015,dom`

**Expected behavior:**

No errors.

**Actual behavior:**

```
index.ts:2:5 - error TS2322: Type 'Promise<{ default: HammerStatic; defaults: HammerDefaults; VERSION: number; INPUT_START: number; INPUT_MOVE: number; INPUT_END: number; INPUT_CANCEL: number; STATE_POSSIBLE: number; STATE_BEGAN: number; ... 36 more ...; prefixed(obj: any, property: string): string; }>' is not assignable to type 'Promise<HammerStatic>'.
  Type '{ default: HammerStatic; defaults: HammerDefaults; VERSION: number; INPUT_START: number; INPUT_MOVE: number; INPUT_END: number; INPUT_CANCEL:number; STATE_POSSIBLE: number; STATE_BEGAN: number; ... 36 more ...; prefixed(obj: any, property: string): string; }' is not assignable to type 'HammerStatic'.
    Type '{ default: HammerStatic; defaults: HammerDefaults; VERSION: number; INPUT_START: number; INPUT_MOVE: number; INPUT_END: number; INPUT_CANCEL: number; STATE_POSSIBLE: number; STATE_BEGAN: number; ... 36 more ...; prefixed(obj: any, property: string): string; }' provides no match for the signature 'new (element: HTMLElement | SVGElement, options?: HammerOptions | undefined): HammerManager'.

2     return import('hammerjs');
      ~~~~~~~~~~~~~~~~~~~~~~~~~~
```

It seems that `new( element:HTMLElement | SVGElement, options?:HammerOptions ): HammerManager;` is not exist in type of `import('hammerjs')` expression.

Even if I change `Promise<typeof import('hammerjs')>` to `Promise<HammerStatic>` or `Promise<typeof Hammer>` (or even import `hammerjs` as `import * as HammerJS from 'hammerjs';` and then use `Promise<typeof HammerJS>`) it still does not work.

**Comment by RyanCavanaugh** [comment]
This is a correct error.

The function signature claims that this is a legal thing to do:
```ts
const h = await loadHammer();
const x = new h(/*element*/ null as any);
```
But it isn't, because dynamic imports can only load the *properties* of the loaded module. The emitted code emulates this behavior and you'd see a runtime exception.

`import` types don't make the property/call signature distinction because you could be doing a correct CommonJS import via `require`.

You can express that the function doesn't return the `new` part of `hammer` to remove the error:
```ts
type PropertiesOnly<T> = { [K in keyof T]: T[K] }

export async function loadHammer(): Promise<PropertiesOnly<typeof import('hammerjs')>> {
    // OK
    return import('hammerjs');
}
```

See also https://stackoverflow.com/questions/39415661/what-does-resolves-to-a-non-module-entity-and-cannot-be-imported-using-this

**Comment by timocov** [comment]
Wow, thanks a lot for clarification!
