### ISSUE TITLE
[Proposal] change `Object.create` in `lib.d.ts`

### ISSUE THREAD

**Issue by texastoland** [Microsoft/TypeScript#26541]
## Search Terms

`object create null`

## Suggestion

Change `Object.create` in `lib.d.ts`.

```ts
namespace Object {
  export type NullPrototype = Record<keyof Object, never>
}

interface ObjectConstructor {
  create
    <T extends object | null>
    (proto: T):
    T extends null ? Object.NullPrototype : T
}
```

## Use Cases

#1108

## Examples

[Playground](https://agentcooper.github.io/typescript-play/#code/HYQwtgpgzgDiDGEAEB5ARgKwvALkg3gFBJIQAeMA9gE544CeMyAcgK4A27ACtZTn42QBeJACVsNACYAeANYR6lAGapM2HABokwCADcI1AHyEAvoUIBLYDgNKEydFlwBhSsCg5qrXDQLEk8NQQIDb+JNIAKqRkNsCSUEiUarhIAD7aHOzGJCQAFDC8-ABcSBEAlEVhpdGx8RmcSAD8qk44AHRsnDx8AkxIJRGm5lY21HaISACSACIWuAAyFvKRhgQA2vL0JR7UVgDmALoDZgx9swtLwlPnOIvLO-urAGQt6h2Z3fynEITwbh5ISRzW6XEo3O5XRxvQLBGy5YCZMrmP7uSjsCBtdiUPa5IEXeRtTZIlFQNEYrE4vEggn8ADKnn2uTKSIA9CychycgA9Hm8vn8vmENlIZwgYDAPhIKy6SjyJBi6IFaBQCxuJAAdwAFpQoMhvkh2AhZAkQAEQA0VXtQDhWEE2kL2RFBEgAOQ6fTUF1ITUgBISgKUMBwHAWNDos0WixWkK26D2h1IWngPXO32vXBtGEhCC5ACC1GoIHobQKPW+xP+eBABaLEKQIihGazcLWBwrqPRmOxuWrhfoEMJClZ7M5o7HSF5Ce6TFo9Fdmy9kko0G0kvIFgBav1LrF9FbLraSFmkiQilYSEgCpdmygLsav3+ZK7ON7tcubTpDOAOOZhCAA)

```ts
interface IDictLike<T> {[key: string]: T}
type DictLike = IDictLike<string> & Object.NullPrototype
const dictLike: DictLike = Object.create(null)

console.log(dictLike.key)
console.log(dictLike.toString())
//          ^^^^^^^^^^^^^^^^^^^
// Cannot invoke an expression whose type lacks a call signature.
// Type 'never' has no compatible call signatures.

// Same type as Object.create(Array.prototype)
const arrayLike = Object.create([])
console.log(arrayLike.key)
//                    ^^^
// Property 'key' does not exist on type 'any[]'. Did you mean 'keys'?
console.log(arrayLike.toString())
```

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by RyanCavanaugh** [comment]
This is a breaking change. The problem here is that you end up creating a poisoned object where you can't use those fields *at all* -- this code becomes illegal:
```ts
const x = Object2.create(null);
// Error, can't assign () => string to never
x.toString = () => "";
```

It also doesn't catch errors in places where you'd presumably want it to:
```ts
function fn(obj: { toString(): string }) { obj.toString() };
const x = Object.create(null);
// No error; crashes
fn(x);
```

**Comment by texastoland** [comment]
👍🏽 makes sense.
