### ISSUE TITLE
Spread operator does not call property getters

### ISSUE THREAD

**Issue by andreashuber69** [Microsoft/TypeScript#26547]
**Search Terms:**
spread operator, property getter

**Code**

```ts
interface IWhatever {
    readonly value: number;
}

class Whatever implements IWhatever {
    public get value() {
        return 42;
    }
}

const whatever: IWhatever = new Whatever();
const obj = { ...whatever, otherValue: 43 };
console.log(obj);
```

**Expected behavior:**
{ value: 42, otherValue: 43 }

This is expected because a readonly property of an interface can be implemented with a getter. The code using the interface cannot know that the property is implemented with a getter and therefore expects to see the property of the interface in the result. 

**Actual behavior:**
{ otherValue: 43 }

**Playground Link:**
[Link](https://www.typescriptlang.org/play/#src=interface%20IWhatever%20%7B%0D%0A%20%20%20%20readonly%20value%3A%20number%3B%0D%0A%7D%0D%0A%0D%0Aclass%20Whatever%20implements%20IWhatever%20%7B%0D%0A%20%20%20%20public%20get%20value()%20%7B%0D%0A%20%20%20%20%20%20%20%20return%2042%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aconst%20whatever%3A%20IWhatever%20%3D%20new%20Whatever()%3B%0D%0Aconst%20obj%20%3D%20%7B%20...whatever%2C%20otherValue%3A%2043%20%7D%3B%0D%0Aconsole.log(obj)%3B%0D%0A)

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
TypeScript doesn't change the behavior of JavaScript.

![image](https://user-images.githubusercontent.com/6685088/44352043-2040e000-a458-11e8-91d7-3a101f0a8e7d.png)

**Comment by andreashuber69** [comment]
That's a fair point, ts isn't responsible for how js works. However, if we expand the example code just a little bit, e.g. as follows...

```ts
interface IWhatever {
    readonly value: number;
}

class Whatever implements IWhatever {
    public get value() {
        return 42;
    }
}

class Utility {
    public static Do(x: IWhatever) {
        return x.value;
    }
}

const whatever: IWhatever = new Whatever();
const obj = { ...whatever, otherValue: 43 };
console.log(Utility.Do(obj));
```
... it becomes clear that the compiler does assume that obj implements the interface, otherwise the code should not compile. More precisely, the compiler falsely assumes that obj will always have a value property even though there's the possibility that it might not.

**Comment by RyanCavanaugh** [comment]
See #9726

**Comment by RyanCavanaugh** [comment]
See also #26287

I'm not sure what you're proposing happen. We don't track own/enumerability (see other open issues on that) so what line should be an error?

**Comment by andreashuber69** [comment]
I'm not sure what should happen, I just think this is a hole in the type system. 

If I had to implement this, I'd say the compiler should not make any assumptions what properties are added to an object by the spread operator. So, the call to `Utility.Do` should be flagged because `obj` cannot be guaranteed to implement the `IWhatever` interface. The programmer could still make the call by casting `obj` to `IWhatever` first.

**Comment by andreashuber69** [comment]
And yes, #26279 is very related. The issue only talks about classes with getters, so I'm not sure whether the fix would also correct the issue WRT interfaces as shown above.

**Comment by RyanCavanaugh** [comment]
It wouldn't fix this case due to the indirection via `IWhatever`

**Comment by andreashuber69** [comment]
Ok, thanks. How are we going forward with this problem (if it is one)? Should I file another issue that more succinctly explains the matter?

**Comment by RyanCavanaugh** [comment]
I don't think there's anything to do about it unless we were going to add a `--strictOwnAndEnumerability` flag to enforce tracking ownness/enumerability on all properties, which seems extraordinarily unlikely.

**Comment by CHBaker** [comment]
Would it be possible to type cast the spread operator value with the properties it is filling in? I think that would be useful instead of assuming the coder is correct

**Comment by ChemaCLi** [comment]
I made it in this way:
```js
function getModelProperties (model: any) {
  return Object.values(model)['0'] as any
}

const student = new Student()
student.name = "Chema" // supose you have the name setter

console.log({ data: { ... getModelProperties(student)} })
// { data: { name: "Chema" } }
```

**Comment by Brain2000** [comment]
It seems the spread operator in Javascript skips over getters in classes, but not in objects.
Sometimes I feel the person implementing Javascript is really high.

```
class C { get x() { return 1; }}
const c = new C();
console.log({...c});  <---does not show x
```

```
const c = { get x() { return 1; }}
console.log({...c}); <---does show x
```
