### ISSUE TITLE
Inconsistent narrowing from unions with overlapping possibly-optional properties

### ISSUE THREAD

**Issue by jcalz** [Microsoft/TypeScript#26551]
**TypeScript Version:**  3.1.0-dev.20180813

**Search Terms:**
type guard, narrowing, union, optional, overlapping 

**Code**

```ts
// --strictNullChecks on, please
declare function guard(w: any): w is { a: string | undefined };

declare const x: { a?: string };
x.a; // string | undefined
if (guard(x)) {
  x.a; // string | undefined
}

declare const y: { a?: string } | { a: string };
y.a // string | undefined
if (guard(y)) {
  y.a; // string ??
}

```

**Expected behavior:**
With `--strictNullChecks` on: after being narrowed by the type guard, both `x.a` and `y.a` should be `string | undefined`.  

**Actual behavior:**
The type guard narrows `y` to `{a: string}` for some reason.  The `{a?: string}` constituent is presumably being eliminated from the union, but I'm not sure why.  

**Playground Link:** 
[Link](https://www.typescriptlang.org/play//#src=%2F%2F%20--strictNullChecks%20on%2C%20please%0Adeclare%20function%20guard%28w%3A%20any%29%3A%20w%20is%20%7B%20a%3A%20string%20%7C%20undefined%20%7D%3B%0A%0Adeclare%20const%20x%3A%20%7B%20a%3F%3A%20string%20%7D%3B%0Ax.a%3B%20%2F%2F%20string%20%7C%20undefined%0Aif%20%28guard%28x%29%29%20%7B%0A%20%20x.a%3B%20%2F%2F%20string%20%7C%20undefined%0A%7D%0A%0Adeclare%20const%20y%3A%20%7B%20a%3F%3A%20string%20%7D%20%7C%20%7B%20a%3A%20string%20%7D%3B%0Ay.a%20%2F%2F%20string%20%7C%20undefined%0Aif%20%28guard%28y%29%29%20%7B%0A%20%20y.a%3B%20%2F%2F%20string%20%3F%3F%0A%7D)

**Related Issues:** 
Didn't find anything obvious... maybe #11403 or #17561? 

Noticed in a [comment](https://github.com/Microsoft/TypeScript/issues/21732#issuecomment-414328387) in #21732.

**Comment by RyanCavanaugh** [comment]
This is the relevant code
```ts
// If the current type is a union type, remove all constituents that couldn't be instances of
// the candidate type. If one or more constituents remain, return a union of those.
if (type.flags & TypeFlags.Union) {
    const assignableType = filterType(type, t => isRelated(t, candidate));
    if (!(assignableType.flags & TypeFlags.Never)) {
        return assignableType;
    }
}
// If the candidate type is a subtype of the target type, narrow to the candidate type.
// Otherwise, if the target type is assignable to the candidate type, keep the target type.
// Otherwise, if the candidate type is assignable to the target type, narrow to the candidate
// type. Otherwise, the types are completely unrelated, so narrow to an intersection of the
// two types.
return isTypeSubtypeOf(candidate, type) ? candidate :
    isTypeAssignableTo(type, candidate) ? type :
        isTypeAssignableTo(candidate, type) ? candidate :
            getIntersectionType([type, candidate]);
```

Basically, unions and non-unions narrow differently. For a union, we remove non-assignable constituents; for a non-union, we intersect in the guarded type if it's disjoint from the original type. This generally produces the best behavior in both cases, at the cost of creating an "inconsistency"

**Comment by jcalz** [comment]
Thanks.  I guess I don't see how `{ a?: string }` is removed from the union though... since we're testing if it's assignable to `{ a?: string }`, right?

**Comment by RyanCavanaugh** [comment]
`isRelated` is `isRelated(source, target)` - we're testing assignability *from* each union constituent (actually relation is subtype in this case)

**Comment by jcalz** [comment]
Ah, okay.
