### ISSUE TITLE
[BUG] In the generated description file, the class type does not check the implemented interface.

### ISSUE THREAD

**Issue by ZSkycat** [Microsoft/TypeScript#26555]
**TypeScript Version:**  3.1.0-dev.20180818

**Search Terms:** description file class type interface implements

**Code**
```ts
export type LibObjectType = 'Circle' | 'Square';

export interface LibObject {
    readonly type: LibObjectType;
    readonly id: number;
}

export class LibCircle implements LibObject {
    readonly type = 'Circle';
    readonly id: number = Date.now();
}

export class LibSquare implements LibObject {
    readonly type = 'Square';
    readonly id: number = Date.now();
}
```

**Expected behavior:**
```ts
// index.d.ts
export declare class LibCircle implements LibObject {
    readonly type: 'Circle';
    readonly id: number;
}
```
![image](https://user-images.githubusercontent.com/20368649/44359327-1a93da80-a4ea-11e8-93ed-22c0181f6163.png)

**Actual behavior:**
```ts
// index.d.ts
export declare class LibCircle implements LibObject {
    readonly type: string;
    readonly id: number;
}
```
![image](https://user-images.githubusercontent.com/20368649/44359275-ff28cf80-a4e9-11e8-9e28-d4b0f6ebb34f.png)

**Playground Link:** 
https://github.com/ZSkycat/issue-typescript-20180821-1

**Related Issues:**

**Comment by weswigham** [comment]
Duplicated of #25990,

Two part fix is already up involving #26556 and #26313

**Comment by ZSkycat** [comment]
@RyanCavanaugh @weswigham 
I found a new issue. The correct type cannot be inferred without using readonly.
Should I open a new issue?

```
export type LibObjectType = 'Circle' | 'Square';

export interface LibObject {
    type: LibObjectType;
    id: number;
}

export class LibCircle implements LibObject {
    type = 'Circle';
    id: number = Date.now();
}

export class LibSquare implements LibObject {
    type = 'Square';
    id: number = Date.now();
}
```

![tim 20180821103706](https://user-images.githubusercontent.com/20368649/44377165-3ae58880-a52e-11e8-8061-536a4138c2dc.png)

**Comment by weswigham** [comment]
That's expected. Mutable locations widen literal types to their base unless appropriately contextually typed, and class properties aren't coming contextualized by their base. We have a bunch of discussions open on that.
