### ISSUE TITLE
Private members cause issues when same class is used between dependencies

### ISSUE THREAD

**Issue by ShwetaTurakhia** [microsoft/TypeScript#26559]
TypeScript Version:

2.9.2

Actual behavior:

Suppose that library-a is an NPM package that exports a TypeScript class called MyClass, and my and library-b consume this class. If those packages find the MyClass.d.ts definition via two different file paths on disk, and if MyClass contains a private member, then the compiler reports an error because it does not trust that the implementations are interchangeable.

This makes sense in general, however there are two everyday NPM usage scenarios where provably equivalent definitions must unavoidably have different file paths. In this situation the TypeScript error is not reasonable and may make life difficult for developers.

**Code**

library-a exports MyClass
library-b depends on library-a version 1.0

My package depends on library-a version 2.0 and library-b version 2.0

My code calls a method in library-b which take a parameter MyClass

On building my package, the MyClass is present in 2 places

Mypackage\node_modules\library-a\lib\MyClass.d.ts
Mypackage\node_modules\library-b\node_modules\MyClass.d.ts

import { MyClass } from 'library-a';
import { BClass } from 'library-b';

export default class MyLibrary {
 public void getMyClass(obj: MyClass) {
  BClass.sendObject(obj);
 }
}

The error looks like this:

error TS2345: Argument of type 'import("/Users/test/Documents/workspace/mypackage/node_modules/lib-a/MyClass...' is not assignable to parameter of type 'import("/Users/test/Documents/workspace/mypackage/node_modules/lib-b/node_modules/lib-a/MyClass...'.
  Types have separate declarations of a private property 'relationId'.

**Expected behavior:**
Given that MyClass definition in both the version is same, I should be able to send MyClass object to the method in lib B

**Actual behavior:**

error TS2345: Argument of type 'import("/Users/test/Documents/workspace/mypackage/node_modules/lib-a/MyClass...' is not assignable to parameter of type 'import("/Users/test/Documents/workspace/mypackage/node_modules/lib-b/node_modules/lib-a/MyClass...'.
  Types have separate declarations of a private property 'relationId'.

**Playground Link:**  

**Related Issues:**
https://github.com/Microsoft/TypeScript/issues/8346

**Comment by RyanCavanaugh** [comment]
> library-a exports MyClass
> library-b depends on library-a version 1.0
> My package depends on library-a version 2.0 and library-b version 2.0

It is absolutely not safe for a v1 `library-a` instance to be passed to a place where a v2 implementation could see it. The private field could have changed type between versions; we have no way to know that it's safe and the conservative choice is to disallow it.

**Comment by ShwetaTurakhia** [comment]
Thanks @RyanCavanaugh Are you suggesting that lib B should not accept the instance of MyClass(lib-a) and hence mypackage will not have to create an instance of MyClass and send it to the method in Lib-b? Consider lib-b is not my package and owned by some third party

**Comment by RyanCavanaugh** [comment]
Correct. `lib-b` exposing `lib-a` directly really means it's directly coupling any of its consumers to that same version.

**Comment by ShwetaTurakhia** [comment]
Thanks @RyanCavanaugh one last question , Is it better to add lib-a 1.0 as devDependency in lib-b? so that my package can depend on lib-a 2.0 and lib-b? Because this removes all the compile errors I was getting.

**Comment by GarimaBathla** [comment]
@RyanCavanaugh I believe npm and node support that each module can have its own dependency - 

So my project structure can look like - 

Project 
  node_modules
     lib-a
       node_modules
          lib-b (v1)
    lib-c
      node_modules
          lib-b (v2)

So this is actually allowed by nom and it resolves dependency correctly.

Problem here is the way definition file is generated. 

In this case - my definition file look like - 
`/**
 * Created by Garima Bathla on 8/3/17.
 */
export declare class BaasEnvContext {
    private relationId;
    private initialized;
    private logger;
    constructor(event: any, context: any, fetchFromEvent: boolean);
    getCorrelationId(): string;
    private initialize(event, context, fetchFromEvent);
}
`
Like you said 
`It is absolutely not safe for a v1 library-a instance to be passed to a place where a v2 implementation could see it (or vice versa). The private field could have changed type between versions; we have no way to know that it's safe and the conservative choice is to disallow it.`

private field can change type between versions, so question I have is - why my definition file is stripping the type - this is typescript so I assume every field should have it's type in the definition file - that could be used by tsc to truely check if the types are really same or different - right now compiler is assuming types are not same.

**Comment by RyanCavanaugh** [comment]
We don't even know that the private field has the same *meaning* across versions, even if the type stays the same. You also have to consider whether e.g. the class keeps a lookup table of its own instances to consult for certain operations.

If you have two versions of a library, it is really never safe to interchange instances between those versions unless it's explicitly documented to work that way in terms of the public interface (which precludes referring to the class type at all). If anything we aren't strict *enough* in this regard.
