### ISSUE TITLE
Type of `let foo: 'foo' | 'bar' = 'foo'` is different from `let foo = 'foo' as 'foo' | 'bar'`

### ISSUE THREAD

**Issue by paulkoerbitz** [Microsoft/TypeScript#26560]
**Search Terms:**
Literal type, inference, type annotation, control flow type analysis

**Code**

```ts
type FooBar = 'foo' | 'bar';
let foo: FooBar = 'foo';
let bar = 'bar' as FooBar;
type fooT = typeof foo; // Expected this type to be FooBar but is 'foo'
type barT = typeof bar; // This type is FooBar, as expected
let nobar: fooT & barT = 'bar'; // Gives error as `fooT & barT = 'foo' & ('foo' | 'bar') = 'foo'``
```

**Expected behavior:**
I expected `foo` and `bar` to be both of type FooBar.

**Actual behavior:**
foo has type `'foo'` and thus the code gives this error:
src/bug.ts:6:5 - error TS2322: Type '"bar"' is not assignable to type '"foo"'

**Observations:**
If in the example we assign `'bar'` to `foo` before taking its type the code works. I'm guessing this has something to do with control flow type analysis.

Maybe this is expected behavior but I find it highly confusing.

**Playground Link:** 
https://www.typescriptlang.org/play/#src=type%20FooBar%20%3D%20'foo'%20%7C%20'bar'%3B%0D%0Alet%20foo%3A%20FooBar%20%3D%20'foo'%3B%0D%0Alet%20bar%20%3D%20'bar'%20as%20FooBar%3B%0D%0Atype%20fooT%20%3D%20typeof%20foo%3B%20%2F%2F%20Expected%20this%20type%20to%20be%20FooBar%20but%20is%20'foo'%0D%0Atype%20barT%20%3D%20typeof%20bar%3B%20%2F%2F%20This%20type%20is%20FooBar%2C%20as%20expected%0D%0Alet%20nobar%3A%20fooT%20%26%20barT%20%3D%20'bar'%3B%20%2F%2F%20Gives%20error%20as%20%60fooT%20%26%20barT%20%3D%20'foo'%20%26%20('foo'%20%7C%20'bar')%20%3D%20'foo'%60%60

**Comment by RyanCavanaugh** [comment]
`typeof foo` yields the type of `foo` at the location where it's written; in this position the initialization with `"foo"` is in effect and the narrowed type is observed.

>  I find it highly confusing.

Understandable. `typeof` could do one of two things - produce the type of the expression at that location, or produce the type of the symbol as it's declared. Since you can always move the declaration of the type alias to a location where no control flow analysis is in effect, it's more flexible to do the former.

**Comment by paulkoerbitz** [comment]
OK, I understand. I'm fine with closing this if it is expected behavior. 

Just as a side note, it doesn't just affect typeof, it also affects any inferred types when using foo (guess that is using the same mechanism)? I just wasn't sure this was really expected behavior, hence the report.

**Comment by paulkoerbitz** [comment]
Closing this. 

I just went through @RyanCavanaugh 's twitter and saw he tweeted about another reporter commenting on the super quick feedback on an issue given there are >=2700 open issues (and ~25K closed ones!!!)

Its definitely a compliment on this fantastically run project. I was amazed as well. Go TypeScript!
