### ISSUE TITLE
Hover type definition is wrongly inferred, but tsc type is correct

### ISSUE THREAD

**Issue by hf** [Microsoft/TypeScript#26577]
There's a small but annoying issue in the `tsserver` implementation (as far as I can tell) that's been around for a long time, I'm tracking from version 2.6.

Namely, there is a mapped-type pattern I want to use, as shown in code below, and the hover type definition doesn't infer multiple levels deep. However, interestingly, `tsc` does infer the type correctly.

**TypeScript Version:**  2.6+

**Code**

```ts
type F<T> = (value: any) => T

function all<V>(vals: { [K in keyof V]: F<V[K]> }): (value: any) => V {
    return null as any;
}

// inspect the hover type of `x`
// it should show const x: { a: { b: any } }
const x = all({
    a: all({
        b: (value: any) => 3
    })
})(3)

// inspect the hover type of `b`
// it should show (property) b: number
x.a.b;

// and obviously this does not compile
x.a.b = 'not-a-number';
```

**Expected behavior:**

The hover type definition (and it's variants) should show 

```ts
const x: { a: { b: number } }
```

**Actual behavior:**

The hover type definition for `x` is 

```ts
const x: { a: { b: any } }
```

[**Playground Link**](https://www.typescriptlang.org/play/#src=type%20F%3CT%3E%20%3D%20(value%3A%20any)%20%3D%3E%20T%0A%0Afunction%20all%3CV%3E(vals%3A%20%7B%20%5BK%20in%20keyof%20V%5D%3A%20F%3CV%5BK%5D%3E%20%7D)%3A%20(value%3A%20any)%20%3D%3E%20V%20%7B%0A%20%20%20%20return%20null%20as%20any%3B%0A%7D%0A%0A%2F%2F%20inspect%20the%20hover%20type%20of%20%60x%60%0A%2F%2F%20it%20should%20show%20const%20x%3A%20%7B%20a%3A%20%7B%20b%3A%20any%20%7D%20%7D%0Aconst%20x%20%3D%20all(%7B%0A%20%20%20%20a%3A%20all(%7B%0A%20%20%20%20%20%20%20%20b%3A%20(value%3A%20any)%20%3D%3E%203%0A%20%20%20%20%7D)%0A%7D)(3)%0A%0A%2F%2F%20inspect%20the%20hover%20type%20of%20%60b%60%0A%2F%2F%20it%20should%20show%20(property)%20b%3A%20number%0Ax.a.b%3B%0A%0A%2F%2F%20and%20obviously%20this%20does%20not%20compile%0Ax.a.b%20%3D%20'not-a-number'%3B)

**Related Issues:** Not that I found.

**Comment by RyanCavanaugh** [comment]
Duplicate #23897
