### ISSUE TITLE
Related error spans on non-async functions containing 'await'

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#26586]
https://twitter.com/sebmck/status/1031974060832436224

Even though we provide a quick fix, it'd be great if we could provide a related span describing a fix on a containing function. Something like

```
Did you mean to mark this function as 'async'?
```

**Comment by akshita31** [comment]
I would like to work on this one. Any help on how I should proceed and where does the related code live ?

**Comment by LasaleFamine** [comment]
I would like to take this one if @akshita31 drop it.

@DanielRosenwasser do you mean to add this within the [diagnostic error messages](https://github.com/Microsoft/TypeScript/blob/13bc46d9707036928e51be91d8d6aeaf95e63132/src/services/codefixes/fixAwaitInSyncFunction.ts#L4) or add a new message as info?

**Comment by DanielRosenwasser** [comment]
If either of you are interested just say you're tackling it and go for it. You'll need to add a new diagnostic and reported as related info on the main error.

**Comment by DanielRosenwasser** [comment]
Thank you @uhyo!
