### ISSUE TITLE
Codefix for "Did you mean to include 'new'?"

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#26580]
## Suggestion

Given this code:

```ts
class C {}
C();
```
The error message says `Did you mean to include 'new'?`. We should have code fix that adds 'new' in front of the call expression.

**Comment by DavidSotoA** [comment]
Can I take this?

**Comment by LasaleFamine** [comment]
Hi there, I would like to help with this (maybe simple) task. Have you some hint for me to start working on this? 

I'm just getting inside the source code, maybe I will find something meanwhile.

**Comment by DanielRosenwasser** [comment]
No worries @LasaleFamine; thanks @iliashkolyar!
