### ISSUE TITLE
Issue with JSX spread and union types not fixed

### ISSUE THREAD

**Issue by KITSMalinnaLeach** [Microsoft/TypeScript#26598]
I am having this exact problem.  It was marked as fixed, but is not fixed on v. 2.7.2 or 2.8.1.

https://github.com/Microsoft/TypeScript/issues/18670

**TypeScript Version:**  2.7.2

**Search Terms:** typescript react spread operator union types

**Code**

Here is a sandbox illustrating this issue:

https://codesandbox.io/s/zom3jlnm4

**Expected behavior:**
You should be able to pass in union typed props using the spread operator

**Actual behavior:**
It throws an error

**Related Issues:** 
https://github.com/Microsoft/TypeScript/issues/18670

**Comment by RyanCavanaugh** [comment]
There isn't an issue with spread here.

`Props` constrains `name` to `"fred" | "paul"`, but the `nameProps` initializer isn't annotated in a way where TypeScript can guarantee that it has one of those values.

Lots of options; one would be to write this:
```ts
const nameProps = {
  name: "fred" as "fred"
};
```
to indicate that `nameProps.name` can't be changed to some other string.
