### ISSUE TITLE
Should be able to fold { ...\n\n\n } in JS/TS

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#26594]
_From @Astrantia on August 20, 2018 22:56_

Blocks enclosed by {...} should be collapsible:
```js
const Example = () => {
   return (
     <Fragment>
      {...
       ...
       this block
       should be
       collapsible
       ...
       ...
      }
    </Fragment>
    )
}
```
cc @mjbvz 

_Copied from original issue: Microsoft/vscode#56859_

**Comment by Kingwl** [comment]
Seems already have.

---

![image](https://user-images.githubusercontent.com/6831019/116208596-a9655480-a773-11eb-9f43-bff5e284a52e.png)

---

![image](https://user-images.githubusercontent.com/6831019/116208616-ad917200-a773-11eb-8d2f-53e3d6970ee3.png)
