### ISSUE TITLE
No JSDoc at call expression of property of function type

### ISSUE THREAD

**Issue by xbtsw** [Microsoft/TypeScript#26611]
**TypeScript Version:**  3.1.0-dev.201xxxxx

**Search Terms:**
jsdoc interface tooltip

**Code**

```ts
interface IMyInterface
{
    /**
     * my property a
     */
    a: string;
}

let o: IMyInterface = { a: "xyz" }; 

let oo: { [index: string]: IMyInterface } = {
    'test': {
        a: 'abc'
    }
};
```

**Expected behavior:**
The tooltip when hovering on "a" should show JSDoc

**Actual behavior:**
The tooltip when hovering on "a" does not show JSDoc

**Playground Link:** 
[Playground](https://www.typescriptlang.org/play/#src=interface%20IMyInterface%0D%0A%7B%0D%0A%20%20%20%20%2F**%0D%0A%20%20%20%20%20*%20my%20property%20a%0D%0A%20%20%20%20%20*%2F%0D%0A%20%20%20%20a%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Alet%20o%3A%20IMyInterface%20%3D%20%7B%20a%3A%20%22xyz%22%20%7D%3B%20%0D%0A%0D%0Alet%20oo%3A%20%7B%20%5Bindex%3A%20string%5D%3A%20IMyInterface%20%7D%20%3D%20%7B%0D%0A%20%20%20%20'test'%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20a%3A%20'abc'%0D%0A%20%20%20%20%7D%0D%0A%7D%3B)

**Related Issues:** 
Seems like a regression of #18358

**Comment by andy-ms** [comment]
This works for me with `typescript@next`.

**Comment by xbtsw** [comment]
@andy-ms Sorry I mistakenly thought the playground is the `@next` version. with vscode and typescript 3.1.0-dev.20180823. I found following example doesn't work:

```ts
interface ITest {
  /**
   * Test JSDoc
   */
  test: () => void;
}
export interface ITest2 {
  t: ITest;
}
const testObj: { [index: string]: ITest2 } = {};
testObj['a'].t.test();
```

![image](https://user-images.githubusercontent.com/4098537/44542653-508bb700-a6c2-11e8-85ae-ff24655125bb.png)

**Comment by andy-ms** [comment]
Thanks, repros with:
```ts
interface ITest {
    /**
     * Test JSDoc
     */
    test: () => void;
}
const testObj: ITest = <any>null;
testObj.test();
```
