### ISSUE TITLE
Discriminated union type inferencing doesn't work if attribute name has a period

### ISSUE THREAD

**Issue by abhinavg** [Microsoft/TypeScript#26613]
**TypeScript Version:**  3.0.0-dev.201xxxxx

**Search Terms:** 
Discriminated union period
**Code**

```ts
// Discriminated union with a discriminant attribute with a '.'. 
interface BarOption1 {
    ".kind": "option1";
    bar1: number;
}
interface BarOption2 {
    ".kind": "option2";
    bar2: string;
}
type Bar = BarOption1 | BarOption2; 
let bar: Bar
switch (bar[".kind"]) {
    case 'option1': {
        bar.bar1
        break;
    }
    case 'option2': {
        bar.bar2;
        break;
    }
}
```

**Expected behavior:**
No compiler error. 

**Actual behavior:**
Got compiler errors
```
Property 'bar1' does not exist on type 'Bar'.
  Property 'bar1' does not exist on type 'BarOption2'.
```
```
Property 'bar2' does not exist on type 'Bar'.
  Property 'bar2' does not exist on type 'BarOption1'.
```

**Playground Link:** 
[Playground link](https://www.typescriptlang.org/play/#src=%2F%2F%20Discriminated%20union%20with%20a%20discriminant%20attribute%20with%20a%20'.'.%20%0Ainterface%20BarOption1%20%7B%0A%20%20%20%20%22.kind%22%3A%20%22option1%22%3B%0A%20%20%20%20bar1%3A%20number%3B%0A%7D%0Ainterface%20BarOption2%20%7B%0A%20%20%20%20%22.kind%22%3A%20%22option2%22%3B%0A%20%20%20%20bar2%3A%20string%3B%0A%7D%0Atype%20Bar%20%3D%20BarOption1%20%7C%20BarOption2%3B%20%0Alet%20bar%3A%20Bar%0Aswitch%20(bar%5B%22.kind%22%5D)%20%7B%0A%20%20%20%20case%20'option1'%3A%20%7B%0A%20%20%20%20%20%20%20%20bar.bar1%0A%20%20%20%20%20%20%20%20break%3B%0A%20%20%20%20%7D%0A%20%20%20%20case%20'option2'%3A%20%7B%0A%20%20%20%20%20%20%20%20bar.bar2%3B%0A%20%20%20%20%20%20%20%20break%3B%0A%20%20%20%20%7D%0A%7D)
**Related Issues:**

**Comment by RyanCavanaugh** [comment]
Duplicate #10530 which is now fixed
