### ISSUE TITLE
`lib` option doesn't seem to work when compiling programatically

### ISSUE THREAD

**Issue by SamVerschueren** [microsoft/TypeScript#26622]
Hi

I'm building a small tool for myself which shows me the pre-compile diagnostics from a file.

```ts
export const runDiagnostics = (fileName: string) => {
	const {compilerOptions} = loadConfig();

	const program = ts.createProgram([fileName], compilerOptions);

	return ts.getPreEmitDiagnostics(program);
};
```

The `compilerOptions` object looks like this (when logged)

```json
{
    "target": "es6",
    "lib": [
        "es2015"
    ]
}
```

When I run the diagnostics on a file with this content

```ts
(async () => {
	const foo: string = await Promise.resolve('foo');
})();
```

It fails with the following errors

> 1. An async function or method must return a `Promise`. Make sure you have a declaration for `Promise` or include `ES2015` in your `--lib` option.
> 2. Cannot find name `Promise`

As you can see from my `compilerOptions` object, I already have `es2015` added to the `lib` array.

When I change the file to something without `async/await`, like this

```ts

Promise.resolve('foo')
	.then((result: string) => {
		// do nothing
	});
```

It only shows the 2nd error

> Cannot find name Promise.

What am I missing here?

Thanks in advance,
Sam

**Comment by RyanCavanaugh** [comment]
Your `compilerOptions` is malformed - a printed display should show `target` with the value `2` (`ts.ScriptTarget.ES2015`), not `"es6"`. Call `parseConfigFileTextToJson` or one of its friends

**Comment by SamVerschueren** [comment]
I would assume `ts.readConfigFile()` would handle that?

```
const {config, error} = ts.readConfigFile(configFile, ts.sys.readFile);
```

I couldn't get it to parse the `target` correctly, it always shows `es6`. So I tried setting the config manually like this

```ts
export const compile = (fileName: string) => {
	const program = ts.createProgram([fileName], {
		target: ts.ScriptTarget.ES2015,
		lib: [
			'es2015'
		]
	});

	return ts.getPreEmitDiagnostics(program);
};
```

Still the exact same errors

> 1. An async function or method must return a `Promise`. Make sure you have a declaration for `Promise` or include `ES2015` in your `--lib` option.
> 2. Cannot find name `Promise`

**Comment by SamVerschueren** [comment]
Currently I'm passing the following options to `createProgram()`

```json
{
	moduleResolution: ModuleResolutionKind.NodeJs,
	target: ScriptTarget.ES2015
}
```

This works as expected. But whenever I pass in `lib: ['es2015']`, it stops working again. Not sure why it does that though.

**Comment by RyanCavanaugh** [comment]
Sorry, cited the wrong function call. `getParsedCommandLineOfConfigFile` is probably what you want - you *really need* to have a `ParsedComandLine` obtained from from calling the commandline parsing code, not an options bag you wrote yourself. By the time it hits `createProgram`, the lib entries should have been resolved to filenames instead of being bare directive names - see `src/testRunner/unittests/commandlineParsing.ts`
