### ISSUE TITLE
 Compiler is unable to resolve return type of function even though it is returning function with known return type

### ISSUE THREAD

**Issue by devuxer** [microsoft/TypeScript#26623]
**TypeScript Version:**  3.0.1

**Search Terms:**

- "implicitly has return type 'any'"
- TS7023

**Code**

```ts
interface Identifiable {
    name: string;
    nickname: string;
    isNameSameAsNickname: boolean;
}

class Person implements Identifiable {
    public name = "Baz";
    public nickname = "Baz";

    get isNameSameAsNickname() {
        return compareNames(this);
    }
}

function compareNames(identifiable: Identifiable) {
    return identifiable.name === identifiable.nickname;
}
```

**Expected behavior:**

Compiles without error

**Actual behavior:**

The following error occurs:

> TS7023: 'isNameSameAsNickname' implicitly has return type 'any' because it does not have a return type annotation and is referenced directly or indirectly in one of its return expressions.

Comment: This error appears to be incorrect (or at least worded ambiguously) because `isNameSameAsNickname` is *not* referenced directly or indirectly in one of its return expressions. Specifically, `isNameSameAsNickname` does not appear directly in the return expression `compareNames(this)` nor does it appear indirectly in `identifiable.name === identifiable.nickname`.

**Workaround:**

Declare the return type explicitly:

```ts
get isNameSameAsNickname(): boolean {
    return compareNames(this);
}
```
**Playground Link:**

This error is indicated in the [playground](https://www.typescriptlang.org/play/#src=interface%20Identifiable%20%7B%0D%0A%20%20%20%20name%3A%20string%3B%0D%0A%20%20%20%20nickname%3A%20string%3B%0D%0A%20%20%20%20isNameSameAsNickname%3A%20boolean%3B%0D%0A%7D%0D%0A%0D%0Aclass%20Person%20implements%20Identifiable%20%7B%0D%0A%20%20%20%20public%20name%20%3D%20%22Baz%22%3B%0D%0A%20%20%20%20public%20nickname%20%3D%20%22Baz%22%3B%0D%0A%0D%0A%20%20%20%20get%20isNameSameAsNickname()%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20compareNames(this)%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Afunction%20compareNames(identifiable%3A%20Identifiable)%20%7B%0D%0A%20%20%20%20return%20identifiable.name%20%3D%3D%3D%20identifiable.nickname%3B%0D%0A%7D) with a red squiggle below `isNameSameAsNickname()`.

Note: Error only occurs if `noImplicitAny` option is checked

**Related Issues:**

- Open: #18805
- Closed: #22390, #8546, #5403

**Comment by RyanCavanaugh** [comment]
>  I gather it's a difficult problem or it would already be solved.

Yep 😉. The real issue here is that the two main operations the checker does - inference and error detection - occur at the "same time". You could imagine a different world where all inference happens, *then* all error checking happens, which would avoid this problem because the check of whether the argument type is assignable to the parameter type would only be part of the error-checking phase. But this would likely be at least twice as slow as the current implementation.

There's no set practice that will avoid all circularity issues. The return type annotation is the best alternative for this example, I would say.
