### ISSUE TITLE
argument types inference breaks for specific object literal method syntax

### ISSUE THREAD

**Issue by billba** [Microsoft/TypeScript#26629]
**TypeScript Version:**  3.1.0-dev.20180823

**Search Terms:** object literal method argument

**Code**
```ts
function goofus <ARGS extends any[]> (f: (...args: ARGS) => any ) {}

goofus((a: string) => ({ dog() { return a; } }));
goofus((a: string) => ({ dog: function() { return a; } }));
```

**Expected behavior:**
infers `ARGS === [string]`

**Actual behavior:**
`[ts] Argument of type '(a: string) => { dog(): string; }' is not assignable to parameter of type '() => any'.`

Note that everything works correctly if you do any of the below:
1. infer a single argument: `function gallant <ARG extends any> (f: (arg: ARG) => any ) {}`
2. use arrow syntax in the object literal: `goofus((a: string) => ({ dog: () => a }));`
3. use method syntax to return the object literal: `goofus(function (a: string) { return { dog() { return a; } } });`

**Playground Link:** [link](https://www.typescriptlang.org/play/#src=function%20gallant%20%3CARG%20extends%20any%3E%20(f%3A%20(arg%3A%20ARG)%20%3D%3E%20any%20)%20%7B%7D%0D%0A%0D%0Agallant((a%3A%20string)%20%3D%3E%20(%7B%20dog%3A%20()%20%3D%3E%20a%20%7D))%3B%0D%0A%2F%2F%20infers%20ARG%20%3D%3D%3D%20string%0D%0A%0D%0Agallant((a%3A%20string)%20%3D%3E%20(%7B%20dog()%20%7B%20return%20a%3B%20%7D%20%7D))%3B%0D%0A%2F%2F%20infers%20ARG%20%3D%3D%3D%20string%0D%0A%0D%0Afunction%20goofus%20%3CARGS%20extends%20any%5B%5D%3E%20(f%3A%20(...args%3A%20ARGS)%20%3D%3E%20any%20)%20%7B%7D%0D%0A%0D%0Agoofus((a%3A%20string)%20%3D%3E%20(%7B%20dog%3A%20()%20%3D%3E%20a%20%7D))%3B%0D%0A%2F%2F%20infers%20ARGS%20%3D%3D%3D%20%5Bstring%5D%0D%0A%0D%0Agoofus((a%3A%20string)%20%3D%3E%20(%7B%20dog()%20%7B%20return%20a%3B%20%7D%20%7D))%3B%0D%0A%2F%2F%20expected%3A%20infers%20ARGS%20%3D%3D%3D%20%5Bstring%5D%0D%0A%2F%2F%20actual%3A%20%20%20%5Bts%5D%20Argument%20of%20type%20'(a%3A%20string)%20%3D%3E%20%7B%20dog()%3A%20string%3B%20%7D'%20is%20not%20assignable%20to%20parameter%20of%20type%20'()%20%3D%3E%20any'.%0D%0A)

**Related Issues:** couldn't find any

**Comment by ahejlsberg** [comment]
This is an issue caused by #25937. I'll have a fix up shortly.

**Comment by billba** [comment]
Thank you!
