### ISSUE TITLE
ES6-only feature 'let' is in typescript.d.ts

### ISSUE THREAD

**Issue by alexeagle** [Microsoft/TypeScript#2663]
This seems to cause our target=es5 build to fail, though we haven't investigated much.

https://github.com/Microsoft/TypeScript/blob/863f0b61807b3f2aa91fbc7f43fed32915dcc589/bin/typescript.d.ts#L1463

**Comment by mhegazy** [comment]
what version of the compiler are you using? 1.4?

**Comment by alexeagle** [comment]
This is when we use the npm release 1.5.0-alpha

**Comment by basarat** [comment]
Let is no longer es6 only. So should work fine with es5 target.

**Comment by mhegazy** [comment]
I am unable to reproduce this issue. @alexeagle please let us know if you run into this issue again.
