### ISSUE TITLE
No error accessing abstract property in destructuring within constructor

### ISSUE THREAD

**Issue by ajafff** [microsoft/TypeScript#26642]
**TypeScript Version:**  3.1.0-dev.20180821

**Search Terms:**

**Code**

```ts
abstract class Foo {
    abstract prop: number;
    constructor() {
        let {prop} = this;
        ({prop} = this);
        prop = this.prop;
    }
}
```

**Expected behavior:**
Error on both destructurings of `{prop}`.
Error on `this.prop`.

**Actual behavior:**
No error on destructuring.
Error on `this.prop`.

**Playground Link:** https://agentcooper.github.io/typescript-play/#code/IYIwzgLgTsDGEAJYBthjAgYge2wg3gFAIkKiQzwIAOU21AXAgHYCuAtiAKZQDcxpWNmYVW8bFAAUASgIDSpZF0T5a9AL4IAvAggALAJZh+ChZNV1qmnfqPSTpkmurbdhsADpnDkusLqgA

**Related Issues:** #26407

**Comment by jakebailey** [comment]
#42265 was interestingly exactly the same issue as this one (same reporter), and was fixed in #42276
