### ISSUE TITLE
Bad formatting for default generic type arguments in type declarations

### ISSUE THREAD

**Issue by AlCalzone** [Microsoft/TypeScript#26656]
**TypeScript Version:**  3.1.0-dev.20180824

**Search Terms:** tuple generic space

**Code**
Format this:
```ts
type Foo<
	T1 extends any[],
	T2 extends any[] = []
> = T1 & T2;
```

**Expected behavior:**
Either **no change** or the following, although I would prefer no indentation on the last line to be consistent with curly braces and object literals:
```ts
type Foo<
	T1 extends any[],
	T2 extends any[] = []
	> = T1 & T2;
```
**Actual behavior:**
```ts
type Foo<
	T1 extends any[],
	T2 extends any[]=[] // <= TSLint complains about missing whitespace
	> = T1 & T2;
```
**Related Issues:** none found

**Comment by AlCalzone** [comment]
Using another type as a default, only one whitespace is missing:
```ts
type Bar<T> = T;

type Foo<
	T1 extends any[],
	T2 extends any[] = Bar<T1>
> = T1 & T2;
```
becomes
```ts
type Bar<T> = T;

type Foo<
	T1 extends any[],
	T2 extends any[]= Bar<T1>
	> = T1 & T2;
```

**Comment by collin5** [comment]
I would love to pick this up. Any pointers to point me in the right direction? thanks!

**Comment by DanielRosenwasser** [comment]
Thanks @fuafa!
