### ISSUE TITLE
destructuring imports and camelcase variable name check

### ISSUE THREAD

**Issue by papakai** [Microsoft/TypeScript#26659]
```typescript
import { Record } from "./record";

//further code
```
now we transpile it to es2016 js code and have eslint validating the result.
it complains then about the generated variable name not being camelcase.

```
error  Identifier 'record_1' is not in camel case         camelcase
```

This enforces us to use the following workaround which makes typesscript coding a bit weird:

```typescript
import * as r from "./record";

//further code, where we have to use r.Record instead of simply record ...
```
I've also tried out

```typescript
import { Record as Record } from "./record";

//further code
```
But this did not change things.
Changing the eslint config doesn't make sense as we check for standard style.

our .eslintrc.js
```javascript
module.exports = {
    'env': {
        'mocha': true,
        'node': true
    },
    'extends': 'standard',
    'plugins': [
        'markdown',
        'json'
    ]
}
```

our .tsconfig.json
```json
{
    "compileOnSave": true,
    "compilerOptions": {
        "experimentalDecorators": true,
        "declaration": true,
        "module": "commonjs",
        "moduleResolution": "Node",
        "noFallthroughCasesInSwitch": true,
        "noImplicitReturns": true,
        "noUnusedLocals": true,
        "noUnusedParameters": true,
        "outDir": "./dist",
        "removeComments": true,
        "sourceMap": true,
        "strict": true,
        "target": "es2016",
        "typeRoots": ["./node_modules/@types/", "./typings/"]
    },
    "include": [
        "src/**/*.ts"
    ],
    "exclude": [
        "node_modules",
        "**/*.spec.ts",
        "coverage",
        ".nyc_output",
        "docs"
    ]
}
```

**Comment by MartinJohns** [comment]
Why not use something like ts-lint? It doesn't strike me as very useful to lint generated code.

**Comment by papakai** [comment]
tslint is for checking typescript code, not for es* code.
We lint the generated code into standard style - to remove unnecessary semicolons etc.

**Comment by nmain** [comment]
This seems difficult to fix.  Typescript would need a setting controlling generated identifier names, with as many different options as there are linters and coding standards.  Do other transpiling tools provide fine grained control over generated identifiers?

**Comment by RyanCavanaugh** [comment]
We can't possibly always emit code that conforms to any conceivable ESLint configuration, or reasonably provide the level of configurability that would be needed for you to express what the code would need to look like to match your config file. Linting generated code doesn't really make sense and isn't something we're going to design our emit story around.

**Comment by papakai** [comment]
But what about just considering javascript standard style? should be the industry standard imo.
For sure it does not make sense to consider every special setup, but at least the standard formatting.
