### ISSUE TITLE
`arguments` variable in arrow function in standard function

### ISSUE THREAD

**Issue by SaschaNaz** [Microsoft/TypeScript#2665]
```typescript
(function () { () => { arguments; } })
// Error: The 'arguments' object cannot be referenced in an arrow function. Consider using a standard function expression.
```

This currently gives error in master branch, but I think the `arguments` here should reference the variable in the outer "standard" function. What do you think?

**Comment by mhegazy** [comment]
For the complete discussion and background, please see #2430.

With #2430 fixed, arguments will reference the outer arguments to correctly align with ES6 semantics. It will still be an error however, as this will change the meaning of previously authored typescript code. We probably will relax this restriction in a release or two, just to make sure that there is no silent change in behavior when migrating to 1.5.

**Comment by SaschaNaz** [comment]
I didn't know that thread, thanks :D
