### ISSUE TITLE
Please stop skipping the method name

### ISSUE THREAD

**Issue by vdakalov** [Microsoft/TypeScript#26658]
Why you translate static and instance methods, defined as

```typescript
class Base {
  static foo() {}
  bar() {}
}
```
in to
```typescript
// ...
Base.foo = function () { };
Base.prototype.bar = function () { };
// ...
```
You loses information about function name. Please translate method with
```typescript
// ...
Base.foo = function foo() { };
Base.prototype.bar = function bar() { };
// ...
```

**Comment by RyanCavanaugh** [comment]
We do this as to not break your code, as the identifier `foo` inside the method body refers to a possible outer `foo`, not the function itself.

See #5611 for the runtime value of `.name`.
