### ISSUE TITLE
Valid listeners and options refused to be assigned to removeEventListener's EventListener and EventListenerOptions respectively with strict mode enabled

### ISSUE THREAD

**Issue by nodaguti** [Microsoft/TypeScript#26652]
**TypeScript Version:**  typescript@3.1.0-dev.20180823

**Search Terms:**
- removeEventListener

**Code**

```ts
function onTouchStart(e: TouchEvent): void {
    console.log(e.currentTarget);
}

function onTouchEnd(): void {
    console.log('touchend!');
}

const div = document.createElement('div');

div.addEventListener('touchstart', onTouchStart, { passive: false });
div.removeEventListener('touchstart', onTouchStart, { passive: false });

div.addEventListener('touchend', onTouchEnd, { passive: false });
div.removeEventListener('touchend', onTouchEnd, { passive: false });
```

**Expected behavior:**
No errors occur just like `addEventListener` calls in the code.

**Actual behavior:**
Two errors are emitted:

```
index.ts:12:39 - error TS2345: Argument of type '(e: TouchEvent) => void' is not assignable to parameter of type 'EventListenerOrEventListenerObject'.
  Type '(e: TouchEvent) => void' is not assignable to type 'EventListenerObject'.
    Property 'handleEvent' is missing in type '(e: TouchEvent) => void'.

12 div.removeEventListener('touchstart', onTouchStart, { passive: false });
                                         ~~~~~~~~~~~~

index.ts:15:51 - error TS2345: Argument of type '{ passive: boolean; }' is not assignable to parameter of type 'boolean | EventListenerOptions | undefined'.
  Object literal may only specify known properties, and 'passive' does not exist in type 'boolean | EventListenerOptions | undefined'.

15 div.removeEventListener('touchend', onTouchEnd, { passive: false });
                                                     ~~~~~~~~~~~~~~
```

**Playground Link:** 
https://www.typescriptlang.org/play/#src=function%20onTouchStart(e%3A%20TouchEvent)%3A%20void%20%7B%0A%20%20%20%20console.log(e.currentTarget)%3B%0A%7D%0A%0Afunction%20onTouchEnd()%3A%20void%20%7B%0A%20%20%20%20console.log('touchend!')%3B%0A%7D%0A%0Aconst%20div%20%3D%20document.createElement('div')%3B%0A%0Adiv.addEventListener('touchstart'%2C%20onTouchStart%2C%20%7B%20passive%3A%20false%20%7D)%3B%0Adiv.removeEventListener('touchstart'%2C%20onTouchStart%2C%20%7B%20passive%3A%20false%20%7D)%3B%0A%0Adiv.addEventListener('touchend'%2C%20onTouchEnd%2C%20%7B%20passive%3A%20false%20%7D)%3B%0Adiv.removeEventListener('touchend'%2C%20onTouchEnd%2C%20%7B%20passive%3A%20false%20%7D)%3B%0A

**Related Issues:** 
None.

**Comment by RyanCavanaugh** [comment]
#23204 regressed
