### ISSUE TITLE
Bad german translation for circular default type in generic type declaration

### ISSUE THREAD

**Issue by AlCalzone** [Microsoft/TypeScript#26657]
**TypeScript Version:**  3.1.0-dev.20180824

**Search Terms:** zirkulären standard

The german translation of the following error is unclear or incomplete.

**Code**

```ts
type Foo<T1, T2 = Foo<T1>> = T2;
                  ~~~~~~~
                  Error: Der Typparameter "T2" weist einen zirkulären Standard auf
```

**Expected behavior:**
Either
> Der Typparameter "T2" besitzt einen zirkulären Standard**typ** (default type)

or
> Der Typparameter "T2" besitzt einen zirkulären Standard**wert** (default value)

Also, "weist ... auf" does sound weird, so "besitzt" is probably better.

**Comment by DanielRosenwasser** [comment]
@PDostalek can you take a look?

**Comment by PDostalek** [comment]
Checking, thank you for pointing this out.

**Comment by lukaschal** [comment]
Fixed.

New TGT: Der Typparameter "{0}" besitzt einen zirkulären Standardwert.

**Comment by janbaltus** [comment]
@AlCalzone please close this issue.
