### ISSUE TITLE
Support folding multi-line brace-less arrow functions

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#26661]
_From @fabiospampinato on August 4, 2018 16:9_

- VSCode Version: 1.25.1
- OS Version: 10.13.5

Especially when working with React I often tend to write multi-line arrow functions without curly braces, but they can't be folded:

<img width="210" alt="screen shot 2018-08-04 at 18 09 29" src="https://user-images.githubusercontent.com/1812093/43678311-8e8c3c4c-9811-11e8-9046-2f199a4f6a69.png">

_Copied from original issue: Microsoft/vscode#55817_

**Comment by jpduckwo** [comment]
+1 
Anyone know a work around for this?

**Comment by pushkine** [comment]
>this simple request has been pending for almost 2 years now
>I really don't like being forced into a specific syntax to use basic text editor features

**Comment by orta** [comment]
There's an open WIP PR for this, you could offer some advice and maybe help out in that PR if you wanted to push this forwards? https://github.com/microsoft/TypeScript/pull/35874

**Comment by dragomirtitian** [comment]
@orta  This seems to work now in the latest version of typescript. This issue should be closed [Playground Link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDGMA0cDecDCE4EAdkifAL5wBmURcA5FKhowNwBQnANkvGiKQyFOAF44ACgCU4gHxTOcZXAA8AE2AA3OaoD0mnZ2nc+AoaXIwACiigoQAZ3GKVcMAC44KEgE9j8q4qGtq6BqHGXGbeXj6+ANoAulwoAHQgKGCSMvKSSioAjHAA1HAAzMbSKemZ2bJicnluRaUV0tKpNMA8MEhQdbn5yjBQAK5IlexAA)

**Comment by orta** [comment]
Concurred 👍🏻
