### ISSUE TITLE
Structure proposal to new kind of type (struct)

### ISSUE THREAD

**Issue by michaeljota** [Microsoft/TypeScript#26665]
## Search Terms

`struct` - `structure`

## Suggestion

I would like to make a proposal for a new type kind `struct`. Semantically they would represent a new type and would compile to a plain POJO, with all properties initialized by default. This would allow easy use of objects when what matters is that they all have a certain shape, wherever the properties have value or not, and a POJO is needed.

- `struct` would be used like a primitive constructor, and such Typescript would not allow it to be instantiated, anyway you probably would like to use a class in this case.
  - This would express the intention for a structure to return a plain Javascript object, as primitive constructors returns a primitive instance, although, I know a primitive instance is not the same a literal primitive. 

- `struct` would potentially allow only property declarations.
  - Even when POJOs can have methods members, functional programming disallow the mixing of properties and methods in the same object, as this is considered to be a OOP pattern. Also, for the latter we have classes, so we are currently cover for that use.

- `struct` would not allow a constructor declaration.
  - Because the struct will not be instantiated, there will no function to be called when calling the struct declaration.

- `struct` calls should allow only a object with an optional partial shape of the `struct` itself.
  - This will allow to call a `struct` declaration without arguments, or with a definition of the default properties. 

- `struct` would not allow `static` members.
  - As the `struct` itself is just a POJO, the is no reason to have static members here.

- If the compiler option `strictNullChecks` is `off`, the properties can be declared without a explicit value. If the option is `on`, then the properties should be declared with an explicit value, or should be explicit optional, or undefined.

- If the compiler option `noImplicitAny` is `off`, the properties can be declared without a explicit type. If the option is `on`, then the properties should either have a type or a value.

## Use Cases

- Common scenarios involve the use of a plain old Javascript object shape, including functional programming.  

- Reactive Forms of Angular: When using a Reactive Form, an object with all the properties initialized is required for the form for binding purposes. As today you can use a class instance.

- Store of ngrx (Angular): When setting the state of a store, you need a certain shape to be filled with default values. This objects needs to be a POJO.

- Probably more. If you have another use case, please comment and I will update this. 

## Examples

  - The `struct` itself would compile
    - from:
    ```ts
    struct Shape {
      a: string;
      b;
      c = true;
    } 
    ```
    - to:
    ```js
    var Shape = {
      a: void 0,
      b: void 0,
      c: true,
    }
    ```
  - The `struct` calls would compile: 
    - from:
    ```ts
    const shape = Shape();
    ```
    - to:
    ```js
    var shape = Object.assign({}, Shape); // shape = { a: void 0; b: void 0; c: true }
    ``` 

    - from: 
    ```ts
    const shape = Shape({ a: 'Hello World '});
    ```

    - to: 
    ```js
    var _shapeDefaultValue = { a: 'Hello World' };
    var shape = Object.assign({}, Shape, _shapeDefaultValue);  // shape = { a: 'Hello World'; b: void 0; c: true }
    ```

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

## FAQ: 

- Can the `struct` types be extended?
  - Yes and no. If you see the proposed spec, you would be allowed to extend a structure and in the compile code Typescript can use Object.assign to extend the value with a higher value, so yes. But I wouldn't like the `struct` types to be extended because is a OOP pattern to extends to another objects. 

## Additional Notes:

There was a proposal to a `struct` concept (#24007), but was marked as `Out of Scope` and with all reasons. I think this proposal of using the `struct` name as a type, would resemble more what you can expect a Typescript structure to be.

**Comment by nmain** [comment]
> This could be implemented without emitting different JS based on the types of the expressions

That doesn't seem to be true.  In your example for `const shape = Shape();`, you would get a different emit if `Shape` was a plain function.

**Comment by michaeljota** [comment]
@nmain You are right. I didn't notice it. Thanks! I don't really want to add complexity with this. I'll think about how to call the struct declaration in a way that the compiler doesn't have to evaluate if the call is a struct or a function (Because most of the type it would be a function anyway).

**Comment by RyanCavanaugh** [comment]
This is too close to a class and too close to a type to justify adding type-directed emit + a new top-level declaration kind + introduce possible future conflict with TC39 work. This proposal is better-suited to es-discuss since it's basically a runtime feature.

**Comment by RyanCavanaugh** [comment]
I don't think it'd clear the complexity bar over there either, it's just the domain where it belongs
