### ISSUE TITLE
Error message on use of async iterators in nodeJS 10 streams misleading

### ISSUE THREAD

**Issue by BurtHarris** [microsoft/TypeScript#26677]
**TypeScript Version:**  typescript@3.1.0-dev.20180825

**Search Terms:**  async iterator ES2018

**Code**

```ts
import { PassThrough } from "stream";  // with  @types/node@10.9.2
// Compiled with --target ES2018.

const stream = new PassThrough();
stream.write( Buffer.from([0,1,2,3]));

async function doIt( )  {
    var buf : Buffer;
    for await (  buf of stream ) {
        console.trace('>>>buf ',  buf);
    }
}

doIt();
```

**Expected behavior:**

No error message.   Fallback code generation or polyfill based `Symbol.asyncIterator`.

**Actual behavior:**

Message:  message index.ts:12:25 - error TS2519: An async iterator must have a 'next()' method. 

This error message is wrong, because the code generated (`__asyncValues`) depends on `[Symbol.asyncIterator]` rather than `next()` on the stream.

**Playground Link:**   Playground does not behave the same, it currently generates different code that actually does depend on a `next()` method, so [this link](https://www.typescriptlang.org/play/#src=import%20%7B%20PassThrough%20%7D%20from%20%22stream%22%3B%20%20%2F%2F%20with%20%20%40types%2Fnode%4010.9.2%0D%0A%0D%0Aconst%20stream%20%3D%20new%20PassThrough()%3B%0D%0Astream.write(%20Buffer.from(%5B0%2C1%2C2%2C3%5D))%3B%0D%0A%0D%0Aasync%20function%20doIt(%20)%20%20%7B%0D%0A%20%20%20%20var%20buf%20%3A%20Buffer%3B%0D%0A%20%20%20%20for%20await%20(%20%20buf%20of%20stream%20)%20%7B%0D%0A%20%20%20%20%20%20%20%20console.trace('%3E%3E%3Ebuf%20'%2C%20%20buf)%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0AdoIt()%3B%0D%0A%0D%0A
) is not particularly useful.    

**Related Issues:**  #20463, the fix here might make the message go away, just as using --target ESNEXT does, but I think that misses the point.   Shouldn't the --target option control the choice of generated language, and not what input syntax is permitted?   

This currently happens for If --target ES2015, ES2016, ES2017, or ES2018, but not ESNEXT.   If --target ES5, a different error is generated, requiring a `Promise` constructor.

I'm hoping we should be able to polyfill async iterators into any implementation support promises and symbols., 

**Note:** the of the @types/node@10.9.2 version of index.d.ts I'm using **does** declare that stream has a `[Symbol.asyncIterator]` method.    If it lacked that, then the message displayed might make sense, but as the generated code never even uses next() method, the message is still confusing..

**Comment by andy-ms** [comment]
It looks like `Stream.prototype[Symbol.asyncIterator]` returns a `AsyncIterableIterator` which is not defined under the default lib setting for `es2018`. Node provides a stub declaration, but that doesn't have `next()` in it. Using `--target es2018 --lib esnext` works, but if we support compiling to async iterators presumably we should have the interface available too.

**Comment by rbuckton** [comment]
This is analogous to defining a custom default lib and not filling in the type for `Promise` and getting errors for `await` not working.

We should be able to resolve this by changing the node definitions to use lib references once typesVersions support is rolled out to DefinitelyTyped.

**Comment by rbuckton** [comment]
This should be resolved now that the NodeJS definitions on DefinitelyTyped are using `"typesVersions"` and lib references.
