### ISSUE TITLE
fourslash-server tests can't handle negative tests

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#2667]
Try writing a getOccurrences test for a keyword in a syntactically invalid construct; for instance:

```TypeScript
switch (100) {
    /*1*/continue;
}
```

Try to verify that the occurrence count is 0.

Expected: Test passes.
Actual:
```
Error: Error No content available.                                                        
 at SessionClient.processResponse (C:\Users\[yournamecouldbehereforalowlowrate]\TypeScript\built\local\run.js:43266:27)
```

**Comment by CyrusNajmabadi** [comment]
We should not be testing in this manner anyways.  We should just send the message and validate the response.   That will make things much simpler and allow us to validate the entire message, not just some small pieces of it.

**Comment by mhegazy** [comment]
@DanielRosenwasser just fix it in your next change.
