### ISSUE TITLE
Argument of type '(event: C) => void' is not assignable to parameter of type '(event: B) => any'

### ISSUE THREAD

**Issue by bigbeno37** [Microsoft/TypeScript#26682]
**TypeScript Version:**  3.1.0-dev.20180825

**Search Terms:**
Argument of type is not assignable to parameter of type
Property is missing in type not assignable

**Code**

```ts
class A {
    foo(handler: (event: B) => any) {

    }
}

interface B {
    name: string;
    [index: string]: any;
}

class C implements B {
    name = "hello";
    name2 = "world";
}

class D extends A {
    constructor() {
        super();
        
        super.foo((event: C) => { });
    }
}
```

**Expected behavior:**
Compiles normally

**Actual behavior:**
Compiles normally under direct compilation, but under `tsc` compilation with a fresh `tsc --init` tsconfig file, the compilation fails with 
```
script.ts:21:19 - error TS2345: Argument of type '(event: C) => void' is not assignable to parameter of type '(event: B) => any'.
  Types of parameters 'event' and 'event' are incompatible.
    Type 'B' is not assignable to type 'C'.
      Property 'name2' is missing in type 'B'.
```

**Playground Link:** [Link here](https://www.typescriptlang.org/play/index.html#src=class%20A%20%7B%0D%0A%20%20%20%20foo(handler%3A%20(event%3A%20B)%20%3D%3E%20any)%20%7B%7D%0D%0A%7D%0D%0A%0D%0Ainterface%20B%20%7B%0D%0A%20%20%20%20name%3A%20string%3B%0D%0A%20%20%20%20%5Bindex%3A%20string%5D%3A%20any%3B%0D%0A%7D%0D%0A%0D%0Aclass%20C%20implements%20B%20%7B%0D%0A%20%20%20%20name%20%3D%20%22hello%22%3B%0D%0A%20%20%20%20name2%20%3D%20%22world%22%3B%0D%0A%7D%0D%0A%0D%0Aclass%20D%20extends%20A%20%7B%0D%0A%20%20%20%20constructor()%20%7B%0D%0A%20%20%20%20%20%20%20%20super()%3B%0D%0A%20%20%20%20%20%20%20%20%0D%0A%20%20%20%20%20%20%20%20super.foo((event%3A%20C)%20%3D%3E%20%7B%7D)%3B%0D%0A%20%20%20%20%7D%0D%0A%7D)

**Comment by MartinJohns** [comment]
When you compile with a fresh `tsc --init` config it has the `strict` mode enabled. When compiling directly without further specifying it it has the `strict` mode not enabled.

https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#strict-contravariance-for-callback-parameters

**Comment by bigbeno37** [comment]
Ah okay I see, I knew it'd be something relatively obscure like that
