### ISSUE TITLE
Monrepo with project references fails to compile

### ISSUE THREAD

**Issue by raymondfeng** [Microsoft/TypeScript#26689]
**TypeScript Version:**  3.0.1

**Search Terms:**

Project references

**Code**

https://github.com/raymondfeng/learn-a/

Please follow the README.md to reproduce the problem.
```sh
npm i
npm run build
```
**Expected behavior:**

The build should be successful.

**Actual behavior:**
```
npm run build

> @ build /Users/rfeng/Projects/demos/learn-a
> tsc -b packages

packages/pkg2/src/index.ts:1:21 - error TS2307: Cannot find module '@ryancavanaugh/pkg1'.

1 import * as p1 from '@ryancavanaugh/pkg1';
```

**Playground Link:** 

**Related Issues:**

**Comment by raymondfeng** [comment]
@RyanCavanaugh Any update?

**Comment by raymondfeng** [comment]
I did more experiment and this project layout works - https://github.com/raymondfeng/learn-a/tree/ts.

Please note that I use `ts` as the `rootDir` to contain `src` and `test` so that `dist` is NOT under `rootDir`. But the project layout is not so intuitive. 

I guess the issue is related to the fact that `outDir` ("dist") is under the `rootDir` (".") and `include/exclude` in `tsconfig.json` is not being honored in this case.

**Comment by ajafff** [comment]
@raymondfeng see discussion in #26867
Your issue is probably caused by `outDir` being located inside `rootDir`

**Comment by raymondfeng** [comment]
@ajafff It seems so but my project layout should be legitimate as it works well with normal (without -b) `tsc` compilation.

**Comment by bajtos** [comment]
Interesting. Maybe we can try to split each package into two sub-projects, one for `src` and another for `test`, as described in http://www.typescriptlang.org/docs/handbook/project-references.html#an-example-project?

**Comment by sheetalkamat** [comment]
@raymondfeng Is this still issue? I cloned your repo and built it and it works. 
Note in your repo, the `include` was inside `compilerOptions` which I moved out and it seems to work and build without any errors after that.

If this is still an issue, please provide more information

**Comment by raymondfeng** [comment]
@sheetalkamat I fixed the tsconfig and upgraded to TypeScript 3.1.1. Everything seems to be work fine now! Thanks a lot. I'll try with a much larger project at https://github.com/strongloop/loopback-next
