### ISSUE TITLE
Auto sort import conflicts with tslint

### ISSUE THREAD

**Issue by rrousselGit** [Microsoft/TypeScript#26685]
I've seen the related issue:
- https://github.com/Microsoft/TypeScript/issues/23366

and tested it on the current typescript next (3.1.0-dev.20180825). But the current fix seems to be incomplete.

**Code**

```ts
import { helloWorld, HELLO_WORLD } from 'foo';
```

**Expected behavior:**

Using "Organize imports", this should become

```ts
import { HELLO_WORLD, helloWorld } from 'foo';
```

due to the `_` in the naming. As this is the expected behavior of tslint `ordered-imports`

**Actual behavior:**

Imports are not reordered. 
Worse, if you have the code following code which fits tslint rules:

```ts
import {  HELLO_WORLD, helloWorld } from 'foo';
```

then "Organize imports" will revert it back

____

For now I added a ` // tslint:disable-next-line:ordered-imports` but this is not ideal.

**Comment by j-oliveras** [comment]
Duplicated of #25114?

**Comment by rrousselGit** [comment]
Oh, didn't see that one. Gotcha
