### ISSUE TITLE
_this is causing error

### ISSUE THREAD

**Issue by pranaydutta89** [Microsoft/TypeScript#2669]
i had added a new prototype to date function 

    interface Date {
         addDays(days:any):any;
     }

     Date.prototype.addDays = (days)=>{
         this.setDate(this.getDate() + days);
        return this;
     }

output generated in this gives me 

     var _this=this;
     Date.prototype.addDays = function (days) {
        _this.setDate(_this.getDate() + days);
         return _this;
     };

in here the "this" is window object,for which it get an error as getDate is undefined, however in "this" i want the instance of date

if i keep it like 

     Date.prototype.addDays = function(days){
        this.setDate(this.getDate() + days);
        return this;
     }

then output is 

     Date.prototype.addDays = function (days) {
        this.setDate(this.getDate() + days);
        return this;
    };

and everything is good

**Comment by CyrusNajmabadi** [comment]
This is the expected behavior for Arrow Functions (=>) versus Function Expressions.  Arrow functions capture the this value of the enclosing context, whereas Function Expressions have their own 'this' value.  For constructors it will be a new object, and for function calls it will be the context object.

**Comment by DanielRosenwasser** [comment]
For the record, the fix is just to change your code to

interface Date {
     addDays(days:any):any;
 }


 Date.prototype.addDays = function (days) {
     this.setDate(this.getDate() + days);
     return this;
 }
