### ISSUE TITLE
Allow Overload Implementaions with no Type Declarations

### ISSUE THREAD

**Issue by Tiedye** [Microsoft/TypeScript#26701]
## Search Terms

overload overlap

## Suggestion / Example

When overloading a function, there will often be times when you have multiple overloads with different lengths and types the union of which will (unfortunately) create a signature that is a strict super-set of the the previous signatures.  For example:

```ts
function f(a: number): void;
function f(a: string, b: string): void;
function f(a: string | number, b?: string) {
  // do something
}
```

This allows a call like `f(1, 'a')` to pass the type checker.  This has the side effect of making it so type-guards in the function implementation can't make super intelligent deductions, for example:

```ts
function f(a: number): void;
function f(a: string, b: string): void;
function f(a: string | number, b?: string) {
  if (typeof a === 'number') {
    // `a` is a string but `b` is still `string | undefined`
  }
}
```

It would be fantastic if we could do something like this:

```ts
function f(a: number): void;
function f(a: string, b: string): void;
function f(a, b) {
  if (typeof a === 'number') {
    // `a` is a string and `b` is thus `undefined`
  }
}
```

What would be happening here is the implementation would not be considered one of the overload signatures, so this would fix the earlier problem of the general signature allowing invalid argument combinations, and the typecheceker would be able to make better deductions about the types arguments.

To preserve compatibility with implicit any, if the feature was only available when `noImplicitAny` is enabled it would be completely backwards compatible as it would only kick in when there were no type arguments on an overloaded constructor/method/function (right now this is an error).

## Use Cases

There are ample examples of overloaded functions, this would allow the typechecker to better do its job when using.  As it is now there are often times when unnecessary type checks and assertions are required get it to behave correctly.

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by yortus** [comment]
Pretty sure it already works like that. [Here's](http://www.typescriptlang.org/play/index.html#src=function%20f(a%3A%20number)%3A%20void%3B%0D%0Afunction%20f(a%3A%20string%2C%20b%3A%20string)%3A%20void%3B%0D%0Afunction%20f(a%3A%20string%20%7C%20number%2C%20b%3F%3A%20string)%20%7B%0D%0A%20%20%2F%2F%20do%20something%0D%0A%7D%0D%0A%0D%0Af(1%2C%20'a')%3B%20%2F%2F%20ERROR%20'1'%20not%20assignable%20to%20'string'%0D%0A) your original example in the playground - note the `f(1, 'a')` call *does* error as you would like it to.

**Comment by Tiedye** [comment]
Yeah I thought it used to do it, must have got confused by it externally narrowing the signature correctly.

**Comment by RyanCavanaugh** [comment]
Disregarding initial confusion about the implementation signature being visible, seems like a duplicate of #22609 ?

**Comment by Tiedye** [comment]
Yeah it is, should have searched for overload narrowing.  Sorry
