### ISSUE TITLE
Wrong optionality of `expression` property of `ThrowStatement` interface 

### ISSUE THREAD

**Issue by vilchik-elena** [microsoft/TypeScript#26706]
**TypeScript Version:**  3.0.1

**Search Terms:** `ThrowStatement`

**Code**

```ts
import * as ts from "typescript";
let throwStatement: ts.ThrowStatement = {} as ts.ThrowStatement
foo(throwStatement.expression); // compilation error: Argument of type 'Expression | undefined' is not assignable to parameter of type 'Expression'. Type 'undefined' is not assignable to type 'Expression'.

function foo(node: ts.Expression) {
}
```

**Expected behavior:**
As throw statement without expression is not valid, I expect API for it to not have optional type for `expression` property

**Actual behavior:**
`throwStatement.expression` has optional type, I have to force its type (`throwStatement.expression!`) or have meaningless condition (`if (throwStatement.expression)...`) 

**Related Issues:** 
This optionality was introduced in this PR #22088

**Comment by j-oliveras** [comment]
It can be undefined if exists a line break after the throw. It is used to report an error inside the checker.
See the parse: https://github.com/Microsoft/TypeScript/blob/ac0d5da6313a6ee8965bf8dfff57aa00053d4532/src/compiler/parser.ts#L5033-L5040

**Comment by ajafff** [comment]
@j-oliveras in other places like missing `ElementAccessExpression.argumentExpression` the parser inserts a MissingNode (basically an Identifier without text) and reports an error if it encounters such a node in the AST

**Comment by ajafff** [comment]
@RyanCavanaugh is this really just a "Question"?
My comment above describes how it could be changed to align with other cases where an expression is missing. This would simplify the API for consumers.

**Comment by RyanCavanaugh** [comment]
I guess we'd take a PR to clean it up.
