### ISSUE TITLE
Extract inferred external Props from a React Component with defaultProps

### ISSUE THREAD

**Issue by rsolomon** [Microsoft/TypeScript#26704]
## Search Terms

ElementProps, ElementConfig, "component props with defaultProps"

## Suggestion

Now that TypeScript infers the external Props API for a Component with `defaultProps`, it would be helpful to add a type that returns the inferred props from a component. Flow accomplishes this with ["React.ElementConfig"](https://flow.org/en/docs/react/types/#toc-react-elementconfig).

## Use Cases

* Extending React components and re-using their prop types without re-writing them.

## Examples

```
class Test extends React.Component<{ foo: string, bar: number }> {
  static defaultProps = {
    foo: 'baz',
  }
  
  render() {
    ...
  }
}

type TestProps = React.ElementConfig<Test>; // { foo?: string, bar: number }
```

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by RyanCavanaugh** [comment]
Would be nice to put that in the React .d.ts file for consistency

**Comment by cheeZery** [comment]
```
class Test extends React.Component<{ foo: string, bar: number }> {
  static defaultProps = {
    bar: 'baz', <-- Error, Type 'string' is not assignable to type 'number'.
  }
  
  render() {
    ...
  }
}
```

So we don't have to declare ``defaultProps`` as ``Partial<{ foo: string, bar: number }>`` or something like that.

(Sorry, if this should be an issue on its own I will gladly create it)

**Comment by cheeZery** [comment]
Yeah, exactly, and that's the bug I would like TypeScript to detect :-) Sorry, that I didn't made that clear! At the moment you can set whatever key value pairs you want in ``defaultProps``. TypeScript should know that keys of the declared Props interface are allowed here. Or am I missing something why this shouldn't be the case?

**Comment by mattmccutchen** [comment]
@cheeZery Yes, please file a new issue as this is unrelated to the current issue.

**Comment by pronebird** [comment]
Is there any plan to add `JSX.LibraryManagedAttributes<typeof T, T["props"]>` into d.ts for React?

**Comment by JDMathew** [comment]
use `JSX.LibraryManagedAttributes<typeof MyComp, React.ComponentProps<typeof MyComp>>` for Functional components as MyComp["props"] only works for class based components
