### ISSUE TITLE
`import` in functions

### ISSUE THREAD

**Issue by streamich** [Microsoft/TypeScript#2670]
It looks like `import` is not allowed inside functions, like so:

```javascript
function my_function() {
    import MyClass = require("./MyClass");
}
```

One can do `var` instead:

```javascript
function my_function() {
    var MyClass = require("./MyClass");
}
```

It is useful for large apps to *lazy-load* modules as it runs, for faster start-up times. I was wondering why `import` is not allowed inside functions?

**Comment by mhegazy** [comment]
looks like the same as #2508
