### ISSUE TITLE
Curry function with labeled arguments 

### ISSUE THREAD

**Issue by freddi301** [Microsoft/TypeScript#26711]
## Suggestion

Always wanted a properly type-checked, intellisense-complete curried by argument's name function? 
Maybe this type definition can be helpful.

## Use Cases

Curry functions without need to respect the order of arguments

## Examples

[playground](https://www.typescriptlang.org/play/index.html#src=type%20Diff%3CT%2C%20S%20extends%20Partial%3CT%3E%3E%20%3D%20%7B%20%5BP%20in%20Exclude%3Ckeyof%20T%2C%20keyof%20S%3E%5D%3A%20T%5BP%5D%20%7D%3B%0D%0A%0D%0Atype%20CurryFunctionWithLabeledArguments%3C%0D%0A%20%20Arguments%2C%0D%0A%20%20Return%2C%0D%0A%20%20Bound%20extends%20Partial%3CArguments%3E%2C%0D%0A%20%20Missing%20%3D%20Diff%3CArguments%2C%20Bound%3E%0D%0A%3E%20%3D%20Bound%20extends%20Arguments%20%3F%20()%20%3D%3E%20Return%20%3A%20CurriedFunctionWithLabeledArguments%3CArguments%2C%20Return%2C%20Bound%2C%20Missing%3E%3B%0D%0A%0D%0Ainterface%20CurriedFunctionWithLabeledArguments%3CArguments%2C%20Return%2C%20Bound%2C%20Missing%3E%20%7B%0D%0A%20%20%3CAdded%20extends%20Partial%3CMissing%3E%3E(args%3A%20Added%20%26%20Partial%3CMissing%3E)%3A%20CurryFunctionWithLabeledArguments%3C%0D%0A%20%20%20%20Arguments%2C%0D%0A%20%20%20%20Return%2C%0D%0A%20%20%20%20Bound%20%26%20Added%0D%0A%20%20%3E%3B%0D%0A%7D%0D%0A%0D%0Aexport%20function%20curryFunctionWithLabeledArguments%3CArguments%2C%20Return%2C%20Bound%20%3D%20%7B%7D%3E(%0D%0A%20%20fun%3A%20(args%3A%20Arguments)%20%3D%3E%20Return%2C%0D%0A%20%20bound%3F%3A%20Bound%0D%0A)%3A%20CurryFunctionWithLabeledArguments%3CArguments%2C%20Return%2C%20Bound%3E%20%7B%0D%0A%20%20return%20((args%3A%20any)%20%3D%3E%0D%0A%20%20%20%20args%20%3F%20curryFunctionWithLabeledArguments(fun%2C%20%7B%20...(bound%20as%20any)%2C%20...args%20%7D)%20%3A%20fun(bound%20as%20any))%20as%20any%3B%0D%0A%7D%0D%0A%0D%0A%2F%2F%20example%0D%0A%0D%0Afunction%20abc(args%3A%20%7B%20a%3A%20string%3B%20b%3A%20number%3B%20c%3A%20boolean%20%7D)%20%7B%0D%0A%20%20return%20new%20Date()%3B%0D%0A%7D%0D%0A%0D%0Aconst%20f%20%3D%20curryFunctionWithLabeledArguments(abc)%3B%0D%0A%0D%0Aconst%20fab%20%3D%20f(%7B%20a%3A%20%22%22%2C%20b%3A%200%20%7D)%3B%0D%0Aconst%20fabc%20%3D%20fab(%7B%20c%3A%20true%20%7D)%3B%0D%0Aconst%20x%20%3D%20fabc()%3B)

```typescript
function abc(args: { a: string; b: number; c: boolean }) {
  return new Date();
}
const f = curryFunctionWithLabeledArguments(abc);
const fab = f({ a: "", b: 0 });
const fabc = fab({ c: true });
const x = fabc();
```

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by andy-ms** [comment]
```ts
type Rest<T, K> = Pick<T, Exclude<keyof T, K>>;

function curry<Args extends object, SomeArgs extends keyof Args, Res>(f: (args: Args) => Res, someArgs: Pick<Args, SomeArgs>): (restOfArgs: Rest<Args, SomeArgs>) => Res {
    return args2 => f({ ...(someArgs as object), ...(args2 as object) } as Args);
}

interface I { x: number, y: number }
function f({ x, y }: I): number { return x + y; }
const curried = curry(f, { x: 1 });
console.log(curried({ y: 2 }));
```

**Comment by freddi301** [comment]
What do you think of the implementation in the playground?

**Comment by andy-ms** [comment]
That works too!
