### ISSUE TITLE
Ability to skip elements in tuple type annotation

### ISSUE THREAD

**Issue by zhuravlikjb** [Microsoft/TypeScript#2671]
Want to write something like this:
```typescript
var [, a, b]: [, string, number] = [0, "a", 5];
```

instead of inserting 'any' manually to all the omitted positions.

**Comment by DanielRosenwasser** [comment]
If I took your example and later added `x` as in the following:

```TypeScript
var [x, a, b]: [, string, number] = [0, "a", 5];
```

What is the desired behavior?

**Comment by zhuravlikjb** [comment]
I suppose that x here should have type of right-hand-side[0], or 'any', if the right-hand-side is absent.

Exactly the same way as for ordinary type annotations, when they are omitted: 
`var x = 0` => x: number
`var x` => x: any

The same in the case of non-destructuring declarations:
```typescript
var x: [, string, number] = [0, "a", 5];     // x is [number, string, number]
var y: [, string, number];  // y is [any, string, number]
```

**Comment by RyanCavanaugh** [comment]
We had a question when discussing this issue -- what are the kinds of cases where the inferred type is "not correct" ? In other words, what's the value of writing these annotations vs letting them be inferred?

**Comment by RyanCavanaugh** [comment]
@zhuravlikjb any thoughts on the above question?

**Comment by zhuravlikjb** [comment]
Sorry for the delay with answer. This question is just about consistency: JavaScript allows empty items and elision in many syntax elements. If it's allowed for array literals, why not to allow it for type annotations? Nothing critical here if the existing behaviour will remain. Just a "why not" thing. :)

**Comment by RyanCavanaugh** [comment]
Doesn't seem to be a lot of desire for this in practice, plus it introduces new weird cases as Daniel pointed out.
