### ISSUE TITLE
Empty object is assignable to inferred generic type

### ISSUE THREAD

**Issue by renatomariscal** [Microsoft/TypeScript#26727]
**TypeScript Version:**  3.1.0-dev.20180828

**Search Terms:  generic types empty **

**Code**

```ts
interface Foo {
    foo: string;
}
function addToArray<T>(array: Array<T>, value: T): void { }

const a = new Array<Foo>();
addToArray(a, {});
```

**Expected behavior:**
The following error:
``` 
Argument of type '{ }' is not assignable to parameter of type 'Foo'.
  Property 'foo' is missing in type '{ }'.
```

**Actual behavior:**
No error

**Playground Link:** http://www.typescriptlang.org/play/#src=interface%20Foo%20%7B%0D%0A%20%20%20%20foo%3A%20string%3B%0D%0A%7D%0D%0Afunction%20addToArray%3CT%3E(array%3A%20Array%3CT%3E%2C%20value%3A%20T)%3A%20void%20%7B%20%7D%0D%0A%0D%0Aconst%20a%20%3D%20new%20Array%3CFoo%3E()%3B%0D%0AaddToArray(a%2C%20%7B%7D)%3B%0D%0A%0D%0A

**Related Issues:**

**Comment by AlCalzone** [comment]
This seems to be because TS infers the type from the 2nd arguments - I don't know the reason why. You can lower that argument's inference priority the following way:
```ts
type NoInfer<T> = T & {[K in keyof T]: T[K]};
function addToArray<T>(array: T[], value: NoInfer<T>): void { }
```
which gives you the expected error `Type {} is not assignable to Foo`

**Comment by ajafff** [comment]
Duplicate of #14829

**Comment by renatomariscal** [comment]
I see, I expected originally to error even if it infers the 2nd, expecting that `Array<Foo>` wouldn't be assignable to `Array<{}>`.

I found it easier to enforce the requirement I need through:
```ts
function addToArray<T,K extends T>(array: Array<T>, value: K): void { }
```

Thanks, should I close this?

**Comment by renatomariscal** [comment]
Closing as this is a duplicate.
