### ISSUE TITLE
Adding a string index signature to `string` triggers a comparison depth error when using a reverse mapped type

### ISSUE THREAD

**Issue by weswigham** [microsoft/TypeScript#26725]
**TypeScript Version:**  3.1.0-dev.201xxxxx

**Search Terms:**

**Code**

```ts
interface String {
    [index: string]: string;
}
declare let a: {x: string};
type Deep<T> = { [K in keyof T]: Deep<T[K]> }
declare function foo<T>(deep: Deep<T>): T;
const out = foo(a);
const q1 = out.a;
```

**Expected behavior:**
No errors.

**Actual behavior:**
Circularity errors on some combination of `declare let a` and `Deep` and an assignability error on the call to `foo`. Materially, the `string` indexer shouldn't make us blow up, just like how we don't blow up on the numeric indexer that already exists.

**Comment by jakebailey** [comment]
I'm looking at old bugs for ones that turned out to be fixed; this one appears to have been fixed in 4.3 and no longer triggers a depth error.
