### ISSUE TITLE
Reverse mapped types do not preserve numeric index signatures

### ISSUE THREAD

**Issue by weswigham** [microsoft/TypeScript#26724]
**TypeScript Version:**  3.1.0-dev.201xxxxx

**Search Terms:**

**Code**
With `strict` on:
```ts
interface A { [x: number]: A }
declare let a: A;
type Deep<T> = { [K in keyof T]: Deep<T[K]> }
declare function foo<T>(deep: Deep<T>): T;
const out = foo(a);
const q1 = out[0];
const q2 = out[0][0];
const q3 = out[0][1][0][2];
```

**Expected behavior:**
No errors.

**Actual behavior:**
Implicit any error on each `out[0]` as `out` has no numeric index signature.

**Comment by laughinghan** [comment]
`out` seems to be inferred to `unknown`, which I think is fine, this amount of recursion sounds hard to infer. This seems like it can be closed.
