### ISSUE TITLE
As arguments to a function, constrained generic function types with a generic return type behave oddly.

### ISSUE THREAD

**Issue by coltmeister** [Microsoft/TypeScript#26735]
**TypeScript Version:**  3.1.0-dev.201xxxxx

**Search Terms:**
generic argument constraint function generic return type

**Code**

```ts
const Function1 = <R, F extends (...args: any[]) => R>(f: F): R => {
    return f()
}

const Function2 = <F extends (...args: any[]) => any>(f: F): ReturnType<F> => {
    return f()
}

const Function3 = () => 5

const Example1 = Function1(Function3) // typeof Example1 === {}
const Example2 = Function2(Function3) // typeof Example2 === number
```

**Expected behavior:**
typeof Example1 === number

**Actual behavior:**
typeof Example1 === {}

I am fairly new to TypeScript, so perhaps I am missing some crucial information on the correct usage of  generics.

[**Playground Link**](http://www.typescriptlang.org/play/#src=const%20Function1%20%3D%20%3CR%2C%20F%20extends%20(...args%3A%20any%5B%5D)%20%3D%3E%20R%3E(f%3A%20F)%3A%20R%20%3D%3E%20%7B%0D%0A%20%20%20%20return%20f()%0D%0A%7D%0D%0A%0D%0Aconst%20Function2%20%3D%20%3CF%20extends%20(...args%3A%20any%5B%5D)%20%3D%3E%20any%3E(f%3A%20F)%3A%20ReturnType%3CF%3E%20%3D%3E%20%7B%0D%0A%20%20%20%20return%20f()%0D%0A%7D%0D%0A%0D%0Aconst%20Function3%20%3D%20()%20%3D%3E%205%0D%0A%0D%0Aconst%20Example1%20%3D%20Function1(Function3)%20%2F%2F%20typeof%20Example1%20%3D%3D%3D%20%7B%7D%0D%0Aconst%20Example2%20%3D%20Function2(Function3)%20%2F%2F%20typeof%20Example2%20%3D%3D%3D%20number)

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
Constraints aren't inference sites for other type parameters.

As an aside, what you should probably write is
```ts
const Function4 = <R>(f: (...args: any[]) => R): R => {
    return f()
}
```

**Comment by coltmeister** [comment]
Ahhh, okay. Thank you for the quick response. Where could I find more information regarding this topic?
