### ISSUE TITLE
Extend external modules not work

### ISSUE THREAD

**Issue by weijarz** [microsoft/TypeScript#26732]
# package @my/koaExt
* @my/koaExt is a package  extends an existing interface in package 'koa'
## FILE: index.ts
```ts
import * as koa from 'koa'

declare module 'koa' {
  interface Context { // extends koa.Context interface
    myvar: string
  }
}

declare global {
  function foo (): void
}
```

# package myapp
`myapp` package depends on package `@my/koaExt`

## FILE tsconfig.json

```json
...
    "typeRoots": [
      "./node_modules/@types",
      "./node_modules/@my"
    ],
...
```

## FILE index.ts
```ts
import { Context } from 'koa'

foo() // works

function f (ctx: Context) {
  ctx.accept
  ctx.myvar // error
}
```

**Expected behavior:**

I would expect `@my/koaExt` can extend an external module `koa`.

**Comment by andy-ms** [comment]
There is a probably an error with the way the module is included. This is working for me with `index.ts` moved to `src` and imported explicitly with `import {} from "./index";`, so the project consists of only the two files -- could you try that?

**Comment by weijarz** [comment]
@andy-ms Thank you for the reply. 
I tried move index.ts to src, but it not work.
I created a repo at https://github.com/weijarz/typescript-module-merge-bug

**Comment by RyanCavanaugh** [comment]
Seems like our module augmentation code might not account for the case where there's no non-augmenting declaration?

**Comment by andy-ms** [comment]
The following test passes:
```ts
// @moduleResolution: node

// @Filename: /app/node_modules/koaExt/index.d.ts
export {};
declare module 'koa' {
    export const ext = 0;
}

// @Filename: /app/node_modules/koa/index.d.ts
export const own = 0;

// @Filename: /app/src/a.ts
import { own, ext } from 'koa'
import {} from "koaExt"
```


The following test fails:
```ts
// @moduleResolution: node

// @Filename: /koaExt/node_modules/koa/index.d.ts
export const own = 0;

// @Filename: /koaExt/node_modules/koa/package.json
{ "name": "koa", "version": "1.2.3" }

// @Filename: /koaExt/index.d.ts
// @symlink: /app/node_modules/koaExt/index.d.ts
export {};
declare module 'koa' {
    export const ext = 0;
}

// @Filename: /app/node_modules/koa/index.d.ts
export const own = 0;

// @Filename: /app/node_modules/koa/package.json
{ "name": "koa", "version": "1.2.3" }

// @Filename: /app/src/a.ts
import { own, ext } from 'koa'
import {} from "koaExt"
```

Note that we don't treat things intended to be augmentations as errors even when they have nothing to augment -- they just become ambient declarations.

**Comment by weijarz** [comment]
I found it works when move koaExt into myapp dir:  https://github.com/weijarz/typescript-module-merge-bug/tree/subdir

**Comment by RyanCavanaugh** [comment]
This is either fixed, was working as intended the whole time, or has affected ~zero other situations.
