### ISSUE TITLE
Unable to infer types when not passing an optional generic

### ISSUE THREAD

**Issue by patrick91** [microsoft/TypeScript#26734]
**TypeScript Version:**  3.0.1
**Search Terms:**

**Code**

Not sure if this is correct, but I feel like TS should be able to infer the correct types even not passing the generic type directly

```ts
type Example<T extends { [K in keyof T]: { prop: any } }> = {
  [K in keyof T]: T[K]['prop']
};

const Ex = <T extends { [K in keyof T]: { prop: any } }>(
  example: Example<T>
) => example;


const x = Ex({ a: 123 });

x.a; // type this should be number but it is any
```

**Expected behavior:**

typeof x.a should be number

**Actual behavior:**

typeof x.a is any

**Playground Link:** http://www.typescriptlang.org/play/#src=type%20Example%3CT%20extends%20%7B%20%5BK%20in%20keyof%20T%5D%3A%20%7B%20prop%3A%20any%20%7D%20%7D%3E%20%3D%20%7B%0D%0A%20%20%5BK%20in%20keyof%20T%5D%3A%20T%5BK%5D%5B'prop'%5D%0D%0A%7D%3B%0D%0A%0D%0Aconst%20Ex%20%3D%20%3CT%20extends%20%7B%20%5BK%20in%20keyof%20T%5D%3A%20%7B%20prop%3A%20any%20%7D%20%7D%3E(%0D%0A%20%20example%3A%20Example%3CT%3E%0D%0A)%20%3D%3E%20example%3B%0D%0A%0D%0A%0D%0Aconst%20x%20%3D%20Ex(%7B%20a%3A%20123%20%7D)%3B%0D%0A%0D%0Ax.a%3B%20%2F%2F%20type%20this%20should%20be%20number%20but%20it%20is%20any%0D%0A%0D%0Aconst%20y%20%3D%20Ex%20%3C%7Ba%20%3A%20%7B%20prop%3A%20number%20%7D%7D%3E(%7B%20a%3A%20123%20%7D)%3B%0D%0A%0D%0Ay.a%3B

**Related Issues:** #23647

**Comment by RyanCavanaugh** [comment]
There are easier ways to write this that don't create inference problems. What's the intended behavior of `Ex` ?

**Comment by patrick91** [comment]
That's the smallest reproduction I was able to make, the use case is a bit more complex, I have a FormFactory that returns a React component that can be used like this:


```jsx
const Form = FormFactory({ name: { initialValue: 'Patrick' } });

<Form onSubmit={(values) => { console.log(values) }}>
  {(fields, submit) => { ... }}
</Form>
```

The idea is that values is typed based on the field definition passed to the FormFactory, but right now I have the issue described in the first message here.

I can post the whole form if needed, but it is a bit messy :)

**Comment by RyanCavanaugh** [comment]
This result isn't wrong (it's correctly constrained to the bounds) and I don't think it's possible to do better with finite inference passes.
