### ISSUE TITLE
Possible regression: default parameter referencing other parameter

### ISSUE THREAD

**Issue by jods4** [Microsoft/TypeScript#26744]
**TypeScript Version:**  3.1.0-dev.20180829 (today's @next)

**Search Terms:** default parameter

**Code**

```ts
function observe<T extends object>(
  target: T, 
  properties: string[] = Object.getOwnPropertyNames(target)) {
}
```

**Expected behavior:**
Previously compiled fine

**Actual behavior:**
Produces TS2304, _Cannot find name `target`_ inside the `getOwnPropertyNames` call.

**Playground Link:** 
https://www.typescriptlang.org/play/index.html#src=function%20observe%3CT%20extends%20object%3E(target%3A%20T%2C%20properties%3A%20string%5B%5D%20%3D%20Object.getOwnPropertyNames(target))%20%7B%0D%0A%20%20%20%20%0D%0A%7D
Playground seems fine, not sure which version it is.

**Related Issues:**
Didn't find any

**Comment by ajafff** [comment]
Duplicate of #26731

**Comment by jods4** [comment]
Indeed, sorry I didn't find it because it doesn't contain the word "default" :(
