### ISSUE TITLE
TSX property autocomplete shouldn't wrap consecutive boolean attributes in braces

### ISSUE THREAD

**Issue by TedDriggs** [Microsoft/TypeScript#26745]
**TypeScript Version:**  3.0.1, typescript@3.1.0-dev.20180829

**Search Terms:** JSX attributes, boolean, braces

This is a minor variation on #23099.

**Code**

```ts
<CSSTransition
    appear
    //<-- cursor here, attempt to type and complete "enter"
/>
```

**Expected behavior:** The boolean property `enter` is inserted

**Actual behavior:** The literal `{enter}` is inserted. This is syntactically invalid. Note that this only occurs if the preceding property is a shorthand boolean, as in the example above. Writing `appear={true}` will cause this to no longer occur.

**Playground Link:** 

**Related Issues:** #23099 is almost identical to this.

**Comment by andy-ms** [comment]
Duplicate of #26937
