### ISSUE TITLE
Infer Interfaces from types

### ISSUE THREAD

**Issue by renatomariscal** [Microsoft/TypeScript#26757]
## Search Terms

infer interfaces types automatic generate mock

## Suggestion

Infer interfaces from public members of types.
`<TypeName>.Interface` would be understood as an interface which requires all public members of **TypeName** to be implemented.

## Use Cases

The majority of interfaces I have in my projects are for testing purpose, to allow mocking out related modules. Any signature change needs to happen always in 3 places (interface, real implementation and mock) what is bothersome.

That would remove the need of writing explicitly this kind of interface.

## Examples

```ts
// Given a type:
class Foo {
     public foo(): string {
        return "I am foo";
    }
}

// This would be a mock implementation:
class MockFoo1 implements Foo.Interface {
     public foo(): string {
        return "mockresult";
    }
}

// This would complain of missing foo function:
class MockFoo2 implements Foo.Interface {
     public bar(): string {
        return "I am foo";
    }
}

// Happy Assignments:
const foo: Foo.interface = new Foo();
const mockFoo1: Foo.interface = new MockFoo1();
```

## Checklist

My suggestion meets these guidelines:
* [X] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by RyanCavanaugh** [comment]
You can already write
```ts
class MockFoo1 implements Foo {
```
and get the behavior you've described. No new syntax needed

**Comment by renatomariscal** [comment]
This is awesome, is that mentioned somewhere in the documentation?

**Comment by renatomariscal** [comment]
Closing as the feature already exists.
