### ISSUE TITLE
Is Typescript V3.0.3 actually legit?

### ISSUE THREAD

**Issue by fabsenet** [microsoft/TypeScript#26768]
npm outdated listed me a version 3.0.3 today but this repo only has a release 3.0.1 and also only a tag for 3.0.1. Is the npm release actually legit? what was changed? is it safe?

**Comment by j-oliveras** [comment]
I think is legit, see #26605.

**Comment by AlCalzone** [comment]
The tag shows 3.0.3 for me - but I'm sure I also saw 3.0.1 earlier. Maybe a cache problem for the badge?

**Comment by RyanCavanaugh** [comment]
Sorry for the confusion; Mohamed used to do releases so we're still figuring out the checklist. 3.0.3 is indeed a real thing.

**Comment by fabsenet** [comment]
okay, 99,6% of me were sure the whole time, but I aked anyway. Just imagine the possible damage if someone would upload a somehow malicious newer version of typescript to npm. frightening!
