### ISSUE TITLE
rebuild failed if update tsconfig

### ISSUE THREAD

**Issue by Kingwl** [microsoft/TypeScript#26761]
**TypeScript Version:**  3.1.0-dev.201xxxxx

**Search Terms:**
jake, rebuild

1. after update https://github.com/Microsoft/TypeScript/pull/23801, i add a new file `src/compiler/transformers/taggedTemplate.ts` and add path into tsconfig.json
2. jake runtests
3. 
![image](https://user-images.githubusercontent.com/6831019/44825384-f4ceaa00-ac3c-11e8-88e3-b240489e1a1e.png)

4. rm -rf built
5. jake runtests
6. ok

**Expected behavior:**

**Actual behavior:**

**Playground Link:** 

**Related Issues:**

**Comment by jakebailey** [comment]
Closing this one; doesn't happen anymore (and we use wildcards in tsconfig post-modules, woo)
