### ISSUE TITLE
Labels should not get type 'any' for their quick info 

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#2677]
We falsely report a label having type `any`.

![image](https://cloud.githubusercontent.com/assets/972891/7058438/b348c478-de16-11e4-95d3-dfa08fdd97e9.png)

**Comment by GuillaumeSalles** [comment]
I tried to fix it in pr #2731

**Comment by CyrusNajmabadi** [comment]
Notes:

1. Labels should have symbols just like anything else.  (This also matches Roslyn).
2. Labels should get quick info.  They should just get *meaningful* quick info.  Things like goto-def, find-references should work on them (ideally without any specialized code.  it should just fall out from them being normal symbols.

**Comment by DanielRosenwasser** [comment]
What kind of meaningful quick-info did you have in mind?

**Comment by CyrusNajmabadi** [comment]
A preview of the statement its relevant to.  C# has something similar when you hover over a closing brace.  it's quite useful.

**Comment by mhegazy** [comment]
Fixed in #2731. Thanks @GuillaumeSalles
