### ISSUE TITLE
Generic inference fails when parameter is supertype of union

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/TypeScript#26773]
**TypeScript Version:**  3.0.1

**Search Terms:** nested supertype union generic inference

**Code**

```ts
enum Types {
    Loading = 'Loading',
    Failure = 'Failure',
    Success = 'Success',
}

type Loading = { type: Types.Loading };

type Failure<E> = {
    type: Types.Failure;
    value: E;
};

type Success<A> = {
    type: Types.Success;
    value: A;
};

type Loaded<E, A> = Failure<E> | Success<A>;
type RemoteData<E, A> = Loading | Loaded<E, A>;

type MyResponse = { foo: number };
type MyFailure = string;
declare const loaded: Loaded<MyFailure, MyResponse>;
declare const remoteData: RemoteData<MyFailure, MyResponse>;

declare const checkIsSuccess: <E, A>(remoteData: RemoteData<E, A>) => boolean;

checkIsSuccess(remoteData);
checkIsSuccess(remoteData);

// Inferred generics are `string, string`, expected `string, MyResponse`
// Type 'MyResponse' is not assignable to type 'string'.
checkIsSuccess(loaded);
// Workaround: specify generics explicitly
checkIsSuccess<MyFailure, MyResponse>(loaded);
```

**Expected behavior:**

**Actual behavior:**

**Playground Link:** https://www.typescriptlang.org/play/index.html#src=enum%20Types%20%7B%0D%0A%20%20%20%20Loading%20%3D%20'Loading'%2C%0D%0A%20%20%20%20Failure%20%3D%20'Failure'%2C%0D%0A%20%20%20%20Success%20%3D%20'Success'%2C%0D%0A%7D%0D%0A%0D%0Atype%20Loading%20%3D%20%7B%20type%3A%20Types.Loading%20%7D%3B%0D%0A%0D%0Atype%20Failure%3CE%3E%20%3D%20%7B%0D%0A%20%20%20%20type%3A%20Types.Failure%3B%0D%0A%20%20%20%20value%3A%20E%3B%0D%0A%7D%3B%0D%0A%0D%0Atype%20Success%3CA%3E%20%3D%20%7B%0D%0A%20%20%20%20type%3A%20Types.Success%3B%0D%0A%20%20%20%20value%3A%20A%3B%0D%0A%7D%3B%0D%0A%0D%0Atype%20Loaded%3CE%2C%20A%3E%20%3D%20Failure%3CE%3E%20%7C%20Success%3CA%3E%3B%0D%0Atype%20RemoteData%3CE%2C%20A%3E%20%3D%20Loading%20%7C%20Loaded%3CE%2C%20A%3E%3B%0D%0A%0D%0Atype%20MyResponse%20%3D%20%7B%20foo%3A%20number%20%7D%3B%0D%0Atype%20MyFailure%20%3D%20string%3B%0D%0Adeclare%20const%20loaded%3A%20Loaded%3CMyFailure%2C%20MyResponse%3E%3B%0D%0Adeclare%20const%20remoteData%3A%20RemoteData%3CMyFailure%2C%20MyResponse%3E%3B%0D%0A%0D%0Adeclare%20const%20checkIsSuccess%3A%20%3CE%2C%20A%3E(remoteData%3A%20RemoteData%3CE%2C%20A%3E)%20%3D%3E%20boolean%3B%0D%0A%0D%0AcheckIsSuccess(remoteData)%3B%0D%0AcheckIsSuccess(remoteData)%3B%0D%0A%0D%0A%2F%2F%20Inferred%20generics%20are%20%60string%2C%20string%60%2C%20expected%20%60string%2C%20MyResponse%60%0D%0A%2F%2F%20Type%20'MyResponse'%20is%20not%20assignable%20to%20type%20'string'.%0D%0AcheckIsSuccess(loaded)%3B%0D%0A%2F%2F%20Workaround%3A%20specify%20generics%20explicitly%0D%0AcheckIsSuccess%3CMyFailure%2C%20MyResponse%3E(loaded)%3B%0D%0A

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
Alias-expanding and culling the example for clarity:
```ts
type Failure<E> = {
    type: "fail";
    value: E;
};

type Success<A> = {
    type: "pass";
    value: A;
};

declare const loaded: Failure<string> | Success<{ foo: number }>;
declare const checkIsSuccess: <E, A>(remoteData: Failure<E> | Success<A>) => boolean;

checkIsSuccess(loaded);
```

**Comment by RyanCavanaugh** [comment]
And here's the version that works:
```ts
type Failure<E> = {
    type: "fail";
    errorMessage: E; // 🌟
};

type Success<A> = {
    type: "pass";
    value: A;
};

declare const loaded: Failure<string> | Success<{ foo: number }>;
declare const checkIsSuccess: <E, A>(remoteData: Failure<E> | Success<A>) => boolean;

checkIsSuccess(loaded);
```

**Comment by RyanCavanaugh** [comment]
I think the root cause here is that we're collecting inference candidates even when a discriminating property from the containing type tells us it can't happen.

**Comment by Andarist** [comment]
This works as expected in all available TS versions in the playground, the issue can be closed
