### ISSUE TITLE
Rest arguments type inference not working for generic constructor functions

### ISSUE THREAD

**Issue by prmph** [Microsoft/TypeScript#26783]
**TypeScript Version:** 3.0.1

**Search Terms:** generics function arguments inference union constructor

**Code**

```ts
type ArgsType<F extends (...x: any[]) => any> 
= F extends (...x: infer A) => any ? A : never;

type CtorArgsType<F extends new (...x: any[]) => any> 
= F extends new (...x: infer A) => any ? A : never;

interface RepoGroup { resetAsync?: () => Promise<void> }

interface RepoGroupOptions<Reset extends "CanReset" | "CannotReset" = "CannotReset"> {
    reset: Reset extends "CanReset" ? () => Promise<void> : undefined
}

type RepoGroupCtor<Reset extends "CanReset" | "CannotReset" = "CannotReset">
    = new (...args: any[]) => RepoGroupOptions<Reset>


export function generate<
    CanReset extends "CanReset" | "CannotReset" = "CannotReset",
    T extends RepoGroupCtor<CanReset> = RepoGroupCtor<CanReset>
    >(args: T) {
    return class implements RepoGroup {
        private args: InstanceType<T>
        constructor(...config: CtorArgsType<T>) {
            this.args = new args(config) as any
        }

        resetAsync = this.args.reset
    }
}


export const Repo = generate<"CannotReset">(class {
    readonly baseUrl: string
    constructor(args: { apiBaseUrl: string }) {
        this.baseUrl = args.apiBaseUrl
    }

    reset: undefined
})

let repository = new Repo()


```

**Expected behavior:**
Compiler error _"Expected 1 arguments, but got 0."_ on the last line

**Actual behavior:**
No error is reported for this code

**Additional Comments**
If I add just a generic parameter to the Repo class argument thus:
`export const Repo = generate<"CannotReset">(class {...`

then the error appears, at it should

**Comment by mattmccutchen** [comment]
Working as intended as explained at https://stackoverflow.com/a/52101463: `T` takes the default of `RepoGroupCtor<CanReset>`, which accepts `...args: any[]`.

**Comment by prmph** [comment]
The failure is in this snippet:

```ts
type RepoGroupCtor<Reset extends "CanReset" | "CannotReset" = "CannotReset">
    = new (...args: any[]) => RepoGroupOptions<Reset>
```

Are you are saying that just because the _Reset_ type parameter is set to its default, then `CtorArgsType<new (...args: any[]) => RepoGroupOptions<"CannotReset">>` must fail?

**Comment by mattmccutchen** [comment]
Because you are passing at least one type argument to `generate`, inference is shut off for the remaining type arguments and they take their defaults.  So on the call to `generate`, `T` is set to its default, `RepoGroupCtor<CanReset>` (which is `RepoGroupCtor<"CannotReset">`).  When we expand `CtorArgsType<T> = CtorArgsType<new (...args: any[]) => RepoGroupOptions<"CannotReset">>`, we successfully extract the `any[]`.  Hence the constructor of the generated class will accept a call with rest arguments that are compatible with `any[]`, i.e., any number of arguments regardless of their types.
