### ISSUE TITLE
Error: TS1055: Type 'Promise' is not a valid async function return type in ES5/ES3 because it does not refer to a Promise-compatible constructor value.

### ISSUE THREAD

**Issue by hackhat** [microsoft/TypeScript#26781]
I already read this https://github.com/Microsoft/TypeScript/issues/12776#issuecomment-265885846 but is not possible to fix. Or I can't understand how has even been solved.

Is fixed by adding `const AsyncBool = Promise;` but is not possible in my case scenario. Also where can I read about this strange syntax. A type and a const with the same name?! Looks strange and confusing.

```ts

async function foo(): Promise<boolean> {
    return Promise.resolve(true);
}

type AsyncBool = Promise<boolean>;
const AsyncBool = Promise;
async function bar(): AsyncBool {
    return Promise.resolve(true);
}

```

**Code**

```ts
interface O {
  o: Promise<number>,
}

const myFn = async ():O["o"] => {
  
}
```

**Expected behavior:**

No error.

**Actual behavior:**

Error: TS1055: Type 'Promise<number>' is not a valid async function return type in ES5/ES3 because it does not refer to a Promise-compatible constructor value.

**Playground Link:** 

http://www.typescriptlang.org/play/#src=interface%20O%20%7B%0D%0A%20%20o%3A%20Promise%3Cnumber%3E%2C%0D%0A%7D%0D%0A%0D%0Aconst%20myFn%20%3D%20async%20()%3AO%5B%22o%22%5D%20%3D%3E%20%7B%0D%0A%20%20%0D%0A%7D

(by the way don't search "ts playground" on google. TS team needs to invest in some SEO I guess.)

**Related Issues:** https://github.com/Microsoft/TypeScript/issues/12776

**Comment by benneq** [comment]
I'm having the same issue with `axios`' `AxiosPromise` typing (see: https://github.com/axios/axios/blob/master/index.d.ts#L87 )

I'm getting:
```
Type 'AxiosPromise' is not a valid async function return type in ES5/ES3 because it does not refer to a Promise-compatible constructor value. ts(1055)
```

As you can see in the provided link, it's just:
```
export interface AxiosPromise<T = any> extends Promise<AxiosResponse<T>> {}
```

**Comment by timocov** [comment]
The same with built-in `ReturnType` helper:

```ts
async function fooBar(): Promise<void> {

}

async function barBaz(): ReturnType<typeof fooBar> { // Type 'ReturnType' is not a valid async function return type in ES5/ES3 because it does not refer to a Promise-compatible constructor value.

}
```

https://www.typescriptlang.org/play/index.html#src=async%20function%20fooBar()%3A%20Promise%3Cvoid%3E%20%7B%0D%0A%0D%0A%7D%0D%0A%0D%0Aasync%20function%20barBaz()%3A%20ReturnType%3Ctypeof%20fooBar%3E%20%7B%0D%0A%0D%0A%7D

**Comment by timocov** [comment]
@RyanCavanaugh why the compiler can't looking deep at the return type to understand that it's an "alias" to Promise-like type? Or this isn't a big deal and users can just change the return type to explicit Promise-like type? For me (in case of using `ReturnType` or any other type alias/mapped type/etc) it looks like a bug.

**Comment by mivanovaxway** [comment]
@typescript-bot @timocov @hackhat 
Indeed I am hitting the same issue and it's really annoying. 
How do we go about reopening this?
Also are there any workarounds?

In my opinion this is definitely a bug.

**Comment by timocov** [comment]
@RyanCavanaugh ping

**Comment by Bessonov** [comment]
Same issue:

```ts
export async function groupCreate(context: Context): Promise<Output> {
```
```ts
async (ctx): ReturnType<typeof groupCreate> => {
```

**Comment by yibuyisheng** [comment]
Same issue.

**Comment by likun7981** [comment]
Same issue

**Comment by pocketcolin** [comment]
Yep same issue!

**Comment by timocov** [comment]
@RyanCavanaugh can you please affirm that you will not fix it and consider to change that behavior (at least at the moment)?

**Comment by Maxim-Mazurok** [comment]
Same issue with `GaxiosPromise`:
```ts
export declare type GaxiosPromise<T = any> = Promise<GaxiosResponse<T>>;
```

```ts
submitAction = async (action: SubmitAction): GaxiosPromise<sheets_v4.Schema$BatchUpdateSpreadsheetResponse> => { ... }
```

```
Error: TS1055: Type 'GaxiosPromise' is not a valid async function return type in ES5/ES3 because it does not refer to a Promise-compatible constructor value.
```

**Comment by risenforces** [comment]
Same issue:

```ts
/* types */

export interface ModalResultPayload {
  action: ModalUserAction
  params: ModalUserParams
}

export type ModalResultPromise = Promise<ModalResultPayload>
```

```ts
/* error location */

export async function callModal(renderFunction: ModalFC): ModalResultPromise { ... }
```

**Comment by onichandame** [comment]
Same here

```typescript
const AsyncFunc = (): Promise<void> => Promise.resolve()
const ReturnAsyncFunc = (): ReturnType<typeof AsyncFunc> => AsyncFunc()
```

reports error 1055

**Comment by moeinrahimi** [comment]
help!

**Comment by sabrehagen** [comment]
halp!

**Comment by mivanovaxway** [comment]
Who should we tag to reopen this, I found only one name?

Hello, @RyanCavanaugh, this is not a question, but clearly a bug that needs fixing. If it's not a duplicate, please change the issue type and re-open.

Regards

**Comment by michal-kurz** [comment]
Same issue

**Comment by 5argon** [comment]
Same issue

**Comment by samratshaw** [comment]
Any updates on this?

**Comment by rangel-rangelov** [comment]
Same issue

**Comment by fhodun** [comment]
saSame issue

**Comment by RaphaelMechali** [comment]
Same issue

**Comment by mfearn-gala** [comment]
Same issue.

**Comment by JonathanPicques** [comment]
Still happening in TS 4.2.3

**Comment by carreylife** [comment]
"target": "esnext",

**Comment by quick007** [comment]
The same problem - how is this still an issue after more than 2 years?

**Comment by bielb2** [comment]
Hey guys =D.

This works for me: 

` Global.d.ts
  type GenericResponse<T> = Promise<T | { status: HttpErrorStatus; message: string }>;
  const GenericResponse = Promise;
  `

And i found here: https://pretagteam.com/question/error-ts1055-type-boolean-is-not-a-valid-async-function-return-type-in-es5es3-in-ionic-4

**Comment by rbideau** [comment]
I had the same error with a type aliasing Promise: `type CustomResponse<T> = Promise<T>`

My target in tsconfig.json was `es5` and upgrading it to `es6` fixed the error

**Comment by foreground-voice** [comment]
> was `es5` and upgrading it to `es6` fixed the error

But I need `es5`. I just made function return `as any`

**Comment by haixiangyan** [comment]
Don't use `"target": "es5"` in `tsconfig.json`, use something like `esnext` should work!

**Comment by dalmo3** [comment]
With arrow functions it might work by moving the type declaration to the `const` object.

```typescript
//doesn't work on target: ES5
const b = async () : Promise<any> => 3

//works for any target
const a : () => Promise<any> = async () => 3```

**Comment by tibic** [comment]
` Its return type 'Promise<Element>' is not a valid JSX element.`
After reading the above answers, I still have this mistake, I am going crazy

**Comment by nullromo** [comment]
For me, this issue arose with a conditional type. I changed
```typescript
const foo = <T extends boolean>(): T extends true ? Promise<string[]> : Promise<string[][]> => {
    //...
}
```
to
```typescript
const foo = <T extends boolean>(): Promise<T extends true ? string[] : string[][]> =>{
    // ...
}
```
In other words, wrapping the whole conditional in a promise worked when splitting the promises inside the conditional didn't.

**Comment by desfero** [comment]
Still happening in the context of monorepo when dependencies are linked to source files using `preconstruct`.

**Comment by haneenmahd** [comment]
Wrap the type or interface with the Promise type. It would be something like this:
```
type MyType = {...};

async function getData(): Promise<MyType> {...}
```

**Comment by Zack-Bee** [comment]
Did this issue have been resolved?  Why is it closed?

**Comment by RyanCavanaugh** [comment]
The return type must be `Promise<something>`. This is the intentional behavior.
