### ISSUE TITLE
No error when using 'allowJs' with 'composite'

### ISSUE THREAD

**Issue by ajafff** [Microsoft/TypeScript#26786]
**TypeScript Version:**  3.1.0-dev.20180830

**Search Terms:**

**Code**

tsconfig.json
```json
{
  "compilerOptions": {
    "composite": true,
    "allowJs": true
  }
}
```

**Expected behavior:**

Same error as `"declaration": true, "allowJs": true` because `declaration` is implicitly enabled by `composite` and project references rely on declaration emit.

This also needs a note in the Project References Handbook chapter about `allowJs` currently not being supported.

**Actual behavior:**

No error.

**Comment by a-tarasyuk** [comment]
@sheetalkamat Sorry, I didn't notice that you were assigned on this issue. I can close my PR if you are responsible on this issue.

**Comment by ajafff** [comment]
@a-tarasyuk that's probably fine as the assignee can then simply review your PR instead of fixing the issue themselves.

**Comment by a-tarasyuk** [comment]
@sheetalkamat thanks!
