### ISSUE TITLE
Type parameter explicitly constrained by `unknown` should not be assignable to `{}`

### ISSUE THREAD

**Issue by mattmccutchen** [microsoft/TypeScript#26796]
**TypeScript Version:**  master (2deb318)

**Search Terms:** conditional type variable parameter undefined null empty object constraint

**Code**
```ts
// With --strictNullChecks
type Test1 = [unknown] extends [{}] ? true : false;  // false
type IsDefinitelyDefined<T extends unknown> = [T] extends [{}] ? true : false;
type Test2 = IsDefinitelyDefined<unknown>;  // true, should be false

function oops<T extends unknown>(arg: T): {} {
    return arg;  // no error, should be an error (unknown not assignable to {})
}
console.log(oops(null).constructor);  // bang!
```

**Expected behavior** / **Actual behavior:** as marked

**Playground Link:** [link](https://www.typescriptlang.org/play/#src=type%20Test1%20%3D%20%5Bunknown%5D%20extends%20%5B%7B%7D%5D%20%3F%20true%20%3A%20false%3B%20%20%2F%2F%20false%0D%0Atype%20IsDefinitelyDefined%3CT%20extends%20unknown%3E%20%3D%20%5BT%5D%20extends%20%5B%7B%7D%5D%20%3F%20true%20%3A%20false%3B%0D%0Atype%20Test2%20%3D%20IsDefinitelyDefined%3Cunknown%3E%3B%20%20%2F%2F%20true%2C%20should%20be%20false) (remember to enable `strictNullChecks`)

**Related Issues:** didn't find any

Discovered via https://stackoverflow.com/questions/52105268 .

**Comment by ahejlsberg** [comment]
In the early days before `--strictNullChecks`, the `{}` type was our top type. With `--strictNullChecks` we carved out `null` and `undefined` and effectively our top type then became `{} | null | undefined`. However, for reasons of backward compatibility we kept `{}` as the default inference for an unconstrained type parameter and we kept the rule that allows an unconstrained type parameter to be assigned to `{}`.

We now have a property top type called `unknown` and if it wasn't for backward compatibility we'd switch from `{}` to `unknown` in the situations above. However, it would be a significant breaking change.

**Comment by mattmccutchen** [comment]
I would happily take the breaking change (under a new strict flag) for the soundness; in fact, I assumed it had come as part of `--strictNullChecks` until I discovered this issue.  If you don't want to do that, we could at least make a type parameter explicitly constrained by `unknown` not assignable to `{}`; nobody should be relying on that behavior.  If we do that and then people use a lint rule to require every type parameter in their code to have a constraint (either `unknown`, `{}`, or something else), then we'll be in pretty good shape; the standard library may still have legacy unconstrained type parameters, but it seems unlikely to me that any of them will expose the buggy behavior.  Shall I write the PR for the assignability change?

**Comment by RyanCavanaugh** [comment]
Per notes in #26954, committed to trying it, at least

**Comment by ahejlsberg** [comment]
The original issue here is actually not controversial. A type parameter with an _explicit_ constraint of `unknown` shouldn't be assignable to `{}`. We should just fix that.

The larger issue is whether it is possible for us to switch the default constraint for type parameters to `unknown` as we discussed in #26954. We should run that experiment and discuss.

**Comment by NN---** [comment]
So, is it planned for next release ?
