### ISSUE TITLE
Decorator documentation bug

### ISSUE THREAD

**Issue by jloveridge** [Microsoft/TypeScript#26799]
**TypeScript Version:**  3.1.0-dev.20180830

**Search Terms:** decorators

**Code**

```ts
import "reflect-metadata";

class Point {
    x: number;
    y: number;
}

class Line {
    private _p0: Point;
    private _p1: Point;

    @validate
    set p0(value: Point) { this._p0 = value; }
    get p0() { return this._p0; }

    @validate
    set p1(value: Point) { this._p1 = value; }
    get p1() { return this._p1; }
}

function validate<T>(target: any, propertyKey: string, descriptor: TypedPropertyDescriptor<T>) {
    let set = descriptor.set;
    descriptor.set = function (value: T) {
        let type = Reflect.getMetadata("design:type", target, propertyKey);
        if (!(value instanceof type)) {
            throw new TypeError("Invalid type.");
        }
        set(value);
    }
}

const line = new Line();
line.p0 = new Point();
```

**Expected behavior:** Expected the code example to work properly.

**Actual behavior:** Receive a TypeError: `TypeError: Cannot set property '_p0' of undefined`

**Code Correction**

```ts
// This version actually works as `this` will not be undefined when calling the `set` function.
function validate<T>(target: any, propertyKey: string, descriptor: TypedPropertyDescriptor<T>) {
    let set = descriptor.set;
    descriptor.set = function (value: T) {
        let type = Reflect.getMetadata("design:type", target, propertyKey);
        if (!(value instanceof type)) {
            throw new TypeError("Invalid type.");
        }
        set.call(target, value);
    }
}
```

**Comment by RyanCavanaugh** [comment]
The sample is from https://www.typescriptlang.org/docs/handbook/decorators.html

**Comment by VerteDinde** [comment]
Hey @RyanCavanaugh, I'd love to put this fix in, if it's no trouble.

**Comment by rbuckton** [comment]
Shouldn't it be `set.call(this, value)`?

**Comment by RobertoMalatesta** [comment]
@rbuckton you're correct.
just starting having a look at decorators and the code below is correct, with strict checking on:

`
import "reflect-metadata";

class Point {
    x: number = 0;
    y: number = 0;

    constructor() {
        this.x = 0;
        this.y = 0;
    }
}

class Line {
    private _p0: Point = new Point();
    private _p1: Point = new Point();

    @validate
    set p0(value: Point) { this._p0 = value; }
    get p0() { return this._p0; }

    @validate
    set p1(value: Point) { this._p1 = value; }
    get p1() { return this._p1; }
}

function validate<T>(target: any, propertyKey: string, descriptor: TypedPropertyDescriptor<T>) {
    let set = descriptor.set;
    descriptor.set = function (value: T) {
        let type = Reflect.getMetadata("design:type", target, propertyKey);
        if (!(value instanceof type)) {
            throw new TypeError("Invalid type.");
        }
        if (set)
            set.call(this, value);
        else {
            console.log("validate<T>:set is undefined on target:T")
            
        }
    }
}


let l = new Line();
l.p0 = new Point();
l.p1.x = 2
l.p1.y = 4

console.log(JSON.stringify(l));
` 

--R
