### ISSUE TITLE
Unable to infer the inner type within expansion of a nested union

### ISSUE THREAD

**Issue by pelotom** [microsoft/TypeScript#26807]
**TypeScript Version:**  3.0.1, 3.0.3, 3.1.0-dev.20180831

**Search Terms:** infer nested union type

**Code**

```ts
type Maybe<A> = { tag: 'none' } | { tag: 'some'; value: A };
type MaybeMaybeNumber =
  | { tag: 'none' }
  | {
      tag: 'some';
      value: { tag: 'none' } | { tag: 'some'; value: number };
    };
type X = Maybe<Maybe<number>> extends Maybe<Maybe<infer T>> ? T : never;
type Y = MaybeMaybeNumber extends Maybe<Maybe<infer T>> ? T : never;
```

**Expected behavior:**

The types `X` and `Y` should both be `number`, because `MaybeMaybeNumber` is just an expansion of `Maybe<Maybe<number>>`.

**Actual behavior:**

`X` is `number`, but `Y` is `{}`.

[**Playground Link**](http://www.typescriptlang.org/play/#src=type%20Maybe%3CA%3E%20%3D%20%7B%20tag%3A%20'none'%20%7D%20%7C%20%7B%20tag%3A%20'some'%3B%20value%3A%20A%20%7D%3B%0Atype%20MaybeMaybeNumber%20%3D%0A%20%20%7C%20%7B%20tag%3A%20'none'%20%7D%0A%20%20%7C%20%7B%0A%20%20%20%20%20%20tag%3A%20'some'%3B%0A%20%20%20%20%20%20value%3A%20%7B%20tag%3A%20'none'%20%7D%20%7C%20%7B%20tag%3A%20'some'%3B%20value%3A%20number%20%7D%3B%0A%20%20%20%20%7D%3B%0Atype%20X%20%3D%20Maybe%3CMaybe%3Cnumber%3E%3E%20extends%20Maybe%3CMaybe%3Cinfer%20T%3E%3E%20%3F%20T%20%3A%20never%3B%0Atype%20Y%20%3D%20MaybeMaybeNumber%20extends%20Maybe%3CMaybe%3Cinfer%20T%3E%3E%20%3F%20T%20%3A%20never%3B%0A)

**Comment by ahejlsberg** [comment]
This is a design limitation of our inference algorithm. Specifically, if, during inference, we are already processing another target type with the same associated symbol (such as an instantiation of the same generic type), we do not explore the nested target as it rarely yields further inferences, but definitely generates lots of work. Obviously that's not a good strategy here.

**Comment by pelotom** [comment]
I see. Any chance of the design being revisited? 🙂

**Comment by sledorze** [comment]
@ahejlsberg is there any way to force that exploration somehow? (forcing being enforced by library authors at definition site)

**Comment by safareli** [comment]
I've checked and starting from Typescript@4.1.5 this is fixed  [see playground link](
https://www.typescriptlang.org/play?ts=4.1.5#code/C4TwDgpgBAsghiARhAPAQQHxQLxQN5TBwDmAXFAOQB2A9lRBVAL5QA++hJ5FAzjQLYMA3FABucADYBXCOTTMhAWABQoSLATJ4SCADkp-ZACccKqGw5EylWvUZMzFvI-Pmr3PoIpLlr1+OlZSy4bOgZmJ05rXgFhMUkZcioDYwUXNNVwaAANHA0dFG1kFGTDCCMMLAgAD2AIKgATHnziotQASyoAM3KoABVKqAB+fqgkiFFynzVoAE08trb9MpMausbmtsLNDu7egawRvrGoekmjISA)

/cc @pelotom

**Comment by vaaas** [comment]
Since this is fixed, this issue shouldn't be open, no?

**Comment by RyanCavanaugh** [comment]
Yep!
