### ISSUE TITLE
Redundant argument names and interface key names in type definitions 

### ISSUE THREAD

**Issue by anurbol** [Microsoft/TypeScript#26805]
## Search Terms

Redundant argument names, redundant object key names, type definitions 

### Redundant argument names in function type defintions
```ts
type = (s: string) => any
```
In the above code, `s: ` is a noise, that doesn't do anything. 
The suggestion is to allow to omit argument names in function type definitions.

### Redundant object key names:
This comment says it all: https://github.com/Microsoft/TypeScript/issues/7803#issuecomment-298872994
The suggestion is to allow to omit object key names in signature definitions.

**Comment by RyanCavanaugh** [comment]
See #3693
