### ISSUE TITLE
Generic parameter types are incorrectly inferred as { }

### ISSUE THREAD

**Issue by CC2A** [Microsoft/TypeScript#26809]
**TypeScript Version:**  3.0.1, vscode 1.26.1

**Search Terms:**

**Code**

```ts
interface A<R> {
    a(): R
}

function some1<R>(a: A<R>): R {
    return null
}

function some2<R, D extends A<R>>(a: D): R {
    return null
}

let out1 = some1({
    a() {
        return 'asd'
    }
})

let out2 = some2({
    a() {
        return 'asd'
    }
})
```

**Expected behavior:** out1: `string`, out2: `string`

**Actual behavior:** out1: `string`, out2: `{}`

[**Playground Link**](http://www.typescriptlang.org/play/index.html#src=interface%20A%3CR%3E%20%7B%0D%0A%20%20%20%20a()%3A%20R%0D%0A%7D%0D%0A%0D%0Afunction%20some1%3CR%3E(a%3A%20A%3CR%3E)%3A%20R%20%7B%0D%0A%20%20%20%20return%20null%0D%0A%7D%0D%0A%0D%0Afunction%20some2%3CR%2C%20D%20extends%20A%3CR%3E%3E(a%3A%20D)%3A%20R%20%7B%0D%0A%20%20%20%20return%20null%0D%0A%7D%0D%0A%0D%0Alet%20out1%20%3D%20some1(%7B%0D%0A%20%20%20%20a()%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20'asd'%0D%0A%20%20%20%20%7D%0D%0A%7D)%0D%0A%0D%0Alet%20out2%20%3D%20some2(%7B%0D%0A%20%20%20%20a()%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20'asd'%0D%0A%20%20%20%20%7D%0D%0A%7D)) 

**Related Issues:**  
[https://github.com/Microsoft/TypeScript/issues/26807](https://github.com/Microsoft/TypeScript/issues/26807)

**Comment by AlCalzone** [comment]
Seems there is not enough context for TS to infer `R` in `some2`, since you are not passing any argument with type `R`. You can fix this by explicitly telling TypeScript to infer `R` from the interface:
```ts
interface A<R> {
    a(): R
}

declare function some2<D extends A<any>>(a: D): D extends A<infer R> ? R : any;

let out2 = some2({
    a() {
        return 'asd'
    }
})
// out2 is string!
```

**Comment by CC2A** [comment]
But why would it be `{}` instead of an error

**Comment by AlCalzone** [comment]
As far as I understand, `{}` is the default when inference fails. This keeps the type-checking enabled - as opposed to `any`, which doesn't.
