### ISSUE TITLE
No error on assignment to non-nullable variable with strictNullChecks turned on.

### ISSUE THREAD

**Issue by sccolbert** [Microsoft/TypeScript#26818]
**TypeScript Version:**  2.9 and 3.x

**Search Terms:**
strictNullChecks, no error, undefined

**Code**

```ts
function thing<T extends boolean | string | number>(v: T): T {
  var c: T | undefined = v;
  var d: T = c; // This should not be allowed under strictNullChecks
  return d;
}
```

**Expected behavior:**
The assignment to `d` should be an error since `c` may be `undefined`.

**Actual behavior:**
The compiler removes the `| undefined` from `c` at the point of assignment to `d`.

**Playground Link:** 
https://www.typescriptlang.org/play/index.html#src=function%20thing%3CT%20extends%20boolean%20%7C%20string%20%7C%20number%3E(v%3A%20T)%3A%20T%20%7B%0D%0A%20%20var%20c%3A%20T%20%7C%20undefined%20%3D%20v%3B%0D%0A%20%20var%20d%3A%20T%20%3D%20c%3B%20%2F%2F%20This%20should%20not%20be%20allowed%20under%20strictNullChecks%0D%0A%20%20return%20d%3B%0D%0A%7D

**Comment by j-oliveras** [comment]
The compiler knows that `v` is of type `T`, so it can not be `undefined`. If you change the `c` assign to `Math.random() < 0.5 ? v : undefined;` then errors as you expect.

Full sample ([playground](https://www.typescriptlang.org/play/index.html#src=function%20thing%3CT%20extends%20boolean%20%7C%20string%20%7C%20number%3E(v%3A%20T)%3A%20T%20%7B%0D%0A%20%20var%20c%3A%20T%20%7C%20undefined%20%3D%20v%3B%0D%0A%20%20var%20d%3A%20T%20%3D%20c%3B%20%2F%2F%20This%20should%20not%20be%20allowed%20under%20strictNullChecks%0D%0A%0D%0A%20%20var%20a%3A%20T%20%7C%20undefined%20%3D%20Math.random()%20%3C%200.5%20%3F%20v%20%3A%20undefined%3B%0D%0A%20%20var%20b%3A%20T%20%3D%20a%3B%0D%0A%0D%0A%20%20return%20d%3B%0D%0A%7D)):

```ts
function thing<T extends boolean | string | number>(v: T): T {
  var c: T | undefined = v;
  var d: T = c; // This should not be allowed under strictNullChecks

  var a: T | undefined = Math.random() < 0.5 ? v : undefined;
  var b: T = a;

  return d;
}
```

Error at `b`:
```
Type 'T | undefined' is not assignable to type 'T'.
  Type 'undefined' is not assignable to type 'T'.
```

**Comment by sccolbert** [comment]
So, this was a simplified example of a more complicated problem which exhibited the same behavior. I'll post the full situation.

**Comment by sccolbert** [comment]
Here's a more complicated example which demonstrates the same behavior, but where the compiler can't infer that `undefined` is not present.

```typescript
interface IIterator<T> {
  next(): T | undefined;
}

function map<T, U>(it: IIterator<T>, fn: (value: T) => U): IIterator<U> {
  throw ''; // the implementation is unimportant
}

type Primitive = number | string | boolean;

interface IItem<T extends Primitive> {
  value: T | undefined;
}

function unbox<T extends Primitive>(items: IIterator<IItem<T>>): IIterator<T> {
  let it = map(items, item => item.value); // VSCode shows this type to be IIterator<T | undefined>;
  return it; // This is allowed, but IIterator<T> should not be assignable to IIterator<T | undefined>
}
```

**Comment by RyanCavanaugh** [comment]
The proper thing would be to add a constraint: `IIterator<T extends object | Primitive> {`
