### ISSUE TITLE
Possible error on 'Destructuring' feature

### ISSUE THREAD

**Issue by cabralRodrigo** [Microsoft/TypeScript#2681]
I was trying the new features of 1.5 and i think I found an error:

```
var test = () => { 
    return {
        event: 'click',
        x: 15,
        y: 36,
        canceled: false
    };
};

var {event} = test();
```

`error TS2403: Subsequent variable declarations must have the same type.  Variable 'event' must be of type 'MSEventObj', but here has type 'string'.`

I think this code wouldn't raise an error.

I'm using version 1.5.0-alpha.

Thanks :)

**Comment by DanielRosenwasser** [comment]
Basically you're clashing with a variable that's already been declared as:

```TypeScript
declare var event: MSEventObj;
```

This has to do with the global `event` object defined in `lib.d.ts`. It's one of the old IE extensions to the `window` object.

**Comment by cabralRodrigo** [comment]
@DanielRosenwasser My Bad. Thanks :)

**Comment by DanielRosenwasser** [comment]
No worries! Glad you're trying out the alpha. We're always on the look out for bugs, so definitely keep an eye out.
