### ISSUE TITLE
No way to exclude specific types when they conflict.

### ISSUE THREAD

**Issue by burtonator** [microsoft/TypeScript#26821]
If two projects have conflicting type declarations there's no way to get them to play nicely.

jquery and webdriverio both declare * and they conflict.

I can *include* only specific types but I can't exclude individual broken types.  

I don't think there's a way to solve this. I hope I'm wrong!

I have a project setup to demonstrate this:

https://github.com/burtonator/broken-ts-test

**TypeScript Version:**  3.0.3

**Expected behavior:**

should compile

**Actual behavior:**

**Playground Link:** 

https://github.com/burtonator/broken-ts-test

**Comment by GongT** [comment]
I think only you can do is copy out jquery's `index.d.ts` and remove declare $ from it...

**Comment by RyanCavanaugh** [comment]
If two things both claim to declare `$` then they can't both be loaded at the same time. If there's some other behavior going on at runtime, then the type definitions should be structured differently
