### ISSUE TITLE
end of file error

### ISSUE THREAD

**Issue by sandeepkalra** [Microsoft/TypeScript#2683]
on Mac : TS6029: Version 1.4.1.0

I have a .ts file. If I leave the last line of file  with comments using /* */ style (e.g. /* END OF FILE */), the whole output is written twice in .js resulting in wrong production. If I leave comments using // (e.g. // END OF FILE), then it works fine. 

Hope this helps. 
Thanks.

**Comment by mhegazy** [comment]
This has been fixed in master. see #1714
