### ISSUE TITLE
Promise of promise type is somehow possible

### ISSUE THREAD

**Issue by KSXGitHub** [Microsoft/TypeScript#26839]
**TypeScript Version:**  3.0.0

**Search Terms:**

**Code**

```ts
async function fn<X>(x: X) {
    return await x
}

const foo = fn(123) // Promise<number>
const bar = fn(foo) // Promise<Promise<number>>
const baz = fn(Promise.resolve('abc')) // Promise<Promise<string>>
```

**Expected behavior:**

`bar` and `baz` should be `Promise<number>` and `Promise<string>` respectively.

**Actual behavior:**

They are `Promise<Promise<number>>` and `Promise<Promise<string>>`

**Playground Link:** [link](https://www.typescriptlang.org/play/#src=async%20function%20fn%3CX%3E(x%3A%20X)%20%7B%0D%0A%20%20%20%20return%20await%20x%0D%0A%7D%0D%0A%0D%0Aconst%20foo%20%3D%20fn(123)%20%2F%2F%20Promise%3Cnumber%3E%0D%0Aconst%20bar%20%3D%20fn(foo)%20%2F%2F%20Promise%3CPromise%3Cnumber%3E%3E%0D%0Aconst%20baz%20%3D%20fn(Promise.resolve('abc'))%20%2F%2F%20Promise%3CPromise%3Cstring%3E%3E%0D%0A)

**Related Issues:**

**Comment by j-oliveras** [comment]
Simplified workaround:
```ts
async function fn<X>(x: PromiseLike<X> | X) {
    return await x
}

const foo = fn(123) // Promise<number>
const bar = fn(foo) // Promise<number>
const baz = fn(Promise.resolve('abc')) // Promise<string>
```

[Playground](https://www.typescriptlang.org/play/#src=async%20function%20fn%3CX%3E(x%3A%20PromiseLike%3CX%3E%20%7C%20X)%20%7B%0D%0A%20%20%20%20return%20await%20x%0D%0A%7D%0D%0A%0D%0Aconst%20foo%20%3D%20fn(123)%20%2F%2F%20Promise%3Cnumber%3E%0D%0Aconst%20bar%20%3D%20fn(foo)%20%2F%2F%20Promise%3Cnumber%3E%0D%0Aconst%20baz%20%3D%20fn(Promise.resolve('abc'))%20%2F%2F%20Promise%3Cstring%3E%0D%0A).

**Comment by DanielRosenwasser** [comment]
I just triaged #27711 so forwarding to that.
