### ISSUE TITLE
Built-in decorators for DI containers

### ISSUE THREAD

**Issue by babakks** [Microsoft/TypeScript#26840]
## Search Terms

dependency injection, DI container, built-in decorators

## Suggestion

Adding (automatically added) built-in decorator(s) that hold type information. 

## Use Cases

As I know, dependency injection containers (DICs) in TypeScript work with their own decorators to be placed at the injection site (or even inject-able classes). This makes switching from one DIC to another an undesired task that involves replacing old decorators with the new ones. Actually, having classes to know 
about the DIC being used breaks the least-knowledge principle. There is, unfortunately, no choice for DICs other that that, because any type information is removed during TS/JS transpilation.

As a solution, I suggest introducing built-in decorators that decorate classes with their constructor parameter types information. Therefore, DIC containers would have no problem to indentify argument types at runtime, and hence, no special decorator needs to be defined. More than that, if the built-in decorators were automatically added during transpilation (set with an option in `tsconfig.json`), then there'd be no need to explicitly add the decorators to any potential injection site, which makes implementations unaware of the outside world coupling mechanics. 

I know when it comes to types, TypeScript development team wants to keep transpiled JS files simple but the lack of type information restricts the clean usage of DICs, and further maintenance decisions.

## Examples

Having such a decorator, type resolving would be quite straightforward. For example, consider the interface and classes below:

```ts
export interface Foo {
    bar(): void;
}

export class NullFoo implements Foo {
    bar(): void {
    }
}

export class Dependent {
    constructor(public foo: Foo) {
    }
}
```

Now, in the composition root, registrations would be as simple as this:
```ts
container.registerInstance<Foo>(new NullFoo());
container.registerType<Dependent>();
```
And, to resolve:
```ts
const dependent = container.resolve<Dependent>();
```
There is no sign of manually added decorators to make types known to the container. But, under the hood, the defintions above are transpiled like this:
```js
@type("NullFoo")
export class NullFoo {
    bar(): void {
    }
}

@type("Dependent")
@arg("Foo")
export class Dependent {
    constructor(foo) {
        this.foo = foo;
    }
}
```
## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by andy-ms** [comment]
TypeScript already has the ability to add constructor parameter metadata to a class. See the [handbook](https://www.typescriptlang.org/docs/handbook/decorators.html) on decorators.

```ts
function decorateClass<T extends Function>(target: T): T {
    console.log(Reflect.getMetadata("design:paramtypes", target));
    return target;
}

@decorateClass
class Point {
    constructor(readonly x: number, readonly y: number) {}
}
```

But yes, it does have to be explicitly asked for -- if we did this by default on every class it would change the runtime behavior of existing JavaScript code and greatly increase code sizes.

**Comment by andy-ms** [comment]
It sounds like you're asking for some value (a new decorator) to be added to the global scope by default. That would definitely be out-of-scope.
