### ISSUE TITLE
typeguards for JSX elements/components

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#26849]
I have this component:
```ts
   class If extends React.Component<{ it: boolean; }> {
        render() {
             return this.props.it ? <>{this.props.children}<> : null;
        }
   }
```
here is how i use it:
```ts
   <If it={shouldBeRendered}>
       <div>Here I am</div>
   </If>
```

unfortunately i cannot do the following, because the results of narrowing do not get imposed on the underlying context
```ts
    <If it={data !== null}>
         <MyComponent {...data}> // <-- data can still be `null`, doesn't typecheck
    </If>
```

suggestion: propagate the results of  type narrowing though the JSX markup

**Comment by mattmccutchen** [comment]
In the example, `<MyComponent {...data}>` gets evaluated before `If.prototype.render` is even called, so narrowing would not be correct.  What do you propose to do about that?

**Comment by aleksey-bykov** [comment]
i am not aware of the order in which react evaluates components in the JSX tree, intuitively `if` sets the context for the enclosed component to be rendered or not, that's my naive understanding how it should work

**Comment by mattmccutchen** [comment]
The emitted code for the example is like this:
```ts
React.createElement(If, { it: data !== null },
    React.createElement(MyComponent, __assign({}, data)));
```
The element gets created regardless of the `data !== null` condition (and if you had an expression like `data.x`, it would crash if `data` is null), but the element only gets _rendered_ if `If` decides to render it.  So TypeScript would have to not narrow `data` during the element creation, but keep track of the fact that it is non-null if the `it` prop to `If` is true.  Do you have a proposal for exactly what reasoning should be supported?

**Comment by aleksey-bykov** [comment]
I guess it means bad luck to the idea. Too bad, because conditional rendering is essential, an the only way to do it as it turns out is to switch to awkward JS expressions.

**Comment by kael-shipman** [comment]
I was looking for this, too. Would be an awesome feature, but it does look like a pretty fundamental limitation. Too bad :(.
