### ISSUE TITLE
Control flow narrowed type preventing property assignment

### ISSUE THREAD

**Issue by voltrevo** [Microsoft/TypeScript#26857]
**TypeScript Version:** ^3.1.0-dev.20180901

**Search Terms:**
- property assignment type error control flow
- control flow based type preventing property assignment
- compiler allows bad state transition

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
let x: { state: 'a' } | { state: 'b' } = { state: 'a' };

x.state = 'b';
```

**Expected behavior:**
No errors.

**Actual behavior:**
```
src/tsbug2.ts:3:1 - error TS2322: Type '"b"' is not assignable to type '"a"'.

3 x.state = 'b';
  ~~~~~~~
```

**Playground Link:** 
https://www.typescriptlang.org/play/index.html#src=let%20x%3A%20%7B%20state%3A%20'a'%20%7D%20%7C%20%7B%20state%3A%20'b'%20%7D%20%3D%20%7B%20state%3A%20'a'%20%7D%3B%0D%0A%0D%0Ax.state%20%3D%20'b'%3B%0D%0A

**Related Issues:** 
I didn't find any.

---

**My thoughts:**

Maybe it's just a bad idea for the compiler to figure out this kind of assignment will always be a valid state transition (could get complicated with other props and more states). However, the compiler does say that this similar assignment is ok:

```ts
function test(x: { state: 'a' } | { state: 'b' }) {
    // This is ok, but did the compiler figure that out or is it just being permissive?
    x.state = 'b';
}
```
https://www.typescriptlang.org/play/index.html#src=function%20test(x%3A%20%7B%20state%3A%20'a'%20%7D%20%7C%20%7B%20state%3A%20'b'%20%7D)%20%7B%0D%0A%20%20%20%20%2F%2F%20This%20is%20ok%2C%20but%20did%20the%20compiler%20figure%20that%20out%20or%20is%20it%20just%20being%20permissive%3F%0D%0A%20%20%20%20x.state%20%3D%20'b'%3B%0D%0A%7D

It looks like it's just being permissive. Digging further, it appears it also permits this invalid transition:

```ts
type X = (
    { state: 'a'; } |
    { state: 'b'; tag: string; }
);

function toStateB(x: X): X {
    x.state = 'b'; // Should be an error right?
    return x;
}

const badX: X = toStateB({ state: 'a' });

console.log(badX);
// logs:
// { state: 'b' }
// which is not of type X
```
https://www.typescriptlang.org/play/index.html#src=type%20X%20%3D%20(%0D%0A%20%20%20%20%7B%20state%3A%20'a'%3B%20%7D%20%7C%0D%0A%20%20%20%20%7B%20state%3A%20'b'%3B%20tag%3A%20string%3B%20%7D%0D%0A)%3B%0D%0A%0D%0Afunction%20toStateB(x%3A%20X)%3A%20X%20%7B%0D%0A%20%20%20%20x.state%20%3D%20'b'%3B%0D%0A%20%20%20%20return%20x%3B%0D%0A%7D%0D%0A%0D%0Aconst%20badX%3A%20X%20%3D%20toStateB(%7B%20state%3A%20'a'%20%7D)%3B%0D%0A%0D%0Aconsole.log(badX)%3B

Whether or not it's a good idea to accept this limitation and be permissive here, shouldn't it be consistent with the first example? Why does the control flow narrowed type make a difference to assignabilty?

**Comment by ahejlsberg** [comment]
This is working as intended (but arguably a design limitation).

You're basically exploring the difference between the types `{ state: 'a' } | { state: 'b' }` and `{ state: 'a' | 'b' }`. With the former you're saying the entire object has either one shape or the other, where each possible shape has a `state` property with a single possible value. With the latter you're saying that `state` is a property that can have two possible values.

Now, when _reading_ the value of `state` it doesn't matter which kind of type you use, and if flow control cannot narrow it to one of the specific cases you're simply going to read a value of type `'a' | 'b'`. However, when _writing_ to `state` there's a difference. It technically is only safe to treat the type as `'a' | 'b'` if it was so declared (i.e. the latter kind of type). In the union of shapes case, if flow control cannot narrow it to one of the specific cases, you could argue that we shouldn't permit the assignment at all, for example by computing type `'a' & 'b'` for the synthetic combined property. However, for reasons of implementation simplicity we don't make this distinction--we effectively check that the assignment _could_ be correct, but not that it is _known_ to be correct.

**Comment by ahejlsberg** [comment]
Also see #14150 and #18101.

**Comment by voltrevo** [comment]
Thanks for the prompt response :-).

> However, for reasons of implementation simplicity we don't make this distinction--we effectively check that the assignment could be correct, but not that it is known to be correct.

I thought something like that might be the case. I read the related issues and can see there are a lot of tricky balls to juggle here.

I also found this related strange behavior:

```ts
type X = (
    { state: 'a'; tag: number; } |
    { state: 'b'; tag: string; tag2: string; }
);

function test1(x: X): X {
    x.tag = 'foo';  // Known limitation as discussed - allowed because it might be ok
    x.tag2 = 'foo'; // This one seems less of an issue (see Demo), yet it's an error
    return x;
}

// Demo
function test2(input: { state: 'a', tag: number }) { }
const input = { state: 'a' as 'a', tag: 3, tag2: 'foo' }; 
test2(input); // Ok: input has the right props, extraneous one tolerated
```
[Playground](https://goo.gl/CvMWo4)

It seems like some conflicting ideas might have made their way into how this works. Is it possible we'll see a `--strictPropertyAssignment` to tighten this up in the future?

In general, is it a non-goal to have a perfectly strict mode? (Meaning: type consistency is guaranteed as long as the types are correct at the boundaries.)

**Comment by ahejlsberg** [comment]
Regarding the error in `test1` above, we only allow an assignment if the property is present in every constituent of the union type.

> Is it possible we'll see a `--strictPropertyAssignment` to tighten this up in the future?

It certainly is possible.

> In general, is it a non-goal to have a perfectly strict mode?

I don't think a perfectly strict mode is an attainable goal. We'd have to rule out so many things that the type checker would become more of a nuisance than a help. For example, no type assertions, no `any`, no co-variant arrays, no reading of variables from outer enclosing functions because we can't prove they've been assigned, etc. etc. Plus we'd force you to write defensive `if` guards to prove to the control flow analyzer that something is not `undefined` even when you know it isn't. Static type checking of the full semantics of a dynamic language is always going to be an imperfect game to some extent.

**Comment by voltrevo** [comment]
Makes sense. Thanks again.
