### ISSUE TITLE
TS Paths not working with index.ts when using a wildcard - more explained inside

### ISSUE THREAD

**Issue by appsolutegeek** [microsoft/TypeScript#26859]
Hi,

I am using paths to point to another project ( I am using lerna), anyway, I have the following path setup.

```
    "paths": {
      "@test/pkg2/*": [
        "./packages/pkg2/src/*"
      ],
```

The problem is that if I do the following, I get an error saying cannot find module.

```
import {Something} from "@test/pkg2"; // <<<<<<< This errors HERE HERE
import {TestMe} from '@test/pkg2/item/testme' << This is fine
```

The above error can be fixed by appending index.ts after the /pkg2, but it should know the default package name is index.ts if not is specified.

I can, of course, change the paths to 

      "@test/pkg2": [
        "./packages/pkg2/src"
      ],

but now, of course, it complains about not finding testme (see above). The only way I was able to get it to work was by adding both the paths, but is this really correct ?

So, here is what i ended up with, its a lot more code.

```
   "paths": {
      "@test/pkg2/*": [
        "./packages/pkg2/src/*"
      ],
      "@test/pkg2": [
        "./packages/pkg2/src/"
      ]
    }
```

**Comment by RyanCavanaugh** [comment]
Folders (or `index` posing "as" a folder) and files are treated separately in path mappings. Generally this is preferred since it gives you more control over whether or not you want to be able to import a sub-module of some given path (frequently you *don't*)

**Comment by exarus** [comment]
@RyanCavanaugh didn't got what should I do to avoid the issue? I've been using WebStorm before, and was very surprised that after jsconfig.json config I still have bugged import resolution.

**Comment by ctsstc** [comment]
Would love to see how jest handles this, or something similar.
ie: 
```
"moduleNameMapper": {
  "^@/(.*)$": "<rootDir>/src/$1"
}
```

**Comment by glemiere** [comment]
Same problem here.
`index.ts` - works fine
`folder/index.ts` - works fine
`folder/folder/folder/index.ts` - fails.

Weird!

**Comment by glemiere** [comment]
Hm, I thought I had a similar issue, but then I realized that I the error was coming from not removing my `lib` folder before rebuilding.
I did create a `file.ts` and then changed it to `file/index.ts`. The previous `file.ts` was still there in my lib folder and was messing everything up.

Hope that helps!

**Comment by W1nstar** [comment]
Got here following this issue https://github.com/Microsoft/vscode/issues/57096

I have a similar problem where vscode can't resolve index.js on a jsconfig.json wildcard defined path. Will this ever be resolved?

**Comment by exarus** [comment]
Why closed? Is the issue is fixed for VSCode?

**Comment by jonlambert** [comment]
FWIW I just got stuck on this but I think I solved it. Adding `"module": "commonjs"` to `compilerOptions` got it working for me. 

My `jsconfig.json`:

```json
{
  "compilerOptions": {
    "target": "es2017",
    "allowSyntheticDefaultImports": false,
    "baseUrl": ".",
    "paths": {
      "app/*": ["src/app/*"],
    },
    "jsx": "react",
    "checkJs": true,
    "module": "commonjs"
  },
  "exclude": ["node_modules", "dist"]
}

```

**Comment by tvercruysse** [comment]
vscode insiders 1.37.0.

Same issue with vue cli, has `src/*` mapped to `@/`. it compiles fine but when "go to definition" of an import, it just gives me either a shim, or a declared interface it can find.

**Comment by Luchanso** [comment]
> FWIW I just got stuck on this but I think I solved it. Adding `"module": "commonjs"` to `compilerOptions` got it working for me.
> 
> My `jsconfig.json`:
> 
> ```json
> {
>   "compilerOptions": {
>     "target": "es2017",
>     "allowSyntheticDefaultImports": false,
>     "baseUrl": ".",
>     "paths": {
>       "app/*": ["src/app/*"],
>     },
>     "jsx": "react",
>     "checkJs": true,
>     "module": "commonjs"
>   },
>   "exclude": ["node_modules", "dist"]
> }
> ```

Yeah, that helped  🎉

**Comment by nicholasmakhija** [comment]
> FWIW I just got stuck on this but I think I solved it. Adding `"module": "commonjs"` to `compilerOptions` got it working for me.
> 
> My `jsconfig.json`:
> 
> ```json
> {
>   "compilerOptions": {
>     "target": "es2017",
>     "allowSyntheticDefaultImports": false,
>     "baseUrl": ".",
>     "paths": {
>       "app/*": ["src/app/*"],
>     },
>     "jsx": "react",
>     "checkJs": true,
>     "module": "commonjs"
>   },
>   "exclude": ["node_modules", "dist"]
> }
> ```

Thanks @jonlambert, that worked like a charm! :clap:

**Comment by JeromeDeLeon** [comment]
Adding `"module": "commonjs"` in my case :disappointed: 

`jsconfig.json`
```json
{
  "compilerOptions": {
    "baseUrl": "src",
    "module": "commonjs"
  },
  "include": ["src"],
  "exclude": ["node_modules"]
}
```

**Comment by JeromeDeLeon** [comment]
Restarting vs code works :smiley:

**Comment by woshixixi** [comment]
why this issue is closed ?

**Comment by bmakan** [comment]
A fair warning for anyone with similar issue as I had. My jsconfig.json:
```json
{
    "compilerOptions": {
        "baseUrl": ".",
        "paths": {
            "@api/*": ["api/*"],
            "@components/*": ["components/*"],
            "@redux/*": ["redux/*"],
            "@slices/*": ["redux/slices/*"],
        },
        "module": "commonJS"
    },
    "exclude": [
        "build",
        "node_modules",
        "public"
    ],
}
```

Now in some JavaScrpt file, this will not work:
```js
import { fetch } from '@api';
```
But the following will:
```js
import { fetch } from '@api/index';
```

The reason is quite simple although took me a while to realize it. This line:
```json
        "@api/*": ["api/*"],
```
Only works for `@api/*` (the forward slash is the most crucial here). Defining another path, e.g. `"@api": ["api/index.js"]`, will allow you to import from `@api` without specifying `index`.

**Comment by rwproj** [comment]
In my project to solve this problem i've added `"moduleResolution": "node"`. Also fixes monorepo issues.

**Comment by koiralakiran1** [comment]
Adding multiple entries solved it for me (one with `/*` and one without `/*`)
![image](https://user-images.githubusercontent.com/11130898/93716163-e807b080-fb8d-11ea-8c08-b23d9e577daf.png)

**Comment by skyewell** [comment]
Multiple entries works for me as well, same as example from koiralakiran1; but doesn't seem like this should be necessary

**Comment by JeromeDeLeon** [comment]
> Adding multiple entries solved it for me (one with `/*` and one without `/*`)
> 
> `"module": "commonjs"`
> ![image](https://user-images.githubusercontent.com/11130898/93716163-e807b080-fb8d-11ea-8c08-b23d9e577daf.png)

This is weird of why do we have to do this instead of just `@services/*` only

**Comment by jtich** [comment]
> Restarting vs code works 😃

This is what finally did it. 🤯

**Comment by phinguyen** [comment]
> > Adding multiple entries solved it for me (one with `/*` and one without `/*`)
> > `"module": "commonjs"`
> > ![image](https://user-images.githubusercontent.com/11130898/93716163-e807b080-fb8d-11ea-8c08-b23d9e577daf.png)
> 
> This is weird of why do we have to do this instead of just `@services/*` only

It work for me, same question with you.

**Comment by arryanggaputra** [comment]
No update on this?

**Comment by peterDuot-stationfive** [comment]
> A fair warning for anyone with similar issue as I had. My jsconfig.json:
> 
> ```json
> {
>     "compilerOptions": {
>         "baseUrl": ".",
>         "paths": {
>             "@api/*": ["api/*"],
>             "@components/*": ["components/*"],
>             "@redux/*": ["redux/*"],
>             "@slices/*": ["redux/slices/*"],
>         },
>         "module": "commonJS"
>     },
>     "exclude": [
>         "build",
>         "node_modules",
>         "public"
>     ],
> }
> ```
> 
> Now in some JavaScrpt file, this will not work:
> 
> ```js
> import { fetch } from '@api';
> ```
> 
> But the following will:
> 
> ```js
> import { fetch } from '@api/index';
> ```
> 
> The reason is quite simple although took me a while to realize it. This line:
> 
> ```json
>         "@api/*": ["api/*"],
> ```
> 
> Only works for `@api/*` (the forward slash is the most crucial here). Defining another path, e.g. `"@api": ["api/index.js"]`, will allow you to import from `@api` without specifying `index`.

This fixed my issue, I had also the same idea when fixing it but used a wrong solution, thanks mate!

**Comment by favger** [comment]
It can even be called import { Button } from "components"; because the baseUrl is set to "./src".

This is how I use the settings.

```json
{
  "compilerOptions": {
    "baseUrl": "./src",
    "jsx": "react",
    "target": "esnext",
    "module": "es6",
    "allowSyntheticDefaultImports": true,
    "paths": {
      "@components": ["components/index"],
      "@modals": ["modals/index"],
      "@config": ["config/index"],
      "@constants": ["constants/index"],
      "@hooks": ["hooks/index"],
      "@utils": ["utils/index"],

      "@components/*": ["components/*"],
      "@config/*": ["config/*"],
      "@constants/*": ["constants/*"],
      "@contexts/*": ["contexts/*"],
      "@hooks/*": ["hooks/*"],
      "@modals/*": ["modals/*"],
      "@modules/*": ["modules/*"],
      "@redux/*": ["redux/*"],
      "@router/*": ["router/*"],
      "@utils/*": ["utils/*"]
    }
  },
  "exclude": ["node_modules", "dist", "build"]
}

```

![vs-code-preferences](https://user-images.githubusercontent.com/25633595/162771368-abe08c3f-8bdb-4400-b31f-45059e87f20f.png)

**Comment by ruoru** [comment]
looks good, but its not work for me, i am try the [vsocde config](https://code.visualstudio.com/docs/languages/jsconfig) and not find the way. any help for me?

Option | Description
-- | --
noLib | Do not include the default library file (lib.d.ts)
target | Specifies which default library (lib.d.ts) to use. The values are "es3", "es5", "es6", "es2015", "es2016", "es2017", "es2018", "es2019", "es2020", "esnext".
module | Specifies the module system, when generating module code. The values are "amd", "commonJS", "es2015", "es6", "esnext", "none", "system", "umd".
moduleResolution | Specifies how modules are resolved for imports. The values are "node" and "classic".
checkJs | Enable type checking on JavaScript files.
experimentalDecorators | Enables experimental support for proposed ES decorators.
allowSyntheticDefaultImports | Allow default imports from modules with no default export. This does not affect code emit, just type checking.
baseUrl | Base directory to resolve non-relative module names.
paths | Specify path mapping to be computed relative to baseUrl option.

<br class="Apple-interchange-newline">


> A fair warning for anyone with similar issue as I had. My jsconfig.json:
> 
> ```json
> {
>     "compilerOptions": {
>         "baseUrl": ".",
>         "paths": {
>             "@api/*": ["api/*"],
>             "@components/*": ["components/*"],
>             "@redux/*": ["redux/*"],
>             "@slices/*": ["redux/slices/*"],
>         },
>         "module": "commonJS"
>     },
>     "exclude": [
>         "build",
>         "node_modules",
>         "public"
>     ],
> }
> ```
> 
> Now in some JavaScrpt file, this will not work:
> 
> ```js
> import { fetch } from '@api';
> ```
> 
> But the following will:
> 
> ```js
> import { fetch } from '@api/index';
> ```
> 
> The reason is quite simple although took me a while to realize it. This line:
> 
> ```json
>         "@api/*": ["api/*"],
> ```
> 
> Only works for `@api/*` (the forward slash is the most crucial here). Defining another path, e.g. `"@api": ["api/index.js"]`, will allow you to import from `@api` without specifying `index`.

**Comment by gheoneaemil** [comment]
Installing `tsconfig-paths` with `npm i -D tsconfig-paths` and adding this

`"ts-node": {
    "require": ["tsconfig-paths/register"]
}`

 in `tsconfig.json` solved it for me:

**Comment by lfzs** [comment]
> FWIW I just got stuck on this but I think I solved it. Adding `"module": "commonjs"` to `compilerOptions` got it working for me.
> 
> My `jsconfig.json`:
> 
> ```json
> {
>   "compilerOptions": {
>     "target": "es2017",
>     "allowSyntheticDefaultImports": false,
>     "baseUrl": ".",
>     "paths": {
>       "app/*": ["src/app/*"],
>     },
>     "jsx": "react",
>     "checkJs": true,
>     "module": "commonjs"
>   },
>   "exclude": ["node_modules", "dist"]
> }
> ```

an easier way is to remove `target` value

**Comment by filoscoder** [comment]
Less verbose solution, covering any aliases 🫡

```json
{
    "compilerOptions": {
        "module": "CommonJS",
        "moduleResolution": "node",
        "baseUrl": "./src",
        "paths": {
            "#*": ["*/index"],
            "#app/*": ["app/*"],
            "#server/*": ["server/*"],
            "#constants/*": ["constants/*"]
        }
    },
    "exclude": ["node_modules", "jest.config.js"]
}

```

**Comment by oleksandr-danylchenko** [comment]
## **_For someone who's working on their library and use the `exports` with the wildcard_** 

### Context
I had an issue with the TS that wouldn't automatically recognize that the import should be implicitly resolved against the `index.ts` file of the imported folder. 
```
TS2307: Cannot find module "**" or its corresponding type declarations.
```

| Error w/o `/index` | No error w/ explicit `/index` |
|--------|--------|
| ![Error without the index](https://github.com/user-attachments/assets/5c60647d-3bca-4710-9317-ed2e5543f508) | ![No error with explicit index import](https://github.com/user-attachments/assets/6a17b4d6-86f0-4808-ae62-2d26a9b242fd) | 

The config I used was:
```json
"files": [
	"dist"
],
"exports": {
	"./*": {
		"types": "./dist/*.d.ts",
		"import": "./dist/*.js"
	}
},
```



### Changes Made
I added an additional `*/index` fallback lookup. 
So that when importing the folder, the TS will follow the inner `index` file if it can't resolve the wildcard itself.
```json
"files": [
	"dist"
],
"exports": {
	"./*": {
		"types": ["./dist/*.d.ts", "./dist/*/index.d.ts"],
		"import": ["./dist/*.js", "./dist/*/index.js"]
	}
},
```

**Comment by oleksandr-danylchenko** [comment]
## **_For someone who's working on their library and use the `exports` with the wildcard_** 

### Context
I had an issue with the TS that wouldn't automatically recognize that the import should be implicitly resolved against the `index.ts` file of the imported folder. 
```
TS2307: Cannot find module "**" or its corresponding type declarations.
```

| Error w/o `/index` | No error w/ explicit `/index` |
|--------|--------|
| ![Error without the index](https://github.com/user-attachments/assets/5c60647d-3bca-4710-9317-ed2e5543f508) | ![No error with explicit index import](https://github.com/user-attachments/assets/6a17b4d6-86f0-4808-ae62-2d26a9b242fd) | 

The config I used was:
```json
"files": [
	"dist"
],
"exports": {
	"./*": {
		"types": "./dist/*.d.ts",
		"import": "./dist/*.js"
	}
},
```



### Changes Made
I added an additional `*/index` fallback lookup. 
So that when importing the folder, the TS will follow the inner `index` file if it can't resolve the wildcard itself.
```json
"files": [
	"dist"
],
"exports": {
	"./*": {
		"types": ["./dist/*.d.ts", "./dist/*/index.d.ts"],
		"import": ["./dist/*.js", "./dist/*/index.js"]
	}
},
```
