### ISSUE TITLE
Keep track of indexed array value type narrowing information

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/TypeScript#26855]
## Search Terms

array index
type narrow

## Suggestion

With strictNullChecks enabled I need to do a bunch of refactoring for the following pattern but I think TS should be able to take care of it:

```
let a: ({} | null)[] = [];

// Works
const a2 = a[0];
if (a2) {
    const b: {} = a2;
}

// Doesn't work
if (a[0]) {
    const b: {} = a[0];
}

// Doesn't work
let i = 0;
if (a[i]) {
    const b: {} = a[i];
}
```

## Use Cases

**What do you want to use this for?**

Avoid creating a new variable (extra code, more to GC).

**What shortcomings exist with current approaches?**

It requires more work and makes the code uglier.

## Examples

This is the section of code I was working on while I created the issue: https://github.com/gwtw/ts-fibonacci-heap/blob/ffb320f0c4af7ea0c947b188c84a99a7f6a77b0f/src/fibonacciHeap.ts#L224-L234

```ts
      // If there exists another node with the same degree, merge them
      while (aux[current.degree]) {
        if (this._compare(current, aux[current.degree]) > 0) {
          const temp = current;
          current = aux[current.degree];
          aux[current.degree] = temp;
        }
        this._linkHeaps(aux[current.degree], current);
        aux[current.degree] = undefined;
        current.degree++;
      }
```

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by RyanCavanaugh** [comment]
See #11483
