### ISSUE TITLE
Consider inverting tsc line number's fg/bg rather than setting the fg/bg colors to ensure contrast

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/TypeScript#26850]
Tested on typescript@3.0.3

Light+ in VS Code (bad):

<img width="194" alt="screen shot 2018-09-02 at 12 25 26 pm" src="https://user-images.githubusercontent.com/2193314/44959932-8d6a6180-aeab-11e8-8191-334035331fd8.png">

A dark theme in VS Code (fine):

<img width="175" alt="screen shot 2018-09-02 at 12 25 32 pm" src="https://user-images.githubusercontent.com/2193314/44959934-8fccbb80-aeab-11e8-9b7d-6850f0e93db3.png">

Terminal.app (fine):

<img width="114" alt="screen shot 2018-09-02 at 12 26 41 pm" src="https://user-images.githubusercontent.com/2193314/44959935-8fccbb80-aeab-11e8-98ce-8c095aa21460.png">

**Comment by DanielRosenwasser** [comment]
Feel free to send a PR! You probably know more about PTTYs than I do at this point ;)

**Comment by Tyriar** [comment]
@DanielRosenwasser I spent a while looking for where this line number is printed but couldn't see it, I'd be happy to if you could you give me a pointer to the file where the line number is rendered?

**Comment by DanielRosenwasser** [comment]
Check out the usages of `gutterStyleSequence` in `program.ts`:

https://github.com/Microsoft/TypeScript/blob/6fb0f6818ad48bf4f685e86c03405ddc84b530ed/src/compiler/program.ts#L253

**Comment by Tyriar** [comment]
@DanielRosenwasser done 😃
