### ISSUE TITLE
Typescript does not update its cache

### ISSUE THREAD

**Issue by prd0000** [microsoft/TypeScript#26858]
I have done some reorganizing, moving modules that has been used in both client and server side to "common" folder. I have updated all references, but it seems typescript still looking at old path.

This is my import
![import](https://user-images.githubusercontent.com/4971305/44979418-507b9900-af97-11e8-93c5-4bf6597e9868.PNG)

and this is what typescript error looks like
![cannot find](https://user-images.githubusercontent.com/4971305/44979453-5f624b80-af97-11e8-867e-e34675fc437e.PNG)

I have searched all files for definition, and this is the result
![search](https://user-images.githubusercontent.com/4971305/44979483-6f7a2b00-af97-11e8-975f-e24fa41e59bc.PNG)

Typescript version is 3.0.3
![image](https://user-images.githubusercontent.com/4971305/44979703-fe874300-af97-11e8-8291-c8534e6f00cc.png)

**Comment by MartinJohns** [comment]
Just pointing out that VS Code is not using your globally installed TypeScript version. By default VS Code ships with a TypeScript which is used for all TS projects. The VS Code version 1.26 (July 2018) ships with TypeScript 3.0.1. You can configure VS Code to use a locally installed version using the `typescript.tsdk` setting.

**Comment by prd0000** [comment]
Ok.. not sure how it fixed, but it is fixed after I reformatted Z drive. copied all src files, reformat, and copy it back, run npm i, and voila. Rather extreme, but I isolated my code, and my deadline is coming.

**Comment by RyanCavanaugh** [comment]
We'll need some way to reproduce this issue in order to investigate it. TypeScript doesn't maintain caches that persist between compilations or between editor sessions, so there is probably something else going on here

**Comment by RyanCavanaugh** [comment]
No repro provided
