### ISSUE TITLE
Allow param decorators to use function generics

### ISSUE THREAD

**Issue by ivogabe** [Microsoft/TypeScript#2685]
At the moment, parameter decorators cannot use generics of their parent function. Example:
```typescript
declare function decorate<T>(): any;
class Foo {
    bar<U>(@decorate<U>() param: U) { }
}
```
Throws: `TS2304: Cannot find name 'U'.`
Suggestion: allow using function generics in parameter decorators. The example should compile.

**Comment by mhegazy** [comment]
But what would that mean.. the decorator does not have access to the installation. the decorator runs only once at the class construction time, so at this point U is just any.

**Comment by ivogabe** [comment]
Well, that's a good question actually.. I was thinking about #2686, but that seems to be the only use-case of it. Closing this, since #2686 contains that already.
