### ISSUE TITLE
JsonWebKey lacking kid attribute

### ISSUE THREAD

**Issue by funkybob** [microsoft/TypeScript#26854]
According to https://tools.ietf.org/html/rfc7517#section-4.5  'kid' is a standard, valid attribute of a JWK.

However, https://github.com/Microsoft/TypeScript/blob/master/src/lib/dom.generated.d.ts#L537 does not include it.

**Comment by saschanaz** [comment]
Looks like this is not in the WebCrypto spec. [Filing an issue there](https://github.com/w3c/webcrypto/issues) may help.

**Comment by RyanCavanaugh** [comment]
Sounds like this was not valid
