### ISSUE TITLE
Error using 'declarationDir' with 'composite'

### ISSUE THREAD

**Issue by ajafff** [Microsoft/TypeScript#26862]
**TypeScript Version:**  3.1.0-dev.20180831

**Search Terms:**

**Code**

tsconfig.json
```ts
{
  "compilerOptions": {
    "composite": true,
    "declarationDir": "./decl"
  }
}
```

**Expected behavior:**

No error because `composite` implicitly enables `declaration`.

**Actual behavior:**

`TS5052: Option 'declarationDir' cannot be specified without specifying option 'declaration'.`

**Related Issues:** #26786

**Comment by a-tarasyuk** [comment]
@RyanCavanaugh I want to start work on this issue. Is it correct expected behavior for this case?

**Comment by a-tarasyuk** [comment]
@RyanCavanaugh could you reply to my previous question?

**Comment by RyanCavanaugh** [comment]
@a-tarasyuk yep
