### ISSUE TITLE
3.0.1 - Empty object in nested array breaks typing 

### ISSUE THREAD

**Issue by Olian04** [microsoft/TypeScript#26868]
**TypeScript Version:**  3.0.1 _(version shipped with vscode)_

**Code**

```ts
const A =  [
  [{}, true]
];

const B =  [
  [new Object(), true]
];

const C =  [
  [{a: 1}, true]
];
```

**Expected behavior:**
The type of:
- `A`  should be `(boolean | {})[][]`
- `B` should be `(boolean | Object)[][]`

**Actual behavior:**
The type of: 
- `A`  is `{}[][]`
- `B` is `Object[][]`

_Note: The type of `C` is `(boolean | {a: number})[][]` as should be expected_

**Playground Link:** https://www.typescriptlang.org/play/#src=const%20A%20%3D%20%20%5B%0D%0A%20%20%5B%7B%7D%2C%20true%5D%0D%0A%5D%3B%0D%0Aconst%20B%20%3D%20%20%5B%0D%0A%20%20%5Bnew%20Object()%2C%20true%5D%0D%0A%5D%3B%0D%0A%0D%0Aconst%20C%20%3D%20%20%5B%0D%0A%20%20%5B%7Ba%3A%201%7D%2C%20true%5D%0D%0A%5D%3B

**Comment by j-oliveras** [comment]
At `A`, true is assignable to `{}`, and at `B`, true is assignable to `Object`. Typescript simplifies the result type (no errors with this code):
```ts
let e: {} = {};
e = true;

let o = new Object();
o = true;
```

[Playground](https://www.typescriptlang.org/play/#src=let%20e%3A%20%7B%7D%20%3D%20%7B%7D%3B%0D%0Ae%20%3D%20true%3B%0D%0A%0D%0Alet%20o%20%3D%20new%20Object()%3B%0D%0Ao%20%3D%20true%3B%0D%0A).
