### ISSUE TITLE
Don't insert spaces for JavaScript object braces

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#26878]
_From @ma11hew28 on September 3, 2018 13:53_

I like the inserted spaces here `if (true) { return; }` but not here `let params = { limit: 1 }`.

Maybe a format setting named, for example, `insertSpaceAfterOpeningAndBeforeClosingObjectBraces` should be added?

I also want this style for TypeScript.

_Copied from original issue: Microsoft/vscode#57813_

**Comment by mjbvz** [comment]
Closing due to lack of further feedback on this issue

**Comment by ma11hew28** [comment]
OK. Thank you.
