### ISSUE TITLE
preserveWatchOutput is ignored when using --build

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/TypeScript#26873]
**TypeScript Version:**  3.0.3

**Search Terms:**

preserveWatchOutput
project references

**Code**

I have a simple `--build` setup with 2 `tsconfig.json`s, both of which have "preserveWatchOutput": true

**Comment by sheetalkamat** [comment]
That's why you need to pass --preserveWatchOutput on command line and not read from tsconfig since we cant turn it on or off for just one project

**Comment by Tyriar** [comment]
I would the main tsconfig (which references the other one) to override it. Can there be more than one primary project?

**Comment by sheetalkamat** [comment]
yes you can pass list of projects

**Comment by Hoishin** [comment]
I think the expected behaviour would be outputting warning if there is conflicting `preserveWatchOutput`. Also it could be considered to deprecate `preserveWatchOutput` settings in `tsconfig.json` and recommend passing it to command line.

**Comment by Tyriar** [comment]
I don't mind if it checks for all are false or just a single one is false or only works on the command line. But there should be some way to make it work as [it makes `tsc` difficult to work with for many users](https://github.com/Microsoft/TypeScript/issues/21295#issuecomment-369395986), a new example I've run into since that comment is using `tsc` with [`concurrently`](https://www.npmjs.com/package/concurrently).

**Comment by sheetalkamat** [comment]
Yes I think passing this on command line makes sense rather than complicating it unnecessarily. (which works today)

**Comment by weswigham** [comment]
I think this was dealt with by #27078.
