### ISSUE TITLE
@ts-nocheck seems to be ignored on TS file

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#26887]
_From @arsnl on August 25, 2018 0:59_

 

- VSCode Version: 1.26.1
- OS Version: macOS High Sierra 10.13.6
- TypeScript: 3.0.1

**Steps to Reproduce**

1. Add `// @ts-nocheck` at the start of any TypeScript file
2. Try to trigger any TS check error

**Result**

VS Code display TS error

![error](https://user-images.githubusercontent.com/763489/44613360-6a232080-a7e0-11e8-8f0d-58cd47d28cfc.jpg)

**Expected**

VS Code should not display TS error

Does this issue occur when all extensions are disabled?: Yes

**Snippet to try**

```TS
// @ts-nocheck

const test = (foo: string) => `${foo}-bar`;

test(1); // Should not display error

test('baz'); // Correct behavior with correct type

// @ts-ignore
test(1); // Correct behavior with @ts-ignore
```

_Copied from original issue: Microsoft/vscode#57187_

**Comment by weswigham** [comment]
In the original design (#14496) the intent was for `ts-check` and `ts-nocheck` to only have meaning in JS files. The same with `ts-ignore`. We gave in to community demands for `ts-ignore` in TS code; so I suppose this now tracks the same for `ts-nocheck`.

**Comment by martpie** [comment]
@hpmax00 if you read the comment just before yours, you can see this is intentional and is not a bug.

From experience (I’ve been there), you would need it for TS files only when something is not correctly configured in your editor or your project, so I advice you to double check your config :)

**Comment by hpmax00** [comment]
@martpie My situation is not as simply as you said just configuring the ide. You said it is intentional. Good job, your house your rules. Anyway thank you for reply.

**Comment by doberkofler** [comment]
@martpie I would find this most helpful especially in the transition to TypeScript or is there another elegant way to prevent files from being type checked?

**Comment by martpie** [comment]
@doberkofler I’d say write JS files and enable TS’s `allowJs` compiler option.

But it defeats a little bit the purpose of TypeScript.

**Comment by kidonng** [comment]
This is implemented in TypeScript 3.7 beta: https://devblogs.microsoft.com/typescript/announcing-typescript-3-7-beta/

**Comment by dcsan** [comment]
my use case for this is having a single file that does some on the fly metaprogramming that strict type checking in TS is not really designed for. But just adding one `.js` file to your app is nasty. for example I have my IDE setup to ignore JS files, to output in a certain place etc. So enabling to use hacky JS syntax in a single file is a benefit.

**Comment by KutnerUri** [comment]
I'm so glad you implemented this feature - a while ago I "upgraded" my entire project by replacing all .js to .ts with `// @ts-nocheck`. Git was smart enough to detect it as a file rename and preserved git history.

Now whenever we encounter a nocheck file, we remove the comment and fix the types, and gradually upgrade the entire project.

**Comment by vkarpov15** [comment]
:+1: for this feature, there should be a way to disable all type checking for a TS file
