### ISSUE TITLE
In JS, can't resolve properties from prototype assignment

### ISSUE THREAD

**Issue by sandersn** [Microsoft/TypeScript#26885]
```js
function Multimap() {
    this._map = {};
};

Multimap.prototype = {
    /**
     * @param {string} key
     * @returns {number} the value ok
     */
    get(key) {
        return this._map[key + ''];
    }
}

/** @type {Multimap} */
const map = new Multimap();
const n = map.get('hi')
```

**Expected behavior:**
No error on `map.get`

**Actual behavior:**
Error: 'get' not found on type 'Multimap'

I thought there were tests that covered exactly this case, but apparently not. This doesn't work in 3.0 or 3.1.

**Comment by andy-ms** [comment]
Note that without the type annotation the type is:
```
const map: Multimap & {
    get(key: string): number;
}
```
So `get` is considered *additional* to `Multimap` rather than being a part of it.
