### ISSUE TITLE
TSX's render function doesn't fail when generic component is without generic type

### ISSUE THREAD

**Issue by sztrzask** [Microsoft/TypeScript#26898]
**TypeScript Version:**  3.0.1

**Search Terms: TSX, generics, required, jsx, typescript**
I also read the jsx section in documentation.

**Code**
``` .tsx
.tsx

import * as React from "react";

class Generics<T> extends React.Component {
  render() {
    return <span>Generics is rendered even though it's T is not defined</span>;
  }
}

export default () => (
  <h1>
    This should fail as Generics does not have a default type. <Generics />
  </h1>
);

```

**Expected behavior:**
The above code should fail during compilation.

**Actual behavior:**
The above code passes the compilation, even though the generic type is not provided and not defaulted

**Playground Link:** 
https://codesandbox.io/s/4q15l927x

**Related Issues:** 
https://github.com/Microsoft/TypeScript/issues/3960

**Comment by ajafff** [comment]
Type parameters that cannot be inferred and don't have a default, fall back to `{}`.
There once was a PR to add an option to make this behavior an error. But that PR was rejected and it was decided this should be implemented in a linter instead.

And that's what I did. I implemented it as [no-inferred-empty-object](https://github.com/fimbullinter/wotan/blob/master/packages/mimir/docs/no-inferred-empty-object.md) for my linter runtime [Fimbullinter](https://github.com/fimbullinter/wotan). [Click here](https://github.com/fimbullinter/wotan/blob/master/packages/wotan/README.md) for detailed documentation about CLI usage, configuration and more.

Note that TSLint has a rule called [no-inferred-empty-object-type](https://palantir.github.io/tslint/rules/no-inferred-empty-object-type/). But that one [doesn't actually work](https://github.com/palantir/tslint/issues/3416) and doesn't check JSX.
