### ISSUE TITLE
Monorepo configuration docs & sample

### ISSUE THREAD

**Issue by budarin** [Microsoft/TypeScript#26904]
## Search Terms

typescript lerna monorepo settings

## Suggestion

provide simple lerna monorepo with typescript settings

## Use Cases

I want to compile my ui-kit (with symlinks) with typescript and generate proper .d.ts declarations for every component

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by RyanCavanaugh** [comment]
I think you're asking for https://www.github.com/RyanCavanaugh/learn-a ? Otherwise it's #25376

**Comment by budarin** [comment]
@RyanCavanaugh thank!
