### ISSUE TITLE
Move to other file doesn't work in JavaScript

### ISSUE THREAD

**Issue by rosieks** [Microsoft/TypeScript#26917]
Repro steps:
1. Create new ASP.NET Core 2.1 application and use React + Redux template.
2. Open file ClientApp\src\store\Counter.js
3. Move cursor to `reducer` and try *Quick actions and Refactorings…*

Expected behavior:
Option to move function to separate file.

Actual behavior:
No quick actions available

Version: Visual Studio 15.8.1

**Comment by andy-ms** [comment]
See https://github.com/Microsoft/TypeScript/issues/24857#issuecomment-418858606
