### ISSUE TITLE
Type parameter is not inferred from method return type

### ISSUE THREAD

**Issue by SLaks** [microsoft/TypeScript#26926]
**TypeScript Version:**  3.0.1-insiders.20180726

**Search Terms:** type parameter object infer

**Code**

```ts
class MyId { private x: undefined; }
class MyObject{
    private x: undefined;
    id: MyId = new MyId;
}

interface Params<TObject, TId> {
    readonly ctor: { new(): TObject },
    getId(obj: TObject): TId;
    processId(id: TId): void;
}

function declareObject<TObject, TId>(params: Params<TObject, TId>): Params<TObject, TId>{
    return params;
}

const MY_OBJECT = declareObject({
    ctor: MyObject,
    getId: obj => obj.id,
    processId: (id) => assertType<MyId>(id),
});

function assertType<T>(val: T) { }
```

**Expected behavior:**

No compilation errors.
The `TId` parameter should be inferred from the return type of `getId`, which should in turn infer the parameter type for `processId`.

**Actual behavior:**

`TId` is inferred as `{}`, creating a compiler error.

**Playground Link:** http://www.typescriptlang.org/play/#src=class%20MyId%20%7B%20private%20x%3A%20undefined%3B%20%7D%0D%0Aclass%20MyObject%7B%0D%0A%20%20%20%20private%20x%3A%20undefined%3B%0D%0A%20%20%20%20id%3A%20MyId%20%3D%20new%20MyId%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20Params%3CTObject%2C%20TId%3E%20%7B%0D%0A%20%20%20%20readonly%20ctor%3A%20%7B%20new()%3A%20TObject%20%7D%2C%0D%0A%20%20%20%20getId(obj%3A%20TObject)%3A%20TId%3B%0D%0A%20%20%20%20processId(id%3A%20TId)%3A%20void%3B%0D%0A%7D%0D%0A%0D%0Afunction%20declareObject%3CTObject%2C%20TId%3E(params%3A%20Params%3CTObject%2C%20TId%3E)%3A%20Params%3CTObject%2C%20TId%3E%7B%0D%0A%20%20%20%20return%20params%3B%0D%0A%7D%0D%0A%0D%0Aconst%20MY_OBJECT%20%3D%20declareObject(%7B%0D%0A%20%20%20%20ctor%3A%20MyObject%2C%0D%0A%20%20%20%20getId%3A%20obj%20%3D%3E%20obj.id%2C%0D%0A%20%20%20%20processId%3A%20(id)%20%3D%3E%20assertType%3CMyId%3E(id)%2C%0D%0A%7D)%3B%0D%0A%0D%0Afunction%20assertType%3CT%3E(val%3A%20T)%20%7B%20%7D

**Related Issues:** None

**Comment by RyanCavanaugh** [comment]
There are competing goals for inference here; this one is a casualty of the ordering of which candidates are preferred.

However, I would say you have too many type parameters. This code is error-free and actually more accurately represents your intent:
```ts
type HasId = { id: unknown };
class MyId { private x: undefined; }
class MyObject {
    private x: undefined;
    id: MyId = new MyId;
}

interface Params<TObject extends HasId> {
    readonly ctor: { new(): TObject },
    getId(obj: TObject): TObject["id"];
    processId(id: TObject["id"]): void;
}

function declareObject<TObject extends HasId>(params: Params<TObject>): Params<TObject>{
    return params;
}

const MY_OBJECT = declareObject({
    ctor: MyObject,
    getId: obj => obj.id,
    processId: (id) => assertType<MyId>(id),
});

function assertType<T>(val: T) { }
```

**Comment by aleclarson** [comment]
I think I have a related use case:
```ts
import { ComponentClass, ReactNode } from 'react'

declare const promised: <Props, Result>(cfg: {
  task: (props: Props) => Promise<Result>
  render: (props: Props) => ReactNode
}) => ComponentClass<Props>

type Props = { b: 1 }
let e = promised({
  task: async (props: Props) => true,
  /** Can we infer `props` and `result` here somehow? */
  render(props, result) {
    return props.a
  },
})
```

IMO, Typescript should (at least) support simple inference like what I'm doing above.

**Comment by aleclarson** [comment]
I think I have a related use case:
```ts
import { ComponentClass, ReactNode } from 'react'

declare const promised: <Props, Result>(cfg: {
  task: (props: Props) => Promise<Result>
  render: (props: Props, result: Result) => ReactNode
}) => ComponentClass<Props>

type Props = { b: 1 }
let MyComponent = promised({
  task: async (props: Props) => true,
  /** Can we infer `props` and `result` here somehow? */
  render(props, result) {
    return props.b
  },
})
```

IMO, Typescript should (at least) support simple inference like what I'm doing above.
