### ISSUE TITLE
Subsequent builds in Visual Studio 2017 15.9.0 fail with "Could not find a declaration file for module"

### ISSUE THREAD

**Issue by mqudsi** [microsoft/TypeScript#26922]
**TypeScript Version:**  3.0 that ships with tools version 15.0 with Visual Studio 15.9.0 (the bundled TSC)

**Search Terms:** 
"Could not find a declaration file for module"

```ts
import * as foo from "foo"; //where foo is an untyped npm package
// with foo.d.ts in the same directory as this file
```

**Expected behavior:**
The foo.d.ts is picked up and used

**Actual behavior:**
* When compiling from the commandline with a bare `tsc` (tsconfig.json follows), the compilation succeeds.
* Restarting Visual Studio 15.9.0 and building solution succeeds
* Debugging the ASP.NET Core project in Visual Studio 15.9.0, waiting a bit of time, then stopping the debug and attempting to F5 debug again (without having changed any code) results in the following error message:

>      Task "MSBuild"
>        Global Properties:
>          INeedThis=JustToRebuildTypescripts
>          BuildingProject=true
>        Building with tools version "15.0".
>        Target PreComputeCompileTypeScript:
>          Using "VsTsc" task from assembly "C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.0\build\TypeScript.Tasks.dll".
>          Task "VsTsc"
>            C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.0\tsc.exe    --removeComments --noImplicitAny --declaration --module System --outDir "wwwroot\transpiled" --sourcemap --target ES5 --moduleResolution node --lib es7,dom --noEmitOnError --listEmittedFiles --locale en-US "D:\GIT\cpsastats\cpsa\ts\Charts.ts" "D:\GIT\cpsastats\cpsa\ts\HtmlUtils.ts" "D:\GIT\cpsastats\cpsa\ts\ReadOnlyTable.ts" "D:\GIT\cpsastats\cpsa\ts\TestCharts.ts" "D:\GIT\cpsastats\cpsa\ts\tests.ts" "D:\GIT\cpsastats\cpsa\ts\TypeGuards.ts" "D:\GIT\cpsastats\cpsa\wwwroot\lib\handsontable\handsontable.d.ts" "D:\GIT\cpsastats\cpsa\wwwroot\lib\moment\moment.d.ts" "D:\GIT\cpsastats\cpsa\wwwroot\lib\numbro\numbro.d.ts"
>          Done executing task "VsTsc".
>        Target "PreComputeCompileTypeScriptWithTSConfig" skipped, due to false condition; ('@(ConfigFiles)' != '' AND '$(DesignTimeBuild)' != 'true') was evaluated as ('' != '' AND '' != 'true').
>        Target CompileTypeScript:
>          Building target "CompileTypeScript" completely.
>          Output file "should_not_exist.file" does not exist.
>          Using "CreateProperty" task from assembly "Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
>          Task "CreateProperty"
>          Done executing task "CreateProperty".
>          Task "VsTsc"
>            C:\Program Files (x86)\Microsoft SDKs\TypeScript\3.0\tsc.exe    --removeComments --noImplicitAny --declaration --module System --outDir "wwwroot\transpiled" --sourcemap --target ES5 --moduleResolution node --lib es7,dom --noEmitOnError --listEmittedFiles --locale en-US "D:\GIT\cpsastats\cpsa\ts\Charts.ts" "D:\GIT\cpsastats\cpsa\ts\HtmlUtils.ts" "D:\GIT\cpsastats\cpsa\ts\ReadOnlyTable.ts" "D:\GIT\cpsastats\cpsa\ts\TestCharts.ts" "D:\GIT\cpsastats\cpsa\ts\tests.ts" "D:\GIT\cpsastats\cpsa\ts\TypeGuards.ts" "D:\GIT\cpsastats\cpsa\wwwroot\lib\handsontable\handsontable.d.ts" "D:\GIT\cpsastats\cpsa\wwwroot\lib\moment\moment.d.ts" "D:\GIT\cpsastats\cpsa\wwwroot\lib\numbro\numbro.d.ts"
>            D:\GIT\cpsastats\cpsa\ts\Charts.ts(1,164): error TS7016: Build:Could not find a declaration file for module 'echarts'. 'D:/GIT/cpsastats/cpsa/node_modules/echarts/index.js' implicitly has an 'any' type.
>            Unknown output:   Try `npm install @types/echarts` if it exists or add a new declaration (.d.ts) file containing `declare module 'echarts';`
>            D:\GIT\cpsastats\cpsa\ts\Charts.ts(2,26): error TS7016: Build:Could not find a declaration file for module 'echarts'. 'D:/GIT/cpsastats/cpsa/node_modules/echarts/index.js' implicitly has an 'any' type.
>            Unknown output:   Try `npm install @types/echarts` if it exists or add a new declaration (.d.ts) file containing `declare module 'echarts';`
>            D:\GIT\cpsastats\cpsa\ts\TestCharts.ts(4,28): error TS7016: Build:Could not find a declaration file for module 'echarts'. 'D:/GIT/cpsastats/cpsa/node_modules/echarts/index.js' implicitly has an 'any' type.
>            Unknown output:   Try `npm install @types/echarts` if it exists or add a new declaration (.d.ts) file containing `declare module 'echarts';`
>            The command exited with code 1.
>          Done executing task "VsTsc" -- FAILED.
>        Done building target "CompileTypeScript" in project "cpsa.csproj" -- FAILED.
>

Switching to the command line and executing `tsc` succeeds.

tsconfig.json:

```json
{
	"compileOnSave": true,
	"compilerOptions": {
		"allowSyntheticDefaultImports": true,
		"allowUnreachableCode": false,
		"alwaysStrict": true,
		"esModuleInterop": true,
		"experimentalDecorators": true,
		"lib": [ "es7", "dom" ],
		"moduleResolution": "node",
		"module": "system",
		"noImplicitAny": true,
		"outDir": "wwwroot/transpiled",
		"preserveConstEnums": true,
		"preserveWatchOutput": true,
		"pretty": true,
		"removeComments": false,
		"sourceMap": true,
		"strict": true,
		"strictPropertyInitialization": false,
		"target": "esnext"
	},
	"exclude": [
		"wwwroot/lib"
	]
}
```

**Comment by mqudsi** [comment]
This appears to be a race condition somewhere and it's more subtle than I reported it to be. _Typically_ first compilation upon running Visual Studio will succeed, but not always. When a subsequent build fails with the error messages from above, simply retrying a few times will make it work.

**Comment by RyanCavanaugh** [comment]
We'd need some reliable-ish way to reproduce this - maybe a zip file of your project? Otherwise there are too many unknowns to know what to look for. Thanks!

**Comment by RyanCavanaugh** [comment]
No repro provided

**Comment by mqudsi** [comment]
I haven't run into it recently so it's probably a heisenbug that got fixed.
