### ISSUE TITLE
Suggestion: Keep interfaces by converting them to classes during compile time

### ISSUE THREAD

**Issue by OzairP** [Microsoft/TypeScript#26929]
## Search Terms
keep interfaces, convert interfaces to class

## Suggestion
Currently interfaces in TypeScript are removed or moved into a type definition, but do not exist anywhere during runtime. I suggest to turn these interfaces into no-op classes. That way using interfaces during runtime to check inheritance or many other reasons is feasible.

```typescript
// At runtime this will dissapear
interface IDoor {
    open (): void;
    close (): void;
}

class SteelDoor implements IDoor {
    public open (): void {
        // ...
    }

    public close (): void {
        // ...
    }
}

if (SteelDoor instanceof IDoor) {
    // Currently: TS2693: 'IDoor' only refers to a type, but is being used as a value here.
}
```

Instead the transpiler will not complain about `TS2693` here and convert `IDoor` into a class, renaming `implements` to `extends`.

```javascript
// this is the transpiled code
class IDoor {
    open () {}
    close () {}
}

class SteelDoor extends IDoor {
    open () {
        // ...
    }

   close () {
        // ...
    }
}

if (SteelDoor instanceof IDoor) {
    // Valid and true!
}
```

## Use Cases and Examples
Firstly, this can be used for inheritance checks at runtime.
```javascript
// Valid
if (SteelDoor instanceof IDoor) {

}
```

Secondly, the interface (class) can be passed around which can make DI Containers extremely useful and type strict. Currently any interface will be renamed to `Object` in the meta data, but classes uses their appropriate identifier. 
```typescript
// IDoor can be used as more than a type! It can be used as meta data!
@Inject
function foo (door: IDoor) {

}

// Now uses
// tslib_1.__metadata("design:paramtypes", [IDoor])
// instead of
// tslib_1.__metadata("design:paramtypes", [Object])
```

## Checklist

My suggestion meets these guidelines:
* [X] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. new expression-level syntax)

This can be a compiler option, but I don't see this breaking any current projects.

**Comment by RyanCavanaugh** [comment]
A non-exhaustive list of problems here: First, classes can implement multiple interfaces, but can only extend one class. Second, you can already do this with `abstract` classes. Third, what happens if you extend one class but implement an interface? Again, classes can only extend one base class.

>  I don't see this breaking any current projects.

For one, existing interface names would start creating value names that shadow existing outer-scope value names, breaking code at runtime.

**Comment by OzairP** [comment]
Whoops, got the two flipped. At that point, might as well use abstract classes. Thanks for your rationale.
