### ISSUE TITLE
In JS, @type for class property declarations is ignored unless the default value is contained in parentheses

### ISSUE THREAD

**Issue by AlCalzone** [Microsoft/TypeScript#26938]
**TypeScript Version:**  3.1.0-dev.20180906

**Search Terms:** js class property type

**Code**

```js
class Foo {
	constructor() {
		/** @type {Record<string, number>} */
		this.bar = {}; // has type {[x: string]: any}

		/** @type {Record<string, number>} */
		this.baz = ({}); // has type {Record<string, number>}
	}
}
```

**Expected behavior:**
`bar` and `baz` both have the declared type.
**Actual behavior:**
Only `baz` has the declared type.

**Related Issues:** possibly 26743

**Comment by andy-ms** [comment]
This seems to be working for me in `typescript@next` -- `this.bar.foo = "";` will fail with `Type '""' is not assignable to type 'number'.`.

**Comment by AlCalzone** [comment]
I must be doing something wrong then
```json
// package.json
{
  "name": "repro",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "typescript": "^3.1.0-dev.20180906"
  }
}

// tsconfig.json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "allowJs": true,
    "checkJs": true,
  }
}
```
![unbenannt3](https://user-images.githubusercontent.com/17641229/45171576-0eef2600-b203-11e8-9d65-9a636d1081e2.PNG)
![unbenannt](https://user-images.githubusercontent.com/17641229/45171579-11518000-b203-11e8-84c5-69a7ca35e155.PNG)
![unbenannt2](https://user-images.githubusercontent.com/17641229/45171581-131b4380-b203-11e8-913c-eebec46ccc48.PNG)

**Comment by andy-ms** [comment]
I did reproduce the error with `typescript@3.0`. Are you sure your editor is [set up](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions) to use `typescript@next`?

**Comment by AlCalzone** [comment]
Thanks, that works indeed. Its kinda hard to switch versions in a js-only project due to the missing button with the TS version.
