### ISSUE TITLE
Cannot override type in declared array

### ISSUE THREAD

**Issue by ORESoftware** [microsoft/TypeScript#26936]
**TypeScript Version:**  3.0.1

**Search Terms:**
mapped type

**Code**

```ts
'use strict';

type TypeMapping = {
  Boolean: boolean,
  String: string,
  Number: number,
  Integer: number,
  ArrayOfString: Array<string>,
  JSON: any,
  SeparatedStrings: Array<string>,
}

export interface ElemType<T = any> {
  name: string,
  type: keyof TypeMapping,
}

export const asOptions = <K extends keyof any, T extends Array<{ name: K, type: keyof TypeMapping }>>(t: T) => t;

export type OptionsToType<T extends Array<ElemType>>
  = { [K in T[number]['name']]: TypeMapping[Extract<T[number], { name: K }>['type']] }


const typeOverride = <T>(v: ElemType): ElemType<T> => <ElemType<T>>v;

const v = asOptions([
  {name: 'foo', type: 'Boolean'},
  {name: 'bar', type: 'String'}
]);

const opts = <OptionsToType<typeof v>>{foo: true, bar: 'ageage'};

```

the above works, and opts has predicted properties on it.
However, if I change it to this:

```ts
const v = asOptions([
  
  {name: 'foo', type: 'Boolean'},
  {name: 'bar', type: 'String'},
 
  typeOverride<string>({      // I am trying to override the type
    name: 'baz',
    type: 'JSON'
  })
]);
```

**Expected behavior:**
It should still work (it compiles, but doesn't give predictive/autocomplete).

**Actual behavior:**
Not sure what the problem is, but I am getting to the limits of my knowledge with it.

**Comment by AlCalzone** [comment]
```ts
export interface ElemType<T = any> {
  name: string,
  type: keyof TypeMapping,
}
```
You are not using the generic type inside `ElemType`, so `ElemType<string>` does not structurally differ from `ElemType<number>` for example. You can add a "brand", like TS does in [several locations](https://github.com/Microsoft/TypeScript/blob/c62920ac81192f9c68fd0a3993218683dd825395/src/compiler/types.ts#L1192) to make the interfaces structurally differ:
```ts
export interface ElemType<T = any> {
  __elemTypeBrand: T;
  name: string;
  type: keyof TypeMapping;
}
```

**Comment by ORESoftware** [comment]
@AlCalzone yeah even if I use that "brand" property in the interface, I still don't get completion...type completion seems to break when I use:

```js
 typeOverride<string>({      // I am trying to override the type
    name: 'baz',
    type: 'JSON'
  })
```

if I just use a plain object, then it works:

```js
 {    
    name: 'baz',
    type: 'JSON'
 }
```

which is why I filed this as a bug.
