### ISSUE TITLE
Can i declare an Object properties must contain a or b ?

### ISSUE THREAD

**Issue by Zane0816** [Microsoft/TypeScript#26934]
when i declare an Object like this:
`interface obj {
 a?:string,
 b?string
}
`
but i want the attribute a not to exist, the attribute b must exist.
`let obj:obj={}`  It is allowed ,i want it is not allowed
`let obj:obj={a:'a'}` or `let obj:obj={b:'b'}`  if i want It is allowed. what should I do?

**Comment by markusjohnsson** [comment]
Yes, but not using an interface. Instead, use `type`:

```ts
type obj = { a: string } | { b: string };
```

if you want both properties:

```ts
type obj = { a: string } | { b: string } | { a: string; b: string; };
```

**Comment by Zane0816** [comment]
thanks! I think it should be simple @markusjohnsson
