### ISSUE TITLE
Auto type reference directives do not lowercase the typing name

### ISSUE THREAD

**Issue by sheetalkamat** [microsoft/TypeScript#26948]
As part of #9824 all type reference directives are lower cased so type="somePackage" results in looking for type reference of `somepackage` instead.

When including the auto type directives, we include list of typings from user or get the package names from typeRoots (where if config doesn't provide it, it will be node_modules/@types)
The package names read here are not lower cased. Thus this leaves a discrepancy between these type sources included and typereference directives included resulting in confusion for packages in these auto type directives to reference other packages at same level.

Eg.
If auto type references are: "UpperCasePackage", "somepackage", and if somepackage needs to reference this `UpperCasePackage` it has no way to do so correctly.

Found while working on #26944

**Comment by sheetalkamat** [comment]
This is still issue irrespective of https://github.com/microsoft/TypeScript/pull/57681

**Comment by jakebailey** [comment]
Ah, my mistake, I mistook this as something to do with emit.
