### ISSUE TITLE
yield operator in generator functions has any return type

### ISSUE THREAD

**Issue by freddi301** [microsoft/TypeScript#26959]
## Search Terms

- generator
- yield

## Suggestion

- Correct return type on `yield` operator
- Correct return type on `yield*` operator
- Correct type for generator function return

## Use Cases

better type safety

[redux-saga](https://github.com/redux-saga/redux-saga)
[koa.js](https://koajs.com/)

## Example

now:
```typescript
function* f() { // :IterableIterator<number>
  const x = yield 0; // x is any
  const y = yield* [2, 3, 4]; // y is any
}
```
desired:
```typescript
function* f1(): TypedIterableIterator<number, number> {
  const x = yield 0; // x is number
  const y = yield* [2, 3, 4]; // y is number
  yield x + y;
}
function* f2() { // :IterableIterator<number, number>
  const x: number = yield 0;
  const y: number = yield* [2, 3, 4];
  yield x + y;
}
function* f3(): TypedIterableIterator<number> {
  const x = yield 0; // x is number
  const y = yield* [2, 3, 4]; // y is number
  yield x + y;
}

interface TypedIterableIterator<T, N = any> {
  next(value: N): T;
}
```

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by gwicksted** [comment]
Can you provide an example?  I've been using yield on generators - you specify the return type of the function as `IterableIterator<T>`.  Working example:

```ts
export function* findParents(element: HTMLElement): IterableIterator<HTMLElement> {
    if (!element) {
        return undefined;
    }

    let parent = element.parentElement;
    while (parent) {
        yield parent;
        parent = parent.parentElement;
    }
}
```

**Comment by andy-ms** [comment]
I think this issue is that a `yield` expression is of type `any`.
```ts
function* f() {
    const x = yield 0; // x is any
}
```

**Comment by gwicksted** [comment]
@andy-ms ah now I understand.

In that case, my understanding is this point needs to be addressed:

> Correct return type on yield operator

But this point does not (see proof below):

> Correct type for generator function return

I'd like to add this point as well:

* Correct return type on yield* operator

Given this example [playground](http://www.typescriptlang.org/play/#src=function*%20f()%20%7B%0D%0A%20%20%20%20const%20x%20%3D%20yield%200%3B%20%2F%2F%20x%20is%20any%0D%0A%20%20%20%20const%20y%20%3D%20yield*%20%5B2%2C%203%2C%204%5D%3B%0D%0A%7D):

```ts
function* f() {
    const x = yield 0;
    const y = yield* [2, 3, 4];
}
```

* [GOOD] `f` return type is already implicitly typed as `IterableIterator<number>`
* [FIXME] `x` type should be implicitly typed as `number` (not `any`)
* [FIXME] `y` type should be implicitly typed as `IterableIterator<number>` (not `any`)

**Comment by andy-ms** [comment]
@gwicksted The value of a `yield` expression isn't necessarily the value being yielded. It depends on who's using the generator, which is why this is complicated. If the user is a `for-of` loop (which 99% of the time it is) this will simply be `void`. Some info [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Iterators_and_Generators).

**Comment by gwicksted** [comment]
@andy-ms please forgive my ignorance!  I hadn't used that syntax before today.  I assumed (incorrectly) that `let a = yield 5;` was equivalent to `let a: number; yield (a = 5);` which is not the case!  `yield` in JS behaves much like `yield` in Python.

Other than analyzing the all the consumers of the iterator looking for each call to `next` to auto-type each `yield`'s return value (good luck!), I expect this should be declared upfront by the generator's return value type declaration.

so instead of just:

```ts
interface Iterator<T> {
    next(value?: any): IteratorResult<T>;
}
interface IterableIterator<T> { }
```

You could have:

```ts
interface Iterator<T,TNext = any> {
    next(value?: TNext): IteratorResult<T>; // IteratorResult may also need to change?
}
interface IterableIterator<T,TNext = any> { }
```

Then define your generator as:

```ts
function* f(): IterableIterator<number, string> {
    const str = yield 5; // str is string
}

const iter = f();
const num = iter.next("hello").value; // next's argument is now type checked
```

Then TS needs to auto type yield's return type to the 2nd generic parameter of the generator's return type.  Shouldn't be too difficult since typing of yield's parameter is already done via the 1st generic parameter of the generator's return type.

Of course there are more advanced cases where multiple yield expressions are being passed different types but I think those are even more rare and they could simply use a union of all types expected.

**Comment by freddi301** [comment]
@gwicksted examples added (with your suggestion)

@andy-ms great suggestions

I think this could be an opt-in type refinement for case where typing on generators is needed on values supplied into it.

**Comment by gwicksted** [comment]
@freddi301 this type definition uses the recently added default generic type notation to make it an opt-in feature without breaking compatibility anywhere.  If you don't provide the 2nd type arg, it defaults to `any` which is effectively what it is today:

```ts
interface IterableIterator<T,TNext = any> { }
```

**Comment by aleclarson** [comment]
An interesting way to support typed "`yield` returns" is to have Typescript use the type expected by  the generator. See the following example:
```ts
function* foo(a: boolean) {
  // The `b` and `c` variables must be typed
  const b: number = yield 0
  const c: string = yield b == 0 ? 0 : 1
}

// The inferred generator type
type Foo = (a: boolean) => {
  next(value: number | string): IteratorResult<0 | 1>
  return(): { value: undefined, done: true }
  throw(e?: any): { value: undefined, done: true }
}

typeof foo extends Foo // => true

foo(true).next() // [ts] Expected a number|string, got undefined
```

If Javascript had [immutable generators](https://github.com/pelotom/immutagen) built-in, this would probably be easier. I'm trying to get [this library](https://github.com/Astrocoders/epitath) working with Typescript, but I don't think I can until "yield returns" can be typed.

**Comment by falsandtru** [comment]
related: #2983

**Comment by Igorbek** [comment]
My proposal for generator type definition: https://github.com/Microsoft/TypeScript/issues/2983#issuecomment-430885606

**Comment by yortus** [comment]
For anyone interested, the issues and ideas raised here were covered in quite some detail in the comment thread in #2873.

**Comment by freddi301** [comment]
Why the maintainers just happily closed the [issue](https://github.com/Microsoft/TypeScript/issues/2873#issuecomment-138646493) if it was addressed only by 20%?
