### ISSUE TITLE
for-of does not work with DOM collections when target is ES3 or ES5

### ISSUE THREAD

**Issue by Arnavion** [Microsoft/TypeScript#2696]
```typescript
var paragraphs = document.querySelectorAll("p");
for (let p of paragraphs) {
	console.log(p);
}
```

```
foo.ts(2,15): error TS2495: Type 'NodeList' is not an array type or a string type.
```

Is it because the standard emit will have the wrong behavior for live lists that are modified during iteration? A `[].slice.call()` in the emit would fix that, but perhaps that detracts from wanting to keep the output as close to the original as possible...

**Comment by mhegazy** [comment]
We did not want to complicate the array emit case, and did not want to do any type-directed emit. So for of only works on arrays for ES3/ES5.

**Comment by Arnavion** [comment]
Yep, makes sense. Thanks.

**Comment by dashaus** [comment]
With `core-js` should work? I've tried but not work, with babel it works.

**Comment by mhegazy** [comment]
Update on this issue, this should be addressed by https://github.com/Microsoft/TypeScript/pull/12346 under `--downlevelIteration`.
