### ISSUE TITLE
Array wrong strict type check on shift

### ISSUE THREAD

**Issue by hibas123** [Microsoft/TypeScript#26963]
Note that this only occures when using strict typeschecking (structNullChecks).
Tested with typescript 3.0.3 and 3.1.0 (\@next)

```ts
let array = [() => console.log("test")];
if (array.length > 0) {
    array.shift()();
}
```

**Expected behavior:**
 No error
**Actual behavior:**
 "Cannot invoke an object which is possibly 'undefined'" at array.shift()()

[Playground](https://www.typescriptlang.org/play/#src=let%20array%20%3D%20%5B()%20%3D%3E%20console.log(%22test%22)%5D%3B%0D%0Aif%20(array.length%20%3E%200)%20%7B%0D%0A%20%20%20%20array.shift()()%3B%0D%0A%7D)

**Comment by RyanCavanaugh** [comment]
We don't dynamically track the length of an array
