### ISSUE TITLE
Please remove non-ES6 types from lib.d.ts

### ISSUE THREAD

**Issue by Arnavion** [Microsoft/TypeScript#2697]
The "IE11 ECMAScript Extensions" contains ES6 collections, which allows code aimed at ES5 runtimes to mistakenly use them and fail at runtime.

For backward compatibility, perhaps make a new lib.es5.d.ts that doesn't have these sections. That will also require a way to override the default lib independent of specifying the target.

**Comment by mhegazy** [comment]
Should be removed in PR #2645

**Comment by Arnavion** [comment]
Currently that PR doesn't touch extensions.d.ts, which is where the non-ES5 extensions come from. https://github.com/Microsoft/TypeScript/blob/b1c93d3/Jakefile#L162

**Comment by mhegazy** [comment]
I left a comment(https://github.com/Microsoft/TypeScript/pull/2645#issuecomment-90275925) for @zhengbli to remove the extensions. the reason we had them is that dom typings depended on them. with the latest change i believe this is not the case any more.

**Comment by mhegazy** [comment]
also we have another issue tracking this #2636

**Comment by Arnavion** [comment]
Fixed by #2739
