### ISSUE TITLE
Remove IE-only types from lib.d.ts

### ISSUE THREAD

**Issue by Arnavion** [Microsoft/TypeScript#2698]
The various MS* interfaces and vars don't exist except in IE, and their extra properties are added to the standard properties. Eg: HTMLElement.style is of type MSStyleCSSProperties instead of CSSStyleDeclaration, which allows `element.style.pixelWidth` to compile but be undefined at runtime.

**Comment by mhegazy** [comment]
@zhengbli has a change to update lib.d.ts to remove them. see PR #2645

**Comment by Arnavion** [comment]
That PR gets rid of pixelWidth and style is now CSSStyleDeclaration, but I see it's added ms- and webkit-prefixed properties and functions. That would lead to the same problem.

But I can see the usefulness of wanting to support code like `var animation = style.animation || style.webkitAnimation;` Should it also include moz-prefixed stuff then?

**Comment by mhegazy** [comment]
These are auto generated; @zhengbli has a script that allows creating the lib file from webidl definitions. we can augment the script to add these definitions as well, assuming we have a webidl for them.

**Comment by zhengbli** [comment]
Yeah the new spec got ride of many of those interfaces but some still remain. I guess after publishing the script it is possible to create a customized version that removes all IE-only content.

**Comment by mhegazy** [comment]
Can we remove the ones that are not needed from extensions.d.ts, specifically Map, Set and the typed arrays?

**Comment by zhengbli** [comment]
Yeah I'm working on that too. Thanks!

**Comment by zhengbli** [comment]
I ran a little analysis of the extension interfaces, and found out the use count of each one:

ArrayBuffer: 5
ArrayBufferView: 17
Int8Array: 0
Uint8Array: 7
Int16Array: 0
Uint16Array: 0
Int32Array: 4
Uint32Array: 0
Float32Array: 21
Float64Array: 0
DataView: 0
Map: 0
WeakMap: 0
Set: 0

I plan to remove the unused ones and keep the others if that looks good.

**Comment by mhegazy** [comment]
Here is what i propose:

From extenstions.d.ts remove:
DataView: 0
Map: 0
WeakMap: 0
Set: 0

Update types in extentions.d.ts to use the same typings in es.d.ts
ArrayBuffer: 5
ArrayBufferView: 17
Int8Array: 0
Uint8Array: 7
Int16Array: 0
Uint16Array: 0
Int32Array: 4
Uint32Array: 0
Float32Array: 21
Float64Array: 0

**Comment by mhegazy** [comment]
should be fixed by #2739
