### ISSUE TITLE
TSC with project references does not watch for new files or changes in new files

### ISSUE THREAD

**Issue by aphex** [Microsoft/TypeScript#26989]
**Search Terms:**
project references new file compile watch

**Code**
Given the following folder structure

```bash
test
├── main
│   ├── src
│   │   └── test.ts
│   └── tsconfig.json
└── ref
    ├── src
    │   ├── main.ts
    │   └── second.tmp
    └── tsconfig.json
```

Files with the following contents
**test/main/src/test.ts**
```ts
console.log('test');
```

**test/main/tsconfig.json**
```json
{
    "compilerOptions": {
      "allowSyntheticDefaultImports": true,
      "esModuleInterop": true,
      "module": "commonjs",
      "moduleResolution": "node",
      "outDir": "./lib",
      "sourceMap": true,
      "strict": true,
      "target": "es6"
    },
    "include": [
      "src/**/*.ts"
    ],
    "exclude": [
      "node_modules"
    ],
  "references": [
    {
      "path": "../ref"
    }
  ]
  }
  ```

**test/ref/src/main.ts**
```ts
// import * as test from "./second";
// console.log(test);
```

**test/ref/src/second.tmp**
```ts
export const f = "Hello World";
```

**test/ref/src/tsconfig.json**
```json
{
  "compilerOptions": {
    "composite": true,
    "declaration": true,
    "esModuleInterop": true,
    "sourceMap": true,
    "strict": true,
    "module": "commonjs",
    "noImplicitAny": true,
    "outDir": "./lib",
    "removeComments": true,
    "rootDir": "./src",
    "preserveConstEnums": true,
    "target": "es5"
  },
  "include": [
    "src/**/*.ts"
  ],
  "exclude": [
    "node_modules"
  ]
}
```
Using the following Steps

```bash
cd test/main
npx typescript@next -b --watch --verbose
```
_Note: that at this point the lib folders have properly built test.js and main.js files._

**While the Typescript compiler is still running** 

```bash
mv ../ref/src/second.tmp ../ref/src/second.ts
```
_Note: This alone should probably re-trigger a compile, however some may argue that second.ts is not used so it wont be accounted for. Seeing that this is a composite library though, all TS files should be valid._

**Edit: test/ref/src/main.ts to the following**
```ts
import * as test from "./second";
console.log(test);
```
_Note: Upon saving this file the compiler does re-run and properly picks up main.ts and second.ts. This is because main.ts existed when the compiler process was started_

**Edit: test/ref/src/second.ts**
```ts
export const f = "Hello World Out There";
```

**Expected behavior:**
Typescript compile is aware of adding a new file and changes in the new file, second.ts. When changes or creation is detected it should recompile.

**Actual behavior:**
Watcher does not trigger a recompile of the project when adding second.ts or changing its contents after creating the file while the compiler is running.

**Related Issues:**
This bug looks similar in description however it was tough to tell if it was explaining the same issue. 
https://github.com/Microsoft/TypeScript/issues/26168

**Comment by sheetalkamat** [comment]
@aphex Thanks for logging this issue. We are aware of it and its a variant of #26524 and it would be addressed as I am already working on this.

**Comment by aphex** [comment]
Thats great, glad it's already being taken care of.
