### ISSUE TITLE
flag to make comments go to .d.ts files instead of the js files

### ISSUE THREAD

**Issue by championswimmer** [Microsoft/TypeScript#26987]
I would like the my JSDoc style comments of functions/classes go into the type declaration files instead of the emitted JS files.

That way, if I chose to use my JS without any minification, I can use it, while the comments would serve their purpose during autocomplete/intellisense in Webstorm/VSCode as well. 

Right now, except interfaces, all other comments go into the emitted JS not into the d.ts files.

**Comment by DanielRosenwasser** [comment]
Duplicate of #14619
