### ISSUE TITLE
TSC should error when emitting unsupported regex flags for legacy targets

### ISSUE THREAD

**Issue by bcherny** [microsoft/TypeScript#26982]
```ts
let a = /foo/u
let b = /goo/s
```

The `u` flag is part of ES2015 and `s` is part of `2018`. When I `target` `es5`, `es3`, etc., should TSC error? Something like:

```
The regular expression u flag is only available when targeting ECMAScript 2015 and higher.
```

**Comment by DanielRosenwasser** [comment]
The reason we didn't do do any checking is because regular expression literals work in a pretty implementation-defined way. If we actually made the distinction, would we also have to commit to down-leveling these regexes?

**Comment by bcherny** [comment]
Maybe a way to start would be to treat the the same way you do getters and setter when compiling to ES3, and just error at compile time. Today, without that error, a user might not realize that their code would give a runtime error in an ES5 environment.

**Comment by dgoldstein0** [comment]
We just learned this the almost-hard way at Dropbox - someone wrote a regex with the `u` flag and, despite compiling and typechecking with `--target ES5`, we got no compile or typecheck error. Given that code that is a syntax error in es5 usually causes a compile or type error, I was expecting the same here; and if we didn't have another test to catch this (which was a stroke of luck) we would have likely shipped the broken code to prod and break our pages in IE11 which doesn't support the `u` flag.

**Comment by RyanCavanaugh** [comment]
Two reports in six years and not many new regex flags being added at this point - I don't think this merits the risk of breaking people who have their targets set a bit too low compared to their actual runtime.
