### ISSUE TITLE
`jake LKG` infrastructure command fails when local TypeScript repo has parentheses in path

### ISSUE THREAD

**Issue by indiescripter** [Microsoft/TypeScript#26984]
**TypeScript Version:**  3.1.0-dev.xxx

**Search Terms:**
jake LKG build compiler directory pathname

**Code**

```shell
# A *self-contained* demonstration of the problem follows...
# With the TypeScript repo cloned in a directory with a pathname containing a path segment like this:
#   .../workspace-2018-09(sep)/TypeScript
npm run jake LKG
```

**Expected behavior:**
All else being good, this should execute the compiler infrastructure LKG build step without any error.

**Actual behavior:**
An unhandled promise rejection error is thrown with the following appearing in console output:
```
<redacted/>/workspace-2018-09(sep)/TypeScript $ npm run jake LKG

> typescript@3.1.0 jake <redacted/>/workspace-2018-09(sep)/TypeScript
> jake "LKG"

node lib/tsc.js -b src
node lib/tsc.js -b scripts
node built/local/tsc.js -b built/local/typescriptServices.tsconfig.json
node built/local/tsc.js -b built/local/tsserverlibrary.tsconfig.json
node scripts/generateLocalizedDiagnosticMessages.js src/loc/lcl built/local src/compiler/diagnosticMessages.generated.json
node lib/tsc.js -b src/tsc/tsconfig.release.json
node scripts/produceLKG.js
Building LKG from <redacted/>/workspace-2018-09(sep)/TypeScript/built/local to <redacted/>/workspace-2018-09(sep)/TypeScript/lib
Copied 39 files matching pattern lib?(.*).d.ts
Building <redacted/>/workspace-2018-09(sep)/TypeScript/lib/protocol.d.ts...
node <redacted/>/workspace-2018-09(sep)/TypeScript/scripts/buildProtocol.js <redacted/>/workspace-2018-09(sep)/TypeScript/src/server/protocol.ts <redacted/>/workspace-2018-09(sep)/TypeScript/built/local/typescriptServices.d.ts <redacted/>/workspace-2018-09(sep)/TypeScript/lib/protocol.d.ts
/bin/sh: 1: Syntax error: "(" unexpected
<redacted/>/workspace-2018-09(sep)/TypeScript/scripts/produceLKG.js:122
process.on("unhandledRejection", err => { throw err; });
                                          ^

Error: Command failed: node <redacted/>/workspace-2018-09(sep)/TypeScript/scripts/buildProtocol.js <redacted/>/workspace-2018-09(sep)/TypeScript/src/server/protocol.ts <redacted/>/workspace-2018-09(sep)/TypeScript/built/local/typescriptServices.d.ts <redacted/>/workspace-2018-09(sep)/TypeScript/lib/protocol.d.ts
/bin/sh: 1: Syntax error: "(" unexpected

    at checkExecSyncError (child_process.js:601:13)
    at Object.execSync (child_process.js:641:13)
    at <redacted/>/workspace-2018-09(sep)/TypeScript/scripts/produceLKG.js:119:22
    at Generator.next (<anonymous>)
    at <redacted/>/workspace-2018-09(sep)/TypeScript/scripts/produceLKG.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (<redacted/>/workspace-2018-09(sep)/TypeScript/scripts/produceLKG.js:4:12)
    at exec (<redacted/>/workspace-2018-09(sep)/TypeScript/scripts/produceLKG.js:107:12)
    at <redacted/>/workspace-2018-09(sep)/TypeScript/scripts/produceLKG.js:59:15
    at Generator.next (<anonymous>)
jake aborted.
Error: Process exited with code 1
    at api.fail (<redacted/>/workspace-2018-09(sep)/TypeScript/node_modules/jake/lib/api.js:336:18)
    at Exec.<anonymous> (<redacted/>/workspace-2018-09(sep)/TypeScript/Jakefile.js:749:13)
(See full trace by running task with --trace)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! typescript@3.1.0 jake: `jake "LKG"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the typescript@3.1.0 jake script.
```

**Related Issues:** 
https://github.com/Microsoft/TypeScript/issues/6891

**Fix**
In file `scripts/produceLKG.ts` modify the async `exec` function at around `line 91` as follows (borrowing code from [substack's shell-quote](https://github.com/substack/node-shell-quote/blob/master/index.js)):
```ts
async function exec(path: string, args: string[] = []) {
    function shellEscape(str: string): string {
        if (/["\s]/.test(str) && !/'/.test(str)) {
            return "'" + str.replace(/(['\\])/g, '\\$1') + "'";
        }
        if (/["'\s]/.test(str)) {
            return '"' + str.replace(/(["\\$`!])/g, '\\$1') + '"';
        }
        return String(str).replace(/([#!"$&'()*,:;<=>?@\[\\\]^`{|}])/g, '\\$1'); 
    }

    const cmdLine = ["node", path, ...args].map(shellEscape).join(" ");
    console.log(cmdLine);
    childProcess.execSync(cmdLine);
}
```

**Comments**
I'm happy to submit a PR for this as. However, looking around the TypeScript compiler code base in general, one finds many places when `cross-spawn` functions such as `spawn`, `exec` and `execSync` are being called without any apparent escaping of shell arguments. According, perhaps a little discussion would be appropriate regarding a *global* fix rather than a *localized* fix before submitting a PR.

**Comment by RyanCavanaugh** [comment]
The build system definitely works when there aren't weird characters in the path; I don't want to potentially introduce new build instabilities to support such a niche scenario.

**Comment by DanielRosenwasser** [comment]
I think this definitely an infrastructure bug, but I do share Ryan's concern here. Whatever solution we come up with needs to be clean, obvious, canonical, and maintainable. For that reason I don't necessarily want to adopt the solution posted above since it's pretty regex heavy and not clear if it really works 100% of the time. There is a balance between enabling new contributors while also protecting the team's current workflows by preventing subtle new bugs that could impact the publishing process in a significant way.

**Comment by indiescripter** [comment]
Fair comment @DanielRosenwasser. Thanks for readdressing and concur with your sentiment about a clean, canonical solution as I alluded to in my prior comment:

> However, looking around the TypeScript compiler code base in general, one finds many places when cross-spawn functions such as spawn, exec and execSync are being called without any apparent escaping of shell arguments.
