### ISSUE TITLE
array.map lose literal types

### ISSUE THREAD

**Issue by cevek** [Microsoft/TypeScript#26999]
**TypeScript Version:**  3.1.0-dev.20180906

**Search Terms:**

**Code**

```ts
interface Item {
    x: number;
    y: 'a' | 'b'
}
var list:Item[] = [].map(it => ({x: 1, y: 'a'}))

```

**Expected behavior:**
No error

**Actual behavior:**
Type 'string' is not assignable to type '"a" | "b"'.

**Comment by RyanCavanaugh** [comment]
Root cause is #241

**Comment by thw0rted** [comment]
This will be fixed by #40311, see the comment I just left on #33158.

**Comment by DanielRosenwasser** [comment]
It won't be fixed by #40311 unfortunately (see the "Future Work" section in the PR writeup)

**Comment by thw0rted** [comment]
Well crud.  This is all my fault, I had a bunch of related tabs open and posted this comment in a few of them where I thought the issue being reported was the same -- this wasn't one of them.  Sorry!

**Comment by DanielRosenwasser** [comment]
Don't sweat it, I had the same enthusiasm at first. 😅
