### ISSUE TITLE
MSBuild tool includes lib.scripthost.d.ts file with wrong name: lib.scriptHost.d.ts

### ISSUE THREAD

**Issue by life777** [Microsoft/TypeScript#26998]
**TypeScript Version:**  3.0.0

**Search Terms:**
MSBuild, scriptHost.d.ts

**Code**
I try to build a TypeScript project on Linux with MSBuild tool. I updated from version 2.9.2 to 3.0.0. 
Microsoft.TypeScript.MSBuild package is downloaded from [nuget](https://www.nuget.org/packages/Microsoft.TypeScript.MSBuild/). 

**Expected behavior:**
Project is built.

**Actual behavior:**
It throws an error: 
File '/home/user/.nuget/packages/microsoft.typescript.msbuild/3.0.0/tools/tsc/lib.scripthost.d.ts' not found.

It tries to find a **lib.scripthost.d.ts** file. I take a look at nuget package files folder, and there is not such file. There is another file: **lib.scriptHost.d.ts**. 

Fix is simple, just to change a case of the file name in nuget package.

**Comment by minestarks** [comment]
This should be fixed in 3.1.

**Comment by life777** [comment]
Yes, it's fixed in version 3.1.5. Thanks a lot.
