### ISSUE TITLE
names of types and variables do not allow a reserved word to be used.

### ISSUE THREAD

**Issue by puppy0cam** [microsoft/TypeScript#26995]
**TypeScript Version:**  3.1.0-dev.20180907

**Search Terms:**
names of types still parse keywords
type name interprets reserved words
declaring names cannot use keywords
reserved words cannot be used 

**Code**

```ts
export namespace Problematic {
    export type 'class' = string | null;
    export var 'class': string | null = "";
    export const 'class': string | null = "";
    export ['class']: string | null = "";
    type 'class' = string;
    export type class = string | null;
    export var class: string | null = "";
    export var class = "";
}
export interface StrangelyOk {
    class: Problematic.class;
}
```

**Expected behavior:**
a member would be declared with the name of 'class', and I could access that member from other objects
**Actual behavior:**
errors occur that prohibit the name being declared, however objects that attempt to access the member simply claim that it does not have a member of that name exported.
**Playground Link:** 
[Playground](http://www.typescriptlang.org/play/#src=export%20namespace%20Problematic%20%7B%0D%0A%20%20%20%20export%20type%20'class'%20%3D%20string%20%7C%20null%3B%0D%0A%20%20%20%20export%20var%20'class'%3A%20string%20%7C%20null%20%3D%20%22%22%3B%0D%0A%20%20%20%20export%20const%20'class'%3A%20string%20%7C%20null%20%3D%20%22%22%3B%0D%0A%20%20%20%20export%20%5B'class'%5D%3A%20string%20%7C%20null%20%3D%20%22%22%3B%0D%0A%20%20%20%20type%20'class'%20%3D%20string%3B%0D%0A%20%20%20%20export%20type%20class%20%3D%20string%20%7C%20null%3B%0D%0A%20%20%20%20export%20var%20class%3A%20string%20%7C%20null%20%3D%20%22%22%3B%0D%0A%20%20%20%20export%20var%20class%20%3D%20%22%22%3B%0D%0A%7D%0D%0Aexport%20interface%20StrangelyOk%20%7B%0D%0A%20%20%20%20class%3A%20Problematic.class%3B%0D%0A%7D)
**Related Issues:** 
None found

**Comment by DanielRosenwasser** [comment]
You can use an export declaration with a local name that's not reserved, and any identifier for an exported name.

```ts
declare namespace Foo {
    var _class;
    export { _class as class };
}

Foo.class
```

**Comment by pineapplemachine** [comment]
I'm converting some JS code to TS. The JS module I'm working on exports a function with a "null" attribute added. The obvious `export const null = ...` produces a syntax error, and I've ended up here trying to find a workaround.

The solution @DanielRosenwasser gave may have worked in an earlier version of TypeScript, but in latest (3.2.4) I get a syntax error with this example code:

``` ts
export namespace MyNamespace {
    const _null = "My Constant";
    export {_null as null};
}
```

This is the error I receive:

``` text
error TS1194: Export declarations are not permitted in a namespace.
3     export {_null as null};
```
