### ISSUE TITLE
type inference, readonly, symbol

### ISSUE THREAD

**Issue by vasivas** [Microsoft/TypeScript#27005]
```
const a = 5; // Ok, const a: 5
const b = Symbol(); // Ok, const a: typeof b

class T {
    readonly a = 5; // Ok, a: 5
    readonly b = Symbol(); // Bug? b: symbol
}
```

[...playground](https://www.typescriptlang.org/play/#src=const%20a%20%3D%205%3B%20%2F%2F%20Ok%2C%20const%20a%3A%205%0Aconst%20b%20%3D%20Symbol()%3B%20%2F%2F%20Ok%2C%20const%20a%3A%20typeof%20b%0A%0Aclass%20T%20%7B%0A%20%20%20%20readonly%20a%20%3D%205%3B%20%2F%2F%20Ok%2C%20a%3A%205%0A%20%20%20%20readonly%20b%20%3D%20Symbol()%3B%20%2F%2F%20Bug%3F%20b%3A%20symbol%0A%7D)

**Comment by andy-ms** [comment]
The value of `new T().b` will be different every time you create a new instance, so I don't think it could be given a unique symbol type.

**Comment by vasivas** [comment]
@andy-ms exactly!

**Comment by vasivas** [comment]
@andy-ms 

```
function f(){
    const v = Symbol(); // v: unique symbol
}

const v = Symbol(); // v: typeof v... why not unique symbol
```

**Comment by DanielRosenwasser** [comment]
It sounds like the real bug here is that `f` shouldn't introduce a unique symbol.
