### ISSUE TITLE
Intellisence doesn't work when exporting a new instance

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#27003]
_From @RomainLanz on September 9, 2018 15:55_

Hey all! 👋 

- VSCode Version: Code - Insiders 1.28.0
- OS Version: macOS 10.13.6

I don't know if this is a TypeScript bug or VSCode bug, feel free to move or close it if it doesn't fit here.

I'm trying to add typing from JSDoc comment via an `import` statement in my type annotation (`@type {import('@adonisjs/framework/src/Route/Manager)`).

When the given class returns a new instance (like the code below) it doesn't provide the intellisence.

```js
class RouteManager {}

module.exports = new RouteManager() // Doesn't work
module.exports =RouteManager // Works
```

**Steps to Reproduce:**

1. Install an AdonisJs application
2. Add types to the file `start/routes.js`

```js
/** @type {import('@adonisjs/framework/src/Route/Manager)} */
const Route = use('Route')

...
```

3. Play with the file inside `node_modules/@adonisjs/framework/src/Route/Manager.js` to add and remove the `new` in the export.

**Example:**
![screenflow](https://user-images.githubusercontent.com/2793951/45266257-836ed280-b458-11e8-9deb-4559607c99ef.gif)

_Copied from original issue: Microsoft/vscode#58298_

**Comment by andy-ms** [comment]
This is working for me for a simple example in `typescript@next`.
**a.js**
```js
class C {
    m() {}
}
module.exports = new C();
```
***b.js**
```js
/** @type {import('./a')} */
const instance = JSON.parse("");
instance.m();
instance.n(); // Error
```

**Comment by andy-ms** [comment]
You shouldn't need to change the file extension. `module.exports =` isn't recognized in TS but is in JS.
Also, if you set up vscode to use your local install of typescript ([instructions](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions)), it should show `3.1.0-dev.20180907`.

**Comment by RomainLanz** [comment]
Yes!

Seems that the bug has been fixed in one of the latest releases of TypeScript!
Thank you @andy-ms!

Latest question, is it possible to type an unpacked variable from JSDoc?

```js
/**
 * @typedef {import('@adonisjs/framework/src/Request')} Request
 */

/**
 * @param {Request} options.request
 */
function main ({ request }) {
  // request is any
}
```

**Comment by andy-ms** [comment]
@RomainLanz I've created an issue #27010 -- in the meanwhile you can add an extra line at the top `@param {object} options`.
