### ISSUE TITLE
Type Narrowing with logical OR doesn't work properly

### ISSUE THREAD

**Issue by berickson1** [microsoft/TypeScript#27002]
**TypeScript Version:**  3.1.0-dev.201xxxxx

**Search Terms:**
Type Narrowing
Logical OR

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
let foo: { a(): string } | undefined;
let bar: { a(): string } | undefined;

if (foo || bar) {
    const val = foo || bar;
    val.a(); // This is a compiler error with strictNullChecks enabled
}
```

**Expected behavior:**
val is typed as  { a(): string } inside the if block

**Actual behavior:**
val includes undefined type

**Playground Link:** http://www.typescriptlang.org/play/#src=let%20foo%3A%20%7B%20a()%3A%20string%20%7D%20%7C%20undefined%3B%0D%0Alet%20bar%3A%20%7B%20a()%3A%20string%20%7D%20%7C%20undefined%3B%0D%0A%0D%0Aif%20(foo%20%7C%7C%20bar)%20%7B%0D%0A%20%20%20%20const%20val%20%3D%20foo%20%7C%7C%20bar%3B%0D%0A%20%20%20%20val.a()%3B%0D%0A%7D

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
We don't track multi-variable type narrowing, i.e. there's no mechanism internally capable of expressing "at least one of these is truthy"

**Comment by berickson1** [comment]
Any chance this would be considered for a future typescript release? Or is this never going to be possible?

**Comment by RyanCavanaugh** [comment]
All things are always possible in the future, but I don't think this is higher priority in terms of usability than a large number of other things that need to be looked at first.
