### ISSUE TITLE
module declare Feature

### ISSUE THREAD

**Issue by spitWind** [Microsoft/TypeScript#27017]
## Search Terms
declare module    
Wildcard

## Suggestion
```
declare module  "./path/*"{
export=()=>void
}

```
It is used in the "d.ts" file to assist in editing javascript

## Use Cases
```
import * as Fb from "./path/f1"
```
Fb is ()=>void  
It is used in the "d.ts" file to assist in editing javascript   

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by DanielRosenwasser** [comment]
1. It's technically not allowed to use an `import *` as a function in ECMAScript.
2. `export =` doesn't allow arbitrary type syntax.
3. Duplicate of #8601.

**Comment by spitWind** [comment]
This wouldn't change the runtime behavior of existing JavaScript code
This isn't a runtime feature (e.g. new expression-level syntax)
the feature is not Duplicate
it user in DefinitelyTyped
