### ISSUE TITLE
Invalid code when emitting function type signature.

### ISSUE THREAD

**Issue by Vbitz** [Microsoft/TypeScript#27018]
**TypeScript Version:**  3.1.0-dev.20180907

**Search Terms:**
Error emitting function type signature.

**Code**

**Note**: This behavior is using the compiler API.

```ts
import * as ts from 'typescript';

const typeNode = ts.createVariableStatement(
    [], [ts.createVariableDeclaration(
            'a',
            ts.createFunctionTypeNode(
                [], [ts.createParameter([], [], undefined, 'hello')],
                ts.createKeywordTypeNode(ts.SyntaxKind.StringKeyword)))]);

const printer = ts.createPrinter({});

console.log(printer.printNode(
    ts.EmitHint.Unspecified, typeNode,
    ts.createSourceFile('', '', ts.ScriptTarget.ES5)));
```

**Expected behavior:**
Should output:
```ts
var a: (hello) => string;
```

**Actual behavior:**
```ts
var a: hello => string;
```

**Playground Link:** 

**Note**: This behavior is using the compiler API.

**Related Issues:** 
I couldn't find a related issue but I think the problem is an error in https://github.com/Microsoft/TypeScript/blob/master/src/compiler/emitter.ts#L2817

**Comment by ajafff** [comment]
I'm already working on a fix. Currently struggling with compiling master...
