### ISSUE TITLE
Return type inference of overloaded function when argument is known

### ISSUE THREAD

**Issue by KSXGitHub** [Microsoft/TypeScript#27027]
**TypeScript Version:**  3.0.3

**Search Terms:**

**Code**

```typescript
declare function fn(x: 'a'): 0
declare function fn(x: 'b'): 1
declare function fn(x: 'c'): 2
declare function fn(x: 'D'): 3

// expected: type One = 1
// received: type One = never
type One = (typeof fn) extends (x: 'b') => infer Return ? Return : never
const one: One = 1
```

**Expected behavior:**

`One` should be `1`

**Actual behavior:**

`One` is `never`

**Playground Link:** [link](https://www.typescriptlang.org/play/#src=declare%20function%20fn(x%3A%20'a')%3A%200%0D%0Adeclare%20function%20fn(x%3A%20'b')%3A%201%0D%0Adeclare%20function%20fn(x%3A%20'c')%3A%202%0D%0Adeclare%20function%20fn(x%3A%20'D')%3A%203%0D%0A%0D%0A%2F%2F%20expect%3A%20type%20One%20%3D%201%0D%0A%2F%2F%20received%3A%20type%20One%20%3D%20never%0D%0Atype%20One%20%3D%20(typeof%20fn)%20extends%20(x%3A%20'b')%20%3D%3E%20infer%20R%20%3F%20R%20%3A%20never%0D%0Aconst%20one%3A%20One%20%3D%201)

**Related Issues:** https://github.com/Microsoft/TypeScript/issues/26591

**Comment by RyanCavanaugh** [comment]
Overloads aren't resolved during inference (only the last is examined), nor are they expanded out combinatorially. In general for any given sequence of specific overloads like this there "should" be a final signature like `(x: 'a' | 'b' | 'c' | 'D'): 0 | 1 | 2 | 3`, which will be the one used during inference. This won't give you the *most* specific type, but would prevent hitting `never` here

**Comment by huan** [comment]
The "Example without conditional types" posted by @andy-ms is still true under TypeScript v4.4.4

I believe this is definitely typing system bug.
