### ISSUE TITLE
Show exact error position in arrays & arrow functions

### ISSUE THREAD

**Issue by cevek** [Microsoft/TypeScript#27030]
If it is not assignable error and infered expression type origin comes from inside of ast error boundaries we can show exact position of an error source

```ts

interface Foo {
    a: number;
}

function foo1(): () => Foo {
    return () => ({a: ''});
}

function foo2(): Promise<Foo> {
    return Promise.resolve({a: ''});
}

function foo3(): Foo[] {
    return [{a: ''}];
}
var y: Foo[] = [{a: ''}] 
var z: Foo[] = [].map(() => ({a: ''}))


```

![agdagag](https://user-images.githubusercontent.com/3171573/45378345-a0510480-b616-11e8-9cbe-7bce01c86b2a.jpg)

@DanielRosenwasser what do you think?

**Comment by DanielRosenwasser** [comment]
This can get arbitrarily complex, but I think that for certain arrays and arrow functions, we can definitely do better here.

**Comment by DanielRosenwasser** [comment]
Specifically I can see us dealing with `foo1`, `foo3`, and `y` pretty easily. I think that `foo2` and `z` will be harder.

**Comment by DanielRosenwasser** [comment]
I think that the majority of work done has been done here; the `Promise.resolve` case is a little harder, but if it's compelling enough for your day-to-day coding I encourage you to open up another issue. Thanks @cevek!
