### ISSUE TITLE
Option for tsc to ignore unknown compiler options

### ISSUE THREAD

**Issue by Serjster** [Microsoft/TypeScript#27038]
This is a continuation of the now closed issue:
https://github.com/Microsoft/TypeScript/issues/19294

**TypeScript Version:**  3.0.3

**Search Terms:**
vs 2017 Unknown compiler option 'composite'

**Code**
```
{
  "compilerOptions": {
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "inlineSourceMap": true,
    "inlineSources": true,
    "module": "system",
    "moduleResolution": "node",
    "noEmitOnError": true,
    "noEmit": false,
    "noImplicitAny": false,
    "outDir": "wwwroot/js",
    "removeComments": false,
    "target": "es5",
    "typeRoots": [ "./node_modules/@types" ],

    "composite": true,
    "declaration": true
  },
  "references": [
    { "path": "../My.App.Web" }
  ],
  "exclude": [
    "node_modules",
    "wwwroot",
    "bin",
    ".nuget"
  ]
}
```

**Expected behavior:**
I am trying to use this in Visual Studio 2017, however since there isn't a package for VS2017 to use Typescript 3+, these compiler options are not available, preventing me from building the project, even though it is actually correct.

My typescript is valid and when I run `TSC` in the command line the typescript compiles successfully, however, I am now unable to build in VS 2017 because the latest that I can find is version 2.9.2:
https://marketplace.visualstudio.com/items?itemName=TypeScriptTeam.typescript-292-vs2017

and since that version doesn't have the compiler options that I need to reference other projects, I am now unable to build in VS even though nothing is technically wrong.

There should be some way to tell typescript to ignore unknown compiler options for similar future cases. Perhaps an immediate fix for my particlar problem is to release a package for VS with v3 of typescript.

**Comment by Serjster** [comment]
Basically, I need to get rid of these errors in VS 2017:
![tsc](https://user-images.githubusercontent.com/3606218/45390327-053b3900-b5dc-11e8-9ef5-d641d06e337b.png)

**Comment by Serjster** [comment]
Based on more digging, adding 
`<TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>`

to the `<PropertyGroup>` of the `csproj` file allowed me to build the project in VS

**Comment by snice** [comment]
How to solve in VS Code ?
