### ISSUE TITLE
Methods labeled as properties when defined by assigning earlier-defined function to prototype

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#27037]
_From @JobLeonard on September 11, 2018 14:34_

- VSCode Version: 1.27.1
- OS Version: Linux

![image](https://user-images.githubusercontent.com/259840/45366431-1df91e00-b5df-11e8-9faf-fec05344da20.png)

![image](https://user-images.githubusercontent.com/259840/45365884-ca3a0500-b5dd-11e8-8aa8-c76499dd56cd.png)

## Steps to Reproduce

Create a JavaScript file with the following code:

```JavaScript
function A(){
    this.test = "`this` is bound to the right object";
}

A.prototype.aMethod = function(){
    return "this is a method";
};

const someFunction = function(){ 
    return this.test; 
};

A.prototype.aProperty = someFunction;

const a = new A();

a.aProperty(); // ==> "`this` is bound to the right object"
```

_Copied from original issue: Microsoft/vscode#58439_

**Comment by mjbvz** [comment]
Another similar example:

```js
class Foo {
    bar = function() { }

    car() {}
}
```

I believe we discussed this before in #25062

**Comment by RyanCavanaugh** [comment]
This is just a description of some code that exists, not a bug report? I don't understand what the expected behavior is.

**Comment by mjbvz** [comment]
The request is to treat function properties as methods:

![screen shot 2019-03-07 at 10 57 03 am](https://user-images.githubusercontent.com/12821956/53981638-ccca7280-40c7-11e9-9859-742de5939e16.png)

This shows up in the navTree and in suggest and is something that we keep seeing reported against VS Code

**Comment by RyanCavanaugh** [comment]
There are two equally-valid ways of interpreting this:
 * Methods are callable, properties are not
 * Methods are on the prototype, properties are own

I don't have a principled way to resolve this, but would note that prototype methods are always subject to `this` context loss, so showing the difference as it is today seems fairly valuable from a safety perspective.

**Comment by JobLeonard** [comment]
I don't think I quite follow:

> There are two equally-valid ways of interpreting this:
> 
> - Methods are callable, properties are not
> - Methods are on the prototype, properties are own

Shouldn't the `aProperty` in my example should be interpreted as a method no matter which of these two ways we pick, since we are talking about a function assigned to the prototype?

> I don't have a principled way to resolve this, but would note that prototype methods are always subject to `this` context loss, so showing the difference as it is today seems fairly valuable from a safety perspective.

It think you are suggesting that there are all-else-being-equal cases where `aMethod` would behave differently from `aProperty`, but I'm not seeing how. Could you elaborate?
