### ISSUE TITLE
Property does not exist on type 'never' reported when it shouldn't

### ISSUE THREAD

**Issue by hanginwithdaddo** [microsoft/TypeScript#27041]
**TypeScript Version:**  3.0.3

**Search Terms:**
property does not exist on type 'never'

The code fragment below without any changes produces the following error when
using TypeScript 3.0.3/TSLint 5.11.0:

(44,47): Property 'b' does not exist on type 'never'.
Replacing the "if isNotDefined(options)" line in ClassB.modify() with either of the lines above it that are commented out stops this error from appearing.

Code fragment:
```
export function myIsDefined<T>(value: T | undefined | null): value is T {
  return <T>value !== undefined && <T>value !== null;
}

export function myIsNotDefined<T>(value: T | undefined | null): value is T {
	return <T>value === undefined || <T>value === null;
}

export interface ClassAModifyResult {
	a: boolean
}

export interface ClassBModifyResult extends ClassAModifyResult {
	b: boolean
}

export class ClassA {
	constructor(options?: any) {
		this.modify(options);
	}

	public modify(options?: any): ClassAModifyResult {
		var result = {} as ClassAModifyResult;
		if ( myIsNotDefined(options) )
			return result;

		result.a = true;
		return result;
	}
}

export class ClassB extends ClassA {
	constructor(options?: any) {
		super(options);
	}

	public modify(options?: any): ClassBModifyResult {
		// if ( !myIsDefined(options) )
		// if ( options === undefined || options === null )
		if ( myIsNotDefined(options) )
			return {} as ClassBModifyResult;

		var result = super.modify(options) as ClassBModifyResult;
		result.b = this._modifyBIfNecessary(options.b);
		return result;
	}

	protected _modifyBIfNecessary(value?: boolean): boolean {
		return true;
	}
}
```
I have seen other cases where using a method like myIsNotDefined() causes other issues for either TypeScript or TSLint.

Example:
```
	someMethod(value?: any | null): void {
		if ( myIsNotDefined(value) )
			return;

		if ( value.member === 'abc' )
			doSomething();
	}
```
With the code fragment above an error may appear stating that 'value' maybe undefined or null at the line that reads "if ( value.member === 'abc' )". Replacing the call to 'myIsNotDefined(value)' with either '!myIsDefined(value)' or 'value === undefined || value === null' stops the error from appearing.

**Comment by AlCalzone** [comment]
I think the problem is your definition of `myIsNotDefined`, specifically the return type (`options is T`) in combination with `any`.
```
if ( myIsNotDefined(options) ) {
    // Here, options is any
    return {} as ClassBModifyResult;
}
// Here, options is whatever remains after excluding any from the type, which results in never
```
When you define the function argument differently, the error changes.

**Comment by hanginwithdaddo** [comment]
Something to note... we cannot use methods like isDefined()/isNotDefined() anyway. Code like the following reports "Object is possibly null" on the line that starts with 'var match =', even though we've effectively ensured that computedStyle and computedStyle.color are both defined. I don't know if this is a compiler issue or just an artifact of TypeScript.
```
	var computedStyle = window.getComputedStyle(someElement);
	if ( isDefined(computedStyle) && isDefined(computedStyle.color) )
	{
		var match = computedStyle.color.match(/\d+/g);
		if ( isDefined(match) )
		{
		    . . .
		}
	}
```

**Comment by AlCalzone** [comment]
This works on the playground with strictNullChecks: 
```ts
function isDefined<T>(a: T | null | undefined): a is T {
	return a !== null && a !== undefined;
}

function foo() {
	var a = window.getComputedStyle(null as any);

	if (isDefined(a) && isDefined(a.color)) {

		var match = a.color.match(/\d+/g);

		match[0]; // Error: Object is possibly null
		if (isDefined(match)) {
			match[0]; // works
		}
	}
}
```

**Comment by hanginwithdaddo** [comment]
... correct ... the isDefined() approach works, its just the isNotDefined() which is not working... sorry.

**Comment by hanginwithdaddo** [comment]
I misunderstood the use of type guards. Closing this ticket.

**Comment by AlCalzone** [comment]
isNotDefined also works if you don't combine it with ||:
```ts
function isNotDefined<T>(a: T | null | undefined): a is (null | undefined) {
	return a !== null && a !== undefined;
}

function foo() {
    var a = window.getComputedStyle(null as any);

    // works:
    if (isNotDefined(a)) {
        a; // null
    } else if (isNotDefined(a.color)) {
        a.color; // null
    }

    // doesn't work!
    if (isNotDefined(a) || isNotDefined(a.color)) {
        a; // CSSStyleDeclaration
        a.color; // string
    }
}
```
I'm not sure if that is a design limitation or a bug, since it is the exact opposite check of `isDefined(a) && isDefined(a.color)`.

**Comment by hanginwithdaddo** [comment]
That is odd. Thanks for the additional notes. I'm just using isDefined() and !isDefined().

**Comment by AlCalzone** [comment]
@RyanCavanaugh while the original post seems to be a question, what about the behavior in https://github.com/Microsoft/TypeScript/issues/27041#issuecomment-420769327? Is that a bug or limitation somehow?
