### ISSUE TITLE
Index signature lost with empty intersections

### ISSUE THREAD

**Issue by poseidonCore** [Microsoft/TypeScript#27044]
**TypeScript Version:**  3.0.1 [TS Playground @ 12 SEP 2018]

**Search Terms:**
Index signature lost 
inconsistent intersections
empty intersections

**Code**
This is a dumbed-down version of what I have experienced.

Whenever 2 empty-object types are merged, the assumption of a type signature is lost.

```ts
type choices<IChoiceList extends {
    [key: string]: boolean;
}> = IChoiceList & {
    shoes:boolean;
    food:boolean;
};

type IMyChoiceList = {
    car: true
};

type IUnknownChoiceList = {};

var defaultChoices: choices<{}>;
var defaultChoicesAndEmpty: choices<{} & {}>;
/*
Type '{}' does not satisfy the constraint '{ [key: string]: boolean; }'.
  Index signature is missing in type '{}'.
*/

var myChoices: choices<IMyChoiceList>;
var myChoicesAndEmpty: choices<IMyChoiceList & {}>;

var unknownChoices: choices<IUnknownChoiceList>;
var unknownChoicesAndEmpty: choices<IUnknownChoiceList & {}>;
/*
Type '{}' does not satisfy the constraint '{ [key: string]: boolean; }'.
*/

```

**Expected behaviour:**
If `{}` is assumed to have a compliant type signature, then surely `{} & {}` should have the same.

**Actual behaviour:**
Whenever 2 empty-object types are merged, the assumption of a type signature is lost.
Errors commented above are for the single line of code above them.

**Playground Link:**
[TS Playground](https://www.typescriptlang.org/play/#src=type%20choices%3CIChoiceList%20extends%20%7B%0D%0A%20%20%20%20%5Bkey%3A%20string%5D%3A%20boolean%3B%0D%0A%7D%3E%20%3D%20IChoiceList%20%26%20%7B%0D%0A%20%20%20%20shoes%3Aboolean%3B%0D%0A%20%20%20%20food%3Aboolean%3B%0D%0A%7D%3B%0D%0A%0D%0Atype%20IMyChoiceList%20%3D%20%7B%0D%0A%20%20%20%20car%3A%20true%0D%0A%7D%3B%0D%0A%0D%0Atype%20IUnknownChoiceList%20%3D%20%7B%7D%3B%0D%0A%0D%0Avar%20defaultChoices%3A%20choices%3C%7B%7D%3E%3B%0D%0Avar%20defaultChoicesAndEmpty%3A%20choices%3C%7B%7D%20%26%20%7B%7D%3E%3B%0D%0A%2F*%0D%0AType%20'%7B%7D'%20does%20not%20satisfy%20the%20constraint%20'%7B%20%5Bkey%3A%20string%5D%3A%20boolean%3B%20%7D'.%0D%0A%20%20Index%20signature%20is%20missing%20in%20type%20'%7B%7D'.%0D%0A*%2F%0D%0A%0D%0Avar%20myChoices%3A%20choices%3CIMyChoiceList%3E%3B%0D%0Avar%20myChoicesAndEmpty%3A%20choices%3CIMyChoiceList%20%26%20%7B%7D%3E%3B%0D%0A%0D%0Avar%20unknownChoices%3A%20choices%3CIUnknownChoiceList%3E%3B%0D%0Avar%20unknownChoicesAndEmpty%3A%20choices%3CIUnknownChoiceList%20%26%20%7B%7D%3E%3B%0D%0A%2F*%0D%0AType%20'%7B%7D'%20does%20not%20satisfy%20the%20constraint%20'%7B%20%5Bkey%3A%20string%5D%3A%20boolean%3B%20%7D'.%0D%0A*%2F%0D%0A)

**Related Issues:** 
`Identity: A & A is equivalent to A.` [#3622](https://github.com/Microsoft/TypeScript/pull/3622)

**Comment by poseidonCore** [comment]
This appears to be directly related to https://github.com/Microsoft/TypeScript/issues/20225

**Comment by RyanCavanaugh** [comment]
@ahejlsberg looks like the index signature check needs to be distributive over intersection types?
