### ISSUE TITLE
Cannot invoke signature help in or adjacent to block body

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#27056]
Apparently a long-standing issue, discovered from experimenting with signature help characters

```ts
declare function foo(...args);

foo(() => {/*1*/}/*2*/)
```

At each position, explicitly request signature help.

**Expected**: Signature help.
**Actual**: No signature help.

Ideally, we'd check whether the trigger reason was that signature help was a manual invocation, and keep walking up if so.

**Comment by sbaidon** [comment]
I would love to help in this, unfortunately I have no previous experience in the repo, might need some guidance

**Comment by DanielRosenwasser** [comment]
Sure! A few things.
 
1. You'll want to edit `src/services/signatureHelp.ts` and check for the right trigger reason (`"invoked"`).
1. Use whether or not `"invoked"` was passed in in the `getContainingArgumentInfo` function.
1. Write tests in `tests/cases/fourslash/`. [See here](https://github.com/Microsoft/TypeScript/pull/24915) for some tests.
1. The fix for this only works in VS Code Insiders (and internal builds of Visual Studio. Get yourself a copy [here](https://code.visualstudio.com/insiders/) if you want to test that things are indeed working. You can trigger signature help with `Ctrl+Shift+Space` or probably `Cmd+Shift+Space` on Mac.

**Comment by sbaidon** [comment]
Thanks! Will try to get a PR ASAP

**Comment by sbaidon** [comment]
Okay I think I have a working solution, I just got confused how could I test it on VS Code Insiders?
