### ISSUE TITLE
Type parameter should not be assumed truthy

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#27050]
**TypeScript Version:**  3.1.0-dev.20180912

**Code**

```ts
function f<T extends string | undefined>(x: T): number {
    return x && 42;
}
f(undefined).toFixed();
```

**Expected behavior:**

Error -- the output may be `""` or `undefined`.

**Actual behavior:**

No error. (Error at runtime.)

**Comment by niazlake** [comment]
Could you explain more how can fix this and try to understand for me.

**Comment by andy-ms** [comment]
I don't know how to fix this, but we'll likely have a fix in a few months since this was assigned to the ts3.2 milestone.

**Comment by ahejlsberg** [comment]
I'm going to mark this a duplicate of #22348. We need the ability to express "the falsy parts of `T`" in higher order form.
