### ISSUE TITLE
quick fix for special add missing type declaration

### ISSUE THREAD

**Issue by Kingwl** [Microsoft/TypeScript#27067]
## Search Terms
quick fix

## Suggestion
add special type declaration for missing type in function context and left of dot is a parameter

## Use Cases

it's useful for extract some common logic to another function with minimal depend
or add a new refactor to do that?

## Examples

```ts
interface A {
    foo: number
}

function bar (a: A) {
    a.foo
    a.bar // error
}
```

to 

```ts
interface A {
    foo: number
}

function bar (a: A & { bar: unknow }) {
    a.foo
    a.bar
}
```

or

```ts
function bar (a) {
    a.foo // error
    a.bar // error
}
```

to 

```ts
function bar (a: { foo: any, bar: any }) {
    a.foo
    a.bar
}
```

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by RyanCavanaugh** [comment]
We can only really have a finite number of refactors and adding an intersection doesn't seem like the kind of thing we'd want to offer as a "fix" - this is very rarely what you intend to do.

The unannotated case is being tracked separately.
