### ISSUE TITLE
Bug: Typescript compiler is confused between Tuple literal and Array Literal

### ISSUE THREAD

**Issue by wongjiahau** [Microsoft/TypeScript#27074]
**Expected behavior:**

No error

**Actual behavior:**

Type error.

**Playground Link:** 

http://www.typescriptlang.org/play/#src=interface%20OK%3CT%3E%20%7B%0D%0A%20%20%20%20kind%3A%20%22OK%22%3B%0D%0A%20%20%20%20value%3A%20T%3B%0D%0A%7D%0D%0Aexport%20function%20ok%3CT%3E(value%3A%20T)%3A%20OK%3CT%3E%20%7B%0D%0A%20%20%20%20return%20%7B%0D%0A%20%20%20%20%20%20%20%20kind%3A%20%22OK%22%2C%0D%0A%20%20%20%20%20%20%20%20value%3A%20value%0D%0A%20%20%20%20%7D%3B%0D%0A%7D%0D%0A%0D%0Alet%20result%3A%20OK%3C%5Bstring%2C%20number%5D%3E%20%3D%20ok(%5B%22hello%22%2C%2012%5D)%3B

**Related Issues:**

**Comment by andy-ms** [comment]
Duplicate of  #11152 -- the problem is that annotating the result as `OK<[string, number]>` has no effect in the inferred type argument. `let result = ok<[string, number]> (["hello", 12]);` would work though.
