### ISSUE TITLE
Function argument with void type should be optional.

### ISSUE THREAD

**Issue by michaeljota** [Microsoft/TypeScript#27077]
**TypeScript Version:**  3.1.0-dev.201xxxxx

**Search Terms:**

- parameters void optional 
- parameters with void type should be optional 

**Code**

```ts
function a(b: void): void {
    return;
}

a();
```

**Expected behavior:**

There is only one possible value that you could pass to a void parameter, `undefined`. As it is the last argument, it should be optional.

**Actual behavior:**

Throws: `Expected 1 arguments, but got 0.`

**Playground Link:** 

[Link](http://www.typescriptlang.org/play/#src=function%20a(b%3A%20void)%3A%20void%20%7B%0D%0A%20%20%20%20return%3B%0D%0A%7D%0D%0A%0D%0Aa()%3B%0D%0A)

**Related Issues:**

**Comment by jack-williams** [comment]
Related and/or duplicate? #4260

**Comment by michaeljota** [comment]
It is. Thanks.
