### ISSUE TITLE
Matching line numbers

### ISSUE THREAD

**Issue by streamich** [Microsoft/TypeScript#2708]
Could you transpile TypeScript such that the resulting JavaScript line numbers would match? Just like React's JSX is doing.

**Comment by mhegazy** [comment]
This may be possible with simple code transformations, not all transformations are guaranteed to match in length. for instance wrapping the whole file in a function to emit in an AMD module would not be possible. 

[SourceMaps](https://github.com/ryanseddon/source-map/wiki/Source-maps%3A-languages,-tools-and-other-info) is a the general solution. you get a .map file along with your .js output that tells your debugger for instance where the line in the .js file came from in the .ts file.

you get source maps by passing --sourceMap to your ts compiler. all modern browsers, and debuggers do support consuming them.
