### ISSUE TITLE
JSDoc typed class doesn't provide intellisence when extended

### ISSUE THREAD

**Issue by RomainLanz** [Microsoft/TypeScript#27104]
**TypeScript Version:**  3.1.0-dev.20180907

**Search Terms:** extends, class, intellisence, jsdoc

**Code**

```js
class B {
  bar () {}
}

module.exports = B

```

```js
/** @type {import('./ClassB')} */
const B = JSON.parse("")

class A extends B {
  foo () {
    // this. doesn't provide the Bar method.
  }
}
```

Repo to reproduce: https://github.com/RomainLanz/extends-type

**Expected behavior:**

When I type `this.` in `A.prototype.foo`, I expect to see the `bar` method from the class `B`.

**Actual behavior:**

Only `foo` is shown.

**Comment by RomainLanz** [comment]
Thank you @andy-ms, it works perfectly now!

If I may use this issue to ask a relative question.

```js
// No Intellisence

/** @typedef {typeof import('@adonisjs/lucid/src/Lucid/Model')} Model */

/** @type {Model} */
const Model = use('Model')
```

```js
// Intellisense

/** @type {typeof import('@adonisjs/lucid/src/Lucid/Model')} */
const Model = use('Model')
```

If I activate `"checkJs": true` it tells me that `Model` is already referenced indirectly but even by removing the `@type` it doesn't work.

**Comment by andy-ms** [comment]
What error is this? I can't reproduce that with just the code you shared, could you try to get an isolated repro?

**Comment by RomainLanz** [comment]
I tried to replicate in the repository I gave above but it was working fine.

This repository reproduce the issue: https://github.com/RomainLanz/extends-model
Please, check the file `app/Models/Token.js`

**Comment by andy-ms** [comment]
@RomainLanz Thanks, filed an issue: #27110

**Comment by RomainLanz** [comment]
Nice!

Could you explain to me why I have no issue in [this one](https://github.com/RomainLanz/extends-type/blob/master/ClassA.js#L8)?

It seems it is the same code. 🤔

**Comment by andy-ms** [comment]
The class isn't exported, apparently the issue only reproduces if it is.

**Comment by RomainLanz** [comment]
Alright, looking forward to this to be fixed.
Thanks again for your time!
