### ISSUE TITLE
Conditionally defined properties on functions should be considered optional

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#27101]
```ts
function readFile() {
}

if (Math.random()) {
  readFile.sync = () => {}
}

readFile.sync();
```

**Expected**: `readFile.sync` has the type `(() => void) | undefined` and it is an error to call it.
**Actual**: `readFile.sync` has the type `() => void` and there is no error present.

**Comment by sandersn** [comment]
Note that if the property is definitely assigned there should be no error:

```ts
function readFile() { }
if (Math.random()) {
  readFile.sync = () => {}
}
else {
  readFile.sync = 'was'
}
readFile.sync.length
```

So the full fix needs control flow from the container object.

**Comment by weswigham** [comment]
> So the full fix needs control flow from the container object.

Less the containing object and more from the start of where the reference becomes available 😛 
```ts
if (Math.random()) {
  readFile.sync = () => {}
}
else {
  readFile.sync = 'was'
}
readFile.sync.length
function readFile() { } // function declarations are hoisted, so this is fine
```
