### ISSUE TITLE
Issue with overloaded function with a generic

### ISSUE THREAD

**Issue by MayhemYDG** [Microsoft/TypeScript#27111]
**TypeScript Version:**  3.0.3, I tried typescript@next but it crashed.

**Search Terms:**
generic overload

**Code**

```ts
function toNum(input: string): number;
function toNum<T>(input: T): T;
function toNum(input: unknown) {
    if (typeof input !== 'string') {
        return input;
    }
    return Number(input);
}

function getValue(): number | string {
    return 'aaa';
}

function test(input: number) {}

test(toNum("str"));
test(toNum(123));
test(toNum(getValue()));
```

**Expected behavior:**
If you pass a `string` to `toNum`, you'll get a `number`.
If you pass a `number` to `toNum`, you'll get a `number`.
If you pass a `number | string` to `toNum`, you'll get a `number`.

**Actual behavior:**
If you pass a `number | string` to `toNum`, you'll get a `number | string`.

This can be fixed by changing `function toNum(input: string): number;` to `function toNum(input: string | number): number;` but I don't think it should be necessary.

**Playground Link:** 
https://www.typescriptlang.org/play/#src=function%20toNum(input%3A%20string)%3A%20number%3B%0D%0Afunction%20toNum%3CT%3E(input%3A%20T)%3A%20T%3B%0D%0Afunction%20toNum(input%3A%20unknown)%20%7B%0D%0A%20%20%20%20if%20(typeof%20input%20!%3D%3D%20'string')%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20input%3B%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20return%20Number(input)%3B%0D%0A%7D%0D%0A%0D%0Afunction%20getValue()%3A%20number%20%7C%20string%20%7B%0D%0A%20%20%20%20return%20'aaa'%3B%0D%0A%7D%0D%0A%0D%0Afunction%20test(input%3A%20number)%20%7B%7D%0D%0A%0D%0Atest(toNum(%22str%22))%3B%0D%0Atest(toNum(123))%3B%0D%0Atest(toNum(getValue()))%3B

Am I doing something wrong? I'm not sure how to search for that kind of bug.

**Comment by RyanCavanaugh** [comment]
This is the intended behavior; when you write
```
function toNum<T>(input: T): T;
```
This says "If passed e.g. `string | number`, then *return* `string | number`". TypeScript has no way to know that you instead want to just return `number` here.

**Comment by MayhemYDG** [comment]
@RyanCavanaugh 
>TypeScript has no way to know that you instead want to just return `number` here.

But it does with
```ts
function toNum(input: string): number;
```
I think TypeScript should be able to compute all the various possible input-output combinations, so it can understand that, given
```
input string -> output number

input T(number) -> output T(number)

input T(string | number)
  = (input string -> output number | input T(number) -> output T(number))
  = input T(string | number) -> output number
```
It doesn't sound impossible to me that TS could figure out what all the possible combinations are, and deduct the most accurate return type.
For example `toNum<string | number | null>(value)` should return with the type `number | null`.
Am I missing something?
