### ISSUE TITLE
Add RTP media API extensions to the RTCPeerConnection interface

### ISSUE THREAD

**Issue by zoonman** [microsoft/TypeScript#27122]
Reference https://w3c.github.io/webrtc-pc/#rtcpeerconnection-interface-extensions

The `tsc` output
```
error TS2339: Property 'getReceivers' does not exist on type 'RTCPeerConnection'.
```

The file `node_modules/typescript/lib/lib.dom.d.ts` doesn't contain RTP media API extensions therefore getReceivers() method doesn't work and causes failures.

**Comment by zoonman** [comment]
Installing `@types/webrtc` fixed the issue but feels like a hack.

**Comment by RyanCavanaugh** [comment]
We don't include experimental APIs in the built-in DOM definitions so that people don't accidently take dependencies on things that aren't widespread yet.
