### ISSUE TITLE
Enable/Disable --allowJs for a few lines

### ISSUE THREAD

**Issue by SephReed** [Microsoft/TypeScript#27123]
## Search Terms

--allowJs, allowJs

## Suggestion

The ability to allowJs for some amount of lines, similar to `tslint:disable...` but not for specific linting, instead just allowing any valid js to be used.

## Use Cases

Often times Typescript makes certain javascript functionality impossible.  In every one of these cases the decision is very well thought out, but rarely perfectly without exception.  In the broad sense, those are the use cases: times at which you'd like to be able to write valid javascript regardless of what typescript thinks you should do.

Also, it could help a lot for moving js over to typescript.  Being able to update copy a js file into a ts one, set all the lines to `allowJs`, and then slowly narrow the band of `allowJs` as you update the file.

## Examples

The instigating example I'm currently facing is the need to not call super() in a constructor.  I would like to be able to use a coding technique called evolutions in which you extend a class after its creation.  This is how it might look:
```
class SuperEvent extends Event {
  public superHeroIdentity: string;

  constructor(event: Event) {
    // allow Js for next line
    // allowJs:1
    if (false) { super(); }
    (event as any).superHeroIdentity = "Megavent";
    return event;
  }
}

const boringEvent = new Event("doThing").
const superEvent = new SuperEvent(boringEvent);
console.log(superEvent); // Megavent
```

## Potential Downsides

Doing the above blatantly makes for a fair amount of nonsense.  I'm not really on the Typescript development team so my understanding of how hard/easy something is means nothing.  It really comes down to luck most of the time anyways, exceptions being so unpredictable.  Never the less, I think it would behoove you to find a way to let users write any and all valid javascript.  It's undeniable that giving users a way to opt out of ts not only shows respect, but shows an acknowledgement of all persons inherit fallibility.  Also, as long you aren't essentially getting in peoples way, they really shouldn't have anything to complain about.

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by yortus** [comment]
Have you tried [`// @ts-ignore`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-6.html#suppress-errors-in-ts-files-using--ts-ignore-comments)?

**Comment by RyanCavanaugh** [comment]
`eval` ? 😈 

ts-ignore is indeed exactly what you're asking for
