### ISSUE TITLE
No index signature for object with clear index signature

### ISSUE THREAD

**Issue by ORESoftware** [Microsoft/TypeScript#27127]
## Search Terms

index signature

## Suggestion

Looking for inference for objects with clear type/index signatures.

## Use Cases

TS does not / cannot infer index signature for plain objects.

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by ORESoftware** [comment]
fuck this is wrong nvm

**Comment by ORESoftware** [comment]
Actually this issue is real, the problem was that the above wasn't an example of it. The following is my biggest gripe with TS (and I love TS), say we have this object:

```js
'use strict';

export const servicesMap = {

  'account-service': {
    count: 1
  },

  'cancellation-service': {
    count: 1
  },

  'integrator-service': {
    count: 1
  },

  'notification-service':{
    count: 1
  }
};
```

tsc will say there is no index signature for the object. How can that be? It's statically available and isn't changing - so why can't TS infer the index signature?

**Comment by ORESoftware** [comment]
We can do this:

```js
export type ServicesMap = {
  [key: string]: {
    count: number
  }
}

export const servicesMap : ServicesMap = {...}
```

but (a) that is more work than necessary it seems, and more importantly (b), we lose auto-complete, because tsc no longer recognizes the hardcoded keys in the original object...

**Comment by RyanCavanaugh** [comment]
> tsc will say there is no index signature for the object. How can that be? It's statically available and isn't changing - so why can't TS infer the index signature?

All you're saying here is that every object should have an index signature, but this is not the common practice of how objects work, and effectively makes index signatures meaningless.

The problem here is that `s` has the wrong type. If `s` had the type `keyof typeof servicesMap`, then there wouldn't be an error, because TS knows that the keys are constrained to known properties.

This and the problem of how to annotate an object for mixed initialization/type hinting both have many open issues; #7481 is a place to start

**Comment by ORESoftware** [comment]
In this case `s` had the right type and I even tried casting to string like this:

```js
const count = servicesMap[s as string].count;
```

and I still got the same thing

**Comment by ORESoftware** [comment]
@RyanCavanaugh  You say indexing every object is not currently done or not doable (perhaps too expensive). How about something like this:

```js
'use strict';

export const servicesMap = <asis>{

  'account-service': {
    count: 1
  },

  'cancellation-service': {
    count: 1
  },

  'integrator-service': {
    count: 1
  },

  'notification-service':{
    count: 1
  }
};
```

using the `<asis>` type says the object is what it is, and as long as the keys/values are consistent then that is the index. It's clear from the object above that the keys are strings and the values are:

`{count: number}`

what am I missing here?
