### ISSUE TITLE
TSC not find imported scoped packages.

### ISSUE THREAD

**Issue by rbiggs** [Microsoft/TypeScript#27126]
**TypeScript Version:**  TS6029: Version 1.5.3

**Search Terms:** import scoped packages

**Code**

In my `package.json` I have
```javascript
"checkjs": "tsc --allowJs --checkJs --noEmit --target ES6 src/*.js"
```

**Expected behavior:**
I'm using NPM scoped packages: https://docs.npmjs.com/misc/scope.
For normal ES6 imports TSC correctly resolves imported packages and parses the results. Scoped
Scoped packages look like this:

```javascript
import {getType} from '@composi/get-type'
```
The scope is basically an NPM namespace to prevent collision of package names.

**Actual behavior:**
TSC fails to find the packages. Here's the error message I'm getting:

```bash
 npm run checkjs
> tsc --allowJs --checkJs --noEmit --target ES6 src/*.js

src/vdom.js:2:23 - error TS2307: Cannot find module '@composi/merge'.

2 import { merge } from '@composi/merge'
                        ~~~~~~~~~~~~~~~~
src/vdom.js:3:25 - error TS2307: Cannot find module '@composi/get-type'.

3 import { getType } from '@composi/get-type'
```
<img width="731" alt="screen shot 2018-09-15 at 8 10 02 pm" src="https://user-images.githubusercontent.com/249218/45592547-87ea2e00-b925-11e8-8650-c8fa42a79409.png">

Rollup and Babel 7.0.0 have no problem with import of scoped packages.

**Comment by rbiggs** [comment]
Here's a simple repository on Github that illustrates the project. Download, run `npm install`. Then try to run TypeScript type checking on the JavaScript using `npm run checkjs`.

https://github.com/rbiggs/scope-package-test

**Comment by rbiggs** [comment]
Interestingly, VSCode seems to have no problem resolving the path for scoped packages:

<img width="731" alt="screen shot 2018-09-15 at 8 52 25 pm" src="https://user-images.githubusercontent.com/249218/45592694-6b4ff500-b929-11e8-94cc-8e58cd62168e.png">

**Comment by kitsonk** [comment]
Version 1.5.3 is from May 2015.  VSCode uses a much newer version than that.  Is the version correct?

**Comment by rbiggs** [comment]
I updated the project to TypeScript 3.0.3 and the same issue occurs.

<img width="722" alt="screen shot 2018-09-16 at 5 57 22 am" src="https://user-images.githubusercontent.com/249218/45596736-6ca70f00-b975-11e8-8bb4-83d15a497b2f.png">

**Comment by mattmccutchen** [comment]
You need to set `--moduleResolution node`.  `--moduleResolution` defaults to `classic` when your target is `es6` and `node` when your target is the default `es3`.  See the [Compiler Options](https://www.typescriptlang.org/docs/handbook/compiler-options.html) handbook page for more information.  It's highly recommendable to put your TypeScript options in a `tsconfig.json` file so you can easily share them between your IDE and your batch build to avoid inconsistencies like this.

**Comment by rbiggs** [comment]
Thanks @mattmccutchen. That seems to be what was the problem. With the `--moduleResolution node` flag, the tsc check is running fine. Closing this now.
