### ISSUE TITLE
Use keyof and typeof with dictionary of object arrays, not work.

### ISSUE THREAD

**Issue by Jiasm** [Microsoft/TypeScript#27132]
**TypeScript Version:**  3.0.3

**Search Terms:** `keyof`,`typeof`,`dynamic key`

**Code**

```ts
type testTypeWithIssues = {
  [k: string]: any
}

const map1: testTypeWithIssues = {
  a: '1',
  b: '2',
}

const map2 = {
  a: '1',
  b: '2',
}

// No Error in there.
const test1: keyof typeof map1 = 'c'

// Error: Type '"c"' is not assignable to type '"a" | "b"'.
// This is in line with expectations
const test2: keyof typeof map2 = 'c'
```

**Expected behavior:** Through error in `test1  decalre`

**Actual behavior:** No error in there.

**Playground Link:** [Playgroud Link](http://www.typescriptlang.org/play/#src=type%20testTypeWithIssues%20%3D%20%7B%0D%0A%20%20%5Bk%3A%20string%5D%3A%20any%0D%0A%7D%0D%0A%0D%0Aconst%20map1%3A%20testTypeWithIssues%20%3D%20%7B%0D%0A%20%20a%3A%20'1'%2C%0D%0A%20%20b%3A%20'2'%2C%0D%0A%7D%0D%0A%0D%0Aconst%20map2%20%3D%20%7B%0D%0A%20%20a%3A%20'1'%2C%0D%0A%20%20b%3A%20'2'%2C%0D%0A%7D%0D%0A%0D%0A%2F%2F%20No%20Error%20in%20there.%0D%0Aconst%20test1%3A%20keyof%20typeof%20map1%20%3D%20'c'%0D%0A%0D%0A%2F%2F%20Error%3A%20Type%20'%22c%22'%20is%20not%20assignable%20to%20type%20'%22a%22%20%7C%20%22b%22'.%0D%0A%2F%2F%20This%20is%20in%20line%20with%20expectations%0D%0Aconst%20test2%3A%20keyof%20typeof%20map2%20%3D%20'c')

**Related Issues:**  _no_

**Comment by AlCalzone** [comment]
`keyof typeof map1` is equal to `keyof testTypeWithIssues`, which is `string`. `'c'` is assignable to `string`, so no issue here.
