### ISSUE TITLE
Spec says nothing about destructuring assignment for rest elements

### ISSUE THREAD

**Issue by JsonFreeman** [microsoft/TypeScript#2713]
Section 4.17.1 (destructuring assignment) does not say what should happen if the assignment element E in an array assignment pattern is a rest element. It may be implied by something else in the spec, but it would be good to make it explicit.

**Comment by Steve-Fenton** [comment]
Hello,

Just to add to this one - it would be good to explicitly cover the combination of rest elements and renaming, for example:

```
const values = { a: "1", b: "2", c: "3", d: "4" };

const { a: one, ...other: twoThreeFour } = values;
```

In this case, there is no token for ```other``` - the name doesn't ever exist, only the renamed ```twoThreeFour``` variable. I don't know whether that would be something for the spec itself, or for the handbook.
