### ISSUE TITLE
Tuple suffix associated with rest element in a binding pattern

### ISSUE THREAD

**Issue by JsonFreeman** [Microsoft/TypeScript#2714]
You could imagine that someone had the following:
```ts
var tuple: [string, number] = ["", 0];
var [a, ...b] = tuple;
```

Right now, a is string, but b is `(string | number)[]`. This is because the type associated with b is the array of the element type of the incoming array.

But it would be really nice if b was `[number]`, or at least `number[]`. You should be able to chop off the rest of the elements in the incoming array, and only use those for the type associated with a rest element.

**Comment by RyanCavanaugh** [comment]
The idea as I understand it is that any spread operator assumes that "all of the rest of the values" are in the domain of the tuple-specified types.

e.g.
```ts
var tuple: [string, number] = ["", 0];
tuple.push(42); // ok
tuple.push('hello'); // ok
tuple.push(window); // err
var [a, ...b] = tuple; // desired: b: Array<string|number>
```
