### ISSUE TITLE
Language Plugin API: How to override a var type?

### ISSUE THREAD

**Issue by huafu** [microsoft/TypeScript#27153]
I'm trying to write a TS language service plugin for use with Jest:

```ts
// func: (v: string) => number
import func from 'some-module'
// jest inject test helpers here
jest.mock('some-module')
// call an injected helper:
func.mockClear()
```
This last line shows a diagnostic because `mockClear` doesn't exists on `typeof func`. What I want to achieve in my plugin is to override in memory the type of `func` so that it becomes `jest.Mock<typeof func>`.

- what method should I override in which the type upgrade should be done (I don't want to hard-code the completion list within `getCompletionAtPosition`, really need the type to be upgraded in-memory for the language service and other plugins)
- how to override the type (which helper should be used, if any)?

FYI I already have my code to find imports and calls to `jest.mock` related `Node`s. **I "just" need to know where and how to upgrade the type of a var.**

**Comment by RyanCavanaugh** [comment]
Language service plugins aren't capable of changing how the core typechecker works. A "type checker plugin model" is a separate beast we haven't tackled yet.

**Comment by huafu** [comment]
@RyanCavanaugh thanks for your quick answer. So what are my choices here and which would you advise me to take?

Also I don't know how you handle Question issues but I guess this can be closed then.

**Comment by RyanCavanaugh** [comment]
In this very specific case, I would just write (in a global .d.ts file)
```ts
interface Function {
  mockClear(): void;
}
```
to add `mockClear` to the global function type.

**Comment by huafu** [comment]
Thanks @RyanCavanaugh, but there are a bunch of helpers (not only mockClear) and that would pollute the whole completion in tests as well as in source files, which is not something users (and I) would want. I guess there would have to:
```ts
import _func from 'some-module'
jest.mock('some-module')
const func = _func as MyTypeUpgrader<typeof _func>
// ...
func.mockClear()
```
