### ISSUE TITLE
TSX React import defaults to "import =" syntax

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#27152]
_From @dontsave on September 17, 2018 17:52_

Currently when vscode auto-imports react into a TSX file (upon detecting JSX markup for example), it uses the `import React = require("react");` syntax, which is unsupported by babel's transform typescript plugin. The does not appear to be a way to change the import syntax to use `import * as React from 'react'` syntax.

- VSCode Version: 1.27.2
- OS Version: Windows 10

_Copied from original issue: Microsoft/vscode#58832_

**Comment by mjbvz** [comment]
_From @vscodebot[bot] on September 17, 2018 17:52_

(Experimental duplicate detection)
Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
- [Import suggestion suggesting import from @types folder (#54860)](https://www.github.com/Microsoft/vscode/issues/54860) 
- [Keeps opening all my files and imports node_modules from library cache (#54906)](https://www.github.com/Microsoft/vscode/issues/54906)

**Comment by mjbvz** [comment]
Tested with 3.1.0-rc-20180911. For a file:

```tsx
export const a = <div></div>
```

The quick fix on `div` adds `import React = require("react");` but for a reference to a missing symbol `React`, the quick fix adds `import React from "react"`

**Comment by andy-ms** [comment]
This seems to be working for me. I have an empty project with just `@types/react` installed, `tsconfig.json` of:
```json
{
    "compilerOptions": {
        "jsx": "react",
        "allowSyntheticDefaultImports": true
    }
}
```
and `src/a.tsx` containing `export const a = <div></div>;`. The import fix is for a default import. Tested in `typescript@3.1.1`, `typescript@3.1.3`, and `typescript@next`.

**Comment by aaroncraig10e** [comment]
Any word on a workaround or idea when it might be resolved for this?

It's consistently breaking builds, now, and requires that I often check imports (which may be sneakily inserted while typing, so not always obvious in the moment) before checking in code.

The `allowSyntheticDefaultImports` fix does not work for me.

**Comment by clayne11** [comment]
Auto-imports are 100% broken for me with the latest update to VSCode.

**Comment by andy-ms** [comment]
@clayne11 That sounds different -- please file a separate issue as soon as you have a way to reproduce it.
@aaroncraig10e We don't have a good repro for this issue yet. Could you share some sample code (`tsconfig.json` and a simple `a.tsx`) that reproduces the issue in `typescript@next`?
