### ISSUE TITLE
jake runtests-browser doesn't work

### ISSUE THREAD

**Issue by iliashkolyar** [microsoft/TypeScript#27154]
**TypeScript Version:** master

**Search Terms:**
runtests-browser

**Code**

```ts
> jake runtests-browser
jake aborted.
Error: Unknown task "runtests-browser"
    at TaskBase.nextPrereq (/usr/local/lib/node_modules/jake/lib/task/task.js:196:15)
    at TaskBase.runPrereqs (/usr/local/lib/node_modules/jake/lib/task/task.js:170:14)
(See full trace by running task with --trace)
```

**Expected behavior:** The usage of `jake runtests-browser` is documented both in [README.md](https://github.com/Microsoft/TypeScript/blob/master/README.md) and in [CONTRIBUTING.md](https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md). It should either work or not exist in the documentation.

**Actual behavior:** The error that is stated above.

**Related Issues:** Looking at the history of `Jakefile.js` it seems that [this is the commit that removed the task](https://github.com/Microsoft/TypeScript/commit/336c37662d11f8c8bc0751d98f051c44f23b56f7#diff-b9cf5d85d3f069782d8b050d115be052).

**Comment by weswigham** [comment]
`gulp runtests-browser` should still exist, for now.

**Comment by iliashkolyar** [comment]
@weswigham As stated in #27533, `gulp runtests-browser` does exist but it doesn't work.
It fails with `"TypeError: Unable to get property 'bufferFrom' of undefined or null reference"`.

**Comment by weswigham** [comment]
`jake` is gone and `runtests-browser` has likewise been exorcised~
