### ISSUE TITLE
API: how to work with fresh type literal or literal type?

### ISSUE THREAD

**Issue by ajafff** [microsoft/TypeScript#27174]
With all the type freshness recently added, is there a way to actually use it through the public API?
`ts.TypeFlags.FreshLiteral` is internal, so that's not an option.

Last time I checked none of the `TypeChecker.getType*` methods returned a type with the freshness flag set, even though is should definitely be there.

Is freshness a concept that is not intended for API users to know and care about?

**Comment by DanielRosenwasser** [comment]
> Is freshness a concept that is not intended for API users to know and care about?

I want to say this is the answer, however I'll defer to @RyanCavanaugh and @weswigham. Is there any reason you need to know about freshness?

**Comment by weswigham** [comment]
It's intended to be internal. Consumers should just be aware that there can be multiple variants of a literal type with different triple-equals assignability that are still essentially identical types, so generally speaking, using triple equals to check for the presence of a specific type is a bad idea. A relationship like isIdenticalTo or isAssignableTo is almost always more correct.

**Comment by ajafff** [comment]
> Is there any reason you need to know about freshness?

Admittedly there are not many use cases and the one I'm presenting here may not be too useful either:
I have a lint rule to detect useless assertions. Currently I have to ignore assertions with literal types as they are used to prevent widening (remove freshness).

```ts
declare function identity<T>(p: T): T;
identity('foo' as 'foo'); // assertion is not necessary because identity functions make fresh literal type non-widening
const wideningFoo = 'foo';
const nonWideningFoo = wideningFoo as 'foo'; // assertion is necessary to remove freshness

'foo' as 'foo'; // assertion is necessary to remove freshness
nonWideningFoo as 'foo'; // assertion is not necessary on a non-widening type
```

The last case in the above example cannot be detected right now.

> A relationship like isIdenticalTo or isAssignableTo is almost always more correct.

I wish one of these functions was exposed as part of the public API. Currently I can only compare type identity using triple equals or compare the output of `typeToString`

**Comment by ajafff** [comment]
I have another use case: I have a rule to detect useless initializers (in ObjectBindingPattern).
It works by looking at the initializer of the VariableLikeDeclaration and check if the destructured property is optional or allows `undefined`.
Unfortunately the type checker adds `SymbolFlags.Optional` to properties of fresh object literals if the destructuring has a default initializer:

```ts
let {a = '', b = ''} = {a: 1, b: Boolean() ? 'foo' : undefined};
```

In the above example properties `a` and `b` are both marked as optional (even though they will always be present). I could simply ignore that flag if I knew that I'm dealing with a fresh object literal. But there's no way for me to find out that the containing type is a fresh object literal (besides looking at the AST).
