### ISSUE TITLE
Generic doesn't save this

### ISSUE THREAD

**Issue by AndreasCag** [microsoft/TypeScript#27177]
**TypeScript Version:**  3.0.1

**Code**

```ts

type DefaultTAdditionalData = {
  [s: string]: (this: Processor<DefaultTAdditionalData>, ...args: any[]) => any;
};

type ProcessorPayload<TAdditionalData extends DefaultTAdditionalData> = {
  getAdditionalData(): TAdditionalData;
};

class Processor<TAdditionalData extends DefaultTAdditionalData> {
  public additionalData: TAdditionalData;

  public state: string = 'DEFAULT_STATE';

  constructor(payload: ProcessorPayload<TAdditionalData>) {
      const additionalData = payload.getAdditionalData();

      // tslint:disable
      for (const additionalDataMethodKey in additionalData) {
          additionalData[additionalDataMethodKey] = additionalData[additionalDataMethodKey].bind(this);
      }
      // tslint:enable

      this.additionalData = additionalData;
  }
}

const createProcessorFactory = <TAdditionalData extends DefaultTAdditionalData>(payload: ProcessorPayload<TAdditionalData>) => {
  return () => {
      return new Processor(payload);
  };
};

type mainProcessorAdditionalData = {
  logState(): void;
};

const mainProcessorFactory = createProcessorFactory<mainProcessorAdditionalData>({
  getAdditionalData: () => ({
      logState() {
          // [ts] Property 'state' does not exist on type 'mainProcessorAdditionalData'.
          console.log(this.state);
      },
  }),
});
```

**Expected behavior:**
With noImplicitThis code doesn't produce any errors, `this` is `Processor` inside `logState` method

**Actual behavior:**
With noImplicitThis:
[ts] Property 'state' does not exist on type 'mainProcessorAdditionalData'.

**Playground Link:** 
Enable noImplicitThis in options

http://www.typescriptlang.org/play/#src=%0D%0Atype%20DefaultTAdditionalData%20%3D%20%7B%0D%0A%20%20%5Bs%3A%20string%5D%3A%20(this%3A%20Processor%3CDefaultTAdditionalData%3E%2C%20...args%3A%20any%5B%5D)%20%3D%3E%20any%3B%0D%0A%7D%3B%0D%0A%0D%0Atype%20ProcessorPayload%3CTAdditionalData%20extends%20DefaultTAdditionalData%3E%20%3D%20%7B%0D%0A%20%20getAdditionalData()%3A%20TAdditionalData%3B%0D%0A%7D%3B%0D%0A%0D%0Aclass%20Processor%3CTAdditionalData%20extends%20DefaultTAdditionalData%3E%20%7B%0D%0A%20%20public%20additionalData%3A%20TAdditionalData%3B%0D%0A%0D%0A%20%20public%20state%3A%20string%20%3D%20'DEFAULT_STATE'%3B%0D%0A%0D%0A%20%20constructor(payload%3A%20ProcessorPayload%3CTAdditionalData%3E)%20%7B%0D%0A%20%20%20%20%20%20const%20additionalData%20%3D%20payload.getAdditionalData()%3B%0D%0A%0D%0A%20%20%20%20%20%20%2F%2F%20tslint%3Adisable%0D%0A%20%20%20%20%20%20for%20(const%20additionalDataMethodKey%20in%20additionalData)%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20additionalData%5BadditionalDataMethodKey%5D%20%3D%20additionalData%5BadditionalDataMethodKey%5D.bind(this)%3B%0D%0A%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%20%20%2F%2F%20tslint%3Aenable%0D%0A%0D%0A%20%20%20%20%20%20this.additionalData%20%3D%20additionalData%3B%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Aconst%20createProcessorFactory%20%3D%20%3CTAdditionalData%20extends%20DefaultTAdditionalData%3E(payload%3A%20ProcessorPayload%3CTAdditionalData%3E)%20%3D%3E%20%7B%0D%0A%20%20return%20()%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20return%20new%20Processor(payload)%3B%0D%0A%20%20%7D%3B%0D%0A%7D%3B%0D%0A%0D%0Atype%20mainProcessorAdditionalData%20%3D%20%7B%0D%0A%20%20logState()%3A%20void%3B%0D%0A%7D%3B%0D%0A%0D%0Aconst%20mainProcessorFactory%20%3D%20createProcessorFactory%3CmainProcessorAdditionalData%3E(%7B%0D%0A%20%20getAdditionalData%3A%20()%20%3D%3E%20(%7B%0D%0A%20%20%20%20%20%20logState()%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20console.log(this.state)%3B%0D%0A%20%20%20%20%20%20%7D%2C%0D%0A%20%20%7D)%2C%0D%0A%7D)%3B%0D%0A

**Comment by weswigham** [comment]
Your type
```ts
type mainProcessorAdditionalData = {
  logState(): void;
};
```
should be
```ts
type mainProcessorAdditionalData = {
  logState(this: Processor<mainProcessorAdditionalData>): void;
};
```
if you enable `strictFunctionTypes` you'll see the lack of an appropriate this `this` type on your signature is a strict variance issue.
