### ISSUE TITLE
Workspace settings should use User setting as default setting.

### ISSUE THREAD

**Issue by RedTailBullet** [Microsoft/TypeScript#27187]
## Search Terms

workspace setting, setting, user setting

## Suggestion

Use user setting as the default setting for workspace setting in setting editor.

## Use Cases

When the default setting has been modified in user setting, workspace setting should be based on user setting instead of default setting.

Under current behavior, if user settings already modified this setting, we are unable to overwrite the workspace settings to set the it as the default value.

This might only be the issue with boolean type settings.

## Examples

Given setting A.  
A's default setting is `false`.  
In user settings, A is set to `true`.  
In workspace settings, A can be set to `false` again.  
When doing the "reset setting" in workspace settings, A should be set to `true` which is the user setting.

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by DanielRosenwasser** [comment]
Is this supposed to be a VS Code issue?

**Comment by RedTailBullet** [comment]
> Is this supposed to be a VS or VS Code issue?

Yes.......... sorry... wrong place...
