### ISSUE TITLE
Preserve variable names when converting commonjs

### ISSUE THREAD

**Issue by jpike88** [Microsoft/TypeScript#27185]
Example file:

```
import { Bar as test } from "./Bar";
import { Foo as test2 } from "./Foo";

let bar = new test()
let foo = new test2();
```

When output using commonjs, looks like this:

```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const Bar_1 = require("./Bar");
const Foo_1 = require("./Foo");
let bar = new Bar_1.Bar();
let foo = new Foo_1.Foo();
```

```test``` and ```test2``` are nowhere to be seen.

This renders inline variable previewing and easy autocomplete in debugging impossible for those variables.

It becomes a guessing game of what import variable names are instead of preserving the original names, I don't see why this would clash or be an issue.

Why transform the names?

**Comment by RyanCavanaugh** [comment]
ES6 module bindings are "live", even if bound to a single local identifier through destructuring. IOW
```
// a.js
export let x = 0;
export function increment() { x++ }

// b.js
import { x, increment } from './a';
increment();
console.log(x.toString()); // Prints 1, not 0
```
