### ISSUE TITLE
Typings for Network Information API

### ISSUE THREAD

**Issue by aneeven** [Microsoft/TypeScript#27186]
## Search Terms

- Network
- Network Information
- Network API
- netinfo

## Suggestion

There are no types for the current draft [Network Information API](http://wicg.github.io/netinfo/) yet. Since it already landed in [some browsers](https://caniuse.com/#feat=netinfo), I'd like to change that.

## Use Cases

For use cases please take a look at MDNs example [here](https://developer.mozilla.org/en-US/docs/Web/API/Network_Information_API).

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. new expression-level syntax)

Are you open for a PR?

Cheers

**Comment by aneeven** [comment]
Any news on my proposal? :)

**Comment by RyanCavanaugh** [comment]
APIs have to leave experimental state before we add them to lib.d.ts.

**Comment by lacolaco** [comment]
@aneeven As a temporary solution, I've created a type definition package. If you still want the types, it may help you. Thanks

https://github.com/lacolaco/network-information-types

**Comment by eliasm307** [comment]
@RyanCavanaugh are these APIs still classed as experimental? MDN has put a ["living standard"](https://developer.mozilla.org/en-US/docs/Web/API/Window/navigator) status on these now

**Comment by TeoAvignon** [comment]
It would be really nice to have an official solution !

**Comment by blixt** [comment]
It looks like `navigator.connection` and `NetworkInterface` was introduced to TypeScript (hence the deprecation of the repo mentioned above) but removed again in this commit: 6004b35ce4c9ed1c9e8c1e450068ef3f9c4cbd5c

The value is available to more than 75% of web users [according to Can I use](https://caniuse.com/netinfo), so I expected it to stick around. Will it make a comeback?

**Comment by boredland** [comment]
Really sad to have to rely on an outdated package for the types to a 77% supported navigator feature...

**Comment by piotr-cz** [comment]
@lacolaco

You archived the `network-information-types` package but it's needed once again: https://github.com/microsoft/TypeScript/issues/27186#issuecomment-2147995552
