### ISSUE TITLE
Expando use-before-def error incorrectly appears cross-module

### ISSUE THREAD

**Issue by sandersn** [Microsoft/TypeScript#27197]
```js
// File: mod1.js
const util = exports = module.exports = {}
util.existy = function () {}
// File: main.js
const util = require('./mod1')
function n() { util.existy }
```

**Expected behavior:**
No use-before-def error.

**Actual behavior:**
Use-before-def error on util.existy. But there isn't one when util.existy is used at the toplevel.

**Comment by brendankenny** [comment]
See also #27167, which I *believe* is the same thing (but the example is in a single file). Requires the same top-level-define/nested-access pattern.

**Comment by sandersn** [comment]
Duplicate of #27167
