### ISSUE TITLE
Mapped Types with Intersections in React Props Definition, results in type is not assignable error

### ISSUE THREAD

**Issue by IllusionElements** [microsoft/TypeScript#27201]
**Search Terms:**
Mapped Types with React Props
incorrect assignable reference
**Code**
the intent is for this to be a decorator
```ts 
type Mutate<T extends string | number | symbol> = Readonly<
  { [K in T]: MutationFn }
>
const withMutation = <
  Key extends string,
  V extends OperationVariables,
  TData extends object = any
>(
  mutationProps: Omit<MutationProps<TData, V>, 'children'>
) => {
  return <P extends object>(
    Component: ComponentType<
      P &
        Mutate<Key> &
        Pick<MutationResult<TData>, 'loading' | 'data' | 'error'>
    >
  ) =>
    class WithMutation extends React.Component<P> {
      render() {
        const key = (mutationProps.mutation
          .definitions[0] as OperationDefinitionNode).name!.value as K
        return (
          <Mutation {...mutationProps}>
            {(mutateFn: MutationFn, result: MutationResult<TData>) => {
              const error = result.error! 

              return (
                <Component
                  loading={result.loading!}
                  error={error}
                  {...result.data}
                  {...this.props}
                  {...{ [key]: mutateFn }}
                />
              )
            }}
          </Mutation>
        )
      }
    }
}

// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**Expected behavior:**
the props should be correct, for reference the mapped type behavior produces this I think
```ts
type Mutate<T extends string | number | symbol> = Readonly<
  { [K in T]: MutationFn }
>

Mutate<'submitForm'> === Readonly<{ submitForm: MutationFn }>
```

not actually sure why it's saying the type is not assignable since 
type '((IntrinsicAttributes & IntrinsicClassAttributes<Component<P & Readonly<{ [K in Key]: MutationFn<any, OperationVariables>; }> & Pick<MutationResult<TData>, "data" | "loading" | "error">, any, any>> & Readonly<...> & Readonly<...>) | (IntrinsicAttributes & ... 2 more ... & { ...; }))["loading"]'

should evaluate to boolean.
**Actual behavior:**
![image](https://user-images.githubusercontent.com/7991461/45718295-86f60e00-bb6a-11e8-88e8-3cb4c30bbc02.png)

**Playground Link:** 

**Related Issues:**

**Comment by dmichon-msft** [comment]
The line `{...result.data}` doesn't match the defined type of the component props. The latter expects `data={result.data}`.
The most strictly correct props type reflected by your current decorator is:
```ts
ComponentType<{ [PropKey in (keyof P | Key | 'loading' | 'error' | keyof MutationResult<TData>)]: PropKey extends Key ? MutationFn : PropKey extends keyof P ? P[PropKey] : PropKey extends keyof MutationResult<TData> ? MutationResult<TData>['data'][PropKey] : PropKey extends ('loading' | 'error') ? MutationResult<TData>[PropKey] : never; }
```

**Comment by IllusionElements** [comment]
even with ``data={result.data}, the compiler still complains that ``loading={result.loading as boolean} is not assignable to type ``{ loading: boolean } in the props

**Comment by RyanCavanaugh** [comment]
Please reduce the repo further - thanks!

**Comment by IllusionElements** [comment]
reduced [here](https://www.typescriptlang.org/play/index.html#src=%2F**%20%40format%20*%2F%0D%0Adeclare%20type%20Index%20%3D%20string%20%7C%20number%20%7C%20symbol%0D%0A%0D%0Adeclare%20type%20Mapped%3CKey%20extends%20Index%2C%20T%3E%20%3D%20%7B%20%5BK%20in%20Key%5D%3A%20T%20%7D%0D%0A%0D%0Adeclare%20type%20MutationFn%3CT%2C%20U%3E%20%3D%20any%0D%0A%0D%0Atype%20I%3CP%2C%20TData%2C%20Key%20extends%20string%3E%20%3D%20Readonly%3C%7B%0D%0A%20%20%20children%3F%3A%20any%3B%0D%0A%20%20%7D%3E%20%26%20Readonly%3CP%20%26%20TData%20%26%20%7B%0D%0A%20%20loading%3A%20boolean%2C%0D%0A%20%20error%3A%20Error%0D%0A%20%20%7D%20%26%20Mapped%3CKey%2C%20MutationFn%3Cany%2C%20any%3E%3E%3E%0D%0A%0D%0Atype%20Z%3CP%2C%20D%2C%20K%20extends%20string%3E%20%3D%20I%3CP%2C%20D%2C%20K%3E%5B%22loading%22%5D%0D%0A%0D%0Aconst%20loading%3A%20boolean%20%3D%20true%0D%0A%0D%0Aclass%20Example%3CP%2C%20D%2C%20K%20extends%20string%3E%20%7B%0D%0A%20%20isLoading%3A%20Z%3CP%2C%20D%2C%20K%3E%20%3D%20loading%0D%0A%7D%0D%0A%0D%0A%0D%0Atype%20Other%3CP%2C%20TData%2C%20Key%20extends%20string%3E%20%3D%20Readonly%3C%7B%0D%0A%20%20%20children%3F%3A%20any%3B%0D%0A%20%20%7D%20%26%20P%20%26%20TData%20%26%20%7B%0D%0A%20%20loading%3A%20boolean%2C%0D%0A%20%20error%3A%20Error%0D%0A%7D%20%26%20Mapped%3CKey%2C%20MutationFn%3Cany%2C%20any%3E%3E%3E%0D%0A%0D%0A%0D%0Atype%20Tesr%3CP%2C%20D%2C%20K%20extends%20string%3E%20%3D%20Other%3CP%2C%20D%2C%20K%3E%5B%22loading%22%5D%0D%0A%0D%0Aclass%20Example2%3CP%2C%20D%2C%20K%20extends%20string%3E%20%7B%0D%0A%20%20isLoading%3A%20Tesr%3CP%2C%20D%2C%20K%3E%20%3D%20loading%0D%0A%7D)

**Comment by weswigham** [comment]
It's worth nothing that the error is correct, if awful to diagnose. In your simplified example:
```ts
/** @format */
declare type Index = string | number | symbol

declare type Mapped<Key extends Index, T> = { [K in Key]: T }

declare type MutationFn<T, U> = any

type I<P, TData, Key extends string> = Readonly<{
   children?: any;
  }> & Readonly<P & TData & {
  loading: boolean,
  error: Error
  } & Mapped<Key, MutationFn<any, any>>>

type Z<P, D, K extends string> = I<P, D, K>["loading"]

const loading: boolean = true

class Example<P, D, K extends string> {
  isLoading: Z<P, D, K> = loading
}


type Other<P, TData, Key extends string> = Readonly<{
   children?: any;
  } & P & TData & {
  loading: boolean,
  error: Error
} & Mapped<Key, MutationFn<any, any>>>


type Tesr<P, D, K extends string> = Other<P, D, K>["loading"]

class Example2<P, D, K extends string> {
  isLoading: Tesr<P, D, K> = loading
}
```
if I instantiated `Example` as `Example<{loading: false}, {}, "">`, the `isLoading` member would be of type `false & boolean` which is `false & (true | false)`, which is `false & true | false & false`, which is `never | false`, which is simply `false`, to which a `boolean` should not be assignable to!

**Comment by IllusionElements** [comment]
> It's worth nothing that the error is correct, if awful to diagnose (at least in your reduced example). In your simplified example:
> 
> ```ts
> /** @format */
> declare type Index = string | number | symbol
> 
> declare type Mapped<Key extends Index, T> = { [K in Key]: T }
> 
> declare type MutationFn<T, U> = any
> 
> type I<P, TData, Key extends string> = Readonly<{
>    children?: any;
>   }> & Readonly<P & TData & {
>   loading: boolean,
>   error: Error
>   } & Mapped<Key, MutationFn<any, any>>>
> 
> type Z<P, D, K extends string> = I<P, D, K>["loading"]
> 
> const loading: boolean = true
> 
> class Example<P, D, K extends string> {
>   isLoading: Z<P, D, K> = loading
> }
> 
> 
> type Other<P, TData, Key extends string> = Readonly<{
>    children?: any;
>   } & P & TData & {
>   loading: boolean,
>   error: Error
> } & Mapped<Key, MutationFn<any, any>>>
> 
> 
> type Tesr<P, D, K extends string> = Other<P, D, K>["loading"]
> 
> class Example2<P, D, K extends string> {
>   isLoading: Tesr<P, D, K> = loading
> }
> ```
> 
> if I instantiated `Example` as `Example<{loading: false}, {}, "">`, the `isLoading` member would be of type `false & boolean` which is `false & (true | false)`, which is `false & true | false & false`, which is `never | false`, which is simply `false`, to which a `boolean` should not be assignable to!

That makes sense, but then why would it still error, if I mark it so that  types P & D have any boolean properties excluded from the type? 

[updated repo here](https://www.typescriptlang.org/play/index.html#src=%2F**%20%40format%20*%2F%0D%0Atype%20Omit%3CT%2C%20K%20extends%20keyof%20T%3E%20%3D%20Pick%3CT%2C%20Exclude%3Ckeyof%20T%2C%20K%3E%3E%0D%0A%0D%0Atype%20MutationFn%20%3D%20()%20%3D%3E%20string%0D%0A%0D%0Atype%20Mapped%3CKey%20extends%20string%20%7C%20number%20%7C%20symbol%3E%20%3D%20%7B%20%5BK%20in%20Key%5D%3A%20MutationFn%20%7D%0D%0A%0D%0A%0D%0Atype%20I%3CP%2C%20TData%2C%20Key%20extends%20string%3E%20%3D%20Readonly%3C%7B%0D%0A%20%20%20children%3F%3A%20any%3B%0D%0A%20%20%7D%3E%20%26%20Readonly%3CP%20%26%20TData%20%26%20%7B%0D%0A%20%20loading%3A%20boolean%2C%0D%0A%20%20error%3A%20Error%0D%0A%20%20%7D%20%26%20Mapped%3CKey%3E%3E%0D%0A%0D%0A%0D%0Atype%20K%3CP%2CD%3E%20%3D%20I%3CP%2C%20D%2C%20'submitForm'%3E%5B%22loading%22%5D%0D%0A%0D%0Atype%20ExcludeBool%3CT%3E%20%3D%20Exclude%3CT%2C%20%7B%20%5Bkey%3A%20string%5D%3A%20boolean%20%7D%3E%20%26%20Exclude%3CT%2C%20%7B%20%5Bkey%3A%20number%5D%3A%20boolean%20%7D%3E%20%0D%0A%0D%0Aconst%20loading%20%3D%20true%0D%0A%0D%0Aclass%20Example%3CP%2C%20D%2C%20O%20extends%20string%3E%20%7B%0D%0A%20%20isLoading%3A%20K%3CExcludeBool%3CP%3E%2C%20ExcludeBool%3CD%3E%3E%20%3D%20loading%0D%0A%7D%0D%0A%0D%0A%0D%0A)

**Comment by weswigham** [comment]
Because `Exclude` is imperfect and can't currently track constraints on the `false` branch of the conditional, as those are (effectively) subtraction types, which we can't easily express right now. :(

**Comment by weswigham** [comment]
`Extract` does a little better. If you can rephrase/reorder in terms of extract, you might manage the desired result.

**Comment by dmichon-msft** [comment]
Excepting possible compilation performance issues, it's best not to use the intersection operator `&` to describe the result of the es6 spread operator, since later object spreads overwrite prior values. This is why I described your component type as:
```ts
ComponentType<{
  [PropKey in (keyof P | Key | 'loading' | 'error' | keyof MutationResult<TData>)]: PropKey extends Key ?
    MutationFn : PropKey extends keyof P ?
    P[PropKey] : PropKey extends keyof MutationResult<TData> ?
    MutationResult<TData>['data'][PropKey] : PropKey extends ('loading' | 'error') ?
    MutationResult<TData>[PropKey] : never;
}>
```
The value for `[key: Key} MutationFn` is written last, so takes precedence, then the values from `this.props: P`, then those from `result.data: MutationResult<TData>['data'}` then finally the results from `result.loading: boolean` and `result.error: Error`.

Incidentally, the compiler will flatten the above described type if you ever call it with concrete types, making it rather easier to find type mismatches.

Your example can also trivially be broken by calling:
```ts
const ex = new Example<{}, {}, "loading">();
```
which will also break at runtime, since `ex.isLoading` will (at runtime) be of type `MutationFn`

**Comment by IllusionElements** [comment]
How does the Readonly type play into all this? It seems that the type only breaks when the intersection is of two Readonly types it will error out but if they aren't wrapped in Readonly it's completely fine

[see here](https://www.typescriptlang.org/play/index.html#src=%2F**%20%40format%20*%2F%0D%0Atype%20Omit%3CT%2C%20K%20extends%20keyof%20T%3E%20%3D%20Pick%3CT%2C%20Exclude%3Ckeyof%20T%2C%20K%3E%3E%0D%0A%0D%0Atype%20MutationFn%20%3D%20()%20%3D%3E%20string%0D%0A%0D%0Atype%20Mapped%3CKey%20extends%20string%20%7C%20number%20%7C%20symbol%3E%20%3D%20%7B%20%5BK%20in%20Key%5D%3A%20MutationFn%20%7D%0D%0A%0D%0A%0D%0Atype%20I%3CP%2C%20TData%2C%20Key%20extends%20string%3E%20%3D%20%7B%0D%0A%20%20%20children%3F%3A%20any%3B%0D%0A%20%20%7D%20%26%20P%20%26%20TData%20%26%20%7B%0D%0A%20%20loading%3A%20boolean%2C%0D%0A%20%20error%3A%20Error%0D%0A%20%20%7D%20%26%20Mapped%3CKey%3E%0D%0A%0D%0A%0D%0Atype%20K%3CP%2CD%3E%20%3D%20I%3CP%2C%20D%2C%20'submitForm'%3E%5B%22loading%22%5D%0D%0A%0D%0Atype%20ExcludeBool%3CT%3E%20%3D%20Exclude%3CT%2C%20Extract%3CT%2C%20true%3E%3E%20%26%20Exclude%3CT%2C%20Extract%3CT%2C%20false%3E%3E%20%0D%0A%0D%0Aconst%20loading%3A%20boolean%20%3D%20true%0D%0A%0D%0Aclass%20Example%3CP%2C%20D%2C%20O%20extends%20string%3E%20%7B%0D%0A%20%20isLoading%3A%20K%3CExcludeBool%3CP%3E%2C%20ExcludeBool%3CP%3E%3E%20%3D%20loading%0D%0A%7D%0D%0A%0D%0A%0D%0A)

**Comment by weswigham** [comment]
The non-readonly case should also be an error; but for historical reasons it isn't. The presence of a generic mapped type (ie, read-only) causes us to defer the access and treat it as a type variable, which we can then actually calculate the constraint of and issue the error. The non-mapped-type case (incorrectly) eagerly looks up the type of the member and uses it as the target type. So instead of assigning to an effective `T extends boolean` as is the case of the access, you just assign to `boolean`. It's a known place where we're unsound, but don't change it for fear of breaking people's old code. :(

**Comment by IllusionElements** [comment]
So what's the best way to write the type so that 
```ts
 {  
[PropKey in
          | keyof P
          | Key
          | 'loading'
          | 'error'
          | keyof MutationResult<TData>]: PropKey extends Key
          ? MutationFn
          : PropKey extends keyof P
            ? P[PropKey]
            : PropKey extends keyof MutationResult<TData>
              ? Result<TData>['data'][PropKey]
              : PropKey extends ('loading' | 'error')
                ? { loading: boolean, error: Error }[PropKey]
                : never
      }["loading"] 

```


will resolve to boolean? and error would correctly resolve to the Error type?
