### ISSUE TITLE
Absolute imports in emitted declaration files using baseUrl

### ISSUE THREAD

**Issue by rdsedmundo** [microsoft/TypeScript#27218]
Hello.

As per https://github.com/Microsoft/TypeScript/issues/16088 I'm aware that TypeScript does nothing in terms of rewriting paths when it comes to the outputted code, and it's required to include a new solution like Babel (with module-resolver plugin) in order to fix the imports, besides TypeScript having the `baseUrl` and `paths` options which only work for the compile time.

I'd like to know though what do with the declaration `d.ts` files being emitted by the `declaration` option. They're being emitted with the absolute paths like `import { InitiatorSource, PayoutType, Row } from 'api';` and Babel plugin is not capable of rewriting them as the syntax is not known by them, therefore other packages trying to use the declaration won't work properly.

**Comment by joonhocho** [comment]
I've created a solution that does not require any dependencies nor babel. https://github.com/joonhocho/tscpaths

https://github.com/Microsoft/TypeScript/issues/15479#issuecomment-427539118
