### ISSUE TITLE
Visual Studio 2017 lists compile errors from tsc.exe twice (duplicates)

### ISSUE THREAD

**Issue by AlexVallat** [Microsoft/TypeScript#27210]
**TypeScript Version:**  3.0.1

**Search Terms:**
Visual Studio error list duplicate twice multiple

**Expected behavior:**
Compile errors are listed once in the Visual Studio 2017 Error List

**Actual behavior:**
Compile errors are listed twice (duplicated) in the Error List

Checking the build log, it appears that Visual Studio runs tsc.exe twice, once with -noEmit (PreComputeCompileTypeScriptWithTSConfig task), and then a second time without -noEmit (CompileTypeScriptWithTSConfig task). tsc.exe reports the same compile errors for both runs, resulting in duplicate errors being displayed in the Errors list.

**Comment by uniqueiniquity** [comment]
I apologize for the delay in responding.
Are you still able to reproduce this with [TypeScript 3.2](https://www.nuget.org/packages/Microsoft.TypeScript.MSBuild)?

**Comment by AlexVallat** [comment]
I've just tested it now, with VS2017 15.9.4 and TypeScript 3.2 installed from SDK, and it no longer appears to list errors from the PreCompute step. I think this is now resolved.
