### ISSUE TITLE
Overriding index signatures

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#27228]
_From @BobFrankston on September 19, 2018 22:36_

I'm sure this has been discussed but I can't find it.

The Index signature is a very useful feature but the current implementation runs into the power of JavaScript objects in being able to have exceptions. I'm using a file generated by EXIFTOOL which is a JSON dump of meta information from images. So it makes sense to declare a string indexer. But when it comes to linking I want to add extra fields but indexers are fighting me. Why?

```
interface exentry {
    [key: string]: string,
    SourceFile: string;
    FileName: string;
    Directory: string;
    byProp: any;    // Really { [prop: string]: byProperty }
    nearby: any; //  exentry[];
}
```
There are complex work-arounds but why impose old school rigidity on the structures? At very least there should be an allow exceptions option in the config since this is a style issue and some of see the ability to add extra bags of goodies to an object as a feature not a bug.

Note that I explicitly declare some entries for clarify. I would like to have a way to say I must use [] for indexers rather than just the . notation so as to protect myself from typos by listing the common cases.

At least indexers aren't as bad as C# dynamic types which require everything have an override.

_Copied from original issue: Microsoft/vscode#58991_

**Comment by andy-ms** [comment]
That wouldn't be sound since `[key: string]: string` declares that *all* keys produce a `string` output.
However, you can use the unsound `&` operator to produce a type:
```ts
type T = { [key: string]: string } & { other: number };
const t: T = { someKey: "", other: 3 } as unknown as T;
t.a; // string
t.other; // number
function f(s: string): string { return t[s]; } // No compile error
f("other").toUpperCase(); // Error at runtime
`

**Comment by BobFrankston** [comment]
Whether it's unsound depends on interpretation. I see the key as a default rather than a command. For me, it's **type annotation**-- getting the IDE to be my assistant not my schoolmarm. I don't want to turn TypeScript into C#. Rigid types were a phase we went through. (For those at Microsoft - remember Cairo).

I remember the fad of proving programs correct ... it sacrificed expressive power for formality.  In this case I did convert my interface to 

```type exentry ={ [key:string]: string} & {byProp: { [prop:string]: byProperty}};```

but it comes at the price of transparency. Two very similar declarations are represented totally differently. That's opaque. I'd rather risk discovering problems at runtime than losing transparency in the source. 

It would make more sense to gave me a way to say that unlisted indexed entries must use [] so that I don't type unwanted accessors. The current implementation offers no protection but just annoying enforcement. In the current implementation "foo.other.substr(0,1)" would fail on a null because all names are valid.

**Comment by BobFrankston** [comment]
To better understand this, I have a real use case - the data generated by EXIFTOOL from XMP, EXIF and other data. Many of the fields are standard(ish) but anyone could add a tag. So I want to declare all the standard fields for safety and then allow for unnamed fields using explicit [] notation to avoid typos.

This is too much for the & notation. Actually, even with [] there are some fields that are numeric not strings. JavaScript doesn't really care and will do the conversions though I can use <> if I care for those cases. 


```
{
  "SourceFile": "Y:/photos/ByDate/2017/201712/20171220/20151005_111349.mp4",
  "ExifToolVersion": 11.09,
  "FileName": "20151005_111349.mp4",
  "Directory": "Y:/photos/ByDate/2017/201712/20171220",
  "FileSize": "7.8 MB",
  "FileModifyDate": "2017:12:28 20:53:57-05:00",
  "FileAccessDate": "2017:12:28 20:53:56-05:00",
  "FileCreateDate": "2017:12:28 20:53:56-05:00",
  "FilePermissions": "rw-rw-rw-",
  "FileType": "MP4",
  "FileTypeExtension": "mp4",
  "MIMEType": "video/mp4",
  "MajorBrand": "MP4 v2 [ISO 14496-14]",
  "MinorVersion": "0.0.0",
  "CompatibleBrands": ["isom","mp42"],
  "MovieDataSize": 8197443,
  "MovieDataOffset": 32,
  "MovieHeaderVersion": 0,
  "CreateDate": "2015:10:05 15:13:54",
  "ModifyDate": "2015:10:05 15:13:54",
  "TimeScale": 1000,
  "Duration": "4.08 s",
  "PreferredRate": 1,
  "PreferredVolume": "100.00%",
  "PreviewTime": "0 s",
  "PreviewDuration": "0 s",
  "PosterTime": "0 s",
  "SelectionTime": "0 s",
  "SelectionDuration": "0 s",
  "CurrentTime": "0 s",
  "NextTrackID": 3,
  "PlayMode": "SEQ_PLAY",
  "TrackHeaderVersion": 0,
  "TrackCreateDate": "2015:10:05 15:13:54",
  "TrackModifyDate": "2015:10:05 15:13:54",
  "TrackID": 1,
  "TrackDuration": "3.93 s",
  "TrackLayer": 0,
  "TrackVolume": "0.00%",
  "ImageWidth": 1920,
  "ImageHeight": 1080,
  "GraphicsMode": "srcCopy",
  "OpColor": "0 0 0",
  "CompressorID": "avc1",
  "SourceImageWidth": 1920,
  "SourceImageHeight": 1080,
  "XResolution": 72,
  "YResolution": 72,
  "BitDepth": 24,
  "VideoFrameRate": 29.994,
  "MatrixStructure": "1 0 0 0 1 0 0 0 1",
  "MediaHeaderVersion": 0,
  "MediaCreateDate": "2015:10:05 15:13:54",
  "MediaModifyDate": "2015:10:05 15:13:54",
  "MediaTimeScale": 48000,
  "MediaDuration": "4.07 s",
  "HandlerType": "Audio Track",
  "HandlerDescription": "SoundHandle",
  "Balance": 0,
  "AudioFormat": "mp4a",
  "AudioChannels": 2,
  "AudioBitsPerSample": 16,
  "AudioSampleRate": 48000,
  "AvgBitrate": "16.1 Mbps",
  "ImageSize": "1920x1080",
  "Megapixels": 2.1,
  "Rotation": 0
},
```
