### ISSUE TITLE
Frequent broken intellisense suggestions and error messages on typing

### ISSUE THREAD

**Issue by vilic** [Microsoft/TypeScript#27233]
**TypeScript Version:**  3.1.0-rc.20180906

**Search Terms:** error message mess, broken intellisense

**Code**

Cannot reproduce with simple projects.

**Expected behavior:**

`foo.` should always list its properties when `.` is typed.

**Actual behavior:**

`foo.` sometimes list global variable names.

By typing and deleting the `.` following a variable, TypeScript gives inconsistent suggestions.

Please search "$params" (one of the expected suggestions) and "DOMRect" (one of the unexpected suggestions) in the log if it helps.

[tsserver.log](https://github.com/Microsoft/TypeScript/files/2401195/tsserver.log)

This issue was first noticed in TypeScript 3.0 if not earlier. The whole document could be messed up with incorrect error messages sometimes on typing, which I guess might be caused by the same issue.

I tried to create a simple project that reproduces this issue but gets no luck, if you guys need more information please let me know.

![image](https://user-images.githubusercontent.com/970430/45817887-ac258080-bd12-11e8-8ffe-2847cea3a3a9.png)

![image](https://user-images.githubusercontent.com/970430/45819518-16402480-bd17-11e8-85a1-8185c27f7930.png)

**Comment by mjbvz** [comment]
This only shows up when using the styled-components plugin?

**Comment by vilic** [comment]
@mjbvz Just double checked with only server-side sub project (without styled-components), and this issue persists (empty compiler plugins). Also by disabling all VS Code extensions, I can no longer reproduce this issue. **HOWEVER**, I tried to rule out the problematic VS Code extension one by one, but got no luck. Might be some sort of race condition?

**Comment by vilic** [comment]
@mjbvz And with the same set of VS Code extensions, I can't reproduce it with an older project written in TypeScript 2.7.

**Comment by vilic** [comment]
@mjbvz Just confirmed the issue exists with `typescript-styled-plugin` added alone as TypeScript plugin, and with all VSCode extension disabled.

**Comment by asvetliakov** [comment]
This issue drives me mad. See https://github.com/Microsoft/typescript-styled-plugin/issues/78 for minimal repro

**Comment by vilic** [comment]
Fixed by https://github.com/Microsoft/typescript-styled-plugin/issues/78
