### ISSUE TITLE
Spec doesn't indicate that binding pattern can't be optional in an implementation signature

### ISSUE THREAD

**Issue by yuit** [microsoft/TypeScript#2723]
Compiler gives an error for the following code:

``` ts
function a({x,y}?) {} // error
```

However, in the spec both section 6.4 (Destructuring Parameter Declaration) and 3.8.2.2 (Parameter List), The later one simply specify that "A parameter can be marked optional by following its name or binding pattern with a question mark (?)..."

**Comment by RyanCavanaugh** [comment]
The spec is now an "archived" artifact and we won't be tracking defects against it anymore.
