### ISSUE TITLE
Functional Types / Interfaces: Return Type Widening

### ISSUE THREAD

**Issue by JasonGore** [Microsoft/TypeScript#27237]
**TypeScript Version:**  3.0.1-insiders.20180726

**Search Terms:** function type interface return widening

This seems like an incredibly basic problem compared to others I've searched for so I apologize in advance if I'm missing some expected behavior with regards to functional types and interfaces.

**Code**

This code properly analyzes return type and generates an error when `invalidKey` is present.
```ts
type IArg = { testArg: number };
type IReturn = { validKey: number };

const generatesExpectedError = (props: IArg): IReturn => {
  return {
    validKey: 1,
    invalidKey: 2   // expected error
  };
};
```

However, when this declaration is elevated to a functional type or interface, return type appears to widen and this error no longer appears. Basic `IReturn` type checking seems to be present as there will be an error if `validKey` is removed. It's as if type checking on the return type has widened.

```ts
// Arrow Function Type
type IArrowFunction = (props: IArg) => IReturn;

const shouldGenerateError1: IArrowFunction = (props) => {
  return {
    validKey: 1,
    invalidKey: 2   // should error
  };
};
```

```ts
// Function Interface
interface IFunction {
  (a: IArg): IReturn;
}

const shouldGenerateError2: IFunction = function(props) {
  return {
    validKey: 1,
    invalidKey: 2   // should error
  };
};
```

**Expected behavior:**

Functional types and interfaces type check return value in the same manner as inline functional typing.

**Actual behavior:**

Functional types and interfaces do not have the same return type checking as inline functional typing.

[**Playground Link**](http://www.typescriptlang.org/play/#src=type%20IArg%20%3D%20%7B%20testArg%3A%20number%20%7D%3B%0D%0Atype%20IReturn%20%3D%20%7B%20validKey%3A%20number%20%7D%3B%0D%0A%0D%0Aconst%20generatesExpectedError%20%3D%20(props%3A%20IArg)%3A%20IReturn%20%3D%3E%20%7B%0D%0A%20%20return%20%7B%0D%0A%20%20%20%20validKey%3A%201%2C%0D%0A%20%20%20%20invalidKey%3A%202%20%20%20%2F%2F%20expected%20error%0D%0A%20%20%7D%3B%0D%0A%7D%3B%0D%0A%0D%0A%2F%2F%20Arrow%20Function%20Type%0D%0Atype%20IArrowFunction%20%3D%20(props%3A%20IArg)%20%3D%3E%20IReturn%3B%0D%0A%0D%0Aconst%20shouldGenerateError1%3A%20IArrowFunction%20%3D%20(props)%20%3D%3E%20%7B%0D%0A%20%20return%20%7B%0D%0A%20%20%20%20validKey%3A%201%2C%0D%0A%20%20%20%20invalidKey%3A%202%20%20%20%2F%2F%20should%20error%0D%0A%20%20%7D%3B%0D%0A%7D%3B%0D%0A%0D%0A%2F%2F%20Function%20Interface%0D%0Ainterface%20IFunction%20%7B%0D%0A%20%20(a%3A%20IArg)%3A%20IReturn%3B%0D%0A%7D%0D%0A%0D%0Aconst%20shouldGenerateError2%3A%20IFunction%20%3D%20function(props)%20%7B%0D%0A%20%20return%20%7B%0D%0A%20%20%20%20validKey%3A%201%2C%0D%0A%20%20%20%20invalidKey%3A%202%20%20%20%2F%2F%20should%20error%0D%0A%20%20%7D%3B%0D%0A%7D%3B%0D%0A)

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
Duplicate #241
