### ISSUE TITLE
Type inference fails for picked object as function param where picked keys are generic

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/TypeScript#27234]
**TypeScript Version:**  3.0.3

**Search Terms:** pick object keys generic type inference

**Code**

```ts
type MyComponentProps = { render: (props: { file: File }) => any };

declare const createDefaultProps: <K extends keyof MyComponentProps>(
    defaultProps: Pick<MyComponentProps, K>,
) => Pick<MyComponentProps, K>;
// `defaultProps` has type ` Pick<MyComponentProps, "render">`, as expected :-)
const defaultProps = createDefaultProps({
    // `props` type is inferred as `any`, but expected `{ file: File }` :-(
    render: props => 'foo',
});
```

**Comment by andy-ms** [comment]
A workaround for now is to explicitly specify the type argument `createDefaultProps<"render">`.

**Comment by OliverJAsh** [comment]
Thanks @andy-ms. Unfortunately the purpose of this function is to infer the keys, so that's not a suitable workaround. Otherwise we would just use a type annotation on a variable with the explicit keys.

**Comment by mattmccutchen** [comment]
A better workaround as seen in the [React typings](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/255de86d7e345dae5f7ca27762a67e299cbb9414/types/react/index.d.ts#L297):
```ts
declare const createDefaultProps: <K extends keyof MyComponentProps>(
    defaultProps: Pick<MyComponentProps, K> | MyComponentProps,
) => Pick<MyComponentProps, K>;
```

**Comment by OliverJAsh** [comment]
@mattmccutchen I don't see that in the link you provided?

**Comment by mattmccutchen** [comment]
It's the `Pick<S, K> | S` in the `state` parameter.

**Comment by Andarist** [comment]
This started to work in 3.4 or 3.5 (3.4 isn't available in the playground so I can't quickly verify this). The issue can be closed
