### ISSUE TITLE
Optional type infer 

### ISSUE THREAD

**Issue by anion155** [Microsoft/TypeScript#27231]
**TypeScript Version:**  Version 3.0.3

**Search Terms:**

optional to null

**Code**

```ts
type Replace<T, U, R> = T extends U ? R : T;
type UndefToNull<T> = {
  [P in keyof T]: Replace<T[P], undefined, null>
}
let a: UndefToNull<{ id?: 5 | 7; }> = { };
```

**Expected behavior:**

Error, cause a now must be of ``` { id: 5 | 7 | null }  ``` type.

**Actual behavior:**

Compiles, cause a is actually of ``` { id?: 5 | 7 | undefined | null } ``` type.

[**Playground Link**](https://www.typescriptlang.org/play/index.html#src=type%20Replace%3CT%2C%20U%2C%20R%3E%20%3D%20T%20extends%20U%20%3F%20R%20%3A%20T%3B%0D%0Atype%20UndefToNull%3CT%3E%20%3D%20%7B%0D%0A%20%20%5BP%20in%20keyof%20T%5D%3A%20Replace%3CT%5BP%5D%2C%20undefined%2C%20null%3E%0D%0A%7D%0D%0Alet%20a%3A%20UndefToNull%3C%7B%20id%3F%3A%205%20%7C%207%3B%20%7D%3E%20%3D%20%7B%20%7D%3B)

The main intent of this was to make type B from type A
```ts
interface A {
  id?: number
}
interface B {
  id: number | null
}
```

**Comment by jack-williams** [comment]
Unless you know something is a bug I'd try stackoverflow first.

[TypeScript 2.8: Improved control over mapped type modifiers](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html#improved-control-over-mapped-type-modifiers)

```ts
type UndefToNull<T> = {
    [P in keyof T]-?: Replace<T[P], undefined, null> // or just T[P] | null
}
```

**Comment by anion155** [comment]
> Unless you know something is a bug I'd try stackoverflow first.
> 
> [TypeScript 2.8: Improved control over mapped type modifiers](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html#improved-control-over-mapped-type-modifiers)
> 
> ```ts
> type UndefToNull<T> = {
>     [P in keyof T]-?: Replace<T[P], undefined, null> // or just T[P] | null
> }
> ```
