### ISSUE TITLE
Generics - type inference - type should be narrowed to effective type

### ISSUE THREAD

**Issue by StefanJann** [Microsoft/TypeScript#27258]
**TypeScript Version:**  3.0

**Search Terms:**
generics, type inference

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, export class Item {
  a: string
}

export class MyItem extends Item {
  b: number
}

export class Container<T extends Item> {
  constructor(public items: T[]) {
  }
}

export function forEachItem<T extends Container<I>, I extends Item>(
    container: T, transform: (item: I) => any): any[] {

  for (const item of container.items) {
    const result = transform.apply(null, item);
  }

  return null;
}

export function test() {
  const containerA: Container<MyItem> = new Container([]);

  forEachItem(containerA, (item) => {
     // --> item has type 'Item' instead of 'MyItem'!
  });
}

```

**Expected behavior:**
item should have inferred type from containerA (MyItem)

**Actual behavior:**
item has type 'Item'.

**Playground Link:** 

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
You have too many type parameters here, which causes inference to not make the correct pairings of types and values. The declaration should be
```ts
export function forEachItem<I extends Item>(container: Container<I>, transform: (item: I) => any): any[] {
```

**Comment by StefanJann** [comment]
You're right, two type parameters were actually unnecessary in this example. In my case, the item parameter in the callback is actually of another class, but typed with the same item type, because a first transformation is made in the forEachItem function before the callback is called.. but that works as well with your simplified code..

`
export function forEachItem<I extends Item>(container: Container<I>, transform: (item: OtherClass<I>) => any): any[] {
`

Thanks :-)
