### ISSUE TITLE
type guard borken with complex type

### ISSUE THREAD

**Issue by Kingwl** [Microsoft/TypeScript#27257]
**TypeScript Version:**  3.1.0-dev.201xxxxx

**Search Terms:**

**Code**

https://www.typescriptlang.org/play/index.html#src=export%20enum%20RequestOrderBy%20%7B%0A%20%20count%20%3D%20'count'%2C%0A%20%20time%20%3D%20'time'%0A%7D%0Aexport%20enum%20ACLDataType%20%7B%0A%20%20ip%20%3D%20%22top_ip%22%2C%0A%20%20ipWebsite%20%3D%20'top_ip_website'%2C%0A%20%20ipUrl%20%3D%20'top_ip_url'%2C%0A%20%20session%20%3D%20'top_session'%2C%0A%20%20sessionWebsite%20%3D%20'top_session_website'%2C%0A%20%20sessionUrl%20%3D%20'top_session_url'%0A%7D%0Aexport%20interface%20IPData%20%7B%0A%20%20ip%3A%20string%0A%7D%0Aexport%20interface%20SessionData%20%7B%0A%20%20session%3A%20string%0A%7D%0Aexport%20interface%20UrlData%20%7B%0A%20%20url%3A%20string%0A%7D%0Aexport%20interface%20WebsiteData%20%7B%0A%20%20website%3A%20string%0A%7D%0Aexport%20interface%20CountData%20%7B%0A%20%20count%3A%20number%0A%7D%0Aexport%20interface%20TimeData%20%7B%0A%20%20time%3A%20number%0A%7D%0Aexport%20interface%20IpCountResponse%20%7B%0A%20%20type%3A%20ACLDataType.ip%2C%0A%20%20order_by%3A%20RequestOrderBy.count%2C%0A%20%20data%3A%20(IPData%20%26%20CountData)%5B%5D%0A%7D%0Aexport%20interface%20IpWebsiteCountResponse%20%7B%0A%20%20type%3A%20ACLDataType.ipWebsite%2C%0A%20%20order_by%3A%20RequestOrderBy.count%2C%0A%20%20data%3A%20(IPData%20%26%20WebsiteData%20%26%20CountData)%5B%5D%0A%7D%0Aexport%20interface%20IpUrlCountResponse%20%7B%0A%20%20type%3A%20ACLDataType.ipUrl%2C%0A%20%20order_by%3A%20RequestOrderBy.count%2C%0A%20%20data%3A%20(IPData%20%26%20UrlData%20%26%20CountData)%5B%5D%0A%7D%0Aexport%20interface%20SessionCountResponse%20%7B%0A%20%20type%3A%20ACLDataType.session%2C%0A%20%20order_by%3A%20RequestOrderBy.count%2C%0A%20%20data%3A%20(SessionData%20%26%20CountData)%5B%5D%0A%7D%0Aexport%20interface%20SessionWebsiteCountResponse%20%7B%0A%20%20type%3A%20ACLDataType.sessionWebsite%2C%0A%20%20order_by%3A%20RequestOrderBy.count%2C%0A%20%20data%3A%20(SessionData%20%26%20WebsiteData%20%26%20CountData)%5B%5D%0A%7D%0Aexport%20interface%20SessionUrlCountResponse%20%7B%0A%20%20type%3A%20ACLDataType.sessionUrl%2C%0A%20%20order_by%3A%20RequestOrderBy.count%2C%0A%20%20data%3A%20(SessionData%20%26%20UrlData%20%26%20CountData)%5B%5D%0A%7D%0Aexport%20interface%20IpTimeResponse%20%7B%0A%20%20type%3A%20ACLDataType.ip%2C%0A%20%20order_by%3A%20RequestOrderBy.time%2C%0A%20%20data%3A%20(IPData%20%26%20TimeData)%5B%5D%0A%7D%0Aexport%20interface%20IpWebsiteTimeResponse%20%7B%0A%20%20type%3A%20ACLDataType.ipWebsite%2C%0A%20%20order_by%3A%20RequestOrderBy.time%2C%0A%20%20data%3A%20(IPData%20%26%20WebsiteData%20%26%20TimeData)%5B%5D%0A%7D%0Aexport%20interface%20IpUrlTimeResponse%20%7B%0A%20%20type%3A%20ACLDataType.ipUrl%2C%0A%20%20order_by%3A%20RequestOrderBy.time%2C%0A%20%20data%3A%20(IPData%20%26%20UrlData%20%26%20TimeData)%5B%5D%0A%7D%0Aexport%20interface%20SessionTimeResponse%20%7B%0A%20%20type%3A%20ACLDataType.session%2C%0A%20%20order_by%3A%20RequestOrderBy.time%2C%0A%20%20data%3A%20(SessionData%20%26%20TimeData)%5B%5D%0A%7D%0Aexport%20interface%20SessionWebsiteTimeResponse%20%7B%0A%20%20type%3A%20ACLDataType.sessionWebsite%2C%0A%20%20order_by%3A%20RequestOrderBy.time%2C%0A%20%20data%3A%20(SessionData%20%26%20WebsiteData%20%26%20TimeData)%5B%5D%0A%7D%0Aexport%20interface%20SessionUrlTimeResponse%20%7B%0A%20%20type%3A%20ACLDataType.sessionUrl%2C%0A%20%20order_by%3A%20RequestOrderBy.time%2C%0A%20%20data%3A%20(SessionData%20%26%20UrlData%20%26%20TimeData)%5B%5D%0A%7D%0A%0A%0Aexport%20type%20MonitorModel%20%3D%20IpCountResponse%0A%20%20%7C%20IpUrlCountResponse%0A%20%20%7C%20IpWebsiteCountResponse%0A%20%20%7C%20SessionCountResponse%0A%20%20%7C%20SessionUrlCountResponse%0A%20%20%7C%20SessionWebsiteCountResponse%0A%20%20%7C%20IpTimeResponse%0A%20%20%7C%20IpUrlTimeResponse%0A%20%20%7C%20IpWebsiteTimeResponse%0A%20%20%7C%20SessionTimeResponse%0A%20%20%7C%20SessionUrlTimeResponse%0A%20%20%7C%20SessionWebsiteTimeResponse%3B%0A%0A%0Atype%20ArrayItem%3CT%3E%20%3D%20T%20extends%20(infer%20P)%5B%5D%20%3F%20P%20%3A%20never%0A%0Atype%20A%20%3D%20MonitorModel%5B%22data%22%5D%5Bnumber%5D%0Atype%20B%20%3D%20ArrayItem%3CMonitorModel%5B%22data%22%5D%3E%0A%0Adeclare%20const%20a%3A%20A%0Adeclare%20const%20b%3A%20B%0A%0Aconst%20u1%20%3D%20'url'%20in%20a%20%3F%20a.url%20%3A%20''%20%2F%2F%20error%0Aconst%20u2%20%3D%20'url'%20in%20b%20%3F%20b.url%20%3A%20''%20%2F%2F%20ok%0A%0Adeclare%20const%20t%3A%20MonitorModel%0A%0Aswitch%20(t.order_by)%20%7B%0A%20%20%20%20case%20RequestOrderBy.count%3A%0A%20%20%20%20%20%20%20%20t.data.reduce(((prev%2C%20next)%20%3D%3E%20next.count)%2C%200)%3B%20%2F%2F%20error%0A%20%20%20%20%20%20%20%20(t.data%20as%20%7B%20count%3A%20number%20%7D%5B%5D).reduce(((prev%2C%20next)%20%3D%3E%20next.count)%2C%200)%3B%20%2F%2Fok%0A%7D

**Expected behavior:**

reduce is working

**Actual behavior:**

a type error

**Playground Link:** 

**Related Issues:**

**Comment by andy-ms** [comment]
Looks like a duplicate of #7294
