### ISSUE TITLE
Implementing an interface with Partial params in the class are not throwing an error

### ISSUE THREAD

**Issue by HenriqueLimas** [Microsoft/TypeScript#27264]
**TypeScript Version:**  3.1.0-dev.20180921

**Search Terms:** Implement interface Partial

**Code**

```ts
type Person = {
    name: string
    lastName: string
}

interface MyInterface {
    method(person: Person)
}

class MyClass implements MyInterface {
    method(person: Partial<Person>) {}
}
```

**Expected behavior:**
Throws an error `Property 'method' in type 'MyClass' is not assignable to the same property in base type 'MyInterface'.` since method It's implementing a partial `Person` instead of a `Person`.

**Actual behavior:**
It's not throwing an error. It throws an error when we try to call the interface method with a partial type.

```ts

class App {
    constructor(myClass: MyInterface) {
        const person: Partial<Person> = { name: 'Joe' }
        myClass.method(person) // Error Argument of type 'Partial<Person>' is not assignable to parameter of type 'Person'.
    }
}
```

**Playground Link:** [link](https://www.typescriptlang.org/play/index.html#src=type%20Person%20%3D%20%7B%0D%0A%20%20%20%20name%3A%20string%0D%0A%20%20%20%20lastName%3A%20string%0D%0A%7D%0D%0A%0D%0Ainterface%20MyInterface%20%7B%0D%0A%20%20%20%20method(person%3A%20Person)%0D%0A%7D%0D%0A%0D%0Aclass%20MyClass%20implements%20MyInterface%20%7B%0D%0A%20%20%20%20method(person%3A%20Partial%3CPerson%3E)%20%7B%7D%0D%0A%7D%0D%0A%0D%0A%0D%0Aclass%20App%20%7B%0D%0A%20%20%20%20constructor(myClass%3A%20MyInterface)%20%7B%0D%0A%20%20%20%20%20%20%20%20const%20person%3A%20Partial%3CPerson%3E%20%3D%20%7B%20name%3A%20'Joe'%20%7D%0D%0A%20%20%20%20%20%20%20%20myClass.method(person)%0D%0A%20%20%20%20%7D%0D%0A%7D)

**Comment by RyanCavanaugh** [comment]
This is how subtyping works - subtypes are allowed to take parameters of a corresponding supertype
