### ISSUE TITLE
Non-existent method parameters incorrectly inferred as {}

### ISSUE THREAD

**Issue by dopeybobo** [microsoft/TypeScript#27263]
**TypeScript Version:**  3.1.0-dev.20180921

**Search Terms:** infer parameter

**Code**

```ts
type FirstArg<T> = T extends (_: infer U) => any ? U : never;

type X = FirstArg<() => void>;
type Y = FirstArg<(_: string) => void>;
```

**Expected behavior:**
```ts
X = never
Y = string
```

**Actual behavior:**
```ts
X = {}
Y = string
```

I expect that passing a function with an inferred parameter will either not match a function without an argument, or that argument would be inferred as undefined.

I would also expect similar behavior for an argument in nth position where the function has fewer than n parameters, e.g.

```ts
type SecondArg<T> = T extends (_: number, __: infer U) => any ? U : never;

type X = SecondArg<() => void>;
type Y = SecondArg<(_: string, __: number) => void>;
type Z = SecondArg<(_: number, __: number) => void>;
```

**Expected behavior:**
```ts
X = never
Y = never
Z = number
```

**Actual behavior:**
```ts
X = {}     // (method matches incorrectly and infers {} instead of undefined)
Y = never  // (method does not match, correct)
Z = number // (method matched, correct)
```

**Comment by j-oliveras** [comment]
See FAQs: [Why are functions with fewer parameters assignable to functions that take more parameters?](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-functions-with-fewer-parameters-assignable-to-functions-that-take-more-parameters) Because of this, it try to infer `U`. `{}` is the type used when a template type can not be inferenced.

**Comment by dopeybobo** [comment]
I understand the fewer parameter assignability principle, which is why I stated that it could either not match (ideal, but goes against the assignability principle) or infer undefined, which is what you would get accessing that argument, not {}.

**Comment by j-oliveras** [comment]
See this sample without using infer that shows what branch of conditional type is used:
```ts
type TrueBranch<T> = T extends (_: any) => any ? true : false;

type X = TrueBranch<() => void>; // true
type Y = TrueBranch<(_: string) => void>; // true
type Z = TrueBranch<(_: string, _2: string) => void>; // false
```
[At playground](https://www.typescriptlang.org/play/#src=type%20TrueBranch%3CT%3E%20%3D%20T%20extends%20(_%3A%20any)%20%3D%3E%20any%20%3F%20true%20%3A%20false%3B%0A%0Atype%20X%20%3D%20TrueBranch%3C()%20%3D%3E%20void%3E%3B%20%2F%2F%20true%0Atype%20Y%20%3D%20TrueBranch%3C(_%3A%20string)%20%3D%3E%20void%3E%3B%20%2F%2F%20true%0Atype%20Z%20%3D%20TrueBranch%3C(_%3A%20string%2C%20_2%3A%20string)%20%3D%3E%20void%3E%3B%20%2F%2F%20false).

As a workaround for your code:
```ts
type FirstArg<T> = T extends () => any ? never : T extends (_: infer U) => any ? U : never;

type X = FirstArg<() => void>; // never
type Y = FirstArg<(_: string) => void>; // string



type SecondArg<T> = T extends (_: any) => any ? never : T extends (_: number, __: infer U) => any ? U : never;

type Xs = SecondArg<() => void>; // never
type Ys = SecondArg<(_: string, __: number) => void>; // never
type Zs = SecondArg<(_: number, __: number) => void>; // number
```
[At playground](https://www.typescriptlang.org/play/#src=type%20FirstArg%3CT%3E%20%3D%20T%20extends%20()%20%3D%3E%20any%20%3F%20never%20%3A%20T%20extends%20(_%3A%20infer%20U)%20%3D%3E%20any%20%3F%20U%20%3A%20never%3B%0A%0Atype%20X%20%3D%20FirstArg%3C()%20%3D%3E%20void%3E%3B%20%2F%2F%20never%0Atype%20Y%20%3D%20FirstArg%3C(_%3A%20string)%20%3D%3E%20void%3E%3B%20%2F%2F%20string%0A%0A%0A%0Atype%20SecondArg%3CT%3E%20%3D%20T%20extends%20(_%3A%20any)%20%3D%3E%20any%20%3F%20never%20%3A%20T%20extends%20(_%3A%20number%2C%20__%3A%20infer%20U)%20%3D%3E%20any%20%3F%20U%20%3A%20never%3B%0A%0Atype%20Xs%20%3D%20SecondArg%3C()%20%3D%3E%20void%3E%3B%20%2F%2F%20never%0Atype%20Ys%20%3D%20SecondArg%3C(_%3A%20string%2C%20__%3A%20number)%20%3D%3E%20void%3E%3B%20%2F%2F%20never%0Atype%20Zs%20%3D%20SecondArg%3C(_%3A%20number%2C%20__%3A%20number)%20%3D%3E%20void%3E%3B%20%2F%2F%20number).

**Comment by andy-ms** [comment]
As @j-oliveras noted, `() => void` is assignable to `(_: {}) => any`. Since `() => void` has no parameter, there's no way to infer a type for `U`, and the default of `{}` is chosen.
If you don't want that behavior you could explicitly write `type FirstArg<T> = T extends () => any ? undefined : T extends (_: infer U) => any ? U : never;`.
