### ISSUE TITLE
TS Compiler API doesn't pick the correct default libs for target ES6

### ISSUE THREAD

**Issue by shivaprasad-basavaraj** [microsoft/TypeScript#27268]
**TypeScript Version:**  3.0.3

**Search Terms:**
compiler api es6

When trying to compile my project using the TypeScript compiler API, I ran into issues with using some of the features supported in ES6 (specifically Maps). I have attached a sample file down below which compiles perfectly fine with tsc but when you run it through the compiler API using the compilets code below, I get an error saying it can't find Map. You can see in the attached tsconfig.json that I have specified the target as ES2015. 

On some debugging I found that compiling through the compiler API misses a step where I think we convert the target string to an enum which the compiler code uses to determine the correct version of the libs to use. In my tsconfig.json if I set the target to 2 then my code compiles correctly through the compiler API but now tsc doesn't work.

**Code**
**main.js**
```
class main {
    private _map: Map<string, number>; 

    constructor()
    {
        this._map = new Map<string, number>();
        this._map.set('first', 1);
        this._map.set('second', 2);
    }
}
```
**compilets.js**
```
const fs = require("fs");
const path = require("path");
const ts = require("typescript");

class CompileTypeScript {
    static compileTypeScriptFiles () {
        let files = ['main.ts']
        let configContents = fs.readFileSync("tsconfig.json");
        let configJson = JSON.parse(configContents);
        let compilerOptions = configJson.compilerOptions;
        let program = ts.createProgram(files, compilerOptions);
        let emitResult = program.emit();
        let allDiagnostics = ts.getPreEmitDiagnostics(program).concat(emitResult.diagnostics);
        let exitCode = emitResult.emitSkipped ? 1 : 0;
        allDiagnostics.forEach(diagnostic => {
            if (diagnostic.file) {
                let { line, character } = diagnostic.file.getLineAndCharacterOfPosition(diagnostic.start);
                let message = ts.flattenDiagnosticMessageText(diagnostic.messageText, '\n');
                console.log(`${diagnostic.file.fileName} (${line + 1},${character + 1}): ${message}`);
                // failing the build if there is any diagnostic with error category available.
                if (diagnostic.category === 1) {
                    exitCode = 1;
                }
            } else {
                console.log(`${ts.flattenDiagnosticMessageText(diagnostic.messageText, '\n')}`);
            }
        });

        console.log(`Process exiting with code '${exitCode}'.`);
        process.exit(exitCode);
    }
}

CompileTypeScript.compileTypeScriptFiles();
```
**tsconfig.json**
```
{
  "compilerOptions": {
    "target": "es2015",
    "module": "none"
  }
}
```

**Expected behavior:**
main.ts compiles with no issues when compiled with tsc or using the Compiler API
**Actual behavior:**
Compiles fine with tsc but not with the Compiler API.

**Comment by RyanCavanaugh** [comment]
You have to parse the config file before handing it to `createProgram`.

Logged #27315
