### ISSUE TITLE
Bad type analysis with (very) complex generic types

### ISSUE THREAD

**Issue by sveyret** [Microsoft/TypeScript#27262]
**TypeScript Version:**  3.0.3

**Code**

I am using the [intl-ts](https://www.npmjs.com/package/intl-ts) library. The following function does not compile because it complains that `lang[result]` is not known to be executable:

```ts
function convertResult<
  T extends Messages &
    { [P in K]: (fieldName: string, p1: P1, p2: P2, p3: P3, p4: P4) => string },
  K extends keyof T,
  P1 = any,
  P2 = any,
  P3 = any,
  P4 = any
>(
  result: K | null,
  params: [P1, P2, P3, P4],
  lang?: Intl<T>,
  fieldName?: string
): boolean | string | null {
  if (result === null) {
    return lang ? null : true
  } else {
    if (lang) {
      return lang[result](fieldName, ...params)
    } else {
      return false
    }
  }
}
```

**Expected behavior:**

Typescript should understand that `lang[result]` is a function.

**Actual behavior:**

Compiler gives error: “Cannot invoke an expression whose type lacks a call signature. Type '{}' has no compatible call signatures.”

**Workaround:**

The error can be removed by deleting the `Messages` inheritance in type `T` and changing `lang` from `Intl<T>` to `T`.

**Playground Link:**

A playground example with all needed types is provided [here](https://www.typescriptlang.org/play/index.html#src=%2F%2F%20Messages%0D%0Atype%20MessageDirect%20%3D%20string%0D%0Atype%20MessageParams%3CP1%2C%20P2%2C%20P3%2C%20P4%2C%20P5%2C%20P6%3E%20%3D%20(arg1%3A%20P1%2C%20arg2%3A%20P2%2C%20arg3%3A%20P3%2C%20arg4%3A%20P4%2C%20arg5%3A%20P5%2C%20arg6%3A%20P6)%20%3D%3E%20string%0D%0Atype%20MessageFunction%3CT%20extends%20MessageDirect%20%7C%20MessageParams%3Cany%2C%20any%2C%20any%2C%20any%2C%20any%2C%20any%3E%3E%20%3D%20T%20extends%20string%0D%0A%20%20%3F%20()%20%3D%3E%20string%0D%0A%20%20%3A%20T%0D%0Ainterface%20Messages%20%7B%0D%0A%20%20%5Bkey%3A%20string%5D%3A%20MessageDirect%20%7C%20MessageParams%3Cany%2C%20any%2C%20any%2C%20any%2C%20any%2C%20any%3E%0D%0A%7D%0D%0A%0D%0A%2F%2F%20Intl%0D%0Ainterface%20IntlPrototype%3CT%20extends%20Messages%3E%20%7B%0D%0A%20%20%20%20readonly%20%24preferences%3A%20ReadonlyArray%3Cstring%3E%0D%0A%20%20%24changePreferences(preferences%3A%20ReadonlyArray%3Cstring%3E%2C%20createGenerics%3F%3A%20boolean)%3A%20this%0D%0A%20%20%2F%2F%20etc.%0D%0A%7D%0D%0Atype%20IntlMessages%3CT%20extends%20Messages%3E%20%3D%20%7B%20%5BP%20in%20keyof%20T%5D%3A%20MessageFunction%3CT%5BP%5D%3E%20%7D%0D%0Atype%20Intl%3CT%20extends%20Messages%3E%20%3D%20IntlPrototype%3CT%3E%20%26%20IntlMessages%3CT%3E%0D%0A%0D%0Afunction%20convertResult%3C%0D%0A%20%20T%20extends%20Messages%20%26%0D%0A%20%20%20%20%7B%20%5BP%20in%20K%5D%3A%20(fieldName%3A%20string%2C%20p1%3A%20P1%2C%20p2%3A%20P2%2C%20p3%3A%20P3%2C%20p4%3A%20P4)%20%3D%3E%20string%20%7D%2C%0D%0A%20%20K%20extends%20keyof%20T%2C%0D%0A%20%20P1%20%3D%20any%2C%0D%0A%20%20P2%20%3D%20any%2C%0D%0A%20%20P3%20%3D%20any%2C%0D%0A%20%20P4%20%3D%20any%0D%0A%3E(%0D%0A%20%20result%3A%20K%20%7C%20null%2C%0D%0A%20%20params%3A%20%5BP1%2C%20P2%2C%20P3%2C%20P4%5D%2C%0D%0A%20%20lang%3F%3A%20Intl%3CT%3E%2C%0D%0A%20%20fieldName%3F%3A%20string%0D%0A)%3A%20boolean%20%7C%20string%20%7C%20null%20%7B%0D%0A%20%20if%20(result%20%3D%3D%3D%20null)%20%7B%0D%0A%20%20%20%20return%20lang%20%3F%20null%20%3A%20true%0D%0A%20%20%7D%20else%20%7B%0D%0A%20%20%20%20if%20(lang)%20%7B%0D%0A%20%20%20%20%20%20return%20lang%5Bresult%5D(fieldName%2C%20...params)%0D%0A%20%20%20%20%7D%20else%20%7B%0D%0A%20%20%20%20%20%20return%20false%0D%0A%20%20%20%20%7D%0D%0A%20%20%7D%0D%0A%7D)

**Related Issues:**

You also can refer to the question on [StackOverflow](https://stackoverflow.com/questions/52439751/typescript-does-not-detect-that-property-is-a-function)

**Comment by andy-ms** [comment]
Can you come up with an example that doesn't depend on external frameworks?
