### ISSUE TITLE
tsc -w should not recompile if a file is created into an excluded folder

### ISSUE THREAD

**Issue by rolivegab** [Microsoft/TypeScript#27279]
**Search Terms:**
tsc -w watch exclude subfolder recompile

**tsconfig.json**

```{
  "compilerOptions": {
    "target": "es5",                          /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017','ES2018' or 'ESNEXT'. */
    "module": "commonjs",                     /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', or 'ESNext'. */
    "lib": ["es7"],                             /* Specify library files to be included in the compilation. */
    "sourceMap": true,                     /* Generates corresponding '.map' file. */
    "outDir": "dist",                        /* Redirect output structure to the directory. */
    "rootDir": "src",                       /* Specify the root directory of input files. Use to control the output directory structure with --outDir. */
    "strict": true,                           /* Enable all strict type-checking options. */
    "allowSyntheticDefaultImports": true,     /* Allow default imports from modules with no default export. This does not affect code emit, just typechecking. */
    "esModuleInterop": true,                  /* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */
    "watch": true,
  },
  "exclude": [
    "node_modules",
    "dist",
    "upload",
  ]
}
```

**Folder structure**
![image](https://user-images.githubusercontent.com/7359906/45907979-a4c4ac80-bdd0-11e8-992e-f9052aac57da.png)

**Expected behavior:**
When i create a file into `upload/`, tsc should not detect file changes.

**Actual behavior:**

When i create a file into `upload/`, server detects file changes and do incremental compilation.
i'm using `"tsc-watch --onSuccess \"node dist/server.js\""`, so, my server is restarted whenever user upload a file.
![image](https://user-images.githubusercontent.com/7359906/45908262-0afdff00-bdd2-11e8-831f-04df970223a1.png)

Is there any way to tsc -w not detect file creation in an excluded project's subfolder?

Thanks in advance.

**Comment by sheetalkamat** [comment]
This is by design. Normally even though file is excluded by the config file, it could get included by module resolution and could be missing. So we cant just ignore file addition or removal of file in exclude directory.

**Comment by xtrinch** [comment]
Any proposals on how to solve the problem, if this is by design so? It's still a problem.

**Comment by davidnjohansson** [comment]
Would very much appreciate some solution to this as well.

**Comment by paramaggarwal** [comment]
> This is by design. Normally even though file is excluded by the config file, it could get included by module resolution and could be missing. So we cant just ignore file addition or removal of file in exclude directory.

@sheetalkamat the excluded file should be part of the build, yes - but it should not trigger a rebuild on change if it is excluded.

**Comment by 128keaton** [comment]
I've been dealing with this issue on two separate projects. Nest uses `tsc --watch` internally for their build triggering, and I'd love to have a folder NOT trigger a rebuild of a project. Super irritating.

**Comment by rettgerst** [comment]
also experiencing this issue, also with nest - we are using sqlite and _any database update_ is triggering a rebuild and thus a server restart.

**Comment by massimeddu** [comment]
Same issue here. Anyone is able to solve this?

**Comment by ckanthony** [comment]
same here

**Comment by peresbruno** [comment]
Same issue here.

**Comment by sudiptosen** [comment]
In my case tsc-watch restarted on every file upload with `multer` config as

`let uploadConfig = multer({dest: './uploads/temp'});`

Just for dev, I started using '**../uploads/temp**'. Puts it outside the watch zone

**Comment by JiProchazka** [comment]
> also experiencing this issue, also with nest - we are using sqlite and _any database update_ is triggering a rebuild and thus a server restart.

Exactly the same issue with LevelDB and NestJS

**Comment by darkyelox** [comment]
I have the same problem with Nest JS, and no solution for this is making the development for certain cases like simple file upload a real pain.

**Comment by helmerdavila** [comment]
> Same issue here. With Nest.js.

https://github.com/Microsoft/TypeScript/issues/27279#issuecomment-625998815

Solved it.

And put your upload directory inside of dir for example.

**Comment by mankittens** [comment]
The approach in #27279 (comment) does not resolve this issue for me.

I'm running tsc -w and webpack side-by-side, with tsc purely checking for ts errors and webpack producing a js bundle.

Every time webpack places a new hot-update.js or hot-update.json file in the build folder, that triggers tsc to recompile. I've confirmed this with the `--exendedDiagnostics` flag:

```bash
DirectoryWatcher:: Triggered with /Users/{redacted}/GitHub/{redacted}/packages/{redacted}/build/main.852665aec4d5e06ecc09.hot-update.js
``` 

My tsconfig:
```json
{
  ...
  "include": ["packages/*/src/**/*"]
}
```

Please give us a way to control which files can or cannot trigger a recompile!

**Comment by sean9999** [comment]
this seems poorly designed. I do not think the stated reason is sufficient. shift the burdon/power to the developers by allowing this exclusion in watch mode.

**Comment by thallada** [comment]
I'm hopeful that https://github.com/microsoft/TypeScript/pull/39030 will fix this (merged, but not released yet).

**Comment by DanazSdiq** [comment]
If anyone is still facing the same issue, I solved this by adding the `include` option in my tsconfig.json. An example:
`"include": [
    "src"
]`
At the moment, the `exclude` option does not work.

**Comment by liv1n9** [comment]
It doesn't work for me
`tsconfig.json`:
```json
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "noImplicitAny": true,
    "target": "es2017",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true,
    "resolveJsonModule": true,
    "strictNullChecks": false,
  },
  "exclude": ["node_modules", "dist", "data", "uploads"],
  "include": ["src"]
}
```
`data` is docker mount volumes and `uploads` is file upload folder

**Comment by max-sv-ma** [comment]
having same issue.
``` "include": [
    "src/*"
  ],
  "exclude": [
    "node_modules",
    "**/*.spec.ts",
    "build/**/*.js",
    "tempDataStore/*"
  ]}
  ```
  
  even tho the files are being generated within ```tempDataStore``` which is outside src. project still being recompiled
  ts version 3.9.7

**Comment by dawsnap** [comment]
Same happening here. Writing a buffer into a file will make cut the writing process and recompile the whole project. So irritating. 

My solution was using a hidden folder /.downloads/. That way it is excluded by default, in case that helps anyone!

**Comment by fabstu** [comment]
Ignoring mydb.sqlite-journal worked for me with excludeFiles in tsconfig.json. My issue was that another package using the database package triggered the depenency, and so had to use .. to navigate to the files that triggered the change.

Used tsc --watch --extendedDiagnostics to see the files that triggered the rebuild.

```json
	"watchOptions": {
		"excludeFiles": [
			"prisma/mydb.sqlite-journal",
			"../database/prisma/mydb.sqlite-journal",
			"../../node_modules/@repo/db/prisma/mydb.sqlite-journal",
			"**/mydb.sqlite-journal"
		]
	}
```
