### ISSUE TITLE
Transform generic of union to union of generic type.

### ISSUE THREAD

**Issue by ccorcos** [microsoft/TypeScript#27272]
I've run into the following type of inferencing problem several times now:

```ts
// These are database tables.
type Table = "a" | "b" | "c"

// These are the types of records in the database.
type TableToRecord = {
	a: { a: number }
	b: { b: string }
	c: { c: string[] }
}

// This object tells you a record with its table.
type RecordWithTable<T extends Table> = {
	table: T,
	record: TableToRecord[T]
}

// I might want to have a function to process any record in my database.
// However, there's a type error that doesn't let you narrow the generic type
// argument.
function processRecord<T extends Table>(recordWithTable: RecordWithTable<T>) {
	if (recordWithTable.table === "a") {
		const x = recordWithTable.record.a // error
	}
}
```

Not entirely sure why Typescript can't handle this case... I assume someone is going to say it has to do with type widening or something. Regardless, we can solve this problem if we transform the "generic of a union type" to a "union of a generic type". For example, the following will type narrow properly.

```ts
function processRecord2(
	recordWithTable:
		| RecordWithTable<"a">
		| RecordWithTable<"b">
		| RecordWithTable<"c">
) {
	if (recordWithTable.table === "a") {
		const x = recordWithTable.record.a // no error
	}
}
```

## Suggestion

What would be really cool is if there was a baked in Typescript type that let you make this transformation. Maybe something like this:

```ts
type RecordWithTableUnion = MapUnion<Table, RecordWithTable>

// Equivalent to explicitly writing it out.
type RecordWithTableUnion = 
	| RecordWithTable<"a">
	| RecordWithTable<"b">
	| RecordWithTable<"c">
```

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

[playground](http://www.typescriptlang.org/play/#src=%2F%2F%20These%20are%20database%20tables%0D%0Atype%20Table%20%3D%20%22a%22%20%7C%20%22b%22%20%7C%20%22c%22%0D%0A%0D%0A%2F%2F%20These%20are%20the%20types%20of%20records%20in%20the%20database.%0D%0Atype%20TableToRecord%20%3D%20%7B%0D%0A%09a%3A%20%7B%20a%3A%20number%20%7D%0D%0A%09b%3A%20%7B%20b%3A%20string%20%7D%0D%0A%09c%3A%20%7B%20c%3A%20string%5B%5D%20%7D%0D%0A%7D%0D%0A%0D%0A%2F%2F%20This%20object%20tells%20you%20a%20record%20with%20its%20table.%0D%0Atype%20RecordWithTable%3CT%20extends%20Table%3E%20%3D%20%7B%0D%0A%09table%3A%20T%2C%0D%0A%09record%3A%20TableToRecord%5BT%5D%0D%0A%7D%0D%0A%0D%0A%2F%2F%20I%20might%20want%20to%20have%20a%20function%20to%20process%20any%20record%20in%20my%20database.%0D%0A%2F%2F%20However%2C%20there's%20a%20type%20error%20that%20doesn't%20let%20you%20narrow%20the%20generic%20type%0D%0A%2F%2F%20argument.%20Not%20entirely%20sure%20why...%0D%0Afunction%20processRecord%3CT%20extends%20Table%3E(recordWithTable%3A%20RecordWithTable%3CT%3E)%20%7B%0D%0A%09if%20(recordWithTable.table%20%3D%3D%3D%20%22a%22)%20%7B%0D%0A%09%09const%20x%20%3D%20recordWithTable.record.a%20%2F%2F%20error%0D%0A%09%7D%0D%0A%7D%0D%0A%0D%0A%2F%2F%20However%2C%20what%20does%20work%20is%20if%20you%20map%20over%20the%20union%20type%20to%20explicity%0D%0A%2F%2F%20create%20a%20union%20of%20the%20generic%20types%20like%20this.%0D%0Afunction%20processRecord2(%0D%0A%09recordWithTable%3A%0D%0A%09%09%7C%20RecordWithTable%3C%22a%22%3E%0D%0A%09%09%7C%20RecordWithTable%3C%22b%22%3E%0D%0A%09%09%7C%20RecordWithTable%3C%22c%22%3E%0D%0A)%20%7B%0D%0A%09if%20(recordWithTable.table%20%3D%3D%3D%20%22a%22)%20%7B%0D%0A%09%09const%20x%20%3D%20recordWithTable.record.a%20%2F%2F%20no%20error%0D%0A%09%7D%0D%0A%7D)

**Comment by AlCalzone** [comment]
This gets you there half of the way:
```ts
type Union = "a" | "b" | "c";
type Generic<T> = { something: T };
type GenericOfUnion<U extends string> = { [K in U]: Generic<K> }[U];
type Foo = GenericOfUnion<Union>; // Generic<"a"> | Generic<"b"> | Generic<"c">
```
You cannot pass `Generic` as an operator though, as that would require higher kinded types (if I understand correctly).

**Comment by jack-williams** [comment]
> Not entirely sure why Typescript can't handle this case... I assume someone is going to say it has to do with type widening or something. Regardless, we can solve this problem if we transform the "generic of a union type" to a "union of a generic type". For example, the following will type narrow properly.

TypeScript only narrows by filtering unions, or by assertion (adding `& T`). Neither of these cases help in your example, though you can get the right 'narrow-by-assertion' behavior with a type guard: 

```ts
function narrow<T extends Table>(t:T, x: any): x is RecordWithTable<T> {
  return x.table === t;
}

function processRecord<T extends Table>(recordWithTable: RecordWithTable<T>) {
	if (narrow("a", recordWithTable)) {
		const x: number = recordWithTable.record.a // no error
	}
}
```

**Comment by ccorcos** [comment]
> TypeScript only narrows by filtering unions, or by assertion (adding & T)

That's actually really helpful to think about. Thanks.

---

Both of these are helpful suggestions. @jack-williams's approach is simple but doesn't produce the correct type. `processRecord` works without the generic at all. That's wrong.

```ts
function processRecord(recordWithTable: RecordWithTable<Table>) {
	if (narrow("a", recordWithTable)) {
		const x = recordWithTable.record.a // error
	}
}

function narrow<T extends Table>(t:T, x: RecordWithTable<Table>): x is RecordWithTable<T> {
  return x.table === t;
}
```

@AlCalzone works pretty nicely actually.

```
type RecordsWithTables<U extends Table> = { [K in U]: RecordWithTable<K> }[U];
type x = RecordsWithTables<Table>
```

I still think it would still be nice if there was some syntax available for doing this.

**Comment by jack-williams** [comment]
@ccorcos 
>  @jack-williams's approach is simple but doesn't produce the correct type. processRecord works without the generic at all. That's wrong.

Yes my type doesn't produce a union of constrained values (is that what you mean?), but it does let you narrow them.

Another encoding of `RecordsWithTables`:

```ts
type RecordsWithTables<T> = T extends Table ? RecordWithTable<T> : never;
type y = RecordsWithTables<Table>; 
```
