### ISSUE TITLE
Array reduce callback (reducer) and default parameters

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/TypeScript#27277]
**TypeScript Version:**  3.0.3

**Search Terms:** redux reducer default parameter state undefined generic

**Code**

```ts
type Reducer<S> = (state: S | undefined, action: any) => S;

declare const actions: Array<any>;

type State = { counter: number };

declare const reducer: Reducer<State>;
const seed: State = { counter: 1 };
// Expected `State` but got `State | undefined`
const result = actions.reduce(reducer, seed);
```

This is very common in Redux. Reducers always allow the first `state` (`previousValue`) to be `undefined`. Users are encouraged to [use default parameters to fill in the "initial state"](https://redux.js.org/recipes/structuringreducers/initializingstate).

Perhaps we could provide a more specific `reduce` overload in the form of:

``` ts
reduce<U>(callbackfn: (previousValue: U | undefined, currentValue: T, currentIndex: number, array: T[]) => U, initialValue: U): U;
```

**Comment by bcherny** [comment]
@OliverJAsh This seems to be fixed in the latest tsc -- can you still repro it?

```
npm install typescript@next
```

**Comment by OliverJAsh** [comment]
Confirmed that appears to fix it. Any idea what the fix was, out of interest?

**Comment by OliverJAsh** [comment]
I still reproduce this on 3.1.6. Can we re-open?

**Comment by OliverJAsh** [comment]
Hi @RyanCavanaugh, this is still an issue. Can we re-open?

**Comment by OliverJAsh** [comment]
Reposted to https://github.com/Microsoft/TypeScript/issues/30686
