### ISSUE TITLE
import for side effects only does not check path

### ISSUE THREAD

**Issue by poseidonCore** [Microsoft/TypeScript#27289]
**TypeScript Version:**  3.1.0 [TS Playground 23 SEP 2018]
When using `import` for side effects only, the path does not seem to be checked.  

Using `import` for side effects is useful in extending base classes and preparing an environment and should be checked in the same way as normal `import` statements.

**Search Terms:**
import for side effects only
bare import
unnamed import
missing file

**Code**

```ts
import * as x from "./someMissingFile";
/* <<<<< ERROR
Cannot find module './someMissingFile'.
ERROR >>>>> */

import "./someMissingFile";
```

**Expected behavior:**
Both should show the same error.

**Actual behavior:**
Only the first will validate the path, in either Intellisense or TS compilation.

**Playground Link:** [TS Playground](https://www.typescriptlang.org/play/#src=import%20*%20as%20x%20from%20%22.%2FsomeMissingFile%22%3B%0D%0A%0D%0Aimport%20%22.%2FsomeMissingFile%22%3B%0D%0A%0D%0A)

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
See #20576, #20767, #20534, #23961

**Comment by poseidonCore** [comment]
All of these references demonstrate the conflicting and frustrating nature of this issue. If you are not planning to fix this shortcoming, then you should accept it as a language feature and document it ... at least as a warning ...

A few lines under the heading "Import a module for side-effects only" would have avoided many of these duplicate issues:

https://www.typescriptlang.org/docs/handbook/modules.html
