### ISSUE TITLE
String Literals with Union Types result in confusing behaviour with method overloads

### ISSUE THREAD

**Issue by MartinLoeper** [microsoft/TypeScript#27297]
**TypeScript Version:**  3.0.3

**Search Terms:** literal type, overload, not recognized, union type

**Code**

```ts
type GermanCountryName = "Germany";
type GermanCountryAbbrevition = "DE";
type AustrianCountryName = "Austria";
type AustrianCountryAbbrevition = "AT";
type GermanStateAbbreviation = "BW" | "BY";
type GermanRegionAbbreviation = "AUG";
type AustrianStateAbbreviation = "St";
type AustrianRegionAbbreviation = "TEST";

// define country identifiers
type GermanCountryIdentifier = GermanCountryName | GermanCountryAbbrevition;
type AustrianCountryIdentifier = AustrianCountryName | AustrianCountryAbbrevition;
export type CountryName = GermanCountryName | AustrianCountryName;
export type CountryAbbreviation = GermanCountryAbbrevition | AustrianCountryAbbrevition;
export type CountryIdentifier = GermanCountryIdentifier | AustrianCountryIdentifier;
export type StateIdentifier = GermanStateAbbreviation | AustrianStateAbbreviation;
export type RegionIdentifier = GermanRegionAbbreviation | AustrianRegionAbbreviation;

// merge state and region identifiers
export type AdministrativeUnitIdentifier = StateIdentifier | RegionIdentifier;

export function MomentHolidayFactoryMethod(country: GermanCountryIdentifier,
    ...administrativeUnits: Array<GermanStateAbbreviation | GermanRegionAbbreviation | "ALL">): any;

export function MomentHolidayFactoryMethod(country: AustrianCountryIdentifier,
    ...administrativeUnits: Array<AustrianStateAbbreviation | AustrianRegionAbbreviation | "ALL">): any;

/**
 * Returns a moment holiday configuration for the given entities.
 * If you provide a country only, you get the country holidays only.
 * If you provide the state identifier "ALL", then all state holidays will be merged with the country holidays.
 * If you provide any states identifiers other then "ALL", then those states's holidays will be merged with
 * the country holidays.
 *
 * @param country the country to look up
 * @param dbConfig a database config which instructs the module to load external holiday definitions from a database
 * @param administrativeUnits the administrative unit(s) to look up
 * @returns a moment holiday configuration which is configured to compute holidays for the given country and units
 */
export function MomentHolidayFactoryMethod(
    country: CountryIdentifier,
    ...administrativeUnits: Array<AdministrativeUnitIdentifier | "ALL">): any {

    // do something
}

// use the factory method
const countryIdentifier = "Germany" as CountryIdentifier;
const instance = MomentHolidayFactoryMethod(countryIdentifier);  // ts error: Argument of type 'CountryIdentifier' is not assignable to parameter of type 'AustrianCountryIdentifier'.
```

**Expected behavior:**
The variable `countryIdentifier` should be a valid first argument for the `MomentHolidayFactoryMethod`.

It does not match any overloads but it matches the function implementation instead.
I do not know why the typescript compiler tries to convert the `CountryIdentifier` into an `AustrianCountryIdentifier`.

**Actual behavior:**
The typescript compiler should skip the first overload and use the function implementation instead.

**Playground Link:** [Playground](http://www.typescriptlang.org/play/#src=type%20GermanCountryName%20%3D%20%22Germany%22%3B%0D%0Atype%20GermanCountryAbbrevition%20%3D%20%22DE%22%3B%0D%0Atype%20AustrianCountryName%20%3D%20%22Austria%22%3B%0D%0Atype%20AustrianCountryAbbrevition%20%3D%20%22AT%22%3B%0D%0Atype%20GermanStateAbbreviation%20%3D%20%22BW%22%20%7C%20%22BY%22%3B%0D%0Atype%20GermanRegionAbbreviation%20%3D%20%22AUG%22%3B%0D%0Atype%20AustrianStateAbbreviation%20%3D%20%22St%22%3B%0D%0Atype%20AustrianRegionAbbreviation%20%3D%20%22TEST%22%3B%0D%0A%0D%0A%2F%2F%20define%20country%20identifiers%0D%0Atype%20GermanCountryIdentifier%20%3D%20GermanCountryName%20%7C%20GermanCountryAbbrevition%3B%0D%0Atype%20AustrianCountryIdentifier%20%3D%20AustrianCountryName%20%7C%20AustrianCountryAbbrevition%3B%0D%0Aexport%20type%20CountryName%20%3D%20GermanCountryName%20%7C%20AustrianCountryName%3B%0D%0Aexport%20type%20CountryAbbreviation%20%3D%20GermanCountryAbbrevition%20%7C%20AustrianCountryAbbrevition%3B%0D%0Aexport%20type%20CountryIdentifier%20%3D%20GermanCountryIdentifier%20%7C%20AustrianCountryIdentifier%3B%0D%0Aexport%20type%20StateIdentifier%20%3D%20GermanStateAbbreviation%20%7C%20AustrianStateAbbreviation%3B%0D%0Aexport%20type%20RegionIdentifier%20%3D%20GermanRegionAbbreviation%20%7C%20AustrianRegionAbbreviation%3B%0D%0A%0D%0A%2F%2F%20merge%20state%20and%20region%20identifiers%0D%0Aexport%20type%20AdministrativeUnitIdentifier%20%3D%20StateIdentifier%20%7C%20RegionIdentifier%3B%0D%0A%0D%0Aexport%20function%20MomentHolidayFactoryMethod(country%3A%20GermanCountryIdentifier%2C%0D%0A%20%20%20%20...administrativeUnits%3A%20Array%3CGermanStateAbbreviation%20%7C%20GermanRegionAbbreviation%20%7C%20%22ALL%22%3E)%3A%20any%3B%0D%0A%0D%0Aexport%20function%20MomentHolidayFactoryMethod(country%3A%20AustrianCountryIdentifier%2C%0D%0A%20%20%20%20...administrativeUnits%3A%20Array%3CAustrianStateAbbreviation%20%7C%20AustrianRegionAbbreviation%20%7C%20%22ALL%22%3E)%3A%20any%3B%0D%0A%0D%0A%2F**%0D%0A%20*%20Returns%20a%20moment%20holiday%20configuration%20for%20the%20given%20entities.%0D%0A%20*%20If%20you%20provide%20a%20country%20only%2C%20you%20get%20the%20country%20holidays%20only.%0D%0A%20*%20If%20you%20provide%20the%20state%20identifier%20%22ALL%22%2C%20then%20all%20state%20holidays%20will%20be%20merged%20with%20the%20country%20holidays.%0D%0A%20*%20If%20you%20provide%20any%20states%20identifiers%20other%20then%20%22ALL%22%2C%20then%20those%20states's%20holidays%20will%20be%20merged%20with%0D%0A%20*%20the%20country%20holidays.%0D%0A%20*%0D%0A%20*%20%40param%20country%20the%20country%20to%20look%20up%0D%0A%20*%20%40param%20dbConfig%20a%20database%20config%20which%20instructs%20the%20module%20to%20load%20external%20holiday%20definitions%20from%20a%20database%0D%0A%20*%20%40param%20administrativeUnits%20the%20administrative%20unit(s)%20to%20look%20up%0D%0A%20*%20%40returns%20a%20moment%20holiday%20configuration%20which%20is%20configured%20to%20compute%20holidays%20for%20the%20given%20country%20and%20units%0D%0A%20*%2F%0D%0Aexport%20function%20MomentHolidayFactoryMethod(%0D%0A%20%20%20%20country%3A%20CountryIdentifier%2C%0D%0A%20%20%20%20...administrativeUnits%3A%20Array%3CAdministrativeUnitIdentifier%20%7C%20%22ALL%22%3E)%3A%20any%20%7B%0D%0A%0D%0A%20%20%20%20%2F%2F%20do%20something%0D%0A%7D%0D%0A%0D%0A%2F%2F%20use%20the%20factory%20method%0D%0Aconst%20countryIdentifier%20%3D%20%22Germany%22%20as%20CountryIdentifier%3B%0D%0Aconst%20instance%20%3D%20MomentHolidayFactoryMethod(countryIdentifier)%3B%20%20%2F%2F%20ts%20error%3A%20Argument%20of%20type%20'CountryIdentifier'%20is%20not%20assignable%20to%20parameter%20of%20type%20'AustrianCountryIdentifier'.)

**Related Issues:** -

**Comment by j-oliveras** [comment]
The implementation is not part of overload list. See [Function overloads into handbook](http://www.typescriptlang.org/docs/handbook/functions.html) (last paragraph).

To solve this, add an other overload coping the implementation signature;
```ts
export function MomentHolidayFactoryMethod(country: GermanCountryIdentifier,
    ...administrativeUnits: Array<GermanStateAbbreviation | GermanRegionAbbreviation | "ALL">): any;

export function MomentHolidayFactoryMethod(country: AustrianCountryIdentifier,
    ...administrativeUnits: Array<AustrianStateAbbreviation | AustrianRegionAbbreviation | "ALL">): any;

// Add this overload
export function MomentHolidayFactoryMethod(
    country: CountryIdentifier,
    ...administrativeUnits: Array<AdministrativeUnitIdentifier | "ALL">): any;

/**
 * Returns a moment holiday configuration for the given entities.
 * If you provide a country only, you get the country holidays only.
 * If you provide the state identifier "ALL", then all state holidays will be merged with the country holidays.
 * If you provide any states identifiers other then "ALL", then those states's holidays will be merged with
 * the country holidays.
 *
 * @param country the country to look up
 * @param dbConfig a database config which instructs the module to load external holiday definitions from a database
 * @param administrativeUnits the administrative unit(s) to look up
 * @returns a moment holiday configuration which is configured to compute holidays for the given country and units
 */
export function MomentHolidayFactoryMethod(
    country: CountryIdentifier,
    ...administrativeUnits: Array<AdministrativeUnitIdentifier | "ALL">): any {

    // do something
}
```

**Comment by dhruvrajvanshi** [comment]
@j-oliveras There still seems to be some unexpected behaviour though.

```ts
const countryIdentifier = "Germany" as CountryIdentifier; // doesn't work
const countryIdentifier: CountryIdentifier = "Germany"; // works
const countryIdentifier= "Germany"; // works
```

Shouldn't forced cast using `as CountryIdentifier` behave exactly like the other cases?
Even though using `as` is correctly typing `countryIdentifier`, in the first (broken) case, it still
tries to use the wrong overload, unlike without cast and without annotation.

**Comment by MartinLoeper** [comment]
@j-oliveras Thank you for clarification! This makes sense to me now.
@dhruvrajvanshi I agree, this is really unexpected behaviour if one does not know the paragraph in the handbook which was mentioned by @j-oliveras.
