### ISSUE TITLE
Pick Conditional or Conditional extends Pick

### ISSUE THREAD

**Issue by wesleyolis** [microsoft/TypeScript#27300]
## Search Terms

Pick 
Conditional Pick
Pick Conditional
Pick Extends

## Suggestion

It would be great if there was a variant of Pick that could support a conditional set of extends arguments, auxiliary params for record re-writting and extraction. Current in many cases of more advanced typing working, one wants to pick a subset of keys that match a certain shape, this is possible as of current, however, results in most disgusting typing descriptions.
A framework support Pick makes it a little cleaner, however, one still must extract the keys to feed into Pick, which results in the most disgusting typings descriptions. I though, that it would be really great, if simple PickConditional, PickInverseConditinal could be supported, were
the typings would be kept clean and readable.

It would be create when doing schema type work, were like to extract readonly fields and non readonly fields so that we can generate clean types for new records, update records and different forms of resulting records.

## Use Cases

```.ts
interface IWrapper<T>
{
    __wrapper: T// typically one would now use a symbol name for the key, to avoid conflicts.
}

interface IReadOnly<T>
{
    __readonly: T// typically one would now use a symbol name for the key, to avoid conflicts.
}

interface Obj
{
 a: number,
b : string,
c : boolean,
d : IWrapper<'wanted-d'>
e : string,
g : IWrapper<'wanted-g'>
h : IReadOnly<'readonly-h'>,
i : string
j: number
}
```

## Examples
```.ts
### ReadOnly Extraction
type ObjReadOnly = PickConditional<Obj, IReadOnly<any>>
// results in
{
h: IReadOnly<'readonly-h'>
}
```
### ReadOnly with Wrapper infer type Extraction.
```.ts
type ObjReadOnly = PickConditional<Obj, IReadOnly<infer A> ? A : never>
// results in, and every else the type description, remains this simple statement above, there are now key of shown anywhere.
{
h: 'readonly-h'
}
```

### ReadOnly And Wrapper Extraction
```.ts
type ObjReadOnly = PickConditional<Obj, IReadOnly<infer A> ? A : never, IWrapper<any>>
// results in, and every else the type description, remains this simple statement above, there are now key of shown anywhere.
{

d : IWrapper<'wanted-d'>
g : IWrapper<'wanted-g'>
h: 'readonly-h'
}
```

### ReadOnly And Wrapper Extraction and keys
```.ts
type ObjReadOnly = PickConditional<Obj, 'b' | 'a' | 'j', IReadOnly<infer A> ? A : never, IWrapper<any>>

{
 a: number,
b : string,
d : IWrapper<'wanted-d'>
g : IWrapper<'wanted-g'>
h: 'readonly-h'
j: number
}
```

### Inverse ReadOnly And Wrapper Extraction and keys
```.ts
type ObjReadOnly = PickConditionalInverse<Obj, 'b' | 'a' | 'j', IReadOnly<infer A> ? A : never, IWrapper<any>>
{

c : boolean,
e : string,
i : string
}
```

### ReadOnly And Wrapper Extraction negatives conditionals and keys
```.ts
type ObjReadOnly = PickConditional<Obj, 'b' | 'a' | 'j',
IReadOnly<infer A> ? A : never,
IWrapper<infer W> extends infer TWrapper ? IWrapper<'wanted-d'> ? never : TWrapper>

{
 a: number,
b : string,
g : IWrapper<'wanted-g'>
h: 'readonly-h'
j: number
}
```

### ReadOnly And Wrapper Extraction and keys
```.ts
type ObjReadOnly = PickConditional<Obj, 'b' | 'a' | 'j',
IReadOnly<infer A> ? A : never,
IWrapper<infer W> extends infer TWrapper  ? IWrapper<'wanted-d'> ? never : W>

{
 a: number,
b : string,
g :'wanted-g'
h: 'readonly-h'
j: number
}
```
## Checklist

My suggestion meets these guidelines:
* [X] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by RyanCavanaugh** [comment]
You can already do this; see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/28691 for a similar example

**Comment by wesleyolis** [comment]
@RyanCavanaugh Hi, I you suggestion that I write the feature and make a pull request?
I am not following you a 100%! I have nearly managed to redo all the mongoose typings, with some things sure you guys be interested to see, what we managed to do. Now to get it into production.. wish me luck. Type script in ways is very powerfully. Just one or town more little features and be able to do everything needed and more.

**Comment by wesleyolis** [comment]
@RyanCavanaugh Clearly stuck in a mental block! That should do thanx!
