### ISSUE TITLE
Be able enforce await on usage of specific async functions

### ISSUE THREAD

**Issue by jpike88** [Microsoft/TypeScript#27303]
## Search Terms

force async await

## Suggestion

A function could have syntax like `async* function`, where that function MUST be have ```await``` used on it. This way people won't forgot to write the function call without awaiting it.

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by jpike88** [comment]
Ah you're a legend, thanks

**Comment by RyanCavanaugh** [comment]
See also #13376
