### ISSUE TITLE
String union type  lost when importing from json

### ISSUE THREAD

**Issue by bali182** [Microsoft/TypeScript#27304]
When importing from a json file, some type information seems to be lost. Would it be worth to keep the strictest type information about the imported type? Eg.: in the example instead of inferring the `{ type: string }` maybe infer `{ type: "frog" }` instead?

**TypeScript Version:**  3.0.3

**Search Terms:**
json import string union type

**Code**

*sample.json*
```json
{
  "type": "frog"
}
```
*sample.ts*
```ts
import sample from './sample.json'

type AnimalType = 'frog' | 'cat' | 'dog'
type Animal = { type: AnimalType }

const a: Animal = sample
```

**Expected behavior:**
No compliation error

**Actual behavior:**

> Compile error: Type '{ "type": string; }' is not assignable to type 'Animal'.
>   Types of property 'type' are incompatible.
>     Type 'string' is not assignable to type 'AnimalType'.

**Comment by s-ve** [comment]
It's been discussed in #26552
