### ISSUE TITLE
IntelliSense popup object inspector should display type signature information at the very top

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#27316]
_From @ziomio on September 21, 2018 14:1_

If I hover over the `polygon` object name in the last line of this source code:
```
let polygon = {
  y: "hello",
  z: "goodbye"
};
polygon.y += 5;
```
IntelliSense will display this popup:
![screenshot](https://user-images.githubusercontent.com/2357073/45885562-6f639300-bdbf-11e8-9ae6-d86002f1f868.png)

It displays `[x: string]: any;` **inside** curly braces, but inside curly braces (in my opinion) must be only object properties. If I look quickly over that popup I can assume that object `polygon` has x,y,z properties, when in fact `x` property is absent. Therefore I propose to display that `[x: string]: any;` information at the most top line of that popup window.

_Copied from original issue: Microsoft/vscode#59105_

**Comment by mjbvz** [comment]
@ziomio `[x: string]: any` is actually a typescript [index signature](https://basarat.gitbooks.io/typescript/docs/types/index-signatures.html). Here it indicates that `polygon` is open and other properties may be added to it later later

Moving upstream because I think we can probably display this to js users more clearly, possibly by omitting the index signature in implicit cases like this. Other ideas?

**Comment by ziomio** [comment]
@mjbvz, the problem is - I don't use TypeScript. It's a regular JS file. I know nothing about TypeScript, CoffeeScript, PanamaScript, etc. I write Vanilla JS. And currently VSCode adds additional field "x" inside my object.

**Comment by RyanCavanaugh** [comment]
Seems to have been fixed already
![image](https://user-images.githubusercontent.com/6685088/53991755-1fb02400-40e0-11e9-8caf-669267fa39a1.png)
