### ISSUE TITLE
Spec: Update grammar for rest parameter

### ISSUE THREAD

**Issue by yuit** [Microsoft/TypeScript#2732]
Currently, our spec uses following grammar to describe rest parameter:

 RestParameter:
   ... Identifier TypeAnnotation <sub>opt<sub>

However, the grammar should be 
 RestParameter:
   ... Identifier ```:``` TypeAnnotation <sub>opt<sub>

**Comment by DanielRosenwasser** [comment]
*TypeAnnotation* already includes the `:` in its production:

> *TypeAnnotation:*
&nbsp; &nbsp; `:`&emsp;*Type*

**Comment by yuit** [comment]
@DanielRosenwasser  you are right
