### ISSUE TITLE
JSDoc @type tag not validating on module.exports

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/TypeScript#27327]
tsc: 3.0.3
vscode: 1.27.2

I have a library (we will call it `my-module`). I am including it in my JavaScript app for testing with JavaScript, I am trying to typedoc a `module.exports` which just exports an object literal. Adding JSDoc to it doesn't validate the object like I was expecting.

I have this TS interface:

```ts
export interface AppSettings {
    port: number;
    // other settings
}
```

This works, it throws an error saying that `port` is missing.

```js
/** @type {import('my-module').AppSettings} */
let settings = {}
module.exports = settings
```

So, I tried it on the object, but it doesn't work, `port` is missing but there is no error.

```js
/** @type {import('my-module').AppSettings} */
module.exports = {}
```

I have tried multiple doctypes, and none of them work such as:

This one is similar to how it is described on the [jsdoc website](http://usejsdoc.org/tags-property.html)
```js
/**
 * @namespace 
 * @property {import('my-module').AppSettings} exports 
 */
module.exports = {}
```
```js
module = {
  /** @type {import('my-module').AppSettings} */
  exports: {}
}
```

**Comment by andy-ms** [comment]
Simplified repro:
```js
/** @type {string} */
module.exports = 0;
```

**Comment by TheColorRed** [comment]
@andy-ms Wouldn't it be `@property` since `exports` is a property?

**Comment by andy-ms** [comment]
We should probably support both.

**Comment by jpage-godaddy** [comment]
This is still happening or happening again using modern TypeScript versions; hopefully this is seen.

**Comment by sandersn** [comment]
@jpage-godaddy please file a new issue with a new repro -- the code has changed quite a bit since this bug was fixed so the cause is almost certainly different.
