### ISSUE TITLE
Feature request: Dynamic import() and a issue about return type

### ISSUE THREAD

**Issue by bluelovers** [Microsoft/TypeScript#27322]
## Search Terms

- Dynamic
- import

## Suggestion

hope can have a syntax for Dynamic import()

## Examples

```ts
/**
 * here has a issue
 * 
 * Error: TS4058: Return type of exported function has or is using name 'Bluebird' from external module "xxx/node_modules/@types/bluebird/index" but cannot be named.
 */
export function currentTsWay(id: string)
{
	return require(id) as typeof import("bluebird")
}

// @ts-ignore
export function requestSomethingLookLikeThis<M extends string>(id: M): typeof import(M)
{
	return require(id)
}

// ts know this is bluebird module
currentTsWay('bluebird');

// request ts can know this is bluebird too
requestSomethingLookLikeThis('bluebird');
```

## a issue

```ts
/**
 * here has a issue
 * 
 * Error: TS4058: Return type of exported function has or is using name 'Bluebird' from external module "xxx/node_modules/@types/bluebird/index" but cannot be named.
 */
export function currentTsWay(id: string)
{
	return require(id) as typeof import("bluebird")
}
```

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by RyanCavanaugh** [comment]
This would basically require rearchitecting large parts of the compiler - we assume today that after parsing, all file I/O is done, but this would invalidate that assumption because you could e.g. alias `requestSomethingLookLikeThis`, which means we wouldn't realize it was a module requiring disk resolution until midway through typechecking.

**Comment by bluelovers** [comment]
@RyanCavanaugh how about use `readonly string`

```ts
export function my_import<T extends readonly string>(name: T)
{
	return import(name)
}
```

=>

```ts
export declare function my_import<T extends readonly string>(name: T): Promise<typeof import(T)>;
```
