### ISSUE TITLE
I was hoping if it was possible to infer optional props from object.

### ISSUE THREAD

**Issue by guptaamol** [microsoft/TypeScript#27336]
## Search Terms
optional prop inference.

## Suggestion
Optional Arguments type creation.

## Use Cases

Currently we need to define a partial to infer optional types.
I was hoping if we could create something as mentioned in the example for inferring optional props.

## Examples
const someObj = {a: 'someString', b: undefined as number};
type someObjType = typeof someObj;
someObjType = {a: string, b?: number}

## Checklist

My suggestion meets these guidelines:
* [ ] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by andy-ms** [comment]
Why is it important that we infer a type for `b` that isn't present in the actual value? Why not just write `const someObj = { a: "", b: undefined }` and let the inferred type be `{ a: string, b: undefined }`? That would be assignable to `{ a: string, b?: number }`.

**Comment by guptaamol** [comment]
the inferred type for b for someObj would be any, hence it could take value
of a string or a number or any other object. if we define b as "b:
undefined as number" it will only take number as a value, an assignment of
string to b should throw an error, defining it all in a single object
instead of using partials is really convenient.

And the type for someObj as mentioned above will be {a: string, b: any}, b
is not optional in the inferred type.

**Comment by andy-ms** [comment]
Try adding `"stict": true` to your tsconfig to avoid the inferred type of `b` being `any`.

**Comment by guptaamol** [comment]
Sure I'll try that
