### ISSUE TITLE
Spec should say public, private and protected modifiers are not allowed to be used with rest parameter

### ISSUE THREAD

**Issue by yuit** [Microsoft/TypeScript#2733]
Currently,
"
A parameter is permitted to include a public, private, or protected modifier only if it occurs in the parameter list of a ConstructorImplementation (section 8.3.1) and only if it doesn't specify a BindingPattern.
"
The spec should have additional specify that "...and only if it doesn't specify a BindingPattern and restParameter" as rest parameter is also included in ParameterList.

**Comment by ahejlsberg** [comment]
The grammar already reflects that accessibility modifiers aren't permitted on rest parameters. I don't think we need to add more wording.
