### ISSUE TITLE
JSDoc object generics class properties

### ISSUE THREAD

**Issue by sdn90** [Microsoft/TypeScript#27333]
**TypeScript Version:**  3.0.3

**Search Terms:**
jsdoc
object generic
class properties

**Code**

```ts
class TestClass {
  constructor() {

    // not working
    /** @type {Object<string, string>} */
    this.mismatchedValue = {
      123: 123
    };

    // not working
    this.mismatchedValue = {
      123: "Hello"
    }

    // working
    this.mismatchedValue = "testing";
  }
  test() {
    // not working
    this.mismatchedValue = {
      123: 123
    }
  }
}
```

**Expected behavior:**
<img width="500" alt="screenshot 2018-09-24 23 48 10" src="https://user-images.githubusercontent.com/2491713/45997496-a30b1b00-c054-11e8-8246-3d2abcfbcdc8.png">

Lines commented `not working` should be giving an error

**Playground Link:** 

**Related Issues:**

**Comment by andy-ms** [comment]
`{ 123: "Hello" }` isn't an error -- the key `123` is converted to a string, so it's assignable to `Object<string, string>`.
I correctly see an error in the other locations when testing with `typescript@next`.
