### ISSUE TITLE
typeof switch filters union types but does not narrow them

### ISSUE THREAD

**Issue by jack-williams** [Microsoft/TypeScript#27335]
**TypeScript Version:** 83fe1ea

**Search Terms:** switch typeof narrowing narrows 

**Code**

```ts
// @strictNullChecks: true
function narrowingNarrows(x: {} | undefined) {
    switch (typeof x) {
        case 'string': x; return; // x is {}, should be string
        case 'number': x; return; // x is {}, should be number
    } 
}
```

**Expected behavior:**

Switching on `typeof` should narrow union members in addition to filtering.
- In the first clause, `undefined` should be filtered and `{}` should be narrowed to `string`.
- In the second clause, `undefined` should be filtered and `{}` should be narrowed to `number`.

**Actual behavior:**

Switching on `typeof` only filters unions.
- In the first clause, `undefined` is filtered but `{}` is not narrowed.
- In the second clause, `undefined` is filtered but `{}` is not narrowed.

**Playground Link:**  Link: N/A (Playground not on this version).

**Comment by jack-williams** [comment]
Should this have a fixed label or should it wait on merging a PR?

**Comment by weswigham** [comment]
The PR's in a milestone, so the fixed label is fine. It's good for making sure nobody else picks up the issue accidentally while it's still open.

**Comment by jack-williams** [comment]
Cheers @weswigham. Might be worth adding a fixed label to #27180 as it handled by the same PR.

**Comment by RyanCavanaugh** [comment]
@weswigham assigning to you for tracking purposes

**Comment by jack-williams** [comment]
@RyanCavanaugh @weswigham 

Is there any merit in trying to unify the `if` and `switch` narrowing code under `typeof`, at least to some degree?
