### ISSUE TITLE
Add util to test for "PromiseLike"

### ISSUE THREAD

**Issue by martinheidegger** [Microsoft/TypeScript#27358]
## Search Terms

isPromiseLike, How to test for PromiseLike

## Suggestion

It would be good to have a util in TypeScript that allows to check at runtime, exactly as at compile-time, if a value is `PromiseLike` or not.

## Use Cases

In order to reduce execution time I would like to offer a `Value | PromiseLike<Value>` typing for an interface in my code. I could write this myself but I wouldn't feel sure if the implementation matches TypeScripts definition to a 100% which is why I would like to have it inside TypeScript.

There are various implementations of this in userland but its unclear which is correct, like:

https://github.com/typestack/routing-controllers/blob/4a56d176db77bc081dfcd3d8550e8433b5bc476e/src/util/isPromiseLike.ts#L1-L6

## Examples

```typescript
interface ItemFactory<T> {
  parse(serialised: string): T | PromiseLike<T>
}

function createAllItems<T> (allSerialised: string[], factory: ItemFactory<T>)?: T[] | PromiseLike<T[]> {
  let list: T[]
  let ps: PromiseLike<T>[]
  for (const serialised of allSerialised) {
    let item = factory.parse(serialised)
    if (isPromiseLike(item)) {
      if (list !== undefined) {
        // If former items were regular items, we need to change
        // all former ones to promises
        ps = list.map(item => Promise.resolve(item))
        list = undefined
      } else if (ps === undefined) {
        // If the first item happens to be PromiseLike
        ps = []
      }
      // And then we add this item.
      ps.push(item)
    } else if (ps !== undefined) {
      // We need to return a Promise even if this item is not a promise
      ps.push(Promise.resolve(item))
    } else if (list !== undefined) {
      // Up until now, there have been only normal items
      list.push(item)
    } else {
      // This is the first item 
      list = [item]
    }
  }
  if (ps === undefined) {
    return Promise.all(ps)
  }
  if (list !== undefined) {
    return list
  }
}
```

## Checklist

* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by JakeTunaley** [comment]
TypeScript doesn't add user-callable runtime functions to JavaScript - just transpilation helper functions like `__awaiter`. You'd have better luck proposing a new language feature over at [TC39](https://github.com/tc39/ecma262).

**Comment by martinheidegger** [comment]
Isn't "PromiseLike" a TypeScript concept?

**Comment by ajafff** [comment]
The Spec calls these things `promise` or `thenable`: https://promisesaplus.com/#terminology
`PromiseLike` is just a type-level abstraction for everything compatible with `promise`.
