### ISSUE TITLE
tuple narrowing is lost when wrapped in Promise

### ISSUE THREAD

**Issue by billba** [Microsoft/TypeScript#27363]
**TypeScript Version:**

3.2.0-dev.20180926

**Search Terms**

tuple array narrow

**Code**
```ts
const gallant = <ARGS extends unknown[] | [unknown]> (
    a: () => ARGS,
    b: (...args: ARGS) => boolean,
 ) => b(...a());


gallant(
    () => [2, "dog"],
    (x, y) => y.repeat(x) === "dogdog"
);


const goofus = async <ARGS extends unknown[] | [unknown]> (
    a: () => Promise<ARGS>,
    b: (...args: ARGS) => Promise<boolean>,
 ) => b(... await a());

goofus(
    () => Promise.resolve([2, "dog"]),
    (x, y) => Promise.resolve(y.repeat(x) === "dogdog")
);

```

**Expected behavior:**

The call to `goofus` to behave like the call to `gallant` -- ARGS should narrow to the tuple `[number, string]` and thus `x` is  a `number` and `y` is a `string`

**Actual behavior:**

In the call to `goofus`, `ARGS === (number | string)[]`, and so both `x` and `y` are `number | string`, which results in the following error:

```
[ts]
Property 'repeat' does not exist on type 'string | number'.
  Property 'repeat' does not exist on type 'number'.
```

**Playground Link:** 

[link](https://www.typescriptlang.org/play/#src=const%20gallant%20%3D%20%3CARGS%20extends%20unknown%5B%5D%20%7C%20%5Bunknown%5D%3E%20(%0D%0A%20%20%20%20a%3A%20()%20%3D%3E%20ARGS%2C%0D%0A%20%20%20%20b%3A%20(...args%3A%20ARGS)%20%3D%3E%20boolean%2C%0D%0A%20)%20%3D%3E%20b(...a())%3B%0D%0A%0D%0A%0D%0Agallant(%0D%0A%20%20%20%20()%20%3D%3E%20%5B2%2C%20%22dog%22%5D%2C%0D%0A%20%20%20%20(x%2C%20y)%20%3D%3E%20y.repeat(x)%20%3D%3D%3D%20%22dogdog%22%0D%0A)%3B%0D%0A%0D%0A%0D%0Aconst%20goofus%20%3D%20async%20%3CARGS%20extends%20unknown%5B%5D%20%7C%20%5Bunknown%5D%3E%20(%0D%0A%20%20%20%20a%3A%20()%20%3D%3E%20Promise%3CARGS%3E%2C%0D%0A%20%20%20%20b%3A%20(...args%3A%20ARGS)%20%3D%3E%20Promise%3Cboolean%3E%2C%0D%0A%20)%20%3D%3E%20b(...%20await%20a())%3B%0D%0A%0D%0Agoofus(%0D%0A%20%20%20%20()%20%3D%3E%20Promise.resolve(%5B2%2C%20%22dog%22%5D)%2C%0D%0A%20%20%20%20(x%2C%20y)%20%3D%3E%20Promise.resolve(y.repeat(x)%20%3D%3D%3D%20%22dogdog%22)%0D%0A)%3B)

**Related Issues:**

The `T extends XXX[] | [XXX]` syntax for tuple narrowing is per @ahejlsberg in https://github.com/Microsoft/TypeScript/issues/27179

**Comment by j-oliveras** [comment]
The `Promise.resolve` has no overload to resolve tuple types. You can add this and will work:
```ts
interface PromiseConstructor {
    resolve<T extends unknown[] | [unknown]>(value: T | PromiseLike<T>): Promise<T>;
}
```

Be aware that, probably, any array created inside `Promise.resolve` will be treated as a tuple.

**Comment by billba** [comment]
Declaration merging didn't change the behavior, because that overload has to come first. When I manually inserted it into the declaration for `PromiseConstructor` it did work:
```ts
interface PromiseConstructor {
    ....
    resolve<T>(value: T | PromiseLike<T>): Promise<T>;
    resolve<T extends unknown[] | [unknown]>(value: T | PromiseLike<T>): Promise<T>;
    ...
}
 ```

This demonstrates the problem with having to depend on a construct like `T extends XXX[] | [XXX]`. What I want is for TypeScript to infer a tuple literal as a tuple.

**Comment by RyanCavanaugh** [comment]
Also discussed at #27486

We can't just infer tuples everywhere (it breaks everything).

**Comment by billba** [comment]
What is your recommendation on how to code `goofus` above?
