### ISSUE TITLE
transform ts to java

### ISSUE THREAD

**Issue by whu-iss-jack** [Microsoft/TypeScript#27362]
## Use Cases

Client and Server communication often need a common message protocal, like `protobuf`, it can generate message struct types for different languages.  Now I write those message types in typescript first, and like to transform them to another language like Java.  I need typescript to provide language service api like type information, thus I can write code to transform and generate Java code automatically 

## Examples

message.ts
```ts
interface IUserInfo {
    name: string;
    age: number;
    level: 'small' | 'big';
}
```
message.java
```java

enum Level {
    small,
    big
}

class IUserInfo {
    public String name;
    public double age;
    public Level level;
}
```

## Checklist

My suggestion meets these guidelines:
* [ ] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by DanielRosenwasser** [comment]
There are other tools to handle this like protocol buffers, Swagger (for REST), and more, but this isn't something the TypeScript team project aims to serve.
