### ISSUE TITLE
Generated markdown issue with spec at section 3.8.2.2

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#2737]
> When a parameter type annotation specifies a string literal ty�����pe, the containing signature is a specialized signature (section 3.8.2.4).

See [3.8.2.2](https://github.com/Microsoft/TypeScript/blob/7ee698c450e8317651ecb102534b0601da5ecb9f/doc/spec.md#3822-parameter-list)

**Comment by ahejlsberg** [comment]
Fixed in #4033.
