### ISSUE TITLE
Generic function argument not assignable when called in a generic function; okay if not called generically

### ISSUE THREAD

**Issue by AnyhowStep** [microsoft/TypeScript#27399]
**TypeScript Version:**  3.0.1 (And the version TS playground is on)

**Search Terms:** generic parameter not assignable 

**Code**

Not sure if this is a minimal example,

```ts
declare function takesPartialObj<T>(
    arg: {
        [k in Extract<keyof T, string>]?: T[k]
    }
): void;

declare function pick<T, K extends string>(
    obj: T,
    keys : K[]
): {
    [k in Extract<Extract<keyof T, K>, string>]: (
        T[k]
    )
}

interface Foo {
    x: number,
    y: string,
    z: boolean,
}
declare const foo: Foo;
//{ x: number; y: string; }
const picked = pick(foo, ["x", "y"]);
//OK
takesPartialObj<Foo>(picked);
//OK
takesPartialObj<Foo>(pick(foo, ["x", "y"]));

function callTakesPartialObj<T, K extends string>(
    obj: T,
    keys: K[]
) {
    const picked = pick(obj, keys);
    //Error
    takesPartialObj<T>(picked);
    //Error
    takesPartialObj<T>(pick(obj, keys));
}
```

**Expected behavior:**

Lines commented with `//Error` should work.

To me, intuitively,

`takesPartialObj<>()` asks for something like,

```ts
{
    field0? : type0,
    field1? : type1,
    field2? : type2,
    field3? : type3,
    //etc
}
```

Where every `fieldX` is optional.

And `pick<>()` should always return an object that fits the above expected type.

But, for some reason, it's not assignable.

**Actual behavior:**

Lines commented with `//Error` do not work.

**Playground Link:** [Here](http://www.typescriptlang.org/play/#src=declare%20function%20takesPartialObj%3CT%3E(%0A%20%20%20%20arg%3A%20%7B%0A%20%20%20%20%20%20%20%20%5Bk%20in%20Extract%3Ckeyof%20T%2C%20string%3E%5D%3F%3A%20T%5Bk%5D%0A%20%20%20%20%7D%0A)%3A%20void%3B%0A%0Adeclare%20function%20pick%3CT%2C%20K%20extends%20string%3E(%0A%20%20%20%20obj%3A%20T%2C%0A%20%20%20%20keys%20%3A%20K%5B%5D%0A)%3A%20%7B%0A%20%20%20%20%5Bk%20in%20Extract%3CExtract%3Ckeyof%20T%2C%20K%3E%2C%20string%3E%5D%3A%20(%0A%20%20%20%20%20%20%20%20T%5Bk%5D%0A%20%20%20%20)%0A%7D%0A%0Ainterface%20Foo%20%7B%0A%20%20%20%20x%3A%20number%2C%0A%20%20%20%20y%3A%20string%2C%0A%20%20%20%20z%3A%20boolean%2C%0A%7D%0Adeclare%20const%20foo%3A%20Foo%3B%0A%2F%2F%7B%20x%3A%20number%3B%20y%3A%20string%3B%20%7D%0Aconst%20picked%20%3D%20pick(foo%2C%20%5B%22x%22%2C%20%22y%22%5D)%3B%0A%2F%2FOK%0AtakesPartialObj%3CFoo%3E(picked)%3B%0A%2F%2FOK%0AtakesPartialObj%3CFoo%3E(pick(foo%2C%20%5B%22x%22%2C%20%22y%22%5D))%3B%0A%0Afunction%20callTakesPartialObj%3CT%2C%20K%20extends%20string%3E(%0A%20%20%20%20obj%3A%20T%2C%0A%20%20%20%20keys%3A%20K%5B%5D%0A)%20%7B%0A%20%20%20%20const%20picked%20%3D%20pick(obj%2C%20keys)%3B%0A%20%20%20%20%2F%2FError%0A%20%20%20%20takesPartialObj%3CT%3E(picked)%3B%0A%20%20%20%20%2F%2FError%0A%20%20%20%20takesPartialObj%3CT%3E(pick(obj%2C%20keys))%3B%0A%7D)

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
TypeScript isn't able to reason about the application of multiple extract/keyof operations in sequence to figure out whether the eventual type is "the same" or not.
