### ISSUE TITLE
AllowJS Not Working?

### ISSUE THREAD

**Issue by sdrioux** [Microsoft/TypeScript#27398]
**TypeScript Version:**  3.1.1

**Search Terms:**
allowJS Implicitly has an 'any' type

**TSConfig**
```
{
    "compilerOptions": {
      "allowJs": true,
      "module": "commonjs",
      "noEmitOnError": true,
      "noFallthroughCasesInSwitch": true,
      "noImplicitReturns": true,
      "noUnusedLocals": true,
      "experimentalDecorators": true,
      "emitDecoratorMetadata": true,
      "moduleResolution": "node",
      "resolveJsonModule": true,
      "strict": true,
      "target": "es2017",
      "lib": [
        "dom",
        "es2017",
        "es2018",
        "esnext"
      ],
  }
```

I am importing this JS file: 
```
module.exports = {
  development: {
    username: "postgres",
    password: "",
    database: "development_database",
    host: "127.0.0.1",
    dialect: "postgres"
  },
  test: {
    username: "postgres",
    password: "",
    database: "test_database",
    host: "127.0.0.1",
    dialect: "postgres",
    logging: false
  }
}
```

 like this: 
```
import { Sequelize } from 'sequelize-typescript'
import * as sequelizeConfig from '../db/config'

const config = sequelizeConfig[process.env.NODE_ENV || 'development']
...
...
```

**Expected behavior:**
On 3.0.3 this compiles fine with no issues.

**Actual behavior:**
On 3.1.1 I get this error: 

```
Element implicitly has an 'any' type because type '{ development: { username: string; password: string; database: string; host: string; dialect: string; }; test: { username: string; password: string; database: string; host: string; dialect: string; logging: boolean; }; }' has no index signature.

7 const config = sequelizeConfig[process.env.NODE_ENV || 'development']
```

I'm new to Typescript, but shouldn't `allowJS: true` prevent this scenario?

**Comment by andy-ms** [comment]
When you set `allowJs` it means we check the JS file. That means we can infer a type for its output, which as you can see from the error message is `{ development: ..., test: ... }`. When you index into that with `[process.env.NODE_ENV || 'development']`, there's an error because `process.env.NODE_ENV` could be anything, so we don't know that it's a valid key.
You could fix this with:
```js
const env = process.env.NODE_ENV || 'development';
if (env !== "development" && env !== "test") throw new Error();
const config = sequelizeConfig[env]
```

(The reason this changed since 3.0 is because we no longer give an index signature to JS object literals in certain positions.)

**Comment by weswigham** [comment]
Yeah, as @andy-ms said, we made it so `noImplicitAny` (a part of `strict`) opt you completely out of the implicit `{[index: string]: any}` index signatures objects originating in JS used to have (since it caused a ton of type safety issues, and the flag is supposed to help remove those).

**Comment by andy-ms** [comment]
`===` and `!==` are treated specially by TypeScript while `includes` is not.
