### ISSUE TITLE
document.createNodeIterator signature breaks compatibility with IE

### ISSUE THREAD

**Issue by alenaksu** [Microsoft/TypeScript#27393]
**TypeScript Version:**  3.1.1

**Search Terms:** createNodeIterator IE Internet Explorer

**Code**

```ts
document.createNodeIterator(
    rootElement, 
    NodeFilter.SHOW_COMMENT, 
    NodeFilter.FILTER_ACCEPT,
    false
);
```

**Expected behavior:** 
`document.createNodeIterator` signature should accept 1-4 arguments to support __Internet Explorer__ browsers.

**Actual behavior:** 
The following exception is thrown during compilation:
`TS2554: Expected 1-3 arguments, but got 4.`

**Comment by weswigham** [comment]
You can always add another IE-specific overload to the `Document` type in your own project:

```ts
interface Document {
    createNodeIterator(root: Node, whatToShow?: number, filter?: NodeFilter, entityReferenceExpansion?: boolean): NodeIterator
}
```

**Comment by alenaksu** [comment]
I see, thank you @j-oliveras @weswigham for your explanations.
