### ISSUE TITLE
Add Enumerator and VBArray declarations+jsDoc to lib.d.ts

### ISSUE THREAD

**Issue by zspitz** [Microsoft/TypeScript#2740]
[Enumerator](https://msdn.microsoft.com/en-us/library/ie/6ch9zb09(v=vs.94).aspx) allows iterating over ActiveX collections, enabling functionality for these collections like VB.NET/VBScript `For Each .. In ..`, C#'s [`foreach`](https://msdn.microsoft.com/en-us/library/ttw7t8t6.aspx) and the Javascript experimental [`for...of`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of). Most of these collections do not have a `length` property or an indexer, and therefore cannot be treated as simple arrays.

[VBArray](https://msdn.microsoft.com/en-us/library/ie/y39d47w8(v=vs.94).aspx) enables reading from a VB array (or safe array) from Javascript.

**Comment by mhegazy** [comment]
thanks @zspitz
