### ISSUE TITLE
TS wrongly assume an expression will always be false

### ISSUE THREAD

**Issue by floribon** [Microsoft/TypeScript#27401]
**TypeScript Version:**  3.2.0-dev.20180927

**Search Terms:** "condition will always return", "no overlap"

**Code**

```ts
interface O {
  v?: 'A' | 'B';
}

const o: O = {};
o.v = 'A';
toB(o);
console.log(o.v === 'B');

function toB(o: O): void {
  o.v = 'B';
}
```

**Expected behavior:**
No TS error

**Actual behavior:**
```
[ts] This condition will always return 'false' since the types '"A"' and '"B"' have no overlap.
```
(console prints `true`)

**Playground Link:** 
http://www.typescriptlang.org/play/#src=interface%20O%20%7B%0D%0A%20%20v%3F%3A%20'A'%20%7C%20'B'%3B%0D%0A%7D%0D%0A%0D%0Aconst%20o%3A%20O%20%3D%20%7B%7D%3B%0D%0Ao.v%20%3D%20'A'%3B%0D%0AtoB(o)%3B%0D%0Aconsole.log(o.v%20%3D%3D%3D%20'B')%3B%0D%0A%0D%0Afunction%20toB(o%3A%20O)%3A%20void%20%7B%0D%0A%20%20o.v%20%3D%20'B'%3B%0D%0A%7D%0D%0A

**Related Issues:** 
A variation without optional property
```ts
interface O {
  v: 'A' | 'B';
}

const o: O = {v: 'A'};
o.v = 'A'; // commenting this line will remove the error
toB(o);
console.log(o.v === 'B');

function toB(o: O): void {
  o.v = 'B';
}
```

**Comment by RyanCavanaugh** [comment]
See #9998

**Comment by floribon** [comment]
I see, sorry for the duplicate. Is there any recommended workaround as of today or should I add a `@ts-ignore`?

**Comment by RyanCavanaugh** [comment]
That's one option. You also could write `o.v = 'A' as 'A' | 'B'` so TS doesn't realize which you set it to, or write `(o.v === 'B' as string)`

**Comment by floribon** [comment]
I see, thanks
