### ISSUE TITLE
Properties with string keys and already declared type are getting their type narrowed when using square bracket assignment.

### ISSUE THREAD

**Issue by lazytype** [Microsoft/TypeScript#27412]
**TypeScript Version:**  3.1.1

**Search Terms:** string property, property assign

**Code**

```ts
let foo: { bar: boolean } = { bar: true };

foo.bar = true; // OK
foo.bar = false; // OK

foo['bar'] = true; //  error TS2322: Type 'true' is not assignable to type 'false'.
foo['bar'] = false; // error TS2322: Type 'false' is not assignable to type 'true'.
```

**Expected behavior:**
No type errors
**Actual behavior:**
Type errors when using square backet assignment

**Playground Link: https://www.typescriptlang.org/play/#src=let%20foo%3A%20%7B%20bar%3A%20boolean%20%7D%20%3D%20%7B%20bar%3A%20true%20%7D%3B%0A%0Afoo.bar%20%3D%20true%3B%0Afoo.bar%20%3D%20false%3B%0A%0Afoo%5B'bar'%5D%20%3D%20true%3B%0Afoo%5B'bar'%5D%20%3D%20false%3B**

**Comment by mikea** [comment]
Another example of the code it breaks:

```
interface IColor {
  r: number;
  g: number;
  b: number;
}

interface ITheme {
  primaryColor?: IColor;  
  "primary-color"?: IColor;
}

const red: IColor = { r: 1, g: 0, b: 0 };

function fillInRedColor(theme: ITheme) {
  if (!theme.primaryColor) {
    theme.primaryColor = red;  
  }
  if (!theme["primary-color"]) {
    theme["primary-color"] = red;  
  }
}
```

http://www.typescriptlang.org/play/index.html#src=interface%20IColor%20%7B%0D%0A%20%20r%3A%20number%3B%0D%0A%20%20g%3A%20number%3B%0D%0A%20%20b%3A%20number%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20ITheme%20%7B%0D%0A%20%20primaryColor%3F%3A%20IColor%3B%20%20%0D%0A%20%20%22primary-color%22%3F%3A%20IColor%3B%0D%0A%7D%0D%0A%0D%0Aconst%20red%3A%20IColor%20%3D%20%7B%20r%3A%201%2C%20g%3A%200%2C%20b%3A%200%20%7D%3B%0D%0A%0D%0Afunction%20fillInRedColor(theme%3A%20ITheme)%20%7B%0D%0A%20%20if%20(!theme.primaryColor)%20%7B%0D%0A%20%20%20%20theme.primaryColor%20%3D%20red%3B%20%20%0D%0A%20%20%7D%0D%0A%20%20if%20(!theme%5B%22primary-color%22%5D)%20%7B%0D%0A%20%20%20%20theme%5B%22primary-color%22%5D%20%3D%20red%3B%20%20%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0A
