### ISSUE TITLE
Add possibility to put every class in separate file

### ISSUE THREAD

**Issue by PashaTurok** [Microsoft/TypeScript#27426]
## Suggestion

I suggest to add possibility to put every class in separate file although they belong to one module and TypeScript must generate one module with these classes.

## Use Cases

Because it is a standard and convenient way to develop classes.
## Examples

Java, C#?
## Checklist

My suggestion meets these guidelines:
* [X] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by RyanCavanaugh** [comment]
You can already accomplish this today by re-exporting the classes.

**Comment by PashaTurok** [comment]
@RyanCavanaugh Can you give a link to `re-exporting the classes` feature? I found examples only here https://stackoverflow.com/questions/29168813/typescript-how-to-export-two-classes-in-separate-files-in-one-module but they all suppose extending in final module classes that are in separate files.

**Comment by PashaTurok** [comment]
The question about this was asked on StackOverflow https://stackoverflow.com/questions/52570738/how-to-merge-two-classes-in-separate-files-into-one-es6-module-using-typescript
