### ISSUE TITLE
interface Position (lib.d.ts) has the wrong type for timespamp parameter

### ISSUE THREAD

**Issue by viniciusx** [Microsoft/TypeScript#2742]
I was testing out the [Cordova Geolocation plugin](https://github.com/apache/cordova-plugin-geolocation) and in the method ```getCurrentPosition``` one of the return parameters is a timestamp of when the geolocation was requested. In the interface Position we have this:
```typescript
interface Position {
    timestamp: Date;
    coords: Coordinates;
}
```
but what actually returns from the method is a ```number ``` representation of the Date (as in 
```Date.now()``` ) : 
```Geoposition {timestamp: 1428934195575, coords: Coordinates}``` (taken from Chrome's console)
Since the definition for the Position interface is in lib.d.ts i thought i'd share it here rathen than the plugin's page.
Thanks!

**Comment by DanielRosenwasser** [comment]
Cordova may or may not have an API that differs from the [W3 standard](http://www.w3.org/TR/geolocation-API/#position_interface), but regardless we should be be following the latter in lib.d.ts.

I'd file a bug with Cordova as well and mention that you think there is an error with [their documentation on `Position` objects](http://docs.phonegap.com/en/edge/cordova_geolocation_geolocation.md.html#Position), but you may want to confirm with an actual Cordova app.

**Comment by viniciusx** [comment]
Yeah, I'm currently using it an app. Had to circumvent the issue with some castings because Visual Studio (rightly) wouldn't let me compile the project.
```javascript
 alert('Latitude: '          + position.coords.latitude          + '\n' +
          'Longitude: '         + position.coords.longitude         + '\n' +
          'Altitude: '          + position.coords.altitude          + '\n' +
          'Accuracy: '          + position.coords.accuracy          + '\n' +
          'Altitude Accuracy: ' + position.coords.altitudeAccuracy  + '\n' +
          'Heading: '           + position.coords.heading           + '\n' +
          'Speed: '             + position.coords.speed             + '\n' +
          'Timestamp: '         + position.timestamp                + '\n');
};
```
Their documentation only shows the call's results, no actual values/types are involved. But i will file a bug there as well, with some code from my app.
If you'd like me to provide a sample app showing the problem, I'd be more than glad to do so.

**Comment by DanielRosenwasser** [comment]
Well I linked to their interface above in my comment.

I also realize that this is part of the `dom.generated.d.ts` which means that we get it from the IE team.

**Comment by mhegazy** [comment]
This looks fixed already.
