### ISSUE TITLE
Pretty time format does not use local time format

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/TypeScript#27428]
**TypeScript Version:**  3.0.3

Here's Gulp's log output in a European country:

```
[15:24:31] Requiring external module ts-node/register
[15:24:33] Using gulpfile ~/src/github.com/sourcegraph/sourcegraph/gulpfile.ts
[15:24:33] Starting 'watchSchema'...
[15:24:33] Starting 'watchGraphQLTypes'...
[15:24:33] Starting 'sass'...
```

Here's `tsc`'s output (with `--pretty`):

```
[3:24:45 PM] File change detected. Starting incremental compilation...

[3:24:45 PM] Found 0 errors. Watching for file changes.
```

This is a minor issue, but the majority of the world uses the 24h system :)

![image](https://user-images.githubusercontent.com/10532611/46211326-8e1fd780-c333-11e8-922f-434ba12c99f5.png)

**Comment by DanielRosenwasser** [comment]
Good point, thanks for bringing it up!

**Comment by AjayPoshak** [comment]
Hey, I would like to work on it.

**Comment by felixfbecker** [comment]
It seems like TypeScript is actually doing the right thing here (and Gulp is not?). So I tried to get 24h working by installing [`full-icu`](https://www.npmjs.com/package/full-icu) and running with `NODE_ICU_DATA`. This loads the ICU correctly because I can manually format a month e.g. in German. But despite having my OS clock in 24h and my OS region set to a European country, Node always uses the American locale for `date.toLocaleString()` (12h). Chrome uses 24h correctly. Anyone know why?

**Comment by felixfbecker** [comment]
Okay, finally figured it out. Node will look at the `LANG` env var, but not consider other the Unix locale env vars like `LC_TIME`. Meaning I can't have `LANG` be English while everything else be e.g. German (such as `LC_TIME` being 24h). I filed this at https://github.com/nodejs/node/issues/23301.

If `LANG` is set to the locale, and Node was compiled with full ICU or invoked with `NODE_ICU_DATA`/`--node-icu-data` pointing to the dat file from `full-icu` (I have this in my profile now) you get 24h time output by tsc.

I am gonna close this because I believe TypeScript is already behaving 100% correctly here, using the local time format that Node uses. I believe it should not do custom localisation logic.

**Comment by felixfbecker** [comment]
I also filed an issue on Gulp btw for consistent timestamps for Americans but it was closed 🤷‍♂️ https://github.com/js-cli/fancy-log/issues/17
