### ISSUE TITLE
Object is possibly 'null' due to slight difference in code with strictNullChecks

### ISSUE THREAD

**Issue by castaneai** [microsoft/TypeScript#27431]
**Typescript Version**: 3.1.1

I found a strange behavior about strictNullChecks. Why?

### It works

```ts
let a: string | null = null;
(() => a = 'str')();
console.log(a.length);
```

http://www.typescriptlang.org/play/#src=let%20a%3A%20string%20%7C%20null%20%3D%20null%3B%0D%0A(()%20%3D%3E%20a%20%3D%20'str')()%3B%0D%0Aconsole.log(a.length)%3B

### Not working

```ts
let a: string | null = null;
const f = (() => a = 'str');
f();
console.log(a.length);
```

http://www.typescriptlang.org/play/#src=let%20a%3A%20string%20%7C%20null%20%3D%20null%3B%0D%0Aconst%20f%20%3D%20(()%20%3D%3E%20a%20%3D%20'str')%3B%0D%0Af()%3B%0D%0Aconsole.log(a.length)%3B

```
$ tsc --strictNullChecks ng.ts
ng.ts:4:13 - error TS2531: Object is possibly 'null'.

4 console.log(a.length);
              ~
```

**Comment by RyanCavanaugh** [comment]
Function references aren't expanded for control flow analysis purposes, but IIFEs are

**Comment by sirdiego** [comment]
> Function references aren't expanded for control flow analysis purposes, but IIFEs are

I've got a slightly more "complex" setup and I don't get why there is an error in line 12 but not in 11. Is this the reason?

Code ([TS Playground](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgCoQM5mQbwFDKHKRYBcam2APsiAK4A2DBRwAJuQMphSgDmeAL548CAPYgsxSgElJYOCCTl0UgLy5ByOBgpZREqQFsAngEEoUOCfIWrJgDyqwAPmQaA2gF0RwGMgAKFkJ6JmQAQjUNEjA5LEUkADoY5AAyVORg6Sw4hSUIZMpE9jTUrNM7a0SYUDY5NggADwCAB3c3FuK2dyjs2PkEgpiugEo8Edws8UkxBgKGMT4AgHJnZbHhIA)):
`interface Test {
    test: Test | null
    id: String
}

const testInstance: Test = {} as Test
const myArray: Array<Test> = []

if (
    null !== testInstance.test && 
    testInstance.test.id &&
    myArray.findIndex(p => p.id === testInstance.test.id)
) {
    console.log('Test')
}
`

**Comment by RyanCavanaugh** [comment]
See #11498
