### ISSUE TITLE
Show default values in jsdoc quick-info.

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#27442]
_From @Wolfonye on September 28, 2018 11:9_

I hope I didn't overlook any issue that poses the same request in a different wording; if yes I am sorry.

The request: 
I repeatedly encounter situations where I would be glad to see the default values
for optional parameters (if specified) in the ctrl+shift+space quick-info. 

Is there anything speaking against such a feature?

_Copied from original issue: Microsoft/vscode#59609_

**Comment by mjbvz** [comment]
Example jsdoc with default param:

```js
/**
 * @param {string} [somebody=John Doe] - Somebody's name.
 */
function sayHello(somebody) {
    if (!somebody) {
        somebody = 'John Doe';
    }
    alert('Hello ' + somebody);
}
```

**Comment by RyanCavanaugh** [comment]
Duplicate #16665
