### ISSUE TITLE
Simple object literal does not work as expected

### ISSUE THREAD

**Issue by PavelPZ** [Microsoft/TypeScript#27448]
**typescript@3.2.0-dev.20180929**

I prepared following smallest test case (demonstrating the problem I found in my real code)

## WRONG:
```
interface Low {
}

interface TransitionLow {
    native: { 
        margin: string 
    }
}

const testWRONG: TransitionLow & Low = {
    native: {
        margin: '',
        color: '',  // ==> NO ERROR HERE, "Object literal may only specify known properties" expected
    }
}

```

## CORRECT:

```
const testOK: TransitionLow & Low = {
    native: {
        color: '',  // CORRECT ERROR: Object literal may only specify known properties,...
    }
}

const testOK2: TransitionLow = {
    native: {
        margin: '',
        color: '',  // CORRECT ERROR: Object literal may only specify known properties,...
    }
}
```

**Comment by j-oliveras** [comment]
Another correctly error detect case (testOK3):
```ts
interface Low {
}

interface TransitionLow {
    native: { 
        margin: string 
    }
}

const testWRONG: TransitionLow & Low = {
    native: {
        margin: '',
        color: '',  // ==> NO ERROR HERE, "Object literal may only specify known properties" expected
    }
}

const testOK: TransitionLow & Low = {
    native: {
        color: '',  // CORRECT ERROR: Object literal may only specify known properties,...
    }
}

const testOK2: TransitionLow = {
    native: {
        margin: '',
        color: '',  // CORRECT ERROR: Object literal may only specify known properties,...
    }
}

const testOK3: TransitionLow & Low = {
    native: {
        margin: '',
        color: '',  // ==> NOW ERROR HERE
    },
    aaaaa: '', // Valid because Low is an empty interface
}
```
[Playground](https://www.typescriptlang.org/play/#src=interface%20Low%20%7B%0A%7D%0A%0Ainterface%20TransitionLow%20%7B%0A%20%20%20%20native%3A%20%7B%20%0A%20%20%20%20%20%20%20%20margin%3A%20string%20%0A%20%20%20%20%7D%0A%7D%0A%0Aconst%20testWRONG%3A%20TransitionLow%20%26%20Low%20%3D%20%7B%0A%20%20%20%20native%3A%20%7B%0A%20%20%20%20%20%20%20%20margin%3A%20''%2C%0A%20%20%20%20%20%20%20%20color%3A%20''%2C%20%20%2F%2F%20%3D%3D%3E%20NO%20ERROR%20HERE%2C%20%22Object%20literal%20may%20only%20specify%20known%20properties%22%20expected%0A%20%20%20%20%7D%0A%7D%0A%0Aconst%20testOK%3A%20TransitionLow%20%26%20Low%20%3D%20%7B%0A%20%20%20%20native%3A%20%7B%0A%20%20%20%20%20%20%20%20color%3A%20''%2C%20%20%2F%2F%20CORRECT%20ERROR%3A%20Object%20literal%20may%20only%20specify%20known%20properties%2C...%0A%20%20%20%20%7D%0A%7D%0A%0Aconst%20testOK2%3A%20TransitionLow%20%3D%20%7B%0A%20%20%20%20native%3A%20%7B%0A%20%20%20%20%20%20%20%20margin%3A%20''%2C%0A%20%20%20%20%20%20%20%20color%3A%20''%2C%20%20%2F%2F%20CORRECT%20ERROR%3A%20Object%20literal%20may%20only%20specify%20known%20properties%2C...%0A%20%20%20%20%7D%0A%7D%0A%0Aconst%20testOK3%3A%20TransitionLow%20%26%20Low%20%3D%20%7B%0A%20%20%20%20native%3A%20%7B%0A%20%20%20%20%20%20%20%20margin%3A%20''%2C%0A%20%20%20%20%20%20%20%20color%3A%20''%2C%20%20%2F%2F%20%3D%3D%3E%20NOW%20ERROR%20HERE%0A%20%20%20%20%7D%2C%0A%20%20%20%20aaaaa%3A%20''%2C%20%2F%2F%20Valid%20because%20Low%20is%20an%20empty%20interface%0A%7D%0A).

Note that, in all cases, the tooltip on `native` shows that is a reference to `TransitionLow` `native` property.

**Comment by DanielRosenwasser** [comment]
Duplicate of #18075

**Comment by PavelPZ** [comment]
@DanielRosenwasser, thanks a lot for duplicate notice.

In https://github.com/Microsoft/TypeScript/issues/18075 is this milestone info: 
**mhegazy modified the milestones: TypeScript 3.0, Future on 3 Jul**

Could you be more specific? "3.0" milestone is out and "Future" is not too concrete. This feature is substantial for my project.

Thanks a lot for info.
