### ISSUE TITLE
ChildNode shouldn't be separated from Node

### ISSUE THREAD

**Issue by nin-jin** [Microsoft/TypeScript#27453]
**TypeScript Version:**  3.1.1

**Search Terms:** ChildNode

**Code**

```ts
let x = document.body.childNodes[1]
x = document.body.firstChild.nextSibling
```

**Expected behavior:**

No error. Type of node shouldn't depends on getting way.

**Actual behavior:**
Error:
```
Type 'Node' is not assignable to type 'ChildNode'.
  Property 'after' is missing in type 'Node'.
```
[**Playground Link**](http://www.typescriptlang.org/play/#src=let%20x%20%3D%20document.body.childNodes%5B1%5D%0Ax%20%3D%20document.body.firstChild.nextSibling%0A)

**Comment by RyanCavanaugh** [comment]
Without a more concrete proposal it seems like you're just proposing allowing any assignment to `x`, which is not the intended behavior.

**Comment by nin-jin** [comment]
More concrete proposal: rollback ChildNode invention.
