### ISSUE TITLE
Return type checking bug with finally clause

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#27454]
**TypeScript Version:**  3.1.1

**Search Terms:**

**Code**

```ts
((): 1 => {
    try {
        return 0;
    }
    finally {
        return 1;
    }
})(); // 1
```

**Expected behavior:**

pass

**Actual behavior:**

return type error

**Playground Link:** https://www.typescriptlang.org/play/index.html#src=(()%3A%201%20%3D%3E%20%7B%0D%0A%20%20%20%20try%20%7B%0D%0A%20%20%20%20%20%20%20%20return%200%3B%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20finally%20%7B%0D%0A%20%20%20%20%20%20%20%20return%201%3B%0D%0A%20%20%20%20%7D%0D%0A%7D)()%3B

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
Thankfully no one ever writes code like this 😜

**Comment by falsandtru** [comment]
You lack imagination.

https://github.com/search?l=JavaScript&q=finally+return&type=Code
