### ISSUE TITLE
T[K] is not assignable to NonNullable<T>[K] even when T is nonnull (regression)

### ISSUE THREAD

**Issue by falsandtru** [microsoft/TypeScript#27456]
**TypeScript Version:**  3.2.0-dev.20180929

**Search Terms:**

**Code**

Revert the change of source code to see the error: https://github.com/falsandtru/clientchannel/commit/14cc53a42132d8e2bae81b7ee3764935b547783e

**Expected behavior:**

pass

**Actual behavior:**

```
TypeScript error: src/layer/domain/indexeddb/service/channel.ts(48,15): Error TS2322: Type 'V[Exclude<keyof V, "__meta" | "__id" | "__key" | "__date" | "__event">] | undefined' is not assignable to type 'NonNullable<Partial<V>>[Exclude<keyof V, "__meta" | "__id" | "__key" | "__date" | "__event">]'.
  Type 'undefined' is not assignable to type 'NonNullable<Partial<V>>[Exclude<keyof V, "__meta" | "__id" | "__key" | "__date" | "__event">]'.
```

**Playground Link:** 

**Related Issues:**

**Comment by ahejlsberg** [comment]
I'm not sure there is a regression here. The following is an error with 3.0 as well:

```ts
// Compile with --strictNullChecks
function foo<T, K extends keyof T>(x: T[K], y: NonNullable<T>[K]) {
  x = y;
  y = x;  // Error
}
```

I think the error is reasonable. After all, `NonNullable<T>` is a subtype of `T`.

**Comment by falsandtru** [comment]
@ahejlsberg

**Comment by falsandtru** [comment]
@ahejlsberg Can you take a look at the requested info?

**Comment by falsandtru** [comment]
@ahejlsberg
