### ISSUE TITLE
`@internal` on constructor does not work

### ISSUE THREAD

**Issue by mattmccutchen** [Microsoft/TypeScript#27455]
Inspired by https://stackoverflow.com/q/52570628 .

**TypeScript Version:**  master (e1a4c2779f93c8389d1589e543920a61771e97ec)

**Search Terms:** internal constructor stripInternal

**Code**: Compile with `--declaration --stripInternal`.
```ts
class Foo {
  /** @internal */
  constructor() {}
}
```

**Expected behavior:** Compile error that this isn't supported, or the generated declaration file has a private constructor.

**Actual behavior:** No compile errors and the generated declaration file has no explicit constructor, which leaves an implicit public constructor, which is clearly contrary to the user's intent.

**Playground Link:** N/A, declaration file generation

**Related Issues:** none found

**Comment by RyanCavanaugh** [comment]
A private constructor would be wrong because we'd then generate an incorrect file when there's a derived class:
```ts
declare class A {
    private constructor();
}

// Error
declare class B extends A {

}
```

`internal` is really use-at-your-own-risk and we should undocument it

**Comment by andrewnester** [comment]
Hello! I created PR to fix this in documentation: https://github.com/Microsoft/TypeScript-Handbook/pull/856

**Comment by vhakulinen** [comment]
Is there no chance for you to support this?

**Comment by southpolesteve** [comment]
@RyanCavanaugh Are there any plans to remove `stripInternal` or document it differently? Wondering if we can rely on it in the future.
