### ISSUE TITLE
StringSplit(str extends string, seperator extends string)

### ISSUE THREAD

**Issue by wesleyolis** [Microsoft/TypeScript#27459]
## Search Terms
String Split,
Validation of concatenated strings.

## Suggestion

I would like to suggest that a new simple StringSplit type method be added to typescirpt, which would allow us to write validators for based on string input. There are many different cases that legacy systems like mongoose, make use of space, common, dot separated strings, which are then split and refer to props/fields on a class/interface. I would like to be able to write backwards compatibles type validation,
however, certain styles of legacy, javascript don't tend to lend themself well to what typescript has to offer.

## Use Cases
```.ts
interface RecordA {
 fieldA : string,
 fieldB : number,
 fieldC : boolean
}

// Guaranty that strFields contains those fields at compile time.
function projectFields(obj:Record<string,any>, strfields : string) : Array<RecordA[keyof RecordA]>
{
 const fields = strfields.split(',');
 return fields.map(f => obj[f]);
}
```

The alternative to this is an array capture mechanism, with a separator
```.ts
function<T extends Array<string,','>>(args:T) :RecordA[T[keyof ArrayKeys<T>]]
{
}
```

## How to write the validator, this is so powerfully great pattern. (;-/)
```.ts
type BuildValidatorItems<T, Fields extends string> = {
[F in Fields] : T extends keyof T ? string : never
}[Fields]
// The results is something that allows the base constraint of string or disallows any input.
// At times in stead of never, I would return string literal 'Error field is not member of object'
// It maybe a suggestion that type Error be added, so that typescript can differentiate between
// a string literal that is error, and probability string literal matches error message.

type BuildValidator<T, StrFields extends string> = BuildValidatorItems<T,StringSplit(StrFields, ',')>

function projectFields<Obj extends Record<string,any>,Fields extends BuildValidator<RecordA, Fields>(obj: Obj, strfields : Fields) : Array<RecordA[keyof RecordA]>
{
 const fields = strfields.split(',');
 return fields.map(f => obj[f]);
}

```

### Examples of one of our mongoose validators for Populate recursive pattern
Basically our schema is mutated all the time with builder pattern.
I am now looking at a new mutation pattern, that hopefully simpler, than
all the extends checking that is required. But for now first pass of few our repositories seems
to be working well. https://mongoosejs.com/docs/populate.html
I do see that this potential un-intended pattern by the compiler, however, it well need one and one that definitely should be improved on. such that initial input form could be given week seed. or Record<string,any>
```.ts


export type ExtractType<O extends any, K extends string> = O[K];
export interface PopulateOptionsBase<Path, Select> {
    path: Path;
    select?: Select;
    options?: any;
}
export type ObjectGetValue<O extends Record<string, any>, K extends string> = O[K];

export type ExtractPopulateOption<
SchemaPartial extends Record<string, any>,
T extends PopulateOptionsBase<any, any>,
Path extends string = T['path'],
Select extends string | undefined = T['select']> = {
    path: keyof SchemaPartial;
    select?: keyof ObjectGetValue<TransformPartial<SchemaPartial, Path>, Path> | ((i: string) => keyof ObjectGetValue<TransformPartial<SchemaPartial, Path>, Path>);
    options?: Select extends undefined ? 
                ExtractPopulateOption<TransformPartial<SchemaPartial, Path>, T['options']> : 
                Select extends keyof ObjectGetValue<TransformPartial<SchemaPartial, Path>, Path> ? 
                ExtractPopulateOption<Pick<ObjectGetValue<TransformPartial<SchemaPartial, Path>, Path>, Select>, T['options']> : never;
    model?: string;
    match?: Object;
};

populate<Paths extends ExtractTranformValidate<SchemaPartial, Paths>>(path: string, select?: undefined, match?: Object, options?: Object): QueryEnhanced<RawSchema, SchemaReadOnly, Transform<SchemaPartial, Paths>, ArrayOfResults, Primative, Lean>;
```

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by RyanCavanaugh** [comment]
This doesn't appear common enough relative to the complexity needed to support it
