### ISSUE TITLE
Compailer fake alert for reduce array function

### ISSUE THREAD

**Issue by vforv** [Microsoft/TypeScript#27466]
Version: 2.9.2

```
public ings: string[];
this.ings = this.items.reduce((prevValue: IItemModel, currentVal: IItemModel): string[] => {
      const ingrediants: string[] = [...prevValue.ingredients, ...currentVal.ingredients];
      return ingrediants;
    })
```

Showing error for this part (prevValue: IItemModel, currentVal: IItemModel):

> Type 'string[]' is not assignable to type 'IItemModel'.
>     Property 'name' is missing in type 'string[]'.
> 

Expected:

Because prevValue.ingredients has type ```string[]``` and ```this.ings``` has type string[] it should't show compilation error.

this.items is type of IItemModel[]

**Comment by DanielRosenwasser** [comment]
If you try the compiled output of your code, it won't work for beyond 2 elements.
