### ISSUE TITLE
Line number for error in array entry not helpful

### ISSUE THREAD

**Issue by danmosemsft** [Microsoft/TypeScript#2746]
Given

```TypeScript
class C { 
    x: string
}

var v: C[] = [
        { x: "str" },
        { x: "str" },
        { x: "str" },
        { x: 6 }
    ];
```
Compiling it produces:

```
test.ts(6,5): error TS2322: Type '({ x: string; } | { x: number; })[]' is not assignable to type 'C[]'.
  Type '{ x: string; } | { x: number; }' is not assignable to type 'C'.
    Type '{ x: number; }' is not assignable to type 'C'.
      Types of property 'x' are incompatible.
        Type 'number' is not assignable to type 'string'.
```

(6,5) is the location of "v". The error is at (10,11). In my case, the array was very large, so to find the error I had to examine each object in turn, or binary search by deleting chunks of it.

The typescript compiler should tell me (10, 11) somehow, and the language service should squiggle (10,11)

**Comment by RyanCavanaugh** [comment]
I'm not sure we're going to be able to do this. By the time we check that the type of the array is assignable to the variable, it's "too late" to go back and figure out which element caused the array to be of an unassignable type.

Any fix here would need some special logic for error reporting that re-checked the array elements against the target type. Seeing a PR that did that might be instructive.
