### ISSUE TITLE
User-defined type guard functions create intersection types, and thus let any's through

### ISSUE THREAD

**Issue by plievone** [Microsoft/TypeScript#27462]
**TypeScript Version:**  3.1.1, also 3.2.0-dev.20180929

**Search Terms:**

User-defined type guards, Type predicate

**Code**

`--strict=true`

```ts
// Object to be validated (combined from various sources)
const obj = {
    u: '',
    v: ('' as any),
};
// Version with type erased (`unknown` works too, and is preferred)
const obj_any: any = obj;

obj.u; // string, ok
obj.v; // any, ok for now

/**
 * Baseline OK
 */

interface A {
    u: string;
    v: string;
}
function isValidA(_obj: any): _obj is A {
    return true;
}
if (isValidA(obj)) {
    obj.u; // string, ok
    obj.v; // string, ok
}
if (isValidA(obj_any)) {
    obj_any.u; // string, ok
    obj_any.v; // string, ok
}

/**
 * With optional property, type guard fails to any
 */

interface B {
    u: string;
    v?: string;
}
function isValidB(_obj: any): _obj is B {
    return true;
}
if (isValidB(obj)) {
    obj.u; // string, ok
    obj.v; // any, unsafe (P1)
}
if (isValidB(obj_any)) {
    obj_any.u; // string, ok
    obj_any.v; // optional string | undefined, ok
}

/**
 * With conflicting property type, type guard fails to any (and has intersection type)
 */

interface C {
    u: number;
    v: number;
}
function isValidC(_obj: any): _obj is C {
    return true;
}
if (isValidC(obj)) {
    obj.u; // string & number, surprising, but compiler will catch further usage (P2)
    obj.v; // any, unsafe (P3)
}
if (isValidC(obj_any)) {
    obj_any.u; // string, ok
    obj_any.v; // number, ok
}

/**
 * Adding undefined to optional property won't be enough, still fails to any
 */

interface D {
    u: string;
    v?: string | undefined;
}
function isValidD(_obj: any): _obj is D {
    return true;
}
if (isValidD(obj)) {
    obj.u; // string, ok
    obj.v; // any, unsafe (P4)
}
if (isValidD(obj_any)) {
    obj_any.u; // string, ok
    obj_any.v; // optional string | undefined, ok
}

/**
 * Removing optionality and adding undefined works (until somebody uses optionality)
 */

interface E {
    u: string;
    v: string | undefined;
}
function isValidE(_obj: any): _obj is E {
    return true;
}
if (isValidE(obj)) {
    obj.u; // string, ok
    obj.v; // string | undefined, ok
}
if (isValidE(obj_any)) {
    obj_any.u; // string, ok
    obj_any.v; // string | undefined, ok
}
```

**Expected behavior:**

I would have expected the user-defined type guards to override any existing types. At least the optionality should not result in allowing anys through (P1), as they are difficult to notice. Narrowing to intersection types (P2) can sometimes be reasonable (refinement by successive type guards?), but even then that `string & number` should result in `never` or be some compilation error for the whole object in question.

**Actual behavior:**

I have marked the problems with (P1), (P2), (P3) and (P4) above. It is surprising if this has been the case for long, as I have relied on user-defined type guards as the entry to the type system and don't remember it working like this (but perhaps haven't just noticed it, as those anys won't trigger any errors later without linter in compiling mode). Now I have to remove all optionalities in interfaces, or ensure that everywhere where the validators are used, they are used on an object with types erased (as unknown), or at least run the linter in compiling mode and inspect all places where 'no-unsafe-any' is suspiciously raised (that's how I found out about this behaviour).

**Playground Link:**  [Here](http://www.typescriptlang.org/play/#src=%2F%2F%20Object%20to%20be%20validated%20(combined%20from%20various%20sources)%0D%0Aconst%20obj%20%3D%20%7B%0D%0A%20%20%20%20u%3A%20''%2C%0D%0A%20%20%20%20v%3A%20(''%20as%20any)%2C%0D%0A%7D%3B%0D%0A%2F%2F%20Version%20with%20type%20erased%20(%60unknown%60%20works%20too%2C%20and%20is%20preferred)%0D%0Aconst%20obj_any%3A%20any%20%3D%20obj%3B%0D%0A%0D%0Aobj.u%3B%20%2F%2F%20string%2C%20ok%0D%0Aobj.v%3B%20%2F%2F%20any%2C%20ok%20for%20now%0D%0A%0D%0A%2F**%0D%0A%20*%20Baseline%20OK%0D%0A%20*%2F%0D%0A%0D%0Ainterface%20A%20%7B%0D%0A%20%20%20%20u%3A%20string%3B%0D%0A%20%20%20%20v%3A%20string%3B%0D%0A%7D%0D%0Afunction%20isValidA(_obj%3A%20any)%3A%20_obj%20is%20A%20%7B%0D%0A%20%20%20%20return%20true%3B%0D%0A%7D%0D%0Aif%20(isValidA(obj))%20%7B%0D%0A%20%20%20%20obj.u%3B%20%2F%2F%20string%2C%20ok%0D%0A%20%20%20%20obj.v%3B%20%2F%2F%20string%2C%20ok%0D%0A%7D%0D%0Aif%20(isValidA(obj_any))%20%7B%0D%0A%20%20%20%20obj_any.u%3B%20%2F%2F%20string%2C%20ok%0D%0A%20%20%20%20obj_any.v%3B%20%2F%2F%20string%2C%20ok%0D%0A%7D%0D%0A%0D%0A%2F**%0D%0A%20*%20With%20optional%20property%2C%20type%20guard%20fails%20to%20any%0D%0A%20*%2F%0D%0A%0D%0Ainterface%20B%20%7B%0D%0A%20%20%20%20u%3A%20string%3B%0D%0A%20%20%20%20v%3F%3A%20string%3B%0D%0A%7D%0D%0Afunction%20isValidB(_obj%3A%20any)%3A%20_obj%20is%20B%20%7B%0D%0A%20%20%20%20return%20true%3B%0D%0A%7D%0D%0Aif%20(isValidB(obj))%20%7B%0D%0A%20%20%20%20obj.u%3B%20%2F%2F%20string%2C%20ok%0D%0A%20%20%20%20obj.v%3B%20%2F%2F%20any%2C%20unsafe%20(P1)%0D%0A%7D%0D%0Aif%20(isValidB(obj_any))%20%7B%0D%0A%20%20%20%20obj_any.u%3B%20%2F%2F%20string%2C%20ok%0D%0A%20%20%20%20obj_any.v%3B%20%2F%2F%20optional%20string%20%7C%20undefined%2C%20ok%0D%0A%7D%0D%0A%0D%0A%2F**%0D%0A%20*%20With%20conflicting%20property%20type%2C%20type%20guard%20fails%20to%20any%20(and%20has%20intersection%20type)%0D%0A%20*%2F%0D%0A%0D%0Ainterface%20C%20%7B%0D%0A%20%20%20%20u%3A%20number%3B%0D%0A%20%20%20%20v%3A%20number%3B%0D%0A%7D%0D%0Afunction%20isValidC(_obj%3A%20any)%3A%20_obj%20is%20C%20%7B%0D%0A%20%20%20%20return%20true%3B%0D%0A%7D%0D%0Aif%20(isValidC(obj))%20%7B%0D%0A%20%20%20%20obj.u%3B%20%2F%2F%20string%20%26%20number%2C%20surprising%2C%20but%20compiler%20will%20catch%20further%20usage%20(P2)%0D%0A%20%20%20%20obj.v%3B%20%2F%2F%20any%2C%20unsafe%20(P3)%0D%0A%7D%0D%0Aif%20(isValidC(obj_any))%20%7B%0D%0A%20%20%20%20obj_any.u%3B%20%2F%2F%20string%2C%20ok%0D%0A%20%20%20%20obj_any.v%3B%20%2F%2F%20number%2C%20ok%0D%0A%7D%0D%0A%0D%0A%2F**%0D%0A%20*%20Adding%20undefined%20to%20optional%20property%20won't%20be%20enough%2C%20still%20fails%20to%20any%0D%0A%20*%2F%0D%0A%0D%0Ainterface%20D%20%7B%0D%0A%20%20%20%20u%3A%20string%3B%0D%0A%20%20%20%20v%3F%3A%20string%20%7C%20undefined%3B%0D%0A%7D%0D%0Afunction%20isValidD(_obj%3A%20any)%3A%20_obj%20is%20D%20%7B%0D%0A%20%20%20%20return%20true%3B%0D%0A%7D%0D%0Aif%20(isValidD(obj))%20%7B%0D%0A%20%20%20%20obj.u%3B%20%2F%2F%20string%2C%20ok%0D%0A%20%20%20%20obj.v%3B%20%2F%2F%20any%2C%20unsafe%20(P4)%0D%0A%7D%0D%0Aif%20(isValidD(obj_any))%20%7B%0D%0A%20%20%20%20obj_any.u%3B%20%2F%2F%20string%2C%20ok%0D%0A%20%20%20%20obj_any.v%3B%20%2F%2F%20optional%20string%20%7C%20undefined%2C%20ok%0D%0A%7D%0D%0A%0D%0A%2F**%0D%0A%20*%20Removing%20optionality%20and%20adding%20undefined%20works%20(until%20somebody%20uses%20optionality)%0D%0A%20*%2F%0D%0A%0D%0Ainterface%20E%20%7B%0D%0A%20%20%20%20u%3A%20string%3B%0D%0A%20%20%20%20v%3A%20string%20%7C%20undefined%3B%0D%0A%7D%0D%0Afunction%20isValidE(_obj%3A%20any)%3A%20_obj%20is%20E%20%7B%0D%0A%20%20%20%20return%20true%3B%0D%0A%7D%0D%0Aif%20(isValidE(obj))%20%7B%0D%0A%20%20%20%20obj.u%3B%20%2F%2F%20string%2C%20ok%0D%0A%20%20%20%20obj.v%3B%20%2F%2F%20string%20%7C%20undefined%2C%20ok%0D%0A%7D%0D%0Aif%20(isValidE(obj_any))%20%7B%0D%0A%20%20%20%20obj_any.u%3B%20%2F%2F%20string%2C%20ok%0D%0A%20%20%20%20obj_any.v%3B%20%2F%2F%20string%20%7C%20undefined%2C%20ok%0D%0A%7D%0D%0A) (To see the types, hover on the variables on the the left side)

**Related Issues:** 

Searched but didn't find.

Edit: Case E was clipped at first

**Comment by RyanCavanaugh** [comment]
This is the intended behavior. Type guards are assumed to "tell the truth" about the types they're operating on; the narrowing rules are not really flexible at this point and have been developed based on actual use cases.

**Comment by plievone** [comment]
Thanks, that is very good to know.
