### ISSUE TITLE
Make first time contributions easy

### ISSUE THREAD

**Issue by AjayPoshak** [Microsoft/TypeScript#27469]
## Search Terms
Contributing.md, first-time contribution

## Suggestion
A better getting started guide or a section in `CONTRIBUTING.md` to help guide the first time, contributors.  I made my first contribution to this repo and learning curve was steep.

## Use Cases
 - Cloning this repo using simple `git clone` is very time taking.

 - Building and running it locally in other projects is something should be mentioned here. In my case, I was trying to test `tsc watch` in my project by symlinking Typescript which wasn't working. 

## Examples

- Approach to clone it using `depth` in `git clone`
- How to run it locally.  Many contributors or enthusiast like me would try to run Typescript in their other local projects first before raising a PR to fix the issue.

## Checklist

My suggestion meets these guidelines:
* [X] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by AjayPoshak** [comment]
If approved, I would love to raise PR to update docs.

**Comment by AjayPoshak** [comment]
My updates would be very small, just a few lines addition would do.

**Comment by Kingwl** [comment]
actually, i spent more than one day to start my first contribution 🤷🏻‍♂️
