### ISSUE TITLE
Special case `primitive | exact-value` unions for documentation purposes

### ISSUE THREAD

**Issue by mihailik** [Microsoft/TypeScript#27494]
## Search Terms
union primitive value 

## Suggestion

There's a simple intuitive pattern we use when modelling JSON data types for API calls:

```ts
type RawDocumentDetails = {
  documentId:  string   | "0036x2-front-desk-importABC12";
  indexName:  string  | "db_2018_0210_morning123";
  score:  number  | 4;
  . . .
}
```

We describe the type plus give a real-life example for reader/developer to have an idea what to expect.

It works great and fits into TypeScript syntax. But IDE features (tooltips, completions) don't quite light-up, as unions are collapsed to the base primitive type.

Of course we DO WANT the unions to collapse as far as actual type checking, overloads, inheritance are applied. Meaning `string | "abc"` should act EXACTLY like `string` except for pretty-printing in rich code APIs and error messages.

And it's fine to limit this behaviour to very straightforward cases only, i.e. non-generic, non-keyof types.

My suggestion meets these guidelines:
* [X] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by RyanCavanaugh** [comment]
We use type identity for caching and optimization everywhere; turning `string | "Foo"` into its own type (which is what we'd have to do to traffic this around everywhere) would actually have nontrivial perf implications as well as complicating a bunch of other code paths where we check for "is exactly the one `string` type".

It's arguable that it should even be legal to write immediately-collapsing types like this in the first place; it's a big source of user confusion. I would recommend using actual documentation syntax for documentation purposes.
