### ISSUE TITLE
Switch over discriminated union inside while loop is broken

### ISSUE THREAD

**Issue by WiseBird** [Microsoft/TypeScript#27493]
**TypeScript Version:**  3.2.0-dev.20181002

**Search Terms:** tagged/discriminated unions unreachable/conditions 

**Code**

```ts
enum Types { Str = 1, Num = 2 }
type Instance = StrType | NumType;
interface StrType {
    type: Types.Str;
    value: string;
    length: number;
}
interface NumType {
    type: Types.Num;
    value: number;
}

function func(inst: Instance) {
    if (false) {
        switch (inst.type) {
            case Types.Str: {
                console.log(inst.value.length);
                break;
            }
            case Types.Num: {
                console.log(inst.value.toExponential);
                break;
            }
        }
    }
}
```

**Expected behavior:**
No errors

**Actual behavior:**
```
Error:(17, 40) TS2339: Property 'length' does not exist on type 'string | number'.
  Property 'length' does not exist on type 'number'.
Error:(21, 40) TS2339: Property 'toExponential' does not exist on type 'string | number'.
  Property 'toExponential' does not exist on type 'string'.
```

**Code**
```ts
function func2(inst: Instance) {
    while (true) {
        switch (inst.type) {
            case Types.Str: {
                console.log(inst.value.length);
                break;
            }
            case Types.Num: {
                console.log(inst.value.toExponential);
                break;
            }
        }
    }
}
```

**Expected behavior:**
No errors

**Actual behavior:**
```
Error:(21, 40) TS2339: Property 'toExponential' does not exist on type 'string'.
```

**Playground Link:** 
[Playground](https://www.typescriptlang.org/play/index.html#src=enum%20Types%20%7B%20Str%20%3D%201%2C%20Num%20%3D%202%20%7D%0D%0Atype%20Instance%20%3D%20StrType%20%7C%20NumType%3B%0D%0Ainterface%20StrType%20%7B%0D%0A%20%20%20%20type%3A%20Types.Str%3B%0D%0A%20%20%20%20value%3A%20string%3B%0D%0A%20%20%20%20length%3A%20number%3B%0D%0A%7D%0D%0Ainterface%20NumType%20%7B%0D%0A%20%20%20%20type%3A%20Types.Num%3B%0D%0A%20%20%20%20value%3A%20number%3B%0D%0A%7D%0D%0A%0D%0Afunction%20func(inst%3A%20Instance)%20%7B%0D%0A%20%20%20%20if%20(false)%20%7B%0D%0A%20%20%20%20%20%20%20%20switch%20(inst.type)%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20case%20Types.Str%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20console.log(inst.value.length)%3B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20break%3B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20case%20Types.Num%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20console.log(inst.value.toExponential)%3B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20break%3B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Afunction%20func2(inst%3A%20Instance)%20%7B%0D%0A%20%20%20%20while%20(true)%20%7B%0D%0A%20%20%20%20%20%20%20%20switch%20(inst.type)%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20case%20Types.Str%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20console.log(inst.value.length)%3B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20break%3B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20case%20Types.Num%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20console.log(inst.value.toExponential)%3B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20break%3B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%7D%0D%0A%7D)

**Related Issues:** 
Not found

**Comment by RyanCavanaugh** [comment]
Duplicate #26914 - search for "unreachable" 🙃

**Comment by WiseBird** [comment]
@RyanCavanaugh, what about second case?
