### ISSUE TITLE
Object destructuring loses type inference

### ISSUE THREAD

**Issue by Ky6uk** [Microsoft/TypeScript#27497]
**TypeScript Version:**  3.1.1

**Search Terms:**
* type inference, destructuring, type narrowing

**Code**

```ts
interface A {
  hasValue: true;
  value: string;
}

interface B {
  hasValue: false;
}

function checkOne(args: A | B) {
  return args.hasValue && args.value;
  //                           ^^^^^ this is ok, 'args' infers type A
}

function checkTwo(args: A | B) {
  const { hasValue } = args;

  return hasValue && args.value;
  //                      ^^^^^ Error: Property 'value' does not exist on type 'B'.
}
```

**Expected behavior:**
Both `checkOne` and `checkTwo` compiled without errors.

**Actual behavior:**
Function `checkTwo` has compilation errors.

**Playground Link:**  [typescriptlang.org](https://www.typescriptlang.org/play/index.html#src=interface%20A%20%7B%0D%0A%20%20hasValue%3A%20true%3B%0D%0A%20%20value%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20B%20%7B%0D%0A%20%20hasValue%3A%20false%3B%0D%0A%7D%0D%0A%0D%0Afunction%20checkOne(args%3A%20A%20%7C%20B)%20%7B%0D%0A%20%20return%20args.hasValue%20%26%26%20args.value%3B%0D%0A%7D%0D%0A%0D%0Afunction%20checkTwo(args%3A%20A%20%7C%20B)%20%7B%0D%0A%20%20const%20%7B%20hasValue%20%7D%20%3D%20args%3B%0D%0A%0D%0A%20%20return%20hasValue%20%26%26%20args.value%3B%0D%0A%7D)

**Related Issues:** I can't find related issues, but I am sure this is already known issue.

**Comment by MarcosAtApprentice** [comment]
How can I work around this and force typescript to infer the type from the assignment?
