### ISSUE TITLE
constant expression

### ISSUE THREAD

**Issue by KSXGitHub** [Microsoft/TypeScript#27504]
## Search Terms

constant expression

## Suggestion

I want this to be possible

```typescript
const a: true = 12 === 12
const b: 5 = 2 + 3
const f: (): 'ab' => 'a' + 'b'
```

Preferably, TypeScript should provide a feature to calculate them ahead of time resulting the following JavaScript code:

```javascript
const a = true
const b = 5
const f = () => 'ab'
```

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by RyanCavanaugh** [comment]
Duplicate #720
