### ISSUE TITLE
Give anchor links to TS website headings

### ISSUE THREAD

**Issue by octref** [microsoft/TypeScript#27503]
I find it cumbersome to link to a specific piece in the TS doc, for example: http://www.typescriptlang.org/docs/handbook/advanced-types.html#string-literal-types

The website doesn't show anchor for all its headings. Something like GitHub API or Vue API doc's style of anchors would be great:

GitHub shows this on hover:

![image](https://user-images.githubusercontent.com/4033249/46365937-b575ed80-c62e-11e8-8ac6-602cead12f81.png)

Vue makes the anchor (#) and the header itself a hyperlink for the anchored url:

![image](https://user-images.githubusercontent.com/4033249/46365969-d2122580-c62e-11e8-9978-bf50a8fe27bb.png)

**Comment by derekdkim** [comment]
I can add the anchor tags like the Vue API documentation. Should this be added for every heading in the documentations tab?

**Comment by VerteDinde** [comment]
@derekdkim If you're still interested in giving it a go, it looks like you can add anchors to .md files using this: https://gist.github.com/asabaylus/3071099

**Comment by suzicurran** [comment]
Put a PR up for just the Basic Types page, as an example/experiment in this vein.

**Comment by derekdkim** [comment]
Oh, I was going to put one up when I finished every page. If @suzicurran 's PR is the way TS wants to proceed with it, I will open a PR for the rest of the pages.

**Comment by orta** [comment]
This is in! I added it a few weeks back 👍
