### ISSUE TITLE
Class implementation ignores optionality of method parameter in interface

### ISSUE THREAD

**Issue by maximgavrilov** [Microsoft/TypeScript#27523]
**TypeScript Version:**  3.2.0-dev.201xxxxx

**Search Terms:** interface, optional parameter

**Code**

```ts
interface IRunner {
    run(s?: string): void;
}

class Runner implements IRunner {
    run(s: string): void {
        console.log(s.length);
    }
}

const runner: IRunner = new Runner();
runner.run(undefined);
```

**Expected behavior:**

Compilation error once strictNullChecks like TS2416: Type '(s: string) => void' is not assignable to type '(s?: string | undefined) => void'.

**Actual behavior:**

No compilation errors.

[**Playground Link** ](http://www.typescriptlang.org/play/#src=interface%20IRunner%20%7B%0D%0A%20%20%20%20run(s%3F%3A%20string)%3A%20void%3B%0D%0A%7D%0D%0A%0D%0Aclass%20Runner%20implements%20IRunner%20%7B%0D%0A%20%20%20%20run(s%3A%20string)%3A%20void%20%7B%0D%0A%20%20%20%20%20%20%20%20console.log(s.length)%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aconst%20runner%3A%20IRunner%20%3D%20new%20Runner()%3B%0D%0Arunner.run(undefined)%3B%0D%0A)

**Comment by RyanCavanaugh** [comment]
Things declared with method syntax are subject to parameter bivariance (see FAQ) due to the prevalence of (yes, unsound) class hierarchies in the wild that float their parameter types in the "wrong" direction

**Comment by sharwell** [comment]
@RyanCavanaugh I'm assuming this is equivalent to the following example?

```
interface TestInterface {
	Method(text: string | undefined): void;
}

class TestClass implements TestInterface {
	public Method(text: string): void {
		console.log(text);
	}
}
```

I'm trying to find a way to validate these signatures at compile time. The implementation in my example has a bug; it should have been declared with the parameter `text: string | undefined`, but the omission of `undefined` can lead an implementer to make incorrect assumptions about the arguments.

**Comment by RyanCavanaugh** [comment]
@sharwell correct. Unfortunately there's not a way to enable strict checks here (doing so would be trivial from an implementation perspective, but would immediately create errors in the DOM lib)
