### ISSUE TITLE
TS returns global symbols for member completion

### ISSUE THREAD

**Issue by asvetliakov** [microsoft/TypeScript#27529]
**TypeScript Version:**  3.1.1

**Search Terms:**
Completion
Member completion

**Behavior:**
This GIF must be self-explained:
![img](http://g.recordit.co/pxayadcTEo.gif)

**Expected behavior:**
Only member completion (save/remove/etc...) should be returned

**Actual behavior**
It VERY often returns global completions. This is very frustrating

**Additional information**
Pretty large private TS monorepo project (8 subprojects, ~400 TS files). Also may be related - diagnostic errors often don't disappear for valid code until next change.

**Comment by andy-ms** [comment]
I think this is the behavior of VSCode when TypeScript doesn't provide any completions at all -- this can happen when we didn't get a good type for `db.manager`. So in this case it's probably vscode providing the completions, not TypeScript. You could verify by opening tsserver.log (ctrl-shift-p, "TypeScript: Open TS Server Log"), which will probably end in something like: `{"seq":0,"type":"response","command":"completionInfo","request_seq":28,"success":false,"message":"No content available."}`

**Comment by asvetliakov** [comment]
```db.manager``` has good known type -> you can see it has correct completions in few slides (```getRepository```, ```getTreeRepository```, etc...)

Here is the relevant part of log confirming that TS returns global completions, not vscode:

```
Info 710  [17:9:37.429] request:
    {"seq":10,"type":"request","command":"geterr","arguments":{"delay":0,"files":["c:/work/ramble/packages/backendjs/src/repositories/__tests__/Test_FPsec.ts"]}}
Perf 711  [17:9:37.429] 10::geterr: async elapsed time (in milliseconds) 0.1857
Info 712  [17:9:37.429] request:
    {"seq":11,"type":"request","command":"change","arguments":{"insertString":".","file":"c:/work/ramble/packages/backendjs/src/repositories/__tests__/Test_FPsec.ts","line":46,"offset":15,"endLine":46,"endOffset":15}}
Perf 713  [17:9:37.429] 11::change: async elapsed time (in milliseconds) 0.0897
Info 714  [17:9:37.429] request:
    {"seq":12,"type":"request","command":"completionInfo","arguments":{"file":"c:/work/ramble/packages/backendjs/src/repositories/__tests__/Test_FPsec.ts","line":46,"offset":16,"includeExternalModuleExports":true,"includeInsertTextCompletions":true,"triggerCharacter":"."}}
Info 715  [17:9:37.430] Starting updateGraphWorker: Project: c:/work/ramble/packages/backendjs/tsconfig.json
Info 716  [17:9:37.430] Finishing updateGraphWorker: Project: c:/work/ramble/packages/backendjs/tsconfig.json Version: 2 structureChanged: true Elapsed: 0ms
Info 717  [17:9:37.434] getCompletionData: Get current token: 1
Info 718  [17:9:37.434] getCompletionData: Is inside comment: 0
Info 719  [17:9:37.434] getCompletionData: Get previous token 1: 0
Info 720  [17:9:37.434] getCompletionsAtPosition: isCompletionListBlocker: 0
Info 721  [17:9:37.504] getCompletionData: Semantic work: 70
Info 722  [17:9:37.519] getCompletionsAtPosition: getCompletionEntriesFromSymbols: 14
Perf 723  [17:9:37.530] 12::completionInfo: elapsed time (in milliseconds) 100.3318
Info 724  [17:9:37.531] response:
    {"seq":0,"type":"response","command":"completionInfo","request_seq":12,"success":true,"body":{"isGlobalCompletion":true,"isMemberCompletion":false,"isNewIdentifierLocation":false,"entries":[{"name":"_","kind":"alias","kindModifiers":"declare","sortText":"0"},{"name":"__dirname","kind":"var","kindModifiers":"declare","sortText":"0"},{"name":"__filename","kind":"var","kindModifiers":"declare","sortText":"0"},{"name":"__promisify__","kind":"function","kindModifiers":"declare","sortText":"0","hasAction":true,"source":"c:/work/ramble/node_modules/@types/glob/index"},{"name":"abbreviate","kind":"function","kindModifiers":"export,declare","sortText":"0","hasAction":true,"source":"c:/work/ramble/packages/backendjs/node_modules/typeorm/util/StringUtils"},{"name":"AbstractRepository","kind":"class","kindModifiers":"export,declare","sortText":"0","hasAction":true,"source":"c:/work/ramble/packages/backendjs/node_modules/typeorm/repository/AbstractRepository"},{"name":"ACCEPT_INVITE","kind":"const","kindModifiers":"export,declare","sortText":"0","hasAction":true,"source":"c:/work/ramble/packages/ramble-api/build/portal/constants/invite"},{"name":"AcceptInvite","kind":"class","kindModifiers":"export","sortText":"0","hasAction":true,"source":"c:/work/ramble/packages/backendjs/src/processing/portal/userHandlers/invite/AcceptInvite"},
// And many others global things, classes, global constants, global functions, etc... Much of them
```

**Comment by andy-ms** [comment]
Could you provide a complete repro?

**Comment by asvetliakov** [comment]
Sorry this is not easily reproducible and happens only in large repos (small projects are fine). [Here is the full log file](https://gist.githubusercontent.com/asvetliakov/cd5cb2393974b312014a1bc497d81db7/raw/cba59cd0e962b6c311d4967bcf9da1036600ea43/TSLog%2520-%2520%252327529) if it helps.

Search for ```findByIds``` in the log-file - these requests are returning normal completions, others are returning global completions. I just insert & delete dot ```.``` after ```db.manager```

If won't help, i think we can provide access to git private repo

**Comment by asvetliakov** [comment]
Also looks like this depends on the typing speed: the bug never happens if there is a noticeable delay (>1 second) before typing ```.```. So this may be a kind of race condition - completion request doesn't wait for previous change request or something like it. Hope this helps.

**Comment by Kovensky** [comment]
This seems to be a side effect of an issue in tsservice that's been happening since 3.0 or so. The parsing is itself slow, and it seems to always be a few steps behind my actual typing.

Sometimes I get stuck with an error message about a syntax error or type error that just goes away if I leave the editor alone for 5 seconds, or go and type a trailing space and delete it.

**Comment by asvetliakov** [comment]
i found that big ```node_modules``` folder somehow affects my original issue, even if the single project file doesn't use any import and has ```types: []``` (so it mustn't load any types). Trying to get the repro.

**Comment by asvetliakov** [comment]
Repro here:

https://github.com/asvetliakov/typescript-27529

**Comment by asvetliakov** [comment]
Related #27233 , https://github.com/Microsoft/typescript-styled-plugin/issues/78
