### ISSUE TITLE
Make Symbol.* (e.g. Symbol.iterator) unique symbols

### ISSUE THREAD

**Issue by KSXGitHub** [microsoft/TypeScript#27525]
## Suggestion

Use this:

```typescript
declare function Symbol (x?: string | number): symbol

declare namespace Symbol {
  const prototype: symbol
  const iterator: unique symbol
}
```

Or this:

```typescript
interface SymbolConstructor {
  (x?: string | number): symbol
  readonly prototype: symbol
  readonly iterator: unique symbol
}

declare var Symbol: SymbolConstructor
```

Instead of this:

```typescript
interface SymbolConstructor {
  (x?: string | number): symbol
  readonly prototype: symbol
  readonly iterator: symbol
}

declare var Symbol: SymbolConstructor
```

## Use Cases

Right now, I can do this for custom `unique symbol`:

```typescript
const foo = Symbol() // unique symbol
const bar: typeof foo = foo

const baz: {
	[foo]: number
} = {
	[bar]: 123
}
```

But not for `Symbol.*`

```typescript
// Expecting 'typeof Symbol.iterator' but received 'symbol'
const iterator: typeof Symbol.iterator = Symbol.iterator

// This is not working
const iterable: Iterable<number> = {
  * [iterator] () {
    yield * [0, 1, 2, 3]
  }
}
```

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

---

[Playground Link](https://www.typescriptlang.org/play/#src=declare%20function%20FakeSymbol%20()%3A%20symbol%0D%0A%0D%0Adeclare%20namespace%20FakeSymbol%20%7B%0D%0A%20%20const%20prototype%3A%20symbol%0D%0A%20%20const%20iterator%3A%20unique%20symbol%0D%0A%7D%0D%0A%0D%0Aconst%20iterator%3A%20typeof%20FakeSymbol.iterator%20%3D%20FakeSymbol.iterator%0D%0A%0D%0Aconst%20foo%3A%20%7B%0D%0A%20%20%5BFakeSymbol.iterator%5D%3A%20number%0D%0A%7D%20%3D%20%7B%0D%0A%20%20%5Biterator%5D%3A%20123%0D%0A%7D%0D%0A) ([This](https://www.typescriptlang.org/play/#src=interface%20FakeSymbolConstructor%20%7B%0D%0A%20%20(x%3F%3A%20number%20%7C%20string)%3A%20symbol%0D%0A%20%20readonly%20prototype%3A%20symbol%0D%0A%20%20readonly%20iterator%3A%20unique%20symbol%0D%0A%7D%0D%0A%0D%0Adeclare%20const%20FakeSymbol%3A%20FakeSymbolConstructor%0D%0A%0D%0Aconst%20iterator%3A%20typeof%20FakeSymbol.iterator%20%3D%20FakeSymbol.iterator%0D%0A%0D%0Aconst%20foo%3A%20%7B%0D%0A%20%20%5BFakeSymbol.iterator%5D%3A%20number%0D%0A%7D%20%3D%20%7B%0D%0A%20%20%5Biterator%5D%3A%20123%0D%0A%7D%0D%0A) also works)

[Related Issue](https://github.com/Microsoft/TypeScript/issues/27524)

**Comment by RyanCavanaugh** [comment]
@rbuckton what are your thoughts on this?

**Comment by weswigham** [comment]
https://github.com/Microsoft/TypeScript/pull/24738 also works around the old-lib issue by considering any symbols under the global `Symbol` constructor as `unique symbol`s.

**Comment by ExE-Boss** [comment]
<https://github.com/microsoft/TypeScript/pull/24738> would&nbsp;fix&nbsp;this in&nbsp;a&nbsp;manner that’s&nbsp;compatible with&nbsp;old&nbsp;`.d.ts`&nbsp;files.
