### ISSUE TITLE
Crash from getSemanticDiagnostics in type annotation in array assignment destructuring

### ISSUE THREAD

**Issue by yuit** [Microsoft/TypeScript#2752]
Type following code in a typescript file:
```ts
var [a,b,c]:
```
VS throw a script error.
![get_semantic_destructuring](https://cloud.githubusercontent.com/assets/489742/7126378/906887ba-e1ed-11e4-8e49-0671262484c4.PNG)

**Comment by mhegazy** [comment]
I could not get this to repro.
