### ISSUE TITLE
Disorder of words in section 'Running the Tests' in Contributiing.md

### ISSUE THREAD

**Issue by noamyogev84** [Microsoft/TypeScript#27534]
**TypeScript Version:**  master-branch

**Search Terms:**
contributing.md, run tests documentation
**Expected behavior:**
Correct order: "This **will run** all tests...."
**Actual behavior:**
Misorder: "This **run will** all tests..."
**Playground Link:** 
https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#running-the-tests

**Related Issues:** 
No

**Comment by DanielRosenwasser** [comment]
Thanks!
