### ISSUE TITLE
Union of tuple types destructures incorrectly

### ISSUE THREAD

**Issue by osdiab** [Microsoft/TypeScript#27543]
**TypeScript Version:**  3.2.0-dev.20181004
**Search Terms:** union tuple array destructuring
**Code**

```ts
type Unioned = [string] | [string, number]
const ex: Unioned = ["hi"] as Unioned

// unexpected: y is typed as string | number, instead of number | undefined
const [x, y] = ex;
```

**Expected behavior:**
`y` typed as `number | undefined`

**Actual behavior:**
`y` typed as `string | number`

**Playground Link:** [Playground](http://www.typescriptlang.org/play/#src=type%20Unioned%20%3D%20%5Bstring%5D%20%7C%20%5Bstring%2C%20number%5D%0Aconst%20ex%3A%20Unioned%20%3D%20%5B%22hi%22%5D%20as%20Unioned%0A%0A%2F%2F%20unexpected%3A%20y%20is%20typed%20as%20string%20%7C%20number%0Aconst%20%5Bx%2C%20y%5D%20%3D%20ex%3B)

**Related Issues:** Not really

**Comment by ulrichb** [comment]
@ahejlsberg 

I have a similar situation with function args tuples (and get `TS2556: Expected 1 arguments, but got 2 or more`). Is this the same issue?

```ts
type RequiredArg = string;
type ArgsTuple = [RequiredArg, ...string[]];

interface FuncHolderA {
    readonly func: (...args: ArgsTuple) => void;
}

interface FuncHolderB {
    readonly func: (arg: RequiredArg) => void;
}

//

type FuncHolder = FuncHolderA | FuncHolderB;

function invoke(fh: FuncHolder) {
    const args: ArgsTuple = ["x", "y", "z"];

    fh.func(...args); // TS2556: Expected 1 arguments, but got 2 or more.
    fh.func(args[0]); // compiles, but isn't that what we want
}

//

const fhA: FuncHolderA = { func: (x, y, z) => console.log(x, y, z) };
invoke(fhA);

const fhB: FuncHolderB = { func: (x) => console.log(x) };
invoke(fhB);
```
