### ISSUE TITLE
Weak inference of String Literal Types by const

### ISSUE THREAD

**Issue by takefumi-yoshii** [Microsoft/TypeScript#27540]
Needless to say, below code infferd as String Literal Types.
```typescript
export const INCREMENT = "INCREMENT"
export const SET_COUNT = "SET_COUNT" as "SET_COUNT"
```
```typescript
// result of infer
const INCREMENT: "INCREMENT"
const SET_COUNT: "SET_COUNT"
```
When put them in the object, It is no longer as String Literal Types without assertion.
Is it correct to be interpreted as weak inference?

```typescript
const object = {
  INCREMENT,
  SET_COUNT
}
```
```typescript
// result of infer
const object: {
  INCREMENT: string;
  SET_COUNT: "SET_COUNT";
}
```

And this problem can avoid below code.

```typescript
const object = {
  INCREMENT: INCREMENT as (typeof INCREMENT),
  SET_COUNT
}
```
```typescript
// result of infer
const object: {
  INCREMENT: "INCREMENT";
  SET_COUNT: "SET_COUNT";
}
```
I am waiting for reply. Best reguards.

**Comment by jack-williams** [comment]
I think the solution to this is covered by #10195

**Comment by takefumi-yoshii** [comment]
@jack-williams thanks! I'll track them.

**Comment by takefumi-yoshii** [comment]
umm...Is the pointer reference strength different depending on whether assertion is present or not？

**Comment by ahejlsberg** [comment]
See #11126 for a description of this behavior.

**Comment by takefumi-yoshii** [comment]
@ahejlsberg thanks for reply. I understood about `Widening and non-widening`. I'll write some localized post about them.
