### ISSUE TITLE
Not reading the prototype chain correctly

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#27554]
_From @TANGL3SIT3S on October 4, 2018 2:16_

```js
function _super(parent, child) {
    parent.call(this);
    child.prototype = Object.create(parent.prototype);
    child.prototype.constructor = child;
}

const Animal = (function (){
    let ssn = '';

    function Animal(name) {
        this.name = name;
    }

    Animal.prototype.sayHello = function () {
        ssn = '458-49-2285';
        console.log(ssn);
    }

    return Animal;
})();


const Dog = (function () {
    let ssn = '';

    function Dog(name) {
        this.name = name;
    }

    _super(Animal, Dog);

    Dog.prototype.sayGoodbye = function () {
        console.log("Goodbye");
    }

    return Dog;
})();

console.log(new Dog().sayHello());
```
-----------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------

VSCode is telling me that sayHello() is not on the prototype chain, even though in Chrome the console reads it correctly. I believe that its a Typescript error it is saying that sayHello() is not on type on Dog, when in fact it IS. 

_Copied from original issue: Microsoft/vscode#59943_

**Comment by mjbvz** [comment]
This code is too dynamic for our intellisense to understand. Moving upstream but I think that supporting this is likely out of scope

**Comment by andy-ms** [comment]
TypeScript can't recognize that `_super` has a side effect on the prototype chain.

**Comment by TANGL3SIT3S** [comment]
Thanks guys. I really didnt know if i needed to post it or not. I figured better safe than sorry... I wanted the ability to declare private and protected fields that es6 didn't offer. VSCode is awesome! I was just co-dependent i suppose, expecting it to replace all my tools lol. But i know there is no silver bullet. You guys are awesome! Thanks again.
