### ISSUE TITLE
error TS6050: Unable to open file 'tsconfig.json'.

### ISSUE THREAD

**Issue by Acaspita** [Microsoft/TypeScript#2755]
Why?
I'm not giving reasons for this to happen:
   1- Running on windows.
   2- I've closed the tsconfig.json file.
   2- The command is "tsc" under a folder that has the following tsconfig.json file:
```
{
    "files": [
        './js/**/*.ts',
        './modules/**/*.ts'
    ]
}
```

**Comment by danquirk** [comment]
tsc config doesn't support globbing, does removing that fix the error?

**Comment by Acaspita** [comment]
yeap...
Hey, at least modify the error message! I thought the issue had to do with what it communicated! But it didn't!...

**Comment by mhegazy** [comment]
#2627 is tracking showing the errors .

**Comment by luzianz** [comment]
valid json uses **double** quotes, not single.
