### ISSUE TITLE
Simple ternary inference issue with generics

### ISSUE THREAD

**Issue by jeremybparagon** [Microsoft/TypeScript#27578]
**TypeScript Version:**  3.2.0-dev.20181004

**Code**

```ts
const f = <T>(a: number) => {
  const b: (T extends { } ? number : number) = a;
};
```

**Expected behavior:**  Successful compilation

**Actual behavior:**  I get the following error:
```
error TS2322: Type 'number' is not assignable to type 'T extends {} ? number : number'.

   const b: (T extends { } ? number : number) = a;
         ~
```

**Playground Link:** [Link](https://www.typescriptlang.org/play/#src=const%20f%20%3D%20<T>(a%3A%20number)%20%3D>%20%7B%0D%0A%20%20const%20b%3A%20(T%20extends%20%7B%20%7D%20%3F%20number%20%3A%20number)%20%3D%20a%3B%0D%0A%7D%3B%0D%0A)

**Use case:** 
I wouldn't expect anybody to write the code above. Here's something more like my original example ([link](https://www.typescriptlang.org/play/#src=const%20f%20%3D%20<B%20extends%20true%20%7C%20false>(b%3A%20B%2C%20n%3A%20number)%3A%20(true%20extends%20B%20%3F%20number%20%7C%20null%20%3A%20number)%20%3D>%20%7B%0D%0A%20%20if%20(b)%20%7B%0D%0A%20%20%20%20return%20null%20as%20true%20extends%20B%20%3F%20null%20%3A%20never%3B%0D%0A%20%20%7D%0D%0A%20%20return%20n%3B%0D%0A%7D%3B%0D%0A)):
```ts
const f = <B extends true | false>(b: B, n: number): (true extends B ? number | null : number) => {
  if (b) {
    return null as true extends B ? null : never;
  }
  return n;
};
```
This gives the error
```
error TS2322: Type 'number' is not assignable to type 'true extends B ? number : number'.

   return n;
   ~~~~~~~~~
```
In this practical example, there is a workaround, changing the return type to `number | (true extends B ? null : never)`. But it was hard for me to figure out what was making TypeScript unhappy, since this seemed too simple an inference for TypeScript to miss.

**Comment by jack-williams** [comment]
The first example is due to this #27530 I think.

The second example is covered by this #26933 I think.

**Comment by jeremybparagon** [comment]
Both should be covered by #26933. Thanks.
