### ISSUE TITLE
isPartOfTypeNode missing SyntaxKind.ObjectKeyword check?

### ISSUE THREAD

**Issue by NaridaL** [Microsoft/TypeScript#27583]
**TypeScript Version:**  master branch, see link below

**Search Terms:**
`isPartOfTypeNode `

This is related to https://github.com/TypeStrong/typedoc/issues/656.
```ts
let x: Promise<object>
```
Calling `getTypeAtLocation`  on the `ObjectKeyword` node is returning the error type instead of the `nonPrimitiveType`.

As far as I can tell (after stepping through the call and comparing to the `let x: Promise<string>` behavior`), this is due to isPartOfTypeNode not returning true for ObjectKeyword.

https://github.com/Microsoft/TypeScript/blob/master/src/compiler/utilities.ts#L975-L982

Adding it does not cause any tests to fail.

**Expected behavior:**
`getTypeAtLocation` returns nonPrimitiveType.
**Actual behavior:**
`getTypeAtLocation` returns errorType.
**Playground Link:** 

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
PR appreciated!

**Comment by flowkraD** [comment]
I would like to go ahead and make a PR if you don't mind (^_^)
