### ISSUE TITLE
Generics inferred as JSX.Element

### ISSUE THREAD

**Issue by guptaamol** [Microsoft/TypeScript#27595]
**TypeScript Version:**  3.2.0-dev.201xxxxx

**Search Terms:**
generics, JSX.Element

**Expected behavior:**
Correct Generic inferrence.

**Actual behavior:**
Generics inferred as JSX.Element.

**Playground Link:** 
Works fine in typescript playground.
The commented code works as well but there is a problem while using arrow function.

**Related Issues:** 
None.
![screenshot from 2018-10-08 00-27-31](https://user-images.githubusercontent.com/22221333/46585671-3c90ee80-ca91-11e8-9cdb-09f482f63057.png)
![screenshot from 2018-10-08 00-28-34](https://user-images.githubusercontent.com/22221333/46585673-3d298500-ca91-11e8-8c05-e0232b873835.png)

**Comment by guptaamol** [comment]
Ok I will keep this in mind.
Any work around for the same....?

**Comment by Cryrivers** [comment]
@guptaamol use normal `function` instead of arrow function. Use `as Type` instead of `<Type>` for type casting.

Seemingly you enabled `jsx` in tsconfig, if you are not using JSX, you could just disable it.
