### ISSUE TITLE
Generic mapped type assignability rules don't check modifiers type properly

### ISSUE THREAD

**Issue by mattmccutchen** [Microsoft/TypeScript#27598]
More warmup for #27484.

**TypeScript Version:**  master (85a3475df87b9c10240570f32090970262c99b54)

**Search Terms:** generic mapped type assignable assignability relation optional modifiers type

**Code**
```ts
let x: {a?: string} = {};
let y: {a: string | undefined};
y = x;  // Error, as expected

type WeirdPick1<A extends {[P in B]?: unknown}, B extends keyof any> = {[P in B]: A[P]};
type WeirdPickAll1<T> = WeirdPick1<T, keyof T>;
y = (<T>(arg: T): WeirdPickAll1<T> => arg)(x);  // OK; expected error

type WeirdPickAll2<T> = {[P in keyof Required<T>]: T[P]};
y = (<T>(arg: T): WeirdPickAll2<T> => arg)(x);  // OK; expected error

type WeirdPickAll3<T> = {[P in keyof Partial<T>]: T[P]};
y = (<T>(arg: WeirdPickAll3<T>): T => arg)<{a: string}>(x);  // OK; expected error
```

**Expected behavior:** All three `WeirdPick` constructions give errors.

**Actual behavior:** None of the `WeirdPick` constructions give errors.

**Playground Link:** [link](https://www.typescriptlang.org/play/#src=let%20x%3A%20%7Ba%3F%3A%20string%7D%20%3D%20%7B%7D%3B%0D%0Alet%20y%3A%20%7Ba%3A%20string%20%7C%20undefined%7D%3B%0D%0Ay%20%3D%20x%3B%20%20%2F%2F%20Error%2C%20as%20expected%0D%0A%0D%0Atype%20WeirdPick1%3CA%20extends%20%7B%5BP%20in%20B%5D%3F%3A%20unknown%7D%2C%20B%20extends%20keyof%20any%3E%20%3D%20%7B%5BP%20in%20B%5D%3A%20A%5BP%5D%7D%3B%0D%0Atype%20WeirdPickAll1%3CT%3E%20%3D%20WeirdPick1%3CT%2C%20keyof%20T%3E%3B%0D%0Ay%20%3D%20(%3CT%3E(arg%3A%20T)%3A%20WeirdPickAll1%3CT%3E%20%3D%3E%20arg)(x)%3B%20%20%2F%2F%20OK%3B%20expected%20error%0D%0A%0D%0Atype%20WeirdPickAll2%3CT%3E%20%3D%20%7B%5BP%20in%20keyof%20Required%3CT%3E%5D%3A%20T%5BP%5D%7D%3B%0D%0Ay%20%3D%20(%3CT%3E(arg%3A%20T)%3A%20WeirdPickAll2%3CT%3E%20%3D%3E%20arg)(x)%3B%20%20%2F%2F%20OK%3B%20expected%20error%0D%0A%0D%0Atype%20WeirdPickAll3%3CT%3E%20%3D%20%7B%5BP%20in%20keyof%20Partial%3CT%3E%5D%3A%20T%5BP%5D%7D%3B%0D%0Ay%20%3D%20(%3CT%3E(arg%3A%20WeirdPickAll3%3CT%3E)%3A%20T%20%3D%3E%20arg)%3C%7Ba%3A%20string%7D%3E(x)%3B%20%20%2F%2F%20OK%3B%20expected%20error)

**Related Issues:** none found

**Comment by ahejlsberg** [comment]
In homomorphic mapped types of one of the forms `{ [P in keyof T]: XXX }` or `{ [P in K]: XXX }`, where `K` has a constraint of the form `keyof T`, we preserve property modifiers (i.e. `readonly` and `?`) as they exist in `T`. In all other cases, the only property modifiers that will be present are those specified in the mapped type itself. See #12563 for more info.

**Comment by mattmccutchen** [comment]
@ahejlsberg I understand.  The problem is that the assignability rules are inconsistent with actual mapped type instantiation in the way they check for the special forms `{ [P in keyof T]: XXX }` and `{ [P in K]: XXX }` (where `K` is constrained by `keyof T`), hence the examples of unsoundness in my original comment.  Please reopen.  I have a draft fix for this but haven't finalized the semantics and test cases in order to submit a PR.

**Comment by n9** [comment]
I have hit a similar issue. However I am not sure whether it is the same problem or not. If not, I will open another issue.

```typescript
// my code

type FieldKind = "numeric" | "text"

interface FieldMeta {
    kind: FieldKind 
}

type FieldsMeta<T> = { [K in keyof T]-?: FieldMeta }

type Compoment = "aComponent"

type FieldComponents<T> = { [K in keyof T]-?: Compoment }

function createComponentsFromMeta<T>(meta: FieldsMeta<T>): FieldComponents<T> {
    return mapValues(meta, (value, key) => "aComponent" as Compoment)) // <-- type error here
}

// external lib

declare type ObjectKey = string | number | symbol

declare type ObjectMap<K extends ObjectKey, V> = { [P in K]: V };
declare type MapObject<K, I, O> = (value: I, key: K) => O;

 // something like lodash.mapValues
declare function mapValues<K extends ObjectKey, I, O>(obj: ObjectMap<K, I>, map: MapObject<K, I, O>): ObjectMap<K, O>
```

This will fail with 'ObjectMap<keyof T, "aComponent">' is not assignable to type 'FieldComponents<T>'.
`FieldsMeta` uses `-?` in order to require metadata also for optional fields (the same is for `FieldComponents`), for instance:

```typescript
interface Foo {
    a: number
    b?: string
}

const fooMeta: FieldsMeta<Foo> = {
    a: { kind: "numeric" }, 
    b: { kind: "text" } 
}
```

**Comment by mattmccutchen** [comment]
@n9 Your case is different from the cases in my original report (your case involves assignability between two generic mapped types, while mine involve assignability between a generic mapped type and another type), but it still falls under the summary of "Generic mapped type assignability rules don't check modifiers type properly", so I am happy to consider it included in this issue.  Now we just hope for the issue to be unmarked as "Working as intended"!

A workaround is to change the definition of `FieldComponents` to:
```ts
type FieldComponents<T> = Record<keyof T, Compoment>;
```
Then instead of using `-?`, which confuses the current assignability rule, you are using a mapped type that doesn't have a modifiers type (since the `keyof` constraint is not part of the original definition of the mapped type in `Record`), so all properties will be required.

**Comment by mattmccutchen** [comment]
@n9 Roughly.  This is one of TypeScript's many underdocumented rules that tries (and sometimes fails) to do what you want.  The decision of the "modifiers type" (if any) from which modifiers will be copied is based on the _original_ definition of the mapped type, before any type parameters are instantiated.  When you write `type FieldComponents<T> = { [K in keyof T]-?: Compoment }`, the `keyof T` appears in the original definition, so `T` is saved as the expression for the modifiers type and then gets instantiated with the type argument you passed for `T`.  When you write `type FieldComponents<T> = Record<keyof T, Compoment>`, the original definition of `Record` is `type Record<K extends keyof any, T> = {[P in K]: T}`, and the constraint `K` is a type parameter with constraint `keyof any`, so the modifiers type is `any` (or maybe there's no modifiers type at all, but either way, there are no modifiers to inherit).  This decision is made _before_ `K` is instantiated as `keyof T`.

**Comment by n9** [comment]
@mattmccutchen Thank you for your explanation. These modifiers look really great at first sight. However it seems to me now, that they are rather fragile. So there is difference between `Working as Intended` and `Working as Expected`. 

@ahejlsberg, @RyanCavanaugh  In case this is `Working as Intended`, there should be another label `Not Working as Expected` 😊

**Comment by mattmccutchen** [comment]
I agree that the determination of whether a mapped type is homomorphic is fragile and surprising, but I wouldn't expect it to be changed at this point.  But that's not what this issue is about.  This issue is about the assignability rules being inconsistent with the way homomorphic mapped types are determined.  ahejlsberg's comment accompanying the "working as intended" label does not address the cases in my original report, so I believe he just didn't read the issue carefully enough.

**Comment by ahejlsberg** [comment]
@mattmccutchen Am I correct that the issue you're referring to is this?

```ts
type Pick1<A, B extends keyof any> = {[P in keyof A & B]: A[P]};
type Pick2<A, B extends keyof any> = {[P in keyof A & B]-?: A[P]};

function foo<T>(x: T, y: Pick1<T, keyof T>, z: Pick2<T, keyof T>) {
    y = x;  // Ok
    z = x;  // Error
}
```

In other words, since `Pick1` is not a homomorphic mapped type it should behave like `Pick2`.

**Comment by mattmccutchen** [comment]
@ahejlsberg There are lots of cases in which the existing assignability rules for generic mapped types are inconsistent with the way generic mapped types are instantiated, and I was hoping that this issue would cover all of the inconsistencies we can find.  (The issue by itself is low priority unless/until realistic code is affected by the problems; I filed it because I thought if we planned to redo the assignability rules anyway for #27484, we should try to get all of these cases fixed at the same time.)

Your example is equivalent to the `WeirdPick1` case from the original report, but we now have three more examples (two more in my initial comment and one from n9), all of which (AFAICT) affect different compiler code paths.
