### ISSUE TITLE
Boxing and unboxing bug

### ISSUE THREAD

**Issue by travelcode** [Microsoft/TypeScript#27603]
I have the following code,
```
class Numeric extends Number {
     numeric:number;
    constructor(numeric: number) {
        super(numeric);
        this.numeric=numeric;
     }
}
```
Then
```
          const number=new Numeric(2);
          number.numeric;
```
An error is as follows:
`TypeError: Cannot create property 'numeric' on number '2'`
Same code in JavaScript,like this:
```
class Numeric extends Number{
   constructor(numeric){
      super(numeric);
     this.numeric=numeric
  }
}
```
run well .I think this is Boxing and unboxing bug,how to solve problems

**Comment by RyanCavanaugh** [comment]
See https://github.com/Microsoft/TypeScript/wiki/FAQ#why-doesnt-extending-built-ins-like-error-array-and-map-work

**Comment by AviVahl** [comment]
@RyanCavanaugh that wiki article mentions new.target, but the example does not match the info given on:
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-2.html
("Support for new.target" section)

**Comment by travelcode** [comment]
Thank you.
All the problems in "#27603" and "#27602" were caused by the property "compileroptions.target" of "tsconfig.json"
The property "compileroption.target" I set in "tsconfig.json" is too low.
This minimum version should be set to "es6".
Now, I think the advantage of typescript is just the "access authority" and the "strongly typed".
Compatibility is still a bad news.
