### ISSUE TITLE
Conditionally inferring a type of a missing function argument always returns {}

### ISSUE THREAD

**Issue by jamietre** [Microsoft/TypeScript#27607]
**TypeScript Version:**  3.2.0-dev.20181006

**Search Terms:** typescript conditional arguments infer

**Code**

```ts
type FirstArgument<T> = T extends (arg1: infer U, ...args: any[]) => any ? 
   U : never;
type Test = FirstArgument<() => void>;
```

**Expected behavior:**

```Test = never```

**Actual behavior:**

```Test = {}```

**Playground Link:** http://www.typescriptlang.org/play/#src=type%20FirstArgument%3CT%3E%20%3D%20T%20extends%20(arg1%3A%20infer%20U%2C%20...args%3A%20any%5B%5D)%20%3D%3E%20any%20%3F%20U%20%3A%20never%3B%0D%0Atype%20Test%20%3D%20FirstArgument%3C()%20%3D%3E%20void%3E%3B%0D%0A%0D%0A%2F%2F%20should%20not%20be%20allowed%0D%0Aconst%20x%3A%20Test%20%3D%20%7B%0D%0A%20%20foo%3A%20'bar'%0D%0A%7D%3B

**Related Issues:** 

Seems similar but this problem is much broader in scope; I can't find any workaround to determine whether the inferred argument exists or not, if the expected type is an object.

https://github.com/Microsoft/TypeScript/issues/24784

**Comment by RyanCavanaugh** [comment]
Functions with fewer arguments are subtypes of functions with more arguments, so TS has to choose the truthy branch of that conditional. `U` has to be *something* so `{}` is the most general type it can name there.

**Comment by jamietre** [comment]
OK, so if I want to use conditional types to create a type branch based on whether or not a function has an argument, how can I do this? Everything extends `{}` so there seems to be no way to differentiate this type.

**Comment by jack-williams** [comment]
```ts
type Args<T extends Function> =
    T extends (...args: infer U) => any ? 
    U : never;
type First<T> = T extends any[] ? T[0] : never;
type FirstArgument<T extends Function> = First<Args<T>>; 
```

**Comment by jamietre** [comment]
THANK YOU!
