### ISSUE TITLE
Type isn't checked when using an array<type> as return value

### ISSUE THREAD

**Issue by StarpTech** [Microsoft/TypeScript#27605]
**Expected behavior:**
Should throw an error: `Type '{ name: string; weight: number; }' is not assignable to type 'Dog'.`

**Actual behavior:**
No error is thrown until the type `Dog` is explicitly set.

**Playground Link:**

http://www.typescriptlang.org/play/#src=interface%20Dog%20%7B%0A%20%20name%3A%20string%3B%0A%7D%0A%0Afunction%20x()%3A%20Dog%5B%5D%20%7B%0A%0A%20%20var%20a%20%3D%20%7B%0A%20%20%20%20name%3A%20%22%22%0A%20%20%7D%3B%20%0A%0A%20%20var%20b%20%3D%20%7B%0A%20%20%20%20name%3A%20%22asd%22%2C%0A%20%20%20%20weight%3A%2022%0A%20%20%7D%0A%0A%20%20%2F%2F%20This%20works%20!%0A%20%20%2F%2Fvar%20b%3A%20Dog%20%3D%20%7B%0A%20%20%2F%2F%20%20name%3A%20%22asd%22%2C%0A%20%20%2F%2F%20%20weight%3A%2022%0A%20%20%2F%2F%7D%0A%0A%0A%20%20return%20%5Ba%2C%20b%5D%3B%0A%7D

**Comment by StarpTech** [comment]
@j-oliveras thanks for the pointer.

**Comment by StarpTech** [comment]
@j-oliveras but this strengthens my argument because 

> ... But in a structural type system, the fact that these types have different names is immaterial. Because they have the same members with the same types, they are identical.

Why typescript doesn't check that both `[a, b]` has the type `Dog` ?

**Comment by Hoishin** [comment]
having extra properties does not invalidate the value as far as I know

**Comment by StarpTech** [comment]
That's not true. Check it by yourself and add the type `Dog` explicit to variable `b`. In order to work with optional members you have to declare them as such `?`.

**Comment by StarpTech** [comment]
@jack-williams this answered my question thanks!

**Comment by StarpTech** [comment]
@jack-williams but it's weird that this code will throw

http://www.typescriptlang.org/play/#src=interface%20Dog%20%7B%0A%20%20name%3A%20string%3B%0A%7D%0A%0Afunction%20x()%3A%20Dog%5B%5D%20%7B%0A%0A%20%20var%20a%20%3D%20%7B%0A%20%20%20%20name%3A%20%22%22%0A%20%20%7D%3B%20%0A%0A%20%20var%20b%20%3D%20%7B%0A%20%20%20%20name%3A%20%22asd%22%2C%0A%20%20%20%20weight%3A%2022%0A%20%20%7D%0A%0A%20%20%2F%2F%20This%20won't%20work%20!%0A%20%20%2F%2Fvar%20b%20%3D%20%7B%0A%20%20%2F%2F%20%20name%3A%20%22asd%22%2C%0A%20%20%2F%2F%20%20weight%3A%2022%0A%20%20%2F%2F%7D%0A%0A%0A%20%20return%20%5Ba%2C%20%20%7B%0A%20%20%20%20name%3A%20%22asd%22%2C%0A%20%20%20%20weight%3A%2022%0A%20%20%7D%20%2F*b*%2F%5D%3B%0A%7D

**Comment by jack-williams** [comment]
@StarpTech 

It's the same behavior: excess property checking. When checking a fresh object literal against a type excess properties are flagged, this applies even if the literal is inside an array.

One you assign the literal to an identifier the 'fresh literal' status is lost, which is why uncommented code does not raise an error.

**Comment by StarpTech** [comment]
Thanks for clarifiying.
