### ISSUE TITLE
Code with union of types is not compiled by TSC 3.1.1

### ISSUE THREAD

**Issue by gsbelarus** [Microsoft/TypeScript#27611]
The following code is not compiled by TSC 3.1.1 throwing error: _Property 'address' does not exist on type 'string | AddressInfo'. Property 'address' does not exist on type 'string'._

```
    httpServer.on("listening", () => {
      console.log(
        `Listening on http://${httpServer!.address().address}` +
        ` env: ${process.env.NODE_ENV}`);
    });
```

corresponding method declared inside Server class as:

```
    class Server extends events.EventEmitter {
        ...
        address(): AddressInfo | string;
```

and **AddressInfo** has field with name **address**:

```
    interface AddressInfo {
        address: string;
        family: string;
        port: number;
    }
```

The code was compiled by previous versions of TS without any errors.

**Comment by andy-ms** [comment]
If the value is `AddressInfo | string`, it's possibly a string. `string` doesn't have an `address` property, so the code can possibly try to access a nonexistent property, printing "Listening on http://undefined". It sounds like TypeScript is doing the right thing and probably worked the same in previous versions -- maybe the httpServer library you're using changed?

**Comment by gsbelarus** [comment]
Ok. Will close.
