### ISSUE TITLE
Property 'onselectionstart' does not exist on type 'HTMLDivElement'

### ISSUE THREAD

**Issue by asmundg** [Microsoft/TypeScript#27618]
**TypeScript Version:**  3.2.0-dev.20181006

**Search Terms:** onselectionstart, selection

**Code**

```ts
// Property 'onselectionstart' does not exist on type 'HTMLDivElement'.
window.document.createElement("div").onselectionstart
```

**Expected behavior:**

Code compiles.

**Actual behavior:**

Typescript fails with error TS2339: Property 'onselectionstart' does not exist on type 'HTMLDivElement'.

This was removed in ee25cdecbc. onselectionstart is part of the experimental Selection API. Is it intentionally unsupported?

**Playground Link:** http://www.typescriptlang.org/play/#src=window.document.createElement(%22div%22).onselectionstart

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
Experimental DOM APIs are intentionally not included in the built-in lib definition

**Comment by asmundg** [comment]
Ok, thanks for the clarification!
