### ISSUE TITLE
Suggestion: TypeScript without setting up a build pipeline (for seamless use in existing JavaScript projects)

### ISSUE THREAD

**Issue by johot** [microsoft/TypeScript#27613]
## Search Terms

typescript without compiling

## Suggestion

This may sound like a crazy idea, but anyways, I think it would be so cool if we could use TypeScript without compiling it using a webpack setup etc. I love TypeScript but the major friction is when getting to a new project that uses for example js and jsx (React). When that happens you start googling for instructions on setting up webpack/tsc or finding a boilerplate for the specific scenario.

 It would be so cool if I could to this:

* Instead of writing a new `.js` or `.jsx` file I could simply create a new `.ts` or `.tsx` file. I can still have `.js` and `.jsx` file around where I see fit (this may for example be an existing/legacy application).
* Now of course something will need to convert these `.ts` or `.tsx` files to `.js/.jsx`, my suggestion would be that an editor such as VS Code would have this built in. Whenever I save my TypeScript files a corresponding compiled `.js/.jsx` file is created (using ES6 for example). 
* The editor (in this case VS Code) would be able to hide the compiled `.js/.jsx` files to give the impression only the TypeScript version exists.

If this was working I could take any existing Babel project and just add `.ts/.tsx` files. These gets compiled "under the hood" and Babel for example would just act like always.

This would make it really really easy to use TypeScript everywhere without setting up the build pipeline for it. The downside would be that it would require the use of a special editor such as VS Code for working with TypeScript but I think that is almost a defacto standard soon when it comes to working with TypeScript.

## Use Cases

* Use TypeScript in existing javascript projects without friction.

## Examples

* I create a new `.ts/.tsx` file. In the background VSCode will generate an ES6 `.js/.jsx` equivalent and hide it in the editor to give the impression only the TypeScript version exists.

Hopefully Babel (or similair) will not see the TypeScript file and just work like regular.

## Checklist

My suggestion meets these guidelines:
* [X] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by RyanCavanaugh** [comment]
You're describing the existing `compileOnSave` feature?

**Comment by johot** [comment]
@RyanCavanaugh 
> You're describing the existing `compileOnSave` feature?

Thanks for your answer Ryan!
Hmm, that seems to be something Visual Studio (not code) picks up right?

I can actually simulate what I want by doing the following
* Create a new React app using `create-react-app` (non TypeScript version)
* I add a new `tsconfig` to the project and set the output dir to `./src` (also enable jsx, use ES2015 for target and module)
* I start tsc using `tsc --watch`
* I do an `npm start`

Now when creating a `.ts/.tsx` file a corresponding `.js/.jsx` file will be created in the same location.

I just wish that I could make all this work with no or very little setup. I guess to get what I want the steps above would have to be incorporated seamlessly into VS Code, and I totally understand that it's not the responsibility of the TypeScript team :)

I was just checking to see if this was anything you have been thinking of. It seems the `compileOnSave` is not something VS Code (for example) picks up right?

Also I would love for the compiled js files to be hidden (also an IDE issue ofc).

**Comment by RyanCavanaugh** [comment]
> Hmm, that seems to be something Visual Studio (not code) picks up right?

> Also again it seems the compileOnSave is not something VS Code (for example) picks up right?

No; this is supported by VS Code as well.

**Comment by johot** [comment]
> > Hmm, that seems to be something Visual Studio (not code) picks up right?
> 
> > Also again it seems the compileOnSave is not something VS Code (for example) picks up right?
> 
> No; this is supported by VS Code as well.

Hmm... tried this but nothing happens, using VSCode 1.28.0.

* Added `tsconfig.json`
```
{
  "exclude": ["node_modules", "**/*.spec.ts"],
  "compileOnSave": true,
  "compilerOptions": {
    "target": "es2015" /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', or 'ESNEXT'. */,
    "module": "es2015" /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', or 'ESNext'. */,
    "jsx": "react" /* Specify JSX code generation: 'preserve', 'react-native', or 'react'. */,
    "outDir": "./src" /* Redirect output structure to the directory. */,
    "strict": true /* Enable all strict type-checking options. */,
    "noImplicitAny": false /* Raise error on expressions and declarations with an implied 'any' type. */
  }
}
```
* Changed my `.tsx` file. Nothing happens. 

What is the expected output? This only works when using `tsc --watch` but in that case it would work even without `compileOnSave`.

Thanks!
