### ISSUE TITLE
Spec incorrectly specify grammar in section 4.17.1

### ISSUE THREAD

**Issue by yuit** [Microsoft/TypeScript#2762]
In section [4.17.1] (https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#4.17), 

AssignmentPattern:
   ObjectAssignmentPattern
   ArrayAssignmentPattern

  ObjectBindingPattern: // This should be ObjectAssignmentPattern
      ...

**Comment by ahejlsberg** [comment]
The spec is being revised to use the ECMAScript 6 grammar as a base, so this particular issue is no longer relevant.
