### ISSUE TITLE
`declare namespace` exported without `export`

### ISSUE THREAD

**Issue by evmar** [microsoft/TypeScript#27620]
**TypeScript Version:**  3.2.0-dev.20181006 and older versions

**Search Terms:** namespace d.ts import

**Code**

```ts
// foo.d.ts
export let x: number;
declare namespace Foo { type T = string; }
```

```ts
// user.ts
import {x, Foo} from './foo';
```

**Expected behavior:**
`Foo` cannot be imported, because it is not exported.

For example, does this mean it's impossible(?) to have an unexported namespace in a d.ts?

**Actual behavior:**
If the first file is `.d.ts`, import succeeds.  If the first file is `.ts`, import fails in the expected way.

**Comment by RyanCavanaugh** [comment]
The syntax for an unexported member in a .d.ts file is:
```

```

**Comment by mattmccutchen** [comment]
Blank code block??

How about:
```ts
export let x: number;
declare namespace Foo { type T = string; }
export {};
```
See [this thread](https://stackoverflow.com/q/52583603) for more information.
