### ISSUE TITLE
await keyword not included in suggestions

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#27622]
From https://github.com/Microsoft/vscode/issues/60133

**TypeScript Version:**  typescript@3.2.0-dev.20181006

**Search Terms:**
- await
- suggestion, completions

**Code**
In a js or ts file, trigger intellisense at the `|`

```ts
awa|
```

**Expected behavior:**
Entry for the `await` keyword returned.

**Actual behavior:**
No suggestion for this keyword included in suggestion results

**Playground Link:** 

**Related Issues:**

**Comment by andy-ms** [comment]
@HrushikeshBodas 

First, the tests go in `tests/cases/fourslash`. See `completionsTypeKeywords.ts` for an example.
Then you should be able to debug using a command like `gulp runtests-browser --t completionsTypeKeywords` (substitute with the name of your new test).

Completions are handled in `completions.ts`. You can probably put a breakpoint in `getKeywordCompletions` and work from there.

**Comment by vibhor1997a** [comment]
The await suggestion is still not working as of TS version `3.1.4`. It works in older versions like `3.0.1`.

**Comment by andy-ms** [comment]
@vibhor1997a It's not in `3.1.4` but should be in `typescript@next`.

**Comment by Cow258** [comment]
The await suggestion is still not working as of `typescript@3.2.1`.  
Tested on VsCode - Insiders 1.30.0-insider.
