### ISSUE TITLE
docCommentTemplate returns "No content available" for ES5 method

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#27638]
From https://github.com/Microsoft/vscode/issues/60335

**TypeScript Version:**  3.2.0-dev.20181006

**Search Terms:**
- jsdoc
- docCommentTemplate

**Code**
For the javascript:
```ks
/** */
MyClass.prototype.myFunction = function (param1, param2) {
};
```

Request a `docCommentTemplate` at the `|` in `/**| */`

**Bug:**
No content available returned.

```
[Trace  - 11:44:31 AM] Sending request: docCommentTemplate (13). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/Users/matb/projects/san/b.js",
    "line": 1,
    "offset": 4
}
[Trace  - 11:44:31 AM] Response received: docCommentTemplate (13). Request took 2 ms. Success: false . Message: No content available.
```

This is a regression from TS 3.0.

We do return the expected response for the case:

```js
/** */
function  foo(param1, param2) {
};
```

**Comment by sandersn** [comment]
This works in 3.5. Adding a test with #31477 to make sure it stays working.
