### ISSUE TITLE
narrowing to null via typeguards doesn't work

### ISSUE THREAD

**Issue by zpdDG4gta8XKpMCd** [microsoft/TypeScript#27634]
i am hacking my way around this limitation #11920

so my goal is to make sure that `isNull` only applied to `T | null` types and by this i mean *that `null` *must be a valid case* of a given type* (types that don't have `| null` must not be permitted), i am trying to use conditional types to enforce it, this is what i got

unfortunately it doesn't work and i am clueless what i am doing wrong, it looks like a bug

```ts
export function isNull<T extends (null extends T ? any : never)>(value: T | null): value is null {
    return value === null;
}

declare var x: null | number;
if (isNull(x)) { // <-- expect to work, actual: number is not assignable to null
}
declare var y: number;
if (isNull(y)) { // <-- expect a type error
}
```

@ahejlsberg you might want to look at it

**Comment by aleksey-bykov** [comment]
hacking my way around this limitation #11920

**Comment by aleksey-bykov** [comment]
@ahejlsberg strange behavior in narrowing to null, you might want to look at it

**Comment by RyanCavanaugh** [comment]
You'd need #9252 to do this

**Comment by aleksey-bykov** [comment]
jfc, no country for an old men

**Comment by jack-williams** [comment]
Maybe?
```ts
export function isNull<T extends (null extends T ? any : never)>(value: T): value is Extract<T,null> {
    return value === null;
}
```

**Comment by aleksey-bykov** [comment]
`Extract<T, null>` is sure a very interesting way of saying `null`, but it seems to work, thanks

**Comment by ahejlsberg** [comment]
I was going to suggest this:

```ts
export function isNull<T extends (null extends T ? any : never)>(value: T): value is T & null {
    return value === null;
}
```

But `Extract<T, null>` seems to work too.

**Comment by aleksey-bykov** [comment]
@ahejlsberg your way (`value is T & null`) works better since `Except<T, null>` only works unions of promitives, but doesn't work on unions of objects, thank you for your help

**Comment by jack-williams** [comment]
@aleksey-bykov Can you post an example of one that doesn't work?

**Comment by aleksey-bykov** [comment]
@jack-williams hm, i guess i am taking my words back, now it looks working just as well

not sure what happened, but when i applied it first time i didn't get narrowing that i expected

if i see it again i will let you know

**Comment by aleksey-bykov** [comment]
broken now: #29662
