### ISSUE TITLE
Overhead code generation for `outFile`

### ISSUE THREAD

**Issue by pankleks** [Microsoft/TypeScript#27679]
I'm compiling my project to single output file using `outFile` option.

TSC is generating overhead code as such:
![image](https://user-images.githubusercontent.com/14176066/46717745-45d4b380-cc69-11e8-92e7-30fd12ac1345.png)

This happens for every file of my solution -> in my case hundreds of  small files which cause significant overhead in output file.

I believe this could be optimized by merging objects in same namespace.

Test solution:
[testmerge.zip](https://github.com/Microsoft/TypeScript/files/2463440/testmerge.zip)

TSC v: 3.1.1 but I believe it was like this since very beginning.

**Comment by RyanCavanaugh** [comment]
Duplicate #447
