### ISSUE TITLE
TS Server stalls during npm install

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#27673]
From https://github.com/Microsoft/vscode/issues/59898

**TypeScript Version:**  3.2.0-dev.20181009

**Search Terms:**
- TS server
- file watcher
- npm install

**Code**
1. For a simple js project:

`package.json`

```json
{
    "dependencies": {
        "express": "4.16.3",
        "lodash": "^4.17.11",
        "react": "^16.5.2",
        "react-native": "^0.57.2",
        "typescript": "^3.2.0-dev.20181009",
        "underscore": "^1.9.1",
        "webpack": "^4.20.2"
    }
}

```

`index.js`

```js
import * as express from "express"
 
let a = express()
```

1. Open the js file
1. Then run `npm install`
1. While install is still happening, repeatedly try triggering intellisense in the js file

**Expected behavior:**
IntellisSense remains responsive

**Actual behavior:**
After some stage of the install the tsserver seems to stall and will not respond to requests. This lasts for a minute or more after the install completes

**Comment by mjbvz** [comment]
TS Server log:  [tsserver log.zip](https://github.com/Microsoft/TypeScript/files/2462619/tsserver.log.zip)

**Comment by sheetalkamat** [comment]
@mjbvz can you try drop from #28209 to see if it helps. I couldn't repro this on windows.

**Comment by mjbvz** [comment]
Yes it seems to help significantly. Here's the updated log: [tsserver.log](https://github.com/Microsoft/TypeScript/files/2527457/tsserver.log)

Only noticed one short delay of about half a second while requesting completions during  `npm install`

**Comment by sheetalkamat** [comment]
@mjbvz the tsconfig in the latest server log doesn't have exclude of node_modules and hence that's the one getting invoked a lot.

**Comment by sheetalkamat** [comment]
I think because you didn't have include it just watched tsconfig directory. I updated the PR with fix for wild card watches as well.
