### ISSUE TITLE
Type parameter constrained to number is not assignable to number

### ISSUE THREAD

**Issue by JsonFreeman** [Microsoft/TypeScript#2767]
```ts
enum E { x }
function enumThing<T extends number>() {
    var t: T;
    var num: number = t; // Should work
    var enumMember: E = t; // Should not work
}
```

Right now both of these are an error. But the number one should work because T is constrained to a number. This is useful because it means T can be a number or any enum type.

The spec and implementation would both need to be updated to allow this.

**Comment by mhegazy** [comment]
Pinging @ahejlsberg for this one.

**Comment by RyanCavanaugh** [comment]
Dupe #2694?

**Comment by mhegazy** [comment]
:) yes.
