### ISSUE TITLE
`jake local` to build entire TypeScript codebase using LKG?

### ISSUE THREAD

**Issue by mattmccutchen** [Microsoft/TypeScript#27676]
## Search Terms

LKG build bootstrap

I'm having a hard time finding search terms that give me a reasonable number of issues to review. :(

## Suggestion

`jake local` should build the entire TypeScript codebase using the LKG compiler, instead of using the LKG compiler for the first stage of the build and the newly built compiler for the second stage.  If it's important to be able to test the new compiler's ability to compile the whole codebase without first copying the new compiler to the LKG, there should be a separate jake target for that.

## Use Cases

When I'm working on a risky change to the compiler, currently I have to get the compiler working well enough to complete the second stage of `jake local` before I'm able to run the language service or the test suite.  Sometimes it's difficult to diagnose failures to compile such a complex real-world codebase.  If I could run the test suite, the same root cause might produce a failure on a much smaller test case that would be much easier to diagnose.  If I could run the language service in VS Code, I would get a much more rapid cycle for testing error reporting and type simplification on small examples than having to run the compiler at the command line.

## Examples

N/A?

## Checklist

My suggestion meets these guidelines:
* [X] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by RyanCavanaugh** [comment]
We absolutely agree and have been meaning to do this for a while. Using one tool for the whole build will also improve overall build times which is something we'd very much like.

**Comment by mattmccutchen** [comment]
I'd like to help, but I just think it won't be worthwhile for me to try to learn how the build works now, let alone how you envision it to work.  I'll leave this one to you and continue working on the issues I know something about.

**Comment by mattmccutchen** [comment]
@rbuckton Am I correct in thinking this was done in 056028b?  If so, I'll close the issue.

**Comment by RyanCavanaugh** [comment]
Yep, this is done now
