### ISSUE TITLE
 Cannot destructure property `error` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by housseincherkawi** [Microsoft/TypeScript#27681]
app.put('/api/upCourses/:id', (req, res) =>{
   // look up the course
   //if not existing , return 404
    const course = courses.find(c => c.id ===  parseInt(req.params.id));
    if(!course) res.status(404).send('The course not Found');
    res.send(course);

    const { error } = validateCourse(req.body); // result.error
    if(error){
        res.status(400).send(result .error.details[0].message);
        return;
    }
   //update course
     course.name=req.body.name;
   //return the update course
     res.send(course);
});
function validateCourse(course){
    //validate
    //if invalid, return 400 -bad request
    const schema = {
        name: Joi.string().min(3).required()
    };
    Joi.validate(course, schema);
}

**Comment by andy-ms** [comment]
Please provide a complete reproducible example of the problem.

**Comment by madhavthatavarthi** [comment]
You should add a return before Joi.validate(). It will work

**Comment by natnael-bedru** [comment]
replace "Joi.validate(course, schema);" with "return schema.validate(course)"
