### ISSUE TITLE
Wrong zh-tw translation for "Move to new file"

### ISSUE THREAD

**Issue by doggy8088** [Microsoft/TypeScript#27682]
There are issues [here](https://github.com/Microsoft/vscode/issues/60272) and [here](https://github.com/Microsoft/Localization/issues/29).  I finally realized there is a translation error exists in TypeScript project.  

https://github.com/Microsoft/TypeScript/blob/07966dcb124ee379a4f062c1032fec0a6c4eaf19/lib/zh-tw/diagnosticMessages.generated.json#L587

The term **Move to new file** in **zh-tw** should translate to **移至新檔**.

**Comment by RyanCavanaugh** [comment]
@lukaschal can we take PRs for the lcl files or do those get overwritten on insertions?

**Comment by DanielRosenwasser** [comment]
CC @PDostalek

**Comment by lukaschal** [comment]
On review.

File: bin\Release\localize\ENU\diagnosticMessages.generated.json
ID: 0; "Move_to_a_new_file_95049"
SRC: Move to a new file
TGT: 移至新行

**Comment by doggy8088** [comment]
Is it possible accept PR for translation?

**Comment by lukaschal** [comment]
Fixed as suggested.

File: bin\Release\localize\ENU\diagnosticMessages.generated.json
RID: 0; "Move_to_a_new_file_95049"
SRC: Move to a new file
New TGT: 移至新檔
