### ISSUE TITLE
Rename should ignore SemanticMeaning

### ISSUE THREAD

**Issue by andy-ms** [microsoft/TypeScript#27699]
**TypeScript Version:**  3.2.0-dev.20181010

**Code**

```ts
function f() {}
namespace f {}
```

**Expected behavior:**

Renaming `f` in `function f()` should rename the namespace too.

**Actual behavior:**

Only renames the function.

**Comment by DanielRosenwasser** [comment]
I feel like we should have both options available; thoughts @mjbvz @amcasey?

**Comment by amcasey** [comment]
I think C# would consider that a cascading rename and I believe cascading renames are governed by a checkbox (but that may have been phased out).

**Comment by mjbvz** [comment]
Are there cases where this may cause unexpected behavior, such if your class or function name collides with some namespace in an external library?

In either case, it would be nice if VS Code showed a preview of the locations that would be renamed so that users know what to expect

**Comment by RyanCavanaugh** [comment]
Not entirely obvious that this is true and we haven't gotten other feedback on it. Closing as "works well enough"
