### ISSUE TITLE
Method reference : Enhancement or new feature

### ISSUE THREAD

**Issue by Kavignon** [microsoft/TypeScript#2769]
Java just started to support lambdas in its language, with this new feature, they brought into play some syntax sugar coating to make code more concise. I thought it look pretty neat and wanted to know if that could be an enhancement of the language.

So, for those who might not know what method reference actually is, I'm going to give a definition for this and then show you an example of how it is used. 
Method reference : shortcuts that you can use anywhere you would use a lambda.
Oracle defines 4 types of method references

Reference to a static method     (ContainingClass::staticMethodName)
Reference to an instance method of a particular object (ContainingObject::instanceMethodName)
Reference to an instance method of an arbitrary object of a particular type  ContainingType::methodName
Reference to a constructor (ClassName::new)

As an example,
Here's the first version in Java (Lambda)
list.sort(comparing( (Apple a) -> a.getWeight() ));
Now here's the version using method reference
list.sort(comparing(Apple::getWeight));

It just makes code a bit shorter when using lambda. I'm well aware that Typescript has delegates and that it could be encapsulated (lambdas) within a delegate. I stumble upon that Java 8 feature and thought that a similar feature would be quite nice.

I'd like to start a discussion on this topic.

**Comment by DanielRosenwasser** [comment]
I'm a little confused - apart from `this

**Comment by DanielRosenwasser** [comment]
>  I'm well aware that Typescript has delegates

What do you mean by "delegates" exactly?

I think what you really want is to do is capture `this` properly when you use a method.

For instance,

```TypeScript
class Apple {
    constructor(private weight: number) {
    }

    public getWeight() {
        return this.weight;
    }
}
```

So currently, if you have:

```TypeScript
```

**Comment by Kavignon** [comment]
oh I see. Then I actually have some more reading to do on Typescript
because I completely over seen that.

**Comment by DanielRosenwasser** [comment]
Sorry @Kavignon, I hadn't finished that response and but accidentally posted (and deleted) it. I realized what you meant in the middle of responding though, which is decidedly different from what I had understood.

**Comment by Kavignon** [comment]
Based on what you understood, would you say that the topic I've raised is good enough to be discussed as a possible feature for either 1,6 or 2.0? @DanielRosenwasser

**Comment by DanielRosenwasser** [comment]
Before I could comment on something like that, we'd need [a formal proposal](https://github.com/Microsoft/TypeScript/wiki/Writing-Good-Design-Proposals). One thing I'll mentions is that we tend to be conservative on new syntax to avoid conflicting with future versions of ECMAScript. 

An issue worth raising is whether this has a use-case outside of instance methods.

**Comment by xenoterracide** [comment]
actually almost all examples given are static methods normal way to reference an instance method in java is `this::methodName` (unless your reference isn't this ). Seems like they would be very useful in chaining with promises

```
        this.container.registerTransient( publicKey, () => {
            return this.client.fetch( '' )
                .then( ResponseHelper::toJson )
                .then( RepsonseHelper::toHal )
                .then( RepsonseHelper::toLinks )
                .then( links => links["public"]);
        });
``

**Comment by jan-swiecki** [comment]
+1

**Comment by Kavignon** [comment]
Kevin would like to stay in touch on LinkedIn.

Kevin Avignon
Senior Software Engineer Student 
Montreal, Canada Area

View profile https://www.linkedin.com/e/v2?e=0-ivzc5ec9-qv&a=publicProfile&tracking=eml-guest-invite-pprofile-link-cta&ek=invite_guest&vanityName=kevinavignon

Confirm that you know Kevin https://www.linkedin.com/comm/start/accept-invitation?sharedKey=60VMl3Ti&invitationId=6208290943456604162&trk=eml-guest-invite-cta&trkEmail=eml-invite_guest-null-112-null-null-0%7Eivzc5ec9%7Eqv


.....................................

Unsubscribe: https://www.linkedin.com/e/v2?e=0-ivzc5ec9-qv&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&li=119&m=unsub&ts=unsub&loid=AQG3dfHY5yK62QAAAVihH0J8poHUkq05iG1w_XYiFbBp_RHpKPPbJ5x1ZBIkFoqrjuwQapMppn8DEdN95thXFgGPhz5i-H_GTh27g3pX5p4DXqVNWqy65VJv4AU_QKFI5Y9hDkmVaILfWoLEyEmKEA7NC6xNASVuREVywIN5VJZqjRGdaqqUY2N6sGn8Kr94TowHicx2FZnver3Wuo_fAfnHmg&eid=0-ivzc5ec9-qv

Help: https://www.linkedin.com/e/v2?e=0-ivzc5ec9-qv&a=customerServiceUrl&ek=invite_guest&li=118&m=footer&ts=help&articleId=67


You are receiving Invitation emails. LinkedIn will use your email address to make suggestions to our members in features like People You May Know.

This email was sent to reply@reply.github.com.

© 2016 LinkedIn Ireland Unlimited Company, Wilton Plaza, Wilton Place, Dublin 2. LinkedIn is a registered business name of LinkedIn Ireland Unlimited Company. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by karlthepagan** [comment]
A related feature #3508 might eventually supersede this issue.

(I came here searching for method references and dug down for the related ecmascript proposals)

**Comment by Kavignon** [comment]
Kevin Avignon would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=60VMl3Ti&invitationId=6208290943456604162&trk=eml-first_guest_reminder_01-hero-121-accept_text&trkEmail=eml-first_guest_reminder_01-hero-121-accept_text-null-%7Eh4t84k%7Eiw6msi7c%7Emf

View Kevin Avignon&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=60VMl3Ti&invitationId=6208290943456604162&trk=eml-first_guest_reminder_01-hero-3-profile_text&trkEmail=eml-first_guest_reminder_01-hero-3-profile_text-null-%7Eh4t84k%7Eiw6msi7c%7Emf





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-h4t84k-iw6msi7c-mf&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=123&m=unsub&ts=HTML&eid=-h4t84k-iw6msi7c-mf&loid=AQHIqosvqxctiQAAAVi8PRGsi7YiEnxh1tLVWU2y2e9lIPPl65pCAUZlohi6ODiIs35SP9iKRA9EuEeCwNSsRfHjK7g_ep6QG1eEcWCXXC0AaMBYL8u1a4INaPOg7lYgRmvjym8AZwVPe_mQF6J-a6Zy9m0P48JP1JWx9eOO24qKg0XOzsEYSdN61q1pYgk1OOqYuyvKxVT76_ceC4OmZ2uLDM9vIw

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-h4t84k-iw6msi7c-mf&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by simonfxr** [comment]
+1
