### ISSUE TITLE
Adding a keyword 'self' and class property prefix (work together)

### ISSUE THREAD

**Issue by dooxe** [Microsoft/TypeScript#27692]
Hello, 

I have been practicing typescript for some months, and I have a couple of suggestions that I believe would be very great. Let me explain what and why.

## Search Terms

* self
* this
* member
* property
* attribute

## Suggestions

1. A keyword `self`
First suggestion is to create a new keyword, let's say `self`. While the value of `this` is not the same depending on the context from which it is used, `self` would always point to the current class instance.
This key word would be very easy to translate in JS: define `var self = this;` at the beginning of each function. 

2. Class property prefix
In some programming languages (Ruby and Objective-C for instance), class properties are prefixed with a symbol (respectively `@` and `_`). My suggestion is to introduce the same kind of prefix to typescript class properties.
The main advantage is to not write `this.` every time one wants to change a property value. The second advantage, if we couple this suggestion to (1) is that we could use class members as is inside anonymous function and so one.

## Use Cases

1. This suggestion would help to differentiate class logic from anonymous functions logic, allowing the code to be more clear. The main drawback of keyword `this` is that its meaning changed with the context, wich would not be the case with `self`.

2. I would use suggestion (2) to make my code even more clear by differentiating class properties changes from local changes.

## Examples

Here is some code using both suggestions I propose. Please see comments inside the code.
```ts
class MyClass {

    //
    private _value  : number;

    //
    constructor(model:MySecondClass){
        // Suggestion (1)
        // var self = this;
        model.on('event', function(n:number):void {     
            self.doSomething(); 
            // Suggestion (2) + (1)      
            // self._value = n;
            _value = n;
        });
    }

    //
    private doSomething():void {
        
    }
}
```
## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
Because it does not change the behaviour of `this`.

* [x] This wouldn't change the runtime behavior of existing JavaScript code

* [x] This could be implemented without emitting different JS based on the types of the expressions
The features I propose does not care about the type of the expressions.

* [X] This isn't a runtime feature (e.g. new expression-level syntax)
... I think so ?

I hope everything is clear ! Let me know what you think about this ;)

**Comment by RyanCavanaugh** [comment]
> This wouldn't be a breaking change in existing TypeScript / JavaScript code

`self` and `_value` are legal identifiers with existing meaning in JavaScript; this proposal would absolutely break existing JS code. It's also a new runtime feature because you have to make `self` appear in places where it currently doesn't (the emit of which turns out to be impossible).
