### ISSUE TITLE
"Conflicting Modifications Detected" error

### ISSUE THREAD

**Issue by stijnherreman** [Microsoft/TypeScript#277]
Original issue: http://typescript.codeplex.com/workitem/1829

> The file Foo.js.map has changed since you opened it. Would you like to save the version you have open over the changes on disk?
> 
> The file Foo.js has changed since you opened it. Would you like to save the version you have open over the changes on disk?

Steps to reproduce:

1. Modify Foo.ts and save it.
2. Save Foo.ts again (with or without modifying it), you will get the errors. 

Demo: http://www.youtube.com/watch?v=3YCQsWtQXro

 - Process Monitor revealed that no other processes are touching the files.
 - All extensions that could be disabled had been disabled, these were still enabled:
    - Microsoft Web Developer Tools 1.2.40308.0
    - NuGet Package Manager 2.7.40911.225
    - Visual Studio Extensions for Windows Library for JavaScript 1.0.9200.20789
 - We have 3 nearly identical hardware setups in our team, problem later appeared on a second system, but never on the third system.

There's a whole bunch of additional information from myself and other users in the original ticket on CodePlex. It's already clear that this affects multiple users and not some odd configuration issue on my part.

I've asked for this multiple times and I'll ask again: is it possible to provide a debug build of the module that generates this error? That could be very helpful in determining the cause of this issue.

Note: I will probably only work for a few more months on my current project, after that I will no longer be able to supply additional information on this issue, unless it appears on a system at my next project.

**Comment by billti** [comment]
Fixing this is non-trivial, and the bug has been around for over a year and a half now without much noise (nobody commented on it for all of 2015). Closing as won't fix. Will revisit if there is some persuasive reason to.

**Comment by SynBiotik** [comment]
I'm using Visual Studio 2015 and  I get the same error. For source control I am using Surround SCM and the corresponding VS plugin.

**Comment by mschlechter** [comment]
Oh crap. Another reason to stop using SourceSafe I guess.

**Comment by mdallau** [comment]
Is the reason, you're using software of more than 10 years old to protect your new sources enough? ;-P
