### ISSUE TITLE
Inferred type does not work for generic reduce function with when not used as a lambda

### ISSUE THREAD

**Issue by Roaders** [Microsoft/TypeScript#27708]
**TypeScript Version:**  3.1

**Search Terms:** type inferrence 

**Code**

```ts
function reduceToPromise<T extends string>(promise: Promise<T>, items: string[]){
    return promise
}

const initialPromise: Promise<string> = {} as any;
const items: string[][] = [];

const reducedOne = items.reduce(reduceToPromise, initialPromise);
const reducedTwo = items.reduce((promise, items) => reduceToPromise(promise, items), initialPromise);
```
[Playground](http://www.typescriptlang.org/play/#src=%0D%0A%0D%0Afunction%20reduceToPromise%3CT%20extends%20string%3E(promise%3A%20Promise%3CT%3E%2C%20items%3A%20string%5B%5D)%7B%0D%0A%20%20%20%20return%20promise%0D%0A%7D%0D%0A%0D%0Aconst%20initialPromise%3A%20Promise%3Cstring%3E%20%3D%20%7B%7D%20as%20any%3B%0D%0A%0D%0Aconst%20items%3A%20string%5B%5D%5B%5D%20%3D%20%5B%5D%3B%0D%0A%0D%0Aconst%20reducedOne%20%3D%20items.reduce(reduceToPromise%2C%20initialPromise)%3B%0D%0A%0D%0Aconst%20reducedTwo%20%3D%20items.reduce((promise%2C%20items)%20%3D%3E%20reduceToPromise(promise%2C%20items)%2C%20initialPromise)%3B%0D%0A)

**Expected behavior:**
Both `reducedOne` and `reducedTwo` should be typed as `Promise<string>`

**Actual behavior:**
`reducedOne` is typed as `{}`

This issue only occurs when the function has a generic type. This works fine:
```ts
function reduceToPromise(promise: Promise<string>, items: string[]){
    return promise
}

const initialPromise: Promise<string> = {} as any;
const items: string[][] = [];

const reduced = items.reduce(reduceToPromise, initialPromise);
```
[Playground](http://www.typescriptlang.org/play/#src=%0D%0A%0D%0Afunction%20reduceToPromise(promise%3A%20Promise%3Cstring%3E%2C%20items%3A%20string%5B%5D)%7B%0D%0A%20%20%20%20return%20promise%0D%0A%7D%0D%0A%0D%0Aconst%20initialPromise%3A%20Promise%3Cstring%3E%20%3D%20%7B%7D%20as%20any%3B%0D%0Aconst%20items%3A%20string%5B%5D%5B%5D%20%3D%20%5B%5D%3B%0D%0A%0D%0Aconst%20reduced%20%3D%20items.reduce(reduceToPromise%2C%20initialPromise)%3B%0D%0A)

**Comment by andy-ms** [comment]
Simplified example:
```ts
function id<T>(x: T): T { return x; }
function callIt<T, U>(f: (t: T) => U, x: T): U { return f(x); }
const x = callIt(id, 0); // Infers `callIt<{}, {}>` so `x` is `{}`. No error if order of parameters is reversed.
```

**Comment by weswigham** [comment]
I think in the past we've called this a design limitation and told people to invert their parameter order; but because of what we've been looking at recently w.r.t. proper unification, I'll mark this as a bug instead and ping @ahejlsberg for input. You think this is worth reconsidering?

**Comment by DanielRosenwasser** [comment]
Closing in favor of #9366.
