### ISSUE TITLE
tsc -w won't recompile when add new files.

### ISSUE THREAD

**Issue by taoqf** [microsoft/TypeScript#27702]
**TypeScript Version:**  3.2.0-dev.20181010

**Search Terms:**

**Expected behavior:** recompile after new files added.

**Actual behavior:** could not recompile except re-save tsconfig.json

**Playground Link:** 

**Related Issues:** https://github.com/Microsoft/TypeScript/issues/26524 https://github.com/Microsoft/TypeScript/issues/26168

**Comment by sheetalkamat** [comment]
Please provide repro so we can analyze this.

**Comment by taoqf** [comment]
I have done some tests and find the reason.
I set `include ` in `tsconfig.json`, then if I add a file 'src/test/test.ts`, it could not recompile.

```json
"include": [
		"./src/"
],
```

but if i change the config

```json
"include": [
		"./src/**/*"
],
```

it works fine.
I don't know if this is designed.

**Comment by taoqf** [comment]
@sheetalkamat Is this fixed?
