### ISSUE TITLE
No warning when you use 'this' inside a function

### ISSUE THREAD

**Issue by wizofaus** [Microsoft/TypeScript#2770]
If my class consists of

    class X {
      foo() {
      }
      bar() {
         setTimeout(function() {
            this.foo();
         }, 10)
      }
    }

I really should get some sort of warning that "this" doesn't mean what I think it means (or that I should use lambda syntax). This has bitten me repeatedly as I've been converting js code into ts code.

**Comment by wizofaus** [comment]
(I seen noticed #1985, but I've put a comment as to why this isn't quite enough).

**Comment by RyanCavanaugh** [comment]
The behavior as-is is by design, as sometimes you really do need the `this` that isn't the lexical one. We're tracking the general problem in hope of solution in the referenced issue and others; no need for a separate one here.
