### ISSUE TITLE
Import module type definition without importing it for async imports.

### ISSUE THREAD

**Issue by ccorcos** [Microsoft/TypeScript#27762]
## Suggestion

I want to asynchronously import a module and assign it to a variable without losing its type definition.

```ts
class NewRelicService {
    private newrelic: X
    public async init() {
        this.newrelic = await import("newrelic")
    }
}
```

However, its not possible for me to get the type definition of the module without importing it.

`@types/newrelic/index.ts` looks like this.

```ts
declare namespace newrelic {
    interface NewRelicAPI {}
}
declare const api: newrelic.NewRelicAPI;
export = api;
```

So the question is how can I get that type definition without importing the newrelic module. This doesn't work, and I've tried a number of different things.

```ts
import {NewRelicAPI} from "@types/newrelic/index"
import {newrelic} from "@types/newrelic/index"
import {api} from "@types/newrelic/index"
import {NewRelicAPI} from "newrelic"
import {newrelic} from "newrelic"
import {api} from "newrelic"
```

**Comment by andy-ms** [comment]
You can use `private newrelic!: typeof import("newrelic");`.

**Comment by ccorcos** [comment]
That's not going to import newrelic?
