### ISSUE TITLE
Edit & Continue not working in Visual Studio 2015 CTP6

### ISSUE THREAD

**Issue by rdesimone** [Microsoft/TypeScript#2777]
In VS 2013 with the TypeScript 1.4.0 plugin, it is possible to edit a TS file and to refresh the browser with the updated JS file while the code is running. With VS 2015 CTP 6 this is not possible.

![image](https://cloud.githubusercontent.com/assets/5596378/7163517/220ec0e2-e3a3-11e4-99e1-59e4bac44747.png)

There are several workarounds but I think this should be made possible again.

**Comment by mhegazy** [comment]
@CyrusNajmabadi i believe this is fixed now. can you confirm.

**Comment by CyrusNajmabadi** [comment]
Yes.  This appears to be fixed.  Have attached what i see when i try this.

![tsenc](https://cloud.githubusercontent.com/assets/4564579/7806642/61849634-0338-11e5-9b48-3fb4eca45fae.gif)
