### ISSUE TITLE
Generic mapped type constrained by a type parameter has different members / index signatures when constraint of that type parameter is a union

### ISSUE THREAD

**Issue by mattmccutchen** [Microsoft/TypeScript#27819]
**TypeScript Version:**  master (b2bae85cceb310354f6ba1ac4bcc9d75fe9a6402)

**Search Terms:** mapped type parameter member index signature constraint constrained union

**Code** (with noImplicitAny)
```ts
function foo1<K extends string>(arg: { [P in K]: string }) {
    // Actual: Error: Element implicitly has an 'any' type because type '{ [P in K]: string; }' has no index signature.
    return arg["test"];
}
function foo2<K extends string | number>(arg: { [P in K]: string }) {
    // Actual: No error
    return arg["test"];
}
function foo3<K extends "foo">(arg: { [P in K]: string }) {
    // Actual: Error: Property 'foo' does not exist on type '{ [P in K]: string; }'.
    return arg.foo;
}
function foo4<K extends "foo" | "bar">(arg: { [P in K]: string }) {
    // Actual: No error
    return arg.foo;
}
```

**Expected behavior:** Consistent behavior between `foo1` and `foo2` and between `foo3` and `foo4`.

**Actual behavior:** As marked.

**Playground Link:** [link](https://www.typescriptlang.org/play/#src=function%20foo1%3CK%20extends%20string%3E(arg%3A%20%7B%20%5BP%20in%20K%5D%3A%20string%20%7D)%20%7B%0D%0A%20%20%20%20%2F%2F%20Actual%3A%20Error%3A%20Element%20implicitly%20has%20an%20'any'%20type%20because%20type%20'%7B%20%5BP%20in%20K%5D%3A%20string%3B%20%7D'%20has%20no%20index%20signature.%0D%0A%20%20%20%20return%20arg%5B%22test%22%5D%3B%0D%0A%7D%0D%0Afunction%20foo2%3CK%20extends%20string%20%7C%20number%3E(arg%3A%20%7B%20%5BP%20in%20K%5D%3A%20string%20%7D)%20%7B%0D%0A%20%20%20%20%2F%2F%20Actual%3A%20No%20error%0D%0A%20%20%20%20return%20arg%5B%22test%22%5D%3B%0D%0A%7D%0D%0Afunction%20foo3%3CK%20extends%20%22foo%22%3E(arg%3A%20%7B%20%5BP%20in%20K%5D%3A%20string%20%7D)%20%7B%0D%0A%20%20%20%20%2F%2F%20Actual%3A%20Error%3A%20Property%20'foo'%20does%20not%20exist%20on%20type%20'%7B%20%5BP%20in%20K%5D%3A%20string%3B%20%7D'.%0D%0A%20%20%20%20return%20arg.foo%3B%0D%0A%7D%0D%0Afunction%20foo4%3CK%20extends%20%22foo%22%20%7C%20%22bar%22%3E(arg%3A%20%7B%20%5BP%20in%20K%5D%3A%20string%20%7D)%20%7B%0D%0A%20%20%20%20%2F%2F%20Actual%3A%20No%20error%0D%0A%20%20%20%20return%20arg.foo%3B%0D%0A%7D%0D%0A) (with noImplicitAny)

**Related Issues:** None found.

Looks like the cause is that this line in `resolvedMappedTypeMembers` in the checker is using `getApparentType`, which changes either `string` or `"foo"` to `String` (which doesn't generate an index signature) but leaves unions alone.  What was the thinking here??

                const keyType = constraintType.flags & TypeFlags.InstantiableNonPrimitive ? getApparentType(constraintType) : constraintType;

**Comment by ahejlsberg** [comment]
I believe this was fixed by #29121. All four examples now produce errors as expected.
