### ISSUE TITLE
Handle type parameter extending a union type in the spec

### ISSUE THREAD

**Issue by JsonFreeman** [Microsoft/TypeScript#2781]
Section 3.10.3 / 3.10.4 need to be updated in the spec to support the code in #2576. The suggested change is:

* If S is a type parameter whose base constraint is a union type, S is assignable to T if the base constraint of S is assignable to T

**Comment by JsonFreeman** [comment]
Code change for this is #2778

**Comment by ahejlsberg** [comment]
Fixed in #4167.
