### ISSUE TITLE
Type parameters of function-valued arguments infer as any when using type aliases.

### ISSUE THREAD

**Issue by justinfagnani** [Microsoft/TypeScript#27848]
**TypeScript Version:**  3.1.1 and playground

**Search Terms:** type argument infer type alias 

**Code**

```ts
type F = (...args: any[]) => Function;

const identity1 = <T extends Function>(o: T): T => o;
const identity2 = <T extends F>(o: T): T => o;

const f = <T>(x: T): T => x;

const f1 = identity1(f);
const f2 = identity2(f);
```

**Expected behavior:**

Both f1 and f2's type should infer as `<T>(x: T) => T`.

**Actual behavior:**

f1's type is correctly inferred as `<T>(x: T) => T`.
f2's type is incorrectly inferred as `(x: any) => any`.

**Playground Link:** http://www.typescriptlang.org/play/#src=type%20F%20%3D%20(...args%3A%20any%5B%5D)%20%3D%3E%20Function%3B%0A%0Aconst%20identity1%20%3D%20%3CT%20extends%20Function%3E(o%3A%20T)%3A%20T%20%3D%3E%20o%3B%0A%0Aconst%20identity2%20%3D%20%3CT%20extends%20F%3E(o%3A%20T)%3A%20T%20%3D%3E%20o%3B%0A%0Aconst%20f%20%3D%20%3CT%3E(x%3A%20T)%3A%20T%20%3D%3E%20x%3B%0A%0Aconst%20f1%20%3D%20identity1(f)%3B%0Aconst%20f2%20%3D%20identity2(f)%3B

**Related Issues:**

**Comment by ahejlsberg** [comment]
This is working as intended. When an argument of a function type with a single generic call signature is passed for a parameter of a generic type constrained to a function type with a single non-generic call signature, as is the case in the call to `identity2`, we instantiate the function type argument in the context of the constraint. So, we end up inferring `any` for `T` in the type of `f` and that the type of the argument is processed as `(x: any) => any`.
