### ISSUE TITLE
Allow spread operator for new expressions when targeting ES3 using a helper function

### ISSUE THREAD

**Issue by JakeTunaley** [Microsoft/TypeScript#27856]
## Search Terms
rest spread class constructor new expression target es3 runtime tslib

## Suggestion

Currently when targeting ES3 it is not possible to use the spread operator to pass arguments to a new expression.

```ts
class Foo {
    constructor (...args: any[]) {}
}

new Foo(1, 7, 8); // Fine
new Foo(...[1, 7, 8]); // [ts] Spread operator in 'new' expressions is only available when targeting ECMAScript 5 and higher.
```

A tslib function could be added to do this.

```js
function __ctorApply (newable, args) {
    var output;
    if (newable !== RegExp) {
        var Wrapper = function () {
            newable.apply(this, args);
        };

        if (Object.create) {
            Wrapper.prototype = Object.create(newable.prototype);
        }
        else {
            // Extracted from an Object.create shim - see https://stackoverflow.com/a/18020329
            var proto = function () {};
            proto.prototype = newable.prototype;
            Wrapper.prototype = new proto();
        }

        Wrapper.prototype.constructor = Wrapper;
        output = new Wrapper();
    }
    else {
        // Fixes "RegExp.prototype.source getter called on non-RegExp object" runtime error
        output = new RegExp(args[0], args[1]);
    }
    return output;
}
```

This would mean the original example, instead of generating an error, would get compiled to the below plus the above function:

```ts
var Foo = /** @class */ (function () {
    function Foo() {
        var args = [];
        for (var _i = 0; _i < arguments.length; _i++) {
            args[_i] = arguments[_i];
        }
    }
    return Foo;
}());
new Foo(1, 7, 8); 
__ctorApply(Foo, __spread([1, 7, 8]));
```

## Use Cases

This suggestion opens up the option of using the spread operator in new expressions, which can be important for dynamic class creation. Here's the example where I ran into this in a real-world application:

```ts
interface State {
    // Information about some system's state
}

abstract class OutputView {
    public readonly state: State;

    public constructor (state: State) {
        this.state = state;
    }

    protected abstract removeFromDomImpl (): void;
}

abstract class IOView extends OutputView {
    private readonly linkedViews: OutputView[];

    public createLinkedView<TArgs extends any[], TOut, TType extends new (state: State, ...args: TArgs) => TOut> (type: TType, ...args: TArgs): TOut {
        const obj = new type(this.state, ...args); // [ts] Spread operator in 'new' expressions is only available when targeting ECMAScript 5 and higher.
        this.linkedViews.push(obj);
        return obj;
    }

    public removeFromDom (): void {
        this.linkedViews.forEach(view => view.removeFromDomImpl());
        this.removeFromDomImpl();
    }
}
```

As a workaround I'm currently defining the above `__ctorApply` function in my runtime library.

### Only Spread Arguments

Pass the spread arguments to the `__spread` tslib function first, just like with the current callable spread implementation.

```ts
new Foo(...[1, 2, 3, 4]);
new Foo(...[1, 2], ...[3, 4]);
// Compiles to
__ctorApply(Foo, __spread([1, 2, 3, 4]));
__ctorApply(Foo, __spread([1, 2], [3, 4]));
```

### Mixed Spread and Normal Arguments

If the user specified both normal and spread arguments, we can concatenate them into an array first, just like with the current callable spread implementation.

```ts
new Foo(1, 2, ...[3, 4]);
new Foo(1, 2, ...rest);
// Compiles to
__ctorApply(Foo, __spread([1, 2], [3, 4]));
__ctorApply(Foo, __spread([1, 2], rest));
```

### Union Types with Functions

Ambiguity over whether to use `__ctorApply` or the current spread operator implementation for newable types unioned with functions, or types that are both newable and callable, can be resolved based on whether the `new` operator is used or not.

```ts
Foo(1, 2, ...[3, 4]);
new Foo(1, 2, ...[3, 4]);
// Compiles to
Foo.apply(void 0, __spread([1, 2], [3, 4]));
__ctorApply(Foo, __spread([1, 2], [3, 4]));
```

### The `Error` Object

Because `Error` objects can't be extended in the same way as normal objects (e.g. `instanceof` breaks if you try), using the spread operator on their constructors should still be an error.

```ts
// Ignoring argument type and undefined variable errors...
new Error(...[1, 2]); // [ts] Spread operator in 'new' expressions where the new object could be Error (or more derived) is only available when targeting ECMAScript 5 and higher.
new RangeError(...[1, 2]); // Same error
const ctor: Foo | Error;
new ctor(...[1, 2]); // Same error
const creator: new (...args: any[]) => Error;
new creator(...[1, 2]); // While this *might* be correct depending on what creator is at runtime, we cannot prove that it will work, so this should also emit the same error
```

### Logging

Depending on the console.log implementation, this may lead to different results.

```js
console.log(__ctorApply(Foo, [])); // Wrapper ... (in Chrome)
```

Note that this doesn't occur when using `this` to get the constructor's name, so this is only a logging issue.

```ts
class Foo {
    public constructor () {
        console.log(Object.getPrototypeOf(this).constructor.name);
    }
}

__ctorApply(Foo, []); // Logs "Foo" instead of "Wrapper"
```

## Checklist

My suggestion meets these guidelines:
* [ ] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. new expression-level syntax)

The first two boxes are unchecked because adding this function could cause a naming conflict if someone already defined something called `__ctorApply`, which would either break existing code or TypeScript's spreading downleveling. Other than that case, this is not breaking and won't change runtime behaviour (apart from the aforementioned logging caveat).

**Comment by weswigham** [comment]
I'm pretty sure the reason we don't allow it when targeting ES3 is because currently we like that `new Array(...[1,2,3])` just emits as the comparably simple `new (Array.bind.apply(Array, [void 0].concat([1, 2, 3])))();` and ES3 has no `.bind` implementation (see #3066). And when talking about other bits of our spread downlevel, we've generally be very hesitant to add a helper for it.
TBH, if you want the behavior I'd polyfill `.bind` and target `ES5` myself.

**Comment by fatcerberus** [comment]
Huh, I'm stunned that it's even possible to polyfill constructor spread in ES3; over a year ago I wanted to polyfill `Reflect.construct()` *in ES5* and it took me forever just to realize I could use `.bind()` and `.apply()` in combination to pull it off.  I wouldn't have even known where to begin to do it in ES3! 😝 

(I'm equally stunned that people still want to target ES3 in 2018 but hey, I'll choose my battles :wink:)
