### ISSUE TITLE
Exclude does not work correctly on constrained type parameters

### ISSUE THREAD

**Issue by WearyMonkey** [Microsoft/TypeScript#27882]
**TypeScript Version:**  
typescript@3.2.0-dev.20181011
typescript@3.1.3
typescript@3.0.3

**Search Terms:**

exclude extends omit

**Code**

```ts
type Primate = 'monkey' | 'human';

function zee<P extends Primate>() {
    const a: Exclude<P, 'human'> = 'monkey';
}
```

**Expected behavior:**

No error

**Actual behavior:**

`Type '"monkey"' is not assignable to type 'Exclude<P, "human">'.`

**Playground Link:** 

https://www.typescriptlang.org/play/#src=type%20Primate%20%3D%20'monkey'%20%7C%20'human'%3B%0D%0A%0D%0Afunction%20zee%3CP%20extends%20Primate%3E()%20%7B%0D%0A%20%20%20%20const%20a%3A%20Exclude%3CP%2C%20'human'%3E%20%3D%20'monkey'%3B%0D%0A%7D%0D%0A

**Related Issues:**

**Comment by mattmccutchen** [comment]
I believe this is working correctly.  If `P` is `never` or `"human"`, then indeed `"monkey"` is not assignable to `Exclude<P, "human">`.
