### ISSUE TITLE
intelli sense union type with spread

### ISSUE THREAD

**Issue by JounQin** [Microsoft/TypeScript#27884]
## Search Terms

- spread
- union

## Suggestion

intelli sense union type with spread

## Use Cases

union type with spread is so great

## Examples

```ts
import React, { SFC } from 'react'
import ReactDOM from 'react-dom'

const handleRef = (ref: React.ReactInstance) => {
  (ReactDOM.findDOMNode(ref) as HTMLElement)!.style.cursor = 'pointer'
}

export const Clickable: SFC<
  | {
      tag?: string
      onClick?: React.MouseEventHandler<Element>
    }
  | {
      tag: SFC | React.ComponentClass
    }
> = ({ children, tag, ...props }) => {
  Object.assign(props, {
    ref: handleRef,
  })

  // there will be error about `props` not incompatible
  return React.createElement(tag || 'span', props, children)
}
```

`props` type is

```ts
typeof props === { onClick?: React.MouseEventHandler<Element> } | {}
```

But actually when `tag` is `string`, it should be `{ onClick?: React.MouseEventHandler<Element> }`, otherwise it should be `{}`, what means both of them should be acceptable.

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by andy-ms** [comment]
Could you try to write an example that doesn't use react? Hard to tell what part of this problem is the type system vs react types.

**Comment by weswigham** [comment]
The error is on `React.createElement` which is defined in `DefinitelyTyped`'s `react.d.ts`. You'd want to submit an issue/PR over at https://github.com/DefinitelyTyped/DefinitelyTyped/ - AFAIK the issue is simply that the `react` types have no overload which can handle a union of an SFC and a tag name string (perhaps reasonably so).

**Comment by JounQin** [comment]
Here is an example without `React`, you can check whether is it working as intended.

```ts
interface Attributes {
  key?: string
}

interface HTMLAttributes extends Attributes {
  onClick?: (e: Event) => void
}

function createElement(tag: string, props: HTMLAttributes): string
function createElement(tag: Element, props: Attributes): string
function createElement(test: Element | string, props: Attributes): string {
  return test.toString() + props.toString()
}

interface Stateless<P> {
  (props: P): void
}

const content: Stateless<
  | {
      tag?: string
      onClick?: (e: Event) => void
    }
  | {
      tag: Element
    }
> = ({ tag, ...props }) => {
  createElement(tag, props) // emit error about type incompatible
}
```

However there will be no error as following:
```ts
const content1: Stateless<{
  tag: string
  onClick?: (e: Event) => void
}> = ({ tag, ...props }) => {
  createElement(tag, props)
}

const content2: Stateless<{
  tag: Element
}> = ({ tag, ...props }) => {
  createElement(tag, props)
}
```
