### ISSUE TITLE
WheelEvent contains fields that are not listed in the offical spec [lib.dom.d.ts]

### ISSUE THREAD

**Issue by lgoenner** [Microsoft/TypeScript#27886]
[WheelEvent in lib.dom.d.ts](https://github.com/Microsoft/TypeScript/blob/master/lib/lib.dom.d.ts#L16194) contains fields not present in the [w3 specification](
https://www.w3.org/TR/uievents/#event-type-wheel).

`readonly wheelDelta: number;
readonly wheelDeltaX: number;
readonly wheelDeltaY: number;`

Currently working on a PR that removes them.

**Comment by DanielRosenwasser** [comment]
Should this be filed against https://github.com/w3c/uievents/issues/?

**Comment by lgoenner** [comment]
Closed by Microsoft/TSJS-lib-generator#579
