### ISSUE TITLE
Question: ClassDeclaration how to locate after brace from the AST

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#2788]
I have a class: 
```
class OtherTest{
}
```
I want to find the location inside the braces `{ /*here*/ }`. I have access to the `ClassDeclaration` node, how can I get the between the brace point. 

Sample ASTs: 

For the given example:
![image](https://cloud.githubusercontent.com/assets/874898/7173066/0f351632-e435-11e4-8781-ea3897317193.png)

And for :

```ts
class Test {
    // What is the location of HERE
    constructor() { 
    }
}
```
![image](https://cloud.githubusercontent.com/assets/874898/7173074/2c452c3a-e435-11e4-99b4-353b80550c1b.png)

**Comment by CyrusNajmabadi** [comment]
if you call .getChildren on the class declaration, you should get back an array that includes the open and close braces.

**Comment by basarat** [comment]
@CyrusNajmabadi cool it looks like thats it. Does `forEachChild` skip such nodes?

**Comment by DanielRosenwasser** [comment]
@basarat yes it does. `forEachChild` is only aware of whatever is in the compiler AST proper.

**Comment by basarat** [comment]
Thanks. I review that code more :heart:

**Comment by basarat** [comment]
I've added an `Ast Full` visualizer : https://github.com/TypeStrong/atom-typescript#ast-visualizer 

![image](https://cloud.githubusercontent.com/assets/874898/7174934/219b82b2-e452-11e4-92f2-915665ed0f05.png)

**Comment by DanielRosenwasser** [comment]
I had a feeling from the screenshots :smile: 

:+1: :+1: :+1: :100: that is awesome @basarat

**Comment by basarat** [comment]
@DanielRosenwasser oh ... I've had the ast visualizer for quite a while ... what I did right now was expanded it to also list the `full` version :)

**Comment by DanielRosenwasser** [comment]
Ah, I see - you'll have to forgive me. I haven't gotten the chance to see the plugin in a while since we've been so focused on 1.5 and our LS front-ends - just at a glance I'm impressed. Keep up the great work!
