### ISSUE TITLE
[docs] Module mode vs. script mode

### ISSUE THREAD

**Issue by bcherny** [microsoft/TypeScript#27893]
Gleaning the [docs](https://www.typescriptlang.org/docs/handbook/modules.html), it looks like TSC parses files in either Module Mode or Script Mode. From the docs and from playing around with TS-

- If a file has at least one `import`, `export`, or `export =`, TSC typechecks the file in Module Mode
- Otherwise, TSC typechecks the file in Script Mode

The differences seem to be that in Script Mode:

- You can directly consume globals exported by UMD modules (`export namespace as`)
- You can declare globals, that are then available in other files in the project without an explicit import. There seem to be a few ways to do that:
  - `let a = 1`, `let a: 1`, or `declare let a: 1` in a _.ts_ file
  - `declare let a: 1` in a _.d.ts_ file

In Module Mode:

- You can't use globals exported from UMD modules, and instead have to explicitly `import` the UMD module's exports
- You can declare globals, that are then available in the current file only (not in other files):
  - `let a = 1`, `let a: 1`, or `declare let a: 1` in a _.ts_ file
  - `declare let a: 1` in a _.d.ts_ file

Are there any other differences, and are there any TSC flags that affect this behavior? I can't find anything else covering this in the spec or the docs.

**Comment by bcherny** [comment]
Also, why is Script mode vs. Module mode based on a heuristic, instead of an explicit tsconfig flag?

**Comment by RyanCavanaugh** [comment]
https://www.typescriptlang.org/docs/handbook/2/modules.html
