### ISSUE TITLE
Support non-code AMD modules

### ISSUE THREAD

**Issue by fsoikin** [Microsoft/TypeScript#279]
Original issue on CodePlex: https://typescript.codeplex.com/workitem/1046

## Problem
Need to `require` text, CSS, and other non-code things.

```
import template: string = require( "text!./Templates/MyTemplate.html" );
```

## Partial workaround
Use the `/// <amd-dependency path="x" />` tag.

```
// At the top of the file
/// <amd-dependency path="text!./Templates/MyTemplate.html" />

... <snip> ...

declare function require( path: string ): any;
var template: string = require( "text!./Templates/MyTemplate.html" );
```

## Why workaround is not good enough
Have to type the module name twice.

**Comment by csnover** [comment]
This is already fixed in 1.5, you can specify a `name` attribute on the amd-dependency comment. https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#amd-dependency-optional-names

**Comment by mhegazy** [comment]
We have talked about allowing type annotation on module imports. something like:
```ts
import * as n: any from "mod";
```

**Comment by RichiCoder1** [comment]
@mhegazy I would very much like that. Not only to type html imports as strings, but also for types that are "map"'d, so you don't have to write a definition to map the name to the actual type.

**Comment by mhegazy** [comment]
@RichiCoder1, i am interested to know what you mean by "mapped". Would that be something covered by mapping paths for module? can you take a look at #2338, and see if this fits your scenario?

**Comment by lukeapage** [comment]
is a type parameter on the amd-dependency possible? e.g.

typescript 1.4
```
// At the top of the file
/// <amd-dependency path="text!./Templates/MyTemplate.html" />

... <snip> ...

declare function require( path: string ): any;
var template: string = require( "text!./Templates/MyTemplate.html" );
```
typescript 1.5
```
// At the top of the file
/// <amd-dependency path="text!./Templates/MyTemplate.html" name="myTemplateHtml" />
declare var myTemplateHtml : string;
... <snip> ...

var template: string = myTemplateHtml;
```
typescript 1.x ?
```
// At the top of the file
/// <amd-dependency path="text!./Templates/MyTemplate.html" name="myTemplateHtml" type="string" />
... <snip> ...

var template: string = myTemplateHtml;
```

**Comment by mhegazy** [comment]
@lukeapage it is just a proposal at this point. it has not been implemented. if and when it is added, i do not think it will be in an `/// <amd-dependency>` tag. more of a syntax extension to ES6 default module import syntax.

**Comment by mhegazy** [comment]
Should be addressed by https://github.com/Microsoft/TypeScript/issues/6615
