### ISSUE TITLE
Question: How does UnionToIntersection helper work

### ISSUE THREAD

**Issue by cevek** [Microsoft/TypeScript#27907]
Can anybody to explain how does this black evil magic work?
```ts
type UnionToIntersection<U> =
	(U extends any ? (k: U) => void : never) extends ((k: infer I) => void) ? I : never

```

If I simplify `(U extends any ? (k: U) => void : never)` -> `(a: U)=>void)` 
it starts to work just as expected (No intersection)
```ts
type UnionToIntersection<U> = ((a: U)=>void) extends ((k: infer I) => void) ? I : never
type F = UnionToIntersection<'A' | 'B'> // A | B
```
Distributive conditional types iterate over union and apply all union units to this condition
But somehow this condition `(U extends any ? (k: U) => void : never)` tells ts that we don't need to iterate over union items in the outer `extends` but in the inner `extends` and make new type: `((k: 'A') => void) | ((k: 'B') => void)`

so after all this combinations ts would work with type like this:  
```ts
type H = (((k: 'A') => void) | ((k: 'B') => void)) extends (k: infer I)=>void ? I : never;
```
And return `'A' & 'B'`  because function argument is contra-variant

So question why outer `extends` doesn't iterate union?

**Comment by jack-williams** [comment]
The outer conditional type:

`(U extends any ?  X : never`

**Comment by jack-williams** [comment]
The check type in the outer conditional is `(U extends any ? (k: U) => void : never)`. Conditional types only distribute if the check type is naked type parameter like `U`.

**Comment by cevek** [comment]
Aa, I understand, if we have some calculated type ts doesn't iterate the union
```ts
type JoinReturnType<T> = T & {} extends ()=>infer Ret ? () => Ret : never;
type A = () => number;
type B = () => string;
type U = JoinReturnType<A | B>;  // () => string | number
// without & {} hack it will be () => string | () => number

```

**Comment by jack-williams** [comment]
Yep! I think the advised way to 'turn-off' distribution, or iteration, is to use a tuple type:

```ts
type JoinReturnType<T> = [T] extends [() => infer Ret] ? () => Ret : never;
```

Your approach works here but there might be some issues in the propagation of constraints (I'm not sure).
