### ISSUE TITLE
Missing blog entry for 3.1 release announcement

### ISSUE THREAD

**Issue by HolgerJeromin** [Microsoft/TypeScript#27906]
I subscribed to the RSS feed behind
https://blogs.msdn.microsoft.com/typescript/

But in the overview and its rss feed the release announcement is not available.

https://blogs.msdn.microsoft.com/typescript/announcing-typescript-3-1/

**Comment by DanielRosenwasser** [comment]
Embarrassing, but I accidentally created a page on the blog instead of a post. Anyway, here's the real URL: https://blogs.msdn.microsoft.com/typescript/2018/09/27/announcing-typescript-3-1/

**Comment by HolgerJeromin** [comment]
Thanks for the quick fix.
The old url is still working. I am unsure if this is wanted. There are old links (for example https://github.com/Microsoft/TypeScript/releases ) pointing to this.

**Comment by DanielRosenwasser** [comment]
I'll fix the release pages, but at this point I can't really take down the page given that tweets can't be edited 😡
