### ISSUE TITLE
get/set properties codegen broken for ES5 - in object literals

### ISSUE THREAD

**Issue by mihailik** [Microsoft/TypeScript#27904]
**TypeScript Version:**  3.2.0-dev.20181011, also 3.1.1, also Playground

**Search Terms:**
getter class literal es5 defineProperty 

**Code**

```ts
class Apple {
    get prop() {
        return '12';
    }
}

var s = {
    get prop() {
        return '14';
    }
}
```

**Expected behavior:**

Build for --target ES5, produced code uses `Object.defineProperty` consistently for both `get`ter in the class Apple and `get`ter in the object literal.

Alternatively it can use newer get/set syntax in both class Apple context and object literal context.

**Actual behavior:**

Transpilation uses `Object.defineProperty` in the class context, and the newer get/set syntax in the object literal. Here's the exact output below:

```typescript
var Apple = /** @class */ (function () {
    function Apple() {
    }
    Object.defineProperty(Apple.prototype, "prop", {
        get: function () {
            return '12';
        },
        enumerable: true,
        configurable: true
    });
    return Apple;
}());
var s = {
    get prop() {
        return '14';
    }
};
```

**Playground Link:** 

<a href="http://www.typescriptlang.org/play/#src=class%20Apple%20%7B%0D%0A%20%20%20%20get%20prop()%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20'12'%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Avar%20s%20%3D%20%7B%0D%0A%20%20%20%20get%20prop()%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20'14'%3B%0D%0A%20%20%20%20%7D%0D%0A%7D">Playground</a>

Both cases being so close originally, should produce very close output.

Ideally my preference be the back-compatible `Object.defineProperty` option, but both on newer get/set syntax is reasonable too.

**Related Issues:** 

https://github.com/Microsoft/TypeScript/issues/14021

**Comment by andy-ms** [comment]
When emitting a class, we need to use `Object.defineProperty(Apple.prototype, ...)` rather than `Apple.prototype = { ... }` because of the possibility of inheritance:
```ts
__extends(Apple, _super);
function Apple() {
    return _super !== null && _super.apply(this, arguments) || this;
}
// overwriting `Apple.prototype` here would break the inheritance
Object.defineProperty(Apple.prototype, "prop", { ... });
```

With an object literal we don't need to worry about that.

**Comment by mihailik** [comment]
Yes, yes and yes. Makes total sense, obviously. Thanks!!
