### ISSUE TITLE
Update language specification

### ISSUE THREAD

**Issue by avchugaev** [Microsoft/TypeScript#27903]
Please update language specification. [Actual specification](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md) covers very old version **1.8**

**Comment by MartinJohns** [comment]
Duplicate of all these: https://github.com/Microsoft/TypeScript/issues?q=is%3Aopen+is%3Aissue+label%3ASpec

And mainly: #15711. But given PRs like #20971 it's clear that there won't be any progress on this any time soon.

**Comment by weswigham** [comment]
Duplicates #15711. Put your upvotes over there
