### ISSUE TITLE
Question: OpenBraceToken vs. FirstPunctuation

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#2791]
https://github.com/Microsoft/TypeScript/blob/05480e38bd78e4bd87dc573bb4b8fa4ef28d0c43/bin/typescript.d.ts#L39 vs. https://github.com/Microsoft/TypeScript/blob/05480e38bd78e4bd87dc573bb4b8fa4ef28d0c43/bin/typescript.d.ts#L265

Is there any difference or just two names for the same thing? Perhaps there was plan for a future difference?

(Sorry for creating these as separate issues, but I feel this way they will show up in search results if by chance other people have the same query or if I need to query it in future for someone else. I do *strictly* close these once answered though.)

**Comment by DanielRosenwasser** [comment]
`FirstPunctuation` and `LastPunctuation` are used to check whether a token is in the range of punctuation tokens. They exist purely so we don't have to remember what the range of punctuation is.

Use the more obvious one for your situation. You shouldn't be interested in `FirstPunctuation` unless you need to check whether a token is, well, punctuation.

**Comment by basarat** [comment]
Makes perfect sense. Thanks :rose:
