### ISSUE TITLE
L

### ISSUE THREAD

**Issue by magmacomputing** [Microsoft/TypeScript#27915]
**TypeScript Version:**  3.0.0-dev.201xxxxx

**Search Terms:** 

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**Expected behavior:**

**Actual behavior:**

**Playground Link:**  

**Related Issues:**

**Comment by saschanaz** [comment]
![image](https://user-images.githubusercontent.com/3396686/47013437-1d294e00-d182-11e8-8bb0-a6a3b8eee634.png)

**Comment by magmacomputing** [comment]
I appear to have been hacked... I did not file this issue.
I cannot guess what the intent of opening this was, though.

apologies
