### ISSUE TITLE
Date constructor throws error TS2556 when using spread operator

### ISSUE THREAD

**Issue by onlyflix** [microsoft/TypeScript#27920]
**TypeScript Version:**  3.2.0-dev.201xxxxx

**Search Terms:**
date spread operator

**Code**

```ts
const dateFields = [2018, 5, 14, 14, 41, 11];

const date = new Date(...dateFields);

```

**Expected behavior:**
The spread syntax is used to create a new date object without a problem.

**Actual behavior:**
The actual date object is created, but Typescript throws the following error: 
`TS2556: Expected 0-7 arguments, but got 0 or more.`

**Playground Link:** 
[Example Playground](https://www.typescriptlang.org/play/index.html#src=const%20dateFields%20%3D%20%5B2018%2C%205%2C%2014%2C%2014%2C%2041%2C%2011%5D%3B%0D%0A%0D%0Aconst%20date%20%3D%20new%20Date(...dateFields)%3B%0D%0A)

**Related Issues:** 
None

**Comment by MartinJohns** [comment]
This is the common problem that the **inferred** type of `dateFields` is `number[]`, and not a tuple as you expect it. If you explicitly type the variable to be a tuple containing 6 numbers then it works.

```
const dateFields: [number, number, number, number, number, number] = [2018, 5, 14, 14, 41, 11];

const date = new Date(...dateFields);
```

There are several issues regarding this open. It's the same problem with literal-types.

**Comment by onlyflix** [comment]
Thanks for the fast reply. I guess this *kind of* fixes it for the moment.

But I am using this code in an Angular project and on the first compiling when I start the project, the error still occurs and the compiling fails. If I then save a file and in this way restart the compiler, it works.

**Comment by MartinJohns** [comment]
You should check what TypeScript version your Angular project is using. Angular limits the supported version of TypeScript you use - you can't just use the newest TypeScript version in an angular project. You need at least TypeScript version 3.0 for this feature.

**Comment by onlyflix** [comment]
Alright, thanks for the clarification! The current stable Angular release only support a TypeScript version under 2.10.

**Comment by ststeiger** [comment]
Actually, since the relevant line in DateConstructor is 
`new(year: number, month: number, date?: number, hours?: number, minutes?: number, seconds?: number, ms?: number): Date; `

You need to define a type that can be anything between a 2 and 7 numbers array. 
That goes like this: 
`type DateComponents = [number, number, number, number, number, number, number] | [number, number, number, number, number, number] | [number, number, number, number, number] | [number, number, number, number] | [number, number, number] | [number, number];`

**Comment by moker-monkey** [comment]
https://stackoverflow.com/questions/55887719/how-to-use-spread-as-argument-of-function/55887905#55887905
