### ISSUE TITLE
I had the same problem. I did `typings dt~mypackage --save --global` and the problem was solved.

### ISSUE THREAD

**Issue by suchetaswabhav** [Microsoft/TypeScript#27921]
_Originally posted by @nfnxmc in https://github.com/Microsoft/TypeScript/issues/15970#issuecomment-316482104_

I am unable to identify and decode the values of this command -

     typings dt~mypackage --save --global

Can you please help. 
My error is -

ERROR in /home/dell/Downloads/Neo4j/Project/Neo4j-4/neo4jproject/src/app/elements/neo4j-primary/neo4j-primary.component.ts (17,26): Module './../../../assets/neovis.js' was resolved to '/home/dell/Downloads/Neo4j/Project/Neo4j-4/neo4jproject/src/assets/neovis.js', but '--allowJs' is not set.

**Comment by j-oliveras** [comment]
Typings is deprecated since June 2017.

[See deprecation notice](https://github.com/typings/typings#deprecation-notice-regarding-typescript20).

**Comment by suchetaswabhav** [comment]
> Typings is deprecated since June 2017.
> 
> [See deprecation notice](https://github.com/typings/typings#deprecation-notice-regarding-typescript20).

Can you help me decode what to write in  ' mypackage' ??
I wrote this command - 

         neovis.js --save --global

And i got output -

          neovis.js: command not found

Please help in determining the correct command
