### ISSUE TITLE
Bug inside of index.dom.d.ts Window

### ISSUE THREAD

**Issue by McFlat** [Microsoft/TypeScript#27925]
The reason for the pull request is to avoid having to set "suppressImplicitAnyIndexErrors":true in the tsconfig.json

ERROR in src/standalone/player/player.ts(194,1): error TS7017: Element implicitly has an 'any' type because type 'Window' has no index signature.

**TypeScript Version:**  2.5.2

master branch

**Search Terms:**

Window index signature

**Code**

```
[key:string]: any; // missing index definition
```
Here's an example:
```
window[ 'VideoPlayer' ] = VideoPlayer
```

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**Expected behavior:**
Expected to be able to set a index on Window object.

**Actual behavior:**
Getting error when setting index on Window

**Playground Link:** 

**Related Issues:** 
Didn't find anything similar, what I found is a suggestion on stackoverflow
- https://stackoverflow.com/questions/42193262/element-implicitly-has-an-any-type-because-type-window-has-no-index-signatur#42193905
- https://basarat.gitbooks.io/typescript/docs/types/index-signatures.html

**Comment by andy-ms** [comment]
You didn't provide an example, but I'll assume you wrote something like:
```ts
function f(s: string) {
    return window[s];
}
```

There's no particular reason we should allow arbitrary accesses on `window` but not on any other type. If you really want to always be able to do this sort of thing, you could set `"noImplicitAny": false,` in your `tsconfig.json` -- if you just wanted to do it in this case, you could write `(window as any)[s]`.

**Comment by McFlat** [comment]
My bad. Here's an example:

```
window[ 'VideoPlayer' ] = VideoPlayer
```

**Comment by McFlat** [comment]
The reason for this pull request is to avoid having to set `"suppressImplicitAnyIndexErrors":true` in the tsconfig.json

**Comment by McFlat** [comment]
@RyanCavanaugh Why was this issue closed? We are trying to write solid code with out buggy behavior, and therefore we are tying to avoid using the `suppressImplicitAnyIndexErrors` setting in tsconfig.json. Please explain why this issue doesn't meet your standards...

**Comment by McFlat** [comment]
But in the real world the issue still stands, in the browser we can set `window['index'] = 1` but in the `MicroSoft/TypeScript` world we can't unless we use a hacky method to do it.

**Comment by McFlat** [comment]
@RyanCavanaugh there's nothing illegal in JavaScript land here. if it was illegal an error would be thrown.

Here's an example:
<img width="382" alt="screen shot 2018-10-19 at 10 37 23 am" src="https://user-images.githubusercontent.com/43896676/47228504-06a21300-d38b-11e8-98c1-457e9268e656.png">

**Comment by RyanCavanaugh** [comment]
@McFlat it sounds like you want a version of TypeScript that only issues errors on syntactic problems, rather than semantic problems? You can do this already - rename from `.ts` to `.js` and you'll see exactly that behavior.

**Comment by McFlat** [comment]
@RyanCavanaugh I was giving you a simple example without taking so much time to come up with a more advanced example. The thing is window allows for index to be set, while in TypeScript it doesn't because of the missing index key any property, therefore I added the missing functionality seeing as window actually allows that behavior in the real world.

**Comment by RyanCavanaugh** [comment]
@McFlat understood. All objects in JavaScript can be indexed. The choice over whether or not TypeScript represents that in the type system for any particular object (especially with the type `any`) depends on how the object is used in common practice, weighed against the downsides of allowing indexing in scenarios where it was unintentional.

For `window`, which is very often used with `window.someMethod` syntax, we think it's more important to get "typo checking" on the `someMethod` part than to make `window["someGlobal"]` more ergonomic; these are in direct tension.

Additionally, you can add the index signature to the global interface in your own code if you'd prefer the looser mode, but you can't remove an existing index signature if we put it in there, so when "opt in" exists but "opt out" doesn't, we'd prefer to have people opt in than make the choice for everyone.

**Comment by McFlat** [comment]
Ok I think `window.index = {}` seems doable
