### ISSUE TITLE
Pass array as rest parameters by destructuring 

### ISSUE THREAD

**Issue by J-F-Liu** [Microsoft/TypeScript#2793]
The following code:
~~~~~~~~~~~~~~
class GameObjectGroup extends GameObject {
    objects: GameObject[];

    constructor(...objects: GameObject[]) {
        super();
        this.objects = objects;
    }
}
class Scene extends GameObjectGroup {
    id: number;

    constructor(...objects: GameObject[]) {
        super(...objects);
    }
}
~~~~~~~~~~~~~~
Can't compile in TypeScript 1.4, will this be supported in 1.5 or not?

**Comment by nycdotnet** [comment]
Take a look at https://github.com/Microsoft/TypeScript/pull/1931
Did you try it in the TypeScript 1.5 alpha?

**Comment by mhegazy** [comment]
This is doable with the latest release 1.5. See the release notes for more details: https://github.com/Microsoft/TypeScript/releases/tag/v1.5.0-alpha

**Comment by J-F-Liu** [comment]
Tried 1.5 alpha, it works, but this is not documented in the release note.
