### ISSUE TITLE
Union types: Primitive type value (like number) can be assigned to interface type

### ISSUE THREAD

**Issue by roman-petrov** [Microsoft/TypeScript#27944]
**TypeScript Version:**  3.1.3

**Search Terms:** union types narrowing 

**Code**

```ts
interface IComplexSize {
    size: ISizeConstraint;
}

function setSize(element: ISimpleSize | IComplexSize, width: number) {
    element.size = width;
}

var simpleSize: ISimpleSize = {
    size: 10
}
setSize(simpleSize, 100);
console.log('simpleSize', simpleSize.size); // logs '100'

var complexSize: IComplexSize = {
    size: {
        value: 10
    }
}
setSize(complexSize, 100);
console.log('complexSize', complexSize.size); // logs '100'
```
**Expected behavior:** Code should not compile

**Actual behavior:** Code compiles and allows to assign number to interface type. Function 'setSize' should compile because ISImpleSize / IComplexSize have nothing in common.

**Playground Link:** https://bit.ly/2J1eCeL

**Comment by RyanCavanaugh** [comment]
This is an intentional complexity/soundness trade-off -- property reads and writes are treated equally

**Comment by roman-petrov** [comment]
I am sorry, maybe am not too good in TypeScript design principles... but I got a runtime error in my program due to this compiler behavior and spent a hour debugging this problem. I have strictly typed program without usage of 'any' type and object with property like 'IComplexSize' but after some code refactoring got run time error and 'number' type in it. 

So I thought that TypeScript type system advantage over JavaScript is to protect user from such situations. For example, from my C# experience, I never was able to write program that able to assign number to incompatible type leading to run time error.

To be more clear, I just expect if I write class like 

```TypeScript
class MyClass  {
   public size: IComplexSize
}
```
I will **never** get a number in `MyClass.size` at run time, because TypeScript is strongly typed language. So please, can you just tell me or give a link describing where I am wrong?..
