### ISSUE TITLE
TSX not compiling when changed, but compileOnSave is enabled

### ISSUE THREAD

**Issue by htinc** [microsoft/TypeScript#27940]
**TypeScript Version:**  3.2.0-dev.20181017

**Search Terms:** 
TSX not compiling when changed, but compileOnSave is enabled

**Code**
Just any .tsx file

```json
{
    "compileOnSave": true,
    "compilerOptions": {
        "target": "es5",
        "sourceMap": true,
        "jsx": "react",
        "jsxFactory": "BDOM.createElement",
        "outFile": "./client/build-out.js"
    }
}
```

**Expected behavior:**
When saving the TSX file, the compiler should recompile the tsx file (I have the compileOnSave enabled)

**Actual behavior:**
The files are not recompiled

**Playground Link:** 
Not Applicable

**Related Issues:**
Didnt find any

**Comment by weswigham** [comment]
In what editor?

**Comment by htinc** [comment]
**VS 2017**
Microsoft Visual Studio Enterprise 2017 
Version 15.8.1
VisualStudio.15.Release/15.8.1+28010.2003
Microsoft .NET Framework
Version 4.7.02046

and

**VSCode**
Version: 1.28.1 (user setup)
Commit: 3368db6750222d319c851f6d90eb619d886e08f5
Date: 2018-10-11T18:13:53.910Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by RyanCavanaugh** [comment]
This has been fixed in newer version of VS
