### ISSUE TITLE
Control flow analysis inference of a generic mapped type

### ISSUE THREAD

**Issue by JasonKleban** [Microsoft/TypeScript#27945]
When upgrading to 3.1.3 I get a new error not in 3.0.3:

I see two problems in the type checking of the sample below.

 1) before `const lo: number = min!;`, the return after null test of either identifier means that both will be non-null.
 2) Even so, I'm asserting non-null and still it thinks it could be null.  The subsequent acceptance of lo2 which includes null as an option suggests that it isn't a problem with the `T["min"]` and `number` half.

(There is no error without the generic <T> aspect of this sample.)

```ts
interface RangeSelectorStateBase {
    min: number | null;
    max: number | null;
}

type RangeSelectorState<T> = {
    [P in keyof (T & RangeSelectorStateBase)]: (T & RangeSelectorStateBase)[P];
}

function foo<T>(state : RangeSelectorState<T>) {
    const { min, max } = state;

    if (min === null || max === null) {
        return;
    }

    const lo: number = min!; // Type 'T["min"] & null' is not assignable to type 'number'.
    const hi: number = max!; // Type 'T["min"] & null' is not assignable to type 'number'.

    const lo2: number | null = min; // type-checks fine.
    const hi2: number | null = max; // type-checks fine.
}
```

[playground link](http://www.typescriptlang.org/play/#src=interface%20RangeSelectorStateBase%20%7B%0D%0A%20%20%20%20min%3A%20number%20%7C%20null%3B%0D%0A%20%20%20%20max%3A%20number%20%7C%20null%3B%0D%0A%7D%0D%0A%0D%0Atype%20RangeSelectorState%3CT%3E%20%3D%20%7B%0D%0A%20%20%20%20%5BP%20in%20keyof%20(T%20%26%20RangeSelectorStateBase)%5D%3A%20(T%20%26%20RangeSelectorStateBase)%5BP%5D%3B%0D%0A%7D%0D%0A%0D%0Afunction%20foo%3CT%3E(state%20%3A%20RangeSelectorState%3CT%3E)%20%7B%0D%0A%20%20%20%20const%20%7B%20min%2C%20max%20%7D%20%3D%20state%3B%0D%0A%0D%0A%20%20%20%20if%20(min%20%3D%3D%3D%20null%20%7C%7C%20max%20%3D%3D%3D%20null)%20%7B%0D%0A%20%20%20%20%20%20%20%20return%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20const%20lo%3A%20number%20%3D%20min!%3B%0D%0A%20%20%20%20const%20hi%3A%20number%20%3D%20max!%3B%0D%0A%0D%0A%20%20%20%20const%20lo2%3A%20number%20%7C%20null%20%3D%20min%3B%0D%0A%20%20%20%20const%20hi2%3A%20number%20%7C%20null%20%3D%20max%3B%0D%0A%7D)

Full error text:

```
Type 'NonNullable<(T & RangeSelectorStateBase)["min"]>' is not assignable to type 'number'.
  Type '(T["min"] & null) | (T["min"] & number)' is not assignable to type 'number'.
    Type 'T["min"] & null' is not assignable to type 'number'.
      Type 'NonNullable<T["min"] & null> | NonNullable<T["min"] & number>' is not assignable to type 'number'.
        Type 'NonNullable<T["min"] & null>' is not assignable to type 'number'.
          Type 'T["min"] & null' is not assignable to type 'number'.
```

**Comment by DanielRosenwasser** [comment]
Seems potentially related to the recent indexed access type changes.

**Comment by ahejlsberg** [comment]
This looks to be the same underlying issue as #22137. Assigning to @weswigham.

**Comment by RyanCavanaugh** [comment]
Tracking with #22137
