### ISSUE TITLE
GitHub: release 3.1.3's bug fixes link points to the 3.1.2 fixes

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/TypeScript#27946]
**Expected behavior:**
The 3.1.3 [release page](https://github.com/Microsoft/TypeScript/releases/tag/v3.1.3) contains a link called `fixed issues query for TypeScript 3.1.3` that actually points to the issues that were fixed in the previous `3.1.2 release`.

**Actual behavior:**
The link should point to [https://github.com/Microsoft/TypeScript/issues?q=is%3Aissue+milestone%3A%22TypeScript+3.1.3%22+label%3A%22fixed%22+](https://github.com/Microsoft/TypeScript/issues?q=is%3Aissue+milestone%3A%22TypeScript+3.1.3%22+label%3A%22fixed%22+)

**Comment by DanielRosenwasser** [comment]
Thanks for the heads up!
