### ISSUE TITLE
Add FormatCodeOptions: InsertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets

### ISSUE THREAD

**Issue by ToddThomson** [Microsoft/TypeScript#2795]
Reading compressed source code is not my thing. I like to see white space! Please consider adding this to FormatCodeOptions.

**Comment by DanielRosenwasser** [comment]
@ToddThomson I'm pretty sure I know what you're requesting, but just to make sure, can you give an example?

**Comment by ToddThomson** [comment]
Same formatting as parenthesis except for brackets. Example:

someArray[ key ] = someValue;

Whitespace after opening bracket and before closing bracket.

**Comment by ToddThomson** [comment]
Ok, this request didn't get into the vs2015 typescript text formatting options.

I will try once again to bring this "oversight" :santa: to the typescript coding gods.

Please provide a text formatting option for including a space before and after brackets. C# has it, heck every other visual studio supported language has it.

Leaving quietly now...

**Comment by RyanCavanaugh** [comment]
I'll bring this up at suggestion triage.

We usually don't support uncommon formatting styles. Linking to some projects that put spaces there would be useful for establishing how many people might want this vs the complexity of adding another formatting option.

**Comment by ToddThomson** [comment]
@RyanCavanaugh Ok. Here you go for supporting bracket "[]" spacing in visual studio languages:

First, only c# and typescript matter anymore!

C# and C++ have abundant support for the unloved "[]" in typescript.

Typescript should look to be the C# of the Javascript world. Don't just support the nodejs and javascript formatting options! Be More!

Example code that looks great; is easy to read:

let anArrayItem = anArray[ easyToSeeIndex ];

Vs:

let x=x[hardToSeeAndConfusingIndex];

The worst part is seeing my lovely, white space code go to compressed, unsupportable code with the addition of a semi-colon.

**Comment by RyanCavanaugh** [comment]
We usually don't support uncommon formatting styles. Linking to some projects that put spaces there would be useful for establishing how many people might want this vs the complexity of adding another formatting option.

**Comment by ToddThomson** [comment]
@RyanCavanaugh Ok. Here you go for supporting bracket "[]" spacing in visual studio languages:

First, only c# and typescript matter anymore!

C# and C++ have abundant support for the unloved "[]" in typescript.

Typescript should look to be the C# of the Javascript world. Don't just support the nodejs and javascript formatting options! Be More!

Example code that looks great; is easy to read:

let anArrayItem = anArray[ easyToSeeIndex ];

Vs:

let x=x[hardToSeeAndConfusingIndex];

The worst part is seeing my lovely, white space code go to compressed, unsupportable code with the addition of a semi-colon.

**Comment by ToddThomson** [comment]
I realize that reposting my replay to your repost will get me no where with this issue, but heck, I do like your hat and I can turn off your MS approved no spacing within brackets!

**Comment by RyanCavanaugh** [comment]
I asked you to provide some evidence that this is a common formatting style. Instead, you told me about how much you would like to have it, and talked about some other languages that also don't commonly use this spacing, which seems entirely irrelevant. Asking again seemed like an appropriate response.

If only a few people in the world want spaces between their brackets, then we're not going to do the feature. Based on evidence available to me, hardly anyone wants this option. Telling me about how much more readable *you* find it doesn't increase the number of people I've seen who want it -- obviously you think this option is desirable, otherwise you wouldn't be here.

**Comment by ToddThomson** [comment]
@RyanCavanaugh I provided you with formatting options that Visual Studio currently offers for C# and C++. I did this to show you that they offer a programmer the choice of having spacing within brackets ( and of course other scenarios ). I also tried to provide an argument for readability in array indexing.
Yes, you did ask for references to projects that use spaces in array indexing. Seriously, how many projects would I have needed to show?
Coding style is personal ( or dictated by an organization ). I have always used spacing in array indexing since my C++ days and will continue to do so ( I guess I'll have to turn off vs2015 automatic formatting for now ).
Respectfully, I'd like to differ with you and suggest that white space use in indexing is not uncommon. If Visual Studio offers it for C# and C++, I'd say there must have been a reason.
Lastly, your team's efforts to advance the javascript language are exactly what is needed. Thank-you.
Ok, off to hit some squash balls.

**Comment by ToddThomson** [comment]
@RyanCavanaugh I took a quick look to see if spacing inside brackets is uncommon. I have to say, quite to the opposite of what I thought, the more popular coding style is to have no whitespace in brackets and parenthesis. However, spacing within parenthesis and brackets is used a little more that by a few people in the world. There are linters that can enforce spacing within non-empty brackets. I would also point to the fairly popular javascript library that adheres to a coding style that uses spacing within brackets - jQuery ( you can look at their code and published coding style guidelines ).
I guess I would just like typescript to supporting a few more spacing options line c# and C++ does. I can only ask.

**Comment by mhegazy** [comment]
@ToddThomson, we would be open to accepting a PR if this is something you would be interested to contribute.

**Comment by ToddThomson** [comment]
@mhegazy I think I'm up for that! I have some time in the 2nd week of Aug.

**Comment by mhegazy** [comment]
Adding a new rule with a new config option should do it. there might be some other rules that conflict with it that would need some work.

Option InsertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis seems like a close match, so i would start by looking at it.

The formatting engine is rule based. so you will need to add a new rule for it. The rules are all in: rules.ts, see NoSpaceBeforeCloseParen https://github.com/Microsoft/TypeScript/blob/5bb2e2f584985b6b66a5ac337578fd1982f666c5/src/services/formatting/rules.ts#L449

The part that enables rules based on options is in rulesProvider.ts, see InsertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis in 
https://github.com/Microsoft/TypeScript/blob/5bb2e2f584985b6b66a5ac337578fd1982f666c5/src/services/formatting/rulesProvider.ts#L63-L72

Then tests are in tests\cases\fourslash, see for an example: https://github.com/Microsoft/TypeScript/blob/5bb2e2f584985b6b66a5ac337578fd1982f666c5/tests/cases/fourslash/formatNestedClassWithOpenBraceOnNewLines.ts

**Comment by ToddThomson** [comment]
@mhegazy You really are an excellent example of OSS project leadership!

When I opened this issue I did a bit of research on what was required - thus the title of the issue. However, your input above is so nice to see.

**Comment by mhegazy** [comment]
thanks @ToddThomson!
