### ISSUE TITLE
Extending `Map` with wrong number of type arguments shows no error

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#27951]
**TypeScript Version:**  3.2.0-dev.20181017

**Code**

```ts
class MyMap extends Map<string> {}
```

**Expected behavior:**

Error: `No base constructor has the specified number of type arguments.`

**Actual behavior:**

No error.

Issue was introduced by #25374. The issues it fixed, #23551 and #25362, seem to work fine even if I revert the change. CC @sandersn to confirm that JS class augmentation has been fixed and #25374 can be reverted.

**Comment by sandersn** [comment]
I change I made recently made sure that base type nodes lookup accounts for jsdoc everywhere, instead of a few places. That's probably what fixed the original issues. Reverting the lib changes seems like the right thing.

I can't find the PR right now, though.
