### ISSUE TITLE
Problem with this type

### ISSUE THREAD

**Issue by tao-cumplido** [Microsoft/TypeScript#27963]
**TypeScript Version:**  2.9.2, 3.1.1 (didn't try any other)

**Search Terms:**
`this` type
`keyof this`

**Code**

```ts
interface Foo {
    foo: number;
}

interface Bar {
    bar: number;
}

type FooBar = Partial<Foo & Bar>;
type FooBarMap<T extends FooBar> = { [P in Extract<keyof FooBar, keyof T>]: string };

declare function map<T extends FooBar>(o: T): FooBarMap<T>;

class A implements Foo {
    foo = 1;
    map = map(this);
    constructor() {
        console.log(this.map.foo) // unexpected: Property 'foo' does not exist on type 'FooBarMap<this>'.
        console.log(this.map.bar) // expected: Property 'bar' does not exist on type 'FooBarMap<this>'.
    }
}

class B implements Bar {
    bar = 1;
    map = map(this as B);
    constructor() {
        console.log(this.map.foo); // expected: Property 'foo' does not exist on type 'FooBarMap<B>'.
        console.log(this.map.bar);
    }
}
```

**Expected behavior:**
`map(this)` should be the same as `map(this as A)` for class `A`;

**Actual behavior:**
See code above or Playground.

I suspected the problem might be `keyof this` vs. `keyof A`, but I didn't manage to reduce the problem to it so I'm not sure.

**Playground Link:** 
[Link](http://www.typescriptlang.org/play/#src=interface%20Foo%20%7B%0D%0A%20%20%20%20foo%3A%20number%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20Bar%20%7B%0D%0A%20%20%20%20bar%3A%20number%3B%0D%0A%7D%0D%0A%0D%0Atype%20FooBar%20%3D%20Partial%3CFoo%20%26%20Bar%3E%3B%0D%0Atype%20FooBarMap%3CT%20extends%20FooBar%3E%20%3D%20%7B%20%5BP%20in%20Extract%3Ckeyof%20FooBar%2C%20keyof%20T%3E%5D%3A%20string%20%7D%3B%0D%0A%0D%0Adeclare%20function%20map%3CT%20extends%20FooBar%3E(o%3A%20T)%3A%20FooBarMap%3CT%3E%3B%0D%0A%0D%0Aclass%20A%20implements%20Foo%20%7B%0D%0A%20%20%20%20foo%20%3D%201%3B%0D%0A%20%20%20%20map%20%3D%20map(this)%3B%0D%0A%20%20%20%20constructor()%20%7B%0D%0A%20%20%20%20%20%20%20%20console.log(this.map.foo)%20%2F%2F%20unexpected%3A%20Property%20'foo'%20does%20not%20exist%20on%20type%20'FooBarMap%3Cthis%3E'.%0D%0A%20%20%20%20%20%20%20%20console.log(this.map.bar)%20%2F%2F%20expected%3A%20Property%20'bar'%20does%20not%20exist%20on%20type%20'FooBarMap%3Cthis%3E'.%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aclass%20B%20implements%20Bar%20%7B%0D%0A%20%20%20%20bar%20%3D%201%3B%0D%0A%20%20%20%20map%20%3D%20map(this%20as%20B)%3B%0D%0A%20%20%20%20constructor()%20%7B%0D%0A%20%20%20%20%20%20%20%20console.log(this.map.foo)%3B%20%2F%2F%20expected%3A%20Property%20'foo'%20does%20not%20exist%20on%20type%20'FooBarMap%3CB%3E'.%0D%0A%20%20%20%20%20%20%20%20console.log(this.map.bar)%3B%0D%0A%20%20%20%20%7D%0D%0A%7D)

**Related Issues:** 
https://github.com/Microsoft/TypeScript/issues/24791

**Comment by andy-ms** [comment]
I think this is the same problem as  #27883. `{ [P in Extract<keyof FooBar, keyof T>]: string };` should contain *at least* "foo", but we don't have a way to represent that.

**Comment by tao-cumplido** [comment]
@andy-ms 
I must admit, I don't think I fully grasp the issue you referenced, but I'm not sure they are related.

My problem here is that `map(this)` infers to `map<this>(this)` and it behaves differently than `map<A>(this)`, i.e. when I use the explicit forms `map<A>(this)` or `map(this as A)` then it works as expected. But from my understanding the type `this` and the type `A` should behave the same, at least in the case above, or not?
