### ISSUE TITLE
Corporate version of CLA

### ISSUE THREAD

**Issue by flapenguin** [microsoft/TypeScript#27967]
Is there a corporate version of [CLA](https://cla.opensource.microsoft.com/Microsoft/TypeScript)?

**Comment by RyanCavanaugh** [comment]
I'm not sure what you mean -- section 4 already covers work any individual might do on behalf of their employer. If a corporation itself has a GitHub account "they" can sign that form on behalf of themselves.

**Comment by flapenguin** [comment]
Thank you, this answers my question. Some companies have separate version for company-company contract.

**Comment by xCounsel** [comment]
Hi Ryan. 

Let me clarify this our question. As you know, companies may have CLAs of both types: for individual contributors and companies (see e.g. the examples at [Canonical](https://www.ubuntu.com/legal/contributors/submit), [FB](https://code.facebook.com/cla) and [Google](https://cla.developers.google.com/clas)). 

Our question was following: 
Do you have different CLAs (for individuals and companies) or the single CLA only (which both individuals on their own behalf and authorized employees on the behalf of their companies may sign)?

If you have both types, we need to read the CLA for companies.
If you have the single CLA, the question is closed.

**Comment by flapenguin** [comment]
Anyone?

**Comment by DanielRosenwasser** [comment]
Let me get back to you on this.

**Comment by xCounsel** [comment]
OK, will wait the news from you.
