### ISSUE TITLE
compiler issue with calling method overloads

### ISSUE THREAD

**Issue by niemyjski** [Microsoft/TypeScript#2796]
I'm trying to do method overloads and it's working great except for the call to `var result = this.createLog2(source, message, level);` is causing a compile time error:

```
2346 Supplied parameters do not match any signature of call target.
```

```typescript
public createLog(message:string): number;
public createLog(source:string, message:string): number;
public createLog(source:string, message?:string, level?:string): number {
  return 0;
}

public submitLog(message:string): void;
public submitLog(source:string, message:string): void;
public submitLog(source:string, message?:string, level?:string): void {
  var result = this.createLog(source, message, level);
}
```

Any ideas?

**Comment by niemyjski** [comment]
I was able to get this to work if I do this.. This seems like a huge hack!

```typescript
public createLog(message:string): number;
public createLog(source:string, message:string): number;
public createLog(source:string, message:string, level:string): number;
public createLog(source:string, message?:string, level?:string): number{
return 0;
}

public submitLog(message:string): void;
public submitLog(source:string, message:string): void;
public submitLog(source:string, message:string, level:string): void;
public submitLog(source:string, message?:string, level?:string): void {
  var result = this.createLog(source, message, level);
}
```

**Comment by mhegazy** [comment]
your solution is correct. the method implementation is not considered an overload. so you need to explicitly add a method signature for every supported way of calling your method.

This allows you to have an implementation be less specific: 
```ts
public createLog(message:string): number;
public createLog(source:string, message:string): number;
public createLog(source:string, message:string, level:string): number;
public createLog(...args): number {
  return 0;
}
```

for more information see the [function overloads](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#62-function-overloads) section in the spec.

**Comment by niemyjski** [comment]
That doesn't seem straight forward... Can this be changed... It also removes the amount of boilerplate..

**Comment by mhegazy** [comment]
Changing this would be a huge breaking change. it is also not clear how you would achieve hiding the implementation signature..

The implementation signature has to be generic enough to fit all overload signatures, so with something like:
```ts
function compare(a: string, b: string): void;
function compare(a: number, b: number): void;
function compare(a: string|number, b: string|number): void {

}
```
Now, if you include the implementation as an overload, i can call this function with `compare(1, "s")` that is clearly not the intent. I do not see how you would get that scenario working otherwise.

**Comment by niemyjski** [comment]
Yeah, I see your point, but in my scenario it's just extra unneeded code.

**Comment by DanielRosenwasser** [comment]
It would inevitably be even more surprising to introduce cases where the implementation signature *does* introduce an overload while keeping the current behavior in other cases.

**Comment by danquirk** [comment]
There are good language design reasons for this rule. However it does feel onerous sometimes to type it out. This is precisely where an IDE could help with some sort of snippet/generation.
