### ISSUE TITLE
Completion in reference comments and imports

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#2799]
```TypeScript
/// <reference path="
```

If requesting completion here, we should get `.`, `..`, and any `.ts` files at the current directory location.

If requesting completion after a `\` or `/` in the path, if the path up until the last `/` or `\` is valid, we should get `.`, `..` and any `.ts` files in that path.

**Comment by danquirk** [comment]
Absolutely. I get this today in Sublime via https://github.com/BoundInCode/AutoFileName. It's handy even outside ///.

**Comment by NoelAbrahams** [comment]
Is this the same as #188?

**Comment by DanielRosenwasser** [comment]
Thanks for the heads up @NoelAbrahams - looks like @ahmad-farid is already assigned this task.
