### ISSUE TITLE
hope can allow force emit a value as function

### ISSUE THREAD

**Issue by bluelovers** [Microsoft/TypeScript#28018]
## Suggestion

hope can have something `@ts-emit-declare-function` for emit a value as function 

## Use Cases

just wanna a function type is a function , not a value

## Examples

```ts
// @ts-emit-declare-function
export const r2 = Math.random
```

### Expected behavior:

```ts
export declare function r2(): number;
```

### Actual behavior:

```ts
export declare const r2: () => number;
```

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by mattmccutchen** [comment]
Why do you care whether the declaration file says `export declare const r2: () => number;` or `export declare function r2(): number;`?  Note that you can always write a wrapper function if you don't mind duplicating the parameter types:
```ts
const r2_1 = Math.random;
export function r2() {
  return r2_1();
}
```

**Comment by bluelovers** [comment]
@markusjohnsson i know, but i don't wanna wrap it ( if can
when use wrap, it will lost type signatures when target function has more than one signatures

**Comment by mattmccutchen** [comment]
Why do you care whether the declaration file says `export declare const r2: () => number;` or `export declare function r2(): number;`?  Unless you have a good reason, I doubt this suggestion is going anywhere.

**Comment by bluelovers** [comment]
this make ide can know it is callable value or is a function
when using ide

![default](https://user-images.githubusercontent.com/167966/47273410-94b60d80-d5c6-11e8-91ba-93d4a16af498.png)

**Comment by weswigham** [comment]
Hmmmm I'd complain to your ide's color scheme implementation. A function-typed value augta be able to be displayed in the "callable" color, too, imo.
