### ISSUE TITLE
Using the switched variable in an if statement causes an error.

### ISSUE THREAD

**Issue by Pixelatedza** [microsoft/TypeScript#28016]
**TypeScript Version:**  3.1

**Search Terms:** switch, if, switch this

**Code**

```typescript
class MyClass{
  myString: string;

  setString() {
    this.myString = "c";
  }

  doSomeSwitching() {
    switch (this.myString) {
      case "a":
        this.setString();
        if (this.myString == "c") {

        }
        break;
      default:
        break;
    }
  }
}
```

**Expected behavior:**
I would expect no error.

**Actual behavior:**
An error is generated for the if statement.

if (this.myString == "c")
*This condition will always return 'false' since the types '"a"' and '"c"' have no overlap.*

The code above is the simplest form. In real use I was creating a parser. Using an instance variable to step through tokens. I check the token type with the case and then "eat" the token. The instance variable is then changed after which I want to check the token again.

**Playground Link:**
[Link](https://www.typescriptlang.org/play/#src=class%20MyClass%7B%0D%0A%20%20myString%3A%20string%3B%0D%0A%0D%0A%20%20setString()%20%7B%0D%0A%20%20%20%20this.myString%20%3D%20%22c%22%3B%0D%0A%20%20%7D%0D%0A%0D%0A%20%20doSomeSwitching()%20%7B%0D%0A%20%20%20%20switch%20(this.myString)%20%7B%0D%0A%20%20%20%20%20%20case%20%22a%22%3A%0D%0A%20%20%20%20%20%20%20%20this.setString()%3B%0D%0A%20%20%20%20%20%20%20%20if%20(this.myString%20%3D%3D%20%22c%22)%20%7B%0D%0A%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%20%20%20%20break%3B%0D%0A%20%20%20%20%20%20default%3A%0D%0A%20%20%20%20%20%20%20%20break%3B%0D%0A%20%20%20%20%7D%0D%0A%20%20%7D%0D%0A%7D)

**Related Issues:** I couldn't find anything that looked like this. Honestly I was mostly looking at the examples they gave since I'm not sure what many of the big words mean.

**Comment by Pixelatedza** [comment]
Nice, I didn't think of doing that. I found that any assignment will make it happy. So you don't even have to mess with the function.

```typescript
class MyClass{
  myString: string;

  setString() {
    this.myString = "c";
  }

  doSomeSwitching() {
    switch (this.myString) {
      case "a":
        this.setString();
        this.myString = this.myString; // <-- Adding this takes the error away.
        if (this.myString == "c") {

        }
        break;
      default:
        break;
    }
  }
}
```

**Comment by ahejlsberg** [comment]
This is a design limitation. See discussion in #9998.

**Comment by fatcerberus** [comment]
Is there any real-world benefit to the type being narrowed to a literal inside the cases?
