### ISSUE TITLE
Adding overloads breaks return type inference

### ISSUE THREAD

**Issue by fatcerberus** [microsoft/TypeScript#28021]
Adding overloads to a function for which type inference has correctly inferred its return type seems to cause it to be inferred as returning `any` instead, even leading to an error if `--noImplicitAny` is used.  The only solution appears to be to manually annotate all overloads, which is frustrating since type inference works correctly without them.

Based on the fact that `tsc` specifically highlights the *overloads* in the implicit-any errors, this leads me to believe it's trying to do type inference on the overloads individually (which will never work since they have no body) instead of just using the return type of the single implementation.

**TypeScript Version:**  3.2.0-dev.20181020

**Search Terms:** overload return type inference

**Code**
```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.

let x = 0;

function foo();
function foo(param1: any, param2: any);
function foo(param1?: any, param2?: any) {
    return x++;
}
```

**Command line**
```
tsc --noImplicitAny repro.ts
```

**Expected behavior:**
No error, `foo()` and all overloads are inferred as returning number and all is right with the world.

**Actual behavior:**
`tsc` produces the following diagnostic:
```
repro.ts:3:10 - error TS7010: 'foo', which lacks return-type annotation, implicitly has an 'any' return type.

3 function foo();
           ~~~

repro.ts:4:10 - error TS7010: 'foo', which lacks return-type annotation, implicitly has an 'any' return type.

4 function foo(param1: any, param2: any);
           ~~~
```

**Playground Link:** 
http://www.typescriptlang.org/play/#src=let%20x%3A%20number%20%3D%200%3B%0D%0A%0D%0A%2F*%20uncomment%20the%20two%20commented%20lines%20below%20to%20see%20the%20issue.%0D%0A%20*%0D%0A%20*%20TypeScript%20tries%20to%20infer%20return%20type%20for%20each%20overload%20individually%2C%20instead%20of%20just%0D%0A%20*%20using%20the%20correctly-inferred%20return%20type%20of%20the%20implementation.%20%20this%20causes%20a%20compiler%20error%0D%0A%20*%20with%20%60--noImplicitAny%60.%0D%0A%20*%2F%0D%0A%0D%0A%2F%2F%20function%20foo()%3B%0D%0A%2F%2F%20function%20foo(param1%3A%20any%2C%20param2%3A%20any)%3B%0D%0Afunction%20foo(param1%3F%3A%20any%2C%20param2%3F%3A%20any)%20%7B%0D%0A%20%20%20%20return%20x%2B%2B%3B%0D%0A%7D%0D%0A

**Related Issues:** 
#13780

**Comment by mattmccutchen** [comment]
It's a general rule that if the return type of a function declaration (that isn't coupled to an implementation) isn't specified, it defaults to `any`; this applies to `declare function`, interfaces, etc.  I assume overload signatures are just following this rule.  I guess your suggestion is that overload signatures should instead default to the (annotated or inferred) return type of the implementation signature.  This would be a potentially breaking change but might be worthwhile.

**Comment by fatcerberus** [comment]
Yeah, that's pretty much it.  It seemed to me like one of TypeScript's goals was to try to infer types wherever it was possible to do so, so I expected it to work for overloads too.

My particular case was this bit of code:
```js
	addJob(type: JobType, callback: () => void, recurring?: false, delay?: number): number;
	addJob(type: JobType, callback: () => void, recurring: true): number;
	addJob(type: JobType, callback: () => void, recurring = false, delay = 0)
	{
		this.jobQueue.push({ jobID: nextJobID, type, callback, recurring, timer: delay });
		return nextJobID++;
	}
```
If I later decide to make `addJob()` here return something other than a number, I have to remember to change the annotations on the overloads, even if the type has been correctly inferred for the implementation--in practice this means the minute I add an overload to any function, I lose all the benefits of return type inference.


> coupled to an implementation

This is the interesting bit: Since overload declarations are tied to a single implementation by definition (not providing one will cause a compile-time error), they therefore *are* logically coupled in this way, it would make most sense to use the implementation as a source for return type inference.  I don't know how difficult that would be implementation-wise, though.

**Comment by weswigham** [comment]
I think we're pretty firmly in the camp of requiring overload signatures have return types at this point, so I'm going to close this suggestion. :)
