### ISSUE TITLE
Type safety lost after build with tsc.

### ISSUE THREAD

**Issue by ericwooley** [microsoft/TypeScript#28029]
**TypeScript Version:**  3.1.3

**Search Terms:**
build all after tsc loses type inference

**Code**

```ts
// unable to reproduce in a single code snippet
```

**Expected behavior:**
code built with tsc and used in an npm module retains the same type inferences.

**Actual behavior:**
After building a module, then depending on it in another package, type information is lost:

I setup two files to be as close as possible, one inside the project directory, and one inside a package that depends on my module.

*type safety is retained*
https://github.com/ericwooley/action-packed-react/blob/typescript-build-problem/action-packed-react/src/integration.test.tsx#L57

*types reverts to any.*
https://github.com/ericwooley/action-packed-react/blob/typescript-build-problem/demo/src/index.tsx#L58

**additional information**
I tried switching to 3.0.x and the issue still occurs, 

I tried with typescript@next, but it was broken for other things, preventing the test.

**Comment by mattmccutchen** [comment]
Minimal example:
```ts
// Compile with: tsc --strict --declaration code.ts; tsc code2.ts

// code.ts
function f() {
    return () => f();
}
console.log(f()().foo);  // Error, as expected

// code2.ts
///<reference path="code.d.ts"/>
console.log(f()().foo);  // No error
```
`f` has a self-referential type, which seems to work fine within a single project, but it emits with an `any` in a declaration file (and also appears with an `any` in the hover).

**Comment by mattmccutchen** [comment]
Looks like a duplicate of #22192.  That one was closed as "design limitation".  I think a design that is incapable of even reporting an error in this situation deserves redesign, but it's not like it matters what I think if I'm not signing up to do the work. :frowning_face:

**Comment by ericwooley** [comment]
@mattmccutchen 

Thanks for the tip, I'll give that a shot tonight. I should have thought to explicitly return that type. 

I agree that there is definitely an issue with the any no erroring since both projects have no implicit any on, and all the strict null checks, yet any just appears out of no where. But like you, i'm not doing the work just benifiting from it. I'll play with this tonight, and probably close this issue since you found a duplicate. 

Thanks a million.

**Comment by weswigham** [comment]
It'd be nice to fix it at least in the case of the simpler examples in this thread.

**Comment by ericwooley** [comment]
This seems to be fixed after upgrading TS, and the issue it was a near duplicate of is closed, so I figure this can probably be closed as well.

Feel free if you guys want this reopened though.
