### ISSUE TITLE
Control Flow narrows  X | undefined to never without checking arrow function

### ISSUE THREAD

**Issue by unional** [microsoft/TypeScript#28038]
TypeScript: 3.1.3

```ts
function foo(cb) {
  cb()
}

let h: { a: 1 } | undefined = undefined // required to reproduce this bug
foo(() => h = {} as any)
if (h) {
  console.log(h.a) // <-- h is of type `never`
}
```

[PlayGround](http://www.typescriptlang.org/play/index.html#src=function%20foo(cb)%20%7B%0A%20%20cb()%0A%7D%0A%0Alet%20h%3A%20%7B%20a%3A%201%20%7D%20%7C%20undefined%20%3D%20undefined%0Afoo(()%20%3D%3E%20h%20%3D%20%7B%7D%20as%20any)%0Aif%20(h)%20%7B%0A%20%20console.log(h.a)%0A%7D%0A)

This happens when `strictNullChecks` is on.

**Comment by jack-williams** [comment]
Related #9998

**Comment by ahejlsberg** [comment]
This is a design limitation. See discussion in #9998.

**Comment by unional** [comment]
Thanks for the info! As long as this is known, I'm happy about it. 🌷
