### ISSUE TITLE
for..of with iterator does not working in Internet Explorer

### ISSUE THREAD

**Issue by acrazing** [Microsoft/TypeScript#28030]
**TypeScript Version:**  3.1.3

**Search Terms:**

**Code**

```ts
import { observable } from 'mobx'
import assert from 'assert'

const map = observable.map<string, string>()
map.set('foo', 'bar')
for(const key of map.keys()) {
  assert(key === 'foo')
}
```

**Expected behavior:**

No error in any browser

**Actual behavior:**

Only works in browsers support `Symbol.iterator`, in other browsers, it will fall into infinite loops with the variable `key` equals to `undefined` if not throw throw error.

**Playground Link:** 

**Related Issues:**

**Comment by ajafff** [comment]
TypeScript doesn't change the runtime behavior of your code. If you intend to use the iteration protocol in runtimes that don't support it, you need to make sure to include a polyfill if necessary.
