### ISSUE TITLE
Auto Import importing symbols for function arguments 

### ISSUE THREAD

**Issue by mohsen1** [Microsoft/TypeScript#28035]
When defining a function TypeScript it trying to import suggestions which never makes sense. 

I like the suggestions themselves. I just don't want them to get imported.  

**TypeScript Version:**  3.2.0-dev.20181020

**Search Terms:**
Auto import, suggestion, functions

**Code**
```ts
function foo() {
    return new Promise<string>((resolve))
   //                                  ^__ here
}
```

**Playground Link:** 
![bug](https://user-images.githubusercontent.com/543633/47274410-deb4da00-d559-11e8-8b23-a0e3e04e3c35.gif)

**Related Issues:**

**Comment by ajafff** [comment]
At this point typescript cannot know that you intend to write an arrow function. It could also be a variable wrapped in parentheses.
