### ISSUE TITLE
Can't type the fake `this` parameter when overloading functions

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/TypeScript#28036]
**TypeScript Version:**  3.2.0-dev.201xxxxx

**Search Terms:** this parameter overloading

**Code**

```ts
class Cash {}

interface Cash {
  text (): string;
  text ( text: string ): this;
}

Cash.prototype.text = function ( this: Cash, text?: string ) {
  return text === undefined ? 'foo' : this;
};
```

**Expected behavior:**

No errors.

**Actual behavior:**

There's an error, it says that `'Cash' is not assignable to 'string'`. If I remove the `this` fake parameter it works, am I doing something wrong here?

**Playground Link:** 

[Here](http://www.typescriptlang.org/play/#src=class%20Cash%20%7B%7D%0A%0Ainterface%20Cash%20%7B%0A%20%20text%20()%3A%20string%3B%0A%20%20text%20(%20text%3A%20string%20)%3A%20this%3B%0A%7D%0A%0ACash.prototype.text%20%3D%20function%20(%20this%3A%20Cash%2C%20text%3F%3A%20string%20)%20%7B%0A%20%20return%20text%20%3D%3D%3D%20undefined%20%3F%20'foo'%20%3A%20this%3B%0A%7D%3B).

**Related Issues:** Not that I could find

**Comment by csvn** [comment]
I am not overly familiar with declaration merging and overloading of functions, but writing this inside the same class produces no errors. 

```ts
class Cash {
  text(): string;
  text(text: string): this;
  text(text?: string | undefined): string | this {
    return text === undefined ? 'foo' : this;
  }
}
```
[Playgorund link](http://www.typescriptlang.org/play/#src=class%20Cash%20%7B%0A%20%20text()%3A%20string%3B%0A%20%20text(text%3A%20string)%3A%20this%3B%0A%20%20text(text%3F%3A%20string%20%7C%20undefined)%3A%20string%20%7C%20this%20%7B%0A%20%20%20%20return%20text%20%3D%3D%3D%20undefined%20%3F%20'foo'%20%3A%20this%3B%0A%20%20%7D%0A%7D%0A)

**Comment by fabiospampinato** [comment]
@csvn you're typing the fake `this` parameter though.

**Comment by fabiospampinato** [comment]
It wasn't a problem of the language https://stackoverflow.com/questions/52921185/typing-this-parameters-in-overloaded-function-involving-declaration-merging?noredirect=1#comment92751900_52921185
