### ISSUE TITLE
The "Add missing enum member" fixer clones all comments above the enum

### ISSUE THREAD

**Issue by Yuudaari** [microsoft/TypeScript#28031]
**TypeScript Version:**  3.2.0-dev.20181020

**Search Terms:** missing enum member comments clone duplicate

**Code**

```ts
// some comments
// wow
enum CoolEnum {
	Foo,
	Bar
}

CoolEnum.Baz
```

**Expected behavior:**
Using the "add missing enum member" fixer on `CoolEnum.Baz` should add the missing enum member.

**Actual behavior:**
It does that, but it also clones the comments, so the file is now:
```ts
// some comments
// wow
// some comments
// wow
enum CoolEnum {
	Foo,
	Bar,
	Baz
}

CoolEnum.Baz
```

One file in a codebase I work in ended up with 513 lines of comments before we noticed. 🤔

**Comment by fatcerberus** [comment]
That's kind of amusing, but also pretty annoying I imagine.

**Comment by sharebear** [comment]
This looked like an easy Hacktober issue, so decided I would take a look. It was trivial to create a failing test case and from there I took a slight guess as to the best solution based on comments in the code.

**Comment by Yuudaari** [comment]
@sharebear I assume it does, but figure I should ask just in case: Does your fix also work w/ other kinds of comments? The duplication happens for any number of any kind of comment above the enum when the enum is preceded by any kind of comments, including JSDoc comments & block comments as well

**Comment by sharebear** [comment]
I assume it does based upon the documentation of `ConfigurableStartEnd` options that I set 

```
    /**
     * Usually node.pos points to a position immediately after the previous token.
     * If this position is used as a beginning of the span to remove - it might lead to removing the trailing trivia of the previous node, i.e:
     * const x; // this is x
     *        ^ - pos for the next variable declaration will point here
     * const y; // this is y
     *        ^ - end for previous variable declaration
     * Usually leading trivia of the variable declaration 'y' should not include trailing trivia (whitespace, comment 'this is x' and newline) from the preceding
     * variable declaration and trailing trivia for 'y' should include (whitespace, comment 'this is y', newline).
     * By default when removing nodes we adjust start and end positions to respect specification of the trivia above.
     * If pos\end should be interpreted literally 'useNonAdjustedStartPosition' or 'useNonAdjustedEndPosition' should be set to true
     */
```

My fix was to set `useNonAdjustedStartPosition` to false.
