### ISSUE TITLE
Let-binding (let ... in)

### ISSUE THREAD

**Issue by malthe** [Microsoft/TypeScript#28039]
## Search Terms

- Let-binding
- "Let ... in"

## Suggestion

Add "let ... in" construct as seen in ML-family languages.

## Use Cases

The ternary operator is the next best thing to an expression-level "if-else" – see #10841. But it's impeded by not having a way to structure initialization before either expression.

## Example

```typescript
const a = b ? let c = d in (e) => { c(e) } : f;
```
This would transpile to something like the following JavaScript:
```javascript
var a = b ? (function() {
    var c = d;
    return function(e) {
        return c(e);
    }
}) : f;

```

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by dragomirtitian** [comment]
It is new expression-level syntax (ie it's syntax that impacts expressions). If JavaScript chooses to implements something similar or use the let keyword for another propose this would break the Typescript is a superset of JavaScript goal. Typescript is generally very conservative when adding syntax that could potentially break this design goal, generally only adding expression-level syntax that is slated for inclusion in JS standards or very limited things like ! for not null assertion or type assertions.
