### ISSUE TITLE
[discussion] dynamic merge properties to type(or interface) by its specific key

### ISSUE THREAD

**Issue by pd4d10** [Microsoft/TypeScript#28041]
Actually it is a question, but I think it may refers to type system of TypeScript, so I post it here.

The problem is **how to dynamic merge properties to type(or interface) by its specific key**.

Assuming we are creating a React component named `Button`. It takes a `component` prop, and will use this value as component actually rendered. Its implementation may looks like this:

```ts
interface ButtonProps {
  component: keyof React.ReactHTML
}

class Button extends React.Component<ButtonProps> {
  render() {
    const { component: Component, ...rest } = this.props
    // give it a button style
    // `component`'s value could be button, a, input, etc
    return <Component {...rest} />
  }
}
```

we need native HTML element's props merged to `ButtonProps`.

For example, the usage examples below should be all type safe.

```ts
<Button component="button" type="submit">A Button</a>
<Button component="a" href="/">A Link Button</a>
<Button component="input" type="submit" value="An input button" />
```

Which means, if `component === 'a'`, `ButtonProps` should be

```ts
{ component: React.ReactHTML } & React.AnchorHTMLAttributes<HTMLAnchorElement>
```

if `component === 'input'`, `ButtonProps` should be

```ts
{ component: React.ReactHTML } & React.InputHTMLAttributes<HTMLInputElement>
```

How to figure this out in TypeScript?

**Comment by pd4d10** [comment]
My thoughts:

```ts
type PropsOfHtmlTag<T extends keyof React.ReactHTML> =
React.ReactHTML[T] extends React.DetailedHTMLFactory<infer R, any>
  ? R
  : never

interface ButtonProps {
  component: keyof React.ReactHTML
}

type DynamicProps = PropsOfHtmlTag<ButtonProps['component']>
```

What we need is to merge `ButtonProps` and `DynamicProps`

**Comment by andy-ms** [comment]
I think this is possible:
```ts
import * as React from "React";

type AttributesForTag = { [K in keyof React.ReactHTML]: React.ReactHTML[K] extends React.DetailedHTMLFactory<infer Attr, any> ? Attr : never; };

class Button<K extends keyof AttributesForTag> extends React.Component<{ component: K } & AttributesForTag[K]> {
    render() {
        const { component, ...rest } = this.props as any;
        return React.createElement(component, rest);
    }
}

const x = <Button component="button" type="submit" />
```

Is it also possible to just make the element be one of the props?
```ts
class Button2 extends React.Component<{ component: JSX.Element }> {
    render() { return this.props.component; }
}
<Button2 component={<button type="submit" />} />
```

**Comment by pd4d10** [comment]
@andy-ms Thanks for your response. I tried your example in VSCode:

<img width="728" alt="2018-10-23 10 47 53" src="https://user-images.githubusercontent.com/9524411/47332228-3dd93280-d6b1-11e8-86fb-88520db678e5.png">

Since HTML tag `a` has no `value`, I think the last line should throw an error but not. Tried to go to `value` key's definition then it shows:

<img width="599" alt="2018-10-23 10 55 07" src="https://user-images.githubusercontent.com/9524411/47332513-1fc00200-d6b2-11e8-9e36-f0cd2f9d12ab.png">

Seems it merges all HTML tags' attributes? Then we got multiple definitions

**Comment by nkappler** [comment]
it works for me:

![image](https://user-images.githubusercontent.com/9429273/47364332-52c9bc00-d6d9-11e8-83b1-0fb8d6c00242.png)

**Comment by andy-ms** [comment]
@pd4d10 Darn, it must be inferring `K = string` and allowing all elements. This has come up before, see  #27808. You'll at least get correct behavior if you remember to provide an explicit type argument: `<Button<"a"> component="a" value="submit" />;`.

**Comment by pd4d10** [comment]
@nkappler @andy-ms Thanks. Closing since the question is answered clearly
