### ISSUE TITLE
Type different based on whether it's imported or not

### ISSUE THREAD

**Issue by G2Jose** [Microsoft/TypeScript#28045]
**TypeScript Version:**  3.0.3

**Search Terms:** Wrong type when importing object & using `keyof typeof` 

The type of an object seems to be different depending on where it's defined - if it's defined in the same file as a type alias, or if it's imported from another file

**Code**
```ts
// file1.ts
export const obj = {
  k1: 'v1',
  k2: 'v2',
}
```
**Expected behavior:**
```ts
// file2.ts
import { obj } from 'file1'
type Key = keyof typeof obj // "k1" | "k2"
```
**Actual behavior:**
```ts
// file2.ts
import { obj } from 'file1'
type Key = keyof typeof obj // string | number
```
However, the same code in one file, without importing `obj` into another file gives me the right type:
```ts
const obj = {
  k1: 'v1',
  k2: 'v2',
}
type Key = keyof typeof obj // "k1" | "k2"
```

**Playground Link:**  N/A

**Related Issues:**  N/A

**Comment by andy-ms** [comment]
The import is probably failing. I suspect if you write `type T = typeof obj;` it will show as  `any`. I notice you're using a non-relative import `'file1'` -- use [`traceResolution`](https://www.typescriptlang.org/docs/handbook/compiler-options.html) to see where that looks for imports. Also see the [module resolution](https://www.typescriptlang.org/docs/handbook/module-resolution.html) docs.
Of course the solution might just be to write `./file1` instead.
A failed import should always be an error in TS code (except for statement import `import "blah";`), so I'm wondering why the error isn't showing for you...
Also be sure to test with [`typescript@next`](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions).

**Comment by G2Jose** [comment]
I think I see what the issue is - file1 is actually a javascript `file1.js` file. Importing it into `file2.ts` causes it to have a type definition
```
 {
    [x: string]: any;
    k1: string;
    k2: string;
}
```
Renaming `file1.js` to `file1.ts` causes the import to have the expected typing 
```
{
    k1: string;
    k2: string;
}
```
Is this documented behaviour?
