### ISSUE TITLE
A bit confused about the code which in docs/handbook/interface.html

### ISSUE THREAD

**Issue by hello-chenchen** [Microsoft/TypeScript#28044]
Actually, I am a newbie to typescript and I am learning it. I think maybe there is a bit problem in your handbook about the example code of interface.
I am reading the handbook of it, and I am a bit confused about the code below:
http://www.typescriptlang.org/docs/handbook/interfaces.html
there are some example code in interface.html to describe methods in an interface:
```typescript
interface ClockInterface {
    currentTime: Date;
    setTime(d: Date);
}

class Clock implements ClockInterface {
    currentTime: Date;
    setTime(d: Date) {
        this.currentTime = d;
    }
    constructor(h: number, m: number) { }
}
```

when i try to compile the above code.
there is an error:
src/main.ts(3,5): error TS7010: 'setTime', which lacks return-type annotation, implicitly has an 'any' return type.

And as a java developer, i think return a type should be better like below:
```typescript
interface ClockInterface {
    currentTime: Date;
    setTime(d: Date) : void;
}

class Clock implements ClockInterface {
    currentTime: Date;
    setTime(d: Date) {
        this.currentTime = d;
    }
    constructor(h: number, m: number) { }
}
```

Content is just for reference only.

**Comment by j-oliveras** [comment]
You, probably have `strict: true` or `noImplicitAny: true` at `tsconfig.json`. The sample is wrote before these flags are added.

**Comment by hello-chenchen** [comment]
> noImplicitAny

Thank U for your comments, and for your comments, can i think that "return a type" should be a better way?
Actually, the reason i try typescript to replace javascript is that i think the syntax of typescript is more strict and normative(although, it is no different after compiled).
