### ISSUE TITLE
Creating types from values in array

### ISSUE THREAD

**Issue by G2Jose** [microsoft/TypeScript#28046]
**TypeScript Version:**  3.0.3

**Search Terms:** Type based on values in array 

Is there a current or planned feature to create a type from strings in an array?

**Code**
```ts
const values = ['A', 'B']
type Foo = OneOf<values> // Is there a way of doing this?

const v1: Foo = 'A' // This should work
const v2: Foo = 'D' // This should give me an error since 'D' doesn't exist in values
```
Similar to how `keyof` works: 
```ts
const values = {
  A: 'A',
  B: 'B'
}
type Foo = keyof typeof values
const v1: Foo = 'A'
const v2: Foo = 'D' // Type '"D"' is not assignable to type '"A" | "B"'
```

**Related Issues:**  https://github.com/Microsoft/TypeScript/issues/20965

**Link to playground** http://www.typescriptlang.org/play/#src=let%20vals1%20%3D%20%5B'A'%2C%20'B'%5D%0D%0Atype%20Foo1%20%3D%20OneOf%3Cvals1%3E%20%2F%2F%20Is%20there%20a%20way%20of%20doing%20this%3F%0D%0A%0D%0Alet%20v1%3A%20Foo1%20%3D%20'A'%20%2F%2F%20This%20should%20work%0D%0Alet%20v2%3A%20Foo1%20%3D%20'D'%20%2F%2F%20This%20should%20give%20me%20an%20error%20since%20'D'%20doesn't%20exist%20in%20values%0D%0A%0D%0Alet%20vals2%20%3D%20%7B%0D%0A%20%20A%3A%20'A'%2C%0D%0A%20%20B%3A%20'B'%0D%0A%7D%0D%0Atype%20Foo2%20%3D%20keyof%20typeof%20vals2%0D%0Alet%20v3%3A%20Foo2%20%3D%20'A'%0D%0Alet%20v4%3A%20Foo2%20%3D%20'D'%20%2F%2F%20Type%20'%22D%22'%20is%20not%20assignable%20to%20type%20'%22A%22%20%7C%20%22B%22'

**Comment by fatcerberus** [comment]
`keyof` only works because it uses information known statically at compile time.  Types in TS are fully erasable and don't exist in the transpiled code, so it's simply not possible to create a type based on the runtime contents of an array.

**Comment by andy-ms** [comment]
This is possible:
```ts
function stringLiterals<T extends string>(...args: T[]): T[] { return args; }
type ElementType<T extends unknown[]> = T extends [...(infer ElementType)[]] ? ElementType : never;

const values = stringLiterals('A', 'B');
type Foo = ElementType<typeof values>;

const v1: Foo = 'A' // This should work
const v2: Foo = 'D' // This should give me an error since 'D' doesn't exist in values
```

Definitely not clear how to do this though. #27179 is related.

**Comment by fatcerberus** [comment]
That’s still using information known statically by the compiler though; at that point I don’t understand what the advantage is over just saying `”A” | “B”`.

**Comment by andy-ms** [comment]
@fatcerberus It's useful to avoid repeating information -- if you just write `const values = ["A", "B"]; type Foo = "A" | "B";` it's easy for someone to change one of them while forgetting to change the other. You could write `const values: Foo[] =["A", "B"];`, but that's still susceptible to adding an additional entry to `Foo` and forgetting to put it in `values`.

**Comment by ChibiBlasphem** [comment]
Like @andy-ms said it would be really useful to avoid repeating information manually.
And like @fatcerberus said, types are fully erasabled. We sometimes need to runtime check data we get for example from a non pure part of application (like webservice, or from the user).

**Comment by drop-george** [comment]
Building on @andy-ms's  [answer](https://github.com/Microsoft/TypeScript/issues/28046#issuecomment-431871542), and using [const assertions](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#const-assertions) introduced in typescript 3.4, it's now possible to do something like this
```
const values = ['A', 'B'] as const
type ElementType < T extends ReadonlyArray < unknown > > = T extends ReadonlyArray<
  infer ElementType
>
  ? ElementType
  : never

type Foo = ElementType<typeof values> // this is correctly inferred as literal "A" | "B"

```

**Comment by 7kms** [comment]
in ts@3.x and above.  solve it like this

```typescript
export const type = <const>[
  'room',
  'room_with_gifter',
  'user_send'
];

export interface Activity {
  id?: string;
  type: typeof type[number];
}
```

**Comment by AmirSavand** [comment]
Instead of this:

```ts
export const type = <const>[
  'room',
  'room_with_gifter',
  'user_send'
];

export interface Activity {
  id?: string;
  type: typeof type[number];
}
```

You can do this:

```ts
export const type = [
  'room',
  'room_with_gifter',
  'user_send'
] as const;

export type type = typeof type;

export interface Activity {
  id?: string;
  type: type;
}
```

_Really don't like using `type` as a variable name._

**Comment by vegerot** [comment]
@7kms 

> in [ts@3.x](mailto:ts@3.x) and above. solve it like this
> 
> ```ts
> export const type = <const>[
>   'room',
>   'room_with_gifter',
>   'user_send'
> ];
> 
> export interface Activity {
>   id?: string;
>   type: typeof type[number];
> }
> ```

Now what if I have this in a class?

```typescript
class Class {
  const list = <const>[
   'room',
   'room_with_gifter',
   'user_send'
 ];

 const withType: typeof list[number];
}
```

Does not work.  I also cannot do `this.list[number]`.  Also, for my particular
usecase, I cannot set `list` to be `static`

**Comment by mintapp** [comment]
> 
> 
> @7kms
> 
> > in [ts@3.x](mailto:ts@3.x) and above. solve it like this
> > ```ts
> > export const type = <const>[
> >   'room',
> >   'room_with_gifter',
> >   'user_send'
> > ];
> > 
> > export interface Activity {
> >   id?: string;
> >   type: typeof type[number];
> > }
> > ```
> 
> Now what if I have this in a class?
> 
> ```ts
> class Class {
>   const list = <const>[
>    'room',
>    'room_with_gifter',
>    'user_send'
>  ];
> 
>  const withType: typeof list[number];
> }
> ```
> 
> Does not work. I also cannot do `this.list[number]`. Also, for my particular
> usecase, I cannot set `list` to be `static`

@vegerot You can't use `const` directly in the scope of the `class`.

**Comment by eyalch** [comment]
> 
> 
> @7kms
> 
> > in [ts@3.x](mailto:ts@3.x) and above. solve it like this
> > ```ts
> > export const type = <const>[
> >   'room',
> >   'room_with_gifter',
> >   'user_send'
> > ];
> > 
> > export interface Activity {
> >   id?: string;
> >   type: typeof type[number];
> > }
> > ```
> 
> Now what if I have this in a class?
> 
> ```ts
> class Class {
>   const list = <const>[
>    'room',
>    'room_with_gifter',
>    'user_send'
>  ];
> 
>  const withType: typeof list[number];
> }
> ```
> 
> Does not work. I also cannot do `this.list[number]`. Also, for my particular
> usecase, I cannot set `list` to be `static`

@vegerot You can't use `const` directly in the scope of the `class`, so the syntax is incorrect.

**Comment by vegerot** [comment]
> > @7kms
> > > in [ts@3.x](mailto:ts@3.x) and above. solve it like this
> > > ```ts
> > > export const type = <const>[
> > >   'room',
> > >   'room_with_gifter',
> > >   'user_send'
> > > ];
> > > 
> > > export interface Activity {
> > >   id?: string;
> > >   type: typeof type[number];
> > > }
> > > ```
> > 
> > 
> > Now what if I have this in a class?
> > ```ts
> > class Class {
> >   const list = <const>[
> >    'room',
> >    'room_with_gifter',
> >    'user_send'
> >  ];
> > 
> >  const withType: typeof list[number];
> > }
> > ```
> > 
> > 
> > Does not work. I also cannot do `this.list[number]`. Also, for my particular
> > usecase, I cannot set `list` to be `static`
> 
> @vegerot You can't use `const` directly in the scope of the `class`, so the syntax is incorrect.

@7kms My bad.  I copied and pasted too much.  What I meant to say is 
```typescript
class Class {
  private list = <const>[
   'room',
   'room_with_gifter',
   'user_send'
 ];

 private withType: typeof list[number];

// OR
  private withType2: typeof this.list[number];

}
```
etc. all do not work.  
Also, for my particular usecase, I cannot set list to be static

**Comment by eyalch** [comment]
> 
> 
> > > @7kms
> > > > in [ts@3.x](mailto:ts@3.x) and above. solve it like this
> > > > ```ts
> > > > export const type = <const>[
> > > >   'room',
> > > >   'room_with_gifter',
> > > >   'user_send'
> > > > ];
> > > > 
> > > > export interface Activity {
> > > >   id?: string;
> > > >   type: typeof type[number];
> > > > }
> > > > ```
> > > 
> > > 
> > > Now what if I have this in a class?
> > > ```ts
> > > class Class {
> > >   const list = <const>[
> > >    'room',
> > >    'room_with_gifter',
> > >    'user_send'
> > >  ];
> > > 
> > >  const withType: typeof list[number];
> > > }
> > > ```
> > > 
> > > 
> > > Does not work. I also cannot do `this.list[number]`. Also, for my particular
> > > usecase, I cannot set `list` to be `static`
> > 
> > 
> > @vegerot You can't use `const` directly in the scope of the `class`, so the syntax is incorrect.
> 
> @7kms My bad. I copied and pasted too much. What I meant to say is
> 
> ```ts
> class Class {
>   private list = <const>[
>    'room',
>    'room_with_gifter',
>    'user_send'
>  ];
> 
>  private withType: typeof list[number];
> 
> // OR
>   private withType2: typeof this.list[number];
> 
> }
> ```
> 
> etc. all do not work.
> Also, for my particular usecase, I cannot set list to be static

```ts
class Class {
  private list = [
    "room",
    "room_with_gifter",
    "user_send"
  ] as const

  private withType: Class["list"][number]
}
```

@vegerot How about this?

**Comment by vegerot** [comment]
@eyalch that's awesome!  Thank you.  I thought the solution would involve `typeof` or something.  Would you give a quick explanation for how this works, or link me to the handbook where this is discussed?

**Comment by eyalch** [comment]
> 
> 
> @eyalch that's awesome! Thank you. I thought the solution would involve `typeof` or something. Would you give a quick explanation for how this works, or link me to the handbook where this is discussed?

@vegerot Sure, I believe it's an "Index type". Here it is in the Handbook: https://www.typescriptlang.org/docs/handbook/advanced-types.html#index-types

Glad I could help!

**Comment by a-x-** [comment]
Hey %username%, if `ElementType` solution doesn't work for you too.
Take attention on as const after array. It's crucial

**Comment by soryy708** [comment]
https://steveholgado.com/typescript-types-from-arrays/

**Comment by Robula** [comment]
How would you create a type that passes values from an array to something like `Pick` or `Omit`?
Like this: [Playground](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgLIE8DyAjAVhBMZAb2QChlLkAHKAe2oEEAuZAZzClAHMKraGAIVYcuIXlRr1qAYRGceZAL5kyCOiA7IAtljwEwrDDnyFkAXhJ9KApqwDkjewBprUoQ8Eu3tucnsy9sqqMACuIITAGjTACADWxvqEADwAKsgQAB6QIAAmbMgAShBwuRoANujJABRxEOh0MGh6pmAAlADaALoAfM7IAKoZ2RB5BQAKsXHJia39qR0godrY0L09yNUAdDu20GDAEGysqW2sQ8Ru6ppEdHjnFiQqbjB0UJvXWntQYOjIje5qPtDmw2lZJJI7rgOt9fl1HroTAYYdJ9ugum4VJI3FAIGBQlAQP88MEyNQprMDNV7LYnP0adJAmCAPTMkiAlj+OmAvwBezIJRAA)

Thanks

**Comment by zeckdude** [comment]
Not sure why this works (maybe someone can help me understand), but this seems to work great for me:

```js
const expectedValues = {
  headlines: {
    signUpSelection: 'Create an account',
    emailSignUp: 'Sign up (for free)',
    logInSelection: 'Log into your account',
    emailLogIn: 'Welcome back!',
    checkout: 'Add a payment method',
  },
};

type SectionName = keyof typeof expectedValues.headlines;
```

**Comment by vegerot** [comment]
> Not sure why this works (maybe someone can help me understand), but this seems to work great for me:
> 
> ```ts
> const expectedValues = {
>   headlines: {
>     signUpSelection: 'Create an account',
>     emailSignUp: 'Sign up (for free)',
>     logInSelection: 'Log into your account',
>     emailLogIn: 'Welcome back!',
>     checkout: 'Add a payment method',
>   },
> };
> 
> type SectionName = keyof typeof expectedValues.headlines;
> ```

@zeckdude I think you mean

```ts
const expectedValues = {
  headlines: {
    signUpSelection: 'Create an account',
    emailSignUp: 'Sign up (for free)',
    logInSelection: 'Log into your account',
    emailLogIn: 'Welcome back!',
    checkout: 'Add a payment method',
  },
} as const;

type SectionName = keyof typeof expectedValues.headlines;
```

**Comment by matthew-dean** [comment]
What if we want to use these as object keys?
```jsx
export const weekdays = [
  'sunday',
  'monday',
  'tuesday',
  'wednesday',
  'thursday',
  'friday',
  'saturday'
] as const

export type WeekdayName = typeof weekdays

// This causes the error: 
// Type 'readonly ["sunday", "monday", "tuesday", "wednesday", "thursday", "friday", "saturday"]' does not satisfy the constraint 'string | number | symbol'
const WeekDayObj: Record<WeekdayName, any> = {
  
}
```
These are string types but it seems that TS doesn't recognize this for the purposes of creating object keys.

**Comment by jniac** [comment]
What about the ability of inferring from an argument?
It could be useful to force the user of the following function to use one of previous declared options:
```typescript
const myFunc = (options: Readonly<unknown[]>, currentOption: typeof options[number]) => {
  // ...
}
myFunc(['foo', 'bar', 'baz'], 'bar') // ok
myFunc(['foo', 'bar', 'baz'], 'qux') // error
```

Currently it's not possible since `as const` could not be used in function parameters.

**Comment by xxRockOnxx** [comment]
Similar to @jniac example, my use case is more like

```
interface TabsProp<T extends string[]> {
  tabs: T
  selected: OneOf<T>
  onSelect: (tab: OneOf<T>) => void
}
```

I currently have no workaround

**Comment by karol-majewski** [comment]
@[xxRockOnxx](https://github.com/xxRockOnxx) Try this:

```typescript
import * as React from 'react';

interface TabsProp<T extends string> {
    selected: ExcludeFromTypeInference<T>;
    tabs: T[]
    onSelect: (tab: ExcludeFromTypeInference<T>) => void
}

type ExcludeFromTypeInference<T> = [T][T extends any ? 0 : never];

declare class MyComponent<T extends string> extends React.Component<TabsProp<T>> {};

<MyComponent tabs={['foo', 'bar']} selected={'foo'} onSelect={tab => {
    tab === 'foo' || tab === 'bar';
}} />
```

[TypeScript Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQdwAdjFlAXlnACrIBGqAArEwAHm5wsAD1ZMAJulQwozAOYA+OAG86cPXFRYANlnxY5ALjgBRKbiMBXOVgBixENwCeYLAEkmBGxYTLhY4ur0+nAw-KhW3ADaALq6+hBMAMrGpjBWABQxfFa29k6u7l4+-oGUIWHc6gCUcAC8mgBuEMBydAC+DDDeXCWOzm4klX4BQXXhrXAJ3EmLkjLBCihMnnAA-HAADHBWTFjtbEn0dM72yJRwN6joALKeAMIkkCcs4quyG0oqJgaX7rdDYPAwAB073A6WCMHEsWEEDEDU0Wl6l1ELxhn3h0ViLS0CTIBAgEDIABpyHxbmQkr0DNkzHIiaTyWRGeksiZ8ETCq10ak9AKWmLyGSKXAAD7Sgl8Vrisi0qC0PqMgD06joQA)

**Comment by SamB** [comment]
Huh, I was expecting this to be a request for a feature where, starting with an expression like

```typescript
["foo", "bar"]
```,

you could request a "refactor" or something that would generate something equivalent to:

```typescript
type NewType =
|"foo"
|"bar"
```

(where NewType would be selected so you could type the name you actually want),
because that is something that I've wanted to do before.

**Comment by shiftyp** [comment]
Not sure if this helps, but to convert a tuple to a union type its sufficient to do:
```
st weekdayNames = [
    "monday",
    "tuesday"
    /* ect */
] as const

// Gives "monday | "tuesday"
type WeekdayNames = typeof weekdayNames[Exclude<keyof typeof weekdayNames, keyof Array>]
```

**Comment by VictorLandimBB** [comment]
This is how to do it in late 2023:

```ts
const animals = ['cat', 'dog', 'mouse'] as const
type Animal = typeof animals[number]

// type Animal = 'cat' | 'dog' | 'mouse'
```

from: https://steveholgado.com/typescript-types-from-arrays/

**Comment by seanpmaxwell** [comment]
> #### Desired:
> What about the ability of inferring from an argument? It could be useful to force the user of the following function to use one of previous declared options:
> 
> const myFunc = <T extends readonly unknown[]>(options: T, currentOption: T[number]) => {
>   // ...
> }
> myFunc(['foo', 'bar', 'baz'], 'bar') // ok
> myFunc(['foo', 'bar', 'baz'], 'qux') // error
> Currently it's not possible since `as const` could not be used in function parameters.
> 
> #### Workaround:
> So the following usage works:
> 
> const options = ['foo', 'bar', 'baz'] as const
> myFunc(options, 'bar') // ok
> myFunc(options, 'qux') // error

I got it to work by putting `as const` in the function call. i.e. myFun(['asdf', ffff'] as const);
