### ISSUE TITLE
Filter working with != and not with !==

### ISSUE THREAD

**Issue by SlimAidar** [microsoft/TypeScript#28051]
this is working:
`deleteSelected() {`
    `const checked = document.querySelector('input.action:checked')['value'];`
    `const id = checked;`
   ` this.employees = this.employees.filter(emp => {`
      `return emp.id != this.id;` // double equal
    `});`
 ` }`

but this is not:
`deleteSelected() {`
    `const checked = document.querySelector('input.action:checked')['value'];`
    `const id = checked;`
    `this.employees = this.employees.filter(emp => {`
      `return emp.id !== this.id;` // triple equal
  `  });`
`  }`

**Comment by chharvey** [comment]
Hey @SlimAidar , could you please edit your post to be formatted with block code? Check out [this article on GitHub Help](https://help.github.com/articles/creating-and-highlighting-code-blocks/) for details. Thanks!
