### ISSUE TITLE
API: LanguageServiceHost.resolveModuleNames return type assumes successful resolution

### ISSUE THREAD

**Issue by AviVahl** [Microsoft/TypeScript#28058]
```ts
resolveModuleNames?(moduleNames: string[], containingFile: string, reusedNames?: string[]): ResolvedModule[];
```
What if my custom code fails resolving the module? Tried returning a shorter array of the modules I am able to resolve, but there is an assert in TypeScript verifying `returnedArray.length` should be equal to `moduleNames.length`.

Looking at the same code with the assert, I noticed there is an `if` verifying returnedArray item (ResolvedModule) is defined.

Long story short, can the return value be adjusted to the more appropriate `Array<ResolvedModule | undefined>`?

**Comment by fatcerberus** [comment]
If you fail to resolve something, shouldn’t you throw?  Not too familiar with the API in question but it’s pretty typical for return types to assume success and if there’s a problem, you throw.

**Comment by sheetalkamat** [comment]
@AviVahl Yes. The return type of LanguageServiceHost.resolveModuleNames should be same as it is on CompilerHost.

**Comment by ajafff** [comment]
fix is up at #28059

**Comment by fatcerberus** [comment]
Well I feel sheepish. :genie: :sheep:

**Comment by AviVahl** [comment]
@fatcerberus You shouldn't. Our ecosystem is full of functions throwing errors around, so it's not uncommon to see such patterns. That being said, most of the TypeScript APIs I've encountered assume you wouldn't throw.

It makes extra sense in this case, because TypeScript probably needs the successful resolutions and to know which ones failed resolving.

Appreciate the input nonetheless.
