### ISSUE TITLE
'.symbol' baselines not emitted if 'tests' parameter is used in 'jake runtests'

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#2806]
Repro:

1. Add test file `tests/cases/compiler/yaddayaddayadda.ts`.
2. Run `jake runtests tests=yaddayaddayadda`

Expected: local '.symbols' baselines created
Actual: local '.symbols' baselines are not created

**Comment by mhegazy** [comment]
@CyrusNajmabadi any idea?

**Comment by CyrusNajmabadi** [comment]
This is unrelated to .symbols generation.  ```jake runtests t=``` is simply broken when you pass in a file name.  @danquirk and i both observed this, but neither of us has had time to investigate what the issue is.

**Comment by DanielRosenwasser** [comment]
I think this is actually a symptom of #2822.
