### ISSUE TITLE
Allow augmented declaration merging of type aliases.

### ISSUE THREAD

**Issue by nkappler** [Microsoft/TypeScript#28078]
I want to extend a type alias declared in node_modules/@types

File "index.d.ts":
```typescript
interface A { /* stuff */ }
interface B { /* stuff */ }
interface C { /* stuff */ }

export type X = A | B | C;
```
My File:

```typescript
interface D { /* stuff */ }

declare module "someModule" {
  export type X = X | D;
}

```

This does not work at the moment, and I don't know if there is a good workaround for what I want to achieve, because I want to call a generic function from that module which expects a parameter of type `X` and I want to pass it a `D`.

**Comment by weswigham** [comment]
@nkappler write
```ts
interface XRegistry {
  A:A
  B:B
  C:C
}
type X= XRegistry[keyof XRegistry];
//... And in the other file
declare module "someModule" {
  interface XRegistry { D:D }
}

```
Instead.

**Comment by weswigham** [comment]
I'd hardly call it clumsy, afaik we use it in the Dom lib for some things. But yeah, merging aliases doesn't make nearly as much sense as interfaces. As you've written it, file parse order would matter. And generally speaking, two arbitrary types don't "merge" cleanly. Eg, what would a merge of `Qux[T]` and `Baz extends T ? Qux : never` even be?

**Comment by shaunluttin** [comment]
How would we make this approach work to extend an external type like this: 

someModule.ts

    export type Foo = 'bar' | 'baz';

someFile.ts

    import { Foo } from 'someModule';

    const: Foo = 'qux'; // how could we extend Foo to make this work?
