### ISSUE TITLE
tslib is missing when I set target to "esnext"

### ISSUE THREAD

**Issue by xiaocaibird** [microsoft/TypeScript#28073]
target: "esnext"

index.ts
```
export default async () => {
    (await import('./app')).default();
};
```

run tsc ===>  index.js
```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = async () => {
    (await Promise.resolve().then(() => __importStar(require('./app')))).default();
};
```

and then I set  target to "es6"

run tsc ===> index.js
```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const tslib_1 = require("tslib");
exports.default = () => tslib_1.__awaiter(this, void 0, void 0, function* () {
    (yield Promise.resolve().then(() => tslib_1.__importStar(require('./app')))).default();
});

```

**Comment by kitsonk** [comment]
Why did you ignore the issue template?

This is not sufficient information to be able to reproduce.

**Comment by jakebailey** [comment]
This is an old issue, and despite my trying with every version that existed when this was filed and every configuration I can think that would do this, I cannot reproduce what's listed above. Whatever it was, I'm pretty sure that it's fixed at this point, if it was ever a bug at all.
