### ISSUE TITLE
JSDoc to type annotation codefix doesn't work

### ISSUE THREAD

**Issue by sandersn** [Microsoft/TypeScript#28084]
```ts
// @noImplicitAny: true
/**
 * @param {String | Number} value
 */
export const f = value => new Number(value)
```

**Expected behavior:**
Implicit any error on `value`, plus a codefix that replaces it with `value: string | number`

**Actual behavior:**
Error, but no codefix offered

**Counterpoint:**  
@pedrouid documented it working as of last week: https://twitter.com/pedrouid/status/1052613754540584960

So maybe it's just broken recently.

**Comment by pedrouid** [comment]
I just tested it and it still works on my side.
```bash
# System
macOS High Sierra v10.13.6 
VS Code v1.28.2
Typescript v3.1.3

# tsconfig.json
{
  "compilerOptions": {
    "target": "es2015",
    "module": "commonjs",
    "strict": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "resolveJsonModule": true
  }
}
```

**Comment by pedrouid** [comment]
Here is the example that I used for that GIF
https://gist.github.com/pedrouid/f82a31c9fe9d45eb8720875bfbf3a6aa

PS - thanks for this awesome feature 🙌 it's so awesome

**Comment by sandersn** [comment]
Works on VSCode with TS 3.2 as well, just not with emacs. I guess this is a bug in tide, then.
