### ISSUE TITLE
Unexplored code paths of string literal union types

### ISSUE THREAD

**Issue by astorije** [Microsoft/TypeScript#28087]
**TypeScript Version:**  3.1.3

**Search Terms:** string literal union type typeguard

**Code**

```ts
function foobar(arg: 'foo' | 'bar') {
  if (arg === 'foo') return true;
  if (arg === 'bar') return false;
}
```

**Expected behavior:** `foobar` should have a return type of `boolean`

**Actual behavior:** Getting the error `Not all code paths return a value`

The example above is overly simplistic on purpose, and an `else` instead of the second `if` statement would do the job, but the issue remains: why can `tsc` not infer that all branches have been explored?

**Playground Link:** https://www.typescriptlang.org/play/index.html#src=%0D%0A%0D%0Afunction%20foobar(arg%3A%20'foo'%20%7C%20'bar')%20%7B%0D%0A%20%20%20%20if%20(arg%20%3D%3D%3D%20'foo')%20return%20true%3B%0D%0A%20%20%20%20if%20(arg%20%3D%3D%3D%20'bar')%20return%20false%3B%0D%0A%7D

**Related Issues:** I am fairly confident this has already been discussed in the past, but I couldn't find any related issues. Sorry if I missed anything obvious!

**Comment by jack-williams** [comment]
Related: #21985

**Comment by weswigham** [comment]
Duplicates #21985
