### ISSUE TITLE
--downlevelIteration errors should mention using later targets

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#28086]
```js
// @ts-check
class Foo {
  constructor(...args) {}
}
function makeFoo() {
  return new Foo(...arguments)
}
```

**Actual**

> Type 'IArguments' is not an array type. Use compiler option '--downlevelIteration' to allow iterating of iterators.

**Expected**

> Type 'IArguments' is not an array type. Either use the '--downlevelIteration' compiler option to allow iterating on iterators, or set the '--target' option to 'es2015' or above.

**Comment by kschiang19** [comment]
Hi, can I work on this issue?

**Comment by DanielRosenwasser** [comment]
Go for it - update `diagnosticMessages.json`, run the test suite, accept the baselines, and send us a PR.

**Comment by DanielRosenwasser** [comment]
Thanks @a-tarasyuk1
