### ISSUE TITLE
Is there a [require("typescript")] api document?

### ISSUE THREAD

**Issue by maskletter** [Microsoft/TypeScript#28096]
![qq 20181024145645](https://user-images.githubusercontent.com/15777183/47412176-84a45680-d79d-11e8-81dc-16ad5bf3c6d5.png)

![image](https://user-images.githubusercontent.com/15777183/47412243-c0d7b700-d79d-11e8-9a79-6bc7a597ae38.png)

I did not find a description of these methods.
。。。
I want to locate the specific code where the error occurred.

**Comment by MartinJohns** [comment]
Unfortunately most of the compiler API is undocumented. To my knowledge there is not more information available besides the JSDoc (in the .d.ts files) and the few Wiki pages:

- https://github.com/Microsoft/TypeScript/wiki/Compiler-Internals
- https://github.com/Microsoft/TypeScript/wiki/API-Breaking-Changes
- https://github.com/Microsoft/TypeScript/wiki/FAQs-for-API-Consumers
- https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API

**Comment by maskletter** [comment]
╮(╯-╰)╭Thank you
