### ISSUE TITLE
Type "foo" & "bar" should be reduced to never

### ISSUE THREAD

**Issue by uhyo** [Microsoft/TypeScript#28094]
**TypeScript Version:**  3.1.3, 3.2.0-dev.20181023

**Search Terms:** intersection literal type never

**Code**

```ts
type T1 = "foo" & "bar";

// error TS2322: Type 'T1' is not assignable to type 'never'.
const n1: never = ({} as any as T1);

// T2 is "foo" & "bar"
type T2 = keyof ({foo: string} | {bar: number});

// error TS2322: Type 'T1' is not assignable to type 'never'.
const n2: never = ({} as any as T2);

// T3 is never
type T3 = T1 | T1;

// No error
const n3: never = ({} as any as T3);
```

**Expected behavior:**
`T1` and `T2` should be reduced to `never` because there is no value of type `"foo" & "bar"`.

**Actual behavior:**
`"foo" & "bar"` remains as-is and is not assignable to `never`. 

Interestingly, `("foo" & "bar") | ("foo" & "bar")` becomes `never`.

**Playground Link:** https://www.typescriptlang.org/play/#src=type%20T1%20%3D%20%22foo%22%20%26%20%22bar%22%3B%0D%0A%0D%0A%2F%2F%20error%20TS2322%3A%20Type%20'T1'%20is%20not%20assignable%20to%20type%20'never'.%0D%0Aconst%20n1%3A%20never%20%3D%20(%7B%7D%20as%20any%20as%20T1)%3B%0D%0A%0D%0A%2F%2F%20T2%20is%20%22foo%22%20%26%20%22bar%22%0D%0Atype%20T2%20%3D%20keyof%20(%7Bfoo%3A%20string%7D%20%7C%20%7Bbar%3A%20number%7D)%3B%0D%0A%0D%0A%2F%2F%20error%20TS2322%3A%20Type%20'T1'%20is%20not%20assignable%20to%20type%20'never'.%0D%0Aconst%20n2%3A%20never%20%3D%20(%7B%7D%20as%20any%20as%20T2)%3B%0D%0A%0D%0A%2F%2F%20T3%20is%20never%0D%0Atype%20T3%20%3D%20T1%20%7C%20T1%3B%0D%0A%0D%0A%2F%2F%20No%20error%0D%0Aconst%20n3%3A%20never%20%3D%20(%7B%7D%20as%20any%20as%20T3)%3B%0D%0A

**Related Issues:**

**Comment by MartinJohns** [comment]
Note that this would render a common nominal-typing technique useless:

```
type Branded<T, B extends string> = T & { [P in B]: never };

type OrderId = Branded<number, 'orderId'>;
type BookingId = Branded<number, 'bookingId'>;
```

**Comment by DanielRosenwasser** [comment]
I think we discussed this at #18339. Thoughts @ahejlsberg?

**Comment by DanielRosenwasser** [comment]
The aforementioned link does discuss this a bit but if you turn these things into `never`, then it becomes harder to diagnose where that `never` originated from, and all of a sudden your properties become assignable to anything.

Is there a use-case you had in mind where this came up?

**Comment by uhyo** [comment]
Sorry I missed #18339.
A use case in my mind was to test that a union type has no common properties by confirming that `keyof` it is `never`.

```ts
type IsNever<T> = T[] extends never[] ? true : false;
type UnionType = {foo: string} | {bar: number};
type UnionTypeKeys = keyof UnionType;
// assert that UnionType has no common properties.
const val1: IsNever<UnionTypeKeys> = true;
```

**Comment by ahejlsberg** [comment]
See #18438 for details on our behavior here. Note that you can always cause empty intersection types to be reduced away by unioning with `never`. For example, this works:

```ts
type IsNever<T> = T[] extends never[] ? true : false;
type UnionType = {foo: string} | {bar: number};
type UnionTypeKeys = keyof UnionType | never;  // Union removes empty intersections
const val1: IsNever<UnionTypeKeys> = true;
```

**Comment by uhyo** [comment]
Thank you, I understand that this is an intended behaviour.
I'm willing to close this unless anyone else wants to continue discussing.
