### ISSUE TITLE
Add `PromiseResult` type to standard lib

### ISSUE THREAD

**Issue by ethanresnick** [microsoft/TypeScript#28105]
## Search Terms
promise result type

## Suggestion
Typescript already ships with a `ReturnType` type and a `Parameters` type, so why not ship with a `PromiseResult` type: 

```ts
type PromiseResult<T> = T extends Promise<infer U> ? U : never;
```

## Use Cases/Examples
```ts
type Output = PromiseResult<ReturnType<typeof computeSomething>>;

async function computeSomething(input: any) {}
function computeFromResult(input: Output) {}
```

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by DanielRosenwasser** [comment]
See #17077, and discussion at 

* https://github.com/Microsoft/TypeScript/issues/17621
* https://github.com/Microsoft/TypeScript/issues/18155

Search also for `awaited`, `await`, `promised`, `unpromise`, and `unpromisify` on the issue tracker.

**Comment by DanielRosenwasser** [comment]
Just to clarify, for `Promises` to work correctly we need a more general `awaited` type which unwraps `PromiseLike`s recursively. If we had that, it would subsume this `PromiseResult` type.

**Comment by ajafff** [comment]
> Just to clarify, for Promises to work correctly we need a more general awaited type which unwraps PromiseLikes recursively.

Sounds like recursive conditional types to me... but that's already discussed somewhere else

**Comment by deser** [comment]
Any progress here? :)

**Comment by westonkjones** [comment]
Interested in this as well. The AWS SDK uses this as the return of their promises
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SecretsManager.html#getSecretValue-property

```
(method) Request<SecretsManager.GetSecretValueResponse, AWSError>.promise(): Promise<PromiseResult<AWS.SecretsManager.GetSecretValueResponse, AWS.AWSError>>

Returns a 'thenable' promise.
```

**Comment by fregante** [comment]
Coming in https://github.com/microsoft/TypeScript/pull/35998, hopefully
