### ISSUE TITLE
tsconfig.json wiki should indicate which version of tsc supports tsconfig.json

### ISSUE THREAD

**Issue by dlee** [Microsoft/TypeScript#2810]
`tsconfig.json` is a great new feature, but older versions of `tsc` do not support it. The documentation at https://github.com/Microsoft/TypeScript/wiki/tsconfig.json should indicate which versions of `tsc` supports `tsconfig.json`.

**Comment by danquirk** [comment]
Thanks, added a note that it's supported starting with 1.5.
