### ISSUE TITLE
Path suggestion should have path with extension in `CompletionEntry.name`

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#28116]
From https://github.com/Microsoft/vscode/issues/61625

**TypeScript Version:**  3.2.0-dev.20181020

**Search Terms:**
- Completions / suggestions
- Path intellisense
- CompletionEntry

**Feature request**
For file path completions we'd like to make the following changes to support https://github.com/Microsoft/vscode/issues/61625:

- `CompletionEntry.name` should have the file name with extension, e.g. `myFile.ts`
- `CompletionEntry.insertText` should have the file name as it will be added in the import, , e.g. `myFile`

This will allow VS Code (and other editors) to show better icons for file path completion items

**Alternative Design**

- Include file extension in the `CompletionEntry.kind` or `CompletionEntry.kindModifiers`

**Comment by zafarmandor786** [comment]
Thanks
