### ISSUE TITLE
Generic cant infer this type inside instance

### ISSUE THREAD

**Issue by HitalloExiled** [Microsoft/TypeScript#28117]
**Search Terms:**
Inference, generic, this type

Gereric methods that use type 'this' in type parameters do not infer correctly when executed inside the same instance or derived. 
Generating errors like:
* Type '["fooBar", number]' is not assignable to type '[keyof this, this[keyof this]]'.
    * Type 'number' is not assignable to type 'this[keyof this]'.

This problem does not occur when the same method is called from outside the instance.

**Code**

```ts
type MappedIndex<K extends string|number|symbol, T> = { [P in K]: T };
type AttributeParse<T extends object, M extends MappedIndex<string, keyof T>> = { [K in keyof M]: M[K] extends keyof T ? (value: string) => [M[K], T[M[K]]] : never };

class Dummy
{
    public fooBar: number = 0;

    public readonly parser: AttributeParse<Dummy, { "foo-bar": "fooBar" }> =
    {
        "foo-bar": value => ["fooBar", Number.parseInt(value)]
    };

    public map
    <
        TAttibute extends string,
        TPropertyMap extends MappedIndex<TAttibute, keyof this>,
        TAttributeParse extends AttributeParse<this, TPropertyMap>,
    >
    (parser: TAttributeParse, attribute: TAttibute, raw: string): void
    {
        const [key, value] = parser[attribute](raw);

        if (value != this[key])
        {
            this[key] = value;
        }
    }

    public parse(key: "foo-bar", value: string): void
    {
        this.map(this.parser, key, value);
        //       ^^^ Error
    }
}

new Dummy().map(Dummy.prototype.parser, "foo-bar", "0"); // No Error
```

**Expected behavior:**
No error. The Inference of **this** type within the instance should be consistent with inference outside of it.

**Actual behavior:**
No inference, error:

**Playground Link:** 
https://www.typescriptlang.org/play/#src=type%20MappedIndex%3CK%20extends%20string%7Cnumber%7Csymbol%2C%20T%3E%20%3D%20%7B%20%5BP%20in%20K%5D%3A%20T%20%7D%3B%0D%0Atype%20AttributeParse%3CT%20extends%20object%2C%20M%20extends%20MappedIndex%3Cstring%2C%20keyof%20T%3E%3E%20%3D%20%7B%20%5BK%20in%20keyof%20M%5D%3A%20M%5BK%5D%20extends%20keyof%20T%20%3F%20(value%3A%20string)%20%3D%3E%20%5BM%5BK%5D%2C%20T%5BM%5BK%5D%5D%5D%20%3A%20never%20%7D%3B%0D%0A%0D%0Aclass%20Dummy%0D%0A%7B%0D%0A%20%20%20%20public%20fooBar%3A%20number%20%3D%200%3B%0D%0A%0D%0A%20%20%20%20public%20readonly%20parser%3A%20AttributeParse%3CDummy%2C%20%7B%20%22foo-bar%22%3A%20%22fooBar%22%20%7D%3E%20%3D%0D%0A%20%20%20%20%7B%0D%0A%20%20%20%20%20%20%20%20%22foo-bar%22%3A%20value%20%3D%3E%20%5B%22fooBar%22%2C%20Number.parseInt(value)%5D%0D%0A%20%20%20%20%7D%3B%0D%0A%0D%0A%20%20%20%20public%20map%0D%0A%20%20%20%20%3C%0D%0A%20%20%20%20%20%20%20%20TAttibute%20extends%20string%2C%0D%0A%20%20%20%20%20%20%20%20TPropertyMap%20extends%20MappedIndex%3CTAttibute%2C%20keyof%20this%3E%2C%0D%0A%20%20%20%20%20%20%20%20TAttributeParse%20extends%20AttributeParse%3Cthis%2C%20TPropertyMap%3E%2C%0D%0A%20%20%20%20%3E%0D%0A%20%20%20%20(parser%3A%20TAttributeParse%2C%20attribute%3A%20TAttibute%2C%20raw%3A%20string)%3A%20void%0D%0A%20%20%20%20%7B%0D%0A%20%20%20%20%20%20%20%20const%20%5Bkey%2C%20value%5D%20%3D%20parser%5Battribute%5D(raw)%3B%0D%0A%0D%0A%20%20%20%20%20%20%20%20if%20(value%20!%3D%20this%5Bkey%5D)%0D%0A%20%20%20%20%20%20%20%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20this%5Bkey%5D%20%3D%20value%3B%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20public%20parse(key%3A%20%22foo-bar%22%2C%20value%3A%20string)%3A%20void%0D%0A%20%20%20%20%7B%0D%0A%20%20%20%20%20%20%20%20this.map(this.parser%2C%20key%2C%20value)%3B%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20%20%20%20%20%20%20%5E%5E%5E%20Error%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Anew%20Dummy().map(Dummy.prototype.parser%2C%20%22foo-bar%22%2C%20%220%22)%3B%20%2F%2F%20No%20Error

**Comment by ahejlsberg** [comment]
This is working as intended. The `parser` has the specific type `AttributeParse<Dummy, { "foo-bar": "fooBar" }>` whereas `this.map` operates on the generic `this` (which could be a type derived from `Dummy` that has more properties). It works if you change the call to

```ts
    (this as Dummy).map(this.parser, key, value);
```

but of course you have then promised that `this` is exactly the class `Dummy` and not a derived class.
