### ISSUE TITLE
Return File Path completion with ts/js suffix

### ISSUE THREAD

**Issue by octref** [Microsoft/TypeScript#28122]
With https://github.com/Microsoft/vscode/issues/44860, if a `CompletionItem` has label `foo.ts`, it'll get TS file icon. However, currently when TS is doing file path completion, it would return `CompletionItem` that has labels without suffix.

![image](https://user-images.githubusercontent.com/4033249/47468158-a3f7af80-d7ae-11e8-875a-ccd078816fdc.png)

If you could change the `CompletionItem.label` to include `.ts` or `.js` suffix and provide a `TextEdit` which doesn't include the suffix, we can get the nice icons and the path completion will work as it was.

I'd be happy to send a PR if you can point me to the right direction (never contributed to TS codebase before). Thanks again!

**Comment by mjbvz** [comment]
I opened #28116 to track this. See that issue for info about how TS Server could be modified to support this
