### ISSUE TITLE
Suggestion for eliminating forgetting to await bug

### ISSUE THREAD

**Issue by LarsLiden** [Microsoft/TypeScript#28134]
## Search Terms

async await promise tslint

## Suggestion

One bug that I see coming up frequently in people's code (which is also hard to debug / detect) is forgetting to put an await in front of an async function.   This could be eliminated by adding a compiler option that requires developers to explicitly mark when they don't want to await an async function.

## Use Cases

This optional feature would greatly reduce hard to find bugs

## Examples

`await this.myAsyncFunction(someData)`   

`nowait this.myAsyncFunction(someData)`  

`this.myAsyncFunction(someData)`   **TSLINT / COMPILER ERROR**

## Checklist

My suggestion meets these guidelines:
* [ ] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by weswigham** [comment]
I'm pretty sure tslint's [no-floating-promise](https://palantir.github.io/tslint/rules/no-floating-promises/) rule covers this.

**Comment by weswigham** [comment]
Yeah.
