### ISSUE TITLE
[lib.webworker.d.ts] Worker constructor type missing optional options

### ISSUE THREAD

**Issue by AviVahl** [Microsoft/TypeScript#28136]
**TypeScript Version:**  3.1.3 (not fixed in `master` as well)
https://github.com/Microsoft/TypeScript/blob/release-3.1/lib/lib.webworker.d.ts#L2699

**Search Terms:**
web worker options

**Code**
```ts
new Worker('https://some-url', {type: 'module'})
```

**Expected behavior:**
Type check should pass.

**Actual behavior:**
Second (options) parameter isn't specified in Worker types, so type check fails.

**Playground Link:** 
http://www.typescriptlang.org/play/#src=new%20Worker('https%3A%2F%2Fsome-url'%2C%20%7Btype%3A%20'module'%7D)

**Related Issues:** 
Couldn't find existing issue discussing this.

Reference:
https://developer.mozilla.org/en-US/docs/Web/API/Worker/Worker

**Comment by weswigham** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by AviVahl** [comment]
@weswigham I gave it a try... cloned the `tsjs-lib-generator` repo, edited `overridingTypes.json` > `interfaces` >`interface` > `Worker`, adding:
```json
"constructor": {
    "override-signatures": [
        "new(stringUrl: string, options?: WorkerOptions): Worker"
    ]
},
```
That seemed to modify the generated constructor the way I wanted.

I couldn't, however, find a proper way to add the [WorkerOptions](https://html.spec.whatwg.org/multipage/workers.html#dedicated-workers-and-the-worker-interface) interface. Tried adding it to `addedTypes.json` > `mixins`:
```json
"WorkerOptions": {
    "name": "WorkerOptions",
    "properties": {
        "property": {
            "type": {
                "name": "type",
                "override-type": "WorkerType",
                "required": 0
            },
            "credentials": {
                "name": "credentials",
                "override-type": "RequestCredentials",
                "required": 0
            },
            "name": {
                "name": "name",
                "override-type": "string",
                "required": 0
            }
        }
    }
}
```
but that resulted in a global `WorkerOptions` constructor variable.

Not sure I'm even editing the correct files. Could use any pointers... :)

**Comment by weswigham** [comment]
I think we normally use the [dictionaries](https://github.com/Microsoft/TSJS-lib-generator/blob/master/inputfiles/addedTypes.json#L2535) section for interfaces.

**Comment by AviVahl** [comment]
@weswigham thx for the tip. I also had to adjust `knownTypes.json` for the interface to actually be exposed. Opened PR.
