### ISSUE TITLE
In finally block, local variable is incorrectly typed as never with return in try block.

### ISSUE THREAD

**Issue by OpenSourceAries** [Microsoft/TypeScript#28153]
**TypeScript Version:**  3.1.3

**Search Terms:** try finally block 

**Code**

```ts
async function test(): Promise<string> {
    let browser: puppeteer.Browser | undefined = undefined;
    let page: puppeteer.Page | undefined = undefined;
    try {
        browser = await test1();
        page = await test2(browser);
        return await page.content();;
    } finally {
        if (page) {
            await page.close();
        }

        if (browser) {
            await browser.close();
        }
    }
}

async function test1(): Promise<puppeteer.Browser> {
    return await puppeteer.launch();
}

async function test2(browser: puppeteer.Browser): Promise<puppeteer.Page> {
    return await browser.newPage();
}
```

**Expected behavior:**
page and browser can be of type puppeteer.Page and puppeteer.Browser

**Actual behavior:**
compile error message:
error TS2339: Property 'close' does not exist on type 'never'.

**Related Issues:** 
#11665(The different is current issue's code contains a return in try block)

**Comment by woutervh-** [comment]
The same happens in the catch block. Here is my minimal reproduction of the error I run into:

```ts
class Foo {
    abortController: AbortController | undefined = undefined;

    async operation() {
        if (this.abortController !== undefined) {
            this.abortController.abort();
            this.abortController = undefined;
        }
        try {
            this.abortController = new AbortController();
        } catch (error) {
            if (this.abortController !== undefined) {
                this.abortController.abort();
            }
        }
    }
}
```

[Playground link](https://www.typescriptlang.org/play/#src=class%20Foo%20%7B%0D%0A%20%20%20%20abortController%3A%20AbortController%20%7C%20undefined%20%3D%20undefined%3B%0D%0A%0D%0A%20%20%20%20async%20operation()%20%7B%0D%0A%20%20%20%20%20%20%20%20if%20(this.abortController%20!%3D%3D%20undefined)%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20this.abortController.abort()%3B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20this.abortController%20%3D%20undefined%3B%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%20%20%20%20try%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20this.abortController%20%3D%20new%20AbortController()%3B%0D%0A%20%20%20%20%20%20%20%20%7D%20catch%20(error)%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20if%20(this.abortController%20!%3D%3D%20undefined)%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20this.abortController.abort()%3B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A)

**Comment by rulatir** [comment]
Still experiencing this for the simplest of cases:

```typescript

import {performance} from "perf_hooks";

let riskyStuffTook = 0;

function foo() {
    
    let start : number;
    try {
        start = performance.now(); // <- ASSIGNING HERE!!!
        doRiskyStuff();
    }
    finally {
        riskyStuffTook += performance.now() - start; // TS2454: Variable 'start' is used before being assigned.
    }
}
```
