### ISSUE TITLE
False positive TS2342 Expression indexer must be of type 'string' 'number' or 'any'

### ISSUE THREAD

**Issue by mrgleba** [Microsoft/TypeScript#2816]
The error is reported in case when the indexer is a union type of string|number:

var a:number|string
var b:any
var c = b[a]; <- TS2342

**Comment by DanielRosenwasser** [comment]
Thanks for the bug report - this seems to be a duplicate of #1715. It's currently working in TypeScript 1.5 alpha if you'd like to try that out.
