### ISSUE TITLE
Bug: Conditional types don't properly propagate this

### ISSUE THREAD

**Issue by SLaks** [Microsoft/TypeScript#28164]
**TypeScript Version:**  3.1.1-insiders.20180926

**Search Terms:** this conditional

**Code**

```ts
class Builder<T1, T2, T3, TWith>{
    private _noStructuralTyping: undefined;

    withBroken<TAlsoWith>() {
        return this as AddWith<this, TAlsoWith>;
    }
    withBroken2<TAlsoWith>(): AddWith<this, TAlsoWith> {
        return this;
    }
    withWorking<TAlsoWith>(): Builder<T1, T2, T3, TWith|TAlsoWith> {
        return this;
    }
}


type AddWith<TBuilder, TAlsoWith> = TBuilder extends
    Builder<infer T1, infer T2, infer T3, infer TWith>?
    Builder<T1, T2, T3, TWith|TAlsoWith>:
    never;

const test = new Builder<1, 2, 3, string>().withBroken<number>();

// Without using the `this` type, it works as expected:
const simpleTest = new Builder<1, 2, 3, string>();
type WithNumber = AddWith<typeof simpleTest, number>;
const demo: WithNumber = simpleTest;
```

**Expected behavior:**

`this` should be convertible to `AddWith<this, whatever>`

**Actual behavior:**

```
Type 'this' is not assignable to type 'AddWith<this, TAlsoWith>'.
  Type 'Builder<T1, T2, T3, TWith>' is not assignable to type 'AddWith<this, TAlsoWith>'.
```

**Motivation**:
I'm building a builder class which builds configuration both in the type system and at runtime.

I don't want to repeat all of the existing type parameters (which have long names) in every method that adds a type to `TWith`

**Playground Link:** http://www.typescriptlang.org/play/#src=class%20Builder%3CT1%2C%20T2%2C%20T3%2C%20TWith%3E%7B%0D%0A%20%20%20%20private%20_noStructuralTyping%3A%20undefined%3B%0D%0A%0D%0A%20%20%20%20withBroken%3CTAlsoWith%3E()%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20this%20as%20AddWith%3Cthis%2C%20TAlsoWith%3E%3B%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20withBroken2%3CTAlsoWith%3E()%3A%20AddWith%3Cthis%2C%20TAlsoWith%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20this%3B%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20withWorking%3CTAlsoWith%3E()%3A%20Builder%3CT1%2C%20T2%2C%20T3%2C%20TWith%7CTAlsoWith%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20this%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0A%0D%0Atype%20AddWith%3CTBuilder%2C%20TAlsoWith%3E%20%3D%20TBuilder%20extends%0D%0A%20%20%20%20Builder%3Cinfer%20T1%2C%20infer%20T2%2C%20infer%20T3%2C%20infer%20TWith%3E%3F%0D%0A%20%20%20%20Builder%3CT1%2C%20T2%2C%20T3%2C%20TWith%7CTAlsoWith%3E%3A%0D%0A%20%20%20%20never%3B%0D%0A%0D%0Aconst%20test%20%3D%20new%20Builder%3C1%2C%202%2C%203%2C%20string%3E().withBroken%3Cnumber%3E()%3B%0D%0A%0D%0A%2F%2F%20Without%20using%20the%20%60this%60%20type%2C%20it%20works%20as%20expected%3A%0D%0Aconst%20simpleTest%20%3D%20new%20Builder%3C1%2C%202%2C%203%2C%20string%3E()%3B%0D%0Atype%20WithNumber%20%3D%20AddWith%3Ctypeof%20simpleTest%2C%20number%3E%3B%0D%0Aconst%20demo%3A%20WithNumber%20%3D%20simpleTest%3B
**Related Issues:** #28159

**Comment by ahejlsberg** [comment]
This is working as intended. We generally don't reason about assignability of conditional types applied to generic types. For this reason, neither `this` nor `AddWith<this, TAlsoWith>` is considered assignable to the other, so the assertion fails. In order for the code to type check you'll need to assume responsibility for verifying the assertion by first converting to `any`:

```ts
return this as any as AddWith<this, TAlsoWith>;
```
