### ISSUE TITLE
Typescript 1.5-alpha - TS2420 on Webstrom 10

### ISSUE THREAD

**Issue by zanettin** [Microsoft/TypeScript#2817]
I've tried 1.5-alpha on webstorm10. 
The error TS2420 (Error:(12, 14) TS2420: Class 'Guest' incorrectly implements interface 'IPerson'.
  Property 'gender' is missing in type 'Guest'.) I just got the error message '[object Object]' in the console. I'm actually not sure, if this is a issue of 1.5 or of the IDE.

testcode:
```
export interface IPerson {

	firstName	:	string;
	lastName	:	string;
	gender		:	string;

	getFirstName()	:	string;
	getLastName()	:	string;
}


export class Guest implements IPerson{

	firstName:string;
	lastName:string;


	constructor(firstName:string = 'John', lastName:string = 'Doe') {

		this.firstName = firstName;
		this.lastName = lastName;
	}

	getFirstName() {

		return this.firstName;

	}

	getLastName() {

		return this.lastName;

	}

}
```

**Comment by mhegazy** [comment]
This looks like an IDE issue. possibly related to #2549

**Comment by zanettin** [comment]
just seen, that jetbrains release 10.0.2 which resolved this issue => https://confluence.jetbrains.com/display/WI/WebStorm+141.614+Release+Notes
