### ISSUE TITLE
Add a step to verify the JS emitted by the tests is valid

### ISSUE THREAD

**Issue by Arnavion** [microsoft/TypeScript#2818]
... to prevent tests with broken emit getting checked in, like the original one in https://github.com/Microsoft/TypeScript/commit/55af7b3#diff-5a553969b7d75b3baab89d60e61bcd5b.

Running the output will require too much effort in the test as well as setting up the environment, so I think only parsing is feasible. It'd require a parser that understands ES6, or perhaps the TS parser itself (with the risk of not noticing bugs that also affect the parser.)

It would also require some way of marking tests as "expected to emit valid JS regardless of type errors", since the presence of a .errors.txt doesn't indicate whether the errors are of syntax or type.

**Comment by mhegazy** [comment]
We used to do something along these lines in the 0.8 timeframe but stopped as it was not catching issues and was taking too long. I think we should do it again, possibly under a flag and /or running it only in Travis and our local CI server. @DanielRosenwasser can u look into enabling these checks?

**Comment by DanielRosenwasser** [comment]
Discussed this with @yuit, she *may* be taking this task on at some point.
