### ISSUE TITLE
WebGL IDL generated types should use ArrayLike<*> for sequence<*>

### ISSUE THREAD

**Issue by jessevdk** [microsoft/TypeScript#28198]
**TypeScript Version:**  3.2.0-dev.201xxxxx

**Search Terms:** WebGL, idl, float32list

**Code**

```ts
const ctx: WebGLRenderingContext = null;
const value: ArrayLike<number> = [0, 1, 2];

ctx.uniform3fv(0, value);
```

**Expected behavior:** Compiles without errors (used to work in 3.0)

**Actual behavior:** Compiles with error since `ArrayLike<number>` isn't assignable to `Float32Array` nor `number[]`

**Playground Link:** http://www.typescriptlang.org/play/#src=const%20ctx%3A%20WebGLRenderingContext%20%3D%20null%3B%0D%0Aconst%20value%3A%20ArrayLike%3Cnumber%3E%20%3D%20%5B0%2C%201%2C%202%5D%3B%0D%0A%0D%0Actx.uniform3fv(0%2C%20value)%3B

**Related Issues:** [Wrong WebGLRenderingContext interface definition for pixelStorei #27542](https://github.com/Microsoft/TypeScript/issues/27542)

**Comment by weswigham** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by saschanaz** [comment]
As I wrote in https://github.com/Microsoft/TSJS-lib-generator/pull/592, Web IDL sequence requires iterator support but ArrayLike does not.

**Comment by weswigham** [comment]
`Iterable` aughta be correct then, right?

**Comment by saschanaz** [comment]
Yes, but unfortunately we cannot use `Iterable` because of es3/5 compatibility. (#23610)

**Comment by saschanaz** [comment]
Maybe we still can add overloads via `dom.es6.d.ts` in this case.

**Comment by weswigham** [comment]
Aye, that's what I was thinking. The es6 Dom lib seems like just the place for an overload like this.

**Comment by saschanaz** [comment]
Oh, I just remembered that I opened an issue exactly for this purpose. https://github.com/Microsoft/TSJS-lib-generator/issues/443

I can start working on this if the team agrees.

**Comment by Istar-Eldritch** [comment]
That makes more sense @saschanaz.
Does that make https://github.com/Microsoft/TSJS-lib-generator/pull/592 obsolete in favour the general sequence override approach? Or should we keep the `dom.generated.d.ts` with number[]?

Also, does this change the scope to a more general approach? Should all number sequences in `dom.generated.d.ts` be overrided to `number[]`?

**Comment by saschanaz** [comment]
We should keep existing `number[]` so that ES5 can keep passing arrays.

>Should all number sequences in dom.generated.d.ts be overrided to number[]?

I'm not sure I understand. `sequence<number>` is already being translated into `number[]`.

**Comment by saschanaz** [comment]
But L15924 doesn't contains `Float32Array`? If you mean `Float32List`, it's a union type of `Float32Array` and `number[]`.

**Comment by Istar-Eldritch** [comment]
@saschanaz true, sorry messing things up. I was indeed mixing `Float32List` with `FLoat 32Array`. @weswigham based on the evidence from @saschanaz, should we assume then that this issue is not achievable and close it?
