### ISSUE TITLE
Cannot import JSON when isolatedModules is true

### ISSUE THREAD

**Issue by brunolemos** [Microsoft/TypeScript#28202]
**TypeScript Version:**  3.2.0-dev.20181027

**Search Terms:** `json isolatedModules`, `resolveJsonModule isolatedModules`

**Code**

```ts
import test from './test.json'
```

`tsconfig.json`:

```json
{
  "compilerOptions": {
    "target": "es5",
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "preserve"
  },
  "include": [
    "src"
  ]
}
```

**Expected behavior:**

Imports JSON without any error.

**Actual behavior:**

`TS1208: Cannot compile namespaces when the '--isolatedModules' flag is provided.`

**Playground Link:** _Could not find a playground that supports editing tsconfig.json, adding a json file and that would show tsc output_

**Related Issues:** #15230, #18232, https://stackoverflow.com/q/52103265/2228575

**Comment by weswigham** [comment]
@sheetalkamat this should either be allowed (I don't see why it wouldn't?) or have a much better error message, I think.
