### ISSUE TITLE
Generics and optionals tends to confuse TS

### ISSUE THREAD

**Issue by zlepper** [Microsoft/TypeScript#28203]
**TypeScript Version:**  typescript@3.2.0-dev.20181027
Also errors out with next 

**Search Terms:**
Generics, Optional, recursive

**Code**

```ts
interface DataComponent<T> {
    data: T;
}

interface Args {
    name: string;
    margin?: string;
}

class SuperComponent {
    constructor(public data: Args) {

    }
}


interface Options<T> {
    data: T;
}

export interface ComponentType<T> {
    new (...args: any[]): T;
}

function openComponent<Y, T extends DataComponent<Y>(component: ComponentType<T>, options: Options<Y>) {
    // Do stuff
}

(function () {

    openComponent(SuperComponent, {
        data: {
            name: 'hello world!',
            margin: 'super duper'
        }
    });

})();
```

**Expected behavior:**
I should be able to assign the margin of the data attribute. 

**Actual behavior:**
```
C:\dev\work\test\ts>tsc test.ts
test.ts:31:19 - error TS2345: Argument of type 'typeof SuperComponent' is not assignable to parameter of type 'ComponentType<DataComponent<{ name: string; margin: string; }>>'.
  Type 'SuperComponent' is not assignable to type 'DataComponent<{ name: string; margin: string; }>'.
    Types of property 'data' are incompatible.
      Type 'Args' is not assignable to type '{ name: string; margin: string; }'.
        Property 'margin' is optional in type 'Args' but required in type '{ name: string; margin: string; }'.

31     openComponent(SuperComponent, {
                     ~~~~~~~~~~~~~~

```

**Playground Link:** 
https://www.typescriptlang.org/play/#src=interface%20DataComponent%3CT%3E%20%7B%0D%0A%20%20%20%20data%3A%20T%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20Args%20%7B%0D%0A%20%20%20%20name%3A%20string%3B%0D%0A%20%20%20%20margin%3F%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Aclass%20SuperComponent%20%7B%0D%0A%20%20%20%20constructor(public%20data%3A%20Args)%20%7B%0D%0A%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0A%0D%0Ainterface%20Options%3CT%3E%20%7B%0D%0A%20%20%20%20data%3A%20T%3B%0D%0A%7D%0D%0A%0D%0Aexport%20interface%20ComponentType%3CT%3E%20%7B%0D%0A%20%20%20%20new%20(...args%3A%20any%5B%5D)%3A%20T%3B%0D%0A%7D%0D%0A%0D%0Afunction%20openComponent%3CY%2C%20T%20extends%20DataComponent%3CY%3E(component%3A%20ComponentType%3CT%3E%2C%20options%3A%20Options%3CY%3E)%20%7B%0D%0A%20%20%20%20%2F%2F%20Do%20stuff%0D%0A%7D%0D%0A%0D%0A(function%20()%20%7B%0D%0A%0D%0A%20%20%20%20openComponent(SuperComponent%2C%20%7B%0D%0A%20%20%20%20%20%20%20%20data%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20name%3A%20'hello%20world!'%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20margin%3A%20'super%20duper'%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%7D)%3B%0D%0A%0D%0A%7D)()%3B%0D%0A

**Related Issues:** 

We are using this to verify arguments to popups. The actual code works fine when it runs, but TS seems to turn the type declarations on their head for some reason. 
It works fine if I make `margin` a non-optional attribute, however it needs to be optional in this context, as the actual component defines some default values.

**Comment by ahejlsberg** [comment]
This is working as intended. The type inferred for `T` from the first argument is `{ data: { name: string, margin?: string } }` and the type inferred for `Y` from the second argument is `{ name: string, margin: string }`. Because of the optional `margin`, the inference for `T` fails to meet the constraint `DataComponent<{ name: string, margin: string>`, so we default `T` to the constraint instead. The first argument subsequently fails the assignment check because it returns an object where `margin` is possibly missing.

The issue here is that you have two separate type variables instead of just one. I suggest you change your declaration to:

```ts
function openComponent<T extends DataComponent<unknown>>(component: ComponentType<T>, options: T) {
    // Do stuff
}
```

**Comment by zlepper** [comment]
That would not solve anything, rather your suggestion is outright wrong for the types given.  The purpose of those generics are to ensure that only valid data is passed to the component in options. 

The actual code we have uses this for opening dialogs and popups. In which case it's pretty important that they get valid args. 

I tried tweaking the playground a bit, to make it slightly more obvious, why I think the current behavior is wrong:

https://www.typescriptlang.org/play/#src=interface%20DataComponent%3CT%3E%20%7B%0D%0A%20%20%20%20data%3A%20T%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20Args%20%7B%0D%0A%20%20%20%20name%3A%20string%3B%0D%0A%20%20%20%20margin%3F%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Aclass%20SuperComponent%20%7B%0D%0A%20%20%20%20constructor(public%20data%3A%20Args)%20%7B%0D%0A%20%20%20%20%20%20%20%20console.log(this.data)%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0A%0D%0Ainterface%20Options%3CT%3E%20%7B%0D%0A%20%20%20%20data%3A%20T%3B%0D%0A%7D%0D%0A%0D%0Aexport%20interface%20ComponentType%3CT%3E%20%7B%0D%0A%20%20%20%20new%20(...args%3A%20any%5B%5D)%3A%20T%3B%0D%0A%7D%0D%0A%0D%0Afunction%20openComponent%3CY%2C%20T%20extends%20DataComponent%3CY%3E%3E(component%3A%20ComponentType%3CT%3E%2C%20options%3A%20Options%3CY%3E)%20%7B%0D%0A%20%20%20%20%2F%2F%20Summerized%20as%3A%0D%0A%20%20%20%20return%20new%20component(options.data)%3B%0D%0A%7D%0D%0A%0D%0A(function%20()%20%7B%0D%0A%0D%0A%20%20%20%20openComponent(SuperComponent%2C%20%7B%0D%0A%20%20%20%20%20%20%20%20data%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20name%3A%20'hello%20world!'%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20margin%3A%20'super%20duper'%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%7D)%3B%0D%0A%0D%0A%7D)()%3B%0D%0A

**Comment by zlepper** [comment]
Hmmm. Actually, I think I see the problem. Typescript doesn't know which of the two options for the generic is the correct one, and therefore goes with the safe option of giving and error on the weaker constraint...

Will have to rethink that then. Thank you. Will go bother people on stackoverflow instead.
