### ISSUE TITLE
'.symbol' baselines don't always get generated, even after a full 'jake runtests'

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#2822]
I updated the compiler such that a file no longer generated errors. When I did a `jake runtests`, I got a new `.types `file and the `.errors.txt` file disappeared. However, only after I did a `jake runtests` did I get the `.symbols` file.

**Comment by mhegazy** [comment]
so you had to run jake runtests twice to get the file?

**Comment by mhegazy** [comment]
and how is this different from #2806?

**Comment by DanielRosenwasser** [comment]
Yes I had to run `jake runtests` twice.

#2806 is probably a symptom of this.
