### ISSUE TITLE
An interface should not depend on its signatures

### ISSUE THREAD

**Issue by JsonFreeman** [Microsoft/TypeScript#2823]
In section 3.9, it says what kinds of constructs depend on what type references when resolving a type alias. An interface or class should not depend on any of its members. Namely, the following should work:
```ts
var s: stringOrFoo;
type stringOrFoo = string | Foo;
interface Foo {
    (): stringOrFoo;
}
```
But this gives a circular reference error because Foo depends on the return types of its call/construct signatures.

This is also observable with indexers:
```ts
var s: stringOrFoo;
type stringOrFoo = string | Foo;
interface Foo {
    [s: string]: stringOrFoo;
}
```
A type should not depend on its indexer types either.

**Comment by JsonFreeman** [comment]
For the indexer case, this bug applies to classes as well.

**Comment by ahejlsberg** [comment]
This looks like a relatively simple fix. We need to lazily compute the following InterfaceType members that we eagerly compute today:

* declaredCallSignatures
* declaredConstructSignatures
* declaredStringIndexType
* declaredNumberIndexType

**Comment by JsonFreeman** [comment]
Yup, exactly. I did it already for base types. It should be a similar procedure for these.
