### ISSUE TITLE
error TS1345: An expression of type 'void' cannot be tested for truthiness - console.log(x) || x

### ISSUE THREAD

**Issue by rolandpeelen** [Microsoft/TypeScript#28248]
In a functional context, I often use loggers like this;
```
const logger = (...args) => console.log(args) || args;
```
As `console.log()` returns undefined, it will always fall through the next argument. However, my angular project now no longer compiles.

-->

**TypeScript Version:**  3.1.4

**Search Terms:** 
error TS1345: An expression of type 'void' cannot be tested for truthiness
found some issues, but not the same.
**Code**

```ts
const logger = (...args) => console.log(args) || args;
```

**Expected behavior:**
Compile

**Actual behavior:**
gives error

**Comment by j-oliveras** [comment]
Change it to use comma operator:
```ts
const logger = (...args) => (console.log(args), args);
```

See the discussion about this change: #26262.

**Comment by j-oliveras** [comment]
@RyanCavanaugh or @DanielRosenwasser, probably you should add `Use of 'void' in control flow constructs is now disallowed` to the breaking changes wiki page.

**Comment by rolandpeelen** [comment]
closed as duplicate

**Comment by stavalfi** [comment]
`.then(x=> console.log(x) || x)` is a type error. 

How can we turn off this rule?
