### ISSUE TITLE
Incorrect enum assignment

### ISSUE THREAD

**Issue by KSXGitHub** [Microsoft/TypeScript#28246]
**TypeScript Version:**  3.2.0-dev.201xxxxx

**Search Terms:**

**Code**

```ts
enum Foo {
    Zero = 0,
    Two,
    One = 1
}

// Expecting: 2 (or at least a value different than 0 or 1)
// Received: 1 (which is already assigned to Foo.One)
console.log(Foo.Two)

// Expecting: 'Two'
// Received: 'One'
console.log(Foo[Foo.Two])
```

**Expected behavior:**

It prints 2 (or a value that isn't 0 or 1) and `Two`

**Actual behavior:**

It prints 1 and `One` instead

**Playground Link:** [link](https://www.typescriptlang.org/play/#src=enum%20Foo%20%7B%0D%0A%20%20%20%20Zero%20%3D%200%2C%0D%0A%20%20%20%20Two%2C%0D%0A%20%20%20%20One%20%3D%201%0D%0A%7D%0D%0A%0D%0Aalert(%60%0D%0AFoo.Two%20%3D%20%24%7BFoo.Two%7D%0D%0AFoo%5BFoo.Two%5D%20%3D%20%24%7BFoo%5BFoo.Two%5D%7D%0D%0A%60)%0D%0A)

**Comment by j-oliveras** [comment]
Working as intended. See [Numeric enums](http://www.typescriptlang.org/docs/handbook/enums.html#numeric-enums) on handbook.

**Comment by KSXGitHub** [comment]
> Working as intended. See [Numeric enums](http://www.typescriptlang.org/docs/handbook/enums.html#numeric-enums) on handbook.

Then change the intended behavior, the current behavior is **error-prone**. It's either forbidding user from explicitly defining an enum without explicitly defining preceding enum or change the way of assigning implicit enums.

Beside, I don't think this behavior is intended either. The code you were referring to has explicit enum all at the top and implicit enum at the bottom whereat my code has explicit enum at two ends and implicit enums at the middle.

**Comment by AnyhowStep** [comment]
I'm against changing the current behaviour. I doubt there's much real-world code that uses enums in this way but if there is, such a change would result in *very confusing* bugs suddenly popping up.

It's a pretty huge breaking change.

**Comment by KSXGitHub** [comment]
> I'm against changing the current behaviour

The other option is preventing user from doing this.

> It's a pretty huge breaking change.

I don't think so, as you can see above, `Foo[Foo.Two]` does not return `'Two'`. It is a bug.

**Comment by weswigham** [comment]
Automatic numbering for enums picks up from the closest explicit number above the member, and this is well-documented.

**Comment by KSXGitHub** [comment]
Then I think TypeScript should prevent user from explicitly defining `One = 1`

**Comment by weswigham** [comment]
You should consider writing a lint rule to that effect. Since we actually make use of how multiple keys can map to the same value within the compiler itself to provide backwards compatible member names when we rename things, and to reuse certain names when space in a flags enum is at a premium, this is highly unlikely to change at the language level.
