### ISSUE TITLE
`as` expression and array of union types

### ISSUE THREAD

**Issue by agentcooper** [microsoft/TypeScript#28251]
I'm not 100% sure this is a bug, but the behavior is not clear to me. 

As a part of the state object I have an array that I want to be inferred as an array of the union type. I know this can be done by providing a type for the whole state (`const state: State = ...`), but I would like to rely on type inference since there are many other state properties of primitive types.

```typescript
type Fruit = "banana" | "apple";

// option 1

const state1 = {
    // OK: works as expected
    fruits: (["banana", "apple"] as Array<Fruit>),
    expression: 1 + 2
};

// option 2

const state2_1 = {
    // OK: error is expected
    fruits: [1, 2, 3] as Array<Fruit>,
    expression: 1 + 2
}

const state2_2 = {
    // NOT OK: error is expected, but not shown!
    fruits: ["banana", "apple", "potato"] as Array<Fruit>,
    expression: 1 + 2
}

// option 3

function inferAsUnionArray<K, T extends K = K>(input: Array<T>) {
    const out: Array<K> = input;
    return out;
}

const state3 = {
    // OK: error as expected. can this be done easier?
    fruits: inferAsUnionArray<Fruit>(["banana", "apple", "potato"]),
    expression: 1 + 2
};
```

[Playground link](https://www.typescriptlang.org/play/index.html#src=type%20Fruit%20%3D%20%22banana%22%20%7C%20%22apple%22%3B%0D%0A%0D%0A%2F%2F%20option%201%0D%0A%0D%0Aconst%20state1%20%3D%20%7B%0D%0A%20%20%20%20%2F%2F%20OK%3A%20works%20as%20expected%0D%0A%20%20%20%20fruits%3A%20(%5B%22banana%22%2C%20%22apple%22%5D%20as%20Array%3CFruit%3E)%2C%0D%0A%20%20%20%20expression%3A%201%20%2B%202%0D%0A%7D%3B%0D%0A%0D%0A%2F%2F%20option%202%0D%0A%0D%0Aconst%20state2_1%20%3D%20%7B%0D%0A%20%20%20%20%2F%2F%20OK%3A%20error%20is%20expected%0D%0A%20%20%20%20fruits%3A%20%5B1%2C%202%2C%203%5D%20as%20Array%3CFruit%3E%2C%0D%0A%20%20%20%20expression%3A%201%20%2B%202%0D%0A%7D%0D%0A%0D%0Aconst%20state2_2%20%3D%20%7B%0D%0A%20%20%20%20%2F%2F%20NOT%20OK%3A%20error%20is%20expected%2C%20but%20not%20shown!%0D%0A%20%20%20%20fruits%3A%20%5B%22banana%22%2C%20%22apple%22%2C%20%22potato%22%5D%20as%20Array%3CFruit%3E%2C%0D%0A%20%20%20%20expression%3A%201%20%2B%202%0D%0A%7D%0D%0A%0D%0A%2F%2F%20option%203%0D%0A%0D%0Afunction%20inferAsUnionArray%3CK%2C%20T%20extends%20K%20%3D%20K%3E(input%3A%20Array%3CT%3E)%20%7B%0D%0A%20%20%20%20const%20out%3A%20Array%3CK%3E%20%3D%20input%3B%0D%0A%20%20%20%20return%20out%3B%0D%0A%7D%0D%0A%0D%0Aconst%20state3%20%3D%20%7B%0D%0A%20%20%20%20%2F%2F%20OK%3A%20error%20as%20expected.%20can%20this%20be%20done%20easier%3F%0D%0A%20%20%20%20fruits%3A%20inferAsUnionArray%3CFruit%3E(%5B%22banana%22%2C%20%22apple%22%2C%20%22potato%22%5D)%2C%0D%0A%20%20%20%20expression%3A%201%20%2B%202%0D%0A%7D%3B%0D%0A%0D%0A).

**Comment by AnyhowStep** [comment]
There is no "static assert" in the C++ sense in TS. Although I wish there was...

I use a similar "hack" as your `state3`, sometimes

**Comment by weswigham** [comment]
Casts allow any types that possibly overlap to be converted. What you want is indeed a kind of type assertion expression. The function call is currently the best safe way to do it, IMO. We have an open issue tracking related suggestions: https://github.com/Microsoft/TypeScript/issues/26064 I'd chime in there.
