### ISSUE TITLE
Event.srcElement has incorrect type

### ISSUE THREAD

**Issue by FrogTheFrog** [Microsoft/TypeScript#28252]
Currently `Event.srcElement` has an `Element | null` type, however according to [Mozzila docs](https://developer.mozilla.org/en-US/docs/Web/API/Event/srcElement) it is an alias for `Event.target` which has type `EventTarget | null`. Furthermore, [DOM Standard](https://dom.spec.whatwg.org/#event) also specifies that it should be of type `EventTarget`.

`Event.srcElement` was brought back by https://github.com/Microsoft/TSJS-lib-generator/commit/ba2728a43eefba902ea732f3fee59bcb203e8a2b commit, however for some reason `Element` type was chosen.

**Comment by weswigham** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

We'll have to double check that the less specific type isn't depended upon by a large set of real code.
