### ISSUE TITLE
Allow acronym cjs as an argument to CLI option `--module`

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#2826]
I'm very lazy at typing `commonjs` in the terminal. Maybe you should allow people to just type cjs?
```
tsc test.ts -m cjs
```

It is very "common" that we refer `commonjs` as `cjs`.

**Comment by CyrusNajmabadi** [comment]
I think this is better served with shell features (like shell aliases and whatnot).

**Comment by tinganho** [comment]
@CyrusNajmabadi I think setting shell alias would be even more cumbersome.

**Comment by RyanCavanaugh** [comment]
Erring on the side of clarity vs typing convenience.
