### ISSUE TITLE
No compatible call signatures in function types with generics

### ISSUE THREAD

**Issue by jsnick** [Microsoft/TypeScript#28262]
**Search Terms:**

**Code**

```ts
function makeABMethods() {
  const methods = {
    a: function <T>(arg: T) {
      return (args: T[] = []) => args;
    },
    b: function <T>(arg: T) {
      return (argOrArgs: T | T[]) =>{
        if (argOrArgs instanceof Array) {
          return [...argOrArgs, arg];
        } else {
          return [argOrArgs, arg];
        }
      };
    }
  }
  type MethodNames = keyof typeof methods;

  let obj: { [key in MethodNames]?: ReturnType<typeof methods[key]> } = {};
  for(const name of Object.keys(methods)) {
    obj = Object.assign(obj, methods[name as MethodNames]('this is error!')); // (1) error line
  }

  return obj as Required<typeof obj>;
}

const methods = makeABMethods();
methods.a // (2) How can I infer this to `(args?: string[]) => string[]` 
```

**Expected behavior:**

no errors.

**Actual behavior:**
at `(1) error line`
```
Cannot invoke an expression whose type lacks a call signature. Type '(<T>(arg: T) => (args?: T[]) => T[]) | (<T>(arg: T) => (argOrArgs: T | T[]) => T[])' has no compatible call signatures.
```

**Playground Link:** 
[Link](https://www.typescriptlang.org/play/index.html#src=function%20makeABMethods()%20%7B%0D%0A%20%20const%20methods%20%3D%20%7B%0D%0A%20%20%20%20a%3A%20function%20%3CT%3E(arg%3A%20T)%20%7B%0D%0A%20%20%20%20%20%20return%20(args%3A%20T%5B%5D%20%3D%20%5B%5D)%20%3D%3E%20args%3B%20%2F%2F%20if%20this%20function%20argument%20type%20is%20not%20optional%2C%20then%20no%20errors.%0D%0A%20%20%20%20%7D%2C%0D%0A%20%20%20%20b%3A%20function%20%3CT%3E(arg%3A%20T)%20%7B%0D%0A%20%20%20%20%20%20return%20(argOrArgs%3A%20T%20%7C%20T%5B%5D)%20%3D%3E%7B%0D%0A%20%20%20%20%20%20%20%20if%20(argOrArgs%20instanceof%20Array)%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20return%20%5B...argOrArgs%2C%20arg%5D%3B%0D%0A%20%20%20%20%20%20%20%20%7D%20else%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20return%20%5BargOrArgs%2C%20arg%5D%3B%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%20%20%7D%3B%0D%0A%20%20%20%20%7D%0D%0A%20%20%7D%0D%0A%20%20type%20MethodNames%20%3D%20keyof%20typeof%20methods%3B%0D%0A%0D%0A%20%20let%20obj%3A%20%7B%20%5Bkey%20in%20MethodNames%5D%3F%3A%20ReturnType%3Ctypeof%20methods%5Bkey%5D%3E%20%7D%20%3D%20%7B%7D%3B%0D%0A%20%20for(const%20name%20of%20Object.keys(methods))%20%7B%0D%0A%20%20%20%20obj%20%3D%20Object.assign(obj%2C%20methods%5Bname%20as%20MethodNames%5D('this%20is%20error!'))%3B%0D%0A%20%20%7D%0D%0A%0D%0A%20%20return%20obj%20as%20Required%3Ctypeof%20obj%3E%3B%0D%0A%7D%0D%0A%0D%0Aconst%20methods%20%3D%20makeABMethods()%3B%0D%0Amethods.a)

**Related Issues:**

**Comment by weswigham** [comment]
Duplicate of #7294 - I'd chime in there.
