### ISSUE TITLE
Allow class/function rename to be triggered on declaration keywords and modifiers

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#28268]
## Search Terms
- rename

## Suggestion
Follow up on https://github.com/Microsoft/vscode/issues/58907

Allow renames to be triggered on keywords such as `public`, `private`, `class`, `const`, `readonly`, and `function` to rename the symbol itself 

```ts
class Foo {
    public bar() { }
}

function func() { }

const x = 1;
```

Use the `triggerSpan` property on the `renameResponse` to actually trigger the rename on the symbol. 

We currently return `"You cannot rename this element."` for these cases

**Comment by DanielRosenwasser** [comment]
Word of caution to make sure that this doesn't interfere with document highlights. Today, if you're hovering on

```ts
class C {
  /**/public foo;
  public bar;
}
```

we highlight all occurrences of the `public` keyword within `C`.

**Comment by RyanCavanaugh** [comment]
@DanielRosenwasser is that a bug or a feature? The current behavior re: `public` seems useless

**Comment by DanielRosenwasser** [comment]
That's a feature - document highlights aims to make it easy to scan through relevant/related declarations and constructs (e.g. the `switch`/`case`/`break` keywords and every `export`-ed declaration). I don't see this as any different.

It's also more consistent with the rest of the editor's visual cues (e.g. the way that VS Code highlights all occurrences of a word in a plain text buffer works more similarly to how we highlight the `export` keyword than find-all-references).

**Comment by rbuckton** [comment]
@DanielRosenwasser: We currently highlight occurrences of the class or function name when you put the cursor on `class` or `function`. Should we change that to highlight occurrences of the `class`/`function` keyword instead to align with that behavior? We currently don't highlight occurrences of keywords like `interface`, `type`, `enum`, `module`, or `namespace` today either.
