### ISSUE TITLE
Codefix for 'cannot find name' in for loop

### ISSUE THREAD

**Issue by andy-ms** [microsoft/TypeScript#28275]
**TypeScript Version:**  3.2.0-dev.20181031

**Code**

```ts
for (x of []) {}
```

**Expected behavior:**

Codefix to convert to `for (const x of []) {}`

**Actual behavior:**

No codefix. It just says `Cannot find name 'x'.`. What do you mean you can't find it? It's right there! After all this time I still have to stare at this for a while to realize the error.

**Comment by rflorian** [comment]
I am having a look at this. 
@andy-ms Would `"Add const modifier to unresolved variable"` be an appropriate display text for the codefix? This would be extendable into `"Add const modifiers to all unresolved variables"` for the codeFixAll.
