### ISSUE TITLE
Import module based on path relative to project root (tsconfig.json).

### ISSUE THREAD

**Issue by vilic** [Microsoft/TypeScript#2828]
Counting `../../../` is painful, it would be great if TypeScript compiler could convert something like `~/modules/my-module` for us based on project root and file path.

**Comment by tinganho** [comment]
:+1:

**Comment by mhegazy** [comment]
this should be handled in #2338, by setting a Path mapping for "~*" : "..\..\..\..\Root\*"

**Comment by cojack** [comment]
@mhegazy and it's possible? Because this issue #2338 is closed, and I did not find any solution there.

**Comment by mhegazy** [comment]
#2338 gives you a way to tell the compiler where the files are, the compiler is not going to rewrite `~/` for you to be `../.././../`. see https://github.com/Microsoft/TypeScript/issues/15479 for more details.
