### ISSUE TITLE
Compiler is forgetting the basetype of an extended type when that type is generic

### ISSUE THREAD

**Issue by 9SMTM6** [microsoft/TypeScript#28280]
I have only done TS for about a 3/4 of a month, and JS for less than 2 months, so maybe I'm just doing someting fundamentally wrong, but after questioning people that have done this for some time I think these are some compiler-issues.

On an somewhat related note, if any of you managed to implement the 'Basic example' from [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) in TS without errors or using //@ts-ignore please let me know. Also why is 'Proxy' in the ES2015 lib and not in the 'ES6' lib, and whats the difference between these libs?

**TypeScript Version:**  3.1.5 and 3.2.0-dev.20181101

**Search Terms:** generic, extend, extended, base-type, basetype, type

**Code**

```ts
// ------------------- with generic type -------------------//
const extGenTypeFactory = <TObj extends Object>(specialObj: TObj) => {
    /**
     * Throws 'TS2312: An interface may only extend a class or another interface.'. 
     * Doesnt compile the stuff using the interfaces and themself
     */
    interface TExtObj extends TObj {
        newAttr: any
    }
    // works
    let newObj = specialObj;

    let extObj: TExtObj
    // This particular issue is Solved in 3.2, keeping it for understanding of the comment line
    // TS2698: 'Spread types may only be created from object types.'. 
    extObj = {
        ...specialObj,
        newAttr: "some other"
    }
    return extObj
}

// Tried to evade problem with suggestion from 'Why doesn't type inference work on this interface: interface Foo<T> { } ?'
const obj = extGenTypeFactory({ attr: "take that" })

// works fine
const genTypeFactory= <TObj>(specialObj: TObj) => {
    return specialObj;
}
// \------------------- with generic type -------------------//

// ------------------- with known type -------------------//
interface TObj extends Object {
    hasAttr: any
}
/**
 * Works fine.
 */
interface TExtObj extends TObj {
    newAttr: any
}
// \------------------- with known type -------------------//
```

**Expected behavior:**
Compiles without error
**Actual behavior:**
Throws TS2312 and TS2698
**Playground Link:** 

**Related Issues:**

**Comment by weswigham** [comment]
>Also why is 'Proxy' in the ES2015 lib and not in the 'ES6' lib, and whats the difference between these libs?

ES2015 _is_ es6. When es6 was published they formally started a by-year versioning scheme; so es6 and es2015 are synonymous.

**Comment by weswigham** [comment]
Secondly: An interface cannot inherit from a variable type parameter. If you want similar behavior, you want to use intersection types, like so:
```ts
    type TExtObj = TObj & {
        newAttr: any
    }
```
Thirdly: Capital `O` `Object` refers to the global `Object` constructor base type. You probably don't want that - you probably want the `object` (lower case `o`) primitive instead.

Fourth: Spreads are currently limited to concrete types - you cannot spread a generic. This will change in 3.2, thanks to #28234.

**Comment by 9SMTM6** [comment]
> ES2015 _is_ es6. When es6 was published they formally started a by-year versioning scheme; so es6 and es2015 are synonymous.

Well, this is embarassing. Other than what you might think I am capable of performing a google search, so when i got an `Cannot find name` error on an `Proxy` keyword while having es6 in the `libs` variable of the tsconfig, I was really out of my depth. Even more so when I tried it with `es2015 `and it worked. But upon retry `es6` works perfectly, so it mustve been an user error somewhere.

> Secondly: An interface cannot inherit from a variable type parameter

Well yeah, thats more or less what I'm saying. Do you mean to say that this is by design? Why would you want to do that?

Thanks for the hint with the intersection types. It could very well work, I'll try and report back.

> Thirdly: Capital O Object refers to the global Object constructor base type. You probably don't want that - you probably want the object (lower case o) primitive instead.

`Object` can refer to both the constructor and an interface exposing js-object functionality. Thats as far as I understood one of the beauties of TS, and also gets supported by VSCode. If I use `Object` as an Interface it says so (and tsc doesnt throw an error), if I use it as an constructor it also says so and doesnt throw errors. Meanwhile using `object` will throw 'Cannot find name'. 

> Fourth: Spreads are currently limited to concrete types - you cannot spread a generic. This will change in 3.2, thanks to #28234.

Good to know, thanks. Hard to test though, as the issue described above is causing issues (Compiler specifically says that its not an object not only upon use of the spread operator but also the interface inheritance.), and here the Compiler of course already resolved it:

```ts
const genTypeFactory = <T>(param: T) => {
    return param;
}

const reWrapped = {...genTypeFactory({attr: "someVal"})}
```
