### ISSUE TITLE
Error message at `a constant or a read-only property` could be more specific

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#28297]
**TypeScript Version:** 3.2.0-dev.20181101

**Code**

```ts
const isMutable = false;
isMutable = true;
```

**Expected behavior:**

`Cannot assign to 'isMutable' because it is a constant.`

**Actual behavior:**

`Cannot assign to 'isMutable' because it is a constant or a read-only property.` It's obviously not a property, and the compiler should be able to tell this. Note this is more tricky with `namespace N { export const x = 0; }`, which is also a property, but I think calling it just "a constant" in that case is fine.

**Comment by a-tarasyuk** [comment]
@andy-ms What about the [following case](https://www.typescriptlang.org/play/#src=Array%20%3D%20%5B%5D%3B)?

```typescript
Array = [];
```

Which error message is correct? 

```shell
Cannot assign to 'Array' because it is a constant.
```

or
 
```shell
Cannot assign to 'Array' because it is a constant or a read-only property.
```

**Comment by andy-ms** [comment]
That's declared as `declare const Array: ArrayConstructor;` so it should be the former case ("because it is a constant.").

**Comment by a-tarasyuk** [comment]
@andy-ms ok, created PR for this suggestion

**Comment by DanielRosenwasser** [comment]
Thanks @a-tarasyuk!
