### ISSUE TITLE
Emit actually-private members for classes, for runtime.

### ISSUE THREAD

**Issue by trusktr** [Microsoft/TypeScript#28291]
## Suggestion

I already read [the FAQ regarding this](https://github.com/Microsoft/TypeScript/wiki/FAQ#you-should-emit-classes-like-this-so-they-have-real-private-members), but private members **_are_** possible, and it'd be nice to (optionally) have them at runtime.

## Use Cases

So people interacting with your code at runtime experience the restrictions we desired them to have. They might not use TypeScript.

## Examples

See [`lowclass`](https://github.com/trusktr/lowclass/) (look at the extensive tests files showing all sorts of uses of runtime public/protected/private members). The implementation is not long, and some features can be omitted in order just to have the minimal protected/private functionality.

It uses WeakMaps to store protected/private state.

Babel also has [private member feature](https://github.com/babel/proposals/issues/12#issuecomment-410115104).

## Checklist

My suggestion meets these guidelines:
* [ ] This wouldn't be a breaking change in existing TypeScript / JavaScript code
   - It will break *JavaScript* code that is improperly relying on emitted internals that should be private.
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
   - Same as previous.
* [ ] This could be implemented without emitting different JS based on the types of the expressions
   - emits different runtime code
* [ ] This isn't a runtime feature (e.g. new expression-level syntax)
   - it is basically a runtime feature, doesn't change anything related to types.

**Comment by weswigham** [comment]
You should be monitoring #9950 for implementation of the official ECMAScript runtime privacy proposal.

**Comment by trusktr** [comment]
Oh sweeet, and sorry. Closing this one.
