### ISSUE TITLE
typesVersions should not be affected by `"types": ""`

### ISSUE THREAD

**Issue by andy-ms** [microsoft/TypeScript#28304]
**TypeScript Version:**  3.2.0-dev.20181101

**Code**

(This is just `typesVersions.justIndex.ts` plus `"types": "",`)

```ts
// @baseUrl: /
// @traceResolution: true
// @target: esnext
// @module: commonjs

// @filename: /a/package.json
{
    "types": "",
    "typesVersions": {
        ">=3.1.0-0": { "*" : ["ts3.1/*"] }
    }
}

// @filename: /a/ts3.1/index.d.ts
export const a = 0;

// @filename: /b/user.ts
import { a } from "a";
```

**Expected behavior:**

No error.

**Actual behavior:**

Module resolution fails. The trace indicates that it is now looking for a file named `"*.d.ts"` instead of parsing the pattern correctly.

**Comment by rbuckton** [comment]
According to the documentation for [Node's module resolution](https://nodejs.org/dist/latest-v12.x/docs/api/modules.html#modules_all_together):

> ```
> LOAD_AS_DIRECTORY(X)
> 1. If X/package.json is a file,
>    a. Parse X/package.json, and look for "main" field.
>    b. If "main" is a falsy value, GOTO 2.
>    c. let M = X + (json main field)
>    d. LOAD_AS_FILE(M)
>    e. LOAD_INDEX(M)
>    f. LOAD_INDEX(X) DEPRECATED
>    g. THROW "not found"
> 2. LOAD_INDEX(X)
```

Step 1.b. indicates we should ignore a "falsy" value for `"main"`, and we should probably do the same for `"types"`, however in both cases we only check for `undefined` and allow `""`.
