### ISSUE TITLE
TSServer: performance problems after typing when using tsconfig.json in large project

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#2830]
Here is my setup

tsconfig.json with the following content:
{
    "compilerOptions": {
        "module": "amd",
        "noImplicitAny": true,
        "removeComments": false,
        "preserveConstEnums": true,
	"target": "ES5",
        "sourceMap": false
    }
}

Our workspace has around 900 ts files which are all covered by the above tsconfig.json

Steps to reproduce:

- open any file is such a workspace
- request completions via the tsserver
- type a character in that file
- request completions again. 

Observe: fulfilling this request takes between 1800 and 2000 ms on my Lenevo T430s

I debugged it a little and around 90% of the time is spend in sznchronizeHostData, and there in createProgram. It looks like that all files listed in a tsconfig.json are treated as root files and changing one file flushes the whole compiler.

**Comment by mhegazy** [comment]
@dbaeumer i have not been able to repro this locally. are you still seeing this issue?

**Comment by dbaeumer** [comment]
@mhegazy Vladimir is working on improving this.

**Comment by mhegazy** [comment]
@vladima has a fix for this in #3616

**Comment by vladima** [comment]
fixed in #4154
