### ISSUE TITLE
API: Make public internal chainBundle

### ISSUE THREAD

**Issue by cevek** [microsoft/TypeScript#28310]
**TypeScript Version:**  3.2.0-dev.201xxxxx

Currently we can't work with bundles in transformers, but built-in transformers use `chainBundle` to iterate over sourceFiles inside them

```
return chainBundle(transformSourceFile);
```

So, we need something similar or opened `chainBundle` to use in the custom transformers

**Comment by SalvatorePreviti** [comment]
+1, it would be really helpful.
