### ISSUE TITLE
TSServer: completions request should return isMemberCompletion & isNewIdentifierLocation

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#2831]
This eases the proposal of snippets on the editor side. For example if the completions are member completions no or different snippets can be provided

**Comment by mhegazy** [comment]
Thanks @dbaeumer. PRs welcomed

**Comment by mhegazy** [comment]
As we talked earlier, VSCode will also need some information about the lexical location for the completion. @mjbvz can you provide the full list of flags needed?

**Comment by mjbvz** [comment]
I believe this has been handled by #17488
