### ISSUE TITLE
TypeError: Object prototype may only be an Object or null: undefined

### ISSUE THREAD

**Issue by oleersoy** [Microsoft/TypeScript#28314]
I wrote this up on SO first, to see what others thought:
https://stackoverflow.com/questions/53122751/typeerror-object-prototype-may-only-be-an-object-or-null-undefined

I don't think importing `Entity` from `index.ts` (Where it is being re exported) rather than from `Entity.ts`, should matter.  Thoughts?  I can produce a minimal github repository with all the code in it if need be.

**Comment by mattmccutchen** [comment]
The problem was a circular import.  TypeScript won't add checking for circular imports; see #21780.

**Comment by oleersoy** [comment]
Just adding a stackblitz demo as a reference:
https://stackblitz.com/edit/typescript-ztvxdz

**Comment by oleersoy** [comment]
I'll just add my thoughts.  Obviously it's a simple work around, I just think it's strange that it exists, and at a minimum it does not have better error reporting.

It seems like this is actually not a circular import.  The reason it's not is that `Run.ts` needs `Customer`.  it load is from `index.ts`.  `Customer` knows that it needs `entity`.  The location of `Entity` is also defined in `index.ts`, but that should be ok.  The runtime should not start running stuff until the runtime definition of `Customer` is complete, so the lookup and loading of `Entity` should happen before the runtime can can attempt to create an instance of `Customer`.

**Comment by oleersoy** [comment]
I suspect that many will see this error in the future, because a lot of us reexport from a central `index.ts`.  Since we are doing that, it's tempting to import from `index.ts` in order to shorten the import path instead of importing the module directly.  

At first it seemed that this was fine because there were no warnings from VSCode ...
