### ISSUE TITLE
Typings for recompose return "does not exist on type value" error

### ISSUE THREAD

**Issue by ravecat** [Microsoft/TypeScript#28322]
**TypeScript Version:**  3.2.0-dev.20181102

**Search Terms:** 
- typescript does not exist on type compose
- typescript does not exist on type compose hocs

**Code**

```ts
import { withState, withHandlers, compose } from "recompose";
import { withTheme } from "common/helpers";
import Collapse from "./Collapse";

export default compose(
  withTheme,
  withState("condition", "handleClick", false),
  withHandlers({
    handleClick: ({ handleClick }) => () =>
      handleClick((condition: boolean) => !condition)
  })
)(Collapse);.
```

**Expected behavior:**
Build project without error

**Actual behavior:**
Get error 
>[!] (rpt2 plugin) Error: /home/max/project/styled-components-toolbox/src/components/Collapse/index.ts(7,29): semantic error TS2339 Property 'handleClick' does not exist on type '{}'.
src/components/Collapse/index.ts

**Playground Link:** 
Branch in repo https://github.com/ravecat/styled-components-toolbox/tree/feature/update-rollup
1. Clone repo https://github.com/ravecat/styled-components-toolbox.git
`git clone https://github.com/ravecat/styled-components-toolbox.git`
2. Checkout on branch 
`git checkout -b feature/update-rollup origin/feature/update-rollup`
2. Run console command `yarn`
3. Run another console command `yarn build`

**Related Issues:** 
https://github.com/acdlite/recompose/issues/231

**Comment by ahejlsberg** [comment]
@ravecat I'm closing this as the repro instructions don't work and the branches mentioned above don't appear to exist. Please open a new issue if you think there is still a problem.
