### ISSUE TITLE
Hard to reproduce older build environment

### ISSUE THREAD

**Issue by saschanaz** [Microsoft/TypeScript#28327]
So today I tried reviving #13574 (#26906) and faced dependency problem. TS's package.json marks every dependency as `latest` and ignores package-lock.json, so it's extremely hard to build with older commits.

Why can't we have normal semver for deps and use [greenkeeper](https://github.com/marketplace/greenkeeper) to constantly update to latest deps?

**Comment by RyanCavanaugh** [comment]
Doesn't seem like enough people are running into this
