### ISSUE TITLE
Use `interface` to force implementation of a `constructor` of a class

### ISSUE THREAD

**Issue by xpepermint** [Microsoft/TypeScript#28333]
I've searched the web and this repository but it seems nobody resolved this by now. 

I'd like to specify which constructors a user must implement when he/she is writing a class. Here's an example of how I'd expect this to look like:

```ts
interface UserBase {
   constructor(name: string);
   constructor(name: string, email: string);
   save(): this;
}
class User implements UserBase {
  public constructor(name: string) {
    // if this constructor is not present you see an error
  }
  public save() {
    return this;
  }
}
```

Currently, there's no way to force this other than using a static method that returns an instance of a class.

**Comment by DanielRosenwasser** [comment]
Sounds like you want a `static implements`, similar to #14600.

**Comment by aleksey-bykov** [comment]
might be a solution: https://github.com/Microsoft/TypeScript/issues/14600#issuecomment-437071092
