### ISSUE TITLE
Export default let/var not working

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#2833]
Are default let/var supported in TS?

```typescript
export default let variable1 = "string1";
export default var variable2 = "string2";
```

Right now they just throw a compile error:
```
error TS1005: ';' expected.
```

I'm currently using master for testing. And everything works by removing the `default` keyword.

**Comment by tinganho** [comment]
FYI `default const` also throws an error.

**Comment by mhegazy** [comment]
This is not supported by the ES6 module spec. only class and function declarations are allowed.

```ts
let variable1 = "string";
export default variable1;
```
