### ISSUE TITLE
Instances of classes created through object literals don't use class instance methods

### ISSUE THREAD

**Issue by LewisAndrewCampbell** [Microsoft/TypeScript#28330]
**TypeScript Version:**  3.0.1

object literal structural typing method call

```ts
class Point {
	constructor(readonly x: number, readonly y: number) { }
	toString() { return `${this.x}, ${this.y}` }	
}

const p1: Point = { x: 0, y: 0 }
const p2: Point = new Point(0, 0)

console.log(p1.toString())
console.log(p2.toString())
```

**Expected behavior:**
p1 and p2 to print the same thing

**Actual behavior:**
p1 bypasses the toString method, and just calls the generic object toString()

**Playground Link:** 
https://www.typescriptlang.org/play/#src=class%20Point%20{%0D%0A%09constructor(readonly%20x:%20number,%20readonly%20y:%20number)%20{%20}%0D%0A%09toString()%20{%20return%20%60${this.x},%20${this.y}%60%20}%09%0D%0A}%0D%0A%0D%0Aconst%20p:%20Point%20=%20{%20x:%200,%20y:%200%20}%0D%0A%0D%0Aalert(p.toString())

**Related Issues:**

**Comment by AlCalzone** [comment]
This is expected because p1 is no instance of Point. You just told Typescript that p1 should be structurally equivalent to Point, i.e. have the properties x and y

**Comment by DanielRosenwasser** [comment]
Types don't impact the runtime behavior, so this is expected. See https://github.com/Microsoft/TypeScript/wiki/FAQ#what-is-type-erasure

**Comment by michaeljota** [comment]
You don't have any warnings or errors because every object* in JavaScript have a `toString` method from Object prototype, so neither in assignment nor calling the method will throw because the method exists in runtime. If you change the method to another name, then you will realice that you must provide an implementation for your object.
