### ISSUE TITLE
TypeFlags outside small integer range

### ISSUE THREAD

**Issue by ahejlsberg** [Microsoft/TypeScript#28354]
In #25886 two extra `TypeFlags` were introduced and we're now using 32 bits. That's bad! Anything beyond the lower 30 bits (`1 << 29`) causes numbers to be boxed and positively wreaks havoc on performance. We know this first hand from previous overflows. We need to bring `TypeFlags` back down to 30 bits ASAP, and certainly before we ship the next RC or release. I'm surprised we merged the PR with this known issue (e.g. see [here](https://github.com/Microsoft/TypeScript/pull/25886/files#r204931387)).

**Comment by ahejlsberg** [comment]
@sheetalkamat I'm already working on a fix for this.

**Comment by sheetalkamat** [comment]
Ok thank you.
