### ISSUE TITLE
Comments after Spread Expression get stripped when targetting "ESNEXT"

### ISSUE THREAD

**Issue by azizhk** [Microsoft/TypeScript#28370]
So I've created a small reproducing repo: https://github.com/azizhk/typescript-comment-bug

Input: https://github.com/azizhk/typescript-comment-bug/blob/master/index.ts
Targetting ES2017 works: https://github.com/azizhk/typescript-comment-bug/blob/master/es2017.js
Targetting ESNEXT failes in two cases: https://github.com/azizhk/typescript-comment-bug/blob/master/esnext.js

The `/*#__PURE__*/` is for uglify, uglify-es, terser minification to show that if the return value is not used, it can drop the function call because it is pure and does not do any side effect.

If you can guide me what files correspond to this, I'll take a look and maybe contribute to fixing.

**Comment by weswigham** [comment]
It's probably be a part of `emitSpreadExpression` in `src/compiler/emitter.ts` - specifically, the `writePunctuation` call probably needs to be a `writeTokenWithComment` call.
