### ISSUE TITLE
Incorrect definition for atan2

### ISSUE THREAD

**Issue by mheavenor** [Microsoft/TypeScript#2837]
In core.d.ts the definition comment for atan2 is the following:

`Returns the angle (in radians) from the X axis to a point (y,x).`  

Although the function does take in the arguments in the order "y, x", the point in the comment should be defined as "point(x, y)" as this is the point on which the calculation is done.

**Comment by RyanCavanaugh** [comment]
I don't think the suggested edit improves clarity. It's incredibly easy to accidently write `atan2(x, y)`; reminding people that the order is reverse of normal is important.

**Comment by mheavenor** [comment]
I agree it is important to remind people that the order is reversed. Perhaps the comment should be reworded, however saying that the calculation is done on point (y, x) rather than point (x, y) is incorrect.

**Comment by mhegazy** [comment]
@RyanCavanaugh the change is in the comment. i think @mheavenor is correct.

**Comment by DanielRosenwasser** [comment]
Agreed with @mhegazy, I'm going to reopen. If we're reminding people of the order, let's just do that explicitly in the comment.

**Comment by RyanCavanaugh** [comment]
Let's just remove the `(y, x)` part from the comment altogether. It's confusing either way.
