### ISSUE TITLE
Warn user when importing the same export with different names

### ISSUE THREAD

**Issue by tmkn** [microsoft/TypeScript#28390]
**TypeScript Version:**  3.1.3

**Search Terms:**
import as

**Code**

```ts
import {
    ExpandAnimation as CSSExpand,
    ExpandAnimation as CSSCollapse
} from "./animations";
```

**Expected behavior:**
A warning that I'm importing the same thing twice under different names.

During some refactoring I ended up in this state where I import the same export under different names and then proceed to use those thinking I'm dealing with 2 different objects, but I actually just imported the same thing twice.

I feel this should be highlighted by TypeScript, since it's most likely not what you intended to do and since this is totally fine as far as syntax goes, it looks like a footgun.

**Actual behavior:**
Totally fine
**Playground Link:** 

**Related Issues:**

**Comment by tmkn** [comment]
Can you give some examples where such a construct is necessary as I fail to see the purpose?
If I'm not mistaken ES6 modules need to be statically analyzable, so you essentially end up with new identifiers who all point to the same thing anyway, doesn't sound very useful?
Since the main intention for the `import ... as` syntax is to resolve name clashes, using it to create new references to 1 single export feels like a wrong way of doing it.

While yes it is valid code, given the above, it doesn't really make sense to go unnoticed, just like:
```ts
let foo = {};
let data = {};
foo[data] = "bar";
```
Which TypeScript warns you about even though it's perfectly fine.

It doesn't need to be an error, handling it in the language service is also fine, just like the unused imports but it shouldn't go unnoticed.
Especially as imports need to be unique, so checking the imports was the last thing I did to solve that issue as I didn't think it was possible to actually reference the same thing twice by using `as`.

**Comment by RyanCavanaugh** [comment]
I'm not sure what the implied harm here is and it doesn't seem to be hurting anyone. It's a difficult mistake to make.

This is actually useful in some cases too, e.g.
```ts
import { superThing as foo, superThing as bar from "etc"

// Satisfy some external API contract.
const opts = {
 foo,
 bar
};
```

**Comment by jakebailey** [comment]
Also... 😄 

https://github.com/microsoft/TypeScript/blob/8336042ea3f84ad536a190ea75e47e74414e8081/src/compiler/watchPublic.ts#L85-L86
