### ISSUE TITLE
spec for ParameterProperties is outdated

### ISSUE THREAD

**Issue by ajafff** [microsoft/TypeScript#28395]
https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#831-constructor-parameters:

> A parameter of a ConstructorImplementation may be prefixed with a public, private, or protected modifier. 

This is missing `readonly`.

> A parameter property declaration may declare an optional parameter (by including a question mark or a default value), but the property introduced by such a declaration is always considered a required property

This is no longer true since the (not so) recent rewrite of the declaration emitter.

**Comment by MartinJohns** [comment]
The entire spec is outdated. The last real comit on it was nearly three years ago: https://github.com/Microsoft/TypeScript/commits/master/doc/spec.md

See also: https://github.com/Microsoft/TypeScript/issues?q=is%3Aopen+is%3Aissue+label%3ASpec  
And mainly: #15711

**Comment by RyanCavanaugh** [comment]
The spec is now an "archived" artifact and we won't be tracking defects against it anymore.
