### ISSUE TITLE
Worker constructor does not accept URL

### ISSUE THREAD

**Issue by TimvdLippe** [Microsoft/TypeScript#28397]
**TypeScript Version:**  3.2.0-dev.201xxxxx

**Search Terms:** worker new url, worker constructor

**Code**

```ts
new Worker(new URL(""))
```

**Expected behavior:** Compiles fine, as it is valid per the spec

**Actual behavior:**

> [ts] Argument of type 'URL' is not assignable to parameter of type 'string'.

**Playground Link:** http://www.typescriptlang.org/play/#src=new%20Worker(new%20URL(%22%22))%3B

**Related Issues:** #15338, #15246 and was recently updated in #28136 as well

**Comment by weswigham** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by TimvdLippe** [comment]
PR is up at https://github.com/Microsoft/TSJS-lib-generator/pull/600
