### ISSUE TITLE
Event "onselectstart" was removed from the interfaces

### ISSUE THREAD

**Issue by andrui** [Microsoft/TypeScript#28391]
Related to the file lib.dom.d.ts
Commit with removal: https://github.com/Microsoft/TypeScript/commit/ee25cdecbca49b2b5a290ecd65224f425b1d6a9c#diff-46fd87925e4552c166ec188712741c3f

**Comment by weswigham** [comment]
I'd guess because it's [experimental](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onselectstart).

**Comment by Misiu** [comment]
Please restore this event. AS mentioned in https://github.com/Microsoft/TSJS-lib-generator/pull/601 it is supported by various browsers.

**Comment by xobotyi** [comment]
+1
