### ISSUE TITLE
Typescript narrows variable type after callback modifies initial value

### ISSUE THREAD

**Issue by sherif-elmetainy** [Microsoft/TypeScript#28393]
**TypeScript Version:**  3.2.0-dev.20181107 and 3.1.6

**Search Terms:**

- TS2345 
- Callback
- Type narrowing

**Code:**
```ts
function f1<T>(a: T): (a: T) => void {
    return (b: T) => {};
}

function f2() {
    // initialise n to null
    let n: number | null = null; // type of n is narrowed to null
   const f3 = () => {
        n = 1;
    };
    f3(); // callback changes n to 1 (callback may or may not be called in my actual use case)
    const f4 = f1(n); // type of n is still narrowed to null which is wrong.
    // f4 has type (a: null) => void instead of (a: number|null) => void
    f4(1); // Error argument of type '1' is not assignable to parameter of type 'null'
}
```
Code is compiled with strict option (tsconfig.json below).
```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "strict": true
   }
}
```

**Expected behavior:**
No type error.

**Actual behavior:**
error TS2345: Argument of type '1' is not assignable to parameter of type 'null'.

**Workaround:**
Changing the call to f1 as follows:
```typescript
const f4 = f1(n as number|null);
```
However this shouldn't be needed because `n` is already defined as `number|null`.

**Related Issues:** 
#7719, #8541 and few referenced in the mentioned issues.

In the related issues I found, the reported issue was that the expected behaviour was that type **should** be narrowed. In my case the expected behaviour is type should **not** be narrowed, hence my thinking that this is not a duplicate.

**Comment by j-oliveras** [comment]
Related to #9998.
