### ISSUE TITLE
File casing issue with rename

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#28401]
**TypeScript Version:**  3.2.0-dev.20181107

**Code**

* Testing on windows in a project with no `tsconfig.json`.
* **a.ts**: `import { b } from "./B";`
* **b.ts**: `export const b = 0;`
* Open *just* `a.ts`.
* Rename `b` to `bee`.
* Vscode will open a new tab `B.ts`.
* Click on `b.ts` in the file explorer. Now `b.ts` and `B.ts` are open side-by-side.

**Expected behavior:**

There is no `b.ts` `B.ts` distinction on windows.

**Actual behavior:**

There is and we have two duplicate files.

Thanks to @rbuckton for discovering this.

**Comment by sheetalkamat** [comment]
Are there multiple projects open at that point? If not I think this isn't bug in tsserver but in vscode. We always prefer casing that user writes (in this case since the import is B file b.ts will be open with B.ts so I don't think its wrong on our part to send result as B.ts file name)

**Comment by andy-ms** [comment]
Moving to Microsoft/vscode#62797
