### ISSUE TITLE
variable typed as any improperly when object refer itself with type parameter

### ISSUE THREAD

**Issue by mmis1000** [Microsoft/TypeScript#28412]
**TypeScript Version:**  3.1.3

**Search Terms:**
type, infer
**Code**

```ts
class FailInfer<T>{
    constructor(arg: ()=>T){}
}

const failed = new FailInfer<number>(()=>failed)
```

**Expected behavior:**
The ts server knows `failed` should be `FailInfer<number>` and the callback is not correctly typed.
Or it should tell the user it can't determine what the type is and force user to choose a proper one.
**Actual behavior:**
The `failed` is typed as `any`, so no error happend

**Playground Link:** 
https://www.typescriptlang.org/play/#src=%0D%0Aclass%20FailInfer%3CT%3E%7B%0D%0A%20%20%20%20constructor(arg%3A%20()%3D%3ET)%7B%7D%0D%0A%7D%0D%0A%0D%0Aconst%20failed%20%3D%20new%20FailInfer%3Cnumber%3E(()%3D%3Efailed)
**Related Issues:**

**Comment by mmis1000** [comment]
However, the final result type is actully totally unrelated to i `failed` tself, the type parameter here is explicitly defined and unrelated to the type of `failed`

**Comment by AnyhowStep** [comment]
TS couldn't infer the type of `failed` because of reasons listed above and gave it an implicit type of `any`.

`any` is assignable to `number`.

**Comment by RyanCavanaugh** [comment]
Once a variable appears in its own initializer in a way that matters, it's always implicitly any. This is a known limitation of our current inference algorithm.
