### ISSUE TITLE
If no return after /* ... */, generate wrong js

### ISSUE THREAD

**Issue by heroboy** [Microsoft/TypeScript#2842]
```typescript
/*
aa
*/var c = 1;
```
generate
```
/*
aa
/*
aa
 var c = 1;
```

**Comment by DanielRosenwasser** [comment]
This is a duplicate of #1714, which we've since fixed. TypeScript 1.4.2, and TypeScript 1.5-alpha, should both have the correct behavior.

**Comment by DanielRosenwasser** [comment]
Sorry I referred to this as a duplicate; in fact, this might not be a duplicate, but it's since been fixed in the latest of TypeScript 1.4 and 1.5 alpha.
