### ISSUE TITLE
Add Guid Type As in C#

### ISSUE THREAD

**Issue by kmanev073** [Microsoft/TypeScript#28446]
## Search Terms

typescript guid, typescript guid type

## Suggestion

I am suggesting a new Guid data type to be added. A guid type jsut like in C#. Simply because now we are forced to use numerous npm packages and external libraries to achieve this functionality and this is adds dependencies to our apps.

## Use Cases

We are using guid primary key for our db records. In order to add a new record, we have to send a valid instance of our model to the back-end. In a case where the id is required field we need a way to generate a new guid or at least an elegant way of creating an empty guid.а

## Examples

```
//creating new instance of our model
Model instance = new Model(Guid.NewGuid(), "param2", "param2");

//checking if the id of our model is equal to an empty guid - 0000000-0000-0000-0000-000000000000
if (instance2.id === Guid.Empty()) {
}

```
## Checklist

My suggestion meets these guidelines:
* This wouldn't be a breaking change in existing TypeScript / JavaScript code
* This wouldn't change the runtime behavior of existing JavaScript code
* This could be implemented without emitting different JS based on the types of the expressions
* This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by DanielRosenwasser** [comment]
Your suggestion actually doesn't meet the guidelines: 

> This isn't a runtime feature

Check out this section from our [Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals):

> Provide additional runtime functionality or libraries. Instead, use TypeScript to describe existing libraries.
