### ISSUE TITLE
Duplicate identifier error in Visual Studio 2015 CTP

### ISSUE THREAD

**Issue by tomitrescak** [Microsoft/TypeScript#2844]
Hi

I create the new "typescript" project.
I generate the description file for the app.ts by `tsp --target es5 -d app.ts`

I immediately receive the duplicate identifier error.
I am not sure how to deal with this issue as I want to have both implementation and description files in my project.

Here are the files `app.ts`

```javascript
class Greeter {
    element: HTMLElement;
    span: HTMLElement;
    timerToken: number;

    constructor(element: HTMLElement) {
        this.element = element;
        this.element.innerHTML += "The time is: ";
        this.span = document.createElement('span');
        this.element.appendChild(this.span);
        this.span.innerText = new Date().toUTCString();
    }

    start() {
        this.timerToken = setInterval(() => this.span.innerHTML = new Date().toUTCString(), 500);
    }

    stop() {
        clearTimeout(this.timerToken);
    }

}

window.onload = () => {
    var el = document.getElementById('content');
    var greeter = new Greeter(el);
    greeter.start();
};
```

and `app.d.ts`

```javascript
declare class Greeter {
    element: HTMLElement;
    span: HTMLElement;
    timerToken: number;
    constructor(element: HTMLElement);
    start(): void;
    stop(): void;
}
```

**Comment by DanielRosenwasser** [comment]
Do you mean that you're receiving duplicate identifier errors in VS when you have `app.ts` and `app.d.ts` (or another file that refers to `app.d.ts`) open at the same time?

Also could you be more specific with which duplicate identifier errors you're getting from underscore.d.ts?

**Comment by tomitrescak** [comment]
I have both app.ts and app.d.ts in my project and I am receiving duplicate identifier error. Removing app.d.ts from the project seemed to help in a specific case.

**Comment by mhegazy** [comment]
both app.ts and app.d.ts define the same objects. so you will get the duplicate identifier errors. you only need one of them, and not both. your .ts expresses API shape and implementation, where as your .d.ts expresses your API shape only. so if you are coding against it, you can use either, but not both.

I usually think of .js + .d.ts together as package (e.g. a .net dll) that you use .js portion for execution, and .d.ts portion for typechecking. but both are outputs.

**Comment by DanielRosenwasser** [comment]
@tomitrescak does this resolve your issues?

**Comment by tomitrescak** [comment]
OK. The weird thing here is tha according to Typescript conventions I should always create d.t.s files and reserence them instead of the .ts files. This behaviour of Visual Studio makes this job a bit more difficult.

**Comment by DanielRosenwasser** [comment]
If you have a group of files part of a common project, I don't see any reason you shouldn't just reference the `.ts` file. The `.d.ts` is more useful to an external consumer.

If you're familiar with C/C++, think of a `.d.ts` as a header file that describes the interface to a linked library, which is the `.js` file here.

**Comment by tomitrescak** [comment]
Thanks for your help.
