### ISSUE TITLE
HTMLElement.nonce should be optional

### ISSUE THREAD

**Issue by evmar** [Microsoft/TypeScript#28452]
**TypeScript Version:**  3.2.0-dev.20181107

**Search Terms:** nonce

**Code**

lib.dom.d.ts has:

```ts
interface HTMLOrSVGElement {
    // [...]
    nonce: string;
}
```

**Expected behavior:**
`nonce` is considered experimental and only available in some browsers: https://devdocs.io/dom/htmlelement/nonce .  It should be marked as `nonce?`.

**Actual behavior:**
`nonce` claims to be an always-present string.

**Comment by saschanaz** [comment]
I think this can and should be in lib.d.ts as 1) [it's in the spec](https://html.spec.whatwg.org/multipage/urls-and-fetching.html#attr-nonce) 2) it has at least one implementation.

**Comment by evmar** [comment]
I guess that leads me to a larger question about how experimental APIs are supposed to be supported.  Is there a TS policy on this written down anywhere?

The issue we have is that a programmer can end up using `elem.nonce` without being aware that it's experimental, and TypeScript will helpfully both autocomplete it and say that it's always present.  (It's funny that this showed up at the same time TS made `document.head` nullable, given that that one is almost always present -- we ended up sprinkling `document.head!` annotations everywhere.)

Worse, because this is in lib.d.ts, we can't make our own `|undefined` declaration of `nonce`, because that conflicts with the builtin one.  (We have the same issue with the browser fullscreen APIs for example.)

For some newer browser APIs in TS you have to add the specific libs to your tsconfig, so that you don't use stuff like `Array#flat` accidentally.

**Comment by saschanaz** [comment]
I do wonder whether any other vendors intend to implement `nonce` since even Firefox Nightly does not support it. If they don't, then it should be removed from the spec based on WHATWG policy and that would also remove the field from lib.d.ts.

**Comment by deiga** [comment]
The PR has now been merged and this issue can most likely be closed :)
