### ISSUE TITLE
JSDoc type import parsing broken in JSDoc typedefs

### ISSUE THREAD

**Issue by ahocevar** [Microsoft/TypeScript#28468]
**TypeScript Version:**  3.2.0-dev.20181024

**Search Terms:** jsdoc import parsing

**Code**

```js
/**
 * @typedef {Object} options
 * @property {import("./module").MyClass} option
 */
```

**Expected behavior:**

The module `./module` can be resolved and type `MyClass` is recognized. This used to work before commit ff6f94791feeb9c2b22ff1ada41c173a61f347fb.

**Actual behavior:**

Since commit ff6f94791feeb9c2b22ff1ada41c173a61f347fb, this generates the following error message:
```
error TS2307: Cannot find module './module.js'.
```

**Comment by ajafff** [comment]
I cannot reproduce this on master. Can you test with `typescript@next`?

**Comment by ahocevar** [comment]
I still run into the issue with `typescript@next` and `master`. I'll see if I can provide a failing test case.  It *might* only affect defualt imports (`{import("./module").default}`) and/or imports of another typedef (`{import("./mymodule").options}`).

**Comment by ahocevar** [comment]
Actually this is not fixed yet. I'm going to create a test case that shows the issue.
