### ISSUE TITLE
We have moved to generate the lib.d.ts from the webidl spec instead of from the Edge webidl spec. the result of that is many vendor speciifc declarations are removed and only declarations part of the spec are left behind. TS 3.0 will bring some of these changes, and TS 3.1 will bring the rest. this includes things like:

### ISSUE THREAD

**Issue by richard457** [microsoft/TypeScript#28466]
* `WebKitEntriesCallback`
* `WebKitErrorCallback`
* `WebKitFileCallback`
* `WebKitDirectoryEntry`
* `WebKitDirectoryReader`
* `WebKitEntry`
* `WebKitFileEntry`
* `WebKitFileSystem`
* `MSAccountInfo`
* `MSAudioLocalClientEvent`
* `MSAudioRecvPayload`
* `MSAudioRecvSignal`
* `MSAudioSendPayload`
* `MSAudioSendSignal`
* `MSConnectivity`
* `MSCredentialFilter`
* `MSCredentialParameters`
* `MSCredentialSpec`
* `MSDCCEventInit`
* `MSDSHEventInit`
* `CanvasRenderingContext2D.mozImageSmoothingEnabled`
* `CanvasRenderingContext2D.oImageSmoothingEnabled`
* `CanvasRenderingContext2D.webkitImageSmoothingEnabled`
* `CanvasRenderingContext2D.msFillRule`
* etc..

The recommendation for the vendor specific properties is to define in them locally in a .d.ts file.

_Originally posted by @mhegazy in https://github.com/Microsoft/TypeScript/issues/25515#issuecomment-403897228_

**Comment by richard457** [comment]
Can you provide a clear way to migrate
?

**Comment by weswigham** [comment]
@DanielRosenwasser did we ever put up a guide for this?

**Comment by richard457** [comment]
@weswigham I did dig dipper around the we I could not find a clear way, my usercase is I am using angular 7.1 and it use latest typescript where those web spec can not be found.

**Comment by DanielRosenwasser** [comment]
It's cumbersome, but why is creating a `webkit.lib.d.ts` file, redefining the missing types, and adding them to your project not currently working?
