### ISSUE TITLE
Feature: embedded TypeScript syntax (a'la EJS)

### ISSUE THREAD

**Issue by mindplay-dk** [Microsoft/TypeScript#2846]
There are plenty of template engines for JS - but to my knowledge, there is currently no template engine that provides any meaningful level of IDE support, e.g. for view-models written in TypeScript. In fact, most template engines don't provide auto-completion or any kind of checking for view-models at all - so when it comes to editing views, you're really no better off with view-models than you are with plain view-dictionary hashes.

In other words, the only viable option for IDE support, for views, at this time, is to use a DSL and stay in TypeScript, which comes with it's own set of drawbacks.

Please consider adding an alternative file-extension (e.g. `.ets`) for TypeScript embedded in text (or markup) a'la [EJS](http://www.embeddedjs.com/), ERB (Ruby), Go templates, PHP, etc. - most every web-language has one.

Basic example:

```
${{ declare var view: ArticleView }}
<!DOCTYPE html>
<html>
<head>
    <title>${view.title}</title>
</head>
<body>
    <article>
        <h1>${view.headline}</h1>
        ${view.body}
    </article>
</body>
</html>
```

So basically, `${expr}` emits the result of a TypeScript expression, and `${{ code }}` escapes to inline TypeScript code without emitting the result, with syntax that resembles that of string templates. In a sense, it's just string templates without the ceremony, e.g. with an intermediary interpretation along the lines of:

```
function _tpl(_fn) {
    return _fn`<!DOCTYPE html>
<html>
<head>
    <title>${this.view.title}</title>
</head>
<body>
    <article>
        <h1>${this.view.headline}</h1>
        ${this.view.body}
    </article>
</body>
</html>`;
}
export = _tpl;
```

That's by no means intended to be correct or complete - the main point is that:

    1. the resulting function is a top-level export.
    2. the template function being used is supplied by the caller.
    3. the calling context is supplied by the caller.
    4. variable references are expanded relative to the calling context.

Any thoughts? (we are evaluating a switch from PHP to Node+TypeScript, and the biggest roadblock right now is the lacking design-time support for views - we're a large team that do a lot of template work, so this is critical.)

**Comment by RyanCavanaugh** [comment]
This looks really neat, but completely out of scope for the TypeScript team to do.

**Comment by NoelAbrahams** [comment]
Although I'm not particularly fond of the actual details of the proposal, I suggest that now that JSX is in scope then so should this.

**Comment by RyanCavanaugh** [comment]
Given infinite resources, sure. In a world where JSX exists and a TypeScript HTML templating system doesn't, no.

The other difference is that if we don't have JSX parsing support, no one can use JSX with TypeScript. If the TypeScript team doesn't implement a templating system, anyone else is still able to do so.

**Comment by mindplay-dk** [comment]
> if we don't have JSX parsing support, no one can use JSX with TypeScript. If the TypeScript team doesn't implement a templating system, anyone else is still able to do so

How so? I don't see the difference, really - somebody else could implement JSX support, it's actually more or less the same problem: "TS with JSX" is a superset of TS, and "embedded TS" is a different superset. Somebody could implement a templating system (or JSX support, or anything else) as a pre-processor, with no IDE support - but that misses the core value proposal, which is great tooling with static checking, symbol-based navigation, statement completion, automated refactoring, etc. - isn't that why you're doing JSX support?

JSX may solve the templating problem for HTML/XML, but only for that. Unless you'd accept a PR for TypeScript, it's virtual impossible for somebody to implement a TS template engine that fully integrates with the language service, providing support in all different editors, etc.

Almost every other mainstream/web language (PHP, Ruby, ASP) has some form of template syntax. Looking at e.g. the ImageBoard sample, everything is neat and safe, right up until you have to render a view template - up until that point, we have things like static checking, symbol-based navigation, statement completion, and code refactoring, but not in the view. Views are not a strange and exotic requirement in the web world, that's why most every web-language has some form of templating.

I mean, sure, there are plenty of template engines available for JS - and I don't by any means expect anything like a template engine, e.g. no "engine" features or concepts like caching, escaping, partials, etc. - just a "string builder" syntax, basically. Engine features can (should) be userland functions. I don't see how we can clamp a PHP/ASP-like syntax variant on top of TS, in practice, without working directly from within the language service core...?

**Comment by NoelAbrahams** [comment]
@RyanCavanaugh,

The problem that JSX is solving is that of dynamically generated views. @mindplay-dk's proposal covers the particular case where the view is generated dynamically, but on the *server-side*. There are frameworks other than JSX that generate the view dynamically on the *user-agent* (e.g. Angular JS).

All these cases involve JavaScript embedded in the HTML views. JSX is peculiar in the sense the HTML is embedded in the JavaScript, while the other frameworks have separation of the view and model.

In framework-neutral terms, the service that is required of TypeScript is to ensure the JavaScript that is embedded in the views is also subject to compilation.

**Comment by RyanCavanaugh** [comment]
The difference is between embedding the TypeScript language in some other DSL, which is clearly tractable for an external tool (the TypeScript parser exposes an API), versus the problem of embedding some other DSL inside TypeScript, which requires directly modifying the TypeScript parser.

I'm not trying to argue against the value of this existing *in isolation*; I'm saying that this is outside the scope of things that our team has the resources to take on. Given the choice of us implementing this, which could be taken on by a third party, or doing any of the other 300 suggestions currently opened, it makes much more sense for us to implement one of those other 300 things.

This applies doubly when we'd essentially be competing with every other HTML templating framework on the planet - we have no special expertise in this area, and would have to do a ton of work just to get to parity with any one of those frameworks.

**Comment by mindplay-dk** [comment]
> This applies doubly when we'd essentially be competing with every other HTML templating framework on the planet - we have no special expertise in this area, and would have to do a ton of work just to get to parity with any one of those frameworks.

As said though, I don't expect (or want) a framework.

Neither PHP, ASP, Go or Ruby embedded syntax relies on any framework either - e.g. do not introduce any concepts or functions or "engine" features, essentially just syntax to enable embedded statements and expressions in a text-file.

> it makes much more sense for us to implement one of those other 300 things which do require more extensive knowledge of the TypeScript language and how to modify i

I get that, but I do think this feature would have more value if (like other web languages) it was not a pre-processor but an alternative syntax, and not a separate extension, but a standard language feature. Do you disagree with that? If not, I do understand that you have other priorities, but perhaps you would consider a PR?

**Comment by danquirk** [comment]
I'm not super familiar with the technical implementations of these other tools you're referring to but it's really unclear why the TypeScript compiler would need or want to implement this.

Like, for the example snippet you gave surely the correct design for such a system is to take an HTML parser and create a pluggable template system where upon running the HTML parser you specify the embedded language that is expected to be seen inside templates (or automatically figure it out somehow). Then every language is not (re)implementing HTML parsing or code for skipping unknown XML literals. It's not clear to me how you imagine a TypeScript PR looking here. The TypeScript compiler is going to take a dependency on an HTML parser or include HTML parsing code within it now?

**Comment by NoelAbrahams** [comment]
> The TypeScript compiler is going to take a dependency on an HTML parser or include HTML parsing code within it now

Isn't that what will have to be done if JSX is going to be supported?

**Comment by lulzmachine** [comment]
+1 on this. Views are the only glaring hole when it comes to typing in node. To be fair, many other environments haven't solved typing in templates either (spring/RoR/php etc). But it would be very much appreciated.
