### ISSUE TITLE
Excess property checking for instances or other object types

### ISSUE THREAD

**Issue by Hoishin** [Microsoft/TypeScript#28464]
## Search Terms

- `object literal class instance`
- `treat object literal as class instance`

## Suggestion

According to [this part of documentation](https://www.typescriptlang.org/docs/handbook/interfaces.html#excess-property-checks), object literal is type-checked more strictly than other objects for excess properties. It would be nice to have feature to check excess properties for other "non-literal" objects such as class instances.

## Use Cases

Let's say we have data fetched from database. It would include `createdAt`, `updatedAt`, or something like `passwordHash`. Some properties are not the best to get out of server.
When sending the data to client, I defined the payload type to not include those excess properties, but if the data is an form of class instance, the excess properties are allowed.

## Examples
[Playground link](http://www.typescriptlang.org/play/#src=interface%20Person%20%7B%0D%0A%20%20%20%20name%3A%20string%3B%0D%0A%20%20%20%20email%3A%20string%3B%0D%0A%7D%0D%0A%0D%0A%2F%2F%20no%20excess%20properties%0D%0Aconst%20bob%3A%20Person%20%3D%20%7B%0D%0A%20%20%20%20name%3A%20'bob'%2C%0D%0A%20%20%20%20email%3A%20'bob%40example.com'%2C%0D%0A%7D%0D%0A%0D%0A%2F%2F%20excess%20properties%20in%20object%20literal%20is%20error%0D%0Aconst%20john%3A%20Person%20%3D%20%7B%0D%0A%20%20%20%20name%3A%20'john'%2C%0D%0A%20%20%20%20email%3A%20'john%40example.com'%2C%0D%0A%20%20%20%20age%3A%2030%0D%0A%7D%0D%0A%0D%0A%2F%2F%20let's%20define%20a%20class%20that%20makes%20same%20interface%20as%20Person%0D%0Aclass%20Student%20%7B%0D%0A%20%20%20%20constructor(public%20name%3A%20string%2C%20public%20email%3A%20string%2C%20public%20age%3A%20number)%20%7B%7D%0D%0A%7D%0D%0A%0D%0A%2F%2F%20excess%20properties%20in%20class%20instance%20are%20not%20error%0D%0Aconst%20alex%3A%20Person%20%3D%20new%20Student('alex'%2C%20'alex%40example.ac.jp'%2C%2020))

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
  * If this feature is introduced as additional feature
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by DanielRosenwasser** [comment]
Exact types: #12936
Nominal types: #202

We don't have excess property checking on other object types because excess property checks are mostly meant to catch issues where an object literal is supposed to be used as a "bag of options".

To try to avoid other issues, we also have overlap checking for "weak types", where if there's no overlap between a *Source* type to a *Target* type, and the target type only has optional properties (i.e. it's "weak") then we error if there's no overlap.

But here, it's not even clear why this example should be an error:

```ts
const alex: Person = new Student('alex', 'alex@example.ac.jp', 20)
```

though I agree that this piece just feels inconsistent:

```ts
const john: Person = {
    name: 'john',
    email: 'john@example.com',
    age: 30
}
```

**Comment by Hoishin** [comment]
@ajafff @DanielRosenwasser 

I have seen Exact types, but I wasn't sure if that was something I was looking for, but after looking back, it seems that they should result in what I want to see.

What would be the best way to do either
- check excess property of non-object literal
- force a value to be object literal
?
