### ISSUE TITLE
Intellisense missing for generic type extending an all partial type

### ISSUE THREAD

**Issue by AviVahl** [microsoft/TypeScript#28470]
**TypeScript Version:**
3.1.3 and 3.2.0-dev.20181110

**Search Terms:**
Intellisense suggestions generic type

**Code**

```ts
interface Options {
    someFunction?: () => string
    anotherFunction?: () => string
}

export class Clazz<T extends Options> {
    constructor(public a: T) {
    }
}

new Clazz({

// ctrl + space on above line does not provide any suggestion
// it does when:
// - making some/anotherFunction required instead of optional (in Options)
//   OR
// - giving constructor's first param a type of `T | Options`
})
```

**Expected behavior:**
suggest `someFunction` and `anotherFunction`.

**Actual behavior:**
no suggestions

**Playground Link:** 
http://www.typescriptlang.org/play/#src=interface%20Options%20%7B%0D%0A%20%20%20%20someFunction%3F%3A%20()%20%3D%3E%20string%0D%0A%20%20%20%20anotherFunction%3F%3A%20()%20%3D%3E%20string%0D%0A%7D%0D%0A%0D%0Aexport%20class%20Clazz%3CT%20extends%20Options%3E%20%7B%0D%0A%20%20%20%20constructor(public%20a%3A%20T)%20%7B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Anew%20Clazz(%7B%0D%0A%0D%0A%2F%2F%20ctrl%20%2B%20space%20in%20line%2012%20does%20not%20provide%20any%20suggestion%0D%0A%2F%2F%20it%20does%20when%3A%0D%0A%2F%2F%20-%20making%20some%2FanotherFunction%20required%20instead%20of%20optional%20(in%20Options)%0D%0A%2F%2F%20%20%20OR%0D%0A%2F%2F%20-%20giving%20constructor's%20first%20param%20a%20type%20of%20%60T%20%7C%20Options%60%0D%0A%7D)%0D%0A

**Related Issues:**

**Comment by parzh** [comment]
Looks like I also encountered this issue, so +1. Hope, this playground is useful: https://goo.gl/17cGA8

```ts
type Direction = "up" | "down" | "left" | "right";

type MovementDescriptor<Dir extends Direction> = {
    [D in Dir]: true;
};

// NB: The error here is that the `MovementDescriptor` type
// does not suggest type parameter autocompletion on Ctrl + Space
// (to test that, change type parameter to "" and press Ctrl + Space with cursor inside the parens),
// while all the compile errors occur just fine as expected
// (to test that, try making an typo, e.g. changing "left" to "let").
interface MovementUp extends MovementDescriptor<"up" | "left"> { }

const up: MovementUp = {
    down: true, // compile error is expected
}; 
```

**Comment by cspotcode** [comment]
I'm hitting this as well.  Here is our use-case:

Our codebase builds large JSON API responses from multiple partial objects that we splat together.  I'd like to have Intellisense for property names; we use verbose and inconsistent property names.  But I'd also like some validation that, when the partial objects are splatted together, the result includes all properties.  We don't want to accidentally omit anything.

So I need some way to:
a) get tab-completion for property names
b) let us omit properties when creating these partial objects
c) infer which properties have been specified so we can prove that the merged object contains all necessary properties

Naively, I tried inferring the type of each partial object via `function partialApiResponse<T extends Partial<ApiReponseJson>(t: T) {return t}`  But Intellisense doesn't offer any suggestions.

**Comment by cspotcode** [comment]
I noticed another behavior that suggests this is an unintended bug rather than an intentional limitation.

[playground link](http://www.typescriptlang.org/play/index.html#src=interface%20Foo%20%7B%0D%0A%20%20%20%20a_a%3A%20boolean%3B%0D%0A%20%20%20%20a_b%3A%20boolean%3B%0D%0A%20%20%20%20a_c%3A%20boolean%3B%0D%0A%20%20%20%20b_a%3A%20boolean%3B%0D%0A%7D%0D%0Afunction%20partialFoo%3CT%20extends%20Partial%3CFoo%3E%3E(t%3A%20T)%20%7Breturn%20t%7D%0D%0ApartialFoo(%7B%0D%0A%20%20%20%20%2F%2F%20%3C--%20Ctrl-Space%20shows%20empty%20completion%20list.%20%20Typing%20additional%20letters%20continues%20to%20show%20empty%20list.%0D%0A%20%20%20%20%2F%2F%20*BUT*%20if%20you%20type%20the%20letter%20%22a%22%20*first*%2C%20you%20see%20a%20completion%20list%2C%20which%20then%20narrows%20as%20you%20type.%0D%0A%7D)%3B)
```typescript
interface Foo {
    a_a: boolean;
    a_b: boolean;
    a_c: boolean;
    b_a: boolean;
}
function partialFoo<T extends Partial<Foo>>(t: T) {return t}
partialFoo({
    // <-- Ctrl-Space shows empty completion list.  Typing additional letters continues to show empty list.
    // *BUT* if you type the letter "a" *first*, you see a completion list, which then narrows as you type.
});
```

**Comment by HaloWang** [comment]
Come from #29180 with VSCode version 1.31.1. This problem still exist.😫

**Comment by HaloWang** [comment]
[#306](https://github.com/Microsoft/vscode-react-native/issues/306#issuecomment-467780654)

**Comment by maxfontana90** [comment]
I found a similar issue with a [generic interface](https://www.typescriptlang.org/play/index.html#src=export%20interface%20GenericObject%20%7B%0D%0A%20%20%5Bprop%3A%20string%5D%3A%20any%3B%0D%0A%7D%0D%0A%0D%0Aconst%20someImmutableGenericObject%3A%20Readonly%3CGenericObject%3E%20%3D%20%7B%0D%0A%20%20PropA%3A%20'foo'%2C%0D%0A%20%20PropB%3A%20'bar'%2C%0D%0A%20%20PropC%3A%20'baz'%2C%0D%0A%7D%3B%0D%0A%0D%0A%0D%0Aconsole.log(%0D%0A%20%20someImmutableGenericObject.PropB%20%2F%2F%20ctrl%20%2B%20space%20in%20this%20does%20not%20provide%20any%20suggestion%0D%0A)%3B%0D%0A%0D%0A). It doesn't infer prop names even if its explicitly declared.

**Comment by parzh** [comment]
@maxfontana90 In your case it is fine, since by stating that `someImmutableGenericObject` is a `GenericObject` you remove all the information about its properties, that might have otherwise be inferred. Try removing `: Readonly<GenericObject>`, this might bring IntelliSense back.

Also, technically this object is neither immutable (you mutate its state), nor a Generic. See the meaning of the latter term [here](https://www.typescriptlang.org/docs/handbook/generics.html).

**Comment by KillyMXI** [comment]
I think I have an issue related to this.

```typescript
interface IBase {
  /** Base property */
  readonly a: number
}

interface ISpecialX extends IBase {
  /** Property X */
  readonly x: number
}

interface ISpecialY extends IBase {
  /** Property Y */
  readonly y: number
}

type SomethingSpecial = ISpecialX | ISpecialY;

export function doSomething(input: SomethingSpecial): void {}
```
And then:
```typescript
import { doSomething } from '...';

doSomething({ a: 1, x: 2 });
```
Here, TypeScript language server can report a wrongly formed object passed as an argument (omit property `a` - get a type mismatch report).
But IntelliSense tooltip only shows documentation for properties from special interfaces, namely property `x` in this case. For the property `a` it shows only information inferred from usage.
