### ISSUE TITLE
Wiki page 'JavaScript Language Service in Visual Studio' has broken link

### ISSUE THREAD

**Issue by gamtiq** [microsoft/TypeScript#28484]
Inside wiki page [JavaScript Language Service in Visual Studio](https://github.com/Microsoft/TypeScript/wiki/JavaScript-Language-Service-in-Visual-Studio#-intellisense-based-on-typescript-declaration-files) there is the following fragment:
> For example, JavaScript IntelliSense can be provided for values declared in a .d.ts file (more info)

Where `more info` is a broken link pointing to https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Writing%20Definition%20Files.md

**Comment by DanielRosenwasser** [comment]
PRs accepted at https://github.com/Microsoft/TypeScript-wiki

**Comment by aleph-naught2tog** [comment]
@DanielRosenwasser Addressed in https://github.com/Microsoft/TypeScript-wiki/pull/192

**Comment by orta** [comment]
This was addressed
