### ISSUE TITLE
MouseWheelEvent.wheelDelta is not defined

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#28495]
**TypeScript Version:**  3.2.0-dev.20181110

**Search Terms:**
- dom.d.ts
- mousewheelevent

**Problem**

https://github.com/Microsoft/TSJS-lib-generator/pull/579 removes the definition for `MouseWheelEvent,wheelDelta`

Although this property is deprecated non-standard (https://developer.mozilla.org/en-US/docs/Web/API/MouseWheelEvent) it was being used in the VS Code code base and potentially elsewhere.

I'll see if VS Code can migrate to use the standard `WheelEvent` but am not sure if the current breaking change on `MouseWheelEvent` is correct.

**Comment by DanielRosenwasser** [comment]
@sandersn let's discuss tomorrow.

**Comment by DanielRosenwasser** [comment]
I think the break is intentional and the workaround should be fairly straightforward for most users.
