### ISSUE TITLE
Property assignment declarations on TS functions ignore declared type

### ISSUE THREAD

**Issue by whitneyit** [microsoft/TypeScript#28492]
**TypeScript Version:**  3.2.0-dev.20181110

**Search Terms:**
* Properties declarations on functions
* Function properties

**Code**

```ts
interface ExampleNum {
    (): boolean
    num: 123;
}

interface ExampleStr {
    (): boolean
    str: "ABC";
}

const exampleNum: ExampleNum = () => true;
exampleNum.num = 123;

const exampleStr: ExampleStr = () => true;
exampleStr.str = "ABC";
```

**Expected behavior:**
`exampleNum.num` to have type of `123`
`exampleStr.str` to have type of `"ABC"`
The function to remain as `(): boolean` instead of being coerced into `(): true`

**Actual behavior:**
> Type '{ (): true; num: number; }' is not assignable to type 'ExampleNum'.
>   Types of property 'num' are incompatible.
>     Type 'number' is not assignable to type '123'.

> Type '{ (): true; str: string; }' is not assignable to type 'ExampleStr'.
>   Types of property 'str' are incompatible.
>     Type 'string' is not assignable to type '"ABC"'.

**Playground Link:** 
http://www.typescriptlang.org/play/#src=interface%20ExampleNum%20%7B%0A%20%20%20%20()%3A%20boolean%0A%20%20%20%20num%3A%20123%3B%0A%7D%0A%0Ainterface%20ExampleStr%20%7B%0A%20%20%20%20()%3A%20boolean%0A%20%20%20%20str%3A%20%22ABC%22%3B%0A%7D%0A%0Aconst%20exampleNum%3A%20ExampleNum%20%3D%20()%20%3D%3E%20true%3B%0AexampleNum.num%20%3D%20123%3B%0A%0Aconst%20exampleStr%3A%20ExampleStr%20%3D%20()%20%3D%3E%20true%3B%0AexampleStr.str%20%3D%20%22ABC%22%3B

**Related Issues:** 
No related issues found relating to losing type safety

**Comment by DanielRosenwasser** [comment]
I'm confused by what you mean when you say "lose type safety". Do you mean that TypeScript reports a type error?

**Comment by whitneyit** [comment]
@DanielRosenwasser, when I say _lost type safety_, the type `123` and `"ABC"` is widened to the more general `number` and `string` types.

As you can see in the actual behavior, `'{ (): true; num: number; }'` doesn't match the `ExampleNum` interface: `'{ (): boolean; num: 123; }'`.

This also applies to `'{ (): true; str: string; }'` which doesn't match the `ExampleStr` interface: `'{ (): boolean; str: "ABC"; }'`

**Comment by sandersn** [comment]
Probably assignment declarations should contextually type their initialisers by the appropriate property type.

**Comment by RyanCavanaugh** [comment]
> Probably assignment declarations should contextually type their initialisers by the appropriate property type.

Kind of confused, because assignment expressions already contextually type their RHS values, so unless the assignment decl is doing something weird this should happen for free.

**Comment by sandersn** [comment]
"weird"

```
> open checker
You open the checker slowly. It is pitch black inside.

> light torch
Inside you see getWidenedTypeFromAssignmentDeclaration. An odd smell fills the air.

> git log getWidenedTypeFromAssignmentDeclaration
Shrieking strings and a muffled roar. Everything returns to darkness.



Your score: NaN
```

**Comment by sandersn** [comment]
Repros inline in both JS and TS:

```ts
export const f: { (): boolean; nun: 456 } = () => true;
f.nun = 456;
```

```js
/** @type {{ (): boolean; nuo: 789 }} */
export const g = () => true
g.nuo = 789
```

**Comment by sandersn** [comment]
getWidenedTypeFromAssignmentDeclaration wasn't checking the containing type for a property of the assigned name, and was also ignoring Typescript annotations. #32553 fixes both problems.
