### ISSUE TITLE
Allow type system to represent `this` in function inputs/outputs

### ISSUE THREAD

**Issue by fsoikin** [Microsoft/TypeScript#285]
The early discussions about generics had this feature outlined, but it never made it into the final version for some reason. Meanwhile, it would be extremely helpful in some cases. The use case that it most dear to my heart is Knockout:

```
interface Observable<T> {
   <U>( this: U, value: T ): U;
}

var viewModel = {
   Str: ko.observable( "abc" ),
   Num: ko.observable( 5 )
};

viewModel.Str( "xyz" ).Num( 10 );
```

**Comment by nathggns** [comment]
Defining the type of `this` within a function body is covered by #1985

**Comment by emanuelpalm** [comment]
@DanielRosenwasser Only allowing `this` for return types is still very useful. I'd say it's entirely justifiable as long as the compiler outputs a decent error message when trying to use it elsewhere.

I would propose the keyword to be `This`, with capital T, just to differentiate it from the property `this`.

Any news on when this feature might land in a stable release?

**Comment by bluong** [comment]
Would very much like an update into this issue

**Comment by DanielRosenwasser** [comment]
Hey @bluong, I think we're still interested in it, but ES6 work has dominated much of our time. We're still also lacking a solid proposal.

**Comment by pmccloghrylaing** [comment]
I'd love to see `this` as a return type for chaining methods implemented - it would *greatly* improve the node.js type definitions, which currently don't support things like:

    readStream.on('error', ...).pipe(writeStream);

The biggest issue for `this` as a return type is inheritance - chaining methods need to be differentiated from `clone`-like. My suggestion would be to implement `this` as a return for chaining methods first, e.g.

    class Chainer {
        doSomething(...) : this {
            // do something
            return this;
        }
    }

Classes with chaining methods can be safely inherited from while maintaining `this` as the return type. So any methods specifying `this` as a return type need to `return this` and nothing else.

I'm not so sure the return type is as useful for `clone`-like methods. It seems to me the only advantage would be if it forced derived classes to override the method - and then all that gives you is an error over what you can do currently. If there's a good reason for it maybe a generic `this<T>` would work to show that the particular implementation returns `T`.

    class Cloner {
        clone() : this<Cloner> {
            return new Cloner();
        }
    }
    class DerivedCloner extends Cloner {
        clone() : this<DerivedCloner> {
            return new DerivedCloner();
        }
    }

**Comment by hypery2k** [comment]
any news on this issue?

**Comment by danquirk** [comment]
@hypery2k the most recent proposal is https://github.com/Microsoft/TypeScript/issues/3694. We have a few different issues tracking the various ways people want to specify `this` types. Suffice to say we know it's a top request but it's also complicated to support correctly :)

**Comment by DmitryEfimenko** [comment]
+1

**Comment by mhegazy** [comment]
this is now tracked by #3694
