### ISSUE TITLE
Scoped typings packages behind a private feed

### ISSUE THREAD

**Issue by clegendre** [Microsoft/TypeScript#28506]
**TypeScript Version:**  3.1.0

**Search Terms:** Private Scope Typings

**Code**

The package.json of a private package named **bar** of the **foo** scope, which depends of private typings 
```js
{
   "name": "@foo/bar",
   "dependencies": {
     "@types/foo__bar": "latest"
   }
}
```

The package.json of a final application which consume private package of **foo** organization.
```js
{
   "name": "my_private_application",
   "dependencies": {
     "@foo/bar": "latest"
   }
}
```
.npmrc file which consume private packages of the scope **foo**
```
@foo:registry=http://my-private-feed.com/
@foo:always-auth=true
```
**Expected behavior:**
The package **@types/foo__bar** is resolved from the private feed defined for the scope @foo

**Actual behavior:**
The package **@types/foo__bar** is resolved from npm.org and is not found.

**Related Issues:** 
This issue describes the problem : https://github.com/DefinitelyTyped/DefinitelyTyped/issues/11658#issuecomment-438308692
#14819

**Comment by MartinJohns** [comment]
Isn't this more of a NPM issue than a TypeScript issue?

**Comment by clegendre** [comment]
This is a good question, and I think that the real problem behind this issue is the design of Typescript about typings: To use the scope **types** to resolve typings...

**Comment by andy-ms** [comment]
If `@foo/bar` is a package that you control, you could always [bundle](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) types with it instead of having a separate `@types` package.

**Comment by clegendre** [comment]
You’re right, providing typings directly in the package will solve this issue.
Thank you for your time.
