### ISSUE TITLE
Abstract methods should not allow `async` modifier

### ISSUE THREAD

**Issue by aleph-naught2tog** [microsoft/TypeScript#28516]
This had already been discussed [here](https://github.com/Microsoft/TypeScript/issues/25710) which was a different issue that was concluded to be intended behaviour, but that abstract methods allowing `async` was *not* intended. 

**TypeScript Version:**  Version 3.2.0-dev.20181113

**Search Terms:**
abstract async, async

**Code**

```ts
// assuming `--lib es2015` is passed to the compiler
abstract class ShouldFailClass {
  async abstract someMethod(): Promise<number>; // This should error, but doesn't
}
```

**Expected behavior:**
Abstract methods should not allow an `async` modifier in the same way an interface and other type parameters don't allow them.

**Actual behavior:**
Abstract methods do not error with an `async` modifier attached; interface methods do.

**Playground Link:**  Both of these should error, not just the second on, as discussed in the earlier linked issue. [Reproduced here](http://www.typescriptlang.org/play/#src=abstract%20class%20BadClass%20%7B%0D%0A%20%20async%20abstract%20badMethod()%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20BadInterface%20%7B%0D%0A%20%20async%20badInterfaceMethod()%3B%0D%0A%7D)

**Related Issues:** 
Originally discussed in the comments in [here](https://github.com/Microsoft/TypeScript/issues/25710), where the consensus was that the behavior was intended for that case, but that `async abstract` should _not_ be allowed.

**Comment by rbuckton** [comment]
@DanielRosenwasser should we also disallow `async` on overloads?

```ts
class C {
  async foo(); // <- should this be disallowed?
  async foo() {
  }
}
```

**Comment by DanielRosenwasser** [comment]
Mmm, I don't know; seems like that's okay since the following is allowed.

```ts
async function foo(): Promise<number>
async function foo() {
  return Promise.resolve(10);
}
```

Thoughts @RyanCavanaugh?

**Comment by Kovensky** [comment]
@DanielRosenwasser your example of allowed code is just how the `PromiseResolve` algorithm works. `PromiseResolve` of a `Promise` will just inherit that promise's state. `async () => Promise.resolve(10)` returns a `Promise` that is not `===` the `Promise.resolve(10)` you just created, but that will have the same state.

**Comment by Kovensky** [comment]
Personally, requiring the `Promise<...>` around the return type of `async` functions is unnecessary syntactic noise. As I mentioned, it is _impossible_ to not return a `Promise` from an `async` function -- TS could just do the clever thing and present the return value as `Promise<ReturnType<the called overload>>`.

But that ship sailed long before I even started learning JavaScript 😓

**Comment by rbuckton** [comment]
@Kovensky: That isn't the issue at question here. The issue is whether to disallow `async` on ambient methods (abstract/overload/etc.).

**Comment by Kovensky** [comment]
It seems related to me because of the contract I just mentioned. An `async` function is guaranteed to never `throw`, only reject its `Promise`, while a non-`async` function that happens to return a `Promise` could `throw`.

**Comment by trotyl** [comment]
> An `async` function is guaranteed to never throw, only reject its `Promise`, while a non-async function that happens to return a Promise could throw.

@Jessidhia Your argument is actually why `async` should be forbid from `abstract` method, because the implementation of an `async` method doesn't need to be `async`, making it wrong assumption of non-throwable:

```typescript
abstract class Base {
    abstract async foo(): Promise<number>
}

class Derived {
    foo(): Promise<number> {
        throw new Error()
    }
}

const base: Base = new Derived()
base.foo() // Throwable
```
