### ISSUE TITLE
Exhaustiveness check does not work with unions and if/else-if

### ISSUE THREAD

**Issue by AlCalzone** [microsoft/TypeScript#28520]
**TypeScript Version:**  3.2.0-dev.20181114

**Search Terms:** union exhaustiveness

**Code**

```ts
declare class Foo { foo: this; }
declare class Bar { bar: this; }

function test1(v1: Foo | Bar) {
  let x: string;
  if (v1 instanceof Foo) {
    x = "Foo";
  } else if (v1 instanceof Bar) {
    x = "Bar";
  }
  x.toLocaleLowerCase();
  // x is used before being assigned
}
```

**Expected behavior:**
No error, since there is clearly an if branch per union member.

**Actual behavior:**
`x` is used before being assigned. This works however:

```ts
declare class Foo { foo: this; }
declare class Bar { bar: this; }

function test2(v1: Foo | Bar) {
  let x: string;
  if (v1 instanceof Foo) {
    x = "Foo";
  } else /* if (v1 instanceof Bar) */ {
    x = "Bar";
  }
  x.toLocaleLowerCase();
  // ok
}
```

**Playground Link:** https://www.typescriptlang.org/play/#src=declare%20class%20Foo%20%7B%20foo%3A%20this%3B%20%7D%0D%0Adeclare%20class%20Bar%20%7B%20bar%3A%20this%3B%20%7D%0D%0A%0D%0Afunction%20test1(v1%3A%20Foo%20%7C%20Bar)%20%7B%0D%0A%20%20let%20x%3A%20string%3B%0D%0A%20%20if%20(v1%20instanceof%20Foo)%20%7B%0D%0A%20%20%20%20x%20%3D%20%22Foo%22%3B%0D%0A%20%20%7D%20else%20if%20(v1%20instanceof%20Bar)%20%7B%0D%0A%20%20%20%20x%20%3D%20%22Bar%22%3B%0D%0A%20%20%7D%0D%0A%20%20x.toLocaleLowerCase()%3B%0D%0A%20%20%2F%2F%20x%20is%20used%20before%20being%20assigned%0D%0A%7D%0D%0A%0D%0Afunction%20test2(v1%3A%20Foo%20%7C%20Bar)%20%7B%0D%0A%20%20let%20x%3A%20string%3B%0D%0A%20%20if%20(v1%20instanceof%20Foo)%20%7B%0D%0A%20%20%20%20x%20%3D%20%22Foo%22%3B%0D%0A%20%20%7D%20else%20%2F*%20if%20(v1%20instanceof%20Bar)%20*%2F%20%7B%0D%0A%20%20%20%20x%20%3D%20%22Bar%22%3B%0D%0A%20%20%7D%0D%0A%20%20x.toLocaleLowerCase()%3B%0D%0A%20%20%2F%2F%20ok%0D%0A%7D
Turn on `strictNullChecks`!

**Related Issues:**

**Comment by weswigham** [comment]
Welllllllll, you could call `test2` like so:
```ts

var obj: { foo: typeof obj } = {} as { foo: typeof obj };
obj.foo = obj;
test1(obj); // will error at runtime, `x` in the body is unassigned because `obj` is neither an instanceof `Foo` nor `Bar` (though it is structurally compatible with `Foo`, so the call is allowed)
```

**Comment by AlCalzone** [comment]
@weswigham Hmm I guess I oversimplified the classes. What about this?

```ts
declare class Foo {
  private foo: this;
}
declare class Bar {
  private bar: this;
}

function test1(v1: Foo | Bar) {
  let x: string;
  if (v1 instanceof Foo) {
    x = "Foo";
  } else if (v1 instanceof Bar) {
    x = "Bar";
  }
  x.toLocaleLowerCase();
  // x is used before being assigned
}
```

Here I cannot call `test1` with your workaround.

**Comment by AlCalzone** [comment]
I read up on this issue - am I correct in assuming that this issue can only be solved with
1. nominal types or
2. `return assertNever(v1);` in the `else` branch?
