### ISSUE TITLE
restrict to exact type by type name

### ISSUE THREAD

**Issue by ORESoftware** [Microsoft/TypeScript#28547]
The following will compile

```js

interface Foo {
  success: boolean
}

interface Bar {
  success: boolean
}


const foo = (v: Foo) =>{

};

const bar = (v: Bar) =>{

};


bar(<Foo>{success: true});
bar(<Bar>{success: true});
```

it will compile because of the way that TS works, which is usually very convenient. But in some cases we may want to restrict to the exact type. 

Basically, I am looking to prevent compilation for:

```js
bar(<Foo>{success: true});
```
I want it to be restricted to:

```js
bar(<Bar>{success: true}); 
```

is that possible?

**Comment by AlCalzone** [comment]
What you want is #202
You should have a look at https://michalzalecki.com/nominal-typing-in-typescript/#approach-2-brands

**Comment by weswigham** [comment]
Aye, duplicate of #202.
