### ISSUE TITLE
Suggestion: Control flow analysis

### ISSUE THREAD

**Issue by danquirk** [Microsoft/TypeScript#2854]
This is a work item to track some of the ideas and work associated with implementing simple control flow analysis for error reporting purposes. @vladima has already implemented a version of this concept in https://github.com/Microsoft/TypeScript/pull/1287. It already covers some of the separate issues people have asked for but I'm adding a list of tasks here that can be checked off/added to by whoever ends up officially taking on this work.

- [ ] Use before definition https://github.com/Microsoft/TypeScript/issues/21
- [ ] Switch case fall through https://github.com/Microsoft/TypeScript/issues/854

**Comment by jbondc** [comment]
Can likely be used to improve type guards too, some pseudo-code here:
https://github.com/Microsoft/TypeScript/issues/1892#issuecomment-72645272

Keep track of widened type assignments & when exiting a block, check if all the same & narrow to the same type.

**Comment by mhegazy** [comment]
Switch fall through is fixed by https://github.com/Microsoft/TypeScript/pull/4788

use before definition is tracked by #5207
