### ISSUE TITLE
TypeScript call AMD module

### ISSUE THREAD

**Issue by z3214965** [Microsoft/TypeScript#28543]
i have a library use AMD，i want call this library in typeScript，
i use “const VertexArray = require('src/assets/thirdParty/cesium/Source/Renderer/VertexArray.js')”，
but in AMD module i use “require('https')”，when i compile typeScript，
ERROR：Module not found: Error: Can't resolve 'https'

**Comment by DanielRosenwasser** [comment]
Hey there, this issue tracker isn't meant to work as a support forum. These questions tend to be better suited for StackOverflow. You may want to open a question up there instead. Thanks!

**Comment by z3214965** [comment]
@DanielRosenwasser 
in StackOverflow，I didn't find a solution，Can you help me out? Thank you
