### ISSUE TITLE
namespaces with the same name compile without problem?

### ISSUE THREAD

**Issue by ORESoftware** [Microsoft/TypeScript#28555]
I have this file:

```typescript
export namespace Entities {
  
  export namespace Foo {
  
  }
  
  export namespace Foo {
  
  }
  
  
}
```

it compiles without error to:

```typescript
export declare namespace Entities {
    namespace Foo {
    }
    namespace Foo {
    }
}
```

I would assume there would be a class of names? Foo clashing with Foo? I don't get it. I am on tsc `v3.1.6`

**Comment by j-oliveras** [comment]
See:
```ts
export namespace Entities {
  
  export namespace Foo {
    export var a = 0; // var a
  }
  
  export namespace Foo {
    export var b = 0; // var b
  }
}
```

Is converted to (into playground):
```js
define(["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    var Entities;
    (function (Entities) {
        var Foo;
        (function (Foo) {
            Foo.a = 0; // var a
        })(Foo = Entities.Foo || (Entities.Foo = {}));
        (function (Foo) {
            Foo.b = 0; // var b
        })(Foo = Entities.Foo || (Entities.Foo = {}));
    })(Entities = exports.Entities || (exports.Entities = {}));
});
```

[Playground](https://www.typescriptlang.org/play/#src=export%20namespace%20Entities%20%7B%0D%0A%20%20%0D%0A%20%20export%20namespace%20Foo%20%7B%0D%0A%20%20%20%20export%20var%20a%20%3D%200%3B%20%2F%2F%20var%20a%0D%0A%20%20%7D%0D%0A%20%20%0D%0A%20%20export%20namespace%20Foo%20%7B%0D%0A%20%20%20%20export%20var%20b%20%3D%200%3B%20%2F%2F%20var%20b%0D%0A%20%20%7D%0D%0A%7D%0D%0A).

**Comment by weswigham** [comment]
Namespaces with the same name merge and have the same scope - that's what makes them namespaces.

**Comment by ORESoftware** [comment]
@weswigham is there a purpose for that? Seems like it should just throw an error? I am looking for an error to prevent duplicate declarations.

**Comment by weswigham** [comment]
Yeah... The purpose is to be able to split a single namespace across multiple files. Namespaces in other languages typically work in a similar fashion.

Tbh, for most modern TS codebases, we'd advise people develop with modules rather than namespaces, since that's JS standard.

**Comment by ORESoftware** [comment]
got it thank you!
