### ISSUE TITLE
MSBuild fails with "no compiler found"

### ISSUE THREAD

**Issue by PranavSenthilnathan** [Microsoft/TypeScript#28556]
**TypeScript Version:**  3.2.0

**Search Terms:** TypeScriptToolsVersion different version msbuild cordova

**Expected behavior:** MSBuild should succeed without errors for a project using TypeScript.

**Actual behavior:** Build fails with error:
Error		Your project file uses a different version of the TypeScript compiler and tools than is currently installed on this machine.  No compiler was found at .  You may be able to fix this problem by changing the <TypeScriptToolsVersion> element in your project file.

**Comment by minestarks** [comment]
Applies to Dev14/Dev15 with Typescript SDK install only (Nuget packages aren't affected). In this scenario anything above TypeScript 2.3 already gives compilation errors due to the Cordova typings being out of date.
