### ISSUE TITLE
TS 3.2.0-rc seems to forget union type refinements more eagerly

### ISSUE THREAD

**Issue by Kovensky** [Microsoft/TypeScript#28568]
**TypeScript Version:**  3.2.0-rc

**Search Terms:**
refinement

**Code**

(EDIT: incorrect reproduction, see correct example at https://github.com/Microsoft/TypeScript/issues/28568#issuecomment-439758028)
```ts
function test(x: { type: 'a'; body: string | null } | { type: 'b'; body: number | null }): string {
  if (x.body === null) {
    return 'null'
  }
  x.body.toString() // ok

  if (x.type === 'a') {
    return x.body.toString() // x.body may be null
  } else {
    return x.body.toString() // x.body may be null
  }
}
```

**Expected behavior:**
The refinement of `x.body` should persist (it does in 3.1)

**Actual behavior:**
TS forgets that it has already refined `x.body` to be not `null`.

**Comment by mmis1000** [comment]
Maybe it guess x.body.toString() may has side effect and fail the refinements?

**Comment by Kovensky** [comment]
Oh, no, removing that line has no effect. I just added it to demonstrate that the initial refinement is working.

**Comment by ahejlsberg** [comment]
I can't reproduce a difference between 3.1 and 3.2. In `--strictNullChecks` mode the example errors on both, and without `--strictNullChecks` the example passes on both.

As an aside, the error in `--strictNullChecks` mode is due to a known design limitation in the control flow analyzer--upon encountering a discriminant check we narrow based on that check but forget about other narrowings that were already in effect.

**Comment by Kovensky** [comment]
That is odd. This is an error I only encountered in existing code once I updated to TS 3.2, but my snippet indeed also displays the error in 3.1...

**Comment by Kovensky** [comment]
Oh, I found the version that errors in 3.2 but not 3.1:

3.2:
<img width="630" alt="image" src="https://user-images.githubusercontent.com/73085/48683980-f8961b00-ebf2-11e8-8f0e-cd851a3689a9.png">

3.1:
<img width="611" alt="image" src="https://user-images.githubusercontent.com/73085/48684009-0f3c7200-ebf3-11e8-8ec7-bcefbb4c0e7c.png">

```ts
function test(x: { type: 'a'; body: string | null } | { type: 'b'; body: number | null }): string {
  if (x.body === null) {
    return 'null'
  }

  switch (x.type) {
    case 'a':
      return x.body.toString() // x.body may be null
    case 'b':
      return x.body.toString() // x.body may be null
  }
}
```

**Comment by ahejlsberg** [comment]
@Kovensky Yes, that is due to #27612. We weren't correctly resetting our narrowing assumptions in `switch` statements. It happened to work in _some_ cases, including yours, bur generally was wrong and inconsistent with corresponding `if` statements.
