### ISSUE TITLE
Store ref to namespaces not just types

### ISSUE THREAD

**Issue by ORESoftware** [Microsoft/TypeScript#28566]
I have this question on SO:
https://stackoverflow.com/questions/53330600/store-reference-to-namespace-instead-of-type

Say I have a namespace like so:

```typescript
    export namespace Foo1 {
      export namespace Foo2 {
        export namespace Foo3 {
          export interface Foo4 {}
          export interface Foo5 {}
        }
      }
    }
```

in a .ts file I have something like this:

```typescript
    import {Foo1} from './foo';
    
    const bar1 = function(){
       type t = Foo1.Foo2.Foo3.Foo4;
    }
    
    const bar2 = function(){
       type t = Foo1.Foo2.Foo3.Foo5;
    }
```

this can get kinda verbose, I am looking to do something like this instead:

```typescript
    import {Foo1} from './foo';

    type Foo3 = Foo1.Foo2.Foo3;  // <<<  this don't work, I get an error explained below
    
    const bar1 = function(){
       type t = Foo3.Foo4;
    }
    
    const bar2 = function(){
       type t = Foo3.Foo5;
    }
```

**problem**: I can't seem to store a reference to a namespace, I can only store a reference to a type? (The error I get is that namespace Foo2 has no exported member Foo3).

## Feature request

Allow .ts code to store a reference to a namespace, so that many references don't have to cite the whole path each time.

**Comment by weswigham** [comment]
> problem: I can't seem to store a reference to a namespace, I can only store a reference to a type? (The error I get is that namespace Foo2 has no exported member Foo3).

Well. Actually there's already syntax for this - `import Alias = Some.Name.Space` should work - though it may only be valid inside a namespace, I'm not sure.

**Comment by ORESoftware** [comment]
@weswigham yes that import syntax works, thanks!!
