### ISSUE TITLE
Incorrect Typing when Destructuring Arrays or Accessing values from Arrays

### ISSUE THREAD

**Issue by cjduncana** [Microsoft/TypeScript#28579]
**TypeScript Version:**  3.2.0-dev.20181116

**Search Terms:**
array destructuring
array access

**Code**

```ts
const arr: number[] = [];
const [head, ...tail] = arr;
const anotherHead = arr[0];
```

**Expected behavior:**
I was expecting `head` and `anotherHead` to be typed as `number | undefined`.

**Actual behavior:**
Instead they are both typed as `number`.

**Playground Link:** https://www.typescriptlang.org/play/index.html#src=const%20arr%3A%20number%5B%5D%20%3D%20%5B%5D%3B%0D%0Aconst%20%5Bhead%2C%20...tail%5D%20%3D%20arr%3B%0D%0Aconst%20anotherHead%20%3D%20arr%5B0%5D%3B

**Related Issues:** Haven't found a related issue.

**Comment by cjduncana** [comment]
In this example, I chose an empty array to prove my point, but in actual code, we do not know the length of the array beforehand, so accessing an element anywhere in the array is not guaranteed.

Just to be explicit, this is not an issue with arrays expressed as tuples. As far as I can tell, they are typed correctly, and `tail` is also typed correctly since it would return an empty array if it exceeds its bounds.

**Comment by cjduncana** [comment]
I noticed this when making a check to create a non-empty array, yet Typescript wasn't asking me to check for the existence of the head.

**Comment by yortus** [comment]
Is #13778 what you are looking for?

**Comment by cjduncana** [comment]
It is. I was surprised when I couldn't find a related issue.
