### ISSUE TITLE
lib.d.ts Function.bind with this

### ISSUE THREAD

**Issue by bluelovers** [microsoft/TypeScript#28571]
## Suggestion

i don't know what is better name for `ITSOverwriteThisFunction`

```ts
interface Function2 extends Function
{
	bind<T extends any, F extends (...args: any[]) => any>(this: F, thisArg: T, ...argArray: any[]): ITSOverwriteThisFunction<T, F>;
}

export type ITSOverwriteThisFunction<T extends any, F extends (...args: any[]) => any> =
	(this: T, ...args: Parameters<F>) => ReturnType<F>
```

## Use Cases

1. we can now let `fn.bind`, know who is `this`

> problem: current typescript not support overload function, so this has limit

## Examples

> this examples looks so stupid, but i don't know how to make look better

```ts
export interface t4 extends Function2
{
	(): string
}

export declare let t5: t4

export let t6 = t5.bind([] as string[])

t6 = function ()
{
	this.includes('') // => this is string[]

	return ''
}
```

## Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by DanielRosenwasser** [comment]
I'm a little bit confused over what's being suggested here, but is it covered by https://github.com/Microsoft/TypeScript/pull/27028 which is coming in TypeScript 3.2?

**Comment by bluelovers** [comment]
@DanielRosenwasser 
i think it not same, 

in t6, ts know it is string[]

but in t9 , ts didn't show error

```
export interface t4 extends Function2
{
	(): string
}

export declare let t5: t4

export let t6 = t5.bind([] as string[])

t6 = function ()
{
	this.includes('') // => this is string[]

	// ts will show error
	this.padEnd(1, '0')
	
	return ''
}

export interface t7 extends Function
{
	(): string
}

export declare let t8: t7

export let t9 = t8.bind([] as string[])

t9 = function ()
{
	this.includes('') // => this is string[]

	// ts didn't show error
	this.padEnd(1, '0')

	return ''
}
```

**Comment by DanielRosenwasser** [comment]
I think that's because you extended `Function`, so all the "wrong" methods for `bind` are present. If you remove that, TS3.2 will resolve `bind` from a new type called `CallableFunction`. Can you verify whether that works?

**Comment by bluelovers** [comment]
my version is 3.2.0-dev.20181114

```ts
export interface t10
{
	(): string
}

export declare let t11: t10

export let t12 = t11.bind([] as string[])

t12 = function ()
{
	this.includes('') // => this is string[]

	// ts didn't show error
	this.padEnd(1, '0')

	return ''
}

export interface t10
{
	(): string
}

export declare function t13()
export let t14 = t13.bind([] as string[])

t14 = function ()
{
	this.includes('') // => this is string[]

	// ts didn't show error
	this.padEnd(1, '0')

	return ''
}
```

![image](https://user-images.githubusercontent.com/167966/48611907-568fec00-e9c2-11e8-88c1-779a9418978c.png)

**Comment by RyanCavanaugh** [comment]
I can't tell what's going on here. The posted code is full of errors and I don't see which ones are supposed to be good or bad. Please open a new issue with a clear description if needed. Thanks!
