### ISSUE TITLE
Since upgrading to Typescript 3, cannot extend readonly properties anymore

### ISSUE THREAD

**Issue by FrenchHipster** [Microsoft/TypeScript#28577]
**TypeScript Version:**  3.1.6

**Search Terms:** readonly, extends

**Code**

```ts
class BaseClass {
    readonly prop = 'value';
}

class ChildClass extends BaseClass {
    readonly prop = 'othervalue';
}
```

**Expected behavior:** It should accept to change the value of a readonly property in a sub-class, which it did in Typescript 2.x.
If this is a new expected behavior, I haven't found it mentioned in the 3.0 or 3.1 Changelogs.

**Actual behavior:** It does not

**Playground Link:** [link](http://www.typescriptlang.org/play/index.html#src=class%20BaseClass%20%7B%0D%0A%20%20%20%20readonly%20prop%20%3D%20'value'%3B%0D%0A%7D%0D%0A%0D%0Aclass%20ChildClass%20extends%20BaseClass%20%7B%0D%0A%20%20%20%20readonly%20prop%20%3D%20'othervalue'%3B%0D%0A%7D%0D%0A)

**Related Issues:**

**Comment by MartinJohns** [comment]
How would this even work?

```
class BaseClass {
    readonly prop = 'value';
}

class ChildClass extends BaseClass {
    readonly prop = 'othervalue';
}

interface WithProp {
    readonly prop: 'value';
}

const val: BaseClass = new ChildClass();
const foo: WithProp = val;
```

`val` is typed `BaseClass`, and `BaseClass` has a property `prop` of the type `'value'`, so it is compatible with the interface `WithProp`. But if you allow overriding of the property with new and incompatible types this won't work anymore.

**Comment by FrenchHipster** [comment]
Thanks. We'll update our codebase accordingly.
