### ISSUE TITLE
Object spread vulnerable to prototype pollution from  __proto__

### ISSUE THREAD

**Issue by mgol** [Microsoft/TypeScript#28596]
**TypeScript Version:**  3.2.0-dev.20181117

**Search Terms:**

- `object spread __proto__`
- `object spread object.assign`

**Code**

```ts
var o = Object.create(null);
o.a = 'foo';
o.__proto__ = [];
var o2 = {...o};
console.log(Array.isArray(Object.getPrototypeOf(o2))); // true, expected: false
```

**Expected behavior:**

`false` should be logged. Object spread should not be vulnerable to `__proto__` prototype pollution.

**Actual behavior:**

It logs `true`. If you paste this code directly in a browser console it prints `false`.

This is because object spread is desugared by TypeScript to a bare `Object.assign` which behaves differently: `Object.assign` invokes property setters and object spread shouldn't (see tc39/proposal-object-rest-spread:Issues.md@master#setters for an example).

This was originally reported to Babel at https://github.com/babel/babel/issues/7382 and has since been fixed (a few months ago).

This may be important for some security contexts which is why TC39 decided to not invoke setters on object spread - `Object.assign` etc. can be monkey-patched in environments with enhances security but it's impossible to patch syntax.

**Playground Link:** https://www.typescriptlang.org/play/#src=var%20o%20%3D%20Object.create(null)%3B%0D%0Ao.a%20%3D%20'foo'%3B%0D%0Ao.__proto__%20%3D%20%5B%5D%3B%0D%0Avar%20o2%20%3D%20%7B...o%7D%3B%0D%0Aconsole.log(Array.isArray(Object.getPrototypeOf(o2)))%3B%20%2F%2F%20true%2C%20expected%3A%20false%0D%0A

**Related Issues:** 
I haven't found anything related.

**Comment by ajafff** [comment]
search terms: `spread setter`
#13668

**Comment by mgol** [comment]
Thanks, I didn't try searching via `setter`. Closing as a duplicate then.
