### ISSUE TITLE
Classes cannot satisfy Constructor<Itself> bound

### ISSUE THREAD

**Issue by prasannavl** [Microsoft/TypeScript#28593]
**TypeScript Version:**  3.2.0-dev.201xxxxx

**Search Terms:** generics mixin classes interfaces constructor

**Code**

```ts
type Constructor<T> = new(...args: any[]) => T;

interface XInterface {}
function make<T extends Constructor<XInterface>>(Base: T) {
    return class extends Base implements XInterface {}
}

// This is ok.
class X extends make(Function) { }

// But this fails.
class X2 extends make(Function) implements Constructor<XInterface> { }
```

**Expected behavior:** 
Code should compile

**Actual behavior:**
Compiler error: X2 provides no match for signature `new(...args: any[]) => XInterface`

--- 

**Edit 1:**
Looks like even something more basic like 

```ts
class Y implements XInterface, Constructor<XInterface> {}
```

fails to compile. This makes it difficult to chain together a set of mixin extending through another mixin function. 

**Edit 2**

Looks like even the simplest case of

```ts
class Y implements Constructor<Y>
```

fails.

**Comment by weswigham** [comment]
@prasannavl the `implements` clause constrains the instance shape of a class - the constructor signature of a class is associate with its static side (it returns the instance), therefore isn't constrainable via `implements`.

```ts
class X2 extends make(Function) implements Constructor<XInterface> { }
```
is saying the class X2 extends a `Constructor<XInterface>` and its instance is a `Constructor<XInterface>` - meaning that when you say `new X2()`, the result is something you can use `new` on and get an `XInterface`, which is, ofc, not the case here.

**Comment by prasannavl** [comment]
Thank you @weswigham  -- That makes a lot of sense. I feel rather silly now after reading the reply. Thanks again for taking the time to explain this! :)
