### ISSUE TITLE
Generic field not narrowed implicitly

### ISSUE THREAD

**Issue by AnyhowStep** [Microsoft/TypeScript#28592]
**TypeScript Version:**  3.2.0-dev.20181117

**Search Terms:** Generic field narrow

**Code**

```ts
export type Map = {
    [key: string]: string
};
export type Table = {
    columns: Map
};

export type TableA = {
    columns: {
        a: "hi",
        b: "bye",
    }
};
declare const tableA: TableA;
export type Columns1<TableT extends Table> = (
    TableT["columns"]
);
export type Columns2<TableT extends Table> = (
    {
        [columnName in keyof TableT["columns"]]: (
            TableT["columns"][columnName]
        )
    }
);

//OK
const columns1: Columns1<TableA> = tableA.columns;
//OK
const columns2: Columns2<TableA> = tableA.columns;

function foo<TableT extends Table>(table: TableT) {
    //OK, columns1 is now of type TableT["columns"]
    const columns1: Columns1<TableT> = table.columns;

    /*
        Error, because table.column is not of type
        TableT["columns"]. It is of type Map.

        Should it be automatically narrowed to TableT["columns"]?
    */
    const columns2: Columns2<TableT> = table.columns;
    /*
        OK, because columns1 is of type TableT["columns"]
    */
    const columns3: Columns2<TableT> = columns1;
}

```

**Expected behavior:**

`table.columns` should be of type `TableT["columns"]`

**Actual behavior:**

`table.columns` is of type `Map`

**Playground Link:** [here](http://www.typescriptlang.org/play/#src=export%20type%20Map%20%3D%20%7B%0A%20%20%20%20%5Bkey%3A%20string%5D%3A%20string%0A%7D%3B%0Aexport%20type%20Table%20%3D%20%7B%0A%20%20%20%20columns%3A%20Map%0A%7D%3B%0A%0Aexport%20type%20TableA%20%3D%20%7B%0A%20%20%20%20columns%3A%20%7B%0A%20%20%20%20%20%20%20%20a%3A%20%22hi%22%2C%0A%20%20%20%20%20%20%20%20b%3A%20%22bye%22%2C%0A%20%20%20%20%7D%0A%7D%3B%0Adeclare%20const%20tableA%3A%20TableA%3B%0Aexport%20type%20Columns1%3CTableT%20extends%20Table%3E%20%3D%20(%0A%20%20%20%20TableT%5B%22columns%22%5D%0A)%3B%0Aexport%20type%20Columns2%3CTableT%20extends%20Table%3E%20%3D%20(%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%5BcolumnName%20in%20keyof%20TableT%5B%22columns%22%5D%5D%3A%20(%0A%20%20%20%20%20%20%20%20%20%20%20%20TableT%5B%22columns%22%5D%5BcolumnName%5D%0A%20%20%20%20%20%20%20%20)%0A%20%20%20%20%7D%0A)%3B%0A%0A%2F%2FOK%0Aconst%20columns1%3A%20Columns1%3CTableA%3E%20%3D%20tableA.columns%3B%0A%2F%2FOK%0Aconst%20columns2%3A%20Columns2%3CTableA%3E%20%3D%20tableA.columns%3B%0A%0Afunction%20foo%3CTableT%20extends%20Table%3E(table%3A%20TableT)%20%7B%0A%20%20%20%20%2F%2FOK%2C%20columns1%20is%20now%20of%20type%20TableT%5B%22columns%22%5D%0A%20%20%20%20const%20columns1%3A%20Columns1%3CTableT%3E%20%3D%20table.columns%3B%0A%0A%20%20%20%20%2F*%0A%20%20%20%20%20%20%20%20Error%2C%20because%20table.column%20is%20not%20of%20type%0A%20%20%20%20%20%20%20%20TableT%5B%22columns%22%5D.%20It%20is%20of%20type%20Map.%0A%0A%20%20%20%20%20%20%20%20Should%20it%20be%20automatically%20narrowed%20to%20TableT%5B%22columns%22%5D%3F%0A%20%20%20%20*%2F%0A%20%20%20%20const%20columns2%3A%20Columns2%3CTableT%3E%20%3D%20table.columns%3B%0A%20%20%20%20%2F*%0A%20%20%20%20%20%20%20%20OK%2C%20because%20columns1%20is%20of%20type%20TableT%5B%22columns%22%5D%0A%20%20%20%20*%2F%0A%20%20%20%20const%20columns3%3A%20Columns2%3CTableT%3E%20%3D%20columns1%3B%0A%7D)

**Related Issues:**

**Comment by ahejlsberg** [comment]
This is working as intended. For reasons of backward compatibility, a property access `obj.foo`, where `obj` is of a generic type `T extends C`, is resolved to the type of the `foo` property in the constraint type `C` instead of being resolved to `T["foo"]`. Without this rule _every_ access through `this` in a class would be a generic indexed access type because `this` in a class is actually a generic type constrained to the class instance type, and that would be a large breaking change.

**Comment by AnyhowStep** [comment]
I guess I can keep using the workaround where I cast/assign the constraint type back to the generic type before using it.

I don't really lose anything and it's only one more line of code in most cases.

Thanks for the follow-up!
