### ISSUE TITLE
Argument objects instead of normal function calls

### ISSUE THREAD

**Issue by JonathanWilbur** [Microsoft/TypeScript#28600]
## Search Terms

* `arguments`
* `object`

## Suggestion

Behind the scenes, TypeScript should convert all function / method signatures to accept a single object as a parameter. This single object should contain keys that represent the arguments as passed into the function.

So something like this:

```typescript
function printName (firstName : string, lastName : string) {
    console.log(firstName + " " + lastName);
}
```

would get transpiled to this:

```javascript
function printName (__args__) {
   console.log(__args__.firstName + " " + __args__.lastName);
}
```

## Use Cases

This would allow optional arguments to come before required ones.

## Examples

This:

```typescript
function printName (salutation? : string, firstName : string, lastName : string) {
    console.log(`${salutation} ${firstName} ${lastName}`);
}
```

would **not** be invalid, because it would transpile to this:

```javascript
function printName (__args__) {
    console.log(`${__args__.salutation} ${__args__.firstName} ${__args__.lastName}`);
}
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by weswigham** [comment]
Sadly, this doesn't really check the box for
>  This feature would agree with the rest of TypeScript's Design Goals.

as it both adds expression level syntax and has the potential to conflict with upcoming js proposals (ie, named arguments).

**Comment by JonathanWilbur** [comment]
Fair enough. I will close this. Thank you!
