### ISSUE TITLE
Array methods lose types of unions

### ISSUE THREAD

**Issue by iKBAHT** [Microsoft/TypeScript#28615]
**TypeScript Version:**  3.1.6 and 3.2.0-dev.20181117

**Code**

```ts
interface ISortable {
  id: number;
}
type EventId = string | number | ISortable;

const eventIds: Array<EventId> = [];

eventIds.sort(sortEventIds);     // must be error here
eventIds.filter(filterEventIds); // and here

function sortEventIds(a: number, b: number): number {
  return a - b;
}

function filterEventIds(a: number): boolean {
  return a % 2 === 0;
}
```

**Expected behavior:**
Compiler error like:
`Argument of type '(a: number, b: number) => number' is not assignable to parameter of type '(a: EventId, b: EventId) => number'`

**Actual behavior:**
No any error

**Playground Link:** 
[Link](https://www.typescriptlang.org/play/#src=interface%20ISortable%20%7B%0D%0A%20%20id%3A%20number%3B%0D%0A%7D%0D%0Atype%20EventId%20%3D%20string%20%7C%20number%20%7C%20ISortable%3B%0D%0A%0D%0Aconst%20eventIds%3A%20Array%3CEventId%3E%20%3D%20%5B%5D%3B%0D%0A%0D%0AeventIds.sort(sortEventIds)%3B%0D%0AeventIds.filter(filterEventIds)%3B%0D%0A%0D%0Afunction%20sortEventIds(a%3A%20number%2C%20b%3A%20number)%3A%20number%20%7B%0D%0A%20%20return%20a%20-%20b%3B%0D%0A%7D%0D%0A%0D%0Afunction%20filterEventIds(a%3A%20number)%3A%20boolean%20%7B%0D%0A%20%20return%20a%20%25%202%20%3D%3D%3D%200%3B%0D%0A%7D%0D%0A)

**Related Issues:** 
I can't find bugs that looked similar

**Comment by j-oliveras** [comment]
In playground, enabling `strictFunctionTypes` I see these errors:
```
Argument of type '(a: number, b: number) => number' is not assignable to parameter of type '(a: EventId, b: EventId) => number'.
  Types of parameters 'a' and 'a' are incompatible.
    Type 'EventId' is not assignable to type 'number'.
      Type 'string' is not assignable to type 'number'.
```
```
Argument of type '(a: number) => boolean' is not assignable to parameter of type '(value: EventId, index: number, array: EventId[]) => any'.
  Types of parameters 'a' and 'value' are incompatible.
    Type 'EventId' is not assignable to type 'number'.
      Type 'string' is not assignable to type 'number'.
```

**Comment by iKBAHT** [comment]
Sorry, I didn't know about this flag. @j-oliveras thank you.
