### ISSUE TITLE
ArrowFunction incorrectly introduces 'arguments' local symbol

### ISSUE THREAD

**Issue by ajafff** [Microsoft/TypeScript#28621]
**TypeScript Version:**  3.2.0-dev.20181110

**Search Terms:** arrow arguments

**Code**

```ts
(() => arguments)();
```

**Expected behavior:**

There's no `arguments` in scope, emit error `cannot find name 'arguments'`.

**Actual behavior:**

No compiler error. Crashes at runtime.

**Playground Link:** https://agentcooper.github.io/typescript-play/#code/BTCUAIF4D5wQwE4HMCuBbApgOwC4GdQwg

I can send a PR if you accept this bug as I'm already looking at the relevant code.

**Comment by DanielRosenwasser** [comment]
Thanks!

**Comment by iamolegga** [comment]
Seems like still not fixed

http://www.typescriptlang.org/play/?ts=3.7-Beta#code/BTCUAIF4D5wQwE4HMCuBbApgOwC4GdQwg
